### ISSUE TITLE
"Push exceeded 100MB limit" however I don't have any files over 100 MB?

### ISSUE THREAD

**Issue by daniellochner** [desktop/desktop#10006]
Hi there,

GitHub desktop continually says I cannot push since there is a file exceeding 100 MB, however as you can see in the attached screenshot, there are none besides the .git packs? Is this the issue?

![100mb-bug](https://user-images.githubusercontent.com/37551307/84687400-fa929e00-af3d-11ea-90f2-016def3b9fc7.png)

Thanks,
Daniel

**Comment by steveward** [comment]
@daniellochner is it possible that you previously committed a file over 100MB? GitHub Desktop will notify you if you attempt to commit a large file, but if the file was previously committed then it will need to be removed from the repository's history. There's a guide for how to remove large files here:

https://help.github.com/en/github/managing-large-files/removing-files-from-a-repositorys-history

Once you remove the large file you should be able to push your changes. Let me know if you have any questions about this process.

**Comment by daniellochner** [comment]
It worked! Thank you so so so (so) much! I can't tell you how much I appreciate the help! Been struggling with some AdSense nonSense and I've had with all the bots and help centers...

Thanks again! :)
