### ISSUE TITLE
ctrl + c No longer exits a process in cmd.exe

### ISSUE THREAD

**Issue by 2JJ1** [desktop/desktop#10001]
### Describe the bug

ctrl + c No longer exits a process in cmd.exe

### Version & OS

Version 2.5.2
Windows 10 Home

### Steps to reproduce the behavior

1: Open a repository in Github Desktop
2: Press ctrl + ` to launch the console in the repository's directory
3: Run the command, > ping -t google.com
4: Press ctrl + c to attempt to cancel the ping process

### Expected behavior

The ping should cancel

### Actual behavior

The ping does not cancel

### Additional context

If I open the command prompt from the Windows search bar and manually navigate to the repository's directory, I can close the process as expected. ctrl + c cancels the ping as mentioned in the reproduction example above.

The issue is not limited to the ping process. I can't do it for any process that I've started. Like starting my Node.js app with the nodemon package or the plain node command. E.g "nodemon index.js" or "node index.js"

**Comment by tierninho** [comment]
@2JJ1 Thank you for filing the issue. I tried to reproduce this but no luck. 😕 

Also, once you leave Desktop to go to the command line, any issues that arise in the command tool are unlikely to be the rooted in Desktop as they are two separate applications. Please advise if there a nexus I am missing here? 

Your logs may include some clues, so please share if you can. See the Help menu in Desktop.

**Comment by 2JJ1** [comment]
The issue seems to have corrected itself after I restarted my computer a few times. I can't think of any other useful information. I'll be more cautious of information to collect if this happens again.
