### ISSUE TITLE
[SMALL ENHANCEMENT] 'Projects' Automation

### ISSUE THREAD

**Issue by Savvasun** [desktop/desktop#10007]
### The project windows on the repo

Right now, the 'community' project on the repo has three columns like 'To Do', 'In Progress', and 'Done', but they aren't automated, which means more confusing to look at from a distance since automation adds many features that make the window more organized.

### Proposed Solution

This will benefit people working on this project/repo and will improve efficiency. I think it can be fixed by clicking the three dots on top of each column and clicking a button that says something similar to 'manage automation', and then configuring each one.

**Comment by tierninho** [comment]
@Savvasun Thanks for the tip on automating projects! 

As our processes require a lot of discussion and shifting priorities (especially in the context of today), we require the flexibility of manually moving our tickets around the Projects board. At this time, full automation may not be the right solution. We do use some automation now and will slowly ramp up as needed.

If there is anything that you found particularly confusing or you think we could improve on with some minor tweaks, please reach out again.
