### ISSUE TITLE
About GitHubDesktop's install path

### ISSUE THREAD

**Issue by Champion-Lai** [desktop/desktop#10000]
### In Windows 10, I want to choose the app's install path

Could you modified the app,let users customizable install path.

### Proposed solution

This modification will make users more like GitHub Desktop.

**Comment by steveward** [comment]
Thanks for contributing @Champion-Lai. Currently it is not possible to customize the installation location of GitHub Desktop. This is a constraint in the installation framework we use, Squirrel.Windows (see https://github.com/Squirrel/Squirrel.Windows/issues/314). At this time we do not have plans of changing the installer we use for GitHub Desktop.

**Comment by munichjake** [comment]
Commenting on a closed issue. 
For Atom, which suffers from the same lack of enterprise usability, there was a ZIP offered with all the files that are needed, which I was able to deploy via Powershell, or package in my own way. In my case, I used InnoSetup.
For GitHub Desktop however, I cannot find such a release, only the "MSI" (which is just a Faux, that doesn't support proper installing or uninstalls) and the regular setup.exe. I tried to unpack the Exe file using 7-Zip, but it was only a downloader inside.
Is there such a ZIP file for GitHub like for Atom?

**Comment by steveward** [comment]
@munichjake a helpful GitHub Desktop user took the initiative to package GitHub Desktop as a portable application:

https://github.com/daemondevin/GitHubDesktopPortable

Please note that this is not officially supported by GitHub, but it should work without issue. I hope that helps!
