### ISSUE TITLE
github desktop .exe or .msi doesnt install in windows 7 32bit 

### ISSUE THREAD

**Issue by ozzie786** [desktop/desktop#10015]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
At this time GitHub Desktop only supports 64-bit versions of Windows.

There is another GitHub Desktop user who put together an experimental 32-bit build of the current version GitHub Desktop -- see [this comment](
https://github.com/desktop/desktop/issues/6874#issuecomment-524081839) for how to build that if you are interested.
