### ISSUE TITLE
Show Check Status at a Commit Level in History

### ISSUE THREAD

**Issue by nileshr** [desktop/desktop#10014]
### Describe the feature or problem you’d like to solve

Currently, we can only see the status of checks only for the latest commit next to the branch but when we open History, there is no indication of the checks at the commit level. This is something that's available on GitHub web version and I've included a screenshot of it below.

![image](https://user-images.githubusercontent.com/1647344/84756223-25cdc980-afe0-11ea-88ad-5d9e19446c0b.png)

### Proposed solution

This will benefit Desktop and its users by not having to visit the GitHub website to view the checks at a commit level. Also this would be useful to see checks for branches that don't have a PR open (including the default branch)

### Additional context

This is how it currently looks in the desktop commit history.

![image](https://user-images.githubusercontent.com/1647344/84757417-c07ad800-afe1-11ea-9efe-ed4b90d7bd1a.png)

**Comment by billygriffin** [comment]
Hi @nileshr, thanks so much for the idea! We discussed this internally, and unfortunately getting each of those statuses would mean fetching quite a lot of data from the API. We do show the status of the last commit on PRs, and based on what we've heard that provides the most value. Given how significant this would be in terms of load on the API, and the fact that we haven't heard it come up as solving a major problem, I'm going to close this to indicate the costs outweigh the benefits. Thanks so much again and we appreciate you sharing the request in such detail. ❤️
