### ISSUE TITLE
i am login to my github account through github desktop but unable to commit any thing on github, it is giving the following error

### ISSUE THREAD

**Issue by sharxxxx** [desktop/desktop#10018]
Commit failed - exit code 128 received, with output: '*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'hp@hp-PC.(none)')'

**Comment by steveward** [comment]
@sharxxxx thanks for the report. It looks like you need to set your name and email in your .gitconfig by going to `File` > `Options` > `Git`. That should get things working and allow you to commit. Let me know if that does not get things working.

**Comment by sharxxxx** [comment]
Yes its working now, thanks brother

**Comment by DIPUL2001** [comment]
in which file i need to go remove the error

**Comment by davesmiths** [comment]
Just wanted to say this happened to me today.

I had version 2.6.2 on MacOS 11.1

To fix I followed the above instructions by @steveward using GitHub > Preferences > Git , edited the name and email, and saved.

I was able to commit again.
