### ISSUE TITLE
publish release files to GitHub releases

### ISSUE THREAD

**Issue by bbodenmiller** [desktop/desktop#10029]
### Describe the feature or problem you’d like to solve

I need the ability to download GitHub Desktop releases from https://github.com/desktop/desktop/releases because I have enterprise mechanism to download from GitHub releases not random websites like https://desktop.github.com/

### Proposed solution

Publish release files to https://github.com/desktop/desktop/releases

Also is good example of actually using GitHub for it's intended features rather than other solutions... after all you are GitHub you should use your own features.

**Comment by billygriffin** [comment]
Hi @bbodenmiller, thanks for the issue! This is the first time we've heard this request, and a wide variety of Enterprise users are using GitHub Desktop without issue today. Also, desktop.github.com is a subdomain of github.com, not just a random website. I'm going to close this as something we likely won't be able to prioritize, but I'd love to understand if you are actually unable to download Desktop from the website for some reason.

**Comment by bbodenmiller** [comment]
@billygriffin my issue is that enterprise policy does not allow downloads from the internet outside of certain white listings. White listing GitHub release pages is much easier than other locations. I'm would expect GitHub would want to dogfood it's own products but I guess not.
