### ISSUE TITLE
GitHub Desktop for Linux cannot update OAuth permission

### ISSUE THREAD

**Issue by danielb987** [desktop/desktop#10028]
The [JMRI](https://github.com/JMRI/JMRI) project requires GitHubDesktop to have the OAuth permission `Update github action workflows`. But neither the GitHub Desktop for Linux application, nor the GitHub website, allows me to add that permission. Therefore it's impossible for me to use GitHub Desktop for Linux to merge from upstream/master when workflow files are changed.

**Comment by tierninho** [comment]
At this time there are no official builds of GitHub Desktop available for Linux, but a former developer of GitHub Desktop helps maintain a fork with Linux builds with limited support:

https://github.com/shiftkey/desktop/releases

Please post the statement there and hopefully someone can advise. Thank you!
