### ISSUE TITLE
"Open with Desktop" missing from Firefox after restoring Github Desktop files from backup, even after reinstall

### ISSUE THREAD

**Issue by MostHated** [desktop/desktop#10024]
### Describe the bug
Ever since I had the issue seen in #9954 I restored the Github Desktop files from backup in order to get the database of repos added back to my list, but ever since the "Open in Desktop" button if my browser is missing. It is getting frustrating having to paste ```x-github-client://openRepo/``` in front of the url to clone it and I can't find info on how to restore the button. I tried redownloading Github Desktop and reinstalling it over my current install, which kept my DB list intact, but didn't fix the button.

Does anyone have any recommendations?

### Version & OS
Windows 10 Pro 2004
Github Desktop Version 2.5.2
Firefox 77.0.1 (64-bit)

**Comment by tierninho** [comment]
Thanks @MostHated for the issue. I am gonna wrap this one up with https://github.com/desktop/desktop/issues/10010 as they are the same issue, just different browsers.

**Comment by MostHated** [comment]
Well, with my issue, it's not that the Open in Desktop button doesn't work, there is no Open in Desktop button at all.

**Comment by tierninho** [comment]
Noted and thanks. Will add that detail. Any chance you could add a screenshot as I am not seeing a missing button in Windows, nor Mac?

**Comment by MostHated** [comment]
Here is a screen of it.

![](https://i.imgur.com/GA6yjnl.png)

**Comment by MostHated** [comment]
I thought that it might be worth noting that I just installed the newer Firefox 78.0b9 (64-bit) Developer edition for the first time, and unfortunately the Clone with Desktop button is still nonexistent.
