### ISSUE TITLE
never ending requests for authorization

### ISSUE THREAD

**Issue by timpiperseek** [desktop/desktop#10033]
### Describe the bug
I keep getting requested to with the following message and no matter how many times I give it authorizition it keeps asking for permission.

"the organisation has enabled or enforced SAML SSO. TO access this repository, you must sign in again and grant github desktop permission to access the organisation repositories.  Would you like to open a browser to grant github desktop permission to access this repository"

### Version & OS

Version 2.5.2
Windows 10

[2020-06-18.desktop.production.log](https://github.com/desktop/desktop/files/4795720/2020-06-18.desktop.production.log)

**Comment by tierninho** [comment]
@timpiperseek Thanks for filing and apologies for the troubles. Did you attempt to log in to your account via `File > Options > Accounts` in GitHub Desktop? You won't be able to authenticate via the Authentication failed dialog.

**Comment by timpiperseek** [comment]
okay that seems to work thank you
