### ISSUE TITLE
Enable non-versioned folders to be Gitable

### ISSUE THREAD

**Issue by FANMixco** [desktop/desktop#10031]
### Describe the feature or problem you’d like to solve

From time to time, I start working some small apps or projects from scratch, and later, I need to commit the changes to GitHub, BitBucket, etc. My general approach is to:

1. Clone the new repo.
2. Move all my projects there.

This is not exactly the most optimal solution because if the projects are huge, then, it takes a lot of time.

### Proposed solution

When a new repo is cloned from X or Y URL, beyond checking if the folder is empty or not, GitHub for desktop should check if the chosen folder doesn't contain a .git or other versioning system folder. If they don't exist, copy the git configurations from the repository.

**Comment by steveward** [comment]
@FANMixco apologies for not responding to this sooner. 

If you want to add a new local project that is not yet a repository you _can_ add it to GitHub Desktop. You will be prompted to initialize it as a new repository. If you want to add project files to an existing remote repository then you would need to clone the existing repository and add the project in File Explorer or Finder. You can then commit those changes in GitHub Desktop and push them back to the remote repository.

GitHub Desktop does support working with third-party Git hosts. See these guides:

https://github.com/desktop/desktop/tree/development/docs/integrations

I'm going to close this out, but let me know if I'm misunderstanding your request and can clarify anything further.
