### ISSUE TITLE
Encounter Error: spawn on GitHubDesktop

### ISSUE THREAD

**Issue by veenahegane96** [desktop/desktop#10042]
![image](https://user-images.githubusercontent.com/67143427/85111691-4ee59880-b232-11ea-9fd0-c28fec95b94f.png)

Unable to access visual code from GitHubDesktop due to following error:
Error: spawn C:\Windows\system32\cmd.exe; ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

Version: 2.5.0
OS: Windows 10.0.18362

Please help me solve this

**Comment by steveward** [comment]
Thanks for the report @veenahegane96. Just to clarify -- is this error only occurring when you attempt to launch Visual Studio Code from GitHub Desktop (i.e. `Repository` > `Open in Visual Studio Code`)?

Could you open the command prompt and share the output of `echo %PATH%`?

**Comment by veenahegane96** [comment]
Yes, the error occurs only while opening the Visual Studio Code. Here is the output for echo %path%

![image](https://user-images.githubusercontent.com/67143427/85254165-4634d280-b47d-11ea-923a-a8a6b21a80f7.png)

**Comment by veenahegane96** [comment]
Hey @steveward 
 I am facing another similar issue when I am building a package in node through npm run build. Are they related to some common issues?

![image](https://user-images.githubusercontent.com/67143427/85315579-eff57d00-b4d8-11ea-9b84-0718d4c2b711.png)

**Comment by steveward** [comment]
@veenahegane96 it looks like `System32` is not in your PATH, which is why you are seeing that ENOENT error. You should be able to run this command to resolve the issue:

`pathman /au C:\Windows\system32`

Let me know if that doesn't get things working!
