### ISSUE TITLE
Cloning from GitHub

### ISSUE THREAD

**Issue by mr5z** [desktop/desktop#10044]
### Describe the bug

Cloning a repository directly from GitHub does not seem to work as I expected.

### Version & OS

Version 2.5.2, Windows 10

### Steps to reproduce the behavior

1. Click the "repository selector".
2. Click on "Add".
3. Select "Clone repository...".
4. Select the tab GitHub.com
5. Enter the git url repo you just copied from this website.
6. See error.

### Expected behavior

I'm expecting it to find the git url I entered.

### Actual behavior

An error message will be displayed saying it can't find the repository.

### Screenshots

![Annotation 2020-06-19 232723_LI](https://user-images.githubusercontent.com/6318395/85151600-8ed66b00-b286-11ea-976e-2937d6e18e50.jpg)

### Logs

NA

### Additional context

NA

**Comment by mr5z** [comment]
Okay. I just realized what that tab is supposed to do. Maybe dropping the **.com** from the tab name would make me realize we're not supposed to put URLs there since **.com** is always associated with URLs.

**Comment by tierninho** [comment]
Thanks for the update, glad you figured it out. Yes, the URL tab is to paste repository urls and the Github.com tab will load all your repositories. Not sure if we will drop the .com part as it helps differentiate between Enterprise.
