### ISSUE TITLE
I have 2 accounts of GitHub. I make a login with one of them but I have my repositories in the another account. What can I do.

### ISSUE THREAD

**Issue by Perramus21** [desktop/desktop#10048]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@Perramus21 at this time GitHub Desktop does not support multiple GitHub accounts (see https://github.com/desktop/desktop/issues/3707) -- you will need to log out and then log in to your different accounts depending on which repositories you are wanting to work with.
