### ISSUE TITLE
Can't able to install GitHub Desktop on my windows 10 

### ISSUE THREAD

**Issue by EzhilYaali** [desktop/desktop#10047]
### Describe the bug

A clear and concise description of what the bug is i can't able to install GitHub desktop on my windows 10 machine. Previously i was using it. From morning it was not opening so i have planned to reinstall it. I have uninstalled and try to reinstall it. But it was not successfully installed.

### Version & OS

I am using windows 10 tried to install latest version of GitHub desktop.

### Steps to reproduce the behavior

1. Uninstall GitHub Desktop
2. Download latest version
3. Reinstall it.

When 

![image](https://user-images.githubusercontent.com/66666858/85193476-8ca3f900-b2e6-11ea-8e00-e5bd81afc4f6.png)

### Expected behavior
It was not successfully installed

### Logs

There is no logs

**Comment by steveward** [comment]
Thanks for the report @EzhilYaali. Could you try performing a fresh installation of GitHub Desktop by following these steps?

1. Open File Explorer
2. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
3. Go to `MondayppData%` and delete the `GitHub Desktop` directory
4. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that doesn't get things working.

**Comment by steveward** [comment]
Closing this issue out due to inactivity @EzhilYaali. Let me know if you are still having issues.
