### ISSUE TITLE
Git returned an unexpected exit code '3221225478' which should be handled by the caller.'

### ISSUE THREAD

**Issue by Salman-Moin** [desktop/desktop#10043]
### Describe the bug
created a local repository, perform first commit and then selected publishing repository while selected the path. after sometime received the above error.

### Version & OS
GIT Desktop 2.5.2 & Windows7

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Go to 'create local repository'
2. Click on 'enter initial commit'
3. Click on 'publishing repository' 
4. Given the required path and the desc of the repository.
5. Click on 'publishing repository'
6. Received the above error

### Expected behavior
repository should be published to Github

### Actual behavior
got error during publishing of repository from Github Desktop to Github

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the report @Salman-Moin. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by Salman-Moin** [comment]
pfa

**Comment by tierninho** [comment]
@Salman-Moin Please use the web interface to attach your logs. They will not attach via email. Thanks

**Comment by Salman-Moin** [comment]
[](url)
[2020-06-20.desktop.production.log](https://github.com/desktop/desktop/files/4807475/2020-06-20.desktop.production.log)

**Comment by tierninho** [comment]
@Salman-Moin Thanks for sharing the logs. It looks like you are have some issues with the install based on the exit code error, and with fetching. 

```
2020-06-20T06:25:33.468Z - warn: [ui] getFetchPollInterval: failed for salman-moin/Hooks_Counter
TypeError: Failed to fetch
```

```
unexpected exit code '3221225478' which should be handled by the caller.'
```

Can you verify you are logged in? Go to File > Options to check.

Also, Antivirus software can sometimes prevent GitHub Desktop from installing correctly. If you are running antivirus software that could be causing this try temporarily disabling it and reinstalling GitHub Desktop.

If none of these potential causes are present on your machine, try performing a fresh installation of GitHub Desktop to see if that gets things working again. Here are the steps you can take to do that:

Close GitHub Desktop
Delete the `%AppData%\GitHub Desktop\` directory
Delete the `%LocalAppData%\GitHubDesktop\` directory
Reinstall GitHub Desktop from desktop.github.com
