### ISSUE TITLE
Github Desktop keeps on telling me that I don't have write access, even though I do

### ISSUE THREAD

**Issue by Razboy20** [desktop/desktop#10040]
### Describe the bug

At the bottom right, Github Desktop tells me that "I don't have write access to <my repository>", even though I am a contributor to the repository. When I switch to a different branch and come back, the issue resolves itself, but it comes back at some later time to bug me again. 

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

Fork a Github Repository that you are not a collaborator in/don't have write access to, gain access to that repository, change git link to there and voila. 

### Expected behavior

Message does not pop up above the commit button.

### Actual behavior

Message does pop up.

### Screenshots

![image](https://user-images.githubusercontent.com/29903962/85080300-6ff4ad80-b18e-11ea-9bd9-9706208032e5.png)

**Comment by tierninho** [comment]
@Razboy20 Thank you for the issue. The current logic is set to show such a notice if you do not have write access per https://github.com/desktop/desktop/issues/8548.

I am not sure about our intention when it comes to collaborators. cc @billygriffin for clarity on our intentions here. 

I am curious if this is this blocking you from your work or just a nuisance?

**Comment by Razboy20** [comment]
It's just a nuisance. I can still commit to the repository.
I'm going to close this issue as well since I don't have much more information for you.

**Comment by tierninho** [comment]
Not a problem for us to look into as your experience and thoughts matter to us. I hope to circle back soon with some more information. Thank you for your patience.

**Comment by MikeCPD** [comment]
Estou tentando da um PUSH em uma alteração que fiz pelo GITHUB DESKTOP, porem ao efetuar o o push, aparece a mensagem
the repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.
Bom não foi deletado nem renomeado, e sim eu tenho acesso, porq consigo fazer o PUSH por via comando no GIT BASH

ainda me pergunta se quero fazer um fork, porem não quero, preciso enviar direto pra main.
