### ISSUE TITLE
Malformed launch arguments received

### ISSUE THREAD

**Issue by SteveRMann** [desktop/desktop#10059]
### Describe the bug

Tried to create a tutorial repository.
### Version & OS

GitHub Desktop Version 2.5.2, Windows 10

### Steps to reproduce the behavior
Click on Create Tutorial Repository

### Actual behavior
Error message:
Failed creating the tutorial repository.
You already have a repository named "desktop-tutorial" on your account at GitHub.com.
Please delete the repository and try again.

So, I go to my github.com page and delete the repository.

And when I go back to the desktop app, I get this error:

Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.

### Logs

[2020-06-22.desktop.production.log](https://github.com/desktop/desktop/files/4815565/2020-06-22.desktop.production.log)

**Comment by tierninho** [comment]
@SteveRMann Thank you for the issue. It looks like you solved the tutorial error correctly.

As for this error in the logs:

```
2020-06-22T20:30:49.517Z - error: [main] Malformed launch arguments received: C:\Users\steve\AppData\Local\GitHubDesktop\app-2.5.2\GitHubDesktop.exe,--squirrel-firstrun
```

It looks to be a bad install. Here are the steps to reinstall:

Close GitHub Desktop
Delete the `%AppData%\GitHub Desktop\` directory
Delete the `%LocalAppData%\GitHubDesktop\` directory
Reinstall GitHub Desktop from desktop.github.com

Hope this helps! Let us know.

**Comment by tierninho** [comment]
As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by SteveRMann** [comment]
Followed the reinstall steps above, and got this error:

"Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account."

**Comment by tierninho** [comment]
Thanks for the update. Possible to attach your logs again?

**Comment by SteveRMann** [comment]
There's two logs. I suspect the smaller one is from the most recent startup of github desktop.
[2020-06-29.desktop.production.log](https://github.com/desktop/desktop/files/4849333/2020-06-29.desktop.production.log)
[2020-06-30.desktop.production.log](https://github.com/desktop/desktop/files/4849334/2020-06-30.desktop.production.log)

**Comment by tierninho** [comment]
Could be as simple as signing out and signing back in as I spotted another similar issue and that worked: https://github.community/t/github-desktop-new-install-no-repos-error-bad-credentials/2659/2

- Another cause could be registry entries. Could you walk through the ["Authentication errors due to modified registry entries"](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#authentication-errors-due-to-modified-registry-entries) section of our known issues document to see if that could possible be causing this error on your machine?
