### ISSUE TITLE
Auto Logout

### ISSUE THREAD

**Issue by dsantos1961** [desktop/desktop#10065]
### Describe the bug

There is no auto logout in github desktop. 
This is a absolut security leak.

Any user that work on my PC is auomatic logged in an have access to my Code.

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@dsantos1961 thanks for the feedback. Logging out of GitHub Desktop would still give access to any local repositories that you have on disk. It's best to practice principles of securing your local user account (strong user password, locking your machine, etc.) if you are in a situation where other users could access your machine.

**Comment by bovlb** [comment]
I mentor a high school robotics team.  We have a pool of shared laptops, and everyone has read access to all the code, but I want people to use their own accounts when pushing changes upstream.  Autologout would work well for us.
