### ISSUE TITLE
Search box inside the changes section of the github desktop client.

### ISSUE THREAD

**Issue by HilalRather** [desktop/desktop#10063]
### There should be a textbox for searching functionality where a user can enter the name or the type of file and the list should be updated as per the value entered into the textbox.

I have hundreds of files in the list that has some kind of changes, and I don't need to commit them all. So, I am facing a problem, and its very time consuming to find and check manually the required files that I need to upload.
Now let us assume that an end-user has thousands of files and he just wants to upload a few of them, So for them, it would be a frustrating task and very time consuming to find and check them manually and commit those files.

### I think there should be a textbox for searching functionality where a developer can enter the name or the type of file and the list should be updated as per the value entered into the textbox. Like, I want only those files in the list that have .cs as an extension, So I will type .cs in the search textbox and the list will be updated with only .cs files. By default, the list will bring all the files that have any kind of change as it is right now, only should be updated whenever a user enters any text inside the search textbox.
![image](https://user-images.githubusercontent.com/19794465/85377907-6638c480-b557-11ea-8413-1a548fb1f990.png)

**Comment by steveward** [comment]
Thanks for the feedback! We are tracking this feature in #6407 -- you can follow along there for updates.

**Comment by HilalRather** [comment]
@steveward, May I know what's taking you guys too long time to implement this?

Thanks.
