### ISSUE TITLE
Push Origin button should be renamed Push to Origin

### ISSUE THREAD

**Issue by SvitlanaMo** [desktop/desktop#10061]
### Describe the feature or problem you’d like to solve

Name of the blue **Push Origin** button is misleading. It is a _jargon_.

### Proposed solution

The button should be renamed **Push to Origin**. 
It is much more understandable _plain English_. 

### Additional context

A screenshot:

![image](https://user-images.githubusercontent.com/65708333/85369448-ccaceb00-b535-11ea-81e6-d60671b6b384.png)

**Comment by steveward** [comment]
Thanks for the feedback @SvitlanaMo. This button description is intended to mirror the Git command `git push origin`, and as a result this is something we do not have plans to change. The light blue informational box also provides further details about what the command does. Thanks for using GitHub Desktop!
