### ISSUE TITLE
Merge commits function is not supported

### ISSUE THREAD

**Issue by Neustradamus** [desktop/desktop#10072]
### Describe the feature or problem you’d like to solve

1/ We do a commit:
- https://i.ibb.co/zZM12Cs/github-screenshot-ticket-9981-and-1644-1.png

2/ After push origin (we can escape this step)
- https://i.ibb.co/fX0kwGQ/github-screenshot-ticket-9981-and-1644-2.png

3/ Go history tab:
- https://i.ibb.co/W5pX9tx/github-screenshot-ticket-9981-and-1644-3.png

4/ Right click on last commit (it is like all commits) or other commits:
- https://i.ibb.co/Tb3qpS1/github-screenshot-ticket-9981-and-1644-4.png

No merge possibility, we launch git in command line in the repository folder:
`git log` to know the hash of commits

Take the HASH of the previous commit of all commits that you want to merge.
`git rebase -i PREVIOUS_HASH`

A window appears, we replace "pick" by "s" except the first one (the base), then we save the file, and close the window, we wait some seconds

A new window appears, we choice a title and a description for the new merged commit, then we save the file, and close the window, in GitHub Desktop we have:
- https://i.ibb.co/djTJ2T6/github-screenshot-ticket-merge-commits-request-5.png

Warning do not click on "Pull origin"!

Go in command line, repository folder, and do:
`git push -f`

Now we can see in GitHub Desktop:
- https://i.ibb.co/QYpPdXx/github-screenshot-ticket-merge-commits-request-6.png

All steps are here.

Thanks in advance and for your comprehension.

### Proposed solution

Add the possibility.

### Additional context

Please read previous parts.

**Comment by billygriffin** [comment]
Thanks for this idea. This feels too specific a workflow (though we are planning to work on things to make overall merging and comparing a bit easier) and likely wouldn't be used by a broad cross-section of our users, so I'm going to close it. Really appreciate the issue.
