### ISSUE TITLE
Investigate new CI solutions

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#10086]
### Describe the feature or problem you’d like to solve

Using Circle CI and Appveyor for our builds slows down our release process.

### Proposed solution

Investigate moving to GitHub Actions for our CI.

**Comment by say25** [comment]
In https://github.com/desktop/desktop/pull/9680 we removed Circle CI and Appveyor

**Comment by billygriffin** [comment]
Nice find @say25!!
