### ISSUE TITLE
Window Maximization doesn't respect minwidth

### ISSUE THREAD

**Issue by rcmaehl** [desktop/desktop#10097]
### Describe the bug

The github desktop can be maximized smaller than minwidth.

### Version & OS

Version 2.5.3
Microsoft Windows [Version 10.0.18362.900]

### Steps to reproduce the behavior

1. Set one monitor to a thin width resolution (e.g. 900x1440)
2. Maximize the window on that monitor

### Expected behavior

Window respects minwidth as set in https://github.com/desktop/desktop/blob/58af53bf0ca8fb7d053bb68d6a2bef6413cfe4fd/app/src/main-process/app-window.ts#L21

### Actual behavior

Window is resized below minwidth

### Logs

N/A

### Additional context

This is likely an upstream bug as it's reproducible with Discord Desktop (also Electron). I've opened [electron/issues/24336](https://github.com/electron/electron/issues/24336), but perhaps there's a workaround you can implement.

**Comment by tierninho** [comment]
@rcmaehl Thank you for filing this. Gonna label it as a bug while we wait for a fix from Electron. If we get time to implement a workaround, we will update this

**Comment by daniporr** [comment]
I think this is now (unfortunately, see #14286) solved in the latest version.
