### ISSUE TITLE
Delete my account 

### ISSUE THREAD

**Issue by FrancesM13** [desktop/desktop#10090]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@FrancesM13 you can find how to delete your GitHub account [here](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/deleting-your-user-account#delete-your-user-account). For reference this issue tracker is for GitHub Desktop, for questions about GitHub please contact [GitHub Support](https://support.github.com/).
