### ISSUE TITLE
Fatal: the remote end hung up unexpectedly on creating large file

### ISSUE THREAD

**Issue by mbartlett21** [desktop/desktop#10099]
### Describe the bug

When pushing a large file commit to github (creating the file), it gives an error:
```shell
Enumerating objects: 4, done.                                                   
Counting objects: 100% (4/4), done.                                             
Delta compression using up to 4 threads
Compressing objects: 100% (3/3), done.                                          
Writing objects: 100% (3/3), 1.21 MiB | 1.19 MiB/s, done.                       
Total 3 (delta 0), reused 0 (delta 0)
remote: fatal: early EOF        
error: RPC failed; curl 56 Failure when receiving data from the peer
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
Everything up-to-date
```

### Version & OS

Version 2.5.3

### Steps to reproduce the behavior

1. Create a large file in a repo that is synced to github and commit it.
2. Click Push origin
3. Wait a while and it comes up with the error

### Expected behavior

It to sync properly.

### Actual behavior

Instead, it didn't sync and showed the error

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

See file at https://github.com/mbartlett21/bible_databases/blob/master/lua/t_dby.lua for the file

**Comment by tierninho** [comment]
@mbartlett21 Thanks for filing this issue. We had a similar report to this in #3695, which we traced to a firewall interfering with the clone operation for a specific repository, which I think is what's happening here. Do you have a firewall installed?

**Comment by mbartlett21** [comment]
@tierninho 
Yes, I do have a firewall.

**Comment by tierninho** [comment]
Please disable it and attempt the clone again. If there are any issues, let us know and we will happy to reopen the issue and investigate more.

**Comment by tnkillen** [comment]
I am having this issue and disabling the firewall did not solve this problem. My situation is identical to this one. I am attempting to do 3 pushes (merge commit) of large files of unreal engine 4 and c++

**Comment by chillenious** [comment]
Same here (Unreal, large binary files). But same push via the command line client worked, so it seems the issue is with the desktop client.

**Comment by Ethshaam** [comment]
I have installed git lfs as that is what was recommended to me, so i tried to push the origin up on the command line but i'm still getting the same error as the people above. Any tips would be greatly appreciated. The error code and screen shots are below. I am getting the same issue for both github desktop and github from the terminal. 
![Screenshot 2021-05-04 at 09 33 14](https://user-images.githubusercontent.com/52074540/116978546-c215c300-acbb-11eb-9271-ae46da0948db.png)

**Comment by chillenious** [comment]
@Ethshaam just an idea (since that was my problem a bit back), make sure you have a proper `.gitattributes` file so that the right files are actually pushed out as lfs. Like the one described here: https://stefanperales.com/blog/unreal-engine-4-and-git-lfs/
