### ISSUE TITLE
Authentication Failed - Github Desktop Ubuntu

### ISSUE THREAD

**Issue by vin-fandemand** [desktop/desktop#10094]
### Describe the feature or problem you’d like to solve

Trying to clone a private repo from my organization. On entering the user name and password,  I get a pop up saying "Authentication failed We were unable to authenticate with github.com. Please enter your username and password to try again."

### Additional context

I am using the Ubuntu distribution. I am able to clone my own repos and public repos from my org.  

![image](https://user-images.githubusercontent.com/64597233/85928286-ea51bb80-b879-11ea-9d79-003fc38e0672.png)

**Comment by tierninho** [comment]
@vin-fandemand Thank you for filing this issue. Please note we do not support Ubuntu here, nor is there official support elsewhere. Sorry!

The auth reason could be one of many things. Some things to consider:

- Make sure you are signed in to Desktop
- Try cloning via HTTPS

There are many resolved auth issues in our repo. Please have a look.

**Comment by jeyakumar-BTR** [comment]
> ### Describe the feature or problem you’d like to solve
> Trying to clone a private repo from my organization. On entering the user name and password, I get a pop up saying "Authentication failed We were unable to authenticate with github.com. Please enter your username and password to try again."
> 
> ### Additional context
> I am using the Ubuntu distribution. I am able to clone my own repos and public repos from my org.
> 
> ![image](https://user-images.githubusercontent.com/64597233/85928286-ea51bb80-b879-11ea-9d79-003fc38e0672.png)

did you fix this?

**Comment by Jhoine** [comment]
You are interested and I will be in on this device to start

คุณ เสกสรร คำแสน

ในวันที่ ส. 20 พ.ค. 2023 01:24 น. jeyakumar-BTR ***@***.***>
เขียนว่า:
