### ISSUE TITLE
Newly created branch date wrong

### ISSUE THREAD

**Issue by frankhli843** [desktop/desktop#10103]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Gitlab repo 
2. Create a new branch 
3. fetch on github desktop

### Expected behavior

Branch should say created a moment ago 

### Actual behavior

![image](https://user-images.githubusercontent.com/51806469/86015196-41c56800-b9ef-11ea-9e7f-b09b128cf567.png)

**Comment by steveward** [comment]
@frankhli843 the date shown in the branch dropdown is the date of the last commit made to that branch. If you created a new branch off of your default branch and the most recent commit was from 6 days ago then that is the date that will be shown. I hope that helps explain things!
