### ISSUE TITLE
Couldn't install git bash.....

### ISSUE THREAD

**Issue by bikram25** [desktop/desktop#10109]
While installing the git all files get scanned but it's not reaching the finish window that reads launch the git bash.... taking too much time....when i ask to restart the pc and cancel that a error code showing that reads  line 3028: unable to run post-install scripts

But the git gui is fine..... it's working  
Please anybody help me to fix the issue

**Comment by steveward** [comment]
@bikram25 this issue tracker is for GitHub Desktop, if you are having specific issues with Git for Windows please [open an issue there](https://github.com/git-for-windows/git/issues).

**Comment by bikram25** [comment]
thanks @steveward 
but i could not get into the solution ....can you or any one give me the guide /steps to fix the problem 

As i trying to open the git bash there is a file named  mintty.exe.stackdump is forming
 the file reads 
              Exception: STATUS_ACCESS_VIOLATION at eip=000901B0
eax=00000000 ebx=0045028B ecx=0022C5CC edx=76F870B4 esi=004A0410 edi=80000000
ebp=0022CB48 esp=0022C614 program=C:\Program Files\Git\usr\bin\mintty.exe, pid 381, thread main
cs=001B ds=0023 es=0023 fs=003B gs=0000 ss=0023
Stack trace:
Frame     Function  Args
0022CB48  000901B0 (20071058, 20071062, 0022CD28, 6100AFA5)
0022CD28  6100AFA5 (00000000, 0022CD84, 61009DD0, 00000000)
0022CD84  610088B2 (00000000, 00000000, 00000000, 00000000)
End of stack trace
 i hope this will help to understand the problem

**Comment by steveward** [comment]
It looks like you may be running into a known mintty issue:

https://github.com/mintty/mintty/issues/763

I'd recommend posting there for assistance.
