### ISSUE TITLE
Ability to make the path element wider

### ISSUE THREAD

**Issue by PartySky** [desktop/desktop#10108]
Hello,

It would be nice to have the path element wider. This element has resizable witdh with max value 350px. The most of time it's pretty nice size. But from time to time I wish to read full files length and It would be nice if the width of the element could be increased (up to 1200px for example).

![Untitled](https://user-images.githubusercontent.com/30129799/86094562-60903100-bab9-11ea-8e3a-3992a9be6d51.png)

**Comment by niik** [comment]
Hi @PartySky, thanks for opening this! We're tracking this issue in #2745 so please subscribe to that issue for any updates!
