### ISSUE TITLE
Support for JetBrains IDE's

### ISSUE THREAD

**Issue by Suyashtnt** [desktop/desktop#10101]
### Describe the feature or problem you’d like to solve
Add support for Jetbrains IDE's based on the most prominent language the repo is in, e.g if its mainly coded in java/kotlin you will have an option to open in IDEA, or if its python make it open in Pycharm

### Proposed solution
Allow the user to choose from integrations "use Jetbrains apps" and this will be a tick box that if the repo does have a specific Jetbrains app that the user has it will open in that app, but then all other ones will open in the default IDE(e.g VSC)

### Additional context
N/A

**Comment by steveward** [comment]
Thanks for the feedback @Suyashtnt. This is being tracked in #9453, so I am going to close this issue out.
