### ISSUE TITLE
Error Loading Author and Summary Field in Github Desktop for Windows 10 

### ISSUE THREAD

**Issue by BrandonMoy** [desktop/desktop#10107]
### Describe the bug
Error Loading Author and Summary Field in Github Desktop for Windows 10 

### Version & OS
2.5.3, newest version of Windows 10

### Steps to reproduce the behavior

1. Open Github Desktop
2. See error

### Expected behavior

See author avatar image and summary field 

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Text representation of image and misaligned/not readable summary field

Add screenshots to help explain your problem, if applicable.

https://user-images.githubusercontent.com/49214669/86088215-7d9e1300-ba6b-11ea-974d-ad573f3a75b5.png

**Comment by tierninho** [comment]
Thanks for the report @BrandonMoy . This looks similar to #5671 and #6041.

Could you try resetting GitHub Desktop a fresh state to see if that helps?

Close GitHub Desktop
Remove all of the files in `%APPDATA%\GitHub Desktop\`
Restart GitHub Desktop (you will need to add your repositories back to the application)

Let me know if that helps.

**Comment by BrandonMoy** [comment]
That worked! Thank you for the help.

**Comment by tierninho** [comment]
Glad to hear! Thanks for using Desktop.
