### ISSUE TITLE
Authentication failed when puching a repository.

### ISSUE THREAD

**Issue by SteveRMann** [desktop/desktop#10113]
### Describe the bug
Using Github Desktop, I cloned a repository to a local folder, made some minor edits, then did a Commit to Master.
Next Github Desktop told me that I had a "local commit waiting to be pushed to GitHub". I clicked on "Push Origin"
And got this error:

Authentication failed. Some common reasons include:
(etc.)

I opened Git Gui and pushed the repository just fine.
But Github Desktop is still saying that I have a "local commit waiting to be pushed to GitHub".

The log file is attached, today's session starts at: 2020-06-30T13:51:04.365Z

### Version & OS

Version 2.5.3
Windows 10

### Logs

[2020-06-30.desktop.production.log](https://github.com/desktop/desktop/files/4853185/2020-06-30.desktop.production.log)

**Comment by tierninho** [comment]
Closing in favor of your [existing issue](https://github.com/desktop/desktop/issues/10059) that is still unresolved. Thanks.

**Comment by rv185130** [comment]
I am currently having this issue not sure why.
I made a branch from main, made my changes, pushed to the branch, merged the branch, and each time this number keeps going up,
<img width="1283" alt="Screen Shot 2021-11-10 at 8 32 19 AM" src="https://user-images.githubusercontent.com/68381312/141122407-10d6dfca-9fe8-4f55-ac99-616786420d28.png">
