### ISSUE TITLE
Can't scroll file preview

### ISSUE THREAD

**Issue by Craigjw** [desktop/desktop#10118]
### Describe the bug

Selecting History gives a list of committed files is shown in the middle pane, if one of these is selected, on the right hand pane, a preview of the file is shown.  The file is not fully scrollable, only showing the first 35 lines.  This is quite useless if the first 35 lines of code does not contain any useful information.  The file should be fully scrollable to the end of the file to give a proper context.

### Version & OS

Github desktop v 2.5.3

### Steps to reproduce the behavior
As above

### Expected behavior
File preview of commited files should be fully scrollable to the end of the file.

### Actual behavior
Only the first 35 lines of a file is visible.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the report @Craigjw. Are you wanting the entire file to be displayed in the diff in the `History` view, or are you having issues viewing the entire diff of a file? GitHub Desktop does not display the entire contents of a file in the diff view in the `History` tab.

There is also a known issue with diff scrolling that can occur at times -- see https://github.com/desktop/desktop/issues/1380.

**Comment by Craigjw** [comment]
It should show the whole file, it's unhelpful otherwise.  I had to view the
changes later in the file and Github desktop was not helpful, I had to
switch to another source control application to accomplish this.

**Comment by niik** [comment]
Hi @Craigjw, as @steveward said we only show the parts of a file that has changed but if there are more changed lines in a file than can be displayed in one view we certainly allow scrolling the file. Are you saying that there were other changes that you could not get to?

![2020-07-06 17-14-07 2020-07-06 17_14_34](https://user-images.githubusercontent.com/634063/86609630-76678f80-bfac-11ea-8450-8dc39a1acce4.gif)

![2020-07-06 17-16-04 2020-07-06 17_16_29](https://user-images.githubusercontent.com/634063/86609669-87b09c00-bfac-11ea-8a93-1e320476503f.gif)

**Comment by Craigjw** [comment]
Hi,

Yes, there were changes I could not see.  The 2nd screen shot you show
(patch-formatter.ts) would not scroll to the bottom of the file.  It seems
to be working fine with files I view now though.  I guess that this would
be an intermittent issue.  I'm really not sure how it was caused.

thank you kindly for getting back to me.

Regards

**Comment by niik** [comment]
Hi  @Craigjw, I'm glad that it seems to be working for you now. If you encounter the issue again and especially if you're able to reliably reproduce it please don't hesitate to comment on this issue or open a new one so that we can take another look.
