### ISSUE TITLE
But with my github desktop where changes are showing up when I did not do anything. 

### ISSUE THREAD

**Issue by pkimchi** [desktop/desktop#10116]
### Describe the bug

Out of no where one day I am showing 222 changes where I have not seen them before. This happens when I open up github desktop. When working through the CLI it shows as everything is "nothing to commit, working tree clean". But when I open up the desktop then all of a sudden I have all all of these changes that just pop up and when I run "git status" again it shows all of those changes that are "not staged for commit"

### Version & OS
Git hub - Version 2.5.3
OS Name	Microsoft Windows 10 Pro N
Version	10.0.19041 Build 19041

### Steps to reproduce the behavior

1. Clone my work repo
2. Open Github desktop
3. Changes where changes should not exist. 

**if i clone the repo straight through github desktop then i get this issue

![image](https://user-images.githubusercontent.com/40174425/86177117-b67dcc80-baeb-11ea-9916-e003dc94a81b.png)

### Expected behavior

That there are no issues with my github desktop

### Actual behavior

222 changes that I did not commit are there(even after a refresh of my repo)

### Screenshots
This is what it looks like when I clone repo from the CLI
![image](https://user-images.githubusercontent.com/40174425/86177266-f0e76980-baeb-11ea-8069-bd67da54a47e.png)

This is what it looks like when I try to clone from the github desktop
![image](https://user-images.githubusercontent.com/40174425/86177365-1ffddb00-baec-11ea-980a-fd6177974ecd.png)

This is what it looks like after i clone from CLI then open up github desktop and add the local repository
![image](https://user-images.githubusercontent.com/40174425/86177220-dd3c0300-baeb-11ea-819d-1473a63d7ef5.png)

From here I cannot switch branches.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.  These are my logs for today. 

[2020-06-30.desktop.production.log](https://github.com/desktop/desktop/files/4854448/2020-06-30.desktop.production.log)

**Comment by tierninho** [comment]
@pkimchi Thanks for the very detailed issue. Looks like the clone worked and the checkout failed, hence all the errors. 

What you are running into is an issue that is specific to Windows machines. There are certain reserved names that cannot be used in filenames. II suspect `sql` is a reserved word. See [this Microsoft help article](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#naming-conventions) for the full list of reserved characters and words.

```
2020-06-30T14:11:25.369Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/livongo/reporting-configs.git/': Could not resolve host: github.com

2020-06-30T14:11:26.582Z - warn: [ui] fetchRepository: an error occurred for 'livongo/reporting-configs'
TypeError: Failed to fetch
2020-06-30T14:11:26.584Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
TypeError: Failed to fetch
2020-06-30T14:11:26.607Z - warn: [ui] fetchRepository: an error occurred for 'livongo/reporting-configs'
TypeError: Failed to fetch
```

```
2020-06-30T17:24:01.878Z - warn: [ui] failed fetching updated PRs for repository livongo/reporting-configs
TypeError: Failed to fetch
2020-06-30T17:24:01.879Z - error: [ui] Error refreshing pull requests for 'livongo/reporting-configs'
TypeError: Failed to fetch
2020-06-30T17:25:17.216Z - info: [ui] [BranchPruner] No branches to prune.
```

```
Resolving deltas: 100% (53512/53512), done.
error: invalid path 'db/redshift/update/nonpii/20200511_INSERT_premera_milestone_claim_billing_config_items.sql '
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

```
2020-06-30T18:07:29.120Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/livongo/reporting.git - pkimchi (has token)
2020-06-30T18:07:29.609Z - error: [ui] `git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/livongo/reporting.git C:\Users\Paul Kim\Documents\GitHub\reporting` exited with an unexpected code: 128.
stderr:
fatal: destination path 'C:\Users\Paul Kim\Documents\GitHub\reporting' already exists and is not an empty directory.
```

**Comment by pkimchi** [comment]
@tierninho Any suggestions on how to bypass this issue? The repo is used by many team members and everyone is on many different machines/operating systems. I guess worst comes to worst... if there is no solution for desktop I can just revert back to using CLI

**Comment by steveward** [comment]
@pkimchi it looks like there is a trailing space at the end of your filename: `config_items.sql '`, which would cause this error. From the doc @tierninho linked:

>Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not. However, it is acceptable to specify a period as the first character of a name. For example, ".temp".

 Are you able to try renaming that file? You could try directly [renaming it on GitHub](https://docs.github.com/en/enterprise/2.14/user/articles/renaming-a-file).

**Comment by steveward** [comment]
Closing this issue out due to inactivity @pkimchi. If you are still having problems please let us know!
