### ISSUE TITLE
La aplicación “GitHub Desktop” no se puede abrir.  -47

### ISSUE THREAD

**Issue by maurogoyeneche** [desktop/desktop#10123]
### Describe the feature or problem you’d like to solve

cant open the desktop app. - error -47

### Additional context

.

**Comment by tierninho** [comment]
Gracias por la noticia. Adjunte los registros para que tengamos más información. Ver el menú Help:

![Screen Shot 2020-07-01 at 3 26 18 PM](https://user-images.githubusercontent.com/14828183/86306187-4f295080-bbaf-11ea-9496-4111636a9248.png)
