### ISSUE TITLE
Occasionally some lines don't get committed

### ISSUE THREAD

**Issue by jabamaus** [desktop/desktop#10124]
### Describe the bug

Occasionally some lines don't get committed

### Version & OS

GitHub Desktop v2.5.3, Windows 10 v2004

### Steps to reproduce the behavior

None I'm afraid

### Expected behavior

I expect whole files to be committed, not have lines left over.

### Actual behavior

Something odd is going on. A few times now I have committed a file only to later see a line change that was supposed to be committed in that commit show up again in changes view. This is pretty worrying. The only info I've got is that I just committed a file with 10 modified lines and no adds or deletes and the 9th line change didn't get committed. I don't _think_ I used discard added/modified on that file. I've noticed this kind of thing a few times recently and I'm pretty sure it started happening in v2.5.3. The last time something odd happened there were several files left over after I thought I'd committed everything. I assumed they must have been scrolled off screen and I'd missed them but now I suspect its this bug.

### Screenshots

None

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
[2020-07-02.desktop.production.log](https://github.com/desktop/desktop/files/4862463/2020-07-02.desktop.production.log)

**Comment by niik** [comment]
Hi @jabamaus, I'm sorry to hear that you're having problems with files being partially committed. If you manage to find a reliable reproduction case we'd love to hear about it. In the meantime I can only talk about how Desktop functions internally.

When a new file is detected in Desktop we assume it's about to be committed and select all the lines in that file for inclusion in the next commit. If new lines get added to that file they too are selected for inclusion. As long a a majority of the lines in a file are selected for inclusion we're gonna assume that any added lines are also going to get included. But if a user deselects more than half of the lines in a file we switch to assuming that any additional added lines will not be included.

I've had this happened to me when I've intentionally been committing partial files and when I realize that a commit didn't include all the lines I wanted I use the "undo commit" functionality which automatically repopulates my commit message again and then I select the lines that got missed and redo the commit. I hope that helps and please let us know if you find a reliable reproduction!

**Comment by jabamaus** [comment]
Thanks for the informative response Markus. I did not even realise that
commits could be made at the line level or that there was even a concept of
selecting lines for commit. I thought it worked at a file level. This
definitely explains the behaviour - I must have inadvertently deselected a
line. When I’m back from holiday I’ll test this all out to make sure I
understand it properly. As far as I’m concerned you can close this as
answered. Thanks Markus, much appreciated.

**Comment by niik** [comment]
Yeah, it's not something we're doing a great job of showcasing, that's for sure. I'll close this issue now but we can easily reopen it if you encounter more odd behavior when you test it out. Enjoy your holiday!

**Comment by jabamaus** [comment]
Thanks 😊

**Comment by nte93** [comment]
> ### Describe the bug
> 
> Occasionally some lines don't get committed
> 
> ### Version & OS
> 
> GitHub Desktop v2.5.3, Windows 10 v2004
> 
> ### Steps to reproduce the behavior
> 
> None I'm afraid
> 
> ### Expected behavior
> 
> I expect whole files to be committed, not have lines left over.
> 
> ### Actual behavior
> 
> Something odd is going on. A few times now I have committed a file only to later see a line change that was supposed to be committed in that commit show up again in changes view. This is pretty worrying. The only info I've got is that I just committed a file with 10 modified lines and no adds or deletes and the 9th line change didn't get committed. I don't _think_ I used discard added/modified on that file. I've noticed this kind of thing a few times recently and I'm pretty sure it started happening in v2.5.3. The last time something odd happened there were several files left over after I thought I'd committed everything. I assumed they must have been scrolled off screen and I'd missed them but now I suspect its this bug.
> 
> ### Screenshots
> 
> None
> 
> ### Logs
> 
> Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
> [2020-07-02.desktop.production.log](https://github.com/desktop/desktop/files/4862463/2020-07-02.desktop.production.log)
> 
> 
> ### Additional context
> 
> Add any other context about the problem here.
>
