### ISSUE TITLE
 Visual Studio is not publishing it's Blazor binaries properly

### ISSUE THREAD

**Issue by arcibaldas** [desktop/desktop#10125]
Hello,

I think there is something fundamentally broken with my Visual Studio. I tried to repair but this didnt help. Tried uninstall visual studio and installed the community preview version. So the problem is that .dll files are properly copied to the project folder. Instead of using 109 files, it only takes 5. These files are the single page application files - all the DLLs, javascript and HTML that make up the website. When the installation builds - nothing is generated. Before, I haven't got this kind of problem. My blazor app is not loaded fully, i don't see anything, because there is no libraries in place. 

I will copy the contents of the compile output. Maybe it will help. You can find in text file attached.
[issue.txt](https://github.com/desktop/desktop/files/4864385/issue.txt). Thank you.

My view:

![issue1](https://user-images.githubusercontent.com/42044734/86361219-3044c000-bc7c-11ea-98f1-4607977e4a92.png)
Should be:

![image](https://user-images.githubusercontent.com/42044734/86361360-5f5b3180-bc7c-11ea-889d-a6274e77b663.png)

Browser view:

![issue2](https://user-images.githubusercontent.com/42044734/86361222-30dd5680-bc7c-11ea-9c1b-7b7c33acbc41.png)

**Comment by steveward** [comment]
@arcibaldas this issue tracker is for GitHub Desktop. Please [contact Microsoft](https://visualstudio.microsoft.com/support/) for Visual Studio support.
