### ISSUE TITLE
show in finder shows up one level above 

### ISSUE THREAD

**Issue by ggrrll** [desktop/desktop#10126]
### Describe the bug

"show in finder" used to open finder directly within the repo path, but since few upgrades it opens in a level above the right one (for instance in my case, it opens in `Documents`, where my git repos are)

### Version & OS

GH Des: 2.5.3
mac os: 10.15.5

any reason why? is it a bug?

Thanks

**Comment by tierninho** [comment]
Thanks for reaching out. We are fixing this in https://github.com/desktop/desktop/pull/9987
