### ISSUE TITLE
Notifications for Desktop

### ISSUE THREAD

**Issue by Osiris-Team** [desktop/desktop#10135]
<div align="center">
<div>
<h1>Notifications for Desktop</h1>
<p>Its a feature request xoxo 💜</p>

<h2>Workflow</h2>
<p>-> Background service listening for notifications ->
Github notification arrives and gets displayed by windows/mac notification
onPressWindowsNotification() -> Opens browser/tab with the issue/pullrequest</p>

<h2>Advantages</h2>
<p>+ Users can react faster to newly opened issues on their repositories. That also means that critical bugs can be fixed faster.</p>
<p>+ Increases users productivity and motivation</p>
<p>+ Increases users interactions with GitHub Desktop</p>

<h2>Design</h2>
<h3>Notification bell icon on the right corner, of the top bar in GitHub Desktop</h3>
<img src="https://i.imgur.com/PqThYx7.png">

<h3>Alternative</h3>
<img src="https://i.imgur.com/D49PTTR.png">

<h3>Windows notification example</h3>
<img src="https://i.imgur.com/s0AW6gJ.png">

<h3>Settings example</h3>
<img src="https://i.imgur.com/28TvPol.png">

</div>

**Comment by niik** [comment]
Hi @Osiris-Team, thanks for opening this. Notifications is certainly something we're interested in exploring in the future. Could you elaborate a little bit on what workflows you would consider most important to get notifications about? When in your  daily work would you expect to get a notification and are there any scenarios where you'd foresee notifications being disruptive to your workflow?

**Comment by Osiris-Team** [comment]
@niik Me personally would like to get notifications about **everything**.
But a good idea would be to add a settings tab with checkboxes of all notifications you can get, so you can enable/disable what you want. Ps. also added a example design :)

**Comment by tierninho** [comment]
Thank you for the thoughts. Closing this as a dupe. Please follow along with https://github.com/desktop/desktop/issues/2825
