### ISSUE TITLE
Remove repo button on deleting

### ISSUE THREAD

**Issue by b5414** [desktop/desktop#10133]
### Describe the feature or problem you’d like to solve

Removing a repo with a checkbox (to bin) freezes the app (while it deleting)

### Proposed solution

[Loader](https://www.google.ru/search?q=loader+js+css&tbm=isch&ved=2) or better - change the color of the Remove button to any, before it starts calculating+deleting the files

### Additional context

I just want to understand if the app performs removing task

**Comment by niik** [comment]
Hi @b5414, thanks for opening this. I've opened https://github.com/desktop/desktop/pull/10143 which should hopefully fix this issue by showing a progress spinner while the repository is being moved to trash. You don't specify whether you're on Windows or macOS though so I wanted to mention that it's possible that the dialog will still stall somewhat on Windows due tot the synchronous blocking nature of the API there.

**Comment by b5414** [comment]
Windows 10, git folder on hdd in exFAT
