### ISSUE TITLE
Display git.exe Location

### ISSUE THREAD

**Issue by nathan-ca** [desktop/desktop#10138]
### Describe the feature or problem you’d like to solve

I always use the git.exe bundled in github desktop version for my automated scripts and other IDEs, such as PyCharm. Whenever I upgrade to the latest Github desktop version, most of the time the git.exe will also upgraded to the latest version. The path to git.exe was changed.

I would appreciate if you can provide me a quick way to get the path to git.exe.

### Proposed solution

In desktop ui, click Help -> About Desktop Github, you can display git version and path to the git.exe in the information. Otherwise I always has to manually find it using Explorer to the path, e.g. C:\Users\{User}\AppData\Local\GitHubDesktop\app-2.5.3\resources\app\git\cmd\git.exe

I believe this will make many developers' life much easier.

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by niik** [comment]
Hi @nathan-ca, thanks for opening this. We don't recommend attempting to use the Git that GitHub Desktop uses internally as it's stripped of several features that GitHub Desktop doesn't need, see https://github.com/desktop/desktop/issues/3708#issuecomment-354665183 for more details.

We instead recommend users who need a command line installation of Git to install [Git for their platform directly](https://git-scm.com/downloads).

We don't anticipate changing our stance on this in the near term so I'm going to close this issue out and I hope you are able to work around your issue by installing Git directly.
