### ISSUE TITLE
Can't search via commit hash

### ISSUE THREAD

**Issue by silcosoftware** [desktop/desktop#10132]
I'd like to be able to search via commit hashes (for example, 3653d25) in the search bar, in the Github desktop app. 

This came up when I was using Elastic Beanstalk to deploy something, and it shows the commit hash (as above) but I am having trouble locating which hash that was.

Would be nice if the Github desktop app allowed me to search via commit hash.

Thanks!

**Comment by niik** [comment]
Hi @silcosoftware, thanks for reaching out! This looks very similar to the request in https://github.com/desktop/desktop/issues/7022 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date with any development happening in that area.
