### ISSUE TITLE
Do not create initial commit automatically!

### ISSUE THREAD

**Issue by bukowa** [desktop/desktop#10131]
### Describe the feature or problem you’d like to solve
If there are existing files in a directory do not automatically create initial commit while creating new repository!

### Proposed solution
Just do not...

### Additional context
Don't you think we should have a choice? Everywhere everyone knows better what i want not giving me any choice, the same problems happens everywhere in software, it is really bad pattern that gives really bad experience.

**Comment by steveward** [comment]
Thanks for the feedback @bukowa.

GitHub Desktop automatically creates the initial commit when a .gitignore template, README file, or license is selected during the repository creation process. If you wish to modify the initial commit you can undo it by clicking on the 'Undo' button below the commit message form.

![image](https://user-images.githubusercontent.com/634063/30150802-1d7d1166-93ad-11e7-9a40-7215cf7fbdf3.png)

That will let you modify the contents of each of the committed files as well as the message without creating a new commit. I hope that helps!

**Comment by bukowa** [comment]
@steveward Thanks for help but- while the "undo" button is workaround for the issue, is not a fix. 
The "undo" of initial commit can cause confusion and lead to more problems. I still believe the files should be created but not automatically commited.
