### ISSUE TITLE
Authentication failed every time

### ISSUE THREAD

**Issue by MCUmbrella** [desktop/desktop#10145]
### Describe the bug

I used this software for two weeks without any problems, but recently I can't use it for any operations, such as cloning repo, pushing commits or submitting pull requests.

### Version & OS

GitHub Desktop 2.5.3 & Windows 10 Enterprise LTSC

### Steps to reproduce the behavior

1. Go to 'File -> Clone repo'
2. Choose any repo you want to clone. I have chosen my hello-world repo
3. Start cloning
4. 'Authentication failed' screen appeared

### Expected behavior

Perform the above operations normally

### Actual behavior

It keeps showing error messages about authentication failures.

### Screenshots

![Push failed](https://user-images.githubusercontent.com/40854260/86604991-b2b0e500-bfd8-11ea-885c-5169e4529e8a.png)
![Clone failed](https://user-images.githubusercontent.com/40854260/86605068-cd835980-bfd8-11ea-92b6-d222d3753c97.png)

### Logs

https://pastebin.com/SCetvE2L

### Additional context

I have tried to log in dozens of times but this problem still exists

**Comment by niik** [comment]
Hi @MCUmbrella, sorry to hear you're having problems. Thanks for filling out the template, that's really helpful!

Just a though to start with, have you opened the Options dialog (File -> Options) and signed out and then back in again with your GitHub.com user account?

**Comment by MCUmbrella** [comment]
I said I tried to re-log many times and it doesnt work. Login success but cant do anything.

**Comment by tierninho** [comment]
@MCUmbrella Thanks for the update. Was that the full logs? It appears to be missing some content. 

> Cloning into 'E:\GitHub\hello-world'...

Also, have you tried cloning in another drive? I believe the E drive is a recovery drive.

**Comment by MCUmbrella** [comment]
Yes it is the full log and my E drive has almost 100GB of free space. I will try cloning repos in other drives soon.

**Comment by MCUmbrella** [comment]
I re-installed both Git and GitHub Desktop and changed where repos are cloned to. The weird thing is now I can only clone repos but cant make a pull request or push commits.
Today's log file: https://pastebin.com/3ifpPHJG

**Comment by tierninho** [comment]
I spotted more errors in the logs:

```
2020-07-07T10:00:42.131Z - warn: [ui] fetchAccount: failed with endpoint https://api.github.com
TypeError: Failed to fetch
```

```
2020-07-07T10:21:44.764Z - error: [main] Malformed launch arguments received: C:\Users\Administrator\AppData\Local\GitHubDesktop\app-2.5.3\GitHubDesktop.exe,--squirrel-firstrun
```

```
2020-07-07T10:21:48.238Z - error: [ui] Error checking for updates
Error: Command failed: 4294967295
System.AggregateException: ����һ���������� ---> System.Exception: Couldn't acquire lock, is another instance running
```

Do you use a proxy, firewall, virus blocker? They may be interfering or there was some issue with a locked file during the installation. If you don't use any of those services, I would clear out the app and reinstall. Were these the steps you followed?

Close GitHub Desktop
Delete the `%AppData%\GitHub Desktop\` directory
Delete the `%LocalAppData%\GitHubDesktop\` directory
Reinstall GitHub Desktop from desktop.github.com

**Comment by MCUmbrella** [comment]
Thanks. I will try it later.

**Comment by Luckyfive** [comment]
@MCUmbrella this may help:


https://github.com/desktop/desktop/issues/10165

**Comment by MCUmbrella** [comment]
@Luckyfive @tierninho Sorry these operations didnt work :(
If possible I will try on other machines to check if something is wrong with my laptop.

**Comment by tierninho** [comment]
Are you able to push to the repository from the command line? You can go to `Repository` > `Open in <command_line>` (you may need to install Git for Windows if you have not done so already). Then just run the git push command to see if it succeeds.

Another user switched to Git Bash and it worked per here: https://github.com/desktop/desktop/issues/10166#issuecomment-655598627

**Comment by reconstrukt** [comment]
@MCUmbrella have a look at this note too, https://github.com/desktop/desktop/issues/10166#issuecomment-655704828

**Comment by MCUmbrella** [comment]
> 
> 
> Are you able to push to the repository from the command line? You can go to `Repository` > `Open in <command_line>` (you may need to install Git for Windows if you have not done so already). Then just run the git push command to see if it succeeds.
> 
> Another user switched to Git Bash and it worked per here: [#10166 (comment)](https://github.com/desktop/desktop/issues/10166#issuecomment-655598627)

It works. 
Output: 
E:\GitHub\MMPROTECT>git push
Enumerating objects: 15, done.
Counting objects: 100% (15/15), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (8/8), 521 bytes | 260.00 KiB/s, done.
Total 8 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/MCUmbrella/MMPROTECT.git
   1da34cf..bad19ee  master -> master

**Comment by reconstrukt** [comment]
@MCUmbrella curious if simply switching to a standard command line worked - or if you had to push via Git Bash?

**Comment by MCUmbrella** [comment]
> @MCUmbrella curious if simply switching to a standard command line worked - or if you had to push via Git Bash?

Sorry I can't understand it. Can you describe it more clearly?

**Comment by steveward** [comment]
@MCUmbrella you may be running into an authentication issue that can be caused by modified registry entries. Please refer to our [help document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789) for steps about how to check for this issue on your machine -- specifically the `Autorun` section. Let me know if you see anything there.

**Comment by steveward** [comment]
@MCUmbrella I'm going to close this out since we haven't heard back from you. Let me know if you are still having issues and we can dig into this further.
