### ISSUE TITLE
Sign in bug

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#10148]
### Describe the bug

When i sign in the desktop github it says ָ���ĵ�¼�Ự�����ڡ������ѱ���ֹ�� I don't understand when i use the browser it shows a blank page. 
![image](https://user-images.githubusercontent.com/66382480/86632351-482e8380-bf9d-11ea-880e-f074500e453d.png)

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@Pusheen8031 Please fill out the template above and include your logs so we have more information. Thank you!
