### ISSUE TITLE
Night Mode

### ISSUE THREAD

**Issue by MrCodingB** [desktop/desktop#10149]
My eyes are really sensitive and the bright white light, that's coming from GitHub / GitHub-Desktop is hurting them just after a few seconds. Please add themes or at least just a night mode.

...adding theming support would be ideal. But some presets or just a night mode would do too.

![image](https://user-images.githubusercontent.com/46847577/86638811-39b18d80-bfd8-11ea-978b-59976bb99574.png)
A Screenshot of the horrible white light (When you can tell the difference between the screenshot and the background, I will be happy)

**Comment by Rexogamer** [comment]
Hey! In the settings, under Appearance there’s an option for dark mode which should fix this for you (and in my opinion is the nicer theme).
