### ISSUE TITLE
Add ability to 'pin' or 'favorite' repos

### ISSUE THREAD

**Issue by StickNitro** [desktop/desktop#10157]
### Describe the feature or problem you’d like to solve

When you have a long list of repos it can sometime take a little while to find the repo you are looking for, would be greate if you could pin or favorite one or more repos and these appear always at the top of the list of repos

### Proposed solution

How will it benefit Desktop and its users?

Those repos that are most used would appear at the top of the repo list reducing the time needed to scroll the long list of repos and find the one you are looking for

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by niik** [comment]
Hi @StickNitro, thanks for opening this!

We don't have any plans in the near future to add favorites to the repository list, for the reasons described here: #8183 (comment). I'm going to close this issue out, but thanks for letting us know you would like to see this feature added to GitHub Desktop. See https://github.com/desktop/desktop/issues/6460 for more of our investigation and discovery preceding this decision.

While I know it's not what you're looking for I want to share a tip about using the Ctrl (or Command if you're on a Mac) + T [keyboard shortcut](https://docs.github.com/en/desktop/getting-started-with-github-desktop/keyboard-shortcuts-in-github-desktop) which opens the repository list with the search field in focus letting you narrow down your selection pretty fast.
