### ISSUE TITLE
Cannot SIgn Into GitHub Enterprise, Github Enterprise version 2.18.20

### ISSUE THREAD

**Issue by billyhales** [desktop/desktop#10158]
### Describe the bug

Whenever I attempt to log into Github Enterprise from GitHub Desktop for Linux, I get directed to a 404 page.

### Version & OS

Apparently, About Github Desktop is greyed out when I try. It is the latest publicly facing version (7-7-2020). I am using Ubuntu Linux 20.04.

### Steps to reproduce the behavior

1. Launch Github Desktop
2. Click on Sign in to Github Enterprise Server
3. Enter Credentials
4. See The 404 comes up after 5 seconds. Sadness.

### Expected behavior

To be able to use GitHub Desktop with my organization's Github Enterprise Server

### Actual behavior

A 404 page shows up on the GitHub Enterprise Server. I am using Mozilla Firefox.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
[2020-07-07.desktop.production.log](https://github.com/desktop/desktop/files/4884016/2020-07-07.desktop.production.log)

**Comment by niik** [comment]
Hi @billyhales, I'm afraid this is a known issue for the unofficial Linux fork (see https://github.com/shiftkey/desktop/issues/72) of GitHub Desktop.

Until such a time when we have official support for Linux I'm afraid there's not much I can do to help here. I wish I had a better answer for you but for the time being I'd suggest subscribing to the issue I linked above to stay informed of any progress.

**Comment by billyhales** [comment]
This is mildly frustrating, as I see this issue is nearly two years old. In the interest of saving devs some time responding to these trouble reports, I would recommend greying out the button so that potential users do not waste their time.
