### ISSUE TITLE
Speed limit

### ISSUE THREAD

**Issue by JzAli** [desktop/desktop#10153]
### Describe the feature or problem you’d like to solve
Speed limit is capped for some reason and very low
A clear and concise description of what the feature or problem is.
My internet is 30Mbps but for some reason my download on github desktop is capped to 210KiB/s i tried on another laptop and it works fine on that i get a 3MiB/s speed on that . Im not really sure why this is happening
### Proposed solution
N/A
How will it benefit Desktop and its users?
N?A
### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by niik** [comment]
Hi @JzAli, I'm sorry to hear you're having problems with transfer bandwidth while using GitHub Desktop. GitHub Desktop does not impose any transfer speed limits. When cloning, fetching, or pulling using GitHub Desktop we rely entirely on Git which doesn't have any built in limitations either.

As such I'm afraid there's not much GitHub Desktop can do to help you out here. I would recommend consulting the [connectivity troubleshooting guide](https://docs.github.com/en/github/getting-started-with-github/troubleshooting-connectivity-problems) and the [GitHub Debug](https://github-debug.com/) site and if that doesn't resolve your issue I would recommend contacting [GitHub Support](https://support.github.com) directly
