### ISSUE TITLE
Cannot commit individual lines if file is viewed after "The diff is too large" message

### ISSUE THREAD

**Issue by Jamizzle93** [desktop/desktop#10154]
### Describe the bug

I cannot select individual lines for committing when I am viewing a file that originally displayed a "The diff is too large" message.

### Version & OS

GitHub Desktop Windows 10 - Version 2.5.3

### Steps to reproduce the behavior

1. Go to the "Changes" tab
2. Click a file
3. Observe the "The diff is too large to be displayed..." error 
4. Click "Show diff" button
5. Attempt to select individual lines for commit by clicking

### Expected behavior

I can select lines and commit them individually.

### Actual behavior

I cannot select lines - I can only select the whole file for commit.

### Screenshots

![GithubDesktopCannotCommitLines](https://user-images.githubusercontent.com/5894967/86739717-ff72db00-c02d-11ea-8140-2134dcee7070.gif)

### Logs
N/A

### Additional context

I have only seen this in one repository, I'm not sure if that helps? It just seems strange that all other files work fine but the one with the large diff doesn't.

**Comment by niik** [comment]
Hey @Jamizzle93, thanks for opening this! I've opened #10159 which should hopefully fix this issue.

**Comment by Jamizzle93** [comment]
Ahh yes @niik that looks like it'll do the job! Thanks. 👍
