### ISSUE TITLE
Couldn´t make commits in origin

### ISSUE THREAD

**Issue by AdrianSanchez613** [desktop/desktop#10169]
Dear sir,

I have created a Java Spring Project named EventsApp, this project is in the Spring workspace in the C: directory.
Using Github Desktop version, I generated the controlled version of the app in my localhost, I have created two branches, the master branch (default) is going to be the project after being tested.
The second branch called "DesarrolloEA" would be the branch in which I will be building the app. After I created the branch, I published it to Github Web with the initial commit, in this moment the two branches are the same in content.

The problem is when I try to commit new changes into the Github web, because the "commit to" button is disabled and i couldn´t do a commit.
If I try to push in origin using git I receive the message "up-to-date" and Git doesn´t do anything.

![sdaksdlasjdkasj](https://user-images.githubusercontent.com/60578940/86920925-b18fcd00-c12a-11ea-8dfd-6b71fa7072a9.PNG)
![dfjskdfhsdhfjsdhfsjdfhjsdf](https://user-images.githubusercontent.com/60578940/86920999-c53b3380-c12a-11ea-8f6a-38b485348881.PNG)

Thank you all

**Comment by steveward** [comment]
@AdrianSanchez613 make sure you enter a commit message in the `Summary (required)` section. That will enable the button. Let me know if you run into any issues!

**Comment by AdrianSanchez613** [comment]
@steveward, you are right, that was the problem, thank you so much
