### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by jjuannn** [desktop/desktop#10164]
### Describe the bug

I cant use "push origin" function

### Version & OS

GitHub Desktop 2.5.3
Windows 10 PRO

### Steps to reproduce the behavior

Do changes in your file
Commit
Press "push origin" 
Error appears

### Expected behavior

Push my local commit // Push the commits

### Actual behavior

It keeps showing error messages about authentication failure

### Screenshots

[error](https://imgur.com/a/IiBRLTy)

(Sorry, i dont know how to upload images)

### Logs

https://pastebin.com/a8RvfW78

### Additional context

I reinstalled GH Desktop, deleted GitHub Files in %appdata% and %localappdata%, logged out and logged in again, and i checked the repository settings. Nothing works. 
Previously, I have never had any problems with the application

EDIT: I don't use proxy, try disabling Windows Defender and Windowns Firewall but it doesn't work either

Thanks!

**Comment by jjuannn** [comment]
[this is the error](https://imgur.com/a/IiBRLTy)

**Comment by Luckyfive** [comment]
Just posted an issue about this exact same problem!

**Comment by Luckyfive** [comment]
https://github.com/desktop/desktop/issues/10165

**Comment by tierninho** [comment]
@jjuannn Thanks for filing the issue. Seems like you tried all the things I would initially suggest. 

There is no much to go on in your logs, and the fact another user got this at the same time could be a coincidence as pushing is working for me on Windows. 🤔 

Can you push on any other repos? Here is test one if you need it: https://github.com/tierninho/LLL

**Comment by jjuannn** [comment]
Thanks for the reply. I tried but I can't either

**Comment by tierninho** [comment]
Hmmm, maybe try this: https://github.com/desktop/desktop/blob/development/docs/known-issues.md#authentication-errors-due-to-modified-registry-entries

**Comment by jjuannn** [comment]
I checked. I don't have any _autorun_ value

**Comment by Luckyfive** [comment]
@jjuannn try the following steps:

1. Go to my Github account settings and click on Applications
2. Go to Authorized OAuth Apps and revoke the Github Desktop application
3. Follow the Sign out and Sign In steps within the Github Desktop application
4. Issue seems fixed for now; I am able to publish a new branch and any changes

**Comment by jjuannn** [comment]
> 1. Go to Github account settings and click on Applications
> 2. Go to Authorized OAuth Apps and revoke the Github Desktop application
> 3. Follow the Sign out and Sign In steps within the Github Desktop application

This worked! Thanks! :)

**Comment by Luckyfive** [comment]
@jjuannn Glad to help 🙂

**Comment by niik** [comment]
Seems like this got resolved, thanks all!
