### ISSUE TITLE
Changed Files Show with 0 Changes 

### ISSUE THREAD

**Issue by krishaug** [desktop/desktop#10163]
### Describe the bug

The changed files are all empty, and a message appears for each "The file is empty." In addition, I cannot push the branch, fetch files from master or submit change to a branch..

### Version & OS

2.5.3 version on Windows 10

### Steps to reproduce the behavior

1. Update local repo 
2. Open GitHub Desktop
3. See the file list empty and a note saying "The file is empty" for each file.
4. Create a branch but it doesn't work.
5. Try to fetch but it returns Never Fetched after appearing to try to update repo.
6. Try to submit changes in file list but it doesn't work because there are no changes

### Expected behavior

I expected to be able to see changes in the file list, create a branch, fetch files, and submit changes.

### Actual behavior

See list above.

### Screenshots

Add screenshots to help explain your problem, if applicable.

**Comment by tierninho** [comment]
@krishaug Please share the logs so we can take a look at what's going on. Thank you!

**Comment by tierninho** [comment]
@krishaug  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by thekingofbandit** [comment]
this bug really piss me off, I scratch my head a lot reverting .
master > dev shown me 0 changes
but it changed some files.

<img width="1318" alt="Screen Shot 2021-10-22 at 16 11 42" src="https://user-images.githubusercontent.com/11798101/138427860-e1a84463-f5f8-468c-aa38-b27dbe1110bb.png">
