### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by Luckyfive** [desktop/desktop#10165]
### Describe the bug

Earlier in the day I was able to commit and push to this branch just fine, not sure what happened. When I commit it goes through fine but when I try to push it shows me the following prompt:

### Version & OS

Github Desktop Version 2.5.3; Windows 10 Home

### Steps to reproduce the behavior

1. Commit changes
2. Click on Push origin
3. See error

### Expected behavior

Committing and pushing to branch should work as expected.

### Actual behavior

Committing works fine, pushing to branch does not.

### Screenshots

Screenshot of the prompt: 
![image (13)](https://user-images.githubusercontent.com/1806809/86861457-29abb380-c095-11ea-8abd-246ad48a1630.png)

### Logs

Logs for today (first file is from earlier today, and the second is from just now -- when the problem started happening):

[2020-07-07.desktop.production.log](https://github.com/desktop/desktop/files/4887809/2020-07-07.desktop.production.log)
[2020-07-08.desktop.production.log](https://github.com/desktop/desktop/files/4887810/2020-07-08.desktop.production.log)

### Additional context

* Already tried logging in and out. Used both the browser log in method and the email + password method. Both succeeded in logging me back in but pushing to the branch still doesn't work
* Already tried pushing via GitBash and that doesn't work either
* Already checked to see that the branch still exists and isn't archived
* Already checked that I have access to the branch
* Already checked that nothing is down on https://www.githubstatus.com/

**Comment by tierninho** [comment]
@Luckyfive Thanks for filing the issue. Seems like you tried all the things I would initially suggest. 

There is no much to go on in your logs, and the fact another user got this at the same time could be a coincidence as pushing is working for me on Windows. 🤔 

Can you push on any other repos? Here is test one if you need it: https://github.com/tierninho/LLL

**Comment by Luckyfive** [comment]
@tierninho I am able to commit and push to other repositories. Just tested it out. 

https://github.com/Luckyfive/LLL/tree/testing

**Comment by Luckyfive** [comment]
@tierninho I found a resolution by following these steps: 

1. Go to my Github account settings and click on Applications
2. Go to Authorized OAuth Apps and revoke the Github Desktop application
3. Follow the Sign out and Sign In steps within the Github Desktop application
4. Issue _seems_ fixed for now; I am able to publish a new branch and any changes

**Comment by niik** [comment]
Glad to see you were able to resolve the issue @Luckyfive.
