### ISSUE TITLE
The "Summary required" box disapeared

### ISSUE THREAD

**Issue by BlackKnight625** [desktop/desktop#10161]
### Describe the bug

When I opened GitHub Desktop to commit some changes I did, the small box where you type in the summary is missing.
Closing and re-opening the app did not fix the issue.

### Version & OS

Version 2.5.3, Windows 10

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. The "summary required" box is missing

### Expected behavior

I expected the usual "Summary required" box to appear so I could type what I did and commit the changes.

### Actual behavior

Instead, the box is covered with my username and I'm unable to write the summary, which prevents me from commiting my changes

### Screenshots

Add screenshots to help explain your problem, if applicable.
![image](https://user-images.githubusercontent.com/43484611/86785081-25ae7000-c05a-11ea-805b-3142874065ee.png)

### Logs

[2020-07-07.desktop.production.log](https://github.com/desktop/desktop/files/4884972/2020-07-07.desktop.production.log)

### Additional context

Restarting the app does not solve the issue

**Comment by steveward** [comment]
Thanks for the report @BlackKnight625. This looks similar to https://github.com/desktop/desktop/issues/5671 and https://github.com/desktop/desktop/issues/6041. 

Could you try resetting GitHub Desktop a fresh state to see if that helps?

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop (you will need to log in again and add your repositories back to the application)

Let me know if that doesn't get things working for you.
