### ISSUE TITLE
Stashed changes are hidden if a branch is renamed

### ISSUE THREAD

**Issue by yakovmanshin** [desktop/desktop#10173]
### Describe the bug

If a branch which has some stashed changes is renamed, the stash will no longer be accessible from GitHub Desktop. However, it will still be available in command line.

### Version & OS

GitHub Desktop 2.5.3 on macOS 10.15.5.

### Steps to reproduce the behavior

1. Make some changes to tracked files;
2. Stash them so the stash appears on the bottom of the staging area;
3. Rename current branch;
4. Look at the bottom of the staging area: the stash button is gone;
5. Rename the branch back to the original name: the stash is back.

### Expected behavior

When the branch is renamed, its corresponding stash’s title is updated appropriately, so that the link between the branch and the stash isn’t broken.

### Actual behavior

The stash retains its original name which includes the branch’s old name (`test-branch` in the example below), so the app no longer sees the stash as linked to the branch.

### Screenshots

<img width="1072" alt="GHD_1" src="https://user-images.githubusercontent.com/4648742/86967592-81205100-c173-11ea-8f73-a7e808115254.png">

<img width="1072" alt="GHD_2" src="https://user-images.githubusercontent.com/4648742/86967602-854c6e80-c173-11ea-817c-11525cfb97ab.png">

At all times, running `git stash list` displays the following entry:
```
stash@{0}: On test-branch: !!GitHub_Desktop<test-branch>
```

**Comment by tierninho** [comment]
@yakovmanshin Thanks for the report. Note this is a [known issue](https://github.com/desktop/desktop/issues/7283) and a side-effect of how we structured the stashing feature. 

Workaround: If you rename the branch, the stash will reappear.
