### ISSUE TITLE
can not connect through GitHub desktop

### ISSUE THREAD

**Issue by muhammadmontasir** [desktop/desktop#10183]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by rafeca** [comment]
Hey @muhammadmontasir ! We require the issue template to be filled so we can investigate the reports efficiently, please reopen the issue and fill out the template.

Thanks!
