### ISSUE TITLE
Unable to find pull request after committing changes into feature branch in github desktop. version:2.5.3 windows OS

### ISSUE THREAD

**Issue by GattuBhavani** [desktop/desktop#10181]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by rafeca** [comment]
Hey @GattuBhavani ! We require the issue template to be filled so we can investigate the reports efficiently, please reopen the issue and fill out the template.

Thanks!
