### ISSUE TITLE
Authentication error with GitLab / Login

### ISSUE THREAD

**Issue by crashzk** [desktop/desktop#10186]
### Describe the bug

Authentication error with GitLab.

### Version & OS

- **OS:** Windows 10
- **GitHub Desktop:** Version 2.5.3

### Steps to reproduce the behavior

1. Just `Clone with HTTPS` any GitLab project for GitHub Desktop;
2. It will ask you to login with GitLab;
3. Then just make the changes you want to the project and then make a **Commit & Pull Request** for the project;
4. In some moments, GitHub gives an authentication error and asks to log in again with the GitLab user and password data;

### Expected behavior

After logging in to GitLab for the first time through GitHub Desktop he should record the access data, not asking to log in again.

### Actual behavior

He keeps giving authentication errors with GitLab, I always need to login again to be able to make Commits & Pull Request.

### Screenshots

![image](https://user-images.githubusercontent.com/32937653/87200316-a677a100-c2d2-11ea-9705-883b958064e8.png)

### Logs

Here are some more recent logs if it helps:
[2020-07-07.desktop.production.log](https://github.com/desktop/desktop/files/4905178/2020-07-07.desktop.production.log)
[2020-07-06.desktop.production.log](https://github.com/desktop/desktop/files/4905179/2020-07-06.desktop.production.log)
[2020-07-05.desktop.production.log](https://github.com/desktop/desktop/files/4905180/2020-07-05.desktop.production.log)
[2020-07-10.desktop.production.log](https://github.com/desktop/desktop/files/4905181/2020-07-10.desktop.production.log)
[2020-07-08.desktop.production.log](https://github.com/desktop/desktop/files/4905182/2020-07-08.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @crashzk. Just to clarify -- you are [generating a token for your GitLab account](https://github.com/desktop/desktop/blob/development/docs/integrations/gitlab.md) and successfully cloning, but GitHub Desktop isn't correctly caching your token? Can you open `Credential Manager` -> `Windows Credentials` and check to see if there is a `GitLab` entry there?

**Comment by crashzk** [comment]
Exactly, it is not caching the token. I did it again, because it gave error again at this very moment.

Here is a print of `Windows Credentials`:
![image](https://user-images.githubusercontent.com/32937653/88070554-31656080-cb49-11ea-8b46-90af49bc630e.png)

He even registered something about GitLab, on GitHub, as you can see, but he keeps giving the same error.

**Comment by steveward** [comment]
@crashzk what is the expiration date for the token being set to when it is created on GitLab? If the token is expiring soon after creation that could be causing the issue.

**Comment by crashzk** [comment]
@stevecat I did not put anything, expiration option I leave blank, when it is created it informs that the expiration date is **Never**.

**Comment by steveward** [comment]
@crashzk is this still an issue for you? One other user encountered this and it was due to a GitLab username change.

**Comment by crashzk** [comment]
@steveward I'll check it out, I'll delete the token and create it again and see if the problem continues.
