### ISSUE TITLE
有些时候需要在Windows平台打开unix编码的仓库，GitHub for Windows 提示有改动。

### ISSUE THREAD

**Issue by hailunchina** [desktop/desktop#10180]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by rafeca** [comment]
Hey @hailunchina ! We require the issue template to be filled so we can investigate the reports efficiently, please reopen the issue and fill out the template.

Thanks!
