### ISSUE TITLE
GitHub windows10 desktop states bad credentials when putting in the right credentials

### ISSUE THREAD

**Issue by plborgprograms** [desktop/desktop#10189]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the report @plborgprograms. Are you able to successfully log in to GitHub Desktop by going to `File` > `Options` > `Accounts`?

**Comment by SSH93** [comment]
![Uploading 88445069...]()

**Comment by SSH93** [comment]
> ### Describe the bug
> 
> 
> 
> A clear and concise description of what the bug is.
> 
> 
> 
> ### Version & OS
> 
> 
> 
> Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.
> 
> 
> 
> ### Steps to reproduce the behavior
> 
> 
> 
> 1. Go to '...'
> 
> 2. Click on '....'
> 
> 3. Scroll down to '....'
> 
> 4. See error
> 
> 
> 
> ### Expected behavior
> 
> 
> 
> A clear and concise description of what you expected to happen.
> 
> 
> 
> ### Actual behavior
> 
> 
> 
> A clear and concise description of what actually happened.
> 
> 
> 
> ### Screenshots
> 
> 
> 
> Add screenshots to help explain your problem, if applicable.
> 
> 
> 
> ### Logs
> 
> 
> 
> Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
> 
> 
> 
> ### Additional context
> 
> 
> 
> Add any other context about the problem here.
> 
>

**Comment by tierninho** [comment]
@plborgprograms As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
