### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by DavidMadrigalB** [desktop/desktop#10198]
### Describe the bug
When I try to clone a GitHub private project (of my team), this show "We were unable to authenticate with github.com. Please enter your username and password to try again.", I put my name and password and it doesn't work, but I can clone it with the terminal.

### Version & OS
Github Desktop 2.5.3. I use Windows 10

### Steps to reproduce the behavior
In Web page
1. Go to clone (a private project of your team)
2. Click on Open Gith Hub Desktop
3. See Authentication Failed

**Comment by steveward** [comment]
@DavidMadrigalB thanks for the report. Have you tried logging out and then logging back in to your GitHub account in GitHub Desktop? Could you upload a log file from a day you experienced the issue (`Help` > `Show Logs...`)?

**Comment by tierninho** [comment]
@DavidMadrigalB As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
