### ISSUE TITLE
Windows desktop version doesn't catch renaming a file with a different case

### ISSUE THREAD

**Issue by Torxed** [desktop/desktop#10193]
### Describe the bug

In Windows explorer, rename a project file from `<lowercase>.py` to `<camelCase>.py` and the change won't stick/get commit:ed.

### Version & OS

 * GitHub Desktop Version 2.5.3
 * OS: Windows 10

### Steps to reproduce the behavior

 1. git clone https://github.com/Torxed/slimWS
 2. Open project in `explorer.exe`
 3. Rename `slimws.py` to `slimWS.py`
 4. View `changes` in the GitHub desktop app

### Expected behavior

Change to be staged for commit 

### Actual behavior

No changes found, not even after modifying the file.

### Screenshots

<img width="1856" alt="github_issue" src="https://user-images.githubusercontent.com/861439/87285448-d0f67380-c4f7-11ea-97d4-aa4e1db4965c.png">

**Comment by rafeca** [comment]
Hey @Torxed, thanks for filing this issue!

The problem here is that Windows file system is case insensitive, so when you change the case of a file (or a branch), `git` won't notice the change (you can also see that no changes are shown by executing `git status` on your command line).

The easiest way to fix that is by either renaming the file from another machine that has a case sensitive file system (like a linux machine) or by trying to do two renames (e.g first from `slimws.py` to `slimws-1.py`, commit the changes and then rename back to `slimWS.py`.

Hope this helps, please feel free to reopen if there's something I missed here.

**Comment by Torxed** [comment]
@rafeca  How is this issue not related to the client even more in this case? If you're aware that the OS has a shortcoming, you need to correct for it in the client. Otherwise working across platforms becomes quite pointless.

**Comment by rafeca** [comment]
@Torxed In understand your frustration and trust me we always aim to have a consistent experience between the different operating systems, but unfortunately in some scenarios we are limited by the platform and there's not much that we can do (we cannot realistically try to work around every single problem on the tools that we rely on).

In this specific case, Desktop gets the modified files of the repository by calling `git status`. When `git` does not return the renamed file there's not much we can do to find out that there was a renamed file.

A workaround for this problem could be to calculate ourselves the list of modified files without using `git` for that but that solution:
a) Would impact negatively the performance of Desktop (`git` has implemented tons of optimizations over the years).
b) Would be very time consuming to implement and maintain (we're a very small team and we prefer to rely on other tools to do the job for us whenever possible, specially when the tool is `git` itself).
c) Could cause tons of subtle issues (there are a lot of corner cases when checking the status of a file).

These points make not worth it for us to try to tackle this issue. While we understand that this can cause confusion to some users, there's plenty of documentation of this problem out there (try googling "git status rename case insensitive"), so we believe that the (small) number of users that will face this problem will be able to unblock themselves.

If circumstances change we'll sure revisit this issue, I hope that you understand.

Thanks!
