### ISSUE TITLE
Annoying error message

### ISSUE THREAD

**Issue by kevincappuccino** [desktop/desktop#10200]
If we drag 'n drop a file that is not a git repo, it displays this message:
![image](https://user-images.githubusercontent.com/56762529/87371860-9ffc5a00-c55c-11ea-90e6-6932cded03b1.png)

The issue is when accidentally we drag and drop 100 files, 'cause that message will pop up for each one of those 100 files.
### Proposed solution
Simply add a "close all (n)" option

How will it benefit Desktop and its users?
UX will be improved

**Comment by rafeca** [comment]
Thanks for the feedback @kevdeveloper!

Just to confirm, did you drag these files by mistake and or there's any scenario where you would want to drag multiple files to Desktop (where some/most of them are not git repositories)?

I think fixing this should be quite easy, so I'll take a look at it.

**Comment by kevdeveloper** [comment]
I dragged them by mistake ;)

**Comment by rafeca** [comment]
I've just created https://github.com/desktop/desktop/pull/10211 which should only show a single modal with all the invalid paths in this situation
