### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by rafaeldev** [desktop/desktop#10208]
### Describe the bug

I have a private application on my owner account. On last weekend I move these projects to team scope https://github.com/fazerorcamento/

After made the move I had problema to push and pull changes (proxy problems) but I delete the folder, clone again (with using ssh) and them open local folder on Github Desktop.

Nevertheless I continue have problem with some operations (seeing on console log) like that:
![image](https://user-images.githubusercontent.com/4596160/87495854-c38cd680-c628-11ea-849c-ed9932bc82dc.png)

I investigate some issues about auth problems. I gave permission to my user on team scope also.

### Version & OS

Version 2.5.3-linux1
Linux Deepin 15.11 (debian stable based)

### Expected behavior

![image](https://user-images.githubusercontent.com/4596160/87496595-48c4bb00-c62a-11ea-8c3a-70a7d5af873e.png)

I expected which companies projects are scoped on my company (like "getninjas" on image)

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

```js
http.ts:149 GET https://api.github.com/repos/fazerorcamento/toguro 404 (Not Found)
t.request @ http.ts:149
request @ api.ts:929
fetchRepository @ api.ts:520
repositoryWithRefreshedGitHubRepository @ app-store.ts:3377
async function (async)
repositoryWithRefreshedGitHubRepository @ app-store.ts:3322
withAuthenticatingUser @ app-store.ts:5070
_fetch @ app-store.ts:4109
refreshIndicatorForRepository @ app-store.ts:2880
async function (async)
refreshIndicatorForRepository @ app-store.ts:2860
refreshAllSidebarIndicators @ app-store.ts:2836
async function (async)
refreshAllSidebarIndicators @ app-store.ts:2836
(anonymous) @ app.tsx:217
install.ts:27 fetchRepository: 'fazerorcamento/toguro' returned a 404
warn @ install.ts:27
fetchRepository @ api.ts:522
async function (async)
fetchRepository @ api.ts:520
repositoryWithRefreshedGitHubRepository @ app-store.ts:3377
async function (async)
repositoryWithRefreshedGitHubRepository @ app-store.ts:3322
withAuthenticatingUser @ app-store.ts:5070
_fetch @ app-store.ts:4109
refreshIndicatorForRepository @ app-store.ts:2880
async function (async)
refreshIndicatorForRepository @ app-store.ts:2860
refreshAllSidebarIndicators @ app-store.ts:2836
async function (async)
refreshAllSidebarIndicators @ app-store.ts:2836
(anonymous) @ app.tsx:217
install.ts:31 [AppStore.withAuthenticatingUser] account found for repository: toguro - rafaeldev (has token)
install.ts:31 proxy url not resolved, protocol not supported
install.ts:31 Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.469s)
http.ts:149 GET https://api.github.com/repos/fazerorcamento/toguro/branches/onboarding-2/push_control 404 (Not Found)
t.request @ http.ts:149
request @ api.ts:929
fetchPushControl @ api.ts:852
refreshBranchProtectionState @ app-store.ts:897
(anonymous) @ app-store.ts:4183
processTicksAndRejections @ internal/process/task_queues.js:85
async function (async)
(anonymous) @ app-store.ts:4161
withPushPullFetch @ app-store.ts:3767
performFetch @ app-store.ts:4143
(anonymous) @ app-store.ts:4112
withAuthenticatingUser @ app-store.ts:5096
async function (async)
withAuthenticatingUser @ app-store.ts:5070
_fetch @ app-store.ts:4109
refreshIndicatorForRepository @ app-store.ts:2880
async function (async)
refreshIndicatorForRepository @ app-store.ts:2860
refreshAllSidebarIndicators @ app-store.ts:2836
async function (async)
refreshAllSidebarIndicators @ app-store.ts:2836
(anonymous) @ app.tsx:217
install.ts:31 [fetchPushControl] unable to check if branch is potentially pushable
Error: Not Found
    at Object.t.parsedResponse (/home/kunta/webpack:/app/src/lib/http.ts:175:4)
    at x.fetchPushControl (/home/kunta/webpack:/app/src/lib/api.ts:853:14)
    at Xe.refreshBranchProtectionState (/home/kunta/webpack:/app/src/lib/stores/app-store.ts:896:29)
    at /home/kunta/webpack:/app/src/lib/stores/app-store.ts:4181:9
    at Xe.withPushPullFetch (/home/kunta/webpack:/app/src/lib/stores/app-store.ts:3766:7)
    at Xe.performFetch (/home/kunta/webpack:/app/src/lib/stores/app-store.ts:4143:5)
    at Xe.refreshIndicatorForRepository (/home/kunta/webpack:/app/src/lib/stores/app-store.ts:2880:7)
    at Xe.refreshAllSidebarIndicators (/home/kunta/webpack:/app/src/lib/stores/app-store.ts:2833:7)
```

### Additional context

The problem is not clear to me and sorry if I can't give relevants infos.
Thanks!

**Comment by rafaeldev** [comment]
Can't create Pull Request also...

![image](https://user-images.githubusercontent.com/4596160/87498363-01d8c480-c62e-11ea-8e2c-5d33933f9a96.png)

**Comment by rafeca** [comment]
Thanks for filling this issue @rafaeldev !

I suggest logging out from GitHub (via the accounts tab in the preferences dialog) and logging it again, and see if you need to grant some additional permissions to GitHub Desktop. Another possibility is to remove the repository from Desktop and re-add it again.

If none of this works, you can try filling an issue in the [Desktop for Linux fork repository](https://github.com/shiftkey/desktop), since I've seen you're using Linux (since the Linux version of Desktop is maintained there, you may get more specific information about possible limitations/workarounds of this problem).

Thanks for using Desktop!

**Comment by rafaeldev** [comment]
@rafeca (chará) you are my hero!

I do the sign out and when do the sign in again I see that:

![image](https://user-images.githubusercontent.com/4596160/87566809-e4414480-c699-11ea-853b-715c9a3e6e49.png)

After grant my project get the right scope:
![image](https://user-images.githubusercontent.com/4596160/87567105-4437eb00-c69a-11ea-8509-9adb8292488c.png)

Thanks!
