### ISSUE TITLE
I cannot discard any change through Github for desktop anymore

### ISSUE THREAD

**Issue by AlessandraRossoVooDoo** [desktop/desktop#10205]
### Describe the bug

I cannot discard any change through Github for desktop anymore

### Version & OS

Version 2.5.3. 
Windows 10.

### Steps to reproduce the behavior

1. Go to Current repository
2. Select changes I want to discard
3. right-mouse-click on the changes
4. Click on Discard Changes
5. nothing happens

### Expected behaviour

the selected changes should disappear

### Actual behaviour

changes stay there. 
Interestingly, the files look empty. I am not sure that's the problem.
Also, the undiscarded changes are preventing me to pull new changes.

**Comment by rafeca** [comment]
Thanks for the report @AlessandraRossoVooDoo !

Can you provide some additional information so I can investigate what's going on?

1. Do you see the file in the "changed files" list on the left column?
2. Does it solve the issue if you right click on the "XX changed files" text and select "Discard all changes..."?

Thanks

**Comment by rafeca** [comment]
Thanks for your response! I'm gonna close this issue but if you stumble across the same issue again please reopen and we can investigate further.

Kind regards

**Comment by ChrisEmteq** [comment]
I am having this issue, I am not able to switch branch or discard changes since there are changes in two files that have changes. Same steps as described above. Should I raise a new issue or can this be re-opened? Version 2.9.0

I did have stashed changes but it let me get rid of those, it still won't allow me to remove them.

EDIT: I used the CLI to `git checkout origin/develop --force` which gave me a detached head which I could then 'discard' the **"**file changes**"** which then let my use the app to switch etc. Fixed.

**Comment by ElwoodHogan** [comment]
im having this same problem.  Right clicking and clicking "discard changes" does nothing.

**Comment by kaipyroami** [comment]
Same here.

**Comment by mxxrten** [comment]
Same here

**Comment by GhullieUser** [comment]
Same here

**Comment by pabloi** [comment]
+1

**Comment by sMcGuckinBTI** [comment]
Me too same issue followed recommended steps

**Comment by GhullieUser** [comment]
My problem was fixed when I stopped trying to discard changes while the editor/program I was working in is still open. Close the program and it'll work, the files were just in use

**Comment by mlph-jandag** [comment]
Same fix I did with @GhullieUser

**Comment by saropa** [comment]
+1

**Comment by inayi** [comment]
+1

**Comment by davicyyo** [comment]
+1

**Comment by ShimelesT** [comment]
Same here
I can discard added lines
I can discard removed lines
BUT I can not discard changed lines action is disabled

**Comment by danielecolaj** [comment]
same here, we've been having this issue for months on our team and I'm shocked that this bug is still there given that it's a fundamental operation one has to be able to rely on

To be precise "discard changes" can be clicked on after selecting the file, but nothing happens


Maybe someone from GHDT can give a list of reasons why the operation can (silently) fail? It may help a lot...

**Comment by luislodosm** [comment]
Same here. Right click, discard changes, file stays.

**Comment by PoeHaH** [comment]
Same here

**Comment by guyal** [comment]
Same

**Comment by CFMcConnell** [comment]
In Tools (upper right gear), what happens if you uncheck **Hide whitespace changes**?

**Comment by omerguzelelectronicguy** [comment]
I have the same problem. It is not a solution but maybe helps to understand the problem. In my case, the repo is in the server path but the terminal or the vs code is opened on the local computer. when I change anything > save then redo > save. it shows there is a changed file but nowhere is changed. when I make those steps in the server terminal or programs it is fine.  Additionally, when I make those steps in the repo cloned on the local path it is also ok.

**Comment by ner00** [comment]
Same problem smh

**Comment by blazing-light** [comment]
Same problem rn

**Comment by sc8di** [comment]
Problem still here.
Unity project and a bunch of sprites that no one has touched.

**Comment by deWaardt** [comment]
Seems that discarding files with only whitespace changes doesn't work.

My repo is currently stuck. Can't pull because active changes, can't get rid of the changes.
Can't recover my stash either because unable to restore stash when changes present on branch.

**Comment by skaylie** [comment]
same problem

**Comment by BrenCyberLegends** [comment]
Same here

**Comment by suhanishri** [comment]
Same here. The problem still persists for me. Unable to discard the changed files and hence unable to pull from upstream to update the local repo

**Comment by omerguzelelectronicguy** [comment]
`git config core.filemode false` This solved my problem.

**Comment by alfred-stokespace** [comment]
In our case we had a user controlling a MS Excel file in the repo and it turned out that Windows10 was convinced there was a file lock on that file and that's what GH Desktop was keying off. This was discovered after I suggested they delete the file under contention. The user reported failing to be able to delete (due to lock) and not having the file open anywhere explicitly. I suggested a restart and ensure nothing opens up upon startup and attempt the gh-desktop discard action again. 

GH Desktop can't control OS level file locks and windows is kind of notorious for file locking being a mysterious and frustrating topic.

**Comment by BrunoGattai** [comment]
Same issue here

**Comment by KarinaDaniluck** [comment]
same issue here

**Comment by ItayTur** [comment]
my case:
1) selecting a changed file
2) right click & `Discard Changes`
3) Confirmation modal is shown
4) confirm

Expected: Changes will be discarded
Actual: Changes aren't discarded and loading is not ending.

**Comment by tatelax** [comment]
same

**Comment by robin-myers-sb** [comment]
Same

**Comment by Johnney1337** [comment]
same

**Comment by Darknerior** [comment]
+1

**Comment by davisjm4** [comment]
Same problem and having this problem with my students too. Can't discard. If I stash, it stashes, but keeps the change in the changes list. Can't pull with changes present. Deleted the file, but it still shows, added it to the git ignore file, but still. Closed out of Desktop and closed it and all editors with task manager, opened it back up and still it persists.

**Comment by TheMagicMax** [comment]
Same problem as mentioned by the previous posts. Discard does nothing. The problem occured when i tried to cherry-pick a commit to another branch. The stash worked but the changes remained and the cherry-pick failed.

**Comment by davisjm4** [comment]
I'm not sure if it's resolving all of the instances, but mine have been resolved: in the task manager, end anything and everything related to UE and Git - some to look for are: Unreal Editor, Hub for UE5 runtime traces, Live Coding Console, Git LFS (I think this is the one that was me issues as well as the live coding console,) once they're closed, open github desktop again and try to discard again

**Comment by abstractspoon** [comment]
In my case I have some 3rd-party dlls saved to the output folder of my repo.

When I updated my app from the internet, it overwrote those dlls which was expected, but GH Desktop now won't let me discard those changes. I tried restarting GHD.

**Comment by oguzhantorayev** [comment]
You guys have the editor/program you're working on is still open so it's not gonna discard your changes on GitHub. You need to close the editor to do it

**Comment by CodingPupper** [comment]
For those that are having this problem - A method that seems to work for me is to create a branch you have no intention of ever committing to your main branch. Any time you go to log off, commit your work for that day, then open the extra branch. If you open git again and have changes that just wont go away, commit them to the useless branch, then poof! theyre gone. It's not full proof, but it at least has saved me and my team some corruptions

**Comment by clod44** [comment]
**This is guaranteed to happen** when you also push the MS Access db to your repo but the MS Access application was already open when you were trying to commit/change branch/discard changes. it messes up everything. in my case MS Access might be immediately rewriting to the file when github tries to change it.

ie. make sure there is no lock on the file and no application is using those files when the "discard changes does nothing" issue happens

**Comment by rmusser01** [comment]
+1

**Comment by Photosounder** [comment]
Same here, it's happening across multiple repos for generated files, I have to "Show in Explorer" and delete files myself. Five years and no fix, this is the power of open source 😂.

**Comment by jojorabbit** [comment]
The issue might be related to how the Recycle Bin is handled for the D drive (in my case). Specifically, when I disabled the Recycle Bin for that drive, I noticed files weren't being discarded as expected.

Upon re-enabling the Recycle Bin, even with a small allocation like 10MB, the system seemed to move files to it without issue. It's possible that the system consistently attempts to move files to the Recycle Bin, and when it's disabled, it simply skips the action. Ideally, I'd prefer an option for permanent deletion.

This information could help troubleshoot the problem.

**Comment by asarbu** [comment]
I am working in Visual studio code, closed all running instances that had the file open. Still, discarding did not work.

**Comment by barbalex** [comment]
This is extremely annoying. I am completely blocked from working on my project.

I tried:

- discarding all changes using the ui
- repeating after restart
- removing all deleted files (the discarded appear here every time I discard)
- git rm --cached -r .
- git reset --hard
- git clean -f
- removing the repository and all its files, then re-clone
- uninstalling github desktop and reinstalling

What else can I do?

The only thing I can think of is not to use github desktop any more.

*****************
edit: I found the reason:
```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'src/formsAndLists/action/Index.tsx'
  'src/formsAndLists/action/index.tsx'
  'src/formsAndLists/actionReport/Index.tsx'
  'src/formsAndLists/actionReport/index.tsx'
  'src/formsAndLists/check/Index.tsx'
  'src/formsAndLists/check/index.tsx'
  'src/formsAndLists/checkReport/Index.tsx'
  'src/formsAndLists/checkReport/index.tsx'
  'src/formsAndLists/place/Index.tsx'
  'src/formsAndLists/place/index.tsx'
  'src/formsAndLists/project/Index.tsx'
  'src/formsAndLists/project/index.tsx'
  'src/formsAndLists/subproject/Index.tsx'
  'src/formsAndLists/subproject/index.tsx'
```

I had been working on linux. This naming does not work on MacOS...

**Comment by davisjm4** [comment]
You have to close out of the programs and then open task manager, every
time it happened to me, there's background processes using the files - I
was using Unreal, so any background processes from Unreal, Unreal Editor,
or anything similar, I needed to end, then it worked.

Thank you,
Josiah Davisson
NVACTE VP Engineering and Tech. Ed.
Computer Science Teacher
TSA (Tech. Student Association) Advisor
Las Vegas High School
DevCat Studios <https://sites.google.com/nv.ccsd.net/wildcatstudios/>
