### ISSUE TITLE
Improvements to the build pipeline

### ISSUE THREAD

**Issue by rafeca** [desktop/desktop#10202]
This issue tracks the improvements made to the Desktop build pipeline to reduce the bundle size of the production assets and the startup time of the Desktop app.

### Add interop layer to import commonJS modules

* **Impact**: This will fix the issues we currently have on unit tests where the code imports a commonJS dependency (see [this comment](https://github.com/desktop/desktop/pull/10053#discussion_r450302353)) and allows to remove the nasty hacks that mix imports with requires ([example](https://github.com/desktop/desktop/blob/development/script/generate-octicons.ts#L13)).
* **PR**: https://github.com/desktop/desktop/pull/10182

### Enable Tree shaking

* **Impact**: This will reduce the bundle size and improve the startup time
* **PR**: https://github.com/desktop/desktop/pull/10185

### Use terser as the minifier

* **Impact**: This will reduce build times, reduce the bundle size and improve the startup time
* **PR**: https://github.com/desktop/desktop/pull/10196

**Comment by niik** [comment]
I believe all the core pieces of this has been merged now, right @rafeca?

**Comment by rafeca** [comment]
> I believe all the core pieces of this has been merged now, right @rafeca?

Yup, https://github.com/desktop/desktop/pull/10244 is just a nice improvement
