### ISSUE TITLE
GitHub Desktop 2.5.3 Clone Repository Error

### ISSUE THREAD

**Issue by gshomali** [desktop/desktop#10216]
### Describe the bug
when trying to clone a forked repository, it reaches 84% the exits with error: filename in tree entry contains backslash: '\'
### Version & OS
GitHub Desktop version 2.5.3, OS: Windows 10

### Steps to reproduce the behavior

1. On GitHub desktop left pane, at the top left click "Add" -> Clone Repository
2- Select the forked repository from the list then click "Clone". Repository cloning stops with the following:
Cloning into 'D:\OfficeWork\DA-Dev\Github\LMSAdmin'...
remote: Enumerating objects: 646, done.        
remote: Counting objects: 100% (646/646), done.        
remote: Compressing objects: 100% (411/411), done.        
error: filename in tree entry contains backslash: '\'| 839.00 KiB/s             
fatal: Not all child objects of c04fc6721b6ec167e5f3910b86ee7757bcedf420 are reachable
fatal: index-pack failed

Would you like to retry cloning ?

### Expected behavior
To get the selected repository cloned locally
 
### Actual behavior
Clone does not complete and exits with the following error information:
error: filename in tree entry contains backslash: '\'| 839.00 KiB/s             
fatal: Not all child objects of c04fc6721b6ec167e5f3910b86ee7757bcedf420 are reachable
fatal: index-pack failed

[2020-07-16.desktop.production.log](https://github.com/desktop/desktop/files/4932328/2020-07-16.desktop.production.log)

**Comment by steveward** [comment]
@gshomali thanks for the report. It looks like you are running into https://github.com/desktop/desktop/issues/10004#issuecomment-644075555. You can download the [beta version of GitHub Desktop](https://github.com/desktop/desktop#beta-channel), which has the updated version of Git that should resolve this issue.
