### ISSUE TITLE
Crash due to Minified React error

### ISSUE THREAD

**Issue by ZhangVivianHua** [desktop/desktop#10210]
I pulled my new project to the master,and then created a new branch. Another mumber of our group created another new branch.Then,I clicked to his branch to see wether he had change any file.As soon as I clicked back to my branch, the error accured.It immediatly closed the window and warning as below:  

```
Invariant Violation: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at i (file:///app/renderer.js:59924:13)
    at s (file:///app/renderer.js:59934:5)
    at Xe (file:///app/renderer.js:61100:9)
    at file:///app/renderer.js:61392:102
    at co (file:///app/renderer.js:61666:28)
    at go (file:///app/renderer.js:61727:115)
    at fo (file:///app/renderer.js:61718:12)
    at bo (file:///app/renderer.js:61807:88)
    at rr (file:///app/renderer.js:62751:13)
    at ir (file:///app/renderer.js:62767:37)
```
Version: 2.5.3
OS: Windows 10.0.18363

**Comment by rafeca** [comment]
Thanks for the report @ZhangVivianHua !

I'm going to do a quick investigation, since we take crashes seriously. If you stumble across the same problem again (or have some reproducible steps to get the crash) it would be super helpful!

Thanks again and apologies for the crash!

**Comment by steveward** [comment]
I'm going to close this stale since we have no seen any further reports of this bug in the past four years.
