### ISSUE TITLE
Commit Failing when Copying and trying to commit a clone of the following repository: https://github.com/electron-react-boilerplate/electron-react-boilerplate

### ISSUE THREAD

**Issue by benjstern** [desktop/desktop#10215]
`Commit failed - exit code 1 received, with output: '/c/Users/Benjamin Stern/AppData/Roaming/npm/yarn: line 5: cygpath: command not found
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'C:\Users\Benjamin Stern\AppData\Local\GitHubDesktop\app-2.5.3\resources\app\git\node_modules\yarn\bin\yarn.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}'`

**Comment by benjstern** [comment]
This seems to be caused when cloning a repository w/ `git clone --depth 1 --single-branch https://github.com/electron-react-boilerplate/electron-react-boilerplate.git your-project-name`

**Comment by benjstern** [comment]
Still getting this issue only have 2 files in the commit queue, 

package.json
yarn.lock

extracted repo https://github.com/electron-react-boilerplate/electron-react-boilerplate
yarn
built
modified dependencies of the package json
    "bootstrap": "^4.5.0",
    "jquery": "^3.5.1",
    "popper.js": "^1.16.1",
    "react-bootstrap": "^1.2.2",
    "react-icons": "^3.10.0",
    "sqlite": "^4.0.11",
    "sqlite3-offline": "^4.3.1"

which i added after source map
"source-map-support": "^0.5.19",

ran yarn again
built

tried to commit.


```
Commit failed - exit code 1 received, with output: '/c/Users/Benjamin Stern/AppData/Roaming/npm/yarn: line 5: cygpath: command not found
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'C:\Users\Benjamin Stern\AppData\Local\GitHubDesktop\app-2.5.3\resources\app\git\node_modules\yarn\bin\yarn.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}'

```

**Comment by rafeca** [comment]
Hey @benjstern ! Thanks for filling this report!

Can you provide some reproduction steps so I can investigate the problem you're facing? Are you cloning the repository from GitHub Desktop or from the command line? What commands are you executing?

Thanks!

**Comment by tierninho** [comment]
@benjstern  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by zedd3v** [comment]
I got the same issue when trying to commit to a branch.

Commit failed - exit code 1 received, with output: '/c/Users/karlo/AppData/Roaming/npm/yarn: line 5: cygpath: command not found
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'C:\Users\karlo\AppData\Local\GitHubDesktop\app-2.5.3\resources\app\git\node_modules\yarn\bin\yarn.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by Brouilles** [comment]
Same here.

**Comment by AustEcon** [comment]
I'm having the same issue with this template: https://github.com/electron-react-boilerplate/electron-react-boilerplate

Every time I try to commit I get:

```
/c/Users/<username>/AppData/Roaming/npm/yarn: line 5: cygpath: command not found
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.9.3\resources\app\git\node_modules\yarn\bin\yarn.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Did anyone figure out why this is happening? The other GIT bash and Git GUI apps work fine I only have this problem with GitHub desktop

**Comment by AustEcon** [comment]
Okay I have managed to fix this with a hack...
(I fully uninstalled gitbash + GithubDesktop and re-installed but the issue persisted - this includes purging my AppData/Local and AppData/Roaming for any directories named GithubDesktop first to be sure..)

The issue still persisted...

So I manually copied the `node_modules` dir into the required place: 
- C:\Users\<username>\AppData\Local\GitHubDesktop\app-2.9.3\resources\app\git\

Now GitHub desktop can find the files it needs and is now working :) 

I hope this helps anyone else who may encounter this problem.
