### ISSUE TITLE
keep getting = fatal:badcongih7 in file c:user/joe/.gitconfig

### ISSUE THREAD

**Issue by joeborak** [desktop/desktop#10212]
brew install git
keep getting = fatal:badcongih7 in file c:user/joe/.gitconfig

**Comment by rafeca** [comment]
Hey @joeborak !

It looks like you may have some invalid configuration in your `.gitconfig`, can you paste the contents of the file `c:/user/joe/.gitconfig` here so we can debug it?

**Comment by joeborak** [comment]
Thank you, for getting back to me and for all your help.

Sincerely,
JB

*Below is what comes up:*

C:\Users\Joe>c:/user/joe/.gitconfig
The system cannot find the path specified.

C:\Users\Joe>.gitconfig

C:\Users\Joe>
[main 2020-07-18T13:05:47.855Z] update#setState idle
(node:94620) Electron: Loading non context-aware native modules in the
renderer process is deprecated and will stop working at some point in the
future, please see https://github.com/electron/electron/issues/18397 for
more information
(node:94620) Electron: Loading non context-aware native modules in the
renderer process is deprecated and will stop working at some point in the
future, please see https://github.com/electron/electron/issues/18397 for
more information
(node:94620) Electron: Loading non context-aware native modules in the
renderer process is deprecated and will stop working at some point in the
future, please see https://github.com/electron/electron/issues/18397 for
more information
(node:94620) Electron: Loading non context-aware native modules in the
renderer process is deprecated and will stop working at some point in the
future, please see https://github.com/electron/electron/issues/18397 for
more information
(node:94316) Electron: Loading non context-aware native modules in the
renderer process is deprecated and will stop working at some point in the
future, please see https://github.com/electron/electron/issues/18397 for
more information
(node:94316) Electron: Loading non context-aware native modules in the
renderer process is deprecated and will stop working at some point in the
future, please see https://github.com/electron/electron/issues/18397 for
more information
[main 2020-07-18T13:06:17.859Z] update#setState checking for updates
[main 2020-07-18T13:06:17.934Z] update#setState idle

**Comment by rafeca** [comment]
Hi @joeborak, it doesn't seem you were able to paste the contents of your `.gitignore` file (I think I pasted the path incorrectly in my previous message).

You try opening that file with `notepad`.

I think the path should be `c:/Users/joe/.gitconfig` (if `joe` is your username), so you can try doing:

```
notepad.exe c:/Users/joe/.gitconfig
```

And then copy and paste here the contents of the file.

**Comment by joeborak** [comment]
Thank you for getting back to me.  I tried to do what you asked.

I put in notepad.  Nothing?

It's still giving me the error message in Github desktop.

I also tried to re-install GitHub desktop.  The same thing happened.

Thank you, again

Joe Borak

**Comment by joeborak** [comment]
Hi Rafael,
I tried VS this morning.

I did receive this below:

user]
    name = Your Name
    email = borakj@gmail.com
    name = Joe
[core]
    editor = code --wa
 1s
I don't know if this helps..

Thanks again for your help

JB

**Comment by rafeca** [comment]
Hi @joeborak,

Yes this helps! It looks like there's some things wrong with your `.gitconfig` file:

1. First thing, first line should be `[user]` instead of `[user]`.
2.  The line containing `name = Your Name` can be deleted, since you already have your name defined two lines later.
3. The line containing ` 1s` doesn't seem to be correct, can you delete it?

So, the contents of the file should look like:

```
[user]
    email = borakj@gmail.com
    name = Joe
[core]
    editor = code --wa
```

**Comment by joeborak** [comment]
Hi Rafael,

I have completed it.  Please see below:  What would you like me to do next?
[user]
    email = borakj@gmail.com
    name = Joe
[core]
    editor = code --wa

**Comment by joeborak** [comment]
PS C:\Users\Joe> c:/user/joe/.gitconfig
c:/user/joe/.gitconfig : The term 'c:/user/joe/.gitconfig' is not
recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:1 char:1
+ c:/user/joe/.gitconfig
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound:
(c:/user/joe/.gitconfig:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Joe>

**Comment by Shadyfire2020** [comment]
**null**

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joeborak** [comment]
Hello,

Is someone still helping me?

Thank you,

JB

**Comment by rafeca** [comment]
Hey @joeborak ! That's all, what happens now when you execute GitHub Desktop? does it work correctly?

**Comment by joeborak** [comment]
Hi Rafael,

Sorry, to say. No.
Still the same error as before.
"fatal: bad config line 7 in file C:/Users/Joe/.gitconfig"

I am so frustrated at this point. This just makes me want to quit.

JB

**Comment by rafeca** [comment]
I'm sorry for your frustration, as a last resort you can try deleting `C:/Users/Joe/.gitconfig` completely: GitHub Desktop will populate it correctly when it gets opened. Let me know if this helps

**Comment by joeborak** [comment]
Hi Rafael,

It will not delete.  Is there someone else that can help me?
Or this there a phone number?  So, I may speak to someone.

Thank you,

Joe Borak

**Comment by rafeca** [comment]
> It will not delete.  Is there someone else that can help me?

You can try renaming it to `.gitconfig_backup` or something if you're afraid, this way you can rename it back later without having any issue.

> Or this there a phone number?  So, I may speak to someone.

We're a very small team and we don't offer phone support directly (take into account that GitHub Desktop is a free opensource app). If you're a GitHub Enterprise customer, though, you can call its phone support and they will probably be able to assist you

**Comment by joeborak** [comment]
Good Morning Rafael,

Thank you, for your help. I am not a GitHub Enterprise customer.

I am brand new and just started with Microsoft Learning.  Since I lost my
job.

Since I can't even get the download to configure correctly.

I am now super frustrated.

I give up.

Thank you,

JB

**Comment by steveward** [comment]
@joeborak do you have GitHub Desktop installed on your machine, or are you just wanting to use Git from the command line? You can also reach out to [GitHub Support](https://support.github.com/) for assistance.

**Comment by joeborak** [comment]
Thank you for your response.

Luckily I had a friend come over this morning.  He was able to fix it.

Thank you, again

JB

**Comment by steveward** [comment]
Glad to hear you were able to get things working!
