### ISSUE TITLE
updating of tags from GitHub not coming to Desktop

### ISSUE THREAD

**Issue by Justin-JHG** [desktop/desktop#10218]
### Describe the bug

updates on tags from GitHub are not flowing through to Desktop

### Version & OS

Windows 10,  Version 2.5.3

### Steps to reproduce the behavior

1. Go to GitHub
2. Create a tag
3. Pull the repo
4. Go to GitHub to delete the tag
5. Pull the repo again in Desktop

### Expected behavior

The tag no longer displayed in Desktop

### Actual behavior

The tag is still displayed.

and the deleting tag option is disabled 
![image](https://user-images.githubusercontent.com/41654878/87735158-11b3fc80-c818-11ea-8b12-6c3e3965dba8.png)
so there is no way to remove the tag from Desktop either

**Comment by steveward** [comment]
@Justin-JHG thanks for contributing. This is the expected behavior in Git -- see https://github.com/desktop/desktop/issues/9946#issuecomment-639609927 for more information.

**Comment by danrowley24081979** [comment]
This is terrible. Please fix, regardless of your own bias.

**Comment by Justin-JHG** [comment]
I agree with you :)

**Comment by kd-tka** [comment]
GitHub Desktop should simply display the current Tags of the local repository:

![image](https://github.com/user-attachments/assets/9cd0b3a6-be8f-46a0-b12e-f7f7962798d7)

As per now, GitHub Desktop does not:

![image](https://github.com/user-attachments/assets/0c72626f-c34f-4874-893f-bfee0d1f6b25)

Please FIX....
