### ISSUE TITLE
Integration with JetBrains IDEs

### ISSUE THREAD

**Issue by WinterSilence** [desktop/desktop#10230]
Please replace constant-strings as 
`SOFTWARE\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhpStorm 2019.2.4` to RegExp's  `SOFTWARE\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\PhpStorm [.\d]+`.
'GitHubDesktop\app-*\resources\app\renderer.js'
Sorry, don't know nodeJs to help with PR.

**Comment by steveward** [comment]
Thanks for the feedback @WinterSilence. We're tracking better support for JetBrains IDEs in #9453, so I am going to close this issue out. Please follow along there for updates.
