### ISSUE TITLE
Encountering a problem while installing github desktop

### ISSUE THREAD

**Issue by Osman-Rafi** [desktop/desktop#10238]
When I'm trying to run the installation file this error message appears.

![image](https://user-images.githubusercontent.com/33856265/87942255-24e7f600-cabe-11ea-9a46-baa338e5de06.png).

I also tried to clear `%LOCALAPPDATA%\GitHubDesktop` directory & restart pc. but nothing works.

**Version**
GitHub Desktop version: [the most recent version found on download page]

**OS version**: [Microsoft Windows 10 [Version 1903]]

**Expected behavior:** [to install]

**Actual behavior:** [error shows up]

**Reproduces how often:** [every time I run the installer]

**Comment by steveward** [comment]
@Osman-Rafi thanks for the report. Could you click `Open Setup Log` and upload that log file in a comment? That should give some more information about why the installation is failing.
