### ISSUE TITLE
[Error] Id returned 1 exit status

### ISSUE THREAD

**Issue by Reclaimer1W** [desktop/desktop#10234]
I am making a simple program using Bhaskara's formula and I get the titled error

Here goes the code:

#include<iostream>
#include<math.h>
using namespace std;

int main(){
	
	float a, b, c, resultado1 = 0, resultado2 = 0;
	
	cout<<"Digite el valor de la variable a: "; cin>>a;
	cout<<"Digite el valor de la variable b: "; cin>>b;
	cout<<"Digite el valor de la variable c: "; cin>>c;
	
	resultado1 = (-b+sqrt(pow(b,2)-4*a*c))/(2*a);
	resultado2 = (-b-sqrt(pow(b,2)-4*a*c))/(2*a);	
	
	cout<<"\nEl resultado numero uno es: "<<resultado1<<endl;
	cout<<"El resultado numero dos es: "<<resultado2<<endl;
		
	
	return 0;
}

Sorry if there is any problem; this is my first post in here.

**Comment by rafeca** [comment]
Hey @Reclaimer1W !

I think you filled the issue in the wrong repository. This repository is about GitHub Desktop, an application that's used to work with GitHub, there's more info in [our official homepage](https://desktop.github.com/).
