### ISSUE TITLE
Favorites for branches?

### ISSUE THREAD

**Issue by sdiedrichsen** [desktop/desktop#10237]
### Describe the feature or problem you’d like to solve

I have many branches and sometimes it's hard to keep track of them. I would like to flag them as favorite or so. 

### Proposed solution

Add a button somewhere, maybe next to the current branch and make a new category in the branches drop-down menu.

**Comment by steveward** [comment]
Thanks for the feedback @sdiedrichsen. I'm going to drop this into #8048 where we are tracking improvements to the branch list.
