### ISSUE TITLE
Wrong error message when trying to publish repo that already exists in organization 

### ISSUE THREAD

**Issue by TimAtFacture** [desktop/desktop#10248]
### Describe the feature or problem you’d like to solve

I accidentally tried to upload a repo whose name matched an existing one in my organization. It didn't affect my files, and I figured out what the problem was, but the error message was not helpful.

### Proposed solution

Either check for an existing repo with the same name separately, or add that to the error message generated. The error message is already pretty wordy, so maybe a link to a troubleshooting page would be better.

### Additional context

Error message text:
  Unable to create repository for organization 'foo'. Verify that it exists, that it's a paid organization, and that you have permission 
  to create a repository there.

**Comment by steveward** [comment]
@TimAtFacture thanks for contributing. The error message when attempting to publish a repository that already exists in an organization says "Verify that the repository does not already exist and that you have permission to create a repository there." That differs from the text you shared -- is it possible you misread it?

**Comment by TimAtFacture** [comment]
![image](https://user-images.githubusercontent.com/41414563/88216654-3e9a5200-cc12-11ea-985f-bffddb08f698.png)

**Comment by steveward** [comment]
@TimAtFacture can you share the version of GitHub Desktop that you are running? This error message was updated recently (see https://github.com/desktop/desktop/pull/9646 and the copy change at https://github.com/desktop/desktop/commit/927b5d9df0f98aebd0a8a473930f45ee6dc6dbbc).

**Comment by tierninho** [comment]
@TimAtFacture  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
