### ISSUE TITLE
File size restriction error message should tell what file is causing the issue

### ISSUE THREAD

**Issue by MathiasYde** [desktop/desktop#10242]
### Describe the feature or problem you’d like to solve

When performing a push, you may risk getting the "File exceeds GitHub's file size restriction (of 100MB)" error. It does not, in fact, mention what file it is.

### Proposed solution

It will benefit greatly to immediately know what file is causing the issue without having to perform further checks and could improve workflow even just a little bit.

For people with slow internet connections, it would benefit greatly if GitHub Desktop would check all file sizes before uploading files, to make sure no time is wasted upon the developer.

### Additional context

Image of the error message:
![image](https://user-images.githubusercontent.com/35201354/87991271-17466680-cae6-11ea-8e3d-12f8ba32c395.png)

**Comment by steveward** [comment]
@MathiasYde thanks for the feedback. This was previously requested in https://github.com/desktop/desktop/issues/5079 and https://github.com/desktop/desktop/issues/8767, and although we do show the specific files before committing I agree this would be helpful before pushing.  See [this comment](https://github.com/desktop/desktop/issues/5718#issuecomment-423957795) if you need assistance removing the large file.

**Comment by Daniel-McCarthy** [comment]
Great call! I would love to work on this, especially as I feel it coincides well with the work I did on #997.
I will start to look into this.

**Comment by ADustyOldMuffin** [comment]
Seeing as there hasn't been much movement on this in around 8 months @steveward I was hoping that I could pick this up.

**Comment by Brother1989** [comment]
#12773

**Comment by Brother1989** [comment]
- [ ] [](url)

**Comment by troys-code** [comment]
@Brother1989 you've linked issue 12773, which seems unrelated to this issue. Typo?
