### ISSUE TITLE
Enable selection / unselection of several files with a Ctrl + Click approach

### ISSUE THREAD

**Issue by paulponcet** [desktop/desktop#10247]
With GitHub Desktop I can select or unselect all files in a go with the checkbox at the top.

However, I often have many changed files (say 50) to be pushed in several commits (say 2 commits of 25 files each), and it is painful to select / unselect 25 of these files one by one with the checkboxes for the first commit.  

It would be very useful and a gain of time to be able to select or unselect files with a Ctrl + Click approach. Is it something you would consider?

**Comment by say25** [comment]
@paulponcet If I am not mistaken both `Ctrl+Click` and `Shift+Click` are supported.

**Comment by steveward** [comment]
@paulponcet like @say25 mentioned you can use those shortcuts to highlight multiple files and then click `spacebar` to select them. I'm going to close this issue out -- thanks for using GitHub Desktop!

**Comment by paulponcet** [comment]
Thanks a lot, I had missed the `spacebar` trick, it works indeed!
