### ISSUE TITLE
GitHub desktop causes data loss when origin is not pulled first before commit

### ISSUE THREAD

**Issue by darkRaspberry** [desktop/desktop#10240]
### Describe the bug

Its may be complicated. Please Read twice.

Clone a repo with GitHub desktop and commit any change then . Commit on web or anywhere else. 
Then commit on GitHub desktop means

GitHub desktop is at commit number `#23` (suppose) Then you commit on somewhere else so the Remote origin is at commit number `#30`(Suppose you commit 7 changes,) .
Then go to GitHub desktop and don't pull origin or refresh repo. Firstly commit. After commit try to push origin. This give u error 
 that remote origin contain unsynced data so GitHub desktop says to pull origin and says to refresh repo then to push origin. If you do so. Its tries to merge data of commit number `#23` and commit `#30` which causes error in data.
I lose a lot of data.
I tries revert the commit still i didn't get success.

### Version & OS

GitHub desktop : 2.5.3
Microsoft Windows [Version 10.0.20170.1000]

### Steps to reproduce the behavior

Explained above

### Expected behavior

No data loss. and first refresh changes and to commit in a way causes no data loss.

### Actual behavior

causes conflict in data and shows old data in repo.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context
example.
https://github.com/darkRaspberry/Forest/commit/1309ed94078372d159f6aacb388ac96ff44f1c2f
This is the merge your GitHub Desktop done automatically causing error

https://github.com/darkRaspberry/Forest/commit/76e6fdbafe82e7f0ff529e7ae199c7f75839741e
This is a reverted commit. as i tried to get my data back by reverting commit.
still nothing happened.

#### Serious issue when collaborating with other members

**Comment by darkRaspberry** [comment]
Git bash unix git manage this very well. and avoid data loss by merge

**Comment by tierninho** [comment]
@darkRaspberry Thanks for filing this issue and apologies for the frustrating experience. Any change you could upload your logs from that day? See the Help menu in Desktop.

**Comment by darkRaspberry** [comment]
I almost cleaned that GitHub desktop. And purely shifted to WSL.
I am having problem with that merge.
##### Specific 
while pushing commits to remote. If GitHub desktop detect commit on remote server it tries to merge automatically.

That's the merge causing me problem.

**Comment by darkRaspberry** [comment]
I try to produce same issue and send u logs.

**Comment by tierninho** [comment]
Closing this for now as we do not have enough information to proceed.
