### ISSUE TITLE
Feedback when cloning repository with LFS activated

### ISSUE THREAD

**Issue by rodrigoalcarazdelaosa** [desktop/desktop#10258]
### Describe the bug

When cloning a repository that has [Git LFS](https://git-lfs.github.com/) activated, if we do it from the terminal (using the `git` command), after the _Updating files_ step, we see a _Filtering content_ step (where the LFS files are actually downloaded).

If we do it with Github Desktop, we don't have any feedback, so it seems that the process got stuck.

### Version & OS

Github Desktop 2.5.3 and macOS 10.15.6.

### Steps to reproduce the behavior

1. Try to clone [this repository](https://github.com/rodrigoalcarazdelaosa/rodrigoalcarazdelaosa.me) with Github Desktop (it has LFS activated).
2. Cloning apparently gets stuck after _Updating files_.

### Expected behavior

I'd expect the same feedback we get when cloning from the terminal with the `git` command (on that step it should say something like _Filtering content_).

### Actual behavior

We don't have any information about what's happening, so it seems the process got stuck.

### Screenshots

![image](https://user-images.githubusercontent.com/9049533/88365201-8e4d5a80-cd85-11ea-892c-97a9a7ffd448.png)

### Additional context
I actually aborted the process several times thinking my Internet had went down or there was a problem with the app itself, until I tried to clone the repository via `git` and then I saw that missing step after _Updating files_...

**Comment by rodrigoalcarazdelaosa** [comment]
Something is not right with this. I let the app running but nothing happened after waiting more than 15 minutes. I just cloned the repository using `git clone` and the _Filtering content_ step did not last that much (and it got cloned successfully)

**Comment by steveward** [comment]
@rodrigoalcarazdelaosa thanks for the feedback. There is actually a PR open (https://github.com/desktop/desktop/issues/10258) to implement LFS output and resolve the original issue (https://github.com/desktop/desktop/issues/3171). I'm going to close this issue out since we already have a tracking issue around this. Thanks for using GitHub Desktop!
