### ISSUE TITLE
Allow to set a file system path as remote

### ISSUE THREAD

**Issue by irvnriir** [desktop/desktop#10257]
### Describe the feature or problem you’d like to solve

It misses control to set as Primary Remote a local repository (`D:\<<..>>`) to use Push to export the changes to backup drive/location .

(I see GHD as a minimalistic all-that-needed git interface (otherwise its no point to use it), and it fits this role perfectly)

### Proposed solution

Add function to select local repository, to `Repository \ Repository settings \ Remote`.

**Comment by steveward** [comment]
Thanks for the feedback @irvnriir. I'm going to lump this into our tracking issue for managing multiple remotes in GitHub Desktop.
