### ISSUE TITLE
Fix ignoring file names with [Brackets] in dir path

### ISSUE THREAD

**Issue by orhan897** [desktop/desktop#10253]
When right clicking a file in the gui and selecting ignore file github desktop won't use escape characters to escape special characters like brackets([])

### Proposed solution
Just a check for special characters in the file dir and use the escape char(\) in conjunction?

So instead of writing 
`resources/[3dtext]/log.txt`
it should write
`resources/\[3dtext]/log.txt`
into the .gitignore file.

**Comment by steveward** [comment]
Thanks for the report @orhan897. I confirmed this behavior as well. I'm going to mark it as a priority-3 bug since it does not break app functionality.

**Comment by MaxEtMoritz** [comment]
Experienced this today, wanted to ignore a temp file that is only present while the file i track in the git repo is opened, and the temp file name starts with a #.
