### ISSUE TITLE
Github desktop asks for my login and password only on a specific repository, others repo work fine

### ISSUE THREAD

**Issue by rodrigoratan** [desktop/desktop#10252]
### Describe the bug

Github desktop asks for my login and password only on a specific repository, others repo work fine, and even if I try to authenticate, it wont accept my login/password

### Version & OS

Version 2.5.3 @ Windows 10 (2004build)

### Steps to reproduce the behavior

1. Go to https://github.com/davidortinau/ShellLoginSample
2. Click on "Code" button
3. Choose "Open with Github desktop"
4. Choose clone destination (in my case, this repo has the same name than another repo I have, so I just choose another name to stop the conflict)
5. Click clone
6. see the error

### Expected behavior

Clone the repo

### Actual behavior

A modal dialog appears saying "Authentication failed<BR>We were unable to authenticate with github.com. Please enter your username and password to try again.
Username:
Password:
But even if I fill out the fields it won't authenticate or clone the repo

### Screenshots

![image](https://user-images.githubusercontent.com/964066/88302201-f182b280-ccdb-11ea-9981-08eff4d345ba.png)

**Comment by steveward** [comment]
Thanks for the report @rodrigoratan. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by rodrigoratan** [comment]
[2020-07-23.desktop.production.log](https://github.com/desktop/desktop/files/4967365/2020-07-23.desktop.production.log)

Ok @steveward , attaching...

**Comment by steveward** [comment]
@rodrigoratan thanks, it looks like the clone is attempting to pull down a repository that no longer exists:

```
2020-07-23T14:52:28.720Z - error: [ui] `git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/davidortinau/ShellLoginSampleOrtinau D:\_GITHUB\ShellLoginSampleOrtinau` exited with an unexpected code: 128.
stderr:
Cloning into 'D:\_GITHUB\ShellLoginSampleOrtinau'...
remote: Repository not found.
fatal: repository 'https://github.com/davidortinau/ShellLoginSampleOrtinau/' not found
```

Was this repository recently renamed?

**Comment by rodrigoratan** [comment]
I guess you found the bug then:

The repository is https://github.com/davidortinau/ShellLoginSample , but then it says that I already have a ShellLoginSample (another repository with the same name) in my parent github folder, It asks me to choose another name and I incorrectly renamed the repository name (first input), not the folder name (second input)

![image](https://user-images.githubusercontent.com/964066/88330802-53561300-cd02-11ea-8328-93ccef7f753d.png)

**Comment by rodrigoratan** [comment]
(By the way, I guess the client should say that the repository is incorrect, and not ask for my credentials. This is a interface issue that was only discovered by my confusion...)
