### ISSUE TITLE
Not recognizing Exterior Editors

### ISSUE THREAD

**Issue by Retro-exe** [desktop/desktop#10250]
**Describe the feature or problem you’d like to solve:**

The problem is that Github desktop is not recognizing sublime text 3 as an "external editor" and instead trying to force my friend to download Atom in order to edit the repository.

**Describe why this issue should be solved:**

Benefits users by actually allowing them to use Github Desktop instead of spending hours trying to figure out why it's not working.

**Additional context:**
![unknown](https://user-images.githubusercontent.com/51489437/88201629-b0c06600-cc15-11ea-94f0-4ed4db13b810.png)

**Comment by steveward** [comment]
@Retro-exe thanks for the report. A couple of questions:

1. Was Sublime Text possibly installed while GitHub Desktop was open? If so, you will need to restart GitHub Desktop in order for the editor to be detected. 
2. Was the portable version of Sublime Text possibly installed?

I just tested out a fresh installation of Sublime Text in a VM and GitHub Desktop correctly detected it.

**Comment by Retro-exe** [comment]
> @Retro-exe thanks for the report. A couple of questions:
> 
> 1. Was Sublime Text possibly installed while GitHub Desktop was open? If so, you will need to restart GitHub Desktop in order for the editor to be detected.
> 2. Was the portable version of Sublime Text possibly installed?
> 
> I just tested out a fresh installation of Sublime Text in a VM and GitHub Desktop correctly detected it.

Thank you for the response. It was #2 that was the problem. Now my friend can help get his mod started.
