### ISSUE TITLE
u

### ISSUE THREAD

**Issue by SSH93** [desktop/desktop#10266]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by SSH93** [comment]
[]()

**Comment by SSH93** [comment]
1

**Comment by locness3** [comment]
Hi @SSH93, please do not spam the issues like this.

**Comment by SSH93** [comment]
> []()
