### ISSUE TITLE
Fullscreen slightly crosses the monitor edge

### ISSUE THREAD

**Issue by mvegter** [desktop/desktop#10267]
### Describe the bug

Full screen GitHub desktop with a multi monitor setup (laptop with secondary monitor) results in a small white line on the other window. The relative positions of the monitor doesn't matter, thus having primary left/right has the same behaviour. Below the screenshot of the edge of a all monitor screenshot. I have not yet experienced/noticed this with other apps.

### Version & OS
Version 2.5.3

OS Name	Microsoft Windows 10 Education
Version	10.0.19041 Build 19041

### Steps to reproduce the behavior

1. Open any application on the primary window
2. Open GitHub desktop full screen on the secondary window
3. Bugs appears at the monitor edge on the primary window, small white line
4. Switching to the other application 'removes'/'hides' the white line

### Expected behavior

Do not cross the border of the monitor on full screen

### Actual behavior

A few pixels over the edge of the monitor

### Screenshots

On the secondary monitor
![image](https://user-images.githubusercontent.com/25134477/88454361-57537380-ce6f-11ea-94df-e79275b6fd40.png)![image](https://user-images.githubusercontent.com/25134477/88454490-6555c400-ce70-11ea-85fc-981a2ef302e4.png)

On the primary monitor
![image](https://user-images.githubusercontent.com/25134477/88454600-12c8d780-ce71-11ea-815e-d48d73055a70.png)

### Logs

Not needed as for as I can tell.

### Additional context
![image](https://user-images.githubusercontent.com/25134477/88454436-1a3bb100-ce70-11ea-8e24-ea395b8cb61f.png)
Laptop (secondary) 1920x1080
Monitor (primary) 3440x1440

Both on 100% scale and layout

**Comment by tierninho** [comment]
@mvegter Thanks for filing this. Labeling this as a bug, pending further investigation.
