### ISSUE TITLE
Can not open in Visual Code Studio due to spawn cmd.exe ENOENT error

### ISSUE THREAD

**Issue by pradiptamishra** [desktop/desktop#10276]
### Describe the bug
Can not open in Visual Code Studio due to spawn cmd.exe ENOENT error

Error: spawn cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

Version: 2.5.3
OS: Windows 10.0.18362

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.
Windows 10

### Steps to reproduce the behavior

1. Go to 'repository'
2. Click on 'repository'
3. Scroll down to 'Choose Menu "Open in Visual Code Studio"

### Expected behavior

The repository is open in Visual Code S
![2020-07-26](https://user-images.githubusercontent.com/12026035/88490530-40de1280-cf6a-11ea-806b-cf28c643aba3.png)
tudio

### Actual behavior
Displays in Desktop

Error: spawn cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

### Screenshots

Add screenshots to help explain your problem, if [applicable.](https://1drv.ms/u/s!AhVG1AhtFsSphO0prmxGD0vbvJBEjA?e=SU6ESk)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@pradiptamishra Thanks for the report. Just to clarify -- is this error only occurring when you attempt to launch Visual Studio Code from GitHub Desktop (i.e. `Repository` > `Open in Visual Studio Code`)?

Could you open the command prompt and share the output of `echo %PATH%`?

If `System32` is not in your PATH, you will see that ENOENT error. You will need to edit your PATH by following [this article](https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/) and adding the following line:

`C:\Windows\system32`

Let me know if that doesn't get things working!

**Comment by tierninho** [comment]
As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
