### ISSUE TITLE
Group cloned repositories in organization or user folders

### ISSUE THREAD

**Issue by locness3** [desktop/desktop#10274]
### Describe the feature or problem you’d like to solve

In organizations, I (and not only me, I think) tend to use vague names for repositories since they are grouped in the organization - like client, frontend etc. However when you're working on things in multiple orgs with GitHub desktop storing all repos in the same folder, you end up with folder name conflicts and have to rename the repository you're cloning.

### Proposed solution

Automatically group cloned repos in folders by organization and user. So, `~
/Documents/GitHub/<username>/<repo>` instead of `~/Documents/GitHub/<repo>`

**Comment by tierninho** [comment]
@locness3 thanks for suggestion!

When the repos are pushed up to GitHub, they'll be grouped by the organization that they're in and therefore visually disambiguated that way. We know it's not ideal for repos you personally created, but we're going to stick with the way it is currently unless we get significantly more signal that a critical mass of users are experiencing this as a problem.
