### ISSUE TITLE
gitHub Desktop Authentication Failed.

### ISSUE THREAD

**Issue by joel-avalos** [desktop/desktop#10283]
### Describe the bug

Hi!
I can't clone repositories using gitHub Desktop, every time when I try to clone the repo using gitHub Desktop I receive this error: **Authentication Failed**.

I can clone the repositories using the command line and my PAT, but I can't clone the repositories using my credentials on gitHub Desktop.

The combinations that I have tried are:
- Email and Browser password
- Email and PAT
- AccountName and browser password
- AccountName and PAT (this combination works using the git clone command in my terminal)

### Version & OS

GitHub Desktop: 2.5.3
git version: 2.20.1
SO: macOS Mojave

### Steps to reproduce the behavior

1. Install GitHub Desktop
2. Go to Preferences -> Accounts
3. Sing in using credentials (account-name and browser password), also using the Browser authentication
4. File -> Clone repositories (I can see the list of repositories)
5. Select 1 repo and press clone
6. Error Authentication Failed. (Here I am trying to use my credentials, combinations describe above)
7. Always getting Authentication Failed

### Expected behavior

Clone the repository using my credentials.

### Actual behavior

Authentication Failed using my credentials

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

2020-07-27T18:44:28.091Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/XXXXX/XXXXXX.git - my-account-name (has token)
2020-07-27T18:44:30.625Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/XXXXX/XXXXX.git /Users/XXXXX/Downloads/projects/git/XXXXX (took 2.203s)
2020-07-27T18:44:30.625Z - error: [ui] `git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/XXXXX/XXXXX.git /Users/XXXXX/Downloads/projects/git/XXXXX` exited with an unexpected code: 128.
stderr:
Cloning into '/Users/XXXXX/Downloads/projects/git/XXXXX'...
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/XXXXX/XXXXX.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Preferences.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)

### Additional context

Using the same command in my terminal works.

git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/XXXXX/XXXXX.git /Users/XXXXX/Downloads/projects/git/XXXXX

When I press enter, the terminal ask for my username and password.

Username: account-name (not email)
Password: PAT (String value, not the name of the PAT)

After this the clone process start.

**Comment by tierninho** [comment]
@joel-avalos Thank you for the report. 

On step 6 when you enter the credentials, does the form look like this? 
<img width="660" alt="84809599-112d0980-afbf-11ea-93f4-e1ad8efcfc2e" src="https://user-images.githubusercontent.com/14828183/88676320-8a854500-d0b1-11ea-9e62-25e25b0e4793.png">

After signing in, can you verify other existing repos can push/pull?

**Comment by joel-avalos** [comment]
Yeah, the step 6 looks like that, but no matters the combinations of credentials that I use I am always getting Authentication failed.

After signing in I can see the list of repositories, but I can't clone theme. If I try to clone the repository gitHub desktop is asking for my credentials (step 6).

Another example if a clone the repositories using the terminal:
`git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/XXXXX/XXXXX.git /Users/XXXXX/Downloads/projects/git/XXXXX`
Username: account-name
Password: My PAT
After cloning the repo I can use the option **Add existing repository**, but If I try to fetch, pull or any operation gitHub desktop ask for my credentials (step 6)

Also in the terminal I can use this command:
`git -c protocol.version=2 clone --recursive --progress -- https://github.com/XXXXX/XXXXX.git /Users/XXXXX/Downloads/projects/git/XXXXX`
Without -**c credential.helper=**, in that case git is cloning the repository without asking my credentials.

**Comment by tierninho** [comment]
Do you have any existing repos that you can verify that work okay (fetch/push/pull)? I believe your authentication from the original sign-in step is not working, and it is not a cloning issue.

**Comment by joel-avalos** [comment]
I have tried with all the git repos that I can see in the list after the signing in. I can't clone any github repo using gitHub desktop but I can clone all of them using the terminal. Also I tried removing my account from gitHub desktop and then using HTTPS link in the option **Clone repository** -> **URL** I got the same result in the stage 6.

I can use gitHub desktop to clone Bitbucket repositories, so when I try to clone a Bitbucket repository in the step 6 I can use my Username and Password and everything works fine. After the first clone I can clone, push, fetch, etc without using my credentials again.

Regards!

**Comment by tierninho** [comment]
Ok. Please create a new repository (`cmd-N`) and try to publish it. I suspect there will be an auth issue will occur. If it does, can you attach the logs found in the Help menu?

**Comment by joel-avalos** [comment]
Hi. Problem solved.

It was a problem with the Proxy. In my global **.gitconfig** I had the proxy like this: <proxy = https://user:@my_proxy> so the authentication against the proxy was failing but gitHub desktop was showing an authentication problem agains my git account.
I changed the proxy to this format <proxy = https://user:**pass**@my_proxy> and now is working fine.

Regards!

**Comment by tierninho** [comment]
Nicely done. Glad to hear!

**Comment by DannyBaine-Entity** [comment]
I'm at step 7, It keeps saying authentication failed

**Comment by DannyBaine-Entity** [comment]
> Do you have any existing repos that you can verify that work okay (fetch/push/pull)? I believe your authentication from the original sign-in step is not working, and it is not a cloning issue.

How do you fix this? Please

**Comment by steveward** [comment]
@DannyBaine-Entity can you share a few more details about the issue you're having? You can also open a new issue and fill out the template for further assistance.
