### ISSUE TITLE
installer no longer works on windows 7

### ISSUE THREAD

**Issue by blueclouds8666** [desktop/desktop#10282]
### Describe the bug

opening the GitHubDesktopSetup.exe on windows 7 gives a KERNEL32.dll error......

### Version & OS

Win7 SP1 x64

### Steps to reproduce the behavior

1. Go to 'https://desktop.github.com'
2. Click on 'download for windows (64 bits)'
3. open downloaded file

### Expected behavior

to just work

### Actual behavior

the installer just doesn't work.
missing procedure "SetDefaultDllDirectories" on KERNEL32.DLL error

### Screenshots

![github desktop developers are useless](https://user-images.githubusercontent.com/52018385/88558243-90384780-d02b-11ea-89b2-aeeff36b9c6d.PNG)

**Comment by blueclouds8666** [comment]
ok i needed the KB2533623 update, but it isn't stated anywhere i need that update.
anyway its fixed

**Comment by tierninho** [comment]
Yes, you are correct. For any other users, it can be found here:https://support.microsoft.com/en-us/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot
