### ISSUE TITLE
Show path of the repository all the time

### ISSUE THREAD

**Issue by stempora** [desktop/desktop#10289]
When you are using multiple times the same repository its hard to identify them.

Example  user/cms, you used it 5 times in 5 different projects. in order to know what project is each you need to hover it until the tooltip with the path will appear. 

Would be nicer to show the path directly ( activated by an option if some wont like it ) under the repository name
user/cms
f:/work/project1/

user/cms
f:/work/project2/  and so on ..

In some other git clients i tried i saw they are using directly the last folder from the path instead of the repository name, but that's not a solution either, best would be both.

**Comment by tierninho** [comment]
@stempora thanks for the feedback and apologies for the frustration this caused.

This looks similar to the suggestions found in #8175 and #8158, which were included in #6460. See #8158 (comment) specifically for the current thinking on this.
