### ISSUE TITLE
Github Desktop is not opening after login in the browser function

### ISSUE THREAD

**Issue by hectorpv10** [desktop/desktop#10284]
### Describe the bug
 i downloaded github desktop.
 i installed the app then i click on the boton sign in and it took me to github.com y logged in using microsoft edge explorer but after i logged in on the browser, it didn't open the app with my acc

### Expected behavior
after i logged in on github.com with my account it should have open the desktop app of github with my account.

### Actual behavior

after i logged in on the browser the app didn't take my account it opens without any account 

### Screenshots
![image](https://user-images.githubusercontent.com/41930344/88593945-53218480-d02e-11ea-9553-2f411c611928.png)

**Comment by tierninho** [comment]
@hectorpv10 Thanks for the report. We are tracking this bug in https://github.com/desktop/desktop/issues/10010. Please use Chrome for the time being if possible.
