### ISSUE TITLE
fail to login in from Github Destkop

### ISSUE THREAD

**Issue by luruibin** [desktop/desktop#10285]
### Describe the bug

fail to login in from Github Destkop

### Version & OS

OS: Mac OS 10.15.6 
GitHub Desktop: the latest version download from official website

### Steps to reproduce the behavior

enter the username and password, but can not login in via the GitHub desktop 
The username and password is correct and can be used to login into the GitHub website from browser.

### Logs
2020-07-28.desktop.production.log
[2020-07-28.desktop.production.log](https://github.com/desktop/desktop/files/4985395/2020-07-28.desktop.production.log)

**Comment by tierninho** [comment]
@luruibin Thanks for the report. It looks like the API is outdated:

```
2020-07-28T00:38:56.905Z - error: [ui] fetchMetadata: unable to load metadata from 'https://api.github.com/meta' as a fallback
Error: Hello there, wayfaring stranger. If you’re reading this then you probably didn’t see our blog post a couple of years back announcing that this API would go away: http://git.io/17AROg Fear not, you should be able to get what you need from the shiny new Events API instead.
```

Have you changed the hosts by any chance?

**Comment by luruibin** [comment]
@tierninho Thank for the reply. 
I changed the hosts file and tried to get around the GFW.  With updated ip address for api.github.com, still not able to login in. The new log file and hosts file is attached. 

[Archive.zip](https://github.com/desktop/desktop/files/4993969/Archive.zip)

BTW:  The desktop software is the Version 2.5.3

**Comment by tierninho** [comment]
There may be some config settings in `~/etc/.ssh/config` or some content in `~/etc/.ssh/known_hosts`, which contains github.com that is interfering, but it is hard to say right now. 

@steveward do you have any insight to this?

**Comment by steveward** [comment]
@luruibin can you run the command `nslookup api.github.com` and let me know what that returns? I would also check your SSH configuration files like @tierninho mentioned since that could be causing this issue.

**Comment by luruibin** [comment]
@steveward, the output of nslookup is attached.
 I also removed all the record in hosts and the login in is still failed, please see the second part of nslookup and new log file. Thank for you help!
[nslookup.log](https://github.com/desktop/desktop/files/4998130/nslookup.log)
[2020-07-30.desktop.production.log](https://github.com/desktop/desktop/files/4998132/2020-07-30.desktop.production.log)

**Comment by luruibin** [comment]
> There may be some config settings in `~/etc/.ssh/config` or some content in `~/etc/.ssh/known_hosts`, which contains github.com that is interfering, but it is hard to say right now.
> 
> @steveward do you have any insight to this?
I do not have the ssh key created yet since it is a fresh new re-installation. Also I check the account setting of Github - There are no SSH keys or CPG key associated with my account.

**Comment by zcl1995** [comment]
@steveward Hi I have met the same problem. The log says

> fetchAccount: failed with endpoint https://api.github.com
when I try to login .
If I use VPN to try to get across GFW, then I got

> fetchUser: failed with endpoint https://api.github.com
> Error: Hello there, wayfaring stranger. If you’re reading this then you probably didn’t see our blog post a couple of years back announcing that this API would go away: http://git.io/17AROg Fear not, you should be able to get what you need from the shiny new Events API instead.

Can you help? Thanks

**Comment by steveward** [comment]
@luruibin are you still having issues logging in to GitHub Desktop? It definitely seems like something in your network is interfering with connection to GitHub's API.

@zcl1995 unfortunately configuring your network settings to work around the GFW isn't something I'm very familiar with.

**Comment by luruibin** [comment]
@steveward The Github is still not working on my PC.  I have download the the latest 2.6.0 version, and it require to login-in through browser. Here is I got problem (screen copy attached). I believe it is the network problem and now I have to use Github website instead the desktop client.


<img width="401" alt="Screen Shot 2020-11-24 at 10 21 03 AM" src="https://user-images.githubusercontent.com/58930771/100038824-3f045d00-2e3f-11eb-88b1-33e090b03ed1.png">

**Comment by steveward** [comment]
@luruibin unfortunately this does seem like a specific issue with your network connection to GitHub. Do Git commands work without issue from the command line?

**Comment by luruibin** [comment]
@steveward the git works fine from command line, I can use git pull/push to update my project in both direction. Thanks.

**Comment by luruibin** [comment]
@steveward , I installed the GitHub desktop on another MS windows10 laptop in same network, and it works fine. The desktop  still not working, I guess some issue happened where the authentication process on the website complete and try to launch the desktop application.

**Comment by steveward** [comment]
@luruibin since GitHub Desktop is working on a different machine I would recommend using something like [Fiddler](https://www.telerik.com/fiddler) to try and diagnose the connection issue. Fiddler allows you to inspect HTTPS traffic. It's not too difficult to work with -- you should be able to run it and inspect the traffic that happens during the authentication attempt. Let me know if that shows anything interesting.

**Comment by vpei** [comment]
This problem has not been solved? I can't log in either.

**Comment by vpei** [comment]
api.github.com    18.179.245.253
