### ISSUE TITLE
Run a (default) command after "New repository" is created.

### ISSUE THREAD

**Issue by bukowa** [desktop/desktop#10290]
### Describe the feature or problem you’d like to solve
Faster development.

### Proposed solution
Allowing to run custom command (or script) after new repository is created would allow us to open this project in our favourite IDE and so faster our development.

**Comment by tierninho** [comment]
Thanks for the suggestion @bukowa !

Once a repo is created you can click the `Open in [editor]` button that would do just that. You can set your editor choice the Preferences/Options.

Hope this helps.
