### ISSUE TITLE
Support developing on remote machines

### ISSUE THREAD

**Issue by lameyer** [desktop/desktop#10299]
### Describe the feature or problem you’d like to solve

I develop on a remote linux machine. So my clone of the repo is not on my computer but rather on a remote server that I ssh to. I use VSCode's [Remote Development with SSH](https://code.visualstudio.com/docs/remote/ssh) in order to run my IDE on my computer but still develop on the remote server. 

Unfortunately, I haven't figured out a way to make Github Desktop work in this case. Since there is no Linux version of the app https://github.com/desktop/desktop/issues/1525 (and I have limitations on what can be installed on the remote server), I also can't install it on the remote server and use it that way. VSCode does have built in source control, but it's much less pleasant to use that Github Desktop.

### Proposed solution

Some way to use SSH to connect to a repo, similar to what VSCode does, would solve this problem and make development so much better for me. This would make Github Desktop useful in so many cases.

**Comment by tierninho** [comment]
@lameyer Thanks for the issue.

At this time there are no official support for GitHub Desktop on Linux, but a former developer of GitHub Desktop helps maintain a fork with Linux builds with limited support:

https://github.com/shiftkey/desktop/releases

Please post the statement there and hopefully someone can advise. Thank you!

**Comment by lameyer** [comment]
@tierninho thanks for the response. The forked linux version _could_ work in some cases, although in this case I have my repo on a remote linux server, but I am still developing on a Macbook. So Github Desktop would be most useful if I could have it installed and running on my Macbook (which of course I can right now), but then have it connect to a git repo via ssh. That way I could use the UI without running a slow/more complex remote sharing setup with the linux server.

I'll probably continue using VS Code's version control support for now, since that is the most performant solution for me. But it would be great if Github Desktop could support remote development setups like this!

**Comment by tierninho** [comment]
Thanks for update. Unfortunately, we are not quite there yet. 
 
I believe this is being tracked in the list of SSH issues in #2579. You can follow along there for updates. Have a good day!
