### ISSUE TITLE
please add a built in code editor

### ISSUE THREAD

**Issue by godalming123** [desktop/desktop#10297]
it is very annoying to have to flick between windows to edit and then publish my code to github and would be nice if there was an always on top option or built in code editor.

**Comment by tierninho** [comment]
@godalming123 Thank you for the suggestion. At this time we are not planning to implement such a feature as we aim to be an alternative way to use GitHub.com, and not a full service development environment. Should we hear further feedback on this, we can review the request at the appropriate time.

**Comment by godalming123** [comment]
Didn't expect such a quick reply thank you.
