### ISSUE TITLE
[Request] Portable version

### ISSUE THREAD

**Issue by UAlbanyErich** [desktop/desktop#10298]
A portable version of GitHub Desktop would allow users to carry their work with them on a USB drive without needing to install Desktop on every new machine they use.  Sure, Desktop doesn't require admin rights to install, but it still requires you to install it and download the repositories on which you want to work.  Students especially, may need to move from lab to classroom to library and back and sit at a different machine every time.  Many places don't keep profiles either, so even getting the same computer doesn't help.  

Without a portable version, a user needs to install GitHub Desktop, log-in and download repositories on every computer before they can start working.  😨 

With a portable version, the user pops in a USB key and goes to work (possibly re-synching repositories).  😄 

A portable version of GitHub Desktop could also resolve [the problem of using multiple accounts](https://github.com/desktop/desktop/issues/3707) which appears in the comments to be important to users, but not to the organization.  🤦 

Thanks.

**Comment by steveward** [comment]
Thanks for the request @UAlbanyErich. Currently we have no plans to release an official portable installer, but you can check out https://github.com/daemondevin/GitHubDesktopPortable which was made by another GitHub Desktop user. I've tested it out and it works well from a USB stick. Hope that helps!

**Comment by UAlbanyErich** [comment]
@steveward I saw that project, but I thought it was dead.  It's had minimal activity, and has had no changes in over 30 months.  The "normal" GitHub Desktop updates very regularly, how can the portable version be still safe and functional?

**Comment by steveward** [comment]
@UAlbanyErich there have not been any commits made to the repository because it works by updating to the latest version once you download and run it. I haven't tested it recently but I believe it should still work without issue.

**Comment by UAlbanyErich** [comment]
FYI, GitHub Desktop Portable is not truly portable.  You can install it on a flash drive and run it, true, but if you install another copy on another flash drive, it will not be separate.  Example:

1. Insert flash drive 1 with GitHub Desktop Portable instance "A" installed.
2. Open instance "A" and sign in.
3. Close instance "A".
4. Eject flash drive 1.
5. Later, insert flash drive 2 with GitHub Desktop Portable instance "B" installed.
6. Open instance "B".
7. Observe that you are already signed into the account from instance "A".

That is **NOT** portable behavior.

**Comment by ghost** [comment]
Come on, don't be lazy. Using unofficial portable version is not a solution, the profile is not portable!

**Comment by daniporr** [comment]
Do you think something like this could work?

https://code.visualstudio.com/docs/editor/portable

---

However, if you only want to avoid the installation phase, on Windows you can:

1. open the installation file "GitHubDesktopSetup-....exe" with any _file archiver_
2. open the "GitHubDesktop-X.X.X-full.nupkg" file
3. extract the "lib/net45" folder
4. inside it you can find the "GitHubDesktop.exe" executable
5. everything should work as expected!

**Note that this is only a way to avoid the "installation", the app files will still be stored in you user account folder** (`AppData\Roaming\GitHub Desktop`).
