### ISSUE TITLE
Issue cloning repository - High Importance

### ISSUE THREAD

**Issue by nosallan** [desktop/desktop#10291]
### Describe the bug

At the time to copy the repository: https://github.houston.softwaregrp.net/arcsight-autoqa/ESM  using the gitHub desktop is downloading the content of the repository  https://github.houston.softwaregrp.net/arcsight-autoqa/ESM-Releases

### Version & OS

Version 2.5.3 . Windows 10

### Steps to reproduce the behavior

1. Clone repository https://github.houston.softwaregrp.net/arcsight-autoqa/ESM
2. Error: clone the content of the repository https://github.houston.softwaregrp.net/arcsight-autoqa/ESM-Releases

### Expected behavior

Obtain the content of the repository https://github.houston.softwaregrp.net/arcsight-autoqa/ESM

A clear and concise description of what actually happened.

**Comment by tierninho** [comment]
@nosallan Thank you for the report. Please attach your logs from the day this happened -- see the Help menu in Desktop to find your logs.

**Comment by tierninho** [comment]
As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
