### ISSUE TITLE
flatten a multi-nested list

### ISSUE THREAD

**Issue by zy8277mm** [desktop/desktop#10306]
def flatten(a_list):
    result=list()
    a_list=list(str(a_list))
    for value1 in a_list:
        if value1==("["):
            a_list.remove(value1)
        elif value1==("]"):
            a_list.remove(value1)
        elif value1==(" "):
            a_list.remove(value1)
        elif value1==(","):
            a_list.remove(value1)
        else:
            result.append(int(value1))
            print(result)
    return result
if __name__ == "__main__":
    print(flatten([[1], 2, [[3, 4], 5], [[[]]], [[[6]]], 7, 8, []]))

**Comment by niik** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
