### ISSUE TITLE
How to flatten a multi-nested list

### ISSUE THREAD

**Issue by zy8277mm** [desktop/desktop#10305]
def flatten(a_list):
    result=[]
    a_list=list(str(a_list))
    for value1 in a_list:
        if type(value1)=="int":
            result.append(value1)
            a_list.remove(value1)
        else:
            for value2 in value1:
                if type(value2)=="int":
                    result.append(value2)
                    a_list.remove(value2)
                else:
                    for value3 in value2:
                        if type(value3)=="int":
                            result.append(value3)
                            a_list.remove([value3])
                        else:
                            for value4 in value3:
                                if type(value4)=="int":
                                    result.append(value4)
                                    a_list.remove(value4)
                        
    return result

if __name__ == "__main__":
    print(flatten([[1], 2, [[3, 4], 5], [[[]]], [[[6]]], 7, 8, []]))

**Comment by niik** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
