### ISSUE TITLE
Please add option to display full path to repository in left hand pane

### ISSUE THREAD

**Issue by CarlosOnline** [desktop/desktop#10304]
### Describe the feature or problem you’d like to solve

I frequently create multiple clones of the same projects which differ only by the parent directory.  

e:\clone**1**\MyProject
e:\clone**2**\MyProject
e:\clone**3**\MyProject

In GIthub Desktop it is difficult to tell which repository I am in because they all show the same names **MyProject** in this example.

To make my life easier please add an option to display the repository folder path instead: **e:\clone2\MyProject**.

### Proposed solution

How will it benefit Desktop and its users?
Make it easier to work with multiple clones of a repository.

### Additional context

**Sample:**
![image](https://user-images.githubusercontent.com/3691895/89114256-2bb42880-d42f-11ea-8980-cb1abfb5cdd7.png)

**Comment by tierninho** [comment]
@CarlosOnline thanks for filing this issue. If you hover over the repo names, you will be able to see the unique paths. 

We know it is not the ideal for everyone, but we had to weigh many options which were included in #6460. See https://github.com/desktop/desktop/issues/8158#issuecomment-524644986 specifically for the current thinking your similar suggestion. Thanks again!

**Comment by SharonWatSPIE** [comment]
Yes please do this - I'd really like for us to be able to see the full repo path... and why not?
