### ISSUE TITLE
GitHub Desktop Losing Connection to remote

### ISSUE THREAD

**Issue by ddsjoberg** [desktop/desktop#10316]
### Describe the bug

After cloning a repo, GitHub Desktop has been losing connection to the remote repo.  Rather than having a button where I can push commits to the remote, it is a button to publish the branch.
![image](https://user-images.githubusercontent.com/26774684/89232594-c0e12980-d5b5-11ea-9c3f-c82855c5aa2d.png)

I can verify in git Bash that the remote is indeed still connected, and pushing from the command line works.
![image](https://user-images.githubusercontent.com/26774684/89232660-e2daac00-d5b5-11ea-93ed-7a1279b52fcb.png)

The problem persists after deleting the repo and re-cloning it. The issue is not isolated to a single repo.
Thank you for your attention!

### Version & OS

Windows 10
GitHub Desktop Version 2.5.3

**Comment by tierninho** [comment]
@ddsjoberg Thanks for reporting this. Are you seeing any authentication messages? 

Also, is it possible to include your logs? See the Help menu in Desktop.

**Comment by ddsjoberg** [comment]
@tierninho thank you for the response!  No, there are no other authentication messages. Also, although the button says publish, after I make changes, if I press it, the new commits are added to the remote.

Here are the logs.
[2020-08-04.desktop.production.log](https://github.com/desktop/desktop/files/5019609/2020-08-04.desktop.production.log)

Thank you!

**Comment by tierninho** [comment]
Hmmm, not much to go on so far. I cloned the repo successfully and the `fetch` button appear as expected.

As this is not isolated to a single repo, I suspect it may be an issue with authentication.

Try signing out then back in. 

If that doesn't work, try:

- Go to Github.com account settings and click on Applications
- Go to Authorized OAuth Apps and revoke the Github Desktop application
- Follow the Sign out and Sign In steps within the Github Desktop application (in Options)

If these don't work, we may have to explore more drastic measures. 😬

**Comment by tierninho** [comment]
Let us know if you require any further assistance. Thanks!

**Comment by ddsjoberg** [comment]
Thank you!

Re-authorizing did fix the issue immediately. But the next day was disconnected again.  I know this isn't much to go on, so i I have time to investigate further i'll add the info here
