### ISSUE TITLE
Feature: Allow requested changes from code reviews to be seen in gh desktop.

### ISSUE THREAD

**Issue by git-ced** [desktop/desktop#10312]
### Describe the feature or problem you’d like to solve

If the specific branch has a pull request, it would be nice if the requested changes or comments in the conversation tab from the site to be seen. 

### Proposed solution

I think this would be a lot of help in terms of developer productivity. Allowing developers to apply the requested changes faster by doing 'Open in Code Editor' instead of navigating it. Also instead of going to the site itself, i think this could save time.

### Additional context

Personally, i would label this as a minor request only as it doesn't have that much of a value for now. I also think that this would require a lot of dev time, as it also might change the current user flow.

Currently, this is what i see when the branch has a pull request.
<img width="855" alt="image" src="https://user-images.githubusercontent.com/46030248/89176139-96926a80-d5bb-11ea-951f-ec9d9018e369.png">

**Comment by tierninho** [comment]
@git-ced Thank you for the suggestion! I am going to fold this in to the Notifications request here https://github.com/desktop/desktop/issues/2825. Although it is not the same thing entirely, it is within the same topic area and your suggestion should be explored in the same discussion should we move forward.
