### ISSUE TITLE
Couldn't parse author identity

### ISSUE THREAD

**Issue by vmoulds01** [desktop/desktop#10314]
### Describe the bug

When cloning a GIT repo I am getting error message "Couldn't parse author identity" 

### Version & OS

GitHub Desktop Version - v2.5.3
OS - Mac Mojave 10.14.16

### Steps to reproduce the behavior

1. Clone private GIT repo 
4. See error attached in screenshot

### Expected behavior

Do not expect to see this error message at all

### Actual behavior

See this error message multiple times and keep continually having to close error message.

### Screenshots

See attached screenshot of error 
![GitHubError](https://user-images.githubusercontent.com/63194960/89199617-b703fa00-d5a6-11ea-9110-9b86ba35d761.png)

### Additional context

I did notice in the last commit message there was a ~ and thought that might have caused an issue similar to - https://github.com/desktop/desktop/issues/9373.  So i tried the fix mentioned in issue #9373 and updated prior commit message to remove anything that could be considered an invalid character but that hasn't resolved the issue.

**Comment by tierninho** [comment]
@vmoulds01 Thanks for filing this.

It is possible the commit message contains non-printing ASCII characters but hard to tell at this point. You can see that GitHub itself [doesn't know how to handle them](https://github.com/ospaarmann/github_desktop_issue_6836/commit/45b19854f6b9b542da25381d4a1574f11ba43783):

<img width="1002" src="https://user-images.githubusercontent.com/359239/52884495-862acd80-3144-11e9-94cb-9eb7d41a5d99.png">

Are you able to share full or partial logs? See the Help menu in Desktop and feel free to redact any info.

Alternatively, you may extract the commit to a new repository that you could share? I'm only interested in the commit message and the specific characters inside.

The rough steps to do this:

`git checkout --orphan <branchname>` to create a new branch separate from the main history of your repository
`git cherry-pick [sha]` to add the problem commit to the branch (will likely cause conflicts)
feel free to transform this into an empty commit (`git commit --allow-empty`) as long as the commit message is the same
add a new remote representing the public repository that you can share this commit on
`git push [new-remote] <branchname>` to push that single commit

**Comment by tierninho** [comment]
@vmoulds01  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
