### ISSUE TITLE
Repeated Failed Logins on GitHub Desktop

### ISSUE THREAD

**Issue by ozinfotech** [desktop/desktop#10313]
### Describe the bug

I'm attempting to create a fork of a project, and when I go to publish, GitHub Desktop asks for credentials with a "Authentication failed" and "We were unable to authenticate with gist.github.com. Please enter your username and password to try again." errors. My credentials, which work fine on github.com, are rejected each time I try them. I've tried resetting my password on github.com to something else, and am still having the issue with GitHub Desktop.

### Version & OS

GitHub Desktop Version: 2.5.3
Windows 10 Professional Version: 2004 (OS Build 19041.388)

### Steps to reproduce the behavior

1. Click the **Publish branch** button
2. See error

### Expected behavior

Expected behavior would be to publish the branch.

### Actual behavior

Actual behavior is a repeated request for credentials.

### Logs

Logs attached.
[2020-08-03.desktop.production.log](https://github.com/desktop/desktop/files/5016768/2020-08-03.desktop.production.log)

**Comment by steveward** [comment]
@ozinfotech thanks for the report. This is a known bug -- when trying to push commits to a gist, GitHub Desktop will fall back to basic authentication and not detect your current credentials. As a workaround for this you should be able to drop into the command line and run a `git push` to push your changes. 

See https://github.com/desktop/desktop/issues/2973 for more information about some of the known issues with using Gists in GitHub Desktop.  I am going to reference this issue in #2973 and close it out for the time being.
