### ISSUE TITLE
Make publish branch a separate button 

### ISSUE THREAD

**Issue by amazinglarry4tw** [desktop/desktop#10322]
### Describe the feature or problem you’d like to solve

While using Github for Windows Desktop, the Fetch origin / Publish / Push buttons are the same depending on the context, and it's incredibly frustrating when I swap to a repository where I was last on a branch that's been merged & deleted from the remote repository and my first instinct is to sync down, but I instead end up publishing the branch.  These really need to be separate buttons.

### Proposed solution

Instead of having the button change context, please consider having dedicated buttons for pulling / pushing / publishing.

**Comment by steveward** [comment]
@amazinglarry4tw thanks for the feedback. This isn't something that we would likely change, but if we hear enough feedback about this in the future it could be something consider. It sounds like you may be interested in a feature that allows remote branches that have been deleted to instantly be deleted in your local repository. This option is being discussed over in https://github.com/desktop/desktop/issues/9824 if you'd like to follow along there.
