### ISSUE TITLE
Authentication Failed, why?

### ISSUE THREAD

**Issue by Troy420** [desktop/desktop#10320]
![image](https://user-images.githubusercontent.com/25684892/89301797-a59d1980-d69c-11ea-8bdd-9800cf3adc7e.png)

**Comment by niik** [comment]
Hey @Troy420, GitHub.com had a temporary (now recovering) availability issue which manifested itself as authentication errors in GitHub Desktop. The issue should resolve itself momentarily but you can follow https://www.githubstatus.com/ to see updates in real time.

**Comment by steveward** [comment]
@Troy420 this should be resolved now -- let us know if you're still having issues.

**Comment by Troy420** [comment]
its fixed now. thanks!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
