### ISSUE TITLE
old code auto deploy

### ISSUE THREAD

**Issue by ravindermaxxmann112** [desktop/desktop#10327]
Hi,

My problem is that when i commit code on github with updated code. and all change has been displayed after deployment.
but after 10 to 12 days my changes has been lost and old code is updated automatically. while we have not make any commit and upload code on github.

is this possible?  please assist us.

**Comment by tierninho** [comment]
@ravindermaxxmann112 Thanks for the issue. If nothing has changed, then your code should not disappear.

To clarify your steps:
- You commit code on Desktop and push to github.com
- On github.com  and Desktop the changes are present after deployment 
- A few days later, the code is missing on both github.com  and Desktop. Old is back.

Does anyone else have access to your repo? Did you check the history and commit logs?

Can you share the logs in Desktop for the day that happened? See the Help menu in Desktop.

**Comment by tierninho** [comment]
@ravindermaxxmann112  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
