### ISSUE TITLE
App is consuming 500% cpu

### ISSUE THREAD

**Issue by nicholas-eden** [desktop/desktop#10335]
### Describe the bug

While running idly in the background the app is consuming 500% cpu.  It ran down the battery on my laptop in under 15 minutes.

### Version & OS

Github Desktop: 2.5.3

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,3
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  Boot ROM Version:	428.0.0.0.0
  SMC Version (system):	2.45f4

### Steps to reproduce the behavior

Unsure, I only use it to clone down repos.

### Expected behavior

It should be close to 0% cpu usage while not being used.

### Actual behavior

The CPU usage is absurd.

### Screenshots

<img width="1680" alt="Screen Shot 2020-08-05 at 10 05 41 AM" src="https://user-images.githubusercontent.com/2496835/89442678-11669d00-d704-11ea-91f9-8c5047aab3bc.png">

### Logs

[2020-08-05.desktop.production.log](https://github.com/desktop/desktop/files/5030032/2020-08-05.desktop.production.log)
[2020-08-04.desktop.production.log](https://github.com/desktop/desktop/files/5030033/2020-08-04.desktop.production.log)

### Additional context

I've had the app running in the background for a few days.  Probably used it to clone 10+ repos from an enterprise github server.

**Comment by tierninho** [comment]
@nicholas-eden Thanks for the issue and apologies for the frustration! 

Not much to go on at this point. I did spot `proxy url not resolved, protocol not supported` error in your logs. Are you using a proxy? Having any issues connecting via proxy? 

We have had multiple reports of this over the last year or so, but haven't been able to pinpoint it as everyones set up is unique. Anything else about your set up that you can share and might be relevant? Does this happen all the time or just when upgrading to v2.5.3?  

Some errors in your logs:

Too long to load
`2020-08-05T15:43:23.008Z - info: [ui] Background fetch for 13 repositories took 20.132sec`

Proxy settings are bad
`2020-08-05T17:08:45.682Z - info: [ui] proxy url not resolved, protocol not supported`

**Comment by nicholas-eden** [comment]
I use a VPN (Pulse Secure) most of the time, but it is not required to connect to the enterprise Github server.  

This is a freshly wiped laptop.  I installed Github Desktop about a week ago and used it to start cloning repos.  I never had an older version.

I'll try to repro and get back to you.

**Comment by nicholas-eden** [comment]
Also, after closing the app through the Mac UI the process kept running.  I'm not sure if you noticed in the screenshot, but it has `(Render` at the end.  Maybe the rendering engine is the problem.

**Comment by steveward** [comment]
@nicholas-eden I'm going to close this out since we now have a tracking issue for this in #10625. Please follow along there for updates.
