### ISSUE TITLE
Application freezes and permanantly stops working

### ISSUE THREAD

**Issue by dedrazer** [desktop/desktop#10344]
### Describe the bug

This happened twice.

After a week or so of use, the application goes into Not Responding mode. Any attempts to End Process are futile unless the computer is restarted.

After restarting the computer, the application just won't open.

After reinstalling, the problem occurred again after a week or so.

### Version & OS

Windows 10 Pro Version 1909
Github Desktop v 2.5.3

### Steps to reproduce the behavior

N/A

### Expected behavior

Proper app launch and not going into non-responsiveness.

### Actual behavior

App becomes non-responsive and refuses to launch.

### Screenshots

None.

### Logs

[https://www.file-upload.com/hftf8nr957nz](url)

### Additional context

This happened on DELL G5 Laptop and didn't happen on my previous Lenovo.

**Comment by tierninho** [comment]
@dedrazer Thanks for the report. Please try adding your logs again as that link does not work.

In the meantime, I would try reinstalling the app based on the following steps:

Close GitHub Desktop
Delete the `%AppData%\GitHub Desktop\` directory
Delete the `%LocalAppData%\GitHubDesktop\` directory
Reinstall GitHub Desktop from desktop.github.com

**Comment by tierninho** [comment]
As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by dedrazer** [comment]
the link doesn't work if you click on it but if you copy and paste it into the address bar

**Comment by tierninho** [comment]
Please `copy+paste` your logs or just `drag+drop` them into the comments here. Sorry for the bother but that site seems too spammy.

**Comment by dedrazer** [comment]
[2020-07-22.desktop.production.log](https://github.com/desktop/desktop/files/5073012/2020-07-22.desktop.production.log)
[2020-07-23.desktop.production.log](https://github.com/desktop/desktop/files/5073013/2020-07-23.desktop.production.log)
[2020-07-24.desktop.production.log](https://github.com/desktop/desktop/files/5073014/2020-07-24.desktop.production.log)
[2020-07-28.desktop.production.log](https://github.com/desktop/desktop/files/5073015/2020-07-28.desktop.production.log)
[2020-07-02.desktop.production.log](https://github.com/desktop/desktop/files/5073016/2020-07-02.desktop.production.log)
[2020-07-21.desktop.production.log](https://github.com/desktop/desktop/files/5073017/2020-07-21.desktop.production.log)

**Comment by tierninho** [comment]
Thank you for the logs. Unfortunately, not much to go on. I see some connectivity issues, which may be been the cause for some of the issues you face, but not to the point you described. Also, this proxy error `proxy url not resolved, protocol not supported` was spotted. Do you use a proxy by chance? Any anti-virus software? Sometimes this interferes.

**Comment by dedrazer** [comment]
I use Bitdefender, no VPN.
