### ISSUE TITLE
Occurs sometimes randomly - App infinitely asks for bitbucket credentials despite them being correct

### ISSUE THREAD

**Issue by VinceHPicton** [desktop/desktop#10348]
### Describe the bug

Upon trying to push/pull from remote bitbucket repo desktop app repeatedly asks for my login credentials - "Authentication failed" the credentials are correct this is absolutely beyond doubt. This bug only occurs sometimes seemingly totally randomly. Sometimes removing my local repo and readding it works, sometimes closing and opening works, sometimes I just can't push until it decides to stop bugging out.

### Version & OS

OS: Windows 10. Desktop. Version 2.5.3

### Steps to reproduce the behavior

-- I cannot reproduce this consistently, it seems to appear randomly --
Requirements to get this bug as far as I know:
create a local repo and link it to a bitbucket remote, then attempt to push/pull from it triggering GitHub desktop to ask for credentials.

### Expected behavior

Pull/push successful upon correct creds being entered

### Actual behavior

App says authentication failed and asks for credentials again.

### Screenshots

N/A

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@VinceHPicton Thank you for the report. Can you attach your logs from that day? Please see the Help menu in Desktop.

**Comment by tierninho** [comment]
As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
