### ISSUE TITLE
Desktop is wiped clean when quitting before triggering protocol handler from browser

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#10341]
Desktop repos, settings, etc are blown away if Desktop is quit before the user clicks the `Open in Desktop` protocol handler in the browser. Upon opening Desktop, the app is missing all the user data.

Maybe related to: https://github.com/electron/electron/issues/23852

Reproduce:
- Open Desktop and logout
- Preferences > Sign In > Sign In with browser
- Wait for browser to display handler, don't click any buttons
- Go back to Desktop and quit
- Go back to browser and click Open Desktop button
- App is opened and data is missing

Tested this is Version 2.5.4-beta1 and data was retained. In 2.5.4-test7 the data was missing.

![Screen Shot 2020-08-06 at 11 19 04 AM](https://user-images.githubusercontent.com/14828183/89584186-5ad3ec80-d7d7-11ea-8a53-3131076ec01f.png)

**Comment by niik** [comment]
We believe this was an environment-specific issue where the previous binary was being launched. Downgrading from electron 9 causes the indexeddb databases to get reset (https://github.com/electron/electron/issues/24882).
