### ISSUE TITLE
github tags

### ISSUE THREAD

**Issue by Aiyaful** [desktop/desktop#10357]
tags that already push cannot deleted in local repo, deleted tags in remote repo cannot fetch or pull in local repo.

Version 2.5.3
win10 OS

**Comment by niik** [comment]
Hi @a-golovanov, thanks for opening this and sorry for the inconvenience!

I'm copying an answer I gave to https://github.com/desktop/desktop/issues/9938 which should apply here as well.  As you've already state GitHub Desktop doesn't support deleting tags that have already been pushed to the remote. 

You're only able to delete a local tag up to the point when you push it. Deleting pushed tags is a much more complicated affair than one might think and this has to do with how Git itself is designed.

If you're curious about the technical details as to why Desktop won't let you delete a pushed tag the `git tag` man page [has a great section on this](https://git-scm.com/docs/git-tag#_on_re_tagging).

> ### On Re-tagging
> What should you do when you tag a wrong commit and you would want to re-tag?
> 
> If you never pushed anything out, just re-tag it. Use "-f" to replace the old one. And you’re done.
> 
> But if you have pushed things out (or others could just read your repository directly), then others will have already seen the old tag. In that case you can do one of two things:
> 
> The sane thing. Just admit you screwed up, and use a different name. Others have already seen one tag-name, and if you keep the same name, you may be in the situation that two people both have "version X", but they actually have different "X"'s. So just call it "X.1" and be done with it.
> 
> The insane thing. You really want to call the new version "X" too, even though others have already seen the old one. So just use git tag -f again, as if you hadn’t already published the old one.
> 
> However, Git does not (and it should not) change tags behind users back. So if somebody already got the old tag, doing a git pull on your tree shouldn’t just make them overwrite the old one.
> 
> If somebody got a release tag from you, you cannot just change the tag for them by updating your own one. This is a big security issue, in that people MUST be able to trust their tag-names. If you really want to do the insane thing, you need to just fess up to it, and tell people that you messed up. You can do that by making a very public announcement saying:
> 
> ```
> Ok, I messed up, and I pushed out an earlier version tagged as X. I
> then fixed something, and retagged the *fixed* tree as X again.
> 
> If you got the wrong tag, and want the new one, please delete
> the old one and fetch the new one by doing:
> 
> 	git tag -d X
> 	git fetch origin tag X
> 
> to get my updated tag.
> 
> You can test which tag you have by doing
> 
> 	git rev-parse X
> 
> which should return 0123456789abcdef.. if you have the new version.
> 
> Sorry for the inconvenience.
> ```
>
> Does this seem a bit complicated? It should be. There is no way that it would be correct to just "fix" it automatically. People need to know that their tags might have been changed.

If you're certain that you're the only one using the repository or that no one else has fetched your tag yet you can follow the instructions in the man page to manually delete the tag on the remote.

**Comment by Aiyaful** [comment]
okay thanks for the answer, sourcetree can delete tags and tags in repo, I try to minimize usage of apps to github desktop only, I guess I still need to use sourcetree.
