### ISSUE TITLE
Github Desktop couldn't find a new forked repository

### ISSUE THREAD

**Issue by meirkr** [desktop/desktop#10352]
### Describe the bug
I've forked some repositoy.
Copied to clipboard the clone url.
via the menu, I chose to clone a repository, using the tab of Github.com.
Pasted the URL of my new forked repository.
Github Desktop couldn't find a new forked repository:
"Sorry. I Can't find any repository matching https://github.com/meirkr/abstractions.xunit.git"

### Version & OS
v 2.5.3
Windows 10.

### Steps to reproduce the behavior

1. Go to 'File --> Clone Repository'
2. Click on tab 'Github.com'
3. paste 'https://github.com/meirkr/abstractions.xunit.git'

### Expected behavior
Clone should have been available.

### Actual behavior
Error message: "Sorry. I Can't find any repository matching https://github.com/meirkr/abstractions.xunit.git"

### Screenshots
![image](https://user-images.githubusercontent.com/26039904/89727592-0460eb00-da2f-11ea-9806-10b131b43dd3.png)

### Logs
[2020-08-09.desktop.production.log](https://github.com/desktop/desktop/files/5046886/2020-08-09.desktop.production.log)

### Additional Context
As a workaround, I have cloned it successfully using the 3rd tab:
![image](https://user-images.githubusercontent.com/26039904/89727689-a54fa600-da2f-11ea-9c15-219f2dbf48d7.png)

**Comment by niik** [comment]
Hi @meirkr, thanks for opening this. I understand how the current behavior would be confusing when trying to paste a clone url. The workaround that you posted is the expected way to clone a repository using a URL. The filter on the first tab only filters the list based on what's shown on each row of the list.

I could see how more intelligent matching could be useful but given how little feedback we've gotten about this it won't be something we'll prioritize in the near term.

As an aside, when cloning from the website I find that using the `Code` button to clone directly from the browser is convenient

![image](https://user-images.githubusercontent.com/634063/89770751-7bfe4b00-daff-11ea-9df2-db5fa2dcb198.png)

Just a tip in case you hadn't seen it before, it is a bit hidden away.

**Comment by meirkr** [comment]
Thanks for your quick unswer.
I now understand the differences between the tabs.

1. I recommend just renaming the tab, instead of "Github.com" which looks like a general, having something like "Your Github Repositories" will be much clear to users it is about filtering own repos. 
I wouldn't have confused if that was the name of the tab.

2. as for your aside proposal "Open with Github Desktop", I've tried this first, but it appears if one has other tool like "Tortois Git" it catches the trigger before the Git Desktop app. Tell me if you think i should open its own issue.
![image](https://user-images.githubusercontent.com/26039904/89776461-9beb3a00-db12-11ea-90c3-faed4b7e312f.png)

**Comment by niik** [comment]
Hi @meirkr, thanks for getting back to us, we appreciate it.

> 2\. f one has other tool like "Tortois Git" it catches the trigger before the Git Desktop app

Yeah, there's unfortunately no way for us to guarantee that other applications on your machine doesn't interfere and register the protocols that we use.

> 2\. Tell me if you think i should open its own issue.

Thanks but we've got an issue for that already (https://github.com/desktop/desktop/issues/4754) and there's unfortunately not a whole lot we can do about it.

**Comment by meirkr** [comment]
ok.
What about #1?

> I recommend just renaming the tab, instead of "Github.com" which looks like a global github related, having something like "Your Github Repositories" will be much clear to users it is about filtering own repos.
> I wouldn't have confused if that was the name of the tab.
> What do you think?
> Would it be a suitable resolution for this issue?

?

**Comment by xiaoheiX66** [comment]
I have some of the same  troubles with your previous situation. I can not fork others private store and so I can not follow up. I think it may be due to private ownership of the warehouse.Of course, it is also possible that I am missing some important steps.Maybe now you have solved it , you can continue to update these content.
