### ISSUE TITLE
Can't clone private repository, keeps asking me to authenticate

### ISSUE THREAD

**Issue by lokeuei** [desktop/desktop#10356]
### Describe the bug

I created a private repo on github.com that is empty. I tried using github desktop on windows 10 to clone it. but I get a dialog box asking me to authenticate, it keeps saying that Authentication Failed and keeps asking for my credentials. 

### Version & OS

Windows 10
Github Desktop: Version 2.5.3

### Steps to reproduce the behavior

Clone repository
Select URL
Paste URL (https://github.com/lokeuei/practisim-stage-builder.git)
error appears

### Expected behavior

expect it to authenticate correctly and clone the repo onto my desktop.

### Actual behavior

keeps saying that Authentication Failed and keeps asking for my credentials. 

### Screenshots

Add screenshots to help explain your problem, if applicable.
![image](https://user-images.githubusercontent.com/3144545/89743171-42710580-da55-11ea-984f-6c63fd6066dc.png)

### Logs

[2020-08-09.desktop.production.log](https://github.com/desktop/desktop/files/5048542/2020-08-09.desktop.production.log)

### Additional context

I have two factor authentication turned on using a Security Key (Yubikey)

**Comment by niik** [comment]
Hi @lokeuei, thanks for opening this. Looking at your log file it seems like the credentials stored on your machine may have gotten corrupted or stale. Could you please try opening `File -> Options` and signing out of your account and then signing in again?

<img width="619" alt="image" src="https://user-images.githubusercontent.com/634063/89771040-faf38380-daff-11ea-9e27-e374a5ad6864.png">

**Comment by tierninho** [comment]
@lokeuei  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
