### ISSUE TITLE
When the branch has no commits, the Commit button always says “Commit to master”

### ISSUE THREAD

**Issue by yakovmanshin** [desktop/desktop#10353]
### Describe the bug
When the branch has no commits and the checked-out branch is not called “master,” the commit button still says “Commit to master.”

### Version & OS
GitHub Desktop 2.5.3 on macOS 10.15.6.

### Steps to reproduce the behavior
1. Create a new repository (either in GitHub Desktop or in terminal; in the second case add the repo to the app);
2. Uncommit the initial commit so the branch has no commits at all;
3. In terminal, rename the branch using `git branch -m <new_name>` (in the following screenshots, `git branch -m dev` has been used);
4. Return to GitHub Desktop.

### Expected behavior
The branch name is updated both in the branch switcher and in the Commit button.

### Actual behavior
Though the branch switcher displays the new branch name, the Commit button still says “Commit to master.”

Once the branch has at least one commit, the button’s title uses the correct branch name.

### Screenshots
No commits: correct branch name in the branch switcher; incorrect name in the Commit button.

<img width="1072" src="https://user-images.githubusercontent.com/4648742/89731017-6b40cd00-da4c-11ea-8d3a-2ba1a1131ff9.png">

At least one commit: correct branch name in the branch switcher; correct name in the Commit button.

<img width="1072" src="https://user-images.githubusercontent.com/4648742/89731019-709e1780-da4c-11ea-8738-8f787780a0c4.png">

**Comment by niik** [comment]
Hi @yakovmanshin, thanks for opening this!

This issue was reported in https://github.com/desktop/desktop/issues/10318 and is indeed a bug when dealing with unborn branches. We've fixed the issue in https://github.com/desktop/desktop/pull/10324 and it should make its way into the next production release in a couple of weeks.
