### ISSUE TITLE
Github desktop on other git servers?

### ISSUE THREAD

**Issue by zayn666** [desktop/desktop#10365]
### Describe the feature or problem you’d like to solve

Does it support adding and working with other git servers? I want it to use just how i use it for github but on the work git server. I can i work with it just like on github?

### Proposed solution

If its not, please consider adding it as it helps everyone to keep theyre workflow on private git servers

**Comment by niik** [comment]
Hi @zayn666, GitHub Desktop supports basic Git functionality on non-GitHub servers. All functionality obviously won't be present (such as pull requests, issue autocompletion, co-authors, @mentions etc) and we won't be able to offer any support.

See https://github.com/desktop/desktop/tree/development/docs/integrations for the documentation that exists on use of other services.

**Comment by zayn666** [comment]
ok, thanks
