### ISSUE TITLE
Newer Commits on Remote

### ISSUE THREAD

**Issue by cmcdow** [desktop/desktop#10362]
### Describe the bug

I am unable to publish on the website via the desktop application (Mac). Whenever, I have attempted to publish, I get and error stating that I have commits on the remote not on my local branch. Whenever it attempts to fetch, nothing occurs. I have attempted reinstalling the desktop application, deleting the online repository, creating clones, all to no avail. 

### Version & OS

OS: High Sierra 10.13.5
Github Desktop: 2.5.3

### Steps to reproduce the behavior

1. Click on Publish branch
2. Wait
3. Error occurs. Attempt to fetch.
4. No changes

### Expected behavior

An updated online repository

### Actual behavior

1. Click on Publish branch
2. Wait
3. Error occurs. Attempt to fetch.
4. No changes

### Screenshots
![Screen Shot 2020-08-10 at 10 30 06 PM](https://user-images.githubusercontent.com/69122248/89854134-ba742400-db58-11ea-996d-cf6c5981a0d7.png)
### Logs

[2020-08-11.desktop.production.log](https://github.com/desktop/desktop/files/5054589/2020-08-11.desktop.production.log)

**Comment by niik** [comment]
Hi @cmcdow, thanks for opening this and sorry to hear that this is causing problems for you.

It looks like the local repository's `master` branch doesn't have a tracking branch set up. In Desktop parlance this means that it's not 'published'. I don't understand how that's happened though. It seems like you created the repository on GitHub.com initially. Did you clone the repository using GitHub Desktop or using the Git command line tools?

You can manually set the upstream tracking branch using the Git CLI as such:

```
git branch -u origin/master
```

**Comment by cmcdow** [comment]
Thanks for the response! I apologize... this is new to me. I don't recall what I did first, but I believe I followed [this tutorial](https://youtu.be/qpXxcvS-g3g). 

I copied and pasted the line of code you provided above in terminal, and received this response. I hope I did it correctly... please tell me if I failed to provide an appropriate directory path.
![Screen Shot 2020-08-11 at 7 33 21 PM](https://user-images.githubusercontent.com/69122248/89961816-81938800-dc08-11ea-9534-0a02de566509.png)

**Comment by niik** [comment]
Hi @cmcdow, sorry for not providing more detailed instructions. Before executing the `git branch` command you need to navigate to the directory of the repository. The easiest way to do this on macOS is to click on the `Repository` menu followed by `Open in Terminal`.

<img width="273" alt="image" src="https://user-images.githubusercontent.com/634063/90014082-c2da7500-dca6-11ea-9ea9-35eb9c65929f.png">

I took a quick look at the tutorial and other than it using a pretty old version of GitHub Desktop those steps should work just fine.

Please let me know if there's anything else I can do to help here.

**Comment by cmcdow** [comment]
I can not thank you enough for your help! That seemed to help... however, it seemed to lead to another issue. I received the error below several times...
![Screen Shot 2020-08-12 at 7 31 14 PM](https://user-images.githubusercontent.com/69122248/90080945-9ab43b80-dcd1-11ea-9eb7-b6a296998c7b.png)

I looked up common solutions (most looking like [this](https://thomas-cokelaer.info/blog/2019/08/git-error-solved-the-remote-end-hung-up-unexpectedly/) and this [https://github.com/qmk/qmk_firmware/issues/6992](url) but to no avail. Would you have any words of advice for this? (I didn't realize Github would as time consuming as this, but I am grateful for your assistance...)

**Comment by tierninho** [comment]
@cmcdow Thanks for the update. 

> would it be better if I drag all the files online manually first?

If it is already time-out a few times on Desktop, the large file uploads could be dropping for a various reasons. Did you attempt the online github.com route yet? I would recommend that like you said. 

Gonna close the original issue for now, but happy to provided continued support if you need it.
