### ISSUE TITLE
git 'remote-https'is not a git command.see 'git--help'

### ISSUE THREAD

**Issue by Dishant-Vashistha** [desktop/desktop#10367]
I am facing this issue from a long time while I am trying to publish a repository. 
Error is - git 'remote-https'is not a git command.see 'git--help'
I have applied all methods .
1. UnInstalling git desktop
2. Cleared localappdata as well as appdata.
Nothing worked for me!
Please help me its urgent

**Comment by tierninho** [comment]
@Dishant-Vashistha sorry to hear things still aren't working. Sounds like a bad install or something interfering. 

Are you running any antivirus software on your machine that could be mistakenly flagging the binaries that GitHub Desktop ships with? Try disabling it to see if things start working again.

Also, do you also run into this issue when attempting to publish a repository from the command line?

**Comment by gerardreches** [comment]
Same as @Dishant-Vashistha .

> 
> 
> @Dishant-Vashistha sorry to hear things still aren't working. Sounds like a bad install or something interfering.
> 
> Are you running any antivirus software on your machine that could be mistakenly flagging the binaries that GitHub Desktop ships with? Try disabling it to see if things start working again.
> 
> Also, do you also run into this issue when attempting to publish a repository from the command line?

I'll answer:

I don't have any antivirus installed, just the default Windows Defender that comes with Windows 10 with its default settings (I've never touched it).

No issues at all from the command line.

**Comment by Dishant-Vashistha** [comment]
@tierninho I haven't install any antivirus software.
Yes, I am able to publish a repository using git command line.
But don't know why git desktop stopped working...🙁
Yesterday I have also reinstalled the git desktop...but don't know what's the real issue.
Is there something by which we can get the root cause of this issue?

**Comment by tierninho** [comment]
@Dishant-Vashistha Are there any logs you can share? Please see the help menu in Desktop.

**Comment by niik** [comment]
Hey @Dishant-Vashistha, we've seen a few of these errors pop up recently and we're gonna use #10345 to track them so please follow that issue for any updates.
