### ISSUE TITLE
Delete Default Branch

### ISSUE THREAD

**Issue by nonsoandre** [desktop/desktop#10369]
### Describe the bug
I have changed my github repo default branch on github. However I am unable to do same on git desktop.

**Comment by niik** [comment]
Hi @nonsoandre, sorry to hear you're having problems. GitHub Desktop should automatically pick up on the default branch change done on GitHub.com. If you click on the branch dropdown does it still show the old branch name as the default branch?

<img width="359" alt="image" src="https://user-images.githubusercontent.com/634063/90013507-abe75300-dca5-11ea-910f-52584dd4cf79.png">

If the old branch name is still showing I'd recommend restarting GitHub Desktop. If that still doesn't make it pick up the default branch name change please upload a log file from GitHub Desktop. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. 

One the branch name change has been picked up you should be able to delete the old branch from your local machine.

Thanks!

**Comment by tierninho** [comment]
@nonsoandre  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
