### ISSUE TITLE
Problem when pulling and pushing the code in GithubDesktop application.

### ISSUE THREAD

**Issue by Antony12931a0519** [desktop/desktop#10374]
Issue while pushing the code as well as pulling the code from github desktop application. Facing the same issue saying "git: 'remote-https' is not a git command. See 'git --help'.".  Try to follow the steps mentioned by @steveward , But no luck facing the same issue.

**Comment by steveward** [comment]
@Antony12931a0519 thanks for the report. Since we've seen a couple of cases of this I'm going to close this issue in favor of https://github.com/desktop/desktop/issues/10345.

**Comment by steveward** [comment]
@Antony12931a0519 can you take a look at https://github.com/desktop/desktop/issues/10345#issuecomment-673450605 and see if any of these situations may be applicable to you?
