### ISSUE TITLE
Allow us to delete commits through the website or desktop app please

### ISSUE THREAD

**Issue by YannisWS** [desktop/desktop#10378]
### Describe the feature or problem you’d like to solve

Put a file into my folder and committed to my public repo. I don't want said file public and would like to delete the commit from the history. For other reasons I believe I'm not allowed to make the repo private.

### Proposed solution

Apparently it's possible with commands, so why not on desktop or the website itself? Sounds like a rather important action that should be present by default. It would help for exact situations like I'm in right now.

### Additional context

Maybe something like:
`Desktop App -> Repo -> History -> right-click a Commit in the History -> Remove Commit`

**Comment by niik** [comment]
Hi @YannisWS, thanks for opening this and sorry to hear this is causing you problems.

I can empathize with your desire to remove a commit from a repository and in your scenario chances are that it would result in the file being removed. That said rewriting history (the Git terminology for what you're asking for) can cause a lot of issues for people who are not well versed in the internals of Git and usually ends up causing more problems than they solve. For that reason we have chosen to be very restrictive with what types of history rewriting we support in the app.

We do for example support "deleting" commits up until the point they've been pushed to the remote (that's the Undo commit feature below the commit message form).

If you've pushed your commit already though you should consider your file to be public and if it contains sensitive information you should consult the guide on how to [remove sensitive data from a repository](https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository).

> Warning: Once you have pushed a commit to GitHub, you should consider any data it contains to be compromised. If you committed a password, change it! If you committed a key, generate a new one.
>
> This article tells you how to make commits with sensitive data unreachable from any branches or tags in your GitHub repository. However, it's important to note that those commits may still be accessible in any clones or forks of your repository, directly via their SHA-1 hashes in cached views on GitHub, and through any pull requests that reference them. You can't do anything about existing clones or forks of your repository, but you can permanently remove cached views and references to the sensitive data in pull requests on GitHub by contacting GitHub Support or GitHub Premium Support.
