### ISSUE TITLE
Allow diffing binary files

### ISSUE THREAD

**Issue by Ramobo** [desktop/desktop#10376]
### Describe the feature or problem you’d like to solve

Binary files cannot be diffed under any circumstances.

### Proposed solution

Allow diffing binary files.

My use case a Unity team project. We have to use `.gitattributes` to set Unity YAML files to binary in order to prevent Git from attempting to merge them, which rarely goes well. We then use Unity's YAML Smart Merge tool to properly merge them.
The files are not actually binary, so it would be very useful to be able to diff them directly in GitHub Desktop.

### Additional context

The user should be able to click a button to force diffing a binary file, or use a setting to automatically diff them on selection.

**Comment by tierninho** [comment]
@Ramobo Thank you for the suggestion. Please follow along at https://github.com/desktop/desktop/issues/169 as we have an existing issue for this request.
