### ISSUE TITLE
Getting list of modified files (staged) (from command line?)

### ISSUE THREAD

**Issue by mikazz** [desktop/desktop#10380]
I wish I could get a list of modified files (from terminal for example). This would be helpful when having to perform some additional operations on those files after creating changes. Like automatically reformatting code with tools like those ones:

https://pypi.org/project/pytest-black/
https://pypi.org/project/pytest-isort/

**Comment by tierninho** [comment]
@mikazz Thanks for reaching out. Desktop only grants access to the command line via the `Open in [command line]` option under `Repository` menu. You can select your favorite shell in Options/Preferences. 

Once the repo is opened in the command line, type `git diff` to see the list of modified files. Further info is here: https://git-scm.com/docs/git-diff
