### ISSUE TITLE
Attach your logs by opening the Help menu and selecting Show Logs..., if applicable.

### ISSUE THREAD

**Issue by ayed42** [desktop/desktop#10388]
**[]()**_[]()_

**Comment by ayed42** [comment]
Attach your logs by opening the Help menu and selecting Show Logs..., if applicable.

**Comment by 3koonce** [comment]
<?*xml* version="*1.0*" encoding="*utf-8*"?>
<*manifest*
    xmlns:android=*"http://schemas.android.com/apk/res/android
<http://schemas.android.com/apk/res/android>"*
    android:sharedUserId=*"android.uid.system"*
    android:versionCode=*"400200000"*
    android:versionName=*"4.0.02"*
    compileSdkVersion=*"29"*
    compileSdkVersionCodename=*"10"*
    package=*"com.sec.android.Cdfs"*
    platformBuildVersionCode=*"29"*
    platformBuildVersionName=*"10"*>
    <*uses-sdk*
        android:minSdkVersion=*"29"*
        android:targetSdkVersion=*"29"**/*>
    <*uses-permission*
        android:name=*"android.permission.WRITE_SETTINGS"**/*>
    <*application*
        android:label=*"@2130771968"*
        allowBackup=*"false"*
        android:hardwareAccelerated=*"false"*>
        <*service*
            android:name=*"com.sec.android.Cdfs.CdfsService"**/*>
        <*receiver*
            android:name=*"com.sec.android.Cdfs.CdfsReceiver"*>
            <*intent-filter*>
                <*action*
                    android:name=*"android.hardware.usb.action.USB_STATE"*
*/*>
            <*/**intent-filter*>
        <*/**receiver*>
        <*meta-data*
            android:name=*"SPDE.build.signature"*
            android:value=*"169e431/49449620/release/Cdfs-400000-4.0.02"**/*
>
        <*meta-data*
            android:name=*"SPDE.env.version"*
            android:value=*"3.4.1/L29.1.16/0.8.5"**/*>
    <*/**application*>
<*/**manifest*>
Hey this is just one of manyapps on my phonethatare controllingit

**Comment by 3koonce** [comment]
How doIget this off my phone📱

<?*xml* version="*1.0*" encoding="*utf-8*"?>
<*manifest*
    xmlns:android=*"http://schemas.android.com/apk/res/android
<http://schemas.android.com/apk/res/android>"*
    android:versionCode=*"1"*
    android:versionName=*"1.0"*
    compileSdkVersion=*"29"*
    compileSdkVersionCodename=*"10"*
    package=*"com.samsung.android.mdm"*
    platformBuildVersionCode=*"29"*
    platformBuildVersionName=*"10"*>
    <*uses-sdk*
        android:minSdkVersion=*"29"*
        android:targetSdkVersion=*"28"**/*>
    <*uses-permission*
        android:name=*"android.permission.STATUS_BAR"**/*>
    <*uses-permission*
        android:name=*"com.samsung.android.knox.permission.KNOX_SECURITY"*
*/*>
    <*uses-permission*
        android:name=*"android.permission.MANAGE_USERS"**/*>
    <*uses-permission*
        android:name=*"android.permission.INTERACT_ACROSS_USERS_FULL"**/*>
    <*uses-permission*
        android:name=*"android.permission.SYSTEM_ALERT_WINDOW"**/*>
    <*uses-permission*
        android:name=*"android.permission.GET_TASKS"**/*>
    <*uses-permission*
        android:name=*"android.permission.READ_PHONE_STATE"**/*>
    <*uses-permission*
        android:name=*"android.permission.WRITE_SETTINGS"**/*>
    <*uses-permission*
        android:name=*"android.permission.REAL_GET_TASKS"**/*>
    <*uses-permission*
        android:name=
*"com.samsung.android.knox.permission.KNOX_SET_PROXY_CREDENTIAL_INTERNAL"*
*/*>
    <*uses-permission*
        android:name=*"android.permission.MANAGE_ACTIVITY_STACKS"**/*>
    <*uses-permission*
        android:name=*"android.permission.INTERNAL_SYSTEM_WINDOW"**/*>
    <*application*
        android:label=*"@2131099648"*
        extractNativeLibs=*"false"*
        directBootAware=*"true"*
        usesNonSdkApi=*"true"*>
        <*service*
            android:name=*"com.samsung.android.mdm.DodBanner"*
            android:exported=*"false"**/*>
        <*activity*
            android:theme=*"@16974546"*
            android:name=*".EnterpriseProxyAuthDialog"*
            android:exported=*"false"*
            android:clearTaskOnLaunch=*"true"*
            android:excludeFromRecents=*"true"*
            android:launchMode=*"multiple"*
            android:configChanges=
*"locale|keyboard|keyboardHidden|orientation|screenSize"*
            android:noHistory=*"true"*>
            <*intent-filter*>
                <*action*
                    android:name=*"android.intent.action.MAIN"**/*>
                <*category*
                    android:name=*"android.intent.category.DEFAULT"**/*>
            <*/**intent-filter*>
        <*/**activity*>
        <*receiver*
            android:name=*".EnterpriseProxyDialogReceiver"*
            android:exported=*"false"*>
            <*intent-filter*>
                <*action*
                    android:name=
*"com.samsung.android.knox.intent.action.PROXY_REFRESH_CREDENTIALS_DIALOG_INTERNAL"*
*/*>
            <*/**intent-filter*>
        <*/**receiver*>
        <*meta-data*
            android:name=*"android.max_aspect"*
            android:value=*"2.1"**/*>
    <*/**application*>
<*/**manifest*>

Backedupthebully
