### ISSUE TITLE
GitHub Desktop fails to clone/checkout when filename exceeds 260 chars

### ISSUE THREAD

**Issue by thatchux** [desktop/desktop#10409]
### Describe the bug

Can't clone repo because filename is too long

### Version & OS

ver 2.5.3, Win 10x64 - 10.0.19041.0

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. Attempt to clone a repo with a file path that exceeds 260 chars (ie: https://github.com/chef/mixlib-install)
3. See error

### Expected behavior

Repo is cloned

### Actual behavior

Caught error:
Cloning into 'C:\Repos\mixlib-install'...
remote: Enumerating objects: 68, done.        
remote: Counting objects: 100% (68/68), done.        
remote: Compressing objects: 100% (48/48), done.        
remote: Total 7546 (delta 17), reused 44 (delta 12), pack-reused 7478           
Receiving objects: 100% (7546/7546), 12.84 MiB | 12.64 MiB/s, done.             
Resolving deltas: 100% (3382/3382), done.                                       
error: unable to create file spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/windows_desktop_artifacts/chef-workstation_windows_artifacts/behaves_like_windows_desktop_download_urls_and_expected_architectures/maps_architecture_to_correct_filename.yml: Filename too long
error: unable to create file spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/windows_desktop_artifacts/chef-workstation_windows_artifacts/behaves_like_windows_desktop_download_urls_and_expected_architectures/returns_server_download_url_for_associated_desktop_versions.yml: Filename too long
error: unable to create file spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/windows_desktop_artifacts/chef_windows_artifacts/behaves_like_windows_desktop_download_urls_and_expected_architectures/returns_server_download_url_for_associated_desktop_versions.yml: Filename too long
error: unable to create file spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/windows_desktop_artifacts/chefdk_windows_artifacts/behaves_like_windows_desktop_download_urls_and_expected_architectures/returns_server_download_url_for_associated_desktop_versions.yml: Filename too long
error: unable to create file spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/windows_desktop_artifacts/inspec_windows_artifacts/behaves_like_windows_desktop_download_urls_and_expected_architectures/returns_server_download_url_for_associated_desktop_versions.yml: Filename too long
error: unable to create file spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/windows_desktop_artifacts/push-jobs-client_windows_artifacts/behaves_like_windows_desktop_download_urls_and_expected_architectures/maps_architecture_to_correct_filename.yml: Filename too long
error: unable to create file spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/windows_desktop_artifacts/push-jobs-client_windows_artifacts/behaves_like_windows_desktop_download_urls_and_expected_architectures/returns_server_download_url_for_associated_desktop_versions.yml: Filename too long
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

### Screenshots

N/A

### Logs

Resolving deltas: 100% (3382/3382), done.
error: unable to create file spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/windows_desktop_artifacts/chef-workstation_windows_artifacts/behaves_like_windows_desktop_download_urls_and_expected_architectures/maps_architecture_to_correct_filename.yml: Filename too long
error: unable to create file spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/windows_desktop_artifacts/chef-workstation_windows_artifacts/behaves_like_windows_desktop_download_urls_and_expected_architectures/returns_server_download_url_for_associated_desktop_versions.yml: Filename too long
error: unable to create file spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/windows_desktop_artifacts/chef_windows_artifacts/behaves_like_windows_desktop_download_urls_and_expected_architectures/returns_server_download_url_for_associated_desktop_versions.yml: Filename too long
error: unable to create file spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/windows_desktop_artifacts/chefdk_windows_artifacts/behaves_like_windows_desktop_download_urls_and_expected_architectures/returns_server_download_url_for_associated_desktop_versions.yml: Filename too long
error: unable to create file spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/windows_desktop_artifacts/inspec_windows_artifacts/behaves_like_windows_desktop_download_urls_and_expected_architectures/returns_server_download_url_for_associated_desktop_versions.yml: Filename too long
error: unable to create file spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/windows_desktop_artifacts/push-jobs-client_windows_artifacts/behaves_like_windows_desktop_download_urls_and_expected_architectures/maps_architecture_to_correct_filename.yml: Filename too long
error: unable to create file spec/fixtures/vcr/Mixlib_Install_Backend_PackageRouter_all_channels/windows_desktop_artifacts/push-jobs-client_windows_artifacts/behaves_like_windows_desktop_download_urls_and_expected_architectures/returns_server_download_url_for_associated_desktop_versions.yml: Filename too long
fatal: unable to checkout working tree

### Additional context

N/A
[2020-08-20.desktop.production.log](https://github.com/desktop/desktop/files/5100007/2020-08-20.desktop.production.log)

**Comment by tierninho** [comment]
@thatchux  thanks for the report!

Because of a Windows API limit paths longer than `MAX_PATH` (260 characters) on Windows are not supported by default in Git for Windows, which is used in Desktop. [This document](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file) talks about the limitation and the workaround (using the extended-length path syntax).

Have you set `core.longpaths` to `true` before cloning to opt-in for using the extended-length path support?

```
$ git config --global core.longpaths true
```

There's some caveats to this from the [Git for Windows documentation](https://github.com/git-for-windows/git/blob/d003d728ffa6c0006da875ec6318d3f6b28a4ddb/Documentation/config/core.txt#L560-L565) which is why we don't enable this by default:

```
core.longpaths::
	Enable long path (> 260) support for builtin commands in Git for
	Windows. This is disabled by default, as long paths are not supported
	by Windows Explorer, cmd.exe and the Git for Windows tool chain
	(msys, bash, tcl, perl...). Only enable this if you know what you're
	doing and are prepared to live with a few quirks.
```

**Comment by thatchux** [comment]
Hey there!

I'm aware of the limit, didn't know about the workaround though! Maybe my bug should be updated to "Add filename too long error workaround to error message"?

Tiernan, you're quality for sure.

**Comment by thatchux** [comment]
Also, after the error message was thrown, I immediately looked for an option in the GUI to handle this issue, but couldn't find one. Any chance that this could be added to the backlog of things to add to the Settings menu? :)

**Comment by tierninho** [comment]
Thanks for the update.

> Any chance that this could be added to the backlog of things to add to the Settings menu?

Yes, this is a possibly but we would have to investigate some of the caveats and limitations in the shared documents. I will be open a new issue when the time comes. 

Thanks for using Desktop!
