### ISSUE TITLE
Please give dark mode for github desktop

### ISSUE THREAD

**Issue by Shoban-Chiddarth** [desktop/desktop#10419]
Dark mode would be very soothing to eyes when we use github desktop for a long time

**Comment by niik** [comment]
Hey @Shoban-Chiddarth, we do support a dark theme in the app. Open Preferences (on macOS) or Options (on Windows) and click on "Appearance" in order to select which theme you'd like to use.

Hope you'll enjoy it!

**Comment by Shoban-Chiddarth** [comment]
Thank you Sent from Mail for Windows 10 From: Markus OlssonSent: 24 August 2020 12:47To: desktop/desktopCc: Shoban-Chiddarth; MentionSubject: Re: [desktop/desktop] Please give dark mode for github desktop (#10419) Hey @Shoban-Chiddarth, we do support a dark theme in the app. Open Preferences (on macOS) or Options (on Windows) and click on "Appearance" in order to select which theme you'd like to use.Hope you'll enjoy it!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
