### ISSUE TITLE
Authentication Failure on GitHub Desktop 

### ISSUE THREAD

**Issue by Krkolle** [desktop/desktop#10413]
### Describe the bug

Whenever I'm trying to push to a repository from my account, its throwing an error saying 
"Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
" I have been trying on this for quite some time, but nothing seems to be working.
### Version & OS

Github Desktop Version 2.5.3
Windows 10

### Steps to reproduce the behavior

1. Make some changes in the local files where the repo is cloned.
2. Go to push origin under your repository 
3. See error

### Expected behavior

It was working fine until day before yesterday. I was able to clone a repository and push to the existing repositories.

### Actual behavior

Unable to or push to existing repositories or new ones.

### Screenshots
Error Screen Says below when I'm trying to push.
Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.

### Logs

Not able to open that folder at all. Its throwing some error as well.
![image](https://user-images.githubusercontent.com/21037854/90828924-7d7c0e80-e35c-11ea-875f-4f6f393cb77c.png)
### Additional context

Please let me know how to proceed.

**Comment by tierninho** [comment]
@Krkolle Thanks for the report. Please follow along at https://github.com/desktop/desktop/issues/10408 as we are investigating the problem there.
