### ISSUE TITLE
Getting email to update desktop even when no newer version exists

### ISSUE THREAD

**Issue by specter78** [desktop/desktop#10411]
### Describe the bug

I got the following email:

`You recently used version 2.5.3 of GitHub Desktop to access GitHub. After November 13th, 2020, version 2.5.3 of GitHub Desktop may no longer work with GitHub.com. Existing installations of GitHub Desktop where you are already signed in will continue to work after November 13th. Please update to version 2.5.4 (or later) to ensure you can continue to use GitHub Desktop with GitHub.com.`

### Steps to reproduce the behavior

Login to the app to get the email

**Comment by niik** [comment]
Hi @specter78, thanks for letting us know about this! I'm reaching out to the relevant teams to see if we can pause these emails. For my own understanding could you let me know if you signed in using your username and password, or using the browser?

**Comment by specter78** [comment]
> For my own understanding could you let me know if you signed in using your username and password, or using the browser?

Username and password

**Comment by niik** [comment]
@specter78 Thanks so much. Could you confirm that signing in using the browser doesn't end up sending you an email?

**Comment by specter78** [comment]
Didn't get an email when signing in using browser.

**Comment by specter78** [comment]
In fact, I signed again using username and password and didn't get an email this time.

**Comment by niik** [comment]
Thanks so much for bringing this to our attention @specter78! I've deployed an update to GitHub.com to fix this.

For anyone watching this these emails are regarding the future deprecation of the API we're using for username and password auth. In time we will only support using the browser to sign in.

Unfortunately we had mistakenly specified that the latest available version of GitHub Desktop was 2.5.4 and not 2.5.3.
