### ISSUE TITLE
Unable to push commits

### ISSUE THREAD

**Issue by alexandrafletch** [desktop/desktop#10429]
I am committing files to my branch in GitHub, adding a summary and description as always, but then when I click on the COMMIT to feature-alex button, the "Pull origin" button does not switch to "Push."  What is going on? When I revert my commits, I lose all my changes.

**Comment by dhunmoon** [comment]
If you have changes on __Origin branch__ of the Repo which are not pulled in then it will show Pull origin. You can only push changes once your local branches have all the changes pulled from remote branch.

I am not sure it helps to solve your problem or not.

**Comment by steveward** [comment]
@alexandrafletch what @dhunmoon said is correct -- the `Pull origin` button will remain until you have pulled down any new changes from the remote repository to your local repository. Once you've integrated those changes you will be allowed to push your local changes. I'm going to close this issue out, but let me know if you have any other questions about how this works.

**Comment by alexandrafletch** [comment]
Hi Steve,
I’ve been pulling origin regularly, and yet still, when I make new commits, I am not given the option to push changes. I’m really at a loss here, I’m managing several other developers who are all working from their own branches, so having commits to my branch vanish is a huge problem.
