### ISSUE TITLE
Windows desktop cloning error

### ISSUE THREAD

**Issue by NarenDatla** [desktop/desktop#10425]
### Describe the feature or problem you’d like to solve

while trying to clone  a project on windows desktop getting the following error

```
Cloning into 'C:\git\*\Data-Warehouse-ETL'...
remote: Enumerating objects: 355, done.        
remote: Counting objects: 100% (355/355), done.        
remote: Compressing objects: 100% (200/200), done.        
remote: Total 355 (delta 133), reused 336 (delta 118), pack-reused 0            
Receiving objects: 100% (355/355), 441.73 KiB | 1.68 MiB/s, done.               
Resolving deltas: 100% (133/133), done.                                         
C:\Users\*\AppData\Local\GitHubDesktop\app-2.5.3\resources\app\git\mingw64\libexec\git-core\git-submodule: line 7: basename: command not found
C:\Users\*\AppData\Local\GitHubDesktop\app-2.5.3\resources\app\git\mingw64\libexec\git-core\git-submodule: line 7: sed: command not found
/mingw64/libexec/git-core/git-sh-setup: line 86: basename: command not found
/mingw64/libexec/git-core/git-sh-setup: line 86: sed: command not found
/mingw64/libexec/git-core/git-sh-setup: line 333: uname: command not found
C:\Users\*\AppData\Local\GitHubDesktop\app-2.5.3\resources\app\git\mingw64\libexec\git-core\git-submodule: line 1121: sed: command not found
C:\Users\*\AppData\Local\GitHubDesktop\app-2.5.3\resources\app\git\mingw64\libexec\git-core\git-submodule: line 1121: cmd_: command not found
```

Would you like to retry cloning ?

I uninstalled desktop several times and also disabled ASLR . still getting this error

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by dhunmoon** [comment]
I don't think that this issue related to Git Desktop is your Git installation.

try adding these path environmental variable, and that should solve the problem. 
C:\Program Files\Git\usr\bin
C:\Program Files\Git\mingw64\libexec\git-core 

😃 Hope that solves the issue

**Comment by tierninho** [comment]
@NarenDatla  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
