### ISSUE TITLE
SetDefaultDllDirectories could not be located in the dynamic link library KERNEL32.dll

### ISSUE THREAD

**Issue by sujeetp7387** [desktop/desktop#10424]
### Describe the bug

I am getting error while running the GitHub desktop windows 64 bit installer downloaded from https://desktop.github.com/

The procedure entry point SetDefaultDllDirectories could not be located in the dynamic link library KERNEL32.dll. 

### Version & OS

Windows 7 64 bith

### Steps to reproduce the behavior

Run the installer 

### Expected behavior

install the setup 

### Actual behavior

throw error 

### Screenshots

![GitHubDesktopInstallerError](https://user-images.githubusercontent.com/70093308/90977641-817a7d00-e564-11ea-9119-a117a6ba6d98.png)

**Comment by tierninho** [comment]
@sujeetp7387 Thanks for the issue. Looks like you need the KB2533623 update. It can be found here: https://support.microsoft.com/en-us/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot

**Comment by sujeetp7387** [comment]
thanks tierninho for your reply...

I had already tried this ....the downloaded msi file from above link does't work on my machine

I am getting this error

![image](https://user-images.githubusercontent.com/70093308/91208307-a408c380-e727-11ea-8391-f98fd3e9b181.png)

**Comment by tierninho** [comment]
@sujeetp7387 I would try Safe Mode as it seems you are malware. A reference is here: https://answers.microsoft.com/en-us/windows/forum/windows_7-security/the-service-cannot-be-started-either-because-it-is/58bf868f-6611-47b4-9d8f-f514d4302ff2
