### ISSUE TITLE
github desktop encountered an error

### ISSUE THREAD

**Issue by sailendra01** [desktop/desktop#10420]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by tierninho** [comment]
@sailendra01  Thanks for the report. Just to clarify -- is this error only occurring when you attempt to launch Visual Studio Code from GitHub Desktop (i.e. `Repository` > `Open in Visual Studio Code`)?

Could you open the command prompt and share the output of `echo %PATH%`?

If `System32` is not in your PATH, you will see that ENOENT error. You will need to edit your PATH by following [this article](https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/) and adding the following line:

`C:\Windows\system32`

Let me know if that doesn't get things working!

**Comment by sailendra01** [comment]
![image](https://user-images.githubusercontent.com/67456565/91122627-80f3fa80-e6ba-11ea-8394-f4aede20df77.png)
![image](https://user-images.githubusercontent.com/67456565/91123006-7ab24e00-e6bb-11ea-9d3a-6d790f0b4d22.png)
I did as you said and it works very well.
Thank you
