### ISSUE TITLE
my idenity has been stolen and i am being hacked on my phones and social media this hacker has stolen thousands of dollars off my website on polkadot today

### ISSUE THREAD

**Issue by angelsamongus777** [desktop/desktop#10422]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by niik** [comment]
@angelsamongus777 This repository is for GitHub's Desktop client. For general GitHub question or account related questions please see https://support.github.com
