### ISSUE TITLE
Delete Branch from Branches View

### ISSUE THREAD

**Issue by TheCrafters001** [desktop/desktop#10432]
### Describe the feature or problem you’d like to solve

I would like to be able to delete branches from the branches selection menu, along with PRs.

### Proposed solution

Add a little trash can icon next to the branch you want to delete. When you click it, it will come up with a notice saying what it will do. If the user clicks Confirm, the branch will be deleted. If the user clicks cancel, the branch will not be deleted. The `Master` Branch cannot be deleted from it.

### Additional context

Mock ups

![GitHubDesktop_ObeyntEbIh](https://user-images.githubusercontent.com/46639269/91050941-656eee00-e5ed-11ea-833a-9cd04a7cf994.png)
![GitHubDesktop_ccFZESo31v](https://user-images.githubusercontent.com/46639269/91050937-63a52a80-e5ed-11ea-94ef-4ec449f95bf4.png)

**Comment by tierninho** [comment]
@TheCrafters001 Thanks for the suggestion. I can imagine that we do not want to make deleting a branch too exposed as it may get clicked accidentally too often, despite the warning message. There is similar logic behind omitting a `ctl/cmd-D` keyboard shortcut. 

As both your suggestion and the current way take two clicks, I am hesitant to move forward. Going to label this appropriately and see if we get any relevant feedback from other users before taking any further action.

**Comment by dhunmoon** [comment]
@tierninho I totally agree with you there. Even if I like the feature which is something good to have, the deleting branch is not a frequent action. The way this feature is done in the application is better.

**Comment by TheCrafters001** [comment]
@tierninho @dhunmoon I do think that miss-clicks can lead to accidental deletion of branches, so, what if we make the user have to confirm (up to) 3 times, or have a check box that says "I understand that deleting this branch will **_permanently_** remove all data in it." I just find it inconvenient (for me) to go to the website every time to delete a branch.

**Comment by dhunmoon** [comment]
@TheCrafters001 there is already the option to delete a branch in the application which is just one click away and on top of that there is a shortcut to delete branch also. The main reason what there is no delete button there because the deleting branch is not such a frequent action.

**Comment by tyler-reed-tsico** [comment]
I actually delete branches quite frequently, so having a feature to do this in bulk is handy.

I typically find myself going to the GitHub UI to do this in bulk, as the desktop app is not equipped to handle this request. I'd love it if it could those. Several competing git management tools (such as Fork and SourceTree) allow this feature.

**Comment by javatlacati** [comment]
I'd like to have it for local branches, it's very common for me to delete them very often
