### ISSUE TITLE
Descript section takes longer to reset on commit.

### ISSUE THREAD

**Issue by dhunmoon** [desktop/desktop#10430]
### Describe the bug

When you have multiple commit to make, based on how many changes you have done, you select a file give it some description and press commit. Commit operation is fast so after that you quickly select next file to do another commit and, you will notice even if commit is done Description field still have the text from last commit which is still waiting to get cleared up, If you clear it by yourself and start typing the new description the Git Application command to clear up the description will fire and now it will clean your current description.

This happens every time for me and it's not something which happens occasionally.

### Version & OS

OS Name : Microsoft Windows 10 Enterprise
GitHub Desktop : Version 2.5.3

### Steps to reproduce the behavior

1. Commit a change where you have something in description.

### Expected behavior

Once you Commit a change description field should clear up as soon are commit action is done. And the code to clear up the Description field should not clear up newly written description.

### Actual behavior

Description field takes longer to clear than actual commit action. Since it takes longer it also clears up it cleans new description message which you are in process of typing.

**Comment by phattkitt** [comment]
Fuck all of this skank shit

**Comment by tierninho** [comment]
@dhunmoon Thanks for the suggestion.

Just to clarify, if you multiple changed files and you intend to make multiple commits, you are noticing a lag that clears anything you type? I tried to recreate this but I couldn't, however I did notice a slight lag.

Looks like we have a bug open for this here: https://github.com/desktop/desktop/issues/7251

> Sounds like this is a little race condition we need to fix.

Please follow along there. Thanks again.

**Comment by dhunmoon** [comment]
Thanks, If you want you can close this thread here. I really appreciate the help.
