### ISSUE TITLE
Commit button disabled

### ISSUE THREAD

**Issue by Kanisha14** [desktop/desktop#10431]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@Kanisha14 thanks for contributing. The commit button remains disabled until you enter a commit message -- can you confirm that you have uncommitted changes and have entered a commit message in the `Summary (required)` text box?

**Comment by dhunmoon** [comment]
@Kanisha14 for commit where you have a single file your `Summary(required)` is field is auto-populated by application by default which generally looks like `Updated <file name>`, and `Commit to <branch name>` button is enabled. But if you have multiple files in a single commit you have to type the `Summary(required)` by yourself, and the `Commit to <branch name>` button will only get enabled if you give your commit a summary.

**Comment by steveward** [comment]
I'm going to close this issue out, but let me know if you are still having issues committing @Kanisha14.

**Comment by Kanisha14** [comment]
It works now.

Thank you,
Kanisha
