### ISSUE TITLE
Request for GitHub Desktop Font setting..

### ISSUE THREAD

**Issue by ijbranch** [desktop/desktop#10436]
I am getting on and have to use glasses.
It would be nice if GitHub Desktop had the ability to increase the Font size.
It would go under Option|Appearance.
Here's hoping....
Regards & TIA,
Ian

**Comment by niik** [comment]
Hi @ijbranch, thanks for opening this!

While we don't have a font setting specifically GitHub Desktop does support zooming the app which will in turn increase the font size. See the View menu or try <kbd>Ctrl</kbd> <kbd>+</kbd> and <kbd>Ctrl</kbd> <kbd>-</kbd>.

Hope that helps!

**Comment by ijbranch** [comment]
Hi Markus,
              Yep.  That works for me.  Tks.
Regards,
Ian

**Comment by TonyPolich** [comment]
Zooming is great, but I want to decrease the zoom level bellow 100% to be able to fit more on the screen.

**Comment by saipat** [comment]
ctrl + or ctrl - does not work for me. I want to zoom beyond 100% and I could not do that. Could you pls help me with this issue?

**Comment by lflewwelling** [comment]
@saipat On windows, it works with ctrl + =, and ctrl + - using the normal keys, not the numpad. Also available from the view menu. 
![image](https://github.com/desktop/desktop/assets/89599028/a4d90783-838d-4a92-b7f5-aeda9c157df3)

**Comment by costas-andriotis** [comment]
If you are mildly familiar with CSS, open Developer Tools -> Sources and check the location of the file **_renderer.css_**. You can try editing this file to suit your needs. For example, I'm using a UHD monitor and I also find some fonts very small, so I added the following at the very end of the file:

`:root { --font-family-sans-serif: 'Noto Sans Condensed'; --font-family-monospace: 'Noto Sans Mono ExtraCondensed'; --font-size: 14px; --font-size-sm: 12px; font-weight: 500;}`

You could try other customizations at your risk, if you like, keeping in mind they probably won't survive updates.
Obviously, I'd prefer to have a UI to customize such settings...

**Comment by Chewypewy** [comment]
Got it.


Sent from Yahoo Mail for iPhone


On Thursday, June 19, 2025, 9:08 AM, Costas Andriotis ***@***.***> wrote:

costas-andriotis left a comment (desktop/desktop#10436)
If you are mildly familiar with CSS, open Developer Tools -> Sources and check the location of the file renderer.css. You can try editing this file to suit your needs. For example, I'm using a UHD monitor and I also find some fonts very small, so I added the following at the very end of the file:

:root { --font-family-sans-serif: 'Noto Sans Condensed'; --font-family-monospace: 'Noto Sans Mono ExtraCondensed'; --font-size: 14px; --font-size-sm: 12px; font-weight: 500;}

You could try other customizations at your risk, if you like, keeping in mind they probably won't survive updates.

**Comment by zen0wu** [comment]
It's wild to me that there's no options to configure the font family?!
