### ISSUE TITLE
search commit

### ISSUE THREAD

**Issue by laithdj** [desktop/desktop#10437]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
Thanks for contributing @laithdj. The ability to search the history view is being tracked in https://github.com/desktop/desktop/issues/7022. I'm going to close this issue out -- please follow along there for updates.
