### ISSUE TITLE
Windows Store version of Desktop does not work -- fix here

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#10447]
If you downloaded a version of Desktop from the **Windows Store**, please perform the following steps below, as that version of Desktop was not uploaded by GitHub and has since been removed.

For a fresh installation of GitHub Desktop:

- Close `GitHub Desktop`
- Delete the `%AppData%\GitHub Desktop\` directory
- Delete the `%LocalAppData%\GitHubDesktop\` directory
- Reinstall `GitHub Desktop` from [desktop.github.com](https://desktop.github.com)

**Comment by SuperHarmony910** [comment]
Is there a Windows Store version of GitHub?

**Comment by tierninho** [comment]
Unofficial.

**Comment by SuperHarmony910** [comment]
Okay, are GitHub staff planning to do a release on Windows Store, however ineffective it will be for a website exists with a likewise purpose, and if not, are they trying to remove this ingenuine installation from the Store?

**Comment by tierninho** [comment]
No plans to release to the Windows Store. I believe the said copy has since been removed.

**Comment by SuperHarmony910** [comment]
Great, no more queries need to be answered, thanks!

**Comment by tierninho** [comment]
Thanks for using Desktop!

**Comment by tierninho** [comment]
Closing this as the copy has been removed from the Windows Store
