### ISSUE TITLE
Publish Branch get "Access is denied"

### ISSUE THREAD

**Issue by Msadr471** [desktop/desktop#10442]
### Publish Branch get "Access is denied"
Hi,

when I create a new repository and finally click on the "Publish Branch" give me this error:
![image](https://user-images.githubusercontent.com/49529241/91201837-31dbb300-e716-11ea-90e6-3ce6ba4b257c.png)

and I added SSH keys:
![image](https://user-images.githubusercontent.com/49529241/91201911-4ddf5480-e716-11ea-9041-b053cb8efae8.png)

so what's the problem?

The program has no problems!
I can create a repository with the command line! commit, change! I push. pull to.

There is no problem in the desktop version except for these two things:
Create a new repository (of course the repository is created but not released!)
And there is no file in the log folder!
![image](https://user-images.githubusercontent.com/49529241/91202765-85023580-e717-11ea-85a6-854b2fc55de3.png)

This is also from the SSH key verification output:

No problem!
![image](https://user-images.githubusercontent.com/49529241/91203149-078af500-e718-11ea-99e9-df541131181e.png)

### Version & OS

GitHub Desktop Version:
![image](https://user-images.githubusercontent.com/49529241/91208545-994a3080-e71f-11ea-97e6-218c87154083.png)

Windows version:
![image](https://user-images.githubusercontent.com/49529241/91208665-c565b180-e71f-11ea-9623-3795c0c1244d.png)

### Logs

and one more thing, why LOG folder is empty???
![image](https://user-images.githubusercontent.com/49529241/91202078-897a1e80-e716-11ea-9e6e-3aaf4bc11e1a.png)

**Comment by steveward** [comment]
@Msadr471 did you possibly install GitHub Desktop from the Windows Store? 

Can also you confirm whether or not you are using SSH with this repository? You can check by going to `Repository` > `Repository Settings` > `Remote`. GitHub Desktop uses HTTPS by default so it's unlikely to be an SSH issue unless you specifically set up this repository to use SSH.

**Comment by Msadr471** [comment]
Yah I downloaded a few days ago in Windows Store!

yah tath's by default on HTTPS:

![image](https://user-images.githubusercontent.com/49529241/91215131-555c2900-e729-11ea-9f74-4627259b6305.png)

I guess maybe because of SSH!

so what should I do?

and why there is no LOG file?

thank you, @steveward,

**Comment by steveward** [comment]
@Msadr471 try downloading the version from here:

http://desktop.github.com

The Windows Store version of GitHub Desktop was not uploaded by GitHub and has been removed -- it did not work properly. Sorry about that. Let me know if you run into any issues with the correct version.

**Comment by Msadr471** [comment]
## it's working
Thanks a lot ... @steveward,

Yes, there was no version when I tried to download GitHub again from the Windows Store last night.

After removing the program completely, I downloaded the updated version again from the main site and now it has no problems and works easily with HTTPS protocol.

But the only downside is that when I enter the SSH address of the new repository, I get an error message!

Do you know the reason ?!
![image](https://user-images.githubusercontent.com/49529241/91258577-ec54cf80-e781-11ea-91fe-15e97d118098.png)
![image](https://user-images.githubusercontent.com/49529241/91258580-ed85fc80-e781-11ea-94e2-f7cd25efe2ca.png)

## LOG Folder
2020-08-26T05:21:38.748Z - info: [ui] [AppStore] loading 27 repositories from store
2020-08-26T05:21:38.749Z - info: [ui] [AppStore] found account: Msadr471 (Mohammad Sadr)
2020-08-26T05:21:39.186Z - info: [ui] [BranchPruner] Last prune took place in 16 hours - skipping
2020-08-26T05:21:39.584Z - info: [ui] launching: 2.5.4 (Windows 10.0.19041)
2020-08-26T05:21:39.584Z - info: [ui] execPath: 'C:\Users\Mohammad\AppData\Local\GitHubDesktop\app-2.5.4\GitHubDesktop.exe'
2020-08-26T05:21:48.788Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.369s)
2020-08-26T05:22:14.394Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: mimi - Msadr471 (has token)
2020-08-26T05:22:14.395Z - info: [ui] proxy url not resolved, protocol not supported
2020-08-26T05:22:16.892Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.417s)
2020-08-26T05:22:16.896Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
Warning: Permanently added the RSA host key for IP address '140.82.121.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)

**Comment by steveward** [comment]
@Msadr471 I'd recommend using HTTPS -- GitHub Desktop does not officially support SSH. You can use SSH, but there are a number of configuration issues that need to be worked around. See [this issue](https://github.com/desktop/desktop/issues/2579) for more information. I'm going to close this issue out as we've resolved the underlying error.
