### ISSUE TITLE
cannot log in getting error

### ISSUE THREAD

**Issue by davids-tips** [desktop/desktop#10440]
### Describe the bug
I cannot log into the GitHub desktop application. I am getting the following error.

The server responded with an error while attempting to authenticate (200)

### Version & OS
Version 2.5.4 windows 10
Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. attempt to log in
2. get errot
Version 2.5.4

### Expected behavior

for the program to log me in

### Actual behavior

getting error

I am also not able to log in using the sign in using your browser button
### Screenshots
![Screenshot (2)](https://user-images.githubusercontent.com/70023798/91187459-2fe60580-e6be-11ea-98fe-17686422d305.png)
![Screenshot (3)](https://user-images.githubusercontent.com/70023798/91187460-307e9c00-e6be-11ea-87cc-0112ff3d3355.png)

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by davids-tips** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/70023798/91186534-29a35980-e6bd-11ea-9b61-15ae4183bbfe.png)

**Comment by davids-tips** [comment]
@steveward could you help with this issue

**Comment by tierninho** [comment]
@davids-tips Looks like a network request is not deserializing properly.  

I would log in to Github.com and go to your Settings (https://github.com/settings/applications) to remove GitHub Desktop from Authorized OAuth Apps, which would revoke the token. The log in to Desktop again.

Let us know how it goes!

**Comment by davids-tips** [comment]
sadly it didnt work. it says that there was a json error at line 0

**Comment by steveward** [comment]
@davids-tips  would you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by davids-tips** [comment]
[2020-08-25.desktop.production.log](https://github.com/desktop/desktop/files/5125570/2020-08-25.desktop.production.log)
[2020-08-25.desktop.beta.log](https://github.com/desktop/desktop/files/5125571/2020-08-25.desktop.beta.log)

**Comment by davids-tips** [comment]
probially is the beta log

**Comment by davids-tips** [comment]
`Do you see what is the issue in the log?`

**Comment by steveward** [comment]
@davids-tips thanks for sharing the log. The log isn't showing anything interesting outside of the error that is already being shown. Would you mind performing a fresh installation of GitHub Desktop to see if that helps?

Here's how to do that:

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `%AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

**Comment by davids-tips** [comment]
i am still getting the issue. should i turn off 2fa and try again

**Comment by davids-tips** [comment]
I tried 


turning 2fa off and it did not work.

**Comment by davids-tips** [comment]
[2020-08-25.desktop.production.log](https://github.com/desktop/desktop/files/5125809/2020-08-25.desktop.production.log)

**Comment by tierninho** [comment]
Maybe something is intercepting the request and serving up different, non-JSON content?

You may see any errors here (if they are present):

- launch the app, then click View | Toggle Developer Tools
- switch to the Network tab
- trigger the issue (by switching repository or whatever)
- select a problem request and inspect the Headers and Response

If you find something interesting, could you attach that here?

**Comment by steveward** [comment]
@davids-tips it'd also be helpful to know if you have any antivirus/security software in place that could be interfering with network requests. Did you have any issues logging in prior to GitHub Desktop updating to v2.5.4?

**Comment by davids-tips** [comment]
I don't know what the antivirus does I just know it is Norton I don't have access to the antivirus.

**Comment by davids-tips** [comment]
@tierninho fun the proxy is blocking it.
 <html><body onload='document.forms[0].submit()'>
<form action='https://ckr01.lsc.k12.in.us/cgi-bin/blockpage/blockpagenl.cgi' method='GET'>
<input type='Hidden' name='URL' value='api.github.com'>
<input type='Hidden' name='CAT' value='EducationalGames (Global)'>
<input type='Hidden' name='CATNO' value='1016'>
<input type='Hidden' name='ACC' value='dpowell/lscwan'>
<input type='Hidden' name='WHY' value='Policy=jhs_restricted; NT Group=jhs restricted internet'>
<input type='Hidden' name='MOD' value='2'>
<input type='Hidden' name='IPA' value='10.250.250.173'>
<input type='Hidden' name='RAW' value='https://api.github.com:443?ck_sni=108024460.443'>
<input type='Hidden' name='AUTH0' value='{CK_USERID},EducationalGames (Global)'>
<input type='Hidden' name='PGE' value='http://ckr01.lsc.k12.in.us/cgi-bin/blockpage/blockpagenl.cgi'>
<input type='Hidden' name='STR' value='null,null,null,null,null'>
<input type='Hidden' name='SRV' value='null'>
<input type='Hidden' name='AUTH1' value='{CK_USERID},https://api.github.com:443?ck_sni=108024460.443,EducationalGames (Global)'>
</form></body></html>

**Comment by davids-tips** [comment]
[new 2.txt](https://github.com/desktop/desktop/files/5136191/new.2.txt)

**Comment by davids-tips** [comment]
the message im getting in the network tab ^^^

**Comment by davids-tips** [comment]
proxy was blocking access... will take note... solved but I could never get connected.
