### ISSUE TITLE
I have no idea where or how to fix it

### ISSUE THREAD

**Issue by amalyaoldano** [desktop/desktop#10455]
### Describe the bug

Apple Swisscom and Police couldn't 

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@amalyaoldano this issue tracker is for GitHub Desktop, If you are having issues with GitHub Desktop please let us know.
