### ISSUE TITLE
Github giving fatal error 500 when performing any operation

### ISSUE THREAD

**Issue by SpoorthiVasanth** [desktop/desktop#10450]
### Describe the bug

Github giving fatal error 500 when performing any operation

### Version & OS

Github version 2.5.4 in windows 10

### Steps to reproduce the behavior

1. Click on pull or push in the github app

### Expected behavior

Should be able to pull the changes are push my changes to the repository
### Actual behavior

fatal: unable to access 'https://******': The requested URL returned error: 500

### Screenshots

Add screenshots to help explain your problem, if applicable.

**Comment by steveward** [comment]
@SpoorthiVasanth thanks for the report. Are you attempting to access repositories hosted on GitHub from GitHub Desktop, or is this a GitHub Enterprise instance? A 500 error indicates an external server issue -- not a specific issue with GitHub Desktop.

**Comment by SpoorthiVasanth** [comment]
Hi,


I am trying to access repositories hosted on GitHub from GitHub Desktop.

Still facing the same issue.


Regards,

Spoorthi


________________________________

**Comment by steveward** [comment]
@SpoorthiVasanth thanks for the update. GitHub is not having any availability issues so I'm not sure what would be causing this -- are you able to access these repositories from your browser? Have you ever been able to successfully work with repositories using GitHub Desktop?

It would also be helpful if you could upload the full log file from GitHub Desktop. You can find this by selecting `Help` > `Show Logs...`.

**Comment by SpoorthiVasanth** [comment]
Hi,

I am trying to access repositories hosted on GitHub from GitHub Desktop.
Still facing the same issue.

Regards,
Spoorthi

**Comment by SpoorthiVasanth** [comment]
Please find the logs attached.

Regards,
Spoorthi

From: Spoorthi Vasantharaju
Sent: Wednesday, August 26, 2020 8:46 PM
To: desktop/desktop <reply@reply.github.com>; desktop/desktop <desktop@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [desktop/desktop] Github giving fatal error 500 when performing any operation (#10450)

Hi,

I am trying to access repositories hosted on GitHub from GitHub Desktop.
Still facing the same issue.

Regards,
Spoorthi

**Comment by tierninho** [comment]
@SpoorthiVasanth Please login to Github.com on your browser to add the logs as they cannot be emailed. Thank you.

**Comment by tierninho** [comment]
As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by Nader-CS** [comment]
the same issue happed to me today

**Comment by marigbede** [comment]
Same here.

**Comment by Essem8006** [comment]
I've also had it just now

**Comment by marigbede** [comment]
<img width="1258" height="388" alt="Image" src="https://github.com/user-attachments/assets/f72c4777-013b-4cc6-b4e6-53543b046b33" />

This must be why

**Comment by ScriptedChicken** [comment]
Same here!

**Comment by richcross08** [comment]
I am getting this as well right now

**Comment by Marcielen-Flash** [comment]
I'm having the same problem.

**Comment by CorSoftware** [comment]
Same problem.

**Comment by Catshark07** [comment]
Same here

**Comment by 0Klart** [comment]
I am to getting the exact problem

**Comment by ObelardO** [comment]
Same here

**Comment by rachidinsa** [comment]
Same here

**Comment by pareshc123** [comment]
same here, facing the same issue
I didnt find any issue when creating a pull request. however, when i am trying to pull to update the local repo. i am seeing this error
**remote: Internal Server Error
fatal: unable to access 'https://github.com/***/***.git/': The requested URL returned error: 500**

**Comment by TJGinis** [comment]
same here

**Comment by npucheta** [comment]
issue ongoing
remote: Internal Server Error
fatal: unable to access 'XYZ': The requested URL returned error: 500

**Comment by fenndragon** [comment]
oh- this is an actual issue? uh- very... strange

**Comment by thatnavguy** [comment]
same here

**Comment by shelbycarlin** [comment]
also having this issue

**Comment by angelmonzant** [comment]
remote: Internal Server Error
fatal: unable to access 'https://github.com/...... The requested URL returned error: 500

**Comment by IWasaenz** [comment]
same here

**Comment by killerswin2** [comment]
Having the same issue. Just doubled checked on a different machine too,

**Comment by camden-bassett** [comment]
I am also having this issue.

**Comment by killerswin2** [comment]
And just tested with regular cli git, both windows and mac.

**Comment by iisraelROC** [comment]
Is anyone from GH able to provide an update?

**Comment by RRitsolution** [comment]
I am to getting the exact problem

**Comment by pappl** [comment]
Same issue, I can view my repositories on a browser, but I get "unable to access 'https://github.com/...': The requested URL returned error: 500" on Visual Studio.

**Comment by AhadKaro** [comment]
Same here

**Comment by killerswin2** [comment]
Honestly this is not the right ticket per se, it seems like a github server issue. https://github.com/orgs/community/discussions/179907

**Comment by Vhutshilo-Khomola** [comment]
any updates on this ?

**Comment by IWasaenz** [comment]
i tried syncing changes through vs code and through cli, error happens on both for me

**Comment by RRitsolution** [comment]
Same here since last 30 minutes .. any update

**Comment by mlucasmichel** [comment]
Same here

**Comment by npucheta** [comment]
I opened a new issue for this, not sure this is getting visibility as is already closed. new issue:
https://github.com/desktop/desktop/issues/21278

**Comment by cesarlugojr** [comment]
same here

**Comment by Orachigami** [comment]
Same in GH actions

**Comment by namanica** [comment]
same through the vs code

**Comment by herman-hellenes** [comment]
Same here

**Comment by jimarcor** [comment]
Same! Could this somehow be related to the Cloudflare outage?

**Comment by RRitsolution** [comment]
remote: Internal Server Error
fatal: unable to access 'https://github.com/....../': The requested URL returned error: 500

**Comment by marigbede** [comment]
Seems its the https endpoints. Has anyone tried SSH?

**Comment by fschadow** [comment]
Maybe it has something to do with the Cloudflare issues today.

**Comment by APKiwi** [comment]
Git CLI giving 500 or 503 for me too, permissions are correct for private repos - have not changed or had issues prior to today.

**Comment by sdminonne** [comment]
Same

**Comment by RRitsolution** [comment]
Looks like it is global issue

**Comment by bis-code** [comment]
Same here

**Comment by cinmoro** [comment]
I am getting error 500 as well.

**Comment by bis-code** [comment]
git push
remote: Internal Server Error
fatal: unable to access 'https://github.com/...: The requested URL returned error: 500

**Comment by trkwon** [comment]
+1

**Comment by bis-code** [comment]
https://www.githubstatus.com/ github down

**Comment by sdminonne** [comment]
https://www.githubstatus.com/incidents/5q7nmlxz30sk

**Comment by rna-code-crypto** [comment]
Hello! The same problem. Error 500.

**Comment by pipinthedev** [comment]
commit works only push and pull / clone doesn't work for me

**Comment by Vhutshilo-Khomola** [comment]
latest update from github status page 

**Update - We have shipped a fix and are seeing recovery in some areas and will continue to provide updates.
Nov 18, 2025 - 21:36 UTC**

**Comment by perad4r** [comment]
oh... I was vibing on Codex cloud and suddenly it stucks at "refreshing repo" 
```
git clone https://github.com/perad4r/source.git
Cloning into 'source'...
remote: Internal Server Error
fatal: unable to access 'https://github.com/perad4r/source.git/': The requested URL returned error: 500
```
And now i can't even clone my own repo using git clone. But downloading zip works.

**Comment by Askas-db** [comment]
> oh... I was vibing on Codex cloud and suddenly it stucks at "refreshing repo"
> 
> ```
> git clone https://github.com/perad4r/source.git
> Cloning into 'source'...
> remote: Internal Server Error
> fatal: unable to access 'https://github.com/perad4r/source.git/': The requested URL returned error: 500
> ```
> 
> And now i can't even clone my own repo using git clone. But downloading zip works.

Yap, it was global.

Oh, it worked for me, now.

**Comment by cheduude** [comment]
Error 500 solved

**Comment by hkjarral** [comment]
Still happening for me

% git push origin develop
remote: Internal Server Error
fatal: unable to access 'https://github.com/hkjarral/Asterisk-AI-Voice-Agent.git/': The requested URL returned error: 500

**Comment by maia-emille** [comment]
> Still happening for me
> 
> % git push origin develop remote: Internal Server Error fatal: unable to access 'https://github.com/hkjarral/Asterisk-AI-Voice-Agent.git/': The requested URL returned error: 500

same

**Comment by richcross08** [comment]
appears to be back now

**Comment by IWasaenz** [comment]
i was able to push my changes

**Comment by maia-emille** [comment]
> i was able to push my changes

Yes, now I can as well

**Comment by RRitsolution** [comment]
I am also able to push also ..

**Comment by hkjarral** [comment]
working now. confirmed.
