### ISSUE TITLE
Files seen as empty and unable to perform commit from desktop client

### ISSUE THREAD

**Issue by dillardj** [desktop/desktop#10456]
### Describe the bug

New or changed files show are seen as empty in the application.

### Version & OS

Version 2.5.4
OS: windows 10 enterprise

### Steps to reproduce the behavior

1. Create or Modify a file
2. Save changes
3. Open GH Desktop and view the branch
4. Add commit message and click Submit
5. Errors out with "Commit failed exit code 1 recieved"

### Expected behavior

I expect the view pane to show me the new object or the modifications to an existing object per normal behavior.

### Actual behavior

selecting a modified or new file shows a message that the file is empty

### Screenshots
![image](https://user-images.githubusercontent.com/30057207/91382315-5733f400-e7de-11ea-98eb-208f73e432a8.png)

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@dillardj Thank you for the issue. Please upload your logs so we can take a closer look. See the Help menu in Desktop.

**Comment by dillardj** [comment]
Not sure how far back you need the logs so I'll start with the past few and see how this goes. On second thought heres all the log files in the logs folder.

[2020-08-27.desktop.production.log](https://github.com/desktop/desktop/files/5139388/2020-08-27.desktop.production.log)
[2020-08-28.desktop.production.log](https://github.com/desktop/desktop/files/5139389/2020-08-28.desktop.production.log)
[2020-07-14.desktop.production.log](https://github.com/desktop/desktop/files/5139390/2020-07-14.desktop.production.log)
[2020-07-20.desktop.production.log](https://github.com/desktop/desktop/files/5139391/2020-07-20.desktop.production.log)
[2020-07-21.desktop.production.log](https://github.com/desktop/desktop/files/5139392/2020-07-21.desktop.production.log)
[2020-07-22.desktop.production.log](https://github.com/desktop/desktop/files/5139393/2020-07-22.desktop.production.log)
[2020-07-23.desktop.production.log](https://github.com/desktop/desktop/files/5139394/2020-07-23.desktop.production.log)
[2020-07-24.desktop.production.log](https://github.com/desktop/desktop/files/5139395/2020-07-24.desktop.production.log)
[2020-07-25.desktop.production.log](https://github.com/desktop/desktop/files/5139396/2020-07-25.desktop.production.log)
[2020-07-26.desktop.production.log](https://github.com/desktop/desktop/files/5139397/2020-07-26.desktop.production.log)
[2020-08-04.desktop.production.log](https://github.com/desktop/desktop/files/5139398/2020-08-04.desktop.production.log)
[2020-08-05.desktop.production.log](https://github.com/desktop/desktop/files/5139399/2020-08-05.desktop.production.log)
[2020-08-06.desktop.production.log](https://github.com/desktop/desktop/files/5139400/2020-08-06.desktop.production.log)
[2020-08-14.desktop.production.log](https://github.com/desktop/desktop/files/5139401/2020-08-14.desktop.production.log)

**Comment by tierninho** [comment]
@dillardj Thank you for the logs. On the 27th log, I see two errors:

```
2020-08-27T09:00:01.209Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://bitbucket.dcinema.com/scm/krak/kraken-distribution.git/': Failed to connect to bitbucket.dcinema.com port 443: Timed out
```
and
```
2020-08-27T15:53:28.810Z - error: [ui] `git commit -F -` exited with an unexpected code: 1.
stdout:
On branch krmast-3031-fix-satellite-update-process
Your branch is up to date with 'origin/krmast-3031-fix-satellite-update-process'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Stored Procedures/dbo.usp_AddSatelliteDistributionMethod.sql

no changes added to commit (use "git add" and/or "git commit -a")
```

- It looks like you are on a non-Github repo, did you login to Desktop ok? Can you verify you can fetch and pull?
- It also looks like your commits were not staged first. If open the command line and run `git add <file>` that should do it. 

Let us know if you have any more trouble!

**Comment by dillardj** [comment]
The bitbucket one is fine and was a one off connection.

The other one that is exiting with an error code of 1 std out, is a github repo.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dillardj** [comment]
So for the non-github repo (bitbucket) that was fine since it was a bitbucket item I did not end up using GH desktop for much there. 

On the error that exited with an unexpected code: 1 - this is an issue with the client. I have changed nothing about my upstream process; so changes are made and saved properly to the correct folder/file. The client can see that a change was made (file modified or added or removed) it is unable to show the changes in the file (msg: File is empty, shown behind the alert box in the image i loaded).

The error in the log - appears to me - to be the same error I showed in the screenshot; which happens when I attempt to commit. Which I imagine is related to the issue of the client not being able to see the file - even though it can see that there is a change to the file.

The client is also unable to show me any changes that were made to any file in the history view as well.

I've resorted to using tortoise git for now to handle my commits - for which I'm not doing anything different either. Code change made, file saved to local repo, then I simply commit.

I like the GH client but this change in functionality makes it unusable.

**Comment by tierninho** [comment]
Thanks for the update and apologies for the frustrations.

Check first if you have added files to your index. Open the command line and check your `git status`. 

In summary, I think this is happening because Desktop relies on the parsed output of git status to present change details in the changes list. Desktop then tries to produce a diff of the changes, but the diff is empty. When you attempt to commit, Desktop presents a Commit failed error. Explanation [here](https://github.com/desktop/desktop/issues/7738).

Also, some users have run into this error due to having nested `.git` directories. If this applies, can you try searching your repository to see if you have multiple `.git` directories?

Finally, check if you have any submodule (a `.gitmodules` file at the root of your repo).

**Comment by dillardj** [comment]
I have not nested .git directories - at least to my understanding, here is a screen shot of how these are setup. The files I last touched when opening this ticket are DB objects. Nothing tricky there just the .sql files.

![image](https://user-images.githubusercontent.com/30057207/91608980-63799780-e92b-11ea-94c1-6c1cc2960ad6.png)

**Comment by dillardj** [comment]
I just made a change to add a new file and still have the same issue even though the change is staged per git status output

![image](https://user-images.githubusercontent.com/30057207/91609870-0c74c200-e92d-11ea-8ba9-ce2ba9dce5ad.png)

**Comment by dillardj** [comment]
Can I get help with this? The walk through didn't work (https://github.com/desktop/desktop/issues/7738) and im seeing errors in my log that I'm not familiar with.
[2020-09-16.desktop.production.log](https://github.com/desktop/desktop/files/5235409/2020-09-16.desktop.production.log)

**Comment by dillardj** [comment]
I'd like to mention that I have repos where the tool works as expected but I'm not sure what to check to see what the differences are.

**Comment by tierninho** [comment]
Looks you are running into is an issue that is specific to Windows machines. There are certain reserved names that cannot be used in filenames. I suspect `sql` is a reserved word. See [this Microsoft help article](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#naming-conventions) for the full list of reserved characters and words.

Are you able to try renaming that file? You could try directly [renaming it on GitHub](https://docs.github.com/en/enterprise/2.14/user/articles/renaming-a-file).

**Comment by dillardj** [comment]
Not sure that would have any impact - my other repos are working just fine and they are all MS SQL Server code repositories. However, the notion that some work and one does not led to me to delete and clone the repo again which seems to have resolved my issue. It doesnt tell me why this was failing and now why its working; however I did also notice that the errors about playing the commits from left to right (see previous logs) has gone away and I have no issues seeing the changes in the client nor any issues in seeing the changes in history (which I could not before).

**Comment by Chifirst10** [comment]
New SQL file seen as empty on GitHub after pushing it
