### ISSUE TITLE
option "show in file manager" is not displaying by GitHub

### ISSUE THREAD

**Issue by 1MuhammadFarhanAslam** [desktop/desktop#10451]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@1MuhammadFarhanAslam thanks for contributing. Would you mind filling out the rest of the template? It's not clear what specifically you are referring to in this report.

You can open your repository in Explorer/Finder by going to `Repository` > `Open in <file_manager` or by using the available keyboard shortcut listed there. You can also launch into the directory a file lives in by right-clicking on an uncommitted file and selecting `Reveal in...`. I hope that helps!
