### ISSUE TITLE
Discarding Changes to a File also Discards Unrelated Reverts Submodule Commits

### ISSUE THREAD

**Issue by TCWORLD** [desktop/desktop#10469]
### Describe the bug

When using submodules, if changes to a file completely unrelated to the submodule (e.g. Readme.md) are discarded, the submodule is randomly checked out to the last committed SHA (detached head state), even though the submodule should not have been touched.

### Version & OS

- Windows 10 (2004)
- Github Desktop Version 2.5.4

### Steps to reproduce the behavior

1. Open repository (Foo) which includes a submodule (Bar). Bar is currently at, say `c01dbed5`.
2. Make commits to the submodule (Bar), its head is now at, say `deadbeef`.
    Foo repository now shows Bar as changed - showing -`c01dbed5` +`deadbeef` - this is expected behaviour.
3. Edit some other file in Foo - lets say README.md.
    Foo now shows README.md as also being changed - again expected behaviour
4. Discard changes to **only** README.md in Foo.
5. Bar is now back at `c01dbed5` - even though it was **not** discarded! Changes in the submodule go irrevocably missing.

### Expected behavior

After discarding the unrelated file (README.md), the submodule should be untouched - it should have remained at `deadbeef` and not reverted, it was not asked to be discarded.

### Actual behavior

Changes to the submodule get discarded - it gets reverted from `deadbeef` to `c01dbed5` even though it was not asked to be discarded.

### Additional context

This has started happening since the latest update (2.5.4) - it may therefore be related to changes for #8218.

**Comment by kanji-keraliya** [comment]
Same here . You can check this video https://www.kapwing.com/videos/5f4f320b6b4f1100288302ce

**Comment by niik** [comment]
Hi, just wanted to let you know that we shipped GitHub Desktop v2.5.5 earlier today which we believe fixes this issue. Please make sure you're on the latest version by clicking the `GitHub Desktop` -> `About GitHub Desktop` menu item on macOS or `Help` -> `About GitHub Desktop` on Windows.

**Comment by nycdotnet** [comment]
Hi - thanks for this fix.  This seems to have significantly improved the performance of discarding a single file as well.

**Comment by TCWORLD** [comment]
@niik Cheers for that. I can confirm that its fixed the problem 👍

**Comment by Afronte** [comment]
> ### Describe the bug
> When using submodules, if changes to a file completely unrelated to the submodule (e.g. Readme.md) are discarded, the submodule is randomly checked out to the last committed SHA (detached head state), even though the submodule should not have been touched.
> 
> ### Version & OS
> * Windows 10 (2004)
> * Github Desktop Version 2.5.4
> 
> ### Steps to reproduce the behavior
> 1. Open repository (Foo) which includes a submodule (Bar). Bar is currently at, say `c01dbed5`.
> 2. Make commits to the submodule (Bar), its head is now at, say `deadbeef`.
>    Foo repository now shows Bar as changed - showing -`c01dbed5` +`deadbeef` - this is expected behaviour.
> 3. Edit some other file in Foo - lets say README.md.
>    Foo now shows README.md as also being changed - again expected behaviour
> 4. Discard changes to **only** README.md in Foo.
> 5. Bar is now back at `c01dbed5` - even though it was **not** discarded! Changes in the submodule go irrevocably missing.
> 
> ### Expected behavior
> After discarding the unrelated file (README.md), the submodule should be untouched - it should have remained at `deadbeef` and not reverted, it was not asked to be discarded.
> 
> ### Actual behavior
> Changes to the submodule get discarded - it gets reverted from `deadbeef` to `c01dbed5` even though it was not asked to be discarded.
> 
> ### Additional context
> This has started happening since the latest update (2.5.4) - it may therefore be related to changes for #8218.

>problem is solved

**Comment by Afronte** [comment]
Duplicate of #### 

> [`_****_`](

- 

- [ ] url

)
