### ISSUE TITLE
Error message "aborting commit due to empty commit message"

### ISSUE THREAD

**Issue by rgendroz** [desktop/desktop#10462]
### Describe the bug

This message appears

![image](https://user-images.githubusercontent.com/49240897/91452197-9ca7fe00-e87e-11ea-9566-706fcfd58fe9.png)

event a text is given

![image](https://user-images.githubusercontent.com/49240897/91452274-ae89a100-e87e-11ea-921b-b56747c079be.png)

### Version & OS

![image](https://user-images.githubusercontent.com/49240897/91452330-bb0df980-e87e-11ea-95a6-d48ad591ac14.png)

### Steps to reproduce the behavior

1. Go to Changes
2. Give a commit message
3. Click on 'Commit to Master'

### Expected behavior

Commit

### Actual behavior

Error message

Thanks for help!

**Comment by steveward** [comment]
@rgendroz thanks for the report. Has committing previously worked on this machine?

Could you also share the output of the following command from Git Bash?

`git config -list --show-origin`

**Comment by rgendroz** [comment]
Hello Steve,

Thanks for your reply,

Yes, the commit worked many times well on this same machine,

Here is the result oft he show origin command:

raoul.gendroz@INT-NB027 MINGW64 ~
$ git config --list --show-origin
file:C:/Program Files/Git/etc/gitconfig diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/etc/gitconfig filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/etc/gitconfig filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/etc/gitconfig filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/etc/gitconfig filter.lfs.required=true
file:C:/Program Files/Git/etc/gitconfig http.sslbackend=openssl
file:C:/Program Files/Git/etc/gitconfig http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/etc/gitconfig core.autocrlf=true
file:C:/Program Files/Git/etc/gitconfig core.fscache=true
file:C:/Program Files/Git/etc/gitconfig core.symlinks=false
file:C:/Program Files/Git/etc/gitconfig pull.rebase=false
file:C:/Program Files/Git/etc/gitconfig credential.helper=manager
file:C:/Users/raoul.gendroz/.gitconfig  user.name=Raoul Gendroz
file:C:/Users/raoul.gendroz/.gitconfig  user.email=raoul.gendroz@intusdata.ch
file:C:/Users/raoul.gendroz/.gitconfig  filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/raoul.gendroz/.gitconfig  filter.lfs.process=git-lfs filter-process
file:C:/Users/raoul.gendroz/.gitconfig  filter.lfs.required=true
file:C:/Users/raoul.gendroz/.gitconfig  filter.lfs.clean=git-lfs clean -- %f


Avec mes meilleures salutations
Raoul Gendroz
Consultant en Digitalisation Fiduciaire
intusdata sa
Rue Marterey 36
1005 Lausanne // Suisse
T // +41 21 635 31 02
D // +41 43 399 47 04
Skype // intusdata ag
raoul.gendroz@intusdata.ch<mailto:raoul.gendroz@intusdata.ch>
intusdata.ch<https://www.intusdata.ch/>


Expertise digitale pour les
fiduciaires suisses depuis 1982.


-------- Message transféré --------
Sujet :

Re: [desktop/desktop] Error message "aborting commit due to empty commit message" (#10462)

Date :

Thu, 27 Aug 2020 09:52:02 -0700

De :

Steve Ward <notifications@github.com><mailto:notifications@github.com>

Répondre à :

desktop/desktop <reply@reply.github.com><mailto:reply@reply.github.com>

Pour :

desktop/desktop <desktop@noreply.github.com><mailto:desktop@noreply.github.com>

Copie à :

rgendroz <raoul@gendroz.ch><mailto:raoul@gendroz.ch>, Mention <mention@noreply.github.com><mailto:mention@noreply.github.com>



@rgendroz<https://github.com/rgendroz> thanks for the report. Has committing previously worked on this machine?

Could you also share the output of the following command from Git Bash?

git config -list --show-origin

**Comment by steveward** [comment]
@rgendroz thanks for sharing that. Could you try committing via the command line to see if that succeeds? Here's how to do that:

1. Go to `Repository` > `Open in <command_line>`
2. Run `git add -A`
3. Run `git commit -m "commit message here"`

Let me know if that succeeds.

**Comment by tierninho** [comment]
@rgendroz  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by rparkins999** [comment]
I am seeing the same problem. `git commit` worked before for me. It used to bring up my editor (kate) and wait for me to type in a commit message, save it, and exit the editor, and then do the commit. Now git brings up my editor (kate) but does not wait. Instead git responds
Aborting commit due to empty commit message.
and exits. I tried
`git config --global core.editor "kate -w"`
as suggested in an old stackoverflow posting, but then `git commit` emits the error message without even starting kate. `git commit -m <message>` works. I'm running git version 2.43.0, which the latest version supported by my (linux) OS openSUSE Leap 15.6.
