### ISSUE TITLE
Similar issue like 4872(https://github.com/desktop/desktop/issues/4872)

### ISSUE THREAD

**Issue by abhishek21nair** [desktop/desktop#10466]
Hi All facing the same issue, tried all of the above solutions, did not work for me.

below is my JSON file.

{
"name": "laravel/laravel",
"description": "The Laravel Framework.",
"keywords": [
"framework",
"laravel"
],
"license": "MIT",
"type": "project",
"require": {
"php": ">=7.4.0",
"laravel/framework": "^7.24",
"laravel/tinker": "~2.0",
"laravelcollective/html": "~6.1",
"milon/barcode": "^7.0",
"maatwebsite/excel": "~3.1.21",
"fideloper/proxy": "^4.2",
"laravel/ui":"^2.0",
"fruitcake/laravel-cors": "^2.0"
},
"require-dev": {
"composer/composer": "^1.10",
"filp/whoops": "~2.0",
"fzaninotto/faker": "^1.9",
"mockery/mockery": "^1.0",
"phpunit/phpunit": "^8.5"
},
"autoload": {
"classmap": [
"database"
],
"psr-4": {
"App\": "app/"
}
},
"autoload-dev": {
"psr-4": {
"Tests\": "tests/"
}
},
"scripts": {
"post-root-package-install": [
"php -r "file_exists('.env') || copy('.env.example', '.env');""
],
"post-create-project-cmd": [
"php artisan key:generate"
],
"post-install-cmd": [
"Illuminate\Foundation\ComposerScripts::postInstall"
],
"post-update-cmd": [
"Illuminate\Foundation\ComposerScripts::postUpdate"
],
"post-autoload-dump": [
"Illuminate\Foundation\ComposerScripts::postAutoloadDump",
"@php artisan package:discover"
]
},
"config": {
"preferred-install": "dist",
"sort-packages": true,
"optimize-autoloader": true
}
}

I have tried disabling antivirus also as well ass tried proxy command which is given above.

error:

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

J:\wamp64\www\Upgrade>composer diagnose

Deprecated: Directive 'track_errors' is deprecated in Unknown on line 0
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: FAIL
[Composer\Downloader\TransportException] Could not resolve host: api.github.com
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: (available)
Dev Public Key Fingerprint: (available)
OK
Checking composer version: OK
Composer version: 2.0.0-alpha3
PHP version: 7.4.9
PHP binary path: J:\wamp64\bin\php\php7.4.9\php.exe
OpenSSL version: OpenSSL 1.1.1g 21 Apr 2020

J:\wamp64\www\Upgrade>

Any help will be appreciated, Thanks in Advance.

ticket used for reffrance URL:
https://github.com/desktop/desktop/issues/4872

**Comment by steveward** [comment]
@abhishek21nair this issue tracker is for GitHub Desktop -- we cannot assist you with issues with Composer. I'd recommend opening an issue there (https://github.com/composer/composer/issues). If you have any questions about GitHub Desktop please let us know.

**Comment by abhishek21nair** [comment]
Thanks @steveward .
