### ISSUE TITLE
Comparing branches in full screen mode does not show the "merge into" information

### ISSUE THREAD

**Issue by robbiegod** [desktop/desktop#10463]
### Describe the bug

Hi, I recently updated Github Desktop to version 2.5.4 on Windows 10.  When I compare a branch to another branch and want to merge the branches together, I am not seeing the button to merge them together when I GD open in full screen mode.  The messages would appear above the "Merge into myBranch" blue button in the left column.

I can get the information to display by exiting full screen mode.

I have also tried running GD in Windowed mode, but still the message does not appear.  Only when I toggle the full screen mode will it appear.

### Version & OS

Github Desktop to version 2.5.4
Windows 10 Pro

### Steps to reproduce the behavior

1. Create two branches. 
2. Make some changes in one of the branches and commit those changes.
3. Switch to the other branch.
4. From the Branch menu, click Compare to Branch.

### Expected behavior

You should see the message in the left column of the window above the Merge into blue button that says something like "it is safe to merge branch_one into branch_two.

### Actual behavior

The message does not appear.  It only appears after I toggle full screen mode.

**Comment by niik** [comment]
Hey @robbiegod, thanks for opening this. Do you think you could share a screenshot of what you're seeing? I tried reproducing it on Windows 10 running in both full screen and windowed mode but I couldn't.

<img width="844" alt="image" src="https://user-images.githubusercontent.com/634063/91456176-412c3f00-e883-11ea-9608-9c07a62bf618.png">

**Comment by robbiegod** [comment]
Basically, where you see "There will be 4 conflicted files when merging origin/diff-too-large into repo-trash-error, I don't see that message until I toggle our of the full screen mode or the blue button if there is a message.

If there is nothing to merge, i also don't see the "there is nothing to merge message" and the "greyed out button.

I can try re-installing the application, perhaps it is something that went wrong with the update. I'll get you a screenshot asap.

**Comment by robbiegod** [comment]
![Github-Desktop---no-merge-into-button-panel](https://user-images.githubusercontent.com/3711317/91459023-2f7f7300-e854-11ea-857c-ca7569f4604b.jpg)

See the attached screenshot. @niik

**Comment by niik** [comment]
@robbiegod What happens if you click on the branch listed under "Other branches"? From looking at that screenshot it seems you've filtered the list but not yet selected the branch

**Comment by robbiegod** [comment]
@niik  This was difficult to screenshot.  The missing button would appear when I clicked off of Github Desktop to open the snip tool.  I had to print screen and crop it for you...

The screenshot is right after I have selected the branch to compare my branch too. That's why it looks weird.

I removed my Repository name because its my url, so i didn't want to expose that.  That is not an issue, in case you were wondering.

**Comment by robbiegod** [comment]
@niik A friend of mine has a mac and updated to the latest version of Github Desktop. We were doing a screenshare and I saw the same thing occuring on his system too.

I did forget out that after I do the compare, then select the branch, if i then click anywhere then the button appears.

**Comment by niik** [comment]
I wonder if #10479 is related to this? Does it seem like the same issue you're facing @robbiegod (save for the full screen part?)

**Comment by tierninho** [comment]
@robbiegod As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by robbiegod** [comment]
@niik  @tierninho  Issue 10479 seems very similar.  Also, the problem also occurs on mac github desktop too.

**Comment by niik** [comment]
@robbiegod Would you be able to upgrade to the latest version of GitHub Desktop (2.5.5) and let us know if the problem remains? We believe it was fixed by #10485.

**Comment by tierninho** [comment]
Closing as the fix should be in the latest build. Please let us know otherwise. Thank you for using Desktop!
