### ISSUE TITLE
Fail to start from WSL2 due to CRLF line endings in github.sh script

### ISSUE THREAD

**Issue by Anthropic** [desktop/desktop#10461]
### Describe the bug

In a [WSL2(Windows Subsystem for Linux 2)](https://docs.microsoft.com/en-us/windows/wsl/about) available on Windows 10, running github CLI command fails to start the Github Desktop.

### Version & OS

GitHub Desktop:
Version 2.5.4
Operating system:
Microsoft Windows [Version 10.0.19041 Build 19041]
WSL enabled with Ubuntu 18.04.5 LTS

### Steps to reproduce the behavior

1. Install WSL2 on a Windows 10 system by following Microsoft's Guide, Ubuntu 18.04.5 LTS is installed for example.
2. Install Github Desktop.
3. Start bash, wsl from Start Menu, or start from your installed Linux distro app ubuntu
4. Run github and you can observe the error message

### Expected behavior

By running github in WSL2 should the application start as expected as it does in cmd, PowerShell and Git bash on Windows 10.

### Actual behavior

The application won't start and a script error is printed.
```bash
$ github
/mnt/c/Users/Serious/AppData/Local/GitHubDesktop/bin/../app-2.5.4/resources/app/static/github.sh: 2: /mnt/c/Users/Serious/AppData/Loc: not foundsktop/bin/../app-2.5.4/resources/app/static/github.sh:
/mnt/c/Users/Serious/AppData/Local/GitHubDesktop/bin/../app-2.5.4/resources/app/static/github.sh: 5: /mnt/c/Users/Serious/AppData/Loc: not foundsktop/bin/../app-2.5.4/resources/app/static/github.sh:
/mnt/c/Users/Serious/AppData/Local/GitHubDesktop/bin/../app-2.5.4/resources/app/static/github.sh: 20: /mnt/c/Users/Serious/AppData/Local/GitHubDesktop/bin/../app-2.5.4/resources/app/static/github.sh:
Syntax error: "elif" unexpected (expecting "then")
```

### Additional context

Different issue to the original failure for WSL launch described in #4998 it seems.

## UPDATED: The fix?

I believe I found the cause, in script AppData/Local/GitHubDesktop/app-2.5.4/resources/app/static/github.sh has CRLF line endings. I opened the file in vscode and re-saved the file with LF and it has now started working.

It now opens but shows lots of formerly unchanged files as "Only whitespace changes found" though.

**Comment by tierninho** [comment]
@Anthropic Thanks for the update and glad you found a fix. Just wanted to confirm that the only issue is the "whitespace" message as of now?

I know we have an open issue on committing after changing from CRLF to LF here: https://github.com/desktop/desktop/issues/3034 Hopefully you do not run into this.

For reference, GitHub has [documentation about how to best deal with line endings changes](https://help.github.com/articles/dealing-with-line-endings/). I'd recommend taking a look at that to see what the best configuration option will be for your specific situation. I hope that helps!

**Comment by Anthropic** [comment]
@tierninho no problem happy to help 👍
I shouldn't hit the saving issue as I always set vscode to use LF in all my repos.

The whitespace issue is the last issue remaining for me.
If you want me to try any fixes I am happy to do what I can to help anyone resolve the issue.

**Comment by tierninho** [comment]
Thanks for the update, @Anthropic !

Gonna let one of our developers chime in here to clarify the expectations and what any future work in this area might look like.

**Comment by Anthropic** [comment]
@tierninho vscode run from the same bash doesn't have the same issue, so I can use that for now.

## VSCode shows no changed files for the same directory if I run it from WSL or Win
![image](https://user-images.githubusercontent.com/1182507/91657623-d0e12000-eb05-11ea-9c39-0d079e87081d.png)


## Github desktop shows the whitespace message
![image](https://user-images.githubusercontent.com/1182507/91657599-8b245780-eb05-11ea-91e9-583ccabbe28e.png)

ps. is there any more info you need or can the more-info-needed flag be removed?
