### ISSUE TITLE
Local directory

### ISSUE THREAD

**Issue by Sliii** [desktop/desktop#10464]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by Tengkuf1996** [comment]
> ### Describe the feature or problem you’d like to solve
> A clear and concise description of what the feature or problem is.
> 
> ### Proposed solution
> How will it benefit Desktop and its users?
> 
> ### Additional context
> Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by Rhmd03** [comment]
> > ### Describe the feature or problem you’d like to solve
> > A clear and concise description of what the feature or problem is.
> > 
> > ### Proposed solution
> > How will it benefit Desktop and its users?
> > 
> > ### Additional context
> > Add any other context like screenshots or mockups are helpful, if applicable.
> 
>
