### ISSUE TITLE
File removed on discard instead of revert it

### ISSUE THREAD

**Issue by kanji-keraliya** [desktop/desktop#10467]
After updated Version **2.5.4** file deleted on discard changes and we can't perform discard action from software

Here is case  :

1. Edit any existing file and click on discard. 
2. Its deleted file instead of revert it back

Can you help me to resolve it ASAP.

Thanks

**Comment by steveward** [comment]
Thanks for the report @kanji-keraliya. I was unable to reproduce this behavior. Are you using a Windows operating system? Are you able to reproduce this issue consistently? Any extra information (screenshots/gifs/videos) would be helpful. 

Your changes should also be recoverable from the Recycle Bin/Trash if you have not yet been able to restore them.

**Comment by stevebell117** [comment]
I am seeing this behavior as well, on Mac. You have to "Discard Changes" multiple times for the file to be added back, but it always deletes it the first few tries.

**Comment by kanji-keraliya** [comment]
@steveward I am using **Windows** system but getting same error in MAC also.
also After updated Version 2.5.4 getting sub module error before this version not showing this error. 

`fatal: destination path 'xxx/xxx/xxx/jsdoc/docdash' already exists and is not an empty directory.
fatal: clone of 'git@github.com:clenemt/docdash.git' into submodule path 'xxx/xxx/xxx/jsdoc/docdash' failed
Failed to clone 'jsdoc/docdash'. Retry scheduled
fatal: destination path 'xxx/xxx/xxx/jsdoc/docdash' already exists and is not an empty directory.
fatal: clone of 'git@github.com:clenemt/docdash.git' into submodule path 'xxx/xxx/xxx/jsdoc/docdash' failed
Failed to clone 'jsdoc/docdash' a second time, aborting`

**Comment by kanji-keraliya** [comment]
@steveward here is video link https://www.kapwing.com/videos/5f4f320b6b4f1100288302ce

**Comment by niik** [comment]
Seems like we've gotten a few reports that are similar here. Going to group them together into #10469. Please follow that issue for updates.
