### ISSUE TITLE
Why does this happen. I wanted to push some changes I made but I lost them even though I reverted stashed changes

### ISSUE THREAD

**Issue by masterjunior24** [desktop/desktop#10477]
![image](https://user-images.githubusercontent.com/59114638/91737949-781e8f80-ebb8-11ea-8bb8-de1157f06f01.png)

**Comment by tierninho** [comment]
@masterjunior24 Thanks for reaching out. This message appears so you can avoid any potential merge conflicts if you pull the same file that you may be actively working on. 

> I wanted to push some changes I made but I lost them even though I reverted stashed changes

Sorry for the trouble! Can you elaborate on the lost files and outline the steps you took? Also, please attach your logs from that day. See the Help menu in Desktop.

**Comment by tierninho** [comment]
As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
