### ISSUE TITLE
When I save a repo to github or to the remote the name gets changed

### ISSUE THREAD

**Issue by rickhall54** [desktop/desktop#10476]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by rickhall54** [comment]
I am not , maybe it is changing the name on my end.  i found once. I'll have to do it later. Sorry and Thank you

**Comment by steveward** [comment]
@rickhall54 it sounds like you were able to track down what was causing this? Let me know if that is not the case and we can assist you further.
