### ISSUE TITLE
Update git name and email after signing in

### ISSUE THREAD

**Issue by AssetKid** [desktop/desktop#10474]
### Describe the feature or problem you’d like to solve

At the moment, whenever you sign in with a different account, the git name and email are not updated.

### Proposed solution

Whenever you sign in, the git name and email should be updated to match those of the current account.

Alternatively, the app can display a warning me when I am about to commit to a repo with the wrong git name and email.

### Additional context

Since Github Desktop does not support multiple accounts yet, I am forced to switch accounts very often. Sometimes I forget to clear the git name and email and start pushing commits with the wrong name and email.

This can be catastrophic if you use a personal email on one of your accounts. It has happened to me before 🙂

**Comment by the-godess** [comment]
cant sing in my bit wallet

**Comment by steveward** [comment]
Thanks for the feedback @AssetKid. We are tracking better handling of improper commit attribution in https://github.com/desktop/desktop/issues/610. There is some [work being done for per-repository commit attribution](#9449) and Git also has [a configuration option you can use](https://github.com/desktop/desktop/issues/610#issuecomment-630411213) to differentiate between work and personal repositories. I hope that is helpful!
