### ISSUE TITLE
GitHub Desktop on Windows 

### ISSUE THREAD

**Issue by padfoot33** [desktop/desktop#10489]
### Describe the feature or problem you’d like to solve

Hi,
I am from India and using github desktop on windows 10, the problem I think is that whenever I download or clone a repository from github it only downloads at about 500KB/sec speed which is fine but my connection is of 50 Mbps i.e. atleast  5 to 6 MB/sec speed should be available and it is when I try to check with speed test or I download from google drive or surf Youtube videos at 4K. Can you please make any improvements or is there any problem from my side? Please guide me through. Thank You

### Proposed solution

Increase speed by probably using good servers or anything like that, probably removing any bandwidth barrier if any.

**Comment by niik** [comment]
Hi padfoot33, I'm sorry to hear you're having problems with transfer bandwidth while using GitHub Desktop. GitHub Desktop does not impose any transfer speed limits. When cloning, fetching, or pulling using GitHub Desktop we rely entirely on Git which doesn't have any built in limitations either.

As such I'm afraid there's not much GitHub Desktop can do to help you out here. I would recommend consulting the [connectivity troubleshooting guide](https://docs.github.com/en/github/getting-started-with-github/troubleshooting-connectivity-problems) and the [GitHub Debug](https://github-debug.com/) site and if that doesn't resolve your issue I would recommend contacting [GitHub Support](https://support.github.com) directly

**Comment by padfoot33** [comment]
Thank You niik, will try out those solutions...
