### ISSUE TITLE
credential.helper is explicitly unset for some ops

### ISSUE THREAD

**Issue by saurabhshri** [desktop/desktop#10486]
### Describe the bug

For some operations, git commands are executed by explicitly unsetting `credential.helper` : 

```
git -c credential.helper= clone --recursive --progress -- <>
```

I love using Github Desktop, it's my favourite git client. I had to work on some repositories stored in AWS codecommit, access to which is through credential helper. I can clone and do git operation with cli just fine, but it doesn't work on Github Desktop.

After enabling dev tools, it shows on console that the executed git commands have `git -c credential.helper= ` appended. 

Is there anyway to override this, or not do this? I would love to be able to use Desktop to work on them too.

[Since this is a federated login, I don't have an option for username/password, I can only use credential helper]

### Version & OS

Desktop Version 2.5.4, macOS Mojave 10.14.6

### Steps to reproduce the behavior

1. Add credentials helper to git config

```
[credential]
        helper = !aws --profile git-codecommit codecommit credential-helper $@
        UseHttpPath = true
```

2. Try to use Desktop to clone, or perform any git operation : 

<img width="560" alt="Screenshot 2020-09-02 at 2 46 36 PM" src="https://user-images.githubusercontent.com/12415700/91963152-20546580-ed2b-11ea-945f-e9b2e9b0173e.png">

3. Use CLI to clone without unsetting credential.helper : 

```
git clone <url>
```

### Expected behavior

Git operations should work.

### Actual behavior

Desktop asks for username/password.

**Comment by niik** [comment]
Hi @saurabhshri, sorry to hear you're having problems. The short answer here is no, there's currently no way to override that behavior. I can think of one workaround for your issue but I'm hesitant to offer it as it's entirely possible that we'll make a change in GitHub Desktop in the future which makes the workaround impossible to use. So with the caveat that this is an unsupported workaround that's subject to change it's possible that specifying a **host specific credential helper** would work in your case. See https://git-scm.com/docs/gitcredentials.

Perhaps something like

```
[credential "https://git-codecommit.us-east-1.amazonaws.com"]
        helper = !aws --profile git-codecommit codecommit credential-helper $@
        UseHttpPath = true
```

I haven't tried with AWS CodeCommit myself, is this credential helper setup mandatory for all uses of the service or is it specific to your (or your company's) setup? I.e. is there a scenario where one could use AWS CodeCommit without a custom credential helper?

I'm going to close this issue as this use case is not something we support at the moment but I'd love to hear if the workaround worked for you and your answer to the question above.

**Comment by saurabhshri** [comment]
Hi @niik, I would try the workaround tonight and report back. Thank you so much for offering it, and I completely understand that this might stop working someday.

> is this credential helper setup mandatory for all uses of the service or is it specific to your (or your company's) setup

This is straight from AWS's docs (https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-https-unixes.html)

>  if you want to connect to CodeCommit using a root account, federated access, or temporary credentials, you can use the credential helper that is included in the AWS CLI.

Federated access is a pretty common way of delegating access so that one could sign in using SSO from, say for example using Gsuite.

Thanks!

PS Would a feature request to have it as a configuration option be accepted? :)
