### ISSUE TITLE
cannot run Github desktop

### ISSUE THREAD

**Issue by pchiou6932** [desktop/desktop#10488]
### Describe the bug

I cannot run Github desktop, even after reinstalling it, since July or end of June. Every time when I try to run it, I get a white screen and the CPU usage goes up to almost 100%.   

### Version & OS

Windows 7
GitHub Desktop v2.5.4

### Expected behavior

able to run Github desktop

### Screenshots

![未命名](https://user-images.githubusercontent.com/62239633/91969590-a3b78c00-ed16-11ea-8c26-1fd35f86296f.jpg)

**Comment by niik** [comment]
Thanks for the report! Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by pchiou6932** [comment]
Unfortunately I am not able to go to the file menu since I get only the white screen after clicking on Github Desktop.

**Comment by dhunmoon** [comment]
go to your C:\Users\YourUserNae\AppData\Roaming\GitHub Desktop\logs to get log files.

**Comment by pchiou6932** [comment]
Thanks for the tip. Here is the log of July 3rd.
[2020-07-03.desktop.production.log](https://github.com/desktop/desktop/files/5163284/2020-07-03.desktop.production.log)

**Comment by niik** [comment]
@pchiou6932 If that's the most recent log file there's really not a lot to go on here I'm afraid. I would try a complete reinstall by means of

1. Quitting GitHub Desktop and restarting your machine to ensure no rogue processes are hanging about
1. Uninstalling GitHub Desktop
1. Deleting the `C:\Users<YourUserName>\AppData\Roaming\GitHub Desktop` folder
1. Downloading and installing GitHub Desktop again from https://desktop.github.com

If that doesn't work I'd try disabling hardware acceleration as a final last-ditch effort by setting the `GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION` environment variable to `1` by running `set GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1` in `cmd.exe` and restarting your machine.

**Comment by pchiou6932** [comment]
@niik Many thanks for your prompt reply. The most recent log should be the following one
[2020-09-02.desktop.production.log](https://github.com/desktop/desktop/files/5163439/2020-09-02.desktop.production.log)

Actually I've tried your first suggestion, but unfortunately it didn't work. I'll try the second one.

**Comment by pchiou6932** [comment]
The problem has been solved by disabling hardware acceleration. Many thanks to @niik and @dhunmoon for your kindly help!

**Comment by chriswinslow** [comment]
There is a common theme among ionic-based apps that shows messed GUI; Visual Studio Code, Postman and of course Github desktop. If the ionic-based app has the option to turn off this broken feature within the app then try that, but if it doesn't, in Windows, you can disable the GPU accelerator by adding the following flag in the shortcut properties of the app's desktop/start menu icon --disable-gpu  For example right click on the app's icon and select Properties and in the Target enter: "C:\Location of of program\GitHubDesktop\GitHubDesktop.exe" --disable-gpu and it should fix the display issue.
