### ISSUE TITLE
log all command-line messages

### ISSUE THREAD

**Issue by wkuckro** [desktop/desktop#10483]
### Describe the feature or problem you’d like to solve

As a user, it'd be great to have every GUI action logged as the equivalent CLI message that might be used. Often a user may know the action they want to take, can use the desktop client to do the action, but doesn't know hot to put together the exact message in a CLI.

### Proposed solution

Logging messages in a console where users can see their output as they work would help increase knowledge and comfort in using CLIs

**Comment by niik** [comment]
Hey @wkuckro, thanks for opening this!

This particular request has been brought up before, both for the classic apps and for the Electron version. Most recently in https://github.com/desktop/desktop/issues/1570. It's an appealing thought but as is explained in [the issue](https://github.com/desktop/desktop/issues/1570) the majority of Git commands run by GitHub Desktop are low-level Git commands that aren't intended to be used by humans and which would not be helpful for new users wanting to learn Git. The canonical example is the command that GitHub Desktop uses to get the list of branches in a repository.

`git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(objectname:short)%00%(author)%00%(committer)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%(trailers:unfold,only)%00%1F refs/heads refs/remotes`.

Whereas a regular command line user would probably just use `git branch`.

Or `git log -g -z --pretty=%gD%x1F%H%x1F%gs refs/stash` where a CLI user would type `git stash list`.

We could provide the equivalent commands to what we're doing but I think there are other tools out there more suited for learning to navigate the command line environment. I'm going to close this issue and refer you to #1570 where you can subscribe for any updates.
