### ISSUE TITLE
Not Cloning repoitory, see the screen-shot and help me.

### ISSUE THREAD

**Issue by imhasib062** [desktop/desktop#10495]
![Screenshot 2020-09-03 083633](https://user-images.githubusercontent.com/50325055/92065299-44628600-edc1-11ea-893b-b22f37cdc8c2.jpg)
### Describe the feature or problem you’d like to solve

I'm trying many times but the initial result is error.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by dhunmoon** [comment]
I think there is something wrong with the file path which is getting cloned from the remote repo. There are certain restrictions on what and what not a file path can contain and sometimes. Sometimes file names created in one operating system are invalid in other.

Please go to [this link](https://github.com/t-b/git-pre-commit-hook-windows-filenames) and follow the instruction it should solve your issue.

>Note: I would suggest waiting for an official solution from a staff member because I am not one. 😄

**Comment by imhasib062** [comment]
> I think there is something wrong with the file path which is getting cloned from the remote repo. There are certain restrictions on what and what not a file path can contain and sometimes. Sometimes file names created in one operating system are invalid in other.
> 
> Please go to [this link](https://github.com/t-b/git-pre-commit-hook-windows-filenames) and follow the instruction it should solve your issue.
> 
> Note: Since this is something which is related to File path if you let developers know which opertaing system you are using that will help them. My guess is it's windows because I have only seen this error occure in windows only.but still 
> 
>  **Important:** I would suggest waiting for an official solution from a staff member because I am not one.

Thank you so much.

**Comment by steveward** [comment]
@imhasib062 what @dhunmoon shared is correct -- in this case I believe the `?` is the issue in the filename. Windows has reserved characters that cannot be used in filenames. The easiest way to resolve this would be to edit the filename directly on GitHub and then try cloning the repository again. If you do not have write permissions to the repository then you could fork the repository and submit a pull request to request to have the file name changed. Let me know if you have any questions about how that process.
