### ISSUE TITLE
How to code sign Update.exe?

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#10494]
When I was building GitHub Desktop, I found I can't code sign Update.exe, because I can't find it during the build process, I can only find it in the installlation folder after install.
![image](https://user-images.githubusercontent.com/5396286/92061741-9dceb300-edc9-11ea-9b94-35c15f73a4af.png)

My code sign method is uploading the binary to server to do digital sign in server side, it was done by my code sign script, and it  works well for GitHubDesktop.exe and GitHubDesktopSetup.exe, because I can found them during the build process.

I found the code sign method in GitHub Desktop is download the cetificate file to local to do code sign locally. But I can't get the certificate file,  I can only sign it by uploading to the server. Does it support to sign the Update.exe by uploading to server? Or any other method?

**Comment by niik** [comment]
Hi @TerryChan, I'm afraid I'm not sure what you mean by "I can only sign it by uploading to the server" but the `Update.exe` process is produced, and signed by, [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows). I would look there for more guidance. As this is not an issue with GitHub Desktop I'm going to close it.
