### ISSUE TITLE
Thanks for clarifying @CKingX!

### ISSUE THREAD

**Issue by 256SHA** [desktop/desktop#10497]
Thanks for clarifying @CKingX!

I wasn't quite able to reproduce this myself but I did spot something a bit odd. I uninstalled GitHub Desktop and removed the `GitHubDesktop\bin` entry from the path env var:

<img width="502" alt="Screen Shot 2020-06-30 at 12 30 45" src="https://user-images.githubusercontent.com/634063/86116505-d7372980-bacd-11ea-943f-59adbdd6e3a1.png">

I then installed GitHub Desktop again and looked at the new environment variable:

<img width="501" alt="Screen Shot 2020-06-30 at 12 32 01" src="https://user-images.githubusercontent.com/634063/86116842-60e6f700-bace-11ea-99ef-930713c78fdf.png">

So while in my case it doesn't appear as if anything got it looks like the `%USERPROFILE%` got auto-expanded and resolved. Looking into this some more it would appear that this is an artifact of how we load the `PATH` environment variable.

We currently load the `PATH` env var through powershell:

https://github.com/desktop/desktop/blob/d6f7518f43bd7f9f55e56737e2845474fe2c7ebb/app/src/lib/process/win32.ts#L20-L38

This was introduced in https://github.com/desktop/desktop/pull/1925/commits/9820f7f988e04ea4b268f1462f6dbe6bb6d8c473#diff-fc992a6c0da9f6047bd328ec09982ec2R111 and copied from Atom https://github.com/atom/atom/pull/10326/files.

The reason for this odd-looking way of loading the path variable is that the previous method of using `reg.exe query HKCU\Environment` could fail due to a ban on registry modification in a group policy on Windows even though reg.exe was only reading a value, not modifying it. This peculiarity was the reason behind implementing our own registry library (https://github.com/desktop/desktop/pull/3492).

If we switch the loading (though not writing) of this environment variable to `registry-js` we need to test it with paths containing non-ascii characters as well.

@CKingX could you do the same thing as I did above and screenshot the before and after?

_Originally posted by @niik in https://github.com/desktop/desktop/issues/10100#issuecomment-651730371_

**Comment by niik** [comment]
Hey @256SHA, copying and pasting a comment from a previously closed issue as a new issue makes it hard for us to understand the underlying problem. Please open a new issue where you describe, in your own words, what the problem is.
