### ISSUE TITLE
unborn head

### ISSUE THREAD

**Issue by kchashin** [desktop/desktop#10500]
### Describe the bug 

The gihub desktop is showing that there is no branches, it shows i made a pull request and that i made a new branch on the website, but does not show the original branch and does not allow me to click on the branch or the pull request. It also says cannot publish unborn head in the publish branch tab.

### Version & OS

github 2.5.4  Windows 10
### Steps to reproduce the behavior
This shows up on the main tabs and does not allow me to push my work to github

### Expected behavior

It should push and show up on the website when checking.

### Actual behavior

it doesnt even push 

### Screenshots
![github issue](https://user-images.githubusercontent.com/33077160/92151053-74744e00-edee-11ea-9e20-0bfe1bea071f.PNG)

### Logs

[2020-09-03.desktop.production.log](https://github.com/desktop/desktop/files/5170402/2020-09-03.desktop.production.log)

### Additional context

Please help, i need this to submit my homework

**Comment by tierninho** [comment]
@kchashin It looks like there may be some underlying repository corruption that is causing this issue. 

Try running this in the command line -- In the `Repository` menu > Open in [command line]:

`git gc --prune=now`
`git remote prune origin`

Please let us know how it goes.

**Comment by kchashin** [comment]
I did that and it doesnt seem to have done anything

**Comment by tierninho** [comment]
Can you paste the output of `git fsck`? Thank you.

**Comment by kchashin** [comment]
error: refs/heads/master: invalid sha1 pointer 0000000000000000000000000000000000000000
error: refs/remotes/origin/HEAD: invalid sha1 pointer 0000000000000000000000000000000000000000
error: refs/remotes/origin/master: invalid sha1 pointer 0000000000000000000000000000000000000000
error: invalid HEAD
error: bad ref for .git/logs/HEAD
error: bad ref for .git/logs/refs/heads/master
error: bad ref for .git/logs/refs/remotes/origin/HEAD
error: bad ref for .git/logs/refs/remotes/origin/master
dangling commit 6ce185be15130f036b38923e7cb34572fd22ddeb
dangling commit 61eaf291140318225b94da926f6cf7a236fc800a
missing blob 05abe385a84a7a2cac2eedd2cdc1983c07f3c1db
missing tree 0f6bbc829228f8bbc688eeafe7c7f7750312d26c
dangling commit ff4cdbee55f4ea50a3d8db1dc77d16752de54a36
dangling commit 400d8dce098e833a911e10b98dd64ad5b7d1eb3a
dangling commit 7ab17e07304d7df0fccccf40f518c4caae222aea
missing tree 045383b439e78087d53e4673e94198d64458ce52
missing blob 08d53df31b72dddbc3c37e3b92db89cd9e621de9
dangling commit 973c77685eb8f065160a7f36df5bba82e3ce2936

**Comment by tierninho** [comment]
Ok. Please try: 
`rm .git/refs/remotes/origin/HEAD`
`git fetch --all`

Let us know the outcome.

---
Because of the corrupted repo, should you want to back it up see here:
```
git clone --mirror yourrepo backup.repo
tar cjf backup.repo.tar.bz2 backup.repo
scp backup.tar.bz2 ssh://somewhereelse
```
Then, to recover from your backup:
```
tar xjf backup.repo.tar.bz2
git clone backup.repo yourrepo
```

**Comment by kchashin** [comment]
'rm' is not recognized as an internal or external command,
operable program or batch file.

Thats what it says

**Comment by tierninho** [comment]
As you are on Windows, use `del` to replace `rm`. Apologies for that.

**Comment by kchashin** [comment]
Invalid switch - "refs".

**Comment by tierninho** [comment]
@steveward Would the [fix here](https://github.com/desktop/desktop/issues/4325#issuecomment-376921554) work?

**Comment by kchashin** [comment]
with it saying that refs is invalid, how would i even do that?

**Comment by steveward** [comment]
@kchashin if the repository is on GItHub then you should be able to run the commands in the link @tierninho shared. Here are the steps:

1. Open the repository in GitHub Desktop
2. Go to the file menu and select `Repository` > `Open in <command_line>`
3. Run the command `rm .git/refs/remotes/origin/master` to delete the broken ref
4. Run the command `git fetch origin` to grab a new copy of the ref
5. Run the command `git branch -u origin/master` to have your local `master` branch track the `origin/master` branch

**Comment by hani77979** [comment]
ت

**Comment by tierninho** [comment]
@kchashin I hope that worked for you. Please reach out if you need further help. Thanks for using Desktop!
