### ISSUE TITLE
Can't create a new repo in Github Desktop

### ISSUE THREAD

**Issue by jguerriere** [desktop/desktop#10509]
### Describe the bug

I can not create a new repo in Github Desktop. The Create Repository button on the Create New Repository Screen is not clickable. 

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

GitHub Desktop: Version 2.5.4
Mac OS/X Version: 10.15.6 (19G2021)

### Steps to reproduce the behavior

1. Go to File, New Repository
2. Click on add Name and Description
3. Scroll down to Choose Local Path
4. See screenshot
### Expected behavior

Should be able to create a new repository at this point.

### Actual behavior

The Create Repository button is not clickable. See attached. 
![Screen Shot 2020-09-04 at 3 15 19 PM](https://user-images.githubusercontent.com/11351452/92278064-5ed05880-eec2-11ea-8e57-b1a50d92e88e.png)

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@jguerriere Thanks for the issue. It appears you have a repo named GitHub and a folder named GitHub, both in the Documents folder. 

To fix:
- Hold `Shift`+`Command`+`.` to expose hidden files.
- Open the Documents folder > open the GitHub folder
- Scroll down until you see a faded `.git` and `.git attributes` file. 
- Make sure they are not in another repo. Trash them both.

You should be good to go!

![Screen Shot 2020-09-04 at 9 50 14 AM](https://user-images.githubusercontent.com/14828183/92280131-78f34200-ee94-11ea-8269-ffe077507d66.png)

**Comment by tierninho** [comment]
As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
