### ISSUE TITLE
Discarding changes marks file for deletion

### ISSUE THREAD

**Issue by ghostpunchBlosser** [desktop/desktop#10504]
### Describe the bug

In Github Desktop, when attempting to discard a change I get an error message (removing path details and submodule name since it's a private repo that I do not own):

> Cloning into 'H:/localPathToSubmodule'...
> fatal: could not read Username for 'https://github.com': No such file or directory
> fatal: clone of 'https://github.com/RepoPathToSubmodule' into submodule path 'H:/localPathToSubmodule' failed
> Failed to clone 'submoduleName'. Retry scheduled
> Cloning into 'H:/localPathToSubmodule'...
> fatal: could not read Username for 'https://github.com': No such file or directory
> fatal: clone of 'https://github.com/RepoPathToSubmodule' into submodule path 'H:/localPathToSubmodule' failed
> Failed to clone 'submoduleName' a second time, aborting

Then the file I was attempting to discard the change on is instead marked for deletion in the "Changes" column. The change I'm discarding has nothing to do with that particular submodule. I've set up a simple text file to test this out with.

I admit I do not know a whole lot about git (didn't know what a submodule was until researching this problem!), but I use the Desktop application on a daily basis when working on this project. Yesterday is the first time I've ever run into this error and confirmed that at least one other member on my team is encountering the same (we are contributors to this project).

I've read some insights that say the cause of this might be that the submodule that the project is using has been marked private, but I've never personally had to deal with this submodule so I'm not sure how to know if it was visible before or how to further diagnose this issue. I tried going to the repo on GitHub.com and clicking on the submodule in the file list but it produces a 404 error. I'm guessing this is where the issue is?

Just looking for insight so I can ask the right questions to the owner of the repo.

Thank you for any help!

### Version & OS

GitHub Desktop version 2.5.4
Windows 10

### Steps to reproduce the behavior

1. In GitHub Desktop, with a modified file in the Changes column, right-click on the file you want to discard changes on and select "Discard changes"
2. Confirm that you want to discard changes.
3. See error listed above

### Expected behavior

When confirming to discard changes, the file should not show up in the "Changes" column in GitHub Desktop anymore.

### Actual behavior

When confirming to discard changes, the error message appears, followed by the file being marked for deletion.

### Logs

Removing path details from the logs again:

> 2020-09-04T00:03:32.452Z - info: [ui] Background fetch for 2 repositories took 1.948sec
> 2020-09-04T00:12:14.128Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.580s)
> 2020-09-04T00:18:32.484Z - info: [ui] Background fetch for 2 repositories took 1.979sec
> 2020-09-04T00:30:28.159Z - info: [ui] Executing updateSubmodule: git submodule update --recursive --force -- (took 1.609s)
> 2020-09-04T00:30:28.161Z - error: [ui] `git submodule update --recursive --force --` exited with an unexpected code: 1.
> stderr:
> Cloning into 'H:/localPathToSubmodule'...
> fatal: could not read Username for 'https://github.com': No such file or directory
> fatal: clone of 'https://github.com/RepoPathToSubmodule' into submodule path 'H:/localPathToSubmodule' failed
> Failed to clone 'submoduleName'. Retry scheduled
> Cloning into 'H:/localPathToSubmodule'...
> fatal: could not read Username for 'https://github.com': No such file or directory
> fatal: clone of 'https://github.com/RepoPathToSubmodule' into submodule path 'H:/localPathToSubmodule' failed
> Failed to clone 'submoduleName' a second time, aborting
> 
> 2020-09-04T00:33:31.588Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: repoName- ghostpunchBlosser (has token)
> 2020-09-04T00:33:33.351Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.724s)
> 2020-09-04T00:33:35.363Z - info: [ui] Background fetch for 2 repositories took 4.854sec
> 2020-09-04T00:36:07.006Z - info: [ui] Executing updateSubmodule: git submodule update --recursive --force -- (took 1.606s)
> 2020-09-04T00:36:07.009Z - error: [ui] `git submodule update --recursive --force --` exited with an unexpected code: 1.
> stderr:
> Cloning into 'H:/localPathToSubmodule'...
> fatal: could not read Username for 'https://github.com': No such file or directory
> fatal: clone of 'https://github.com/RepoPathToSubmodule' into submodule path 'H:/localPathToSubmodule' failed
> Failed to clone 'submoduleName'. Retry scheduled
> Cloning into 'H:/localPathToSubmodule'...
> fatal: could not read Username for 'https://github.com': No such file or directory
> fatal: clone of 'https://github.com/RepoPathToSubmodule' into submodule path 'H:/localPathToSubmodule' failed
> Failed to clone 'submoduleName' a second time, aborting
> 
> 2020-09-04T00:43:15.092Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.119s)
> 2020-09-04T00:48:31.471Z - info: [ui] Background fetch for 2 repositories took 1.869sec

**Comment by niik** [comment]
Thanks for opening this @ghostpunchBlosser and sorry to hear you're having troubles discarding in the app. I really appreciate the thorough description of the issue, it was most helpful and thanks to that I think I have an idea of what's going on.

For housekeeping purposes I'm gonna close this in favor of #10469 which seems to be identical to this issue. Please subscribe to that issue to follow along with any updates.
