### ISSUE TITLE
Support Shallow Clone

### ISSUE THREAD

**Issue by MuhammedZakir** [desktop/desktop#10506]
Is there any plan for shallow clone?

https://github.com/desktop/desktop/issues/9660#issue-608780641:
> With open source repositories' size in GBs, the app should allow shallow cloning.
> 
> Also, even if a repo has been shallow cloned using terminal, fetch origin from app downloads the "entire" repo making shallow cloning futile.

https://github.com/desktop/desktop/issues/3480#issue-278493813:
> As a user who often contributes translations, documentation improvements, etc. I rarely have much use for an offline copy of a repo's entire history. I [would trade](https://github.com/katrinleinweber/konfig/blob/master/git-Arbeitsdreieck.sh) that for an option to clone shallowly, so that my workflow can be faster.

https://github.com/desktop/desktop/issues/3480#issuecomment-348529403:
> That's a very good point @j-f1. This would also help those who are in countries with poor internet. This will get addressed in our next planning session soon.

Why this is needed is explained pretty well above.

---

https://github.com/desktop/desktop/issues/9660#issue-608780641:
> Moreover, once fetch origin started, there was no way to stop it from within app itself. Restarting the app continued with the fetch.

Is there still no method to stop fetching other than quitting app?

**Comment by niik** [comment]
Hi @MuhammedZakir, thanks for opening this

> Is there any plan for shallow clone?

We don't have any plans to support shallow clones at this time. We're a very small team and we have to make some hard decisions on what features we invest in based on what we believe will bring the most value to our users. We've referred other issues about this to https://github.com/desktop/desktop/issues/3480 so I'm afraid I will do the same here and ask that you subscribe to https://github.com/desktop/desktop/issues/3480 instead. If we decide to prioritize support for shallow clones in the future we will open that issue again to let everyone know about our impending work.

> Why this is needed is explained pretty well above.

Thanks for including those references, that was helpful.

> Is there still no method to stop fetching other than quitting app?

No, we don't support cancelling an ongoing fetch or clone operation at this time. Subscribe to https://github.com/desktop/desktop/issues/2082 for any updates on that.
