### ISSUE TITLE
Allow users to choose whether to use an editor in ~/Applications or /Applications if both have the same editor

### ISSUE THREAD

**Issue by ajs256** [desktop/desktop#10502]
### Describe the feature or problem you’d like to solve

As someone who develops on a shared machine, I have editors installed under my username (in `~/Applications`), and not in the global app directory (`/Applications`). I would like to be able to open in those editors directly from Desktop.

### Proposed solution

Scan for external editors in `~/Applications`. If the same editor is found in both `~/Applications` and `/Applications`, allow the user to choose which one to use.

**Comment by MuhammedZakir** [comment]
Maybe your editor is not support\*? All supported editors in `~/Applications` are detected on mine.

\* https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/configuring-a-default-editor

**Comment by niik** [comment]
Hi @ajs256, what editor are you trying to use? We rely on [app-path](https://github.com/sindresorhus/app-path) on macOS to determine the path to an editor, see https://github.com/desktop/desktop/blob/development/app/src/lib/editors/darwin.ts. I'm afraid I'm not familiar enough with macOS resolution order when locating a path by its bundle ID but I know that we only get one path back from `app-path` so right now we're not able to offer a choice should the application be installed in both locations.

**Comment by ajs256** [comment]
I'm trying to use VSCode, which is installed in both locations. Because the previous user of this computer also had VSC installed, but I can't update it, I have a version that I can update installed under my username. If your library can't give that one priority, then this would probably fall under #5083, and I would use the command `open -a ~/Applications/Visual\ Studio\ Code.app *` in the repo folder.

**Comment by ajs256** [comment]
I apologize for being unclear, I've renamed the issue now.

**Comment by steveward** [comment]
Since GitHub Desktop now provides support for selecting custom editors in any location I believe this can be closed.
