### ISSUE TITLE
CANNOT TRANSFER MY REPOSITORY F

### ISSUE THREAD

**Issue by Caesar1o1** [desktop/desktop#10516]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Problem is what i cant transfer MY repository on new PC. What kind on permission i need get to trasfer it??? Cause i had try added my nickname but its shows " You do not need permission for transfer your own Repository ". How i can transfer my old repository for new PC?

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@Caesar1o1 to get your repository to your new machine you can [clone the repository](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/cloning-a-repository-from-github-to-github-desktop) using GitHub Desktop. Let me know if you have any questions about how to do this!

**Comment by hani77979** [comment]
Y
