### ISSUE TITLE
Support keyboard to confirm on "Merge into branch" dialog

### ISSUE THREAD

**Issue by DanTup** [desktop/desktop#10511]
When clicking Branch -> Merge into Current Branch I'm presented with this dialog:

When the dialog appears, I can immediately type "master" and then use <cursor down> to select the upstream/master branch:

<img width="548" alt="Screenshot 2020-09-05 at 11 55 45" src="https://user-images.githubusercontent.com/1078012/92303658-086d2380-ef6f-11ea-93ec-a53b5e43c58b.png">

However, I can't press <enter>/<space> (with or without any modifier key as far as I can tell) and have to use the mouse to perform the merge. It would be much better if I could do this using only the keyboard.

**Comment by niik** [comment]
Hi @DanTup, thanks for reporting this! I've opened #10519 which should address this issue. I'm hoping we'll have it be part of one of the next production releases but I don't have a good estimate of when that will be just now.

**Comment by DanTup** [comment]
Great, thanks! 🙂
