### ISSUE TITLE
"Revert" is ambiguous

### ISSUE THREAD

**Issue by andybak** [desktop/desktop#10515]
Let's say I have the following commits (most recent at the top)

C. Broke stuff
B. More good stuff
A. Good stuff

I want to get my repo back to the state it was at B.

The current UI makes this confusing. Do I click on C and choose "revert" (meaning "I want to undo this bad commit) or do I click on B and choose "revert" (meaning "I want to go back to this point in time")?

I think it would be clearer if either:

1. the wording was changed to "revert to here" and the user was expected to click on B
or 2. The wording was changed to "revert the changes in this commit" and the user was expected to click on C.

I prefer option 1.

**Comment by niik** [comment]
Hi @andybak, thanks for opening this!

> The current UI makes this confusing. Do I click on C and choose "revert" (meaning "I want to undo this bad commit) or do I click on B and choose "revert" (meaning "I want to go back to this point in time")?

As you've no doubt guessed already you would click on C and choose revert. The revert terminology has a very specific meaning in git [see git-revert](https://git-scm.com/docs/git-revert). If we supported [git reset --hard](https://git-scm.com/docs/git-reset), however, you would chose B to remove all commits leading up to B.

> 1. the wording was changed to "revert to here" and the user was expected to click on B
>    or 2. The wording was changed to "revert the changes in this commit" and the user was expected to click on C.

We would have to chose option 2 here for the reason outlined above. We don't want to introduce behavior that diverges from Git's semantics. A revert means creating a commit which is the exact opposite of the original commit. I would suggest we change the text of the menu item to `Revert Changes in Commit` which should hopefully clarify what to expect while remaining fairly terse.

**Comment by andybak** [comment]
That's a good solution.

(I've personally used git reset a lot more often than I've used git revert - which is why I found this ambiguous)

**Comment by niik** [comment]
> That's a good solution.

Awesome, I'm glad you think so. Would you like to submit a PR to change it?

https://github.com/desktop/desktop/blob/f250d7b51d766c6b9ca5f05b120b95e23b4117bd/app/src/ui/history/commit-list-item.tsx#L160

**Comment by halitogunc** [comment]
Hey @niik I think you can close this issue since these changes are already on development branch.
see: https://github.com/desktop/desktop/blob/development/app/src/ui/history/commit-list-item.tsx#L160

**Comment by niik** [comment]
Hey @halitogunc I believe [the plan](https://github.com/desktop/desktop/issues/10515#issuecomment-688404086) we settled on was to change it to `Revert Changes in Commit` (and appropriately cased for Windows as well). If you want to take a swing at it you're more than welcome

**Comment by halitogunc** [comment]
Oh, thanks for pointing that out. Sure, it is always a pleasure to contribute to the tool I like.

**Comment by danielb987** [comment]
Hi,
Where do I find the option to revert changes in my branch? I have GitHub Desktop version 2.6.1 on Windows 8.1

I asked in this thread since if I open a new Issue, I have the options "Submit a feature request" and "Bug report" and this is neither of them.

Thanks,
Daniel

**Comment by octco** [comment]
Branch to ower reademe-edits
.commits fit bug
