### ISSUE TITLE
GitHub Mac client endless loop on switching branch

### ISSUE THREAD

**Issue by slavag** [desktop/desktop#10528]
### Describe the bug

I'm trying to switch to particular branch and getting endless loop in "switching branch progress bar".
### Version & OS

Version 2.5.4 for MacOS (version Catalina 10.15.6)

### Steps to reproduce the behavior

1. Go to 'current branch'
2. Click on 'current branch'
3. Choose desired branch
4. See endless "switching" with progress bar reaching end over and over again.

### Expected behavior

Switch to branch

### Actual behavior

Branch is not changing, but progress bar is endlessly flickering and reaching end over and over again.  

### Logs

(The error was parsed as 37: Unable to switch branches as there are working directory changes which would be overwritten. Please commit or stash your changes.)

### Additional context

No error message is shown in the GUI.

**Comment by tierninho** [comment]
@slavag Thank you for the report. I sounds like an earlier reported bug here https://github.com/desktop/desktop/issues/9297 that is still being investigated. Please add any details on the thread there if you think they might be relevant.
