### ISSUE TITLE
Github pushing will push with wrong account

### ISSUE THREAD

**Issue by xernphoton** [desktop/desktop#10520]
### Describe the bug

I have two accounts, this one and another one that is active on my only repository. The thing is: my github desktop is signed in on this account but pushes to github with my other account. Why?

### Version & OS

Version 2.5.4; MacOS Big Sur Beta

### Steps to reproduce the behavior

1. sign into one account
2. sign into another
3. push to repository

### Expected behavior

Push with this account: not my other account.

### Actual behavior

It pushed with another account.

### Screenshots

<img width="1016" alt="Screen Shot 2020-09-07 at 12 52 40 PM" src="https://user-images.githubusercontent.com/70344800/92407655-2ec6c680-f109-11ea-9794-718545c777b7.png">

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by Tabby85** [comment]
You need to fork them together

**Comment by dhunmoon** [comment]
Account information to log in to GitDesktop can be different from the Repo Author. If you want you can change it using the command below.
```
$ git config user.name "Your Name"
$ git config user.email "yourName@domain.com"
```
The above command will set what name and email git should push when pushing future changes.

**Comment by steveward** [comment]
@xernphoton you need to make sure you update the email address in `GitHub Desktop` > `Preferences` > `Git` to point to an email address associated with your currently logged in GitHub account. This will ensure your commits get associated with the correct user. See [this help article](https://docs.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user) for more information. We're also tracking improving this in https://github.com/desktop/desktop/issues/610 if you'd like to follow along for updates.

**Comment by xernphoton** [comment]
thx it worked
