### ISSUE TITLE
Add Side-by-Side View for Changes

### ISSUE THREAD

**Issue by Nexusmeister** [desktop/desktop#10523]
### Describe the feature or problem you’d like to solve

Azure DevOps or Visual Studio let's you review changes side by side instead of an inline view (like in GitHub Desktop).
![image](https://user-images.githubusercontent.com/37147173/92476528-656f1080-f1df-11ea-8635-bea3f6f097a0.png)

### Proposed solution

Users like me who like the side-by-side mode more would benefit from this option. It looks very structured and clear to review changes

### Additional context

Possible Layout
![image](https://user-images.githubusercontent.com/37147173/92476741-bb43b880-f1df-11ea-94d8-27fd3dd210f5.png)

Option Layout
![image](https://user-images.githubusercontent.com/37147173/92477143-5ccb0a00-f1e0-11ea-9401-578612d6d5fd.png)

**Comment by niik** [comment]
Hi @Nexusmeister, thanks for opening this. I'm going to refer you to #172 and ask that you subscribe to it and give it a 👍 When and if we are able to prioritize side-by-side diffs we'll let everyone who's following that issue know.
