### ISSUE TITLE
Discard Changes is emptying contents of the file

### ISSUE THREAD

**Issue by stevensmith-powerschool** [desktop/desktop#10525]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by niik** [comment]
Hi @stevensmith-powerschool. Thanks for opening this!

I suspect this is the same issue as #10469 which was addressed in https://github.com/desktop/desktop/pull/10507. We're hoping to release that fix tomorrow (#10524). If it doesn't appear to you as if the two are related please let us know and we can reopen this issue.

**Comment by niik** [comment]
Hi, just wanted to let you know that we shipped GitHub Desktop v2.5.5 earlier today which we believe fixes this issue. Please make sure you're on the latest version by clicking the `GitHub Desktop` -> `About GitHub Desktop` menu item on macOS or `Help` -> `About GitHub Desktop` on Windows.
