### ISSUE TITLE
Cannot publish new branches

### ISSUE THREAD

**Issue by TodTheSushiMonster** [desktop/desktop#10521]
### Describe the bug

I'm using github desktop with my unity game, and every time I press "Publish Branch" An error pops up saying, 

"  error: cannot spawn .git/hooks/pre-push: No such file or directory
error: waitpid for .git/hooks/pre-push failed: No child processes
error: failed to push some refs to 'https://github.com/Yayness-Games/Defender-Game.git'  "

I can't do it with the github for unity package either.

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.
GitHub Desktop version 2.5.4
I'm running on Windows 10

### Steps to reproduce the behavior

1. Press Publish Branch
2. Error occurs

### Expected behavior

It publishes my branch to github

### Actual behavior

The error pops up

### Screenshots

![Error](https://user-images.githubusercontent.com/69654470/92409755-8dcf1000-f0f6-11ea-859e-aaefea308e2b.png)

### Logs

[2020-09-07.desktop.production.log](https://github.com/desktop/desktop/files/5184337/2020-09-07.desktop.production.log)
These are my logs for the day it started happening

**Comment by tierninho** [comment]
@TodTheSushiMonster thanks for the report. Have you installed [Git for Windows]( https://git-scm.com/download/win) on this machine? If not it's likely that the hook cannot run because Git is not in your PATH. See [this issue comment](https://github.com/desktop/desktop/issues/5036#issuecomment-400947617). Let me know if that gets things working for you.

**Comment by TodTheSushiMonster** [comment]
I haven't installed it, i'll do that now and see if it fixes it.

**Comment by TodTheSushiMonster** [comment]
Hmmm... It still doesn't seem to be working. This is the right app, correct?
![Git GUI](https://user-images.githubusercontent.com/69654470/92515204-15388400-f1c8-11ea-92d3-4c570971dd96.png)

**Comment by tierninho** [comment]
It looks like it is installed. Try opening Git Bash:

> Finally, I found out the reason. After I added "C:\Program Files\Git\bin" to the system environment "path", it works. the git/bin contains the bash which is required by my pre-commit hook.

**Comment by TodTheSushiMonster** [comment]
What exactly should I type in?

**Comment by tierninho** [comment]
Please see instructions [here](https://stackoverflow.com/questions/26620312/git-installing-git-in-path-with-github-client-for-windows). Let us know if you run into any issues.

**Comment by TodTheSushiMonster** [comment]
Hmmm Still doesn't work. I'm pretty sure I did the steps correctly, though I had to use the second person's advice because I didn't have anything in `C:\Users\<user>\AppData\Local\GitHub\PortableGit_<guid>\cmd\git.exe
`
I did however have `C:\Program Files\Git\bin\git.exe
` this path, so I followed his instructions.

**Comment by TodTheSushiMonster** [comment]
I did notice however that I didn't actually have a PATH user variable, so I created one.
![image](https://user-images.githubusercontent.com/69654470/92640436-2057e680-f292-11ea-88b0-7027bf01fb01.png)
This is what it currently contains, is there supposed to be something else there that might have accidently gotten deleted?

**Comment by tierninho** [comment]
@steveward Any chance you see something missing here? Thank you!

**Comment by steveward** [comment]
@TodTheSushiMonster you'll want to add `C:\Program Files\Git\cmd` to the `System Variables` -> `Path` section. That should allow Git to be picked up correctly. You can also rerun the installer and select the option to add it to your PATH during the configuration process.

**Comment by TodTheSushiMonster** [comment]
![image](https://user-images.githubusercontent.com/69654470/92660163-bdc11380-f2ae-11ea-85cc-01f7b238622f.png)
So this?

**Comment by steveward** [comment]
@TodTheSushiMonster can you try deleting the `pre-push` hook in `.git/hooks` to see if that gets things working?

**Comment by TodTheSushiMonster** [comment]
@steveward Where exactly is .git/hooks? Sorry i'm kind of new to navigating github.

**Comment by steveward** [comment]
The `.git` directory will be a hidden directory in the root of your repository. You will need to enable the option to View hidden files/folders in File Explorer. Once you do that you should be able to go into `.git` and find the `hooks` directory where you can delete the `pre-push` file.

**Comment by TodTheSushiMonster** [comment]
Yes it worked! Thank you so much guys!
