### ISSUE TITLE
could desktop offer a file explorer& viewer prefer than notepad&os explorer? 

### ISSUE THREAD

**Issue by Dream2Land** [desktop/desktop#10531]
### Describe the feature or problem you’d like to solve

could desktop offer a file explorer& viewer prefer than notepad&os explorer? 

### Proposed solution

it's more easy view repository files tree and file content,most i think view is more than edit and push. 

### Additional context

git desktop did't need develop viewer self, integration other editer or file viewer may be better

**Comment by steveward** [comment]
Thanks for the feedback @Dream2Land. GitHub Desktop is not intended to be a file browser, although you can easily launch into a file browser or text editor from the `Repository` menu or by using the [shortcuts available](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/keyboard-shortcuts). You can also find the list of supported editors [here](https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md). I hope that helps!
