### ISSUE TITLE
using github desktop to work in team with gitlab repo

### ISSUE THREAD

**Issue by GamesAlchemist** [desktop/desktop#10538]
I have watched a few videos on how to add an ssh key but none go into depth on how it should be used in a team.

I have used the command ssh-keygen via gitbash > then saved the ssh public key to my gitlab account after it was saved to my pc upon generation.

Created a master project and then cloned the project with the ssh clone link via github desktop to my local drive.

then in gitlab created a group and forked the project and added the group to the project.

Added people to the group asked them to then generate a ssh key via gitbash and add there public key to there gitlab ssh keys account.

Then I asked them to clone the project via ssh link via clone URL, github desktop.

They are not able to do this and github desktop keeps throwing an authentication error message.

I’ve tried multiple things like getting them to regenerate the key and saving it to there drive. but still keeps throwing the same error.

They have been able to clone the project via HTTPS link on gitlab to github desktop but I just don’t understand why I can download the SSH link from gitlab via github desktop and to my Hard drive when other team members are not able to do this without it throwing an error. Also it is saying that the key is not being used for that team member which I assume is because they haven’t downloaded via ssh.

Is there something I’m doing wrong with the SSH keys and the team?
should I save there public ssh public keys to my gitlab ssh key account?
or should I send them my public key to save in there gitlab ssh key account?
or is getting both owner and developer, to separately generate the keys then save them in our own public keys, to our own accounts, correct?

Any help would be greatly appreciated. Thanks in advance :)

**Comment by steveward** [comment]
@GamesAlchemist I'd recommend creating a token and using HTTPS to work with GitLab repositories in GitHub Desktop. GitHub Desktop has some edge-cases with SSH if your environment is not set up correctly. See [this guide])https://github.com/desktop/desktop/blob/development/docs/integrations/gitlab.md) for steps about how to get set up using GitLab in GitHub Desktop. Let me know if you have any questions.

You can find some of the SSH issues in https://github.com/desktop/desktop/issues/2579 if you are interested in following along.

**Comment by GamesAlchemist** [comment]
Thanks for the response. For each member of the group of the gitlab repo, do they have to create there own individual token on there gitlab profile and save it. Or will the one token cover everyone or will I have to create a token for each of them? 
Sorry if this is a dumb question just I get the rest but this is not clear to me?

**Comment by steveward** [comment]
@GamesAlchemist each GitLab user will need to create a token for their account.

**Comment by GamesAlchemist** [comment]
@steveward Hi I'm using the latest update of Unity 2020.1.4f1 using version control to share project via gitlab as host for the project and github desktop as the local client. I have ssh keys saved on local Hard drive and Gitlab. I created the access token on gitlab.
After creating the project and cloning via https to local HD using the token password and then creating a project in Unity for the HDRP render pipeline, I have not been able to open the project and get stuck with a blanked out updater for Unity and failed to load window layout pop up, none of the buttons worked other than quit.

I had to reinstall unity hub and unity 2020.1.4f1 create a blank project on another drive which worked. then recreated the project and somehow I was able to open the project. 

I have now gone through the same process with a 2nd team member and he is having the same issue with not being able to load the default layout or revert to factory settings. which is not allowing him to open the project. 
when he cloned the project he did not have to enter the access token or username. Where as I did have to access username and password before cloning. 

I had a 3rd team member go through the process without having the ssh key installed and he did have to enter the key and username and he was able to download it. 

Is this something to do with a conflict with the SSH keys and token, should the second team member have both? (I have made him try it without the ssh key saved to local drive and gitlab and same issue)

Or is this something to do with the cache on github desktop?

**Comment by steveward** [comment]
I'm not sure what the specific project loading issue could be related to (Unity support would be better suited to answer that), but the 2nd team member likely had their GitLab username/password already cached which is why they didn't have to enter it. There isn't any conflict when using SSH or HTTPS -- they're just different protocols you can use.
