### ISSUE TITLE
Paladin Protection light/hand of protector 

### ISSUE THREAD

**Issue by soor66** [desktop/desktop#10530]
Requesting an option bar with hp percentage so you can adjust freely when to use Light/Hand of protector.

**Comment by niik** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!

**Comment by soor66** [comment]
oh ok sorry i posted by mistake
