### ISSUE TITLE
fatal: invalid value for submodule.$name.update

### ISSUE THREAD

**Issue by sgbaird** [desktop/desktop#10545]
### Describe the bug

When trying to clone a repository that contains sobmodules, when submodule.$name.update is set to remote, it reports

`fatal: invalid value for submodule.$name.update`

### Version & OS

Version 2.5.5 on Windows 10, 10.0.19041 Build 19041

### Steps to reproduce the behavior

Create a .gitsubmodules file with the option:
[submodule "$name"]
	path = code/$name
	url = $link
	branch = master
	update = remove

Try to clone the repository using GitHub Desktop

### Expected behavior

I had no issues when running a command line linux clone command: git clone --recurse-submodules $link. I expected the repository to get cloned on GitHub Desktop similarly without issue.

### Actual behavior

A dialogue box with the bug mentioned appears, and the repository fails to clone.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
[2020-09-10.desktop.production.log](https://github.com/desktop/desktop/files/5199608/2020-09-10.desktop.production.log)

### Context
I am doing this for a private repository, if that's relevant.

**Comment by steveward** [comment]
@sgbaird it looks like the `remove` value is not a valid option for the `update` config variable. See [the `update` documentation](https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt-update--init--remote-N--no-fetch--no-recommend-shallow-f--force--checkout--rebase--merge--referenceltrepositorygt--depthltdepthgt--recursive--jobsltngt--no-single-branch--ltpathgt82308203) for more information. Fixing that should hopefully get things working for you. Let me know how that goes.
