### ISSUE TITLE
Special characters and symbols

### ISSUE THREAD

**Issue by romulofpaiva** [desktop/desktop#10547]
### Describe the feature or problem you’d like to solve

Special characters and symbols like ç, ã, ¶, etc. are showed as �.

### Proposed solution

Fix how special characters and symbols are showed.

### Additional context

At line 541 was expected "Local do Arquivo cadastrado no processo de importação inexistente.¶File Location registered in the nonexistent import process.".

![GitHubDesktop](https://user-images.githubusercontent.com/43273354/92749646-af313580-f35c-11ea-96a8-99f5bc65db9c.png)

**Comment by steveward** [comment]
Thanks for the report @romulofpaiva. This looks like the same issue as https://github.com/desktop/desktop/issues/3923, so I am going to close this issue out. You can follow along there for updates about this.
