### ISSUE TITLE
Conflict details

### ISSUE THREAD

**Issue by hadeel-** [desktop/desktop#10549]
### Describe the feature or problem you’d like to solve

I use GitHub for desktop, and in previous versions, when I try to (Pull Origin) in case of conflict --> usually I see conflict files so I know how to handle them, but now after last update, I got msg about conflict but I don't know which files, I have to go to github website and check files changed in last commit to be able to find conflict files

### Proposed solution

keep it as previous versions and mention conflict files

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.
![image](https://user-images.githubusercontent.com/7837795/92754121-39948c00-f393-11ea-98eb-6924519f72e9.png)

**Comment by niik** [comment]
Hi @hadeel-, thanks for opening this! I believe this is the same issue as https://github.com/desktop/desktop/issues/10441 so I'm going to close this in favor of it. If you believe I'm mistaken please let me know and we can reopen this.
