### ISSUE TITLE
Discarding Multiple Files

### ISSUE THREAD

**Issue by pxlpug** [desktop/desktop#10557]
### Describe the feature or problem you’d like to solve

When I discard large amounts (hundreds) of modified files the program sits there while it's processing with no visual feedback. This can last several minutes depending on the files. Sometimes I restart Tower because I don't know if it will actually discard the files or if it's still processing.

### Proposed solution

Show some type of visual to know that it's processing the command.

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by tierninho** [comment]
@pxlpug Thanks for the suggestion. Marking this as an enhancement as it be a nice touch to get some visual cue that the application is working on it.

**Comment by steveward** [comment]
@pxlpug you mentioned Tower in your description -- just to confirm is this an issue in GitHub Desktop or in the Tower Git client?

**Comment by pxlpug** [comment]
Oh shoot, my bad. Wrong place.
