### ISSUE TITLE
Feature request: ability to save bookmarks for different branches of the same repo

### ISSUE THREAD

**Issue by massimo-cassandro** [desktop/desktop#10569]
### Describe the feature or problem you’d like to solve
Sometimes I need to mantain on my computer both the master branch and a developing one. GitHub Desktop doesn't allow to bookmark the same repo twice, and I have to check the active branch each time, so it's pretty easy to make a mistake

### Proposed solution
Ability to add the same repository bookmark more times, changing its bookmark name and specifing the related branch ([Sourcetree](https://www.sourcetreeapp.com/) has this ability).
This way, it would be possible to bookmark each branch making it easier to manage them

### Additional context
In addition, the ability to show the active branch in the repo would be very useful

**Comment by tierninho** [comment]
@massimo-cassandro Thank you for the suggestion. 

> GitHub Desktop doesn't allow to bookmark the same repo twice

If I understood correctly, there is actually is a workaround for this. You can put the same repo in two different places within your directory structure. For example one repo on the desktop and a copy of the same repo in some folder. Both repos can co-exist on Desktop and be on different branches. However, you'll have to keep them in sync and hover over the name in the repo list to see which is which. Is this kind of what you intended (outside of creating an actual setting)?

As for showing the branch name in the repo list, we have an issue for that here: #8158

**Comment by massimo-cassandro** [comment]
Hi @tierninho,
Thank you for your answer.
The alternative solution you describe would certainly be sufficient, except for not being able to immediately understand, from the name that appears in the list, which branch it is, but showing the branch name in the repo list would solve the issue.
But if I try to clone, via Desktop, a repository already present in its repositories list, nothing happens. Desktop seems to understand that the repository is already in its lists and avoids cloning it again.
Perhaps I should clone the repository from the command line and then import it into Desktop?

Thanks for your attention

**Comment by tierninho** [comment]
> But if I try to clone, via Desktop, a repository already present in its repositories list, nothing happens. 

Did you attempt to clone it into a different folder? 

> Perhaps I should clone the repository from the command line and then import it into Desktop?

Alternatively, yes you could go this route. Let us know know how it goes.

**Comment by steveward** [comment]
@massimo-cassandro as we have not heard back from you I am going to close this issue out. Let me know if you ran into any issues getting this set up and we can assist further.
