### ISSUE TITLE
Show directory paths for repository listing

### ISSUE THREAD

**Issue by danielh-official** [desktop/desktop#10562]
This setting would be two-fold:

- An option that can be enabled to show it under the repository name. 
- A tooltip that shows up when the user hovers over the repository.

This feature will improve the accessibility for users that have repositories all over their computer. With the current build (Windows 10), users have to select the "Repository" in the top menu and click "Show in Explorer" to find out where their repositories are located. This feature would shorten that process.

**Comment by steveward** [comment]
@danielh-official thanks for the feedback. You can hover over the repository name to view the full directory path of the repository. This request sounds similar to #8175 and #8175, both which were included in #6460. See #8158 (comment) specifically for the current thinking on this. I'm going to close this issue out -- thanks for using GitHub Desktop.

**Comment by danielh-official** [comment]
My bad. I should've waited longer.
