### ISSUE TITLE
sign in problem in githubdesktop

### ISSUE THREAD

**Issue by SujalGupta244** [desktop/desktop#10565]
### Describe the feature or problem you’d like to solve

I had sign in githubdesktop with an email id, but i have deleted that github account  (sujal725 ) but githubdesktop is not showing to singin again with different email id which is causing a problem to not letting me to clone my github repository files from different github account. 

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@SujalGupta244 if you need to sign in to a different account you can do so by going to the menu > `File` > `Options` > `Accounts`. I hope that helps!

**Comment by AlemuTeshome** [comment]
For the time being, I don't want to use the desktop app of GitHub.

**Comment by SujalGupta244** [comment]
Thank you very much for your help . It's a great help from your side. Thank
you again.
