### ISSUE TITLE
github repository can't be deleted

### ISSUE THREAD

**Issue by han00119** [desktop/desktop#10568]
I'm very new to this subject and am sorry if this is a very easy problem to solve.

I made a repository on Github by commiting then import into version control->share project on github. I realised I made a mistake then deleted the project on github, but even after this I cannot use the name of the repository I deleted and I says the name already exists, however, I need to use said name for one of my projects in school.

Please Help

**Comment by steveward** [comment]
@han00119 thanks for the report. Is GitHub Desktop showing this error, or are you seeing this issue when attempting to create the repository on github.com?

**Comment by AlemuTeshome** [comment]
no coment

**Comment by steveward** [comment]
I'm going to close this out @han00119 -- let us know if you are still having issues.
