### ISSUE TITLE
Add support for AVIF image preview

### ISSUE THREAD

**Issue by laukstein** [desktop/desktop#10577]
AVIF is now supported in Chrome 85 and soon in any other browsers, except discontinued browsers like IE and Edge legacy.
Support status in https://caniuse.com/avif

**Comment by steveward** [comment]
Thanks for opening this @laukstein. I'm going to throw the `help-wanted` label on this issue -- hopefully someone from the community can tackle this in the future.

**Comment by brendonbarreto** [comment]
Can I give it a try?

**Comment by brendonbarreto** [comment]
Oh, now that I see that the version of chrome that electron is using is 83 🤦🏻‍♂️

**Comment by OregonSells** [comment]
@help-wanted

**Comment by filiptronicek** [comment]
It's now Chrome 87 👀 @brendonbarreto
