### ISSUE TITLE
error: RPC failed; curl 18 transfer closed with outstanding read data remaining fatal: the remote end hung up unexpectedly

### ISSUE THREAD

**Issue by formatc2013** [desktop/desktop#10573]
### Describe the feature or problem you’d like to solve
Trying to publish a project that uses git lfs

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Please see cmd:

```
Nemesis03@Janek MINGW64 /g/UE4EngineBuilds/DQSWankOMate-Backup (master)
$ git repack --max-pack-size=100M -a -d
Enumerating objects: 4354, done.
Counting objects: 100% (4354/4354), done.
Delta compression using up to 12 threads
Compressing objects: 100% (4276/4276), done.
Writing objects: 100% (4354/4354), done.
Total 4354 (delta 208), reused 0 (delta 0), pack-reused 0
Removing duplicate objects: 100% (256/256), done.


Nemesis03@Janek MINGW64 /g/UE4EngineBuilds/DQSWankOMate-Backup (master)
$ git push origin master
Uploading LFS objects: 100% (1786/1786), 4.7 GB | 0 B/s, done.
Enumerating objects: 4354, done.
Counting objects: 100% (4354/4354), done.
Delta compression using up to 12 threads
Compressing objects: 100% (4068/4068), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
Writing objects: 100% (4354/4354), 4.00 GiB | 6.10 MiB/s, done.
Total 4354 (delta 263), reused 4299 (delta 208), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date
```

I get similar errors whet I try to push from GItHubDesktop.

Just upgraded my git lfs storage space to 50GBs/$5 pack.

I can see some of the git lfs files are up because in the morning it was only 5 GBs now its 15.

I tried several times, to no avail.

**Comment by formatc2013** [comment]
@steveward Thanks for the quick reply!

I copypasted the last commit sha and put it into the equation above :(

Results:

```
Nemesis03@Janek MINGW64 /g/somepath/myproject (master)
$ git push origin buchofnumbers2a7dfa56d91ed7e2a777b5c80fdb16abe915:master
error: The destination you provided is not a full refname (i.e.,
starting with "refs/"). We tried to guess what you meant by:

- Looking for a ref that matches 'master' on the remote side.
- Checking if the <src> being pushed (buchofnumbers2a7dfa56d91ed7e2a777b5c80fdb16abe915')
  is a ref in "refs/{heads,tags}/". If so we add a corresponding
  refs/{heads,tags}/ prefix on the remote side.

Neither worked, so we gave up. You must fully qualify the ref.
hint: The <src> part of the refspec is a commit object.
hint: Did you mean to create a new branch by pushing to
hint: 'buchofnumbers2a7dfa56d91ed7e2a777b5c80fdb16abe915:refs/heads/master'?
error: failed to push some refs to 'https://github.com/formatc2013/myproject.git'
```

**Comment by steveward** [comment]
@formatc2013 can you confirm you have a `master` branch? What does the output of `git branch -a` show?

**Comment by formatc2013** [comment]
@steveward  Double checked, it does!

**Comment by formatc2013** [comment]
@steveward 
Just wondering if you have any more trick or tips I could try...

**Comment by steveward** [comment]
Try `git push <remotename> <commit SHA>:refs/heads/<branch>` -- it looks like it requires the full refname.

**Comment by formatc2013** [comment]
```
$  git push origin bunchofnums2fc40a8da2dedf:refs/heads/master
Uploading LFS objects: 100% (1961/1961), 5.0 GB | 1.1 MB/s, done.
Enumerating objects: 5022, done.
Counting objects: 100% (5022/5022), done.
Delta compression using up to 12 threads
Compressing objects: 100% (4727/4727), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
Writing objects: 100% (5022/5022), 4.00 GiB | 6.20 MiB/s, done.
Total 5022 (delta 641), reused 4264 (delta 208), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date
```


Fails with this...

**Comment by formatc2013** [comment]
Not sure why this issue is closed, is still persists!

**Comment by steveward** [comment]
@formatc2013 apologies for not getting back to you. It looks like you are still trying to push over 4GB which is why the push is still failing -- is it possible that a specific has a large total file size?

**Comment by kifayatullahkhan** [comment]
A push request  is causing the following error:
Enumerating objects: 306, done.
Counting objects: 100% (306/306), done.
Delta compression using up to 4 threads
Compressing objects: 100% (300/300), done.
error: RPC failed; curl 55 Send failure: Connection was aborted
fatal: the remote end hung up unexpectedly9.00 KiB/s 
Writing objects: 100% (306/306), 5.53 MiB | 111.00 KiB/s, done.
Total 306 (delta 213), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

**Comment by protawk** [comment]
Ok

**Comment by formatc2013** [comment]
you mind taking a look at this?

https://github.com/desktop/desktop/issues/11722

protawk <notifications@github.com> ezt írta (időpont: 2021. jan. 20., Sze,
8:22):

**Comment by AlizerUncaged** [comment]
This has been an ongoing problem with git and the developers are never interested on fixing this
