### ISSUE TITLE
UX BUG: GitHub Client Default Path Is Under User Document - VERY BAD LOCATION 

### ISSUE THREAD

**Issue by CreepyGnome** [desktop/desktop#10572]
### Describe the bug

USER EXPERIENCE BUG

Currently, the default path root for cloning is the users Documents path. This is a horrible default to put SOURCE CODE. Source code is not documents.  Many people have their document folder backed up/sync'd with any one of a dozen services.

Doing this triggers bad things and lots of file getting sync'd to services the user probably doesn't want them to go to.  Stopping this after the fact is a pain in the arse, and the user now has to go clean up a lot of crap.

This could easily be resolved by the client ASKING THE USER ON FIRST CLONE where they would like the root folder for all future clones to go. 

Also then providing a SETTING in the SETTING area to change the default after the fact, and not have to remember to do it during the act of cloning, which is how a user can get in trouble in the first place.

Not all users on their first launch of the GitHub client is familiar with the tool, and where to look for making changes, and when they want to clone a repo quick, they may TRUST GITHUB to make a responsible choice for the location.  Therefore if GitHub cannot be trusted with this, they should not pick one and aks the user on the first clone.

### Expected behavior

On the first clone after installing ask the user directly, and in a modal dialog, where they want the root for all future cloning operations to be.

### Actual behavior

Doesn't ask, and it is all too easy to not notice the path and not change it on the first clone.

**Comment by tierninho** [comment]
@CreepyGnome Thank you for the issue and apologies for any frustrations this may have caused. 

Currently, there is no setting for this as Desktop remembers the last directory you cloned a repo to. The only thing that is needed is to clone a repo and the next time, it will default to that location. The first clone will still default to Documents, however.

Despite the current method, we may still decide to make a dedicated setting to address this as you are not the first to ask. However, we are a small team that needs to weigh all issues/features to determine our roadmap. 

This issue, or one of the prior issues for the same, will be reopened when the time comes. Thank you for using Desktop.

**Comment by CreepyGnome** [comment]
I understand clearly how it works, and that is the issue. This is a user experience issue, that could cause a person to run out space in OneDrive, DropBox, or other service because you choose to use a users document folder for source code. Source code that includes large assests if you are using something like Unity or other game dev kits. 

It seems odd to close and ignore something that could cause devistating issues for a user. But okay small team and all so I guess that next feature that allows some cool animation is more important. Gotch!

**Comment by az6667** [comment]
#5377 #4626 #2889
What/who keeps closing this same issue over-and-over again?

If y'all aren't going to add the basic option instead of "last-clone-location", just _let us know_.
I'll fork and Do It My Self (TM)

**Comment by yasinkavakli** [comment]
Just installed Github Desktop to check it out if it can replace git-fork for me, haven't found an option to change this setting (changing the location in the clone window says folder isn't empty, yes, it has all my repos in it) and deleted Github Desktop. Will try that in a year again to see if Github was able to put the most basic and simple option into their Git client.
See you all next year!
