### ISSUE TITLE
How to add file thing with no file type to .gitattributes (or can I just delete it)

### ISSUE THREAD

**Issue by HowTheHellDoIdoThis** [desktop/desktop#10584]
So I'm using GitHub desktop for a Unity game, and after throwing myself down the incomprehensibly vast and probably non-euclidean rabbit hole of how the hell LFS is supposed to work, someone told me I had to do something with my .gitattributes file. Not knowing what this meant, i just copy-pasted the already existing lines and replaced the file extension names (probably not what I was supposed to do but I didn't have much to go off of) with things like ".png" or ".fbx". As i thought that the file over the 100mb limit was a texture or model or something, as I tend to bake pretty large textures. But after adding many many filetypes to the list, nothing worked. So I decided to quit being a dumbass and find the problem file itself, discovering that the models and textures I _thought_ were causing problems were well within the limit. So imagine my surprise when I find out that the problem file is in fact, this thing:
![image](https://user-images.githubusercontent.com/41463398/93282286-e780ab80-f782-11ea-9e33-cc9e781bb77c.png)
What the hell is that? What do I do with it? There is literally no file type. Is it important? Can I just delete it? This thing has been causing me trouble for the past month or two at least, and I have absolutely no clue what this could possibly be. Also file explorer won't let me search for things over just 100mb, so even more problem files just like this could be hiding within the 1-128 mb range.

I have so many questions, and I've come here for answers.
Please help.

(Also if I was doing the gitattributes thing wrong please tell me)

**Comment by steveward** [comment]
It looks like that is a directory for temporary files. Check out [this reply from Unity](https://support.unity3d.com/hc/en-us/articles/205215493-Is-the-Library-Folder-required-in-the-repository-?_ga=2.184284838.141354617.1600268279-1535738377.1600268279) for some more information. I'd recommend adding this [Unity .gitignore](https://github.com/github/gitignore/blob/master/Unity.gitignore) to ensure you ignore the correct files in your project.

Unfortunately deleting that file from your repository will not delete it from the repository's history, so it will need to be removed using a tool like [BFG repo cleaner](https://rtyley.github.io/bfg-repo-cleaner/). See [this guide](https://docs.github.com/en/github/managing-large-files/removing-files-from-a-repositorys-history) as well. If you have any questions about how to do that let me know.
