### ISSUE TITLE
Not responding, can't close, can't kill, have to restart computer

### ISSUE THREAD

**Issue by sgbaird** [desktop/desktop#10583]
### Describe the bug

GitHub Desktop stops responding, and can't be closed or killed through normal means. I end up having to restart my computer to relaunch GitHub Desktop. This has happened several times to me in the last day or two.

### Version & OS

GitHub Desktop 2.5.5, Windows 10 Home 2004, 19041.508

### Steps to reproduce the behavior

Unfortunately I haven't been able to reproduce this behavior, it's just happened several times seemingly "randomly".

### Expected behavior

If it stops responding, at least for task manager to be able to kill the process.

### Actual behavior

I get a blank white screen for the GitHub Desktop app. Clicking anywhere in the white space (No X arrow) I get "not responding, are you sure you wish to close? end now", but this button does nothing. If I hover over the taskbar icon and click the "X", it doesn't close it. I can't relaunch GitHub desktop either by opening up a new instance. The only way I've figured out how to solve this problem is by restarting my computer.

### Logs

This is the log from before I relaunched GitHub.
[2020-09-14.desktop.production.log](https://github.com/desktop/desktop/files/5228576/2020-09-14.desktop.production.log)

This is the most recent log from when I relaunched GitHub. Not sure if it will be useful.
[2020-09-15.desktop.production.log](https://github.com/desktop/desktop/files/5228566/2020-09-15.desktop.production.log)

### Additional context

I have a Dell G7 laptop if that matters.

**Comment by tierninho** [comment]
@sgbaird Thank you for the report. If that's the most recent log file there's really not a lot to go on here I'm afraid. I would try a complete reinstall by means of

1. Quitting GitHub Desktop and restarting your machine to ensure no rogue processes are hanging about
1. Uninstalling GitHub Desktop
1. Deleting the `C:\Users<YourUserName>\AppData\Roaming\GitHub Desktop` folder
1. Downloading and installing GitHub Desktop again from https://desktop.github.com

If that doesn't work I'd try disabling hardware acceleration as a final last-ditch effort by setting the `GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION` environment variable to `1` by running `set GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1` in `cmd.exe` and restarting your machine.

**Comment by Splatterxl** [comment]
This happened to me too. If you find the `renderer.js` file and the
```js
module.exports = function (e) {
```
is just
```js
module.exports = functi on () {
```
then you should change the `function` back.

I'm sorry if I'm completely off the mark here.

**Comment by tierninho** [comment]
As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by sgbaird** [comment]
Sorry about that, yeah for some reason it hasn't happened again. I'm planning on trying out those instructions if it does happen again. Thank you for the help.

**Comment by sgbaird** [comment]
It happened again, so I restarted my machine, deleted the folder, and reinstalled per the directions. We'll see how it goes

**Comment by jonfroehlich** [comment]
This is also happening to me on Win10.

![image](https://user-images.githubusercontent.com/1621749/96046865-06796880-0e29-11eb-9552-d2c33411a2ce.png)

**Comment by sgbaird** [comment]
> It happened again, so I restarted my machine, deleted the folder, and reinstalled per the directions. We'll see how it goes

Hasn't happened since following the instructions.
