### ISSUE TITLE
add way to easily push repository

### ISSUE THREAD

**Issue by godalming123** [desktop/desktop#10582]
add way to easily push repository

I propose to fix this you either add a always on top option where the window is small or a button that appears when i hover over the icon to commit and push my repository
How will it benefit Desktop and its users?

![Screenshot 2020-09-15 165821](https://user-images.githubusercontent.com/68993177/93235015-eba5cc80-f774-11ea-8fb1-47bb29eba171.jpg)

**Comment by steveward** [comment]
@godalming123 thanks for contributing. Is your feature request for GitHub Desktop or a different application? GitHub Desktop has a button that allows you to push your commits to your remote repository -- `Push origin`. You can also use the`Command/Control+P` I'm going to close this issue out but let me know if I am misunderstanding your request.
