### ISSUE TITLE
Github Desktop Not Recognizing Private Organization

### ISSUE THREAD

**Issue by rdblake21** [desktop/desktop#10591]
### Github Desktop Not Recognizing Private Organization

I'm using GitHub Desktop and trying to connect a repository that's a apart of an Organization that's Private and has Single Sign-on Enabled for access.  I'm not able to enter my username and password where I'm thinking the issue is with the SIngle Sign-On or the Private Organization i'm trying to associate to.

### Version & OS

Version 2.5.2
OS - Windows 10 Version 1703

### Steps to reproduce the behavior

1. Go to Add in Select Repository
2. Click on Clone Repository (which has already been forked to me repository)
3. Click on GitHub.com, the forked repository does not show /UST-Milestones-PM
4. Go to URL and enter https://github.com/rdblake21/UST-Milestone-PM and a new folder path.
5. At this point it says the Authenication has failed and to enter Username and password
6. Github Username and Password are entered and Authentication keeps failing.

### Expected behavior

I would expect to have the repository cloned, similar to my other repository

### Actual behavior

No cloning happens and it is not viewable in Github Desktop

### Screenshots

![image](https://user-images.githubusercontent.com/60475518/93471989-af2fb900-f8b9-11ea-8f65-55a0eab217a5.png)
![image](https://user-images.githubusercontent.com/60475518/93472043-c53d7980-f8b9-11ea-8718-aabc60bfb3e7.png)

**Comment by steveward** [comment]
@rdblake21 you likely need to request approval for GitHub Desktop from your organization. See this guide:

https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/requesting-organization-approval-for-oauth-apps

I'm going to close this out, but let me know if you run into any issues after doing that.

**Comment by rdblake21** [comment]
Thank you!
