### ISSUE TITLE
Adjust Desktop to screen size on Mac when clicking at the top of window

### ISSUE THREAD

**Issue by ilmari-aalto** [desktop/desktop#10594]
### Describe the feature or problem you’d like to solve

On Mac the Github Desktop app doesn't auto-adjust to screen size when double-clicking at the top of the window. Many other apps do so it should be straight-forward to implement. (With top of the window I mean the topmost part of the window which you can use to move the window. It's where you also have close window/minimize window/full screen options.)

### Proposed solution

When double-clicking at the top of Github Desktop window it will auto-adjust to the screen size on which it's open. (Not the full-screen mode, but rather the maximum possible size that doesn't hide OS top menu or Dock.) This is especially helpful if you have more than one window which are of different sizes, or use your laptop sometimes with external monitors, sometimes without.

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by niik** [comment]
Hi @ilmari-aalto, thanks for opening this.

What version of Desktop and what version of macOS are you running? Double clicking on the top-most part of the Windows should already maximize the application, see this example from my machine

![2020-09-17 17-18-56 2020-09-17 17_21_17](https://user-images.githubusercontent.com/634063/93491669-445a9e00-f90a-11ea-9f7f-d6dbe7582ecd.gif)

**Comment by ilmari-aalto** [comment]
Hi @niik , thanks for a super quick answer!

I'm on 10.15.5 (19F101) MacOS, and GitHub Desktop version 2.5.5

After seeing your message I tested on the laptop screen with and without external screens connected, light and dark mode, but wasn't able to make the auto-size happen. So at least on my machine it doesn't (and never did) work for some reason.

**Comment by niik** [comment]
@ilmari-aalto Could  you open the developer tools window (View menu -> Toggle Developer Tools), select the Console tab and paste the following snippet so that we can take a look at what macOS thinks your preference is:

`require('electron').remote.systemPreferences.getUserDefault('AppleActionOnDoubleClick', 'string')`

Should look something like this:

![image](https://user-images.githubusercontent.com/634063/94268855-0ed33780-ff3e-11ea-963f-3855b8ad69c4.png)

Can you also verify that the `Double-click a window's title bar to` item in the Dock system preferences is checked and that the dropdown is set to `zoom`?

![image](https://user-images.githubusercontent.com/634063/94268798-fbc06780-ff3d-11ea-9cc8-27bebcdf592e.png)

**Comment by ilmari-aalto** [comment]
Hi @niik ,

Thanks for the detailed instructions!

My Dock setting "Double-click a window's title bar to" was enabled and set to `zoom`.

The output for the console command in GitHub Desktop was an empty string:
```
> require('electron').remote.systemPreferences.getUserDefault('AppleActionOnDoubleClick', 'string')
< ""
```

**Comment by niik** [comment]
> The output for the console command in GitHub Desktop was an empty string:

Interesting, so that's definitely the culprit behind Desktop not doing what you'd expect. If  you change the system preference from `zoom` to minimize and then run the same command in DevTools again what do you get?

**Comment by ilmari-aalto** [comment]
Thanks for your help @niik !

Fortunately (or unfortunately as we can't get to the bottom of the issue!) my Github Desktop just auto-upgraded to 2.5.6 and my iOS also auto-upgraded to 10.15.6 (19G2021) and the window maximization now works! 

The output for the previous debugging command is now also as expected:
```
> require('electron').remote.systemPreferences.getUserDefault('AppleActionOnDoubleClick', 'string')
< "Maximize"
```
