### ISSUE TITLE
Deleted branch appears under "Recent branches"

### ISSUE THREAD

**Issue by valentinoPereira** [desktop/desktop#10597]
1. Use a branch
2. Delete it
3. Github desktop automatically switches me to master
4. Click on current branch dropdown and you will see the deleted branch under the "Recent branches" header

Github desktop Version 2.5.5

**Comment by tierninho** [comment]
@valentinoPereira Thank you for the issue. If you delete a branch locally, Step 4 should still occur, but the branch should appear under `Other Branches` as `origin/[my-branch]`. 

![Screen Shot 2020-09-18 at 7 50 34 AM](https://user-images.githubusercontent.com/14828183/93629243-a73c4b80-f983-11ea-8786-02649c012f91.png)

When you delete the branch and select the option to delete in on the `remote` as well, then the branch should be removed altogether.

Were you expecting the branch to be removed completely, or for it to fall under the `Other Branches` section? Did you select the `remove from remote ` option?

**Comment by tierninho** [comment]
As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
