### ISSUE TITLE
Show branch name in repo list?

### ISSUE THREAD

**Issue by dledge** [desktop/desktop#10595]
### Describe the feature or problem you’d like to solve

I may be working on a few different branches at the same time within a given repo. I'll typically have these cloned in different folders locally.

When I look at my list of cloned/selected repos in the desktop app, they are listed with just the repo name. I need to click though each one to determine which branch these are on.

### Proposed solution

It would be nice to be able to give the repos a local nickname or display the current branch name after the repo name so when a repo is cloned multiple times, it's easy to see which one is which.

**Comment by steveward** [comment]
Thanks for the request @dledge. I'm going to close this in favor of https://github.com/desktop/desktop/issues/7856 where we are tracking the option to rename repositories. Thanks for using GitHub Desktop!
