### ISSUE TITLE
disable refreshing some API information when not signed in

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#1060]
We should review the refresh code to better handle a private GitHub repository (or any Enterprise repository) when the user is not signed in. Most of the endpoints should return a 403, which seems like we're doing unnecessary work.

**Comment by niik** [comment]
Gonna close this. If we experience it being a problem we can revisit but it hasn't been thus far and it's tricky to know whether a repository can't be reached by an anonymous user or not. Even Enterprise repositories can be public public (even if it's unusual) and private repositories could have been made public.
