### ISSUE TITLE
User Control Setings

### ISSUE THREAD

**Issue by rorycambra** [desktop/desktop#10615]
I have a user settings control issue.

I signed up for GitHub to explore and possibly enjoy solving problems and making life more efficient.  I have never used GitHub until today.  I believe I logged in and got my username and password and stopped right before watching the tutorial.  

Fast forward to Sunday.  Somehow all of my user rights as and Rory-Admin got was no longer available and someone else created a group with other users that Rory-Admin gave them to have more control than Rory-Admin does. Example:

![Github](https://user-images.githubusercontent.com/65514607/93825673-99542800-fc1a-11ea-99ea-c2da7675b03e.JPG)

I simply am cut off from my parts of my C drive for programs and my E drive which is for data.

![Github Network Creditials](https://user-images.githubusercontent.com/65514607/93826761-ca355c80-fc1c-11ea-9e69-25124142d9f2.JPG)

When I open up each tab,  I seems like all hell has broken loose.

![Github Network Creditials 2](https://user-images.githubusercontent.com/65514607/93826825-eb964880-fc1c-11ea-934b-95c856076efd.JPG)

So as you can see, something happened.  Now I don't know how this happened? But I do need to access my stuff and get back to normal.

I have a Dell Desktop computer with Window 10 Pro.

![Dell Computer](https://user-images.githubusercontent.com/65514607/93827812-f225bf80-fc1e-11ea-9351-366ddb9faaed.JPG)

I am using GitHub Version 2.5.5

### Steps to reproduce the behavior

1. Go to '...' Desktop
2. Click on '....' Click on the folders tab
3. Scroll down to '....' I will take you to quick access
4. click on documents tab

![Document Error](https://user-images.githubusercontent.com/65514607/93828266-c9ea9080-fc1f-11ea-8f3a-5987ffc61bc4.JPG)

Can't access even though I am the Admin. I also found some configuration files.

![Github2](https://user-images.githubusercontent.com/65514607/93828363-00c0a680-fc20-11ea-8f38-1b09a7e81ddd.JPG)

No logs that I know of.

I cannot access the internet using chrome only.

**Comment by tierninho** [comment]
@rorycambra  user-name thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by rorycambra** [comment]
Will do.


*Rory Cambra - rlcambra@gmail.com <rlcambra@gmail.com>*
760-505-4800

**Comment by rorycambra** [comment]
Done.


*Rory Cambra - rlcambra@gmail.com <rlcambra@gmail.com>*
760-505-4800

**Comment by tierninho** [comment]
@rorycambra That looks quite frustrating!

It looks like your permissions or access rights are preventing you from making any Windows-related changes. Also, antivirus software could be blocking you. 

The Desktop folder you highlighted in the first pic does not appear to be `GitHub Desktop` application. If you go to the Windows search bar and type in `Desktop` to open the application, does it open and run ok?

**Comment by rorycambra** [comment]
Yes I'm getting hammered.  When I type in Desktop the Github desktop appears at the default. Then it takes me to my Github desktop.

**Comment by tierninho** [comment]
Glad GitHub Desktop is opening fine. 

When you get past the permissions issues, please let us know if GitHub Desktop gives you any problems. Until then, going to close this issue as it does not appear to be related to GitHub Desktop.

**Comment by rorycambra** [comment]
> Glad GitHub Desktop is opening fine.
> 
> When you get past the permissions issues, please let us know if GitHub Desktop gives you any problems. Until then, going to close this issue as it does not appear to be related to GitHub Desktop.

Why are we clolsing this as it's stil an issue that utilized GiHub Desktop?

**Comment by tierninho** [comment]
Do not mean to be dismissive, but I do not see the correlation of the your issue and GitHub Desktop. (Note, the Desktop folder on your computer is not related to GitHub Desktop the application.)

Please feel free to let me know if I have missed something and we will be happy to help.

If you need general GitHub support, please reach out to the team here: https://support.github.com/contact

**Comment by rorycambra** [comment]
That's okay.  I uninstalled the desktop just in case.  Can I still use my
username and password when I come back?


*Rory Cambra - rlcambra@gmail.com <rlcambra@gmail.com>*
760-505-4800

**Comment by tierninho** [comment]
> Can I still use my username and password when I come back?

Yes, absolutely!
