### ISSUE TITLE
How to change text editor

### ISSUE THREAD

**Issue by guitejes000** [desktop/desktop#10611]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by niik** [comment]
Hey @guitejes000, you can choose among a list of [supported editors](https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md#windows) in the Integrations tab of Options (on Windows) or Preferences (macOS):

![image](https://user-images.githubusercontent.com/634063/93775641-f8b63600-fc22-11ea-8042-097988959b1d.png)

Hope that helps!
