### ISSUE TITLE
stash界面未更新导致代码丢失

### ISSUE THREAD

**Issue by qiangwushuang** [desktop/desktop#10610]
### Describe the bug

当stash时，若某个文件处于占用状态，虽然stash成功了，但是界面没有任何更新。会让人误以为没有stash成功，若此时再次stash也没有会覆盖已有stash的提示，二次stash后只有被占用文件被暂存，之前的内容被清理掉（没有正常二次stash的提示）。

### Version & OS

windows10

### Steps to reproduce the behavior

1. 打开一个excel文件。
2. 进行stash
3. 再次进行stash

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by niik** [comment]
Automatic translation by Google Translate 👇 

> # The stash interface is not updated and the code is lost
> When stash, if a certain file is in the occupied state, although the stash is successful, the interface is not updated. People will mistakenly think that there is no stash success. If stash again does not overwrite the existing stash at this time, only the occupied files are temporarily stored after the second stash, and the previous content is cleaned up (there is no prompt for the normal second stash ).

**Comment by niik** [comment]
@qiangwushuang 嗨，谢谢你打开这个问题。 您能提供一些截图来显示问题吗？

Automatic translation by Google Translate of 👇

Hi and thanks for opening this issue. Would you be able to provide some screenshots to show the problem?

**Comment by qiangwushuang** [comment]
![1](https://user-images.githubusercontent.com/6835840/93790865-1789ec00-fc66-11ea-89c7-4c0ce6e789e2.gif)
![2](https://user-images.githubusercontent.com/6835840/93790998-3d16f580-fc66-11ea-93b8-eba6559df43b.gif)

**Comment by niik** [comment]
非常感谢您提供的屏幕截图。 抱歉，我无法在计算机上重现此内容。 您正在运行哪个版本的GitHub Desktop？ 您可以提供日志文件吗？ 请打开Help菜单并选择Show Logs...附加您的日志。

> Thank you so much for the screenshots. I'm sorry but I am not able to reproduce this on my machine. What version of GitHub Desktop are you running? Would you be able to provide a log file? Please attach your logs by opening the Help menu and selecting Show Logs...

**Comment by niik** [comment]
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.
