### ISSUE TITLE
GitHub Desktop is ignoring Options > Git settings on Windows

### ISSUE THREAD

**Issue by ocdtrekkie** [desktop/desktop#10613]
### Describe the bug
@niik and @steveward I think there is a new bug that may have led to the opening of #10608, #10520, #10508, etc.

I noticed after updating GitHub desktop that, if I commit on this machine, it appears that it would use the email address associated with my Windows-logged-in domain or Microsoft account *not* any email address listed in my GitHub profile *or* the Git tab on Options.

Right now, the Git tab in Options shows the email address I want to use for Git commits, but on the main window, left of where you'd enter the summary of a new commit, it shows a randomly-generated avatar, and when highlighting over it, you get my Windows domain account address... again, instead of anything in my GitHub Desktop settings. The address shown there isn't on my GitHub account, and has never been used with any Git repo in the history of ever.

GitHub Desktop appears to be *ignoring* the Options settings entirely in favor of pulling from my Windows login for some reason. Changing the email address in Options > Git does nothing to fix this.

### Version & OS

Version 2.5.5 on Windows 10

**Comment by ocdtrekkie** [comment]
In true mystery fashion... on a reload, it has returned to normal behavior. And nothing in the logs seems to suggest it ever did anything but found my GitHub credentials. I have no idea where or how GitHub Desktop pulled in the email address attached to my Windows domain account, because that was never associated with GitHub Desktop, Options > Git, or any Git repo in any way.

**Comment by tierninho** [comment]
@ocdtrekkie Thank you for the report. If it happens again or you spot a clue, please let us know. Glad it resolved itself safely!

If I can reproduce this, I will reopen and investigate further.
