### ISSUE TITLE
husky commit-msg hook failed

### ISSUE THREAD

**Issue by akash-bhoite** [desktop/desktop#10618]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by akash-bhoite** [comment]
when i commit the code at that git gives me this error -> husky commit-msg hook failed

**Comment by niik** [comment]
Hi @akash-bhoite,

I'm afraid we can't offer support with debugging individual Git hook setups, but it seems that the project you're trying to contribute to is using the [husky](https://github.com/typicode/husky) project to enforce a certain format for their commit messages. I would consult the project's `package.json` file and look for the `commit-msg` property to see if you can find any clues as to why you commit message got rejected.
