### ISSUE TITLE
Automatically creating branch Feature/ 

### ISSUE THREAD

**Issue by valentinoPereira** [desktop/desktop#10621]
I have my existing branch name format as "feature/<whatever_feature>" 

But since last 2 months github desktop is automatically creating new branches with the same name with a capital "F" thus I now have "Feature/<whatever>" .. And my fetch is giving errors due to same branch names..

Fix this asap please it is discouraging us to use github desktop and making us go back to terminal.

![image](https://user-images.githubusercontent.com/21219324/93899069-8f612080-fd11-11ea-88a5-6a11338f9c20.png)

Version 2.5.5

**Comment by niik** [comment]
Hi @valentinoPereira, thanks for opening this.

To be clear, GitHub Desktop doesn't change the capitalization of branch names. Without knowing the specifics of your environment I suspect what's happened here is that you're on an operating system that uses a case-insensitive but case-preserving file system. When you create a branch in Git using slashes (`/`) to separate components like in your example Git will create the corresponding file system hierarchy in the `.git/refs` directory.

So when you create a branch called `feature/foo/bar` Git will create a directory in the `.git/refs/heads` folder called `feature` and within that another directory called `foo` and within that directory a file named `bar`.

When using case-insensitive but case-preserving file systems (such as NTFS) both `.git/refs/heads/feature` and `.git/refs/heads/Feature` can be used to refer to the same folder.

So I suspect what's happened here is that at some point (likely around 2 months ago) there you didn't have any checked out branches starting with `feature/` and either checked out someone else's branch that started with `Feature/` or created your own. Until all branches starting with `feature/` or `Feature/` have been removed from your machine a branch that starts with `feature/` will still get created under the `Feature` prefix and thus enforcing the case that you don't want.

Now, on the server, however, we use a case-sensitive file system where `feature/foo` and `Feature/foo` can exist at the same time and refer to different branches. That's not the case on your machine however and leads to errors like the one you're seeing.

You can attempt to manually fix this by renaming the folder on your machine but as long as there are branches on the server (remote) that start with `Feature/` you're going to run into this issue so you first need to ensure that there are no branches on the remote that start with `Feature/`. If you don't want to mess with the `.git` folder manually (which is understandable) I would recommend cloning the repository again after you've ensured that the remote doesn't have any branches starting with `Feature`.

I'm sorry that you've run into this but there's not a lot GitHub Desktop can do to alleviate this as you'd run into the same issue eventually using the command line client. 

See also https://stackoverflow.com/questions/15371866/why-is-git-capitalizing-my-branch-name-prefix

I'm going to close this as it's not something we're going to be able to solve from within GitHub Desktop, a change to support this on case-preserving case-insensitive file systems must come from Git or the OS. I hope you're able to get your situation resolved!
