### ISSUE TITLE
Display issues on GitHub Pages

### ISSUE THREAD

**Issue by mahyarbgr3076** [desktop/desktop#10623]
why does not display others content on GitHub Pages ?
it just display some of contents in html on GitHub live Pages.
I checked issues but does not have any issue to change.
![Screenshot (31)](https://user-images.githubusercontent.com/71526698/93934277-c80ff280-fd2f-11ea-9ee7-5880b0be1066.png)

**Comment by tierninho** [comment]
@mahyarbgr3076 This issue looks to be related to GitHub Pages. Please see the help guide here: https://docs.github.com/en/github/working-with-github-pages and contact support here if needed: https://support.github.com/contact
