### ISSUE TITLE
Adding lots of files to a repo results in the UI displaying the prompt Can't find "repo name"

### ISSUE THREAD

**Issue by 7sharp9** [desktop/desktop#10620]
### Describe the bug

Adding lots of files to a repo results in the UI displaying the prompt Can't find "repo name", this results in the locate dialog been shown, which then after about 10 seconds shows the Cant find "repos name" again

### Version & OS

2.5.5
MacOS 10.15.6

### Steps to reproduce the behavior

Add a lot of files to the repo, in this instance I have 4 folders each with 200,000 files

### Expected behavior

No dialog reporting the repo cannot be found.

### Actual behavior

 The UI displays the prompt Can't find "repo name"

### Screenshots

<img width="1061" alt="Screenshot 2020-09-22 at 14 32 54" src="https://user-images.githubusercontent.com/588746/93888912-82780900-fce0-11ea-852c-1048a30bf34d.png">

### Logs

[2020-09-22.desktop.production.log](https://github.com/desktop/desktop/files/5261713/2020-09-22.desktop.production.log)

**Comment by niik** [comment]
Hey @7sharp9, thanks for opening this!

Yes, this is a known limitation I'm afraid. When the output of Git status [exceeds 20 Mb](https://github.com/desktop/desktop/blob/f97dc0d52e152880eae0e2644850ff2199d97e9c/app/src/lib/git/status.ts#L186-L191) we're unable to parse it. I think 20Mb was picked rather arbitrarily and we could probably raise it a bit but for now the only workaround would be to either make the initial commit outside of Desktop or, assuming you don't want all of those 200k files in the repository, set up a .gitignore file prior to adding the repository to Desktop.

I'm going to close this in favor of https://github.com/desktop/desktop/issues/9049
