### ISSUE TITLE
how to change password for github desktop 

### ISSUE THREAD

**Issue by oriola1** [desktop/desktop#10633]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by niik** [comment]
Hi @oriola1, please see https://docs.github.com/en/github/authenticating-to-github/updating-your-github-access-credentials for more information on changing your password.
