### ISSUE TITLE
error: cannot spawn ask-pass-trampoline.bat: No such file or directory

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#10632]
### Describe the bug

Just to clear it out. I'm completely a newbie with this github thing. A friend of mine and I are trying to do some work related to websites together and he though using github would make it easier for us. 

Basically, everytime I try to clone or publish a branch of my repository, the following error pops up; 

"error: cannot spawn C:\Users\cliente\AppData\Local\GitHubDesktop\app-2.5.5\resources\app\static\ask-pass-trampoline.bat: No such file or directory
fatal: could not read Username for 'https://github.com': terminal prompts disabled" (when I try to publish a branch)

and

"Cloning into 'C:\Users\cliente\Documents\GitHub\McvTest'... error: cannot spawn C:\Users\cliente\AppData\Local\GitHubDesktop\app-2.5.5\resources\app\static\ask-pass-trampoline.bat: No such file or directory fatal: could not read Username for 'https://github.com': terminal prompts disabled" (when I try to clone)

### Version & OS

I'm currently using GitHub Desktop 2.5.5 and Windows 10 as OS.

### Steps to reproduce the behavior

1. Open GitHub Desktop 
2. Try to clone or publish a repository
3. Error pops up

### Expected behavior

From my friend's experience, we expected to accomplish the publishment of the branch so we could join the project and start working.

### Actual behavior

It didn't publish and when I tried by joinin my friend's repository and clone it another error message poped up

### Screenshots

(Trying to publish a branch)
![image](https://user-images.githubusercontent.com/71803138/94101918-3d9ac200-fe07-11ea-8f52-02544069cd72.png)

(Trying to clone a repository)
![image](https://user-images.githubusercontent.com/71803138/94101954-5acf9080-fe07-11ea-8bd5-ffe7d99534ac.png)

### Logs

[2020-09-24.desktop.production.log](https://github.com/desktop/desktop/files/5273497/2020-09-24.desktop.production.log)

### Additional context

So I've tried generating a ssh key following a tutorial from github's page, then adding it to my github account through settings in the web app. I'm linking a screenshot here. I'm censuring the numbers and letters because I'm not sure what can people do with that, but since it's called key, better be safe. 
![sshkey](https://user-images.githubusercontent.com/71803138/94102276-29a39000-fe08-11ea-8e28-1d640332c322.png)

Also I've tried on my sister's computer and the app worked well, I then discarded an account problem because I used my own github account in my sister computer. 

I tried installing the setup from another browser but the same ocurr.

I looked on regedit for something called autorun but didn't found anything. 

I reinstalled multiple times, github and git as well.

**Comment by niik** [comment]
Hi @kurokocchibit, thanks for opening this and I'm sorry to hear you're having problems.

Could you verify that there is in fact no file in `C:\Users\cliente\AppData\Local\GitHubDesktop\app-2.5.5\resources\app\static\ask-pass-trampoline.bat`? That file is supposed to be installed alongside the application.

Do you have any anti-virus solution on your machine that could interfere with the creation of that file?

**Comment by kurokocchibit** [comment]
> Hi @kurokocchibit, thanks for opening this and I'm sorry to hear you're having problems.
> 
> Could you verify that there is in fact no file in `C:\Users\cliente\AppData\Local\GitHubDesktop\app-2.5.5\resources\app\static\ask-pass-trampoline.bat`? That file is supposed to be installed alongside the application.
> 
> Do you have any anti-virus solution on your machine that could interfere with the creation of that file?

Hello, 
Yes, I just check on that and there it is the file. 
![image](https://user-images.githubusercontent.com/71803138/94172083-6e5f1380-fe68-11ea-8e74-c2eec6c339a4.png)
But if I try to click it, this appears; 
![image](https://user-images.githubusercontent.com/71803138/94171803-158f7b00-fe68-11ea-9142-9898b955b2f5.png)
It says the following; "Windows cannot find the file C:/Users/cliente/AppData/Local/GitHubDesktop/app-2.5.5/reso.../ask-pass-trampoline.bat" Make sure the name is well-written and try again"

Also, yeah I do have an anti-virus, but I'm not sure if it can cause conflict, the one I'm using is the free trial of Avast Antivirus. I desactived its shields when I reinstalled tho

**Comment by niik** [comment]
@kurokocchibit It seems something on your machine is preventing Desktop from being able to execute that file. Have you tried the steps in our [known issues](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789) document?

**Comment by kurokocchibit** [comment]
> @kurokocchibit It seems something on your machine is preventing Desktop from being able to execute that file. Have you tried the steps in our [known issues](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789) document?

Yeah I did them all. For the first one, I can reach this "HKEY_CURRENT_USER\Software\Microsoft" but there's no Comand Processor folder nor autorun. The same with HKEY_LOCAL_MACHINE

The name of my windows user doesnt have any special char but a space, because it forces me to put a name and a surname. 

I've just uninstalled Avast and tried reinstalling GitHub but the same ocurr

I've already tried installing GitHub running the setup file as an administrator with no success. 

And I've already deleted those folders at appdata and localappdata and tried to reinstall but the error is still there. 

The only thing I haven't tried is to create a new user on windows, also, a friend of mine told me to try installing github in another path but the setup app doesnt let me choose that

**Comment by kurokocchibit** [comment]
> @kurokocchibit It seems something on your machine is preventing Desktop from being able to execute that file. Have you tried the steps in our [known issues](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789) document?

I just tried with a completely new user in Windows with no luck. The same error popped up.

**Comment by kurokocchibit** [comment]
update: I couldn't fix it yet

**Comment by jonivesto** [comment]
I ran into this issue today. Re-installing fixed it for me.

**Comment by AndresQuiVal** [comment]
why is this closed????

**Comment by XREINX** [comment]
I have the same problem

**Comment by blanker2023** [comment]
me too

**Comment by blanker2023** [comment]
How to solve it?
