### ISSUE TITLE
Cannot log in to github desktop while working behind a proxy

### ISSUE THREAD

**Issue by aimarpl** [desktop/desktop#10635]
### Describe the bug

Cannot log on to github desktop with proxied connection.
Error returned:
The server responded with an error while attempting to authenticate (407)
Proxy authentication required

### Version & OS

Github Desktop Version 2.5.5 ; 
Windows 10 10.0.18363
 
### Steps to reproduce the behavior

1. Install latest github desktop release
2. Open github desktop application
3. Sign in with username and password to github
(nothing happens, just reloads with same form, no error returned)

Alternatively
1. Install latest github desktop release
2. Open github desktop application
3. Skip logon
4. Go to file -> options -> accounts -> github.com -> sign in
5. enter credentials
6. Error (407) returned

### Expected behavior

Logon should be performed.

### Actual behavior

407 proxy error is returned

### Logs
2020-09-24T08:09:54.388Z - info: [ui] calling captureCommandOutput(where git)
2020-09-24T08:11:37.091Z - warn: [ui] deserialize: invalid JSON found at 'https://api.github.com/meta' - status: 407, length: '832' id: '(missing)'
TypeError: Failed to fetch

### Additional context

I have also tried to apply changes manually in .gitconfig with proxy user:pass@host:port, but it does not help. 
then I tried doing the same via cli -> git config --global http.proxy http://user:pass@host:port   ...also same result.

**Comment by niik** [comment]
Hi @aimarpl, thanks for opening this. I'm sorry to hear you're having issues signing in with GitHub Desktop.

Unfortunately GitHub Desktop [doesn't support authenticating proxies](https://github.com/desktop/desktop/blob/development/docs/technical/proxies.md#authenticating-proxies) at this time.

Some users have reported success with installing a local proxy which can then deal with the upstream authentication, such as [cntlm](http://cntlm.sourceforge.net) or [winfoom](https://github.com/ecovaci/winfoom) but it's not anything we have experience with.

I'm going to close this in favor of https://github.com/desktop/desktop/issues/10026, please subscribe to that issue for any updates.
