### ISSUE TITLE
Changing my account in Preferences doesn't refresh the UI.

### ISSUE THREAD

**Issue by GTruslove** [desktop/desktop#10647]
### Describe the bug

Changing my account in Preferences doesn't refresh the UI. I have 2 accounts and signing out and then signing in does nothing, even with restarts.

### Version & OS

Mac

### Steps to reproduce the behavior

Sign out.

Sign in with different account

### Expected behavior

Repositories from new account should be show.

### Actual behavior

Old respositories are stil. shown

**Comment by niik** [comment]
Hi @GTruslove, thanks for opening this.

Can you elaborate on where these repositories are located in the UI? Are you talking about the list of repositories in the sidebar, i.e:

<img width="271" alt="image" src="https://user-images.githubusercontent.com/634063/94270866-0d573e80-ff41-11ea-8f6d-8ba286c0083f.png">

A screenshot would be helpful

**Comment by GTruslove** [comment]
Yes. All I see is the old account:

![image](https://user-images.githubusercontent.com/45291224/94271640-cfa2e780-ff39-11ea-918b-aa2f0a2d4368.png)

**Comment by niik** [comment]
@GTruslove Ah, so  what's shown in that list is the list of repositories that you've cloned locally to your machine and added to GitHub Desktop. It's not a list of all repositories you have on your account on the server. You'll need to clone the repositories from your other account as well. I hope that helps clear things up!

**Comment by GTruslove** [comment]
Ah got it, thanks.
