### ISSUE TITLE
Support for Nova.app as external editor

### ISSUE THREAD

**Issue by greystate** [desktop/desktop#10645]
I would love to be able to choose Panic's **Nova** (https://nova.app) as my external editor.

**Comment by niik** [comment]
Hey @greystate, we'd be happy to review a PR that adds support for Nova. If you or anyone else is interested in picking this up please see https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md for information on how to go about adding support for  an editor.

**Comment by greystate** [comment]
Ah - of course! There's a Hacktoberfest attempt for me then :)

Thanks!
