### ISSUE TITLE
Long branch names cut off from "Current Branch" column

### ISSUE THREAD

**Issue by liamrathke** [desktop/desktop#10649]
### Describe the feature or problem you’d like to solve

I use GitHub Desktop everyday, but it's sometimes frustrating to use because many of the repositories I work on have long branch names. When there are multiple branches that start out with similar long names, it's difficult to find out which branch you are currently on. 

Without pulling up a terminal or switching to my IDE, this is only possible in GitHub Desktop by clicking on the "Current Branch" button, then hovering over the branch you are currently on, and waiting a couple seconds for the tooltip with the full branch name to appear.

### Proposed solution

The width of the "Current Branch"  column is locked to 230px; we could change the minimum width to 230px, which would allow the branch name to expand as necessary. 

Alternatively, we could allow users to resize the width of the "Current Branch" column, just as users are allowed to adjust the width of the "Current Repository" column by dragging it. If it won't be possible to change the "Current Branch" column width, we could set the branch name text to horizontally scroll on hover (example [here](https://jsfiddle.net/tb68dwqr/)).

### Additional context

Example of the branch name being cut off:

![Screen Shot 2020-09-25 at 10 35 35](https://user-images.githubusercontent.com/33555592/94280894-f6eabc00-ff1b-11ea-8b90-b3b1621ae59f.png)

The column with the max width at 230px limitation removed:

![Screen Shot 2020-09-25 at 10 48 17](https://user-images.githubusercontent.com/33555592/94282752-2f8b9500-ff1e-11ea-89ac-7ba103414c5a.png)

If we allow the column to exceed 230px in length, some minor tweaking would be necessary to ensure that all horizontal space is occupied and that the scrollbar is to the right:

![Screen Shot 2020-09-25 at 10 48 53](https://user-images.githubusercontent.com/33555592/94282962-6f527c80-ff1e-11ea-84aa-24dcfccadd3b.png)

**Comment by niik** [comment]
Hi @liamrathke, thanks for opening this and for laying out your thoughts so succinctly.

We've written a bit about why making the button width dynamic or changing the width to a min-width in https://github.com/desktop/desktop/pull/3269 so I'm not going to rehash that here but please take a look at it. It was written a long time ago but I believe a lot of it still holds true.

We're looking at ways to relax our width constraints to better support wide or high resolution monitors. For the first part of this work we're going to work on removing the resizable constraint from the sidebar and the file list in the history view. As part of that work we're going to have to look into the button widths as the first toolbar button is currently tied to the width of the sidebar.

Once that work is done (and I'm afraid I don't have an estimate for this) we can start looking at ways to allow wider toolbar buttons as well.

I'm going to roll this up into https://github.com/desktop/desktop/issues/4569. While it's not phrased  exactly the same it's referring to the same problem.
