### ISSUE TITLE
Improve date resolution on commit history

### ISSUE THREAD

**Issue by Simmeh** [desktop/desktop#10653]
All activity that occurred today is listed with date resolution in hours, such as 3h, 5h etc.  Anything that happened on a repo yesterday is shortened to 1d, the day before 2d etc. Currently to find a more precise time you have to navigate the cursor over the 1d and hover to see a full timestamp.

It can be important to examine commit times more closely when investigating issues, and when on a busy repo with 50+ commits a day this behaviour makes it awkward to see the timestamps at a glance.

Including a more detailed timestamp would remove this awkward UI problem and allow users to understand the timeline of events better.

![image](https://user-images.githubusercontent.com/36480033/94291526-a8f1aa80-ff53-11ea-9dac-e45a8d440db6.png)

**Comment by tierninho** [comment]
@Simmeh Thanks for the note. This was part of a recent change so we are unlikely to make any changes right away as we await feedback like yours. 

In the meantime, you can hover over the time to see a more granular timestamp.

![Screen Shot 2020-09-25 at 8 03 27 AM](https://user-images.githubusercontent.com/14828183/94301038-a49ea080-ff05-11ea-82e8-acac55e7b6ad.png)
