### ISSUE TITLE
How to delete files in a repository

### ISSUE THREAD

**Issue by jekaza** [desktop/desktop#10654]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@jekaza Prior to committing, right click any files and select `discard`. After committing, you must delete the file locally from the folder where your repo is located -- then commit the changes. Please reach out if you need further help.
