### ISSUE TITLE
Ability to customize the number of repos can appear in the Recent section

### ISSUE THREAD

**Issue by oguzyildiz1991** [desktop/desktop#10652]
### Describe the feature or problem you’d like to solve
Problem: I keep scrolling over a big list of repos like 1/4 the time I'm using github desktop.

### Proposed solution

I'd like to have more repos in the Recent section. I think this would improve life so much for people who have tons of repos and work on 3+ of them on a daily basis. Could be a simple setting on the Preferences

**Comment by steveward** [comment]
Thanks for the feedback @oguzyildiz1991. It sounds like you are interested in having the option to pin repositories to the top of the list. We don't have any plans in the near future to add pinning favorites in the repository list, and you can find the reasoning for that in #8183. I'm going to close this issue out, but thanks for letting us know you would like to see this feature added to GitHub Desktop. See https://github.com/desktop/desktop/issues/6460 for more discussion around the decisions.

One last note -- you can use `Command/Control+T` to quickly jump to the `Filter` search box to search for a repository.

**Comment by oguzyildiz1991** [comment]
@steveward thanks for the response. I'm not asking for a pin, I'm simply asking to increase the number of repos in the recent section. Currently, it shows the 3 latest repos I used. I'd like to increase that number, that would help me so much
