### ISSUE TITLE
The push was rejected by the server for containing a modification to the workflow file .github/workflows/main.yml

### ISSUE THREAD

**Issue by ryandesign** [desktop/desktop#10669]
### Describe the bug

I created a new branch, made some changes to my code, committed them, and then tried to push the branch to the server. It said:

> The push was rejected by the server for containing a modification to the workflow file .github/workflows/main.yml

The branch does not modify anything in the .github directory. (It was this branch: https://github.com/macports/macports-ports/pull/8551)

I was able to push the branch to the server from the command line.

### Version & OS

2.5.5, macOS 10.13.6

### Steps to reproduce the behavior

1. Create a branch with `git checkout -b opendetex`
2. Add or modify files in text editor
3. Use GitHub Desktop to add those files, enter a commit message and commit
4. Click "Publish Branch" button

### Expected behavior

successful push to server

### Actual behavior

> The push was rejected by the server for containing a modification to the workflow file .github/workflows/main.yml

### Logs

[2020-09-27.desktop.production.log](https://github.com/desktop/desktop/files/5288149/2020-09-27.desktop.production.log)

### Additional context

I have created and published hundreds of branches to this repository and others over the past 4 years and have never seen this error before.

In case it's relevant, I had created a branch of the same name on GitHub.com shortly before, then deleted it before trying to publish the branch from GitHub Desktop.

**Comment by niik** [comment]
Hi @ryandesign, thanks for opening this.

Is it possible that you happened to merge another branch into yours prior to attempting to push? It's possible that a merge commit contained a modification to a workflow file even though it wasn't authored by you.

Regardless of the reason the dialog that you're seeing should present you with an option to update your authentication token with the needed permissions to be able to push workflow files. Either follow that step to sign-in again using the browser or manually sign out and back in again and that error should go away.
y
> I have created and published hundreds of branches to this repository and others over the past 4 years and have never seen this error before.

Right, it's a pretty new thing that GitHub.com requires a special `workflow` security permission for OAuth applications such as GitHub Desktop (the command line isn't affected by this assuming you're using username/password auth or a Personal Access Token with sufficient permissions). Chances are you signed into GitHub Desktop prior to this enhanced security mode taking effect.

**Comment by ryandesign** [comment]
> Is it possible that you happened to merge another branch into yours prior to attempting to push? It's possible that a merge commit contained a modification to a workflow file even though it wasn't authored by you.

No, we don't use merge commits. I created my branch from my master, modified files, committed them, and tried to publish the branch.

> Regardless of the reason the dialog that you're seeing should present you with an option to update your authentication token with the needed permissions to be able to push workflow files.

It did ask me if I wanted to grant myself permission to modify workflow files. Since it had not been my intention to modify workflow files, I did not do so.

> Either follow that step to sign-in again using the browser or manually sign out and back in again and that error should go away.

If I see the error again the next time I try to publish a branch, I'll try signing out and back in.

I still think the program should be changed. If I am not trying to modify workflow files, it should not say that I am and it should not prevent me from publishing my branch.

> Chances are you signed into GitHub Desktop prior to this enhanced security mode taking effect.

Probably; it's been a long time since I signed in.

**Comment by niik** [comment]
> I still think the program should be changed. If I am not trying to modify workflow files, it should not say that I am and it should not prevent me from publishing my branch.

I'm afraid there's not much we can do here, that message isn't coming from GitHub Desktop but rather from the Git server  on GitHub.com. If you are certain that the message was sent in error I'd try reaching out to [GitHub Support](https://support.github.com) to have that resolved.

I don't believe there's anything else GitHub Desktop can do here so I'm going to close this out. I hope it didn't cause you too much inconvenience.

**Comment by ryandesign** [comment]
Understood. Unfortunately, GitHub no longer provides a way to contact them; see https://github.community/t/how-to-contact-github-support/123774

**Comment by ryandesign** [comment]
Now reported to the community here: https://github.community/t/the-push-was-rejected-by-the-server-for-containing-a-modification-to-the-workflow-file-github-workflows-main-yml/134629
