### ISSUE TITLE
Include a files' compatible compiler with the github desktop client on windows 10.

### ISSUE THREAD

**Issue by Chummpp** [desktop/desktop#10661]
### Describe the feature or problem you’d like to solve

The desktop client does not show a compiler when rite clicking on the folder of the cloned software.
![Capture](https://user-images.githubusercontent.com/66265171/94339395-58b03200-ffbf-11ea-914a-3e614abf2a20.PNG)

### Proposed solution

How will it benefit Desktop and its users? It will benefit the user by automatically compiling software.

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by niik** [comment]
Hi @Chummpp, thanks for opening this.

Including a compiler to build cloned projects is interesting but currently outside of the scope of GitHub Desktop. The number of different languages and build systems is more than we're able to handle with our little team.

I'm going to close this issue as it's not something we're going to be able to invest in anytime soon.
