### ISSUE TITLE
How do multiple local commit merge into a push?

### ISSUE THREAD

**Issue by yinzhenkun** [desktop/desktop#10674]
### Describe the feature or problem you’d like to solve

How do multiple local commit merge into a push?

### Proposed solution

Facilitate local commits  consolidation

### Additional context

https://user-images.githubusercontent.com/41945280/94406771-19433a80-01a5-11eb-9afc-e706dc683a73.png

**Comment by niik** [comment]
Hi @yinzhenkun. I'm afraid I don't understand what you're trying to accomplish. Could you try explaining in more detail what it is you're trying to do?

**Comment by yinzhenkun** [comment]
For example, I commit locally three times and push it to the server.
The server displays three commits.
I actually want to merge local three times into local one,then submit to the server for display once
[https://blog.csdn.net/ywdhzxf/article/details/90517432](url)

**Comment by niik** [comment]
Hi @yinzhenkun, thanks for explaining. I believe you're referring to is [squashing commits](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec) using interactive rebase, it's an advanced feature of Git that's not supported in GitHub Desktop. You can, however, choose to squash and rebase your pull requests which will take all the commits and squash them into one before merging into the target branch. See https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges#squash-and-merge-your-pull-request-commits for more information on that.
