### ISSUE TITLE
Mac Enterprise Login Failure

### ISSUE THREAD

**Issue by Connor24601** [desktop/desktop#10678]
### Describe the bug

On Mac, upon downloading github desktop, I am unable to log in to my github enterprise account despite being able to access it fine through browser.

### Version & OS

Github desktop: Most recent, just downloaded. Cannot view "about" screen, but release notes say 2.5.6.

Github Enterprise server 2.21.6

MacOS Catalina 10.15.6, 2018 Mac Mini

### Steps to reproduce the behavior

1. Download fresh copy of github desktop for mac
2. Open the application
3. Click "Sign in to GitHub Enterprise Server"
4. Enter url for a github enterprise server (https://git.****.com/) and hit enter

### Expected behavior

Continuing with the log in behavior, which I believe involves redirecting to browser.

### Actual behavior

Get error "Unable to authenticate with the GitHub Enterprise Server instance. Verify that the URL is correct, that your GitHug Enterprise Server instance is running version 2.8.0 or later, that you have internet connection and try again."
and stays on the current page

### Screenshots

None 

### Logs

[2020-09-28.desktop.production.log](https://github.com/desktop/desktop/files/5293846/2020-09-28.desktop.production.log)

### Additional context

I am also unable to clone my github enterprise repository through terminal, which gives an SSL certificate error. Almost certainly linked, but also an error I have no idea how to solve, given I am able to access the repository through browser just fine. Below is the error message for the git clone.

`% git clone https://git.****.com/bjohnson/*******.git
Cloning into '*******'...
fatal: unable to access 'https://git.****.com/bjohnson/*******.git/': SSL certificate problem: self signed certificate in certificate chain`

Any advice on the github desktop side or on the terminal side would be useful, as currently I am unable to get this repo through either terminal or github desktop

**Comment by steveward** [comment]
@Connor24601 you likely need to add the SSL certificate of your GitHub Enterprise server to your certificate chain. See [this guide](https://support.apple.com/guide/keychain-access/add-certificates-to-a-keychain-kyca2431/mac) for how to do that. Let me know if that doesn't get things working.

**Comment by Connor24601** [comment]
Hi Steveward,
Thanks for your help. I have not been able to add the SSL certificate successfully, but this is clearly an issue with my SSL certificate and GitHub Enterprise server, so I'd like to close the ticket. Thanks again.
