### ISSUE TITLE
History needs to be retrieved

### ISSUE THREAD

**Issue by CN-Jane** [desktop/desktop#10672]
GitHub desktop, the historical records can not be retrieved according to the submitted person and the comments of the submitted records. I think this function is very important.

**Comment by niik** [comment]
Hi @CN-Jane, I'm afraid I don't quite understand what functionality you're describing. Would you please elaborate?

**Comment by CN-Jane** [comment]
current history records cannot be searched according to submitter, information, path, email,comments. In my opinion, this function is pretty important.looks like:History filter conditions in TortoiseGit.

**Comment by bzmarzlaktcz83** [comment]
Priv sex

**Comment by bzmarzlaktcz83** [comment]
> GitHub desktop, the historical records can not be retrieved according to the submitted person and the comments of the submitted records. I think this function is very important.

**Comment by CN-Jane** [comment]
Hi @niik ,I describe the problem again.
current history records cannot be searched according to submitter, information, path, email,comments. In my opinion, this function is pretty important.looks like:History filter conditions in TortoiseGit.

**Comment by niik** [comment]
Hi @CN-Jane thanks for explaining. We're tracking feedback related to being able to search or filter the history in https://github.com/desktop/desktop/issues/7022. I'm going to ask that you subscribe to that issue for any updates. Thanks!
