### ISSUE TITLE
I would just disable the stashed changes menu quicker so it can't happen

### ISSUE THREAD

**Issue by Stronger6546** [desktop/desktop#10677]
I would just disable the stashed changes menu quicker so it can't happen

_Originally posted by @IanBrownDelsys in https://github.com/desktop/desktop/issues/10651#issuecomment-699023871_

**Comment by IanBrownDelsys** [comment]
If this is the case in 2.5.6 It is still not patched. I was able to wrongly pull files across branches using the #10651 method of sniping the restore button immediately after a branch switch.
