### ISSUE TITLE
Desktop hangs on committing to master until user interacts with one of the changed files.

### ISSUE THREAD

**Issue by JacobSchellman** [desktop/desktop#10689]
### Describe the bug

Before I begin, I should note that my knowledge of git in general is very limited - I really only began using it recently in order to align with class expectations. That being said, the course instructor is far more knowledge able than I and is experiencing the same issue. I have been has tasked with trying to find a solution.

I have been TAing for a introduction to programming course where we use shiftkey's desktop in order to allow students to submit their assignments via GitHub. On all students' virtual machines, we cannot readily commit to master. We hang on "committing to master". It appears though, that as soon as the user interacts with any of the changed files (reads from them, modifies them, even selects them in the Changes pane when committing), that the commit almost immediately finishes. 

### Version & OS

Version 2.5.4-linux1 on Ubuntu 20.04.1 LTS (hosted on VMWare Workstation 15, host machine running Windows 10 Enterprise 2004)

### Steps to reproduce the behavior

Please note that I have created a new repository separate from the shared Repo we are using in the programming class. The behavior persists. 
I have made a short video highlighting the problem.
https://tendies.moe/u/FmIfPUazDt.mp4

### Expected behavior

I believe the program should commit without any requisite user interaction.

### Actual behavior

The program hangs after the users instructs the program to commit forever.

### Logs

> 2020-09-29T17:09:17.775Z - info: [ui] [AppStore] loading 0 repositories from store
> 2020-09-29T17:09:17.786Z - info: [ui] [Welcome] no sign in step found. ignoring...
> 2020-09-29T17:09:17.838Z - info: [ui] [Welcome] no sign in step found. ignoring...
> 2020-09-29T17:09:17.846Z - info: [ui] launching: 2.5.4-linux1 (Linux 5.4.0-48-generic)
> 2020-09-29T17:09:17.846Z - info: [ui] execPath: '/usr/lib/github-desktop/github-desktop'
> 2020-09-29T17:09:17.865Z - info: [ui] [Welcome] no sign in step found. ignoring...
> 2020-09-29T17:09:17.988Z - info: [ui] Opt in reported.
> 2020-09-29T17:09:19.886Z - info: [ui] [Welcome] advancing to step: SignInToDotComWithBrowser
> 2020-09-29T17:09:19.888Z - info: [ui] [SignInStore] initializing OAuth flow
> 2020-09-29T17:09:19.891Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=3a723b10ac5575cc5bb9&scope=repo%20user%20workflow&state=ee401c08-68e9-478f-8275-ad3d09f91d5c
> 2020-09-29T17:09:19.892Z - info: [ui] [Welcome] current sign in state not found. ignoring...
> 2020-09-29T17:09:19.910Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
> 2020-09-29T17:09:21.653Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
> 2020-09-29T17:09:45.021Z - info: [main] Received possible protocol arguments: 2
> 2020-09-29T17:09:45.021Z - info: [main] Processing protocol url
> 2020-09-29T17:09:45.032Z - info: [ui] [Dispatcher] requesting authenticated user
> 2020-09-29T17:09:45.040Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
> 2020-09-29T17:09:45.833Z - info: [ui] [SignInStore] account resolved
> 2020-09-29T17:09:45.834Z - info: [ui] [AppStore] adding account JacobSchellman (JacobSchellman) to store
> 2020-09-29T17:09:45.835Z - info: [ui] [Welcome] advancing to step: ConfigureGit
> 2020-09-29T17:09:45.887Z - info: [ui] [Welcome] no sign in step found. ignoring...
> 2020-09-29T17:09:46.276Z - info: [ui] [Welcome] no sign in step found. ignoring...
> 2020-09-29T17:09:50.447Z - info: [ui] [Welcome] advancing to step: UsageOptOut
> 2020-09-29T17:09:54.234Z - info: [ui] Opt in reported.
> 2020-09-29T17:09:54.235Z - info: [ui] [Welcome] no sign in step found. ignoring...
> 2020-09-29T17:10:09.601Z - error: [ui] `git rev-parse --is-bare-repository` exited with an unexpected code: 128.
> stderr:
> fatal: not a git repository (or any of the parent directories): .git
> 
> (The error was parsed as 28: This is not a git repository.)
> 2020-09-29T17:10:26.272Z - info: [ui] [AppStore] adding repository at /home/pi/CodeBlocks Projects to store
> 2020-09-29T17:11:17.793Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 51.326s)
> 2020-09-29T17:12:38.264Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master --set-upstream --progress (took 3.100s)
> 2020-09-29T17:12:39.383Z - info: [ui] [BranchPruner] No branches to prune.
> 2020-09-29T17:15:31.904Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 14.309s)
> 2020-09-29T17:15:32.098Z - info: [ui] [Timing] Action 'create commit' for 'jacobschellman/TOOP-TA' took 14.510s
> 2020-09-29T17:15:51.447Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: TOOP-TA - JacobSchellman (has token)
> 2020-09-29T17:15:54.537Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 3.067s)
> 2020-09-29T17:19:23.772Z - info: [ui] [AppStore] loading 1 repositories from store
> 2020-09-29T17:19:23.772Z - info: [ui] [AppStore] found account: JacobSchellman (JacobSchellman)
> 2020-09-29T17:19:24.025Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
> 2020-09-29T17:19:24.069Z - info: [ui] launching: 2.5.4-linux1 (Linux 5.4.0-48-generic)
> 2020-09-29T17:19:24.070Z - info: [ui] execPath: '/usr/lib/github-desktop/github-desktop'
> 2020-09-29T17:19:24.255Z - info: [ui] Stats reported.
> 2020-09-29T17:19:42.396Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 9.919s)
> 2020-09-29T17:19:42.587Z - info: [ui] [Timing] Action 'create commit' for 'jacobschellman/TOOP-TA' took 10.122s
> 2020-09-29T17:19:48.434Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: TOOP-TA - JacobSchellman (has token)
> 2020-09-29T17:19:51.597Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 3.149s)
> 2020-09-29T17:23:55.462Z - info: [main] Received possible protocol arguments: 2
> 2020-09-29T17:23:55.462Z - info: [main] Processing protocol url
> 2020-09-29T17:23:55.526Z - error: [ui] `git rev-parse --is-bare-repository` exited with an unexpected code: 128.
> stderr:
> fatal: not a git repository (or any of the parent directories): .git
> 
> (The error was parsed as 28: This is not a git repository.)
> 2020-09-29T17:27:45.782Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 182.332s)
> 2020-09-29T17:27:46.002Z - info: [ui] [Timing] Action 'create commit' for 'jacobschellman/TOOP-TA' took 182.560s
> 2020-09-29T17:28:16.219Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 23.306s)
> 2020-09-29T17:28:16.383Z - info: [ui] [Timing] Action 'create commit' for 'jacobschellman/TOOP-TA' took 23.476s
> 2020-09-29T17:30:11.886Z - info: [ui] [BranchPruner] No branches to prune.
> 2020-09-29T17:30:33.885Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 3.105s)
> 2020-09-29T17:30:35.240Z - info: [ui] Executing createCommit: git commit -F - (took 1.356s)
> 2020-09-29T17:30:35.346Z - info: [ui] [Timing] Action 'create commit' for 'jacobschellman/TOOP-TA' took 4.576s
> 2020-09-29T17:30:42.175Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: TOOP-TA - JacobSchellman (has token)
> 2020-09-29T17:30:45.271Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 3.079s)
> 2020-09-29T17:31:27.263Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 1.382s)
> 2020-09-29T17:31:27.398Z - info: [ui] [Timing] Action 'create commit' for 'jacobschellman/TOOP-TA' took 1.525s
> 2020-09-29T17:31:32.471Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: TOOP-TA - JacobSchellman (has token)
> 2020-09-29T17:31:35.632Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 3.145s)
> 2020-09-29T17:32:10.455Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 9.209s)
> 2020-09-29T17:32:10.581Z - info: [ui] [Timing] Action 'create commit' for 'jacobschellman/TOOP-TA' took 9.341s
> 2020-09-29T17:48:43.854Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 672.763s)
> 2020-09-29T17:48:44.018Z - info: [ui] [Timing] Action 'create commit' for 'jacobschellman/TOOP-TA' took 672.934s
> 2020-09-29T17:52:45.577Z - info: [ui] [AppStore] loading 1 repositories from store
> 2020-09-29T17:52:45.578Z - info: [ui] [AppStore] found account: JacobSchellman (JacobSchellman)
> 2020-09-29T17:52:45.932Z - info: [ui] [BranchPruner] No branches to prune.
> 2020-09-29T17:52:45.941Z - info: [ui] launching: 2.5.4-linux1 (Linux 5.4.0-48-generic)
> 2020-09-29T17:52:45.941Z - info: [ui] execPath: '/usr/lib/github-desktop/github-desktop'
> 2020-09-29T17:54:38.073Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 86.262s)
> 2020-09-29T17:54:38.204Z - info: [ui] [Timing] Action 'create commit' for 'jacobschellman/TOOP-TA' took 86.400s
> 2020-09-29T17:56:01.521Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 10.812s)
> 2020-09-29T17:56:01.714Z - info: [ui] [Timing] Action 'create commit' for 'jacobschellman/TOOP-TA' took 11.012s
> 2020-09-29T17:58:32.921Z - info: [ui] [AppStore] loading 1 repositories from store
> 2020-09-29T17:58:32.922Z - info: [ui] [AppStore] found account: JacobSchellman (JacobSchellman)
> 2020-09-29T17:58:33.307Z - info: [ui] launching: 2.5.4-linux1 (Linux 5.4.0-48-generic)
> 2020-09-29T17:58:33.308Z - info: [ui] execPath: '/usr/lib/github-desktop/github-desktop'
> 2020-09-29T17:58:33.371Z - info: [ui] [BranchPruner] No branches to prune.
> 2020-09-29T17:58:53.029Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 12.937s)
> 2020-09-29T17:58:54.201Z - info: [ui] Executing createCommit: git commit -F - (took 1.172s)
> 2020-09-29T17:58:54.304Z - info: [ui] [Timing] Action 'create commit' for 'jacobschellman/TOOP-TA' took 14.220s

**Comment by steveward** [comment]
Thanks for the report @JacobSchellman. It looks like you may be running into https://github.com/shiftkey/desktop/issues/329, so I'd recommend following along there for updates about this.
