### ISSUE TITLE
login

### ISSUE THREAD

**Issue by deraeler** [desktop/desktop#10688]
### Describe the feature or problem you’d like to solve
Why can I sign into GitHub on the web, but I can't login to GitHub desktop using the SAME CREDENTIALS?

When I go to clone a repos (in desktop) - which is INVOKED from the web version - it works. Yet I haven't logged into Desktop at any point. It's obviously picking up on the fact that I'm logged into the web version. How do I "Fix" desktop to know my credentials so I can log into it?
A clear and concise description of what the feature or problem is.
Can't loging into Desktop - it rejects my credentials which are valid on the web version.
### Proposed solution
Allow my credentials to be updated in desktop.
How will it benefit Desktop and its users?
obvious
### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.
self explanatory

**Comment by steveward** [comment]
@deraeler thanks for the report. Just to clarify the issue -- are you encountering problems when attempting to login from `File` > `Options` > `Accounts`?

**Comment by deraeler** [comment]
Files->Options->Accounts shows me as logged in because I downloaded the
repos from the web site e;lecting to use desktop.
However, prior to that, Desktop alone would not except my same credentials
(that I subsequently used to login to the web site).

**Comment by steveward** [comment]
If you were attempting to authenticate via the dialog that appears when a clone fails then that was likely the issue -- that method of authentication will only work for third-party Git hosts. Logging in via the menu is the best method. I'm going to close this out but let me know if you continue to have any issues.

**Comment by deraeler** [comment]
Desktop now gives me a message stating that it now requires users to sign
in from the browser.

Didn't get that the first time around....it just rejected my login.  So
presume this behavior will continue and should be OK.
