### ISSUE TITLE
Backwards search for .gitignore

### ISSUE THREAD

**Issue by jamesafk** [desktop/desktop#10681]
### Describe the feature or problem you’d like to solve

A backwards search for .gitignore, so when it gets updated, desktop searches files in the git repository, checks and removes any that occur in the .gitignore file. So for example if I had a changelog.txt file and I added changelog.txt to .gitignore, it would search the repo for changelog.txt and remove it in the next push.

### Proposed solution

It will make removing sensitive files, or files that just shouldn't be in the repository, from the repo, easier by that extra 10% and remove the extra step of having to remove files from the repository after updating .gitignore, so that github removes them.

### Additional context

I am not sure if this should be an issue on desktop so please let me know if it should go somewhere else!

**Comment by bzmarzlaktcz83** [comment]
Sex kamery

**Comment by jamesafk** [comment]
> Sex kamery

huh

**Comment by bzmarzlaktcz83** [comment]
Dawaj prib

**Comment by steveward** [comment]
Thanks for the feedback @jamesafk. The process of removing files from a repository's history is rather complicated, and can cause a lot of issues for people who are not familiar with how it works. For that reason we have chosen to be very restrictive with what types of history rewriting we support in GitHub Desktop.

We do support "deleting" commits up until the point they've been pushed to the remote (that's the Undo commit feature below the commit message form).

If you've pushed your commit already you should consider your file to be public and if it contains sensitive information you should consult [the guide](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/removing-sensitive-data-from-a-repository) on how to remove sensitive data from a repository.

We're tracking ignoring files that have already been committed in #2537 -- please follow along there for updates. You can also find some more context and discussion about this in https://github.com/desktop/desktop/pull/3164#issuecomment-339789343.
