### ISSUE TITLE
How to add Pycharm as the default editor

### ISSUE THREAD

**Issue by A-a66** [desktop/desktop#10684]
My question is "how to add Pycharm as the default editor". In the installation process, I put Pycharm in the path of my computer but still, I don't see a 'Pycharm' option in the GitHub Desktop software. Please help me...

**Comment by steveward** [comment]
Thanks for contributing @A-a66. At this time GitHub Desktop only supports editors that have been specifically integrated into the application. You can find the details of how this works along with the supported editors here:

https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md

We happily accept pull requests to integrate new editors. Broader support for Jetbrains editors has been requested in https://github.com/desktop/desktop/issues/9453. You can follow along there for updates.
