### ISSUE TITLE
Expand the branch name tab! Please!

### ISSUE THREAD

**Issue by guillembertran** [desktop/desktop#10705]
### Describe the feature or problem you’d like to solve

In the Github Desktop Application there are two basic tabs: Branch tab (for branch management) and Fetch Origin (For commit management).

For the groups or companies that use a directory format for the branches (eg. Bugs/Release-October/364573-ExpandDialogFullSize) the name of the branches can become really large.

Even if I set my Github Desktop at full size, the tab is not expanding and all the names of the branches are cut:
(eg. Bugs/Release-October/36....)

![image](https://user-images.githubusercontent.com/47111706/94825639-4e969500-03fe-11eb-966d-3bc2f1cafe1c.png)

WHAT ABOUT ALL THE SPACE IN THE RIGHT? THERE IS A LOT!

### Proposed solution

If Github Desktop application is full size (or even if its none), the current expanded tab takes all the horitzontal space to the right. Or maybe just the necessary space to cover the longest branch name. Whatever!

How will it benefit Desktop and its users?
More clear visibility of name branches and last edition

### Another solution
On mouse over text displays the tooltip with the full name AT THE INSTANT THE MOUSE IT'S OVER IT (not 5 seconds after)

**Comment by steveward** [comment]
Thanks for the feedback @guillembertran. This was brought up recently in https://github.com/desktop/desktop/issues/10649 -- see @niik's reply there for some thoughts about this. I'm going to roll this into https://github.com/desktop/desktop/issues/4569, which is our tracking issue for this.
