### ISSUE TITLE
Error Cloning Github Wiki Repository

### ISSUE THREAD

**Issue by PriyaMoPatel** [desktop/desktop#10708]
### Describe the bug

I am getting an error when attempting to clone the wiki of a Github repository. 

### Version & OS
GitHub Desktop Version 2.5.6 
Windows 10 Home

### Steps to reproduce the behavior

1. Go to relevant repository in browser and select Wiki.
2. Click the copy button under 'Clone this wiki locally'.
3. Go to Github Desktop and click 'Add' -> 'Clone repository...'
4. Paste wiki repository URL and click 'Clone'

### Expected behavior

Wiki is cloned.

### Actual behavior

Error message appears: *We couldn't find that repository. Check that you are logged in, the network is accessible, and the URL or repository alias are spelled correctly.*

### Screenshots

![clone_wiki_issue](https://user-images.githubusercontent.com/9441958/94872318-4e0bf780-041a-11eb-8887-4187c27316a3.png)

### Logs

2020-10-01T22:41:15.180Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://github.com/[Redacted]/[Redacted]/wiki.git C:\Repos\wiki` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\Repos\wiki'...
remote: Not Found
fatal: repository 'https://github.com/[Redacted]/[Redacted]/wiki.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)

### Additional context

I had successfully cloned the repository a couple of weeks ago and was able to push a couple of updates through Github Desktop. However, yesterday I started receiving an 'unable to find origin' message when attempting to push additional changes to the wiki repo so I removed the wiki and have been attempting to re-clone it.

**Comment by steveward** [comment]
Thanks for the report @PriyaMoPatel. GitHub Desktop does not have great support for wikis at this time -- see https://github.com/desktop/desktop/issues/3839 for the tracking issue with known bugs. I'd recommend cloning the wiki via the command line and working with it there. I'm going to close this issue out since we are already tracking these problems.

**Comment by shadu120** [comment]
It does not work in command line ethier.
