### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by calalty** [desktop/desktop#10704]
I have been trying to create a new repository in github, however i keep getting this error when pushing it

```
$  git push --set-upstream origin master
remote: No anonymous write access.
fatal: Authentication failed for 'https://github.com/calalty/learning-TS.git/'

```

HELP!!! PLEASE :(

**Comment by steveward** [comment]
@calalty this issue tracker is specifically for GitHub Desktop. I'd recommend taking a look at our help documentation for Git authentication from the command line:

https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/set-up-git

If you have any questions I'd recommend asking for assistance on our [GitHub Support Community](https://github.community).
