### ISSUE TITLE
external editor

### ISSUE THREAD

**Issue by ujjawalmittal55** [desktop/desktop#10711]
### Describe the feature or problem you’d like to solve

in external editor only showing sublime not able to acess visual studio code

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@ujjawalmittal55 thanks for the report. Did you recently install VSCode? If so, you will need to restart GitHub Desktop in order for the editor to be properly detected. Let me know if that is not the case.

**Comment by steveward** [comment]
Since we haven't heard back from you @ujjawalmittal55 I'm going to close this out. If you are still having issues let me know and we can assist you further.
