### ISSUE TITLE
Error uploading new repro

### ISSUE THREAD

**Issue by jonmarksartist** [desktop/desktop#10722]
### Version & OS
Desktop 2.5.6
Windows 10 Pro V 10.0.19041 Build 19041

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1 Created new local repro from local files
2 Commit to main (local)
3 Click publish to origin
4 Writing objects 99%

### Expected behavior

Upload files to repro

### Actual behavior

A clear and concise description of what actually happened.

Error displayed

### Screenshots

![2020-10-04 08_19_49-GitHub Desktop](https://user-images.githubusercontent.com/61344519/95009499-7d895280-061a-11eb-9c03-06ce90300cc2.png)

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
[2020-10-04.desktop.production.log](https://github.com/desktop/desktop/files/5322790/2020-10-04.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report. It looks like the total file size is over 2GB, which is the hard limit GitHub sets for push sizes. [This guide](https://github.community/t/working-with-large-files-and-repositories/10203) has some useful tips for resolving these scenarios. I'd recommend setting up Git LFS if you are going to be working with large files.

You can also push your repository in chunks from the command line by using the following convention:

`git push <remotename> <commit SHA>:<branch>`

Let me know if you run into any issues getting this working and I can help further.

**Comment by jonmarksartist** [comment]
Hi Steve,

Sorry I'm less familiar with LFS. Do you have a step by step guide. Example
my remote is jonmarksartist and local
repo C:\Users\jonma\Documents\Projects\Unity\Living Room Rendering and host
will be https://github.com/jonmarksartist/ Living-Room-Rendering

Do I have to do folder by folder, the total folder size is 8GB as I'm using
HD render.

Here's a view of my files, maybe I can add an exclude for a folder?

[image: image.png]

Thanks

Jon
