### ISSUE TITLE
Very High CPU usage when drag & dropping the application into Mac's Applications Folder and running it from launchpad

### ISSUE THREAD

**Issue by F0rce** [desktop/desktop#10723]
### Describe the bug

CPU usage is on about 400 % even though the application is only "opened" without any major operations running.

### Version & OS

Version 2.5.6
macOS Catalina 10.15.7 (19H2)

### Steps to reproduce the behavior

1. Download GitHub Desktop
2. Drag & Drop it from the Downloads folder into the Applications folder
3. Open the Application

### Expected behavior

Zero to very low CPU usage because the application is doing "nothing".

### Actual behavior

Very high CPU usage (about 60 %)

**Comment by steveward** [comment]
Thanks for the report @F0rce. We're tracking CPU usage issues in https://github.com/desktop/desktop/issues/10625. Would you be able to try disable background fetching in GitHub Desktop to see if that resolves this issue? 

![](https://user-images.githubusercontent.com/634063/94568686-20358000-026d-11eb-888a-4ce8b0d782d1.png)

**Comment by F0rce** [comment]
I updated Github Desktop on my mac and the issues seemed to disappear.

Thanks for the help.

**Comment by steveward** [comment]
@F0rce i'm glad to hear things are working for you, and I appreciate you coming back to update us. These issues have been difficult to reproduce so that's helpful.
