### ISSUE TITLE
Add Ability to Change Tracking Branch

### ISSUE THREAD

**Issue by tyler-reed-tsico** [desktop/desktop#10726]
### Describe the feature or problem you’d like to solve

When working with forks and PRs in general, I often have a branch that has the same name in the fork (origin) versus the original (upstream). I prefer to base all of my PRs off of the upstream variant of the branch (e.g. `master`), but I'm unable to check it out since I have a branch with the same name on my fork.

To avoid dirty PRs and such, I find myself going to the command line to forcibly change the upstream branch so that I don't have this problem anymore, but it would be nice to be able to both see and change the upstream branch within the UI.

### Proposed solution

Add new option in the "Branch" dropdown menu called "Change Tracking Branch". If that's too complex, just the ability to change the remote (via "Change Remote") or similar would still satisfy my needs.

**Comment by steveward** [comment]
Thanks for the detailed feedback @tyler-reed-tsico. I'm going to lump this into https://github.com/desktop/desktop/issues/4527 where we are tracking this issue.
