### ISSUE TITLE
Can't push origin to Github using desktop client “remote end hung up unexpectedly”

### ISSUE THREAD

**Issue by Tim-maC** [desktop/desktop#10727]
### Describe the bug

Using Github Desktop.

Trying to push origin, getting this message:

Enumerating objects: 891, done. Counting objects: 100% (891/891), done. Delta compression using up to 4 threads Compressing objects: 100% (775/775), done. error: RPC failed; curl 56 Failure when receiving data from the peer fatal: the remote end hung up unexpectedly Writing objects: 100% (887/887), 498.39 MiB | 9.30 MiB/s, done. Total 887 (delta 447), reused 243 (delta 112), pack-reused 0 fatal: the remote end hung up unexpectedly Everything up-to-date

Which prevents me from pushing.

Tried disabling all firewalls and trying again without success.

### Version & OS

Version 2.5.6 Windows 10 home

### Steps to reproduce the behavior

1. Committed to push a 1.5 mb image file
2. Push origin
3. At the end of the process I get the message

Note: I can still use push origin for other files. It seems that this happens on certain files.

### Expected behavior

Should not have error message and should push to origin instead

### Actual behavior

Get error message

### Screenshots

N/A

### Logs

[2020-10-04.desktop.production.log](https://github.com/desktop/desktop/files/5324156/2020-10-04.desktop.production.log)
Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

N/A

**Comment by steveward** [comment]
Thanks for the report @Tim-maC. Are you possibly behind a firewall that could be interfering with the clone operation?

You can debug this further by running the following command to provide more verbose output:

`GIT_TRACE=1 GIT_CURL_VERBOSE=1 GIT_TRACE_PACKET=1 git clone <repository_URL>`

That should give some more information about where the operation is failing.

**Comment by niik** [comment]
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.
