### ISSUE TITLE
App fails to switch to branch with leading hyphen

### ISSUE THREAD

**Issue by tupaschoal** [desktop/desktop#10735]
### Describe the bug

If you (accidentally) create a branch with a leading `-`, you won't be able to switch to this new branch via the GUI
### Version & OS

Version 2.5.6
Windows 10 Version 2004 (19041.508)

### Steps to reproduce the behavior

1. Create a branch with leading hyphen by using the command line, e.g.: `git fetch upstream pull/<ID>/head:-pr-12345`
2. Click on current branch and try to switch to the new one with the leading hyphen
3. Notice it errors out

### Expected behavior

Switch branch normally

### Actual behavior

Error dialog with misinterpreted git command

### Screenshots

![image](https://user-images.githubusercontent.com/6443427/95148554-ffcc6080-0759-11eb-9c9c-ecd44c569511.png)
![image](https://user-images.githubusercontent.com/6443427/95148569-0955c880-075a-11eb-933a-679b31c250ac.png)

### Logs

[2020-10-06.desktop.production.log](https://github.com/desktop/desktop/files/5330911/2020-10-06.desktop.production.log)

### Additional context

If you try to create this branch via the app, it removes the leading hyphen and shows a warning symbol

**Comment by steveward** [comment]
Thanks for the report @tupaschoal. It looks like ref components can begin with a `-` but not branch names. I wasn't aware of this. From [git-check-ref-format](https://git-scm.com/docs/git-check-ref-format):

>e.g. a dash may appear at the beginning of a ref component, but it is explicitly forbidden at the beginning of a branch name

Is this a convention you use often? It definitely seems like an edge-case that most users won't run into since creating branch names like this via the CLI/Desktop isn't allowed.

**Comment by tupaschoal** [comment]
> Is this a convention you use often? 

Not at all, I typed the leading hyphen completely by mistake, but I found the app behavior weird.

**Comment by niik** [comment]
Thanks for reporting this @tupaschoal. I agree that it's a confusing behavior but given that branches with leading hyphens are prohibited in Git I don't think it's worth it for us to invest time into handling this specific case. I'm going to close this issue but if you find a way to create one of these branches through desktop please let us know and we'll take another look. I noticed that `git switch` provides a better UX than `git checkout` in this scenario as it would allows us to stop command line arg processing before we add the branch name but that command is still marked as experimental so we'd probably want to wait for a bit before switching (no pun intended) to it.
