### ISSUE TITLE
Unable to clone repository onto GitHub Desktop

### ISSUE THREAD

**Issue by paulcjw** [desktop/desktop#10739]
Expected to clone the repository.

### Actual behavior

Attempt#1:
1. Create a new repository on hard drive.
2. Publish repository
3. Successful
4.  Add > Clone a repository
5. See screenshot error1

Attempt#2:
1. Uninstalled & re-installed GitHub Desktop.
2. Repeated the procedures as in attempt 1.
3. Got the same error.

Attempt#3:
1. Uninstalled and removed all prior directories in the file explorer
2. Repeated Attempt 2
3. Still unable to clone a repository. Got a different error (screenshot error 2).

### Screenshots

![Screen Shot error1](https://user-images.githubusercontent.com/69235969/95177990-736d7c80-07f1-11eb-86d2-b9a97784739e.JPG)
![Screen Shot error2](https://user-images.githubusercontent.com/69235969/95178013-78cac700-07f1-11eb-9f77-0ac11aeeb9ed.JPG)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

I'm trying to clone a shared repository. All other members of my team except me, are able to clone it.

**Comment by steveward** [comment]
@paulcjw thanks for the report. It looks like the version of Git that ships with GitHub Desktop may be corrupt -- can you try following these steps to see if it fixes things?

1. Close GitHub Desktop 
2. Remove all of the files in `%LocalAppData%\GitHubDesktop\`
3. Reinstall GitHub Desktop from http://desktop.github.com

**Comment by paulcjw** [comment]
Hi @steveward,

So I did the steps you suggested (I assume C:\Users\G550\AppData\Local\GitHubDesktop is the same address as in step 2?).
But I still get the same error.
![Screen Shot error3](https://user-images.githubusercontent.com/69235969/95295311-690eb980-08a9-11eb-8d8c-c46f9e00f074.JPG)

Appreciate the help, thanks!

**Comment by steveward** [comment]
@paulcjw apologies for not following up -- are you still encountering this error in GitHub Desktop? Are you running any antivirus or other security software on this machine that could be interfering with GitHub Desktop?

**Comment by paulcjw** [comment]
Hi @steveward 
After getting the same error a couple more times, I discovered that Visual Studio has a GitHub extension. So I used that instead. And I uninstalled GitHub desktop and haven't tried since. I guess I'll try it again if I use an IDE without a GitHub extension.

Yes, I'm running AVG.

**Comment by steveward** [comment]
@paulcjw thanks for the update. It may be worth trying to disable AVG temporarily and then reinstall GitHub Desktop (if you plan on using it again). I'll close this issue out but let us know if that ends up getting things working for you (or doesn't).
