### ISSUE TITLE
Unable to clone a GitHub hosted Wiki repository

### ISSUE THREAD

**Issue by Digital-Platform-Services** [desktop/desktop#10732]
### Describe the bug

Unable to clone a GitHub hosted Wiki repository

### Version & OS

GitHub Desktop Version: 2.5.6
OS: Windows 10 (1903)

### Steps to reproduce the behavior

1. Go to GitHub and click click "Clone this wiki locally"
2. Open GitHub Desktop app
3. Go to File > Clone Repository...
4. Go to the URL tab
5. Paste repository URL (https://github.com/Digital-Platform-Services/Nova-Scotia-Login-Service.wiki.git)
6. Choose an empty local folder
7. Error msg: We couldn't find that repository. Check that you are logged in, the network is accessible, and the URL or repository alias are spelled correctly

### Expected behavior

GitHub Desktop will clone the GitHub hosted wiki on my local machine

### Actual behavior

Cloning fails

### Screenshots

![2020-10-05 10_51_34-GitHub Desktop](https://user-images.githubusercontent.com/57504305/95088167-f8c13600-06f8-11eb-91b9-a0ebd8406fd6.png)

### Logs

NA

### Additional context

NA

**Comment by steveward** [comment]
Thanks for the report @Digital-Platform-Services. GitHub Desktop does not have great support for wikis at this time -- see https://github.com/desktop/desktop/issues/3839 for the tracking issue with known bugs. I'd recommend cloning the wiki via the command line and working with it there. I'm going to close this issue out since we are already tracking these problems.

**Comment by shadu120** [comment]
Still not work...

**Comment by evilpeibol** [comment]
Still not work...

**Comment by ldhasson** [comment]
That would be a nice feature to have. We have so much contents in Wikis that having a local copy is really useful.

**Comment by piercetyler** [comment]
Totally agree with @ldhasson. I am trying to clone a wiki using the Desktop app but am unable to do it. Would be super nice to have!

**Comment by romanlee17** [comment]
As a temporary solution, you can clone your wiki repository using git bash, and then open that local repository using Github Desktop. It will be able to recognize it, fetch and push any changes too.

**Comment by TheSmartGerman** [comment]
Hi, also struggling to clone a wiki. Desktop is not woking. If a use bash my Images are missing. 

Most of the editing was made online. now in my local copy I'm missing the "assets" folder. any ideas?

**Comment by kmanuele** [comment]
Piling on: Still doesn't work.
Why is that 'feature' even included?

**Comment by ronhombre** [comment]
Still broken

**Comment by joyfullservice** [comment]
One workaround is to download [SourceTree](https://www.sourcetreeapp.com/), and use that to clone the wiki, then open the wiki repository as a local repository in GitHub Desktop. Once you have added the local repository, use can use it just like you normally would in GitHub Desktop.

**Comment by hippogamesunity** [comment]
> One workaround is to download [SourceTree](https://www.sourcetreeapp.com/), and use that to clone the wiki, then open the wiki repository as a local repository in GitHub Desktop. Once you have added the local repository, use can use it just like you normally would in GitHub Desktop.

Omg, this works, thanks! I wonder why they don't want to implement this feature.

**Comment by tidy-dev** [comment]
@hippogamesunity This has been fixed in [#19152](https://github.com/desktop/desktop/issues/19152) and shipped in 3.4.5-beta1.
