### ISSUE TITLE
Unable to clone repositories onto GitHub Desktop

### ISSUE THREAD

**Issue by paulcjw** [desktop/desktop#10738]
### Describe the bug

Unable to clone both personal and shared repositories from GitHub.com.

### Version & OS

Version 2.5.6; Windows 10.

### Steps to reproduce the behavior

1. Go to 'File'
2. Click on 'Clone a Repository > Select Repository > Clone'
3. See error

### Expected behavior

Expected to clone the repository.

### Actual behavior

Attempt#1:
1. Create a new repository on hard drive.
2. Publish repository
3. Successful
4.  Add > Clone a repository
5. See screenshot error1

Attempt#2:
1. Uninstalled & re-installed GitHub Desktop.
2. Repeated the procedures as in attempt 1.
3. Got the same error.

Attempt#3:
1. Uninstalled and removed all prior directories in the file explorer
2. Repeated Attempt 2
3. Still unable to clone a repository. Got a different error (screenshot error 2).

### Screenshots

![Screen Shot error1](https://user-images.githubusercontent.com/69235969/95177021-3e145f00-07f0-11eb-8a72-091590b1062f.JPG)

![Screen Shot error2](https://user-images.githubusercontent.com/69235969/95177672-0ce85e80-07f1-11eb-9a55-f4c9414ae597.JPG)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

I'm trying to clone a shared repository. All other members of my team except me, are able to clone it.

**Comment by steveward** [comment]
Closing as a duplicate.
