### ISSUE TITLE
[config] default git config in repository core.ignorecase at true

### ISSUE THREAD

**Issue by Maxipork** [desktop/desktop#10742]
### Describe the feature or problem you’d like to solve

When cloning a new repository, git config core.ignorecase seems to be always set to true in the .git folder.

### Proposed solution

Get rid of this option and let the user config with git --global or git --system decide what's best for them.

How will it benefit Desktop and its users?

This option is unintuitive as a case change in a filename should be seen and committed by default. Having to go edit the git config manually for each cloned repository if this option is unwelcome shouldn't be necessary. 

### Additional context

Small impact configuration, but I think also a small change to implement.
Thanks for reading me and have a great day.

**Comment by niik** [comment]
Hi @Maxipork, thanks for opening this. This is not something that GitHub Desktop has control over. When initializing a repository Git will probe the filesystem to determine if it's case-insensitive or not and if it is it'll set `core.ignorecase` as setting it to true can result in some unintuitive behavior unless you're paying close attention.

https://github.com/git/git/blob/d98273ba77e1ab9ec755576bc86c716a97bf59d7/builtin/init-db.c#L322-L325

See https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreignoreCase

> ### core.ignoreCase
> Internal variable which enables various workarounds to enable Git to work better on filesystems that are not case sensitive, like APFS, HFS+, FAT, NTFS, etc. For example, if a directory listing finds "makefile" when Git expects "Makefile", Git will assume it is really the same file, and continue to remember it as "Makefile".
> 
> The default is false, except git-clone[1] or git-init[1] will probe and set core.ignoreCase true if appropriate when the repository is created.
> 
> Git relies on the proper configuration of this variable for your operating and file system. Modifying this value may result in unexpected behavior.

GitHub Desktop is not going to override this default behavior of Git. If you're convinced it should I'd recommend reaching out to the Git developers directly.
