### ISSUE TITLE
Context menu operates on wrong file in commit history

### ISSUE THREAD

**Issue by nonsensery** [desktop/desktop#10743]
### Describe the bug

When I right-click on an unselected file in the commit history the actions in the context menu act on the previously selected file, instead of the newly-selected file.

### Version & OS

GitHub Desktop 2.5.6
macOS

### Steps to reproduce the behavior

1. Go to the History tab.
2. Select a commit that modified multiple files.
3. Select one of those files.
4. Right-click on one of the unselected files. (This has the side effect of selecting this new file.)
5. Choose "Copy File Path".

### Expected behavior

The path for the file that was selected by the right-click in step (4) should be copied.

### Actual behavior

The path for the file that was selected in step (3) is copied.

### Screenshots

I'm not able to provide screen shots for privacy reasons.

### Logs

Also not able to provide these.

### Additional context

I used "Copy File Path" because it's a clear example, but this bug affects all actions in the context menu.

**Comment by steveward** [comment]
Thanks for the detailed report @nonsensery. I was able to reproduce this as well, and although I feel like this has been reported previously I was unable to find an existing issue (that may have been a bug with line selection, though).
