### ISSUE TITLE
Ability to filter changed file list

### ISSUE THREAD

**Issue by Jaimi** [desktop/desktop#10752]
### Describe the feature or problem you’d like to solve

When using Github Desktop with Unity, there are many files generated that are version specific (.asset files get upgraded, .meta files generated, etc). Sometimes you will want to check these in, and sometimes you don't.  For example, working with source control you should have all your assets serialized as text. However, doing this in Unity makes the scenes load about 20x slower. 
When I am coding .cs files, I am only interested in selecting and checking these in, as checking in the other files could cause versioning issues. However, when I am ready, I do need to check them in. So I need to some files sometimes, and other times not.

### Proposed solution

Add a filter textbox above the changed files list. When a value is entered in this box, the changed files are filtered to this value (using normal file wildcards). For example, I could enter in *.proj to find the project files. Or "*.cs" to find all the csharp code files. Or I could Inter a partial name to filter based on that partial name.  Concatenate filters together with a ";"

### Additional context

![__filter](https://user-images.githubusercontent.com/11434720/95365345-a10d0100-0897-11eb-8f65-9ceeb5731f26.png)

**Comment by steveward** [comment]
Thanks for the feedback @Jaimi! This is being tracked in https://github.com/desktop/desktop/issues/6407 -- you can follow along there for updates.
