### ISSUE TITLE
Cloned project won't open in VS Code

### ISSUE THREAD

**Issue by maristhek** [desktop/desktop#10754]
### Describe the bug

Success fully cloned RAKWireless/RAK2245-LoRaGateway-RPi-Raspbian-OSA into local dir.

### Version & OS

Windows Server 2016.

### Steps to reproduce the behavior

Click on Open in Visual Studio Code
 Exception:
Error: spawn cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

Version: 2.5.6
OS: Windows 10.0.14393

### Actual behavior

Error: spawn cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

Version: 2.5.6
OS: Windows 10.0.14393

### Screenshots

![image](https://user-images.githubusercontent.com/9547432/95374825-ad8f5a80-0893-11eb-90d0-4f8cbe33d370.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the report @maristhek.

Could you open the command prompt and share the output of `echo %PATH%`?

If `System32 is not in your PATH, you will see the `ENOENT` error. You will need to edit your PATH and add the following line:

`C:\Windows\system32`

Let me know if that doesn't get things working!

**Comment by maristhek** [comment]
Kinda my bad.  It's in my Local enviro path but not System (it's a Win Srv OS - embarssing cuz I was on the MS Hydra team that devved the Win SRV OS).

Now it's peachy keen. Tnx

**Comment by steveward** [comment]
Glad to hear that got things working!
