### ISSUE TITLE
dwm.exe gpu usage very high

### ISSUE THREAD

**Issue by cambsukguy** [desktop/desktop#10753]
The program has been installed and resident for a few days.

I noticed fan noise and investigated; dwm.exe (Desktop Windows Manager) was using 50% to 70% of one of the systems' GPUs.

I exited Edge and Netflix (the usual suspects) to no avail.

Upon exiting GitHub desktop, the usage immediately plummeted.

My system is a HP Spectre using the latest Windows 2004 (19041 build 19041). It has 2 GPUs. The program was running on the main (4K) screen.

It is possible that detaching the HDMI (used with a TV), running on battery and subsequently plugging the power and HDMI back in caused the issue.

Version	10.0.19041 Build 19041
System Model	HP Spectre x360 Convertible 15-eb0xxx
Processor	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, 2592 Mhz, 6 Core(s), 12 Logical Processor(s)
Adapter Description	Intel(R) UHD Graphics
Driver Version	27.20.100.8280
Adapter Description	NVIDIA GeForce GTX 1650 Ti with Max-Q Design
Driver Version	27.21.14.5638 (Studio Driver)

**Comment by steveward** [comment]
Thanks for the report @cambsukguy. I haven't seen any other reports of this (we do have high CPU usage reports, but not GPU). If this happens again it may be worth trying to [disable hardware acceleration](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#i-get-a-black-screen-when-launching-desktop) to see if that fixes things. Let me know if you continue to run into this and we can dig in further.
