### ISSUE TITLE
Double-click file to "open in default program"

### ISSUE THREAD

**Issue by furf** [desktop/desktop#10751]
### Describe the feature or problem you’d like to solve

I often review changes in GitHub Desktop before committing, and I often review previous commits to "find my place" before getting started. When I find the file I'm looking for, I open it in my editor directly from the Desktop app. This requires me to ctrl-click on the file and choose "Open in Visual Studio Code" (or "Open with Default Program") from the contextual menu.

Contextual menus require multiple steps (keystroke, click, scroll menu, target, click) and are generally more difficult UI to navigate. For commonly used behaviors, a shortcut is preferred.

### Proposed solution

It would be more efficient if double-clicking on the file under Changes and History would trigger "Open with Default Program." 

### Additional context
![image](https://user-images.githubusercontent.com/35775/95362075-69e02500-0882-11eb-8c27-0947b34fbf37.png)
![image](https://user-images.githubusercontent.com/35775/95362018-5765eb80-0882-11eb-8a29-700dd7737722.png)

🤕

**Comment by steveward** [comment]
Thanks for the feedback @furf. I'm going to combine this into https://github.com/desktop/desktop/issues/4655 where we are tracking support for using a keyboard shortcut to open a file in the default program.

**Comment by furf** [comment]
@steveward Thanks!

**Comment by digitalmaster** [comment]
This is request is now being rolled into https://github.com/desktop/desktop/issues/2620
