### ISSUE TITLE
submodule folder is empty when switch to another branch 

### ISSUE THREAD

**Issue by superpdwang** [desktop/desktop#10767]
### Describe the bug

I have cloned a repository which has two branches(master branch + NH50) by using Github Desktop. The submodule supposed to be in NH50 branch.
The problems are like following:
1. After cloning, I was in master branch which is default settings. But when I switch to the NH50 branch, the submodule folder is empty, I have to manually give the $ git submodule update or similar command to update the submodule. 
2. I have also create a Release version for the NH50 branch on git, but the submodule folder in zip-file for the download are also empty. I think both problems are because of the same reason. 
### Version & OS

GitHub Desktop 2.5.6
Window 10
Visual Studio Code 1.49.3

### Steps to reproduce the behavior

1. Open Github Desktop
2. Click on 'clone repository'
3. switch to branch 'NH50'
4. the submodule folder is empty

### Expected behavior

all the scripts or models supposed to be include in the submodule folder.

### Actual behavior

after switch the branch, the submodule folder is empty.

### Additional context
I made a test by putting the same submodule in master branch. After cloning, the submodule in master branch is well cloned.

**Comment by steveward** [comment]
Apologies for not getting back to you about this issue @superpdwang. This looks like the same problem as https://github.com/desktop/desktop/issues/9174, where submodules are not updating correctly when switching branches. This is being tracked in our broader [submodule issue](https://github.com/desktop/desktop/issues/7523). Thanks for reporting this.

**Comment by CoderzNation** [comment]
I know this is old, and I apologize, but this still seems to be an issue. When I'm using submodules while switching branches, sometimes my submodules will disappear, and sometimes they won't.

**Comment by LalarrShoplink** [comment]
So what should can do ?
