### ISSUE TITLE
Improve consistency between the local path displayed in the New Repository and Clone Repository modals

### ISSUE THREAD

**Issue by chapb** [desktop/desktop#10774]
### Describe the feature or problem you’d like to solve

When cloning a repository -- after you make a repository selection -- the local path updates to display the full path of the new repository (i.e. including the repository name). 

![ghd_clone](https://user-images.githubusercontent.com/12411657/95622372-57f8b080-0a41-11eb-9123-1bcf9f4a6b75.PNG)

But, when adding a new repository, the local path remains static, even after specifying a repository name.

![ghd_new](https://user-images.githubusercontent.com/12411657/95622473-92fae400-0a41-11eb-9c39-9f32a45f5810.PNG)

While the behavior is consistent between modals (windows?), and the repository is created as a subfolder of the default folder in both cases, this is displayed differently. 

This inconsistency may confuse new users as to what path to specify: a complete path, as in the clone repository modal; or a parent path, as in the new repository modal. This may either cause the user to create the repo as a subfolder of the intended folder, or attempt to clone a repository into a folder with existing contents.

### Proposed solution

As the user types a name in the new repository modal, it could be automatically appended to the local path.

### Additional context

Apologies if this is a duplicate -- hard to come up with useful search strings. Cheers!

**Comment by steveward** [comment]
Thanks for the report @chapb. This behavior is going to be improved in https://github.com/desktop/desktop/pull/10081 -- once that is merged in it should make things more consistent. I'll bump that PR up, but please feel free to add any feedback you have to that thread.

**Comment by niik** [comment]
After reading #10081 I believe there's two different issues at play here. Gonna reopen this as I don't believe it's actually remedied by #10081.
