### ISSUE TITLE
Error uploading new repro

### ISSUE THREAD

**Issue by jonmarksartist** [desktop/desktop#10772]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

Version & OS
Desktop 2.5.6
Windows 10 Pro V 10.0.19041 Build 19041

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Expected behavior
1 Created new local repro from local files
2 Commit to main (local)
3 Click publish to origin
4 Writing objects 99%

### Actual behavior

A clear and concise description of what actually happened.

Upload files to repro

### Screenshots

Add screenshots to help explain your problem, if applicable.
![image](https://user-images.githubusercontent.com/61344519/95607886-45d43d80-0a54-11eb-998a-30f7be7fda41.png)
g)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
[2020-10-04.desktop.production.log](https://github.com/desktop/desktop/files/5356212/2020-10-04.desktop.production.lo
### Additional context

Replied on ticket 10722 with 

"Thanks for the report. It looks like the total file size is over 2GB, which is the hard limit GitHub sets for push sizes. This guide has some useful tips for resolving these scenarios. I'd recommend setting up Git LFS if you are going to be working with large files.

You can also push your repository in chunks from the command line by using the following convention:

git push <remotename> <commit SHA>:<branch>

Let me know if you run into any issues getting this working and I can help further."

My reply not answered

Hi Steve,

Sorry I'm less familiar with LFS. Do you have a step by step guide. Example
my remote is jonmarksartist and local
repo C:\Users\jonma\Documents\Projects\Unity\Living Room Rendering and host
will be https://github.com/jonmarksartist/ Living-Room-Rendering

Do I have to do folder by folder, the total folder size is 8GB as I'm using
HD render.

Here's a view of my files, maybe I can add an exclude for a folder?

![image](https://user-images.githubusercontent.com/61344519/95608079-892eac00-0a54-11eb-9ab3-c16e16dc19d0.png)

Thanks

Jon

**Comment by steveward** [comment]
@jonmarksartist apologies for not getting back to you yet -- I'm not seeing your ticket in our ticketing software so I'm not sure what happened there. You can definitely exclude the 8G folder by adding it to the repository's `.gitignore`. See [this guide](https://docs.github.com/en/free-pro-team@latest/github/using-git/ignoring-files). You can ignore an entire directory by adding it to your `.gitignore`, i.e. adding the line `Assets` would ignore the `Assets` directory. That would definitely help reduce the total size of the repository, but if the repository is still over 2GB in size you will continue to run into this error. Let me know if I can help with setting up your `.gitignore` or Git LFS.

**Comment by steveward** [comment]
@jonmarksartist I'm going to close this issue out as we haven't heard back from you with any updates. If you are still having problems please let me know.
