### ISSUE TITLE
32 bit app version

### ISSUE THREAD

**Issue by tiziodcaio** [desktop/desktop#10773]
Exe or Msi doesn't work in 32 bit windows 10 pc! Please create a 32 bit version...
### Thanks

**Comment by klo1991qa** [comment]
謝謝

**Comment by steveward** [comment]
Thanks for the feedback @klo1991qa. You can check [this thread for an experimental 32-bit build](https://github.com/desktop/desktop/issues/9034#issuecomment-581552044) of GitHub Desktop. Please follow along there for updates. Thanks for using GitHub Desktop.
