### ISSUE TITLE
Linux!!

### ISSUE THREAD

**Issue by yezz123** [desktop/desktop#10799]
As a `Linux` user and `Github `user why there is no desktop application its will be more helpful and also compatible cause a lot of people don't like to user terminal to publish a repository or create a new commit.
Also the interface can be more helpful for junior user and also simple to use.
And you can check that the community of users who use `Linux` and work on there `projects` and there `codes` are so large that what i think will be the good idea for this corporation to add an `Github` app for `Linux` . 
this is just a simple Suggestion for a new feature can be more helpful in the future.

**Comment by niik** [comment]
Hi @yezz123,  thanks for opening this. I'm going to refer you to #1525 which has all of the current thinking and context around Linux support. Please subscribe to that issue for any updates.

> We have no immediate plans to support an official Linux version, but we continue to evaluate it alongside our other priorities and we know it's important to many people out there. I also know "maybe someday" is a disappointing response and I apologize for that. We're enormously grateful that @shiftkey has built a fork (https://github.com/shiftkey/desktop) and that many people are using that successfully, but @shiftkey is only one person and I hope people will understand that he's not always able to keep it entirely up to date with the official version.
>
> I assure you that if/when we're able to commit to supporting a Linux version, we'll update this issue accordingly, and I appreciate your ask for a more "official" answer.
