### ISSUE TITLE
Not able to see my all repository in git desktop 

### ISSUE THREAD

**Issue by Vaibhav-84** [desktop/desktop#10808]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by Vaibhav-84** [comment]
![Uploading Screenshot 2020-10-12 210242.png…]()

**Comment by Vaibhav-84** [comment]
![Screenshot 2020-10-12 210242](https://user-images.githubusercontent.com/69572218/95764599-48da6280-0cce-11eb-933f-34b5f232d794.png)

**Comment by niik** [comment]
Hi @Vaibhav-84. The list you took  a screenshot of only includes the repositories that you've cloned to your machine using GitHub Desktop. If you want to see all the repositories you have access to on your GitHub.com account please click the Add button and then `Clone Repository`

<img width="263" alt="image" src="https://user-images.githubusercontent.com/634063/95873017-c7d3a780-0d6f-11eb-8229-b8e3bac691f0.png">

If you have repositories on your machine already you can choose `Add Existing Repository` instead.

I'm going to close this as it doesn't appear to be a bug in Desktop but please let us know if it's still an issue for you.
