### ISSUE TITLE
Run git remote prune origin if pull fails with unable to update local ref

### ISSUE THREAD

**Issue by maxkoshevoi** [desktop/desktop#10805]
### Describe the feature or problem you’d like to solve

From time to time when I pull updates, I get `error: cannot lock ref (unable to update local ref)`. And until I run `git remote prune origin` the problem won't go away.

### Proposed solution

Could you please automatically run this command if fetch/pull/push fails with `unable to update local ref` error.

### Additional context

1) Pull fails
![image](https://user-images.githubusercontent.com/6609929/95732469-751fc000-0c89-11eb-9a09-8f90b05d34f5.png)

2) I run the command
![image](https://user-images.githubusercontent.com/6609929/95732679-bfa13c80-0c89-11eb-921f-41ac6da2ec36.png)

3) I click `Pull` button again and everything works
![image](https://user-images.githubusercontent.com/6609929/95732765-dfd0fb80-0c89-11eb-9aaa-61e7862739a5.png)

**Comment by steveward** [comment]
@maxkoshevoi thanks for the report, and apologies for the delay. This issue has been discussed in https://github.com/desktop/desktop/issues/5438, and there are some mentioned workarounds there. A number of users have had success running a `git gc --prune=now` and then deleting `.git/refs/remotes/origin`. Let me know if that does not get things working for you.

**Comment by maxkoshevoi** [comment]
Hi, I don't have any issues. `git remote prune origin` works for me in this situation.

I'm asking so GitHub Desktop will execute this command automatically if such error occurres and retry the pull.

**Comment by maxkoshevoi** [comment]
@steveward Should I specify that this is feature request and not a bug somewhere?
