### ISSUE TITLE
Add "add as a shortcut to desktop" right click context

### ISSUE THREAD

**Issue by alimertcakar** [desktop/desktop#10809]
![Screenshot_4](https://user-images.githubusercontent.com/56369392/95766896-9fd73c00-0cbc-11eb-852a-f255ff94839d.png)

I have dozens repositories with similar names. Accessing them from the desktop with a shortcut could be a life saver.
Take your time

**Comment by steveward** [comment]
@alimertcakar thanks for contributing. Just so I understand the request -- are you wanting a shortcut in GitHub Desktop to create a shortcut on your desktop that will then launch the repository in GitHub Desktop? Similar to the `right-click` > `Send to` > `Desktop (create shortcut)` option on Windows?

**Comment by alimertcakar** [comment]
Yes, exactly. I think it may be a very cool feature. But you don't have to add that if you don't see fit.
