### ISSUE TITLE
Error: git: 'remote-https' is not a git command. See 'git --help'.

### ISSUE THREAD

**Issue by DawonChoi** [desktop/desktop#10801]
### Describe the bug

When I comment on a commit message and fetch origin in the Github Desktop, I got an error message like
git: 'remote-https' is not a git command. See 'git --help'.

### Version & OS

window 10 home

### Actual behavior
I don't have any idea.
1. reinstall, reinstall, reinstall...

### Screenshots

![report](https://user-images.githubusercontent.com/41173953/95708651-c9ca3780-0c97-11eb-8ea2-4d30bc5605a1.PNG)

**Comment by niik** [comment]
Hey @DawonChoi, we've seen a few of these errors pop up recently and we're gonna use #10345 to track them so please follow that issue for any updates. If you could also answer the questions in https://github.com/desktop/desktop/issues/10345#issuecomment-673450605 that'd be really helpful.
