### ISSUE TITLE
Update from default branch is not working anymore

### ISSUE THREAD

**Issue by riccardodivirgilio** [desktop/desktop#10804]
### Update from default branch is not working anymore

The menu item Branch > Update from default Branch is not working anymore, this menu item was once named Update from MASTER.

### Version & OS

Version 2.5.6, MacOS

### Steps to reproduce the behavior

1. Create a new branch from master
2. Checkout master
3. Add a commit
4. Switch to the branch you just created
5. Click the button Branch > Update from default branch

### Expected behavior

The button is clickable and creates a merge

### Actual behavior

The button is unclickable

### Screenshots

<img width="354" alt="Screenshot 2020-10-12 at 10 03 42" src="https://user-images.githubusercontent.com/187641/95720959-36cad680-0c72-11eb-830c-cfb862898a9a.png">

**Comment by riccardodivirgilio** [comment]
Ok so it looks like all my repo hosted on github do not have this problem, they show correctly "master" in the menu.
All other repos I have on private repositories do have this problem, even if (with the very same repo on the same machine) that button used to work.

**Comment by steveward** [comment]
Thanks for the report @riccardodivirgilio. Are these private repositories local-only, or have they been published to a Git hosting provider?

For a non-GitHub repository we check what the `origin/HEAD` symbolic ref points to in the repository. This is a ref that remotes declare to indicate which branch should be considered the "default" branch.

Are you able to run this command on your local repository and see whether it returns `origin/master`? 

```
$ git symbolic-ref refs/remotes/origin/HEAD
```

**Comment by leofonic** [comment]
In my case this command showed the following output:

```
$ git symbolic-ref refs/remotes/origin/HEAD
fatal: ref refs/remotes/origin/HEAD is not a symbolic ref
```

I found a solution to this here:
https://stackoverflow.com/questions/45811971/warning-ignoring-broken-ref-refs-remotes-origin-head

After inspecting branches with "git branch -r" and verifying "origin/HEAD" was not present in the list, i did:

`git remote set-head origin master`

And the greyed out command "Update from default branch" turned back into "update from master" and was selectable again.

**Comment by riccardodivirgilio** [comment]
hi, so sorry I missed the email!

`➜  rotostampa git:(feature/new-layout) ✗ git symbolic-ref refs/remotes/origin/HEAD
fatal: ref refs/remotes/origin/HEAD is not a symbolic ref`

**Comment by riccardodivirgilio** [comment]
I can confirm that this command works: `git remote set-head origin master`

I think in the case where the default branch is not set, we can maybe assume master is the default?

**Comment by steveward** [comment]
@riccardodivirgilio I'm glad to hear that got things working for you.

>we can maybe assume master is the default?

A lot of repositories are moving from `master` -> `main` for the default branch, so that isn't an assumption we can make going forward.

**Comment by abhinavvaidya** [comment]
> git remote set-head origin master

I had the same issue, @riccardodivirgilio : your command helped, thank you!
