### ISSUE TITLE
Cannot clone private repository if your Windows username contains `(` bracket

### ISSUE THREAD

**Issue by JNCressey** [desktop/desktop#10811]
### Describe the bug

When logged in to windows computer as a user that has brackets in its name, for example `User(Admin)`, 

using GitHub desktop to attempt to 
- clone a private repository from your GitHub profile, 
- or create a tutorial repository, 
- or publish a branch to GitHub after creating from a local folder, 

will result in an error that includes `'C:\Users\Guest' is not recognized as an internal or external command, operable program or batch file.` (logs attached). 

From that, it would appear some command is trying to run something without properly handling the `(` bracket in the path. 

### Version & OS

GitHub Desktop Version 2.5.6. 

OS: Microsoft Windows 10 Pro. Version 1909 (OS Build 18363.1082) 64 bit

### Steps to reproduce the behavior

common steps:

1. Create a local account named `Guest(Admin)`. (files owned by this user are in subdirectories of `C:\Users\Guest(Admin)\`)
2. From `https://desktop.github.com/` press `Download for Windows (64bit)`, and run the installer
3. Sign in to GitHub Desktop.

#### Cloning a repository

4. From the `Let's get started!` page, press `Clone repository from the Internet...`.
5. Select one of your private repositories from the 'GitHub.com' tab
6. Choose a local path that starts with `C:\Users\Guest(Admin)\`
7. Press `Clone` and see the error.

#### Creating a tutorial repository

4. Ensure you don't already have a `desktop-tutorial` repository in your GitHub profile and there isn't a folder already at `C:\Users\Guest(Admin)\Documents\GitHub\desktop-tutorial`.
5. From the `Let's get started!` page, press `Create a tutorial repository...`.
6. Press `Continue` and see the error.

#### Publishing a branch

4. Create a folder `C:\Users\Guest(Admin)\Documents\GitHub\test`.
5. From the `Let's get started!` page, press `Create a New Repository on your hard drive...`.
6. Enter name `test` and local path `C:\Users\Guest(Admin)\Documents\GitHub\test` and press `Create repository`.
7. Press `Publish repository`.
8. Select the `GitHub.com` tab and have `Keep this code private` ticked.
9. Press `Publish repository` and see the error.
10. Press `Publish branch` and see the error.

### Expected behavior

These operations should successfully complete.

### Actual behavior

When cloning, no local folder is created, no files arrive, GitHub desktop does not list the repository.

When publishing or creating a tutorial repository, an empty repository is created at GitHub with no files uploaded to it.

### Logs

Logs attached. The only edit I have made is replacing parts of the OAuth URL with the full block character █.

[2020-10-12.desktop.production.log](https://github.com/desktop/desktop/files/5366311/2020-10-12.desktop.production.log)

The repositories with these names are public:
 - JNCressey/click-counter
 - JNCressey/hannoi-no-recursion
 - JNCressey/ante-somnum
 - JNCressey/MPMP_BankBalance
 - JNCressey/Crumble

The repositories with these names are private but I don't mind their names being public
 - JNCressey/RuneScape-SpicyStew
 - JNCressey/click-counter
 - JNCressey/minecraft-identicon-skins
 - JNCressey/hello-world

The repository with this name is not mine, but a random public repository:
 - fw876/helloworld

### Additional context

Cloning public repositories worked fine.

On the same computer, I logged in to a different account `James` and installed GitHub Desktop and it worked fine.

**Comment by steveward** [comment]
Thanks for the detailed report @JNCressey. This is a known issue that is tracked in our [help document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789), and is something that we are planning to address in the future. I'm going to close this out, but thanks for using GitHub Desktop!
