### ISSUE TITLE
Cannot scroll inside expanded commit message

### ISSUE THREAD

**Issue by nikita-kiryanov** [desktop/desktop#10815]
### Describe the bug

If the commit message is so long that it takes more than one screenful of rows, you can't read all of it even at the Expanded view, because the expanded view is not scrollable, and the commit message will be cut off at the bottom of the screen.

### Version & OS

Version 2.5.6
Windows 10

### Steps to reproduce the behavior

1. Make a commit with a very long message, one that takes multiple screenfuls.
2. Click on the commit, and click on "Expand" to see the whole message.
3. Observe that you can't see the whole text, and also scroll doesn't work.

### Expected behavior

Expand view should have a scroll bar when necessary.

**Comment by niik** [comment]
Thanks for reporting this @nikita-kiryanov! I've reproduced this and opened #10824 to fix it which should hopefully get included in the next production release.

**Comment by candace8879** [comment]
> ### Describe the bug
> 
> 
> 
> If the commit message is so long that it takes more than one screenful of rows, you can't read all of it even at the Expanded view, because the expanded view is not scrollable, and the commit message will be cut off at the bottom of the screen.
> 
> 
> 
> ### Version & OS
> 
> 
> 
> Version 2.5.6
> 
> Windows 10
> 
> 
> 
> ### Steps to reproduce the behavior
> 
> 
> 
> 1. Make a commit with a very long message, one that takes multiple screenfuls.
> 
> 2. Click on the commit, and click on "Expand" to see the whole message.
> 
> 3. Observe that you can't see the whole text, and also scroll doesn't work.
> 
> 
> 
> ### Expected behavior
> 
> 
> 
> Expand view should have a scroll bar when necessary.
> 
>
