### ISSUE TITLE
Verified commits and tags

### ISSUE THREAD

**Issue by matt-hu** [desktop/desktop#10810]
### Describe the feature or problem you’d like to solve

At the moment, GitHub Desktop is unable to make verified commits and tags

### Proposed solution

There should be an option to enable verified commits within the app. This would mean everyone using this feature would have their commits show up as verified, like they do when you commit directly on the GitHub website. To get around this at the moment, I have to use the command line to make sure that my tags are verified. This is a real pain to do and anything done to solve this would be very much appreciated!

**Comment by niik** [comment]
Hi @matt-hu, thanks for opening this. I'm going to roll this into #78 as that deals with being able to sign commits which is necessary to have commits marked as "verified" on GitHub.com. Please subscribe to that issue for any updates!
