### ISSUE TITLE
Resolving conflicts using "use the added file from [branch]" incorrectly commits file with merge conflicts

### ISSUE THREAD

**Issue by Myaamori** [desktop/desktop#10820]
### Describe the bug

When merging two branches each containing newly added files with the same name but differing content, and "use the added file from [branch]" is selected to resolve the conflict, Github Desktop will commit a file containing merge conflicts (including the conflict markers), rather than the file from the specified branch.

### Version & OS

Reproduced on:

* 2.5.6, Windows
* 2.5.4-linux1 (unofficial Linux fork), Arch Linux

### Steps to reproduce the behavior

Prepare the repository:

```
$ mkdir testrepo
$ cd testrepo
$ git init
Initialized empty Git repository in /home/user/GitHub/testrepo/.git/
$ touch file
$ git add file
$ git commit -m "initial commit"
[master (root-commit) 854f1d1] initial commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 file
$ git checkout -b new-branch
Switched to a new branch 'new-branch'
$ cat >new-file <<END
> text
> some more text
> hello
> END
$ git add new-file
$ git commit -m "new file from new-branch"
[new-branch bf00580] new file from new-branch
 1 file changed, 3 insertions(+)
 create mode 100644 new-file
$ git checkout master
Switched to branch 'master'
$ cat >new-file <<END
> some other text
> different from the text on the other branch
> hello
> END
$ git add new-file
$ git commit -m "new file from master"
[master 382ec2b] new file from master
 1 file changed, 3 insertions(+)
 create mode 100644 new-file
```

Then in Github Desktop:

1. Choose `File > Add local repository...`
2. Navigate to the test repository and click `Add repository`
3. Select `Branch > Merge into current branch...`
4. Select the branch `new-branch` and click `Merge new-branch into master`
5. Choose `Use the added file from master` for `new-file`
6. Click `Commit merge`

### Expected behavior

`new-file` should contain the contents originally committed to the `master` branch:

```
some other text
different from the text on the other branch
hello
```

### Actual behavior

`new-file` instead contains a file with merge conflicts:

```
$ cat new-file 
<<<<<<< HEAD
some other text
different from the text on the other branch
=======
text
some more text
>>>>>>> new-branch
hello
$ git log --pretty=oneline --abbrev-commit
9751b71 (HEAD -> master) Merge branch 'new-branch'
382ec2b new file from master
bf00580 (new-branch) new file from new-branch
854f1d1 initial commit
$ git status
On branch master
nothing to commit, working tree clean
```

### Additional context

When merging modifications to the same file rather than two added files, it works as expected. `git checkout --ours` and `git checkout --theirs` both work as they should when executed from the command line.

**Comment by niik** [comment]
Thanks you so much for opening this @Myaamori and thanks especially for the detailed step-by-step instructions, that was very helpful! I've opened #10826 which I believe will fix this issue and I'm hoping to get that into the next production release in the early November!

**Comment by ma-6cji** [comment]
please wait  thank  you
