### ISSUE TITLE
Annotate or flagging a branch

### ISSUE THREAD

**Issue by kwhjvdkamp** [desktop/desktop#10829]
### Describe the feature or problem you’d like to solve

Actually, I like to do a suggestion for a feature. A feature which might  help to a little bit about branches in operation.
When a certain branch is in operation, it would be nice that collaborators know a little bit more about the status of the branch; what the purpose is/was of that branch.
Let me try to explain. 
Currently I do have solution, which I am working on having at the same time two or three branches in operations. Yesterday, I created a new branch: purpose my manual ongoing proces every other week checking if new packages are published/upgrading npm packages . After upgrading I was notified that 4 high vulnerabilities occurred on one particular package. Executing 'npm audit fix' did not succeed. It turned out those vulnerabilities do have something to do with security issues which are flagged as 'medium' problems. Problems about prototype pollution possibilities in the 'node-forge' package. 
It is obvious you do not want to merge such branch into your master but it is thinkable you want to keep that branch and fix it when a solution on those vulnerabilities has been published. Then it might be helpful to annotate such a branch not valid for merge into master preventing you accidently performing a merge with all its consequences, performing a rollback ect.

### Proposed solution

A Boolean option in a context menu on that particular branch to flag it still not suitable(valid) to merge into master because of containing certain (security) vulnerabilities.

It might help Desktop and others user preventing accidently bringing security issues into your master (production)

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by niik** [comment]
Hi @kwhjvdkamp, thanks for opening this. I feel like the scenario you describe is where a [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/) would come in very handy. You'd open your PR in draft mode to signal that it's not ready for review or merging but might be one day.

I hope that's helpful to you, I don't think implementing something custom is something that the Desktop product should do ourselves as it wouldn't be visible to users of other clients. Different teams have different approaches (ie. branch naming schemes).
