### ISSUE TITLE
Paging down through changed files stops working when highlighted file goes off screen

### ISSUE THREAD

**Issue by gingerbeardman** [desktop/desktop#10837]
### Describe the bug

Paging down through changed files stops working when highlighted file/row goes off screen

### Version & OS

- GitHub Desktop 2.5.6
- macOS 10.14.6 (18G6032)

### Steps to reproduce the behavior

1. repo with more than one screen full of changes
2. click on a file to highlight it
3. press page down repeatedly, or hold page down key

### Expected behavior

- should page down repeatedly

### Actual behavior

- page down works only until highlighted file does off screen (so, once here)

### Screen Recording

- https://imgur.com/a/s5jCzGd 

### Logs

n/a

### Additional context

- Workaround: scrolling only using the cursor keys, as this repeatedly moves the highlighted row (keeping it on screen)

**Comment by niik** [comment]
Hey @gingerbeardman, thanks for opening this. Would you mind trying out https://github.com/desktop/desktop/pull/10866 and seeing if that works for you? I took a quick stab at this but the selection logic is rather gnarly so I'd really appreciate a second pair of eyes.

**Comment by gingerbeardman** [comment]
I don't have a way of building source right now, sorry.

**Comment by ma-6cji** [comment]
thanks  you   for  your  job
