### ISSUE TITLE
App not re-connecting to repo after connecting to VPN

### ISSUE THREAD

**Issue by neziric** [desktop/desktop#10847]
### Describe the bug

I have to be on VPN in order to fetch commits from repository hosted on GitLab.
When VPN is not connected and I click on "Fetch Origin", "Fetching origin" and spinner icon is shown.
At this point when I connect to VPN, the app is not trying to re-connect and just fails after a while.

### Version & OS

Version 2.5.6 on macOS 10.15.3 (19D76)

### Steps to reproduce the behavior

1. VPN is disconnected
2. Click on Fetch origin
3. Fetching origin and loading icon displayed
4. Connect to VPN
5. App still doesn't re-connect to the repository and fails after a while (popup with error message "Authentication failed...")

### Expected behavior

After I connect to VPN, app should re-connect to repository within seconds

### Actual behavior

After I connect to VPN, app still showing "Fetching origin" and fails after a while

### Screenshots

None

### Logs

```
stderr:
ssh: connect to host xxx.xxx port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Preferences.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
2020-10-16T17:30:45.753Z - info: [ui] proxy url not resolved, protocol not supported
2020-10-16T17:32:00.854Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 75.101s)
2020-10-16T17:32:00.862Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
ssh: connect to host xxx.xxx port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Preferences.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
```

### Additional context

None

**Comment by steveward** [comment]
Thanks for the report @neziric. The original fetch operation will continue until timeout, and switching to a VPN wouldn't interrupt that connection. A Git fetch operation from the command line would behave the same way. Since switching to a VPN in the middle of a fetch operation is a pretty specific scenario I'm going to close this issue out as it isn't something that would likely affect a lot of users. Thanks for using GitHub Desktop!
