### ISSUE TITLE
The case for prioritizing a rollback feature, e.g checkout <SHA> or checkout -b <SHA>

### ISSUE THREAD

**Issue by niclasmattsson** [desktop/desktop#10858]
There are several issues that request some kind of rollback feature in Github Desktop (see list below). Although one is still tagged future-proposal there is no indication that any are currently under consideration, and comments from the dev team have so far been largely discouraging.

Here I make the case that even a basic beginner-friendly Git application like Github Desktop needs to have **some** kind of rollback mechanism. My hope is to convince the devs to instigate a new `epic-rollback` issue tag and make this a priority for the next Desktop version.

### Existing issues with rollback feature requests

These are the main issues which propose rollback variants and their command-line equivalents:

* #10068 git checkout SHA or git checkout tag
* #8580 git checkout SHA  (folded into #3474)
* #7719 git checkout -b SHA
* #6291 git checkout SHA  (folded into #3474)
* #5860 git reset --hard SHA  (or --soft)
* #3474 git checkout SHA  (tagged `future-proposal`)
* #2347 "Roll back to this commit"  (previous feature of GitHub for Mac)

### The case

1. If you can't roll back to a previous state, then you are missing a major selling point of version control. To drive this point home, this is the first paragraph of the introduction in the "Pro Git" book. Note that roughly half the text refers to rollback mechanisms.
<p align="center"><img width="514" alt="Pro Git book highlights" src="https://user-images.githubusercontent.com/33093224/96348402-bf99a600-10a8-11eb-8a70-60f352597174.png"></p>

2. The ability to roll back to a previous commit is arguably **more** important for coding beginners than for experienced devs. One reason is that beginners are less likely to have anticipated risky coding excursions by creating a new branch in advance. Also, if Github Desktop doesn't provide any way of rolling back then Git beginners will have to google how to do it in the CLI. Even an imperfect implementation of rollback in Desktop would be preferable to abandoning newbies entirely.

3. To anticipate the question that Desktop devs ask about most feature requests: **"Why do you need this feature in your workflow?"** Here are some reasons:
    * Abandon a coding dead-end when you didn't create a branch.
    * To retroactively create a branch at a previous commit.
    * To manually bisect bugs.
    * Allow inspecting the state of the repository in past commits. Unlike some other Git GUIs, you cannot currently browse files in Github Desktop (only commit diffs). But if Github Desktop could temporarily roll back, you could at least inspect files in your editor.
    * The question itself is not always relevant. If every feature of every application required a use case in ideal workflows then we would never have undo/redo - or backup.

4. Another anticipated objection: **"Some rollback commands lead to a Detached HEAD state, which can be extremely confusing and hard to exit for beginners."** This is on point and something the devs clearly are concerned about, see e.g. https://github.com/desktop/desktop/issues/10068#issuecomment-648534680 and https://github.com/desktop/desktop/issues/5860#issuecomment-428959691. I have some suggestions on how to mitigate this problem, see #10857.

### So what kind of rollback should Desktop implement?

I honestly don't have a preference - my point here is just that Desktop has to pick at least one. But I'll note that both `git checkout SHA` and `git checkout -b SHA` can be implemented at practically zero development cost in the right-click context menu of the commit history. All the infrastructure for dealing with the detached HEAD state (for `git checkout SHA`) or managing branches (for `git checkout -b <SHA>`) is already in place. So frankly it's getting annoying that Desktop has punted on adding this to the UI for two years.

### The role of Github Desktop

Most other git GUIs aim to reproduce every git command, which tends to make the UI overwhelming for beginners. I think it's brilliant that Github Desktop has chosen a different direction. Everything in Desktop is designed to be user-friendly and gently introduce git concepts: the deliberately limited feature set, the Summary page with suggested next steps, the context-sensitive morphing fetch/pull/push button and the clever abstracting-away of the index/staging area. But everyone needs to roll back from time to time. Currently Desktop banishes new git users to the scary wilderness of the command line just when they need hand-holding the most, when they face a potentially risky rollback. Providing a limited, relatively safe rollback implementation in Github Desktop would certainly lead to fewer self-inflicted Git disasters for newbies - and Desktop would finally become "feature complete" (for basic use).

EDIT: Removed brackets around all occurances of SHA (which made them invisible in the markdown).

**Comment by steveward** [comment]
@niclasmattsson thanks for the detailed and thoughtful writeup! We've been inundated with a lot of new issues recently, but we'll try to get back to you as soon as possible with a reply.

**Comment by niik** [comment]
> But I'll note that both `git checkout SHA` and `git checkout -b SHA` can be implemented [...] in the right-click context menu of the commit history.

Hey @niclasmattsson, just happened to stumble upon this issue today and I'm happy to say that this was added in https://github.com/desktop/desktop/pull/12160 which shipped in 2.9.0!

Thanks for your hard work writing up this issue!
