### ISSUE TITLE
Publish Branch Issue

### ISSUE THREAD

**Issue by pravin-sudhir** [desktop/desktop#10856]
### Error
![publish_error](https://user-images.githubusercontent.com/69452519/96334970-4ee78f00-1092-11eb-9cf1-d3fde88b1218.PNG)

The push operation includes a file which exceeds GitHub's file size restriction of 100MB. Please remove the file from history and try again.

**Comment by niik** [comment]
Hi @pravin-sudhir, that error message comes from GitHub.com which has a hard-limit for file sizes at 100mb. If you need to store files greater than 100Mb in Git please see [versioning large files](https://docs.github.com/en/free-pro-team@latest/github/managing-large-files/versioning-large-files). For more information about the 100Mb limit please see https://docs.github.com/en/free-pro-team@latest/github/managing-large-files/conditions-for-large-files for more information.
