### ISSUE TITLE
Icon for macOS Big Sur

### ISSUE THREAD

**Issue by yamatsum** [desktop/desktop#10855]
### Describe the feature or problem you’d like to solve
big sur has redesigned its icons and is beginning to change third-party applications to more friendly icons.
![image](https://user-images.githubusercontent.com/42740055/96327992-7120e300-1079-11eb-8bd9-5f4560b6f4c0.png)

### Proposed solution
I think github desktop should also support the new icon design specifications
https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/

### Additional context
Reference: Icons for other well-known third-party applications updated for big sur
- [iterm](https://gitlab.com/gnachman/iterm2/-/issues/8969) 
- [reader5](https://apps.apple.com/jp/app/reeder-5/id1529448980?mt=12) 
- [bartender4](https://www.macbartender.com/Bartender4/)

**Comment by niik** [comment]
Thank you so much for opening this @yamatsum, I'm going to tag @ampinsk here for when she's back after vacation and we'll see about finding some time to look at this.

**Comment by ampinsk** [comment]
This is something our internal creative team would likely work on, I just pinged them about it. I'll post if I have any updates from them on this!

**Comment by victor871129** [comment]
<img width="128" alt="desktop" src="https://user-images.githubusercontent.com/284717/97095716-a5bc0e00-1628-11eb-90ab-de92c0a8b744.png">

**Comment by janbrasna** [comment]
Just for reference there's some "fan fiction" macOS11–styled icons already out there, like:

![Screen Shot 2020-11-03 at 21 16 53](https://user-images.githubusercontent.com/1784648/98036360-301b2380-1e1a-11eb-8147-6cda5417e344.png)
— https://stijndv.com/goodies/big-sur-replacement-icons/  _(… & more at https://macosicons.com)_

which looks super sweet and extremely close to what the official icon should aim for, neumorphic-feel-wise: it has the right amount of depth, detail, color identity, elevation etc., matching other/official macOS 11 icons _(as compared to much simpler and flat iOS app icons, that shouldn't really be transposed for this desktop use)._

Here's the original resolution of the icon above:
![image](https://user-images.githubusercontent.com/1784648/97818784-c4fc1080-1ca4-11eb-8681-56ec3fa21756.png)

Fell in love instantly! 💟 
Not sure what direction the staff designers plan to go, but this octofeline treatment checks all the boxes for me, so just wanted to share…

**Comment by quanglam2807** [comment]
> Just for reference there's some "fan fiction" macOS11–styled icons already out there, like:
> 
> ![Screen Shot 2020-11-03 at 21 16 53](https://user-images.githubusercontent.com/1784648/98036360-301b2380-1e1a-11eb-8147-6cda5417e344.png)
> — https://stijndv.com/goodies/big-sur-replacement-icons/ _(… & more at https://macosicons.com)_
> 
> which looks super sweet and extremely close to what the official icon should aim for, neumorphic-feel-wise: it has the right amount of depth, detail, color identity, elevation etc., matching other/official macOS 11 icons _(as compared to much simpler and flat iOS app icons, that shouldn't really be transposed for this desktop use)._
> 
> Here's the original resolution of the icon above:
> ![image](https://user-images.githubusercontent.com/1784648/97818784-c4fc1080-1ca4-11eb-8681-56ec3fa21756.png)
> 
> Fell in love instantly! 💟
> Not sure what direction the staff designers plan to go, but this octofeline treatment checks all the boxes for me, so just wanted to share…

I also like this one. It's exactly the same as the current one, reshaping to follow macOS Big Sur guideline.

**Comment by JunyuKuang** [comment]
Would be nice if you could take the opportunity to match up (color scheme) to GitHub's iOS app.
<img width="560" alt="Screen Shot 2020-11-20 at 8 50 46 PM" src="https://user-images.githubusercontent.com/12454138/99802116-1431b480-2b72-11eb-8d0e-337920f64df2.png">

**Comment by ya2s** [comment]
@ampinsk 
When's the new icon going to be included in a release?

**Comment by niik** [comment]
@yamatsum We just shipped a production release yesterday so unless we need to get a hotfix out the next will likely be mid-January.

@tobiasahlin has been kind enough to help out with a new icon, I'll let him post what he's come up with when he's comfortable doing so but I'm excited!

**Comment by ya2s** [comment]
@niik 
v2.6.2 was released yesterday. I updated it, but the icon doesn't seem to change 🤔 
https://desktop.github.com/release-notes/

**Comment by jschneid** [comment]
Just dropped by to say that -- not having been aware that this change was coming -- I noticed the new macOS icon for GitHub Desktop, and I really like it! Nice work, @tobiasahlin!

**Comment by tobiasahlin** [comment]
Definitely mostly @ampinsk's work! ✨

**Comment by ghost** [comment]
I've just downloaded the desktop app for mac. New icon looks great
