### ISSUE TITLE
commit failed exit cdde 1 recieved

### ISSUE THREAD

**Issue by RosePinkDragon** [desktop/desktop#10869]
### Describe the bug

Commit is failing with exit code 1 github is taking wrong name for a folder.
Original Folder name : "Backend"
Folder name Git takes: "BBackend"
                                      
This bug does not apply to files it uploads the file in god knows where but not the actual folder.

### Version & OS

Version 2.5.6
Windows 10 Pro

### Steps to reproduce the behavior

1. See that the folder name has two same letters at the beginning
for eg: Backend becomes bbackend <- there is an extra b before the folder name in any case even changing the name wont help
1.Click on commit to master
2. See error

### Expected behavior

A push message to master

### Actual behavior

Error thrown
### Screenshots

![image](https://user-images.githubusercontent.com/59683036/96476096-72f1ce80-1252-11eb-8a69-3b4aea2c4017.png)

### Logs
[2020-10-19.desktop.production.log](https://github.com/desktop/desktop/files/5403161/2020-10-19.desktop.production.log)

### Additional context
It happens only for folders but not files

**Comment by steveward** [comment]
@RosePinkDragon thanks for the report. Did you rename the folder in File Explorer? I would recommend trying to rename it using this command to ensure Git tracks the changes correctly:

`git mv <old_name> <new_name>`

Then try committing again via GitHub Desktop. You can access the command line by going to `Repository` > `Open in <command_prompt>` if you aren't familiar with that.

**Comment by RosePinkDragon** [comment]
Yes i did try renaming the folder also i did that cmd thingy too

**Comment by steveward** [comment]
Thanks for the update. Could you try committing via the command line to see if that gives some further output? Here's how to do that:

1. Go to `Repository` > `Open in <command_line_app>`
2. Run the command `git add -A`
3. Run the command `git commit -m "your commit message"`

Let me know if that succeeds.

**Comment by MatthewLThomas** [comment]
Within that Backend folder, do you perhaps have a folder named .git nested inside of it? I did, and after deleting it, The issue was gone.

**Comment by RosePinkDragon** [comment]
yes i saw that in another issue and deleted the file still the same

**Comment by steveward** [comment]
@RosePinkDragon did you try committing via the command line by following the steps I gave?

**Comment by RosePinkDragon** [comment]
yes

**Comment by steveward** [comment]
@RosePinkDragon can you share whether or not that succeeded, and if it failed the specific output it gave?

**Comment by RosePinkDragon** [comment]
it works thank you love youuuuuuu. 
I just deleted the entire node_modules folder and also .git files 
Only kept my files along with the package.json file.
Created a separate folder named whatServer and added a .gitignore file to it.
Moved the folder into Frontend Folder. still doesnt work if its outside in the main folder 😢.
Went to terminal npm install.
Boom 🤯🤯 it works.
Everything worked as it should be.

Still dont know the problem but since it works, it works.

Thanks for the help and time you took. Appreciate it.
You can close the thread or reply back if you have any queries. Thank you ❤️😄.

**Comment by steveward** [comment]
I'm glad to hear that got things working for you!
