### ISSUE TITLE
Can't switch away from pull-request branch

### ISSUE THREAD

**Issue by toasterpic** [desktop/desktop#10867]
### Describe the bug

opening a pull request from github.com, then merging it on web, makes it impossible to switch away on Desktop.

### Version & OS

2.56 on MacOS 10.14.6.

### Steps to reproduce the behavior
see description

### Expected behavior

Desktop switches branch to selected one.

### Actual behavior

Current branch control animates then resets continually, only exiting the app stops it. Restarting keeps it on the original branch (not the one we asked to switch to).

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by toasterpic** [comment]
using git via CLI I noted the target branch was facing local changes overwrite in case of a successful switch (`error: Your local changes to the following files would be overwritten by checkout`)

**Comment by niik** [comment]
Thanks for the report! Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by toasterpic** [comment]
Enclosed

**Comment by niik** [comment]
@toasterpic that didn't seem to come through. If you tried attaching it as an email I don't think that'll work.

**Comment by toasterpic** [comment]
[2020-10-19.desktop.production.log](https://github.com/desktop/desktop/files/5401863/2020-10-19.desktop.production.log)

**Comment by niik** [comment]
@toasterpic Thank you so much. It appears this issue is the same as #9297. As per that issue, do you ever use `git update-index --assume-unchanged`?

**Comment by toasterpic** [comment]
I see. If at all, we use `git update-index --skip-worktree`.

**Comment by niik** [comment]
> I see. If at all, we use `git update-index --skip-worktree`.

That's super helpful @toasterpic. How do you normally resolve these kinds of problems on the command line then? Do you do a force checkout?

**Comment by toasterpic** [comment]
@niik Depends on context (as this would mean the setting is not applied on a collaborator's machine), but yes, force, stash, or commit.

**Comment by niik** [comment]
This was addressed in #10957 which is currently on beta and expected to make it into the next production release.
