### ISSUE TITLE
error pushing the repo

### ISSUE THREAD

**Issue by lucasan123** [desktop/desktop#10863]
### Describe the bug
i click on push origin

it gives this error

Impossibile trovare il percorso specificato.
error: unable to read askpass response from 'C:\Users\PC\AppData\Local\GitHubDesktop\app-2.5.6\resources\app\static\ask-pass-trampoline.bat'
fatal: could not read Username for 'https://github.com': terminal prompts disabled

### Version & OS
Version 2.5.6
windows 10

### Steps to reproduce the behavior
2. Click on 'push origin'
3. 

### Expected behavior

pushing repo
### Actual behavior

error

### Screenshots
![immagine](https://user-images.githubusercontent.com/28005324/96377600-efb77680-1186-11eb-8ece-0768f2b5a9f9.png)
![immagine](https://user-images.githubusercontent.com/28005324/96377617-0eb60880-1187-11eb-82dd-7884d9b797ad.png)

### Logs

[2020-10-18.desktop.production.log](https://github.com/desktop/desktop/files/5398038/2020-10-18.desktop.production.log)

**Comment by niik** [comment]
Hi @lucasan123, thanks for opening this. I'm sorry to hear you're having problems using GitHub Desktop. Please see https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789.

Please try following the instructions in that document and let us know if that doesn't work!
