### ISSUE TITLE
Limited SSD as C:

### ISSUE THREAD

**Issue by PBMCube** [desktop/desktop#10873]
### Describe the bug

I have a limited Solid State Drive as C:

### Version & OS

Windows 10 Pro

### Steps to reproduce the behavior

N/A

### Expected behavior

I want to install on a drive of my choice.

### Actual behavior

Defaults to C:

### Screenshots

N/A

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for contributing @PBMCube. Currently it is not possible to customize the installation location of GitHub Desktop. This is a constraint in the installation framework we use, Squirrel.Windows (see https://github.com/Squirrel/Squirrel.Windows/issues/1002). I'm sorry that I don't have better news for you at this time. My best recommendation would be to check out the portable installer a fellow GitHub Desktop user made:

https://github.com/daemondevin/GitHubDesktopPortable
