### ISSUE TITLE
Unable to split commits via rebase with 2.5.6

### ISSUE THREAD

**Issue by Personwithhat** [desktop/desktop#10880]
### Describe the bug

"RESOLVE MERGE CONFLICTS" dialog -> No conflicts to resolve -> Unable to commit. 
May only continue rebase.

### Version & OS

2.5.6, Windows 10 desktop.

### Expected behavior

git rebase -i XXX
Edit a commit
git reset --soft ID_BEFORE_COMMIT
Select different files and commit separately (split commit into several)

### Actual behavior

git rebase -i XXX
Edit a commit
git reset --soft ID_BEFORE_COMMIT

"RESOLVE MERGE CONFLICTS" dialog -> No conflicts to resolve -> Unable to commit. 
May only continue rebase.

**Comment by niik** [comment]
This sounds like the exact same problem as described in https://github.com/desktop/desktop/issues/10460 so I'm going to close this issue in favor of that and ask that you subscribe to it for any updates.

Please see https://github.com/desktop/desktop/issues/10460#issuecomment-694301036 for an explanation of what changed.
