### ISSUE TITLE
Error with lint-staged and globally installed package manager

### ISSUE THREAD

**Issue by zygimantas** [desktop/desktop#10885]
### Describe the bug

I am describing this as a bug, but honestly, I have no idea if it's a real bug, or some misconfiguration on my machine.
I can't use lint-staged in my project because Github Desktop throws this error:

```
Commit failed - exit code 1 received, with output: '/c/Users/zygim/AppData/Roaming/npm/yarn: line 5: cygpath: command not found
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'C:\Users\zygim\AppData\Local\GitHubDesktop\app-2.5.6\resources\app\git\node_modules\yarn\bin\yarn.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}'
```

My lint-staged configuration is:

```
module.exports = {
    '*.{js,ts}': 'yarn run eslint',
}
```

**It works as expected if I use `git` cli.**
It looks like Github Desktop does not search for global packages and try to use local instead.

### Version & OS

Github Desktop:         2.5.6
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041
Node:                         v14.4.0
Npm:                          7.0.2 (the same is with older)
Yarn:                            1.22.10 (the same is with 2.x)

### Expected behavior

Globally installed `yarn` is used.

### Actual behavior

An error, described above.

### Additional context

The workaround was to use `npm` instead of `yarn` (which is not an option now because of other issues) and set the lint-staged config to:

```
module.exports = {
    '*.{js,ts}': 'npx eslint',
}
```

**Comment by steveward** [comment]
@zygimantas thanks for the report. Can you try launching GitHub Desktop via the `github` command from the command line? That should force it to inherit your correct environment.

**Comment by zygimantas** [comment]
I've tried launching GitHub Desktop via the `github` command and the issue is the same.

**Comment by zygimantas** [comment]
The fix was `rm -f .git/hooks/*` and `yarn add husky --dev`
