### ISSUE TITLE
View on Github (Ctrl Shift G) doesn't work 

### ISSUE THREAD

**Issue by HeikoNoeldeke** [desktop/desktop#10892]
### Describe the bug

Weather the shortcut (Ctrl Shift G) nor the link in the Repository menue works at my current Repository. It is greyed out.

### Version & OS

Version 2.5.6 @ Windows 10

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Go to 'Repository'
2. Click on 'View on GitHub'
3. nothing happens
### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the report @HeikoNoeldeke. Is your repository in the `Other` category? If not can you verify it has a valid remote URL in `Repository` > `Repository Settings` > `Remote`?
