### ISSUE TITLE
Add a filter textbox to filter down the changed files

### ISSUE THREAD

**Issue by ebicoglu** [desktop/desktop#10902]
### Describe the feature or problem you’d like to solve

Add a filter textbox to filter the changed files.

### Proposed solution

When I want to see changes in a specific file, it's hard to scroll down to the corresponding file. A filter textbox will ease this.

### Additional context

![](https://user-images.githubusercontent.com/9526587/96869897-cb0a1a00-1478-11eb-83af-80e144117f15.png)

**Comment by niik** [comment]
Hi @ebicoglu, thanks for opening this. Seems like this is the same as #6407 so I'm going to refer you there and ask that you subscribe to that issue for any updates, thanks!
