### ISSUE TITLE
Turn off Usage Stats through Registry or other locations NOT in the app itself? 

### ISSUE THREAD

**Issue by Emeraldplum** [desktop/desktop#10906]
is there a way to turn off usage statistics through the registry or through command line for GitHub Desktop? Been looking and can't seem to find anything. 

I know you can turn it off manually through File > Options. I'm trying to script an install to run the install silently and want to be sure that usage data is off after the script runs.

**Comment by billygriffin** [comment]
Hi @Emeraldplum, thanks for the feedback! This isn't something we enable, but as you mentioned you can easily turn it off during the welcome flow or anytime thereafter within the app. Sorry it's not exactly what you're looking for but we don't plan to implement additional ways to do that.
