### ISSUE TITLE
Allow Users to add issues from github desktop

### ISSUE THREAD

**Issue by Perezari** [desktop/desktop#10901]
hello,
i will be happy if you will add a user form to add issues from github desktop and not from web.
its will be cool!
thank you!

**Comment by steveward** [comment]
Thanks for the feedback @Perezari. This has been previously discussed in https://github.com/desktop/desktop/issues/8989. Currently we don't have any plans to implement this but I would recommend following along in that issue for any updates. Thanks for using GitHub Desktop!
