### ISSUE TITLE
add ability to check out a tag

### ISSUE THREAD

**Issue by gilmoskowitz** [desktop/desktop#10907]
### Describe the bug

There does not seem to be a way to check out a repository's contents at a tag.

### Version & OS

GitHub Desktop v2.5.6 on macOS (Catalina, 10.15.7). A colleague sees similar behavior on Windows, unknown client version.

### Steps to reproduce the behavior

1. Go to 'View > Show History'
2. Scroll down in the History list to a commit marked with a tag
3. Right click on that commit
4. *Note that there is no option to check out the repository at this tag*

Trying a different approach:
5. Click on the Current Branch at the top-center of the desktop client window
6. *Note that one can choose from a number of branches or pull requests but not tags*

### Expected behavior

- The GitHub Desktop client should provide a list of tags, distinct from the list of branches and commits
- It should be possible to check out the tagged code

### Actual behavior

- Switching to the head of a branch looks easy
- Reverting commits looks easy
- Finding tags is hard and requires knowing which branches were tagged

### Screenshots

<img width="642" alt="GitHub_Desktop_History_rightclick" src="https://user-images.githubusercontent.com/704111/97033124-d3259080-1530-11eb-82e7-b5f4290333c8.png">
<img width="742" alt="GitHub_Desktop_Current_Branch" src="https://user-images.githubusercontent.com/704111/97033134-d882db00-1530-11eb-9319-e22bdd823604.png">

### Logs

N/A

### Additional context

At least three common tasks would benefit from this:

- Generate documentation for a tagged release
- Reproduce a bug
- Check out the baseline code from which to create a branch, perhaps for a bug-fix release

**Comment by steveward** [comment]
Thanks for the feedback and for sharing your specific use cases @gilmoskowitz. This was brought up in https://github.com/desktop/desktop/issues/4829, but I'll leave this open since that issue is closed out now that we have implemented basic tag functionality. Checking out arbitrary commits in a repository's history was just brought up in https://github.com/desktop/desktop/issues/10858, and is similar to what you are requesting here.

**Comment by billygriffin** [comment]
Hi @gilmoskowitz, thanks for your issue! Since we shipped the ability to create a branch from a previous commit, I think that solves this use case sufficiently to close the issue. Hopefully that helps meet your needs!

**Comment by DegrangeM** [comment]
We still need a way to list tags. If there is a lost of commits, it's gonna be difficult to find the tag we want.
