### ISSUE TITLE
@SafNaaz Thank you for the suggestion. As you are the first to request this please share more about the request. For example, a user might need one editor to develop a game app, one mandated by their job and one for personal projects. If so, I could see how switching would be tiresome. I'd appreciate any thoughts you could share.

### ISSUE THREAD

**Issue by ahhydo** [desktop/desktop#10911]
@SafNaaz Thank you for the suggestion. As you are the first to request this please share more about the request. For example, a user might need one editor to develop a game app, one mandated by their job and one for personal projects. If so, I could see how switching would be tiresome. I'd appreciate any thoughts you could share.

_Originally posted by @tierninho in https://github.com/desktop/desktop/issues/10321#issuecomment-668730841_

**Comment by SafNaaz** [comment]
@ahhydo since we can checkout from GitHub and gist, please make sure that default selection of editor for gist repository is notepad++. Atleast
