### ISSUE TITLE
add search to changes files

### ISSUE THREAD

**Issue by hadeel-** [desktop/desktop#10925]
### Describe the feature or problem you’d like to solve

Hi, I'm using windows app, and when I want to check what changes made for a file I have to scroll all changes to find it.
so I think it's very helpful if we have search textbox on top of changes files list

### Proposed solution

this will save time to search for a file within changes

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by niik** [comment]
Hi @hadeel-, thanks for opening this! Seems like this is the same as #6407 so I'm going to refer you there and ask that you subscribe to that issue for any updates, thanks!
