### ISSUE TITLE
Unable to clone repository - 502 error

### ISSUE THREAD

**Issue by lsoukup** [desktop/desktop#10929]
I have tried many "workarounds" but have gotten to this point.  I believe something has changed on my anitvirus software, but can't pinpoint what it is.  Please see the command I am trying to run and the config settings I currently have:

PS C:\Users\LSOUKUP>  git clone https://lindsay.soukup%40oracle.com@alm.oraclecorp.com/pditcas/s/pditcas_caes-content-experience-cloud_10162/scm/keystone.git
Cloning into 'keystone'...
fatal: unable to access 'https://lindsay.soukup%40oracle.com@alm.oraclecorp.com/pditcas/s/pditcas_caes-content-experience-cloud_10162/scm/keystone.git/': The requested URL returned error: 502
PS C:\Users\LSOUKUP> git config --show-origin -l
file:"C:\\ProgramData/Git/config"       core.symlinks=false
file:"C:\\ProgramData/Git/config"       core.autocrlf=true
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:C:/Program Files/Git/mingw64/etc/gitconfig http.sslbackend=openssl
file:C:/Program Files/Git/mingw64/etc/gitconfig http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/mingw64/etc/gitconfig http.sslcapath=C:\Program
file:C:/Program Files/Git/mingw64/etc/gitconfig http.sslcapath=C:\Program
file:C:/Program Files/Git/mingw64/etc/gitconfig http.sslcapath=C:/Program
file:C:/Program Files/Git/mingw64/etc/gitconfig credential.helper=manager
file:C:/Users/LSOUKUP/.gitconfig        filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/LSOUKUP/.gitconfig        filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/LSOUKUP/.gitconfig        filter.lfs.process=git-lfs filter-process
file:C:/Users/LSOUKUP/.gitconfig        filter.lfs.required=true
file:C:/Users/LSOUKUP/.gitconfig        user.name=Lindsay Soukup
file:C:/Users/LSOUKUP/.gitconfig        user.email=lindsay.soukup@oracle.com
file:C:/Users/LSOUKUP/.gitconfig        http.proxy=http://www-proxy.us.oracle.com:80
file:C:/Users/LSOUKUP/.gitconfig        http.sslverify=false
file:C:/Users/LSOUKUP/.gitconfig        http.sslbackend=schannel
file:C:/Users/LSOUKUP/.gitconfig        http.schannelcheckrevoke=false

**Version & OS**

git version 2.21.0.windows.1
Windows 10 Pro Version 10.0.18363 Build 18363

**Comment by steveward** [comment]
@lsoukup this issue tracker is specifically for GitHub Desktop. If you are having issues with your GitHub Enterprise account I would recommend reaching out to [GitHub Enterprise Support](https://enterprise.github.com/support). It looks like there is an issue with your proxy, so it may be worth reaching out to your GitHub Enterprise administrator or someone else in your organization to ensure things are configured correctly. I hope that helps!
