### ISSUE TITLE
View all stashes on a branch

### ISSUE THREAD

**Issue by CodeTroopers** [desktop/desktop#10926]
### Describe the feature or problem you’d like to solve

Github deskstop show only the last stash on the current branch

### Proposed solution

It would be nice to display all stashes on the current branch and let the user select which to restore

**Comment by billygriffin** [comment]
Hi @CodeTroopers, this was an explicit design choice that we made after talking with lots of folks and trying to figure out the most common use cases. I know that for people who keep around a lot of stashes it can be annoying and doesn't quite fit with that workflow, but we found that the simpler approach of people being most likely to care about the most recent stash for a branch makes things clearer. Thanks for the feedback!

**Comment by CodeTroopers** [comment]
It could be a second choice : by default propose only the most recent stash and in an advanced mode propose all stashes.
