### ISSUE TITLE
'Git could not be found at the expected path' and 'Failed to execute getStatus: ENOENT'

### ISSUE THREAD

**Issue by ipython3** [desktop/desktop#10921]
### Describe the bug

Encountered this issue today when I start the app.

It says:
`Git could not be found at the expected path: 'C:\Users\lenovo\AppData\Local\GitHubDesktop\app-2.5.6\resources\app\git\cmd\git.exe'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.`

I clicked 'close' and then it keep saying:
`Failed to execute getStatus: ENOENT`

And 'can't find' all the repositories, while they are still there.
![屏幕截图 2020-10-27 002248](https://user-images.githubusercontent.com/31297905/97199354-e2376780-17ea-11eb-9cc6-3eea508daf41.png)

I'm sure that I didn't touch anything in 'C:\Users\lenovo\AppData\Local\GitHubDesktop\' today and the app works fine this morning.

### Version & OS

Version: 2.5.6
OS: Windows 10 Version 2004

### Steps to reproduce the behavior

1. Start the app.

### Logs

[2020-10-26.desktop.production.log](https://github.com/desktop/desktop/files/5439994/2020-10-26.desktop.production.log)

**Comment by steveward** [comment]
@ipython3 thanks for the report. We're tracking this issue in https://github.com/desktop/desktop/issues/9604.

Often a fresh install will get things working. Here's how to do that:

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `%AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that does not get things working.

**Comment by ipython3** [comment]
Fresh install works. Thank you! @steveward

**Comment by saleh1100** [comment]
`**_[g](https://stadia.com/link/?link=https://stadia.google.com/player/a4c5eb3f4e614b7fadbba64cba68f849rcp1?fallback_sku%3D480a6d783c834b9faa5c995f69b49431%26link_id%3D8517360941251284199&apn=com.google.stadia.android&amv=15113&isi=1471900213&ibi=com.google.stadia&st=PlayerUnknown%27s+Battlegrounds+-+Payback+Edition&si=https://ssl.gstatic.com/stadia/gamers/assets/stadia_logo_and_text_v1.jpg&cid=1601959530215184629&_osl=https://stadia.com/link/HR7G3nYXi9uRJQMX9?_iipp%3D1&_iipp=1&_icp=1)_**`
