### ISSUE TITLE
Add keyboard shortcut for switching current branch

### ISSUE THREAD

**Issue by cheshire137** [desktop/desktop#10920]
### Describe the feature or problem you’d like to solve

I'd like a keyboard shortcut to switch the active branch in my current repository. I use Cmd-T occasionally to switch which repository I'm on, but I switch branches more frequently than I do repositories. I don't know of a keyboard shortcut to open the branch filter, so I end up clicking it. My goal is to be able to stay entirely on the keyboard for bringing up the branch filter, typing in an approximation of a branch name that exists, using arrow keys to choose which branch I meant from a list of actual branches, and hitting Enter to make that my active branch.

![image](https://user-images.githubusercontent.com/82317/97194811-94821700-1778-11eb-86e9-09cefcf66991.png)

### Proposed solution

In my editor, I use Cmd-T to switch files and Cmd-R to jump to a method within the current file. It looks like Cmd-R is already taken in Desktop to show the pull request for the current branch. Maybe another shortcut, like Cmd-Shift-T, could be used for bringing up the branch filter. If you were open to reassigning shortcuts, I would prefer Cmd-T toggle the branch filter and a separate shortcut toggle the repository switcher.

**Comment by niik** [comment]
Hey @cheshire137, I believe we already have <kbd>Cmd</kbd><kbd>B</kbd> assigned for this purpose

![image](https://user-images.githubusercontent.com/634063/97195588-d0829f80-17ab-11eb-8aa9-443db108fcef.png)

Could you try it and see if that works for your use case?

> If you were open to reassigning shortcuts, I would prefer Cmd-T toggle the branch filter and a separate shortcut toggle the repository switcher.

Reassigning is something we've tried to stay away from as it causes a lot of disruption for people who've already committed a keyboard combination to muscle memory.

**Comment by cheshire137** [comment]
Easiest issue close ever! 😆 Cmd-B is exactly what I need, thank you! I didn't see the option because I was looking in the Branch menu for something like "Switch branch", "Filter branches", or "Change active branch":

![image](https://user-images.githubusercontent.com/82317/97196350-5ede2d80-177a-11eb-8d80-f74679dd2344.png)

I see it's under the View menu:

![image](https://user-images.githubusercontent.com/82317/97196395-6b628600-177a-11eb-8a91-27a1e13578cd.png)

What do you think about surfacing it under the Branch menu as well?

> Reassigning is something we've tried to stay away from as it causes a lot of disruption

Definitely, I thought that might be the case. Thanks!

**Comment by niik** [comment]
> What do you think about surfacing it under the Branch menu as well?

We've been trying to follow the platform conventions when it comes to menu organization and I'm not aware of an existing pattern to duplicate items across top-level menus on macOS. I could certainly be mistaken though, examples are much appreciated.

It's undoubtedly the case that we could do a better job of discoverability within the app as a whole. That's something we're looking into potential solutions for but not an immediate priority. The lovely docs team do maintain a list of common shortcuts at https://docs.github.com/en/free-pro-team@latest/desktop/installing-and-configuring-github-desktop/keyboard-shortcuts and that document can be found from the help menu in the app as well.

I'm going to close this as the original issue here is addressed and because our gut reaction is to not duplicate the menu item.

**Comment by cheshire137** [comment]
> I'm not aware of an existing pattern to duplicate items across top-level menus on macOS. I could certainly be mistaken though, examples are much appreciated.

One example is in Safari for showing Bookmarks:

![image](https://user-images.githubusercontent.com/82317/97372301-51f83180-1881-11eb-9602-fea882e35d99.png)

![image](https://user-images.githubusercontent.com/82317/97372309-5a506c80-1881-11eb-9d54-6ddd7284e765.png)

Both of these options show the bookmarks sidebar. When I use View > Show Bookmarks Sidebar, then Bookmarks > Show Bookmarks changes to Bookmarks > Hide Bookmarks. When I use Bookmarks > Show Bookmarks, then View > Show Bookmarks Sidebar becomes View > Hide Bookmarks Sidebar.

**Comment by niik** [comment]
That's a great example @cheshire137, thank you.

I wonder if us having that duplicate item would have improved the discoverability of the keyboard shortcut in this scenario though.

Given that we can only use the keyboard accelerator for one of the menu items (just like Safari) I wonder if it could actually end up making it worse by making users stop searching for the "actual" menu item once they find it under the "branch" menu without an accelerator.
