### ISSUE TITLE
We couldn't find that repository. Check that you are logged in, the network is accessible, and the URL or repository alias are spelled correctly.

### ISSUE THREAD

**Issue by AngeloSolusys** [desktop/desktop#10930]
Describe the bug
When cloning a repository (Note that repository is correct), it keeps getting an error. Error will be: We couldn't find that repository. Check that you are logged in, the network is accessible, and the URL or repository alias are spelled correctly.

Version & OS
Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

Version 2.5.6 and Windows 10.0.19042

Steps to reproduce the behavior
Go to 'Github Desktop'
Click on 'Your Repositories'
Click the 'Clone Repository'
Type in your 'URL or username/repository'
Click 'Clone'
See Error

Expected behavior
Get the repository cloned.

Actual behavior
When clicking on the Clone it keeps getting the Error: We couldn't find that repository. Check that you are logged in, the network is accessible, and the URL or repository alias are spelled correctly.

Screenshots

![image](https://user-images.githubusercontent.com/72274746/97336727-15670e80-185e-11eb-918a-689005429581.png)

Logs
[2020-10-27.desktop.production.log](https://github.com/desktop/desktop/files/5446879/2020-10-27.desktop.production.log)

Additional context

**Comment by steveward** [comment]
@AngeloSolusys thanks for the report. If you go to the `GitHub.com` tab is the repository visible there? Have you tried cloning any other repositories?

**Comment by AngeloSolusys** [comment]
> @AngeloSolusys thanks for the report. If you go to the `GitHub.com` tab is the repository visible there? Have you tried cloning any other repositories?

Yes, when I log on  `GitHub.com` the repository is there.
When I tried to clone other  repository worked ok

![image](https://user-images.githubusercontent.com/72274746/97433317-12baf680-18fc-11eb-91bf-6aa6b11b02e3.png)

Log File today:
[2020-10-28.desktop.production.log](https://github.com/desktop/desktop/files/5451673/2020-10-28.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the update @AngeloSolusys. Can you try cloning the repository via the command line (`git clone <repo_URL>`) to see if that succeeds? I

**Comment by niik** [comment]
This sound very similar to #10923 and I'm starting to suspect this could have something to do with https://github.com/desktop/desktop/pull/7634.

@AngeloSolusys Was the repository in question deleted or renamed at any point in the past?

**Comment by AngeloSolusys** [comment]
> This sound very similar to #10923 and I'm starting to suspect this could have something to do with #7634.
> 
> @AngeloSolusys Was the repository in question deleted or renamed at any point in the past?

Actually yes. I was making some tests and I created the repository Monitor, uploaded some files and then deleted it, after that I created another repository with the same name, uploded some files again and then deleted it again. I've done that about 3 or 4 times, (I can't remebem exactly how many times) in about 1 hour, the first times I was able to clone it but then in some point I couldn't clone the repository anymore using github desktop.

I tried to clone it using the command line and it worked.
![image](https://user-images.githubusercontent.com/72274746/97565010-42cdcc80-19c4-11eb-9112-905b5e4ac06f.png)

**Comment by Far-cpu** [comment]
Vivo

**Comment by TheNewJavaman** [comment]
I have the exact same issue. This is probably a duplicate of #10923

**Comment by Andre601** [comment]
I face the same issue when trying to clone the wiki of a GitHub Repository.
The repository in question however, was never deleted, renamed or similar.

The logs also don't mention anything about a failed cloning or the repository in question.
[2020-11-07.desktop.production.log](https://github.com/desktop/desktop/files/5505106/2020-11-07.desktop.production.log)

**Comment by nte93** [comment]
為何會如此該#10930如是桌面該是其他

**Comment by bryx** [comment]
Hey, I also encounter the same blockage. Whether I make the project public or private, it doesn't change anything. On the other hand, via Visual Studio Code no problem for cloning.

**Comment by steveward** [comment]
>I face the same issue when trying to clone the wiki of a GitHub Repository.
The repository in question however, was never deleted, renamed or similar.

@Andre601 there are some known issues working with wikis. See https://github.com/desktop/desktop/issues/3839. If you are running into specific authentication issues please open a new issue and we can assist you further.

@bryx it would be helpful if you could open a new issue and fill out the issue template. Thanks!

**Comment by CaptainJackey** [comment]
You can completely remove github desketop from you PC and install again, remember don't forget to delete Residual file!!! 

![1](https://user-images.githubusercontent.com/42539086/100264591-fc9b6700-2f89-11eb-9d2c-6fcc349de5cf.png)

Then it can be solved.

**Comment by AngeloSolusys** [comment]
But I believe it's better to find and solve the problem than try to find ways to hide the problem, cause cloning the repository in other ways is easy, I already have done that. i just reported the problem for it to be resolved.

**Comment by abdullahyildiz** [comment]
I also have the same problem. Signing out from my account and then logging in didn't help.
I use GitHub Desktop for macOS Version 2.6.1.

**Comment by Th-eo** [comment]
Use Git GUI to clone it, then "Add local repository" from GitHub Desktop to circumvent this issue.

**Comment by AngeloSolusys** [comment]
Well, if it's the case i'm closing the issue cause i've already got what i need, but the problem remains on the app

**Comment by dmauro** [comment]
I'm having this problem as well. Suddenly today on Windows I stopped being able to authenticate via command line using a PAT (though it still works on macOS and it worked that last time I was on Windows with no changes).

**Comment by steveward** [comment]
@dmauro this issue tracker is for GitHub Desktop. For Git authentication issues I'd recommend reaching out to [GitHub Support](https://support.github.com/).

**Comment by AndreasTraut** [comment]
> 
> 
> You can completely remove github desketop from you PC and install again, remember don't forget to delete Residual file!!!
> 
> ![1](https://user-images.githubusercontent.com/42539086/100264591-fc9b6700-2f89-11eb-9d2c-6fcc349de5cf.png)
> 
> Then it can be solved.



> 
> 
> You can completely remove github desketop from you PC and install again, remember don't forget to delete Residual file!!!
> 
> ![1](https://user-images.githubusercontent.com/42539086/100264591-fc9b6700-2f89-11eb-9d2c-6fcc349de5cf.png)
> 
> Then it can be solved.

I had the same problem as described above. Seems to be similar to [#10923](https://github.com/desktop/desktop/issues/10923) [#7634](https://github.com/desktop/desktop/pull/7634) and other issues. Thank you @CaptainJackey : your advice solved my problem. I wish I would have found a more "elegant" solution, but de-install, re-install is probably the easiest one for a novice like me.

**Comment by NounKim** [comment]
Good. Fast and Easy,

**Comment by dmillar1** [comment]
I just had the same problem with the latest GitHub Desktop 3.0 and manually solved it following the advice from @CaptainJackey. This is an active bug and shouldn't be marked as closed.

**Comment by hbabashah** [comment]
Same Issue, I just completely uninstall and install it again as suggested and it worked!
Thanks

**Comment by chadmkidner** [comment]
Fresh GitHub Desktop install and having this issue still.

**Comment by StellaWava** [comment]
@AndreasTraut guide worked for me.

Thank you!

**Comment by Quinienl** [comment]
Error still exist on Mac. After reinstall User and Pass is ask for the repo but still not getting in. Other repos clone without problem. New repo won't

**Comment by tuqa7** [comment]
make it public it worked for me

**Comment by matheusdinizdev** [comment]
@Quinienl 
I was having the same error, it worked on my macOS and my Windows after I logged out and logged back into my Github desktop account.
You go to File -> Options -> Account.

**Comment by vennells** [comment]
> 

This worked for me. Thank you

**Comment by vennells** [comment]
> @Quinienl I was having the same error, it worked on my macOS and my Windows after I logged out and logged back into my Github desktop account. You go to File -> Options -> Account.

This worked for me. Thank you

**Comment by RBnzr** [comment]
>  @Quinienl I was having the same error, it worked on my macOS and my Windows after I logged out and logged back into my Github desktop account. You go to File -> Options -> Account.


I had the same issue. ^this worked for me. Thanks

**Comment by ThyagoMartins0** [comment]
Iae pessoal, tudo certo ?, estava com o mesmo problema( S.O WINDOWS)
Solução:: desinstalei, apaguei os arquivos adicionais e reinstalei

funcionou de boas

**Comment by bhu619** [comment]
> @Quinienl I was having the same error, it worked on my macOS and my Windows after I logged out and logged back into my Github desktop account. You go to File -> Options -> Account.

I also solved this problem by re-logging in, thank you very much!
