### ISSUE TITLE
Please give a label also which will be showing how many files I have selected for committing!

### ISSUE THREAD

**Issue by ErVishalMWFX** [desktop/desktop#10938]
Hi, I am using github desktop and it is super fast and very well created but there should be a label also which will be showing how many files I have selected for committing.

Ex - 29 Files I have changed but I want to commit only 1 file so when I select files, no where showing that how many files I have selected.  I have uploaded one image for example.
![image](https://user-images.githubusercontent.com/69079339/97530051-4454c000-19d7-11eb-9267-af85052e1709.png)

So a label can be added with **29 Changed Files** that **1 File Selected** It will be very helpful for each user.

Thanks.

**Comment by niik** [comment]
Hey, thanks for reaching out! This looks very similar to the request in https://github.com/desktop/desktop/issues/8776 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date with any development happening in that area!
