### ISSUE TITLE
A way to discriminate between local repositories pointing to the same github repo

### ISSUE THREAD

**Issue by brouwert** [desktop/desktop#10933]
### Describe the feature or problem you’d like to solve

Currently when you have checked out the same github repo in different directories they all have the same name in the list of repositories, even if they are on a different branch.

![image](https://user-images.githubusercontent.com/7447695/97407050-69273580-18fa-11eb-8f5e-855754a3eab6.png)

### Proposed solution

Show the branch or the directory name in the list where the repo's are checked out.

**Comment by steveward** [comment]
Thanks for the feedback @brouwert. We're tracking this in https://github.com/desktop/desktop/issues/1929. You can follow along there for updates.
