### ISSUE TITLE
Push origin - unable to authenticate with my Github username/password

### ISSUE THREAD

**Issue by slsu0424** [desktop/desktop#10945]
### Describe the bug

When I try to push a change to the origin to my web-based GitHub repo, I am unable to get past the authentication step.  I input my username (email) and password I had set up with GitHub.  Note this is not an enterprise account.

### Version & OS

GitHub Desktop Version: 2.5.6
OS: Windows 10

### Steps to reproduce the behavior

1. Go to 'Push commits to the origin remote'
2. Click on 'Push Origin'
3. See error 'Authentication Failed'
4. Input Username & Password
5. See error 'Authentication Failed'

### Expected behavior

I expect that I am able to push my change to the origin remote.  The origin remote is: https://github.com/slsu0424/r-server-hospital-length-of-stay.git

### Actual behavior

System is unable to authenticate my username and password

### Screenshots

See attached screenshot
![Screenshot 2020-10-30 115122](https://user-images.githubusercontent.com/25472516/97727029-46398480-1aa6-11eb-82a5-9c804ae5e500.jpg)

### Logs

Logs are attached
[2020-10-30.desktop.production.log](https://github.com/desktop/desktop/files/5466150/2020-10-30.desktop.production.log)

### Additional context

No other context

**Comment by steveward** [comment]
Thanks for the report @slsu0424. Could you try logging out and then logging back by going to `File` > `Options` > `Accounts`? It looks like there is an issue with your cached credentials:

```
2020-10-30T14:19:11.635Z - error: [ui] Failed to look up canonical clone url for 'https://github.com/microsoft/r-server-hospital-length-of-stay.git'
Error: Bad credentials
```

**Comment by slsu0424** [comment]
Yes this resolved the issue.
