### ISSUE TITLE
Changing font size can be helpful

### ISSUE THREAD

**Issue by burakgunduztr** [desktop/desktop#10955]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
Thanks for reaching out @burakgunduztr !

If you are wanting to increase the font size you can go to `View` > `Zoom In`. If I'm misunderstanding your request please fill out the template and bump this issue with a reply. Thanks for using GitHub Desktop!
