### ISSUE TITLE
Blank screen; have to edit source code.

### ISSUE THREAD

**Issue by Splatterxl** [desktop/desktop#10952]
### Describe the bug

GitHub Desktop opens with a blank screen and I have to manually edit the source code.

### Version & OS

Windows NT 10, build 1909
It happens every time I update.

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. See error

### Expected behavior

GitHub Desktop just opens as normal.

### Actual behavior

A blank screen with no UI, close or minimize buttons or ANYthing opens up.

However, I can open DevTools.

### Screenshots

No need, it's just a blank screen.

### Logs

N/A Can't open HELP menu.

### Additional context

__Edit__: I fix the problem now, by going in to the main file and changing 
```js
module.exports = functi on {
...
}
```
to
```js
module.exports = function {
...
}
```
but I'd like to know how that error occurs anyway.

**Comment by niik** [comment]
Hey @Splatterxl

> but I'd like to know how that error occurs anyway.

Yeah, so would we. This is not something we've heard of before so I have to assume it's due to some aspect of your environment. Do you have any anti-virus software installed or other tools that could end up modifying files on disk? Is this your own machine or a company- issued one? Are you using any web proxy that could interfere?

**Comment by Splatterxl** [comment]
Hey @niik,

I only have AVG Antivirus, and that  is set not to scan my downloaded files.

I do not have any other tools or proxy and it is my own computer.

**Comment by Splatterxl** [comment]
hey wait a second i updated and it didn't happen just now

**Comment by steveward** [comment]
@Splatterxl I'm glad to hear things seem to be resolved now. Let us know if you run into any further issues.
