### ISSUE TITLE
Can't create new repository inside GitHub folder

### ISSUE THREAD

**Issue by zfett** [desktop/desktop#10960]
### Describe the bug

I cannot create a new repository in the GitHub folder, or any folder for that matter. It keeps notifying me that my current folder is already a Git repository and will not let me create a new repo. When I try to switch to a completely different folder, for example, my Photos folder, I get the same error as shown in the attached screenshots:  

[Screenshot 1](https://user-images.githubusercontent.com/21271081/97938746-347b0a00-1d50-11eb-9d19-4c091bcdb0e2.png)  
[Screenshot 2](https://user-images.githubusercontent.com/21271081/97938774-48267080-1d50-11eb-89f2-90b59561b311.png)
[Screenshot 3](https://user-images.githubusercontent.com/21271081/97939077-1f52ab00-1d51-11eb-9f2d-f8b19985567e.png)

### Version & OS

GitHub Desktop: Version 2.5.6  
Git: Version 2.27.0.windows.1  
Windows: Windows 10 Home, Version 2004, Build 19041.572  

### Steps to reproduce the behavior

1. Go to File > New repository or use Ctrl+N.
2. When the window pops up, no matter what directory your new repository is set to, it will display the error shown in screenshot 3.
3. Try to input the information for your new repository, but fail in creating it because the "create repository" button will be forever disabled.

### Expected behavior

I should be able to create a new repository from the Desktop app, inside my default GitHub repository folder, with no issues.

### Actual behavior

I cannot create a new repository from the app due to the flow of operation being stopped because the app thinks that every folder is a repository folder, even if no repository has ever been cloned or created in that folder before.

### Screenshots

![Screenshot 1](https://user-images.githubusercontent.com/21271081/97938746-347b0a00-1d50-11eb-9d19-4c091bcdb0e2.png)  
![Screenshot 2](https://user-images.githubusercontent.com/21271081/97938774-48267080-1d50-11eb-89f2-90b59561b311.png)
![Screenshot 3](https://user-images.githubusercontent.com/21271081/97939077-1f52ab00-1d51-11eb-9f2d-f8b19985567e.png)

### Logs

https://pastebin.com/XsmYcxxL
or...
https://gist.github.com/zfett/559a78acba330b8acdede9fb32dd1379

**Comment by steveward** [comment]
Thanks for the report @zfett. Are there possibly any Git repositories in higher-level directories that could be causing this? We've seen cases where repositories mistakenly get initialized in the root user folder and cause this behavior.

**Comment by zfett** [comment]
@steveward There are no high-level repos or Git directories anywhere on my computer other than the GitHub folder that I know of, but let me check later today to be sure.

**Comment by zfett** [comment]
Sorry for the wait, I just checked every folder from my GitHub one up, and found no Git repos, or remnants of Git files in them.

**Comment by zfett** [comment]
I don't know what has happened, since I just opened GitHub desktop, but I can now create a repo where I wanted to before. I'll upload my logs but I honestly don't know what has changed.

I no longer get the error I had before, and I can now create a repo. As far as I can see, I see no changes in either the app nor my computer.

Thanks anyway guys!

[2020-11-03.desktop.production.log](https://github.com/desktop/desktop/files/5484744/2020-11-03.desktop.production.log)
