### ISSUE TITLE
Long named branches to break into another line

### ISSUE THREAD

**Issue by vinnom** [desktop/desktop#10962]
### Describe the feature or problem you’d like to solve
Long named branches just collapses into "..."

### Proposed solution
Long named branches on browser breaks into another line, which makes it easier to read (even if github-desktop displays the full name when hovering the cursor over the branch name). Maybe this could be applied to the "Current branch" box too - or make them resizable.

### Additional context

How it's on browser (and how I think it should be on desktop too)
![Captura de tela de 2020-10-30 09-21-53](https://user-images.githubusercontent.com/11577103/98062369-a6c11c80-1e2c-11eb-976e-50e803e04610.png)

Here I just show where I think it should be applied (both on "current branch" box and on the drop-down list of branches) - be it a resizing option or breaking the names on another line
![Captura de tela de 2020-10-30 09-15-40](https://user-images.githubusercontent.com/11577103/98062372-a7f24980-1e2c-11eb-9011-fbe955e41b76.png)

EDIT: just for reference, I [opened an issue on github-desktop fork for linux](https://github.com/shiftkey/desktop/issues/364#issue-733143363) and was redirected here.

**Comment by steveward** [comment]
Thanks for the feedback @vinnom. We are tracking this issue in https://github.com/desktop/desktop/issues/4569, so I am going to close this out. Thanks for using GitHub Desktop!
