### ISSUE TITLE
unable to pass the tutorial past step 2

### ISSUE THREAD

**Issue by supernoodled** [desktop/desktop#10971]
### Describe the bug
Step 1 - works fine, recognises sublime text is installed
Step 2 - will not proceed past this point, no matter what i do or how many branches i create

Decided to see if it would skip past this if I attempted the other steps,
so I also did all the other steps and no change, still stuck on step 2.

### Version & OS

Github Desktop version 2.5.6

Windows 10 Pro version 2004, build 19041.610

### Screenshot
![image](https://user-images.githubusercontent.com/31737227/98251453-a03bbd80-1f70-11eb-9924-eb13e596ab86.png)

### Logs
don't know if they would be helpful, but here they are (i cleaned out personal info tho):
[2020-11-05.desktop.production.log](https://github.com/desktop/desktop/files/5494938/2020-11-05.desktop.production.log)

### Additional context

**my github desktop settings:**
- External editor: Sublime Text
- Shell: Command Prompt
- Default branch for new repositories: master
- Appearance: Dark
- Background updates: disabled

**Comment by steveward** [comment]
@supernoodled thanks for the report! I'm not sure what would be causing this -- I just tested this out on macOS and the tutorial flow worked without issue. You can try resetting GitHub Desktop and creating a fresh tutorial. To do that you can follow these steps:

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop (you will need to log in again)

Let me know if that helps!
