### ISSUE TITLE
NOT ABLE TO PUSH MY PROJECT

### ISSUE THREAD

**Issue by tusharDelhi** [desktop/desktop#10970]
### Describe the feature or problem you’d like to solve
when i push my project on github.
then this message APPEARS

git: 'remote-https' is not a git command. See 'git --help'

**Comment by steveward** [comment]
Thanks for the report @tusharDelhi. Can you try resetting GitHub Desktop by following these steps?

1. Close GitHub Desktop 
2. Remove all of the files in `%LocalAppData%\GitHub Desktop\`
3. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that doesn't get things working.

**Comment by tusharDelhi** [comment]
kkkk
