### ISSUE TITLE
Can you make a MacOS Chinese package?

### ISSUE THREAD

**Issue by clien9025** [desktop/desktop#10979]

**Comment by steveward** [comment]
Thanks for contributing @clien9025. At this time we do not have language localization in GitHub Desktop, but this is something that we would like to pursue in the future. I don't have a timeline for when that may happen as it would require quite a bit of work by the team. I'm sorry that I don't have better news at this time.

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/GitHub-Desktop-Chinese-Language-Pack
