### ISSUE TITLE
Big Sur Title bar

### ISSUE THREAD

**Issue by guidezpl** [desktop/desktop#10980]
Minor issue but the new title bar on Big Sur looks a little out of place
<img width="326" alt="Screenshot 2020-11-06 at 13 32 32" src="https://user-images.githubusercontent.com/6655696/98366605-8c598f80-2034-11eb-98c7-e27fda26e120.png">

**Comment by steveward** [comment]
Thanks for pointing this out @guidezpl!

**Comment by billygriffin** [comment]
@guidezpl Thanks for the report! @niik took a stab at it in #11017, but we haven't been able to actually test it on Big Sur yet. Any chance you'd be open to checking out that PR and building the app to see how it feels? The instructions to set up your machine, if you've never built Desktop, are here if you're interested: https://github.com/desktop/desktop/blob/development/docs/contributing/setup.md And if not, obviously that's fine too - we still appreciate you letting us know. 😄

**Comment by guidezpl** [comment]
<img width="371" alt="Screenshot 2020-11-17 at 13 15 01" src="https://user-images.githubusercontent.com/6655696/99389182-eed54a00-28d6-11eb-8a58-139f41ad07d1.png">
I think it looks good!

**Comment by billygriffin** [comment]
Thanks @guidezpl!
