### ISSUE TITLE
Extremely slow push to origin

### ISSUE THREAD

**Issue by angelmarauder** [desktop/desktop#10984]
### Describe the bug

Push to origin is extremely slow

### Version & OS

Windows 10 
Version 2.5.7
### Steps to reproduce the behavior

push to origin
### Expected behavior

 multiple MB/s

### Actual behavior

300 KB/s max

### Screenshots

![image](https://user-images.githubusercontent.com/45987112/98422524-bb75fe00-2040-11eb-8446-51477320c250.png)

### Logs

[2020-11-06.desktop.production.log](https://github.com/desktop/desktop/files/5503882/2020-11-06.desktop.production.log)

**Comment by Xyncgas** [comment]
Unity project has a bunch small files to commit probably

**Comment by steveward** [comment]
@angelmarauder thanks for the report. Unfortunately there isn't much we can do about your connection speed to GitHub. You can check out https://github-debug.com/ to try and diagnose if there are any specific issues. It does look like you are working with a large repository -- is the push completing or throwing an error? Are you using Git LFS with this repository?

**Comment by angelmarauder** [comment]
> @angelmarauder thanks for the report. Unfortunately there isn't much we can do about your connection speed to GitHub. You can check out https://github-debug.com/ to try and diagnose if there are any specific issues. It does look like you are working with a large repository -- is the push completing or throwing an error? Are you using Git LFS with this repository?

I am using Git LFS.  Thank you for the debug link.  I will use it and reopen the issue if I find more actionable information.
