### ISSUE TITLE
My countDown button is not functioning as it should be 

### ISSUE THREAD

**Issue by kberhane30** [desktop/desktop#10998]
### Describe the bug
My (Restart) button is not functioning as needed. It supposes to restart the timer to the assigned time after clicked. But it's not doing this.
Version 2.5.3
### Steps to reproduce the behavior

1. Click on 'start' the timer will starts. 
2.Click on 'Pause' the timer will stop.
3.Click on 'restart' the timer will display the time but it doesn't count Down from that, it keeps counting down from the previous time.

### Expected behavior
The time will restart the counting down from 10:00 ( the new time after the restart button is clicked)
 
and here's my code : const counterOne = document.getElementById('clock');
    const startTime = 10;
    let time = startTime * 60;
    const btn1 = document.getElementById('start');
    const btn2 = document.getElementById('two');
    const btn3 = document.getElementById('three');
    // to start the counter
    
    btn1.addEventListener('click', function () {
        const interval = setInterval(counting, 1000);
        function counting() {
            let minutes = Math.floor(time / 60);
            let seconds = time % 60;
            seconds = seconds < 10 ? '0' + seconds : seconds;
            minutes = minutes < 10 ? '0' + minutes : minutes;
            counterOne.innerHTML = `${minutes}: ${seconds}`
            time--;
        }
        // to pause the counter 
        btn2.addEventListener('click', function () {
            clearInterval(interval);
        })
        // to restart the counter
        btn3.addEventListener('click', () => {
            counterOne.innerHTML = '10:00'
            time--;
    
        })
    })

**Comment by niik** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
