### ISSUE TITLE
GitHub Desktop quit working in macOS Mojave.  Opens to white screen.

### ISSUE THREAD

**Issue by ising4jesus** [desktop/desktop#10997]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the report @ising4jesus. We're tracking this in https://github.com/desktop/desktop/issues/4054. Normally this can be resolved by closing GitHub Desktop and deleting `~/Library/Application Support/Github Desktop/IndexedDB`. Let me know if that doesn't get things working for you.
