### ISSUE TITLE
Automatic Pushing and Pulling

### ISSUE THREAD

**Issue by Splatterxl** [desktop/desktop#10995]
### Describe the feature or problem you’d like to solve

I find it really slow to manually push and pull repos when I'm in a team. I think it would be a good idea to add an automatic option.

### Proposed solution

My solution would be to add an option in the repository settings, to automatically `git push` and `git pull` _when the user is connected to Wi-Fi_.

**Comment by steveward** [comment]
Thanks for the feedback @Splatterxl. GitHub Desktop performs a fast-forward merge for branches that you're not on as part of the auto-fetching process in the background. The automatic push feature was requested in #2191, and please see [this comment](https://github.com/desktop/desktop/issues/2191#issuecomment-431093456) for why this request is not currently on our roadmap. Feel free to drop any additional feedback you have into that issue thread.
