### ISSUE TITLE
Commit hangs while GHD is in focus on 2-core machine

### ISSUE THREAD

**Issue by ianshmean** [desktop/desktop#11000]
### Describe the bug

On an Ubuntu machine with 2 cores, git actions like commit hang indefinitely if the GitHub Desktop app is in focus.
If I select another window, the action immediately proceeds successfully

### Version & OS

Version 2.5.4-linux1
Ubuntu 20.04

### Steps to reproduce the behavior

1. Be on 2-core machine 
2. Have desktop window in focus
3. Commit
4. hang

### Expected behavior

Commits should not hang

### Actual behavior

Commits hang

**Comment by steveward** [comment]
@ianshmean thanks for the report. Since you're using the Linux fork of GitHub Desktop I'd recommending following along in the tracking issue for this bug: https://github.com/shiftkey/desktop/issues/329.

**Comment by ianshmean** [comment]
Ah yes, sorry.

I'm surprised that linux support hasn't been centralized yet, given that the fork has become so stable. Is there an up to date post somewhere that explains why it hasn't been?
