### ISSUE TITLE
[Feature Request] Interactive rebase / squashing commits

### ISSUE THREAD

**Issue by RedDevilus** [desktop/desktop#11009]
### Describe the feature or problem you’d like to solve

The ability to squash on a branch/main/PR. AKA Interactive Rebase.

### Proposed solution

Show amount of commits in the correct order, maybe even in a text editor like notepad++, and push those changes.
Even possibility to drag and drop and a checkbox where you can pick to squash/edit/rename.

### Additional context

Right now i am using GitHub Desktop to make PRs, clone , basically everything i need, but i have to go into my PRs files , use Git Bash (Mingw64 with CMD) do _git rebase -i HEAD~3_ see the commits and squash/fix/reorder how i like. And in the end do _git push -f_

Example how i workaround:
git rebase -i HEAD~ 2
git rebase -i HEAD~ 3
![image](https://user-images.githubusercontent.com/24227051/98750921-60853380-23bf-11eb-974d-49e8ada77d26.png)
Control +S and close file
Do my edits if needed
![image](https://user-images.githubusercontent.com/24227051/98750982-81e61f80-23bf-11eb-87c4-2126a1d7653f.png)
Control +S and close file
git push -f

And then look at the GitHub Desktop application to see changes and/or go to GitHub Site.

**Comment by billygriffin** [comment]
Hi @RedDevilus, thanks for the issue! We're discussing squashing in #2507 so I'm going to close this in favor of that one. The question around whether it's only when you merge, or more general support for squashing is still up in the air, so if you have use cases you'd like to share, please feel free to do so there.
