### ISSUE TITLE
Authentication Failed on Ubuntu

### ISSUE THREAD

**Issue by mansorab2020** [desktop/desktop#11004]
### Version & OS

Ubuntu 20.04.1 LTS    64-bit

### Steps to reproduce the behavior
I am a member of an organization that has a private repository 
1.past the link of repo in to the (clone a repository from internet...) URL tab
![image](https://user-images.githubusercontent.com/74176024/98656743-fd25e200-237b-11eb-8992-7a546719ac50.png)
2. the error is the authorization...
![image](https://user-images.githubusercontent.com/74176024/98657172-863d1900-237c-11eb-8beb-2ffd58bab2c3.png)

Note:the organization's settings of (Member repository permissions) are set for all members same as for me, they doesn't have any issues, but I do, they use windows OS.
### Expected behavior
the repo should be cloned

### Actual behavior
the authentication error

**Comment by niik** [comment]
@mansorab2020 thanks for the report. Since you're using the Linux fork of GitHub Desktop I'd recommending opening an issue in shiftkey's unofficial Linux repository instead: https://github.com/shiftkey/desktop. Best of luck!

**Comment by FaisalJamil-DITS** [comment]
### **SOLVED**

1. Generate a SSH key in the Linux & add it to Github Account. ([Guide](https://medium.com/featurepreneur/setting-up-ssh-key-with-github-for-ubuntu-cd8f2fabf25b))
2. Clone the repo using Github CLI. ([Guide](https://medium.com/devcnairobi/the-github-cli-gh-repo-clone-c0595e5672de))
3. Add existing repo to Github Desktop. ([Guide](https://docs.github.com/en/desktop/adding-and-cloning-repositories/adding-a-repository-from-your-local-computer-to-github-desktop))
