### ISSUE TITLE
GitHub Desktop doesn't update changes 

### ISSUE THREAD

**Issue by bogdanbgd7** [desktop/desktop#11001]
### Describe the bug

Nothing happens in GitHub Desktop when I commit few changes in certain file. 

### Version & OS

GitHub Desktop version: 2.5.7
OS: MacOS Catalina 10.15.7
### Steps to reproduce the behavior

1. Commit few changes in file
2. Save file
3. Open GitHub Desktop with cloned repo
4. 0 changed files 

### Expected behavior

Show changes each time I save file.

### Actual behavior

0 changed files even though I saved file in XCode

### Screenshots

<img width="249" alt="Screenshot 2020-11-09 at 17 39 01" src="https://user-images.githubusercontent.com/43911633/98569331-76590280-22b2-11eb-88b4-5a0a4a45b7b2.png">

**Comment by steveward** [comment]
Thanks for the report @bogdanbgd7. Can you confirm whether or not you have a `.gitignore` file that could be causing these changes to be ignored in your repository? You can go to the file menu and select `Repository` > `Repository Settings` > `Ignored Files` to check this.

**Comment by bogdanbgd7** [comment]
@steveward I don't have a `.gitignore `file within my project.

**Comment by steveward** [comment]
@bogdanbgd7 thanks for the update. Can you reliably reproduce this issue in another repository? What happens if you go to `Repository` > `Open in Terminal` and run `git status`?

**Comment by steveward** [comment]
@bogdanbgd7 as we have not heard back from you I am going to close this issue out. Let me know if you are still having problems.

**Comment by AyushBhattacharya52** [comment]
Im having the same problem and it gives an error
I think the problem is I uninstalled git
its probably the same for him
