### ISSUE TITLE
I can't use 2 accounts with 1 GitHubDesktop

### ISSUE THREAD

**Issue by valentijnpeters** [desktop/desktop#11005]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by billygriffin** [comment]
Thanks for the issue. This is captured in #3707 so please just leave a 👍 there if this is something you want. Since this is a duplicate I'm going to close it.
