### ISSUE TITLE
Unlimited width of the changed file list

### ISSUE THREAD

**Issue by Lars-jnk** [desktop/desktop#11012]
I have long file-paths and -names and atm I don't see them completly. It would be great if you can remove the max width setting for list where I see them. Also in when I selected one commit in the history tab.

Thx!

**Comment by niik** [comment]
Hey, thanks for reaching out! This looks very similar to the request in #2745 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date with any development happening in that area!
