### ISSUE TITLE
Mac OS version download is not an app and cannot be run.

### ISSUE THREAD

**Issue by Ayolland** [desktop/desktop#11014]
### Describe the bug

The download for Mac OS does not contain an app, but instead a folder named what the app should be. The app cannot be run or opened as-is.

### Version & OS

Cannot open app,
Catalina 10.15.6

### Steps to reproduce the behavior

1. Go to 'https://desktop.github.com/' while running macOS.
2. Click on 'Download for macOS'
3. Download and unarchive the zip file.
4. This expands to a *folder* named 'Github Desktop,' with an inner folder labeled 'Contents' indicating this is supposed to be an app.

### Expected behavior

To be able to download a working copy of the app.

### Screenshots

<img width="632" alt="Screen Shot 2020-11-11 at 11 52 29 AM" src="https://user-images.githubusercontent.com/10699280/98858412-6a398600-2415-11eb-8d39-adcd885b0c11.png">

**Comment by niik** [comment]
Hey @Ayolland, sorry to hear you're having problems.

What browser are you using to download Desktop? And are you using a third party tool to extract the zip file? On macOS applications are folders that adhere to a certain layout. When extracting the `.zip` file a directory should be created called `GitHub Desktop.app` which macOS then treats as an application bundle. It seems your extraction have ended up creating a `GitHub Desktop` folder without the necessary `.app` suffix.

When looking at an application in Finder you can right click on it and choose "Show package contents" to view it as a directory

![image](https://user-images.githubusercontent.com/634063/98922043-4a1bcc80-24d2-11eb-9593-0e63a4be9738.png)

Which in this case should reveal a layout very similar to that you posted.

![image](https://user-images.githubusercontent.com/634063/98922056-4ee08080-24d2-11eb-9e43-c78a6ceec10d.png)

Can you try downloading the app using Safari and ensure that you've got the "Open "safe" files after downloading" option turned on in Safari preferences (under General)

![image](https://user-images.githubusercontent.com/634063/98922752-21e09d80-24d3-11eb-94dd-2af76cc211ca.png)

**Comment by Ayolland** [comment]
You are correct, this appears to be not an issue with the archive file itself, but with a third-party archive tool that had become the default on my machine. Downloading and automatically un-archiving via Safari worked, as did using the MacOS app. Thanks for the response, sorry for the false alarm.
