### ISSUE TITLE
Can't access repository after update to 2.5.7 #10973

### ISSUE THREAD

**Issue by Mishasama** [desktop/desktop#11022]
### Describe the bug

It looks can't access the private repository after the #10973 update.

### Version & OS

2.5.7
WIN 10 1809

### Steps to reproduce the behavior

1. Set the private repository as the current repository.
2. Commit something changes.
3. Click Push origin.
4. See error.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.
![021113081917](https://user-images.githubusercontent.com/54498172/99009691-c58d8480-258b-11eb-9247-34f3661a95e0.png)
![021113081735](https://user-images.githubusercontent.com/54498172/99008248-1fd91600-2589-11eb-8716-8e64df386274.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
[2020-11-12.desktop.production.log](https://github.com/desktop/desktop/files/5533858/2020-11-12.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @Mishasama. It looks like you're running into a strange authentication issue that I haven't seen before. Can you try resetting GitHub Desktop by following these steps? I'm hoping this is just an artifact from the update process.

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop and log in/add your repositories again

Let me know if that doesn't get things working.

**Comment by davesmiths** [comment]
@steveward 

Hi, just wanted to say thank you

I had this issue as well, I followed the steps and apart from losing all my settings, I was able add my repo again and push to it.
(plus my little avatar icon appeared next to the commit message textbox, whereas before it had fallen-back to a generic icon with the recent update)

... back at it 👍 

🥳❤️

all the best
Dave

**Comment by davesmiths** [comment]
@steveward 

I'm sorry, but it has happened again.

I was able to push to my repo earlier after the above.

but now I'm back to where I was... nooooooooooooo
🙂

ah well, it'll be alright in the end

this is the error I see, which to me was a variant of Misha's

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/61648/99249393-f676ef00-2801-11eb-8858-ab751d0c068f.png">

**Comment by davesmiths** [comment]
Hi, I got it working shortly after the last message

I followed the instructions again and instead deleted "Session Storage" only

This worked and and has continued all day long 
🥳❤️

**Comment by steveward** [comment]
I'm glad to hear that got things working!
