### ISSUE TITLE
Unable to see changes made in code

### ISSUE THREAD

**Issue by joeltan99** [desktop/desktop#11025]
### Describe the bug

All files show its empty. Changes made cannot be seen on github desktop app.

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.
![Capture](https://user-images.githubusercontent.com/71722385/99081067-2d2fe800-25fd-11eb-803a-fae6431218d7.PNG)

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by billygriffin** [comment]
Hi @joeltan99, would you mind filling out the rest of the template to help us further investigate? Also, this usually happens when you're changing a file that is in your .gitignore. Those changes should not show up because they won't be committed to the repo.
