### ISSUE TITLE
.\:F.\groupname:login.\2222\Users\!?$user$?!\temp~

### ISSUE THREAD

**Issue by superkiller22** [desktop/desktop#11038]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

F.\?!$<USER>$!?\:C:\Users\?!$user$!?\desktop\groupname\.temp~.!:(:re:):"25688625424525688652.0:55.45.46.1?.:34.666.888:99.98.:66.88.66:0.0.0.0.0.00.00.00.000.000.000:45.55.46:666:8:45:46.55.46.45:88:00.00.00.00:(:re:):.\:#2,,,,!!!!!!:#:(:re:):.\Users\user\desktop\user.temp~\~temp:88.!:(:re:):"(".\:F:a.a:01:34:42:55:a.a:(:re:):-Æ{:(:re:):!:(:re:):!:#$??$#:(:re:):!:(:re:):!Groupname!.:88:666:2222.2454256886522.0.\user.\temp~!:(:re:):!.:(:re:):?user?:(:re:):.!.2.8:(:re:):="Groupname":(:re:):.aa\Æ#!:(:re:):!:(:re:):.#*:*#.2.[[:[:#:!.!:a:a.a.a:a.a.h.a.s.o.p.r.e.c.t.o.n.s.o.a.:!.!.Trash.!.!#:[56478 = 1,54678 var 1,?_[!*4051*!]_?.:(:re:):|U:(.2*8*2.):U|:(:re:):.?_[!*4051*!]_?]:]].!#:(:re:):!:(:re:):{|}{!.!!:(:re:):.#.*:*.#.*\Users\userlist.txt.log.txt\:#+:#$\\.\2: ".\":".0/.1/.2/}:"12452135312567887652135312454212567777887777652135312454212568899988652135312454212568899988652454213531245421353125600":=>:".0/.1/.2/}:"124521353125678876521353124542125677778877776521353124542125688999886521353124542125688999":\/}{|U:(.2):U|}{:43!.:".0/.1/.2/}:"124521353125678876521353124542125677778877776521353124542125688999886521353124542125688999":=:.0/.1/.2/}:"1245213531256788765213531245421256777788777765213531245421256889998865213531245421256889998865245421353125600"!:43!......:#+:#$#:+:#$$#:.\$user$\\:#+:#$2$#:(:re:):.8:(:re:):.org\8:(:re:):"Groupname:apply:1234.1222.2223.3334.4443.3332.2221.0.0.0.0:00:00:00:00.0000.0000.0000:1.2.2222.2222.1.0.1.0.1?:1, or, 0!.:(:re:):?":("Disconnected:0"):\\%$user$%\temp~

**Comment by superkiller22** [comment]
Groupname login/user/connected through groupname new policy, and rights on service side is only user applied by login on A:\ service by groupname users could be fw, or security is pw , group connected on app by groupname connected betwen users

**Comment by superkiller22** [comment]
F.\?!$<USER>$!?\:C:\Users\?!$user$!?\desktop\groupname\.temp~.!:(:re:):"25688625424525688652.0:55.45.46.1?.:34.666.888:99.98.:66.88.66:0.0.0.0.0.00.00.00.000.000.000:45.55.46:666:8:45:46.55.46.45:88:00.00.00.00:(:re:):.\:#2,,,,!!!!!!:#:(:re:):.\Users\user\desktop\user.temp~\~temp:88.!:(:re:):"(".\:F:a.a:01:34:42:55:a.a:(:re:):-Æ{:(:re:):!:(:re:):!:#$??$#:(:re:):!:(:re:):!Groupname!.:88:666:2222.2454256886522.0.\user.\temp~!:(:re:):!.:(:re:):?user?:(:re:):.!.2.8:(:re:):="Groupname":(:re:):.aa\Æ#!:(:re:):!:(:re:):.#*:*#.2.[[:[:#:!.!:a:a.a.a:a.a.h.a.s.o.p.r.e.c.t.o.n.s.o.a.:!.!.Trash.!.!#:[56478 = 1,54678 var 1,?_[!*4051*!]_?.:(:re:):|U:(.2*8*2.):U|:(:re:):.?_[!*4051*!]_?]:]].!#:(:re:):!:(:re:):{|}{!.!!:(:re:):.#.*:*.#.*\Users\userlist.txt.log.txt\:#+:#$\\.\2: ".\":".0/.1/.2/}:"12452135312567887652135312454212567777887777652135312454212568899988652135312454212568899988652454213531245421353125600":=>:".0/.1/.2/}:"124521353125678876521353124542125677778877776521353124542125688999886521353124542125688999":\/}{|U:(.2):U|}{:43!.:".0/.1/.2/}:"124521353125678876521353124542125677778877776521353124542125688999886521353124542125688999":=:.0/.1/.2/}:"1245213531256788765213531245421256777788777765213531245421256889998865213531245421256889998865245421353125600"!:43!......:#+:#$#:+:#$$#:.\$user$\\:#+:#$2$#:(:re:):.8:(:re:):.org\8:(:re:):"Groupname:apply:1234.1222.2223.3334.4443.3332.2221.0.0.0.0:00:00:00:00.0000.0000.0000:1.2.2222.2222.1.0.1.0.1?:1, or, 0!.:(:re:):?":("Disconnected:0"):\\%$user$%\temp~

**Comment by superkiller22** [comment]
Groupname list & users connected by through domain and connected on new formable way

**Comment by superkiller22** [comment]
Groupname app, user list and mm

**Comment by superkiller22** [comment]
Groupname user list & connected to one another mainly for stream and easier connection betwen users on distance

**Comment by superkiller22** [comment]
> ### Describe the feature or problem you’d like to solve
> A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.
> 
> ### Proposed solution
> How will it benefit Desktop and its users?
> 
> ### Additional context
> Add any other context like screenshots or mockups are helpful, if applicable.
> 
> F.?!$$!?:C:\Users?!$user$!?\desktop\groupname.temp~.!:(:re:):"25688625424525688652.0:55.45.46.1?.:34.666.888:99.98.:66.88.66:0.0.0.0.0.00.00.00.000.000.000:45.55.46:666:8:45:46.55.46.45:88:00.00.00.00:(:re:):.:#2,,,,!!!!!!:#:(:re:):.\Users\user\desktop\user.temp~~temp:88.!:(:re:):"(".:F:a.a:01:34:42:55:a.a:(:re:):-Æ{:(:re:):!:(:re:):!:#$??$#:(:re:):!:(:re:):!Groupname!.:88:666:2222.2454256886522.0.\user.\temp~!:(:re:):!.:(:re:):?user?:(:re:):.!.2.8:(:re:):="Groupname":(:re:):.aa\Æ#!:(:re:):!:(:re:):.#_:_#.2.[[:[:#:!.!🅰️a.a.a:a.a.h.a.s.o.p.r.e.c.t.o.n.s.o.a.:!.!.Trash.!.!#:[56478 = 1,54678 var 1,?_[!_4051_!]_?.:(:re:):|U:(.2_8_2.):U|:(:re:):.?_[!_4051_!]_?]:]].!#:(:re:):!:(:re:):{|}{!.!!:(:re:):.#._:_.#.*\Users\userlist.txt.log.txt:#+:#$\.\2: ".":".0/.1/.2/}:"12452135312567887652135312454212567777887777652135312454212568899988652135312454212568899988652454213531245421353125600":=>:".0/.1/.2/}:"124521353125678876521353124542125677778877776521353124542125688999886521353124542125688999":/}{|U:(.2):U|}{:43!.:".0/.1/.2/}:"124521353125678876521353124542125677778877776521353124542125688999886521353124542125688999":=:.0/.1/.2/}:"1245213531256788765213531245421256777788777765213531245421256889998865213531245421256889998865245421353125600"!:43!......:#+:#$#:+:#$$#:.$user$\:#+:#$2$#:(:re:):.8:(:re:):.org\8:(:re:):"Groupname:apply:1234.1222.2223.3334.4443.3332.2221.0.0.0.0:00:00:00:00.0000.0000.0000:1.2.2222.2222.1.0.1.0.1?:1, or, 0!.:(:re:):?":("Disconnected:0"):\%$user$%\temp~

**Comment by polly400** [comment]
> ### Describe the feature or problem you’d like to solve
> 
> A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.
> 
> ### Proposed solution
> 
> How will it benefit Desktop and its users?
> 
> ### Additional context
> 
> Add any other context like screenshots or mockups are helpful, if applicable.
> 
> F.\?!$<USER>$!?\:C:\Users\?!$user$!?\desktop\groupname\.temp~.!:(:re:):"25688625424525688652.0:55.45.46.1?.:34.666.888:99.98.:66.88.66:0.0.0.0.0.00.00.00.000.000.000:45.55.46:666:8:45:46.55.46.45:88:00.00.00.00:(:re:):.\:#2,,,,!!!!!!:#:(:re:):.\Users\user\desktop\user.temp~\~temp:88.!:(:re:):"(".\:F:a.a:01:34:42:55:a.a:(:re:):-Æ{:(:re:):!:(:re:):!:#$??$#:(:re:):!:(:re:):!Groupname!.:88:666:2222.2454256886522.0.\user.\temp~!:(:re:):!.:(:re:):?user?:(:re:):.!.2.8:(:re:):="Groupname":(:re:):.aa\Æ#!:(:re:):!:(:re:):.#*:*#.2.[[:[:#:!.!:a:a.a.a:a.a.h.a.s.o.p.r.e.c.t.o.n.s.o.a.:!.!.Trash.!.!#:[56478 = 1,54678 var 1,?_[!*4051*!]_?.:(:re:):|U:(.2*8*2.):U|:(:re:):.?_[!*4051*!]_?]:]].!#:(:re:):!:(:re:):{|}{!.!!:(:re:):.#.*:*.#.*\Users\userlist.txt.log.txt\:#+:#$\\.\2: ".\":".0/.1/.2/}:"12452135312567887652135312454212567777887777652135312454212568899988652135312454212568899988652454213531245421353125600":=>:".0/.1/.2/}:"124521353125678876521353124542125677778877776521353124542125688999886521353124542125688999":\/}{|U:(.2):U|}{:43!.:".0/.1/.2/}:"124521353125678876521353124542125677778877776521353124542125688999886521353124542125688999":=:.0/.1/.2/}:"1245213531256788765213531245421256777788777765213531245421256889998865213531245421256889998865245421353125600"!:43!......:#+:#$#:+:#$$#:.\$user$\\:#+:#$2$#:(:re:):.8:(:re:):.org\8:(:re:):"Groupname:apply:1234.1222.2223.3334.4443.3332.2221.0.0.0.0:00:00:00:00.0000.0000.0000:1.2.2222.2222.1.0.1.0.1?:1, or, 0!.:(:re:):?":("Disconnected:0"):\\%$user$%\temp~

**Comment by polly400** [comment]
``
