### ISSUE TITLE
Choosing ide

### ISSUE THREAD

**Issue by arihant2math** [desktop/desktop#11037]
When one chooses their external editor in options, atom is the only choice for an editor, is it possible to allow users to add editors by choosing the editors file path?
![image](https://user-images.githubusercontent.com/58895652/99178276-42bd1480-26c6-11eb-9668-70ed5346f75e.png)

**Comment by steveward** [comment]
At this time GitHub Desktop only supports editors that have been specifically integrated into the application. You can find the details of how this works along with the supported editors here:

https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md

We happily accept pull requests to integrate new editors. There is also a [tracking issue](https://github.com/desktop/desktop/issues/7033) where we are collecting feedback about better support for external editors. Please feel free to add feedback there.
