### ISSUE TITLE
Fresh Install; Can't Login

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#11034]
### Describe the bug

I tried to log out of my main account and I keep getting an error saying the username/account doesn't exist. I have tried this with a few accounts. Even creating a new GitHub account and trying to log in that way. Keeps getting error after error. Tried reinstalling my OS and redoing everything from scratch and I am having the same issue.

### Version & OS

POP!OS 20.10. Github Desktop v2.4.1

### Steps to reproduce the behavior

1. Install Fresh Github Desktop
2. Or log out of your account
3. Log in again
4. Or create a new account and try to login

### Expected behavior
Incorrect email or password

**Comment by omaisali** [comment]
i have same issue
