### ISSUE TITLE
Add user extensions support

### ISSUE THREAD

**Issue by MiguelRipoll23** [desktop/desktop#11033]
### Describe the feature or problem you’d like to solve

I feel by looking at the most requested features that GitHub Desktop is way behind, even though for a new user is a perfect choice after using it for some time for both personal and work use cases features like the branches graph, git flow or cherrypick are quite important and missed.

I fully understand that the development team may not agree to adding some features due to product decisions or high features demand.

### Proposed solution

Adding support for extensions (just like VS Code) would reduce features demand by moving the work to the community and enhancing the experience for advanced users.

### Additional context

The most requested features usually get closed due to product decisions or high features demand. Please keep the discussing civil and avoid writing +1 comments.

**Comment by steveward** [comment]
Thanks for the feedback @MiguelRipoll23. Adding support for extensions is something that was discussed in https://github.com/desktop/desktop/issues/1718 -- see https://github.com/desktop/desktop/issues/1718#issuecomment-502863425 for the current thinking on this. At this time our plans have not changed with regards to supporting extensions, so I am going to close this issue out. Thanks for letting us know you'd like to see this.
