### ISSUE TITLE
Can't switch to another branch after creating new branch

### ISSUE THREAD

**Issue by KrisBNelson** [desktop/desktop#11049]
### Describe the bug

In a branch called 'nonprod', I have code changes. I create a New Branch 'X', based on 'nonprod', then I bring changes over to the new branch 'X'. I click on 'nonprod' to switch back over, click on 'Leave changes' in the branch 'X', but the branch remains 'X' and not the desired 'nonprod'.

I tested this on 2 repos, the same thing happens. I can't get to my previous branch.

### Version & OS

Version 2.5.7
Windows 7

### Steps to reproduce the behavior

1. Have uncommitted new code, then go to Branch.
2. Click on New Branch.
3. Create branched based on current branch.
4. Click on Create branch.
5. Click on Bring changes over.
6. New branch is created.
7. Try to go to a different branch.
8. Click on Current branch dropdown.
9. Select another branch.
10. Click on Leave my changes.
11. Click on Switch branch.

### Expected behavior

When I create a new branch, I expect to be able to go to other branches afterwards, even without committing the new code.

### Actual behavior

I can't go to other branches after I create a new branch with uncommitted code in it.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

[2020-11-16.desktop.production.log](https://github.com/desktop/desktop/files/5548453/2020-11-16.desktop.production.log)

**Comment by steveward** [comment]
@KrisBNelson thanks for the report. It looks like there your name and password are not configured:

```
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
```

Can you go to `File` > `Options` > `Git` and verify that your name and email are set correctly?

**Comment by KrisBNelson** [comment]
I do have it configured. Repos keep giving me this error all the time. I go to Options, Git, click Save, and it lets me commit until next time. My name and email were there from the start, but it keeps asking me for them even though I have them set. I've also done it with the git command as the commit failure tells me, and it's the same thing. Eventually it gives me this nonsense again after letting me through if I do the cmd or Options>Git>Save. It just never lasts.

Regardless, why would that prevent me from switching branches?

I have reinstalled Git Desktop and will see if the "tell me who you are" bug is gone.

**Comment by steveward** [comment]
@KrisBNelson does `git config --list` show that your name and email are set? There could be an issue with GItHub Desktop writing to that file.

**Comment by KrisBNelson** [comment]
Yes it has them set. I reinstalled (deleted user Roaming/Local folders after uninstall) and still get the annoying "tell me who you are" at commit time issue which goes away for some time but then comes back.

**Comment by steveward** [comment]
I notice you are using Windows 7, which I haven't tested in a while. Any chance there are any permissions set that could be preventing GitHub Desktop from reading your config files?

**Comment by KrisBNelson** [comment]
I'm not using Windows 7. It's Windows 10 Enterprise. I was using another corporate laptop as admin and didn't have these issues. Admin here too. I don't get why I can't get rid of that annoying commit "who are you" message/restriction.

**Comment by steveward** [comment]
@KrisBNelson have you tried committing via the command line? If the configuration of your name/email is missing it should throw an error there as well. If it doesn't then there's likely an issue with GitHub Desktop reading your config file. Is it possible you have your user directory mapped to a network drive?

**Comment by KrisBNelson** [comment]
@steveward I have local user directory, where I deleted Github Desktop folders when I previously uninstalled. I did the config via command line and then the GUI for committing, but that didn't resolve the issue permanently either. Next time I commit I guess I can try the cmd method, but doubt that will change anything either.

**Comment by KrisBNelson** [comment]
Well, that worked @steveward . I don't know why. Setting up the mail and username, followed by the commit, both done in the command line, seems to have resolved the commit issue, where as doing the mail and username in command line only and committing in the GUI didn't work. Thanks for the help.
