### ISSUE TITLE
Github Desktop displaying incorrect commit history for default branch when the default branch is not 'master' branch

### ISSUE THREAD

**Issue by Justin-JHG** [desktop/desktop#11045]
### Describe the bug

Github Desktop displaying different commit history compare to GitHub

### Version & OS

Version 2.5.7 on Windows 10

### Steps to reproduce the behavior

noticed today I can't find some commit history in GitHbub Desktop but I can find them on GitHUb web page.

### Expected behavior

GitHub Desktop commit history display should be exactly same as GitHub commit history on web page

### Screenshots
screenshot on Github web page
![image](https://user-images.githubusercontent.com/41654878/99203887-0d204480-2808-11eb-8e74-4a3ab8282f55.png)

screenshot on Github Desktop
![image](https://user-images.githubusercontent.com/41654878/99203927-2628f580-2808-11eb-96c9-8d459c3e3bf8.png)

the commit history for pull request 1393 and 1394 are missing on Github Desktop

just to add some more information, this happens on the default branch in our repo. and looks like history displayed on GitHub Desktop is showing history of our Master branch, instead of the history of our default branch. our default branch is not 'Master' branch

**Comment by steveward** [comment]
Thanks for the report @Justin-JHG.

>just to add some more information, this happens on the default branch in our repo. and looks like history displayed on GitHub Desktop is showing history of our Master branch, instead of the history of our default branch. our default branch is not 'Master' branch

Can you confirm that your currently checked-out branch in GitHub Desktop is your default branch (and not `master`)?

**Comment by Justin-JHG** [comment]
Hi @steveward ,

Yes can confirm that my current checkout branch was the default branch, not master

And the history showing is partially for current branch and partially for master branch.


Justin

**Comment by btitze** [comment]
Hi @Justin-JHG and @Steveward,

I have noticed a similar problem: After a merge, the history of the branch I'm working on looks fine on GitHub.com, but in GitHub Desktop, the history is not the same. The branch should be ahead by 80 commits, but all these commits that were added in the merge are not shown in the commit history in GitHub desktop.

I'll post a separate issue for that.

**Comment by steveward** [comment]
@Justin-JHG I believe this should be resolved by the fix in https://github.com/desktop/desktop/pull/12553. Let us know if you're still encountering this!
