### ISSUE TITLE
Wrong Default branch for repo

### ISSUE THREAD

**Issue by AbdelrahmanNafea** [desktop/desktop#11040]
### Describe the bug

The desktop application can't select the right default branch from the online one 
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior
1- creat new branch 
2- the main not the default one but on online Github is the default

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the report @AbdelrahmanNafea. GitHub Desktop should respect the default branch of your remote repository. Is this a new repository that was created in GitHub Desktop, or did you clone this as an existing repository from GitHub to GitHub Desktop? Is the specific issue that the wrong branch is being shown as the default when you click the `new branch` button?

Any extra details or screenshots you can share about the problem you are experiencing would be helpful.

**Comment by Dboingue** [comment]
Well I am surprised that this was closed. or not further documented. Here no new branch involved in the problem.
I switched the default from master on github site repository (my fork of another repository).
On GHD, I have parent pointing to my fork not the upstream remote, and even if I update or restart GHD, in the branch selector drop down, the master is still the branch under "default" heading.  

I could further check if that has consequences when creating new branch form there to see which default actually is used as base  for new branch...   To no avail.  both the ensuing dialog confirms GHD still thinks the default is master, and if created the branch content will not have the files that are part of the branch that has been set as default on github site, the origin of the clone.

I hope that this is the same issue.  As it does seem a compatible phrasing. In my case I would have written that the clone repository in GitHub Desktop does not reflect its remote origin repository new default branch as updated.  keeping the master that was the previous default on both origin and clone.

### current work-around.  
- Delete clone from GHD (files too).  Re-clone from github site, while is has the new default.

And just to make sure, an extra check that, a further default change at remote (origin), still does not propagate back to clone GHD default assignment.  Still same behavior.  no local clone GHD changes either with branch drop down, or new branch dialog, confirming that the remote default update did not get "fetched".

Do you still need screenshots, or should I create another issue? Thanks for reading, even if closed.
