### ISSUE TITLE
Control/Shift clicking checkboxes in file list doesn't work as expected

### ISSUE THREAD

**Issue by robotboy655** [desktop/desktop#11051]
### Describe the bug
Control/Shift clicking checkboxes in file list doesn't work as expected. This makes selecting a subset of a large list of files very painful.

What's worse is clicking on the checkboxes with either shift or control held down acts as if I clicked on the row itself, which is causing weird flip-flop behavior seen at the end of the second gif.

### Version & OS

Github Desktop Version 2.5.7
Windows 10

### Expected behavior
![plastic](https://user-images.githubusercontent.com/3299036/99334300-64b2c480-2889-11eb-855c-318a66934a19.gif)

### Actual behavior
![github](https://user-images.githubusercontent.com/3299036/99336150-ef93bf00-2889-11eb-9896-a0e541424356.gif)

**Comment by steveward** [comment]
Thanks for the report and gifs @robotboy655! We are tracking this bug in https://github.com/desktop/desktop/issues/8750. I'll bump up that issue.

**Comment by robotboy655** [comment]
I saw that issue and I wouldn't call it the same issue, although indeed related.
