### ISSUE TITLE
Large block with minor changes highlighted in red with no green followup

### ISSUE THREAD

**Issue by HaoSun1** [desktop/desktop#11057]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for reaching out @HaoSun1!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. Thanks!

**Comment by HaoSun1** [comment]
I'm a bit hesitant to include my tex file and I don't know how to turn the content of my file to giberrish while preserving the structure and keeping same words same  not sure if would know how to do this.

**Comment by niik** [comment]
Hey @HaoSun1, we'd love to get to the bottom of this. I'm assuming you're seeing this in the new split diff mode right? As @steveward said we're not going to be able to troubleshoot this without being able to reproduce it. Let us know if you'd be willing or able to share screenshots and a sample file with us privately via email for us to debug.

**Comment by HaoSun1** [comment]
@niik how do I send you an email?

**Comment by HaoSun1** [comment]
Actually I'm gonna close this issue as it seems I cannot reproduce it.
