### ISSUE TITLE
Add visual rebase entry for squashing

### ISSUE THREAD

**Issue by Adrianilloo** [desktop/desktop#11054]
### Describe the feature or problem you’d like to solve

I am a rebase guy. I love rebasing for both unifying commits on current branch (via squash/fixup) and sometimes also use it from branches of a parent repository. GitHub Desktop allows to rebase another branch from active repository into current one, which is nice, but it lacks the former use case (squashing), so I need to use command line for it.

### Proposed solution

Add a contextual menu entry at history panel for each commit which says "Rebase from this commit" (or similar) that invokes interactive rebase **from** selected commit, that is, the following command: `git rebase -i <commit_hash>^`  or a better variant.

Thanks!

**Comment by steveward** [comment]
Thanks for the feedback @Adrianilloo. We're discussing squashing in #2507 so I'm going to close this in favor of that one. The question around whether it's only when you merge, or more general support for squashing is still up in the air, so if you have use cases you'd like to share, please feel free to do so there.

**Comment by Adrianilloo** [comment]
I'd like to say I'm very happy with the new visual squashing flow. That covers my needs absolutely while being a very effective generic solution.
