### ISSUE TITLE
Not possible to Fetch origin since last update

### ISSUE THREAD

**Issue by JesusCasasBorregon** [desktop/desktop#11067]
### Describe the bug

I'm getting the following message whenever I try to Fetch origin:

"remote: Bad Request
fatal: unable to access 'https://gitlab.com/mberthet/9th-age-latex.git/': The requested URL returned error: 400"

I can open the repository without any problem in gitlab.com in my browser

Feth origin was working without issues until today, when github desktop updated to the last version. Since then I'm getting this message

### Version & OS

GitHub Desktop Version 2.6.0
Microsoft Windows 10 Home, 10.0.19041 compilation 19041

### Steps to reproduce the behavior

Repository: https://gitlab.com/mberthet/9th-age-latex
1. Open Github Desktop
2. Click on Fetch Origin (regardless of the branch)

### Expected behavior

Github Desktop shall fetch repository origin

### Actual behavior

Eror message is displayed:
remote: Bad Request
fatal: unable to access 'https://gitlab.com/mberthet/9th-age-latex.git/': The requested URL returned error: 400

It is not possible to fetch origin

### Logs

[2020-11-18.desktop.production.log](https://github.com/desktop/desktop/files/5562404/2020-11-18.desktop.production.log)

### Additional context

Issue was not observed until last GitHub Desktop update

**Comment by niik** [comment]
> Issue was not observed until last GitHub Desktop update

Hey @JesusCasasBorregon, I believe this might be a coincidence. Looking at your log file this error is actually coming from Git not being able to push to the repository.

```
`git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Bad Request
fatal: unable to access 'https://gitlab.com/mberthet/9th-age-latex.git/': The requested URL returned error: 400
```

I would suggest trying to contact GitLab support to see if they might be having some issues with Git operations at the moment.

Are you able to clone/push/pull repositories not hosted on GitLab?

**Comment by steveward** [comment]
@JesusCasasBorregon I just tested fetching with my GitLab test repository and did not run into any issues. I would recommend trying to authenticate again by deleting your GitLab credentials in `Credential Manager`, and if that doesn't work definitely reach out to GitLab support like @niik mentioned.

**Comment by Mediagone** [comment]
I have the same problem since the update, it might be related to the authentication changes (removed user/password connection).

To what `Credential Manager` do you refer, @steveward ?

**Comment by Mediagone** [comment]
After further investigation, you need to set up a valid ssh key for GitLab authentification.

**Comment by steveward** [comment]
@Mediagone Windows has a built-in credential tool called `Credential Manager` -- you should be able to launch it from the start menu search bar. See [this guide](https://support.microsoft.com/en-us/windows/accessing-credential-manager-1b5c916a-6a16-889f-8581-fc16e8165ac0#:~:text=Windows%2010,select%20Credential%20Manager%20Control%20panel). You should be able to find the credentials GitHub Desktop stores for GitLab there. 

>After further investigation, you need to set up a valid ssh key for GitLab authentification.

SSH will work, but you can also follow [this guide](https://github.com/desktop/desktop/blob/development/docs/integrations/gitlab.md) if you would prefer to use HTTPS.

**Comment by Mediagone** [comment]
It works, thanks :)

**Comment by JesusCasasBorregon** [comment]
Hi Bruce,

It worked with a combination of deleting the credentials from Credential Manager and Cloning the repository as you suggested following the how to.

Thanks to all for your support!
Jesús

________________________________
De: Bruce <notifications@github.com>
Enviado: viernes, 20 de noviembre de 2020 11:30
Para: desktop/desktop <desktop@noreply.github.com>
Cc: JesusCasasBorregon <jkasas13@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [desktop/desktop] Not possible to Fetch origin since last update (#11067)


It works, thanks :)

**Comment by steveward** [comment]
Glad to hear things are working!
