### ISSUE TITLE
Split diff mode: Ctrl+Cmd+F opens search instead of toggling fullscreen

### ISSUE THREAD

**Issue by mischnic** [desktop/desktop#11069]
### Describe the bug

Pressing Ctrl+Cmd+F while viewing a diff in the "split" mode opens a search bar inside the diff instead of toggling fullscreen.

### Version & OS

2.6.0
macOS 10.15.5

### Steps to reproduce the behavior

1. Go to the "Changes" tab and make sure there is a diff displayed
2. Switch into "spit"  diff mode via the gear dropdown menu
3. Press Ctrl+Cmd+F

### Expected behavior

Pressing Ctrl+Cmd+F should toggle fullscreen mode (like it does in the unified diff mode)

### Actual behavior

Pressing Ctrl+Cmd+F opens a search field

### Screenshots

That search bar:

![Bildschirmfoto 2020-11-19 um 00 34 54](https://user-images.githubusercontent.com/4586894/99601108-0e679200-29ff-11eb-99a8-b2092aa4b3f9.png)

**Comment by steveward** [comment]
Thanks for the report @mischnic! I confirmed this as well. Labeling it a `priority-3`.
