### ISSUE TITLE
Corporate Proxy

### ISSUE THREAD

**Issue by BlueMystical** [desktop/desktop#11062]
### Describe the feature or problem you’d like to solve

It is NEEDED a Set Proxy Option for both HTTP and HTTPS connections.

### Proposed solution

Lots of Developers work on Corporate Environments who use a Proxy.

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.
Idk what  a 'mockup' is.

**Comment by steveward** [comment]
@BlueMystical thanks for contributing. GitHub Desktop automatically attempts to use your existing proxy, but if you need to manually configure your proxy authentication you can follow these steps:

1. Go to the file menu and select `Repository` > `Open in Terminal` (macOS) or `Open in command prompt` (Windows)
2. Run the following command:

`git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`

Replace `proxyuser` with your proxy username and `proxypwd` with your proxy password. Also, `proxy.server.com:8080` needs to point to the URL of your proxy server.

Let me know if you have any issues getting this set up.

**Comment by BlueMystical** [comment]
Hello,
Thanks for the answer, but... You should not close this that easy.
I do not have such a menu.  (See Screenshot below)
And i downloaded the Program Today,
Had already looked for an option to set up the proxy and couldn't find one,
that's why i submitted this ticket.

I found at StackOverflow something about editing a file named '.gitconfig'
somewhere under 'Users' data folder, i'll try that later.
However, the reason for my request is exactly to avoid having to manually
edit weird files.

[image: Sin título.png]

**Comment by steveward** [comment]
@BlueMystical your screenshot did not come through because it was sent via an email reply. Feel free to upload it as an attachment here.

>I found at StackOverflow something about editing a file named '.gitconfig'
somewhere under 'Users' data folder, i'll try that later.

You can directly edit the .gitconfig file, but running the command I gave adds the entry to the same file and is less likely to cause configuration errors. You may need to [download Git](https://git-scm.com/download/win) to run that command if you have not done so already.

**Comment by BlueMystical** [comment]
Found the menu you said not under 'File' Menu but parallel to it, and all
its sub-menus are disabled, probably due that i haven't been able to load
any of my repositories, they do show tough, but when attempting to open
they throw proxy error.

The command worked and solved my problem, applied the command from git
console instead.

Even if my problem is fixed, dont you think that editing weird files and
running commands is far too complicated for most users? I guarantee you
that there are lots having the same problem, you may be missing them
because they solve their problem through StackOverflow instead of
submitting bug reports.
Wouldn't be easier (for the users) to have a menu box to do this simple
task?
Is it really that hard to accomplish?

That's the reason I submitted this as a feature request instead of as a bug
report.
Anyways, thanks for the support.

Regards.

**Comment by steveward** [comment]
We did ship improvements for automatic proxy detection (see https://github.com/desktop/desktop/pull/9154), but authenticated proxies require configuration. Thanks for the feedback about this.

**Comment by BlueMystical** [comment]
That required configuration in a menu that pops a simple box for input the
Proxy settings, is the feature needed.
