### ISSUE TITLE
Problem with large repositories (disk space + bandwidth + money)

### ISSUE THREAD

**Issue by Neustradamus2** [desktop/desktop#11077]
There is a problem with large repositories, impossible to download all the repository.

To solve the problem of data, please add this feature directly in the Desktop software:
- git –depth n (with "n": a number of choice, example "1")

Important for:
- GitHub company (less bandwidth + eco responsibility + saving money)
- Users (less disk space + less bandwidth + eco responsibility + saving money)
- Server admins (less backup space + less local and external bandwitch + eco responsibility + saving money)
- Providers (less bandwidth + eco responsibility + saving money).

Thanks in advance.

Links:
- https://linuxhint.com/git-shallow-clone-and-clone-depth/
- https://www.perforce.com/blog/vcs/git-beyond-basics-using-shallow-clones
- https://ahmadawais.com/shallow-clone-large-git-repository/
- https://git-scm.com/docs/git-fetch
- https://git-scm.com/docs/git-clone
- https://www.google.com/search?q=git+–depth+1
- ...

**Comment by billygriffin** [comment]
Thanks for the issue! This is still under consideration as part of #3480, but isn't currently prioritized and likely will not be something we're working on in the next several months at least. But this is helpful and we'll update that issue if we are able to prioritize this work. Thanks again.

**Comment by Neustradamus2** [comment]
@billygriffin: Thanks for your reply but the specified ticket has been closed, when it is closed it is not good...
