### ISSUE TITLE
Pre-commit Git Hooks do not recognize Flutter command when run through GitHub Desktop

### ISSUE THREAD

**Issue by jtmuller5** [desktop/desktop#11079]
### Describe the bug

I've setup a pre-commit Git Hook inside the .git/hooks/ folder and it will only run when I commit code using bash. If I commit the code using GitHub desktop, the "flutter" commands in my file are not recognized.

### Version & OS

- Windows 10
- GitHub Desktop Version 2.6.0

### Steps to reproduce the behavior

1. Create a new Flutter project and add the pedantic package. Import the package into the analysis_options.yaml file like in the pub.dev instructions
2. In .git/hooks/ add a file called "pre-commit"
3. Add this to it
```
#!/usr/bin/env sh

where flutter
flutter analyze
if [ $? -ne 0 ]; then
  exit 1
fi

flutter test
if [ $? -ne 0 ]; then
  exit 1
fi
```
4. Make a change to the project and commit the changes using bash (everything works fine)
5. Make another change but this time commit using GitHub Desktop

### Expected behavior

The pre-commit hook should work the same in Bash and GitHub Desktop

### Actual behavior

GitHub Desktop doesn't recognize the flutter command even though it knows where the directory is

### Screenshots

![image](https://user-images.githubusercontent.com/47997351/99860142-2c003d00-2b60-11eb-9266-a0b53fe870c9.png)

**Comment by jtmuller5** [comment]
I got this working like this but I'm not sure why the .bat extension is needed for GitHub desktop.
```
#!/bin/env sh
flutter.bat analyze
if [ $? -ne 0 ]; then
  exit 1
fi

flutter.bat test
if [ $? -ne 0 ]; then
  exit 1
fi
```

**Comment by steveward** [comment]
Thanks for letting us know how you go this working @jtmuller5. Issues with pre-commit hooks is something we are aware of -- see https://github.com/desktop/desktop/issues/9351 for an example. Since we're tracking this in other issues I am going to close this out, but let us know if you run into any further problems.
