### ISSUE TITLE
Requesting spell checking functionality 

### ISSUE THREAD

**Issue by shasiru** [desktop/desktop#11078]
Typos often happen during typing commit summary and description and we don't even realize it until it's too late.

Adding a spell checking functionality to the github desktop would help a lot in this case.

**Comment by niik** [comment]
Hi @shasiru, thanks for reaching out! This looks like that same request in #1597 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date with any development happening in that area.

Worth noting is that @Hovemeyer5 has an [open PR](https://github.com/desktop/desktop/pull/10996) right now with a working implementation of this. I'm hoping to get time to review it soon so with a little luck you won't have to wait all that long. No promises though.
