### ISSUE TITLE
'remote-https' is not a git command. 

### ISSUE THREAD

**Issue by ShubK98** [desktop/desktop#11074]
Everytime I try to push a commit I get this error .

I had changed the Environment variables ,but now that I have changed the environment variables path back to normal I am still getting this error

**Comment by billygriffin** [comment]
Thanks for the report @ShubK98. Based on @steveward's guidance from other issues, can you try resetting GitHub Desktop by following these steps?

- Close GitHub Desktop
- Remove all of the files in %LocalAppData%\GitHub Desktop\
- Reinstall GitHub Desktop from http://desktop.github.com

Let us know if that doesn't get things working.

**Comment by ShubK98** [comment]
Tried it . Reinstalled it . Still getting the same error : (

**Comment by steveward** [comment]
@ShubK98 are you running any antivirus/security software that could be interfering with the installation of GitHub Desktop?

**Comment by ShubK98** [comment]
Not running any antivirus . I was able to Push files earlier . But cant anymore  .  Could this be because I changed some Environment variable path or something ?

**Comment by steveward** [comment]
What specific environment variables did you modify? That would give us some more information about whether or not this would affect GitHub Desktop.
