### ISSUE TITLE
Authentication fails despite being signed in

### ISSUE THREAD

**Issue by JimHokanson** [desktop/desktop#11080]
### Describe the bug

When I go to fetch a repository I get an authentication failure despite being signed in. Signing out and signing in again fixes the problem.

### Version & OS

Version 2.6 and Windows 10

### Steps to reproduce the behavior

1. Go to a private repository
2. Click on fetch
3. See authentication error

### Expected behavior

I expect the fetch process to work since I've signed in to my account.

### Actual behavior

A popup shows up saying Authentication failed. 

### Logs

I'm seeing API rate limit exceeded all over my log file. I have maybe 50 repos (maybe 43 by log below) and periodic fetching enabled. 

2020-11-21T01:21:33.714Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 43 repositories took 35.8s of which 0.0s paused, total 35.8s
2020-11-21T01:21:45.172Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: routh_uds - JimHokanson (empty token)
2020-11-21T01:21:45.784Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/JimHokanson/routh_uds.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

### Additional context

Importantly, signing out again and signing in again fixes the problem. I tried uninstalling and reinstalling the application but that did not work. I did not wipe out Git on my machine or the settings for the desktop application. I was hoping to avoid both of those steps ...

**Comment by Joory-86** [comment]
Llllal

**Comment by steveward** [comment]
@JimHokanson thanks for the report -- the `JimHokanson (empty token)` indicates that there was an issue with your authentication token. Logging out and then logging back in like you mentioned should fix this issue. Uninstalling will not work because the locally cached token is not removed unless you manually delete things on your machine to clean up. It looks like you were able to resolve this issue so I'm going to close this out.

**Comment by JimHokanson** [comment]
I should have clarified, this happens all the time. I'm not sure if that's literally every time or every hour or what, but it is quite frequent. So yes, a workaround is present, but it is annoying needing to click so many different buttons.

I just tested a fetch and it works fine; I very much expected it to fail. After posting this I remembered disabling the periodically fetch and refresh option. It seems like enabling that feature shouldn't require causing the problem I'm seeing. I would think ideally the manual and automatic queries could be separated and/or that the automatic queries could be automatically throttled if it gets close to running into limits. I don't think I use any fancy API features (just the desktop on a few computers).

**Comment by steveward** [comment]
If this happens continuously I would recommend "resetting" GitHub Desktop to see if that gets things working:

1. Close GitHub Desktop
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop and log in and add your repositories again
