### ISSUE TITLE
Renaming a file from '.PNG' to 'png' does not register as a change

### ISSUE THREAD

**Issue by pippinmole** [desktop/desktop#11087]
### Describe the bug

Consider file 'image.PNG', referenced in a html file somewhere (which is case sensitive) as 'image.png'. This file will not display in html because of case sensitivity.
Renaming said image and attempting to push will not be possible, as renaming file 'image.PNG' to 'image.png' does not register as a change in GitHub Desktop.

### Version & OS

Windows 10

### Steps to reproduce the behavior

1. Create empty repo
2. Create image.PNG (case sensitive)
3. Commit
4. Rename to image.png (all lowercase)
5. Observe no change

### Expected behavior

Ability to commit this change

### Actual behavior

Does not allow commit

### Screenshots

https://gyazo.com/615ab38d7914d204adcbd6ebf6f505fc

*Note that even though it does lowercase the extension of the file when rename is done, it does still register as 'image.PNG'*

**Comment by niik** [comment]
Hi  @pippinmole, thanks for opening this and sorry to hear you're having problems. The behavior you're observing has to do with the Windows file system being case-insensitive but case-preserving. That is, to Windows a file named `image.PNG` and a file named `image.png` are both the same (as opposed to popular file systems on Linux where you could have `image.png` and `image.PNG` side-by-side.

See this article about [Git case sensitivity](https://docs.microsoft.com/en-us/azure/devops/repos/git/case-sensitivity?view=azure-devops) for more information.

For now there are a few ways to go about solving this. Either you open a command line prompt and run the command specified in the article above (i.e. `git mv -f image.PNG image.png` followed by `git commit`. Or if you want to stay in GitHub Desktop you first rename `image.PNG` to `image_tmp.png`, make a commit, and then rename `image_tmp.png` to `image.png` and commit.

You can also [rename the file directly on GitHub.com](https://docs.github.com/en/free-pro-team@latest/github/managing-files-in-a-repository/renaming-a-file) and then pull that change to your repository.

I hope that helps!
