### ISSUE TITLE
Can't sign in "unable to fetch authenticated user"

### ISSUE THREAD

**Issue by Hans701** [desktop/desktop#11098]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

[2020-11-23.desktop.production.log](https://github.com/desktop/desktop/files/5580871/2020-11-23.desktop.production.log)
[2020-11-22.desktop.production.log](https://github.com/desktop/desktop/files/5580872/2020-11-22.desktop.production.log)

**Comment by niik** [comment]
Hi @Hans701, are you by chance attempting to use GitHub Desktop behind a proxy? I'm seeing errors trying to connect to localhost in the log files

```No connection could be made because the target machine actively refused it 127.0.0.1:8080```

Port 8080 is a common proxy port so I suspect you've got a proxy set up on your machine and for one reason or another that  proxy isn't letting requests from GitHub Desktop through.

**Comment by allanlealluz** [comment]
I have this problem

**Comment by liuhe-trec** [comment]
I also have

**Comment by dhia-gharsallaoui** [comment]
I also have this problem and it's because the entreprise proxy. Any solution ?

**Comment by L261173157** [comment]
I have it too

**Comment by harshil28** [comment]
Look if you are using any vpn..you need to disable it's proxy settings...
Changing proxy settings to default worked for me...

**Comment by redflasher** [comment]
it may be firewall also

> Посмотрите, используете ли вы какой-либо VPN ... вам нужно отключить его настройки прокси ... Изменение настроек прокси на значения по умолчанию сработало для меня ...

**Comment by tanayweb** [comment]
I also had this issue then I checked my proxy settings . Then I have seen a proxy after which I've disabled it . Later my Github desktop was ok and I was able to sign in .....
