### ISSUE TITLE
Cant find "(My User)"

### ISSUE THREAD

**Issue by dustmarijn** [desktop/desktop#11104]
### Describe the bug

If i try to upload a repo and I select the folder where its located it always redirects me to the user folder and says Cant Find "marijnboeve"

### Version & OS

GitHub Desktop: 2.6.0
MacOS: 10.15.6

### Steps to reproduce the behavior

1. Click on add repository
2. Add path to folder
3. Submit

### Expected behavior

Now i would expect to see the good repository if i open the folder.

### Actual behavior

I get to the root folder of my machine and cant see anything of my added repository.

### Screenshots

[http://marijnboeve.nl/screenshot/Schermafbeelding%202020-11-23%20om%2010.31.03.png](http://marijnboeve.nl/screenshot/Schermafbeelding%202020-11-23%20om%2010.31.03.png
)
### Logs

There is no log created.

**Comment by niik** [comment]
Hi @dustmarijn, this can happen if you've accidentally initialized a Git repository in your user folder. Could you check to see if there's a `.git` folder located at `/Users/marijnboeve/.git`?

**Comment by dustmarijn** [comment]
Hai @niik i have found the map in my user folder If i delete this folder my issues would be gone?

**Comment by niik** [comment]
@dustmarijn Most likely, yes, this is assuming that you created the user-directory repository by mistake. I you want to play it safe you can also rename it to something like `.git-backup`, that should have the same effect.

**Comment by dustmarijn** [comment]
@niik Great, i will do that. Thanks for the help!
