### ISSUE TITLE
CAN'T MAKE MY RESPOSITORY

### ISSUE THREAD

**Issue by Harsh0605** [desktop/desktop#11117]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by billygriffin** [comment]
Hi @Harsh0605, please fill out the template so we're able to investigate what might be causing the problem. Without that additional information, there's very little we're able to do to help. Thanks!
