### ISSUE TITLE
Option to automatically stash ignored files when switching branches

### ISSUE THREAD

**Issue by NinoFoxx** [desktop/desktop#11112]
### Describe the feature or problem you’d like to solve

I'm currently working on the v2 of a project and I have some ignored files that I don't wanna commit (certificate keys, etc).

When switching from branch v2 to v1 (for checking something in the old code) and back to v2, the ignored files are lost as expected (?).

The current workaround is to open a terminal and execute `git stash --all` before checking out branch v1, and `git stash pop` after switching back to v2.

### Proposed solution

I believe an option to do this automatically would be very useful and time-saving.

**Comment by steveward** [comment]
Thanks for contributing @NinoM4ster. There's a good explanation of why this happens in [this StackOverflow question](https://stackoverflow.com/a/37213497). Let me know if you have any questions about this.
