### ISSUE TITLE
It is not connecting to my github account

### ISSUE THREAD

**Issue by Jitesh-Gadage16** [desktop/desktop#11113]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help expla
![Screenshot (50)](https://user-images.githubusercontent.com/74908438/100058909-2cdeea80-2e50-11eb-9085-e27979292363.png)
in your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

[](url)

**Comment by steveward** [comment]
Thanks for the report @Jitesh-Gadage16. Can you try going to `File` > `Options` > `Accounts` and verify that you are logged in to your GitHub account? If that does not get things working it would be helpful if you could upload the log file.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
