### ISSUE TITLE
Image Difference Swipe mode bugged

### ISSUE THREAD

**Issue by theolaa** [desktop/desktop#11120]
### Describe the bug

The image difference swipe mode is supposed to let you have a moveable, hard cutoff point on either side of which you can view the differences in an image. The current version locks the left edge of the "old version" of the image to the slider position, rather than the left edge being locked to the left edge of the viewing area (so the images can actually be compared).

### Version & OS

Version 2.6.0
Windows 10 Pro

### Steps to reproduce the behavior

1. Find an image in a commit that was changed (not added or deleted).
2. Select "Swipe" mode from the bottom right
3. Move the slider (the dot on the blue bar), you will see that the previous version of the image moves around with the slider instead of being locked to the left of the viewing area.

### Expected behavior

The image should not move around with the slider, instead, the previous and current versions of the image should occupy the same space in the viewing area, with the slider only hiding and revealing portions of each.

### Actual behavior

The current version of the image remains locked in place (as it should), but the previous version of the image moves around with its left edge locked to the slider's position.

### Screenshots
![image](https://user-images.githubusercontent.com/38194309/100187017-0f377280-2e9c-11eb-9394-c4d84c91317f.png)
![image](https://user-images.githubusercontent.com/38194309/100187006-08a8fb00-2e9c-11eb-83b0-89acf41c3f97.png)
![image](https://user-images.githubusercontent.com/38194309/100186979-f5962b00-2e9b-11eb-8047-9eb2a05671c3.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

I restarted github desktop and the problem persisted. I assume the error occurs for all supported image formats, but in my particular case it occurs with a .bmp file.

**Comment by niik** [comment]
Hi @theolaa, thanks for opening this! I've opened #11124 which should hopefully address this problem as well as make the swipe mode behave even more like it does on GitHub.com. With a little luck we'll have this fix out in the next production release in a few weeks but if you'd like we'd greatly appreciate it if you'd be willing to try it out in the beta version of the app (we should be shipping an update including this fix within a week). Instructions for installing our beta version are available in our [README](https://github.com/desktop/desktop#beta-channel).

**Comment by swipe5** [comment]
[[](url)``](url)

**Comment by swipe5** [comment]
### _**[Sample-20200815T000203Z [](-001.zip](https://github.com/desktop/desktop/files/5607927/Sample-20200815T000203Z-001.zip)**_)

- [ ]

**Comment by swipe5** [comment]
**p[
Duplicate of 

> #

1. 

- [ ]  #@
Duplicate of #

](url)
