### ISSUE TITLE
New branches aren't shown until the next refresh event

### ISSUE THREAD

**Issue by jdngray77** [desktop/desktop#11125]
### Describe the bug

Unless an update occurs, a newly created local branch is not displayed within Desktop Branches drop down menu.

### Version & OS

Desktop 2.6.0,
MacOS  10.12.6

### Steps to reproduce the behaviour

1. Create a staged change that's awaiting commit
2. Open the branches drop down, and select `New Branch`
3. Provide name, and confirm you want to `Create Branch`
4. When prompted about your stage, hit cancel; don't switch branch.

Not switching to the new branch prevents the refresh required to display it in the branches menu.

### Expected behaviour

The branch now exists locally, but is not checked out. It shows in the branch menu, confirming to the user that it was created.

### Actual behavior

The branch now exists locally; it's visible in the CLI, and Desktop recognises it's presence if you attempt to create it a second time.

However, it's not visible within the branches menu until the user performs another action, such as switching repositories or removing focus from and returning focus to the Desktop window, which causes a refresh.

### Additional

This has the possibility to confuse the user by lack of creation confirmation. After pressing 'cancel' and seeing that the branch isn't in the branches list, it's easy to draw the conclusion that the branch wasn't created; yet you're informed it already exists when you try again.

**Comment by niik** [comment]
Thanks for opening this @Shinkson47, I was able to reproduce it and have labelled it accordingly.
