### ISSUE TITLE
Expanding long description in history tab may cause diff display content to 'flicker' up and down vertically

### ISSUE THREAD

**Issue by jkamleh** [desktop/desktop#11127]
### Describe the bug

Entered an 18 character 'Summary; and 1001 character 'Description', when selecting 'Expand' on the description in the History tab of the commit. The contents of the div with 'commit-details' class, flickers up and down rapidly non-stop while the mouse is hovering the div with class 'commit-summary-description'. 

Note: doesn't occur in fullscreen (maximized) mode. Occurred on 1780 x 933px windowed mode

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.
Version 2.6.0, Windows 10 Enterprise

### Steps to reproduce the behavior

1. On 'Changes' tab, Enter 18 character 'Summary; and 1001 character 'Description', commit (push to origin?)
2. Select 'History' tab, select the most recent commit (the one we just pushed)
3. Click the 'Expand' button (expander)
4. Move mouse around the commit details/summary sections or off the app all together
5. Close, GitHub desktop and re-open and the issue still occurs.

### Expected behavior

View the expanded summary without this flickering (e.g. just like any other commit)

### Actual behavior

Commit details top border shifting up and down rapidly

### Screenshots

Cannot provide video at this stage without blurring sensitive information

### Logs

N/A

### Additional context

N/A

**Comment by niik** [comment]
Hey @jkamleh, thanks for opening this. Unfortunately I haven't been able to reproduce the issue. Would you be able to create a commit which experiences these issues containing non-sensitive information and push that to a public repository?
