### ISSUE TITLE
Mac app starts crazy slow on MacBook Air M1

### ISSUE THREAD

**Issue by viktoriakrasznai** [desktop/desktop#11126]
### Describe the bug

Mac app starts crazy slow on MacBook Air M1

### Version & OS

Version 2.6.0

macOS Big Sur (M1)

### Steps to reproduce the behavior

It happens always when starting the app.

### Expected behavior

To be as quick as before.

### Actual behavior

It's crazy slow.

**Comment by jdngray77** [comment]
This may have more to do with the new M1 ARM architecture and Rosetta 2 translating from x86_64 to AArch64 upon load than Desktop itself.

As quoted in [this](https://www.somagnews.com/apple-m1-chip-macbooks-can-be-slow-to-launch-apps/) article,

> If an executable contains only Intel instructions, macOS automatically launches Rosetta and starts the translation process. When the translation is finished, the system launches the translated executable in place of the original. However, the translation process takes time, so that users should notice that translated applications start or run more slowly at times.

> Users will notice that applications ‘bounce’ on the dock for approximately 20 seconds while this process is complete. 

Edit:
However it also says
> subsequent application launches will be fast.

**Comment by dennisameling** [comment]
A native version of GH Desktop for M1 on the Mac is possible, but requires an upgrade to Electron 11. GH Desktop is currently at 9.3.1. Work on this is underway in https://github.com/desktop/desktop/pull/11021, please keep an eye on that PR!

**Comment by jmparsons** [comment]
Mine opens quickly - m1 mini, but the fetches take extra calls to authorize properly, a simple pull can take +1 minute or more.

**Comment by niik** [comment]
I haven't been able to reproduce this on my mac mini M1, it starts just as snappy as on my Intel macbook pro. Without more information there's not much we can  do here as it's not affecting all M1 macs. I'm going to close this out but if you can come up with anything more actionable we'd be happy to take another look @aczel.

**Comment by niik** [comment]
Oh, I meant to say that just like @dennisameling said we are working towards shipping an arm64 build of Desktop which should alleviate this problem if it is indeed related to rosetta translation.

**Comment by jmparsons** [comment]
One thing I noticed is it's only slow with ssh mode, with https it's fast!
