### ISSUE TITLE
Multiple user accounts

### ISSUE THREAD

**Issue by mralexsaavedra** [desktop/desktop#11135]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by niik** [comment]
Thanks for the issue. This is captured in #3707 so please just leave a 👍 there if this is something you want. Since this is a duplicate I'm going to close it.
