### ISSUE TITLE
Not detecting local changes

### ISSUE THREAD

**Issue by Mgregchi** [desktop/desktop#11137]
### Describe the bug

First Error : Application pops up error : " Can't find "repository" It was last seen at "C:\Users\path". Meanwhile the repository was just created and still in the location.

Second Error : Failing to detect and update local changes in a repository. And also ignoring some files if published.

### Version 2.4.3 & OS Microsoft Windows 10 Pro Version 10.0.17134 Build 17134

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Go to 'View'
2. Click on 'Repository list'
3. Select 'One of the repository'
4. See Can't find "repository-name"

### Expected behavior

First : Open application find current repository without getting "Can't find repository" even when it is still in the last location.

Second : Open application, create a repository and add some other files to it, and changes should be detected and updated. Publish complete repository files without leaving some.

### Actual behavior

First : Can't find repository error on opening the Desktop app. If i use the locate option few minutes past same problem again.

Second : When changes are made to a repository, the Github app fails to detect and update. And it ends up publishing some of repository files while leaving others behind.

### Screenshots

Some Screenshots

.

### Logs
![Screenshot (41)](https://user-images.githubusercontent.com/56840758/100486644-0695a500-3105-11eb-93eb-a4639ab48123.png)
![Screenshot (43)](https://user-images.githubusercontent.com/56840758/100486646-085f6880-3105-11eb-9033-76d4f464a47d.png)

### Additional context

The above issues started a day ago while trying to publish a new repository. At first though it was connection issues which i checked and my data connection was working as expected.

**Comment by steveward** [comment]
Thanks or the report @Mgregchi. Are you storing repositories in a mapped network drive or a syncing service like OneDrive/Dropbox on your machine? That can sometimes cause issues like this.

Could you also upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Mgregchi** [comment]
@steveward Thanks for your response.
No I don't store my repositories syncing services, just on the "C: " Drive.

Here's log file :
[2020-11-27.desktop.production.log](https://github.com/desktop/desktop/files/5632370/2020-11-27.desktop.production.log)

Thanks

**Comment by steveward** [comment]
@Mgregchi Can you try resetting GitHub Desktop by following these steps?

1. Close GitHub Desktop 
2. Open File Explorer and remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop (you will need to log in and add your repositories again)
