### ISSUE TITLE
Double click a file to open it in the default editor

### ISSUE THREAD

**Issue by the21st** [desktop/desktop#11149]
### Describe the feature or problem you’d like to solve

I often review my changes in Github Desktop and when I spot something I want to correct I usually right click the file and choose "Open with default editor". Double-clicking to do the same would be a lot faster.

### Proposed solution

More efficient way to open files. Double-click seems to be unused so it should be low-hanging fruit.

### Additional context

N/A

**Comment by steveward** [comment]
Thanks for the feedback @the21st! I'm going to roll this into https://github.com/desktop/desktop/issues/4655 where we are tracking quicker ways to open files.

**Comment by digitalmaster** [comment]
This is request is now being rolled into https://github.com/desktop/desktop/issues/2620
