### ISSUE TITLE
Why is the Github desktop not released for Linux?

### ISSUE THREAD

**Issue by CCCCCCCCCCCCCCCCCCCCCCCCCCCC33** [desktop/desktop#11145]
**Why is the Github desktop not released for Linux?
Github Is based On Electron But Not Releasing For Linux.
Why ????**

**Comment by niik** [comment]
Hey, thanks for reaching out! This looks identical to the request in https://github.com/desktop/desktop/issues/1525 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date with any development happening in that area.

I will mention that there is an unofficial fork of GitHub Desktop available for Linux: https://github.com/shiftkey/desktop. Hope that helps!
