### ISSUE TITLE
GithubDesktop won't open

### ISSUE THREAD

**Issue by barbamento** [desktop/desktop#11141]
### Describe the bug

I don't know why but my pc won't open a github process if i try to run it:
I tried to open it from the icon and through cmd but it doesn't start any process.

### Version & OS

GitHub: 2.5.7
Windows 10 build: 19041.630

### Steps to reproduce the behavior

1. Click on githubdesktop link
Or:
1.Open cmd.exe
2.go to githubdesktop directory
3.start GitHubDesktop.exe from there

### Expected behavior

To open github desktop

### Actual behavior

Litterally nothing happens

### Additional Information

I've seen that this is not the first thread on the argument, but all the solution in this one ( https://github.com/desktop/desktop/issues/6835 ) or in this one ( https://github.com/desktop/desktop/issues/3757 ) won't work

**Comment by molheiser** [comment]
I had the same issue this morning, the desktop would not open, no message, nothing.  I was able to fix my issue by going to the Github application folder (C:\Users\YOURNAME\AppData\Local\GitHubDesktop) and renaming the latest "app-" folder so it would not use it.  Apparently, the last download/update did not work.

**Comment by steveward** [comment]
Thanks for the report @barbamento. This does sound like a potential update issue. You can try the steps @molheiser shared, and if that does not work I would recommend fully deleting the `%LocalAppData%\GitHubDesktop` directory and reinstalling. Let me know how that goes.

**Comment by steveward** [comment]
@barbamento as we have not heard back from you I am going to close this issue out. Let me know if you are continuing to have problems and we can dig into this further.

**Comment by Vadimde88** [comment]
So, Hello everybody! I found my own solution by clicking the 2nd mouse on the github desktop shortcut and deleting the "Start in" row. Or you can try renaming it to any previous folder name app- etc.
Thank you and have a good day!

**Comment by gwilku** [comment]
GitHub 2.8.0 doesn't open as well.

**Comment by sputnik190033** [comment]
> So, Hello everybody! I found my own solution by clicking the 2nd mouse on the github desktop shortcut and deleting the "Start in" row. Or you can try renaming it to any previous folder name app- etc. Thank you and have a good day!

Thanks! This works well for me.

**Comment by thejeffreyallen** [comment]
Issue still happening 04/2022 molheiser's fix above worked

**Comment by RieSadohara** [comment]
Same here, Issue still happening 04/2022 and molheiser's fix above worked.

**Comment by Strooss** [comment]
i got this issue now
