### ISSUE TITLE
git: 'remote-https' is not a git command. See 'git --help'.

### ISSUE THREAD

**Issue by mangeshugale100** [desktop/desktop#11144]
git: 'remote-https' is not a git command. See 'git --help'.

**Comment by niik** [comment]
Hey @mangeshugale100, we've seen a few of these errors pop up recently and we're gonna use #10345 to track them so please follow that issue for any updates. If you could also answer the questions in https://github.com/desktop/desktop/issues/10345#issuecomment-673450605 that'd be really helpful.
