### ISSUE TITLE
"Open in Visual Studio Code" from Github Desktop

### ISSUE THREAD

**Issue by Daggerpov** [desktop/desktop#11148]
Adding this button to Github Desktop will allow users to open their repositories from Github Desktop with their IDE (not sure if it works with other IDEs other than VSC). I've had this feature on Mac and Windows. 

There's no reason why this feature shouldn't be included, so I don't feel as though I really have to explain this. 

I'm currently using the Flatpak version of VSC, which may be what's causing this issue to not show up.

**Comment by niik** [comment]
Hi @Daggerpov, we do support Visual Studio Code, see your list of supported editors in https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md. I'm not familiar with Flatpak but a quick google leads me to believe it's related to packaging on Linux, is that correct?

GitHub Desktop doesn't officially support running on Linux although there's a popular fork available at https://github.com/shiftkey/desktop. If flatpak is linux-specific I would suggest raising an issue over there. It looks like they look for VS Code in `/snap/bin/code` and `/usr/bin/code` so it's possible adding the flatpak version of that path would do the trick for you.

In the meantime I'm going to close this out but if I'm mistaken about this referring to Linux please let me know and we can reopenn.

**Comment by Daggerpov** [comment]
Yes, I actually wanted to open this issue under the shiftkey fork of VSC.
