### ISSUE TITLE
repositories doesnt appear

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#11157]
### Describe the bug

My repositories doesnt appear on my github desktop app

### Version & OS

Version 2.6.0
windows 10

### Expected behavior

Have all my repositories available to donwload

### Actual behavior

My repositories doesnt appear

### Screenshots

![image](https://user-images.githubusercontent.com/29644665/100769103-e5320300-33fb-11eb-9be3-07e429137dfe.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the report @alvaroac99. Have you tried clicking the `Refresh this list` option? I would also recommend selecting the `Clone a repository from the internet` option to see if your repositories appear there. Let me know if you still do not see them appear.
