### ISSUE TITLE
Partition stats collection by Enterprise and Dotcom?

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#1115]
@tierninho brought this up in https://github.com/desktop/desktop/issues/1064:

>Should Desktop offer separate tracking for Enterprise and Personal accounts, as some users may opt out as there organization requires so, yet personally they do not care. We miss out on this data by keeping them bundled. Perhaps we can add a tracking option in the Prefs pane?

It might be tricky to make that distinction with some stats (e.g., launch time applies to the app and not the repository). But might be worth thinking about.

**Comment by telliott27** [comment]
This isn't a big concern for me right now - I don't think we'd see a big enough increase in metrics reporting for the work it would require.

**Comment by shiftkey** [comment]
Works for me
