### ISSUE TITLE
Cant fetch origin

### ISSUE THREAD

**Issue by willb155** [desktop/desktop#11153]
### Describe the bug

Every time I fetch origin I get the same result. I have looked for answers online but it didn't work

[2020-11-30.desktop.production.log](https://github.com/desktop/desktop/files/5617744/2020-11-30.desktop.production.log)

### Version & OS

Version 2.60, Windows 10 

### Expected behavior

I expected my branch to update

### Actual behavior

remote: Enumerating objects: 255, done.        
remote: Counting objects: 100% (255/255), done.        
remote: Compressing objects: 100% (64/64), done.        
error: RPC failed; curl 56 Failure when receiving data from the peer
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Sorry to hear you're having issues fetching @willb155. A few questions:

- Are you by chance located behind a proxy server? That's a common cause for this type of error. 
- Are you able to fetch from the repository using the command line? 

There are some recommendations for troubleshooting connection errors [in this help article](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/troubleshooting-connectivity-problems#troubleshooting-slow-downloads-and-intermittent-slow-connections) that may be helpful as well.

**Comment by willb155** [comment]
Hi sorry for getting back to you so late, I have tried this command line "git config http.postBuffer 524288000" if thats the one you were referring to. I am not behind a proxy server

**Comment by steveward** [comment]
@willb155 running that command usually is not necessary anymore since Git has made improvements in this area. I was referring to whether or not a `git fetch origin` completes successfully via the command line. Could you try running that and let me know if it succeeds?

**Comment by willb155** [comment]
It wasnt successful

**Comment by sum2012** [comment]
My forked source don't update.
I need run the following command,

edit: git remote add upstream https://github.com/hrydgard/ppsspp.git 
git fetch upstream
git merge upstream/master
git submodule update --init --recursive

**Comment by steveward** [comment]
@willb155 are you still having issues fetching from GitHub? Switching to using SSH may get things working if you are having HTTPS connection issues. You can follow [this guide](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) for steps about setting up SSH. You can set the SSH remote in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`.

I'm going to close this out as this is not a specific issue with GitHub Desktop, but let me know if you have any other questions.
