### ISSUE TITLE
Cloneing Repository with Similar Name

### ISSUE THREAD

**Issue by Batfoxkid** [desktop/desktop#11158]
### Describe the bug

A repository with a similar name is cloned instead of chosen repository.

### Version & OS

Version 2.6.0
Windows 10 Home

### Steps to reproduce the behavior

1. Add a new repository via cloning
2. Search a clone a repository that uses a similar name, either GitHub.com or URL
3. One repository takes priority and is cloned instead

### Expected/Actual behavior

To choose the specific repository but instead chooses another with a similar name

### Screenshots

![GitHubDesktop_f8180puclr](https://user-images.githubusercontent.com/15969488/100786593-3a075680-33c7-11eb-9faf-b4f946982f22.png)

In this example I want to clone Batfoxkid/SuperZombieFortress but instead chooses Batfoxkid/SuperZombieFortressRedux to clone, filepath however is the same as choosen.

**Comment by steveward** [comment]
Thanks for the report @Batfoxkid. It looks like you are running into https://github.com/desktop/desktop/issues/3855. Here's how you can resolve this:

1. Close GitHub Desktop
2. Delete `C:\Users\<your_user>\AppData\Roaming\GitHub Desktop\Cache`
3. Restart GitHub Desktop

Let me know if that does not get things working and we can dig into this further.
