### ISSUE TITLE
Merge Conflicts

### ISSUE THREAD

**Issue by GraceBelt** [desktop/desktop#11166]
Hello Madam or Sir, 
I have merge conflicts in my team's GitKraken. I don't know where to find it or how to solve merge conflicts. I need big help today.

**Comment by GraceBelt** [comment]
Hello Madam or Sir,
I have merge conflicts in my team's GitKraken. I don't know where to find it or how to solve merge conflicts. I need big help today.

**Comment by billygriffin** [comment]
Hi @GraceBelt, this is the GitHub Desktop repository, which is a separate product from GitKraken. So we aren't able to help with questions related to GitKraken. Apologies and best of luck.
