### ISSUE TITLE
Github Desktop will not fetch/push, but git from command line works fine.

### ISSUE THREAD

**Issue by jmanthony3** [desktop/desktop#11177]
### Describe the bug

BUG: remote-curl.c:1342: The entire rpc->buf should be larger than LARGE_PACKET_MAX
fatal: expected flush after ref listing

### Version & OS

Version: 2.6.0
OS: Windows 10

### Steps to reproduce the behavior

A. If seeking to clone repo to local machine
     1. Go to clone a repository.
     2. Pick repository of interest.
     3. Push clone.
B. If seeking to fetch/push origin of already cloned repository.
     1. Select repository of interest.
     2. Push fetch/push origin.

### Expected behavior

I would expect the fetch/push origin command to execute with no problem. 

### Actual behavior

Git commands from Windows Command Line execute with no problem, and Github Desktop even updates to see that the repository was "fetched/pushed just now".

### Screenshots

From Github Desktop: 
![image](https://user-images.githubusercontent.com/62029937/101175369-1b959b00-3613-11eb-9cf4-fc1dc3686634.png)

From git command line: 
![image](https://user-images.githubusercontent.com/62029937/101175437-2c461100-3613-11eb-95a2-50b89a037206.png)

From Github Desktop (to show new time of fetch):
![image](https://user-images.githubusercontent.com/62029937/101175494-39fb9680-3613-11eb-92de-61d680c29ba4.png)

### Logs

[2020-12-04.desktop.production.log](https://github.com/desktop/desktop/files/5643336/2020-12-04.desktop.production.log)

### Additional context

Error was first noticed when adding a file exceeding 100 MB limit for a single repository (I was much newer to Github at the time and did not know about LFS until after the fact). Since then, have added problematic files to .gitignore, have removed the files from the repo, pruned the repo, and attempted to completely clean Github/git from computer's hidden files to reinstall application(s). But now I cannot clone any of my other repositories to my personal machine. The most annoying part is that on another Windows 10 machine (with the same versions/setup of Github Desktop/command) I use for work, everything works fine. I can clone repositories, fetch/push origins, etcetera all from Github Desktop or Git command.

**Comment by steveward** [comment]
Thanks for the report @jmanthony3.

> But now I cannot clone any of my other repositories to my personal machine. The most annoying part is that on another Windows 10 machine (with the same versions/setup of Github Desktop/command) I use for work, everything works fine.

Are you seeing this same error when you attempt to clone any repository in GitHub Desktop? This looks like an underlying cURL error. 

>attempted to completely clean Github/git from computer's hidden files to reinstall application(s). But now I cannot clone any of my other repositories to my personal machine. 

Did you remove `%LocalAppData%\GitHubDesktop` and then reinstall?

**Comment by jmanthony3** [comment]
This error persists with any repository, yes. And I had cleaned the folder to reinstall with no change in performance.

Joby M. Anthony III
Mechanical Engineering (Mathematics) ‘20
Graduate Research Technician I
School of Engineering


[http://www.liberty.edu/media/1616/40themail/wordmark-for-email.jpg]

Liberty University  |  Training Champions for Christ since 1971

**Comment by jmanthony3** [comment]
Update: After performing a clean install of Windows 10 on personal machine, Github Desktop works just fine.
