### ISSUE TITLE
Cannot clone any repository

### ISSUE THREAD

**Issue by zawaung7791** [desktop/desktop#11178]
### Describe the bug

When cloning any repository off Github, Threejs for example.
The connection is lost and cannot complete cloning.
Gets to 15% download and then has errors and stops

### Version & OS

V2.60
MacOs 11.0.1

### Steps to reproduce the behavior

1. Click on "clone a repository from the internet"
2. Enter URL
3. Click Clone
4. See error and attached screenshots

### Expected behavior

The repository to be cloned

### Actual behavior

Get error message 

### Screenshots

![image](https://user-images.githubusercontent.com/385527/101205660-de0e2d80-3665-11eb-8478-781c917a6589.png)

![image](https://user-images.githubusercontent.com/385527/101205787-0eee6280-3666-11eb-8245-d3ea6bbb8926.png)

![image](https://user-images.githubusercontent.com/385527/101205841-1f9ed880-3666-11eb-90cb-6dd1f760b8cc.png)

### Logs

[2020-12-04.desktop.production.log](https://github.com/desktop/desktop/files/5644964/2020-12-04.desktop.production.log)

### Additional context

Happens with both deskop programme and CLI

**Comment by steveward** [comment]
@zawaung7791 I'm seeing a couple of errors in the log file:

```
Error: Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. See https://github.com/Squirrel/Squirrel.Mac/issues/182 for more information.
```
Can you verify that you are running GitHub Desktop inside your `~/Applications` directory and not the `Downloads` directory?

The second error I'm seeing is the one you mentioned:

```
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

Since this is happening from both the command line and GitHub Desktop this is likely a specific network issue. Are you on a reliable network connection?

**Comment by zawaung7791** [comment]
Hi Steve,

Thanks for the reply,

I've added to the Applications folder now
I'm in the UK and using my home broadband provided by TalkTalk
Have connected my desktop to my mobile hotspot from my phone and is past the usual 15% with threejs.
I've even tried disabling my firewall on my router, to help with github, but still no improvement.
Is there anything I can do?

**Comment by zawaung7791** [comment]
Have uninstalled Anaconda from my mac (python dev environment and apps) and now github is working?

**Comment by niik** [comment]
Hey @zawaung7791, I'm glad to hear Desktop is working for you again. As this seems to be an issue specific to your environment I'm going  to close this issue.
