### ISSUE TITLE
Requesting authentication & failing when trying to clone from Gitlab.

### ISSUE THREAD

**Issue by LordMilitus** [desktop/desktop#11185]
When I attempt to clone anything from GitLab into GitHub Desktop, it tells me my authentification isn't working and I get the following image (see attachment). This was an issue on my old laptop too, I had to use my friends laptop. I have moved countries now and can no longer do this. I have attempted a common log-out and log-in fix, but it did not work for me as it requires you to log in through browser now.

This is a clean install on a machine it has never been on before. I work on a team so I cannot make my own GitLab either, so cloning really has to work here. 
![d34c9881c07049a91b5992876e785243](https://user-images.githubusercontent.com/65270089/101266859-3c650a00-3753-11eb-9ddd-5e2229018bd8.png)

Desktop Version 2.6.0
Windows 10

**Comment by LordMilitus** [comment]
I got this now after I kept trying.

![6f6935762e2cbf1e1f9ebbf7d619d797](https://user-images.githubusercontent.com/65270089/101346024-40467880-3888-11eb-8024-a625e0bf9406.png)

**Comment by steveward** [comment]
@LordMilitus please follow the instructions here that walk through authenticating with GitLab:

https://github.com/desktop/desktop/blob/development/docs/integrations/gitlab.md

Let me know if you run into any problems.

**Comment by LordMilitus** [comment]
> @LordMilitus please follow the instructions here that walk through authenticating with GitLab:
> 
> https://github.com/desktop/desktop/blob/development/docs/integrations/gitlab.md
> 
> Let me know if you run into any problems.

I didn't even get to that screen now to attempt it. I now have the error I showed in the comment above yours.

Ontop of this, I had a token previously and had been able to access the GitLab on another laptop roughly half a year ago.

**Comment by steveward** [comment]
@LordMilitus I would try opening `Credential Manager` and deleting the existing GitLab credential that GitHub Desktop stores there. Once you do that try authenticating again to see if that succeeds. If that does not get things working please share the log file from GitHub Desktop. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by LordMilitus** [comment]
@steveward Hey again and thanks for the reply,

I can't seem to find the Credential Manager in either Desktop or GitLab. Do you mean in GitLab under 'Active personal access tokens (1)' ? I've gone ahead and gotten the logs already just incase. The one dated 5th should be prior to my new issue as well.

[2020-12-05.desktop.production.log](https://github.com/desktop/desktop/files/5654865/2020-12-05.desktop.production.log)
[2020-12-07.desktop.production.log](https://github.com/desktop/desktop/files/5654866/2020-12-07.desktop.production.log)

**Comment by steveward** [comment]
@LordMilitus you can see how to access the credential manager here:

https://support.microsoft.com/en-us/windows/accessing-credential-manager-1b5c916a-6a16-889f-8581-fc16e8165ac0

There should be an entry under `Windows Credentials` that has your GitLab token that is stored by GitHub Desktop. Try deleting that and then generating a new token via the steps in the help document I shared. Let me know if that does not get things working.

**Comment by LordMilitus** [comment]
@steveward 

I did that and it still has the new error of Clone Failed: URL returned error: 404

**Comment by steveward** [comment]
A 404 error indicates that the URL cannot be found. Are you seeing that error or this one still?

`fatal: unable to access 'https://gitlab.com/Zapdude/mod.git/': The requested URL returned error: 400`

That's a different error than a `404`. If you're having specific issues accessing your GitLab repository you may need to reach out to GitLab support for assistance.

**Comment by LordMilitus** [comment]
I meant 400, I'm just so used to memes about 404, my bad! I'll try that and then return to this. Thanks.

**Comment by LordMilitus** [comment]
Still haven't gotten a reply. Do you think making a new account would fix this? It's a bit of a last resort but..

**Comment by LordMilitus** [comment]
It SEEMS to work now! The 400 error disappeared on it's own and the steps provided above worked!

**Comment by steveward** [comment]
I'm glad to hear things are working now! I'm going to close this out.
