### ISSUE TITLE
Live HTML website not updating after pull request

### ISSUE THREAD

**Issue by mjbtax** [desktop/desktop#11183]
### Describe the bug

My website mjbtax.ca is not updating after the last few Pull Requests. Ive updated text only and its not appearing on the live website. I build and have the repository on my desktop using Github Desktop. No issues up until 24 hours ago, no subsequent pull requests or other updates/changes to html code are appearing on live website. Not sure how to maybe 'reset' the live website so it just runs the updated html code properlty.
 

### Version & OS

Version 2.6.0, using Microsoft Surface, 64 bit OS, windows 10 pro. 

### Steps to reproduce the behavior

See describe.

**Comment by niik** [comment]
Hey @mjbtax, this is the repository for the open source GitHub Desktop application. It sounds like you're having issues with GitHub Pages which we're not able to provide support for here. Please see https://support.github.com/ for ways to find support with GitHub Pages.

I'm going to close this out as it doesn't seem related to GitHub Desktop but if I'm mistaken please let me know and we'll see about reopening.
