### ISSUE TITLE
Boot looping

### ISSUE THREAD

**Issue by RunnersNum40** [desktop/desktop#11184]
### Describe the bug

When I try to open a repository with a large number of files I get an error "Maximum call stack size exceeded." If I hit exit and restart or close the window or end to the process in task manager the application boots again and then crashes with the same issue. This results in a boot loop. Even after restarting my desktop Github Desktop continues to boot loop.

### Version & OS

Version: 2.6.0
OS: Windows 10.0.19041

### Steps to reproduce the behaviour

Try opening a viewing a repository with many files

### Logs
I cannot access the application so all I have is the error report

RangeError: Maximum call stack size exceeded
    at Rm (file:///app/renderer.js:59:16576)
    at file:///app/renderer.js:59:15957
    at file:///app/renderer.js:45:243596
    at Em.render (file:///app/renderer.js:59:11792)
    at ko (file:///app/renderer.js:37:62856)
    at Eo (file:///app/renderer.js:37:62651)
    at Do (file:///app/renderer.js:37:66489)
    at Bs (file:///app/renderer.js:37:90287)
    at Hs (file:///app/renderer.js:37:90671)
    at ka (file:///app/renderer.js:37:97697)

Version: 2.6.0
OS: Windows 10.0.19041

### Additional context
I was trying to view https://github.com/RunnersNum40/ESC180

**Comment by niik** [comment]
Hey @RunnersNum40, sorry to hear you're having problems. Please see #11111:


---

> The crash you're experiencing is coming from the new split diff mode that we released in 2.6.0. It's been fixed in #11064 but hasn't shipped to production yet.
> 
> I'm not sure why exactly you're seeing this problem but in our testing we found that complex (i.e most often large) diffs are the culprit. In order to work around the problem you can either attempt to manually commit or stash your changes in your repository before opening GitHub Desktop (and then switching back to the unified diff mode) or you can try resetting GitHub Desktop by following these steps
> 
> - Close GitHub Desktop
> - Remove all of the files in %LocalAppData%\GitHub Desktop\
> - Open GitHub Desktop  again
> 
> Let us know if that doesn't get things working. Please note that resetting means that you will have to sign in again and add your repositories.

You may also try downloading the [latest beta version](https://github.com/desktop/desktop#beta-channel) which does include the fix. I'm going to close this issue since it's describing the same problem as #11111.
