### ISSUE TITLE
Transaction committed too early

### ISSUE THREAD

**Issue by niik** [desktop/desktop#11192]
Extracting https://github.com/desktop/desktop/issues/11176#issuecomment-739507650 into its own issue

---

@hubgit: I'm getting a slightly different error after downloading the latest beta from the link above (which I have been using, not sure if I'd accidentally switched back to stable):

![image](https://user-images.githubusercontent.com/14294/101282265-02841a00-37cc-11eb-8db5-38378fecc701.png)

This is macOS 11.0.1, and I have been using GitHub Desktop for quite a long time.

Nothing's logged when running the script above in Dev Tools, so I guess it's not an undefined `parentID`.

It's working ok again after removing `~/Library/Application\ Support/GitHub\ Desktop`.

**Comment by ttasovac** [comment]
I have this same issue. I tried the script from https://github.com/desktop/desktop/issues/11176#issuecomment-738921088 but that didn't work for me.

I have way to many repos so adding them all manually again is not an option.

**Comment by niik** [comment]
@ttasovac Could you estimate how many repositories you have tracked? I'm trying to understand the root cause of this and I haven't been able to reproduce it.

@hubgit Did you also have tons of repositories?

**Comment by ttasovac** [comment]
ok, maybe I was being a bit of a drama queen, I don't have "tons" of repositories, but probably around 20-30...

**Comment by niik** [comment]
@ttasovac Are there any other errors or log messages in your DevTools console? Make sure you've got the `Verbose` log level selected as well

![image](https://user-images.githubusercontent.com/634063/101332713-f0f74c80-3875-11eb-9a43-a0f289fac3d5.png)

**Comment by ttasovac** [comment]
I do actually have one additional error before the one quoted above. It's also a transaction-committed-early kind of error, but slightly different:

<img width="547" alt="Снимок экрана 2020-12-07 в 10 54 31" src="https://user-images.githubusercontent.com/5304839/101336333-a5936d00-387a-11eb-8888-2da3302d320f.png">

**Comment by niik** [comment]
@ttasovac Thanks! Could you please copy and paste the contents of the stack, and _stack properties respectively?

**Comment by niik** [comment]
@ttasovac @hubgit Could either (preferably both) of you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload the most recent log file where you experienced the problem.

**Comment by ttasovac** [comment]
ok, here we go:

**stack**
"PrematureCommitError: Transaction committed too early. See http://bit.ly/2kdckMn
    at file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:45:216690
    at file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:45:201900
    at cr (file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:45:197102)
    at pr (file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:45:197587)
    at hr (file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:45:197438)"

**_stack**
"PrematureCommitError: Transaction committed too early. See http://bit.ly/2kdckMn
    at file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:45:216690
    at file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:45:201900
    at cr (file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:45:197102)
    at pr (file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:45:197587)
    at hr (file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:45:197438)"

**log** 

[2020-12-07.desktop.beta.log](https://github.com/desktop/desktop/files/5653314/2020-12-07.desktop.beta.log)

 I see that a couple of repos i've been tracking do not exist anymore.

**Comment by niik** [comment]
@ttasovac Thanks a bunch! I've got a fix lined up for this in #11198 and I'm aiming to publish a new beta release in a few hours, I'll update here but since you can't launch the app you'll have to download the latest beta manually.

**Comment by niik** [comment]
The beta channel has been updated to 2.6.1-beta3 which includes a fix for this issue. If you don't receive automatic updates please download the latest version from https://github.com/desktop/desktop#beta-channel. Should the problem persist after upgrading please let us know about it!
