### ISSUE TITLE
Unusable pixelated/corrupted graphics upon startup

### ISSUE THREAD

**Issue by Bazindigo** [desktop/desktop#11200]
### Describe the bug

Every time I open up the app, I am presented with an unusable pixelated screen. I can tell that in the background it says 'Welcome to GitHub' Desktop, but I cannot click any buttons or get to any other view in the app. Restarting the app does not help, nor does uninstalling/reinstalling.

### Version & OS

Version: It will not let me open the about menu (grayed out), but I would assume 2.6.0 as I downloaded it from the [desktop.github.com](url) today.

OS: macOS 11.0.1

### Steps to reproduce the behavior

1. Go to 'desktop.github.com'
2. Click 'Download for macOS'
3. Unzip and open the app (in macOS 11.0.1)

### Screenshots

![Screen Shot 2020-12-08 at 12 03 56 PM](https://user-images.githubusercontent.com/25091199/101530319-fd030d00-394e-11eb-84a1-6775d24d97ec.png)

### Logs

[2020-12-08.desktop.production.log](https://github.com/desktop/desktop/files/5661356/2020-12-08.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @Bazindigo. I see that you are running macOS Big Sur -- are you also possibly using a new Macbook with the M1 chip?

**Comment by Bazindigo** [comment]
No, I'm running it on a late 2019 16" MBP. 

Adding on to the problem, I just found this process hogging a bunch of CPU even while the app is closed (the last time I opened it was to file the original report):
<img width="417" alt="Screen Shot 2020-12-08 at 1 30 57 PM" src="https://user-images.githubusercontent.com/25091199/101539680-22e2de80-395c-11eb-94f1-0297442c5be1.png">

**Comment by niik** [comment]
Hey @Bazindigo, looks like something odd is going on either with your graphics card drivers or the graphics card itself. Have you rebooted your machine recently?

You can try launching GitHub Desktop with GPU accelerated rendering turned off to verify that it is indeed related to the GPU by running the following command from a Terminal window

```
GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1 open -b com.github.GitHubClient
```

If that makes GitHub Desktop render normally you could try following any of the numerous [guides](https://www.lifewire.com/troubleshooting-mac-display-problems-4121097#:~:text=Restart%20Your%20Mac&text=Restarting%20your%20Mac%20puts%20everything,restarts%20everything%20in%20orderly%20steps.) out there on troubleshooting your macOS graphics.

**Comment by Bazindigo** [comment]
I just tried launching it again, and for whatever reason, it worked this time. I'm unfortunately unable to reproduce this bug any more. Thanks so much for your help!
