### ISSUE TITLE
4 video fix height but add more video not a responsive

### ISSUE THREAD

**Issue by kalpesh1711** [desktop/desktop#11204]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by kalpesh1711** [comment]
![Uploading 12_9_2020, 12_46_02 PM.png…]()

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by kalpesh1711** [comment]
i want solution thats problem

**Comment by niik** [comment]
@kalpesh1711 Hey, I'm having problems understanding what it is you're looking for. This is the repository for the open source project GitHub Desktop and your question seems to be related to video somehow. If you're having a problem with GitHub Desktop please fill out the details in the issue template and provide a thorough explanation of your problem.

**Comment by kalpesh1711** [comment]
I work in make a app and web for video conferencing for group calling based.
all ready that is completed but some issue
in right side video height fixed but more than 4 video not a responsive on desktop version
![12_9_2020, 12_46_02 PM](https://user-images.githubusercontent.com/73703967/101623415-6c0b5f00-3a3e-11eb-9187-9c0ec07833a3.png)

**Comment by kalpesh1711** [comment]
please check I worked 6 video in right side but not a responsive

**Comment by kalpesh1711** [comment]
please check I worked 6 video in right side but not a responsive

**Comment by niik** [comment]
Hey @kalpesh1711, this is the repository for the [GitHub Desktop](https://desktop.github.com) product (a Git/GitHub client). It looks like you have a question about a project that you're building. Such questions are best asked on developer Q/A sites such as https://stackoverflow.com/.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question **about GitHub** please check out [GitHub support](https://support.github.com).

Best of luck!
