### ISSUE TITLE
⭐Add support for multi user switching ⭐

### ISSUE THREAD

**Issue by sssppp57** [desktop/desktop#11211]
To have a way to switch between Github user accounts is seriously needed for this app.  There is a related pull request https://github.com/desktop/desktop/pull/9499

**Comment by steveward** [comment]
Thanks for the feedback. We are in the process of thinking through detecting correct commit attribution to ensure commits are made as the correct GitHub user. You can follow along in https://github.com/desktop/desktop/issues/610 for updates about this. At this time we don't have any plans to support multiple users, but that may be something we revisit again in the future. I'm going to close this out, but feel free to drop any feedback you have in that issue.
