### ISSUE TITLE
Not authenticating while trying to clone a repo

### ISSUE THREAD

**Issue by xhashimks** [desktop/desktop#11216]
Till yesterday I was able to fetch the repository using github desktop. Now I am not able to clone the repository. It says "we are unable to authenticate to github.com server". I gave the correct credentials but still problem. In web, I am able to login and download code. Also github desktop preferences -> account is logged in. But whenever i tried to clone, it asks for user id and password (even though its logged in) and it throws above error after input the correct credentials.

I tried restart my mac machine, re-install github desktop, re-sign github etc. But still getting above issue. Please help. This is blocking my dev activities. I am using latest app.

[2020-12-11.desktop.production.log.zip](https://github.com/desktop/desktop/files/5677574/2020-12-11.desktop.production.log.zip)

**Comment by steveward** [comment]
@xhashimks thanks for the report. It looks like the specific clone that is failing is from an organization that you belong to. I did verify that the permissions are correct so repository access should not be an issue. Can you confirm whether or not you are able to clone private repositories from your personal user account? If you are then this may be a specific organization setting issue.

**Comment by xhashimks** [comment]
@steveward I tried with other credentials which has all the rights and also i tried with my personal id to pull my personal branch(not from organisation). Still same issue.

**Comment by xhashimks** [comment]
@steveward Somehow this issue got resolved yesterday. You may please close this. Thanks!

**Comment by steveward** [comment]
I'm glad to hear things are working now @xhashimks!
