### ISSUE TITLE
Error when cloning

### ISSUE THREAD

**Issue by samalsib** [desktop/desktop#11217]
### Describe the bug

we were unable to authentication in github.com. Please enter username and password is repeatedly getting displayed when trying to clone a repository.

### Version & OS

Version 2.6.0

### Steps to reproduce the behavior

1. Go to  File->Options in GitHub Desktop
2. Click on 'Sign In'
3. Sign In with browser
4. Enter your username and password
5. Redirected to GitHub Desktop
6. Assigned repositories are displayed
7. Select a repository
8. Clone repository
9. Error displayed after sometime to fill up username and password
10. enter username and password
11. Click on Save and Try
12. After sometime again same error

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.
![image](https://user-images.githubusercontent.com/71323305/101877663-5fa91280-3bb4-11eb-96de-6dcb6085a8e5.png)

### Logs

Attach your logs by openi
[2020-12-11.desktop.production.log](https://github.com/desktop/desktop/files/5677791/2020-12-11.desktop.production.log)
ng the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

It was working fine and suddenly from yesterday stopped working.

**Comment by steveward** [comment]
@samalsib thanks for the report. I verified that you have the correct permissions to clone this repository, so I'm not sure why this specific repository is failing to clone. Are you able to clone any other repositories within this organization?

**Comment by samalsib** [comment]
Hi Steve,

Thanks for looking into this.
I am not able to clone any repository within this organization.

To give you a background, yesterday all of a sudden I was getting below
error on GitHub Desktop.
Hence I uninstalled and re-installed GitHub Desktop. Then I am getting this
error.

Authentication failed. Some common reasons include:- You are not logged in
to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to
confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the
ssh-agent and associated with your account.

Please let me know if you need any other input.

Thanks,
Sibasish

**Comment by steveward** [comment]
@samalsib are you able to clone private repositories from your personal GitHub account? If you don't have any private repositories could you try creating one and then seeing if you are able to clone it in GitHub Desktop? That would help narrow down what the issue is.
