### ISSUE TITLE
MacOS - UI goes white with no escape

### ISSUE THREAD

**Issue by avaer** [desktop/desktop#11219]
### Describe the bug

UI sometimes goes white when committing on MacOS M1. There is no fix other than to force shut down of the app.

### Version & OS

MacOS M1
GHD Version 2.6.0

### Steps to reproduce the behavior

Open some repos.
See changes in the repo.
Commit
[2020-12-12.desktop.production.log](https://github.com/desktop/desktop/files/5682181/2020-12-12.desktop.production.log)
.
Keep window not maximized, just some normal size (don't know if it matters).
UI will go completely while sometimes.
Three is no escape from this other than to shit down the app entirely.

### Expected behavior

The UI never goes blank/white when using the app.

### Actual behavior

The UI sometimes randomly goes white when committing from the UI.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attached.

**Comment by steveward** [comment]
Thanks for the report @avaer. We've seen reports of this happening in https://github.com/desktop/desktop/issues/10128 with the Developer Transition Kit., but not with actual production M1 hardware. To verify this isn't the same as https://github.com/desktop/desktop/issues/4054 can you try deleting the following directory and then try launching GitHub Desktop again?

`~/Library/Application Support/Github Desktop/IndexedDB`

Let me know how that goes.

**Comment by kobakaxa** [comment]
> ### Describe the bug
> UI sometimes goes white when committing on MacOS M1. There is no fix other than to force shut down of the app.
> 
> ### Version & OS
> MacOS M1
> GHD Version 2.6.0
> 
> ### Steps to reproduce the behavior
> Open some repos.
> See changes in the repo.
> Commit
> [2020-12-12.desktop.production.log](https://github.com/desktop/desktop/files/5682181/2020-12-12.desktop.production.log)
> .
> Keep window not maximized, just some normal size (don't know if it matters).
> UI will go completely while sometimes.
> Three is no escape from this other than to shit down the app entirely.
> 
> ### Expected behavior
> The UI never goes blank/white when using the app.
> 
> ### Actual behavior
> The UI sometimes randomly goes white when committing from the UI.
> 
> ### Screenshots
> Add screenshots to help explain your problem, if applicable.
> 
> ### Logs
> Attached.
> 
> ### Additional context
> Add any other context about the problem here.

**Comment by avaer** [comment]
I deleted that directory, will post if I see the lockup again. It is random so it might take a bit.

**Comment by avaer** [comment]
I saw the white screen of death again just now. It is still an issue.

**Comment by avaer** [comment]
Here is a screenshot.

<img width="991" alt="Screen Shot 2020-12-19 at 8 56 16 PM" src="https://user-images.githubusercontent.com/6926057/102703438-aa71fc80-423c-11eb-9974-3da9d8d1830c.png">

**Comment by avaer** [comment]
I am seeing this a few times an hour now -- making Github Desktop functionally unusable.

**Comment by lmcd** [comment]
Seeing this every so often on macOS Big Sur on M1 hardware

**Comment by jackprosser** [comment]
This is happening constantly in the latest version and makes this app useless.

**Comment by PeterMain** [comment]
Seeing this on M1 also. usually happens after an action, like creating new branch. Restart fixes it, but very annoying.

**Comment by wyand-sp** [comment]
Same for me as well. I'm with the latest version of Github Desktop.

**Comment by psyzz** [comment]
same for me

**Comment by avaer** [comment]
For anyone else with this issue, Github Desktop doesn't support M1 macs.

Maybe one of these years they will add support, but in the meantime the fix is to uninstall Github Desktop.

You can uninstall Github Desktop from the macOS Applications directory. After that the github.com site should work fine and you won't have to deal with these issues anymore.

<img width="364" alt="Screen Shot 2021-03-20 at 11 01 23 AM" src="https://user-images.githubusercontent.com/6926057/111874440-a5236b80-896b-11eb-9a7c-ede53a27ff2d.png">

**Comment by AhmedMugtaba** [comment]
I have this issue as well, as the app is useless, I use Mac mini M1

**Comment by koenpunt** [comment]
Electron has support for ARM Mac, and I managed to compile a version of the app using the arm64 architecture. I did have to manually recompile some native dependencies, and had to comment out about 10 lines of code, but it has been running smooth ever since.

And I just noticed that something I had to change to make it work has already landed on the `development` branch, so I'm assuming someone is working on M1 support already.

**Comment by koenpunt** [comment]
While updating my private build, it seems that I only had to recompile the `keytar` dependency for the arm64 arch, which can be achieved using:

    npm rebuild --arch=arm64 --target_arch=arm64 keytar

**Comment by geojorg** [comment]
Arm Build
https://github.com/desktop/desktop/pull/11969#issuecomment-823987465

**Comment by sergiou87** [comment]
Thanks for posting the link here @geojorg! ❤️ 

Please let me know if you can still reproduce the issue with that ARM build, hopefully you cannot 🤞

**Comment by geojorg** [comment]
@sergiou87 Is working smooth and fast !!!

**Comment by steveward** [comment]
Closing as resolved.
