### ISSUE TITLE
Deactivate my account until I get secure devices he’s on he got my reset link before ne

### ISSUE THREAD

**Issue by Btrfly79** [desktop/desktop#11215]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by niik** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with accessing or resetting your account please see GitHub's [support site](https://support.github.com/) for more information.

Best of luck!
