### ISSUE TITLE
Menu Option To Reset???

### ISSUE THREAD

**Issue by CanadianJeff** [desktop/desktop#11227]
instead of having to open a git bash window and type in `git reset --hard` just have a menu option to do this in just 1 click

**Comment by steveward** [comment]
@CanadianJeff thanks for the feedback. GitHub Desktop has a `Undo` option that allows you to `reset` your most recent commit. You should see the option above the commit button. The changes will still be in your working directory, but you can then discard them if you would like to remove them. This only works for commits that have not yet been pushed up to the remote repository on GitHub. I hope that helps!

**Comment by CanadianJeff** [comment]
but what about commits that was pushed to my fork that was pushed by mistake?
