### ISSUE TITLE
Switch to current branch

### ISSUE THREAD

**Issue by mstein-ck** [desktop/desktop#11235]
### Switch to current branch

When selecting the current branch from the branches dropdown, I get the prompt to stash my changes or bring them over. If I select "bring over" nothing happens but if I select "stash", my changes are stashed.

### Version & OS

Version 2.6.1
Windows 10

### Steps to reproduce the behavior

1. Go to 'Branches'
2. Click on the current branch

### Expected behavior

Nothing should happen or there should be a message that you are already on this branch

### Actual behavior

Acts as if it is switching branches

### Screenshots

![image](https://user-images.githubusercontent.com/47797106/102253663-a0b36680-3ed5-11eb-8a61-151a6faaecb7.png)

### Additional Context

This issue occurs when there are changes present on the current branch and "Ask me where I want my current changes to go" is set.

**Comment by billygriffin** [comment]
Thanks for the issue @mstein-ck! I totally agree that this is valid and we shouldn't attempt to checkout a branch you're already on. Looks like @niik already has a PR in place (✨) so this should be fixed in an upcoming release. Really appreciate you letting us know.
