### ISSUE TITLE
Impossible to create new branch after resolving merge conflicts

### ISSUE THREAD

**Issue by SGanT** [desktop/desktop#11239]
### Describe the bug

After bringing changes from one branch to another there occured merge confilct, which was successfully resolved (green ticks near filenames appeared). But GitHub still asks to resolve first index when attempt to create new branch. Conflicts resolved in VS Code.

### Version & OS

Win 10

### Steps to reproduce the behavior

1. Code something in one branch
2. Try to bring it to another branch so that merge conflict appears
3. Resolve it
4. Try to create new branch without committing

### Expected behavior

New branch created, changes brought to it

### Actual behavior

System asks to resolve first index

**Comment by steveward** [comment]
Thanks for contributing @SGanT. This is the expected behavior in Git. When you encounter a merge conflict it needs to be resolved and committed prior to switching/creating branches. Let me know if you have any questions about this.
