### ISSUE TITLE
Pull request from forked repo: "A branch with that name already exists."

### ISSUE THREAD

**Issue by shilman** [desktop/desktop#11238]
### Describe the bug

After upgrading to 2.6.1 (apparently), re-selecting a PR branch from a forked repo fails with the error "A branch with that name already exists."

### Version & OS

- GH Desktop: 2.6.1
- MacOS: 10.14.6

### Steps to reproduce the behavior

1. Clone the storybook repo: https://github.com/storybookjs/storybook
2. Select a PR from a forked branch, e.g. `pr/13142`
3. Select a non-forked branch, e.g. `next`
4. Re-select the PR from the forked branch in #2
5. See error "A branch with that name already exists."

Note that selecting a second PR from the same fork, e.g. `pr/13429`, will succeed after performing these steps. And then selecting another branch and re-selecting `pr/13429` will fail with the same error.

### Expected behavior

I expect to be able to freely switch between branches, including PRs from forked repos.

### Actual behavior

Selecting a branch on a forked repo fails the second time around.

### Logs

```
2020-12-16T02:11:24.810Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune github-desktop-BarryThePenguin (took 2.222s)
2020-12-16T02:11:25.178Z - error: [ui] `git branch pr/13429 github-desktop-BarryThePenguin/update-ember-cli` exited with an unexpected code: 128.
stderr:
fatal: A branch named 'pr/13429' already exists.

(The error was parsed as 26: A branch with that name already exists.)
```

### Additional context

- Checking out PRs from forked repos is a regular part of my workflow, and the problem seems to have been introduced very recently, probably in `v2.6.1`.
- Manually deleting the branch locally on the command line `git branch -d pr/13429` is a temporary workaround.

**Comment by niik** [comment]
Thanks so much for the report @shilman, really appreciate the clear reproduction steps and pertinent log excerpt. I've been able to reproduce this and I've got a fix coming in a bit.

**Comment by exzolink** [comment]
Not fixed

**Comment by FernandoGarcia** [comment]
Hi @niik!

I'm facing this problem in version 2.7.2 with Ubuntu 18.04.

Best regards.

**Comment by fnehmer** [comment]
Facing the bug in Version 2.8.6 (x64) Windows aswell

**Comment by smappinc** [comment]
Yep still an issue, not fixed

**Comment by jlund24** [comment]
for those with this issue, here's how I resolved it on GitHub Desktop:
- in your forked branch (e.g. "master"), select History in the left panel
- click "select Branch to Compare..."
- select "upstream/master" or your comparable branch that has a conflict to be resolved
- this will bring up a dialog for actually resolving the conflicts

**Comment by ghost** [comment]
اشكركم جميعا ماذا على ان افعل ارجوا المساعدة لتصحيح الاخطاء

**Comment by Gulfick** [comment]
> for those with this issue, here's how I resolved it on GitHub Desktop:
> 
> * in your forked branch (e.g. "master"), select History in the left panel
> * click "select Branch to Compare..."
> * select "upstream/master" or your comparable branch that has a conflict to be resolved
> * this will bring up a dialog for actually resolving the conflicts

I have that bug in Version 3.2.3 (x64). But **jlund24** solution above helped me.
