### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by calvario2308** [desktop/desktop#11233]
### Describe the bug
When i try to clone a repository from a internet https url, i get the same error "authentication failed please enter your username and password and try again

### Version & OS

Version 2.6.1

### Steps to reproduce the behavior

1. Go to 'Clone the repository from the internet'
2. Click on 'URL'
3. See error 'Authentication Failed'

### Expected behavior

To clone the repository properly

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

![Sem Título](https://user-images.githubusercontent.com/75980522/102212520-457d7600-3ecd-11eb-9ed1-cccad09e1e99.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by jdngray77** [comment]
Reproduced with a GitLab account that was made via `sign up with GitHub`, however I could authenticate manually by defining a password for my GitLab online, then entering my *git**lab*** e-mail and password.

Seems that GitHub accounts cannot always naturally authenticate GitLab accounts, even when they were created via GitHub. Are you sure you're using the credentials for your *git**lab***, not  *git**hub***?

**Comment by steveward** [comment]
@calvario2308 can you try logging out and then logging back in by going to `File` > `Options` > `Accounts`? If that does not get things working please share the log file from GitHub Desktop.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by calvario2308** [comment]
Im trying to clone a repository from gitlab, yes! may that be the problem?

**Comment by steveward** [comment]
@calvario2308 if you are authenticating to a GitLab account you will need to follow the steps here:

https://github.com/desktop/desktop/blob/development/docs/integrations/gitlab.md

Let me know if you run into any issues with that.
