### ISSUE TITLE
Shortcut for Commit button

### ISSUE THREAD

**Issue by OneQuy** [desktop/desktop#11232]
The title it is.

**Comment by jdngray77** [comment]
Assuming you mean *keyboard* shortcuts, Desktop has  `CTRL / CMD + Enter` to commit, however it doesn't seem to be well documented.

A full list of keyboard shortcuts can be found [here](https://docs.github.com/en/free-pro-team@latest/desktop/installing-and-configuring-github-desktop/keyboard-shortcuts); it does not include it.

**Comment by steveward** [comment]
Thanks for opening this @OneQuy and for sharing the shortcut @Shinkson47. I've just opened a PR to have this added to our shortcut list. I'm going to close this out.
