### ISSUE TITLE
GH Desktop will not open a PR from the browser "Open with Desktop" feature

### ISSUE THREAD

**Issue by elbuhofantasma** [desktop/desktop#11236]
### Describe the bug

When attempting to open the following PR using the "Open with Desktop" feature in the browser, GitHub Desktop will open but the PR will not open. Github Desktop will start with the last opened project and not the intended PR.

PR: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9033
### Version & OS

Version 2.6.1
Windows 20H12

### Steps to reproduce the behavior

1. Go to https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9033
2. Click on 'Open with Desktop'
3. Let GitHub Desktop start
4. See that the PR was not opened in GitHub.

### Expected behavior

The PR will open in GitHub Desktop, allowing the user to interact with that PR.

### Actual behavior

GitHub Desktop runs, but opens the last used repository and branch.

### Logs

[2020-12-15.desktop.production.log](https://github.com/desktop/desktop/files/5698182/2020-12-15.desktop.production.log)

**Comment by billygriffin** [comment]
@elbuhofantasma Thanks for the report! To make sure I understand, had you already cloned the repo in question and had it in Desktop prior to trying to open the PR in Desktop? I'm wondering whether it has something to do with the PR being from a fork that isn't yours, but I think it should still open. If you don't mind sharing more detailed repro steps including whether the repo was already cloned in Desktop, and whether the same behavior happens for a PR that isn't from someone else's fork, that'd be really helpful. Thanks!

**Comment by elbuhofantasma** [comment]
Hi @billygriffin! You are very welcome for the report! I did have the repo (microsoft/mrtk-unity not the rogpodge/mrtk-unity) cloned previously in Desktop prior to trying to open the PR in Desktop. When I was attempting to find a workaround for this issue, I deleted the repo and tried to clone it fresh from 1. the PR and 2. the base repo but still had this issue occur. 

I mostly test the code instead of committing it, but in my account's private repo, I am able to use the 'Open with Desktop' feature without running into this issue. 

I am not entirely sure what information you are looking for from the more detailed repro steps, but I will provide as much information as I am able to publicly. Other than that, I have been using the 'Open with Desktop' button for the last 6 months with this configuration without any issue. 

It might also be important to note that I am unable to use the GH CLI to grab the PR, I just get the start of a clone, then the errors "Aborting" and "exit status 1" when running the command. 

GitHub Desktop cloned repositories:
Private repo 1
Private repo 2
Private repo 3
Private repo 4
@elbuhofantasma account private repo 5
https://github.com/microsoft/MixedReality-Unreal-Samples
https://github.com/microsoft/MixedReality-UXTools-Unreal
https://github.com/microsoft/MixedRealityToolkit-Unity

1. Open https://github.com/microsoft/MixedReality-UXTools-Unreal in Github Desktop
2. Close GitHub Desktop
3. Navigate to https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9033 in a browser
4. Click the 'Open with Desktop' option
5. GitHub Desktop opens to https://github.com/microsoft/MixedReality-UXTools-Unreal instead of the PR from MRTK-Unity.

**Comment by billygriffin** [comment]
@elbuhofantasma Thanks for the additional info. Unfortunately I'm unable to reproduce this with the two repos in question and the PR that you referenced. 😕 For me, the PR was checked out in Desktop using the "Open in Desktop" button without any issue. 

@steveward Do you have any ideas?

**Comment by steveward** [comment]
@elbuhofantasma I was unable to reproduce this as well. It may be a local caching issue -- could you try clearing out GitHub Desktop's local cache to see if that fixes this issue? Here's how to do that:

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop -- you will need to log in and add your repositories again

Let me know if you're still able to reproduce this problem after these steps.

**Comment by elbuhofantasma** [comment]
You're welcome @billygriffin! I am following your steps now @steveward 

I also forgot to mention that I am apart of the org and team in GitHub that owns the repository. The repo that is submitting the request is also apart of the same org and team.

**Comment by elbuhofantasma** [comment]
@steveward I am still running into the issue after following your steps. Here is the log output: 
[2020-12-17.desktop.production.log](https://github.com/desktop/desktop/files/5712156/2020-12-17.desktop.production.log)

**Comment by steveward** [comment]
@elbuhofantasma I'm seeing this error in the log file now:

```
Error: Resource protected by organization SAML enforcement. You must grant your OAuth token access to this organization.

```

Can you try approving GitHub Desktop in your organization? See [this article](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/approving-oauth-apps-for-your-organization) for how to do that.

**Comment by elbuhofantasma** [comment]
@steveward I will look into that, but it might take some time since people are out for the holidays. Also does not having GitHub Desktop approved in my org account for not being able to use the 'git' command to grab the PR? I have tried using 'git' and the GitHub CLI with the same inability to access the PR. 

I had never had a problem with using GitHub Desktop with this repository previously, and I do not have any issues with adding the repository to GitHub Desktop, or pulling the project down with GitHub Desktop either. Only when trying to open any PR from the MRTK-Unity repository do I run into this problem. I also have no issues with using GitHub Desktop to open a PR and my personal account that is not apart of any org.

**Comment by steveward** [comment]
@elbuhofantasma GitHub CLI and a Git command line token need to be authorized in your organization as well. You should see the `Enable SSO` option in https://github.com/settings/tokens which would approve them for use in your organization. It's possible this setting was only recently enabled in your organization which would explain why it previously worked.

**Comment by elbuhofantasma** [comment]
Thank you for the information @steveward, this has been helpful in trying to sort this issue out. I am closing this issue out since it seems like an org configuration problem and not a problem with GitHub Desktop.
