### ISSUE TITLE
git hub desktop setup

### ISSUE THREAD

**Issue by Bernaaaa** [desktop/desktop#11245]
when i have to link my account on the aapplication on desktop it requires me so sign in from te site by clicking sing in. When I click it it opens up internet explore and I have to click to agree to continue. But it doesn't let me i can't click on agree and i have already verified my e-mail so it should work but it doesn't.

**Comment by steveward** [comment]
@Bernaaaa thanks for the report. Could you try switching the default browser on your machine to something like Google Chrome or Firefox? It would also be helpful if you could share a screenshot of what you are seeing.

**Comment by Bernaaaa** [comment]
thank you for the support! I've set google chrome as default browser and
now it works and it lets me to accept the terms. Thank you again :)

Il giorno gio 17 dic 2020 alle ore 17:09 Steve Ward <
notifications@github.com> ha scritto:

**Comment by MRTECHLAD** [comment]
No more emails please
