### ISSUE TITLE
100 MB file size issue

### ISSUE THREAD

**Issue by TM818** [desktop/desktop#11247]
I have a project I'm attempting to initially commit to a new github repo. 

I've deployed lfs, but I believe, based on research, the issue is that I attempted the commit prior to doing so, so desktop is trying to re-commit the file every time. 

The issue is - I have no idea which file it is. Why would the software not indicate which file is the one causing the issue? I have thousands of files in my project, and I do not see anything offhand that exceeds 100 MB, but obviously it's in there somewhere. 

Am I missing something or does this software really simply print that "100 MB file" error but provide no way to see which file it is?

**Comment by steveward** [comment]
@TM818 if the file is in the history of your repository it will need to be removed. There's [a guide](https://docs.github.com/en/free-pro-team@latest/github/managing-large-files/removing-files-from-a-repositorys-history) that walks through how to do that.

The specific large files should be discoverable directly from the log file. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. You can search in the most recent log for `100MB` and it should show the specific files that are blocking the push. I'd also be happy to help if you want to upload the log file to this issue.

**Comment by TM818** [comment]
@steveward Thank you for the response - I identified the file via the logs, I followed these exact steps, and the issue remains. 

When I git push (or attempt to push via the desktop client), I receive this error:

$ git push --set-upstream origin main
Uploading LFS objects: 100% (503/503), 780 MB | 0 B/s, done.
Enumerating objects: 1167, done.
Counting objects: 100% (1167/1167), done.
Delta compression using up to 20 threads
Compressing objects: 100% (1140/1140), done.
Writing objects: 100% (1167/1167), 368.12 MiB | 10.72 MiB/s, done.
Total 1167 (delta 104), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (104/104), done.
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: bc0864f6ebb10772eb7862bf19018aa55390c657729b764835f4790b8ef79c05
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File Content/Movies/VAudio/TPA_SH_1.uasset is 633.62 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/TM818/ProjectManhattan_V1.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/TM818/ProjectManhattan_V1.git'

So, while in this directory: /c/ght/code/projects/ProjectManhattan_V1 

I run the following (as instructed) and receive this error: 

$ git rm --cached /c/ght/code/projects/ProjectManhattan_V1/Content/Movies/VAudio/TPA_SH_1.uasset
fatal: pathspec 'C:/ght/code/projects/ProjectManhattan_V1/Content/Movies/VAudio/TPA_SH_1.uasset' did not match any files

... This is because I have already deleted this via these same instructions previously - as evidenced when I execute: 

Victor@VicAWR11Dev MINGW64 /c/ght/code/projects/ProjectManhattan_V1 (main)
$ git commit --amend -CHEAD
[main b24398a] Delete TPA_SH_1.uasset
 Date: Thu Dec 17 05:53:22 2020 -0600
 1 file changed, 3 deletions(-)
 delete mode 100644 Content/Movies/VAudio/TPA_SH_1.uasset

But when I git push, I get:

$ git push --set-upstream origin main
Uploading LFS objects: 100% (503/503), 780 MB | 0 B/s, done.
Enumerating objects: 1167, done.
Counting objects: 100% (1167/1167), done.
Delta compression using up to 20 threads
Compressing objects: 100% (1140/1140), done.
Writing objects: 100% (1167/1167), 368.12 MiB | 10.72 MiB/s, done.
Total 1167 (delta 104), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (104/104), done.
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: bc0864f6ebb10772eb7862bf19018aa55390c657729b764835f4790b8ef79c05
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File Content/Movies/VAudio/TPA_SH_1.uasset is 633.62 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/TM818/ProjectManhattan_V1.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/TM818/ProjectManhattan_V1.git'


...As such, I cannot delete the file via the specified instructions. I try to do the same thing via Github desktop, same issue. 

Any idea as to why? What am I missing?

**Comment by steveward** [comment]
@TM818 if the file was not committed in the most recent commit the `git rm --cached` command will not work. You will need to use BFG cleaner or `git filter-branch` which is mentioned in [this article](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/removing-sensitive-data-from-a-repository). Let me know if you have any questions about this.
