### ISSUE TITLE
Refresh all projects replicated locally.

### ISSUE THREAD

**Issue by ChrisNoelBritto** [desktop/desktop#11240]
### Describe the feature or problem you’d like to solve

This is about getting the latest changes of code from all the projects that I have linked to my local system.

### Proposed solution

It would be nice, if there is a refresh button or so, that I can use, which will iterate through all the projects and do a get latest on my GitHub Desktop.

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
Thanks for contributing @ChrisNoelBritto. GitHub Desktop automatically performs periodic background fetches for each of your repositories and displays the ahead/behind status in the repository list. We actually recently added the ability to disable this in `Preferences/Options` > `Advanced` menu option. I hope that's helpful! If you have any questions about this let us know.
