### ISSUE TITLE
Spoilers for repository list

### ISSUE THREAD

**Issue by b5414** [desktop/desktop#11246]
### Describe the feature or problem you’d like to solve

For example, if I am a collaborator in more than 3 accounts, then it causes some difficulty in choosing a repository in this list every time.

I'm about: Pic1 (or ~same window when cloning, but it has a search bar..)

### Proposed solution

Spoilers, I propose to introduce spoilers there, or make a small transition, i.e. display accounts list first, then their repositories - after click.

And there must be a way to disable it in options, for example, who does not need it due to the small number of repositories\accounts..

### Additional context

Until today, I thought that your account goes first, then others, but this is just an alphabetical list.

Pic1 - https://imgur.com/IIIHUBn

**Comment by billygriffin** [comment]
@b5414 Thanks for the issue. As I'm sure you can imagine, this is a difficult problem to solve well for everyone using Desktop with varying use cases and types of repos. We're not planning any upcoming work in this area as it's something people build muscle memory around and having multiple accounts isn't something we generally support more broadly at this point in time. So I'm going to close this issue, but we appreciate your feedback!

**Comment by b5414** [comment]
@billygriffin I didn't mean "multi-account", I meant "I'm a collaborator for different accounts", namely displaying them in the list of local repositories, it would be great if each of the accounts [whose repository on my computer] would be a hiding list.

https://imgur.com/TXpmaQ5 (right - is what I meant)
`***` + _Number_ are accounts, Your \ Company \ Collaborator, whatever
`***` are repos

Now you need to scroll through all repos, but I'm suggesting "drop-down lists" 🙃
