### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by karialo** [desktop/desktop#11251]
### Describe the bug

Simply unable to log in, getting a 404 not found error.

### Version & OS

PopOS 20.10, using GitHub Deskop Version 2.4.1-linux1

### Steps to reproduce the behavior

1. Open app
2. try log in with username / email and password, failed
3. try log in with website (which is already logged in) brought me to the page to confirm authorised access
4. nothing. i've tried signing in with website again, and firefox doesn't understand the address, apparently.

### Expected behavior

I expected to be able to log in.

### Actual behavior

Not letting me log in, with either email or username. 

### Screenshots

![Screenshot from 2020-12-17 20-58-50](https://user-images.githubusercontent.com/65705552/102543471-423fe100-40ab-11eb-9ac6-9284292adddf.png)
![Screenshot from 2020-12-17 20-58-35](https://user-images.githubusercontent.com/65705552/102543473-42d87780-40ab-11eb-91c4-fc52e466c4b2.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@karialo for issues with the Linux fork of GitHub Desktop please open an issue in https://github.com/shiftkey/desktop. It looks like you may be running into https://github.com/shiftkey/desktop/issues/134. I'm going to close this issue out -- thanks for using GitHub Desktop.
