### ISSUE TITLE
Diff viewer could benefit from an option to disable line wrapping

### ISSUE THREAD

**Issue by dustinlineweber** [desktop/desktop#11253]
### Describe the feature or problem you’d like to solve

The change diff viewer currently wraps lines, without an option to disable this functionality.  I've never seen a diff tool or any tool dealing with code that wraps lines, but wrapping being present in Desktop makes me realize there are many situations wrapping diffs and code is not ideal.

### Proposed solution

If line wrapping were optional, code could remain formatted as intended, readability (for us mortals) would no longer be hindered, differing characters could be compared directly in close spatial context (vs across multiple lines), and more lines could be represented in the view.  Even a compromise of only wrapping on whitespace, some selection of stop characters, or something else the grammar of the detected language informs would help readability (comprehension and speed), since users would no longer have to mentally stitch together mid-word breaks.

**Comment by steveward** [comment]
Thanks for the feedback @dustinlineweber. I'm going to roll this into https://github.com/desktop/desktop/issues/11052.

**Comment by dustinlineweber** [comment]
Thanks @steveward !  No idea how I didn't find that issue.

**Comment by dustinlineweber** [comment]
I will note, just in case some subset of solutions exist that can't solve both, that I wasn't even commenting at all about the side-by-side view (as https://github.com/desktop/desktop/issues/11052 seems to be focused on).  There is definitely heavy overlap.
