### ISSUE TITLE
Pull requests not updating

### ISSUE THREAD

**Issue by RMWMStevens** [desktop/desktop#11265]
### Describe the bug

Pull requests no longer update, even when clicking the refresh button manually. This worked just fine before the latest version, if I recall correctly. At least, I didn't notice anything then.

### Version & OS

Windows 10 20H2
Github Desktop v2.6.1

### Steps to reproduce the behavior

1. Be part of any repository
2. Click on "Current branch"...
3. Switch to "Pull requests"
4. On the site, create a pull request
5. In Github Desktop, click the "refresh" icon

### Expected behavior

Pull requests update and you can see the latest ones

### Actual behavior

Pull requests do not update and the application needs to be restarted before pull requests are shown correctly again.
Sometimes weird stuff happens with branch names as well.

### Logs

2020-12-21T12:48:46.445Z - info: [ui] [AppStore] loading 1 repositories from store
2020-12-21T12:48:46.447Z - info: [ui] [AppStore] found account: Gladalucio (Roel Stevens)
2020-12-21T12:48:46.708Z - info: [ui] launching: 2.6.1 (Windows 10.0.19042)
2020-12-21T12:48:46.708Z - info: [ui] execPath: 'C:\Users\rshun\AppData\Local\GitHubDesktop\app-2.6.1\GitHubDesktop.exe'
2020-12-21T12:48:47.261Z - info: [ui] Stats reported.
2020-12-21T12:48:55.355Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: eenmaal-andermaal - Gladalucio (has token)
2020-12-21T12:48:56.800Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.402s)

**Comment by niik** [comment]
@Gladalucio thank you so much for opening this and I'm sorry to hear you're having problems. We have confirmed this to be a problem with the latest production version and we've come up with a fix in https://github.com/desktop/desktop/pull/11241. Unfortunately we haven't released the fix to our production channel just yet. For now the best workarounds are to either switch to another repository and then back again as that will force a reload of the PR list or, as you've already found, to restart the app.

You could also try out our [beta channel](https://github.com/desktop/desktop#beta-channel) while you wait for our next official release.

I'm going to close this issue as we've identified the problem and have a fix ready to go in the next release.

> Sometimes weird stuff happens with branch names as well.

Could you open a new issue with more information about this problem?

**Comment by RMWMStevens** [comment]
Thank you for your reply! And my apologies for not seeing that this has already been fixed. I'm still somewhat new to Github and everything surrounding it.

**Comment by niik** [comment]
I wouldn't expect anyone to go looking for merged PRs to find that it was fixed, you were the first to report the issue, we just happened to have caught it internally. Thank you again!
