### ISSUE TITLE
Unable to fetch/pull origin from GitHubDesktop even after login with 2FA and Salesforce Authorization

### ISSUE THREAD

**Issue by savadutha** [desktop/desktop#11260]
Unable to fetch/pull origin from GitHubDesktop even after login with 2FA and Salesforce Authorization.
Getting following error even after successfully signin, this is used to work till last week.

Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.

**Comment by steveward** [comment]
Thanks for the report @savadutha. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by savadutha** [comment]
This seems to be working from 23/12/2020 automatically. Not sure what has been changed in between.

**Comment by savadutha** [comment]
Again facing same issue.
It is giving following error when fetching repository code, push, pull actions.

ERROR
Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.

LOGS
2021-01-07T05:03:02.425Z - info: [main] Received possible protocol arguments: 4
2021-01-07T05:03:02.425Z - info: [main] Processing protocol url
2021-01-07T05:03:02.429Z - info: [ui] [Dispatcher] requesting authenticated user
2021-01-07T05:03:02.538Z - info: [main] Received possible protocol arguments: 3
2021-01-07T05:03:02.541Z - info: [main] Processing protocol url
2021-01-07T05:03:05.576Z - info: [ui] [SignInStore] account resolved
2021-01-07T05:03:05.577Z - info: [ui] [AppStore] adding account savadutha (savadutha) to store
2021-01-07T05:03:18.386Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: eCommerce - savadutha (has token)
2021-01-07T05:03:22.982Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 4.320s)
2021-01-07T05:03:22.983Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/LevisAMA-Atlas/eCommerce.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)

**Comment by steveward** [comment]
@savadutha I do see that the `LevisAMA-Atlas` org has app restrictions in place. Can you verify that GitHub Desktop has been approved for use? See [this help article](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/approving-oauth-apps-for-your-organization).
