### ISSUE TITLE
Not Able to push or pull from GitHub Desktop: error msg: Authentication failed. Some common reasons include:

### ISSUE THREAD

**Issue by Ronak-Godhania** [desktop/desktop#11262]
[2020-12-21.desktop.production.log](https://github.com/desktop/desktop/files/5722569/2020-12-21.desktop.production.log)
### Describe the bug

Not Able to push or pull from GitHub Desktop: error msg: Authentication failed. Some common reasons include:

### Version & OS

Version 2.6.1 : Windows 10

### Steps to reproduce the behavior

Any Pull or Push Request returens the error msg.
### Expected behavior

My code needs to be published but seeing error modal

### Actual behavior

Getting Error Modal

### Screenshots

![image](https://user-images.githubusercontent.com/63836437/102744887-db5b4a00-4380-11eb-8137-43e00a3d7769.png)

### Logs

Check attachment for log files.
[2020-12-18.desktop.production.log](https://github.com/desktop/desktop/files/5722571/2020-12-18.desktop.production.log)

**Comment by Ronak-Godhania** [comment]
I had faced a similar issue last week but It got auto resolved on Monday, but today it is still there.
I have checked all the points mentioned on the pop-up modal..everything seems fine, even my colleague from another system is able to upload the files so the repository exists and my other members are using it.
Why I am facing this issue.

**Comment by steveward** [comment]
Thanks for the report @Ronak-Godhania. Is this error only occurring for this specific repository? Are you able to push/pull from private repositories created under your GitHub account?

**Comment by Ronak-Godhania** [comment]
@steveward Sry for the delay, but I am facing this for all repositories, and it occurs sometime and after a few days it gets auto-resolve now today again I started facing this issue.
Not able to resolve whats exactly is causing this.

**Comment by steveward** [comment]
Can you refer to our [help document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789) and check the Windows registry for Autorun entries? This has been a cause of authentication errors in the past.
