### ISSUE TITLE
License file with old username

### ISSUE THREAD

**Issue by heltonricardo** [desktop/desktop#11272]
Hi!

This is the header of a LICENSE file:

---

MIT License

Copyright (c) 2020 [username]

---

I changed my username. When I create any new repository, the license file is created using my old username.
TIP: I would like to be able to choose the name that will be inserted in license files, so I could choose my real name instead of my current username.

**Comment by niik** [comment]
Hi @heltonricardo, thanks for opening this, we fill out the license file using the name you've configured on your machine to use when creating commits. See https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration for more information on `user.name` and `user.email`. You can configure these values in Desktop by opening Preferences (on macOS) or Options (on Windows) and selecting the Git tab

![image](https://user-images.githubusercontent.com/634063/102904031-6f0c4380-4471-11eb-8448-f7cf2348daf9.png)

I hope that helps!
