### ISSUE TITLE
push error

### ISSUE THREAD

**Issue by sugita3** [desktop/desktop#11270]
### Describe the bug
Enumerating objects: 298, done.
Counting objects: 100% (298/298), done.
Delta compression using up to 4 threads
Compressing objects: 100% (289/289), done.
Writing objects: 100% (289/289), 14.97 MiB | 14.49 MiB/s, done.
Total 289 (delta 150), reused 0 (delta 0), pack-reused 0
error: RPC failed; curl 55 Send failure: Connection was aborted
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
Everything up-to-date
### Version & OS
OS:Windows10
Version:1909
### Steps to reproduce the behavior

I get this error when I commit and push.

I only get this error at home. (This error has occurred about 30 times so far)
This error does not occur in places such as schools where the environment is in place.
I've tried various solutions on the net, but none of them worked.

### Expected behavior

（Normal push）

### Actual behavior
この文章の先頭に書いたエラーがでる
（I get the error I wrote at the beginning of this sentence）
A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

<Solution I tried>
1. Increase the buffer
It didn't work at all

2. Commit little by little
If the amount of commits at one time is quite small, you can commit, but if you put in one SE for about 3 seconds, this error will occur.

3. Recreate the file
It's a way to rename the original file and clone a new one.
Now you can recreate it from scratch, but you'll get this error with just a big commit.

I'm working on it now by repeating the second and third methods dozens of times. I searched for other methods, but I couldn't find a solution and I couldn't proceed.

I am Japanese, so if you are good at Japanese, please reply in Japanese.

**Comment by steveward** [comment]
@sugita3 thanks for the report. The `error: RPC failed; curl 55 Send failure` error usually indicates the `git push` operation is timing out. Since you mentioned this is only occurring at home this is likely a specific issue with your home network. Are you behind a proxy or firewall on your home network that could be interfering with your connection? Are you able to clone repositories without issue?

**Comment by sugita3** [comment]
返信ありがとうございます。スティーブワードさんの言われたところを中心に調べたところ、解決することができました。本当にありがとうございます。

（解決の経緯）
ファイアウォールの中で、VisualStudioのプライベートとパブリックの両方にチェックがついていました。そこで、プライベートの方のチェックを外したところ、正常にpushすることができました。

**Comment by sugita3** [comment]
Thank you for your reply. When I investigated mainly what Steve Ward said, I was able to solve it. thank you very much.

(Background of solution)
In the firewall, both Visual Studio private and public were checked. So, when I unchecked the private one, I was able to push normally.

**Comment by steveward** [comment]
I'm glad to hear you were able to get things working @sugita3!
