### ISSUE TITLE
GitHub Desktop for Linux

### ISSUE THREAD

**Issue by CompeyDev** [desktop/desktop#11273]
### Overall Feature Requested:

I would like it to be available on Linux.

### Proposed solution

Some developers use Linux to build such as me. This is because it has a good environment for developing.

### Additional Context

I use elementary OS. Many Linux distros (like my OS) have their own App Stores making it harder to reach many Linux users. Hence, it would be great if it was available on [SnapCraft](https://snapcraft.io) as it can reach more Linux users.

**Comment by niik** [comment]
Hey @TheAwesomeCoder05, thanks for reaching out! This looks identical to the request in #1525 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date with any development happening in that area.

I will mention that there is an unofficial fork of GitHub Desktop available for Linux: https://github.com/shiftkey/desktop. Hope that helps!

**Comment by CompeyDev** [comment]
Thanks @niik. Sorry for posting an identical issue. I have given that issue a 👍 to show that I would like that to be available. Also, I noticed the unofficial fork but did not install it because I was unsure about its security. Thanks again for replying on a short notice.

**Comment by Saint-R007** [comment]
i cant install my github desktop for my linux elementary os,please fix it for me,so we can learn for other

**Comment by CompeyDev** [comment]
There is currently no official support for Linux that I know of. There is a forked unofficial repository though: https://github.com/shiftkey/desktop. 

**Installation Instructions:**

1. Download this shell script and cd to the folder you saved this to: https://gist.github.com/berkorbay/6feda478a00b0432d13f1fc0a50467f1
2. Then run "chmod +x github_desktop_ubuntu.sh" to make the script executable. 
3. Finally run the script by using "./github_desktop_ubuntu.sh"* (Press y every time you are given a prompt.)
4. Voilà, you now have Github Desktop on Linux.

_*Uncomment the last line if you get an error saying "sudo: gdebi not found" or something similar. This means you don't have gdebi installed which is not installed by default on elementaryOS._

**Comment by linonetwo** [comment]
Hi, I have a question, where will Github Desktop locate in Linux?

For example, VSCode will located like:

```js
  {
    name: 'Visual Studio Code',
    paths: ['/usr/share/code/bin/code', '/snap/bin/code', '/usr/bin/code'],
  }
```

Where will `Github Desktop` be in this format ↑?

Will it be this?

```jso
{
    name: 'GitHub Desktop',
    paths: ['/snap/bin/desktop', '/usr/bin/desktop'],
  }
```

**Comment by CompeyDev** [comment]
I'm not exactly sure, maybe someone else could help you out?
