### ISSUE TITLE
GH Desktop won't save options

### ISSUE THREAD

**Issue by YouveGotMeowxy** [desktop/desktop#11277]
### Describe the bug

Won't save options. I've tried several times, including running as Admin.

### Version & OS

Windows 10

![image](https://user-images.githubusercontent.com/39491297/102939607-2a35dc00-4474-11eb-807a-40774ca24a62.png)

### Steps to reproduce the behavior

1. Go to Options
2. Click on Dark Theme, set enternal editor to VS Code instead of Atom, and uncheck the "Help GH by sending, etc.)"
3. Click Save, exit GH Desktop
4. Start GH Desktop again, get hit (AGAIN; it happens on literally every single startup, no matter how many times I uncheck it) with the  "help GH by sending (etc.)" nag.
5. Go to Options, see that all the previously changed settings are back to how they were.

### Expected behavior

The opposite of the above.

### Actual behavior

The steps listed above.

**Comment by niik** [comment]
Hi @YouveGotMeowxy, thanks for opening this and sorry to hear you're having problems running Desktop!

It sounds like for one reason or another GitHub Desktop is unable to write its settings to disk. These settings are stored in the `%LocalAppData%\GitHubDesktop` directory. I would try shutting down GitHub Desktop, deleting that entire GitHubDesktop folder and launching the app again. Hopefully it's just a permissions issue which can be sorted by starting from scratch. I would not recommend running GitHub Desktop as administrator.

Please try that out and let us know how it went!

**Comment by YouveGotMeowxy** [comment]
> Hi @YouveGotMeowxy, thanks for opening this and sorry to hear you're having problems running Desktop!
> 
> It sounds like for one reason or another GitHub Desktop is unable to write its settings to disk. These settings are stored in the `%LocalAppData%\GitHubDesktop` directory. I would try shutting down GitHub Desktop, deleting that entire GitHubDesktop folder and launching the app again. Hopefully it's just a permissions issue which can be sorted by starting from scratch. I would not recommend running GitHub Desktop as administrator.
> 
> Please try that out and let us know how it went!

Hi niik

Well, I went to the folder you mentioned, and deleted everything there and restarted, but it behaved the same, and never even re-created files in that folder. looking at the shortcut to the app, it pointed to `C:\ProgramData\<username>\GitHubDesktop\`; looking in there the files looked about the same as the ones in the other folder; deleted all of the stuff in there and not surprisingly all of GH desktop is gone and I have to re-download and reinstall.

**Comment by YouveGotMeowxy** [comment]
To make things more interesting, I just downloaded and installed GHD again from the website, and it installed again to `C:\ProgramData\<username>\GitHubDesktop\`; I ran it, change some options, exited, looked for `%LocalAppData%\GitHubDesktop` and it didn't/doesn't exist.

**Comment by memecofun** [comment]
Https://memecofun.github.io
my whole website is build of folders and githud hates folder inports so i went to ghd put my files in and... look for your selfs help
its the same problom

**Comment by steveward** [comment]
Closing as stale. @YouveGotMeowxy if you're still experiencing this issue please let us know and we can investigate further.
