### ISSUE TITLE
Pull Request list no longer updates

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#11276]
### Describe the bug
With the latest version - clicking the refresh button on the PR branch list no longer refreshes the UI. The only way to refresh the list of PRs is to restart Github Desktop

### Version & OS
Version 2.6.1 on Windows 10

### Steps to reproduce the behavior
1. Start Github Desktop
2. Open Branches dropdown and switch to Pull requests tab
3. Close Pull request in Github
4. Switch back to Github desktop and click refresh button on Pull requests tab to refresh list

### Expected behavior
5. PR list refreshes and closed PR is no longer listed.

### Actual behavior
5. Nothing happens

### Screenshots

<img width="1000" alt="PR Refresh Bug" src="https://user-images.githubusercontent.com/62958961/102938161-bb5b8180-4479-11eb-8028-2693c0224efe.png">

### Logs

[2020-12-22.desktop.production.log](https://github.com/desktop/desktop/files/5732212/2020-12-22.desktop.production.log)

**Comment by trackwell-mike** [comment]
I can confirm this issue exists for v2.6.1 on Mac as well.

**Comment by niik** [comment]
@michael-malling @trackwell-mike Thanks for reporting this, I'm going to roll this into #11265. We've got a fix for this which will go out in the next production release.

> We have confirmed this to be a problem with the latest production version and we've come up with a fix in https://github.com/desktop/desktop/pull/11241. Unfortunately we haven't released the fix to our production channel just yet. For now the best workarounds are to either switch to another repository and then back again as that will force a reload of the PR list or, as you've already found, to restart the app.
> 
> You could also try out our [beta channel](https://github.com/desktop/desktop#beta-channel) while you wait for our next official release.
