### ISSUE TITLE
Option to open the project in GitHub

### ISSUE THREAD

**Issue by ChrisNoelBritto** [desktop/desktop#11283]
### Describe the feature or problem you’d like to solve

For the projects I have synced to my desktop and keep getting new versions, I see two options (Open in Visual Studio Code and Show in Explorer)

Example: https://github.com/pnp/sp-dev-solutions

### Proposed solution
Good if there is a button when I click would open the project in the browser (https://github.com/pnp/sp-dev-solutions)

How will it benefit Desktop and its users?
To read the stuff from README.md  on the home page in the brower better (in my VS Code, it hurts my eyes in dark mode)

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
Thanks for contributing @ChrisNoelBritto. You can go to the file menu and select `Repository` > `View on GitHub` to open the repository in your default browser. You can also use the keyboard shortcut `Ctrl+Shift+G`. You can find the full list of shortcuts [here](https://docs.github.com/en/free-pro-team@latest/desktop/installing-and-configuring-github-desktop/keyboard-shortcuts).
