### ISSUE TITLE
GitHub Desktop ignores PAT

### ISSUE THREAD

**Issue by mciuca** [desktop/desktop#11281]
### Describe the bug

GitHub recently notified me:

> You recently used a password to access the repository at XXX with git using git/2.29.2.windows.2.
> Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information around suggested workarounds and removal dates.

After reading the notice I decided to use a PAT.
As I was using SourceTree, I decided to leave it and to switch to GitHub Desktop, and to use a PAT. First, I installed GitHub Desktop, and even with GitHub Desktop I used basic authentication using a password to Git; my commits are ok. Secondly, I created a PAT, and tried to change authentication method in GitHub Desktop. To do so, I signed out from GitHub Desktop, closed it, and then asked to sign in again. But GitHub Desktop never asks me to supply the PAT, instead, GitHub Desktop offers me only one possibility: "Continue with browser", and then my password is requested. So, my PAT is never used.

What I want is to protect my repo and to be sure GitHub will accept my commits.
Do I need a PAT when I'm using GitHub Desktop?
I'm totally confused about that.

What I need is to protect my repo and to be sure GitHub will accept my commits.
### Version & OS

OS: Windows 7 Pro
GitHub Desktop 2.6.1

### Steps to reproduce the behavior

1. Open GitHub Desktop, and "ctrl"+comma
2. Click on 'Sign in' for GitHub.com
3. the only choice now is: "Continue with browser"
4. now, you're automatically logged in, if your browser stored your password

### Expected behavior

I would expect that my PAT is required somewhere when I'm sign in for the first time (meaning, after a sign out)

### Actual behavior

My PAT is never required, and only my GitHub password is used when authenticating. 
Even if a switched from SourceTree to GitHub Desktop, I have the same authenticating method. 

### Screenshots
Prepare to sign in:
![image](https://user-images.githubusercontent.com/46031462/103037056-6861f700-456b-11eb-86de-37fc65cfb28e.png)

The only choice is "continue with the browser"
![image](https://user-images.githubusercontent.com/46031462/103037377-ffc74a00-456b-11eb-8c3b-65a259d70a7c.png)

And after that, I'm automatically logged in, as my browser stored the password :)

**Comment by steveward** [comment]
@mciuca thanks for contributing. GitHub Desktop automatically generated an OAuth token for you using the browser authentication, so there is no need to generate a PAT. You can view your OAuth applications [here](https://github.com/settings/applications). The generated OAuth token is not stored in your browser, it is stored in secure credential storage on your operating system (in this case Windows Credential Storage). Let me know if you have any further questions about this!

**Comment by mciuca** [comment]
@steveward thanks for responding! As said I switched from SourceTree to GitHub Desktop because of the announced depreciation of the basic authentication using a password to Git. It means now that I'm using GitHub Desktop my commits will be safe. I'm no more concerned with password authentication depreciation. Thanks! And also: Good climbing all, That keep the Mountain Law :) ! (personal quotation of the Jungle Books)

**Comment by moznualom2** [comment]
*Follow me  *https://tinyurl.com/y5cnk96p
