### ISSUE TITLE
MacOS Big Sur: x-github-client are not supported

### ISSUE THREAD

**Issue by notiv-nt** [desktop/desktop#11282]
### Describe the bug

Using CLI tool throws an error:

> There was a problem connecting to the server.
> URLs with the type “x-github-client:” are not supported.

But this button (in website) works fine
![image](https://user-images.githubusercontent.com/10743009/103097494-7c176700-4618-11eb-93d5-532ff9fb822f.png)

### Version & OS

Github Desktop: 2.6.1
MacOS: Bug Sur 11.1

### Steps to reproduce the behavior

1. Install CLI tool
2. Terminal: `github .`

### Screenshots

![image](https://user-images.githubusercontent.com/10743009/103097629-f6e08200-4618-11eb-95e2-30f39c0880c3.png)

### Logs

Empty

### Quick Solution:

1. `rm /usr/local/bin/github`
2. Open `.zshrc`, or similar
3. Add alias `alias github="open -a Github\ Desktop.app"`

And use it: `cd  ~/Downloads/ && github .`

**Comment by steveward** [comment]
Thanks for the report @notiv-nt. I don't have a Big Sur machine in front of me at the moment, but I believe @niik and @sergiou87 both do so hopefully one of them can check to see if this is a reproducible issue.

**Comment by steveward** [comment]
Closing this out as I don't believe it is an issue any longer.

**Comment by notiv-nt** [comment]
I can't check, I've decided to stay on Catalina, but the solution above could be like a variant
