### ISSUE TITLE
Change work dictionary OVERWRITE all link files

### ISSUE THREAD

**Issue by robertlzj** [desktop/desktop#11294]
### Describe the bug

Change work dictionary (like switch to a new branch), saying "you have changes on this branch", select "leave my changes on (original branch)" (stash them), will overwrite these files which were hardlink/symbol links, now after stash, the link breaks, they became normal files, and it's content become text of target path. I think even target copy is better.

### Version & OS

Version 2.6.1. Win 10 64 bit Version 2.6.1.

### Steps to reproduce the behavior

Add a symbol link file to working dictionary.
Change branch.
Select leave changes.
Switch back
The link file break.

### Expected behavior

All unversioned file keep original, as if they are ignored.
Only handle versioned file in white list.

### Actual behavior

All unversioned file has been replaced.

### Screenshots

x

### Logs

x

### Additional context

x

**Comment by robertlzj** [comment]
Maybe suffered on old version, found problem suddenly. Now updated.

**Comment by steveward** [comment]
@robertlzj thanks for the report. Can you share the output of `git config --list --show-origin`? i'd like to see if you have configured the `core.symlinks` option. The default is true and should work for Windows. See the `man` page:

```
core.symlinks
If false, symbolic links are checked out as small plain files that contain the link text. git-update-index[1] and git-add[1] will not change the recorded type to regular file. Useful on filesystems like FAT that do not support symbolic links.

The default is true, except git-clone[1] or git-init[1] will probe and set core.symlinks false if appropriate when the repository is created.
```
