### ISSUE TITLE
GitHub Desktop show the wrong default branch

### ISSUE THREAD

**Issue by robert-heath-spike** [desktop/desktop#11299]
### Describe the bug

The default branch for my repo is `master`. However, GH Desktop shows the default as a different branch, one that is in fact deleted.

### Version & OS

GitHub Desktop 2.6.1
MacOS Big Sur, Version 11.1

### Steps to reproduce the behavior

1. Go to the remote repo and verify that `master` is set as the default.
2. Open GitHub Desktop and switch to the local copy of the repo.
3. Click Current Branch to list the branches.
4. See that `master` is not listed as the default.

### Expected behavior

GitHub Desktop should be in synch with the settings of my remote repo.

**Comment by steveward** [comment]
@robert-heath-spike thanks for the report. Normally [refreshing the repository](https://github.com/desktop/desktop/issues/5709#issuecomment-524435092) should update the default branch. You should be able to select the repository again in the repository list to refresh it. Let me know if that doesn't get things working!

**Comment by robert-heath-spike** [comment]
Thanks, Steve. However, doing that did not resolve the problem.

**Comment by steveward** [comment]
@robert-heath-spike can you share the output of `git symbolic-ref refs/remotes/origin/HEAD` from the command line? That should show the default local branch.

**Comment by robert-heath-spike** [comment]
Sure. The output is below the screenshot from GitHub Desktop.

[image: reply-to-gh.png]

**Comment by steveward** [comment]
@robert-heath-spike it looks like the image didn't make it through (images don't work through email replies to issues).

**Comment by robert-heath-spike** [comment]
I included two images. One showed the output of the command:

refs/remotes/origin/master

The other showed GitHub Desktop still displaying the default branch of the
same repo as something else.

**Comment by robert-heath-spike** [comment]
Any news about what might be causing this problem?

**Comment by Hexcede** [comment]
> @robert-heath-spike can you share the output of `git symbolic-ref refs/remotes/origin/HEAD` from the command line? That should show the default local branch.

For me this is showing the correct output (`refs/remotes/origin/dev`), but GitHub desktop is not using the correct default branch (I've tried doing what you've said, as well as switching between two repositories, restarting GitHub desktop, etc) but GitHub desktop still uses the incorrect default branch.

GitHub desktop is selecting `main` as my default branch (which is what my global config is set to use, and a `main` branch does actually exist on my repository) but on the GitHub remote (and locally) it should be `dev` instead, which appears to be the case, but GitHub desktop doesn't appear to be respecting the repository config.

I've also (locally) set `init.defaultbranch` to `dev` on this repository, which didn't make a difference.

Screenshot:
![image](https://user-images.githubusercontent.com/8394472/146836331-85814d87-e06e-4f53-84f0-7d5a718fceb9.png)

I would like GitHub desktop to correctly respect if I change a default branch locally.

**Comment by steveward** [comment]
For reference this was reported again in https://github.com/desktop/desktop/issues/13669 and I've labeled that issue as a bug since I was able to reproduce the problem. We'll look into this and update that issue with details.

**Comment by andresnievessouthworks** [comment]
No update on this?

**Comment by calebds** [comment]
Seeing this behavior on:

Version 3.0.3 (arm64)
macOS 12.2

**Comment by Andyroid0** [comment]
Still problematic on Version 3.0.5 (arm64)

**Comment by steveward** [comment]
@Andyroid0 you can download the latest beta to test out the fix for this issue:

https://desktop.github.com/beta

**Comment by Andyroid0** [comment]
> @Andyroid0 you can download the latest beta to test out the fix for this issue:
> 
> 
> 
> https://desktop.github.com/beta

Fellow Daytonian for the win.

**Comment by attheshow** [comment]
> @Andyroid0 you can download the latest beta to test out the fix for this issue:
> 
> https://desktop.github.com/beta

I'm experiencing this issue as well. I've tried downloading the latest beta but it still shows the incorrect default branch. I'm honestly not sure how it ever got changed from "master" to the branch that it is currently. Is there a git command that I'm not aware of to change the default branch?

**Comment by SamDaHanson** [comment]
This is still not working for me either, I can't use this while it's in this state

**Comment by steveward** [comment]
@SamDaHanson @attheshow does `git symbolic-ref refs/remotes/origin/HEAD` return the correct default branch in the repository you are having issues with?

**Comment by attheshow** [comment]
I ended up deleting the feature branch that was incorrectly marked as the default branch. That seems to have fixed the issue for me and correctly set it back to the expected master branch.
