### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by MoE069** [desktop/desktop#11291]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by MoE069** [comment]
- [ ] - - [ ] - - - [ ] @desktopbot [](https://twitter.com/moe64565868/status/1342252067172343808?s=21) ä![image](https://user-images.githubusercontent.com/76610353/103166555-86f21780-4823-11eb-9533-05777a37bcf4.jpeg)_silk-road**_@_**_

**Comment by steveward** [comment]
Thanks for reaching out @MoE069!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further.
