### ISSUE TITLE
GitHub Desktop Shows "The File Is Empty" after running "Expo Init Mobile" on a folder that contains the files!

### ISSUE THREAD

**Issue by alissonpratesperes** [desktop/desktop#11297]
Hello Everyone, I'm studying development and started to use Expo for abstraction of my app to my phone. When I run the command "expo init mobile" where "mobile" is my folder with the code to my app, the Github Desktop doesn't to see the files are added and don't process any changes of this files. When I try to commit to Github desktop, the "mobile" folder stays empty. What's going on guys, i've bem stuck with this s*it since tuesday and can't find anyone with this problem on the net.

I'm using MacOS Big Sur 11.1 on a Macbook Air 2017 Running Github Desktop on 2.6.1 Version

![step07](https://user-images.githubusercontent.com/52282116/103249869-fa914300-494f-11eb-8b08-99fcb7a0d288.png)

Help me with this please! I do not know much about react-native and I'm very very very newbie about this. Only know few about Expo and this doesn't work. I would like to versioning my app with github, for this is because I'm so frustrated right now cause the app with expo runs ok on my machine, only doesn't work with github desktop!

**Comment by daisukedd** [comment]
Conseguiu resolver? estou tendo o mesmo problema.
