### ISSUE TITLE
Full screen Bug/Glitch

### ISSUE THREAD

**Issue by wendellmeset** [desktop/desktop#11292]
### Describe the bug

Whenever you set GitHub Desktop to full screen mode (not f11, just plain full screen), then you close and reopen it, a white line appears at the top, and to get rid of it, you need to go out of full screen mode and go back in.

### Steps to reproduce the behavior

1. Make GitHub Desktop full screen (not full screen mode, not f11, just plain full screen)
2. Close GitHub Desktop
3. Open it

### Expected behavior

I expected it to stay in full screen mode without that white line when I reopen it (GitHub Desktop)

### Actual behavior

It stayed in full screen mode, but a white line appeared at the top

**Comment by steveward** [comment]
Thanks for the report @wendellmeset. I was unable to reproduce this in a virtual machine running Windows 10. Can you share a screenshot of what you are seeing?

**Comment by xuyxu** [comment]
Hi @steveward, this problem does exist. Here is the screenshot :

![screenshot](https://user-images.githubusercontent.com/22359569/104121374-a8e9af00-5378-11eb-9ee2-a0cb97079a0d.png)

**EDIT**: This white line will disappear if we first change github deskptop to the window mode, and then back to the full screen mode. It does not cause any problem, but would be better if it can be fixed :-)
