### ISSUE TITLE
GitHub Desktop Update Description Explanation Overalpping Issue

### ISSUE THREAD

**Issue by Dragola** [desktop/desktop#11307]
### Describe the bug

The latest commit I pushed in the history tab seems to have a graphical issue with the description box. It seems to be overlapping or re-showing it continuously which makes it impossible to read. This issue seems to only be for this project and that specific push only. While this issue doesn't break GitHub Desktop it's still an inconvenience if I wanted to read the updates description

### Version & OS

GitHub Desktop- Version 2.6.1; Windows 10 20H2

### Steps to reproduce the behavior

1. Go to project.
2. Click on history tab.
3. Click on latest push/update.
4. click on expand for the push/update description.
5. Hover the mouse over the files. Click one and hover the mouse over the other files, repeat for each until issue is seen.
6. See the error.

### Expected behavior

The updates description to be clear and not bugging out.

### Actual behavior

The updates description bugging out/overlapping.

### Screenshots

Can't get a screenshot of the issue.

### Logs

[2020-12-30.desktop.production.log](https://github.com/desktop/desktop/files/5754982/2020-12-30.desktop.production.log)

### Additional context

https://user-images.githubusercontent.com/45637546/103368886-bc526b80-4a96-11eb-8df8-ae4c18a767f9.mp4

**Comment by steveward** [comment]
Thanks for the report @Dragola. I believe what you are running into is https://github.com/desktop/desktop/issues/1380, so I'm going to close this out in favor of that tracking issue. Please follow along there for updates.
