### ISSUE TITLE
Add SubEthaEdit as External Editor for MacOS

### ISSUE THREAD

**Issue by brokosz** [desktop/desktop#11308]
### Describe the feature

I'm looking to get [SubEthaEdit](https://subethaedit.net) added as a supported external editor. I don't know what other files need to change, but some edits are below. 

### Proposed solution

Additions for `darwin.ts`:

```
export enum ExternalEditor {
[…]
SubEthaEdit = 'SubeEthaEdit',
```

```
function getBundleIdentifiers(editor: ExternalEditor): ReadonlyArray<string> {
  switch (editor) {
    case ExternalEditor.SubEthaEdit:
      return ['de.codingmonkeys.SubEthaEdit.Mac']
```

```
 case ExternalEditor.SubEthaEdit:
      return Path.join(installPath, 'Contents', 'MacOS', 'SubEthaEdit')
```

```
const [
[…]
    SubEthaEditPath,
] = await Promise.all([
    findApplication(ExternalEditor.SubEthaEdit),
```

```
if (SubEthaEditPath) {
    results.push({ editor: ExternalEditor.SubEthaEdit, path: SubEthaEditPath })
  }
```

**Comment by steveward** [comment]
GitHub Desktop now provides support for [adding custom editors](https://docs.github.com/en/desktop/configuring-and-customizing-github-desktop/configuring-a-default-editor-in-github-desktop?platform=windows#configuring-a-custom-editor), so you can add SubEthaEdit by following the steps in that linked help article. I'm going to close this out.
