### ISSUE TITLE
Unknown error when pushing or pulling

### ISSUE THREAD

**Issue by Myrte46** [desktop/desktop#11306]
### Describe the bug

There is an unknown error every time I try to push or pull from GitHub Desktop.

### Version & OS

Github version 2.6.1
Windows 10 Home 64-bit

### Steps to reproduce the behavior

Try to push or pull in any way (shortcut or with the button)

### Expected behavior

I expected to see my commits being pushed to and pulled from the remote branch, as it had done that morning.

### Actual behavior

An error message showed up saying 'unknown error'

### Screenshots

![image](https://user-images.githubusercontent.com/44023715/103356711-cafa4c00-4ab1-11eb-831b-ef1eb65209c8.png)

### Logs

[2020-12-30.desktop.production.log](https://github.com/desktop/desktop/files/5754478/2020-12-30.desktop.production.log)

### Additional context

As I stated, it worked fine this morning, then suddenly it didn't for the rest of the day, and due to the lack of information, I can't troubleshoot it myself. I have also tried to push with Visual Studio 2019, which resulted in the same error. I'm not sure if this is something with GitHub specifically or if it's more general than that, like a link between my remote and local files.

**Comment by steveward** [comment]
Thanks for the report @Myrte46. Unfortunately the log file isn't showing much information. Have you tried pushing via the command line to see if any errors are shown there?

**Comment by Myrte46** [comment]
@steveward I tried pushing it using the command line and this seemed to bring up locking support on origin which I have no knowledge of, but removing that locking state allowed me to push and pull again, so I have a way of pushing and pulling now. Thank you!
