### ISSUE TITLE
Github Desktop doesn't open after clean Big Sur Installation

### ISSUE THREAD

**Issue by Exitare** [desktop/desktop#11300]
### Describe the bug

After reinstalling a fresh copy of Mac OS Big Sur Github Desktop will not open. The symbol shows up in the Dock, but the application itself is not shown. 

### Version & OS

Mac OS 11.1 
Intel Based
Github Desktop most recent version. About is not possible because it is only showing a blank screen. Screenshot attached.

### Steps to reproduce the behavior

1. Download the application
2. Drag it to the Application folder
3. Start it

### Expected behavior

Github Desktop should open normally

<img width="1978" alt="Screen Shot 2020-12-29 at 09 37 36" src="https://user-images.githubusercontent.com/13048528/103303092-f994fb80-49b9-11eb-811b-37fd3c79c961.png">

If no-one else encounters this issue, its most likely an issue on my side and this issue can be closed. I just want to make sure i am not the only one encountering that problem.

Best

**Comment by affrae** [comment]
Hi @Exitare I've been running Big Sur for about a week now and I have not as yet had a problem with GitHub Desktop. I made sure I had a time machine back up, wiped my Mac and reinstalled OS and then restored my apps and home directory from that back up. Not sure if this helps.

I'm not official support I just happen to work for GitHub and saw this issue.

**Comment by Exitare** [comment]
Hey @affrae,
thanks for your reply.
I did the same thing. 
Wiping the ssd in the os recovery, installed a fresh copy and then reapplied the time machine backup.

While every other application is working just fine, only GitHub desktop is showing me this white screen basically rendering it unusable. 

I tried to "uninstall" GitHub desktop yesterday, deleting the settings and the application itself, but to no use. Its still not working and i had to switch over to an alternative.

**Comment by affrae** [comment]
Hey @Exitare, have you tried cleaning out `~/Library/Application Support/GitHub Desktop`?

I'd copy the folder somewhere else then delete it from `~/Library/Application Support/` then relaunch the app.

You may have to set some stuff again, but let's see if you can at least get it launched.

If that works, try putting the folder back and relaunching. If it again breaks we know where our problem is.

I would then empty the contents of `Cache`, `GPUCache` and `Session Storage` folders to begin with - I just tested and they are rebuilt on launch if they do not exist.

**Comment by Exitare** [comment]
@affrae 
i didn't delete that file, but that is exactly what caused the issues.
Thank so much for your help!
You saved my day!

**Comment by affrae** [comment]
Anytime! Have a great new year, @Exitare

**Comment by Exitare** [comment]
Same to you @affrae !
