### ISSUE TITLE
I have a problem in making a clone at desktop github

### ISSUE THREAD

**Issue by masood-123** [desktop/desktop#11309]
Please help me i have spent two days to sovle this problem but i can't.
i have an error in making a clone at desktop github and i also did not find the directories 
with the name #appdata #localappdata i reinstall the app of desktop github multiple time but it isn't work please help me it would be your 

kind on me............
![Capture](https://user-images.githubusercontent.com/76804395/103400486-0acf3b00-4b67-11eb-98b4-223aebb63cb2.PNG)

**Comment by billygriffin** [comment]
This looks like it's the same as https://github.com/desktop/desktop/issues/10345. Would you mind trying the steps on that thread and sharing what works or doesn't work there? We haven't been able to figure this one out but it's popped up quite a bit so any additional context you can share about your environment or potential other software that might be interfering would be helpful. Thanks!
