### ISSUE TITLE
I can't push to my repository (sometimes)

### ISSUE THREAD

**Issue by CharlieS1103** [desktop/desktop#11301]
When I try to push a commit to my repository it doesn't work

It just says "fatal: unable to access ': Couldn't connect to server"

I use MacOS Catalina 10.15.7 and github desktop 2.6.1

### Steps to reproduce the behavior

1. Make changes to a repository
2. Commit changes
3. Try to push changes

### Expected behavior

I expected it to push to the repository.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

[2020-12-29.desktop.production.log](https://github.com/desktop/desktop/files/5751747/2020-12-29.desktop.production.log)

### Additional context

It works sometimes, however, it will randomly stop working until i restart my computer

**Comment by steveward** [comment]
Thanks for the report @SaltNuggets. This sounds like a network issue -- have you tried performing a `git push` via the command line when you encounter this error in GitHub Desktop? That would help narrow down if this a specific issue with GitHub Desktop or with your network.

**Comment by CharlieS1103** [comment]
I have, it seems to be an issue with my network, it also doesn't work using the intellij github plugin.

**Comment by steveward** [comment]
@SaltNuggets common causes of network issues can be antivirus software, firewalls, or proxies. If you have anything like that running on your system or network I'd recommend looking there first. I'm going to close this out since we've isolated it as not specific to GitHub Desktop, but let me know if you have any further questions.

**Comment by CharlieS1103** [comment]
I have anti virus software but I gave github desktop-specific bypass to the firewall, and I disabled my computers firewall.
