### ISSUE TITLE
out dated divers in windows 10 pro 64 

### ISSUE THREAD

**Issue by klitgen** [desktop/desktop#11315]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by billygriffin** [comment]
Hi @klitgen, this doesn't look like a problem with GitHub Desktop so I'm going to close this issue.
