### ISSUE TITLE
Unable to set 'Fork behaviour' to 'For my own purposes'

### ISSUE THREAD

**Issue by OllyMcBrideOB** [desktop/desktop#11327]
### Describe the bug

I have forked a public repository and cloned to GitHub Desktop, when prompted with the 'Fork behaviour' dialog, I selected 'For my own purposes'.

However, if I then go to 'Repository -> Fork behaviour' the 'To contribute to the parent repository' option is selected. If I then select the 'For my own purposes' option, click 'Save', and then re-open the dialog, the incorrect 'To contribute to the parent repository' option is selected again.

### Version & OS

Microsoft Windows 10 Home 10.0.19041
GitHub Desktop Version 2.6.1

### Steps to reproduce the behavior

1. Go to 'Repository -> Fork behaviour'
2. Click on 'For my own purposes'
3. Click 'Save'
4. Go to 'Repository -> Fork behaviour'
5. See that the incorrect option is selected

### Expected behaviour

I would expect the 'For my own purposes' option to be selected, or an error message if there was a failure with the selection.

### Actual behaviour

The 'To contribute to the parent repository' option is selected.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

Forking the https://github.com/ARMmbed/mbed-os repository.

**Comment by billygriffin** [comment]
Hi @OllyMcBrideOB, thanks for the issue! I was able to reproduce this, and we're looking into it now. This should definitely not be happening so I appreciate you letting us know!

**Comment by sergiou87** [comment]
Hi @OllyMcBrideOB !!

I think I found and fixed the issue, you can get more details in #11332 

As a workaround until it's fixed, your settings will take effect if you close and reopen the app right after changing them. For example:
1. Clone the fork in the app
2. Tell the app you want to use it "For my own purposes"
3. Close the app
4. Open it again

Or:
1. With the repository selected…
2. Go to Repository -> Repository Settings
3. Click on Fork Behavior
4. Choose "For my own purposes"
5. Click on "Save"
6. Close the app
7. Open it again

I hope that works for now!
