### ISSUE TITLE
Github Desktop and Windows AppLocker

### ISSUE THREAD

**Issue by blazoncek** [desktop/desktop#11329]
### Describe the bug

If Windows computer has Microsoft Windows AppLocker enabled by Group Policy (to prevent running applications outside of allowed folders (e.g. C:\Program Files)) Github Desktop fails to run.

### Version & OS

Windows 10

### Steps to reproduce the behavior

1. Create Group Policy AppLocker entry to prevent running applications outside of C:\Program Files
2. Enable Windows AppLocker by Group Policy for the computer
3. Start Github Desktop

### Expected behavior

Github Desktop and all dependent software be installed in C:\Program files (or any other AppLocker excluded folder).

### Actual behavior

Github Desktop installer does not allow selection of installation destination folder.

### Screenshots

![image](https://user-images.githubusercontent.com/7722392/103612543-f56e5e00-4f24-11eb-8c00-e3d402bd6a5a.png)

![image](https://user-images.githubusercontent.com/7722392/103612480-d1128180-4f24-11eb-92e4-a29d77f7da6c.png)

### Logs

None.

### Additional context

None.

**Comment by steveward** [comment]
Thanks for the report @blazoncek. Unfortunately the installation directory is limited by the Squirrel installer we use with GitHub Desktop. The best solution I can give you (other than allowing applications installed to `%AppData%`) would be to try the portable version of GitHub Desktop a user created:

https://github.com/daemondevin/GitHubDesktopPortable

I hope that helps!

**Comment by kimoppalfens** [comment]
Github Desktop is signed with a certificate with this thumbprint: fb713a60a7fa79dfc03cb301ca05d4e8c1bdd431.
Is there a repository available what else is signed with this certificate? If this cert is only used to sign Github Desktop a rule could be made to trust this certificate instead of trusting everything in %AppData%. %AppData% is user writable , allowing that in an applocker policy would be a rather big opening no-one should be prepared to make.

**Comment by blazoncek** [comment]
Agree on that.
Strict (company) policies should not allow  application installations outside of "Program Files" which requires elevated privileges to write into.

And BTW @steveward portable version has same implications. Does not solve the problem.
