### ISSUE TITLE
Shortcut Issue To Open Command Line

### ISSUE THREAD

**Issue by Quark03** [desktop/desktop#11328]
### Describe the feature or problem you’d like to solve
The shortcut for opening the repository with the default command line tool on windows is  CTRL + ` (back slash) but in a Spanish Layout keyboard it is not working because you need to press the key 2 times to actually use the symbol. That means that the shortcut is hard if not impossible to use

### Proposed solution
Either changing the shortcut for a more convenient key

**Comment by steveward** [comment]
Thanks for the feedback @Quark03. I'm going to add this to https://github.com/desktop/desktop/issues/3240 where we are tracking the same issue for German keyboards.
