### ISSUE TITLE
Renamed repositories remain listed under old name

### ISSUE THREAD

**Issue by wojtekmaj** [desktop/desktop#11326]
### Describe the bug

Renamed repositories remain listed under old name.

### Version & OS

GitHub Desktop 2.6.1

macOS Catalina 11.1

### Steps to reproduce the behavior

1. Add repository named "foo" to GitHub Desktop
2. Rename repository on GitHub to "bar"
3. Create new "foo" repository
4. Add it to GitHub Desktop too
5. Now you have 2 "foo" repositories.

### Expected behavior

Repository gets renamed on repo list in GitHub Desktop, or at the very least the name is updated when repo is removed and re-added to GitHub Desktop.

"View on GitHub" opens a repository correctly.

### Actual behavior

Repository remains listed under old name on repo list. Removing and adding repository back doesn't help.

"View on GitHub" opens a repository that's under old name.

"View on GitHub" option in commit context menu opens a repository that's under old name, resulting in 404 since SHA is unique.

### Screenshots

GitHub: 

<img width="309" alt="obraz" src="https://user-images.githubusercontent.com/5426427/103528175-c9e76700-4e83-11eb-8c62-5752c5e43dc2.png">

GitHub Desktop:
![obraz](https://user-images.githubusercontent.com/5426427/103527756-25652500-4e83-11eb-87c3-756061693dae.png)

### Additional context

Despite the issues mentioned above, push/pull works perfectly fine - points to a correct remote origin.

**Comment by billygriffin** [comment]
@wojtczal Thanks for the issue! If you switch away from the renamed repo and back to it, does it update? I thought it should also update when you push or pull from it, so I'm curious if that's the case also.

**Comment by wojtekmaj** [comment]
No, it does not. I actually have this problems for a few weeks now, so this included switching between repos, fetching, pushing and pulling hundreds of times, couple of restarts, full machine shutdowns etc.

**Comment by steveward** [comment]
@wojtekmaj I wasn't able to reproduce this issue. Renames were updated correctly in GitHub Desktop after switching repos in the repository list. Did the `origin` remote URL update correctly in `Repository` > `Repository Settings` when you renamed the repository?

**Comment by wojtekmaj** [comment]
Yes, it has updated correctly and everything works fine, except for the things I listed in the original post. I have no idea how that happened.

Here's a screenshot showing Repository Settings (with new name) and Current Repository (with the old name that failed to update).

![bez nazwy](https://user-images.githubusercontent.com/5426427/103581892-24f97800-4edd-11eb-8e8b-384d2b097b8d.png)

**Comment by wojtekmaj** [comment]
Fixed by #12308 (although you do need to clone the renamed repo again)
See also #3855
