### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Anuj-malviya0** [desktop/desktop#11320]
when I newly installed git desktop it was working find but when ,I i made some changes and created some repositories the are not appearing on git desktop app ,I cross checked my repositories are showing up on git hub web page but they are not showing up on the git hub desktop app

**Comment by Seb33300** [comment]
Did you add your repository in GitHub desktop app?

This is not automatic. You have to add all repositories manually in your GitHub desktop by using the `Open with GitHub Desktop` link for instance.

![image](https://user-images.githubusercontent.com/915273/103497763-0d86a480-4e75-11eb-9e6d-d3aed15997e8.png)

**Comment by billygriffin** [comment]
Thanks for the response @Seb33300! I think that's the issue, so I'm going to close this out.

**Comment by Anuj-malviya0** [comment]
Thank you so much for helping me
