### ISSUE TITLE
Error in Cloning Repository

### ISSUE THREAD

**Issue by stanleyowen** [desktop/desktop#11338]
### Describe the bug
* When I am going to clone [https://github.com/stanleyowen/stanleyowen](https://github.com/stanleyowen/stanleyowen) repository, it actually doesn't clone this repository, but it is cloning [https://github.com/stanleyowen/stanleyowen.github.io](https://github.com/stanleyowen/stanleyowen.github.io).

__Note: [https://github.com/stanleyowen/stanleyowen](https://github.com/stanleyowen/stanleyowen) and [https://github.com/stanleyowen/stanleyowen.github.io](https://github.com/stanleyowen/stanleyowen.github.io) are different repository with different content.__

### Version & OS

GitHub Desktop Version 2.6.1
Windows 10 Home Single Language Version 20H2

### Expected behavior

* It is going to clone [https://github.com/stanleyowen/stanleyowen](https://github.com/stanleyowen/stanleyowen)

### Actual behavior

A clear and concise description of what actually happened.
* It is cloning [https://github.com/stanleyowen/stanleyowen.github.io](https://github.com/stanleyowen/stanleyowen.github.io)

### Screenshots

https://user-images.githubusercontent.com/69080584/103724606-4eaebe00-5007-11eb-8429-7e28e46961ea.mp4

I am going to clone stanleyowen, but it shows `Cloning stanleyowen.github.io`

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

* Beside trying to clone a repository through GitHub.com (From GitHub Desktop), I have also tried to Clone through GitHub Desktop URL, it also not working. However when I am trying to clone it through Git Bash, it worked normally.

**Comment by steveward** [comment]
Thanks for the report @stanleyowen. Did you recently rename the repository on GitHub? This sounds like it may be another case of https://github.com/desktop/desktop/issues/3855.

You should be able to resolve this by resetting GitHub Desktop:

1. Close GitHub Desktop 
2. Open File Explorer and delete the `%APPDATA%\GitHub Desktop\Cache` directory
3. Restart GitHub Desktop and try cloning again

Let me know if that does not get things working for you.

**Comment by stanleyowen** [comment]
Great, it works! Thanks for the information 👍
