### ISSUE TITLE
Error while uploading icon-logo-yellow.ico

### ISSUE THREAD

**Issue by roma2** [desktop/desktop#11331]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by billygriffin** [comment]
Hi @roma2, thanks for the issue. We ask for the full template to be filled out as we're a small team and need that additional information to be able to understand what might be causing the problem (and what the problem is). Thanks!

**Comment by Sarah56546567** [comment]
Follow me  https://tinyurl.com/y5cnk96p

**Comment by moznualom2** [comment]
*Follow me  *https://tinyurl.com/y5cnk96p
