### ISSUE TITLE
Private class fields in typescript files don't have syntax highlighting

### ISSUE THREAD

**Issue by xt0rted** [desktop/desktop#11336]
### Describe the bug

When using [private class fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields) in typescript files (haven't tested javascript) syntax highlighting is lost and the entire line is rendered in red.

### Version & OS

2.6.2-beta2 on windows

### Steps to reproduce the behavior

1. Create a typescript file with a normal field
2. Change it to a private field
4. View the diff

### Expected behavior

For the lines to be rendered just like using normal fields.

### Actual behavior

The entire line is rendered in red.

### Screenshots

![image](https://user-images.githubusercontent.com/831974/103717043-7e6fae80-4f92-11eb-97d9-8cdf07d5e56e.png)

![image](https://user-images.githubusercontent.com/831974/103717176-d1e1fc80-4f92-11eb-9fe2-90067b87cc21.png)

### Additional context

This was found while retesting https://github.com/desktop/desktop/issues/8574#issuecomment-755013423

**Comment by steveward** [comment]
Thanks for the issue @xt0rted. This was previously reported in https://github.com/desktop/desktop/issues/10355. If you're interested in working on this see @niik's comment in that issue for what needs to be done to resolve this. I'm going to close this out.
