### ISSUE TITLE
Former account after logging in with a new account is the author of commits.

### ISSUE THREAD

**Issue by nebulaOW** [desktop/desktop#11335]
### Describe the bug

After logging out of an account and logging in with a different account, the commit will be authored by the former account.

### Version & OS

Version 2.6.1 on Windows 10 2004

### Steps to reproduce the behavior

1. Logged in as Account 1.
2. File > Options > Accounts > Sign out
3. File > Options > Accounts > Sign in
4. Log in with Account 2.

### Expected behavior

Commits should be authored by Account 2.

### Actual behavior

Commit was authored by Account 1 on a repo with no other collaborators other than Account 2.
Photo of Account 1 was still appearing in the bottom left corner.

**Comment by steveward** [comment]
Thanks for the issue @nebulaOW. You can check the name and email address that are being used in your .gitconfig by going to `File` > `Options` > `Git`. Make sure the email address being used there matches an email address that is associated with your currently logged in GitHub account (https://github.com/settings/emails). You can read more about how commit attribution works here:

https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user

In the future we are hoping to prevent these scenarios by automatically detecting if an email address does not match an associated email address of the currently logged-in account. You can follow along in https://github.com/desktop/desktop/issues/610 for updates about this.
