### ISSUE TITLE
Pull request sync button often doesn't do anything

### ISSUE THREAD

**Issue by ImRodry** [desktop/desktop#11334]
### Describe the bug
When clicking the "Refresh the list of pull requests" button on the branch dropdown this button often doesn't do anything. In fact, I have barely ever seen it working, causing it to often show closed PRs and now show new ones after the app was opened.

### Version & OS
Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.
Version 2.6.1 on Windows 10 version 20H2 OS build 19042.685

### Steps to reproduce the behavior

1. Open a repository
2. Select the "Current branch" dropdown
3. Choose the "Pull requests tab"
4. Check the available pull requests
5. Open/close a pull request on said repository on github.com
6. Hit "Refresh the list of pull requests" and observe how the list should stay the same (button doesn't give any visual feedback either like a pressing animation)

### Expected behavior
The pull requests should've been synced.

### Actual behavior
A clear and concise description of what actually happened.
The list of pull requests stayed the same and even included old ones

### Screenshots
Add screenshots to help explain your problem, if applicable.
Would be hard to screenshot this but I can get a video if needed

### Logs
Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
Logs do not mention any action related to this.

### Additional context
Feel like I've mentioned everything. If you need more info I'll be happy to help.

**Comment by steveward** [comment]
Thanks for the report @ImRodry. I just tested the PR refresh in a test repository and it correctly updated the list with the new PR. I then closed the PR and the list again successfully updated.

Could you share your logs from GitHub Desktop so that I can check to see if there are any errors being thrown that could be causing this? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by ImRodry** [comment]
So I did check the logs and at the time and I couldn't find any errors related to that specifically but maybe this will help you out. Otherwise I can try some troubleshooting steps but iirc that button has only worked once since I've started using github desktop
[2021-01-05.desktop.production.log](https://github.com/desktop/desktop/files/5783405/2021-01-05.desktop.production.log)

**Comment by niik** [comment]
@ImRodry Thanks for reporting this, I'm going to roll this into #11265. We've got a fix for this which will go out in the next production release.

> We have confirmed this to be a problem with the latest production version and we've come up with a fix in https://github.com/desktop/desktop/pull/11241. Unfortunately we haven't released the fix to our production channel just yet. For now the best workarounds are to either switch to another repository and then back again as that will force a reload of the PR list or, as you've already found, to restart the app.
> 
> You could also try out our [beta channel](https://github.com/desktop/desktop#beta-channel) while you wait for our next official release.

**Comment by Sarah56546567** [comment]
Follow me  https://tinyurl.com/y5cnk96p

**Comment by dhh** [comment]
I have the same issue, but the beta channel version did not fix it:

<img width="1252" alt="Screen Shot 2021-01-24 at 10 58 33 AM" src="https://user-images.githubusercontent.com/2741/105626866-24e0fe00-5e33-11eb-8b08-74e7479a6890.png">

Would be pretty amazing if there were no pending PRs for Rails!

**Comment by billygriffin** [comment]
@dhh 👋 Thanks for the follow up. Would you mind confirming which version you're on in "About GitHub Desktop"? I'm unable to repro this on the latest beta after the PR shipped that @niik referenced above, so just wanted to find out a bit more. Separate from that, is it reliably reproduceable or intermittent? Here's my local copy of `rails/rails`:

<img width="1269" alt="Screen Shot 2021-01-26 at 12 46 44 PM" src="https://user-images.githubusercontent.com/5091167/105896813-8db3ac00-5fd4-11eb-93ad-f3f4802045d4.png">

But maybe yours is correct, in which case congrats on getting the open PRs down to zero! Quite an accomplishment! 😆

**Comment by dhh** [comment]
It says 2.6.2. It's reliably reproducible. As in, it's constant. And it's not just on the rails repo, it's on all repos. There's no connection to the PRs.

**Comment by sergiou87** [comment]
Thanks for double-checking @dhh ! After looking into that, our current theory is that the app might be in a broken state for you, where it has an invalid token for your user. In that case, signing out and in again in Preferences -> Accounts should fix the issue 🤞 

Please, let us know if that doesn't fix the problem, we'll be happy to investigate further!

**Comment by dhh** [comment]
Logging out and in again solved it for me 👍

**Comment by billygriffin** [comment]
Great to hear! Thanks for following up, and sorry for the confusion.
