### ISSUE TITLE
Authentication failed message is shown Whenever I am pushing my code from my local repository

### ISSUE THREAD

**Issue by UltimoHarish10** [desktop/desktop#11330]
Description of my bug

Authentication failed message is shown Whenever I am pushing my code from my local repository.

### Version & OS
 
Version of My GitHub desktop is  Version 2.6.1
My Operating system is Windows 10 version 20H2

### Steps to reproduce the behavior

I have made some changes in my code which is in local repository.
Then I have commited my changes to my branch.
Then I am pushing my changes.
While pushing my changes I get the Authentication failed message.

### Expected behavior

When I login into my github account and see my changes It needs to be shown in my branch

### Actual behavior

I could not see any changes made

### Screenshots

![image](https://user-images.githubusercontent.com/70843950/103626738-a3e4c400-4f62-11eb-826a-e3b5ee0e811f.png)

### Logs
Attaching my log files during pushing my code
[2021-01-05.desktop.production.log](https://github.com/desktop/desktop/files/5769125/2021-01-05.desktop.production.log)

**Comment by UltimoHarish10** [comment]
I searched this type of issue and found the same case attaching URL for your reference
[https://github.com/desktop/desktop/issues/6868](url)

can some one help me on this???

**Comment by steveward** [comment]
@UltimoHarish10 thanks for the report. Unfortunately the log file you sent over isn't showing the specific error. It looks like you do have a valid token, so I'm guessing that is not the issue. Are you able to reproduce the error again and upload a new log file?

**Comment by UltimoHarish10** [comment]
@steveward  As You have mentioned in the previous comment I have tried the same scenario in my machine and I could reproduce the same issue. I have made a video recording of that issue and uploaded here. Hope this might help you. And I have also included the log file during pushing my changes.

[2021-01-05.desktop.production.log](https://github.com/desktop/desktop/files/5772112/2021-01-05.desktop.production.log)

https://user-images.githubusercontent.com/70843950/103688204-7bd38000-4fb7-11eb-8246-a754656159b7.mp4

**Comment by steveward** [comment]
Thanks for the video @UltimoHarish10. One common cause of mysterious authentication failures has been modified registry entries on your machine. See this [help document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789) for steps about how check for this issue on your machine. Let me know if that doesn't seem to be the issue here and we can look into other possible causes.

**Comment by UltimoHarish10** [comment]
@steveward Thanks for the document. As per the document I have cleared the registry entry of the Autorun in the specified path. Now I can able to push my commits.

**Comment by steveward** [comment]
@UltimoHarish10 I'm glad to hear that got things working for you!
