### ISSUE TITLE
github desktop encountered error

### ISSUE THREAD

**Issue by ambroseap** [desktop/desktop#11337]
after dow
![Screenshot (142)](https://user-images.githubusercontent.com/65343392/103725651-5f474000-4fd7-11eb-8a67-45874a633faf.png)
nloading, and cloning a repository, i just closed the app, and when i tried opening it again, it return the following error

**Comment by steveward** [comment]
Thanks for the report @ambroseap. This was tracked and resolved in https://github.com/desktop/desktop/issues/9710. Previous reports were on macOS so this may be a new issue specific to Windows. 

Is this continuing to happen even after restarting your machine?
