### ISSUE TITLE
Not showing anything after push/pull command.

### ISSUE THREAD

**Issue by Techitreesoutions** [desktop/desktop#11339]
After run command, git pull or git push normally GIT  ask for username password. but from today morning it is not showing anything. Only a blank screen like a notepad
<img width="571" alt="Screenshot 2021-01-06 at 7 03 22 PM" src="https://user-images.githubusercontent.com/49784811/103774051-fa7cfb80-5051-11eb-9bf5-b11ea1f1fe55.png">

**Comment by steveward** [comment]
@Techitreesoutions this issue tracker is for GitHub Desktop. For specific questions about using Git on the command line I'd recommend reaching out to [GitHub Support](https://support.github.com/).
