### ISSUE TITLE
Unable to login to GitHub Desktop 2.6.1 with certain browsers

### ISSUE THREAD

**Issue by the-r3dacted** [desktop/desktop#11341]
### Describe the bug

So far I've found Opera GX and Waterfox Classic to be two browsers that don't have any link associations to log into GitHub Desktop.

### Version & OS

GitHub Desktop 2.6.1 on Windows Server 2008 R2

### Steps to reproduce the behavior

1. Download GitHub desktop
2. Try to log in using one of the two browsers
3. See no file associations 

### Expected behavior

Browser sees GitHub Desktop's browser association, and works.

### Actual behavior

GitHub Desktop sits on the loading waiting for login screen, and the browser has no associations for opening GitHub Desktop

### Additional context

If you hadn't taken out logging in from within the GitHub desktop app, this wouldn't be an issue, but you "had" to remove it because of "security", even though you still get logged into the app, so it can't be for "security".

**Comment by steveward** [comment]
Thanks for the feedback @R3n001. At this time GitHub Desktop works with [GitHub's supported browsers](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/supported-browsers). Please note that we also do not officially support Windows Server operating systems. Let me know if you have any further questions.
