### ISSUE TITLE
JetBarins PyCharm is not detected as an external editor

### ISSUE THREAD

**Issue by jd-develop** [desktop/desktop#11340]
### Describe the feature

In `File>Options`, JetBrains PyCharm is not detected as an external editor.

### Proposed solution

It would be good if this software was detected.

**Comment by steveward** [comment]
Thanks for the report @jd-develop. At this time GitHub Desktop only supports editors that have been specifically integrated into the application. You can find the details of how this works along with the supported editors here:

https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md

PyCharm is currently integrated on macOS but not on Windows.
 
There is also a [tracking issue](https://github.com/desktop/desktop/issues/7033) where we are collecting feedback about better support for external editors. We're also tracking broader JetBrains editor support in https://github.com/desktop/desktop/issues/9453, so I am going to close this issue out.
