### ISSUE TITLE
[Feature Request] Ability to pin/star repos in the repo list

### ISSUE THREAD

**Issue by maxijabase** [desktop/desktop#11348]
### Describe the feature or problem you’d like to solve

When the list of repositores at a user's disposal gets relatively large, it can take a moment to remember where the repository you want to go to is.

### Proposed solution

In cases where a user has a large list of repositories at their disposal, it would be useful to have the ability to pin/star repositories  at the top for easy and quick access to them as soon as you open the repo list.

**Comment by steveward** [comment]
Thanks for the feedback @ratawar. This feature request was captured in #6460 (along with a number of other repository list improvements). We decided that for now we’re going to stick with “Recent” as the way to navigate amongst frequently used repos. We may revisit in the future, but have no plans at present to add the ability to pin a repo.

I'm going to close this issue out, but thanks for using GitHub Desktop!
