### ISSUE TITLE
Github desktop not opening or finishing install on windows 10.

### ISSUE THREAD

**Issue by cyric2020** [desktop/desktop#11363]
The issue:
The installer runs but all of a sudden stop, local appdata is generated but not roaming. No shortcut is created and when i try to run the exe from local appdata nothing happens.

System info:
Windows 10 Home - Version 1909
OS Build 18363, 1256
Tested on: 2.6.1 & 2.6.2-beta2

**Comment by steveward** [comment]
Thanks for the report @cyric2020. To get some more information about why the installation is failing it would be helpful if you could send over the log file that the Squirrel installer generates. You should be able to find the log file here:

`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`

If no log file is being generated there you should be able to find one in the `SquirrelTemp` directory:

`%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

Please upload that as an attachment.

**Comment by cyric2020** [comment]
The log only said something about the updated initialising and nothing else, I just installed a fresh version of windows and its working fine now.
