### ISSUE TITLE
GitHub Desktop very slow to commit after re-install

### ISSUE THREAD

**Issue by kvz** [desktop/desktop#11364]
### Describe the bug

Before my reinstall, a commit would be immediately, just like on my commandline. After the reinstall, it takes over a minute to commit a simple README.md change.

### Version & OS

Version 2.5.4-linux1.

I tried the latest version as well, to find the same behavior.

### Steps to reproduce the behavior

1. Change any file 
2. Commit

### Expected behavior

Near-immediate commit

### Actual behavior

Commit takes over a minute

### Screenshots

![image](https://user-images.githubusercontent.com/26752/104133133-d4bd6280-5381-11eb-8091-22e92294c7fc.png)

### Logs

```
2021-01-10T19:15:38.860Z - info: [ui] Background fetch for 3 repositories took 0.623sec
2021-01-10T19:16:35.940Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-01-10T19:18:13.325Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 95.848s)
2021-01-10T19:18:13.611Z - info: [ui] [Timing] Action 'create commit' for 'transloadit/transloadit-api2' took 96.172s
2021-01-10T19:20:24.302Z - info: [ui] Executing parseTrailers: git interpret-trailers --parse (took 122.124s)
```

**Comment by steveward** [comment]
Thanks for the report @kvz. I'd recommend opening up an issue in the repository for the Linux fork of GitHub Desktop:

https://github.com/shiftkey/desktop/issues

I'm going to close this out.

**Comment by kvz** [comment]
Thanks, I've moved the issue over to https://github.com/shiftkey/desktop/issues/413.

By the way, are there any desires for merging these projects and roll out official Linux support from this repo?

**Comment by johannesschobel** [comment]
Dear @kvz ,
unfortunately, there is no official support for linux - for now.

I think, this question arises on a monthly basis, haha. See these issues for example #1525, #11273, #10799, #9841, #9820.

All the best

**Comment by kvz** [comment]
One of the last pieces to the puzzel for an ideal dev setup on Linux for me :) 

Hoping this can be a reality one day 🙌

**Comment by johannesschobel** [comment]
@kvz , yeah, but you can easily use this repository, jump to the `releases` ( https://github.com/desktop/desktop/releases ) and download the latest version here manually..

I do this "from time to time" (i.e., whenever i think of it, haha) and it works perfectly for me ;)

All the best
