### ISSUE TITLE
On hover show full message

### ISSUE THREAD

**Issue by maifeeulasad** [desktop/desktop#11375]
### Describe the feature or problem you’d like to solve

Complete message of current operation is not visible.

### Proposed solution

On hover show complete message.

### Additional context

A gif of current problem : 

![Screencast from মঙ্গলবার 12 জানু 2021 12 35 48 +06](https://user-images.githubusercontent.com/29339330/104278696-36d9ad00-54d3-11eb-80ae-a410ffc39de2.gif)

**Comment by harshilparmar** [comment]
Can I take this?

**Comment by maifeeulasad** [comment]
I was thinking, I'll get assigned by default.
