### ISSUE TITLE
Pull Request list not updating

### ISSUE THREAD

**Issue by abott123** [desktop/desktop#11378]
### Describe the bug

Github Desktop used to update the list of pull requests.  Now as developers close or add pull requests I need to close Github Desktop and reopen it to see the current list of PRs to select from.

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Have more then one pull request in github.
2. Have some close one of them or close it yourself using the browser, not github desktop.
3. Try to fetch to refresh
4. Try the refresh button on the pull request tab.  That button seems to be disabled.
5. Look at the branch and pull request list.  You will find the closed pull request is still listed.
6. Close github desktop and reopen it
7. Now the closed PR is removed from the list.

### Expected behavior

I would expect that after refreshing the list would be updated as it was in previous versions.

### Actual behavior

The PR list is not being refreshed.  Maybe the branch list also is not being refreshed.

**Comment by abott123** [comment]
I am running github desktop on Windows 10 Version 10.0.19042 Build 19042 and this started happening on version 2.6.1 of github desktop.

**Comment by steveward** [comment]
Thanks for the report @abott123.

We have confirmed this to be a problem with the latest production version and we've come up with a fix in https://github.com/desktop/desktop/pull/11241. We'll be releasing an update (https://github.com/desktop/desktop/pull/11369) with a fix for this shortly. For now the best workarounds are to either switch to another repository and then back again as that will force a reload of the PR list or, as you've already found, to restart the app.

You could also try out our [beta channel](https://github.com/desktop/desktop#beta-channel) while you wait for the next official release.
