### ISSUE TITLE
Login failed in Desktop app

### ISSUE THREAD

**Issue by anoopjbee** [desktop/desktop#11370]
### Unable to authenticate user login in desktop app

I am able to login to my client repo using my credentials. But when I use same credentials in Desktop Git app it does not work

### Steps to reproduce the behavior

1. Go to '...' open app
2. Click on '....' clone from internet

mail anoopjb@in.ibm.com
username anoopjbee

**Comment by steveward** [comment]
@anoopjbee you should be authenticating via your browser in GitHub Desktop. Please go to `File` > `Options` > `Accounts` and verify that you are logged in to your account there. 

If you continue to encounter issues please send over the log file from GitHub Desktop. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by samsungbiologics** [comment]
big problems os computer
