### ISSUE TITLE
GitHub Desktop version is too old

### ISSUE THREAD

**Issue by yeldarby** [desktop/desktop#11373]
### Describe the bug

I reinstalled my operating system and GitHub Classic won't let me login. I realize the app is not receiving active updates but I've been using it up until this morning with no problems and it perfectly fits my workflow. No interest in upgrading to the Electron version without #2191 being added (which as I understand isn't going to happen...).

I would have expected that if use of the legacy version was going to be cut off it would have been clearly communicated.

### Version & OS

GitHub Desktop (native/classic)
Tasty Things Done Tastily (224)

MacOS 11 Big Sur

### Steps to reproduce the behavior

1. Install [from here](https://central.github.com/mac/latest)
2. Try to login

### Expected behavior

Successful login.

### Actual behavior

Blocked with message "GitHub Desktop version is too old"

### Screenshots

![image](https://user-images.githubusercontent.com/870796/104246010-de4ed500-542a-11eb-90cb-47a3be18f26a.png)

**Comment by yeldarby** [comment]
I think it might have to do [with this](https://developer.github.com/changes/2020-02-14-deprecating-oauth-app-endpoint/) but that isn't supposed to take effect for another 5 months or so.

**Comment by billygriffin** [comment]
Hi @yeldarby, thanks for the issue. I'm assuming this is the problem, which was removed last November: https://developer.github.com/changes/2020-02-14-deprecating-oauth-auth-endpoint/

As you alluded to, we are no longer providing support for the old version, so unfortunately I'm not able to help beyond that if you don't intend to try out the new version. Hope you're able to find something that works for you, and apologies that I can't give you a better answer.
