### ISSUE TITLE
JetBrains Clion integration

### ISSUE THREAD

**Issue by mreinart** [desktop/desktop#11379]
### Describe the feature or problem you’d like to solve

Nearly the whole family of JetBrains IDE flavors seems to be supported for integration/as editor - except CLion.
Is there a specific reason fro not supporting C/C++ IDE from JetBrains?

### Proposed solution

Better integration for C/C++ based projects.

### Additional context

N/A

**Comment by steveward** [comment]
Thanks for the request @mreinart. We're tracking broader support for JetBrains IDEs in https://github.com/desktop/desktop/issues/9453. I'll add this into that thread.
