### ISSUE TITLE
Authentication failed while I try to clone the repository only on my MAC machine

### ISSUE THREAD

**Issue by xpoarul** [desktop/desktop#11377]
Am able to login in github using my credentials and able to see my repo and also able to login from github desktop also. When i try to fetch the repository, it says authentication failed. This issue is seen only on my mac machine, when I try to do the same on other machine with my login, am able to fetch or clone. should i change any config in my machine or any idea to resolve this issue. 

Mac version - 10.15. 4
github desktop version - 2.3.1

[2021-01-12.desktop.production.log](https://github.com/desktop/desktop/files/5802245/2021-01-12.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @xpoarul. It looks like you are authenticated:

`2021-01-12T12:33:09.430Z - info: [ui] [AppStore] adding account xpoarul (xpoarul) to store`

Have you tried logging out and logging back in? If that does not get things working I would recommend trying to clear out the stored credential in `Keychain Access.app`. Search for `GitHub - https://api.github.com` and delete the stored token. Then try authenticating again in GitHub and let me know if it doesn't get things working.

**Comment by xpoarul** [comment]
@steveward  -
1. Yes tried logging out and logging back,
2. deleted GitHub - https://api.github.com from the keychain and then tried to authenticate
3. uninstalled and reinstalled the github desktop
4. From colleagues machine, i tried with my login and it is working.
Issue is seen only on my system.

**Comment by steveward** [comment]
@xpoarul thanks for the update. Do Git operations succeed in this repository from the command line (i.e. are you able to perform a `git fetch`)? Have you tried working with any other repositories in GitHub Desktop to see if you can reproduce the issue?

**Comment by starpods** [comment]
https://login.us2.oraclecloud.com/oam/server/auth_cred_submit

**Comment by Vehiz** [comment]
I tried cloning my organisations repo which I have access to, from the terminal. After keying in my login details, I am getting 'Authentication failure' error, please How can I go about this  ?

**Comment by m2gi-pavlovm** [comment]
same issue here, i login just fine but when i try to clone, it says authentication failure, and neither a PAT nor my password work, neither with username, nor with email

**Comment by bobitro32** [comment]
i have the same problem right now

**Comment by steveward** [comment]
If you're having issues please open a new issue and fill out the template so we can assist you further. Thanks!
