### ISSUE TITLE
Login Issue with Github Desktop - PoP_OS

### ISSUE THREAD

**Issue by cBodenwinkler** [desktop/desktop#11372]
### Describe the bug

Login doesn't work with both the app and the 'sign in using your browser' option. Button shows a short load and then stops. Have this problem for some time now. (Don't know exactly)

### Version & OS

Can't open the 'About GitHub Desktop' menu.
Operating System is PoP_OS 20.04. LTS

**Comment by cBodenwinkler** [comment]
[2021-01-11.desktop.production.log](https://github.com/desktop/desktop/files/5797753/2021-01-11.desktop.production.log)

**Comment by steveward** [comment]
@cBodenwinkler for issues with the Linux fork of GitHub Desktop please open an issue in https://github.com/shiftkey/desktop. It looks like you may be running into https://github.com/shiftkey/desktop/issues/134. I'm going to close this issue out -- thanks for using GitHub Desktop.
