### ISSUE TITLE
Error While Cloning Bitbucket URL on Mac

### ISSUE THREAD

**Issue by mkinkarhurix** [desktop/desktop#11374]
Hello,

I am trying to use the bitbucket URL to clone the repository, but it is giving the below error on Mac,

**Cloning :** 
![clone-issue](https://user-images.githubusercontent.com/76177584/104274906-df820f80-54c7-11eb-8203-3e55bf69b877.PNG)

**Error Log:**
![cloning-log](https://user-images.githubusercontent.com/76177584/104274749-903bdf00-54c7-11eb-9b5e-9d910ca02fe1.PNG)

Already tried all the suggestion which are mentioned in know-issue.md file. But nothing is working for Mac

**Comment by steveward** [comment]
@mkinkarhurix thanks for the report. It looks like your credentials aren't being found. Did you follow the steps in [this article](https://github.com/desktop/desktop/blob/development/docs/integrations/bitbucket.md) to generate a token to use in GitHub Desktop? If you have any existing credentials I'd recommend trying to delete them and then generate a new token. To check your existing tokens you can go to `Keychain Access` and look for `GitHub - <your_bitbucket_instance>`.

Let me know if that doesn't get things working.

**Comment by mkinkarhurix** [comment]
Hello, 

I followed the steps mentioned in the post but  [this article ](https://github.com/desktop/desktop/blob/development/docs/integrations/bitbucket.md) but I am still getting the same error on Mac.

**Comment by steveward** [comment]
@mkinkarhurix has GitHub Desktop previously worked on this machine? The `permission denied` error seems to indicate you may need to modify the permissions on your machine. Does cloning via the command line succeed?
