### ISSUE TITLE
Cannot add RStudio as external editor in github desktop

### ISSUE THREAD

**Issue by alok1920** [desktop/desktop#11386]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
Thanks for the feedback @alok1920. At this time GitHub Desktop only supports editors that have been specifically integrated into the application. You can find the details of how this works along with the supported editors here:

https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md

We happily accept pull requests to integrate new editors. There is also a tracking issue where we are collecting feedback about better support for external editors:

https://github.com/desktop/desktop/issues/7033

I'm going to leave this open in case someone wants to work on getting RStudio added as an integration.
