### ISSUE TITLE
I cant access my web page. error 404 

### ISSUE THREAD

**Issue by UniverseX21** [desktop/desktop#11389]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@UniverseX21 this issue tracker is for GitHub Desktop, if you are having issues with GitHub Pages I'd recommend asking for help [in our community forum](https://github.community/c/github-help/github-pages/31/l/new).
