### ISSUE TITLE
committer user

### ISSUE THREAD

**Issue by tonycody** [desktop/desktop#11383]
![image](https://user-images.githubusercontent.com/6773121/104393375-49a9bb80-557f-11eb-8f69-157a9150fbce.png)
It is recommended that the submitting user be associated with the repository, and each repository can be user A or user B.
exp:
repository1  use user-1
repository2 use user-2

Because submitting to the GitHub repository should not be the same user as submitting to the company repository

**Comment by steveward** [comment]
Thanks for the feedback @tonycody. We are tracking better handling of improper commit attribution in https://github.com/desktop/desktop/issues/610. There is some [work being done for per-repository commit attribution](https://github.com/desktop/desktop/issues/9449) and Git also has [a configuration option you can use](https://github.com/desktop/desktop/issues/610#issuecomment-630411213) to differentiate between work and personal repositories. I hope that is helpful!
