### ISSUE TITLE
Feature request: In the suggested local path add the username while cloning a repo

### ISSUE THREAD

**Issue by rallets** [desktop/desktop#11406]
### Describe the feature or problem you’d like to solve

When I clone a repo using "Open with GitHub Desktop", the suggested local path (on Windows) contains only the repo name, which can conflict with an existing one. This can happen when you fork a repo, and have also the original one.

### Proposed solution

In the clone repo dialog, prefix the local path with the username, or had a sub-folder.
As example: user "user1", repo "github-desktop"
Proposed local path: C:\GitHub\user1-github-desktop"
OR
Proposed local path: C:\GitHub\user1\github-desktop"

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.
![image](https://user-images.githubusercontent.com/379999/104845347-3c6d3380-58d5-11eb-8a20-ee688a226cfa.png)

**Comment by jackjt8** [comment]
It's not even just this.

Clone repo from user1 and it suggests `user1\a-repo-name` like you suggested. 

Clone a fork of the repo from user2 and it proposes `user1\a-repo-name` . It doesn't correctly recognize forks are different.

---

This behaviour has been reported multiple times and no movement has been made.

**Comment by tinohager** [comment]
- https://github.com/desktop/desktop/issues/5449
- https://github.com/desktop/desktop/issues/7685
- https://github.com/desktop/desktop/issues/12583

**Comment by steveward** [comment]
Thanks @tinohager, I'm going to consolidate this into #5449.
