### ISSUE TITLE
What's new dialog box is too small

### ISSUE THREAD

**Issue by tntc4** [desktop/desktop#11402]
### Describe the feature or problem you’d like to solve

Currently i'm working on 24' LCD monitor (1920 x 1080 is current resolution).
But when a new version is available, and I click "What's new" link i see something like this screen shot.
![Screenshot_1](https://user-images.githubusercontent.com/3246834/104819079-ee542380-5833-11eb-9106-aa9f5b0b9194.png)

### Proposed solution

Can you pls increase the dialog box so I not scroll like champ this tiny scrollbar where the What's new description is.

**Comment by steveward** [comment]
Thanks for the feedback @tntc4. Is the issue the size of the dialog box or the small width of the scrollbar making it difficult to select? We're tracking feedback about scrollbar improvements in https://github.com/desktop/desktop/issues/4776.

**Comment by tntc4** [comment]
My issue is with dialog box size.

**Comment by steveward** [comment]
Closing in favor of https://github.com/desktop/desktop/issues/6851 which is an existing issue about this.
