### ISSUE TITLE
Integration with Adobe Dreamweaver

### ISSUE THREAD

**Issue by jenssss** [desktop/desktop#11407]
### Describe the feature or problem you’d like to solve

I would like to be able to open Adobe Dreamweaver directly from Github Desktop. When trying to change the default editor in Desktop preferences, Dreamweaver does not show up, and from the docs it looks like Dreamweaver is currently not supported.

**Comment by niik** [comment]
Hey @jenss, thanks for reaching out! Just like you suspected GitHub Desktop only supports editors that have been specifically integrated into the application.. You can find the details of how this works along with the supported editors here:

https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md

We happily accept pull requests to integrate new editors. There is also a tracking issue where we are collecting feedback about better support for external editors:

https://github.com/desktop/desktop/issues/7033

I'm going to leave this open in case you or someone else wants to work on getting Adobe Dreamweaver added as an integration.

**Comment by sol5000** [comment]
yes

**Comment by tsvetilian-ty** [comment]
Hello 👋 I tried to implement the Dreamweaver integration but had an issue along the way. Dreamweaver's executable doesn't support a directory as a param, instead expects a file. So if you try to run the integration, it crashes.

![dw](https://user-images.githubusercontent.com/9341546/117549778-f46d4a80-b044-11eb-835d-9ea6bc139fd9.gif)

**Comment by steveward** [comment]
GitHub Desktop now provides support for [adding custom editors](https://docs.github.com/en/desktop/configuring-and-customizing-github-desktop/configuring-a-default-editor-in-github-desktop?platform=windows#configuring-a-custom-editor), so Adobe Dreamweaver can be added that way. I'm going to close this out.
