### ISSUE TITLE
Fails to push, saying rejected by another machine

### ISSUE THREAD

**Issue by ChadTheSecondEthan** [desktop/desktop#11419]
### Describe the bug

When pushing a commit, it says No connection could be made because the target machine actively refused it

### Version & OS

Version 2.6.2, OS is Windows 8

### Steps to reproduce the behavior

1. Commit changes
2. Push to origin

### Expected behavior

It should simply push my commit to github

### Actual behavior

This error pops up

Post "https://github.com/ChadTheSecondEthan/Fast-Food-Game-3D.git/info/lfs/locks/verify": proxyconnect tcp: dial tcp [::1]:80: connectex: No connection could be made because the target machine actively refused it.
error: failed to push some refs to 'https://github.com/ChadTheSecondEthan/Fast-Food-Game-3D.git'

### Additional context

I just created a repository. My initial commit was successfully pushed, but every commit that I've tried since then has failed.

**Comment by steveward** [comment]
Thanks for the report @ChadTheSecondEthan. Are you behind a proxy or firewall that could be interfering with your connection to GitHub? Are you using Git LFS with this repository?

**Comment by ChadTheSecondEthan** [comment]
No, I am not behind a proxy or firewall. I am also not using Git LFS.

**Comment by steveward** [comment]
@ChadTheSecondEthan are you able to perform a `git push` from the command line successfully?

**Comment by steveward** [comment]
@ChadTheSecondEthan I'm going to close this issue out as we have not heard back from you yet. Let me know if you are still having issues.
