### ISSUE TITLE
Repository being Cached

### ISSUE THREAD

**Issue by RebornBeat** [desktop/desktop#11415]
### Describe the bug

While deleting a local repository directly from Github.com and then removing the Git files in my folder and repo from the desktop app, I am still presented with the same changes and commits upon creating a new repository in Github Desktop, believing that the Repo is still live and presenting a 404 github repo link on click. I have tried changing the name of the repo and the name of the folder location and the problem still persits. A bit annoying, is the desktop saving cached files somewhere that isnt being deleted on repo delete?

### Version & OS

Version 2.6.2 Win 10

### Expected behavior

To have a clean repo on creating upon deleting the old one.

### Actual behavior

Cached files and commits of deleted repo.

**Comment by steveward** [comment]
@RebornBeat GitHub Desktop does not delete the repository files on disk unless you select the option to send the files to the Recycle Bin. You will need to manually delete the repository in File Explorer.

If you want to start a fresh repository you will need to delete the hidden `.git` directory inside of the repository. I hope that helps!

**Comment by RebornBeat** [comment]
> @RebornBeat GitHub Desktop does not delete the repository files on disk unless you select the option to send the files to the Recycle Bin. You will need to manually delete the repository in File Explorer.
> 
> If you want to start a fresh repository you will need to delete the hidden `.git` directory inside of the repository. I hope that helps!

Should there not be an option to delete this without sending it to the recycling bin?

**Comment by steveward** [comment]
It isn't common to delete the `.git` directory, which is why this option is not available.
