### ISSUE TITLE
Can't Find 'GitHub'

### ISSUE THREAD

**Issue by mw-developers** [desktop/desktop#11411]
I need help!!!
"C:\Users\admin\Downloads\Can't find .png"
<img width="1128" alt="Can't find " src="https://user-images.githubusercontent.com/74386582/104922895-30e04200-5993-11eb-8c04-38cea1e884a4.png">

**Comment by steveward** [comment]
@mw-developers thanks for the report. I see you are storing your repositories in OneDrive -- generally we recommend storing repositories outside of file syncing services since it can sometimes cause file corruption issues. Does that location still exist on disk on your machine?
