### ISSUE TITLE
Can't install Github Desktop.

### ISSUE THREAD

**Issue by FishBugs** [desktop/desktop#11426]
I'm having trouble installing GitHub Desktop
Whenever I try to run the GitHub Desktop setup it will pull up with a window that says "Update has stopped working" and then another saying "Installation has failed". I'm running Windows 7 and my computer is 64-bit. 
Here is my log:
[SquirrelSetup.log](https://github.com/desktop/desktop/files/5843534/SquirrelSetup.log)

I have also tried the MSI download but when I ran that setup i got no response from it.

**Comment by steveward** [comment]
Sorry to hear you're having trouble installing GitHub Desktop @FishBugs.

Are you running any antivirus security software on this machine? If so, I would recommend disabling it during the installation process. 

If that does not get things working try clearing out the `C:\Users\N987\AppData\Local\SquirrelTemp` directory. It'd also be helpful if you could check to see if anything is being written to `C:\Users\N987\AppData\Local\GitHubDesktop`.

**Comment by FishBugs** [comment]
I just tried to install it after turning off my anti-virus (Norton) but that didn't work either.

Stuff is being written into C:\Users\N987\AppData\Local\GitHubDesktop. There is Update.exe, GitHubDesktop.exe, and two folders: "packages" and "app-2.6.2".

**Comment by steveward** [comment]
@FishBugs I was able to install GitHub Desktop without issue on a machine running Windows 7 SP1. Are there any group policy or other restrictions on your machine that could be preventing GItHub Desktop from installing? 

There are a couple of other things we can try to see if it gets GitHub Desktop working.

- Open up an elevated command prompt and run `sfc \scannow`. This will scan your system for any issues that may be causing the installation to fail, such as missing DLLs.

- Run the .NET Framework Repair Tool. This will scan your system for any issues with your .NET installation and attempt to repair them. You can download that here:

http://www.microsoft.com/en-us/download/details.aspx?id=30135

Let me know if either of those steps helps.

**Comment by steveward** [comment]
@FishBugs as we have not heard back from you I am going to close this issue out. Let me know if I can be of any further assistance.
