### ISSUE TITLE
fatal: unable to access 'https://github.com/ErosMLima/Instagram.git/': getaddrinfo() thread failed to start

### ISSUE THREAD

**Issue by ErosMLima** [desktop/desktop#11427]
I try to make the git push and don't work, they give me this message:
"fatal: unable to access 'https://github.com/ErosMLima/Instagram.git/': getaddrinfo() thread failed to start"

in the GitHub Desktop version too, so how I can fix this? I try to watch and read about but notting make effect.

"### Describe the bug

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the report @ErosMLima. Just to clarify -- are you seeing this error in both the command line and in GitHub Desktop?

This looks like a specific cURL error. Are you behind a firewall or running any antivirus/security software on your machine?

**Comment by ErosMLima** [comment]
Yes in the Git and the GitHub send me the same error. When I watch the people making the "git push origin master" this action activate some login asking for the ID and Password of the github, but in my case this don't happen, and I try to re-install or unistall several time, thanks for answer, and I wait for a solution.

**Comment by steveward** [comment]
>When I watch the people making the "git push origin master" this action activate some login asking for the ID and Password of the github,

That is the specific authentication flow for the command line. See [this guide](https://docs.github.com/en/github/authenticating-to-github/about-authentication-to-github#authenticating-with-the-command-line) for how to create a token to use on the command line.

To get some more information about the errors you are encountering in GitHub Desktop it would be helpful if you could upload a log file. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by ErosMLima** [comment]
Thanks, I'm gonna try this and comeback when I find if this method gonna work.
Thanks for the answer and the link for the exactly part that maybe help me.

**Comment by steveward** [comment]
@ErosMLima I'm going to close this out as we have not heard back from you. Let me know if you are still having issues and we can dig into this further.
