### ISSUE TITLE
search commits by keyword

### ISSUE THREAD

**Issue by guolanren** [desktop/desktop#11421]
### Describe the feature or problem you’d like to solve

It cost my much time to find a history commit. If it support search, 

### Proposed solution

Easy to find what i want

### Screenshot

![image](https://user-images.githubusercontent.com/17938708/105115797-71130200-5b04-11eb-806a-134d118876f3.png)

**Comment by steveward** [comment]
@guolanren Thanks for the suggestion. We have a similar request [here](https://github.com/desktop/desktop/issues/7022), so please follow along for any updates and share please share any specific issues you may want addressed.
