### ISSUE TITLE
Can't Publish to master

### ISSUE THREAD

**Issue by BlackRece** [desktop/desktop#11436]
### Describe the bug

GitHub Desktop reports that the file size quota has been reached on target repo.
I am trying to commit and empty Unity project to the master branch to begin a new project.
The size being committed is under 491MB
Git LFS is installed and configured.

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.
Ver 2.6.2 on Win 10

### Steps to reproduce the behaviour

1. Go to repo https://github.com/BlackRece/TGPGame.git
2. Click publish branch
3. See error: 
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to push some refs to 'https://github.com/BlackRece/TGPGame.git'

### Expected behaviour

Some message to confirm all files and folders have been committed to repo

### Actual behaviour

Error message and no data committed

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.
![image](https://user-images.githubusercontent.com/19497851/105412951-538d8780-5c2d-11eb-9407-10d3884ca83d.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
[2021-01-21.desktop.production.log](https://github.com/desktop/desktop/files/5852197/2021-01-21.desktop.production.log)

**Comment by steveward** [comment]
@BlackRece I took a look at the repository and it does look like the repository is over its free data quota of 1GB. You can see the specific pricing and quotas for Git LFS [here](https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-git-large-file-storage). If you have any further questions about Git LFS plans I'd recommend reaching out to [GitHub Support](https://support.github.com/).

**Comment by BlackRece** [comment]
i don't understand how a folder that is around 500MB, can't be split between GitHub and Git LFS.
I thought it was a setup issue, not a quota issue.
The ignore file and attributes file should be functioning.
How do i remove the files that the ignore and attribute files should be dealing with?

**Comment by steveward** [comment]
@BlackRece If your repository size is 500MB then you shouldn't run into an issue as long as you aren't performing pushes that would exceed the free bandwidth of 1GB over the period of a month. The 500MB in size would be under the 1GB storage allocation, so the only issue would be total bandwidth used. I hope that helps!
