### ISSUE TITLE
Show README in Desktop app (Enhancement proposal) 

### ISSUE THREAD

**Issue by tomkyle** [desktop/desktop#11433]
### Describe the feature or problem you’d like to solve

Is it possible to let desktop app render the current repo's README (like the web frontend does), or offer a shortcut way to open the repo README in its editor?

### Proposed solution

New box in the desktop app's repo canvas (where at repo clean state boxes inform about “push commits using Cmd-P” or “Open repo in external editor using Cmd-Shift-A”). The box would be titled “View README” and offer a button “Open in editor” (which then opens the .md file in the Markdown editor).
Luxury version: In an ideal world, Desktop app would render the Markdown directly under these boxes, with its TOC in the left sidebar under a third tab “Documentation” (beneath Changes and History). Activating that tab would make the canvas render the docs again. 

How will it benefit Desktop and its users?
A keyboard shortcut will shorten the way to the most used project documentation, the repo README. Compared to current situation: Now one has to view the repo in Finder/File explorer, locate the README and open it, and switch back to Desktop …

### Additional context
Quick tinkering with screenshots:
![Github-proposal-20210121](https://user-images.githubusercontent.com/412560/105372610-119d1b00-5c06-11eb-94bc-9f2dc2a5e691.png)

**Comment by steveward** [comment]
Thanks for the feedback @tomkyle. I'm going to drop this into https://github.com/desktop/desktop/issues/8687 where we are capturing feedback about this. At this time this feature is not on our radar (which is why the issue is closed), but this may be something we look into in the future.
