### ISSUE TITLE
Desktop column max sizes

### ISSUE THREAD

**Issue by vituel** [desktop/desktop#11449]
Columns in the desktop app are still locked to a max size. So changes, and file directory on commits, are hard to see the full scale of.

### Proposed solutions

1. Make the "drag column width" unconstrained.
2. Make some of the columns - like the code changes - collapsible.
3. Add possibility to left/right align commit file-list paths.

**Comment by niik** [comment]
Hey, thanks for reaching out! This looks very similar to the request in https://github.com/desktop/desktop/issues/2745 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date with any development happening in that area.
