### ISSUE TITLE
UX: 'Create a branch' from another branch dialog

### ISSUE THREAD

**Issue by staabm** [desktop/desktop#11440]
### Describe the feature or problem you’d like to solve

when checking out a 'release branch', to create a new branch based on the currently checked out one (e.g. to build a hotfix for this release branch), github desktop opens a dialog with the 'master' branch pre-selected.

it requires an additional click to confirm the re-select the 'release branch'.

sometimes I don't notice that I need this additional click, start working in the newly created branch (which was mistakenly created based from 'master'). I finally realize that all my commits are based on the wrong branch when in the end of the process I open a PR which tells me that the target branch I originally had in mind has conflicts with my new hotfix-branch.

**Current Dialog:**

![grafik](https://user-images.githubusercontent.com/120441/105476763-4ca05c80-5ca1-11eb-9ee3-6cd93578b2a9.png)

Note: 
- the currently select branch is 'DAIB_S024'
- the pre-selected branch in the dialog is 'master'

### Proposed solution

**alternative A)**

- instead of a 'Create branch' button and the above 'branch chooser' we could have 2 buttons: one reading 'create branch from master' and another one 'create branch from $current-branch'

that way the button I am clicking also gives me an idea which path I have taken

**alternative B)**

- preselect the previously selected branch (Current branch) instead of master

**Comment by steveward** [comment]
Thanks for the issue @staabm. This has been previously discussed in https://github.com/desktop/desktop/issues/9845, and [this comment](https://github.com/desktop/desktop/issues/9845) specifically outlines the reasoning behind this decision. 

At this time we don't have any plans to change this behavior. I'm going to close this issue out, but we'd still value feedback going forward about this decision and we do continue to evaluate issues even if they are closed. Thanks for using GitHub Desktop.
