### ISSUE TITLE
GitHub Desktop still defaults to creating a default branch titled master instead of main in some cases

### ISSUE THREAD

**Issue by KaiReidCasey** [desktop/desktop#11447]
### Describe the bug

GitHub Desktop still defaults to creating a default branch titled master instead of main when building out a new repository. GitHub was moving away from this practice to be more inclusive.

### Version & OS

Version 2.6.2 on Windows 10

### Steps to reproduce the behavior

1. Log into your account on GitHub and open GitHub Desktop (if they aren't open already)
2. Navigate to your repositories (https://github.com/{{YOUR_PROFILE_NAME}}?tab=repositories)
3. Click the green 'New' button that should be in the upper left corner
4. Add a valid repository name
5. Add a valid repository description
6. Public/private doesn't matter
7. Click 'Create repository'
8. Once it is created, go to GitHub Desktop and File>Clone repository...
9. Click the refresh button to the mid-upper left
10. Click your new repository's name
11. Click the Clone button near the bottom
12. Current branch is now set to **master.**

You cannot rename master from here by going to Branch>Rename or by hitting Ctrl+Shift+R.
This does not change if you create a file, until that file is pushed.

### Expected behavior

In step 12, I expected that the current branch would be set to **main.**

### Actual behavior

In step 12, the current branch was set to **master.**

### Screenshots

A screenshot of a repository called i_caused_a_bug with the current branch set to master. A file named foo.py is displaying it's diff, which only includes the comment "# foo.y"

![github_desktop_bug_report_master_0](https://user-images.githubusercontent.com/9575844/105608341-6d37e780-5d71-11eb-92c8-7ed7b7ade43e.PNG)

### Logs

[2021-01-23.desktop.production.log](https://github.com/desktop/desktop/files/5860573/2021-01-23.desktop.production.log)

### Additional context

I just hope it's fixed soon. It seems like if I create a new repository from GitHub Desktop (test in the logs), it sets the first branch to main as expected, so that's a good start.

**Comment by billygriffin** [comment]
@KaiReidCasey Sorry about that! Thanks for the feedback - I can see how that's confusing, as it happens even if you have your Git preferences in Desktop set to use `main` and your preference on GitHub also set to use `main`. 

The problem here is that it's initialized as an empty repo without an initial commit, and we obviously didn't cover that case. This is something we'll look at, but in the meantime, if you create the repo with a README on GitHub.com prior to cloning, or if you create the repo from Desktop, both of those should pick up the correct default branch name.

**Comment by sergiou87** [comment]
This should've been fixed in #11487 😌 

Thanks for your report and your patience! The fix should be out in a few weeks from now 😄
