### ISSUE TITLE
Authentication failes after a while

### ISSUE THREAD

**Issue by ArmanJakupovic** [desktop/desktop#11442]
### Describe the bug

Client keeps asking for authentication/credentials when updating branch. Once logged in it will stay logged in but after a while it will log me out and once again ask for my credentials.

### Version & OS

Github Desktop 2.6.2, Windows 10x64

### Steps to reproduce the behavior

1. Go to azure devops and pick your project
2. Go to repos and clone a repo
3. Generate git credentials
4. Enter credentials into github desktop
5. Clone and do some changes
6. Reboot machine
7. Start github desktop
8. Try to push or pull
9. Client once again asking for credentials.

### Expected behavior

Client not asking for credentials after reboot or after some time. 

### Actual behavior

Once an hour or two have passed the client asks for authentication when trying to update branch.

### Logs

2021-01-22T14:46:23.780Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr: fatal: Authentication failed for 'https://my.visualstudio.com/DefaultCollection/domain.repo/_git/repo/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)

**Comment by steveward** [comment]
Thanks for the report @ArmanJakupovic. This looks similar to what was reported in https://github.com/desktop/desktop/issues/9579 and https://github.com/desktop/desktop/issues/10078. Have you tried generating a new token to see if that resolves the issue? I see you mentioned `Generate git credentials` but I wanted to verify you were generating a new access token.
