### ISSUE TITLE
Add change log/log for whats not present in stable version, alongside download link for transparency reasons

### ISSUE THREAD

**Issue by ankushduacodes** [desktop/desktop#11444]
### Describe the feature or problem you’d like to solve
I think it would be great to add a little link to the features/bugs that are present in the beta version those have to not yet made it to stable version for transparency reasons.

How will it benefit Desktop and its users?
Better transparency/user knowledge. A direct download button does not say much.

**Comment by billygriffin** [comment]
Thanks @ankushduacodes! Opened a PR to address this, appreciate the suggestion.
