### ISSUE TITLE
Adding a button to go to github.com/<loggedin-user>

### ISSUE THREAD

**Issue by ankushduacodes** [desktop/desktop#11443]
### Describe the feature or problem you’d like to solve
There is no way(to my knowledge) to get to logged in user profile from inside github desktop
### Proposed solution
My solution would be to add a tiny button on the top right side of the github desktop(beside `fetch` button) that points to the profile and opens the link in default browser when clicked.

### How will it benefit Desktop and its users?
I think its a convenience feature and I find myself looking for.

**Comment by billygriffin** [comment]
Hi @ankushduacodes, thanks for the idea. I don't think this is something we'll plan to do just because it's not something we've heard sufficient feedback about to warrant space in the UI. But I'm curious to hear more about why you're hoping to frequently get from Desktop to your user profile page on GitHub.com if you don't mind sharing.

**Comment by ankushduacodes** [comment]
Hi @billygriffin, There are a number of reasons for which I find myself going to my profile.
1. To check if I have any notification.
2. To get a link to a repo I want to clone.
3. To get to repo I am contributing to ask a question or reply(Although this could be a different issue)

**Comment by billygriffin** [comment]
Thanks @ankushduacodes! I think all of these should be accessible through other means. You can use "View on GitHub" to just get to dotcom, or clone a repo right from Desktop.

<img width="925" alt="Screen Shot 2021-01-25 at 6 57 07 AM" src="https://user-images.githubusercontent.com/5091167/105715206-8d36ea80-5eda-11eb-9db5-48f35966b7a3.png">

I really appreciate the idea and thanks so much for sharing more context. 😄
