### ISSUE TITLE
Merge state:  add "Undo" for each file

### ISSUE THREAD

**Issue by sneltyn** [desktop/desktop#11465]
### Describe the feature or problem you would like to solve.

In a state of fusion, when the conflict for file solved the case, he resolved not correct and want to cancel it, but to have an abortion not really, as will have to re-solve conflicts. I think it would be convenient if you could roll back to the original merge state for a specific file.

### Proposed solution

With the help of the console, this problem is easily solved:

```
git checkout -m <file_path>
```
It would be possible to make Undo available for all files in conflict, see the attached screenshot.

### Additional context

![image](https://user-images.githubusercontent.com/7827331/105873950-b3f14000-6004-11eb-875c-70c022a2c93e.png)

**Comment by billygriffin** [comment]
Hi @sneltyn, thanks for the issue! I think this is interesting, but we've never heard feedback about this before and I think the use case is too complex to warrant such a prominent position in the UI. This is intended to make merge conflicts less intimidating and simpler, and adding additional complexity would run counter to that goal. Sorry I can't give you a better answer on this one, and thanks again for the suggestion. ❤️
