### ISSUE TITLE
Stash changes

### ISSUE THREAD

**Issue by mpirescarvalho** [desktop/desktop#11468]
### Describe the feature or problem you’d like to solve

Sometimes we need to save current changes, to work on something else, and get back to them later. Right now it's necessary to switch to a terminal to use stash features.  There sould be a possibility to stash and apply/unstash changes out of the box.

### Proposed solution

Add "Stash changes" option to files context menu

![image](https://user-images.githubusercontent.com/20830847/106000682-dd09e300-608d-11eb-9f01-7a1661de8361.png)

**Comment by steveward** [comment]
Hi @mpirescarvalho, we introduced support for stashing your changes when switching branches in GitHub Desktop 2.0, see our [blog post](https://github.blog/2019-06-05-github-desktop-expands-to-support-stashing-and-rebasing/) about that release for more details.

Right now we're not looking to expand on that support to include manual creation of stashing (see  https://github.com/desktop/desktop/issues/8197#issuecomment-527249225). Please subscribe to https://github.com/desktop/desktop/issues/8197 to stay notified of any developments there.

**Comment by steveward** [comment]
@mpirescarvalho you can right-click on the '6 changed files' to see the option to stash all of your changes. You will also see the option when switching branches. I hope that helps!
