### ISSUE TITLE
Adding existing files to a new repository is not working how I would expect

### ISSUE THREAD

**Issue by cyberangel67** [desktop/desktop#11462]
### Describe the bug

I would probably not call this a bug, but I would say this doesn't work as I would expect. I am used to Unity GitHub plugin, where it creates a repository in the same project as the existing files. But I don't like this plugin to Unity, because I can not roll back individual files or even merge changes. SO I am now looking into this Application.

So I am taking existing projects, non github repository projects and trying to create a repository for them.

My first port of call would be to use the New Repository, give it a name, and the location of where the files are and it creates a repository of the files here, but instead, it creates a folder with this name in that repository with no files added.

Now I managed to do this once, where it gave me a link to create a repository, but I don't know what I clicked on to do this.

### Version & OS

Version 2.6.2 and Windows 10

### Steps to reproduce the behavior

1) Go to file and select new repository
2) Type in the repository name
3) Give it the path to the existing Unity Project
4) Select Unity Git Ignore
5) Select Create Repository

### Expected behavior

Create a repository with the existing files added to the repository, ready to be pushed to a master online.

### Actual behavior

Creates a folder inside the unity project with the name that you entered, and no files have been added to the repository.

Like I said this is maybe not a bug, but very weird behaviour turning any project C#, Java, Website into a repository. Happy to answer anything that is not listed here, but this is really self-explanatory.

**Comment by steveward** [comment]
Thanks for the report @cyberangel67. This was also mentioned in https://github.com/desktop/desktop/issues/10774, and should be addressed by https://github.com/desktop/desktop/pull/10081. I'm going to close this out -- thanks for using GitHub Desktop!
