### ISSUE TITLE
Group repositories locally by owner

### ISSUE THREAD

**Issue by Zk2u** [desktop/desktop#11464]
There should be an option to group cloned repositories into folders with the respective repo's owner's username.

Nothing much else to say, mockups follow...

### Before

![before](https://user-images.githubusercontent.com/67651251/105866941-6cf75080-5fec-11eb-8d84-43377761d084.png)

### After feature is switched on

![after](https://user-images.githubusercontent.com/67651251/105866989-7b456c80-5fec-11eb-90c8-e497e331f483.png)

**Comment by niik** [comment]
Hey @xelamade, thanks for reaching out! This looks very similar to the request in https://github.com/desktop/desktop/issues/8461 so I'm going to close this issue in favor of that.

According to https://github.com/desktop/desktop/issues/8461#issuecomment-541944174 we're not looking to change this behavior but please subscribe to it to stay up to date with any development happening in that area and you may add an emoji reaction to it to signal your interest as well!
