### ISSUE TITLE
[fork] Remotes - rename 'upstream' to 'up', keeps returning

### ISSUE THREAD

**Issue by MSP-Greg** [desktop/desktop#11476]
### Describe the bug

With forks, I prefer to rename 'upstream' to 'up'.  I normally do this from Git for Windows.  It seems that Desktop keeps adding an 'upstream' remote.  This shows duplicated branches in the 'branch list', and `git remote -v` in Git for Windows shows the remote.

### Version & OS

2.6.2 & Windows 10 Pro

### Steps to reproduce the behavior

1. Using Git for Windows', run `git remote rename upstream up`
2. Using Git for Windows', run `git remote -v`, shows 'up', not 'upstream'
3. Open Desktop a few times (auto fetch?), and you'll see 'upstream' branches
4. Using Git for Windows', run `git remote -v`, shows both 'up' and 'upstream'

### Expected behavior

'upstream' remote disappears

### Actual behavior

It haunts me...

**Comment by sergiou87** [comment]
I'm sorry, but `upstream` is what Desktop uses internally to keep track of the remote representing the repo you forked from:

https://github.com/desktop/desktop/blob/a629e40/app/src/lib/stores/helpers/find-upstream-remote.ts#L6

If you want, you can just create a new remote called `up` that only you use, but Desktop will keep creating and using `upstream`.
