### ISSUE TITLE
cant authorise desktop

### ISSUE THREAD

**Issue by JeanAbiHanna** [desktop/desktop#11478]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by sergiou87** [comment]
Hello @JeanAbiHanna! I'm sorry you're having issues authorizing the app, but could you fill the template and provide more info? That would help us diagnose the issue and hopefully provide a solution.

Thank you!!
