### ISSUE TITLE
unable to clone via SSH or HTTPS

### ISSUE THREAD

**Issue by UJDS** [desktop/desktop#11471]
### Describe the feature or problem you’d like to solve

I have been trying since a very long time to clone a github repository on a windows machine using git-bash.
been trying via both SSH and HTTPs with no luck, can you look into it please?
SSH creates the empty folder which means git is able to access the target directory

--------------------------
$ git clone https://github.com/xxxx/Machine-Learning.git
Cloning into 'Machine-Learning'...
fatal: unable to access 'https://github.com/xxxx/Machine-Learning.git/': SSL certificate problem: unable to get local issuer certificate
----------------------
$ git clone git@github.com:xxxx/Machine-Learning.git
Cloning into 'Machine-Learning'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
----------------

![image](https://user-images.githubusercontent.com/78070540/106098115-efe5eb80-6151-11eb-8f66-c39d7d7f3601.png)

**Comment by sergiou87** [comment]
Hi @UJDS! 👋 I'm sorry you're having these problems, but I think the https://github.com/git-for-windows repo would be a better place to get help to fix them.

In a quick search I found this that might be relevant to you: https://github.com/git-for-windows/git/issues/1574

I hope that helps!
