### ISSUE TITLE
Commit failed - exit code 1 received with UI but works with command line

### ISSUE THREAD

**Issue by AdrianHordyk** [desktop/desktop#11488]
### Describe the bug

Any new commit with GitHub Desktop now results in this error: `Commit failed - exit code 1 received`

Was working fine until yesterday - although my Github Desktop wasn't updated recently.  Tried a re-install, same problem.

Problem so far only occurs with one repo. 

Tried the approaches described [here](https://stackoverflow.com/questions/50052115/commit-failed-exit-code-1-received-when-trying-to-commit-a-new-local-reprosi). Do not appear to have any nested .git directories or .gitmodules.

Committing with `git commit -F -` in the console works fine.

### Version & OS

Version 2.6.2. Windows 10 Pro

### Steps to reproduce the behavior

Commit any file with Github Desktop

### Expected behavior

Changed files to commit as usual.

### Actual behavior

Stages but doesn't commit.

### Logs

2021-01-29T17:13:05.687Z - info: [ui] [AppStore] loading 33 repositories from store
2021-01-29T17:13:05.689Z - info: [ui] [AppStore] found account: AdrianHordyk (Adrian Hordyk)
2021-01-29T17:13:05.846Z - info: [ui] [BranchPruner] Last prune took place in 2 hours - skipping
2021-01-29T17:13:05.907Z - info: [ui] launching: 2.6.2 (Windows 10.0.18363)
2021-01-29T17:13:05.907Z - info: [ui] execPath: 'C:\Users\Adrian\AppData\Local\GitHubDesktop\app-2.6.2\GitHubDesktop.exe'
2021-01-29T17:13:10.863Z - error: [ui] `git commit -F -` exited with an unexpected code: 1.
2021-01-29T17:13:10.863Z - info: [ui] [Timing] Action 'create commit' for 'blue-matter/MSEtool' took 0.223s

**Comment by steveward** [comment]
Thanks for the report @AdrianHordyk. Since this is only happening with one repository it seems like an isolated issue. Are all of your repositories in the same root directory?

**Comment by AdrianHordyk** [comment]
@steveward - yes all repositories are in same directory and nothing has changed with directory structure. Agree that this is an isolated issue, but seems related to Desktop as it works without error in terminal.

**Comment by AdrianHordyk** [comment]
Fixed the issue by deleting local repo and cloning again (back to same root directory) from GitHub master.

Closing issue but still seems an unresolved problem somewhere.

**Comment by phaselden** [comment]
FWIW - I am experiencing this issue ATM, so it hasn't gone away.

**Comment by icbd** [comment]
```
`git commit -F -` exited with an unexpected code: 1.
stderr:
[36mLefthook v1.2.2[0m
[36mRUNNING HOOK:[0m [1mpre-commit[0m
[31m
  EXECUTE >[0m [1msecrets-detection[0m
Error: unknown flag: --no-banner
Usage:
  gitleaks protect [flags]

Flags:
  -h, --help     help for protect
      --staged   detect secrets in a --staged state

Global Flags:
  -c, --config string          config file path
                               order of precedence:
                               1. --config/-c
                               2. env var GITLEAKS_CONFIG
                               3. (--source/-s)/.gitleaks.toml
                               If none of the three options are used, then gitleaks will use the default config
      --exit-code int          exit code when leaks have been encountered (default 1)
  -l, --log-level string       log level (trace, debug, info, warn, error, fatal) (default "info")
      --redact                 redact secrets from logs and stdout
  -f, --report-format string   output format (json, csv, sarif) (default "json")
  -r, --report-path string     report file
  -s, --source string          path to source (default: $PWD) (default ".")
  -v, --verbose                show verbose output from scan


[36m
SUMMARY: (done in 0.04 seconds)[0m
🥊  [31msecrets-detection[0m[31m[0m
```
