### ISSUE TITLE
After installing GitHub desktop, my Credentials don't work properly anymore.

### ISSUE THREAD

**Issue by justin-jalandoni** [desktop/desktop#11485]
Download GitHub Desktop and login (Credentials A). 

Clone any repository (Repository X)

Delete the credentials from Credential Manager.

Uninstall Github Desktop

Try to clone/push Repository X using different credentials (Credentials B)

Check user.name. This will still be Credentials A

**Comment by steveward** [comment]
@zxa4fd it sounds like you are referring to the name and email stored in your .gitconfig file. Those values are used for commit attribution, and not for authentication. When you log in with a different account it does not automatically change the name and email address -- you will need to do this by going to `File` > `Options` > `Git`.

In the future we'd like to automatically detect when your email doesn't match the currently logged in GitHub account. You can follow along in https://github.com/desktop/desktop/issues/610 for updates about this.

I'm going to close this out, but let me know if I'm misunderstanding the issue.

**Comment by justin-jalandoni** [comment]
Thanks!
