### ISSUE TITLE
Unable to commit changes to branch

### ISSUE THREAD

**Issue by kellyph234** [desktop/desktop#11499]
I'm trying to commit changes I made in Atom through my GitHub Desktop. When  I do I continuously receive this error with the screenshot attached. It appears it's an issue with my login credentials but I am logged in on both GitHub desktop and my browser as well.
<img width="561" alt="Screen Shot 2021-01-29 at 5 42 31 PM" src="https://user-images.githubusercontent.com/77938628/106397100-98998280-63c0-11eb-9fb6-2b5ca27d12ea.png">

2.6.2 Version & OS

macOS Big Sur 11.1

Steps to reproduce the behavior

1. Go to GitHub desktop
2. Click on changes needed to commit
3. Scroll down to enter commit description and enter commit to main
4. See error message pop up 

I need this issue resolved so I can commit my changes to main and move through this project. I have not had issues with this error the previous two times I used GitHub desktop to make changes so I'm unsure where the problem lies.

**Comment by steveward** [comment]
@kellyph234 it looks like your name and email may not be properly set in your .gitconfig file. Here's how to fix this:

1. Open GitHub Desktop and go to `GitHub Desktop` > `Preferences` > `Git`
2. Enter your name and email -- make sure the email address matches an email address associated with your currently logged in GitHub account

That should get things working. Let me know if you have any further issues.
