### ISSUE TITLE
how do I set up or install a ungoogled chromium browser?

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#11494]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by billygriffin** [comment]
Sorry @Blubber3710, this is the repository for the GitHub Desktop app so we're only able to answer questions about the product specifically. Best of luck.
