### ISSUE TITLE
增加合并commit功能

### ISSUE THREAD

**Issue by Jick-study** [desktop/desktop#11500]
什么时候可以支持git rebase 命令呢？
有时确实需要将某分支的多次提交合并为一次提交然后与主分支合并，这样可以很好的让主分支提交记录保持干净整洁。

**Comment by steveward** [comment]
@fy287216637 thanks for the issue. You can rebase in GitHub Desktop by going to the menu in GitHub Desktop and selecting `Branch` > `Rebase Current Branch`. I hope that helps!
