### ISSUE TITLE
Change app icon to macOS Big Sur style

### ISSUE THREAD

**Issue by ExEr7um** [desktop/desktop#11507]
### Describe the feature or problem you’d like to solve

In macOS Big Sur Apple has revealed new app icons guidelines. But GitHub Desktop app uses old guidelines.
<img width="1508" alt="Снимок экрана 2021-02-01 в 15 55 58" src="https://user-images.githubusercontent.com/35431350/106461913-7843f380-64a6-11eb-9126-0a77575c2e5e.png">

### Proposed solution

Make a new icon or use one of community made like this one made by [Stijn](https://stijndv.com/).
<img width="1508" alt="Снимок экрана 2021-02-01 в 15 58 11" src="https://user-images.githubusercontent.com/35431350/106462132-bb05cb80-64a6-11eb-86f5-565934f155fe.png">

### Additional context

You can download Stijn icon [here](https://stijndv.com/goodies/big-sur-replacement-icons/download/Github.icns).

**Comment by sergiou87** [comment]
Thank you for your suggestion @ExEr7um !!

We already have a Big Sur icon (see #11388), and it will be available in the next beta release 😄
