### ISSUE TITLE
Unable to clone a repository with the url

### ISSUE THREAD

**Issue by shane-ondriezek-ie** [desktop/desktop#11509]
### Describe the bug

I am unable to clone a repository using the URL. I consistently get the "Authentication Failed" popup.

### Version & OS

GitHub Desktop version: 2.6.2
OS: windows 10

### Steps to reproduce the behavior

click File => clone repository => URL
Enter the URL, select a local path, and click Clone

### Expected behavior

The repo gets cloned

### Actual behavior

Authentication Failed popup appears:

### Screenshots

![image](https://user-images.githubusercontent.com/77021849/106491370-cba54a00-6484-11eb-8c9f-e66a90337cf0.png)

### Logs

[2021-02-01.desktop.production.log](https://github.com/desktop/desktop/files/5905390/2021-02-01.desktop.production.log)

### Additional context

I am signed in. 
I have tried:
- signing out and signing in again
- uninstalling and reinstalling github desktop
- removing the all windows credentials for github and signing into github desktop
- creating a blank local repo and cloning into it

**Comment by steveward** [comment]
@shane-ondriezek-ie thanks for the issue. Can you share some more details about site you are trying to clone this repository from? Is this a specific third-party Git hosting service?

**Comment by shane-ondriezek-ie** [comment]
@steveward I was able to get this to work finally. Not sure what actually fixed it, but I tried using my TFS login info in the Authentication Failed popup and it mysteriously worked this time. Thanks though.

**Comment by steveward** [comment]
Glad to hear things are working now!
