### ISSUE TITLE
Have the option to resize the Current Branch dropdown's width

### ISSUE THREAD

**Issue by fabtjar** [desktop/desktop#11503]
I have to click the dropdown to see the full name of the current branch.

I should be able to change the width of it. There's a lot of unused space on the top bar so it seems like there wouldn't be an issue with this change.

![image](https://user-images.githubusercontent.com/42767280/106434218-25981680-6469-11eb-85e6-ee0efa487585.png)

**Comment by tidy-dev** [comment]
Thanks for the feedback @fabtjar  We are tracking this issue in #4569, so I am going to close this out. Thanks for using GitHub Desktop!
