### ISSUE TITLE
version of github are not covered in the lesson plan i am using a free version

### ISSUE THREAD

**Issue by familyhope41** [desktop/desktop#11504]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
👋🏻 @familyhope41 -- this issue tracker is for GitHub Desktop. It sounds like you may be having an issue with your GitHub account. I'd recommend reaching out to [GitHub Support](https://support.github.com/).

I'm going to close this out, but let me know if you are having any specific issues with GitHub Desktop.

**Comment by familyhope41** [comment]
What does that mean


Sent from Mail for Windows 10
