### ISSUE TITLE
Git credentials not found when trying to update from master in LFS repository

### ISSUE THREAD

**Issue by Peaj** [desktop/desktop#11513]
### Describe the bug

Git credentials not found when trying to update from master in LFS repository.

### Version & OS

Version 2.6.2
Windows 10

### Steps to reproduce the behavior

Just use 'Update from Master'

Sometimes it works but the error occured multiple times on different machines.
Unsure if it is related to which content has been changed.
Seems to be connected to LFS

### Expected behavior

Update the current branch with changes from Master

### Actual behavior

Error message (redacted):

Error downloading object: Assets/.../file.fbx (ba5ab45): Smudge error: Error downloading Assets/.../file.fbx (ba5ab45270c66715464ad3a7bb2b0bbf1676ad7d1a0754bafabb6517026fe084): batch response: Git credentials for https://github.com/user/repo.git not found.

Leaves uncommited changes from master in the working directory after showing the error message.

Git credentials for https://github.com/user/repo.git not found.

### Logs

[2021-02-02.desktop.production.redacted.log](https://github.com/desktop/desktop/files/5910229/2021-02-02.desktop.production.redacted.log)
[20210202T103654.9797022-redacted.log](https://github.com/desktop/desktop/files/5910263/20210202T103654.9797022-redacted.log)

### Additional info
This is the only case where credentials seem to be missing.
Every other function (Commit/Push/Pull/Rebase from Master) just works as expected.

**Comment by steveward** [comment]
Thanks for reporting this @Peaj. Do Git operations succeed in this LFS repository from the command line? It'd be helpful to see if you are able to reproduce this error there as well so we can determine if this a specific issue with GitHub Desktop or with your repository.

**Comment by Peaj** [comment]
I did not try to resolve it via command line yet.
As the operation left the working copy with uncommited changes which I could not distinguish from the existing changes we abondoned the branch.
The next time I encounter the error I will try to resolve it via command line.
Is it possible to see the exact sequence of git commands used by the client when updating from master?

**Comment by steveward** [comment]
Consolidating this into https://github.com/desktop/desktop/issues/11575.
