### ISSUE TITLE
Remote branches names get changed

### ISSUE THREAD

**Issue by phillip-mediablanket** [desktop/desktop#11514]
### Describe the bug

When changing to a branch like origin/feature/foobar it loads the branch as expected but if you change to another branch and then back the branch now shows up as Feature/foobar. The capital F now prevents you from pushing to the remote as a branch with that name already exists. 

### Version & OS

version 2.6.2
osx 10.15.7

### Steps to reproduce the behavior

1. create branch feature/foo using cmd or through a browser
2. checkout feature/foo
3. checkout master
4. checkout Feature/foo
5. you now wont be able to push any changes to this branch

**Comment by steveward** [comment]
Thanks for the report @phillip-mediablanket. I was unable to reproduce this directly.

Can you share the output of `git branch -a` from the command line?

**Comment by phillip-mediablanket** [comment]
Im not sure if it makes a difference but these are hosted on bitbucket

$ git branch -a
Feature/billing
dev
master
remotes/origin/feature/billing
remotes/origin/dev
remotes/origin/master

**Comment by phillip-mediablanket** [comment]
doesn't seems to be happening anymore not sure what updated to fix this
