### ISSUE TITLE
LFS Push error: failed to push some refs

### ISSUE THREAD

**Issue by zarlin** [desktop/desktop#11522]
### Describe the bug

I have a git repository with LFS initialized. I have a commit with LFS content. When trying to push to a bitbucket repository, I get the error message:

> batch request: exec: "": executable file not found in %PATH%
error: failed to push some refs to *repository url redacted*

The developer log has a bit more info:

> `git -c credential.helper= push origin master:master --progress` exited with an unexpected code: 1.
stdout:
Uploading LFS objects:   0% (0/8), 0 B | 0 B/s, done.

> stderr:
batch request: exec: "": executable file not found in %PATH%
error: failed to push some refs to *repository url redacted*

From the git command it seems like it tries to use a credential helper, even though I'm using SSH keys for authentication, which works fine when pulling/fetching. The problem only seems to occur with LFS content.

### Version & OS

GitHub Desktop Version 2.6.2
Windows 10 Pro build 2004

### Steps to reproduce the behavior

This probably isn't reproducable, but here are my steps:

1. Commit files which are tracked under LFS
2. Attempt to push files to git remote

### Expected behavior

The LFS files are pushed/uploaded without error OR I get a descriptive error which helps me to solve whatever is wrong.

### Actual behavior

I get an error (see description) and the commit is not pushed.

**Comment by steveward** [comment]
Thanks for the report @zarlin. Does performing a git push from the command line throw the same error?

I'd be curious if HTTPS would succeed. If you're interested in giving that a try you can follow [this guide](https://github.com/desktop/desktop/blob/development/docs/integrations/bitbucket.md) for steps about setting up GitHub Desktop to use HTTPS. GitHub Desktop doesn't have great SSH key support so we recommend HTTPS whenever possible.

**Comment by zarlin** [comment]
Thanks for your reply @steveward. A git push from the command line gives the same error, however after setting up the repo using HTTPS instead of SSH, the push command did succeed, so my problem is solved!

Will GitHub Desktop get better SSH support in the future?

**Comment by steveward** [comment]
@zarlin i'm glad to hear that got things working. We're tracking SSH improvements in https://github.com/desktop/desktop/issues/2579 if you would like to follow along.
