### ISSUE TITLE
local branch can't track or checkout remote branch with same name

### ISSUE THREAD

**Issue by YueZeng0304** [desktop/desktop#11539]
When I'm already in the master branch, and it should up to date with 'origin/master', but desktop will show my local branch is not published. If I try to checkout to 'origin/master', it will say can't checkout because I have local branch with the same name.
I also tried --set-upstream-to and --track, then it will show two branch head/origin/master and remotes/origin/master. Still it shows branch not published and can't checkout to remotes/origin/master

What I can do, is checkout to other branch, delete the local master branch, then checkout to origin/master

This always happens when I add exsiting repo in master branch, in other branch it doesn't happen

**Comment by steveward** [comment]
Thanks for the report @YueZeng0304. This issue is being tracked in https://github.com/desktop/desktop/issues/4527. You can follow along there for updates about this.
