### ISSUE TITLE
Parameter `f` is incorrect

### ISSUE THREAD

**Issue by iqtedar123** [desktop/desktop#11537]
### Describe the bug
On windows, I am unable to commit changes to an enterprise repository due to the following error:

### Version & OS
2.6.2
Windows 10

### Steps to reproduce the behavior
1. Make a file change
2. Try commiting the change

### Expected behavior

Commit is successful.

### Actual behavior

Commit fails.

### Screenshots

![image](https://user-images.githubusercontent.com/12553327/107052062-3616fc80-679b-11eb-9b41-46b3439900b8.png)

### Logs
```
2021-02-05T14:49:28.807Z - error: [ui] `git commit -F -` exited with an unexpected code: 1.
stderr:
T h e   p a r a m e t e r   i s   i n c o r r e c t . 
 
 
 
2021-02-05T14:49:28.808Z - info: [ui] [Timing] Action 'create commit' for 'online-web/diesel-src' took 1.952s
2021-02-05T14:49:37.744Z - error: [ui] `git commit -F -` exited with an unexpected code: 1.
stderr:
T h e   p a r a m e t e r   i s   i n c o r r e c t . 

```

**Comment by sergiou87** [comment]
Hello @iqtedar123! 👋 

I'm sorry about this issue 😢 I just tested it and works as expected here. The command run by the app is as simple as `git commit -F -` as you can see in the logs. This is the code that invokes it: https://github.com/desktop/desktop/blob/development/app/src/lib/git/commit.ts/#L26-L33

From what I see, I think it's more probable that either the repository path or the message caused the issue 🤔 

1. Does the full path to the repository have anything special? Some character, or maybe it's a super long path…
2. Does the commit message have anything special? Again: some character, maybe it's a super long message…

Thanks in advance for your help!

**Comment by iqtedar123** [comment]
> Hello @iqtedar123! 👋
> 
> I'm sorry about this issue 😢 I just tested it and works as expected here. The command run by the app is as simple as `git commit -F -` as you can see in the logs. This is the code that invokes it: https://github.com/desktop/desktop/blob/development/app/src/lib/git/commit.ts/#L26-L33
> 
> From what I see, I think it's more probable that either the repository path or the message caused the issue 🤔
> 
> 1. Does the full path to the repository have anything special? Some character, or maybe it's a super long path…
> 2. Does the commit message have anything special? Again: some character, maybe it's a super long message…
> 
> Thanks in advance for your help!

Nope. Simple path: `D:\git\Work\repo-1`
Commit message was `remove console log`.

**Comment by steveward** [comment]
@iqtedar123 does this error occur in all of your repositories, or only one specific repository?

**Comment by steveward** [comment]
@iqtedar123 since we have not heard back from you I am going to close this issue out. Let me know if you're able to reproduce this issue across multiple repositories and we can look into this further.

**Comment by wadewomersley** [comment]
I get this too:
` C:\Users\wade8\AppData\Local\GitHubDesktop\app-2.6.3\resources\app\git\cmd\git.exe commit -F -`
gives:
`  h e   p a r a m e t e r   i s   i n c o r r e c t .`
Only happens in one repo.

If I run my standard git  install it works fine:
`& 'C:\Program Files\Git\cmd\git.exe' commit -F -`
`(reading log message from standard input)`
