### ISSUE TITLE
Default branch renaming does not update branch options' availability on previously checked out default branch

### ISSUE THREAD

**Issue by Rekkonnect** [desktop/desktop#11530]
### Bug description

Renaming the default branch on GitHub while being locally checked out on it will enable some branch options unless another branch or repo is selected.

### Version & OS

GitHub Desktop: 2.6.2
OS: Windows 10

### Steps to reproduce

1. Open the desired repository locally on GitHub Desktop and check out on the default branch (usually `master` or `default`).
2. Open the same repository on the GitHub website, and go to settings.
3. Rename the default repository to something else.
4. Fetch the changes on GitHub Desktop.
5. Open the Branch menu item while being checked out on the previous default branch (before the rename).
6. Observe the options "Rename" and "Delete".

### Expected behavior

The options "Rename" and "Delete" should be available on the branch, since it is no longer the default branch.

### Actual behavior

These options are still disabled. They will be re-enabled after switching to another repo or branch, and then back to that branch.

**Comment by helleenam32** [comment]
hello learning what this web site loads up and offf it self any hints whome to trust

**Comment by steveward** [comment]
I was no longer able to reproduce this issue. After performing a fetch the new renamed default branch was fetched and the previous local branch was left with the ability to rename or delete. Closing out as resolved.
