### ISSUE TITLE
Add link for running external diff to binary file diff view.

### ISSUE THREAD

**Issue by sfadschm** [desktop/desktop#11545]
### Describe the feature or problem you’d like to solve

When we change some "binary" files in a repository, Github Desktop is not able to build a diff of them unless we have, e.g., a working `textconv` filter configured in git. While `textconv` filters are feasible for several binary file types, there is other files that cannot be converted to a user-readable text format.

git itself allows us to use an external `command` to properly display such diffs from console, these are however intentionally diabled in Github Desktop (and for good reason, I think).

The current implementation gives the following view with a link to open the specific file in the default program configured in the users OS:

    This binary file has changed.
    Open file in external program.

### Proposed solution

I think it would be helpful to have

1. an additional message displayed here, if the `.gitconfig` originally has an external command configured for the diff view that is ignored by Dektop, e.g.:  
     ```An external command is defined for generating diff views for this file type but cannot be displayed inside Dektop.```
     ```Run 'git diff "filename.extension"' from the command line to review it externally.```
2. another link displayed here to fire the command line diff (if that is compatible with security considerations), e.g.:
    ```View diff with command line tool.```

These additions will greatly increase the usability of Desktop for diffing non-text file formats and will spare lots of time when working with repositories containing, e.g. vector images or such.

**Comment by tidy-dev** [comment]
Hi @sfadschm! Thank you for input! We have #1765  that is tracking the need for being able to open files in an external diff tool. This is a great addition to this discussion! Linking this and closing this issue in favor of tracking it there.
