### ISSUE TITLE
Popup to delete local branch that used to exist on the remote but now doesn't

### ISSUE THREAD

**Issue by DarkiBoi** [desktop/desktop#11544]
### Describe the feature or problem you’d like to solve
In the event of a remote branch deletion, it would be desirable to be informed about the local branches dangling status in the clients interface. Branches of this kind fill up the branch selection dialog very quickly and makes it uncomfortable to naviagate.

### Proposed solution
Display deletion dialogue or something of the likes, if local branch, that was previously attached to the remote, is not attached anymore.

### How will it benefit Desktop and its users?
Fixes branch selection dialog getting clogged up by unused dangling branches.

### Additional context
- N/A

**Comment by tidy-dev** [comment]
Thank you @DarkiBoi  for your suggestion!

We are currently working on a feature to allow deleting branches directly from the branch menu via a context menu on a branch. See #11434. This should alleviate the problem by make deleting unwanted branches much simpler.

Also, there already is a feature that will automatically clean up local branches associated with a remote branch that has been merged into the default branch after a 14 days.

**Comment by aazxx099** [comment]
في اثنين، ٨ فبراير، ٢٠٢١ في ٨:٤٠ م، كتب tidy-dev <notifications@github.com>:
