### ISSUE TITLE
Make commit sha selectable in the history view

### ISSUE THREAD

**Issue by donokuda** [desktop/desktop#1154]
It's pretty useful when I need to reset, cherry-pick, or revert commits.

**Comment by adamreisnz** [comment]
Can I resurrect this and ask that clicking on the displayed hash will have the same action as `Copy SHA`?

![image](https://user-images.githubusercontent.com/490562/30622008-d755bc1e-9e02-11e7-824a-2e333d8e4f95.png)

I can _see_ the commit hash, but the UI doesn't let me click it or even select the text. It would be intuitive if clicking on this hash would copy it to your clipboard.

Now we have to right click to the left on the history item instead, which is ok, but counter intuitive.

**Comment by joshaber** [comment]
Yeah this view went through a good amount of churn.

At minimum I think it's reasonable for that label to be selectable 👍

**Comment by adamreisnz** [comment]
Awesome! 🎉
