### ISSUE TITLE
error when trying to publish

### ISSUE THREAD

**Issue by JaxsonYorke** [desktop/desktop#11540]
### Describe the bug
im doing the geting started tutorial and when i try to to step 5 publishing to github it gives me an error
`git: 'remote-https' is not a git command. See 'git --help'. `
### Version & OS
version 2.6.2
windows 10
### Steps to reproduce the behavior

download the github desktop app
install
make the tutorial repository
do the steps

### Expected behavior

i expected it to publish to github

### Actual behavior

it gave me the error `git: 'remote-https' is not a git command. See 'git --help'.`

### Screenshots

[2021-02-05.desktop.production.log](https://github.com/desktop/desktop/files/5935474/2021-02-05.desktop.production.log)

### Logs

[2021-02-05.desktop.production.log](https://github.com/desktop/desktop/files/5935475/2021-02-05.desktop.production.log)

**Comment by tidy-dev** [comment]
Hi @theyobros, I am sorry you are having this issue. It looks like this is the same as #10345. Please refer to #10345 for troubleshooting. It looks like uninstalling/reinstalling gitHub desktop (see thread for specifics) and seeing if an antivirus software is interfering are your best bets, but there are some other suggestions in there.  Also, feel free to add any additional info you have to that thread.
