### ISSUE TITLE
Does not connect to VS code.

### ISSUE THREAD

**Issue by reagand01** [desktop/desktop#11548]
### Describe the bug

Does not give me the option to open my repositories in VS code. Only has Notebook++ as an option.

### Version & OS

Github Desktop Version 2.6.2
Edition	Windows 10 Home
Version	20H2
Installed on	‎1/‎16/‎2021
OS build	19042.789
Experience	Windows Feature Experience Pack 120.2212.551.0

### Steps to reproduce the behavior

1. Go to 'File'
2. Click on 'Options'
3. Scroll down to 'Integrations'

### Expected behavior

Show VScode as an option under 'External editor'

### Actual behavior

Only shows 'Notepad++' 
[2021-02-08.desktop.production.log](https://github.com/desktop/desktop/files/5948751/2021-02-08.desktop.production.log)
[2021-02-09.desktop.production.log](https://github.com/desktop/desktop/files/5948752/2021-02-09.desktop.production.log)

**Comment by steveward** [comment]
@reagand01 thanks for the report. Did you recently install VSCode? If so, you will need to restart GitHub Desktop in order for the editor to be detected by GitHub Desktop. Let me know if that isn't the issue and we can dig into this further!
