### ISSUE TITLE
Every time you do a new patch you create a new folder with a new number so my git.exe path get changed every time

### ISSUE THREAD

**Issue by alexnicola07** [desktop/desktop#11550]
Every time you update the github desktop client you update the folder name with a new number
This:
C:\Users\Alex\AppData\Local\GitHubDesktop\app-2.6.2\resources\app\git\cmd\git.exe
turns into this:
C:\Users\Alex\AppData\Local\GitHubDesktop\app-2.6.3\resources\app\git\cmd\git.exe

this is a problem because the path gets wrong in the environment variables so I can't use the command git in the cmd.
I need to manually update it every time you create a version.

**Comment by steveward** [comment]
Thanks for the issue @alexnicola07. GitHub Desktop includes an embedded version of Git, and it is not intended to be used in your PATH. I would recommend downloading [Git for Windows](https://git-scm.com/download/win). There is an option during the installation flow to add it to your PATH. I hope that helps!
