### ISSUE TITLE
Azure DevOps Repos - Authentication failed

### ISSUE THREAD

**Issue by sevket-yilmaz** [desktop/desktop#11557]
### Describe the bug

I'm constantly having a connection problem between GitHub Desktop and Azure DevOps repository. I have GitHub repositories and also Azure DevOps repositories. There is no problem when I working with GitHub repositories, but when I want to do something (pull,push..) in Azure DevOps repo I see "Authentication failed" window. No problem with the first pull, but **after a while** I see "Authentication failed" window.

### Version & OS

My GitHub Desktop (Windows) version is 2.6.3

### Steps to reproduce the behavior

1. I connect my GitHub repositories with my GitHub account.
2. I connect my Azure DevOps repositories with PAT(Azure DevOps - Personal Access Tokens)
3. I can pull Azure DevOps repository to my machine.
-->and after a while (ex: 20 minutes)
4. I see the "Authentication failed" window when I try to do something(pull/push).
5. I input my username and password again and we come back to step "3".

### Expected behavior

I shouldn't need to enter password again.

### Actual behavior

My username and password are correct, and I can use the repo with this credential but after a while.. something is gone.. 

### Screenshots

![Screenshot_8](https://user-images.githubusercontent.com/10208986/107506271-e8413080-6bae-11eb-8a0e-6c4a0c1a4133.png)
![Screenshot_6](https://user-images.githubusercontent.com/10208986/107506305-f3945c00-6bae-11eb-8b2d-8dcacc5e5176.png)

### Logs

![Screenshot_7](https://user-images.githubusercontent.com/10208986/107506516-39e9bb00-6baf-11eb-9d46-e3271fcc1b20.png)

### Additional context

Note: My PAT token is new(so expire date is long..) and the status is active.

**Comment by tidy-dev** [comment]
Thanks for the report @sevket-yilmaz. This looks similar to what was reported in #9579 and #10078. Have you tried generating a new token to see if that resolves the issue?

It may also be helpful to check in the Credential Manager -> Windows Credentials to see what is being stored under dev.azure.com. This users in #9579 appears to have success by remove the credentials there and re-authenticating.

**Comment by sevket-yilmaz** [comment]
I understand, this related to windows credentials. GitHub desktop can generate new credential but cannot use correct credential. I removed the all dev.azure.com credentials from Windows Credential Manager and entered again my username and password, I waited for a while, I see that the problem has been resolved.

Thanks for your help @tidy-dev
