### ISSUE TITLE
delete tags

### ISSUE THREAD

**Issue by epaulperimeter** [desktop/desktop#11552]
### Describe the feature or problem you’d like to solve
Delete Tag option was not working in the History Tab.

### Proposed solution
Add an option to force delete the tag

### Additional context
Currently delete tag is not working for a pushed tag.is this a feature? can we include force options in the app?

**Comment by epaulperimeter** [comment]
Option to delete a Tag

**Comment by billygriffin** [comment]
Hi @epaulperimeter, we require the template to be filled out so we can better understand what it is folks are asking for and how it might be beneficial to them. As you can imagine, we get many feature requests regularly, and this helps us be able to prioritize our time and attention on things that have more information for us to understand the problem people are running into.

**Comment by aazxx099** [comment]
في ثلاثاء، ٩ فبراير، ٢٠٢١ في ٦:٤٧ م، كتب Billy Griffin <
notifications@github.com>:

**Comment by ahmedhory** [comment]
Good

**Comment by dwirahayu256** [comment]
> Option to delete a Tag



> ### Describe the feature or problem you’d like to solve
> Delete Tag option was not working in the History Tab.
> 
> A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.
> 
> ### Proposed solution
> Add an option to force delete the tag
> 
> How will it benefit Desktop and its users?
> Remove unwanted Tags
> 
> ### Additional context
> Add any other context like screenshots or mockups are helpful, if applicable.

> 

>

**Comment by dwirahayu256** [comment]
oke

**Comment by epaulperimeter** [comment]
i have answered the questions

**Comment by steveward** [comment]
Thanks for updating the issue @epaulperimeter. GitHub Desktop does not support deleting tags that have been pushed to the remote -- see [this comment](https://github.com/desktop/desktop/issues/9938#issuecomment-638779503) for the reasoning behind that. I'm going to close this issue out -- thanks for using GitHub Desktop.
