### ISSUE TITLE
Identity bug - Incorrect user name for commits

### ISSUE THREAD

**Issue by M-casado** [desktop/desktop#11567]
### Describe the bug

The username that performs a commit displayed in the webpage is erroneous. Commits pushed by my main account are shown to be pushed by my alternative account (with not even privileges to do so). 

### Version & OS

* GitHub Desktop version: Version 2.6.3

OS details:
* Edition: Windows 10 Pro
* Version: 20H2
* Sub-version: 19042.746 

### Steps to reproduce the behavior

1. Change a GH repository.
2. Commit changes through GitHub Desktop
3. Check committer in the webpage

### Expected behavior

The username of the committer should be the correct one (the one you logged with in GH Desktop)

### Actual behavior

Alternative account's name is displated for commits in the webpage.

### Screenshots

![Image 1](https://github.zendesk.com/attachments/token/NssKyT1EA3fQtZnUEMAuQitZK/?name=image.png)

![Image 2](https://github.zendesk.com/attachments/token/RWgVjjJbMxeb69D3yCXjPjKz7/?name=image.png)

![Image 3](https://github.zendesk.com/attachments/token/SvRzXtajRatTsPPj2y4Fuwo4K/?name=image.png)

### Additional context

Hello, I have noticed a bug in the GitHub webpage related to the identity of a commiter within sub-branches (and sometimes in master branches) of a project. My working GitHub account is **M-casado**, and I commited a few times over different projects of the [EbiEga GH repository](https://github.com/EbiEga). The thing is I just noticed that my commits sometimes appear as **Marcos-CB** (see _image 1_), which is the username of an alternative account I had in the past (and in which I am not logged in). 

This account does not have edit privileges, nor can access most of the EbiEga repositories, so it does not make sense that I can commit to it. When I click on the commit history report (e.g. https://github.com/EbiEga/ega-metadata-schema/commits?author=Marcos-CB) it shows that I commited all of the changes through **Marcos-CB**, although the correct account I used is **M-casado**. Furthermore, the profile of the alternative accoutn shows no commits whatsoever for 2021. 

I believe it may be related to GitHub desktop, since I recently started committing through the application instead of the webpage. But even so, when I check the logged account of GitHub Desktop, the only one that appears is the main account (M-casado), and not the alternative (see _image 3_).

**Comment by steveward** [comment]
Thanks for the issue @M-casado. Misconfigured commit attribution does not mean that someone can access your account. GitHub uses the email address in your .gitconfig to associate the commits with your account.  You can check the name and email address that are being used in your .gitconfig by going to `File` > `Options` > `Git`. Make sure the email address being used there matches an email address that is associated with your currently logged in GitHub account ([check here to see your saved email addresses](https://github.com/settings/emails)). 

You can read more about how commit attribution works here:

https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user

**Comment by billygriffin** [comment]
Hi @M-casado, in addition to what @steveward shared, we're actively working on a feature that will hopefully improve this by displaying if your git config is different from the emails listed for your GitHub account. So hopefully when that's released, this won't be an issue for you or others going forward. ❤️
