### ISSUE TITLE
Search In history

### ISSUE THREAD

**Issue by MiddleTommy** [desktop/desktop#11568]
Frequently I would like to search my git repository history. I would like to search for file names and also search for code being able to filter between the two. This would be very useful to find past files and their changes when you are hunting down what changed. A history view of just one file would also be welcome.

**Comment by steveward** [comment]
Thanks for the feedback @MiddleTommy. This is being tracked in https://github.com/desktop/desktop/issues/7022, so I am going to close this issue out. Feel free to add a 👍🏻 to that issue top indicate it's something you would like to see in GitHub Desktop.
