### ISSUE TITLE
Can NOT view changes anymore on History tab selecting a specific file

### ISSUE THREAD

**Issue by kwhjvdkamp** [desktop/desktop#11569]
### Describe the bug
Since a few days I can NOT view changes anymore after commits. Only a message is presented: file binary changed, open in a remote tool. Clicking on this link for instance a typescript file, this file is opened as a video file which can't be handled.

### Version & OS
Latest version of Github for Desktop 2.6.3, latest version of Visual Code, OS Windows (latest)

### Steps to reproduce the behavior
A new repo added does not have this problem. On all repos on which I do a lot of maintenance, I notice this problem. Also on different machines (my desktop and lt). Somehow I got the feeling it has something to do max of something. Cannot find any doc's on what to do to solve

### Actual behavior
See screenshot

### Screenshots
![Problem_GitHub_Desktop](https://user-images.githubusercontent.com/9660415/107714105-f4231480-6ccc-11eb-98c9-e5791b9724e4.png)

**Comment by kwhjvdkamp** [comment]
I think it is not really a bug, I guess I do miss some specific knowledge

**Comment by steveward** [comment]
@kwhjvdkamp I responded to your question github.community, so I am going to close this issue out. Please feel free to respond there if you are still having issues.
