### ISSUE TITLE
add more than one GHE account

### ISSUE THREAD

**Issue by ChristophHoyer** [desktop/desktop#11565]
### Describe the feature or problem you’d like to solve

Having a productive and a testing instance of our GitHub Enterprise Server, I can't connect to both with GitHub Desktop. After establishing one connection, there's no more "Add Account" button.

### Proposed solution

I'd like to connect via GitHub Desktop to both available GHE instances. Maybe even with two connections to one GHE instance (one as owner, one as member of a test environment).

### Additional context

-

**Comment by steveward** [comment]
Thanks for the request @ChristophHoyer. Please feel free to leave a 👍🏻 in https://github.com/desktop/desktop/issues/3707 -- that's where we are tracking feedback for this feature. I'm going to close this issue out since it is a duplicate.
