### ISSUE TITLE
When creating a new project C# is not in the list as a project type

### ISSUE THREAD

**Issue by Makuna** [desktop/desktop#11579]
### Describe the feature or problem you’d like to solve

Adding a C# project, it requires extensive rework of the ignore file after the creation and includes lots of noise from binary files already present.

### Proposed solution

Add a template for a C#, as a C or C++ project won't work.

**Comment by Makuna** [comment]
If the user selects "Visual Studio" then they will get what they want.  This is not obvious.

**Comment by sergiou87** [comment]
Hi @Makuna! 👋 

Thank you for your feedback, I'm sorry that was confusing 😖 

Right now, GitHub Desktop is grabbing those templates (and their names) from the https://github.com/github/gitignore repository. More specifically grabbing the name of the file. In this case, that would be https://github.com/github/gitignore/blob/master/VisualStudio.gitignore

If you believe that template should be named differently (or that we need a specific template for C#), I'd recommend you to [contribute in that repo](https://github.com/github/gitignore#contributing-workflow).

Thank you again!
