### ISSUE TITLE
Clicking "View on GitHub" on a forked repository opens the original repo instead of the fork

### ISSUE THREAD

**Issue by ImRodry** [desktop/desktop#11574]
### Describe the bug

When you click the "View on GitHub" button on GitHub Desktop on a fork it opens the original repository instead of your fork, making it harder to pull request

### Version & OS

Version 2.6.3 and Windows 10 version 20H2 (OS build 19042.746)

### Steps to reproduce the behavior

1. Clone a forked repository
2. On the main page of the repo, click "View on GitHub"
3. Observe the repository you were put in (should be the main one and not the fork)

### Expected behavior

The button opens the repository that is open (the fork)

### Actual behavior

The original repository is opened

### Screenshots

N/A

### Logs

N/A (I think)

**Comment by billygriffin** [comment]
Thanks for the issue @ImRodry! It's likely that your fork preference for the repo is selected that you're using the fork to contribute to the upstream repo, which has the behavior you're reporting as expected. In Repository > Repository settings, you're able to switch this, however, and that will allow you to use the forked repo more in isolation.

<img width="594" alt="Screen Shot 2021-02-12 at 10 28 56 PM" src="https://user-images.githubusercontent.com/5091167/107842616-f5fadf80-6d81-11eb-8406-9ba68b7747b9.png">

**Comment by ImRodry** [comment]
> Thanks for the issue @ImRodry! It's likely that your fork preference for the repo is selected that you're using the fork to contribute to the upstream repo, which has the behavior you're reporting as expected. In Repository > Repository settings, you're able to switch this, however, and that will allow you to use the forked repo more in isolation.
> 
> <img alt="Screen Shot 2021-02-12 at 10 28 56 PM" width="594" src="https://user-images.githubusercontent.com/5091167/107842616-f5fadf80-6d81-11eb-8406-9ba68b7747b9.png">

Hey! I do in fact have that option selected but I believe this should still be considered a bug because since there is no button to create a pull request, viewing it on github and then clicking pull request would be the only option. With the current behaviour we have to open it and then change the repository owner in the url to go to our fork which is not ideal and much less practical. That’s why I submitted this issue

**Comment by billygriffin** [comment]
Hi @ImRodry, so you're using PRs to contribute to upstream, but you still want "View on GitHub" to view your fork instead of the upstream repo? I may be confused as to what you're trying to achieve and what state you're in. Would you mind sharing some screenshots and explaining a bit more to help us understand. The current paradigm has worked really well for folks so we're hesitant to change it, but maybe there's something we overlooked in terms of expectations. Thanks.

**Comment by ImRodry** [comment]
> Hi @ImRodry, so you're using PRs to contribute to upstream, but you still want "View on GitHub" to view your fork instead of the upstream repo? I may be confused as to what you're trying to achieve and what state you're in. Would you mind sharing some screenshots and explaining a bit more to help us understand. The current paradigm has worked really well for folks so we're hesitant to change it, but maybe there's something we overlooked in terms of expectations. Thanks.

Hey! I’ll try by best to explain this better. So when you have a fork and you want to make a pull request out of it, visiting your fork shows you a button that automatically starts the pull request process whereas in the upstream repo there is no such button and you have to navigate to the pull requests tab and then select your fork. Here’s a screenshot of what I mean: 
![9686667F-5F8D-4DC1-AAB0-9E29B381F778](https://user-images.githubusercontent.com/38259440/108031203-59a63680-7028-11eb-8acf-d6f66d5c40c7.jpeg)

Hope this makes it easier to understand!

**Comment by billygriffin** [comment]
Hi @ImRodry, thanks! That's helpful. Is there a reason why the "Create PR" action in Desktop doesn't work for your needs instead? It would save you the step of having to go to the repo page and then create the PR, and instead just go to the create PR page directly.

**Comment by ImRodry** [comment]
Where is that button? I usually only see that on branches that are different from master/main and never on forks

**Comment by billygriffin** [comment]
When you've pushed your commits, you should see this come up in the UI. Also, there's a "Create pull request" menu item and keyboard shortcut in the Branch menu.

<img width="978" alt="Screen Shot 2021-02-16 at 4 39 25 PM" src="https://user-images.githubusercontent.com/5091167/108135548-892f6000-7075-11eb-964d-85b1dbcfa259.png">

**Comment by ImRodry** [comment]
Well then that must be a bug because if you have a fork and you're committing to its master branch the Create a pull request button does not show up, it only does if it's a different branch on the same repo (forks don't work). Going into the branch menu, however, does show that button but I'd appreciate it if that big blue button would appear on forks too as it seems like that's unintended behavior.
