### ISSUE TITLE
GitHub Desktop cant login

### ISSUE THREAD

**Issue by bwlok** [desktop/desktop#11584]
hello if I want login with my Github acc in Github Desktop it is loading on sign in using your browser but nothing happen  and I can only cancel it.
![Unbenannt](https://user-images.githubusercontent.com/65543013/107887428-52870780-6f06-11eb-9c41-af94d1485b9e.PNG)

**Comment by sergiou87** [comment]
Hi @bwlok!! Could you provide more info about your problem, [filling the template](https://github.com/desktop/desktop/issues/new?assignees=&labels=&template=bug_report.md&title=)?

Other than that, I think in the past other users with the same problem fixed it by changing their default internet browser.

Please, give that a try and let me know if it works!

**Comment by bwlok** [comment]
Thanks Bit it is already solved

Sergio Padrino <notifications@github.com> schrieb am Mo. 15. Feb. 2021 um
11:50:
