### ISSUE TITLE
Mass select/deselect items

### ISSUE THREAD

**Issue by Ali-00-Ridha** [desktop/desktop#11581]
### Describe the feature or problem you’d like to solve

mass deselect/select  items from right click menu, see image below:

### Proposed solution

cut time selecting/deselecting items one by one.

### Additional context

![New Bitmap Image](https://user-images.githubusercontent.com/40155463/107865694-4e150d00-6e7a-11eb-952c-8ee9697de347.jpg)

**Comment by sergiou87** [comment]
Hi @Ali-00-Ridha!! 👋 

Thank you for your suggestion 😄  Without the context menu, you can already select a bunch of files and then press Space in your keyboard to select/deselect those files.

I hope that helps!

**Comment by Ali-00-Ridha** [comment]
Thank you for your response, no need to implement this feature since there is such a shortcut, I will close this issue.
Now i'm reading shortcuts document for other usefull tricks/shortcuts,

Thank u.
