### ISSUE TITLE
Ability to change spell check language

### ISSUE THREAD

**Issue by kurtextrem** [desktop/desktop#11589]
### Describe the feature or problem you’d like to solve

Currently, the spell-checker seems to use the OS language to set the spellcheck language... but I do use English in my commits, instead of German, which kind of makes the spell-checker useless in my case.

### Proposed solution

A new option (File -> Options) to change the spell-checker language.

**Comment by HyagoOliveira** [comment]
This feature would help a lot. Most developers use English when creating commits.

**Comment by myz-dev** [comment]
I agree

**Comment by AaronPedersen-QUT** [comment]
I have my OS language set to "English (Australia)", but Github Desktop is still giving me spell-checking for American English, and it's really annoying not being able to change it.
