### ISSUE TITLE
linux?

### ISSUE THREAD

**Issue by 343GuiltySpark-04** [desktop/desktop#11580]
### Describe the feature or problem you’d like to solve

Well no real detailed way to say it but Linux support would be terrific

### Proposed solution

Easier access for Linux users

**Comment by sergiou87** [comment]
Hi @343GuiltySpark-04 👋  Thanks for reaching out! This request already exists in #1525, so I'm going to close this one in favor of that. Please subscribe to it to stay up to date with any development happening in that area.

I guess you already know, but there is an unofficial fork of GitHub Desktop available for Linux: https://github.com/shiftkey/desktop. Hope that helps!

**Comment by 343GuiltySpark-04** [comment]
Thanks I'll be sure to check it out
