### ISSUE TITLE
Clicking the icon in the task bar maximises the window on macOS

### ISSUE THREAD

**Issue by fabtjar** [desktop/desktop#11590]
When clicking the GitHub Desktop icon in the task bar the window expands the the max size filling the screen. Clicking on the icon should show the window, not expand it.

I'm using macOS Bug Sur version 11.2.

**Comment by sergiou87** [comment]
Ouch! Thanks for reporting this bug @fabtjar 😐 

It just happens that I always use GH Desktop using my whole screen, and for some reason this bug doesn't happen in development builds (which I have using only half of my screen).

We'll dig into this and fix it as soon as possible, as we understand how annoying this is.

**Comment by sergiou87** [comment]
More info: this only happens if the app started maximized, otherwise it'll behave as expected.

Steps to reproduce:
1. Open the app
2. Maximize it
3. Close it
4. Open it again
5. Change its size
6. Click on the app's icon in the Dock

**Comment by fabtjar** [comment]
Thanks @sergiou87. I've closed the app and reopened and it's working as expected now.

When I clicked on the icon before the window would maximise to fill the screen. It was still windowed, not fullscreen. I'd make it a smaller window size but would maximise when clicking the icon again.

I cannot replicate the issue.

**Comment by adamjohnson** [comment]
I too had the same experience as fabtjar on Github Desktop 2.6.3--except I'm on OSX Catalina (10.15.7).

I followed sergiou87's directions and that seems to have fixed the maximizing issue for me. Thanks, folks. 🌟
