### ISSUE TITLE
Setting for toggling "Recent" repositories in the repository switcher

### ISSUE THREAD

**Issue by karmasakshi** [desktop/desktop#11598]
### Describe the feature or problem you’d like to solve

Suggestion to allow the "Recent" repositories inside repository switcher to be hidden.

### Proposed solution

A checkbox in `Settings > Appearance` to Enable or Disable the "Recent" section in repository switcher.

**How will it benefit Desktop and its users?**

It may be confusing for some to see the same repository twice in the list. This will allow them to turn this section off.

### Additional context

**Add any other context like screenshots or mockups are helpful, if applicable.**

<img width="257" alt="Screenshot 2021-02-16 at 8 59 03 AM" src="https://user-images.githubusercontent.com/4698762/108020175-39c93f80-7035-11eb-8aa5-b83e884f44fb.png">

**Comment by geophilusd** [comment]
Can I work on this?

**Comment by geophilusd** [comment]
Can I work on this?

**Comment by steveward** [comment]
Requested in https://github.com/desktop/desktop/issues/12633.

**Comment by steveward** [comment]
Requested in https://github.com/desktop/desktop/issues/12824.

**Comment by quisido** [comment]
It looks like a PR was already opened for this and just closed??

This "feature" is detrimental to the developer experience. Please just accept the PR.

**Comment by quisido** [comment]
It's also requested in #9156 with another commenter offering support.

**Comment by billygriffin** [comment]
Hi folks, I'm going to close this for now as something we don't intend to support. We'll continue to monitor feedback as we go and likely do a more holistic look at the repo switcher down the road, but we're not going to add a toggle at this point to turn off the recent repos list. If you haven't yet weighed in here, please feel free to continue to share feedback that's different from what others have shared, or add a 👍 on the original issue here to express agreement.

**Comment by steveward** [comment]
Feedback from #13160:

>Previously I found the `Recent` category in the `Current Repository` tab useful, but at the moment it's just an extra category which I would rather hide to have an organized list of all currently cloned repositories. This would also make the only headers in the list the category headers of repositories forked from others or organizations.

**Comment by bnn678** [comment]
Adding an additional comment for visibility in the hopes that will encourage development on this issue.

If not a feature flag, an additional potential improvement would be to allow users to specifiy the number of recent repositories they want displayed. That would serve as both an improvement and a solution to this issue as users could set the number to 0.

**Comment by mlar1997** [comment]
Also adding comment to chime in - it would be a good feature to include.

**Comment by ChristianDunweber** [comment]
I agree, would be a nice feature. I'm annoyed by the "non-consistency" of recents.

**Comment by gusso** [comment]
Maintaining a small list of repositories for each org should allow me to find things a lot faster, but the `Recent` list feels like it's always in the way of scanning quickly for me because:

- the content of the list items is always changing, so there's less visual memory for the prime area at the top left
- it changes height whenever you delete a repository, so the `y` position where the first org starts is also often moving
- it has no visual treatment to differentiate it from the rest of the org lists, so it looks like another org

It would be great if any of these areas could be improved, but I'd prefer for the whole feature to be optional.

**Comment by marclammerding** [comment]
Agreed, please add this feature.

**Comment by vampire337** [comment]
A simple options checkbox to disable redundant display of repositories would allow developers who like this to continue to see it, and allow users who don't need the clutter to hide it. Even Windows includes the ability to show/hide "recent folders" in Windows Explorer. I don't understand why this request from three and a half years ago has been so controversial.

**Comment by brunobittarello** [comment]
> something we don't intend to support

This recent repo is a feature that you are supporting, we just want to hide it. It is a simple thing that shouldn't be a big issue or breaking change. Please reconsider it.

**Comment by digbyphonic** [comment]
+1

**Comment by Tom5421** [comment]
Once again another 'Feature' that gets in the way that the user can't disable.

Very frustrating to see that people have done the work to remove this annoyance but it wasn't accepted....

**Comment by maartenbusstra** [comment]
Would love to get rid of the recent list. Please accept.

**Comment by sstrandvold** [comment]
Please fix this.

**Comment by quisido** [comment]
I am supremely annoyed that this feature has been requested to be disableable by an innumerable number of users for _four years_ and is still ignored.

Can we reframe the ask? **What criteria needs to be met before you're willing to accept this change?** @billygriffin

**Comment by arvicxyz** [comment]
I already became a dad and this feature is not yet implemented. Let there be fix. Okay back to coding. Still super annoying to see 4 changes indicator instead of only 2.

**Comment by quisido** [comment]
Sorry, I should say that it's been _nearly six (6)_ years because [the original issue](https://github.com/desktop/desktop/issues/9156) was also closed.

**Comment by mattjonsson** [comment]
Please fix this.

**Comment by TFJ5183** [comment]
+1

**Comment by liuqixing** [comment]
i really want this, and can i work on this?

**Comment by Wanheda407** [comment]
@billygriffin This feature has been requested numerous time and a large amount of people support the change. It is a simple toggle that has been continuously asked for going on _6 years_ now. I see no reason why this can not be added and multiple Pull Requests have been made and just closed that address this. Having this many users wanting a change that does **not** affect the people that like the recent section and not even giving so much as a valid reason for why it won't be implemented is both baffling and frustrating. This simple toggle can just be added to the settings menu, defaulted to on, and anyone that does not want the recent list can just toggle it off.
