### ISSUE TITLE
Renamed existing repo name1 to name2. Created new repo name1.  Cloning name1 now clones name2.

### ISSUE THREAD

**Issue by shalemrv** [desktop/desktop#11604]
I had a repository `Portfolio`
I renamed it to `AngularJS-Portfolio`
I created a new Repo with name `Portfolio`
(because my portfolio is now developed in a different tech stack)

Now whenever I clone `Portfolio` repo using Github Desktop, it's cloning `AngularJS-Portfolio` instead of the new Repo named `Portfolio`

Note: Problem only with the Desktop Application(Windows10) and not Git CLI.
Reinstalling Github desktop did not solve this issue.

Version : 2.6.3
Operating System: Windows 10

### Steps to reproduce the behavior

1. Create Repo named repo1
2. Change name to repo2
3. Create new repo1
4. Clone repo1
5. See error

### Expected behavior

When I clone `Portfolio` it has to clone the new repo `Portfolio` and not the repo that was earlier named `Portfolio`
It appears `Portfolio` has became an alias for `AngularJS-Portfolio`.

### Actual behavior

When cloning `Portfolio` it's actually cloning `AngularJS-Portfolio`

### Screenshots

![image](https://user-images.githubusercontent.com/50116207/108068688-6b1f2b00-7088-11eb-9f76-a7fad87a81db.png)

Now there are 2 instances of the repo AngularJS-Portfolio in different folders.

Thank you.

**Comment by sergiou87** [comment]
Thanks for your report @shalemrv!! ❤️ 

From what I see, this seems to be the same issue as #11448, so I'm gonna close this in favor of that one.
