### ISSUE TITLE
桌面图标

### ISSUE THREAD

**Issue by zhyotaog** [desktop/desktop#11607]
话不投机半句多！请技术师查阅我的桌面图标，我运行的时间已很长了，但程序还末响应过来，请问怎样解决？谢谢！

**Comment by sergiou87** [comment]
Hi @zhyotaog!

I'm sorry, but the team doesn't speak Chinese 😳  I used Google Translate and this is what I got:

> **Desktop icon**
> Don't be too speculative! Ask a technician to check my desktop icon. I have been running for a long time, but the program is still not responding. How can I solve it? Thank you!

Would you mind filling the issue template so that we can understand better what is the problem?

```
### Describe the bug

A clear and concise description of what the bug is.

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

### Expected behavior

A clear and concise description of what you expected to happen.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

Add any other context about the problem here.
```

**Comment by zhyotaog** [comment]
Thank you for your reply!  My problem is that when I run the desktop GitHub program and the computer responds very slowly, I can't wait to terminate the program.  And I submitted a question to you without knowing it!  Thank you for your response!发自我的华为手机-------- 原始邮件 --------发件人： Sergio Padrino <notifications@github.com>日期： 2021年2月17日周三 下午4:50收件人： desktop/desktop <desktop@noreply.github.com>抄送： zhyotaog <w284945@hotmail.com>, Mention <mention@noreply.github.com>主    题： Re: [desktop/desktop] 桌面图标 (#11607)

Hi @zhyotaog!

I'm sorry, but the team doesn't speak Chinese 😳  I used Google Translate and this is what I got:



Desktop icon

Don't be too speculative! Ask a technician to check my desktop icon. I have been running for a long time, but the program is still not responding. How can I solve it? Thank you!



Would you mind filling the issue template so that we can understand better what is the problem?

### Describe the bug



A clear and concise description of what the bug is.



### Version & OS



Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.



### Steps to reproduce the behavior



1. Go to '...'

2. Click on '....'

3. Scroll down to '....'

4. See error



### Expected behavior



A clear and concise description of what you expected to happen.



### Actual behavior



A clear and concise description of what actually happened.



### Screenshots



Add screenshots to help explain your problem, if applicable.



### Logs



Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.



### Additional context



Add any other context about the problem here.

**Comment by steveward** [comment]
@zhyotaog could you upload the log file from GitHub Desktop so that I could get some more information about these performance issues? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by steveward** [comment]
Closing this issue out due to inactivity.  @zhyotaog if you are able to share the log files I can assist you further. Thanks!
