### ISSUE TITLE
Click the Dock Icon Expands the App's Window to the Screen's Bounds

### ISSUE THREAD

**Issue by grantjbutler** [desktop/desktop#11611]
### Describe the bug

When activating the app through the Dock on macOS, the app's window grows to the size of my display.

### Version & OS

Desktop app Version 2.6.3

### Steps to reproduce the behavior

1. While the app is running, click on the app icon in the Dock (the app can hidden, just behind any other windows of other apps, or the foreground app).

### Expected behavior

The main app window becomes active if it wasn't already active.

### Actual behavior

The main app window becomes active if it wasn't already active, and expands to the full bounds of my screen.

### Screenshots

https://user-images.githubusercontent.com/526054/108232241-8fbee580-7110-11eb-80e4-6c22c078172d.mov

### Logs

N/A

### Additional context

I don't know if this matters, but I saw this behavior while having an additional screen attached, and the lid on my laptop closed. Most of the time, I work from the laptop with the app already expanded to the full size of the screen, since it's a laptop screen. I just noticed the behavior since I started using an external display.

**Comment by sergiou87** [comment]
Thanks for your report @grantjbutler!! ❤️ 

You'll be glad to know this was fixed yesterday in #11599, so the fix should be out in the next version (beta and production).

If you're interested, there is a workaround for now: resize GitHub Desktop so it's not maximized, then close it and open it again.

After that, the app should behave as expected... until you close the app being maximized again 😅 

I hope that helps!
