### ISSUE TITLE
Make GitHub Desktop a verified entity on GitHub

### ISSUE THREAD

**Issue by neil-119** [desktop/desktop#11612]
Currently, the Authorized OAuth Apps section on GitHub does not show `GitHub Desktop` as a verified entity. I don't know about you, but it makes me a little uneasy to grant it access to our repos. Ideally, if it showed `github` as being the owner, even better, or at least verified to be a GitHub product.

![image](https://user-images.githubusercontent.com/4636522/108269607-d83bca80-7133-11eb-827e-0e0c909267e8.png)

**Compare that with the VS extension:**

![image](https://user-images.githubusercontent.com/4636522/108269803-251fa100-7134-11eb-8ea6-308c7117c2e1.png)

**Comment by sergiou87** [comment]
Thank you for your report @neil-119 😄 

I think you're totally right and the `desktop` organization should be verified. From what I see, the process to verify it started but wasn't completed. I just initiated the process again and hopefully it should be done in the next few days 🤞

**Comment by sergiou87** [comment]
Now https://github.com/desktop/ is a verified org! 😌 
Thank you again @neil-119! ❤️
