### ISSUE TITLE
Multiple projects open at the same time

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#11627]
### Describe the feature or problem you’d like to solve

First, I apologize if this issue already exists or is similar to another one but I couldn't find one.

Now, here is my idea. It would be cool if we could have a " tab system " so you can have multiple git projects open in the same time so you don't have to switch between one to the other. It can be really usefull if we are working with a git project that has a git submodule. In this case, you could have the main project open and its submodule. No need to switch, you can just go to the tab you want.

**Comment by steveward** [comment]
Thanks for the feedback @HoTKreeZy. Since this is along the lines of the feedback we've been tracking in https://github.com/desktop/desktop/issues/3606 I'm going to add this there and close this issue out. Thanks for using GitHub Desktop!
