### ISSUE TITLE
 Why is the original old file still after I update

### ISSUE THREAD

**Issue by Tsuj100** [desktop/desktop#11628]
hope delete old files after the update

**Comment by steveward** [comment]
Thanks for the issue @Tsuj100. Can you share a few more details about the issue you are experiencing in GitHub Desktop? It would be helpful if you could fill out the issue template to give us more information.

When you say 'after the update' are you referring to performing a `Pull origin` operation in GitHub Desktop to pull down new changes from the remote repository?

**Comment by Tsuj100** [comment]
I am referring to the githubdesktop client

**Comment by steveward** [comment]
@Tsuj100 we will need more information about the specific issue you are encountering. Without that it will be difficult to assist you further.

**Comment by Tsuj100** [comment]
![image](https://user-images.githubusercontent.com/38718810/108795948-7f03e900-75c2-11eb-8666-cfe2a6a851f9.png)
like this，After the update, the old version file is still there

**Comment by steveward** [comment]
Thanks for the screenshot @Tsuj100. The Squirrel installer we use with GitHub Desktop keeps around the previous version of the application -- see https://github.com/Squirrel/Squirrel.Windows/issues/589. I hope that helps!
