### ISSUE TITLE
Add Option To Skip Pre-Commit Hooks (--no-verify)

### ISSUE THREAD

**Issue by digitalmaster** [desktop/desktop#11626]
### Describe the feature or problem you’d like to solve

I love this app so much that I feel a sense of discomfort anytime I need to switch to my terminal to do something. In that spirit, one of the actions that still requires switching to the terminal is performing a commit that I know will fail the pre-commit hooks (ex: linting).

### Proposed solution
**Proposal I**: Add Option to skip webhooks in commit form
This could be a checkbox next to the "Add Co-Authors" Icon. 
![image](https://user-images.githubusercontent.com/1279335/108532884-b6b31e00-72ae-11eb-9b41-6a176f83684a.png)

**Proposal II**: Add a "Commit Anyway" button to failed pre-commit hook modal
![image](https://user-images.githubusercontent.com/1279335/108532825-a56a1180-72ae-11eb-8d0b-bf559fd7460b.png)

How will it benefit Desktop and its users?
No need to switch to perform checkpoint commits where we expect our hooks to fail.

**Comment by steveward** [comment]
Thanks @digitalmaster! We've discussed the option of providing a pre-commit "escape hatch" in https://github.com/desktop/desktop/issues/9351. I'm going to add this feedback to that thread. Thanks for using GitHub Desktop!

**Comment by kazunetakeda25** [comment]
Hi @steveward is this feature added? or not yet?

**Comment by steveward** [comment]
@kazunetakeda25 this feature has not been implemented yet.

**Comment by keoshi** [comment]
Also looking forward to have this capability in the desktop app.

**Comment by qanut** [comment]
Would definitely be a quality of life improvement to get this feature added.  Hope it can be added soon.

**Comment by AkqaMartin** [comment]
Any news on this? I would love to see this feature implemented

**Comment by Hantuch** [comment]
Would love to see this! it can be annoying sometimes

**Comment by Ghurir** [comment]
For people still struggling with this, you can use the following method:

1. select all the files you want to commit
2. press the commit button, and wait for it to show the error popup.
3. On the top window select "Repository>Open in command prompt"
4. type "git status" to verify that the files you selected have been added to the staging area
you should see something like:
```
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   simulation_parameters/microbe_stage/compounds.json
        modified:   src/engine/Settings.cs
        modified:   src/microbe_stage/Compound.cs
        modified:   src/microbe_stage/CompoundCloudPlane.cs
        modified:   src/microbe_stage/CompoundCloudPlane.tscn
        modified:   src/microbe_stage/CompoundCloudSystem.cs
```

5. If all files are present use "git commit --no-verify"

**Comment by 1pete** [comment]
i use this, works for me :)
```sh
git config --global core.hooksPath /dev/null
```

source: https://stackoverflow.com/questions/7230820/skip-git-commit-hooks

**Comment by mosherc** [comment]
> For people still struggling with this, you can use the following method:
> 
> 1. select all the files you want to commit
> 2. press the commit button, and wait for it to show the error popup.
> 3. On the top window select "Repository>Open in command prompt"
> 4. type "git status" to verify that the files you selected have been added to the staging area
>    you should see something like:
> 
> ```
> Changes to be committed:
>   (use "git restore --staged <file>..." to unstage)
>         modified:   simulation_parameters/microbe_stage/compounds.json
>         modified:   src/engine/Settings.cs
>         modified:   src/microbe_stage/Compound.cs
>         modified:   src/microbe_stage/CompoundCloudPlane.cs
>         modified:   src/microbe_stage/CompoundCloudPlane.tscn
>         modified:   src/microbe_stage/CompoundCloudSystem.cs
> ```
> 
>  5. If all files are present use "git commit --no-verify"

That's not really any easier than committing via command line in the first place. It would be nice to have this in the UI so we don't have to go to the command line at all.

**Comment by karpur** [comment]
--no-verify works, but in my case, I didn't want to put the parameter all the time on the terminal. So I opted for something a little more aggressive.

If you want to disable git hooks globally, you could try running this:

git config --global core.hooksPath /dev/null
But, if you want to leave it as it was before, just run the following command in your terminal:

git config --global --unset core.hooksPath
If you do not want it to be global, just remove the argument: --global

**Comment by ryanhiebert** [comment]
Can you see if this solves your problem? I think this might disable hooks and store the config in the local repository directly, and it doesn't appear to be the same way that the pre-commit hook is installed, so it may persist even after launching a devcontainer.

```sh
git config core.hooksPath /dev/null
```

**Comment by alimertcakar** [comment]
It would be nice to still have pre-commit hooks in terminal and have --no-verify in github desktop for things like squashing...

Suggested solutions are worse IMO.
Actually commenting and uncommenting husky precommit files is easier. You could bind that to an alias like: "$disable-precommit hooks"  "$enable-precommit-hooks". Also you have to git reset them so you don't commit them, and stash them when you are about to commit/squash etc.

**Comment by rprhernandez** [comment]
any news if this will be implemented in the near future..?

**Comment by marceloapd** [comment]
up

**Comment by dragidavid** [comment]
up up ☝

**Comment by JohannSig** [comment]
Up 👍🏻

**Comment by sushil-b** [comment]
Waiting for this 👀

**Comment by maurei** [comment]
Upping this too :-)

**Comment by rignaneseleo** [comment]
upppp

**Comment by cloydlau** [comment]
upppp

**Comment by kaytladi22** [comment]
UUUUUUUUppp

**Comment by JDS-DC** [comment]
Why is this marked as closed? It's still a missing feature. It's essential!

**Comment by yatsenkoleg-spiralsoft** [comment]
up

**Comment by anastasiia-matiushenko** [comment]
hey! any chance we actually have this `commit anyway` in Github Desktop. will be super useful!!
