### ISSUE TITLE
GitHub Desktop displaying incorrect commit history for a branch after a merge

### ISSUE THREAD

**Issue by btitze** [desktop/desktop#11639]
### Describe the bug

I merged around 80 commits from a feature branch into another existing development branch using GitHub Desktop und dealt with several merge conflicts.  The commits that I merged were from April and May 2020.
I noticed that all those old commits from April/May 2020 did not show up in the history of the branch in GitHub Desktop.
Interestingly, when I select a branch to compare -- and I select the one that the branch was based off before the merge -- all the commits that were merged are correctly shown as "Ahead", but when I remove the comparison and check in the history, they are not there.

### Version & OS

GitHub Desktop Version 2.6.3, 
OS: Windows 10 Pro

### Steps to reproduce the behavior

1. Switch to the branch in GitHub Desktop and click "Fetch Origin"
2. Click on History
3. Search for the expected commit - It cannot be found.
4. Go to GitHub.com, to the same branch and search for the expected commit - it can be found.

I tried to remove the local repository and cloned it again, but this did not help: The commits that should be in the history of the branch are not shown.

### Expected behavior

The commit history for a branch on GitHub.com should be identical to the commit history shown for that same branch in GitHub Desktop.

### Actual behavior

The commit history in GitHub Desktop is not correct - 80 commits that should be in the history are not shown.

### Additional context

Could be related to a similar bug report posted here:
https://github.com/desktop/desktop/issues/11045

**Comment by btitze** [comment]
I'd like to add that I also checked with git on the command line (Git for Windows):
`git log --full-history`
All the commits are in the history, but in GitHub Desktop, they are not.

**Comment by steveward** [comment]
@btitze I believe this should be resolved by the fix in https://github.com/desktop/desktop/pull/12553. Let us know if you're still encountering this!
