### ISSUE TITLE
Pushing to GitHub from command line

### ISSUE THREAD

**Issue by Vydra-ai** [desktop/desktop#11637]
Hello, I am having a bit of trouble pushing my code to github using command lines.
I am on Windows 10 downloaded curl and git.
Using a command "  curl -u "Vydra-ai" https://api.github.com/user/repos -d "{ \"name\": \"EcommerceGamlit\" }"   " that I found in a tutorial should create the repository but all I get is a json response :
"message": "Requires authentication",
"documentation_url": "https://docs.github.com/rest/reference/repos#create-a-repository-for-the-authenticated-user"
and I have no idea what I am suppoused to authenticate.
Thank you for your response.

**Comment by steveward** [comment]
👋🏻 @Vydra-ai this issue tracker is for [GitHub Desktop]( http://desktop.github.com). If you have questions about using Git from the command line I'd recommend asking in our [Community forum](https://github.community/) or by contacting [GitHub Support](https://support.github.com/).
