### ISSUE TITLE
"Open in Visual Studio Code" ignores VSCode Dev Container window

### ISSUE THREAD

**Issue by Soneji** [desktop/desktop#11634]
### Describe the bug

When I right click a file in file explorer, and click "Open in Visual Studio Code" it opens the file in the wrong editor window if I am using a [Dev Container](https://code.visualstudio.com/docs/remote/containers)

### Version & OS

Version 2.6.3
MacOS Big Sur

### Steps to reproduce the behavior

1. Setup devcontainer in vscode
2. Right click file in github desktop
3. Click 'open in vscode'
4. github desktop opens file in new window or wrong window

### Expected behavior

File should open in devcontainer window

### Actual behavior

File opened in new window/old incorrect window

**Comment by steveward** [comment]
Thanks for the report @soneji. I haven't used this feature of VSCode, but with a quick read of the documentation it does look like projects should be opened in the container once the `devcontainer.json` file has been created:

>You can now interact with your project in VS Code just as you could when opening the project locally. From now on, when you open the project folder, VS Code will automatically pick up and reuse your dev container configuration.

I'm going to label this as `help-wanted` in case someone else from the community wants to dig into this further.

**Comment by Soneji** [comment]
Hi @steveward 
I actually have `.devcontainer/devcontainer.json` in the repository but it still opens in the standard editor

**Comment by ADustyOldMuffin** [comment]
I opened a bug in the VS Code Repository for this, you can find it [here](https://github.com/microsoft/vscode/issues/127587). But I don't think this is a Github Desktop issue as it occurs outside of Github Desktop as well in windows file explorer and the command line.

**Comment by ADustyOldMuffin** [comment]
From that other issue https://github.com/microsoft/vscode/issues/127587#issuecomment-871660400 that's to be expected.

**Comment by ADustyOldMuffin** [comment]
@steveward After a discussion on the VSCode repo this request is not actually possible for VSCode as the host computer can't determine if the folder is open inside VSCode in a container since it's well, in the container.

They're looking at ways to fix this but I believe this should be able to be closed.

**Comment by steveward** [comment]
@ADustyOldMuffin thanks for the update! We'll close this out for the time being but this is something we can revisit again in the future if things change.
