### ISSUE TITLE
issue feature for github desktop

### ISSUE THREAD

**Issue by histion** [desktop/desktop#11630]
### Describe the feature or problem you’d like to solve
first,my english is no good,the mean may be have deviation 

I think should add issue to github desktop，now version if i want to create a new issue of change some issue,i must to github.com Instead of  use desktop,so i think could you add this Features ？thank you~❤

### Proposed solution

if  must open browser,so much windows often look like boring,and affect work efficiency 
i want the github desktop can:create new issue ,close issue ,add assigneess labels and some..

### Additional context

NO have

**Comment by steveward** [comment]
@histion thanks for the issue. You can use the `Control+I` shortcut in GitHub Desktop to quickly launch your browser and create a new issue.

At this time we do not have plans to add full issue integration to GitHub Desktop. You can find some discussion about this in https://github.com/desktop/desktop/issues/8989, specifically [this comment](https://github.com/desktop/desktop/issues/8989#issuecomment-587545367).  I hope that helps explain things!
