### ISSUE TITLE
GitHub Desktop Hangs in Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by surfd4wg** [desktop/desktop#11645]
### Describe the bug

After installing GitHub Desktop on Ubuntu 20.04.02 LTS, created a new repo File --> New Repository.
Copy files into the local directory.
Commit 

GitHub Desktop hangs.  It says "Committing to main"

and doesn't come out of it...

### Version & OS

Ubuntu focal 20.04.2 LTS
GitHub Desktop 2.6.3-linux1

### Steps to reproduce the behavior

1. After installing GitHub Desktop on Ubuntu 20.04.02 LTS, created a new repo File --> New Repository.
2. Copy files into the local directory.
3. Commit 
4. Hangs

### Expected behavior

I expect the GitHub Desktop UI to come back right after the commit button is pushed.

### Actual behavior

Hangs with "Committing to main"

### Screenshots

![image](https://user-images.githubusercontent.com/63609504/108907100-e92a8700-75de-11eb-97ae-7966652e8381.png)

**Comment by steveward** [comment]
👋🏻 @surfd4wg I'd recommend opening an issue in the Linux fork of GitHub Desktop:

https://gihtub.com/shiftkey/desktop

At this time we do not provide official support for Linux, but feel free to 👍🏻 in [this issue](https://github.com/desktop/desktop/issues/1525).

**Comment by BudgieInWA** [comment]
For reference, this sounds like it might be https://github.com/shiftkey/desktop/issues/329, with a workaround of switching away from the app then back.
