### ISSUE TITLE
Automatically get the currently created branch.

### ISSUE THREAD

**Issue by Gu-f** [desktop/desktop#11647]
### Describe the feature or problem you’d like to solve

Better compatibility with GitLab.
Using GitLab.
Branch cannot synchronize with Web.
When I create a branch on the Desktop, the web can see the created branch, but when I create a branch on the web, the Desktop can't get the branch automatically unless I clone it again.
I hope to provide a button to refresh the branches, or automatically synchronize the branches created by the web.

**Comment by steveward** [comment]
@Gu-f thanks for the issue. You can click the `Fetch origin` button to pull down any new branches from your GitLab repository. The branches will appear as `origin/<branch_name>` in the repository list. You don't need to clone the repository again. I hope that helps!

**Comment by Gu-f** [comment]
Thanks. I did it.
