### ISSUE TITLE
Cannot install github desktop on my windows 32bit

### ISSUE THREAD

**Issue by BSCSC2018Garcia** [desktop/desktop#11646]
[###](url
[SquirrelSetup.log](https://github.com/desktop/desktop/files/6032585/SquirrelSetup.log)
) Describe the bug

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the issue @BSCSC2018Garcia. At this time GitHub Desktop only supports 64-bit versions of Windows.

There is another GitHub Desktop user who put together an experimental 32-bit build of GitHub Desktop -- see this comment for how to access that:

https://github.com/desktop/desktop/issues/6874#issuecomment-524081839

I hope that is helpful!
