### ISSUE TITLE
I chose "Open in Desktop" for a file in a PR, and GH desktop opens but does not display the PR diff there

### ISSUE THREAD

**Issue by StingyJack** [desktop/desktop#11649]
### Describe the bug

I was looking at a PR for someone and having trouble reading the code due to the word wrapping that was being done, so I wanted to try viewing the diff some other way.  I chose "Open in Desktop" for a file in a PR, and GH desktop opens but does not display the PR diff there  It just asked me about cloning the repo and eventually opened a folder where the PR Branch's file was at. 

### Version & OS

Windows 10

### Steps to reproduce the behavior

See title and description

### Expected behavior

I expected to see the diff open in GH Desktop, without wordwrapping (hopefully, otherwise there isnt a point to me taking this set of actions)

### Actual behavior

The best I got was windows explorer folder being opened showing me the files in the PR branch.  I still would have to open them up in some other editor or Git for windows differ.

### Screenshots

cant

### Logs

dont think they are relevant here, can sanitize and post if really needed

### Additional context

Word wrapping source code in a diff/comparison window does not make any sense to be doing.

**Comment by steveward** [comment]
@StingyJack thanks for the issue. The `Open in Desktop` option will clone the repository (if it does not already exist) and check out the relevant PR branch. You can then navigate to the `History` tab to view the commit history of the branch. I hope that helps!

**Comment by billygriffin** [comment]
Adding to what @steveward helpfully shared, we are likely going to be working on an improved PR experience in the next few months, so hopefully this should be improved for you before too long. 😄

**Comment by StingyJack** [comment]
@steveward - will the open in desktop action meet the expectation of doing what the browser is doing?

@billygriffin - I have given a rather long list of usability impediments, defects, and other problems with the GH PR system in a support ticket a few weeks ago. Are any of those on the desktop roadmap?

**Comment by billygriffin** [comment]
This is the issue describing some of the things we're thinking about for PRs: https://github.com/desktop/desktop/issues/11517

**Comment by StingyJack** [comment]
I commented on the other issue you noted, but I am afraid that you will not take the opportunity as far as it needs to go or won't be allowed to use it properly and we will just get a desktop version of the same crummy PR tooling the dotcom has.

I still expect the menu item I clicked here to open in the diff view, but the diff view should be **better** otherwise what's the point?
