### ISSUE TITLE
Add added and deleted count

### ISSUE THREAD

**Issue by Piet2001** [desktop/desktop#11656]
### Describe the feature or problem you’d like to solve

When you have committed something, you will see the number of lines that have been changed (added and removed) on the site. I think it would be nice if you could also see this in the desktop app before you put this online.
I myself work with different JSONs and in this way I can easily check whether too much has been deleted.

### Proposed solution

More clarity about the changes in the files.

**Comment by sergiou87** [comment]
@Piet2001 I hope this helps: #12714 😄
