### ISSUE TITLE
Provide visual feedback to the user while a merge is taking place

### ISSUE THREAD

**Issue by FUJonathan** [desktop/desktop#11650]
### Describe the feature or problem you’d like to solve

When the user merges a branch into another, there is no visual feedback to the user until the merge completes. For long merges, it can be unclear that the merge is actually taking place and the git process has not hung, crashed, etc., and the user may subsequently try to repeat the merge or perform some other action at the same time.

### Proposed solution

Display the message "Merging {branch A} into {branch B}" somewhere while the merge operation is taking place. Suggested locations are the branch button or the "toast" where the "merge successfully completed" message appears. If possible, it would also be nice to report the progress of the merge with a progress bar behind the text, etc. This would indicate to the user that the operation is taking place and they should wait before doing anything else.

#### Mockup 1: Branch button
![image](https://user-images.githubusercontent.com/7123060/109103604-8a941300-776e-11eb-9251-6a00056f3629.png)
This can get cramped if the branch names are long, and splitting onto two lines may prove to be a challenge for localization depending on the target language. However, it is consistent with other actions.

#### Mockup 2: "Toast" where the "Successfully merged" message appears
![image](https://user-images.githubusercontent.com/7123060/109104276-0a21e200-776f-11eb-99bb-26868d65efcf.png)
Plenty of room for long messages, but you may need to implement a new spinner.

**Comment by steveward** [comment]
Thanks for the feedback @FUJonathan! I'm going to add this to https://github.com/desktop/desktop/issues/11650 where we are tracking this request.
