### ISSUE TITLE
I pushed my new github pages but it shows an error 404 on my himajpatil.github.io/JobApply/

### ISSUE THREAD

**Issue by HimajPatil** [desktop/desktop#11662]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tidy-dev** [comment]
@HimajPatil Thank you for your issue. Can you share a few more details about the issue you are experiencing in GitHub Desktop? It would be helpful if you could fill out the issue template to give us more information.

**Comment by steveward** [comment]
@HimajPatil it sounds like you are having issues getting your GitHub Pages site working. This issue tracker is for GitHub Desktop -- if you have any issues specific to GitHub Desktop please let us know. You can reach out for assistance with GitHub Pages [at our community forum](https://github.community/c/github-help/github-pages/31). I'm going to close this issue out.
