### ISSUE TITLE
Expand/Collapse func in history 

### ISSUE THREAD

**Issue by ratn1ksun** [desktop/desktop#11669]
### Describe the bug

I upload another iteration of code with 4 paragrpaph of comment, which visual splited by "#". When i open an "history" tab, and click to fresh uploaded data, i click on "expand/collapse" button, and when placeholder with my code comment expanded, i got all comment field start blink like crazy. If toggle to "colapse" blinks will stop, also if i click on documents that was changed or hover coursour to docs.   

### Version & OS

GirHub Desktop Version 2.6.3
Windows Version: 2044 (OS Build 19041,801)

### Steps to reproduce the behavior
1. Add 4 paragraph of "describe" field vithual splited by "#" only (with no spaces)
2. Commit to master 
3. Go to 'History'
4. Click on 'First history list option'
5. Click on 'Expend button'
6. See error

### Expected behavior

Non blink field 

### Actual behavior

I upload another iteration of code with 4 paragrpaph of comment, which visual splited by "#". When i open an "history" tab, and click to fresh uploaded data, i click on "expand/collapse" button, and when placeholder with my code comment expanded, i got all comment field start blink like crazy. If toggle to "colapse" blinks will stop, also if i click on documents that was changed or hover coursour to docs.   

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context
There is the video of what exactly happend 
https://youtu.be/5-mu5XvvXIs

**Comment by tidy-dev** [comment]
@ratn1ksun Thank you for the report!  I will mark this as a bug to be on our radar.

**Comment by sergiou87** [comment]
I cannot reproduce the issue here with some random text. @ratn1ksun could you post here the exact commit message you're using so we can try it out? Thank you! ❤️

**Comment by ratn1ksun** [comment]
With pleasure:
**---commit messege starts here---**
#Косяк был в том, что запрос выводит количество моделей по количеству тегов. Т.е. у одно модели - 3 тега.
Значит у меня будет 3 пуджа
#Второе, цикл вывода брал число исходя из отдельного, прямого запроса на количество моделей и получал верное их число, а именно - 4
#Третье, т.к. фильтр на дубли стоял до цикла вывода, получалась ситуация, при которой дубли "забивали" очередь вывода, таким образом, что: +1 тег к модели -> плюс один индекс в массиве -> он не выводится в виду проверки, при выводе, но как индекс остается смещая индексацию на +1 вперед.
#А т.к. он не выводится, но забивает индекс, а количество выводимых не зависит от количество тегов (т.к. там обособленный запрос) дубли забивали пространство в массиве тем самым последующие записи, уникальные шли вникуда, т.к. им не оставалось места
**---commit messege ends here---**

**Comment by sergiou87** [comment]
Thank you @ratn1ksun!! ❤️ 

However, I just created a commit with that text and I couldn't reproduce the behavior 😞  The text is expanded and collapsed normally for me, without weird UI glitches 🤯

**Comment by yusuf969** [comment]
I want to like any one in git

**Comment by sergiou87** [comment]
@ratn1ksun is this still a problem? We made some fixes in #14791 for this specific component that might have affected (and hopefully fixed) this bug 🤞
