### ISSUE TITLE
Failure to authenticate in WSL with SSH Keys after manually cloning

### ISSUE THREAD

**Issue by andria-dev** [desktop/desktop#11661]
### Describe the bug

To use 2FA with GitHub, I have to use SSH Keys. In using SSH Keys in WSL, I'm now unable to do any kind of action in GitHub Desktop that requires me to authenticate with GitHub with repositories that I have already cloned down. Specifically, I get the following error followed by a large list of explanations:

> Authentication failed.

And yes I am adding my SSH Key to my `ssh-agent` like so:

```bash
# Inside "~/.bashrc"

eval $(ssh-agent -s)
ssh-add
```

### Version & OS

I am using "Version 2.6.4-beta2" of GitHub Desktop. I was originally trying this out on the stable version though and upgraded to beta to see if it was fixed. Same problem in both versions.

I'm on Windows 10 Pro Version 20H2.

I'm using running Ubuntu 20.04 LTS in WSL version 1 (couldn't get version 2 to work).

```powershell
PS C:\Users\[username]> wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         1
```

```bash
$ uname -a
Linux [computer-name] 4.4.0-19041-Microsoft #488-Microsoft Mon Sep 01 13:43:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### Steps to reproduce the behavior

1. Install Ubuntu with WSLv1.
2. Use `ssh-keygen` to make Ed25519 keys.
3. Set the SSH Keys up in GitHub.
4. Clone down repository via SSH in the command line `git clone git@github.<user>/<repo>.git`.
 a. It is very important that it is cloned with SSH and not HTTPS.
5. Attempt fetch, pull, or push in GitHub Desktop.
6. Witness failure to authenticate.

### Expected behavior

Successful authentication despite using SSH.

### Actual behavior

Failure to authenticate and was presented with a modal telling me so.

### Screenshots

![Modal in GitHub Desktop saying "Authentication failed" and explaining possible reasons.](https://user-images.githubusercontent.com/19195374/109405771-98e25a80-7939-11eb-9dd1-2d970cfcccde.png)

> Authentication failed. Some common reasons include:
> - You are not logged in to your account: see File > Options.
> - You may need to log out and log back in to refresh your token.
> - You do not have permission to access this repository.
> - The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
> - If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.

### Logs

```text
2021-02-28T02:24:53.238Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
```

**Comment by andria-dev** [comment]
For now, I'm just going to change my remote url to HTTPS.

**Comment by tidy-dev** [comment]
@ChrisBrownie55 Thank you for the report. There are known problems with SSH. I am linking your issue to the current tracking issue for this. #2579
