### ISSUE TITLE
Authentication failed. Some common reasons include:

### ISSUE THREAD

**Issue by MD20M** [desktop/desktop#11678]
### Describe the bug
This happens when i try to publish a repository

### Version & OS

Version 2.6.3. I'm using windows 10 

### Steps to reproduce the behavior

1. Try to publish a repository

### Expected behavior

I wanted to publish a repository.

### Actual behavior

It says: Authentication failed. Some common reasons include:

### Screenshots

![image](https://user-images.githubusercontent.com/78083321/109771110-bb57ca80-7bfc-11eb-8b0f-5a8feafc5707.png)

### Logs

https://mega.nz/file/1oEBRaaL#vCqNb5jGG8i5wBDPXQOBLAnnBPSMmjpbJAAG4zM60lQ

### Additional context

I just want to publish a repository pls help!

**Comment by steveward** [comment]
Thanks for the issue @MD20M. It looks like you are using SSH authentication with this repository:

```
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

GitHub Desktop defaults to using HTTPS, and works best when using HTTPS for authentication. If you would like to switch to using HTTPS you can do so by going to `Repository` > `Repository Settings` > `Remote` and change the URL there to the HTTPS remote:

`https://github.com/<user>/<repo>.git`

If you would like to continue to use SSH you can follow the guide for setting up a SSH key on GitHub:

https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

Let me know if you run into any issues.
