### ISSUE TITLE
Show GitLab Merge Request Details in the GitHub Desktop app

### ISSUE THREAD

**Issue by pmolaro** [desktop/desktop#11673]
### Describe the feature or problem you’d like to solve
I am requesting that the desktop client be updated to show a GitLab project's merge request details, with the same functionality that is offered for a GitHub project.

In addition, I am requesting that it also allow users to make MR comments and sync those back and forth with the website client. See issue #11672 for specific details. 

### Proposed solution
Not sure what else to add here except that I would like to be able to mange both GitHub and GitLab projects via the desktop client. 

How will it benefit Desktop and its users?
The desktop client UI is more open and easier to read than the desktop client. Allowing users the ability to manage projects from both GitLab and GitHub would be a game changer.

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by billygriffin** [comment]
Hi @pmolaro, thanks for the issue! While we support basic functionality for other hosting providers, GitHub Desktop is a GitHub project and therefore we prioritize improving support for GitHub features over others, given that we have a small team and limited bandwidth. Additionally, everything added is additional maintenance overhead, and we have far less visibility and control over changes made to things (like merge requests) from other hosting providers. I know that's likely a disappointing answer but hopefully that explains our reasoning.
