### ISSUE TITLE
Add Ability to Add Comments on a Pull/Merge Request

### ISSUE THREAD

**Issue by pmolaro** [desktop/desktop#11672]
### Describe the feature or problem you’d like to solve
I would like to be able to fully manage a pull request in the desktop application, in the same manner I can in website. Additionally, I would like the same functionality for a connected GitLab repository.

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.
I recently installed GitHub Desktop for Mac and connected to to both my GitHub account and my company's GitLab account. I am looking for a better experience managing Pull Requests / Merge Requests than the current Web UI. In one of my GH projects, I created a dummy feature branch and submitted a small change for it. I then started a pull requests for it against master/main. In the GitHub Desktop app, I can see the pull request, but I cannot make comments on the changes. Via the web view I made a sample comment on one of the changes. I went back to the GH Desktop app and hoped to at least seem the comment but did not. 

### Proposed solution
Update the desktop application to allow a user to add a comment to the changed code in a pull request. These comments should sync with the web client in real time. The desktop client should also show comments made to PRs via the web client, and offer a sync button to refresh comments. 

How will it benefit Desktop and its users?
The UI in the desktop app is superior to the web client, so being able to do PRs with it would be superior to the web client. 

### Additional context
I will add a 2nd feature request to add this functionality for a GitLab project, which currently doesn't;t even show the PR option.

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by tidy-dev** [comment]
@pmolaro Thank you for your feedback. We are tracking feedback related to a possible improved pull request experience in Desktop on  #11517.  I am going to close this in favor of that as this will now be linked to that discussion. Great input!
