### ISSUE TITLE
Colors are offset when hide whitespace changes is enabled in the diff

### ISSUE THREAD

**Issue by ImRodry** [desktop/desktop#11681]
### Describe the bug

When you go to the commit history of a repository, find a commit with whitespace changes and enable the "Hide whitespace changes" option, the colors of the text are offset (they are set to where the text would be if the option was disabled) 
![image](https://user-images.githubusercontent.com/38259440/109795476-e21efc80-7c0e-11eb-94b1-32d0b9e26b7f.png)

### Version & OS

Version 2.6.3, Windows 10 20H2 build 19042.844

### Steps to reproduce the behavior

1. Make a commit where you add/remove whitespaces
2. Go to the commit history and select that commit
3. Make sure "Hide whitespace changes" is enabled
4. Observe the overlapping colors

### Expected behavior

The colors adapt to the position of the diff

### Actual behavior

The colors stay where the text would be before the commit

### Screenshots

![image](https://user-images.githubusercontent.com/38259440/109795741-3924d180-7c0f-11eb-808a-541556f0e749.png)

**Comment by tidy-dev** [comment]
@ImRodry Thank you for the report. I was able to reproduce as well.  Marking as bug. 

![image](https://user-images.githubusercontent.com/75402236/109813125-ee00c380-7bfa-11eb-88ce-c7f7afb06dcf.png)

**Comment by niik** [comment]
Hey @ImRodry, I missed this issue and ended up engaging in #14920 instead which describes the same issue. Given that we've already got a discussion going in there I'm going to close your issue in favor of that and ask that you subscribe to #14920 for any updates regarding this!
