### ISSUE TITLE
Make it easier to recycle commit summaries (and possibly messages as well)

### ISSUE THREAD

**Issue by dfeinzimer** [desktop/desktop#11689]
### Describe the feature or problem you’d like to solve

As someone who consistently sets the commit "summary" field to consist of a date and time timestamp(YY.MM.DD.HH.MM.SS) I'd love to see the ability to persist my previous timestamp in the summary field so I can only change the values that are needed each time I commit.

### Proposed solution

It will make it quicker for anyone who uses a consistent summary message form to commit.

### Additional context

N/A

**Comment by billygriffin** [comment]
Hi @kernelpop, thanks for the issue and sorry for the delayed reply. While I totally understand how this might be useful for you, we haven't seen enough evidence that this is a common enough use case to support this more broadly. I know that's not a particularly satisfying answer, but didn't want to just close your issue without explaining why. Thanks again.

**Comment by dfeinzimer** [comment]
@billygriffin @sergiou87  I know it's been a while and this didn't pique your interest before but I just discovered that SmartSVN almost has this exact feature and it's very handy. 

One simply selects a dropdown menu and is provided with a list of the most recent commit messages ([example here](https://ibb.co/87kBYmN)). Clicking on one auto-fills the commit message field.

This indicates to me that it actually is a feature that others would use and find helpful.

I could also imagine it implemented as if the text field were a terminal and a user could just use the up/down arrows to revive previous commands (commit messages in this context). That would presumably require zero UI modification.
