### ISSUE TITLE
How to compile and use this

### ISSUE THREAD

**Issue by Yoplayer-1** [desktop/desktop#11692]
Hi I don't know TypeScript so how can I compile and use this.

**Comment by sergiou87** [comment]
Hello @Yoplayer-1! 👋 

I recommend you to take a look at the [Development Environment Setup](https://github.com/desktop/desktop/blob/development/docs/contributing/setup.md) document, which will guide you in the process 😄 

I hope that helps!

**Comment by Yoplayer-1** [comment]
thanks @sergiou87
