### ISSUE TITLE
100% CPU usage while the update modal shows on macOS

### ISSUE THREAD

**Issue by alastaircoote** [desktop/desktop#11698]
### Describe the bug

Whenever the "install a new Helper" dialog is visible the GitHub Desktop app uses 100% CPU. I discovered this morning that my Macbook has been at 100% CPU overnight so presumably this doesn't ever stop, unless you do something with the modal (dismissing rather than saying yes works, either option returns you to normal CPU use)

### Version & OS

Version 2.6.4 on macOS Catalina

### Steps to reproduce the behavior

1. Wait for an update modal to appear
2. Do nothing
3. Observe 100% CPU

### Expected behavior

For the app to use zero (or near-zero) CPU when waiting on user response

### Actual behavior

100% CPU the entire time the dialog is active.

### Screenshots

<img width="602" alt="Screen Shot 2021-03-04 at 8 47 02 AM" src="https://user-images.githubusercontent.com/732835/109975460-a47eaa00-7cc8-11eb-883d-48bb84f71094.png">

### Additional context

I think a preferable solution here is that GH Desktop doesn't show the OS modal automatically. It's pretty disruptive. Can we see the app's own update notification first and have that trigger the OS modal when clicked?

**Comment by steveward** [comment]
Thanks for the report @alastaircoote. I can see you commented in https://github.com/desktop/desktop/issues/9901 where we are tracking this. I am going to close this issue out as a duplicate.
