### ISSUE TITLE
Commit Attribution Check is Case-Sensitive

### ISSUE THREAD

**Issue by velocity23** [desktop/desktop#11691]
### Describe the bug

The "commit misattribution" popup shows even when the email is a different case. 

### Version & OS

2.6.4
Windows 10 Professional

### Steps to reproduce the behavior

1. Change the case of your email in your git config
2. Open GitHub desktop

### Expected behavior

The capitalization of the email is ignored in GitHub desktop as it is on GitHub.

### Actual behavior

The capitalization is not ignored

### Screenshots

![image](https://user-images.githubusercontent.com/34199284/109908682-cd1e9800-7cf8-11eb-98a2-98d1d7d91e0f.png)

### Logs

N/A

### Additional context

I've had no issues with commit attribution on GitHub.

**Comment by sergiou87** [comment]
Thank you for this bug report @velocity23! I'll try to get this fixed ASAP 😄  Sorry for any inconvenience it could've caused.

**Comment by velocity23** [comment]
No worries at all, thanks for the speedy response!
