### ISSUE TITLE
App closes automatically as I tap to publish a repository, and my repository s not published.

### ISSUE THREAD

**Issue by Aniket200-ind** [desktop/desktop#11701]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by billygriffin** [comment]
Hi @Aniket200-ind, thanks for the issue! We're in the process of deploying a fix for this, but we're also hoping to get a bit more feedback that might help us diagnose what's causing it. Would you mind sharing whether there's anything worth nothing about your environment? Are you using any antivirus (if so, which one?) or proxy or anything like that?

Also, if we ship a fix to our beta channel, would you be willing to test that out in the next day or two to help us diagnose the problem and fix it?

**Comment by MephistonX** [comment]
I am experiencing the same issue,

No matter what I do, push, pull, commit, it seems the app crashes either instantly or a few seconds after

**Comment by billygriffin** [comment]
@MephistonX Sorry about that! Would you mind sharing more info from my question above? Also, there's a fix on the way that will be available in just a few minutes.

**Comment by MephistonX** [comment]
I'm pushing only basic changes (i only really work on art assets) 
I'm using Avast Free anti-virus, with no proxy 
I'm happy to use a beta 
Cheers

**Comment by MephistonX** [comment]
The update appears to have worked!

thank you

**Comment by billygriffin** [comment]
@MephistonX Great to hear and thank you! I'll respond here again when the beta is available that will help diagnose the problem better so we can make sure we fix it before it ships to production again. Should be in the next hour or two. This is a really rare error so we're grateful for your willingness to help out. ❤️

**Comment by sergiou87** [comment]
@Aniket200-ind @MephistonX Thank you for confirming that fix works! ❤️  As @billygriffin suggested, could you also try the latest beta (v2.6.6-beta1)? You can download it from here: https://github.com/desktop/desktop/#beta-channel

That beta will display an error message to you where the previous production build used to crash. It would be very helpful if you could try to reproduce those errors a few times and share the error messages here.

**Comment by billygriffin** [comment]
Hi @MephistonX (and @Aniket200-ind)! A few questions @sergiou87 had in the other issue dealing with the same problem. Any chance you could give us some insight into this and try out the beta version he linked above?

I haven't been able to reproduce that error on my end, but I was wondering if there is anything specific about your network configuration that could cause this issue, for example:

- Do you have any kind of firewall rule that could affect incoming TCP connections to 127.0.0.1? If you have a Firewall at all, could you try disabling it entirely and then testing the beta to see if that solves the issue?
- Does your machine have anything special around 127.0.0.1? Is your machine/network configured for IPv6 only by any chance?
- Do you have another machine where you can test the beta build and see if the problem occurs there too?

So far I think the most plausible option is the existence of a firewall blocking the connection. If you use Windows Defender, you're probably using Windows Firewall too, right?

**Comment by Aniket200-ind** [comment]
I am using NPAV antivirus. and as I have recently installed new hard disk
there are not many apps in it.

**Comment by Aniket200-ind** [comment]
You are welcome. I will also try and sorry that I have replied late I was
busy studying.

**Comment by Aniket200-ind** [comment]
OK I will check.

**Comment by Aniket200-ind** [comment]
I downloaded the beta app and as @billygriffin suggested I disabled antivirus and my repository was published. Thank you al for your help.

**Comment by sergiou87** [comment]
@Aniket200-ind @MephistonX We just deployed a new beta (2.7.0-beta2) which hopefully fix this issue entirely, even if you have an Antivirus. Would you mind enabling your antivirus again and trying it out? You can download it from https://github.com/desktop/desktop#beta-channel

**Comment by billygriffin** [comment]
Hi @Aniket200-ind and @MephistonX, we just wanted to follow up here to see if either of you would be willing to try out the latest beta with your antivirus enabled. We think the fix @sergiou87 made may help it to work even with the antivirus enabled, and we were hoping to get confirmation of that prior to shipping it to production again. Thanks!

**Comment by Aniket200-ind** [comment]
Done. It worked, Thanks sir for all the help you provided.

**Comment by Aniket200-ind** [comment]
Sure, It worked. Thank you for solving the problem.

**Comment by billygriffin** [comment]
That's great news, thanks for checking! We'll likely ship this to production again in the next few weeks. We really appreciate both of your help getting to the bottom of it.
