### ISSUE TITLE
Program crashed and broke permanently

### ISSUE THREAD

**Issue by dy** [desktop/desktop#11704]
### Describe the bug

Working with enterprise account, tried to push changes to remote branch - github hanged on pushing (long loading).
I decided not to wait for timeout and quit the app.
Now on opening app it shows sequence of alerts:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/300067/109993723-96398980-7cda-11eb-84c0-018095909660.png">
<img width="617" alt="image" src="https://user-images.githubusercontent.com/300067/109993744-9afe3d80-7cda-11eb-88cd-5fbc3522806d.png">
<img width="636" alt="image" src="https://user-images.githubusercontent.com/300067/109993760-9e91c480-7cda-11eb-8e70-31c9d36590aa.png">
<img width="634" alt="image" src="https://user-images.githubusercontent.com/300067/109993776-a2bde200-7cda-11eb-9cd3-6d79c70644d4.png">
<img width="632" alt="image" src="https://user-images.githubusercontent.com/300067/109993791-a6516900-7cda-11eb-9a76-4870ad28eb71.png">
<img width="624" alt="image" src="https://user-images.githubusercontent.com/300067/109993808-a9e4f000-7cda-11eb-8d7d-ced0497d4e3c.png">
<img width="619" alt="image" src="https://user-images.githubusercontent.com/300067/109993834-b1a49480-7cda-11eb-81d7-cd3f4919df1c.png">
<img width="621" alt="image" src="https://user-images.githubusercontent.com/300067/109993856-b79a7580-7cda-11eb-8f77-a6c466fb7af0.png">
<img width="630" alt="image" src="https://user-images.githubusercontent.com/300067/109993870-bc5f2980-7cda-11eb-9e99-310eca078bd4.png">
<img width="631" alt="image" src="https://user-images.githubusercontent.com/300067/109993886-bff2b080-7cda-11eb-9d01-50f988c05538.png">
<img width="628" alt="image" src="https://user-images.githubusercontent.com/300067/109993903-c41ece00-7cda-11eb-9862-97af6c757b76.png">
<img width="648" alt="image" src="https://user-images.githubusercontent.com/300067/109993915-c84aeb80-7cda-11eb-953a-81ca85d7cb82.png">
(and 10-20 more)

These errors return on blur/unblur app window as well. Relaunching app didn't help first time, second time it worked.

### Version & OS

BigSur 11.21, Github 2.6.3

### Steps to reproduce the behavior

Not sure...

**Comment by steveward** [comment]
Thanks for the report @dy. Could you upload the log file from GitHub Desktop so that I could get some more information about these errors? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by dy** [comment]
There's confidential info in logs, doesn't seem that I'm allowed to do that unfortunately. I see there Auth failed errors and repeated attempts.

**Comment by steveward** [comment]
Could you try performing a fresh installation of GitHub Desktop by following these steps?

Here's how to do that:

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `%AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that helps at all.

**Comment by dy** [comment]
@steveward it even helped just quitting and running app again, thanks. The bug report is rather pointing to some possible problem when force-quitting an app during long pull origin.

**Comment by steveward** [comment]
@dy glad to hear things are working now. Let us know if you run into this again.
