### ISSUE TITLE
Infinite "Update and Restart"

### ISSUE THREAD

**Issue by bwinklesky** [desktop/desktop#11705]
### Describe the bug

Infinite "Update and Restart".  Never updates the software but keeps showing me the dialog to update and restart.  

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Open App
2. Click on 'Update and Restart'
3. Rinse and Repeat

### Expected behavior

Update the software.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by bwinklesky** [comment]
Version 2.6.3

**Comment by billygriffin** [comment]
Hi @bwinklesky, thanks for the issue - that sounds frustrating. Would you mind sharing what version of GitHub Desktop you're on from "About GitHub Desktop" and what OS and version are you on? Also, is there a "What's new?" link as well, and if so, what shows up when you click on that? Thanks!

**Comment by bwinklesky** [comment]
It's trying to install version 2.6.5 (from the What's New link)

**Comment by billygriffin** [comment]
Agh, sorry @bwinklesky. This is the first time I've ever seen that happen and not really sure what's causing it. 

Can you try reinstalling GitHub Desktop by following these steps?

1. Close GitHub Desktop
2. Remove all of the files in `%LOCALAPPDATA%\GitHubDesktop\`
3. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that doesn't get things working.

**Comment by bwinklesky** [comment]
This is on a Mac and not sure there is a LOCALAPPDATA.  I moved the .app to a different location than the Applications folder and still no luck. 

Perhaps you can add a way to not do update checks?  I think a manual update would be better for Mac.  I had issues with a "helper" (lots of others have this issue too if you scan the issues) file always wanting my admin credentials.  That went away after I uninstalled and reinstalled GitHub, but now it just won't update.

**Comment by steveward** [comment]
@bwinklesky you can find the GitHub Desktop application files on macOS in `~/Library/Application Support/GitHub Desktop`. Try deleting that directory and let us know if that doesn't get things working.

> I had issues with a "helper" (lots of others have this issue too if you scan the issues) file always wanting my admin credentials. That went away after I uninstalled and reinstalled GitHub, but now it just won't update.

That's normally caused by a permission issue -- see [this comment]( https://github.com/desktop/desktop/issues/3616#issuecomment-400371047) for how to resolve this.

**Comment by bwinklesky** [comment]
That doesn’t get things working.

**Comment by steveward** [comment]
@bwinklesky could you share the log file from GitHub Desktop? That may give some more information. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by bwinklesky** [comment]
Here is a clean log.

Checked for updates and hit the “Quit and Install” button.  It quits, but nothing after that.

**Comment by dxdc** [comment]
I've had identical issues for at least 10 months on 10.15/10.16 macOS. I've tried a lot of options within the Github app itself, which don't work (e.g., trying to more forcibly check for updates, then update&restart, etc.). I've also just manually deleted the app from the Applications folder, and downloaded/installed a new one.

None of this works to fix the issue. Log files are unhelpful. Here's a very typical one, after restarting multiple times to update.

I have resorted to just manually downloading/updating every time there's a new update.

```
2021-03-06T15:13:39.813Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.465s)
2021-03-06T15:13:48.042Z - info: [ui] [AppStore] loading 39 repositories from store
2021-03-06T15:13:48.043Z - info: [ui] [AppStore] found account: dxdc (dxdc)
2021-03-06T15:13:50.860Z - info: [ui] launching: 2.6.4 (Mac OS 11.2.1)
2021-03-06T15:13:50.861Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2021-03-06T15:17:38.702Z - info: [ui] [AppStore] loading 39 repositories from store
2021-03-06T15:17:38.703Z - info: [ui] [AppStore] found account: dxdc (dxdc)
2021-03-06T15:17:41.399Z - info: [ui] launching: 2.6.4 (Mac OS 11.2.1)
2021-03-06T15:17:41.399Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2021-03-06T15:17:50.603Z - info: [ui] [AppStore] loading 39 repositories from store
2021-03-06T15:17:50.604Z - info: [ui] [AppStore] found account: dxdc (dxdc)
2021-03-06T15:17:51.691Z - info: [ui] Executing getRemotes: git remote -v (took 1.059s)
2021-03-06T15:17:51.695Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.023s)
2021-03-06T15:17:53.813Z - info: [ui] launching: 2.6.4 (Mac OS 11.2.1)
2021-03-06T15:17:53.814Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
```

**Comment by WinkelCode** [comment]
Hi, I have a similar issue, Windows 10, GitHub Desktop 2.6.2 (currently, because it won't update, I'll do it manually in a bit). Every time I had to go an manually download the installer and run it to update GitHub Desktop.

It just gets stuck on "Downloading update...", I can see that update.exe is downloading about 75 MB and then... nothing. The app still shows "Downloading update...".

**Comment by steveward** [comment]
@martinsstuff any chance you are running antivirus/security software other than the standard Windows Defender that could be preventing the update process from completing? Sometimes when we ship updates with binaries that have changes it can trigger antivirus software.

**Comment by WinkelCode** [comment]
Nope, just using Windows Defender. I also haven't received any notifications that would indicate it took any actions.

Good news however is that after testing just now, it did seem to work, though it took an unusually long (compared to similar applications like Discord or Google Chrome) time. About 2 minutes.

I updated from 2.6.6 to 2.7.1

In total:

`2021-04-01 18:48:39> Program: Starting Squirrel Updater: --checkForUpdate https://central.github.com/api/deployments/desktop/desktop/latest?version=2.6.6&env=production`

to

`2021-04-01 18:50:41> ApplyReleasesImpl: Starting fixPinnedExecutables`

2 minutes and 2 seconds.

---

Looking through the log file (SquirrelSetup.log), the slowest tasks were these:

1.

`2021-04-01 18:49:10> DeltaPackageBuilder: Repacking into full package: C:\Users\___\AppData\Local\GitHubDesktop\packages\GitHubDesktop-2.7.0.nupkg`

Taking 42 seconds

2.

`2021-04-01 18:50:04> DeltaPackageBuilder: Repacking into full package: C:\Users\___\AppData\Local\GitHubDesktop\packages\GitHubDesktop-2.7.1.nupkg`

Taking 23 seconds

3.

`2021-04-01 18:50:29> LogHost: Rigging execution stub for GitHubDesktop_ExecutionStub.exe to C:\Users\___\AppData\Local\GitHubDesktop\GitHubDesktop.exe`

Taking 11 seconds.

---

```
FileDownloader: Downloading url: https://central.github.com/api/deployments/desktop/desktop/latest/RELEASES?version=2.6.6&env=production&id=GitHubDesktop&localVersion=2.6.6&arch=amd64
FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-2.7.1-delta.nupkg
FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-2.7.0-delta.nupkg
```

Only took 9 seconds to complete (as I would expect), though about two minutes to extract a 9 second download seems like there is something not working right...

Edit: I think when I previously had the slow/frozen update bug I left it open for longer than 2 minutes, back then it was a 72mb download, in this case only about 2.8mb (if my network monitoring software is correct).

**Comment by ghost** [comment]
I have this update  issue on macOS Catalina. I originally thought it was a Gatekeeper issue. I have been downloading the updates manually as well.

```
xattr -l /Applications/GitHub\ Desktop.app
com.apple.quarantine: 01c3;60492eb5;Safari;E6C0510B-8E98-421F-A67F-506900D02B2C
```
Removing the Gatekeeper rule for this app didn't stick. The rule comes back.

```
xattr -d /Applications/GitHub\ Desktop.app

xattr -l /Applications/GitHub\ Desktop.app
com.apple.quarantine: 01c3;60492eb5;Safari;E6C0510B-8E98-421F-A67F-506900D02B2C
```

Checking Gatekeeper rules shows a rule:
```
$ spctl --list | grep git
identifier "com.github.GitHubClient" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = VEKTX9H2N7
```
App package is signed properly
```
codesign -dvvvv /Applications/GitHub\ Desktop.app
Executable=/Applications/GitHub Desktop.app/Contents/MacOS/GitHub Desktop
Identifier=com.github.GitHubClient
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20500 size=1763 flags=0x10000(runtime) hashes=46+5 location=embedded
VersionPlatform=1
VersionMin=657920
VersionSDK=720896
Hash type=sha256 size=32
CandidateCDHash sha1=9eb3927ddf63861f8b8a70a692d1b87e41e4120d
CandidateCDHashFull sha1=9eb3927ddf63861f8b8a70a692d1b87e41e4120d
CandidateCDHash sha256=f7bef762554f2dde6f93a6a08d2f1f2247939839
CandidateCDHashFull sha256=f7bef762554f2dde6f93a6a08d2f1f22479398391b342e0bb544b7ae873170b5
Hash choices=sha1,sha256
CMSDigest=adee957eb2e6e3be101850ee888d1783db588331f429e12a0f54421c6621b03f
CMSDigestType=2
Page size=4096
CDHash=f7bef762554f2dde6f93a6a08d2f1f2247939839
Signature size=9031
Authority=Developer ID Application: GitHub (VEKTX9H2N7)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Mar 30, 2021 at 3:38:29 AM
Info.plist entries=31
TeamIdentifier=VEKTX9H2N7
Runtime Version=11.0.0
Sealed Resources version=2 rules=13 files=1440
Internal requirements count=1 size=184
```

**Comment by dxdc** [comment]
I've struggled with this issue for years. I think I may have stumbled upon a fix, curious if this will work for others as well: https://github.com/desktop/desktop/issues/12818#issuecomment-1046915246

**Comment by sergiou87** [comment]
Hopefully solved with @dxdc 's solution (❤️ ). If it happens again, please share the contents of your `~/Library/Caches/com.github.GitHubClient.ShipIt` folder for further investigation 🙏
