### ISSUE TITLE
It's not possible to show stashed changes even if there are some

### ISSUE THREAD

**Issue by ijacek** [desktop/desktop#11709]
### Describe the bug

I have stashed changes in the repo but the action "Show stashed changes" is disabled.

### Version & OS

win 10, Version 2.6.5

### Steps to reproduce the behavior

1. have some uncommited changes 
2. stash them
3. it's possible to view and restore the stash
4. checkout another branch
5. it's not possible to view and restore the stash anymore
6. if I return to the original branch, the stash is there

### Expected behavior

I would like to have the stash available in step 5. in order to bring some changes to another branch and then return back to the original one.

### Additional context

Maybe it's intended to avoid some issues for unexperienced users but I think my workflow is valid. I use it when I have something unrelated in progress and I want to put it to another (newly created) branch and then return to the previous stuff. Now I have to go to cmdline and run "git stash pop" in step 5.

**Comment by tidy-dev** [comment]
@ijacek Thank you for the report. This is the intended behavior. We keep stashes in relation to their branches. Thus, in your scenario if you checked out the branch you stashed them on you could pop them there. 

However, there is a built in flow to accomplish your goal. If you have uncommitted changes that you would like on another branch. Go ahead and checkout another branch, you will receive this popup.
![image](https://user-images.githubusercontent.com/75402236/110104080-b28a0480-7d74-11eb-9390-b61adaee9f01.png)

Just select "Bring my changes to {branch-name}" and your changes list will remain when you switch branches.
