### ISSUE TITLE
When opening some large repositories switching focus to and from Github Desktop new instances of "Git for Windows"

### ISSUE THREAD

**Issue by treacherousfiend** [desktop/desktop#11707]
### Describe the bug

On one very large repository of mine (approximately 10GB of mostly binary files) when focus is given to Github Desktop, new instances of Git for Windows are added.
This includes the built-in git.exe as well as Windows' conhost.exe

Additonal notes:
Many of these new instances do not close when Github Desktop is closed, and require to be force closed

### Version & OS

Github Desktop version 2.6.5
Windows 10 Home 20H2 build 19042.804

### Steps to reproduce the behavior

1. Open Github Desktop
2. Open a very large repository
3. Switch focus to another program
4. Give focus back to Github Desktop again

### Expected behavior

Github Desktop should not be creating new instances of git.exe and conhost.exe without removing the old ones

### Actual behavior

Github Desktop creates more and more instances of these programs, causing ridiculous CPU and RAM usage

### Screenshots

![image](https://user-images.githubusercontent.com/46549454/110077641-6b087600-7d7e-11eb-8181-6acbecf2eedf.png)

### Logs

Unfortunately logs did not provide any info.

### Additional context

The repo that causes this issue is approximately 10 GB with over 20k binary files, this might simply be an issue with loading large amounts of (albeit small) files.

**Comment by steveward** [comment]
Thanks for the report @treacherousfiend. This looks similar to what was reported in https://github.com/desktop/desktop/issues/9675. 

With a repository of that size you are likely to run into performance issues. Are you using Git LFS to manage the binary files in this repository? Have you tried disabling background fetching by going to `File` > `Options` > `Advanced`?

**Comment by treacherousfiend** [comment]
The only Git program I am using is Github Desktop.
Disabling background fetching did not fix or mitigate the issue at all.

I'm not particularly surprised that a large repository would have issues, but it seems odd to me that it would cause Git processes to not be closed.

**Comment by steveward** [comment]
@treacherousfiend following up here -- in https://github.com/desktop/dugite/issues/385 there is a report of Git LFS spawning processes, similar to what you are seeing. Can you confirm if this specific repository is using Git LFS? GitHub Desktop includes Git LFS so if you've enabled it for this repository that could be a potential cause.
