### ISSUE TITLE
GitHub Desktop fails to clone private repository

### ISSUE THREAD

**Issue by fireFerry** [desktop/desktop#11708]
### Describe the bug

When I try to clone a private repository, I get the error: `Cloning into 'C:\Users\*****\Documents\GitHub\*******'...
error: unable to read askpass response from 'C:\Users\******\AppData\Local\GitHubDesktop\app-2.6.5\resources\app\static\ask-pass-trampoline.bat'
fatal: could not read Username for 'https://github.com': terminal prompts disabled`
I've tried to reinstall GitHub Desktop & Git multiple times, without succeeding. I'm sure I'm logged into GitHub Desktop, That I've got access to the repository, cause I'm seeing it in the clone screen. I'm also 100% sure that the repository isn't archived.

### Version & OS

GitHub Desktop: Version 2.6.5
OS: Windows (OS Build 19041.804)

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. Go to `File` > `Clone repository`
3. Choose a private repository
4. Click clone and see error

### Expected behavior

The repository should be cloned to the selected path.

### Actual behavior

The repository doesn't clone and an error pops up.

### Screenshots

![image](https://user-images.githubusercontent.com/61279925/110092413-df9cde00-7d99-11eb-83b8-938c9a18d28f.png)

### Logs

[2021-03-05.desktop.production.log](https://github.com/desktop/desktop/files/6089375/2021-03-05.desktop.production.log)

**Comment by sergiou87** [comment]
Hello @fireFerry! 👋 

We're very sorry about this problem. It's a known issue documented here: https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors

Right now we're experimenting with a new solution that you can try out by just installing the beta version from https://github.com/desktop/desktop#beta-channel

Please, let me know if the beta version works!

**Comment by fireFerry** [comment]
Alright will try that, sorry for opening an unnecessary issue, but I just couldn't find it after hours of research

**Comment by sergiou87** [comment]
No worries! Sometimes it's hard to find info even if it's a frequent issue, but we're here for that and very happy to help! ❤️

**Comment by fireFerry** [comment]
Just an update, The beta version seems to work fine!
