### ISSUE TITLE
Https remote command not founf in git

### ISSUE THREAD

**Issue by rajeshk07** [desktop/desktop#11719]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by sergiou87** [comment]
Hi @rajeshk07! 👋  Could you provide more context about the issue? Filling the template would be very helpful, thank you! ❤️
