### ISSUE TITLE
GitHub Desktop does not recognize  other IDE's

### ISSUE THREAD

**Issue by Liam-Walton19074402** [desktop/desktop#11710]
### Describe the bug

First time install of GitHub Desktop and it only recognizes Notepad++, I would like to use my other IDE's but I am unable to add them. https://github.community/t/external-editor/1808 shows other people with the same issue.

### Version & OS

GitHub Desktop 2.6.5
OS: Win 10 20H219042.804

### Steps to reproduce the behavior

Install a few IDE's
Install GitHub Desktop
Go to File/Options/Integrations
Try and select another IDE

### Expected behavior

Able to select from the various IDE's on the system

### Actual behavior

Only able to select from one, and only one IDE on the system.

### Screenshots
![image](https://user-images.githubusercontent.com/59876753/110095329-b75eb080-7d94-11eb-9b15-4edb12c9a502.png)
### Logs

[2021-03-05.desktop.production.log](https://github.com/desktop/desktop/files/6089489/2021-03-05.desktop.production.log)

### Additional context

All IDE's were installed BEFORE installing Desktop Client

**Comment by sergiou87** [comment]
Hi @Liam-Walton19074402 !

Unfortunately NetBeans is not supported, but you can add support for it following the instructions here: https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md

Regarding Atom, it is supported, I just installed it directly from https://atom.io and it works as expected:

![image](https://user-images.githubusercontent.com/1083228/110099075-2fcb6e80-7da1-11eb-8c2b-569d5b832335.png)

Maybe uninstalling Atom and installing it again from https://atom.io could fix the issue?
