### ISSUE TITLE
GitHub Desktop does not respect pull.rebase=true

### ISSUE THREAD

**Issue by aroman** [desktop/desktop#11718]
### Describe the bug

My Git config is set to `pull.rebase=true` (from `git config -l`), but GitHub Desktop does not respect this config and creates merge commits instead of performing an automatic rebase when pulling new commits.

### Version & OS

Version 2.6.5, Windows 10 latest stable version

### Steps to reproduce the behavior

1. Push commits to remote branch from another machine
2. On local machine with unpushed local commits, pull
3. A merge commit is automatically created

### Expected behavior

Instead of a merge commit being created, the local commits are rebased on top of newly pulled commits from remote branch.

### Actual behavior

 A merge commit is automatically created

### Additional context

It seems this supposed to work, but it doesn't, hence this bug. https://github.com/desktop/desktop/issues/3422#issuecomment-467950522

Here's another user reporting the same issue in a comment: https://github.com/desktop/desktop/pull/6893#issuecomment-782010812

**Comment by sergiou87** [comment]
Hi @aroman! Thanks for your report ❤️ 

I just tried this in both macOS and Windows and it works as expected for me. Do you at least see the "Pull with rebase" text in the button?

![image](https://user-images.githubusercontent.com/1083228/110302653-c5613b00-7ff9-11eb-937b-5d2e83ebf29b.png)

```bash
$ git config -l | grep pull
pull.rebase=true
```

**Comment by aroman** [comment]
Thanks for the reply, Sergio! I do not see that UI, but I can confirm that `git config -l` shows `pull.rebase=true` under both WSL2 and git via PowerShell.

**Comment by aroman** [comment]
Perhaps there is some other third git config that Desktop is using?

**Comment by sergiou87** [comment]
I don't think so… 🤔 

The app just runs `git config` in the repo folder 😕 

If you run `git config -l | grep pull` do you see anything else? Maybe there is a `pull.rebase=true` in the global config and a `pull.rebase=false` in the repo's local config? I can't think of other option at this point 😖
