### ISSUE TITLE
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: Unknown error code (err 8) fatal: the remote end hung up unexpectedly

### ISSUE THREAD

**Issue by formatc2013** [desktop/desktop#11722]
### Describe the bug

Can't publish repo.

### Version & OS

Version 2.6.5 - Win10

### Logs

[2021-03-06.desktop.production.log](https://github.com/desktop/desktop/files/6095229/2021-03-06.desktop.production.log)

### Additional context

abc /d/JanekD/UE4Projects/Clean (main)
$ git push origin main
Uploading LFS objects: 100% (589/589), 1.4 GB | 0 B/s, done.
Enumerating objects: 2373, done.
Counting objects: 100% (2373/2373), done.
Delta compression using up to 24 threads
Compressing objects: 100% (2323/2323), done.
fatal: Out of memory, malloc failed (tried to allocate 2263917 bytes)
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
error: failed to push some refs to 'https://github.com/formatc2013/Clean.git'

abc /d/JanekD/UE4Projects/Clean (main)
$ git push origin main
Uploading LFS objects: 100% (589/589), 1.4 GB | 0 B/s, done.
Enumerating objects: 2374, done.
Counting objects: 100% (2374/2374), done.
Delta compression using up to 24 threads
Compressing objects: 100% (2324/2324), done.
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: Unknown error code (err 8)
fatal: the remote end hung up unexpectedly
Writing objects: 100% (2374/2374), 2.46 GiB | 1.22 MiB/s, done.
Total 2374 (delta 358), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

abc /d/JanekD/UE4Projects/Clean (main)
$ git push origin main
Uploading LFS objects: 100% (589/589), 1.4 GB | 0 B/s, done.
Enumerating objects: 2374, done.
Counting objects: 100% (2374/2374), done.
Delta compression using up to 24 threads
Compressing objects: 100% (2324/2324), done.
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: Unknown error code (err 8)
fatal: the remote end hung up unexpectedly
Writing objects: 100% (2374/2374), 2.46 GiB | 1.18 MiB/s, done.
Total 2374 (delta 359), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

abc /d/JanekD/UE4Projects/Clean (main)
**$ git config http.postBuffer 524288000**

abc /d/JanekD/UE4Projects/Clean (main)
$ git push origin main
Uploading LFS objects: 100% (589/589), 1.4 GB | 0 B/s, done.
Enumerating objects: 2374, done.
Counting objects: 100% (2374/2374), done.
Delta compression using up to 24 threads
Compressing objects: 100% (2324/2324), done.
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: Unknown error code (err 8)
fatal: the remote end hung up unexpectedly
Writing objects: 100% (2374/2374), 2.46 GiB | 1.29 MiB/s, done.
Total 2374 (delta 358), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

abc /d/JanekD/UE4Projects/Clean (main)
**$ git config --global http.version HTTP/1.1**

abc /d/JanekD/UE4Projects/Clean (main)
$ git push origin main
Uploading LFS objects: 100% (672/672), 1.9 GB | 1.4 MB/s, done.
Enumerating objects: 2512, done.
Counting objects: 100% (2512/2512), done.
Delta compression using up to 24 threads
Compressing objects: 100% (2459/2459), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
Writing objects: 100% (2512/2512), 2.46 GiB | 1.33 MiB/s, done.
Total 2512 (delta 392), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

Nemesis02@DESKTOP-LQFU5P0 MINGW64 /d/JanekD/UE4Projects/Clean (main)
**$ git config --global http.postBuffer 157286400**

Nemesis02@DESKTOP-LQFU5P0 MINGW64 /d/JanekD/UE4Projects/Clean (main)
$ git push origin main
Uploading LFS objects: 100% (706/706), 2.0 GB | 325 KB/s, done.
Enumerating objects: 2595, done.
Counting objects: 100% (2595/2595), done.
Delta compression using up to 24 threads
Compressing objects: 100% (2533/2533), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
Writing objects: 100% (2595/2595), 2.46 GiB | 1.15 MiB/s, done.
Total 2595 (delta 416), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

**Comment by steveward** [comment]
@formatc2013 it looks like you are trying to push a large amount of changes and are hitting out of memory or timeout errors. Are there large files in this repository that could be versioned using [Git LFS](https://git-lfs.github.com/)?

**Comment by Avemorris** [comment]
What do i need to do?

**Comment by MANOJ1245723** [comment]
Change your network
