### ISSUE TITLE
Rename Repo names

### ISSUE THREAD

**Issue by rigorojas** [desktop/desktop#11721]
### Describe the feature or problem you’d like to solve

When I add a repo they are all name by the name of the directory they live in. This leads to all my repos being named "www" - I have 17 of them. 

### Proposed solution

Let me use an arbitrary name 

### Additional context

This is what they look like now.
![image](https://user-images.githubusercontent.com/4935930/110192799-3976c580-7de5-11eb-85e3-076ff1b3a79c.png)

**Comment by sergiou87** [comment]
Thanks for your suggestion @rigorojas! ❤️ 

I see other users have already requested this, like #7856, so I recommend you to subscribe to that issue. I will close this one in favor of #7856 😄
