### ISSUE TITLE
Image diff with small images makes the ui overlap

### ISSUE THREAD

**Issue by TomMalbran** [desktop/desktop#11729]
### Describe the bug

On the image diff UI if the images are too small the texts overlap

### Version & OS

GitHub Desktop Version 2.6.5
OS: macOS Catalina 10.15.3

### Steps to reproduce the behavior

1. Commit a small image. Mine was 20 by 20px
2. Replace the image with another small image. I used the same size as before
3. Check the diff between both images

### Expected behavior

I expect the image container to have a min width to avoid overlaps and show more space for the texts. 

### Actual behavior

Some of the texts overlaps and is hard to read all the text

### Screenshots

![Screen Shot 2021-03-07 at 20 44 24](https://user-images.githubusercontent.com/1299997/110259518-d45ad580-7f86-11eb-9bed-a17b6feea30a.png)

**Comment by sergiou87** [comment]
Hi @TomMalbran! Thank you for your report 😄 ❤️ 

Some other user reported this very same bug in #11404, so I recommend you to subscribe there since I'm gonna close this one in favor of #11404.
