### ISSUE TITLE
GitHub Desktop launches with unresponsive white screen as administrator

### ISSUE THREAD

**Issue by paulvzyl** [desktop/desktop#11739]
### Describe the bug

When launching GitHub Desktop as administrator only a white screen is displayed.

### Version & OS

GitHub Desktop Version 2.6.5
Windows 10 1809 (17763.1757)

### Steps to reproduce the behavior

1. Launch GitHub desktop as administrator
2. Nothing happens (but two processes show up in Task Manager)
2. Launch GitHub desktop as administrator again
3. White window is displayed. 

### Expected behavior

The app should launch normally.

### Actual behavior

The app is displaying only an empty white window. Can be maximized with F11 and closed with ALT+F4

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

[2021-03-08.desktop.production.log](https://github.com/desktop/desktop/files/6102645/2021-03-08.desktop.production.log)

### Additional Context

Started happening after upgrading to v2.6.3. I can still launch it when not running it as administrator. I have also tried deleting everything in %APPDATA%\GitHub Desktop\ as well as re-installing.

**Comment by sergiou87** [comment]
Thanks for the report @paulvzyl! ❤️ 

It's weird… it works perfectly fine for me 🤔 

Have you tried in another Windows computer to see if you can reproduce the same behavior?

**Comment by paulvzyl** [comment]
It is also affecting my colleague, but we have the same PC and Operating System setup.

**Comment by jackprosser** [comment]
Could be related to https://github.com/desktop/desktop/issues/11219, although different OS. The app has become so unusable I've uninstalled it there's a fix.

**Comment by alexarena** [comment]
I'm seeing the same thing on my M1 Macbook Pro. Like Jack said, thinking this could be the same underlying issue as #11219.

**Comment by steveward** [comment]
@jackprosser are you still encountering this issue? Have you tried deleting `%LocalAppData%\GitHubDesktop` and reinstalling to see if that fixes things?

**Comment by jackprosser** [comment]
> @jackprosser are you still encountering this issue? Have you tried deleting `%LocalAppData%\GitHubDesktop` and reinstalling to see if that fixes things?

It's an Apple M1 issue. I've already tried deleting all the data but seemed to come back. Trying this now.

Arm Build
[#11969 (comment)](https://github.com/desktop/desktop/pull/11969#issuecomment-823987465)

**Comment by steveward** [comment]
@jackprosser apologies, I meant to mention @paulvzyl the original poster since he is running Windows.
