### ISSUE TITLE
push tags

### ISSUE THREAD

**Issue by Goddard** [desktop/desktop#11738]
It would be cool if I could create tags on a commit and push the tags to my github repo.

Currently if I want to do this with a GUI I can use gitg which has the tags creation feature, but I still have to manually git push --tags.

**Comment by steveward** [comment]
@Goddard thanks for the issue. GitHub Desktop supports tags. See [this article](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-tags) for steps on how to work with tags. I hope that helps!

**Comment by Goddard** [comment]
Thanks that is cool I can create them.  

Maybe you can tell me how do I actually push them then?

The article says "create, push, and view tags", but in the headings all I see are create view and delete. 

Much appreciate.

Or are old tags not pushed?  Do I have to create the commit then create the tag and then push?  It doesn't do it after it is already pushed then.
