### ISSUE TITLE
Autosave not working

### ISSUE THREAD

**Issue by owenbrownzc** [desktop/desktop#11742]
### Describe the bug
I'm using the auto-save and it doesn't work.

### Version & OS
I'm on macOS 11.2.2 (20D80)
Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.
I'm on Atom 1.54.0 x.64

### Steps to reproduce the behavior
1. Download atom.
2. Install the autosave package.
3. Enable the package.
4. Edit a file
5. Leave the window
6. The file doesn't save (!!!)
7. Quit atom
8. The file still isn't saved!

### Expected behavior
It should save when I close Atom or change focus.

### Actual behavior
It doesn't save!

**Comment by steveward** [comment]
@owenbrownzc this issue tracker is for GitHub Desktop. Please open an issue in the [Atom issue tracker](https://github.com/atom/atom/issues) for assistance with Atom.
