### ISSUE TITLE
"Ignore File (add to .gitignore)" not working

### ISSUE THREAD

**Issue by dstrube1** [desktop/desktop#11749]
### "Ignore File (add to .gitignore)" not working

Adding a file to .gitignore updates .gitignore, but doesn't remove the ignored file from list of files to be committed. If updating .gitignore doesn't remove the ignored file from list of files to be committed, then what is the point of updating .gitignore?

### Version & OS

GitHub Desktop version 2.6.5
macOS version 11.2.3

### Steps to reproduce the behavior

1. Go to list of files to be committed, find one that you want to exclude from the list for all future commits for this repo.
2. Right-Click on the file and select "Ignore File (add to .gitignore)"
3. Note that .gitignore is updated.
4. Note that the "ignored" file is still in the list of files to be committed.
5. BONUS: Commit the .gitignore file. Close and reopen GitHub Desktop. Find the file still waiting to be committed, right click on it again, select "Ignore File (add to .gitignore)" again, note the duplicate entry added to .gitignore.

### Expected behavior

1. Go to list of files to be committed, find one that you want to exclude from the list for all future commits for this repo.
2. Right-Click on the file and select "Ignore File (add to .gitignore)"
3. .gitignore is updated.
4. The ignored file is no longer in the list of files to be committed.

### Actual behavior

(See Steps to reproduce the behavior)

### Screenshot
<img width="955" alt="Screen Shot 2021-03-09 at 13 37 40" src="https://user-images.githubusercontent.com/7396679/110520728-dafb6100-80dc-11eb-9f27-ddad8f074c59.png">

**Comment by steveward** [comment]
@dstrube1 thanks for the issue. If the file has been previously committed to your repository it needs to be removed in order to ignore it. You'll need to run this command from the command line:

`git rm --cached .DS_Store`

You should then be able to ignore the file. 

>Commit the .gitignore file. Close and reopen GitHub Desktop. Find the file still waiting to be committed, right click on it again, select "Ignore File (add to .gitignore)" again, note the duplicate entry added to .gitignore.

This is being tracked in https://github.com/desktop/desktop/issues/2537. I'm going to close this issue out, but let me know if you have any further questions.

**Comment by zenmanenergy** [comment]
This solution sucks! Fix the app.

**Comment by ManyLattice** [comment]
> This solution sucks! Fix the app.

Try this:

```
git rm -rf --cached .
git add .
```

**Comment by karoklinik** [comment]
> > This solution sucks! Fix the app.
> 
> Try this:
> 
> ```
> git rm -rf --cached .
> git add .
> ```

Thanks that helped! :)

**Comment by Alex-888888** [comment]
> > This solution sucks! Fix the app.
> 
> Try this:
> 
> ```
> git rm -rf --cached .
> git add .
> ```

It helps too ;)
