### ISSUE TITLE
Tree

### ISSUE THREAD

**Issue by farukyo** [desktop/desktop#11743]
### Describe the feature or problem you’d like to solve

We need to see a project tree on windows, like source tree or git kraken.

### Proposed solution

Will provide a big picture view to the developer and a little bit of gui usefulness.

Can be a view commit tree button or something on top.

**Comment by steveward** [comment]
Thanks for the feedback @farukyo. You can follow along in https://github.com/desktop/desktop/issues/9452 for updates about a commit graph in GitHub Desktop. Please feel free to add any additional feedback you may have there.

**Comment by farukyo** [comment]
Thank you so much, sorry i wasted your time a little

**Comment by farukyo** [comment]
> 
> 
> Thanks for the feedback @farukyo. You can follow along in #9452 for updates about a commit graph in GitHub Desktop. Please feel free to add any additional feedback you may have there.

can you delete the issue thank you so much
