### ISSUE TITLE
Image difference is not correctly displayed

### ISSUE THREAD

**Issue by ayoubkhan558-zz** [desktop/desktop#11741]
### Describe the bug
I replaced a image with lower height and width, and when Github desktop show me diff width, height and size text are not correctly displayed.

### Version & OS
Windows 10, Version 2.6.5

### Screenshots
![image](https://user-images.githubusercontent.com/20210961/110367403-7b2d8900-7ffc-11eb-9ccf-348bb9e07773.png)
 
### Possible Solution
When replacing images of low width and height Width, Height and Size should be wrapped on new line.

**Comment by sergiou87** [comment]
Hi @ayoubkhan558! Thank you for your report 😄 

Some other user reported this very same bug in #11404, so I recommend you to subscribe there since I'm gonna close this one in favor of #11404.
