### ISSUE TITLE
error: RPC failed; curl 52 Empty reply from server

### ISSUE THREAD

**Issue by raikm** [desktop/desktop#11751]
### Describe the bug

After I wanted to upload an image for my docs I have following issue: 

Enumerating objects: 56, done.
Counting objects: 100% (36/36), done.
Delta compression using up to 4 threads
Compressing objects: 100% (23/23), done.
Writing objects: 100% (24/24), 1.06 MiB | 57.02 MiB/s, done.
Total 24 (delta 12), reused 0 (delta 0), pack-reused 0
error: RPC failed; curl 52 Empty reply from server
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
Everything up-to-date

### What I tried

- git config --global http.postBuffer 524288000

- git config --global http.postBuffer 157286400

- git config --global core.compression 0

- git config http.sslVersion tlsv1.2

- change network connection

### Version & OS

Version 2.6.5, Mac OS Big Sur

### Logs

2021-03-09T19:12:42.099Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: homepanorama - raikm (has token)
2021-03-09T19:12:44.527Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 2.381s)
2021-03-09T19:12:44.529Z - error: [ui] `git -c credential.helper= -c protocol.version=2 push origin master:master --progress` exited with an unexpected code: 1.
stderr:
Enumerating objects: 56, done.
Counting objects:   2% (1/36)
Counting objects:   5% (2/36)
Counting objects:   8% (3/36)
Counting objects:  11% (4/36)
Counting objects:  13% (5/36)
Counting objects:  16% (6/36)
Counting objects:  19% (7/36)
Counting objects:  22% (8/36)
Counting objects:  25% (9/36)
Counting objects:  27% (10/36)
Counting objects:  30% (11/36)
Counting objects:  33% (12/36)
Counting objects:  36% (13/36)
Counting objects:  38% (14/36)
Counting objects:  41% (15/36)
Counting objects:  44% (16/36)
Counting objects:  47% (17/36)
Counting objects:  50% (18/36)
Counting objects:  52% (19/36)
Counting objects:  55% (20/36)
Counting objects:  58% (21/36)
Counting objects:  61% (22/36)
Counting objects:  63% (23/36)
Counting objects:  66% (24/36)
Counting objects:  69% (25/36)
Counting objects:  72% (26/36)
Counting objects:  75% (27/36)
Counting objects:  77% (28/36)
Counting objects:  80% (29/36)
Counting objects:  83% (30/36)
Counting objects:  86% (31/36)
Counting objects:  88% (32/36)
Counting objects:  91% (33/36)
Counting objects:  94% (34/36)
Counting objects:  97% (35/36)
Counting objects: 100% (36/36)
Counting objects: 100% (36/36), done.
Delta compression using up to 4 threads
Compressing objects:   4% (1/23)
Compressing objects:   8% (2/23)
Compressing objects:  13% (3/23)
Compressing objects:  17% (4/23)
Compressing objects:  21% (5/23)
Compressing objects:  26% (6/23)
Compressing objects:  30% (7/23)
Compressing objects:  34% (8/23)
Compressing objects:  39% (9/23)
Compressing objects:  43% (10/23)
Compressing objects:  47% (11/23)
Compressing objects:  52% (12/23)
Compressing objects:  56% (13/23)
Compressing objects:  60% (14/23)
Compressing objects:  65% (15/23)
Compressing objects:  69% (16/23)
Compressing objects:  73% (17/23)
Compressing objects:  78% (18/23)
Compressing objects:  82% (19/23)
Compressing objects:  86% (20/23)
Compressing objects:  91% (21/23)
Compressing objects:  95% (22/23)
Compressing objects: 100% (23/23)
Compressing objects: 100% (23/23), done.
Writing objects:   4% (1/24)
Writing objects:   8% (2/24)
Writing objects:  12% (3/24)
Writing objects:  16% (4/24)
Writing objects:  20% (5/24)
Writing objects:  25% (6/24)
Writing objects:  29% (7/24)
Writing objects:  33% (8/24)
Writing objects:  37% (9/24)
Writing objects:  41% (10/24)
Writing objects:  45% (11/24)
Writing objects:  50% (12/24)
Writing objects:  54% (13/24)
Writing objects:  58% (14/24)
Writing objects:  62% (15/24)
Writing objects:  66% (16/24)
Writing objects:  70% (17/24)
Writing objects:  75% (18/24)
Writing objects:  79% (19/24)
Writing objects:  83% (20/24)
Writing objects:  87% (21/24)
Writing objects:  91% (22/24)
Writing objects:  95% (23/24)
Writing objects: 100% (24/24)
Writing objects: 100% (24/24), 1.06 MiB | 57.02 MiB/s, done.
Total 24 (delta 12), reused 0 (delta 0), pack-reused 0
error: RPC failed; curl 52 Empty reply from server
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
Everything up-to-date

**Comment by raikm** [comment]
I just pulled my own repo and replaced the old one

**Comment by bodhi-one** [comment]
Not following, what was the issue?  What does 'replaced the old one' mean?
