### ISSUE TITLE
Can not open GitHub Desktop from Windows 10 Parallels Desktop on Mac after browser login

### ISSUE THREAD

**Issue by efrainbautista** [desktop/desktop#11759]
I'm using GitHub Desktop from **Windows 10 Parallels Desktop** on **Mac**, but after browser login, it only allows to open GitHub Desktop from Mac and NOT from Windows 10 virtual machine, see image below:

<img width="1177" alt="browser" src="https://user-images.githubusercontent.com/8764052/110551162-08f39c00-8103-11eb-9d37-ee0d11d807e1.png">

**Comment by sergiou87** [comment]
Hi @efrainbautista! 👋 

That seems to be an issue with Parallels and how it tries to be smart about where to open the app. I think Parallels provides some settings to help it decide on which side (host or VM) open links: https://kb.parallels.com/125092

If you can't find a proper setting to change in Parallels to make this work, I'd recommend you to uninstall GitHub Desktop on your Mac, login from the VM, and then install it again on Mac if you need it. I don't think there's anything else we can do on our end 😞 

I hope that helps!
