### ISSUE TITLE
Bump embedded git version

### ISSUE THREAD

**Issue by ActuallyTrent** [desktop/desktop#11758]
### Describe the feature or problem you’d like to solve

There was a [security vulnerability reported today](https://www.openwall.com/lists/oss-security/2021/03/09/3) in the current embedded `git` version (v2.29.2, among others) and it is fixed in v2.29.3.

### Proposed solution

Bump embedded git

**Comment by ActuallyTrent** [comment]
Actually looks like a PR is open for this: #11755

**Comment by sergiou87** [comment]
Yup! It'll be released in a few hours, but thanks for filing this issue! ❤️
