### ISSUE TITLE
When switching to a PR, the branch shows as pr/(number) instead of the actual branch, even though pr/(number) is not an actual branch and thus doesn't work via git checkout on the commandline

### ISSUE THREAD

**Issue by thesyntaxinator** [desktop/desktop#11765]
### Describe the bug

When switching to a PR, the branch shows as pr/(number) instead of the actual branch, even though pr/(number) is not an actual branch and thus doesn't work via git checkout on the commandline.

### Version & OS

Version 2.6.6
MacOS 11.2.1

### Steps to reproduce the behavior

Click dropdown for current branch -> click Pull Requests -> click a pull request -> click dropdown again -> click Branches

### Expected behavior

Currently checked out branch and recent branches should show actual branch name, not pr/(number). Or this behavior should be togglable via a setting.

### Actual behavior

Branch shows as pr/(number).

**Comment by sergiou87** [comment]
Hi @thesyntaxinator! 👋 

I recently explained here why that behavior: https://github.com/desktop/desktop/issues/11733#issuecomment-792684775

>  I'm sorry that's confusing, but as far as I can tell, what is happening is that your clone is a fork, and when GitHub Desktop "switches to a PR", it doesn't check out to the PR's branch and instead it will create a `pr/12345`. Therefore everything seems like expected behavior to me.
>
> Using `pr/27412` will prevent a collision between the PR's branch in your fork (`origin/minor1136`), and the PR's branch in the original repo (`upstream/minor1136`).

I hope that explanation helped. I'm gonna close this issue, but let me know if there is anything else I can do to help or explain better.

**Comment by thesyntaxinator** [comment]
How do I remove the fork and check out the branch directly?

**Comment by sergiou87** [comment]
For that you need to either clone the original repo directly (instead of your fork), or I think you can open `Repository` -> `Repository Settings`, and then go to `Fork Behavior` and switch to `For my own purposes`.

**Comment by tattooonyou** [comment]
How do I stop receiving emails from you

**Comment by sergiou87** [comment]
@tattooonyou you have to unsubscribe from the repository. Open https://github.com/desktop/desktop and at the top right you'll find this:
![image](https://user-images.githubusercontent.com/1083228/110757284-7dd1ed80-824b-11eb-83e3-be8cad78a1b9.png)
Select `Ignore` and that's it.
