### ISSUE TITLE
2.6.6 not working on Mac OSX 11.2.2 (20D80)

### ISSUE THREAD

**Issue by moryde** [desktop/desktop#11767]
### Describe the bug

The app is completely unresponsive.

### Version & OS

Not possible, but 2.6.6

### Steps to reproduce the behavior

Install the latest version of the app.

### Expected behavior

The App is unresponsive, and something called GitHub Desktop Helper (Renderer) is blow away 100% of CPU on my MBP 2019.

### Actual behavior

I was using the app and I think it auto-updated, resulting in a non-working app.

### Screenshots
<img width="967" alt="Screenshot 2021-03-10 at 20 34 54" src="https://user-images.githubusercontent.com/3193379/110686891-34988400-81e0-11eb-8fc5-35ddee68abae.png">

### Logs

No possible

### Additional context

Can I download the older version?

**Comment by sergiou87** [comment]
Weird, there are only a few unrelated commits between 2.6.5 and 2.6.6, so I'm surprised about this behavior 😞 

Have you tried restarting your machine? Could you provide logs? They should be in `~/Library/Application Support/GitHub Desktop/logs`

**Comment by moryde** [comment]
<img width="1428" alt="Screenshot 2021-03-10 at 21 20 42" src="https://user-images.githubusercontent.com/3193379/110692262-7af0e180-81e6-11eb-952f-d6502c16cf47.png">
 There is nothing. 
I found version 2.6.5 it does not work either. I tried updating OS X to the latest version, without any luck.

**Comment by moryde** [comment]
Just close this. There was something wrong with the files in my repo which rendered the app unresponsive..
