### ISSUE TITLE
Changed files list cannot be filtered by keyword.

### ISSUE THREAD

**Issue by teanfoo** [desktop/desktop#11761]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
Thanks for the issue @teanfoo. You can follow along in https://github.com/desktop/desktop/issues/6407 for updates about this feature.
