### ISSUE TITLE
Ask for credentials when you´re cloning a private repo

### ISSUE THREAD

**Issue by FANMixco** [desktop/desktop#11773]
### Describe the feature or problem you’d like to solve

I cannot clone private repos when I didn´t login with the same account.

### Proposed solution

If you´re cloning a private repo and you´re not connected with the same credentials, it would be a great idea to request the credentials to verify.

**Comment by steveward** [comment]
@FANMixco thanks for the issue. At this time GitHub Desktop does not support this type of flow, and there are currently no plans to implement this. I'd recommend following in https://github.com/desktop/desktop/issues/3707 where we are tracking feedback about supporting multiple accounts in GitHub Desktop.

**Comment by FANMixco** [comment]
Hi @steveward , thanks ? Are you tracking in a close ticket the changes?

**Comment by steveward** [comment]
@FANMixco we do track requests in closed issues. If an issue is closed it still may be considered again in the future based off of feedback we receive.
