### ISSUE TITLE
Show repository path in the 

### ISSUE THREAD

**Issue by CarlosOnline** [desktop/desktop#11785]
### Describe the feature or problem you’d like to solve

I frequently clone a repository multiple times for work purposes.  The additional clones have the same folder name, but are located in a different root folder.  For example.

```
c:\dev1\my-cool-project
c:\dev2\my-cool-project
c:\dev3\my-cool-project
```

When I add all 3 repositories to GitHub Desktop the repository list shows the same name 3 times like below.  It is difficult to distinguish between the repositories.  NOTE: I keep the folder names the same to simplify development scripts that can be targeted at a different root folder.

```
my-cool-project
my-cool-project
my-cool-project
```

# Request Please add option to show the _repository.path_ instead of repository.name like it does today

### Proposed solution

How will it benefit Desktop and its users?
Easily distinguish between same repositories in different folders.

Fix is simple change the text from `text={repository.name}` to `text={repository.path}`.

Modify `app\src\ui\repositories-list\repository-list-item.tsx` to render repository.path instead of the name.

```
    return (
...
          <HighlightText
            text={repository.path}
            highlight={this.props.matches.title}
          />
        </div>
```

### Additional context

![github desktop](https://user-images.githubusercontent.com/3691895/111017183-abf82000-8366-11eb-8f74-3f2f8480808d.png)

**Comment by steveward** [comment]
@CarlosOnline thanks for the feedback. You can hover over the repository name to view the full directory path of the repository. This request sounds similar to #8175 and #8175, both which were included in #6460. See #8158 (comment) specifically for the current thinking on this. I'm going to close this issue out -- thanks for using GitHub Desktop.
