### ISSUE TITLE
Sometimes cannot open the app with no warnings or other tips.

### ISSUE THREAD

**Issue by DarrenYing** [desktop/desktop#11783]
### Describe the bug

有时关闭后再次打开，就打不开了，也不会弹窗报错，即使从github上选择open with github desktop也不行，卸载重下后可以，但是过段时间又会出现相同的问题。

### Version & OS

Github Desktop 2.6.5，Windows 10 专业版

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by sergiou87** [comment]
Sorry @DarrenYing but no one in the team speaks Chinese 😅  This is what Google Translate gives me:

![image](https://user-images.githubusercontent.com/1083228/110910920-467a4400-8312-11eb-9b1e-bda94dfebc0e.png)

> Sometimes when you close it and open it again, it won’t open, and there will be no pop-up error. Even if you choose open with github desktop from github, it doesn’t work. After uninstalling and restarting, the same problem will occur again.

Could you provide more info? What happens exactly? You see the app open but a white window? Or the app doesn't open at all?

Could you provide logs?

Thank you!
