### ISSUE TITLE
My Repositories have disappeared from the website

### ISSUE THREAD

**Issue by KKendall56** [desktop/desktop#11780]
I can no longer see ANY of my repos on the website. I can open locally and push, pull whatever but when I try to see them on the website I get the 404 screen and my prodile says I have NO REPOSITORIES. I had three so what the hell is going on?

**Comment by steveward** [comment]
@KKendall56 if you have specific problems with your GitHub account please reach out to [GitHub Support](https://support.github.com/). It sounds like your account may have been accidentally flagged.
