### ISSUE TITLE
Support multiple GitHub Enterprise servers

### ISSUE THREAD

**Issue by j3p0uk** [desktop/desktop#11797]
### Describe the feature or problem you’d like to solve

I have multiple distinct GitHub Enterprise servers that I interact with.  I would like to be able to configure all of them to be used via GitHub Desktop.

### Proposed solution

All GitHub Desktop users will be able to interact with multiple GitHub Enterprise servers, which is not unusual in a large company.

**Comment by steveward** [comment]
Thanks for the feedback @j3p0uk. I'm going to add this to https://github.com/desktop/desktop/issues/3707 where we are tracking feedback about this. You can follow along there for updates about this.
