### ISSUE TITLE
does not change language

### ISSUE THREAD

**Issue by tonychagas** [desktop/desktop#11791]
### Describe the bug

remains just in english

### Version & OS

windows 10

**Comment by Spanden** [comment]
да, нужен на русском

**Comment by twocountriestrus** [comment]
Gracias

**Comment by steveward** [comment]
Thanks for the feedback @tonychagas. At this time we do not have plans to provide multilingual support in GitHub Desktop due to the bandwidth it would require from the team, but this may be something we reconsider again in the future. Please see #8289 for further information.
