### ISSUE TITLE
Rendre possible les téléversements en ligne, sans être forcé de passer par un dépôt en local

### ISSUE THREAD

**Issue by UnionPolitiqueCitoyenne-be** [desktop/desktop#11792]
Je pense que tout est dans le titre. Je suis juste confronté au problème actuellement, car mon collègue dans l´élaboration de mon site, est parvenu à télécharger la version .zip, mais par contre, le lien https, se contente d'ouvrir la page web github du repository, mais ne crée rien en local, et n'effectue aucun mouvement de fichiers.

**Comment by steveward** [comment]
@UnionPolitiqueCitoyenne-be thanks for the issue. At this time we are only able to provide support in English. I've added a translation from Google to your issue. 

Are you having issues cloning a repository to GitHub Desktop? I don't see any mention of GitHub Desktop, so let me know if that is not correct.
