### ISSUE TITLE
Clicking on a pull request does not do anything

### ISSUE THREAD

**Issue by ChilliCreek** [desktop/desktop#11798]
### Describe the bug

I try to view a pull request with a conflict someone created to resolve the conflicts and merge the branches, by clicking on the pull request to view it. But nothing happens, and I can't view the changes and all to resolve the conflict.

### Version & OS

Windows 10 , github version 2.6.6

### Steps to reproduce the behavior

1. Go to 'current branch'
2. Click on 'pull requests'
3. Click on any pull request there.
4. No error, but a cant see the pull request's contents

### Expected behavior

See the pull request and the changes of it.

### Actual behavior

Nothing happens, and the current branch window closes.

### Screenshots

![BUG](https://user-images.githubusercontent.com/9676360/111186415-f5a66c00-85ed-11eb-997a-53f708608667.png)

### Additional context

This applies to all repositories, and every pull request I try to view.

**Comment by steveward** [comment]
Thanks or the issue @ChilliCreek. 

Checking out a pull request is the same as checking out a branch -- the changes will be visible in the commit history or by directly opening your editor/IDE to view the files. If there are merge conflicts to be resolved you will need to open up the repository in your text editor.

We're looking into improving the pull request experience in https://github.com/desktop/desktop/issues/11517 -- I would recommend following along there for updates. Let me know if I am misunderstanding the issue.
