### ISSUE TITLE
Can Github Desktop automatically push the commit?

### ISSUE THREAD

**Issue by Cliff0317** [desktop/desktop#11809]
### Can Github Desktop automatically push the commit instead of having to click on a button?
It's substantially tiring to click the Push button every time I made some changes into the document. Can Github Desktop automatically do so? Or are there some implementation concerns?

### Proposed solution
It should save some work.

**Comment by steveward** [comment]
Thanks for the issue @Cliff0317. We are tracking requests about this in https://github.com/desktop/desktop/issues/2191, so I am going to close this issue out. I'll add your feedback there.
