### ISSUE TITLE
Bug when unstashing an ignored file after merging a branch that had it ignored

### ISSUE THREAD

**Issue by HeCorr** [desktop/desktop#11803]
### Describe the bug

I believe I found a bug where if you stash a file on a branch, then merge from another branch where the file is ignored and then restore it, it will not be ignored, even if `.gitignore` is correct and the file name matches.

### Version & OS

GitHub Desktop v2.6.6
Windows 10 Pro

### Steps to reproduce the behavior

(not tested. I'm afraid to break it even further)
1. create two branches.
2. create a file on branch 1
3. checkout branch 2 and choose "Leave changes at branch 1"
4. add the file extension to `.gitignore` (like `*.json`), commit it
5. go back to branch 1, merge from branch 2
6. unstash it.

### Expected behavior

The file is ignored since it's extension matches the recently merged `.gitignore`

### Actual behavior

The file is **not** ignored at all.
(I tried switching branches, stashing and unstashing it but nothing worked.)
If you rename the file to **anything** but it's current name (keeping the extension) it **will** be properly ignored.
I even added the full file name to `.gitignore` and still nothing.

### Screenshots

![image](https://user-images.githubusercontent.com/75134774/111239806-b6215500-85d8-11eb-821f-806bc7c8e79d.png)
![image](https://user-images.githubusercontent.com/75134774/111239849-d05b3300-85d8-11eb-92db-d596ae1cb856.png)
![image](https://user-images.githubusercontent.com/75134774/111239864-d8b36e00-85d8-11eb-9920-e74a66298cac.png)

### Logs

No useful logs.

**Comment by HeCorr** [comment]
Update: I managed to ignore it again (not all steps might be necessary):

1. bring your changes to another branch
2. stash it (by checking out another branch and clicking "Leave my changes")
3. go back, unstash
4. checkout the first branch again, choosing "Bring my changes"
5. delete the file
6. recreate it.
7. (extra step that fixed the file not being faded out on VSCode): open `.gitignore` and save it.

Very weird and edge-case it seems.

Wasn't going to report the issue since I got it fixed (somehow) but I already had written everything so might as well.

**Comment by HeCorr** [comment]
Reopening because the same issue happened **again**.

This is getting really annoying.....

**Comment by HeCorr** [comment]
And for some reason the steps from earlier are not working........

**Comment by HeCorr** [comment]
Fixed with [`git rm --cached`](https://git-scm.com/docs/git-rm).

**Comment by HeCorr** [comment]
Reopening because for some reason, `git rm --cached` sometimes simply marks the file as deleted instead of **ACTUALLY IGNORING IT**...

**Comment by steveward** [comment]
@HeCorr thanks for the report. The `git rm --cached` command showing the file as deleted is the correct behavior. It removes the file from the index but leaves it in the working directory.

**Comment by TEJohnF** [comment]
@steveward I am also seeing this exact behavior.
Deleting the ignored file (which appears as an added file despite being ignored) and then pasting it back into the same directory then allows the file to be present without showing up as a change.

Seems this is an intermittent problem, or may depend if branch1/2 is the "main branch" or not, would have to do more testing to confirm that but using Github Desktop Version 3.1.5 (x64) on Windows 10 Pro this is still an issue.
