### ISSUE TITLE
Close button doesn't work in full screen mode

### ISSUE THREAD

**Issue by pawan-regoti** [desktop/desktop#11808]
### Describe the bug

Close button doesn't work in full-screen mode.

### Version & OS

Mac OS Big Sur (11.2.3)
GitHub Desktop app v 2.6.6

### Steps to reproduce the behavior

1. Go to 'Github Destop app'
2. Click on 'full screen'
3. Click 'Close' button

### Expected behavior

The app should be minimized as it works in normal mode.

### Actual behavior

Nothing happens

https://user-images.githubusercontent.com/39826745/111282990-e1d72600-863e-11eb-89ed-9940906ba0aa.mov

**Comment by steveward** [comment]
Thanks for the report @pawan-regoti. I was unable to reproduce this, but I'm on Catalina and not Big Sur. I will mark this as investigation needed. Do you see this behavior in any other Electron applications?

**Comment by pawan-regoti** [comment]
@steveward I have checked with VS Code (which I am assuming is an electron app) and it works as expected.

**Comment by steveward** [comment]
Closing as a duplicate of https://github.com/desktop/desktop/issues/9757.
