### ISSUE TITLE
git: 'remote-https' is not a git command. See 'git --help'.

### ISSUE THREAD

**Issue by georgioyammine** [desktop/desktop#11819]
### Describe the bug

git: 'remote-https' is not a git command. See 'git --help'. on any fetch, push, pull, clone. Started happening today, was working perfectly before.

### Version & OS

Version 2.6.6, Win 10

### Steps to reproduce the behavior

Fetch, Push, Pull, Clone...

### Expected behavior

Should work perfectly

### Actual behavior

git: 'remote-https' is not a git command. See 'git --help'.

error in developer tools/logs:
git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
git: 'remote-https' is not a git command. See 'git --help'.

error @ install.ts:23

**Comment by georgioyammine** [comment]
Performed the following steps and still the same issue:
1. Close GitHub Desktop
2. Open File Explorer
3. Go to %LocalAppData% and delete the GitHubDesktop directory
4. Reinstall GitHub Desktop from http://desktop.github.com

**Comment by steveward** [comment]
Thanks for the issue @georgioyammine. Did you notice whether GitHub Desktop updated today? Are you running any antivirus software on this machine that could be causing GitHub Desktop to fail to update properly? We've seen cases where updates can trigger antivirus software and cause problems like this.

**Comment by georgioyammine** [comment]
I have Bitdefender antivirus, and I don't think there was an update for GitHub Desktop. nevertheless I turned off the antivirus to test it now and everything is back to working normally, I then re-enabled the AV and it continued to work just fine. So I don't know what actually solved it or what was the root cause but it is back to working normally and that's what matters. Thank you for the support.
