### ISSUE TITLE
Slow performance of "create branch"

### ISSUE THREAD

**Issue by gemal** [desktop/desktop#11816]
`[Timing] Action 'create branch' for 'gemal/xxx.com' took 37.659s`

is it normal that performance is like this?

other slow commands:
```
2021-03-16T19:26:02.463Z - info: [ui] Executing getAllTags: git show-ref --tags -d (took 45.600s)
2021-03-16T19:26:04.833Z - info: [ui] Executing getBranches: git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(symref)%00 refs/heads refs/remotes (took 14.238s)
```

using Version 2.7.0-beta3 on Windows 10

**Comment by billygriffin** [comment]
@gemal Thanks! Is there anything special about the repo where this is happening? Creating branches definitely takes longer generally in giant repos, but I'm not able to reproduce anything approaching what you're seeing, even on enormous repos. I'm curious if this behavior persists independent of which repo you're in, or whether there are other contributing factors. I'm also curious if @steveward has any ideas.

**Comment by gemal** [comment]
on command line `git checkout -b newbranch` takes around 2 seconds

**Comment by billygriffin** [comment]
@gemal Sorry, my question was whether other repositories in GitHub Desktop also take a long time to create branches. In other words, does it take forever in every repo, or is it just this particularly large one?

**Comment by steveward** [comment]
@gemal any chance you are running antivirus software that could be slowing down Git operations on this machine?

**Comment by gemal** [comment]
fast on another repo
`2021-03-18T08:43:02.635Z - info: [ui] [Timing] Action 'create branch' for 'gemal/core' took 1.576s`

no antivirus software installed

**Comment by gemal** [comment]
I'm not 100% sure these are related to the create branch command but they also seem slow:
```
2021-03-18T11:25:21.336Z - info: [ui] Executing getBranches: git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(symref)%00 refs/heads refs/remotes (took 20.214s)
2021-03-18T11:25:22.101Z - info: [ui] Executing getBranches: git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(symref)%00 refs/heads refs/remotes (took 19.715s)
2021-03-18T11:25:22.758Z - info: [ui] [Timing] Action 'create branch' for 'gemal/dinnerbooking.com' took 35.649s
```

**Comment by gemal** [comment]
let me know if I can help to debug

**Comment by steveward** [comment]
@gemal do you have a different machine that you could test this issue out on to see if you are able to reproduce the slow performance? If it's an open-source repository I could also test it out as well.

**Comment by gemal** [comment]
> 
> 
> @gemal do you have a different machine that you could test this issue out on to see if you are able to reproduce the slow performance? If it's an open-source repository I could also test it out as well.

I tested on a different machine I got the same slow performance
I have no anti virus but the default Windows 10

**Comment by billygriffin** [comment]
Hi @gemal, would you mind answering my question from earlier to help us diagnose please? I'd love to know whether this is happening for you across multiple repos, or just this one repo? Is one of the repos it's happening in open source by chance so we can try to reproduce it on our end?

**Comment by gemal** [comment]
I thought I already answered this with https://github.com/desktop/desktop/issues/11816#issuecomment-801741377
I dont see this performance problem with other repos.
It's not open source sorry

**Comment by gemal** [comment]
is there another way I can provide you with more details ?

**Comment by steveward** [comment]
@gemal to debug this a bit further you could open the Developer Tools in GitHub Desktop (`View` -> `Toggle Developer Tools`) and head to the `Performance` tab. From there you can use the `Record` option to record the performance of the create branch function. Once that's done you can download it as a `.json` file and upload it here. That should give us some more information about what's taking so long to complete. Thanks!

**Comment by gemal** [comment]
can I add it here? it does not contain private information?

**Comment by steveward** [comment]
It does not contain any private information.

**Comment by gemal** [comment]
[Profile-20210421T202620.zip](https://github.com/desktop/desktop/files/6365969/Profile-20210421T202620.zip)

**Comment by steveward** [comment]
@gemal we're going through old issues and closing out any that are stale. We haven't had other reports of this specific issue, so I'm going to close this out. If you are still experiencing this in recent versions of GitHub Desktop please let us know and we can investigate further.
