### ISSUE TITLE
Can´t choose where do I to install Github App in my PC

### ISSUE THREAD

**Issue by pedrogxv** [desktop/desktop#11812]
### Describe the bug

I cannot choose where to install the Github Desktop app in my windows 10 PC.
It just download automaticaly in my C driver, but i want it in the E driver.
The PC is mine bruh, I have the right to choose where to install...

### Version & OS

Windows 10 Pro 64 bit (19042.867).
Github Desktop 2.6.6

### Steps to reproduce the behavior

1. Intall the setup on the Github Desktop site
2. Execute the setup
3. Uninstall it and install infinitely until it gives you the option to choose the location

### Expected behavior

It expected to show popup with the option to chose where do I want the app to be in my pc.

### Additional context

Just add the option. Is it too hard?

**Comment by steveward** [comment]
Thanks for the issue @PedroGXV. Currently it is not possible to customize the installation location of GitHub Desktop. This is a constraint in the installation framework we use, Squirrel.Windows (see https://github.com/Squirrel/Squirrel.Windows/issues/314). At this time we do not have plans of changing the installer we use for GitHub Desktop.
