### ISSUE TITLE
Unable to clone remote repository

### ISSUE THREAD

**Issue by VoidSec** [desktop/desktop#11817]
### Describe the bug
Whenever I use the "Open with Github Desktop" button launcher and try to clone a repository I'm presented with below error:

```
Cloning into 'S:\Github\File-Format-Templates'...
remote: Enumerating objects: 3, done.        
remote: Counting objects: 100% (3/3), done.        
remote: Compressing objects: 100% (2/2), done.        
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0        
Receiving objects: 100% (3/3), done.
      0 [main] sh 1311 dofork: child -1 - forked process 36192 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\VoidSec\AppData\Local\GitHubDesktop\app-2.6.6\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
1075039 [main] sh 1311 dofork: child -1 - forked process 19432 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\VoidSec\AppData\Local\GitHubDesktop\app-2.6.6\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
3143831 [main] sh 1311 dofork: child -1 - forked process 17556 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\VoidSec\AppData\Local\GitHubDesktop\app-2.6.6\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
7235778 [main] sh 1311 dofork: child -1 - forked process 10640 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\VoidSec\AppData\Local\GitHubDesktop\app-2.6.6\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
15310856 [main] sh 1311 dofork: child -1 - forked process 37104 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\VoidSec\AppData\Local\GitHubDesktop\app-2.6.6\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: Resource temporarily unavailable
```

### Version & OS

- Windows 10 Pro 20H2 19042.867
- Github Desktop v.2.6.6
- Firefox 86.0.1

### Steps to reproduce the behavior

1. Go to 'https://github.com/VoidSec/File-Format-Templates.'
2. Click on 'Code > Open with Github Desktop'
3. Leave default values and click on 'Clone'
4. See above error or attached logs

### Expected behavior
Successfully clone the repository without getting back any error.

### Actual behavior

`Clone Failed` error message pop out and the repository is not cloned

### Screenshots

![image](https://user-images.githubusercontent.com/5717603/111441741-e7e50980-8707-11eb-94ab-6285a317379d.png)

### Logs

[2021-03-17.desktop.production.log](https://github.com/desktop/desktop/files/6154997/2021-03-17.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @VoidSec. Has this error been consistently occurring on your machine, or did it only start occurring recently (perhaps after an update)?

This sounds like the type of error you'd get if you've enabled [Mandatory ASLR](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#enable-mandatory-aslr-triggers-cygheap-errors---3096). Please see our [known issues document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#enable-mandatory-aslr-triggers-cygheap-errors---3096) or [this comment](https://github.com/desktop/desktop/issues/9089#issuecomment-584652898) for more details on that.

If you don't have mandatory ASLR enabled for your machine let us know and we'll keep troubleshooting.

**Comment by VoidSec** [comment]
@steveward you are perfectly right, mandatory ASLR was breaking it.

**Comment by burgil** [comment]
**How do I disable it?**
### Return to my Issue: https://github.com/desktop/desktop/issues/12376

None of the links explains how to disable it.

I've read "Mandatory ASLR" and the "known issues document":  (FYI Both navigates to the same page @steveward)
https://github.com/desktop/desktop/blob/development/docs/known-issues.md#enable-mandatory-aslr-triggers-cygheap-errors

---------------------
![image](https://user-images.githubusercontent.com/41600149/120946610-b0ee2500-c745-11eb-8bbb-37bccdfc734d.png)
---------------------

But it did not contain any information about **how to actually fix the problem**

From there I clicked on Related issue: #3096 - https://github.com/desktop/desktop/issues/3096

But no one actually explained how to solve the issue step by step, Everyone just posted random parts of the solution and some claimed they were able to fix it without explaining actually how.

And also read "this comment": https://github.com/desktop/desktop/issues/9089#issuecomment-584652898
Again it does not contain anything useful about how to fix the problem.
