### ISSUE TITLE
Add option for Desktop to use git via WSL rather than Windows-installed

### ISSUE THREAD

**Issue by exoRift** [desktop/desktop#11828]
### Describe the feature or problem you’d like to solve

It would be nice to have an option for Desktop to do git operations via git installed in the default WSL distro rather than requiring it to be installed on main Windows. I basically have to have git installed twice with configs I have to both manage.

**Comment by steveward** [comment]
@exoRift thanks for the issue. GItHub Desktop actually bundles its own version of Git, but it does use the global config files.

Have you tried using the [includes](https://git-scm.com/docs/git-config#_includes) feature to include config options from WSL? That may be a potential workaround for you.

**Comment by exoRift** [comment]
GHD comes packaged with its own Git? I didn't know
