### ISSUE TITLE
Let the user choose a tool for resolving conflicts or seeing diffs

### ISSUE THREAD

**Issue by Thaval** [desktop/desktop#11831]
### Describe the feature or problem you’d like to solve
When pulling, merging or rebasing branches, conflicts often occur. I'd like to resolve the conflicts in an external program (it'd be 1000 times better do to it in github desktop itself but we cant unfortunately) like WinMerge, Meld, Visual Studio or Rider.

### Proposed solution

Instead of predefining all tools in the external tools dropdown selector, add an extra entry there like "custom tool", so the user can choose a path to an exe and specify the arguments for that program (like SourceTree does it). 
The problem is, that currently "External tools" provide me only VSCode and Notepad++, both not good for merging/resolving conflicts.

How will it benefit Desktop and its users?
The user will feel so much more comfortable when he/she can work with whatever tool he/she loves and we can finally merge/resolve stuff.

**Comment by Rexogamer** [comment]
From what I know the Desktop is currently looking into better ways to support editors, but also bear in mind that if you have a specific editor you want to use with Desktop, someone will likely add support for it if you make a dedicated issue :)

**Comment by steveward** [comment]
Thanks for the feedback @Thaval. This has been previously discussed in https://github.com/desktop/desktop/issues/68. I'm going to roll this into https://github.com/desktop/desktop/issues/9609 which is an open issue for tracking support for external diff/merge tools.
