### ISSUE TITLE
Split diff uses 8 spaces for a tab instead of 4

### ISSUE THREAD

**Issue by mrlife** [desktop/desktop#11838]
### Describe the bug

The Unified diff displays a tab correctly as 4 spaces. The Split diff should use 4 spaces as well but uses 8.

### Version & OS

GitHub Desktop 2.6.6
macOS 10.15.7

### Steps to reproduce the behavior

1. Go to a repository's History
2. Click on a previous commit
3. Switch to Split diff
4. See 8 spaces for a tab
5. Switch to Unified diff
6. See 4 spaces for a tab

### Expected behavior

Split diff should display a tab as 4 spaces.

### Actual behavior

Split diff displays a tab as 8 spaces.

### Screenshots

Unified diff:
![Screen Shot 2021-03-19 at 5 02 17 PM](https://user-images.githubusercontent.com/213164/111842214-735fc580-88d5-11eb-90fe-ff1da9b345d2.png)

Split diff:
![Screen Shot 2021-03-19 at 5 02 29 PM](https://user-images.githubusercontent.com/213164/111842250-81ade180-88d5-11eb-985a-0eba7f36097d.png)

**Comment by tidy-dev** [comment]
@mrlife Thanks for your issue. I was able to confirm the difference between the two.

**Comment by steveward** [comment]
This is no longer present (and tab size can be customized now). Closing it out as resdolved.
