### ISSUE TITLE
Ability to disable the creation of a desktop shortcut during installation

### ISSUE THREAD

**Issue by rakleed** [desktop/desktop#11837]
### Describe the feature or problem you’d like to solve
Please add the option to disable the creation of a desktop shortcut when installing an application on Windows. Since I would like to be able to control this during installation.

### Proposed solution
Please add the option to disable the creation of a desktop shortcut when installing an application on Windows. So that later users do not need to manually remove the shortcut from the desktop.

**Comment by steveward** [comment]
Thanks for the issue @rakleed. I believe this is possible in Squirrel.Windows based on [this document](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events.md), but at this time we don't have any plans to change the installation flow. One of the benefits of Squirrel is the seamless installation that doesn't make you go through numerous prompts. 

I'm going to close this out, but if this is something we continue to hear feedback about in the future we can revisit it. Thanks for using GitHub Desktop.
