### ISSUE TITLE
Can't navigate to GitHub repos anymore

### ISSUE THREAD

**Issue by alliedcvil** [desktop/desktop#11842]
### Describe the bug

View on Github button for all repos is suddenly greyed out. (Example is: https://github.com/microsoft/terminal)

### Version & OS

Version 2.6.6
Windows 10 Pro 20H2

### Steps to reproduce the behavior

1. Open Github Desktop.
2. Use product for a bit and fetch from several repos.
3. Visit a few repos on Github.
4. Update product then notice that you can no longer View on Github because the button is greyed out on all repos.

### Expected behavior

You can View on Github by having Github desktop launch a browser to a Github repo or at least have a tooltip indicating why you can't View on Github.

### Actual behavior

Button and menus options to View on Github are greyed out.

### Screenshots

![image](https://user-images.githubusercontent.com/5561081/111888512-98c30100-89b3-11eb-89e6-90c9f4230fd1.png)
![image](https://user-images.githubusercontent.com/5561081/111888516-a37d9600-89b3-11eb-8246-8f3384af424b.png)

### Logs

I see the error indicating within the logs: Error: Bad credentials for one repo, but it's not reporting anything within the desktop.

**Comment by alliedcvil** [comment]
Fixed by logging out from the options menu and logging in using the browser. Very odd.

**Comment by tidy-dev** [comment]
@alliedcvil Thank you for the report! Sounds like you had some credentials that were invalid and was impacting whether the app could identify this a github repository. Since you were able resolve your issue by log out/log in, I am going to close this issue.
