### ISSUE TITLE
Imp: Github desktop repository and synchronization issue.

### ISSUE THREAD

**Issue by thevinayysharma** [desktop/desktop#11847]
Hello, team!

I'm **not able to initialize a new repository on hard drive** from Github Desktop controls. Whenever I choose to create one, the local path doesn't get added or it shows "this directory appears to be a git repository, would you like to  add this repository instead.  When I choose to the later option, it gets synched to my earlier Github account [vinaysharmatech] which has been deactivated. 

Please clear me on the below issue as well:
->What exactly is local path in the above context.
->How to create a working Git directory for local path.  I have tried to add local path by the option provided to choose local path, but while  adding a open folder to it, it didn't worked. 

 I am not able to resolve it even after trying so hard, and felt like crying from last week. Please resolve asap!

The screenshots have been attached for your reference.

![github_desktop_issue_image](https://user-images.githubusercontent.com/68610608/112033224-37da2b00-8b63-11eb-9a8c-568868373c1c.png)
![github_desktop_issue_2](https://user-images.githubusercontent.com/68610608/112033290-47f20a80-8b63-11eb-8253-3eaad9a25b5e.png)

**Comment by steveward** [comment]
@thevinayysharma thanks for the issue. Do you possibly have an existing repository of the same name in your Documents directory?  I would recommend creating a `GitHub` or `Code` directory in your Documents folder to see if you are able to create a repository there.

>->What exactly is local path in the above context.

The local path is the path to the directory your repository will be created in.

>->How to create a working Git directory for local path. I have tried to add local path by the option provided to choose local path, but while adding a open folder to it, it didn't worked.

Is it possible you accidentally created a repository inside of your `Documents` directory? That could also cause an error like this.
