### ISSUE TITLE
Fetch Origin: Never Fetched.

### ISSUE THREAD

**Issue by Chuntestev72674** [desktop/desktop#11841]
### Describe the bug
Github's "Fetch Origin" notifer says that "Fetch Origin: Never Fetched." None of my projects allow me to push changes. Every time I attempt to push a change an error pops up: 

"ERROR: 
On branch dev-main
Your branch is up to date with 'origin/dev-main'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)

no changes added to commit (use "git add" and/or "git commit -a")"

### Version & OS

WINDOWS 10 and Version 2.6.6

### Steps to reproduce the behavior

1. Move and rename folder of one of your repositories.
2. Github will notify that file has been disconnected (cannot find file)
3. Re-connect file to corresponding Github repository. 

### Expected behavior

I thought once I reconnected the file to my existing repository, things should update and work normally. Where I could push my changes. 

### Actual behavior

Errors pop up every time I try to push changes. But I can pull and see other people's changes. 

### Screenshots

![GitHub Desktop 3_19_2021 11_20_58 PM](https://user-images.githubusercontent.com/62954218/111857992-c5234280-890b-11eb-97e2-a629b26329b5.png)
![GitHub Desktop 3_19_2021 11_21_33 PM](https://user-images.githubusercontent.com/62954218/111857995-c8b6c980-890b-11eb-8c31-1e9f4f0e0774.png)

**Comment by steveward** [comment]
Thanks for the issue @Chuntestev72674. 

>Move and rename folder of one of your repositories.

Can you clarify exactly what you did here? Did you move a folder inside the existing repository outside of the repository or move the entire repository?

**Comment by Chuntestev72674** [comment]
Hi! Thank you for your response.
I moved and renamed entire repository folder.

**Comment by Chuntestev72674** [comment]
Hi! I just found a fix!
I deleted my source folder in my computer files and re-downloaded the repository on an Empty Folder. Everything works normally!
