### ISSUE TITLE
Commit Problem

### ISSUE THREAD

**Issue by NijatM** [desktop/desktop#11850]
### Describe the feature or problem you’d like to solve

error: cannot spawn null: No such file or directory
error: gpg failed to sign the data
fatal: failed to write commit object

**Comment by tidy-dev** [comment]
@NijatM Thanks for your report! Looks like you may be running into issue being tracked on this #1391. And one user was able to work around the error, check out [their comment](https://github.com/desktop/desktop/issues/1391#issuecomment-299669727 ) about setting the gpg sign config. Going to close this issue in favor of tracking it there. Feel free to add more detail to that issue.
