### ISSUE TITLE
Ability to move file changes between commits

### ISSUE THREAD

**Issue by exoRift** [desktop/desktop#11858]
### Describe the feature or problem you’d like to solve

Could you add a feature that allows users to move file changes between commits?

I made a lot of changes at once and wanted to split them individually into different commits. However, 7 commits in, I realized that I forgot to include a file deletion in the first commit and I don't want to have to undo all my commits and rebasing is a nightmare. Adding a way to do it via UI would be a big help.

**Comment by tidy-dev** [comment]
@exoRift Thank you for the suggestion. I believe the Git way of doing what you propose is amending a commit. We are tracking that feature request under #1644. Closing this one in favor of that one - feel free to add your concern to it for more context.
