### ISSUE TITLE
Pressing up key on most recent commit goes to middle of commit history

### ISSUE THREAD

**Issue by mrlife** [desktop/desktop#11851]
### Describe the bug

Pressing the up key, when the top history item is selected, goes to middle of the commit history.

### Version & OS

GitHub Desktop 2.6.6
macOS 10.15.7

### Steps to reproduce the behavior

1. Go to a repository's History (it should perhaps have a lot of history)
2. Click on the most recent commit
3. Press the up key on the keyboard
4. Notice that a random commit in the middle of the history is now selected

### Expected behavior

Pressing up on the most recent commit either does nothing or goes to the first commit.

### Actual behavior

Pressing up on the most recent commit goes to a random commit in the middle of the commit history.

**Comment by Copane40** [comment]
I forget... no ping 
Cover -dell?

**Comment by tidy-dev** [comment]
@mrlife Thank you this issue. We already have it documenting unexpected behavior on up key in history on #7679. I am going to close this one in favor of tracking it there. Thanks again!
