### ISSUE TITLE
No option to install for all users

### ISSUE THREAD

**Issue by Justin-Frazier** [desktop/desktop#11855]
### Describe the bug

When I install GitHub Desktop, it is only visible ot me. I do not have a way to make it available to all users of a machine.

### Version & OS

Version 2.6.6
Windows Server 2019

### Steps to reproduce the behavior

1. Install GitHub Desktop
2. Log out
3. Log in as different user
4. GitHub Desktop is not available

### Expected behavior

The application should be installed in either the C:\Program Files\GitHubDesktop\ or c:\ProgramData\GitHubDesktop\ folder.

### Actual behavior

The application is installed into C:\Users\<username>\AppData\Local\GitHubDesktop\ folder. This prevents it from being used by multiple users.

### Screenshots

N/A

### Logs

N/A

### Additional context

This should be a pretty self-explanatory and obvious feature.

**Comment by steveward** [comment]
@ac05219 thanks for the issue. There is a machine-wide installer available [here](https://central.github.com/deployments/desktop/desktop/latest/win32?format=msi). 

Please note that this will still install to to `%AppData%` on a per-user basis. At this time the installation directory is not customizable. Let me know if you have any questions.
