### ISSUE TITLE
Show folder name that a repo is deployed to.

### ISSUE THREAD

**Issue by Justin-Frazier** [desktop/desktop#11856]
### Describe the feature or problem you’d like to solve

When a repo is checked out multiple times on the same machine, the repo name shows up multiple time on the same machine. The only way to know which repo you are looking at is to hover over the repo name and get the file location popup.

### Proposed solution

Adding the folder name will allow users to look at the repo list and see which folder they was to manage.

### Additional context

Current display
![current list](https://user-images.githubusercontent.com/68287649/112346911-cdc5a100-8c9c-11eb-834e-8912a823c184.png)

A better display
![future list](https://user-images.githubusercontent.com/68287649/112346934-d28a5500-8c9c-11eb-8fee-e8b03f86238b.png)

**Comment by tidy-dev** [comment]
@ac05219 Thank you for the suggestion - I believe we are tracking this issue here #7856. Thus, I am closing this one in favor of it.
