### ISSUE TITLE
Deleted files/changes getting cached and blocking branch changin

### ISSUE THREAD

**Issue by BenChirlinn** [desktop/desktop#11867]
### Describe the bug

Changes made by other contributors are somehow getting stuck in my app such that when I change branches using the app they reappear on each branch change. Not only do I have to be careful not to recommit these changes, which seem to reliably be file path changes (i.e. deletion and re-adds), but they also block branch changes. Often they don't even appear in the changed files side bar in the app (see screenshot). Eventually they may show up but then the only way to revert the changes is to do a manual `restore` in command line (right clicking and clicking "Discard Changes" doesn't reliably work).

I've tried `git rm --cache` for whichever files occur but with mixed results and new files eventually start to cause issues regardless.

Edit: After some poking around it looks like this is an access issue caused by my Github Enterprise account I'm using as reported in the logs (see below). One of the pre-checkout hooks seems to be doing process that requires enterprise authorization. This is failing and somehow being reported as changes to phantom files (perhaps from earlier unrelated commits or merges).

### Version & OS

Version 2.6.6 on Windows 10

### Steps to reproduce the behavior

1. Have other contributors move files to a new path/rename
2. While up to date with master switch to existing working branch
3. Deleted files should show up in change log

### Expected behavior

File changes I've not made that are coming from master shouldn't impact my working branch.

### Actual behavior

File path changes that I've not touched on my working branch randomly appear as (sometimes invisible) changes on my branch preventing branch changes via app and requiring command line to fix/switch branches.

### Screenshots

![image](https://user-images.githubusercontent.com/908329/112552433-0a1dfd80-8d80-11eb-95e6-52fa326a0a01.png)
NB: no changes displayed in app but phantom changes blocking branch changing. In command line `git status` reveals no changes and I'm able to freely `git checkout master`

### Logs

[2021-03-25.desktop.production - Copy.log](https://github.com/desktop/desktop/files/6208247/2021-03-25.desktop.production.-.Copy.log)

### Additional context

I'm using Windows Git Bash via Con Emu for Windows git/command line. I'm also working in a Git Enterprise account which requires SSO and a VPN. Reviewing the app log (above), it appears there might be permissions issues though I can normally work with Git no issue. I'll try relogging and see if that consistently fixes my issues.

Edit: Confirmed that logging out of my enterprise account and then back in fixes the issue apparently but _only_ if I log in via the browser and not if I log in using my username and password. So the bug seems to be that account access issues are being reported as or causing phantom blocking files changes.

**Comment by steveward** [comment]
Thanks for the report @BenChirlin. This is an interesting one! I can see the permissions issue you mention in the log occurring during the fetch operation:

```
2021-03-25T22:26:33.126Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Anonymous access denied
fatal: Authentication failed 
```

and then the checkout failure:

```
2021-03-25T22:26:58.809Z - error: [ui] `git -c credential.helper= checkout --progress master --` exited with an unexpected code: 1.
stderr:
error: Your local changes to the following files would be overwritten by checkout:
	src/sites/sunlight/pages/viewer-rewards-emotes-page/components/emotes-settings-dashboard/components/emotes-settings/components/subs-emotes-settings-section/components/subs-emote-grid/components/subs-tier-emote-grid/component.test.tsx
	src/sites/sunlight/pages/viewer-rewards-emotes-page/components/emotes-settings-dashboard/components/emotes-settings/components/subs-emotes-settings-section/components/subs-emote-grid/components/subs-tier-emote-grid/component.tsx
Please commit your changes or stash them before you switch branches.
Aborting
```

The weird thing is that it does look like you have a valid token when you attempt to switch branches:

`[AppStore.withAuthenticatingUser] account found for repository: twilight - bchirlin (has token)`

Are you able to consistently reproduce this? It'd also be helpful to know your specific hook configuration if you're able to share that.

**Comment by BenChirlinn** [comment]
Somewhat consistently yes. The files that cause it seems to be fairly consistent but then will mysteriously go away for a spell only to possibly come back later or with new files. I'm not sure currently what our hooks are set up to do but I'll take a look when I'm back on my work machine.

**Comment by steveward** [comment]
@BenChirlin just checking in to see if you are still encountering this issue in GitHub Desktop -- thanks!

**Comment by BenChirlinn** [comment]
It's definitely changed. Now it seems on most new boots I have to log into my account again. Because we're using github enterprise and require a VPN for connection I'm just going to close this for now. Too hard to know if this is a organization specific issue.
