### ISSUE TITLE
Folder name and repository name...

### ISSUE THREAD

**Issue by F1r3Pr1nc3** [desktop/desktop#11861]
### Describe the feature or problem you’d like to solve

The folder name and repository name can not be **differently**, which is an absolutely incomprehensible and unnecessary  limitation (and often wanted feature). 
Because folder names are sometimes **fixed or with the same name or only long numbers.**

### Proposed solution
Make a checkbox on New repository...

### Additional context
On creation you can give an description of the repository, but in the repository browser it is also not visible!
Sorry, this issue is steadily growing in me since I first used this tool. ~~As I more and more using Github this tool, it gets unusable for me~~.

Thank you for your tool and your understanding.

**Comment by tidy-dev** [comment]
@F1r3Pr1nc3  Thank you for the report! I believe we are tracking this issue in #7856. I am going to close this one in favor of that one. If you feel it is a separate issue, feel free to provide more detail and reopen if I misunderstood you.
