### ISSUE TITLE
Add ability to Commit with default/previous/preset Summary

### ISSUE THREAD

**Issue by irvnriir** [desktop/desktop#11862]
### Describe the feature or problem you’d like to solve

Enable Committing with empty Summary field, and in such case insert a timestamp, the last used, or predefined Summary .

This will help to easier use Github Desktop for all the cases when it is used/serving as a backup system .

**Comment by billygriffin** [comment]
@irvnriir Thanks for the issue. Since we think descriptive commit messages are helpful to promote best practices and facilitate better communication around code, I don't think it's wise for us to make the summary optional. Apologies we can't help you here, but due to that I'm going to close this issue.

**Comment by irvnriir** [comment]
Though its more git related, what about adding a ("per") Repository config item, that will define whether def summary is present/allowed ? (which would be synced with the Repo . that would allow the Repo administration to choose whether they want to prompt/force the custom Summary)

**Comment by billygriffin** [comment]
@irvnriir We try to keep config items to those that will be significantly different for large numbers of our users. For larger things like this, we try to nudge toward what we consider best practices in using descriptive commit messages. Thanks again for the feedback!

**Comment by irvnriir** [comment]
@billygriffin as i mentioned, the system can be used differently . if its used as backup one, such case/way becomes the worse practice .

**Comment by raveensrk** [comment]
@billygriffin I agree with @irvnriir. I use git hub desktop to sync and backup my notes. I would like to commit and push with a default or preset summary.
