### ISSUE TITLE
Hope to add gti proxy

### ISSUE THREAD

**Issue by varSmallRookie** [desktop/desktop#11869]
git config --global https.proxy

**Comment by steveward** [comment]
Thanks for the issue @varSmallRookie. 

If your proxy requires credentials you can follow these steps:

1. Go to the file menu and select `Repository` > `Open in Terminal` (macOS) or `Open in command prompt` (Windows)
2. Run the following command:

`git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`

Replace `proxyuser` with your proxy username and `proxypwd` with your proxy password. Also, `proxy.server.com:8080` needs to point to the URL of your proxy server.

Let me know if you have any issues getting this set up.
