### ISSUE TITLE
Feature request for Network Proxy settings

### ISSUE THREAD

**Issue by ch4rc0al1080** [desktop/desktop#11860]
### Describe the feature or problem you’d like to solve

If people want to use socks5/socks4/http proxy to push/pull repos, it will be convenient
### Proposed solution

Convenient for people to use proxy in GithubDesktop

**Comment by steveward** [comment]
Thanks for the issue @kinglyl. GitHub Desktop does provide support for proxies -- see [this document](https://github.com/desktop/desktop/blob/development/docs/technical/proxies.md) for more information. At this time we are not able to support authenticating proxies. If your proxy requires authentication you can run this command to set it in your `.gitconfig`:

`git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`

Replace `proxyuser` with your proxy username and `proxypwd` with your proxy password. Also, `proxy.server.com:8080` needs to point to the URL of your proxy server.

I hope that helps!
