### ISSUE TITLE
Bulk delete repos

### ISSUE THREAD

**Issue by eonist** [desktop/desktop#11868]
### Bulk delete repos

I have many repos in GitHub desktop. Deleting one by one is boring. At some point I reinstall the app to remove all repos.

### Proposed solution

Maybe there is a json file somewhere which I can just delete to start fresh? Or add reset app option in prefs?

### Additional context

Nope

**Comment by steveward** [comment]
@eonist if you want to clear out the cached data you can delete `%AppData%\GitHub Desktop` (on Windows). This will reset the application back to a fresh state without needing to reinstall. Please note that this will not delete the repositories from your local disk. I hope that helps!

**Comment by eonist** [comment]
Great tip! But MacOS here. Should have mentioned that. Sorry.

Is there an equivalent folder in MacOS?

**Comment by steveward** [comment]
@eonist  `View` -> `Toggle Developer Tools` -> `Application` -> `Clear Storage` is an easy way to clear things out on macOS. You'll need to restart the app.
