### ISSUE TITLE
[IMPORTANT] - Feature and Functionality - Allow the user to choose what browser to sign in with

### ISSUE THREAD

**Issue by iu18** [desktop/desktop#11871]
On my computer my account is broken so I can't access my settings to change my default browser so it always opens edge and crashes. I can't use edge either.

What you guys should do is add back the sign in from github desktop and/or add an option to choose a different browser for sign in. This will benefit users who are using a work computer where settings is blocked, edge just doesn't work, or settings is broken.

I understand its for security purposes but it is pretty important that gets re implemented. Most other apps have a sign in page in the app. Maybe work on security.

**Comment by steveward** [comment]
@InvalidUser18-alt thanks for the request. I'm going to roll this into https://github.com/desktop/desktop/issues/11027 which is an open tracking issue for this.
