### ISSUE TITLE
Expand current branch panel

### ISSUE THREAD

**Issue by RomnKo** [desktop/desktop#11876]
### Describe the feature or problem you’d like to solve
The Current Branch dropdown button is too small and only shows the first thirteen characters. Considering that feature branches are typically titled "feature/..." thusly the rest of the branch name only has 5 characters left to uhh explain itself.

### Proposed solution
Expand the "Current Branch" panel to the right, exposing more of the branch name. There is empty space to the right of the "Fetch origin" button, so nothing will be obscured. Or ideally this panel would be user expandable.

### Additional context
Here's a quick mockup:
![image](https://user-images.githubusercontent.com/1963962/112674968-cf6da100-8e23-11eb-939d-f267e2f85b94.png)

**Comment by billygriffin** [comment]
Thanks @RomnKo for the issue. This is the same as https://github.com/desktop/desktop/issues/2745, which also now has a related PR that hopefully we'll be able to take a look at in the coming weeks. Since this is a duplicate I'm going to close it, but please follow along there!

**Comment by aarfing** [comment]
Actually, [#2745](https://github.com/desktop/desktop/issues/2745) and this is not exactly the same. I'm - like @RomnKo - also suggesting that the "Current branch"-button should get wider (or preferably user expandable). [#2745](https://github.com/desktop/desktop/issues/2745) is about expanding the columns that appear once the button has been clicked.
