### ISSUE TITLE
[Request] Dark theme for GitHub Desktop

### ISSUE THREAD

**Issue by avatar-lavventura** [desktop/desktop#11878]
I was wondering can we apply dark theme for `GitHub Desktop`? If yes how? -Thanks

**Comment by tidy-dev** [comment]
Select the Dark option in the Appearance settings.  (Note: my screenshots are from Beta and look a little different than current production)

For Windows:
File > Options
![image](https://user-images.githubusercontent.com/75402236/112833574-ebac5080-9064-11eb-97d8-24487082918c.png)


For Mac:
GitHub Desktop -> Preferences
![image](https://user-images.githubusercontent.com/75402236/112833657-041c6b00-9065-11eb-98de-c314eaeaf0ad.png)

**Comment by avatar-lavventura** [comment]
@tidy-dev Where can I download the beta version for mac?

**Comment by avatar-lavventura** [comment]
@tidy-dev Thanks! Can background be black like its on (https://github.com), or can be an option for users to select?

<img width="500" alt="image" src="https://user-images.githubusercontent.com/18537398/113329226-fa755a80-9325-11eb-9d1d-0cc3d8098ae6.png">

**Comment by tidy-dev** [comment]
Not sure if I understand your question (maybe looking for a darker dark theme?). But, we only support one dark theme.

**Comment by avatar-lavventura** [comment]
@tidy-dev Yes sir I was looking for the darkest theme (like background is complete black). I believe `github desktop` uses only `dark dimmed`

=> [https://github.com/settings/appearance](https://github.com/settings/appearance) has three theme options:

- Default light
- Default dark
- Dark dimmed

Example (from the original https://github.com page color setup):

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/18537398/113488788-d140ff80-94c8-11eb-8804-77277ce87750.png">

--------

Since its(dark theme) used by the github, I was just hoping `github desktop` could easily integrage it. Please see it as a feature request in future.

**Comment by tidy-dev** [comment]
@avatar-lavventura Gotcha - I have marked this as an enhancement for consideration. Thanks for the feedback!

**Comment by billygriffin** [comment]
Hi @avatar-lavventura, thanks for the request but our team on GitHub Desktop is quite small and we haven't heard enough feedback to make it worth the investment to support an additional theme that isn't for a more specific purpose (like Accessibility). We're not opposed to revisiting this in the future, but for now I'm going to close this to signify that it isn't something we plan to support. Thanks again.

**Comment by avatar-lavventura** [comment]
@billygriffin Thanks for considering anyway. Current dark theme also saves the day, during night time saves the eyes :-)

**Comment by billygriffin** [comment]
@avatar-lavventura Of course, and appreciate your understanding! I use it every day. 😄
