### ISSUE TITLE
option for default protocol

### ISSUE THREAD

**Issue by HUMORCE** [desktop/desktop#11885]
### Describe the feature or problem you’d like to solve

an option for default protocol: https/ssh

### Proposed solution

manualy edit remote repo is work, but an option for default is better for fastwork or beginner, and the option exists in github-cli.

**Comment by steveward** [comment]
Thanks for the feedback @HUMORCE. I'm going to group this into https://github.com/desktop/desktop/issues/2579 where this has previously been brought up and where we are tracking broader SSH improvements. Thanks for using GitHub Desktop!
