### ISSUE TITLE
[solved] github desktop does not work - Authentication failed. permission denied

### ISSUE THREAD

**Issue by lazyJoon** [desktop/desktop#11883]
```
OS: Windows 10 pro
GitHub Desktop version: 2.6.6
```
---
### github desktop did not work with ssh. (git bash and poweshell works well.)

- github desktop log

```
info: [ui] [AppStore] loading 6 repositories from store
info: [ui] [BranchPruner] Last prune took place in 10 hours - skipping
info: [ui] launching: 2.6.6 (Windows 10.0.18363)
info: [ui] execPath: 'C:\Users\user\AppData\Local\GitHubDesktop\app-2.6.6\GitHubDesktop.exe'
info: [ui] Executing push: git -c credential.helper= push origin main --set-upstream --progress (took 1.584s)
[ui] `git -c credential.helper= push origin main --set-upstream --progress` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
```

---

### so I changed ssh to https back but same error again.

![image](https://user-images.githubusercontent.com/81410965/112746368-38eadc80-8fe9-11eb-83ce-818add9b1167.png)

- github desktop log

```
info: [ui] [AppStore] loading 6 repositories from store
info: [ui] [BranchPruner] Last prune took place in a day - skipping
info: [ui] launching: 2.6.6 (Windows 10.0.18363)
info: [ui] execPath: 'C:\Users\user\AppData\Local\GitHubDesktop\app-2.6.6\GitHubDesktop.exe'
```
---

### and I tried change internal ssh to openssh but... another error occured.

> I was able to reproduce this issue, and it comes down to Desktop choosing to use it's internal `ssh` program (which doesn't know about the `ssh-agent` service associated with OpenSSH on Windows which runs as a Windows Service) over anything that might be defined on `PATH`.
> 
> The workaround for this is to change your global configuration to use the OpenSSH for Windows build of SSH:
> 
> ```
> git config --global core.sshCommand "'C:\Windows\System32\OpenSSH\ssh.exe'"
> ```
> 
> Or in your `~/.gitconfig`:
> 
> ```
> [core]
> 	sshCommand = 'C:\\Windows\\System32\\OpenSSH\\ssh.exe'
> ```
> 
> [https://github.com/desktop/desktop/issues/5641#issue-360207252](url)
---

- github desktop log

```
info: [ui] [AppStore] loading 6 repositories from store
info: [ui] [BranchPruner] Last prune took place in a day - skipping
info: [ui] launching: 2.6.6 (Windows 10.0.18363)
info: [ui] execPath: 'C:\Users\user\AppData\Local\GitHubDesktop\app-2.6.6\GitHubDesktop.exe'
```

- git bash or powershell (or command propt)

```
$ git push
fatal: The current branch main has no upstream branch.
To push the current branch and set the remote as upstream, use

git push --set-upstream origin main
```

```
$ git pull
CreateProcessW failed error:193
ssh_askpass: posix_spawn: Unknown error
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.


Please make sure you have the correct access rights
and the repository exists.
```

---

And, when I try to push or pull from github desktop or vs code, the loading spinner spins indefinitely, and the push/pull never finish.
Please let me solve this :(

_Originally posted by @lazyJoon in https://github.com/desktop/desktop/issues/5641#issuecomment-808805611_

**Comment by lazyJoon** [comment]
> - Install posh-git
> 1. `Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned -Force`
> 2. `Set-PSRepository -Name PSGallery -InstallationPolicy Trusted`
> 3. `Update-Module PowerShellGet -Force`
> If  'Module 'PowerShellGet' was not installed by using Install-Module' error occured, 
> 3-A. `Install-Module PowerShellGet -Force -SkipPublisherCheck` and back to 3.
> 4. `Install-Module Posh-Git -Scope CurrentUser`
> 5. `'Import-Module Posh-Git' | Out-File -Append -Encoding default -FilePath $profile`

> - Add scripts to powershell $profile (runs when powershell is opened.)
> 6. open powershell directory `C:\User\Documents\WindowsPowerShell`
> 7. open `Microsoft.PowerShell_profile.ps1`
> 8. now, You can see `Import-Module Posh-Git` in that file.
> 9. Add followed lines.
> 
> > ```
> > Set-Alias ssh-agent "C:\ProgramFiles\git\usr\bin\ssh-agent.exe"
> > Set-Alias ssh-add "C:\ProgramFiles\git\usr\bin\ssh-add.exe"
> > Start ssh-agent
> > Set-Alias ssh "C:\ProgramFiles\git\usr\bin\ssh.exe"
> > ```
> > - image
> > ![image](https://user-images.githubusercontent.com/81410965/112755103-2f2d9d00-901a-11eb-9f2e-784b4ae93132.png)
> 
> 10. reopen powershell
> 11. `git config --global core.sshCommand "'C:\Windows\System32\OpenSSH\ssh.exe'"`
> 12. now, github desktop is working (obsidian, VS Code, ..., ETC)
---
You must open powershell each time you reboot your computer.
If you don't want to do, use `task scheduler` or `group policy` or `Start Menu`
---
[How to install posh-git](https://git-scm.com/book/en/v2/Appendix-A%3A-Git-in-Other-Environments-Git-in-PowerShell)
[posh-git github](https://github.com/dahlbyk/posh-git)
[powershell profile scripts](https://stackoverflow.com/questions/34638462/using-git-with-ssh-agent-on-windows/34640053#34640053)
[use openssh instead of internal ssh](https://github.com/desktop/desktop/issues/5641#issuecomment-421801704)

**Comment by caiowebcoder** [comment]
Apenas saia da sua conta no git e entre com a sua conta novamente. no meu caso funcionou, mas lembre-se de ter a sua senha em mente.
