### ISSUE TITLE
Github Desktop doesn't show history of one specific repository

### ISSUE THREAD

**Issue by pfiterman** [desktop/desktop#11881]
### Describe the bug

There is a specific repository I am not viewing the commits and thus the history by GitHub Desktop.
I am just getting it by git log command through Git Bash.

### Version & OS

Windows 10
GitHub Desktop 2.6.6

### Steps to reproduce the behavior

History doesn't appear when I click in the history tab.

### Expected behavior

It should show all repository's commits on history.

### Screenshot
![GitHubDesktopHistoryRepositoryIssue](https://user-images.githubusercontent.com/27889296/112726825-1d56d780-8efe-11eb-9689-bc18283bf766.jpg)

**Comment by sergiou87** [comment]
Hi @pfiterman! 👋 

That's interesting… could you provide logs when that happens?

Is there anything specific in that repo that you can think of?

Thank you!

**Comment by pfiterman** [comment]
Hi @sergiou87 

It has started two weeks ago.
In this repository I have others submodules but I don't believe it's the reason for.

I uploaded the log file.
[2021-03-16.desktop.production.log](https://github.com/desktop/desktop/files/6222286/2021-03-16.desktop.production.log)

I hope be useful for solving the bug.

Thanks for helping me.

**Comment by steveward** [comment]
Thanks for the log @pfiterman. It looks like this is the issue:

```
2021-03-16T19:52:44.564Z - error: [ui] Could not load new contents for syntax highlighting
Error: EISDIR: illegal operation on a directory, read
```

EISDIR stands for "Error, is directory" -- unfortunately it isn't showing what specifically is causing this issue. There's some discussion about these errors on StackOverflow, and most seem to point to specific configuration issues ([example](https://stackoverflow.com/questions/34959038/npm-stuck-giving-the-same-error-eisdir-illegal-operation-on-a-directory-read-a)). 

Is this in a public repository where we could take a look to see if we can reproduce the issue?

**Comment by pfiterman** [comment]
Hi @steveward 

I'm going take a look in the StackOverflow discussion about this error and try figure out what can be happening.
It's a private repository I'm using to control reactjs' projects source code.

All my others private repositories are working properly.
Any advance in this issue I let you know.

Thanks!

**Comment by pfiterman** [comment]
Hello guys!

After update GitHub Desktop to version 2.7.1 my repository's history is working again.
I guess you all fixed the bug.

Good job! 

Thanks!

**Comment by sergiou87** [comment]
I don't know how that's possible, but I'm super happy that it works for you again! 😂 ❤️
