### ISSUE TITLE
Git Flow.

### ISSUE THREAD

**Issue by JenuelDev** [desktop/desktop#11887]
Git flow is really good and one of the most used way to add, fix, release.. and it makes it simple.. I hope github desktop will have this feature also.

check this: https://danielkummer.github.io/git-flow-cheatsheet/

**Comment by billygriffin** [comment]
Hi @BroJenuel, thanks so much for the issue. We're tracking this in https://github.com/desktop/desktop/issues/2139. It's still considered a `future proposal` meaning that it's closed but still under consideration.

**Comment by BroJenuel** [comment]
i think if github desktop will not support this, the software will be forgotten by companies, but itmay help students.

**Comment by JenuelDev** [comment]
> Hi @BroJenuel, thanks so much for the issue. We're tracking this in #2139. It's still considered a `future proposal` meaning that it's closed but still under consideration.

I hope this git support will be implemented soon.
