### ISSUE TITLE
logout issue .... not able to log out of application

### ISSUE THREAD

**Issue by sohail313** [desktop/desktop#11880]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by sergiou87** [comment]
Hi @sohail313 ! 👋 

Could you provide more details by filling the template so we can help you more effectively?

Thank you!!
