### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by whippingdot** [desktop/desktop#11896]
# Cherry Pick Warning Not Given

I was trying the new cherry pick feature, thinking that I would get a confirmation when I cherry pick, when I realized I didn't get one. GitHub Desktop just went straight into the process without confirming. I was lucky that there were merge conflicts, or else it would've been bad.

## Confirm Message

This will benefit us GitHub Desktop users by preventing accidental cherry picks (though you would have to have **very very very** messy hands) and will prevent 'test' cherry picks.

---

P.S. I have had an idea for adding the Git Graph. If you are hesitant of adding a Git Graph because there is no space in the application, you can add a button in the top row as there is a lot of white space:

**ON A BIG COMPUTER LIKE MINE**
![image](https://user-images.githubusercontent.com/64354499/112972726-31087500-916e-11eb-939a-d25a9e845021.png)

**REDUCED FRAME**
![image](https://user-images.githubusercontent.com/64354499/112972832-51d0ca80-916e-11eb-8f78-5d2da8797791.png)

When you press the button, it can take you to another tab with a whole scrollable git graph with any branch's name (even deleted ones) on hover and full commit details.

**VS CODE GIT GRAPH COMMIT DETAILS**
![image](https://user-images.githubusercontent.com/64354499/112973295-c99ef500-916e-11eb-9318-2c01bec28169.png)

_Note: This is how the full commit details can look, though I would prefer them on a popup tab below or with a better style. This doesn't look that nice so if you implement this, I would expect a better design_

**FULL GIT GRAPH LOOK**
![image](https://user-images.githubusercontent.com/64354499/112973624-30241300-916f-11eb-9c74-6072a158517d.png)

_Note: Picture taken from online - http://blog.axosoft.com/wp-content/uploads/2015/10/1-main-view.png. This is a picture of GitKraken. Again I would expect a better design from GitHub Desktop but this looks sweet anyway and I love that the colors pop out!_

## Like this issue if you think both of these or one of these should come in a future update

**Comment by tidy-dev** [comment]
@whippingdot Thanks for the feedback on cherry-picking. We took a low friction approach since cherry-picking is easy to undo and is a local action. If you give it another try, and you should see the undo feature in the success bar.

Also, great suggestion on the graph, we are tracking feedback for that on #1634 and would welcome additional input there. In fact, if you wouldn't mind, putting your history graph feedback as a comment there it would be easier to track these two separate issues.

**Comment by whippingdot** [comment]
> If you give it another try, and you should see the undo feature in the success bar.

Oh cool. I was too scared to try it then but I will be sure to try it when I am on my computer again!

> Also, great suggestion on the graph, we are tracking feedback for that on #1634 and would welcome additional input there. In fact, if you wouldn't mind, putting your history graph feedback as a comment there it would be easier to track these two separate issues.

Ok! I just wanted to mention the graph again as, no offense, but not much has been done to show you guys are working on this. I know that you have other things going on too but I just wanted to remind you that some of us are still waiting on this feature. I personally switched back to GitHub desktop cause of the awesome design, but I will be more inclined to stay if the git graph is added. I hope this feature rolls out by the start of June 😁😁🎉🎉

P.S. I did not mean this as an angry comment so do not take the tone of the comment that way.

**Comment by whippingdot** [comment]
Oh wait the issue you linked to is the wrong one which has been closed...I will post my feedback on the git graph comparison view issue.

**Comment by tidy-dev** [comment]
@whippingdot Either place will work! Even if it is closed, we still track the input. Yeah. You are right, the history graph is not currently on our roadmap. But, we still love the feedback and take it that input account during planning sessions. Thank you again!

**Comment by whippingdot** [comment]
> Even if it is closed, we still track the input.

Umm I meant locked but ok 🤷 

P.S. ~~Please add it to your roadmap lol~~

**Comment by tidy-dev** [comment]
@whippingdot Oh..  Sorry! I didn't realize it had been locked!

**Comment by billygriffin** [comment]
Hi @whippingdot! Since we decided to go with the "Undo" approach instead of a blocking confirm to reduce friction, I'm going to close this issue. Appreciate your feedback!
