### ISSUE TITLE
How do I open a specific path in GitHub Desktop?

### ISSUE THREAD

**Issue by Milo123459** [desktop/desktop#11909]
I planned on writing a VSCode extension to just open github desktop in the current CWD, but, I wasn't sure how to open githubdesktop in the current cwd via the cli. How can I do this?

**Comment by Tabbibaby** [comment]
jonmagic @Milo123459 @mutle @mtodd @probablycorey @

**Comment by Milo123459** [comment]
Huh?

**Comment by steveward** [comment]
@Milo123459 GitHub Desktop includes a command line tool that allows you to launch the application. Running `github /path/to/repo` will launch a specific repository in GitHub Desktop. I hope that helps!

**Comment by Milo123459** [comment]
> @Milo123459 GitHub Desktop includes a command line tool that allows you to launch the application. Running `github /path/to/repo` will launch a specific repository in GitHub Desktop. I hope that helps!

Thanks for the fast response. I ran `githubdesktop C:\\Users\\milo5\\Desktop\\GitHub\\Wie` and it didn't open that in github desktop. Ideas?

**Comment by steveward** [comment]
@Milo123459 just using `github C:\\Users\\milo5\\Desktop\\GitHub\\Wie` should work.

**Comment by Milo123459** [comment]
That didn't work..

**Comment by steveward** [comment]
I would make sure your path is correct. Try running `github .` inside your repository to verify it launches the current directory.
