### ISSUE TITLE
support custom name of repo without renaming the actual folder name

### ISSUE THREAD

**Issue by ledmirage** [desktop/desktop#11905]
### Describe the feature or problem you’d like to solve

When importing an existing repo into Desktop, the repo name is set to be the same of the repo folder name.
But there might be multiple repo on disk with same folder name, so if we can set a custom name it can avoid confusion.

### Proposed solution

Provide a mean to set a custom name for imported repo.
Actual folder name on disk remain unchanged.
For example, right click on the repo name, provide an option "Rename".

How will it benefit Desktop and its users?

Avoid confusion for user with multiple repo on disk with same folder name (under different parent folders)

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

screenshot showing what i mean by different repo of same (folder) name added:

![sc-pjlp-029](https://user-images.githubusercontent.com/279166/113078405-9eb3b000-9205-11eb-87d2-697039ff26b6.png)

**Comment by sergiou87** [comment]
Hi @ledmirage! 👋 

Thank you for your feedback. I think this request is the same as #7856 so I recommend you to subscribe to that issue to get notified when there is any progress on this feature 😄

**Comment by ledmirage** [comment]
thanks. i did a search before i raise the request but i didn't see that come up, might have missed it.
