### ISSUE TITLE
Cherry picking by drag and drop to the same branch breaks file and diff panes

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#11915]
### Describe the bug

When trying to cherry pick a commit with the newly added drag and drop functionality (#1685) if you drop the commit onto the branch it came from, the files and diff panes break.

### Version & OS

Version 2.7.1,  Windows 10 20H2

### Steps to reproduce the behavior

1. Create a repo
2. Make some commits
3. Go to History View
4. Drag a commit from history onto branch selector and drop it on current branch
4. The commit details view is now dimmed and cannot be interacted with (red 🚫 cursor)

### Expected behavior

You should be told that the commit you are trying to cherry pick is already on this branch OR that this commit comes from the branch your are picking from.

### Actual behavior

You can't interact with files that were changed in the commit and you cannot interact with diff view because they are now under dimming overlay that blocks mouse interaction. Switching the branch or repo solves the problem.

### Screenshots

![image](https://user-images.githubusercontent.com/57894394/113313883-9b065300-9303-11eb-98b9-617e7c38b901.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

Action after which this but occurs is a bit nonsensical. I discovered the bug because I had only one branch in my repro and I wanted to see what will happen when I drop the commit on it. Somebody could perform this move by accident thus mildly braking the program. 

This is my first bug report ever, sorry if I'm doing something wrong.

**Comment by billygriffin** [comment]
@andy-zero I was able to reproduce this, thanks so much for the detailed issue! We're looking into this now, and we'll hopefully have it fixed sometime next week on production, and likely sooner on beta.

**Comment by billygriffin** [comment]
@andy-zero and others encountering this bug, we just shipped a beta that fixes this. You can download the beta version from here if you'd like: https://github.com/desktop/desktop#beta-channel

Our goal is to get a production release with this fix out sometime next week. Thanks again for your report!

**Comment by Xyncgas** [comment]
updates are scary for softwares
