### ISSUE TITLE
wrong file being hosted

### ISSUE THREAD

**Issue by ejb9786** [desktop/desktop#11928]
I am having issues. I went through the necessary steps to have my html file hosted but looks completely different from what it should look like. i use this code "$ echo "template" > index.html" since in my file the "template" is my original html. When i follow the rest of steps and publish everything, the text just says template in Windows Edge. 
Not what i want:
https://ejb9786.github.io/
![screen capture template](https://user-images.githubusercontent.com/66187317/113497337-179a5c80-94d1-11eb-9617-b212f8ad0337.png)

What it should show:
file:///C:/Users/ejb97/OneDrive/Desktop/HTML/ejb9786.github.io/template.html
![Homework Template](https://user-images.githubusercontent.com/66187317/113497369-72cc4f00-94d1-11eb-9622-c849c5868d24.png)

**Comment by tqpcharlie** [comment]
IIRC, when you run $echo "text", you're telling the terminal to echo whatever is in that "text" field, not a specific file. I don't use the CLI often, so I'd look into a working command for this if I were you...

**Comment by steveward** [comment]
@ejb9786 this looks like a question with GitHub Pages. This issue tracker is for GitHub Desktop -- if you have a question about GitHub Pages I'd recommend asking for help in the [Community Forum](https://github.community/c/github-help/github-pages/31). I'm going to close this out -- let me know if you have any questions about GitHub Desktop.

**Comment by ejb9786** [comment]
I do happen to have a question about GitHub Desktop. I gave up on the CLI but the desktop doesn't have the Publish button after i commit. I searched the web and found that if  Remote in the Repository Setting does not have a url, than i would have to place one in but my question is what if i have a URL setup all ready and I'm still missing that button?

**Comment by steveward** [comment]
@ejb9786 if you have an existing GitHub Pages site then your repository is already published. You should see a `Push origin` button that allows you to push your new changes up to your remote repository on GitHub. I hope that helps!
