### ISSUE TITLE
ESC should cancel drag-n-drop of commit

### ISSUE THREAD

**Issue by gabrielAtManticore** [desktop/desktop#11925]
I just tried the feature of dragging a commit in the history view onto the branches, for cherry pick. This is cool, but the ESC key should cancel the drag operation. That is a standard expectation for users.

**Comment by billygriffin** [comment]
@gabrielAtManticore That's definitely a reasonable request - we'll chat about it in our next meeting. Letting go of the drag outside any hit area should also cancel it, so you don't need an explicit key press.
