### ISSUE TITLE
Trying to add local repository but adds instead C:/Users folder instead

### ISSUE THREAD

**Issue by astral-monad** [desktop/desktop#11930]
When I try to add a local repository by typing in the directory location, it then adds the entire C:/Users folder as a local repository instead.

**Comment by steveward** [comment]
@westher0870 thanks for the report. This can often happen when there's a nested `.git` directory inside your user folder. Can you search for any hidden `.git` directories on your file system to verify that you haven't accidentally created a `.git` directory in C:/?

**Comment by astral-monad** [comment]
Thanks @steveward. I found a hidden .git folder in my C drive and deleted it. I will see if adding a local repository works now.

**Comment by steveward** [comment]
@westher0870 I'm going to close this out, but let me know if that doesn't get things working!
