### ISSUE TITLE
Needs to detect Github Repositories inside the system

### ISSUE THREAD

**Issue by verbose117** [desktop/desktop#11939]
### Describe the feature or problem you’d like to solve

The github desktop app does not recongnize and find the Github Repositories in the system.

### Proposed solution

It would be a good solution for users because they don't want to import every repository one by one.
Because it is hard to import each and every remote github repositories in to the github desktop app.

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@haneenmahd thanks for the feedback. This has been previously discussed in https://github.com/desktop/desktop/issues/1574. At this time we do not have plans to add this feature, but you can drag-and-drop multiple repositories into GitHub Desktop to quickly add them. I hope that helps!

I'll add your feedback to #1574 and close this out.
