### ISSUE TITLE
show full file path on top of difference showing screen - as left pane is minimized most of the times

### ISSUE THREAD

**Issue by talekardj** [desktop/desktop#11931]
### The feature or problem you’d like to solve

as in GitHubDesktop app - left pane is minimized most of the times to save space for difference viewer screen - we can get the file name only by hovering over it

### Proposed solution

Please show full file path on top of difference showing screen

### Additional context
![image](https://user-images.githubusercontent.com/30791807/113551894-ff325b00-9612-11eb-9b94-31a22acc822d.png)

**Comment by steveward** [comment]
Thanks for the feedback @talekardj. We are tracking feedback about expanding the column widths in https://github.com/desktop/desktop/issues/2745, which would allow the full file path to be visible. You can follow along for updates there.
