### ISSUE TITLE
GitHubDestop.exe - Entry Point Not Found. Can not Push and Pull.

### ISSUE THREAD

**Issue by Bullinger85** [desktop/desktop#11945]
### Describe the feature or problem you’d like to solve   GitHubDestop.exe - Entry Point Not Found. The procedure entry point av_buffer_create could not be located in the dynamic link library. C:\Users\Allan\AppData\local\gitHubDesktop\app-2.7.1\GitHubDesktop.exe. This went wrong in Desktop installation.

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
Thanks for the issue @Bullinger85. Based on [this thread]( https://answers.microsoft.com/en-us/windows/forum/all/procedure-entry-point-av-buffercreate-not-located/fb8c7dc9-ea58-40d4-b167-debf9953d93e) it looks like this is a specific system issue. I'd recommend following the steps mentioned there to see if it gets things working. Let me know if it helps!

**Comment by Jasper-Nelligan** [comment]
I had this same error when trying to install version 3.x.x. I deleted that and tried installing 2.9.15 which worked.

**Comment by max4th** [comment]
i have this problem and i couldn't fix it windows 8.1 pro

any advice?

**Comment by AhmedmeHassan** [comment]
same problem on Window 8.1 Pro
