### ISSUE TITLE
batch response: Git LFS is disabled

### ISSUE THREAD

**Issue by vpadhiar47** [desktop/desktop#11956]
Hello,

I am attempting to push a .h5 file up to the GitHub Repo using Git LFS but, I keep getting the following error: 

Uploading LFS objects:   0% (0/1), 0 B | 0 B/s, done.
batch response: Git LFS is disabled
error: failed to push some refs to 'https://code.devtools.lumeris.com/scm/tlk/prime-analytics.git'

I am assuming Git LFS is disabled for my account based on my research of reviewing other Git users in the issues forum. If that's the actual case, can you please enable LFS ASAP because my team needs to review the to be pushed in files!

Thanks,
Viraj
![batchResponse_GitLFSIsDisabled](https://user-images.githubusercontent.com/33465143/113889884-45112f80-9789-11eb-8e94-2c61e19f2665.png)

**Comment by billygriffin** [comment]
Hi @vpadhiar47, thanks for the issue! I don't think this is a GitHub Desktop specific problem, but rather that Git LFS is disabled for your GitHub account. Based on taking a look in this issue https://github.com/git-lfs/git-lfs/issues/2481, I think you may need to email support@github.com to get this resolved.

**Comment by vpadhiar47** [comment]
You're welcome @billygriffin! Yes, I figured the same. Do I have to separately email this issue to support@github.com since I already raised a ticket in GitHub Support?

**Comment by billygriffin** [comment]
@vpadhiar47 This is the repo for GitHub Desktop, so while I'm sure that's probably confusing, we aren't able to assist with Git LFS account related things. So yes, please email support and hope they can get it resolved for you quickly. Thanks again.

**Comment by SichangHe** [comment]
Seemingly moved to https://support.github.com/.
