### ISSUE TITLE
commit takes minutes not seconds

### ISSUE THREAD

**Issue by ng0177** [desktop/desktop#11963]
`Version 2.7.1-linux1` takes minutes not seconds for a commit even if a single character in respository consisting of just one file has changed. The command line only takes a fraction of a second.

**Comment by billygriffin** [comment]
@ng0177 Thanks for the issue. Unfortunately we don't have official support for GitHub Desktop on Linux, so I'm not able to help you. I assume you're using this fork https://github.com/shiftkey/desktop, in which case you're certainly welcome to see if there are similar issues or create a new one there. Best of luck!
