### ISSUE TITLE
Can not publish branch to GitHub

### ISSUE THREAD

**Issue by Arkathas** [desktop/desktop#11979]
### Describe the bug

I created new repository and when I try to Publish the repository to the remote, this error appears. This repository holds an Unreal Project previously able to use GitHub repository but suddenly started to pop this same error.
Decided to create a new repository hoping that would fix the problem. Now I can not even publish the repository to restart working with it:

Enumerating objects: 5828, done.
Counting objects: 100% (5828/5828), done.
Delta compression using up to 24 threads
Compressing objects: 100% (5691/5691), done.
error: RPC failed; curl 55 Send failure: Connection was aborted
fatal: the remote end hung up unexpectedly
Writing objects: 100% (5828/5828), 3.90 GiB | 18.03 MiB/s, done.
Total 5828 (delta 368), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

### Version & OS

Version 2.7.2

### Steps to reproduce the behavior

1. Go to 'Current repository'
2. Click on 'Publish branch'
3. See error

### Expected behavior

Expected to publish the repository to be able to share it with collaborators in order to work on it.

### Actual behavior

Can not publish the repository due to the error:

Enumerating objects: 5828, done.
Counting objects: 100% (5828/5828), done.
Delta compression using up to 24 threads
Compressing objects: 100% (5691/5691), done.
error: RPC failed; curl 55 Send failure: Connection was aborted
fatal: the remote end hung up unexpectedly
Writing objects: 100% (5828/5828), 3.90 GiB | 18.03 MiB/s, done.
Total 5828 (delta 368), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

[Logs.log](https://github.com/desktop/desktop/files/6288733/Logs.log)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

When created repository, git ignored was set to Unreal.

License was left empty.

I do not know much about GitHub so I have not been able to try different "complicated" solutions.

**Comment by steveward** [comment]
@Arkathas thanks for the issue. It looks like you have previously committed a file to this repository that is over GitHub's file size limit of 100MB. Here is the specific error:

```
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.        
remote: error: Trace: 4e4aa679dcc5f7a3ba1af4db9993f8710c7e2d5bf860caf83ab1e21e6e2f94d7        
remote: error: See http://git.io/iEPt8g for more information.        
remote: error: File Content/DeadHillsLandscape/Maps/Overview/Overview.umap is 499.47 MB; this exceeds GitHub's file size limit of 100.00 MB        
To https://github.com/Arkathas/Nature.git
 ! [remote rejected]   main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/Arkathas/Nature.git'

(The error was parsed as 41: The push operation includes a file which exceeds GitHub's file size restriction of 100MB. Please remove the file from history and try again.)
```

In order to push to this repository you will need to remove the large file from your repository's history. There are a number of options you can use in [this help article](https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository). Once you have removed the large file I would recommend using [Git LFS](https://docs.github.com/en/github/managing-large-files) to work with this large file. GitHub Desktop includes Git LFS.

I'm going to close this out, but let me know if you have any questions about this.
