### ISSUE TITLE
能不能调整一下字体 字也太小了。。。。

### ISSUE THREAD

**Issue by siburuxue** [desktop/desktop#11971]
下网以后能出一个可以设置字体样式和大小的功能 读取用户所有的字体 可以设置

**Comment by sergiou87** [comment]
Hello @siburuxue! 👋 

I'm sorry, nobody in the team speaks Chinese, so I had to use Google Translate and this is what I got:
![image](https://user-images.githubusercontent.com/1083228/114187345-286f2600-9948-11eb-8b0a-1a660894be85.png)

Right now you can't select manually a font and size, but you can use this options in the `View` menu to increase the size of the font overall:
![image](https://user-images.githubusercontent.com/1083228/114187461-518fb680-9948-11eb-97c8-22aa8656ef7d.png)

I hope that helps, thank you!

**Comment by siburuxue** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        是这样的，我们国家的综合国力已经站在世界的前列，是时候说汉语了。你们可以学习一下。em….关于字体部分我改了下APP包里的源码 以满足我的需求。我在控制台中执行了代码 localStorage.setItem(‘localname’,’zhangpeng’);在左侧History加载的时候判断 每次提交的用户列表是不是有zhangpeng这个名字 如果有 那么把他标红 这样我就知道哪些提交是包含我的代码。另外，能不能加一个选项卡”MyPush"在History旁边，只显示我提交的Commit。
            
        
    
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                siburuxue
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2021年04月9日 21:29，Sergio ***@***.***> 写道： 




Hello @siburuxue! 👋

I'm sorry, nobody in the team speaks Chinese, so I had to use Google Translate and this is what I got:



Right now you can't select manually a font and size, but you can use this options in the View menu to increase the size of the font overall:



I hope that helps, thank you!



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by JustinHewei2046** [comment]
如果用网页版这个怎么解决？有办法吗？

> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 是这样的，我们国家的综合国力已经站在世界的前列，是时候说汉语了。你们可以学习一下。em….关于字体部分我改了下APP包里的源码 以满足我的需求。我在控制台中执行了代码 localStorage.setItem(‘localname’,’zhangpeng’);在左侧History加载的时候判断 每次提交的用户列表是不是有zhangpeng这个名字 如果有 那么把他标红 这样我就知道哪些提交是包含我的代码。另外，能不能加一个选项卡”MyPush"在History旁边，只显示我提交的Commit。 siburuxue ***@***.*** 签名由 网易邮箱大师 定制 在2021年04月9日 21:29，Sergio ***@***.***> 写道： Hello @siburuxue! 👋 I'm sorry, nobody in the team speaks Chinese, so I had to use Google Translate and this is what I got: Right now you can't select manually a font and size, but you can use this options in the View menu to increase the size of the font overall: I hope that helps, thank you! —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by siburuxue** [comment]
> 如果用网页版这个怎么解决？有办法吗？
> 
> > font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 是这样的，我们国家的综合国力已经站在世界的前列，是时候说汉语了。你们可以学习一下。em….关于字体部分我改了下APP包里的源码 以满足我的需求。我在控制台中执行了代码 localStorage.setItem(‘localname’,’zhangpeng’);在左侧History加载的时候判断 每次提交的用户列表是不是有zhangpeng这个名字 如果有 那么把他标红 这样我就知道哪些提交是包含我的代码。另外，能不能加一个选项卡”MyPush"在History旁边，只显示我提交的Commit。 siburuxue _**@**_.*** 签名由 网易邮箱大师 定制 在2021年04月9日 21:29，Sergio _**@**_.***> 写道： Hello @siburuxue! 👋 I'm sorry, nobody in the team speaks Chinese, so I had to use Google Translate and this is what I got: Right now you can't select manually a font and size, but you can use this options in the View menu to increase the size of the font overall: I hope that helps, thank you! —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

这个软件已经弃用了 用idea家的全家桶 挺好用的
