### ISSUE TITLE
Would be adding support for commit templating utilities a good idea? 

### ISSUE THREAD

**Issue by Milo123459** [desktop/desktop#11982]
Hey,
I made a thing called [glitter](https://github.com/Milo123459/glitter) which can template out commit messages and I was wondering if me making a PR for desktop adding support for glitter (ie, a UI allowing you to template out your commit messages) would be a good idea.

I'm asking because I don't want to spend too much time on it and then it be denied because it's not what desktop wants.

Thanks!

**Comment by billygriffin** [comment]
Hi @Milo123459, thanks for the issue and glitter looks neat. Generally, we're really conservative about bringing in new dependencies, especially those that aren't very mature.

I'd love to hear how you envision this being used, especially if you think it might be used regularly by a significant portion of Desktop's users.

**Comment by Milo123459** [comment]
Thanks for the fast response! Thanks for the kind words about glitter.
Glitter is something you install via a binary, so it just has to be available in the $PATH, something like scoop or homebrew can do this. I envision this, glitter has a thing called type_enums, ensuring an argument is one of the values specified in the type enums.
When you get onto an argument with a type_enum, a drop-down appears which has all valid type_enums and you can click to insert it. 
A command coming in the next version called `glitter template ...` will template out the arguments allowing for construction of the commit message. I also planned on adding some sort of lock onto the commit button if not all terms are met, ie, there is an invalid type_enum or something or not enough arguments.

Thanks!

**Comment by Milo123459** [comment]
@billygriffin should I add it?

**Comment by billygriffin** [comment]
Hi @Milo123459, I'm really sorry for the delay. 😳 After further consideration I think we're going to have to say no. I really appreciate the idea and I do think it's a neat concept, but doesn't quite fit into how we try to make things as broadly usable as possible. Sorry again for the delay and thanks for sharing how you think it might be useful! ❤️

**Comment by Milo123459** [comment]
Alright, cool, thanks.

**Comment by Milo123459** [comment]
@billygriffin Fast-forward a few months... well, I've had an idea that can potentially solve a few problems you may have. I'd be more then happy to implement other templating tools like commitlint and whatever. Should I just create a draft PR with a very simple mockup of how I imagine it to look, and we can do some comments and then make another decision?

**Comment by billygriffin** [comment]
@Milo123459 If you'd like, you're welcome to articulate the benefits and likely tradeoffs of an approach to tackle commit templates, but given that this is something that only a narrow slice of Desktop users would benefit from, we're not convinced of the value. That said, open to ideas of how you envision it looking. I just don't want you to do too much work when our likely position is that we're unlikely to include a feature for this at this point.

**Comment by Milo123459** [comment]
Maybe a setting to enable them?
