### ISSUE TITLE
hi, i have github desktop version 2.7.2 windows 2016 enterprise and 64 bit system, anyway i can't clone online github repository to desktop github, the error image keeps popping up , how can i solve it ?

### ISSUE THREAD

**Issue by tamuska** [desktop/desktop#11983]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
Thanks for the issue @tamuska.

Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by tamuska** [comment]
[image: error.PNG]

**Comment by tamuska** [comment]
[
![error](https://user-images.githubusercontent.com/70161895/114437929-363ada80-9bd8-11eb-81f3-0af4f5a04589.PNG)
](url)

**Comment by tamuska** [comment]
[2021-04-08.log](https://github.com/desktop/desktop/files/6298732/2021-04-08.log)
[2021-04-10.log](https://github.com/desktop/desktop/files/6298733/2021-04-10.log)

**Comment by steveward** [comment]
@tamuska thanks for sharing those log files. It looks like there are a number of errors:

```
2021-04-08T16:16:30.833Z - error: [ui] `git config -z --global protocol.version` exited with an unexpected code: 3221225477.
TypeError: Failed to fetch
2021-04-08T16:07:44.209Z - warn: [ui] Error refreshing account 'tamuska'
TypeError: Failed to fetch
2021-04-08T16:07:44.209Z - warn: [ui] fetchRepositories: TypeError: Failed to fetch
2021-04-08T16:07:44.210Z - error: [ui] Error reporting stats:
TypeError: Failed to fetch
2021-04-08T16:07:45.107Z - error: [ui] Error checking for updates
undefined: 
```

It looks like there is a specific issue with your installation of GitHub Desktop. Are you running any antivirus or other security software that could have preventing the installation from completing successfully?

If so, I would try temporarily disabling your antivirus and reinstalling GItHub Desktop by following these steps:

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `%AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that helps at all.

**Comment by tamuska** [comment]
thank you for helping me but it didn't work. i have uninstalled my antivirus and reinstalled github and again the same issue keeps popping up.

**Comment by tamuska** [comment]
thank you for your effort, but it didn't work, i uninstalled my antivirus
and reinstalled githib desktop but the same issue keeps popping up.

**Comment by steveward** [comment]
@tamuska can you share the specific antivirus you are running? I haven't seen this specific error in GitHub Desktop before but based on a quick search it seems other users encountered this in VSCode and it was the result of antivirus.

**Comment by tamuska** [comment]
i am running CCleaner, hope it helps.

**Comment by steveward** [comment]
@tamuska thanks for the update. I'm not aware of any specific issues with CCleaner, unless it's removing installation files after a scan. Does it have any active virus/malware prevention that could be causing this? I used CCleaner years ago but I've heard it has changed quite a bit.

Searching the specific error code pulls up a few hits related to antivirus software, so my hunch is that it's still something on your system blocking GitHub Desktop from running successfully. It may also be worth opening an elevated command prompt and running `sfc /scannow` to see if there are any system issues that need to be repaired.

**Comment by tamuska** [comment]
thanks alot for so much help and advice , i think i will let the issue be
for now , but when i take it to the service center i will tell them about
antivirus , have a nice day ))

**Comment by steveward** [comment]
Thanks for the update @tamuska, let us know if we can help any further.
