### ISSUE TITLE
Include Move to Recycling Progress

### ISSUE THREAD

**Issue by TheCrafters001** [desktop/desktop#11980]
### Describe the feature or problem you’d like to solve

When you select "Remove" on a repo, and check "Also move this repository to Recycling Bin", display a progress bar to show how many files it has left to move, along with estimated time.

### Proposed solution

It can benefit showing a progress bar, instead of the program locking up (like it currently does) until it finishes moving everything over to the recycling bin,

### Additional context

Here is a mockup I have created.
![image](https://user-images.githubusercontent.com/46639269/114249862-d0e1b200-9969-11eb-9f7e-17e8e01d7dcf.png)

**Comment by steveward** [comment]
From #12642:

>When you click the "Remove" button in the "Remove repository" dialog, it locks the UI thread and doesn't show any progress. It would be nice if the UI thread didn't lock up & a progress bar, or at least a spinner, displayed.
