### ISSUE TITLE
Virus & threat protection services has stoppped

### ISSUE THREAD

**Issue by PohTiongHSC** [desktop/desktop#11987]
### Describe the bug

Whenever i open the Github Desktop the Windows security virus & threat protection service will stopped.

### Version & OS

Github desktop 2.7.2

### Steps to reproduce the behavior

1. Open Github desktop
2. Go to windows security and check the virus & threat has stopped

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@PohTiongHSC thanks for the issue. GitHub Desktop will not interfere with your antivirus -- is it possible something else on your system could be causing this?

We have seen cases where GitHub Desktop can be blocked by antivirus/firewall software. Let me know if that's possibly what you are referring to here. Any extra information you can share would be helpful.

**Comment by PohTiongHSC** [comment]
@steveward I think not related to GitHub Desktop. Windows update fixed my problem. Thanks.
