### ISSUE TITLE
In the repository selector, show the branch currently selected for each repo

### ISSUE THREAD

**Issue by dclaux** [desktop/desktop#11995]
### Describe the feature or problem you’d like to solve

I tend to clone a single repository multiple times and switch from one to the other in GitHub desktop. This allows me to work on multiple features at the same time without having to worry about pending/uncommitted changes. I clone these various copies into different folders, but the names shown in the repository selector are the repository name, not the folder name.

In the end, I get multiple times the same name listed in the repository list, and I have no idea which one is which:

![image](https://user-images.githubusercontent.com/1334689/114593153-a0876580-9c40-11eb-9080-22c3991e1f36.png)

It would be great to have a quick way to distinguish these visually.

### Proposed solution

I can think of two solutions:
- Show the folder name in the selector
  - That's better but not ideal, because I frequently switch branches in each of those clones
- A better solution IMO would be to show the name of the branch currently selected

![image](https://user-images.githubusercontent.com/1334689/114593671-328f6e00-9c41-11eb-8e6a-a7b4032b0729.png)

**Comment by sergiou87** [comment]
Hey @dclaux ! 👋 

Thank you for your suggestion, we've received similar requests and we're tracking them in #7856 so I recommend you to subscribe to that issue to get any updates on this feature 😄 

Would setting an alias for the repos be enough for your use case?

**Comment by jkamleh** [comment]
@sergiou87 Appears that #7856 is closed now but doesn't implement the above feature (based on the sample video in the PR #12000).

I too would like to see the 'Current branch' listed alongside the repository name in the 'Current repository' dropdown alongside the repository name (whether it's an alias or the name of the original repository - shouldn't matter).

The left hand side 'Current repository' dropdown is aware of changes (i.e. uncommitted files, new files to fetch from origin etc), i haven't looked at the code but how hard would it be to simply add 'Current branch' name alongside each repo? So you can see the branch that is checked out across the board for all your repositories without clicking in to each one?

**Comment by gpinkas** [comment]
There is another duplicate #10037 where I posted more or less the same suggestion:

![image](https://user-images.githubusercontent.com/54795296/136231826-33096f67-0c53-43f0-a1a1-021b7641eb10.png)

**Comment by tidy-dev** [comment]
Since this ticket's issue more generalized to distinguishing between duplicate repos and we now have repo aliasing that can handle that scenario (Right click on repo in repo list and `Create Alias`). I am going to close this one and leave #10037 open for tracking the branch name suggestion.
