### ISSUE TITLE
Push all tags feature

### ISSUE THREAD

**Issue by frankrakowitz** [desktop/desktop#11996]
### Describe the feature or problem you’d like to solve

Using Github Desktop I want to able to push all existing tags in an local repository to the remote repository.

### Proposed solution

Stay with Github Desktop always and not be forced to switch to e.g. git bash or other clients.

### Additional context

I am able to push complete existing local repsoitories with github desktop, so why should I not be able to push the existing tags?
Github Desktop: Version 2.7.2
OS:  Windows 10 Pro

**Comment by steveward** [comment]
Thanks for the report @frankrakowitz. This is being tracked in https://github.com/desktop/desktop/issues/11121 so you can follow along there for updates about this issue.
