### ISSUE TITLE
"Do not show me this again" on move to applications popup

### ISSUE THREAD

**Issue by MoonBarc** [desktop/desktop#11998]
### Describe the feature or problem you’d like to solve

When starting GitHub Desktop, it is very annoying to see the same pop-up many times to move itself to the Applications folder. I am currently using a school-provided computer without administrator access and I do not permission to move the app the the Applications folder.

### Proposed solution

Add a "Do not show me this again" checkbox. This could help users in my situation by not needing to click the close the warning every single startup.

### Additional context

Mockup:
![gd-mockup](https://user-images.githubusercontent.com/39464198/114727056-e2311280-9d0b-11eb-98de-ccc9cabc7f27.png)

Thanks!

**Comment by billygriffin** [comment]
Hi @MoonBarc, thanks so much for the issue! It makes perfect sense to us, and sorry you're running into this. We'll have a PR up soon and this will be included in our next production release, but that might not be for a few weeks. We'll try to get it onto the beta version well before that though if you're able to use that. Thanks again!
