### ISSUE TITLE
Repository nickname

### ISSUE THREAD

**Issue by jdavisp3** [desktop/desktop#11991]
### Describe the feature or problem you’d like to solve

Having multiple clones of the same github.com repository in different directories is hard to navigate because they all have the same name in the desktop UI.

### Proposed solution

I would propose allowing either the user to choose a display name for the repository or to show additional details (like the file path) in the list of repositories.

**Comment by sergiou87** [comment]
Hey @jdavisp3! 👋 

Thank you for your suggestion, but we're already tracking that work in #7856 so I recommend you to subscribe to that issue to get any updates on this feature 😄

**Comment by jdavisp3** [comment]
🚀 Thank you!!
