### ISSUE TITLE
Can't use 2 different platforms on one application

### ISSUE THREAD

**Issue by sallarahmed** [desktop/desktop#12003]
### Describe the feature or problem you’d like to solve
I can't clone repo of continuously work on 2 repos that are on 2 different platforms like if i want to clone a repo from bitBucket and i am already loggedIn to my code commit account and working on a repo if i logIn to butBucket account i will no longer access my code commit account and it will behave abnormal. 

### Proposed solution
Two accounts should work parallel. if i am already loggedIn to code commit and i'm cloning repo from but bucket with different so that both repos should work accordingly.

### Additional context
I think described enough to understand the issue.

**Comment by steveward** [comment]
@sallarahmed thanks for the issue. GitHub Desktop does not provide official ways of logging in to other Git hosting services like BitBucket, but we do allow you to authenticate to these services. See [these guides](
https://github.com/desktop/desktop/blob/development/docs/integrations) for how to do that.

Each service requires its own authentication token, so you should be able to use BitBucket and another service together as long as you have a valid authentication token for each one. Let me know if you have any questions about this!
