### ISSUE TITLE
Hover tooltip of branch name not showing anymore

### ISSUE THREAD

**Issue by chrisrueger** [desktop/desktop#12008]
### Describe the bug

With a recent update, hovering over a branch name with the mouse does not show the branch name anymore.
In the past this was showing. 

The problem is when we have pretty long branch names, where the interesting part is at the end e.g.

- ticketID-verylong-branch-name
- ticketID-verylong-branch-name-bugfix1
- ticketID-verylong-branch-name-bugfix2

So if I am interested in e.g. in bugfix2, I just see the beginning of the name and need to try them or guess by the (12 hours ago) timestamp.

### Version & OS

Github Desktop Version 2.7.2
MacOSX 11.2.3 (Big Sur)

### Steps to reproduce the behavior

1. Open _Current branch_ dropdown
2. hover over any branch name with the mouse and wait 2-4s over each item (don't move the mouse)

### Expected behavior

An HTML tooltip (usually as from the HTML title attribute) should appear. 

### Actual behavior

Tooltip does not appear.

### Screenshots

![image](https://user-images.githubusercontent.com/188422/114932555-ece8c600-9e37-11eb-80dd-27173d3b9739.png)

The screenshot shows how it is looking at the moment without the hover tooltip appearing. Unfortunately I don't have a screenshot of a version where it was still working. 

But the tooltip is showing in _merge other branch into current branch_ modal:

![image](https://user-images.githubusercontent.com/188422/114933639-2cfc7880-9e39-11eb-9296-f4e700f2c585.png)

That's how it should be.

### Logs

-

### Additional context

-

**Comment by say25** [comment]
This is also an issue on Windows 10 builds

**Comment by steveward** [comment]
Thanks for the report @chrisrueger. I can confirm this is happening as well, and it definitely is not great if you have long branch names. I'll mark this as a `priority-2` bug.
