### ISSUE TITLE
Help me get my gmail account back hacked before 

### ISSUE THREAD

**Issue by victoriahogshead** [desktop/desktop#12004]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@victoriahogshead this issue tracker is for GitHub Desktop, so we are unable to help with this.
