### ISSUE TITLE
add issue-tracker

### ISSUE THREAD

**Issue by jfwild** [desktop/desktop#12005]
### Describe the feature or problem you’d like to solve
to track your issues, you have to login-in on github.com - would be nice to add this to the  desktop  app.

### Proposed solution
add issues to desktop app

**Comment by steveward** [comment]
Thanks for the feedback @jfwild. We discussed issue creation within GitHub Desktop in https://github.com/desktop/desktop/issues/8989. You can follow along there for any new updates about this, but at this time we do not have plans to add a way to directly view issues within GitHub Desktop. 

We do provide issue integration into commit messages. You can reference issues in commit messages by using the `Closes #<issue_number>`. When you type this out it will bring up a list of issues for you to scroll through if you want to close out a specific issue with a commit. When this commit is merged into your default branch it will automatically close the referenced issue. I hope that helps!
