### ISSUE TITLE
[ENHANCE] add stylelint

### ISSUE THREAD

**Issue by danny007in** [desktop/desktop#12016]
If ok,

Then I will implement the best configuration.

along with https://github.com/XhmikosR/find-unused-sass-variables

this will improvise css.

**Comment by danny007in** [comment]
Added in https://github.com/desktop/desktop/pull/12018

**Comment by tidy-dev** [comment]
@danny007in Thank you for the suggestion. However, I closed the PR out as it is not something we are are interested at this time (see the comment https://github.com/desktop/desktop/pull/12018#issuecomment-822570799 for more detail)

**Comment by ISAACMETHOD** [comment]
ok
