### ISSUE TITLE
Question about possible Linux support 

### ISSUE THREAD

**Issue by 343GuiltySpark-04** [desktop/desktop#12019]
Will there ever be a mainstream Linux version or is that not possible or something just curious

**Comment by sergiou87** [comment]
Hi @343GuiltySpark-04! 👋 

You can read more about Linux support in https://github.com/desktop/desktop/issues/1525

I hope that helps!

**Comment by 343GuiltySpark-04** [comment]
Literally just realize i asked this before lmao *facepalm*
