### ISSUE TITLE
Windows: "Open with Default Program" fails if file path contains RIGHT SINGLE QUOTATION MARK (U+2019)

### ISSUE THREAD

**Issue by david-allison** [desktop/desktop#12025]
### Describe the bug

"Open with Default Program" fails if file path contains `RIGHT SINGLE QUOTATION MARK (U+2019)`

### Version & OS

GitHub Desktop Version 2.7.2

Windows 10 Pro.

### Steps to reproduce the behavior

1. Load a repository
2. Open the Repository in Windows Explorer
3. Create a folder named `Ta’n` (note: U+2019, not Straight Apostrophe)
4. Create `example.txt` in folder
5. In GitHub Desktop: Right Click `example.txt` - `Open With Default Program`

### Expected behavior

Either the file opens, or a useful error message is displayed

### Actual behavior

> Unable to open file C:\Users\David\source\repos\Manx-Search-Data\Manx-Search-Data\OpenData\NedBeg\Ta’n\manifest.json.txt in an external program. Please check you have a program associated with this file extension

### Screenshots

![image](https://user-images.githubusercontent.com/62114487/115354228-4ee75980-a1b1-11eb-92a4-2b6ec08485c6.png)

### Logs

```
2021-04-20T07:15:41.591Z - error: [main] Call to openExternal failed: 'Error: Failed to open'
```

**Comment by sergiou87** [comment]
Thank you for your report @david-allison-1 ! ❤️ 

I think this bug is the same as #11879, so I will close this one in favor of that one. I'd recommend you to subscribe to #11879 if you're interested in getting notified when we fix the bug 😄
