### ISSUE TITLE
Maximizing window on Windows positions it slightly off screen

### ISSUE THREAD

**Issue by niik** [desktop/desktop#1202]
This is out title bar when window is not maximized

![image](https://cloud.githubusercontent.com/assets/634063/25001528/33ef37ce-2046-11e7-8cf6-f193a0f643bf.png)

Make note of the margin between the top of the app icon and the window edge

This is the same title bar when the app is maximized

![image](https://cloud.githubusercontent.com/assets/634063/25001558/522e90c2-2046-11e7-9aee-7005f7f05847.png)

Calling `getPosition` on the `BrowserWindow` instance seems to indicate that we're positioned 8px to the left and 8px above from the screen top left edge

![image](https://cloud.githubusercontent.com/assets/634063/25001596/85ab746a-2046-11e7-8e97-dc6c881bf675.png)

The size is also wrong

![image](https://cloud.githubusercontent.com/assets/634063/25001748/358fa2e8-2047-11e7-972b-50eb0aadf447.png)

On my monitor the size of a maximized window should be 2560x1400 (full width and -40px to account for the Windows task bar) but it seems to be 16px too large both on the x and y axis.

There's a [16px magic number](https://github.com/electron/electron/blob/787bc8570382e98c4f204abff05b2af122e5a422/atom/browser/ui/views/frameless_view.cc#L18) in the electron code base that I suspect might have something to do with it but it could just be a coincidence as well.

cc @kevinsawicki, this seems to be a problem with electron, I'm gonna see if I can make a small reproduction repository and then open an issue on Electron

**Comment by bebekpekiwan** [comment]
Hi, I got the same problem with my windows 10 file explorer. I'm not familiar to programming, can anyone help me to solve this step by step? its a minor issue but it really bothering me.
