### ISSUE TITLE
cant clone my repository. it says you dont have access to that repository 

### ISSUE THREAD

**Issue by beastdev12** [desktop/desktop#12026]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by sergiou87** [comment]
Hi @beastdev12 !! 👋 

- Are you trying to clone it via HTTPS or SSH?
- Have you logged in your GitHub account from GitHub Desktop?

It would be super helpful if you could fill the template in the original issue, thank you! 😄
