### ISSUE TITLE
pikpol.damianpolakowski/skyline1983skyline

### ISSUE THREAD

**Issue by skyline1983skyliny** [desktop/desktop#12022]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for reaching out @skyline1983skyliny! This issue tracker is for GitHub Desktop, if you are having a specific issue with GitHub Desktop please fill out the template and let us know. Thanks.
