### ISSUE TITLE
Use tauri over electron

### ISSUE THREAD

**Issue by Milo123459** [desktop/desktop#12033]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

Electron isn't very lightweight on some systems, and tauri would solve this.

### Proposed solution

How will it benefit Desktop and its users?

Use [tauri](https://tauri.studio) - it's an alternative to electron and is in beta.

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by sergiou87** [comment]
Thank you for your suggestion! ❤️ 

However, I'm afraid this would be a huge change and we have no plans for something like that. If anything changes, we'll let you know 😄

**Comment by Milo123459** [comment]
Ah, ok.

**Comment by StrongTheDev** [comment]
Hello @sergiou87, Tauri is no longer in beta. can this now be considered?

**Comment by steveward** [comment]
@DanielHuey this likely isn't something we'll be considering anytime in the near-term. Sorry that I don't have better news.
