### ISSUE TITLE
Removing ongoing cloning repository keeps cloning in the background and appears after a while when done

### ISSUE THREAD

**Issue by maifeeulasad** [desktop/desktop#12039]
### Describe the feature or problem you’d like to solve

While cloning a repository if I remove that before it's finished, it will get removed from the list but it will keep cloning in the background. After cloning is done, some trigger is triggered and UI is updated after a while.

### Proposed solution

There can be many solution to this : 
 - Can ask user if *want to just clone and don't want to show in the repo list* or *send to recycle bin* 
 - The cloning process can be killed instantly

### Steps to reproduce the behavior

1. clone something big
2. remove it before it's done
3. keep waiting

### Snap(short) : 
![cut1](https://user-images.githubusercontent.com/29339330/115679369-5571fe80-a374-11eb-8085-8a645a52135f.gif)

### Record(full) : 
YouTube link : https://www.youtube.com/watch?v=g-1vpwl9KNY

**Comment by maifeeulasad** [comment]
Can I get assigned to this ?

**Comment by tidy-dev** [comment]
@maifeeulasad This looks to be along the same lines as https://github.com/desktop/desktop/issues/2082.  It probably will be kind of tricky to cancel the clone. But, you are welcome to take a stab at it. i am going to close this one in favor of that. :)
