### ISSUE TITLE
Cherry Pick multiple commits via Ctrl button

### ISSUE THREAD

**Issue by wheelwrightpien** [desktop/desktop#12030]
### Describe the feature or problem you’d like to solve

The new cherry-pick feature is fantastic!  The one issue I have is that it currently only allows to select multiple commits with the Shift button, so it is impossible to select commits which are not listed side by side, 

### Proposed solution

Add support for multiple choice via Ctrl key, which will allow users to select several commits that aren't side by side.

**Comment by tidy-dev** [comment]
@wheelwrightpien Thank you for the suggestion. It is something we were considering - so I went ahead and implemented it (See linked PR) . 🎉

**Comment by wheelwrightpien** [comment]
@tidy-dev   Amazing. Thank you!!!
