### ISSUE TITLE
More flexibility with column sizing

### ISSUE THREAD

**Issue by gdignard** [desktop/desktop#12037]
### Describe the feature or problem you’d like to solve

The windows desktop has unnecessary restrictions on column widths which prevent being able to see information

### Proposed solution

Being able to take advantage of a wide monitor so that information isn't unnecessarily suppressed

### Additional context

![WidthRestriction](https://user-images.githubusercontent.com/5778830/115639393-7722a580-a2e2-11eb-961a-b2f5a7eed485.jpg)

**Comment by sergiou87** [comment]
Thank you for your suggestion! This one seems to be pretty similar to what is requested in #2745, so I'm gonna close this in favor of that one. You can subscribe to #2745 to get notified when any relevant work is done 😄
