### ISSUE TITLE
Ignore folders

### ISSUE THREAD

**Issue by niik** [desktop/desktop#1203]
I recently created a git repository from a pre-existing projects and realized that we have no way of ignoring folders.

![image](https://cloud.githubusercontent.com/assets/634063/25003437/b299ba6e-204f-11e7-9ebb-01a3c5c616bc.png)

In this scenario I'd like to see the `Ignore` menu item become a submenu with this hierarchy

```
+--------------------+
| Discard changes... | +----------------------------+
| Ignore             +-> node_modules               |
+--------------------- | node_modules/.bin          |
                       | node_modules/.bin/electron |
                       +----------------------------+
```

**Comment by j-f1** [comment]
How about something like this?

```
┌──────────────────┐
│ Discard changes...  │ ┌──────────────────────────┐
│ Ignore              ├─→ 📄 electron                  │
└──────────────────┘   │ 📁 .bin                      │
                       │ 📁 node_modules              │
                       └──────────────────────────┘
```

This way, you don’t have to show complicated paths. This was inspired by the title-bar dropdown in Mac apps (cmd+click the file name in the title bar to see it)

**Comment by nawagers** [comment]
I came here to offer this same suggestion. The exact implementation details aren't very important. Any of the above solutions is fine. This feature would be particularly useful for young repositories as there are often directories that get created during various compile/build phases. Once they are all added to .gitignore (like on established repos) it's not an issue

**Comment by crea7or** [comment]
Why not to try gitkraken approach? ![image](https://user-images.githubusercontent.com/467357/36453266-9199dd76-16a8-11e8-9fcc-6798642ed293.png)
Context menu can be opened on files or folders. All important commands in the menus.

**Comment by MagicMarvMan** [comment]
I see, if I can open a PR with the enhanced context menu... :octocat:

**Comment by CyborgSemon** [comment]
+1 This would be really helpful!

**Comment by ArthurBrussee** [comment]
We now since have ignore file, and ignore all .extension, which is great! I still would really love to have a ignore path option though

**Comment by steveward** [comment]
Requested by @matiasmorant in #9374.

> >1- If there is an untracked folder with lots of files just show there is a new folder, not every file inside
> 2- Allow to right-click and add a folder to .gitignore not just a file
> 3- After right-click > Ignore file, show an editor to modify what you added to .gitignore, not just .gitignore diff

**Comment by steveward** [comment]
Requested in https://github.com/desktop/desktop/issues/13619.

**Comment by steveward** [comment]
Requested in https://github.com/desktop/desktop/issues/17273.
