### ISSUE TITLE
Mark repositories as "recent" when they are pulled from

### ISSUE THREAD

**Issue by MattRix** [desktop/desktop#12040]
### Describe the feature or problem you’d like to solve

I have multiple repos that I pull from often but I don't make commits to. They are always hard to find because I have dozens of repos, and pulling from a repo does not put it in the recent repos list. 

### Proposed solution

When a user pulls from a repo, it should get added to the recent repos list. 

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by MattRix** [comment]
An alternative solution would be to allow favoriting repos manually, and favorited repos would show up in a new section above recent repos.

**Comment by steveward** [comment]
@MattRix thanks for the feedback! I'm going to put this into https://github.com/desktop/desktop/issues/8183 which is our tracking issue for favoriting/pinning repositories in the repository list.
