### ISSUE TITLE
error: RPC failed; curl 55 Send failure: Connection was aborted

### ISSUE THREAD

**Issue by cpsusie** [desktop/desktop#12044]
When trying to push a commit to github, I got the error in the subject line.  

The following is the complete command line from that session:

> PS C:\Users\Christopher Susie> cd Source  
PS C:\Users\Christopher Susie\Source> cd .\Repos\  
PS C:\Users\Christopher Susie\Source\Repos> cd .\Int128\  
PS C:\Users\Christopher Susie\Source\Repos\Int128> git push  
Enumerating objects: 17, done.  
Counting objects: 100% (17/17), done.  
Delta compression using up to 12 threads  
Compressing objects: 100% (12/12), done.  
Writing objects: 100% (12/12), 422.21 KiB | 20.10 MiB/s, done.  
Total 12 (delta 3), reused 0 (delta 0)  
error: RPC failed; curl 55 Send failure: Connection was aborted  
fatal: the remote end hung up unexpectedly  
fatal: the remote end hung up unexpectedly  
Everything up-to-date  
PS C:\Users\Christopher Susie\Source\Repos\Int128>  

This seems similar to issue #9367, but unlike that issue, my upload is only 422.21 KiB as opposed to 8.66 GiB.

**Comment by sergiou87** [comment]
Just curious, have you tried this from another issue? https://github.com/desktop/desktop/issues/6485#issuecomment-618857664

Maybe that helps 🤞

**Comment by cpsusie** [comment]
> Just curious, have you tried this from another issue? [#6485 (comment)](https://github.com/desktop/desktop/issues/6485#issuecomment-618857664)
> 
> Maybe that helps 🤞

Well, I non-resolved resolved the issue in this instance by copying changes to my Linux box and pushing from there.  This is the second time this has happened to me (first-time complainer), so it may well happen again.  Most of the content of **both** failing commits were adding png files and editing a markdown file that refs the pngs.  It hasn't ever happened with a "just text/code" push.  Next time this happens, I'll try repack and report back..

**Comment by steveward** [comment]
Thanks for the update @cpsusie. For reference this issue tracker is specifically for GitHub Desktop -- if you're having issues pushing from the command line I'd recommend contacting [GitHub Support](https://support.github.com/) directly for assistance. 

I'll close this out since you were able to resolve things.

**Comment by cpsusie** [comment]
> Thanks for the update @cpsusie. For reference this issue tracker is specifically for GitHub Desktop -- if you're having issues pushing from the command line I'd recommend contacting [GitHub Support](https://support.github.com/) directly for assistance.
> 
> I'll close this out since you were able to resolve things.

No problem.  I realized that too late but figured since there were other similar issues here, someone here would have a fix for it.

**Comment by Mofehlo** [comment]
any mistakes i did here? please help


Enumerating objects: 164, done.
Counting objects: 100% (164/164), done.
Delta compression using up to 4 threads
Compressing objects: 100% (164/164), done.
error: RPC failed; curl 55 Send failure: Connection was aborted
fatal: the remote end hung up unexpectedly | 45.00 KiB/s
Writing objects: 100% (164/164), 17.63 MiB | 801.00 KiB/s, done.
Total 164 (delta 22), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

**Comment by steveward** [comment]
@Mofehlo that type of timeout can happen when pushing a lot of changes, or if you are just having connection issues. If you're continuing to encounter the error one thing that can often resolve it is to switch to using SSH for this repository. You can read how to create a new SSH key via the command line [here](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent).
