### ISSUE TITLE
Clone repo on Windows with binary files shows changes the moment cloning is complete

### ISSUE THREAD

**Issue by jakeonrails** [desktop/desktop#12049]
### Describe the bug

I checked out a repo today and the moment cloning stopped there were changes present in the working directory that I had no way of making.
When I "discard changes" nothing happens.
These two files are Binary files (.exes)

### Version & OS

Windows 10
Most recent Github Desktop: Version 2.7.2

### Steps to reproduce the behavior

(This is in a private repo so I'm unsure how to duplicate it yet in a way that's reproducible for you)

### Expected behavior

1. Clone repo
2. No changes are present in my working directory

### Actual behavior

1. Clone Repo
2. 2 files are marked as "changed" and ready to commit

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the report @jakeonrails. We've seen this happen with file mode changes when repositories are used on different operating systems. Could that possibly be the cause of the issue? You could try running `git config core.filemode false` in the repository to see if that resolves things.
