### ISSUE TITLE
Make the app installation process easier on macOS

### ISSUE THREAD

**Issue by rakleed** [desktop/desktop#12043]
### Describe the feature or problem you’d like to solve and proposed solution
Please make the process of installing the app on macOS more convenient either by making a DMG installer with the Applications folder and the app itself or immediately after launching, prompt the user to move the app to the Applications folder (if you determine that the app is not launched from the Applications folder).

**Comment by sergiou87** [comment]
Thanks for the suggestion! We already did the latter in #11846 😄  

We did that after considering having a DMG, but it seems the API to move the app to the `Applications` folder [doesn't get along very well with the DMG in some circumstances](https://github.com/electron/electron/issues/12869).

I hope that helps! 👋
