### ISSUE TITLE
In "Clone a repository" rename the `GitHub.com` tab title to `GitHub - my repositories`

### ISSUE THREAD

**Issue by darkred** [desktop/desktop#12054]
### Describe the feature or problem you’d like to solve

Currently, in: 'File' | 'Clone a repository' (<kbd>Ctrl Shift O</kbd>)
the 1st tab, `GitHub.com`, contains a list of "Your repositories" that you may clone.

But, named `GitHub.com` gives the wrong impression that entering *any* github repo URL in there, you may clone it.
That's not the case - that's the 3rd tab for: `URL` .

### Proposed solution

My suggestion is to rename it to `GitHub - my repositories`
This change will help clarify the purpose of these tabs.

### Additional context

![](https://user-images.githubusercontent.com/723651/115969534-07145980-a546-11eb-9454-1e28a482d338.jpg)
Using GitHub Desktop 2.7.2 with win10 x64.

**Comment by billygriffin** [comment]
Thanks for the idea @darkred. Since this is such a commonly used piece of the app, we're hesitant to change it without widespread agreement that something isn't working. In this case, it says "Your repositories" immediately below the filter box, which I think is sufficient to capture the intent here. Sorry that it's not a better answer, we just don't want to confuse more people by changing up the way it works here.

**Comment by darkred** [comment]
> it says "Your repositories" immediately below the filter box, which I think is sufficient to capture the intent here.

Yes, indeed there's "Your repositories", 
and also the "Filter your repositories" filter box has as background text: "Filter your repositories":
![](https://user-images.githubusercontent.com/723651/115969534-07145980-a546-11eb-9454-1e28a482d338.jpg)

&nbsp;
The "Filter your repositories" filter box's purpose is to search among your repos using words as criteria, e.g. "test".

But, if you enter a URL instead of words, 
the resulting message is: *"Sorry, I can't find any repo matching `some_URL`"* , 
even if the repo actually exists in the target URL, it's just not cloned yet:
![2021-04-29_003528](https://user-images.githubusercontent.com/723651/116475662-d6ecf380-a882-11eb-90e8-8514a03bcd6f.jpg)


&nbsp;
Do you think it would be worth changing the message into:

*"Sorry, you have entered a URL instead of words, so search among your repos cannot display any results.
Click >here< to switch to the 'URL' tab and try to clone that repo from `some_URL`."*  ?

Or, alternatively, make the filter box not accept URL-like strings ?
