### ISSUE TITLE
Adding the same file to .gitignore multiple times create duplicated entries.

### ISSUE THREAD

**Issue by fabiocaccamo** [desktop/desktop#12057]
### Describe the bug

Adding the same file to .gitignore multiple times create duplicated entries.

### Version & OS

`macOS BigSur 1.2.3`

### Steps to reproduce the behavior

1. Go to any file, eg. `TODO.txt`
2. Right click on it and select "Ignore File"
3. Commit the updated `.gitignore`
4. The file is already in the changed files list (it shouldn't)
5. Right click on it and select "Ignore File"
6. The `.gitignore` file contains duplicated `TODO.txt` entries.

### Expected behavior

- Files added to `.gitignore` should not be visible (or made opaque and disabled) in the changed files list.
- Adding a file to `.gitignore` more than once should not create duplicated entries.

### Actual behavior

- Files added to `.gitignore` stay visible in the changed files list even after having committed the `.gitignore` changes.
- Adding a file to `.gitignore` more than once create duplicated entries.

**Comment by steveward** [comment]
Thanks for the report @fabiocaccamo. We are tracking this in https://github.com/desktop/desktop/issues/2537, you can follow along there for updates. I'm going to close this out.
