### ISSUE TITLE
add  eslint-plugin-unicorn

### ISSUE THREAD

**Issue by danny007in** [desktop/desktop#12059]
if possible
https://github.com/xojs/eslint-config-xo-react
https://github.com/xojs/eslint-config-xo-typescript

**Comment by danny007in** [comment]
and remove tslint
we can configure with https://github.com/typescript-eslint/typescript-eslint#what-about-tslint

**Comment by steveward** [comment]
Thanks for the issue @danny007in. We migrated to using `typescript-eslint` a couple of years ago (see https://github.com/desktop/desktop/pull/6771), so I'm going to close this out.
