### ISSUE TITLE
login for GitHub desktop not possible under pop!os

### ISSUE THREAD

**Issue by akerkow** [desktop/desktop#12053]
### Login-Problem:

I downloaded GitHub desktop 3.1.6 from the pop!shop under pop!os 20.10 as a debian package. 
Than when I put in my login data and press "log in", nothing happens. When I try to sign in by using the browser, after typing in the data into the browser and allowing the data transfer, GitHub desktop shows a loading sign forever and again nothing happens. Internet connection is stable and I tried the loading for severel hours overnight... but no log in happens!

I still can use GitHub by means of the browser, but I wanted to report the problem here because I guess it is a bug. When there is a nice workaround for the problem so that I can use the desktop version I would also be pleased to learn about the trick.

Thanks in advance for the time and effort for trouble shooting or explanations!

**Comment by sergiou87** [comment]
Hi @akerkow! 👋 

I'm sorry you're having this issues. Unfortunately, we don't officially support Linux at this point. There is, however, an unofficial fork in https://github.com/shiftkey/desktop/issues where you might be able to get better help about your issue.

You can also subscribe to #1525 if you want to get notified whenever we decide to support Linux officially  😄
