### ISSUE TITLE
Broken download links v2.7.2

### ISSUE THREAD

**Issue by prithvi2k2** [desktop/desktop#12062]
### Describe the bug

GitHub Desktop download links are broken! v2.7.2

### Steps to reproduce the behaviour

1. Go to [desktop.github.com](Official page)
2. Click on the `Download` buttons
4. Loads for some time and browser reports `took too long to respond`, Tried on different devices and browsers but no use

### Expected behaviour

Download GitHub Desktop GUI client

### Actual behaviour

Can't download the setup

### Screenshots

![snap](https://user-images.githubusercontent.com/72189314/116115780-5dc98280-a66f-11eb-9945-639beef1041e.png)

**Comment by prithvi2k2** [comment]
If this is a good first issue, I would like to work on this. I'm a complete beginner, might need some guidance.

EDIT:
GitHub is also broken, images don't load, can't upload images and videos etc seems like a serious issue! 
Hope developers could fix these issues ASAP

**Comment by prithvi2k2** [comment]
No, wait, GitHub is also broken, images don't load, can't upload images and videos, unable to edit my previous comment etc, seems like a serious issue!

**Comment by steveward** [comment]
@prithvi2k2 I'm not seeing any of the issues you mentioned -- this sounds like a specific issue with your machine or network. Are you behind a firewall or proxy that could be blocking your connection to GitHub?

**Comment by prithvi2k2** [comment]
> @prithvi2k2 I'm not seeing any of the issues you mentioned -- this sounds like a specific issue with your machine or network. Are you behind a firewall or proxy that could be blocking your connection to GitHub?

@steveward I tried from a cellular network, unexpectedly it worked, setup was downloaded, seems like a problem with ISP and firewall, i don't know what to do, I'll try to find a fix myself. Thanks for mentioning the point, or else I would've been lost!

**Comment by prithvi2k2** [comment]
Turned my home network from public to private, the firewall was blocking some features in public. Now everything works fine, I don't know how it was made public without my knowledge😕.
