### ISSUE TITLE
Linux not supported

### ISSUE THREAD

**Issue by mikoloism** [desktop/desktop#12068]
### Describe the feature or problem you’d like to solve

Hi Github team :wave: :star:
please, support Linux destros for github desktop

:heart:

**Comment by steveward** [comment]
Thanks for the issue @miko-github. At this time there are no official builds of GitHub Desktop available for Linux, but a former developer of GitHub Desktop maintains a fork with Linux builds available for download:

https://github.com/shiftkey/desktop/releases

We are also tracking official Linux support in https://github.com/desktop/desktop/issues/1525.

**Comment by mikoloism** [comment]
thanks :heart:
