### ISSUE TITLE
Git Bash shell integration does not appear

### ISSUE THREAD

**Issue by bjornenalfa** [desktop/desktop#12076]
### Describe the bug

The "Open in Git Bash" shell integration does not appear. Github Desktop appears to be looking for it in the wrong folder.

### Version & OS

Version 2.7.2
Windows 10 Pro 10.0.19042 Build 19042

### Steps to reproduce the behavior

1. Install Windows 10 Pro.
2. Install Github Desktop.
3. Install Git for Windows.
4. Open a repository in Github Desktop.
5. Click "Repository" in the top bar.
6. "Open in Git Bash" does not appear.

### Expected behavior

"Open in Git Bash" appears as an option under "Repository" in the top bar.

### Actual behavior

"Open in Git Bash" does not appear as an option under "Repository" in the top bar.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

Git for Windows installs in `C:\Program Files\Git`, not `C:\Program Files\GitForWindows`

**Comment by steveward** [comment]
Thanks for the report @bjornenalfa. Can you verify that Git has been added to your PATH? You can check your path by opening CMD and running `echo %PATH%`. Check to see if `C:\Program Files\Git\cmd` has been added there.

**Comment by bjornenalfa** [comment]
It is present:

```
C:\Users\bjorn>echo %PATH%
C:\Python39\Scripts\;C:\Python39\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Git\cmd;C:\Program Files\Go\bin;C:\Program Files (x86)\Bitvise SSH Client;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\bjorn\AppData\Local\Microsoft\WindowsApps;C:\Users\bjorn\AppData\Local\GitHubDesktop\bin;C:\Users\bjorn\.dotnet\tools;C:\Users\bjorn\go\bin;C:\Users\bjorn\AppData\Roaming\npm;C:\Users\bjorn\AppData\Local\Programs\Azure Data Studio\bin
```

**Comment by steveward** [comment]
@bjornenalfa just to verify so that I'm not missing anything -- have you changed the option in GitHub Desktop to use Git Bash in `File` > `Options` > `Integrations` > `Shell`?

**Comment by bjornenalfa** [comment]
Aha! I have never had to do that in any of my previous installs, and I have not found/seen anything mentioning that setting.
