### ISSUE TITLE
"Branch with that name already exists" when opening pull request

### ISSUE THREAD

**Issue by AaronLS** [desktop/desktop#12070]
### Describe the bug

Can't open pull request, error "A branch with that name already exists."

### Version & OS

GitHub Desktop 2.7.2 on Windows 10

### Steps to reproduce the behavior

1. Clone a Repository
2. Choose AaronLS/Mtgdb
3. Choose the "For my own purposes" option so Pull requests targeting AaronLS/mtgdb will be shown.
4. Open the Current branch dropdown -> Pull requests
5. Click pull request "Update fork from upstream."
6. Error shown "A branch with that name already exists."

### Expected behavior

Be able to view the pull request so I can proceed to resolve conflicts.

### Actual behavior

Error shown "A branch with that name already exists."

### Screenshots

![image](https://user-images.githubusercontent.com/2784372/116180893-ae7cc200-a6e7-11eb-9e86-e1d501c0e1a6.png)

![image](https://user-images.githubusercontent.com/2784372/116180972-c94f3680-a6e7-11eb-8d9b-6f71b092a9d4.png)

### Logs

```
2021-04-27T03:32:43.031Z - info: [ui] [Timing] Action 'checkout pull request from list' for 'aaronls/Mtgdb' took 1.634s
2021-04-27T03:32:50.199Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Mtgdb - AaronLS (has token)
2021-04-27T03:32:50.413Z - error: [ui] `git -c credential.helper= -c protocol.version=2 checkout --progress upstream/master -b master --` exited with an unexpected code: 128.
stderr:
fatal: A branch named 'master' already exists.

(The error was parsed as 26: A branch with that name already exists.)
2021-04-27T03:32:52.079Z - info: [ui] [Timing] Action 'checkout pull request from list' for 'aaronls/Mtgdb' took 1.973s
```

### Additional context

I was following a guide that showed creating a Pull Request against my own fork and pulling changes from upstream in order to bring my fork up to date.  I successfully created the pull request, but needed to open the pull request in GitHub desktop in order to resolve conflicts.  I understand there's other approaches to accomplishing this, but am hoping there's a way to address this specific issue of being unable to open the Pull Request.

**Comment by AaronLS** [comment]
I also tried the approach of changing origin to the parent repo, but then my pull doesn't appear.  I try Pull Origin to then pull from upstream, but because my fork is so far behind there's almost 300 conflicts(most in my opinion such as file Adds I'm not sure why it's a conflict since the file is unmodified in my fork or non-existent), all of which I would happily accept "theirs" but there's no way to just select all.  Even trying to find command line to bulk accept theirs leads to convoluted piping between commands.  It feels like I'm sitting down and writing a cmd batch file to do something that I'm used to it being three clicks in another VCS.  

I tried the "Rebase current branch" option under the branch menu, but it doesn't let me choose to rebase to the current branch from upstream.  In the dialog that appears when I choose upstream/master, it is telling me it will apply commits on top of upstream/master.  As I understand it, that wouldn't be what the parent menu describers as "Rebase current branch", but rather would be a rebase of the upstream.  The way this dialog works, shouldn't the menu item say "Rebase another branch from current branch"?  I would indeed like to Rebase my current branch, but the dialog doesn't let me do that, it wants to only let me rebase another branch.

![image](https://user-images.githubusercontent.com/2784372/116184460-cc4d2580-a6ed-11eb-899f-2c105da8768f.png)

![image](https://user-images.githubusercontent.com/2784372/116184434-c22b2700-a6ed-11eb-978f-b212d555f51e.png)

**Comment by steveward** [comment]
Thanks for the report @AaronLS. This issue is being tracked in https://github.com/desktop/desktop/issues/4527.  You can follow along there for updates about this.

**Comment by AaronLS** [comment]
@steveward I know unrelated, I'm not very familiar with rebasing, but is the "Rebase current branch..." not confusing? The verbiage in the subsequent dialog "This will... applying its X commits on top of upstream/master" makes it sound like it is rebasing upstream rather than rebasing current.  The result of the rebase of current should be that commits from upstream are applied to current.  Not applied to upstream.  See screen clippings above.

**Comment by Buddelbubi** [comment]
When will it be fixed?

**Comment by jimmyvaswani** [comment]
Is this fixed yet? If yes pls share the solution, thanks.

**Comment by Buddelbubi** [comment]
> Is this fixed yet? If yes pls share the solution, thanks.

No, its not

**Comment by Buddelbubi** [comment]
![grafik](https://github.com/user-attachments/assets/d4a910d7-0e7b-40ee-b6a6-e82edb7f9283)

**Comment by Splitrox** [comment]
wow not yet?
