### ISSUE TITLE
Good

### ISSUE THREAD

**Issue by ksa505qht** [desktop/desktop#12073]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@ksa505qht this issue tracker is for GitHub Desktop. If you have any questions about GitHub Desktop please fill out the template and let us know.
