### ISSUE TITLE
GitHub desktop pushing changes very slowly on Chrome OS Linux

### ISSUE THREAD

**Issue by Bobby99as** [desktop/desktop#12088]
### Describe the bug

Taking forever to push origin

### Version & OS

2.6.3 Chrome OS Linux

### Steps to reproduce the behavior

1. Clone your repository to internal storage
2. Make any type of change to any of the files in it
3. Click push changes to origin
4. You'll see that it takes forever to push the simple change

### Expected behavior

It uploads in a few seconds

### Actual behavior

It takes about a couple minutes

### Screenshots

N/A

### Logs

I don't have any but if they're needed I can upload some

### Additional context

I've noticed that it takes a couple of seconds to upload my changes when I have GitHub desktop installed on my Windows computer but when I work on my Chromebook and I go to push the changes on it. it takes about a couple of minutes.

**Comment by steveward** [comment]
@Bobby99as thanks for the issue. To report problems with the Linux fork of GitHub Desktop please open an issue in https://github.com/shiftkey/desktop/issues. Thanks!

**Comment by Bobby99as** [comment]
Oh sorry @steveward
