### ISSUE TITLE
Show the worktree name in addition to the repo name

### ISSUE THREAD

**Issue by markshep** [desktop/desktop#12082]
### Describe the feature or problem you’d like to solve

I can't distinguish between multiple worktrees for the same repo.

### Proposed solution

Show the worktree name in addition to the repo name.

### Additional context

I often use multiple worktrees for a project.  I'll setup a bare copy of the repo at "project.git" then add worktrees, e.g. "project-a", "project-b" etc.  After adding multiple such worktrees to GitHub Desktop I'm unable to distinguish between them as they just display the repo name of "user/project".

Existing view:

<img width="265" alt="repos" src="https://user-images.githubusercontent.com/490067/116238856-d442af00-a759-11eb-8f83-518eb1e79f6e.png">

Proposed view:

<img width="265" alt="worktrees" src="https://user-images.githubusercontent.com/490067/116238899-e4f32500-a759-11eb-8d27-3190f7e2f822.png">

**Comment by steveward** [comment]
Thanks for the issue @markshep! We'll be adding the ability to set custom repository aliases in our next release (shipping tomorrow), which should resolve this issue for you. See https://github.com/desktop/desktop/pull/12000. I'm going to close this out, but feel free to grab the [latest beta](https://github.com/desktop/desktop#beta-channel) if you want to get this right now and help it test it out.
