### ISSUE TITLE
Hope edit the differences after the stash pops up

### ISSUE THREAD

**Issue by Tsuj100** [desktop/desktop#12084]
like vscode

**Comment by steveward** [comment]
@Tsuj100 thanks for the issue. Can you clarify the feature you are requesting here with some more details?

**Comment by Tsuj100** [comment]
Thans for your response. I think I can handle merge conflicts quickly when resolving conflicts.

**Comment by steveward** [comment]
Thanks for the update @Tsuj100. At this time we do not have plans to integrate direct merge conflict resolution into GitHub Desktop. You will need to launch your preferred editor/IDE to resolve conflicts. Let me know if I am misunderstanding your request.
