### ISSUE TITLE
An error in global config file on windows 10.

### ISSUE THREAD

**Issue by WHUFrozenHeart** [desktop/desktop#12085]
Recently, I wanted to change some settings of global config. But after using `git config --global --list`, there will always be an error, as shown below.
```
error: cannot spawn less: No such file or directory
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
```
Even after I delete this config file and let app create new one, this error is still exiting. Although, this error seems not to affect any functionality of app, I still want to know this error is about what and how to fix it.

**Comment by steveward** [comment]
@WHUFrozenHeart thanks for the report. Is this error occurring in GitHub Desktop, or just via the command line?

It looks like Git is unable to run the `less` command on your system. If you're running this in Git for Windows it should be in `C:\Program Files\Git\usr\bin\less.exe`. I would check there to see if it exists. GitHub Desktop's bundled Git does not ship with `less` since the application does not need to use it.

**Comment by WHUFrozenHeart** [comment]
@steveward thanks for your answer. I am using the git of Git Hub Desktop's own by setting "System Environment Variable" configuration. I have already checked the folders of `\GitHubDesktop\app-2.7.2\resources\app\git\usr\bin` and  `\GitHubDesktop\app-2.8.0\resources\app\git\usr\bin`, for the reason that, last night, app automatically updated from 2.7.2 to 2.8.0. There is no `less.exe` file in both of them.

When I am using 2.8.0, I took the same action just as in 2.7.2 without this error. It is so strange. Maybe update fixed it. But still thanks for your attention and help.

At last, I hope that the git folder can be moved from `\GitHubDesktop\app-x.x.x\` to `\GitHubDesktop\`, which make it no need to change "System Environment Variable" configuration every time app updates.

**Comment by steveward** [comment]
@WHUFrozenHeart I wouldn't recommend using GitHub Desktop's bundled Git. It's meant to be used only by GitHub Desktop. I would instead recommend installing [Git for Windows directly](https://git-scm.com/download/win). The Git we ship with GitHub Desktop is custom and does not include everything that Git for Windows ships with.

I'm glad to hear things are working for you now so I'm going to close this issue out. Let me know if you have any other questions.
