### ISSUE TITLE
[Enhance] branch ui part

### ISSUE THREAD

**Issue by danny007in** [desktop/desktop#12080]
![GitHubDesktop_vUE3dRnpvQ](https://user-images.githubusercontent.com/50356015/116233896-80e05900-a779-11eb-918b-8d0b73f76581.png)

**Comment by danny007in** [comment]
![image](https://user-images.githubusercontent.com/50356015/116274601-74bbc200-a7a0-11eb-84a2-8d7b7393a30b.png)

**Comment by billygriffin** [comment]
Thanks @danny007in - we don't have immediate plans to change the branch menu and generally we're hesitant to significantly change the layout of things like this unless there's a really compelling reason to do so. For your initial post, you can click "Fetch" and it will grab new branches and update your current one. Thanks for the idea.
