### ISSUE TITLE
Add user name in repo tab

### ISSUE THREAD

**Issue by mathurk29** [desktop/desktop#12090]
### Describe the feature or problem you’d like to solve

Add username before the repo name in the leftmost tab so that one can differentiate b/w upstream and forks.

**Comment by billygriffin** [comment]
Hi @mathurk29, GitHub repos are currently separated by owner in the app. We also just shipped an update in 2.8 that allows you to create aliases for repositories to more easily differentiate. 

![repo alias](https://user-images.githubusercontent.com/5091167/116561533-a5464d80-a8bf-11eb-9f87-f4b38494f153.gif)


I think the combination of these things should solve what you're trying to do, so I'm going to close this issue.
