### ISSUE TITLE
Getting this while opening github desktop

### ISSUE THREAD

**Issue by xavierallem** [desktop/desktop#12095]
<img width="433" alt="Capture" src="https://user-images.githubusercontent.com/60181637/116539880-0e9d7f00-a907-11eb-82a4-7a11da5575a5.PNG">

**Comment by sergiou87** [comment]
Hi @xavierallem! 👋 

From what I see in that screenshot, seems like you're using an old version of the app (2.5.6), have you tried updating the app to see if the issue is resolved?
