### ISSUE TITLE
"An update is ready to install" window keeps poping up  in Mac

### ISSUE THREAD

**Issue by twilightgod** [desktop/desktop#12099]
Hi,

I'm running MacOS 11.2.3, GitHub desktop 2.7.2
I have the issue that "An update is ready to install" keeps poping up even I enter password.
This process also eats up 100% CPU usage.
I did some search and found this solution, change the owner to my user:
https://github.com/desktop/desktop/issues/3616#issuecomment-400371047
It works for me for one user, but I have multiple users signed in this Mac, others users still have this issue.
It's very annoying, can I disable the auto update feature?

**Comment by sergiou87** [comment]
Hello @twilightgod! 👋 

I'm sorry you're having those issues, but I'm afraid you cannot disable the auto update 😓 

Have you tried to delete the app and just download it again? Hopefully that will fix your permissions issue and it will work in future updates. Your settings, repos and all that are stored somewhere else (in `~/Library/Application Support/GitHub Desktop`), so just removing and reinstalling the app should be safe, but feel free to back that folder up before doing so.
