### ISSUE TITLE
Display full repo name below Current Repository

### ISSUE THREAD

**Issue by photonstorm** [desktop/desktop#12093]
### Describe the feature or problem you’d like to solve

I have a large number of repositories that all have the exact same name, but are under different GitHub accounts. Currently, it's impossible to tell which repo I'm actually in because all it displays is the repo name:

![image](https://user-images.githubusercontent.com/164476/116535226-6b834000-a8db-11eb-9b32-9c98ea5123f3.png)

You can hover the mouse over this and it'll give you a tool-tip showing the file path, which can of course be used to identify the repo, but I would really love the ability to just see it without having to wait for the tooltip to appear.

As I add more and more repos to GitHub Desktop, it is genuinely becoming harder to navigate and differentiate them. The 'Recent' list tries to help here, but being limited to 3 items is just too tiny a quantity for the volume of projects I work across. However, I appreciate that's a different issue to this.

### Proposed solution

Even if this was just a setting hidden away in Preferences that would be great! As I understand that for a lot of users the current display is probably fine.

**Comment by steveward** [comment]
@photonstorm thanks for the issue. We just added a feature that allows you to add an alias to a repository to help differentiate between repositories with the same name. You can access this by right-clicking on the repository in the repository list. I hope that helps!

**Comment by photonstorm** [comment]
Perfect, thank you!
