### ISSUE TITLE
fatal: unable to access 'https://github.com/fearthefoca3/Project3D.git/': Unsupported proxy syntax in ':0'

### ISSUE THREAD

**Issue by ainaplanass** [desktop/desktop#12106]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by ainaplanass** [comment]
fatal: unable to access 'https://github.com/fearthefoca3/Project3D.git/': Unsupported proxy syntax in ':0'

**Comment by ainaplanass** [comment]
:(

**Comment by ainaplanass** [comment]
![image](https://user-images.githubusercontent.com/82839054/116722259-770b5f80-a9de-11eb-857c-e92c1287b158.png)

**Comment by steveward** [comment]
@ainaplanass thanks for the issue. Can you share a few more details about your network setup?

- Are you behind a proxy?
- Have you configured Git to work with your proxy?
- Can you share the output of `git config --global --list` from the command line?

**Comment by ainaplanass** [comment]
I dont use any proxy

**Comment by ainaplanass** [comment]
I dont know where is the command line

**Comment by steveward** [comment]
@ainaplanass you can launch the command line by going to `Repository` > `Open in <command_line>`. You will need to install Git if you do not already have it installed on your system.

**Comment by ainaplanass** [comment]
![image](https://user-images.githubusercontent.com/82839054/116740631-93ff5d00-a9f5-11eb-8759-9962df7a6b1f.png)
sorry im a boomer i cant select it where i click

**Comment by steveward** [comment]
@ainaplanass you can download  Git for Windows (https://git-scm.com/download/win) and then run the command there. Since you do not have an existing repository the command is greyed out (GitHub Desktop would prompt you to install Git for Windows as well).

**Comment by steveward** [comment]
@ainaplanass I'm going to close this out due to inactivity, but please let me know if you are still having issues and we can dig into this further.
