### ISSUE TITLE
git: 'remote-https' is not a git command. See 'git --help'.

### ISSUE THREAD

**Issue by manju-gilhare** [desktop/desktop#12103]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

git: 'remote-https' is not a git command. See 'git --help'.

**Comment by steveward** [comment]
Thanks for the report @manju-gilhare. Usually this error indicates there is an issue with your installation of GitHub Desktop.

Could you try performing a fresh installation of GitHub Desktop by following these steps? If you are running any anti-virus software I would also recommend temporarily disabling it to ensure it does not interfere with the installation.

Here are the steps:

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `%AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that does not get things working for you.
