### ISSUE TITLE
görüntü ses müzik canlı yayın instagram takipçi 

### ISSUE THREAD

**Issue by live125** [desktop/desktop#12112]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by live125** [comment]
![060](https://user-images.githubusercontent.com/83435079/116800057-4cb4c180-ab06-11eb-86ce-fe99f498233e.jpg)
şarkı ve ses kaydıyla takipçi kazanmak istiyourm

**Comment by VMGuy23** [comment]
Bunun GitHub Desktop ile ne ilgisi var?
