### ISSUE TITLE
im new to this and was trying to find at the start of github where to find your repository can someone please explain

### ISSUE THREAD

**Issue by jason7311** [desktop/desktop#12116]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by jason7311** [comment]
> ### Describe the feature or problem you’d like to solve
> A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.
> 
> ### Proposed solution
> How will it benefit Desktop and its users?
> 
> ### Additional context
> Add any other context like screenshots or mockups are helpful, if applicable.

it

**Comment by jason7311** [comment]
it says to go to the hello world and to hit the + button and then to click on the create a new repository but i cant find it

**Comment by billygriffin** [comment]
Hi @jason7311, this is the repository for GitHub Desktop, not for learning about GitHub. There are lots of resources out there for getting started with GitHub, I'd start here: https://guides.github.com/
