### ISSUE TITLE
Strs in "Current repository" are coverd

### ISSUE THREAD

**Issue by Air-EL** [desktop/desktop#12114]
### Describe the bug

Strs in "Current repository" are coverd

### Version & OS

Version 2.8.0 / Win10

### Steps to reproduce the behavior

1. Click on "Current repository"

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

![error](https://user-images.githubusercontent.com/56814839/116805847-b4e1c280-ab5b-11eb-9daa-e1640f6d1150.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tidy-dev** [comment]
@Air-EL Thank you for the report. I am not able to reproduce.  When my alias are too long, it truncates and applies the ellipsis as expected.

Can you add any further reproduction steps?

![image](https://user-images.githubusercontent.com/75402236/116874134-ce7c1c00-abe6-11eb-911b-81464dd537e0.png)
