### ISSUE TITLE
Support for Sublime Text 4 for Windows

### ISSUE THREAD

**Issue by kenodegard** [desktop/desktop#12124]
### Describe the feature or problem you’d like to solve

macOS correctly detects Sublime Text 2, 3, and ~~the beta version~~ 4 since #11263. Windows does not.

**Update: Sublime Text 4 was [officially released](https://www.sublimetext.com/blog/articles/sublime-text-4) on May 21, 2021** 

### Proposed solution

This allows support for all of the Sublime Text editors and makes the Windows application consistent with the macOS one. 

### Additional context

I see that this is where the change is needed:
https://github.com/desktop/desktop/blob/18238077aa1e4851e710cfa66587cd4fd597bacd/app/src/lib/editors/win32.ts#L162-L169

And looking at regedit I see the following Sublime Text entries:

| `regedit` entry | Executable |
|---|---|
| `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Sublime Text 2_is1` | `C:\Program Files\Sublime Text 2\sublime_text.exe` |
| `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Sublime Text 3_is1` | `C:\Program Files\Sublime Text 3\subl.exe` |
| `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Sublime Text_is1` | `C:\Program Files\Sublime Text\subl.exe` |

**Comment by Rexogamer** [comment]
I am happy to pick this one up.

**Comment by jhall11784** [comment]
Ok go
