### ISSUE TITLE
Unchanged files are in the Changes list

### ISSUE THREAD

**Issue by felipedrumond** [desktop/desktop#12127]
### Describe the bug

Unchanged files are in the list of changes files.

### Version & OS
2.8.0
Windows 10 Pro

### Steps to reproduce the behavior
Not sure how to reproduce.

### Expected behavior

Unchanged files should not be in the Changes tab

### Actual behavior

Unchanged filed are in the Changes tab but the details panel says "No content changes found" 

### Screenshots
![image](https://user-images.githubusercontent.com/17038136/116952144-458be000-accd-11eb-80f6-564bd089479c.png)

**Comment by steveward** [comment]
Thanks for the report @felipedrumond. We've seen this happen with file mode changes when repositories are used on different operating systems. Could that possibly be the cause of the issue? You could try running `git config core.filemode false` in the repository to see if that resolves things.

**Comment by felipedrumond** [comment]
Hi @steveward - I couldn't get that resolved.

I tried to discard the changes, set to false/true, verify it's set to false/true and build my solution in VS 2019. Issue remains.

A git diff gave me this 

`git diff Article.cs`
warning: LF will be replaced by CRLF in Article.cs.
The file will have its original line endings in your working directory

Then I checked 
`git config core.autocrlf`
true

setting **core.autocrlf to false resolved the issue**

Thank you!

**Comment by felipedrumond** [comment]
oops - that made all the changes made to be displayed in a not desired way. Any tiny change would display the diff as the whole file has changes rather then just the lines changed. So core.autocrlf needs to be true.

**Comment by steveward** [comment]
@felipedrumond you may want to add a `.gitattributes` file with a `* text=auto` line. This should normalize the line endings and prevent this issue within this specific repository. See [this guide](https://docs.github.com/en/github/getting-started-with-github/configuring-git-to-handle-line-endings#per-repository-settings). Let me know if that helps!

**Comment by steveward** [comment]
@felipedrumond closing this out due to inactivity -- let me know if you are still having any issues.
