### ISSUE TITLE
github desktop refusing to locate local folders

### ISSUE THREAD

**Issue by roosterroosie** [desktop/desktop#12132]
### Describe the bug

when I add a local file it says it can't find it

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Go to 'File'
2. Click on 'Add local repository'
3. Choose a local folder
4. Click on "Add repository"
5. See error

### Expected behavior

added repository being shown on screen

### Actual behavior

error saying that it can't find the repository

### Screenshots

![image](https://user-images.githubusercontent.com/83658826/117045792-d2538f80-ad07-11eb-946b-468cd6cccab3.png)

**Comment by steveward** [comment]
Thanks for the report @roosterroosie. Can you try dragging-and-dropping the folder directly into GitHub Desktop to see if you encounter the same issue?

**Comment by gprovostqa** [comment]
I have the same issue since I updated versions. My existing repositories are not found anymore, even if I try to Locate them again. The Clone Again option does not work in that case since the repository already exists localy. 
If I clone my Git repository from scratch it works.

**Comment by steveward** [comment]
@gprovostqa it sounds like you ran into something similar to https://github.com/desktop/desktop/issues/11620. Are you storing your repositories in a directory that is also managed by a file syncing service?

Can you try resetting GitHub Desktop by following these steps?

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop
4. Drag-and-drop your repositories into GitHub Desktop to add them back

Let me know if that helps.

**Comment by gprovostqa** [comment]
@steveward I tried those steps and as soon as I drag-and-drop my repository, the same issue showed up.

For now I reinstalled GitHub and cloned my Git repository from scratch. I managed to commit, I'll see if it holds. 🤞

**Comment by steveward** [comment]
@gprovostqa thanks for the update, let me know if you run into this again and we can dig into this further.
