### ISSUE TITLE
provide feature to copy branch/repository name

### ISSUE THREAD

**Issue by saranrajui** [desktop/desktop#12141]
### Describe the feature or problem you’d like to solve

If I want to copy the name of the branch or repository that I cloned, no way to do it( than rename -> copy )

### Proposed solution

IT will be easy to copy if the user wants to use it for some other purpose 

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
Thanks for the request @saranrajui. Can you share some additional context about how you would use this feature if it were added to GitHub Desktop?

**Comment by tidy-dev** [comment]
😸 I agree that it is a little annoying that if I want to send the name of a branch to a coworker for them to checkout.. I can't highlight the text to copy it easily. (I do what @saranrajui mentions -> rename and copy) I have run into this a few times since using Desktop.
