### ISSUE TITLE
Show Full File Path in Commits Explorer

### ISSUE THREAD

**Issue by karmasakshi** [desktop/desktop#12158]
### Describe the feature or problem you’d like to solve

Each row in the files section of the History tab truncates the file path and name, and there is no way to view this (except hovering over the file names for 2-3 seconds). Extensible width of this column is also limited.

<img width="255" alt="Screenshot 2021-05-06 at 12 56 50 PM" src="https://user-images.githubusercontent.com/4698762/117271034-dea42d80-ae6a-11eb-9cee-be00fad34030.png">

### Proposed solution

A new bar above the diff explorer showing the complete file path and name non-truncated.

How will it benefit Desktop and its users?

Users will be able to view which files were changed in a commit.

**Comment by steveward** [comment]
Thanks for the request @karmasakshi. We are tracking expanding the column width in https://github.com/desktop/desktop/issues/2745, so I'm going to close this out. Please follow along there for updates.

**Comment by karmasakshi** [comment]
Hi @steveward, thanks for having a look here. Just wanted to point out that expanding the column width will not solve the issue unless we also remove the truncation.
