### ISSUE TITLE
Create a new branch from filtering by just hitting `Enter`

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#12154]
### Describe the feature or problem you’d like to solve

This request is via @cheshire137. To create a new branch in the branch filter process, you have to click the blue button with your mouse or tab to it. 

### Proposed solution

It would be nice to just be able to hit `Enter` to pop the dialog to create the branch after you've typed the new branch name. I'm not super worried about lowering the friction because you still have the dialog to verify whether it's what you meant to do.

### Additional context

<img width="457" alt="Screen Shot 2021-05-05 at 3 28 24 PM" src="https://user-images.githubusercontent.com/5091167/117211658-89a6df80-adb6-11eb-8bfb-377740a11763.png">

**Comment by cheshire137** [comment]
Who's got the time to go clicky-clicking when I could whack that Enter key? 😆 Thanks for opening this!

**Comment by 1972chris** [comment]
Enter
