### ISSUE TITLE
Update upstream

### ISSUE THREAD

**Issue by maifeeulasad** [desktop/desktop#12172]
### Describe the feature or problem you’d like to solve

Update upstream by clicking a button

### Proposed solution

Github added this feature yesterday (2021.05.07) in their web. A long awaited feature, I guess. What about the same thing in GitHub Desktop. 

### Additional context

Current solution : 
```
# Add the remote, call it "upstream":

git remote add upstream https://github.com/whoever/whatever.git

# Fetch all the branches of that remote into remote-tracking branches

git fetch upstream

# Make sure that you're on your master branch:

git checkout master

# Rewrite your master branch so that any commits of yours that
# aren't already in upstream/master are replayed on top of that
# other branch:

git rebase upstream/master
```
Source : https://stackoverflow.com/a/7244456

**Comment by Mrlinkwii** [comment]
you can do this currently in 2 clicks atm  choose  to `merge  into current branch` under the branch menu option   , and choose `upstream/ (main/master)` in the next window

**Comment by tidy-dev** [comment]
As @Mrlinkwii commented, under the branch menu you can `Merge into current branch`. You can also `Rebase current branch` as that appears to be your goal. There is also the option to `Update from development` if you are just seeking to update to the most recent in the default branch. As can be seen in the branch menu, each command also have keyboard shortcuts if that is your preference for faster application traversal. Also to note, you may want to press the 'Fetch origin' button prior to this to make sure all your branches are up to date.
