### ISSUE TITLE
Wrong (short)link to issues with forked reposetories

### ISSUE THREAD

**Issue by AetherDim** [desktop/desktop#12176]
### Describe the bug
Github desktop autocompletes/links the wrong issues when used on a fork.

### Version & OS
Version 2.8.1
OS: Windows and macOS

### Steps to reproduce the behavior

1. open a forked reposetory
2. click on the description/summary field
3. write a '#'
4. This will autocomplete to the master reposetory (not the fork)

5. Commit '#1'
6. click on  #1 -> this will link to the wrong reposetory

### Expected behavior

The isses of the fork should be completed and linked.

### Actual behavior

The issues of the master/origin reposetory are linked.

### Screenshots
![image](https://user-images.githubusercontent.com/74829006/117539985-50b47800-b00d-11eb-9b32-afd38856af58.png)
![image](https://user-images.githubusercontent.com/74829006/117539998-5f9b2a80-b00d-11eb-8767-0b99a67d8531.png)

### Note
The commit on github.com links to the correct issue.

**Comment by sergiou87** [comment]
@AetherDim if you open `Repository` -> `Repository Settings…`, what do you have in the `Fork Behavior` tab?

![image](https://user-images.githubusercontent.com/1083228/120215425-00a88a00-c236-11eb-9977-4c2e03b7c2cb.png)

It will autocomplete with issues from the parent repo only if you have set the behavior to be to "Contribute to the parent repository". Is that the case?
