### ISSUE TITLE
Cannot log in to github on Manjaro

### ISSUE THREAD

**Issue by Firestar-Reimu** [desktop/desktop#12173]
Cannot log in to github on Manjaro, using the 2.7.1-1, I clicked the "log in via browser" and logged in on the Internet and use the browser to open github-desktop but it still want me to log in.

PS: the AUR package is marked out-of-date on 04/11/2021 @immackay

**Comment by tidy-dev** [comment]
@1900011604 Hi! Sorry for your troubles. However, Github Desktop only supports MacOs and Windows. I know that wasn't what you were looking for 🙁 , but you can find more about a linux fork on #1525 that might work for Manjaro as it is linux based.

**Comment by cjreyneke** [comment]
Bullshit.


#noted


# ☺=$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$


☺

**Comment by cjreyneke** [comment]
I don't give a flying fuck about you nor any one else let me show
you........kindness doos!
You are busy fucking up some one's life like you are God who can decide .


😊


-- 

CHRISTO REYNEKE

PROFESSIONAL I.T. SOLUTIONS



Tel:      +27 (0)13 656 6405

Cell:     +27 (0)60 760  <%2B27%20%280%2962%C2%A0458%203039>7744

E-mail: f <FURIOUSITSOLUTIONS@***@***.***

Web:     https://www.facebook.com/FURIOUSITSOLUTIONS


[image: Description: furious logo.png]

**Comment by cjreyneke** [comment]
This is me again responding as a human being again...I have.......no   I
did ......uhm....

Nvm, I am so confused now....:-) only small piece of mind I gave you and
your company so many years of my life.....you will pay...

Crypto....bitcoin....hellcoins..???

I am not a robot or computer to hit some random attacks.i am sitting in
flesh sending my condolences

On Monday, May 10, 2021, Christo Reyneke ***@***.***>
wrote:

> I don't give a flying fuck about you nor any one else let me show
> you........kindness doos!
> You are busy fucking up some one's life like you are God who can decide .
>
>
> 😊
>
>
> --
>
> CHRISTO REYNEKE
>
> PROFESSIONAL I.T. SOLUTIONS
>
>
>
> Tel:      +27 (0)13 656 6405
>
> Cell:     +27 (0)60 760  <%2B27%20%280%2962%C2%A0458%203039>7744
>
> E-mail: f <FURIOUSITSOLUTIONS@***@***.***
>
> Web:     https://www.facebook.com/FURIOUSITSOLUTIONS
>
>
> [image: Description: furious logo.png]
>
>

-- 

CHRISTO REYNEKE

PROFESSIONAL I.T. SOLUTIONS



Tel:      +27 (0)13 656 6405

Cell:     +27 (0)60 760  <%2B27%20%280%2962%C2%A0458%203039>7744

E-mail: f <FURIOUSITSOLUTIONS@***@***.***

Web:     https://www.facebook.com/FURIOUSITSOLUTIONS


[image: Description: furious logo.png]

**Comment by 1900011604** [comment]
> This is me again responding as a human being again...I have.......no I did ......uhm.... Nvm, I am so confused now....:-) only small piece of mind I gave you and your company so many years of my life.....you will pay... Crypto....bitcoin....hellcoins..??? I am not a robot or computer to hit some random attacks.i am sitting in flesh sending my condolences
> […](#)
> On Monday, May 10, 2021, Christo Reyneke ***@***.***> wrote: I don't give a flying fuck about you nor any one else let me show you........kindness doos! You are busy fucking up some one's life like you are God who can decide . 😊 -- CHRISTO REYNEKE PROFESSIONAL I.T. SOLUTIONS Tel: +27 (0)13 656 6405 Cell: +27 (0)60 760 <%2B27%20%280%2962%C2%A0458%203039>7744 E-mail: f <FURIOUSITSOLUTIONS@***@***.*** Web: https://www.facebook.com/FURIOUSITSOLUTIONS [image: Description: furious logo.png]
> -- CHRISTO REYNEKE PROFESSIONAL I.T. SOLUTIONS Tel: +27 (0)13 656 6405 Cell: +27 (0)60 760 <%2B27%20%280%2962%C2%A0458%203039>7744 E-mail: f <FURIOUSITSOLUTIONS@***@***.*** Web: https://www.facebook.com/FURIOUSITSOLUTIONS [image: Description: furious logo.png]

Delete them

**Comment by OscarMalan** [comment]
idk if anyone is still reading this, but I found at least that a. logging into the github CLI. and b. reloading the auth site then requesting again fixed it for me
