### ISSUE TITLE
Github Desktop as a tool for managing mono repositories

### ISSUE THREAD

**Issue by admizh** [desktop/desktop#12170]
### Describe the feature or problem you’d like to solve
Mono repositories and distributed management systems for multiple repositories are very popular. For example: Managing multiple repositories into one, it will be justified to add not only aliases (https://github.com/desktop/desktop/issues/6818) but also mechanisms for intuitive management of merge, bulk operations, synchronization between repositories ...
I take to mind into account that for example, GitHub itself works as a mono repository with forks.
It will be good if you share any ideas for managing multiple Git repositories to one over Git Desktop, it will be convenient and functional.

**Comment by steveward** [comment]
Thanks for the issue @admizh. At this time this is outside of the focus of GitHub Desktop, so I'm going to close this out. 

However it would be helpful if you could share some specific details of the types of features you would want to see implemented into GitHub Desktop to better support monorepos. If we hear enough feedback it may be something we consider again in the future. Thanks!
