### ISSUE TITLE
Allow users to zoom

### ISSUE THREAD

**Issue by donokuda** [desktop/desktop#1217]
via @cheshire137 

> wondering if font size adjustment is something that's been considered. I want to increase the font size in the app. Slack allows this via Cmd-+, like in a browser.

I agree that this is good to have, especially from an accessibility stance.

Given that there are instances where we hardcode row heights and font sizes, we might want to discuss what are the limitations that we would run into from both an experience and a technical perspective. For example, if you push Slack's zoom to 150%, the text gets cut off because it doesn't wrap and you can't scroll horizontally.

**Comment by tekkub** [comment]
Huge 👍 here.  Not all of us have young designer eyeballs, or worse, have medical conditions that impair our vision.

Even ignoring zoom settings, I'd encourage you to use larger base fonts in general. `14pt` (**not** `px`!!) minimum is a wonderful standard to aim for.

**Comment by cheshire137** [comment]
https://blog.marvelapp.com/body-text-small/ was a good article I read the other day about using a larger base font size.

**Comment by niik** [comment]
Tentatively moving this to 1.0 for prioritization and discussion

**Comment by niik** [comment]
Moving this to M5 since there's a [PR in flight](https://github.com/desktop/desktop/pull/1720)

**Comment by BBGUNN333** [comment]
## **

1. 

**

**Comment by BBGUNN333** [comment]
Trying to figure this out
