### ISSUE TITLE
Open in Xcode button doesnt work

### ISSUE THREAD

**Issue by AelyxGaelarysTaelnalys** [desktop/desktop#12175]
In a repository, if I click on "Open in XCode", the file doesnt open and error shows as shown in attached picture.
<img width="338" alt="Screenshot 2021-05-08 at 5 48 09 PM" src="https://user-images.githubusercontent.com/67012224/117538954-c9bfc980-b025-11eb-8aa0-6e9db33fb5ba.png">

**Comment by steveward** [comment]
Thanks for the report @AelyxGaelarysTaelnalys. Could you open `Console.app` and see if any specific errors are shown when XCode fails to launch? Does XCode open the file successfully outside of GitHub Desktop?

It'd also be helpful if you could upload the log file from GitHub Desktop. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by AelyxGaelarysTaelnalys** [comment]
thank you. @steveward for looking into this.

1. 

`console.app` `system.log` entry when I click on "Open in XCode" button 

> com.apple.xpc.launchd[1] (com.apple.mdworker.shared.01000000-0200-0000-0000-000000000000[1300]): Service exited due to SIGKILL | sent by mds[82]

2.

Yes. File successfully opens outside GitHub Desktop in XCode.


3.

Log file attached.
[2021-05-12.desktop.production.log](https://github.com/desktop/desktop/files/6467404/2021-05-12.desktop.production.log)

Hope I have given the information that you asked for.
thank you again. 👍

**Comment by sergiou87** [comment]
@AelyxGaelarysTaelnalys are you opening a file or the whole repo in Xcode?

The former should just work, the latter will only work if you have a xcworkspace or xcodeproj in the root of your repository. Is that the case?

**Comment by Markarek** [comment]
I have the same error, I’m taking courses and decided to switch to xcode, since it’s more convenient for me, but the thing is that when I connected it to github and added a directory, it gives the same error, I can only open separately attached code files, but not the entire directory

**Comment by DanielYamini** [comment]
Unsubscribe
