### ISSUE TITLE
The remote end hung up expectedly

### ISSUE THREAD

**Issue by dermot-murphy** [desktop/desktop#12186]
### Describe the bug

Some days I am unable to push to GitHub.

>git push --set-upstream origin feature/571_Machine_On_Detection
Enumerating objects: 141, done.
Counting objects: 100% (141/141), done.
Delta compression using up to 4 threads
Compressing objects: 100% (67/67), done.
Writing objects: 100% (80/80), 2.59 MiB | 2.07 MiB/s, done.
Total 80 (delta 62), reused 0 (delta 0), pack-reused 0
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
Everything up-to-date

### Version & OS

GitHub V2.8.0
Windows 10

### Steps to reproduce the behavior

Either use the command line command above, or within GitHub desktop Publish Branch

### Expected behavior

Normally, pushing to GitHub is problem free, but this issue has occurred a number of times over the last few weeks.

### Actual behavior

Push to GitHub failed.

### Screenshots

See above

### Logs
[2021-05-10.desktop.production.log](https://github.com/desktop/desktop/files/6451840/2021-05-10.desktop.production.log)

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

NA

**Comment by steveward** [comment]
Thanks for the report @dermot-murphy. A few questions to help diagnose this:

- Are you behind a proxy/firewall that could be interfering with Git operations? 
- How large is this repository?
- Does this error occur in multiple repositories, or just in one specific repository?
