### ISSUE TITLE
With release 2.8.1 it has become very slow

### ISSUE THREAD

**Issue by andreseduardop** [desktop/desktop#12188]
### Describe the bug

GitHub Desktop is considerably slower after installing the 2.8.1 release.

### Version & OS

GitHub Desktop Version 2.8.1
Windows 7 Ultimate, SP1.

### Steps to reproduce the behavior

1. Go to 'Changes'
2. Click on 'Any file'
4. The program hangs for a couple of seconds, before displaying the changes to the selected file.

### Expected behavior

View file changes immediately.

### Logs

[2021-05-10.desktop.production.log](https://github.com/desktop/desktop/files/6452661/2021-05-10.desktop.production.log)

**Comment by sergiou87** [comment]
Thanks for your report @andreseduardop!

Did version 2.8.0 work fine for you? I'd love to pinpoint the exact update which started causing this issue.

**Comment by andreseduardop** [comment]
Looking at the logs, the problem starts in version 2.7.2
But this is strange. The problem occurs overnight without an update.
On April 20 there was no problem. So, April 21 happens.
I attach the two logs.

## April 20.
[2021-04-20.desktop.production.log](https://github.com/desktop/desktop/files/6452760/2021-04-20.desktop.production.log)

## April 21.
[2021-04-21.desktop.production.log](https://github.com/desktop/desktop/files/6452762/2021-04-21.desktop.production.log)

**Comment by steveward** [comment]
@andreseduardop are you running any antivirus/security software on this machine? That has been the most common culprit of performance issues like this. See https://github.com/desktop/desktop/issues/11179 for an example. Let us know if that's a possibility here.

**Comment by andreseduardop** [comment]
Reviewing the logs, I find that GitHub Desktop runs very frequently the command `git remote -v`
And this blocks all other processes.

`2021-04-21T17: 47: 09.598Z - info: [ui] Executing getRemotes: git remote -v (took 1.374s)`
In the attached file lines 3, 12, 15, 21 ... and so on.
[2021-04-21.desktop.production.log](https://github.com/desktop/desktop/files/6454154/2021-04-21.desktop.production.log)

**Comment by steveward** [comment]
Thanks for sharing that @andreseduardop -- can you confirm whether or not you are running any antivirus/security software on this machine?

**Comment by andreseduardop** [comment]
> Thanks for sharing that @andreseduardop -- can you confirm whether or not you are running any antivirus/security software on this machine?

The error occurs even without antivirus.

**Comment by andreseduardop** [comment]
Apparently the error occurs because GitHub Desktop runs incessantly `git remote -v`

**Comment by sergiou87** [comment]
@andreseduardop if you see your logs, all `git` operations are taking super long when the app is trying to refresh the current state of the repository.

Could you try running `time git remote -v` in your repo from a command prompt (like Git Bash) to see how long it takes?

In the past I think other users in this situation fixed the problem by just rebooting their machines (maybe some other process was making git slower). Have you tried that?

**Comment by andreseduardop** [comment]
Thanks, @sergiou87.
The problem was solved by uninstalling and reinstalling GitHub Desktop.
The program no longer hangs. Although the `fetch` command executions take a couple of seconds, but the latter is to be expected.

[2021-05-11.desktop.production.log](https://github.com/desktop/desktop/files/6459022/2021-05-11.desktop.production.log)
Checking the log I see that `git remote -v ` no longer runs continuously.

**Comment by sergiou87** [comment]
Interesting! I'm glad you fixed it, but I'm curious… did you only uninstall GitHub Desktop or did you _also_ delete its settings?

**Comment by andreseduardop** [comment]
I just uninstalled GitHub Desktod (2.8.1). I immediately installed the same version.
Nothing more. The settings are the same.

**Comment by sergiou87** [comment]
🤯  then I wonder what could made the app run those commands more frequently (or slower) if it still uses the very same settings and repositories.

In any case, again, I'm glad it works fine now, and thank you for your patience!!! 🙇‍♂️ ❤️

**Comment by andreseduardop** [comment]
>   then I wonder what could made the app run those commands more frequently (or slower) if it still uses the very same settings and repositories.

A good question for Desktop developers. :smiley: 

@sergiou87, thanks for your attention to this issue.
