### ISSUE TITLE
Project disappears after changing Sublime into Rstudio

### ISSUE THREAD

**Issue by acromarcopolo** [desktop/desktop#12197]
My ProgrammingAssignment2 is forked from rdpeng/ProgrammingAssignment2. Then under Code, i chose open with Git Desktop.  I had to install it first, then it worked and I could even open the main .R file into Sublime.  BUT then i closed Sublime as I decided to change the default to RStudio, which I did.  Then I opened the file again, and I could never get it to appear in Rstudio.  Now the view in Git Desktop is stuck there (see attachment) and there is no .R file in sight no matter where I look.  Curiously after changing back to Sublime the file is still there, along with the Readme and History, but in Git Destkop only the History is visible, and it's not my history but that of the original fork.  Please explain what's normal, what's not, and how i can get out of this mess, meaning being to edit my files in Rstudio & do something with them in Git Desktop
<img width="953" alt="Screen Shot 2021-05-12 at 2 21 06 PM" src="https://user-images.githubusercontent.com/82025721/117976767-6ccb5880-b330-11eb-8c69-4a9a667b9044.png">
<img width="923" alt="Screen Shot 2021-05-12 at 2 41 28 PM" src="https://user-images.githubusercontent.com/82025721/117976777-6e951c00-b330-11eb-8b2a-895957157c8c.png">

**Comment by sergiou87** [comment]
Hello @acromarcopolo! 👋 

I'm sorry but I don't understand what the problem is exactly. Is it that you don't see `cachematrix.R` in GitHub Desktop? What if you make changes to it (and save it)?

**Comment by acromarcopolo** [comment]
Hi @sergiou87 ,
Right, i didn't see it in GitHub Desktop anymore. In the meantime I could locate my .R file it and open it directly in my Rstudio (which i couldn't do from GitHub Desktop since it wasn't there). I worked on it, edited it, saved it, and now it suddenly appears in GitHub Desktop.. from where i could commit it.  So i guess this is resolved for now, hopefully no more glitch ahead :)

**Comment by sergiou87** [comment]
Glad it works now! In theory your `.R` file should be visible in GitHub Desktop only when it has changes from your latest commit.

In any case, you can open the whole repository/project in Rstudio by clicking on `Repository -> Open in Rstudio` or by pressing <kbd>Control</kbd>+<kbd>Shift</kbd>+<kbd>A</kbd> (for that, you must select Rstudio as your external editor in `Settings -> Integrations`.
