### ISSUE TITLE
Scrollbar's clickable area is partially covered by the sidebar resize click area

### ISSUE THREAD

**Issue by jsunsawyer** [desktop/desktop#12190]
### Describe the bug

I use a scroll-wheel mouse and sometimes I need to click the scrollbar to drag down on a very large list of changes.

Currently, over 1/2 of the scrollbar (right side) is covered by the resize area for changing the width of the sidebar. Only a sliver of the scrollbar is clickable. This makes me accidentally resize my sidebar instead of allowing me to scroll.

### Version & OS
Version 2.8.1
macOS 10.15.7

**Comment by steveward** [comment]
Thanks for the issue @jsunsawyer. This looks like the same report as https://github.com/desktop/desktop/issues/4776, so I'm going to close this issue out and add your feedback there to bump that one up.

**Comment by jsunsawyer** [comment]
Thanks @steveward, though I looked at the issue and it seems to be pretty stale. My issue seems to be a new bug from a recent change, not a general UI improvement request.

A large portion of the actual scrollbar doesn't work as a scrollbar. Some other (invisible) UI is covering it, and it doesn't seem to be intentional.

Would be nice if this could be addressed independently of the overall scroll improvements. Also, for reference, here's the actual issue I think you were intending to reference: #4776
