### ISSUE TITLE
Seamless transition between a fork and the upstream repo

### ISSUE THREAD

**Issue by ImRodry** [desktop/desktop#12201]
### Describe the feature or problem you’d like to solve

Sometimes when you're done contributing to a project and decide to delete your fork to make a new, more up to date, one, you have to delete it on desktop and clone the upstream repo again so that you can fork it again. I believe you should be able to change the owner of a repository seamlessly so that you can switch between the original repo and your fork without having to delete and redownload so many files

### Proposed solution

In the repository settings tab there could be an option called "Change repository owner, which lets you pick a new owner and tries to fetch the repository under that name. If it succeeds, the owner changes, if not, it alerts the user that that repository wasn't found

**Comment by sergiou87** [comment]
Hi @ImRodry!

If I understand you correctly, seems like what you want to achieve is to update your fork with the latest changes from upstream, just like what you can do lately from GitHub.com: https://twitter.com/github/status/1390382527588798477

Is that right?

**Comment by ImRodry** [comment]
Not necessarily. I want to be able to switch seamlessly between a fork and the upstream repo or another fork without having to clone twice (given it's the same repo that just might differ in a few commits that could then be fetched)

**Comment by Robgizzle4** [comment]
Straight up quit sending me motherfucking emails I don't give a damn

On May 13, 2021 1:16:30 PM Rodry ***@***.***> wrote:
>
> Not necessarily. I want to be able to switch seamlessly between a fork and 
> the upstream repo or another fork without having to clone twice (given it's 
> the same repo that just might differ in a few commits that could then be 
> fetched)
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.


Sent with Aqua Mail for Android
https://www.mobisystems.com/aqua-mail

**Comment by ImRodry** [comment]
I- what 
Just disable notifications on the repo settings I guess

**Comment by sergiou87** [comment]
Ohhh ok, I thought that maybe that feature I mentioned could solve your problem as well 😅  Thanks for clarifying! ❤️ 

We've discussed about this and we haven't seen any similar requests in the past, so it's probably kind of a niche use case, and we won't add support for it unless we see more people requesting it. Sorry!
