### ISSUE TITLE
Discard changes

### ISSUE THREAD

**Issue by omerguzelelectronicguy** [desktop/desktop#12202]
### Describe the bug
I couldn't update my code on github desktop. I though there is a problem and I try to discard changes and restore to try update again. However, I cannot find my updates and cannot recover.

### Version & OS
Windows 10

**Comment by steveward** [comment]
Thanks for the report @omerguzelelectronicguy. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by omerguzelelectronicguy** [comment]
[2021-05-12.desktop.production.log](https://github.com/desktop/desktop/files/6481218/2021-05-12.desktop.production.log)
[2021-05-13.desktop.production.log](https://github.com/desktop/desktop/files/6481219/2021-05-13.desktop.production.log)
 It was night and I continue to write code by starting from start. So, I didn't remember whether it was before 24.00 or after 24.00. That is why I insert both log file.
 By the way, I code the deleted part again.

**Comment by steveward** [comment]
Thanks @omerguzelelectronicguy. I can see that there was a merge conflict preventing you from pulling:

```
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

(The error was parsed as 38: There are unresolved conflicts in the working directory.)
```

It then looked like GitHub Desktop could no longer find the repository:

```
2021-05-13T00:16:51.709Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/omerguzelelectronicguy/deneme2.git/' not found
```

I'm not sure what specifically happened based on the details you provided, but In the future you can recover your changes from the Recycle Bin if they are discarded. You can also temporarily [stash your changes](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/stashing-changes#stashing-changes) if you need to temporarily store them.  I hope that helps. I'm going to close this out, let me know if you run into any further issues.
