### ISSUE TITLE
能出个中文版吗

### ISSUE THREAD

**Issue by xianrenqh** [desktop/desktop#12205]
Can you issue a Chinese version

能出个中文版吗

**Comment by sergiou87** [comment]
Hi @xianrenqh! 👋  At this time we do not have language localization in GitHub Desktop, but this is something that we would like to pursue in the future. We don't have a timeline for when that may happen as it would require quite a bit of work by the team. I'm sorry that I don't have better news at this time.

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/GitHub-Desktop-Chinese-Language-Pack
