### ISSUE TITLE
very slow

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#12200]
update changes in realtime

decrease the update time of changes

![image](https://user-images.githubusercontent.com/38570195/118030774-bb2e2680-b333-11eb-827c-c2b1a7f39197.png)

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by sergiou87** [comment]
Hi @AlexandroGonSan! 👋 

Could you be more specific about how slow it feels for you? In general, the app should reflect any changes in your repo almost instantaneously. Is that not the case? Has it ever been?
