### ISSUE TITLE
Unable to clone a repo to Mapped network drive

### ISSUE THREAD

**Issue by merenouf** [desktop/desktop#12213]
### Describe the bug

Since version 2.6.1, when trying to clone a repo to a mapped drive, we get an error :
Unable to create '//server/path/...../.git/refs/remotes/origin/Head.lock: no such file or directory
fatal: unable to update refs/remotes/origin/Head

### Version & OS

Version 2.71 (have also tried 2.8.2-beta)
windows 2012r2 (have tried windows 2016)

### Steps to reproduce the behavior

1. Clone a repository
2. github enterprise
3. select repository
4. under local path choose path H:\repo (mapped network drive)
5. click clone

### Expected behavior

Expect the repo to clone to the selected network path

### Actual behavior

Get a error clone failed
Cloning into 'H:\repo'...
error: Unable to create ' UNC path to H drive/.git/refs/remotes/origin/HEAD.lock': no suc file or directory

### Screenshots

![image](https://user-images.githubusercontent.com/84155811/118189256-66071900-b3f6-11eb-8639-eee20f9530b6.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

I am not sure why cloning to a network mapped drive would enumerate the unc path, but I believe the issue is that the unc path has "traverse" permissions.  it appears that after 2.6.1 githubdesktop is trying to read the unc path at a level where only traverse permissions are allowed.

**Comment by steveward** [comment]
Thanks for the report @merenouf. Have you tested cloning via the command line to see if this error is reproducible there? That'd be helpful in narrowing down if this is a specific GitHub Desktop issue.

**Comment by merenouf** [comment]
I get the same error when trying to clone via the command line.    The weird thing is that if I revert github desktop back to 2.6.1 I can successfully clone from github desktop but I still cannot clone from command line.  I do see a similar error in the github logs but the clone is still successful using the 2.6.1 version.  It appears to be because users only have traverse on a portion of the unc path to the mapped drive.  I am not sure why it would be enumerating the unc path when the mapped drive is specified though.

Here is the log where the clone succeeded with 2.61:
2021-05-14T20:18:55.409Z - error: [ui] Error reporting opt out:
TypeError: Failed to fetch
2021-05-14T20:18:55.410Z - info: [ui] [AppStore] loading 3 repositories from store
2021-05-14T20:18:55.410Z - info: [ui] [AppStore] found account: ***** (*****)
2021-05-14T20:18:55.676Z - info: [ui] [BranchPruner] Last prune took place in 10 minutes - skipping
2021-05-14T20:18:55.686Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: failed to stat '                                 //*******/****/UserDocs': Permission denied

**Comment by steveward** [comment]
@merenouf thanks for the update. The embedded Git we ship with GitHub Desktop was updated after v2.6.1, but I don't believe anything was changed that would affect this. The `failed to stat` error you shared above would normally indicate another Git process is preventing GitHub Desktop from working with that file.

Are you running any other IDEs or applications that are accessing this repository and could be causing this?

**Comment by merenouf** [comment]
I downloaded version 2.26.2 of git that was in the 2.6.1 version of githubdesktop and I do not have an issue cloning the repo.  When I use 2.31.1, I get the error.  It appears there was a change to git that is causing an issue with Mapped drives where part of the unc path has traverse only permissions.  I am not using any other ide or application that would be accessing the repo.

**Comment by steveward** [comment]
@merenouf is your mapped drive SMB or NFS? I'd like to test this to see if I'm able to reproduce the issue but I want to confirm your setup.

**Comment by merenouf** [comment]
The mapped drive is SMB.  I was able to find the advanced permissions that is causesing the issue.  If I add "read attributes" to the permissions then I can now clone the folder.  
This works:
![image](https://user-images.githubusercontent.com/84155811/120546469-c90c2000-c3a4-11eb-9dd0-4e39c0d2733d.png)

This does not:
![image](https://user-images.githubusercontent.com/84155811/120546541-db865980-c3a4-11eb-9dc7-5e8cf13e6571.png)

**Comment by steveward** [comment]
I'm glad to hear you were able to get things working! And thanks for sharing the details  --  that's helpful in case other users run into this issue. I'm going to close this out.
