### ISSUE TITLE
Improve the warning badge in the commit message avatar

### ISSUE THREAD

**Issue by litetex** [desktop/desktop#12210]
### Describe the feature or problem you’d like to solve
Currently the warning icon (for "misattributed" commit) is extremely tiny and nearly invisible when using the dark mode, which causes it to get easily overlooked.
 
light mode:
![grafik](https://user-images.githubusercontent.com/40789489/118171489-8ef5d100-b42b-11eb-9742-c35141f6fb4b.png)

dark mode:
![grafik](https://user-images.githubusercontent.com/40789489/118171506-93ba8500-b42b-11eb-851b-602c0cc35c07.png)

### Proposed solution

Make the icon a bit bigger and give it a more noticeable color:

light mode:
![grafik](https://user-images.githubusercontent.com/40789489/118171617-b64c9e00-b42b-11eb-92d2-7076df6c44e9.png)

dark mode:
![grafik](https://user-images.githubusercontent.com/40789489/118171635-ba78bb80-b42b-11eb-9b8c-7e3fdd4360b7.png)

**Comment by litetex** [comment]
I created PR #12211 with the proposed changes.
It's also editable for maintainers if you want to further improve it

**Comment by intimniy** [comment]
# - [ ] - @desktopbot
