### ISSUE TITLE
Co-authors button not appearing

### ISSUE THREAD

**Issue by NoamBytes** [desktop/desktop#12229]
### Describe the bug

Co-authors button does not appear

### Version & OS

Version is 2.8.1 and I'm on Mac OS Catalina 10.15.7

### Steps to reproduce the behavior

1. Go to Github desktop
2. Add the files you're committing
3. Add a commit message and description
4. The button for co-authors is not there.

I did make sure I was signed in to Github via Desktop and I even signed out and signed back in to no avail. Another teammate of mine on the same version has the same issue.

### Expected behavior

The add co-authors button to appear

### Actual behavior

No button

### Screenshots

![Screen Shot 2021-05-17 at 1 44 25 PM](https://user-images.githubusercontent.com/17066482/118554756-b3e19100-b716-11eb-9c2a-e90fd4426ab2.png)

**Comment by NoamBytes** [comment]
Closing the issue because I ended up figuring out that it had to do with the format of the URL "Primary Remote Repository" in the Repository Settings, but this should still probably be addressed and possibly some more helpful information added to the docs as that's not currently addressed in there

**Comment by sergiou87** [comment]
@NoamBytes thanks for your report! What did you change exactly?

That button is only available for GitHub repositories, so maybe something in that URL made the app think it wasn't a GitHub repository.
