### ISSUE TITLE
clone failed to github desktop

### ISSUE THREAD

**Issue by Fahadrm** [desktop/desktop#12220]
### Describe the bug

When i try to clone repository using github desktop for my jodah group repository getting failed .

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by sergiou87** [comment]
Hi @Fahadrm! 👋 

Could you provide more details about the issue you're running into, please? Just filling out the template in your post should be enough 😄 

Thank you! ❤️

**Comment by Fahadrm** [comment]
![1](https://user-images.githubusercontent.com/55850573/118604551-ef419580-b7d2-11eb-9b99-f4880b0ea656.JPG)

**Comment by sergiou87** [comment]
Thank you for the screenshot @Fahadrm, but I'm afraid we need more information to understand what's happening 😓 
Could you fill out the template and share logs after reproducing the issue, please? Thank you!
