### ISSUE TITLE
can not login from desktop app

### ISSUE THREAD

**Issue by ugggur** [desktop/desktop#12224]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by sergiou87** [comment]
Hi @ugggur ! 👋 

Could you provide more details about the issue you're running into, please? Just filling out the template in your post should be enough 😄 

Thank you! ❤️

**Comment by ugggur** [comment]
Thank you the issue is resolved
