### ISSUE TITLE
Ability to choose other command shells (Windows)

### ISSUE THREAD

**Issue by JC3** [desktop/desktop#12223]
Windows 10, 64-bit

### Describe the feature or problem you’d like to solve

I have Git Bash installed and I much prefer it to cmd. It would be nice if there was an option to configure which shell to use for the "Open In Command Prompt..." actions.

### Proposed solution

A section in the Settings dialog where you can configure the executable and additional command line parameters to use as the shell.

**Comment by Rexogamer** [comment]
I think this is already available under the same section (**Integrations**) as the external editor settings.

**Comment by sergiou87** [comment]
As @Rexogamer pointed out (❤️ ) this is already possible in the app. You can also find some [documentation about how to integrate new shells](https://github.com/desktop/desktop/blob/development/docs/technical/shell-integration.md) if needed.

**Comment by JC3** [comment]
Not sure how I missed that for so long but 🎉💃🎉💃🎉. Thanks!!
