### ISSUE TITLE
Please support Visual Studio 2019 (and greater) as external editors.

### ISSUE THREAD

**Issue by mcquiggd** [desktop/desktop#12238]
### Describe the feature or problem you’d like to solve

Please support Visual Studio 2019 (and greater) as external editors. 

_This may also be possible with Visual Studio 2017 and 2015, which also support opening folders, in addition to being able to open solution or project files - I do not have these earlier versions, so I am not able to say for certain._

### Proposed solution

1. Check for the existence of Visual Studio in the registry, it seems that the location of devenv.exe, the Visual Studio IDE, can be found at the following location:

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\devenv.exe

2. Support passing the selected repositories absolute directory path as an argument to devenv.exe.

This would enable a enhanced workflow for Visual Studio users; this is a major editor on the Windows platform.

### Additional context

I have verified that Visual Studio 2019 is perfectly capable of opening folders as specified by GitHub Desktop, by performing the following:

1. Locate the code.cmd file that is used to provide command line support for Visual Studio Code. On my PC that is:

C:\Users\[User Name]\AppData\Local\Programs\Microsoft VS Code\bin

2. Change the contents of the file code.cmd from:

```
@echo off
setlocal
set VSCODE_DEV=
set ELECTRON_RUN_AS_NODE=1
"%~dp0..\Code.exe" "%~dp0..\resources\app\out\cli.js" %*
endlocal
```

To:

```
@echo off
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.exe" %*
```

This is simply pointing to a different executable.

3. Select Visual Studio Code as the default editor in GitHub Desktop options.

4. Open any repository in the default editor.

5. Visual Studio 2019 will open the repo in folder view.

6. Changes in Visual Studio 2019 are correctly reflected in GitHub Desktop.

7. Changes in GitHub Desktop (e.g. committing files, discarding etc) are correctly reflected in Visual Studio 2019.

**Comment by steveward** [comment]
Thanks for looking into this @mcquiggd. For reference we're broadly tracking better editor support in https://github.com/desktop/desktop/issues/7033, and would appreciate feedback there as well. I will label this as an enhancement to use for tracking Visual Studio support going forward.

**Comment by mcquiggd** [comment]
@steveward Would you like me to add a similar comment to #7033?

There might be different registry paths for different versions of Visual Studio - I am happy to investigate when I have time; let me know the best location to contribute.

**Comment by steveward** [comment]
@mcquiggd if your feedback is similar then just a 👍🏻 to the issue is good enough. We do happily accept pull requests for editor integrations, and you can find more details about how it works in [this document](https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md).
