### ISSUE TITLE
"Expand whole file" feature omits or duplicates display of lines in certain cases

### ISSUE THREAD

**Issue by PacRecAssoc** [desktop/desktop#12237]
### Describe the bug

When viewing file differences in either the Changes or History tab, selecting "Expand whole file" mode sometimes omits and sometimes duplicates display of lines.  Omitted lines can be detected by non-contiguous line numbers.  Duplicated lines contain the same "before change" line number, the same "after change" line number, and the same line content.

### Version & OS

GitHub Desktop v2.8.1
Windows 10 Pro v1909

### Steps to reproduce the behavior

1. In either the Changes or History tab, select an edited file that has differences.
2. In the differences display, right-click and select "Expand whole file".
3. Carefully examine at least five lines of context around each highlighted change.
4. Look before each highlighted change section for non-contiguous line numbers, and look after each highlighted change for duplicated line numbers (and line content).

### Expected behavior

In "Expand whole file" display mode, all lines should be displayed exactly once each and in line number order... that is, no lines should be omitted, and no lines should be duplicated.

### Actual behavior

In "Expand whole file" display mode, single lines are sometimes omitted prior to a highlighted change, and single lines are sometimes duplicated after a highlighted change

### Screenshots

Omitted line before a highlighted change:  
![image](https://user-images.githubusercontent.com/6599429/118684087-c7443900-b7b6-11eb-81d7-d1be6a7544de.png)

Duplicated line after a highlighted change:  ![image](https://user-images.githubusercontent.com/6599429/118683576-5a30a380-b7b6-11eb-8060-b5c2c9a5fd49.png)

### Logs

Not applicable.

### Additional context

None.

**Comment by sergiou87** [comment]
Thank you for your report @PacRecAssoc !! ❤️ 

Does this happen in Split view, in Unified view or in both?

**Comment by PacRecAssoc** [comment]
Wow, fast response, thanks!  Didn't know about split view until you mentioned it... cool!

This issue reproduces in both Unified view and Split view.

**Comment by sergiou87** [comment]
Awesome, thanks for the feedback 😄 

I'm trying to reproduce it here but I can't 😢  Have you identified any kind of pattern when/where this happens exactly? Or it happens all the time for you?

Have you seen it if you manually expand the file clicking on these buttons?
![image](https://user-images.githubusercontent.com/1083228/118791889-6cced980-b897-11eb-857b-f41135556883.png)

**Comment by PacRecAssoc** [comment]
Clicking on the expansion buttons does not reproduce the issue (in neither Unified nor Split view)... the issue only reproduces when selecting the "Expand whole file" context menu item (both views).

The two attached files can be used to reproduce the issue.  First check in and commit the "Original" file, then replace its contents with those in the "Changes" file and save, then "Expand whole file" and observe the line numbers.

Additionally, in my example, after selecting "Expand whole file", the final "Expand Down" button (at the bottom of the file) is still present, and not expanded... and expanding it shows another instance of the issue.

[GitHub Desktop Diff Expand Whole File Display Issue Example - Original.txt](https://github.com/desktop/desktop/files/6510203/GitHub.Desktop.Diff.Expand.Whole.File.Display.Issue.Example.-.Original.txt)
[GitHub Desktop Diff Expand Whole File Display Issue Example - Changes.txt](https://github.com/desktop/desktop/files/6510206/GitHub.Desktop.Diff.Expand.Whole.File.Display.Issue.Example.-.Changes.txt)

**Comment by sergiou87** [comment]
Ohhh I see it, I'll fix it ASAP 😄 

Thank you so much for taking the time to generate sample files for me, those are super super helpful ❤️

**Comment by PacRecAssoc** [comment]
You're welcome!

I worked for Microsoft for 18 years... started as a Software Test Engineer, and ended up as a Senior Software Design Engineer Lead.  I'm very familiar with how to repro, report, find, and fix code bugs.
