### ISSUE TITLE
Authentication failed when fetching a repository

### ISSUE THREAD

**Issue by rdash99** [desktop/desktop#12239]
### Version & OS

Github: Version 2.8.1
Windows 10 Pro Version 20H2

### Steps to reproduce the behavior

1. Go to any repository
2. Click on fetch origin

### Expected behavior

The origin to be fetched and the repository to be refreshed with updated code

### Actual behavior

Error: authentication failed

### Screenshots

![image](https://user-images.githubusercontent.com/15672040/118785254-992f2980-b888-11eb-87e7-c0cd646410ed.png)

### Logs

2021-05-19T09:04:34.886Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
fatal: Out of memory, malloc failed (tried to allocate 2764472320 bytes)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)

### Additional context

I have tried fetching on my other computer - that works and is on the same version of Github Desktop, the problem doesn't appear to be a network issue as I have tried on the same wifi as well as mobile data, I have also tried to log out and login multiple times, I don't believe that my repositories are using ssh - I could be wrong though.

**Comment by ashishrawat0** [comment]
Are the credentials in windows credential manager correct?

**Comment by rdash99** [comment]
They appear to be correct

**Comment by ashishrawat0** [comment]
> They appear to be correct

Can you remove and try again?

**Comment by rdash99** [comment]
I have tried removing the credentials in Credential Manager and signing in again, I have also tried uninstalling and reinstalling GitHub Desktop, neither made any difference.

**Comment by rdash99** [comment]
Update, I think the problem may have been caused by a lack of memory in the buffer as running: git config --global http.postBuffer 100000000 in cmd appears to have solved the problem
