### ISSUE TITLE
git clone fail and git restore fail help

### ISSUE THREAD

**Issue by luismendes070** [desktop/desktop#12242]
### Describe the bug

Cloning into 'C:\Users\luism\poligonosdemos'...remote: Enumerating objects: 25338, done.        remote: Counting objects: 100% (1385/1385), done.        remote: Compressing objects: 100% (879/879), done.        Receiving objects: 100% (25338/25338), 729.91 MiB | 239.00 KiB/s, done.remote: Total 25338 (delta 487), reused 1231 (delta 431), pack-reused 23953        Resolving deltas: 100% (6173/6173), done.error: invalid path 'packages/pwa_ionic_react_poligonosapp/src/"msw/node".d.ts'fatal: unable to checkout working treewarning: Clone succeeded, but checkout failed.You can inspect what was checked out with 'git status'and retry with 'git restore --source=HEAD :/'

Would you like to retry cloning ?

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by luismendes070** [comment]
[Uploading 2021-05-19.desktop.production.log…]()

**Comment by steveward** [comment]
@luismendes070 it looks like your log file failed to upload -- could you try sharing it again?

Based on the portion you shared it looks like this specific file is causing the clone to fail:

`invalid path 'packages/pwa_ionic_react_poligonosapp/src/"msw/node".d.ts'`

Can you verify the full path to that file for me? If there are actual quotes in the file name then that means it violates the [Windows naming conventions](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#naming_conventions) and you will need to rename the file to remove those characters. Let me know if that doesn't seem to be the case.
