### ISSUE TITLE
Everytime I close and open GitHub Desktop it logs me out and makes me reinstall

### ISSUE THREAD

**Issue by jolespin** [desktop/desktop#12246]
### Describe the bug

Every time I close GitHub Desktop it logs me out and makes me download another version manually and reinstall to log back in

### Version & OS

Tasty Things Done Tastily (224)

jespinoz@x86_64-apple-darwin13 Packages % sw_vers
ProductName:	macOS
ProductVersion:	11.2.3
BuildVersion:	20D91

### Steps to reproduce the behavior

1. Close GitHub Desktop
2. Open GitHub Desktop

### Expected behavior

To stay functional even if was an outdated version.  However, this happens with the newest version too. 

### Actual behavior

Makes me reinstall just to login. 

### Screenshots

![image](https://user-images.githubusercontent.com/9061708/118895565-428f1300-b8bb-11eb-89b9-c5fc69506b2e.png)
![image](https://user-images.githubusercontent.com/9061708/118895593-4cb11180-b8bb-11eb-9101-7e6d034f7b01.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by sergiou87** [comment]
I'm sorry @jolespin but you're using an old version (from more than 4 years ago!) that is not supported anymore. The whole login process for apps integrated with GitHub [changed in November 2020 and logins with username and password are not allowed anymore](https://github.blog/2020-07-30-token-authentication-requirements-for-api-and-git-operations/) (again, that applies not only to GitHub Desktop, but any other app that accesses to your GitHub repositories).

The only option is to download the latest version from https://desktop.github.com and start using that one instead.

**Comment by jolespin** [comment]
Oh wow! I downloaded the zip and everything then replaced it in my Applications folder.  

Are there any hidden files I need to change?

By any chance, is there a conda recipe for the desktop version ?
