### ISSUE TITLE
Mac desktop app, right/left arrow keys to move between panes.

### ISSUE THREAD

**Issue by nicholaswright** [desktop/desktop#12247]
### Describe the feature or problem you’d like to solve

When using the Mac desktop app I can use the up and down arrows to move between commits, but once on a commit I'd like to navigate to the files column and move up and down the files. The obvious action is to use the right arrow to move into the files column where it should then select the top file from where I can use the down arrow to move through the files. This is how the Mac's finder operates when in column view. 

### Proposed solution

Update the UI so that the right arrow moves from the active commit into the files column and selects the first file.

Even better would be for the right arrow to then step into the code pane.

Obviously the left arrow would step left.

**Comment by steveward** [comment]
Thanks for the feedback @nicholaswright. This sounds similar to what was requested in #9496 so I'm going to add your feedback to that thread.
