### ISSUE TITLE
Cannot remove desktop getting started 

### ISSUE THREAD

**Issue by blocktype11** [desktop/desktop#12255]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@blocktype11 thanks for the issue. Can you share a screenshot of what you are seeing in GitHub Desktop? The getting started view should go away once you clone/add/create a repository.

**Comment by blocktype11** [comment]
**The Issue was sloved**
I'm new to github.  so i started a github  desktop clicked on   "create a tutorial reposiotry" and halfway i got an error   . My repo was not  getting updated so i couldn't remove it from my github account repo this error showed "i had to remove it from github repo" somehow the  next day i found it (repo was seen on github page)i deleted it and it solved the error. Thank You
