### ISSUE TITLE
Filter changed files - option to filter whitespace changed files.

### ISSUE THREAD

**Issue by yarden-app** [desktop/desktop#12253]
### Describe the feature or problem you’d like to solve

It would be great if there was an option to see only actually changed files, those that are not only white space changed, in the changed files explorer.

### Proposed solution

It will allow faster viewing of changed files.

### Additional context
This can also open up to further features such as viewing changed files by directories, etc. (should I open a separate request in that regard?)

**Comment by steveward** [comment]
Thanks for the issue @yarden-app. You can click the gear icon in the top right-corner of the diff view and select `Hide Whitespace Changes` to hide files with whitespace changes. We're tracking broader changes filtering improvements in https://github.com/desktop/desktop/issues/6407, so you can follow along there for updates or drop any additional feedback you have. I hope that helps!

**Comment by KMVisscherLab** [comment]
no this does not work.  I'm in windows 10, and 'hiding whitspace changes' only changes the actions of the text editor display.  I think @steveward is talking about a different window than OP is asking about.  The question is about hiding those files in the 'changed files' viewer that are labeled "only whitespace changes found."  I also desperately need this functionality.

**Comment by silaghif** [comment]
> no this does not work. I'm in windows 10, and 'hiding whitspace changes' only changes the actions of the text editor display. I think [@steveward](https://github.com/steveward) is talking about a different window than OP is asking about. The question is about hiding those files in the 'changed files' viewer that are labeled "only whitespace changes found." I also desperately need this functionality.

I have exactly the same problem.....any suggestion?

**Comment by tidy-dev** [comment]
Just linking this to the "Filter changes issue" https://github.com/desktop/desktop/issues/6407 to capture an additional filter vector
