### ISSUE TITLE
[FEATURE REQUEST] Cancel clone

### ISSUE THREAD

**Issue by darigovresearch** [desktop/desktop#12267]
### Describe the feature or problem you’d like to solve

Give the ability for a user to cancel cloning a repo from within the app. Examples for use are
- you have accidently selected the wrong repository to clone
- You have chosen a repo which is too large and must wait for completion before you can delete it

### Proposed solution

Button next to progress bar to force cancel & delete any files already downloaded

### Additional context

Example of cloning a repo which may be too large so will take a while before the user can delete the files manually if they do not have enough space on their device to clone

![image](https://user-images.githubusercontent.com/30328618/119237993-c9502400-bb37-11eb-8b3c-62a856a5df2b.png)

**Comment by steveward** [comment]
Thanks for the feedback @darigovresearch. I'm going to close this in favor of the existing open issue https://github.com/desktop/desktop/issues/2082. Please follow along there for updates.

**Comment by darigovresearch** [comment]
@steveward thanks for the update & pointing in favour of the pre-existing open issue!
