### ISSUE TITLE
Describe the bug

### ISSUE THREAD

**Issue by wawa0109** [desktop/desktop#12265]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by darigovresearch** [comment]
@wawa0109 it appears the issue you had raised is the default one, did you want to submit a bug or was this an accident?

**Comment by steveward** [comment]
Thanks for reaching out @wawa0109 !

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further.
