### ISSUE TITLE
Github desktop authentication error when Fetch, but cmdline tool success

### ISSUE THREAD

**Issue by essie-chiang** [desktop/desktop#12278]
### Describe the bug

Click Fetch origin
![image](https://user-images.githubusercontent.com/3705838/119431534-56b49380-bd45-11eb-8748-bafdc3c5947f.png)

Integration Shell, tried both Terminal and iterm2
![image](https://user-images.githubusercontent.com/3705838/119431747-b1e68600-bd45-11eb-9db1-78d912b1483b.png)

In cmd tool:
add ssh key to git agent, git pull or push success

In git desktop:
show build status success
after cmd line pull, show last fetch time correct,
![image](https://user-images.githubusercontent.com/3705838/119432047-3802cc80-bd46-11eb-8100-5ddd7a306f9f.png)

But fetch with git desktop fails with an authentication error

Tried log out then log in, tried uninstall then install, also tried command line git clone new projects and then add to git desktop, it did not work. 

Also to check the preference, always be interrupted by this.
![image](https://user-images.githubusercontent.com/3705838/119431668-8f546d00-bd45-11eb-9972-fe3628790d70.png)

### Version & OS
Version 2.8.1
MacOS 10.15.7

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@essie-chiang unfortunately this error is usually caused by network issue on your end and is not a specific problem with GitHub Desktop. We've seen it mainly happen with users based in China. Are you behind a firewall that could be interfering with your connection?
