### ISSUE TITLE
Add Framework

### ISSUE THREAD

**Issue by stewart-mcleod** [desktop/desktop#12277]
### Landing page for app

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by overhiltzzz** [comment]
> ### Landing page for app
> **Allow-All**
> **Allow-All**
> **Allow-All**
> A clean and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.
> **Allow-All**
> 
> 
> ### Get at my house 
> **Allow-All**
> **Allow-All**
> **Allow-All**
> How will it benefit Desktop and its users?
> **Allow-All**
> **Allow-All**
> **Allow-All**
> ### Additional context
> 
> 
> 
> Add any other context like screenshots or mockups are helpful, if applicable.
> 
>
