### ISSUE TITLE
Can't commit multiple files

### ISSUE THREAD

**Issue by lekhasy** [desktop/desktop#12271]
### Describe the bug

The commit button disabled when i select the second file.

### Version & OS
GitHub Desktop 2.8.1 - MAC OS Big Sur 11.3.1

### Steps to reproduce the behavior

I don't have the step to produce since this only happen to me once.
This morning I just can't click on commit button (it was disabled just like no file selected). Then i tried:
Step 1, Commit one file
Step 2, Undo commit
Step 3, Commit both file => success

### Expected behavior

I should be able to commit both file in the first place.

### Actual behavior

Need to do some trick so make it work

### Screenshots

So sorry, this is all i can provide.
<img width="464" alt="Screen Shot 2021-05-24 at 10 23 26" src="https://user-images.githubusercontent.com/14049235/119292194-16d4aa00-bc7a-11eb-910d-c8d21496e0c1.png">
The only different is that the commit button being disabled.

### Logs

[2021-05-24.desktop.production.log](https://github.com/desktop/desktop/files/6529656/2021-05-24.desktop.production.log)

### Additional context

This problem has never happen, but few days earlier, i just setup git hook with `pre-commit` package:
[https://pre-commit.com/](https://pre-commit.com/)

This is my scripts in package.json:
```
"scripts": {
    "start": "react-scripts start",
    "build_dev": "node ./script/setenv-dev.js > .env && react-scripts build && mv build dist",
    "build_test": "node ./script/setenv-test.js > .env && react-scripts build && mv build dist",
    "build_prod": "node ./script/setenv-prod.js > .env && react-scripts build && mv build dist",
    "test": "react-scripts test --env=jsdom",
    "test:nowatch": "react-scripts test --watchAll=false",
    "sonar": "node_modules/sonar-scanner/bin/sonar-scanner",
    "lint": "eslint src",
    "prettier": "prettier --check ."
  }
  ```
  
  And this is my pre-commit section in package.json:
  
  ```
  "pre-commit": [
    "prettier",
    "lint",
    "test:nowatch"
  ],
  ```

**Comment by steveward** [comment]
Thanks for the report @lekhasy. We've seen commit failures due to pre-commit hooks, but I haven't seen the button disabled.  GitHub Desktop ships with an internal version of Git which we use for all actions inside the app. As such the environment within which your commit hooks execute will likely not exactly match that of your normal environment.

Since this only happened once, are you now able to commit with the pre-commit hook in place?

**Comment by lekhasy** [comment]
@steveward yes I can commit now. I can commit and push before the problem happens.
The problem only happens once.
I even have tried switch to another branch => Leave changes on the current branch => switch back to previous that branch => apply stash => the problem still happens.
I have tried to quit the app and restart it again but doesn't help.

**Comment by lekhasy** [comment]
@steveward I only use GitHub desktop for all my works but I thought hook executed inside the internal git of GitHub desktop.
In addition, I think git hook only got involved after I hit the commit button, isn't it?
anyway, this is my global git version: 2.31.1.

**Comment by lekhasy** [comment]
OH MY GOD, turn out it's my stupid mistake:
When i choose one file => i have a default commit summary
When i choose two file => i have no commit sumary => that's why the commit button disabled

Should we change the border color of summary field if user hit commit button when it's disabled?

**Comment by steveward** [comment]
@lekhasy I'm glad to hear you were able to figure out the case -- I'm going to close this out. We haven't seen this hit a large number of people but it is something we may consider in the future if we continue to get feedback about it.
