### ISSUE TITLE
Waste Commits

### ISSUE THREAD

**Issue by goyalyashpal** [desktop/desktop#12283]
### Describe the feature or problem you’d like to solve

Sometimes a bad change in local repo might be mistakenely committed. 
To avoid them being pushed, currently, it seems that only option is to delete the repository. Which feels like a nuclear option imo.

### Proposed solution

Ability to delete/remove local non-pushed commits

How will it benefit Desktop and its users?

In the above problem, this will be a life savour if there is big sized project.

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by goyalyashpal** [comment]
sort of tangentially related: https://github.com/desktop/desktop/issues/7903
duplicate issues searched by: [delete commits](https://github.com/desktop/desktop/issues?q=is:issue+delete+commits)

**Comment by tidy-dev** [comment]
HI @yashpalgoyal1304. We actually do have feature that I believe will help. 

If your commits are local non-pushed commits, they will have this up arrow indicator on them.
![image](https://user-images.githubusercontent.com/75402236/119543040-38a75d00-bd5e-11eb-9f94-967d64961ae2.png)

Any commit with that arrow can be undone via the undo button on the changes tab (which is only present when there are unpushed commits)
![Screen Shot 2021-05-25 at 1 36 52 PM](https://user-images.githubusercontent.com/75402236/119543219-6c828280-bd5e-11eb-9744-ee0961026f40.png)

This will do a `git reset --soft` on the last local commit keeping those changes locally so you can modify them or recommit them.

Hope that helps. :)

**Comment by goyalyashpal** [comment]
yeah, it worked. niiice. Thanks a lot. 👍

**Comment by goyalyashpal** [comment]
For ux suggestion:

1. it slips from the view. as it seems to be sticking in the ui boundaries. the padding from bottom can be improved to make it more vertically center aligned.
![gimp-2 10_BIYUlegY6l](https://user-images.githubusercontent.com/19423063/119547186-6cac6d80-bdb2-11eb-801a-b7c3c3a18594.png)

2. views on giving the undo button there?? 
![GitHubDesktop_T7VvfuY6Jv](https://user-images.githubusercontent.com/19423063/119545749-c90e8d80-bdb0-11eb-9437-1217bf162252.png)

**Comment by tidy-dev** [comment]
Thank you for your suggestions. We are currently in discussion for something like you are suggesting in bullet  2. 🙂

**Comment by goyalyashpal** [comment]
also, the undo-ing doesnt work well in case there are commits after the wrong commit.

https://user-images.githubusercontent.com/19423063/119629273-7b833680-be2b-11eb-9d02-7c4063982aa3.mp4

**Comment by tidy-dev** [comment]
[Here is the issue](https://github.com/desktop/desktop/issues/1644) we are tracking Amend/Undo feedback under if you want to add anything there. 🙂
