### ISSUE TITLE
x64

### ISSUE THREAD

**Issue by Sunhat** [desktop/desktop#12291]
### Describe the bug

Recent update said support for M1. Github Desktop says x64.

### Version & OS
Github Desktop 2.8.2
MacOS 11.3

### Steps to reproduce the behavior

1. Open Github Desktop
2. Look at the context menus
3. Click Github Desktop
4. Click About
5. Read 'x64'
6. 
### Expected behavior

Read 'arm64'

### Actual behavior

Read 'x64'

### Screenshots

![image](https://user-images.githubusercontent.com/16484032/119627786-6ba42c00-be04-11eb-904f-f56c6c6cea97.png)

### Additional context

Your bug report said it was mandatory to fill each field out. Was it necessary to ask for steps to reproduce and my os version? Is my macos version 11.3 going to cause typos? Do I really need 'expected' and 'actual' behaviour? Perhaps these fields aren't all required

**Comment by sergiou87** [comment]
That was fast! I just deployed the release 😂 

Right now the app doesn't auto-update from x64 to arm64 (it will in upcoming versions, when we're 100% sure it's safe). Meanwhile, you need to download the arm64 build from https://desktop.github.com/

![image](https://user-images.githubusercontent.com/1083228/119629351-3c92b800-be0e-11eb-8b77-ed05f08c298f.png)

Dropping a link here for those who land here looking for the arm64 build: https://central.github.com/deployments/desktop/desktop/latest/darwin-arm64
