### ISSUE TITLE
Open Multiple repos in multiple windows/tabs

### ISSUE THREAD

**Issue by arunim2405** [desktop/desktop#12290]
### Describe the feature or problem you’d like to solve

Currently, if you're working on two different repos, you have to switch between them in the app. The feature would allow users to open different repos in different GitHub tabs/windows

### Proposed solution
The feature would allow users to open different repos in different GitHub tabs/windows, allowing them to view different commits without having to switch the repo.

### Additional context

None.

**Comment by steveward** [comment]
Thanks for the issue @arunim2405. We're tracking feedback about this in https://github.com/desktop/desktop/issues/3606 -- you can follow along there for updates.
