### ISSUE TITLE
Reorder commits in commit history

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#12299]
### Describe the feature or problem you’d like to solve

When we've gotten feature requests for interactive rebase, one of the things people say they're using it for is to reorder commits. So let's enable that!

### Proposed solution

Now that we have a drag-drop paradigm from cherry-picking, we can use that to let people drag commits to wherever they would like in the commit history.

Note: This should play well with squashing since we'll be enabling that with drag-drop functionality as well.

**Comment by Kurt-von-Laven** [comment]
This would be great! It's one of a small handful of lingering issues keeping our team from adopting the tool, because we rebase a lot. Right now we rely on GitLens for this graphical interactive rebases, but I believe it is buggy.
