### ISSUE TITLE
Organize files by folders

### ISSUE THREAD

**Issue by Nanokaso** [desktop/desktop#12307]
### Organize files by folders

Recently I found problems to commit some files in specific
And I thought a folder organization would be cool

Visual Studio nowadays has this facility:
![image](https://user-images.githubusercontent.com/38362771/119858634-08d99000-beeb-11eb-8e30-bcb66384ac0f.png)

But I've been using gitdesktop for a long time and I feel familiar with the shortcuts.

An example that can be used as inspiration is SublimeText or even Visual Studio:
(sublime text)
![image](https://user-images.githubusercontent.com/38362771/119857809-3ffb7180-beea-11eb-8106-68d7a4e10948.png)

This would be useful for many developers

**Comment by billygriffin** [comment]
Thanks @Nanokaso for the issue. Unfortunately, lots of different people have different preferences for how files are displayed and we don't think it's compelling enough at this point to fundamentally alter the layout of files changed in the app. I also think that GitHub Desktop is a different tool for a different purpose than VS Code or Sublime Text or another text editor, and therefore it makes sense that they'd have different layouts. Thanks again and hope that makes sense.

**Comment by Nanokaso** [comment]
@billygriffin Thanks for the answer. And I understood perfectly.
