### ISSUE TITLE
No content changes found

### ISSUE THREAD

**Issue by HaoSun1** [desktop/desktop#12300]
![image](https://user-images.githubusercontent.com/26881685/119696036-c6e21880-be1c-11eb-80e7-db5c4b2a8520.png)

I don't know why this happens I open dropbox and GitHub suddenly detects changes but there are no changes.

**Comment by steveward** [comment]
@HaoSun1 thanks for the issue. Usually this is the result of either line endings changes or file mode changes. My recommendation would be to normalize the line endings in your repository by adding a `.gitattributes` file with the `* text=auto` line. You can read more about managing line endings (along with other options) in [this article](https://docs.github.com/en/github/getting-started-with-github/getting-started-with-git/configuring-git-to-handle-line-endings). 

Let me know if that doesn't get things working and we can dig into this further.
