### ISSUE TITLE
Branch : based on

### ISSUE THREAD

**Issue by goyalyashpal** [desktop/desktop#12312]
### Describe the feature or problem you’d like to solve

currently, the option of new branch > based on differ hugely. And the choices remain hidden and arent accessible easily

### Proposed solution

Show both the "default of upstream" and "default of your repository" when creating a new branch. Contrast this with current behaviour of hiding either of these on the basis of what i've chosen in `Repository settings > Fork behaviour` which leads to unnecessary frustrating situations.

### Additional context

suggestion's illustration
![image](https://user-images.githubusercontent.com/19423063/120042114-1a27b700-c027-11eb-97d7-84878c21ef61.png)

**Comment by goyalyashpal** [comment]
reserving

**Comment by billygriffin** [comment]
Hi @yashpalgoyal1304, thanks for the issue. We currently allow you to base new branches on either the default branch or your current branch, which has been a pretty well-liked approach given most people's workflows. We don't have plans to change this so I'm going to close this issue, but I'm curious to learn more about how you'd expect this to work?

**Comment by goyalyashpal** [comment]
@billygriffin smth like this was my expectation, i.e. "default of upstream" and "default of your repository" both shown together alongwith usual "currently checkout". I dont want either of it to be hidden on the basis of what i've chosen in Repository settings > Fork behaviour.

![image](https://user-images.githubusercontent.com/19423063/120042114-1a27b700-c027-11eb-97d7-84878c21ef61.png)

**Comment by billygriffin** [comment]
Ah, yeah, I can see that. I'm curious why sorting by how you're using the fork isn't working for you? Like, in what instances are you wanting it to be one way vs. the other way?

**Comment by goyalyashpal** [comment]
> one way vs. the other way

taking this as to be different ways of basing branch on (my master/upstream master):

i initially might have set this as "for my own purposes" and then got involved in the coding related stuff. Committed mistakenly to my repo's master, then later while have to rebase etc, got blatantly clueless where the button to base branch based on upstreams went (i.e. might have used it once before)., and was not able to figure out what to do. I tried switching this Fork behaviour setting too iirc, but it didnt seem to work. maybe as i was in state of hurriedness and missed some required step.

All in all, current behaviour caused me lot of trouble, and the solution doesnt damage anything imo. So... Also, this will be a bit like foolproofing for newcomers.

But i can imagine it being used in non-mistake / intentional use cases too. Like say you are doing things for ur own purpose, but then u have created smth which u want to merge upstream too. So, t'll have to be cherry-picked to branch based on upstream's repo for that particular thing. While the rest of ur main efforts remain focussed on ur own repo/purpose.

**Comment by billygriffin** [comment]
Got it, thanks @yashpalgoyal1304. You can always change the setting in Repo Settings, but I hear you. We've gone through several iterations of this and part of the goal of Desktop is to help make you think less by putting you in the right context. More choices and options can be helpful, but they can also be overwhelming, so we try to give people choices at the best times with the best context. That's not always going to be perfect, as it clearly wasn't in the case you described. But I think we've seen that this approach has been pretty reasonable and with so many users who use the existing patterns, we're hesitant to change it again without overwhelming feedback that it's not working for people. Thanks again for sharing!
