### ISSUE TITLE
Commit bug, duplicating the first letter

### ISSUE THREAD

**Issue by germanolira** [desktop/desktop#12314]
### Describe the bug

I have had problems with Github Desktop when 'commit', whenever I create a new project, the first letter is duplicated, and this bug happens and I can't commit, I've seen some tutorials on 'commit' in the terminal to try to solve this problem, but it didn't work.

### Version & OS

Version 2.8.2 (x64) - Windows 10 Version 21H1

### Steps to reproduce the behavior

On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	react-native/chapter-2/

nothing added to commit but untracked files present (use "git add" to track)

### Expected behavior

I expected to click 'commit to main' and everything would work, I didn't do anything for it to stop working, I just created a new folder with expo init gofinances and this error started to appear, but when I went to create a new project, this error also appeared .

### Actual behavior

I have had problems with Github Desktop when 'commit', whenever I create a new project, the first letter is duplicated, and this bug happens and I can't commit, I've seen some tutorials on 'commit' in the terminal to try to solve this problem, but it didn't work.

### Screenshots

![image](https://user-images.githubusercontent.com/25235170/120056995-4850cb00-c016-11eb-8dc1-052e5e4efad2.png)

### Logs

[2021-05-29.desktop.production.log](https://github.com/desktop/desktop/files/6563987/2021-05-29.desktop.production.log)

### Additional context

I don't know if it's a bug, or if I'm doing something wrong, but there is still a bug where it is duplicating the first letter of the project.

**Comment by BaichuanTang** [comment]
same here

**Comment by sergiou87** [comment]
I'm trying to reproduce that behavior but I cannot… what is that `gofinances1` exactly? Is it a file or a folder?

**Comment by germanolira** [comment]
> I'm trying to reproduce that behavior but I cannot… what is that `gofinances1` exactly? Is it a file or a folder?

A folder

**Comment by germanolira** [comment]
![image](https://user-images.githubusercontent.com/25235170/120228874-625ef900-c222-11eb-9e24-0c8335b72a3c.png)

**Comment by sergiou87** [comment]
And is that folder (or any of its subfolders) also a git repository? I ask because I'm unable to reproduce this 😅

**Comment by germanolira** [comment]
> And is that folder (or any of its subfolders) also a git repository? I ask because I'm unable to reproduce this 😅

![image](https://user-images.githubusercontent.com/25235170/120369238-5db14800-c2e9-11eb-95bb-eaac1d76e1a9.png)

**Comment by germanolira** [comment]
![image](https://user-images.githubusercontent.com/25235170/120369296-702b8180-c2e9-11eb-9161-e0b9b81939a1.png)

**Comment by germanolira** [comment]
![image](https://user-images.githubusercontent.com/25235170/120369346-820d2480-c2e9-11eb-85ae-00c35085e058.png)

**Comment by germanolira** [comment]
I just realized that I could have posted all the photos in just one comment

**Comment by sergiou87** [comment]
Ohhh thanks for those screenshots! The problem seems to be you're adding repositories inside of a repository, so that `gofinances1` is a repository. I still don't understand why it duplicates the first character, but the error committing seems to be related to that.

If you don't want `gofinances1` to be a repository, you can remove its `.git` folder (which might be hidden).

**Comment by germanolira** [comment]
I still have problems with commit, I'm having to use the terminal

![image](https://user-images.githubusercontent.com/25235170/120877950-a12ce000-c58f-11eb-8834-3a5cb5657be0.png)

**Comment by germanolira** [comment]
When I change something, I get these weird "subproject commit" numbers

**Comment by jil-jeep** [comment]
Very Nice .

**Comment by steveward** [comment]
This came up in https://github.com/desktop/desktop/issues/12693.

**Comment by steveward** [comment]
This was previously reported in https://github.com/desktop/desktop/issues/4670 as well.

**Comment by steveward** [comment]
Another report in https://github.com/desktop/desktop/issues/13007.

**Comment by Gonzalobarrioss** [comment]
> 
> 
> Ohhh thanks for those screenshots! The problem seems to be you're adding repositories inside of a repository, so that `gofinances1` is a repository. I still don't understand why it duplicates the first character, but the error committing seems to be related to that.
> 
> If you don't want `gofinances1` to be a repository, you can remove its `.git` folder (which might be hidden).

It worked for me. Thank you!

**Comment by steveward** [comment]
Another report in https://github.com/desktop/desktop/issues/13518.

**Comment by Kunal-5020** [comment]
I know how to fix the issue first 
what is actually the issue Is?
->it happens when there is a **_.gitore file_** or the **_.git folder(which is hidden)_** are present in the folder you are commiting 
how to resolve it ? 
-> simply remove these and you can fix it 
and to find the hiddent .git folder you can check this image 
![Screenshot 2024-11-13 155524](https://github.com/user-attachments/assets/340fea3d-4165-4026-b01f-8aa5a21e3ab9)
