### ISSUE TITLE
Unable to clone a Project Wiki

### ISSUE THREAD

**Issue by jgyo** [desktop/desktop#12310]
### Describe the bug
When I try to clone a wiki of one of my projects locally using Github Desktop, I get an error message stating, "We couldn't find that repository. Check that you are logged in, the network is accessible, and the URL or repository alias are spelled correctly."

### Version & OS
 - GitHub Desktop 2.8.2 (x64)
 - OS Name: Windows 10 Home
 - OS Version: 10.0.19041

### Steps to reproduce the behavior

1. Open Github project wiki page at https://github.com/jgyo/PluginManager/wiki
2. Click on the copy button by "Clone this wiki locally."
![Snag_5b682c5](https://user-images.githubusercontent.com/2886615/119911368-d5b0f400-bf1e-11eb-9732-bd7752385265.png)
3. Open Github Desktop.
4. Check login status at File/Options under Accounts.
![Snag_5b6b0bb](https://user-images.githubusercontent.com/2886615/119911379-dcd80200-bf1e-11eb-87f1-2579d19f9f80.png)
5. Close Options.
6. Press Ctrl-Shift-O to open Clone a repository.
7. Click the URL tab.
8. Click in the URL field.
9. Press Ctrl-V to paste the wiki repository address.
![Snag_5b6e4ea](https://user-images.githubusercontent.com/2886615/119911399-e497a680-bf1e-11eb-9136-acf81f480028.png)
10. Click the Clone button.
11. See error.
![Snag_5b716a8](https://user-images.githubusercontent.com/2886615/119911426-ed887800-bf1e-11eb-8876-718725eb76bd.png)

### Expected behavior
The operation should clone wiki documents locally.

### Actual behavior
An error message stating, "We couldn't find that repository. Check that you are logged in, the network is accessible, and the URL or repository alias are spelled correctly," appears.

### Logs
The log file does not contain any reference to the operation.
[2021-05-27.desktop.production.log](https://github.com/desktop/desktop/files/6557360/2021-05-27.desktop.production.log)

**Comment by billygriffin** [comment]
Hi @jgyo, thanks for the issue, and sorry you're running into that. We don't have great support for wikis in Desktop unfortunately, and we're tracking that in https://github.com/desktop/desktop/issues/3839, so please follow along there. For full transparency, I don't anticipate we'll be working on this anytime in the near future because our team is small and we have to prioritize things that are likely to significantly benefit a greater percentage of users. Thanks again!

**Comment by jgyo** [comment]
Thanks for the info. I was able to clone the wiki with the Visual Studio Git feature, so I'm happy.
