### ISSUE TITLE
Using HTTP protocol to clone repositories

### ISSUE THREAD

**Issue by ferenczy** [desktop/desktop#12321]
I just noticed that the app is using the HTTP protocol to clone repositories (I didn't check other operations). Isn't it a bug, shouldn't it be using HTTPS instead?

### Version & OS

GitHub desktop: 2.8.2 (x64)
Operating system: Windows 10 Pro

**Comment by sergiou87** [comment]
Thanks for your report @ferenczy!!

Just curious, where do you see it's using HTTP and not HTTPS? 🤔

**Comment by ferenczy** [comment]
@sergiou87 Sorry, I didn't describe it very clearly. Also, I'm, not sure if it's even related to the GitHub app and not to Git. And I also don't know what actual request was it trying to make using the HTTP protocol, maybe it wasn't the cloning itself, it just happened when I tried to clone a repository.

This is how I had noticed it: **I tried to clone a repository** in the GitHub app on a computer in a corporate network with a proxy server for outgoing connections **and it failed with the HTTP error `407 Proxy Authentication Required`**. So I checked my `.gitconfig` and noticed that **I had the proxy server configured for the HTTPS protocol only**. When I added it also for the HTTP protocol, the GitHub app cloned the repository successfully. So it looks like something actually tried to make an HTTP request before or during the cloning, I guess.

**Comment by sergiou87** [comment]
No worries!! Was that a GitHub repository? Or was it hosted somewhere else?

**Comment by ferenczy** [comment]
It's a GitHub repository.

And it's not just about the cloning, it looks like any network operation ends with the `407` error, for example pull or fetch. But only when it's made from the GitHub app. When I use the CLI Git client in a Powershell or Git Bash terminal (opened from the GitHub app's _Repository_ menu), it performs the operation on the same repository successfully. Even though both clients share the same configuration.

BTW the GitHub app is using the CLI Git client for any manipulation with repositories, isn't it? If so, then it looks like the app is trying to make a network request before it actually executes the Git CLI command to perform the repository operation.

I have tried to analyze the network traffic using Fiddler but got some confusing results, I have to dedicate more time to that and check it again. Will let you know when I know more.

It's not a very critical issue (actually that depends on if it's really making an unencrypted HTTP request or not and mainly what's being transfered in that request), but would be good to know what exactly is happening there anyway.

**Comment by sergiou87** [comment]
> BTW the GitHub app is using the CLI Git client for any manipulation with repositories, isn't it?

That's right! The only requests the app does directly, AFAIK, are requests to GitHub.com API (list of issues, list of PRs, list of users, clone info for a repo…).

I still can't repro the issue, so I'm gonna close this. But if you find anything that we can investigate, please post it and I'll be happy to reopen!!

Thank you again for reporting and looking into this 🙇‍♂️ 🙇‍♂️ 🙇‍♂️
