### ISSUE TITLE
not able to drag and drop the folder in github

### ISSUE THREAD

**Issue by shriSundaram** [desktop/desktop#12329]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by sergiou87** [comment]
Hi @shriSundaram! 👋 

Could you provide more details about your problem? Thanks!
