### ISSUE TITLE
Ghost changes

### ISSUE THREAD

**Issue by augustvc** [desktop/desktop#12324]
### Describe the bug

There are "changes" that are not actual changes. When I try to restore my stash, I am not allowed to because there are "changes". When I try to discard them, nothing happens. When I add them to the .gitignore, nothing changes. When I try to commit them, it says I didn't add any changes to the commit.

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

I am working with glitter, and folders are automatically being changed (appending a -dirty). Glitter/Vendor/assimp and Glitter/Vendor/imgui. Like this:
Subproject commit 40f9d37a38209f0dbd10b71361bc905d314f10a7
Subproject commit 40f9d37a38209f0dbd10b71361bc905d314f10a7-dirty

### Expected behavior

I expected it to be ignored by git, and not registered. So that I could freely do whatever with git without being blocked from doing certain actions because of ghost changes.

### Actual behavior

I permanently have 2 "changed files" in the changes tab. I can not discard the changes or ignore them, they are always there. As a result I am not able to restore my stash, or do other things that are blocked by having pending changes.

### Screenshots

When I try to commit the "changes", this happens:
![image](https://user-images.githubusercontent.com/22351360/120192319-528fe680-c21b-11eb-860b-4969f19b9735.png)

The Restore button is unable to be clicked:
![image](https://user-images.githubusercontent.com/22351360/120192554-9d116300-c21b-11eb-856f-8c79dfeb7e21.png)

Adding it to .gitignore doesn't make a difference
![image](https://user-images.githubusercontent.com/22351360/120192671-c3cf9980-c21b-11eb-9c28-15814a58d5f1.png)

### Logs

None

### Additional context

None

**Comment by steveward** [comment]
Thanks for the issue @augustvc. Being unable to commit submodule changes is being tracked in https://github.com/desktop/desktop/issues/1770. If you need to work around this you can ignore the submodule changes by editing the `.gitmodules` file. See [this issue comment](https://github.com/desktop/desktop/issues/7823#issuecomment-581195520) for reference.

**Comment by steveward** [comment]
Closing this as we are tracking various submodule improvements in other issues.
