### ISSUE TITLE
update-index --skip-worktree is ignored in changes

### ISSUE THREAD

**Issue by Sil-Boydens** [desktop/desktop#12322]
### Describe the bug

the list of changed files is showing files that are set to ignore using --skip-worktree

### Version & OS

OS: W10 pro 1909
App: 2.8.2 (x64)

### Steps to reproduce the behavior

1. run command `git update-index --skip-worktree config/editor.ini` (or any other changed file in the repo)
2. look at changed files list in desktop (even after restarting)

### Expected behavior

desktop should show the same list of files as `git status` does.

### Actual behavior

desktop is showing files that `git status` is ignoring

### Additional context

our editors continiously change these files and update the "last 3 opened files" in them, this to have a shortcut to re-open recently closed files per project. but this causes a lot of merge conflicts.
however the same config files also include settings that we want to track in git.
using the --skip-worktree i want it to not list these changes so the devs who are not as good in git would stop committing these files.
if an update to these files is required, i will do a manuel `git add` to update them. our developers that only use the desktop client  (as they don't know how to use the cli) don't need to update these files.

if someone can tell me a way to hide these files from desktop but still be able to track changes when i want it (using cli), let me know pls.

**Comment by sergiou87** [comment]
I just tested this and works as expected. Do you have anything in your git config (global or local) that could be interfering with this behavior?

**Comment by Sil-Boydens** [comment]
i did some more testing and it seems to be wildcard related
`git update-index --skip-worktree conf*/*.ini` is the original command i did as i wanted to hide hundreds of files from several diffrent folders;
but doing `git update-index --skip-worktree conf-server/msaps-broker.ini` does hide that one file from the desktop app.
my global git config is just username and password and `git ls` alias, there is no local git config for the project

**Comment by sergiou87** [comment]
I just tried using wildcards and still works as expected here 😕 

Would you be able to provide a detailed example with which I could reproduce and investigate the issue?

**Comment by Sil-Boydens** [comment]
i tried in a small repository and can not reproduce.
trying again in the big project i found this issue in originally and i can repro it.
however, this is with 500+ changed files (refactoring to add consistency)
if i stash my changes and try i can't reproduce it.
something about the huge amount of changed files make it not pick up changes even after restarting.
*got interupted while writing this*
i was helping a colleage and left desktop open with the files showing that it should skip (even the files from yesterday where still showing), when i came back to my pc they weren't showing anymore. so i just had to keep desktop open on that repository for a while and give it time to refresh.
if it's just that it takes time in big project with lots of changes to remove files from the changed list, the issue can be closed or changed to feature request:
can there be a way (button menu item or keyboard shortcut) to force an index rebuild?
i already saw an feature request asking for a progres bar on index rebuilds (#11614) making what he proposes a seperate button to force refresh the index can help people with my situation. 
(or a keyboard shortcut/menu option starts an index rebuild and it shows over the push/pull button as suggested by jonathan)

**Comment by sergiou87** [comment]
Thank you for your feedback! ❤️  It's definitely a weird issue, so I'll close this for now.

Regarding the index rebuild: we haven't seen many requests for that feature, so it's not in our roadmap. We also haven't seen a clear use case for it 😅
