### ISSUE TITLE
Can't find Sublime Text 4

### ISSUE THREAD

**Issue by stervel** [desktop/desktop#12349]
### Describe the bug

Github Desktop doesn't seem to recognize that Sublime Text 4 is installed. I have only ST4 installed in my machine and GD says "no editors found".

### Version & OS

Version 2.8.3 (x64), Windows 10 Home 20H2

### Steps to reproduce the behavior

1. Go to "Options"
2. To "Integration"
3. See error

### Expected behavior

There should be a choice to select and integrate ST 4 but there's nothing to select and GD suggests me to install another editor instead.

This should be pretty easy to solve, right? I'm new to GD or anything.

**Comment by steveward** [comment]
Thanks for the issue @stervel. This should be resolved once https://github.com/desktop/desktop/pull/12297 is merge in, so I am going to close this out.
