### ISSUE TITLE
Save text in Description and Summary text boxes

### ISSUE THREAD

**Issue by Halen84** [desktop/desktop#12348]
### Describe the feature or problem you’d like to solve

When the app closes, save the inputted text in the Description and Summary text boxes.

### Proposed solution

Can be used as a changelog for example so you don't have to put your changes elsewhere if you don't have a designated location to put them. So instead of putting your changes in another location and then paste them in the text boxes when your ready to push a commit, GitHub Desktop will remember what text was in the text boxes.

### Additional context

![Screenshot 2021-06-02 164301](https://user-images.githubusercontent.com/55899402/120556095-a76d6180-c3c1-11eb-8183-d96b62be499d.png)

**Comment by billygriffin** [comment]
Hi @Halen84, are you frequently closing the app mid-commit and that causes you to lose the summary and description when the app closes? Just trying to understand how this will be useful for you (and potentially for others).

**Comment by Halen84** [comment]
> are you frequently closing the app mid-commit and that causes you to lose the summary and description when the app closes?

Yes. 

So basically what I'm trying to say here, GitHub Desktop should remember what was in the description and summary boxes.

Personally, this would speed up my process of pushing commits so I can just commit without having to re-enter a summary and description of the commit.

It can be useful for when you make some changes, you can change the description of what you changed instead of having to remember what you changed since the text boxes are cleared when the app closes. If I make a small change in some code, I can just add it to the description and safely close the app.

**Comment by billygriffin** [comment]
I guess I'm wondering under what circumstances you're closing the app while you're in the process of using it? That's the part that's not apparent to me, so I'd love to hear why you're doing that or what's causing that chain of events.

**Comment by Halen84** [comment]
I'm sorry if I'm not understanding your question here.

I really only used GitHub Desktop to review changes I make in my external editors (Visual Studio 2019 & Atom). Reviewing takes only a couple of seconds to a few minutes depending on the amount of changes, which means I'm not heavily using the app.

**Comment by billygriffin** [comment]
Thanks! I think I'm confused about why you're writing a commit summary and description and *not* committing, and then closing the app? 

Most of the workflows I've seen involve writing commit messages as part of crafting the commit. And even if you're writing something ahead of time, typically we've seen people keep the app open until they finish committing, which preserves the commit message. I really appreciate you sharing your workflow, but given that this does seem relatively atypical, I'm going to close this issue. If you'd like to share more about how this happens, I am interested in learning more, and apologies that I can't give you a better answer.
