### ISSUE TITLE
Add ignore directory to context menu of a commit

### ISSUE THREAD

**Issue by Yakov5776** [desktop/desktop#12359]
### Describe the feature or problem you’d like to solve

If you want to add a folder to .gitignore you have to add it manually.

### Proposed solution

Add Ignore Directory to the context menu just like there is Ignore File.

### Additional context

![image](https://user-images.githubusercontent.com/28637006/120682213-30d86e80-c46a-11eb-8d2e-00c7f3164b2d.png)

**Comment by steveward** [comment]
Thanks for the issue @Yakov5776. We are tracking this in https://github.com/desktop/desktop/issues/1203, you can follow along there for updates.
