### ISSUE TITLE
not able authenticate from git desktop 

### ISSUE THREAD

**Issue by vivekgowdatv1992** [desktop/desktop#12374]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by Mrlinkwii** [comment]
:wave:  hello  @vivekgowdatv1992  , 

Could you provide more details about your problem and update the template ? Thanks!
