### ISSUE TITLE
GitHub shows all files are new, doesn't show cadges until after commit

### ISSUE THREAD

**Issue by ramtronik** [desktop/desktop#12392]
### Describe the bug

this is a known bug, upgraded my GitHub today, still an issue. it means you can't code review unless you commit, which isn't much use.

**Comment by steveward** [comment]
@ramtronik thanks for the report. Usually this is the result of either file mode or line ending changes in your repository. Can you check what `git diff <file_name>` shows for a specific file in your changes list? That should indicate if it is a line endings or file mode issue.

**Comment by ramtronik** [comment]
I would say neither. I’ve just gone through every repository, all showed a sensible list of changes. )I already committed the problematic one).

But, if I restart github dersktop and choose a repo, I get 847 additions.

Including the .gitattributes and .gitignore.

The diff command shows nothing at all. As I would expect (I chose readme.md)

But …

I used ‘copy path’ on the gui, and tried to enter it, but it didn’t work.

Mac-mini:~ phil$ cd /Users/phil/Library/Mobile Documents/com~apple~CloudDocs/IOS Development/Canvey-App-iOS/
-bash: cd: /Users/phil/Library/Mobile: No such file or directory
Mac-mini:~ phil$ cd /Users/phil/Library/Mobile\ Documents/com\~apple\~CloudDocs/IOS\ Development/Canvey-App-iOS
Mac-mini:Canvey-App-iOS phil$ ls
README.md The Canvey App
Mac-mini:Canvey-App-iOS phil$ git diff README.md
Mac-mini:Canvey-App-iOS phil$ /Users/phil/Library/Mobile Documents/com~apple~CloudDocs/IOS Development/Canvey-App-iOS/.gitattributes

The path doesn’t include certain backslashes in the cloud docs path (my mac had icloud set up on it) … like I said, it sorts itself out after commit, but the gui seems to get itself in a twist when you restart it.

Hope that helps.

Regards,
Phil

**Comment by steveward** [comment]
@ramtronik I'd recommend adding the `* text = auto` line to your `.gitattributes` file to normalize the line endings. Once you commit those line-endings changes this problem should go away for you. See [this help article](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings) for more information. Let me know if that doesn't get things working.
