### ISSUE TITLE
GitHubDesktop repeatedly tries to install helper tool. Even if I enter the password, keeps asking.

### ISSUE THREAD

**Issue by mctrafik** [desktop/desktop#12395]
### GHD update process broken for OSX.
Multiple times a day GHD asks me to input my password to install a "helper tool" on OSX. Even if I enter a password, it still pop up immediately after. Sometimes this happens over 10x times even if I input my password. This is broken. We need the ability to turn off auto updates, install GHD into a non-admin directory and have an update process that doesn't require root access. 

Note that whatever is causing this it's separate from normal updates, which show up in the update tool and those go through just fine.

**Comment by steveward** [comment]
@mctrafik thanks for the issue -- can you try [this workaround](https://github.com/desktop/desktop/issues/3616#issuecomment-400371047) and see if that gets things working for you?

**Comment by mctrafik** [comment]
Tried it:

```shell
<machine> % sudo ls -l /Applications | grep "GitHub Desktop" 
drwxr-xr-x   3 root       wheel          96 May  5 00:41 GitHub Desktop.app
<machine> % sudo chown <username> "/Applications/Github Desktop.app" 
<machine> % ls -l /Applications | grep "GitHub Desktop"        
drwxr-xr-x   3 <username>  wheel          96 May  5 00:41 GitHub Desktop.app
```

Will let you know if that works next time the update thing comes up.
