### ISSUE TITLE
"Pin" the repositories menu to the left as a side menu.

### ISSUE THREAD

**Issue by adrianspacely** [desktop/desktop#12399]
### Describe the feature or problem you’d like to solve

I work between two projects that integrate with one another. It's painful clumsily clicking back-and-forth through the repos menu.

### Proposed solution

It would make life easier if the repositories menu had a pin icon I could click to keep it showing as a side menu rather than a dropdown menu.

### Other possible solutions

* Being able to "favourite/star" repos, and using cmd+[1...9] to switch between those repos.
* A command pallet prompt like in sublime text or VS Code to quickly do something.

**Comment by steveward** [comment]
Thanks for the feedback @adrianb93! I'm going to add this to https://github.com/desktop/desktop/issues/8183 where we are tracking feedback about repository pinning.
