### ISSUE TITLE
Can't integrate Sublime Text 4 on Big Sur

### ISSUE THREAD

**Issue by dchassin** [desktop/desktop#12398]
### Describe the bug

Sublime is not listed:

<img width="585" alt="image" src="https://user-images.githubusercontent.com/20801735/121093407-d7da4480-c7a1-11eb-9b19-f8fc347fef2e.png">

Yet Sublime is installed:

<img width="813" alt="image" src="https://user-images.githubusercontent.com/20801735/121093447-e7598d80-c7a1-11eb-98c8-bcef0e8f615f.png">

### Version & OS

GitHub Desktop Version 2.5.7

~~~
$ uname -a
Darwin PC98798 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
~~~

### Steps to reproduce the behavior

1. Go To "GitHub Desktop"
2. Choose "Preferences..."
3. Voila... or rather "ou est-ce?"

### Expected behavior

Sublime Text should be listed

### Actual behavior

Nothing is listed

### Screenshots

See above

### Logs

NA

### Additional context

NA

**Comment by steveward** [comment]
@dchassin is there a chance you have not restarted GitHub Desktop since installing the new version of Sublime Text? GitHub Desktop needs to be restarted to detect new editor installations.

**Comment by dchassin** [comment]
> @dchassin is there a chance you have not restarted GitHub Desktop since installing the new version of Sublime Text? GitHub Desktop needs to be restarted to detect new editor installations.

Yes, I have restarted GitHub desktop, and it made no difference.

**Comment by say25** [comment]
I don't believe Sublime 4 has been added for macOS (or Windows for that matter yet). Windows support seems to be in-flight https://github.com/desktop/desktop/pull/12179 but I don't believe anyone has picked up this effort for macOS.

**Comment by sergiou87** [comment]
> GitHub Desktop Version 2.5.7

@dchassin I think the problem is you have a really old version of GitHub Desktop. Version 2.5.7 was released ~7 months ago, and Sublime Text 4 support was added ~5 months ago in 2.6.2.

Please, update to the latest version and let us know if that doesn't fix it 😄

**Comment by dchassin** [comment]
@sergiou87, interesting. This is newly minted system and this happened after I installed GitHub Desktop and it told me that an update was available, which I accepted (which in retrospect is itself odd given it was a fresh download).  I won't be able to access the system for about 10 days, so I'll let you know what I find out when I can access it again.

**Comment by dchassin** [comment]
@sergiou87, it is worth noting that on my laptop I have GitHub Desktop 2.8.3 and Sublime 4107 and it works fine.  Thanks for the info. This seems like an easy fix.

**Comment by sergiou87** [comment]
The fact that it suggested you to update a version you just downloaded sounds bad, specially to such an old version 😥 We'll investigate, thank you!!

**Comment by dchassin** [comment]
Thanks. In the meantime, I'll check into how the system build was done because it's possible that Time Machine recovery of my data included the Downloads folder, which could easily explain how an older version snuck in there.

**Comment by dchassin** [comment]
Following up for the record. The problem originated with a cherry-picked Time-machine restore of data after installing Big Sur. The restore copied an old version of GitHub Desktop in my downloads folder. After downloading and installing the newer version, the problem went away.

**Comment by sergiou87** [comment]
Thanks for the follow up! Never considered that possibility 🤯
