### ISSUE TITLE
Incorrect warning for incorrect Git config email address with multiple Github account emails

### ISSUE THREAD

**Issue by jimlevett** [desktop/desktop#12402]
### Describe the bug

In a recent update, Github Desktop is warning me, with a triangular ! warning sign to the left of the "Summary" box, that "This commit will be misattributed", as according to the message, my email address in my global Git config does not match my Github account.

However, in my Github account I have two emails listed in https://github.com/settings/emails. The second one listed, and also marked as primary, is the one I am being warned does not match.

Furthermore, the dropdown box contains no entries to update to.

![image](https://user-images.githubusercontent.com/2193298/121160809-525ba080-c844-11eb-8fb1-7df7c7576eff.png)
![image](https://user-images.githubusercontent.com/2193298/121161074-8afb7a00-c844-11eb-93ca-4d93dd660c9d.png)

### Version & OS

Github Desktop version: Version 2.8.3 (x64)
OS: MacOS Catalina 10.15.7

**Comment by sergiou87** [comment]
Hello @jimlevett! 👋 

Does it help if you close and reopen the app, or if you sign out and in again? The problem seems to be the app didn't pick your email addresses, which is certainly weird 🤔

**Comment by jimlevett** [comment]
Hi @sergiou87 closing and restarting the app seems to have cleared it!
Perhaps as a seasoned dev I should have done that already, hopefully the bug report may have served of some useful insight.

**Comment by sergiou87** [comment]
Happy to hear that! Thank you for confirming it works, sounds like it was a one-off request failure or something 😌  And you shouldn't see that happening again 🤞
