### ISSUE TITLE
Code highlighting should be optional

### ISSUE THREAD

**Issue by kuehn-sba** [desktop/desktop#12417]
### Describe the feature or problem you’d like to solve

Users should be able to turn off things like code highlighting (which only confuse). 
And this option should only apply to the color scheme of the code/language, **not** the green additions / red deletions highlights.

### Proposed solution

a flag/checkbox in the settings would be suitable for it

**Comment by steveward** [comment]
Thanks for the issue @kuehn-sba. Is there a specific issue you have with the syntax highlighting in GitHub Desktop? Can you share some details about what is confusing? This is not something we've heard feedback about before (outside of incorrect syntax highlighting).

**Comment by kuehn-sba** [comment]
I would like to completely deactivate the code highlighting, because it doesn't correspond to the IDE anyway and on the other hand I'm only interested in the changes marked in color (green / red). In my eyes, red code highlighting for JS is very confusing to distinguish between the actual changes.

if i see that correctly, it's just a class of css style ..

**Comment by kuehn-sba** [comment]
for example:
![Bildschirmfoto 2021-06-09 um 21 29 39](https://user-images.githubusercontent.com/8360913/121417119-d8bdd280-c969-11eb-9046-8b91e5afe1bf.png)

**Comment by steveward** [comment]
Thanks for the update. At this time we have no plans to disable syntax highlighting, but if this is something we continue to hear feedback for we can investigate it again in the future. I'm going to close this out to help keep our open issues manageable, but we will continue to gather feedback about this request within this issue.
