### ISSUE TITLE
Use of own CSS styles or theme files

### ISSUE THREAD

**Issue by kuehn-sba** [desktop/desktop#12418]
### Describe the feature or problem you’d like to solve

It would be awesome to adjust the color, style of the GUI by users. I feel that the pure division into dark / light is too limited.

And if a whole user theme like that is too complicated, it would be good to be able to set the **font, font style and font size for the syntax preview**.

### Proposed solution

Specifying a user-defined CSS file, which overwrites existing styles.

**Comment by steveward** [comment]
Thanks for the feedback @kuehn-sba. This was previously discussed in https://github.com/desktop/desktop/issues/2609, and at this time adding the ability to implement custom themes is still not something that is not on our priority list. In the future custom themes may be something we consider if we continue to hear feedback requesting it. I'm going to close this out.
