### ISSUE TITLE
Smooth Scrolling

### ISSUE THREAD

**Issue by kuehn-sba** [desktop/desktop#12428]
### Describe the feature or problem you’d like to solve

Is there a way to improve the scrolling of the content view? In contrast to the old "Github Desktop Classic", the scrolling with scrollbar or mousewheel is jerky  - by no means smooth, which quickly becomes exhausting when searching through it quickly.

**Comment by steveward** [comment]
Thanks for the issue @kuehn-sba. We had reports of diff scrolling problems that we were tracking in https://github.com/desktop/desktop/issues/1380, but most users have reported it as being resolved. Could you take a look at that issue and see if it seems similar to what you are experiencing?

**Comment by kuehn-sba** [comment]
no, in principle it works, it's just not that fluid, possibly caused by the (possibly a bit overloaded) html / css structure (attributes, tags)  underneath. maybe there is room for improvement.

**Comment by steveward** [comment]
@kuehn-sba [this comment](https://github.com/desktop/desktop/issues/1380#issuecomment-819578493) seems to align with what you are mentioning:

>here's a few visual glitches, like it can't seem to render the diff fast enough to not display a blank area in the scroll direction for a frame or two if I scroll past the loaded section,

I can also reproduce what I believe is the behavior you described when scrolling fast. Unfortunately to make improvements in this area we'd likely need to look into using something other than CodeMirror. I'm going to close this out to keep our issue tracker manageable but if we continue to hear feedback about this it may be something we look into in the future.
