### ISSUE TITLE
auto commit name

### ISSUE THREAD

**Issue by LeGitHubDeTai** [desktop/desktop#12424]
### Describe the feature or problem you’d like to solve

add an option to put a default commit name.

**Comment by steveward** [comment]
Thanks for the issue @LeGitHubDeTai. I'm not sure I understand your request -- are you possibly wanting GitHub Desktop to support commit templates? We are tracking that in https://github.com/desktop/desktop/issues/8698. If you can share further details that would be helpful.

**Comment by LeGitHubDeTai** [comment]
![image](https://user-images.githubusercontent.com/65470169/121585777-4255e380-ca33-11eb-91ff-547740d151a3.png)
add an option to put the commit names automatically.

the goal is to be faster for push, but instead of having "Update <filename>" have a custom text here is "🖋 Update"

**Comment by LeGitHubDeTai** [comment]
![image](https://user-images.githubusercontent.com/65470169/121586259-bee8c200-ca33-11eb-8268-256122abc50b.png)

**Comment by steveward** [comment]
Thanks, since this aligns with commit templates I am going to close this out. Please follow along in #8698 for updates.
