### ISSUE TITLE
Error when start GitHub Desktop

### ISSUE THREAD

**Issue by martinsluka** [desktop/desktop#12436]
### Describe the bug

When GitHUb Desktop starter first of all there is a window with error message. 

dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Applications/GitHub Desktop.app/Contents/Resources/app/git/libexec/git-core/git-lfs
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Applications/GitHub Desktop.app/Contents/Resources/app/git/libexec/git-core/git-lfs
  Expected in: /usr/lib/libSystem.B.dylib

SIGTRAP: trace trap
PC=0x7fff62343075 m=4 sigcode=1

goroutine 0 [idle]:
runtime.walltime1(0x0, 0xc000000000)
	hostedtoolcache/go/1.16.3/x64/src/runtime/sys_darwin.go:270 +0x4a fp=0xc000139db0 sp=0xc000139d78 pc=0x4057e4a
runtime.walltime(...)
	hostedtoolcache/go/1.16.3/x64/src/runtime/time_nofake.go:23
time.now(0x45a4c60, 0x4602f01, 0xc000032030)
	hostedtoolcache/go/1.16.3/x64/src/runtime/timestub.go:16 +0x25 fp=0xc000139de0 sp=0xc000139db0 pc=0x406b3a5
time.Now(0x45a4c60, 0xc000032030, 0x0)
	hostedtoolcache/go/1.16.3/x64/src/time/time.go:1067 +0x26 fp=0xc000139e08 sp=0xc000139de0 pc=0x40c8266
github.com/git-lfs/git-lfs/config.NewIn(0x0, 0x0, 0x0, 0x0, 0x4628165)
	work/dugite-native/dugite-native/git-lfs/config/config.go:69 +0xe5 fp=0xc000139e88 sp=0xc000139e08 pc=0x41aa325
github.com/git-lfs/git-lfs/config.New(...)
	work/dugite-native/dugite-native/git-lfs/config/config.go:61
github.com/git-lfs/git-lfs/commands.Run(0x10)
	work/dugite-native/dugite-native/git-lfs/commands/run.go:97 +0x265 fp=0xc000139f20 sp=0xc000139e88 pc=0x4514445
main.main()
	work/dugite-native/dugite-native/git-lfs/git-lfs.go:33 +0xec fp=0xc000139f88 sp=0xc000139f20 pc=0x4520eac
runtime.main()
	hostedtoolcache/go/1.16.3/x64/src/runtime/proc.go:225 +0x256 fp=0xc000139fe0 sp=0xc000139f88 pc=0x403a556
runtime.goexit()
	hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000139fe8 sp=0xc000139fe0 pc=0x406e101

goroutine 1 [running]:
runtime.asmcgocall(0x406f8e0, 0xc000139d90)
	hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:652 +0x42 fp=0xc000139d48 sp=0xc000139d40 pc=0x406dd62
runtime.libcCall(0x406f8e0, 0xc000139d90, 0x10)
	hostedtoolcache/go/1.16.3/x64/src/runtime/sys_libc.go:48 +0x6c fp=0xc000139d78 sp=0xc000139d48 pc=0x405848c
runtime.walltime1(0x0, 0xc000000000)
	hostedtoolcache/go/1.16.3/x64/src/runtime/sys_darwin.go:270 +0x4a fp=0xc000139db0 sp=0xc000139d78 pc=0x4057e4a
runtime.walltime(...)
	hostedtoolcache/go/1.16.3/x64/src/runtime/time_nofake.go:23
time.now(0x45a4c60, 0x4602f01, 0xc000032030)
	hostedtoolcache/go/1.16.3/x64/src/runtime/timestub.go:16 +0x25 fp=0xc000139de0 sp=0xc000139db0 pc=0x406b3a5
time.Now(0x45a4c60, 0xc000032030, 0x0)
	hostedtoolcache/go/1.16.3/x64/src/time/time.go:1067 +0x26 fp=0xc000139e08 sp=0xc000139de0 pc=0x40c8266
github.com/git-lfs/git-lfs/config.NewIn(0x0, 0x0, 0x0, 0x0, 0x4628165)
	work/dugite-native/dugite-native/git-lfs/config/config.go:69 +0xe5 fp=0xc000139e88 sp=0xc000139e08 pc=0x41aa325
github.com/git-lfs/git-lfs/config.New(...)
	work/dugite-native/dugite-native/git-lfs/config/config.go:61
github.com/git-lfs/git-lfs/commands.Run(0x10)
	work/dugite-native/dugite-native/git-lfs/commands/run.go:97 +0x265 fp=0xc000139f20 sp=0xc000139e88 pc=0x4514445
main.main()
	work/dugite-native/dugite-native/git-lfs/git-lfs.go:33 +0xec fp=0xc000139f88 sp=0xc000139f20 pc=0x4520eac
runtime.main()
	hostedtoolcache/go/1.16.3/x64/src/runtime/proc.go:225 +0x256 fp=0xc000139fe0 sp=0xc000139f88 pc=0x403a556
runtime.goexit()
	hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000139fe8 sp=0xc000139fe0 pc=0x406e101

goroutine 5 [runnable]:
os/signal.loop()
	hostedtoolcache/go/1.16.3/x64/src/os/signal/signal_unix.go:21
created by os/signal.Notify.func1.1
	hostedtoolcache/go/1.16.3/x64/src/os/signal/signal.go:151 +0x45

goroutine 6 [runnable]:
main.main.func1(0xc000080240, 0xc000030060)
	work/dugite-native/dugite-native/git-lfs/git-lfs.go:19
created by main.main
	work/dugite-native/dugite-native/git-lfs/git-lfs.go:19 +0xe7

rax    0x7fff6237c290
rbx    0x4c071b0
rcx    0x0
rdx    0x0
rdi    0x7fff6237c400
rsi    0x0
rbp    0x700000186c50
rsp    0x700000186c38
r8     0x7fff6236504c
r9     0xffff8000
r10    0x700000186a3a
r11    0x7fff6237c400
r12    0x1
r13    0x1
r14    0x7fff6237c400
r15    0xffffffffffffffff
rip    0x7fff62343075
rflags 0x246
cs     0x2b
fs     0x0
gs     0x0

### Version & OS

Version 2.8.3 (x64) MacOSX 10.11.6

### Steps to reproduce the behavior

Start GitHub Desktop

### Expected behavior

No error Message

### Actual behavior

GitHub Desktop works as normaly when Error message window is closed.

### Screenshots

![Snímek obrazovky 2021-06-13 v 16 57 56](https://user-images.githubusercontent.com/7187070/121812563-9269bb80-cc68-11eb-9652-9f81ecd16bd6.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
[2021-06-13.desktop.production.log](https://github.com/desktop/desktop/files/6644112/2021-06-13.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the issue @martinsluka. Here's the specific error I'm seeing:

```
2021-06-13T14:52:30.136Z - error: [ui] `git lfs install --skip-repo` exited with an unexpected code: 2.
stderr:
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Applications/GitHub Desktop.app/Contents/Resources/app/git/libexec/git-core/git-lfs
  Expected in: /usr/lib/libSystem.B.dylib
```

It looks like you are running macOS El Capitan, which does not include `clock_gettime`. There have been some reports that installing the XCode command line tools may resolve this. If you'd like to try that you can run this command:

`xcode-select --install`

If that does not get things working then unfortunately you will need to update to a more recent version of macOS in order to get GitHub Desktop working. I'm sorry that I don't have better news.

**Comment by martinsluka** [comment]
Thank you

Martin

Odesláno z iPhonu

15. 6. 2021 v 19:36, Steve Ward ***@***.***>:

**Comment by amark** [comment]
@steveward @martinsluka 

This is really sad to hear, I have the exact same OS version & got same error. (below)

I already have (it says) `xcode-select --install` on my machine.

Is it safe to use GitHub Desktop and just ignore this error?

The previous version of GitHub Desktop worked just fine.

Should I revert back to `release-2.8.1`? Any others?

Error:

```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Applications/GitHub Desktop.app/Contents/Resources/app/git/libexec/git-core/git-lfs
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Applications/GitHub Desktop.app/Contents/Resources/app/git/libexec/git-core/git-lfs
  Expected in: /usr/lib/libSystem.B.dylib

SIGTRAP: trace trap
PC=0x7fff6dd52075 m=5 sigcode=1

goroutine 0 [idle]:
runtime.walltime1(0x0, 0xc000000000)
	hostedtoolcache/go/1.16.3/x64/src/runtime/sys_darwin.go:270 +0x4a fp=0xc0001c1db0 sp=0xc0001c1d78 pc=0x4057e4a
runtime.walltime(...)
	hostedtoolcache/go/1.16.3/x64/src/runtime/time_nofake.go:23
time.now(0x45a4c60, 0x4602f01, 0xc00005a020)
	hostedtoolcache/go/1.16.3/x64/src/runtime/timestub.go:16 +0x25 fp=0xc0001c1de0 sp=0xc0001c1db0 pc=0x406b3a5
time.Now(0x45a4c60, 0xc00005a020, 0x0)
	hostedtoolcache/go/1.16.3/x64/src/time/time.go:1067 +0x26 fp=0xc0001c1e08 sp=0xc0001c1de0 pc=0x40c8266
github.com/git-lfs/git-lfs/config.NewIn(0x0, 0x0, 0x0, 0x0, 0x4628165)
	work/dugite-native/dugite-native/git-lfs/config/config.go:69 +0xe5 fp=0xc0001c1e88 sp=0xc0001c1e08 pc=0x41aa325
github.com/git-lfs/git-lfs/config.New(...)
	work/dugite-native/dugite-native/git-lfs/config/config.go:61
github.com/git-lfs/git-lfs/commands.Run(0x10)
	work/dugite-native/dugite-native/git-lfs/commands/run.go:97 +0x265 fp=0xc0001c1f20 sp=0xc0001c1e88 pc=0x4514445
main.main()
	work/dugite-native/dugite-native/git-lfs/git-lfs.go:33 +0xec fp=0xc0001c1f88 sp=0xc0001c1f20 pc=0x4520eac
runtime.main()
	hostedtoolcache/go/1.16.3/x64/src/runtime/proc.go:225 +0x256 fp=0xc0001c1fe0 sp=0xc0001c1f88 pc=0x403a556
runtime.goexit()
	hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0001c1fe8 sp=0xc0001c1fe0 pc=0x406e101

goroutine 1 [running]:
runtime.asmcgocall(0x406f8e0, 0xc0001c1d90)
	hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:652 +0x42 fp=0xc0001c1d48 sp=0xc0001c1d40 pc=0x406dd62
runtime.libcCall(0x406f8e0, 0xc0001c1d90, 0x10)
	hostedtoolcache/go/1.16.3/x64/src/runtime/sys_libc.go:48 +0x6c fp=0xc0001c1d78 sp=0xc0001c1d48 pc=0x405848c
runtime.walltime1(0x0, 0xc000000000)
	hostedtoolcache/go/1.16.3/x64/src/runtime/sys_darwin.go:270 +0x4a fp=0xc0001c1db0 sp=0xc0001c1d78 pc=0x4057e4a
runtime.walltime(...)
	hostedtoolcache/go/1.16.3/x64/src/runtime/time_nofake.go:23
time.now(0x45a4c60, 0x4602f01, 0xc00005a020)
	hostedtoolcache/go/1.16.3/x64/src/runtime/timestub.go:16 +0x25 fp=0xc0001c1de0 sp=0xc0001c1db0 pc=0x406b3a5
time.Now(0x45a4c60, 0xc00005a020, 0x0)
	hostedtoolcache/go/1.16.3/x64/src/time/time.go:1067 +0x26 fp=0xc0001c1e08 sp=0xc0001c1de0 pc=0x40c8266
github.com/git-lfs/git-lfs/config.NewIn(0x0, 0x0, 0x0, 0x0, 0x4628165)
	work/dugite-native/dugite-native/git-lfs/config/config.go:69 +0xe5 fp=0xc0001c1e88 sp=0xc0001c1e08 pc=0x41aa325
github.com/git-lfs/git-lfs/config.New(...)
	work/dugite-native/dugite-native/git-lfs/config/config.go:61
github.com/git-lfs/git-lfs/commands.Run(0x10)
	work/dugite-native/dugite-native/git-lfs/commands/run.go:97 +0x265 fp=0xc0001c1f20 sp=0xc0001c1e88 pc=0x4514445
main.main()
	work/dugite-native/dugite-native/git-lfs/git-lfs.go:33 +0xec fp=0xc0001c1f88 sp=0xc0001c1f20 pc=0x4520eac
runtime.main()
	hostedtoolcache/go/1.16.3/x64/src/runtime/proc.go:225 +0x256 fp=0xc0001c1fe0 sp=0xc0001c1f88 pc=0x403a556
runtime.goexit()
	hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0001c1fe8 sp=0xc0001c1fe0 pc=0x406e101

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	hostedtoolcache/go/1.16.3/x64/src/runtime/sigqueue.go:165 +0x9d
os/signal.loop()
	hostedtoolcache/go/1.16.3/x64/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	hostedtoolcache/go/1.16.3/x64/src/os/signal/signal.go:151 +0x45

goroutine 6 [chan receive]:
main.main.func1(0xc00008e240, 0xc00002c080)
	work/dugite-native/dugite-native/git-lfs/git-lfs.go:21 +0x65
created by main.main
	work/dugite-native/dugite-native/git-lfs/git-lfs.go:19 +0xe7

rax    0x7fff6dd8b290
rbx    0x4d03f90
rcx    0x0
rdx    0x0
rdi    0x7fff6dd8b400
rsi    0x0
rbp    0x700000209990
rsp    0x700000209978
r8     0x7fff6dd7404c
r9     0xffffe000
r10    0x70000020977a
r11    0x7fff6dd8b400
r12    0x1
r13    0x1
r14    0x7fff6dd8b400
r15    0xffffffffffffffff
rip    0x7fff6dd52075
rflags 0x246
cs     0x2b
fs     0x0
gs     0x0
```

**Comment by amark** [comment]
:( :( :( the "release" isn't a working Application. How do I download an old version of GitHub Desktop? Please! @steveward

**Comment by martinsluka** [comment]
Read previous posts, please. 

Martin

Odesláno z iPhonu

25. 7. 2021 v 2:52, Mark Nadal ***@***.***>:

**Comment by martinsluka** [comment]
From Steve Ward:

It looks like you are running macOS El Capitan, which does not include clock_gettime. There have been some reports that installing the XCode command line tools may resolve this. If you'd like to try that you can run this command:

xcode-select --install

If that does not get things working then unfortunately you will need to update to a more recent version of macOS in order to get GitHub Desktop working. I'm sorry that I don't have better news.


Martin
