### ISSUE TITLE
Allow multiple instances of Github Desktop

### ISSUE THREAD

**Issue by NeonWizard** [desktop/desktop#12433]
### Describe the feature or problem you’d like to solve

I would like to be able to open multiple instances of Github Desktop. This means multiple windows, with each being able to select their own repository and perform their own isolated functions independent of each other.

### Proposed solution

My specific use case is that I have several virtual desktops in Windows 10, such as one each for Personal, School, and Remote Work. However, since only one instance of Github Desktop can be open, I have to drag that window between each virtual desktop whenever I want to use it. If I could use multiple instances, I'd be able to have one for each virtual desktop with a different repository selected in each.

### Additional context

![image](https://user-images.githubusercontent.com/1355586/121749449-ec7f4b00-cac7-11eb-84e9-6c0dfd47838d.png)
Windows 10 virtual desktops

**Comment by steveward** [comment]
Thanks for the issue @NeonWizard. We're tracking this in https://github.com/desktop/desktop/issues/3606 so I am going to close this out and add your feedback there.

**Comment by Viznity** [comment]
+1

**Comment by AnanthSB** [comment]
Is this PR resolved the issue, can we use more than one github desktop now in windows pc.
