### ISSUE TITLE
Can't login in github desktop

### ISSUE THREAD

**Issue by pratiksharma7774** [desktop/desktop#12434]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by sergiou87** [comment]
Hello 👋 !

Can you provide more details about your issue? Filling the template would be very useful 😄 Thank you!
