### ISSUE TITLE
GitHub Desktop won't install on Windows 10 Pro

### ISSUE THREAD

**Issue by zk-sn** [desktop/desktop#12448]
### Describe the bug

Can't install GitHub Desktop for Windows
I downloaded both the .exe and .msi versions of GitHub Desktop.
Running either one I see a very brief "installing" box on taskbar but it vanishes within a second and nothing is installed.
Tried running both as administrator, same problem.

Troubleshooting:
Reading some other issues I attempted some of the troubleshooting steps recommended

- Disabled antivirus (Windows defender antivirus)
- Restarted computer
- Cleared out C:\Users\<user>\AppData\Local\SquirrelTemp (there were 2 files in there about a month old)
- Checked folder C:\Users\<user>\AppData\Local\GitHubDesktop - folder does not exist
- Opened elevated command prompt and ran sfc /scannow - no problems found
- Ran .NET repair utility from http://www.microsoft.com/en-us/download/details.aspx?id=30135 - no problems found
- Checked windows event log:  I can see 4 entries in Application log every time I run the MSI installer, but they seem to think it installed successfully

1. Beginning a Windows Installer transaction: C:\Users\Zach\Downloads\GitHubDesktopSetup-x64.msi. Client Process Id: 2932.
2. Ending a Windows Installer transaction: C:\Users\Zach\Downloads\GitHubDesktopSetup-x64.msi. Client Process Id: 2932.
3. Product: GitHub Desktop Deployment Tool -- Configuration completed successfully.
4. Windows Installer reconfigured the product. Product Name: GitHub Desktop Deployment Tool. Product Version: 2.8.3.0. Product Language: 1033. Manufacturer: GitHub, Inc.. Reconfiguration success or error status: 0.

- Checked program files directory - c:\Program Files (x86) has a subdirectory GitHub Desktop Deployment that contains one file, GitHubDesktopDeploymentTool.exe.  Running that file brings up a brief "Installing" on task bar and then nothing.

### Version & OS
Windows 10 Pro
OS Build 19042.985
Windows Feature Experience Pack 120.2212.2020.0

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

Download GitHub Desktop MSI or EXE
Run either
See nothing happen

### Expected behavior

GitHub should install

### Actual behavior

Nothing

### Screenshots
n/a

### Logs
n/a

### Additional context
n/a

**Comment by steveward** [comment]
Thanks for the report @zk-sn. To get some more information about why the installation is failing it would be helpful if you could send over the log file that the Squirrel installer generates.

You should be able to find the log file here:

`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`

If no log file is being generated there you should be able to find one in the `SquirrelTemp` directory:

`%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

Please upload that as an attachment.

**Comment by zk-sn** [comment]
I do not have a directory %LocalAppData%\GitHubDesktop

%LocalAppData%\SquirrelTemp only has one file, Update.exe.  I'd previously deleted everything in that directory but Update.exe is recreated when I run the .exe installer, GitHubDesktopSetup-x64.exe.

**Comment by steveward** [comment]
@zk-sn apologies for not following up. Are you still having issues installing GitHub Desktop? Have you run into issues installing any other Electron applications on your machine?
