### ISSUE TITLE
macOS 12.0 Monterey: Desktop hangs when device wakes from sleep

### ISSUE THREAD

**Issue by devgregw** [desktop/desktop#12458]
### Describe the bug

When the device wakes from sleep, GitHub Desktop will sometimes (as will other Electron apps) hang indefinitely and use up a lot of CPU while ramping up fans.

### Version & OS

GitHub Desktop 2.8.3 (x64) and macOS 12.0 beta 1 (21A5248p) on a MacBook Pro (16-inch, 2019)

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. Close the window, but keep the app running in the background (don't quit the app)
3. Put the device to sleep
4. Wake it up
5. Check the status of the GH Desktop process in Activity Monitor - it should show "not responding"

In my experience, this issue doesn't occur every time.

### Expected behavior

The process should resume normally when the device wakes up

### Actual behavior

The GitHub Desktop process stops responding and starts to use a lot of CPU, which ramps up the fans

### Screenshots

![Screenshot on 6-15-21 at 5 32 27 PM](https://user-images.githubusercontent.com/3732383/122133430-46eb1500-ce02-11eb-82d8-c26b53225b96.png)

### Logs

Here is the log generated by macOS when force quitting Desktop: [github.txt](https://github.com/desktop/desktop/files/6659147/github.txt)

### Additional context

I've noticed this issue with Microsoft Teams and Bitwarden, which I believe are also Electron apps.  They usually all stop working together.

**Comment by devgregw** [comment]
[Found a similar issue for Bitwarden](bitwarden/clients#2605), one of the other apps I'm having problems with.

**Comment by sergiou87** [comment]
Thanks for your report, @devgregw!! I haven't seen anything reported in the [Electron repo](https://github.com/electron/electron/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc), so we'll have to keep an eye.

I've labelled this as `priority-1`, not because of its current state, but because of what it can become as more users start upgrading to Monterey.

**Comment by Tharolzakariya** [comment]
Zakku143

**Comment by steveward** [comment]
I'm going to close this out as stale. If this is still an issue please let us know and we can reopen and investigate further.
