### ISSUE TITLE
deleted repository 

### ISSUE THREAD

**Issue by Passion2Learn** [desktop/desktop#12462]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by sergiou87** [comment]
Deleted… where? 😄 

Would you mind filling out the template with more details so we can help you? Thank you!! ❤️
