### ISSUE TITLE
Search History Commit 

### ISSUE THREAD

**Issue by Mudassarali222** [desktop/desktop#12468]
### Describe the feature or problem you’d like to solve
We want an search input field in history tab where we can search our old commits fastly. 
### Proposed solution
It will help to see old commits easily without scrolling tons of History commits.
### Additional context
![Screenshot_1](https://user-images.githubusercontent.com/75826150/122333879-3c3f9580-cf52-11eb-8a8b-b46ba148c838.png)

**Comment by JosephTLyons** [comment]
Sounds a bit like https://github.com/desktop/desktop/issues/7022

**Comment by tidy-dev** [comment]
Yep. @JosephTLyons  You are right - this feels like a duplicate or inline with #7022 so I am closing it in favor of that one.
