### ISSUE TITLE
[Feature] Divide/split a large commit, or cherry-pick only certain changes in a large commit

### ISSUE THREAD

**Issue by adrianspacely** [desktop/desktop#12461]
### Describe the feature or problem you’d like to solve

Today I needed to cherry-pick changes from a large commit. I needed everything but the database changes. I needed to work out how to pick only the changes I needed from the commit.

### Proposed solution

I wish I could have done either of the following:

* Cherry-picked certain changes in a commit.
* Divided/split/broke-apart the commit and force pushed. Then I'd be able to cherry-pick what I needed.

Either of those solutions to the problem would have benefited my situation. It would benefit users by making cherry picking easier for sloppy commit histories.

**Comment by tidy-dev** [comment]
The typical git way of achieving this is to do a cherry-pick with the no-commit flag (not currently supported in GitHub Desktop). This works by bringing over the changes from the cherry-picked commit into your working directory and then you have the option to only stage the changes you want and discard the others before committing it.

In GitHub Desktop, a flow I have used for this purpose is to cherry-pick the commit that has the changes I want, then, undo the cherry-picked commit. This puts you in the same state as a no-commit flag option allowing you to discard any changes you don't want and recommit.

The undo option is right below your commit summary or in the history context menu and is only available unpushed commits. Also, with the 2.9.0 release, you can amend your last commit from history context menu which is another way you could modify the cherry-picked commit (but likely better if you wanted to add something to it as opposed to remove).

**Comment by billygriffin** [comment]
Thanks @tidy-dev for sharing your workflow for this, and thanks for sharing what you're hoping to do @adrianb93! Since this is a relatively niche workflow overall and there are ways to achieve it without being supported out of the box, I'm going to close this issue as something we don't plan to support unless we see a lot more people who will likely benefit from it. Thanks again y'all.

**Comment by okorohelijah** [comment]
Hello please is there a way of splitting pull requests using github desktop?

**Comment by Ocean-Odyssey** [comment]
Github GUI is terrible for this, its why I find perforce so much easier to use.
