### ISSUE TITLE
[Feature] Pushing to GitLab prompts a link to create or view a MR

### ISSUE THREAD

**Issue by adrianspacely** [desktop/desktop#12460]
### Describe the feature or problem you’d like to solve

As much as I prefer and love GitHub, for work we have to use GitLab. I wish there was a link to view or create a merge request in GitLab after pushing.

### Proposed solution

Can GitHub Desktop show that link on the splash page after pushing?

### Additional context

When I push in the terminal, there's a message with a link to view or create a merge/pull request. Maybe there is also a way to generate it too?

**Comment by sergiou87** [comment]
Hello! 👋 

Thank you for your suggestion! Unfortunately, aside from the generic `git` features, as of today we don't have plans to integrate GitHub Desktop with anything other than GitHub 😅
