### ISSUE TITLE
View Added tags for a Branch

### ISSUE THREAD

**Issue by vedansh-bold** [desktop/desktop#12471]
### Describe the feature or problem you’d like to solve

There should be a window to view all added tags in a particular branch.

### Proposed solution

If this is done , then we don't have to scroll down to find the last tag added and on which commit. This takes lot of time to scroll and search

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@vedansh-bold thanks for the issue. This is a duplicate of https://github.com/desktop/desktop/issues/9687. so I am going to close this out.
