### ISSUE TITLE
Desktop app update issue

### ISSUE THREAD

**Issue by priyank-namdev** [desktop/desktop#12475]
when I'm updating the desktop app the app shows downloading update and after some time the update paused.

**Comment by steveward** [comment]
Thanks for the report @PriyankNamdev21. To get some more information about why the update is failing it would be helpful if you could send over the log file that the Squirrel installer generates.

You should be able to find the log file here:

`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`

Please share that in this issue as an attachment.
