### ISSUE TITLE
Multi-select stage/un-stage files from commit.

### ISSUE THREAD

**Issue by WspDev** [desktop/desktop#12477]
### Describe the feature or problem you’d like to solve
Presently each file is staged/un-staged separately, or all files are staged/un-staged using the parent checkbox.
It would be great to be able to multi-select files and change their checkbox in one go.

### Proposed solution
Select multiple changed files.
Then click the checkbox of one of the selected files. If the checkbox is checked, un-check all selected, otherwise check all selected files.
Having an option on the right-click context menu would be great too.

**Comment by sergiou87** [comment]
Hello! 👋 

Thank you for your feedback 😄  Something about that was mentioned in: https://github.com/desktop/desktop/issues/11974#issuecomment-816688533

You can select multiple items using <kbd>Command</kbd> (macOS) or <kbd>Control</kbd> (Windows) or <kbd>Shift</kbd> (if you want consecutive items), and then press <kbd>Space</kbd> to select or deselect them all simultaneously. That is all standard OS behavior, so I hope it works for you! 😄

**Comment by WspDev** [comment]
Thanks @sergiou87!
I tried everything that I would have thought was usual behaviour and had no success. :D
