### ISSUE TITLE
Enterprise financial institutions

### ISSUE THREAD

**Issue by Huawei8** [desktop/desktop#12476]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by Huawei8** [comment]
Enterprise

**Comment by Huawei8** [comment]
Bye

**Comment by steveward** [comment]
@Huawei8 this issue tracker is for GitHub Desktop. Thanks!
