### ISSUE TITLE
Is there a way to view "Files Changed" tab on pull requests?

### ISSUE THREAD

**Issue by opqpop** [desktop/desktop#12470]
### Describe the feature or problem you’d like to solve

On github.com there's a very handy "Files Changed" tab to review all commits for a pull request. Is there a way to do this in github desktop? I tried selecting multiple diffs in a pull request but it says "Unable to display diff when multiple commits are selected".  

We love this feature of being able to quickly review all commits for a pull request without having to look at each one individually, but we also love github desktop's ability to do split diffs. 

### Proposed solution

Same as showing the files changed tab in github website. It's how our team reviews the bulk of PRs vs having to review each individual commit unless necessary. 

### Additional context

![image](https://user-images.githubusercontent.com/5566843/122357644-c5ca7580-cf08-11eb-8a95-8b1c9f6abb59.png)

![image](https://user-images.githubusercontent.com/5566843/122357690-cd8a1a00-cf08-11eb-8c12-07970f9befea.png)

**Comment by tidy-dev** [comment]
@opqpop Thanks you for the issue. This falls in line with our discussion on what a better PR experience would be in Desktop #11517. Thus I am going to close your issue in favor of tracking it there. This issue will now be linked but feel free to add to the discussion there.
