### ISSUE TITLE
Sublime Task not showing in editor list.

### ISSUE THREAD

**Issue by mamtagupta2008** [desktop/desktop#12498]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by sergiou87** [comment]
I just tested it on macOS and Windows and I can see Sublime Text in both 😅  @mamtagupta2008 would you mind filling the template and giving us more details so we can help you? Thank you! ❤️ 
![image](https://user-images.githubusercontent.com/1083228/123106317-d31bbe80-d438-11eb-88b5-bfb5c1d4b509.png)
![image](https://user-images.githubusercontent.com/1083228/123106341-d9aa3600-d438-11eb-8a93-d1e9734f6eef.png)
