### ISSUE TITLE
Redirected repos

### ISSUE THREAD

**Issue by ms609** [desktop/desktop#12494]
### Describe the bug

Renaming a repo to a repo that has previously been renamed causes repos to be merged

### Version & OS

Version 2.9.0 (x64)
Windows 10

### Steps to reproduce the behavior

1. Set up a repo called `foo` and a repo called `bar` on GitHub, and clone these to Desktop
2. On GitHub, rename `foo` to `foofoo` and rename `bar` to `foo`.
3. On GitHub Desktop, go to the `foo` repo, which will rename itself `foofoo`
4. On GitHub Desktop, go to the `bar` repo, which will rename itself `foo`, then immediately rename itself `foofoo`, and associate itself with the `foofoo` repository.

### Expected behavior

The renamed repos should remain independent

### Logs 

[2021-06-22.desktop.production.log](https://github.com/desktop/desktop/files/6697094/2021-06-22.desktop.production.log)

In the log, I renamed `Rogue` → `Rogue-ms`, and `Rogues` → `Rogue`.  I later renamed this repo `Roguey` on GitHub and re-checked it out into a new directory, copying changes across, but when I renamed it `Rogue` again, GitHub Desktop conflated it with the `Rogue-ms` repo.

**Comment by sergiou87** [comment]
Thanks for your report @ms609! ❤️ 

We knew about this issue but we thought #12308 fixed it 😞 

@tidy-dev is this a scenario you would expect to be fixed with your PR? 🤔

**Comment by tidy-dev** [comment]
:D The never ending bug... This is a whole new level/scenario.. before we were just investigating if you were simply trying to "archive" a repo by renaming it and start another with the same name, not trying to have 2 existing and switch repo names. But... this is the same issue.. When `foo` updates to `foofoo` it sets the cache for `foo` to `foofoo`; thus when `bar` updates to `foo` it then retrieves `foofoo`... I am sort of surprised that the no caching on that one updated call doesn't prevent this too.. but maybe a timing sort of thing in this case. I will look into this new scenario.

**Comment by ms609** [comment]
I wonder whether you could recommend any way for me to clear the cache and start afresh here?
Several renames later I'm now experiencing very odd behaviour in which the repo I'd originally called `Rogues` is not operating correctly.

Specifically, changed to files are not being recognized in GitHub Desktop, which thinks that files either  exhibit "no content changes found" or new files are empty.  I can add and commit these using the git command line, but not Desktop, which (reasonably) won't allow me to commit when files haven't changed.

![image](https://user-images.githubusercontent.com/1695515/124941930-16625980-e003-11eb-9f0a-0d19c1d59b8f.png)

Presumably fixing the original bug will mean that other users don't end up in this situation, but given that I am where I am, is there any way that I can carry on using this repo without dragging round this unusual behaviour or staring from scratch?

[2021-07-08.desktop.production.log](https://github.com/desktop/desktop/files/6785367/2021-07-08.desktop.production.log)

**Comment by tidy-dev** [comment]
@ms609  Sorry for not getting back to you sooner (been OOO). I am not sure if this will work. But, maybe worth a shot. 
1. Open developer tools. (View > Toggle Developer Tools) 
2. Navigate to the Application tab
3. On left hand menu, find 'Clear Storage'
4. Once on that screen, there is a button labeled 'Clear Site Data'. 
  _Note this clear site data has many checkboxes. If you don't want the hassle of loosing all your cached info. I would suspect "Cache storage" and "Local and session storage" to be the most likely culprits. You could start with them first. Close and Reopen and if still seeing issue add others in._

Once you clear the site data, close and restart GitHub Desktop.  If you clear everything, you will find that you must log back in as well as add back your repositories (you don't have to reclone, you can drag and drop the repository folders into the app or add them via the "Add Existing Repository" option).

I would really appreciate if you can let me know if it helps. 🙂

**Comment by ms609** [comment]
@tidy-dev Thanks for the suggestions; after a few restarts, I have found myself with a duplicate entry for each repo; one duplicate still displays the behaviour described above, whilst the other works normally. Clearing "Cache storage" and "Local and session storage" didn't change anything, but now I've got a workable setup I'm hesitant to start clearing more data.

**Comment by tidy-dev** [comment]
Alright.. after some investigation on this, it is not a caching problem.. but a Desktop design problem. We use the name of the repo to fetch them. If two repos are renamed in this way, we don't have a way of determining that from the Desktop client.. and will result in one correctly being renamed and the other see that a repo exists of it's name does not rename. 

Preemptively, what can be done currently:
1. Rename one of the repos on GitHub.com. Open desktop and let it rename itself and close desktop.
2. Then, go rename the 2nd repo. Open desktop. (assuming no caching interferes) it should detect the rename.

After the fact, if you get to where you have 2 repos with the same name:
1. Find the one that is incorrectly named (the files do not match the one with that name on GitHub.com). 
2. Go to the repository settings of that repo and update the remote to the correct name:
![image](https://user-images.githubusercontent.com/75402236/131688018-0253731a-475d-4f85-9b3a-4f6361783922.png)

**Comment by tidy-dev** [comment]
As we do not plan to change how Desktop is designed in this use case, I am going to close this issue.

**Comment by ms609** [comment]
Thanks!  These instructions has allowed me to untangle my repos and get back to good working order.
