### ISSUE TITLE
Allow expanding the commit editor into a full dialog

### ISSUE THREAD

**Issue by haykam821** [desktop/desktop#12491]
### Describe the feature or problem you’d like to solve

The default commit editor often gets cramped with trying to write a longer or more complex commit message.

### Proposed solution

Giving users the option to expand the commit editor into a full dialog would improve usability when writing longer commit messages and allow GitHub Desktop to provide the user with more tools that would be incommodious in the default commit editor.

**Comment by steveward** [comment]
Thanks for the feedback @haykam821. I'm going to add this to https://github.com/desktop/desktop/issues/1646 where we are tracking improvements to commit writing.
