### ISSUE TITLE
Adding current branch to the repository list

### ISSUE THREAD

**Issue by iRumba** [desktop/desktop#12500]
### Describe the feature or problem you’d like to solve

Please add current branch column to the repositories list

### Proposed solution

It is usefull when you work with submodules. It can be optional.

### Additional context

![image](https://user-images.githubusercontent.com/12796309/123194014-f776aa00-d4cf-11eb-8e46-06165bd1d7fa.png)

**Comment by sergiou87** [comment]
Hello! Thank you for your suggestion ❤️ 

This was already requested in #11995, so I'd recommend to subscribe to that issue if you want to get notified when we make progress on this 😄
