### ISSUE TITLE
smart diffs on XML files

### ISSUE THREAD

**Issue by el-schalo** [desktop/desktop#12505]
### Describe the feature or problem you’d like to solve
A long xml line shouldn't be recognized as complete NEW, when there is only a minor change like an attribute value etc.

### Proposed solution
A smarter diff would make quality checks in development and merge requests easier and safer.

### Additional context
![GitHubDesktopDiffXmlSyntaxHighlightMixup](https://user-images.githubusercontent.com/20655271/123265099-fb6bf180-d4fa-11eb-8a97-f5e2d69d06b0.png)

**Comment by steveward** [comment]
Thanks for the request @el-schalo. GitHub Desktop should mirror how Git displays the diff. At this time we don't have any plans to make specific customizations like what you requested. I also tested out a `.xml` file and didn't see the same behavior.

In this case it sounds like being able to use a third-party merge/diff tool that does a better job of handling XML would be beneficial. You can follow along in https://github.com/desktop/desktop/issues/9609 and https://github.com/desktop/desktop/issues/1765 for updates about the ability to use third-party merge/diff tools.
