### ISSUE TITLE
GitHub Desktop opens the wrong path for Windows Terminal

### ISSUE THREAD

**Issue by OverHash** [desktop/desktop#12503]
### Describe the bug
When attempting to launch Windows Terminal through GitHub Desktop via the keybind, GitHub Desktop will attempt to open a non-existent `wt.exe` file.
GitHub Desktop will try to open `C:\Users\USER\AppData\Local\Microsoft\WindowsApps\wt.exe`, but my WSL installation appears to be accessible via `C:\Users\USER\AppData\Local\Microsoft\WindowsApps\Microsoft.WindowsTerminal_8wekyb3d8bbwe\wt.exe`. Because the first path does not exist, I am unable to open Windows Terminal with GitHub Desktop.

### Version & OS
Windows 10 build `19042.1052` with GitHub Desktop `2.9.0`

### Steps to reproduce the behavior
1. Attempt to open a repository in Windows Terminal via `Repository > Open in Windows Terminal`
2. View logs, and see that GitHub Desktop attempted to run a non-existent terminal.

### Expected behavior
For GitHub Desktop to open Windows Terminal `cd`'d into my repository.

### Actual behavior
GitHub Desktop silently fails to open the terminal. I am only able to see the issue when I view the logs GitHub desktop produces, and see that it is attempting to run a non-existent file.

### Logs
The most relevant log is this one, displayed when I try to open Windows Terminal with GitHub Desktop:
```
2021-06-24T07:17:24.181Z - info: [ui] calling captureCommandOutput(where git)
2021-06-24T07:17:24.285Z - info: [ui] launching Windows Terminal at path: "C:\Users\USER\AppData\Local\Microsoft\WindowsApps\wt.exe"
```

**Comment by OverHash** [comment]
Looks like this was actually an issue with my computer having the Windows Terminal alias incorrect. To fix this, I simply had to open the Windows Settings for "App execution aliases" and re-toggle the Windows Terminal app, which appeared to have fixed the redirect.

**Comment by jizc** [comment]
Thanks for the tip! Re-toggle fixed it for me as well.
