### ISSUE TITLE
Don't attempt to fast forward branches if fetch was noop

### ISSUE THREAD

**Issue by niik** [desktop/desktop#1250]
Right now we always refresh the repository and attempt to fast forward branches after a fetch. Ideally we should be able to tell when running the fetch if it actually pulled in any changes and skip those steps if it didn't.

Should spare us a few redundant CPU cycles for background fetches.

**Comment by mmangipano** [comment]
up-for-grabs i want in

**Comment by billygriffin** [comment]
I'm going to close this since it hasn't seemed to surface organically. Definitely not opposed to reopening if we think it might add significant value.
