### ISSUE TITLE
Renamed files without changes

### ISSUE THREAD

**Issue by iRumba** [desktop/desktop#12501]
### Describe the bug
(Tested with not github repositories only)
When file renamed, changes view says: "The file was renamed but not changed".

### Version & OS

Windows 10

### Steps to reproduce the behavior

1. Checkuot clean branch (without changes)
2. Open any source file and change code
3. Rename source file
4. In repo folder exeute git add -A
5. Choose this repo in Github Desktop

### Expected behavior

I see that file was renamed
Also, when I change it in changes list I see code changes.

### Actual behavior

In changes view I see "The file was renamed but not changed"

### Screenshots

![image](https://user-images.githubusercontent.com/12796309/123205854-d1a7d000-d4e4-11eb-9855-97a75fcffefb.png)

But after commit changes exists

![image](https://user-images.githubusercontent.com/12796309/123206327-b1c4dc00-d4e5-11eb-843e-51475402eabe.png)

### Logs

without logs, because same behavior is in Git (git diff file)

### Additional context

What can you do with it?

**Comment by sergiou87** [comment]
Thank you for your report! ❤️ 

This issue was already reported in #6014 so I recommend you to subscribe to that issue to get notified when we make progress on it!
