### ISSUE TITLE
When pushing a branch, focusing on another window pauses the push.

### ISSUE THREAD

**Issue by oguzyildizz** [desktop/desktop#12508]
### Describe the bug

When I'm pushing some commits to remote, and switch to another app while it's in progress, it's not pushing anymore. It waits for me to focus on github desktop again to finalize the pushing.

### Version & OS

It's been happening for at least more than a year.

### Steps to reproduce the behavior

1. Push some commits to remote
2. Switch to Chrome, go to Github to wait for the green "Create a Pull Request" button that appears when you push a new branch -> it won't happen
3. Focus back to github desktop, see that it resumes the push, and then after half a second, the button becomes "Fetch origin"
4. Now go back to Chrome, see that the branch is now pushed.

### Expected behavior

Once I push, it should finalize the push even if I focus to another window.

### Actual behavior

It pauses the push until I get back to Github Desktop.

**Comment by sergiou87** [comment]
Thanks for your report @oguzyildiz1991! ❤️ 

I just tried this and it all works as expected. Could you specify which app version and OS are you using?

In theory there is no reason for the app to behave like that: once that `git push` is triggered, the commits should be pushed regardless of whether the app is in foreground or not 🤔
