### ISSUE TITLE
111

### ISSUE THREAD

**Issue by wsx154777** [desktop/desktop#12517]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by Mrlinkwii** [comment]
:wave:  can you fill out the template pls :slightly_smiling_face:
