### ISSUE TITLE
ignore file not working

### ISSUE THREAD

**Issue by prateek-lodha** [desktop/desktop#12511]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by prateek-lodha** [comment]
When we right click on a file and choose 'ignore file', this feature is not working

**Comment by sergiou87** [comment]
@prateek-lodha could you provide more details?

Does that action not add the specified file to the `.gitignore` file?

**Comment by steveward** [comment]
@prateek-lodha if the file has been previously committed to your repository it needs to be removed in order to ignore it. You'll need to run this command from the command line:

`git rm --cached <file>`

You should then be able to ignore the file. Let us know if that is not the case!
