### ISSUE TITLE
 'https://github.com/import-io/robot-library.git/': Could not resolve host: github.com

### ISSUE THREAD

**Issue by anilprofecialinks** [desktop/desktop#12516]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by tidy-dev** [comment]
Hi @anilprofecialinks 

Could you fill the template and provide more info about the issue you're facing? Thank you!
