### ISSUE TITLE
> Our use case is:

### ISSUE THREAD

**Issue by techno494** [desktop/desktop#12514]
> Our use case is:
> 
>     * Developer works on some task by checking out a task branch from `dev`.
> 
>     * They are free to save commits on that task branch willy nilly with names like `save`, or `now builds`.
> 
>     * When they are finished, they check out `dev` branch, pull  and `git merge --squash` the temp task branch. This produces 1 clean commit per task.

I do this procedure with my personal projects.

_Originally posted by @JosephTLyons in https://github.com/desktop/desktop/issues/2507#issuecomment-833011168_

**Comment by JosephTLyons** [comment]
I was mentioned here - I'm not sure what this is, I think this feature was already added into the last Desktop release

**Comment by goyalyashpal** [comment]
i think @techno494 wanted to "quote reply" but ended up doing "reference in new issue"
