### ISSUE TITLE
Periodically fetch and refresh set to off having no effect

### ISSUE THREAD

**Issue by nckrtl** [desktop/desktop#12527]
### Describe the bug

In the advanced settings I have periodically fetch and refresh set to off. Yet Github Desktop still fetches origin periodically. Restarted the dekstop app and the issue remains.

### Version & OS

Version: 2.9 (arm64)
Mac OS: 11.4

### Steps to reproduce the behavior

1. Go to preferences menu
2. Click on advanced
3. Turn off 'Periodically fetch and refresh status of all repositories'
4. Wait a while and you'll see Fetch origin turn on automatically in the UI at the top

### Expected behavior

Fetch origin won't get triggered with 'Periodically fetch and refresh status of all repositories' turned off.

### Actual behavior

It still fetches the origin ever 5 min

### Screenshots

-

### Logs

-

### Additional context

-

**Comment by steveward** [comment]
@nckrtl thanks for the report. See https://github.com/desktop/desktop/issues/10687 -- the selected repository will still background fetch periodically. I'm going to close this out since we're tracking this in #10687.
