### ISSUE TITLE
Submodule browsing

### ISSUE THREAD

**Issue by flaviotordini** [desktop/desktop#12520]
### Describe the feature or problem you’d like to solve
Working with submodules is cumbersome. It could be made simpler by allowing the user to browse repository submodules and directly work with them without having to do "Add Local Repository..." for each one.

### Proposed solution
The Repository List should have submodules automatically listed under the parent repository.

**Comment by steveward** [comment]
Thanks for the feedback @flaviotordini. I'm going to add this to https://github.com/desktop/desktop/issues/7519 and close this out. See https://github.com/desktop/desktop/issues/7523 for our broader submodule tracking issue.
