### ISSUE TITLE
Git rebase no longer resumes (--continue) after commit and force push is missing

### ISSUE THREAD

**Issue by AndyGee** [desktop/desktop#12533]
### Describe the bug

2.8.3 used to continue a rebase after resolving conflicts and offer a force push at the end. This is no longer the case in 2.9.0

### Version & OS

Using 2.9.0 on Windows 10

### Steps to reproduce the behavior

1. Create branch1 off master make a change
2. Create branch2 off master make a conflicting change
3. Merge branch2 to master
4. Rebase branch1 over master
5. Resolve the conflict (Either in notepad++ or IntellijIDEA)
6. Repository is disconnected and the "git rebase --continue" is no longer performed
7. Switch to shell and execute "git rebase --continue"
8. Switch to Desktop, branch is reconnected
9. The option to git push --force is NOT offered - Operation of the "Fetch" action would actually destroy the rebase here!
10. Switch to shell and execute "git push --force"
11. Switch to Desktop and refresh

### Expected behavior

As previously working in 2.8.3, I would expect the rebase to continue and at the end of the process a force push to be offered.

### Actual behavior

The rebase does not proceed and the shell must be used to perform the --continue and --force operations to complete the rebase

### Screenshots

NA

### Logs

2021-06-29T08:08:34.444Z - info: [ui] [rebase] starting rebase for SEP-10214 at 670fec53180c74afdc13db7a488a74d03f25fa5c
2021-06-29T08:08:34.445Z - info: [ui] [rebase] to restore the previous state if this completed rebase is unsatisfactory:
2021-06-29T08:08:34.445Z - info: [ui] [rebase] - git checkout SEP-10214
2021-06-29T08:08:34.445Z - info: [ui] [rebase] - git reset 670fec53180c74afdc13db7a488a74d03f25fa5c --hard
2021-06-29T08:08:35.737Z - info: [ui] [rebase] completed rebase - got ConflictsEncountered and on tip 2a56045e7d87ef05870d5aa99205880b2f211b5c - kind Detached

### Additional context

I often use IntellijIDEA to resolve conflicts, switching between Desktop and IDEA until the rebase is complete. This used to be a seamless process in the 2.8.3 Desktop version, but seems to be broken in the 2.9.0 release.

Thank you for all your efforts on this great tool.

**Comment by tidy-dev** [comment]
@AndyGee Thank you for the report! Sorry for your frustration. However, we have been unable to reproduce this. Would you mind creating a video to give us a little more detailed repro steps?

**Comment by the21st** [comment]
+1 I'm also using IDEA for conflict resolution and the rebase flow stopped working for me in the past month with Github Desktop

**Comment by DaneEveritt** [comment]
I too can confirm this issue, rebasing and resolving conflicts inside of PhpStorm causes the GitHub app to just stop trying to guide you through the process. I've been getting around it by just using 'Continue Rebase' within PhpStorm's git tooling and then manually running `git push -f` at the end.

This also happens when resolving merge conflicts in PhpStorm and then returning to the GitHub app window, it does not suggest committing the changes, I have to run `git commit --continue` to get it to continue.

@tidy-dev happy to record a short video of this if the issue is re-opened?
