### ISSUE TITLE
showing current repo. but repo doesn't exists 

### ISSUE THREAD

**Issue by Yechieler** [desktop/desktop#12535]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by sergiou87** [comment]
Hi @Yechieler !! 👋 

Could you fill the template and provide more info about the issue you're facing? Thank you!
