### ISSUE TITLE
Co-author incorrectly being applied

### ISSUE THREAD

**Issue by tidy-dev** [desktop/desktop#12537]
### Describe the bug
From @cheshire137 ,

>I had set Enrique as co-author on another commit earlier on this branch, then I hit Undo on that commit and removed him as co-author. he no longer shows as co-author in the app:

>I ended up discarding changes from that commit once I hit 'Undo' on it, in addition to removing the co-author. I then made different changes and committed.

>guessing somehow Enrique persisted as co-author after undoing the commit he had been co-author on?

### Version & OS

Version 2.9.1-test1 (x64)

### Steps to reproduce the behavior

1. Undo a commit with a co-author
2. Remove co author
3. Make changes and commit 

### Expected behavior
No coauthor be applied

### Actual behavior
Coauthor from commit undone is applied.

**Comment by sogan66** [comment]
#12537
