### ISSUE TITLE
Increase the Git buffer size

### ISSUE THREAD

**Issue by Aragorn2009** [desktop/desktop#12539]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by sergiou87** [comment]
Hi @Aragorn2009! 👋 

Could you please fill out the template with details about your proposal?

Thank you! 😄
