### ISSUE TITLE
sanjnachoudhary100 - My Github Desktop is not signing using Github Desktop

### ISSUE THREAD

**Issue by sanjnachoudhary100** [desktop/desktop#12536]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by Mrlinkwii** [comment]
:wave:  can you fill in the template please :slightly_smiling_face:
