### ISSUE TITLE
RPC failed; curl 18 transfer closed with outstanding read data remaining send-pack: unexpected disconnect while reading sideband packet

### ISSUE THREAD

**Issue by SouhaibESS** [desktop/desktop#12569]
### Describe the bug

i'm getting this error while tryin to push to remote <git push -u origin master>

### Version & OS

windows 10

### Steps to reproduce the behavior
git push -u origin branch

### Actual behavior

Enumerating objects: 152, done.
Counting objects: 100% (152/152), done.
Delta compression using up to 8 threads
Compressing objects: 100% (149/149), done.
Writing objects: 100% (152/152), 7.97 MiB | 11.98 MiB/s, done.
Total 152 (delta 15), reused 0 (delta 0), pack-reused 0
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date

### Screenshots
![image](https://user-images.githubusercontent.com/62354824/124586859-e3776480-de4e-11eb-8fb9-902a72844476.png)

**Comment by steveward** [comment]
@SouhaibESS this issue tracker is for GitHub Desktop. For issues with using Git from the command line please contact [GitHub Support](https://support.github.com/).
