### ISSUE TITLE
Github Desktop does not honor the checkout/checkin settings of the Git Bash

### ISSUE THREAD

**Issue by brt-han-mai** [desktop/desktop#12563]
### Describe the bug

Github Desktop does not honor the checkout/checkin settings of the Git Bash.
I have a source with LF line ending but when checking out in Windows it is converted to CRLF which totally mess up with my Git Bash settings and causes confusion when working with VS Code

### Version & OS

Version 2.9.0 (x64)
Windows 10

### Steps to reproduce the behavior

1. Setup Git Bash ending line style as 'check out as is, check in as is'
2. Clone some source code using Github Desktop
3. Open source code with VS Code (from the button in the Github Desktop)
4. All the files are converted into CRLF (Windows style) which causes a lot of unwanted git modifications.

### Expected behavior
 
Code should be checked out with LF line ending (in my case) or any original line endings.

### Actual behavior

Code was checked out with CRLF line ending

### Screenshots

![image](https://user-images.githubusercontent.com/61673365/124376764-2f090180-dcdb-11eb-8cbd-82b362b0cfe4.png)

### Logs

N/A

### Additional context

N/A

**Comment by steveward** [comment]
Thanks for the issue @brt-han-mai. GitHub Desktop should respect the settings in your config the same as Git from the command line. Could you share the output of this command from within the repository?

`git config --list --show-origin`

That should give some more information about your setup.

**Comment by brt-han-mai** [comment]
Here it is.
![image](https://user-images.githubusercontent.com/61673365/125494396-26fc3283-10fd-4e36-8e43-f7f48b5a1e01.png)

Sorry for bad redaction 🙄. I don't have mouse with me.

**Comment by shawn-ogg** [comment]
I can second that issue.

Version 2.9.0 
Windows 10

```
 git config --list --show-origin

file:C:/Program Files/Git/etc/gitconfig diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/etc/gitconfig filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/etc/gitconfig filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/etc/gitconfig filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/etc/gitconfig filter.lfs.required=true
file:C:/Program Files/Git/etc/gitconfig diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/etc/gitconfig filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/etc/gitconfig filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/etc/gitconfig filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/etc/gitconfig filter.lfs.required=true
file:C:/Program Files/Git/etc/gitconfig http.sslbackend=schannel
file:C:/Program Files/Git/etc/gitconfig core.autocrlf=false
file:C:/Program Files/Git/etc/gitconfig core.fscache=true
file:C:/Program Files/Git/etc/gitconfig core.symlinks=false
file:C:/Program Files/Git/etc/gitconfig core.usebuiltinfsmonitor=true
file:C:/Program Files/Git/etc/gitconfig core.whitespace=cr-at-eol
file:C:/Program Files/Git/etc/gitconfig pull.rebase=true
file:C:/Program Files/Git/etc/gitconfig credential.helper=manager-core
file:C:/Program Files/Git/etc/gitconfig credential.https://dev.azure.com.usehttppath=true
file:C:/Program Files/Git/etc/gitconfig init.defaultbranch=master
file:C:/Users/D069147/.gitconfig        filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/D069147/.gitconfig        filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/D069147/.gitconfig        filter.lfs.process=git-lfs filter-process
file:C:/Users/D069147/.gitconfig        filter.lfs.required=true
file:C:/Users/D069147/.gitconfig        user.name=Tobias Farrenkopf
file:C:/Users/D069147/.gitconfig        user.email=#############
file:C:/Users/D069147/.gitconfig        init.defaultbranch=master
file:C:/Users/D069147/.gitconfig        core.eol=lf
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.symlinks=false
file:.git/config        core.ignorecase=true
file:.git/config        submodule.active=.
file:.git/config        remote.origin.url=###################
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.master.remote=origin
file:.git/config        branch.master.merge=refs/heads/master
```

**Comment by shawn-ogg** [comment]
@steveward did you had a chance to look at this?

**Comment by steveward** [comment]
@brt-han-mai do you have anything set in the `.gitattributes` file of this repository that could be modifying the line endings?

**Comment by brt-han-mai** [comment]
> @brt-han-mai do you have anything set in the `.gitattributes` file of this repository that could be modifying the line endings?

No. I don't have

```bash
$ ls -la .gitattributes
ls: cannot access '.gitattributes': No such file or directory
```

**Comment by steveward** [comment]
@brt-han-mai just to confirm --  are seeing these line ending changes in both GitHub Desktop and Git Bash?

**Comment by brt-han-mai** [comment]
I stopped using the GitHub Desktop. Sorry and Thanks.

**Comment by brt-han-mai** [comment]
> @brt-han-mai just to confirm -- are seeing these line ending changes in both GitHub Desktop and Git Bash?

If I don't use GitHub Desktop, the issue does not happen.
If I use GitHub Desktop, the issue happens. If I open the repo by VS Code and check the ```git status```, all files are changed (red color), it means issue happens. In the File Browse Pane of the VS Code, all files are red, it means issue happens.

As I said before, it seems that GitHub Desktop somehow changes the LF line ending to CRLF line ending by its own. Should you check the issue in the source code?

Also, a little bit surprise when you close the issue. I feel disappointed.
