### ISSUE TITLE
enable multiple independent GitHub Desktop instances

### ISSUE THREAD

**Issue by gbresearch** [desktop/desktop#12578]
### Describe the feature or problem you’d like to solve

It's common for developers to work on multiple projects which may include multiple repositories and multiple accounts. Current single instance Desktop design creates unnecessary complications for developers and is error prone.

### Proposed solution

GitHub Desktop must allow multiple instances with independent settings or allow creating multiple projects with independent settings within one instance. Multiple instances is a preferred design because those instances can be placed in different Windows desktops at the same place where all other tools for a particular project are located.

**Comment by bacharacherif** [comment]
#12475

**Comment by lance-anderson** [comment]
Agreed. At least the ability to have multiple tabs/windows. I'm trying out GitHub Desktop today after using [Tower](https://www.git-tower.com/mac) for years now. I enjoy having multiple windows open to different repositories at the same time and was disappointed and surprised it isn't supported in GitHub Desktop yet.

**Comment by steveward** [comment]
Thanks for the issue @gbresearch. I'm going to add this to https://github.com/desktop/desktop/issues/3606 where we are tracking support for multiple instances.

**Comment by Viznity** [comment]
+1
