### ISSUE TITLE
Issues with the Folder Selection when Cloning Repository

### ISSUE THREAD

**Issue by jjavierv** [desktop/desktop#12571]
When cloning a project via URL, the Local Path button is not working properly.  The complete path must be entered manually in the Local Path text box.

Version 2.9.0 (x64) - Windows 10 Pro 21H1

**Steps to reproduce the behavior**

1. Go to 'File' and select 'Clone Repository'
2. Click on the 'Choose...' button to select a Local Path via the File Explorer Dialog Box
3. Select a Folder and press 'Select' (it changes to 'Open'), then press 'Open' to open the folder.
4. Press 'Select'

**Expected Behavior**
The dialog box should close itself upon folder selection, and update the 'Local Path textbox

**Actual behavior**
Nothing happens.  The user must close the dialog box to return and manually input the local path.

**Comment by tidy-dev** [comment]
@jjavierv Thanks for the report! Unfortunately, I could not reproduce this behavior. Would you mind submitting a screen capture?
