### ISSUE TITLE
Description & title of the commit stay visible

### ISSUE THREAD

**Issue by Roxy-cyber888** [desktop/desktop#12575]
### Describe the bug

After commited some code, the title and the description remain visible in the "Changes" part 

### Version & OS

Version 2.9.0 (x64)
Windows 10

### Steps to reproduce the behavior

Put a title and a description to a commit and commit your code

### Expected behavior

Clear the inputs for the nex commit

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the issue @Roxy-cyber888. Could you reproduce this issue and share a screenshot? That should better help me understand the problem. Thanks!
