### ISSUE TITLE
Improve resize left panel and remove the width pixel limit

### ISSUE THREAD

**Issue by passariello** [desktop/desktop#12576]
### Describe the feature or problem you’d like to solve

Please, remove the limit that you impose on left side of application... it's really annoying

### Proposed solution

Remove the limit to have a nice interaction with files and long names

### Additional context

![Screenshot 2021-07-07 084001](https://user-images.githubusercontent.com/17809213/124789474-2d1f8800-deff-11eb-8d02-90a1ebe672ce.jpg)

**Comment by steveward** [comment]
Thanks for the issue @passariello, we are tracking this in https://github.com/desktop/desktop/issues/2745. I'm going to close this out.
