### ISSUE TITLE
Cloning not working in Ubuntu 

### ISSUE THREAD

**Issue by shariful23** [desktop/desktop#12588]
I am trying to clone a repository from Github Desktop ( Ubuntu Version ) But I am getting this error: 

<code> Cloning into '/home/sujon/Desktop/ExpenseTracker/p'...
/usr/lib/github-desktop/resources/app/git/libexec/git-core/git-remote-https: symbol lookup error: /usr/lib/github-desktop/resources/app/git/libexec/git-core/git-remote-https: undefined symbol: curl_global_sslset
</code>

Please Help :)

**Comment by steveward** [comment]
Thanks for the issue. At this time we do not provide official support for GitHub Desktop on Linux. I'd recommend opening up an issue in the Linux fork:

https://github.com/shiftkey/desktop/issues
