### ISSUE TITLE
Select all commits broken on windows

### ISSUE THREAD

**Issue by caxapexac** [desktop/desktop#12585]
### Describe the bug

Some version of the program ago I was able to select every uncommited change to discard it. Now it doesn't work

### Version & OS

Version 2.9.0 (x64)

### Steps to reproduce the behavior

1. Click on any uncommited file
2. Press Ctrl+A
3. See nothing selected

### Expected behavior

Everything selected

### Actual behavior

Selecting some text fields from the upper-right of the commit view window

Sometimes it works I don't know why

### Screenshots

What actually selects

![image](https://user-images.githubusercontent.com/33996246/125090455-049eb600-e0d8-11eb-9781-251ab06080b9.png)

**Comment by steveward** [comment]
Thanks for the issue @caxapexac. It looks like you have the split diff view enabled. You need to switch back to unified to discard multiple selected changes in the diff view. See [this explanation](https://github.com/desktop/desktop/issues/11948#issuecomment-831200004) for more details. Let me know if you have any further questions about how this works!

**Comment by caxapexac** [comment]
It's not relevant to my problem. Read the issue again please. I want to select files at the left side of the screen, not diffs

**Comment by steveward** [comment]
@caxapexac apologies for misunderstanding your question. You can right-click the "changed files" header and select `Discard all changes` to discard the changes to all of the files. I was also able to use `Ctrl-A` to select all the files in the list without issue on both macOS and Windows.

**Comment by caxapexac** [comment]
Wow thank you it is exactly what I wanted ;)
