### ISSUE TITLE
Can't delete folder/file if open github desktop

### ISSUE THREAD

**Issue by gladshop** [desktop/desktop#12598]
### Describe the bug

I can't delete folder target and any folder/file in target folder if open github desktop (this folder has been in .gitignore)

### Version & OS

Version 2.9.0 (x64)

### Steps to reproduce the behavior

I can't delete folder target and any folder/file in target folder if open github desktop (this folder has been in .gitignore)

=> Can't build project if open github destop

### Expected behavior

Allow delete folder when open github destop

### Actual behavior

Can't delete folder when open github destop

**Comment by steveward** [comment]
@gladshop thanks for the report. I wasn't able to reproduce any issues deleting files in File Explorer with GitHub Desktop open, but there may be something I am missing. Can you provide specific reproduction steps?
