### ISSUE TITLE
GitHub Desktop ERROR

### ISSUE THREAD

**Issue by luismendes070** [desktop/desktop#12628]
### Describe the bug
git push
https://gist.github.com/luismendes070/1f72965c442a1fca3e326e080343e698
Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.

### Version & OS
Microsoft Windows 10 Pro 21H1 19043.1110
Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by Elchiclesjxkw** [comment]
Eso que o xq es eso

**Comment by steveward** [comment]
@luismendes070 thanks for the issue. It looks like you are using BitBucket. Did you clone this repository outside of GitHub Desktop and add it? To use BitBucket with GitHub Desktop you need to generate a token, which can be used during the clone operation. You can follow [this guide](https://github.com/desktop/desktop/blob/development/docs/integrations/bitbucket.md) for more information about how to do that. Let me know if you run into any problems.
