### ISSUE TITLE
Please add links to open pull requests for a branch

### ISSUE THREAD

**Issue by owenbrownzc** [desktop/desktop#12629]
### Describe the feature or problem you’d like to solve
I've made a commit and I want to see my Pull Request for the branch I'm on.

### Proposed solution
This is what is currently displayed:
![image](https://user-images.githubusercontent.com/68297063/125813390-0a59f3ec-e6cf-44c7-8934-e359b994f690.png)
It's not helpful. Instead it should show the links to each of the open pull requests for this branch.

How will it benefit Desktop and its users?
It will save each user 10-15 seconds each time they want to navigate to their pull requests for a branch they have updated.

### Additional context
The "Create a pull request" feature is great. Let's build from here. 
Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@owenbrownzc thanks for the issue! You can use `Command/Control+R`  or use the `Branch` -> `Show Pull Request` menu option to quickly open the pull request for the branch in your browser. We're also tracking broader improvements to the pull request experience in https://github.com/desktop/desktop/issues/11517, so I'd recommend following there for updates. Feel free to drop any specific feedback you have in that issue.
