### ISSUE TITLE
GitHub Desktop wont authenticate my bitbucket user

### ISSUE THREAD

**Issue by Santirazoqui** [desktop/desktop#12632]
### Describe the bug

Github desktop refuses to authenticate bitbucket user

### Version & OS

Version 2.9.0 (x64)
Windows

### Steps to reproduce the behavior

1. Click on 'Fetch Origin'
2. Fill Username and Password fields
3. Click 'Save and Retry'

### Expected behavior

I expect github desktop to validate my user and effectively fetch the repository branch.

### Actual behavior

Authentication fails

### Screenshots

![image](https://user-images.githubusercontent.com/71331155/125854542-82a99970-ee0c-4d16-a8a2-fde316e6fb8a.png)

### Additional context

I have already changed password, and I can access BitBucket without any problems, so it's hard to know if it's a problem on my part.

I have also tried reinstalling, and signing out of my github account. Git Bash works fine, though it asks for validation every time I want to do something.

**Comment by steveward** [comment]
@Santirazoqui you will need to generate a personal access token to use BitBucket with GitHub Desktop. See [this guide](https://github.com/desktop/desktop/blob/development/docs/integrations/bitbucket.md) for the specific steps. Let me know if you have any questions!
