### ISSUE TITLE
Github Desktop not updating tags correctly

### ISSUE THREAD

**Issue by tyler-g-AVGroup** [desktop/desktop#12631]
### Describe the bug

After (re)creating a Tag via the web repo, the tag will not update on github desktop. Same branch is being used.

### Version & OS

GitHub Desktop
Version 2.9.0 (x64)

Windows Specs
Edition	Windows 10 Pro
Version	20H2
OS build	19042.1110
Experience	Windows Feature Experience Pack 120.2212.3530.0

### Steps to reproduce the behavior

1. Create tag on repo. <commit 1> <tag 1>
2. go to website, delete tag
3. make a change on the website (ie: update readme or somthing), commit. <commit 2>
4. Add a tag by making a release online, use the same tag as original. <tag 1>
5. Check that the tag is associated to the newer commit SHA
6. open Github Desktop, fetch/pull
7. look at history

### Expected behavior

<tag 1> should have been removed from <commit 1> and placed on <commit 2>

### Actual behavior

<tag1> stays on <commit 1>

If user removes the repo from their computer and re-clones, the tag updates to <commit 2>.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

Probably not "correct" use of the tag system, as tags should not be deleted and reused, but here we are.
Have not tried adding a previously unused tag, via web, to see if it updates. So, I'm not sure if it is just a bug on re-used tags or if its a larger issue in which tags are not being updated when  pulling origin.

**Comment by steveward** [comment]
Thanks for the issue @tyler-g-AVGroup. This is the expected behavior -- see [this comment](https://github.com/desktop/desktop/issues/9946#issuecomment-639611586) for more details.

**Comment by steveward** [comment]
@tyler-g-AVGroup tags that have been deleted/updated via the web UI will not be deleted locally in GitHub Desktop -- see this [explanation](https://github.com/desktop/desktop/issues/9946#issuecomment-639611586) for more details. Let me know if you have any questions about this.

**Comment by tyler-g-AVGroup** [comment]
Thanks for the reply and the extra info!
