### ISSUE TITLE
Logout highlighted on Prefs page

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1264]
Logout button for user is highlighted (ever so slightly) when I open Prefs panel. This also prevents the hover UI change when you mouseover. 

<img width="600" alt="2017-04-21_1142" src="https://cloud.githubusercontent.com/assets/14828183/25291707/0d8ccdd8-2688-11e7-86f9-e0e5d4db001b.png">

Did notice this after I logged out and logged back in, although I cannot pinpoint an exact connection.

v0.0.33, OSX 10.11.5

**Comment by joshaber** [comment]
@tierninho I can't reproduce this in 0.6.2. Could you give it another shot?

**Comment by tierninho** [comment]
Looks fixed, closing.
