### ISSUE TITLE
checkbox in stashs changes

### ISSUE THREAD

**Issue by danny007in** [desktop/desktop#12649]
![image](https://user-images.githubusercontent.com/50356015/126070772-daba4a8c-9d8c-47bb-99a3-a1dba09cea79.png)

**Comment by steveward** [comment]
Thanks for the issue @danny007in. Can you share some specific details about why adding a checkbox to the stashed changes view would be helpful? Are you often restoring only certain stashed files?

**Comment by danny007in** [comment]
i want to unstash particular files.
this feature will be time saving

**Comment by steveward** [comment]
@danny007in this was requested in https://github.com/desktop/desktop/issues/11531 so I am going to close this out. Thanks for using GitHub Desktop.
