### ISSUE TITLE
Add a 'Open in GithHub Desktop' context menu in Explorer. 

### ISSUE THREAD

**Issue by dhruvnnd** [desktop/desktop#12641]
There should be an `Open in GitHub Desktop` context menu in the File Explorer.

It will make things much easier by speeding up the process of accessing GitHub Desktop directly from the File Explorer. 

I have seen this feature in **Sourcetree**, and liked it a lot and thought that it should exist in GitHub Desktop as I use it pretty much a lot.

**Comment by steveward** [comment]
Thanks for the feedback @iDCoded! This is being tracked in https://github.com/desktop/desktop/issues/5373 so I would recommend following along there for updates.
