### ISSUE TITLE
Remove repository dialog is slow and locks UI thread

### ISSUE THREAD

**Issue by wreiske** [desktop/desktop#12642]
### Describe the bug

When you click the "Remove" button in the "Remove repository" dialog, it locks the UI thread and doesn't show any progress. It would be nice if the UI thread didn't lock up & a progress bar, or at least a spinner, displayed.

### Version & OS

Version 2.9.0 (x64)
Windows 10

### Steps to reproduce the behavior

1. Go to a repository
2. Click on "Repository" in the menu bar
3. Click on 'Remove..." menu item
4. Click on "Remove" button

### Expected behavior

No locking UI and a progress bar of some sort should display.

### Actual behavior

![USYwUzQO21](https://user-images.githubusercontent.com/6295044/126024843-45ab59af-79a9-457d-8f5a-d3f2e6c63880.gif)

**Comment by steveward** [comment]
Thanks for the issue @wreiske. I'm going to add this to https://github.com/desktop/desktop/issues/11980 and close this one out.
