### ISSUE TITLE
F11+normalize window

### ISSUE THREAD

**Issue by valerybokov** [desktop/desktop#12643]
### Win10

GitHub Desktop version 2.9.0 (x64)
### Steps to reproduce the behavior

1. app window if maximized
2. press F11 key (expected hide menu mode. It looks like it doesnt support)
3. try to normalize window (button between minimize and close)

### Expected behavior

The app window will be normalized.

### Actual behavior

The window is still maximized.

### Screenshots

no

### Logs

no

### Additional context

no

**Comment by steveward** [comment]
Thanks for the issue @valerybokov. This is being tracked in https://github.com/desktop/desktop/issues/6223, so I am going to close this out as a duplicate. 

You can use `F11` to normalize the window again. You can also use `Alt` to bring up the GitHub Desktop menu in this full screen mode. This behavior is present in other applications like VSCode as well.
