### ISSUE TITLE
.gitignore is not ignoring files

### ISSUE THREAD

**Issue by techandtopics** [desktop/desktop#12645]
### Describe the bug

.gitignore does not work

### Version & OS

Git Desktop Version 2.9.0 (x64) on Win10

### Steps to reproduce the behavior

1. Create/checkout a repo
2. Add a .gitignore file in the root folder
3. Try to commit, but see that the ignored files still are tracking
4. Try clearing cache via git, but still see same behavior

### Expected behavior

I would expect that the files listed in .gitignore would be ignored and not commited.

### Actual behavior

Files listed in .gitignore are still being tracked and committed.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@techandtopics thanks for the issue. 

>Try clearing cache via git, but still see same behavior

Did you run `git rm --cached <filename>`? If the files were previously committed you will need to run that command.

**Comment by techandtopics** [comment]
I tried:

```
git rm -r --cached .
git add .
git commit -am 'git cache cleared'
git push
```

I think I'll just delete my local repos or something and try again. I'm guessing this is just my issue, so I'm closing this. Sorry.
