### ISSUE TITLE
fatal: bad numeric config value ''false'' for 'http.sslverify': invalid unit

### ISSUE THREAD

**Issue by TiZing** [desktop/desktop#12647]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@TiZing thanks for the issue. This sounds like a problem with your `.gitconfig`. Could you open the command line and run `git config --list` and let me know the output of that command?
