### ISSUE TITLE
Node.js downloaded 

### ISSUE THREAD

**Issue by NSR111** [desktop/desktop#12644]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by NSR111** [comment]
Hello team i m new in this community pls help me to learn all the amazing methods, so i try my best.

**Comment by steveward** [comment]
@NSR111 this issue tracker is for GitHub Desktop. If you have programming questions I'd recommend checking out https://github.community. Let me know if you have any specific questions about GitHub Desktop.
