### ISSUE TITLE
有没有中文版本的 插件  

### ISSUE THREAD

**Issue by dugudongfangshuo** [desktop/desktop#12656]
有没有中文版本的 插件

**Comment by steveward** [comment]
Thanks for contributing @dugudongfangshuo. At this time we do not have language localization in GitHub Desktop, but this is something that we would like to do in the future. I don't have a timeline for when that may happen as it would require quite a bit of work by the team. I'm sorry that I don't have better news at this time.

**Comment by dugudongfangshuo** [comment]
Thank you for your reply
