### ISSUE TITLE
i can't find my reposetories

### ISSUE THREAD

**Issue by street-fighter99** [desktop/desktop#12651]
### Describe the bug

I can't find the reposetories that are avaible in my github

### Version & OS

Laptop,windows 10,

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for reaching out @street-fighter99!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further.
