### ISSUE TITLE
Can't install GitHub Desktop in Wine 5.0

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [desktop/desktop#12655]
### Describe the bug

When I try run `wine GitHubDesktopSetup-x64.exe` I obtain `0009:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80040111 for dll L"C:\\windows\\system32\\ieframe.dll` error and the following window opens:

![Screenshot from 2021-07-20 14-35-56](https://user-images.githubusercontent.com/42812113/126262935-6de79829-7162-4644-af8e-2ccbdc38fd16.png)

### Version & OS

OS version: Ubuntu 20.04.2 LTS
Wine version: wine-5.0 (Ubuntu 5.0-3ubuntu1)

### Steps to reproduce the behavior

1. Download GitHub Desktop Windows installer
2. Execute `wine GitHubDesktopSetup-x64.exe`
4. See `0009:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80040111 for dll L"C:\\windows\\system32\\ieframe.dll` error

### Expected behavior

Normal installation in Wine 5.0

### Actual behavior

Installation failure.

**Comment by steveward** [comment]
@alvinseville7cf thanks for the issue. At this time we only provide official support for macOS and Windows. I'd recommend downloading the unofficial Linux fork of GitHub Desktop to use on Ubuntu:

https://github.com/shiftkey/desktop/releases

I hope that helps!
