### ISSUE TITLE
CREATE Repository BUTTON DISABLED

### ISSUE THREAD

**Issue by codernoob1** [desktop/desktop#12669]
### Describe the bug
crate repository button did not work
when I click new repository and a dialogue box where I have to name my repository but in my case even after give a name to the repository and give description ,the create repository button did not work.   
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.
Version 2.9.0 (x64)
### Steps to reproduce the behavior

1. Go to '..file .'
2. Click on '...new repository.'
3.after giving the name and description
4. 
 you will see create repository button disabled

### Expected behavior
create repository should enabled 

### Actual behavior
create repository button disabled
A clear and concise description of what actually happened.

### Screenshots
![Screenshot (62)](https://user-images.githubusercontent.com/79470721/126748421-3a75f62f-c049-4305-ae6d-527678113bb2.png)

here ,look create repository button is still disabled

**Comment by sergiou87** [comment]
Your screenshot has a warning below the local path, have you seen that?

![2021-07-26 at 10 34](https://user-images.githubusercontent.com/1083228/126959208-dd05f32a-4663-4a95-95f4-e7213102d06b.png)

It means that folder is already a git repository, probably by mistake I'd say looking at the folder name, so you need to choose a different one.

I'll close this assuming that's the problem, but let us know if something different is wrong.
