### ISSUE TITLE
submodule recursive push

### ISSUE THREAD

**Issue by john-kays** [desktop/desktop#12660]
### Describe the feature or problem you’d like to solve
Hi, I am working with sub modules within GitHub repository.
I was able to pull everything using git submodule update --recursive
but when I update code in submodules, it doesn't show up in the GUI updates.
How can I use Github desktop to take into account all changes in submodules and further push them on a branch?

Thanks
A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
Thanks for the issue @john-kays. Can you verify in the `.gitmodules` file that you do not have ` ignore = dirty` set? That will cause Git to ignore submodules with changes.

We also have a list of known issues with submodules that we are tracking in https://github.com/desktop/desktop/issues/7523.
