### ISSUE TITLE
Integrations running in 32 bit instead of 64

### ISSUE THREAD

**Issue by UndercoverNL** [desktop/desktop#12661]
### Describe the bug

When editing a file with the software selected in the options > Integrations tab, my editor starts up with an error which tells me that I am running the 32 bit launcher and not the 64 bit. My editor is in this case PHPStorm

### Version & OS

2.9.0 (x64) Windows 10

### Steps to reproduce the behaviour

1. Go to 'options > Integrations'
2. Select PHPStorm as editor.
3. Go to any branch to edit or view files.
4. Click on | Open in JetBrains Phpstorm" in the "Open the repository in your external editor" tab

### Expected behaviour

The file loads in PHPStorm

### Actual behaviour

As soon as github desktop is trying to startup the editor phpstorm returns the error which says that the 32-bit launcher has been used instead of the 64 bit one.

### Screenshots

![image](https://user-images.githubusercontent.com/42718013/126443405-c457a72a-6f90-40d9-ba92-aadc72b17b5e.png)

### Logs

[2021-07-21.desktop.production.log](https://github.com/desktop/desktop/files/6853343/2021-07-21.desktop.production.log)

**Comment by feilipuxiansheng** [comment]
leve on databases;

**Comment by steveward** [comment]
Thanks for the issue @UndercoverNL. Currently GitHub Desktop is referencing the 32-bit version of PHPStorm, which is causing this issue. The Jetbrains integrations need updating, and we're using https://github.com/desktop/desktop/issues/9453 as a broader tracking issue for that. If you're interested in helping out with this you can see our [editor integration docs](https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md).

I'm going to add this to the tracking issue linked above and close this out.
