### ISSUE TITLE
authentication failing in desktop app (works in command line)

### ISSUE THREAD

**Issue by LarsLiden** [desktop/desktop#12667]
### Describe the bug

Starting this morning I started getting Authentication Failed messages when I try to update my ADO repository or re-clone.  I've validated my credentials (name and password) in ADO.   Note that it still works just fine via the git command line - just fails in github desktop.  I've tried restarting the app and re-cloning

### Version & OS

Version 2.9.0 (x64) on Windown 10

### Steps to reproduce the behavior

Attempt to update an existing repository or re-clone

### Expected behavior

Shouldn't have auth failure

### Actual behavior

Getting auth failure

### Logs

2021-07-22T17:27:20.333Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
fatal: Authentication failed for 'https://msazure.visualstudio.com/DefaultCollection/....'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.

### Additional context

Worked fine yesterday and still works fine if I use the command line

**Comment by sergiou87** [comment]
Weird that it works in command line but not in GitHub Desktop 🤔  Is it possible you need some kind of Personal Access Token instead of your password?

For example: https://github.com/desktop/desktop/blob/development/docs/integrations/azure-devops.md
