### ISSUE TITLE
File selection in Changes tab should use the Git index

### ISSUE THREAD

**Issue by dmolesUC** [desktop/desktop#12668]
### Describe the feature or problem you’d like to solve

GitHub Desktop conceptually distinguishes staged and unstaged changes (checked and unchecked files), but doesn't use the index to do it. When switching back and forth between Desktop and other tools (the command line, Visual Studio Code…), there's no relationship between the selections in Desktop and the actual state of the index. This is confusing and likely to lead to user error.

### Proposed solution

Using the Git index to track the checked/unchecked state instead of tracking it separately in the application would allow users to move seamlessly between tools without having to either

1. choose not to use the Git functionality of their other tools or,
2. risk messing up their changesets

### Additional context

Screenshot with Desktop (top left), VS Code (top right), command line (bottom). Note that VS Code and the command line agree on what's going to be in the next commit, but Desktop has its own ideas.

<img width="970" alt="Screen Shot 2021-07-22 at 2 15 24 PM" src="https://user-images.githubusercontent.com/10374934/126710829-6a43b328-7ab6-4ca8-b4ab-7ad8080c3631.png">

**Comment by billygriffin** [comment]
Thanks for the issue @dmolesUC, and appreciate you sharing your perspective. This was a design choice that we made knowing there are unfortunately downsides, but overall it seems to work quite well for the vast majority of Desktop users. Here's a bit more context on how it works and why: https://github.com/desktop/desktop/issues/4408#issuecomment-379527584

I totally understand that some folks will have differing opinions here, but we don't plan to change such a core part of the app. Thanks again.

**Comment by dmolesUC** [comment]
@billygriffin I understand not wanting users to have to learn how staging and the index work (I don't **agree** with it—I think it's one of the features that makes git git, and one of the reasons this isn't MercurialHub Desktop or SVNHub Desktop—but I understand it).

That said, I don't think the actual user experience for the average user has to change at all; I'm not proposing explicit index support like VS Code, I'm proposing using the index as the backing store for the feature Desktop _already has_ of selecting which files are going to be committed.

The only potentially knotty situation I can see is where someone (outside of Desktop, in a tool that supports it) stages a file and then makes further edits—that's the additional feature the real index has that Desktop's checkboxes don't. But you could finesse that by automatically `git add`-ing those files, and still get the same behavior Desktop has now, with the additional benefit that anyone who does use other tools (half the editors on your [list of supported editors](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/configuring-and-customizing-github-desktop/configuring-a-default-editor)) will see a consistent state.

(FWIW, this is similar to what JetBrains does, although they don't `add` until `commit`, and their reimplementation of SVN changelists on top of Git confuses things even further.)

**Comment by hhe** [comment]
This is literally the only reason I don't use Github Desktop. Otherwise it's much nicer than `git gui` and most other clients.

I'm not sure how difficult it would be, but having this behavior at least be _configurable_ would vastly improve the experience, not just for more technical users but also intermediate users.
