### ISSUE TITLE
I can't connect VS through github

### ISSUE THREAD

**Issue by PeaceFL** [desktop/desktop#12666]
### Describe the bug
Sorry, I have no way to let my github connected to VS

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@hufei12 this issue tracker is for GitHub Desktop. Are you trying to connect to GitHub using Visual Studio? Microsoft [has documentation](https://docs.microsoft.com/en-us/visualstudio/version-control/git-with-visual-studio?view=vs-2019) for working with Git in Visual Studio.

You can also use GitHub Desktop alongside Visual Studio. If you're referring to the fact that GitHub Desktop does not support launching Visual Studio, then this is something that we are aware of (see https://github.com/desktop/desktop/issues/3148). I hope that helps!
