### ISSUE TITLE
Add a 'Verbose' or 'learning' mode

### ISSUE THREAD

**Issue by kartikcho** [desktop/desktop#12674]
### Describe the feature or problem

The app, although abstracts the Git commands (which is pretty much the point of a visual Git client), can make it difficult for new devs to understand how things are working behind the app. 
Considering the amount of folks who use GitHub Desktop to learn and start using Git, I think the tool can also be used in reverse to help understand the Git commands used instead of wrapping and abstracting it away for all users.

### Proposed solution

Show the Git commands used behind every action in the UI so people can also learn what's happening under the hood to achieve a particular action.

### Mock

The mock suggests some places where we can add commands to the UI (with one example in the modal header).

![image](https://user-images.githubusercontent.com/48270786/126893816-f5c9ea70-d2cc-4e02-aa2e-c01273a7def8.png)

This maybe an absurd request but I think Gh Desktop is the most beginner friendly Git client out there and adding this feature would surely help new devs even more!

**Comment by kleinkkk** [comment]
> ### Describe the feature or problem
> The app, although abstracts the Git commands (which is pretty much the point of a visual Git client), can make it difficult for new devs to understand how things are working behind the app.
> Considering the amount of folks who use GitHub Desktop to learn and start using Git, I think the tool can also be used in reverse to help understand the Git commands used instead of wrapping and abstracting it away for all users.
> 
> ### Proposed solution
> Show the Git commands used behind every action in the UI so people can also learn what's happening under the hood to achieve a particular action.
> 
> ### Mock
> The mock suggests some places where we can add commands to the UI (with one example in the modal header).
> 
> ![image](https://user-images.githubusercontent.com/48270786/126893816-f5c9ea70-d2cc-4e02-aa2e-c01273a7def8.png)
> 
> This maybe an absurd request but I think Gh Desktop is the most beginner friendly Git client out there and adding this feature would surely help new devs even more!

**Comment by steveward** [comment]
Thanks for the feedback @kartikcho. This has been previously discussed in https://github.com/desktop/desktop/issues/1570 and at this time is something that we do not have plans of adding to GitHub Desktop. I'll add this feedback to #1570.
