### ISSUE TITLE
# how to install pandas_profiling using github

### ISSUE THREAD

**Issue by oguro515** [desktop/desktop#12671]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by Mrlinkwii** [comment]
can you please fill out the template  :slightly_smiling_face:
