### ISSUE TITLE
unable to login from git desktop 

### ISSUE THREAD

**Issue by harish92** [desktop/desktop#12676]
### Describe the bug

unable to login from git desktop client every time shows authentication failed

### Version & OS
Git Desktop version: Version 2.9.0 (x64)
OS: windows 11

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by sergiou87** [comment]
Hi @harish92! 👋 

Could you provide more details so we can help you more effectively?

Is the repository hosted in GitHub or in some other service?
