### ISSUE TITLE
无法使用GitHub desktop拉取代码

### ISSUE THREAD

**Issue by Gronyan** [desktop/desktop#12677]
已安装GitHub desktop，但是无法使用GitHub desktop直接拉取代码,更换edge浏览器也不可以
![搜狗截图20210726181403](https://user-images.githubusercontent.com/70813470/126973118-8c24485c-e145-47c5-854f-7b203e3675fc.png)

**Comment by steveward** [comment]
@Royan7 thanks for the issue. It looks like you are running into https://github.com/desktop/desktop/issues/8258, where TortoiseGit hijacks GitHub Desktop's links. See https://github.com/desktop/desktop/issues/10352 for some further discussion about this. Let me know if you have any further questions.
