### ISSUE TITLE
Broken link from local repo

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1267]
When deleting a cloned repo, then adding the repo back locally, I noticed the SHA links were broken despite being hyperlinked. I'd expect the link to be grey'd out until the repo is re-synced with dotcom. 

<img width="972" alt="screen shot 2017-04-21 at 1 49 54 pm" src="https://cloud.githubusercontent.com/assets/14828183/25295912/92784e70-269a-11e7-9737-155051d77109.png">

Once the app syncs with dotcom, the link was re-established:
<img width="747" alt="screen shot 2017-04-21 at 1 56 20 pm" src="https://cloud.githubusercontent.com/assets/14828183/25295958/cceb8518-269a-11e7-9072-1f4d4f101e7b.png">
I tried clicking the `update origin`, but nothing happened, so I had to reselect the repo, and then the sync was initiated and link was clickable.

Build 0.0.34, OSX 10.11.5

**Comment by shiftkey** [comment]
I think this has been inadvertedly fixed as my newly created, unpublished commit doesn't show a View on GitHub link at all (this is on `0.6.2`):

<img width="985" alt="screen shot 2017-06-24 at 11 47 52 am" src="https://user-images.githubusercontent.com/359239/27511148-30894424-58d3-11e7-9345-b40d269b1b18.png">
