### ISSUE TITLE
Commits take a very long time to complete

### ISSUE THREAD

**Issue by mttkay** [desktop/desktop#12670]
### Describe the bug

Commits take a very long time to complete compared to using CLI.

I looked at the logs to understand what's happening after committing via the UI, and here is what I see:

```
2021-07-23T17:20:57.980Z - info: [ui] [AppStore] loading 16 repositories from store
2021-07-23T17:20:58.174Z - info: [ui] launching: 2.8.1-linux1 (Linux 5.11.0-7620-generic)
2021-07-23T17:20:58.174Z - info: [ui] execPath: '/usr/lib/github-desktop/github-desktop'
2021-07-23T17:21:38.762Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 35.509s)
2021-07-23T17:21:38.935Z - info: [ui] [Timing] Action 'create commit' for 'stargazer' took 35.715s
```

Something called `updateIndex` took 35 seconds to complete before the app even attempted to commit.

### Version & OS

Version 2.8.1-linux1

OS: Pop_OS! 21.04

```
Linux carbon 5.11.0-7620-generic #21~1624379747~21.04~3abeff8-Ubuntu SMP Wed Jun 23 02:34:03 UTC  x86_64 x86_64 x86_64 GNU/Linux
```

### Steps to reproduce the behavior

1. Go to 'main UI'
2. Click on 'Commit' (can even be a single, small file)

Though I expect that there is something at play that only affects certain setups or projects.

### Expected behavior

A commit not taking longer than on the CLI.

### Actual behavior

A commit taking 35 seconds instead of at most a second on the CLI.

### Logs

See description.

**Comment by Mrlinkwii** [comment]
:wave: linux isn't offically supported ( as per  https://github.com/desktop/desktop/issues/1525#issuecomment-783584346 ) but theirs a linux fork you can use   https://github.com/shiftkey/desktop/ to post said issue their  if its still occuring   also the version your using is old id recommend updating to the latest version also

**Comment by mttkay** [comment]
> wave linux isn't offically supported ( as per [#1525 (comment)](https://github.com/desktop/desktop/issues/1525#issuecomment-783584346) ) but theirs a linux fork you can use https://github.com/shiftkey/desktop/ to post said issue their if its still occuring also the version your using is old id recommend updating to the latest version also

Hi, interesting, I wasn't aware that this is an unofficial fork. But it is the version I use, since when I click About > Releases, it takes me to https://github.com/shiftkey/desktop/releases/

I had installed it via flathub in Pop_OS, so it looks like these releases are distributed via flatpak. I am on the latest version of whatever is in that repository, which is a version from late May (I wouldn't exactly consider that "old").

But thanks for the pointer. If we think this problem is specific to Linux (quite honestly I don't see why -- it looks more like a git-backend thing to me and otherwise the Linux version runs flawlessly), I can move the issue to that other repository.

**Comment by sergiou87** [comment]
`updateIndex` is what adds files to the stage (i.e. the equivalent to `git add <your files>`), I'm surprised it takes that long.

Does that happen with file you add/change?

**Comment by Mrlinkwii** [comment]
> But thanks for the pointer. If we think this problem is specific to Linux (quite honestly I don't see why -- it looks more like a git-backend thing to me and otherwise the Linux version runs flawlessly), I can move the issue to that other repository.

if i remember correctly i think their was  efforts made making it better time wise in one of the 2.9.0 Rc releases

**Comment by sergiou87** [comment]
Not really like that, I'm afraid 😞 

Those changes don't affect how long `git update-index` takes: #12529
