### ISSUE TITLE
 failed to receive handshake, SSL/TLS connection failed

### ISSUE THREAD

**Issue by LYUBO-0228** [desktop/desktop#12687]
### Describe the feature or problem you’d like to solve

Write a clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

Please share how this will it benefit Desktop and its users?

### Additional context

Please include any other context, like screenshots or mockups, if applicable.

**Comment by tidy-dev** [comment]
Hi! @LYUBO-0228, Could you fill the template and provide more info about the issue you're facing? Thank you!

**Comment by LYUBO-0228** [comment]
***@***.***

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年7月28日 18:38
收件人: ***@***.***>
抄送: LYU ***@***.***>; ***@***.***>
主题: Re: [desktop/desktop] failed to receive handshake, SSL/TLS connection failed (#12687)


Hi! @LYUBO-0228<https://github.com/LYUBO-0228>, Could you fill the template and provide more info about the issue you're facing? Thank you!

―
