### ISSUE TITLE
Error receiving objects after githubdesktop update

### ISSUE THREAD

**Issue by Gae84** [desktop/desktop#12686]
Hello,
while i try to download my files from a repository (pull) i get timeout errors. 
It stays stuck at around 3% for 5 minutes and then shows me the message:

**remote: Enumerating objects: 40097, done.        
remote: Counting objects: 100% (1741/1741), done.        
remote: Compressing objects: 100% (923/923), done.        
error: RPC failed; curl 56 Send failure: Connection was reset
error: 5979 bytes of body are still expected
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed_**

This problem only occurs on a PC Windows10 with the latest version of GitHubDesktop, 2.9.0 (x64) . I tried reinstalling GitHubDesktop but nothing.

The problem also occurs with other repositories.

Trying with another computer in the same network and the same GitHubDesktop version I have no problems so I rule out firewall problems.
It all started after updating to the latest release.
How can I solve?
Thanks

Gae

**Comment by tidy-dev** [comment]
Thanks for the issue @Gae84. Sometimes on windows, installing the update can have a hiccup and requires clearing out locally stored application files. If you want to clear them out, you can delete %AppData%\GitHub Desktop. This will reset the application back to a fresh state without needing to reinstall. Please note that this will not delete the repositories from your local disk. I hope that helps!

**Comment by Gae84** [comment]
I followed your instructions step by step but the error still persists.
![immagine](https://user-images.githubusercontent.com/19800910/127364655-4ce2b550-2b7e-475e-a938-130982830494.png)

Please help me.
Thanks
Gae

**Comment by sergiou87** [comment]
Is that repository hosted on GitHub.com? Does cloning/pulling from the command line work? 🤔

**Comment by Gae84** [comment]
Yes my repository is hosted on GitHub.com .
I solved the problem last night, changing the internet connection of the pc, connecting via hotspot (downloading the files at a lower speed than the optical fiber) I was able to clone the entire repository. 
Thanks for the help everyone.
