### ISSUE TITLE
Error on Publish branch

### ISSUE THREAD

**Issue by andregosling** [desktop/desktop#12695]
I try to press publish branch and it gives me this error, I've done everything and it doesn't solve.

Enumerating objects: 3771, done.
Counting objects: 100% (3771/3771), done.
Delta compression using up to 12 threads
Compressing objects: 100% (3707/3707), done.
error: RPC failed; curl 56 Send failure: Connection was reset
fatal: the remote end hung up unexpectedlyiB | 4.70 MiB/s 
Writing objects: 100% (3771/3771), 1.04 GiB | 16.19 MiB/s, done.
Total 3771 (delta 487), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

**Comment by sergiou87** [comment]
Can you try and push the branch from command line with `git push`?

AFAIK this issue usually comes from a network problem on the user's end. Please take a look at https://github.com/desktop/desktop/issues/9619 maybe there is anything that helps.
