### ISSUE TITLE
Link Github desktop app to existing local repo?

### ISSUE THREAD

**Issue by jdx-john** [desktop/desktop#12690]
I have migrated to a new Mac. I copied all my github folders across, but now GitHub app doesn't know where they are. I can't find anywhere in preferences to point it at existing folders.
When I try to clone a repo from GitHub.com to the local folder, I get an error.

How am I supposed to do this please? Hack some file, or does the GUI allow it and I missed it?

**Comment by tidy-dev** [comment]
Hi @jdx-john! You should be able to simply drag and drop the folder holding your repo into the desktop ui and it will add the repo for you.  Alternatively, you can use the "Add Existing Repository" option on the "Add" dropdown button in the repository view. 
![image](https://user-images.githubusercontent.com/75402236/127398691-1dde3a0b-79a8-4a88-9de3-f84d8685ecae.png)
