### ISSUE TITLE
how to make a game

### ISSUE THREAD

**Issue by Jannikcoding1223** [desktop/desktop#12697]
### Describe the feature or problem you’d like to solve

Write a clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

Please share how this will it benefit Desktop and its users?

### Additional context

Please include any other context, like screenshots or mockups, if applicable.

**Comment by Mrlinkwii** [comment]
can you please  fill in the template :slightly_smiling_face:

**Comment by MaddyGuthridge** [comment]
This probably isn't the place to ask. I'd suggest doing some googling. There are tons of videos on YouTube explaining how to do this as well. You might want to look at tutorials for Unreal Engine or Unity, and then learn C++ or C# respectively. Making games is far from easy, but it's a great learning experience. Just remember to start from something simple and work your way up.
