### ISSUE TITLE
Delete/Drop Commits

### ISSUE THREAD

**Issue by bmetitiri** [desktop/desktop#12694]
### Describe the feature or problem you’d like to solve
The addition of squashing and reordering commits is awesome, and I saw in other issues that a full interactive rebase is not on the roadmap, but being able to delete/ drop commits in the history would be super useful. 

### Proposed solution

Right click on a commit and have an option for "Delete". This would make rebasing in certain team workflows a lot more effective.

### Additional context

My team has a workflow where PRs are squashed and merged. Because of people having different working hours, there is often a delay between submitting a PR and getting it reviewed and merged. I sometimes create a branch A and open a PR with it, and while I am waiting for review I will make a branch B so I can continue work using changes from A. Once A is squashed and merged, if I do a non-interactive rebase of branch B onto the updated main branch, it will include all the commits from A in addition to B, which makes the diff more confusing and makes B's PR look bigger than it is. I really only want to rebase the commits from B onto the main branch. I normally handle this by reverting to using `rebase -i` on the command line and not including those commits from A in the rebase at all, but I think it would work just as well in Github Desktop to do a normal rebase and then delete the commits from A that are redundant.

**Comment by Sergio0694** [comment]
+1 to this.
I can easily avoid having to pull up git CLI in most cases now that I can squash and reorder commits from the GitHub Desktop app and then force push from there, but cases where I need to also drop commits are the only ones where I'm still forced to go back to the terminal. Being able to drop commits as suggested would be awesome. A few of my teammates also using the GitHub Desktop app also were hoping dropping commits would be enabled as well just like squashing and reordering 👍

**Comment by hckhanh** [comment]
+1
In WebStorm, it already have a feature which is called `Drop Commits`:

![image](https://user-images.githubusercontent.com/6380436/139192227-7460892c-3420-4995-ac1c-fb50a89c1e73.png)

**Comment by R-J-dev** [comment]
+1
Trying to pick this up in my spare time. Made already a small start here: https://github.com/R-J-dev/desktop/commit/66d391ec19853c8984bf73ffdd14bfe1aab180b1.
Will add a PR when finished.

**Comment by steveward** [comment]
@R-J-dev before you move forward with a PR I'd like to bring this up for discussion with the team about whether or not this enhancement is something we'd like to implement at this time. I'll put it on our agenda for discussion and will get back to you. Thanks for your interest!

**Comment by trevyn** [comment]
@R-J-dev I would love this feature and would be happy to maintain an open source fork of Desktop with this feature if upstream does not want it. So please move forward with a PR-ready patch. Thanks!

**Comment by R-J-dev** [comment]
@steveward thanks for letting me know! I could use the feature myself, so I will use the fork for now.
However, I would prefer to just add a PR and use the main version of GitHub desktop instead.
When do you expect to bring this up for discussion with your team?

PS Added a working version now in the fork. Still need to add some tests and probably a feature toggle if a PR is requested.

**Comment by steveward** [comment]
We discussed this in our weekly sync, and decided that a "delete commit" option isn't something that we would want to implement into GitHub Desktop at this time. The feature we are considering for the future would be an implementation of `git reset`, which would allow for previous commits to be deleted. The equivalent of `git reset --hard` is something we've had quite a few requests for.

There are quite a few considerations around these types of actions due to the potential of work being lost, so I don't have a firm timeline for when that may happen. Some prior work has been done, see https://github.com/desktop/desktop/pull/12393. 

I'm going to close this out, but thanks for your interest in working on this feature @R-J-dev.

**Comment by Sergio0694** [comment]
I guess we'll have to keep switching to terminal and manually doing `git rebase -1 HEAD~n`, drop, force push every time 🥲

Was really looking forwards to this one. GitHub Desktop already allows you to reorder commits, merge commits, and force push. Also allowing to drop commits felt like a natural extension to that, and something that feels like it's just missing from the context menu right now. But oh well...
