### ISSUE TITLE
GraphicsDeviceType does not contain a definition for Playstation 5

### ISSUE THREAD

**Issue by Rynalesca** [desktop/desktop#12692]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS
2.9.0 & Windows 10

### Steps to reproduce the behavior
![Screenshot 2021-07-29 160732](https://user-images.githubusercontent.com/80893825/127506653-87d106a2-0bb2-4e8a-b320-cf8b95790ff9.png)

**Comment by sergiou87** [comment]
I'm sorry, but this has nothing to do with GitHub Desktop 😅

**Comment by Rynalesca** [comment]
I just realised I posted it at the wrong place and wanted to delete it, sorry 😅
