### ISSUE TITLE
It doesn't show the last local changes to commit or push to remote branch

### ISSUE THREAD

**Issue by bahramizeynab** [desktop/desktop#12701]
### Describe the bug
I have added a new folder and a file, but it says that branch is up to date and doesn't show the change to commit or push 

### Version & OS

Version 2.9.0 (x64)
Windows 10

### Steps to reproduce the behavior

1. Got to local repo
2. create new folder
3. add a file in the folder
4. in GitHub desktop go to change tab
5. No change is listed to select and commit

### Expected behavior

It should list of change include newly added file to select and commit

### Additional context
[2021-07-31.desktop.production.log](https://github.com/desktop/desktop/files/6910891/2021-07-31.desktop.production.log)

**Comment by sergiou87** [comment]
I cannot reproduce it here, it always shows the file for me.

Can you double check the path of the repo used in GitHub Desktop is the same where you're creating the folder and file?

**Comment by bahramizeynab** [comment]
Hi  Sergiou87
Thanks for the response
The issue is fixed. The problem was that the file type of the file that I made change to it was in gitgnore. so I removed the file type from the git ignore file and it showed the change
Thanks
Zeynab

**Comment by bahramizeynab** [comment]
I will close the issue as it is resolved
Regards
Zeynab

**Comment by bahramizeynab** [comment]
I will close the issue as it is resolved
Regards
Zeynab
