### ISSUE TITLE
Difficulty pushing my local repo to the remote repo

### ISSUE THREAD

**Issue by Aro1914** [desktop/desktop#12702]
### Describe the bug
I am having problems pushing to the remote repo of my project.

### Version & OS

I am using the Version 2.9.0 (x64) of GitHub Desktop. I use a Windows OS, Windows 10 Pro-2004 version, OS build 19041.1.

### Steps to reproduce the behavior

I simply clicked on the 'Publish to Branch' button to push to my remote repo I just created.

### Expected behavior

I was expecting a confirmation of a successful push.

### Actual behavior

But after some time monitoring the progress bar, I got an error message, saying that the push unsuccessful.

### Screenshots
![2021-07-31T16_58_11](https://user-images.githubusercontent.com/68448315/127745815-a234324f-f1c1-4e52-89a0-a6fb626b0367.jpeg)

### Additional context
I had tried to push using the git bash but still, I got the same error over and over again.
![2021-07-31T17_15_17](https://user-images.githubusercontent.com/68448315/127745975-36c72930-5e31-4bfa-994d-bcd6c9fe6afc.jpeg)

### Logs
[2021-07-31.desktop.production.log](https://github.com/desktop/desktop/files/6911446/2021-07-31.desktop.production.log)

**Comment by Aro1914** [comment]
Please I would greatly appreciate a response to this issue, because it has given me serious issues. I am a student, learning the Java language and that is the second project I have done using the language that I would like to publish. In fact it was the reason I installed GitHub Desktop. Before now I use Git Bash, but hoping that the issue may be resolved if I change the application, I installed GitHub Desktop. Please I sincerely ask for assistance.

**Comment by steveward** [comment]
@Aro1914 thanks for the issue. This looks like a specific issue with the push timing out. How large is the repository that you are trying to push to GitHub?

**Comment by Aro1914** [comment]
@steveward It was about 40MB.

**Comment by steveward** [comment]
@Aro1914 are you behind a firewall or proxy that could be interfering with your connection? You can also go to https://github-debug.com/ and check the reliability of your connection to GitHub. There are some further debugging steps in [this thread](https://stackoverflow.com/questions/59282476/error-rpc-failed-curl-92-http-2-stream-0-was-not-closed-cleanly-protocol-erro) that you can try, like changing your HTTP version.

**Comment by steveward** [comment]
@Aro1914 as we have not heard back from you I am going to close this out. Let me know if you are still encountering issues and we can investigate further.

**Comment by Aro1914** [comment]
Thanks Steve Ward, I had forgotten to close the issue. I had to delete the
repo, create a BitBucket account, upload the project, then clone it to a
new GitHub repo I created with the same name as the previous repo.
