### ISSUE TITLE
Hi! 

### ISSUE THREAD

**Issue by Bedirhangndr** [desktop/desktop#12715]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by Bedirhangndr** [comment]
Hi! I try to upload my project. İ cloned my repository and some changed on my code  on jupyter notebook. Although there is a change in the github desktop application, this change is not seen in my git hub address

**Comment by sergiou87** [comment]
Hi @Bedirhangndr ! Have you committed that change? You must create a commit with those changes, and then publish the commit on GitHub. Does that make sense?
