### ISSUE TITLE
Error 503 Backend is unhealthy

### ISSUE THREAD

**Issue by joaodesousa** [desktop/desktop#12713]
When trying to download Desktop app for any OS, a "Error 503 Backend is unhealthy" is presented.

**Comment by azabiphetamine** [comment]
same

**Comment by tidy-dev** [comment]
@joaodesousa @TheGoldenPotion this should be fixed. Do you mind confirming before I close this out?

**Comment by joaodesousa** [comment]
@tidy-dev solved on my side.

**Comment by steveward** [comment]
Thanks for confirming!
