### ISSUE TITLE
Word diffs not displayed

### ISSUE THREAD

**Issue by jjcurtin** [desktop/desktop#12718]
### Describe the bug
This relatively recent [blog post](https://github.blog/2020-11-17-introducing-split-diffs-in-github-desktop/) suggested that split diffs could display highlighting of word (rather than only line) level diffs.  However, I only see line level diffs in my current version of the app.   Did word level diffs get removed as a feature?   When I look for options, I only see a checkbox to display or hide whitespace.

### Version & OS
* Github desktop Version 2.9.0 (x64)

* Windows 10 Pro for Workstations.  

### Steps to reproduce the behavior

1. Go to 'History tab'
2. Click on 'a specific commit' on any file
3. Under settings icon select Split diff display
4. Red and green highlighting displays full lines that have been changed but not individual words

### Expected behavior

I had expected that word level deletes would be highlighted in darker red than the surrounding line and word level additions would be displayed in darker green than the surrounding green line.

### Actual behavior

I only see full lines highlighted in one shade of red or green despite the commit having added and deleted individual words.

### Screenshots

The top image in the blog post  I linked to above displays the two shades of red and green to indicate line vs. word level changes that I expected.   

I have posted a screenshot of what I actually see [here](https://dionysus.psych.wisc.edu/open/github_diff.jpg).  There is no shading to indicate word level edits though you can see by the diff that words were both added or deleted from some of the lines.

### Logs

NA

### Additional context

NA

**Comment by jjcurtin** [comment]
My apologies but I see this issue has already been reported for the Mac OS in #11553.  Let this issue report confirm the issue is present on Windows 10 as well.  Thanks.   Word level diffs are very useful for some applications.  I find myself having to switch back and forth between Github desktop (which is my preferred GUI) and Gitkraken (which supports word level diffs).  It would be great to be able to use only Github desktop.  Thanks!

**Comment by steveward** [comment]
Thanks for the report @jjcurtin! I'll add this to #11553.
