### ISSUE TITLE
Error when clicking 'Fetch Origin'

### ISSUE THREAD

**Issue by thomas-orthbandt** [desktop/desktop#12728]
### Describe the bug
When Fetching Origin, I receive an error that states: Authentication failed. Some common reasons include:

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also, include what operating system you are using.

GitHub Deskto: 2.9.0
OS: Max Big Sur v11.4

### Steps to reproduce the behavior

1. Go to login
2. Click on Fetch Origin
3. See error

### Expected behavior

Expect to get the latest build from GitHub

### Actual behavior

Nothing, get Error

### Screenshots

<img width="587" alt="Screen Shot 2021-08-04 at 13 43 32" src="https://user-images.githubusercontent.com/87342650/128252677-e9f012f8-c4cd-4e48-bcc1-5d013ad159d6.png">

### Logs

[2021-08-04.desktop.production.log](https://github.com/desktop/desktop/files/6934317/2021-08-04.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the issue @thomas-orthbandt. It looks like you are using SSH with this repository, but GitHub Desktop can't find a valid key:

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

I'd recommend taking a look at the steps for troubleshooting SSH connections here:

https://docs.github.com/en/github/authenticating-to-github/troubleshooting-ssh/error-permission-denied-publickey

You can also switch GitHub Desktop to use HTTPS to fix this (this is what the app does by default). To do this you can go to `Repository` > `Repository Settings` > `Remote` and change the SSH URL to the HTTPS URL of your repository. Let me know if you have any questions or further issues.
