### ISSUE TITLE
Exploring new design concepts for GitHub Desktop on Windows 11

### ISSUE THREAD

**Issue by zedaraf** [desktop/desktop#12723]
### Describe the feature or problem you’d like to solve

Discover new designs to help improve the consistency for Windows 11 users when using GitHub Desktop

### Proposed solution

A seamless design that integrates with the new Windows 11 will give users a better experience and consistency across developing tools.

### Additional context

Credit goes to [Zee-Al-Eid Ahmad Rana](https://twitter.com/zeealeid/status/1419028161065541632/photo/2) for these design concepts.
![github_desktop_dark](https://user-images.githubusercontent.com/56755783/128172916-aafe45de-76c8-4e24-9ed4-ff60fddde9c3.png)
![github_desktop_light](https://user-images.githubusercontent.com/56755783/128172933-5a8a88d6-538d-4350-8ede-59ae7c461aca.png)

**Comment by billygriffin** [comment]
Hi! Thanks for sharing this. We try to keep our issues scoped to things that are more discrete so I'm going to close this issue, but we'll check these out for inspiration. It's fun to see how others would take the app in various different directions.
