### ISSUE TITLE
"Open in Command Prompt" should be "Open in PowerShell" on Windows

### ISSUE THREAD

**Issue by wbt** [desktop/desktop#12720]
Right-clicking on a repo in the repo list on GitHub Desktop for Windows 10, there is an option to "Open in Command Prompt." 
Instead of or in addition to that, "Open in PowerShell" would be much more useful.

**Comment by tsvetilian-ty** [comment]
Hey @wbt 
"Open in ...." menu item base its value on the shell you picked from the options.

![image](https://user-images.githubusercontent.com/9341546/128090411-8cff4a09-8d92-4e65-9732-8355efb8cbd5.png)

**Comment by billygriffin** [comment]
Since @tsvetilian-ty answered this, I'm going to close it. Thanks so much!
