### ISSUE TITLE
Allow multiple instances or multiple windows

### ISSUE THREAD

**Issue by dave-murray** [desktop/desktop#12724]
### Describe the feature or problem you’d like to solve

I have several projects that involve multiple Git repos (e.g. mobile app + backend). It would be useful to be able to view both repos at the same time but GitHub Desktop is a single instance application.

### Proposed solution

Allow multiple instances of GitHub Desktop to run at the same time or allow multiple repos to be opened in seperate GitHub Desktop windows.

**Comment by steveward** [comment]
Thanks for the feedback @dave-murray! We are tracking this in https://github.com/desktop/desktop/issues/3606 so I am going to close this out. You can follow along there for updates.

**Comment by Viznity** [comment]
+1
