### ISSUE TITLE
Ability to change the origin of an empty local branch.

### ISSUE THREAD

**Issue by yannickrondeau** [desktop/desktop#12729]
### Describe the feature or problem you’d like to solve

Whenever a new branch is created, its origin commit sha serve as its origin point. There is currently no way to update this origin commit since GitHub Desktop lacks the `reset -- hard` option and the rebase button isn't available if there isn't any commit in the actual branch.

I am not sure if this makes any sens in a normal situation, but could help to prevent starting a new branch already late.

### Proposed solution

I see two solutions to the problem.

1. The GUI could either allow the user to reset the current branch to any other commit _(already discussed in #8153)_.
2. The GUI could allow a user to rebase a branch onto another one when there isn't any commit in the current branch (new branch).

### Additional context

Concrete example : 
* John creates a `develop` branch with `commit A`.
* Jane creates a new branch `featureA` based onto `develop`.
* John commits a new change `commit B` onto `develop`
* Jane's `featureA` branch now has 1 commit behind.
_(She either needs to merge or delete and recreate her branch.)_

_The merge here could make sens; however, it seems a bit odd to me since there isn't anything started yet._

**Comment by steveward** [comment]
@YannickRondeau thanks for the issue.

I don't this is a workflow we would plan to support, since it's common to create feature/topic branches and continue to merge changes into that branch from main/development as needed. 

Is the issue here that you are not wanting to create merge commits?

**Comment by yannickrondeau** [comment]
@steveward I don't think there is an issue at all. I was just used to this feature in other Git GUI. Having a branch that start with 1-2 merge commit before any actual feature commit was a bit confusing for me at first, but I guess that I'll get use to it.

Thanks,
