### ISSUE TITLE
Desktop doesn't fetch from upstream

### ISSUE THREAD

**Issue by desmondga** [desktop/desktop#12731]
### Describe the bug
Hi there,

My class has been having issues with getting data from upstream via GitHub Desktop. When there are changes to origin, fetching says it is getting from upstream and when it is done there are no changes seen. But when we do it via commandline

```
git checkout master
git fetch upstream
git merge upstream/master
The changes show.
```

We have checked using git remote -v and we get this:

```
origin   https://blah.com/xxx/homework_submission.git (fetch)
origin  https://blah.com/xxx/homework_submission.git (push)
upstream   https://blah.com/yyy/homework_submission.git (fetch)
upstream   https://blah.com/yyy/homework_submission.git (push)
```

This is the first time I’ve encountered this issue, so I’m not sure what is wrong.
We are all using the latest version of Desktop and all of us are have having this issue

Can someone help?

### Version & OS

Windows and Mac.

### Steps to reproduce the behavior

Click on "Fetch Origin". Upon finding new entries in upstream, the "pull" button will appear below

### Actual behavior

There is no "pull" button even though upstream has new inputs.

<img width="857" alt="Screenshot 2021-08-05 at 5 51 34 PM" src="https://user-images.githubusercontent.com/87894112/128330836-efc8cf07-5140-4752-b0e0-fcebac9dd6ce.png">

[2021-08-05.desktop.production.log](https://github.com/desktop/desktop/files/6937699/2021-08-05.desktop.production.log)

**Comment by steveward** [comment]
@desmondga thanks for the issue. If you click the branch list and select `Choose a branch to merge into <current branch>` at the bottom you can select the `upstream/<branch>` from the branch list. GitHub Desktop automatically fetches changes to your branches in the background, so your `upstream` branch will already be up-to-date. 

See [this guide](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/keeping-your-local-repository-in-sync-with-github/syncing-your-branch) for the specific steps. I hope that helps!

**Comment by tang88888888** [comment]
> ### 描述错误
> 嘿，你好
> 
> 我的类一直有问题，通过GitHub桌面从上游获取数据。当原产地发生变化时，取货说它是从上游获取的，完成后不会看到任何变化。但是，当我们通过命令线做到这一点
> 
> ```
> git checkout master
> git fetch upstream
> git merge upstream/master
> The changes show.
> ```
> 
> 我们已经检查了使用git远程-v，我们得到这个：
> 
> ```
> origin   https://blah.com/xxx/homework_submission.git (fetch)
> origin  https://blah.com/xxx/homework_submission.git (push)
> upstream   https://blah.com/yyy/homework_submission.git (fetch)
> upstream   https://blah.com/yyy/homework_submission.git (push)
> ```
> 
> 这是我第一次遇到这个问题，所以我不知道出了什么问题。
> 我们都在使用最新版本的桌面，我们都有这个问题
> 
> 有人能帮忙吗？
> 
> ### 版本和操作系统
> 窗户和Mac。
> 
> ### 复制行为的步骤
> 单击"获取原点"。在上游找到新条目后，"拉"按钮将显示在下面
> 
> ### 实际行为
> 即使上游有新的输入，也没有"拉"按钮。
> 
> <img alt="Screenshot 2021-08-05 at 5 51 34 PM" width="857" src="https://user-images.githubusercontent.com/87894112/128330836-efc8cf07-5140-4752-b0e0-fcebac9dd6ce.png">
> 
> [2021-08-05.桌面.生产.log](https://github.com/desktop/desktop/files/6937699/2021-08-05.desktop.production.log)

**Comment by steveward** [comment]
@tang88888888 are you attempting the same process I shared above?

>If you click the branch list and select `Choose a branch to merge into <current branch>` at the bottom you can select the `upstream/<branch>` from the branch list. 

That will let you merge changes from `upstream`, the same as the steps you are running in the command line. There isn't a combined `Pull upstream` option. GitHub Desktop performs the fetch automatically in the background and then you can perform the merge. I hope that helps!
