### ISSUE TITLE
Windows Github desktop doesn't recognize Visual Studio in the 'Options\Integrations\External editor menu'

### ISSUE THREAD

**Issue by walladallel** [desktop/desktop#12733]
### Describe the bug
Visual Studio is installed on my PC and is my main code editor.
In Github Desktop (Windows) click 'File' >> click 'Options' >> Integrations >> Click the External editor drop-down box
Visual Studio doesn't exist in the drop-down box.

### Version & OS
Github Desktop Version - 2.9.0 (x64)
OS - Windows

**Comment by tsvetilian-ty** [comment]
Hey @walladallel  👋 

Do you use Visual Studio IDE or Visual Studio Code? I don't think that Visual Studio IDE is supported at the moment.

**Comment by walladallel** [comment]
Hi.
IDE I think..
This is what's written in the Help section:
Microsoft Visual Studio Community 2019
Version 16.10.1

**Comment by ghost** [comment]
thank you

**Comment by tsvetilian-ty** [comment]
@walladallel I checked and Visual Studio Community is not supported currently. Alternatively, you can try Visual Studio Code

**Comment by walladallel** [comment]
Thank you very much for the support :)

**Comment by steveward** [comment]
@walladallel you can also follow along in https://github.com/desktop/desktop/issues/7033 where we are tracking broader editor support in GitHub Desktop. I'm going to close this out.

**Comment by WhiteGator** [comment]
do you know if visual studio 2022 is supported or if it ever will be because it is my main code ide and it won't work with github desktop
