### ISSUE TITLE
I'm unable to create a 'new repository' 

### ISSUE THREAD

**Issue by lbferrand** [desktop/desktop#12735]
When trying to create a new repository, the following message appears to bellow the 'path', and if I change the path, nothing changes, the message still appears

![Screen Shot 2021-08-05 at 9 23 38 PM](https://user-images.githubusercontent.com/22985604/128442290-e5444e36-7b68-4515-b04d-5e74cc071d8a.png)

**Comment by lbferrand** [comment]
I believe is taking the 'lferrand' as a repository - which is not

**Comment by Glutexo** [comment]
Experiencing the same behavior here with 2.9.3 (x64) on Windows 10.

1. Create a new repository setting Local Path to _C:\Users\Glutexo\Documents\repos_ and Name to _first_.
2. See that _C:\Users\Glutexo\Documents\repos\first_ was created and is a Git repository. _C:\Users\Glutexo\Documents\repos_ is not a repository.
3. Try to create another repository setting Local Path to aging _C:\Users\Glutexo\Documents\repos_ and Name to _second_.
4. _See the This directory appears to be a Git repository._ message, which is not true. It is not possible to create the repository.

Doing the same with 2.9.3 (x64) on macOS Big Sur 11.6（20G165） works correctly and the bug does not appear.

**Comment by steveward** [comment]
@lbferrand are you still encountering this issue? Is it possible you have nested Git repositories? You can try searching your machine for `.git` to see if there is an accidental repository that was created somewhere.

@Glutexo I wasn't able to reproduce the issue on Windows 10. Are you only storing repositories in your `repos` directory?

**Comment by lbferrand** [comment]
The issue is solved. Thanks! Regards
