### ISSUE TITLE
Github Desktop won't preview changes

### ISSUE THREAD

**Issue by Arrow-x** [desktop/desktop#12732]
### Describe the bug
Github Desktop won't preview changes, it will change the icon the History tab to changed

### Version & OS

Version 2.9.0 (x64)

### Steps to reproduce the behavior

1. make a change to a file 
2. go to changes
3. click on the file that got changed
4. no preview on the right

### Expected behavior

to see the changes committed to the file

### Screenshots

![Capture](https://user-images.githubusercontent.com/3308421/128339984-05126b9b-9ee6-4552-afb6-d580967cd690.PNG)

**Comment by sergiou87** [comment]
Has the file effectively changed? Sometimes that happens when the file permissions change, but not the content. Could that somehow be the case?

**Comment by Arrow-x** [comment]
No, I changed the file manually, and check with external tools (Notepad++)

**Comment by steveward** [comment]
@Arrow-x these could be line-endings changes. What does `git diff <file>` show for one of the changed files? 

See [this article](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings) for some tips on managing line-endings on Windows.

**Comment by Arrow-x** [comment]
@steveward Yep that it the problem thanks!
