### ISSUE TITLE
Suggestion to 'publish branch' for already published branch

### ISSUE THREAD

**Issue by jwest-cox** [desktop/desktop#12753]
### Describe the bug
I am currently working on a branch that I have been working with for several months, and have been committing to, and pushing almost daily.

This afternoon after committing several changes, I noticed the 'push to origin' button actually says 'publish branch'. However, the branch categorically has been published - and even more oddly, despite desktop complaining as per below - my changes have actually been pushed to Github, convincing me this is a desktop client error.

`error: cannot lock ref 'refs/remotes/origin/rig-control': unable to resolve reference 'refs/remotes/origin/rig-control': reference broken
From https://github.com/Cox-Powertrain/pttrig
 ! [new branch]      rig-control -> origin/rig-control  (unable to update local ref)`

This appears to be related to the closed issue #8214.

### Version & OS

Github desktop 2.9.0 (x64)
Windows 10, 64-bit

### Steps to reproduce the behavior

Not sure how to reproduce, as I've never seen this before, nor is it a problem for anything else I'm working on...

### Expected behavior

After committing, I was simply expecting the usual behaviour - to push the update.

### Actual behavior

As above, my changes were committed, and were pushed to Github - despite the client complaining otherwise.
[2021-08-10.desktop.production.log](https://github.com/desktop/desktop/files/6963211/2021-08-10.desktop.production.log)

### Logs

Logfile attached.

**Comment by jwest-cox** [comment]
Note running $ git status in bash, not Github Desktop client, returns the following...

```
Your branch is based on 'origin/rig-control', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)
```

But, said branch absolutely isn't gone... I'm looking at it!

Running the suggested command ran without return, and subsequent $ git status' simply the return the usual:

```
$ git status
On branch rig-control
nothing to commit, working tree clean
```

Github Desktop client however, still refuses to recognise that this branch exists - and a further attempt to push returns the same error message as in the initial post, followed by a return of the 'upstream is gone' error.

**Comment by jwest-cox** [comment]
Further update... removed the local branch using

`$ rm .git/refs/remotes/origin/rig-control`

Followed by

`$ git fetch`

Said button in desktop client has now returned to 'fetch origin', as expected with a clean working tree.

**Comment by steveward** [comment]
@jwest-cox glad to hear you were able to get things working. There were some availability issues earlier today that could have caused problems as well.
