### ISSUE TITLE
Commits with markdown formatted code in message aren't formatted

### ISSUE THREAD

**Issue by mostpinkest** [desktop/desktop#12750]
### Describe the bug
In a commit message, if markdown code format (i.e. \`like this\`) is used, it won't be.

### Version & OS

MacOS Monterey beta 4 
Github Desktop Version 2.9.1-beta2 (x64)

### Steps to reproduce the behavior

1. Find or make a commit with markdown code formatting.
2. Take a good, long look at the backticks and the variable-width font.

### Expected behavior

Format it correctly, just like the website.
<img width="190" alt="Screen Shot 2021-08-10 at 10 34 58 pm" src="https://user-images.githubusercontent.com/81077770/128867692-21dc49b0-b648-4082-a188-13c6cc2c2c4e.png">

### Actual behavior

Unformatted backticks and a variable-width font.
<img width="190" alt="Screen Shot 2021-08-10 at 10 34 37 pm" src="https://user-images.githubusercontent.com/81077770/128867734-22c52603-1e76-48d5-8179-83e4afd4c810.png">

**Comment by steveward** [comment]
Thanks for the issue @Logicer16. At this time we don't have any plans of adding markdown rendering to commit messages, but I'll label this as an enhancement for future consideration.

**Comment by niik** [comment]
I'm going to close this in favor of https://github.com/desktop/desktop/issues/18104 which contains more detail around why this isn't working today and what might be done to support it.
