### ISSUE TITLE
youtube.com/watch?v=9h9eZWR5vGo

### ISSUE THREAD

**Issue by imgod123456** [desktop/desktop#12755]
### Describe the feature or problem you’d like to solve

Write a clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

Please share how this will it benefit Desktop and its users?

### Additional context

Please include any other context, like screenshots or mockups, if applicable.

**Comment by imgod123456** [comment]
@imgod123456

**Comment by Dino1981** [comment]
#12751 

> @imgod123456
