### ISSUE TITLE
Open with Xcode beta

### ISSUE THREAD

**Issue by orihpt** [desktop/desktop#12751]
Hello fellow mates,
In GitHub Desktop there is an option to open the project with Xcode, but when Xcode Beta is installed I get this prompt:

<img width="464" alt="צילום מסך 2021-08-10 ב-17 13 21" src="https://user-images.githubusercontent.com/52978143/128882716-1902143f-7862-4ad5-95d7-cba169fad794.png">

When I tap Open Preferences:

<img width="617" alt="צילום מסך 2021-08-10 ב-17 18 13" src="https://user-images.githubusercontent.com/52978143/128883522-0886ff75-116d-4a61-8909-2c02ea7d2d2f.png">

I expected it to recognize my Xcode Beta but it didn't. (it's under `/Applications/Xcode-beta.app`)

I would also suggest that if two Xcode are installed - one beta and the other is not - GitHub Desktop will ask us which one to use.

Thank you!

### Version & OS

OS: **macOS Big Sur 11.4**
Machine: _I don't think it matters, but if it does please write a comment and I'll add it._
GitHub Desktop Version: **Version 2.9.0 (x64)**

**Comment by steveward** [comment]
Thanks for the issue @orihpt. Beta/Insider versions of editors need to be added separately to our editor integration (e.g. [Visual Studio Insiders](https://github.com/desktop/desktop/pull/3441). 

You can find the details of how this works along with the supported editors here:

https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md

We happily accept pull requests to integrate new editors.

**Comment by steveward** [comment]
GitHub Desktop now provides support for [adding custom editors](https://docs.github.com/en/desktop/configuring-and-customizing-github-desktop/configuring-a-default-editor-in-github-desktop?platform=windows#configuring-a-custom-editor), so you can add Xcode beta by following the steps in that linked help article. I'm going to close this out.
