### ISSUE TITLE
github desktop is getting slow day by day

### ISSUE THREAD

**Issue by bilalkhld** [desktop/desktop#12769]
### Describe the bug
Using the latest version of GitHub, in the start, it was very responsive but now for just single small commit, it takes more than a minute.

### Version & OS
windows 10
Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by sergiou87** [comment]
Hello @bilalkhld! 👋 

Lately we've done some changes to improve commit times, specially on big repositories: #12529 

This change will be out in future releases, but you can test it out now installing a beta of GitHub Desktop: https://github.com/desktop/desktop#beta-channel

Could you give it a try and let me know if the experience is better? Thanks!
