### ISSUE TITLE
Dependabot's avatar is not shown

### ISSUE THREAD

**Issue by filiptronicek** [desktop/desktop#12766]
### Describe the bug
When I look into the history of my repo in GitHub Desktop, commits generated by dependabot (and maybe other bots) have the default GitHub avatar beside them.

### Version & OS
```
OS: Windows 11
GH Desktop: Version 2.9.1-beta2 (x64)
```

### Steps to reproduce the behavior
1. Go to a repo (any with Dependabot will do)
2. Go to the commit history
3. Find a Dependabot commit

### Expected behavior
It would be better to include the Dependabot's profile picture or avatar in the history, as seeing commits done by this avatar-less user looks like it is a real user with a GitHub profile.

### Actual behavior
This avatar is shown for the dependabot user:
![avatar](https://avatars.githubusercontent.com/u/49699333?s=64)

### Screenshots
![image](https://user-images.githubusercontent.com/29888641/129224491-1d1b3ac4-a00f-46cf-8b5c-7c3be5cf3532.png)

**Comment by steveward** [comment]
Thanks for the issue @filiptronicek! In this case the specific email address that Dependabot uses is `49699333+dependabot[bot]@users.noreply.github.com`. We have regex in place to parse the user id from these emails:

https://github.com/desktop/desktop/blob/f3294859501e4c622e5317161440705f62fa1b24/app/src/ui/lib/avatar.tsx#L52

It looks like we're parsing that id and then grabbing the URL from here:

https://avatars.githubusercontent.com/u/49699333

That returns the avatar you are seeing. But [the API](https://api.github.com/users/dependabot%5Bbot%5D) is actually returning the avatar value as https://avatars.githubusercontent.com/in/29110, which shows the correct avatar. I'll label this as a bug for us to look into to see if we can handle bot users better.

**Comment by Darahi** [comment]
- [ ] r
