### ISSUE TITLE
Rename local master branch to main when such action has been detected on origin

### ISSUE THREAD

**Issue by wojtekmaj** [desktop/desktop#12768]
### Describe the feature or problem you’d like to solve

Renaming master branch to main is a popular trend right now. However, renaming it in GitHub desktop isn't handled.

### Proposed solution

* Detect when `HEAD` on origin is equal to `refs/heads/main` e.g. by using `git ls-remote`
* Display a message, like:
    ```
    The default branch has been renamed!
    master is now named main

    Would you like to rename local master branch to main?
    [ Cancel ] [ Rename ]
    ```

Please share how this will it benefit Desktop and its users?

* Saves them from running
    ```
    git branch -m master main
    git fetch origin
    git branch -u origin/main main
    git remote set-head origin -a
    ```
   which I believe a considerable chunk of userbase that only used Git by UI may find a little scary and cryptic.

**Comment by Mrlinkwii** [comment]
i think this is due changing main to master is an optional thing

**Comment by steveward** [comment]
Thanks for the issue @wojtekmaj. You are correct that we don't automatically update the local branch to match the remote, but it's easy to quickly rename the branch in GitHub Desktop by right-clicking on the branch and selecting `Rename`. The work for this was done in https://github.com/desktop/desktop/pull/10415. I'm going to close this out.

**Comment by wojtekmaj** [comment]
Will it change the origin tracking branch automatically as well?
