### ISSUE TITLE
Authentication Errors - can't clone repos

### ISSUE THREAD

**Issue by netabe-tr** [desktop/desktop#12774]
### Describe the bug

In the github desktop app each time I try to clone a repository by URL it requires my username and password - when I enter them it tries to connect but fails and show me the authentication failed window. 

### Version & OS

Version 2.9.0 (x64).
windows 10.

### Steps to reproduce the behavior

1. Go to 'File'
2. Click on 'Clone repository'
3. Click on 'URL'
4. Enter URL and path 
5. Click on 'Clone'
6. Enter the username and password
7. Click on 'Save and Clone'
8. See error
9. Try again
10. See same error 

### Expected behavior

The clone will work and the app will recognize my user

### Actual behavior

The clone does not work and the app does not recognize my user

### Screenshots

![image](https://user-images.githubusercontent.com/88964000/129475371-4f3d9b14-4e34-4cca-bdf3-91448fac9051.png)

### Logs

[2021-08-15.desktop.production.log](https://github.com/desktop/desktop/files/6987944/2021-08-15.desktop.production.log)
[2021-08-12.desktop.production.log](https://github.com/desktop/desktop/files/6987945/2021-08-12.desktop.production.log)

**Comment by pomnt** [comment]
[2021-08-15.desktop.production.log](https://github.com/desktop/desktop/files/6988320/2021-08-15.desktop.production.log)

**Comment by NicholasWilliamFreeman** [comment]
likewise that and im not sur but all my files get tossed onto the desk top

**Comment by steveward** [comment]
@NicholasWilliamFreeman it looks like your organization needs to authorize GitHub Desktop:

```
remote: The organization has enabled or enforced SAML SSO. To access
remote: this repository, you must re-authorize the OAuth Application `GitHub Desktop`.
```

You can see how to do that here:

https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-your-membership-in-organizations/requesting-organization-approval-for-oauth-apps

I'm going to close this out, but let me know if you have any issues after getting GitHub Desktop approved.
