### ISSUE TITLE
Create Pull Request button is disabled

### ISSUE THREAD

**Issue by troys-code** [desktop/desktop#12773]
### Describe the bug
The Branch > "Create Pull Request" menu item is disabled.

### Version & OS

Desktop: Version 2.9.0 (arm64)
OS: macOS Big Sur 11.5.1

### Steps to reproduce the behavior

1. Open your private repo
2. Click on Branch
3. The Create Pull Request menu item is disabled

### Expected behavior

The Create Pull Request button should be available for all repositories that support it.

### Actual behavior

The Create Pull Request button is only enabled for repositories that are hosted at github.com. The text on this button is misleading.

### Screenshots

![Screen Shot 2021-08-14 at 12 48 20](https://user-images.githubusercontent.com/13446008/129443972-65c6f9fe-7f88-43bd-859a-a6b0d8c01738.png)

### Additional context

I want to use this app for all the projects that I contribute to, some of which are hosted elsewhere.

About 23% of companies host their code on GitHub.
Source: https://www.datanyze.com/market-share/source-code-management--315

Any GitHub specific features should be labelled as such. For example, "Compare on GitHub" is aptly named.

I would be happy to contribute and maintain the behaviour of "Create Pull Request" for projects hosted on GitLab.

**Comment by Mrlinkwii** [comment]
it seems to be working here,  is their  any changes on the  said branch and  is the said branch pushed to github ?

**Comment by steveward** [comment]
Thanks for the feedback @troy-lamerton. Supporting pull requests on GitLab would require building out authentication as well, and at this time we do not have any plans to implement this into GitHub Desktop.

This was previously discussed in https://github.com/desktop/desktop/issues/7791#issuecomment-501788755:

>While we intend to continue basic support for repos from other sources, our primary goal is for the GitHub <-> GitHub Desktop experience to shine. We don't intend to support publishing local repos to other hosts *from Desktop* n the near term.

I'm going to close this out, but I'll make a note for our next team meeting to discuss the wording.
