### ISSUE TITLE
Github authorization is not working.

### ISSUE THREAD

**Issue by faye-a** [desktop/desktop#12772]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.
Fetched my main branch to up to date. Then clicked push. It should automatically push every changed file. 

### Actual behavior
An error message popped up saying that authorization failed when trying to push my main branch to my remote repository.

Write a clear and concise description of what actually happened.
I opened the desktop app. Committed the new files created to main branch. While comitting, I pressed fetch button. Then, the authorization error message popped up. The commit finished. When trying to push it, the same pop up keeps appearing. 

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by faye-a** [comment]
Worked just as I posted it.

**Comment by bleble8** [comment]
sob., 14 sie 2021, 01:05 użytkownik faye-a ***@***.***>
napisał:
