### ISSUE TITLE
error: RPC failed; curl 55 Send failure: Connection was aborted

### ISSUE THREAD

**Issue by AnjaniGourisaria** [desktop/desktop#12770]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

Enumerating objects: 129, done.
Counting objects: 100% (129/129), done.
Delta compression using up to 8 threads
Compressing objects: 100% (126/126), done.
error: RPC failed; curl 55 Send failure: Connection was aborted
fatal: the remote end hung up unexpectedly
Writing objects: 100% (129/129), 73.17 MiB | 2.14 MiB/s, done.
Total 129 (delta 12), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

**Comment by steveward** [comment]
Thanks for the issue @AnjaniGourisaria. In the future please don't add the entire message to the issue title. 

A couple of questions to help debug this:

1. Are there any large files in this repository that could be causing this?
2. Are you encountering this error in only this specific repository?

It'd also be helpful if you could upload a log file. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by AnjaniGourisaria** [comment]
File size is 445mb fresh repo 
2021-08-17T21:43:49.512Z - info: [ui] [AppStore] loading 1 repositories from store
2021-08-17T21:43:49.514Z - info: [ui] [AppStore] found account: AnjaniGourisaria (AnjaniGourisaria)
2021-08-17T21:43:50.030Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-08-17T21:43:50.681Z - info: [ui] launching: 2.9.0 (Windows 10.0.22000)
2021-08-17T21:43:50.682Z - info: [ui] execPath: 'C:\Users\DELL\AppData\Local\GitHubDesktop\app-2.9.0\GitHubDesktop.exe'
2021-08-17T21:43:52.903Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.929s)
2021-08-17T21:43:54.278Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 4.704s)
2021-08-17T21:43:54.443Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 4.246s)
2021-08-17T21:43:57.291Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 4.072s)
2021-08-17T21:44:17.858Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Tryhackme - AnjaniGourisaria (has token)
2021-08-17T21:44:20.996Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 4.866s)
2021-08-17T21:44:55.962Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin main --set-upstream --progress (took 37.885s)
2021-08-17T21:44:55.984Z - error: [ui] `git -c credential.helper= -c protocol.version=2 push origin main --set-upstream --progress` exited with an unexpected code: 1.
stderr:
Enumerating objects: 129, done.
Counting objects:   0% (1/129)
Counting objects:   1% (2/129)
Counting objects:   2% (3/129)
Counting objects:   3% (4/129)
Counting objects:   4% (6/129)
Counting objects:   5% (7/129)
Counting objects:   6% (8/129)
Counting objects:   7% (10/129)
Counting objects:   8% (11/129)
Counting objects:   9% (12/129)
Counting objects:  10% (13/129)
Counting objects:  11% (15/129)
Counting objects:  12% (16/129)
Counting objects:  13% (17/129)
Counting objects:  14% (19/129)
Counting objects:  15% (20/129)
Counting objects:  16% (21/129)
Counting objects:  17% (22/129)
Counting objects:  18% (24/129)
Counting objects:  19% (25/129)
Counting objects:  20% (26/129)
Counting objects:  21% (28/129)
Counting objects:  22% (29/129)
Counting objects:  23% (30/129)
Counting objects:  24% (31/129)
Counting objects:  25% (33/129)
Counting objects:  26% (34/129)
Counting objects:  27% (35/129)
Counting objects:  28% (37/129)
Counting objects:  29% (38/129)
Counting objects:  30% (39/129)
Counting objects:  31% (40/129)
Counting objects:  32% (42/129)
Counting objects:  33% (43/129)
Counting objects:  34% (44/129)
Counting objects:  35% (46/129)
Counting objects:  36% (47/129)
Counting objects:  37% (48/129)
Counting objects:  38% (50/129)
Counting objects:  39% (51/129)
Counting objects:  40% (52/129)
Counting objects:  41% (53/129)
Counting objects:  42% (55/129)
Counting objects:  43% (56/129)
Counting objects:  44% (57/129)
Counting objects:  45% (59/129)
Counting objects:  46% (60/129)
Counting objects:  47% (61/129)
Counting objects:  48% (62/129)
Counting objects:  49% (64/129)
Counting objects:  50% (65/129)
Counting objects:  51% (66/129)
Counting objects:  52% (68/129)
Counting objects:  53% (69/129)
Counting objects:  54% (70/129)
Counting objects:  55% (71/129)
Counting objects:  56% (73/129)
Counting objects:  57% (74/129)
Counting objects:  58% (75/129)
Counting objects:  59% (77/129)
Counting objects:  60% (78/129)
Counting objects:  61% (79/129)
Counting objects:  62% (80/129)
Counting objects:  63% (82/129)
Counting objects:  64% (83/129)
Counting objects:  65% (84/129)
Counting objects:  66% (86/129)
Counting objects:  67% (87/129)
Counting objects:  68% (88/129)
Counting objects:  69% (90/129)
Counting objects:  70% (91/129)
Counting objects:  71% (92/129)
Counting objects:  72% (93/129)
Counting objects:  73% (95/129)
Counting objects:  74% (96/129)
Counting objects:  75% (97/129)
Counting objects:  76% (99/129)
Counting objects:  77% (100/129)
Counting objects:  78% (101/129)
Counting objects:  79% (102/129)
Counting objects:  80% (104/129)
Counting objects:  81% (105/129)
Counting objects:  82% (106/129)
Counting objects:  83% (108/129)
Counting objects:  84% (109/129)
Counting objects:  85% (110/129)
Counting objects:  86% (111/129)
Counting objects:  87% (113/129)
Counting objects:  88% (114/129)
Counting objects:  89% (115/129)
Counting objects:  90% (117/129)
Counting objects:  91% (118/129)
Counting objects:  92% (119/129)
Counting objects:  93% (120/129)
Counting objects:  94% (122/129)
Counting objects:  95% (123/129)
Counting objects:  96% (124/129)
Counting objects:  97% (126/129)
Counting objects:  98% (127/129)
Counting objects:  99% (128/129)
Counting objects: 100% (129/129)
Counting objects: 100% (129/129), done.
Delta compression using up to 8 threads
Compressing objects:   0% (1/126)
Compressing objects:   1% (2/126)
Compressing objects:   2% (3/126)
Compressing objects:   3% (4/126)
Compressing objects:   4% (6/126)
Compressing objects:   5% (7/126)
Compressing objects:   6% (8/126)
Compressing objects:   7% (9/126)
Compressing objects:   8% (11/126)
Compressing objects:   9% (12/126)
Compressing objects:  10% (13/126)
Compressing objects:  11% (14/126)
Compressing objects:  12% (16/126)
Compressing objects:  13% (17/126)
Compressing objects:  14% (18/126)
Compressing objects:  15% (19/126)
Compressing objects:  16% (21/126)
Compressing objects:  17% (22/126)
Compressing objects:  18% (23/126)
Compressing objects:  19% (24/126)
Compressing objects:  20% (26/126)
Compressing objects:  21% (27/126)
Compressing objects:  22% (28/126)
Compressing objects:  23% (29/126)
Compressing objects:  24% (31/126)
Compressing objects:  25% (32/126)
Compressing objects:  26% (33/126)
Compressing objects:  27% (35/126)
Compressing objects:  28% (36/126)
Compressing objects:  29% (37/126)
Compressing objects:  30% (38/126)
Compressing objects:  31% (40/126)
Compressing objects:  32% (41/126)
Compressing objects:  33% (42/126)
Compressing objects:  34% (43/126)
Compressing objects:  35% (45/126)
Compressing objects:  36% (46/126)
Compressing objects:  37% (47/126)
Compressing objects:  38% (48/126)
Compressing objects:  39% (50/126)
Compressing objects:  40% (51/126)
Compressing objects:  41% (52/126)
Compressing objects:  42% (53/126)
Compressing objects:  43% (55/126)
Compressing objects:  44% (56/126)
Compressing objects:  45% (57/126)
Compressing objects:  46% (58/126)
Compressing objects:  47% (60/126)
Compressing objects:  48% (61/126)
Compressing objects:  49% (62/126)
Compressing objects:  50% (63/126)
Compressing objects:  51% (65/126)
Compressing objects:  52% (66/126)
Compressing objects:  53% (67/126)
Compressing objects:  54% (69/126)
Compressing objects:  55% (70/126)
Compressing objects:  56% (71/126)
Compressing objects:  57% (72/126)
Compressing objects:  58% (74/126)
Compressing objects:  59% (75/126)
Compressing objects:  60% (76/126)
Compressing objects:  61% (77/126)
Compressing objects:  62% (79/126)
Compressing objects:  63% (80/126)
Compressing objects:  64% (81/126)
Compressing objects:  65% (82/126)
Compressing objects:  66% (84/126)
Compressing objects:  67% (85/126)
Compressing objects:  68% (86/126)
Compressing objects:  69% (87/126)
Compressing objects:  70% (89/126)
Compressing objects:  71% (90/126)
Compressing objects:  72% (91/126)
Compressing objects:  73% (92/126)
Compressing objects:  74% (94/126)
Compressing objects:  75% (95/126)
Compressing objects:  76% (96/126)
Compressing objects:  77% (98/126)
Compressing objects:  78% (99/126)
Compressing objects:  79% (100/126)
Compressing objects:  80% (101/126)
Compressing objects:  81% (103/126)
Compressing objects:  82% (104/126)
Compressing objects:  83% (105/126)
Compressing objects:  84% (106/126)
Compressing objects:  85% (108/126)
Compressing objects:  86% (109/126)
Compressing objects:  87% (110/126)
Compressing objects:  88% (111/126)
Compressing objects:  89% (113/126)
Compressing objects:  90% (114/126)
Compressing objects:  91% (115/126)
Compressing objects:  92% (116/126)
Compressing objects:  92% (117/126)
Compressing objects:  93% (118/126)
Compressing objects:  94% (119/126)
Compressing objects:  95% (120/126)
Compressing objects:  96% (121/126)
Compressing objects:  97% (123/126)
Compressing objects:  98% (124/126)
Compressing objects:  99% (125/126)
Compressing objects: 100% (126/126)
Compressing objects: 100% (126/126), done.
Writing objects:   0% (1/129)
Writing objects:   1% (2/129)
Writing objects:   2% (3/129)
Writing objects:   3% (4/129)
Writing objects:   4% (6/129)
Writing objects:   5% (7/129)
Writing objects:   6% (8/129)
Writing objects:   7% (10/129)
Writing objects:   8% (11/129)
Writing objects:   9% (12/129)
Writing objects:  10% (13/129)
Writing objects:  11% (15/129)
Writing objects:  12% (16/129)
Writing objects:  13% (17/129)
Writing objects:  14% (19/129)
Writing objects:  14% (19/129), 984.00 KiB | 675.00 KiB/s
Writing objects:  14% (19/129), 3.39 MiB | 1.36 MiB/s    
Writing objects:  15% (20/129), 3.39 MiB | 1.36 MiB/s
Writing objects:  16% (21/129), 3.39 MiB | 1.36 MiB/s
Writing objects:  17% (22/129), 3.39 MiB | 1.36 MiB/s
Writing objects:  18% (24/129), 3.39 MiB | 1.36 MiB/s
Writing objects:  19% (25/129), 3.39 MiB | 1.36 MiB/s
Writing objects:  20% (26/129), 3.39 MiB | 1.36 MiB/s
Writing objects:  21% (28/129), 3.39 MiB | 1.36 MiB/s
Writing objects:  22% (29/129), 3.39 MiB | 1.36 MiB/s
Writing objects:  23% (30/129), 3.39 MiB | 1.36 MiB/s
Writing objects:  24% (31/129), 3.39 MiB | 1.36 MiB/s
Writing objects:  24% (31/129), 3.76 MiB | 129.00 KiB/s
error: RPC failed; curl 55 Send failure: Connection was aborted
fatal: the remote end hung up unexpectedly
Writing objects:  24% (31/129), 38.83 MiB | 1.28 MiB/s 
Writing objects:  25% (33/129), 38.83 MiB | 1.28 MiB/s
Writing objects:  26% (34/129), 38.83 MiB | 1.28 MiB/s
Writing objects:  27% (35/129), 38.83 MiB | 1.28 MiB/s
Writing objects:  28% (37/129), 38.83 MiB | 1.28 MiB/s
Writing objects:  29% (38/129), 38.83 MiB | 1.28 MiB/s
Writing objects:  30% (39/129), 38.83 MiB | 1.28 MiB/s
Writing objects:  31% (40/129), 38.83 MiB | 1.28 MiB/s
Writing objects:  32% (42/129), 55.81 MiB | 1.81 MiB/s
Writing objects:  33% (43/129), 55.81 MiB | 1.81 MiB/s
Writing objects:  34% (44/129), 55.81 MiB | 1.81 MiB/s
Writing objects:  36% (47/129), 55.81 MiB | 1.81 MiB/s
Writing objects:  36% (47/129), 58.87 MiB | 1.85 MiB/s
Writing objects:  37% (48/129), 58.87 MiB | 1.85 MiB/s
Writing objects:  38% (50/129), 58.87 MiB | 1.85 MiB/s
Writing objects:  39% (51/129), 58.87 MiB | 1.85 MiB/s
Writing objects:  40% (52/129), 58.87 MiB | 1.85 MiB/s
Writing objects:  41% (53/129), 58.87 MiB | 1.85 MiB/s
Writing objects:  42% (55/129), 58.87 MiB | 1.85 MiB/s
Writing objects:  43% (56/129), 58.87 MiB | 1.85 MiB/s
Writing objects:  44% (57/129), 58.87 MiB | 1.85 MiB/s
Writing objects:  44% (58/129), 58.87 MiB | 1.85 MiB/s
Writing objects:  45% (59/129), 58.87 MiB | 1.85 MiB/s
Writing objects:  47% (61/129), 58.87 MiB | 1.85 MiB/s
Writing objects:  48% (62/129), 58.87 MiB | 1.85 MiB/s
Writing objects:  48% (63/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  49% (64/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  50% (65/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  51% (66/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  52% (68/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  53% (69/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  54% (70/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  55% (71/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  55% (72/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  56% (73/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  57% (74/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  58% (75/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  59% (77/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  60% (78/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  61% (79/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  62% (80/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  63% (82/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  64% (83/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  65% (84/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  66% (86/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  67% (87/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  68% (88/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  70% (91/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  71% (92/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  72% (93/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  73% (95/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  74% (96/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  75% (97/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  76% (99/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  77% (100/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  78% (101/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  79% (102/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  80% (104/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  81% (105/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  82% (106/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  83% (108/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  84% (109/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  85% (110/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  86% (111/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  87% (113/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  88% (114/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  89% (115/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  90% (117/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  91% (118/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  92% (119/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  93% (120/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  94% (122/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  95% (123/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  96% (124/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  97% (126/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  98% (127/129), 66.87 MiB | 1.96 MiB/s
Writing objects:  99% (128/129), 66.87 MiB | 1.96 MiB/s
Writing objects: 100% (129/129), 66.87 MiB | 1.96 MiB/s
Writing objects: 100% (129/129), 73.17 MiB | 2.12 MiB/s, done.
Total 129 (delta 12), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

**Comment by steveward** [comment]
@AnjaniGourisaria unfortunately it looks like this a specific issue with your connection. Do you have reliable upload speed? Are you able to try pushing on a different network to see if it succeeds?
