### ISSUE TITLE
No longer able to do per-line commits

### ISSUE THREAD

**Issue by whalesalad** [desktop/desktop#12771]
Up until very recently I was able to select individual lines and commit them one by one. The UI for this looks to be totally disabled now? Maybe there is a bug?

The issue occurs with both diff display settings: unified/split both have the issue.

Previously one could click these blue boxes to enable/disable them:

<img width="337" alt="Screen Shot 2021-08-13 at 12 35 35 PM" src="https://user-images.githubusercontent.com/5907/129391407-e7374422-1a80-42df-befe-5f67f44d003d.png">

My environment:

- macOS Mojave 10.14.6 (18G9323)
- `Darwin loki 18.7.0 Darwin Kernel Version 18.7.0: Tue Jun 22 19:37:08 PDT 2021; root:xnu-4903.278.70~1/RELEASE_X86_64 x86_64`
- Github Desktop v 2.9.0 x64

**Comment by BEXX22** [comment]
> Up until very recently I was able to select individual lines and commit them one by one. The UI for this looks to be totally disabled now? Maybe there is a bug?
> 
> The issue occurs with both diff display settings: unified/split both have the issue.
> 
> Previously one could click these blue boxes to enable/disable them:
> 
> <img width="337" alt="Screen Shot 2021-08-13 at 12 35 35 PM" src="https://user-images.githubusercontent.com/5907/129391407-e7374422-1a80-42df-befe-5f67f44d003d.png">
> 
> My environment:
> 
> - macOS Mojave 10.14.6 (18G9323)
> - `Darwin loki 18.7.0 Darwin Kernel Version 18.7.0: Tue Jun 22 19:37:08 PDT 2021; root:xnu-4903.278.70~1/RELEASE_X86_64 x86_64`
> - Github Desktop v 2.9.0 x64

**Comment by sergiou87** [comment]
Hello @whalesalad! 👋 

Is it possible that you have "Hide Whitespace Changes" enabled? That feature disables line-level change selection:
![2021-08-16 at 10 02](https://user-images.githubusercontent.com/1083228/129531314-d1f41ad0-c36a-4a8b-9631-ec65aaf062aa.png)

Please let me know if that's not the case and we'll investigate 😄
