### ISSUE TITLE
♧◇♡♤

### ISSUE THREAD

**Issue by Brother1989** [desktop/desktop#12776]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

__

**Comment by NicholasWilliamFreeman** [comment]
can of shit [worms](hooked)security shut down an god knows what it may or may not hav got had to lock screen so will see. I could just be over thinking it but or not thinking about it enough.
