### ISSUE TITLE
Allow multiple instances

### ISSUE THREAD

**Issue by felipedrumond** [desktop/desktop#12780]
My workflow includes working with micro services, which is very common nowadays. That means I change multiple repositories very often and at the same time. I lack the ability to run multiple instances of GitHub Desktop and see what code changes I'm about to check in.

### Proposed solution

Add a option on File/Options/Advanced to enable GitHub Desktop to open multiple instances.

**Comment by steveward** [comment]
Thanks for the feedback @felipedrumond! We are tracking this in https://github.com/desktop/desktop/issues/3606 so I am going to close this out. You can follow along there for updates.

**Comment by Viznity** [comment]
Any update?
