### ISSUE TITLE
Push to GitHub repository fails with "error: RPC failed; curl 55 Send failure: Connection was aborted"

### ISSUE THREAD

**Issue by DuhallowGreyGeek** [desktop/desktop#12784]
### Describe the bug
When I attempt to Push 2 commits to my remote repository the update fails with a pop-up error window.

### Version & OS
GitHub Desktop: Version 2.9.0 (x64) - "You have the latest version (last checked about 13 minutes ago),"
Windows 10, fully up to date 

### Steps to reproduce the behavior

Connected to my repository: Clio_History_GitHub_20191008, Branch: Tar_1916_on
1. On main screen, Commit two changes to branch ""
2. Click on 'Push Origin'
3. Push update on remote repository seems to work as normal and then fails with the error screen in attachment: GitHubError_20210817.jpg

### Expected behavior

I expected the Push to complete as usual.

### Actual behavior

The Push failed with the error in the Screenshot
### Screenshots

See: GitHubError_20210817.jpg
### Logs

Logs attached:
Problem first encountered yesterday 16th August 2021.
I have included logs for
16th August 2021
17th August 2021 - I can see the Error messages from the pop-up towards the end of the log.

### Additional context
After I first encountered the problem, I backed out a number of updates in a single commit and then tried committing them and pushing them to the repository individually. Some small text files worked as normal. I waited overnight and did a little research on the internet and the GitHub documentation. I didn't find anything obvious. 
The problem _may_ be associated with the two files: 
JG_Chqs_Chapter_1923.docx (0.97 MB) and JG_Chqs_Chapter_1923.pdf (1.00 MB)
"docx" is an MS Word file and "pdf" is the same content. GitHub considers both to be binary files. I've made updates containing other, larger binaries in the past.
[2021-08-16.desktop.production.log](https://github.com/desktop/desktop/files/6999868/2021-08-16.desktop.production.log)
[2021-08-17.desktop.production.log](https://github.com/desktop/desktop/files/6999869/2021-08-17.desktop.production.log)
![GitHubError_20210817](https://user-images.githubusercontent.com/10222701/129724777-1ef2cfe5-9143-4cd5-ade2-fd29be9cf358.jpg)

I 've removed the two files because the content is "private" but it's not particularly sensitive (ancient family history).

**Comment by steveward** [comment]
@DuhallowGreyGeek thanks for the report. Unfortunately these cURL errors can be caused by a number of items. I have a couple of questions that may help narrow things down:

1. Are you having this issue in only one specific repository, or in multiple repositories?
2. Are you behind a firewall/proxy or running any antivirus software that could be interfering with your connection?

Sometimes running `git config http.postBuffer 524288000` can resolve these, and it may be worth trying that to see if it gets things working for you.

**Comment by DuhallowGreyGeek** [comment]
@steveward Thanks for your response. I'm only using one repository actively at present. Give me a few hours and I'll try to answer your questions.

**Comment by DuhallowGreyGeek** [comment]
Hello @steveward, I've run some tests. I've attached the log file, which I think shows everything I've done.

**Are you having this issue in only one specific repository, or in multiple repositories?**
I tried with another repository. "Gray":
- I started with committing a small test file and then the pdf and the docx files. I used the same files that are associated with the problem.
- Everything worked as I expected. I checked the host repository as well.

I moved back to the repository which manifests the problem "History_Github"
- I undid the commits for the pdf and docx files.
- I removed these files from the directory and GitHub Desktop recognised that they were gone ("No changes to be committed")
- I added a small test file, committed and pushed it to the host repository. That worked as expected and the file was present up on the host.
- I added and committed the pdf file (on its own). Pushing an update containing that file caused the problem to manifest. I can see the report at the end of the log file.
  
**Are you behind a firewall/proxy or running any antivirus software that could be interfering with your connection?**
Yes, I've got Windows Defender and am running an Antivirus package, but before we investigate that route, I'd like to try the "postBuffer" thing, but I will need some help.

**Sometimes running git config http.postBuffer 524288000**
I found the directory where GitHubDesk is installed but I can't run the command
> C:\Users\user\AppData\Local\GitHubDesktop>git
> 'git' is not recognized as an internal or external command,
> operable program or batch file.

I can launch GitHubDesktop
> C:\Users\user\AppData\Local\GitHubDesktop>githubdesktop

Where do I run the "git config http.postBuffer 524288000" command, or do I need to add something (what) on the end of my PATH variable?

I'm a bit rusty at this sort of thing. I don't remember when I last used a command prompt seriously, and Windows 10 seems a bit "different".

Thanks.

[2021-08-18.desktop.production.log](https://github.com/desktop/desktop/files/7007100/2021-08-18.desktop.production.log)

**Comment by steveward** [comment]
@DuhallowGreyGeek you will need to install Git for Windows:

https://git-scm.com/download/win

During the installation process you can add Git to your PATH to allow you to run it from the command prompt. You can launch Git from GitHub Desktop by going to `Repository` > `Open in <command_line>`.

**Comment by DuhallowGreyGeek** [comment]
@steveward Unfortunately that didn't work.
I downloaded and installed git.
Ran the command (which seemed to work)

> C:\Users\user\Documents\Clio_History_GitHub_20191008>git config http.postBuffer 524288000
> C:\Users\user\Documents\Clio_History_GitHub_20191008>

Opened GitHub Desktop and Pushed the update.
Same error message as before. The relevant bits seem to be in the log file, after time 15:08
[2021-08-18.desktop.production.log](https://github.com/desktop/desktop/files/7008327/2021-08-18.desktop.production.log)

What do you suggest next?

**Comment by steveward** [comment]
Thanks for sharing that. It looks like you're hitting a new error now:

```
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
```

If you are continuing to have issues with this specific repository you could try switching this repository to use SSH instead of HTTPS. GitHub Desktop just shipped improved SSH support. You can read how to set up a new SSH key here if you don't have an existing one:

https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

Once you've done that you can change the remote in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. You'll need to change the remote to `git@github.com:<user>/<repo>.git`. Let me know if that helps.

**Comment by DuhallowGreyGeek** [comment]
OK. I'll try doing that. It will take me a little while because I have other things to do as well.

**Comment by DuhallowGreyGeek** [comment]
@steveward Hello, I'm afraid that didn't work. I went through the procedure of creating and adding a new SSH key (very carefully, this is unfamiliar territory for me) and when I try and Push a committed update, I get a pop-up with the following message:
```
Authentication failed. Some common reasons include:
- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.
```
My interpretation of this is that _this_ problem is authentication with ssh and nothing to do with the GitHub update. 

- I think I followed the instructions for setting up and installing the keys properly (nothing surprising happened anyway)
- I closed GitHub Desktop and re-launched it.
- I logged out of Desktop and logged back in again. That made me go through an additional security step where I authorised the browser to launch GitHub Desktop.
- Still the same (new) result.

Any further suggestions?

**Comment by steveward** [comment]
@DuhallowGreyGeek can you run `ssh -v git@github.com` from the command line and let me know what that returns?

**Comment by DuhallowGreyGeek** [comment]
@steveward Here you are:
```
Microsoft Windows [Version 10.0.19043.1165]
(c) Microsoft Corporation. All rights reserved.

C:\Users\user>ssh -v git@github.com
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
debug1: Connecting to github.com [140.82.121.4] port 22.
debug1: Connection established.
debug1: identity file C:\\Users\\user/.ssh/id_rsa type -1
debug1: identity file C:\\Users\\user/.ssh/id_rsa-cert type -1
debug1: identity file C:\\Users\\user/.ssh/id_dsa type -1
debug1: identity file C:\\Users\\user/.ssh/id_dsa-cert type -1
debug1: identity file C:\\Users\\user/.ssh/id_ecdsa type -1
debug1: identity file C:\\Users\\user/.ssh/id_ecdsa-cert type -1
debug1: identity file C:\\Users\\user/.ssh/id_ed25519 type 3
debug1: identity file C:\\Users\\user/.ssh/id_ed25519-cert type -1
debug1: identity file C:\\Users\\user/.ssh/id_xmss type -1
debug1: identity file C:\\Users\\user/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.1
debug1: Remote protocol version 2.0, remote software version babeld-91825f0b
debug1: no match: babeld-91825f0b
debug1: Authenticating to github.com:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-rsa SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8
debug1: Host 'github.com' is known and matches the RSA host key.
debug1: Found key in C:\\Users\\user/.ssh/known_hosts:1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
debug1: Will attempt key: C:\\Users\\user/.ssh/id_rsa
debug1: Will attempt key: C:\\Users\\user/.ssh/id_dsa
debug1: Will attempt key: C:\\Users\\user/.ssh/id_ecdsa
debug1: Will attempt key: C:\\Users\\user/.ssh/id_ed25519 ED25519 SHA256:DgaU46BohOynuFrF81TeqG9yPZtpir4IKsQo5nCno10
debug1: Will attempt key: C:\\Users\\user/.ssh/id_xmss
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: C:\\Users\\user/.ssh/id_rsa
debug1: Trying private key: C:\\Users\\user/.ssh/id_dsa
debug1: Trying private key: C:\\Users\\user/.ssh/id_ecdsa
debug1: Offering public key: C:\\Users\\user/.ssh/id_ed25519 ED25519 SHA256:DgaU46BohOynuFrF81TeqG9yPZtpir4IKsQo5nCno10
debug1: Authentications that can continue: publickey
debug1: Trying private key: C:\\Users\\user/.ssh/id_xmss
debug1: No more authentication methods to try.
git@github.com: Permission denied (publickey).

C:\Users\user>
```

It's all greek to me I'm afraid.

**Comment by steveward** [comment]
@DuhallowGreyGeek did you start `ssh-agent` and add your key? These are the specific commands:

`eval "$(ssh-agent -s)"`
`ssh-add ~/.ssh/id_ed25519`

**Comment by DuhallowGreyGeek** [comment]
@steveward Progress of a sort. The problem does seem to be in this area. It's made harder because I am not familiar with what I am doing.
I tried the first command:
```
Microsoft Windows [Version 10.0.19043.1165]
(c) Microsoft Corporation. All rights reserved.

C:\Users\user>eval "$(ssh-agent -s)"
'eval' is not recognized as an internal or external command,
operable program or batch file.
```
OK. So Windows doesn't recognise "eval". I dug around a bit and found out how to start OpenSSH in Windows Control Panel. I've done that and Windows says the service is running. I've set the properties of the server to start automatically. I've also started the SSH Authentication Agent as that seemed like a likely candidate too.
![OpenSSH_Agents](https://user-images.githubusercontent.com/10222701/131834628-981e0e0d-7f36-4b15-b9cb-a6aaa0eac998.jpg)

Following both of those I get the same result: 
```
C:\Users\user>ssh-add ~/.ssh/id_ed25519
Error connecting to agent: No such file or directory
```
Please bear in mind that although I have an idea what is going on in principle, I don't understand the details.

- Should I be invoking these commands from the windows/dos command prompt or should I be doing it from somewhere else?
- And do I need to be in a specific directory when invoking them?

Thanks.

**Comment by steveward** [comment]
>Should I be invoking these commands from the windows/dos command prompt or should I be doing it from somewhere else?

Generally we recommend installing [Git for Windows](https://git-scm.com/download/win) to use alongside GitHub Desktop since it provides the full suite of Git commands. Once you install it and add Git to your PATH you can also run commands in PowerShell/CMD/etc.

>And do I need to be in a specific directory when invoking them? 

Nope!

**Comment by DuhallowGreyGeek** [comment]
Hi @steveward  I've re-installed git. And git-bash.
Following that I ran the command to start the agent. That worked and returned a pid.
Then I ran the command to add the key. That asked for a passphrase which I supplied and then responded "identity added".
Then I ran the ssh command to connect to git. That failed as before.
record of what happened below:
 
```
user@Lenovouser MINGW64 ~
$ eval "$(ssh-agent -s)"
Agent pid 131

user@Lenovouser MINGW64 ~
$ ssh-add ~/.ssh/id_ed25519
Enter passphrase for /c/Users/user/.ssh/id_ed25519:
Identity added: /c/Users/user/.ssh/id_ed25519 (duhallowhypnosis@gmail.com)

user@Lenovouser MINGW64 ~
$ ssh -v git@github.com
OpenSSH_8.7p1, OpenSSL 1.1.1k  25 Mar 2021
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to github.com [140.82.121.3] port 22.
debug1: Connection established.
debug1: identity file /c/Users/user/.ssh/id_rsa type -1
debug1: identity file /c/Users/user/.ssh/id_rsa-cert type -1
debug1: identity file /c/Users/user/.ssh/id_dsa type -1
debug1: identity file /c/Users/user/.ssh/id_dsa-cert type -1
debug1: identity file /c/Users/user/.ssh/id_ecdsa type -1
debug1: identity file /c/Users/user/.ssh/id_ecdsa-cert type -1
debug1: identity file /c/Users/user/.ssh/id_ecdsa_sk type -1
debug1: identity file /c/Users/user/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /c/Users/user/.ssh/id_ed25519 type 3
debug1: identity file /c/Users/user/.ssh/id_ed25519-cert type -1
debug1: identity file /c/Users/user/.ssh/id_ed25519_sk type -1
debug1: identity file /c/Users/user/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /c/Users/user/.ssh/id_xmss type -1
debug1: identity file /c/Users/user/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.7
debug1: Remote protocol version 2.0, remote software version babeld-e995f6d1
debug1: compat_banner: no match: babeld-e995f6d1
debug1: Authenticating to github.com:22 as 'git'
debug1: load_hostkeys: fopen /c/Users/user/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-rsa SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8
debug1: load_hostkeys: fopen /c/Users/user/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: Host 'github.com' is known and matches the RSA host key.
debug1: Found key in /c/Users/user/.ssh/known_hosts:1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /c/Users/user/.ssh/id_ed25519 ED25519 SHA256:DgaU46BohOynuFrF81TeqG9yPZtpir4IKsQo5nCno10 agent
debug1: Will attempt key: /c/Users/user/.ssh/id_rsa
debug1: Will attempt key: /c/Users/user/.ssh/id_dsa
debug1: Will attempt key: /c/Users/user/.ssh/id_ecdsa
debug1: Will attempt key: /c/Users/user/.ssh/id_ecdsa_sk
debug1: Will attempt key: /c/Users/user/.ssh/id_ed25519_sk
debug1: Will attempt key: /c/Users/user/.ssh/id_xmss
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /c/Users/user/.ssh/id_ed25519 ED25519 SHA256:DgaU46BohOynuFrF81TeqG9yPZtpir4IKsQo5nCno10 agent
debug1: Authentications that can continue: publickey
debug1: Trying private key: /c/Users/user/.ssh/id_rsa
debug1: Trying private key: /c/Users/user/.ssh/id_dsa
debug1: Trying private key: /c/Users/user/.ssh/id_ecdsa
debug1: Trying private key: /c/Users/user/.ssh/id_ecdsa_sk
debug1: Trying private key: /c/Users/user/.ssh/id_ed25519_sk
debug1: Trying private key: /c/Users/user/.ssh/id_xmss
debug1: No more authentication methods to try.
git@github.com: Permission denied (publickey).

user@Lenovouser MINGW64 ~
$
```
What now?

**Comment by steveward** [comment]
@DuhallowGreyGeek apologies for the delay. here. I'm not seeing the public key under your GitHub account. You need to make sure you follow [this article](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) to ensure your public key has been added. Let me know if that helps!
