### ISSUE TITLE
Hiding whitespace changes should include new line and carriage return characters

### ISSUE THREAD

**Issue by Justin-Frazier** [desktop/desktop#12787]
## The feature or problem to solve

When comparing changes, the option to hide whitespace hides neither a single line split into two nor two lines merged into one. This can hide the significant changes in a file when it has been reformatted in the IDE. (e.g. when a new code standard is applied or a file gets converted between *nix and Windows line endings.)

![ignore_crnl](https://user-images.githubusercontent.com/68287649/129735525-a52fd243-3d59-41e6-8281-e5f7da4c6323.png)

## Proposed solution

1. Include the CR/NL characters by default
2. Add another option to hide new lines under the "Hide whitespace changes" option
![hide new lines](https://user-images.githubusercontent.com/68287649/129736575-f7f819d7-e74f-4270-b8ff-41eeaa963038.png)

**Comment by sergiou87** [comment]
We use the [`-w` parameter](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt--w) of `git diff` to hide the whitespace changes and that's not hiding those changes, sorry 😞

**Comment by Justin-Frazier** [comment]
Seems like you could easily add the [`--ignore-cr-at-eol` parameter](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---ignore-cr-at-eol) flag to this then.
