### ISSUE TITLE
I can't clone this repo

### ISSUE THREAD

**Issue by marioegghead2** [desktop/desktop#12781]
im trying to clone this but this suddenly happened:
![image](https://user-images.githubusercontent.com/82485570/129665230-6a5de511-1e31-4e62-86fa-63faa55d3db2.png)
first i created a repo
![image](https://user-images.githubusercontent.com/82485570/129665273-fbfd9eae-ffe6-49d2-b78a-5987ee67ec36.png)
then clicked set up in desktop and this happens
![image](https://user-images.githubusercontent.com/82485570/129665347-5455c5db-61cb-4f37-8a2f-f4b8231c2f4d.png)

**Comment by Klimoshenkoaleksandr** [comment]
Я не знаю как это делать

**Comment by tsvetilian-ty** [comment]
Hey @marioegghead2 👋 

It looks like the directory in your local path contains some files which make it invalid. Try to change the local path to an empty directory

**Comment by marioegghead2** [comment]
but how

**Comment by marioegghead2** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/987cfa1b-cbd3-49c6-b4de-5d62bdd31bf8-88df08af-2d2e-4608-bf59-fef75e8d8c50-v1.png?transparent=1&palette=1&width=246)

'

**Comment by tsvetilian-ty** [comment]
> but how

@marioegghead2 click the "Choose..." button that is next to your local path and pick an empty directory

**Comment by marioegghead2** [comment]
> > but how
> 
> @marioegghead2 click the "Choose..." button that is next to your local path and pick an empty directory

send ss

**Comment by marioegghead2** [comment]
> {
    "_readme": [
        "This file locks the dependencies of your project to a known state",
        "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file",
        "This file is @generated automatically"
    ],
    "content-hash": "5031df936f8eb37f15de9723cb1256cc",
    "packages": [
        {
            "name": "guzzlehttp/guzzle",
            "version": "6.3.3",
            "source": {
                "type": "git",
                "url": "https://github.com/guzzle/guzzle.git",
                "reference": "407b0cb880ace85c9b63c5f9551db498cb2d50ba"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/guzzle/guzzle/zipball/407b0cb880ace85c9b63c5f9551db498cb2d50ba",
                "reference": "407b0cb880ace85c9b63c5f9551db498cb2d50ba",
                "shasum": ""
            },
            "require": {
                "guzzlehttp/promises": "^1.0",
                "guzzlehttp/psr7": "^1.4",
                "php": ">=5.5"
            },
            "require-dev": {
                "ext-curl": "*",
                "phpunit/phpunit": "^4.8.35 || ^5.7 || ^6.4 || ^7.0",
                "psr/log": "^1.0"
            },
            "suggest": {
                "psr/log": "Required for using the Log middleware"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "6.3-dev"
                }
            },
            "autoload": {
                "files": [
                    "src/functions_include.php"
                ],
                "psr-4": {
                    "GuzzleHttp\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Michael Dowling",
                    "email": "mtdowling@gmail.com",
                    "homepage": "https://github.com/mtdowling"
                }
            ],
            "description": "Guzzle is a PHP HTTP client library",
            "homepage": "http://guzzlephp.org/",
            "keywords": [
                "client",
                "curl",
                "framework",
                "http",
                "http client",
                "rest",
                "web service"
            ],
            "time": "2018-04-22T15:46:56+00:00"
        },
        {
            "name": "guzzlehttp/promises",
            "version": "v1.3.1",
            "source": {
                "type": "git",
                "url": "https://github.com/guzzle/promises.git",
                "reference": "a59da6cf61d80060647ff4d3eb2c03a2bc694646"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/guzzle/promises/zipball/a59da6cf61d80060647ff4d3eb2c03a2bc694646",
                "reference": "a59da6cf61d80060647ff4d3eb2c03a2bc694646",
                "shasum": ""
            },
            "require": {
                "php": ">=5.5.0"
            },
            "require-dev": {
                "phpunit/phpunit": "^4.0"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "1.4-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "GuzzleHttp\\Promise\\": "src/"
                },
                "files": [
                    "src/functions_include.php"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Michael Dowling",
                    "email": "mtdowling@gmail.com",
                    "homepage": "https://github.com/mtdowling"
                }
            ],
            "description": "Guzzle promises library",
            "keywords": [
                "promise"
            ],
            "time": "2016-12-20T10:07:11+00:00"
        },
        {
            "name": "guzzlehttp/psr7",
            "version": "1.6.1",
            "source": {
                "type": "git",
                "url": "https://github.com/guzzle/psr7.git",
                "reference": "239400de7a173fe9901b9ac7c06497751f00727a"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/guzzle/psr7/zipball/239400de7a173fe9901b9ac7c06497751f00727a",
                "reference": "239400de7a173fe9901b9ac7c06497751f00727a",
                "shasum": ""
            },
            "require": {
                "php": ">=5.4.0",
                "psr/http-message": "~1.0",
                "ralouphie/getallheaders": "^2.0.5 || ^3.0.0"
            },
            "provide": {
                "psr/http-message-implementation": "1.0"
            },
            "require-dev": {
                "ext-zlib": "*",
                "phpunit/phpunit": "~4.8.36 || ^5.7.27 || ^6.5.8"
            },
            "suggest": {
                "zendframework/zend-httphandlerrunner": "Emit PSR-7 responses"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "1.6-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "GuzzleHttp\\Psr7\\": "src/"
                },
                "files": [
                    "src/functions_include.php"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Michael Dowling",
                    "email": "mtdowling@gmail.com",
                    "homepage": "https://github.com/mtdowling"
                },
                {
                    "name": "Tobias Schultze",
                    "homepage": "https://github.com/Tobion"
                }
            ],
            "description": "PSR-7 message implementation that also provides common utility methods",
            "keywords": [
                "http",
                "message",
                "psr-7",
                "request",
                "response",
                "stream",
                "uri",
                "url"
            ],
            "time": "2019-07-01T23:21:34+00:00"
        },
        {
            "name": "netresearch/jsonmapper",
            "version": "v1.4.0",
            "source": {
                "type": "git",
                "url": "https://github.com/cweiske/jsonmapper.git",
                "reference": "3868fe1128ce1169228acdb623359dca74db5ef3"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/cweiske/jsonmapper/zipball/3868fe1128ce1169228acdb623359dca74db5ef3",
                "reference": "3868fe1128ce1169228acdb623359dca74db5ef3",
                "shasum": ""
            },
            "require": {
                "php": ">=5.6"
            },
            "require-dev": {
                "phpunit/phpunit": "~4.8.35 || ~5.7 || ~6.4",
                "squizlabs/php_codesniffer": "~1.5"
            },
            "type": "library",
            "autoload": {
                "psr-0": {
                    "JsonMapper": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "OSL-3.0"
            ],
            "authors": [
                {
                    "name": "Christian Weiske",
                    "email": "cweiske@cweiske.de",
                    "homepage": "http://github.com/cweiske/jsonmapper/",
                    "role": "Developer"
                }
            ],
            "description": "Map nested JSON structures onto PHP classes",
            "time": "2017-11-28T21:30:01+00:00"
        },
        {
            "name": "picaboooo/snapchatsdk",
            "version": "v1.0.1",
            "source": {
                "type": "git",
                "url": "https://github.com/Picaboooo/SnapchatSDK.git",
                "reference": "61616ce8a8ee0066d92196d83f213d8efa50db69"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/Picaboooo/SnapchatSDK/zipball/61616ce8a8ee0066d92196d83f213d8efa50db69",
                "reference": "61616ce8a8ee0066d92196d83f213d8efa50db69",
                "shasum": ""
            },
            "require": {
                "ext-json": "*",
                "ext-openssl": "*",
                "ext-zip": "*",
                "guzzlehttp/guzzle": "^6.2",
                "netresearch/jsonmapper": "v1.4.0"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "Snapchat\\": "src/Snapchat/",
                    "Picaboooo\\": "src/Picaboooo/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "proprietary"
            ],
            "description": "Snapchat private API for PHP",
            "keywords": [
                "api",
                "php",
                "private",
                "snapchat"
            ],
            "time": "2019-07-09T10:59:13+00:00"
        },
        {
            "name": "psr/http-message",
            "version": "1.0.1",
            "source": {
                "type": "git",
                "url": "https://github.com/php-fig/http-message.git",
                "reference": "f6561bf28d520154e4b0ec72be95418abe6d9363"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/php-fig/http-message/zipball/f6561bf28d520154e4b0ec72be95418abe6d9363",
                "reference": "f6561bf28d520154e4b0ec72be95418abe6d9363",
                "shasum": ""
            },
            "require": {
                "php": ">=5.3.0"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "1.0.x-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "Psr\\Http\\Message\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "PHP-FIG",
                    "homepage": "http://www.php-fig.org/"
                }
            ],
            "description": "Common interface for HTTP messages",
            "homepage": "https://github.com/php-fig/http-message",
            "keywords": [
                "http",
                "http-message",
                "psr",
                "psr-7",
                "request",
                "response"
            ],
            "time": "2016-08-06T14:39:51+00:00"
        },
        {
            "name": "ralouphie/getallheaders",
            "version": "3.0.3",
            "source": {
                "type": "git",
                "url": "https://github.com/ralouphie/getallheaders.git",
                "reference": "120b605dfeb996808c31b6477290a714d356e822"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/ralouphie/getallheaders/zipball/120b605dfeb996808c31b6477290a714d356e822",
                "reference": "120b605dfeb996808c31b6477290a714d356e822",
                "shasum": ""
            },
            "require": {
                "php": ">=5.6"
            },
            "require-dev": {
                "php-coveralls/php-coveralls": "^2.1",
                "phpunit/phpunit": "^5 || ^6.5"
            },
            "type": "library",
            "autoload": {
                "files": [
                    "src/getallheaders.php"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Ralph Khattar",
                    "email": "ralph.khattar@gmail.com"
                }
            ],
            "description": "A polyfill for getallheaders.",
            "time": "2019-03-08T08:55:37+00:00"
        }
    ],
    "packages-dev": [],
    "aliases": [],
    "minimum-stability": "stable",
    "stability-flags": [],
    "prefer-stable": false,
    "prefer-lowest": false,
    "platform": [],
    "platform-dev": []
}

**Comment by tidy-dev** [comment]
@marioegghead2 As the error indicates, it can't clone to directory that is non-empty. Thus you must choose a different directory to clone to. You can either change the default generated path provided in `Local path` manually by changing the input or as tsvetilian-ty mentioned there is a `Choose...` button next to that input that will open your directory finder and you can navigate to a directory you which to clone to. (mine is on a mac so that finder will appear different on your windows machine but will be similar). Here is a quick video:

https://user-images.githubusercontent.com/75402236/130073117-a19cda19-a683-4e89-aaae-b8c186794c99.mov
