### ISSUE TITLE
Can we Please see some win UI 3 or fluent Ui in the next update? to match windows 11 design

### ISSUE THREAD

**Issue by fisforfaheem** [desktop/desktop#12808]
win UI 3 or fluent Ui in the next update? to match windows 11 design

**Comment by sergiou87** [comment]
Hello! Thanks for the suggestion, but we try to keep our issues scoped to things that are more discrete so I'm going to close this issue. If you have a more specific suggestion, feel free to share it! 😄 

Related: #12723

**Comment by fisforfaheem** [comment]
the latest version really has some good UI but still need more anyway
wthanks



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
08/24/21,
03:22:50 PM
