### ISSUE TITLE
Authentication Failed 

### ISSUE THREAD

**Issue by M3mbrane** [desktop/desktop#12814]
https://user-images.githubusercontent.com/71910687/130306635-8953493f-8e81-4fa4-afe1-80be63e24daa.mp4

**Comment by tsvetilian-ty** [comment]
👋  @M3mbrane 

You can try to generate a personal access token ([see more](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token)) and use it as a password. The other option is to log into your GitHub profile through the app and I think it will automatically set all things required for proper authentication

**Comment by sergiou87** [comment]
Yes! Exactly that 😄  Thank you @tsvetilian-ty ❤️ 

We made a few improvements to the auth failed dialog in #12538 which should make this much more clear in the upcoming version of the app 😄 

![image](https://user-images.githubusercontent.com/1083228/130427942-be38b03a-707c-4ba5-b599-743ae2108424.png)
