### ISSUE TITLE
Clone Selecting Directory Requires a file instead of a folder

### ISSUE THREAD

**Issue by CherryEx** [desktop/desktop#12812]
### Describe the bug
The bug is inside the clone repository window. When I want to select a directory to clone the repo, It's actually a file dialog and it requires a file instead of a folder

### Version & OS

Version 2.9.0 (x64) on Windows 10

### Steps to reproduce the behavior

1. Click on File
2. Choose Clone Repository
3. Click on "Choose..." button

### Expected behavior

It should be a directory dialog so I can choose a folder

### Actual behavior

It's a file dialog so I'm not able to select a folder

**Comment by sergiou87** [comment]
This is indeed a bug introduced in #11949, which should be easy to revert/fix.

Thank you for letting us know!! ❤️

**Comment by j-f1** [comment]
@HamidReza585 — did you want to clone the repo directly into an existing directory? The current dialog UI is designed to allow you to create a new directory to clone into. In the meantime, you can modify the path in the clone dialog to put the clone in the right place.

For reference, here’s what I’m trying to understand: do you want to do A or B (file trees shown):

```
A:
C:\...\my_projects (existing directory)
- cloned_repo (new directory)
  - .git
  - README.md (cloned from repo)
  - ... (cloned from repo)

B:
C:\...\my_projects\cloned_repo (existing directory)
- .git
- README.md (cloned from repo)
- ... (cloned from repo)
```

**Comment by CherryEx** [comment]
It doesn't really matter if I am trying to clone it into a new or existing directory.
The problem is the current dialog wants you to choose a file instead of a location to clone the project. The problem is obvious and easy to fix.

**Comment by jrshelby** [comment]
+1 on this.

I really thought it was a bug, but after playing with it for a bit, maybe it's just that the UI is confusing in its current form. Maybe my memory is wrong, but I seem to remember that the old behavior was:
- Open dialog allows a folder to be selected
- By default, a sub-folder named after the repo is appended to the path you select
- If you want, you could change the name of that folder in the textbox afterward

Now, the behavior is:
- Save dialog _feels like_ it wants you to select a file
- However, if you type a new name at the bottom, it creates a path ending with a folder with that name

Currently using Windows 10 (could be other OS file dialog feels better) but perhaps the UI weirdness is related to the fact that it's really unusual for a Save dialog to be used to create a new _folder_ rather than a file?

**Comment by joshSi** [comment]
> +1 on this.
> 
> I really thought it was a bug, but after playing with it for a bit, maybe it's just that the UI is confusing in its current form. Maybe my memory is wrong, but I seem to remember that the old behavior was:
> 
> * Open dialog allows a folder to be selected
> * By default, a sub-folder named after the repo is appended to the path you select
> * If you want, you could change the name of that folder in the textbox afterward
> 
> Now, the behavior is:
> 
> * Save dialog _feels like_ it wants you to select a file
> * However, if you type a new name at the bottom, it creates a path ending with a folder with that name
> 
> Currently using Windows 10 (could be other OS file dialog feels better) but perhaps the UI weirdness is related to the fact that it's really unusual for a Save dialog to be used to create a new _folder_ rather than a file?

Yep. I realized this too, the "Choose..." button creates a sub-folder named after the repository as it should.

I think the "bug" I encountered at some point might've been because a folder already existed with the repository name or something

**Comment by SharakPL** [comment]
> Now, the behavior is:
> 
>  * Save dialog _feels like_ it wants you to select a file
>  * However, if you type a new name at the bottom, it creates a path ending with a folder with that name

It shouldn't be like that. It's about a path for the repo, not about naming it. Setting up name already works fine. When I choose a repo from the list to be cloned then its name is automatically added to the path. The same when I paste an url so this part is working perfectly. If someone wants to change the name then simply update the path. For creating new repo the name should have another input in the form. No _save as_ dialog is required here.

This should be used for path, not _Save as_ prompt:

![obraz](https://user-images.githubusercontent.com/5007456/159654651-29b4ec57-75eb-49d0-9729-272fd40178dc.png)

btw. @HamidReza585 please, update the title to be more specific on the issue
