### ISSUE TITLE
GitHub Desktop - easy copying of Branch Name Feature Request

### ISSUE THREAD

**Issue by jonathangroves** [desktop/desktop#12810]
As a developer who creates and PRs many branches each day, given that I have to use branch names in Kanban comments, checkouts and pulls on remote machines, and DevOps notes, I want to be able to easily copy the branch name from GitHub Desktop so that it saves me typing and reduces errors.
GitHub Desktop is the obvious single source of truth for getting this name.
I can find no way of copying the branch name from inside the app - the "Create a Pull Request" element on the Changes view of the current repo is the obvious place - perhaps clicking on this could copy the name to the clipboard (or at least allow drag-copy to clipboard)?
Keep safe, guys - and keep being awesome!

**Comment by tsvetilian-ty** [comment]
Hello @jonathangroves 👋 

What version of GitHub Desktop you're using?
The ability to copy the branch name already exists. Check out the [release notes](https://desktop.github.com/release-notes/) for version 2.8.3.

**Comment by jonathangroves** [comment]
Hi. Thanks for replying. 2.9.0 (x64) under macOS - no Copy Branch Name here (see screenshot)
<img width="258" alt="Screenshot 2021-08-20 at 10 50 47" src="https://user-images.githubusercontent.com/26300378/130215873-d9deba2b-315e-48af-956c-86d9daa7a7e0.png">

**Comment by tsvetilian-ty** [comment]
Can you screenshot your context menu, which is shown when you right-click/secondary click on a repo or a branch?

![image](https://user-images.githubusercontent.com/9341546/130223666-ac20291b-b88e-465d-8688-dc662eb1e2a9.png)
![image](https://user-images.githubusercontent.com/9341546/130223710-7ce88861-90fd-4565-ba2c-1907764ce315.png)

**Comment by jonathangroves** [comment]
I see it now - thanks so much for your time, keep safe.
