### ISSUE TITLE
Can't include/exclude lines from committing for staged files

### ISSUE THREAD

**Issue by Optifun** [desktop/desktop#12811]
### Describe the bug
Can't stage/unstage lines in diff section when 'Hide whitespace changes' option is enabled.

### Version & OS
GitHub Desktop - Version 2.9.0 (x64)
Windows 10 20H2

### Steps to reproduce the behavior

1. Go to Options in the right angle of the diff section
2. Enable 'Hide whitespace changes' option
3. Click on line numbers of modified lines of code

### Expected behavior

Lines must change their state to staged/unstaged when you click on them.

### Actual behavior

Lines aren't clickable, so you can't exclude them from commit.

### Screenshots
Hide whitespace changes: on
![image](https://user-images.githubusercontent.com/36756042/130211274-c6179b56-8a52-48d9-b26a-9bc5b356d423.png)

Hide whitespace changes: off
![image](https://user-images.githubusercontent.com/36756042/130213089-f2aca6f7-5a69-4766-aeca-e2ebf451f3f8.png)

**Comment by sergiou87** [comment]
This is an intended limitation with `Hide whitespace changes`, because it's hard to understand what will be the changes actually included in the commit and excluded from it, so we left it to an "all or nothing" kind of thing.
