### ISSUE TITLE
github desktop windows 7 32 bit login failed

### ISSUE THREAD

**Issue by Dima73** [desktop/desktop#12816]
Use github desktop windows 7 32 bit version 3.3.6.1
I recently signed out of my account.
Now I cannot log back into account(Log in Failed). 
In what file are these files recorded and in what format?
I really ask for your help.

**Comment by Dima73** [comment]
I know I am using a very old version of the program.
But at the moment I have no opportunity to supply 64 systems.
Therefore, if it is possible to write the program github desktop account to the configuration file?

**Comment by sergiou87** [comment]
I'm sorry, what files are you looking for exactly? Your repositories?

**Comment by Dima73** [comment]
I need a file where the github account data is stored (login / password).
I understand that the .gitconfig file.
What is the correct format for these lines?
For example if:
  login Dima
password 12345 

[remote "origin"]
	url = https://Dima@github.com/Dima
       password = 12345

or

[github]
???
or
?

**Comment by sergiou87** [comment]
Hmmm I have no idea where in the old app (that old app is more than 4 years old and I joined GitHub 8 months ago 😅 ), but in any case passwords might be in the Windows Credential Manager: https://www.youtube.com/watch?v=y__5OVMxbj8

**Comment by sergiou87** [comment]
I'm gonna close this, but I'll be happy to help if I can!

**Comment by steveward** [comment]
@Dima73 you won't be able to log in to the classic GitHub Desktop application anymore due to the deprecation of password authentication:

https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/

I'm sorry that I don't have better news.

**Comment by Dima73** [comment]
I seem to have solved the problem:
.gitconfig
[user]
	name = 
	email = 
	username = 
	password = 
	token = 
[github]
	user = 
	token = 
	password = 
	url = https://github.com/user

.git-credentials
https://user:token@github.com
