### ISSUE TITLE
GitHub Desktop 2.9.0 Dark theme is mostly white on Win 10 x64

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#12826]
### Describe the bug
GitHub Desktop Dark theme is mostly white

### Version & OS

Windows 10  x64 Microsoft Windows [Version 10.0.19043.1165]
Version 2.9.0 (x64)

### Steps to reproduce the behavior

Click on file/options/appearance, Click on dark, restart client, mostly white

### Expected behavior

All should be dark gray

### Actual behavior

Dark gray ribbon. The main window is still white

### Screenshots

https://i.postimg.cc/tgWyqDrf/github-dark.jpg
![github_dark](https://user-images.githubusercontent.com/60808025/130536328-49ff2c50-d58d-4888-b94c-79656bea67d2.jpg)

### Logs

n/a

### Additional context

n/a

**Comment by steveward** [comment]
@adludum99 thanks for the report. This looks like a case of https://github.com/desktop/desktop/issues/4054.

Can you try resetting GitHub Desktop by following these steps?

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop

Let me know if that does not get things working.

**Comment by ghost** [comment]
no change 🙁

https://i.postimg.cc/NMVW9TYL/githubdark.jpg



________________________________

**Comment by steveward** [comment]
@adludum99 based on that screenshot it looks like the main window returned -- is the issue now that the theme is not changing correctly?

**Comment by ghost** [comment]
what I'm saying is that it doesn't matter which theme I choose, after restarting the app the main window is still whitethe way it isI pick light theme, restart the app, the main window is whiteI pick dark theme, restart the app, the main window is whiteI pick system theme, restart the app, the main window is white if Windows high contrast theme is Onthe way it should beI pick light theme, restart the app, the main window is whiteI pick dark theme, restart the app, the main window is darkI pick system theme, restart the app, the main window is dark if Windows high contrast theme is OnOn Sep 9, 2021 3:05 AM, Steve Ward ***@***.***> wrote:
@adludum99 based on that screenshot it looks like the main window returned -- is the issue now that the theme is not changing correctly?

**Comment by steveward** [comment]
Thanks for the clarification. Could you try performing a completely fresh installation of GitHub Desktop by following these steps?

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `%AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that helps.
