### ISSUE TITLE
Setting to hide recent repositories

### ISSUE THREAD

**Issue by quisido** [desktop/desktop#12824]
Re-opening #9156 because it was deemed "too new a feature" to improve upon (???) and closed. It's been a year and a half since then, and this is still the most annoying part of GitHub Desktop, and I'm still dying to get it addressed.

### Describe the feature or problem you’d like to solve

When I open the repositories dropdown, the top of the list ("recent") is distracting and useless to me. I have dozens of repositories that are each updated frequently (often daily). Every so often, I click down the list on each repository in order to "pull latest" to keep my local copies up to date. When I open the repository list, I look for the ⬇ icon that signifies that an update to this repository exists. The top repositories are the first thing I see, but they are duplicates of the repositories below them. I often find myself clicking a recent repository because it needs updating, clicking pull latest, then clicking that same repository not on the recent list, because that duplicate entry also has the ⬇ icon next to it while the updating is pulling.

This is difficult to gauge which repositories need updating.

Given I work in so many repositories, the recent list is always arbitrary and useless. I never look to it to find a repository. It just gets in the way, and it causes the aforementioned problem.

### Proposed solution
A setting to hide recent from the list

### Additional context
N/A

**Comment by steveward** [comment]
Thanks for the issue @CharlesStover. I'm going to close this in favor of https://github.com/desktop/desktop/issues/11598. You can follow along there for updates.

**Comment by ghost** [comment]
Probably Instead, they are working hard to reduce carbon emissions.

**Comment by marclammerding** [comment]
Implement this already!!
