### ISSUE TITLE
Syntax Highlighting For Dart

### ISSUE THREAD

**Issue by aaronRosenfeld** [desktop/desktop#12822]
### Describe the feature or problem you’d like to solve
It would be very nice to have the Dart language supported with syntax highlighting.

**Comment by say25** [comment]
I can open up a PR to add this feature tonight

**Comment by aaronRosenfeld** [comment]
Just took a quick look at the codebase. TBH, idk anything about how any of this works, but i do see that dart is included in this file: `app/src/highlighter/globals.d.ts` already. But the syntax highlighting still does not appear to be working. Again, not sure what this means though haha

thanks for offering to pick this up @say25 !
