### ISSUE TITLE
Add --ignore-cr-at-eol flag to ignore whitespace option

### ISSUE THREAD

**Issue by Justin-Frazier** [desktop/desktop#12820]
### Describe the feature or problem you’d like to solve

#12787 was closed without considering how to implement it. The solution was a couple of lines above the documentation quoted in the reason for closing the request.

### Proposed solution

Add the [`--ignore-cr-at-eol` parameter](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---ignore-cr-at-eol) flag to the hide whitespace option or add a checkbox that adds this flag to the `git diff` command

**Comment by sergiou87** [comment]
FYI I could've reopened #12787 if needed 😝 

Does that work for you? I tested it on macOS (so only `\n` and no `\r`) and didn't work for me, so I assumed it didn't work. Also, looking at the implementation, looks like `-w` already includes `--ignore-cr-at-eol`: https://github.com/git/git/blob/49f38e2de47a401fc2b0f4cce38e9f07fb63df48/xdiff/xutils.c/#L185-L204

```diff
$ git --no-pager diff --ignore-cr-at-eol


diff --git a/src/socket.c b/src/socket.c
index ac088dd..8cc924c 100644
--- a/src/socket.c
+++ b/src/socket.c
@@ -37,7 +37,8 @@ int initializeNetwork(void) {
   return 0;
 }

-void terminateNetwork(void) {
+void terminateNetwork(void)
+{
 #ifdef WINDOWS
     WSACleanup();
 #endif
```

**Comment by Justin-Frazier** [comment]
Sorry, I didn't realize that you could re-open feature suggestions.

I don't use git on the command line, but it looks like line breaks fail to be ignored when you compare files. This seems like a defect in git itself?

Either way, this should work for mac, Linux, or Windows and it doesn't appear to.

**Comment by niik** [comment]
Given that we already do apply the `--ignore-cr-at-eol` parameter (through our use of `-w`) it seems the proposed solution here isn't going to cut it for your use case so I'm going to close this issue but please let us know if you come up with an alternative approach.
