### ISSUE TITLE
Changes area lagging

### ISSUE THREAD

**Issue by b5414** [desktop/desktop#12831]
### Describe the bug
Scrolling in the changes area - loads the computer and lags

### Version & OS

`Version 2.9.1 (x64)`
Win 10 latest + drivers latest
Github installed on ssd, but git folder hdd placed
High end AMDs cpu&gpu

### Steps to reproduce the behavior

1. Open any repo
2. Do a lot changes in a file (I have ~400 lines .js one) // Or you can use any commit, at the history tab
3. Scroll down/up quick at the right changes area to see the lags, or you can use the overflow bar

### Expected behavior

Nice & smooth experience

### Actual behavior

Cpu using 10% and lags, also white space sometimes

### Screenshots

https://imgur.com/NMZCZCQ

### Logs

_logs are empty_

### Additional context

This started happening when I updated the application to a new version today

**Comment by billygriffin** [comment]
Thank you @b5414! We're looking into this, and looks to be the same as https://github.com/desktop/desktop/issues/12830, so I'm going to close this one as a duplicate. Please follow along there, and thanks again for reporting!
