### ISSUE TITLE
Publishing a repository when it already exists gives incorrect error

### ISSUE THREAD

**Issue by kareemsaifi** [desktop/desktop#12837]
### Describe the bug
When you create a local repository and want to publish it if the repository already exists you get the error: "Unable to publish repository. Please check if you have an internet connection and try again." instead of something along the lines of "Unable to publish repository, repository with same name already exists"

### Version & OS
Version 2.8.1
Windows 10

**Comment by steveward** [comment]
Thanks for the report @kareemsaifi. The app should handle these errors -- here's what I see when attempting to publish a repository with the same name:

<img width="441" alt="Screen Shot 2021-08-25 at 10 22 18 AM" src="https://user-images.githubusercontent.com/721500/130808434-f271567c-2af7-417e-af21-675383950396.png">

Can you share your log file to verify you are hitting the same error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

**Comment by BestInteriorDesignersinNoida** [comment]
The Goodwood is one of the [Best Interior Designers in Noida](https://thegoodwood.in/). We have provided different types of Designing like Modular Kitchen, Interior Designing.

**Comment by gzoohkitchens** [comment]
Gzooh Kitchens is the [url=https://www.gzoohkitchens.com/]Best Cloud Kitchens in St. Albert[/url]. Gzooh Kitchens provide different types of online food delivery service like Ghost Kitchens and Virtual Kitchens.
