### ISSUE TITLE
2.9.1 causes large diffs to flicker and lag

### ISSUE THREAD

**Issue by ziemkowski** [desktop/desktop#12830]
### Describe the bug
After upgrading from 2.9.0 to 2.9.1, the diff pane flickers or stutters while rendering.

When scrolling, most of the diff view is replaced by the window background color as it attempts to render during scroll. Worse yet, it now scrolls very slowly because of the lag... what was once a single swipe between pages, becomes several swipes moving 20 lines at a time.

Could it be due to the dynamic gutter width change? #12071

### Version & OS

GitHub Desktop Version 2.9.1 (x64)
macOS Big Sur 11.5.2 (20G95)

Also occurs on Windows: #12831

### Steps to reproduce the behavior

- Click a file with a large diff (300+ lines)
- Scroll the diff view up and down

I had to split this lorem ipsum into one line per sentence because otherwise, a diff of the same size but only containing a dozen or fewer changed lines has no issue, suggesting the variable that changes the render speed is the number of lines with changes, not the vertical height of the content.

### Expected behavior

It used to be very fast and fluid with no flicker in 2.9.0.

### Actual behavior

Render issues cause the scroll to stutter and the content to be replaced by the window background color.

### Screenshots

https://user-images.githubusercontent.com/704098/130614300-782ca662-da0e-4319-82c2-041033e26c93.mov

**Comment by sergiou87** [comment]
Thanks for the report @ziemkowski! We're looking into it and will try to fix it ASAP 😄 ❤️

**Comment by tidy-dev** [comment]
@ziemkowski We just released a version 2.9.2 with a performance fix for this. Thank you again for the report!
