### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by LongEcho** [desktop/desktop#12832]
### Describe the feature or problem you’d like to solve

A Linux version of Github Destop would be great!

### Proposed solution

Many of my colleagues in the indie developer area work with Linux and want Github Destop support. Github Destop would appeal to a larger crowd of people and make programming easier for them!

Thanks for the great interface!

**Comment by steveward** [comment]
Thanks for the issue @LongEcho.

At this time there are no official builds of GitHub Desktop available for Linux, but a former developer of GitHub Desktop maintains a fork with Linux builds available for download:

https://github.com/shiftkey/desktop/releases

Official Linux support is being tracked in https://github.com/desktop/desktop/issues/1525.

**Comment by Mesum-Hussain** [comment]
I would really be very happy if that happens soon. Shifting very recently to Linux, the only problem I have been facing all along is that many of my favorite applications are not supported. So I have to use Open Source alternatives and GitHub is the place to find them. Given that Linux users are the biggest supporters of Open Source, GitHub should not be one of the softwares not supporting Linux. Till then I guess I will use the fork you mentioned. I wonder if you can take inspiration from that fork to get Linux support soon.

Thanks.
