### ISSUE TITLE
Is it possible to delete local branch history files and save storage space?

### ISSUE THREAD

**Issue by Josh65-2201** [desktop/desktop#12839]
I have many files changed and having GitHub storage all of them into its .git folder is kind of pointless for me after a certain point. I would like to know if I could delete the files for them at all, and if it's possible could it be done automatically after certain number of commits.

**Comment by b5414** [comment]
Save all changes (by a commit / copy&paste), then remove git repo from your hdd, then clone it back

**Comment by steveward** [comment]
@josh-65 thanks for the issue. You can rewrite your history, but it's a more advanced feature that is often used to remove sensitive data. Something like https://github.com/newren/git-filter-repo may be of interest to you, but please note these actions are destructive and require force-pushing your repository. 

We're tracking support for lightweight clones in https://github.com/desktop/desktop/issues/3480, but at this time GitHub Desktop does not support this feature. Lightweight clones would improve performance when working with larger repositories where the entire history is not needed. I'd recommend keeping an eye on that issue for updates.

I'm going to close this out, but I hope that helps!
