### ISSUE TITLE
Can't select individual lines to commit

### ISSUE THREAD

**Issue by JonasSamuelsson** [desktop/desktop#12848]
### Describe the bug

I used to be able to select individual lines to include/exclude per commit by clicking in the line number gutter, but this doesn't work any more.

### Version & OS

GitHub Desktop 2.9.2 x64

Windows 10 Enterprise
Version	21H1
Installed on	‎2021-‎06-‎17
OS build	19043.1165
Experience	Windows Feature Experience Pack 120.2212.3530.0

### Screenshots

![image](https://user-images.githubusercontent.com/2103937/131082585-4cf46d90-5e6e-435f-8940-c264df639ce6.png)

**Comment by sergiou87** [comment]
Hi @JonasSamuelsson ! 👋 

Is it possible you have `Hide Whitespace Changes` enabled?

![2021-08-30 at 08 10](https://user-images.githubusercontent.com/1083228/131293325-f30e96e8-fd0d-4473-805a-d18722f50053.png)

Just disabling it should make it work as you'd expect again 😄

**Comment by JonasSamuelsson** [comment]
Yes, that was it, thank you :smile:

But that information is way to hidden. I enabled hide whitespace changes weeks ago and thus it's long gone from memory.
A better solution in my mind would be to display a info popup or something similar when trying to include/exclude lines.
