### ISSUE TITLE
list unchanged file

### ISSUE THREAD

**Issue by Mamba413** [desktop/desktop#12845]
### Describe the bug
File does not change but it is listed as a changed file.

### Version & OS

operating system: Windows 11. Github desktop version: Version 2.9.2 (x64)

### Screenshots

![image](https://user-images.githubusercontent.com/24458259/131064814-cde4e62b-5056-4117-9351-07c8e7cd08b6.png)

**Comment by tsvetilian-ty** [comment]
Hi @Mamba413 

The reason for this issue most likely is file mode or line ending changes, a potential fix is present in here #12127

**Comment by Mamba413** [comment]
Thanks! It is helpful.
