### ISSUE TITLE
Unable to get Intellij under integration on windows 10

### ISSUE THREAD

**Issue by prvn01** [desktop/desktop#12847]
### Describe the bug
Unable to get Intellij under integration on windows 10. It is working fine in Mac.

### Version & OS

Version 2.9.2 (x64)
OS : Windows 10 Pro 20H2

### Steps to reproduce the behavior

1. Go to 'File --> options --> Integrations -->Applications'
2. Click on ' (External Editor) Drop Down'

### Expected behavior

You should be able to see Intellij as an option there.

### Actual behavior

You don't see Intellij as an option there

### Screenshots

![image](https://user-images.githubusercontent.com/88649408/131078164-9885ffdc-3f28-4fb4-be4d-2ced6034f594.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by Joe838383** [comment]
Block this person and don't allow anymore
