### ISSUE TITLE
Notepad++ External Editor support regression

### ISSUE THREAD

**Issue by MalcolmHannah** [desktop/desktop#12841]
### Describe the bug
I no longer have the option to open files in Notepad++, which I had configured as my External Editor.
GitHub Desktop doesn't find any suitable editors and prompts me to install VS Code.

### Version & OS
GitHub Desktop version 2.92.
Microsoft Windows [Version 10.0.19041.1165]

### Steps to reproduce the behavior

1. Go to the Changes tab.
2. Check the main pane (on the right).

### Expected behavior

The main pane should show an option to "Open the repository in your external editor", just above the option to "View the files of your repository in Explorer".

### Actual behavior

Only the Explorer option is shown.

Also, the File, Options, Integrations dialog now says "External editor.  No editors found.  Install Visual Studio Code?"
but it should offer a way to choose Notepad++.

### Additional context

I've observed this on two different computers, both Windows 10.
Notepad++ support was working well in version 2.90 as shown in the screenshot.

### Screenshots

![ghd290-nppp](https://user-images.githubusercontent.com/19389579/130998992-fb71ff95-25c4-4e46-99ef-063e659fcd55.PNG)

**Comment by tsvetilian-ty** [comment]
Hello @MalcolmHannah 👋 

It looks like the issue is introduced in this [commit](https://github.com/desktop/desktop/commit/16190b7ad7ee9434ecec6de6537baa17dc7d7d50). @sergiou87 can confirm if these changes are the cause of the problem. 

Perhaps a fix might be adding an empty array inside executableShimPaths's existing one, example:

```ts
 {
    name: 'Notepad++',
    registryKeys: [
      // 64-bit version of Notepad++
      LocalMachineUninstallKey('Notepad++'),
      // 32-bit version of Notepad++
      Wow64LocalMachineUninstallKey('Notepad++'),
    ],
    executableShimPaths: [[]],
    installLocationRegistryKey: 'DisplayIcon',
    expectedInstallationChecker: (displayName, publisher) =>
      displayName.startsWith('Notepad++') && publisher === 'Notepad++ Team',
  }
```

> Note: RStudio might need the same change!

**Comment by MalcolmHannah** [comment]
Thanks @tsvetilian-ty.

I ran Process Monitor to watch the registry activity and can see lots of **successful** accesses of
`HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Notepad++`
followed by an **unsuccessful** access of 
`HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Notepad++
`

I've attached the Process Monitor log file in case it might be helpful:
[Logfile.CSV](https://github.com/desktop/desktop/files/7062854/Logfile.CSV)

I should have mentioned before that this is x64 Windows 10 Home, and I have the x64 version of Notepad++ (it's installed in "C:\Program Files\Notepad++" and `dumpbin /headers` confirms it is an x64 buiild).

**Comment by MalcolmHannah** [comment]
Fix confirmed with version 2.9.3.

Thanks @sergiou87 @tsvetilian-ty and team.

**Comment by admbanking1** [comment]
#pay

**Comment by Taefive55** [comment]
#13067

**Comment by Taefive55** [comment]
#13067

**Comment by aiodh** [comment]
> ### Describe the bug
> I no longer have the option to open files in Notepad++, which I had configured as my External Editor. GitHub Desktop doesn't find any suitable editors and prompts me to install VS Code.
> 
> ### Version & OS
> GitHub Desktop version 2.92. Microsoft Windows [Version 10.0.19041.1165]
> 
> ### Steps to reproduce the behavior
> 1. Go to the Changes tab.
> 2. Check the main pane (on the right).
> 
> ### Expected behavior
> The main pane should show an option to "Open the repository in your external editor", just above the option to "View the files of your repository in Explorer".
> 
> ### Actual behavior
> Only the Explorer option is shown.
> 
> Also, the File, Options, Integrations dialog now says "External editor. No editors found. Install Visual Studio Code?" but it should offer a way to choose Notepad++.
> 
> ### Additional context
> I've observed this on two different computers, both Windows 10. Notepad++ support was working well in version 2.90 as shown in the screenshot.
> 
> ### Screenshots
> ![ghd290-nppp](https://user-images.githubusercontent.com/19389579/130998992-fb71ff95-25c4-4e46-99ef-063e659fcd55.PNG)
