### ISSUE TITLE
error: RPC failed; HTTP 401 curl 22 The requested URL returned error: 401

### ISSUE THREAD

**Issue by PoulChapman** [desktop/desktop#12854]
### Describe the bug
When using GitHub Desktop with an Azure DevOps repo, I'm getting the following error, and am unable to push to origin
* error: RPC failed; HTTP 401 curl 22 The requested URL returned error: 401
However, when I use the Command Prompt opened from GH Desktop, I am able to push to origin (verified by checking the branch on AzDO website

### Version & OS

GitHub Desktop version 2.9.2 x64
Windows 10 ver 21H1 19043.1165

### Steps to reproduce the behavior

1. In Azure DevOps, clone a repo
2. Paste that URL into GH Desktop
3. Switch to a topic branch
4. Make a change, and commit the PR
5. In GH Desktop, push Origin
6. From GH Desktop, open the command prompt & type "git push"
7. Success!! Confirmed by looking at branch in online AzDO

### Expected behavior

The push should be successful by using GH Desktop

### Actual behavior

Get this Error:
error: RPC failed; HTTP 401 curl 22 The requested URL returned error: 401
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
Everything up-to-date

**Comment by steveward** [comment]
Thanks for the issue @PoulChapman. Did you create a token for GitHub Desktop to use? We have the specific steps here:

https://github.com/desktop/desktop/blob/development/docs/integrations/azure-devops.md

**Comment by PoulChapman** [comment]
@steveward - Ah that's the issue. I didn't realize I had two PATs, one that was read/write that the command line was using, and another read-only that GitHub Desktop was using. Switched the second PAT to read/write and it worked.

I'll let you close in the event there's any experience changes you can/want to make
