### ISSUE TITLE
No external editor available

### ISSUE THREAD

**Issue by Billy2011** [desktop/desktop#12858]
### Describe the bug

Notepad++ as external editor no longer available.

### Version & OS

GitHub Desktop 2.9.2 on Windows 10 Pro (x64) version 21H1

### Steps to reproduce the behavior

1. Go to 'Options...'
2. Click on 'Integrations'
3. See error 'No editors found'

### Expected behavior

In version 2.9.0 Notepad++ was displayed as ext. editor.

**Comment by tsvetilian-ty** [comment]
Hi @Billy2011 the problem is reported, you can follow the progress in #12841
