### ISSUE TITLE
Can't use Notepad++ even though supported

### ISSUE THREAD

**Issue by Mythical-Github** [desktop/desktop#12856]
### Describe the bug
Notepad++ is no longer registered by Github Desktop as existing even though it was previously working.
Not sure what exactly caused it. 
I opened something via github desktop in notepad++, closed notepad++, then tried to open it again via github desktop a few seconds later and now it won't let me at all and won't recognize it. 
I've tried full uninstall, delete all settings and remaining files, and reinstall of both applications to no avail.
Other IDEs that are officially supported work but this one won't and is my preffered.

### Version & OS
Version 2.9.2 (x64) and Windows 10
Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior
Install Notepad++ and install Github Desktop, having used both already, open github desktop and go to 
file->options->integrations->external editor -> look for notepad++

### Expected behavior

Being able to Choose notepad++ as my preferred ide to open things with from inside github desktop

### Actual behavior

Doesn't see Notepad++ at all, reccomends me install vsc

**Comment by tsvetilian-ty** [comment]
Hello @Mythical-Github the problem is reported, you can follow the progress in #12841

**Comment by sergiou87** [comment]
Sorry about that! I'll take a look right away.

**Comment by Mythical-Github** [comment]
Thanks for the fast fix, I installed the latest beta and everything is great again
