### ISSUE TITLE
I can't fetch origin

### ISSUE THREAD

**Issue by terezapalanska** [desktop/desktop#12851]
### Describe the bug

I can't Fetch origin on the Github Desktop even if:

1. I am signed up.
2. I have signed out and signed in. (Token refreshed)
3. Restarted my computer and reinstalled the Github Desktop

I have used Github Desktop since the beginning of the project and did have any similar problems until now. On July 20, I received the following e-mail:

_Hi @terezapalanska,

You recently used a password to access the repository at janxmares/wb-gtid with git using git/2.29.3.

Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information around suggested workarounds and removal dates.

Thanks,
The GitHub Team_

I set the two-factor authentication, but nothing changed and I still cannot fetch the origin.

### Version & OS

GitHub Desktop 4: Version 2.9.2 
OS: MacOS Mojave version 10.14.6

### Steps to reproduce the behavior

1. Go to GitHub Desktop
2. Click on 'Fetch Origin'

### Expected behavior

Fetch origin is done.

### Actual behavior

The error message pops up - see Screenshots section.

### Screenshots
![image](https://user-images.githubusercontent.com/61198666/131152089-708ea06f-b045-46b3-acf1-4d5a23f030dd.png)

**Comment by sergiou87** [comment]
Hi @terezapalanska! 👋 

Could you share the logs? Those might have more details about what went wrong exactly. You can find those in `Help` -> `Show Logs in Finder`
