### ISSUE TITLE
Uncaught (in promise) Error: The current branch is unborn.

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1286]
Getting a "Uncaught (in promise) Error: The current branch is unborn" error. Unsure why this is happening, but there should be some messaging for the user to help resolve the issue. 

I believe I was trying to publish a repo, with bad credentials, but I am not 100% as I couldn't reproduce it. Perhaps there was a lag between creating new repo, logging in, and publishing the repo.

![screen shot 2017-04-24 at 2 09 34 pm](https://cloud.githubusercontent.com/assets/14828183/25359214/2ea77cf2-28f9-11e7-8d64-ee4ce420e220.png)

App was updated right before this error surfaced. v0.0.34, Windows 10

**Comment by oyeanuj** [comment]
@shiftkey I can still reproduce the same problem in a private repo. I created a new repo on github.com and tried both cloning and 'opening repo in Desktop' option. In both cases, the repo is cloned and the app shows me an option to 'Publish branch'. When I click on it, I see the promise error.

Any recommended workarounds?

**Comment by j-f1** [comment]
@oyeanuj Can you open a new issue and fill out the template so we can figure out what’s going on?

**Comment by shiftkey** [comment]
@oyeanuj what @j-f1 said
