### ISSUE TITLE
Switch Branch: Allow double click to confirm option

### ISSUE THREAD

**Issue by tordans** [desktop/desktop#12865]
### Describe the feature or problem you’d like to solve

The UI of the switch branch dialogue make me think the options are buttons, so I click them to confirm the dialogue.

![image](https://user-images.githubusercontent.com/111561/131329549-8e2ed7f6-5391-49ab-92b0-132b9e5a0609.png)

This is a UI pattern that Windows calls (called?) [command link](https://docs.microsoft.com/en-us/windows/win32/uxguide/ctrl-command-links) 
![image](https://user-images.githubusercontent.com/111561/131329868-4528100d-4048-4147-81c9-74025d783ff5.png)

However, in this case its actually a radio button group (with a different design) that requires using the confirm button.

### Proposed solution

There are multiple solutions to this … I want to focus on one, that might help users that struggle with this issue without changing the UI at all.

Allow to confirm the choosen selection by double clicking on it. Everything else (especially the confirm-button) stay the same they are now.

Users that are eager to discover a faster way to work around the dialogue, can double click either the selected or the unselected radio button option and confirm the window at the same time.

**Comment by sergiou87** [comment]
Thanks for your feedback @tordans!! ❤️ 

> Allow to confirm the choosen selection by double clicking on it

This specific bit should work since 2.9.1: #12559

**Comment by billygriffin** [comment]
This should definitely be consistent anytime we use this design pattern. If someone would want to make a PR to do it for the remaining places, we'd be happy to review. The PR @sergiou87 referenced from @j-f1 is the one to take a look at for prior art.

**Comment by tordans** [comment]
> This specific bit should work since 2.9.1: #12559

Yes, it does <3, thanks for pointing that out @sergiou87. And thanks @j-f1 for building it!

---

I will leave this issue open since @billygriffin's question about other dialogues is still valid. Please feel free to rename it to be more general or close it in favor of a the ticket.

**Comment by j-f1** [comment]
My recent PR (linked above) should address all the dialogs in the app. Are there any it didn’t affect?

**Comment by niik** [comment]
Looking at https://github.com/desktop/desktop/pull/12559 it sure seems like it would cover all similar dialogs so I'm going to close this for the time being. Feel free to create a new issue if there's a specific dialog that doesn't behave!
