### ISSUE TITLE
Conflict is resolved, but can't merge master into my branch

### ISSUE THREAD

**Issue by rammba** [desktop/desktop#12875]
### Describe the bug
Conflict is resolved, but I can't merge master into my branch.

### Version & OS
Version 2.9.2 on Windows 10

### Steps to reproduce the behavior

1. One conflict file on my branch because I brought changes from another branch
2. Resolved conflict
3. Merge master into my branch
4. Error dialog opened

### Screenshots

![Resolved](https://user-images.githubusercontent.com/40705899/131502444-b22ac623-9c22-41af-96b5-5fa4f1db0d46.png)
![Merge](https://user-images.githubusercontent.com/40705899/131523595-e2f1550b-5d2e-409c-a11b-777062f83c64.png)
![Error](https://user-images.githubusercontent.com/40705899/131503024-d5491279-9137-4375-a98e-4356bc4e45bd.png)

**Comment by steveward** [comment]
@rammba thanks for the issue. Can you go to `Repository` > `Open in <command_line>` and run the following command?

`git diff --check | grep -i conflict`

That should show if there are any leftover conflict markers that could be causing this error.

**Comment by rammba** [comment]
There is no result for that command.
![Command](https://user-images.githubusercontent.com/40705899/131522701-1dc98675-b41b-4899-9388-aa0e7a78d667.png)

**Comment by steveward** [comment]
@rammba did you commit the merge conflicts after resolving them?  Fixing the conflicts in your editor alone does not resolve the index. We have an open issue tracking potential improvements around this scenario (https://github.com/desktop/desktop/issues/11959).

**Comment by rammba** [comment]
I didn't saw that issue, sorry. The situation seems to be the same as here.
