### ISSUE TITLE
Disabled "Create a Pull Request" button

### ISSUE THREAD

**Issue by artivilla** [desktop/desktop#12879]
### Describe the bug
Disabled "Create a Pull Request" from your current branch but I can visit my github.com and create a pull request against master branch.

### Version & OS
GH desktop: Version 2.9.2 (x64) (latest)
Mac: Big Sur 11.3.1 (20E241)

### Expected behavior

When you create a new branch cmd+shift+N in your desktop app and create a new branch and commit to a new branch, create pull request buttons should be enabled.

### Actual behavior

Button should be enabled.

### Screenshots

<img width="780" alt="Screen Shot 2021-08-31 at 7 36 00 PM" src="https://user-images.githubusercontent.com/2120159/131589220-bc211675-6ec6-403f-aa6f-a79905144d3e.png">

**Comment by steveward** [comment]
Thanks for the report @artivilla. I was unable to reproduce this. Are you able to consistently reproduce this within this repository? What happens if you go to `Branch` > `Compare on GitHub`? You should see 'Changes to Compare' if there are changes.

**Comment by artivilla** [comment]
@steveward  I'll close. I've had this issue for a while but it seems like upgrading my OSx resolved it?  I've been creating PRs using github.com for a while now so I'm unclear what caused this.
