### ISSUE TITLE
No icon in github-desktop

### ISSUE THREAD

**Issue by robson-66** [desktop/desktop#12889]
Why is there no icon?
![ScreenShot](https://i.postimg.cc/BQ8tyJw6/Zrzut-ekranu-z-2021-09-01-21-10-17.png)

**Comment by steveward** [comment]
@robson-66 issues related to the unofficial Linux fork of GitHub Desktop can be filed here:

https://github.com/shiftkey/desktop/issues

At this time we only officially provide support for macOS and Windows.
