### ISSUE TITLE
Moving the window closes open dialogs

### ISSUE THREAD

**Issue by J-rg** [desktop/desktop#12885]
### Describe the bug
GitHub Desktop allows for dismissing modal dialogs by clicking anywhere outside the dialog. This also holds true for the title area, so if you move the window while a dialog is open, the dialog gets dismissed.

### Version & OS
Version 2.9.3 (x64), macOS 11.5.2 (20G95)

### Steps to reproduce the behavior
1. Open a dialog overlay, e.g. by right-clicking a branch and selecting “Rename…”
2. Click on the title bar and move the window around

### Expected behavior
The dialog stays open.

### Actual behavior
The dialog is dismissed.

**Comment by steveward** [comment]
From #14156:

>This is an issue for me because sometimes when I am typing the name of my new branch, I need to move the window to look at a document behind the GitHub Desktop window with our naming standards/conventions to see how I need to structure the name. However, when I move the window, the "Create a Branch" modal will collapse and discard any value I had already typed into the Name field.

**Comment by steveward** [comment]
We discussed this in our team meeting yesterday and the modal closing when clicking the title area is a bug that we're planning to fix.

**Comment by steveward** [comment]
I'm no longer able to reproduce this issue, so I'm going to close it out.
