### ISSUE TITLE
Color picker dismisses immediately upon click when customizing the high contrast theme

### ISSUE THREAD

**Issue by haykam821** [desktop/desktop#12895]
### Describe the bug

When the high contrast theme is selected, a set of color swatches appear to allow the user to customize the theme's colors. Clicking a swatch opens a color picker, but this color picker immediately dismisses once anything is clicked.

### Version & OS

- **GitHub Desktop:** 2.9.4-beta1
- **Operating System:** macOS Monterey 12.0 beta

### Steps to reproduce the behavior

1. Open preferences
2. Select the 'Appearance' pane
3. Select the 'High Contrast' theme
4. Click the 'Background' color swatch
5. Attempt to drag an interactive element of the color picker

### Expected behavior

The color picker allows complex interactions such as sliders and other drag interactions.

### Actual behavior

The color picker dismisses immediately, applying the resultant color from a single click on the color picker.

### Media

https://user-images.githubusercontent.com/24855774/131912626-0dfaa4b0-7e15-4fed-a4d0-3a4c3921b326.mov

**Comment by say25** [comment]
This behavior is the same on Windows

**Comment by steveward** [comment]
Thanks for the report @haykam821! /cc @tidy-dev

**Comment by tidy-dev** [comment]
@haykam821 Yep. Thank you for the report. This is among the polish type things I have listed in the [PR](https://github.com/desktop/desktop/pull/12833).

**Comment by steveward** [comment]
Closing this because the color picker was removed in https://github.com/desktop/desktop/pull/16559.
