### ISSUE TITLE
Impossible to merge branch. Desktop crashes

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#12891]
### Describe the bug
Impossible to merge a branch. When selecting one, nothing happens, and after a minute it crashes.

### Version & OS

Version 2.9.3 (x64) - Windows 10 21H1 19043.1165

### Steps to reproduce the behavior

1. Create two branches
2. Push a commit on one
3. Checkout the other
4. Select merge into current branch

### Expected behavior

The selection never comes to an end, and then it crashes. The yellow point indicating changes appear but nothing about what to merge.

### Actual behavior

Write a clear and concise description of what actually happened.

### Logs

RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be >= 0 && <= 2147483647. Received 2299290207
    at Function.concat (buffer.js:562:5)
    at ChildProcess.<anonymous> (file:///app/renderer.js:55:232838)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

Version: 2.9.3
OS: Windows 10.0.19043

**Comment by steveward** [comment]
Thanks for the issue @DuncanSourdin. Is this reproducible across multiple repositories, or is it only happening in one specific repository? 

I've tested merging recently on Windows and did not encounter any issues (and we haven't seen any other reports of this as of yet). Is there anything unusual about the repository you are working with?

It would also be helpful if you could upload the whole log file from a day you experienced the issue in GitHub Desktop just so we can ensure there isn't anything else we are missing.

**Comment by ghost** [comment]
I encountered only today and just switched to command line. I'll post infos if I get more but that's probably an isolated case

**Comment by steveward** [comment]
@DuncanSourdin thanks for the update -- I'll keep this open for a period of time in case you run into it again and we need to investigate further.

**Comment by steveward** [comment]
@DuncanSourdin I'm going to close this out, but let us know if you run into it again and we can dig into it further.
