### ISSUE TITLE
Not highlighting differences

### ISSUE THREAD

**Issue by ProtocolLive** [desktop/desktop#12897]
### Describe the bug
The Github Desktop are not highlighting the diferences in a file like the site.

App
![image](https://user-images.githubusercontent.com/39626142/132000471-aca32eff-0f1e-4c53-b7cf-00f9805576a6.png)
Site
![image](https://user-images.githubusercontent.com/39626142/132000488-85fc76d0-c3eb-4f25-afe1-7f22cf973c0e.png)

### Version & OS
Version 2.9.3 (x64)
Windows 10

**Comment by steveward** [comment]
Thanks for the issue @ProtocolLive. This is being tracked in https://github.com/desktop/desktop/issues/2700. I'm going to close this out.
