### ISSUE TITLE
Can't choose which lines to commit

### ISSUE THREAD

**Issue by b5414** [desktop/desktop#12908]
### Describe the bug
Can't choose which lines to commit

### Version & OS

2.9.3 (Windows 10.0.19043) x64

### Steps to reproduce the behavior

1. Make some changes in any repo
2. Open the app, diff area
3. Click on the blue "buttons" with line number

### Expected behavior

The clicked line will be disabled for the next commit

### Actual behavior

The blue button does not respond to clicking

### Screenshots

**blue button** = https://imgur.com/4wOhNSO

### Logs

_empty_

### Additional context

_none_

**Comment by sergiou87** [comment]
Hi @b5414! 👋 

I'm afraid the problem is you have enabled `Hide whitespace changes`. We want to improve the feedback we give to users about this limitation, please see #12862
