### ISSUE TITLE
2.9.3 freezes when I open it on Windows

### ISSUE THREAD

**Issue by danielfowler** [desktop/desktop#12904]
I see a perpetual "Fetching origin" loading gif or "Publish branch" and can't click on anything in the GUI. Can't even close the program, and my CPU/GPU fans start to stress out a bit, increasing from 3700 RPM to 4700 RPM. I have to right-click the Windows navbar to Close Window.

**Comment by danielfowler** [comment]
Nevermind... I was frozen due to a commit revert. Once I cleared that out, GitHub Desktop is back to working.

**Comment by Hakim77pixel** [comment]
Pada Sab, 4 Sep 2021, 3:29 PG Daniel F ***@***.***> menulis:
