### ISSUE TITLE
Allow "N changed files" list to expand further.

### ISSUE THREAD

**Issue by Niko-O** [desktop/desktop#12906]
### Describe the feature or problem you’d like to solve

I have pretty long paths in my repository (\*looks judgingly at Java package names\*).
But I also have a pretty big screen to view them (1920x1080 pixels).
Unfortunately, GitHub Desktop does not make use of all those pixels. The list on the left is only allowed to expand to approximately 460 pixels wide. It's especially bad when it detects files as "Renamed", because then two paths get cramped into a single line. Meanwhile, there's a lot of unused whitespace on the right side of the UI that's wasted.

### Proposed solution

The solution is to remove the limit on how far the divider can be dragged to the right. I don't see a practical reason for this limitation anyways.
Another possible solution is to allow paths in this list to wrap, just like code in the diff view also wraps.

### Additional context

![Space](https://user-images.githubusercontent.com/4943909/132093959-74966d58-6bfc-4f57-8107-b7805ac0f4b1.png)
Especially bad with "Renamed" files:
![Space 2](https://user-images.githubusercontent.com/4943909/132093960-19141f9b-ca5b-4050-bed7-250cf89265a1.png)

**Comment by sergiou87** [comment]
Hi @Niko-O! 👋 

Thanks for your feedback 😄  We're already tracking that in #2745 and #1588. Please feel free to subscribe and react to those issues. You will get notified whenever we make progress on them!
