### ISSUE TITLE
The commit message container has gaps revealing a different background

### ISSUE THREAD

**Issue by haykam821** [desktop/desktop#12900]
### Describe the bug

A border radius issue causes a separate background to be revealed.

### Version & OS

- **GitHub Desktop:** 2.9.4-beta1
- **Operating System:** macOS Monterey 12.0 beta

### Steps to reproduce the behavior

1. Look at the commit message container.

### Expected behavior

The commit message container should have a dark gray background.

### Actual behavior

There are curved gaps on both sides just above the action bar that reveal a slightly lighter gray background.

### Screenshots

![Curved gaps](https://user-images.githubusercontent.com/24855774/132014759-a629bca0-e86c-4d80-87f1-28c324158af3.png)

**Comment by steveward** [comment]
Good catch @haykam821, and thanks for opening a PR to fix this!
