### ISSUE TITLE
Support for latest Jetbrains IDE installed by Toolbox

### ISSUE THREAD

**Issue by CubergDev** [desktop/desktop#12912]
### Describe the bug
Trying to choose one of Jetbrains IDE as default editor, but non of them is listed. Jetbrains IDE are PyCharm, WebStorm, Intellij IDEA (all of them installed by Jetbrains Toolbox)

### Version & OS

Version 2.9.3 (x64)
Windows 10 Pro, build 19043.1202

### Steps to reproduce the behavior

1. Go to "File" menu on top.
2. Click on "Options"
3. Go to "Integrations"
4. Open list of available external editors

### Expected behavior

At least, one of Jetbrains IDE should be listed

### Actual behavior

Only Notepad++ is listed`

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by sergiou87** [comment]
Thanks for your report @CubergDev! ❤️ 

We've tracking this issue in #9453, so I would recommend you to subscribe to it and you will get notified whenever we make progress on it 😄

**Comment by sergiou87** [comment]
I'm gonna reopen this since #9453 was more generic.

**Comment by Khan8615** [comment]
So I guess support is never coming then ?? I guess well just drop the Github Desktop app all together then.

**Comment by tsvetilian-ty** [comment]
In the last 16 days, we had three issues reports for unsupported JetBrains IDE installed through Toolbox, so I decided to bring some light on why that is. 

### How GitHub Desktop external editor detection works
The current method used by GitHub Desktop to detect installed editors/IDEs is by finding specific hardcoded entries in the Windows Registry for each editor/IDE. 

### The problem with JetBrain Toolbox
When the user installs JetBrains IDE through Toolbox, there is no entry in the registry, and GitHub Desktop can't catch it. 


@Khan8615 I wouldn't say "never"! It's just hard to give an exact due date! Even now, there is a proposal PR https://github.com/desktop/desktop/pull/14843 that aims to solve the issue of unsupported external editors.

**Comment by Khan8615** [comment]
> 

Well, I have stopped using the GitHub desktop app and all of my friends/co-workers no longer use the app or GitHub. 
We have found better already working alternatives for riders sadly. It was either we all switched or moded your app & no one likes running hacked apps on their desktop.

**Comment by marty1331** [comment]
Duplicate of #`
