### ISSUE TITLE
Authentication failure while trying to fetch the origin from Azure remote repo

### ISSUE THREAD

**Issue by riasaheli** [desktop/desktop#12916]
i cloned the repo from Azure using VScode and added the repo in GitHub desktop. After that i tried to fetch origin but i got authentication failure error (please note i used username and PAT).

i tried to fetch the origin from command line and it worked fine.
[Document.docx](https://github.com/desktop/desktop/files/7115873/Document.docx)

**Comment by sergiou87** [comment]
Hi @riasaheli! 👋 

I cannot reproduce this issue, it works fine for me using my username and PAT. Could you share your logs from a day where this happened?

Thank you!

**Comment by riasaheli** [comment]
[2021-09-08.desktop.production.log](https://github.com/desktop/desktop/files/7128492/2021-09-08.desktop.production.log)
Please find the attached logs

**Comment by steveward** [comment]
@riasaheli thanks for the log. Just to confirm, did you use the PAT you generated in GitHub Desktop when you saw the prompt for your username/password? Entering it in Visual Studio Code alone will not work since GitHub Desktop stores it separately.

**Comment by riasaheli** [comment]
yes i entered my username and PAT in the github desktop when authentication popup window appear.

**Comment by steveward** [comment]
@riasaheli can you verify you are following [these steps](https://github.com/desktop/desktop/blob/development/docs/integrations/azure-devops.md) exactly? I would recommend going into Credential Manager as well and checking the `Windows Credential` section to see if there is a `GitHub - ` token there for your Azure DevOps account.
