### ISSUE TITLE
Blank Github Desktop screen with Menu items

### ISSUE THREAD

**Issue by PunitKunai** [desktop/desktop#12911]
### Describe the feature or problem you’d like to solve

I did install Github desktop on my Macincloud (MacOS) and it was working fine but when i try to access Github i see the white blank screen with Menu item list greyed out and which i am not able to access them.

Write a clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

- [ ] 

### Proposed solution

Please share how this will it benefit Desktop and its users?

### Additional context

Please include any other context, like screenshots or mockups, if applicable.

**Comment by steveward** [comment]
@PunitKunai thanks for the issue. What version of macOS is your Macinthecloud instance running?

 You should be able to resolve this by running the following command:

`rm -r ~/Library/Application\ Support/GitHub\ Desktop/IndexedDB`

And then restarting GitHub Desktop. Let me know if that helps.
