### ISSUE TITLE
diff line selection stopped working

### ISSUE THREAD

**Issue by aholtzma-am** [desktop/desktop#12915]
### Describe the bug
After updating to  2.9.3, I can no longer select/deselect lines to be included in a commit. It behaves like the clicks are not registered and the lines stay blue.

<img width="180" alt="image" src="https://user-images.githubusercontent.com/77404441/132143221-9fc30cb6-e8bb-4db8-b468-318418330a97.png">

### Version & OS

This is version 2.9.3 with Catalina. On my other machine with 2.9.3 and Big Sur however, it works as expected.

### Steps to reproduce the behavior
In the changes tab select a file with changes and try to remove some changed lines from the diff.

### Expected behavior

Toggling the diff inclusion by clicking on the blue line numbers.

### Actual behavior

Clicking on the blue line numbers does nothing.

**Comment by sergiou87** [comment]
Hi @aholtzma-am! 👋 

Is it possible that you have `Hide whitespace changes` enabled? Please see #12862

**Comment by aholtzma-am** [comment]
Yes, this is it, thanks.
