### ISSUE TITLE
Documentation incorrectly states GitHub Desktop to work on macos 10.10 onwards.

### ISSUE THREAD

**Issue by PyPublishing** [desktop/desktop#12921]
Documentation incorrectly states GitHub Desktop to work on macos 10.10 onwards.

According to issues #12920 , #12436 and #12346 this is not the case anymore.

Correct at the time of writing would therefore be macos 10.12.

<img width="761" alt="Bildschirmfoto 2021-09-07 um 16 10 26" src="https://user-images.githubusercontent.com/88194470/132360495-78a04e4d-7bc6-481c-9251-b5dcc67527a1.png">

**Comment by niik** [comment]
Hey @PyPublishing, thanks for opening this. We updated the minimum OS version in https://github.com/github/docs/pull/9870.

Note that the changes should appear on the site within approximately 24 hours.
