### ISSUE TITLE
Please add a build for linux arm32(raspberry pi)

### ISSUE THREAD

**Issue by Painadath** [desktop/desktop#12924]
### Describe the feature or problem you’d like to solve

I am using my pi 4 as a desktop and I want this desktop I tried to build but didn't worked

### Proposed solution

It will help all GitHub users having a pi

**Comment by niik** [comment]
Hi @Painadath, issues related to the unofficial Linux fork of GitHub Desktop can be filed here:

https://github.com/shiftkey/desktop/issues

At this time we only officially provide support for macOS and Windows.
