### ISSUE TITLE
Macos: "dyld: lazy symbol binding failed: Symbol not found: _clock_gettime"

### ISSUE THREAD

**Issue by PyPublishing** [desktop/desktop#12920]
### Describe the bug

Whenever I open GitHub Desktop on Macos, I get an error about:

"dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
Referenced from: /Applications/GitHub Desktop.app/Contents/Resources/app/git/libexec/git-core/git-lfs
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Applications/GitHub Desktop.app/Contents/Resources/app/git/libexec/git-core/git-lfs
  Expected in: /usr/lib/libSystem.B.dylib

SIGTRAP: trace trap
PC=0x7fff65b37075 m=5 sigcode=1"

### Version & OS

Version: "Version 2.9.3 (x64)"
OS: OS X El Capitan 10.11.6 (internal production system, but GitHub Desktop claims to support from 10.10 onwards...)

### Steps to reproduce the behavior

1. Double click on GitHub Desktop in the macos "/Applications" folder 
2. See the error message as described above and in the attached screen shot

### Expected behavior

When opening GitHub Desktop, I do expect to not see any error message about "lazy symbol binding failed" or "Symbol not found: _clock_gettime"

### Actual behavior

1. I double click on GitHub Desktop in the macos "/Applications" folder in order to start the application 
2. I am immediately shown the error message as described above and in the attached screen shot

### Screenshots

Please find enclosed the mentioned screen shot displaying the error message.

<img width="715" alt="Bildschirmfoto 2021-09-07 um 15 49 17" src="https://user-images.githubusercontent.com/88194470/132357848-fc098465-1a6d-402f-9178-48d0cf486e1e.png">

### Logs

[2021-09-07.desktop.production.log](https://github.com/desktop/desktop/files/7122081/2021-09-07.desktop.production.log)

### Additional context

This is the complete error message:

dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Applications/GitHub Desktop.app/Contents/Resources/app/git/libexec/git-core/git-lfs
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Applications/GitHub Desktop.app/Contents/Resources/app/git/libexec/git-core/git-lfs
  Expected in: /usr/lib/libSystem.B.dylib

SIGTRAP: trace trap
PC=0x7fff6670d075 m=3 sigcode=1

goroutine 0 [idle]:
runtime.walltime1(0x0, 0xc000000000)
	hostedtoolcache/go/1.16.3/x64/src/runtime/sys_darwin.go:270 +0x4a fp=0xc0001c1db0 sp=0xc0001c1d78 pc=0x4057e4a
runtime.walltime(...)
	hostedtoolcache/go/1.16.3/x64/src/runtime/time_nofake.go:23
time.now(0x45a4c60, 0x4602f01, 0xc0000ae010)
	hostedtoolcache/go/1.16.3/x64/src/runtime/timestub.go:16 +0x25 fp=0xc0001c1de0 sp=0xc0001c1db0 pc=0x406b3a5
time.Now(0x45a4c60, 0xc0000ae010, 0x0)
	hostedtoolcache/go/1.16.3/x64/src/time/time.go:1067 +0x26 fp=0xc0001c1e08 sp=0xc0001c1de0 pc=0x40c8266
github.com/git-lfs/git-lfs/config.NewIn(0x0, 0x0, 0x0, 0x0, 0x4628165)
	work/dugite-native/dugite-native/git-lfs/config/config.go:69 +0xe5 fp=0xc0001c1e88 sp=0xc0001c1e08 pc=0x41aa325
github.com/git-lfs/git-lfs/config.New(...)
	work/dugite-native/dugite-native/git-lfs/config/config.go:61
github.com/git-lfs/git-lfs/commands.Run(0x10)
	work/dugite-native/dugite-native/git-lfs/commands/run.go:97 +0x265 fp=0xc0001c1f20 sp=0xc0001c1e88 pc=0x4514445
main.main()
	work/dugite-native/dugite-native/git-lfs/git-lfs.go:33 +0xec fp=0xc0001c1f88 sp=0xc0001c1f20 pc=0x4520eac
runtime.main()
	hostedtoolcache/go/1.16.3/x64/src/runtime/proc.go:225 +0x256 fp=0xc0001c1fe0 sp=0xc0001c1f88 pc=0x403a556
runtime.goexit()
	hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0001c1fe8 sp=0xc0001c1fe0 pc=0x406e101

goroutine 1 [running]:
runtime.asmcgocall(0x406f8e0, 0xc0001c1d90)
	hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:652 +0x42 fp=0xc0001c1d48 sp=0xc0001c1d40 pc=0x406dd62
runtime.libcCall(0x406f8e0, 0xc0001c1d90, 0x10)
	hostedtoolcache/go/1.16.3/x64/src/runtime/sys_libc.go:48 +0x6c fp=0xc0001c1d78 sp=0xc0001c1d48 pc=0x405848c
runtime.walltime1(0x0, 0xc000000000)
	hostedtoolcache/go/1.16.3/x64/src/runtime/sys_darwin.go:270 +0x4a fp=0xc0001c1db0 sp=0xc0001c1d78 pc=0x4057e4a
runtime.walltime(...)
	hostedtoolcache/go/1.16.3/x64/src/runtime/time_nofake.go:23
time.now(0x45a4c60, 0x4602f01, 0xc0000ae010)
	hostedtoolcache/go/1.16.3/x64/src/runtime/timestub.go:16 +0x25 fp=0xc0001c1de0 sp=0xc0001c1db0 pc=0x406b3a5
time.Now(0x45a4c60, 0xc0000ae010, 0x0)
	hostedtoolcache/go/1.16.3/x64/src/time/time.go:1067 +0x26 fp=0xc0001c1e08 sp=0xc0001c1de0 pc=0x40c8266
github.com/git-lfs/git-lfs/config.NewIn(0x0, 0x0, 0x0, 0x0, 0x4628165)
	work/dugite-native/dugite-native/git-lfs/config/config.go:69 +0xe5 fp=0xc0001c1e88 sp=0xc0001c1e08 pc=0x41aa325
github.com/git-lfs/git-lfs/config.New(...)
	work/dugite-native/dugite-native/git-lfs/config/config.go:61
github.com/git-lfs/git-lfs/commands.Run(0x10)
	work/dugite-native/dugite-native/git-lfs/commands/run.go:97 +0x265 fp=0xc0001c1f20 sp=0xc0001c1e88 pc=0x4514445
main.main()
	work/dugite-native/dugite-native/git-lfs/git-lfs.go:33 +0xec fp=0xc0001c1f88 sp=0xc0001c1f20 pc=0x4520eac
runtime.main()
	hostedtoolcache/go/1.16.3/x64/src/runtime/proc.go:225 +0x256 fp=0xc0001c1fe0 sp=0xc0001c1f88 pc=0x403a556
runtime.goexit()
	hostedtoolcache/go/1.16.3/x64/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0001c1fe8 sp=0xc0001c1fe0 pc=0x406e101

goroutine 34 [syscall]:
os/signal.signal_recv(0x0)
	hostedtoolcache/go/1.16.3/x64/src/runtime/sigqueue.go:165 +0x9d
os/signal.loop()
	hostedtoolcache/go/1.16.3/x64/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	hostedtoolcache/go/1.16.3/x64/src/os/signal/signal.go:151 +0x45

goroutine 35 [runnable]:
main.main.func1(0xc00010e240, 0xc000096000)
	work/dugite-native/dugite-native/git-lfs/git-lfs.go:19
created by main.main
	work/dugite-native/dugite-native/git-lfs/git-lfs.go:19 +0xe7

rax    0x7fff66746290
rbx    0x4c06e80
rcx    0x0
rdx    0x0
rdi    0x7fff66746400
rsi    0x0
rbp    0x700000103890
rsp    0x700000103878
r8     0x7fff6672f04c
r9     0x0
r10    0x70000010367a
r11    0x7fff66746400
r12    0x1
r13    0x1
r14    0x7fff66746400
r15    0xffffffffffffffff
rip    0x7fff6670d075
rflags 0x246
cs     0x2b
fs     0x0
gs     0x0

**Comment by niik** [comment]
Hi @PyPublishing, thanks for opening this. This was reported in https://github.com/desktop/desktop/issues/12436 and unfortunately the only known workaround is to upgrade to a more recent OS (or possibly an xcode install see https://github.com/desktop/desktop/issues/12436#issuecomment-861700032). We're working on updating the docs to reflect this.

The problem is with the version of Git LFS that we ship in the app so if you're not using LFS the error should be safe to ignore.

**Comment by PyPublishing** [comment]
I do understand this.

But it is most unfortunate that the documentation clearly - or in this case wrongly? - claims GitHub Desktop to work from 10.10 onwards:

https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/installing-and-authenticating-to-github-desktop/installing-github-desktop

<img width="761" alt="Bildschirmfoto 2021-09-07 um 16 10 26" src="https://user-images.githubusercontent.com/88194470/132359883-aea1acc6-383e-4ad9-88d2-0b80c2e81358.png">
