### ISSUE TITLE
Allow github desktop to trampoline for git cli, not just itself (?)

### ISSUE THREAD

**Issue by ph0tic** [desktop/desktop#12937]
### Describe the feature or problem you’d like to solve
This is actually more of a question: 

(with regards to https repos and _not_  ssh) This may be a HORRIBLE idea and really really bad, allow github CLI to use the GH Desktop trampoline. My employer has a GHent setup and uses a SSO/mfa solution which Github Desktop Successfully works with. From what I understand for the trampoline solution, Github Desktop is setting up server/port, passing the port to an env variable for the client, and using ASKPASS to get git to use the client with the env var to send/rcv the data - essentially passing back stdout. When its done, it tears down the server and port and thus everything is secure again. This loopback is on localhost.  And thus concludes my simplistic very watered down understanding :). 

github cli cannot take advantage of this because the port is random and only comes up when GH Desktop is doing 'things'. I'm a windows user doing stuff with vscode in windows and various scripting in WSL, so git cli comes up on both sides of the fence for me.

### Proposed solution

To make everything work, I had to use Github Credential Manager (new ver) and setup a PAT. Now i can do everything i wanted to do with cli, but its not exactly connected to GH Desktop. maybe this is a good thing? I'm not sure. 

Is there something that I missed where git cli can use github desktop to handle the authentication? Seamless is always the goal, so the extra steps for the PAT made me wonder what i missed. 

I could not find any documentation stating that having a completely separate PAT authentication for cli using the credential manager is the only path forward when dealing with desktop+cli and there's no way to make git cli to rely on GH desktop's saved authentication. 

Regardless of the answer I receive, documentation stating either "yes, do steps 1-20 to make it work with cli" or "nope; you need to make a pat for http authentication when not using ssh" would be awesome. 

P.S. I love github desktop. thank you so much for making it. best of most worlds 👍

**Comment by niik** [comment]
Hi @ph0tic, thanks for opening this. Your analysis of how our trampoline works is spot on. Unfortunately extending support to other applications is complicated by the fact that each trampoline invocation is performed with a secret token generated just in time by the desktop executable to prevent other network capable applications on the machine from getting hold of the secrets.

Even if we were to find a way to allow other "trusted" apps to generate these tokens the user experience wouldn't be great as it would require the Desktop binary to be running.

So while the idea is interesting I'm afraid it's not what the trampoline was built for and continued investment in tools like [Git Credential Manager Core](https://github.com/microsoft/Git-Credential-Manager-Core) is likely the best path forward.

Thanks for your interest in wanting to improve the Git and GitHub ecosystem
