### ISSUE TITLE
Renaming a branch "looses" (hides) stash

### ISSUE THREAD

**Issue by tordans** [desktop/desktop#12934]
### Describe the bug

1. Create a branch name "test-branch"
2. Stash changes
    `stash@{0}: On test-branch: !!GitHub_Desktop<test-branch>`
   => Stash is visible in Github Desktop
3. Rename branch with shortcut cmd+shift+r to "stash-hidden"
   => **Stash is hidden in Github Desktop**
   `git stash list` shows it with the old branch name.

Possible solutions / Ideas

* On the rename panel and if a stash is preset: Inform that renaming will hide the stash but terminal `git stash pop` will still restore it
* Rename the stash name alongside the branch name so the stash stays visible
* List all stashes in the App so I may find the one that is now hidden – but that is more https://github.com/desktop/desktop/issues/12699

### Version & OS

>Version 2.9.3 (x64)

**Comment by steveward** [comment]
Thanks for the issue @tordans. This was an issue that was reported with our initial stash implementation (https://github.com/desktop/desktop/issues/7283), but GitHub Desktop does show a warning when you rename a branch with a stash (https://github.com/desktop/desktop/pull/7539):

<img width="602" alt="Screen Shot 2021-09-09 at 9 22 25 AM" src="https://user-images.githubusercontent.com/721500/132693760-2a29d1d9-e025-4142-9133-f6730c334f18.png">

We don't show this when renaming a branch that contains a stash that was made on the command line, though. It does look like you made the above stash in GitHub Desktop but I wanted to confirm that wasn't the behavior you were seeing.

**Comment by tordans** [comment]
@steveward you are right, the warning is already there 👍 .

I tested for this while writing the bug description but my test case was flawed 🙄 .

Thanks for taking the time to look into this. I will close the issue since any further improvement will likely be best consolidated with allowing multiple stashes at some point (or never ;)).
