### ISSUE TITLE
Deleted branch in the remote & unused branch in local doesn't get remove after 14 days

### ISSUE THREAD

**Issue by penguinawesome** [desktop/desktop#12932]
Version 2.9.3 (x64) - Windows 10

We are seeing a lot of deleted branch in the remote on our github desktop client and these branches are unused already (meaning we didn't select for a long time and no commits on the local machine), i read somewhere that github desktop auto delete it after 14 days or is there a settings that we need to set? We want to auto delete these branches

![image](https://user-images.githubusercontent.com/8090574/132632497-a9eb84b4-6174-4e65-bd0d-7df601c76567.png)

**Comment by niik** [comment]
Hi @firephantomassasin, thanks for opening this. You're right that GitHub Desktop prunes merged branches where the remote branch no longer exists. The logic is fairly well explained in https://github.com/desktop/desktop/blob/ac3cfab2762f0b94c6f5184c5dc3dcb8e6eb13b7/app/src/lib/stores/helpers/branch-pruner.ts#L130-L249

In short, we attempt to prune branches that meet all the following criteria

- Has been merged into the default branch (typically `git branch --merged main`)
- Hasn't been checked out locally in the last 2 weeks
- Are tracking a remote branch that no longer exists (i.e. the PR  has been merged and the branch on the remote deleted)
- Isn't named such that it's likely to be a default branch (i.e. main, trunk, develop, etc etc).

Can you see anything in the above that would explain why your branches aren't deleted?

**Comment by penguinawesome** [comment]
These branches have been merged under our "dev" branch since our stable development branch is named as "dev", our master acts as more stable and production ready branch. So all these branches in the screenshots have been merged already with our dev branch and has been removed already from the remote branch. 


We are using azure devops git as our remote code repository.

**Comment by niik** [comment]
> These branches have been merged under our "dev" branch since our stable development branch is named as "dev", our master acts as more stable and production ready branch. So all these branches in the screenshots have been merged already with our dev branch and has been removed already from the remote branch.

Then that's likely the culprit here. GitHub Desktop needs to take a pretty conservative approach when it comes to pruning local branches so we want to make sure that the branches have been merged into the default branch (which, if I understand correctly, would be `master` for you).

So the good news is that once the changes make their way from `dev` to `master` those branches should start to get cleaned up. If you try running `git branch --merged master` in your repository you don't see the aforementioned branches, right?

**Comment by givihuda** [comment]
I need to know how to disable this. In one of our projects, I often unfortunately have to keep looking up old merged branch references, and it's just easier to grep search a branch list and check it out than recreate it. Sorry if that's not in best practice for GitHub, but the default way has become more of a nuisance for this project.
