### ISSUE TITLE
Double click shows the full content of files

### ISSUE THREAD

**Issue by abelardovn** [desktop/desktop#12942]
### Describe the feature or problem you’d like to solve
When I git pull, several commits are showed under "History" tab. When I click on any commit, changed files are showed. I would like to see its full content when I double-click on those files.

### Proposed solution
To show the entire content of any file when I double click on it.

**Comment by niik** [comment]
Hi @abelardovn, assuming you mean showing the entire content of the file _within GitHub Desktop_ you can do that by right clicking on the diff and selecting "Expand Whole File".

![image](https://user-images.githubusercontent.com/634063/133074446-bfb0b39b-50d8-4c58-8459-59996cd3cae4.png)

If you instead mean to open the file in an external editor that's been discussed in https://github.com/desktop/desktop/issues/2620 and we don't have any plans to implement that but feel free to give it a 👍 reaction if it's something you'd like to see.
