### ISSUE TITLE
Cannot remove upstream repo

### ISSUE THREAD

**Issue by JamesCatt** [desktop/desktop#12958]
### Describe the bug
After adding a repo (from Github Enterprise) that has been forked from an upstream repo, it seems to be not possible to remove the upstream from Github desktop (the upstream repo has since been deleted). There's no option for setting it in the menus, and removing it via command line (`git remote rm upstream`) only works until Github Desktop is restarted—then the upstream is re-added.

This results in fetch attempts failing because the upstream repo is unreachable—I have to open a command prompt and fetch manually or remove the upstream after every restart.

### Version & OS

Github Desktop v2.9.3 x64
MacOS 11.4

### Steps to reproduce the behavior

1. Add a repo that has been forked from an upstream
2. Delete the upstream
3. Attempt to fetch with Github Desktop (fails)
4. Remove the upstream via command line (`git remote rm upstream`), fetch now works
5. Restart Github Desktop

### Expected behavior

Github Desktop does not re-add the removed upstream repo when restarting, and/or should provide the ability to edit/remove it in the Repository Settings menu (it only displays origin, not upstream).

### Actual behavior

Github Desktop re-adds the upstream repo after every restart, and has no menu/settings options for removing it.

### Screenshots

![image](https://user-images.githubusercontent.com/20130162/133310289-f66f9a80-c0b7-4c82-a834-5085106d5fc0.png)
![image](https://user-images.githubusercontent.com/20130162/133310313-ec26058c-7da3-4050-b0d7-c7681be53001.png)

### Logs

![image](https://user-images.githubusercontent.com/20130162/133311058-ce0b27b1-a1ba-46f2-bd82-9c9dbf4ade75.png)

**Comment by steveward** [comment]
Thanks for the report @JamesCatt. This is being tracked in https://github.com/desktop/desktop/issues/3715, I'll bump up that issue with a reference to this.
