### ISSUE TITLE
Desktop app is not recognizing new GitHub PAT format

### ISSUE THREAD

**Issue by mike-copley-atg** [desktop/desktop#12959]
### Describe the bug
When generating a new personal access token for use with GitHub desktop, the app does not recognize the token and fails to authenticate with the GitHub service.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@mike-copley-atg thanks for the issue. You don't need to generate an access token to log in to GitHub Desktop. You can go to the `Accounts` view in the Preferences and log in via the browser flow. Let me know if you run into any issues.

**Comment by mike-copley-atg** [comment]
Thank you Steve for that helpful tip.  I was not aware of that preference. I am now working again.

Michael Copley
Senior Software Engineer
Microsoft Gaming Developer Advanced Technology Group
