### ISSUE TITLE
Multi-Window Support

### ISSUE THREAD

**Issue by yakovmanshin** [desktop/desktop#12955]
### Describe the feature or problem you’d like to solve

It’d be great to have GitHub Desktop support multiple windows, so repositories could be opened simultaneously and placed in different spaces (virtual desktops).

### Proposed solution

Enable support for multiple app windows.

Users working on multiple projects at once will no longer need to move the GitHub Desktop window from one space to another, switch between repositories, etc.

**Comment by niik** [comment]
Hey, thanks for reaching out! This looks very similar to the request in https://github.com/desktop/desktop/issues/3606 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date with any development happening in that area.

By cross-referencing in this comment we can associate your request with #3606 but you may also add a 👍 reaction to that issue to signal your interest.

**Comment by Asvsmadhav** [comment]
😶
