### ISSUE TITLE
Please separate fetch origin and push origin to 2 buttons

### ISSUE THREAD

**Issue by gitlcl** [desktop/desktop#12963]
### Describe the feature or problem you’d like to solve

Currently 【 fetch origin 】button auto switch between【  fetch origin 】and 【push origin 】 buttons ,which may leads to mistake  operation.
For example , I made some draft commits then i want to fetch the latest status of origin  to see if there any update, but that button has  auto changed to 【 push origin 】and i didn't notice that, then my click will push my draft commits to origin by mistake.

### Proposed solution

Please separate【 fetch origin 】and 【push origin 】to 2 buttons,  fetch origin with green background , push origin with red background . 
Benefits : 
1. user can do what they indeed want to 
2. different color help to distinguish the operation
3. red imply push origin is a little bit dangerous , user have to be careful of what he/she is doing

### Additional context
This is why i didn't use this App after i installed it for 1 year.
![image](https://user-images.githubusercontent.com/9178353/133576762-d04bba22-93ac-40f3-a767-684a14b8ac25.png)

**Comment by niik** [comment]
Hey, thanks for reaching out! This looks very similar to the request in #10444 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date with any development happening in that area.
