### ISSUE TITLE
[Feature Request] Override / Switch between an already same-named branch from fork to upstream

### ISSUE THREAD

**Issue by RedDevilus** [desktop/desktop#12961]
### Describe the feature or problem you’d like to solve

The ability to change from local/master such as RedDevilus/desktop and upstream/master such as desktop/desktop
![image](https://user-images.githubusercontent.com/24227051/133508620-dbddb149-ec5f-4281-945d-4e141d77c4bb.png)

### Proposed solution

Easily switch between local changes and easy fetched upstream/master commits
![image](https://user-images.githubusercontent.com/24227051/133508823-332f2461-6f1f-453e-87eb-5ef93e1607c7.png)
![image](https://user-images.githubusercontent.com/24227051/133508868-092872dc-0b84-4de1-8fa9-7c513abffcb0.png)
Without it locking up, as it sees a duplicate branch even though the origin is different.
### Additional context

It would help me and others doing less steps if you just want to check out upstream without having to delete the clone / create a new clone. I don't want to publish the branch anyway, workaround is to have a branch named that's not in upstream but that's not optimal.

**Comment by steveward** [comment]
Thanks for the issue @RedDevilus, this is being tracked in https://github.com/desktop/desktop/issues/4527. You can follow along there for updates about this.
