### ISSUE TITLE
Changing commit message from history

### ISSUE THREAD

**Issue by maifeeulasad** [desktop/desktop#12967]
### Describe the feature or problem you’d like to solve

Changing commit message from history.

### Proposed solution

Accidentally, pushed with some commit message? Need to rename them. It will be easier to do so, from the favorite GitHub Desktop. May require `--force` push like popup.

### Additional context

Something like this: https://stackoverflow.com/a/41987851/10305444

**Comment by steveward** [comment]
Thanks for the issue @maifeeulasad. You can amend the most recent commit in your repository -- see the [documentation](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/amending-a-commit) for how to do that.

At this time this is not on our roadmap to provide an interactive rebase that would allow you to change commit messages further back in your repository's history, but you can leave a 👍🏻 on https://github.com/desktop/desktop/issues/12354 to indicate your interest in this feature.
