### ISSUE TITLE
View not refreshing when active file changes

### ISSUE THREAD

**Issue by thinkyhead** [desktop/desktop#12962]
### Describe the bug
- The "diff" view is not refreshing when the file being displayed is altered on disk.
- The "diff" view is not refreshing after selected (cherry-picked) lines are committed.

### Version & OS

2.9.4-beta2 (arm64) on macOS 11.6

### Steps to reproduce the behavior

1. Select a file so it appears in the "diff" view.
2. Go to another app, edit, and save changes.
3. Return to GitHub Desktop.

-- or --

2. Select some changed lines in the "diff" view for cherry-picking.
3. Create a commit with the selected lines.

### Expected behavior

- In the first case, the "diff" view should update to show the new changes.
- In the second case, the "diff" view should update to hide the committed changes.

### Actual behavior

- The view stays the same, so you must select a different file and then switch back to force an update.

### Additional context

- This has only started to occur in this specific update, which fixed the layout issues.

**Comment by niik** [comment]
Thank you for reporting this @thinkyhead, I've confirmed the problem and I'll open a PR to address it in a minute!

**Comment by thinkyhead** [comment]
Thanks! In my own playing around with Electron (VSCode plugin) I use a file watcher so the plugin gets a notification on file or folder change, and this is better than just refreshing when focus goes away and returns, because it still works in the background. Better for situations where apps are open side-by-side.
