### ISSUE TITLE
Older app versions stays in the hard drive instead of getting deleted after update.

### ISSUE THREAD

**Issue by deb1992** [desktop/desktop#12975]
### Describe the bug
Older app versions stays in the hard drive instead of getting deleted after update.

### Version & OS

Windows 10 64 bit - Pro. Github version 2.9.3

### Steps to reproduce the behavior

1. Go to 'C:\Users\<username>\AppData\Local\GitHubDesktop'
2. check after update, you will find teh older version folder still present not deleted. It will keep consuming my SSD space.

### Expected behavior

The older version folder should have been deleted.

### Actual behavior

The older version folder with data still remains. Had to delete it manually.

### Screenshots

![image](https://user-images.githubusercontent.com/89631195/133726133-e86405ae-1616-4c05-a0c0-41a0e7b514d7.png)

**Comment by niik** [comment]
Hi @deb1992, thanks for opening this. This is a result of how the auto-update framework on Windows works, see https://github.com/Squirrel/Squirrel.Windows/issues/589#issuecomment-180075676

GitHub Desktop doesn't have control over Squirrel.Windows so while I imagine there's good reason for why it's storing the last version you could file an issue with Squirrel.Windows or possibly Electron if you believe it should behave differently.
