### ISSUE TITLE
No such interface “org.freedesktop.Secret.Collection” on object at path /org/freedesktop/secrets/collection/login

### ISSUE THREAD

**Issue by Slips-PC** [desktop/desktop#12971]
### Describe the bug
Attempting to sign in to my GitHub account via the desktop app provides the above error and prevents me from accessing a variety of options in the taskbar.

### Version & OS
Version 2.9.3-Linux1
OS: Arch Linux

### Steps to reproduce the behavior
1: Click Options
2: Click "Sign In" on the Accounts > Github.com tab.
### Expected behavior

It would open a link in Firefox, which would authenticate the app, thus allowing my Github account to be accessed.

### Actual behavior

The link was opened in firefox, but returning to the Github Desktop app provides this error:

No such interface “org.freedesktop.Secret.Collection” on object at path /org/freedesktop/secrets/collection/login

Furthermore, after this popup, I can no longer access multiple options in the taskbar, including the Options modal.

### Screenshots

![image](https://user-images.githubusercontent.com/59989951/133707534-9eee2678-1f1d-4233-8266-ca7cff3b7031.png)

### Logs

Cannot provide, as Help > Open logs in file manager hangs the app.

### Additional context

N/A.

**Comment by niik** [comment]
Hi @Slips-PC, issues related to the unofficial Linux fork of GitHub Desktop can be filed here:

https://github.com/shiftkey/desktop/issues

At this time we only officially provide support for macOS and Windows.
