### ISSUE TITLE
Scroll position is shared across files

### ISSUE THREAD

**Issue by magiblot** [desktop/desktop#12980]
### Describe the bug
A repository often has several changed files. When I click on a changed file in order to see its diff, the scrollbar position varies according to the previous diff I was looking at.

### Version & OS

Version 2.9.3, Arch Linux x64.

### Steps to reproduce the behavior

1. Have a repository with several changed files, where the changes in each file are big enough that the diff needs to use scroll bars.
2. Click on a changed file and scroll the diff down to the bottom.
3. Click on another changed file.

### Expected behavior

The diff should be scrolled back to the top after clicking on a different changed file. Ideally (but I can live without it): if that diff had already been viewed before, the scroll position should be restored from that time.

### Actual behavior

The second diff is scrolled near the bottom because the previous one also was scrolled to the bottom.

### Screenshots

1. First diff (scrollbar is at the top).
![Screenshot_20210917_230500](https://user-images.githubusercontent.com/20713561/133853713-74f362ae-6534-4cfd-9d1e-517d8db0aaf4.png)
2. Scroll it to the bottom.
![Screenshot_20210917_230522](https://user-images.githubusercontent.com/20713561/133853732-d3ad2deb-a52a-46f5-85b3-0cdde1d76c09.png)
3. After clicking on a different changed file, the diff is still scrolled to the bottom (instead of being at the top).
![Screenshot_20210917_230537](https://user-images.githubusercontent.com/20713561/133853762-48c4e599-6a94-4328-adb4-1897ceb36591.png)
### Logs

N/A.

### Additional context

None.

**Comment by sergiou87** [comment]
Thanks for the report @magiblot! We were able to reproduce the bug 😄

**Comment by magiblot** [comment]
¡Muchas gracias!

**Comment by Klp2121** [comment]
😆

**Comment by meshl555** [comment]
None .

**Comment by meshl555** [comment]
None.

**Comment by meshl555** [comment]
None.

**Comment by meshl555** [comment]
None.

**Comment by meshl555** [comment]
None.

**Comment by meshl555** [comment]
None.

**Comment by meshl555** [comment]
None.

**Comment by meshl555** [comment]
None.
