### ISSUE TITLE
GitHub Desktop won't install on Windows 10

### ISSUE THREAD

**Issue by matthew-wilford** [desktop/desktop#12987]
### Describe the bug
Attempted multiple times to download and install GitHub Desktop.  Windows dialogue box states that "Installation has failed." It prompts me to check the setup log for more information. 

### Version & OS

I assume that the GitHub Desktop app is the current release as I am downloading it from the GitHub website.  I am running Win 10 Home version 21H1 OS build 19043.1237.  Laptop is i5, 64 bit

### Steps to reproduce the behavior

1. Go to 'https://desktop.github.com/'
2. Click on 'Download for Windows  (64 bit)'
3. Run "GitHubDesktopSetup-x64"
4. Receive dialogue box with Installation failure message and link to Setup Log file

### Expected behavior

GitHub Desktop installation and ability to launch.
### Actual behavior

It Will not install.

### Screenshots

See attached files

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context
Also turned off anti-virus software.  Installed latest Windows updates.

![GitHub Dialogue Box - Install error](https://user-images.githubusercontent.com/78808294/133939923-d3ee3607-d2a0-4bd8-8e65-9487b7bab97a.PNG)
[SquirrelSetup - InstallError.log](https://github.com/desktop/desktop/files/7192744/SquirrelSetup.-.InstallError.log)

**Comment by sergiou87** [comment]
@just-MattW it looks like another instance of the installer is running (and probably stuck) so the new instance is unable to install it and that's when you get the error.

Could you tried rebooting or looking for the other instance in the Task Manager? 🤞

**Comment by matthew-wilford** [comment]
@sergiou87 thanks for replying! I followed your directions. I restarted my system. Then, I attempted to install GitHub Desktop again while monitoring the Task Manager. The same installation failure occurred. In Task Manager, one application appeared titled "Update." There was only one instance of this application running during the installation.

**Comment by sergiou87** [comment]
That's bad 😞 

Is this the first time you install GitHub Desktop? Or are you trying to update an existing installation? If so, please try to uninstall the existing installation first, maybe that helps 🤔 

Otherwise, I'd wonder if there is anything special about your setup that you can think of?

**Comment by matthew-wilford** [comment]
This is the first time I have tried to install GitHub Desktop. I have also tried to delete the GitHub Desktop Launcher. Then, download it again and try to install GitHub Desktop. It has resulted in the same outcome. There is nothing special about my setup, from what I can tell. I have the ACER Aspire 3 laptop. The specific model is A315-53-50Y7.

**Comment by steveward** [comment]
@just-MattW are you running any antivirus software outside of the standard Windows Defender that could be interfering with the installation process?

I'd also recommend deleting the `Temp` directory to clear out any leftover lock files since that's being referenced in the installation error log. Open up a command prompt as an administrator and run this command:

`rmdir C:\Users\matth\AppData\Local\Temp /s`

Then try installing GitHub Desktop again. Let us know if that helps.

**Comment by CodeSharp5** [comment]
Did anyone read the SquirrelSetup*.log?  
Line 3: 20504> 2020-04-15 21:55:43> Program: About to install to: C:\Users\matth\AppData\Local\Discord
Why would GitHub Desktop's installer be writing in this guy's Discord folder?

**Comment by steveward** [comment]
@CodeSharp5 Discord also uses Squirrel, which is why there you are seeing that in the log file. This Squirrel installer log will log output from any application that uses Squirrel.

**Comment by CodeSharp5** [comment]
So the installer log is the cumulative report of everything that Squirrel has installed?  I was thinking it was just the log for the current app being installed, and freaking about it touching other apps suspiciously.
Thanks.

**Comment by matthew-wilford** [comment]
Hello everyone, sorry for the late reply. This weekend, I am replacing my laptop's HDD with an SSD. Hopefully, this resolves the issue. Someone I know believes that the issue is related to fragmentation in the HDD. I have had problems in the past installing a few apps (Logitech Options and Scenebuilder). If this does not resolve the issue, I will likely buy a new laptop because my laptop is aging anyway.

**Comment by matthew-wilford** [comment]
> Thank you for your issue! We haven’t gotten a response to our questions above. With only the information that is currently in the issue, we don’t have enough information to take action. We’re going to close this but don’t hesitate to reach out if you have or find the answers we need. If you answer our questions above, a maintainer will reopen this issue.

I did replace the HDD with an SSD and the issue was resolved. I am planning to give away my laptop, anyway.

**Comment by adotaiman** [comment]
i download github desktp but its installation has failed every time

**Comment by steveward** [comment]
@adotaiman please open a new issue and fill out the template so we can assist you further. Thanks!

**Comment by avatarxargo** [comment]
Since this is the top search result for this issue I will leave my resolution to the problem even though the thread is closed.

In my case, I've had Github Desktop for a while and then it stopped working and would not launch. No suggested method worked, but when I went to clear github desktop appdata files, Windows told me that one library file was being used by another application (some keyboard LED driver, presumably also using Squirrel Installer). After I terminated that process and deleted said library file, the installer started working properly.

Hope that helps someone.

**Comment by gandradeaglh** [comment]
check antivirus.  in my case i had to turn off antivirus

**Comment by Frank-HACKs** [comment]
ive been trying to download github desktop for almost a week now but it keeps on showing this
![error photo](https://github.com/user-attachments/assets/d0d5e8ac-5886-4ff3-942a-3730360e2996)

**Comment by bussi2009** [comment]
> check antivirus. in my case i had to turn off antivirus
 
this solved the problem thanks

**Comment by nassim6321** [comment]
The same problem and the message of error...
Stop antivarus or firewall program temporarily, install the program everything as it fine. reactivate your protection,

**Comment by greg251354** [comment]
cannot instal github desk top as my computer keeps telling me i must allow cookies and have checked all brousers
