### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#12983]
### It's very useful to have the ability to add multiple accounts with different SSH keys, like a personal account and work account.

The user had the ability to go to the accounts menu under the preferences and select a different Github account from a menu or dropdown list.
By adding a new account, the user had the ability to add or point to a new ssh key that differs from another account.
And add a menu beside the branch and the Push/Pull menu a new menu that displays the selected account and the ability to switch between them, and its design could be to be like the branch selection menu.

### In the accounts menu under the preferences add the ability to add a new account with a new ssh key by clicking on a button that opens an add new account dialog in this dialog the user will add this GitHub account email address display name and the ssh key.

This will help the users managing two different accounts with two different ssh keys from GitHub Desktop without using the cmd/Terminal, then go to the preferences Git to change their email address and their display name.

**Comment by steveward** [comment]
Thanks for the feedback @hadiabouhamzehvc. We are tracking feedback for supporting multiple accounts in https://github.com/desktop/desktop/issues/3707. You can leave a 👍🏻 in that issue to indicate your desire to see this implemented.
