### ISSUE TITLE
Allow resizing of Squash Commit Textarea

### ISSUE THREAD

**Issue by tordans** [desktop/desktop#12989]
### Describe the feature or problem you’d like to solve

The window to squash commit has a fixed height. Therefore, the textarea inside also has a fixed height. This makes it hard to consolidate two commit messages that are more than just a few lines.

### Proposed solution

Idea 1: Allow resizing the whole panel, by grabbing the panel corner – which in turn should increase the size of the textare.

Idea 2: Allow resizing of the textarea, by grabbing the corner of the textarea (like in the browser) – which in turn should resize the panel.

Idea 3, unrelated: The initial height of the window could be bigger, depending on the amount of text in it.

### Additional context

<img width="453" alt="Bildschirmfoto 2021-09-20 um 07 35 40" src="https://user-images.githubusercontent.com/111561/133961089-a97f3904-f2f4-4f55-98f0-be14d3c715fb.png">

This is related to https://github.com/desktop/desktop/issues/2546 which introduce resizing of the commit message.

**Comment by sergiou87** [comment]
Thank you for your suggestion @tordans !!! ❤️ 

This seems to be mostly covered by #1646 so I'll close this in favor of #1646 adding your feedback there.
