### ISSUE TITLE
Restore Stash even with changes present, if overlaps are obviously impossible

### ISSUE THREAD

**Issue by pedropsi** [desktop/desktop#12994]
### The stash could be restored, even with changes present, if conflicts are impossible

The user made some uncommited changes to file A, while the stash stores some changes in file B.

From the user's perspective, there is nothing preventing the stash from being restored, as there is no way the changes in file A would ever conflict with those in file B.

So it can be a bit disappointing/annoying that the UI refuses to restore the stash just because "changes are present". Especially if it's not convenient to commit all changes to A at this point. 

![image](https://user-images.githubusercontent.com/36260325/134026856-8c892502-d326-4f56-b0ef-9144644e1786.png)

### Current workaround

A workaround exists, eg. commiting A, restoring B, commiting B, squashing A+B, undoing the squashed commit A+B. But users may not be that creative and may be frustrated with the inconvenience of doing this too often.

### Proposed solution

The stash should be restored, resulting in two uncommited changes: the original ones (A) plus the unstashed ones (B).

### Extended solution

One could extend the logic to a set of uncommited files (A1, A2, A3...) vs another set of stashed files (B1, B2, etc..)  as long as there are no overlaps.

Taking this idea even further, one could think not on a file-by-file basis, but even a line-by-line basis.

**Comment by samuelko123** [comment]
@sergiou87 Can I give it a try?

**Comment by sergiou87** [comment]
@samuelko123 be my guest! 😄
