### ISSUE TITLE
Issues Deleting Discord Messages

### ISSUE THREAD

**Issue by bunnyyx** [desktop/desktop#12999]
Version 2.9.3 (x64)

Total messages found: 276
Ended because PAI returned an empty page

I use it in Chrome

Not very well versed with this kind of stuff. Not sure why all of a sudden today it stopped working. 

I delete messages all the time
![discord](https://user-images.githubusercontent.com/74756547/134151638-95b604ad-8d24-412f-8345-06e104585fec.png)

**Comment by niik** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
