### ISSUE TITLE
Diff Doesn't Re-render when Making GitHub Desktop Active

### ISSUE THREAD

**Issue by say25** [desktop/desktop#12996]
### Describe the bug

Diff Doesn't Re-render when Making GitHub Desktop Active

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

Version 2.9.4-beta2 (x64)
Windows 10

### Steps to reproduce the behavior

1. Make changes to a file
2. View the changes in GH Desktop
3. Make more changes to the file
4. Switch back to GH Desktop and see that the changes aren't represented 

### Expected behavior

Diff rerenders when making GitHub Desktop active like it previously did

### Actual behavior

Diff rerenders only after switching active file/diff

### Screenshots

![image](https://user-images.githubusercontent.com/7467062/134036047-3ebc62e5-5153-4e43-b776-881bb4dcfc16.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

I believe this change was introduced recently

**Comment by billygriffin** [comment]
I think this was fixed by https://github.com/desktop/desktop/pull/12964, but please feel free to reopen if not @say25!
