### ISSUE TITLE
GitHub Desktop encountered an error Error: spawn cmd.exe ENOENT

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#13005]
How can i resolve this?

Error: spawn cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Version: 2.9.3
OS: Windows 10.0.17763

![imagem_2021-09-22_133240](https://user-images.githubusercontent.com/70543348/134393032-5cc3f044-dde9-407f-b644-f72e89d1830e.png)

**Comment by steveward** [comment]
Thanks for the report @Arthur-Vinicius. Just to clarify -- is this error only occurring when you attempt to launch Visual Studio Code from GitHub Desktop (i.e. `Repository` > `Open in Visual Studio Code`)?

Could you open the command prompt and share the output of `echo %PATH%`?

If `System32` is not in your PATH, you will see that ENOENT error. You will need to edit your PATH by following [this article](https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/) and adding the following line:

`C:\Windows\system32`

Let me know if that doesn't get things working!

**Comment by ghost** [comment]
C:\Users\arthursouza>echo %PATH%
C:\app\suporte\product\11.2.0\client_1\bin;C:\Users\arthursouza\AppData\Local\Microsoft\WindowsApps;C:\Users\arthursouza\AppData\Local\GitHubDesktop\bin;C:\Users\arthursouza\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\arthursouza\AppData\Local\Programs\Git\cmd;C:\Users\arthursouza\AppData\Roaming\npm

C:\Users\arthursouza>echo %PATH%
C:\app\suporte\product\11.2.0\client_1\bin;
C:\Users\arthursouza\AppData\Local\Microsoft\WindowsApps;
C:\Users\arthursouza\AppData\Local\GitHubDesktop\bin;
C:\Users\arthursouza\AppData\Local\Programs\Microsoft VS Code\bin;
C:\Users\arthursouza\AppData\Local\Programs\Git\cmd;
C:\Users\arthursouza\AppData\Roaming\npm

**Comment by steveward** [comment]
@Arthur-Vinicius can you confirm when this error is occurring?

**Comment by ghost** [comment]
When i click to open in vscode.

**Comment by steveward** [comment]
@Arthur-Vinicius thanks -- I don't see `system32` in your PATH so you will need to add that in order to get this working.

**Comment by ghost** [comment]
when I go to the advanced settings, this appears:

![imagem_2021-09-22_174816](https://user-images.githubusercontent.com/70543348/134426615-fe039cd3-e106-47ed-9d8e-8c3603b00308.png)

i'm gona try solve this...

**Comment by sergiou87** [comment]
Seems like this might be an issue with your Windows configuration and not specific to GitHub Desktop, so I'll close this, sorry! 😅
