### ISSUE TITLE
No syntax highlighting for HAML

### ISSUE THREAD

**Issue by alexanderadam** [desktop/desktop#13009]
### Describe the feature or problem you’d like to solve

There's no syntax highlighting for HAML files in changed files overview.

### Proposed solution

People using HAML would be able to have the advantage of helpful syntax highlighting.

**Comment by Rpndj** [comment]
[SyntaxHighlight_GeSHi-REL1_36-8ec43c6 (1).tar.gz](https://github.com/desktop/desktop/files/7220734/SyntaxHighlight_GeSHi-REL1_36-8ec43c6.1.tar.gz)
****

**Comment by niik** [comment]
Hi @alexanderadam, thanks for reaching out! It looks like we currently don't have a mapping between the file extension for haml and the syntax highlighting mode. Would you like to contribute support for that mapping? We have some documentation in https://github.com/desktop/desktop/blob/development/docs/technical/syntax-highlighting.md which should let you get started and https://github.com/desktop/desktop/blob/development/app/src/highlighter/index.ts#L43 contains all the currently defined modes which should give you a good idea of what needs to be done to support haml.

**Comment by alexanderadam** [comment]
Hi @niik,

thank you for the fast response! 🙌 

> Would you like to contribute support for that mapping?

[Something like this](https://github.com/desktop/desktop/pull/13015)? I'm not sure I did it right. 🙈 
I got [the MIME type from CodeMirror documentation](https://codemirror.net/mode/haml/index.html).
