### ISSUE TITLE
I can't squash commits in Github Desktop anymore

### ISSUE THREAD

**Issue by Robinson664** [desktop/desktop#13003]
### Describe the bug
I can't squash commits in Github Desktop anymore.  I used to be able to, but I haven't been able to for a while.

### Version & OS

Version 2.6.6
Windows 10 Enterprise

### Steps to reproduce the behavior

I just followed the steps on this page https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits

1. Go to "History" tab
2. Shift+click multiple commits

### Expected behavior

I expect multiple commits to be selected, but only the most recently clicked commit will be selected.  I also expect that the right-click menu will include some options for squashing commits, but it only includes "Revert changes in commit", "Create tag...", "Copy SHA", and "View on Github"

### Actual behavior

Only one commit is ever selected no matter if I shift+click, or control+click, or click and drag.

### Screenshots

N/A

### Logs

N/A

### Additional context

None

**Comment by yesseruser** [comment]
Shift-clicking is going to select all commits from wherever you clicked first, to wherever you clicked second. It is range-selecting. Try CTRL-clicking to select multiple commits.

**Comment by sergiou87** [comment]
Hi @Robinson664 !! 👋 

> Version 2.6.6

If that's correct and you're using 2.6.6, I'm afraid you're using an old version of GitHub Desktop that doesn't support commit squashing 😅  Squashing was introduced in v2.9.0. The app should be able to auto-update from the About dialog, otherwise, you can go to https://desktop.github.com/ to download the latest version.

I hope that helps! 😄

**Comment by Robinson664** [comment]
@sergiou87 please read my bug report more closely.  In it I mentioned that I used to be able to select multiple commits in the "History" tab.  I don't know what changed, but now I can only select one at a time.  Is there some setting that allows me to select multiple commits?  As I said in my bug report, in the "Actual behavior" section, only one commit is ever selected no matter if I shift+click, or control+click, or click and drag.

**Comment by sergiou87** [comment]
@Robinson664 if the version number you provided is correct, it's normal you cannot select multiple commits. That was enabled when cherry-picking was released, in version 2.7.1. There is no setting for that.

How is it possible that you could do all that stuff before and not now? I have no idea but sounds like you were in a newer version and somehow you switched to an older one (maybe you have 2 installations in your machine somehow? or you restored a backup?)

Is it correct that you're using 2.6.6?

**Comment by Robinson664** [comment]
Yes version 2.6.6.  I don't know what version I was using when this worked before.  I don't remember ever changing versions.  I'm behind a corporate firewall so I can't upgrade.  I'll just have to use the command line to squash commits.

**Comment by sergiou87** [comment]
Hmmm, maybe the admin who manages your machine switched to a previous version for whatever reason 😕  If possible, I'd try to contact that person and ask them to upgrade the app. I'm sorry I can't be of more help!
