### ISSUE TITLE
Stopped syncing with actual repository

### ISSUE THREAD

**Issue by dragonsarebest** [desktop/desktop#13008]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior
pull new files from a branch that a friend is working on
Write a clear and concise description of what you expected to happen.
pull all changes
### Actual behavior
new files arent showing up, no new updates but the repository DOES have new files
Write a clear and concise description of what actually happened.
it's not recognizing theres an update that was pushed to github
### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by sergiou87** [comment]
Hi @dragonsarebest ! Can you confirm if your friend has pushed their changes before you tried to pull them?

If that's the case and still doesn't work, have you tried running `git pull` from the command line?

Also, which version of GitHub Desktop are you running?

Thank you!!

**Comment by dragonsarebest** [comment]
Ah yeah sorry bout that it turned out his internet was simply being slow. Problem resolved 😅


Sent from Yahoo Mail for iPhone


On Thursday, September 23, 2021, 3:13 AM, Sergio Padrino ***@***.***> wrote:




Hi @dragonsarebest ! Can you confirm if your friend has pushed their changes before you tried to pull them?

If that's the case and still doesn't work, have you tried running git pull from the command line?

Also, which version of GitHub Desktop are you running?

Thank you!!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
