### ISSUE TITLE
MadCap Flare

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#13012]
Hello,

I'm attempting to push files to a GITHUB repository from MadCap Flare. Each time I attempt to push files, GITHUB launches a login screen that asks me for my username and password. When I enter my username and password into the GIBTHUB login dialog box and presses enter, I get an error message. Subsequent attempts to login produce error messages. Yes, I am using the correct username and login. I cannot push project files and folders to GITHUB. Please advise.

**Comment by niik** [comment]
Hi @sdsasse-cx, thanks for reaching out. I'm afraid I'm not familiar with MadCap Flare. This is the repository for the open source client GitHub Desktop, it sounds to me like your issue occurs when you try to publish changes from within the MadCap Flare application which we're unable to help you with. I'd suggest contacting the publishers of the software directly to see if they can help.

I will note however that GitHub.com recently updated its policies to not allow password-based authentication to its Git services, that could be what you're running into. See https://github.blog/changelog/2021-08-12-git-password-authentication-is-shutting-down/ for more information on that.

Best of luck!

**Comment by ghost** [comment]
Thank you. I’ll give it a shot. Have a great day.

Best regards,

Doug Sasse

From: Markus Olsson ***@***.***>
Sent: Friday, September 24, 2021 2:27 AM
To: desktop/desktop ***@***.***>
Cc: Sasse, Stuart D. ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [desktop/desktop] MadCap Flare (#13012)

Caution, the source of this email is outside of Intrado. Please use caution opening any attachments. Hi @sdsasse-cx, thanks for reaching out. I'm afraid I'm not familiar with MadCap Flare. This is the
External ***@***.******@***.***>)
  Report This Email<https://shared.outlook.inky.com/report?id=aW50cmFkby9zZHNhc3NlQHdlc3QuY29tLzU5MjYxZGFjMTA3NWMxMjY5MmI3NGU2MDZjYzE5NDVlLzE2MzI0Njg0NTkuMzM=#key=2006bff40dea467bde6542c74c64b70a>  FAQ<https://getskout.com/emailprotectionfaq/>  Skout Email Protection<https://getskout.com/emailprotection/>

Caution, the source of this email is outside of Intrado. Please use caution opening any attachments.

Hi @sdsasse-cx<https://shared.outlook.inky.com/link?domain=github.com&t=eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eJxVj29rgzAQxr9LXrspii8qDDroX2gyCnVFKUiaXGts1JGcm8vYd18sg7F3d_c8z93vvggCb5UkGVEdGi57EkwVmI5rkl24thAQ8HLXo7oowVH1nZ1fFdbD-VH0rfdP6X-DwfgsqRHfbHYKT-GfeAqttNxaeBCjN77kJOsGrQOCtQGOlYZ38NnIQ0xb-TGNRLu6nT9nrtywWiRM7zdSi2Q_FPEMdy5PaVOM5XrV0MNzwo509H1K223C1nlMF2VTuGXKFq9655YxdduINdeIHW4DdfRpYrVgKmi50hWX0oC1_u4v5PwDLN5_-v4BhdZkrw.MEQCIEV_7KVj8k3YeNXkBk9RtntX7dez7N8ElOODf1Ys81a6AiBLMEZouksQ2XZRvIn4WhxXL9Rylz6F-P3nD4c_Jk91gg>, thanks for reaching out. I'm afraid I'm not familiar with MadCap Flare. This is the repository for the open source client GitHub Desktop, it sounds to me like your issue occurs when you try to publish changes from within the MadCap Flare application which we're unable to help you with. I'd suggest contacting the publishers of the software directly to see if they can help.

I will note however that GitHub.com recently updated its policies to not allow password-based authentication to its Git services, that could be what you're running into. See https://github.blog/changelog/2021-08-12-git-password-authentication-is-shutting-down/<https://shared.outlook.inky.com/link?domain=github.blog&t=eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eJxVUF1rwjAU_S95NmttKczCwIGfYDIEnSgFiU1sU9NEkpvpOvbfl4ovezv3nnM4594fBIK1kqMcSQ2WcYMGPRJWM4XyM1NODJAItDYgz7JkII1240pC7U8vpWmDvnf_W3gbvKgGuLq8iIroSZ6UqYqorJmuxAMmcTLE8SseJjhI8JU5dzOWY-ahFhqeaVg67GoPIHWFubnpIgoZH1uUa6_UAEFtBYOjEl8ixMahf1-I7bK4bGeX0_eoOyxoXaZUrRdclena75MRrLptRpr9_TCfNWTzntIduYc5I-0ypfNtQiaHZt9NMzr5VKtumpBuGdOmiunm4klH3voznbBH0TKpjoxzK5wLuY67cIYY34SDxzt-_wC1zHlt.MEYCIQD7u-gIGarw4lXeSTc3LgLNssBl-v1UWGWC_J3MqEbZzAIhAMg_W5k-jP_0kt7sgu-FSZtWSVF4KrgaEDAlbCNYOkV2> for more information on that.

Best of luck!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://shared.outlook.inky.com/link?domain=github.com&t=eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eJxVT11vgkAQ_C_XV1sQiq0kTWziZ-JdY6I1GhJycqscHGDYpbWY_vcevrR929mZ2Z25MgJZaMVCpkuqpapYr5ugLqVh4VEahB4DS5cV6aNOJOmqxNFJU9ocHpKqsPrO_W_R1NbLUqIzhpETOb9k5CjAnKrzn0EjNoCR0_fdvnd3Q1ZZQEn3Q2_w6D49D_r26NuGhWVjTI9RWoOk2MAH2D-uDdwlkNvATYppfvgatvu5SBNfmNVcmcRfNTtvSMt2E_Bsd9nPphlfv_piyy8WB7xY-GK28fh4n-3aSSDG72bZTjzeLlyRnVyxzhve8peuF0IdQyG1iaVSNSDav6hQIsLoE5Bu_b9_AA8GcyA.MEQCIDUgXGJ-YC6hNSK1AE94JAmreIQEe6Mq-Y7Ua4BFSckKAiAGLX-Y2o5Xv25yaYQ_xopeQcyUZtOm9V2MI57W4KTwxg>, or unsubscribe<https://shared.outlook.inky.com/link?domain=github.com&t=eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eJxVUF1Pg0AQ_C_3XIUUeSiJSbF81XBXq9AGQkIOuJajB5j70Irxv3v4Yvq2u7OzM7PfQBLc0wY4gA6S42YEi7kifMAMOCfMBFkAouFhlPREayzpOIj1mcpWVff12Ov9mX0zUFxzQSvlu3AKozD-wcK4uVMYahCqEjWnFbnDSraF4R52T5mfBonn5wFMst3zS4SsOPX2rw-WizYoeIO2n4abMHG11i4FzqAYWwDZcoJlycgH0fKmzjEbw0fbrPvgUn2tpjxCbW0hto8aVlt7lS1XMp5SG3bZNQ-DDiauhY7wqnsb9lsLhekSenmXTb6NvAOLJ38Jp62JurOJkouCE3yc4wrCS9JjykrcNJwIoXVFI7AQZP1JhPx7y88vq0d6eQ.MEUCIQDdhDu6YoHddGnRO49VFZqbTJdyuerHsFuKLzr4Sex-gQIgQXMwyvL9thl7aigu7adh5wwv7gAKADoooG14mNuqEGg>.
Triage notifications on the go with GitHub Mobile for iOS<https://shared.outlook.inky.com/link?domain=apps.apple.com&t=eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eJxVkNtqwkAQht9lL7zykCauqYFQCx7B3SJoRRFkzY5m4-ZAdtLalL57N7lqb37myPfPfBMEkSpJAqIyLIXMSbeJoMyEJsFVaANdArad5aiuKhKo8sxMbgrj6tKP8tTON9v_ClVpd0mMWJjgNDgNRFGYvhUNzUCbt6KhZzAv4TRQ8mno-54_Gjv0JcLwL60HqVC6k2L43CkwpO5w5FNLeduRIKu07hKMSxB41vABFuzYCxpLYk-dKJ3fL1_j-rjkceRxvVlKHXmb6uCOcV3vKEsOj-NinrDtq8f37GFzytKVxxc7l02PyaGeUT591-t65rJ65fDk5vDtvWI1C5tDDZTn1t5ZSFmCMZZrpBHGwOQTDLYP-fkFeE94Ug.MEQCIHrDhEG0l-XKOvHcR5F6xsjJW83y9q_SDFkiKK3JMF6WAiA8qsc-fa319919qHrLJqPqYH7WXuz08YiHH4GJIp3V6A> or Android<https://shared.outlook.inky.com/link?domain=play.google.com&t=eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eJxVUF1rwkAQ_C8H9smakJCCAakFP8FLEbSiBMKZW5OLd7lwH62m-N97sX2wb7szs7Oz-40MEMEoihGrjSJUon5XgaoJR_GJcA19BI6upWEnlhPDZK3HBTOlPQ5yKZy-m_4HWOVmUWlMo-PUS72Gk-ugkLLg0ClSTxupIPVI0-jUo2AI4_qV0ZEjB39OpKZKMvqk4ARKgRpZI7KciIawou6Fk8c8zyCcQy946TQCKLPCKR5BLa3KwYG_7i7j-xbFteW8j0ypgJiMwye42L67vzuI7CI_F7Pz8TpsD4ukzMOErxeU5-Ha7oOhWbXbCFf7y2E-q_DmLUx2-OL6CItlmMy3AZ4cqn07jZLJB1-10wC3Sz-pCj_ZnC1u8ah7kwaV3VNmhFIFWru9mmqiNYy_QJv7O28_eB-Smg.MEUCIE5mLk0Xjk_w3sUzcm0J6_zNXgZOZApW90taog6123INAiEA_gdJXmHdb5vVLn-QjA_-Kh2ID7eO2o7b8ib8UxZi-UI>.
