### ISSUE TITLE
**What cheatsheet is this about? (if applicable)**

### ISSUE THREAD

**Issue by son3ofSatan** [desktop/desktop#13021]
**What cheatsheet is this about? (if applicable)**

Advanced cheatsheet

**What's your issue or idea?**

_Write here_

__Originally posted by @Joemitchell36 in https://github.com/typescript-cheatsheets/react/issues/459__

**Comment by Pob1212** [comment]
> **What cheatsheet is this about? (if applicable)**
> 
> Advanced cheatsheet
> 
> **What's your issue or idea?**
> 
> _Write here_
> 
> __Originally posted by @Joemitchell36 in https://github.com/typescript-cheatsheets/react/issues/459__
