### ISSUE TITLE
File ignored

### ISSUE THREAD

**Issue by ProtocolLive** [desktop/desktop#13026]
### Describe the bug
I right-click on a file, click "Ignore file", and it is not ignored.

### Version & OS
Windows 11, Github Desktop Version 2.9.3

### Screenshots
![image](https://user-images.githubusercontent.com/39626142/134917980-e15d0cc5-bcfb-4595-9e48-de3055d2e431.png)
![image](https://user-images.githubusercontent.com/39626142/134918055-6d9cfcca-7b36-483d-bfd1-8afade339078.png)

**Comment by niik** [comment]
Hi @ProtocolLive, thanks for reaching out. The most likely explanation is that the file is already tracked by Git (i.e. it's been included in at least on commit before). See https://github.com/desktop/desktop/issues/10379#issuecomment-674014560

> I believe this is due to those two files already having been committed to the repository. Git will not ignore a file that is already tracked in the repository.
> 
> In order to not have the files be tracked you would have to first move the files outside of the repository directory. This will cause Git to believe they've been deleted. You then make a commit recording that removal and causing the files to not be tracked any more. You can then move the files back into the repository and they will no longer show up as modified files (if you don't care about the contents of the files you can straight up delete the files as well).

Please let us know if removing the file from git helps!
