### ISSUE TITLE
Typora issue

### ISSUE THREAD

**Issue by lix343** [desktop/desktop#13020]
### Describe the bug
I used to use typora as a external ediotr for the github desktop, but after i downloaded the VS code, I can;t use typora as an editor, I tried to change the integration, there is even no option for typora, only vs code

### Expected behavior
I just want to use typora on the github desktop as an external editor.

**Comment by steveward** [comment]
@1738345414 thanks for the report. I have Typora installed on my machine and it is still available as an option. Are you on macOS or Windows? 

> I tried to change the integration, there is even no option for typora, only vs code

Just to confirm -- are you not seeing Typora in the list when you go to `GitHub Desktop` > `Preferences` > `Integrations` > `External Editor`?

**Comment by lix343** [comment]
I figured it out myself, there is no typora options in the external editor, but after i updated the versions of typora, it suddenly apprears, i guess the reason why is the unupdated typora might disturb the Github Desktop, thanks for asking!
