### ISSUE TITLE
MacOs - Clone Issue

### ISSUE THREAD

**Issue by NotII** [desktop/desktop#13037]
### Describe the bug
Can't clone repo's 
### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.
Version 2.9.3 (arm64)
MacOs: 12 Beta
### Steps to reproduce the behavior

When trying to clone a repo i get this error 
```Cloning into '/Users/notii/Documents/GitHub/reponame here'...
ERROR: Couldn't connect to 127.0.0.1:60720 - Please make sure you don't have an antivirus or firewall blocking this connection. (49): Can't assign requested address
error: unable to read askpass response from '/Applications/GitHub Desktop.app/Contents/Resources/app/desktop-trampoline/desktop-trampoline'
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```
### Expected behavior

The expected behaviour would clone the repo
### Screenshots
<img width="625" alt="Screenshot 2021-09-29 at 00 01 41" src="https://user-images.githubusercontent.com/46204250/135177055-7383c9de-a763-48f1-ab85-a6e16feeb04f.png">

#12890

**Comment by NotII** [comment]
Seemed to have fixed it with 
```git config --global --add url."git@github.com:".insteadOf "https://github.com/```
And then logging into to GitHub via git using a ssh key

**Comment by steveward** [comment]
Thanks for the report @NotII. 

Did GitHub Desktop previously work on this machine prior to upgrading to macOS 12? Is there any security software running on your machine that could be blocking GitHub Desktop?

**Comment by NotII** [comment]
> Thanks for the report @NotII.
> 
> Did GitHub Desktop previously work on this machine prior to upgrading to macOS 12? Is there any security software running on your machine that could be blocking GitHub Desktop?

Yes it did work prior to the update to macOS 12, there shouldn't be any security running on the machine which could block GitHub Desktop, If there's anymore info required, Ask and ill see if I can provide the required information

**Comment by steveward** [comment]
@NotII can you try running `sudo ifconfig en0 down && sudo ifconfig en0 up` to reset your network adapter to see if that helps with this issue?

**Comment by NotII** [comment]
@steveward not sure if thats going to work as i stated i have found a temporary work around for such. if it happens again i can try it again

**Comment by steveward** [comment]
I'll close this out for the time being -- feel free to drop a reply in the future if you'd like for us to investigate this further.
