### ISSUE TITLE
partially staging a file, is that feature gone?

### ISSUE THREAD

**Issue by martinrode** [desktop/desktop#13033]
### Describe the bug
Until a few versions ago it was possible to partial commit a file by clicking on the blue marker in the diff viewer. That option does not work any more for me. Was that removed on purpose or is this hiding somewhere else now?

### Expected behavior

Clicking on the blue marker should remove the marked block from the current staging process.

### Actual behavior

Clicking on the marker, nothing happens.

**Comment by niik** [comment]
Hi @martinrode, thanks for reaching out. Chances are that you've turned on the option to hide whitespace changes in diffs. That option is incompatible with partial staging. See https://github.com/desktop/desktop/issues/12862 for more information on that. We just merged https://github.com/desktop/desktop/pull/12979 which should help make this more obvious going forward. Sorry for the confusion!
