### ISSUE TITLE
Unable to set Github Desktop to open Github links on Windows 11

### ISSUE THREAD

**Issue by Gr8z** [desktop/desktop#13035]
I am running Windows 11 beta and have the latest version of Desktop installed.

I want to be able to open "Open in Desktop" links in GitHub desktop. In the default apps setting page for Windows 11. I cannot find GitHub Desktop anywhere.

How do I change the default app for everything related to GitHub Desktop?

### Screenshots

![image](https://user-images.githubusercontent.com/4633243/135076860-5d8e0cfc-55e1-4ffd-b5be-8afa1e077034.png)

![image](https://user-images.githubusercontent.com/4633243/135076954-58c82fec-68a6-45ca-a0bc-f5ab1044122d.png)

**Comment by say25** [comment]
I might be wrong but I believe GitHub Desktop supports `x-github-client` 

https://github.com/desktop/desktop/blob/4c62d3d495089959c8c117f0c9519e7eeae33f9b/app/src/main-process/main.ts#L82

As part of our integration with https://www.electronjs.org/docs/api/protocol

**Comment by say25** [comment]
I might be wrong but I believe GitHub Desktop supports `x-github-client` 

https://github.com/desktop/desktop/blob/4c62d3d495089959c8c117f0c9519e7eeae33f9b/app/src/main-process/main.ts#L82

As part of our integration with https://www.electronjs.org/docs/api/protocol.

@Gr8z can you try to change that property in your settings? I don't yet have Windows 11 installed anywhere to test myself

**Comment by steveward** [comment]
@Gr8z TortoiseGit taking over their links is being tracked in https://github.com/desktop/desktop/issues/8258. Changing the `x-github-client` protocol is what you would want to do like @say25 mentioned. I don't have Windows 11 on hand but I'm surprised there isn't an option there to select another local application on your machine.

**Comment by Gr8z** [comment]
@say25 @steveward Windows 11 does not allow me to select anything other than TortoiseGit. Even for ``x-github-client``

**Comment by steveward** [comment]
@Gr8z I'd recommend trying [this workaround](https://stackoverflow.com/questions/52747051/github-clone-to-desktop-uses-tortoisegit-instead-of-github-desktop/57905263#57905263) until we have a better fix for this. Let me know if that doesn't get things working.

**Comment by darck-storm** [comment]
hello mi brader

**Comment by darck-storm** [comment]
im darck storm
_

**Comment by steveward** [comment]
@Gr8z hopefully you were able to get things working via the workaround I shared -- I'm going to close this out for the time being as we're tracking this in #8258.
