### ISSUE TITLE
Incorrect misattributed warning for incorrect Git config no-reply email address

### ISSUE THREAD

**Issue by omavi** [desktop/desktop#13039]
### Describe the bug
I setup a `no-reply` email address and now GitHub Desktop is warning me about my commits being misattributed although the docs say that shouldn't be a problem.

### Version & OS

Version 2.9.3 (arm64)
macOS 11.6

### Steps to reproduce the behavior

1. Setup a `no-reply` email address according to these instructions

### Expected behavior

GitHub Desktop should be aware of `no-reply` email addresses so no misattributed warning should show.

### Actual behavior

The misattributed warning appears in GitHub Desktop. My `no-reply` email address doesn't appear in the dropdown of addresses to choose from, implying that the app is completely unaware of the address.

### Screenshots

![image](https://user-images.githubusercontent.com/5963067/135180420-2aa3f2d3-aa63-4daa-a4fe-480130ee24c0.png)

**Comment by sergiou87** [comment]
This is working for me as expected: the noreply email address is shown in that dropdown. Is the public (non-private) version of your email address in that dropdown instead? 🤔

**Comment by omavi** [comment]
Yes, exactly. The noreply email address is missing from the dropdown while my normal email address that I hid is in the dropdown. Maybe it's because I just set it up and I assume you already had yours configured?

**Comment by sergiou87** [comment]
I don't think that's it, I just set it up to test this and I saw it immediately. I had to restart the app though, so that it'd refresh the account emails. Did you do that?

**Comment by omavi** [comment]
Yes, I did before opening this issue since I saw your reply on another issue: https://github.com/desktop/desktop/issues/12402#issuecomment-856634066.

I just tried again on two different machines and that didn't help either; however, I realized that I should try signing out and back in. That totally worked. Thanks @sergiou87!

**Comment by sergiou87** [comment]
I'm surprised (but glad) that worked! 😂 

In any case, thanks for reporting back! ❤️

**Comment by omavi** [comment]
Same here and of course. I really appreciate your insight and speedy responses! 🙂
