### ISSUE TITLE
cherry-pick: Add an option to restore source branch instead of staying on target branch

### ISSUE THREAD

**Issue by olivierchatry** [desktop/desktop#13031]
Cherry picking same commit(s) on different branch is hard because after cherry picking, desktop stays on the target branch. 

Adding an option to restore source branch after successful cherry-pick would make it easier to do that.

I already implemented the feature on my fork, here is the setting window: 

![image](https://user-images.githubusercontent.com/1267483/135036349-1562b07d-8716-4239-81e7-070af92d3578.png)

and after cherry pick, you stay on the source branch:

![image](https://user-images.githubusercontent.com/1267483/135036559-6fdcb2f3-74ab-4774-9a28-4c27c5f33df0.png)

**Comment by olivierchatry** [comment]
Only issue is it seems `this.changeCommitSelection(repository, [commits[0].sha])` does not update the selection state on the commits history.

**Comment by tidy-dev** [comment]
@olivierchatry Thank you for the suggestion. This feels like very situational feature so I am not sure that a permanent setting makes the most sense for all users. 

I was curios if you knew that you can ctrl+click or shift+click to select multiple commits to cherry-pick at one time. You may be able to reduce or eliminate the need to jump back to the source branch. 

![image](https://user-images.githubusercontent.com/75402236/135094579-d873662b-f512-45e0-8a8c-a4abc6e8516b.png)

**Comment by olivierchatry** [comment]
It still very annoying when you have to put them into differnent branches, as select will get reset when you switch branches.

I implemented the feature in my pull-request : https://github.com/desktop/desktop/pull/13032

**Comment by billygriffin** [comment]
Thanks for the suggestion @olivierchatry. As @tidy-dev shared in your PR, we don't think this is a widespread enough case to warrant a setting, and therefore I'm going to close this as well. We're open to revisiting things if we hear lots of feedback from folks that ending up on the target branch is making the experience painful. Thanks again.

**Comment by olivierchatry** [comment]
No worries.

Le mar. 28 sept. 2021 à 20:51, Billy Griffin ***@***.***> a
écrit :

**Comment by andreasabel** [comment]
@billygriffin wrote:
> we don't think this is a widespread enough case to warrant a setting, and therefore I'm going to close this as well. We're open to revisiting things if we hear lots of feedback from folks that ending up on the target branch is making the experience painful.

In my case (#13336), I only installed GitHub Desktop to get help with cherry-picking, which is cumbersome on the command line.  With the current UI, it is even more cumbersome with GitHub Desktop.  I settled for `gitk`, that dinosaur tool...

This is my data point (for your feedback collection).

I think #13032 would have exactly solved my problem.
