### ISSUE TITLE
Feature to view version history for any particular file.

### ISSUE THREAD

**Issue by learning-zone** [desktop/desktop#13042]
### Describe the feature 

Feature to view version history for any particular file. This feature is already available in [TortoiseGit](https://tortoisegit.org/)

### Screenshot for Reference

![image](https://user-images.githubusercontent.com/10107543/135225114-7748dd11-cfe4-4e49-9956-0655565de049.png)

**Comment by steveward** [comment]
Thanks for the issue @learning-zone. This has been previously requested in https://github.com/desktop/desktop/issues/11990 so you can follow along there for updates.
