### ISSUE TITLE
move github desktop to a new computer

### ISSUE THREAD

**Issue by staabm** [desktop/desktop#13043]
### Describe 

is it possible to migrate/move my existing github desktop konfiguration/installation to a new computer?
I will copy over my projects folders with all the included `.git` folders and would love if I could somehow also copy over the github desktop configs, so I will not loose settings or alias-definition etc.

### Version & OS

windows 10 x64, latest version

### Expected behavior

I want to migrate/move the installation to a new computer without the need to re-do all configs/settings and aliases again

### Actual behavior

wasn't able to find information whether/how this can be achieved

**Comment by steveward** [comment]
@staabm thanks for the issue. You should be able to move the `%AppData%\GitHub Desktop` directory to your new machine and overwrite the existing files. If your repositories are in the same directory paths then it should work fairly seamlessly. I hope that helps!
