### ISSUE TITLE
Commit doesn't update after creating a tag

### ISSUE THREAD

**Issue by MrBartusek** [desktop/desktop#13054]
### Describe the bug

When a tag is created by commit context menu it doesn't update the UI

### Version & OS

Version 2.9.3 (x64) on Windows 10

### Steps to reproduce the behavior

1. Go to commits list on any repo
2. Right click on any commit -> create a tag
3. Create a tag with any name

### Expected behavior

A commit should update when a tag is created

### Actual behavior

It doesn't show that a tag was created and only clicking on different commit fixes that

### Screenshots

![Animation](https://user-images.githubusercontent.com/23432278/135614965-d2d33d8b-9233-4e7f-aeb8-193171571cfc.gif)

**Comment by timsu92** [comment]
This fixes when I open `create a tag` dialog again or click on the pull/push button.
But I would like it to update automatically as well!

Along side with this issue, if I create a tag and then right-click on the commit right away, `delete tag` button won't show up either.

**Comment by steveward** [comment]
I'm no longer able to reproduce this issue. @MrBartusek if you're still able to please let me know and we can reopen and investigate further.
