### ISSUE TITLE
Archimate tool Archi not authorized import/publish to Github

### ISSUE THREAD

**Issue by jaimecont** [desktop/desktop#13057]
I have installed the archi plugin for collaboration. I am trying to import archi models from Github to start collaboration but I did received the notification NOT AUTHORIZED. I can create the Github repository using Github desktop but I can not import using Archi tool.

![image](https://user-images.githubusercontent.com/91664057/135713175-dc8cc332-1f3b-4584-b42f-99d92d744730.png)

**Comment by niik** [comment]
Hi @jaimecont, I'm afraid I'm not familiar with that tool and unfortunately we're not able to provide support for any software other than GitHub Desktop. I'd suggest reaching out to the authors of Archi tool to see if they can assist you with authenticating. Best of luck!

**Comment by jaimecont** [comment]
Thanks Markus.

At final, I found a solution... :-)

**Comment by yassinekhlifi** [comment]
Hi jaimecont
I have same problem.
I try to install and use Archi. in git, and i was install coArch tool .
But i have same message (not Authorize) 
Can told me how how did you solve the problem ?

Thank you
