### ISSUE TITLE
Manualy created order groups for repositories list

### ISSUE THREAD

**Issue by Wohlstand** [desktop/desktop#13063]
Hello!

Recently I got an idea to request the ability to make own groups and sort repositories among them. Mainly, I do develop of various projects, and almost every project unites many repositories. Or, separate repositories I do for my main work, and repositories of my own projects I do at my home as a hobby.

### Proposed solution

Users will be able to have their own manual grouping of repositories in the list and will be able to sort up projects they do: divide repositories per different project, per goal, or spheres such as developed for home, for study, or for the work, or projects developed for various customers, etc. etc.

**Comment by steveward** [comment]
Thanks for the feedback @Wohlstand. See [this comment](https://github.com/desktop/desktop/issues/10201#issuecomment-658693653) for more information about why we do not have plans to implement repository grouping at this time. Thanks for using GitHub Desktop!

**Comment by Wohlstand** [comment]
Okay, maybe, alternatively, add the tagging instead? I mean, let users assign to repositories in the list specific tag, and let user filter them by tag in the list, should be simpler to implement. This doesn't mean any grouping mechanism changes. Just will allow filter the showing of repos in the list by tag, keeping the same grouping as now.

**Comment by tidy-dev** [comment]
@Wohlstand Something that may help you -  If you right click a repo name, you can `Create Alias`. Then, you could preface or suffix the repos for a specific project to your preference, and the filter by that convention.

Example: I just prefaced these two repos with Project 1 and then filtered by it.
![image](https://user-images.githubusercontent.com/75402236/136075244-c0b39bf3-7dd9-4407-be2e-50b2db604ee0.png)
