### ISSUE TITLE
Add "Initialize local repository" to file menu

### ISSUE THREAD

**Issue by Peaj** [desktop/desktop#13071]
### Describe the feature or problem you’d like to solve

The option to add and initialize a repository from an existing folder is hidden serveral steps behind "Add local repository".
Before today I didn't even know that an "Init Repository" dialog exists.
I was using a workaround by via the "New Repository..." entry and naming the repo exactly like the existing folder.

### Proposed solution

Add an "Initialize local repository..." entry to the File menu.

### Additional context

It is common to create a project folder in an IDE or e.g. game engine and than init a repo in this existing folder.
This issue is losely connected to #9651

**Comment by tidy-dev** [comment]
@Peaj Thanks for the suggestion! As you pointed out this could be part of a solution for #9651, thus, I am going to close this in favor of tracking the issue there.
