### ISSUE TITLE
GitHub Dektop ignores the setting to disable automatic fetching of remote

### ISSUE THREAD

**Issue by awnumar** [desktop/desktop#13070]
### Describe the bug

GitHub Desktop by default pulls remote periodically. This is not a feature that I want as it polls my 2FA token and prompts for a password every time, disturbing my workflow. Also, in many cases I have local changes and do not want to deal with remote changes yet.

Fortunately, there is an option in settings to disable this behaviour:

![image](https://user-images.githubusercontent.com/8942495/136188487-f83e229b-6586-4950-b9b6-df35057b6325.png)

As you can see, I have the feature turned off. However, GitHub Desktop ignores this setting and continues to fetch remote whenever it feels like it..

### Version & OS

GitHub Desktop: Version 2.9.4 (x64)
OS: macOS Big Sur 11.6
Kernel: Darwin Kernel Version 20.6.0

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. Make sure the option to periodically sync with remote is disabled in settings.
3. Observe that the program ignores this setting

**Comment by niik** [comment]
Hey @awnumar, thanks for reaching out and I'm sorry to hear you're having problems with GitHub Desktop. Fetching the currently selected repository in the background or not is not configurable at the moment. Please see https://github.com/desktop/desktop/issues/10687 which is tracking being able to disable fetching of the current repository.

I'm curious, are you using SSH remotes in your workflow? If you use the http protocol GitHub.com shouldn't require you to enter your 2FA tokens repeatedly.

I'm closing this issue as it's both known and documented in https://github.com/desktop/desktop/issues/10687 but I'm curious to hear more about your workflow.

**Comment by awnumar** [comment]
@niik Thanks for the reply.

My SSH key is stored inside a YubiKey. I have to enter the YubiKey password for remote operations. There is a cooldown so that if I do multiple operations in a row it only prompts me for a password the first time, although this resets after a few minutes and also resets if I put my laptop to sleep or lock my screen. 

It's also really scary for my YubiKey password prompt to come up unexpectedly as the only time this happens is if I explicitly perform an operation that requires access to its secret state. Also, the popup happens unpredictably and appears on top of all other windows so it interrupts whatever I'm doing at the time. I really do not expect my Git client to be speaking to remote without my explicit instructions

> If you use the http protocol GitHub.com shouldn't require you to enter your 2FA tokens repeatedly.

It's not an option for me to switch off using this SSH key, especially not to password authentication.

> Fetching the currently selected repository in the background or not is not configurable at the moment. 

It seems to me that the option in the settings that I quoted above is a little misleading in the way that it's worded
