### ISSUE TITLE
Allow repository menu actions (like show in explorer, open terminal) during conflict resolution

### ISSUE THREAD

**Issue by xPaw** [desktop/desktop#13081]
### Describe the bug
Most menu items are disabled when in conflict resolution mode.

### Version & OS

Version 2.9.4 (x64) on Windows 10.

### Steps to reproduce the behavior

1. Start a rebase and get into a conflict
2. Close the rebase windows
3. Click on Repository menu

### Expected behavior

Menu items like View on github, open in terminal, open in explorer are available.

### Actual behavior

They are disabled. Funnily enough even "About github desktop" was disabled while I was creating this issue. Even ctrl-~ to open terminal is disabled.

### Screenshots

![image](https://user-images.githubusercontent.com/613331/136379075-e8a27314-3fc1-483c-bf17-1d74d7e95905.png)

**Comment by steveward** [comment]
Thanks for reporting this @xPaw!

**Comment by tidy-dev** [comment]
This appears to be a regression - I pulled version 2.7.0 and those menu items were enabled when resolve conflicts banner is present (But not when resolve conflicts dialog is present).

**Comment by xPaw** [comment]
I believe this is caused by this code:

https://github.com/desktop/desktop/blob/34d391b60e9189fca75a62394ea4422e3a5ca00c/app/src/lib/menu-update.ts#L365-L368

It doesn't take into account that the popup can be hidden. I briefly debugged it, and it keeps calling `getAllMenusDisabledBuilder` as long as it is in the conflict state, even with the popup hidden.

By the way, this does not affect the context menu when right clicking on the repository name.

**Comment by angusdev** [comment]
Based on @xPaw's finding, the ```currentPopup``` is not reset in ```onDismissed```, see the PR #15471 for details
