### ISSUE TITLE
v2.9.4 removed option to open repo in Sublime Text

### ISSUE THREAD

**Issue by nitinthewiz** [desktop/desktop#13089]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS
Desktop v2.9.4
OS  - MacOS Catalina 10.15.7

### Steps to reproduce the behavior

1. Go to a repo
2. Under No Local Changes, it should show Open in Sublime Text. The other option of Show in Finder still exists.
3. After update from 2.9.3 it only shows Open in XCode (which is not my editor of choice)

### Expected behavior

Under v2.9.3 I had the option to open my repos in Sublime Text 3. This option has now disappeared. I do not remember if I did anything special to get that feature. Did I have to add it as a third party editor? Don't remember.

### Actual behavior

Desktop offers to open the repo in XCode.

### Screenshots

I'll add if needed.

### Additional context

Xcode is a horrible and ugly editor and vastly inferior to the greatness that is Sublime Text, in my humble opinion. It is my understanding that Desktop has a "fixed list" of editors it supports. Don't know how or why but ST was the default for me for many, many months. Don't take this away from me please.

**Comment by sergiou87** [comment]
Hi @nitinthewiz! 👋 

In theory, we haven't done anything in the latest version that could affect the integration with Sublime Text. I can confirm it works for me. Could you check in the app Settings -> Integration and see if it's listed among the other editors?

If it's not in there, could you provide logs to see if the app mentions something about it?

Thank you!

**Comment by nitinthewiz** [comment]
Hi Sergio!

Seems like I gave it a night and the option came back. Could have something to do with restarting the GitHub Desktop app a few times and finally updating Sublime Text 3 to the latest stable build.

Not sure, which, but closing the ticket now.

Thanks!

**Comment by f00k** [comment]
Sublime Text disappeared from the "Right Click -> Open In" dropdown menu and External Editors list on the Integrations screen after the update for me too, leaving Visual Studio Code as the only option as External Editor.

I do not know if I updated from the previous one or I was several builds behind the latest version - but I'm 100% sure the update removed Sublime Text as an option.

Restarting the apps or my MacBook (Big Sur 11.4) entirely did not resolve the issue for me.

**Comment by nitinthewiz** [comment]
@f00k going to the latest sublime text and waiting for a night seemed to fix it for me. Maybe that would fix it for you too?
