### ISSUE TITLE
Unsupported proxy, libcurl is built without the HTTPS-proxy support.

### ISSUE THREAD

**Issue by diev** [desktop/desktop#13082]
### Describe the bug

Trying to clone a GH repository through a corporate http proxy fails.

### Version & OS

Version 2.9.4 (x64) & Microsoft Windows 8.1

### Steps to reproduce the behavior

1. Go to 'File \ Clone...'
2. Click on 'Clone'
3. See error

### Expected behavior

To get the repository cloned without error messages.

### Actual behavior

Error message:

Cloning into 'C:\Repos\ConvertFRBtoABS'...
fatal: unable to access 'https://github.com/diev/ConvertFRBtoABS.git/': Unsupported proxy '10.0.2.1:3128', libcurl is built without the HTTPS-proxy support.

### Screenshot

![clone_fails](https://user-images.githubusercontent.com/2707312/136410431-48f50ff3-d5ae-4b9e-88a1-e3498c31d21e.png)

### Logs

2021-10-07T14:43:56.190Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/diev/ConvertFRBtoABS.git - diev (has token)
2021-10-07T14:43:56.795Z - error: [ui] `git -c credential.helper= -c protocol.version=2 -c init.defaultBranch=master clone --recursive --progress -- https://github.com/diev/ConvertFRBtoABS.git C:\Repos\ConvertFRBtoABS` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\Repos\ConvertFRBtoABS'...
fatal: unable to access 'https://github.com/diev/ConvertFRBtoABS.git/': Unsupported proxy '10.0.2.1:3128', libcurl is built without the HTTPS-proxy support.

### Additional context

No settings to configure the Proxy in the GitHub Desktop. Automatically used IE system settings fail. This proxy has no authentication for simplicity, but fails. When will developers take into consideration those facts about corporate proxies existing and some white-listening of Internet resources? The corporate world thinks about its information security by regulatory!

**Comment by steveward** [comment]
@diev thanks for the report. It looks like you need to manually configure your proxy. You can do that by running this command (you will need to install Git for Windows if you have not already):

`git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`

Replace `proxyuser` with your proxy username and `proxypwd` with your proxy password (if needed). Also, `proxy.server.com:8080` needs to point to the URL of your proxy server.

Let me know if you run into any issues getting this working.

**Comment by diev** [comment]
Well, this has solved my issue completely! Thank you. Just correct your error message to advise this, please.
