### ISSUE TITLE
Kotlin syntax highlight is buggy on literal fun names

### ISSUE THREAD

**Issue by Xeoneid** [desktop/desktop#13086]
### Describe the bug
When showing Kotlin code in which a function is named as a literal ( ```fun `this is a function name with spaces`()``` ) the syntax highlight is shown incorrectly, specially when the function name uses reserver keywords such as `when` .

### Version & OS

Version 2.9.4 (x64) macOS (not M1) BigSur.

### Steps to reproduce the behavior

1. Commit a .kt file with this code:
```
@Test
  fun `add one life when invoke`(){
    // redacted
  }
```
2. Go to the History tab on GitHub desktop.
3. Select that commit.
4. See error. `when` and `invoke` are highlighted as keywords when they are not.

### Expected behavior

The hole name function should be highlighted as the same token, a function name.

### Actual behavior

Highlights `when` and `invoke` as keywords.

### Screenshots

![image](https://user-images.githubusercontent.com/10685315/136439291-618b1e69-3c45-48b0-a219-8ebec15f8785.png)

**Comment by steveward** [comment]
Thanks for the report @Xeoneid! It looks like this has already been [reported in CodeMirror](https://github.com/codemirror/CodeMirror/issues/5775). If a fix gets merged in we'll eventually update the version of CodeMirror we ship with GitHub Desktop to fix this.

**Comment by steveward** [comment]
In the interest of cleaning up our issue tracker I am going to close this issue out since there is an existing external issue in CodeMirror.
