### ISSUE TITLE
We're not handling added in index + deleted in working directory

### ISSUE THREAD

**Issue by niik** [desktop/desktop#1310]
As I was updating [mapStatus](https://github.com/desktop/desktop/blob/54b351bb2c94d4b64c1a553bf78515ca46e2b0a4/app/src/lib/git/status.ts#L35-L63) to work with the new porcelain v2 parser in #1305 I noticed that we didn't have a special case for `AD` which is added in index and deleted in work-tree.

This isn't your typical status which is probably why we ignored it in the first place.

```
> touch foo
> git add foo
> rm foo
> git status --porcelain=2
1 AD N... 000000 100644 000000 0000000000000000000000000000000000000000 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 foo
```

We currently treat this file as modified whereas I think we should omit the file entirely. From the perspective of Desktop we don't care about the index and we'll blow away the index before committing anyway.

![image](https://cloud.githubusercontent.com/assets/634063/25486626/123ac22a-2b62-11e7-9b48-c0eaecf4352d.png)

The inverse scenario is not something we handle well either (a file deleted in the index that's still in the working directory)

```
> touch foo
> git add foo
> git commit -m 'foo'
> git rm --cached foo
> git status --porcelain=2
1 D. N... 100644 000000 000000 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 0000000000000000000000000000000000000000 foo
? foo
```

This shows up as 2 changed files in desktop

![image](https://cloud.githubusercontent.com/assets/634063/25487560/e04d7fc0-2b64-11e7-80bf-d04c372b5e1b.png)

**Comment by shiftkey** [comment]
```
> touch foo
> git add foo
> git commit -m 'foo'
> git rm --cached foo
> git status --porcelain=2
1 D. N... 100644 000000 000000 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 0000000000000000000000000000000000000000 foo
? foo
```
