### ISSUE TITLE
Adding repositories goes into random accounts

### ISSUE THREAD

**Issue by roosterroosie** [desktop/desktop#13100]
### Describe the bug
repositories being messed up when creating new repositories, when adding new repositories they go all over the place

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Go to 'File'
2. Click on 'Add local repository'
3. Select a repository and click select

### Expected behavior

the repository being on the right account

### Actual behavior

the repository goes into a random account like someone else's account

**Comment by steveward** [comment]
@roosterroosie thanks for the report. Can you share a few more details/screenshots of the issue you are experiencing? If you could give specific reproduction steps that would also be helpful.
