### ISSUE TITLE
Ignore selected files doesn't ignore it from tracking

### ISSUE THREAD

**Issue by lapec** [desktop/desktop#13109]
### Describe the bug
Ignore selected files doesn't ignore it from tracking.

### Version & OS

Version 2.9.4 (x64) Windows 10
### Steps to reproduce the behavior

1. Go to 'Changes'
2. Select 4 changes
3. Click right click on it 
4. Click Ignore five selected files
5. See those files are still in Changes list

or 
1. Go to 'Changes'
2. Select 4 changes
3. Click right click on it 
4. Click Ignore five selected files
5. Commit gtignore file
6. Pull
7. See those files are still tracked

### Expected behavior

Write a clear and concise description of what you expected to happen.
4. Click Ignore five selected files
5. Those files disappear from Changes forever(until I choose to track them again)
### Actual behavior

4. Click Ignore five selected files
5. Still tracks it

### Screenshots

![image](https://user-images.githubusercontent.com/6226467/136942200-b5450bdd-fe6c-41e2-b56c-56dba1328f7e.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the issue @lapec.  If the files have been previously committed in your repository they need to removed prior to being ignored. You'll need to run this command from the command line:

`git rm --cached <file>`

You should then be able to ignore the files. You can find more information in [this help article](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files). Let me know if you run into any issues.

**Comment by lapec** [comment]
Thanks for fast response. I already did this but it would be cool if you
add some GUI btn for this.

Regards,
