### ISSUE TITLE
I cant publish my repo to github using github desktop.

### ISSUE THREAD

**Issue by bryant-the-coder** [desktop/desktop#13113]
THIS IS THE OUTPUT. I AM IN THE MIDDLE OF A URGENT MATTER THAT I NEED TO PUBLISH IT. PLEASE HELP ME~

Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.

**Comment by sergiou87** [comment]
Hi @bryant-the-coder ! Could you upload the app logs (from `Help` -> `Show Logs in…`) here so we can see what the problem is exactly?

Thanks!
