### ISSUE TITLE
Error appears when i try to commit

### ISSUE THREAD

**Issue by yannickninot** [desktop/desktop#13111]
### Describe the bug
I am on a branch on which I have made modifications. When I want to upload my files to the current branch, GitHub Desktop tells me there is an error and I need to do a git add

**On branch develop
Your branch is up to date with 'origin/develop'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   ../../../.gitignore

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	../../uploads/

no changes added to commit (use "git add" and/or "git commit -a")**

### Version & OS
Version 2.9.4 (arm64)
macOS Big Sur
Version 11.6

### Steps to reproduce the behavior

1. Make a change in your files
2. Save your files
3. Go to GitHub Desktop and then write a Summary
4. Click on "Commit to branch"
5. See error

### Expected behavior

I would like that when I click on "commit to branch" that it does not ask me every time to do the command "git add."

### Actual behavior

When I click on "commit to branch" it asks me each time to do the command "git add." so I still have to go to my terminal to do the requested commands then commit from GitHub Desktop

### Screenshots

![Capture d’écran, le 2021-10-12 à 12 20 11](https://user-images.githubusercontent.com/91280356/136993330-d3ab770a-ab0c-47de-8ad9-0484f61e70d5.png)

### Logs

[2021-10-12.desktop.production.log](https://github.com/desktop/desktop/files/7331621/2021-10-12.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @yannickninot. This looks similar to https://github.com/desktop/desktop/issues/3779.

Can you verify that this file exists in your repository?

`Users/yannickninot/Local Sites/cookit/app/public/wp-content/themes/chefcookit.com/wp-content/uploads/wp-defender/index.php`

That seems to be the root of the issue. It'd also be helpful if you could open the repository in the command line to see if committing directly from there succeeds or errors out:

`git add -A`
`git commit -m "your commit message`

**Comment by yannickninot** [comment]
Hi Steve,

Where do you find this path ? Users/yannickninot/Local
Sites/cookit/app/public/wp-content/themes/
chefcookit.com/wp-content/uploads/wp-defender/index.php

I looked in my GitHub repository and in my local files but didn't have
/wp-content/uploads/wp-defender/index.php
<http://chefcookit.com/wp-content/uploads/wp-defender/index.php> after
chefcookit.com/ ...

If I run my terminal at the root of my WordPress theme
(Users/yannickninot/Local
Sites/cookit/app/public/), where git is located and I do the commands you
suggested, it works correctly, I don't have an error.

Le mar. 12 oct. 2021 à 16:35, Steve Ward ***@***.***> a
écrit :

**Comment by steveward** [comment]
@yannickninot that file path was in the log file in the error:

`Error: ENOENT: no such file or directory, open '/Users/yannickninot/Local Sites/cookit/app/public/wp-content/themes/chefcookit.com/wp-content/uploads/wp-defender/index.php'`

>it works correctly, I don't have an error.

After committing via the command line do you still encounter the same error in GitHub Desktop?

**Comment by simonegli8** [comment]
I have the same issue, and the erroneous file according to the log is present on my disk. I always have to use git add and git commit from the command line

**Comment by FreakyAli** [comment]
I randomly started getting this error yesterday, and it would not go away. I am using GD for Mac. Was someone able to fix this?

**Comment by smitdylan2001** [comment]
Same here on Windows. Also cannot push via cmd
