### ISSUE TITLE
In full screen mode on macOS, moving the cursor to the system menu bar should push the GitHub controls down with it

### ISSUE THREAD

**Issue by AustinConlon** [desktop/desktop#13119]
The controls at the top should be anchored to the system menu bar instead of clipped.

https://user-images.githubusercontent.com/1305957/137185592-21fb91bb-0c27-4f4f-b60e-d2555167f79f.mov

**Comment by steveward** [comment]
Thanks for the feedback @AustinConlon. This is the standard behavior in fullscreen mode in macOS so at this time it isn't something we would plan on changing.

**Comment by AustinConlon** [comment]
> Thanks for the feedback @AustinConlon. This is the standard behavior in fullscreen mode in macOS so at this time it isn't something we would plan on changing.

Hi Steve, thanks for the response. Just tried with Finder and Safari in full screen mode, and they both have this behavior. Is this just a matter of different built-in behavior in native vs. Electron?
