### ISSUE TITLE
Add Button to see all Changes to a File

### ISSUE THREAD

**Issue by daniel31079** [desktop/desktop#13110]
### Describe the feature or problem you’d like to solve

I recently switched from Sourcetree to Github Desktop and i enjoy it so far - but i am missing the following feature:

In Sourcetree you can display every commit of a File by rightclicking the File when there are open changes and then select "Log Selected".

### Proposed solution

You can easily see who edited a file and also would have quick overview what has been changed in the commit.

### Additional context

![image](https://user-images.githubusercontent.com/70377161/136979189-5e1e1ced-0369-438a-be48-0f2e1ebbbdac.png)
![image](https://user-images.githubusercontent.com/70377161/136979023-4494df36-38c7-4996-a550-a3b6de66cb39.png)

**Comment by steveward** [comment]
Thanks for the feedback @daniel31079. This has been previously requested in https://github.com/desktop/desktop/issues/11990 so you can follow along there for updates. I'll drop a reference to this issue there as well.
