### ISSUE TITLE
hi i want to publish my repositori and i just write my code then press and publish it but when i search my web in google it say error 404 why?   web: mohammad-jozani.github.io

### ISSUE THREAD

**Issue by mjjjozani** [desktop/desktop#13125]
### Describe the feature or problem you’d like to solve

Write a clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

Please share how this will it benefit Desktop and its users?

### Additional context

Please include any other context, like screenshots or mockups, if applicable.

**Comment by mjjjozani** [comment]
hi i want to publish my repositori and i just write my code then press and publish it but when i search my web in google it say error 404 why? web: mohammad-jozani.github.io

**Comment by steveward** [comment]
Thanks for the issue @Mjjozani. This issue tracker is for GitHub Desktop, and we are unable to help with getting your GitHub Pages site working. 

I would recommend asking for assistance [here](https://github.community/c/github-help/github-pages/31) or reading through the [help docs](https://docs.github.com/en/pages). If you have any issues with GitHub Desktop let us know.
