### ISSUE TITLE
Error on push failing to spawn?

### ISSUE THREAD

**Issue by HypoConDreAct** [desktop/desktop#13124]
### Describe the bug
on push
error: cannot spawn .git/hooks/pre-push: No such file or directory
error: waitpid for .git/hooks/pre-push failed: No child processes
error: failed to push some refs to 'https://github.com/Blackrobin-Games/Slag.git'

### Version & OS
Version 2.9.4 (x64) Win10

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

on push i get this warning and it fails to push

### Expected behavior

it to push to the main branch

### Actual behavior

gets  the warning above

### Screenshots

![image](https://user-images.githubusercontent.com/67771542/137257187-63110427-7382-4b2e-9ee8-3ba7ae565607.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
[2021-10-14.desktop.production.log](https://github.com/desktop/desktop/files/7343269/2021-10-14.desktop.production.log)

### Additional context

i had a quick look in the hook file and it only had Null pointers in it. (using notepad++) i then removed said file and tried to push again but that caused other issues
so i un did this

**Comment by sergiou87** [comment]
Hello @HypoConDreAct !

I'm sorry you're experiencing this issue. Have you tried running `git push` in the repository from the command line? I assume that `.git/hooks/pre-push` file exist and it's in the right location.

**Comment by HypoConDreAct** [comment]
Morning, 
I have tired to but I keep running into token issues that I cant seam to get around. as in it always ask for login in and then fails as we use tokens now. or at lest that's what I understand.
I am using it with UE4 (unreal Engine 4) and have reverted a few changes that went badly form inside this. that's when I started to have this issue. would making a copy of my local repo - the .git dir. then reverting clean up or fix the .git files as well ?
I assume they do not get added to the repos change list.

I will try updating the git command/bash and see if its because I haven't updated that in ages (only just thought about it )
So yea did that 
![image](https://user-images.githubusercontent.com/67771542/137393012-fda21437-abea-4030-a0de-09b2132279e8.png)

**Comment by steveward** [comment]
@HypoConDreAct thanks for the update. Are you using Git LFS with this repository? It sounds like the `pre-push` file was corrupt, and deleting it should have resolved the error you were encountering. What specific issues did you run into after deleting the `pre-push` file?

> would making a copy of my local repo - the .git dir. then reverting clean up or fix the .git files as well ?

You can reset your repository back to a previous good state, but it'd definitely be worth backing up your repository in case something goes wrong. I would recommend right-clicking on a previous commit in the repository's history and selecting `Create Branch from commit` to create a branch off of a previous 'good' commit. You can then see if you run into the same issues on that branch -- that can help determine a safe point to reset back to.

**Comment by HypoConDreAct** [comment]
Right it has been solved
yes I am using LFS with this repository. when I tried to push with that file removed it ran into an unknown issue. (there are some hash codes in the log report you can see where I have tried to do this with the prehook file removed. what I didn't do was try the LFS push to master branch and this has now solved the issue.
here's an image as my explanation maybe lacking.
![image](https://user-images.githubusercontent.com/67771542/137408548-1538e5c4-dbfa-4d02-a7fe-851457281517.png)
