### ISSUE TITLE
Commit & Push

### ISSUE THREAD

**Issue by perholmes** [desktop/desktop#13120]
Every other Git client supports this, so I trip over myself in GitHub desktop over an over by having to push manually.

Is there any upside to splitting committing and pushing to two mouse-click with a mandatory wait between them?

Commit & Push please

**Comment by steveward** [comment]
Thanks for the feedback @perholmes. At this time we don't have any plans to add a commit and push option, but if we continue to hear feedback about this being a pain point for users it may be something we consider again in the future. You can check out https://github.com/desktop/desktop/issues/2256 for some previous discussion around this.
