### ISSUE TITLE
Support for multiple external editor

### ISSUE THREAD

**Issue by wengfatt** [desktop/desktop#13121]
### Support multiple external editor

Currently only support 1 external editor. 

### Proposed solution

Option to choose different external editor for different language such as Java repo can choose IntelliJ, C# repo can choose rider, Python repo can choose Pycharm, etc. It would definitely improve productivity of developer.

**Comment by steveward** [comment]
Thanks for the issue @wengfatt. This is being tracked in https://github.com/desktop/desktop/issues/5891 -- please follow along there for updates.
