### ISSUE TITLE
please check my account. 

### ISSUE THREAD

**Issue by juniormiguel** [desktop/desktop#13137]
i am seeing pulls and stuff in my history if im reading ths correctly. and possibly something to do with my sim card , not sure. can you tell me if my bf is monitoring my account or hacking my cell phone, i have an iphone xr. thnk you for your time. im new to all this so if you have any pointers please share thank you

**Comment by niik** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!

**Comment by juniormiguel** [comment]
Hello
