### ISSUE TITLE
Unable to Clone Private Repository

### ISSUE THREAD

**Issue by ParadaCarleton** [desktop/desktop#13131]
Attempting to clone a private repository the user has access to results in an authentication error.

### Version & OS

Version 2.9.3-linux3 (x64)

### Steps to reproduce the behavior

1. Click "Clone repository" and enter URL
2. Enter authentication information
3. Get "Authentication failed" error, regardless of whether user enters password or personal access token

### Expected behavior

Repository should be cloned

### Actual behavior

Repository is not cloned.

**Comment by niik** [comment]
Thanks for the report! Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by digitalpanopticon** [comment]
Hey there, I have the same problem.
Cloning a private repository from my account works fine but cloning one from an organisation fails as explained above.
I tried both using a Token and my password, when prompted to enter my credentials.
For both it prompts me to enter my creds again...

In git on the commandline it works just fine.

**Comment by steveward** [comment]
@noagon there may be an issue with the permissions in your organization. Can you confirm you have the correct access permissions for the repository you are trying to clone? You can also upload a log file if you'd like for me to take a look and see if there are any underlying errors that could show what the issue is.

**Comment by KevinMarques** [comment]
Same problem here while cloning repository using SSH key. Doing it through **git** console **works fine**.

No permission issues in my organization.

I'm using Github Desktop version 2.9.4

> 2021-10-21T09:51:50.206Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.773s)
> 2021-10-21T09:51:51.643Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.271s)
> 2021-10-21T09:51:51.643Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
> stderr:
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> The requested repository either does not exist or you do not have access. If you believe this repository exists and you have access, make sure you're authenticated.
> 
> (The error was parsed as 2: Authentication failed. Some common reasons include:
> 
> - You are not logged in to your account: see File > Options.
> - You may need to log out and log back in to refresh your token.
> - You do not have permission to access this repository.
> - The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
> - If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
> - If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
> - If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)

**Comment by steveward** [comment]
@KevinMarques are you on Windows or macOS? If you are on Windows can you go to `File` > `Options` > `Advanced` and check if `Use system OpenSSH` is selected under `SSH`?

**Comment by digitalpanopticon** [comment]
> Can you confirm you have the correct access permissions for the repository you are trying to clone

As said: "In git on the commandline it works just fine." So yes, I have the right permissions. I also tried it on Windows and it worked right away. Seems to be an Linux Problem.
Ill upload the logfile as soon as I can.

**Comment by KevinMarques** [comment]
> @KevinMarques are you on Windows or macOS? If you are on Windows can you go to `File` > `Options` > `Advanced` and check if `Use system OpenSSH` is selected under `SSH`?

I'm on Windows and yes, `Use system OpenSSH` is selected.

**Comment by rodlie** [comment]
This is a very annoying issue and should have been fixed years ago. 

I must clone private repos from the terminal and then add that to GitHub Desktop, very bad workflow.

1. I'm not logged in
2. I use SSH keys
3. It's impossible to clone private repos (git@github.com:ORG/REPO)

**Comment by Umme14** [comment]
@niik I'm facing the same issue. It is working fine in windows but recently my company switch from windows to linux centOS 8 server and facing the same issue of cloning repository.
For reference I'm attaching my log file with this.
[2024-02-21.desktop.production.log](https://github.com/desktop/desktop/files/14373102/2024-02-21.desktop.production.log)
[2024-02-21.desktop.production.log](https://github.com/desktop/desktop/files/14373108/2024-02-21.desktop.production.log)

**Comment by steveward** [comment]
@Umme14 for the Linux fork of GitHub Desktop you'll want to look in https://github.com/shiftkey/desktop/issues for corresponding issues. It's likely you're running into https://github.com/shiftkey/desktop/issues/972.
