### ISSUE TITLE
clone

### ISSUE THREAD

**Issue by shanmuka089** [desktop/desktop#13130]
### Describe the feature or problem you’d like to solve

Write a clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

Please share how this will it benefit Desktop and its users?

### Additional context

Please include any other context, like screenshots or mockups, if applicable.

**Comment by steveward** [comment]
Thanks for reaching out @sagaragarwal94. If you are having an issue with GitHub Desktop please fill out the issue template so we can assist you further. Thanks!
