### ISSUE TITLE
Cancelling cloning large repository

### ISSUE THREAD

**Issue by klenium** [desktop/desktop#13139]
### Describe the feature or problem you’d like to solve

I started cloning a repository since it could help me as told by a tutorial. Sure, but this repository is huge, probably it has large commit history. The repo is the IntelliJ IDEA Community storage. Cloning this repo via the GitHub Desktop killed my PC, too much network and storage usage. I just decided I'll skip this step or try it from another way (like not cloning historic commits). But uh, I can't canel the cloning process. :(

### Proposed solution

Add a cancel button if cloning the repo takes lot of time. Or alternatively add a remove this repo to the right-click context menu.

**Comment by niik** [comment]
Hey @klenium, thanks for reaching out. We're tracking this request in https://github.com/desktop/desktop/issues/2082 so please follow along there for updates!

**Comment by klenium** [comment]
Great, thanks! Sorry I couldn't find that other ticket. :(
