### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by LynnbaronGitHub** [desktop/desktop#13147]
When trying to push locally made changes via github desktop to a bitbucket repository, I am shown an authentication error and a request to fill in my username and password. Neither my bitbucket nor github login information are accepted.
![image](https://user-images.githubusercontent.com/16822469/137757689-8f73d7f1-f338-46d2-87cf-a74622565d4a.png)

**Comment by sergiou87** [comment]
Hello @LynnbaronGitHub ! 👋 

I think the problem might be related to that paragraph you can see right above the buttons: you need to provide, not a password, but a Personal Access Token generated from Bitbucket. You can check [our integration docs](https://github.com/desktop/desktop/blob/development/docs/integrations/bitbucket.md) to get some help on that.

I'll close this issue, as I think that's the problem, but if it's not, let me know and I'll reopen it 😄
