### ISSUE TITLE
Error while cloning.

### ISSUE THREAD

**Issue by e-adware** [desktop/desktop#13149]
OS: Linux Mint 18.3(64-bit)
Github Desktop Version 2.9.3-linux3 (x64)

`Cloning into '/var/www/html/project_name'...
/usr/lib/github-desktop/resources/app/git/libexec/git-core/git-remote-https: symbol lookup error: /usr/lib/github-desktop/resources/app/git/libexec/git-core/git-remote-https: undefined symbol: curl_global_sslset

Would you like to retry cloning project_name?`

I am getting this error.

**Comment by sergiou87** [comment]
@e-adware issues related to the unofficial Linux fork of GitHub Desktop can be filed here:

https://github.com/shiftkey/desktop/issues

At this time we only officially provide support for macOS and Windows.

Sorry!
