### ISSUE TITLE
Feature: Context menus on Current Repository/Branch panels

### ISSUE THREAD

**Issue by veloxo** [desktop/desktop#13148]
### Describe the feature or problem you’d like to solve

Feature: Add the context menus in repo/branch-selection dropdowns available on the "Current Repository" and "Current Branch" panels themselves.

### Proposed solution

This makes it easier to access context-menu options, eg copying repo/branch names, which I frequently use to paste to coworkers or into remote sessions. Currently, these panels have no context menu (right-clicking does nothing).

**Comment by ADustyOldMuffin** [comment]
Hello! I think this should be fairly straight forward, and if this is available for the community I'd like to take this on.

**Comment by msavin** [comment]
Very nice and obvious improvement
