### ISSUE TITLE
History's "File Lists" Column Width, at HDPi

### ISSUE THREAD

**Issue by jyxjjj** [desktop/desktop#13145]
### Describe the feature or problem you’d like to solve

When i use a large screen, i want see the full path of the History's File Lists.
But the desktop application will not let me pull more wider.

### Proposed solution

-

### Additional context

It has poor width only like this.

Even i have already use 4K screen.

![image](https://user-images.githubusercontent.com/16695261/137656076-0944e1d0-dd7a-4c11-8335-483fcfb7a625.png)

Disable the CSS max-width may let it work.

Or do not use release version of Electron, release Desktop application with SDK version of Electron, so that we can edit the CSS by ourselfs.

**Comment by niik** [comment]
Hi @jyxjjj, thanks for reaching out. We're tracking this issue in https://github.com/desktop/desktop/issues/2745 so please follow along there for updates!
