### ISSUE TITLE
Width of file list pane is clamped to some arbitrary max value

### ISSUE THREAD

**Issue by KutanaDev** [desktop/desktop#13157]
### Describe the bug
The GitHub desktop app is divided into three panes; the left-hand pane contains Changes or History. When the left hand pane is displaying History, the middle pane contains a list of the files changed at a particular revision and the right-hand pane contains a diff view.

There are vertical splitters between adjacent panes allowing their width to be changed.

The issue is that the max width of the middle pane is clamped to some arbitrary value. The repo I'm working on has several levels of folders and I'd like to be able to widen the middle pane so I can see the file path in its entirety. Currently at its widest the pane shows the entire filename and a collapsed rendering of the text in the file's path. The only way of seeing folder names is to hover the mouse over each file in turn until the tooltip appears. This is awkward.

### Version & OS

Windows 10 x64, GitHub desktop Version 2.9.4 (x64)

### Steps to reproduce the behavior

1. View a repository 
2. Click on the History tab in the left hand pane
3. Click and drag the vertical splitter on the right-hand edge of the middle pane.
4. The width of the pane is clamped to some arbitrary value.

### Expected behavior

I would expect to be able to drag the vertical splitter anywhere I like within the app window.

**Comment by steveward** [comment]
Thanks for the feedback @KutanaDev. This is being tracked in https://github.com/desktop/desktop/issues/2745 -- I'll reference this issue there.

**Comment by KutanaDev** [comment]
I just noticed that this is fixed in GitHub desktop - probably has been for a while.

But Many Thanks anyway. I can see the entire file path now!




[Logo]<https://kutana.co.uk/>

Brian Thomas | Senior Developer

Kutana Ltd | The Old Mill, Mill St, Wantage, OX12 9AB
e: ***@***.*** | w: www.kutana.co.uk<http://www.kutana.co.uk/>
m: +44 (0)7952 451 429 | p: +44 (0)333 202 0971




________________________________
