### ISSUE TITLE
Support git Stash

### ISSUE THREAD

**Issue by Zh1Cheung** [desktop/desktop#13159]
### Describe the feature or problem you’d like to solve

I want to add a new one, and use it frequently ：git stash

Now if there is a file conflict or you want to submit a part of the code during use, it will be very inconvenient

**Comment by steveward** [comment]
@Zh1Cheung thanks for the issue. GitHub Desktop does support stashing -- see [this guide](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/stashing-changes) for how to stash. I hope that helps!
