### ISSUE TITLE
Is dead repo?

### ISSUE THREAD

**Issue by WinterSilence** [desktop/desktop#13163]
Application don't integrated with popular editors as Notepad++ and PhpStorm.
I checked it 2 years ago, I check it now - no changes.
So the obvious question: is this application abandoned?

**Comment by steveward** [comment]
@WinterSilence thanks for the issue. GitHub Desktop does support Notepad++ and PHPStorm -- you can find the full list of supported editors [here](https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md#windows).

Let me know if you're having any issues getting them integrated.
