### ISSUE TITLE
Add a 'Display Recent' toggle in options > Appearance.

### ISSUE THREAD

**Issue by Tonemon** [desktop/desktop#13160]
### Describe the feature or problem you’d like to solve

Previously I found the `Recent` category in the `Current Repository` tab useful, but at the moment it's just an extra category which I would rather hide to have an organized list of all currently cloned repositories. This would also make the only headers in the list the category headers of repositories forked from others or organizations.

### Proposed solution

I think it would be a useful feature to add a `Display Recent` toggle in the `options` > `Appearance` tab (below light/dark/system theme options), where users can decide if they want the `Recent` category to appear in de list of repositories. It could also be enabled on default so only users who wish to hide it need to go to the options to disable it.

**Comment by steveward** [comment]
Thanks for the issue @Tonemon. I'm going to close this in favor of https://github.com/desktop/desktop/issues/11598 and add your feedback there.
