### ISSUE TITLE
Add tree view to changes

### ISSUE THREAD

**Issue by JonasSamuelsson** [desktop/desktop#13162]
I think there are some usability problem with the current list of changes, primarily related the long paths.
Since the path has to be truncated it is sometimes difficult to identify individual files and also hard to get a sense of which files are physically close to each other.

```
▢ app\co...\data\file1.txt
▢ app\co...\data\file2.txt
▢ app\sta..\background.jpg
```

It would be great if you could add a tree view as a complement to the list view, with an easy way to switch between the two.
Would be nice to have the possibility to include/exclude files on the folder level as well.

```
▢ ▵app
▢  ▵content\data
▢    file1.txt
▢    file2.txt
▢  ▵staticContent
▢    background.jpg
```

**Comment by steveward** [comment]
Thanks for the feedback @JonasSamuelsson. I'm going to add this to https://github.com/desktop/desktop/issues/2417, where we are tracking feedback for a tree view in the `Changes` tab. Even if an issue is closed it does not mean we may not prioritize it in the future. I'm going to close this out. Thanks for using GitHub Desktop!

**Comment by umarcor** [comment]
@steveward, how to you tell apart issues to be prioritized in the future from non-relevant issues? It seems that #2417 has no label, milestone or any other method for you to find it in the future...
