### ISSUE TITLE
M1 MacBook Pro White Screen of Death

### ISSUE THREAD

**Issue by df511** [desktop/desktop#13166]
### Version & OS

I am using macOS Big Sur Version 11.4 on a MacBook Pro (M1, 2020). I cannot see any display for the version of GitHub desktop, but I have tried re-downloading and installing several times over the last couple weeks. 

### Steps to reproduce the behavior

1. Download and install GitHub Desktop (latest version from website for Apple Silicon chips, most recently downloaded on 10/23/21).
2. Open program to see blank, white screen and no functionality.

### Expected behavior

I expected the program to open as usual and be able to interact with the typical GitHub Desktop interface.

### Actual behavior

I open program and see only a blank, white screen and no functionality. I can click through menu options, but nothing displays, and only menu options which refer to hyperlinks and open a web-page respond at all.

### Screenshots

![image](https://user-images.githubusercontent.com/30601505/138575108-33ef1e39-9fa0-4239-8712-220a3cc1943d.png)### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

[2021-10-24.desktop.production.log](https://github.com/desktop/desktop/files/7403848/2021-10-24.desktop.production.log)

**Comment by sergiou87** [comment]
Hey @df511 👋 

I'm sorry you're experiencing this issue. As far as we know, it happened _some times_ with x64 (non-arm) builds. Have you tried the arm64 builds of Desktop? The latest one is here: https://central.github.com/deployments/desktop/desktop/latest/darwin-arm64

Please, give that a try and let me know if it works!

PS: I love the screenshots 😂

**Comment by df511** [comment]
Hey Sergio,

Haha glad you liked the screenshots.

Yup, that's the one I've primarily been trying to use. Still getting just
the blank white screen. Any ideas?

- Dan

**Comment by sergiou87** [comment]
Has it ever worked? The only idea I have is to delete the folder `~/Library/Application Support/GitHub` and see if that works.

It'd be also interesting if you could open the developer tools (from the `View` menu -> `Toggle Developer Tools`) and then switch to the `Console` tab looking for errors or anything that seems relevant.

Please let me know if any of that helps! 🤞

**Comment by df511** [comment]
Hi, could you please reopen the issue? I apologize, I missed the previous
email. GitHub desktop has never worked. I also don't have a folder called
GitHub folder within Application Support. I saw that advice online, but
since the folder doesn't exist, I couldn't delete it. I haven't had a
chance to open the dev tools yet. I'll do that shortly!

- Dan

**Comment by steveward** [comment]
@df511 can you check if you have a `~/Library/Application Support/GitHub Desktop` directory? @sergiou87 likely meant that directory. Normally the `IndexedDB` directory is the specific one that needs to be deleted within `GitHub Desktop`.

**Comment by df511** [comment]
Hi Steve,

Thanks for that. I don't seem to have any directory related to GitHub
(/GitHub or /GitHub Desktop) in my /Application Support folder. I did find
that a bit odd. I checked for hidden folders as well, and still nothing.

- Dan

**Comment by sergiou87** [comment]
@df511 were you able to show the developer tools following these instructions?
> It'd be also interesting if you could open the developer tools (from the `View` menu -> `Toggle Developer Tools`) and then switch to the `Console` tab looking for errors or anything that seems relevant.

**Comment by df511** [comment]
Hi Sergio,

This is what I see when I open the Dev Tools.

[image: image.png]

Thanks!

- Dan

**Comment by sergiou87** [comment]
I'm sorry @df511 but the image got lost since you replied via email 😞 

(Also I'm sorry, but for some reason I missed the notification of your reply, hence my late response 😳 )

**Comment by df511** [comment]
HI Sergio,

Attaching again now!


- Dan

**Comment by sergiou87** [comment]
@df511 nothing 😢  I think you must post that image by replying from GitHub directly 😳

**Comment by df511** [comment]
![image (2)](https://user-images.githubusercontent.com/30601505/141367507-99228570-0821-48da-8f46-c073cf2ef5c0.png)

Ah okay! This should've worked then.

**Comment by sergiou87** [comment]
Yes, thank you! It seems like there is something wrong with the database, I'm surprised you can't find it 🤔 

Could you run this from a terminal to make sure it doesn't exist?
```
ls ~/Library/Application\ Support/GitHub\ Desktop
```

**Comment by df511** [comment]
![image](https://user-images.githubusercontent.com/30601505/141513955-b11c0abf-85dd-4d1e-86c3-e62733f3206e.png)
(FYI, this isn't a macbook air, I just transferred files directly from my previous computer). 

There's a "Databases.db" within the database folder, as well

**Comment by sergiou87** [comment]
Could you remove that folder?

If you want to keep a backup, you can use this: `mv ~/Library/Application\ Support/GitHub\ Desktop ~/Library/Application\ Support/GitHub\ Desktop-backup`
Otherwise, just run this to remove the folder directly: `rm -rf ~/Library/Application\ Support/GitHub\ Desktop`

That should restore the app settings and _hopefully_ fix the issue at hand 🤞

**Comment by df511** [comment]
Yessss! Thank you so much, Sergio! The program just opened normally and I'm configuring settings now. 

- Dan

**Comment by steveward** [comment]
I'm glad to hear that got things working! I'm going to close this out.
