### ISSUE TITLE
View conflicts menu scroll bar overlays menu button

### ISSUE THREAD

**Issue by jsakas** [desktop/desktop#13161]
### Describe the bug

When viewing conflict lists that are longer than a few files, there is an invisible scroll bar that takes precedence over the down chevron in the options list. When you try to click it, the scroll bar takes the event and it moves the page around. Difficult to reproduce.  

### Version & OS

- Version 2.9.4 (x64)
- macOS Big Sur 11.3.1 (20E241)

### Steps to reproduce the behavior

1. Rebase something with more conflicts than can fit in the "View conflicts window"
2. Try to click the options menu toggle
3. Many times the menu will move up and down because the scroll bar is being clicked

### Expected behavior

I can open the menu without issue on long conflicts lists.

### Actual behavior

The scroll bar takes the click event and the window scrolls up and down. 

### Screenshots

![Screen Shot 2021-10-21 at 1 19 33 PM](https://user-images.githubusercontent.com/4934432/138343258-af75845d-0480-464b-b74f-1414a3cf324b.png)

![Screen Shot 2021-10-21 at 1 16 50 PM](https://user-images.githubusercontent.com/4934432/138343263-d85576ac-e065-4b4e-9b2e-9c90daa98827.png)

**Comment by steveward** [comment]
Thanks for the report @jsakas! This is being tracked in https://github.com/desktop/desktop/issues/6199, so I'm going to close this issue out.
