### ISSUE TITLE
Authentication of old GitHub.com account persists whenever GitHub Desktop is restarted

### ISSUE THREAD

**Issue by cyeow** [desktop/desktop#13172]
### Describe the bug
Authentication of old GitHub.com account persists whenever GitHub Desktop is restarted. Git config has already been updated to match the new account's information. 

### Version & OS
GitHub Desktop: Version 2.9.4 (x64)
OS: Windows 8.1

### Steps to reproduce the behavior

1. Log into `GitHub.com account A` on GitHub Desktop 
2. Clone any existing repo from `GitHub.com account A` 
3. Close GitHub Desktop fully & reopen GitHub Desktop 
4. Log out of `GitHub.com account A` and log into `GitHub.com account B`
5. Under File > Options > Git, update name & email to match with `GitHub.com account B` (just to be sure the problem does not lie with Git config)
6. Close GitHub Desktop fully & reopen GitHub Desktop
7. Open File > Options. Observation: `[Git tab]` Git config remains updated while `[Accounts tab]` GitHub.com login reverts to `GitHub.com account A`. 

### Expected behavior

After step 6 above, the GitHub.com account should be `GitHub account B`. 

### Actual behavior

After step 6 above, the GitHub.com account is `GitHub account A`. 

### Screenshots

Logged into `GitHub.com account B`: 
![image](https://user-images.githubusercontent.com/8532365/138633224-9e1f8679-1cc1-484a-8b2e-db827126e2e4.png)

After restarting GitHub Desktop: 
![image](https://user-images.githubusercontent.com/8532365/138633559-e2c9136c-bc0b-4377-9e6d-f9af2e60b850.png)

### Logs

[2021-10-25.desktop.production.log](https://github.com/desktop/desktop/files/7407160/2021-10-25.desktop.production.log)
(cyeow [myself] is AccountB) 

### Additional context

(Will add on if necessary)

**Comment by steveward** [comment]
Thanks for the report @cyeow. I tested this out fairly thoroughly, and wasn't able to reproduce the issue. I'd be curious to see if you are still able to reproduce this after clearing out any locally stored data. Here's how you can do that:

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop (you will need to log in and add your repositories back via drag-and-drop)

Let me know if you are still able to reproduce this issue. We also just got a report in https://github.com/desktop/desktop/issues/13232 that looks similar.

**Comment by steveward** [comment]
@cyeow I'm going to close this out as we have not heard back from you -- let me know if you're still encountering this issue or are able to directly able to reproduce it again. Thanks!
