### ISSUE TITLE
Github Desktop application issue

### ISSUE THREAD

**Issue by zahid819** [desktop/desktop#13175]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also, include what operating system you are using.

### Steps to reproduce the behavior

4. See an error

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

my folder is not being accessed by GitHub
![ddddhhhhh](https://user-images.githubusercontent.com/92372515/138676886-1574feb6-0bfe-4af4-95b1-86fbe0708093.PNG)
 desktop application

**Comment by steveward** [comment]
Thanks for the issue @zahid819. It looks like your repository just need to be "found" again -- you should see a prompt to locate it again when you select the repository. Let me know if you are not seeing that and we can dig into this further.

**Comment by zahid819** [comment]
The repository doesn't seem to be accessed by Github. Facing same issue

**Comment by steveward** [comment]
@zahid819 can you share your log file from GitHub Desktop? I need some further details about the errors you are encountering.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
