### ISSUE TITLE
Add TOKEN login

### ISSUE THREAD

**Issue by jajosheni** [desktop/desktop#13189]
### Describe the feature or problem you’d like to solve

I love using Github Desktop but now I have to request for permission to use it with any repos that do not belong to me but that I am a collaborator of.

### Proposed solution

I would like to have an option to log in via Github Desktop using a generated token from the website.
 Jetbrains IDEs already have this feature.

**Comment by steveward** [comment]
Thanks for the issue @jajosheni. At this time we don't have any plans of changing the authentication methods available for GitHub Desktop, but we do appreciate the feedback. We're tracking support for multiple accounts in https://github.com/desktop/desktop/issues/3707, which would likely require alternative authentication methods outside of browser auth. I'd recommend following along there for updates.
