### ISSUE TITLE
Curl 56 Failure

### ISSUE THREAD

**Issue by WattSkill** [desktop/desktop#13181]
Describe the bug
Me and My friend are trying to Setup a github for us both to keep files updated ETC and he is getting error code (curl 56 Failure)

Version & OS
He is using version Version 2.9.4 (x64)
Windows 10 21H1
Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

Steps to reproduce the behavior

1. Ive pushed a source (100MB push)
2. He is pulling
3. It gets to Receiving Objects 95%
4. Error

Expected behavior

This is meant to let him to pull the files and lets us do what we need to do

Actual behavior

This error comes up 

remote: Enumerating objects: 458, done.
remote: Counting objects: 100% (458/458), done.
remote: Compressing objects: 100% (431/431), done.
error: RPC failed; curl 56 Failure when receiving data from the peer
error: 3189 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

Screenshots

https://media.discordapp.net/attachments/814522965261025360/902233113994874990/unknown.png?width=404&height=227

Logs

https://pastebin.com/ugYpZd6r

**Comment by steveward** [comment]
Thanks for the report @AshedTRP. This looks like a network issue -- are you encountering this issue only in one specific repository? Are you behind a proxy/firewall or running any antivirus software the could be interfering with your connection?

**Comment by WattSkill** [comment]
@steveward he hasn't got any proxy/firewall or antivirus only thing it could be is windows defender and when he turns that off it still doesn't work

**Comment by Ammo1x** [comment]
Hello it is me with the Issue it shouldn't be my wifi but if it is I dont understand why as its 100mbs download and 40mbs upload so I am not sure

**Comment by WattSkill** [comment]
@steveward

**Comment by steveward** [comment]
@Ammo1x unfortunately this just looks like connection issues, and not a specific problem with GitHub Desktop. You could try switching to using SSH to see if you have better success. See this guide for setting up a new SSH key:

https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

You will also need to change the URL of your repository to use SSH. You can do this in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. You will want the URL to look like `git@github.com:<user>/<repo>.git`. Let me know if that gets things working.

**Comment by WattSkill** [comment]
@steveward so he cant use the github desktop and needs to use gitbash?

**Comment by WattSkill** [comment]
This is what it says when he changes it 
Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.

**Comment by steveward** [comment]
@AshedTRP you can use SSH with GitHub Desktop as well. If there is are an issue with SSH it would be helpful if the full log file could be sent over (`Help` > `Show Logs...`).

**Comment by kdantley** [comment]
Help

**Comment by Ammo1x** [comment]
[2021-10-28.desktop.production.log](https://github.com/desktop/desktop/files/7430035/2021-10-28.desktop.production.log)

**Comment by steveward** [comment]
@Ammo1x that log file is still only showing the cURL 56 error -- did you set up SSH? How large is the repository you are attempting to push?

You can also run `ssh -v git@github.com` to debug the SSH connection. If you can run that from the command line and let me know the output we can dig into this further.

**Comment by franker54** [comment]
I am assuming you work with something to do with Git Hub. I have not done
any form of coding in over 10 years so I have no clue how to do it right
and gave up after like 5 trys. I actually could use some help !

**Comment by WattSkill** [comment]
@steveward he isnt trying to push he is trying to pull like 500mb and its giving that error

**Comment by Ammo1x** [comment]
> @Ammo1x that log file is still only showing the cURL 56 error -- did you set up SSH? How large is the repository you are attempting to push?
> 
> You can also run `ssh -v git@github.com` to debug the SSH connection. If you can run that from the command line and let me know the output we can dig into this further.

Where do I run this sorry? @steveward

**Comment by WattSkill** [comment]
@steveward please help!

**Comment by steveward** [comment]
@Ammo1x you can run that command in Git Bash -- have you installed [Git for Windows](https://git-scm.com/download/win) on your machine? You can launch the command line from within GitHub Desktop by going to `Repository` > `Open in <command_line>`.

If you are having issues setting up a new SSH key please let me know.
