### ISSUE TITLE
Authentication error while publishing branch using Github Desktop 

### ISSUE THREAD

**Issue by 15jindalrahul** [desktop/desktop#13198]
Please help in resolving the issue.I am in middle of important work and this is creating trouble for me. 
I am putting correct username  and in password field correct Private Access token .But still it is saying authentication failed.

Screenshot (23)
https://user-images.githubusercontent.com/38556126/139046964-d7b01c37-de4c-47c2-a9d8-f521ae0fa708.png

**Comment by steveward** [comment]
Thanks for the report @15jindalrahul. Are you using GitHub Enterprise, or a different Git hosting service with GitHub Desktop?

If you are using GitHub Enterprise you will need to authenticate by following the steps [here](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/installing-and-authenticating-to-github-desktop/authenticating-to-github).

**Comment by 15jindalrahul** [comment]
I am using gitlab .There we have repository and i have cloned that repository succesfully.
On my local i am using Github Desktop.

Please help , i am struggling from past 1 week.

**Comment by steveward** [comment]
Thanks for the update. Can you confirm you followed the same steps as mentioned in [this document](https://github.com/desktop/desktop/blob/development/docs/integrations/gitlab.md)? Let me know if that does not get things working.

**Comment by 15jindalrahul** [comment]
i dont have github account and also enterprise account.
I have gitlab account

**Comment by steveward** [comment]
@15jindalrahul the article I shared above gives you steps for authenticating via GitLab -- make sure you've followed those specific steps.

**Comment by 15jindalrahul** [comment]
yes already done then only i was able to clone the repository last week.
I have created Personal access token last week only and today again.
In scopes i have uptick api,   read_user ,read_repository ,read_registry .Is that affecting anything?
Do i have to tick only api?

**Comment by steveward** [comment]
@15jindalrahul I would recommend going to `Credential Manager` > `Windows Credentials` and deleting the `GitHub - <your_gitlab_server>` entry. Then try recreating the token again. I believe either `api` or `write_repository` should work for access. 

Have you also tried pushing via the command line to verify this isn't a permissions issue?

**Comment by 15jindalrahul** [comment]
> @15jindalrahul I would recommend going to `Credential Manager` > `Windows Credentials` and deleting the `GitHub - <your_gitlab_server>` entry. Then try recreating the token again. I believe either `api` or `write_repository` should work for access.
> 
> Have you also tried pushing via the command line to verify this isn't a permissions issue?

checked via command line ,but still the same authentication issue
 

How should i connect with you ,so that i can share the screen and resolve this issue.

**Comment by steveward** [comment]
Just to confirm -- pushing via the command line succeeded?

**Comment by 15jindalrahul** [comment]
> Just to confirm -- pushing via the command line succeeded?

no ,same error authentication coming

**Comment by steveward** [comment]
If you are having an issue pushing from the command line and GitHub Desktop then this is likely a permission issue. Since you were able to clone the repository but not push I would verify that you have read/write access and not read only access. I'm not as familiar with GitLab's permissions system so you may need to reach out to them for further assistance or get in touch with someone in your organization.

**Comment by steveward** [comment]
@15jindalrahul I'm going to close this out since we haven't heard back from you -- let us know if you're still having issues.
