### ISSUE TITLE
bug in file name

### ISSUE THREAD

**Issue by Gonzalobarrioss** [desktop/desktop#13190]
### Describe the bug
Github Desktop duplicates the first letter of the filename

### Version & OS

Version 2.9.4 (x64)
Windows 10 Pro Version 20H2 - S.O Version 19042.631

### Steps to reproduce the behavior

Open Github Desktop
1. Go to 'Current Repository'
2. See error on "Changes" screen

### Expected behavior

I was hoping that I did not duplicate the first letter, like the other files

### Actual behavior

I duplicate the first letter of the file, and I can't commit

### Screenshots

![bug github](https://user-images.githubusercontent.com/49219316/138886737-5f13482e-f01c-4bcf-8927-f30241e1e806.jpg)

### Additional context

Thanks you all

**Comment by steveward** [comment]
Thanks for the issue @Gonzalobarrioss -- this is being tracked in https://github.com/desktop/desktop/issues/12314. You can follow along there for updates.
