### ISSUE TITLE
'Add existing repositoy...' doesn't add repository to app.

### ISSUE THREAD

**Issue by Flohhhhh** [desktop/desktop#13199]
### Describe the bug
When attempting to add a repository to the desktop app using Add > Add existing repository nothing happens. Additionally, deleting and trying to clone the same repository successfully clones it onto my device, but it then disappears from the desktop app UI.

### Version & OS
Version 2.9.4 (x64)
Windows 10

### Steps to reproduce the behavior

1. Go to Repository list
2. Click on 'Add'
3. Click on 'Add existing repository'
4. Enter local path of repository
5. Click Add repository

### Expected behavior

I expect the repository to be added to the desktop app so I can see history and make commits.

### Actual behavior

Nothing happens and the modal disappears.

### Screenshots
![image](https://user-images.githubusercontent.com/48927090/139088729-5d812309-23f2-4b95-acfd-760aea3f2b06.png)

### Logs
[2021-10-27.desktop.production.log](https://github.com/desktop/desktop/files/7427061/2021-10-27.desktop.production.log)

**Comment by Flohhhhh** [comment]
Someone was able to successfully perform this same action without any issue for the same repository. So it's just an issue with my client.

**Comment by Flohhhhh** [comment]
This won't work with any repository

**Comment by steveward** [comment]
@Flohhhhh thanks for the report. What happens if you try and drag-and-drop a local repository into GitHub Desktop?

I would recommend clearing out the locally cached data in GitHub Desktop to see if that gets things working:

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop

Let me know if that helps.

**Comment by Flohhhhh** [comment]
Same issue for dragging! It shows the dialogue and after pressing it closes but nothing happens.

Fortunately, clearing the app data seems to have resolved it. Thanks for the help!

**Comment by steveward** [comment]
Glad to hear that got things working!
