### ISSUE TITLE
how to pull a request

### ISSUE THREAD

**Issue by wilsonkamau** [desktop/desktop#13205]
### Describe the feature or problem you’d like to solve

Write a clear and concise description of what the feature or problem is. If this is a bug report, please use the bug report template instead.

### Proposed solution

Please share how this will it benefit Desktop and its users?

### Additional context

Please include any other context, like screenshots or mockups, if applicable.

**Comment by steveward** [comment]
@wilsonkamau thanks for the issue. GitHub Desktop allows you to launch directly into creating an issue or pull request from the app. See [this article](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/creating-an-issue-or-pull-request) for the specific steps. Let me know if you have any questions!
