### ISSUE TITLE
i can't sign in to my github account while using GitHub Desktop..it asks to sign in using your browser and when i click continue with browser, it stacks

### ISSUE THREAD

**Issue by Joelgashaw** [desktop/desktop#13202]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by niik** [comment]
Hey, thanks for reaching out! This looks very similar to the request in #11410 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date with any development happening in that area. It seems a lot of users have reported success in switching their default browser temporarily.
