### ISSUE TITLE
Rebase window gets stuck after conflicts are resolved and "Continue rebase" button clicked

### ISSUE THREAD

**Issue by recyard** [desktop/desktop#13204]
### Describe the bug
Rebase window gets stuck after conflicts are resolved and "Continue rebase" button clicked

### Version & OS

Version 2.9.4 (x64) on: MacOS 12.0.1 with Git 2.30.1 & Windows 7 with Git 2.33.1

### Steps to reproduce the behavior

1. Clone a repo from GitHub.
2. git config pull.rebase true
    git config rebase.autoStash true
3. On GitHub web, add a file "j" with content "123" and commit.
4. On local cloned repo, do not pull latest change, but add a file "j" with content "456" and commit.
5. On Github Desktop, click Repository -> Pull, a window pops out, showing 1 conflicted file.
6. Click "Open in some editor", resolve the conflict, then save the file, go back to Github Desktop.
7. Now the pop-out window shows 0 conflicted files, so click "Continue rebase".
8. The window will stuck forever, have to force quit the app then reopen, this time the "Continue rebase" can complete.

### Expected behavior

The rebase can complete without problem.

### Actual behavior

The rebase window gets stuck.

### Screenshots
![Screen Shot 2021-10-29 at 17 43 33](https://user-images.githubusercontent.com/2900536/139415892-a75651d3-b2d1-4a49-9400-2473936207ba.png)

### Logs

2021-10-29T09:42:15.404Z - info: [ui] Executing pull: git -c credential.helper= -c rebase.backend=merge pull --progress origin (took 2.272s)
2021-10-29T09:42:15.405Z - error: [ui] `git -c credential.helper= -c rebase.backend=merge pull --progress origin` exited with an unexpected code: 1.
stdout:
CONFLICT (add/add): Merge conflict in j
Auto-merging j

stderr:
remote: Enumerating objects: 3, done.        
remote: Counting objects:  33% (1/3)        
remote: Counting objects:  66% (2/3)        
remote: Counting objects: 100% (3/3)        
remote: Counting objects: 100% (3/3), done.        
remote: Compressing objects:  50% (1/2)        
remote: Compressing objects: 100% (2/2)        
remote: Compressing objects: 100% (2/2), done.        
remote: Total 2 (delta 1), reused 0 (delta 0), pack-reused 0        
From https://github.com/***/example
   0dc2203..595475d  master     -> origin/master
Rebasing (1/1)
error: could not apply de6810f... Create j
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply de6810f... Create j

(The error was parsed as 6: We found some conflicts while trying to rebase. Please resolve the conflicts before continuing.)

### Additional context

For a successful rebase, additional logs will show, but when the window hangs, no following logs.

2021-10-29T09:44:14.948Z - info: [ui] [continueRebase] continuing rebase for 595475de35a731d1ae3bd1672f04e2b7890dedab
2021-10-29T09:44:15.077Z - info: [ui] [continueRebase] completed rebase - got CompletedWithoutError and on tip 95a5dd13786d336d207c13d0057375cd6ae1e685 - kind Valid

**Comment by recyard** [comment]
Hi, any comments?

**Comment by tidy-dev** [comment]
@recyard Thank you for the report! I was able to reproduce.

**Comment by tidy-dev** [comment]
It appears we are getting into a rebase without correctly setting the state when entering into a rebase through this flow. If this is a common workflow for you, something that might help you until we can get a fix out is force refreshing the app through developer tools. You can do this via the app view menu > toggle developer tools or ⌥ + ⌘ + I and then, and click inside your developer tools and press ⌘+R. This will force an app reload.. similar to you having to force quit and reopen the app.

**Comment by Xeoneid** [comment]
I've just updated and will be testing it along the week. Thanks for fixing this bug! My team totally loves the tool but this was the issue we most often encounter.

**Comment by recyard** [comment]
@tidy-dev Thanks a lot for the fix, Desktop now works like a charm.

**Comment by SwaroopKumarDasari** [comment]
![image](https://user-images.githubusercontent.com/77830492/182378574-b118aaeb-9f0c-4db4-8295-5d2e8f153104.png)
This issue is still there when I'm trying to merge a branch into another. This issue comes out of no where. could someone help me out here?

**Comment by SwaroopKumarDasari** [comment]
![Screenshot (35)](https://user-images.githubusercontent.com/77830492/182379437-f4eaa029-5a7e-4107-9452-c421013eb604.png)
My screen is stuck when I tried to merge a branch into another branch. Please resolve this issue. If someone could read this.
