### ISSUE TITLE
GD Diff tool

### ISSUE THREAD

**Issue by paulnpdev** [desktop/desktop#13215]
### Describe the feature or problem you’d like to solve

I would love to have the capability to "diff" two branches A<->B.  HEAD to HEAD by default if they are different branches, HEAD to previous commit if they are the same branch, with the option of selecting specific commits on both A and B) in the style of a github pull request.  

### Proposed solution

Makes it easy for me to preview a PR without pushing to origin.  Easy to see exactly what was in a specific commit.  Even lets me do the work of bisect with the same visual tool I'm used to using for code reviews.

Bonus points for simple edits within github desktop :) 

### Additional context

Please include any other context, like screenshots or mockups, if applicable.

**Comment by tidy-dev** [comment]
@paulnpdev Thanks for the input. I believe this is already being tracked in #6757. I am going to paste your feedback there and close this one in favor of that. Thanks again!
