### ISSUE TITLE
Cannot install GitHub Desktop on Windows 10

### ISSUE THREAD

**Issue by ZuzannaKozlowska182270** [desktop/desktop#13222]
### Describe the bug
I can't install Github Desktop. After I click the download button a box pops up with a message about some error. 

### Version & OS

Current GitHub Desktop version as I'm trying to download it.
Windows 10 Home 21H1 19043.1288. 64bit

### Steps to reproduce the behavior

1. Go to 'https://desktop.github.com/'
2. Click on 'Download for Windows 10 (64 bit)'
3. Just wait as the file is loaded. 
4. Either nothing happens and the download is marked as failed or receive dialogue box with Installation failure message and link to Setup Log file.

### Expected behavior

GitHub Desktop installation and ability to launch.

### Actual behavior

A box pops up with a message which translates to 'the file C:\Users\spook\AppData\local\Temp\F_r2oUPw.exe.part could not be saved, because the source file could not be read. Try again later, or contact the server administrator.”

### Screenshots

(url
![log](https://user-images.githubusercontent.com/93452233/139585184-76a1dee7-1210-4dac-a6b3-a076d673b57f.png)
)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

I've turned off my Avast Antivirus and restarted my computer but it didn't help.

**Comment by steveward** [comment]
Thanks for the issue @ZuzannaKozlowska182270. To get some more information about why the installation is failing it would be helpful if you could send over the log file that the Squirrel installer generates.

You should be able to find the log file here:

`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`

If no log file is being generated there you should be able to find one in the `SquirrelTemp` directory:

`%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

Please send that over as an attachment.

**Comment by ZuzannaKozlowska182270** [comment]
Thanks for the replay. I just tried once again installling Github Desktop and it works now! I wonder what was wrong the last few days but I'm glad it resolved by itself. I guess I don't have to attach the logs now.
