### ISSUE TITLE
Add a repository to the app when opening from the command line with the current folder

### ISSUE THREAD

**Issue by MaddyGuthridge** [desktop/desktop#13220]
### Describe the feature or problem you’d like to solve

I really enjoy using GitHub Desktop for working on my personal projects, but sadly the integration with repositories from external sources (such as my university's private GitLab server) isn't quite as good, and opening up those repositories takes quite a while.

### Proposed solution

It'd be awesome to automatically load a local repository if I started the app by invoking it with the command `github-desktop .` in the same directory as a git repo, similar to how I can start VS Code in that directory and the like.

**Comment by steveward** [comment]
Thanks for the issue @MiguelGuthridge. You can use `github .` to do exactly what you're looking for. I hope that helps!

**Comment by MaddyGuthridge** [comment]
Oh so it seems not to work for the fork that I'm using to get it on Linux. I'll create an issue there
