### ISSUE TITLE
Double Clicking File Opens File 

### ISSUE THREAD

**Issue by digitalmaster** [desktop/desktop#13229]
### Describe the feature or problem you’d like to solve

I love this app and I would love to integrate it into as many parts of my dev worklow as possible. I'd like to optimise the "View Changes" ➞ "Edit Changes" part of my workflow. Today the only way to do this is to right-click on a file and select "Open With Visual Studio Code". 

![image](https://user-images.githubusercontent.com/1279335/139691431-bd35831d-85bc-43da-be50-0fee0d8f6a9e.png)

### Proposed solution
Make that action the default action triggered by double click 🤓

### Additional context
Nice to haves:
- The ability to also do that from the diff as well (Maybe CMD - Click takes you to that file at that line)
- The ability to set the default editor (so we don't have to choose each time or set system defaults for every file type)

**Comment by steveward** [comment]
Thanks for the feedback @digitalmaster. This is being tracked/discussed in https://github.com/desktop/desktop/issues/2620. At this time we don't have any plans to implement this but feel free to give it a 👍 reaction if it's something you'd like to see.
