### ISSUE TITLE
Commit Issue: "No such file or directory 2: ./node_modules/pre-commit/hook"

### ISSUE THREAD

**Issue by mgg143** [desktop/desktop#13221]
### Describe the bug
When I try to commit a file using GitHub Desktop, I end up with this error:
"
: No such file or directory 2: ./node_modules/pre-commit/hook
: integer expression expected: [: 127
: numeric argument required 5: exit: 0 

"

I'm hoping to make a multi-line commit message, and GitHub Desktop definitely seems like it would help with that.

### Version & OS

Version 2.9.4 (x64)
Windows 10 [Fully updated]

### Steps to reproduce the behavior

Click on "Commit" with the file I want to commit selected.  The error message then populates.

### Expected behavior

Write a clear and concise description of what you expected to happen.

I would love to have my local change committed to my GitHub repository with a descriptive comment, but instead I am getting the error message previously described.  This is very frustrating as it prevents me from contributing to my project.

### Actual behavior

GitHub Desktop tries to make the commit and then populates the error message.

### Screenshots
![GitHubDesktopError](https://user-images.githubusercontent.com/77564511/139576441-6ec1675f-43e6-4622-a6e3-d75578113202.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
[2021-10-31.desktop.production.log](https://github.com/desktop/desktop/files/7448450/2021-10-31.desktop.production.log)

### Additional context

Add any other context about the problem here

**Comment by FMA606** [comment]
https://github.com/desktop/desktop/files/7448450/2021-10-31.desktop.production.log

**Comment by steveward** [comment]
@mgg143 apologies for not getting a response back to you. If you are still running into this issue I would recommend following the solution [mentioned here](https://github.com/desktop/desktop/issues/12586#issuecomment-892436293) and [here](https://github.com/desktop/desktop/issues/12562#issuecomment-1007154382) by making this change:

```sh
npm -> npm.cmd
npx -> npx.cmd
```

Let us know if that helps.
