### ISSUE TITLE
Not able to see Amend commit action

### ISSUE THREAD

**Issue by lpilot** [desktop/desktop#13224]
### Describe the bug
I've the latest version installed and I see that feature was added to amend commit. 

https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/amending-a-commit

### Version & OS

Github Desktop - Version 2.9.4 (x64)
MAC OS - Version 12.0.1

### Steps to reproduce the behavior

Right click on on the commit and don't see amend commit action. 

### Expected behavior

As per the doc, I should see this.

![image](https://user-images.githubusercontent.com/49317423/139600890-cd140003-de21-4fe4-a2d1-5bf887741bc3.png)

**Comment by tidy-dev** [comment]
HI @sparmar-atheer! The amend action is only available for the last unpushed commit. That is indicated by the up arrow bubble icon. Sorry for the confusion!

![image](https://user-images.githubusercontent.com/75402236/139658765-db9fdd2d-e08f-4b87-921f-e7aa95d95744.png)
