### ISSUE TITLE
克隆失败

### ISSUE THREAD

**Issue by sun-tong** [desktop/desktop#13225]
error: cannot spawn C:\Users\Administrator\AppData\Local\GitHubDesktop\app-2.9.4\resources\app\static\ask-pass-trampoline.bat: No such file or directory
fatal: could not read Username for 'https://github.com': terminal prompts disabled

**Comment by tidy-dev** [comment]
Hi @sun-tong! It would seem that Desktop is not able to locate a file it requires for authentication. I would try a clean install - that is removing all the GitHub Desktop app data and reinstalling.

App data is located:
Windows: `%APPDATA%\GitHub Desktop\`
Mac: `~/Library/Application Support/GitHub Desktop/`
