### ISSUE TITLE
When I sign out, no option comes up to sign in to another different account.It keeps returning to the account I previous signed out of

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#13232]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by jakapongbucha** [comment]
Show Logs..

**Comment by steveward** [comment]
Thanks for the report @jakapongbucha. Are you logging into the different account in your browser prior to GitHub Desktop? GitHub Desktop will authenticate based on your currently-logged in GitHub account in your default browser.
