### ISSUE TITLE
Add JetBrains IDEs support to external editors

### ISSUE THREAD

**Issue by inzanty** [desktop/desktop#13257]
### Describe the feature or problem you’d like to solve

By default GitHub Desktop have VS Code, Sublime Text, Notepad ++ support, but i think that would be nice if you add support JetBrains IDEs such as PHPStorm, CLion, Rider, etc. GitHub Desktop much better in use.

### Proposed solution

Please share how this will it benefit Desktop and its users?

### Additional context

Please include any other context, like screenshots or mockups, if applicable.

**Comment by steveward** [comment]
Thanks for the issue @inzanty. We shipped broader support for JetBrains IDEs in https://github.com/desktop/desktop/pull/12778 -- is there a specific integration that is not working for you?

**Comment by inzanty** [comment]
> Thanks for the issue @inzanty. We shipped broader support for JetBrains IDEs in #12778 -- is there a specific integration that is not working for you?

I didn’t really understand what more information you need to provide from me? It's just that I don't see support for JetBrains IDE right now, or is it available in newer versions?

**Comment by steveward** [comment]
@inzanty I was asking if there was a specific Jetbrains IDE that was not showing up in GitHub Desktop, since we have shipped broader support for Jetbrains IDEs in the app already.

**Comment by inzanty** [comment]
> @inzanty I was asking if there was a specific Jetbrains IDE that was not showing up in GitHub Desktop, since we have shipped broader support for Jetbrains IDEs in the app already.

PHPStorm

**Comment by sergiou87** [comment]
@inzanty PHPStorm should be already supported, yes, unless:
1. You have an old version (from 2018 or older)
2. You installed it via JetBrains Toolbox, which is not supported _yet_

Is any of those two true in your case?

**Comment by inzanty** [comment]
> @inzanty PHPStorm should be already supported, yes, unless:
> 
> 1. You have an old version (from 2018 or older)
> 2. You installed it via JetBrains Toolbox, which is not supported _yet_
> 
> Is any of those two true in your case?

Thanks. I installed PHPStorm from clear installation, thats was problem with toolbox that you described.

**Comment by sergiou87** [comment]
Cool 😌  For now that's not supported, sorry!

**Comment by erseversahin** [comment]
The JetBrains **WebStorm** IDE is still not supported.

![image](https://user-images.githubusercontent.com/63604193/163333775-101feaba-80dc-4f7f-88d5-163a2c9345a3.png)

![image](https://user-images.githubusercontent.com/63604193/163333833-479f2a12-1a03-4fd0-bc3b-593c7ae6f32f.png)

**Comment by PiedrasAi** [comment]
When is CLion support being added?
