### ISSUE TITLE
local repository doesnt want to get added

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#13251]
ok, so i have read a few issues here with the exact or almost exact issue as mine.

whenever i try to add a local repository i have that is also on github, it adds for a couple of seconds then i get an error "cant locate X" and happens over and over no matter how many times i try.

and it is a git hub repository i am 100% sure i also ran a command in git-bash someone suggested
![image](https://user-images.githubusercontent.com/22788269/140027143-e6ec3218-731f-453f-ad51-e5b6f32994d1.png)

i dont know what to do, since it worked flawlessly not so long ago but now doesnt want to open

**Comment by sergiou87** [comment]
Hello @KeyZHostHD! 👋 

Could you share the app logs? You can find them in `Help` -> `Show Logs in Explorer`

Thanks!

**Comment by ghost** [comment]
> Hello @KeyZHostHD! 👋
> 
> Could you share the app logs? You can find them in `Help` -> `Show Logs in Explorer`
> 
> Thanks!


[2021-11-03.desktop.production.log](https://github.com/desktop/desktop/files/7466443/2021-11-03.desktop.production.log)

**Comment by sergiou87** [comment]
Thanks @KeyZHostHD 

Looking at the logs, it seems like running `git status` in that repo is emitting an output of more than 19MB, which Desktop is not able to handle at this moment:
```
2021-11-03T05:14:09.013Z - error: [ui] 'git status' emitted 119289350 bytes, which is beyond the supported threshold of 20000000 bytes
```
My guess is there are many many many changes in that repository at the moment, is that true?

**Comment by ghost** [comment]
> Thanks @KeyZHostHD
> 
> Looking at the logs, it seems like running `git status` in that repo is emitting an output of more than 19MB, which Desktop is not able to handle at this moment:
> 
> ```
> 2021-11-03T05:14:09.013Z - error: [ui] 'git status' emitted 119289350 bytes, which is beyond the supported threshold of 20000000 bytes
> ```
> 
> My guess is there are many many many changes in that repository at the moment, is that true?

yes that is true, any way i can push it either way ?
i cannot tell you exactly, but it will be many thoushands of files added, not big each but its alot

**Comment by sergiou87** [comment]
You can… but not from Desktop 😞 

You must handle all those changes from somewhere else and then you can open it again from Desktop. However, this will happen again if you generate that many changes again!
