### ISSUE TITLE
Pull request review process in GitHub Desktop

### ISSUE THREAD

**Issue by StanimirS** [desktop/desktop#13262]
Currently there is not way for a person to review, comment or approve a pull request.

Adding this basic feature in GitHub Desktop will make it much more functional and would lessen the need to use the browser version. As things stand now it is annoying to have to open the desktop version AND the browser version in order to manage a repository.

**Comment by tidy-dev** [comment]
@StanimirS  Thank you for the feedback. We are tracking a [better PR experience here](https://github.com/desktop/desktop/issues/11517). Tho I think the focus right now is being able to start a PR in Desktop. I believe your feedback is inline with the discussion and I am going to close this issue and crosspost your feedback there.
