### ISSUE TITLE
I am failing to push my code

### ISSUE THREAD

**Issue by uwisergio12** [desktop/desktop#13269]
### Describe the feature or problem you’d like to solve

I am trying to push mu code but when I put my username and password, it doesn't work. 

### Proposed solution

Someone else may have the same issue and may get to know how to handle it.

### Additional context

Please include any other context, like screenshots or mockups, if applicable
![Github_Desktop](https://user-images.githubusercontent.com/93675546/140346928-34863b32-033a-450e-953d-223a5bc14658.PNG)
.

**Comment by steveward** [comment]
@uwisergio12 thanks for the issue. Are you trying to push to a GitHub repository? Can you verify that you are logged in when you go to `File` > `Options` > `Accounts`?

**Comment by Kiranoah** [comment]
> ### Describe the feature or problem you’d like to solve
> 
> I am trying to push mu code but when I put my username and password, it doesn't work. 
> 
> ### Proposed solution
> 
> Someone else may have the same issue and may get to know how to handle it.
> 
> ### Additional context
> 
> Please include any other context, like screenshots or mockups, if applicable
> ![Github_Desktop](https://user-images.githubusercontent.com/93675546/140346928-34863b32-033a-450e-953d-223a5bc14658.PNG)
> .
>gh pr checkout 2462
