### ISSUE TITLE
GIT:// repos not working behind corporate firewall

### ISSUE THREAD

**Issue by AirborneZA** [desktop/desktop#13264]
### Describe the bug
GIT:// repos not being cloned, HTTPS:// repos working fine, behind corporate firewall

### Version & OS

Version 2.9.4 - WIndows 10

### Steps to reproduce the behavior

1. Go to 'Clone repo'
2. Click on 'Enter URL'

### Expected behavior

Need GIT repos to function as HTTPS repos are

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

I've tried this on both LINUX and WIN computers behind the corporate firewall - neither works. Bypassing the firewall the GIT repo works but this is not an option.

**Comment by steveward** [comment]
@AirborneZA thanks for the issue. The `git://` protocol is not recommended -- it's read-only and unencrypted. It's also going to be [turned off](https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git) on GitHub. If you are having issues using SSH or HTTPS please let us know.
