### ISSUE TITLE
current branch

### ISSUE THREAD

**Issue by Manalitentworks** [desktop/desktop#13275]
![image](https://user-images.githubusercontent.com/84073762/140495652-9113b759-12b4-4e35-a1bf-3a235d66687b.png)

Current branch option in not available

**Comment by sergiou87** [comment]
Hi @Manalitentworks ! 👋 

Thank you for your report. Could you share the app logs from `Help` -> `Show Logs in Explorer`?

According to the app's logic, that `Current branch` option is not available when there is no repository selected, or the repository is either being cloned or missing in disk: https://github.com/desktop/desktop/blob/45d7b17832802a1bd09e8e2784a6effc0dd787f6/app/src/ui/app.tsx/#L2492-L2494

Are you able to reproduce this problem consistently? Any specific steps we can follow?
