### ISSUE TITLE
show minimal menu when rendering static error page

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#1327]
As part of #1198 we may display a browser window if the main window hasn't been launched.

https://github.com/desktop/desktop/blob/66d2b7abde4480711c89724b34de7d1cfee22555/app/src/main-process/error-page.ts#L52

We should ensure that a minimal menu is created and applied here - basically an `File -> Exit` menu item on Windows and a `GitHub Desktop -> Quit GitHub Desktop` on macOS.

**Comment by niik** [comment]
This was done in #1562. We don't render the menu on Windows but we do support the keyboard shortcuts to launch DevTools. I don't think an explicit `File->Exit` menu is necessary on Windows.
