### ISSUE TITLE
Shortcut to go at that place in file

### ISSUE THREAD

**Issue by anotte** [desktop/desktop#13288]
### Describe the feature or problem you’d like to solve

Shortcut to go at that place in file.

### Proposed solution

Add a button VS (or other editor) File At This Line (selected line)

### Additional context

Please include any other context, like screenshots or mockups, if applicable.

![image](https://user-images.githubusercontent.com/2053464/140748335-9c1c8ec2-56a0-4b1c-83b3-18c7f0e1afb0.png)

**Comment by niik** [comment]
Closing in favor of https://github.com/desktop/desktop/issues/14476
