### ISSUE TITLE
Authentication failed to push - git Desktop

### ISSUE THREAD

**Issue by Saranatarajan** [desktop/desktop#13292]
Hi team,

I couldnot pudh the code to repository.it says authentication failed.i tried creating new password,authenticatiing through browser.generating token and passing it as password still no luck.

![image](https://user-images.githubusercontent.com/69920659/140807774-b4b98f10-33da-418f-92cd-ef2fe00066e0.png)

email:snatarajan@mtrustcompany.com
Please help !

**Comment by sergiou87** [comment]
Hello @Saranatarajan 👋 

Did you follow the instructions from https://github.com/desktop/desktop/blob/development/docs/integrations/azure-devops.md to create the token?

Also from what I see, I think you're not in the latest version of GitHub Desktop. Shouldn't make a huge difference for this, but maybe it helps.

Could you also provide logs from `Help` -> `Show Logs from Explorer`? That could help us diagnose the issue 🤞
