### ISSUE TITLE
Pinned Repositories in app or taskbar icon (windows)

### ISSUE THREAD

**Issue by SeanKilleen** [desktop/desktop#13297]
### Describe the feature or problem you’d like to solve

I have a lot of repositories. Sometimes, like on a client project, it would be really helpful to be able to pin one or more, either within the app's repositories list, or on a right-click on the taskbar icon (for Windows). Similar to how Visual Studio has lists of recent projects and those can be pinned within the taskbar.

Redacted screenshot:

![image](https://user-images.githubusercontent.com/2148318/140934011-6df7c69f-37f6-4ab0-a7f2-de7a790eaa00.png)

_____

Side note: this is an idea that I had while using the app, which I just want to say is a phenomenal tool overall and clearly a labor of love. I absolutely enjoy using it every day.

**Comment by sergiou87** [comment]
Thank you for your suggestion and lovely feedback @SeanKilleen !!! ❤️ 

Right now we're tracking this feature request in #8183, and unfortunately currently isn't being worked on. However, we may revisit in the future so I'm going to link this issue. Feel free to add your comment or thumbs up to that issue as well if you want! 😄

**Comment by SeanKilleen** [comment]
Thanks! Sorry I'd missed the duplicate in my initial search.
