### ISSUE TITLE
MacOS ARM Build - Install command line tool ...

### ISSUE THREAD

**Issue by 0xtf** [desktop/desktop#13291]
Since I couldn't find any reference to this in the documentation I would like to confirm that, when using the ARM build of GitHub Desktop, the "Install command line tool ..." option will install an ARM build of git, and not a x86 (and subsequently Rosetta).

Thank you!

**Comment by steveward** [comment]
@0xtf thanks for the issue! The command line tool does not install Git -- it installs a helper tool that lets you launch GitHub Desktop directly from the command line by running `github /path/to/repository`. I hope that helps explain things.
