### ISSUE TITLE
Authentication failure when using system OpenSSH on windows 10

### ISSUE THREAD

**Issue by mateeni-dev** [desktop/desktop#13293]
### Describe the bug
I am getting an authentication failed error when fetching, or pushing to a remote Gitlab repository via ssh.
 
This only happens when I have the option `Use system OpenSSH (recommended)` enabled. 
Disabling this option fixes the issue for me on Windows 10.

I've tried the workaround of setting `sshCommand` as explained here #5641 

### Version & OS

Github Desktop: Version 2.9.4 (x64)
Windows 10: Version 21H1 (OS Build: 19043.1288)

### Steps to reproduce the behavior

1. Go to **File > Options > Advanced**
2. Enable `Use system OpenSSH (recommended)`
3. Fetch or push to a repository on Gitlab via ssh
4. See error pop-up

### Expected behavior

Be able to fetch, or push to a remote Gitlab repository via ssh, with option `Use system OpenSSH (recommended)` enabled.

### Actual behavior

Authentication failure error pop-up shows up when fetching or pushing to a remote Gitlab repository via ssh.

### Screenshots

https://imgur.com/oj2D2jp

### Logs

```
2021-11-09T01:02:01.110Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: <REDACTED> (has token)
2021-11-09T01:02:04.123Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.902s)
2021-11-09T01:02:04.123Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions for '<REDACTED>/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "<REDACTED>/id_rsa": bad permissions
git@gitlab.com: Permission denied (publickey,keyboard-interactive).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
```

**Comment by sergiou87** [comment]
Unless I'm missing something, there seems to be a problem with the permissions of your SSH key. You need to run `chmod 600 /path/to/your/key/id_rsa` and that should fix the problem.

I'm gonna assume that's the problem and close the issue. Please let me know if it didn't help and I'll reopen!
