### ISSUE TITLE
Cache under %APPDATA%

### ISSUE THREAD

**Issue by CanastraRF** [desktop/desktop#13308]
GitHub Desktop under Windows create and save lot of data under %APPDATA%\GitHub Desktop.
This is part of server sync profiles in enterprise environment.
Often this folder is size limited.
In often situation a user has a expensive small SSD for OS and APPs and e cheap big HDD for data.
So please save caches and temp data under %LOCALAPPDATA% or let the user select an folder for caches.

**Comment by steveward** [comment]
Thanks for the issue @CanastraRF -- this looks like the same request as https://github.com/desktop/desktop/issues/6523, so I'm going to close this issue out and add your feedback there.
