### ISSUE TITLE
Editor detect

### ISSUE THREAD

**Issue by CanastraRF** [desktop/desktop#13309]
Github Desktop for Windows support a limited count of editors and detect them in the registry under the HKLM\...\uninstall key.

I use normally VSCode portable. So nothing is set under HKLM\...\uninstall and Github Desktop does not detect my VSCode.
BTW: I've no admin credential the add something to HKLM\...\uninstall.
So please let the user select where an editor is installed.

**Comment by steveward** [comment]
Thanks for the feedback @CanastraRF -- I'm going to drop this into https://github.com/desktop/desktop/issues/7033 where we are tracking better editor integration support.
