### ISSUE TITLE
authentication failed

### ISSUE THREAD

**Issue by AbdulMughal** [desktop/desktop#13315]
Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.

I have logged out and log in again and authorized my desktop from the github page

**Comment by sergiou87** [comment]
Where is your repository hosted, @AbdulMughal ? Is it on GitHub, GitLab, Bitbucket, Azure…?

**Comment by AbdulMughal** [comment]
Got hub .
________________________________

**Comment by steveward** [comment]
@AbdulMughal Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by AbdulMughal** [comment]
logs attached


Best Regards

Abdul




Abdul Mughal

AWS Cloud Security Engineer
Signet Jewelers ​
***@***.******@***.***>
________________________________

**Comment by sergiou87** [comment]
I'm sorry @AbdulMughal but the logs didn't make it here because you replied via email, I'm afraid you must upload them from GitHub.com and not as an email attachment 😓

**Comment by AbdulMughal** [comment]
attached
[2021-11-12.desktop.production.log](https://github.com/desktop/desktop/files/7546974/2021-11-12.desktop.production.log)
g

**Comment by sergiou87** [comment]
@AbdulMughal thanks! I don't see any obvious reason for it to fail: I see how you log in & out, you have a token to access the repository… so I have a few questions:

1. Did you clone the repository from GitHub Desktop?
2. Are you able to run `git fetch` on that repository from a Git Bash terminal?
3. Are you running a firewall or antivirus on your machine that you could temporarily disable?
4. Have you tried accessing other private repositories from GitHub Desktop?

**Comment by AbdulMughal** [comment]
1. no , if try from git hub I get this error. 
2. 
![image](https://user-images.githubusercontent.com/83608060/142216502-c8e2bd52-8fd1-4ab5-94f8-efcfeb2dfa6f.png)
2. no not using git fetch
3. It can be but it would be a headache. 
4. No

**Comment by sergiou87** [comment]
That error from the screenshot can be avoided by just changing the local path in the textbox below (you can call it `security-control-tower-customizations-2`, for example). Please, try that to check if Desktop is at least able to clone your repository 🤞
