### ISSUE TITLE
Git remote branch

### ISSUE THREAD

**Issue by Murad-555** [desktop/desktop#13328]
Hello, I wanted to ask about a deleted branch, if I deleted a branch in Visual Studio, how can I recover files?

**Comment by steveward** [comment]
Thanks for the issue @Murad-555. This issue tracker is for GitHub Desktop -- are you having any specific issues there? 

If you deleted a local branch you can restore it from the command line. You will need to use the `git reflog` command to find the SHA of the branch you deleted. There should be a `Delete branch <branch_name>` in the reflog. Copy the SHA of that and you can then run `git checkout -b <branch> <sha>` to recreate the branch. I hope that helps!

**Comment by Murad-555** [comment]
Thank you very much, immensely grateful to you, I already thought that I would no longer be able to return all my projects (I accidentally threw the entire folder into the branch), I am a completely newbie :)))

**Comment by Murad-555** [comment]
I apologize for not answering for so long
