### ISSUE TITLE
Click area to select hunk on both sides of diff is wrong

### ISSUE THREAD

**Issue by jwbth** [desktop/desktop#13325]
### Describe the bug
In split diff display, the click area to select a hunk on both sides of a diff is wrong (limited to the left side).
 
### Version & OS

2.9.4 (x64), Windows 10.

### Steps to reproduce the behavior

1. Make a change to some file in a repository.
2. Select it in the Changes tab.
3. Make sure you have "Split" diff display selected in the settings under the gear icon in the top right corner.
4. Hover over the area between the line numbers of the changed lines.

### Expected behavior

The click area is stretched from the left to the right side of the center area.

### Actual behavior

The click area is limited to the *left* side of the center area.

### Screenshots

To select a hunk on both sides of a diff, I can perform a click right in the center of the diff: 
![image](https://user-images.githubusercontent.com/33615628/141784875-680a17ac-399d-4202-a833-0fd971a762e1.png)

In practice, however, the click area is limited to a small space between the line numbers on the left and the center:
![image](https://user-images.githubusercontent.com/33615628/141785934-20e7b45e-497b-43a7-a604-93d3ac313aab.png)

### Additional context

The reason for this bug is that the click area (the `.hunk-handle` element), while being positioned correctly, is obstructed by the `.after` element. A possible solution is to set a `z-index` to the `.hunk-handle` element or move it after the `.after` element.
![image](https://user-images.githubusercontent.com/33615628/141787388-70d1194e-6757-4ec8-861b-a0917233b975.png)

**Comment by choochatJumpathong** [comment]
Excellent and the best this one i believe that
