### ISSUE TITLE
Cherry-picking without switching branches (or at least remembering where I was)

### ISSUE THREAD

**Issue by andreasabel** [desktop/desktop#13336]
I am on a repo with 20.000 commits on `master`.  I branched off `release` around 300 commits back from `master HEAD`.  Now I want to go through these 300 last commits and cherry-pick say half of them to the `release` branch.

My first attempt was by switching to `release`, viewing the 300 commits in the "Compare to `master`" view and tried to drag a commit from there onto `release`.  This did not work, but I think this is already reported as #12688.

So I switched to `master`, located the branching point by scrolling back, grabbed 5 commits and cherry-picked them onto `release`.
However, this had the unwanted side effect to switching to the `release` branch.  I rather wanted to continue cherry-picking from `master`.

Ok, so I switched again to `master`.  But then I my position was lost, I am not in the place where I grabbed the 5 commits.  Instead, I have to scroll back 300 commits again, make sure I am at the right point, look for the next commit to pick, and repeat the whole game.
Feels like this will be very tiring without need.

Intuitively, when I stumbled over the ad https://github.blog/2021-03-30-github-desktop-now-supports-cherry-picking/ , I expected a tool that could give me a productivity boost and make my life easy.  The current design seems to aim at users that want to pick just one commit or one sequence.  For my purposes, a tool would have to look as follows (and this is what I intuitively expected from a GUI for cherry-picking):
You have two columns, one for the source branch and one for the target branch.  Then you simply drag entries from column 1 to column 2.  Besides the 2 columns there is a space where I see the content of the commit I have just selected. That's it.  (No branch switching, scrolling all the time to find the point where I was at etc.)

**Comment by andreasabel** [comment]
I managed to cherry-pick 140 commits (https://github.com/agda/agda/pull/5654) via `gitk`:
1. check out target branch
2. run `gitk` from the repo root with the checked-out target branch
3. create a view of the source branch
4. to cherry-pick a commit from the source branch, right click on the commit title and select "Cherry-pick" from the context menu (https://gitolite.com/gitk.html)

This is a UI that could be taken as an example on how to do cherry-picking.  The only flaw in the ointment with `gitk` is that I cannot select a range of commits.  I can only pick single commits there.  This aspect is better in GitHub Desktop.

**Comment by tidy-dev** [comment]
Hi @andreasabel! Thank you for the feedback. We have had one [similar issue](https://github.com/desktop/desktop/issues/13031) reported.  Feel free to add your feedback there. Currently, we do not believe this is a widespread enough use case to warrant adding. But, if we get enough feedback otherwise, we may revisit in the future.

**Comment by andreasabel** [comment]
See also palindrome issue #13031.
