### ISSUE TITLE
Linux version ?

### ISSUE THREAD

**Issue by Watynecc** [desktop/desktop#13334]
### Describe the feature or problem you’d like to solve
Why we don't get a Linux release even it's a Eletron app ?

### Proposed solution
Release a Linux one ?

Please share how this will it benefit Desktop and it's users ?
I think many Developer use Linux mainly instaid of Using windows

**Comment by steveward** [comment]
Thanks for the issue @Watynecc. At this time there are no official builds of GitHub Desktop available for Linux, but a former developer of GitHub Desktop maintains a fork with Linux builds available for download:

https://github.com/shiftkey/desktop/releases

You can also follow along with https://github.com/desktop/desktop/issues/1525 for updates about an official Linux release.

**Comment by Hanro50** [comment]
Perhaps just linking to the fork where one can get the Linux version in the main readme could alleviate some of the confusion/demand?

At least till an official Linux build is actually available or the patches from the current Linux orientated fork are merged into the main repository.
