### ISSUE TITLE
unable to access received http code 407 github desktop

### ISSUE THREAD

**Issue by rashidbilgrami** [desktop/desktop#13330]
When i tried to clone an application it's throwing an error "unable to access received http code 407 github desktop". We are using proxy in our office. I am using windows 7 64 bit with 2.9.4 version of GitHub 
![Untitled](https://user-images.githubusercontent.com/1667625/141931797-8af2486f-f75a-4a4d-9651-c6004f99ea03.gif)

**Comment by niik** [comment]
Hey @rashidbilgrami, thanks for reaching out! It looks like you're using an authenticated proxy. GitHub Desktop can auto-configure non-authenticated proxies but requires a bit of help with authenticating proxies. You will need to manually configure the proxy url, username, and password by setting the [`http.proxy` configuration variable](https://git-scm.com/docs/git-config#Documentation/git-config.txt-httpproxy).

Something along the lines of:

```
git config --global http.proxy http://username:password@proxy.server.com:port
```

The username, password, server and port number are details you'll need to get from someone who manages your office network.

Best of luck!
