### ISSUE TITLE
Unable to authenticate when trying to use repo which is not pulled with Github Desktop app

### ISSUE THREAD

**Issue by jaggaer-npasic** [desktop/desktop#13339]
### Describe the bug
When trying to fetch from a remote repo, an authentication failed error window is shown.
Note: I'm actually able to manipulate with my remote repo with no problem either through CLI or Intellij or whatever I want. But when using the GitHub desktop app, I'm unable to do so.
Interesting thing is that If I pull the repo directly from Git, I'm able to work with it. But If the repo is already on my PC, I can't add it as a local repo and work with it. Push is not working, fetch also... 

### Version & OS
OS: Windows 10
GHD: Version 2.9.4 (x64)

### Steps to reproduce the behavior
1. File -> Add local repo
2. Select repo and click on Add repository
3. Select added repo and click on "Fetch origin"
4. Error modal is being displayed
![image](https://user-images.githubusercontent.com/70564484/142394099-2ff9e7d7-3609-4b08-a314-f680a1ba22c1.png)

### Expected behavior

I should be able to fetch from a remote repository.

### Actual behavior
An error occurred.

### Logs

```
2021-11-18T09:41:16.583Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.399s)
2021-11-18T09:41:16.584Z - error: [ui] git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin exited with an unexpected code: 128.
stderr:
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

### Additional context

I'm able to manipulate with remote repo through CLI, Intellij, or any other tool.
It seems like the app is not capable to import the project properly if it's not cloned with this app.

**Comment by sergiou87** [comment]
If I'm not wrong, that repository was cloned via SSH, right? You can try to toggle this setting and see if it makes a difference:
![2021-11-18 at 11 09](https://user-images.githubusercontent.com/1083228/142395362-6a16fc19-c29f-4d2a-82ac-672141bce6c0.png)

**Comment by jaggaer-npasic** [comment]
Hi @sergiou87, yes, this repo is cloned via SSH.
I already have this enabled
![image](https://user-images.githubusercontent.com/70564484/142401052-2078adf0-d9ab-40d1-8722-bb993fd2dc3d.png)

**Comment by sergiou87** [comment]
@jaggaer-npasic does it work if you disable it?

**Comment by jaggaer-npasic** [comment]
Hmm... strange, this time works.
The last time didn't.
I did uninstall and everything from scratch. Seems like it helped... 👍 
Thank you.
