### ISSUE TITLE
Fetching should be an option when working with unpublished branches

### ISSUE THREAD

**Issue by tzakharko** [desktop/desktop#13340]
### Describe the feature or problem you’d like to solve

The fetch/publish/push button in the UI changes depending on the context. One consequence is that it not possible to fetch when working with an unpublished branch (or if the branch has changes that have not been pushed). Sometimes however one does not want to publish a private branch. The current workaround for updating it is to change to the main branch, fetch/update from there, then change back and update from main. This is  cumbersome. 

### Proposed solution

There should be a fetch menu option (e.g. under Repository) and maybe permanently visible fetch tool on the toolbar. This would allow the user to fetch the data on other branches without having to first push their current branch.  

### Additional thoughts

Related to this: would be nice if the UI on updating branches from main was a bit more clear. Right now there is no clear way of seeing how many commits the branch is behind the main. I believe an earlier version of GitHub desktop had this functionality, but it seems to have been removed?

**Comment by steveward** [comment]
@tzakharko thanks for the issue. I'm going to add your feedback into https://github.com/desktop/desktop/issues/10444, which is a similar open issue.

>Right now there is no clear way of seeing how many commits the branch is behind the main. I believe an earlier version of GitHub desktop had this functionality, but it seems to have been removed?

You're likely thinking of the comparison view  (`Branch` > `Compare to Branch`) -- that shows the ahead/behind count.

**Comment by tzakharko** [comment]
Thank you @steveward, this is great!

> You're likely thinking of the comparison view (`Branch` > `Compare to Branch`) -- that shows the ahead/behind count.

True, but it would be great if this information were available unprompted, as it is universally useful. In our specific use case for example, users are not expert programmers (we are using git to coordinate transcription of language data), and they sometimes forget to check the main branch for changes. If there was a little message like "x commits behind the  main branch" somewhere near the branch UI on the main window it would be a great usability improvement. 

If you think it will be helpful, I would be happy to open a new issue with more background, usability motivation as well as a little mockup.
