### ISSUE TITLE
Hooks and lfs folder in root project directory

### ISSUE THREAD

**Issue by bigzaiko** [desktop/desktop#13342]
### Describe the bug
After push changes to server and then update from master from another branch, hook and lfs files will be shown (see attachment).
It happens sometimes and it is not clearly reproducable.

### Version & OS

Github version: 2.9.4
Windows 10 build: 19043.1348

### Steps to reproduce the behavior

1. Push changes to server
2. Update from master (from another branch)
3. Make changes on your project
4. Github shows hook and lfs files

### Expected behavior

Hook and lfs files shouldn't be shown in project root folder just in .git folder

### Screenshots

<img width="389" alt="gitfiles" src="https://user-images.githubusercontent.com/11092507/142420227-bd4a7789-0237-4ae1-bfe9-5bdc962b386d.png">

**Comment by steveward** [comment]
@bigzaiko thanks for the report. What changes are being shown in those files? It'd be helpful if we could get the exact output that `git diff` shows from the command line for one of the LFS pointer files and one of the hook files. My guess is that this is a line-endings or file mode issue. If you could go to `Repository` > `Open in <comamnd_line>` and run `git diff \path\to\file` and share the output for a few of those files that would be helpful.

**Comment by headsphere** [comment]
I noticed this exact same issue this week. I found this issue #3898 which also appears to be the same problem. I upgraded my LFS version to 3.0.2 and the issue seems to have gone away. In case this helps anyone...
