### ISSUE TITLE
EOL on repo creating or on commit

### ISSUE THREAD

**Issue by b5414** [desktop/desktop#13341]
### Describe the feature or problem you’d like to solve

I would like to lock `eol` for all files, for example to `crlf` 🙂

### Proposed solution

It would be convenient if a selector with `[crlf, lf, auto, input]` was added in the app settings

### Additional context

I would like to be able to change the default `.gitattributes` file (too?), when I create a new repository;
Or not create it at all, with `Git ignore` - `node` (app > create repo)

`git config --global core.autocrlf true` does not propagate to github app

Also, the change in eol of files is not committed when I send them via the app - they are simply deleted, and I see the eol change through the vscode  
// Let me know if I should create a new bug issue that describes this, Or can you handle it yourself?

**Comment by steveward** [comment]
@b5414 thanks for the issue. Line-endings are definitely an area of Git that can cause headaches, but at this time we don't have any plans of implementing various configuration options for them directly in GitHub Desktop. This has been discussed in the past (https://github.com/desktop/desktop/issues/1964 and https://github.com/desktop/desktop/issues/2850), but isn't on our roadmap at this time. Generally the best method for handling line-endings is to create a `.gitattributes` file with `* text = auto` (what GitHub Desktop does by default when creating a new repo), as that allows line-endings to be consistent across various OS platforms and not rely on `core.autocrlf`. GitHub has a [best-practices guide](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings) that is recommended reading.

>git config --global core.autocrlf true does not propagate to github app

GitHub Desktop should respect the `core.autocrlf` setting in your .gitconfig, unless it is being superseded by the local `.git/config` or the `.gitattributes` file.

>Also, the change in eol of files is not committed when I send them via the app - they are simply deleted, and I see the eol

It sounds like you may be running into https://github.com/desktop/desktop/issues/3034. 

I hope that helps. Let me know if you have further questions.
