### ISSUE TITLE
Window for github Desktop is larger than screen on my, cannot reach 

### ISSUE THREAD

**Issue by grishkam** [desktop/desktop#13345]
### Describe the bug
Write a clear and concise description of what the bug is.
Window for github Desktop is larger than screen on my, cannot see/reach the edges of it
### Version & OS
Version 2.9.4 (x64). I am using windows 10.

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Open github desktop
2. minimize the window by clicking -
3. click on the icon at the bottom of screen to make the window re appear
4. The window reappears but is large

### Expected behavior
I expect the window to fit the screen. It would also help if I could move or resize it but that does not work.

### Actual behavior
Window is large than screen and cannot be resized

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by sergiou87** [comment]
I cannot reproduce this behavior 😞 

Is the window maximized before you minimize it?

A trick you can use to at least recover from that state is pressing <kbd>Windows</kbd>+<kbd>Up</kbd> once or twice to maximize it, or <kbd>Windows</kbd>+<kbd>Left/Right</kbd> to dock it to either sides of your screen.

**Comment by WilliamJons** [comment]
I am experiencing a similar issue where I can't see the commit button. @sergiou87, is there an option to get some help with this or re-open the issue?

![image](https://user-images.githubusercontent.com/72273078/182920410-607f02f3-dde4-4217-9b14-adb8d13a72a6.png)

**Comment by sergiou87** [comment]
@WilliamJons could you try the latest beta from https://desktop.github.com/beta and tell me if it fixes the issue? We believe it was a problem in Electron that was solved in a more recent version.

**Comment by shamasaifee22** [comment]
![Screenshot 2024-11-07 104807](https://github.com/user-attachments/assets/2a46ef31-6534-4d8f-bc2f-01f571610c35)

I am unable to minimize or drag the window.

**Comment by VinciusAndrade** [comment]
just press f11 people
