### ISSUE TITLE
Npm Run Build error

### ISSUE THREAD

**Issue by SosaTheHustler** [desktop/desktop#13358]
I'm trying to push my react application to github pages and I'm currently getting this error everytime I try.

warning: ignoring broken ref refs/heads/gh-pages
fatal: cannot lock ref 'refs/heads/gh-pages': unable to resolve reference 'refs/heads/gh-pages': reference broken
A       asset-manifest.json
A       favicon.ico
A       index.html
A       logo192.png
A       logo512.png
A       manifest.json
A       robots.txt

I've looked up everything and nothing works... any help would be great

**Comment by steveward** [comment]
Thanks for the report. Are you having any specific issues with GitHub Desktop? Normally a `reference broken` error indicates local repository corruption. If you run `git fsck` in the repository from the command line it should give some more information about the root cause of the error.

**Comment by NamanSnag** [comment]
I am also receiving 
-> fatal: cannot lock ref 'HEAD': unable to resolve reference 'refs/heads/main': reference broken
after running git fsck
-> Checking object directories: 100% (256/256), done.
error: refs/heads/main: invalid sha1 pointer 0000000000000000000000000000000000000000
error: refs/remotes/origin/main: invalid sha1 pointer 0000000000000000000000000000000000000000
error: invalid HEAD
error: bad ref for .git/logs/HEAD
error: bad ref for .git/logs/refs/heads/main
error: bad ref for .git/logs/refs/remotes/origin/main
notice: No default references
dangling commit 7c84b779143352cbfff71a08f5ea1816341560f8
dangling commit b7c0c813e5614838a4b0bfc389945e5067eb586e
dangling commit c14ac4da7c5a42a653c1315fdad2c758a55d466b
Can anyone help me for that ?

**Comment by swadebsharma6** [comment]
I am also reciving.....What can i do Next...
Checking object directories: 100% (256/256), done.
error: refs/heads/main: invalid sha1 pointer 0000000000000000000000000000000000000000
error: refs/remotes/origin/main: invalid sha1 pointer 0000000000000000000000000000000000000000
error: invalid HEAD
error: bad ref for .git/logs/HEAD
error: bad ref for .git/logs/refs/heads/main
error: bad ref for .git/logs/refs/remotes/origin/main
notice: No default references
dangling commit 0916ddbdb844ad4737b6a71b0d6242981f4f2bf8
dangling commit 4c466e37eabc296d47fba8e10b4f1c68928feeee
dangling commit c6b086781ce253c13e2c90ee5a972d6e434807d5
dangling commit e37e9e080c12cf301189cb09edbff0d6ff23fb3a
dangling commit faf6f1a7a3190f135bf8fb145468c1bcc375ae52
dangling commit 0839210c3f0f553850b0aa1e489e77a2a60be585
dangling commit 3175b09b45e662b2974e5dd7b9e82e6c4a85f5ef
dangling commit 3d035b2d34266604be305508c80b622f7eef70db
dangling commit b39b16469f76609e57b0de7200848c9d78b0e088
dangling commit d2f52e4c59a31d509ad75722aab032fd63b3e2d2
dangling commit e9d9b8fdb356da50673a5c91e9aaaf985ec0c89f

**Comment by steveward** [comment]
@swadebsharma6 that looks like repository corruption, unfortunately. A fresh clone of the repository would be the quickest way to resolve it.
