### ISSUE TITLE
github desktop is not able to select a repository

### ISSUE THREAD

**Issue by Inderjeetkaur747** [desktop/desktop#13350]
Cloning into 'C:\Users\inder\OneDrive\Documents\GitHub\Minor-Project.github.io'...
git: 'remote-https' is not a git command. See 'git --help'.

**Comment by steveward** [comment]
Thanks for the report @Inderjeetkaur747. Are you running any antivirus or other security software that could be interfering with GitHub Desktop? If so, try temporarily disabling it to see if that gets things working.

If that does not work it would be helpful if you could upload a log file from GitHub Desktop. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
