### ISSUE TITLE
IDENTITY THEFT 

### ISSUE THREAD

**Issue by PHEON1XENT** [desktop/desktop#13355]
### Describe Issue 

IOS users are able to see and use different apps that Android users are unavailable to access leaving Android users unable to see iOS users on the web iOS users become then invisible hackers to Android users and are able to utilize the same apps that the Android users would be using without having any detection of them at all.

### Proposed solution

I think that if we were able to merge both of the servers together you be able to see iOS users as clearly as Android users and then also have Biometrics as well as facial recognition be used to verify a person the Biometrics every person needs to have their fingerprints verify because iOS users are able to use facial recognition and can take a picture and open up your your screen with just a facial recognition if you make it so that everybody has to use fingerprint verification to fix the identity theft epidemic 

### Additional context

Please include any other context, like screenshots or mockups, if applicable.

**Comment by niik** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
