### ISSUE TITLE
Tracking issue

### ISSUE THREAD

**Issue by omidMolaverdi** [desktop/desktop#13353]
### Describe the bug
The issue is that when I click on the files (second column in the window from left), the highlight for the commits in the commit column disappears and I need to keep memorizing where I was before. 
### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Open the client
2. click on one commit
3. from the second column that shows the files that have changes select any
4.  Now the highlight (for me in blue) for the commit that you selected disappears

### Expected behavior

I expect to commit keep highlighted

### Screenshots

![image](https://user-images.githubusercontent.com/66969636/142728666-7a0cbeac-7e9c-4a11-9b8a-3dbd827e8980.png)
### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by felipedrumond** [comment]
I'm also having trouble using Git Desktop, specially when I have many changes and want to self review my code. I get lost all the time and the only way to know where I am is looking at the file name in the right-hand side and search for it on the left-hand side.

**Comment by Charlie-Brownie** [comment]
On Windows 10 with dark theme enabled there is a color difference when selecting individual files.
![image](https://user-images.githubusercontent.com/11286791/142777753-9124c847-40e5-4f13-98b5-756fc7a6f484.png)
![image](https://user-images.githubusercontent.com/11286791/142777756-545dd402-e3a8-4832-b129-67f6a07b7ff5.png)

**Comment by Charlie-Brownie** [comment]
This issue has been addressed here #13115. Just gotta wait for it to make it to production :)

**Comment by steveward** [comment]
Thanks for the issue @omidMolaverdi. Like @Charlie-Brownie mentioned the fix for this will soon be out in production. You can grab the [beta](https://github.com/desktop/desktop#beta-channel) if you would like to get it now.
