### ISSUE TITLE
Visualize branches like git log --graph --all does.

### ISSUE THREAD

**Issue by SkybuckFlying** [desktop/desktop#13365]
### Describe the feature or problem you’d like to solve

The most fun and interesting part about GIT for me are definetly the branches and then lines/connections draw between them as can be seen in git log --graph --all.

Right now this information is completely lost in github desktop, it looks messy, somewhat confusing, and way too much like windows explorer which is very old technology to store data/files, while I can understand people used to that, it is not the future of storage/versioning technology, git branches/visual lines is what should be the future, much clearer how branches related to each other and in time. 

### Proposed solution

Add visuals lines between branches, especially from commit to commit that are on the same branch.

### Additional context

See second comment

**Comment by SkybuckFlying** [comment]
![Misleading branch view](https://user-images.githubusercontent.com/34254801/142931941-ce68f128-2a99-4f1c-95fe-825efcaaebc0.png)

This view while maybe nice for noobies, gives a very misleading view of how branches work in git as far as I can tell, it is also somewhat hard to tell what are the dates of these commits ? now that I look at it again I see 5d and then some dates and yet indeed they are not sorted by date, not that it should cause that is not how git works.

The left most plane is missing lines to connect the commits.

**Comment by steveward** [comment]
Thanks for the issue @SkybuckFlying, this is being tracked in https://github.com/desktop/desktop/issues/9452. I'd recommend following along there for any updates.

**Comment by ddublon** [comment]
Hi there are any updates about that?

**Comment by ddublon** [comment]
I want to see tree like it look on intellij products 

![image](https://github.com/desktop/desktop/assets/127298010/44e6f49a-a645-4cc0-af1c-22727c69ab19)

**Comment by godstime147** [comment]
May /20/2022
June /8/20022

**Comment by ddublon** [comment]
what do those dates mean?

**Comment by Duna** [comment]
Still do not see the graph tree :( task is closed for no reason

**Comment by mgstauffer** [comment]
Please?

**Comment by alicebalayan** [comment]
if we ask nicely...pretty please? 

But for now, this extension works: https://chromewebstore.google.com/detail/le-git-graph-commits-grap/joggkdfebigddmaagckekihhfncdobff

**Comment by mhd-fettah** [comment]
is there other way ?? 
I newly migrated from jetBrains to VsCode 
lots of features missing . 

this one did not thought how important and nice it is . till we miss it

**Comment by FluffyProgramming** [comment]
If you connect you VSCode to your GitHub you can get the graph view in the IDE. I wish I could get it in GitHub Desktop but I basically do my git actions exclusively from VSCode.

![Image](https://github.com/user-attachments/assets/5f2973f2-2cda-4658-acaa-b50b7e35a541)

**Comment by dkchshv** [comment]
@FluffyProgramming check out that fork: [https://github.com/pol-rivero/github-desktop-plus](https://github.com/pol-rivero/github-desktop-plus)
