### ISSUE TITLE
Editor/Source View is not updated when using arrows keys.

### ISSUE THREAD

**Issue by SkybuckFlying** [desktop/desktop#13366]
### Describe the feature or problem you’d like to solve

Using the arrow keys to move through changed files is very interesting. However when it's done very fast it does not update the SourceView.

While I can understand that this might prevent crashes because of too fast changing graphics and also allow quicker navigation through the files, the idea of quickly getting some sense of the code contents would be very usefull.

Another issue is that pressing up or down repeatedly can hurt the arm mussles and lead to RSI, repetitive strain injury, this is not a joke.

Plus wear and tear on arrow keys could become a real phenomenon on long term usage. 

For that reason reduce the strain on arrow keys and fingers/arm mussles to reduce interaction with keyboard and mouse clicks to an absolute minimum.

### Proposed solution

Do try and visualize the source view, perhaps build in an option how it should behave if arrows are used for example:

1. Allow fast navigation through files without updating source view
2. Force source view update and wait for update/load.

Another possiblity is to slow it down slightly and try updating it or allow the user to decide the speed at which the arrow keys navigation throught he files.

3. Arrow keys navigation speed: 10 items per second.
where 10 can be changed to any other value.
4. And perhaps a checkbox: "wait for file to load before continueing".
The file doesn't need to be loaded totally just the first part to give an impression of what is in the file or perhaps the first changed part.

5. the software could also introduce a "timeout" value in case the harddisk loading is too slow then skip over file, option example:
skip file if loading takes longer than 300 microseconds.

Where 300 can be changed to any integer value within 31 bit limitation.

### Additional context

This feature is very interesting have not seen it before in any other software.

This could make github desktop much more populair if implemented correctly as described above.

**Comment by steveward** [comment]
@SkybuckFlying thanks for the feedback. The diff view can take some time to load depending on file size, and showing better messaging around that is being tracked in https://github.com/desktop/desktop/issues/1913. We do have diff size limits in place as well. At this time we don't have any plans to make any changes with the diff view, so I am going to close this out for the time being. Thanks for letting us know you'd like to see this improved.
