### ISSUE TITLE
Fatal error setting up desktop-tutorial

### ISSUE THREAD

**Issue by spinphysgit** [desktop/desktop#13361]
### Describe the bug
New to github. On 'Let's get started' page of github desktop. Clicked 'Create a tutorial repository...' and got the message in the attached image. i.e. "Error fatal: bad config line 1 in file .git/config"

### Version & OS
Windows 10
Github version 2.9.4 (x64)

### Steps to reproduce the behavior
Explained above

### Expected behavior

Create a tutorial repository without error

### Actual behavior

Above described error. But the repository seems to have been created

### Screenshots

Attached

### Additional context

Add any other context about the problem here
[2021-11-22.desktop.production.log](https://github.com/desktop/desktop/files/7581441/2021-11-22.desktop.production.log)
![Screenshot 2021-11-22 132533](https://user-images.githubusercontent.com/94842919/142869438-414ce726-086c-4863-80b8-a8b6a175a9df.png)
.

**Comment by steveward** [comment]
@spinphysgit thanks for the report. This error indicates an issue with your local config file, which can be found at`.git/config` within your repository. You'll need to enable viewing hidden files/folders to access the `.git` directory. If you can open that file and share the contents that should let us know what the issue is with the first line.

**Comment by spinphysgit** [comment]
Hi Steve
Thanks for you reply. May I ask (not knowing how github works) do you work for github? My post seemed as if it was public (I could see others posts!); is that correct?
Here is mthe contents of my config file

[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true


Thanks

**Comment by steveward** [comment]
@spinphysgit this is a public issue tracker so it is visible to other users. Are you still having issues working with GitHub Desktop?

**Comment by spinphysgit** [comment]
Yes. I do still have the problem

**Comment by manjitsinghrai9** [comment]
Someone hacked my all social media account and my And my home Internet IP address and my iCloud’s IP address my device I am in and the IP address creator helping people there’s a helping websites on the Wikipedia so whatever’s third-party websites using after my use all data so please help mepersonal information or personal data on my all Gmail account Samsung account Google Drive data Apple iCloud iPhone you are number all other social media all account and my domain name my service Canada account my face ID everything scammer you can help me my banking information my credit debit all other information so I want to hug you can help me put it to me pleaseAll my URL number on my domain name of my all service Canada account my all social media accounts without my permission my tax regarding all information you can help me protect me

**Comment by manjitsinghrai9** [comment]
Someone hacked my all social media account and my And my home Internet IP address and my iCloud’s IP address my device I am in and the IP address creator helping people there’s a helping websites on the Wikipedia so whatever’s third-party websites using after my use all data so please help mepersonal information or personal data on my all Gmail account Samsung account Google Drive data Apple iCloud iPhone you are number all other social media all account and my domain name my service Canada account my face ID everything scammer you can help me my banking information my credit debit all other information so I want to hug you can help me put it to me pleaseAll my URL number on my domain name of my all service Canada account my all social media accounts without my permission my tax regarding all information you can help me protect me

**Comment by manjitsinghrai9** [comment]
Someone hacked my all social media account and my And my home Internet IP address and my iCloud’s IP address my device I am in and the IP address creator helping people there’s a helping websites on the Wikipedia so whatever’s third-party websites using after my use all data so please help mepersonal information or personal data on my all Gmail account Samsung account Google Drive data Apple iCloud iPhone you are number all other social media all account and my domain name my service Canada account my face ID everything scammer you can help me my banking information my credit debit all other information so I want to hug you can help me put it to me pleaseAll my URL number on my domain name of my all service Canada account my all social media accounts without my permission my tax regarding all information you can help me protect me

**Comment by steveward** [comment]
@spinphysgit have you been able to resolve this? Let me know if you're still having issues.

**Comment by lamppost0** [comment]
i have the same problem, can someone help me with this please?

**Comment by spinphysgit** [comment]
I think it relates to trying to clone to a network drive. Seems to be fine if I use C:

**Comment by lamppost0** [comment]
> I think it relates to trying to clone to a network drive. Seems to be fine if I use C:

i deleted the config file and it created a new one without the error and it works now
