### ISSUE TITLE
Problem with pushing existing local repository.

### ISSUE THREAD

**Issue by SkybuckFlying** [desktop/desktop#13367]
### Describe the feature or problem you’d like to solve

Desktop tried to update .gitnore for *.rsm file also noticed LF and CRLF

Push fails.

Strange thing is, if I clone repository with github and then push another change it does work.

### Proposed solution

no idea, must be debugged.

### Additional context

Try creating github repositories manually without github desktop/clone try and import.

I had a feeling something like this might happen, that's why I made backups first.

Now had to make another clone, might be worth it but it's strange.

There is one *.rsm to be excluded maybe this somehow trips up the push... strange stuff...

login,cloning seems to work fine and pushing too on new cloned repository, why can't it work on older one ?

**Comment by steveward** [comment]
Thanks for the report @SkybuckFlying. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by SkybuckFlying** [comment]
I have begun to start diagnosing the problem. I think I am getting close.

I suspect the problem might be with the following.

The cloned github repository has remotes set up as follows:

git-bash:
new@new-PC MINGW64 /e/SourceCode/PascalCoinGit/PascalCoin (PascalCoinMaster)
$ git remote -v
origin  https://github.com/SkybuckFlying/PascalCoin.git (fetch)
origin  https://github.com/SkybuckFlying/PascalCoin.git (push)
upstream        https://github.com/PascalCoinDev/PascalCoin.git (fetch)
upstream        https://github.com/PascalCoinDev/PascalCoin.git (push)

While my original repository is setup as follows:
switching to git-cmd: for easier switching to long filefolder names:
E:\SourceCode\PascalCoinGit(old apperently damaged somehow github desktop dont work with it)\PascalCoin>git remote -v
PascalCoin      https://github.com/PascalCoin/PascalCoin (fetch)
PascalCoin      https://github.com/PascalCoin/PascalCoin (push)
PascalCoinDev   https://github.com/PascalCoinDev/PascalCoin (fetch)
PascalCoinDev   https://github.com/PascalCoinDev/PascalCoin (push)
kapytanhook     https://github.com/kapytanhook/PascalCoin (fetch)
kapytanhook     https://github.com/kapytanhook/PascalCoin (push)
origin  https://github.com/SkybuckFlying/PascalCoin (fetch)
origin  https://github.com/SkybuckFlying/PascalCoin (push)
upstream        https://github.com/PascalCoinDev/PascalCoin.git (fetch)
upstream        https://github.com/PascalCoinDev/PascalCoin.git (push)

Perhaps this has something to do with it.

I will try and add these remotes to see if the problem returns.

**Comment by SkybuckFlying** [comment]
First I will also try and find/upload the log as requested that might shorten the hunt for the source of this issue, thanks for help !

**Comment by SkybuckFlying** [comment]
I renamed old log, so it produces a new log, I don't think it's helpfull at finding the problem:

2021-11-22T21:40:11.074Z - info: [ui] [AppStore] loading 2 repositories from store
2021-11-22T21:40:11.076Z - info: [ui] [AppStore] found account: SkybuckFlying (Skybuck Flying)
2021-11-22T21:40:11.102Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-11-22T21:40:11.418Z - info: [ui] launching: 2.9.4 (Windows 6.1.7601)
2021-11-22T21:40:11.420Z - info: [ui] execPath: 'C:\Users\new\AppData\Local\GitHubDesktop\app-2.9.4\GitHubDesktop.exe'
2021-11-22T21:40:13.894Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: PascalCoin - SkybuckFlying (has token)
2021-11-22T21:40:20.210Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.280s)

I will attach the entire old log as wel
[old 2021-11-22.desktop.production.log](https://github.com/desktop/desktop/files/7584553/old.2021-11-22.desktop.production.log)
l

**Comment by SkybuckFlying** [comment]
Tried it one more time, removed repository first, then restarted desktop,

Added it again, tried to do a push, failed to do it this is the log:

2021-11-22T21:42:38.735Z - info: [ui] [AppStore] loading 1 repositories from store
2021-11-22T21:42:38.737Z - info: [ui] [AppStore] found account: SkybuckFlying (Skybuck Flying)
2021-11-22T21:42:38.761Z - info: [ui] [BranchPruner] Last prune took place in 20 hours - skipping
2021-11-22T21:42:39.227Z - info: [ui] launching: 2.9.4 (Windows 6.1.7601)
2021-11-22T21:42:39.227Z - info: [ui] execPath: 'C:\Users\new\AppData\Local\GitHubDesktop\app-2.9.4\GitHubDesktop.exe'
2021-11-22T21:42:39.723Z - info: [ui] Current tutorial step is now AllDone
2021-11-22T21:42:50.150Z - info: [ui] [AppStore] adding repository at E:\SourceCode\PascalCoinGit(old apperently damaged somehow github desktop dont work with it)\PascalCoin to store
2021-11-22T21:42:50.674Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-11-22T21:42:52.615Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: PascalCoin - SkybuckFlying (has token)

This is not helping much, it was a nice try, I will continue with setting the remotes to see if that reproduces the problem.

**Comment by SkybuckFlying** [comment]
I have better idea, I will first add an upstream remote, maybe that will fix it.
OH github desktop already added an upstream to it, 
I still believe desktop github might be getting confused because of additional remotes,
also there is no more master branch that was pruned yesterday, it was renamed, maybe pruning damaged this repository.

I will copy this one and then remove the remotes to see if that will make it work again.

**Comment by SkybuckFlying** [comment]
Removing the additional remotes fixes part of the problem. At least github desktop is now capable of fetching.

However it might be having issue with the missing of a master branch as it's used too..

It's trying to re-upload PascalCoinMaster claiming that it's not present on the remote, while I know it is.

So this may be some bug.

But I will try and fix it by removing some commits, though I believe this bug might remain.

Very maybe setting PascalCoinMaster in settings of github desktop might help but it says this will change my global git settings and I don't want that to occur so I will not try this possibility.

**Comment by SkybuckFlying** [comment]
When trying to push PascalCoinMaster branch it says, newer commits on remote...

The strange thing is the other cloned repository can work with this PascalCoinMaster branch... so maybe something wrongly setup in this local repository not sure.

I will try vice-versa.

Add the remotes to the github created clone that will shed some light on this.... somewhat..

**Comment by SkybuckFlying** [comment]
OK I have solved the problem for now as follows:

1. Clone my repository/fork.
2. Re-add remotes.

As far as I know this will re-create a repository that is similiar to my own, except no local file garbage... not sure if that has anything to do with it.

I will try and work with this new repository to see if I run into any issues or if anything else is missing... don't think so... besides from some garbage files... so I think this gives me a good chance that it will work.

Maybe re-downloading the repository is a good idea to fix any bugs in the repository ! ;)

**Comment by steveward** [comment]
Glad to hear you were able to get things working!
