### ISSUE TITLE
Enable side bar view for Desktop app

### ISSUE THREAD

**Issue by msavin** [desktop/desktop#13372]
### Describe the feature or problem you’d like to solve

I'm always switching between repos - some projects have multiple repos in one place. Currently, repos are only accessible by clicking on "Current Repository" - but it would be great to just have them available as a side bar. 

### Proposed solution

Have all the repos available as a side bar - just like you would have with any text editor. Allow different  groups and repos to be collapsed if necessary. There's no need to force those extra clicks. 

Bonus: allow to filter just for orgs. For example, if you're are work, you can set filter to `org:microsoft` and only those repos would appear so that you are not distracted 

### Additional context

![Group](https://user-images.githubusercontent.com/2031235/143182123-828e1272-d0d0-4cac-88fb-1fce65e2ab14.png)

**Comment by niik** [comment]
Hey @msavin, thanks for opening this! This has been discussed in https://github.com/desktop/desktop/issues/1593 and our current stance is that we don't intend to implement an always-open sidebar. Issues and comments like yours always weigh in when we re-evaluate our priorities though and I would suggest you add a 👍 reaction to the issue above and subscribe to it to follow any developments that happen in that area.
