### ISSUE TITLE
Link directly to branch or PR 

### ISSUE THREAD

**Issue by vincelamm** [desktop/desktop#13378]
### Describe the feature or problem you’d like to solve

When reviewing PRs, I often times start the branches locally. Getting to the PR however takes longer than it feels it would need to take. Getting to the Repo is as easy as SHIFT + COMMAND + G, getting to the PR/branch takes unnecessarily long.

### Proposed solution

Add an option or point GitHub option directly to the PR instead of the repo.

<img width="722" alt="Bildschirmfoto 2021-11-24 um 17 12 42" src="https://user-images.githubusercontent.com/6005290/143274624-a36c2215-9653-4870-b72b-185ef3bd3291.png">

**Comment by sergiou87** [comment]
Hey @vincelamm ! 👋 

Not sure if I'm following, but I think <kbd>Command</kbd> + <kbd>R</kbd> is what you're looking for. That shortcut will create a PR if you're in a branch that has been pushed but is not associated to a PR, or open the PR associated to the current branch if any.

Is that what you're looking for?
