### ISSUE TITLE
After cloning repository, GitHub Desktop prompts to commit non-existent changes

### ISSUE THREAD

**Issue by rakleed** [desktop/desktop#13370]
### Describe the bug

After cloning the repository, GitHub Desktop prompts me to commit the non-existent changes.

### Version & OS

- GitHub Desktop 2.9.4 (arm64)
- macOS 12.0.1

### Steps to reproduce the behavior

0. You may need to fork my repository and clone the already forked repository.
1. Open GitHub Desktop.
2. In the app menu select File › Clone Repository...
3. Go to the URL tab, enter `https://github.com/rakleed/rgpu`, and click Clone.
4. Agree to initialize Git LFS during cloning.
5. After cloning is complete, open the rgpu repository on GitHub Desktop and go to the Changes tab.

### Expected behavior

GitHub Desktop does not offer to commit anything.

### Actual behavior

GitHub Desktop offers to commit files as new, which have already been added to the repository.

### Screenshots

<img width="1072" alt="screenshot" src="https://user-images.githubusercontent.com/19418601/143089951-7c01504f-32a1-4e0c-9904-f1e76e5996cf.png">

### Logs

- [2021-11-14.desktop.production.log](https://github.com/desktop/desktop/files/7590530/2021-11-14.desktop.production.log)
- [2021-11-15.desktop.production.log](https://github.com/desktop/desktop/files/7590532/2021-11-15.desktop.production.log)

### Additional context

There is no such problem in the Windows version of GitHub Desktop. Also I tried to discard the changes in GitHub Desktop but it didn't help.

**Comment by steveward** [comment]
Thanks for the report @rakleed. Usually this is caused by line-ending or file mode changes. You can try running `git config core.fileMode false` to see if ignoring file mode changes helps in this instance, and I would also recommend normalizing your line-endings since you are using Windows and macOS. See [this guide](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings) for how to do that. 

It'd also be helpful if you could share the output of `git config --list --show-origin` to verify there aren't any configuration issues that could be causing this.

**Comment by rakleed** [comment]
@steveward Opened the path with cloned `rgpu` repository in terminal. Entered `git config core.fileMode false`, but it didn't help. Then I entered `git config --global core.autocrlf input`, but that didn't help either. Also rebooted macOS just in case, but that didn't work either.

<details>
<summary>git config --list --show-origin</summary>

```bash
file:/opt/homebrew/etc/gitconfig        credential.helper=osxkeychain
file:/Users/rakleed/.gitconfig  filter.lfs.process=git-lfs filter-process
file:/Users/rakleed/.gitconfig  filter.lfs.required=true
file:/Users/rakleed/.gitconfig  filter.lfs.clean=git-lfs clean -- %f
file:/Users/rakleed/.gitconfig  filter.lfs.smudge=git-lfs smudge -- %f
file:/Users/rakleed/.gitconfig  user.name=Pavel Moiseenko
file:/Users/rakleed/.gitconfig  user.email=19418601+rakleed@users.noreply.github.com
file:/Users/rakleed/.gitconfig  core.autocrlf=input
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.ignorecase=true
file:.git/config        core.precomposeunicode=true
file:.git/config        submodule.active=.
file:.git/config        remote.origin.url=https://github.com/rakleed/rgpu.git
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.main.remote=origin
file:.git/config        branch.main.merge=refs/heads/main
file:.git/config        lfs.https://github.com/rakleed/rgpu.git/info/lfs.access=basic
```

</details>
