### ISSUE TITLE
Compile it on my own

### ISSUE THREAD

**Issue by TheBlckbird** [desktop/desktop#13387]
How can I compile Github Desktop on my own for LinuxARM32?

**Comment by niik** [comment]
Hi @1Spinne, GitHub Desktop doesn't officially support Linux although there's a very active fork which does (https://github.com/shiftkey/desktop) which would be your best bet for finding more information about Linux builds.

Out of curiosity, what kind of hardware are you running that would require 32-bit ARM?

**Comment by TheBlckbird** [comment]
@niik I`m using a raspberry pi
