### ISSUE TITLE
Could not resolve host: github.com

### ISSUE THREAD

**Issue by imraaqeel** [desktop/desktop#13383]
(base) C:\Users\Dr. Abdul Majid>pip install git+https://github.com/bp-kelley/descriptastorus
Collecting git+https://github.com/bp-kelley/descriptastorus
  Cloning https://github.com/bp-kelley/descriptastorus to c:\users\dr9ee7~1.abd\appdata\local\temp\pip-req-build-pk5xf6sy
  Running command git clone -q https://github.com/bp-kelley/descriptastorus 'C:\Users\DR9EE7~1.ABD\AppData\Local\Temp\pip-req-build-pk5xf6sy'
  fatal: unable to access 'https://github.com/bp-kelley/descriptastorus/': Could not resolve host: github.com
ERROR: Command errored out with exit status 128: git clone -q https://github.com/bp-kelley/descriptastorus 'C:\Users\DR9EE7~1.ABD\AppData\Local\Temp\pip-req-build-pk5xf6sy' Check the logs for full command output.

**Comment by sergiou87** [comment]
I'm sorry @imraaqeel but that doesn't look like a GitHub Desktop specific error.

It seems your machine is unable to resolve github.com, meaning there is some kind of DNS problem. If your machine is running behind a proxy, you probably need some extra configuration in git to make it work. For example, you can take a look at https://stackoverflow.com/questions/20370294/git-could-not-resolve-host-github-com-error-while-cloning-remote-repository-in

I hope that helps.

**Comment by KendallDoesCoding** [comment]
@imraaqeel Please confiirm if issue has been fixed!

**Comment by imraaqeel** [comment]
Yes. It has resolved
