### ISSUE TITLE
Can't clone a repository onto a network share

### ISSUE THREAD

**Issue by DanForever** [desktop/desktop#13380]
### Describe the bug
I created a fresh repository with a readme and license file (nothing else) via the web interface
Then I tried to clone the repository to my NAS. Both the network path \\MyNas\Project\Path and the mapped path Z:\Project\Path produce the same error

### Version & OS
Github desktop Version 2.9.4 (x64)
Windows 10  21H1

### Error from desktop app
Cloning into 'Z:\Projects\MyProject'...
error: unable to open object pack directory: //MyNas/Projects/MyProject/.git/objects/pack: Not a directory
remote: Enumerating objects: 4, done.        
remote: Counting objects: 100% (4/4), done.        
remote: Compressing objects: 100% (4/4), done.        
error: unable to open object pack directory: //MyNas/Projects/MyProject/.git/objects/pack: Not a directory
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0        
Receiving objects: 100% (4/4), 12.55 KiB | 676.00 KiB/s, done.
fatal: update_ref failed for ref 'HEAD': cannot update the ref 'refs/heads/main': unable to create directory for '//MyNas/Projects/MyProject/.git/logs/refs/heads/main': No such file or directory

**Comment by sergiou87** [comment]
Hey @DanForever !

Have you tried cloning the repo to the same path via the command line?

**Comment by DanForever** [comment]
You mean just with pure git?

**Comment by sergiou87** [comment]
Yup! I'd like to know if it's a problem specific to GitHub Desktop or more generic. Thanks!

**Comment by marelab** [comment]
Have the same Problem doesn't work on Desktop and CLI. Maybe after NAS QNAP Update.
OS WIN10 x64
GIT cli git version 2.34.0.windows.1
GIT DESKTOP Version 2.9.4 (x64)

MSG:
remote: Enumerating objects: 312, done.        
remote: Counting objects: 100% (312/312), done.        
remote: Compressing objects: 100% (220/220), done.        
remote: Total 312 (delta 147), reused 234 (delta 69), pack-reused 0        
Receiving objects: 100% (312/312), 2.31 MiB | 4.61 MiB/s, done.
Resolving deltas: 100% (147/147), done.
error: Unable to create '//NAS3443A0/share/GITHUB/stealth-controller/.git/refs/remotes/origin/HEAD.lock': No such file or directory
fatal: unable to update refs/remotes/origin/HEAD

**Comment by DanForever** [comment]
So here's the command line doing it onto the network mapped directory (cmd does not support unc paths)
```Z:\test>git clone https://github.com/DanForever/Arduino-PC-Health-Monitor.git ./
Cloning into '.'...
remote: Enumerating objects: 226, done.
remote: Counting objects: 100% (226/226), done.
remote: Compressing objects: 100% (149/149), done.
remote: Total 226 (delta 86), reused 202 (delta 66), pack-reused 0
Receiving objects: 100% (226/226), 1.17 MiB | 6.23 MiB/s, done.
Resolving deltas: 100% (86/86), done.
fatal: bad object refs/tags
fatal: remote did not send all necessary objects```

**Comment by sergiou87** [comment]
If it's an issue from the command line, I'm afraid it's not a Desktop specific issue. Does this help? https://stackoverflow.com/a/13831085 🤞
