### ISSUE TITLE
Two accounts is creating problems

### ISSUE THREAD

**Issue by Gcull** [desktop/desktop#13388]
I created two accounts with the same email address, attempted to delete one after encountering issues, now after deleting one my desktop Github is logged into one and my web browser is logged into another, and they seem to be confusing each other?

**Comment by tidy-dev** [comment]
@Gcull That is a curious scenario. I would suggest signing out and back in again to make it so they are both on the same account. 

On Windows, File > Options > Accounts -> Sign out (same to sign in)o 
On Mac, GitHub Desktop > Preferences > Account

**Comment by tidy-dev** [comment]
With the thumbs up, going to assume this is no longer an issue. Feel free to reach out again if otherwise. :)

**Comment by CwanyJest95** [comment]
> I created two accounts with the same email address, attempted to delete one after encountering issues, now after deleting one my desktop Github is logged into one and my web browser is logged into another, and they seem to be confusing each other?
