### ISSUE TITLE
Design Sync-up Agenda (May 9)

### ISSUE THREAD

**Issue by donokuda** [desktop/desktop#1338]
We (@niik and @donokuda) won't be able to sync up this week due to holiday and travel schedules; however, I'll still open up this issue for tracking ongoing design work. **This sync-up is also scheduled for after our planned beta ship**; therefore, let's treat this as an on-going to do list as well as an agenda!

**Action items from [last week](https://github.com/desktop/desktop/issues/1276)**

- [ ] @donokuda and @niik to ponder better ways to show an expandable commit message
- [x] @donokuda to follow up app icon with a couple more color variations (https://github.com/desktop/desktop/issues/1221)
- [ ] @niik to write up issue(s) for discarding changes
- [x] @donokuda to check in with installation animation
- [ ] @niik to continue work in the a11y branch
- [x] Someone to start design for showing long running commit processes
- [x] @donokuda to get the new Desktop site staged somewhere and tested out before we merge in.
- [x] @donokuda to also follow up with more content for the Desktop site
- [ ] @donokuda or @niik to pull primer color variables into our stylesheets

**New agenda**

```typescript
// TODO: Fill me in
```

**Comment by niik** [comment]
Next sync up is at https://github.com/desktop/desktop/issues/1816
