### ISSUE TITLE
Current repository not highlighted in list in light mode

### ISSUE THREAD

**Issue by mthierman** [desktop/desktop#13386]
### Describe the bug
In light mode, the current repository is not highlighted in the list like in dark mode.

### Version & OS

2.9.4 (x64) - Windows 11

### Steps to reproduce the behavior

1. Select repository
2. Open list & check for current repository

### Expected behavior

Current repository to be highlighted as in the dark mode.

### Actual behavior

No repository is highlighted.

### Screenshots

![ghd-highlight](https://user-images.githubusercontent.com/68129072/143483931-488a5508-d4af-47b6-9893-71b423d18026.png)

**Comment by niik** [comment]
Hi @rovingey, thanks for opening this. We identified and fixed this issue in https://github.com/desktop/desktop/pull/13115 and it will be included in the next production release. In the meantime your welcome to install our beta version or temporarily use the dark theme.
