### ISSUE TITLE
Trying to make a commit and get "error Command "husky-run" not found."

### ISSUE THREAD

**Issue by wcardosodev** [desktop/desktop#13391]
### Describe the bug
When trying to commit some file changes I get this error message: "error Command "husky-run" not found."

### Version & OS
Version: 2.9.4 (x64)
OS: Windows 10

### Steps to reproduce the behavior
1. Tick relevant files I want to commit
2. Enter name of commit 
3. Click "commit to ${myBranch}"

### Expected behavior
The commit would go through without receiving said error.

### Actual behavior
I received the error which is preventing me from commiting.

### Logs
https://justpaste.it/4e1fg

### Additional Context
Git on windows seems to be not working as expected either. Not 100% sure if related

**Comment by sergiou87** [comment]
Hi @wcardosodev! 👋 

I'm afraid we can't offer support with debugging individual Git hook setups, but it seems that the project you're trying to contribute to is using the [husky](https://github.com/typicode/husky) project to enforce a certain format for their commit messages. If that's the case, you probably need to install husky (or disable it) to make this work.

I'm sorry I can't be of more help 😳
