### ISSUE TITLE
add support for searching files in a commit

### ISSUE THREAD

**Issue by devsebastian** [desktop/desktop#13396]
### Describe the feature or problem you’d like to solve

It's been a really long time since I've wanted the file search feature in GitHub Desktop! In large projects like huge Web/Mobile Applications, it becomes really hard to keep track of what files were updated/added/removed in a specific commit of a branch. The file search feature will make it very simple to find updated files and show their changes as opposed to finding the files manually by scrolling through the large list of updated files!

### Proposed solution
The proposed solution is to add a `<FancyTextbox/>`  right above the file list, like the one used in "search for branches to compare" in GitHub Desktop. This would be a huge productivity booster for many developers who would also want to search for a specific file on other branch commits!

****_I would also like to ask if I could start working on this feature? I would find it really interesting to contribute and introduce this feature in the Desktop app._**

![image](https://user-images.githubusercontent.com/19506171/143733924-74b2f3c6-dece-4df6-bdb5-7f1e6329f28b.png)

**Comment by steveward** [comment]
Thanks for the issue @devsebastian! This has been previously requested/discussed in https://github.com/desktop/desktop/issues/7022 so I'm going to add your feedback there to consolidate everything.
