### ISSUE TITLE
git commit is not working

### ISSUE THREAD

**Issue by spdsp04** [desktop/desktop#13394]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tidy-dev** [comment]
@spdsp04 Thank you for the issue. Can you fill out the rest of template above ☝️ so we have an indication of what the problem is.
