### ISSUE TITLE
how to recover my login and pass?

### ISSUE THREAD

**Issue by KingdomMir2** [desktop/desktop#13397]
it seems my github web page id and pass will not work here , how can i log in to upload my hub?

**Comment by tidy-dev** [comment]
👋  @KingdomMir2  If you are signed out in GitHub Desktop, you can sign into GitHub Desktop by going to preferences. View the main systems menu of GitHub Desktop > Preferences > Accounts and for an enterprise (most common) look under the first heading of GitHub.com and click the sign in button. This will open GitHub.com in browser to complete the login process. 

(You have posted this here, so I would assume you can log in to GitHub.com) But, if you are having trouble signing to GitHub.com, you may want to try the the Forgot password? link there and create a new password.
