### ISSUE TITLE
add proxy set.

### ISSUE THREAD

**Issue by lxeridium** [desktop/desktop#13398]
### Describe the feature or problem you’d like to solve

add proxy set.
add language support.

**Comment by Meaningisuse** [comment]
Good idea! In China, we must use a proxy to access github most of the time

**Comment by steveward** [comment]
@lxeridium thanks for the issue. 

You can configure GitHub Desktop to work with a proxy by running the following command from the command line (you will need to [install Git for Windows](https://git-scm.com/download/win) if you have not already):

`git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`

Replace `proxyuser` with your proxy username and `proxypwd` with your proxy password. Also, `proxy.server.com:8080` needs to point to the URL of your proxy server.

At this time we do not have language localization in GitHub Desktop, but this is something that we would like to do in the future. I don't have a timeline for when that may happen as it would require quite a bit of work by the team. I'm sorry that I don't have better news at this time. I'm going to close this issue out.
