### ISSUE TITLE
Commit Removal Request

### ISSUE THREAD

**Issue by baoqt2** [desktop/desktop#13399]
Hello,

I've accidentally committed a large file and am unable to revert the commit in order to get back to my regular routine. Can someone please reach out and help? Please refer to the attached.

My github username is baoqt2 and email is at baoqt2@uci.edu

Thank you, in advance. 

![Screenshot (82)](https://user-images.githubusercontent.com/57159268/143782713-1cd6313f-9b28-418c-9763-9c4d7a51a7a0.png)

**Comment by tidy-dev** [comment]
@baoqt2 Hi! The latest unpushed commit can be "undone" via right clicking the context menu and selecting "Undo Commit..". This will move those changes back into your changes tab. 

You will get a warning if you have changes present. If you are concerned about those changes conflicting or just muddling when you undo your last commit, you can stash them via the Branch Menu > Stash all changes.  And then, undo the large file commit, recommit without it, then, you can apply the stash again at the bottom of the changes panel. :) Hope this helps!

![Screen Shot 2021-11-29 at 6 37 39 AM](https://user-images.githubusercontent.com/75402236/143861616-6a45b757-b7ca-46e3-9c15-fab715ba9f7a.png)
