### ISSUE TITLE
Pushing to origin problem (Github Desktop)

### ISSUE THREAD

**Issue by sercandemirtas** [desktop/desktop#13402]
Hello all,

Im using GitHub desktop version to upload my files. Sometimes I have the following problem while uploading files.
When I try to "Push Origin" It is just trying to upload, it stays the way i shared the picture. Round arrows keep spinning and value of the Total, Delta and reused stays steady. What is problem here ?

Thanks..

### Version & OS

Version 2.9.4 (x64)
MacOS Monterey 12.1

### Expected behavior

Complete Push Origin

### Actual behavior

Trying to Push 

### Screenshots
<img width="255" alt="Ekran Resmi 2021-11-29 16 48 10" src="https://user-images.githubusercontent.com/68244546/143879333-7d17f783-6d5a-4997-b32f-ccfec046783f.png">

### Logs
.
[2021-11-29.desktop.production.log](https://github.com/desktop/desktop/files/7618548/2021-11-29.desktop.production.log)

**Comment by tidy-dev** [comment]
@sercandemirtas Thanks for the report!

When this occurs have you tried logging out and logging back in again (with an account that has access to this repo). The logs seem to indicate that GitHub Desktop is unable to access the repo. You can do this by going to GitHub Desktop > Preferences > Accounts
