### ISSUE TITLE
'Current branch' control width - increase?

### ISSUE THREAD

**Issue by MSP-Greg** [desktop/desktop#13400]
### Describe the feature or problem you’d like to solve

Current branch name is often truncated.

### Proposed solution

Currently there are three control areas below the menu, 'Current repository', 'Current branch', and 'Fetch *'. On my desktop, even with the app window ~ 60% of my desktop width, the three areas are about 50% of the window width.  Could they be widened?  In particular, 'Current branch'?

I changed the `#desktop-app-toolbar .toolbar-dropdown.branch-button` width value to `30em` and also `330px`, and both looked like they'd work for most desktops?

### Additional context

na

**Comment by tidy-dev** [comment]
Hi @MSP-Greg! Thank you for the feedback. This issue is being tracked under #2745. Thus, I am going to close this one in favor of tracking it there. Feel free to add your support by thumbs upping the issue and comment on it if you would like to add more context.
