### ISSUE TITLE
Can't push [ Remote hungup]

### ISSUE THREAD

**Issue by divyanshu-kunwar** [desktop/desktop#13415]
### Describe the bug
Sometimes GitHub desktop shows a message while pushing . " send-pack: unexpected disconnect while reading sideband packet
fatal: The remote end hung up unexpectedly "

### Version & OS

Version 2.9.4 (x64)

### Steps to reproduce the behavior
While pushing commit , on network change i think.

### Expected behavior

Able to push without any unexpected issue

### Actual behavior

This is terrible experiance
### Screenshots

![image](https://user-images.githubusercontent.com/68821907/144093400-575aaf47-3976-448a-8580-e3898cbb096e.png)

### Logs

[2021-11-30.desktop.production.log](https://github.com/desktop/desktop/files/7627434/2021-11-30.desktop.production.log)

**Comment by tidy-dev** [comment]
Thanks for the report @kUNWAR-DIVYANSHU Are you behind a proxy/firewall or running any antivirus software the could be interfering with your connection?

**Comment by divyanshu-kunwar** [comment]
It was working well and it started working again after changing HTTPS to
ssh and back to HTTPS.

**Comment by tidy-dev** [comment]
Ok. I am glad you found a resolution. This would seem to be a connection issue and especially if you have reason to suspect that your network did change at some point. Possibly the switching back and forth just reestablished the connection.. or gave enough time for the network connection to resolve.
