### ISSUE TITLE
Outdated Unity gitignore template

### ISSUE THREAD

**Issue by heatblayze** [desktop/desktop#13410]
### Describe the bug
The .gitignore template file provided with the desktop app is severely outdated.
The file provided with Github Desktop appears to be [this version](https://github.com/github/gitignore/blob/a2e5aea9171bda7cc8efdfcd1623b907504c6528/Unity.gitignore) of the Unity.gitignore template (which is around 3 years old).
There have been a number of changes to the template after the version that was included.

### Version & OS

Github Desktop: 2.9.4
OS: Windows 10 x64 

### Steps to reproduce the behavior

1. Check the version of the template included with Github Desktop (windows is located at `%localappdata%/GitHubDesktop/app-2.9.4/resources/app/static/gitignore`)
2. Compare to the version on master branch of the github/gitignore repo [located here](https://github.com/github/gitignore/blob/master/Unity.gitignore)
3. Also compare against the version that appears to match with the one included with the desktop app, [located here](https://github.com/github/gitignore/blob/a2e5aea9171bda7cc8efdfcd1623b907504c6528/Unity.gitignore)

### Expected behavior

The template should be at least semi-recent. I had assumed the desktop application pulled from the Github REST API ([reference](https://docs.github.com/en/rest/reference/gitignore)), but the data retrieved from the REST API appears to be the most recent version of the file.

### Actual behavior

The Github Desktop application uses a version of the Unity gitignore template from roughly 3 years ago.

### Screenshots

File from gitignore repo from Oct 18, 2018: 
![image](https://user-images.githubusercontent.com/10677646/143971376-d63e4cd9-ff71-4205-92de-9e05d6275179.png)

File located in `%localappdata%/GitHubDesktop/app-2.9.4/resources/app/static/gitignore` (which gets included in new projects when selected):
![image](https://user-images.githubusercontent.com/10677646/143971630-38765112-151c-4548-932f-d64b75c22364.png)

### Logs

N/A

### Additional context

Not super impactful, just a minor annoyance when setting up new projects 😊

**Comment by say25** [comment]
I can take this on
