### ISSUE TITLE
[Feature] Support force push directly by user

### ISSUE THREAD

**Issue by darkduckgo** [desktop/desktop#13420]
### Describe the feature

Try a lot of way but can't know how to force push to remote repository by myself, please do support it, even with the WARNING  
 dialog

### Proposed solution

people may commit amend to previous commit, and want to force push (not rebase, it was dangerous), and now we only can rebase it then force push in desktop, so could we support one click (with ensure again) for user to force push directly?

thanks a loooooot, the desktop design is really wonderful

**Comment by sergiou87** [comment]
Does this help a bit: #13384 ?

**Comment by darkduckgo** [comment]
> Does this help a bit: #13384 ?

yep, thanks a lot, hopefully it could release soon~  (u can link this issue to it)
