### ISSUE TITLE
custom command pallet 

### ISSUE THREAD

**Issue by nilupulHeshan** [desktop/desktop#13421]
users should have to have the access of type custom command for a certain repository.
There should be a terminal

**Comment by steveward** [comment]
Thanks for the request @nilupulHeshan. Adding a command palette has been [previously discussed](https://github.com/desktop/desktop/issues/3050#issuecomment-462493209), but at this time is out of the scope of what we want to focus on in GitHub Desktop. In the future this may be something we consider again, so thanks for letting us know you're interested in this feature.
