### ISSUE TITLE
Unable to Discard Files

### ISSUE THREAD

**Issue by say25** [desktop/desktop#13433]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Version 2.9.6-beta1 (x64)
Windows 10

### Steps to reproduce the behavior

1. Make a change
2. Click right click discard changes on file
3. See application hang

### Expected behavior

File is discarded

### Actual behavior

App hangs, you are unable to cancel discard changes as well.

### Screenshots

![image](https://user-images.githubusercontent.com/7467062/144482493-7e9be727-ed7e-4d5c-9c96-edfae69b7e86.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

This is the first version with new Electron and there are Electron changes around file discards

**Comment by Tweaker420** [comment]
Mirror concept and execute in the transcript
