### ISSUE TITLE
desktop app doesn't work

### ISSUE THREAD

**Issue by mvrozend** [desktop/desktop#13437]
### Describe the bug
Write a clear and concise description of what the bug is.
I am not able to log in on the desktop app with a different email address. I want to log out because my projects are not syncing, so I made a different account, but I can't even use that.

### Version & OS
Windows. 

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Go to 'options'
2. Click on 'sign out'
3. Click on 'sign in'
4. the application sends you to a webbrowser to sign you in
5. the webbrowser immediately signs you in and sends you back without you being able to switch accounts

### Expected behavior
I expect to still be able to change my account. Normally you still have to press the login button if your username and password are already there, and then it sends you back to the desktop application.

Write a clear and concise description of what you expected to happen.

### Actual behavior
I don't see the login screen, as soon as I go to the browser login, it sends me back to the application. 
Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context
It's annoying. I also deleted my account and made a new one (new emailadress as well), yet my old account is still opened, even though it was deleted.

**Comment by sergiou87** [comment]
Hey @mvrozend ! 👋 

In order to fix this you must sign in with the new account from the browser.

GitHub Desktop will sign in with whatever account you have signed in on your browser.

Does that help? 😳

**Comment by mvrozend** [comment]
Yes I understand that I need to sign in with a new account. My problem is that I can't. There is no login screen.

**Comment by tidy-dev** [comment]
@mvrozend If you are currently logged in on GitHub.com with account X, but want to use account Y in GitHub Desktop. I would suggest going to GitHub.com and clicking on the dropdown with your avatar in top right of screen and click sign out. Now, when you attempt to login from GitHub Desktop and it opens the browser, it should request you to login. Hopefully that helps?
