### ISSUE TITLE
[suggestion] add an option to hide the program to tray when minimized

### ISSUE THREAD

**Issue by 1280px** [desktop/desktop#13438]
(check title)

**Comment by niik** [comment]
Hey @1280px, thanks for opening this. This has been requested in https://github.com/desktop/desktop/issues/4098 and while we don't have any plans to support minimizing to tray at this time you can subscribe to that issue to see any developments in that area. Perhaps a third-party tool (a list of such can be found at https://www.maketecheasier.com/send-windows-programs-to-system-tray/) could satisfy your requirement.
