### ISSUE TITLE
Tooltips overlap on uncommitted changes badge

### ISSUE THREAD

**Issue by j-f1** [desktop/desktop#13449]
### Describe the bug

The path tooltip and the “There are uncommitted changes in this repository” tooltip overlap.

### Version & OS

GitHub Desktop Version 2.9.5 (x64)
macOS 11.6 (20G165)

### Steps to reproduce the behavior

1. Make changes in a repo, but don’t commit them
2. Open the repo switcher
3. Hover over the blue dot 🔵
4. See behavior as in screenshot below

### Expected behavior

The new tooltip UI shows up with a description of the blue dot

### Actual behavior

![image](https://user-images.githubusercontent.com/25517624/144752599-1b7917a0-e69e-4a5f-b176-4e5f132a3b2a.png)

### Logs

N/A but happy to attach if needed

**Comment by niik** [comment]
Thanks for reporting this @j-f1! I'll take a look. Fixing the old-style tooltip should be no biggie but I have to ponder a little bit on what to do with nested tooltips like this

**Comment by JunnieEJ4** [comment]
Opensea

**Comment by YoseeF27** [comment]
- [ ]
