### ISSUE TITLE
i have a 100MBps internet connection but i am getting 200KB/s Speed, Why i am getting this problem

### ISSUE THREAD

**Issue by shoaiboss** [desktop/desktop#13444]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@shoaiboss thanks for the issue. It'd be helpful if you could fill out the template and upload your log files to give us some more information. Are you seeing slow speeds when cloning repositories?

Speed issues can be related to a number of factors -- the size of the repository, the reliability of your ISP, your proximity to GitHub's servers, etc. I'd recommend running through https://github-debug.com/ to see what kind of performance you get.
