### ISSUE TITLE
MAJOR PROBLEM Repository stopped working 

### ISSUE THREAD

**Issue by soaringcylinder** [desktop/desktop#13448]
### Describe the feature or problem you’d like to solve

Hi so after working for months my repository suddenly disappeared and now i cant get access to my project i don't know how to get it back. 

### Proposed solution

idk I'm new to this 

### Additional context

Please include any other context, like screenshots or mockups, if applicable
![wierd shit](https://user-images.githubusercontent.com/89431943/144731078-d01a9f59-fcdf-4ac5-bbba-547df62f6137.PNG)
![wierd shit](https://user-images.githubusercontent.com/89431943/144731083-02fae0f0-7871-4faa-9347-74d01ba1eb95.PNG)
.

**Comment by tidy-dev** [comment]
:wave:  Sorry as I can see this must be frustrating. Based on that error, it looks like your repository was stored in a location that was likely deleted upon upgrading to the 2.9.5 release.  Did you have any of this work pushed to a remote store? 🤞 

Some quick googling and I found this - maybe it could help you recover those files. 
https://support.microsoft.com/en-us/windows/recover-lost-or-deleted-files-7bf065bf-f1ea-0a78-c1cf-7dcf51cc8bfc

For future references, I would suggest cloning your repositories to somewhere app agnostic. Many people store them in their Documents directory or something similar that they have created for repos. Do not store them in GitHubDesktop\app-x.x.x\ folder as with updates those folders get churned.
