### ISSUE TITLE
Pushing to origin doesn't finish

### ISSUE THREAD

**Issue by daileyl1** [desktop/desktop#13440]
### Describe the bug
Write a clear and concise description of what the bug is.
When trying to commit to the git hub repository, the process starts but just spins after it says total 9202 (delta 2189)
![image](https://user-images.githubusercontent.com/68693115/144619239-5cac37d3-6206-4729-a407-493ff77e55fe.png)

### Version & OS
Version 2.9.4(x64) MAC OS
Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.
Commit to complete
### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

![image](https://user-images.githubusercontent.com/68693115/144619297-be96f74c-a9c2-40ac-981c-385403862546.png)

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
2021-11-23.desktop.production.log
2021-12-03.desktop.production.log

**Comment by steveward** [comment]
@daileyl1 thanks for the report. It looks like your log uploads didn't make it through -- could you try uploading them again?

**Comment by BerkayTrkmn** [comment]
I had same problem, closed GitHub desktop and changed internet connection.That's solved my problem.

**Comment by nad328** [comment]
> I had same problem, closed GitHub desktop and changed internet connection.That's solved my problem.

solid, this worked for me too. thanks :)

**Comment by luigiast** [comment]
Same problem here!

**Comment by luigiast** [comment]
> I had same problem, closed GitHub desktop and changed internet connection.That's solved my problem.

Also worked for me. Thanks!

**Comment by brundlefly** [comment]
> I had same problem, closed GitHub desktop and changed internet connection.That's solved my problem.

This worked perfectly! You saved my butt today.

**Comment by neuromancer2022** [comment]
> 

This worked for me too - I quit Github desktop, switched from Wifi to ethernet, restarted Github desktop and....boom! :)

The question I have is....why?

**Comment by Elvish9090** [comment]
Just update Git desktop and try again...

**Comment by rhoffmanstellar** [comment]
> I had same problem, closed GitHub desktop and changed internet connection.That's solved my problem.

This also worked for me.  I turned on my VPN connection and was able to push.
