### ISSUE TITLE
Annoying tooltips in new version

### ISSUE THREAD

**Issue by agusterodin** [desktop/desktop#13452]
In the new version of GitHub Desktop on MacOS Version 2.9.5 (arm64), there are tooltip when hovering over "current repository", "current branch", and "fetch origin".

Personally I find this really annoying. Can we get an option to disable? I understand that option to disable seems way too specific and seems like extra complexity and maintenance burden for your team but I just don't understand the point of these tooltips.

In particular the "current branch" popup offers zero advantage to anybody other than a literal first time user. It is completely redundant.

![image](https://user-images.githubusercontent.com/10248395/144769182-e2ebb946-351a-4514-a80d-074e75bc0e75.png)

Thanks for your consideration. This is an otherwise awesome application.

**Comment by agusterodin** [comment]
I really hate to be that guy but this is perplexing. 

![image](https://user-images.githubusercontent.com/10248395/144769986-0780bec1-ba27-4fa3-9ee2-d643a48fa358.png)

**Comment by niik** [comment]
Hey @agusterodin, thanks for opening this. Converting all of our previous style tooltips (which took ~2s to appear) was a big project and we have certainly missed a few places where the tooltips previously didn't cause a nuisance (since few people saw them). I'll try take a look at these two this week!

**Comment by agusterodin** [comment]
Thanks for your consideration. 

It really is a practice of optimizing for first time user versus someone who uses the software daily . I'd say some of the more redundant ones (like shown in screenshots) are completely unnecessary whereas ones like last fetch timestamp and file path for selected repository are more useful.

What was the reasoning for getting rid of the 2s delay on tooltips? Personally I much prefer that behavior.

**Comment by billygriffin** [comment]
> What was the reasoning for getting rid of the 2s delay on tooltips?

It's just undiscoverable. So we've gotten tons of questions over the years of "how do I see x thing" and it's there but they just don't know it, and given space constraints and highly variable naming in Git repos, we think more immediate feedback, especially that we have more control over, is a nicer way to deliver that helpful information when it exists.

**Comment by agusterodin** [comment]
What about the tooltips in my screenshots where you mirror the exact
contents of a button or current branch? Those aren't helpful at all.

Jeff Rosen

**Comment by niik** [comment]
> What about the tooltips in my screenshots where you mirror the exact contents of a button or current branch?

Yeah, I'm taking a look at those along with #13449 this week 👍

**Comment by Yanp2373** [comment]
Xgv

**Comment by jmayes41** [comment]
> In the new version of GitHub Desktop on MacOS Version 2.9.5 (arm64), there are tooltip when hovering over "current repository", "current branch", and "fetch origin".
> 
> 
> 
> Personally I find this really annoying. Can we get an option to disable? I understand that option to disable seems way too specific and seems like extra complexity and maintenance burden for your team but I just don't understand the point of these tooltips.
> 
> 
> 
> In particular the "current branch" popup offers zero advantage to anybody other than a literal first time user. It is completely redundant.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/10248395/144769182-e2ebb946-351a-4514-a80d-074e75bc0e75.png)
> 
> 
> 
> Thanks for your consideration. This is an otherwise awesome application.
> 
> 

Good job keep up the good work
