### ISSUE TITLE
GitHub Desktop Invalid argument in Commit

### ISSUE THREAD

**Issue by isacfmaia** [desktop/desktop#13459]
### Describe the bug
When committing the code, the tool displays the error messages:

error: unable to create temporary file: Invalid argument
error: unable to create temporary file: Invalid argument
error: Error building trees

In log GitHub Desktop:
error: [ui] `git commit -F -` exited with an unexpected code: 1.

### Version & OS
Version 2.9.5 (x64)
Windowns 10 Pro 21H2

### Steps to reproduce the behavior

1. Go to changes;
2. Select alter files to commit;
3. Scroll down to button 'commit to branch'
4. After click see error.

### Screenshots

[https://drive.google.com/file/d/1V01ambsVSfxPAZfPM2R2eTbJalHEQyRc/view?usp=sharing](url)

### Logs

2021-12-07T13:38:35.034Z - info: [ui] [Timing] Action 'create commit' for 'MYPROJECT' took 0.936s
2021-12-07T13:38:56.371Z - info: [ui] [AppStore] loading 13 repositories from store
2021-12-07T13:38:57.955Z - info: [ui] launching: 2.9.5 (Windows 10.0.19044)
2021-12-07T13:38:57.956Z - info: [ui] execPath: 'C:\Users\username\AppData\Local\GitHubDesktop\app-2.9.5\GitHubDesktop.exe'
2021-12-07T13:38:59.035Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.076s)
2021-12-07T13:39:08.533Z - error: [ui] `git commit -F -` exited with an unexpected code: 1.
stderr:
error: unable to create temporary file: Invalid argument
error: unable to create temporary file: Invalid argument
error: Error building trees

**Comment by steveward** [comment]
Thanks for the report @isacfmaia. These types of errors can be caused by a few things, so it'd be helpful if you could answer a few questions:

- Are you seeing this error in one specific repository or in all of your repositories? 
- Are you storing this repository in a standard directory (i.e. not in DropBox, on a mapped network drive, etc.)?
- Have you tried committing directly via the command line to see if that succeeds?

**Comment by avipars** [comment]
I'm getting the error because it appears that windows put the folder in read only mode

**Comment by steveward** [comment]
@avipars permissions issues can cause this error. If you're having issues getting it resolved feel free to open a new issue.

**Comment by avipars** [comment]
Wanted to pipe in and hope other people can see ... hope it helps

**Comment by smargoli2** [comment]
I'm having this issue on a repository that is stored on OneDrive. I think it has been causing me a lot of issues. What do you recommend?
