### ISSUE TITLE
Github Desktop not counting as application, not coming as a application

### ISSUE THREAD

**Issue by KendallDoesCoding** [desktop/desktop#13455]
### Describe the bug
Cloning into 'path'...
git: 'remote-https' is not a git command. See 'git --help'.

path = (Screenshot with path added)

### Version & OS
Newest Github Version
Windows OS

### Steps to reproduce the behavior

1. Clone Repo 
2. Clone from Github.com
3. Paste url https://github.com/TechStudent11/heroku-portfolio

### Expected behavior
Error with code

### Actual behavior
Unsure

### Screenshots
![image](https://user-images.githubusercontent.com/84712013/144809226-588ac83f-e2ab-4e4f-98c2-731713421be3.png)

Add screenshots to help explain your problem, if applicable.

### Logs
No Logs

### Additional context

Not able to clone github repo from Github.com.. The same thing worked on my Laptop, but isn't working on the PC

**Comment by KendallDoesCoding** [comment]
I think the Github Destop app got automatically uninstalled because I opened the installation file again to send #13454, I'm reinstalling the software and I think it should work then, If it doesn't, I will re-open this issue.

**Comment by KendallDoesCoding** [comment]
Hi,

I re-installed it, but it's still not counting as a computer application, and is not viewable on the computer softwares list. It did show up on my other device. 

Please help me on this, and then I think my issue of cloning repo will be fixed.

**Comment by KendallDoesCoding** [comment]
I uninstalled and re-installed the app but it still it ddnt come

**Comment by tidy-dev** [comment]
@KendallDoesCoding Could you try doing a full uninstall:

1. Go to %AppData% and delete the GitHub Desktop directory
2. Re-download from [desktop.github.com](https://desktop.github.com/) and reinstall

**Comment by KendallDoesCoding** [comment]
Will do that shortly, Thanks!

**Comment by KendallDoesCoding** [comment]
![image](https://user-images.githubusercontent.com/84712013/144853494-72b8b1d9-9e56-4a53-bf58-41e2255409f5.png)

**Comment by tidy-dev** [comment]
@KendallDoesCoding Seems something is interfering with Desktop function. Do you have any other antivirus asides from windows defender? (Here is a [recent issue](https://github.com/desktop/desktop/issues/12163) where that was the problem.)

**Comment by KendallDoesCoding** [comment]
Yup, I got Norton but I have that on my laptop too and it worked just fine
there.

**Comment by tidy-dev** [comment]
Sometimes the antivirus only interferes around updates - which we just had one. Could you try disabling it, and redoing the full uninstall and reinstall? 
(If this works, the full solution would be to whitelist Desktop from your antivirus.)

**Comment by KendallDoesCoding** [comment]
Yup, I'll try doing that in a while and get back to you.

**Comment by OP-EAA-MUSIC-NETWORKS** [comment]
STOP SENDING ME THESE
