### ISSUE TITLE
Cannot cherry-pick

### ISSUE THREAD

**Issue by JeffRubinoff** [desktop/desktop#13462]
### Describe the bug
I cannot drag a revision from History to the branch picker. If I right-click a commit, Cherry-Pick is greyed out. This is true for all commits in all branches. 
The only interesting thing in my repository is that I have more than one remote configured, with different branches on different remotes.
### Version & OS
2.9.5 (x64), macOS 11.6.1

### Steps to reproduce the behavior

1. Configure a repository with branches from at least 2 remotes.
2. Go to 'History'
2. Select any commit
3. Attempt to drag to the branch picker.
5. Right-click commit
6. Attempt to select 'Cherry-pick Commit...' option

### Expected behavior
I expected to be able to drag a commit over to the branch picker, that this would open a list of branches, and I would be able to drop the commit on a branch to cherry-pick it. Failing this, I would expect to be able to do something in the context menu for a commit.
### Actual behavior
I cannot drag a commit at all. The cherry-pick option in the context menu is greyed out.
### Screenshots

Add screenshots to help explain your problem, if applicable.

<img width="446" alt="2021-12-07_15-56-43" src="https://user-images.githubusercontent.com/95699904/145052369-8dd49b89-a8b9-44f1-bead-fe107776c968.png">
### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tidy-dev** [comment]
@JeffRubinoff That should only be the case if the app thinks a cherry-pick is in progress (in which case, it should be showing you some UI to indicate this). Could you try closing out the app and reopening it?

**Comment by JeffRubinoff** [comment]
It seems to have magically resolved itself! Since I was cherry-picking on the CLI in parallel, trying out this functionality, it's very possible the app thought the last one was still in progress. Feel free to close.

**Comment by SmartManoj** [comment]
> Could you try closing out the app and reopening it?

Reopen solved it. 

Steps to reproduce:
![Image](https://github.com/user-attachments/assets/51def312-acb2-4ac2-ad9f-fc1d2728c9d2)

If clicked outside the box, or switched the app, the pop-up will disappear and the issue will be appeared.
