### ISSUE TITLE
Everytime I close the app and reopen it I am forced to log back in

### ISSUE THREAD

**Issue by wcardosodev** [desktop/desktop#13468]
### Describe the bug
When opening the application, it asks me to "Sign in to GitHub.com" which I do successfully. I can push pull commit etc fine, but when I close the application and reopen it I am forced to "Sign in to GitHub.com" all over again, which happens every single time I close it.

### Version & OS
Version: 2.9.5 (x64)
OS: Windows 10

### Steps to reproduce the behavior

1. Open GithubDesktop
2. Click the "Sign in to Github.com" button.
3. Click the "Finish" button.
4. Close the application, just through clicking the "X" in the top right.
5. Reopen the app
6. See that you are logged out and must repeat steps 1 - 3.

### Expected behavior
I expect to stay logged in when I close the app and not have to relog every time I close it.

### Actual behavior
I get logged out when every time I close the app. OR. My login details are not saved and therefore I have to login when I reopen the app.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs
[2021-12-08.desktop.production.log](https://github.com/desktop/desktop/files/7675133/2021-12-08.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @wcardosodev.

Can you try resetting GitHub Desktop by following these steps?

1. Close GitHub Desktop
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop, log in, and add your repositories again

Let me know if that does not resolve this issue.

**Comment by wcardosodev** [comment]
@steveward that's worked perfectly thank you!
