### ISSUE TITLE
Github Desktop is working too slowly

### ISSUE THREAD

**Issue by togaykurtulus** [desktop/desktop#13465]
I use GitHub Desktop with my multiple divices. I ve got one more device and in this laptop
 github is working too slow. Commitint speed, seting up the branch , pushing and pulling are extremlly slow. In my desktop normally opening and getting ready to fetch  take 15 sec but at my new laptop it takes 5 minutes. Commiting takes 10-15 sec normally but now it takes 20 minutes. I can't understand what is wrong, please help me

**Comment by KendallDoesCoding** [comment]
> I use GitHub Desktop with my multiple divices. I ve got one more device and in this laptop github is working too slow. Commitint speed, seting up the branch , pushing and pulling are extremlly slow. In my desktop normally opening and getting ready to fetch take 15 sec but at my new laptop it takes 5 minutes. Commiting takes 10-15 sec normally but now it takes 20 minutes. I can't understand what is wrong, please help me

Same, It's lagging for my laptop too.

**Comment by steveward** [comment]
@togaykurtulus can you fill out the template and share the log files from GitHub Desktop? It'd be helpful to know what operating system you are running.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. 

For reference there is another recent report of performance issues in https://github.com/desktop/desktop/issues/13416, but so far I've been unable to directly reproduce this.

**Comment by togaykurtulus** [comment]
hello Steve , I used the same reprasotory with i3, i5  and i have the issue with i7 16gb ram and 1 tb ssd. 
[2021-12-07.desktop.production.log](https://github.com/desktop/desktop/files/7671735/2021-12-07.desktop.production.log)

Thank you for the template but this is only GUI lack , switching branch, commiting are taking too long. As i mentioned i used the same project with other systems and they were working ok.  
Thank you for the help

**Comment by steveward** [comment]
@togaykurtulus are you running antivirus/security software on your machine outside of the built-in Windows Defender? That's a common cause of performance problems.

**Comment by steveward** [comment]
@togaykurtulus as we have not heard back from you I am going to close this out. If you can share further details about your setup we can assist further. Thanks!
