### ISSUE TITLE
Github Desktop Youtube

### ISSUE THREAD

**Issue by KendallDoesCoding** [desktop/desktop#13473]
### Describe the feature or problem you’d like to solve

Know this is kinda off topic for this repo, but a Github Desktop youtube channel would really be cool. I know you guys have docs but yeah

### Proposed solution
It will have tutorial videos, which will help people to understand how to use Github Desktop more better.

### Additional context

I just think this is a cool idea!

**Comment by steveward** [comment]
Thanks for the feedback @KendallDoesCoding! At this time we don't have any plans around this, but there are a number of helpful videos created by users of GitHub Desktop on YouTube (and anyone is welcome to make some more!). We do have presentations about GitHub Desktop during our yearly GitHub Universe conference, so I'd recommend following along with the official GitHub YouTube channel for that type of content.

**Comment by KendallDoesCoding** [comment]
Thanks Steve!
