### ISSUE TITLE
Add support for VSCode portable

### ISSUE THREAD

**Issue by wingforth** [desktop/desktop#13483]
I have a portable vscode on my computer, but GitHub Desktop app can't  recognize it.  If I want to set vscode as an external editor of GitHub Desktop, I need to install vscode through the installation file. 
Is there any way to set the  poratble vscode as an external editor for GitHub Desktop?

**Comment by steveward** [comment]
Thanks for the feedback @wingforth. At this time portable installations are not supported in GitHub Desktop, but this is being tracked along with other editor improvements in https://github.com/desktop/desktop/issues/7033. There's a similar request for Notepad++ in https://github.com/desktop/desktop/issues/9561. I'm going to edit the title and label this as an enhancement.

**Comment by wingforth** [comment]
> Thanks for the feedback @wingforth. At this time portable installations are not supported in GitHub Desktop, but this is being tracked along with other editor improvements in #7033. There's a similar request for Notepad++ in #9561. I'm going to edit the title and label this as an enhancement.

Thank you for your reply, and hope that vscode can support adding other editors (including portable) as an external editor.

**Comment by ercothran** [comment]
I agree, I prefer using portable apps, less headache if something happens to my system, I just sync my folders over to a network share and then sync down to my new system and have very little to do and no admin rights to install required...thanks!

**Comment by steveward** [comment]
Portable editors should work now that you can add [custom editors to GitHub Desktop](https://docs.github.com/en/desktop/configuring-and-customizing-github-desktop/configuring-a-default-editor-in-github-desktop#configuring-a-custom-editor). I hope that helps!
