### ISSUE TITLE
swagger 2 snyk issue

### ISSUE THREAD

**Issue by sendebarshi** [desktop/desktop#13488]
used the latest version of swagger2 3.0.0 but still the issue persists because there is no fixed version available for Swagger-improper validation input. Here is the code snippet.
#feature/cdtasde 4416
      <dependency>
         <groupId>io.springfox</groupId>
         <artifactId>springfox-swagger2</artifactId>
         <version>3.0.0</version>
         <exclusions>
             <exclusion>
                 <artifactId>guava</artifactId>
                 <groupId>com.google.guava</groupId>
             </exclusion>
         </exclusions>
      </dependency>
      <dependency>
         <groupId>io.springfox</groupId>
         <artifactId>springfox-swagger-ui</artifactId>
         <version>3.0.0</version>
      </dependency>

**Comment by steveward** [comment]
@sendebarshi this issue tracker is for GitHub Desktop, it looks like you're looking for a different repository that is hosted on GitHub. I'm going to close this out.
