### ISSUE TITLE
github desktop is not opening in my windows 10

### ISSUE THREAD

**Issue by sahilpatil9763** [desktop/desktop#13497]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for reaching out @sahilpatil9763!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. It would especially be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

To access the log files go to the  menu in GitHub Desktop and select `Help` > `Show Logs...`. The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue.

**Comment by sahilpatil9763** [comment]
When i click on the icon of github desktop its not opening in my pc only showing loding but not opeing

**Comment by niik** [comment]
Can you try resetting GitHub Desktop by following these steps?

- Close GitHub Desktop
- Remove all of the files in `%APPDATA%\GitHub Desktop\`
- Restart GitHub Desktop, log in, and add your repositories again

Let me know if that does not resolve this issue.

**Comment by sahilpatil9763** [comment]
its still not opening

**Comment by steveward** [comment]
To get some more information about why the installation is failing it would be helpful if you could send over the log file that the Squirrel installer generates.

You should be able to find the log file here:

`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`

If no log file is being generated there you should be able to find one in the `SquirrelTemp` directory:

`%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

Please send that over as an attachment.

**Comment by carrickpaul** [comment]
I've had a similar issue when upgrading from 2.9.5 to 2.9.6 today. It would launch  (briefly seen in the task manager) and disappear.

I opened the old 2.9.5 executable (C:\Users\Paul\AppData\Local\GitHubDesktop\app-2.9.5), did a commit, exited, and the new 2.9.6 version now works.

From todays log files,  from before the app was working again, the only warning was:
[14/12/21 17:34:38] warn: UpdateInfo: Couldn't get release notes for:GitHubDesktop-2.9.6-delta.nupkg: System.IO.FileNotFoundException: Could not find file 'C:\Users\Paul\AppData\Local\GitHubDesktop\packages\GitHubDesktop-2.9.6-delta.nupkg'.
File name: 'C:\Users\Paul\AppData\Local\GitHubDesktop\packages\GitHubDesktop-2.9.6-delta.nupkg'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.ZipPackage.<>c__DisplayClass9_0.<.ctor>b__0()
   at NuGet.ZipPackage.EnsureManifest()
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)

**Comment by steveward** [comment]
@sahilpatil9763 you can also try deleting `%LocalAppData%\GitHubDesktop` and then reinstalling again to see if that gets things working.

**Comment by sahilpatil9763** [comment]
its still not happning

**Comment by KendallDoesCoding** [comment]
@sahilpatil9763 Do you have any antivirus running?

**Comment by sahilpatil9763** [comment]
no, it is expired

**Comment by KendallDoesCoding** [comment]
> no, it is expired

Ok. But did you manage to fix your issue or is it still giving you trouble?

**Comment by sahilpatil9763** [comment]
i did it but its still giving trouble

**Comment by KendallDoesCoding** [comment]
> i did it but its still giving trouble

Oh

**Comment by sahilpatil9763** [comment]
now whats next sir

**Comment by tidy-dev** [comment]
@sahilpatil9763  Getting the squirrel log would be helpful. :) 

>To get some more information about why the installation is failing it would be helpful if you could send over the log file that the Squirrel installer generates.
>
>You should be able to find the log file here:
>
>%LocalAppData%\GitHubDesktop\SquirrelSetup.log
>
>If no log file is being generated there you should be able to find one in the SquirrelTemp directory:
>
>%LocalAppData%\SquirrelTemp\SquirrelSetup.log
>
>Please send that over as an attachment.


Also you could try a full uninstall and clean install.

That is:
 1. Uninstall GitHub Desktop
 2. Remove  %APPDATA%\GitHub Desktop\
 3. Reinstall GitHub Desktop

**Comment by sahilpatil9763** [comment]
thank u sir now its working properly

**Comment by KendallDoesCoding** [comment]
@sahilpatil9763 That's great to hear! Requesting you to close this issue thread in that case.

**Comment by KendallDoesCoding** [comment]
> @sahilpatil9763 That's great to hear! Requesting you to close this issue thread in that case.

Thanks @sahilpatil9763

**Comment by Uchenna-ibute** [comment]
i can not access my github account, it keep saying sorry something went wrong

**Comment by sahilpatil9763** [comment]
> Can you try resetting GitHub Desktop by following these steps?
> 
> * Close GitHub Desktop
> * Remove all of the files in `%APPDATA%\GitHub Desktop\`
> * Restart GitHub Desktop, log in, and add your repositories again
> 
> Let me know if that does not resolve this issue.

**Comment by steveward** [comment]
@Uchenna-ibute if you are having issues authenticating in GitHub Desktop please open a new issue. Thanks!
