### ISSUE TITLE
Amend commit not showing up

### ISSUE THREAD

**Issue by willparsons** [desktop/desktop#13490]
### Describe the bug
I don't have the option to amend a commit in the history section.

### Version & OS
Github Desktop: 2.9.5
OS: Windows 11 21H2 Build 22000.348

### Steps to reproduce the behavior

1. Go to history 
2. Right-click on commit
3. No option to amend

### Expected behavior

I can amend a commit.

### Actual behavior

No option to amend a commit.

### Screenshots

![image](https://user-images.githubusercontent.com/10012418/145460597-c154b660-95ea-49bc-8dd8-185f59e38927.png)

### Logs

...

### Additional context

...

**Comment by steveward** [comment]
@willparsons thanks for the issue. You can only amend the most recent commit in your repository's history -- if you're unable to do that please let me know!

**Comment by willparsons** [comment]
That one was the most recent commit in history.
