### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by Gomathi91** [desktop/desktop#13493]
Many times i tried to clone gitlab project and it's display issue "Authentication Failed". I created Personal Access Token(PAT) in gitlab and used as a password in github desktop again it doesn't clone and get authentication failed. Please fix this issue. 

![image](https://user-images.githubusercontent.com/95854867/145522819-9effd37d-d2e6-461a-9c7d-fdbf6bad071a.png)

**Comment by steveward** [comment]
@Gomathi91 have you followed [this guide](https://github.com/desktop/desktop/blob/development/docs/integrations/gitlab.md) for using GitLab with GitHub Desktop? You need to make sure you set up the correct read/write access setting for the token. Let me know if that doesn't help.
