### ISSUE TITLE
Do

### ISSUE THREAD

**Issue by nikolay-pv** [desktop/desktop#13507]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by Thore3** [comment]
Show Logs...,

**Comment by nikolay-pv** [comment]
You won't believe me, but this issue was logged by accident through the GitHub mobile app in my pocket. I saw it briefly but assumed no harm was done.
I guess, logging issues now as easy as never 👍🏻 

Sorry for the inconvenience.
