### ISSUE TITLE
Don't show sign in buttons in the Welcome flow if they're already signed in

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1350]
On the Welcome flow, if a user signs in with their account, and then goes to the Git Credentials page and clicks `cancel`, I noticed that the the Sign-in links, `Sign into Github.com` and `Sign into Github Enterprise`, are still available to click. 

Should we allow the user to sign-in again at this point, as the account credentials has been accepted? I mention this because I can sign in with the browser and then come back to the below page and hit `skip this step`, yet it still accepts my browser login. 

Talking about this page after clicking `cancel` on Git Credentials page:
<img width="547" alt="screen shot 2017-05-02 at 2 54 54 pm" src="https://cloud.githubusercontent.com/assets/14828183/25634174/987597f0-2f47-11e7-8913-f425da85525e.png">

v0.0.037, OS X 10.11.5

**Comment by shiftkey** [comment]
Marking this as `enhancement` to indicate there's some things about the workflow that we need to think about.

**Comment by billygriffin** [comment]
@niik Wanted to bring this to your attention as part of #5686.

**Comment by tierninho** [comment]
Closing this as it has not come up enough times to be validated as a real problem.
