### ISSUE TITLE
I can't seem to build the project using an M1 MacBook Pro

### ISSUE THREAD

**Issue by agisilaos** [desktop/desktop#13510]
### Describe the bug
Hello folks I digged in again and tried to build the project since I would like to continue making contributions to one of my favourite projects. When I follow the instructions for building the project for [Arm64](https://github.com/desktop/desktop/blob/development/docs/contributing/building-arm64.md) I get this error(s) as a result. What am I missing? I've install all required dependencies such as yarn, node, etc. 

<img width="1550" alt="Screenshot 2021-12-12 at 13 42 14" src="https://user-images.githubusercontent.com/10944108/145712693-23812813-87fc-44c6-aa5b-38aaa7b9842f.png">

**Comment by niik** [comment]
> I would like to continue making contributions to one of my favourite projects

:heart: We' love to see more contributions from you!

Paging @sergiou87 who's the only one on our team who currently builds Desktop on an M1 but some quick Googling suggests that maybe it's your installed version of Node (17.2.0) that's causing this problem. Could you try installing the [same version we're using](https://github.com/desktop/desktop/blob/development/.node-version) (14.15.1)? 

See https://github.com/desktop/desktop/blob/development/docs/contributing/setup-macos.md for more information on configuring a version manager if you'd like to use more than one version of Node on your machine.

Please let us know if that worked for you!

**Comment by sergiou87** [comment]
I'm sorry @agisilaos I think that documentation is very outdated. I will try to find the time to update it.

Meanwhile, what I do is just setting `TARGET_ARCH` and `npm_config_arch` env variables to `arm64`. You can try this out:

```bash
$ export TARGET_ARCH=arm64
$ export npm_config_arch=arm64
$ yarn install
$ yarn build:dev
$ yarn start
```

Please, give that a try and let me know if it helps!

**Comment by agisilaos** [comment]
@sergiou87 Doesn't seem to work. Will give it a go with @niik's suggestion and report back. ❤️

**Comment by agisilaos** [comment]
@niik For some reason I tried installing node version by typing `nvm install` inside desktop directory and I installed `14.15.4` not `14.15.1`.  I didn't specify a version, I expected to install the one you mentioned but that didn't happen.

 Then I followed @sergiou87 commands then and it worked. I can build the project.

**Comment by agisilaos** [comment]
@sergiou87 I can update the docs if you want. We can coordinate on that and I can open the PR when we land on the exact document updates.

**Comment by sergiou87** [comment]
It's weird that it didn't pick the version from our `.nvmrc` file 🤔 

@agisilaos that sounds good to me! I guess we don't need the step of installing arm64 dependencies anymore (I haven't used that at least FWIW), and just exporting the two new env vars and having the right node version should suffice.

**Comment by agisilaos** [comment]
Since the issue has been fixed I'm planning to close this and update the docs today.
