### ISSUE TITLE
Not able to clone 

### ISSUE THREAD

**Issue by karthikrajn** [desktop/desktop#13513]
I am not able to clone the project from the github look into the issue and solve it as soon as possible

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by karthikrajn** [comment]
when ever I try to clone the project I am facing the issue "remote: Repository not found." how to solve those issue

**Comment by niik** [comment]
Hi @karthikrajn, without a complete template or log file it's hard to speculate but the most common reason for that error is that you're either not logged in or that the user you've logged in with in GitHub Desktop doesn't have access to the repository.

**Comment by karthikrajn** [comment]
I have access to that repository and even i have logged into the github in my system n even cleared all the data in the credential manager n then tried again even facing the same issue, here is the snippet of the log file it might help.

{
  "exitCode": 128,
  "gitErrorCode": "NotAGitRepository",
  "gitCommand": "rev-parse",
  "stdout": "",
  "stderr": "fatal: not a git repository (or any of the parent directories): .git\n"
}

**Comment by karthikrajn** [comment]
Cloning into 'c:\Users\karthikraj.n\SilmaaSima2\cc-silmaasema'...
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/silmaasema/cc-silmaasema.git/'
> git status -z -u
> git clone https://github.com/silmaasema/cc-silmaasema.git c:\Users\karthikraj.n\Desktop\silmaasima\cc-silmaasema --progress
Cloning into 'c:\Users\karthikraj.n\Desktop\silmaasima\cc-silmaasema'...
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/silmaasema/cc-silmaasema.git/'

**Comment by steveward** [comment]
@karthikrajn could you upload the entire log file so that we can take a closer look?

**Comment by karthikrajn** [comment]
Validating found git in: C:\Program Files\Git\cmd\git.exe
Validating found git in: C:\Program Files (x86)\Git\cmd\git.exe
Validating found git in: C:\Program Files\Git\cmd\git.exe
Validating found git in: C:\Users\karthikraj.n\AppData\Local\Programs\Git\cmd\git.exe
Using git 2.32.0.windows.2 from C:\Users\karthikraj.n\AppData\Local\Programs\Git\cmd\git.exe
Opening repository for path='c:\Users\karthikraj.n\SilmaaSima2' failed; ex=Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "NotAGitRepository",
  "gitCommand": "rev-parse",
  "stdout": "",
  "stderr": "fatal: not a git repository (or any of the parent directories): .git\n"
}
> git clone https://github.com/silmaasema/cc-silmaasema.git c:\Users\karthikraj.n\SilmaaSima2\cc-silmaasema --progress
> git rev-parse --git-dir
Open repository: c:\Users\karthikraj.n\SilmaaSima2\cc-silmaasema
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/master refs/remotes/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git check-ignore -v -z --stdin
> git config --get commit.template
> git config --local branch.master.github-pr-owner-number
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/silmaasema/cc-silmaasema.git/'
Cloning into 'c:\Users\karthikraj.n\SilmaaSima2\cc-silmaasema'...
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/silmaasema/cc-silmaasema.git/'
> git status -z -u

**Comment by karthikrajn** [comment]
[Info] C:\Users\karthikraj.n\.ssh\config: ENOENT: no such file or directory, open 'C:\Users\karthikraj.n\.ssh\config'
[Info] Registering git provider
[Info] Looking for git repository
[Info] Found 0 repositories during activation
[Info] Waiting for git repository
[Info] Repository file:///c%3A/Users/karthikraj.n/SilmaaSima2/cc-silmaasema has been opened
[Info] Repository file:///c%3A/Users/karthikraj.n/SilmaaSima2/cc-silmaasema opened
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] No remote with name 'origin' found.
[Info] No remote with name 'upstream' found.
[Info] No GitHub remotes found
[Info] Review> Queuing additional validate state
[Info] Review> Validating state...
[Info] No remote with name 'upstream' found.
[Info] Found GitHub remote
[Info] Review> no matching pull request metadata found for current branch master
[Info] Review> no matching pull request metadata found on GitHub for current branch master

**Comment by karthikrajn** [comment]
[20211214T090744.zip](https://github.com/desktop/desktop/files/7708723/20211214T090744.zip)

**Comment by niik** [comment]
Hey @karthikrajn, that log file doesn't appear to come from GitHub Desktop, my best guess is that you're using Visual Studio Code. Could you please verify that the application you're having problems with is GitHub Desktop?

**Comment by karthikrajn** [comment]
I have a issues in github desktop as well the log file is attached as follows 
[2021-12-13.desktop.production.log](https://github.com/desktop/desktop/files/7711115/2021-12-13.desktop.production.log)
[2021-12-14.desktop.production.log](https://github.com/desktop/desktop/files/7711116/2021-12-14.desktop.production.log)
[2021-11-19.desktop.production.log](https://github.com/desktop/desktop/files/7711117/2021-11-19.desktop.production.log)

**Comment by karthikrajn** [comment]
<img width="722" alt="image" src="https://user-images.githubusercontent.com/93183838/145992835-e22f07da-e2f4-43cc-b264-474220975320.png">
