### ISSUE TITLE
PAT is not saved for Azure DevOps

### ISSUE THREAD

**Issue by laithhisham** [desktop/desktop#13537]
### Describe the bug
GitHub Desktop seems to no longer be saving the personal access token and keeps asking for credentials on each action performed on an Azure DevOps repo. The PAT is valid and using it again works, so it seems to be an issue in storing and reusing it.

### Version & OS
2.9.6 (x64), Windows 11

### Steps to reproduce the behavior
1. Clone a repo from AzureDevops.
2. Switch to a new branch and attempt to pull/push
3. Notice that you get an authentication failed popup asking for credentials to login again. This happens every once in a while.

### Expected behavior
No credentials popup should be shown and the authentication should be performed automatically. This was the behavior until recently.

### Actual behavior
A login window is shown on each operation on an Azure DevOps repo.

### Screenshots
![AuthenticationFailedPopup](https://user-images.githubusercontent.com/49263932/146138140-dab1b163-9e77-4a1e-95ec-ac0f3f88768e.png)

**Comment by niik** [comment]
Hi @laithhisham, thanks for the report! Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Explorer`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by laithhisham** [comment]
> Hi @laithhisham, thanks for the report! Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Explorer`.
> 
> The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

@niik uploaded. Thanks a lot
[GitHubDesktopLogs.txt](https://github.com/desktop/desktop/files/7719696/GitHubDesktopLogs.txt)

**Comment by steveward** [comment]
Thanks for sharing that @laithhisham. We've had previous reports of this (https://github.com/desktop/desktop/issues/9579), but I haven't been able to reproduce it myself. I just created a fresh Azure DevOps token in a test VM and I'll see if I run into any issues.

It would be helpful to know if clearing out the local cache helps -- you can follow these steps to do this:

1. Close GitHub Desktop
2. Open File Explorer to the `%AppData%\GitHub` directory
3. Delete all the files in that folder.

You'll need to log in and add your repositories again via drag-and-drop after doing this, but let me know if that helps at all.

**Comment by laithhisham** [comment]
@steveward 
Tried clearing cache but it didn't help.
I also tried reinstalling GitHub Desktop and it did not solve the issue.

**Comment by steveward** [comment]
@laithhisham is this still an issue you are encountering? I've been testing this out with my Azure DevOps account this week and haven't hit any auth failures due to a failed token yet.

**Comment by ldrick** [comment]
I can verify the same on my Github Desktop used for work. I have version 2.9.6 installed and it loses the PAT sometimes very often, sometimes it stays for couple of commits and fetches.
~~Can't really tell what triggers the loss, as it doesn't feel systematic.~~
So I played around now and found out, that once I am opening Visual Studio Code, the PAT gets lost for Github Desktop.
I have somehow the feeling the trusted Extensions in VS Code are doing something 
![image](https://user-images.githubusercontent.com/3674067/149349223-534b4d7e-b6b4-4fbb-97e1-a2b89bd00d42.png)

**Comment by laithhisham** [comment]
> I can verify the same on my Github Desktop used for work. I have version 2.9.6 installed and it loses the PAT sometimes very often, sometimes it stays for couple of commits and fetches. ~Can't really tell what triggers the loss, as it doesn't feel systematic.~ So I played around now and found out, that once I am opening Visual Studio Code, the PAT gets lost for Github Desktop. I have somehow the feeling the trusted Extensions in VS Code are doing something ![image](https://user-images.githubusercontent.com/3674067/149349223-534b4d7e-b6b4-4fbb-97e1-a2b89bd00d42.png)

I can confirm this is the case for me too. Once I close VS Code the PAT issue no longer happens

**Comment by steveward** [comment]
Thanks for the updates! I'll look into this to see if I can reproduce this with VSCode as well.

**Comment by steveward** [comment]
This should now be resolved since we provide support for Git Credential Manager.
