### ISSUE TITLE
Toolbar - 'Current Branch' control truncates many branch names

### ISSUE THREAD

**Issue by MSP-Greg** [desktop/desktop#13534]
### Describe the feature or problem you’d like to solve

Using a fork of the desktop repo, many of the branch names are truncated.  With a 4k monitor, the toolbar's 'Current Branch' control is too narrow.  Same for its drop down list.

### Proposed solution

Please allow it to resize based on window width or add a re-sizer control to it.

**Comment by steveward** [comment]
Thanks for the issue @MSP-Greg. This is being tracked in https://github.com/desktop/desktop/issues/4569, so you can subscribe there for updates.

**Comment by MSP-Greg** [comment]
> This is being tracked

Given that the issue is from May of 2018, I might say ignored.  In terms of adoption and use, adding new features only goes so far if basic UI issues aren't addressed...  \<rant off\>

**Comment by OP-EAA-MUSIC-NETWORKS** [comment]
FUCK OFF SENDING THESE

STOP TRYING TO CLONE ME
