### ISSUE TITLE
Remove restriction to size of 'Changed Files' window on desktop app MAC

### ISSUE THREAD

**Issue by PhilPercipio** [desktop/desktop#13530]
I would like to suggest removing the restrictions to the size limit of the Changed Files window on the Github desktop version. 

I often find myself trying to expand the window, especially with larger screens so that I can see the full file path and name displayed. Currently there is a hard limit on the width of the left hand window section and '...' is used to truncate the file path.

This will benefit users with longer-named file structures and those who want to display github on a much larger screen space.

Thanks for all your hard work, Merry Christmas/Happy Holidays and Many thanks! 

Phil

**Comment by niik** [comment]
Hey @PhilPercipio, thanks for reaching out. We just made a change to support much wider panels in #13439. That change is currently on our beta channel and will likely make it into the next production release. If you want to try it out right now you can install our beta version from https://github.com/desktop/desktop#beta-channel
