### ISSUE TITLE
Helper installer pegs my processer if not noticed right away

### ISSUE THREAD

**Issue by KeygenOld** [desktop/desktop#13540]
### Describe the bug
When the desktop app updater window pops up asking for credentials, if it goes unnoticed, it will spin up the CPU. I stepped away from my laptop running macOS Big Sur and when I came back the fans were going nuts. Checking activity monitor showed it was using 99.9% CPU.

### Version & OS

GitHub Desktop 2.9.5 (after today's update)
macOS Big Sur 11.6

### Steps to reproduce the behavior

Just let the window asking for admin name and password sit there for a while.

### Expected behavior

It won't peg my processor.

### Actual behavior

It fries the CPU.

### Screenshots

N/A

**Comment by steveward** [comment]
Thanks for the report @KeygenLLC, I'm going to add this to https://github.com/desktop/desktop/issues/5789 where we are tracking these issues.
