### ISSUE TITLE
Creating Repository

### ISSUE THREAD

**Issue by Hepworthg** [desktop/desktop#13546]
Hi, i have been struggling for 2 days now so before my head explodes, kindly assist with my problem, I have attached the screenshots of where I am stuck, and moving forward will make my day brighter, I am so emotional now that I feel like crying but giving up is not an option, kindly help.

1. I am here

![Screenshot (36)](https://user-images.githubusercontent.com/96171718/146386777-553853c8-614f-401e-b516-2b57f680d44e.png)

2. Struggling to get here

![Screenshot 2021-12-16 120621 (2)](https://user-images.githubusercontent.com/96171718/146352841-dc82b15d-38f3-4976-9481-81da0c262042.png)

3. To here

![Screenshot 2021-12-16 120706](https://user-images.githubusercontent.com/96171718/146354044-79583a44-7fc9-48c8-ae5d-475eaacf0ed5.png)

I hope I have explained myself clearly, thank you in advance.

**Comment by Hepworthg** [comment]
I have been struggling for 2 days and before I have been enjoying the pre working assignments

**Comment by steveward** [comment]
@Hepworthg thanks for the issue. This issue tracker is for [GitHub Desktop](http://desktop.github.com). If you have questions about using the command line I'd recommend reaching out for help at https://github.community, or taking a look at GitHub's [help documentation](https://docs.github.com/en/get-started).

If you are interested in using GitHub Desktop to work with your repository we have a helpful [getting started guide](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/overview/getting-started-with-github-desktop#introduction).

Let me know if you have any questions.
