### ISSUE TITLE
3d objects not working

### ISSUE THREAD

**Issue by JoachimBrandenburg** [desktop/desktop#13545]
### Describe the bug
When creating any 3d related object or fixture

### 21H1 Windows 10 Pro
Github Version 2.9.6 (x64)

Processor	AMD Ryzen 7 3800X 8-Core Processor                3.89 GHz
Installed RAM	15,9 GB
Graphics Radeon RX 570 Driver version 30.0.14011.3017

### Steps to reproduce the behavior

1. Go to 'Create'
2. Click on 'objects then Primitive or import Geo' or "Geometry"

### Expected behavior

Adding Primitive, Object or Geometry

### Actual behavior

Red and/or blue viewport  or when clicking 'Geometry' a complete freeze

### Screenshots

![GeoPix ImportGeo](https://user-images.githubusercontent.com/96195240/146363318-fde32ebe-b75b-4b66-8ac8-5af6b91a429f.JPG)
![GeoPix Prim](https://user-images.githubusercontent.com/96195240/146363320-be5064ff-861d-49d2-8d2c-70c6723364dc.JPG)

### Logs From Errors and Diagnostics (first System then GLSL)
======= Newest Errors at the Top =======

SOURCE: COMP : 3 : /UberGui/CustomFixtureEditor/container_Channels
ERROR: (1) TypeError: float() argument must be a string or a number, not 'NoneType'
Context:(Parameter: Offset)

SOURCE: COMP : 3 : /UberGui/UiMapper/Body/Drivers/driverMaps/driverPoolScrollable/container1_template
ERROR: (9) TypeError: float() argument must be a string or a number, not 'NoneType'
Context:(Parameter: Background Color)

+++++++++++++++
/UberGui/CustomFixtureEditor/Viewer/FROXEL_BLOCK/geo_AABB_Froxel_Block/glsl_light_CULL_shader
+++++++++++++++

=============

Vertex Shader Compile Results: 
Vertex shader failed to compile with the following errors:
ERROR: 0:12: error(#110) Invalid Directive: include
ERROR: 0:13: error(#110) Invalid Directive: include
ERROR: 0:48: error(#143) Undeclared identifier: RetrieveLightType
ERROR: 0:48: error(#202) No matching overloaded function found: RetrieveLightType
ERROR: 0:48: error(#160) Cannot convert from: "const float" to: "highp unsigned int"
ERROR: 0:52: error(#143) Undeclared identifier: testAABB_PointLight
ERROR: 0:52: error(#202) No matching overloaded function found: testAABB_PointLight
ERROR: 0:67: error(#143) Undeclared identifier: testAABB_ConeLight
ERROR: 0:67: error(#202) No matching overloaded function found: testAABB_ConeLight
ERROR: error(#273) 9 compilation errors.  No code generated

=============

=============

=============

Pixel Shader Compile Results: 

Compiled Successfully

=============

=============

Program Link Results: 
Vertex shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 

+++++++++++++++
/UberGui/CustomFixtureEditor/Viewer/FROXEL_BLOCK/geo_AABB_Froxel_Block/glsl_light_CULL_shader
+++++++++++++++

=============

Vertex Shader Compile Results: 
Vertex shader failed to compile with the following errors:
ERROR: 0:12: error(#110) Invalid Directive: include
ERROR: 0:13: error(#110) Invalid Directive: include
ERROR: 0:48: error(#143) Undeclared identifier: RetrieveLightType
ERROR: 0:48: error(#202) No matching overloaded function found: RetrieveLightType
ERROR: 0:48: error(#160) Cannot convert from: "const float" to: "highp unsigned int"
ERROR: 0:52: error(#143) Undeclared identifier: testAABB_PointLight
ERROR: 0:52: error(#202) No matching overloaded function found: testAABB_PointLight
ERROR: 0:67: error(#143) Undeclared identifier: testAABB_ConeLight
ERROR: 0:67: error(#202) No matching overloaded function found: testAABB_ConeLight
ERROR: error(#273) 9 compilation errors.  No code generated

=============

=============

=============

Pixel Shader Compile Results: 

Compiled Successfully

=============

=============

Program Link Results: 
Vertex shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 

+++++++++++++++
/UberGui/CustomFixtureEditor/Viewer/FROXEL_BLOCK/geo_AABB_Froxel_Block/glsl_light_CULL_shader
+++++++++++++++

=============

Vertex Shader Compile Results: 
Vertex shader failed to compile with the following errors:
ERROR: 0:12: error(#110) Invalid Directive: include
ERROR: 0:13: error(#110) Invalid Directive: include
ERROR: 0:48: error(#143) Undeclared identifier: RetrieveLightType
ERROR: 0:48: error(#202) No matching overloaded function found: RetrieveLightType
ERROR: 0:48: error(#160) Cannot convert from: "const float" to: "highp unsigned int"
ERROR: 0:52: error(#143) Undeclared identifier: testAABB_PointLight
ERROR: 0:52: error(#202) No matching overloaded function found: testAABB_PointLight
ERROR: 0:67: error(#143) Undeclared identifier: testAABB_ConeLight
ERROR: 0:67: error(#202) No matching overloaded function found: testAABB_ConeLight
ERROR: error(#273) 9 compilation errors.  No code generated

=============

=============

=============

Pixel Shader Compile Results: 

Compiled Successfully

=============

=============

Program Link Results: 
Vertex shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 

+++++++++++++++
/UberGui/CustomFixtureEditor/Viewer/FROXEL_BLOCK/geo_AABB_Froxel_Block/glsl_light_CULL_shader
+++++++++++++++

=============

Vertex Shader Compile Results: 
Vertex shader failed to compile with the following errors:
ERROR: 0:12: error(#110) Invalid Directive: include
ERROR: 0:13: error(#110) Invalid Directive: include
ERROR: 0:48: error(#143) Undeclared identifier: RetrieveLightType
ERROR: 0:48: error(#202) No matching overloaded function found: RetrieveLightType
ERROR: 0:48: error(#160) Cannot convert from: "const float" to: "highp unsigned int"
ERROR: 0:52: error(#143) Undeclared identifier: testAABB_PointLight
ERROR: 0:52: error(#202) No matching overloaded function found: testAABB_PointLight
ERROR: 0:67: error(#143) Undeclared identifier: testAABB_ConeLight
ERROR: 0:67: error(#202) No matching overloaded function found: testAABB_ConeLight
ERROR: error(#273) 9 compilation errors.  No code generated

=============

=============

=============

Pixel Shader Compile Results: 

Compiled Successfully

=============

=============

Program Link Results: 
Vertex shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 

+++++++++++++++
/UberGui/CustomFixtureEditor/Viewer/FROXEL_BLOCK/geo_AABB_Froxel_Block/glsl_light_CULL_shader
+++++++++++++++

=============

Vertex Shader Compile Results: 
Vertex shader failed to compile with the following errors:
ERROR: 0:12: error(#110) Invalid Directive: include
ERROR: 0:13: error(#110) Invalid Directive: include
ERROR: 0:48: error(#143) Undeclared identifier: RetrieveLightType
ERROR: 0:48: error(#202) No matching overloaded function found: RetrieveLightType
ERROR: 0:48: error(#160) Cannot convert from: "const float" to: "highp unsigned int"
ERROR: 0:52: error(#143) Undeclared identifier: testAABB_PointLight
ERROR: 0:52: error(#202) No matching overloaded function found: testAABB_PointLight
ERROR: 0:67: error(#143) Undeclared identifier: testAABB_ConeLight
ERROR: 0:67: error(#202) No matching overloaded function found: testAABB_ConeLight
ERROR: error(#273) 9 compilation errors.  No code generated

=============

=============

=============

Pixel Shader Compile Results: 

Compiled Successfully

=============

=============

Program Link Results: 
Vertex shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 

+++++++++++++++
/UberGui/CustomFixtureEditor/Viewer/FROXEL_BLOCK/geo_AABB_Froxel_Block/glsl_light_CULL_shader
+++++++++++++++

=============

Vertex Shader Compile Results: 
Vertex shader failed to compile with the following errors:
ERROR: 0:12: error(#110) Invalid Directive: include
ERROR: 0:13: error(#110) Invalid Directive: include
ERROR: 0:48: error(#143) Undeclared identifier: RetrieveLightType
ERROR: 0:48: error(#202) No matching overloaded function found: RetrieveLightType
ERROR: 0:48: error(#160) Cannot convert from: "const float" to: "highp unsigned int"
ERROR: 0:52: error(#143) Undeclared identifier: testAABB_PointLight
ERROR: 0:52: error(#202) No matching overloaded function found: testAABB_PointLight
ERROR: 0:67: error(#143) Undeclared identifier: testAABB_ConeLight
ERROR: 0:67: error(#202) No matching overloaded function found: testAABB_ConeLight
ERROR: error(#273) 9 compilation errors.  No code generated

=============

=============

=============

Pixel Shader Compile Results: 

Compiled Successfully

=============

=============

Program Link Results: 
Vertex shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 

+++++++++++++++
/UberGui/CustomFixtureEditor/Viewer/FROXEL_BLOCK/geo_AABB_Froxel_Block/glsl_light_CULL_shader
+++++++++++++++

=============

Vertex Shader Compile Results: 
Vertex shader failed to compile with the following errors:
ERROR: 0:12: error(#110) Invalid Directive: include
ERROR: 0:13: error(#110) Invalid Directive: include
ERROR: 0:48: error(#143) Undeclared identifier: RetrieveLightType
ERROR: 0:48: error(#202) No matching overloaded function found: RetrieveLightType
ERROR: 0:48: error(#160) Cannot convert from: "const float" to: "highp unsigned int"
ERROR: 0:52: error(#143) Undeclared identifier: testAABB_PointLight
ERROR: 0:52: error(#202) No matching overloaded function found: testAABB_PointLight
ERROR: 0:67: error(#143) Undeclared identifier: testAABB_ConeLight
ERROR: 0:67: error(#202) No matching overloaded function found: testAABB_ConeLight
ERROR: error(#273) 9 compilation errors.  No code generated

=============

=============

=============

Pixel Shader Compile Results: 

Compiled Successfully

=============

=============

Program Link Results: 
Vertex shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 

+++++++++++++++
/UberGui/CustomFixtureEditor/Viewer/FROXEL_BLOCK/geo_AABB_Froxel_Block/glsl_light_CULL_shader
+++++++++++++++

=============

Vertex Shader Compile Results: 
Vertex shader failed to compile with the following errors:
ERROR: 0:12: error(#110) Invalid Directive: include
ERROR: 0:13: error(#110) Invalid Directive: include
ERROR: 0:48: error(#143) Undeclared identifier: RetrieveLightType
ERROR: 0:48: error(#202) No matching overloaded function found: RetrieveLightType
ERROR: 0:48: error(#160) Cannot convert from: "const float" to: "highp unsigned int"
ERROR: 0:52: error(#143) Undeclared identifier: testAABB_PointLight
ERROR: 0:52: error(#202) No matching overloaded function found: testAABB_PointLight
ERROR: 0:67: error(#143) Undeclared identifier: testAABB_ConeLight
ERROR: 0:67: error(#202) No matching overloaded function found: testAABB_ConeLight
ERROR: error(#273) 9 compilation errors.  No code generated

=============

=============

=============

Pixel Shader Compile Results: 

Compiled Successfully

=============

=============

Program Link Results: 
Vertex shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 

+++++++++++++++
/UberGui/CustomFixtureEditor/Viewer/FROXEL_BLOCK/geo_AABB_Froxel_Block/glsl_light_CULL_shader
+++++++++++++++

=============

Vertex Shader Compile Results: 
Vertex shader failed to compile with the following errors:
ERROR: 0:12: error(#110) Invalid Directive: include
ERROR: 0:13: error(#110) Invalid Directive: include
ERROR: 0:48: error(#143) Undeclared identifier: RetrieveLightType
ERROR: 0:48: error(#202) No matching overloaded function found: RetrieveLightType
ERROR: 0:48: error(#160) Cannot convert from: "const float" to: "highp unsigned int"
ERROR: 0:52: error(#143) Undeclared identifier: testAABB_PointLight
ERROR: 0:52: error(#202) No matching overloaded function found: testAABB_PointLight
ERROR: 0:67: error(#143) Undeclared identifier: testAABB_ConeLight
ERROR: 0:67: error(#202) No matching overloaded function found: testAABB_ConeLight
ERROR: error(#273) 9 compilation errors.  No code generated

=============

=============

=============

Pixel Shader Compile Results: 

Compiled Successfully

=============

=============

Program Link Results: 
Vertex shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 

+++++++++++++++
/UberGui/CustomFixtureEditor/Viewer/FROXEL_BLOCK/geo_AABB_Froxel_Block/glsl_light_CULL_shader
+++++++++++++++

=============

Vertex Shader Compile Results: 
Vertex shader failed to compile with the following errors:
ERROR: 0:12: error(#110) Invalid Directive: include
ERROR: 0:13: error(#110) Invalid Directive: include
ERROR: 0:48: error(#143) Undeclared identifier: RetrieveLightType
ERROR: 0:48: error(#202) No matching overloaded function found: RetrieveLightType
ERROR: 0:48: error(#160) Cannot convert from: "const float" to: "highp unsigned int"
ERROR: 0:52: error(#143) Undeclared identifier: testAABB_PointLight
ERROR: 0:52: error(#202) No matching overloaded function found: testAABB_PointLight
ERROR: 0:67: error(#143) Undeclared identifier: testAABB_ConeLight
ERROR: 0:67: error(#202) No matching overloaded function found: testAABB_ConeLight
ERROR: error(#273) 9 compilation errors.  No code generated

=============

=============

=============

Pixel Shader Compile Results: 

Compiled Successfully

=============

=============

Program Link Results: 
Vertex shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 

+++++++++++++++
/UberGui/CustomFixtureEditor/Viewer/FROXEL_BLOCK/geo_AABB_Froxel_Block/glsl_light_CULL_shader
+++++++++++++++

=============

Vertex Shader Compile Results: 
Vertex shader failed to compile with the following errors:
ERROR: 0:12: error(#110) Invalid Directive: include
ERROR: 0:13: error(#110) Invalid Directive: include
ERROR: 0:48: error(#143) Undeclared identifier: RetrieveLightType
ERROR: 0:48: error(#202) No matching overloaded function found: RetrieveLightType
ERROR: 0:48: error(#160) Cannot convert from: "const float" to: "highp unsigned int"
ERROR: 0:52: error(#143) Undeclared identifier: testAABB_PointLight
ERROR: 0:52: error(#202) No matching overloaded function found: testAABB_PointLight
ERROR: 0:67: error(#143) Undeclared identifier: testAABB_ConeLight
ERROR: 0:67: error(#202) No matching overloaded function found: testAABB_ConeLight
ERROR: error(#273) 9 compilation errors.  No code generated

=============

=============

=============

Pixel Shader Compile Results: 

Compiled Successfully

=============

=============

Program Link Results: 
Vertex shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 

+++++++++++++++
/UberGui/CustomFixtureEditor/Viewer/FROXEL_BLOCK/geo_AABB_Froxel_Block/glsl_light_CULL_shader
+++++++++++++++

=============

Vertex Shader Compile Results: 
Vertex shader failed to compile with the following errors:
ERROR: 0:12: error(#110) Invalid Directive: include
ERROR: 0:13: error(#110) Invalid Directive: include
ERROR: 0:48: error(#143) Undeclared identifier: RetrieveLightType
ERROR: 0:48: error(#202) No matching overloaded function found: RetrieveLightType
ERROR: 0:48: error(#160) Cannot convert from: "const float" to: "highp unsigned int"
ERROR: 0:52: error(#143) Undeclared identifier: testAABB_PointLight
ERROR: 0:52: error(#202) No matching overloaded function found: testAABB_PointLight
ERROR: 0:67: error(#143) Undeclared identifier: testAABB_ConeLight
ERROR: 0:67: error(#202) No matching overloaded function found: testAABB_ConeLight
ERROR: error(#273) 9 compilation errors.  No code generated

=============

=============

=============

Pixel Shader Compile Results: 

Compiled Successfully

=============

=============

Program Link Results: 
Vertex shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 

+++++++++++++++
/UberGui/CustomFixtureEditor/Viewer/FROXEL_BLOCK/geo_AABB_Froxel_Block/glsl_light_CULL_shader
+++++++++++++++

=============

Vertex Shader Compile Results: 
Vertex shader failed to compile with the following errors:
ERROR: 0:12: error(#110) Invalid Directive: include
ERROR: 0:13: error(#110) Invalid Directive: include
ERROR: 0:48: error(#143) Undeclared identifier: RetrieveLightType
ERROR: 0:48: error(#202) No matching overloaded function found: RetrieveLightType
ERROR: 0:48: error(#160) Cannot convert from: "const float" to: "highp unsigned int"
ERROR: 0:52: error(#143) Undeclared identifier: testAABB_PointLight
ERROR: 0:52: error(#202) No matching overloaded function found: testAABB_PointLight
ERROR: 0:67: error(#143) Undeclared identifier: testAABB_ConeLight
ERROR: 0:67: error(#202) No matching overloaded function found: testAABB_ConeLight
ERROR: error(#273) 9 compilation errors.  No code generated

=============

=============

=============

Pixel Shader Compile Results: 

Compiled Successfully

=============

=============

Program Link Results: 
Vertex shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 

+++++++++++++++
/UberGui/CustomFixtureEditor/Viewer/FROXEL_BLOCK/geo_AABB_Froxel_Block/glsl_light_CULL_shader
+++++++++++++++

=============

Vertex Shader Compile Results: 
Vertex shader failed to compile with the following errors:
ERROR: 0:12: error(#110) Invalid Directive: include
ERROR: 0:13: error(#110) Invalid Directive: include
ERROR: 0:48: error(#143) Undeclared identifier: RetrieveLightType
ERROR: 0:48: error(#202) No matching overloaded function found: RetrieveLightType
ERROR: 0:48: error(#160) Cannot convert from: "const float" to: "highp unsigned int"
ERROR: 0:52: error(#143) Undeclared identifier: testAABB_PointLight
ERROR: 0:52: error(#202) No matching overloaded function found: testAABB_PointLight
ERROR: 0:67: error(#143) Undeclared identifier: testAABB_ConeLight
ERROR: 0:67: error(#202) No matching overloaded function found: testAABB_ConeLight
ERROR: error(#273) 9 compilation errors.  No code generated

=============

=============

=============

Pixel Shader Compile Results: 

Compiled Successfully

=============

=============

Program Link Results: 
Vertex shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 

+++++++++++++++
/UberGui/CustomFixtureEditor/Viewer/FROXEL_BLOCK/geo_AABB_Froxel_Block/glsl_light_CULL_shader
+++++++++++++++

=============

Vertex Shader Compile Results: 
Vertex shader failed to compile with the following errors:
ERROR: 0:12: error(#110) Invalid Directive: include
ERROR: 0:13: error(#110) Invalid Directive: include
ERROR: 0:48: error(#143) Undeclared identifier: RetrieveLightType
ERROR: 0:48: error(#202) No matching overloaded function found: RetrieveLightType
ERROR: 0:48: error(#160) Cannot convert from: "const float" to: "highp unsigned int"
ERROR: 0:52: error(#143) Undeclared identifier: testAABB_PointLight
ERROR: 0:52: error(#202) No matching overloaded function found: testAABB_PointLight
ERROR: 0:67: error(#143) Undeclared identifier: testAABB_ConeLight
ERROR: 0:67: error(#202) No matching overloaded function found: testAABB_ConeLight
ERROR: error(#273) 9 compilation errors.  No code generated

=============

=============

=============

Pixel Shader Compile Results: 

Compiled Successfully

=============

=============

Program Link Results: 
Vertex shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 

+++++++++++++++
/UberGui/CustomFixtureEditor/Viewer/FROXEL_BLOCK/geo_AABB_Froxel_Block/glsl_light_CULL_shader
+++++++++++++++

=============

Vertex Shader Compile Results: 
Vertex shader failed to compile with the following errors:
ERROR: 0:12: error(#110) Invalid Directive: include
ERROR: 0:13: error(#110) Invalid Directive: include
ERROR: 0:48: error(#143) Undeclared identifier: RetrieveLightType
ERROR: 0:48: error(#202) No matching overloaded function found: RetrieveLightType
ERROR: 0:48: error(#160) Cannot convert from: "const float" to: "highp unsigned int"
ERROR: 0:52: error(#143) Undeclared identifier: testAABB_PointLight
ERROR: 0:52: error(#202) No matching overloaded function found: testAABB_PointLight
ERROR: 0:67: error(#143) Undeclared identifier: testAABB_ConeLight
ERROR: 0:67: error(#202) No matching overloaded function found: testAABB_ConeLight
ERROR: error(#273) 9 compilation errors.  No code generated

=============

=============

=============

Pixel Shader Compile Results: 

Compiled Successfully

=============

=============

Program Link Results: 
Vertex shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 

+++++++++++++++
/UberGui/CustomFixtureEditor/Viewer/FROXEL_BLOCK/geo_AABB_Froxel_Block/glsl_light_CULL_shader
+++++++++++++++

=============

Vertex Shader Compile Results: 
Vertex shader failed to compile with the following errors:
ERROR: 0:12: error(#110) Invalid Directive: include
ERROR: 0:13: error(#110) Invalid Directive: include
ERROR: 0:48: error(#143) Undeclared identifier: RetrieveLightType
ERROR: 0:48: error(#202) No matching overloaded function found: RetrieveLightType
ERROR: 0:48: error(#160) Cannot convert from: "const float" to: "highp unsigned int"
ERROR: 0:52: error(#143) Undeclared identifier: testAABB_PointLight
ERROR: 0:52: error(#202) No matching overloaded function found: testAABB_PointLight
ERROR: 0:67: error(#143) Undeclared identifier: testAABB_ConeLight
ERROR: 0:67: error(#202) No matching overloaded function found: testAABB_ConeLight
ERROR: error(#273) 9 compilation errors.  No code generated

=============

=============

=============

Pixel Shader Compile Results: 

Compiled Successfully

=============

=============

Program Link Results: 
Vertex shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 

+++++++++++++++
/UberGui/CustomFixtureEditor/Viewer/FROXEL_BLOCK/geo_AABB_Froxel_Block/glsl_light_CULL_shader
+++++++++++++++

=============

Vertex Shader Compile Results: 
Vertex shader failed to compile with the following errors:
ERROR: 0:12: error(#110) Invalid Directive: include
ERROR: 0:13: error(#110) Invalid Directive: include
ERROR: 0:48: error(#143) Undeclared identifier: RetrieveLightType
ERROR: 0:48: error(#202) No matching overloaded function found: RetrieveLightType
ERROR: 0:48: error(#160) Cannot convert from: "const float" to: "highp unsigned int"
ERROR: 0:52: error(#143) Undeclared identifier: testAABB_PointLight
ERROR: 0:52: error(#202) No matching overloaded function found: testAABB_PointLight
ERROR: 0:67: error(#143) Undeclared identifier: testAABB_ConeLight
ERROR: 0:67: error(#202) No matching overloaded function found: testAABB_ConeLight
ERROR: error(#273) 9 compilation errors.  No code generated

=============

=============

=============

Pixel Shader Compile Results: 

Compiled Successfully

=============

=============

Program Link Results: 
Vertex shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed. 

+++++++++++++++
/UberGui/CustomFixtureEditor/Viewer/FROXEL_BLOCK/geo_AABB_Froxel_Block/glsl_light_CULL_shader
+++++++++++++++

=============

Vertex Shader Compile Results: 
Vertex shader failed to compile with the following errors:
ERROR: 0:12: error(#110) Invalid Directive: include
ERROR: 0:13: error(#110) Invalid Directive: include
ERROR: 0:48: error(#143) Undeclared identifier: RetrieveLightType
ERROR: 0:48: error(#202) No matching overloaded function found: RetrieveLightType
ERROR: 0:48: error(#160) Cannot convert from: "const float" to: "highp unsigned int"
ERROR: 0:52: error(#143) Undeclared identifier: testAABB_PointLight
ERROR: 0:52: error(#202) No matching overloaded function found: testAABB_PointLight
ERROR: 0:67: error(#143) Undeclared identifier: testAABB_ConeLight
ERROR: 0:67: error(#202) No matching overloaded function found: testAABB_ConeLight
ERROR: error(#273) 9 compilation errors.  No code generated

=============

=============

=============

Pixel Shader Compile Results: 

Compiled Successfully

=============

=============

Program Link Results: 
Vertex shader(s) were not successfully compiled before glLinkProgram() was called.  Link failed.

**Comment by sergiou87** [comment]
I'm sorry @JoachimBrandenburg but I think this bug should be reported in https://github.com/EnviralDesign/GeoPix/issues
