### ISSUE TITLE
Feature request: command palette

### ISSUE THREAD

**Issue by KishanBagaria** [desktop/desktop#13549]
All actions in the app should be accessible through a command palette, accessed through the ⌘ K hotkey – similar to GitHub.com, VS Code, Sublime Text.

**Comment by steveward** [comment]
Thanks for the request @KishanBagaria. Adding a command palette has been [previously discussed](https://github.com/desktop/desktop/issues/3050#issuecomment-462493209), but at this time is out of the scope of what we want to focus on in GitHub Desktop. In the future this may be something we consider again, so thanks for letting us know you're interested in this feature.
