### ISSUE TITLE
Changes displays existing files as 'added'

### ISSUE THREAD

**Issue by Peaj** [desktop/desktop#13551]
### Describe the bug
The changes tab displays some files as 'added' that are already tracked and did not change.
When trying to commit these 'added' files it fails because no changes have been staged (see screenshot)
When discaring the changes they will show up again after some time.

### Version & OS

Version: 2.9.6 (x64)
OS: Windows

### Steps to reproduce the behavior

The issue is sporadic. I am unsure what causes the files to mistakenly show up as 'added'

### Expected behavior

Existing tracked files should not be displayed as 'added'
In the example the Changes tab should only display the single valid change to the 'Virtual Screen.cs' file

### Actual behavior

Already existing and tracked files are displayed as 'added'

### Screenshots

![grafik](https://user-images.githubusercontent.com/3155116/146539983-22b2f9ca-46dc-49b8-a528-6d8c94ebc1e7.png)

### Logs

[2021-12-17.desktop.production.log](https://github.com/desktop/desktop/files/7734857/2021-12-17.desktop.production.log)

### Additional Context
The files vanished from the change list after taking the screenshot with the snapping tool

**Comment by steveward** [comment]
@Peaj thanks for the issue. Is this a Unity project? Based on some quick searching it looks like those `.meta` files can get changed automatically by Unity, but I'm not very familiar with Unity itself. I'd recommend reaching out to them for assistance. 

Let me know if i'm off base here and we can dig into this further.

**Comment by Peaj** [comment]
@steveward yes you are correct this is a Unity project. Sry for omitting this detail.
You are also right that .meta files have their quirks and may be changed unintentionally.

In this case I am pretty sure that this is (at least partly) a GitHub Desktop bug though.
The files have already been tracked by git.
So there is something wrong with them being shown as added.
The error message also shows that these changes are not actually staged.

As a side note: Unity does not do anything git related (e.g. staging files). It just creates and changes files.

**Comment by steveward** [comment]
@Peaj can you share the full output of `git status` from the command line? GitHub Desktop handles things differently -- it doesn't actually stage your files (see https://github.com/desktop/desktop/issues/4475#issuecomment-385422905).

**Comment by Peaj** [comment]
I am afraid the repo isnt in this state anymore. So a `git status` wouldnt help much.
If this happens again I will make sure to post the `git status` output here.

**Comment by steveward** [comment]
Thanks for the update @Peaj. I'm going to close this out but we can reopen if you run into this again.
