### ISSUE TITLE
GUI application of GitHub for Linux

### ISSUE THREAD

**Issue by FahimFBA** [desktop/desktop#13557]
### Describe the feature or problem you’d like to solve

Hello, the windows users and the Mac users can use the native GitHub Desktop application which we, the Linux users can't. Although there is an app in flatpak, but that doesn't work.

### Proposed solution

Please provide an official GUI application for Linux.

### Additional context

Not applicable for this issue.

**Comment by GrahamSH-LLK** [comment]
Duplicate of #1525

**Comment by FahimFBA** [comment]
Oh! I am extremely sorry for this. Thanks a lot for pointing that out.
