### ISSUE TITLE
I can't push to github

### ISSUE THREAD

**Issue by z0z0r4** [desktop/desktop#13567]
Like this,I don't know why.That's Version 2.9.6.
![image](https://user-images.githubusercontent.com/78744121/146877703-d19e5bf7-2820-461d-9f7b-33d4a7ef6316.png)

**Comment by z0z0r4** [comment]
need help!

**Comment by steveward** [comment]
Thanks for the issue @z0z0r4. Could you upload the log file from GitHub Desktop so that I could get some more information about this error?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs Explorer`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by z0z0r4** [comment]
ok , here is it.
I install desktop on windows server 2019 firist time and met this bug
may be this is that error

`2021-12-21T05:39:59.969Z - error: [ui] `git -c credential.helper= -c protocol.version=2 push origin main --set-upstream --progress` exited with an unexpected code: 128.
stderr:
error: cannot spawn C:\Users\Administrator\AppData\Local\GitHubDesktop\app-2.9.6\resources\app\static\ask-pass-trampoline.bat: No such file or directory
fatal: could not read Username for 'https://github.com': terminal prompts disabled`

AMD 5800x
32GB memory
[2021-12-21.desktop.production.log](https://github.com/desktop/desktop/files/7760241/2021-12-21.desktop.production.log)

**Comment by steveward** [comment]
@z0z0r4 we don't officially support Windows Server with GitHub Desktop -- is there a specific reason you are using that vs. a standard Windows 10/11 installation? Are you running any antivirus/security software on this machine that could be interfering with GitHub Desktop?

**Comment by z0z0r4** [comment]
There aren't any any antivirus/security software
I need Github desktop on windows server,Because I need to push my blog  to GitHub on VPS, Windows 11/10 cannot be installed on VPS
Can Github Desktop support windows server?
