### ISSUE TITLE
GitHub Desktop v2.9.6 on MacOS

### ISSUE THREAD

**Issue by HarshalCapgemini** [desktop/desktop#13571]
Branches created from Github Desktop App with say with name "feature/test", automatically updates it's first letter and makes it like "Feature/test".

Need help to resolve this as it is creating unnecessary two branches on Website.

**Comment by steveward** [comment]
Thanks for the issue @HarshalCapgemini. This isn't a specific bug with GitHub Desktop -- see [this explanation](https://github.com/desktop/desktop/issues/10621#issuecomment-696783727) for why this is happening and how you can resolve it. I hope that helps!
