### ISSUE TITLE
Dropdown features of a repository doesn't work, while it's being cloned

### ISSUE THREAD

**Issue by maifeeulasad** [desktop/desktop#13572]
### Describe the bug
When a repo is being cloned, clicking on dropdown options doesn't work.

### Version & OS
Version 2.9.6 (x64)
Microsoft Windows 10 Home - Version 21H2 - Build 19044.1415

### Steps to reproduce the behavior

- Starting cloning a huge repo
- When being cloned click on, left panel
- Find that repo, right-click on it
- Click anything from that dropdown, nothing will work

### Expected behavior

They should work, or at least be disabled

### Actual behavior

Dropdown with no functionality

### Screenshots

[!video representation](https://user-images.githubusercontent.com/29339330/146995398-dd0aa9d7-37b3-4d48-a499-2da35ea56ea8.mp4)

### Logs

*not applicable*

### Additional context

I guess I can get assigned to this 😄

**Comment by steveward** [comment]
@maifeeulasad thanks for the issue -- I tested this out and was unable to reproduce the issue. Selected actions from the context menu immediately worked when cloning a large repository. For reference I tested this out on both macOS and Windows. 

Could you take a look at Task Manager and see if your CPU usage is spiking during a clone operation?

**Comment by nomanalir** [comment]
> ### Describe the bug
> 
> When a repo is being cloned, clicking on dropdown options doesn't work.
> ### Version & OS
> 
> Version 2.9.6 (x64) Microsoft Windows 10 Home - Version 21H2 - Build 19044.1415
> ### Steps to reproduce the behavior
> 
>     * Starting cloning a huge repo
> 
>     * When being cloned click on, left panel
> 
>     * Find that repo, right-click on it
> 
>     * Click anything from that dropdown, nothing will work
> 
> 
> ### Expected behavior
> 
> They should work, or at least be disabled
> ### Actual behavior
> 
> Dropdown with no functionality
> ### Screenshots
> github_issue.mp4
> ### Logs
> 
> _not applicable_
> ### Additional context
> 
> I guess I can get assigned to this 😄

**Comment by maifeeulasad** [comment]
@steveward there was a spike in CPU usage sometimes while cloning, sometimes not. But the results were still the same.

**Comment by steveward** [comment]
@maifeeulasad is this still an issue you're experiencing? I have not seen any further reports and have been unable to reproduce this, so I'm hoping an update may have fixed things for you.

**Comment by maifeeulasad** [comment]
@steveward I tried reproducing it, but couldn't.
