### ISSUE TITLE
Very Slow Performance since 2.9.6 update

### ISSUE THREAD

**Issue by Benoit1980** [desktop/desktop#13586]
### Describe the bug
I am having a massive slow down in the entire UI. I disabled all my security, same issue. The fetch takes ages, when moving my mouse over menus, the UI takes 2 or 3 seconds to respond. I did not get this issue with the 2.9.5 version. Where can I download the old 2.9.5 MSI please?

I tried to redownload the 2.9.6 but same issue.

### Version & OS

Version 2.9.6 of Git desktop
On Windows 10 64Bit Build 19044

### Logs
This error shows in the log:
error: [ui] Highlighter worked failed for old contents
Error: timed out  at C:\Users\user\AppData\Local\GitHubDesktop\app-2.9.6\webpack:\app\src\lib\highlighter\worker.ts:85:14
error: [ui] Highlighter worked failed for new contents
Error: timed out at C:\Users\user\AppData\Local\GitHubDesktop\app-2.9.6\webpack:\app\src\lib\highlighter\worker.ts:85:14

**Comment by popcron** [comment]
Im experiencing a similar (if not the same) issue, somtimes when opening ghd it wouldnt show up and it would stay running in the background with a high power usage trend.

**Comment by narethi** [comment]
I am seeing the same issue, I have checked a few older topics and did a reinstall and turned off my firewall and I am still having this issue.

It takes around 30 seconds to switch selected files, and after the selection change completes, the detail view doesn't always change to match the newly made selection.

Version 2.9.6 of GitHub desktop
On Windows 10 Pro 64Bit Build 19043

*EDIT* Turning off auto fetch has made the application usable, but its still not very responsive (maybe like 5 or so seconds to switch files). Also all application menus (File, Edit, View, Repository, etc.) are incredibly slow to open.

**Comment by Benoit1980** [comment]
Do you both also see the same error as the one I see above?
Help>>Show log in explorer>>Select the latest file

Could it be the colour highlighter library that we see in the right-side panel that causes the issue?
webpack:\app\src\lib\highlighter\worker.ts:

**Comment by Benoit1980** [comment]
Anyone knows if there is an MSI file to go back with the 2.9.5 version please as this slow down is killing my development speed. Thanks

**Comment by rolivhuwa-03** [comment]
> I am seeing the same issue, I have checked a few older topics and did a reinstall and turned off my firewall and I am still having this issue.
> 
> It takes around 30 seconds to switch selected files, and after the selection change completes, the detail view doesn't always change to match the newly made selection.
> 
> Version 2.9.6 of GitHub desktop
> On Windows 10 Pro 64Bit Build 19043
> 
> *EDIT* Turning off auto fetch has made the application usable, but its still not very responsive (maybe like 5 or so seconds to switch files). Also all application menus (File, Edit, View, Repository, etc.) are incredibly slow to open. 

It's might be thy the software does not work with your device.try a different app or file.

**Comment by Benoit1980** [comment]
> > I am seeing the same issue, I have checked a few older topics and did a reinstall and turned off my firewall and I am still having this issue.
> > It takes around 30 seconds to switch selected files, and after the selection change completes, the detail view doesn't always change to match the newly made selection.
> > Version 2.9.6 of GitHub desktop
> > On Windows 10 Pro 64Bit Build 19043
> > _EDIT_ Turning off auto fetch has made the application usable, but its still not very responsive (maybe like 5 or so seconds to switch files). Also all application menus (File, Edit, View, Repository, etc.) are incredibly slow to open.
> 
> It's might be thy the software does not work with your device.try a different app or file.

I have the same issue and with the 2.9.5 it was fine. When upgrading to 2.9.6, the problem started.

I can confirm that when auto fetching is off, the software seems much faster.

**Comment by narethi** [comment]
> > I am seeing the same issue, I have checked a few older topics and did a reinstall and turned off my firewall and I am still having this issue.
> > It takes around 30 seconds to switch selected files, and after the selection change completes, the detail view doesn't always change to match the newly made selection.
> > Version 2.9.6 of GitHub desktop
> > On Windows 10 Pro 64Bit Build 19043
> > _EDIT_ Turning off auto fetch has made the application usable, but its still not very responsive (maybe like 5 or so seconds to switch files). Also all application menus (File, Edit, View, Repository, etc.) are incredibly slow to open.
> 
> It's might be thy the software does not work with your device.try a different app or file.

I am running a Windows desktop, with an i7 7700, a GTX 1650, 2TB Samsung Evo 860 (that is mostly empty) and 32Gb (typically 20Gb or so free) of DDR4 Memory, its not the most recent hardware but I am assuming that the GitHub desktop application should run on this device comfortably. 

I will take a look at the  comment @Benoit1980 left about checking the highlighting library, but looking over my logs it seems that the remote calls to the server are taking between 5 and 30 seconds to complete.

 @Benoit1980 I am having the same symptoms as you mentioned in the initial post all UI menus are slow, trying to perform any action in the UI is resulting in large wait times for the application to respond and loading the local list of changes is taking upwards of a minute. I am going to look into the highlighting direction as that might be it.

**Comment by Benoit1980** [comment]
> > > I am seeing the same issue, I have checked a few older topics and did a reinstall and turned off my firewall and I am still having this issue.
> > > It takes around 30 seconds to switch selected files, and after the selection change completes, the detail view doesn't always change to match the newly made selection.
> > > Version 2.9.6 of GitHub desktop
> > > On Windows 10 Pro 64Bit Build 19043
> > > _EDIT_ Turning off auto fetch has made the application usable, but its still not very responsive (maybe like 5 or so seconds to switch files). Also all application menus (File, Edit, View, Repository, etc.) are incredibly slow to open.
> > 
> > 
> > It's might be thy the software does not work with your device.try a different app or file.
> 
> I am running a Windows desktop, with an i7 7700, a GTX 1650, 2TB Samsung Evo 860 (that is mostly empty) and 32Gb (typically 20Gb or so free) of DDR4 Memory, its not the most recent hardware but I am assuming that the GitHub desktop application should run on this device comfortably.
> 
> I will take a look at the comment @Benoit1980 left about checking the highlighting library, but looking over my logs it seems that the remote calls to the server are taking between 5 and 30 seconds to complete.
> 
> @Benoit1980 I am having the same symptoms as you mentioned in the initial post all UI menus are slow, trying to perform any action in the UI is resulting in large wait times for the application to respond and loading the local list of changes is taking upwards of a minute. I am going to look into the highlighting direction as that might be it.

Try this as it helped a bit with the speed from my side:

File>>Options>>Advanced>>Untick "Periodically fetch and refresh status of all repositories"

See if this helps a bit

**Comment by narethi** [comment]
> > > > I am seeing the same issue, I have checked a few older topics and did a reinstall and turned off my firewall and I am still having this issue.
> > > > It takes around 30 seconds to switch selected files, and after the selection change completes, the detail view doesn't always change to match the newly made selection.
> > > > Version 2.9.6 of GitHub desktop
> > > > On Windows 10 Pro 64Bit Build 19043
> > > > _EDIT_ Turning off auto fetch has made the application usable, but its still not very responsive (maybe like 5 or so seconds to switch files). Also all application menus (File, Edit, View, Repository, etc.) are incredibly slow to open.
> > > 
> > > 
> > > It's might be thy the software does not work with your device.try a different app or file.
> > 
> > 
> > I am running a Windows desktop, with an i7 7700, a GTX 1650, 2TB Samsung Evo 860 (that is mostly empty) and 32Gb (typically 20Gb or so free) of DDR4 Memory, its not the most recent hardware but I am assuming that the GitHub desktop application should run on this device comfortably.
> > I will take a look at the comment @Benoit1980 left about checking the highlighting library, but looking over my logs it seems that the remote calls to the server are taking between 5 and 30 seconds to complete.
> > @Benoit1980 I am having the same symptoms as you mentioned in the initial post all UI menus are slow, trying to perform any action in the UI is resulting in large wait times for the application to respond and loading the local list of changes is taking upwards of a minute. I am going to look into the highlighting direction as that might be it.
> 
> Try this as it helped a bit with the speed from my side:
> 
> File>>Options>>Advanced>>Untick "Periodically fetch and refresh status of all repositories"
> 
> See if this helps a bit

I had already unticked the "Periodically fetch and refresh status of all repositories" option as mentioned previously.

I discovered the source of my issue here locally. I installed "Daemon Tools Lite" recently (on Nov 26) and it appears to have bundled "https://www.reasonsecurity.com/" into its install, the application installed as service but did not add its self to my windows security dialog, and was installed with Daemon tools under its entry in add or remove programs. I had to uninstall it from the uninstaller in the install directory and that fixed the issue. (Although I don't remember installing this so I will likely just reinstall windows)
 
@Benoit1980 I am not sure if that is the same cause of your issue, it might be possible that there is something else that is conflicting on your system, Maybe you could run your system in SafeMode with networking and see if the issue goes away

**Comment by Benoit1980** [comment]
> > > > > I am seeing the same issue, I have checked a few older topics and did a reinstall and turned off my firewall and I am still having this issue.
> > > > > It takes around 30 seconds to switch selected files, and after the selection change completes, the detail view doesn't always change to match the newly made selection.
> > > > > Version 2.9.6 of GitHub desktop
> > > > > On Windows 10 Pro 64Bit Build 19043
> > > > > _EDIT_ Turning off auto fetch has made the application usable, but its still not very responsive (maybe like 5 or so seconds to switch files). Also all application menus (File, Edit, View, Repository, etc.) are incredibly slow to open.
> > > > 
> > > > 
> > > > It's might be thy the software does not work with your device.try a different app or file.
> > > 
> > > 
> > > I am running a Windows desktop, with an i7 7700, a GTX 1650, 2TB Samsung Evo 860 (that is mostly empty) and 32Gb (typically 20Gb or so free) of DDR4 Memory, its not the most recent hardware but I am assuming that the GitHub desktop application should run on this device comfortably.
> > > I will take a look at the comment @Benoit1980 left about checking the highlighting library, but looking over my logs it seems that the remote calls to the server are taking between 5 and 30 seconds to complete.
> > > @Benoit1980 I am having the same symptoms as you mentioned in the initial post all UI menus are slow, trying to perform any action in the UI is resulting in large wait times for the application to respond and loading the local list of changes is taking upwards of a minute. I am going to look into the highlighting direction as that might be it.
> > 
> > 
> > Try this as it helped a bit with the speed from my side:
> > File>>Options>>Advanced>>Untick "Periodically fetch and refresh status of all repositories"
> > See if this helps a bit
> 
> I had already unticked the "Periodically fetch and refresh status of all repositories" option as mentioned previously.
> 
> I discovered the source of my issue here locally. I installed "Daemon Tools Lite" recently (on Nov 26) and it appears to have bundled "https://www.reasonsecurity.com/" into its install, the application installed as service but did not add its self to my windows security dialog, and was installed with Daemon tools under its entry in add or remove programs. I had to uninstall it from the uninstaller in the install directory and that fixed the issue. (Although I don't remember installing this so I will likely just reinstall windows)
> 
> @Benoit1980 I am not sure if that is the same cause of your issue, it might be possible that there is something else that is conflicting on your system, Maybe you could run your system in SafeMode with networking and see if the issue goes away

Thanks for the tip, I will try this in a couple of days and see if safe mode helps. The only security I have is bitdefender, I already turned it off but the same problem occurred. I will try the safemode. Thanks!

**Comment by helhadad** [comment]
Same performance issue here.

**Comment by sergiou87** [comment]
Thanks for reporting this! We suspect the problem might be related to the recent upgrade of Electron to v13 (#13426), which tends to cause random issues. There are some known performance issues but only on macOS, though, so I wonder what's the problem exactly in your case.

You can go back to 2.9.5, however ⚠️ **your GitHub Desktop settings (like the list of repositories) might be completely deleted because upgrading to Electron 13 made some changes that are not backwards compatible** ⚠️ You can make a backup of [the settings folder](https://github.com/desktop/desktop/blob/development/docs/installation.md#windows-1) before installing 2.9.5, and then restore it when you go back to 2.9.6 (or newer).

If you still want to try 2.9.5 out, you can download it from https://centralreleases.blob.core.windows.net/github-desktop/releases/2.9.5-acc55692/GitHubDesktopSetup-x64.exe

**Comment by sergiou87** [comment]
Forgot to ask, does this happen with every single repo you have tried?

**Comment by caioavelar** [comment]
Hi! I'm also experiencing this issue.
I've reinstalled the software and it is still very slow.
I've seen in my logs one previous mentioned error, so I believe it's the same problem.
2022-02-11T12:32:06.248Z - error: [ui] Highlighter worked failed for new contents
Error: timed out
[2022-02-11.desktop.production.log](https://github.com/desktop/desktop/files/8049573/2022-02-11.desktop.production.log)
    at C:\Users\cavelar\AppData\Local\GitHubDesktop\app-2.9.6\webpack:\app\src\lib\highlighter\worker.ts:85:14


> Forgot to ask, does this happen with every single repo you have tried?

Yes, it happens with all of my repos.

**Comment by sergiou87** [comment]
Thank you for your report @caioavelar. Could you try the latest beta build? You can download it from https://github.com/desktop/desktop#beta-channel

We updated some core dependencies and the problem might be fixed 🤞

**Comment by caioavelar** [comment]
Hello @sergiou87!
I've tried to download the latest beta through this address https://central.github.com/deployments/desktop/desktop/latest/win32?env=beta, available in the beta channel, but it downloaded the 2.9.6 version. Maybe the link is incorrect? Reinstaling the 2.9.6 has solved for now, but the problem may come back.

**Comment by sergiou87** [comment]
> Reinstaling the 2.9.6 has solved for now

That's unexpected 😐 

I just downloaded the app from that URL and it downloaded the latest beta for me. In any case, if reinstalling 2.9.6 worked for you, that's great!

**Comment by Benoit1980** [comment]
And do not know if this can help you but I did all my windows 10 updates and the problem stopped.

**Comment by danielfowler** [comment]
I have been having this issue for the past 5 days - I'm not sure exactly where it started since version 2.9.7/8/9 all happened so fast, but it seems to have gotten much better here in the past hour for me. I had tried a number of different things, all of which are mentioned above, and *maybe* it was toggling off "Periodically fetch and refresh status of all repositories" that finally got me running mostly like normal just now.

**Comment by ikalogic** [comment]
I'm on 2.9.10, and have quite similar problems. Every mouse click takes approx 4 to 5 seconds to make any effect in GUI.

Have tried all suggestions above to no avail.

I can't find anything suspicious in logs.

**Comment by NickCraver** [comment]
Chiming in here: performance issues persist in version 2.9.13 (tried beta channel to - no difference). What profiling can we do to help locate what regressed here? I was ignoring it hoping this was known and a new release was pending, but I see that's not the case and it's causing me quite a bit of time in aggregate each day now, so how can we help find the culprit here?

**Comment by NickCraver** [comment]
I tried to ascertain which version this regressed in by installing previous builds (via chocolatey on Windows 11). Unfortunately, going back to 2.8.0 (and many release in-between) doesn't have any effect. I don't believe the regression is inside GitHub desktop itself, but how it calls out to git. Could be some Windows AV change, etc. I'll try and take some more time to do event tracing on this and see if I can determine what's so slow, but wanted to add info here: it's not the GitHub Desktop release, because reverting back years yields the same bad performance...something more fun is in play.

**Comment by j05hau** [comment]
This problem has only just started happening for me also. Yesterday I got a notification to update GitHub Desktop and after restarting the application it was working as per normal. However this morning after booting the computer it is the only application that is running incredibly laggy. Prior to the 2.9.14 update, performance has been as snappy as I have come to expect from this gem of an app. 

Hovering over any of the tabs takes a few seconds for the highlight to show up, and clicking on the tabs results in them slow to open. Also if I switch a branch it looks like the app is struggling to do the task and feels somewhat dangerous to be using - corruption of files or something. The lag in the highlighting seems to occur only after selecting any of the tabs, as it appears the app is trying to play catch up to some processess that are slow to process.

I have BitDefender Total Security but it never got in the way with prior versions up until now, so not sure its the anti-virus. 

Its also running 4 processes in the task manager, however I am not sure if this is normal or not. Just thought to mention it. 

![image](https://user-images.githubusercontent.com/20903421/163651966-455d9c48-93d7-4996-9651-8ffbd949cc65.png)

Also if I click on the tabs in the app, I get more instances of Git for Windows pop up. Don't know if this is normal or not, but the lag appears to happen when those processess show up in the Task Manager

![image](https://user-images.githubusercontent.com/20903421/163652516-a92f3282-252c-4aa7-ad59-8dccfb3ccbf2.png)

**Comment by the-IncideN7** [comment]
Similar issues here. Win10 and Mac.

It worked fine in the morning, and at some point, after I pulled some changes and tried to restore my local ones, the app just froze. Nothing seems to unstuck it. Reboots of the entire system included. It happens on both Windows and the latest Mac.
The same issue was present at least one time after the previous update.

My small research points me to the Restore function as a main cause.

If I leave the app open (and frozen) for about an hour, it gradually starts to work again.

**Comment by steveward** [comment]
Reported in https://github.com/desktop/desktop/issues/14429.

**Comment by steveward** [comment]
Another report in https://github.com/desktop/desktop/issues/15195.

**Comment by kmcdaniel-d2l** [comment]
Slow actions started after update to Version 3.0.6 on windows 10 last week
Log attached, 30 second create commit, 30-180 seconds fetch, 60 seconds pull
[2022-08-29.desktop.production.log](https://github.com/desktop/desktop/files/9445841/2022-08-29.desktop.production.log)

My issue has been resolved with Version 3.0.7 !!

**Comment by ihf4n** [comment]
Slow actions started after update to Version 3.1.3 on windows 10 
[2023-01-10.desktop.production.log](https://github.com/desktop/desktop/files/10389661/2023-01-10.desktop.production.log)

**Comment by steveward** [comment]
In https://github.com/desktop/desktop/issues/17193 performance issues were reported with antivirus software running.

**Comment by steveward** [comment]
Adding https://github.com/desktop/desktop/issues/18125.

**Comment by steveward** [comment]
In the interest of issue consolidation I am going to close this out in favor of our broader tracking issue https://github.com/desktop/desktop/issues/10625. History has shown that the majority of these cases are caused by overzealous antivirus software.
