### ISSUE TITLE
Desktop

### ISSUE THREAD

**Issue by Attila180** [desktop/desktop#13585]
https://user-images.githubusercontent.com/96492168/147230072-222624b4-a982-4668-bf68-c1bc8b9b3397.jpeg)

**Comment by KendallDoesCoding** [comment]
@tidy-dev The text is, Click here to read the QR code, but it may be a spam website so a spam ticket too, so you guys decide if you guys wanna scan it or no.

**Comment by Attila180** [comment]
I so so sorry, please help, I' not the problem

**Comment by Attila180** [comment]
Hy, please check the status? Good his not good!! Thanks Attila Bardos

Üdv ati

**Comment by Attila180** [comment]
Hy master! Please. Thank you

https://github.com/desktop/desktop/issues/13585


Üdv ati
