### ISSUE TITLE
Not pushed to the correct branch with Git for Windows

### ISSUE THREAD

**Issue by Yukuro** [desktop/desktop#13591]
### Describe the bug
Not pushed to the correct branch with Git for Windows

### Version & OS

Version 2.9.6 (x64)
Windows 10 Home (Version 20H2)

### Steps to reproduce the behavior

1. Clone the repository from `File > Clone repository`
2. Open [Git for Windows](https://gitforwindows.org/) and execute the following command
    - Create a "test_branch" branch from "origin/master"
    ```bash
    git checkout -b test_branch origin/master
    ```
3. Add some files (in this case test.txt)
4. Return to Github desktop
5. Click the Commit button in the lower left corner to commit.
    - **In the "Current branch" column, it is displayed as "test_branch"**
    ![prob01](https://user-images.githubusercontent.com/15343476/147349656-4e90a6f3-5ace-4378-ad37-cd93ddf11dff.png)
6. Press Push origin button
7. View my repository on github.com
8. In fact, the "test_branch" branch is not created, but pushed to the "main" branch
![image](https://user-images.githubusercontent.com/15343476/147349751-e233d4d1-049c-4772-980b-1334ef1c0ad0.png)

### Expected behavior
A "test_branch" branch is created, and test.txt is added to the "test_branch" branch.

### Actual behavior
On GitHub Desktop, it appears as if you are pushing to "test_branch".
In reality, however, "test_branch" is not created and pushed to "main".

### Additional context
I don't know if this problem is caused by GitHub Desktop or Git for Windows
But at least the "Current Branch" column should show the correct branch I'm on.

**Comment by tidy-dev** [comment]
I was able to reproduce with `git checkout -b test_branch origin/master`. If you follow this same set of steps through on the git for windows CLI, and try just pushing it will error out and make you choose: 
```
fatal: The upstream branch of your current branch does not match
the name of your current branch.  To push to the upstream branch
on the remote, use

    git push origin HEAD:main

To push to the branch of the same name on the remote, use

    git push origin HEAD

To choose either option permanently, see push.default in 'git help config'.
```

However, when following console in Desktop, I did not see this error so assuming we are making a decision in our code at some point to default to option one.

Other notes:
If you `git checkout -b test_branch` instead it works as expected.. so maybe there is something of Git that happens when you specify the source that makes it so it doesn't fully create/check out a new branch.

**Comment by samuelko123** [comment]
The push command is `git -c credential.helper= push origin test_branch:main --progress`. It means it'll push local `test_branch` to remote `main`.

The `:main` was introduced to fix https://github.com/desktop/desktop/issues/1689.

Both https://github.com/desktop/desktop/issues/1689 and this issue stem from local/remote branch name mismatch, but users have different expectation on the push behaviour.

Therefore, I propose appending the remote branch name when local/remote branch name mismatch occurs.

@tidy-dev May I raise a PR for that?

Case 1 - Local: `test_branch` ; Remote: `main`
![image](https://user-images.githubusercontent.com/91960206/233813005-d47de25f-503b-4c86-b197-f2552d383b48.png)

Case 2 - Local: `main` ; Remote: `main`
![image](https://user-images.githubusercontent.com/91960206/233813035-585ac8c0-b20a-4671-aaec-04c1458422ff.png)

**Comment by tidy-dev** [comment]
@samuelko123 Yep. We will take a  look at it. :)

**Comment by samuelko123** [comment]
Thanks @tidy-dev, I've raised a PR.

**Comment by michaelhaydendeveloper** [comment]
Long time CLI user.......started using this GitHub Desktop app.....no issues....till just now.....I'm on my branch and the desktop app pushed changes to main......emotional damage!!!!
