### ISSUE TITLE
set the open tool for each repo

### ISSUE THREAD

**Issue by jiangxiaoqiang** [desktop/desktop#13593]
### Describe the feature or problem you’d like to solve

Right now I could set the default IDE for all repo, but I need to set different IDE for differenent repo. For exampe, set visual studio for react code and CLion for rust code and Android Studio for flutter code.

**Comment by steveward** [comment]
Thanks for the feedback @jiangxiaoqiang! I'm going to roll this into https://github.com/desktop/desktop/issues/12195 where this was previously requested. You can follow along there for updates.
