### ISSUE TITLE
Set automatic repository folders

### ISSUE THREAD

**Issue by danielh-official** [desktop/desktop#13601]
### Describe the feature or problem you’d like to solve

A lot of times, users have their repos stored in a singular directory (e.g., Repositories). With GitHub Desktop right now, you have to add each individual repository for them to show on the app.

### Proposed solution

The user should be able to add a directory to an automatic register. The app would then look for Git repositories in that directory and add them automatically. This would increase the speed of development by cutting the time it takes to add all repositories to GitHub Desktop.

**Comment by Sanbot0000** [comment]
https://github.com/desktop/desktop/issues/13601#issue-1089549235

**Comment by tidy-dev** [comment]
@danielh-official Thank you for the suggestion! We have a way to handle adding multiple repos at one time; a user can select the multiple repository directories and drag and drop them at one time.  Thus, per your example, a user could open that Repositories directory, select all, and drag over onto GitHub Desktop. I hope this helps and as for now I don't believe we will be looking to adapt this. Thanks again!
