### ISSUE TITLE
Are there any documents for the CLI?

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#13605]
I found there are some CLI comands, like below:
![image](https://user-images.githubusercontent.com/5396286/147588329-a15543e9-3c9b-4279-8513-ed48f98e6c19.png)
Are there any technique documents on how the CLI work and implemented? such as how the commands are invoked from shell to the code, and the capability of the CLI if add more commands, such as whether the CLI can initiate an http request, etc. Thanks.

**Comment by tidy-dev** [comment]
@TerryChan 👋  This is an issue tracker for GitHub Desktop, which is not a CLI; thus, I am going to close out this ticket.  

However, if you are interested in learning about git (GitHub Desktop's underlying version control software that often interacted with through a CLI); you can check out [the official Git documentation.](https://git-scm.com/doc). 🙂

**Comment by TerryChan** [comment]
I'm not asking the CLI of git, I'm asking the CLI of GitHub Desktop, the 3 CLI supported by github command, as I mentioned in the snapshot of my question. 
Because I'm extending the function of the CLI in GitHub Desktop. I need to initiate http request to my server, and execute with async in my new CLI command, but it failed. So I hope to get some technique document on the CLI of GitHub Desktop.

**Comment by tidy-dev** [comment]
We interact with Git through a custom package called [dugite](https://github.com/desktop/dugite). There are some [docs](https://github.com/desktop/dugite/blob/master/docs/overview.md) with that repo (not entirely sure how up to date they are), but also GitHub Desktop is open source so you can take a gander at how we utilize it throughout the code base, but most of our Git interact can be found in the [git directory](https://github.com/desktop/desktop/tree/development/app/src/lib/git).  

Sorry I am not fully understanding your question, but hopefully this helps?
