### ISSUE TITLE
엉키즈 크롤링 파일 다운로드 이슈

### ISSUE THREAD

**Issue by tomatozoo** [desktop/desktop#13607]
### 위치 

datapipeline 브랜치 - pipeline/unkiz/e_unkiz.py

### 이슈
download 버튼 누르기를 하고
로딩을 위해 파일 다운로드를 해두었으나 에러는 없으나 다운로드 안됨

**Comment by tidy-dev** [comment]
@tomatozoo Hi! I popped this issue into google translate as no one on the team can translate.

```
location
datapipeline branch - pipeline/unkiz/e_unkiz.py

issue
and press the download button
I downloaded the file for loading, but there is no error, but it does not download
```

I received the above, unfortunately this is not enough for me to determine an issue. Could you please fill out the entire issue template?
