### ISSUE TITLE
Certificati postazione

### ISSUE THREAD

**Issue by PoddaManuela** [desktop/desktop#13609]
Buongiorno, 
ho bisogno di scaricare i certificati per la mia postazione, come posso fare? Preciso che ho una card ANPR con microchip nuovo che non riesco ad utilizzare. Potete chiamarmi al numero 070/7691218? Grazie.
Manuela Podda,
Comune di Settimo San Pietro (CA)

**Comment by steveward** [comment]
@PoddaManuela this issue tracker is for GitHub Desktop -- it sounds like you may be looking for a different project hosted on GitHub. If you are having specific issues with GitHub Desktop please let me know and we can investigate further.
