### ISSUE TITLE
Can't select final line of code & odd selection behavior (Edge case with line endings)

### ISSUE THREAD

**Issue by Daniel-McCarthy** [desktop/desktop#13613]
### Describe the bug
When working on a file, I found a case where committing a file with no final newline character/carriage return file ending, then making changes to add a new line caused line selection issues,

This can be reproduced by creating a file with some lines of code and saving with now newline/CR ending to the file, and creating a commit with it. Then, the file is changed to have a newline CRLF file ending, causing that line to no longer be able to be selected, and behavior shown in a gif attached of the behavior experienced.

Additionally, in the example given, the change can not be discarded.
___
### Version & OS

- **GitHub Desktop version**: Version 2.9.6 (x64)
- **Operating System**: Windows 10
___
### Steps to reproduce the behavior

1. Create a file that ends in a semi colon and has no extra newline afterwards.

Example code for file:
```js
test = () => {
}
```
(In my example, the file ends directly with the `}`, there is no `CRLF` or `LF` ending.)
Example file as shown in hex editor:
<details>
  <summary>My example file in a hex editor has no line endings, and ends with the `}` as the last byte of the file</summary>
  <img src='https://user-images.githubusercontent.com/4957200/147711563-14db9295-12ff-4e06-90d6-57d8104170ab.png' />
</details>

2. Commit the file to the repository.
3. Edit add a new line to the end of the file and save. (Do not commit the change).
<details>
  <summary>My changes to the example file in a hex editor, showing a `CR LF` file ending.</summary>
  <img src='https://user-images.githubusercontent.com/4957200/147711824-55ef1010-1353-4fa2-8835-4763211ff081.png' />
</details>

4. View the changes to the file in GitHub Desktop.
Example of how this appears on my end:
![image](https://user-images.githubusercontent.com/4957200/147711463-bbdbf8bb-7c64-40e5-a1b0-4ab9e502dcba.png)

5. Click and drag the changed lines in the diff view from top to bottom (or click the first line individually, then click the last one).
Example change:
___
### Expected behavior

Both the removed and added lines are selected.

### Actual behavior

Only the top line in the diff is selected.

<details>
  <summary>Gif demonstration of issue based on example above:</summary>
  <img src='https://user-images.githubusercontent.com/4957200/147711977-5d9738b0-db8d-42ce-bd7c-d3fdeb252019.gif' />
</details>

___

 ### Example Repository:

**[Single Line example  (as seen above)](https://github.com/Daniel-McCarthy/GitHubDesktop-ReproduceLineSelectionissue/blob/main/example1.js)**
**[Multi Line example (with demonstration below)](https://github.com/Daniel-McCarthy/GitHubDesktop-ReproduceLineSelectionissue/blob/main/example-multiline.js)**:

<details>
  <summary>Multi-line example file demonstration of issue (gif):</summary>
  <img src='https://user-images.githubusercontent.com/4957200/147712192-48a3a6b2-66f2-4e24-9c6a-f6dc660db88c.gif' />
</details>

I hope this helps, please let me know if there are any issues reproducing this or there are any further question!

**Comment by sergiou87** [comment]
Thank you for your detailed report! We will take a look and let you know 😄

**Comment by sergiou87** [comment]
Hey @Daniel-McCarthy !

We have talked about it, and we think it's probably an issue related to the way we handle new lines (or lack of them) at the end of the file, which are not represented by the existence or lack of them, but by a flag: https://github.com/desktop/desktop/blob/1a0e7e7a3e32611246a8f87cce30ee918a8dfe06/app/src/models/diff/diff-line.ts#L19

As far as we can tell, this shouldn't break anything badly, hence the `priority-3` label. Right now we don't have bandwidth to take care of it either, but feel free to take a look if you want and have the time for it!

**Comment by steveward** [comment]
I'm no longer able to reproduce this issue, so I'm going to close this out. @Daniel-McCarthy if you're still able to reproduce this please let me know.

https://github.com/user-attachments/assets/ca6131f8-dcc7-4766-aaff-02aabc47fae6
