### ISSUE TITLE
Add folder to gitignore

### ISSUE THREAD

**Issue by Andersama** [desktop/desktop#13619]
### Describe the feature or problem you’d like to solve
There's no context menu item to add a folder to the .gitignore.

### Proposed solution
When selecting items under the same folder, or subfolders present context menus to add folders to the gitignore. Should be fairly simple, Iterate through the selected edited files, add unique folder paths to the right click context menu.

### Additional context
Currently it's simple to ignore individual files or even file extensions, but it's also useful in some projects to ignore folders. Although ignoring files is useful, temporary files and folders from something like a build directory only clutters the ignore file unless added manually in. Given how easy it is to ignore files and files with particular extensions, it should also be equally easy to add folders.

**Comment by steveward** [comment]
Thanks for the issue @Andersama. This is being tracked in https://github.com/desktop/desktop/issues/1203, so I'll bump that issue up and close this one out. You can subscribe there for updates.
