### ISSUE TITLE
commit not functionning

### ISSUE THREAD

**Issue by Massetstephane** [desktop/desktop#13627]
### Describe the bug
using function commit to pass my folder modification to the main branch and nothing updated. (commit 6 hours ago)

### Version & OS

Version 2.9.6 (x64) french windows 10 21H2 64 bits

**Comment by steveward** [comment]
@Massetstephane thanks for the issue. When you say 'nothing updated', are you referring to the remote repository on GitHub? Did you push your changes after committing in GitHub Desktop? GitHub Desktop does not automatically sync your changes.

**Comment by Massetstephane** [comment]
hi ! my files on my computer (local) are not updated to the main branch (internet) , ah perhaps it's my error just use the commit fonction but before that I only used the commit button and all my modified files would replace those in the main branch of my project.
The biggest problem is that each time I have the English French translator to decipher the words commit, fech, push and other, I watch the tutorials but it's not easy to understand, But before this problem I only used the commit function to send my files.
But hey I used the upload file function, and I did everything manually.
I opened Github desktop just now, I think I understood the basics, pull origin files go to my hard drive, ok for the term fetched recuper in french, commit to main : modified files go to the main branch.
I think I was not wrong, the day before yesterday, github desktop sent the files successfully, but nothing was updated on github.
but when you say "Did you push your changes after committing in GitHub Desktop" I think I didn't, that's probably the error.
I will try again by adding a file and test, it's weird because I did the manipulation before :)
so i will create a file, use commit to main and push
I would come back to you to tell you if I understood or not.
steph

**Comment by Massetstephane** [comment]
hi ! i'm back, I think the error comes from that I modified locally by deleting files, and doing the same in the main branch without updating everything and when I made my github desktop updates was blocked because the local files no longer matched the main branch files, I corrected, and add a text, by committing to main I have the Push option now and the file has been transferred.
The problem is: that I wanted to erase the readme.md in my local folder, I will watch tutorials for the git ignore function.
Well it's ok I know transferred from the local to the main branch, and conversely, I have to test so that some files remain only on the main branch such as the readme.md.
steph

**Comment by steveward** [comment]
Thanks for the update. We have a [getting started guide](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/overview/getting-started-with-github-desktop) that you could take a look at -- it's not currently available in French but hopefully some of the screenshots along with running it through browser translation would be helpful!

Since we seem to have tracked down the issue you were having I'm going to close this out, but let me know if you have any further questions.
