### ISSUE TITLE
Cancel cloning/downloading button doesn't exist when it's in progress

### ISSUE THREAD

**Issue by OmarSherif96** [desktop/desktop#13620]
### Describe the feature or problem you’d like to solve

I was cloning a huge project but then I wanted to cancel the progress I didn't find cancel button

### Proposed solution

Add a cancel button while cloning at progress

### Additional context

Please include any other context, like screenshots or mockups, if applicable.

**Comment by steveward** [comment]
Thanks for the issue @OmarSherif96 -- we are tracking this in https://github.com/desktop/desktop/issues/2082 so I am going to close this out.  Please follow along there for updates.
