### ISSUE TITLE
French version for github and github desktop

### ISSUE THREAD

**Issue by Massetstephane** [desktop/desktop#13626]
all in the title i'm tired with "commit" "fesh" "push" term translate !!! into french every time i'm back here or using github desktop, i'm not sure with the function name and forced to have a translator anglais to french...

**Comment by steveward** [comment]
Thanks for the feedback @Massetstephane. At this time we do not have language localization in GitHub Desktop, but this is something that we would like to do in the future. I don't have a timeline for when that may happen as it would require quite a bit of work by the team. I'm sorry that I don't have better news at this time.
