### ISSUE TITLE
`spawn` is slow on dev builds for macOS running on Apple silicon devices

### ISSUE THREAD

**Issue by sergiou87** [desktop/desktop#13639]
### Describe the bug
After upgrading to Electron 13 (#13426), dev builds of the app take much longer to run `git` commands on macOS when running on Apple silicon devices. It still happens when building the app with Electron 15.

Normally, spawning git commands on a Mac Mini M1 in a given small repo would take around 0.0015s. But now, dev builds take 0.15-0.20s for the very same git commands.

### Version & OS

v2.9.6-dev
macOS 11.6+
Apple silicon

### Steps to reproduce the behavior

1. Build the app for development. Follow the instructions in https://github.com/desktop/desktop/blob/development/docs/contributing/setup.md#building-desktop
2. Run the app
3. Explore a repository
4. Keep an eye on the Developer Tools, where you can see how long it takes to run `git` commands.
5. Compare with the latest release build https://central.github.com/deployments/desktop/desktop/latest/darwin-arm64

### Expected behavior

Times should be similarly low in both dev and release builds.

### Actual behavior

Times are 10-100x slower on dev builds.

### Additional context

As mentioned in #12978 , on Electron 13 using `spawn` becomes very slow on the aforementioned conditions.

The problem seems to be in [libuv](https://github.com/libuv/libuv/issues/3050), and [a first attempt to fix it](https://github.com/libuv/libuv/pull/3064) made some Node.js tests fail, so the change [was reverted](https://github.com/libuv/libuv/pull/3107). This affects other apps like VS Code, and they decided to apply the changes to Electron, ignoring those broken Node.js tests, but [they found other problems derived from this](https://github.com/electron/electron/issues/26143#issuecomment-879569238) that they had to deal with.

Our hopes are in a [new PR trying to fix this](https://github.com/libuv/libuv/pull/3257), but the new fix led to a kernel bug that has been reported to Apple.

Related issues:
- Issue in libuv: https://github.com/libuv/libuv/issues/3050
- First report in the Electron repo: https://github.com/electron/electron/issues/26143
- Same issue in VS Code: https://github.com/microsoft/vscode/issues/132654
- VS Code uses a fork with the first fix but it causes its own issues: https://github.com/electron/electron/issues/26143#issuecomment-879569238
- First attempt o fix the issue: https://github.com/libuv/libuv/pull/3064
- Second attempt to fix the issue: https://github.com/libuv/libuv/pull/3257

**Comment by say25** [comment]
Is this still an issue? I know we just upgraded to Electron 16 on Beta?

**Comment by sergiou87** [comment]
I haven't tested it yet, but AFAIK this issue hasn't been addressed. The Electron team is working on it, and you can check their progress in https://github.com/libuv/libuv/pull/3257

Seems like they've made some good progress in the last weeks, I hope they manage to fix it! 🤞
