### ISSUE TITLE
Unable to access Github 

### ISSUE THREAD

**Issue by BalintN-MPP** [desktop/desktop#13637]
Get the message:

-------------------
ERROR: The `xxx' organization has enabled or enforced SAML SSO. To access
this repository, you must use the HTTPS remote with a personal access token
or SSH with an SSH key and passphrase
that has been authorized for this organization. Visit
https://docs.github.com/articles/authenticating-to-a-github-organization-with-saml-single-sign-on/ for more information.

fatal: Could not read from remote repository.

-------------------------
Behavior is the same with git command client, Github desktop client, Sourcetree.
Followed the link in the error message, logged in using the browser, cleared credentials from Windows Credential manager, in signed out and back in again.
My URLs use https.

Any suggestions?

**Comment by steveward** [comment]
@BalintN-MPP you likely need to reauthorize GitHub Desktop if your organization recently enabled SAML SSO. You can go to [this page](https://github.com/settings/applications) to revoke GitHub Desktop and then log in again from the app. Let me know if that helps.

**Comment by BalintN-MPP** [comment]
Thank you for the response, I managed to sort it out.

I found that in my .git/config file I had this: 
    url = git@github.com:myorg/myrepo.git

I changed it to 
    url = https://www.github.com/myorg/myrepo.git

This time when issuing a git command like git pull I was presented with a login dialog where I could provide my PAT token and it started to work.
