### ISSUE TITLE
Instructions to build

### ISSUE THREAD

**Issue by Advik-B** [desktop/desktop#13632]
### Describe the feature or problem you’d like to solve

I am currently on a linux PC. If needed i will build apps for my use but i dont have the instructions how to build on linux

### Proposed solution

In `README.md` please add the build instructions

### Additional context

( For python [EXAMPLE] )
```
pyinstaller --onefile -w --icon=assets/icon.ico __main__.py
```

**Comment by sergiou87** [comment]
I'm sorry @Advik-B but Linux is not officially supported. You can check out this other unofficial fork with Linux support where you'll find instructions to build it for Linux: https://github.com/shiftkey/desktop/blob/linux/docs/contributing/setup-linux.md
