### ISSUE TITLE
External editor 

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#13645]
I cant change the external editor on mt github desktop its showing only sublime editor and nothing else even after trying to change it

**Comment by niik** [comment]
Hi @richiebabe, please see https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md for the list of editors that GitHub Desktop supports. If your preferred editor is among the ones we support and you still don't see it in the list please open a new issue and we'll take a closer look.
