### ISSUE TITLE
Error when cloning a repository

### ISSUE THREAD

**Issue by basedmago** [desktop/desktop#13642]
I'm trying to clone a repository to my pc, in the verison 2.9.6 (x64) of github desktop, but i recieve this error everytime i try:

error: RPC failed; curl 56 Send failure: Connection was resets/s  
error: 6182 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

pls help me :(

**Comment by niik** [comment]
Hey @basedmago, this appears to be a problem with the internet connectivity between you and GitHub.com (assuming it is GitHub.com you're connecting to). There's not much GitHub Desktop can do to solve this so I would suggest following the steps in the [Troubleshooting connectivity problems](https://docs.github.com/en/get-started/using-github/troubleshooting-connectivity-problems) guide.

You can use the [GitHub Debug](https://github-debug.com/) tool to test your connectivity to GitHub.com and, if necessary, submit a support request to our support team.
