### ISSUE TITLE
git commits with machine name for user.email if missing config

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#1364]
#### Installed Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item.

**GitHub Desktop version:** 0.0.37

#### Operating System

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** macOS Sierra

#### Steps to reproduce

Please provide a list of instructions to recreate the issue. If the issue
involves a specific public repository, including the information about that
repository will make it is easier to recreate the issue:

 1. Open application and complete welcome wizard
 1. `git config --unset --global user.email`
 1. `git config --unset --global user.name`
 1. Make a commit in the repository

#### Expected Behaviour

**What did you expect to happen at this point?** 

An error from Git about not having an email address defined.

#### Actual Behaviour

**What actually happened? Attach any screenshots or error messages you think
might be valuable here.**

Git went ahead and used the machine name, instead of getting me to set an email address.

<img width="567" src="https://cloud.githubusercontent.com/assets/359239/25687770/90fef004-30bc-11e7-9840-896d77c1bf93.png">

The output when you do this from the command line is a hint:

```
[master 47bfd56] ha
 Committer: Brendan Forster <shiftkey@perses.local>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly:

    git config --global user.name "Your Name"
    git config --global user.email you@example.com

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 1 file changed, 1 insertion(+), 1 deletion(-)
```

I wonder if there's a flag for us to pass to disable this behaviour.

This is how the commit looks in the UI:

<img width="664" alt="screen shot 2017-05-04 at 11 28 32 am" src="https://cloud.githubusercontent.com/assets/359239/25687825/d8529bae-30bc-11e7-874d-7397adc7abe5.png">

**Comment by shiftkey** [comment]
Update: with Git 2.13 you'll get an error on the Window side. I'm not sure why macOS doesn't fail in the same way, I should revisit this.

There's also [this config value](https://git-scm.com/docs/git-config#git-config-useruseConfigOnly) (unset by default) that we could enable to enforce this:

> **`user.useConfigOnly`**
> Instruct Git to avoid trying to guess defaults for `user.email` and `user.name`, and instead retrieve the values only from the configuration. For example, if you have multiple email addresses and would like to use a different one for each repository, then with this configuration option set to `true` in the global config along with a name, Git will prompt you to set up an email before making new commits in a newly cloned repository. Defaults to `false`.

**Comment by steveward** [comment]
This shouldn't an issue anymore since we now show a warning if a commit will be misattributed. ✨
