### ISSUE TITLE
Backward "line endings will be changed" warning

### ISSUE THREAD

**Issue by thinkyhead** [desktop/desktop#13652]
### Describe the bug
The tooltip for the warning icon that concerns line endings is backward. It says "Warning - line endings will be changed from 'CRLF' to 'LF'," but the line endings are actually changing from LF to CRLF.

### Version & OS

Version 2.9.6 (arm64) on macOS 12.1 (21C52). 

### Steps to reproduce the behavior

1. Edit a file, changing only the line-endings.
2. Go to GitHub Desktop and hover over the 'warning' icon at top-right.
3. Observe the tooltip that appears.

### Expected behavior

"Warning - line endings will be changed from 'LF' to 'CRLF'."

### Actual behavior

"Warning - line endings will be changed from 'CRLF' to 'LF'."

### Screenshots

![image](https://user-images.githubusercontent.com/698003/148674496-837377cd-cdb4-4426-9d09-583a24bee569.png)

**Comment by niik** [comment]
Hey @thinkyhead, thanks for reaching out! That message is taken almost verbatim from Git itself so while it can be unintuitive I don't think it's incorrect.

The warning has to do with the `core.autocrlf` setting in Git (https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_core_autocrlf) which (when set to true) will automatically transform Windows-style line endings (CRLF) to Unix-style line endings (LF). I believe what's happening here is that you've manually saved the file with Windows-style line endings and Git is letting you know that it will _store_ the file with `LF` line endings.

See https://stackoverflow.com/questions/17628305/windows-git-warning-lf-will-be-replaced-by-crlf-is-that-warning-tail-backwar/44581947

Hope that helps!

**Comment by thinkyhead** [comment]
You're correct! I was misinterpreting the message. Thanks!
