### ISSUE TITLE
Github Desktop won't update Default Branch to main

### ISSUE THREAD

**Issue by john-lebens-highspot** [desktop/desktop#13669]
### Describe the bug

In the repository and from the command and in every conceivable place I have updated my default to main. However, when I click on the dropdown from Github Desktop it still displays master as the Default branch. 

NOTES:

- I have gone through every previous related issue and followed steps to solve to no avail. 
- This command: git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@'
   returns: main
- master branch has been deleted
    
### Version & OS

Github Desktop Version 2.9.6 (x64)
macOS Monterey Version 12.0.1

### Steps to reproduce the behavior

1. Change default to main in the repository and delete master
2. In every conceivable place change default branch to main
3. Rub these steps:
    `git branch -m master main
      git fetch origin
      git branch -u origin/main main
      git remote set-head origin -a
      git branch -d -r origin/master`
4. Confirm default is main using command line and checking repository and user settings
5. Restart computer and/or git
6. Notice that default in the dropdown still lists master

### Expected behavior

Default should not point to a branch that doesn't exist. It should match whatever the remote repository points to.

### Actual behavior

It is not updating

### Screenshots

The interface here won't allow me to upload a screenshot. 

### Logs

Not sure if I can share these as this is work related

**Comment by steveward** [comment]
Thanks for the report @john-lebens-highspot. I tested this out a bit and it does seem that GitHub Desktop isn't updating the default branch correctly. We've had reports of this in https://github.com/desktop/desktop/issues/11299 as well. I'll label this a bug for us to look into. 

For reference a fresh clone of the repository should resolve things.

**Comment by aurelien31** [comment]
I've the same issue and found that click on the refresh button (to the right of search input) on Pull Requests tab in Branches dropdown refreshes the default branche.

If that can help someone...

**Comment by dstrome** [comment]
@steveward - fyi - removing the repo from GH Desktop but not removing the files, then re-adding the repo to GH Desktop doesn't fix the issue. Oddly enough, cloning the repo to a new location fixes the issue in **both** the new and old location. 

Do you have any ideas where this info is stored? We're in the process of renaming master -> main in a few dozen repos, and we have several hundred contributors that this may happen with. We've already had reports from the first test batch. I'd love to give them a workaround that doesn't involve either deleting their local repo entirely or creating a second local clone to get the first clone to correctly update.

david.

**Comment by 06000208** [comment]
> Oddly enough, cloning the repo to a new location fixes the issue in **both** the new and old location.

Thank you, this solved it for me. `git symbolic-ref refs/remotes/origin/HEAD` output `refs/remotes/origin/main` just fine and I'd tried recloning the repo but I used the same location as before.

**Comment by steveward** [comment]
We got another recent report of this in https://github.com/desktop/desktop/issues/14266, I'm going to close this out in favor of tracking the more recent issue for 👀.

**Comment by JakeSidSmith** [comment]
@steveward did you mean #14266 ? I've just clicked through to this same page more times than I'd care to admin. 😂
