### ISSUE TITLE
Cannot connect to my new GitHub account

### ISSUE THREAD

**Issue by biznearme** [desktop/desktop#13671]
Completely uninstalled Github Desktop from Windows.
Installed new version.
Changed setting in app to new email, company name.
When I try to log in it is pointed to my OLD account.  That part of the screen is locked (as in I cant edit the account / username.

So... cant use GD if you create new repo (as in a new client with their own repo)  and try to change from the one you had previously connected. to.

Visual Studio auths also have the same exact problem.  Where did everyone get the idea that developer would only access ONE GH account.  Customers have their own.  Multiple account support.  What a great idea.  Please advise.

**Comment by steveward** [comment]
@biznearme thanks for the issue. When you uninstall GitHub Desktop there are files that left behind -- your cached credentials and local `.gitconfig` settings included. You can log out/log in by going to `File` > `Options` > `Accounts` and make sure your user/email are set correctly in the `Git` section as well.

We are tracking feedback for supporting multiple accounts in https://github.com/desktop/desktop/issues/3707. You can leave a 👍🏻 in that issue to indicate your desire to see this implemented.
