### ISSUE TITLE
UName.exe pegging processor, even when GitHub Desktop is NOT running

### ISSUE THREAD

**Issue by jaypatrick** [desktop/desktop#13670]
### Describe the bug
I recently noticed my CPU fan in my laptop going crazy quite often, and the offending process is uname.exe. Going to the install location from Taskman shows it living in a directory underneath the github desktop install folder. What is this process, and why does it not only run, but pegs CPU to 100%, even when GHD isn't even running? I use GHD all the time, but am wondering why it's doing something that requires so much CPU horsepower when the app isn't running?

### Version & OS

2.9.6 on Windows 11

### Steps to reproduce the behavior

uname.exe runs arbitrarily, don't know how to reproduce

### Expected behavior

I expect that when GHD is closed, it doesn't leave processes open that hijack my CPU power.

### Additional context

I think we all deserve an explanation as to why this happening, especially as software engineers. I am now very wary of your app, having been a longtime user for as long as the app has been out.

**Comment by steveward** [comment]
@jaypatrick thanks for the issue. The `uname` command is used for displaying system information, and is included with the Git installation that ships with GitHub Desktop. It definitely shouldn't be running after closing GitHub Desktop and using CPU. Any chance you have any antivirus or other software that could be interfering with GitHub Desktop? 

Just in case there's an install issue I'd recommend trying a fresh install by following these steps:

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that helps at all.
