### ISSUE TITLE
Can push but cannot commit

### ISSUE THREAD

**Issue by spsanderson** [desktop/desktop#13674]
### Describe the bug
I have been using github desktop all day committing and pushing. I made a new repository and tried to commit and got an error that wsl cannot be found. I did the commit via rstudio just fine and then pushed to the repo from github desktop...

### Version & OS

2.9.6 x64

### Steps to reproduce the behavior

1. change files
2.  add commit message
3. press commit

### Expected behavior

files should be committed

### Actual behavior

error of now distribution found for wsl, yes I can type wsl into windows start and it pulls up, however in admin in powershell wsl does not come up with a distribution which is odd since I already installed it.

### Screenshots

![Capture](https://user-images.githubusercontent.com/1976011/149581517-f6b63847-7773-4db3-9f02-849e548b7e4f.PNG)

### Logs

[2022-01-14.desktop.production.log](https://github.com/desktop/desktop/files/7873067/2022-01-14.desktop.production.log)
e.

**Comment by steveward** [comment]
Thanks for the report @spsanderson. That's a new error I haven't seen -- did you just recently install WSL on your machine? I do have a test VM with WSL and have not encountered this issue there. Has anything else changed on your system? Have you tried a quick restart to see if that resolves the issue?

**Comment by spsanderson** [comment]
I installed it maybe two months ago so I went ahead again today and did an install of a Ubuntu 1804 LTS and voila problem solved
