### ISSUE TITLE
Manual initialization of fetching

### ISSUE THREAD

**Issue by GHNewbiee** [desktop/desktop#13672]
### Initialize fetching manually for all projects

It is not clear when auto-fetching commences. There are cases that I feel that it never happens automatically. Pulling is not necessary to take place automatically.

### Proposed solution

Adding a button which triggers the fetching procedure immediately, one by one to feel that I have the control.

**Comment by steveward** [comment]
Thanks for the issue @GHNewbiee. Background fetching should occur hourly. The discussion around providing a separate `fetch` button is being tracked in https://github.com/desktop/desktop/issues/10444 -- I'll reference this issue there. 

Here's the frequency for background fetching for reference:

https://github.com/desktop/desktop/blob/15ed259dad47ff45c82e533000d470ed768dcb5f/app/src/lib/stores/app-store.ts#L338-L341

I hope that helps!
