### ISSUE TITLE
View upstream on GitHub

### ISSUE THREAD

**Issue by jlaurens** [desktop/desktop#13681]
### Describe the feature or problem you’d like to solve

Actually the action "View on GitHub" always opens the upstream repository even when called from a forked clone.

### Proposed solution

When the current repository is **not** a fork, no change.

When the current repository is a fork,
"View on GitHub" open the forked repository
"View upstream on GitHub" open the upstream repository

**Comment by sergiou87** [comment]
Thanks for your feedback @jlaurens !

In theory that behavior should change for forks depending on your "Fork Behavior":

![2022-01-17 at 16 09](https://user-images.githubusercontent.com/1083228/149794431-90c51ada-f9e3-45fc-ba32-27e7df98049a.png) ![2022-01-17 at 16 10](https://user-images.githubusercontent.com/1083228/149794469-8a12b2ec-5df9-4a3f-9982-b65afb3c9725.png)

You can select this in forked repos when you clone them, but also from `Repository` -> `Repository Settings` -> `Fork Behavior`:
![image](https://user-images.githubusercontent.com/1083228/149794875-8092389f-5bb2-46bf-8d01-d5d456f09a3a.png)

I hope that helps!
