### ISSUE TITLE
External Edition Option

### ISSUE THREAD

**Issue by naxtreasif** [desktop/desktop#13695]
While using GitHub Desktop in Mac, allows selecting Android studio to select as the default external editor, However, in Windows, it is not showing the option to select Android studio to select as default external editor. Can you please tell me if there is any way I can add it to the options or I can get in next release/

**Comment by sergiou87** [comment]
Yes! You can take a look at https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md for instructions about how to add new editors 😄 

Thank you and looking forward to your contribution!
