### ISSUE TITLE
One click instead of twp clicks to directly commit and push when possible

### ISSUE THREAD

**Issue by nsisodiya** [desktop/desktop#13694]
can we have a setting from which we can enable commit and push from just one button?
reason -> when I click commit, it takes 10-30 seconds to run pre-commit hooks and meanwhile I switch to chrome tabs or vscode. then I have come back to push the commit which I forget 80% of the time.

![image](https://user-images.githubusercontent.com/333455/150081135-d9c226b5-d7c4-4eab-83d9-220e23d4db29.png)

**Comment by steveward** [comment]
Thanks for the feedback @nsisodiya. At this time we don't have any plans to add a commit and push option, but if we continue to hear feedback about this being a pain point for users it may be something we consider again in the future. You can check out https://github.com/desktop/desktop/issues/2256 for some previous discussion around this.
