### ISSUE TITLE
Graphic display of branches 

### ISSUE THREAD

**Issue by MalekMneri** [desktop/desktop#13699]
We need a graphic display of when were the branches created and when were they merged. this will help immensely when resolving merge conflicts or trying to checkout a previous commit. 
![image](https://user-images.githubusercontent.com/47902348/150104614-c80560f6-732a-4634-825e-285b7bffe38d.png)

**Comment by steveward** [comment]
Thanks for the request @MalekMneri. Please follow along in https://github.com/desktop/desktop/issues/9452 for updates about a visual commit graph in GitHub Desktop. I'm going to close this out.
