### ISSUE TITLE
Only visible code stays selected when selecting a large chunk of code in a diff

### ISSUE THREAD

**Issue by CaveMobster** [desktop/desktop#13701]
### Describe the bug
When trying to select code in a diff and scrolling through it (I wanted to copy a chunk of code that's bigger than the viewport), only the selected code within the viewport stays selected.

### Version & OS
2.9.6 (Windows 10)

### Steps to reproduce the behavior

1. Open a file with a diff that's big enough to scroll
2. Start mouse selection at the top of the diff
3. Drag down and let the page scroll, or use the scroll wheel
3. Let go and scroll up to the start of the selection

### Expected behavior

I expected all code to be selected from the top of the diff to where I released the mouse button.

### Actual behavior

Only the code within the viewport is selected.

### Screenshots

https://user-images.githubusercontent.com/72231755/150154138-99d43cdd-0483-471b-b79b-4b6794890a79.mp4

**Comment by steveward** [comment]
Thanks for reporting this @CaveMobster!

**Comment by joyfullservice** [comment]
If anyone else is struggling with this, you can switch over to the **Unified diff** view to allow the selection of content that is larger than the viewport. (Assuming you don't have a lot of inline edits in the desired code snippet.)

![image](https://user-images.githubusercontent.com/7254992/154981185-b3080e77-2bdf-420b-871e-f251d26513f1.png)
