### ISSUE TITLE
Feature: I wish there could be a 'blame' view for files

### ISSUE THREAD

**Issue by kuehn-sba** [desktop/desktop#13708]
### Describe the feature or problem you’d like to solve

I wish there could be a 'blame' view files like in the portal

### Proposed solution

With this function it is possible to discover changes of certain lines of code from the perspective of the file. I am not sure if this is even possible locally. it's more of an idea..

**Comment by steveward** [comment]
Thanks for the feedback @kuehn-sba. This has been previously requested in https://github.com/desktop/desktop/issues/2310 -- at this time it isn't on our radar but I will bump up that issue.

**Comment by kuehn-sba** [comment]
fine .)

**Comment by Escain** [comment]
This is really required: 
1) Github-desktop is not only used with github.com, and not everyone has a cool web app to access the blame.
2) Github.com is not always accessible (e.g. when working offline). A blame is a must

**Comment by Escain** [comment]
Absolutely needed!
