### ISSUE TITLE
Can't sign in 2.9.6

### ISSUE THREAD

**Issue by st4rdog** [desktop/desktop#13716]
### Describe the bug
Can't sign-in due to not being able to set default browser.

### Version & OS

2.9.6

### Steps to reproduce the behavior

- File > Options > Accounts > Sign In
- Click Continue with browser

### Expected behavior

Browser redirects back to Github Desktop and it signs me in.

### Actual behavior

Browser says "You are being redirected." Github Desktop sits at the "Sign in using your browser" popup with a spinning icon in the top-right.

The buttons read "Continue with browser" and "Cancel". 

### Additional context

- You have not put any thought into what default browser people use or allow them to switch.
- You have not understood what a desktop program is. (We should not have to sign in using a browser.)
- Started because of "Author identity unknown" error when creating a new repository from File menu, even though I was logged in.

**Comment by steveward** [comment]
Thanks for the issue @st4rdog. It sounds like you may have run into https://github.com/desktop/desktop/issues/11410 -- does that seem correct? Were you able to authenticate? 

The ability to select a default browser is being tracked in https://github.com/desktop/desktop/issues/11027. I'll reference this issue there.
