### ISSUE TITLE
Dark mode - follow system

### ISSUE THREAD

**Issue by d7mtg** [desktop/desktop#13715]
### Describe the bug
There's an extra dot at the end of the sentence "Automatically switch theme to match system theme".
### Version & OS

Version 2.9.6 (arm64) macOS Monterey Version 12.1
### Steps to reproduce the behavior

1. Open Preferences from the GitHub Desktop menu
2. Click on Appearance
3. See that the subtitle of the System option is "Automatically switch theme to match system theme.", with an unexpected period at the end of the sentence.

### Expected behavior

I would expect there to not be a period, based on the guidelines mentioned in Primer / Interface guidelines / Foundations / [Content § Labels and Buttons](https://primer.style/design/foundations/content#labels-and-buttons).
### Actual behavior

I saw the above. 

### Screenshots

![CleanShot 2022-01-20 at 15 33 11@2x](https://user-images.githubusercontent.com/40274365/150417693-d67d5837-1a6e-4853-8805-de33cf875fae.png)

### Logs

Not applicable

### Additional context

Nothing, really.

**Comment by steveward** [comment]
Thanks for catching this @d7mtg!

**Comment by d7mtg** [comment]
I see it made it in today's release notes! so proud

**Comment by Ormkat5** [comment]
Change
