### ISSUE TITLE
Commits get sent from logged-out user

### ISSUE THREAD

**Issue by phildias** [desktop/desktop#13728]
### Describe the bug

In the GitHub Desktop GUI, when you log off from user A, then log on with user B, the commits you make will be registered as having been made by user A (not B). This likely has something to do with some of the files inside `%APPDATA%\GitHub Desktop` and how authentication is taken care of.

### Version & OS

GitHub Desktop 2.9.6 (x64)
Windows 10

### Steps to reproduce the behavior

1. In your default browser, log in to GitHub.com using one account. Let's call this account "User A". 
2. On the GitHub Desktop GUI, click on File>Options>Accounts>Sign in (to GitHub.com, not Enterprise)
3. A new window will pop up saying "Sign in using browser". Click on the "Continue with browser" button.
4. In the browser, click through the options to accept the authentication request coming from the app
5. If prompted by your browser, allow it open the authentication request using the GitHub Desktop GUI.
6. Load/clone any repository. Let's call this "Repository X".
7. Make some edits to "Repository X".
8. Using the GitHub Desktop GUI, commit the changes and push them to "Repository X"'s online repository. 
9. Using your browser, go to GitHub.com, access "Repository X"'s online repository and check the user responsible for its most recent commit. It should be listed as "User A".
10. Sign out of your GitHub.com account from "User A". 
11. Also log out from "User A"'s account on the GitHub Desktop GUI.
12. In your browser, log in to GitHub.com using **another** account. Let's call this account "User B".
13. Go through the same process described in steps 2, 3, 4 and 5 to log into "User B"'s account on the GitHub Desktop GUI.
14. Load/clone any **other** repository. Let's call this "Repository Y".
15. Make some edits to "Repository Y".
16. Using the GitHub Desktop GUI, commit the changes and push them to "Repository Y"'s online repository. 
17. Using your browser, go to GitHub.com, access "Repository Y"'s online repository and check the user responsible for its most recent commit. It should be listed as "User A".

### Expected behavior

I expect the most recent commit to "Repository Y" to be registered to "User B", since the GitHub Desktop GUI was logged in to "User B" when the commits were made.

### Actual behavior

Instead, "Repository Y"'s online repository will state that the most recent commit was made by "User A" , not "User B". This is likely due to some left-over authentication files that don't get cleared out when we log out of the GitHub Desktop GUI.

### Additional context

If you can't replicate this bug, try erasing the files in the `%APPDATA%\GitHub Desktop` folder (typically, `C:\Users\your_username\AppData\Roaming\GitHub Desktop`). But please back up your files before you do this!!!!

**Comment by steveward** [comment]
Thanks for the issue @phildias. What you are encountering is actually misattributed commits -- the email in your `.gitconfig` needs to match the email address in your currently logged in GitHub account in order for the commit to be attributed correctly. GitHub Desktop shows a warning symbol when the commit will be attributed to the wrong account:

<img width="379" alt="Screen Shot 2022-02-14 at 12 49 33 PM" src="https://user-images.githubusercontent.com/721500/153919204-fb2d3b87-a7a6-4a51-9188-b93b2ad63f45.png">

You can read more about how commit attribution works on GitHub [here](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user). If you have further issues or not seeing the warning symbol please let us know!

**Comment by Emezu** [comment]
Thank you so much,This was really helpful
