### ISSUE TITLE
Git SubModule Buttons

### ISSUE THREAD

**Issue by YawLighthouse** [desktop/desktop#13725]
### Describe the feature or problem you’d like to solve

When it comes to submodule's we're locked into using command line and custom powershell scripts and such to do so.

### Proposed solution

Adding buttons that would automate creating, adding, fetching, committing, pulling, and pushing changes to do these commands.

**Comment by mikemcguinness** [comment]
Something I actually agree with tonight lol.

Sent from Yahoo Mail on Android 
 
  On Sat, Jan 22, 2022 at 8:57 PM, Nicholas ***@***.***> wrote:   


Describe the feature or problem you’d like to solve

When it comes to submodule's we're locked into using command line and custom powershell scripts and such to do so.

Proposed solution

Adding buttons that would automate creating, adding, fetching, committing, pulling, and pushing changes to do these commands.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by steveward** [comment]
Thanks for the issue @Oldsiren. We're tracking submodule improvements in https://github.com/desktop/desktop/issues/7523 so reference this issue there.
