### ISSUE TITLE
Cloning error on Github Desktop

### ISSUE THREAD

**Issue by Shigeyuki-Matsunami** [desktop/desktop#13732]
### Describe the bug
I have a GitHub account, but I'm getting an error when trying to "clone a repositoriy",
that error massage is "Look like there are no repositories for XXXXXX  on Github.com. "
I uninstalled GitHub Desktop once, and then installed it again, but the problem persisted.

Attached is a dump screen.

### Version & OS

OS Windows 10
GitHub Desktp ver.2.9.6 (x64)

### Screenshots

![Inkedスクリーンショット 2022-01-24 16 37 30_LI](https://user-images.githubusercontent.com/38028745/150742179-fb1e56b0-7980-40de-85b2-63b7aaae9a22.jpg)

### Logs

[2022-01-24.desktop.production.log](https://github.com/desktop/desktop/files/7923630/2022-01-24.desktop.production.log)

**Comment by steveward** [comment]
@Shigeyuki-Matsunami thanks for the issue. Can you verify you are logged in to your GitHub account by going to `File` > `Options` > `Accounts`? If you are, try logging out and then logging back in to see if that helps.

**Comment by Shigeyuki-Matsunami** [comment]
Thanks, steveward. 
![スクリーンショット 2022-01-25 08 28 35](https://user-images.githubusercontent.com/38028745/150882659-40e83de9-ed20-4da9-8e49-28e3918b6a0b.png)
I made sure that I was logged in. I also tried logging out and back in again, but the same error message appeared.

**Comment by Shigeyuki-Matsunami** [comment]
Here is another information.

Cloning from "github.com" fails, but cloning from the "URL" succeeds.
![スクリーンショット 2022-01-25 08 36 00](https://user-images.githubusercontent.com/38028745/150883215-c1831911-b0c0-451d-a986-c2f7267d4529.png)

**Comment by steveward** [comment]
@Shigeyuki-Matsunami thanks for the update. Can you upload the log file from the day of the clone failure?

**Comment by Shigeyuki-Matsunami** [comment]
@steveward  
I've already uploaded the log file in the first comment line. Please see attached  "2022-01-24.desktop.production.log"

**Comment by steveward** [comment]
Thanks, I misread your last reply thinking there was a new error. Can you try resetting GitHub Desktop by following these steps?

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop and log in again

**Comment by Shigeyuki-Matsunami** [comment]
@steveward
I tried, but unfortunately, it didn't work.

**Comment by Shigeyuki-Matsunami** [comment]
By the way, I have another GitHub account, and it works well.

**Comment by steveward** [comment]
@Shigeyuki-Matsunami there must be a specific issue with that account. Could you go to `View` > `Toggle Developer Tools` and then go to the `Console` tab to see if there are any further errors when you click the `Refresh` button in the repository list?

**Comment by Shigeyuki-Matsunami** [comment]
@steveward
yes,  the error massage shown in the Console is below.
"install.ts:27 fetchRepositories: TypeError: Cannot read property 'owner' of null"

**Comment by steveward** [comment]
@Shigeyuki-Matsunami just to recap the situation:

- Cloning via URL in the clone dialog succeeds
- Authentication succeeds
- Fetching the repository list from the API fails

Once you clone a repository via HTTPS in the clone dialog via the URL option, do regular Git operations (i.e. push/pull) succeed without issue?

Is there anything like a firewall or proxy that could be interfering with network operations?

**Comment by Shigeyuki-Matsunami** [comment]
@steveward

Authentication is now successful　!
I am grateful for your polite response．
