### ISSUE TITLE
 No such file or directory 2: ./node_modules/pre-commit/hook error when commiting

### ISSUE THREAD

**Issue by k-matti** [desktop/desktop#13738]
### Describe the bug
Can't commit because of " No such file or directory 2: ./node_modules/pre-commit/hook" error everytime

### Version & OS

Version 2.9.6 (x64)

### Steps to reproduce the behavior

1. Go to 'Github desktop'
2. Click on 'Commit'
3. See error

### Screenshots

![image](https://user-images.githubusercontent.com/66017397/150948487-7a1462d9-8c2a-4605-a886-921ed1dc03f5.png)

**Comment by steveward** [comment]
Thanks for the issue @k-matti. Are you wanting to use a `pre-commit` hook with this repository? If you don't need the `pre-commit` hook, you can delete it in your repository by editing the pre-commit file (`git/hooks/pre-commit`). Some users have also had success gettin hooks to work by following [these steps](https://github.com/desktop/desktop/issues/10326#issuecomment-883749457). Let me know if that helps.

For reference we are tracking the option to skip `pre-commit` hooks in https://github.com/desktop/desktop/issues/11626.

**Comment by k-matti** [comment]
Hi @steveward I don't want to remove hooks from repo. I just want to use GitHub desktop instead of git from command line where everything works fine.

**Comment by steveward** [comment]
Try following the solution [mentioned here](https://github.com/desktop/desktop/issues/12586#issuecomment-892436293) and [here](https://github.com/desktop/desktop/issues/12562#issuecomment-1007154382) of making this change:

```sh
npm -> npm.cmd
npx -> npx.cmd
```

Let us know if that helps.

**Comment by k-matti** [comment]
> Try following the solution [mentioned here](https://github.com/desktop/desktop/issues/12586#issuecomment-892436293) and [here](https://github.com/desktop/desktop/issues/12562#issuecomment-1007154382) of making this change:
> 
> ```shell
> npm -> npm.cmd
> npx -> npx.cmd
> ```
> 
> Let us know if that helps.

I run these commands in CMD but get still the same error

**Comment by steveward** [comment]
@k-matti just to clarify -- you need to edit your hooks with that change -- is that what you did?

**Comment by k-matti** [comment]
@steveward don't have hooks folder. I switch do sourcetree and everything works fine there
