### ISSUE TITLE
git.exe push error for two 1.3 MB files

### ISSUE THREAD

**Issue by PavelPZ** [desktop/desktop#13734]
Error:
```
>git push
Enumerating objects: 10, done.
Counting objects: 100% (10/10), done.
Delta compression using up to 4 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (8/8), 831.75 KiB | 207.94 MiB/s, done.
Total 8 (delta 3), reused 5 (delta 1), pack-reused 0
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date
```

Using GitHub desktop with the same result.

See also https://github.com/desktop/desktop/issues/13733

**Comment by steveward** [comment]
Thanks for the issue @PavelPZ. Are you on a reliable network connection? Is there anything in your network that could be interfering with your connection to GitHub? Unfortunately this looks like a specific network issue and not a problem with GitHub Desktop. I would recommend trying on a different network to see if that succeeds.
