### ISSUE TITLE
Reordering Local Commits Broken

### ISSUE THREAD

**Issue by haacked** [desktop/desktop#13746]
### Describe the bug
I used to be able to reorder local commits by dragging and dropping them. Today, it stopped working. I tried restarting Destktop but it didn't fix it.

### Version & OS

MacOs Monterey 12.1 (21C52)
GitHub Desktop: Version 2.9.6 (arm64)

### Steps to reproduce the behavior

1. Open a repo in Desktop.
2. Create a couple of commits.
3. Try to reorder the commits.

### Expected behavior

I'm able to drag and drop local commits. 

### Actual behavior

I don't even get a drag indicator.

**Comment by tidy-dev** [comment]
@haacked Hi! I am thinking it could another instance of rebase in progress not being properly detected (Seen in #13051)

Could you try: 

- Make a backup of your repository (just in case)
- Open the repository in the Terminal
- Run: git rebase --abort
- Then, return to GitHub Desktop and see if reorder is working.

**Comment by haacked** [comment]
@tidy-dev there's no rebase in progress. I followed those steps and `git rebase --abort` reports

> fatal: No rebase in progress?

**Comment by haacked** [comment]
@tidy-dev I did confirm that it's only this one repo that's having a problem.

**Comment by haacked** [comment]
I was able to fix the issue by removing the repository from GitHub Desktop and then re-adding it.

**Comment by tidy-dev** [comment]
@haacked That is curious. Glad you were able to get it resolved!

**Comment by haacked** [comment]
@tidy-dev it happened again. I often do rebases in the command line. Seems like Desktop may be getting confused. `git version 2.32.0 (Apple Git-132)`

**Comment by tidy-dev** [comment]
Thanks for the additional info! Since you do rebases from command line often, I expect it is a similar bug to the previously referenced issue of partially detecting a rebase state (but maybe not updating after rebase state is cleared?) - Going to keep this one closed in favor of investigating these type of bugs/solving it under that ticket.
