### ISSUE TITLE
Can't pull due to unresolved conflicts, but they are resolved

### ISSUE THREAD

**Issue by ChrisJamesonGroves** [desktop/desktop#13756]
### Describe the bug
This is similar to #12250 which has been closed.
Working on a branch with another developer, he committed changes which I then pulled and resulted in a conflict. This was easy to resolve as I just needed to accept both changed. The other developer then committed another change (an enum typo) which did not have any conflicts. However I was unable to 'pull' his seconds round of changes with Github desktop telling me I have unresolved conflicts. 

Reading the above mentioned (#12250) bug resolution it stays that you need to commit your own changes before the conflict it truly resolved, which then allows you to pull any other changes. This does indeed fix the initial issue of not being able to pull changes. However, because his second commit was to address an enum typo, which I found when using that enum, it meant I had to commit code which i knew was wrong (using the, now outdated, incorrect enum) and then fix the issue, using the corrected enum and commit again!

This feels wrong to me. Why can pushed changes not be pulled to local branch when all local conflicts are resolved? If I had not known about this enum typo in the second commit and I simply committed my code and pushed/pulled all changes then the next developer to pull my changes would have found the build fails because of my committed use of the old enum.

### Version & OS
Windows 10 Pro (build 19044)
Github Desktop 2.9.6 (x64)

### Steps to reproduce the behavior
1. 2 developers on the same branch, make changes to the same file in the same location (maybe both add different references or something)
2. Dev 1 to push changes
3. Dev 2 pull changes and see conflict
4. Dev 2 to manually resolve conflict (see green tick in github desktop), but dont yet commit
5. Dev 1 to make changes which impacts the work of Dev 2, such as change an enum definition and push these changes
6. Dev 2 now cannot pull these latest changes, even though conflict is resolved and has green tick.
7. Dev 2 can now only really commit the resolved merge conflicts and push/pull all changes
8. Remote Branch now contains code with wrong code (invalid enum in this example) which could result in failed build.

### Expected behavior
I dont see why a developer cant pull remote changes to their local branch if all local conflicts are resolved. This would allow them to check that the latest changes all work together!

### Actual behavior
Cant pull changes, have to first commit, potentially broken, code.

**Comment by magnuswikhog** [comment]
Any progress on this? 
I have the same problem, also on 2.9.6 (x64) and Windows 10. 

It seems to happen any time there was a conflict and I manually resolved it by editing the file (right click, "Open in Sublime Text", edit, close the file). I see a green checkmark in Github Desktop, but the next time I try to pull it says there are unresolved conflicts even though there is no indication of any conflicts in Github Desktop anymore.

The way I work around it is 
1. Open a command window in the repo directory.
2. Run `git status` to see which files are modified.
3. Run  `git add <filename>` on all of them (might be enough to run it on the ones marked as "Unmerged paths").
4. Now I can do a pull from Github Desktop. 

Kind of defeats the purpose of having a GUI in the first place though.

**Comment by steveward** [comment]
Thanks for sharing this @magnuswikhog and @ChrisJamesonGroves -- we are tracking this in https://github.com/desktop/desktop/issues/11959. I'm going to reference these reports there.

**Comment by Aleem7890** [comment]
I resolved this by following Simple Steps:
 I'm using GitHub Desktop and in the **'CHANGES' tab**, I saw a Change with a **"Tick-mark"** ✔ on it. 
 I **discarded it** (or you can uncheck it) from the "Changes-TAB", and then I was able to PULL the changes on that branch.

**Comment by Nicoconot** [comment]
To simplify @magnuswikhog 's solution, what worked for me was:
- Run git status
- One line was different than the others, and said:
```
"Unmerged paths:
  (use "git add <file>..." to mark resolution)
        both modified:   [filename]"
```
- I manually ran` git add "[filename]"`
- GitHub Desktop was happy, and the merge continued normally

Note that even though it said "unmerged paths", I had already previously chosen to use the file from the pulled branch.
