### ISSUE TITLE
Unable to close GitHub Desktop on Mac

### ISSUE THREAD

**Issue by rv-harsha** [desktop/desktop#13753]
### Describe the bug

The cross button(in red) on the left top of the GitHub desktop screen doesn't seem to work on MacBook (M1 Pro)

### Version & OS

1. macOS - Monterey 
2. version - 12.2
3. GitHub Desktop version - 2.9.6 (arm64)

### Steps to reproduce the behavior

1. Open GitHub Desktop in full screen
2. Try to click on the close button on the left top corner of the GitHub desktop screen
3. GitHub desktop does not close

### Expected behavior

Click on the close button (in red) on the left top corner of the GitHub desktop screen should cause the application to close

### Logs

[2022-01-27.desktop.production.log](https://github.com/desktop/desktop/files/7946973/2022-01-27.desktop.production.log)

### Additional context

However, I am able to close the application when I minimize the GitHub desktop screen and click the close button. Or click on Quit GitHub desktop by selecting from the dropdown menu.

**Comment by steveward** [comment]
Thanks for the report @rv-harsha, this will be fixed in an upcoming release (https://github.com/desktop/desktop/pull/13685).
