### ISSUE TITLE
GitHub CLI broken in Monterey 12.3 (Beta)

### ISSUE THREAD

**Issue by saluzafa** [desktop/desktop#13779]
### Describe the bug
Github CLI does not work anymore because `/usr/bin/python` does not exists in Monterey 12.3 (Beta) since Apple removed it.

### Version & OS

GitHub Desktop Version: 2.9.6 (x64)
OS: MacOS Monterey 12.3 Beta

### Steps to reproduce the behavior

1. Open a Terminal
2. Enter the command: `github .`

### Expected behavior

It should open GitHub Desktop

### Actual behavior

It crash with an error.

```
/usr/local/bin/github: line 5: /usr/bin/python: No such file or directory
ls: ./MacOS/: No such file or directory
/usr/local/bin/github: line 13: ./MacOS/: No such file or directory
```

**Comment by sergiou87** [comment]
Thanks for your report @saluzafa! We'll look into this, but https://github.com/desktop/desktop/pull/13764 seems to be an attempt to fix this.

**Comment by steveward** [comment]
Should be fixed by https://github.com/desktop/desktop/pull/13764, so I'm going to close this out.
