### ISSUE TITLE
VS Codium not supported

### ISSUE THREAD

**Issue by antllo** [desktop/desktop#13777]
VS Codium is not supported on GitHub Desktop, but aparently you can do commits with VS Codium. 
I'm new here on GitHub and i would like improve my habilities and learn new things, Thank You.

**Comment by sergiou87** [comment]
Thanks for your report @antllo ! I assume this is happening on Windows.

I think this is the same problem as the one reported in https://github.com/desktop/desktop/issues/13295 so I'll close this in favor of that one. You can subscribe to that other issue if you want to get notified when progress is made 😄 

In theory, GitHub Desktop supports VS Codium on both macOS and Windows, but it might need adjustments on Windows for the latest versions.
