### ISSUE TITLE
error: RPC failed; curl 55 Send failure: Connection was aborted

### ISSUE THREAD

**Issue by assasingh** [desktop/desktop#13784]
Enumerating objects: 9861, done.
Counting objects: 100% (9861/9861), done.
Delta compression using up to 4 threads
Compressing objects: 100% (7679/7679), done.
error: RPC failed; curl 55 Send failure: Connection was aborted
send-pack: unexpected disconnect while reading sideband packet
Writing objects: 100% (9861/9861), 32.89 MiB | 1.24 MiB/s, done.
Total 9861 (delta 1909), reused 9861 (delta 1909), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

**Comment by sergiou87** [comment]
This usually happens when there is an antivirus or firewall installed in your machine. Please, try to disable them (you might need to reinstall GitHub Desktop) and see if that fixes the issue.
