### ISSUE TITLE
🐛 GitHub Desktop can't find Visual Studio Code (VSCode) when installed via package manager 🤷🏻‍♂️

### ISSUE THREAD

**Issue by pcgeek86** [desktop/desktop#13798]
### Describe the bug

I have Visual Studio Code installed on my dev system using the well-known [scoop package manager](https://scoop.sh). I can run `code` from the command line to launch VSCode. I use `scoop update *` to keep all of my software packages up-to-date.

I have also installed GitHub Desktop with scoop, using `scoop install github`.

Unfortunately, GitHub Desktop doesn't seem to be able to "find" VSCode. I am not sure how the detection is working, but I do have VSCode installed and up-to-date on my system. 

### Version & OS

* Windows 11 Dev Preview
* GitHub Desktop version 2.9.6

### Steps to reproduce the behavior

Use the ephemeral [Windows Sandbox VM](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview) to run PowerShell and issue these commands:

```
Set-ExecutionPolicy Unrestricted

# Install Scoop
iwr -useb get.scoop.sh | iex

# Install git
scoop install git

# Add the "extras" bucket for scoop
scoop bucket add extras

# Install VSCode and GitHub Desktop
scoop install vscode github
```

![image](https://user-images.githubusercontent.com/466713/151846723-e7edb650-1424-41c4-9527-3f5b6b2b00e9.png)

### Expected behavior

GitHub Desktop should see that VSCode is installed, and accessible on the `$PATH` environment variable, and launch it using that command.

### Actual behavior

![image](https://user-images.githubusercontent.com/466713/151846929-774ef3d2-7778-455b-81ba-cedebc968d2f.png)

### Logs

```
2022-01-31T17:54:13.573Z - info: [ui] [AppStore] loading 0 repositories from store
2022-01-31T17:54:13.751Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-01-31T17:54:13.843Z - info: [ui] launching: 2.9.6 (Windows 10.0.22523)
2022-01-31T17:54:13.844Z - info: [ui] execPath: 'C:\Users\WDAGUtilityAccount\scoop\apps\github\current\GitHubDesktop.exe'
2022-01-31T17:54:13.848Z - error: [ui] Error checking for updates
Error: The application is missing a dependency it needs to check and install updates. This is very, very bad.
    at file:///C:/Users/WDAGUtilityAccount/scoop/apps/github/2.9.6/resources/app/renderer.js:55:146726
    at onAutoUpdaterError (file:///C:/Users/WDAGUtilityAccount/scoop/apps/github/2.9.6/resources/app/renderer.js:55:147142)
    at CallbacksRegistry.apply (electron/js2c/renderer_init.js:107:834)
    at electron/js2c/renderer_init.js:83:5623
    at electron/js2c/renderer_init.js:83:5332
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:103:732)
    at EventEmitter.emit (events.js:315:20)
    at Object.onMessage (electron/js2c/renderer_init.js:91:925)
2022-01-31T17:54:13.852Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-01-31T17:54:13.978Z - info: [ui] Opt in reported.
2022-01-31T17:54:14.012Z - info: [ui] [Welcome] no sign in step found. ignoring...
2022-01-31T17:54:15.944Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2022-01-31T17:54:29.627Z - info: [ui] [AppStore] adding repository at C:\Users\WDAGUtilityAccount\Documents\GitHub\asdf to store
```

**Comment by sergiou87** [comment]
Hi @pcgeek86 ! 👋 

GitHub Desktop looks for certain uninstall keys in the registry: https://github.com/desktop/desktop/blob/75f0a03a9a7a512f52c250265f2139c21f3a8a50/app/src/lib/editors/win32.ts#L158-L177

I assume that installing it like you did either doesn't generate those keys, or they are different and yours need to be added to the list. Could you check which of those is true, please?

Thank you!

**Comment by babyrusa** [comment]
@sergiou87  can you repeat the suggestion please? i have the same issue for months now where Github suddenly misses the option to open with VSCode.

**Comment by Cignul** [comment]
Bump,Necro - I'm having this issue now.  Just updated VS code and it won't show in the external browser dropdown.

**Comment by TNTErick** [comment]
Same here on Win10, Github Desktop installed from the Setup.exe;
Win10 was reinstalled at some point so there is no uninstall key, but VS Code is kept on another disk.

**Comment by thelastWallE** [comment]
> Hi @pcgeek86 ! 👋
> 
> GitHub Desktop looks for certain uninstall keys in the registry:
> 
> https://github.com/desktop/desktop/blob/75f0a03a9a7a512f52c250265f2139c21f3a8a50/app/src/lib/editors/win32.ts#L158-L177
> 
> I assume that installing it like you did either doesn't generate those keys, or they are different and yours need to be added to the list. Could you check which of those is true, please?
> 
> Thank you!

Thank you. You just helped me troubleshoot this. Apparently an old installation was not removed completely and GithubDesktop was just doing nothing on clicking the button. I just deleted the leftover key in the registry and it chooses the right installation of VSCode now.

**Comment by larryli** [comment]
```ini
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\{771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1]
"DisplayIcon"="\"C:\\Users\\(current user)\\scoop\\apps\\vscode\\current\\Code.exe\""
"DisplayName"="Microsoft Visual Studio Code"
"Publisher"="Microsoft Corporation"
"InstallLocation"="C:\\Users\\(current user)\\scoop\\apps\\vscode\\current"
```
