### ISSUE TITLE
Help window support

### ISSUE THREAD

**Issue by AustinConlon** [desktop/desktop#13795]
I think it'd be nice to see native help [window support](https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/help/).

**Comment by sergiou87** [comment]
Thank you for your feedback!! We had those kind of tooltips before (and we still do in some places) but they weren't good enough for us, and we want to keep some consistency across operating systems, so I don't think we'll make changes around this any time soon, sorry!
