### ISSUE TITLE
SSH Background fetch job is consuming massive amounts of network bandwidth

### ISSUE THREAD

**Issue by MMullin7** [desktop/desktop#13815]
### Describe the bug
Seems as if there is an issue with the job running the background fetch. It is either cloning the databases in repositories it knows about or doing some horribly inefficient request.

### Version & OS
![image](https://user-images.githubusercontent.com/6788425/152289260-04c634ab-0308-4dca-abd0-ed2c7b97def6.png)

![image](https://user-images.githubusercontent.com/6788425/152289299-a6fd0418-496f-433c-a233-790eaee2816a.png)

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Go to Preferences
2. Click on `Periodically fetch and...`
3. Wait and watch for periodic downstream data consumption

### Expected behavior

I would expect a reasonably throttled fetch.

### Actual behavior

The SSH service tied to the github desktop process was pulling down Gigs of data at a concerning rate

### Screenshots
Not sure when this was enabled by me(if ever at all), but something seems wrong, my wifi usage has gone exponential
![image](https://user-images.githubusercontent.com/6788425/152289146-fcc2f61d-6af9-4370-880f-fbe2291e4d20.png)

**Comment by sergiou87** [comment]
Thanks for your report @MMullin7!

Did anything specific happen when you started noticing this? (e.g. updating to 2.9.6, starting to work on a specific repository, starting to use SSH for your repos…)

Looking at the dates, it started going up before we released 2.9.6 (14-Dec-2021), also before we released 2.9.5 (2-Dec-2021), and then 2.9.4 was released back in October, so it doesn't *seem* tied to a specific version of GitHub Desktop.

**Comment by MMullin7** [comment]
> Thanks for your report @MMullin7!
> 
> Did anything specific happen when you started noticing this? (e.g. updating to 2.9.6, starting to work on a specific repository, starting to use SSH for your repos…)
> 
> Looking at the dates, it started going up before we released 2.9.6 (14-Dec-2021), also before we released 2.9.5 (2-Dec-2021), and then 2.9.4 was released back in October, so it doesn't _seem_ tied to a specific version of GitHub Desktop.

I'm not sure honestly, I try to keep it up to date as much as possible. I wasn't even aware of the issue until the ISP reached out to me to slap me with a fine.   I'm still digging into this to see if I can get more information though.

**Comment by sergiou87** [comment]
Is someone else working on that repo? The app should only fetch remote data in background, so if other people are pushing stuff to the repository, that's what the app will be downloading. Not sure if that helps you pinpoint where the issue could be 😅 

In any case, please keep us posted if you find anything suspicious!

**Comment by MMullin7** [comment]
> Is someone else working on that repo? The app should only fetch remote data in background, so if other people are pushing stuff to the repository, that's what the app will be downloading. Not sure if that helps you pinpoint where the issue could be 😅
> 
> In any case, please keep us posted if you find anything suspicious!

I work at a software developement company. So a large number of engineers are modifying quite a few repositories.  I noticed in the UI(but didn't think twice around it) that the fetch origin was being called without me doing anything and taking quite awhile to finish and I'd have to just use the cli.

I'm also not convinced that the background job actually turns off with the checkbox disabled.  
![image](https://user-images.githubusercontent.com/6788425/152400114-e010a1cd-2e6d-4e61-bf37-b2e300f98e94.png)
 I disabled it last night and haven't done anything this morning and noticed this in the UI.

**Comment by MMullin7** [comment]
![image](https://user-images.githubusercontent.com/6788425/152404003-43e8a9bf-d36a-4f58-bad2-06b6a4e341c9.png)
![image](https://user-images.githubusercontent.com/6788425/152404071-308310c7-f3e0-4eac-bfd4-dd02709f950b.png)

**Comment by MMullin7** [comment]
> Is someone else working on that repo? The app should only fetch remote data in background, so if other people are pushing stuff to the repository, that's what the app will be downloading. Not sure if that helps you pinpoint where the issue could be 😅
> 
> In any case, please keep us posted if you find anything suspicious!

It is 100% confirmed it is the background job.  It must be doing something highly inefficient.

**Comment by sergiou87** [comment]
Unless I'm missing something, it's just doing a `git fetch`, which just updates your branches with whatever other people has pushed to the repository 🤔 

Just curious, have you tried to clone that repo using https instead of ssh and see if it makes a difference?
