### ISSUE TITLE
> ### Describe the bug

### ISSUE THREAD

**Issue by aiodh** [desktop/desktop#13819]
> ### Describe the bug
> I no longer have the option to open files in Notepad++, which I had configured as my External Editor. GitHub Desktop doesn't find any suitable editors and prompts me to install VS Code.
> 
> ### Version & OS
> GitHub Desktop version 2.92. Microsoft Windows [Version 10.0.19041.1165]
> 
> ### Steps to reproduce the behavior
> 1. Go to the Changes tab.
> 2. Check the main pane (on the right).
> 
> ### Expected behavior
> The main pane should show an option to "Open the repository in your external editor", just above the option to "View the files of your repository in Explorer".
> 
> ### Actual behavior
> Only the Explorer option is shown.
> 
> Also, the File, Options, Integrations dialog now says "External editor. No editors found. Install Visual Studio Code?" but it should offer a way to choose Notepad++.
> 
> ### Additional context
> I've observed this on two different computers, both Windows 10. Notepad++ support was working well in version 2.90 as shown in the screenshot.
> 
> ### Screenshots
> ![ghd290-nppp](https://user-images.githubusercontent.com/19389579/130998992-fb71ff95-25c4-4e46-99ef-063e659fcd55.PNG)

_Originally posted by @aiodh in https://github.com/desktop/desktop/issues/12841#issuecomment-1029906245_

**Comment by tsvetilian-ty** [comment]
Hi @aiodh 

I checked on version 2.9.6 (x64) of Github Desktop and everything works as expected. Can you share what is the version of Notepad++ you're using?
