### ISSUE TITLE
Pushing to github repositories takes forever II

### ISSUE THREAD

**Issue by haesleinhuepf** [desktop/desktop#13855]
### Describe the bug

This is a follow up for issue #13800 

Uploading to github.com takes ages. It looks like it hangs in an endless loop here:

<img width="317" alt="image" src="https://user-images.githubusercontent.com/12660498/153286452-6376beb8-7d21-4428-adb2-43848097c6c5.png">

### Version & OS

<img width="440" alt="image" src="https://user-images.githubusercontent.com/12660498/153286553-1c6a85e1-288a-446d-b0ff-21b9876a67f6.png">

I'm working on a Mac M1

<img width="221" alt="image" src="https://user-images.githubusercontent.com/12660498/153286615-ccae6202-d1b3-4cee-8f8f-e44e94e6e917.png">

### Steps to reproduce the behavior

It happens when pushing to a repository. I have the impression that bug happens when I push many files and/or large files ( 1 to 5 MB images for example)

### Expected behavior

Would be great if pushing would work.

### Actual behavior

Pushing hangs.

### Screenshots

See above and #13800 

### Logs

The last log entries in the last log file are about 1h old. I assume these log entries have nothing to do with the current operation.

### Additional context

If you could let me know how to debug those things, that would be great. Is there some kind of verbose mode?

**Comment by sergiou87** [comment]
Hi again @haesleinhuepf!

Do you use Git LFS in that repo? I wonder if that might be related 🤔 

Also, have you tried pushing from the terminal with `git push`?
