### ISSUE TITLE
Cherry picking into current branch doesn't work

### ISSUE THREAD

**Issue by tomas-varga-swi** [desktop/desktop#13865]
When trying to cherry pick from any branch into currently active one - user is prompted with error message

### Version & OS

Version 2.9.6 (x64), Win 10 Enterprise 1909

### Steps to reproduce:

0. Have a branch with commit you want to cherry-pick and another branch where you want to apply the commit.
1. Select the branch you want to apply the commit TO as your current branch.
2. Switch to History tab.
3. Look-up the branch you want to cherry-pick commit FROM and select it to view it's history.
4. Find the commit you want to cherry-pick in the history list.
5. Right-click the commit and select 'Cherry-pick commit'.
6. Select your current branch as the destination for the cherry-pick.

### Expected behavior

User is able to proceed with the cherry pick when the two branches are different

### Actual behavior

User is unable to proceed, instead is prompted with a message saying the two branches can't be the same, even if that's not the case.

### Screenshots

![Screenshot 2022-02-11 121145](https://user-images.githubusercontent.com/63790025/153581937-b1c0ee22-1517-4b8c-ab10-16afb1485ecc.png)

- The message is also not DPI aware (hence the offset), but that least of my problems here.

**Comment by tidy-dev** [comment]
@tomas-varga-swi Hi! Based on your screenshot, I believe what you are doing is trying to do is cherry-pick a commit by using the compare function in the history tab to view commits from a different branch. As can be read more about #12688, it is a bug that the cherry-pick functionally is enabled when the compare function is being used and not how it is intended to be used.

If you would like to cherry-pick commits from `branch-A` to `branch-B`, 
1. Check out `branch-A`.
2. Go to the history view (do not use compare function) and find those commits.
3. Invoke the cherry-pick (either context menu, or drag commits up to branch dropdown)
4. Select or drop onto `branch-B`.

Desktop will then copy those commits to `branch-B` and check `branch-B` out where you can view it's history to see that the commits were successfully copied.


(Going to close this, but if I have misunderstood your scenario, feel free to comment back).

**Comment by tomas-varga-swi** [comment]
@tidy-dev Hi, you're right, this is a duplicate of the https://github.com/desktop/desktop/issues/12688. Your steps would work, so does switching to a "neutral" branch beforehand and doing it this way. Do you have any recommendations for doing multiple cherry-picks from different branches into one? If you use command-line you can do it all from the destination branch, but using the UI here would require multiple branch switches.

**Comment by tidy-dev** [comment]
@tomas-varga-swi Yep. You are right using a neutral branch works when using the compare feature. We found when developing cherry-picking, that most use cases only involved two branches. (A single source and a single target), and our solution is optimized for that. So yes, you would have to switch to the different source branches under this approach.

We have also received feedback in #13031 about staying on the source branch instead of checking out the target.. which I suppose would allow someone to use the compare feature with neutral branch work around to do this.. but we currently do not have plans to support this.
