### ISSUE TITLE
multiple files are not converted into single file

### ISSUE THREAD

**Issue by Antimony-R** [desktop/desktop#13878]

**Comment by Allawialkaabi7** [comment]
> شكرا لك على مشكلتك! لم نحصل على رد على أسئلتنا أعلاه. مع المعلومات الموجودة حاليًا في المشكلة فقط ، ليس لدينا معلومات كافية لاتخاذ إجراء. سنغلق هذا ولكن لا تتردد في التواصل إذا كان لديك أو تجد الإجابات التي نحتاجها. إذا أجبت عن أسئلتنا أعلاه ، فسيقوم المشرف بإعادة فتح هذه المشكلة.

ما فهمت شو المطلوب من المستندات بالضبط

**Comment by Allawialkaabi7** [comment]
موضوعي كامل عندكم وواضح جدا

**Comment by Allawialkaabi7** [comment]
***@***.***‬‏

في الاثنين، ٢١ فبراير، ٢٠٢٢ ٩:٢٥ م no-response[bot] <
***@***.***> كتب:
