### ISSUE TITLE
Misattribution notice more tolerant for GH private emails

### ISSUE THREAD

**Issue by janbrasna** [desktop/desktop#13879]
### Describe the feature or problem you’d like to solve

The warning triangle for author misattribution notice is present even though my git config email is fine, and has always been. It's just in the old format before the `id+…` addition. I'd prefer not to change the committer info in my git settings as I've always had this one and would prefer to keep it … and at the same time get rid of the warning triangle that covers my avatar.

### Proposed solution

Please consider silently tolerating `example@users.noreply.github.com` in git config even for `12345+example@users.noreply.github.com` account as that might have been "the correct" form back in the day.

### Additional context

![Screenshot 2022-02-14 at 18 45 21](https://user-images.githubusercontent.com/1784648/153919545-361a6042-3b9b-4563-924a-dbea428c9348.png)

**Comment by janbrasna** [comment]
(I'd try to propose a solution for it, but given the wording in its function it seems there might be a known mismatch use case that is intentionally not ignored?)

https://github.com/desktop/desktop/blob/18238077aa1e4851e710cfa66587cd4fd597bacd/app/src/lib/is-account-email.ts#L5-L10

**Comment by niik** [comment]
Thanks for reporting this @janbrasna, you're absolutely right that the "legacy" format should be considered when determining if a commit will be attributed correctly. I'll try to get a fix up for this shortly
