### ISSUE TITLE
Application hangs when trying to discard changes

### ISSUE THREAD

**Issue by palhal** [desktop/desktop#13888]
### Describe the bug
When trying to discard changes, the application becomes unresponsive.

### Version & OS
2.9.7 (x64)
Windows 10 21H2 (19044.1526)

### Steps to reproduce the behavior
1. Change a file in any repository
2. Open the Changes tab
3. Right click on the applicable file
4. Click _Discard changes_ in the context menu
5. Click _Discard changes_ in the confirmation dialog

### Expected behavior
* The changes are discarded

### Actual behavior
* A spinner icon appears in the dialog title bar
* The whole application becomes unresponsive
* Nothing happens when clicking Discard changes or Cancel
* The changes are not discarded

### Screenshots
![github-discard](https://user-images.githubusercontent.com/56862114/154061580-7030fd63-ce1c-4ac3-a40f-061ca6e6505f.png)

### Logs
Not much relevant content in the logs. This is the only line written:
```log
2022-02-15T11:32:53.506Z - info: [ui] No submodules found. Skipping "git submodule status"
```

### Additional context
* I have waited about 10 minutes for the operation to finish
* The only solution is to terminate the application from Task Manager
* I have checked that there are no other processes using the file
* I have tried to discard multiple file types (.js, .html, .json)
* I have tried multiple repositories. All repositories are non-GitHub.
* I have tried deleting _%AppData%\GitHub Desktop_ to start "fresh" 
* Downgrading to 2.9.6 fixes the problem
* Not directly related, but the application seems slower to start in 2.9.7

I was unsure whether I should open a new issue or comment on #13433 or #13661, but those appear closed by #13436.

**Comment by tidy-dev** [comment]
Thanks for the report! Curious if it does discard the changes and just that the application hangs?

**Comment by tidy-dev** [comment]
I know there were not errors, but would you mind uploading the log anyways? - We might be able to at least see app progression to see if it is not reaching something we expect. :)

**Comment by palhal** [comment]
Thanks for the prompt response. No, the changes are not discarded. That's why I thought there might be a file-already-in-use problem, but I'm quite certain that's not the case.

I didn't think older logs were relevant and unfortunately I deleted the whole logs folder when the problem started. I have the logs however for when I downgraded to 2.9.6 and it was working until I upgraded again. I also included a log for a "fresh" start with the _%AppData%\GitHub Desktop_ folder removed. I'm not sure if any of that helps.

[after-upgrade.log](https://github.com/desktop/desktop/files/8072036/after-upgrade.log)
[fresh.log](https://github.com/desktop/desktop/files/8072124/fresh.log)

A strange side effect when I downgraded was that all my repositories were gone. (That's why you see the number changes from 12 to 0.)

**Comment by tidy-dev** [comment]
Thank you for your help debugging! (We are unable to reproduce this on our windows machines). 
Would you mind uninstalling GitHub Desktop, removing this folder `%LOCALAPPDATA%\GitHubDesktop\`, and reinstalling? 

> strange side effect when I downgraded was that all my repositories were gone. (That's why you see the number changes from 12 to 0.)

This is expected as with this upgrade we had some underlying db changes that are not backwards compatible. Also the above actions will do the same thing. A helpful shortcut is that you drag and drop repository folders onto desktop to add them and can do more than one at a time this way.

**Comment by palhal** [comment]
No problem! This is a great product and I'm happy to help. Thank you for the drag and drop tip and downgrade explanation. I was starting to think there were some other serious issues with this machine 😄

Removing the folder and reinstalling did not help, but I think I've found the cause. Can you please try disabling the Recycle Bin for the drive where the repository is stored?

![recycle-bin-properties](https://user-images.githubusercontent.com/56862114/154102064-84dc2dd9-9926-4f58-b8ca-2fb523783058.png)

If I select _Custom size_ the problem disappears.

**Comment by steveward** [comment]
Thanks @palhal, I was able to reproduce this issue as well on my Windows machine with those options configured.

**Comment by steveward** [comment]
Here's the specific error I'm seeing in the console:

```
index.tsx:131 Uncaught exception {name: 'Error', message: "Error invoking remote method 'move-to-trash': Error: Failed to perform delete operation", stack: "Error: Error invoking remote method 'move-to-trash…iscard-changes\\discard-changes-dialog.tsx:153:42)"}
rM @ index.tsx:131
(anonymous) @ index.tsx:204
emit @ node:events:394
Kp @ non-fatal-exception.ts:44
(anonymous) @ index.tsx:222
node:electron/js2c/renderer_init:61 Uncaught (in promise) Error: Error invoking remote method 'move-to-trash': Error: Failed to perform delete operation
    at EventEmitter.i.invoke (node:electron/js2c/renderer_init:61)
    at async git-store.ts:1462
    at async queue-work.ts:39
    at async ks.discardChanges (git-store.ts:1457)
    at async Object._discardChanges (app-store.ts:4357)
    at async Object.AS.discard [as onSubmit] (discard-changes-dialog.tsx:153)
```

**Comment by t3knoid** [comment]
I too am seeing this after I upgraded this morning. Will try to get more information. The only thing I've tried so far is deleting the cache folder. That did not help. I'll post more if I find any new information. Just posting here for now to confirm the op's report.

**Comment by t3knoid** [comment]
My current work folder is located in a mounted NAS share. It wouldn't be part of recycle bin. Is this a similar use case as the one described in #13899?

**Comment by tidy-dev** [comment]
@t3knoid Likely it is a similar issue in that the `electron.trashItem()` fails since it cannot access it (before this upgrade it would have silently failed to do so)

**Comment by t3knoid** [comment]
Just got the new upgrade, 2.9.8. It no longer hangs. The error is being caught, "Failed to discard to recycle bin". However, this should no apply to my set up since I am using a shared network folder.

**Comment by ivalkenburg** [comment]
An option to disable discarding changes to recycle bin all together would be stellar

**Comment by kevinroast** [comment]
Hi, i've just upgraded to '2.9.9 (x64)' on Windows 10. I am no longer able to to discard modified items, I see the error:

**Failed to discard changes to Recycle Bin.
A common reason for this is that the Recycle Bin is set to delete items immediately.**

Which is interesting since my Recycle Bin is _not_ set to delete items immediately. This was all working fine before upgrade. I haven't changed anything else locally on my system, also note that a manual 'git restore ...' using cmd line on the same file works correctly.

**Comment by t3knoid** [comment]
My Recycle bin is also set to not set delete items immediately. Plus as I mentioned, my local repo is on a network NAS share in which deletes don't normally go into the recycle bin. And yes, this was all working before upgrade.

**Comment by adamiatro** [comment]
I'd like to add that this behaviour now also happens in WSL2. I can no longer discard any changes so an option to not use the Recycle Bin at all would be very helpful.
