### ISSUE TITLE
Show User Guides

### ISSUE THREAD

**Issue by geishajunkie** [desktop/desktop#13882]
### Describe the bug
Clicking on 'Show User Guides' in the 'Help' menu on the Github desktop app directs to a 404 Page not found 
 

### Winblows 11 with Firefox Developer Edition

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Clicked on 'Help'' at main menu of Desktop App
2. Click on 'Show User Guides'
3. See 404 error

### Expected behavior

Expected to find a bunch of User Guides.

### Actual behavior

My web browser opened to a 404 Page not found and said "Ooops".

### Screenshots

![github_user_guides_404](https://user-images.githubusercontent.com/1691077/153987962-5091ede3-787f-4126-a420-db88975566c5.jpg)

**Comment by geishajunkie** [comment]
The link should be https://docs.github.com/en/desktop instead of https://docs.github.com/desktop/guides

**Comment by niik** [comment]
Thanks for the report @geishajunkie! Would you be interested in contributing a fix? This is the place where we open the browser:

https://github.com/desktop/desktop/blob/ab48d526da6feb6a47fa9a4f4a77eaaf9293cc35/app/src/main-process/menu/build-default-menu.ts#L473-L480

There's a link below that to the keyboard shortcuts which is also using the `help.github.com` domain which could use an update as well.

If you don't have the bandwidth just let us know and we'll take care of it!
