### ISSUE TITLE
Unable to fetch authenticated user with 2.9.7

### ISSUE THREAD

**Issue by Tensuko** [desktop/desktop#13893]
### Describe the bug
After (sadly forceing) update from 2.9.6 to 2.9.7 I noticed an Error with fetching.
So I tried to reconnect my user to gitHub Desktop and recieved that Error.

While for example VS Code had no problem connecting, I guess there is some bug in the new version.

So I did some tests and I got the app-2.9.6 and app-2.9.7 folders inside GitHubDekstop folder.
Starting the .exe from 2.9.6 and it works fine and it als detects my repositories and branches.
Starting the .exe from 2.9.7 and no connection is possible.

Some old but maybe related Issue: #11346
As well as the feature request for turn off auto update: #9575
(Haven't found an option to disable this)

### Version & OS
2.9.6 / 2.9.7
Windows 10 Pro (x64)

### Steps to reproduce the behavior

Have 2.9.6 running fine.
Wait for AutoUpdate.
Start 2.9.7 and it stops working.
(Yes this might only happens on my side :) )

### Expected behavior

Else be able to turn off the auto-update, or have a clear changelog about authentication changes.

### Actual behavior

I guess the descriptions says it all.

### Screenshots

Screenshot of that Error is the same, as in the linked Issue.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
[2022-02-15.desktop.production.log](https://github.com/desktop/desktop/files/8073005/2022-02-15.desktop.production.log)

### Additional context

Appreciating your project, it is a rly helpful tool for quick switching branches and easy commiting.

**Comment by steveward** [comment]
Thanks for the report @Tensuko. Any chance you are running antivirus software or behind a firewall that could be flagging GitHub Desktop and blocking network connections? The updates we ship can sometimes trigger these issues. Here are the related errors I'm seeing in the log:

```
Cloning into 'I:\Dokumente\My Games\FarmingSimulator2022\mods\FS22_Courseplay'...
fatal: unable to access 'https://github.com/Courseplay/Courseplay_FS22.git/': Send failure: Connection was reset

2022-02-15T13:08:54.202Z - info: [ui] [AppStore] loading 6 repositories from store
2022-02-15T13:08:54.202Z - info: [ui] [AppStore] found account: Tensuko (Tensuko)
2022-02-15T13:08:56.619Z - warn: [ui] fetchAccount: failed with endpoint https://api.github.com
TypeError: Failed to fetch
```

**Comment by Tensuko** [comment]
That is actually the first time it does it like that.
And only for the .exe of 2.9.7 wich is kinda strange.
I don't remember that I had to add any .exe from github Dekstop to allow access and if so it would ask me for permission and not throw an Error. (Windows Firewall, Kaspersky Anti-Virus)

**Comment by Tensuko** [comment]
Somehow with the latest version it seems to be fixed.
But I keep an eye on it.
