### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by ttuhin03** [desktop/desktop#13895]
### Missing "Issues" tab on GithubDesktop

On GitHub, Users have the Option to add "Issues" to their Project, wich works like a TODO List.
This is a great feature for communication between people, who work on the same project,

### Add a "Issues" Tab next to the "Fetch Origin" Tab

With this Tab, the Users see directly in the GitHub Desktop App, what the current status of the TODO List is, who may already be working on it, and if they need to do it him/herself.

### Its already a core feature on GitHub , but somehow missing on the Desktop Version

![image](https://user-images.githubusercontent.com/75586604/154113264-173cd986-548c-4481-84fc-ae1f5c4d5ce2.png)

**Comment by steveward** [comment]
Thanks for the feedback @HaeMGe. We discussed issue creation within GitHub Desktop in https://github.com/desktop/desktop/issues/8989. You can follow along there for any new updates about this, but at this time we do not have plans to add a way to directly view issues within GitHub Desktop. 

We do provide issue integration into commit messages. You can reference issues in commit messages by using the `Closes #<issue_number>`. When you type this out it will bring up a list of issues for you to scroll through if you want to close out a specific issue with a commit. When this commit is merged into your default branch it will automatically close the referenced issue. I hope that helps!
