### ISSUE TITLE
Discard changes Failed

### ISSUE THREAD

**Issue by dongdapeng1982** [desktop/desktop#13905]
### Describe the bug
My recycle bin settings: do not move files to the recycle bin. Delete files immediately after they are removed.

Then the Discard changes will fail.

If you open the recycle bin, everything is normal.

### Version & OS

Version 2.9.7 (x64)      Win10

**Comment by steveward** [comment]
Thanks for the issue @dongdapeng1982. This is being tracked in https://github.com/desktop/desktop/issues/13888, please follow along there for updates.
