### ISSUE TITLE
Adding/Opening an Existing Local Repo from Disk Results in Folder Path Entry Issues (lost keystrokes)

### ISSUE THREAD

**Issue by trmatt** [desktop/desktop#13901]
### Describe the bug
When opening a local repository via CTRL+O and then typing in a path, characters appear, and then disappear as though either being erased, or the keystroke undo buffer is being triggered (as it sometimes affects more than 1 character).

### Version & OS

Version 2.9.7 (x64) on Windows 10

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. CTRL + O to Add a local repository...
3. Begin typing the path in the Local path text field provided
4. Usually starts about the time the first path separator (backslash) is entered (e.g. c:\) -- the character will be displayed, then removed and possibly redisplayed (if typing is paused). 

### Expected behavior

When entering text for the path, don't alter the input.

If checking the path validity to highlight the Add repository button, ensure user input is not discarded.

### Actual behavior

When entering the path, it is necessary to pause regularly to figure out what the textbox is going to do. Sometimes it will swallow one or more characters, but then redisplay them. Other times, it will swallow and not redisplay the characters, forcing re-entry.

### Screenshots

![add-local-repository-dialog](https://user-images.githubusercontent.com/46758082/154145498-7f36bc5c-2652-4ec0-80e7-66efb1b8f1c6.png)

### Logs

No logs seem to be applicable. Opening the Developer Tools to watch the console during the process did not show anything at all (good or bad) until the repository had been selected, and was opened.

### Additional context

I am not using GitHub for these repos (or this install of GitHub Desktop). It is currently only operating on local repositories hosted on an internal service.

EDIT: fixed backslash disappearing from issue report (replaced with word)

**Comment by uttiya10** [comment]
I have had this issue too, but thought it was simply my computer acting up, guess not.

Seems like this is happening because there a check to see if the path is a valid git repository, which triggers on every keypress.

https://github.com/desktop/desktop/blob/24cbf878a66801def4997080017d7e6d0eeca96d/app/src/ui/add-repository/add-existing-repository.tsx#L167-L171

This check occurs *before* updating the textbox's internal state, and since this check can take some time, it may be possible for you to enter more text before the check has completed, resulting in keystrokes being deleted.

A possible fix would be to update the textbox's internal state *first*, then perform the check afterwards.
Here's a rough changelog:

```diff
diff --git a/app/src/ui/add-repository/add-existing-repository.tsx b/app/src/ui/add-repository/add-existing-repository.tsx
index ab299e21b..ac46124d6 100644
--- a/app/src/ui/add-repository/add-existing-repository.tsx
+++ b/app/src/ui/add-repository/add-existing-repository.tsx
@@ -165,9 +165,17 @@ export class AddExistingRepository extends React.Component<
   }

   private onPathChanged = async (path: string) => {
-    const isRepository = await isGitRepository(path)
-
-    this.setState({ path, isRepository })
+    // We set isRepository to false to prevent user from submitting the dialog
+    // while we manually verify it. 
+    this.setState({ path, isRepository: false }, async () => {
+      const isRepository = await isGitRepository(path)
+      // The path might have changed while we were checking, in which case we
+      // don't care about the result anymore.
+      if (this.state.path !== path) {
+        return
+      }
+      this.setState({ isRepository })
+    })
   }

   private showFilePicker = async () => {

```

**Comment by trmatt** [comment]
I'm pretty sure you've hit the nail on the head.

That code and your explanation looks/sounds like exactly what is happening.

An alternative would be to separate the path validation from the button status entirely.

e.g. Always allow people to confirm the path (to an existing or new repository) with a icon (+/checkmark) to indicate whether you'll be opening or creating a new repo folder, with follow-up workflow if a folder needs to be created and repo details set.

That's a larger scale change, but sidesteps the issue and puts the user back in control.

My two cents anyway.

Sounds like it'll be better in future now though!
