### ISSUE TITLE
New local repository has wrong local path

### ISSUE THREAD

**Issue by DavidTs93** [desktop/desktop#13909]
### Describe the bug
When adding a new local repository from a local path the `Local Path` changes to something else entirely.
No matter what folder I choose it always changes the `Local Path` to the same (different) folder. The folder that's chosen doesn't even exist - some path and a folder with my GitHub username as the final folder.

### Version & OS

Version 2.9.7 (x64)
Windows 10 (x64).

### Steps to reproduce the behavior

1. `File`
2. `Add Local Repository`
3. `(choose)`
4. `create a repository`
5. Wrong `Local Path`

**Comment by steveward** [comment]
Thanks for the report @DavidTs93. I was unable to reproduce this -- are you able to reproduce this when attempting to add multiple (different) repositories? Could you also try dragging-and-dropping a repository into GitHub Desktop to see if that shows the correct path?

Clearing out `%AppData%\GitHub Desktop` will likely get things working again.

**Comment by DavidTs93** [comment]
I cleared and I just lost all my local info... and that's it.
The `Local path` defaults to `C:\Users\<username>\Documents\GitHub` no matter what, and thus doesn't even look at the folder I actually chose.

**Comment by sergiou87** [comment]
This fix should be out in 2.9.9, thanks for your patience! 😄

**Comment by seshadrianadasu** [comment]
The HTML file which is hosted in the git hub, there is a problem that is images are not shown. after debug the page  i am found that the images files are "the server responded with a status of 404 ( )"  how to solve it .
<img width="958" alt="Screenshot 2024-01-14 195424" src="https://github.com/desktop/desktop/assets/153181738/f19f8451-bc1f-4444-829e-9feb842364e3">
"the server responded with a status of 404 ( )"  how to solve it .
