### ISSUE TITLE
Error while opening github desktop on mac

### ISSUE THREAD

**Issue by syedhasanabbaszaidi** [desktop/desktop#13912]
### Describe the bug
Error while opening the desktop tool

### Version & OS

Mac OS V 12.0.1

Github version - Version 2.9.6 (x64)

![image](https://user-images.githubusercontent.com/13048828/154226049-eac8e6ef-3ba2-4060-aede-8c2103fed47b.png)

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Open Github desktop tool and got the error

### Expected behavior

Must open without errors

### Actual behavior
Must open without errors

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

![image](https://user-images.githubusercontent.com/13048828/154225367-aebcdaa0-06ca-4938-8086-28bbe7b46892.png)

![image](https://user-images.githubusercontent.com/13048828/154225553-c3a856a3-db30-485b-9585-00d7a5d0b7c8.png)

![image](https://user-images.githubusercontent.com/13048828/154225596-2cd5b5f8-afdd-4742-9c07-ab833753fac0.png)

![image](https://user-images.githubusercontent.com/13048828/154225623-4c844998-14c0-40f4-a1e6-eab86bc6f448.png)

![image](https://user-images.githubusercontent.com/13048828/154225650-9e0ded7b-aa3e-4f2f-ab21-e9254d1a7afb.png)

![image](https://user-images.githubusercontent.com/13048828/154225689-aed28d3d-f238-4393-85b6-e3c127b4f671.png)

![image](https://user-images.githubusercontent.com/13048828/154225716-8d3b30fd-c57f-407b-95ce-f2f88fd1e6eb.png)

![image](https://user-images.githubusercontent.com/13048828/154225738-9a876368-804b-472e-8f03-7dcf61c3db85.png)

![image](https://user-images.githubusercontent.com/13048828/154225757-93f0c67b-7464-493b-b6ac-284429fcd9ea.png)

![image](https://user-images.githubusercontent.com/13048828/154225784-67a73617-b9e3-442b-88ee-721ea9e41644.png)

![image](https://user-images.githubusercontent.com/13048828/154225805-bf0fbdd6-5bf0-44be-8453-9c71844c9248.png)

![image](https://user-images.githubusercontent.com/13048828/154225833-357a2e8f-ef0c-4666-9841-c9bfd8de382e.png)

**Comment by Sed9yDataBank** [comment]
I am getting the same exact error on my Mac OS as well! the GitHub Desktop app made an update last night, and today after I reopened the app, I am getting the above errors...

**Comment by niik** [comment]
Thanks for the report! Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by snicolet** [comment]
I also experienced the same issue (or maybe different, but related issue):

a) at **each** launch of Github Desktop, I get a Finder error dialog ("Github Desktop has quit unexpected")
b) I had one error dialog within Github similar to the ones shown by @syedhasanabbaszaidi , about "Command failed: ..." for formatting code.

Hope this helps,
Stéphane

Three attachments : 
1) production.log  :  [2022-02-18.desktop.production.log](https://github.com/desktop/desktop/files/8094915/2022-02-18.desktop.production.log)
2) crash report for (a) :  [crash.log](https://github.com/desktop/desktop/files/8094974/crash.log)
3) screen.png for (a)  : 

<img width="2048" alt="screen" src="https://user-images.githubusercontent.com/6761856/154636313-6262074c-2b80-4fc9-bde8-f11f7421240d.png">

**Comment by dkav** [comment]
I am also experiencing a similar issue as @snicolet. GitHub version is 2.9.9 and macOS is 10.15.
[GitHub Desktop_2022-02-22-111754.crash.log](https://github.com/desktop/desktop/files/8119576/GitHub.Desktop_2022-02-22-111754.crash.log)
[2022-02-22.desktop.production.log](https://github.com/desktop/desktop/files/8119592/2022-02-22.desktop.production.log)

**Comment by snicolet** [comment]
@niik Sorry, but what information do you need? There have been two persons posting crash.log and production.log files, yet the bot closes the issue :-(

**Comment by niik** [comment]
Hey @snicolet, sorry about that, our bot is rather picky about the response needing to come from the person who initially opened the issue. It looks like there's at least two issues being discussed in this thread, the original issue and the one you and @dkav are experiencing which is the same as is being discussed in https://github.com/desktop/desktop/issues/13974 so I would urge you both to subscribe to that issue for updates instead.

Thanks!

**Comment by snicolet** [comment]
thanks :-)
