### ISSUE TITLE
Commit failed error with GPG signing turned on

### ISSUE THREAD

**Issue by bwestover** [desktop/desktop#1391]
### Description

I recently started seeing this with the atom/github package as well. See that report for more details: https://github.com/atom/github/issues/737

When I try to make a commit I get an error message: 

```
Commit failed - exit code 128 received, with output: 'error: cannot run gpg: No such file or directory
error: gpg failed to sign the data
fatal: failed to write commit object'
```

### Version

**GitHub Desktop version:** 0.0.37

**OS version:** OS X El Capitan (10.11.6)

### Steps to Reproduce

1. Make a change to a file in a repository
1. Type a commit message
1. Click Commit button
1. Error Message:
![image](https://cloud.githubusercontent.com/assets/1987494/25757491/919d3e6c-317f-11e7-8086-a1eb90212e39.png)

**Expected behaviour:** I expect the commit to succeed.

**Actual behaviour:** I get the above error message, changes remain in the **Changes** tab and are not committed.

**Reproduces how often:** 100%

### Logs

I couldn't find log files for Desktop beta. Are there any?

#### Additional Information

I have git configured to sign every commit:

```
$ git config --global --get commit.gpgsign
true
```
And my git version:
```
$ git --version
git version 2.12.0
```

**Comment by mysticatea** [comment]
I have encountered this problem, too.
The previous official GitHub Desktop for Windows (https://windows.github.com/) is working well.

**Version**

GitHub Desktop version: 0.5.3
OS version: Windows 7 pro

**Comment by EtherTyper** [comment]
@bwestover That is the problem! :smiley: I used the same fix in #1578, and now GPG signing works.

**Comment by joshaber** [comment]
I'm gonna roll this into #1796 so that we can track the underlying cause.

**Comment by HajarElkoumikhi** [comment]
I tried this out and it works ! 

`git config --global commit.gpgsign false`

**Comment by marchershey** [comment]
^ Unfortunately, that's not what most of us are after. We want to sign our commits, and that is just turning it off. If you're not worried about it, then yes, use that command to disabled commit signing.

**Comment by RCNOverwatcher** [comment]
Any update on this? I have the same error and apart from turning of commit signing, there's not much I can do.
