### ISSUE TITLE
Add Repository defaults to an old / different directory. Choose path is greyed out

### ISSUE THREAD

**Issue by WCramRTC** [desktop/desktop#13927]
### Describe the bug
When trying to initialize a local folder ( a basic website in my case ) the Local Path doesn't update with the folder directory I'm trying to add, and doesn't allow me to manually change it. It tries to initialize an old folder or a default location on a different drive.  This happens if I drag the folder onto the GitHub desktop app or the Add Repository menu option. I can only properly add if I initialize manually through bash, then add repo with Desktop.

This is a brand new issue as of yesterday, 02/15/2022.

### Version & OS
GH Desktop: 2.9.8
Windows 11

### Steps to reproduce the behavior

Menu Version
1. Click on File
2. Click Add Local Repository
3. Choose folder I want to add
4. Select Create a Repository when prompted
5. Local Path has not changed and I am unable to change.

Same result if I drag the folder onto desktop to prompt add local repo

### Expected behavior

The local path on the "Create a new repository" popup changes to the folder directory that I want to initialize.

### Actual behavior

The local path on the "Create a new repository" popup contains an old repository directory, or a default directory on a different drive. The choose button by the local path field is inactive and I am unable to change the directory.

### Screenshots

![image](https://user-images.githubusercontent.com/91401050/154421137-dbf4f3c2-b624-4c38-b900-31cd58558676.png)
The name is the name of the folder and director, the Topic_Examples path is from an old repo.

### Additional context

This seems to have happened after I updated to the latest version of the Desktop app. I haven't tested on my laptop, which hasn't been updated yet, to see if I get a similar result.

**Comment by DavidTs93** [comment]
This is the exact [same problem](https://github.com/desktop/desktop/issues/13909) I'm having! (clearing that folder doesn't solve the problem)

**Comment by sergiou87** [comment]
Thanks for your report @WCramRTC !! ❤️ 

As @DavidTs93 mentions, this is the same as #13909 so I'm closing yours in favor of that one.

In any case, I've already addressed the issue in https://github.com/desktop/desktop/pull/13928 and hopefully will be fixed in the upcoming release, soon 😄
