### ISSUE TITLE
Getting error "/usr/bin/env: ‘bash’: No such file or directory" when committing after update.

### ISSUE THREAD

**Issue by Metsuryu** [desktop/desktop#13929]
### Describe the bug

Yesterday I uninstalled node.js and installed nvm to update node to version 16.13.2, and today when I tried to push anything, I get this error: /usr/bin/env: ‘bash’: No such file or directory
I also updated github desktop yesterday, so I'm not sure if the update caused this problem, or if it was the update of node.
Committing from command line, and from Git Extensions works, so it looks like the problem is about Github Desktop specifically.

### Version & OS

Version 2.9.8 (x64) - Windows 10

### Steps to reproduce the behavior

1. Make any change in the repository
2. Click on "Commit to ...."
3. See error: /usr/bin/env: ‘bash’: No such file or directory

### Expected behavior

Until today, commits worked fine.

### Actual behavior

Commits no longer work.

### Logs

[2022-02-17.desktop.production.log](https://github.com/desktop/desktop/files/8088938/2022-02-17.desktop.production.log)

**Comment by steveward** [comment]
@Metsuryu thanks for the issue. Is there a `pre-commit` hook in `.git/hooks` that could be causing this? We've seen these types of errors reported in https://github.com/desktop/desktop/issues/12562.

**Comment by Metsuryu** [comment]
Hi @steveward , yes, there is a pre-commit hook that our team uses to check for lint errors before committing.

**Comment by Metsuryu** [comment]
Doing this worked:
https://github.com/desktop/desktop/issues/12562#issuecomment-1006506536

**Comment by steveward** [comment]
Thanks for the update @Metsuryu. Since we're tracking this in other issues I'm going to close this out.

**Comment by cg-tester** [comment]
Hi @Metsuryu . the reason of error: /usr/bin/env: ‘bash’  is github desktop app ?   what is the solution ? please tell me.

**Comment by Metsuryu** [comment]
@cg-tester  See here: https://github.com/desktop/desktop/issues/12562#issuecomment-1006506536

**Comment by cg-tester** [comment]
@Metsuryu   sorry, not work.
my file
 .husky/pre-commit is
#!/usr/bin/env bash
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged

can you tell me what's wrong ?

**Comment by Metsuryu** [comment]
Ah, I don't know then.
