### ISSUE TITLE
GitHub Desktop insists on the Recycle Bin being active on Windows

### ISSUE THREAD

**Issue by ddesc1234** [desktop/desktop#13924]
### Describe the bug

Since the upgrade to 2.9.8 is seems that you can no longer revert changes on Windows if you have your Recycle Bin set to delete immediately. I don't think this should be a requirement of GitHub Desktop I believe this should be the choice of the Windows user user.

### Version & OS

![image](https://user-images.githubusercontent.com/39615930/154369618-df0fff49-8ace-4e3a-9357-30a92b2e9fa6.png)
![image](https://user-images.githubusercontent.com/39615930/154369723-dd272aa7-c29b-4efb-ac43-bf9e7d92817a.png)

### Steps to reproduce the behavior

1. Make sure your Recycle Bin is set to delete immediately
1. Change a file in your repo folder
2. Go to GitHub Desktop
3. Try to revert the file
4. See error "Failed to discard changes to Recycle Bin. A common reason for this is that the Recycle Bin is set to delete items immediately."

### Expected behavior

File should be reverted since I have chosen not to use my Recycle Bin ( I don't mind if there's a warning prompt ).

### Actual behavior

I get an error, file is not reverted.

### Screenshots

![image](https://user-images.githubusercontent.com/39615930/154369281-850d4fe0-9d7b-4fbd-ae2d-20db97f54d6c.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by sergiou87** [comment]
Thanks for your feedback @ddesc1234 ! ❤️ 

We're already tackling that in https://github.com/desktop/desktop/pull/13904 and will be out in the next release.

**Comment by Aryabroo** [comment]
git reset --hard
