### ISSUE TITLE
Installation failed on windows 10

### ISSUE THREAD

**Issue by EverlynRochefort** [desktop/desktop#13931]
### Describe the bug

I'm trying to install github desk from the main web https://desktop.github.com/ but it kept saying "Installation failed", done it like 4x times already, also alr try to run it on admin with anti-virus off still not working. 

I also went through some similar issues on this repo but non of them related to mine.

### Version & OS

GitHubDesktopSetup (newest)
Windows (x64)

### Steps to reproduce the behavior

Download setup.exe on the main website and run it 

### Expected behavior

Installed

### Actual behavior

"Installation has failed"

### Screenshots

![github-failed-message](https://user-images.githubusercontent.com/69831958/154518878-aa1015cc-7c17-4d93-b2ef-dc6ae1259b7f.png)

### Logs

Done it but it doesn't show anything (got one tho, but i don't think this log even related to github but idk)
[SquirrelSetup.log](https://github.com/desktop/desktop/files/8090184/SquirrelSetup.log)

### Additional context

The only file i found related to github
![ss](https://user-images.githubusercontent.com/69831958/154519488-bbdaa8a0-2b70-4fe5-97df-c51246e7ca07.png)

**Comment by sergiou87** [comment]
Could you delete that `SquirrelTemp` directory completely and then try to install it again? 🤞

**Comment by EverlynRochefort** [comment]
@sergiou87 still does not work :/

**Comment by steveward** [comment]
@EverlynRochefort are you running any antivirus/security software on your machine that could be blocking the installation? Unfortunately the setup log isn't showing much.

**Comment by sergiou87** [comment]
@EverlynRochefort we just released another version that can be downloaded from https://desktop.github.com , could you try that one?

**Comment by EverlynRochefort** [comment]
@sergiou87 success :), thanks for the support
