### ISSUE TITLE
Not enough memory resources are available to process this command when logging in.

### ISSUE THREAD

**Issue by puppimaniax13** [desktop/desktop#13937]
### Describe the bug
I try to sign into my GitHub account and I am able to go through the process except once done in the browser when I click the "Open GitHub.exe" on chrome, it opens GitHub Desktop but I am left not signed in and with a **Not enough memory resources are available to process this command.**

### Version & OS

GitHub Desktop Version 2.9.9 (x64)
Windows 10 Pro Build 19042.1526

### Steps to reproduce the behavior

1. Open GitHub Desktop App (Not Logged In Yet)
2. Click Sign In to GitHub.com
3. Click continue to browser.
4. Sign in on browser.
5. Click the "Open GitHub.exe" pop up.
6. Error Pops Up

### Expected behavior

The expected behavior is to be able to log into my account on the GitHub Desktop App.

### Actual behavior

I am unable to log into my account on the GitHub Desktop App, therefore unble to make/edit/publish a repository.

### Screenshots

![Error](https://user-images.githubusercontent.com/52646241/154590394-88fd09c8-bf98-443b-9351-46d4a06a589f.gif)

### Logs

2022-02-17T23:40:33.991Z - info: [ui] [AppStore] loading 2 repositories from store
2022-02-17T23:40:34.570Z - info: [ui] launching: 2.9.9 (Windows 10.0.19042)
2022-02-17T23:40:34.571Z - info: [ui] execPath: 'C:\Users\becke\AppData\Local\GitHubDesktop\app-2.9.9\GitHubDesktop.exe'
2022-02-17T23:40:44.861Z - info: [ui] [SignInStore] initializing OAuth flow
2022-02-17T23:40:44.862Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=a090e413-0632-4f1e-8fd0-5f1a4b4ad93c
2022-02-17T23:40:46.796Z - info: [main] Received possible protocol arguments: 4
2022-02-17T23:40:46.796Z - info: [main] Processing protocol url
2022-02-17T23:40:46.799Z - info: [ui] [Dispatcher] requesting authenticated user
2022-02-17T23:40:47.159Z - info: [ui] [SignInStore] account resolved
2022-02-17T23:40:47.159Z - info: [ui] [AppStore] adding account puppimaniax13 (Becker Geiger) to store
2022-02-17T23:40:47.161Z - error: [ui] Error adding account 'puppimaniax13'
Error: Not enough memory resources are available to process this command.

### Additional context

I have tried a variety of things such as changing my browser from chrome to microsoft explorere, uninstalling and reinstalling as well as a CMD and Regedit method for the Not Enough memory error, which all have not helped.

**Comment by tsvetilian-ty** [comment]
@puppimaniax13, this issue looks similar to #13754. Can you check if you have a "GitHub - " entry in Windows Credential Manager? 
Control Panel > User Accounts > Credential Manager > Select Windows Credentials

**Comment by puppimaniax13** [comment]
It was randomly fixed... I guess just restart computer a couple times and you're good.

**Comment by xbmspeccy** [comment]
I have the exact same error above. I've tried various solutions with no avail. I'm pretty new to all things Git.

I've tried using GitBash, GitKracken (With limited success, but endless login prompts), GitDesktop (See screenshot)
![Screenshot 2022-04-09 231803](https://user-images.githubusercontent.com/80379085/162599904-2b8c5523-a3d6-4a28-bee7-a98acfdb3e5c.png)

**Comment by pixel-streamer** [comment]
I'm having the same problem, and I have git gui installed too. Not sure what's happening. I'm trying to log-in through the browser (Firefox and Chrome) and both have a problem. The squirrel isn't finding the git, due to the logs- plus the app is already approved because I'm on a new laptop. Even the email is set up the same. It just refuses to log in.

**Comment by gatorlanphear** [comment]
Still having this issue. Windows 11.
I am not github savvy and I am the Administrator on my laptop
![Screenshot 2022-08-28 121554](https://user-images.githubusercontent.com/112341620/188020756-7106a4dc-674d-49b7-8b8f-fae9cd8b7bcf.jpg)

**Comment by sala91** [comment]
Same Issue. Also happens with Meta Messenger from Microsoft Store.

Pretty sure I have memory. Issue has been persisting for long time, surprised to see it pop up in Github client.

CPU: AMD Ryzen Threadripper 2950x 16 Cores, 32 Threads @ 4.2Ghz
CPU HSU: EK-Quantum Velocity sTR4 D-RGB - Nickel + Plexi
MOBO: MSI MEG X399 Creation E-ATX
RAM: CORSAIR Vengeance RGB LED 64GB, 3000MHz DDR4 CL15
VGA: Palit GEFORCE RTX 3090 GamingPro OC 24GB
VGA HSU: EK-Quantum Vector RE RTX 3080/3090 D-RGB - Nickel + Plexi + EK-Quantum Vector RTX 3080/3090 Backplate - Nickel
LCD: 49" Samsung CRG90 5120x1440 120Hz 32:9 HDR
Main Storage: 1 TB NVMe 970 EVO Plus M.2 (R/W: 3000+ MB/s)
Scratch: 4 X 1 TB PCI-E 16X NVMe RAID 0 (R/W: 12000+ MB/s)
Slow Scratch: 2 X 240GB PCI-E 16X NVMe RAID 0 (R/W: 6000+ MB/s)
PSU: Corsair HX1200i
CASE: Liam Li O11 Dynamic XL ROG Edition
DISTRO PLATE: EK-Quantum Reflection PC-O11D XL D5 PWM D-RGB - Plexi
RADS: EK-CoolStream PE 360 (Triple) + EK-CoolStream XE 360 (Triple)
FITTINGS: EK-Quantum Torque HDC 14 x 16 + EK-Quantum Torque Rotary 90° X 6 + EK-Quantum Torque Extender Static MF 14 X 4
LIQUID: EK-CryoFuel Mystic Fog (1800ML)
FANS: Corsair ML120 x 9, LL120 X 1
MOUSE: Logitech G903 + PowerPlay
KEYBOARD: Logitech G915
WEBCAM: Logitech Brio 4K
SOUND: Logitech Z-4i 2.1 / Behringer UMC204HD / NW-700 Mic / SE2200A
OS: Windows 10 Pro for Workstations
NET: Aquantia 10Gbps

**Comment by sala91** [comment]
When I launch the application as administrator, then no error is presented but also no success is being generated. Tried also to launch browsers as admin and log in then still same effect.

**Comment by sala91** [comment]
@tsvetilian-ty there is no github cert in the manager for better or worse.

**Comment by tsvetilian-ty** [comment]
Hey @sala91 The issue appears when there are too many entries in Windows Credential Manager. You can check the workaround mentioned in [here](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#not-enough-resources-error-when-signing-in)

**Comment by sala91** [comment]
Yeah. Seems that Adobe has populated majority of the crential space. Did not know what to do delete, so just went with few of the oldest Adobe Prefetch entries and removed them. Hope it helps anyone else with same issue.

PS: This workaround should be present in the error text. It was really helpful.

**Comment by RedLeggedWarbler** [comment]
@tsvetilian-ty @sala91 I registered here **just** so I could say Thank You. This resolved my problem (and it was Adobe's fault in my case too).
I agree, the error text could be better :-)

**Comment by TommySTYP** [comment]
This solution always work for me.

Go to Control Panel -> User Accounts -> Manage your credentials -> Windows Credentials

Before do anythings below, please do not forget Back up Credentials to make sure you did not remove important credentials accidentally.

After backed up then remove unnecessary or no longer use credentials such as mapping drive, credentials related to old software that you've uninstalled, etc. This way help to free up space of Credentials Manager.

Try to open Github Desktop and see if the problem has been gone to the wind. If yes, congratuation and you will see "Github - https://....." on Generic Credentials

**Comment by nandunag** [comment]
please help to continue  error show in output " Not enough memory available to process your request "  
![sample](https://github.com/desktop/desktop/assets/135817789/541a6bd4-2e87-4f8c-b958-401a0acad300)

**Comment by steveward** [comment]
@nandunag this issue tracker is for GitHub Desktop -- are you running into this issue there?

**Comment by nandunag** [comment]
yes , i am  use Github on desktop

**Comment by steveward** [comment]
Freeing up space in the Credential Manager like what is mentioned [here](https://github.com/desktop/desktop/issues/13937#issuecomment-1491991555) should resolve this issue. Let us know if that doesn't help.

**Comment by Toaster-Ui** [comment]
> @puppimaniax13, this issue looks similar to #13754. Can you check if you have a "GitHub - " entry in Windows Credential Manager? Control Panel > User Accounts > Credential Manager > Select Windows Credentials

I had an old certificate from a random enterprise. I deleted it and my problem was fixed. Thanks :)

**Comment by Fart-dart** [comment]
what the sigma

**Comment by mtycholaz** [comment]
> This solution always work for me.
> 
> Go to Control Panel -> User Accounts -> Manage your credentials -> Windows Credentials
> 
> Before do anythings below, please do not forget Back up Credentials to make sure you did not remove important credentials accidentally.
> 
> After backed up then remove unnecessary or no longer use credentials such as mapping drive, credentials related to old software that you've uninstalled, etc. This way help to free up space of Credentials Manager.
> 
> Try to open Github Desktop and see if the problem has been gone to the wind. If yes, congratuation and you will see "Github - https://....." on Generic Credentials

Just had this issue happen to me and this worked. Thanks!
