### ISSUE TITLE
Show user guides link is broken

### ISSUE THREAD

**Issue by AZProductions** [desktop/desktop#13932]
### Describe the bug
When going to Help - Show User Guides on the window title menu, [the link](https://docs.github.com/desktop/guides) that it opens responds with a 404/error page.

### Version & OS
Version 2.9.8 (x64) on Windows 10 21H1

### Steps to reproduce the behavior

1. Go to the menu
2. Click on 'Help'
3. Scroll down to 'Show User Guides'
4. It opens docs.github.com/desktop/guides which doesn't exist

### Expected behavior

Open a list of guides for Github Desktop

### Actual behavior

Github Desktop opens a link on your default browser which doesn't exist.

### Screenshots
![image](https://user-images.githubusercontent.com/66299945/154523778-5b98d140-610a-4061-9d90-dc033af6fe85.png)
![image](https://user-images.githubusercontent.com/66299945/154524030-db9dd0e3-4d38-4b63-a972-5ce30efde4a6.png)

**Comment by sergiou87** [comment]
Thanks for your report! This was already fixed in #13920 😄  Will be out in one of the upcoming releases, stay tuned!
