### ISSUE TITLE
GitHub CLI broken in M1 Monterey 12.2.1

### ISSUE THREAD

**Issue by offirgolan** [desktop/desktop#13935]
### Describe the bug
Github CLI does not work on M1 Monterey 12.2.1 

### Version & OS

GitHub Desktop Version: 2.9.8 (x64)
OS: MacOS Monterey 12.2.1 M1

### Steps to reproduce the behavior

1. Open a Terminal
2. Enter the command: `github .`

### Expected behavior

It should open GitHub Desktop

### Actual behavior

It crashes with an error.

```
/usr/local/bin/github: line 13: /Applications/GitHub Desktop.app/Contents/MacOS/GitHub Desktop: No such file or directory
```

The `GitHub Desktop` executable exists in that path so not sure why this is erroring.

**Comment by steveward** [comment]
Thanks for the report @offirgolan. I tested this on a non-M1 running 12.2.1 and was unable to reproduce the error. For reference https://github.com/desktop/desktop/issues/13779 was the previous report of this. 

@sergiou87 has an M1 Mac so he should be able to give it a test to see if it's reproducible.

**Comment by sergiou87** [comment]
It works perfectly fine here 😕 

Maybe the `No such file or directory` is not complaining about the `GitHub Desktop` binary but about the folder you're trying to open.

Could you edit `/usr/local/bin/github` to add `-x` at the end of the first line and try again? The first line should look something like this after the change: `#!/bin/sh -x`

That will print out every step the script takes:
```
{9:01}[ruby-3.0.1]~ ➭ github .
++++++ realpath /usr/local/bin/github
++++++ /usr/bin/perl -e 'use Cwd;print Cwd::abs_path(@ARGV[0])' /usr/local/bin/github
+++++ dirname '/Users/sergiou87/Development/GitHub/desktop/dist/GitHub Desktop-dev-darwin-arm64/GitHub Desktop-dev.app/Contents/Resources/app/static/github.sh'
++++ dirname '/Users/sergiou87/Development/GitHub/desktop/dist/GitHub Desktop-dev-darwin-arm64/GitHub Desktop-dev.app/Contents/Resources/app/static'
+++ dirname '/Users/sergiou87/Development/GitHub/desktop/dist/GitHub Desktop-dev-darwin-arm64/GitHub Desktop-dev.app/Contents/Resources/app'
++ dirname '/Users/sergiou87/Development/GitHub/desktop/dist/GitHub Desktop-dev-darwin-arm64/GitHub Desktop-dev.app/Contents/Resources'
+ CONTENTS='/Users/sergiou87/Development/GitHub/desktop/dist/GitHub Desktop-dev-darwin-arm64/GitHub Desktop-dev.app/Contents'
++ ls '/Users/sergiou87/Development/GitHub/desktop/dist/GitHub Desktop-dev-darwin-arm64/GitHub Desktop-dev.app/Contents/MacOS/'
+ BINARY_NAME='GitHub Desktop-dev'
+ ELECTRON='/Users/sergiou87/Development/GitHub/desktop/dist/GitHub Desktop-dev-darwin-arm64/GitHub Desktop-dev.app/Contents/MacOS/GitHub Desktop-dev'
+ CLI='/Users/sergiou87/Development/GitHub/desktop/dist/GitHub Desktop-dev-darwin-arm64/GitHub Desktop-dev.app/Contents/Resources/app/cli.js'
+ ELECTRON_RUN_AS_NODE=1
+ '/Users/sergiou87/Development/GitHub/desktop/dist/GitHub Desktop-dev-darwin-arm64/GitHub Desktop-dev.app/Contents/MacOS/GitHub Desktop-dev' '/Users/sergiou87/Development/GitHub/desktop/dist/GitHub Desktop-dev-darwin-arm64/GitHub Desktop-dev.app/Contents/Resources/app/cli.js' .

+ exit 0
```

**Comment by offirgolan** [comment]
This is the output I got:

```bash
❯ github .
++++++ realpath /usr/local/bin/github
++++++ /usr/bin/perl -e 'use Cwd;print Cwd::abs_path(@ARGV[0])' /usr/local/bin/github
+++++ dirname '/Applications/GitHub Desktop.app/Contents/Resources/app/static/github.sh'
++++ dirname '/Applications/GitHub Desktop.app/Contents/Resources/app/static'
+++ dirname '/Applications/GitHub Desktop.app/Contents/Resources/app'
++ dirname '/Applications/GitHub Desktop.app/Contents/Resources'
+ CONTENTS='/Applications/GitHub Desktop.app/Contents'
++ ls '/Applications/GitHub Desktop.app/Contents/MacOS/'
+ BINARY_NAME='GitHub Desktop'
+ ELECTRON='/Applications/GitHub Desktop.app/Contents/MacOS/GitHub Desktop'
+ CLI='/Applications/GitHub Desktop.app/Contents/Resources/app/cli.js'
+ ELECTRON_RUN_AS_NODE=1
+ '/Applications/GitHub Desktop.app/Contents/MacOS/GitHub Desktop' '/Applications/GitHub Desktop.app/Contents/Resources/app/cli.js' .
/usr/local/bin/github: line 13: /Applications/GitHub Desktop.app/Contents/MacOS/GitHub Desktop: No such file or directory
+ exit 127
```

I ran the final command and it worked...

```bash
❯ ELECTRON_RUN_AS_NODE=1 '/Applications/GitHub Desktop.app/Contents/MacOS/GitHub Desktop' '/Applications/GitHub Desktop.app/Contents/Resources/app/cli.js' .
```

**Comment by sabman** [comment]
Same problem. I tried escaping the spaces in the path but that didn't work. 
My Workaround:

rename `Github Desktop.app` to `Github_Desktop.app` and symlink the binary without space `ln -s GitHub\ Desktop GitHub_Desktop` then modify the bash cli script to use the new binary names as below:

https://gist.github.com/sabman/92cefa88c362893c67ba31b5bb633c64

```bash
#!/bin/sh
set -x

# The least terrible way to resolve a symlink to its real path.
function realpath() {
  /usr/bin/perl -e "use Cwd;print Cwd::abs_path(@ARGV[0])" "$0";
}

CONTENTS="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
BINARY_NAME="$(ls "$CONTENTS/MacOS/")"
BINARY_NAME="GitHub_Desktop"
ELECTRON="${CONTENTS}/MacOS/${BINARY_NAME}"
CLI="${CONTENTS}/Resources/app/cli.js"

ELECTRON_RUN_AS_NODE=1 "${ELECTRON}" "${CLI}" "$@"

exit $?
```

**Comment by sergiou87** [comment]
I just installed Monterey to test this and I couldn't repro it. I wonder if there is anything specific in your setup that could cause this. Do you use macOS' zsh or something else? Do you have anything in your `.(bash|zsh|whatever)_profile` files that could cause this?

The only recent change related to this file was replacing the previous Python command with Perl: #13764

**Comment by offirgolan** [comment]
I think the issue is here:

```bash
BINARY_NAME="$(ls "$CONTENTS/MacOS/")"
```

My `ls` command is aliased to `gls -AFh ${colorflag} --group-directories-first` which is probably causing weird issues. If I set `BINARY_NAME="GitHub Desktop"` the command works.

This is what I get when I run the `ls` command:

```bash
❯ ls "/Applications/GitHub Desktop.app/Contents/MacOS"
'GitHub Desktop'*
```

**Comment by offirgolan** [comment]
I was able to get it to work with changing `ls` to `find`:

```bash
#!/bin/sh

# The least terrible way to resolve a symlink to its real path.
function realpath() {
  /usr/bin/perl -e "use Cwd;print Cwd::abs_path(@ARGV[0])" "$0";
}

CONTENTS="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
ELECTRON="$(find "$CONTENTS/MacOS" -mindepth 1 -print -quit)"
CLI="$CONTENTS/Resources/app/cli.js"

ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"

exit $?
```

**Comment by sergiou87** [comment]
That's very useful @offirgolan, thank you!!

Switching to `find` (or anything else FWIW) could cause the same issue if users have aliased it. Could you try the original script replacing only this line?
```bash
BINARY_NAME="$(command ls "$CONTENTS/MacOS/")"
```

I just added `command` which is supposed to run `ls` ignoring any aliases.

**Comment by offirgolan** [comment]
Ah yeah that's much better. Unfortunately that didn't work for me since my `ls` colors are enabled. Turning off colors ended up working for me:

```bash
BINARY_NAME="$(command ls --color=none "$CONTENTS/MacOS/")"
```

**Comment by sergiou87** [comment]
@offirgolan could you try this instead of `--color=none`, please?
```
BINARY_NAME="$(TERM=dumb command ls "$CONTENTS/MacOS/")"
```

Versions older than Monterey don't have `--color` in `ls` so the command fails 😅

**Comment by offirgolan** [comment]
@sergiou87 that worked for me 🙌

**Comment by sergiou87** [comment]
@offirgolan just to confirm, you tried the TERM=dumb thing, right?

I ask because I initially wrote something different with LSCOLORS and CLICOLORS and changed it later without saying anything, sorry 🤦‍♂️🤦‍♂️

**Comment by offirgolan** [comment]
Haha all good, yeah it works with `TERM=dumb`

**Comment by sergiou87** [comment]
Yay!! Thank you for testing it out and being so quick in your responses 🙇‍♂️
