### ISSUE TITLE
@billygriffin You guys plan on merging this or should I close this? I can also add a screenshots section if you guys want.

### ISSUE THREAD

**Issue by bara55** [desktop/desktop#13946]
@billygriffin You guys plan on merging this or should I close this? I can also add a screenshots section if you guys want.

_Originally posted by @KendallDoesCoding in https://github.com/desktop/desktop/issues/13517#issuecomment-1005417826_

**Comment by KendallDoesCoding** [comment]
@bara55 ?? What is this issue?
