### ISSUE TITLE
Code selection lost when scrolling in split diff

### ISSUE THREAD

**Issue by joyfullservice** [desktop/desktop#13945]
### Describe the bug
If you select several lines of code in the preview pane of the **_split diff_**, then scroll the selection outside the current view, the selection is lost.

### Version & OS

GitHub Desktop Version 2.9.9 (x64)
Windows 10 Pro (x64)

### Steps to reproduce the behavior

Select some lines:

![image](https://user-images.githubusercontent.com/7254992/154764914-bb8652d1-0f8a-4cb0-87d7-404b060bca1e.png)

Use the mouse wheel to scroll the selection _completely_ out of view:

![image](https://user-images.githubusercontent.com/7254992/154765082-c04b5b5b-c834-41e8-aa7b-9f8153bb3ce3.png)

Scroll back up, and the selection is gone:

![image](https://user-images.githubusercontent.com/7254992/154765127-6db7a175-1a91-421d-b410-07c2aaea88c4.png)

### Expected behavior

The selection is preserved when scrolling back into view.

The behavior is correct (selection is preserved) if using the Unified view:

![image](https://user-images.githubusercontent.com/7254992/154765272-8762b949-5852-4089-bb35-eca5e893150d.png)

### Actual behavior

The selection is lost.

**Comment by niik** [comment]
Hey @joyfullservice, this looks identical to https://github.com/desktop/desktop/issues/13945 so I'm going to close this issue in favor of that. Thanks a lot for reporting this and for the detailed screenshots!

**Comment by joyfullservice** [comment]
Thanks @niik! What was the related issue again? (I must have missed it when scrolling through the open issues before I created the issue.) The link above is for _this_ issue, and of course this issue is identical to itself.  😉

**Comment by joyfullservice** [comment]
Ahh, I think I found it. This issue appears to be a duplicate of #13701.

**Comment by niik** [comment]
@joyfullservice that's the one 🤦 copy paste is hard! Thanks for digging up the correct link!
