### ISSUE TITLE
Error when discarding changes, due to Recycle Bin set to delete items immediately.

### ISSUE THREAD

**Issue by AnalyticSpinors** [desktop/desktop#13948]
### Describe the bug
After upgrading GitHub Desktop to version 2.9.9 (x64), whenever attempting to discard items, an error occurs:

Failed to discard changes to the Recycle Bin
A common reason for this is that the Recycle Bin is set to delete items immediately

My Recycle Bin is indeed set this way.  The previous version of Desktop did not exhibit this issue.

### Version & OS

Version 2.9.9 (x64)

### Steps to reproduce the behavior

1. Right click your Recycle Bin and select Properties.
2. Choose "Don't move files to the Recycle Bin. Remove files immediately when deleted."
3. Prefer this setting because it is just better.
2. Make an edit to a file you are tracking.
2. In desktop, right click on the Changed Files header, and select Discard All Changes...

### Expected behavior

Previous versions allowed discarding changes while the Recycle Bin was assigned this setting.

### Actual behavior

I get an error window, which gives me the option to close. No files are discarded.

### Screenshots

![image](https://user-images.githubusercontent.com/18457449/154780523-c40838d3-e7c1-4a31-bf97-2572b6dd1fce.png)

**Comment by sergiou87** [comment]
Sorry about this, it's already being tracked in #13904 and #13888

**Comment by f-rakete** [comment]
This is an issue as well if the repo is stored on a network drive, which by its nature doesn't support the recycling bin. 
So at the moment, I can't even work around this. @sergiou87 Is this fixed? Still exists on  2.9.10 (x64)

**Comment by Mariusio** [comment]
@f-rakete I have the exact same issue. My repo is stored on a network drive and now with the latest version of GitHub Desktop (`Version 2.9.10 (arm64)`) I can't discard changes anymore at all because I always get the attached dialog.
<img width="535" alt="Screenshot 2022-02-28 at 15 22 41" src="https://user-images.githubusercontent.com/3234136/155999214-640d32cc-a372-4c27-9931-c577c1d8bdff.png">

**Comment by BensonSherman** [comment]
I have this issue with an empty recycle bin and no setting for auto delete for my recycle bin. I think the bin was full, and thus auto deleting, but I emptied it and that has not fixed the error.

**Comment by vincent-philippe** [comment]
Same error here

![image](https://user-images.githubusercontent.com/22416140/156137889-193a3591-ae3d-449f-a894-ff4a2cbe7e7f.png)

The recycle bin is **not** set to delete items immediately :

![image](https://user-images.githubusercontent.com/22416140/156139728-11e9829d-b6b9-4dea-9bc1-951e8b2c31c2.png)


(trust me, I know it's in french, but it is write that the recycle bin do not delete items immediately :) )

As a workaround I can still `git checkout filename` the file I wish to discard, so this is not blocking me.

**Comment by anandu06dev** [comment]
> Same error here
> 
> ![image](https://user-images.githubusercontent.com/22416140/156137889-193a3591-ae3d-449f-a894-ff4a2cbe7e7f.png)
> 
> The recycle bin is **not** set to delete items immediately :
> 
> ![image](https://user-images.githubusercontent.com/22416140/156139728-11e9829d-b6b9-4dea-9bc1-951e8b2c31c2.png)
> 
> (trust me, I know it's in french, but it is write that the recycle bin do not delete items immediately :) )
> 
> As a workaround I can still `git checkout filename` the file I wish to discard, so this is not blocking me.

was @ corporate proxy don't have a admin rights to change any system settings, so not able to change the settings ,could you please let me know any other way?

**Comment by ChrisSantiago82** [comment]
Same Issue. And of course, if it's a network drive, you can not enable the bin....

**Comment by ChrisSantiago82** [comment]
@sergiou87 all issues that track this problems are closed. But the problem is still there. Maybe we should reopen this issue again?

**Comment by sergiou87** [comment]
The problem is still there because it has been fixed… but the fix has not been released yet 😅 

You can try out the latest beta from https://github.com/desktop/desktop#beta-channel which includes the fix for this.

**Comment by ChrisSantiago82** [comment]
Ahh, ok. Thank you very much :)

**Comment by vincent-philippe** [comment]
It have been fixed !!! I'm now able to force discard.

![image](https://user-images.githubusercontent.com/22416140/156765377-dc1af52a-c96c-4c41-9c7b-612110a81688.png)

This is great !

😄
