### ISSUE TITLE
Make possible to create folders in the repo list

### ISSUE THREAD

**Issue by daymonoid** [desktop/desktop#13955]
1. Please, make it possible to create folders in the repo list with drag&drop repo into the folder.
2. Allow to create/pull repo with same name in different folders.

**Comment by steveward** [comment]
Thanks for the feedback @daymonoid. See [this comment](https://github.com/desktop/desktop/issues/10201#issuecomment-658693653) for more information about why we do not have plans to implement repository grouping at this time. 

One workaround is to use the repository alias feature and then use that to filter by a specific alias prefix. I hope that helps.
