### ISSUE TITLE
Emojis in commit messages are displayed at initial position

### ISSUE THREAD

**Issue by J-rg** [desktop/desktop#13958]
### Describe the bug

If a commit message contains an emoji, GitHub Desktop displays the emoji in front of the remaining characters of the commit message.

### Version & OS

Version 2.9.9 (x64), macOS 11.6.4

### Steps to reproduce the behavior

1. Type a commit message containing at least one emoji into the summary field, e.g. "Bug 🐛 Report 🐛"
2. Click on 'Commit to _branch_'
3. The commit message is displayed as "🐛🐛Bug Report"

### Expected behavior

Emojis are displayed at their actual position within the commit message.

### Actual behavior

Emojis are displayed at the beginning of the commit message.

### Additional context

In 2.9.6, it displayed as expected.

**Comment by niik** [comment]
This was introduced in https://github.com/desktop/desktop/pull/13914 which we should be able to revert now that https://github.com/desktop/desktop/pull/13930 has been merged.

**Comment by Ploxx73** [comment]
> ### Describe the bug
> If a commit message contains an emoji, GitHub Desktop displays the emoji in front of the remaining characters of the commit message.
> 
> ### Version & OS
> Version 2.9.9 (x64), macOS 11.6.4
> 
> ### Steps to reproduce the behavior
> 1. Type a commit message containing at least one emoji into the summary field, e.g. "Bug bug Report bug"
> 2. Click on 'Commit to _branch_'
> 3. The commit message is displayed as "bugbugBug Report"
> 
> ### Expected behavior
> Emojis are displayed at their actual position within the commit message.
> 
> ### Actual behavior
> Emojis are displayed at the beginning of the commit message.
> 
> ### Additional context
> In 2.9.6, it displayed as expected.
@desktopbot
