### ISSUE TITLE
GitHubDesktop won't open after update

### ISSUE THREAD

**Issue by zaddo67** [desktop/desktop#13952]
### Describe the bug
GitHubDesktop will not launch from toolbar shortcut, menu shortcut or directly when double clicking on .exe
There is nothing showing in windows event logs.  I also couldn't find anything in the GitHubDesktop logs

### Version & OS
GitHubDesktop - 2.9.8 
OS - Windows 11

### Steps to reproduce the behavior

1. Click on Shortcuts or double click on exe
2. Nothing happens

### Expected behavior

I expect githubdesktop to open

### Actual behavior

There is no hourglass or indication that anything is trying to start. The app just does not start.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

The shortcut "Start in" property on the shortcut was pointing at 2.9.7. The logs show that version 2.9.8 had been installed. I tried chanigng the property to 2.9.8, but this did not fix the issue.

An un-install and re-install of GitHubDesktop resolved the issue.

I suspect there was a problem with the update that was applied from 2.9.7 to 2.9.8.

[Squirrel-Update.log](https://github.com/desktop/desktop/files/8103168/Squirrel-Update.log)

**Comment by sergiou87** [comment]
Thank you for your report! We were aware of some issues like you describe with 2.9.7 and 2.9.8, so we released 2.9.9

In this case, I'm afraid you will need to download it from https://desktop.github.com since auto update won't work 😢

We're very sorry about this inconvenience, please let me know if 2.9.9 fixed this issue for you.

**Comment by Roddyyyy** [comment]
i have exactly the same problem, update didnt help

**Comment by sergiou87** [comment]
@Roddyyyy sorry, just to be specific: did you download the latest version from https://desktop.github.com/ and it didn't help?

Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by sergiou87** [comment]
Sorry, of course you won't find your logs like that 🤦 

They should be in `C:\Users\<your user>\AppData\Roaming\GitHub Desktop\logs`

**Comment by Roddyyyy** [comment]
this is another issue we may be facing. I can see github desktop running in task manager so i guess it doesn't create crash log. Also because i have deleted Github desktop folder in roaming and Local before re-installing I don't have the old logs
[2022-02-20.desktop.production.log](https://github.com/desktop/desktop/files/8104906/2022-02-20.desktop.production.log)
![Screenshot 2022-02-20 225128](https://user-images.githubusercontent.com/38702439/154863892-0ab779f7-f03f-46c7-bc47-a6c1f173f7b0.png)

**Comment by Roddyyyy** [comment]
and yes, i did download the latest 2.9.9 version

**Comment by Roddyyyy** [comment]
@sergiou87 👉👈

**Comment by sergiou87** [comment]
Sorry @Roddyyyy I was OOO yesterday. We have a theory about what could be wrong, and we'll have a new build out today with a potential fix 🤞

**Comment by sergiou87** [comment]
@Roddyyyy @zaddo67  could you try the latest beta from https://github.com/desktop/desktop#beta-channel and let me know if it works?

We think the problem you had might be related to #13962 and #13963: when the app starts it crashes trying to log some stuff, then it tries to log the crash and that crashes too, and enters in a crash loop that consumes the CPU as you see. It's just a theory… please give that build a try and if it doesn't work, upload your logs from `C:\Users\<your user>\AppData\Roaming\GitHub Desktop\logs` so we can take a look 🙏

**Comment by Roddyyyy** [comment]
@sergiou87 Well, beta version didn't help either. Log is still pretty empty as before
[2022-02-22.desktop.beta.log](https://github.com/desktop/desktop/files/8116704/2022-02-22.desktop.beta.log)

**Comment by sergiou87** [comment]
Yikes 😢  Thank you for testing. Have you tried moving/renaming/deleting `C:\Users\<your user>\AppData\Roaming\GitHub Desktop` temporarily and then running the app to see if it opens?

That's where the app stores all settings, list of repos you added, etc. Maybe there is something it doesn't like about them with the latest upgrade 🤔

**Comment by zaddo67** [comment]
@sergiou87 As I mentioned in the original post, I managed to get my system working before posting the problem, by doing a complete uninstall/reinstall to version 2.9.9.  I  installed the Beta, to test the new version, and GitHubDesktop is still working.

**Comment by Roddyyyy** [comment]
@sergiou87 still doesnt work :(

**Comment by sergiou87** [comment]
@Roddyyyy I ran out of ideas for now… 😕  Could you try uninstalling and reinstalling the app as `zaddo67` suggests and see if that fixes the issue for you?

**Comment by Roddyyyy** [comment]
sadly no results either 😔

**Comment by sergiou87** [comment]
😐  so sorry @Roddyyyy 

For now the only suggestion I have is to use 2.9.6, hoping that one still works. You can download it from: https://centralreleases.blob.core.windows.net/github-desktop/releases/2.9.6-9196a1ae/GitHubDesktopSetup-x64.exe

**Comment by Roddyyyy** [comment]
2.9.6 is working fine. Turned off auto updates and will stay on this version for some time
https://github.com/desktop/desktop/issues/11455#issuecomment-770424076

**Comment by KendallDoesCoding** [comment]
Do you have a antivirus software that may be blocking it? I suggest you uninstall GitHub Desktop and reinstall the latest version and see if you still face the issue.

**Comment by Roddyyyy** [comment]
updating windows to 22H2 (build 22567) fixed the issue

**Comment by wmullaney** [comment]
Can't open github desktop after windows forced me to update to windows 11. I am getting rid of windows for the last time. I swore I would never use it again but I took a new job and it was already installed on the work computer. I am wiping the computer and putting linux on my work computer asap. I have had it with windows randomly forcing a reboot and installing windows 8, 10, 11 or whatever crap they are trying to push on the market. I have been in the IT industry for 20 years. For while microsoft was a company that would take two steps forward and one step back. Annoying but making progress. It is unbearable at this point going nowhere. Good riddance!

**Comment by leoSryde** [comment]
My Github desktop app stopped working after i upgraded Windows 11 to the latest version (24H2). 

Any plans to release a fix?
