### ISSUE TITLE
Maximize button not working after upgrade to Version 2.9.9

### ISSUE THREAD

**Issue by dinakaranram9** [desktop/desktop#13959]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version 2.9.9 &  Windows 10

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Open Github desktop.
2. Click on maximize icon. Commit gets disappeared below taskbar. Please fix the issue ASAP
### Expected behavior

It has to be maximized properly with commit buttons visible above taskbar

Write a clear and concise description of what you expected to happen.

Commit gets disappeared below taskbar

I has to be maximized properly with commit buttons visible above taskbar

### Describe the bug
Write a clear and concise description of what the bug is.

### Version 2.9.9 &  Windows 10

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Open Github desktop.
2. Click on maximize icon. Commit gets disappeared below taskbar. Please fix the issue ASAP
### Expected behavior

It has to be maximized properly with commit buttons visible above taskbar

Write a clear and concise description of what you expected to happen.

Commit gets disappeared below taskbar

I has to be maximized properly with commit buttons visible above taskbar

### Screenshots
![image](https://user-images.githubusercontent.com/33784891/154890158-0b3f3e3b-ff4e-49f1-9088-b72a96b2c97c.png)

**Comment by tsvetilian-ty** [comment]
Hey @dinakaranram9, your issue looks similar to #13940. Can you give more information about your resolution and if you use scale settings

**Comment by steveward** [comment]
Closing in favor of #13940. Please follow along there for updates.
