### ISSUE TITLE
menssagem de erro ao tentar publicar o conteúdo no repositório remoto

### ISSUE THREAD

**Issue by devLuanPaiva** [desktop/desktop#13969]
error: cannot lock ref 'refs/remotes/origin/main': unable to resolve reference 'refs/remotes/origin/main': reference broken
From https://github.com/Luan029/JavaScript
 ! [new branch]      main       -> origin/main  (unable to update local ref)

**Comment by steveward** [comment]
Thanks for the report @Luan029. Can you try opening the repository in the command line and running `git remote prune origin` to see if that resolves the issue with the broken reference?

Let me know if that does not get things working.
