### ISSUE TITLE
Invisible Error: "Please upgrade your plan to create a new private repository."

### ISSUE THREAD

**Issue by bwestover** [desktop/desktop#1396]
### Description

The default option on the "Publish Repository" dialog is to "Keep this code private":
![image](https://cloud.githubusercontent.com/assets/1987494/25776253/303dda1a-326e-11e7-9482-eed6cddf7d61.png)

This is a good choice to prevent accidental disclosure of a private repo :+1:

However, if a user doesn't have a paid plan, the repo creation will fail silently. At least from the user perspective it's silent. The developer tools console shows this error:
```
Uncaught (in promise) Error: {
  "message": "Please upgrade your plan to create a new private repository.",
  "documentation_url": "https://github.com/pricing"
}


    at renderer.js:3
    at XMLHttpRequest.J.ae.onreadystatechange (renderer.js:3)
```

### Version

**GitHub Desktop version:** 0.0.39
**OS version:** OS X El Capitan (10.11.6)

### Steps to Reproduce

1. Log in with an account that is using the free plan.
1. Add a repository to GitHub Desktop beta that doesn't have any remotes configured.
1. On the toolbar, click Publish Repository**.
1. Fill in a name (or accept the default), and leave "Keep this code private" selected.
1. Click **Publish Repository**.

**Expected behaviour:** I expect an error message stating that I cannot create a private repository without first upgrading my plan.

**Actual behaviour:** The dialog goes away, but visibly nothing else occurs. An error is logged in the developer console.

**Reproduces how often:** 100%

**Comment by CharXu** [comment]
private repository is not free
