### ISSUE TITLE
Trying to login enterprise account

### ISSUE THREAD

**Issue by aiden-shinsegae** [desktop/desktop#13973]
### Describe the bug
I add the repository from the local and tried to publish on to github enterprise repository.
And this error pops up.
<img width="959" alt="image" src="https://user-images.githubusercontent.com/100100743/155248287-9c81708d-5ade-4552-bc3e-edb8442f0680.png">

### Version & OS
Version  : Version 2.9.9 (arm64)
OS : macOS Monterey Version 12.1

**Comment by steveward** [comment]
Thanks for the report @aiden-shinsegae. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by aiden-shinsegae** [comment]
The Log looks like this.

2022-02-23T23:16:08.689Z - error: [ui] fetchMetadata: unable to load metadata from 'https://github.com/api/v3/meta' as a fallback
Error: API error https://github.com/api/v3/meta:  (404)
    at zt (/webpack:/app/src/lib/http.ts:178:11)
    at /webpack:/app/src/lib/api.ts:1611:11
    at Or.endpointSupportsBasicAuth (/webpack:/app/src/lib/stores/sign-in-store.ts:255:11)
    at Or.setEndpoint (/webpack:/app/src/lib/stores/sign-in-store.ts:549:13)

**Comment by steveward** [comment]
@aiden-shinsegae if you are trying to log in to a GitHub Enterprise instance it needs to be a specific URL -- not your username. Apologies for missing that in your image. Let me know if you have any issues with that.

**Comment by aiden-shinsegae** [comment]
Even if I log in to a GitHub Enterprise with specific URL, It returned same result
<img width="399" alt="스크린샷 2022-02-25 오전 8 39 06" src="https://user-images.githubusercontent.com/100100743/155625823-cfa805bd-9cf7-4c67-ba97-d77ee4c67682.png">

**Comment by steveward** [comment]
@aiden-shinsegae do you have a GitHub Enterprise URL you use? If you are wanting to log in with your GitHub Enterprise Cloud account then you can use the regular GitHub.com log in. We're going to update the wording to clarify this better.

**Comment by aiden-shinsegae** [comment]
I Just push origin to github and set the organization, then it pushed into enterprise repository!

**Comment by steveward** [comment]
Glad to hear you were able to get things working!
