### ISSUE TITLE
Local path no longer pre-filled with repo name

### ISSUE THREAD

**Issue by photonstorm** [desktop/desktop#13971]
### Describe the bug

When cloning a repo from GitHub it will launch GitHub Desktop and open the "Clone a repository" window correctly, but the "Local path" option doesn't seem to be pre-filled anymore.

I'm positive in earlier versions that it would automatically create a folder or pre-populate the Local path input with the repo name. 

But now it's always just my default folder with an error saying "This folder contains files. Git can only clone to empty folders". So now I have to copy-paste the repo name from the Repository URL field down to the end of the Local path. I've never had to do this before, it used to happen automatically.

### Version & OS

Version 2.9.9 (x64) - Windows 11.

### Steps to reproduce the behavior

1. Go to any project on GitHub
2. Click on Clone - Open with GitHub Desktop
3. See how the Local path is no longer populated

### Expected behavior

I expect for it to either automatically append the repo name to the Local Path (which I _think_ is what it used to do?), or for you to be able to specify any folder as the Local path and when you click 'Clone' for it to automatically create a folder based on the name of the repo.

### Screenshots

![image](https://user-images.githubusercontent.com/164476/155175391-f37795f5-9a86-4c21-b645-6adbb840ed40.png)

**Comment by sergiou87** [comment]
Thanks for your report! ❤️  I managed to reproduce this, we'll try to fix it for one of our upcoming releases.

**Comment by MamasavageYa** [comment]
What
