### ISSUE TITLE
Update text for master branch

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1400]
As https://github.com/desktop/desktop/pull/1336 updated the default branch name, we should update the text seen here as "master" branch isn't necessarily accurate:

<img width="387" alt="screen shot 2017-05-08 at 11 02 33 am" src="https://cloud.githubusercontent.com/assets/14828183/25810439/20780c1a-33de-11e7-93ea-7c66943fb1fb.png">

v0.0.039, OSX 10.11.5

**Comment by shiftkey** [comment]
@tierninho could you provide some repro steps before we mark this as `up-for-grabs`?

**Comment by tierninho** [comment]
Looks like this was fixed as I cannot reproduce. Closing.
