### ISSUE TITLE
git ignore

### ISSUE THREAD

**Issue by ahmadalikhani** [desktop/desktop#14008]
### Describe the bug
git ignore file does not work correctly 
in some cases can not ignore files and add them in commits
i added that file Avon file and all files that have the same extension to .gitignore file
but i see them in github desktop and when i commit a change , All those files exist in commit

### Version & OS

Version 2.9.10 (x64)

**Comment by steveward** [comment]
Thanks for the issue @AhmadAlikhani.  If the files have been previously committed in your repository they need to removed prior to being ignored. You'll need to run this command from the command line:

`git rm --cached <file>`

You should then be able to ignore the files. You can find more information in [this help article](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files). Let me know if you run into any issues.

**Comment by ahmadalikhani** [comment]
thanks alot
