### ISSUE TITLE
Problem report popup on app open

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#14005]
Problem report dialog popup each time the app is opened. Removing and reinstalling app does not resolve the issue. Occurs with beta channel, as well.

<img width="600" alt="Screen Shot 2022-02-24 at 11 24 45" src="https://user-images.githubusercontent.com/1542238/155515531-cec3bca8-dc50-4727-b373-fe8cff35bed9.png">

**Comment by sergiou87** [comment]
Thanks for your report @thosbsamsgom! We're tracking this problem from #13974 so please subscribe to that one if you want to be notified when we make progress about it 😄
