### ISSUE TITLE
Crash on launch, but app still appears

### ISSUE THREAD

**Issue by gingerbeardman** [desktop/desktop#14018]
### Describe the bug

Crash on launch, app still appears though

### Version & OS

GitHub Desktop: 2.9.10 (x64)
macOS: 10.14.6 (18G9323)

### Steps to reproduce the behaviour

1. Open GitHub Desktop 2.9.10
2. Crash report
3. App appears

### Expected behaviour

- no crash reports on launch

### Actual behaviour

- crash report on launch

### Logs

- [2022-02-26.desktop.production.log.zip](https://github.com/desktop/desktop/files/8147575/2022-02-26.desktop.production.log.zip)

### Additional context

- [15 crash reports](https://github.com/desktop/desktop/files/8147579/Crashes.zip)

**Comment by gingerbeardman** [comment]
Maybe dupe of #13974 and #13912

**Comment by mackonsti** [comment]
I confirm too this behaviour on macOS Catalina 10.15.7 with latest GitHub Desktop client v2.9.10.
The application seems to work without hiccups, closes OK but upon each relaunch, I get a crash dialog as well "GitHub Desktop quit unexpectedly" together with the application itself...

**Comment by gingerbeardman** [comment]
I downloaded an old version but there seems to be no way to stop it updating, so I have to reinstall/unzip the old version after every launch. What a mess.

**Comment by m-r-m-s** [comment]
> I confirm too this behaviour on macOS Catalina 10.15.7 with latest GitHub Desktop client v2.9.10. The application seems to work without hiccups, closes OK but upon each relaunch, I get a crash dialog as well "GitHub Desktop quit unexpectedly" together with the application itself...

I am having the exact same behavior you describe on 10.14.6 (same specs and behavior as reported above: https://github.com/desktop/desktop/issues/14018#issue-1152352195)

**Comment by niik** [comment]
Hey @gingerbeardman! Yup, this is the same issue as is described in https://github.com/desktop/desktop/issues/13974. We're investigating and hopefully we'll find a safe solution soon. In the meantime the app should work just fine if you choose to dismiss that crash dialog.

I'm closing this in favor of https://github.com/desktop/desktop/issues/13974!
