### ISSUE TITLE
GitHub Desktop keeps prompting to install helper on MacOS Monterey

### ISSUE THREAD

**Issue by crotalis** [desktop/desktop#14013]
Since moving to Monterey 12.2 last week, I've been getting almost continuous prompts "An update is ready to install. GitHub Desktop is trying to add a new helper tool. Enter your password to allow this.

I could understand seeing this once, or occasionally. But it is very frequent.

What is going on? How can I fix it?

**Comment by steveward** [comment]
Thanks for the report @crotalis. We had a recent report of this in https://github.com/desktop/desktop/issues/13956, but haven't been able to reproduce this behavior. Is GitHub Desktop in your `/Applications` directory?

**Comment by obchodniuspech** [comment]
it seems delevopers are really patient people :D i was clicking it every hour for like 2 months :D

**Comment by crotalis** [comment]
Steveward - yes, it is in the /Applications directory. It will give me the prompts, I give the password, it will immediately repeat - this goes on a few times then goes away for some time.

**Comment by niik** [comment]
Thanks for the extra details @crotalis. We'll be investigating this in #13956 so please subscribe to that issue to follow along!
