### ISSUE TITLE
Upstream broken

### ISSUE THREAD

**Issue by Ironic8b498** [desktop/desktop#14011]
### Describe the bug
Took a while to notice, but the silent upstream never worked and I have no clue how to reconnect my projects

### Version & OS

2.9.10 x64 Windows 10 21H2

### Steps to reproduce the behavior

1. Go to '...' click Git update button
2. Click on '....' OK Merge incoming
3. Scroll down to '....' lower right corner to see error message
4. See error Can't update master has no tracked branch

### Expected behavior

update my code on GitHub website

### Actual behavior

nothing happened

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

Might be something I did, just need to know how to fix

**Comment by steveward** [comment]
Thanks for the issue @Ironic8b498. Can you clarify what specific issues/errors you are seeing? Are your `upstream` branches not updating in GitHub Desktop? Any extra details you can share would be helpful.
