### ISSUE TITLE
Advertise Beta Version of Github Desktop on Main Website

### ISSUE THREAD

**Issue by uttiya10** [desktop/desktop#14015]
### Describe the feature or problem you’d like to solve

Currently, the only way to download the beta version of Github Desktop is through this github's repository README file.
Therefore, many people, including me, might not have been aware of this seperate build.

### Proposed solution

Adding a download link for the beta version on the homepage will increase awareness, which can result in more beta testers finding issues before they affect the public.

### Additional context

VSCode includes a link to the beta/insider version directly from the download page:
![image](https://user-images.githubusercontent.com/56562649/155809563-ce24ddb1-49df-4a5e-af9a-bc82289f1d25.png)

**Comment by steveward** [comment]
Thanks for the issue @uttiya10. Promoting the beta more is actually something we've been actively discussing, since we'd like to increase our pool of beta users.

**Comment by tidy-dev** [comment]
:tada: Done! [Beta download page](https://desktop.github.com/beta/) added.
