### ISSUE TITLE
Windows Environment Variable for PATH after app update

### ISSUE THREAD

**Issue by hl2guide** [desktop/desktop#14010]
### Describe the bug
The Windows Environment Variable for PATH is not correctly updated after a new application update is applied.

e.g. Version 2.9.9 is updated to 2.9.10, PATH value remains as:
```
C:\Users\Dean\AppData\Local\GitHubDesktop\app-2.9.9\resources\app\git\mingw64\bin
```

### Version & OS

Version 2.9.10 (x64)
Windows 10 21H2

### Steps to reproduce the behavior

1. Install an app update
2. Check the PATH value for GitHub Desktop

### Expected behavior

PATH is updated.

### Actual behavior

as above

**Comment by steveward** [comment]
Thanks for the report @hl2guide. I would not recommend using GitHub Desktop's internal Git as it's solely intended for use by the app itself, and is not fully-featured. I'd recommend installing Git for Windows and adding it to your PATH during the install process.

Let me know if you have any further questions.
