### ISSUE TITLE
Commiting to wrong directory

### ISSUE THREAD

**Issue by musthafaCoder** [desktop/desktop#14016]
### Describe the bug
I was cloning a empty repository to my local using GitHub desktop, after cloning the current repository showing as another repository name, not the one  cloned from git. And after the commit the files replaced from another project, nothing updated in cloned repository I lost all my old repository changes that was very  important to me

### Version & OS
Version 2.9.10 (x64)
OS: Windows 10 Pro ,21H2

### Steps to reproduce the behavior

1. clone a repository
2. Shows another repository name as current repository not the one cloned in GitHub desktop
3. Commit the changes to repository ,Replaced files from another repository

### Expected behavior

Should be committed to exact cloned  repository 

### Actual behavior

Commiting to wrong repository after cloning

### Screenshots
Add screenshots to help explain your problem, if applicable.
![image](https://user-images.githubusercontent.com/42212466/155841837-316a82a5-2f09-4294-bb53-2d4d4c1e3e59.png)

**Comment by steveward** [comment]
Thanks for the report @musthafaCoder. Could you upload a log file from the day you clone this repository? That should hopefully give some more information about this.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.
