### ISSUE TITLE
The application opens with a white screen

### ISSUE THREAD

**Issue by ahanna-WWN** [desktop/desktop#14020]
### Describe the bug
The application opens as a white screen and is not responsive.

Opening the developer tools the console is empty as it nothing is loaded.

![image](https://user-images.githubusercontent.com/100567814/155966949-9cb4fdfa-8a73-487c-9348-43062a78643f.png)

### Version & OS

Cannot open the about as the menus are not visible. But going to appData I can see these folders in the Github Desktop folder:

![image](https://user-images.githubusercontent.com/100567814/155967252-4dcbf004-fcc8-4d8b-94a4-8d23cba4f7cd.png)

I'm on Windows 10

### Steps to reproduce the behavior

1. Open the application.

### Expected behavior

The application should load.

### Actual behavior

The application shows as an unresponsive white screen

### Screenshots

![image](https://user-images.githubusercontent.com/100567814/155967579-c7de846b-2eb6-4679-9e7c-32111ac08833.png)

![image](https://user-images.githubusercontent.com/100567814/155967626-f22a288d-5845-4677-a4f1-54ec983f3a5c.png)

### Logs

the following log is from the `AppData/Roaming/Github Desktop/logs`

```
2022-02-28T10:10:37.871Z - info: [main] Received possible protocol arguments: 2
2022-02-28T10:10:37.873Z - error: [main] Malformed launch arguments received: C:\Users\****\AppData\Local\GitHubDesktop\app-2.9.10\GitHubDesktop.exe,--allow-file-access-from-files
2022-02-28T10:13:01.179Z - info: [main] Received possible protocol arguments: 2
2022-02-28T10:13:01.181Z - error: [main] Malformed launch arguments received: C:\Users\****\AppData\Local\GitHubDesktop\app-2.9.10\GitHubDesktop.exe,--allow-file-access-from-files
2022-02-28T10:13:46.539Z - info: [main] Received possible protocol arguments: 2
2022-02-28T10:13:46.539Z - error: [main] Malformed launch arguments received: C:\Users\****\AppData\Local\GitHubDesktop\app-2.9.4\GitHubDesktop.exe,--allow-file-access-from-files
2022-02-28T10:24:46.850Z - info: [main] Received possible protocol arguments: 2
2022-02-28T10:24:46.852Z - error: [main] Malformed launch arguments received: C:\Users\****\AppData\Local\GitHubDesktop\app-2.9.10\GitHubDesktop.exe,--allow-file-access-from-files
```

### Additional context

I can temporarily solve the issue by uninstalling and reinstalling the application but it occurs every few days.

**Comment by steveward** [comment]
Thanks for the report @ahanna-WWN. We had a previous report of this (https://github.com/desktop/desktop/issues/13906) that was due to upgrading Electron. This should be resolved in v2.9.10. 

Have you tried a full fresh install to see if that gets things working? These are the steps you would need to take:

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to ` %AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

You will need to log in and add your repositories again after performing these steps (drag-and-drop is the quickest way to do this). Let me know if that helps.

**Comment by ahanna-WWN** [comment]
@steveward Hey thanks for the fast reply. Unfortunately the app does not open anymore it just shows up in the Task manager > Details and these are the commandlines for these instances
![image](https://user-images.githubusercontent.com/100567814/156127396-f19d05e6-3d9b-4ee8-97a2-8b281e04b1a9.png)

This is the log file:

```
2022-03-01T07:33:56.956Z - info: [main] Received possible protocol arguments: 2
2022-03-01T07:33:56.975Z - error: [main] Malformed launch arguments received: C:\Users\****\AppData\Local\GitHubDesktop\app-2.9.10\GitHubDesktop.exe,--squirrel-firstrun
```

I have been able to run it by downloading the msi installer and extracting the files using 7-zip to another folder and running it from there (C:\Users\****\Downloads\GitHubDesktopSetup-x64.msi Contents\GitHub Desktop Deployment\GitHubDesktopDeploymentTool\GitHubDesktop-2.9.10-full\lib\net45\GitHubDesktop.exe)

**Comment by sergiou87** [comment]
@ahanna-WWN could you try editing the app's shortcut (the one you use to open the app, from the Desktop or the start menu) and add the `--disable-gpu` parameter to see if it works?

We've recently seen "blank screen" issues related to GPU problems (#13906) and running the app with `--disable-gpu` helped there 🤞

**Comment by ahanna-WWN** [comment]
@sergiou87 It works with the --disable-gpu parameter. And doesn't without it. However the one I extracted from the msi installer works perfectly without the parameter.

Executing through git bash doesn't give the errors seen in #13906 ([comment](https://github.com/desktop/desktop/issues/13906#issuecomment-1042719690))
![image](https://user-images.githubusercontent.com/100567814/156348515-04ce618d-e8d9-4998-9dd4-fad1efb55f7c.png)

Also my username is five lowercase letters and does not include any special characters as suggested in ([comment](https://github.com/desktop/desktop/issues/13906#issuecomment-1041975101))

If you want any further debug information I will gladly help.

BTW my GPU is Intel UHD Graphics 630 integrated in the i3-10100 CPU. I tried restarting the graphics driver (via Win+Ctrl+Shift+B) but nothing changed.

**Comment by sergiou87** [comment]
Wow!! Thank you so much for such detailed information 🙇‍♂️ 

> However the one I extracted from the msi installer 

I'm sorry, what do you mean exactly? Installing GH Desktop from the `.exe` installer fails without the parameter and installing it from the `.msi` installer works without the parameter? 😳

**Comment by ahanna-WWN** [comment]
> I'm sorry, what do you mean exactly?

I have been able to run it by downloading the msi installer and extracting the files using 7-zip to another folder and running it from there (C:\Users****\Downloads\GitHubDesktopSetup-x64.msi Contents\GitHub Desktop Deployment\GitHubDesktopDeploymentTool\GitHubDesktop-2.9.10-full\lib\net45\GitHubDesktop.exe)

First I extracted the msi installer `GitHubDesktopSetup-x64.msi`:
![image](https://user-images.githubusercontent.com/100567814/156458602-3122d5ea-9b7b-45a8-9c18-455341c9f121.png)
![image](https://user-images.githubusercontent.com/100567814/156458626-ef30952f-d416-4c39-925a-a0e012b2c45e.png)

Then I extracted the `GitHubDesktopDeploymentTool.exe` using 7-zip:
![image](https://user-images.githubusercontent.com/100567814/156458774-03631eb6-54d5-4543-828b-3c6342feb65e.png)

Then I extracted the `GitHubDesktop-2.9.10-full.nupkg` also using 7-zip:
![image](https://user-images.githubusercontent.com/100567814/156459920-1aaae1c3-5cc5-45ec-9b53-23e43029d15d.png)

Finally I started the application from the resulting files (from `\lib\net45\GitHubDesktop.exe`):
![image](https://user-images.githubusercontent.com/100567814/156458982-df750b82-6cc9-480f-8c61-f85a50cd65f9.png)

I tried copying the `net45` filder to the GitHubDesktop folder in `AppData\Local` but it didn't run. and tried copying the `app-2.9.10` folder to another folder outside `AppData\Local` and it worked perfectly.

Also I noticed that every executable inside the `AppData\Local\GitHubDesktop` folder seems to lose its icon:
![image](https://user-images.githubusercontent.com/100567814/156461707-e86f229a-4480-4766-b733-4ddfab052744.png)
![image](https://user-images.githubusercontent.com/100567814/156461709-b6b5a12e-6a2d-4fe9-aa8b-86b16993adf6.png)
![image](https://user-images.githubusercontent.com/100567814/156461715-792ac124-f373-44ae-b930-78df6f58eb07.png)

And when I copied the `app-2.9.10` folder to another location the icons reappeared.

Hope this helps. I'm available for any further information/testing.

PS: Installing the application from the msi installer did not affect the bug.

**Comment by ahanna-WWN** [comment]
Upon further inspection, I noticed that the case sensitivity for the file names is enabled in the folder `AppData\Local\GitHubDesktop`.

I disabled it and it worked without the `--disable-gpu` parameter. However, the icons didn't return 😕
Hope this helps.

**Comment by sergiou87** [comment]
> I noticed that the case sensitivity for the file names is enabled in the folder

As far as I can see, that attribute is disabled for me. I wonder how got that enabled in your case, but I'm glad that fixed the issue.

Do you get both icons + the app working without `--disable-gpu` if you reinstall the app completely and make sure case sensitivity is disabled?

**Comment by ahanna-WWN** [comment]
No, the icons didn't return. And I had to re-disable the Case Sensitive flag after the complete deletion of the folders (in Local and Roaming).

In any case, the application is working again, thank you.
I will investigate further into it in a couple of days.

**Comment by niik** [comment]
> In any case, the application is working again, thank you.

I'm glad to hear you got it working again @ahanna-WWN, I'm gonna close this issue to try and keep our open issues at bay but feel free to comment again or open a new issue if the problem returns.
