### ISSUE TITLE
Github Desktopo couldn't find my repositories

### ISSUE THREAD

**Issue by adriano-asinc** [desktop/desktop#14026]
### Describe the bug
I loaded the Github Desktop App, version 2.9.9 (x64), and it started opening error windows, saying "Geit returned an unexpected exit code '3221225781' which should be handled by the caller.'", and it keep showing these pop-up windows until it just showed the 'Can't find "[repository name]", and showing the last path seen, and if you follow that path, you reach the file folder.

### Version & OS

Github Desktop Version 2.9.9 (x64)
OS Windows 10 Pro, 64 bits

### Steps to reproduce the behavior

1. Execute the Github Desktop App
2. Pop-ups errors start showing.

### Expected behavior

Normal use of the Github App

### Actual behavior
Executed the Github App, it stat showing the errors pop-ups, can't find the repositories location.

### Screenshots

![ErroGit5](https://user-images.githubusercontent.com/70326203/156003551-b04e858d-b143-410c-b9c2-16968478bdd5.png)
![ErroGit6](https://user-images.githubusercontent.com/70326203/156003855-5d0c715b-6019-42bf-aae8-b9b08a7f910b.png)
![ErroGit7](https://user-images.githubusercontent.com/70326203/156004115-be7ef12e-fd3e-4541-a513-9f1b47889383.png)

### Log

[2022-02-28.desktop.production.log](https://github.com/desktop/desktop/files/8154219/2022-02-28.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @adriano-asinc. In [one other instance](https://github.com/desktop/desktop/issues/9434) of this error a simple restart resolved the issue. Could you try that and let us know if it gets things working? If not, we can dig into this further.
