### ISSUE TITLE
Haxe gitignore template

### ISSUE THREAD

**Issue by SlickFromMars** [desktop/desktop#14027]
### Describe the feature or problem you’d like to solve

We should add a Haxe/Flixel gitignore template.

### Proposed solution

Those who use haxeflixel can easily gitignore files.

### Additional context

```gitignore
### VS Code
export/*
.vscode/*
*.code-workspace
# Local history which shouldn't be shared.
.history
.ionide
# ! means a file should be added regardless of it it gets ignored prior.
# Including to allow others to use already set-up configuration tweaked for the project.
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
vscode-project.hxml
```

**Comment by steveward** [comment]
Thanks for the issue @SlickFromMars. It looks like Haxe has not yet been added as a template, see https://github.com/github/gitignore/pull/3455. Once that is merged in it will be brought in to GitHub Desktop when we update  our .gitignore submodule.
