### ISSUE TITLE
Discarding Changes to Recycle Bin on Mapped Network Drive

### ISSUE THREAD

**Issue by PeteAUK** [desktop/desktop#14033]
### Describe the bug
This previously worked, but attempting to discard changes to a file now fails because it attempts to discard them to the Recycle Bin.  If the files are on a mapped network drive then there is no Recycle Bin.

### Version & OS

Version 2.9.10 (x64).  Windows 10

### Steps to reproduce the behavior

1. Right-click on file and select "Discard Changes"
2. Confirm I wish to discard changes to the file
3. Receive error: "Failed to discard changes to Recycle Bin. A common reason for this is that the Recycle Bin is set to delete items immediately."

### Expected behaviour

Changes discarded without putting into recycle bin because network shares don't have a recycle bin

### Actual behaviour

I get an error and changes haven't been discarded.

### Screenshots

![image](https://user-images.githubusercontent.com/893132/156149452-99f67dd2-d558-40c9-bb1c-77d8a8a93ecf.png)

### Logs

022-03-01T10:06:42.402Z - error: [ui] Failed discarding changes
Error: Error invoking remote method 'move-to-trash': Error: Failed to perform delete operation
    at EventEmitter.i.invoke (node:electron/js2c/renderer_init:57:526)
    at C:\Users\Pete\AppData\Local\GitHubDesktop\app-2.9.10\webpack:\app\src\lib\stores\git-store.ts:1462:62
    at C:\Users\Pete\AppData\Local\GitHubDesktop\app-2.9.10\webpack:\app\src\lib\queue-work.ts:39:5
    at Es.discardChanges (C:\Users\Pete\AppData\Local\GitHubDesktop\app-2.9.10\webpack:\app\src\lib\stores\git-store.ts:1457:50)
    at Pr._discardChanges (C:\Users\Pete\AppData\Local\GitHubDesktop\app-2.9.10\webpack:\app\src\lib\stores\app-store.ts:4356:5)
    at Object.RS.discard [as onSubmit] (C:\Users\Pete\AppData\Local\GitHubDesktop\app-2.9.10\webpack:\app\src\ui\discard-changes\discard-changes-dialog.tsx:153:42)

### Additional context

-

**Comment by sergiou87** [comment]
Thanks for your report @PeteAUK ! ❤️ 

We were tracking this problem in #13363 and this specifically was addressed in #13904 by adding a new confirmation dialog when those changes will be discarded permanently. We'll ship a release soon with this fix.

Sorry about this inconvenience and thank you for your patience 🙇‍♂️
