### ISSUE TITLE
Make website open-source

### ISSUE THREAD

**Issue by KendallDoesCoding** [desktop/desktop#14030]
https://desktop.github.com/ should be open source.

**Comment by niik** [comment]
Hey @KendallDoesCoding, thanks for reaching out. We discussed this internally and while it could be interesting in the future we would need to audit that repository history prior to open sourcing it as it's been around for many years and we don't have the bandwidth to do so at this time. Should we find ourselves doing a major rework of that site we'll definitely consider opening it up though.

**Comment by KendallDoesCoding** [comment]
> Hey @KendallDoesCoding, thanks for reaching out. We discussed this internally and while it could be interesting in the future we would need to audit that repository history prior to open sourcing it as it's been around for many years and we don't have the bandwidth to do so at this time. Should we find ourselves doing a major rework of that site we'll definitely consider opening it up though.

Ok cool. I just thought of the idea. As, it would be very cool incase there's any issues, people can fix it as well, instead of the Desktop team, so that way yall can focus on "Github Desktop" and that in itself, coz ik yall are busy people! but fair points stated by you.
