### ISSUE TITLE
Release notes on GitHub

### ISSUE THREAD

**Issue by KendallDoesCoding** [desktop/desktop#14032]
### Describe the feature or problem you’d like to solve

I know the release notes already exist on the website at https://desktop.github.com/release-notes/ 

### Proposed solution

It will be very useful if it exists on the repo too, for the people just looking around at the repo, according to me.

### Additional context

priority: low

**Comment by tidy-dev** [comment]
@KendallDoesCoding Thanks for the suggestion! The release notes there are updated each release by pulling from the [changelog](https://github.com/desktop/desktop/blob/development/changelog.json). Thus, at this time, we are not planning for another view of the release notes.

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding Thanks for the suggestion! The release notes there are updated each release by pulling from the [changelog](https://github.com/desktop/desktop/blob/development/changelog.json). Thus, at this time, we are not planning for another view of the release notes.

Ok cool.
