### ISSUE TITLE
Allow multiple users to connect to GitHub Desktop at once

### ISSUE THREAD

**Issue by KendallDoesCoding** [desktop/desktop#14031]
### Describe the feature or problem you’d like to solve

2 people in my house, code, so we both need to use GitHub desktop, the issue is you can only connect to one normal account at once, I believe if its enterprise, you can connect to one normal account and one enterprise account at the same time.. There should be a way to connect 2 normal accounts on GitHub desktop and when committing pick the account you want to commit from.

### Proposed solution

It will let 2 people using the same computer to code and using GitHub desktop.

**Comment by steveward** [comment]
Thanks for the issue @KendallDoesCoding. We are tracking feedback for supporting multiple accounts in https://github.com/desktop/desktop/issues/3707. You can leave a 👍🏻 in that issue to indicate your desire to see this implemented.

**Comment by KendallDoesCoding** [comment]
Ok cool! Thanks Steve for your reply.

**Comment by Asvsmadhav** [comment]
Done connected
