### ISSUE TITLE
Bitbucket: Authentication failed - since March 1st 2022

### ISSUE THREAD

**Issue by marcreig** [desktop/desktop#14035]
Good afternoon,

Yesterday I received a Bitbucket mail explaining:

> Beginning March 1, 2022, you will no longer be able to use your Atlassian account password when using Basic authentication with the Bitbucket Cloud REST API or Git over HTTPS.

I've a Bitbucket account with some personal projects.
Those personal projects sync with no problems through GitHub Desktop to Bitbucket, with my main user/pwd as always did.

But I've some "shared" projects, where I as a contributor (admin privilege), when I try to sync, they don't. Authentication failed error appears, asking for some new credentials.

I've created App Passwords with EVERYTHING checked on my account. The token is useful for syncing my projects, but fails the same with shared ones.

As those shared sync failing projects were local enterprise developed by 2 users, and those 2 do not work here anymore, I've updated they Atlassian account passwords of them and created App Passwords with FULL privileges to test if with they credentials or with they app tokens would login pass. But fails. There is no way to sync anymore thos shared projects (no pull, no push, no refresh... nothing).

I've deleted ALL windows keychain saved credentials, to recreate them. No way. My projects asks first time for user/pwd and everything starts to run smoothly, and shared ones, keep failing and asking credentials.

And that's rare too! Because my ones, keep working with my Atlassian user/pwd pair which suposedly souldn't since today!

Any ideas?
Anyone?

Thanks.

**Comment by steveward** [comment]
@marcreig thanks for the issue. I'd recommend reaching out to Atlassian support as they should be able to assist you better with authentication issues occurring on their service. Thanks for using GitHub Desktop!

**Comment by marcreig** [comment]
@steveward, I'm on it. But cannot understand why I can sync my projects but not the shared ones.
![image](https://user-images.githubusercontent.com/3540728/156203811-681c9cc7-5751-4222-b027-f1dbd498f7ba.png)
That's what it says...
And that's what the log says about:
![image](https://user-images.githubusercontent.com/3540728/156204529-8c00b6fc-f380-42b4-855e-aae87f921c9d.png)

I've tried to make a CLONE of one of the repositories with my same creds that work on my projects, on a diferent folder to test if they work on bitbucket, and they do! It clones with no problems.
But when used on GitHub Desktop, they don't work on those projects.
