### ISSUE TITLE
User cannot push changes to renamed default branch

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1404]
I tested the master branch default fix (https://github.com/desktop/desktop/pull/1336) and it doesn't seem to be fixed.

Reproduce:
- Clone repo from dotcom to Desktop. Repo should have two branches, with the second one set to master.
- Open branch list and Master is still default.

If you rename the default branch (per dotcom) on Desktop, then try pushing a change, you will be blocked. No errors surface as expected as you are not supposed to be able to rename the default branch on Desktop. This bug will be fixed once Desktop default branch is in-sync with dotcom. Renaming the default also creates another branch on dotcom, instead of updating the original.

Related: https://github.com/desktop/desktop/issues/1028

v0.0.39, OSX 10.11.5

**Comment by joshaber** [comment]
I haven't been able to reproduce this. There _is_ some lag between when I change the default branch on GitHub.com and when it's reflected in the Desktop app, but that's to be expected as we only refresh API info periodically.

@tierninho Feel free to open a new issue if you can reproduce this still.
