### ISSUE TITLE
Constant crashes on macOS

### ISSUE THREAD

**Issue by probablykasper** [desktop/desktop#14046]
### Describe the bug
Every few hours, the app crashes. I think this issue started happening around 1 month ago.

### Version & OS

Version 2.9.10 (x64)
macOS 10.15.7

### Logs

https://pastebin.com/SZGsg47g
(too long to include)

**Comment by steveward** [comment]
Thanks for the issue @probablykasper. Is the app just idle in the background when crashing, or are there specific actions you are performing when the crash occurs? Any extra details you can share would be helpful.

**Comment by probablykasper** [comment]
It's just running idle in the background, no pattern I've noticed

**Comment by ghost** [comment]
I'll go in and see if there's anything wrong and I'll tell you to follow me.

**Comment by ghost** [comment]
https://g.co/doodle/kmy6dyp It's an update in a new way that is not the same in the world of maps and the climate where you live will not be the same. If you are in Thailand and you are in Bangkok, it will be a symbol in your style according to the address.

**Comment by psychemedia** [comment]
I'm seeing a crash a few seconds after I clone a repo from Github to the desktop.

**Comment by darkduckgo** [comment]
If u are using 10.15.7, seems meet the same issue #13974 , check it maybe?

**Comment by sergiou87** [comment]
Yes, looking at the crash it seems to be the same as https://github.com/desktop/desktop/issues/13974, so I'm going to close this. @probablykasper @psychemedia please try out the latest version 2.9.11 which should fix this, thanks!

**Comment by probablykasper** [comment]
@sergiou87 Still an issue in 2.9.11 unfortunately

**Comment by darkduckgo** [comment]
> @sergiou87 Still an issue in 2.9.11 unfortunately

are u the same error info in v2.9.11 like #14075? maybe could attach the crash & error log there

**Comment by alecxvs** [comment]
I'm not sure if this is the same issue, or if it is, it's manifesting differently (more severely).

#13974 describes the issue as such:
> The alert shows up every single time GitHub Desktop is opened. **However, there is no impact on using the program, which so far works normally**

The app is running normally with no message in my case (this issue I presume) except after a couple minutes it suddenly crashes, whether I'm actively using it or not. The difference is there's a delay after opening before a crash message, and it actually crashes.

#14075 claims the same issue "however after using the latest version, **the same dialog alerts**" still not describing an actual crash but the nuisance is simply the crash dialog. In my case the app is definitely crashing though

Maybe it is the same and it's just manifesting differently on our systems, but as it's described in this issue, the app is rendered almost unusable except for simple quick tasks between crashes.

**Comment by probablykasper** [comment]
> are u the same error info in v2.9.11 like #14075? maybe could attach the crash & error log there

Yes, I think #14075 is a duplicate of this issue. Log here: https://pastebin.com/4Y2rW1Fa

**Comment by darkduckgo** [comment]
> > are u the same error info in v2.9.11 like #14075? maybe could attach the crash & error log there
> 
> Yes, I think #14075 is a duplicate of this issue. Log here: https://pastebin.com/4Y2rW1Fa

U can paste the error log in #14075 due to current issue has been closed and we could merge the same problem into one for dev to deal

**Comment by sergiou87** [comment]
Yep, that one seems to be the same crash, thanks! I just referenced to it in #14075 to keep track of it.
