### ISSUE TITLE
Add Android Studio To External Editor Options

### ISSUE THREAD

**Issue by detherminal** [desktop/desktop#14044]
### Describe the feature or problem you’d like to solve

I want to be able to open my git repository at Android Studio by clicking the button (or Ctrl+Shift+A) at the menu

### Proposed solution

It will be easy for Android Studio users

### Additional context

This button is located in the main menu. Open the repository in your external editor. 

Photo of the menu:
![github_desktop](https://user-images.githubusercontent.com/76167420/156238061-600a9bac-a834-4cbf-8143-46b6a6f88f46.png)

Photo of the options menu:
![github_desktop_2](https://user-images.githubusercontent.com/76167420/156238215-fdf6c7f0-4465-45c1-8411-95a88497fdde.png)

**Comment by steveward** [comment]
Thanks for the issue @detherminal. If you're interested you can check out https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md for instructions about how to add new editor integrations to GitHub Desktop.

**Comment by detherminal** [comment]
Ok. I checked the docs and it looks like it is easy to add an external editor option. I will close the issue when I open a pull request and it gets merged. Thanks!
