### ISSUE TITLE
Broken "Open with GitHub Desktop" File Autocomplete

### ISSUE THREAD

**Issue by nsudhakaran679** [desktop/desktop#14058]
### Describe the bug
When using the GitHub prompt to open a repository in GitHub Desktop, the location to clone the repository to defaults to the `Documents/GitHub` folder as oppose to creating a new subdirectory for this project.

### Version & OS
Github Desktop **Version 2.9.10** (arm64) running on a **2020 M1 MacBook Pro** with **MacOS Big Sur 11.4**.

### Steps to reproduce the behavior

1. Open any repository on [github.com](https://github.com/).
1. Click on the green button that says "Code", and in the dropdown select "Open with GitHub Desktop".
1. GitHub Desktop should open with a prompt to clone a repository. However, the current file path the clone the repository to results in an error—"This folder contains files. Git can only clone to empty folders".

### Expected behavior

The path to clone the folder to should be (by default) a subdirectory within `Documents/GitHub` with the same name as the repository to be cloned there (e.g. a repository named `hello-world` would live in `Documents/GitHub/hello-world`).

### Actual behavior

The path to clone the folder is (by default) the `Documents/GitHub` directory itself.

### Screenshots
**Expected:**
<img width="507" alt="The expected behavior" src="https://user-images.githubusercontent.com/89160678/156423477-724665ae-4bc2-4e5f-bfb6-8bdd3915826f.png">

**Actual:**
<img width="500" alt="The actual behavior" src="https://user-images.githubusercontent.com/89160678/156423310-3eeff427-aa28-40ea-b80f-81c5989480b2.png">

**Comment by steveward** [comment]
Thanks for the report @nsudhakaran679, this is fixed by https://github.com/desktop/desktop/pull/13980 and will be in an upcoming release.

**Comment by nsudhakaran679** [comment]
Apologies for not noticing that! Thank you very much! 😊
