### ISSUE TITLE
Can not create a repository

### ISSUE THREAD

**Issue by AmayasALLAM** [desktop/desktop#14059]
### Describe the bug
I suppressed a Repository on github, but it is still on github desktop. I can not suppress it on github desktop. When I try to do so, it tells me that it is done, but when I try to create a new repo with the file I have on my computer it seems like it recognizes as the old one. When I try to push it on github, it says it can not because it has been suppressed.

### Version & OS

Version 2.9.10 (x64) with Windows 10

### Steps to reproduce the behavior

1. Go to 'Github Desktop'
2. Click on 'Repository'
3. Click on 'Remove...'
4. Click again on 'Remove'
5. Click on 'add an existing repository from your hard drive'
6. Choose the repository path
7. See error

### Expected behavior

 I expected it to create a new repository with a new name

### Actual behavior

It came back to the repository that should have been canceled

### Screenshots

No relevant screenshot 

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

[2022-03-01.desktop.production.log](https://github.com/desktop/desktop/files/8172178/2022-03-01.desktop.production.log)
[2022-03-02.desktop.production.log](https://github.com/desktop/desktop/files/8172179/2022-03-02.desktop.production.log)
re

**Comment by steveward** [comment]
@AmayasLeBoss thanks for the issue. Just to confirm -- when you say suppressed are you referring to deleting the repository on GitHub? Deleting a repository on GitHub does not delete the local repository in GitHub Desktop. 

Are you wanting to create a fresh repository with no commit history, or just rename the existing repository? For reference you can[ rename repositories ](https://docs.github.com/en/repositories/creating-and-managing-repositories/renaming-a-repository)directly on GitHub, and GitHub Desktop will pick up the rename.

If you want to create a fresh repository you will need to go to the repository and delete the hidden `.git` directory. You can then add it to GitHub Desktop to initialize it as a new repository. You should then be able to commit your changes and publish the repository up to GitHub. 

Let me know if you have any questions.
