### ISSUE TITLE
Checkout commit from History tab

### ISSUE THREAD

**Issue by ahanna-WWN** [desktop/desktop#14053]
### Describe the feature or problem you’d like to solve

In the course of debugging I often need to run my application as an older version and I was doing so by copying a commit's SHA and entering in the command line `git checkout 213124125123...`
However, my application consists of 7 repositories, and reverting to previous versions multiple times per day takes a long time in addition to the possibility of mistakes.

### Proposed solution

Since Github Desktop works correctly in detached head mode. It would be relatively easy to put an option in the commit's context menu to `Checkout this commit`. Currently there is only an option to create a branch based on the commit but then I would have to name and later delete the branch manually every time.

### Additional context

![image](https://user-images.githubusercontent.com/100567814/156353557-0ea4ef81-1672-4283-9f47-695d41892041.png)

**Comment by steveward** [comment]
Thanks for the feedback @ahanna-WWN. I'm going to close this in favor of https://github.com/desktop/desktop/issues/10068 where are tracking this request.
