### ISSUE TITLE
i am having difficulty deleting repositories from the github desktop

### ISSUE THREAD

**Issue by ntami-ekor** [desktop/desktop#14066]
I need assistance with deleting repositories from the github desktop, i already delted from via the github web but i still find them on the github desktop and this is not letting me go forward with my projects

**Comment by sergiou87** [comment]
@ntami-ekor you can delete repositories from GitHub Desktop **locally** (i.e. the copy you have in your machine) by right clicking them in the repository list and then selecting `Remove`:
![image](https://user-images.githubusercontent.com/1083228/156608413-d010b861-6436-41a7-9144-c523f82c6bbc.png)

Aside from that, you must delete them (if you want) from the GitHub web as you said you did.

I hope that helps!
