### ISSUE TITLE
error: cannot spawn .git/hooks/pre-commit: No such file or directory

### ISSUE THREAD

**Issue by hokran** [desktop/desktop#14063]
### Describe the bug
when click on commit button, getting below error 

'error: cannot spawn .git/hooks/pre-commit: No such file or directory"

### Version & OS
Windows 10 Pro

GitHub Deskotp Version 2.9.10 (x64)

### Steps to reproduce the behavior

1.Open git hut desktop version
2. Changes any one file
3. Enter commit text
4. Click on Commit button

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for the issue @hokran. Are you wanting to use hooks in this repository?

GitHub Desktop will run pre-commit hooks on commit if your Git repository is configured to use them. Note however that the hooks will run inside of GitHub Desktop's environment which means they won't necessarily have access to the same environment variables as you'd normally have when using the command line.

**Comment by hokran** [comment]
Hi Steve, let me know what info you needed to resolve this issue.

**Comment by steveward** [comment]
@hokran are you wanting to use pre-commit hooks in this repository? If not, you can remove the `pre-commit` hook in `.git/hooks`. If you are wanting to use a pre-commit hook it'd be helpful if you could share the contents of `.git/hooks/pre-commit` so that we could see what the issue might be there.

**Comment by hokran** [comment]
Hi Steve, Its working fine after removing `pre-commit` hook in `.git/hooks`. Thanks a lot for your help

**Comment by steveward** [comment]
Glad to hear you were able to get things working!

**Comment by Krzeszny** [comment]
Hello. In my case, there's no pre-commit in .git/hooks. There's only post-merge and post-checkout.
