### ISSUE TITLE
GitHub Desktop does not recognize newly added files or folder

### ISSUE THREAD

**Issue by Rydelfox** [desktop/desktop#14073]
### Describe the bug
When I add a new file or folder in a local repository, GitHub Desktop will not list the newly added files or folder in Changes, nor will they appear in a commit.
If I attempt to move a file, it recognizes it being deleted from the old location, but not being added to the new one

### Version & OS

GitHub Desktop Version 2.9.11 (x64)
Windows 10 Pro 21H1

### Steps to reproduce the behavior

1. Have an existing repository, synced to your computer
2. Add a new file anywhere in that local repository
3. File is not listed under changes in GitHub Desktop

### Expected behavior

Newly added files appear under changes (marked with a green + in a box in older versions

### Actual behavior

Newly added files are ignored

### Logs

Nothing reflected in logs

### Additional context

Worked in 3.3.6.1 (which, despite the higher version number, is an older version)

**Comment by sergiou87** [comment]
That's so weird… could you open a terminal in that repository and run `git status`?

GitHub Desktop should reflect whatever `git status` shows for you.

**Comment by Rydelfox** [comment]
On branch FixMissingItemImages
Your branch is up to date with 'origin/FixMissingItemImages'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   ../src/main/java/com/rydelfox/morestoragedrawers/MoreCreative.java
        modified:   ../src/main/java/com/rydelfox/morestoragedrawers/block/ModBlocks.java
        modified:   ../src/main/java/com/rydelfox/morestoragedrawers/block/tile/TileEntityDrawersMore.java
        modified:   ../src/main/java/com/rydelfox/morestoragedrawers/client/model/MoreDrawerModel.java
        modified:   ../src/main/java/com/rydelfox/morestoragedrawers/client/renderer/TileEntityDrawersRenderer.java

no changes added to commit (use "git add" and/or "git commit -a")
________________________
It does not list ../src/main/java/com/rydelfox/morestoragedrawers/testFile.txt that I added for this test

**Comment by Rydelfox** [comment]
It appears Intellij IDEA can color files based on version control status, and it's listing these files as ignored.  If I use that to tell it to add the file, the file shows up in GitHub Desktop.

It also looks like I had told .gitignore to ignore a specific folder, but it was also ignoring another subfolder with the same name
