### ISSUE TITLE
App icon doesn't appear in app switcher on Windows

### ISSUE THREAD

**Issue by donokuda** [desktop/desktop#1407]
### Description

The new icon doesn't appear in the <kbd>alt</kbd>+<kbd>tab</kbd> application selector on Windows.

### Version

**GitHub Desktop version:** 0.0.39
**OS version:** Microsoft Windows [Version 10.0.14393]

### Steps to Reproduce

1. Open GitHub Desktop
1. Hit <kbd>alt</kbd>+<kbd>tab</kbd>

**Expected behaviour:** The app icon is the purple icon 

**Actual behaviour:**
![image](https://cloud.githubusercontent.com/assets/1174461/25824760/565f830a-33f5-11e7-8487-5c40bf7d5d1c.png)

**Reproduces how often:** 100%

**Comment by mboughaba** [comment]
Hi
It looks like this is still reproducible in v 1.0.6 on Windows 7 64bits.

**Comment by j-f1** [comment]
@mboughaba Can you open a new issue and fill out the template for us so we can better help you?
