### ISSUE TITLE
Commit area invisible

### ISSUE THREAD

**Issue by isoengas** [desktop/desktop#14074]
### Describe the bug
The commit component (textboxes + botton) become hidden after minimizing the GitHub desktop window.

### Version & OS

Version 2.9.11 (x64)
Windows 11

### Steps to reproduce the behavior

1. Open program
2. Maximize window
3. Click on Minimize window
4. Click on the windows taskbar to restore window
5. The commit area is no longer visible. The maximized window also covers the windows taskbar.
6. I need to restore window (un-maximize) to be able to see the commit area again

### Expected behavior

Commit area visible at all times

### Actual behavior

Unable to commit from github desktop unless I do the step 6 to fix the problem

### Screenshots
![image](https://user-images.githubusercontent.com/20572545/156731621-50d07906-97a3-4dbc-8f1a-365f18e1d22c.png)

### Logs

Not applicable

### Additional context

This behavior only happens in one of my monitors (the external one). I can not reproduce on the laptop monitor.

**Comment by sergiou87** [comment]
Hi @isoengas ! 👋  Thanks for your report.

We think this is a regression in the latest Electron version and affects people using non-standard UI scales. In your case my guess is one of your monitors has the UI scaled and not 100%, is that possible?

**Comment by isoengas** [comment]
Yes, that is correct. The problem is only affecting my monitor with 100% scale, the other monitor is set at 250% @sergiou87

**Comment by sergiou87** [comment]
Cool, thank you! Then I'm gonna close this in favor of https://github.com/desktop/desktop/issues/13940

Please, subscribe to that issue if you want to get notified when we make progress. Sorry I can't be of more help at the moment 😓
