### ISSUE TITLE
Pre-fill previous commit summary when pressing arrow up key

### ISSUE THREAD

**Issue by PDerid** [desktop/desktop#14076]
Hi!
I have an idea for the GitHub desktop app that could be handy for some people.

### Describe the feature or problem you’d like to solve

At our company we always place a JIRA ticket number in front of out commit message so that it's clear on what task we worked. On the command line it's easy to press the arrow up key to pre-fill the previous commit so I don't need to always type the JIRA ticket number manually.

### Proposed solution

When you are focused in the commit summary input field and you press the arrow up (and down) button, you can cycle through the previous commit messages so that the issue number is pre-filled and I only need to change the actual message.

For example; when my last pushed commit message was `PROJECT-3454: Added new background color` and I want to make a new commit at a later time, I can focus in the commit summary field, press the arrow up key and the previous commit message (`PROJECT-3454: Added new background color`) will be pre-filled so that I don't have to manually type `PROJECT-3454:` again.

If this feature is not relevant, feel free to close it.

Thanks!

**Comment by steveward** [comment]
Thanks for the issue @PeeJeeDR. Would something like [support for commit templates](https://github.com/desktop/desktop/issues/8698) help with this issue? There are also solutions using hooks, like https://www.npmjs.com/package/jira-prepare-commit-msg that could be used.

This is likely a fairly niche feature so it's not something we'd specifically support, but commit templates are something we may consider providing better support for in the future. Thanks for using GitHub Desktop!

**Comment by marco2216** [comment]
I think this would be very useful, I could use this frequently when I commit something and have to revert it, and then want to commit it again.
