### ISSUE TITLE
Add the option of `Open in GitBash` similar to that of other `Open in …` options already available (VS Code and Windows Terminal) 

### ISSUE THREAD

**Issue by egvijayanand** [desktop/desktop#14071]
### Describe the feature or problem you’d like to solve

Add the option to `Open in GitBash` similar to that of other `Open in ...` options already available (VS Code and Windows Terminal).

### Proposed solution

GitBash offers additional features such as the `Current Branch` we're in to be well aware of the context and auto-completion of Git commands to name a few.

### Additional context

![image](https://user-images.githubusercontent.com/81947404/156643203-16286142-4d59-47b6-b69d-11f430f3f55b.png)

**Comment by egvijayanand** [comment]
Have seen that Integrations are being handled via Option settings.

All it needs is to add another dropdown upon choosing the `Windows Terminal` as Shell option then load the configured profiles as another dropdown to select the launch profile so that the user can opt-in to open in any of the profiles desired and not restricted to `Git Bash` alone.

https://docs.microsoft.com/en-us/windows/terminal/command-line-arguments?tabs=windows#new-tab-command

![image](https://user-images.githubusercontent.com/81947404/156653056-bcb62b41-6927-4fe2-a2a9-8fcab8155b17.png)

**Comment by tsvetilian-ty** [comment]
Hello @egvijayanand, Git Bash should already be an opinion when picking shell in the Integrations tab.
![image](https://user-images.githubusercontent.com/9341546/156664879-c33b025f-64a5-4c63-934e-5b5a14f0e49d.png)
![image](https://user-images.githubusercontent.com/9341546/156666163-4d6e245f-f040-41ac-83d3-d873b2414b24.png)

Your idea to pick a specific profile for the terminal sounds good :)

**Comment by egvijayanand** [comment]
> Git Bash should already be an opinion when picking shell in the Integrations tab.

Yes, I saw it off late. Thanks.

> Your idea to pick a specific profile for the terminal sounds good :)

`Windows Terminal` has the extensibility advantage for other prominent CLI editors (recently they even added the VS Developer Command Prompt) that way, it becomes a unified option with a profile launch option. Users can work with the editor of their choice.

**Comment by niik** [comment]
Hey @egvijayanand, thanks for reaching out. And thanks @tsvetilian-ty for helping out! 😄 

Since the original issue here was addressed I'm going to close this out. Supporting shell-specific configuration options is not something we've heard any requests for previously but feel free to open an issue specifically about that where you outline that specific request and how you think it should work (and if there's any workarounds today).
