### ISSUE TITLE
Path not set when Open with GithubDesktop

### ISSUE THREAD

**Issue by jgwill** [desktop/desktop#14087]
### Describe the bug

Github Desktop opens when I click " Open with GithubDesktop" and usually, the Path to checkout is set right (like c:\src\myrepobeingcheckout
Now, the path is just c:\src\   and I am expecting as before that the name of the repo is appended to latest path I use.

### Version & OS
2.9.10

### Steps to reproduce the behavior

1. Go to a GitHub Repo
2. Click on ' Open with GithubDesktop'
3. Observe the Path

### Expected behavior

Repo Name being appended to path

### Actual behavior

Repo Namo not appended to path

#### BUGGED

![image](https://user-images.githubusercontent.com/23141173/156807283-5497f129-5d06-43c1-934f-0339a367a950.png)

#### EXPECTED Example

![image](https://user-images.githubusercontent.com/23141173/156807517-ee739889-1e29-46cd-a2bc-25c034000f35.png)

regards

**Comment by steveward** [comment]
Thanks for the report @jgwill, this will be fixed by https://github.com/desktop/desktop/pull/13980 in an upcoming release.
