### ISSUE TITLE
"Command failed" dialog in Github Desktop mac

### ISSUE THREAD

**Issue by snicolet** [desktop/desktop#14098]
### Describe the bug

A dialog error appears in Github Desktop with a message about a "failed command" related to formatting

### Version & OS

Github Desktop version 2.9.11 (x64) running on Mac OS 10.13.6

### Steps to reproduce the behavior

1. Launch Github Desktop
2. Wait a couple of minutes, using other apps (for instance surfing the Internet)
3. Switch back to GitHub Destop
4. See the error dialog (as in screenshot below)

### Expected behavior

No error dialog

### Actual behavior

Error dialog 

### Screenshots

<img width="1981" alt="screen" src="https://user-images.githubusercontent.com/6761856/156897787-3d3277aa-e26b-47d9-8e0c-19ddced32337.png">

### Logs

This is the production log:
[2022-03-05.desktop.production.log](https://github.com/desktop/desktop/files/8191342/2022-03-05.desktop.production.log)

### Additional context

None

**Comment by sergiou87** [comment]
Hi @snicolet! 👋 

Could you try GitHub Desktop with the very same repo and steps on a newer macOS version? Unfortunately we're unable to provide support for High Sierra nor Mojave 😥
