### ISSUE TITLE
Button commit gone

### ISSUE THREAD

**Issue by Yamiriko** [desktop/desktop#14100]
### Describe the bug
Button Commit Gone

### Version & OS
Version 2.9.11 (x64) & Windows 10

### Screenshots
![gambar](https://user-images.githubusercontent.com/52909993/156914077-23e4b5cc-8b71-4276-8c62-16e6ace760c7.png)
https://prnt.sc/Kbz2KX4ayx1x

**Comment by Yamiriko** [comment]
My Display Resolution : 1366 X 768

**Comment by niik** [comment]
Hi @Yamiriko, thanks for reporting this. This appears to be the same issue as https://github.com/desktop/desktop/issues/13940. Can you verify that you're running your interface scaled like [this user](https://github.com/desktop/desktop/issues/13940#issuecomment-1044226771)?
