### ISSUE TITLE
Unable to discard changes to Recycle Bin when a repository's path uses a Virtual Drive Letter.

### ISSUE THREAD

**Issue by callumtw** [desktop/desktop#14108]
### Describe the bug
Attempting to discard changes in a repository which uses a Virtual Drive Letter in its path displays an Error dialogue saying "Failed to discard changes to Recycle Bin", when this worked in previous versions of GitHub Desktop. 

My recycle bin is not set to delete files immediately. Our repository uses a Virtual Drive path mapped with the `subst` command in startup, to point the W:/ letter to a specific location on a local physical disk drive, R:/. 

I assume GitHub Desktop is now treating Virtual Drives as if they were Networked Drives, where the Recycle Bin would not be available, however this is not the case, and it used to work correctly in previous versions.

### Version & OS
v2.9.11 (x64). Windows 10 Pro 19044.1526.

### Steps to reproduce the behavior

1. Create a directory on a local, physical disk drive to house a new repository for the purposes of reproducing this issue (e.g. C:/test).
2. Create a new repository in this directory (in this example, I have named it 'Repository').
3. Create a text file in this repository. 
4. In the changes list in GitHub Desktop, right click the newly created file entry and discard the change. Note that no Error dialogue was displayed. Note that the discarded text file appears in your Recycle Bin.
5. Remove the repository from GH Desktop and Empty your Recycle Bin (or simply delete the text file permanently).
6. In a command prompt, create a virtual drive letter pointing to the test directory location, e.g.: `subst p: c:\test` (this will map the drive letter P:/ to C:/test/).
7. Add the repository back to GH Desktop **using the virtual path**. I.e. File/Add Local Repository, then selecting P:/Repository as the local path.
8. Create a new text file in the repository.
9. In the changes list, right click and attempt to discard this newly created file once again. Note that this time, the "Failed to discard changes to Recycle Bin" Error Dialogue is displayed, and permanently discarding the changes will (obviously) not send the file to the Recycle Bin.

### Expected behavior
We would expect the behaviour of discarding changes to be identical for any repository that ultimately exists on a local physical disk, regardless of whether the repository's path uses a virtual drive letter or the physical disk drive's letter. This includes discarded changes being sent to the Recycle Bin. (As was the case in previous versions of GH Desktop).

### Actual behavior
Using a virtual drive letter in the path to a local repository treats that repository as if it were a Networked Drive, thus not allowing discarding changes to the Recycle Bin.

### Additional context
Related but different to #13948 and #14033.

**Comment by tidy-dev** [comment]
@callumtw Thanks for reaching out. I am curious if you are sure that prior to v2.9.7 that it actually did move it to the Recycle Bin (not just say it did). Because prior to that when the library we used failed to move a file to the Recycle Bin, it just did so silently and did the permanent delete unknowing to the user (I have confirmed that with the recycle bin setting scenario).

**Comment by callumtw** [comment]
> @callumtw Thanks for reaching out. I am curious if you are sure that prior to v2.9.7 that it actually did move it to the Recycle Bin (not just say it did). Because prior to that when the library we used failed to move a file to the Recycle Bin, it just did so silently and did the permanent delete unknowing to the user (I have confirmed that with the recycle bin setting scenario).

In all honesty, I can't be _certain_ that it would have moved them to the Recycle Bin, only that it never displayed an Error dialogue. I remember recovering a couple of commits from the Recycle Bin over the last year, but we moved our machines over to using virtual paths halfway through the last year, so I can't be 100% sure whether it was before or after that.

If there is anywhere I can grab an older binary for GitHub Desktop that _may_ have worked, I'd be happy to test and confirm.

In any case, do you think this would be something that could be resolved? If there is a way to query whether the drive is mapped to a physical local drive, it would be very useful to treat it as one, rather than treating it similarly to a Network Drive. If not, I suppose the only workaround will be to add the repositories using their absolute physical paths.

**Comment by tidy-dev** [comment]
Here is a download link to [v2.9.6](https://centralreleases.blob.core.windows.net/github-desktop/releases/2.9.6-9196a1ae/GitHubDesktopSetup-x64.exe) if you would like to try.

However, to your question, I am not sure there is currently a good way to resolve it. I believe Windows itself does not provide a recycling bin for virtual drives and is what the service Electron relies on to accomplish this.

> `If there is a way to query whether the drive is mapped to a physical local drive`, 

Maybe worth a look see, but as this is likely only affecting a small percentage of users, I am not sure when this will be prioritized.

>If not, I suppose the only workaround will be to add the repositories using their absolute physical paths.

Yes. Also upon prompt to permanently discard, a user could manually decide to copy the files to a temp directory outside their repository if they are unsure they want to delete them permanently.. as that is basically what the recycle bin is doing.

**Comment by callumtw** [comment]
I just tried with v2.9.6 - discarding changes to newly created files appears to outright fail (the file is not deleted, no error is displayed, and it remains in the list) - which I have encountered before and just thought was a bug (unaware it might have been related to virtual drives) - and discarding modifications to an existing file does so without throwing an error prompt, but does not send the file to the Recycling Bin.

As an aside, unfortunately installing the older version appears to have wiped my list of known repositories. That's my fault for not taking precautions, but a bit of a stinger all the same!

> I believe Windows itself does not provide a recycling bin for virtual drives and is what the service Electron relies on to accomplish this.

I just tried deleting a file in Explorer, at a virtual drive path, and Windows indeed displayed a prompt indicating the file would be permanently deleted, rather than sent to the Recycling Bin. I was totally unaware of this, and I'm quite shocked (in the "of course, it's Windows" kind of way) and disappointed that the OS doesn't support it.

Sorry to have wasted both of our time in many ways! Whilst I would love the Recycle Bin to be supported in this setup, as it doesn't seem like this behaviour is native even to Windows, I really don't expect it to be prioritised/supported, especially as I'm sure it would be a small percentage of users. We will probably just move the repos to use absolute paths, since that provides better peace of mind with less friction than copying the files to a temp directory.

Thanks for your assistance @tidy-dev !

**Comment by tidy-dev** [comment]
I am sorry about the wiping out of your repositories! I forgot about the db change that causes this from 2.9.6 to 2.9.7 and should for-warned you. In case you are unaware, you can drag/drop repository folders onto the desktop app to add them back. I keep all my repos in one parent directory so I can just select them all and then drag/drop them onto desktop to add them all at once. 

Thank you for trying it out tho! 

> (in the "of course, it's Windows" kind of way) 
😸
