### ISSUE TITLE
Unable to login with github.com account

### ISSUE THREAD

**Issue by damies13** [desktop/desktop#14107]
### Describe the bug
Unable to login with github.com account

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

Window 10 Enterprise (20H2)
![image](https://user-images.githubusercontent.com/15232871/156966945-4c72ddfe-2309-4675-a532-f9a00aa5ba7d.png)

### Steps to reproduce the behavior

1. Go to 'File>Options'
2. Click on 'Accounts'
2. Click on 'Sign In' button in GitHub.com section (not GitHub Enterprise)
2. Click on 'Continue with browser'
3. On return from browser get 'Failed to fetch' error
4. See error in screenshots below

### Expected behavior

User logged in with github.com account

### Actual behavior

'Failed to fetch' error (See error in screenshots below)

### Screenshots

![image](https://user-images.githubusercontent.com/15232871/156967713-702b47b2-5354-4861-a795-908df53bca01.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

*was not able to attach logs*

**Comment by niik** [comment]
Thanks for the report! Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by niik** [comment]
> was not able to attach logs

Sorry, I saw this after posting my previous comment. We are going to need to look at the logs to see if there's anything in there that could help us troubleshoot this. What issue were you facing that prevented you from attaching logs?

Is this your own personal machine or is it a company/university setup?

**Comment by Kalakaarboyz1** [comment]
ghi

**Comment by damies13** [comment]
Actually it was my work computer. I don't have admin rights on the machine, so I guess it could be a permissions issue, does this component attempt to write outside the user profile , i.e. HKEY_SYSTEM instead of HKEY_CURENTUSER or a path that doesn't use %USERPROFILE% ?

I first tried to attach the file by uploading it in as an attachment, but got an error, then I copied the content and tried putting it in as code block, but then the post was too big.

I also realised there are a few issues that are similar symptom like #11410 and #13754

Unfortunately I'm not able to try the workaround in https://github.com/desktop/desktop/issues/11410#issuecomment-811442461 as I don't currently have access to edit the registry (Standard for no privileged users)

Hopefully this helps.

**Comment by niik** [comment]
Hi @damies13, this error is one we typically see when the application isn't allowed to connect to github.com for one reason or another. Can you verify that you can connect to github.com in your browser on your machine?

Do you connect via a proxy? If so you'll need to configure your system level proxy for GitHub Desktop to pick up on that

**Comment by damies13** [comment]
Ok Thanks, I'll check tomorrow when I'm at work. 

I was able to connect to github.com from the browser, and sign in and click the authorise github desktop button on the web page. the system proxy settings are configured by the admins using a wpad file, does github desktop not pick up the system proxy settings or is it not able to use a wpad file?

**Comment by damies13** [comment]
Where do I access the proxy settings in GitHub Desktop?

**Comment by damies13** [comment]
Never mind I found it https://github.community/t/common-questions-about-github-desktop/10198

**Comment by damies13** [comment]
Ok today's log was a bit smaller it let me upload:
[2022-03-09.desktop.production.log](https://github.com/desktop/desktop/files/8210328/2022-03-09.desktop.production.log)

Hope this helps.

**Comment by niik** [comment]
> Ok today's log was a bit smaller it let me upload: [2022-03-09.desktop.production.log](https://github.com/desktop/desktop/files/8210328/2022-03-09.desktop.production.log). Hope this helps.

Thanks for that! Unfortunately it didn't contain much that could help us troubleshoot this.

> the system proxy settings are configured by the admins using a wpad file, does github desktop not pick up the system proxy settings or is it not able to use a wpad file?

GitHub Desktop should pick up on system proxy settings as long as they're picked up by your operating system. WPAD is specifically listed as supported as far as I can tell. Are your company using an authenticating proxy?

Could you open Developer Tools (under the View menu), and check the Network tab while you attempt to sign in. See if any failing request shows up there an if you can see anything that could help us debug.

**Comment by damies13** [comment]
> Could you open Developer Tools (under the View menu), and check the Network tab while you attempt to sign in. See if any failing request shows up there an if you can see anything that could help us debug.

Will have a try when I'm back at work.

**Comment by damies13** [comment]
I seems I can't connect at all to https://api.github.com

![image](https://user-images.githubusercontent.com/15232871/158110979-b998140c-0f12-4eb1-b649-8391a5a0ed3b.png)

When I tried the same uri in a browser (I tried Chrome and Edge) I get the same error. I don't know if this host no longer exists or it's being actively blocked?

**Comment by niik** [comment]
> When I tried the same uri in a browser (I tried Chrome and Edge) I get the same error. I don't know if this host no longer exists or it's being actively blocked?

Hi @damies13, thanks for reporting back! That host definitely exists, it's a key part of GitHub. I'm wondering if it's possible that your company is blocking it though? Is there some IT-department or IT-support service that you could contact and see if this is something they'd need to explicitly enable?

**Comment by damies13** [comment]
Thanks,

Seems it is being blocked by my companies proxy server, as this is not an issue with this application, I'll close the issue. 

Thanks all for the help.
