### ISSUE TITLE
guides at (https://docs.github.com/desktop/guides) do not exist

### ISSUE THREAD

**Issue by sputnikutah** [desktop/desktop#14106]
### Describe the bug
Write a clear and concise description of what the bug is.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by niik** [comment]
Thanks @sputnikutah, this was reported in https://github.com/desktop/desktop/issues/13882 and addressed in https://github.com/desktop/desktop/pull/13920. Please make sure you're running the latest version of GitHub Desktop (at time of writing 2.9.11)
