### ISSUE TITLE
Offline Network Graph

### ISSUE THREAD

**Issue by 201flaviosilva** [desktop/desktop#14114]
### Describe the feature or problem you’d like to solve

I'll start by apologizing if this has already been suggested :)

But what I think is really cool to have a tree view of branches like we have on GitHub is the [network](https://github.com/desktop/desktop/network)

It would be very helpful if this feature were implemented to have a better understanding of the ramifications locally :)

(Sorry for my English, and again I apologize if it has already been suggested, I looked in the questions but didn't find anything :))

(By the way, I think it would be cool to add the discussions tab to this repository :))

#### Example image:
<img width="939" alt="Captura de ecrã 2022-03-07, às 19 19 18" src="https://user-images.githubusercontent.com/55815265/157103627-9919879c-5c90-4493-bef8-21fcd79425f9.png">

**Comment by 201flaviosilva** [comment]
Sorry if this has already been suggested 😅

**Comment by steveward** [comment]
Thanks for the issue @201flaviosilva! We are tracking this in https://github.com/desktop/desktop/issues/9452, so you can subscribe there for updates about this feature.

**Comment by 201flaviosilva** [comment]
Thank you very much:)
