### ISSUE TITLE
Unable to get the Desk top aplication to work on my Vertual Machine

### ISSUE THREAD

**Issue by NAVR-CMCK** [desktop/desktop#14118]
### Describe the bug
Unalbe to log into the application even thought the browser

### Version & OS

2.9.0 64 bit

### Steps to reproduce the behavior

1. Click Push
2. Choose to login via browser and follow instructions
4. 
![image](https://user-images.githubusercontent.com/71879732/157206387-9be61d6e-84be-4b8b-b7b1-12a22874295d.png)

### Expected behavior

to be able to login and push my changes

### Actual behavior

Not able to log in

### Logs

[2022-03-08.desktop.production.log](https://github.com/desktop/desktop/files/8204536/2022-03-08.desktop.production.log)

**Comment by niik** [comment]
Hi @NAVR-CMCK, this error is one we typically see when the application isn't allowed to connect to github.com for one reason or another. Can you verify that you can connect to github.com in your browser on your virtual machine?

Do you connect via a proxy? If so you'll need to configure your system level proxy for GitHub Desktop to pick up on that
