### ISSUE TITLE
Merge conflict on empty __init__.py files have no way to resolve in the desktop

### ISSUE THREAD

**Issue by bhealy-indeed** [desktop/desktop#14113]
### Describe the bug
Moved changes when creating a new branch. Old branch had an empty __init__.py that gained some includes on the new changes. Flagged as having a merge conflict, but has no resolvable text (i.e. '>>>>>', '<<<<<<', etc), so I cannot resolve the conflict in GitHub Desktop

### Version & OS
GitHub Desktop 2.9.11
MacOS 12.2.1

### Steps to reproduce the behavior

1. Ensure your repo is out of date with your main branch and that your Django settings file is empty (`settings/__init__.py`)
2. Modify the Django `settings/__init__.py` to add some includes
3. Use GitHub Desktop to create a new branch
4. The __init__.py file should be flagged as having a merge issue, but have no branch indicator text

### Expected behavior

File should have no merge issues

### Actual behavior

File was flagged as having merge issues

### Screenshots

![image](https://user-images.githubusercontent.com/62403057/157081252-2fad8bb4-4199-4b48-86df-da3e8b2916bf.png)

### Logs

[2022-03-07.desktop.production.log](https://github.com/desktop/desktop/files/8199487/2022-03-07.desktop.production.log)

### Additional context
None

**Comment by steveward** [comment]
Thanks for the report @bhealy-indeed. What does a standard `git status` return from the command line when you run it?

**Comment by bhealy-indeed** [comment]
@steveward, I can't seem to reproduce the issue now (though I did it 3 times originally to make sure I _could_ do it at the time). IIRC, it showed the file as having a merge conflict, though without an actual confirmation or reproduction, my memory on this is moot.

Since I can't seem to get the issue to reproduce, this should probably be closed (unless someone else can reproduce it).

**Comment by steveward** [comment]
Thanks for the update, and apologies for the delay in getting back to you on this. I've tested a few things with merge conflicts recently and didn't run into any issues, so I'm going to close this out. Let me know if you run into this again.
