### ISSUE TITLE
Re-open issue #13975

### ISSUE THREAD

**Issue by SadPencil** [desktop/desktop#14117]
Issue #13975 has been closed in favor of #10026 by @steveward. These two issues are not relevant at all and #13975 should be opened again.

The issue is not for git cloneing stuff, it is for the GitHub Desktop GUI itself, i.e. network traffic interacting with github.com instead of git repos. This remainder has been mentioned in this issue twice. Also, it has nothing to do with authenticating proxies.

**Comment by niik** [comment]
Taking this back to #13975. In the future please don't open another issue to request reopening of another. That just adds noise and unnecessary work for us

**Comment by SadPencil** [comment]
> Taking this back to https://github.com/desktop/desktop/issues/13975. In the future please don't open another issue to request reopening of another. That just adds noise and unnecessary work for us

@niik, I know but I have already left comments on both issues 3 days ago and get no responses. I have no other choices.
