### ISSUE TITLE
Periodically fetch and refresh status of all repositories set to ON is having no effect - repos not auto-refreshing

### ISSUE THREAD

**Issue by ibrowne** [desktop/desktop#14121]
### Describe the bug
I have the app set to refresh repos in the background, but it does not seem to be doing that automatically.
![image](https://user-images.githubusercontent.com/1280115/157272481-f80ab7a6-9823-438d-a456-215c99283eef.png)

### Version & OS

GitHub Desktop - v2.9.11 (x64)
Mac OS 11.6.3

### Steps to reproduce the behavior

1. Go to "preferences"
2. Click on "advanced"
3. Make sure "Periodically fetch and refresh status of all repositories" is checked.
4. Click Save
5. Note that none of the repos are fetched automatically in the background even after waiting a few hours.

### Expected behavior

I'd expect the repos to refresh in the background every so often

### Actual behavior

the repos are never refreshed in the background, even after waiting a few hours.

### Screenshots

See above

### Logs

n/a

### Additional context

This used to be working for me, but has stopped working for the last few months or so.  I have 15 repos checked out ... would that play a role in this not working?  Is there a max number of repos for which the auto-refresh will work, for performance reasons?

**Comment by niik** [comment]
Hey @ibrowne, thanks for reaching out. The logic around when a repository will be fetched or not is complex so it's not straightforward to identify what would cause your problem without more information. Could you please open Developer Tools (under the View menu), checking the Console tab, and making sure you've got 'Verbose' selected

<img width="647" alt="image" src="https://user-images.githubusercontent.com/634063/157825771-f52f20e7-3736-4bfa-b49e-716e845c4fea.png">

Look for log lines containing RepositoryIndicatorUpdater or "background fetch" and see if that reveals anything.

One thing I will note however is that we won't fetch repositories in the background unless the application is focused. We chose this approach to not consume resources on our users' machines when they weren't necessarily going to interact with the application.

**Comment by ibrowne** [comment]
> we won't fetch repositories in the background unless the application is focused.

So that answers my question.  I know there was a time when repos would be refreshed even if they were not in focus.  i liked that since I could at my list of repos and see which ones had changes to pull since they'd be marked with the 
![image](https://user-images.githubusercontent.com/1280115/157966602-a1d47405-662d-4533-a8f3-19edf58cf1b6.png) down arrow.  Am I imagining things or was that a thing™ a while back?

**Comment by steveward** [comment]
@ibrowne just to make sure things are clear the repo doesn't have to be in focus, just the app itself. We also still show the indicators. 

There is also a "Fetch all" feature tracking issue in https://github.com/desktop/desktop/issues/13700 if you'd like to follow along. I'm going to close this out.

**Comment by wonton1234** [comment]
I cannot even find the option
