### ISSUE TITLE
Show actions status on branch selector 

### ISSUE THREAD

**Issue by Madpeterz** [desktop/desktop#14135]
### Describe the feature or problem you’d like to solve
Currently you are forced to goto the git hub website or use a 3rd party system to view the status of github actions, or other status events (like image builds) I would like the status system that is used for pull request checks to use the status icons of the git so you can see at a glance if all is well.

### Proposed solution

Please share how this will it benefit Desktop and its users?
they dont have to commit and then go open github to view the build status / git hub action status 
they can just see a yellow dot to show its under way or a red X or a green tick.

### Additional context

https://github.blog/changelog/2021-12-14-github-desktop-now-shows-pull-request-check-run-statuses

![image](https://user-images.githubusercontent.com/57852827/157554888-6411f17b-7bf7-41e6-b2b4-8810a4f44c70.png)

**Comment by niik** [comment]
Hey @Madpeterz, thanks for reaching out. I believe this is the same request as https://github.com/desktop/desktop/issues/10115 so I'm going to close this issue in favor of that. If I'm mistaken please let me know and we can reopen, if not please subscribe to that issue for any updates!

**Comment by Madpeterz** [comment]
no probs I did not see that request 👍
