### ISSUE TITLE
Long commit numbers truncate branch names in display

### ISSUE THREAD

**Issue by leewynbpm** [desktop/desktop#14146]
### Describe the bug
In the 'Current branch' display, I'm using a repo that has commit numbers of 4 digits (e.g. in the image attached, it's commit number #1100). The branch name I have is 16 characters long and is being truncated in the display. 

### Version & OS

Version 2.9.11 (x64) - Windows

### Steps to reproduce the behavior

1. Use a repo with over 1000 commits in the history
2. Create a branch name of 16 characters
3. Open the branch in Github desktop client and notice that the commit number truncates the branch name in the display 

### Expected behavior

There's a lot of real estate in the upper panel of the Github for Desktop client, and the branch dropdown could be widened to show longer text. Ideally, it would be adjustable.

### Actual behavior

The branch name is truncated.

### Screenshots

![image](https://user-images.githubusercontent.com/55364874/157766779-0e51a0d4-caf7-4766-b2d4-d9376e8f800d.png)

Version
![image](https://user-images.githubusercontent.com/55364874/157767513-bf7d053b-3689-4c83-aa41-e5a32ccc2446.png)

### Logs

Not applicable.

### Additional context

Not applicable.

**Comment by niik** [comment]
Hey @leewynbpm, thanks for reaching out. This issue is being tracked in https://github.com/desktop/desktop/issues/4569 so I'm going to close this in favor of that. Please subscribe to that issue for any updates.
