### ISSUE TITLE
White scrollbar when dark mode is active

### ISSUE THREAD

**Issue by LukasPietzschmann** [desktop/desktop#14144]
### Describe the bug
The scrollbar in the list of changes stays white, although GH Desktop and my OS are in dark mode.

### Version & OS
2.9.12-beta1 & MacOS 12.2.1

### Steps to reproduce the behaviour
1. Switch GH Desktop to dark mode

### Expected behaviour
The whole UI (including all scrollbars) turns dark

### Actual behaviour
The whole UI, except the scrollbar in the list of changed files, turns dark

### Screenshots
![Screen Shot 2022-03-10 at 21 50 35 PM](https://user-images.githubusercontent.com/49213919/157753232-0482b098-7ece-4903-86b3-78e9d41412e4.png)

### Logs
[2022-03-10.desktop.beta.log](https://github.com/desktop/desktop/files/8227139/2022-03-10.desktop.beta.log)

### Additional context
It seems to be irrelevant, if GitHub follows the OS theme, or is set to dark mode by hand

**Comment by niik** [comment]
Hey @LukasPietzschmann, thanks for reaching out. There's a PR open to address this (#14142) which will hopefully make its way into a production release soon. Stay tuned!
