### ISSUE TITLE
GitHub desktop won't fetch or push branches

### ISSUE THREAD

**Issue by claytonaphillips1** [desktop/desktop#14157]
### Describe the bug
When I try to fetch a repo branch or publish changes to a branch, I get the standard Authentication Error message. I have signed in and out multiple times as well as reinstalled GitHub Desktop to no avail. My SSH key is fine since I can still manually push and pull branches via VS Code just fine. What's odd is it lets me make commits and I can also see the full commit history but it just won't let me push or pull.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.
GitHub Desktop Version: 2.9.11
Mac OS Version: 10.15.7

### Steps to reproduce the behavior

1. Click "fetch origin" or "publish branch" (after making a commit) on any branch
2. See error

### Expected behavior

It should fetch the latest version of the branch I'm on or publish the branch I've just made commits to. 

### Actual behavior

I get an error message (see screenshot below).

### Screenshots

<img width="629" alt="image" src="https://user-images.githubusercontent.com/53096212/157967692-94e23bcd-d919-4185-a6c5-061142b7c8f9.png">

### Logs

[2022-03-11.desktop.production.log](https://github.com/desktop/desktop/files/8235790/2022-03-11.desktop.production.log)

**Comment by AraHaan** [comment]
Did you try recloning the project using Github Desktop?

**Comment by claytonaphillips1** [comment]
@AraHaan it just hangs when I try to clone it.

<img width="769" alt="image" src="https://user-images.githubusercontent.com/53096212/157973194-0ac35701-93e7-48a8-ba5c-5f9050458e8a.png">

**Comment by claytonaphillips1** [comment]
here is the error I get 
<img width="750" alt="image" src="https://user-images.githubusercontent.com/53096212/157973825-efe96abf-03d9-44aa-b5c3-5ac7ed4a0eec.png">

**Comment by steveward** [comment]
Thanks for the report @claytonaphillips1. Are you behind a proxy or firewall that could be interfering with GitHub Desktop? If Git operations are working via the command line then it's likely something on your machine/network that is causing issues with askpass.

**Comment by claytonaphillips1** [comment]
@steveward I'm on a company VPN but beyond that, no. I've never had issues until today though and my colleagues who also use GitHub desktop aren't having any problems.

**Comment by claytonaphillips1** [comment]
In addition, I just disconnected from my VPN and tried to clone it but still no luck.

**Comment by claytonaphillips1** [comment]
Looks like I'm good to go now. I restarted my computer again (already did it once) and that did the trick. Thanks for the help
