### ISSUE TITLE
Conversion of crlf to lf and save then try and commit claims no changes when clearly there are actual changes!

### ISSUE THREAD

**Issue by eporto2021** [desktop/desktop#14158]
Conversion of crlf to lf and save then try and commit claims no changes when clearly there are actual changes!
2.9.11 x64

**Comment by steveward** [comment]
@eporto2021 thanks for the issue. It's possible you have the config option to ignore line ending changes enabled. Can you run `git config --list --show-origin` and let me know the output of that?
