### ISSUE TITLE
Persistent "Create a Branch" Modal Window

### ISSUE THREAD

**Issue by Schallenballa** [desktop/desktop#14156]
## Problem
The "_Create a Branch_" modal window disappears when I click outside of the modal or move/resize the overall Desktop window. 

#### Use Case:
This is an issue for me because sometimes when I am typing the name of my new branch, I need to move the window to look at a document behind the GitHub Desktop window with our naming standards/conventions to see how I need to structure the name. However, when I move the window, the "_Create a Branch_" modal will collapse and discard any value I had already typed into the `Name` field.

#### Steps to reproduce: 
1. Click "_New Branch_" to bring up the modal window
2. Drag the main GitHub Desktop window anywhere
3. Modal window will collapse and discards anything that was typed into the `Name` field

#### Alternative method of reproduction:
1. Click "_New Branch_" to bring up the modal window
2. Click _anywhere_ outside of the modal window but still inside of the GitHub Desktop app
3. Modal window will collapse and discards anything that was typed into the `Name` field

## Proposed solution
Make the modal window for "_Create a Branch_" persistent so that it does not automatically close whenever a user clicks outside of the window. Or, at a minimum, make the modal window persistent when a user is simply resizing or moving the GitHub Desktop window overall.

### Additional context
Occurs on MacBook Pro running macOS BIg Sur 11.6.4 and GitHub Desktop version 2.9.11

**Comment by steveward** [comment]
Thanks for the feedback @Schallenballa. This has been discussed in https://github.com/desktop/desktop/issues/7526 and https://github.com/desktop/desktop/issues/12885. Since https://github.com/desktop/desktop/issues/12885 is open I'm going to close this out in favor of that issue, but I'll make a note to bring this up in our next team sync for discussion.

**Comment by steveward** [comment]
We discussed this in our team meeting yesterday and the modal closing when clicking the title area is a bug that we're planning to fix.

**Comment by Schallenballa** [comment]
That is great to hear! Thank you for keeping me updated and listening to our feedback to address the issue!
