### ISSUE TITLE
Repo published to dotcom; Desktop failed to update status

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1415]
Added a local repo and clicked publish despite getting same error in #969 seen here:

<img width="590" alt="screen shot 2017-05-09 at 8 59 44 am" src="https://cloud.githubusercontent.com/assets/14828183/25852050/1331984c-3496-11e7-90f5-ed666fff9c1d.png">

Noticed the `Publish` button is still intact, even though the repo made it to dotcom. (Note, I cannot click `Publish` anymore, it seems disabled).

<img width="1112" alt="screen shot 2017-05-09 at 8 59 02 am" src="https://cloud.githubusercontent.com/assets/14828183/25852100/2e84114c-3496-11e7-8da2-9f958324bfdc.png">

<img width="762" alt="screen shot 2017-05-09 at 8 59 17 am" src="https://cloud.githubusercontent.com/assets/14828183/25852059/1a6d5358-3496-11e7-9020-615d567018a6.png">

Also, my `ReadMe` file was never published to dotcom either, nor recognized by Desktop as its missing from the History.

<img width="630" alt="screen shot 2017-05-09 at 8 59 25 am" src="https://cloud.githubusercontent.com/assets/14828183/25852104/32c12aba-3496-11e7-846b-ef4d67c4a045.png">

Problem seems to be my path, but nevertheless, the repo shouldn't have been published to dotcom.
<img width="1098" alt="screen shot 2017-05-09 at 9 12 23 am" src="https://cloud.githubusercontent.com/assets/14828183/25852540/b308af12-3497-11e7-9916-6d77b446cb28.png">

Fixed the path issue, and now getting a unborn branch error. Should we surface this error?
<img width="1112" alt="screen shot 2017-05-09 at 9 28 33 am" src="https://cloud.githubusercontent.com/assets/14828183/25853196/f572bb84-3499-11e7-8334-598e3aab8983.png">

v0.0.039, OSX 10.11.5

**Comment by joshaber** [comment]
I'm not sure if there's still a bug here 😀 so I'm gonna close this. @tierninho feel free to re-open with reproduction steps if there's still a bug.
