### ISSUE TITLE
Add schedule push/pull with notification option

### ISSUE THREAD

**Issue by MazighusDZ** [desktop/desktop#14159]
Hi GitHub team 

Manual pushing get tiring and sometimes get forgotten, for more efficient work, I like you add scheduling tasks similar to the Windows Task Scheduler with a notification option, this new feature is necessary, thank you so much :)

### Proposed solution

![image](https://user-images.githubusercontent.com/66381229/158002620-446c7d31-dc03-469b-aaec-0a7d54c070d5.png)

**Comment by steveward** [comment]
Thanks for the issue @MazighusDZ. At this time we have no plans to implement scheduling like this, but some users have requested automatic pushing on commit. You can find that in https://github.com/desktop/desktop/issues/2191 if you'd like to subscribe for any updates or leave feedback.
