### ISSUE TITLE
.gitconfig file

### ISSUE THREAD

**Issue by LaraKroencke** [desktop/desktop#14166]
Hi,

how can I change the location on my computer where the global .gitconfig file is stored?

Thanks
Lara

**Comment by steveward** [comment]
@LaraKroencke thanks for the issue. Is there a specific reason you are wanting to change the location of your `.gitconfig`? I may be able to provide a better solution with further details.

It is possible to modify system environment variables to change the default location, but I would recommend using [conditional includes](https://git-scm.com/docs/git-config#_conditional_includes) if you were wanting to store a config file in a different directory. However at this time there is a bug preventing GitHub Desktop from supporting conditional includes (https://github.com/desktop/desktop/issues/12041).
