### ISSUE TITLE
[Unwanted behaviour] Installing Github Desktop aplication adds desktop shortcut

### ISSUE THREAD

**Issue by KittenRaee** [desktop/desktop#14163]
### Describe the bug

Upon installing the aplication there isn't any installation wizard options, it just installs forcing a desktop shortcut to appear.

### Version & OS

Version 2.9.11 (x64) & 21H2 22000.556

### Steps to reproduce the behavior

Install the application 

### Expected behavior

No desktop shortcut should **ever** be placed.

### Actual behavior

Desktop shortcut is created

### Screenshots

n/a

### Logs

n/a

### Additional context

n/a

**Comment by steveward** [comment]
Thanks for the issue @KittenRaee. See my previous comment in https://github.com/desktop/desktop/issues/11837#issuecomment-803129610 for why we currently have no plans to change this. Once you delete the shortcut it will not reappear on updates. Thanks for using GitHub Desktop!
