### ISSUE TITLE
Program complaining about file size >100MB upon committing when its not

### ISSUE THREAD

**Issue by PiMoNFeeD** [desktop/desktop#14164]
### Describe the bug
Title.

### Version & OS
2.9.11 x64, Windows 8.1

### Steps to reproduce the behavior
I don't know, possibly use a file that is over 100kk bytes in size but still less than 100 megabytes in size

### Expected behavior
For it to allow me to commit without asking for Git LFS, obviously

### Actual behavior
Title.

### Screenshots
![image](https://user-images.githubusercontent.com/36343425/158078492-7dcada60-cced-479a-a6fc-90be615caed4.png)

**Comment by niik** [comment]
Hi @PiMoNFeeD, thanks for reaching out! Indeed it looks like there's a mismatch here between what GitHub Desktop considers a large file and what GitHub.com does. I'm going to mark this as a bug and see if we can't fix this for the next production release.

**Comment by PiMoNFeeD** [comment]
> Hi @PiMoNFeeD, thanks for reaching out! Indeed it looks like there's a mismatch here between what GitHub Desktop considers a large file and what GitHub.com does. I'm going to mark this as a bug and see if we can't fix this for the next production release.

Thanks for a quick fix! Is there any ETA on when this fix is going to be released?

**Comment by niik** [comment]
> Thanks for a quick fix! Is there any ETA on when this fix is going to be released?

We usually release about once a month so within a couple of weeks would be a rough estimate. We ship to our beta channel more frequently than that (see our README.md for links to install the beta channel). This shouldn't be blocking for you though given that you can opt to "commit anyway" right?

**Comment by PiMoNFeeD** [comment]
> > Thanks for a quick fix! Is there any ETA on when this fix is going to be released?
> 
> This shouldn't be blocking for you though given that you can opt to "commit anyway" right?

Yeah lol, I guess so, thanks!
