### ISSUE TITLE
on mac unable to signout from github desktop

### ISSUE THREAD

**Issue by Owais897** [desktop/desktop#14172]
### Describe the bug
unable to logout from github desktop

### Version & OS
Version 2.9.11 MAC

### Steps to reproduce the behavior

1. Go to 'file tab on top'
2.  'option' key isnt available
3. unable to logout as no option available

### Expected behavior

1. Go to 'file tab on top'
2.  'option' key should be available
3. able to logout as option available

Write a clear and concise description of what you expected to happen.
1. being able to logout

### Screenshots

<img width="1680" alt="Screenshot 2022-03-15 at 2 24 33 PM" src="https://user-images.githubusercontent.com/55442490/158347119-c103738c-992b-42b3-89d9-83579bd977d5.png">

**Comment by sergiou87** [comment]
Hi @Owais897 

You can find `Preferences` in the `GitHub Desktop` menu or by pressing <kbd>Command</kbd> + <kbd>,</kbd>

![2022-03-15 at 10 29](https://user-images.githubusercontent.com/1083228/158347892-2792897d-0cda-48fa-a75e-9d5fa69b47ff.png)

I hope that helps!
