### ISSUE TITLE
returning old and new code

### ISSUE THREAD

**Issue by eairafao** [desktop/desktop#14179]
### Describe the bug

When we merge the branch, GitHub Desktop recognizes the code difference. We chose a code to be the predominant one, however, when the code is sent .. both codes remain.

 EXAMPLE: "
 <<<<<<<< HEAD

xxxx
 xxxxxx

==============
xxxxx
  xxxxxxx
xxxxxxx"

### Version & OS

Version 2.9.11 and Windows

### Expected behavior

merge the codes, and get only 1

h
### Actual behavior

merging the two codes with comments

### Screenshots

![head](https://user-images.githubusercontent.com/63694647/158449994-6e65c0c5-ec92-4ec8-979c-c5831c893aee.png)

**Comment by steveward** [comment]
Thanks for the issue @eairafao. Just so I understand -- you're encountering merge conflicts and then choosing the `Use modified file from...` option, but the conflicts are not being correctly resolved? When you say 'code is sent` are you referring to pushing changes to GitHub? Any details you can share would be helpful.

I did test out the merge conflict flow and did not encounter any issues, so if you can provide some specific steps you are taking that would be helpful.
