### ISSUE TITLE
Integrate for Azure DevOps platform with its own features + options to create Pull request easily

### ISSUE THREAD

**Issue by aravindk777** [desktop/desktop#14184]
### Describe the feature or problem you’d like to solve

* Currently i can integrate the Azure DevOps (ADO) via add existing repo, or remote repo by url but it would be nice to integrate seamlessly via login or ADO url etc. 
* Creating the PR is not working always or as a link which can be improved.

### Proposed solution

Although VS and VS Code integrates Git within, github desktop can help manage all these git /ADO based projects in one place where there is no such tool for ADO currently

**Comment by steveward** [comment]
Thanks for the issue @aravindk777. At this time we have no plans to provide full support for other Git services. I'm going to close this out since it isn't on our radar and to help keep our issue tracker manageable. Thanks for using GitHub Desktop!
