### ISSUE TITLE
Not able to login, using browser or even entering credentials. Duplicate issues didn't help on resolving this issue

### ISSUE THREAD

**Issue by thecowmilk** [desktop/desktop#14188]
### Describe the bug
I can't log on my account in my Github Desktop. I use authenticate using browser or even I enter creds manually and still can't login.

### Version & OS
Version 2.9.9-linux2 (x64), OS: Ubuntu 20.04 LTS

### Steps to reproduce the behavior

1. Go to github desktop program.
2. Click on File -> Options -> Sign In -> Sign In using Browser 
3. Click on Continue with Browser
4. Keeps looping on logging but it won't log in

### Expected behavior

I just want to login to my account and open my repositories.

### Actual behavior
Keeps looping on login and it won't login me

### Screenshots

https://i.imgur.com/QuSckto.png

### Logs

https://pastebin.com/puugBSfe

**Comment by niik** [comment]
Hey @thecowmilk, thanks for reaching out. The issue with authenticating in Linux versions of GitHub Desktop is being tracked in https://github.com/shiftkey/desktop/issues/666. Please share details there as we do not officially support Linux at this time (see https://github.com/desktop/desktop/issues/1525).

**Comment by PauloBoaventura** [comment]
the problem still persists in the ubuntu version

**Comment by saad710** [comment]
the problem still persists in ubuntu.

**Comment by jmerort** [comment]
I still have this problem 🤕

**Comment by alex2qw** [comment]
same problem here

**Comment by pkgangadharan** [comment]
Same problem
Github Desktop Version 3.4.12-linux1 (x64)
Ubuntu 25.04

**Comment by ytcyde** [comment]
Same issue. Cinnamon, arch linux.

**Comment by Tormentous** [comment]
same issue

**Comment by ShakSheep** [comment]
The problem also persist in KDE Arch when using the flatpak version over the AUR one.

**Comment by hutaoshusband** [comment]
Same issue here, Arch Linux, Linux 6.19.9-arch1-1, Hyprland

**Comment by ExoriumYTB** [comment]
Same issue here when using firefox

OS: Arch Linux
VM:Hyprland
KERNEL: 7.1.4-arch1-1
