### ISSUE TITLE
All app is blurry

### ISSUE THREAD

**Issue by banban60** [desktop/desktop#14190]
### Describe the bug
All the app is blurry, even if I restart it. I reset the zoom and it doesn't change anything

### Version & OS
Windows 10, version 2.9..11(x64)

### Steps to reproduce the behavior

1. Just start the app

### Expected behavior

A not blurry image

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

![image](https://user-images.githubusercontent.com/79019044/158622494-d0b77e56-12f9-4791-851d-a6b80ac5f89a.png)

### Logs

[2022-03-16.desktop.production.log](https://github.com/desktop/desktop/files/8263903/2022-03-16.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @BanbanProduction. A few questions:

- Do you have any scaling or other display preferences enabled? 
- What resolution display are you using? 
-  Are you using multiple monitors?

Windows has an option to [fix apps that are blurry](https://support.microsoft.com/en-us/windows/fix-apps-that-appear-blurry-in-windows-10-e9fe34ab-e7e7-bc6f-6695-cb169b51de0f) -- could you try that to see if it helps things?

**Comment by banban60** [comment]
Everything in my parameters is in default mode, I only use one monitor, and the windows is enabled and changes nothing.

**Comment by tsvetilian-ty** [comment]
Hey @BanbanProduction 👋

A friend of mine used to have a similar problem, and it was the Nvidia antialiasing setting. The following steps might help in your case.

1. Open Nvidia Control Panel
2. Select "Manage 3D settings"
3. Choose the "Program Settings" tab
4. Click "Add" and pick GitHubDesktop
5. In "Specify the settings for this program", make sure that Antialiasing - FXAA is set to Off

Restart Github Destkop after the changes!

**Comment by banban60** [comment]
Thank you very much, this solved my problem !

**Comment by PaxRon777** [comment]
To report I had the same problem, Nvidia anti-aliasing settings was the issue.
