### ISSUE TITLE
Right-click option to "Include selected changes"

### ISSUE THREAD

**Issue by joyfullservice** [desktop/desktop#14198]
### Search for existing feature requests

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the feature I am requesting.

### The feature request

If you select a list or range of files, you can right-click and **_discard_** those changes, but you can't add them to the selected files that you want **_included_** in the commit.

![image](https://user-images.githubusercontent.com/7254992/158875877-137f1167-6b77-4e1c-a7b7-c1387369c8ef.png)

This would be very helpful when dealing with a large numbers of changed files that I am wanting to selectively add to different commits. At present the only option is to select them one by one after clicking to select all or select none. This can get rather tedious when working with hundreds of files.

### Proposed solution

Add a context menu option named "Include 16 selected files". In functionality, this would check the box for each selected item to include it in the list of files included in the commit.

### Additional context

I realize that probably the biggest barrier here is in making the terminology clear. You have a _selection_ that means you checked the box, and a _selection_ that means you have highlighted the file in the list. It would confuse the user if we give them the option to "Add the selection to the selection", or to "Remove the selected files from the selection".

We could use terms like **Include** to refer to the checkbox, and **selection** for the files that are selected in the list. The rationale behind this is that the end goal is to select which files should be included in the commit.

Along those lines, I would propose the following wording for the context menu:

- **Include 16 selected files**
- **Do not include 16 selected files**

For the second item, I intentionally did not use the logical antonym _Exclude 16 selected files_ because this could easily be confused with _ignoring_ the files in git, which is not the intent. It keeps the focus on the end result of which files are _included_ in the commit.

To make this even more intuitive, I would suggest that the context menu also be aware of whether the items are checked to include in the commit. If nothing is currently selected (no boxes checked), we only need to show them the option to include the files. Similarly, if all the files are selected, the only relevant option is to _not include_ them. If we have a mixed selection, we can show both options.

Thanks for your consideration!!

**Comment by tidy-dev** [comment]
@joyfullservice Thank you for your suggestions! I believe feedback for this enhancement idea is already being tracked by https://github.com/desktop/desktop/issues/7790. Feel free to subscribe and/or add any additional input there. 

Something you may find useful is that when you select multiple files like this, you can toggle the checkboxes by pressing the space bar or enter key.
