### ISSUE TITLE
Creating a "new branch" should takeover changes

### ISSUE THREAD

**Issue by kuehn-sba** [desktop/desktop#14194]
That's how it was in the "classic" version and that was basically very good - especially when you realize that you'd rather put the changes you made into a separate branch.

**Comment by tsvetilian-ty** [comment]
@kuehn-sba, when creating a new branch, you can bring the changes or leave them on the current branch.

![image](https://user-images.githubusercontent.com/9341546/158794444-3178db31-bf5a-4a79-8ba9-4d19e9bd9e24.png)

**Comment by kuehn-sba** [comment]
I mean the takeover of changes that remain as "stashed changes" in the based branch (in this case, a basis other than 'master').

**Comment by kuehn-sba** [comment]
This could help:
![1](https://user-images.githubusercontent.com/8360913/158796684-17474983-871b-44b6-a5aa-e33af7da3d0b.png)
.

**Comment by kuehn-sba** [comment]
I think that settles the issue.

**Comment by steveward** [comment]
Glad to hear that setting will work for you @kuehn-sba. Let us know if you have any other questions.
