### ISSUE TITLE
Need add context support visual studio

### ISSUE THREAD

**Issue by chuongmep** [desktop/desktop#14209]
### Search for existing feature requests

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the feature I am requesting.

### The feature request

I use visual studio 2022 to work with project, wether we can add context menu open in visual studio open file sln ?
![image](https://user-images.githubusercontent.com/31106432/159112581-ab9d7d80-27a7-4ccc-9494-5a88344aef08.png)
Some feature look like this
![image](https://user-images.githubusercontent.com/31106432/159112678-a6e1be7b-1f5b-45f4-98e3-be2399b73677.png)

### Proposed solution

Help many developer .net open project quickly

**Comment by steveward** [comment]
Thanks for the issue @chuongmep -- we're tracking Visual Studio support in https://github.com/desktop/desktop/issues/12946. Unfortunately there are some issues with integrating VS (see https://github.com/desktop/desktop/pull/13395#discussion_r757799482), but you can follow along for updates. We also have https://github.com/desktop/desktop/issues/7033 open which is tracking broader improvements to our editor integrations.

You can also use the `Open with Default Program` option from the file context menu to open files with the default system application. I hope that's helpful! I'm going to close this out.

**Comment by chuongmep** [comment]
Nice, thanks for infomation!
