### ISSUE TITLE
Hide commits from other branches in history tab

### ISSUE THREAD

**Issue by bnjix** [desktop/desktop#14201]
### Search for existing feature requests

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the feature I am requesting.

### The feature request

The history tab is useful when I'm working on a separate branch from master. It gives me an easy way to access past commits and recent changes.
However, as soon as I merge master (or I suspect any other branch) into my branch, the history tab gets polluted with all other commits from the other branch. I can no longer get a clear view of my changes

### Proposed solution

Only show the current branche's commits when looking at the history tab - in other words exclude commits resulting from a merge. Might still want to show that a merge happened somehow (maybe that's a single squash-style commit).

**Comment by tidy-dev** [comment]
@bnjix Thank you for the suggestion! What you describe is similar to https://github.com/desktop/desktop/issues/1691. It sounds like wanting to view `git log --first-parent` as opposed to just `git log`. This would mean the history would show commits made to the branch and merge commits only (not the merge commit's "children"). Our current approach to displaying the branch history matches dotcom and therefore we will likely not change the default behavior. 

However, I am adding enhancement for this as it is can be useful and I will jump out to a terminal to see it. But, if implemented would likely be something like a checkbox/setting toggle not a default behavior; and we currently do not have plans to add the feature at this time.

**Comment by bnjix** [comment]
@tidy-dev Thank you for the prompt reply and what you are describing is exactly what I had in mind.

A checkbox/setting toggle would be more than enough here, and I agree that changing the default behavior is probably not what should be done. I'll keep an eye on this, and thanks again!

**Comment by BrianAtAFG** [comment]
I think this need is now met by the Compare Branches feature #3956.   It shows you the commits that exist on your branch that do not exist on the parent branch.

**Comment by bnjix** [comment]
Looks like it, thanks!

**Comment by dmudro** [comment]
ability to view commit log with `--first-parent` only would be very useful. main use case is in better history overview in repos with a lot of activity: it _visually_ squashes merge commits without actually being squashed.

it's probably the only feature I am missing in GitHub Desktop vs [Sourcetree](https://www.sourcetreeapp.com/):

![image](https://github.com/desktop/desktop/assets/1648143/a02632ee-f26b-44d2-af8e-ad9fc3566ae6)
