### ISSUE TITLE
Error: spawn C:\FFmpeg ENOENT (with how to fix)

### ISSUE THREAD

**Issue by ccppoo** [desktop/desktop#14202]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

after installing (downloading ffmpeg zip file and placing at C: drive (C:\\)

add system variables for ffmpeg

opening VSCode via Github Desktop fails with this message

```
Error: spawn C:\FFmpeg ENOENT

```

### Release version

2.9.11

### Operating system

Windows 10.0.19044

### Steps to reproduce the behavior

1. download ffmpeg distribution
2. move to C drive
3. add system variables

1. open VSCode via Github Desktop
2. error happens

### Additional context

# HOW I FIXED IT

look for System variables and check both 

USER's and System variable and look for variables pointing to **ffmpeg**

in my case, as I knew this error raised after ffmpeg installation, there was two  system path to ffmpeg

calling ffmpeg in command prompt had no problems,

but it looks like github desktop is scanning system path or **ffmepg**

1. open system path
2. check paths that are pointing to ffmpeg
3. **remove duplications** (could be three or more ffmpeg system variables)

+ no difference with lowwer / upper case (ffmpeg <--> FFmpeg)

**Comment by tsvetilian-ty** [comment]
Hi @ccppoo, your issue looks similar to #14129. GitHub Desktop uses VS Code `InstallLocation` field in the registry entry to open it. Can you share the result from the steps I suggested in [that](https://github.com/desktop/desktop/issues/14129#issuecomment-1068073046) comment?

**Comment by ccppoo** [comment]
@tsvetilian-ty 

something unexpected is that installDate is marked as `20220311` 

![image](https://user-images.githubusercontent.com/46418312/158985693-061416e4-1ded-4848-bcd5-84d62575e9fd.png)

would this help even if I reinstalled yesterday?

censor is User name

**Comment by tsvetilian-ty** [comment]
Thanks for the fast response @ccppoo. I think the reason for the issue might be the path separators. Can you copy the path of `InstallLocation` (you can remove your username from it) and share it as a snippet? 

You can copy by right-clicking `InstallLocation` > Modify > Value Data.

**Comment by ccppoo** [comment]
```
C:\Users\<USER_NAME>\AppData\Local\Programs\Microsoft VS Code\
```

**Comment by tsvetilian-ty** [comment]
@ccppoo I change my VM regional settings to Korean and have a duplicate registry entry to match yours, but it works in my case. The issue is not related to the path separators!
![image](https://user-images.githubusercontent.com/9341546/159001909-52884bf3-da9e-4332-b3f9-feb03db3fe59.png)

Can you try to start VS Code from your terminal/command prompt?
```
code .
```

**Comment by ccppoo** [comment]
@tsvetilian-ty 
When I had this problem there was ffmpeg enviornment variables pointing

| Variable name | Path |
|-----| -----| 
| Path | C:\\ffmpeg | 
| Path | C:\\ffmpeg\bin | 
| ComSpec |  C:\\ffmpeg | 

can't remember whether it was at USER's path or System's path
as I had already solved the problem opening VS Code so I'm not sure if I could reproduce this error

```
code .
```

works fine

sorry that I'cant give any more hints for reproducing this problem nor what's happening :(

**Comment by tsvetilian-ty** [comment]
@ccppoo I get it now I thought you changed only the `Path` variables. If your `ComSpec` is changed, that explains the problem! `ComSpec` is a path reference to the default command prompt. The default value for `ComSpec` should be `%SystemRoot%\system32\cmd.exe`

#### `ComSpec` SET to `C:\Users\test\Desktop\Crash_Test`:
![scree-rec](https://user-images.githubusercontent.com/9341546/159004914-8fb267f7-3501-452c-95d5-efa585b2ca32.gif)

#### `ComSpec` properly set:
![scree-rec](https://user-images.githubusercontent.com/9341546/159005223-dfc6a165-e043-42d3-88c6-0a8bde634c9d.gif)

**Comment by ccppoo** [comment]
@tsvetilian-ty 
I've no memories about changing ComSpec
maybe there should be concensus about modifying "ComSpec" IDEs and anyother programs

hmm.. why did my ComSpec was pointing to ffmpeg?

anyways.. Cheers! 🎉 I was the Riddler

**Comment by steveward** [comment]
Glad to hear things are working again @ccppoo, and thanks @tsvetilian-ty for your debugging! ✨

**Comment by Evani-maker** [comment]
make a video on how to change to %SystemRoot%\system32\cmd.exe
