### ISSUE TITLE
stash specific files

### ISSUE THREAD

**Issue by wadie** [desktop/desktop#14207]
### Search for existing feature requests

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the feature I am requesting.

### The feature request

It is currently possible to right click the top bar of changed files and stash all the changes.

Feature request: should be possible to specific files.

### Proposed solution

Right click an individual file or several files and stash only those selected.

**Comment by steveward** [comment]
Thanks for the feedback @wadie. This is being tracked in https://github.com/desktop/desktop/issues/11531, you can follow along there for updates.
