### ISSUE TITLE
Unable to cherry pick from compare branches.

### ISSUE THREAD

**Issue by adrianspacely** [desktop/desktop#14217]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

**Request:** it would be convenient to cherry-pick from the commits in `History -> Compare -> Behind` into the checked-out branch.

### Release version

2.9.11

### Operating system

MacOS 12.3 arm64

### Steps to reproduce the behavior

1. I checked out a branch, i.e. `main`
2. I compared a branch, i.e. `develop`
3. I wanted to cherry-pick the commit that was on `develop` to `main`

Because I checked out `main` and wanted to cherry-pick to `main`, I got the message "You are not able to cherry-pick to the same branch."

As a user, I wanted to merge, but there were changes I didn't want to include. I was in the flow of wanting to merge something and cherry-picking would have been great from where I was.

**Comment by tidy-dev** [comment]
@adrianb93 Thanks for the input! I believe this is a duplicate to https://github.com/desktop/desktop/issues/12688 and am closing in favor of tracing feedback on the issue there.
