### ISSUE TITLE
Unkown Errors and 3221225477 error.

### ISSUE THREAD

**Issue by CeelB-2055440** [desktop/desktop#14212]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

Whin I open github desktop, push, pull, change repository or clone, I often get an Unknown error. Sometimes I get the error with error code 3221225477. Restarting PC doesnt fix it, reinstalling Git and GitHub doesn't fix it. Sometimes even an error by shut having GitHub opend.

### Release version

Version 2.9.11 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Open GitHub

1. Open GitHub
2. Wait

1. Open GitHub
2. Fetch origin

1. Open Github
2. make a Commit
3. Push Origin.

1. Open GitHub
2. File
3. Clone repository
4. Select repository
5. clone

### Log files

[2022-03-19.desktop.production.log](https://github.com/desktop/desktop/files/8309849/2022-03-19.desktop.production.log)

### Screenshots

![afbeelding](https://user-images.githubusercontent.com/71815809/159133680-bd43f87e-5070-45b4-9365-bf160928f332.png)

**Comment by steveward** [comment]
Thanks for the report @CeelB-2055440. It looks like there is an issue with your installation:

```
2022-03-19T17:44:55.142Z - error: [ui] Branch fast-forwarding failed
GitError: Unknown error
```

Are you running any antivirus software that could be interfering with the installation of GitHub Desktop or Git operations?

If that isn't the case I would recommend trying a full fresh reinstall of GitHub Desktop to see if that helps. I know you mentioned you reinstalled but it's also recommended to delete local installation directories prior to reinstalling.

Here's how to do that:

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `%AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that helps at all.

**Comment by ghost** [comment]
No it did not work. I even tried it twice. But sometimes it works sometimes it gives me an error. But when it gives me an error it still  completes it's task.

**Comment by ghost** [comment]
I only have windows defender as an antivirus installed. But it often detects PowerShell/malefigams.h as a virus but it can not remove it nor place it in quarantaine. Restarting the pc sometimes works. In the span of 3 day I have reinstalled windows 6 times each time github gave me that error. But only when I had git installed. Using Git GUI it works just fine.

**Comment by steveward** [comment]
My next recommendation would be to open up an elevated command prompt and run `sfc /scannow` to see if there are any broader system issues that need to be repaired, but if you've done a fresh installation of Windows then that may not be the issue. Unfortunately these types of errors can be difficult to track down since they're often specific to the system.

**Comment by StevenKamwaza** [comment]
I am still experiencing this error every time I open GitHub Desktop. Is there a  solution for this?

![Image](https://github.com/user-attachments/assets/ffe6a2dd-28b4-41b6-8017-962ae6bad972)

**Comment by dmitrykinakh** [comment]
@StevenKamwaza - I also have this issue as well. Not sure what is wrong. Have you got this resolved?

**Comment by dmitrykinakh** [comment]
@HeeMa6 - not sure what you have attached. Seems like unrelated file.

**Comment by HeeMa6** [comment]
> - ไม่แน่ใจว่าคุณแนบอะไรไว้ ดูเหมือนไฟล์ที่ไม่เกี่ยวข้อง

**Comment by StevenKamwaza** [comment]
> [@StevenKamwaza](https://github.com/StevenKamwaza) - I also have this issue as well. Not sure what is wrong. Have you got this resolved?

No... I switched OS, no longer facing such issue
