### ISSUE TITLE
Selected diff text look bad (Windows, dark mode)

### ISSUE THREAD

**Issue by marc2k3** [desktop/desktop#14227]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

I noticed it just now immediately after being upgraded to 2.9.12.

It's not nice and I'm not a fan of those checkboxes either

![image](https://user-images.githubusercontent.com/62050527/159691940-a47a2ce7-7b76-4d7b-9328-ab2c0fcf7b77.png)

### Release version

2.9.12

### Operating system

Windows 10 19044

**Comment by tidy-dev** [comment]
Verified the selected text used to look like:

![Screen Shot 2022-03-23 at 12 01 43 PM](https://user-images.githubusercontent.com/75402236/159743249-f1b0d95e-9cd3-4c56-8ed8-49968db85c9b.png)

versus now:
![Screen Shot 2022-03-23 at 12 02 00 PM](https://user-images.githubusercontent.com/75402236/159743226-35d92199-89a0-447f-8b14-e8eaecfe1c92.png)

I am assuming this is a regression cause by: https://github.com/desktop/desktop/pull/14142

**Comment by marc2k3** [comment]
No idea when this was fixed but it is now so closing.
