### ISSUE TITLE
PAT fails on authenticating a push

### ISSUE THREAD

**Issue by IndigoHomme** [desktop/desktop#14223]
I enter:
  `git push --set-upstream origin master`

I am prompted for a username that I enter.
Then I enter the PAT for the password and receive this:

```
remote: Permission to IndigoHomme/LearningRuby.git denied to IndigoHomme.
fatal: unable to access 'https://github.com/IndigoHomme/LearningRuby.git/': The requested URL returned error: 403
```

**Comment by steveward** [comment]
@IndigoHomme this issue tracker is for GitHub Desktop. If you're having problems pushing to GitHub please contact [GitHub Support](https://support.github.com/). I'd first recommend verifying your token hasn't expired and permissions have been set correctly.

**Comment by IndigoHomme** [comment]
My mistake.
Thanks Steve.
