### ISSUE TITLE
Text out of range when group name is long

### ISSUE THREAD

**Issue by chaerin-dev** [desktop/desktop#14233]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

When I click the Current Repository tab, the long-name group is out of range in the drop-down menu, so I can't read the name clearly.

### Release version

Version 2.9.12 (x64)

### Operating system

macOS Monterey

### Steps to reproduce the behavior

1. Click on 'Current Repository'
2. See error (If you have long -name group)

### Screenshots

<img width="1072" alt="스크린샷 2022-03-24 오후 8 50 12" src="https://user-images.githubusercontent.com/70943835/159911178-bb2f390f-1f59-48d7-97fb-de6c5e00e7c4.png">

**Comment by Derick128** [comment]
Any one wanna help
