### ISSUE TITLE
unknown error when creating new repo 

### ISSUE THREAD

**Issue by Steven-zion** [desktop/desktop#14241]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

I cant clone or create new repo with the git desktop. am getting a popup with msg 'unknown error' I've tried checking for updates but am getting the error msg 'spawn UNKNOWN'
I've checked previous issues and it recommended to open a new issue
errror img:
![git issue](https://user-images.githubusercontent.com/68914811/160298101-723913bc-db45-477f-9e8e-8aad201957f3.jpg)
the log:
[2022-03-27.desktop.production.log](https://github.com/desktop/desktop/files/8358347/2022-03-27.desktop.production.log)
'

### Release version

Version 2.9.0 (x64)

### Operating system

windows 10 pro

### Steps to reproduce the behavior

1. click create tutorial repo
2. wait for the 10seconds load before the error

the same error works in cloning a repo

### Log files

[2022-03-27.desktop.production.log](https://github.com/desktop/desktop/files/8358341/2022-03-27.desktop.production.log)

### Screenshots

![git issue](https://user-images.githubusercontent.com/68914811/160297995-8e27e956-bc71-4114-9047-07922e1128ac.jpg)

### Additional context

please confirm if the issue may affect my vscode and github linkup coz vscode has been working weird when i try to perform the git actions

**Comment by sergiou87** [comment]
Hi @Steven-zion ! 👋 

That problem sounds to me like something like an antivirus might have deleted some installation files. Is it possible that you have an antivirus or something like that?

If so, you probably can mark GitHub Desktop files as "safe" in your antivirus or at least disable it temporarily. In any case, you might need to reinstall the app 😞
