### ISSUE TITLE
Re-run checks visual bug

### ISSUE THREAD

**Issue by wojtekmaj** [desktop/desktop#14246]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

Re-run checks window has a visual bug where the list of checks overflows the container. Possibly due to a longer than predicted list of checks and lack of scrolling?

### Release version

2.9.12 (x64)

### Operating system

macOS Monterey

### Screenshots

<img width="430" alt="image" src="https://user-images.githubusercontent.com/5426427/160453190-7eed8dce-e382-4c07-ab2c-c48cba54de9d.png">

**Comment by steveward** [comment]
Thanks for reporting this @wojtekmaj!

**Comment by wojtekmaj** [comment]
This warning seems useless BTW 🤔 If there are 0, why would I care?
