### ISSUE TITLE
Unable to push to GitHub

### ISSUE THREAD

**Issue by JP-CASSOU** [desktop/desktop#14248]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

error: invalid object 100644 a70798080337efad39ed4509599ae616484238b2 for 'frmclaviervirtuel.pas'
error: invalid object 100644 a70798080337efad39ed4509599ae616484238b2 for 'frmclaviervirtuel.pas'
error: Error building trees

Painfull error +++

These annoying bugs make Github Desktop completely unusable 

### Release version

Version 2.9.12 (x64)

### Operating system

Windows 10

### Screenshots

![image](https://user-images.githubusercontent.com/5596861/160483215-5b075f80-2da5-484e-83fc-f5c320c9e427.png)

**Comment by steveward** [comment]
Thanks for the report @JP-CASSOU. Unfortunately this type of error often indicates repository corruption. Can you open the repository in the command line (`Repository` > `Open in <command_line_app>` and run the following command?

`git fsck`

Let me know the full output of that command.
