### ISSUE TITLE
Don't login use browser

### ISSUE THREAD

**Issue by DenRen** [desktop/desktop#14242]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

After reinstall OS I download GitHub Desktop. but I can't login. When I confirm login in browser I get infinity loading of GitHub Desktop.

### Release version

2.9.9

### Operating system

Linux Mint 20.3 Cinnamon

### Steps to reproduce the behavior

1. Install GitHub Desktop
2. Sign in from browser
3. Get infinity loading

**Comment by sergiou87** [comment]
Hi @DenRen! 👋  Issues related to the unofficial Linux fork of GitHub Desktop can be filed here:

https://github.com/shiftkey/desktop/issues

At this time we only officially provide support for macOS and Windows.

Sorry!

**Comment by PauloBoaventura** [comment]
the problem still persists in the ubuntu version
