### ISSUE TITLE
How can I put my username in desktop github?

### ISSUE THREAD

**Issue by JoaquinSanchezG** [desktop/desktop#14247]
In the App i can't pull the changes i want. The text said that I am an unknown user. How can I put my username? I am log in in my account.

**Comment by steveward** [comment]
@JoaquinSanchezG thanks for the issue. I would first make sure that you are logged in by going to `File` > `Options` > `Accounts`. You can also verify that your correct name and email are set for your commits by going to the `Git` section of the options menu.

If you have any further issues let us know!
