### ISSUE TITLE
"Git returned an unexpected exit code '3221225477' which should be handled by the caller." when adding an existing local repository.

### ISSUE THREAD

**Issue by Monsoonexe** [desktop/desktop#14254]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

When adding an existing local repository to GitHub Desktop, it kicks back with the given error. It then tells me that the repository could not be found, and I have to re-add it. I do this cycle until it eventually works as expected (adds the existing repository into my list of repos).

![image](https://user-images.githubusercontent.com/43690629/160702732-4282bb7d-41d7-46db-aff1-3c2c35c69dec.png)

Just now I experienced this same error after the repository was added and when I fetched for the first time.

### Release version

Version 2.9.12 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Download GitHub Desktop.
2. Add existing local repository
3. If it doesn't show this error now...
4. Discard all changes
5. If it doesn't show this error now...
6. Fetch

### Log files

[2022-03-29.desktop.production.log](https://github.com/desktop/desktop/files/8374915/2022-03-29.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/43690629/160704315-40aca209-6613-4c56-9056-0bfc3041fe88.png)

### Additional context

The repo was copied from another machine which had some changes on it. The repo is ~30 GB.

**Comment by sergiou87** [comment]
Does the repository use Git LFS?

**Comment by flony-hub** [comment]
buenas noches, tengo el mismo problema con GitHub Desktop 
la version es 
![image](https://github.com/user-attachments/assets/e49bb03a-38db-4bc6-916e-0e6f39d5a7bb)
no uso Git LFS
