### ISSUE TITLE
Cloning repository 

### ISSUE THREAD

**Issue by flexgaming** [desktop/desktop#14250]
### Search existing issues

- [ ] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

I have a problem with cloning a repository that i have been invited to. There is an error message that says that my filename is too long and because of that it won't download the whole repository.

The filename is as such:
"Explorius/Library/PackageCache/com.unity.ide.visualstudio@2.0.11/Editor/AppleEventIntegration~/AppleEventIntegration.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist"

### Release version

Version 2.9.12 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Trying to clone repository
2. Choosing file path
3. Pressing cloning button
4. File loading and connecting
5. Cloning done but download not

### Log files

[shadercompiler-UnityShaderCompiler.exe0.log](https://github.com/desktop/desktop/files/8370858/shadercompiler-UnityShaderCompiler.exe0.log)
[shadercompiler-UnityShaderCompiler.exe1.log](https://github.com/desktop/desktop/files/8370859/shadercompiler-UnityShaderCompiler.exe1.log)
[shadercompiler-UnityShaderCompiler.exe2.log](https://github.com/desktop/desktop/files/8370860/shadercompiler-UnityShaderCompiler.exe2.log)
[shadercompiler-UnityShaderCompiler.exe3.log](https://github.com/desktop/desktop/files/8370861/shadercompiler-UnityShaderCompiler.exe3.log)
[shadercompiler-UnityShaderCompiler.exe4.log](https://github.com/desktop/desktop/files/8370862/shadercompiler-UnityShaderCompiler.exe4.log)
[shadercompiler-UnityShaderCompiler.exe5.log](https://github.com/desktop/desktop/files/8370863/shadercompiler-UnityShaderCompiler.exe5.log)
[shadercompiler-UnityShaderCompiler.exe6.log](https://github.com/desktop/desktop/files/8370864/shadercompiler-UnityShaderCompiler.exe6.log)
[shadercompiler-UnityShaderCompiler.exe7.log](https://github.com/desktop/desktop/files/8370865/shadercompiler-UnityShaderCompiler.exe7.log)
[shadercompiler-UnityShaderCompiler.exe8.log](https://github.com/desktop/desktop/files/8370866/shadercompiler-UnityShaderCompiler.exe8.log)
[shadercompiler-UnityShaderCompiler.exe9.log](https://github.com/desktop/desktop/files/8370867/shadercompiler-UnityShaderCompiler.exe9.log)
[shadercompiler-UnityShaderCompiler.exe10.log](https://github.com/desktop/desktop/files/8370868/shadercompiler-UnityShaderCompiler.exe10.log)
[shadercompiler-UnityShaderCompiler.exe11.log](https://github.com/desktop/desktop/files/8370869/shadercompiler-UnityShaderCompiler.exe11.log)
[shadercompiler-UnityShaderCompiler.exe12.log](https://github.com/desktop/desktop/files/8370870/shadercompiler-UnityShaderCompiler.exe12.log)
[shadercompiler-UnityShaderCompiler.exe13.log](https://github.com/desktop/desktop/files/8370871/shadercompiler-UnityShaderCompiler.exe13.log)
[shadercompiler-UnityShaderCompiler.exe14.log](https://github.com/desktop/desktop/files/8370872/shadercompiler-UnityShaderCompiler.exe14.log)
[shadercompiler-UnityShaderCompiler.exe15.log](https://github.com/desktop/desktop/files/8370873/shadercompiler-UnityShaderCompiler.exe15.log)
[AssetImportWorker0.log](https://github.com/desktop/desktop/files/8370874/AssetImportWorker0.log)
[Packages-Update.log](https://github.com/desktop/desktop/files/8370876/Packages-Update.log)
[shadercompiler-AssetImportWorker0.log](https://github.com/desktop/desktop/files/8370877/shadercompiler-AssetImportWorker0.log)

### Screenshots

![error message file too long](https://user-images.githubusercontent.com/17099528/160599879-58848a83-739f-475e-bad7-2d2716d1e0a8.png)

### Additional context

This is currently not only happening to this pc but also my other pc and it is also not the only repository that dont want to be downloaded.

**Comment by bayleev33me** [comment]
I don't know how to stay on it still studying. what can I do to help you

David bayleev

**Comment by sergiou87** [comment]
Maybe you need to enable long paths in that repository. Could you try any of the solutions from https://stackoverflow.com/a/34415249 and see if they work? 🤞

**Comment by flexgaming** [comment]
> Maybe you need to enable long paths in that repository. Could you try any of the solutions from https://stackoverflow.com/a/34415249 and see if they work? 🤞

I have already tried that but i just get the same error message

![error message file too long](https://user-images.githubusercontent.com/17099528/161208998-2f2b18c4-159d-455f-86a4-c1c66f2ca1d5.png)

**Comment by sergiou87** [comment]
That's bad 😥  Can you clone it from command line at least? It's a workaround, but can get you unblocked 🤞

**Comment by flexgaming** [comment]
> That's bad 😥 Can you clone it from command line at least? It's a workaround, but can get you unblocked 🤞

I have just tried this but apparently i don't have access to to the project. However i have also tried it on the other project i was talking about that had the same problem. Is it because I have to create a SSH key or something?

![Git clone with command not working](https://user-images.githubusercontent.com/17099528/161250321-458ec28b-8996-4f7c-8c3c-ef5ba5d39b0d.png)

**Comment by sergiou87** [comment]
Oh, when you are prompted for your username and password, you have to provide your username and a [Personal Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token).

Alternatively, you can open the `Credential Manager` on Windows, look for the `GitHub - https://api.github.com/flexgaming` entry and pick the "password" from there (which is the token used by GitHub Desktop to authenticate on git). Then you use `flexgaming` as your username and that token as your password when `git clone` prompts for credentials, and that should work 🤞

**Comment by flexgaming** [comment]
> Oh, when you are prompted for your username and password, you have to provide your username and a [Personal Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token).
> 
> Alternatively, you can open the `Credential Manager` on Windows, look for the `GitHub - https://api.github.com/flexgaming` entry and pick the "password" from there (which is the token used by GitHub Desktop to authenticate on git). Then you use `flexgaming` as your username and that token as your password when `git clone` prompts for credentials, and that should work 🤞

Thank you, this solved the problem! I  don't know why it have to be so difficult to download, but this seems to work just fine! :)
