### ISSUE TITLE
Ability to customize "commit message length" nag

### ISSUE THREAD

**Issue by dangerismycat** [desktop/desktop#14255]
### Search for existing feature requests

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the feature I am requesting.

### The feature request

I'd like the ability to customize the nag about the commit message length. I'd like to be able to specify the number of characters or turn it off completely.

### Proposed solution

Different repos have different standards around things like commit message length. This is the sort of thing we can configure with linters and code formatters; we should allow per-repo configuration of this nag as well.

**Comment by strughle333** [comment]
yes ready

**Comment by steveward** [comment]
Requested in #14722:

>This may be "right" or "wrong" either way it's way to aggressive to always come up and no option to disable it.
Maybe our team thinks 49 or 51 characters is the magic number... don't force this on us.

**Comment by DanielRouxSA** [comment]
I'd like to request this as well. In our team's case, we have no reason to limit the length of our commit messages, so the message is superfluous to us.

**Comment by steveward** [comment]
From https://github.com/desktop/desktop/issues/16456:

>Currently the app is showing lightbulb icon when 50 characters met but sometimes you do need a bit more and it's nice to know the point where the commit message will be cutted (I guess it's at 72 symbols) and the rest of it will go to commit description.

**Comment by steveward** [comment]
Closing this out since https://github.com/desktop/desktop/pull/16643 will soon be merged to remove the commit length hint entirely.

**Comment by niik** [comment]
Hey @dangerismycat, as of https://github.com/desktop/desktop/pull/17370 it's possible to disable the commit message length warning and it's off by default for new installs.

![Image](https://github.com/user-attachments/assets/2fc2a9c5-17c4-4def-a298-10bb34255193)

Given that the ability to turn it off was one of your possible solutions I'm going to close this out.
