### ISSUE TITLE
Git Worktree Support - Pull not available

### ISSUE THREAD

**Issue by BOFH-raf** [desktop/desktop#14251]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

My Git structure is

.\repo (bare)
.\branchA (worktree)
.\branchB (worktree)

While basic worktree operations work (e.g. commit), it is currently not possible to PULL changes. The Pull menu entry is always greyed-out if a worktree is used.

### Release version

2.9.12

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Add local repository
2. Navigate to e.g. Feature2 worktree
3. Open the Repository Menu
4. The Pull command is not available

### Log files

no entry

### Screenshots

![GitHubPull](https://user-images.githubusercontent.com/71273796/160606520-358aad8d-3cd7-4fd9-9610-ca6a16aebf4a.png)

**Comment by sergiou87** [comment]
Thank you @BOFH-raf, but right now worktrees are not supported by GitHub Desktop. You can subscribe to https://github.com/desktop/desktop/issues/907 if you want to get notified whenever we start making progress on it. Sorry!
