### ISSUE TITLE
unable to add external editor

### ISSUE THREAD

**Issue by HMT2002** [desktop/desktop#14269]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

I have both Visual studio and android studio but the app only show one option is android studio. Is there anything I can do to fix this?

### Release version

Version 2.9.12 (x64)

### Operating system

Window

### Steps to reproduce the behavior

I was just install github desktop recently, then I cloned an android project back from web, then I open the project with android studio application, and then push with android too. Github later add android studio as external editor automatically. I tried to do the same thing with visual studio and visual project but it didn't work the same. Is there anything that I missed or anything that I can do? Please help!

### Screenshots

![image](https://user-images.githubusercontent.com/82308907/161252896-21165d8e-51d3-4d12-a290-cb912d35cde6.png)
Here the pic

**Comment by steveward** [comment]
Thanks for the issue @HMT2002 -- we're tracking Visual Studio support in https://github.com/desktop/desktop/issues/12946. Unfortunately there are some issues with integrating VS (see https://github.com/desktop/desktop/pull/13395#discussion_r757799482), but you can follow along for updates. We also have https://github.com/desktop/desktop/issues/7033 open which is tracking broader improvements to our editor integrations.

You can also use the `Open with Default Program` option from the file context menu to open files with the default system application. I hope that's helpful! I'm going to close this out.
