### ISSUE TITLE
GitHub Desktop screen is frozen

### ISSUE THREAD

**Issue by KTuccio** [desktop/desktop#14264]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

I was trying to push a request and now my screen is frozen and I am unable to do anything else. 

### Release version

Version 2.9.12 (x64)

### Operating system

Windows 10

**Comment by steveward** [comment]
@KTuccio thanks for the report. Have you tried opening Task Manager to force the app to quit? If your entire operating system is frozen then that may have been a system issue -- I would try restarting your machine to see if that helps.
