### ISSUE TITLE
A fork of Desktop for students

### ISSUE THREAD

**Issue by SpiritAxolotl** [desktop/desktop#14267]
### Search for existing feature requests

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the feature I am requesting.

### The feature request

Github Desktop except you can only make changes to repositories you created. 

### Proposed solution

Students will be able to work on their projects on Github without schools being worried about bypassing their firewalls and other security software. 

### Additional context

My school has extremely restrictive software on our computers, and recently they blocked github desktop because we could download software on there. I'm asking for this so that I can request for this build to be added to their list of approved/whitelisted applications for students to download.

**Comment by steveward** [comment]
Thanks for the issue @SpiritAxolotl. At this time we don't have any plans of making a custom version of GitHub Desktop. 

The most common issue we see is firewalls/proxies blocking the network access or antivirus software flagging the binaries that ship with the app. I would recommend asking your school to whitelist the application to work around these issues. Many organizations and schools have been able to do this in the past. If you have any specific questions about this please let me know. I'm going to close this out.
