### ISSUE TITLE
Wrong selected Repo Protocol 

### ISSUE THREAD

**Issue by jgwill** [desktop/desktop#14260]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

When opening with Desktop, the protocol (git) selected for the repo is not the one Desktop received (http).

### Release version

2.9.10 (x64)

### Operating system

win10

### Steps to reproduce the behavior

Select git prototol
open using desktop
observe : should be http

**Comment by steveward** [comment]
Thanks for the issue @jgwill. The `Open with GitHub Desktop` option uses HTTPS, and at this time it isn't possible to change this behavior. If you want to clone using SSH you can go to `File` > `Clone Repository` and enter the SSH URL of the repository. You'll need to have a working SSH key associated with your account. I hope that helps!
