### ISSUE TITLE
Desktop app doesn't remember full screen mode

### ISSUE THREAD

**Issue by gruedisueli** [desktop/desktop#14263]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

When I set Github Desktop to maximized mode, it properly fills the screen, above the Windows taskbar.

When I go to another program, and then return to the Github Desktop app, the program has reverted to some other "restored" window state that extends over the taskbar, hiding it, and necessitating me having to re-maximize the window.

This happens on both my monitors, one of which is 4k, the other 1080p. On the 4k screen, the app's window goes behind the taskbar, on the 1080p screen, it goes in front, but in both cases "maximized" is forgotten.

This issue only cropped up in the past month or two.

### Release version

2.9.12 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

See description.

**Comment by steveward** [comment]
Thanks for the report @gruedisueli. We've had a few multi-monitor issues come up (see https://github.com/desktop/desktop/issues/14017 for example) after updating the version of Electron we ship with GitHub Desktop.

**Comment by sergiou87** [comment]
Closing this as it will be finally fixed with the Electron upgrade to v19 in 3.0.8. See https://github.com/desktop/desktop/pull/15239
