### ISSUE TITLE
uthor identity unknown  *** Please tell me who you are.  Run    git config --global user.email "you@example.com"   git config --global user.name "Your Name"  to set your account's default identity. Omit --global to set the identity only in this repository.  fatal: unable to auto-detect email address (got 'hp@DESKTOP-6UALG5U.(none)')

### ISSUE THREAD

**Issue by Cynthia-Wanja-Dinah** [desktop/desktop#14271]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

uthor identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'hp@DESKTOP-6UALG5U.(none)')

### Release version

cersion 2.9.12

### Operating system

windows 10

### Screenshots

uthor identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'hp@DESKTOP-6UALG5U.(none)')

### Additional context

no other context

**Comment by steveward** [comment]
@Cynthia-Wanja-Dinah thanks for the issue.  It looks like your name and email are not set correctly in your .gitconfig file. Can you go to the file menu in GitHub Desktop and select `File` > `Options` > `Git` and enter your name and email?

That should get things working for you again. Let me know if you have any further issues.

**Comment by thisismanikandan** [comment]
Are you getting for Jenkins? If so, to solve this, please configure the username and user-email in Jenkins GIT Plugin. The steps are listed below:

1. Login Jenkins and Click "Manage Jenkins".
2. Click "System" option.
3. Search for Git Plugin
4. Enter the Name and Email for Git user.name and user.email

**Comment by Odiaga** [comment]
Running the following code as highlighted in the error message should solve the problem. 
Always take note of the recommendations highlighted in the error message.

**git config --global user.email "[you@example.com](mailto:you@example.com)"
git config --global user.name "Your Name**

**Comment by Firewolf786YT** [comment]
> Running the following code as highlighted in the error message should solve the problem. Always take note of the recommendations highlighted in the error message.
> 
> **git config --global user.email "[you@example.com](mailto:you@example.com)" git config --global user.name "Your Name**

The real question is what to do when you try and run this, but it doesn't work

**Comment by 1shubham0** [comment]
git config --global user.email "[you@example.com])"
git config --global user.name "Your Name"

run this cmd give your github email and github username it is working

**Comment by ademguleer** [comment]
I tried them as you said but I get the same error again.

**Comment by kush34** [comment]
> I tried them as you said but I get the same error again.

i was having same problem just a space btn user.email and your mail address 

also do same  with user.name and your "username"

hope it helps

**Comment by minnizzo** [comment]
> > I tried them as you said but I get the same error again.
> 
> i was having same problem just a space btn user.email and your mail address
> 
> also do same with user.name and your "username"
> 
> hope it helps

i tried this but i keep getting errors

**Comment by sasidhar13** [comment]
[Reference](https://stackoverflow.com/questions/11656761/git-please-tell-me-who-you-are-error)

1. git init
2. git config user.name "someone"
3. git config user.email "someone@someplace.com"
4. git add * / git add "filepath"
5. git commit -m "some init msg"
6. git branch -M main
7. git remote add origin https://github.com/someone/something.git
8. git push -u origin main
these steps in the exact order worked for me
