### ISSUE TITLE
Option for number of Recent Repos to show

### ISSUE THREAD

**Issue by andrewralon** [desktop/desktop#14280]
### Search for existing feature requests

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the feature I am requesting.

### The feature request

The "Recent" repos list is a good idea. It would be even better if users could increase the number of recent repos it shows.

As a user, I would like the number of repos shown under Recent to be a value I can increase in Options, so more recent repos will show in the Recent repos list.

Example: 
- The default Recent repos count seems to be 2 or 3 (depending on which org owns the repo). I would like to be able to change the Recent repos to show 10 repos that I use very often.

### Proposed solution

Create a "Recent Repos" field with an integer value. This would live in the Options window under the Advanced tab.
- Minimum value of Recent Repos is the default value used currently.
- Maximum value of Recent Repos is 30 (suggested). The maximum must be at least 10.

Details:
- Recent Repos should be an integer value the user can change.
- The default value should be the number of repos that Recent shows currently.
- Existing logic for determining which repos are recent does NOT need to change. This is to limit the scope of changes and speed up delivery time. There will likely be a few tweaks to this feature in the future, so the goal is to deliver the feature and see what needs to change after users evaluate it and provide feedback.

**Comment by steveward** [comment]
Thanks for the feedback @andrewralon. Would pinning repositories be a helpful solution here? We've gotten quite a bit of feedback about pinning/favoriting repositories in https://github.com/desktop/desktop/issues/8183.

**Comment by andrewralon** [comment]
Thanks for pointing me to that one @steveward - I agree they are similar. Pinning favorite repos is an even better idea. I'd be happy with either feature. Sadly, #8183 is closed and #14229 does not look too optimistic either.

**Comment by steveward** [comment]
Thanks for the update. Since pinning is often requested that may be something we consider again in the future, but at this time we don't have specific plans to make changes to the repository list. I'm going to close this out.
