### ISSUE TITLE
How to build Apple Silicon version on Apple Intel machine?

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#14299]
I found GitHub Desktop is support Apple Silicon, and I tried to build Apple SIlicon verison on Apple M1 machine, and it works well. I wonder whether it's feasible to build a Apple Silicon versionon Apple Intel machine for GitHub Desktop? since I don't have too many Apple M1 machines. If if's feasible, how to setup the build process? Thanks in advance.

**Comment by niik** [comment]
Hey @TerryChan, it is possible to build for arm processors on Intel machines. You'll need to set the `npm_config_arch` and `TARGET_ARCH` environment variables, see https://github.com/desktop/desktop/blob/development/.github/workflows/ci.yml.

I see you asking a lot of questions about the infrastructure of Desktop, may I ask what you're trying to accomplish?
