### ISSUE TITLE
Two accounts

### ISSUE THREAD

**Issue by guycart** [desktop/desktop#14293]
### Search for existing feature requests

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the feature I am requesting.

### The feature request

I have two github accounts, I had an existing personal one and was required to make another with my school email. When I want to work through my school github it does not allow me to open up github desktop through my school email. Nor does it allow me to sign out and re-sign in on github desktop to acquire my school accounts repositories.

### Proposed solution

Make it so you can just as easily sign into github desktop as you can on your website.

**Comment by steveward** [comment]
Thanks for the feedback @guycart. We are tracking support for multiple accounts in https://github.com/desktop/desktop/issues/3707. I'm going to add your feedback there.

**Comment by FANMixco** [comment]
Hi @steveward, are you really tracking the topic there? Wouldn't it be better just to say that it is not going to be implemented? Because it's long and people keep coming to the same location over and over again.
