### ISSUE TITLE
Repository settings does not include Fork behavior

### ISSUE THREAD

**Issue by mcorbin-ibm** [desktop/desktop#14292]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

The Repository Settings dialog does not include Fork Behavior settings.

### Release version

2.9.12 (x64)

### Operating system

macOS Big Sur 11.6.4

### Steps to reproduce the behavior

I have cloned a repo that I do not have write access to.  It does not prompt me to create a fork when cloning the repo.  When I go look at the Repository settings (Repository > Repository settings), I do not have "Fork behavior" as the [documentation](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/adding-and-cloning-repositories/cloning-and-forking-repositories-from-github-desktop#managing-fork-behavior) says I should.

**Comment by sergiou87** [comment]
Hi @mcorbin-ibm !

Those settings only appear if the repository you cloned is a fork. If you keep working on that repository, like trying to commit and push those commits, GitHub Desktop will prompt you to fork the repository.

Please, try that out and let me know if it works. But the app seems to work as expected, so I'm closing this issue. I'll be happy to reopen it if it happens to be a bug.

I hope that helps!

**Comment by SmartManoj** [comment]
The remote name should be "origin".
