### ISSUE TITLE
Slow on M1 pro

### ISSUE THREAD

**Issue by thagxt** [desktop/desktop#14290]
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

When I open the app on a brand new Apple M1 pro machine, the app is taking around 10 secs to load on screen. I've the latest version.

### Release version

Version 2.9.12 (x64)

### Operating system

macOS Monterey - 12.3 (21E230)

### Steps to reproduce the behavior

1. Open App
2. Wait

### Screenshots

https://user-images.githubusercontent.com/7128602/161978377-c0040f2b-e4e1-4be3-90e2-c5eeff5848fe.mov

**Comment by sergiou87** [comment]
It seems you're using the build for Intel CPUs. We also provide builds for Apple silicon: https://central.github.com/deployments/desktop/desktop/latest/darwin-arm64

Worst case, in the next auto-update it would switch to the arm64 build for your Apple silicon, but if you don't want to wait, there you have the download link 😄  (also available in https://desktop.github.com)
