### ISSUE TITLE
Changelist feature

### ISSUE THREAD

**Issue by saipavanbhanu** [desktop/desktop#14301]
It's not about stashing. 
Change list feature will help on below scenarios.
1. When we are working on different features at the same time, it would be good if we can have one commit for different features.
2. local changes only for dev environment which we don't want to include for every commit.

More about this feature in this link.
https://www.jetbrains.com/help/idea/managing-changelists.html#:~:text=If%20you're%20working%20with,automatically%20placed%20in%20this%20changelist.

_Originally posted by @saipavanbhanu in https://github.com/desktop/desktop/issues/9992#issuecomment-1091201791_

**Comment by steveward** [comment]
Thanks for the feedback @saipavanbhanu. If you're working on multiple features I would recommend using branching. At this time the specific feature you linked isn't something we would plan to implement in GitHub Desktop, so I'm going to close this out.
