### ISSUE TITLE
Unable to locate Git shows up every time terminal is opened

### ISSUE THREAD

**Issue by hgdagon** [desktop/desktop#14309]
### The problem

Github Desktop is unable to locate my Git installlation, so every time I open Terminal/PowerShell/CommandPrompt, it asks be to download. An option to not show it again would be appreciated.

### Release version

2.9.12 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Go to Repostory -> `Open in Windows Terminal`(/`Open in PowerShell`/`Open in Command Prompt`)

### Screenshots

![unable](https://user-images.githubusercontent.com/15173076/162428461-1432de9a-dc6d-4654-b189-84db79dccd6b.png)

### Additional context

I have Git installed in Msys2, which also gives me a Bash shell, and I can run it via Windows terminal.

**Comment by steveward** [comment]
@hgdagon thanks for the issue. Have you added `C:\msys64\usr\bin` to your PATH? That should get this working and stop the prompt. Let me know if you have any further issues.

**Comment by hgdagon** [comment]
@steveward I have not, since that introduces incompatibilities with certain libraries in that path for other applications.

**Comment by hgdagon** [comment]
@steveward Actually, that's interesting. if I sort out those incompatibilities, and add Msys2 to my path, will GH Desktop use my full Git installation (with my global settings and everything) or does it only care for `Git.exe`?

**Comment by steveward** [comment]
GitHub Desktop respects the global `.gitconfig` but uses its own bundled Git for operations.

**Comment by hgdagon** [comment]
OK. Well, how do I let GH Desktop know I have a `.gitconfig` in Msys2?
