### ISSUE TITLE
Pull Requests on Desktop incorrect (or deeply unintuitive)

### ISSUE THREAD

**Issue by matteoruscitti** [desktop/desktop#14312]
### The problem

I'm working on changes using atom. My repository is cloned locally without issue. It's a fork of a larger project that I don't have access to. I'm trying to create a pull request for _my project._ I have no idea why it keeps trying to make a pull request on the original. I'm in the correct repository and branch (new-meta-incorporated/pokemon-showdown) but it brings me to smogon/pokemon showdown. This has to be a bug, right? It's so clearly based on our forked project, and it even says that itself, but it's bringing it to the wrong one entirely. This is extremely frustrating, since editing code on the web version doesn't do this, ever... but I can't do the web version for these particular changes because it's a RAW file that I can't edit unless I use Atom. Please, tell me how to fix this.

### Release version

Version 2.9.12 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Open up new-meta-incorporated/pokemon-showdown/data/learnsets.ts in atom
2. do changes
3. Try to make a pull request to master using the changes brought from atom in desktop
4. Fail because it brings you to a repo that has nothing to do with anything at this point

### Screenshots

![correctrepo](https://user-images.githubusercontent.com/30511094/162585722-a49a66da-b754-47f1-a414-c2d359b43840.PNG)
![andthenthis](https://user-images.githubusercontent.com/30511094/162585742-c26c9bd6-b147-4a70-b3cd-722ca2d42d68.PNG)

Image 1: Showing that this is the correct repo I'm modifying
Image 2: What creating a pull request sends me to (for some reason)

### Additional context

I looked online for answers, and found none. Nobody's had quite this issue.

**Comment by niik** [comment]
Hey @matteoruscitti, thanks for reaching out. You can configure whether you want to use the repository to contribute to the parent repository (i.e the typical open source flow), or to your own fork, in the Repository settings for that repository.

<img width="626" alt="image" src="https://user-images.githubusercontent.com/634063/162710086-6a1aee02-3b50-4ea7-a3c4-746bc7b32c16.png">

In you case you should select the 'For my own purposes' option.

Hope that solves your issue!

**Comment by matteoruscitti** [comment]
@niik Negative, I tried that already
