### ISSUE TITLE
i can't see commit button 

### ISSUE THREAD

**Issue by shehza-d** [desktop/desktop#14317]
### The problem

im facing big problem as i can't see important buttons such as commit button even in full screen or in half screen
![image](https://user-images.githubusercontent.com/93990677/162639782-bba67f59-d24a-4722-b919-d1b5e2e3762a.png)
![image](https://user-images.githubusercontent.com/93990677/162639923-143484a5-7f1c-40ee-9ac3-5af5f70b6dd3.png)

### Release version

Version 2.9.12 (x64)

### Operating system

windows 10

### Screenshots

![image](https://user-images.githubusercontent.com/93990677/162639782-bba67f59-d24a-4722-b919-d1b5e2e3762a.png)

**Comment by steveward** [comment]
@shehza-d thanks for the report. This appears to be the same issue as https://github.com/desktop/desktop/issues/13940. Can you verify that you're running your interface scaled like [this user](https://github.com/desktop/desktop/issues/13940#issuecomment-1044226771)?

**Comment by steveward** [comment]
@shehza-d as we haven't heard back from you I am going to close this issue out. Let me know if we can be of further assistance.
