### ISSUE TITLE
Unexpected time travel when visiting Pull Requests tab

### ISSUE THREAD

**Issue by wojtekmaj** [desktop/desktop#14313]
### The problem

It looks like:
* PRs raised yesterday are marked as raised tomorrow
* PRs raised 2 days ago are marked as raised in 2 days
...and so on.

### Release version

2.9.12 (arm64)

### Operating system

macOS Monterey

### Steps to reproduce the behavior

1. Have Pull Requests raised for some time
2. Open Pull Requests tab
3. PROFIT! (see screenshot)

### Screenshots

![image](https://user-images.githubusercontent.com/5426427/162587786-714e1f9e-7c21-4fb9-8ff3-62574db78290.png)

**Comment by wojtekmaj** [comment]
Possibly related to #14149

**Comment by niik** [comment]
Hey @wojtekmaj, thanks for opening this. We identified, and fixed the breach of temporal laws in https://github.com/desktop/desktop/pull/14239. It will be part of the next production release. Sorry for the inconvenience!
