### ISSUE TITLE
Show the output of the hooks in GitHub Desktop.

### ISSUE THREAD

**Issue by yogeshwar-chaudhari-20** [desktop/desktop#14323]
### The feature request

I am currently checking type issues, test coverage and other trivial things in the pre-push hook. This is because these issues are identifiable in the local machine and once fixed provides high assurance that the build will be stable.

### Proposed solution

Step 1: Check if any hooks are configured for the given repo. (The files under .git/hooks/ without .sample extension)
Step 2: If present, show a console window in GitHub Desktop (Please refer the screen shot - Inline with Commit message but in No changes window - Bottom section)
Step 3: The output of the respective hook should be dumped here on respective action.

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/30533337/162863279-892871af-af9e-4c02-8062-bbdc3cc1b021.png">

**Comment by steveward** [comment]
I'm to close and add this to https://github.com/desktop/desktop/issues/15286 to help consolidate our issues.
