### ISSUE TITLE
GitHub Desktop seems to ignore git system config

### ISSUE THREAD

**Issue by david-sevcik** [desktop/desktop#14328]
### The problem

I set the `autocrlf` to `false` in git system config (`C:\Program Files\Git\etc\gitconfig`) but it seems to be ignored by GHD (GitHub Desktop).
When I checkout the repo, the line endings in source files are still converted.
The `autocrlf` in global neither in repository is not set.
Other tools doesn't do that, I used VS (Visual Studio 2022) and the line are correct after checkout in this app.
I also checked, that if the `autocrlf` is set to false in global config (`~/gitconfig`) the GHD behaves like VS, the line endings are not converted.

### Release version

2.9.12 (x64)

git version 2.35.1.windows.2

### Operating system

Windows 10 Enterprise (build 19044.1586)

### Steps to reproduce the behavior

1. Set the `autcrlf` in the git system config to `true` (only in the system config, not in the global [`~/gitconfig`] or in the repository config)
2. Checkout some existing repo containing text files with linux line endings
3. The line endings are converted to windows line endings (GitHub Desktop even doesn't report changed files, but other tools do [e.g. VS])

### Log files

```sh
$ git config --list --show-origin
file:C:/Program Files/Git/etc/gitconfig diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/etc/gitconfig filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/etc/gitconfig filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/etc/gitconfig filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/etc/gitconfig filter.lfs.required=true
file:C:/Program Files/Git/etc/gitconfig http.sslbackend=schannel
file:C:/Program Files/Git/etc/gitconfig core.autocrlf=false
file:C:/Program Files/Git/etc/gitconfig core.fscache=true
file:C:/Program Files/Git/etc/gitconfig core.symlinks=true
file:C:/Program Files/Git/etc/gitconfig core.usebuiltinfsmonitor=true
file:C:/Program Files/Git/etc/gitconfig core.editor="C:\\Program Files\\Notepad++\\notepad++.exe" -multiInst -notabbar -nosession -noPlugin
file:C:/Program Files/Git/etc/gitconfig pull.rebase=true
file:C:/Program Files/Git/etc/gitconfig credential.helper=manager-core
file:C:/Program Files/Git/etc/gitconfig credential.https://dev.azure.com.usehttppath=true
file:C:/Program Files/Git/etc/gitconfig init.defaultbranch=main
file:C:/Users/David.Sevcik/.gitconfig   user.name=David Ševčík
file:C:/Users/David.Sevcik/.gitconfig   user.email=***
file:C:/Users/David.Sevcik/.gitconfig   filter.lfs.process=git-lfs filter-process
file:C:/Users/David.Sevcik/.gitconfig   filter.lfs.required=true
file:C:/Users/David.Sevcik/.gitconfig   filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/David.Sevcik/.gitconfig   filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/David.Sevcik/.gitconfig   difftool.sourcetree.cmd='' "$LOCAL" "$REMOTE"
file:C:/Users/David.Sevcik/.gitconfig   mergetool.sourcetree.cmd=''
file:C:/Users/David.Sevcik/.gitconfig   mergetool.sourcetree.trustexitcode=true
file:C:/Users/David.Sevcik/.gitconfig   pull.rebase=true
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.symlinks=false
file:.git/config        core.ignorecase=true
file:.git/config        submodule.active=.
file:.git/config        remote.origin.url=****************************
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.master.remote=origin
file:.git/config        branch.master.merge=refs/heads/master
api#119
```

**Comment by steveward** [comment]
Thanks for the issue @david-sevcik. GitHub Desktop bundles its own version of Git, so the `system` config is referenced from the install location of the app. Is there a specific reason you are wanting this set in the system config instead of `.gitconfig`?

**Comment by david-sevcik** [comment]
Yes, because it's set from the git installer, where you can configure how it should behave globally. I supposed, that these settings should apply to all tools working with git. Is it possible to set GHD to use shared version of git?

**Comment by steveward** [comment]
@david-sevcik GitHub Desktop can only use its custom bundled version of Git -- sorry that I don't have better news.

**Comment by david-sevcik** [comment]
And why is that please?
