### ISSUE TITLE
Can't open visual studio on github

### ISSUE THREAD

**Issue by RalphJ4** [desktop/desktop#14325]
### The problem

I can't open visual studio code on github

### Release version

Version 2.9.12

### Operating system

Windows 10

### Screenshots

![image](https://user-images.githubusercontent.com/100404299/162914874-d199a6ea-7590-48ce-a5b2-69dd81048de7.png)

### Additional context

Error: spawn C:\Program Files\Java\jdk1.7.0_21\bin ENOENT
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at __node_internal_errnoException (node:internal/errors:594:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

Version: 2.9.12
OS: Windows 10.0.19044

**Comment by steveward** [comment]
Thanks for the report @RalphJ4. It looks like you're running into the same issue as https://github.com/desktop/desktop/issues/14129. You can see if [this solution](https://github.com/desktop/desktop/issues/14202#issuecomment-1072376656) gets things working for you. Let me know if that helps!

**Comment by RalphJ4** [comment]
> Thanks for the report @RalphJ4. It looks like you're running into the same issue as https://github.com/desktop/desktop/issues/14129. You can see if [this solution](https://github.com/desktop/desktop/issues/14202#issuecomment-1072376656) gets things working for you. Let me know if that helps!

I already fixed it. The 1 letter of the folder name is capital so i changed it to lower case and i delete the jdk in the path on environment and it works well

**Comment by steveward** [comment]
Glad to hear things are working again!
