### ISSUE TITLE
Default Branch Switching

### ISSUE THREAD

**Issue by zulkifelff** [desktop/desktop#14326]
### The problem

Upon updating the default branch
![image](https://user-images.githubusercontent.com/45070594/162916758-0bba8745-24e2-4e67-a8e1-f936bedb2617.png)
![DefaultNaming](https://user-images.githubusercontent.com/45070594/162916137-e8064e10-d2d4-451f-b854-5a5c91c9ac2c.jpg)

 of private repository , Default Branch name is not updated.

### Release version

Version 2.9.12 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Change Default Branch on Github
2. Open Github Desktop
3. Click "Branch"
4. Option "Update from" is showing name of previous default branch name

**Comment by steveward** [comment]
Thanks for the report @zulkifelff. We are tracking this in https://github.com/desktop/desktop/issues/14266 -- you can follow along there for updates.
