### ISSUE TITLE
Add support for Warp dot dev

### ISSUE THREAD

**Issue by vinayakkulkarni** [desktop/desktop#14329]
### The feature request

Since Warp.dev is now open for public, it'd be amazing if GitHub Desktop could support Warp as one of the options for Shell in the dropdown.

<img width="610" alt="Screenshot 2022-04-12 at 7 24 20 PM" src="https://user-images.githubusercontent.com/19776877/162978447-d6b80105-8cad-4a8a-8a64-3bb3bd551a8b.png">

### Proposed solution

- [ ] Update the shells here ? – https://github.com/desktop/desktop/blob/18238077aa1e4851e710cfa66587cd4fd597bacd/app/src/ui/preferences/integrations.tsx#L51-L59

**Comment by lhvy** [comment]
I have started working on this in 9138385. For anyone interested, there is a guide for adding terminals [here](https://github.com/desktop/desktop/blob/development/docs/technical/shell-integration.md).

Only problem is that currently Warp does not support launching to a specific directory. I have left a comment on their issue tracking page and am double checking this is the case on their discord. If anyone knows a way to launch Warp to a specific path, let me know and I'll promptly finish up my branch and make a PR!

**Comment by alokedesai** [comment]
Hey @lhvy, thanks for getting this started! We actually support opening warp at a specific directory as of two weeks ago :) You should be unblocked to add this integration. If you don't have bandwidth let me know, and someone from the Warp team could also take it over!

**Comment by lhvy** [comment]
Thanks for the reminder @alokedesai! I'm working on it again now, hopefully should be pretty quick.

**Comment by lhvy** [comment]
@alokedesai I've finished this feature in the linked PR, although is is worth noting a bug with Warp's restored sessions taking priority over a directory passed in as an argument. I've opened an issue about it here: warpdotdev/Warp#1621.

**Comment by shehza-d** [comment]
How can i enable this for Linux Ubuntu 22?

**Comment by tristanpoland** [comment]
Is there anything in particular we need to do to make the option show up I have both installed on Windows and GitHub Desktop seemingly doesn't detect Warp as an option. I also tried pointing to the executable but as expected Warp doesn't accept that argument formatting

<img width="467" height="497" alt="Image" src="https://github.com/user-attachments/assets/c9adf0cd-9a07-4e5f-88b7-8f32603a1038" />
