### ISSUE TITLE
No syntax highlighting for multi-line TOML strings

### ISSUE THREAD

**Issue by GeeTransit** [desktop/desktop#14333]
### The problem

Multi-line TOML strings aren't coloured in the diff - only the first line does. No error message appear in the console.

### Release version

2.9.12

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Create and save a new TOML file with a multi-line string.
2. Observe the absence of colour on the string :(

### Screenshots

![image](https://user-images.githubusercontent.com/27315593/163096619-8d8a81c5-5014-4aa5-ba1e-cde71771e5db.png)
![image](https://user-images.githubusercontent.com/27315593/163097694-cc2bb3ce-1f64-472d-92fb-d7579c2766a7.png)

**Comment by steveward** [comment]
Thanks for the report @GeeTransit. GitHub Desktop uses [CodeMirror](https://github.com/codemirror/CodeMirror/i) for syntax highlighting -- you can open an issue there about this and if a fix gets merged we'll eventually update our version that ships with the app.

**Comment by GeeTransit** [comment]
I can't seem to reproduce it on CodeMirror's [interactive TOML mode site](https://codemirror.net/mode/toml/index.html). I've opened https://github.com/codemirror/CodeMirror/issues/6909 anyways.

**Comment by steveward** [comment]
It's possible something fixed it upstream and updating our dependency will resolve the issue in GitHub Desktop.

**Comment by GeeTransit** [comment]
A large majority of the TOML mode [hasn't changed for 9 years](https://github.com/codemirror/CodeMirror/blame/master/mode/toml/toml.js) though so I doubt it'll help (though it's worth a shot).

I have noticed that each line is processed separately (assuming that's what [this line](https://github.com/desktop/desktop/blob/029fa13207da058652fb8b55c20a15bd6a2684c8/app/src/highlighter/index.ts#L631) does), though I'm not sure if it could change how code is highlighted.

**Comment by Jamal-Randolp** [comment]
Awesome! Great job! Thank you!!!👏👏👏✊💪🇺🇸🌎🌎🙏
