### ISSUE TITLE
App sometimes can't find repository on launch

### ISSUE THREAD

**Issue by webmasterlv** [desktop/desktop#14338]
### The problem

Github Desktop randomly is unable to locate repository on a mounted Samba share. Even though clicking "Locate..." dialog opens on the exact same folder it cannot find. "Check again" does nothing. The problem goes away automatically in some time (about 10 minutes) without doing nothing. The path on question is on network drive, mounted as Y:. Network drive is a Samba share running on Linux Ubuntu 20.04

### Release version

2.9.13 (x64)

### Operating system

Windows 11

### Log files

There is something related to this in the log:

```
2022-04-13T10:37:09.122Z - info: [ui] [AppStore] loading 8 repositories from store
2022-04-13T10:37:09.450Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//deniss.local/Data/path/to/repository' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //deniss.local/Data/path/to/repository

```

### Screenshots

![2022-04-13_13-38-14](https://user-images.githubusercontent.com/2886170/163163692-5411ecc5-2b6e-4845-8b37-30ddc6d4d0bc.png)

**Comment by niik** [comment]
Hi @webmasterlv, thanks for reaching out. We're tracking this in #14336. The Git project shipped a security release yesterday to protect against a vulnerability. That fix requires the repository to be owner by the current user which your samba directory isn't. i'm going to close this in favor of #14336 but running `git config --global --add safe.directory //deniss.local/Data/path/to/repository` should mark the repository as safe and let you continue on.

**Comment by stakach** [comment]
thanks for that @niik perfect timing was just about to +1 this
