### ISSUE TITLE
If we fast click on one History Branch to other

### ISSUE THREAD

**Issue by masakbar** [desktop/desktop#14334]
### The problem

If we fast click on History Branch let's say from "foo" to "bar" while foo still loading, we will see "foo" log description on "bar" branch.

### Release version

2.9.12 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

If we fast click on History Branch let's say from "foo" to "bar" while foo still loading, we will see "foo" log description on "bar" branch.

### Screenshots

![Screenshot_14](https://user-images.githubusercontent.com/97865020/163112193-876aced7-e54b-4708-8139-940f8e2ee44a.png)

**Comment by steveward** [comment]
Thanks for reporting this @muhamadrizkiakbar. This looks like the same issue as https://github.com/desktop/desktop/issues/13633, so I am going to close this out.
