### ISSUE TITLE
Version 2.9.13 doesn't recognize my git repositories.

### ISSUE THREAD

**Issue by bswimley** [desktop/desktop#14349]
### The problem

I installed the latest github desktop update to 2.9.13.  Afterwards, github desktop did not recognize any of my local git repositories. I downgraded to version 2.9.10 (x64) and deleted the contents of the %appdata%\github desktop folder and this version of github desktop recognizes my repositories just fine.

### Release version

2.9.13

### Operating system

Windows 10

**Comment by sauravbv** [comment]
Experiencing the same issue...

It recognizes only some repos

Release version
2.9.13

Operating system
Windows 11

**Comment by tidy-dev** [comment]
Duplicate of #14336  - Please follow along there -> some appear to be able to resolve it with the a git command.
