### ISSUE TITLE
Can't find repository in local (Loop error)

### ISSUE THREAD

**Issue by Maxime66410** [desktop/desktop#14348]
### The problem

GitHub Desktop can't find local files.
The files are however existing, it detects for a micro second that everything is in order but immediately it tells me that there are no repositories in this folder.

### Release version

Version 2.9.13 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

- Go download any Repository.
- Put in **"C:\xampp\htdocs"**
- Wait finish to download.
- And see the error.

### Log files

[2022-04-13.desktop.production.log](https://github.com/desktop/desktop/files/8482444/2022-04-13.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/37190601/163208944-6f82fdf1-29b7-4863-8f3a-ffe5cca026ff.png)

![image](https://user-images.githubusercontent.com/37190601/163209036-d1714694-67b0-4faf-aa1e-825da26e2410.png)

### Additional context

I summarize, overnight I can no longer use github in a specific directory that puts important to work faster.

I can no longer have a project in this specific directory.

**C:\xampp\htdocs**

However on other files it works.

**Comment by niik** [comment]
Hey, thanks for reaching out! This issue is described in #14336 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date with any development happening in that area.

**Comment by Maxime66410** [comment]
> Hey, thanks for reaching out! This issue is described in #14336 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date with any development happening in that area.

Thanks you so much !

Fix : 
`git config --global --add safe.directory YOUR DIRECTORY`
