### ISSUE TITLE
Can't locate local repo on WSL 

### ISSUE THREAD

**Issue by adamlap** [desktop/desktop#14346]
### The problem

After updating GitHub Desktop can no longer locate the folder inside WSL (\\wsl$\Ubuntu\home\...)
I have tried to relocate it but it doesn't fix the issue.

### Release version

2.9.13 (x64)

### Operating system

Windows Home 64 bit

### Steps to reproduce the behavior

1. Open GitHub Desktop with a repo pointing to a WSL location.

**Comment by niik** [comment]
Duplicate of #14336. Please follow along there for updates
