### ISSUE TITLE
Github not understanding that gitlab projects are git repos

### ISSUE THREAD

**Issue by JohnCliffe** [desktop/desktop#14347]
### The problem

Cloning:
![Capture3](https://user-images.githubusercontent.com/8880765/163207500-87a27c3d-0941-4f80-b587-ce63066c5bb5.PNG)
Still cloned: 
![Capture1](https://user-images.githubusercontent.com/8880765/163207502-2c9f7cf2-05c2-4b4b-a22c-4b850a62061a.PNG)
Can't even add existing repo:
![Capture2](https://user-images.githubusercontent.com/8880765/163207507-4bbfdaa0-207a-45db-91e2-c0326c90bb8d.PNG)

Github desktop doesn't seem to be picking up my gitlab repos and when cloning them there is an error at the end of it even though it does seem to clone them properly. If I try and add existing repository after cloning it it will also fail with the 3rd image error.

### Release version

2.9.13

### Operating system

Windows 10

### Steps to reproduce the behavior

Try to clone gitlab repo. Doesn't let you.

**Comment by niik** [comment]
Hey, thanks for reaching out! This issue is described in #14336 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date with any development happening in that area.
