### ISSUE TITLE
Version 2.9.13 has broke on wsl2

### ISSUE THREAD

**Issue by jamieb2b** [desktop/desktop#14342]
### The problem

Using Ubuntu on wsl2, when cloning a repo it will clone and then say the folder is not a git repo

### Release version

Version 2.9.13

### Operating system

windows 10

### Steps to reproduce the behavior

set up wsl2 and ubuntu, then clone a repo to the home folder.

**Comment by niik** [comment]
Duplicate of #14336, please subscribe to that issue to follow along!
