### ISSUE TITLE
'Can't find <repository>'

### ISSUE THREAD

**Issue by Lukas-Buricin** [desktop/desktop#14340]
### The problem

After updating to the latest version 2.9.13 (x64), no repositories are visible to GitHub Desktop. It literally worked 2 seconds before the update and all repositories were showing correctly.

After the update I see 'Can't find XYZ' for any repository I choose.

### Release version

2.9.13 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1) Click "What's new" when the update message appears
2) On the dialog with list of fixes etc. just click "Exit and Install"
3) After the app re-appearing no repositories can be found despite them being there all the time. It keeps saying "It was last seen at ... Check again" but clicking "Check again" does nothing, neither does restarting the app.

**Comment by charescape** [comment]
#14336

**Comment by tidy-dev** [comment]
Hi @Lukas-Buricin, thanks for reaching out. We're tracking this in https://github.com/desktop/desktop/issues/14336. The Git project shipped a security release yesterday to protect against a vulnerability. That fix requires the repository to be owner by the current user. I'm going to close this in favor of https://github.com/desktop/desktop/issues/14336 but running git config --global --add safe.directory {directory name} should mark the repository as safe and let you continue on.
