### ISSUE TITLE
Can't find local repos after update to 2.9.13 

### ISSUE THREAD

**Issue by djderex** [desktop/desktop#14341]
### The problem

After today's update to version 2.9.13 (x64) , i get an error message on all local repositories "Can't find local repos"

### Release version

2.9.13

### Operating system

Windows 11 PRO

### Steps to reproduce the behavior

Click on any of the local repos., get error message that can't be found. The files are there, intact.

### Screenshots

![Screenshot 2022-04-13 123024](https://user-images.githubusercontent.com/16526135/163171004-53921749-7f32-4e4d-ba03-e44d9e0bac1b.png)

**Comment by charescape** [comment]
#14336

**Comment by tidy-dev** [comment]
Hi @djderex, thanks for reaching out. We're tracking this in https://github.com/desktop/desktop/issues/14336. The Git project shipped a security release yesterday to protect against a vulnerability. That fix requires the directory of the repository to be owned by the current user. I'm going to close this in favor of https://github.com/desktop/desktop/issues/14336 but running git config --global --add safe.directory {directory name} should mark the repository as safe and let you continue on.
