### ISSUE TITLE
GH Desktop 2.9.13 (x64) unable to find existing repo

### ISSUE THREAD

**Issue by danglingptr0x0** [desktop/desktop#14350]
### The problem

The desktop client lost track of an existing repo immediately after update today.
Running version `2.9.13 (x64)`

`git` has no problem working with the repo from the shell, but the GH client can't seem to grasp the fact that the repo exists and is valid and keeps reporting that it couldn't be found

Tried removing and re-adding, but now it reports that there's no repo in the given directory:
![image](https://user-images.githubusercontent.com/51794014/163220951-b13f2c18-3373-4ea5-9bf8-0ee79919f3d7.png)

Somehow, however, other repos work after switching to them in the repo dropdown.

### Release version

2.9.13 (x64)

### Operating system

Win10Pro

### Steps to reproduce the behavior

1. Update to `2.9.13 (x64)`
2. Restart the client as prompted
3. Observe the client being unable to work with the repo

### Log files

```
2022-04-13T14:37:16.012Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('D:/[redacted]' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory 'D:/[redacted]'

2022-04-13T15:29:55.140Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('D:/[redacted]' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory 'D:/[redacted]'
```

**Comment by danglingptr0x0** [comment]
> Somehow, however, other repos work after switching to them in the repo dropdown.

Just found out that repos owned by my account do indeed work as intended, it's just org repos that are inaccessible

**Comment by danglingptr0x0** [comment]
Updated to `git version 2.35.2.windows.1` and now not even Git can work with the repo. I've just read about the vuln and that's why I updated. Will try explicitly declaring the repo dir as safe

**Comment by niik** [comment]
Hey, thanks for reaching out! This issue is described in #14336 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date with any development happening in that area.

**Comment by danglingptr0x0** [comment]
> Updated to `git version 2.35.2.windows.1` and now not even Git can work with the repo. I've just read about the vuln and that's why I updated. Will try explicitly declaring the repo dir as safe

Tried the workaround, git reported `0` as exit code, however the error still gets reported:

```
fatal: unsafe repository ('D:/[redacted]' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory 'D:/[redacted]'
```
