### ISSUE TITLE
Desktop for Windows on my virtual windows instance can no longer see the repositories on my Mac (physical machine)

### ISSUE THREAD

**Issue by jwmccandless** [desktop/desktop#14351]
### The problem

After the update this morning to version 2.9.13, all of my repositories are inaccessible. I am using a virtual instance of Windows and keep the repositories on my Mac.

I have had no problems with this setup until this update.

### Release version

2.9.13

### Operating system

Windows 10

### Steps to reproduce the behavior

Trying to access any repository stored on my Mac.

**Comment by niik** [comment]
Hey, thanks for reaching out! This issue is described in #14336 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date with any development happening in that area.
