### ISSUE TITLE
Can't find repos after update

### ISSUE THREAD

**Issue by jtrelfa** [desktop/desktop#14353]
### The problem

With the most recent update, the program can no longer locate or read any of my repositories

### Release version

2.9.13 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

Update the app, try to open a local repository

### Log files

[2022-04-13.desktop.production.log](https://github.com/desktop/desktop/files/8483301/2022-04-13.desktop.production.log)

**Comment by helmiau** [comment]
same as mine

**Comment by zedd3v** [comment]
here aswell, my repos are on wsl2

when i reload them it shows for a milisecond then goes back to the "cant find package" page

also running windows 11

**Comment by niik** [comment]
Hey, thanks for reaching out! This issues is described in #14336 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date
