### ISSUE TITLE
Not able to push the code to repository

### ISSUE THREAD

**Issue by AB013BX** [desktop/desktop#14359]
### The problem

Hi Team,

I am not able to push the code to repository from github IDE and not from terminal. even i have write access on repository

On march 29 2022 able to push the code to repository.

Please find the attached log file, screen shot and other details

Please help me to resolve the issue.

Regards,
Vijay

### Release version

version 2.9.12

### Operating system

Windows 10

### Log files

[2022-04-14.desktop.production.log](https://github.com/desktop/desktop/files/8486759/2022-04-14.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/72545276/163326300-3f137374-b911-44cd-854f-840cdeff2eba.png)

### Additional context

![image](https://user-images.githubusercontent.com/72545276/163326415-964ea206-6272-4f43-90da-2ed5e8a288ae.png)

**Comment by niik** [comment]
@AB013BX I'm not seeing any error in either the screenshots or the log file. What happens when you click the "Push origin" button? Please include screenshots and/or an updated log file from a day when you experienced the problem

**Comment by steveward** [comment]
@AB013BX as we haven't heard back from you I am going to close this issue out. If you're still having issues let us know and we can investigate further.
