### ISSUE TITLE
unable to read local repository after upgrading 2.9.13

### ISSUE THREAD

**Issue by jayarnold** [desktop/desktop#14355]
### The problem

I have a repository that I use the git command line to sync, but use GitHub Desktop for Windows to review changes and create commits.  GitHub desktop is unable to read the local repository since upgrading to 2.9.13.  Version 2.9.12 worked correctly.

When I try to re-add the local repository, GitHub desktop displays a message that "This directory does not appear to be a Git repository."  

### Release version

2.9.13

### Operating system

Windows 10

### Steps to reproduce the behavior

From a system with a local repository,
1. Respond to message "An updated version of GitHub Desktop is available and will be installed at the next launch. See what's new or restart GitHub Desktop"
2. After restarting GitHub Desktop, a message appears that the current repository is local invalid and offers to delete.  
3. Delete the repository
4. Attempt to re-add the local repository

Result: 
GitHub Desktop will not add the repository, displaying the message "This directory does not appear to be a Git repository."  

### Log files

[2022-04-12.desktop.production.log](https://github.com/desktop/desktop/files/8484253/2022-04-12.desktop.production.log)
[2022-04-13.desktop.production.log](https://github.com/desktop/desktop/files/8484254/2022-04-13.desktop.production.log)

### Additional context

.git/config file:
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
[remote "origin"]
	url = ssh://codeserver.dev.2ec67223-d50c-42e1-ba61-de7333af7fde@codeserver.dev.2ec67223-d50c-42e1-ba61-de7333af7fde.drush.in:2222/~/repository.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[branch "jay"]
	remote = origin
	merge = refs/heads/jay
[pull]
	rebase = false
[branch "shevonne"]
	remote = origin
	merge = refs/heads/shevonne
[branch "2022apr"]
	remote = origin
	merge = refs/heads/2022apr

**Comment by edoartworks** [comment]
I have this issue as well!

**Comment by niik** [comment]
See #14336
