### ISSUE TITLE
Vigilant mode verification doesn't work on github desktop

### ISSUE THREAD

**Issue by Kris-Zhang-122507** [desktop/desktop#14357]
### The problem

I am trying to verify my signature for commiting to my repos. It works fine in VScode but doesn't on github desktop. I am pretty sure I am signed in correctly email. I am not sure what is happening. I did work a while ago though.

### Release version

2.9.14 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Make sure you have vigilant mode on and a verified gpg key

1. Make changes on Text Editor.
2. Go to Github Desktop
3. Commit
4. Go to commits in github repo
5. unverified (supposed to be verified)

### Screenshots

<img width="955" alt="image" src="https://user-images.githubusercontent.com/83886868/163305235-ef9b34c1-02b7-40e6-a9e0-acb854cc1a33.png">

Below is the one I did in vscode

The One above is the one done in Github Desktop.

**Comment by steveward** [comment]
@Kris-Zhang-122507 GPG signing should work in GitHub Desktop even though we don't officially support it --[ these are the steps](https://gist.github.com/xavierfoucrier/c156027fcc6ae23bcee1204199f177da) I usually point users to who are looking to get it working. Can you check to see if everything is configured correctly?

**Comment by steveward** [comment]
@Kris-Zhang-122507 I recently tested out GPG signing and it worked without issue. If you're still having problems let us know. I'm going to close this out.
