### ISSUE TITLE
Must detect ownership issues and offer to resolve them

### ISSUE THREAD

**Issue by KMZeiseBTAC** [desktop/desktop#14352]
@TalicZealot For you it would appear the vulnerability protection is working as intended. Could you make sure that the `D:/Programming/Khaos-Bot-Script` folder is owned by your user or if that's not an option you can add it as an exception by running `git config --global --add safe.directory "D:/Programming/Khaos-Bot-Script"`

_Originally posted by @niik in https://github.com/desktop/desktop/issues/14336#issuecomment-1097847383_

GitHub Desktop can detect such issues, should provide a correct diagnostic, and it should offer to resolve them for us

**Comment by niik** [comment]
Hey @KMZeiseBTAC, we are working on that in #14344 which we're hoping to ship to beta real soon
