### ISSUE TITLE
Desktop blackout from full screen toggle

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1436]
Desktop is blacked out on Windows from toggling full screen twice. 

Reproduce:
- Toggle full screen mode
- Press Alt, to pull up menu
- Select Toggle full screen again

Results in black screen where Desktop is inoperable and unrecoverable. No logs found.

<img width="1202" alt="screen shot 2017-05-11 at 2 07 18 pm" src="https://cloud.githubusercontent.com/assets/14828183/25964664/a87546d8-3653-11e7-846b-cb2addef6aa5.png">

v0.0.39, Windows 10 via VM

**Comment by niik** [comment]
Reopening this as we're getting more reports

**Comment by niik** [comment]
Ehh, issue overload it looks like we're tracking this in #1502, gonna move the discussion over there instead
