### ISSUE TITLE
Can't commit to main - "cannot add to the index - missing --add option?"

### ISSUE THREAD

**Issue by saja2196** [desktop/desktop#14379]
**Describe the issue**
I'm unable to "commit to main" via Github Desktop. I created a folder A (called CO) on the github website, cloned that, I copy pasted folder B (called Banner_Scripts) into folder A 

**System environment**
OS: Windows 10 Education

**Error**
`error: invalid path 'Banner_Scripts/'
error: Banner_Scripts/: cannot add to the index - missing --add option?
fatal: Unable to process path Banner_Scripts/` 

**Additional context**
![image](https://user-images.githubusercontent.com/102328670/163452557-b7198c22-876f-43fb-b8a4-625e2a056fee.png)

**Comment by steveward** [comment]
@saja2196 thanks for the report. Is there anything unusual about where this repository is stored? Is it on a standard system drive or is it in a network drive? Is it possibly open in another application like Visual Studio?

**Comment by saja2196** [comment]
> @saja2196 thanks for the report. Is there anything unusual about where this repository is stored? Is it on a standard system drive or is it in a network drive? Is it possibly open in another application like Visual Studio?

Thanks for your message. The repository is on my desktop but it appears that my desktop is in my organization's OneDrive. [](url
![419github](https://user-images.githubusercontent.com/102328670/164021419-914bf92d-9930-43eb-89dd-9f31a196992e.png)
)

**Comment by saja2196** [comment]
bump

**Comment by steveward** [comment]
@saja2196 is it possible you have nested Git repositories? Can you check in your 'Banner_Scripts' directory to see if there is a hidden `.git` directory?

**Comment by saja2196** [comment]
> @saja2196 is it possible you have nested Git repositories? Can you check in your 'Banner_Scripts' directory to see if there is a hidden `.git` directory?

there isn't
