### ISSUE TITLE
Save commit message in between restarts

### ISSUE THREAD

**Issue by JeremyEastham** [desktop/desktop#14382]
### The feature request

Currently, the commit message title, summary, co-contributors, and selected files are lost when GitHub Desktop updates, the system restarts, or GitHub Desktop is restarted. This can be especially annoying when composing a long description for a commit that is not completely finalized.

#### Workarounds
- Commit with the message and description and then amend the last commit when more changes are made
- Save the commit message and description to a text document
- Type them out again

All of these options are very inconvenient when this functionality could be built-in to GitHub Desktop.

### Proposed solution

I propose that the commit summary, description, co-authors, and selected changed files are saved to a temporary file until the changes are committed (persisted between application and system restarts). This will speed up users' workflows by not forcing them to complete these actions again if they are interrupted. These settings should be saved per-repository, but should be cleared (or saved separately) when switching branches.

**Comment by steveward** [comment]
Thanks for the request @JeremyEastham. I'm going to bump up https://github.com/desktop/desktop/issues/3664 with this feedback, since that's a pre-existing issue.
