### ISSUE TITLE
Why can't I have visual studio as the external editor?

### ISSUE THREAD

**Issue by BradAda** [desktop/desktop#14385]
### The feature request

Be able to have visual studio as an external editor

### Proposed solution

As visual studio is the premiere IDE I honestly don't see why it hasn't being added yet.

**Comment by steveward** [comment]
Thanks for the issue @BradAda -- we're tracking Visual Studio support in https://github.com/desktop/desktop/issues/12946. Unfortunately there are some issues with integrating VS (see https://github.com/desktop/desktop/pull/13395#discussion_r757799482), but you can follow along for updates. We also have https://github.com/desktop/desktop/issues/7033 open which is tracking broader improvements to our editor integrations.

You can also use the `Open with Default Program` option from the file context menu to open files with the default system application. I hope that's helpful! I'm going to close this out.

**Comment by BradAda** [comment]
Hi sorry I forgot to say I'm on Mac so I don't think the Open with default Program will work.

**Comment by steveward** [comment]
@BradAda that option is available on macOS as well.

**Comment by coezbay** [comment]
@steveward That option does just show up in the changes area of GitHub Desktop. So maybe it would be nice to tell where to find it when you're saying that it is available in MacOS as well.

**Comment by steveward** [comment]
@coezbay here's a screenshot of where you can find it from the context menu:

<img width="1060" alt="Screen Shot 2022-11-10 at 2 32 57 PM" src="https://user-images.githubusercontent.com/721500/201189270-50b28f00-275b-413c-9392-ac9d079d5a38.png">

**Comment by coezbay** [comment]
> @coezbay here's a screenshot of where you can find it from the context menu:
> 
> <img alt="Screen Shot 2022-11-10 at 2 32 57 PM" width="1060" src="https://user-images.githubusercontent.com/721500/201189270-50b28f00-275b-413c-9392-ac9d079d5a38.png">

Exactly. In the changes area... Some people may not know it. Especially when they're just getting into the material ;)
