### ISSUE TITLE
"Trust Repository" button has no effect

### ISSUE THREAD

**Issue by mapwiz** [desktop/desktop#14386]
### The problem

GitHub Desktop prompts me about a potentially unsafe repository folder for the last repository used. However the “Trust Repository” button has no effect -- literally, nothing happens when you click it.   

The problem may ultimately be rooted in a problem with Git itself but the behavior of the “Trust Repository” button needs to be discussed here.

### Release version

2.9.14

### Operating system

Windows 10 21H2

### Steps to reproduce the behavior

1. Open GitHub Desktop.   You are prompted that the repository is unsafe.  
2. Click on the Trust Repository button.  The button has the appearance of being clicked but nothing happens.

### Additional context

This is related to the Visual Studio issue https://developercommunity.visualstudio.com/t/Git-Error-after-1714-update/10012565

I recently updated VS to 17.1.4. After experiencing the issue above, I also updated Git to 2.35.3-64, and GitHub Desktop to 2.9.14. 

The repository a clone, lives in a folder owned by a security group my account is in. It’s in a DFS shared folder on a NAS device.

I added the repository path as a safe.directory via the git command line.   
git config -l shows the path to the repository //company/dfs/projects/IT/repos (also the mapped drive letter version P:\IT\repos) in the list of safe directories.

**Comment by tidy-dev** [comment]
Issue is being tracked #14336. ([More Info](https://github.com/desktop/desktop/issues/14336#issuecomment-1098294609)). Currently, a fix for it is on our [Beta channel.](https://desktop.github.com/beta/)
