### ISSUE TITLE
Cannot add any existing repository

### ISSUE THREAD

**Issue by MilesFarber** [desktop/desktop#14396]
### The problem

Adding an existing repository from your hard drive causes this to happen. Clicking on "add an exception for this directory" does absolutely nothing.
![image](https://user-images.githubusercontent.com/24918282/163708620-204eff6b-b416-4b3f-830a-75d5609d42a2.png)

### Release version

Version 2.9.14 (x64)

### Operating system

Windows 10 21H2

### Steps to reproduce the behavior

1. Click on "add an existing repository from your hard drive"
2. Try to add any repository

### Log files

[2022-04-17.desktop.production.log](https://github.com/desktop/desktop/files/8501289/2022-04-17.desktop.production.log)

### Additional context

I'm using a network shared drive on SAMBA.

**Comment by MilesFarber** [comment]
Doing `git config --global --add safe.directory //server/z/GitHub/Windows10SuperCharger` does nothing.

**Comment by tsvetilian-ty** [comment]
👋 @FlarosOverfield download the latest version from the [beta channel](https://desktop.github.com/beta/). Your issue is related to #14336

**Comment by Squadz** [comment]
I had the same issue, downloading the Beta version fixed it.
Thanks Tsvetilian !
