### ISSUE TITLE
JetBrains WebStorm IDE support to external editors

### ISSUE THREAD

**Issue by erseversahin** [desktop/desktop#14398]
### The feature request

By default GitHub Desktop have VS Code, Sublime Text, Notepad ++ support,  also some JetBrains IDEs(like PhpStorm, PyCharm) have now been added. But The JetBrains WebStorm IDE is still not supported.

![image](https://user-images.githubusercontent.com/63604193/163333775-101feaba-80dc-4f7f-88d5-163a2c9345a3.png)

![image](https://user-images.githubusercontent.com/63604193/163333833-479f2a12-1a03-4fd0-bc3b-593c7ae6f32f.png)

### Proposed solution

Please share how this will it benefit Desktop and its users?

### Additional context

Please include any other context, like screenshots or mockups, if applicable.

**Comment by say25** [comment]
WebStorm should be supported https://github.com/desktop/desktop/blob/8b0871ad201e443381ee5de40b6a8be7b6e4895b/app/src/lib/editors/win32.ts#L301

**Comment by tsvetilian-ty** [comment]
Hi @erseversahin, I can confirm what @say25 said, WebStorm is supported. You can try to restart GitHub Desktop, so it tries again to detect the editors. 

![image](https://user-images.githubusercontent.com/9341546/163723185-2a77d005-d26a-4276-b634-5e8094dd38bc.png)
![image](https://user-images.githubusercontent.com/9341546/163723197-7a08934e-ca42-4763-9899-1d13c290c1b0.png)

**Comment by erseversahin** [comment]
> WebStorm should be supported
> 
> https://github.com/desktop/desktop/blob/8b0871ad201e443381ee5de40b6a8be7b6e4895b/app/src/lib/editors/win32.ts#L301

@tsvetilian-ty @say25 

How can I fix this? I can not add WebStorm to external editor.

**Comment by tsvetilian-ty** [comment]
@erseversahin can you check in the "Registry Editor" for the key associated with WebStorm?

1. Open "Registry Editor"
2. Navigate to `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall`
3. Check if `WebStorm 2022.1` entry exists
