### ISSUE TITLE
Mac Silicon - Pushing hangs and never completes

### ISSUE THREAD

**Issue by wedgiebee** [desktop/desktop#14399]
### The problem

When I try to Push, the progress bar gets stuck at "Pushing to origin, Total 365 (delta 243), resued 0...". I have left it over night making sure my computer didn't sleep and it still doesn't complete. There are no error messages or additional info that appears.

I have 17 commits I am trying to push, no huge files, but there was a lot of re-foldering in those commits.

### Release version

Version 2.9.14 (arm64)

### Operating system

macOS Monterey Version 12.3.1

### Log files

[2022-04-16.desktop.production.log](https://github.com/desktop/desktop/files/8502037/2022-04-16.desktop.production.log)

### Screenshots

![Screen Shot 2022-04-17 at 9 45 55 AM](https://user-images.githubusercontent.com/3342937/163724235-8581fca2-437b-4201-b156-a1f88f484b44.png)

### Additional context

Seems related to https://github.community/t/guthub-desktop-hangs-on-push/218348/7 and to https://github.com/desktop/desktop/issues/13855

**Comment by steveward** [comment]
Thanks for the report @wedgiebee. Have you tried pushing via the command line to see if that succeeds? Do pushes in other repositories succeed? Unfortunately the log file isn't showing any helpful information about why the push could be hanging.

**Comment by wedgiebee** [comment]
Hey @steveward, I pushed with the command line over night and it worked! There were a few odd things to note though:

1) It still took a really long time, to the point where I did just have to leave it overnight.
2) I'm not familiar with the command line, but from what I could tell it never printed text indicating it actually finished pushing (though online and in the Github Desktop history tab I can verify that it did finish pushing).

Here's the command line for a __normal push:__

<img width="602" alt="Screen Shot 2022-04-18 at 8 49 21 AM" src="https://user-images.githubusercontent.com/3342937/163835133-165586ce-c43e-4e63-b10f-c3caff7e4c14.png">

But here's what I got for the __push that I had to leave on overnight that was failing in Desktop:__

<img width="602" alt="Screen Shot 2022-04-18 at 8 21 06 AM" src="https://user-images.githubusercontent.com/3342937/163835223-52717025-3340-44d1-900d-c6f5eb0b7284.png">

Note that that's what it looked like both when I left it overnight, but also when I came back and saw that the push had succeeded on the Github website and the Github Desktop history tab.

It never printed the text that seems to indicate the push was successful. Hope this info is helpful!

**Comment by wedgiebee** [comment]
Wait but I did answer the questions above 🤔

**Comment by steveward** [comment]
@wedgiebee sorry about that, we switched to a new no response bot. It sounds like the push was just taking a long time...if you push a smaller change does it succeed? I would also recommend trying on a different network if possible.

**Comment by wedgiebee** [comment]
@steveward All good! When I push smaller changes it succeeds. Sadly I don't have another network to try. Yes it took a long time, but I think the weirdest thing for me is just that **the terminal never showed it completed (see above screenshot) even though it actually had** - as well as the fact that it **only succeeded through the terminal** and not through Desktop.

Real update is that it was becoming too huge of a hassle, so I switched to using SourceTree. I found SourceTree would also hang indefinitely when doing big pushes, but if I force quit, re-launched, and pushed again it would succeed (which was **not** the case with Github Desktop)! This was a little inconvenient but at least it worked, so I've just been in SourceTree since. Sorry I don't have any other Github Desktop info!

**Comment by steveward** [comment]
Thanks for the update @wedgiebee -- I'm going to close this out as it doesn't look like it's a specific issue with GitHub Desktop.

**Comment by karaismailhakki** [comment]
This problem still persists. In 90% of my commits, it gets stuck with a text like "Total xxx (delta xx), reused 0 ...". This is a situation you need to resolve. It's not something you can just say it's okay and throw it away.

**Comment by steveward** [comment]
@karaismailhakki please open a new issue and fill out the template if you are experiencing a similar problem.

**Comment by LeakedDave** [comment]
Reopening. Consistent issues pushing Large PNG files from MacOS. Having this issue on my x86 Mac Pro and on my Apple Silicon MacBook Air. I'm trying to push a 1.9MB PNG file as a background for a level for my game, no bueno. It hangs saying Total 25 (delta 20). Same issue on command line. I pay a hefty monthly subscription. Shouldn't be any issues here.

**Comment by LeakedDave** [comment]
I tried a trick I found online

git config http.postBuffer 16384

This isn't resolving the issue, either.

**Comment by portalzine** [comment]
**Update:** 
`git config --global core.compression 4` fixed it for me !

Having the same issue and can confirm the above applies to me as well.
Hangs on Github Desktop and from the commandline. 
Worked fine last night, so might be related to a specific time of the day.

**Comment by burakc** [comment]
Was having same issue with Macbook Pro 2019 Intel i7
@portalzine solution worked for me thanks.
`git config --global core.compression 4`

**Comment by spawn81** [comment]
Today I had the same problem after upgrading GitHub desktop and my Mac M1 to Ventura 13.2.1 
The @portalzine solution worked for me too. Thanks

**Comment by gewimmer-neuro** [comment]
Also same issue, never finishing when pushing larger than usual update (web images).  @portalzine solution also worked for me.

**Comment by KibbaFlyer** [comment]
Had the same issue on a M-chip macbook pro, a couple of 30 MB files didn't want to upload for some reason (had just the issue described by OP), @portalzine solution solved it!

**Comment by xgg94** [comment]
Since two weeks this happened to me as well. Using a M1 Max. Unfortunately, the answer from  @portalzine did not worked for me. Still hanging after "Total xxx (delta xx), reused 0 ..." Any other advices? I tried everything I found online.

**Comment by om3opr** [comment]
I have this issue as well on an m2 max MacBook. No luck!

**Comment by funonbeach** [comment]
still happening. m2 macbook

**Comment by portalzine** [comment]
Working perfectly for me on a M2.

**Comment by ShaMan123** [comment]
this helped me
https://stackoverflow.com/questions/8957862/how-to-upgrade-git-to-latest-version-on-macos
