### ISSUE TITLE
File Handler Reassertion for Windows

### ISSUE THREAD

**Issue by VishwaJay** [desktop/desktop#14405]
### The feature request

There are a few apps which have the ability to hook and assert file and protocol handling in Windows (not sure on other OS platforms).

The feature I'm asking for is to be able to revoke and reassert the GitHub Desktop handler within browsers within the options of GitHub Desktop, since literally everyone now says it's someone else's problem.

### Proposed solution

The issue of lost and reasserted permissions within various browsers is almost certainly something that will require a lot of collaboration with various browser teams. But the end result will be a smoother and more resilient functionality for those times where we end users accidentally click a button we didn't mean, and have zero recourse to correct the choice.

It seems that every time someone comes up with a solution to restore the correct function, the browser teams fix it so that you can't hack the browser, and typically this reverts a previous (non-functional, or at the very least dysfunctional) state.

Browser teams need to either allow restoration and change, or they need to stop preventing such. Until that time, a simple hook to revoke and then reassert protocol handling within the browsers should be something the desktop app should be able to initiate with regard to the browser's operation.

### Additional context

When I was first installing GitHub Desktop, I was asked if I wanted it to handle all protocol handlers for opening in GitHub Desktop. The answer was an accidental 'no'. In over a year, I've been exploring different ways to reassert this behavior, and literally nothing works.

The fine folks at Windows said it's not their issue. Multiple browsers say they can, but that it's something that the software should be able to reassert, and refuse to offer help on hacking the browser back to correct functionality. So, here I am, asking for this feature, which should essentially restore the one feature I still want working.

With everyone saying "it's not my job" the aim here is to get everyone who believes that to hammer out whose job it actually is, and make it so that the software behaves in a functional way instead of being locked to dysfunction.

**Comment by steveward** [comment]
Thanks for the issue @VishwaJay. This has been an issue in the past, but has not been widespread enough to warrant a specific solution within GitHub Desktop itself. The more prominent issue we've had it our links getting used by other applications (https://github.com/desktop/desktop/issues/8258).

What specific browser and operating system are you using? It should be possible to get things working again for you.

**Comment by VishwaJay** [comment]
The issue is within Firefox on Window 11, but also seems to affect Chrome.

The workaround I've found to get it working again (which seems to have fixed both browsers as of 3 days ago) is to completely wipe out all history, cookies, etc., and push it back to as close to factory new as possible.

Oddly, an uninstall/reinstall didn't have the same effect. It has to be done within the settings of each browser affected on an existing install, wherever the wrong button was accidentally selected. This pushes toward the idea that it's the onus of the browser groups to provide a hook for specific apps to reassert. But it's working now.
