### ISSUE TITLE
GitHub Desktop completely unusable for me

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#14401]
### The problem

When I try to clone any repository, GitHub Desktop fails and puts out this error message:

_"Cloning into 'C:\Users\Test\Documents\GitHub\example'...
remote: Enumerating objects: 757, done.        
remote: Counting objects: 100% (333/333), done.        
remote: Compressing objects: 100% (277/277), done.        
remote: Total 757 (delta 135), reused 124 (delta 38), pack-reused 424        
Receiving objects: 100% (757/757), 1.60 MiB | 9.51 MiB/s, done.
Resolving deltas: 100% (309/309), done.
      0 [main] sh 1652 dofork: child -1 - forked process 332 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Test\AppData\Local\GitHubDesktop\app-2.9.14\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
1088465 [main] sh 1652 dofork: child -1 - forked process 13928 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Test\AppData\Local\GitHubDesktop\app-2.9.14\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
3188997 [main] sh 1652 dofork: child -1 - forked process 10300 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Test\AppData\Local\GitHubDesktop\app-2.9.14\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
7283242 [main] sh 1652 dofork: child -1 - forked process 9240 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Test\AppData\Local\GitHubDesktop\app-2.9.14\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
15371245 [main] sh 1652 dofork: child -1 - forked process 7464 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Test\AppData\Local\GitHubDesktop\app-2.9.14\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: Resource temporarily unavailable

Would you like to retry cloning ?"_

However, it actually manages to download all contents of the repositories to the GitHub folder inside my Documents folder. The problem prevents me from doing any pull requests or fetches.

This problem affects all repositories equally and I already tried deleting the GitHub folders in AppData/Roaming and AppData/Local. I also tried completely uninstalling GitHub Desktop and reinstalling it. The problem still persists.

The last time GitHub Desktop worked flawlessy was around March 1st-3rd 2022. Thats the last time I used GitHub Desktop. 

### Release version

Version 2.9.14 (x64)

### Operating system

Windows 11 Enterprise

### Steps to reproduce the behavior

I dont know what to write here, because this issue affects all repositories equally which makes GitHub Dekstop completely unusable for me.

### Log files

Cloning into 'C:\Users\Test\Documents\GitHub\example'...
remote: Enumerating objects: 757, done.        
remote: Counting objects: 100% (333/333), done.        
remote: Compressing objects: 100% (277/277), done.        
remote: Total 757 (delta 135), reused 124 (delta 38), pack-reused 424        
Receiving objects: 100% (757/757), 1.60 MiB | 9.51 MiB/s, done.
Resolving deltas: 100% (309/309), done.
      0 [main] sh 1652 dofork: child -1 - forked process 332 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Test\AppData\Local\GitHubDesktop\app-2.9.14\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
1088465 [main] sh 1652 dofork: child -1 - forked process 13928 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Test\AppData\Local\GitHubDesktop\app-2.9.14\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
3188997 [main] sh 1652 dofork: child -1 - forked process 10300 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Test\AppData\Local\GitHubDesktop\app-2.9.14\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
7283242 [main] sh 1652 dofork: child -1 - forked process 9240 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Test\AppData\Local\GitHubDesktop\app-2.9.14\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
15371245 [main] sh 1652 dofork: child -1 - forked process 7464 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Test\AppData\Local\GitHubDesktop\app-2.9.14\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: Resource temporarily unavailable

Would you like to retry cloning ?

### Screenshots

![Screenshot 2022-04-18 121251](https://user-images.githubusercontent.com/29334879/163794251-20b3946d-4f4c-4952-87f5-3ecfa725ceb2.png)

### Additional context

[system info.txt](https://github.com/desktop/desktop/files/8505047/system.info.txt)

**Comment by steveward** [comment]
Thanks for the issue @yorehiwo.

Could you take a look at this: https://github.com/desktop/desktop/blob/development/docs/known-issues.md#enable-mandatory-aslr-triggers-cygheap-errors ?

You may have mandatory ASLR enabled which could cause this kind of issue. Could you try disabling it and see if that helps?

**Comment by ghost** [comment]
I had to google first. What ASLR means and how to disable it.
But I found it, disabled it and now GitHub works again. Thank you.

For everyone else having the same issue and dont know how to disable ASLR:

It's within Windows-Security under "App & browser control" and then at "Force randomization for images (Mandatory ASLR)" Set it to "Off by default"

Again, thank you @steveward for your help.

![0](https://user-images.githubusercontent.com/29334879/163827872-608294f6-e9bd-4acf-afa8-e4a4fc5229fa.png)

**Comment by amaribrahim** [comment]
Pretty sure it's a terrible idea to disable ASLR. Is there a safer fix?

**Comment by nitronarcosis** [comment]
> Pretty sure it's a terrible idea to disable ASLR. Is there a safer fix?

You should be able to disable it on a per-app basis by using the program settings tab instead. I think the long-term fix is to make sure all the executables are compiled with ASLR support.

**Comment by deminimis** [comment]
Which program would you disable ASLR for in the Github desktop installation? I disabled completely and now it works, but I tried disabling a few of them in there without disabled for the entire Windows 10, such as the githubdesktop.exe (a couple in there), git-credential-manager under mingw64, etc., and none of them would make it work.
