### ISSUE TITLE
无法上传以及汉化后白屏问题

### ISSUE THREAD

**Issue by kuanglanlingxian** [desktop/desktop#14400]
### The problem

始终无法上传显示cannot publish ubborn HEAD

### Release version

version 2.9.14 (x64)

### Operating system

Windows7

**Comment by steveward** [comment]
@guqilingcang the `cannot publish unboard HEAD` usually indicates that there are no commits on the current branch that you are trying to publish. Try committing changes and then publishing, let me know if you run into any issues.
