### ISSUE TITLE
"Discard modified lines" does not discard changes

### ISSUE THREAD

**Issue by TheHolyWaffle** [desktop/desktop#14408]
### The problem

When right-clicking the change and choosing "Discard modified lines", it does not discard the changes.

Expected result: changes should be discarded

### Release version

2.9.14

### Operating system

macos 12.0.1

### Steps to reproduce the behavior

1. Make a change in a file
2. Go to github desktop to see the line changes
3. Right-click on the blue section next to the relevant lines
4. Choose "Discard modified lines"

### Screenshots

![image](https://user-images.githubusercontent.com/787914/163955707-abf5875a-ee21-41c5-bea9-304c2422e8bf.png)

**Comment by steveward** [comment]
Thanks for the report @TheHolyWaffle. I was unable to reproduce this issue on my machine. Are you able to reproduce this consistently across multiple repositories?

**Comment by TheHolyWaffle** [comment]
@steveward Yes, it happens across all repositories on my MacBook pro. I could not find any output in logs nor developer tools when reproducing it 😢

**Comment by steveward** [comment]
@TheHolyWaffle have you tried switching the diff display to split diff to see if you are able to discard the changes there?
