### ISSUE TITLE
Unable to modify or delete a repository

### ISSUE THREAD

**Issue by Maxime66410** [desktop/desktop#14414]
### The problem

Unable to modify, create or even delete the repository.

Yet nothing uses these files, I restarted my pc several times but I still had the error.

I tried to reinstall github but I still had the same error only on this repository.

Yes I am logged into my github account.

### Release version

Version 2.9.14 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

- Go to download repository
- Wait to download
- All FInish

### Log files

[2022-04-20.desktop.production.log](https://github.com/desktop/desktop/files/8518883/2022-04-20.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/37190601/164165152-c45f6475-c096-4960-82ce-a3c11c3af009.png)

![image](https://user-images.githubusercontent.com/37190601/164165215-115c4cfa-832c-447e-9c60-f7f61440d171.png)

**Comment by steveward** [comment]
Thanks for the report @Maxime66410. Are you able to perform any actions in GitHub Desktop, like committing? The specific error I'm seeing in the log file would be triggered by trying to delete the repository:

```
2022-04-20T06:32:18.697Z - error: [ui] Failed moving repository to trash
Error: Error invoking remote method 'move-to-trash': Error: Operation was aborted
```

This specific error should have been fixed in a previous release -- are you storing this repository on a network drive or in WSL?

**Comment by Maxime66410** [comment]
> WSL

WSL ?

The project is on an external hard drive.
Could this be the cause of the problem?

**Comment by steveward** [comment]
Apologies, that stands for Windows Subsystem for Linux. I would recommend testing on a standard system drive to see if you encounter the issue there as well.

**Comment by Maxime66410** [comment]
Sorry but yesterday I waited 1 hour and it came back on its own.

I don't know what caused this problem.

It's probably like you say I use an external hard drive, but that's something that never happened.

Anyway thank you very much.
