### ISSUE TITLE
When new GitHub Desktop version?

### ISSUE THREAD

**Issue by paulb-peterson** [desktop/desktop#14413]
### The problem

When will a new version of GitHub Desktop be released to fix this issue? https://github.com/desktop/desktop/issues/14336

### Release version

2.9.14 (x64)

### Operating system

Windows 10

**Comment by niik** [comment]
Hey @paulb-peterson. We've already shipped an update to our [beta channel](https://desktop.github.com/beta/) that you can install right now. We're planning on shipping an updated version to our production channel this week.

**Comment by paulb-peterson** [comment]
I'd rather not install betas.  I'll wait for the updated version.  Thx
