### ISSUE TITLE
multi-remote support in Desktop

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#1442]
Opening this up to track a discussion around which scenarios we could/should support in Desktop.

**Comment by j-f1** [comment]
When cloning a forked repository from the macOS classic app, two remotes are generated: `origin` (pointing to the fork) and *username*, (pointing to the parent). For example, if I forked and cloned this repository, I’d get this:

```
$ git remote --verbose
desktop      https://github.com/desktop/desktop.git (fetch)
desktop      https://github.com/desktop/desktop.git (push)
origin  https://github.com/j-f1/forked-desktop.git (fetch)
origin  https://github.com/j-f1/forked-desktop.git (push)
```

However, when using the new app, I get this:

```
$ git remote --verbose
origin  https://github.com/j-f1/forked-desktop.git (fetch)
origin  https://github.com/j-f1/forked-desktop.git (push)
```

This makes it more difficult to keep the repo up-to-date with the parent repository.

**Comment by shiftkey** [comment]
@nturaga suggested the ability to manage remotes in #2470:

> I expect to be able to click on "Repository settings", and be able to add a remote. So, maybe a "new remote" button which leads to "remote name" and "remote url".

**Comment by joshaber** [comment]
We're planning to handle the specific case of forks in [1.1](https://github.com/desktop/desktop/issues/2364). 

Other than that, we don't have anything on our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out.

**Comment by oogetyboogety** [comment]
Support for multiple remotes is a workflow requirement because Github for desktop does not allow for me to clone a public Github repository, then publish that same repository to a new remote, but not a new origin, on the corporate Github Enterprise server. Or maybe I'm not away of how.

**Comment by steveward** [comment]
@oogetyboogety thanks for your feedback! You are correct that it is not possible to work with a GitHub Enterprise remote and a GitHub remote in the same repository within GitHub Desktop -- you will have to use the command line. Is it a common scenario for you to work with the same repository that exists in both GitHub and GitHub Enterprise?

**Comment by YaseenTwati** [comment]
Hey
Personally I don't use Github with Github Enterprise 
but its a common scenario for me to push to multiple remotes with the same repository as one of the is the production server and the other is the dev/testing one before pushing to production.

**Comment by suparnavg** [comment]
@steveward this would be a useful addition to the desktop client

**Comment by jm3** [comment]
I use Dropbox as a primary remote and GH as a "releases" remote that i push too less regularly, so this would be handy for me as well.

**Comment by drewbaker** [comment]
I'm dealing with this with a cleint who wants us to push to a Github Enterprise account behind a VPN. Would be so handy to have two remotes, one for our regular GitHub version, and another for the clients Github Enterprise repo.

**Comment by gilmoskowitz** [comment]
I'd like to see good support for multiple remotes in GitHub Desktop as well. At present a couple of different workflows my company uses cannot be handled with the desktop client. Here's one that should be common but doesn't seem simple to accomplish:

```
+--------------+                +---------+
| company repo |<-pull request--| my fork |        <<< on github
+--------------+                +---------+
       |                             ^
 fetch |                             | push
       +-----------+      +----------+
                   V      |
                +-----------+
                | my clone  |                      <<< my laptop
                +-----------+
```
That's two remotes — company and mine. The `origin` depends on which was cloned and which was `remote add`ed. The situation gets more complex when reviewing code, as that often requires yet another remote for each contributor. I typically have between 3 and 5 remotes in any given clone to coordinate distributed team development.

At minimum the ability to add remotes and fetch either singly or `--all` is important. So is the ability to pick the remote to `push --set-upstream`, allowing suggestions via pull request to my teammates' forks. Displaying or filtering branches by remote would be helpful.

**Comment by steveward** [comment]
Feedback from @Jasonnor in https://github.com/desktop/desktop/issues/9596:

>We can only change default remote url, but not "remote".
E.g., there is 3 remotes: `origin`, `upstream`, `gitlab`, and default remote is `origin`.
But only the remote URL of `origin` can be changed instead of switching from `origin` to `gitlab`.

**Comment by steveward** [comment]
Feedback from https://github.com/desktop/desktop/issues/10257:

>It misses control to set as Primary Remote a local repository (D:\<<..>>) to use Push to export the changes to backup drive/location .

**Comment by steveward** [comment]
Requested in https://github.com/desktop/desktop/issues/10876.

**Comment by cyberangel67** [comment]
After 2 years I struggle to see why this is not a thing, as someone who does a lot of contract work, I have more than one repository. C# Stuff I have with Azure DevOps Account on MS through Visual Studio. And with all my Unity stuff I also have on GitHub as well as some private repositories, any reason GitHub Desktop doesn't support more than one repository after 2 years?

**Comment by PhillipNordwall** [comment]
Having multiple remotes for work ends up being used everyday for me. I am surprised that this is still not a capability that GitHub Desktop has.

**Comment by bitbound** [comment]
This is the only feature that prevents me from using GitHub Desktop as my primary git tool.

**Comment by guyer** [comment]
In addition to the typical development patterns discussed above, that use multiple remotes, because GitHub Classroom's use of templates and branches [is](https://education.github.community/t/templates-and-branches/49615) [broken](https://github.com/education/classroom/issues/2453), multiple remotes is a necessary workaround. With only one remote, GH Desktop is basically useless for Classroom repos (for the instructor anyway).

**Comment by MrNickArcher** [comment]
I need this feature please.
So typical to find several closed issues pointing to this one, only to find this one closed D:

**Comment by crstauf** [comment]
Why has this been neglected for four years? Is this a hard thing to add? Unbelievable.

**Comment by kerri-hicks** [comment]
I know this issue is marked closed, but it's a feature that would be quite useful for our team. I work with a host that holds our live production code in its own git repo. However, their repo doesn't have any peer-review tools, which are an integral part of our workflow. Here's how it looks now:

1. Develop and test locally, commit, push to GitHub (remote "github").
2. Create pull request for code review by another dev, then the reviewer dev merges the PR to main ("never merge your own commits").
3. Pull down merged main branch from GitHub to local.
4. Push from local to host (remote "origin").

I can do this at the command line (and probably with CI), but I have students/junior devs who need to start out with a GUI client. (Also, some devs just prefer to use a GUI tool rather than the command line, no judgement.)

It would be really useful if I could change the remote in GHD to be able to make this happen.

**Comment by steveward** [comment]
Requested in https://github.com/desktop/desktop/issues/14614

**Comment by MisterVector** [comment]
What is holding this up from being added? You know this is a very requested feature, hence the big question I just asked. I too would like this added!

**Comment by liamcsmith** [comment]
Echoing other comments in this thread, this would be a very useful feature that exists in other git GUIs, would be great to see it implemented.

**Comment by techtunes** [comment]
6 years of request but not implemented.

**Comment by bobsummerwill** [comment]
Just found my way here when trying to do exactly this, and cannot believe the feature is missing.

Look at SourceTree.  It is trivial to add additional remotes there, just as it is trivial to do so with the git command line.

Please can this be prioritized?   Most users will be an upstream as well as origin for normal daily flow.

**Comment by steveward** [comment]
Requested in https://github.com/desktop/desktop/issues/16085.

**Comment by Bian-Sh** [comment]
> 6 years of request but not implemented.

so far so cool~

**Comment by Noufal-Hashcode** [comment]
any tool available  to use github and bitbucket as remote together

**Comment by guyer** [comment]
@Noufal-Hashcode, [SourceTree](https://www.sourcetreeapp.com/) is the app that GH Desktop should be.

**Comment by bobsummerwill** [comment]
@Noufal-Hashcode @guyer I would second that.

SourceTree is what I was using previously and might well return to because of this issue.

**Comment by ghost** [comment]
Merhaba arkadaşlar benim bu hesabımı

**Comment by ghost** [comment]
Merhaba arkadaşlar bu hesabım çalınmıştır. Whappsab, facebook, youtube mail lerim ve biraz arastırma yapıp Microsoft uyguşamasında vigil ikiz uygulamalar indirilmiş. Lütfen bu hesabımı şikayet edin ve kapansın.

**Comment by ghost** [comment]
İOS hesabıma giremiyorum. Herşey elinde çalan kişi

**Comment by ghost** [comment]
> Opening this up to track a discussion around which scenarios we could/should support in Desktop.

**Comment by huangcs427** [comment]
any plan?

**Comment by JonSmithAsItWere** [comment]
This is a very important feature for my workflow currently, and it's really unfortunate that it's missing from a client that pretty much does everything else exactly as I'd want it to.

I dropped SourceTree in favor of Github Desktop, and we even switched over from Bitbucket to Github Desktop due to issues with the Bitbucket API doing strange things with the encoding of some of our files. And SourceTree has severe performance issues as your repository library grows in size. But I may have to reconsider using SourceTree since GD is the only Git GUI that I know of that doesn't innately support multiple remotes.

Just to describe the kind of workflow I have (where this is critical), I sometimes have to reference and cherry-pick individual commits from other remote repositories that aren't in the history of the origin/upstream that I'm using. Much of the codebase across the repositories I have is fairly standardized, which makes the occasional cherry-pick to add or remove some feature possible. But these repositories are only similar enough that a cherry-pick can be used - a full-blown merge is simply not feasible or pragmatic unless I want to give myself way more work by manually confirming every relevant change.

By having multiple remotes and being able to cherry-pick commits from those remotes, I can quickly implement a feature from one repository's codebase to my current repository. And that's why being able to use multiple remotes is invaluable for a Git GUI.

**Comment by crstauf** [comment]
@JonSmithAsItWere I used to use SourceTree as well, and switched to [Fork](https://git-fork.com/) because of the performance issues. It's a dream.

**Comment by JonSmithAsItWere** [comment]
@crstauf Thank you, I'll have to try that client at some point.

So far I've been through SourceTree, GitKraken, Github Desktop, and now Git Tower. GD has almost every feature I need... except for this one...

**Comment by crstauf** [comment]
@JonSmithAsItWere Yeah, I've tried those as well, and Fork has been the best for me.

**Comment by therpgmaster** [comment]
+1 for adding this feature. It's a simple one, I can't believe it's not there already.

**Comment by NickMainAtPI** [comment]
This would also be very useful when migrating a repository from one host to GitHub. I would like to setup multiple remotes so we can keep our new GitHub repo in sync until we phase out of using the old remote.

**Comment by diev** [comment]
7 years of being ignored. This is highly likely just a vendor lock-in.

**Comment by xtools-at** [comment]
this is a dealbreaker for many. since the request was ignored for 7 years, it's probably better to find some other app...
btw the team is linking to this issue from every other thread, but it's a closed one, so most likely no one cares anyway

**Comment by llcxiongmao** [comment]
7 years, not implement, please open again.

**Comment by steveward** [comment]
From https://github.com/desktop/desktop/issues/18657:

> GitHub Desktop currently lacks support for managing multiple remotes through its graphical user interface (GUI). This feature request aims to address this limitation and provide users with the ability to seamlessly manage multiple remote repositories directly within GitHub Desktop.
> 
> Proposed solution
> Introduce a dedicated interface within GitHub Desktop that allows users to add, remove, and switch between multiple remotes associated with their repositories. This interface could include options to:
> 
> Add new remotes by specifying the remote URL and a custom name.
> Remove existing remotes.
> Select a default remote for push/pull operations.
> Easily switch between remotes when viewing branches, commits, and pull requests.
> 
> Additional context
> It's important to note that while GitHub Desktop currently supports basic remote management for the default "origin" remote, there is no built-in functionality for managing additional remotes. As a result, users often resort to using the terminal, which may not be ideal for everyone.
> 
> Incorporating support for managing multiple remotes directly within the GitHub Desktop GUI would align with the tool's goal of providing a seamless and user-friendly Git experience. This feature would cater to the needs of users who frequently collaborate across multiple remote repositories and contribute to enhancing GitHub Desktop's overall usability.

**Comment by JustusAvramenko** [comment]
?!?!?!?!?!?!?!?!?!?!?

Where is the feature?

**Comment by bayraak** [comment]
Yes, reopen this please

**Comment by netcore-jroger** [comment]
Any updates now?

**Comment by sed1ka** [comment]
@steveward Can you please reopen this issue so it can at least be tracked?
Currently, GitHub Desktop doesn’t support multiple remotes, while other Git GUI tools already provide this feature. It would be great to have this functionality considered here as well.
