### ISSUE TITLE
slow operation of the Github Desktop

### ISSUE THREAD

**Issue by Dimach24** [desktop/desktop#14429]
### The problem

Github desktop is running so slow.
Each action causes application freezes

### Release version

2.9.15 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

any button pressing or clicking

### Log files

[2022-04-21.desktop.production.log](https://github.com/desktop/desktop/files/8532232/2022-04-21.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report, I'm going to add this to https://github.com/desktop/desktop/issues/13586 and close this issue out. you can follow along there for updates.
