### ISSUE TITLE
GitIgnore Bug

### ISSUE THREAD

**Issue by satyambits** [desktop/desktop#14427]
### The problem

The Problem is I can't commit my changes as the library file are also included in it, forcefully. Whereas, in Unity Library file are not needed to commit

### Release version

Version 2.9.15 (x64)

### Operating system

Windows 11

### Screenshots

![image](https://user-images.githubusercontent.com/75877682/164480722-828c7533-47b1-44e7-9057-bc21c2cd9485.png)

**Comment by steveward** [comment]
@geekysv if you updated your `.gitignore` and need to commit those changes you can de-select all changes (click the checkbox in the `changed files` header). Once you've done that you can select the `.gitignore` file to commit, which should cause those `Library` files to be ignored. Let me know if you have any further issues.
