### ISSUE TITLE
GithubDesktop v2.19.15 malicious?

### ISSUE THREAD

**Issue by KnulstBDH** [desktop/desktop#14420]
### The problem

As soon as I start Github Desktop, my pc detects the following in Squirrel and 2.19.5-full.nupkg:
![afbeelding](https://user-images.githubusercontent.com/89086157/164226249-3a93097d-a4bb-43d4-bdf8-072b68a15ccd.png)

Is this a false positive or..?

### Release version

2.19.5

### Operating system

Windows

**Comment by niik** [comment]
@KnulstBDH what anti-virus software are you using? We see false-positives from anti virus vendors time to time. Running that file [through virustotal](https://www.virustotal.com/gui/file/716110ded01a609f149d6c756b8c3e0c35c895cb9898f397cb821d96ecc32969/detection) shows two vendors (Cylance, and Jiangmin) flagging the file. Are you using either of those?

**Comment by KnulstBDH** [comment]
Hi @niik ,

I am using Securepoint Antivirus Pro version 3.3.32

**Comment by steveward** [comment]
@KnulstBDH it looks like you should be able to whitelist specific directories in Securepoint:

https://wiki.securepoint.de/index.php?title=AV/Client/Einstellungen&uselang=en

See the 'Exclusions' section. Can you try doing that to see if it gets things working?

**Comment by KnulstBDH** [comment]
It seems that the issue has resolved itself. Thanks for the help!
