### ISSUE TITLE
Desktop application crash

### ISSUE THREAD

**Issue by aareusoftnet** [desktop/desktop#14424]
I have got a white screen in the GitHub Desktop app and I quit the app and open it again then it automatically crashes. Please check the crash log which shows me while opening GitHub Desktop app.
![Screenshot 2022-04-21 at 11 05 21 AM](https://user-images.githubusercontent.com/90060278/164381704-3c5b5713-f19c-4f8a-82d9-52c9da098c45.png)

**Comment by steveward** [comment]
Thanks for the report @aareusoftnet. Have you tried performing a fresh installation of GitHub Desktop to see if that resolves the issue?

**Comment by steveward** [comment]
@aareusoftnet as we haven't heard back from you I am going to close this issue out. If you're still having issues let us know and we can investigate further.
