### ISSUE TITLE
Switches to changes tab from history tab for an instant

### ISSUE THREAD

**Issue by sushiljainam** [desktop/desktop#14428]
### The problem

* I was comparing feature branch to base branch in history tab of selected repo and selected branch.
* multiple times whole screen changed to 'Changes' tab for an instant and cam back to 'History' tab automatically.
* I recorded a video (2min long video), posting a clip here only for around 5 seconds.

**Frequency**: happened 4 5 times in 10 min duration.

https://user-images.githubusercontent.com/13596814/164482809-80138574-12e5-4ece-8624-da7a349ec97a.mp4

### Release version

Version 2.9.15 (arm64)

### Operating system

MacOS Monterey 12.3.1 (21E258)

### Steps to reproduce the behavior

* I was comparing feature branch to base branch in history tab of selected repo and selected branch.
* multiple times whole screen changed to 'Changes' tab for an instant and cam back to 'History' tab automatically.
* I recorded a video (2min long video), posting a clip here only for around 5 seconds.

**Comment by steveward** [comment]
Thanks for reporting this @sushiljainam -- the video is helpful. We've seem similar UI behavior reports in https://github.com/desktop/desktop/issues/14364 (in that case it was changes appearing/disappearing). 

Are you able to reproduce this in multiple repositories?

**Comment by sushiljainam** [comment]
I don't think it is related to repo, but I'll try to observe in other repos as well.

**Comment by sushiljainam** [comment]
did not observed since long.
may be it was fixed with some other work going on.
i am using current version is 3.0.0 for GitHub Desktop, working fine.

**Comment by steveward** [comment]
Thanks for the update @sushiljainam. I'm going to close this out, but let us know if you run into this again.
