### ISSUE TITLE
Github desktop keeps prompting for a helper tool, and changes its ownership to root when updating

### ISSUE THREAD

**Issue by chunkybanana** [desktop/desktop#14422]
### The problem

Every few hours, a prompt pops up as described [here](https://github.com/desktop/desktop/issues/10777). The steps described [here](https://github.com/desktop/desktop/issues/3616#issuecomment-400371047) fix the problem temporarily, but a bit later, the same prompt pops up, and when I check the ownership of `Github Desktop` it has returned to `root`.

### Release version

2.9.14

### Operating system

MacOS 12.3

### Steps to reproduce the behavior

`chown` the ownership of `Github Desktop.app` from `root` to the current user
Wait a few days for an update
Check the ownership of `Github Desktop.app` - it will have changed back to `root`

### Log files

[2022-04-20.desktop.production.log](https://github.com/desktop/desktop/files/8525367/2022-04-20.desktop.production.log)

**Comment by himanshumps** [comment]
+1 .. I am having the same issue. Giving the 777 permission to all the files and subfolders did not help

```
bash-3.2$ ls -l /Applications | grep "GitHub Desktop"
drwxrwxrwx  3 *******  staff   96 Mar  3 15:00 GitHub Desktop.app
```

**Comment by niik** [comment]
@chunkybanana Going through stale issues and came across this one. Is this something you're still experiencing with the latest version? If it is could you try removing the app entirely from the Applications folder, downloading the latest version from https://desktop.github.com and dragging it to the Application folder. There's no logic that I'm aware of that would cause GitHub Desktop to attempt to change the ownership of itself.

**Comment by sergiou87** [comment]
Probably related: #13956
