### ISSUE TITLE
Problem of github desktop view

### ISSUE THREAD

**Issue by jbarcia2019** [desktop/desktop#14426]
### The problem

As we can see in the screenshot i have some lines of diferents colors next to the github desktop window.
When i move window the lines also move and when i minize github window lines disappear.

This problem start today when i updated the github desktop to the latests 

### Release version

2.9.15

### Operating system

Windows 11

### Steps to reproduce the behavior

Only opening it

### Screenshots

![image](https://user-images.githubusercontent.com/80538755/164478089-4a6f1c33-b49e-4227-86e7-ff9dca55163d.png)

**Comment by steveward** [comment]
Thanks for the screenshot @jbarcia2019. Does this persist across restarting the app?

**Comment by steveward** [comment]
@jbarcia2019 as we haven't heard back from you I am going to close this issue out. If you're still having issues let us know and we can investigate further.

**Comment by jbarcia2019** [comment]
Yes, and restarting windows and reinstalling the app also

Jesús Barcia

El 21 abr 2022, a las 20:05, Steve Ward ***@***.***> escribió:

﻿

Thanks for the screenshot @jbarcia2019<https://github.com/jbarcia2019>. Does this persist across restarting the app?

**Comment by sergiou87** [comment]
@jbarcia2019  Have you tried updating to the latest version of Desktop (current is 3.1.1)?

**Comment by salva-ruiz** [comment]
Hello, I think I have the same problem.
I have tried restarting Windows, the application and updating to the latest version 3.3.6 (64-bit) but the problems have persisted for several weeks.

![captura2](https://github.com/desktop/desktop/assets/46647615/e853d2ab-a99c-474c-babc-852f26d220c4)
![captura](https://github.com/desktop/desktop/assets/46647615/8a50ba83-5ff1-43f4-a617-72ef2c5b9dee)
