### ISSUE TITLE
Hi, This issue was not fixed!

### ISSUE THREAD

**Issue by harlandpj** [desktop/desktop#14437]
Hi,

This reply doesn't help!

Here's what I tried.

1. Started with an EMPTY directory on my PC.
2. Opened Github desktop which says can't locate repo (as expected) on my pc, and cloned it again.
3. Clone then FAILS with error "Clone succeeded, but checkout failed" due to Git repository over its data quota.

Yes I know it is, I'm trying to reduce the size of it!!!!

So... I CAN'T EVEN CLONE (even when I start with an empty directory on my PC) the repo, and when I try to switch from main to the development branch with the offending commits on, it WON'T stash changes of the stuff (which I just don't care about anyway, and won't let me overwrite them), that I had to clone to even open the repo, as my repo is.... OVER the quota (as it keeps telling me EVERY single time I try) using Github Desktop, so how can I do the changes you suggest?

Thanks!
Thanks
Phil

_Originally posted by @harlandpj in https://github.com/desktop/desktop/issues/14436#issuecomment-1106573615_

**Comment by harlandpj** [comment]
Hi,

I can do NOTHING with this repo as it stands.

I CANNOT clone it using Gitbash / CLI as it fails to clone due to the LFS quota issue!

I cannot even switch branch, or even do a git branch to list branches!!!

$ git clone https://github.com/harlandpj/wunderland-city
Cloning into 'wunderland-city'...
remote: Enumerating objects: 4193, done.
remote: Total 4193 (delta 0), reused 0 (delta 0), pack-reused 4193
Receiving objects: 100% (4193/4193), 225.38 MiB | 24.31 MiB/s, done.
Resolving deltas: 100% (2535/2535), done.
Updating files: 100% (2797/2797), done.
Downloading Wunderland City/Assets/Audio/Ambient/Extreme-Sport-Trap-Music-PISTA.mp3 (1.3 MB)
Error downloading object: Wunderland City/Assets/Audio/Ambient/Extreme-Sport-Trap-Music-PISTA.mp3 (c7a04a6): Smudge error: Error downloading Wunderland City/Assets/Audio/Ambient/Extreme-Sport-Trap-Music-PISTA.mp3 (c7a04a624bfe34fb63c3de48f02c92c0b5c312aec62f38d5bae9527adae90332): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to D:\Unity Projects\Wunderland-City\wunderland-city\.git\lfs\logs\20220422T160519.3844478.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Wunderland City/Assets/Audio/Ambient/Extreme-Sport-Trap-Music-PISTA.mp3: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'


Git branch won;t even show my development branch!
phil_@Phils-PC MINGW64 /d/unity projects/wunderland-city (master)
$ git branch

phil_@Phils-PC MINGW64 /d/unity projects/wunderland-city (master)

**Comment by harlandpj** [comment]
Additionally, just tried:

"    Go to history find a commit in that the branch that is in a good state. (before commit of the large files)
    Right click that commit and select "Create a branch from this commit". (make a new branch)
    Go to back to your affected branch and select the too large commits.
    Drag and drop them on your new branch in the branch menu Or right click them and select cherry-pick and then select your new branch.

Now your affected commits will be local to your new branch and you should be able to undo them."

I can't do this either, it will create a branch which I called "broken commits to delete" based on the working commit PRIOR to the large one that broke everything, but then I CAN'T switch to the development branch again as it WON'T stash the changes due to the LFS quoate issue.

This repo is now completely stuffed at present!

p.s.

Even creating a brand new repo, and trying to put the code in results in:
"phil_@Phils-PC MINGW64 /d/unity projects/wunderland-city-2 (main)
$ git push origin
Uploading LFS objects:   0% (0/100), 0 B | 0 B/s, done.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
"

Why, it's a completely new repo?

**Comment by steveward** [comment]
@harlandpj the reason you cannot clone is because the [free bandwidth](https://docs.github.com/en/billing/managing-billing-for-git-large-file-storage/about-billing-for-git-large-file-storage) has been used for your account. Unfortunately I'm not able to reset this, but if you reach out to [GitHub Support](https://support.github.com/) they may be able to assist you further. 

You can bypass the LFS objects during the clone operation by running this command:

`GIT_LFS_SKIP_SMUDGE=1 git clone <repository_URL>`

I would recommend following the steps @tidy-dev shared if you're comfortable using the command line to reset your existing local repository. You can also follow [this guide](https://docs.github.com/en/repositories/working-with-files/managing-large-files/removing-files-from-git-large-file-storage) to remove the specific files from LFS.

**Comment by harlandpj** [comment]
Hi,

Thanks, I've now just bought a data pack, but Github support have currently inadvertently broken my repo by deleting more LFS files than they were asked to, and consequently have BROKEN the vast majority of Unity GUID (unique file pairs between files and meta files which look to be generated in Unity using the original file creation times etc) objects in it as a result.

I have requested they restore this repo from any daily backups (which should have been done by Github) before they made changes to it, as currently it is wrecked, with all scene data/audio/lighting and terrain data completely missing, and cannot be built at all.

Thanks
Phil.

**Comment by steveward** [comment]
Thanks for the update. If we can be of any further assistance on the GitHub Desktop side of things let us know! I'm going to close this out.
