### ISSUE TITLE
Authentication failed - UNPROTECTED PRIVATE KEY FILE - as of 2.9.15

### ISSUE THREAD

**Issue by leongersen** [desktop/desktop#14435]
### The problem

After the update to 2.9.15 I'm getting an "Authentication Failed" error on any Git action in Desktop.

Logs show that my private key was ignored because its permissions are too open. I got this resolved by having our admin (who provisions these key files) limit the permissions on the file, and enabling `Use system OpenSSH (recommended)` in `File > Options > Advanced`.

I'm not sure what changed in the latest release to check for these permissions.

It would be nice if this error was presented to the user, instead of having to pull it from the logs.

### Release version

2.9.15

### Operating system

Windows Server 2019 Standard - Remote Desktop Session Host role

### Log files

```
2022-04-22T06:38:46.491Z - error: [ui] `git -c credential.helper= push origin <REMOVED> --set-upstream --progress` exited with an unexpected code: 128.
stderr:
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions for 'C:\\Users\\<REMOVED>/.ssh/id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "C:\\Users\\<REMOVED>/.ssh/id_rsa": bad permissions
git@git.<REMOVED>: Permission denied (publickey).
fatal: Could not read from remote repository.
```

### Screenshots

![image](https://user-images.githubusercontent.com/1206361/164623327-8e7b5870-cff8-471b-807d-0067ad2c1701.png)

**Comment by thinkyhead** [comment]
You may just need to do `chmod 644 $HOME/.ssh/id_rsa` to make git happy again.

**Comment by joseph-sch** [comment]
I had the same issue and solved it by changing manually the permissions of the key file as per [this answer](https://superuser.com/a/1296046) to the question [Windows SSH: Permissions for 'private-key' are too open](https://superuser.com/questions/1296024/windows-ssh-permissions-for-private-key-are-too-open) on Super User:
 * Locate the file in Windows Explorer, right-click on it then select "Properties". Navigate to the "Security" tab and click "Advanced"
 * Make sure you are the owner or change the owner to yourself, disable inheritance (at bottom of window) then delete all permissions other than yours. Make sure you keep "Full control" and save.

**Comment by steveward** [comment]
I'm going to close this since we have some further investigation going on in #16875.

**Comment by kpboyle25** [comment]
I had this same issue. Posting in case someone else finds this useful.
+ Originally was using Desktop without GitBash, then started using GitBash and Desktop interchangedly. 
+ GitBash was able to fetch/pull/push/checkout fine and had no issues, but Desktop would throw "Authentication Failed" every time. 

My solution was found through #16875:
> but GitHub Desktop should abort the operation, report an error and tell me to move my SSH key to a safer location or to **not use the system OpenSSH but the one from git bash**.

In GitHub Desktop:
1. Try logging out and back in again just in case.
2. Go to Options \> Advanced \> Network and credentials 
3. Uncheck "Use system OpenSSH (recommended)"

![Capture](https://github.com/user-attachments/assets/ac03c4cc-fa33-469c-ac86-22445a866065)

As per the article [Generating a new SSH key and adding it to the ssh-agent](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent):
>If you have [GitHub Desktop](https://desktop.github.com/) installed, you can use it to clone repositories and not deal with SSH keys.

If you have generated ssh keys then it appears you do not need the **System** OpenSSH.
