### ISSUE TITLE
Error when amending last commit

### ISSUE THREAD

**Issue by erickriva** [desktop/desktop#14438]
### The problem

I was triyng to amend a commit, it had only title and I've added a description to it, and when I've clicked 'Amend last commit' button this error happened.

### Release version

2.9.16-beta1

### Operating system

Windows 11

### Log files

[2022-04-22.desktop.beta.log](https://github.com/desktop/desktop/files/8541890/2022-04-22.desktop.beta.log)

### Screenshots

![image](https://user-images.githubusercontent.com/2746558/164737230-2c6c9a5e-8277-42e7-b39f-f231031b53b8.png)

**Comment by steveward** [comment]
@erickriva it looks like there is an issue with a pre-commit hook in your repository. Some users have had success with [this workaround](https://github.com/desktop/desktop/issues/10999#issuecomment-866353129). Let us know if that helps!

**Comment by erickriva** [comment]
I got back to last stable version (2.9.15) and everything is working fine around here.
I appreciate your answer.
