### ISSUE TITLE
Cannot pull origin 

### ISSUE THREAD

**Issue by gesnkb** [desktop/desktop#14430]
### The problem

remote: Enumerating objects: 6, done.        
remote: Counting objects: 100% (4/4), done.        
remote: Total 6 (delta 4), reused 4 (delta 4), pack-reused 2        
fatal: bad object refs/remotes/upstream/main
error: https://github.com/gesnkb/Captstone did not send all necessary objects

### Release version

latest

### Operating system

Windows 11

### Steps to reproduce the behavior

Click "pull origin" and then I receive that error 

### Screenshots

![Screenshot (182)](https://user-images.githubusercontent.com/54376836/164514907-e3084549-e0d9-4674-a767-ff09db4baa16.png)

**Comment by steveward** [comment]
Thanks for the report @gesnkb. 

Can you share the output of these commands from within the repository? (Repository > Open in `<command_line>`)

- `git remote -v`
- `git fsck`
- `cat .git/refs/remotes/upstream/main`

**Comment by gesnkb** [comment]
Hi Steve,

I have attached a screenshot of the outputs of those commands.

Thank you,
Grace Sanders
________________________________

**Comment by steveward** [comment]
@gesnkb unfortunately you will need to upload images directly in this issue -- attaching them via email does not work.

**Comment by gesnkb** [comment]
![Screenshot (183)](https://user-images.githubusercontent.com/54376836/164544252-2f4a186a-bcd9-4891-aaf5-11347bd2a590.png)

**Comment by tsvetilian-ty** [comment]
@gesnkb you're using a "Command prompt" and cat is not a valid command. Instead, you can open Power Shell to execute the command (`cat` can be used in power shell). If you want to use CMD you should use `type`. 

Example for CMD:  `type .git\refs\remotes\upstream\main`

**Comment by gesnkb** [comment]
![Screenshot (186)](https://user-images.githubusercontent.com/54376836/164561375-c601c3a4-bf1a-42d7-b716-10fc30000333.png)

I get an empty return using "type"

**Comment by gesnkb** [comment]
I have been still trying to fix this broken connection, and have been wondering if this explains the issues further? I used the git branch -r command, and it seems there's an error with my branches?
![Screenshot (193)](https://user-images.githubusercontent.com/54376836/165186127-e950a26a-36bf-4564-b2f4-3678cd728760.png)

**Comment by steveward** [comment]
@gesnkb you should be able to resolve this by running the following commands:

`rm .git/refs/remotes/upstream/main` 
`git fetch upstream` 

Let me know if that helps.

**Comment by steveward** [comment]
@gesnkb I'm going to close this out, let me know if you are still having problems.

**Comment by RANJEETSAHOO** [comment]
$ git pull origin suraj
remote: Enumerating objects: 1070, done.
remote: Counting objects: 100% (765/765), done.
remote: Compressing objects: 100% (285/285), done.
remote: Total 587 (delta 293), reused 468 (delta 179), pack-reused 0
Receiving objects: 100% (587/587), 171.92 KiB | 451.00 KiB/s, done.
Resolving deltas: 100% (293/293), completed with 80 local objects.
fatal: bad object refs/remotes/origin/Ranjeet
error: https://github.com/InnoverenIT-Pvt-Ltd/hrweb.git did not send all necessary objects

**Comment by bowles123** [comment]
> @gesnkb you should be able to resolve this by running the following commands:
> 
> `rm .git/refs/remotes/upstream/main` `git fetch upstream`
> 
> Let me know if that helps.

THANK YOU!! Tried so many different things and I finally found this and it's what did the trick. Had a bad branch our something that was fudging with things so I couldn't pull and such.
