### ISSUE TITLE
 "You have divergent branches and need to specify how to reconcile them."

### ISSUE THREAD

**Issue by RedCheese** [desktop/desktop#14431]
### The problem

I keep´getting this issue all of the sudden. 

hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.

I read at anwsers for it to explain but i didn't understood a single thing. I guess im not versed at Github lingo. Going to attach the screenshot for easier udnerstanding

### Release version

Version 2.9.15

### Operating system

Windows 10

### Screenshots

![tmnc](https://user-images.githubusercontent.com/44277044/164540951-cadef7be-5b07-4ad8-9bba-10b817663599.PNG)

**Comment by tsvetilian-ty** [comment]
@RedCheese check out this comment: https://github.com/desktop/desktop/issues/14423#issuecomment-1105607066

**Comment by RedCheese** [comment]
> @RedCheese check out this comment: [#14423 (comment)](https://github.com/desktop/desktop/issues/14423#issuecomment-1105607066)

Sorry but i still didnt understand. Where do i input those changes in the app? is not working in the console so im confused.

**Comment by carriontrooper** [comment]
also having this problem, how do I make those changes? There isn't any newbie-friendly guide online, I checked.

**Comment by pavelhoral** [comment]
This should be available configuration inside Options next to committer's name/mail, ideally with default being `ff = true`. The precedent of editing global `.gitconfig` is already there:

![image](https://user-images.githubusercontent.com/2012726/164734492-ebd4e037-293d-413d-8ef9-54c024217aac.png)

The error is pretty confusing to people that are not that familiar with git and making people go edit "some configuration file" (`~/.gitconfig`) is not quite an acceptable solution (note, that if you are using purely GitHub Desktop you won't have `git` CLI so average user won't even know how to fix this).

**Comment by tidy-dev** [comment]
We are looking at a more ideal solution for this through Desktop, but in the mean time. For those unfamiliar with using the Command Line Interface (CLI). 

1. From GitHub Desktop, you can press Ctrl + `  (Also available from the "Repository" main menu as "Open in [Your set terminal]"). This should open up a CLI. 

2. There you can type:
`git config --global  pull.ff true` (or any of the other options specified in the error hints).

3. Now when you attempt to pull it will use that configuration and allow you to continue.

There is the possibility that because you do not use the CLI, you may need to [download and install git](https://git-scm.com/downloads) for this to work.

Some explanation of choice above if interested:
I suggested `pull.ff true` simply because it attempts to fast forward your branch to be up to date with your remote before applying your local commits and if not it will preform a merge from the remote to your local branch. [Read docs here](https://git-scm.com/docs/git-pull). Typically when you pull a branch, add commits, and push. It is in the order assuming your local is up to date with remote. By merging when fast forwarding is not possible, you will see a merge commit informing you of how it was handled. (The other options are to rebase or always merge, many new users find rebase to be less intuitive, but really accomplishes the same thing)

I added the --global flag so that your choice will apply to all your repos and you won't see this error message again. Simply omit this if you want a different behavior per repository.

**Comment by ghost** [comment]
thank

> We are looking at a more ideal solution for this through Desktop, but in the mean time. For those unfamiliar with using the Command Line Interface (CLI).
> 
> 1. From GitHub Desktop, you can press Ctrl + `  (Also available from the "Repository" main menu as "Open in [Your set terminal]"). This should open up a CLI.
> 2. There you can type:
>    `git config --global  pull.ff true` (or any of the other options specified in the error hints).
> 3. Now when you attempt to pull it will use that configuration and allow you to continue.
> 
> There is the possibility that because you do not use the CLI, you may need to [download and install git](https://git-scm.com/downloads) for this to work.
> 
> Some explanation of choice above if interested: I suggested `pull.ff true` simply because it attempts to fast forward your branch to be up to date with your remote before applying your local commits and if not it will preform a merge from the remote to your local branch. [Read docs here](https://git-scm.com/docs/git-pull). Typically when you pull a branch, add commits, and push. It is in the order assuming your local is up to date with remote. By merging when fast forwarding is not possible, you will see a merge commit informing you of how it was handled. (The other options are to rebase or always merge, many new users find rebase to be less intuitive, but really accomplishes the same thing)
> 
> I added the --global flag so that your choice will apply to all your repos and you won't see this error message again. Simply omit this if you want a different behavior per repository.
thank!

**Comment by bluetata** [comment]
> We are looking at a more ideal solution for this through Desktop, but in the mean time. For those unfamiliar with using the Command Line Interface (CLI).
> 
> 1. From GitHub Desktop, you can press Ctrl + `  (Also available from the "Repository" main menu as "Open in [Your set terminal]"). This should open up a CLI.
> 2. There you can type:
>    `git config --global  pull.ff true` (or any of the other options specified in the error hints).
> 3. Now when you attempt to pull it will use that configuration and allow you to continue.
> 
> There is the possibility that because you do not use the CLI, you may need to [download and install git](https://git-scm.com/downloads) for this to work.
> 
> Some explanation of choice above if interested: I suggested `pull.ff true` simply because it attempts to fast forward your branch to be up to date with your remote before applying your local commits and if not it will preform a merge from the remote to your local branch. [Read docs here](https://git-scm.com/docs/git-pull). Typically when you pull a branch, add commits, and push. It is in the order assuming your local is up to date with remote. By merging when fast forwarding is not possible, you will see a merge commit informing you of how it was handled. (The other options are to rebase or always merge, many new users find rebase to be less intuitive, but really accomplishes the same thing)
> 
> I added the --global flag so that your choice will apply to all your repos and you won't see this error message again. Simply omit this if you want a different behavior per repository.

thank you it's work for me!

**Comment by RedCheese** [comment]
thank you. I think that did the trick indeed

**Comment by PhilippSPOTTERON** [comment]
+1

**Comment by pavanhg** [comment]
> We are looking at a more ideal solution for this through Desktop, but in the mean time. For those unfamiliar with using the Command Line Interface (CLI).
> 
> 1. From GitHub Desktop, you can press Ctrl + `  (Also available from the "Repository" main menu as "Open in [Your set terminal]"). This should open up a CLI.
> 2. There you can type:
>    `git config --global  pull.ff true` (or any of the other options specified in the error hints).
> 3. Now when you attempt to pull it will use that configuration and allow you to continue.
> 
> There is the possibility that because you do not use the CLI, you may need to [download and install git](https://git-scm.com/downloads) for this to work.
> 
> Some explanation of choice above if interested: I suggested `pull.ff true` simply because it attempts to fast forward your branch to be up to date with your remote before applying your local commits and if not it will preform a merge from the remote to your local branch. [Read docs here](https://git-scm.com/docs/git-pull). Typically when you pull a branch, add commits, and push. It is in the order assuming your local is up to date with remote. By merging when fast forwarding is not possible, you will see a merge commit informing you of how it was handled. (The other options are to rebase or always merge, many new users find rebase to be less intuitive, but really accomplishes the same thing)
> 
> I added the --global flag so that your choice will apply to all your repos and you won't see this error message again. Simply omit this if you want a different behavior per repository.

You Saved me a lot f time :) +1

**Comment by abedputra** [comment]
Thank you 

> We are looking at a more ideal solution for this through Desktop, but in the mean time. For those unfamiliar with using the Command Line Interface (CLI).
> 
> 1. From GitHub Desktop, you can press Ctrl + `  (Also available from the "Repository" main menu as "Open in [Your set terminal]"). This should open up a CLI.
> 2. There you can type:
>    `git config --global  pull.ff true` (or any of the other options specified in the error hints).
> 3. Now when you attempt to pull it will use that configuration and allow you to continue.
> 
> There is the possibility that because you do not use the CLI, you may need to [download and install git](https://git-scm.com/downloads) for this to work.
> 
> Some explanation of choice above if interested: I suggested `pull.ff true` simply because it attempts to fast forward your branch to be up to date with your remote before applying your local commits and if not it will preform a merge from the remote to your local branch. [Read docs here](https://git-scm.com/docs/git-pull). Typically when you pull a branch, add commits, and push. It is in the order assuming your local is up to date with remote. By merging when fast forwarding is not possible, you will see a merge commit informing you of how it was handled. (The other options are to rebase or always merge, many new users find rebase to be less intuitive, but really accomplishes the same thing)
> 
> I added the --global flag so that your choice will apply to all your repos and you won't see this error message again. Simply omit this if you want a different behavior per repository.

Thanks a lot

**Comment by tech-doctor** [comment]
> We are looking at a more ideal solution for this through Desktop, but in the mean time. For those unfamiliar with using the Command Line Interface (CLI).
> 
> 1. From GitHub Desktop, you can press Ctrl + `  (Also available from the "Repository" main menu as "Open in [Your set terminal]"). This should open up a CLI.
> 2. There you can type:
>    `git config --global  pull.ff true` (or any of the other options specified in the error hints).
> 3. Now when you attempt to pull it will use that configuration and allow you to continue.
> 
> There is the possibility that because you do not use the CLI, you may need to [download and install git](https://git-scm.com/downloads) for this to work.
> 
> Some explanation of choice above if interested: I suggested `pull.ff true` simply because it attempts to fast forward your branch to be up to date with your remote before applying your local commits and if not it will preform a merge from the remote to your local branch. [Read docs here](https://git-scm.com/docs/git-pull). Typically when you pull a branch, add commits, and push. It is in the order assuming your local is up to date with remote. By merging when fast forwarding is not possible, you will see a merge commit informing you of how it was handled. (The other options are to rebase or always merge, many new users find rebase to be less intuitive, but really accomplishes the same thing)
> 
> I added the --global flag so that your choice will apply to all your repos and you won't see this error message again. Simply omit this if you want a different behavior per repository.

Thanks, this works for me.

**Comment by rahulmanas** [comment]
This `git config --global pull.ff true` worked for me too. Thanks..

**Comment by kunal-chhabra-6970** [comment]
> 2\. git config --global  pull.ff true

Thanks a lot !

**Comment by koushikaccionlabs** [comment]
`git config --global  pull.ff true` This is working as charm. Thanks a lot.

**Comment by sheetalj2205** [comment]
> `git config --global pull.ff true` This is working as charm. Thanks a lot.

what to do after this? I want to push my code

**Comment by digital-marketing-engineer** [comment]
What I usually did:

1. Save your current work
1. Switch to the branch you want to merge into
1. Merge the other branch
1. Resolve conflicts
1. Stage the resolved changes
1. Commit the merge
1. Push the changes

EDIT: I asked the ChatGPT about this, and it aligns with what usually I did, so I use it for clarity of my experience. Edited, so it will not like comment from robot.

**Comment by ultracodez** [comment]
> Wha I usually did:
> 
> 1. Save your current work: Before making any changes, it's important to save your current work. Commit any pending changes or stash them using git stash so that you can easily come back to them later if needed.
> 2. Switch to the branch you want to merge into: Determine which branch you want to merge the changes into. For example, if you have a branch called featureA and want to merge it into main, switch to the main branch using git checkout main.
> 3. Merge the other branch: Once you're on the branch you want to merge into, use the git merge command followed by the branch name you want to merge. For example, to merge featureA branch into main, run git merge featureA.
> 4. Resolve conflicts: Git may encounter conflicts during the merge if there are conflicting changes in the files being merged. When conflicts occur, Git will mark the conflicting sections in the affected files. Open those files and manually resolve the conflicts by choosing which changes to keep or modifying the content as necessary.
> 5. Stage the resolved changes: After resolving the conflicts, use git add to stage the modified files. For example, if you resolved conflicts in a file called myfile.txt, run git add myfile.txt.
> 6. Commit the merge: Once you have resolved all conflicts and staged the changes, commit the merge using git commit. Git will automatically generate a commit message for the merge. You can modify it if needed or use the default message.
> 7. Push the changes: Finally, when you have merged all the branches and resolved any conflicts, push the changes to the remote repository using git push. This will update the remote branch with the merged changes.

ChatGPT?

**Comment by digital-marketing-engineer** [comment]
Yes, it is correct.
Thanks for pointing out.
It is aligned with what I usually did, so I use it as it helps for clarity.
I will modify it so it will not like robot comment.

**Comment by vadlani9** [comment]
`git config --global  pull.ff true` worked for me. thank you

**Comment by Jalalnx** [comment]
worked for me just fine . thank you

**Comment by Hasratmucher** [comment]
Oky

**Comment by Sabbir345** [comment]
`git config --global pull.ff true` worked for me. thank you

**Comment by vijayboopathirajan** [comment]
> We are looking at a more ideal solution for this through Desktop, but in the mean time. For those unfamiliar with using the Command Line Interface (CLI).
> 
> 1. From GitHub Desktop, you can press Ctrl + `  (Also available from the "Repository" main menu as "Open in [Your set terminal]"). This should open up a CLI.
> 2. There you can type:
>    `git config --global  pull.ff true` (or any of the other options specified in the error hints).
> 3. Now when you attempt to pull it will use that configuration and allow you to continue.
> 
> There is the possibility that because you do not use the CLI, you may need to [download and install git](https://git-scm.com/downloads) for this to work.
> 
> Some explanation of choice above if interested: I suggested `pull.ff true` simply because it attempts to fast forward your branch to be up to date with your remote before applying your local commits and if not it will preform a merge from the remote to your local branch. [Read docs here](https://git-scm.com/docs/git-pull). Typically when you pull a branch, add commits, and push. It is in the order assuming your local is up to date with remote. By merging when fast forwarding is not possible, you will see a merge commit informing you of how it was handled. (The other options are to rebase or always merge, many new users find rebase to be less intuitive, but really accomplishes the same thing)
> 
> I added the --global flag so that your choice will apply to all your repos and you won't see this error message again. Simply omit this if you want a different behavior per repository.

Thanks. It worked and the explanation was nice.

**Comment by YEL-59** [comment]
> 2\. git config --global  pull.ff true

thank you a lot you save my day the command git config --global  pull.ff true is perfectly working

**Comment by FernandaKelly** [comment]
> This `git config --global pull.ff true` worked for me too. Thanks..

This git config --global pull.ff true worked for me too. Thanks a lot for your explication.

**Comment by darshanshethiya** [comment]
> ere is the possibility that because you do not use the CLI, you may

Thanks a lot, You have saved my time

**Comment by Subritt** [comment]
> We are looking at a more ideal solution for this through Desktop, but in the mean time. For those unfamiliar with using the Command Line Interface (CLI).
> 
> 1. From GitHub Desktop, you can press Ctrl + `  (Also available from the "Repository" main menu as "Open in [Your set terminal]"). This should open up a CLI.
> 2. There you can type:
>    `git config --global  pull.ff true` (or any of the other options specified in the error hints).
> 3. Now when you attempt to pull it will use that configuration and allow you to continue.
> 
> There is the possibility that because you do not use the CLI, you may need to [download and install git](https://git-scm.com/downloads) for this to work.
> 
> Some explanation of choice above if interested: I suggested `pull.ff true` simply because it attempts to fast forward your branch to be up to date with your remote before applying your local commits and if not it will preform a merge from the remote to your local branch. [Read docs here](https://git-scm.com/docs/git-pull). Typically when you pull a branch, add commits, and push. It is in the order assuming your local is up to date with remote. By merging when fast forwarding is not possible, you will see a merge commit informing you of how it was handled. (The other options are to rebase or always merge, many new users find rebase to be less intuitive, but really accomplishes the same thing)
> 
> I added the --global flag so that your choice will apply to all your repos and you won't see this error message again. Simply omit this if you want a different behavior per repository.

If fast forward is not working the you can try rebase. If even after committing it is asking you to commit or stash then you can use
- `git stash` to temporarily save and later reapply them.
- `git stash apply` after `git pull --rebase` to apply the stashed changes.

**Comment by RobinHossain** [comment]
> `git config --global pull.ff true`

It worked for me too. Thanks!

**Comment by webcat12345** [comment]
Worked for me too. Thanks!

**Comment by Probatio-Diabolica** [comment]
It WORKED THANKS!! 
It works for linux too

**Comment by redflitzi** [comment]
I do not understand.
Having this error also now, after pausing for three weeks with my work.

I am generally working in a Codespace with VSCode in the browser.
In the meantime, I did some changes directly in GitHub, always edited and committed directly on the Github website editor.
Now I am working again in codespace.
I have only one branch, main, which I am working directly on (for now). There should be no divergent branches.

So I presume I cannot install Github Desktop in my codespace.

What to do now? I feel I have to get all the "online" changes back into codespace first. But how?
Thank you very much.

**Comment by eduefl** [comment]
> I suggested `pull.ff true` simply because it attempts to fast forward your branch to be up to date with your remote before applying your local commits and if not it will preform a merge from the remote to your local branch.

thanks again it still works

**Comment by loglinn05** [comment]
> We are looking at a more ideal solution for this through Desktop, but in the mean time. For those unfamiliar with using the Command Line Interface (CLI).
> 
> 1. From GitHub Desktop, you can press Ctrl + `  (Also available from the "Repository" main menu as "Open in [Your set terminal]"). This should open up a CLI.
> 2. There you can type:
>    `git config --global  pull.ff true` (or any of the other options specified in the error hints).
> 3. Now when you attempt to pull it will use that configuration and allow you to continue.
> 
> There is the possibility that because you do not use the CLI, you may need to [download and install git](https://git-scm.com/downloads) for this to work.
> 
> Some explanation of choice above if interested: I suggested `pull.ff true` simply because it attempts to fast forward your branch to be up to date with your remote before applying your local commits and if not it will preform a merge from the remote to your local branch. [Read docs here](https://git-scm.com/docs/git-pull). Typically when you pull a branch, add commits, and push. It is in the order assuming your local is up to date with remote. By merging when fast forwarding is not possible, you will see a merge commit informing you of how it was handled. (The other options are to rebase or always merge, many new users find rebase to be less intuitive, but really accomplishes the same thing)
> 
> I added the --global flag so that your choice will apply to all your repos and you won't see this error message again. Simply omit this if you want a different behavior per repository.

Thank you very much! This solutions has helped me too!
