### ISSUE TITLE
SSH Authentication Failing for Private Repository

### ISSUE THREAD

**Issue by haywoodIII** [desktop/desktop#14446]
### The problem

2.9.15 seems to have an issue with SSH authentication. Working fine on 2.9.14. It's returning the auth failed modal. 

### Release version

2.9.15

### Operating system

Windows

### Steps to reproduce the behavior

1. Click Fetch origin tab
2. Authentication failed Modal displayed

### Screenshots

![image](https://user-images.githubusercontent.com/38250060/165001169-01f4dc27-1e09-41f8-9390-751ce7511d5e.png)

![image](https://user-images.githubusercontent.com/38250060/165001086-cf57adfd-c4d2-47ec-8e2d-8d074c27644b.png)

**Comment by steveward** [comment]
Thanks for the report @haywoodIII. I just tested out SSH on both macOS and Windows and was unable to reproduce any issues. I did generate a new key on Windows, since my VM did not have SSH set up. I'm assuming `ssh -v git@github.com` from the command line works without issue as well?

**Comment by haywoodIII** [comment]
I'm running against a locally hosted git server running on a linux box and I am able to ssh successfully to that server from a terminal (I'm using git bash). 

Ran "ssh git@10.255... -vvvv" and didn't see anything interesting in the logs. Again, working fine on the previous version of github desktop.

**Comment by steveward** [comment]
@haywoodIII are you still having issues with SSH? We did update Git, but we haven't had any other reports of SSH support breaking between versions. Are you using OpenSSH in GitHub Desktop? You can check by going to `File` > `Options` > `Advanced`.

**Comment by haywoodIII** [comment]
@steveward Thanks for the insight on the git update, that helped me track down the issue. 

I updated git.exe and was able to reproduce the error I saw in the github desktop log. Ran ssh -vv <user>@<server> and had the interesting bit of logging: 
**SSH-RSA key rejected with message "no mutual signature algorithm"**

Found that [OpenSSH 8.8 ](https://www.openssh.com/txt/release-8.8) or newer disables RSA signatures using the SHA-1 hash algorithm by default. Checked the version bundled with GitHubDesktop(its git version) with
"\GitHubDesktop\app-3.0.0\resources\app\git\usr\bin\ssh.exe -V" and it was OpenSSH_8.8p1

Regenerated my keys with ED25519 algorithm and added pub key to the server with the commands using git bash on windows:

ssh-keygen -t ed25519 -C "your_email@example.com"
eval ssh-agent`
ssh-add -k ~/.ssh/id_ed25519 
ssh-copy-id -i ~/.ssh/id_ed25519.pub <user>@<server>

Regenerating the key with the ED25519 algorithm fixed it. 

Thanks again. Can close.

**Comment by steveward** [comment]
Glad to hear things are working now!
