### ISSUE TITLE
Ability to switch between two Github accounts in the desktop app

### ISSUE THREAD

**Issue by shaunmeechan-abertay** [desktop/desktop#14448]
### The feature request

I often have to switch between my personal Github account and my Github student account. I can do this by signing out of the app and then signing back in using whatever account is logged in on the web. While this works it's really quite tedious and requires me to remember (or check) what account I'm logged into on the web.

### Proposed solution

I think it would be useful if there was a drop-down menu or something similar in the accounts section of the settings menu. A user could pick an account from the drop-down menu then logged in account in the app would change (personal account -> student and vice versa).

**Comment by tidy-dev** [comment]
Thanks for the feedback @shaunmeechan-abertay. We are tracking support for multiple accounts in https://github.com/desktop/desktop/issues/3707. I'm going to add your feedback there.
