### ISSUE TITLE
Push to origin hangs up when repo set as private

### ISSUE THREAD

**Issue by drelich** [desktop/desktop#14456]
### The problem

Was unable to do initial commit, GitHub Desktop app hung up on me when doing the push to origin. Turned out, it was because the repo was set as private. Once I set it as public, the initial commit went through just fine. Seems like setting the repo back to private after the initial commit works okay, was able to push git ignore file a short while ago. 

### Release version

Version 2.9.15 (arm64)

### Operating system

macOS Monterey - 12.3.1 (21E258)

**Comment by sergiou87** [comment]
Hey @drelich! 👋 

Is this still happening to you? I just tried with a private repository cloned both with HTTPS and SSH and in all cases I could push, pull and all just fine.

**Comment by drelich** [comment]
Hey @sergiou87 !

How big was your initial commit? Did you commit using the GitHub for desktop app or some other way?

I just updated the GitHub for Desktop app to v. 3.0.0 (arm64), created a private test repo via GitHub page, and then used the desktop app to clone it onto my Mac, added a couple hundred files to the directory and did the first push. It seems stuck again. 

![Screenshot 2022-04-26 at 17 35 37](https://user-images.githubusercontent.com/24796898/165338342-594b45d6-a74f-4109-9a63-62531a0b8604.png)

So I closed the app, changed the visibility of the testrepo, fired up the app and... interestingly enough, with the v. 3.0.0 (arm64) version and the testrepo set to public, it gets stuck as well? Previous version at least worked with public repos, haha.

**Comment by drelich** [comment]
Okay, restarting the app and pushing the initial commit to the public repo worked now...

**Comment by sergiou87** [comment]
I'm glad it worked now! Maybe the app was in a weird state after the update 😅

**Comment by drelich** [comment]
It didn't. It only worked for the public repo but the private repo initial push still doesn't.

**Comment by sergiou87** [comment]
Oh, sorry, I misunderstood it 🤦‍♂️ 

> How big was your initial commit? Did you commit using the GitHub for desktop app or some other way?

It was just a small commit created from GitHub Desktop. Is that different from what you did?

**Comment by drelich** [comment]
My initial commit had hundreds of files across about a dozen directories.

**Comment by estin92** [comment]
<img width="316" alt="Screenshot 2022-05-17 at 08 24 20" src="https://user-images.githubusercontent.com/11060245/168753395-75f4c31d-a0ae-4364-8596-2d7c91077ab7.png">

I can confirm this is an issue being experienced here too. Changing networks weirdly seems to sort the issue, and it's not all of the time. But sporadically hangs when pushing to the remote origin.

**Comment by D300** [comment]
>  Changing networks weirdly seems to sort the issue, and it's not all of the time. But sporadically hangs when pushing to the remote origin.

thanks a lot for mentioning the "changing network move" also fixed it for me for now

**Comment by mika4president** [comment]
Same here, when repo is set to private it fails. Changing the visibility to public, retry the push and it works again.

**Comment by KiranJodhani** [comment]
I had same issue. I managed to fix by logout in both browser and Desktop app and login again

**Comment by usamamuneerchaudhary** [comment]
<img width="294" alt="Screenshot 2023-01-26 at 15 40 50" src="https://user-images.githubusercontent.com/24513380/214880056-a10df7b0-bbdf-4d73-a6bc-ab0fd4004386.png">

Still having the issue

**Comment by estin92** [comment]
For anybody still having this issue, switching from https to ssh seems to do the trick.

In the `~/.git/config` file, change the repository details to SSH:

Default behaviour:
```
[remote "origin"]
	url = https://github.com/estin92/repository-name.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```

Update to:
```
[remote "origin"]
	url = git@github.com:estin92/repository-name.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```

This has worked better for me than dropping between network connections.

**Comment by estin92** [comment]
For anybody still having this issue, switching from https to ssh seems to do the trick.

In the `~/.git/config` file, change the repository details to SSH:

Default config from GitHub Desktop:
```
[remote "origin"]
	url = https://github.com/estin92/repository-name.git
	...
```

Update to:
```
[remote "origin"]
	url = git@github.com:estin92/repository-name.git
	...
```

This has worked better for me than dropping between network connections.
