### ISSUE TITLE
Use true immutable data structures

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#1445]
We're using `Readonly*` variants in a lot of spots, but they aren't truly immutable. It's just a type level enforcement.

@niik saw a bug caused by this:

>Like, in this case we were sending the commit cache as an invalidation prop to the commit list

>That will never invalidate since we're just mutating a Map

>but making a copy of the map just to add a commit is crazytalk

>If we had true immutable shared data structures though adding to a map ought to be reasonably efficient

>In this particular scenario the solution was to not rely on the commit cache for invalidation at all but rather use the list of SHAs but we have the same issue with gitHubUsers which is a shared read-write Map

>I started down the path of converting that one to a ReadonlyMap but I'm not a huge fan of that because it too can get pretty damn large

https://facebook.github.io/immutable-js/ is probably the most popular option.

**Comment by niik** [comment]
This was a good dream but the ship has sailed. In more encouraging news we've got `ReadonlyMap` that we're leveraging here and there.
