### ISSUE TITLE
Error on Commit  (./node_modules/pre-commit/hook: line 49: : command not found)

### ISSUE THREAD

**Issue by danbruton-nav360** [desktop/desktop#14454]
### The problem

![image](https://user-images.githubusercontent.com/78436060/165225407-723f3b4a-8f97-43f9-b456-698a4a6c507b.png)

### Release version

Latest

### Operating system

Windows 11

### Steps to reproduce the behavior

Click "Commit to...

### Log files

[2022-04-26.desktop.production.log](https://github.com/desktop/desktop/files/8560017/2022-04-26.desktop.production.log)

**Comment by sergiou87** [comment]
Hello! Could you check what's the content of that `node_modules/pre-commit/hook` file? At least its line 49 to understand which command is not being found.

Thanks!

**Comment by danbruton-nav360** [comment]
Yes, this is the error: 
![image](https://user-images.githubusercontent.com/78436060/165434198-d8bbcde6-a64a-4201-801a-339612da8500.png)

**Comment by sergiou87** [comment]
Thank you @danbruton-nav360, but I'm looking for the contents of the `node_modules/pre-commit/hook` file.

You should be able to find that file inside of your repository folder from Explorer and open it with your favourite text editor.

**Comment by danbruton-nav360** [comment]
I'll try to attach the file.
Thanks!
[hook.txt](https://github.com/desktop/desktop/files/8578061/hook.txt)

**Comment by sergiou87** [comment]
Thank you for that! From what I see, the pre-commit hook is looking for `node` which might not be installed in your system. So you can either [install node](https://nodejs.org/) (you might need to restart your computer after that) or, if that doesn't work, just disable the pre-commit hooks which live in the `.git/hooks` folder inside your repository.

I hope that helps!
