### ISSUE TITLE
Same co-author can be displayed multiple times if they are included multiple times in the commit description

### ISSUE THREAD

**Issue by Alexejhero** [desktop/desktop#14451]
### The problem

Same co-author can be visually displayed multiple times in a commit, if they are included multiple times in the commit description

### Release version

Version 2.9.15 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

- Create a new commit and add another user as a co-author by pasting the "Co-Authored-By: NAME <EMAIL>" in the commit description multiple times
- Inspect the commit in the history tab

### Screenshots

![image](https://user-images.githubusercontent.com/32238504/165115480-26863e0f-db17-4a82-af3e-e8900c127cd3.png)

### Additional context

On GitHub, this commit will only show the co-author once.
On GitHub Desktop, the co-authors will be shown multiple times.

**Comment by steveward** [comment]
Thanks for reporting this @AlexejheroYTB. I was unable to reproduce this issue -- are you able to consistently reproduce it?
