### ISSUE TITLE
Unable to switch branch after resolve conflit on uncommited files

### ISSUE THREAD

**Issue by Justin-JHG** [desktop/desktop#14467]
### The problem

I know I can use git bash or something else to add changes to Index, e.g. git add * 
but I thought the idea of GitHub Desktop is so that there is no concept of index area and it shouldn't require another application to add changes to index

### Release version

v3.0.0

### Operating system

windows

### Steps to reproduce the behavior

1. make a change to a file and commit to current branch A
2. switch to another branch B and make different changes to the same file
3. trying to switch back to branch A again
4. Desktop will say there is a conflit need to be resolved.
5. Resolve the conflit for the file in Branch A
![image](https://user-images.githubusercontent.com/41654878/165651471-7b26e487-a713-4a7c-93c5-4c6358a7428d.png)
6. Now try to switch to Branch B

**Expected**:
 switched to branch B without error

**Actual**:
 Error saying needs to resolve index first 

![image](https://user-images.githubusercontent.com/41654878/165651597-2669ea7e-77f7-4750-b786-d70cf32a99c5.png)

### Screenshots

![image](https://user-images.githubusercontent.com/41654878/165651609-39c4686c-b5b9-453c-afe5-04a06edbb579.png)

**Comment by sergiou87** [comment]
Thank you for your report @Justin-JHG. I think this is the same as #11959 (at least the same underlying reason for it), so I'm gonna close this issue in favor of that one. Feel free to subscribe to that one if you want to get notified when we work on it!
