### ISSUE TITLE
Windows "Make everything bigger" setting causes window to overlap Taskbar

### ISSUE THREAD

**Issue by cloewen8** [desktop/desktop#14460]
### The problem

Increasing the Windows Ease of Use, "Make everything bigger" setting to 125% on a 1920x1080 display causes the application to display overtop of the Taskbar when initially opened while maximized.

A temporary workaround is to restore and re-maximize the window.

### Release version

3.0.0 (x64)

### Operating system

Windows 10 21H2

### Steps to reproduce the behavior

1. Maximize GitHub Desktop.
2. Close the application.
3. Re-open GitHub Desktop.

**Comment by sergiou87** [comment]
Thanks for your report! This is a bug in Electron (https://github.com/electron/electron/issues/32957) that we're already tracking in https://github.com/desktop/desktop/issues/14009

I suggest you to subscribe to that issue to get updates when this bug is fixed.
