### ISSUE TITLE
Github Desktop Fails to launch after install

### ISSUE THREAD

**Issue by jimstowe01** [desktop/desktop#14464]
### The problem

I’ve tried this multiple times, installing (and uninstalling) Github desktop both as the “user” and as a local admin. Same results each time:

Failed to execute “installGlobalLFSFilter”

I’ve checked the log (which is very sparse since this is a new install). There’s nothing referencing this.

We are in an organization with very strict group policies. Not sure if that may be a factor. Other users in the same department are successfully running Github desktop.

### Release version

2.9.15

### Operating system

Windows 10

### Log files

[2022-04-26.desktop.production.log](https://github.com/desktop/desktop/files/8572921/2022-04-26.desktop.production.log)

### Screenshots

![GitHub_launch_error](https://user-images.githubusercontent.com/104222149/165541993-730c26cd-1d27-493c-b327-99c4352bf468.png)

**Comment by sergiou87** [comment]
Hi @jimstowe01! 👋 

Do you mean that right after getting that error, the app closes and you can't use it?

From what I see, `installGlobalLFSFilter` just runs `git lfs install --skip-repo` which just sets up some stuff for Git LFS globally (https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-install.1.ronn), but I can't think of any reason why that would fail.

**Comment by steveward** [comment]
@jimstowe01 as we haven't heard back from you I am going to close this issue out. Let us know if you are still having problems and we can investigate further.
