### ISSUE TITLE
Can't merge conflicts

### ISSUE THREAD

**Issue by DORGJoe** [desktop/desktop#14468]
### The problem

I am trying to confirm merge conflicts but the program's option is way below my screen to confirm. I am stuck

### Release version

 3.0.0 (x64)

### Operating system

Windows 11

### Screenshots

![Screenshot (214)](https://user-images.githubusercontent.com/68997177/165659522-91c02926-7f74-45ae-b51b-5571a3b05eaf.png)

**Comment by sergiou87** [comment]
We're very sorry about that @DORGJoe, I just submitted a PR fixing this problem in #14470

Meanwhile I can only suggest to either commit those files in smaller batches or to use the command line.

**Comment by sergiou87** [comment]
Thank you for your patience @DORGJoe , this should be fixed in 3.0.1.
