### ISSUE TITLE
Mark Fovorite Repos

### ISSUE THREAD

**Issue by konkos1** [desktop/desktop#14472]
### The feature request

It would be nice if you can mark a Repo as a favourite in the List of local Repos

### Proposed solution

Add e.g. 'Mark As Fvourite' via right-click on a Repo in the list.
Favourite Repos should be sorted at the top.

**Comment by steveward** [comment]
Thanks for the request @kkoschel. This is being tracked in https://github.com/desktop/desktop/issues/8183, but at this time we don't have any plans to work on this. This may change in the future, though. I'll reference this issue there, and feel free to leave a 👍🏻 to the original issue comment to indicate your interest in this feature.
