### ISSUE TITLE
User avatar doesn't change between commits

### ISSUE THREAD

**Issue by dario-jahnel** [desktop/desktop#14474]
### The problem

When navigating history tab user avatar gets stucked on the first picture loaded (see attached screenshots, user changes, avatar doesn't)

![image](https://user-images.githubusercontent.com/98162838/165822056-c7730999-7e93-4e33-9224-a77c0382afb7.png)
![image](https://user-images.githubusercontent.com/98162838/165822070-3b18daff-3017-4f49-9b5b-1b24f672ac6c.png)

### Release version

Version 3.0.0 (arm64)

### Operating system

macOS Monterey 12.3.1

### Steps to reproduce the behavior

1. Select a repository that has more than 1 contributor
2. Go to history tab
3. Navigate between commits and look at the avatar showed in the right panel

**Comment by sergiou87** [comment]
Hi @dario-jahnel 👋 

I cannot reproduce that behavior using, for example, this repository:
![image](https://user-images.githubusercontent.com/1083228/165911747-e1285cc0-90ff-400f-b9e2-5294561fa598.png)

Is it possible that both of those commits have the same email even if the user name is different?

**Comment by dario-jahnel** [comment]
Hi @sergiou87!
Checked it again and it only happens in one repository, inside a feature branch.. strange!

I was referring to the right panel, the one that shows the details of the commit.
Each person of our team has a unique email account

left panel:
![image](https://user-images.githubusercontent.com/98162838/165941267-a205a25e-f1d3-44bd-922c-9283815d8c98.png)

right panel:
![image](https://user-images.githubusercontent.com/98162838/165941300-86688cfb-a1bf-45d1-bb20-dae6d3f514ee.png)
![image](https://user-images.githubusercontent.com/98162838/165941313-2e64a5ac-665a-43dc-8ac4-5df6e142479c.png)

**Comment by sergiou87** [comment]
Interesting! If you hover over those avatars, do they have the correct email address and different from each other?

![image](https://user-images.githubusercontent.com/1083228/165953308-f543bf94-cc42-49cb-bd8f-af686a888770.png)

**Comment by dario-jahnel** [comment]
it shows the email address of the account that has the picture (using one piece characters if zoro made the commit it shows the picture and email of luffy)

**Comment by sergiou87** [comment]
Well, first of all, 10/10 to you for the One Piece references ❤️ 

And second, 0/10 to Desktop for doing something that crazy 🤔 

So if I understand it correctly…
1. The left panel (History with list of commits) everything is correct: avatar, name, and data in the tooltip when you hover over those avatars.
2. The commit description shows the wrong avatar (and wrong data in its tooltip), but the right name.

Could you run `git log --format=fuller` and see if there is anything odd there? Maybe something unexpected around the `Author` and `Commit` users
