### ISSUE TITLE
Support for linux

### ISSUE THREAD

**Issue by shvmimg** [desktop/desktop#14475]
### The feature request

The way GitHub desktop has a support for windows and macos, the request to provide GitHub dekstop support for linux too.

### Proposed solution

The way GitHub desktop has a support for windows and macos, the request to provide GitHub dekstop support for linux too.

**Comment by sergiou87** [comment]
Thanks for the issue @shvmimg . At this time there are no official builds of GitHub Desktop available for Linux, but a former developer of GitHub Desktop maintains a fork with Linux builds available for download:

https://github.com/shiftkey/desktop/releases

You can also follow along with https://github.com/desktop/desktop/issues/1525 for updates about an official Linux release.
