### ISSUE TITLE
Window size is bigger than screen

### ISSUE THREAD

**Issue by peeyushjain27** [desktop/desktop#14477]
### The problem

Dear Team,My github desktop screen is larger in size then computer screen. so I am not able to checkin the code and not getting the corners of the github

Version 2.9.15 (x64)

### Release version

Version 2.9.15 (x64)

### Operating system

windows10

**Comment by sergiou87** [comment]
Could you try the key combination Windows+Arrow Up or Windows+Arrow Left/Right to adjust the window to your screen size?

**Comment by peeyushjain27** [comment]
Hi Team,

Issue is not resolved.

[cid:478cdb07-afc4-4f13-a19a-4364278f2c0d]
________________________________

**Comment by steveward** [comment]
@peeyushjain27 have you tried using F11 to toggle fullscreen mode? Enabling/disabling fullscreen may get things working here.
