### ISSUE TITLE
The Feature tools button `Custom Action`

### ISSUE THREAD

**Issue by zhangmo8** [desktop/desktop#14483]
### The feature request

I think we can add a `Custom Action` on the tools `Branch` Menu.
Through this button, we can set some personalized commands to form some new button on the menu.

It will be like this.
When I click on it, a form appears in the pop-up box with two input boxes(**Command name[input]** and **Command code[textarea]**).

The **Command name** will be button text, such as `force push`

There will be some aliases in the Command code, such as the `{b}` is alias for a branch. Mine **Command name** is `git push origin {b} -f`,.

When I fill out the form and save it, a new button `force push` appears in my tools/Branch.

when i click the `force push` button, `{b}` is detected, the branch selection box will pop up when we click this button, it's just like the current `Merge into Current Branch`. After I choose the `dev` branch,it will execute the `git push origin dev -f`

### Proposed solution

This will enable users to customize tool commands, and more personalized tools will give users a better experience.

### Additional context

when i want contributo for the open soure repositry. i fork rep and  submit a PR. After a while, and I need to update mine fork repositry. And now i use the `tools/Branch/Rebase Current Branch`. it's worked. But this caused my newly submitted PR to produce a lot of commit that have been updated.

so i have to use the `git command` rollback and do that rebase and `git push -f`

if we can add some custom command become some button on mine `Github Desktop`, we can do some personalized action with `Github Desktop`.

These Setting can save in our Github Account.When we use the other Deivce(Maybe i upgradle mine computer). We can easily use them through `Github Desktop`.

**Comment by niik** [comment]
Hi @wegi8, thanks for the suggestion and for wanting to contribute to GitHub Desktop!

Custom actions/scripting within GitHub Desktop isn't something we're planning on adding to GitHub Desktop in the short term. While I can see the usefulness in your particular scenario but GitHub Desktop isn't a good host for running generic commands and we believe that the gain doesn't make up for the added complexity. That may change in the future but for now I'm going to close this issue out.

**Comment by PaddleStroke** [comment]
This is a bad decision imo. It's not even hard to implement and would let people with different workflow use github desktop.

I am trying github desktop now, and the missing 'rebase interactive' is a show stopper for me (see https://github.com/desktop/desktop/issues/12354).
If it was possible to add custom commands as it is possible in Git Gui, then I would just do that and keep using github desktop.

But no it is not possible.

So as it stands I'll be back to the very limited and no-darktheme git gui.

**Comment by ZakTaccardi** [comment]
this is why I use sourcetree. I can right click on a commit to do a fixup, it's awesome
