### ISSUE TITLE
Branch won't merge to Master

### ISSUE THREAD

**Issue by MissEpticx** [desktop/desktop#14485]
### The problem

Repository is for a Uni group game project. For months I have had team members use their own branches to commit and push changes to, and I will periodically merge all necessary branches into the master branch. Before doing this, I always create a Test_Merge branch based from the master branch to check for conflicts and errors. 

Today I did as normal, and the test merge went smoothly with 5 different branches (1 of which is an art branch). When I came to merge this same art branch into the master (after merging 1 other of the pre-tested branches), it keeps checking for ability to merge automatically and never comes out of this cycle, I've left it for up to an hour and still no change despite merging absolutely fine in the test merge branch. I have also occasionally received an error "RangeError: Array buffer allocation failed" when retrying, or trying with a new branch using the art branch as its base.

I don't understand why it suddenly cannot merge with any other branch (I have tested this also). I'm not massively well versed in the world of GitHub but I have managed the same system of merging for 3 months and have only recently had this issue. Nothing I do will fix it. 

### Release version

Version 3.0.0 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Go to master
2. Click "Choose a branch to Merge into Master"
3. Select NewArtBranch
4. Wait to see if Merge happens or conflicts show - does not occur each time I try.

### Log files

2022-05-01T19:41:49.748Z - error: [main] RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (node:internal/buffer:959:5)
    at createUnsafeBuffer (node:internal/buffer:1062:12)
    at allocate (node:buffer:409:10)
    at Function.allocUnsafe (node:buffer:374:10)
    at Function.concat (node:buffer:552:25)
    at ChildProcess.<anonymous> (file:///C:/Users/Colette%20Senior/AppData/Local/GitHubDesktop/app-3.0.0/resources/app/renderer.js:2:998597)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)

### Screenshots

![checking_for_merge](https://user-images.githubusercontent.com/72127844/166169120-48eb8375-9275-4b86-86f5-8056c95e91d3.jpg)
![Github Error](https://user-images.githubusercontent.com/72127844/166169121-03aeeb7b-908a-4b19-b904-4d505eadf8e4.jpg)

**Comment by niik** [comment]
Hi @MissEpticx, thanks for reaching out! There seems to be two issues here, one being that the check for "mergeability" never returns and the other being that the app crashes.

This is the first time I'm hearing of the first problem and I would love to dig into it more. The repository you're working with wouldn't happen to be public would it? So that I could try it out myself.

For the second issue it seems it's failing because it's unable to allocate enough memory (i.e. your machine, in that instance, is running low on/out of memory). That would explain why you're only seeing it occasionally.

I'm going to see if I can reproduce this locally but for my colleagues: it seems the merge-tree output in this scenario is huge which fits the bill considering @MissEpticx mentions one branch being an "art" branch so I'm imagining large binary resources. The crash is happening because the concatenation of buffers in the `close` handler in `spawnAndComplete` throws which is never caught. We should investigate a streaming approach for `merge-tree` parsing as well as a bail-out for when the mergeability check is taking too long, i.e. "this is taking a long time, merge anyway?"

@MissEpticx I'm afraid I don't have a good workaround here until we're able to make some changes to GitHub Desktop. Do you have Git installed on your machine? If not you can install it from https://git-scm.com/downloads. What GitHub Desktop would do if you clicked the merge button is simply to run the command `git merge origin/NewArtBranch`. You could do that yourself and then switch back to GitHub Desktop to resolve any conflicts.

**Comment by Quawetim** [comment]
Same thing with our private repo. While Github Desktop checking ability to merge, RAM grows from ~9GB to ~18GB (full space is 32GB), then app crashes. Same vesion, same log.

**Comment by apoosrini** [comment]
I am facing the same error when I try to "Merge into Master". But I don't face this issue with other branches.

**Comment by Albosonic** [comment]
I am having this issue, but it's not due to large commit diff, because I have merged much larger commits

**Comment by ddiazFG** [comment]
Same issue, small PR (234 new lines), `Checking for ability to merge automatically…` hung forever

**Comment by DaoudAli** [comment]
Also having similiar issue

**Comment by davidburson** [comment]
me too, small PR

**Comment by peter-hindos** [comment]
Stuck as well, small commit

**Comment by ioanam** [comment]
Same on my side, one line commit

**Comment by DavidInojosa** [comment]
Same here, small commit

**Comment by tominek** [comment]
Same here, big commit, doing a production release 🤦‍♂️

**Comment by JulioCRFilho** [comment]
Apparently github is going through some breaking, all of those comments were made just now...

**Comment by mpjmpj** [comment]
Same here - though small commit.

**Comment by Albosonic** [comment]
finally worked, took about 25 min or so

**Comment by HorydJakub** [comment]
Same here, small commit

**Comment by KevinGaleon** [comment]
> finally worked, took about 25 min or so

what did you do?

**Comment by msaini28r** [comment]
same problem, but nothing worked. logged out 3 times already.

**Comment by Mariga-M** [comment]
Same issue...I've tried logging out a couple of times

**Comment by osichan** [comment]
smth with github servers
https://www.githubstatus.com/

**Comment by Mariga-M** [comment]
Finally able to merge.... I've just waited

**Comment by sofrrivest** [comment]
I am having the Same issue.  The PR is not that big

**Comment by eeprojectmain** [comment]
Same issue, is github server down?

**Comment by i1idan** [comment]
Same issue

**Comment by aparcanapavel** [comment]
Also had this issue! check here for their statuses https://www.githubstatus.com/

**Comment by Frank-1998** [comment]
same issue

**Comment by dirkdirk** [comment]
Same issue

**Comment by eleonorazu** [comment]
Hey facing same issue, is there a solution for this?

**Comment by aptonwork-sam** [comment]
Same issue, is github server down?

**Comment by htuli-tuw** [comment]
Having the same issue

**Comment by nathanfrey-ovx** [comment]
If you go to github is says all is well 
https://www.githubstatus.com/

But if you go to the "history" is shows they are having problems.
https://www.githubstatus.com/history

Hmm...

**Comment by lolainta** [comment]
Thanks for the information provided above, I think we can do nothing but just wait for it.

**Comment by ninsuo** [comment]
Same, https://www.githubstatus.com/incidents/7txcg0j03kkg is still onging out here :)
Good luck to on-call peeps!

**Comment by SaraDonaldson** [comment]
Thanks! Same issue with a small PR between 2 branches I regularly merge

**Comment by suchakra-texada** [comment]
Same here... at least 2 of our PRs are stuck like this.

**Comment by tsoud** [comment]
I'm having this issue right now. Nothing fancy, just a simple merge with a few changes.

**Comment by DeeMcCart** [comment]
also having the problem

**Comment by Dave820SA** [comment]
Having the same problem. Do we know if it is being worked-on??

**Comment by avmk911** [comment]
Same same..

**Comment by Oscizcod** [comment]
Having the same issue. Hung for the past 45 minutes.

**Comment by Juanca0312** [comment]
Same issue

**Comment by WhiteHeadbanger** [comment]
Same problem, 110 lines :(

**Comment by albertoviciute** [comment]
Same issue

**Comment by chrisblona** [comment]
same here, had no problem 2 hours ago and now been waiting for >30'

**Comment by charlottecrnj** [comment]
Same issue

**Comment by mlacey-dig** [comment]
Same issue

**Comment by Med5KDB** [comment]
Same issue here

**Comment by sergeysportcore** [comment]
Same issue

**Comment by philcosapp** [comment]
Same issue. It s stuck from past 2 hours

**Comment by jrodriguezluna** [comment]
Same issue ;v;

**Comment by Lupesms97** [comment]
Same issue

**Comment by EmanuelRLima** [comment]
I have the same problems, https://www.githubstatus.com/history here they say they have problems

**Comment by brentglassmanfrequence** [comment]
Same issue

**Comment by wanflap** [comment]
git hub stalled on Checking for ability to merge automatically…

**Comment by ColinReinhart** [comment]
Same

**Comment by ekasaragih** [comment]
Same

**Comment by karinaLitskevich** [comment]
same issue

**Comment by ssiuwowl** [comment]
same issue... developer tool shows one of the calls to https://api.github.com/_private/browser/stats is taking forever
not sure if this is causing the issue to happen

**Comment by chrisrueger** [comment]
Same here.

**Comment by EmanuelRLima** [comment]
I just waited and it works now

**Comment by steveward** [comment]
This issue tracker is specifically for GitHub Desktop, not GitHub the website. Please check https://www.githubstatus.com/ for updates about github.com's availability and report issues to [GitHub Support](https://support.github.com/) if you continue to have problems after the incident has resolved.
