### ISSUE TITLE
problem update branch

### ISSUE THREAD

**Issue by DelnestD** [desktop/desktop#14487]
### The feature request

When i delete branch on gitlab or other, github decktop didn't actualise that

### Proposed solution

Could you add an actualise button to refresh all branch enable for the project ?

**Comment by tidy-dev** [comment]
@DelnestD Thanks for reaching out. There are two things that could be going on here.
1) If I have a branch named "foo" and I check it out locally at some point and then delete the remote branch (on gitlab or other), I will still have a reference to "foo" locally that would also require deleting. (right click on it's name in the list or select Delete from the Branch menu). This is how Git work - not unique to Desktop. :) 
2) If I did not check "foo" out and am seeing it in the branches list, that would indicate that I need run a "Fetch". See image below. The fetch button will be available on a branch that is up-to-date with the remote. (Thus if the scenario is above, you would likely see a publish button). Additionally, Desktop will automatically do this for you periodically.
![image](https://user-images.githubusercontent.com/75402236/166221868-e1f02ee0-9b80-445b-9b36-22f54f5ffa2d.png)
