### ISSUE TITLE
not being able to push origin

### ISSUE THREAD

**Issue by blumeski** [desktop/desktop#14489]
### The problem

Git Hub Desktop not being able to authenticate with github.com, and the authentication keeps failing 

### Release version

Version 3.0.0 (arm64)

### Operating system

macOS Monterey 12.3.1 

### Screenshots

<img width="1440" alt="Captura de Tela 2022-05-02 às 13 06 39" src="https://user-images.githubusercontent.com/104200198/166292783-4e0ed818-efb2-449f-b576-54cb7ccdedbd.png">

### Additional context

It does not recognize the username and password

**Comment by steveward** [comment]
@blumeski thanks for the issue. Can you verify that you are logged in by going to `GitHub Desktop` > `Preferences` > `Accounts`? If you are, try logging out and then logging back in again to see if that gets things working.

**Comment by steveward** [comment]
@blumeski as we haven't heard back from you I am going to close this issue out. Let us know if you are still having problems and we can investigate further.
