### ISSUE TITLE
Support "Fetch and Merge"

### ISSUE THREAD

**Issue by ryanxingql** [desktop/desktop#14491]
### The feature request

I fork a repository, and I want to sync my repo frequently by fetching and merging the main repo.
I can do it with the browser. But I want to do it with GitHub desktop.

### Proposed solution

Support the "fetch and merge" button at the desktop app.

**Comment by steveward** [comment]
Thanks for the issue @ryanxingql. The ability to quickly merge from upstream is being tracked in https://github.com/desktop/desktop/issues/14145.

For reference you can merge from upstream currently -- you will see the upstream branches in the branch list when selecting `Merge into current branch...`. I hope that helps!

**Comment by ryanxingql** [comment]
@steveward Thanks for your timely response.
