### ISSUE TITLE
[Linux] Repositories are cloned into an improper subdirectory

### ISSUE THREAD

**Issue by suicvne** [desktop/desktop#14494]
### The problem

Problem: Cloning a repository through GitHub desktop creates about 5 subdirectories with my username where the project is finally stored in. Cloning other repositories will sometimes create a new folder with username and place the repo in there.

Example: Cloning a repo named 'TheXTech'. 
Expected Location: `~/Documents/GitHub/username/TheXTech`
Actual Location: `~/Documents/GitHub/username/username/username/username/username/TheXTech`

Sometimes there are more folders with my username created. Sometimes there are less. 

I have also tried completely deleting all repositores and re-cloning again. I have also tried signing out and signing back into GitHub desktop. 

### Release version

2.9.3-linux1

### Operating system

Pop OS 21.10 x64, Cinnamon DM

### Steps to reproduce the behavior

1. Download and install GitHub desktop.
2. Sign into your GitHub account.
3. Clone repository
4. Check where 

### Log files

After deleting all repositories, re-opening the application, and cloning a repository:

[2022-05-03.desktop.production.log](https://github.com/desktop/desktop/files/8611371/2022-05-03.desktop.production.log)

### Screenshots

![GHDesktopPathBug](https://user-images.githubusercontent.com/861492/166478633-74fead4d-5889-4ee0-a287-01903957f2bd.png)

### Additional context

I'm really not sure why this is happening, but even just a simple option to change where the repositories are cloned to by default might help a lot with this.

**Comment by sergiou87** [comment]
@suicvne issues related to the unofficial Linux fork of GitHub Desktop can be filed here:

https://github.com/shiftkey/desktop/issues

At this time we only officially provide support for macOS and Windows.

Sorry!
