### ISSUE TITLE
Total Selected Files Number 

### ISSUE THREAD

**Issue by sabirkhalil-CM** [desktop/desktop#14497]
### The feature request

please add feature for selected file number. most time we not commit all file we select only few file but its difficult to know how many file we are select for commit  

### Proposed solution

please add feature for selected file number. most time we not commit all file we select only few file but its difficult to know how many file we are select for commit

**Comment by niik** [comment]
Hi @sabirkhalil-CM, thanks for reaching out. You can hover over the "x changed files" header in the sidebar to see the number of selected files

<img width="259" alt="image" src="https://user-images.githubusercontent.com/634063/166682561-f01fbce6-9494-4f35-91cb-28dfb60c265c.png">

Hope that helps!

**Comment by MSJemprededor** [comment]
#13

**Comment by MSJemprededor** [comment]
Muito bom
