### ISSUE TITLE
MacOS client does not recognize non-main default branch

### ISSUE THREAD

**Issue by neakor** [desktop/desktop#14505]
### The problem

We updated our default branch from `main` to `staging` in our repo, via the Settings web page. However the MacOS client still uses `main` as the default branch. Creating a new branch automatically branches off of `main`. The branch dropdown menu also incorrectly displays `main` as the default branch.

i've also tried updating `.git/config` manually:
```
[init]
	defaultBranch = staging
```
This does not solve the issue either.

### Release version

Version 3.0.0 (arm64)

### Operating system

MacOS 12.3.1

**Comment by steveward** [comment]
Thanks for the report @neakor. We are tracking this in https://github.com/desktop/desktop/issues/14266.

The quickest way to resolve this would be to clone a fresh copy of the repository.

**Comment by neakor** [comment]
> Thanks for the report @neakor. We are tracking this in #14266.
> 
> The quickest way to resolve this would be to clone a fresh copy of the repository.

Recloning worked. Thank you!
