### ISSUE TITLE
Can't get rid of files

### ISSUE THREAD

**Issue by Jbonneyi3m** [desktop/desktop#14503]
### The problem

Hello, so my issue is that I can't delete these files on my git desktop. I tried to delete all my changes once after some things went wrong so I could go back to how it was. It wouldn't delete all the files. I then tried to delete them by tracking them and it can't find them. They won't delete and I can't switch branches or do anything because of these things. I tried to ignore them which didn't really work either. I have been unchecking them in order to do anything. I don't know what to do or how to get rid of them. Any help would be greatly appreciated.

### Release version

Version 3.0.0 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

I'm not sure.
1) Update an asset in unity with dependencies. Magic Light Probes is the one that won't delete. Everything else did.
2) Try to delete changes
3) There are 2 files that  will not go away
4) Try to switch branches. It doesn't work.
5) Try to stash. It doesn't work.
6) Try to change branches and leave them on that branch. It won't work.
7) Try to delete them. It won't work
8) Try any number of ways to get rid of them with no success. Be unable to change branches or do much of anything.
9) It will switch if you bring them with you sometimes but I don't want to mess up another branch with them.

### Log files

[2022-04-28.desktop.production.log](https://github.com/desktop/desktop/files/8628019/2022-04-28.desktop.production.log)

### Screenshots

![GitHubDesktop_aSES2R7EYP](https://user-images.githubusercontent.com/102617335/166843347-957ca4cc-ef7f-46be-8cac-e8812cc51127.png)
![GitHubDesktop_IRw6TVfXGm](https://user-images.githubusercontent.com/102617335/166843361-019551ea-48dc-4ca9-bab0-f8701f093aef.png)
![GitHubDesktop_rRdU8HcEvj](https://user-images.githubusercontent.com/102617335/166843364-18fb04c2-6676-4d76-ba79-7119a3e12b58.png)
![GitHubDesktop_pMFUXehd8q](https://user-images.githubusercontent.com/102617335/166843368-b682954c-4b37-4cd6-a058-46c8945a0c03.png)
![GitHubDesktop_GBg6S7QNDx](https://user-images.githubusercontent.com/102617335/166843372-80e6d9c1-992d-4b64-b7c3-30bc173b72fa.png)
![GitHubDesktop_Yq9ATsoQ3l](https://user-images.githubusercontent.com/102617335/166843381-05f9c422-ff37-4665-a885-9e51d97e5d26.png)

**Comment by steveward** [comment]
@Jbonneyi3m thanks for the issue. I'm seeing a long paths issue -- you can try setting Git to allow longpaths to see if that helps. To do that you can run this command:

`git config --global core.longpaths true`

Let me know if that helps.

**Comment by Jbonneyi3m** [comment]
Hello,

That did work. Thank you very much!

**Comment by steveward** [comment]
Glad to hear that got things working!
