### ISSUE TITLE
Virtual groups for cloned repositories

### ISSUE THREAD

**Issue by Faq** [desktop/desktop#14500]
### The feature request

Working on lot of projects and having lot of repositories in any of project makes a bit confusing to find all related repositories.

### Proposed solution

Would be nice to have:
+ a possibility to create virtual group(folder) in repository list with freely chosen name(possible to rename). Where can move or assign cloned repositories to it or in it.
+ or even better in cloning process to point in what virtual group it will go in.

**Comment by steveward** [comment]
Thanks for the feedback @Faq. See [this comment](https://github.com/desktop/desktop/issues/10201#issuecomment-658693653) for more information about why we do not have plans to implement repository grouping at this time. 

One workaround is to use the repository alias feature and then use that to filter by a specific alias prefix. I hope that helps.
