### ISSUE TITLE
Cloning to an empty folder fails because "Directory not empty"

### ISSUE THREAD

**Issue by FrankOVD** [desktop/desktop#14501]
### The problem

GitHub Desktop screwed my code while I was trying to move to another branch. In those times, I just empty my folder and click "Clone again" on GitHub Desktop.

The problem is, the cloning process creates files and foldes from the repo and suddenly tries to unlink one of those folder and makes an error. Files are only partialy downloaded to the dev folder.

### Release version

3.0.0 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Empty folder
2. Click "Clone again" when GitHub Desktop says it can't find the folder.

### Screenshots

![GHDB](https://user-images.githubusercontent.com/16547085/166819688-f4b3c5fd-7fa8-4552-9bb6-f96b09a52980.png)

### Additional context

My dev folder is shared from my dev machine. 
v2.9.14 blocked any access I had to my dev folder so I struggled with trying to install a previous version, which led to the same cloning problem and since then I still have this cloning problem very often because I get the errors while changing branch very often.
It also looks like file that should be ignored always keep popping in the changes (left pane) even though I always click "add to .gitignore"

**Comment by sergiou87** [comment]
Hi @FrankOVD 👋 

Just to make sure I understand: did you empty the existing repository folder and then clone the same repo into it again? If so, maybe you didn't delete some hidden files/folders which is causing the problems you're seeing 🤔 

Other than that, I'd be interested in those issues you experience when switching branches or with files that aren't being ignored. Please, if you don't mind, file new issues for those so we can look into them. Thank you!

**Comment by FrankOVD** [comment]
Hi @sergiou87 

Yes, I did in fact empty the existing repository folder and cloned the same repo into it again. My File explorer is set to show all hidden and system folders so I know I did. Plus this __ARCHIVE sub folder is not hidden and could not have been deleted if there was anything remaining in it.

I'll try to document the other issues so I can file these too.

**Comment by sergiou87** [comment]
Sorry for the late reply 😳  Somehow I missed this notification.

Next time could you try deleting the whole folder? I think Desktop should suggest you to retry clone too, maybe that works 🤔
