### ISSUE TITLE
Add linux support 

### ISSUE THREAD

**Issue by Imshubh69** [desktop/desktop#14516]
### The feature request

Hey GitHub desktop team here i am request you guys to make a GitHub desktop for linux as 25-30% devlopers use linux and we need GitHub desktop app so can you guys make one for linux as a flatpak package or something like that :)

### Proposed solution

It will help to devlopers who uses linux as thier primary os

**Comment by steveward** [comment]
Thanks for the issue @shvmimg. At this time there are no official builds of GitHub Desktop available for Linux, but a former developer of GitHub Desktop maintains a fork with Linux builds available for download:

https://github.com/shiftkey/desktop/releases

You can also follow along with https://github.com/desktop/desktop/issues/1525 for updates about an official Linux release.
