### ISSUE TITLE
A javascript error occured in the main process

### ISSUE THREAD

**Issue by huaxiaxueyuan** [desktop/desktop#14517]
### The problem

An error dialog shows in the installation process on windows 10.

### Release version

the last version of windows

### Operating system

windows 10 professional

### Screenshots

![微信截图_20220507141611](https://user-images.githubusercontent.com/18324764/167241912-efa0d55d-3a55-48f0-bd94-d1a382014c35.png)

**Comment by sergiou87** [comment]
Thanks for your report @huaxiaxueyuan 

Is this a problem updating the app or installing it from the first time?

If it's the latter, could you please look for files prefixed with `Squirrel-` in `C:\Users\<your username>\AppData\Local\GitHubDesktop` and upload them here?
