### ISSUE TITLE
Github Desktop fails to authenticate to BitBucket

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#14510]
### The problem

Suddenly not long ago, Github Desktop stopped accepting my username and password, preventing me from using the product from anything other than looking at the local copies of my repos.

My user name and password has not been changed.

Direct use of the git commands in the command line works fine with no issues at all, so I've been forced to revert to using git commands where I would rather use the Desktop.

### Release version

3.0.0 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Go into any repo in the list.
2. Click 'Pull Origin', 'Fetch' or any other command that interacts with BitBucket.
3. Error occurs
![AuthenticationFailure](https://user-images.githubusercontent.com/40154484/167031086-b19c59d2-7afb-45cc-95c7-85020d0c6c57.PNG)

### Log files

[2022-05-05.desktop.production.log](https://github.com/desktop/desktop/files/8636250/2022-05-05.desktop.production.log)

**Comment by 6645594094** [comment]
Fgffc

2022-05-05 14:51 GMT-07:00, MattRobinsonGenesys ***@***.***>:

**Comment by 6645594094** [comment]
Fgh

2022-05-05 15:50 GMT-07:00, Armando Pelayo Duran ***@***.***>:

**Comment by ghost** [comment]
What does 'Fgh' and 'Fgffc' mean, Armando ?

**Comment by sergiou87** [comment]
Hey @MattRobinsonGenesys! 👋 

Could you check if anything in #14052 helps you with this issue? 🤞

**Comment by ghost** [comment]
Thanks Sergio.

It certainly helped. This issue is now solved for me. 😊
