### ISSUE TITLE
I cannot open files into Android Studio from GitHub.

### ISSUE THREAD

**Issue by mskogstadstubbs** [desktop/desktop#14519]
### The problem

I cannot open files into Android Studio from GitHub.

![image](https://user-images.githubusercontent.com/4955209/167296848-152d42b6-c861-48a2-b9ac-cf399d3cca71.png)

### Release version

3.0.0 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Open project in GitHub
Select Repository > Open in Android Studio
Get error message.

**Comment by sergiou87** [comment]
@mskogstadstubbs thanks for your report! I already submitted a PR with the fix in #14523

**Comment by sergiou87** [comment]
This should be fixed in 3.0.1 @mskogstadstubbs , thank you for your patience!
