### ISSUE TITLE
Order Repository By Activity

### ISSUE THREAD

**Issue by hslee2008** [desktop/desktop#14522]
### The feature request

Currently, when cloning my repository, the repos are ordered by names.
This is a bit inconvenient as the user would have to scroll through or find it by typing.
Most of the time when you are cloning repository, you are cloning your forks/your repos.
Usually, you try cloning the repo in GitHub Desktop if you want to contribute or do something in GitHub Desktop that is not possible in Git/GitHub.

### Proposed solution

Order the repos by activities such as commits, branches date, latest activity and more.
Sort of like in GitHub where you see your repos in the order of your activities.

**Comment by steveward** [comment]
@HyunseungLee-Travis thanks for the issue. The repository list has a `Recent` section, which appears when you have over a certain number of repositories cloned (I believe 7). This displays recently viewed repositories. At this time we don't have any plans to make further changes to the repository list, so I am going to close this out.

**Comment by hslee2008** [comment]
Thank you for this info!
