### ISSUE TITLE
Repository Folders

### ISSUE THREAD

**Issue by ThirdByteTaken** [desktop/desktop#14526]
### The feature request

The idea is to have visual folders which allow us to better sort repositories in the 'Current Repository' selection. They could be sorted in a similar way to the existing "Recent" section except collapsible. 
<img width="252" alt="Example" src="https://user-images.githubusercontent.com/62224502/167528279-7d425640-bb1a-43f2-9b58-052139085275.png">
 

### Proposed solution

This would be great for anyone who works with a large amount of different repositories, allowing them to avoid having to manually search for them. I personally frequently change between projects so finding them quickly is an important part of this.

### Additional context

Mockup:
![Mockup1](https://user-images.githubusercontent.com/62224502/167529427-140aa0ce-9e01-4fce-8a59-5c71db04483b.png)
![Mockup2](https://user-images.githubusercontent.com/62224502/167529432-e34f8a1c-8bed-4311-bc12-3263bdd9d3c6.png)

**Comment by niik** [comment]
Thanks for the feedback @ThirdByteTaken. See [this comment](https://github.com/desktop/desktop/issues/10201#issuecomment-658693653) for more information about why we do not have plans to implement repository grouping at this time. Thanks for using GitHub Desktop
