### ISSUE TITLE
Not letting me push changes to my repository

### ISSUE THREAD

**Issue by idwilsona** [desktop/desktop#14609]
### The problem

Not letting me push changes to my repository

### Release version

3.0.0

### Operating system

windows 10

### Steps to reproduce the behavior

click on "push origin"
Fill authentication info and saying authentication fail (see screenshot below)

### Screenshots

![image](https://user-images.githubusercontent.com/94861245/168178866-cc2dcecb-15be-4944-9b1b-7485a4eefa49.png)

**Comment by steveward** [comment]
@idwilsona thanks for the issue. You will need to follow these instructions to generate a personal access token to use with your GitLab instance:

https://github.com/desktop/desktop/blob/development/docs/integrations/gitlab.md

Let me know if you run into any issues!
