### ISSUE TITLE
Review Pull Request (Github desktop)

### ISSUE THREAD

**Issue by siamsuhaib** [desktop/desktop#14603]
### The problem

The tab "Pull Requests" under current branch is missing! I can't view pull requests

### Release version

3.0.0 official and 2.9.16-beta2 x64

### Operating system

Windows 10 Enterprise 19044.1645

### Screenshots

![image](https://user-images.githubusercontent.com/91011445/167871249-7bc8e5a8-938c-4591-a433-6eefb2325148.png)

**Comment by tidy-dev** [comment]
@siamsuhaib Thank you for the issue. Is this repository a GitHub repository? (The pull request tab is only supported for GitHub repositories).

**Comment by siamsuhaib** [comment]
Thanks @tidy-dev for your quick response. Yes this is a GitHub repository. And the pull request tab is available on my teammate machine with GitHub desktop using the same version

**Comment by siamsuhaib** [comment]
@tidy-dev I update the OS information it's actually Windows 10 Enterprise not Windows 11

**Comment by siamsuhaib** [comment]
Seems GitHub desktop was not signed in correctly
