### ISSUE TITLE
Open With Android Studio 64 bit

### ISSUE THREAD

**Issue by mamamia5x** [desktop/desktop#14605]
### The problem

I know it was fixed in #14523, but how do I the updated files without having to use JS to compile everything again.

### Release version

3.0

### Operating system

Windows 10

**Comment by sergiou87** [comment]
Hello @mamamia5x 👋 

I don't think you can until we release a new version (it could be a beta). One option you might want to consider, **but I haven't tested and I have no idea if it has other implications**, is to go to `C:/Program Files/Android Studio/bin` folder, rename `studio.exe` temporarily to something else (e.g. `backup-studio.exe`) and then rename `studio64.exe` to `studio.exe`.

I think that should do the trick _for now_ if you cannot wait.

**Comment by mamamia5x** [comment]
Thanks, I'll try it as soon as I can.
