### ISSUE TITLE
Import and export repositories collection

### ISSUE THREAD

**Issue by profimedica** [desktop/desktop#14610]
### The feature request

For the moment, we can't add multiple repositories at once.
Once we manage to manually add multiple repositories, it would be very useful to share the repositories collection with other users or to migrate them to another installation.

### Proposed solution

I can imagine it is possible to export them as a json file and import them back.

**Comment by steveward** [comment]
Thanks for the feedback @profimedica. You can add multiple repositories by bulk selection and then adding them via drag-and-drop directly into GitHub Desktop. A 'scan for repositories' feature is being tracked in https://github.com/desktop/desktop/issues/1574 if you would like to add feedback there as well.

I'm going to close this out.
