### ISSUE TITLE
"Checking for ability to merge automatically..." will not end when the diff is too big

### ISSUE THREAD

**Issue by gecko655** [desktop/desktop#14629]
### The problem

I have a branch `foo` that has more than 10,000,000 lines difference from the master branch.

When I attempted to merge the master branch to `foo` branch, the GitHub Desktop app shows "Checking for ability to merge automatically..." message and will not finish the check.
When this happens, the console shows the following error:

```
node:buffer:784 Uncaught (in promise) Error: Cannot create a string longer than 0x1fffffe8 characters
    at Buffer.toString (node:buffer:784:17)
    at Vh (merge.ts:125:32)
    at async Promise.all (index 0)
    at async SO.updateStatus (merge-choose-branch-dialog.tsx:102:12)
toString	@	node:buffer:784
Vh	@	merge.ts:125
```

### Release version

Version 3.0.0 (arm64)

### Operating system

macOS Monterey (12.3.1)

### Steps to reproduce the behavior

1. Create a branch named `foo-branch` that has 10,000,000 lines difference from the master branch
2. Click "Choose a branch to merge into foo-branch"
3. Choose `master` branch as the merging branch
4. wait for the error to be output

### Log files

[2022-05-18.desktop.production.log](https://github.com/desktop/desktop/files/8715648/2022-05-18.desktop.production.log)

### Screenshots

<img width="1072" alt="スクリーンショット 2022-05-18 20 03 19" src="https://user-images.githubusercontent.com/6166778/169026196-bb525f4a-bb20-4027-8ac7-145ec10d0896.png">

### Additional context

The `foo` branch actually has 14.9M difference from the master branch.
```
❯ git diff --numstat origin/master | awk '{sum+=$1+$2} END {print sum}'
14968519
```

**Comment by niik** [comment]
Hey @gecko655, thanks so much for reaching out and for your detailed explanation of the problem. This was reported in https://github.com/desktop/desktop/issues/14485 so I'm going to close this issue in favor of that and I'll be opening a PR shortly to hopefully address the underlying problem.

Please subscribe to https://github.com/desktop/desktop/issues/14485 to follow along with any development
