### ISSUE TITLE
neither PAT nor PWD works 

### ISSUE THREAD

**Issue by sreenageshusa** [desktop/desktop#14627]
### The problem

I am failed multiple attempts to git clone 
1. using username and/or username@mail.com + password
2. user username and/or username@mail.com + personal access token freshly generated as well.
3. Both from command line  and github desktop app
4. Doesn't work even after resetting password to PAT in windows credential manager.
So frustrating that the documentation simply states - paste the password when prompted but never works. Wasting my hours trying to fix this without result.

### Release version

3.0

### Operating system

windows

### Steps to reproduce the behavior

1. windows-cmd-prompt> git clone url-repo.git
2. prompts for username: your-username or emailid
3. prompts for password: enter_PAT_here
4. **always displays** : remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.

**Comment by steveward** [comment]
@sreenageshusa have you logged in via `File` > `Options` > `Accounts`? Browser authentication is the only supported method of authentication in GitHub Desktop. The user/PAT authentication is for cases where you are using third-party services like Bitbucket or Gitlab. 

I'm going to close this out, but let me know if you have any further issues authenticating.
