### ISSUE TITLE
I am unable to authenticate on a single machine

### ISSUE THREAD

**Issue by mattboulter** [desktop/desktop#14648]
### The problem

I run Desktop on multiple machines at home, but on one single machine I am unable to authenticate in the Desktop App.
I am authenticated in Chrome. I have tried being logged out in Chrome, then redoing the authenticate. 
I have had it working on this machine before.
I have tried changing my default browser, so there wouldn't be anything cached or tokens/cookies, and retry in Desktop
get redirected, enter my U/P get the browser dialog to pass back control to Desktop, agree but  then get the error again.
I have tried uninstalling, but it feels like the uninstaller must not clear some settings, because upon reinstall of Desktop,
I immediately have my local repos all setup, I don't need to re-add them, which it must have settings cached somewhere.

### Release version

Version 3.0.0 (x64)

### Operating system

Windows 10 Pro (20H2 - build 19042.964)

### Steps to reproduce the behavior

1. Start Desktop
2. If I click Pull Origin I get "fatal: unable to access 'https://github.com/mattboulter/python-devops.git/': Failed to connect to github.com port 443 after 37 ms: Bad access"
3. I click File > Options
4. Accounts > Github.com > Sign In
5. Click Continue with browser
6. I can see a tab open and close quickly in the Browser 
7. Then Desktop has the red "Unable to fetch authenticated user" banner

I just did it again and kept click continue with browser, I got to the "Authorize Desktop" page and clicked authorize , now the Sign in dialog box just has spinning arrows in the upper right corner, now I cant click cancel. I will add that log file to this ticket.

### Log files

[2022-05-14.desktop.production.log](https://github.com/desktop/desktop/files/8746883/2022-05-14.desktop.production.log)
[2022-05-21.desktop.production.log](https://github.com/desktop/desktop/files/8746884/2022-05-21.desktop.production.log)
[2022-05-21.desktop.production.log](https://github.com/desktop/desktop/files/8746903/2022-05-21.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/7412831/169633377-b4198165-390a-4384-b8ac-3b474269bfe4.png)
![image](https://user-images.githubusercontent.com/7412831/169633382-a56fe45c-1112-438e-8ae6-23f1ebba0296.png)
![image](https://user-images.githubusercontent.com/7412831/169633385-9ccb4773-a03b-4b32-ab00-877af0571382.png)
![image](https://user-images.githubusercontent.com/7412831/169633689-4a512898-3b6d-436b-98e9-d392049912a4.png)

**Comment by tsvetilian-ty** [comment]
@mattboulter usually, that type of error is related to proxy settings, firewall, or antivirus software blocking the communication with github.com. You can try to exclude GitHub Desktop from your antivirus or firewall
