### ISSUE TITLE
Error en Pushing 

### ISSUE THREAD

**Issue by salimass** [desktop/desktop#14644]
### The problem

Por error subi unos videos , los borrre del repositorio y ahora que hago pushing no toma los cambios me sigue saliendo el mismo error como si aun los estubiera cargando.

The push operation includes a file which exceeds GitHub's file size restriction of 100MB. Please remove the file from history and try again.

File causing error:

Videos_Procedimientos.zip (228.34 MB)
Notaria5/03.Ejecución/Doc.Entregada.Notaria5/VENTA INTERESES SOCIAL (VIS).mkv (210.93 MB)
Notaria5/03.Ejecución/Doc.Entregada.Notaria5/VENTA INTERES PRIORITARIO (VIP).mkv (166.91 MB)

que puedo hacer?

### Release version

GitHub Desktop.

### Operating system

Windows 10 

### Log files

helpme

### Screenshots

help me 

### Additional context

helpme

**Comment by sergiou87** [comment]
Hola @salimass! 👋 

Como consejo, para próximos issues es mejor que escribas en inglés para que mis compañeros puedan ayudar también de manera más efectiva 😄 

Entiendo que jamás hiciste push de esos vídeos, sino que los borraste **y después** intentaste hacer push de cambios nuevos. El problema es que los vídeos están en el historial de commits y hay que borrarlos de ahí. Si estoy en lo cierto y no has podido hacer push, abajo a la izquierda deberías tener un botón "Undo" para deshacer commits. **Importante:** esto va a deshacer el commit **PERO MANTENDRÁ TUS CAMBIOS**.

![2022-05-20 at 15 46](https://user-images.githubusercontent.com/1083228/169541628-efb5305c-5364-476a-9985-12700e49f1ea.png)

Con esto en mente, lo que yo haría es:
1. **MUY MUY IMPORTANTE:** Haz una **copia de seguridad** del repositorio en algún lugar de tu disco duro. Simplemente copia la carpeta a otro lugar por si necesitas recuperarla más adelante.
1. Pulsa ese botón "Undo" hasta deshacer el commit en el que añadiste esos archivos por error **(incluido ese commit)**. Es posible que la segunda vez que pulses "Undo" te pida confirmación por si se pierden datos. No debería haber pérdida de datos en este caso (pero por si acaso es importante la **copia de seguridad** del paso anterior), así que confirma la operación sin miedo.
1. Borra esos archivos del repositorio.
1. Haz un commit con todos los demás cambios que tengas en ese momento en el repositorio.
1. Haz push

Espero que esto te ayude! Si necesitas más ayuda, házmelo saber. Por el momento voy a cerrar este issue ya que no se trata de un bug de la aplicación.
