### ISSUE TITLE
Wider current branch tab

### ISSUE THREAD

**Issue by jayjwseo** [desktop/desktop#14642]
### The feature request

Branch names are truncated due to narrow width of 'Current Branch' tab. 

### Proposed solution

Increase the width of 'Current Branch' tab so that users can see longer branch names without truncation.

### Additional context

![truncated-branch-name](https://user-images.githubusercontent.com/70701494/169468992-e87baf5d-8664-4b17-822d-dfb3d0b59a3b.png)

**Comment by steveward** [comment]
Thanks @jayjwseo, we are tracking this in https://github.com/desktop/desktop/issues/4569. You can follow along there for updates.  I'm going to close this out.
