### ISSUE TITLE
Search commit messages

### ISSUE THREAD

**Issue by BB-fat** [desktop/desktop#14643]
### The feature request

Fuse search for commit messages.

### Proposed solution

Maybe we can add a search input on the bottom of the history panel.

![image](https://user-images.githubusercontent.com/45072480/169511125-39aa21cf-b8bb-45f5-82c3-fea88eb2a60d.png)

**Comment by steveward** [comment]
Thanks @BB-fat, we are tracking this in https://github.com/desktop/desktop/issues/7022, so I'm going to close this issue out. I'll reference this there.
