### ISSUE TITLE
unable to enable notifications on GitHub desktop for mac

### ISSUE THREAD

**Issue by rohityadav225** [desktop/desktop#14659]
### The problem

I am unable to enable notification on macOS Monterey 12.4 because the GitHub desktop app does not appear on mac notification center

### Release version

3.0.0 (x64)

### Operating system

macOS Monterey 12.4

### Steps to reproduce the behavior

1. Download and Install GitHub desktop version 3.0.0 (x64)
2. Navigate to System Preferences -> Notifications & Focus -> Notifications and notice that Github Desktop is not listed there

### Screenshots

<img width="449" alt="Screen Shot 2022-05-21 at 9 53 15 PM" src="https://user-images.githubusercontent.com/39043578/169676182-7273997b-c100-426d-ac14-c60d6320116c.png">

**Comment by sergiou87** [comment]
@rohityadav225 thanks for your report!

On v3.0.0, the app should prompt you to grant permission to display notifications the first time you get an actual notification.

However, you can try the first beta of v3.0.1 which allows you to do that from `Settings -> Advanced` (changes made in https://github.com/desktop/desktop/pull/14496):


https://user-images.githubusercontent.com/1083228/167612530-ee4af24e-d633-4421-aed3-22a002d33049.mov


You can download this beta from https://desktop.github.com/beta

Please, let me know if that helps!

**Comment by rohityadav225** [comment]
I tried multiple times but`v3.0.0` did not work for me. The beta version works. Thanks!

**Comment by sergiou87** [comment]
Glad to hear that! Thanks for reporting back 😄
