### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by SaintWish** [desktop/desktop#14656]
### The problem

For whatever reason I keep getting "Authentication Failed" when I try to push changes to any one of my repositories. I have tried deleting the contents of ``%APPDATA%/Github Desktop/`` and tried to sign in again on Github Desktop with no avail. 

This started happening a few days ago when I regenerated a PAT I used with Github Desktop and enabled 2FA on my account.

### Release version

Version 3.0.0 (x64)

### Operating system

Windows 10

### Log files
```
2022-05-21T18:08:02.024Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.559s)
2022-05-21T18:08:02.024Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/HexiaHost/toolshed.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
```

**Comment by tsvetilian-ty** [comment]
@SaintWish try to check when your GitHub credentials were last modified.

1. Search in Windows for "Credential Manager" (Control Panel\User Accounts\Credential Manager)
2. Select "Windows Credentials"
3. Check the Modified indicator for GitHub

Also, you can try to login through your browser. Open GitHub Desktop and go to `File > Options` in the Accounts tab you can use the browser.

**Comment by SaintWish** [comment]
> 1. Credential Manager

They were last modified today according to Windows. I tried to login through my browser, but I still get the same authentication error.

**Comment by tsvetilian-ty** [comment]
@SaintWish you can try to remove the GitHub credentials entry from the Credential Manager, and after that, try to login with a browser

**Comment by SaintWish** [comment]
> @SaintWish perhaps you can try to remove the GitHub credentials entry from the Credential Manager, and after that, try to login with a browser

I tried just now, but still the same thing.

**Comment by sayamkeshri** [comment]
Kindly try checking the account you are in is the owner of your that repository. Because I had the same issue once

**Comment by SaintWish** [comment]
I figured out the issue, my actual GIT configuration was using a old PAT which I completely forgot about which broke everything. Cheers for y'all patience!
