### ISSUE TITLE
Let Client use System Proxy or Manually Set a HTTP or SOCKS5 Proxy

### ISSUE THREAD

**Issue by sfc9982** [desktop/desktop#14663]
### The feature request

Let Client use System Proxy or Manually Set a HTTP or SOCKS5 Proxy

### Proposed solution

Some user need to use proxy to use GitHub, so if you add the feature, they wont use system-wide proxy config but to specify one for GitHub Desktop

**Comment by sergiou87** [comment]
Thanks for your report @sfc9982 !

I think this is the same as #13975 so I'm gonna close this one. If you want to know when we make progress on that, please subscribe to #13975.
