### ISSUE TITLE
Unable to add a local repository

### ISSUE THREAD

**Issue by JamesVanWaza** [desktop/desktop#14660]
### The problem

When I go to File -> Add Local Repository -> Choose, Github Desktop Crashes, and I am unable to add Local Repository

### Release version

3.0.0

### Operating system

macOS Monterey 12.3.1

### Log files

[2022-05-22.desktop.production.log](https://github.com/desktop/desktop/files/8750331/2022-05-22.desktop.production.log)

**Comment by sergiou87** [comment]
Hi @JamesVanWaza 👋 

Thank you for your report. I cannot reproduce this crash. When it happens, do you get any kind of alert/message describing the crash? If so, could you share it with us, please?

**Comment by JamesVanWaza** [comment]
@sergiou87 No crash report so far but on Activity Monitor it just shows that it's not responding.

**Comment by sergiou87** [comment]
Hard to tell what's going on then… clicking on that button just [tells Electron to show the Open dialog](https://www.electronjs.org/docs/latest/api/dialog#dialogshowopendialogbrowserwindow-options).

Could you try running the app from a clean state?
1. Quitting GitHub Desktop and restarting your machine to ensure no rogue processes are hanging about
1. Uninstalling GitHub Desktop
1. Moving/renaming temporarily the `C:\Users<YourUserName>\AppData\Roaming\GitHub Desktop` folder. This folder has all your GitHub Desktop settings and the list of repositories.
1. Downloading and installing GitHub Desktop again from https://desktop.github.com

**Comment by JamesVanWaza** [comment]
I restarted computer and was able to get it to work. Thanks for the help 👍🏿
