### ISSUE TITLE
Pin repositories

### ISSUE THREAD

**Issue by pavansandeep2910** [desktop/desktop#14671]
### The feature request

Currently, I think there is no way to pin cloned repositories on the Github desktop. Pinning repositories can easily help us to navigate to the repository that a developer constantly works on.

### Proposed solution

Please introduce pin cloned repository feature like pinning chat groups in Microsoft teams

**Comment by tsvetilian-ty** [comment]
@pavansandeep2910, the feature is on the roadmap of the core team, or it wasn't the last time it was suggested. Feedback and tracking on the topic you can find in #8183
