### ISSUE TITLE
not getting confirmation email

### ISSUE THREAD

**Issue by faisalhayat540** [desktop/desktop#14685]
am not getting confirmation email request from my teammates, why?
how can i get email???

**Comment by sergiou87** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
