### ISSUE TITLE
History not showing up last commit

### ISSUE THREAD

**Issue by uprealdigital** [desktop/desktop#14683]
### The problem

After pushing changes, the history panel doesn't show the last push. At some point, it starts to work but I don't know how or when exactly.

### Release version

3.0.0 X64

### Operating system

Windows 10

### Steps to reproduce the behavior

1-Make changes to your repo
2-Push to cloud repo
3-Look in the History panel, the most recent commit you just did is missing.

**Comment by sergiou87** [comment]
Hello!

I cannot reproduce this behavior, does it happen with every repository?

Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

Thanks!

**Comment by uprealdigital** [comment]
Hi! 

Thank you for the quick reply to this bug!

Here's the logs from yesterday when it happened.
[2022-05-26.desktop.production.log](https://github.com/desktop/desktop/files/8787116/2022-05-26.desktop.production.log)

The problem seems be a UI issue so I'm not sure it will be part of the logs.

Never had this issue before but I believe that since I updated Github version, I started getting that weird behavior of not seeing the last push history element.

**Comment by sergiou87** [comment]
Sorry for the late reply 😢 
For me it works as expected. I wonder if maybe the repository is too big or you have something slowing down all the work GitHub Desktop does after a push to update the UI 🤔 For example, an antivirus…

**Comment by uprealdigital** [comment]
Hey Sergiou87, it might be the antivirus, I'll do a test without to see if there's a difference.Thanks!

**Comment by philipborbon** [comment]
I'm experiencing this issue on Version 3.2.0.

Edit:
Seems to be happening randomly.

**Comment by jacquie77917** [comment]
I am experiencing the same issue now ;( It was still working last Saturday (Oct 21) and it suddenly stopped working the day after! It's happened before, but it went back to normal the next day  but it is still not working at the moment ;(

**Comment by Elie-1996** [comment]
I am having this issue in the latest version as of today....
I have to exit the app and reopen to see latest changes.
