### ISSUE TITLE
Commit button doesn't work with kbd shortcut when an item in the changes list has focus

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#14689]
### The problem

When trying to commit using <kbd>CMD + Enter</kbd>, I just noticed that a change in the changes list is selected/deselected instead of the commit being made.

### Release version

3.0

### Operating system

macOS 12.4

### Steps to reproduce the behavior

1. Stage a change
2. Select the change from the changes list
3. Try to commit using <kbd>CMD + Enter</kbd> 
4. Note that the selection is toggled on and off

### Screenshots

![2022-05-28 22 27 31](https://user-images.githubusercontent.com/1715082/170850697-a94afdf4-96cf-4ba0-b3d6-cf6d7cb6b794.gif)

### Additional context

I can work around this by manually bringing focus to the commit form, but this is annoying, to say the least 😇

**Comment by niik** [comment]
👋 @iAmWillShepherd! Thanks for the report and hope you're doing well!

I believe this unfortunate behavior is how it's always been, the code which detects the CmdOrCtrl+Enter key combo lives within the commit message component

https://github.com/desktop/desktop/blob/bef95af3bf91f1181cf5aedd9019d9813a920aa1/app/src/ui/changes/commit-message.tsx#L339-L343

It shouldn't, obviously, but that's nonetheless the reason why this doesn't work. I'm gonna label this as a bug and to whomever picks this up in the future we likely want to subscribe to this on document or through a GlobalShortcut but we need to make sure that we don't react to it if there's a dialog or foldout open.

**Comment by iAmWillShepherd** [comment]
> 👋 @iAmWillShepherd! Thanks for the report and hope you're doing well!

Yo! Didn't expect to see you here 😃. I'm ok, well left about 5 years ago, but I'm here if you wanna set the bar low 🤣Hopefully you doing aight up there in The North, with all that's happening over there. 

> 'm gonna label this as a bug and to whomever picks this up in the future we likely want to subscribe to this on document or through a GlobalShortcut but we need to make sure that we don't react to it if there's a dialog or foldout open.

It's not a huge deal, to be honest, just a minor annoyance. I've been caught by this more than I remember in the past, so I assumed it was a regression, but it does make sense that the root cause is that the event handler is bound to the component and not the app document. 

For some reason, I thought the keyboard shortcut to select/deselect a checkbox was the <kbd>Space</kbd> key. Bad memory 🤔 .
