### ISSUE TITLE
Error in work

### ISSUE THREAD

**Issue by TarasYanchuk** [desktop/desktop#14699]
### The problem

The light went out in the house, after connecting to GitHub Desktop, all repositories need to be sent again, but they were sent to me.

### Release version

Version 3.0.0 (x64)

### Operating system

Windows 10

### Screenshots

![Безымянный](https://user-images.githubusercontent.com/98208982/171045628-ba028f67-7e74-4e3c-9738-fc4c49e7338f.jpg)

**Comment by steveward** [comment]
@TarasYanchuk thanks for the issue. Can you share some further details about the issue you are having? Did your repositories disappear from GitHub Desktop, or are they just all showing as not being published to GitHub? The repository may have gotten corrupt if Git operations were occurring during a sudden power outage.
