### ISSUE TITLE
Changes from other commit are displayed in history

### ISSUE THREAD

**Issue by HesseM** [desktop/desktop#14695]
### The problem

Github desktop shows changes from previous selected commit in history when other commit is selected before changes from previous commit are loaded

### Release version

3.0.0

### Operating system

Windows 10 (21H2)

### Steps to reproduce the behavior

1. Go to History
2. Select a commit
3. Switch to a commit with a huge number of changes
4. Before changes are loaded and viewed switch back to commit from step 2
5. Changes from both commits are displayed

### Log files

[2022-05-30.desktop.production.log](https://github.com/desktop/desktop/files/8796904/2022-05-30.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @HesseM. This looks like the same issue as https://github.com/desktop/desktop/issues/13633, so I am going to close this out. You can follow along there for updates.
