### ISSUE TITLE
Error code 128

### ISSUE THREAD

**Issue by 0xj0n1** [desktop/desktop#14696]
### The problem

I can't clone a private repo from an organisation...

`Host key verification failed.
fatal: could not read from remote repository

Please make sure you have the correct access rights and the repository exists `

### Release version

latest

### Operating system

Linux

### Screenshots

<img width="359" alt="image" src="https://user-images.githubusercontent.com/78429664/170967635-8413609e-a338-443a-8389-154b34bb9566.png">

### Additional context

Ps.: It's in German and I work on Linux

**Comment by niik** [comment]
Hi @0xj0n1, the error you're seeing typically indicates that you either have the wrong host key or none at all in your `~/.ssh/known_hosts` file. Typically this key would be added automatically by GitHub Desktop but I'm not sure how that differs on Linux since we don't officially support that platform (see https://github.com/shiftkey/desktop for the linux fork).

Typically how you would resolve this is by looking at your known hosts file and removing any failing host key. Since you didn't specify which version you're running I'll note that we added a specific dialog for this scenario in 2.9.4 which might solve this for you.

Also see https://stackoverflow.com/questions/13363553/git-error-host-key-verification-failed-when-connecting-to-remote-repository for more information on how to resolve this manually.

If you believe this is a bug in the Linux fork please create a new issue in that repository.

**Comment by 0xj0n1** [comment]
Now I get the error 
`
Warning: Permanently added 'github.com' (ECDSA) to the list of known hosts.
Permission denied (publickey).
`

**Comment by steveward** [comment]
@0xj0n1 I would verify your key is configured correctly by running `ssh -vT git@github.com` from the command line. Make sure `ssh-agent` is running and that your key has been added.

**Comment by 0xj0n1** [comment]
`root@vicev:~# ssh-agent
SSH_AUTH_SOCK=/tmp/ssh-h1y7UIuJ4IRN/agent.45974; export SSH_AUTH_SOCK;
SSH_AGENT_PID=45975; export SSH_AGENT_PID;
echo Agent pid 45975;
root@vicev:~# ssh -vT git@github.com
OpenSSH_7.4p1 Debian-10+deb9u7, OpenSSL 1.0.2u  20 Dec 2019
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to github.com [140.82.121.4] port 22.
debug1: Connection established.
debug1: permanently_set_uid: 0/0
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u7
debug1: Remote protocol version 2.0, remote software version babeld-44f79051
debug1: no match: babeld-44f79051
debug1: Authenticating to github.com:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM
debug1: Host 'github.com' is known and matches the ECDSA host key.
debug1: Found key in /root/.ssh/known_hosts:3
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /root/.ssh/id_rsa
debug1: Trying private key: /root/.ssh/id_dsa
debug1: Trying private key: /root/.ssh/id_ecdsa
debug1: Trying private key: /root/.ssh/id_ed25519
debug1: No more authentication methods to try.
Permission denied (publickey).
`

I've done this and the key is still denied
