### ISSUE TITLE
GitHub Desktop not opening after update

### ISSUE THREAD

**Issue by Mumbarun** [desktop/desktop#14707]
### The problem

On my old iMac '11 computer (macOS High Sierra) I opened GitHub Desktop and everything works fine, but after rebooting for GitHub (3.0.1) auto update it won't open

### Release version

3.0.1

### Operating system

MacOS High Sierra (10.13.6)

### Steps to reproduce the behavior

1. Launch old version of GitHub Desktop (I do not know which)
2. Click Update
3. The app closes automatically but does not reopen
4. Click on GitHub Desktop application
5. Nothing happens

### Additional context

I try to reinstall GitHub Desktop from the original download page, but nothing change

**Comment by tsvetilian-ty** [comment]
@Mumbarun could you upload the log file from GitHub Desktop so it's easier to check what is causing the issue? If you have UI available, go to Help > "Show Logs..." if not, type `open /Users/user/Library/Application\ Support/GitHub\ Desktop/logs` in the terminal.

**Comment by steveward** [comment]
@Mumbarun unfortunately we're no longer able to support macOS High Sierra in GitHub Desktop -- are you able to update to a newer version of macOS? I'm sorry that I don't have better news for you.

I'm going to close this out, but let me know if I can help with anything else.

**Comment by Mumbarun** [comment]
@tsvetilian-ty I found some logs files, this is the last:

```
- 2022-06-01T09:12:38.797Z - info: [ui] [AppStore] loading 30 repositories from store
- 2022-06-01T09:12:38.826Z - info: [ui] [AppStore] found account: Mumbarun (Francesco Sasso)
- 2022-06-01T09:12:39.461Z - info: [ui] Subscribed 'Mumbarun' to Alive channel
- 2022-06-01T09:12:39.571Z - info: [ui] [BranchPruner] No branches to prune.
- 2022-06-01T09:12:40.238Z - info: [ui] launching: 3.0.0 (Mac OS 10.13.6)
- 2022-06-01T09:12:40.239Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
- 2022-06-01T09:12:45.091Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.303s)
- 2022-06-01T09:12:47.333Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: rossetti-pavimenti-api - Mumbarun (has token)
- 2022-06-01T09:12:48.932Z - info: [ui] Executing pull: git -c credential.helper= -c protocol.version=2 -c rebase.backend=merge pull --ff --progress origin (took 1.528s)
- 2022-06-01T09:12:52.268Z - info: [ui] [BranchPruner] No branches to prune.
- 2022-06-01T09:12:57.739Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: dado-api - Mumbarun (has token)
- 2022-06-01T09:12:58.921Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.149s)
- 2022-06-01T09:13:03.592Z - info: [ui] [Timing] Action 'checkout branch from list' for 'meccanichecreative/dado-api' took 0.001s
- 2022-06-01T09:13:09.530Z - info: [ui] No submodules found. Skipping "git submodule status"
- 2022-06-01T09:13:11.083Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 29 repositories took 10.9s of which 0.8s paused, total 11.7s
```

**Comment by Mumbarun** [comment]
@steveward Hi, I can't update the OS because this mac (iMac 2011) is not compatible with the newer version.
I have a new mac and on it GitHub desktop work just fine, but only in the old pc I have a program that I use a lot.
There are some other method to use GitHub on High Sierra? via Terminal?

Thanks anyway

**Comment by JV-conseil** [comment]
Same problem here 👋

By forcing a launch of GitHub Desktop v3.0.1 from Terminal 

```bash
/Applications/GitHub\ Desktop.app/Contents/MacOS/GitHub\ Desktop 
```

It ends with these lines

```bash
Error: Cannot create BrowserWindow before app is ready
    at new Ne (/Applications/GitHub Desktop.app/Contents/Resources/app/main.js:2:260722)
    at /Applications/GitHub Desktop.app/Contents/Resources/app/main.js:2:265420
    at Ze (/Applications/GitHub Desktop.app/Contents/Resources/app/main.js:2:265927)
    at process.<anonymous> (/Applications/GitHub Desktop.app/Contents/Resources/app/main.js:2:266953)
    at process.emit (node:events:402:35)
    at process._fatalException (node:internal/process/execution:170:25)
```

**Comment by steveward** [comment]
@Mumbarun apologies, we're investigating a fix for this issue and hope to have an update soon. See  https://github.com/desktop/desktop/issues/14712#issuecomment-1144536119. You can follow along there for updates.

**Comment by Maryejc** [comment]
> @Mumbarun could you upload the log file from GitHub Desktop so it's easier to check what is causing the issue? If you have UI available, go to Help > "Show Logs..." if not, type `open /Users/user/Library/Application\ Support/GitHub\ Desktop/logs` in the terminal.
