### ISSUE TITLE
Stalled upload

### ISSUE THREAD

**Issue by amelia-ingram** [desktop/desktop#14704]
### The problem

Upload is not working.  Won't let me cancel from Github Desktop.  

### Release version

3.0.0

### Operating system

MacOS Monterey ver. 12.4

### Screenshots

![Screen Shot 2022-05-31 at 4 59 48 PM](https://user-images.githubusercontent.com/96954499/171283658-aa253b28-75c7-448a-b92b-a4f95d6516b4.png)

**Comment by steveward** [comment]
Thanks for the request @amelia-ingram, I'm going to add this to https://github.com/desktop/desktop/issues/14095 where we are tracking this issue. You can follow along there for updates.
