### ISSUE TITLE
Maximised window overflows to another display

### ISSUE THREAD

**Issue by felipedrumond** [desktop/desktop#14708]
### The problem

I have two displays and when I maximise Git Desktop in any of them, the window overflows to the another.

### Release version

3.0.1

### Operating system

Windows 10 Version 2004 19041.1415

### Screenshots

![image](https://user-images.githubusercontent.com/17038136/171381866-26d6ff0f-e6d5-4e82-a202-97bdd60e54fe.png)
![image](https://user-images.githubusercontent.com/17038136/171381955-a63aedb4-d9b1-4f04-8549-47922819d8bb.png)

### Additional context

No other programs windows overflow to the other window when maximised.

**Comment by tsvetilian-ty** [comment]
@felipedrumond 👋 the issue is already reported. You can follow for updates and feedback https://github.com/desktop/desktop/issues/13939
