### ISSUE TITLE
Github desktop won't register new changes from desktop. 

### ISSUE THREAD

**Issue by Erin-Rooney** [desktop/desktop#14703]
### The problem

Github desktop doesn't register when I make changes to my new repository and allow me to push to github. 

### Release version

Version 3.0.0 (x64)

### Operating system

Windows

### Steps to reproduce the behavior

1. Go to github repository on desktop
2. Make folder
3. Attempt to commit and push folder to github

**Comment by steveward** [comment]
@Erin-Rooney thanks for the issue. Git doesn't track empty folders -- are there any files within the folder?

**Comment by Erin-Rooney** [comment]
That was the issue, the folders were empty. Thank you!!

Erin
