### ISSUE TITLE
connexion impossible

### ISSUE THREAD

**Issue by zzmck** [desktop/desktop#14716]
### The problem

Bonjour,

je viens d'installer github desktop,

Quand je veux connecter à mon compte github, il ouvre la page d'autorisation.
J'accepte.
La page nouvelle page s'ouvre en attente de redirection qui ne se fait jamais.
En cliquant sur le lien, rien ne se passe.
Et github desktop tourne en boucle.

### Release version

3.0.1 X64

### Operating system

windows11

### Screenshots

It s bloqued here :

![2](https://user-images.githubusercontent.com/20737183/171590353-396607d4-2eff-4fd7-a23e-7cb8bd9ae32f.jpg)

**Comment by ghost** [comment]
#14639

**Comment by zzmck** [comment]
i have change my browser and it will be good. thanks
