### ISSUE TITLE
notifications not working on windows server 2016

### ISSUE THREAD

**Issue by Justin-JHG** [desktop/desktop#14714]
### The problem

I have never received any notifications from GitHub Desktop even in app notification setting is ticked. 

### Release version

Version 3.0.1 (x64)

### Operating system

windows server 2016

### Steps to reproduce the behavior

1. create a pull request
2. a reviewer approved the pull request

Expected: 
Desktop notify me about the PR approved 

Actual:
No notifications 

![image](https://user-images.githubusercontent.com/41654878/171539928-52df3f9b-540b-468e-a057-7f8846bee4d2.png)

GitHub Desktop is not showing up in system settings, not sure how to make it appear here 

![image](https://user-images.githubusercontent.com/41654878/171540081-cfc7bf97-fff9-4b5a-b6c2-91e67b62f569.png)

**Comment by sergiou87** [comment]
Do you see notifications for other apps? I've seen this myself on Windows Server too (but not on non-server editions), but I couldn't test it for long enough to see if other apps' notifications would work.

**Comment by Justin-JHG** [comment]
> Do you see notifications for other apps? I've seen this myself on Windows Server too (but not on non-server editions), but I couldn't test it for long enough to see if other apps' notifications would work.

yes I'm receiving notifications from outlook and other apps

**Comment by sergiou87** [comment]
@Justin-JHG do you have a GitHub Desktop icon _somewhere_ in your start menu?

**Comment by Justin-JHG** [comment]
hi @sergiou87 
I did pin it to start menu but looks like it's not listed 

![image](https://user-images.githubusercontent.com/41654878/172732077-da3ce902-cd5f-440b-856d-dedab54f8ea3.png)

**Comment by sergiou87** [comment]
That might be the reason 🤔 Windows depends on apps to have a shortcut in the start menu in order to get notifications. But not any shortcut, you need a shortcut created by the GitHub Desktop installer. I think the shortcut you might have in your Desktop, copying it to the Start menu, should get the notifications working.

**Comment by Justin-JHG** [comment]
hi @sergiou87 seems still not working after add it to start menu. 

still not receiving notifications and still not appearing in system notification settings 

![image](https://user-images.githubusercontent.com/41654878/172988282-4700ffce-ed84-434f-bd8c-4609a191caff.png)

**Comment by sergiou87** [comment]
@Justin-JHG could you follow these instructions to find out the `App User Model Id` of GitHub Desktop? https://docs.microsoft.com/en-us/windows/configuration/find-the-application-user-model-id-of-an-installed-app#to-find-the-aumid-by-using-file-explorer

It should be `com.squirrel.GitHubDesktop.GitHubDesktop`

**Comment by Justin-JHG** [comment]
hi @sergiou87  

![image](https://user-images.githubusercontent.com/41654878/173010279-9c9f66b9-2bbb-44e2-8e60-22dad7a1ef97.png)

**Comment by sergiou87** [comment]
Hey @Justin-JHG !! Thanks for all your feedback 🙇‍♂️ 

Just so you know, I _finally_ got access to a Windows Server VM and investigated the issue. It seems the notifications API in older Windows versions was quite limited and, in this case, was failing silently. I've done a few changes in https://github.com/desktop/desktop-notifications/pull/22 to disable the newest and shiniest notification features for older versions of Windows, but you will still get the, let's say, basic support with some limitations (mainly, without the improvements from https://github.com/desktop/desktop-notifications/pull/13)

Unfortunately, it will still take some time until that fix is released given we'll be taking days off, but wanted to let you know about the upcoming fix.

Thank you for your patience!

**Comment by Justin-JHG** [comment]
Great! Thank you, enjoy your leave.

Sent from my iPhone
________________________________

**Comment by sergiou87** [comment]
Hi again @Justin-JHG ! Just wanted to let you know v3.0.6 was released today and contains the fix for this issue. Thank you again for your patience 🙇‍♂️

**Comment by Justin-JHG** [comment]
> 3.0.6 was released today and contains the

oh great so I can expect to receive some notifications now? thank you so much @sergiou87

**Comment by Justin-JHG** [comment]
![image](https://user-images.githubusercontent.com/41654878/186556319-d8b00b88-7ee8-459b-91a3-5ae2060d9166.png)
Nice!
