### ISSUE TITLE
Unable to start Git Hub Desktop app Mac OS High Sierra 10.13.6

### ISSUE THREAD

**Issue by pankiale** [desktop/desktop#14718]
### The problem

Git Hub decktop app has stopped working today. I have relaunched it - but is does not launch any more. I have deleted and reinstalled the latest version for Mac from your website - no result. App is not starting. 
I still can access my repository /pankiale and i still can run git through terminal.

### Release version

latest version for MAc os available to download on your website

### Operating system

Mac OS High Sierra 10.13.6

### Steps to reproduce the behavior

go to programs
start Gihub decktop
app not launching

**Comment by pychheda** [comment]
Similar thread: https://github.com/desktop/desktop/issues/14712

**Comment by steveward** [comment]
@pankiale thanks for the issue. We'll be shipping a fix for this in https://github.com/desktop/desktop-notifications/pull/18.
