### ISSUE TITLE
Keep UI zoom level after update.

### ISSUE THREAD

**Issue by RhoSigma-QB64** [desktop/desktop#14726]
### The feature request

Currently after every update of GitHub Desktop, its UI zoom level is reset to 100%.

### Proposed solution

Keep the user's UI zoom level set before the update and restore it to the same level after the update is finished. It's not that big deal, but rather a convenience option. Just put on low priority, so if anyone feels to pick it up, it can be done.

**Comment by niik** [comment]
Hey @RhoSigma-QB64, thanks for reaching out! This looks very similar to https://github.com/desktop/desktop/issues/5315 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date with any development happening in that area.

**Comment by RhoSigma-QB64** [comment]
You make it yourself very easy. I've opend this new issue, because the other one lasts for 4 years now and meanwhile got buried beneth nearly 10000 other issues. I'm pretty sure nobody will remember the other one anymore. Many thanks for (almost) nothing.
