### ISSUE TITLE
enable "Contact Support" menu item once Support is ready

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#1472]
I removed the Contact Support button in #1466 to avoid accidentally directing support to the current team - who are dealing with supporting the existing applications.

As we get closer to 1.0 and organize the transition period, we can revert that PR to enable the menu button again.

**Comment by joshaber** [comment]
We should save this for the literal 1.0 release.

**Comment by joshaber** [comment]
Example URL: https://github.com/contact?from_desktop_app=1&repo=desktop/desktop&app_version=1.0
