### ISSUE TITLE
Search and Filter bar in changes and submit 

### ISSUE THREAD

**Issue by SimonL888** [desktop/desktop#14725]
### The feature request

For submits with many files it would be helpful to have a search bar for files and the option to filter them (e.g. by file type) and same for the "Changes" Tab.

### Proposed solution

Add a search/ filter bar to the "Changes" tab and to "History--><submit-name>-->included files".

### Additional context

![image](https://user-images.githubusercontent.com/97226454/171809040-e022ee28-0095-46e4-8528-0419f155ae45.png)

**Comment by niik** [comment]
Hey @SimonL888, thanks for reaching out! This looks very similar to https://github.com/desktop/desktop/issues/6407 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date with any development happening in that area.
