### ISSUE TITLE
Delete my account

### ISSUE THREAD

**Issue by Gemintheclouds** [desktop/desktop#14728]
Hi, I can't seem to delete my github account. The github app on my end will not give me the option to delete my account. I don't use github enough this is why i would like to close my account.

**Comment by steveward** [comment]
@Gemintheclouds you can follow the steps here to delete your account:

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/deleting-your-personal-account
