### ISSUE TITLE
50 Character prompt can't be disabled

### ISSUE THREAD

**Issue by anthony-chaudhary** [desktop/desktop#14722]
### The problem

This prompt is a little too aggressive and does not seem to have any option to disable it.

![image](https://user-images.githubusercontent.com/18080164/171734016-c3bcaef0-4562-4daa-86d7-bdb9a1a466f4.png)

### Release version

Version 3.0.1 (x64)

### Operating system

Windows

### Steps to reproduce the behavior

Try to make a commit with more then 50 chars

### Additional context

This may be "right" or "wrong" either way it's way to aggressive to always come up and no option to disable it. 
Maybe our team thinks 49 or 51 characters is the magic number... don't force this on us.

**Comment by steveward** [comment]
Thanks for the feedback @anthony-sarkis. This has been previously requested in https://github.com/desktop/desktop/issues/14255, so I'm going to add your feedback there and close this out.
