### ISSUE TITLE
dont work after new update github desktop

### ISSUE THREAD

**Issue by leedavidcuellar** [desktop/desktop#14723]
### The problem

after new update, in mac, the github desktop dont open.

### Release version

3.0.1

### Operating system

macOS 10.13.6

### Steps to reproduce the behavior

1. try to open the app
2. the app dont open

### Log files

i cant access because dont open to get logs.

**Comment by PeyTy** [comment]
Same, infinite CPU and RAM usage
Windows 10
3.0.0 works fine (previous installation wasn't deleted in `AppData` so I could test it)

**Comment by leedavidcuellar** [comment]
the problem happened in mac, i tryed uninstalled but doesn't work.

**Comment by creold** [comment]
Confirm the problem on OS X 10.13.6 Intel. 3.0.2-beta1 also does not work

**Comment by sergiou87** [comment]
Hey @leedavidcuellar @PeyTy @creold ! Sorry about that, please take a look at https://github.com/desktop/desktop/issues/14712#issuecomment-1145013673 for a test build with a fix for the issue.

We're gonna deploy a new beta today with the issue fixed, and I'll announce it in that conversation when it happens.

**Comment by sergiou87** [comment]
We just deployed 3.0.2-beta2 with the fix if you don't want to use a test build 😄 

You can download it from https://desktop.github.com/beta

**Comment by leedavidcuellar** [comment]
Thank you 😄. the problem was resolved.
