### ISSUE TITLE
Changing file name's letter case doesn't count as a modification

### ISSUE THREAD

**Issue by crosby-moe** [desktop/desktop#14731]
### The problem

GitHub Desktop doesn't view changing the letter case in a file's name as a modification, so when I tried to do so in java, the class name inside the file was correctly changed, whilst the file name remained the same. This caused my GitHub actions workflow to fail while my dev environment was working perfectly.

### Release version

Version 3.0.1

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Create a file, ex. GuiHandler
2. Commit to GitHub
3. Rename the file, but only change the letter case, ex. GUIHandler

**Comment by tsvetilian-ty** [comment]
@RacoonDog See https://github.com/desktop/desktop/issues/2672#issuecomment-329011490

**Comment by steveward** [comment]
@RacoonDog like @tsvetilian-ty shared via that link, this is the expected behavior based on `core.ignorecase`. You can use `git mv <old_file_name> <new_file_name>` from the command line to rename the file -- Git will detect this change and allow you to commit it. I hope that helps!
