### ISSUE TITLE
app is running very slow

### ISSUE THREAD

**Issue by SahiZahidi** [desktop/desktop#14736]
### The problem

The desktop version of github is working very slow , specially while commiting codes, and using features like push , pull and fetch. 

### Release version

Version 3.0.1 (x64)

### Operating system

Windows 10 Home Single Language version - 21H2 OS - 19044.1706

### Log files

The desktop version of github is working very slow , specially while commiting codes, and using features like push , pull and fetch ,

**Comment by steveward** [comment]
Thanks for the issue @SahiZahidi. We are tracking performance issues in https://github.com/desktop/desktop/issues/13586, you can follow along there for updates. Feel free to share your log file there which could be helpful in giving us more information about the issue.
