### ISSUE TITLE
Github Desktop won't open: macOS High Sierra (10.13.6)

### ISSUE THREAD

**Issue by nataliey16** [desktop/desktop#14735]
My Github Desktop won't open when I click on the application icon.

I tried fixing this by deleting and redownloading the newest version but nothing loads open after clicking on the application. 
It worked perfectly fine until I meant to drag my Github folder (containing my code) onto VS Code but accidentally released it on the Github desktop icon in the doc. 

I am a beginner coder so any help would be appreciated! Thanks!

**Comment by markseuffert** [comment]
Github Desktop version 3.0.1 is not working on macOS High Sierra, as far as I know. You can go to website -> beta -> download. This should fix the problem. See also #14712.

**Comment by nataliey16** [comment]
Awesome that worked! Thank you!

**Comment by jdaw1** [comment]
I had same problem. And https://desktop.github.com/beta/ worked for me. Thank you.

**Comment by fusi-sdm** [comment]
Hi, same problem here with High Sierra. Downloading the Beta version worked for me too. Thank you!

**Comment by steveward** [comment]
Thanks for sharing the link to the beta @markseuffert. This fix will be going out in an upcoming release. I'm going to close this out.

**Comment by Miguelit023** [comment]
NECEITO AYUDA NO ME FUNCIONA EN HIGH SIERRA
