### ISSUE TITLE
Github Desktop on maximized mode goes on the other monitor when focused

### ISSUE THREAD

**Issue by Swiftly1** [desktop/desktop#14734]
### The problem

When I maximize GH Desktop, then small part of it (right edge?) appears on second monitor

which is very annoying

This can be prevented by manually resizing the whole window

![obraz](https://user-images.githubusercontent.com/77643169/172018110-e9350dae-11f1-4126-9136-cde038e2440a.png)

Other screens:

Fully, Manually Resized (works OK):

![obraz](https://user-images.githubusercontent.com/77643169/172018189-f0823f2d-55ba-48b7-b244-41f7567f5ecd.png)

Maximized with focus on Windows Terminal - right, (works OK):

![obraz](https://user-images.githubusercontent.com/77643169/172018256-9bc1efe9-b522-4fcc-a2e5-d1cd84ec4b51.png)

Maximized with focus on GH Desktop - left, (works not OK):

![obraz](https://user-images.githubusercontent.com/77643169/172018212-9ea45acb-cd6f-4db3-a50f-661ce6d9950d.png)

Do you notice that white lane on the last screenshoot between apps?

that's it

### Release version

3.0.1

### Operating system

Windows 10

### Steps to reproduce the behavior

Open GH Desktop in maximized mode

Focus GH Desktop

Notice that it goes on second monitor

**Comment by tsvetilian-ty** [comment]
👋 @Swiftly1 that's a known issue #13939

**Comment by tidy-dev** [comment]
(Closing in favor of issue linked above)
