### ISSUE TITLE
Issues with character diff highlighting

### ISSUE THREAD

**Issue by safetycar** [desktop/desktop#14737]
### The problem

For quite some time I've been seeing issues with diff highlighting.
Usually about no highlight of word changes.

I've been trying to catch something meaningful worth opening an issue and I think I've finally found it.
The issues have different form, nor the unified version, nor the split version work 100% of the time.
One fails in some contexts and the other fails in others.

### Release version

3.0.1 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Create the file and modify lines 2 and 4 as shown in the image.

![GitHub Desktop](https://user-images.githubusercontent.com/536820/172047809-4005c960-f030-4004-ad4e-b0d68ea2f257.png)

For the unified display: 
It is highlighting the char on line 2, which isn't showing any deletion over it.
The change for line 4 should start on one line and finish on the next, but something else is going on there.

For the split display:  (not in the image)
The lines are presented with a better shape but its chars are not highlighted in darker green.

**Comment by safetycar** [comment]
I'm not seeing this labeled yet.
Is it only happening to me?

**Comment by safetycar** [comment]
I've installed the beta hoping it would be fixed by https://github.com/desktop/desktop/pull/14710
But it wasn't.
I'm using a simple txt file for the test.

**Comment by steveward** [comment]
Thanks for the issue @SafetyCar. It looks like this is the same as some reports we've seen in https://github.com/desktop/desktop/issues/2700. Does that seem to align with what you are seeing?

**Comment by safetycar** [comment]
On appearance that was my problem at the beginning.
But please take a look at the example I showed. It shows something actually failing, it should be easier to analyze than something that does not appear.

**Comment by safetycar** [comment]
I've reviewed the other issue a bit more and github web is doing something different but also failling.
The character differences don't appear, only the line ones:
![aaa](https://user-images.githubusercontent.com/536820/173612729-20396fe3-cb5c-4403-9b4c-df52ea94213a.png)

**Comment by steveward** [comment]
I'm going to close this out in favor of https://github.com/desktop/desktop/issues/2700 so that we can centrally track these diff issue reports.
