### ISSUE TITLE
I can not push/clone my Private repo

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#14745]
### The problem

Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.

### Release version

latest

### Operating system

windwos

### Steps to reproduce the behavior

use GitHub

**Comment by tsvetilian-ty** [comment]
👋 @wihola could you share the log files from GitHub Desktop? (Help > Show Logs...)

**Comment by ghost** [comment]
I have found the reason:
This doesn't work `ssh-keygen -t ed25519 -C "your_email@example.com"`
This works `ssh-keygen -t rsa -b 4096 -C "youremail@example.com"`
I spent an hour figuring out this.
