### ISSUE TITLE
Please make "Add Favorite Repository"

### ISSUE THREAD

**Issue by dancinlife** [desktop/desktop#14746]
### The feature request

Add Favorite Repository

### Proposed solution

- Add Favorite Repository

**Comment by tsvetilian-ty** [comment]
@dancinlife 👋 there is such a feature request #8183. Perhaps at some point, it will be present in GitHub Desktop.

**Comment by steveward** [comment]
@dancinlife at this time we don't have plans of changing the repository list, but this may be something we reconsider again in the future. Thanks for the feedback.
