### ISSUE TITLE
Set editor separately for each repository

### ISSUE THREAD

**Issue by Zeriz** [desktop/desktop#14749]
### The feature request

Setting editor separately for each repository would be very helpful for when you have projects in multiple languages, I.e.: I have python projects where I use  PyCharm, PHP projects where I use PHPStorm and other projects (nodejs, vjs, etc) where I use  VSCode. 

### Proposed solution

![Screenshot 2022-06-07 at 10 22 30](https://user-images.githubusercontent.com/22762988/172332573-e0591c7a-77d2-47a0-88a4-e6871c2e1e7a.png)

You are in "name of repo"
Select an editor for this repository only:
[dropdown]

**Comment by steveward** [comment]
Thanks for the issue @Zeriz. This was requested in https://github.com/desktop/desktop/issues/12195, so I'm going to reference it there.
