### ISSUE TITLE
打开软件闪退

### ISSUE THREAD

**Issue by yzs2011** [desktop/desktop#14747]
### The problem

2022年6月6号,开始打开软件就闪退
Mac 10.13.6系统 Intel Core i5 2.7GHz
github  Desktop 直接官网下载Mac版本 最新的 3.0.1
2022年6月4号 还在正常使用

### Release version

3.0.1 Mac

### Operating system

Mac 10.13.6 Intel Core

### Steps to reproduce the behavior

就直接打开弹2下 闪退

### Screenshots

>

**Comment by sergiou87** [comment]
Hi @yzs2011!

Could you try the latest beta from https://desktop.github.com/beta and see if that one works? I wonder if this is the same as #14712 

Please let me know if the latest beta works for you. Thanks!

**Comment by yzs2011** [comment]
> 你好@yzs2011！
> 
> 您可以尝试来自https://desktop.github.com/beta的最新测试版，看看它是否有效？我想知道这是否与[#14712相同](https://github.com/desktop/desktop/issues/14712)
> 
> 请让我知道最新的测试版是否适合您。谢谢！

谢谢 这个 最新测试版 可以用,没问题.

**Comment by steveward** [comment]
Glad to hear that got things working @yzs2011. I'm going to close this out.
