### ISSUE TITLE
Github Desktop 3.0.1 Does Not Launch on Mac OS 10.13 (High Sierra)

### ISSUE THREAD

**Issue by doppelhub** [desktop/desktop#14757]
### The problem

Github Desktop 3.0.1 will not launch.
I've reproduced this behavior on two machines, both running 10.13.6 (17G14042).

Correct behavior:
1: Download Github Desktop 3.0.0.
2: Place Github Desktop 3.0.0 in Applications Folder.
3: Launch Github Desktop 3.0.0
Result: Github Desktop Launches and works without issue.

Workaround:
-Continue using Github Desktop 3.0.0

### Release version

3.0.1

### Operating system

High Sierra 10.13.6

### Steps to reproduce the behavior

Steps to reproduce incorrect behavior:
1: Download Github Desktop 3.0.1.
2: Place Github Desktop 3.0.1 in Applications Folder.
3: Launch Github Desktop 3.0.1.
Result: Github Desktop crashes immediately on launch.  No GUI elements shown to user.

Console log reports:
Jun  7 18:23:07 Chonker com.apple.xpc.launchd[1] (com.github.GitHubClient.43160[1298]): Service exited with abnormal code: 7

### Log files

GUI will not launch.

**Comment by tsvetilian-ty** [comment]
@doppelhub 👋  fix for that issue is available in the [beta channel](https://desktop.github.com/beta/)

**Comment by doppelhub** [comment]
Fixed in 3.0.2-beta4
