### ISSUE TITLE
Customise new branch promt default

### ISSUE THREAD

**Issue by moritztim** [desktop/desktop#14752]
### The feature request

![new branch prompt settings](https://user-images.githubusercontent.com/90388353/172381965-3e12b4ac-e188-48db-8a4f-9fe8e841e4e7.png)
Right now we can only deside that either one of the options is chosen or that we get to choose. The default in that case is currently not customisable but it would be quite nice if it was.

### Proposed solution

The settings menu could have a sub section that appears when clicking on "Ask me where I want the changes to go" that allows one to switch between the new or the current branch.

### Additional context

**Mockup:**

**If I have changes and I switch branches...**
  
- Aks me where I want the changes to go
  - Bring them to my new branch by default
  - Stash and leave my changes on the current branch by default
- Always bring them to my new branch
- Always stash and leave my changes on the current branch

**Comment by steveward** [comment]
Thanks for the issue @moritz-t-w. I'm not sure I understand the request -- are you wanting the option to set a default option when the prompt appears when switching branches?

**Comment by Mzul86** [comment]
Browser web

**Comment by Mzul86** [comment]
Google Chrome

**Comment by moritztim** [comment]
> Thanks for the issue @moritz-t-w. I'm not sure I understand the request -- are you wanting the option to set a default option when the prompt appears when switching branches?

Yes.

**Comment by moritztim** [comment]
> are you wanting the option to set a default option when the prompt appears when switching branches?

Yes. Like I said.

**Comment by steveward** [comment]
@moritz-t-w I'm going to close this out as at this time we don't have any plans to provide this type of option directly in the prompt. If this is something we hear further feedback about in the future we can look into this again. Thanks for using GitHub Desktop.
