### ISSUE TITLE
ERROR: failed to receive handshake, SSL/TLS connection failed

### ISSUE THREAD

**Issue by wanjohiryan** [desktop/desktop#14758]
### The problem

I keep getting "**fatal: unable to access 'https://github.com/${user}/${repo}.git/': schannel: failed to receive handshake, SSL/TLS connection failed**"  while trying to push my code to a remote repo.

This error is completely random, and the app will sometimes push to Github while still displaying it, and other times it will not.

Other times, I'll have to restart the app, and it'll work fine the first time, but then throw the error again in subsequent commits.

### Release version

Version 3.0.0 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Create a local repository
2. Push to Github 

### Log files

[2022-06-08.desktop.production.log](https://github.com/desktop/desktop/files/8858005/2022-06-08.desktop.production.log)

### Screenshots

_no reponse_

### Additional context

_no reponse_

**Comment by steveward** [comment]
Thanks for the issue @wanjohiryan. Are you running any antivirus software, or behind a proxy/firewall that could be interfering with your connection?

**Comment by wanjohiryan** [comment]
Hi @steveward 

No i am not. (i have not installed or used any antivirus or VPNs recently either)

**Comment by steveward** [comment]
@wanjohiryan thanks for the update -- it's strange that this is not happening consistently. 

Can you let me know what the output of `git config http.sslBackend` shows?

**Comment by wanjohiryan** [comment]
Hi, @steveward. Here is the output;

`openssl`

**Comment by steveward** [comment]
Can you try switching to `schannel` to see if that succeeds?

`git config --global http.sslBackend schannel` is the command you will want to run.

**Comment by VikalpHarbola** [comment]
> git config --global http.sslBackend schannel

This helped to solve this issue

**Comment by goshp** [comment]
I am trying to run this commands (vagrant box add bento/centos-7 --provider=virtualbox
and vagrant up) on git batch but the below error keeps pumping up: I need help

schannel: failed to receive handshake, SSL/TLS connection failed

![19-07-2022 11-01-24](https://user-images.githubusercontent.com/51539331/179725056-452c616f-4e6f-41d5-881e-ba5a7df0f047.png)
![11-07-54](https://user-images.githubusercontent.com/51539331/179725815-b4a40baa-28df-442d-bcba-c37687d4404d.png)

**Comment by firthro** [comment]
it would be really nice to have screenshots for a resolution of this in Visual Studio

**Comment by gkogko130** [comment]
Ok

**Comment by ossimantylahti** [comment]
I can confirm that this is an issue with Windows 10 client. Suddenly repositories from Git started to complain that they cannot be cloned. I do not have Git installed on command line on this Windows box, so I cannot execute the git config command. Uninstalling and reinstalling github application does not do anything.

**Comment by aravindswamy-shell** [comment]
Try changing the wifi connection.

**Comment by ossimantylahti** [comment]
I am using wired connection. How

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by metacraft-hq** [comment]
Thank you -- `git config --global http.sslBackend schannel` worked for me

**Comment by snowman** [comment]
![image](https://github.com/desktop/desktop/assets/16096559/6b578da5-9bd9-471b-a0c6-c3b76454a81d)

Make sure the proxy client is running
