### ISSUE TITLE
Root process does not terminate on exit, v3.0.1 Windows

### ISSUE THREAD

**Issue by NeArnold** [desktop/desktop#14759]
If I run the Windows version 3.0.1 (x64) on a Windows 10 machine, it orphans the root process (it doesn't close) after all other processes have terminated on program exit.  This termination can be an upper right X window click or via the file:exit menu.
Using process explorer here is before termination:
![image](https://user-images.githubusercontent.com/62027872/172524659-ff7986ba-dd0c-42f3-8cfa-53392f62f293.png)
and after termination
![image](https://user-images.githubusercontent.com/62027872/172524777-fa936705-700d-4502-841e-df3f97f45baa.png)
This identical behavior has been observed to two separate Win 10 x64 machines patched through May 2022.  It did not occur on v3.0.0.

**Comment by tsvetilian-ty** [comment]
@NeArnold thanks for the report. Fix is available in the [beta channel](https://desktop.github.com/beta/)

**Comment by sergiou87** [comment]
As @tsvetilian-ty says, fixed in #14733 😄
