### ISSUE TITLE
Github Desktop - Running Very Very Slow

### ISSUE THREAD

**Issue by saaemfaridi** [desktop/desktop#14763]
### The problem

My pc is running fine when i have Github Desktop opened in background and when i maximize the github desktop window Only the github desktop window is like running very slow af .

When i click on a dropdown it takes me a lot of time

### Release version

Latest

### Operating system

Windows 10

**Comment by saaemfaridi** [comment]
Help me someone

**Comment by tsvetilian-ty** [comment]
👋 @saaemfairdi07 could you share the log file from GitHub Desktop? You can find it by clicking "Help > Show logs ..." if the reason for the slowdown is an error, it will be present in the logs. Also, if it's a generic performance issue, those are tracked in #13586

**Comment by steveward** [comment]
@saaemfairdi07 we're tracking performance issues in https://github.com/desktop/desktop/issues/13586 -- if can share your log file that should give us more information about if you're running into a similar issue.
