### ISSUE TITLE
VS-Code : Github Desktop Sync

### ISSUE THREAD

**Issue by sushantshah-dev** [desktop/desktop#14765]
### The feature request

This feature would likely be elective. The feature will allow us to automatically change the project in Github Desktop based on the last active VS Code window. 

### Proposed solution

The solution is to detect the last active VS Code window and switch to the git repository in the VS Code project if present. This can be done using an extension that links between the Github Desktop installation and all the VS Code instances.

**Comment by steveward** [comment]
Thanks for the issue @sushantshah-dev! This is an interesting idea, but likely not something we would tackle for a specific editor since we're a small team. I'm going to close this out.

**Comment by Black-Blaze** [comment]
Hey! Can The Community Make The Bridge? If We Get A Way To Interact With Github Desktop Programmatically, It Would Be Helpful
