### ISSUE TITLE
Text selection is too tall in diff view’s shrunk code element

### ISSUE THREAD

**Issue by yakovmanshin** [desktop/desktop#14760]
### The problem

In diff view’s shrunk code element (the one with blue background; see screenshot), text selection spans across the entire height of the element, while it should only cover the actual text.

### Release version

3.0.1

### Operating system

macOS 12.4

### Steps to reproduce the behavior

1. Make a commit with changes in two places of a single file, distant from each other;
2. Open the commit in History;
3. Select some text in the pane that appears between changed regions and allows to expand code (“shrunk code element”).

### Screenshots

<img src="https://user-images.githubusercontent.com/4648742/172565666-81b45851-8e59-48be-9ce4-085fd5d52b98.png">

**Comment by steveward** [comment]
Thanks for reporting this @yakovmanshin!

**Comment by biel-correa** [comment]
Just to note that this also happens on Windows but smaller

![image](https://user-images.githubusercontent.com/56176344/173673049-3ab71384-05cc-447b-ae8c-0e2150005083.png)

**Comment by yakovmanshin** [comment]
Hey @biel-correa! I believe your screenshot depicts a different situation: you show the actual diff (portions of removed code on red background and added on green), while the original report was about the collapse / expand panel you get when your file has several changes relatively distant from each other (so the unmodified code in between them is collapsed).

**Comment by biel-correa** [comment]
@yakovmanshin yep, found it and it looks the same

![image](https://user-images.githubusercontent.com/56176344/173683442-5198d7f9-fd16-4637-9dad-2567facc83b3.png)
> I'm using dark theme

**Comment by biel-correa** [comment]
I reduce the padding of this type of line in half, so now it looks like this:

![image](https://user-images.githubusercontent.com/56176344/173699847-bb405c3b-daf3-480a-a9da-f2898d544ac3.png)

This is how it looks without selecting the text:

![image](https://user-images.githubusercontent.com/56176344/173700178-be52c43f-b56a-4d60-bad3-0502f458e6aa.png)

It\`s not big but it\`s also not the same size of the other lines, the previus padding was 14px and now is 7px, the expand line has 5px of padding. Tell me what you think!

**Comment by yakovmanshin** [comment]
To be honest, the panel now stands out less prominently, so it’s easier to be confused for a plain line of code, even despite the difference in background color ☹️

Would it be possible to add top and bottom margins to the text label and not stretch it to entire panel height? Sorry if the question sounds silly—I’ve never dealt with Electron.

**Comment by biel-correa** [comment]
Also thought the same, I tried adding the margin but it gives a strange look

![image](https://user-images.githubusercontent.com/56176344/173712943-d0c45c8f-e43d-4928-a86f-88a98de16890.png)

**Comment by biel-correa** [comment]
I think 10px would be the sweet spot

![image](https://user-images.githubusercontent.com/56176344/174159493-b90e2cb5-b4a9-476d-adb7-6a23b80fcdf8.png)

**Comment by yakovmanshin** [comment]
To me, the objectives here seem contradicting, and either compromise is a bad one: leaving the panel tall enough is good for its overall visibility and expand buttons’ UX, yet bad for text selection; decreasing the panel’s height is good for text selection but bad for the UI overall ☹️

Is it really not possible to make the text label not take up the entire panel’s height, so only a portion of the panel is highlighted on selection?

![](https://user-images.githubusercontent.com/4648742/174163794-ecdff556-f020-4e7d-927b-486283f54823.png)

**Comment by biel-correa** [comment]
I want to get to this result but doesn't seem to be possible without changing part of the component, I'll check what I can do

**Comment by niik** [comment]
I believe this was fixed when we switched the engine powering unified diffs in v3.3.5. Going to close this!

![Image](https://github.com/user-attachments/assets/e8463134-c684-49d7-9c1e-e7fd5861337b)
