### ISSUE TITLE
Crash on launch macOS 10.12

### ISSUE THREAD

**Issue by couleurs** [desktop/desktop#14771]
### The problem

Hello! With the latest update (3.0.1) I'm no longer able to open Github Desktop on mac OS 10.12.6
It seems the app crashes on launch.
Thanks!

### Release version

3.0.1

### Operating system

mac OS Sierra 10.12.6

### Steps to reproduce the behavior

Open app

**Comment by sergiou87** [comment]
Hello! 👋 
Please take a look at the latest beta from https://desktop.github.com/beta which includes #14719 and fixes the issue.

Sorry about that! We'll release a production build with the fix next week (see #14769)

**Comment by couleurs** [comment]
Wonderful, works perfectly! Thanks so much Luffy :)
