### ISSUE TITLE
Create Github Desktop app that supports x86 operating system

### ISSUE THREAD

**Issue by pham-tuyen** [desktop/desktop#14779]
### The feature request

Make a x86 Github Desktop please

### Proposed solution

It will help Github Desktop more users.

**Comment by steveward** [comment]
Thanks for the issue @pham-tuyen. What operating system are you currently running? 

Supporting 32-bit isn't on our radar, but some discussion and experimentation did happen around this in https://github.com/desktop/desktop/issues/6874. I'm going to close this out as it's not something we have planned.

**Comment by pham-tuyen** [comment]
> Thanks for the issue @pham-tuyen. What operating system are you currently running?
> 
> Supporting 32-bit isn't on our radar, but some discussion and experimentation did happen around this in #6874. I'm going to close this out as it's not something we have planned.

I'm using Windows 7 SP1
