### ISSUE TITLE
Fails to connect to GitLab repos with 2FA (Personal Access Token)

### ISSUE THREAD

**Issue by srodriguez142857** [desktop/desktop#14778]
### The problem

I was able to access the GitLab repos with the user and password.
After upgrading to v3.0.1 (latest), it couldn't connect and asked for a "Personal Access Token" (PAT) from the GitLab account.
I set the 2FA and generated a PAT.
Now, I could not even refresh/access the GitLab repos.
I have the following error:

```
remote: Retry later  
fatal: unable to access 'https://gitlab.domain/user/project/': The requested URL returned error: 429
```

### Release version

Version 3.0.1 (x64)

### Operating system

Edition	Windows 11 Pro Version	21H2 Installed on	‎2022-‎01-‎24 OS build	22000.708 Experience	Windows Feature Experience Pack 1000.22000.708.0

### Screenshots

![image](https://user-images.githubusercontent.com/9869215/172993523-76217cce-5a07-463b-970c-41e9ad944f9f.png)

**Comment by steveward** [comment]
@srodriguez142857 thanks for the issue. Did you follow the steps here to add the token to GitHub Desktop?

https://github.com/desktop/desktop/blob/development/docs/integrations/gitlab.md

I would recommend deleting the existing token from `Windows Credential Manager` > `Windows Credentials` and trying to add the new token. The `429` error is coming from GitLab's servers so you will need to reach out to them if you continue to have issues. I'm going to close this out but let me know if you have any questions about adding the token to GitHub Desktop.

**Comment by srodriguez142857** [comment]
Hi, Steve.

Thank you for your swift reply.  Yes, I did follow the steps there.
Interestingly, after some time (and restarting the GitHub Desktop app), I
could access and connect to the GitLab repos without any problems.
I'm not sure why I got that 429 error at the beginning.  Anyways, it was
resolved after a while.
All is good now.  Thanks.

/$¡rm
Best regards,
Sergio J. Rodríguez M.
