### ISSUE TITLE
Newest update broken on macOS (3.0.1)

### ISSUE THREAD

**Issue by jakerieger** [desktop/desktop#14776]
### The problem

The app opens and immediately closes. Opening the binary at `Contents/MacOS/GitHub Desktop` reveals an error: `Cannot create BrowserWindow before app is ready`. Reverting to the previous version worked fine.

### Release version

3.0.1

### Operating system

macOS 10.13.6 (High Sierra)

### Steps to reproduce the behavior

1. Open the app

### Screenshots

![Screen Shot 2022-06-09 at 7 08 39 PM](https://user-images.githubusercontent.com/19679090/172959805-2ce1f980-9c95-4fff-b134-3794345123c6.png)

**Comment by sergiou87** [comment]
Please install the latest beta from https://desktop.github.com/beta with the fix (#14719 )

We'll release a new production build next week with the fix too, if you prefer to wait!
