### ISSUE TITLE
Github Desktop keeps running in the background despite closing the application

### ISSUE THREAD

**Issue by seirdotexe** [desktop/desktop#14786]
### The problem

When closing Github Desktop, the process keeps running in the background. The processes never get killed, so if you keep opening the application, you'll get more processes. I also tried reinstalling but that didn't work.

### Release version

Version 3.0.1 (x64)

### Operating system

Windows 10 21H2

### Steps to reproduce the behavior

1. Open Github Desktop
2. Close Github Desktop
3. GitHubDesktop.exe is still running in the background

### Screenshots

![image](https://user-images.githubusercontent.com/80536518/173201668-91ef12c8-e26f-4789-8098-92f50743042a.png)

### Additional context

Here's what I'd see on a day of work
![image](https://user-images.githubusercontent.com/80536518/173201722-7a5454b5-c905-4134-add5-1ca4e044620e.png)

**Comment by danny007in** [comment]
probably fixed in https://github.com/desktop/desktop/pull/14769

**Comment by tsvetilian-ty** [comment]
@seirdotexe, as @danny007in mentioned, the fix will be available in GitHub Desktop 3.0.2 (next week). If you want to try it now, you can download a [beta version](https://desktop.github.com/beta/).

**Comment by seirdotexe** [comment]
@tsvetilian-ty Thank you, I'll be waiting for the stable release.
