### ISSUE TITLE
After updation github is not working properly

### ISSUE THREAD

**Issue by PrakNew** [desktop/desktop#14796]
### The problem

Github desktop automatically updated and now it is not able to find the path 
C:\Users\prakh\AppData\Local\GitHubDesktop\app-3.0.2\resources\app\git\cmd\git.exe

there is no cmd folder and besides that, there is no git.exe file so I guess after updation git.exe file just deletes.

### Release version

Version 3.0.2 (x64)

### Operating system

Windows 10

**Comment by tsvetilian-ty** [comment]
@PrakNew are you trying to use it from the command line, or it's an error from GitHub Desktop? 

- Using the embedded version of git that comes with GitHub Desktop is not recommended. Check out: https://github.com/desktop/desktop/issues/3708#issuecomment-354665183
- If you see the error in GitHub Desktop, please upload the log files "Help > Show logs..." The files are generated daily!
