### ISSUE TITLE
amd64 file for deb

### ISSUE THREAD

**Issue by kbully777** [desktop/desktop#14793]
need a amd64 downloadlink

**Comment by sergiou87** [comment]
Thanks for the issue @kbully777 . At this time there are no official builds of GitHub Desktop available for Linux, but a former developer of GitHub Desktop maintains a fork with Linux builds available for download:

https://github.com/shiftkey/desktop/releases

You can also follow along with https://github.com/desktop/desktop/issues/1525 for updates about an official Linux release.
