### ISSUE TITLE
Commit Author is a Deleted Account

### ISSUE THREAD

**Issue by randomizednum** [desktop/desktop#14797]
### The problem

I used to have a different Github account, but I deleted it. Somehow, commits made from Github Desktop are apparently made by my old account. I'm signed in to my current account in Github Desktop.

### Release version

3.0.2

### Operating system

Windows 10 21H1 64 bit

### Steps to reproduce the behavior

1. Log into an account, preferably a temporary one, in Github Desktop.
2. Delete the account.
3. Create a new account.
4. Sign in to your new account in Github Desktop.
5. Create a new repository.
6. The author of the commits **should** be the deleted account.

### Log files

[2022-06-13.desktop.production.log](https://github.com/desktop/desktop/files/8893427/2022-06-13.desktop.production.log)

### Screenshots

![github_issue_screenshot_1](https://user-images.githubusercontent.com/101424255/173417064-efb1e4d3-9881-4853-a207-673bf2033fcf.png)
![github_issue_screenshot_2](https://user-images.githubusercontent.com/101424255/173417862-5f1852ca-739b-45c6-8eed-a25d399fc6a2.png)

### Additional context

A repository which was affected by this problem: https://github.com/randomizednum/single-statement-tic-tac-toe

**Comment by steveward** [comment]
@randomizednum you can change this by going to `Options` > `Git`, although GitHub Desktop should detect that your email address is mismatched and notify you in the commit pane. 

Can you let me know if you seen the "This email address does not match..." message in the `Git` settings view?

**Comment by randomizednum** [comment]
> @randomizednum you can change this by going to `Options` > `Git`, although GitHub Desktop should detect that your email address is mismatched and notify you in the commit pane.
> 
> Can you let me know if you seen the "This email address does not match..." message in the `Git` settings view?

I see the message. Why isn't it shown around the commit button? That would make it noticeable.

**Comment by steveward** [comment]
It should be -- I'm not sure why it isn't in this specific case. I verified it still works in my app.

Can you try using the `Other` option in the dropdown and enter a bogus email to see if it detects the incorrect email correctly?

**Comment by randomizednum** [comment]
It doesn't. It even shows one of the default profile pictures. There still is a warning in Options>Git.

Actually, after publishing the repository (it was local previously), now I can see a warning next to the profile picture.

**Comment by steveward** [comment]
Thanks @randomizednum -- I missed that it wasn't published yet. We don't show this message for `Other` repositories since we're can't assume you're pushing these repositories to GitHub. The improvements discussed in https://github.com/desktop/desktop/issues/14692 would be a solution to this issue as we could suggest updating the Git config during the authentication process. I'm going to close this out.
