### ISSUE TITLE
Repository folders + sorting?

### ISSUE THREAD

**Issue by andrewhong04** [desktop/desktop#14799]
### The feature request

Once someone has around 40 repositories, it's hard to keep track of the long scrolling list of repositories in your sidebar. 

### Proposed solution

I propose that GitHub Desktop should have folders to organize what kind of repository belongs together. Or if folders aren't the user's thing, we could add some sort of sorting feature that sorts the repositories from last modified.

**Comment by tsvetilian-ty** [comment]
Thanks for this feature request @novialriptide. Currently, there are no plans to implement repository folders. See https://github.com/desktop/desktop/issues/10201#issuecomment-658693653

I'm going to close this one since you can follow the discussions in the comment above.

**Comment by ghnp5** [comment]
I was just coming here to suggest the exact same.  @novialriptide   @tsvetilian-ty 

Either create our own grouping/folders for organizing the repos,
or at least GitHub Desktop could group the repos based on the folder they're at.

So, if we have some directory structure like:

Repos
- Partners
   - Repo 1
   - Repo 2
- Common
   - Repo 3
   - Repo 4
- DevTools
   - Repo 5
   - Repo 6
- ProjectSomething
   - Repo 7 Web
   - Repo 8 API

GitHub Desktop could have an optional View to reorganize and sort repos this way.
