### ISSUE TITLE
Repository Tags

### ISSUE THREAD

**Issue by Furkan-Gurel** [desktop/desktop#14802]
### The feature request

When I copy two or more from the same repos, I get confused between them, so if the tag or coloring feature comes, I think we will prevent the applications from mixing with each other.

### Proposed solution

Coloring or marking repo domains as tags

**Comment by tidy-dev** [comment]
@Furkan-Gurel Thanks for your suggestion! Unfortunately, I am not sure I follow. Are you looking for an easy way to distinguish two clones of the same repo? 

If so, you can right-click on a repos name and choose `Create Alias`, this will allow you to display a different name to distinguish from another clone of the same repo.

**Comment by Furkan-Gurel** [comment]
@tidy-dev Thanks for the help.I will use this feature
