### ISSUE TITLE
Resizing problem on 14" laptop screen

### ISSUE THREAD

**Issue by andrey-levichev** [desktop/desktop#14808]
### The problem

My laptop has 14" screen running Windows at 150% scaling with 120% text scaling. It's comfortable for my eyes. GitHub Desktop starts occupying most of the screen with "Commit to master" button at the bottom visible. Any attempt to resize or maximize the window cause the bottom portion of the UI to go off screen, including the commit button.

### Release version

v3.0.2

### Operating system

Windows 11

**Comment by tsvetilian-ty** [comment]
Thanks for the report @andrey-levichev

That is a known issue, and it's linked to the electron version used in GitHub Desktop. You can follow #13940 for more information.

**Comment by steveward** [comment]
I'm going to close this out as a duplicate report, thanks again for the report @andrey-levichev.
