### ISSUE TITLE
Configure external editor per project

### ISSUE THREAD

**Issue by crizzis** [desktop/desktop#14809]
### The feature request

As far as I can tell, the external editor can only be configured globally. 

This makes no sense when working with multiple languages / technologies. It's pretty tedious to change the setting whenever you check out a new project and then change it back when opening a previously checked out one. 

### Proposed solution

Would it be possible to make the external editor a per-project setting? 

Probably a global setting still make sense for folks that usually work with just a single technology / use VSCode for everything. This setting could instead work as a default option for newly checked out projects, though.

**Comment by steveward** [comment]
Thanks for the issue @crizzis -- this is being tracked in https://github.com/desktop/desktop/issues/12195 so you can follow along there for updates. I'm going to close this out.
