### ISSUE TITLE
Application crashes upon setting spellcheck to system language

### ISSUE THREAD

**Issue by abu-co** [desktop/desktop#14817]
### The problem

When I accidentally clicked `Set spellcheck to system language`, the whole application crashed, yielding the following error:
```
2022-06-16T09:22:55.962Z - error: [main] Error: Invalid language code provided: "zh-CN" is not a valid language code
    at click (C:\Users\<username>\AppData\Local\GitHubDesktop\app-3.0.1\webpack:\[name]\app\src\main-process\menu\build-spell-check-menu.ts:109:26)
    at MenuItem.click (node:electron/js2c/browser_init:73:1908)
    at EventEmitter.a._executeCommand (node:electron/js2c/browser_init:81:2453)
```

I've tested this multiple times, and every attempt resulted in a crash.

The problem probably has something to do with this:
https://github.com/desktop/desktop/blob/2389b82ba1058dbe28d45c293647362514bb0eb6/app/src/main-process/menu/build-spell-check-menu.ts#L109

### Release version

Version 3.0.2 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Set system language to Simplified Chinese
2. Right-click on a misspelled word
3. Select `Set spellcheck to system language`
4. (Crashes)

### Screenshots

![image](https://user-images.githubusercontent.com/52994294/174047242-2028d192-8d3f-493f-b824-cef0d6d9bdd4.png)

---

![image](https://user-images.githubusercontent.com/52994294/174047335-24758dc2-5bda-4576-b665-9c95d4b0214e.png)

**Comment by tsvetilian-ty** [comment]
Thanks for the report @abu-co! 

It looks like `zh-CN` is not supported by the spellchecker 😞 On Windows, the spellchecker is powered by Hunspell dictionaries ([more info](https://www.electronjs.org/docs/latest/tutorial/spellchecker)). 

I will open a PR with additional checks to make sure GitHub Desktop doesn't throw a critical error!
