### ISSUE TITLE
SEARCH BY COMMIT NAME

### ISSUE THREAD

**Issue by jaybsg** [desktop/desktop#14816]
### The feature request

Please give feature which gives filter search on commit name or description. 

**ex.** I am having so many branches for one repository and I have done changes to any one branch with commit name 'xyz'. now I have forgotten on which branch I have done the changes and i need to do the cherry pick the same to other branch. so I need to go through all branches to find commit 'xyz'. 

### Proposed solution

Add commit search option on branches or repository.

**Comment by CraigChilds94** [comment]
+1 

I thought about having a go at this the other day!

**Comment by tidy-dev** [comment]
@jaybsg Thanks for the suggestion. We are tracking around searching/navigation of the commit list on https://github.com/desktop/desktop/issues/7022. You can subscribe to it for any updates and thus, I am closing this one in favor of tracking feedback there.
