### ISSUE TITLE
GitHub desktop does not recognize changes to files

### ISSUE THREAD

**Issue by valay93** [desktop/desktop#14826]
### The problem

I add new files to a github repository locally (that has been cloned from a master repo on github) but github desktop does not detect these files and I cannot push new commits with these files. 

### Release version

Version 3.0.2 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Create new shell script in VS Code
2. Save the code file in cloned repository, locally
3. New file does not appear in GitHub desktop changes

**Comment by steveward** [comment]
@valay93 thanks for the issue. Does your repository have a `.gitignore` file that could be ignoring changes to specific filetypes/directories?

You can check this in GitHub Desktop by going to `Repository` > `Repository Settings` > `Ignored Files`. If that doesn't seem to be the issue, try opening the repository in the command line and running `git status` to see if anything shows there. It'd also be helpful if you could make a test change to an existing file.

**Comment by valay93** [comment]
Yes! I removed the ignored files and they started to show the new files. Some how the git ignore was using regexp to ignore files. Thank you,

**Comment by steveward** [comment]
Glad to hear things are working for you now!
