### ISSUE TITLE
acccount link

### ISSUE THREAD

**Issue by Ayomide200024** [desktop/desktop#14823]
### The problem

I'm unable to link my account to the Github desktop app.

### Release version

Version 3.0.1

### Operating system

Windows 11

**Comment by steveward** [comment]
Thanks for the issue @Ayomide200024. Can you share some specific details about where the authentication process is failing for you? Is it failing during the browser authentication process?

**Comment by tjmericka** [comment]
Yes it is failing diring the browser authenication process it never opens the browser and then I get the message in the screen shot that I sent in the original message.

**Comment by tjmericka** [comment]
click on GitHub Assignment Invite
click on assignment repository
click on code
click on Open with GitHub Desktop
Click on Clone
I get this message 
![image](https://user-images.githubusercontent.com/107413609/174651437-da8927de-5589-40f7-a9d7-fa149cf22107.png)
So I click on the GitHub.com option and I get this message
![image](https://user-images.githubusercontent.com/107413609/174651694-0afe89ec-ae99-4aea-ab3a-c537b43e77a4.png)
Then I click on continue with browser and then I get this message
![image](https://user-images.githubusercontent.com/107413609/174651836-a037e1e8-47bd-4bb4-99fb-1c584a72f0c6.png)

**Comment by tjmericka** [comment]
I answered the question with the information I posted above.

**Comment by Ayomide200024** [comment]
I have been able to find a solution.  Thanks for your help

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
