### ISSUE TITLE
Please add feature sort the branch list by time created

### ISSUE THREAD

**Issue by phnghue** [desktop/desktop#14828]
### The feature request

When the number branches going to many, my team increased conflict problem merging each time switching project and cloning source.
Due to the list of Other branches are not sorted correctly by date created and took a lot of time to find the latest branches and also mistake in reading the date.
![git branches](https://user-images.githubusercontent.com/5476425/174347896-5ca3a798-c8db-4e26-9e89-38597838eb90.png)

### Proposed solution

The solution is simple by sorted the list branches by date created. It'll save a lot of time when finding the latest branches.
Programmer that work on the same branch on different machine (company, home, different OS) will save lot of time when switching to latest work. 

It help us to avoid conflict merging, lost branch merging and rebuild run program multiple time to safe check the latest work (when the different algorithm code is super complex to read in some projects, modules and programming languages @@ ).

It's also helpful if we have some other sort option:  by date modify, date committed, name alphabet.

**Comment by steveward** [comment]
Thanks for the issue @phnghue, I am going to add this to https://github.com/desktop/desktop/issues/5155 where we are tracking this issue.

**Comment by rtemple6** [comment]
Having the option to sort the branch list would be _**amazing**_

**Comment by virati** [comment]
Yeah, kind of shocked this is still not a thing. Would drastically help my productivity to have a simple "sort by time" to quickly jump to the branch I just started.
