### ISSUE TITLE
be smarter about revoked authorization

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#1482]
### Description

Users can revoke the authorization for GitHub Desktop, and while we fail we don't provide any more smarts here around "Oh, your authorization isn't actually valid. Let's sign in again"

### Version

**GitHub Desktop version:** 0.5.1

**OS version:** macOS Sierra 10.12.4

### Steps to Reproduce

1. Sign into the app, completing the OAuth flow and authorizing the application
1. Add a private repository to the application, ensuring it is associated with your account
1. Point your browser at https://github.com/settings/applications and revoke the authorization for GitHub Desktop
1. Return to the application and press Fetch to trigger the authentication error

<img width="669" src="https://cloud.githubusercontent.com/assets/359239/26086239/e5df7e94-3a2c-11e7-84ee-8597d302ac6e.png">

Then, switch to Preferences:

<img width="494" src="https://cloud.githubusercontent.com/assets/359239/26086240/ee18bbf2-3a2c-11e7-9d02-b410327b742e.png">

**Expected behaviour:** a hint that the current authorization isn't working

**Actual behaviour:** nothing really

**Reproduces how often:** 100%

#### Additional Information

I'm open to ideas and suggestions around how we go about this, but from a functionality side we need:

 - some way to detect our authorization has been revoked
 - some hint (maybe not on the first authentication, but after a couple) to review your account settings
 - a way to validate in the preferences view that your account isn't valid, and to redo the login flow

**Comment by tierninho** [comment]
A side effect of this is found in the Clone repo list, as we do not surface any error message pointing to  a stale login as a culprit. The list simply does not load and shows a generic error message instead. 

Logging out and back in fixes the problem.

<img width="454" alt="screen shot 2018-11-14 at 9 35 58 am" src="https://user-images.githubusercontent.com/14828183/48501386-f5b1b980-e7f1-11e8-9739-c7982e767680.png">

tested on v1.5, windows 10

**Comment by steveward** [comment]
Thanks to the work of @sergiou87 in https://github.com/desktop/desktop/pull/12554 we now detect these scenarios and prompt for authentication. ✨
