### ISSUE TITLE
Authentication Fail when trying to access BitBucket repo with GitHub Desktop

### ISSUE THREAD

**Issue by darcycordell** [desktop/desktop#14831]
### The problem

I have followed the directions on this page exactly: https://github.com/desktop/desktop/blob/development/docs/integrations/bitbucket.md

However, after cloning my bitbucket repo into GitHub desktop I *DO NOT* immediately receive an "authentication error" as the document suggests I should. I am able to access the repo as expected, and I can make changes, commit changes, etc. without having to enter a personal access token which I created as per the above document.

The problem comes when I try to push a change. At this point, I get an "authentication error" but when I enter my bitbucket user name and the personal access token password which was just created, it just keeps returning the same "authentication error" window.

The most bizarre part is that I have previously pushed to this repo before without a PAT. All of a sudden today I tried to push and I got the authentication error. So I removed the repo, logged out, restarted computer, and followed the steps laid out in the above doc. But the problem still persists.

Really banging my head against the wall here about this, so any help is appreciated.

### Release version

3.0.2

### Operating system

MacOS 11.6.5

**Comment by tsvetilian-ty** [comment]
👋 @darcycordell could you upload the log files "Help > Show logs...". The names of the files are annotated with the date!

**Comment by sergiou87** [comment]
@darcycordell could you take a look at https://github.com/desktop/desktop/issues/14052 and see if any of that info helps? 🙏

**Comment by darcycordell** [comment]
@tsvetilian-ty Here's log files from Friday and today.
[2022-06-17.desktop.production.log](https://github.com/desktop/desktop/files/8941874/2022-06-17.desktop.production.log)
[2022-06-20.desktop.production.log](https://github.com/desktop/desktop/files/8941875/2022-06-20.desktop.production.log)

**Comment by darcycordell** [comment]
> @darcycordell could you take a look at #14052 and see if any of that info helps? 🙏

I tried this and it worked! Thanks!

**Comment by sergiou87** [comment]
Yay!!! Could you tell me which specific steps helped you to address this issue? I'd love to update the https://github.com/desktop/desktop/blob/development/docs/integrations/bitbucket.md document with that info to help other users.

**Comment by darcycordell** [comment]
Here are the modified step I took from [here](https://github.com/desktop/desktop/issues/14052#issuecomment-1057911647).

> - Completely close Github Desktop and developing GUI. Everything related.
> - Delete all bitbucket related credentials from Windows/Mac "keychain". (I am on Mac so I open "Keychain Access" and deleted everything from bitbucket)
> - Delete entire shared bitbucket projects folders from my local (not mine projects, only shared ones). Or save on to different paths away, if you need to recuperate some made code changes. But be sure the folders are not were they used to be anymore.
> -Create an APP Password on the bitbucket/Atlassian website under "Personal Settings" and then "App Passwords". You must create with ALL permisions set. All the checks you can check, do it. Save the token received on App password creation.
> - Open Github desktop and travel to shared projects. It says they're removed and asks for removing from Github Desktop. Accept removing all of them.
> - Now clone the shared project.
> - Now try to fetch, push, or pull anything from your bitbucket shared proejct. It's going to ask for credentials. Write your Atlassian USER, the one appearing on bitbucket personal page. NOT the e-mail, but the user AS-IS. 
> - It should sync as expected and you can now push, pull, fetch anything.

I'm not entirely sure which of the steps was what I was missing before. I feel like the two things that the previous user suggested which I hadn't done was to delete the keychain and to select ALL permissions when creating the app password.
