### ISSUE TITLE
More account support

### ISSUE THREAD

**Issue by deMartiniFrancesco** [desktop/desktop#14839]
### The feature request

Add the support for multiple accounts

### Proposed solution

possibility of logging in with multiple accounts and having the option to choose with which one wants to work

**Comment by sergiou87** [comment]
Thanks for the feedback @deMartiniFrancesco. We are tracking support for multiple accounts in https://github.com/desktop/desktop/issues/3707. Feel free to subscribe to that issue if you want to get updates in case we make any progress.
