### ISSUE TITLE
Size to fit branch name container

### ISSUE THREAD

**Issue by csmintic** [desktop/desktop#14830]
### The feature request

The container that presents the branch name should have variable width to accommodate longer branch names.
It's just frustrating to not be able to read the entire branch name at a glance when there is so much available free space.
<img width="1726" alt="long_branch_name" src="https://user-images.githubusercontent.com/102375315/174401400-2c004291-f545-4ff0-97e6-a7ead435fbcf.png">

### Proposed solution

Proposal 1: Make the branch container auto-resize to accomodate the branch name.
Proposal 2: Make the top containers (branch and remote) have manual draggable width control.

**Comment by tsvetilian-ty** [comment]
Thanks @csmintic. You can follow the discussion in #4569. Feel free to leave your feedback.
