### ISSUE TITLE
"refusing to merge unrelated histories" with initial repository

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#1484]
### Description

There's a corner case where your local repository and remote repository can have distinct histories (because they were initialized with their own commit). We should surface this error, but what to do about it properly is an Excellent Question™.

### Version

**GitHub Desktop version:** 0.5.1

**OS version:** Windows 10

### Steps to Reproduce

This is a bit convoluted, apologies.

- Create a new repository on GitHub, named whatever (I'm calling mine `initialized-repository` for future reference) and include a README so it gets an initial commit.
- Open Desktop and create a new repository with the same name (because consistent). Ensure it at least has a README too. Make a note of where you saved it.

Here's my setup:

<img width="458" alt="screen shot 2017-05-16 at 12 05 20 pm" src="https://cloud.githubusercontent.com/assets/359239/26086798/535ac23c-3a30-11e7-883c-66ccb56b75fe.png">

- Launch `Repository` -> `Open command prompt` to open a shell
- Run these command to wireup the repositories and the current branch:

```
git remote add origin https://github.com/{account}/{repo}.git -f
git branch -u origin/master
```

`{account}` is the owner and `{repo}` is whatever named you defined earlier - so for me this is:

```
git remote add origin https://github.com/shiftkey/initialized-repository.git -f
git branch -u origin/master
```

- Remove the repository, then drag-and-drop the folder to add it back in. This should light it up, and you should see this as your Pull button:

<img width="266"  src="https://cloud.githubusercontent.com/assets/359239/26087117/59c2e58a-3a32-11e7-8ebc-d4a7a1151c76.png">

- Press `Pull`

**Expected behaviour:** some guidance about resolving these two histories, favouring the remote repository

**Actual behaviour:** a basic error

<img width="441" alt="screen shot 2017-05-16 at 12 23 29 pm" src="https://cloud.githubusercontent.com/assets/359239/26087145/7f53f104-3a32-11e7-97b3-f354b67092d1.png">

And the console logs are kind of meh:

```
- The command `git -c credential.helper= pull --progress origin` exited with an unexpected code: 128. The caller should either handle this error, or expect that exit code.
(anonymous) @ core.ts:145
- core.ts:151 fatal: refusing to merge unrelated histories

(anonymous) @ core.ts:151
```

**Reproduces how often:** 100%

#### Additional Information

Some better messaging around this would be a good start while we figure out the solution path. I've opened https://github.com/desktop/dugite/issues/93 to track getting this into the Git bindings first.

**Comment by shiftkey** [comment]
There's a [more descriptive error](https://github.com/desktop/desktop/blob/master/app/src/lib/git/core.ts#L203) in here from an update to `duguite`, but we need some flow around this to get the user to a happy place.

Putting this aside for the moment.

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by fy-kenny** [comment]
I create a local repository and create another remote repository. then occur the warning
maybe, you cloud try:
1. git rebase
2. git pull
3. git push

**Comment by billygriffin** [comment]
@shiftkey This feels sufficiently edge-casey to potentially allow it to surface more frequently before we consider solving for it. Would you be ok with removing `future proposal` here?

**Comment by shiftkey** [comment]
@billygriffin yeah, I'm happy to let this sit. But keep in mind we've also seen #1308 #2247 and #5012 mention this particular Git error...

**Comment by cookieuon** [comment]
Hey @shiftkey I've just reproduced this fault in 1.6.5, but no error is presented as in your initial post. I try to push, and I am informed the remote is newer than local, I should fetch the remote. Click Fetch, thinks for a second then goes away. Try to push again, rinse and repeat.
I had to go to the CLI to be presented with the error: "fatal: refusing to merge unrelated histories"

Hope this isn't in the wrong place.

**Comment by steveward** [comment]
@cookieuon you can use the command `git pull origin master --allow-unrelated-histories` from the command line to force Git to merge the two separate repositories together. Let me know if you run into any issues with that.

**Comment by billygriffin** [comment]
Going to remove future proposal for now, with the caveat that this may resurface from users and we'll be able to reference this issue if/when it does. Thanks for clearly laying it out @shiftkey!

**Comment by Mr-HaleYa** [comment]
Created a new repo, cloned it onto desktop, created a Readme.md using the website then tried uploading files and the error happens 
![image](https://user-images.githubusercontent.com/42821995/91186167-ee4c5f00-e6ab-11ea-94e6-35865e56e687.png)

**Comment by tierninho** [comment]
@Mr-HaleYa Please open a new issue here https://github.com/desktop/desktop/issues/new?template=bug_report.md so we can address your situation independently. Thank you.
