### ISSUE TITLE
Full match repository search should be top 1 search result

### ISSUE THREAD

**Issue by doekman** [desktop/desktop#14845]
### The problem

I want to select a repository in GitHub Desktop, so I click the search field. I type the full name of the repository I want to navigate to ("ok-bash" in my case). I expect if there is a full match, it should the first result, and it should be selected. Because, then I can just press enter, and make the repository active.

### Release version

Version 3.0.2 (x64)

### Operating system

macOS 12.4

### Steps to reproduce the behavior

1. Click current repository, so repository pane will show
2. In search field, type the name of the repository to search for (full name)
3. Observe the search for repository is not the first result, and is also not selected
    - When repeating this (after the searched for repository has been selected) the search for repository also appears under "Recent" in the search result. It is still not selected
4. To select the repository, a combination of TAB + arrow-down has to be pressed to select the repository.

See also screenshot.

### Screenshots

<img width="402" alt="Schermafbeelding 2022-06-21 om 09 21 34" src="https://user-images.githubusercontent.com/1086388/174740994-a7c78f14-97f8-43b3-be6e-d71f05668d3b.png">

**Comment by steveward** [comment]
This is being tracked in https://github.com/desktop/desktop/issues/4860, so I'm going to close this out as a duplicate. You can follow along there for updates.
