### ISSUE TITLE
Add a button to invoke `git mergetool` when doing a merge or rebase

### ISSUE THREAD

**Issue by the21st** [desktop/desktop#14854]
### The feature request

I have a special 3-way merge tool configured in my gitconfig and every time I do a merge or rebase using Github desktop and have a conflict, I have to instead open up my terminal, type `git mergetool`, resolve conflicts this way, and then come back to Github Desktop. This is especially painful if there are lots of conflicts in multiple commits in a complicated rebase.

### Proposed solution

Replace the "You can also open the command line to resolve" prompt by "You can also use your mergetool to resolve" that is shown instead if a mergetool is configured in git config. Upon clicking it, the command `git mergetool` is executed.

**Comment by sergiou87** [comment]
Hello @the21st ! 👋 

Thank you for your suggestion, but this seems to be related to #9609 so I'm gonna close it in favor of that. I'll post your suggestion there, feel free to subscribe if you want to get notified when we make progress on that.
