### ISSUE TITLE
Something is missing 

### ISSUE THREAD

**Issue by ahrar2002** [desktop/desktop#14856]
Hi, I've downloaded gradle many times but Android studio is still requiring gradle every time. Can anyone help me with this issue ?
Please...............
![image](https://user-images.githubusercontent.com/32236629/175068386-56a43e43-bc07-4956-aabc-1dc291d53a60.png)

**Comment by sergiou87** [comment]
Hello! 👋 
I'm sorry but this is the repository of GitHub Desktop, and I'm afraid we can't help you with issues with Android Studio or Gradle 😞
