### ISSUE TITLE
validate commit summary to handle whitespace being entered

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#1485]
### Description

You can try and create a commit with an empty summary field. It fails.

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** 0.5.1

**OS version:** Windows 10

### Steps to Reproduce

1. Create a new local repository, pre-populated with some files.
1. Launch `Repository` -> `Open in Explorer` to get to the filesystem
1. Modify a file so some changes appear in the app
1. Enter a space for the commit summary

**Expected behaviour:** A warning that the commit summary is not valid

**Actual behaviour:** No error

**Reproduces how often:** 100%

#### Additional Information

Currently this fails with a somewhat meaningful error, so this feels more like a polish task

<img width="599" src="https://cloud.githubusercontent.com/assets/359239/26087369/b84aac68-3a33-11e7-9102-c31872b0baf6.png">

There's also some design work here that we'd need to consider given how the commit form is limited.

**Comment by shiftkey** [comment]
Moving this to `help wanted` as this is something good for an external contributor, but much like #5240 there will probably be some discussion about what makes sense here.

**Comment by Daniel-McCarthy** [comment]
I believe that this issue can be closed now that #5677 has been merged.
I likely should have used "Fixes #1485" for this case.

**Comment by outofambit** [comment]
@Daniel-McCarthy good catch! thanks!
