### ISSUE TITLE
Two separate repositories have same name

### ISSUE THREAD

**Issue by JordanR94** [desktop/desktop#14851]
### The problem

I have created two separate repositories which with different names however they are appearing as the same name on the desktop version. Elsewhere they are different (online and my machine). 

### Release version

Version 3.0.2 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Go to current repository on github desktop
2. View repositories
3. Notice that two are the same (symf6_vinyl) - one should be symf6_docs
4. Hover over each of these repositories and you will see the directory location with the correct repo name

### Log files

No log files applicable

### Screenshots

![image](https://user-images.githubusercontent.com/44776172/174990886-a0515361-a723-446d-a8ff-771bf794c3fb.png)
![image](https://user-images.githubusercontent.com/44776172/174991035-aae02ae8-51db-4433-8609-a524d63ed915.png)
![image](https://user-images.githubusercontent.com/44776172/174991171-c4f19e28-6749-4685-b1f4-9fa5f61645d8.png)

### Additional context

No files seem to be conflicted, I believe this is just a bug on the GitHub Desktop repo names.

**Comment by tsvetilian-ty** [comment]
@JordanR94 👋 the name of the repository is **NOT** based on your local folder structure. You have cloned two local instances of the same repository (JordanR94/symf6_vinyl), which is why you have the same name. 

You can right click one of the repos and select "Create alias", which will prompt you to create a name for the repo.

**Comment by JordanR94** [comment]
Thank you, will keep this in mind for future repos!
