### ISSUE TITLE
Installing GH Desktop result in error about ffmpeg.dll

### ISSUE THREAD

**Issue by theking2** [desktop/desktop#14857]
### The problem

Installing GH new on a vm.
During installating an error is displayed
The code execution cannot proceed because ffmpeg.dll was not found. Reinstalling the program may fix this problem

### Release version

3.0.2

### Operating system

Windows 10

### Log files

[2022-06-22.desktop.production.log](https://github.com/desktop/desktop/files/8959908/2022-06-22.desktop.production.log)

**Comment by sergiou87** [comment]
Hello @theking2 👋 

Looking at your logs, seems like your GitHub Desktop installation is not in the "standard" location (`C:\Users\<your user>\AppData\Local\GitHubDesktop`). How did you install it exactly? 🤔 

Aside from that, `ffmpeg.dll` should be in the `app-3.0.2` subfolder in that location:
![2022-06-23 at 09 27](https://user-images.githubusercontent.com/1083228/175241007-85843921-8e25-4ca5-b174-d6b428127707.png)

In your case, that'd be in `C:\ProgramData\Jo\GitHubDesktop\app-3.0.2`

**Comment by PISSOFF3** [comment]
Helloooo

**Comment by theking2** [comment]
Pissoff? Really? When will you grow up?

----------------------------------------

30 jun. 2022 21:51:58 PISSOFF3 ***@***.***>:

**Comment by vcsjones** [comment]
Another report of this via twitter from @ericlaw1979:

https://twitter.com/ericlaw/status/1555303074054524932

**Comment by theking2** [comment]
I get the error during setup (installation has failed) On my surface all folders are standard. The ffmpeg.dll is not in the app-3.5.5 location.

**Comment by sergiou87** [comment]
@theking2  AFAICT that Squirrel log only mentions other apps (related to Teams and O365) but I don't see anything about GitHub Desktop 🤔 

Does your `C:\Users\<your user>\AppData\Local\GitHubDesktop` folder have the right permissions (read-write for your user)?

**Comment by ericlaw1979** [comment]
FWIW, when I got this message, it might have possibly happened when I had two installations of GHDesktop installing in parallel (because Edge's UI doesn't make it clear when you've successfully "Open"ed the download, so I kept clicking on the link).

**Comment by kingma-sbw** [comment]
> Hello @theking2 👋
> 
> Looking at your logs, seems like your GitHub Desktop installation is not in the "standard" location (`C:\Users\<your user>\AppData\Local\GitHubDesktop`). How did you install it exactly? 🤔
> 
> Aside from that, `ffmpeg.dll` should be in the `app-3.0.2` subfolder in that location: ![2022-06-23 at 09 27](https://user-images.githubusercontent.com/1083228/175241007-85843921-8e25-4ca5-b174-d6b428127707.png)
> 
> In your case, that'd be in `C:\ProgramData\Jo\GitHubDesktop\app-3.0.2`
I aktually did not change the installation folder.

**Comment by kingma-sbw** [comment]
I could not reproduce the problem. It might be caused by what @ericlaw1979 reported. Specifically in a VM response is slow and a second click on install might have triggered multiple install attempts.

**Comment by 4cad** [comment]
Figured I would put this here for posterity. I had an identical situation to @ericlaw1979 happen today on the latest installer, the ffmpeg.dll error appeared after I mistakenly started two instances of the installer at the same time after downloading the file through edge.

Installation worked properly afterwards when I had only one process running, without having to re-download the installer.

**Comment by logancyang** [comment]
> FWIW, when I got this message, it might have possibly happened when I had two installations of GHDesktop installing in parallel (because Edge's UI doesn't make it clear when you've successfully "Open"ed the download, so I kept clicking on the link).

I just encountered this and it's exactly because of 2 parallel installations with Edge. Just leaving a data point here.

**Comment by temabu** [comment]
As per @logancyang, I had the same with two parallel installs through a double click in Edge.  Uninstall the one you have through control panel and re-run the installation.  All settings retained and install worked perfectly.
