### ISSUE TITLE
Referencing Deleted remote branch, unsuccessful pulling or pushing

### ISSUE THREAD

**Issue by adebayo-maborukoje** [desktop/desktop#14865]
### The problem

WHenever I try to pull or push to my remote repository.

I get the follow error:
Fatal: bad object ref/heads/(a random branch)

### Release version

Version 3.0.2 (x64)

### Operating system

MacOS

### Screenshots

<img width="618" alt="Screenshot 2022-06-23 at 04 20 12" src="https://user-images.githubusercontent.com/9351454/175480689-2a46d24c-4183-4f81-a75e-3ea96c98cca3.png">

**Comment by tsvetilian-ty** [comment]
Hey @adebayo-maborukoje are you able to pull or push from cli?

**Comment by adebayo-maborukoje** [comment]
@tsvetilian-ty  Yes. My cli works perfectly fine

**Comment by tsvetilian-ty** [comment]
@adebayo-maborukoje could you upload the log file "Help > Show logs...". The log files are generated daily, and the date is encoded in the file's name.

**Comment by adebayo-maborukoje** [comment]
[2022-06-24.desktop.production.log](https://github.com/desktop/desktop/files/8975085/2022-06-24.desktop.production.log)

**Comment by adebayo-maborukoje** [comment]
> @adebayo-maborukoje could you upload the log file "Help > Show logs...". The log files are generated daily, and the date is encoded in the file's name.


Resolving deltas:   0% (0/2784)
Resolving deltas:   1% (28/2784)
Resolving deltas:   2% (56/2784)
Resolving deltas:   3% (84/2784)
Resolving deltas:   4% (112/2784)
Resolving deltas:   5% (140/2784)
Resolving deltas:   6% (168/2784)
Resolving deltas:   7% (195/2784)
Resolving deltas:   8% (223/2784)
Resolving deltas:   9% (251/2784)
Resolving deltas:  10% (279/2784)
Resolving deltas:  11% (307/2784)
Resolving deltas:  12% (335/2784)
Resolving deltas:  13% (362/2784)
Resolving deltas:  14% (390/2784)
Resolving deltas:  15% (418/2784)
Resolving deltas:  16% (446/2784)
Resolving deltas:  17% (474/2784)
Resolving deltas:  18% (502/2784)
Resolving deltas:  19% (529/2784)
Resolving deltas:  20% (557/2784)
Resolving deltas:  21% (585/2784)
Resolving deltas:  22% (613/2784)
Resolving deltas:  23% (641/2784)
Resolving deltas:  24% (669/2784)
Resolving deltas:  25% (696/2784)
Resolving deltas:  26% (724/2784)
Resolving deltas:  27% (752/2784)
Resolving deltas:  28% (780/2784)
Resolving deltas:  29% (808/2784)
Resolving deltas:  30% (836/2784)
Resolving deltas:  31% (864/2784)
Resolving deltas:  32% (891/2784)
Resolving deltas:  33% (919/2784)
Resolving deltas:  34% (947/2784)
Resolving deltas:  35% (975/2784)
Resolving deltas:  36% (1003/2784)
Resolving deltas:  37% (1031/2784)
Resolving deltas:  38% (1058/2784)
Resolving deltas:  39% (1086/2784)
Resolving deltas:  40% (1114/2784)
Resolving deltas:  41% (1142/2784)
Resolving deltas:  42% (1170/2784)
Resolving deltas:  43% (1198/2784)
Resolving deltas:  44% (1225/2784)
Resolving deltas:  45% (1253/2784)
Resolving deltas:  46% (1281/2784)
Resolving deltas:  47% (1309/2784)
Resolving deltas:  48% (1337/2784)
Resolving deltas:  49% (1365/2784)
Resolving deltas:  50% (1392/2784)
Resolving deltas:  51% (1420/2784)
Resolving deltas:  52% (1448/2784)
Resolving deltas:  53% (1476/2784)
Resolving deltas:  54% (1504/2784)
Resolving deltas:  55% (1532/2784)
Resolving deltas:  56% (1560/2784)
Resolving deltas:  57% (1587/2784)
Resolving deltas:  58% (1615/2784)
Resolving deltas:  59% (1643/2784)
Resolving deltas:  60% (1671/2784)
Resolving deltas:  61% (1699/2784)
Resolving deltas:  62% (1727/2784)
Resolving deltas:  63% (1754/2784)
Resolving deltas:  64% (1782/2784)
Resolving deltas:  65% (1810/2784)
Resolving deltas:  66% (1838/2784)
Resolving deltas:  67% (1866/2784)
Resolving deltas:  68% (1894/2784)
Resolving deltas:  69% (1921/2784)
Resolving deltas:  70% (1949/2784)
Resolving deltas:  71% (1977/2784)
Resolving deltas:  72% (2005/2784)
Resolving deltas:  73% (2033/2784)
Resolving deltas:  74% (2061/2784)
Resolving deltas:  75% (2088/2784)
Resolving deltas:  76% (2116/2784)
Resolving deltas:  77% (2144/2784)
Resolving deltas:  78% (2172/2784)
Resolving deltas:  79% (2200/2784)
Resolving deltas:  80% (2228/2784)
Resolving deltas:  81% (2256/2784)
Resolving deltas:  82% (2283/2784)
Resolving deltas:  83% (2311/2784)
Resolving deltas:  84% (2339/2784)
Resolving deltas:  85% (2367/2784)
Resolving deltas:  86% (2395/2784)
Resolving deltas:  87% (2423/2784)
Resolving deltas:  88% (2450/2784)
Resolving deltas:  89% (2478/2784)
Resolving deltas:  90% (2506/2784)
Resolving deltas:  91% (2534/2784)
Resolving deltas:  92% (2562/2784)
Resolving deltas:  93% (2590/2784)
Resolving deltas:  94% (2617/2784)
Resolving deltas:  95% (2645/2784)
Resolving deltas:  96% (2673/2784)
Resolving deltas:  97% (2701/2784)
Resolving deltas:  98% (2729/2784)
Resolving deltas:  99% (2757/2784)
Resolving deltas: 100% (2784/2784)
Resolving deltas: 100% (2784/2784), completed with 728 local objects.
fatal: bad object refs/heads/dev_update 2
error: github.com:Nivoda/website.git did not send all necessary objects


2022-06-24T09:38:32.865Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 2.3s of which 3330.7s paused, total 3333.0s

**Comment by tsvetilian-ty** [comment]
@adebayo-maborukoje the issue looks similar to https://github.com/desktop/desktop/issues/14473 can you check if the resolution works for you?

**Comment by adebayo-maborukoje** [comment]
@tsvetilian-ty  When I re-`add existing repository` the problem still persists but when I clone the repository directly using github desktop it works well.

**Comment by adebayo-maborukoje** [comment]
@tsvetilian-ty
I was able to identify the real reason why my local repository was throwing the refs error.
A branch was wrongly named `dev 2` with spaces in between. my Cli ignores this broken name while pulling and pushing.
a check on all local branches shows that it is  ignored.

the solution is  `git branch -D 'dev 2'`  and every other broken refs
