### ISSUE TITLE
Image diff: calculation of percentage value not useful

### ISSUE THREAD

**Issue by craftedsystems** [desktop/desktop#14863]
### The problem

The image diff displays a percentage value for byte difference that makes no sense – at least for me. :-)

**Example**

<img width="527" alt="Screenshot 2022-06-23 at 18 24 13" src="https://user-images.githubusercontent.com/26137287/175350133-eb1769e9-7572-4a23-935a-2ae0a29e41d8.png">

The current calculation returns **Diff: -14.69 KiB (30%)**
The value I would like to see is **Diff: -14.69 KiB (70%)**
and can be calculated like that: `Math.abs(Math.round(100 / previous * (previous - current)))`

Related source code:
https://github.com/desktop/desktop/blob/18238077aa1e4851e710cfa66587cd4fd597bacd/app/src/ui/diff/image-diffs/two-up.tsx#L9

### Release version

Version 3.0.2 (x64)

### Operating system

macOS 12.4

**Comment by craftedsystems** [comment]
(I can create a PR if you want me to)

**Comment by sergiou87** [comment]
Thank you for your report @craftedsystems 

While I agree it's not the most intuitive thing, GitHub (web) follows the same convention of displaying the % of the current file size compared to the original. You can check `https://github.com/<org>/<repo>/commit/<commitSHA>` for that specific commit and see the web should show the same as GitHub Desktop.

I'm gonna close this assuming that's correct, if it's not please let me know and I'll be happy to reopen this 😄
