### ISSUE TITLE
Inconsistent tab sizes in code diff

### ISSUE THREAD

**Issue by TianyiChen** [desktop/desktop#14869]
### The problem

The top level tabs have a size of 3, and tabs in other levels have a size of 4. It makes me feel the file might be bad-formatted while it isn't.

### Release version

3.0.2 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Any source code which uses tab and has multiple level of indention should suffice, my snippet:
```
void local_function() {
	if (a == 1) {
		return;
	}
}
```

### Screenshots

GitHub Desktop:
`i` in `if` is aligned with `d` in `void`, the tab has size 3
`r` in `return` is aligned with `a`, the tab has size 4
![image](https://user-images.githubusercontent.com/10559772/175759717-ece59877-2302-4417-8b13-6dec31afc955.png)
VS code:
`i` in `if` is aligned with space after `void`, the tab has size 4
`r` in `return` is aligned with `a`, the tab has size 4
![image](https://user-images.githubusercontent.com/10559772/175759736-29a43ed5-65b6-434d-9979-dfe7ed2be2dc.png)

**Comment by tsvetilian-ty** [comment]
Hey @TianyiChen thanks for your report. It looks like a duplicate of https://github.com/desktop/desktop/issues/8616

**Comment by TianyiChen** [comment]
Thanks @tsvetilian-ty Yes they are duplicate, hence I am closing this one.
