### ISSUE TITLE
[usability]the long menu item name is not displayed completely

### ISSUE THREAD

**Issue by iamqiz** [desktop/desktop#14868]
### The problem

![image](https://user-images.githubusercontent.com/48077521/175699039-bf147aa3-a925-414e-b09c-f373460f1d49.png)

### Release version

3.0.2

### Operating system

win10

**Comment by Kokomo1982** [comment]
> ### The problem
> ![image](https://user-images.githubusercontent.com/48077521/175699039-bf147aa3-a925-414e-b09c-f373460f1d49.png)
> 
> ### Release version
> 3.0.2
> 
> ### Operating system
> win10
> 
> ### Steps to reproduce the behavior
> _No response_
> 
> ### Log files
> _No response_
> 
> ### Screenshots
> _No response_
> 
> ### Additional context
> _No response_
124()
