### ISSUE TITLE
GitHub Desktop Lagging

### ISSUE THREAD

**Issue by UG0100120** [desktop/desktop#14864]
### The problem

Every thing in my pc work perfect, but when I come to GitHub desktop it's lagging.

### Release version

Version 3.0.2 (x64)

### Operating system

Window 11

### Log files

No log files

### Screenshots

![image](https://user-images.githubusercontent.com/84369314/175471155-5f274216-7c54-491b-b379-9c4a1c7113f2.png)

**Comment by sergiou87** [comment]
Thanks for your report @UG0100120 !

Does rebooting your PC fix the issue? If it doesn't, what are the specs of your PC?
