### ISSUE TITLE
Can my local pull exist over an SSH connection?

### ISSUE THREAD

**Issue by quisido** [desktop/desktop#14867]
### The feature request

I want to do my dev work on my personal Windows machine (using SSH to connect to a more powerful, development machine).

I want the git repository to exist on the more powerful, development machine, but I want to use GitHub Desktop on my personal machine to manage that git repository.

Example workflow:
```
Ubuntu machine:
  git clone
  make
  run

Windows machine:
  github desktop - add the cloned directory from the Ubuntu machine via SSH
  vscode - connect to the Ubuntu machine for editing
  vscode - make changes, save
  github desktop - see the changes I made, branch, commit, push
```

### Proposed solution

"Local repositories" should be either on the current machine or support SSH to a different machine.

**Comment by sergiou87** [comment]
I'm sorry but I don't think that's possible as of today, unless you mount that repository in your local machine via sshfs or similar. That way, GitHub Desktop will have access to the remote files locally and might be able to use git on them.
