### ISSUE TITLE
Open in shell option when no changes

### ISSUE THREAD

**Issue by moritztim** [desktop/desktop#14866]
### The feature request

In the [changes ui when there are no changes](https://github.com/desktop/desktop/blob/development/app/src/ui/changes/no-changes.tsx), display a button to open the repository in the selected shell, just like viewing on github, in the file explorer or in an external editor.

### Proposed solution

There's a lot of space there, why not use it to display the one remaining Repository menu item?

### Additional context

![grafik](https://user-images.githubusercontent.com/90388353/175516485-56b6d237-37e0-4085-8cdf-5dfa4dd9c2e1.png)
this is the ui I am talking about.

**Comment by tsvetilian-ty** [comment]
@moritz-t-w thanks for your feedback! There were two attempts (https://github.com/desktop/desktop/pull/6677 and https://github.com/desktop/desktop/pull/12162) to add this suggested action, but based on the discussion in https://github.com/desktop/desktop/issues/6674 they were closed.

**Comment by moritztim** [comment]
Sorry, I forgot to check
