### ISSUE TITLE
Unable to ciommit changes

### ISSUE THREAD

**Issue by rbknox16** [desktop/desktop#14879]
### The problem

Repository has been functional until today. When i try to commit changes i get the following error

error: open(".vs/SimTCP/v16/Browse.VC.opendb"): Permission denied
fatal: Unable to process path .vs/SimTCP/v16/Browse.VC.opendb

### Release version

v3.03

### Operating system

win 10 enterprise

### Screenshots

![image](https://user-images.githubusercontent.com/98232569/176149471-79dbe6fe-fa1e-4231-8225-c774a5b16104.png)

**Comment by steveward** [comment]
@rbknox16 thanks for the issue. It looks like there's a database lock file preventing your commit from completing (meaning the database is in use). You will want to ignore database files (see the recommended [.gitignore](https://github.com/github/gitignore/blob/main/VisualStudio.gitignore) that you can add). I'm going to close this out, but let me know if you have any further questions.
