### ISSUE TITLE
View and download the files of a specific commit.

### ISSUE THREAD

**Issue by AAndyProgram** [desktop/desktop#14876]
### The feature request

For example. I have commits of the following dates: 2020-01-20, 2020-06-11, 2021-11-10, 2022-06-06, etc.
I want to browse the repository for 2021-11-10. I want to see the whole structure of the files at this point. Currently, I can only see the changed files and changes. It would also be great if I could get the archive of the files (or extract the files to a specific folder). I mean the same as the GitHub commit history: "Browse the repository at this point of the history". And then clone the code.

### Proposed solution

This is really needed, especially for a local repository that has not been uploaded to GitHub.

**Comment by tsvetilian-ty** [comment]
Hi @AAndyProgram thanks for the request. You can right-click on the specific entry in the history (let's say `2021-11-10` from your example) list and select "Create branch from commit". I think that will simulate the behavior you want in safe way by creating a separate branch based on the one you selected.

**Comment by steveward** [comment]
@AAndyProgram the solution @tsvetilian-ty shared is the best method for viewing your repository in a specific state at a previous point in its history. I'm going to close this out, but let us know if you have any further questions.

**Comment by AAndyProgram** [comment]
Hello @tsvetilian-ty, @steveward. Thank you for your reply.
Yes, of course I know about this method and use it now. But it's not the same and not comfortable.
- I can't view a single file from this repository point.
- I was forced to change the whole files structure every time.
- If I currently have uncommitted changes, I am forced to make a decision: bring the changes to a new branch; left here; commit all of them. Just one smallest bug in GitHubDesktop and all my changes will be lost!

However, thank you for your time.
