### ISSUE TITLE
ensure local path is valid when creating repository

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#1487]
Supersedes #1067

### Description

We should provide a helpful message when the user has entered a known invalid path, before trying to create it.

### Version

**GitHub Desktop version:** 0.5.1

**OS version:** `Microsoft Windows [Version 10.0.15063]`

### Steps to Reproduce

1. Launch `File` -> `New Repository`
1. Change the local path to `>`

**Expected behaviour:** some sort of validation that the path is not valid

**Actual behaviour:** no message, can continue with creating the repository

**Reproduces how often:** 100%

#### Additional Information

The error you get differs per-platform. Here's what it is on Windows:

<img width="472" src="https://cloud.githubusercontent.com/assets/359239/26089020/f46d8206-3a3d-11e7-90c7-581c2a2c4b0c.png">

And on macOS:

![ecc58010-109b-11e7-9321-dd9945c18ea0](https://cloud.githubusercontent.com/assets/359239/26089055/2343a97a-3a3e-11e7-8a83-93171e3b95fe.png)

The other downside of this current behaviour is that it occurs _after_ the form has been dismissed - so there's no way for the user to recover - they need to go through the process all over again.

**Comment by iAmWillShepherd** [comment]
What constitutes a valid path here? 

On macOS, `/github` is technically a path. Is this issue more to do do about checking if a user has permissions to create files and directories in certain places?
