### ISSUE TITLE
WARN and extra step if user tries to do a REVERT of a merge commit that is remote--->local of same branch

### ISSUE THREAD

**Issue by jxbell** [desktop/desktop#14888]
### The feature request

Using the github desktop app to create a revert commit is super easy.

We used it to undo accidental commits to master -- normally commits should only be to working branches and then PRs with squash merge to master.

My team found out THE HARD WAY that if the commit you assume you want to revert because it was accidental was not a normal commit but a "merge commit from remote ---> local of the same branch", from our experience that should NOT be reverted because it's not reeeeeeeeally changes in the same sense. 

If you do a revert of that type of commit , it is CATASTROPHE for the branch, we learned!!! It does not do what you think!!!!

PLUS, you can't even REVERT THE REVERT COMMIT -- well, we tried and it made things even more unintuitive, because browsing the commits makes it look like it does something but in truth it doesn't change the files. Very confusing to the git history!

PROPOSAL:

(1) PLEASE WARN AND EXTRA STEP TO OK IT if user tries to do a REVERT of a merge commit that is remote--->local of the SAME branch. Proposed warning: "WARNING: This is not a normal commit. This is an automatically created merge commit that git creates to maintain the history across repos. For example, it might represent merging the remote version of a branch into the local branch of the SAME branch to keep the history in sync. If you make a revert commit of this merge commit, the behavior might not be as expected. Are you sure you want to create the revert commit?

(2) Reverting one of THOSE ^^^^ revert commits if they are created should ALSO get a warning before the user proceeds. It does not do what the user thinks! It does NOT undo the damage of the previous "revert the auto-created merge to same branch" commit. It's very confusing to untangle.

### Proposed solution

PROPOSAL:

(1) PLEASE WARN AND EXTRA STEP TO OK IT if user tries to do a REVERT of a merge commit that is remote--->local of same branch. Proposed warning: "WARNING: This is not a normal commit. This is an automatically created merge commit that git creates to maintain the history across repos. For example, it might represent merging the remote version of a branch into the local branch of the SAME branch to keep the history in sync. If you make a revert commit of this merge commit, the behavior might not be as expected. Are you sure you want to create the revert commit?

(2) Reverting one of THOSE ^^^^ revert commits if they are created should ALSO get a warning before the user proceeds. It does not do what the user thinks! It does NOT undo the damage of the previous "revert the auto-created merge to same branch" commit. It's very confusing to untangle.

**Comment by steveward** [comment]
Thanks for the issue @jxbell, this looks similar to the report in https://github.com/desktop/desktop/issues/5541. This is the expected behavior, but there may be something we can do to handle these cases better. I'll reference this issue there.
