### ISSUE TITLE
Login Problem in Github Desktop

### ISSUE THREAD

**Issue by prathamrajbhar** [desktop/desktop#14892]
### The problem

I am try to login in Github Desktop but he is not working. So , Can you Solve This Error .

Thanks You

### Release version

3.0.3

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Go to File
2. Click on Option
3. Click on Github Login
4. Redirect form browser
5. ERROR

### Log files

[2022-06-30.desktop.production.log](https://github.com/desktop/desktop/files/9016639/2022-06-30.desktop.production.log)

### Screenshots

![Screenshot (11)](https://user-images.githubusercontent.com/108448284/176599641-ec49daad-2668-48d1-a7a8-0233d520c057.png)

**Comment by sergiou87** [comment]
Hi @PrathJarvis ! 👋 

Looking at the logs I see GitHub Desktop is having trouble to find the shortcuts that should be installed in your desktop and Start menu. This is not bad per se (except that [notifications](https://github.blog/2022-04-26-github-desktop-3-0-brings-better-integration-for-your-pull-requests/) won't work), but makes me wonder… how did you install GitHub Desktop on your machine? Maybe you did something unconventional that is preventing the app from completing the sign in flow 🤔

**Comment by kissurda** [comment]
Same problem, i tried logged in to azure repository, but the application only showned this messag
![Screenshot 2022-07-01 at 10 50 03](https://user-images.githubusercontent.com/60176571/176860646-cd4f0a25-1bc6-45d8-a3d1-1fc297ef08b6.png)
e

Version 3.0.3
![Screenshot 2022-07-01 at 10 51 07](https://user-images.githubusercontent.com/60176571/176860756-2f35cfa2-e62f-4687-8e19-f61e9eef9713.png)
3

**Comment by steveward** [comment]
@kissurda you can follow [this guide](https://github.com/desktop/desktop/blob/development/docs/integrations/azure-devops.md) for instructions on authenticating to Azure DevOps.

**Comment by kissurda** [comment]
> @kissurda you can follow [this guide](https://github.com/desktop/desktop/blob/development/docs/integrations/azure-devops.md) for instructions on authenticating to Azure DevOps.

Thx. It's work for me!
