### ISSUE TITLE
Add a terminal to 

### ISSUE THREAD

**Issue by gustavo-herrera-cabrera** [desktop/desktop#14898]
### The feature request

Add a terminal to run commands from the repo's directory.

### Proposed solution

A card in the repo's main screen.

### Additional context

![image](https://user-images.githubusercontent.com/102456523/176957872-4716e253-d66a-4a1b-8016-96ef51eba585.png)

**Comment by steveward** [comment]
Thanks for the issue @gustavo-herrera-cabrera. We do not have any plans to implement a built-in terminal directly into GitHub Desktop, so I am going to close this issue out. GitHub Desktop provides a few options to launch a command line directly from within the application, and the quickest way is to use the 'Control+`' shortcut.

**Comment by gustavo-herrera-cabrera** [comment]
Could you at least add a button to open the terminal in the menu, please?
