### ISSUE TITLE
File update not showing

### ISSUE THREAD

**Issue by team-techchef** [desktop/desktop#14897]
### The problem

 I have added few things in my event.md file but they are not showing on the frontside

### Release version

3.0.3

### Operating system

Windows 8

**Comment by tsvetilian-ty** [comment]
Hey @team-techchef could you check if `event.md` is added to your `.gitignore` file?

**Comment by team-techchef** [comment]
![image](https://user-images.githubusercontent.com/70327952/176958787-06b67dc1-1888-46eb-ac59-9de8fc34ac92.png)
not it is not there

**Comment by tsvetilian-ty** [comment]
@team-techchef from GitHub Desktop, open your terminal (Crtl+\`) and type `git status` to see if `event.md` is visible
