### ISSUE TITLE
Wrong time / dates on current branch dropdown

### ISSUE THREAD

**Issue by tangentlab** [desktop/desktop#14895]
### The problem

Looking at my list of current branches in the drop down I started a 2 branches yesterday on June 29th and they both are listing as being created on June 24th at 3 in the afternoon.  The time listing on the side says it was created 6 days ago vs 1 day.

Working on a branch this morning looks like it's labelling it's time correctly.  

### Release version

3.0.3

### Operating system

Windows 10

### Steps to reproduce the behavior

1. create a branch today
2. see what date is lists?

### Screenshots

![image](https://user-images.githubusercontent.com/47337594/176724123-20f2c390-2c71-4a52-bb5e-403c81620354.png)

**Comment by steveward** [comment]
@tangentlab thanks for the issue. The date is based off of the last commit timestamp that the branch is created off of, not when you actually created the branch. Git does not track the specific creation time of a branch since branches are just pointers. I hope that helps!
