### ISSUE TITLE
Feature Request: Allow multiple stashes in each branch

### ISSUE THREAD

**Issue by clind-seismic** [desktop/desktop#14896]
### The feature request

Currently Github Desktop only allows for a single stash per branch. Having multiple stashes per branch would be very helpful.

### Proposed solution

Having multiple stashes per branch would be very helpful.

**Comment by steveward** [comment]
Thanks for the issue @clind-seismic, I'm going to add this to https://github.com/desktop/desktop/issues/12699 where we are tracking this request.

**Comment by Nasrullud** [comment]
Unsubscribe

Pada tanggal Sab, 2 Jul 2022 01.11, Carl Lind ***@***.***>
menulis:

**Comment by Watcher3056** [comment]
Why we still don`t have such important feature along with conflict resolve possibility like in Sourcetree?
Everytime when conflicts appear we cannot use github-desktop to properly solve them and need to launch Sourcetree, but Sourcetree is very slow. Today one of our worker encountered out of memory exception while working with Sourcetree and I have no idea how to help him...

**Comment by gcohen-dev** [comment]
Not having multiple stash feature is a real bummer. I had to roll back to the shitty source tree.
