### ISSUE TITLE
Problems with default remote to push

### ISSUE THREAD

**Issue by iamsardorbek** [desktop/desktop#14894]
### The problem

In the past, the push button would show "Push origin", now it shows "Push upstream". I need to push to origin with Ctrl + P, but I can't now.

![image](https://user-images.githubusercontent.com/58874777/176643766-90c183bc-145d-496d-b5c1-63a62d294287.png)

### Release version

3.0.3 (x64)

### Operating system

Windows 10

### Log files

[2022-06-30.desktop.production.log](https://github.com/desktop/desktop/files/9018462/2022-06-30.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/58874777/176644434-dbc91ad7-46e0-4457-bbb8-5b16e9668ddb.png)

**Comment by steveward** [comment]
@iamsardorbek thanks for the issue. This means that you're currently on the `upstream/debug` branch -- did you intent to make changes to the upstream branch or are you wanting to push to the `origin/debug` branch?

**Comment by iamsardorbek** [comment]
@steveward thank you for your prompt reaction!
In fact, I discovered that I was on upstream/debug branch. Trying to change the active branch to origin/debug threw an alert: "Branch with such name already exists". I deleted locally upstream/debug branch and managed to activate origin/debug. Thank you for your time and attention.
