### ISSUE TITLE
Push

### ISSUE THREAD

**Issue by swolfadder** [desktop/desktop#14906]
### The problem

When you make a local change, and after you enter the summary, and select "push"

The application hangs half way through the push, and you have to force close the application, and then re-open the app, and push again, the second push after a force restart, the push goes through right away. 

Happens regardless of network, have tried via VPN as well. 

### Release version

3.0.3 (arm64)

### Operating system

MacOS

### Steps to reproduce the behavior

1. make changes in repo
2. commit changes
3. add summary
4. click push button
5. app hangs forever

**Comment by niik** [comment]
Thanks for the report! Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by swolfadder** [comment]
Funny thing is, the log doesn't show much, but sure
[2022-07-04.desktop.production.log](https://github.com/desktop/desktop/files/9048083/2022-07-04.desktop.production.log)

**Comment by niik** [comment]
Yeah, just like you said, not much to go on there unfortunately. This isn't something I've heard about before so I'm a bit stumped as to what could cause it other than a machine-specific issue, especially given that you say you've tested several networks already.

Do you have access to another machine that you could try this on?

**Comment by swolfadder** [comment]
[Sample of GitHub Desktop.txt](https://github.com/desktop/desktop/files/9066462/Sample.of.GitHub.Desktop.txt)
still happens, 
open GitHub desktop, where a repo has changed, 
add comment, and select commit to main, 
<img width="575" alt="Screen Shot 2022-07-07 at 2 46 15 PM" src="https://user-images.githubusercontent.com/81205911/177847296-93ed2d27-9f5a-48d3-8a22-fc01c76496c2.png">

hit push to origin, and it's just sits there, 
<img width="581" alt="Screen Shot 2022-07-07 at 2 46 33 PM" src="https://user
<img width="732" alt="Screen Shot 2022-07-07 at 2 46 58 PM" src="https://user-images.githubusercontent.com/81205911/177847730-0c9787b0-7249-4339-8537-7e72860a8bbb.png">
-images.githubusercontent.com/81205911/177847463-b52f169f-83d5-4687-9ef0-968fd3f5ac00.png">

no spinning beach ball, 

just hangs indefinitely ... 

you have to force close, and open it again, then the push goest through right away.

**Comment by niik** [comment]
> still happens,

Do you mean this happens on another machine as well?

**Comment by tsvetilian-ty** [comment]
The same problem was reported in https://github.com/desktop/desktop/issues/14942

**Comment by swolfadder** [comment]
> The same problem was reported in #14942

Ok, there still wasn't a resolution ..

**Comment by steveward** [comment]
@ryancollins-dev is there any potential security software on this machine running that could be interfering with network operations? It's definitely strange that things work instantly after a force quit.

Have you tried reinstalling GitHub Desktop to see if that helps at all?

**Comment by swolfadder** [comment]
No security installed other than the default security protocols from Apple. Happens even on a fresh install. 🤦🏻‍♂️

**Comment by swolfadder** [comment]
> No security installed other than the default security protocols from Apple. Happens even on a fresh install. 🤦🏻‍♂️ Sent from Proton Mail for iOS
> […](#)

Not only that, since the last update, it's worse, I have to force close more than 3 times to push, and end up just using the command-line as that goes through instantly, so it's not a problem on my end, it's the app itself..

**Comment by swolfadder** [comment]
I am going to close this issue, I reset my M1 Mac last night, and since then, the issue has gone away.

**Comment by swolfadder** [comment]
Yea I’ll make a few tests from my PC later and report back

**Comment by swolfadder** [comment]
On Mac. Haven’t tried windows yet, just provided some more info that I didn’t have the other day.
