### ISSUE TITLE
Group Repos in Repository List

### ISSUE THREAD

**Issue by andez2000** [desktop/desktop#14902]
### The feature request

I have a number of repos I have committed locally.  Would it be possible to group them in the Repository Tree (by drag and drop)?

I have different repos across GitHub, GitHub Enterprise and Azure Dev Ops - a number of projects - which do get grouped into 2.

![image](https://user-images.githubusercontent.com/16876524/177055237-5102ebd1-3460-48b4-8ad9-aa733f93422c.png)

I would like to add a new label and associate the repos under that label.  And to also change the order of those labels, as well as collapsing and minimising the list.

### Proposed solution

Allow the developer to 
1. Add labels to the Repo List.
2. Rename labels
3. Drag and drop repos from/to a label
4. Remove repo from a label
5. Collapse/Expand all in the list

It would make locating the repo easier by looking.  Sure there is a filter in there.

### Additional context

It might be better practice to only keep what you are working on locally.  But I am a digital hoarder.  Plus I like the benefit of having the code just in case something happens to the repo.

**Comment by niik** [comment]
Thanks for the feedback @andez2000. See [this comment](https://github.com/desktop/desktop/issues/10201#issuecomment-658693653) for more information about why we do not have plans to implement repository grouping at this time. 

One workaround is to use the repository alias feature and then use that to filter by a specific alias prefix. I hope that helps.
