### ISSUE TITLE
Pull Not Done

### ISSUE THREAD

**Issue by sumuanimator** [desktop/desktop#14904]
fatal: update_ref failed for ref 'ORIG_H
![image](https://user-images.githubusercontent.com/52774777/177153446-ad034573-afc3-43cc-85f6-df78b040b4da.png)
EAD': cannot lock ref 'ORIG_HEAD': unable to resolve reference 'ORIG_HEAD': reference broken

**Comment by niik** [comment]
Hey @sumuanimator, thanks for reaching out. It looks like your repository has become corrupt somehow. Have you had a recent computer malfunction during a pull perhaps? Another common cause is storing repositories on cloud sync services like Dropbox or Onedrive.

Could you check in your repository folder if there's a file in the `.git` folder called `ORIG_HEAD` or `ORIG_HEAD.lock` and check the contents of those? Chances are you can move those two files somewhere else and have Git recreate them on the next pull.

**Comment by Lul-Abdifan** [comment]
Hello there, @niik @sumuanimator why do you close the issue with no solution.
