### ISSUE TITLE
Please add identifier like branch name to "Squash and merge into current branch..." commits, e.g. "Squashed commit of some-branch-name"

### ISSUE THREAD

**Issue by AlanSl** [desktop/desktop#14908]
### The feature request

The new feature to allow squash-merging in branches from the "Branch" menu is really great! I already use it a lot to conveniently create integration branches, squash-merging the current state of open PRs in a way that is really easy to tidy up in an interactive rebase from the command line once those PRs are merged - `git rebase -i origin/main`, then `drop` all the `Squashed commit...` commits that will be replaced by the new commits on main.

The only problem is, the first line of the commit description (and therefore the line visible in lists such as Github Desktop UI history panel) is the same for all such squashed commits - "Squashed commit of the following changes:" - so if I'm integrating more than one branch, my local commit history is not very readable:

> **Squashed commit of the following changes:**
> My name - 25 minutes ago
> 
> **Some recent change in this branch**
> My name - 29 minutes ago
> 
> **Squashed commit of the following changes:**
> My name - 37 minutes ago
> 
> **Some earlier change done in this branch**
> My name - 48 minutes ago

The feature would be even better if the commits created by squash merge contained something from the target branch that simply and clearly identified which branch they came from.

### Proposed solution

Add in the name of the branch instead of "the following changes", with truncation if necessary, for example:

> **Squashed commit (some-new-feature)**
> My name - 25 minutes ago
> 
> **Some recent change in this branch**
> My name - 29 minutes ago
> 
> **Squashed commit (fix-that-broken-thing-tha...)**
> My name - 37 minutes ago
> 
> **Some earlier change done in this branch**
> My name - 48 minutes ago

---

Or maybe better still, use the branch name and a reference to the latest specific commit as well, so it's clear what's going on if the feature is used to apply updates from a moving open branch:

> **Squashed: some-new-feature 4b12a27**
> My name - 25 minutes ago
> 
> **Some recent change in this branch**
> My name - 29 minutes ago
> 
> **Squashed: fix-that-broken-thing-that-c... 91hnbd**
> My name - 37 minutes ago
> 
> **Squashed: some-new-feature 1j1b3j8**
> My name - 43 minutes ago
> 
> **Some earlier change done in this branch**
> My name - 48 minutes ago

**Comment by niik** [comment]
Hey @AlanSl, thanks for reaching out!

This commit message is actually not something that GitHub Desktop composes, it's the default behaviour of [Git itself](https://github.com/git/git/blob/30cc8d0f147546d4dd77bf497f4dec51e7265bd8/builtin/merge.c#L437). We merely call upon `git merge --squash` here and have Git auto-generate the commit message.

While we could override the message our first approach is to stay true to Git's behavior unless we have a compelling reason not to. It's possible this would count as a compelling enough reason and I'll mark it as a possible enhancement but I would appreciate if you could bring up this discussion with the Git project instead. If the change is made in Git it'll benefit everyone including command line users.

**Comment by niik** [comment]
I'm going to close this out as we're not planning on working on this given the reasoning I outlined above.
