### ISSUE TITLE
Help Requested

### ISSUE THREAD

**Issue by Merrylegs1** [desktop/desktop#14918]
Good Evening.

I have installed github.com But I cannot seem to get the full window as shown in the tuturial.
Where am I going wrong?
I would appreciate advice

Kind Regards

James Merrilees
jamesmerrilees@outlook.com
Take Care - Stay Safe

**Comment by niik** [comment]
Hey @Merrylegs1, could you provide us with a link or screenshot to the tutorial you're attempting to follow? Thanks
