### ISSUE TITLE
Problem plublishing my repo 

### ISSUE THREAD

**Issue by samemah24** [desktop/desktop#14912]
### The problem

![bug](https://user-images.githubusercontent.com/101899392/177495711-9f6e09e4-51d5-45c3-94bc-7232a773751c.JPG)
Im trying to publish a repo but it tells me to be connect to internet and im already as you can see on the screenshot

### Release version

Version 3.0.3 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

go to the app
choose a repo you want to work on 
then try to publish it

### Log files

[2022-07-06.desktop.production.log](https://github.com/desktop/desktop/files/9052661/2022-07-06.desktop.production.log)

### Screenshots

![bug](https://user-images.githubusercontent.com/101899392/177496342-bba61bc7-76d0-49e0-8273-50e1f8672510.JPG)

**Comment by tsvetilian-ty** [comment]
@samemah24 thanks for the report! The issue seems to be related to the communication with `https://api.github.com`. If you have antivirus software, you can try adding GitHub Desktop as "excluded" in your AV to ensure it's not cutting your connection to GitHub! 

Do you authenticate through the browser or with PAT? Also, do you use a proxy?

**Comment by samemah24** [comment]
Through the browser and with no proxy

Le mer. 6 juil. 2022 11:31, Tsvetilian Yankov ***@***.***> a
écrit :

**Comment by tsvetilian-ty** [comment]
You can try re-instating GitHub Desktop as suggested by [this comment](https://github.com/desktop/desktop/issues/14780#issuecomment-1154981034). The issue logs match the ones you shared 🤔

**Comment by samemah24** [comment]
i tried and it works fine thanks
ᐧ

**Comment by niik** [comment]
Thanks for reporting back @samemah24, and thanks for helping resolve this @tsvetilian-ty!
