### ISSUE TITLE
Remove and untrack a file

### ISSUE THREAD

**Issue by sctn4elk** [desktop/desktop#14923]
### The feature request

Some times a file gets added to the repo accidentally and you only realize after the fact. Add the feature to remove and untrack the file and auto add it to the .gitignore file.

### Proposed solution

Add a new option to the right mouse-click pop up menu to perform a "Untrack and ignore" option. Simply execute from the desktop version in the same manner as executing "git rm --cached <file path>".

### Additional context

![image](https://user-images.githubusercontent.com/8302924/177826699-22368943-7001-4e0f-af5b-37afa0236471.png)

**Comment by steveward** [comment]
Consolidating this with https://github.com/desktop/desktop/issues/2537, which is a bug report about duplicate entries being added to `.gitignore` when a file is already tracked by Git.
