### ISSUE TITLE
Implementation of a backtracking system with undo (commits, ...)

### ISSUE THREAD

**Issue by Linj1k** [desktop/desktop#14928]
### The feature request

When you undo a commit it deletes all the changes made without any possibility of going back....

### Proposed solution

Be able to CTRL-Z or not delete changes

### Additional context

I lost at least 6 hours of work because of this ....

**Comment by niik** [comment]
Hi @Linj1k, sorry to hear you lost work! I'm not quite sure how though, undoing a commit in GitHub Desktop is the equivalent of doing a [mixed reset](https://git-scm.com/docs/git-reset#Documentation/git-reset.txt---mixed) which leaves your changes in-place in the working directory. Undoing a commit and then discarding changes will, however, delete the changes. Is it possible that's what happened here?

Fortunately there's a good chance, assuming that the undo happened relatively recently, that the original commits are still recoverable by using the reflow to find the commit in question and then restoring them using `git cherry-pick`. This will require a little fiddling around in the command line but fortunately there are plenty of guides out there on how to restore lost commits. See for example https://www.geeksforgeeks.org/recovering-lost-commits-in-git/ and https://rewind.com/blog/how-to-restore-deleted-branch-commit-git-reflog/.



> When you undo a commit it deletes all the changes made without any possibility of going back....

Given what I wrote above this shouldn't happen. Do you think you could outline in more detail what you did or (better yet) put together reproducible steps?
