### ISSUE TITLE
I LOST MY REPOSATIRY BY M ISTAKE 

### ISSUE THREAD

**Issue by SmayanSingh** [desktop/desktop#14939]
### The feature request

I WANT TOR RECOVER MY PROJECT IN DELETED BY MISTAKE IS THERE ANY WAy by which I can get it back ??? 

### Proposed solution

want bvack my repo

### Additional context

please help

**Comment by niik** [comment]
Hi @SmayanSingh, if you delete a repository in GitHub Desktop the contents of the repository will either stay where it was initially cloned or created, or if you selected the option to move it to trash it will en up in the Recycle Bin on Windows or Trash on macOS from where it can be restored.

If you deleted a repository on GitHub.com and want to get it back this isn't the best place to get answers as we can only answer questions about GitHub Desktop but assuming that you've cloned the repository to your machine you can always publish the repository again. If your question concerns deleting repositories on GitHub.com I'd suggest visiting https://support.github.com/?tags=dotcom-direct to find more information.

Best of luck!
