### ISSUE TITLE
Github Desktop does not update local default branch when changed on web

### ISSUE THREAD

**Issue by rocketjeff** [desktop/desktop#14932]
### The problem

I changed a repository's default branch on the web. GitHub Desktop still shows the old default branch, even after several pulls and restarts.

### Release version

3.0.3

### Operating system

MacOS 12.4

### Steps to reproduce the behavior

1. Changed a repository's default branch on the web. 
2. Open GitHub Desktop
3. GitHub Desktop still shows the old default branch, even after several pulls and restarts. still shows the old default branch.

**Comment by tsvetilian-ty** [comment]
@rocketjeff thanks for the report! This is a known issue, and we are tracking it in https://github.com/desktop/desktop/issues/14266

I will close this issue in favor of the original report.
