### ISSUE TITLE
Can't push local comits to GitHub

### ISSUE THREAD

**Issue by hartgebh** [desktop/desktop#14931]
### The problem

Suddenly unable to commit to GitHub. The error message states:
"The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed."

When I go to GitHub in my browser, the repository is there, but I cannot edit individual files. 
The message is "You must be able to fork repositories to propose changes."

I do not have this issue with another repository.

### Release version

Version 3.0.3 

### Operating system

Windows 10 Enterprise

### Steps to reproduce the behavior

1. Go to https://github.ibm.com/hdm/asm-docs/tree/dita_ASM1114
2. Select a file and click the Edit pencil icon.

### Log files

[2022-07-08.desktop.production.log](https://github.com/desktop/desktop/files/9073586/2022-07-08.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/88485899/178031987-fd88a032-1abc-49ce-9dd7-b4e66f82ddf3.png)

**Comment by tidy-dev** [comment]
> When I go to GitHub in my browser, the repository is there, but I cannot edit individual files.
The message is "You must be able to fork repositories to propose changes."

Given you receive access errors in the browser, it appears your user account lacks the permissions required to make changes on this repository. This is not an issue with GitHub Desktop. You need to contact the manager of your repository. If you can regain editing access to this repository in the browser, you may need to log out and log back in on GitHub Desktop.
