### ISSUE TITLE
Add version number in installer file and https://desktop.github.com/

### ISSUE THREAD

**Issue by Firestar-Reimu** [desktop/desktop#14949]
### The feature request

Add version number in installer file and https://desktop.github.com/

Every time I download the installer, I cannot know whether it has updated. All file name are `GitHubDesktopSetup-x64.exe` and https://desktop.github.com/ has no word like `Download Github Desktop 3.0.3`.

### Proposed solution

`GitHubDesktopSetup-(version_number)-x64.exe`

![image](https://user-images.githubusercontent.com/65082432/178244985-55e341fc-389f-41e2-a03e-0ea7f3f3ae17.png)

**Comment by steveward** [comment]
@Firestar-Reimu thanks for the feedback here. I'm going to close this out as viewing the [release notes](https://desktop.github.com/release-notes/) is the best way to see the latest version number and release info prior to downloading.
