### ISSUE TITLE
Trying to push my files on my fork 

### ISSUE THREAD

**Issue by JonnycatMeow** [desktop/desktop#14942]
### The problem

everytime i push my files on my fork it it just stuck there 
 

### Release version

3.0.3

### Operating system

macOS 64 bit intel  

### Screenshots

![Screen Shot 2022-07-10 at 3 17 06 PM](https://user-images.githubusercontent.com/107599365/178164072-a7e5317d-8488-4448-a6c1-f08e32353ef2.png)

**Comment by tsvetilian-ty** [comment]
Thanks for the report @ItsyourboyJonnycat! Could you upload a log file "Help > Show logs..." Also, your issue looks similar to https://github.com/desktop/desktop/issues/14906 can you confirm if you're experiencing the same behavior?

**Comment by JonnycatMeow** [comment]
yes

**Comment by tsvetilian-ty** [comment]
@ItsyourboyJonnycat could you share a log file in GitHub Desktop (`Help > Show logs...`)? 
We need the log file to check if there is helpful information that can lead to a solution.

**Comment by JonnycatMeow** [comment]
i don't have the log files cause i quited the upload and removed it sorry

**Comment by tsvetilian-ty** [comment]
No worries 👍 I will close this issue in favor of https://github.com/desktop/desktop/issues/14906. You can follow there for any updates
