### ISSUE TITLE
iOS app won't open

### ISSUE THREAD

**Issue by boydpearce** [desktop/desktop#14954]
### The problem

Xcode error message: Failed to launch script /Users/boydpearce/Documents/GitHub/MyGrandKids/my_grand_kids/ios/Runner.xcworkspace: The operation couldn’t be completed. Permission denied

### Release version

3.0.3 (x64)

### Operating system

iOS 15.5

### Steps to reproduce the behavior

1. Use this public link to Apple App Store https://testflight.apple.com/join/L8zR0fXY to get My Family & Friends internal test version 1.8.15 release 151
2. TestFlight must be installed on device
3. From App Store, install & open app to see white screen and app not complete loading

### Screenshots

<img width="1440" alt="Screen Shot 2022-07-12 at 6 30 11 AM" src="https://user-images.githubusercontent.com/48601052/178413230-bcfba4ba-b54d-45f4-8981-4613fb7af053.png">

**Comment by sergiou87** [comment]
I'm sorry but this is the repository of GitHub Desktop, so I'm afraid we cannot help you with that issue.
