### ISSUE TITLE
When cloning a repo use the developer name as part of the suggested path

### ISSUE THREAD

**Issue by potanin** [desktop/desktop#14951]
### The feature request

Currently, GitHub desktop always suggests a location using the last cloned developer name followed by the project name. Which is confusing as if you go and checkout rust-lang/rust under the same folders on your computer (rust-lang/rust) and then try to checkout desktop/desktop - it will suggest rust-lang/desktop. Why not suggest both developer name and the project name rather than just project name?

### Proposed solution

As per above description. Perhaps when the user is placing the folder they may be given a choice to suggest "developer name/project name" as the suggested path location not only "project name" in the last working folder?

**Comment by tidy-dev** [comment]
@potanin Thank you for the suggestion. The provided location is only meant as quick suggestion. If a user has another preference, they can use the file finder to select the parent folder of their choice or manually type in their preferred directory. As the user already has choice of where to clone to, I am closing this ticket.
