### ISSUE TITLE
My github pages automatically redirect to another domain

### ISSUE THREAD

**Issue by Rancho2002** [desktop/desktop#14959]
### The problem

I have created a  domain from namecheap using my github student pack. After that, my websites that are hosted in github automatically redirect to another website(same website that I have created in namecheap). There is no solution I found till now. Here is the example of one of my github page: 
https://rancho2002.github.io/mysimplecalculator/

### Release version

Version 2.9.6 (x64)

### Operating system

Windows 11

### Screenshots

![githubIssue](https://user-images.githubusercontent.com/92109154/178578268-2ff5a8ea-9d9c-41c4-95b3-40e54c8dd62a.png)

**Comment by tsvetilian-ty** [comment]
Hey, @Rancho2002 your issue is not related to GitHub Desktop, so I will close it! But I checked [your repo](https://github.com/Rancho2002/Rancho2002.github.io), and you have `CNAME` file in it, which I assume is the reason for the redirects. You can read more on the topic of managing GitHub pages at https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

**Comment by Rancho2002** [comment]
thank you very very very much @tsvetilian-ty, you are a life savior. My issue is resolved successfully.

**Comment by derek-yip** [comment]
I have the same problem, I use the custom domain has error now, even I revert the previous version of my repo commit. My github public page always redirect to wrong domain instead of github-io

**Comment by gketronDS** [comment]
@derek-yip Same problem here. I added and removed a cname file so much I think I broke the pages backend. I may try either renting the redirected domain name or redeploying my code to a the public page since I messed up a project page

**Comment by Abhishek-Sumn** [comment]
> thank you very very very much @tsvetilian-ty, you are a life savior. My issue is resolved successfully.

how did you solved it ??

**Comment by TheBlckbird** [comment]
@Abhishek-Sumn Github automatically creates a CNAME file in your repo to redirect you. You have to remove your custom domain and delete the CNAME file or rerun your actions

**Comment by ishankgoel** [comment]
@TheBlckbird 
How to solve this? I have the exact same problem. My namecheap domain got expired & even after deleting the cname from my repo, it still redirects to old domain. I even deleted my repo & created new one still facing same problem. Re-running actions also didn't help. Please help

**Comment by TheBlckbird** [comment]
@ishankgoel hm idk, sry...

**Comment by ritikeshgupta** [comment]
@tsvetilian-ty I am also facing the same issue (`ritikeshgupta.github.io` is being redirected to `ritikeshgupta.com`) can you look into this?

**Comment by TheBlckbird** [comment]
it isn’t redirecting for me.
have you tried restarting your PC?
Maybe it has cached it somehow

**Comment by ishankgoel** [comment]
@ritikeshgupta your github page is not redirecting. Try doing a shift + refresh or ctrl + refresh while loading page

**Comment by Thecartoondude** [comment]
I have the same problem. I am making a rep called PBS-Kids-2006 but the site still redirects to the custom domain I removed.
https://thecartoondude.github.io/PBS-Kids-2006/
Can you fix the problem?

**Comment by steveward** [comment]
@Thecartoondude I'd recommend asking for help at https://github.com/orgs/community/discussions/categories/pages as this issue tracker is for GitHub Desktop, not GitHub Pages.

**Comment by B1TSH3LL** [comment]
same issue , i dont have any cname file, my namecheap domain got expired and github page is redirecting towards it.
https://github.com/B1TSH3LL/Green-Screen
Please Help.

**Comment by bharathkodakandla** [comment]
![Screenshot 2024-04-06 204233](https://github.com/desktop/desktop/assets/154347788/e21b543d-0879-4f9c-82f9-7aedc1618ff0)

**Comment by mukund0911** [comment]
I cleared my browser cache memory. It worked then.

**Comment by mukund0911** [comment]
> same issue , i dont have any cname file, my namecheap domain got expired and github page is redirecting towards it. https://github.com/B1TSH3LL/Green-Screen Please Help.

I cleared my browsing cache memory, and it worked.

**Comment by tdh1985** [comment]
> same issue , i dont have any cname file, my namecheap domain got expired and github page is redirecting towards it. https://github.com/B1TSH3LL/Green-Screen Please Help.

did you find an answer?
