### ISSUE TITLE
Slow Desktop Github

### ISSUE THREAD

**Issue by sakadana** [desktop/desktop#14956]
### The problem

Github Desktop is Slow when used to work on projects even though I use HP Pavilion Gaming 15 Laptops, I think all applications are slow. In fact this is very unreasonable

### Release version

Version 3.0.3 (x64

### Operating system

WIndows

**Comment by tidy-dev** [comment]
Duplicate of https://github.com/desktop/desktop/issues/14950. Please follow those there for suggestions to try.
