### ISSUE TITLE
Unable to change branches in Git Desktop

### ISSUE THREAD

**Issue by FinellaM** [desktop/desktop#14963]
### The problem

Hi,
I have been creating new branches regularly. I am constantly receiving a message that I can't switch to them. 

### Release version

Version 3.0.3 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Create new branch off  Main
2. Switch to new branch
3. Error message received.
![image](https://user-images.githubusercontent.com/36837664/178663087-ee124dbe-abe9-41a8-922e-b25c588ced11.png)

### Log files

[2022-07-13.desktop.production.log](https://github.com/desktop/desktop/files/9099412/2022-07-13.desktop.production.log)

### Additional context

It's happening with every new branch I create. And then all of a sudden, it will finally let me switch. Creating a new branch in github.com and then selecting 'Open in GitHub desktop' doesn't work either. Github desktop will keep opening to the branch it appears to be stuck on.

**Comment by tsvetilian-ty** [comment]
@FinellaM thanks for the report!

Could you try to clone the repo in another directory? Also, ensure that no other software is locking the directory, as reported in https://github.com/desktop/desktop/issues/11992

**Comment by tidy-dev** [comment]
@FinellaM Curious if `Mcba - Assignment 2` is open in a program that locks access to it when you try to switch to the new branch? For example, if it was a PDF and opened in adobe acrobat.

If so, you should just need to close the locking program and try again.
