### ISSUE TITLE
Add search feature on file changes list

### ISSUE THREAD

**Issue by malisancube** [desktop/desktop#14968]
### The feature request

I'd like to have a search feature that can enable users to search and find a file by name or extension. This would mean adding a searchbox above the lists.

![image](https://user-images.githubusercontent.com/586423/178854407-c1bea203-8c8c-4208-acf6-4cd8b205478e.png)

### Proposed solution

Users will be able to search for files that they have changes to quicky omit them from the commit or include the selected files that have been search and found.

### Additional context

It may happen that after adding some npm packages you alos make some changes to some files and intend to look for a specific file to exclude from the commit.

**Comment by tsvetilian-ty** [comment]
@malisancube thanks for riching out! There is already a discussion on the topic you can follow it in https://github.com/desktop/desktop/issues/6407
