### ISSUE TITLE
Cant add existing repository

### ISSUE THREAD

**Issue by borisdelev** [desktop/desktop#14966]
### The problem

Hi there, 
My issue is simple: I cant add any existing local repository to Github Desktop

If it is already reported- sorry, didn't find it.
Greetings and may the force be with you :)

### Release version

3.0.4

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Open File -> Add Local repository 
2. Select folder with existing repo ... then error appear

### Log files

[2022-07-13.desktop.production.log](https://github.com/desktop/desktop/files/9103117/2022-07-13.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/4441663/178757891-1577b568-740b-4412-8f3c-360294bfe0ff.png)

**Comment by tsvetilian-ty** [comment]
Hey @borisdelev 👋 

It looks like GitHub Desktop doesn't detect this directory as a git repo 🤔 Could you run `git status` in `D:\www\kmk`?

**Comment by borisdelev** [comment]
Ive resolve my issue... its somehow Folders owner was changed (maybe because windows reinstall)... and it doesn't matter current user have full access, must replace owner of parent directory.

![image](https://user-images.githubusercontent.com/4441663/178778000-20cc55da-87df-4bb0-9439-1a706c7157e2.png)

**Comment by rtarnaud** [comment]
Same issue here.
The repo is fine (checked with git status).
That issue started with the latest update although I also restarted the computer to install some Windows updates.

**Comment by stakach** [comment]
also have the same issue where repositories are located on WSL2 and exposed to windows via a mapped network drive.
Existing repositories continue to work, however I can no longer add a new repository
<img width="295" alt="image" src="https://user-images.githubusercontent.com/368013/178914016-6952563a-21ff-4256-8cb9-397cadfeb3ca.png">

on linux
<img width="549" alt="image" src="https://user-images.githubusercontent.com/368013/178914215-94c9ae2d-96b7-4047-8534-7c3353f94e9b.png">

github desktop used to ask to make this exception as part of the add dialog, however this is no longer the case in the new version.
<img width="854" alt="image" src="https://user-images.githubusercontent.com/368013/178913876-eae96d13-a351-4c07-b9c1-6263c80376fe.png">

After adding the exception manually from the command line, then I was able to add the repository to github desktop

**Comment by sergiou87** [comment]
Hi @borisdelev @rtarnaud 👋 

As I mention in https://github.com/desktop/desktop/issues/14970#issuecomment-1184102149 this is indeed a regression in 3.0.4, but we'll release a fix ASAP. Sorry for all the trouble 😢

**Comment by borisdelev** [comment]
> Hi @borisdelev @rtarnaud 👋 
> 
> As I mention in https://github.com/desktop/desktop/issues/14970#issuecomment-1184102149 this is indeed a regression in 3.0.4, but we'll release a fix ASAP. Sorry for all the trouble 😢 

U are great! Thank you!!!

**Comment by jonasflynn66** [comment]
hmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm

**Comment by sergiou87** [comment]
@stakach @borisdelev @rtarnaud you can now download 3.0.5 which should fix this issue. Thank you for your patience!

**Comment by borisdelev** [comment]
@sergiou87 Many thanks. You awesome :)
