### ISSUE TITLE
How do we reduce memory footprint of Github on laptop?

### ISSUE THREAD

**Issue by c2rosa** [desktop/desktop#14977]
### The feature request

Presently I am seeing a huge memory footprint in the subdirectory:
C:\Users\rosa.charles\AppData\Local\SquirrelTemp
This seems to be where GitHub stores a lot of stuff.
Would love there to be some facility in github which cleans this out and reduces the amount of stuff stored in this area.

### Proposed solution

Having this feature would help users of Github save memory on their laptops/computers.

**Comment by niik** [comment]
Hey @c2rosa, sorry for us dropping this issue. SquirrelTemp is created by the installer/updater that we (by means of Electron) use. Normally that folder should be cleaned up automatically but there are cases where it doesn't but it's perfectly fine to delete it yourself, see https://github.com/Squirrel/Squirrel.Windows/issues/1195
