### ISSUE TITLE
Window border shows up on another monitor when maximized

### ISSUE THREAD

**Issue by MehediH** [desktop/desktop#1497]
On the new GitHub desktop, the window border shows up on the secondary monitor when maximized on a multi-monitor setup. I believe the issue is caused by the custom titlebar, as there was a similar bug with my app that's also built on Electron. 

I can't actually screenshot the issue for some reason, but here's a picture: http://i.imgur.com/BAitqx7.jpg

**Comment by shiftkey** [comment]
cc @desktop/electron

**Comment by xt0rted** [comment]
I'm seeing this as well. I'm not seeing this with my other Electron based apps, just GitHub Desktop.

This is what it looks like with GitHub Desktop maximized and then Chrome maximized over top of it. The thin white line is the border from GitHub Desktop on the other display.

### Version

**GitHub Desktop version:** 0.5.5
**OS version:** Win10 Creators Update (10.0.15063)

![image](https://cloud.githubusercontent.com/assets/831974/26267327/81a698c6-3cb7-11e7-9520-e26b73dc31da.png)

**Comment by steveward** [comment]
Closing this in favor of #13939 as the more recent issue.
