### ISSUE TITLE
Can't add existing repository on file share

### ISSUE THREAD

**Issue by stakach** [desktop/desktop#14970]
### The problem

Where repositories are located on WSL2 and exposed to windows via a mapped network drive.
Existing repositories continue to work, however I can no longer add a new repository

<img width="295" alt="image" src="https://user-images.githubusercontent.com/368013/178914016-6952563a-21ff-4256-8cb9-397cadfeb3ca.png">

on linux

<img width="549" alt="image" src="https://user-images.githubusercontent.com/368013/178914215-94c9ae2d-96b7-4047-8534-7c3353f94e9b.png">

github desktop used to ask to make this exception as part of the add dialog, however this is no longer the case in the new version.

<img width="854" alt="image" src="https://user-images.githubusercontent.com/368013/178913876-eae96d13-a351-4c07-b9c1-6263c80376fe.png">

After adding the exception manually from the command line, then I was able to add the repository to github desktop

related to #14966 (probably)

### Release version

Version 3.0.4 (x64)

### Operating system

Windows 11

**Comment by sergiou87** [comment]
Thank you for your detailed report @stakach 🙇 

It seems we introduced a regression in 3.0.4 as you can read in #14971 (which also contains the fix). We'll deploy a new version ASAP with the fix. We're very sorry for any inconvenience this could've caused you!

**Comment by sergiou87** [comment]
This has been fixed in v3.0.5 (I hope it works for you now, @stakach 🤞 ), closing…
