### ISSUE TITLE
Desktop default repo does not match ADO

### ISSUE THREAD

**Issue by MarteenXCB** [desktop/desktop#14978]
### The problem

ADO default repo set to something that is not named "master" .  Github desktop does not detect the new default repo.

### Release version

3.0.4

### Operating system

windows 10

### Steps to reproduce the behavior

change default repo in ADO
wait 5 minutes or so for the change to propagate
restart github desktop
try to creat new branch -- github has old default repo , not the new default report

**Comment by sergiou87** [comment]
Hi @MarteenXCB 👋 

Thanks for your report, but I think is the same as https://github.com/desktop/desktop/issues/14266 so I'm gonna close this issue in favor of that one. Please, feel free to subscribe to #14266 if you want to get notified when we make progress on it (hopefully soon)
