### ISSUE TITLE
App should open on the same display as last opened on

### ISSUE THREAD

**Issue by asger-noer** [desktop/desktop#14973]
### The feature request

When the app is restarted or opened, the app should reopen on the display where is was closed. If that display is not available, the app should open on the main display.

### Proposed solution

Open on display where the app was closed. if that display is not available, the app should open on the main display.

**Comment by sergiou87** [comment]
Hello @AsgerNoer !

That issue is probably related to Electron, which we upgraded in the beta builds of GitHub Desktop. Do you mind trying the latest beta and see if it behaves as you'd expect? 

You can download it from https://desktop.github.com/beta

**Comment by asger-noer** [comment]
Hi @sergiou87 

Just tried the beta build. Seems to work. I found a bug though. If it is made fullscreen on display 1 and then moved to display 2 or 3 in mission-ctrl, then it'll still reopen on the display 1 if the app is closed or restarted.
