### ISSUE TITLE
Permission denied- Cannot clone

### ISSUE THREAD

**Issue by presianrusinov** [desktop/desktop#14987]
### The problem

Hello I could not clone or create any new repositories. I am using GitHub desktop how can i solve this problem

### Release version

Version 3.0.5 (x64)

### Operating system

Windows 11

**Comment by tsvetilian-ty** [comment]
Thanks for reaching out @presianrusinov! Could you upload a log file from GitHub Desktop (Help > Show logs...)? The log files are generated daily.

**Comment by presianrusinov** [comment]
Hi, here is the file. Thanks for reaching out








 >-------- Оригинално писмо --------

 >От: Tsvetilian Yankov ***@***.***

 >Относно: Re: [desktop/desktop] Permission denied- Cannot clone (Issue #14987)

 >До: desktop/desktop  

 >Изпратено на: 18.07.2022 18:33



 
 
  
  
  
Thanks for reaching out  @presianrusinov ! Could you upload a log file from GitHub Desktop (Help > Show logs...)? The log files are generated daily.

**Comment by tsvetilian-ty** [comment]
Hey @presianrusinov I'm unable to see the log file! I think that if you attached it to the email, it would not appear in the issue tracker. Could you paste/upload it in the issue?

**Comment by presianrusinov** [comment]
>  @`
[2022-07-18.desktop.production.log](https://github.com/desktop/desktop/files/9135709/2022-07-18.desktop.production.log)
`

**Comment by presianrusinov** [comment]
Hello, sorry for the delay. Here is the file 
[2022-07-18.desktop.production.log](https://github.com/desktop/desktop/files/9140498/2022-07-18.desktop.production.log)

**Comment by tsvetilian-ty** [comment]
It looks like you don't have write permissions🤔 You could try to create another folder for your projects. I see you're using a folder in the `Users` directory (`C:\Users\GitHub projects\`). 

Could you try to create a folder in `C:\Users\{your_current_user}\projects`?

**Comment by presianrusinov** [comment]
It worked. Thanks . If it's not a problem, could you please tell me why was this issue caused? I didn't knew that if the folder is not in users I wouldn't have write permissions. Sorry if I sound noobish

**Comment by tsvetilian-ty** [comment]
Glad it worked 🥳 The reason for the issue is that the `Users` folder in Windows requires Administrator privileges. GitHub Desktop runs with your current user privileges, so it gets permission denied when it tries to clone in the `Users` folder.
