### ISSUE TITLE
Repositories Not Shown on Desktop App

### ISSUE THREAD

**Issue by Tarek-Hijazi** [desktop/desktop#14981]
### The problem

Dear Support,

I have recently joined the GitHub and have been added to our company profile. I was able to see the repositories on the company GitHub page. However, The repositories are not shown in the GitHub desktop application.

Please help me in this

### Release version

3.0.5

### Operating system

Windows 10

**Comment by sergiou87** [comment]
Hello @Tarek-Hijazi 👋 

Did you log in with your Enterprise account in GitHub Desktop? You can find more info about that here: https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/installing-and-authenticating-to-github-desktop/authenticating-to-github#authenticating-an-account-on-github-enterprise
