### ISSUE TITLE
Mac download page not found ???

### ISSUE THREAD

**Issue by git-cncoder** [desktop/desktop#14991]
### The problem

Mac download page not found ???
https://github.com/deployments/desktop/desktop/latest/darwin-arm64

### Release version

darwin-arm64

### Operating system

darwin-arm64

**Comment by sergiou87** [comment]
Hi @sun-fight , I'm afraid that's the wrong link. Where did you get it from?

You can download GitHub Desktop from https://desktop.github.com/

More specifically, if you want the Apple Silicon build, the link is this: https://central.github.com/deployments/desktop/desktop/latest/darwin-arm64

**Comment by git-cncoder** [comment]
Hi @sergiou87 ,I get it from https://github.com/desktop/desktop#where-can-i-get-it
And click [macOS (Apple Silicon)](https://central.github.com/deployments/desktop/desktop/latest/darwin-arm64).
I don't know why `central.github.com` change to `github.com`.
But now it's normal work.
