### ISSUE TITLE
Diff selection shouldn't includes +s and -s

### ISSUE THREAD

**Issue by mdiep** [desktop/desktop#1499]
### Description

<img width="927" alt="diff-selection" src="https://cloud.githubusercontent.com/assets/1302/26119686/15687198-3a3c-11e7-8426-024a6a23b60b.png">

Desktop of yore didn't includes the `+`s and `-`s in the diff selection. This is handy for copy and paste, and it's something I make frequent use of. This Desktop should do the same. ☺️ 

### Version

**GitHub Desktop version:** 0.5.3
**OS version:** 10.12.4

### Steps to Reproduce

1. Open a repo
2. Open a diff
3. Select multiple changed lines
4. Copy and paste

**Comment by shiftkey** [comment]
@mdiep nice spot. I'm not sure if this is a CodeMirror (the editor we use in here) limitation or not.
