### ISSUE TITLE
Unable to connect to repository

### ISSUE THREAD

**Issue by ONeill632** [desktop/desktop#14990]
### The problem

Logged in and greeted with the screenshot provided. Can no longer connect to the current repository.  Application updated yesterday

### Release version

Version 3.05 (x64)

### Operating system

Windows 10

### Log files

[2022-07-19.desktop.production.log](https://github.com/desktop/desktop/files/9138716/2022-07-19.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/96053365/179695287-4b7f5e81-15f6-468a-a1b0-28add9a65b3a.png)

**Comment by sergiou87** [comment]
Hello @BrianONeill632  👋 

We've seen those kinds of issues in the past when an antivirus marked the git binaries inside of GitHub Desktop as dangerous. You might need to tell your antivirus that GitHub Desktop is safe, and then reinstall it to get those binaries back to normal.

Please, let me know if that helps 🤞
