### ISSUE TITLE
Github Desktop Super Lagging / Almost not responding

### ISSUE THREAD

**Issue by AchmadRijalu** [desktop/desktop#15004]
I just got updated to windows 11 and also resetting my windows because of several problem before.  and then i redownload my git stuff and github desktop, but i got a problem here that make me frustrating. When i open github desktop i got around almost 1-2 minutes thats all button can hovered and clicked. After several action, its happening again like the hover are late , drop down are not showed and i almost can't use it this github. Please help me 
![Screenshot 2022-07-21 010123](https://user-images.githubusercontent.com/70996942/180051125-799a61c5-a8ad-45ae-af73-a05f0f26b5d9.png)

**Comment by steveward** [comment]
Thanks for the report @AchmadRijalu. We are tracking this in https://github.com/desktop/desktop/issues/14950 -- you can see the [steps here](https://github.com/desktop/desktop/issues/14950#issuecomment-1190122116) that may help us narrow the issue. I'm going to close this issue out in favor of #14950.
