### ISSUE TITLE
Close Repo list menu after removing last repo

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1500]
### Description
In order to highlight the "No repositories found" page, we should close the repo list menu after removing last repo.

### Version

**GitHub Desktop version:** v0.0.53
**OS version:** OSX 10.11.5

### Steps to Reproduce

1. Remove last repo
1. Repo list stays open

<img width="1129" alt="screen shot 2017-05-16 at 1 45 48 pm" src="https://cloud.githubusercontent.com/assets/14828183/26120407/a9a212e0-3a3e-11e7-8b61-88182fa335b3.png">

**Expected behaviour:** Repo list should close to highlight the "No repositories found" page

**Actual behaviour:** Repo list stays open

**Reproduces how often:** 100%

**Comment by kevinlitchfield** [comment]
May I try my hand at this, @tierninho?

**Comment by shiftkey** [comment]
@kevinlitchfield I'm happy to mark this as `up-for-grabs`. Good luck!

**Comment by kevinlitchfield** [comment]
@shiftkey Thanks!

**Comment by shiftkey** [comment]
I've got a rough patch together for this, if someone wants to do some testing and confirm this fixes the issue:

```diff
diff --git a/app/src/lib/stores/app-store.ts b/app/src/lib/stores/app-store.ts
index 634b126fd..f5e678577 100644
--- a/app/src/lib/stores/app-store.ts
+++ b/app/src/lib/stores/app-store.ts
@@ -2869,7 +2869,12 @@ export class AppStore extends TypedBaseStore<IAppState> {
       await this.repositoriesStore.removeRepository(id)
     }

-    this._showFoldout({ type: FoldoutType.Repository })
+    const allRepositories = await this.repositoriesStore.getAll()
+    if (allRepositories.length === 0) {
+      this._closeFoldout(FoldoutType.Repository)
+    } else {
+      this._showFoldout({ type: FoldoutType.Repository })
+    }
   }

   public async _cloneAgain(url: string, path: string): Promise<void> {
```

**Comment by agisilaos** [comment]
Just opened a PR about this one! @shiftkey  🎧 #4269
