### ISSUE TITLE
git submodules: 'Never fetched' status and weird GUI "jumping about" effect

### ISSUE THREAD

**Issue by mikey-gray** [desktop/desktop#15008]
### The problem

Firstly, love GitHub Desktop! Amazing work, and has become a tool I depend on 👍 

Two oddities when working in git submodules that I believe are related:

- The submodule repo status never changes beyond 'Never fetched' 
- When Github Desktop does a background fetch/refresh the GUI jumps about (see the video, it looks like it hops to the history and back)

The second issue is far more disruptive, as it happens when writing commit messages and moves the focus away from the summary/description fields. Very jarring!

### Release version

3.0.5 (arm64)

### Operating system

macOS 12.4

### Steps to reproduce the behavior

1. Open a repo that uses submodules
2. Start working in one of the submodules
3. Notice that the status remains "never fetched"
4. Wait a bit for a fetch/refresh
5. See the GUI jump about! (see video)

### Log files

[2022-07-20.desktop.production.log](https://github.com/desktop/desktop/files/9157226/2022-07-20.desktop.production.log)
[2022-07-21.desktop.production.log](https://github.com/desktop/desktop/files/9157227/2022-07-21.desktop.production.log)

### Screenshots

I had to leave this running and then trim it to capture the GUI problem:

https://user-images.githubusercontent.com/91396169/180160188-8773fc4b-09ff-42fb-b0d3-2be1ca94852d.mov

**Comment by sergiou87** [comment]
Hi @mikey-gray!

Thank you for your kind words 🙇‍♂️ 🙇‍♂️ 🙇‍♂️ 🙇‍♂️ 

We're looking into improving the experience with submodules as we speak, but I can't tell if what I see in your video is the parent repo or one of its submodules. Also, the beta has had some submodule-specific improvements enabled for a few years (mainly, updating submodules when cloning or switching branches, for example). You can download the latest beta from https://desktop.github.com/beta

**Comment by mikey-gray** [comment]
Thanks @sergiou87!

The beta version has certainly fixed the odd jumping about thing that was happening, so thanks! The "Never fetched" status remains, but the most disruptive problem is solved 👍
