### ISSUE TITLE
##[error]ENOENT: no such file or directory, stat '/home/vsts/work/1/s/$(ScriptDir)/prerequisites.ps1'

### ISSUE THREAD

**Issue by ctahok** [desktop/desktop#15002]
### The problem

Besides I tried to specify folder location for /pwsh in AzGovViz/AzGovViz.variables.yml file as

```
  # If you integrate AzGovViz into an existing repository you may need to adjust the script directory
  - name: ./AzGovViz/pwsh
```
or
`  - name: /pwsh`
or
`- name: /AzGovViz/pwsh`
or
`- name: AzGovViz/pwsh`

I keep getting either 

**ENOENT: no such file or directory, stat '/home/vsts/work/1/s/pwsh/prerequisites.ps1'**
or
**ENOENT: no such file or directory, stat '/home/vsts/work/1/s/$(ScriptDir)/prerequisites.ps1'**
error. 

### Release version

v6_major_20220521_1

### Operating system

Azure DevOps

### Steps to reproduce the behavior

1. Clone the code
2. Configure permissions
3. Create a pipeline from _AzGovViz/.azuredevops/pipelines/AzGovViz.pipeline.yml_
4. Configure _/pwsh_ folder location in _AzGovViz/AzGovViz.variables.yml_ file
5. Run the pipeline

### Screenshots

<img width="629" alt="D4NJmXgYxz" src="https://user-images.githubusercontent.com/17162642/180010198-b0598aa9-cfe1-4be2-8433-eb13c3e36a95.png">

**Comment by tsvetilian-ty** [comment]
@ctahok in what context is your issue related to GitHub Desktop?

**Comment by sergiou87** [comment]
Hi there @ctahok ! 👋 

I'm sorry but looking at the description of your issue I don't see how it is related to GitHub Desktop.

EDIT: you beat me @tsvetilian-ty 🥇

**Comment by ctahok** [comment]
Sorry, I meant to post it to another repo.
