### ISSUE TITLE
need a new build of win 10 im stuck in 10.0.19044 and my omen x2 s software and firmware is not compatible

### ISSUE THREAD

**Issue by tuckstarrydell** [desktop/desktop#15006]
### The feature request

i need new build up to date one that my omen software and firmware will work with

### Proposed solution

a windows download i dont even care if im wiped clean as long as i dont loose my gpu.

### Additional context

please help

**Comment by steveward** [comment]
@tuckstarrydell this issue tracker is for GitHub Desktop, it sounds like your problem is related to a different piece of software. If you're having issues with GitHub Desktop please let us know.
