### ISSUE TITLE
"Discard added/modified/removed lines" broken in recent builds

### ISSUE THREAD

**Issue by Sergio0694** [desktop/desktop#15003]
### The problem

Not entirely sure when this started happening, but I noticed the "Discard added/modified/removed lines" option is currently broken. I can repro this repos from different folders and origins (eg. GitHub, or ADO linked with a personal access token).

Discarding a whole file seems to work, but doing so for a group of lines doesn't seem to work at all anymore.

### Release version

3.0.5 (x64)

### Operating system

W11 22000.795

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. Open a repo
3. Make any changes
4. Right click on a group of changes lines
5. Click "Discard ..."

### Log files

```
2022-07-20T15:28:34.942Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-07-20T15:28:35.741Z - info: [ui] [AppStore] loading 31 repositories from store
2022-07-20T15:28:35.744Z - info: [ui] [AppStore] found account: Sergio0694 (Sergio Pedri)
2022-07-20T15:28:35.820Z - info: [ui] [BranchPruner] Last prune took place 6 minutes ago - skipping
2022-07-20T15:28:35.920Z - info: [ui] launching: 3.0.5 (Windows 10.0.22000)
2022-07-20T15:28:35.922Z - info: [ui] execPath: 'C:\Users\sergiopedri\AppData\Local\GitHubDesktop\app-3.0.5\GitHubDesktop.exe'
2022-07-20T15:28:36.374Z - info: [ui] Subscribed 'Sergio0694' to Alive channel
2022-07-20T15:28:37.709Z - info: [ui] Stats reported.
```

Not really seeing anything in here. I tried to discard some changes 3 times, nothing was apparently logged for that.

### Screenshots

![github_desktop_issue](https://user-images.githubusercontent.com/10199417/180021805-49d241c2-4cb6-4d73-b02b-73c43eacd634.gif)

**Comment by steveward** [comment]
Thanks for the report @Sergio0694. I was unable to reproduce this issue when testing on both Windows and macOS, so I'm not sure what's happening here. Does discarding individual lines work?

**Comment by sergiou87** [comment]
@Sergio0694 do you have "Hide whitespace changes" enabled? If so, try disabling it. I think the "Discard lines…" menu option shouldn't be there when "Hide whitespace changes" is enabled. In the Split diff the context menu is not available at all, I think that's broken for the Unified diff 😞

**Comment by Sergio0694** [comment]
Oh wow, yeah that was it! I did have "Hide whitespace changes", and disabling it did in fact make it work again 😄
Would it be possible to get the "Discard changes" feature working when hiding whitespaces too?
They're both really great features and it'd be awesome not to have to give up on one of them at a time 🙂

**Comment by sergiou87** [comment]
I don't think so, because the information `git` needs to discard specific lines is in the "full diff" (without hiding whitespace changes). That's also why selecting individual lines for commits is disabled when that setting is enabled 😕

**Comment by Sergio0694** [comment]
Would there be any way to enable this when not showing whitespaces? The current workflow is quite frustrating:
- Click the settings wheel
- Uncheck the whitespace option
- Right click > Discard changes
- Click the settings wheel
- Check the whitespace option again

This every single time I need to undo some changes 🥲

Like, especially when the diff doesn't include any ignore whitespaces, wouldn't it be possible to just map that to the diff without ignoring whitespaces, so that you could still discard that even when ignoring whitespaces and it'd still work?
