### ISSUE TITLE
Unable to access

### ISSUE THREAD

**Issue by leonardo-collazo** [desktop/desktop#15014]
### The problem

I can't publish a new repository. Github Desktop shows me this message and I don't know why:

fatal: unable to access 'https://github.com/KidBourbon/Personal_Project.git/': Failed to connect to 127.0.0.1 port 1080 after 2030 ms: Connection refused

### Release version

Version 3.0.5 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. I created a new repository
2. Click on "Publish branch"

**Comment by sergiou87** [comment]
Hello @KidBourbon 👋 

That sounds like you have some kind of proxy configured (and not running?), is that possible?

**Comment by leonardo-collazo** [comment]
Hello Sergio Padrino. I solved the problem, thank you very much!

**Comment by sachalchandio** [comment]
how ?
