### ISSUE TITLE
GitHub Desktop won't launch

### ISSUE THREAD

**Issue by jacklaplante** [desktop/desktop#15012]
### The problem

Hello! I was using GitHub Desktop before but now it won't launch.

### Release version

can't open so not sure

### Operating system

Windows 10

### Steps to reproduce the behavior

1. I press windows key
2. type "Github Desktop" and hit Enter to launch

### Log files

I looked in `C:\Users\lapla\AppData\Roaming\GitHub Desktop\logs` and I see logs but none from when I try and launch it, only logs from the past. Here is the most recent log file
[2022-06-27.desktop.production.log](https://github.com/desktop/desktop/files/9162985/2022-06-27.desktop.production.log)

**Comment by sergiou87** [comment]
Hi @jacklaplante 👋 

Have you tried rebooting your PC and see if it helps? Maybe there is some process of GitHub Desktop still running and preventing a new instance to start 😖 

If that doesn't work, you can try deleting (or moving/renaming temporarily) the `C:\Users<YourUserName>\AppData\Roaming\GitHub Desktop` folder. This folder has all your GitHub Desktop settings and the list of repositories.

**Comment by jacklaplante** [comment]
neither of those things fixed it but reinstalling did
