### ISSUE TITLE
Pycharm not recognised 

### ISSUE THREAD

**Issue by jinyu2072** [desktop/desktop#15016]
### The problem

Pycharm is not recognised as external editor by GitHub Desktop.

However it was working before & I didn't change any settings on GitHub Desktop / PyCharm.. Any ideas why this happened suddenly?

### Release version

Version 3.0.5 (x64)

### Operating system

macOS Catalina Version 10.15.7

### Screenshots

![image](https://user-images.githubusercontent.com/105432905/180421619-f6f33395-10ab-4647-a213-25cd54ed69eb.png)

**Comment by tsvetilian-ty** [comment]
Hey @jinyu2072 👋 

How did you install your PyCharm? Is it standard installation or through JetBrains Toolbox?

**Comment by jinyu2072** [comment]
> Hey @jinyu2072 👋
> 
> How did you install your PyCharm? Is it standard installation or through JetBrains Toolbox?

Hello @tsvetilian-ty ,

Thanks for the reply. It was standard installation. 
Pycharm & git hub were working properly before.

**Comment by tsvetilian-ty** [comment]
@jinyu2072 thanks for the report! I can confirm that there is a change in JetBrains bundle identifiers (PyCharm CE identifier is `com.jetbrains.pycharm.ce`), which is why the IDE is not visible. 

I will mark it as a bug and will fix it as soon as possible
