### ISSUE TITLE
Code edit

### ISSUE THREAD

**Issue by aarabii** [desktop/desktop#15025]
### The feature request

An option to edit code inside the application.

### Proposed solution

As I'm going through its tutorial it asked me to go to its directory and make some changes and then come back here.
For what ill comes back here to commit?
I can do that in VS code itself or other IDE

Yeah, it makes merging branches and creating new branches easy but a code editor feature would be awesome.

**Comment by sergiou87** [comment]
Thank you for your suggestion but we think it's better if GitHub Desktop focuses on one thing, and there are much better tools for code editing. Sorry!

**Comment by aarabii** [comment]
ok @sergiou87 then what about issues section
