### ISSUE TITLE
Open on github desktop redirects to Download page when already downloaded and open

### ISSUE THREAD

**Issue by Phoenix1205555** [desktop/desktop#15026]
### The problem

Trying to get a file but couldn't since the browser couldn't detect the application.

### Release version

3.0.5

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Goto repository file
2. Open in github desktop

### Screenshots

![Screenshot 2022-07-24 115600](https://user-images.githubusercontent.com/47672935/180655689-359bc3db-215d-4501-9fdb-d783af19420e.png)

**Comment by tsvetilian-ty** [comment]
@Phoenix1205555 thanks for the report! 
What browser you're using? Also, could you try to paste `x-github-client://openRepo/https://github.com/desktop/desktop.git` into your browser to check if the protocol handler is working as expected?

**Comment by Phoenix1205555** [comment]
I was using brave web browser, That link works as expected. It's just the website that didn't detect the app and took me to the download page. Edit: it detects the program again I guess it was link that fixed it or it needed a update.

**Comment by steveward** [comment]
Glad to hear things are working for you now!

**Comment by wwsoapbox** [comment]
This problem is NOT FIXED.  IT still does the same thing in 2023.  Wehn you click on "Open with Git-Hub desktop" It takes you to the Desktop download page.  I have down loaded the GitHub desktop 4 times.  All I want to do is copy some code.  No development, no updates, just please just a simple way to copy a few files.  THis thing was made by and for professional programmers; please have mercy on mere mortals.  Thank you,

**Comment by mcluckster** [comment]
Quick workaround for anyone who the magnet link doesn't work for, and they find themselves here:
Inside of GitHub desktop, click File > Close Repository, then in the popup click URL and copy the URL of the repo you want to clone into the box.  Click clone, and it will add the repo.

**Comment by warrenwallis** [comment]
Hey yall,

I noticed that I wasn't signed in when I encountered this issue. Once I signed in, the problem of asking me to download GitHub desktop went away and it would open the app as expected.

I hope that helps!

**Comment by dhhepting** [comment]
That did help me. Once I signed in, Github Desktop opened the selected repository for me instead of asking me to download the app again. However, would it not be better to redirect to a URL that  (also) suggests signing in to your account?

**Comment by Andrews3002** [comment]
The problem for me was that I was signed into github desktop with a different account than the account I was signed into for github web. Basically for the problem to be solved I needed to ensure that I was using the same github account on both github desktop and github.com.
