### ISSUE TITLE
On window focus, the UI flicks between History and Changes

### ISSUE THREAD

**Issue by ivanmaeder** [desktop/desktop#15022]
### The problem

Sometimes when I switch back to GitHub Desktop from another window (maybe only from another virtual desktop?), the UI shows the "History" tab for a split second before going back to the "Changes" tab which is what was selected.

I think I've seen it do it the other way around too: flick to "Changes" and then back to the selected "History" tab.

I've attached a video—I'm definitely not pressing CTRL-TAB to do that!

### Release version

Version 3.0.5 (x64)

### Operating system

macOS Catalina 10.15.7

### Steps to reproduce the behavior

1. Open GitHub Desktop to a repo and the "Changes" tab
2. Maybe make some file changes (not sure if this is required)
3. Switch away from GitHub Desktop and do something else for a while
4. Go back to GitHub Desktop

### Log files

[2022-07-23.desktop.production.log](https://github.com/desktop/desktop/files/9173292/2022-07-23.desktop.production.log)

### Screenshots

https://user-images.githubusercontent.com/1976478/180595352-e548c591-e8b8-4884-8144-4ede0ea1f2d1.mov

### Additional context

I usually update within a few days of a new update becoming available and this has been happening for a few weeks, maybe a couple of months. Unlikely more.

The computer is a MacBook Air (13-inch, Mid 2012) with 8GB RAM and plenty of free space on the drive.

I use multiple desktops with the dock and menu bar hidden by default.

**Comment by tsvetilian-ty** [comment]
@ivanmaeder thanks for the report! A similar issue was reported in https://github.com/desktop/desktop/issues/15008, and it looks like the latest beta fixes it. Could you try out the newest beta from https://desktop.github.com/beta?

**Comment by ivanmaeder** [comment]
Hi @tsvetilian-ty, thanks for that. I looked but didn't see the other issue.

I downloaded the beta **Version 3.0.6-beta1 (x64)** and I'm still seeing the flicker.

**Comment by tsvetilian-ty** [comment]
I'm not able to reproduce the issue 😞 

I will label it as `investigation-needed`.

**Comment by ivanmaeder** [comment]
Ok, let me know if I can help with anything.

**Comment by niik** [comment]
Hey @ivanmaeder, I just tried reproducing this but wasn't able to. I recognize that it's been quite some time since your report and we've done a lot of work related to accessibility which could have affected this, are you still able to reproduce this?

**Comment by ivanmaeder** [comment]
Hi @niik, I haven’t noticed this in a long time so yes, please ignore. Thanks!
