### ISSUE TITLE
refs/remotes/origin/00Tree.html

### ISSUE THREAD

**Issue by kryton-me** [desktop/desktop#15024]
### The problem

For every repository on my system I get this error when attempting a fetch:

Bitbucket:
error: cannot lock ref 'refs/remotes/origin/00Tree.html': unable to resolve reference 'refs/remotes/origin/00Tree.html': reference broken
error: could not remove reference refs/remotes/origin/00Tree.html

GitHub:
remote: Enumerating objects: 71, done.        
remote: Counting objects: 100% (71/71), done.        
remote: Compressing objects: 100% (57/57), done.        
remote: Total 60 (delta 36), reused 27 (delta 3), pack-reused 0        
fatal: bad object refs/remotes/origin/00Tree.html

This only happens on my Mac, other systems with different clients can pull just fine. I'm not aware of this file existing on any repository I use. 

### Release version

3.0.5 (x64)

### Operating system

Mac OS Big Sur 11.6.8

### Steps to reproduce the behavior

Pull or fetch from a repository

### Log files

[2022-07-23.desktop.production.log](https://github.com/desktop/desktop/files/9174778/2022-07-23.desktop.production.log)

**Comment by sergiou87** [comment]
Hi @kryton-me ! 👋 

I think that's not a file but a branch maybe? I'm not entirely sure what's going on, can you delete your local copy of the repo and clone it again to see if it's solved like that?

**Comment by kryton-me** [comment]
I’m not sure it is a branch, as every repo I have checked out has done it at once. Most of them only I work on so have one branch “main”. Some of the repos I have checked out are libraries and I’ve never checked into them and they have the same problem.

**Comment by kryton-me** [comment]
Sorry hit the wrong button.

**Comment by sergiou87** [comment]
Yeah, I'm not sure how, but it looks like a branch in the logs, in many of your repositories:

```
From https://bitbucket.org/Wilkbourne/rmr
 - [deleted]         (none)     -> origin/00Tree.html
```

```
From https://github.com/kryton-me/kryton-me.github.io
 - [deleted]         (none)     -> origin/00Tree.html
```

```
From https://bitbucket.org/Wilkbourne/bike
 - [deleted]         (none)     -> origin/00Tree.html
```

But no idea where it's coming from 🤯

**Comment by kryton-me** [comment]
I appear to be having this issue with this Repository that I don't have write access to:

[https://gitlab.com/kicad/libraries/kicad-footprints](https://gitlab.com/kicad/libraries/kicad-footprints)

This is in the public domain so you should be able to double check this (I'll concede to knowing more about Capacitors & IC's than git). I've searched the branch list and can't see a 00Tree.

I also have most of these repositories (although not KiCAD) on my iPad / iPhone using "Working Copy" and all is well.

**Comment by sergiou87** [comment]
Is it possible that you have some kind of global git config that could affect this?

**Comment by iamyeizi** [comment]
sorry, here is some information about this file `00Tree.html`, it is an autogenerated file with the [tree](https://linux.die.net/man/1/tree) command while used with the `-R` option.
