### ISSUE TITLE
notify users when fetch is available

### ISSUE THREAD

**Issue by TechnicallyGio** [desktop/desktop#15029]
### The feature request

Notify users when fetch origin has changes available. 

### Proposed solution

Will allow users to pull the changes in the moment rather than going into the desktop app to make a change.

**Comment by steveward** [comment]
Thanks for the issue @TechnicallyGio. A notification every time a change is available to pull would be rather noisy, and would likely interfere with the more valuable notifications that can be surfaced (like pull request feedback). We'll definitely be continuing to think about how we can continue to build on notifications in the future, but at this time we don't have any plans for this specific feature so I am going to close this out.
