### ISSUE TITLE
Webstorm is not being detected as an external editor when it's installed using JetBrains Toolbox

### ISSUE THREAD

**Issue by elbkr** [desktop/desktop#15021]
### The problem

Webstorm IDE is detected on Windows as an external editor when it's installed [individually](https://www.jetbrains.com/webstorm/download/#section=windows), but it's not detected when it's installed using [JetBrains toolbox](https://www.jetbrains.com/toolbox-app/).

### Release version

Version 3.0.5 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Download and install JetBrains toolbox, and then install the Webstorm IDE using the toolbox
2. Open GitHub desktop options
3. Go to the `Integrations` tab
4. Check the external editor's drop-down and you'll see that WebStorm isn't there.

### Expected Behavior
WebStorm should show appear in the drop-down list.

### Actual Behavior
WebStorm doesn't show up.

**Comment by tsvetilian-ty** [comment]
@elbkr thanks for reaching out! That is a known issue, and we track it in https://github.com/desktop/desktop/issues/12912

I will close this issue in favor of https://github.com/desktop/desktop/issues/12912
