### ISSUE TITLE
"Unknown Error"

### ISSUE THREAD

**Issue by purplelunamine** [desktop/desktop#15034]
### The problem

Every time I open GitHub Desktop, I get a pop-up message with the title "Error" and the description "Unknown Error". When I try to clone/create any repositories, I get the exact same pop-up. There's nothing else, no error code, no information, it just says "Unknown Error".

### Release version

3.0.5 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. Try to create or clone any repository

### Log files

[2022-07-26.desktop.production.log](https://github.com/desktop/desktop/files/9186251/2022-07-26.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/77215030/180915470-974b91f8-8d1a-4a7d-82bf-a47f95ad6dcd.png)

**Comment by sergiou87** [comment]
There seems to be something wrong with your git binaries, not sure if due to an antivirus or what (see https://github.com/desktop/desktop/issues/11610#issuecomment-780633964 for more info). If that's not possible in your case, could you try uninstalling and then reinstalling it again? 🤞

**Comment by purplelunamine** [comment]
My computer got a virus and I had to reinstall Windows, so it's no longer an issue. Thank you anyways!
