### ISSUE TITLE
Managing repos in remote servers?

### ISSUE THREAD

**Issue by xz-liu** [desktop/desktop#15035]
### The feature request

Nowadays, people usually use remote servers instead of their PCs to run programs. However, it's tedious to text commands on servers since most of them don't have a GUI. 
Rather than copying a URL to manually clone a repo, it is far more convenient to just click a button on one Github repo page.
Thus, I wonder whether it is possible to add a server management function via SSH or something else that I can also just click a button then the repo is cloned on my remote machine. 

### Proposed solution

Maybe add a list of server configuration, then when each time a user create/clone a repo, they can choose from the local and remote server paths.

**Comment by steveward** [comment]
Thanks for the issue @joker-xii, this has been previously requested in https://github.com/desktop/desktop/issues/11667 so I'm going to close this out in favor of that issue. Please follow along there for updates.
