### ISSUE TITLE
GitHub Desktop "Failed ___" Errors

### ISSUE THREAD

**Issue by VladKapitantchouk-IBI** [desktop/desktop#15031]
### The problem

Getting errors for every action...likely after an automatic update.
Trying to sync a repo - "Failed to execute: installGlobalLFSFilter: UNKNOWN"
Cloning a repo from the internet - "Failed to execute clone: UNKNOWN"
Creating a new repo on my pc - "Failed to execute getConfigValueInPath: UNKNOWN"

I've tried to log in and out, in case of an expired token.
I've tried to remove the repo folders from Github Desktop.

It's not that easy for me to re-install software as I am working from a work computer, and don't want to have to have IT fix this everytime it happens - is there any other solution? This seems to have been happening over the last few years based on forums.

Thanks in advance.

### Release version

3.0.4 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Various steps - see description above. Nothing repo-related works, returning vague error messages.

### Screenshots

![image](https://user-images.githubusercontent.com/107556377/180814114-988d290b-5b78-40bc-8329-4ee5afa64960.png)
![image](https://user-images.githubusercontent.com/107556377/180814403-0768ae84-af13-43f7-9bf2-ce74c88816e7.png)

**Comment by tsvetilian-ty** [comment]
Hey @VladKapitantchouk-IBI thanks for reaching out! Could you add GitHub Desktop as excluded software if you have antivirus or firewall software? 

There is a discussion in https://github.com/desktop/desktop/issues/11610 for the same issue, and the cause for the problem was firewall rules.

**Comment by VladKapitantchouk-IBI** [comment]
> Hey @VladKapitantchouk-IBI thanks for reaching out! Could you add GitHub Desktop as excluded software if you have antivirus or firewall software?
> 
> There is a discussion in #11610 for the same issue, and the cause for the problem was firewall rules.

Hi @tsvetilian-ty,

Thanks for getting back. I'll have someone in our IT department have a look, and will get back, thanks!

**Comment by VladKapitantchouk-IBI** [comment]
Hi all, this turned out to be a user permission issue. Reinstalling didn't help, but running it under an admin account with the appropriate permissions did. 

Perhaps one day Github can implement error messages that will notify the user of the exact issue and cause in such situations for other users.

Thanks again for the quick response @tsvetilian-ty.
