### ISSUE TITLE
The remote disconnected. Check your Internet connection and try again.

### ISSUE THREAD

**Issue by jeremywarner** [desktop/desktop#15032]
### The problem

I am trying to push an update with a large number of files, and over 1 GB of size. The desktop app compresses all the files, and then says that it writes all the files to the remote server, and then when it gets to the last file, I get this error message:

The remote disconnected. Check your Internet connection and try again.

There is nothing wrong with the internet connection, I have tried this over and over again from reliable internet connections. Please help.

### Release version

3.0.5 (x64)

### Operating system

macOS Monterey version 12.4

### Steps to reproduce the behavior

1. Press the "push origin" button
2. Wait for the error

### Log files

[2022-07-25.desktop.production.log](https://github.com/desktop/desktop/files/9184129/2022-07-25.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the issue @jeremywarner. It looks like this is the cause:

```
remote: fatal: pack exceeds maximum allowed size (2.00 GiB)        
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
send-pack: unexpected disconnect while reading sideband packet
```

One solution would be to try and use the command line to push a subset of commits, using the command `git push origin commit-SHA:branch`.

So if you have three commits A (4d3bf9) - B (e55b5f) - C (c109e0) and wanted to push A and B to your `dev` branch you would run this command:

`git push origin e55b5f:dev`

You can also try using something like [git-sizer](https://github.com/github/git-sizer) to try and figure out what is causing the issues with your repository size. 

I hope that helps!
