### ISSUE TITLE
Changes filter shotcut

### ISSUE THREAD

**Issue by passariello** [desktop/desktop#15036]
### The feature request

Hello, will be great to have a select menu (or some similar) to filter by type. 
I need to see only removed file... updated or added.

Many thanks for your hard work :)

Dario

![Screenshot 2022-07-26 105721](https://user-images.githubusercontent.com/17809213/181065958-c32d49f0-e28c-48ed-833a-891f8032e1ce.png)

### Proposed solution

Have a select menu or radio button to show/hide toggle by type at top UI

### Additional context

I hope that it's a good idea for you... it's really annoying thing!

**Comment by tidy-dev** [comment]
Another contribution to the ideas in https://github.com/desktop/desktop/issues/6407. Going to close and add this there for further consideration under types of filter of the changes list.
