### ISSUE TITLE
Github Desktop: The remote disconnected systematically at the end of Publish.

### ISSUE THREAD

**Issue by NicolasChoukroun** [desktop/desktop#15038]
### The problem

Using Github Desktop, I try to Publish but at the end of it, I get an error and I cannot publish.
It is systematic. I have paid for the bandwidth and the authorized size is higher than the size of the project. I am using less than 50% of my authorized storage and bandwidth.

It seems that at every try, I am using more bandwidth, and this is not deduced from my account because of the error. 

My internet is perfectly fine and is not the problem, I have Fiber 1TB/500Mbs and no interruption, so the time out or error is on Github end.

Here is the log, I don't know what to do at this point. 

error: RPC failed; curl 55 Send failure: Connection was aborted
send-pack: unexpected disconnect while reading sideband packet
Writing objects:  99% (15781/15905), 2.00 GiB | 17.57 MiB/s
Writing objects:  99% (15784/15905), 2.03 GiB | 19.11 MiB/s
Writing objects:  99% (15788/15905), 2.06 GiB | 21.66 MiB/s
Writing objects: 100% (15905/15905), 2.06 GiB | 21.66 MiB/s
Writing objects: 100% (15905/15905), 2.10 GiB | 14.64 MiB/s, done.
Total 15905 (delta 33), reused 15121 (delta 3), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

(The error was parsed as 4: The remote disconnected. Check your Internet connection and try again.)
2022-07-26T23:57:33.128Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.140s)

### Release version

3.0.5 x64

### Operating system

Windows 10

### Steps to reproduce the behavior

It is specific to my repository. i have 1 file that is large (600Mb) the total repo is 18GB it is an Unreal 5 project.

### Log files

Writing objects:  98% (15632/15905), 921.73 MiB | 11.24 MiB/s
Writing objects:  98% (15632/15905), 935.01 MiB | 11.72 MiB/s
Writing objects:  98% (15633/15905), 939.26 MiB | 11.74 MiB/s
Writing objects:  98% (15633/15905), 958.72 MiB | 11.91 MiB/s
Writing objects:  98% (15634/15905), 968.88 MiB | 11.88 MiB/s
Writing objects:  98% (15635/15905), 978.20 MiB | 13.91 MiB/s
Writing objects:  98% (15636/15905), 993.88 MiB | 12.43 MiB/s
Writing objects:  98% (15636/15905), 999.80 MiB | 10.62 MiB/s
Writing objects:  98% (15636/15905), 1.00 GiB | 12.97 MiB/s  
Writing objects:  98% (15636/15905), 1.01 GiB | 13.61 MiB/s
Writing objects:  98% (15637/15905), 1.02 GiB | 12.70 MiB/s
Writing objects:  98% (15637/15905), 1.04 GiB | 15.00 MiB/s
Writing objects:  98% (15638/15905), 1.05 GiB | 15.06 MiB/s
Writing objects:  98% (15638/15905), 1.08 GiB | 16.36 MiB/s
Writing objects:  98% (15639/15905), 1.09 GiB | 14.53 MiB/s
Writing objects:  98% (15639/15905), 1.11 GiB | 16.07 MiB/s
Writing objects:  98% (15639/15905), 1.13 GiB | 16.69 MiB/s
Writing objects:  98% (15640/15905), 1.13 GiB | 14.71 MiB/s
Writing objects:  98% (15640/15905), 1.15 GiB | 17.57 MiB/s
Writing objects:  98% (15641/15905), 1.16 GiB | 15.85 MiB/s
Writing objects:  98% (15642/15905), 1.19 GiB | 16.84 MiB/s
Writing objects:  98% (15642/15905), 1.20 GiB | 16.29 MiB/s
Writing objects:  98% (15643/15905), 1.23 GiB | 18.73 MiB/s
Writing objects:  98% (15644/15905), 1.23 GiB | 16.89 MiB/s
Writing objects:  98% (15646/15905), 1.25 GiB | 16.35 MiB/s
Writing objects:  98% (15655/15905), 1.27 GiB | 18.60 MiB/s
Writing objects:  98% (15663/15905), 1.28 GiB | 16.33 MiB/s
Writing objects:  98% (15664/15905), 1.31 GiB | 17.17 MiB/s
Writing objects:  98% (15665/15905), 1.31 GiB | 16.09 MiB/s
Writing objects:  98% (15667/15905), 1.33 GiB | 17.79 MiB/s
Writing objects:  98% (15668/15905), 1.36 GiB | 17.24 MiB/s
Writing objects:  98% (15671/15905), 1.37 GiB | 15.98 MiB/s
Writing objects:  98% (15672/15905), 1.38 GiB | 18.19 MiB/s
Writing objects:  98% (15672/15905), 1.41 GiB | 18.92 MiB/s
Writing objects:  98% (15679/15905), 1.42 GiB | 17.50 MiB/s
Writing objects:  98% (15683/15905), 1.43 GiB | 18.41 MiB/s
Writing objects:  98% (15685/15905), 1.47 GiB | 18.99 MiB/s
Writing objects:  98% (15686/15905), 1.47 GiB | 16.75 MiB/s
Writing objects:  98% (15690/15905), 1.48 GiB | 18.41 MiB/s
Writing objects:  98% (15696/15905), 1.50 GiB | 17.54 MiB/s
Writing objects:  98% (15703/15905), 1.52 GiB | 16.34 MiB/s
Writing objects:  98% (15705/15905), 1.54 GiB | 18.16 MiB/s
Writing objects:  98% (15707/15905), 1.56 GiB | 16.97 MiB/s
Writing objects:  98% (15707/15905), 1.58 GiB | 17.26 MiB/s
Writing objects:  98% (15710/15905), 1.59 GiB | 16.82 MiB/s
Writing objects:  98% (15716/15905), 1.61 GiB | 18.50 MiB/s
Writing objects:  98% (15718/15905), 1.62 GiB | 16.91 MiB/s
Writing objects:  98% (15722/15905), 1.64 GiB | 17.26 MiB/s
Writing objects:  98% (15736/15905), 1.66 GiB | 17.51 MiB/s
Writing objects:  99% (15746/15905), 1.67 GiB | 17.64 MiB/s
Writing objects:  99% (15751/15905), 1.69 GiB | 17.94 MiB/s
Writing objects:  99% (15753/15905), 1.70 GiB | 18.17 MiB/s
Writing objects:  99% (15756/15905), 1.71 GiB | 18.52 MiB/s
Writing objects:  99% (15758/15905), 1.73 GiB | 16.72 MiB/s
Writing objects:  99% (15760/15905), 1.75 GiB | 17.32 MiB/s
Writing objects:  99% (15760/15905), 1.77 GiB | 17.41 MiB/s
Writing objects:  99% (15761/15905), 1.78 GiB | 16.34 MiB/s
Writing objects:  99% (15762/15905), 1.80 GiB | 17.85 MiB/s
Writing objects:  99% (15766/15905), 1.82 GiB | 17.36 MiB/s
Writing objects:  99% (15767/15905), 1.84 GiB | 17.70 MiB/s
Writing objects:  99% (15769/15905), 1.85 GiB | 17.21 MiB/s
Writing objects:  99% (15769/15905), 1.87 GiB | 18.86 MiB/s
Writing objects:  99% (15771/15905), 1.89 GiB | 17.63 MiB/s
Writing objects:  99% (15774/15905), 1.90 GiB | 17.36 MiB/s
Writing objects:  99% (15774/15905), 1.93 GiB | 17.13 MiB/s
Writing objects:  99% (15775/15905), 1.93 GiB | 17.17 MiB/s
Writing objects:  99% (15777/15905), 1.95 GiB | 17.16 MiB/s
Writing objects:  99% (15779/15905), 1.97 GiB | 16.79 MiB/s
Writing objects:  99% (15779/15905), 2.00 GiB | 17.24 MiB/s
error: RPC failed; curl 55 Send failure: Connection was aborted
send-pack: unexpected disconnect while reading sideband packet
Writing objects:  99% (15781/15905), 2.00 GiB | 17.57 MiB/s
Writing objects:  99% (15784/15905), 2.03 GiB | 19.11 MiB/s
Writing objects:  99% (15788/15905), 2.06 GiB | 21.66 MiB/s
Writing objects: 100% (15905/15905), 2.06 GiB | 21.66 MiB/s
Writing objects: 100% (15905/15905), 2.10 GiB | 14.64 MiB/s, done.
Total 15905 (delta 33), reused 15121 (delta 3), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

(The error was parsed as 4: The remote disconnected. Check your Internet connection and try again.)
2022-07-26T23:57:33.128Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.140s)

**Comment by NicolasChoukroun** [comment]
Here is a video showing what is happening.

https://user-images.githubusercontent.com/40539492/181134188-ba801676-0cea-4ee3-a79d-d6aa9ce3bb01.mp4

**Comment by steveward** [comment]
Thanks for the issue @NicolasChoukroun. Just to confirm -- have you set the large files to be tracked by Git LFS?
