### ISSUE TITLE
Consider re-mapping Command+Delete

### ISSUE THREAD

**Issue by jeffdaley** [desktop/desktop#15033]
### The feature request

Several times, I've keyed `command+delete` and accidentally run the "Delete..." command when I've intended to "Remove..." a selected file.

![CleanShot 2022-07-25 at 16 21 20](https://user-images.githubusercontent.com/754957/180867609-b223f683-b4be-4373-9443-dbac876c726b.png)

Because the sidebar looks like the Finder, and because the selection highlight is so strong, it's hard to shake the muscle memory that `command+delete` should mean "delete the selected file."

I can't be the only one who's made this mistake.

Thanks for taking a look.

### Proposed solution

Re-map the Delete control to something less standard.

### Additional context

The warning message has never prevented me from making this mistake. I dismiss instinctively.

Also, in the meantime, I'm using System Preference to re-map "Delete..." away from `command+delete`. Unfortunately I'm unable to use `command+delete` for `Remove...` (but at least I'll stop making the mistake).

**Comment by steveward** [comment]
Thanks for the feedback @jeffdaley, I'm going to add this to https://github.com/desktop/desktop/issues/11924 where we are tracking this.
