### ISSUE TITLE
Problema ao clonar repositório

### ISSUE THREAD

**Issue by Mirand43** [desktop/desktop#15037]
### The problem

Eu estou a usar uma rede VPM compartilhado pelo celular, e tive de configurar o endereço proxy no mcomputador, e desta feita estou com um projecto que precisso clonar o repositorio e pelo git aparece  a seguinte mensagem: fatal: unable to access 'https://github.com/Eh-ncy/ehpharma.git/': OpenSSL SSL_connect: Connection was reset in connection to github.com:443; porem pelo github desktop a mensagem é: fatal: unable to access 'https://github.com/Eh-ncy/ehpharma.git/': Unsupported proxy 'github.com', libcurl is built without the HTTPS-proxy support.

E desejo de ajuda para resolver, por favor!

### Release version

0.0.1

### Operating system

Windows 11

### Steps to reproduce the behavior

1.vou para o git;
2.Acesso ao git;
3.Digito o comando git clone;

### Log files

![Uploading Captura de Tela (58).png…]()

### Screenshots

![Uploading Captura![Uploading Captura de Tela (58).png…]()

### Additional context

![Uploading Captura de Tela (59).png…]()

**Comment by steveward** [comment]
Thanks for the issue @Mirand43. Can you share how you configured your proxy? The output of this command should give some more information about your config:

`git config --list --show-origin`

**Comment by Mirand43** [comment]
E como faço para configurar o proxy para eu estar a usar uma VPN e poder clonar o repositório!? @mordomo

**Comment by steveward** [comment]
@Mirand43 the `Unsupported proxy 'github.com` message in the error makes me think your proxy is configured correctly. If you view your `.gitconfig` you should see the proxy setting which should be pointing to the URL of your proxy server.

Thanks for writing in.

We don't officially support running the application behind a proxy for this release, but if your proxy requires credentials there are some steps you can take to configure it:

This is the specific command to configure a proxy:

git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`

Replace `proxyuser` with your proxy username and `proxypwd` with your proxy password. Also, `proxy.server.com:8080` needs to point to the URL of your proxy server.

Let me know if that helps.
