### ISSUE TITLE
Allow user config the behavior for 'Show in Finder / Explorer'

### ISSUE THREAD

**Issue by hezean** [desktop/desktop#15043]
### The feature request

Currently when I click `Show in Finder`, the repo folder itself will be opened, but consider a scenario that, if I prefer open the project in IDE by dragging this folder to it, thus I need to step a level back every time, that's quite confusing.

I understand that a lot of user may love to access files in the repo by clicking this button, but why not let user decide its behavior?

### Proposed solution

Add an item in the `Advanced` settings to let user choose whether open the repo folder or its parent folder by default.

**Comment by steveward** [comment]
Thanks for the feedback @HeZean. This isn't likely something that we will change in the future as we try to minimize the amount of configuration settings that we add to GitHub Desktop. Something you may be interested in is a 'per-repository' option for opening an IDE/text editor, which is being tracked in https://github.com/desktop/desktop/issues/12195. That would allow you to configure a specific IDE for a repository. This isn't on our radar at this time, but it may be something we consider in the future.
