### ISSUE TITLE
cant see my invites both in my mail and notifications

### ISSUE THREAD

**Issue by Ebunoluwaoyetunji** [desktop/desktop#15046]
### The problem

hi,i was sent an invite to join a project but i didnt receive it in my mail and it is also not in my nootification.

### Release version

version 2.9.15

### Operating system

window 8

**Comment by steveward** [comment]
@Ebunoluwaoyetunji this issue tracker is for GitHub Desktop, it sounds like you may have been looking for another project hosted on GitHub. Let us know if you are having any issues with GitHub Desktop.

**Comment by Ebunoluwaoyetunji** [comment]
Hi Steve
Yes you are right.I have been looking for a project but unfortunately it’s
saying no users found
And please what can I do to get access to the invites that was sent to me
Thank you
