### ISSUE TITLE
JetBrains IDE's not being seen as External Editors when installed using JetBrains Toolbox

### ISSUE THREAD

**Issue by Ghrafkly** [desktop/desktop#15048]
### The problem

I had IntelliJ Ultimate installed for a while and was able to use it as an external editor for GitHub for Desktop just fine. As my projects grew, I started using other JetBrains IDE's, leading to me using JetBrains Toolbox so I could easily manage all the IDE installs.

After uninstalling IntelliJ Ultimate and other JetBrains IDE's and reinstalling them using toolbox, they disappeared as an External Editor option

### Release version

Version 3.0.5 (x64)

### Operating system

Windows 10 Home 21H2

### Steps to reproduce the behavior

1. Install a JetBrains IDE using Jetbrains Toolbox (ensure that it is an IDE supported by GitHub for Desktop)
2. Navigate to Integrations and click the External Editor, the IDE should not appear (other IDE's that have been previously installed locally, not via Toolbox will be unaffected)

### Screenshots

I have IntelliJ Ultimate open, but it is not present as an External Editor

![image](https://user-images.githubusercontent.com/69286273/181702737-8174504d-466d-43ec-923e-63eedaafbb19.png)

**Comment by tsvetilian-ty** [comment]
Hey @Ghrafkly currently, GitHub Desktop doesn't support JetBrains IDEs installed through JetBrain Toolbox. You can follow the topic at https://github.com/desktop/desktop/issues/12912

**Comment by shafiq9018** [comment]
In 2024 it does support it. However I have the same problem now. Please help.
