### ISSUE TITLE
There's no any option to look repository files in GitHub Desktop version

### ISSUE THREAD

**Issue by mmd18cury** [desktop/desktop#15041]
### The feature request

It seems to be there, but when you try to find any file in that app, there's no one, unless you look into history -> creation.
It seems very strange to me. I thought files should be there and i will be able to see them.

### Proposed solution

Add this option pls. And for example add a simple code editor into your desktop version.

**Comment by steveward** [comment]
Thanks for the issue @redmms. GitHub Desktop is not intended to be a file browser -- that's why we make it easy to launch into your favorite text editor or file manager. I'm going to close this out as it isn't something we're planning to support at this time.
