### ISSUE TITLE
Installation problem on windows 7

### ISSUE THREAD

**Issue by NagaSatyaGeeth** [desktop/desktop#15050]
### The problem

I have installed Github Desktop application from the official website but it isn't installing and showing the following error.

![WhatsApp Image 2022-07-29 at 4 04 48 PM](https://user-images.githubusercontent.com/67518197/181743511-ecc3c3fa-3e5e-49b6-8f29-6bc31e3cafc3.jpeg)

### Release version

Latest on

### Operating system

Windows 7

### Steps to reproduce the behavior

1. Download Github desktop application.
2. Click on the downloaded package to install it.
3. Install normally or as administrator 
4. If it as administrator click on yes.
5. The error from the screenshot pops up

### Log files

[SquirrelSetup.log](https://github.com/desktop/desktop/files/9219298/SquirrelSetup.log)

**Comment by steveward** [comment]
@Artistole Do you have the latest operating system updates on this machine? Windows 7 is no longer officially supported, but it should work unless there is a breaking change we are unaware of. You need to make sure you have [this update installed](https://support.microsoft.com/en-us/topic/microsoft-security-advisory-insecure-library-loading-could-allow-remote-code-execution-486ea436-2d47-27e5-6cb9-26ab7230c704) as well.
