### ISSUE TITLE
Failed to execute setConfigValueInPath: UNKNOWN

### ISSUE THREAD

**Issue by Rapha-L** [desktop/desktop#15058]
### The problem

I can't load any local git repository on git Desktop: I get the following error message: "Failed to execute setConfigValueInPath: UNKNOWN". The message "Refreshing repository - hang on" is running continuously without anything happening. 

### Release version

Version 3.0.5 (x64)

### Operating system

Windows 10 Entreprise

### Steps to reproduce the behavior

1) Open git hub desktop
2) Choose a repository (any of them)
3) no changes are displayed (although changes have been made)
4) Go to 'History'
5) see error: Failed to execute setConfigValueInPath: UNKNOWN

### Log files

[2022-08-01.desktop.production.log](https://github.com/desktop/desktop/files/9231983/2022-08-01.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/34375570/182100331-f1792190-fe74-44ed-a6e9-b2e925162884.png)

**Comment by steveward** [comment]
Thanks for the report @Rapha-L. Did this error possibly start occurring after a recent update to GitHub Desktop? If so I'd recommend trying a fresh install to see if that helps.

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `%AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that helps at all.
