### ISSUE TITLE
Full screen mode spills into multiple monitors

### ISSUE THREAD

**Issue by lfricken** [desktop/desktop#15056]
### The problem

When GitHub Desktop is put in fullscreen mode, it spills from one monitor into adjacent monitors (left and right) by a few pixels.

### Release version

3.0.5 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Have multiple monitors.
2. Tell GitHub Desktop to "Maximize" in one of them.
3. Notice a little white line appear in any adjacent monitors.

### Log files
None

### Screenshots

![image](https://user-images.githubusercontent.com/6675120/182056418-329803ca-a6c5-489a-a3d5-f6a29efa592d.png)

### Additional context

It doesn't happen if you just align it to the side. It only happens with the "Maximize" button.
It doesn't happen with other programs/windows.
My graphics driver (970 GTX) is up to date.

**Comment by tsvetilian-ty** [comment]
@lfricken thanks for reaching out! This issue is related to the version of Electron used in GitHub Desktop. The problem should be fixed in the [beta version](https://desktop.github.com/beta/) and soon in production🥳
