### ISSUE TITLE
add option to show in shell on current repo page

### ISSUE THREAD

**Issue by feinbd** [desktop/desktop#15051]
### The feature request

I have to often open my code in git bash.  i have selected it thru my  options as my shell and can do it via the repository menu, but...

### Proposed solution

On the main page where it shows if your repo has changes and you can push or create PR, there's options to view it in github, view in explorer, view in editor (vs code in my case), it would be nice to also have open in shell

**Comment by tsvetilian-ty** [comment]
Hey @feinbd thanks for the suggestion, but this feature is not in focus at the moment. You can read more on the topic at https://github.com/desktop/desktop/issues/6674
