### ISSUE TITLE
How da fuk do i publsih my work as a web on the internet i dont see github pages please for the love of god help

### ISSUE THREAD

**Issue by Pussidon** [desktop/desktop#15068]
### The problem

titlt

### Release version

tktkt

### Operating system

ktktkt

**Comment by steveward** [comment]
@Pussidon this issue tracker is for GitHub Desktop. You can find documentation for GitHub Pages here:

https://docs.github.com/en/pages

If continue to have issues you can reach out to [GitHub Support](https://support.github.com/).
