### ISSUE TITLE
Recursive donwloading of branch fails

### ISSUE THREAD

**Issue by DimitarBelemezov** [desktop/desktop#15064]
### The problem

When i try to download a branch that needs a recursive download it fails. Same thing done on the git bash works fine 

git clone --recurse-submodules ssh link

If needed more information it will be provided. I do not know what to attach else than the error log. 

LOG:
Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.

Probably the ssh is not synced correctly. I emphasize on the fact that with git bash everything works fine.  

### Release version

Version 3.0.5 (x64

### Operating system

Windows 

### Steps to reproduce the behavior

-

**Comment by steveward** [comment]
@DimitarBelemezov thanks for the issue. Could you upload the full log file? That should show what submodule is failing to clone.
