### ISSUE TITLE
TypeError: files.at is not a function | Setting up dev environment

### ISSUE THREAD

**Issue by maifeeulasad** [desktop/desktop#15063]
### The problem

I tried to start development in my Windows system, but I got this error.
```
PS D:\projects\desktop> yarn
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.2.1: The platform "win32" is incompatible with this module.
info "fsevents@2.2.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > parallel-webpack@2.3.0" has incorrect peer dependency "webpack@^1.12.9 || ^2.2.0 || ^3.x || ^4.x".
[5/5] Building fresh packages...
$ ts-node -P script/tsconfig.json script/post-install.ts

D:\projects\desktop\node_modules\once\once.js:25
    return f.value = fn.apply(this, arguments)
                        ^
TypeError: files.at is not a function
    at D:\projects\desktop\script\post-install.ts:26:57
    at f (D:\projects\desktop\node_modules\once\once.js:25:25)
    at Glob.<anonymous> (D:\projects\desktop\node_modules\glob\glob.js:151:7)
    at Glob.emit (events.js:400:28)
    at Glob.emit (domain.js:475:12)
    at Glob._finish (D:\projects\desktop\node_modules\glob\glob.js:197:8)
    at done (D:\projects\desktop\node_modules\glob\glob.js:182:14)
    at Glob._processReaddir2 (D:\projects\desktop\node_modules\glob\glob.js:434:12)
    at D:\projects\desktop\node_modules\glob\glob.js:371:17
    at RES (D:\projects\desktop\node_modules\inflight\inflight.js:31:16)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Release version

Development

### Operating system

Microsoft Windows 10 Home Single Language | 10.0.19044 | 19041.1.amd64fre.vb_release.191206-1406

### Steps to reproduce the behavior

```
git clone https://github.com/desktop/desktop.git
yarn
```
I didn't have to install any other tools, as I already had them installed.

### Screenshots

![image](https://user-images.githubusercontent.com/29339330/182288283-2111e185-1524-4f02-ad98-5341654862c2.png)

### Additional context

```
PS D:\projects\desktop> node -v
v14.18.0
PS D:\projects\desktop> nvm v
1.1.9
PS D:\projects\desktop> python --version
Python 3.9.7
```

I have been following this documentation: https://github.com/desktop/desktop/blob/development/docs/contributing/setup-windows.md

**Comment by tsvetilian-ty** [comment]
@maifeeulasad do you have the [Visual C++ Build Tools](https://github.com/desktop/desktop/blob/development/docs/contributing/setup-windows.md#visual-c-build-tools) installed?

**Comment by maifeeulasad** [comment]
Yes, Sir, they are installed in my system:

![image](https://user-images.githubusercontent.com/29339330/182343061-2efb46e1-4950-4c02-a08e-e88275f4bdd7.png)

---

![image](https://user-images.githubusercontent.com/29339330/182343302-b595080e-6f34-471c-8c5f-5d274bee5879.png)

**Comment by tsvetilian-ty** [comment]
@maifeeulasad if you scroll down in the "Modify" window, you should see "Desktop development with C++" is it installed?

EDIT: Also, make sure to delete `node_modules` before running `yarn`

**Comment by maifeeulasad** [comment]
I have installed _Desktop development with C++_ too and set those variables as required.

![image](https://user-images.githubusercontent.com/29339330/182372802-c72d96c7-01c0-430f-bdbb-cfda86199a86.png)
---
![image](https://user-images.githubusercontent.com/29339330/182373241-22a98e00-acc7-450e-b254-a500b4955495.png)

**Just not sure if it is due to the version of it or not. As I'm using 2022, and it says 2019 or 2017.**

**Comment by tsvetilian-ty** [comment]
@maifeeulasad I tried the environment setup on Windows 10 Home and had no issue with the installation 🤔 Could you try to clear the npm cache and delete the project's `node_modules`?

Note: I ran the `yarn` command before installing Visual Studio, and it still worked!

**Comment by maifeeulasad** [comment]
Thanks for your support @tsvetilian-ty . 

But nothing seems to work. I actually tried almost everything:

- Downgrading to VS 2019
- Downgrading to VS 2017

![image](https://user-images.githubusercontent.com/29339330/182551387-1a1c2a93-7d5c-43db-8886-e98be4b3d162.png)
😭

**Comment by niik** [comment]
Hey @maifeeulasad, thanks for reaching out! It looks like you are using an older version of Node.js than what's required.

> ```
> PS D:\projects\desktop> node -v
> v14.18.0
> ```

We're currently using 16.13.0 (see [.node-version](https://github.com/desktop/desktop/blob/development/.node-version)) which is necessary to support the new `.at` method for arrays. We've begun it ([Array.prototype.at](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at)) in a number of places already and we expect to use it more and more so we're not keen on reverting those changes.

Please install Node 16.13.0 (either globally or using a version manager, see https://github.com/desktop/desktop/blob/node-16-recommendation/docs/contributing/setup-windows.md#i-need-to-use-different-versions-of-nodejs-in-different-projects

I'm going to close this issue but let us know if upgrading Node didn't solve your issue and we'll continue troubleshooting.

xref https://github.com/desktop/desktop/pull/14907

**Comment by maifeeulasad** [comment]
Thanks, @niik, [it](https://github.com/desktop/desktop/issues/15063#issuecomment-1213239338) worked.

And really appreciate your help, @tsvetilian-ty.
