### ISSUE TITLE
GitHub Desktop won't appear on the start menu for Windows 10 after it is installed

### ISSUE THREAD

**Issue by xbonafi7x** [desktop/desktop#15062]
### The problem

GitHub Desktop won't appear on my Start Menu for Microsoft Windows 10 Home, after it's downloaded and installed.  

GitHub Desktop initially opens after I run the setup file (GitHubDesktopSetup-x64.exe), but after I close the program, I cannot find it on the start menu, and can't open it, unless I reinstall the program.

If I go to "Control Panel > Programs > Programs and Features" I can see that GitHub Desktop is installed (and it will let me Uninstall it).

If I go to "Apps & features" I can also see that GitHub Desktop is installed (and it will let me Uninstall it).

However, I cannot find GitHub Desktop on my start menu, and have no way of opening the program, once I close it, after the installation.  

GitHub Desktop only opens, right after the installation.

Another user experienced this same problem:

https://github.com/desktop/desktop/issues/3757

### Release version

Version 3.0.5 (x64)

### Operating system

Microsoft Windows 10 Home (Version 10.0.19044 Build 19044)

### Steps to reproduce the behavior

1. Download "GitHubDesktopSetup-x64.exe" from https://desktop.github.com/
2. Run GitHubDesktopSetup-x64.exe
3. After GitHub Desktop opens, close the program
4. GitHub Desktop does appear on the start menu, and cannot be reopened

### Additional context

Another user reported this problem perfectly:

"GitHub Desktop won't open on Windows 10 #3757"

https://github.com/desktop/desktop/issues/3757

**Comment by tsvetilian-ty** [comment]
@xbonafi7x thanks for the report! 
Could you check if you can open GitHub Desktop from `%LOCALAPPDATA%\GitHubDesktop\`?

**Comment by ahukg** [comment]
This exact issue is also occurring for me. I can open the exe from `%LOCALAPPDATA%\GitHubDesktop`, however, the app does not show up from start and is not searchable from the windows search. 

Microsoft Windows 10 Enterprise (Version 10.0.19044 Build 19044)

**Comment by ChanHY-beep** [comment]
The solution for me was to create a shortcut of GitHub.exe and place it into `C:\ProgramData\Microsoft\Windows\Start Menu\Programs` (If you can open GitHub.exe file in `%LOCALAPPDATA%\GitHubDesktop`)

**Comment by joshsutterfield** [comment]
Solution for me was to Run as Administrator when installing. Uninstalling the existing version might be tricky/manual because it really doesn't properly install all the way.
