### ISSUE TITLE
Commit history preview occasionally won't update when switching between commits quickly

### ISSUE THREAD

**Issue by EthyMoney** [desktop/desktop#15074]
### The problem

I have found that if I quickly jump around between different commits in the commit history list, the change preview on the right sometimes will not update and will stay stuck showing the changes for the last commit you were looking at. I also noticed that when this happens, the changed file is not selected, almost like the file from the previous commit you were looking at is still selected for the preview. I can fix this and make the preview update by just clicking on the changed file(s).

This one isn't a huge deal, but I have seen it come up a few times now where I'm rapidly clicking through some commits looking for something in particular then suddenly find that when I stop, the wrong preview is being shown.

### Release version

3.0.5 (x64)

### Operating system

Windows 10 Pro x64 Version 21H2 Build 19044.1865

### Steps to reproduce the behavior

1. Open a repo that's had commits made before
2. Open the "History" tab to see the commits
3. Now quickly click on multiple other commits from the list and then stop on one
4. The change preview on the right might show the changes from the previous commit you had clicked, rather than the one you currently have selected
5. Clicking a changed file will update the preview to the correct commit you have selected

### Log files

[2022-08-03.desktop.production.log](https://github.com/desktop/desktop/files/9254401/2022-08-03.desktop.production.log)

### Screenshots

![GitHubDesktopBug](https://user-images.githubusercontent.com/16528213/182691415-7d562fb1-782d-482a-9406-9b218e42c1cf.gif)

### Additional context

I didn't do super extensive testing on this to try to narrow down things like whether it occurs more often on big chnages, or repos with large commit histories for example. I just know that I've seen this come up occasionally both when at work and at home working on personal repos. This does not seem to be limited to a specific type of change or changed file, or any specific repos, it just kind of happens when and wherever it want to from what I can tell. The gif shown above is just a general example.

**Comment by steveward** [comment]
Thanks for reporting this @EthyMoney. This looks like the same report as @EthyMoney, but I appreciate you sharing the gif as that's helpful. I'm going to reference this issue there and close this out.

**Comment by EthyMoney** [comment]
I wouldn't close this, this is the only report I see, and there isn't another one. You referenced me twice haha

I think you got confused thinking there was another one of these

**Comment by steveward** [comment]
Apologies, copy and paste error. This is the issue I meant to reference: https://github.com/desktop/desktop/issues/13633.
