### ISSUE TITLE
Cant link repository to correct directory

### ISSUE THREAD

**Issue by keithlyx** [desktop/desktop#15076]
### The problem

I have been trying to create a repository from a local directory "WebstormProjects/authentication" however upon creation it automatically links to "WebstormProjects", which shows all the other files in WebstormProject as well. I think this is because the remote repository is in WebstormProjects, but I cannot seem to find and delete it. 

### Release version

3.0.5

### Operating system

Windows 1-

**Comment by steveward** [comment]
Thanks for the issue @keithlyx. Does the `WebstormProjects` directory have a hidden `.git` directory? That would indicate that it is a repository and would cause this issue. You don't want to create nested repositories if that is the case.
