### ISSUE TITLE
No Fastforward mode 

### ISSUE THREAD

**Issue by BloonHyzenert** [desktop/desktop#15078]
### The feature request

Hi,

I use your Github Desktop app a lot, which is simple and efficient with a very nice design. However, one small detail bothers me. This is the FastForward. Currently, all merges are done in Fastforward by default and rendering on a graph is less interesting. 

### Proposed solution

Would it be possible to add an option to launch merges with No FastForward (-no-ff) please.

### Additional context

Thank you for your help and for the app you offer

**Comment by steveward** [comment]
Thanks for the issue @BloonHyzenert. You can configure this by running the following command:

`git config --global merge.ff false`

This will apply to all repositories -- you can omit the global if you want to set it on a per-repo basis. I hope that helps!
