### ISSUE TITLE
"Not enough memory resources are available to process this command"

### ISSUE THREAD

**Issue by Digitalalienn** [desktop/desktop#15073]
### The problem

I am trying to log into my github account through github desktop. Every time it makes me log in through my browser, then it flashes the error in the heading. I have reinstalled the application as well as cleared the %appdata% for the desktop application multiple times. 

### Release version

Unable to see verion

### Operating system

Windows 10 64bit

### Steps to reproduce the behavior

1. Sign in to Git hub Account
2. new tab and browser pops up asking if I would like to open Github Desktop
3. Hit accept
4. "not enough memory to process command"

**Comment by steveward** [comment]
Thanks for the report @Digitalalienn. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Digitalalienn** [comment]
[2022-08-03.desktop.production.log](https://github.com/desktop/desktop/files/9255210/2022-08-03.desktop.production.log)
@steveward  here is my log file from today

**Comment by steveward** [comment]
Thanks for sending that over. This likely indicates a system issue -- could you try opening an elevated command prompt and running the command `sfc /scannow` to see if there are any system issues that need to be repaired?

**Comment by Digitalalienn** [comment]
I ran the elevated command prompt, it did say that there were some broken files that needed repair and it repaired them but I am still running into the same error.

**Comment by steveward** [comment]
I'm guessing you've also tried restarting your machine to see if that helps? Are you having issues with any other applications?

**Comment by Digitalalienn** [comment]
I have restarted my machine, I also made sure to restart my system after I ran the cmd prompt line. This is the only application I have issues with for memory. My system has 64 gigs of memory and while its more full than I like it, the boot drive does have open space on it

**Comment by travmason** [comment]
Same issue here.
Windows 11 Version 10.0.22000 Build 22000
32gb ram
no other issue with any app on the machine.

[2022-09-03.desktop.production.log](https://github.com/desktop/desktop/files/9481630/2022-09-03.desktop.production.log)

**Comment by steveward** [comment]
See [the solution here](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#not-enough-resources-error-when-signing-in) for a way to resolve this issue based off of https://github.com/desktop/desktop/issues/15217#issuecomment-1236989284. I'm going to close this out, but let me know if that solution does not work.
