### ISSUE TITLE
I can not open Rstudio after Github installed

### ISSUE THREAD

**Issue by CongWang141** [desktop/desktop#15079]
### The problem

every time I open Rstudio, GitHub desktop will be opened automatically
then RStudio has problem to run
If I uninstall GitHub desktop, I can run RStudio normally again

### Release version

3.0.5

### Operating system

windows 10

### Screenshots

![image](https://user-images.githubusercontent.com/110236467/182917494-c4cb5db2-a9bc-49cb-8405-d0a93075447b.png)

**Comment by steveward** [comment]
Thanks for the report @CongWang141. Have you configured anything Git related in `Tools -> Global Options -> Git/SVN` in RStudio? I know you need to configure Git when using RStudio, so I'm wondering if something could be misconfigured and pointing to GitHub Desktop instead of git.exe.

**Comment by CongWang141** [comment]
Dear Steve Ward,

Thanks for your help!  I didn't do it before, followed by your instructions
I fixed this problem.
Thanks again, and have a nice day!

Best regards

Cong

**Comment by steveward** [comment]
Glad to hear that got things working!
