### ISSUE TITLE
Not seeing any pull request sub-tab in current branch tab.

### ISSUE THREAD

**Issue by joel-regen** [desktop/desktop#15072]
### The problem

latest update, but not seeing the pull request tab.

### Release version

Version 3.0.5 (x64)

### Operating system

Mac OS 2

### Screenshots

<img width="620" alt="Screen Shot 2022-08-03 at 10 16 22 AM" src="https://user-images.githubusercontent.com/1912095/182631272-58ade060-a568-4be9-87df-b07f09d3a796.png">

**Comment by steveward** [comment]
Thanks for the report @joel-regen. Is this repository possibly classified as 'Other' in the repository list? That would cause the PR tab to disappear.
