### ISSUE TITLE
Option for more than 5 recent branches in drop down

### ISSUE THREAD

**Issue by gitsakos** [desktop/desktop#15082]
### The feature request

I often need to switch back and forth amongst more than 5 different branches.  Would be really nice to have the drop down show up to 10 of my recent branches.  On the contrary, I don't think I have ever used the 'Other Branches' section to change branches.

### Proposed solution

Add an option to only show recent branches in the drop down.

**Comment by steveward** [comment]
Thanks for the issue @gitsakos. This is being tracked in https://github.com/desktop/desktop/issues/14311 so you can follow along there for updates. I'm going to close this out.
