### ISSUE TITLE
Automatic add Submodule if Main Git added in the app 

### ISSUE THREAD

**Issue by mahmudabir** [desktop/desktop#15084]
### The feature request

I think there should be a feature where we can add a local repository & the app automatically adds the submodules existing in it. Also I suggest to show them as a tree representation.

### Proposed solution

I have to work in some projects where codes have sub repositories. This feature may help use to navigate to a repository's submodules very easily. 

Also, rearranging the list of repositories, mark as starred facility would be very helpful.

**Comment by steveward** [comment]
Thanks for the issue @mahmudabir. GitHub Desktop does recursively pull down the submodules associated with a repository when cloning. Automatically adding all submodules could cause the repository list to balloon, and at this time we don't have any plans to implement a tree view into the repository list. You can manually add submodules as needed, and we are in the process of working on improving the overall submodule experience in GitHub Desktop (see https://github.com/desktop/desktop/issues/7523).

I will reference this issue in https://github.com/desktop/desktop/issues/7523, but I'm going to close it out now as it isn't something that we'll likely implement.
