### ISSUE TITLE
Loss of sync with remote repository causes erroneous merge 

### ISSUE THREAD

**Issue by lloydtao** [desktop/desktop#15088]
### The problem

GitHub Desktop believes that a commit hasn't been pushed, even though it has, as evident on `github.com`:

![image](https://user-images.githubusercontent.com/41923457/183256900-686aa76f-245e-47a6-b172-0a862e11d1bf.png)

It wants to pull and merge the commit erroneously. After resolving the conflict (creating an incompatible merge commit), it will then allow to push this respective commit.

Restarting relevant applications (i.e. GitHub Desktop, VSCode Git extensions) does not resolve this.

Force pushing 'resolved' the issue for me by effectively syncing them back up.

### Release version

Version 3.0.5 (x64)

### Operating system

Windows 10 Pro

### Steps to reproduce the behavior

I do not have consistent reproducibility steps.

### Log files

[2022-08-06.desktop.production.log](https://github.com/desktop/desktop/files/9275431/2022-08-06.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @lloydtao, I'll take a look and see if I can reproduce this.

**Comment by niik** [comment]
Hey @lloydtao, I'm afraid we've been unable to reproduce this. If you encounter this again please let us know by opening a new issue and referring to this one. If you encounter this again please also compare the commit id (the "shas") of the commits on the remote and locally to make sure that a rebase or cherry-pick operation hasn't created similar-looking but different commits causing this behavior.
