### ISSUE TITLE
Issue with push data to workflow in Treasure Data

### ISSUE THREAD

**Issue by VimalArockiaraj** [desktop/desktop#15081]
### The feature request

Hi,

I am getting below error message while pushing data to workflows in Treasure Data.
error: Status code 403: {"message":"Cannot edit projects","status":403}
I can't able to identify the issue, Kindly help me to find the solution.

Thanks,
Vimal A

### Proposed solution

NA

### Additional context

Kindly give me a understanding on this issue.

**Comment by steveward** [comment]
@VimalArockiaraj thanks for the report. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by VimalArockiaraj** [comment]
[2022-08-05.desktop.production.log](https://github.com/desktop/desktop/files/9268906/2022-08-05.desktop.production.log)


PF Attached.

**Comment by steveward** [comment]
@VimalArockiaraj thanks for sharing that. I'm not seeing the specific error you mentioned, but I am seeing some `failed to fetch` and `404` errors. Are you able to push in other repositories?

Can you share a screenshot of the error you are seeing?

**Comment by VimalArockiaraj** [comment]
![Screenshot 2022-08-08 103009](https://user-images.githubusercontent.com/52524590/183342707-8f4302e9-c590-496d-ab48-3fffb4a46488.png)

**Comment by VimalArockiaraj** [comment]
[1_build (1).txt](https://github.com/desktop/desktop/files/9278847/1_build.1.txt)

**Comment by VimalArockiaraj** [comment]
Can you update.

**Comment by steveward** [comment]
@VimalArockiaraj we can't provide support for GitHub Actions here. You'll need to reach out to [GitHub Support](https://support.github.com/) or ask for help [here](https://github.com/orgs/community/discussions/categories/actions-and-packages).
