### ISSUE TITLE
Execute Meta TXN? on Etherscan

### ISSUE THREAD

**Issue by Vivalamilz** [desktop/desktop#15094]
I used my Loopring Smart Wallet app to send someone some Ether...
I then sent them the TXN HASH to confirm payment...
They never received the funds...
I pulled up the TXN on Etherscan and noticed that this TXN was different..
It created a smart contract with my wallet as the creator...(First time I have seen this....)
It also has a "EXECUTE META TXN" from: 0x212e75bf264c4fb3133fa5ef6f47a34367020a1a
Can anyone tell me the next steps to execute this transaction so I can get the recipient his funds...
Does it involve my guardian? or an additional signature on the blockchain:?
Any guidance and help would be much appreciated....
I am a novice when it comes to coding....
Thanks, Brad Mills
vivalamilz@protonmail.com
[Loopring Execute Meta TXN 0x59aafe861ecf5a53be6b21119f11bf6ab30e4e2a9f8e7a78bf3f2edfe962509.docx](https://github.com/desktop/desktop/files/9286790/Loopring.Execute.Meta.TXN.0x59aafe861ecf5a53be6b21119f11bf6ab30e4e2a9f8e7a78bf3f2edfe962509.docx)

**Comment by niik** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
