### ISSUE TITLE
Error EISDIR

### ISSUE THREAD

**Issue by MathiAs2Pique** [desktop/desktop#15096]
### The problem

After creating a nuxt project from npm (`npm init nuxt-app`), all files are created, and correctly, everything is visible in Visual Studio, but Github Desktop shows me only one file, with the name of the folder, with the error "The file is empty".
After looking at the logs, I found this: 
`Error: EISDIR: illegal operation on a directory, read`.

### Release version

3.0.5

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Open Github Desktop
2. In Visual Studio Code's terminal, create a nuxt project with npm in a repository
3. Check your Github Desktop

### Log files

```
2022-08-09T16:24:47.909Z - info: [ui] launching: 3.0.5 (Windows 10.0.19044)
2022-08-09T16:24:47.916Z - info: [ui] execPath: 'C:\Users\admin\AppData\Local\GitHubDesktop\app-3.0.5\GitHubDesktop.exe'
2022-08-09T16:24:48.227Z - error: [ui] Could not load new contents for syntax highlighting
Error: EISDIR: illegal operation on a directory, read
```

### Screenshots

![image](https://user-images.githubusercontent.com/45072138/183707431-45648220-7bff-4a33-9e66-ecea9e60fdbc.png)
![image](https://user-images.githubusercontent.com/45072138/183707510-6b680a9b-fc4c-46b3-84ed-a91144df0be8.png)

### Additional context

Same error if : 
- `npm init` run from cmd
- Github Desktop launched as admin

**Comment by steveward** [comment]
Thanks for the issue @MathiAs2Pique. We had a previous report of this `EISDIR` error in https://github.com/desktop/desktop/issues/11881, and in that case it resolved itself after an updates. 

Have you been able to reproduce this after you initially hit the error? I'll take a look and see if I can trigger the error on a test VM.

**Comment by MathiAs2Pique** [comment]
Hello, thank you for this quick response.
I'm facing this issue for 2 days now, regardless of the path and name of the folder.

**Comment by tsvetilian-ty** [comment]
@MathiAs2Pique does it happen only when using `nuxt`? Could you test with another repository? 

I tried to reproduce the issue, but with no success 😞

**Comment by steveward** [comment]
@MathiAs2Pique unfortunately I was unable to reproduce this as well.

Another related issue is https://github.com/desktop/desktop/issues/7691, which was specifically caused by diffing submodules.
