### ISSUE TITLE
Cloning Error

### ISSUE THREAD

**Issue by gvekariya08** [desktop/desktop#15092]
### The problem

Getting error of GitHub signing while cloning repositories.

### Release version

Version 3.0.5 (x64)

### Operating system

Windows 10

### Screenshots

![image](https://user-images.githubusercontent.com/86401801/183341570-b94bf2e9-6bd9-44ef-841b-df175eb34ef0.png)

**Comment by steveward** [comment]
@gvekariya08 thanks for the issue. This looks like a network problem -- are you behind a proxy or firewall that could be interfering with your connection to GitHub?
