### ISSUE TITLE
Github Desktop not working with PATs

### ISSUE THREAD

**Issue by TXP-BenHoffman** [desktop/desktop#15093]
### The problem

There is a repository I am attempting to clone locally that requires a PAT. When I attempt to clone it, it allows me to download the repository. At the end of the download, I get the below error screen.  This is the first place where Github Desktop lets me enter a PAT. At this point I enter it, delete the clone directory (it won't let me proceed if I don't) and then click Save & Retry after it downloads again, I get the same error message.
![image](https://user-images.githubusercontent.com/1637888/183498848-2eefa6d0-5d7c-4ef9-bf9e-2410443e962e.png)

### Release version

3.0.5

### Operating system

Windows 10

**Comment by steveward** [comment]
Thanks for the issue @BenHoffman. Is there a specific local hosting service you are using (i.e. GitLab, Gitea, etc.)?

**Comment by TXP-BenHoffman** [comment]
Thank you, I believe I figured it out. There appears to be a submodule and
I do not have access to it. This is all on github.  It was not very clear
that it was failing on the submodule and not the actual repo itself.  Thank
you! You can close the ticket.

Ben Hoffman
