### ISSUE TITLE
Coup'de fleet

### ISSUE THREAD

**Issue by Courvoisiae181** [desktop/desktop#15091]
### The problem

I am having troublesome add photos and videos for communication. Can you help?

### Release version

REad.ME

### Operating system

internet Explorer Window 11

### Log files

https://user-images.githubusercontent.com/110782843/183306373-c782851e-bece-491d-a44d-309372f3cefe.mp4

**Comment by niik** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
