### ISSUE TITLE
Show in Terminal Link

### ISSUE THREAD

**Issue by bhubbard** [desktop/desktop#15100]
### The feature request

Add a button for show in terminal.

### Proposed solution

Add a button to show in terminal, in addition to the Show in finder option
![GitHub Desktop 2022-08-11 at 8 25 28 AM](https://user-images.githubusercontent.com/3837/184170682-ef73204e-3832-4c18-8f60-30ef010617af.png)
.

**Comment by tsvetilian-ty** [comment]
👋 @bhubbard  You can find the original discussion in https://github.com/desktop/desktop/issues/6674. There is also a comment (https://github.com/desktop/desktop/issues/6674#issuecomment-459905998) explaining why that option is currently unavailable in the suggested actions view.
