### ISSUE TITLE
Unable to select all contents of stashed file

### ISSUE THREAD

**Issue by will056** [desktop/desktop#15102]
### The problem

Execute  stash. Now I can't select all the content in it. And copy to notepad.
But only the part that is on the screen is copied, not the entire file.

### Release version

Version 3.0.5 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1 change repository file
2 make stash
3 go to preview hidden files
4 select all content crtl+a
5 copy. button copy or ctrl+c
6 paste into notepad
but

### Log files

[2022-08-12.desktop.production.log](https://github.com/desktop/desktop/files/9314891/2022-08-12.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/13799692/184316953-6995bfae-d694-4b17-b4bb-45d7ab9acd05.png)
![image](https://user-images.githubusercontent.com/13799692/184317719-10f32ce7-b6c2-4274-8c9a-d13e2001fd6c.png)
![image](https://user-images.githubusercontent.com/13799692/184317542-02f68cd9-753f-4995-9c73-84b930f899d2.png)

**Comment by niik** [comment]
Hey @will056, thanks for reaching out! This looks to be the same bug as is descried in https://github.com/desktop/desktop/issues/13701 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date with any development happening in that area.
