### ISSUE TITLE
Add "View Forked Repository on GitHub" if the repository is forked.

### ISSUE THREAD

**Issue by andrewhong04** [desktop/desktop#15106]
### The feature request

When contributing to other repositories to which we don't have write access, we always create a fork to that repository, and sometimes we want to navigate to our forked repository instead of the parent. GitHub Desktop always redirects us to the parent repository instead of our fork.

### Proposed solution

Add "View Forked Repository on GitHub" if the repository is forked.

### Additional context

Can I work on this?

**Comment by steveward** [comment]
Thanks for the issue @novialriptide. This is being tracked in https://github.com/desktop/desktop/issues/13533, so you can follow along there for updates. I'm going to close this out.
