### ISSUE TITLE
HTTP code 407 from proxy after CONNECT

### ISSUE THREAD

**Issue by teddirussell** [desktop/desktop#15113]
Hi team, we use a proxy on our work computers which I believe is causing this. Don't have much authority to fix things on the machine. What can I instruct IT to do to fix this for me
![183532890-8e42a587-eaa8-4f6e-a6a5-b06c6ef804ce](https://user-images.githubusercontent.com/74998818/184556455-50ee114b-53a0-41f5-8bac-b3b66b0613ec.png)
?

**Comment by tsvetilian-ty** [comment]
@teddirussell thanks for the report! This issue has been discussed in https://github.com/desktop/desktop/issues/10026, https://github.com/desktop/desktop/issues/13330, and https://github.com/desktop/desktop/issues/6488. You could try some of the proposed solutions.
