### ISSUE TITLE
Constantly Disconnecting

### ISSUE THREAD

**Issue by Mashimaro7** [desktop/desktop#15110]
### The problem

I'm trying to commit a fairly large repository. My internet is stable, but I've tried at least 5 times, and it always says it disconnected near the end of the upload. I don't think it's actually disconnecting? Even if it was, why is there no way to resume the upload if it fails?

### Release version

Version 3.0.5 

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Upload a large repository
2. Disconnect

**Comment by niik** [comment]
> I'm trying to commit a fairly large repository

What's a fairly large repository? There are [limits](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github) to how big a repository is allowed to be on GitHub, including limits on the size of individual pushes (100Mb). I would guess you're running into one of those limits. Please see the ["About large files on GitHub" article](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github) for more information.

**Comment by Mashimaro7** [comment]
Hey, I am aware of these limits, but shouldn't it be showing me an error stating that the repository or some of the files are too large? I have committed this repository before, i was just running into some issues with the commits not being shown on my collaborator's side, so i decided to duplicate the project and commit it again. I tried committing it a few more times and it still always says it disconnected when the repo is almost fully committed.(I'm using Github Desktop, by the way)
________________________________

**Comment by steveward** [comment]
@Mashimaro7 could you share the log file from GitHub Desktop so that we could take a closer look at the underlying issues you are hitting?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
