### ISSUE TITLE
Signed-off-by

### ISSUE THREAD

**Issue by arjitc** [desktop/desktop#1511]
Would it be possible to add this to automatically add to each commit (perhaps a setting under options) ?

**Comment by shiftkey** [comment]
`-s` is just a flag to pass to Git, so it's not much work to add it in.

Speaking personally, this isn't something that's a huge part of my workflow - and that's mostly down to the projects I contribute to. I'll leave this open to gauge interest.

**Comment by Croydon** [comment]
Please add signing off commits and tags natively.

**Comment by niik** [comment]
> Would it be possible to add this to automatically add to each commit (perhaps a setting under options) ?

@arjitc Could you tell us a little more about your workflow here? Are you adding the signed-off-by line on your own commits? I'm not very familiar with Signed-off-by but after some reading it appears that it's used in some projects as a way to signal that you've consciously made a determination that the code your adding can be included under the same license as the project you're contributing to is governed by.

Some more reading suggest that it's frowned upon to have this added automatically as, as previously stated, it's supposed to be a conscious decision. As such Git itself doesn't have a configuration option to add this automatically.

I'm thinking that one way we could support this would be to add a context menu option to the description textbox that appends the signed-off-by tag. That way it would still be a conscious call.

![image](https://cloud.githubusercontent.com/assets/634063/26240377/203e52ee-3c81-11e7-869c-0f03bc591f3e.png)

![image](https://cloud.githubusercontent.com/assets/634063/26240456/63d600c4-3c81-11e7-94d7-9acac161d8a4.png)

**Comment by niik** [comment]
> Please add signing off commits and tags natively.

@Croydon We're tracking tag support in https://github.com/desktop/desktop/issues/257 please subscribe to that issue to follow along

**Comment by arjitc** [comment]
Hi @niik,
> @arjitc Could you tell us a little more about your workflow here? Are you adding the signed-off-by line on your own commits? I'm not very familiar with Signed-off-by but after some reading it appears that it's used in some projects as a way to signal that you've consciously made a determination that the code your adding can be included under the same license as the project you're contributing to is governed by.

Yes, it's in our own private projects hosted here on Github, we use it primarily to indicate that the changes have been approved/seen/accepted by that person who signs off it into the repo.

> Some more reading suggest that it's frowned upon to have this added automatically as, as previously stated, it's supposed to be a conscious decision. As such Git itself doesn't have a configuration option to add this automatically.

Yes, perhaps this could be a option like a checkbox above the commit info box ([] Add Signed-off-by)

**Comment by niik** [comment]
> Yes, perhaps this could be a option like a checkbox above the commit info box ([] Add Signed-off-by)

I'd prefer not to add anything to the primary interface for this feature since it's not a widely used feature. Would you like to take a stab at adding a context menu for the description box?

**Comment by arjitc** [comment]
> I'd prefer not to add anything to the primary interface for this feature since it's not a widely used feature. Would you like to take a stab at adding a context menu for the description box?

Ah, the right click (?) to add Singed-off-by would be nice too as in your screenshot above 👍

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
@arjitc Thanks for the issue here! Because we haven't seen this resurface in any meaningful way, we're going to close this to indicate that we don't intend to work on it in the near future. But we're not against revisiting if we see evidence from more users that this would be something they would also find value in. Thanks again, and appreciate you weighing in with the idea.

**Comment by Davo911** [comment]
I'd still be interested in this

**Comment by oscarllann** [comment]
bloqueado investigacion   jordi moreno gracias licito
