### ISSUE TITLE
unknown Error

### ISSUE THREAD

**Issue by Lefirmor** [desktop/desktop#15129]
### The problem

many questions, without describing an Error
![image](https://user-images.githubusercontent.com/111429897/185144411-3a11d2a6-1e05-46ef-ab94-6c5703b80b33.png)

### Release version

Version 3.0.5 (x64)

### Operating system

Windows

### Steps to reproduce the behavior

It happens by clicking "Sign in", Contunie with browser, then i have a link which has to direct me in GitHub Desctop. Then i get an Error above

### Log files

[2022-08-17.desktop.production.log](https://github.com/desktop/desktop/files/9363030/2022-08-17.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/111429897/185144472-c6d1a266-daee-4f2d-8bfc-15cf4ac61bb9.png)

**Comment by Lefirmor** [comment]
i have not seen this problem other people with other people, maybe it is very rare ivent

**Comment by sergiou87** [comment]
Hi @Lefirmor !

I think those � are supposed to be characters of your system language (cyrillic or something like that?). If you can switch your system language to English and try again we can see the exact error you're getting, but I think it's related to storing your GitHub user's token (used for authentication) in the Windows Credentials Manager.
