### ISSUE TITLE
Rebase freezes upon merge conflict

### ISSUE THREAD

**Issue by kamalca** [desktop/desktop#15135]
### The problem

Rebase freezes if there is a merge conflict.
I go to Branch > Rebase current Branch... > main > Rebase
A progress bar pops up showing "Applying commit 1 out of ..." then it freezes.

I had to finish the rebase with terminal.

### Release version

Version 3.0.5 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

Have a branch that will have merge conflict if rebased on main.
Go to Branch > Rebase current Branch... > main > Rebase
A progress bar pops up showing "Applying commit 1 out of ..." then it freezes.

### Log files

[2022-08-18.desktop.production.log](https://github.com/desktop/desktop/files/9377989/2022-08-18.desktop.production.log)

**Comment by sergiou87** [comment]
Hey @kamalca! 👋 

I've tried to reproduce this issue with those steps but I got no luck 😢 I've been able to finish all rebases with and without conflicts, as expected.

Is there anything special about that repo or branch? (e.g. many many commits/files being changed in that rebase, your branch is many commits behind `main`, you use Git LFS, submodules…)

In the logs you attached I see an authentication issue with a repository, were you aware of that? I wonder if it has anything to do with this problem 🤔

**Comment by kamalca** [comment]
The repo I was rebasing requires extra authentication for my organization, Microsoft. This must be what is causing the issue. Do you know how I can fix this?

Edit for additional comment: After Github Desktop freezes, I am able to fix conflicts and complete rebase through the terminal. Therefore, there are no permissions issues with the rebase operation.

**Comment by kkoppul2** [comment]
Experiencing the same issue as this ticket, rebasing a branch for the Rust Embassy project, https://github.com/embassy-rs/embassy/. 

Operating System
Windows 11 OS

Version
Version 3.3.14 (x64)

**Comment by kamalca** [comment]
I also still experience this issue. I’m not sure what is special about my set up, but I am part of an github organization which might make the authentication process more complex.

**Comment by niik** [comment]
Hey @kamalca, @kkoppul2. We're still unable to reproduce this I'm afraid. Could either of you get the app into this bad state and then (while the rebase is frozen) check that which of the following files exist in your repository

```
.git/REBASE_HEAD
.git/rebase-merge/orig-head
.git/rebase-merge/head-name
.git/rebase-merge/onto
```

Thanks!
