### ISSUE TITLE
go dark

### ISSUE THREAD

**Issue by MakingMC** [desktop/desktop#15133]
### The feature request

make dark mode

### Proposed solution

dark mode

### Additional context

night time eyes go owwww

**Comment by sergiou87** [comment]
Hi! You can already enable a dark mode from the app settings -> Appearance. I hope that helps 😄 
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/1083228/185379611-2bfa04bf-bdd4-40c4-8be5-7800fb92d446.png">
