### ISSUE TITLE
Impossibile to deactivate undo prompt

### ISSUE THREAD

**Issue by riccardodivirgilio** [desktop/desktop#15134]
### The problem

I disabled all prompts under settings, but apparently there is no setting to deactivate the UNDO commit prompt.
<img width="1121" alt="Screenshot 2022-08-18 at 13 14 57" src="https://user-images.githubusercontent.com/187641/185382275-de4fa72b-188a-435d-bf24-982782ddef48.png">

<img width="624" alt="Screenshot 2022-08-18 at 13 16 59" src="https://user-images.githubusercontent.com/187641/185382348-1b50ab3d-5970-4060-b0b4-0e84387f376b.png">

### Release version

Version 3.0.5 (x64)

### Operating system

macOS

### Steps to reproduce the behavior

1. create a new commit
2. press "UNDO"
3. a prompt is displayed

**Comment by geophilusd** [comment]
I would like to work on this one. 

We have different Undo commit warnings when we undo merge commits. Should we use a single disable prompt option for both these scenarios or have separate options?

<img width="768" alt="Screenshot 2022-09-03 at 2 18 22 PM" src="https://user-images.githubusercontent.com/35450302/188263361-dda309e0-6012-4f3e-97a3-ccfb8497dc9f.png">

**Comment by tidy-dev** [comment]
@geophilusd Great - Thanks for wanting to work this issue! We just discussed this issue recently and think it does make sense to add the check box for the simple undo commit scenario. Thus, to directly answer your question, we do not want to add an option to disable the undo commit dialog when it has the merge commit message as it can change the users history output and it is expected to be more rare of an occurrence anyways.

**Comment by riccardodivirgilio** [comment]
why not let me disable the prompt? I know what I'm doing at with my workflow it happens every 10 minutes when I'm working. 

I think the user should be able to disable any prompt... Also a checkbox in the prompt (next to the cancel button) that says "Don't ask again" would be great.

**Comment by tidy-dev** [comment]
Sorry if I wasn't clear. The plan would be to implement the "Don't ask again" for the prompt in this issue and add corresponding check box in the prompts section.
![image](https://user-images.githubusercontent.com/75402236/188683657-4c97c8be-e863-49af-805b-9df05b92ebf0.png)

But not in @geophilusd comment (which is a different less common scenario with greater negative impact):
![image](https://user-images.githubusercontent.com/75402236/188683777-1c6c578a-f559-4336-9f50-0d3846922d32.png)

**Comment by riccardodivirgilio** [comment]
Thank you in any case for looking at this 💪

**Comment by Yogi199501** [comment]
…
