### ISSUE TITLE
Add ability to copy commit tags

### ISSUE THREAD

**Issue by notxcain** [desktop/desktop#15137]
### The feature request

It is impossible to copy a commit tag neither in commit history view nor in commit details view. This would be very handy for my workflow.

### Proposed solution

1. Add `Copy Tags` context menu item to the commit history view
2. Click on the tags in the commit details view should copy the tags in the clipboard

**Comment by andrewhong04** [comment]
I can get to work on this!

**Comment by Shivareddy-Aluri** [comment]
https://github.com/desktop/desktop/pull/15506
added an option to copy tags in the above PR
