### ISSUE TITLE
If there a Backtick(`) used anywhere in the code. Git Desktop consider everything after it as string.

### ISSUE THREAD

**Issue by ThePiyushAggarwal** [desktop/desktop#15147]
### The problem

If there a Backtick(`) used anywhere in the code. Git Desktop consider everything after it as string.
This can be seen in any file that is open in GitHub Desktop.
Tested for JavaScript code for a React app.

### Release version

Version 3.0.5 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Go to any repo in GitHub Desktop.
2. Open any file that has React.js code and has a Backtick somewhere in the code.

### Screenshots

![image](https://user-images.githubusercontent.com/27003616/185807129-ff4712bc-c7c1-47f9-8d14-ff5aea582c1c.png)

**Comment by tsvetilian-ty** [comment]
@ThePiyushAggarwal thanks for the report! The syntax looks broken overall, and my guess is that the reason is the `.js` extension. Could you try to change your file extension to `.jsx`?

**Comment by ThePiyushAggarwal** [comment]
Hi! Thanks for the reply.
I tried it with the .jsx file extension. It works right for that.
But I think not everybody will actually use JSX only in .jsx files.
CRA makes the app and it has a App.js file. It might have a Backtick as well.
GitHub Desktop probably needs fixing.

**Comment by tsvetilian-ty** [comment]
I'm not sure we can consider it a bug 🤔 I will mark it with the enhancement tag because it technically works when the proper extension is used.

**Comment by niik** [comment]
I don't think this is a bug. JSX content in a JS file isn't valid syntax and backticks (when used for string interpolation) does highlight correctly.

Our syntax highlighting comes from CodeMirror and you can test theirs out at https://codemirror.net/5/mode/javascript/index.html and https://codemirror.net/5/mode/jsx/index.html.

I'm going to close this as we don't consider it a bug.
