### ISSUE TITLE
Cancel repo clone

### ISSUE THREAD

**Issue by hueys** [desktop/desktop#15143]
### The feature request

It would be nice to have a button or keyboard shortcut to be able to cancel cloning a repo.

### Proposed solution

Add a button to the repo clone progress view to allow the operation to be canceled.

**Comment by sergiou87** [comment]
Hi @hueys ! Thanks for your suggestion, but this is already being tracked in #2082

I suggest you to subscribe to that issue in case we make any progress on it. We already have a mechanism to cancel ongoing git operations in dugite (https://github.com/desktop/dugite/pull/448) we just need to write a proper test for it (https://github.com/desktop/dugite/pull/454) and then use it in Desktop 😄
