### ISSUE TITLE
Inverter 2 will not "saved" 

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#15146]
### The problem

[Solar320](https://github.com/Solar320) commented [1 hour ago](https://github.com/grindylow/ahoy/issues/183#issuecomment-1221580898)

I wrote this allready to  "Settings not stored #183 " but it was closed

The error is still present. If you configure the Inverters, Inverter 0 is saved. But Inverter 1 has allready the Serial "484d2d3830300000" and the Power Limit "65535" inserted. If you delete this and save and restart the ESP8266, the values are not deleted and are inserted again in the Setup. The consequence is that the HTML Surface shows 2 Inverters although only on was configured. I will try to change the values to other values than "nothing" like1234567 and 16000 and will look what happen. If this values also not saved this shows that there is something wrong. Since I have only one Inverter my fast solution was to change the max supported Inverters from 3 to 1 to prevent to showing 2 Inverters at the visualization HTML site.
@[Solar320](https://github.com/Solar320)
Solar320 commented [1 hour ago](https://github.com/grindylow/ahoy/issues/183#issuecomment-1221582936) •

Ok I get it, the problem is that this html surface will only change anything when you insert capitals and numbers. If you don't insert anything in the fields (or delete the old input) , the HTML Surface will do nothing and use the old values. But the Surface should delete the memory if I delete alle numbers and capitals in the input fields.
I can confirm that an new Inverter will saved, if you change anything but there is still the problem that you can't save an empty inputfield. I can't confirm if an second Inverter will work because I have only one.
@[Solar320](https://github.com/Solar320)
Solar320 commented [now](https://github.com/grindylow/ahoy/issues/183#issuecomment-1221592924)

I found an quickfix for this problem. If you want to let the support in the source code at 3 Inverters and have currently only one Inverter installed, then you can set the second Inverter input fields all to "0". If you insert "0" instead of deleting all the input of the input fields, it will be interprate this as "Nothing" or no Value. If you then save and restart, all the inputfields of the Inverter 1 will be clean and also in the vizualization only one Inverter will be showed.

### Release version

0.5.15

### Operating system

Win10

**Comment by sergiou87** [comment]
I'm sorry @Solar320 but I think this is the wrong repo to post that 😅
