### ISSUE TITLE
Custom grouping + collapse expand 

### ISSUE THREAD

**Issue by shay-te** [desktop/desktop#15149]
### The feature request

As a freelancer, I am working with multiple customers and the list of repositories is becoming very large. 
especially these days when all is separated into microservices and libraries. 

The filter is good. but require of me to do some work. 
Thinks of GitHub desktop of a freelancer after 5 years of work. he will type the filter box a lot. 
it will be nice to group by and to collapse and expand groups.

### Proposed solution

It could make life much easier if I could 

- group by the repository owner (https://github.com/<OWNER>/some-repo)
- group by the repository server (GitHub/GitLab/bitbucket/etc.)
- collapse/expand a group.
- Create a custom group by name. 
- and more

### Additional context

great product. Thank you

**Comment by tsvetilian-ty** [comment]
Hey @shay-te thanks for reaching out! Perhaps this functionality will be available in the feature, but currently, there are no plans to include it in GitHub Desktop. You can read more on the topic in https://github.com/desktop/desktop/issues/10201#issuecomment-658693653. Also, you can check the conversation regarding repositories navigation in https://github.com/desktop/desktop/issues/6460

**Comment by ghnp5** [comment]
I was just coming here to suggest the exact same.  @shay-te  @tsvetilian-ty 

Either create our own grouping/folders for organizing the repos,
or at least GitHub Desktop could group the repos based on the folder they're at.

So, if we have some directory structure like:

Repos
- Partners
   - Repo 1
   - Repo 2
- Common
   - Repo 3
   - Repo 4
- DevTools
   - Repo 5
   - Repo 6
- ProjectSomething
   - Repo 7 Web
   - Repo 8 API

GitHub Desktop could have an optional View to reorganize and sort repos this way.
