### ISSUE TITLE
UI Hover Bubble glitch when no text

### ISSUE THREAD

**Issue by Louis-Ladd** [desktop/desktop#15155]
### I hovered over a file's changes stat with no changes and noticed this
![Screenshot (2)](https://user-images.githubusercontent.com/16233776/185965743-d4cec97c-8ea0-4960-aaed-3e7c5f73c1e6.png)

### Release version

3.0.5 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Add a empty file
2. Hover over additions/deletions
3. mouse may block it, move mouse over to see it.

### Additional context

This is really minor.

**Comment by haykam821** [comment]
This issue seems to be caused specifically by the only changed file in the commit being a rename. That issue can easily be solved, but are there any other file status kinds that could be encountered here? Would it make sense to create a fallback so that an empty tooltip never appears?

**Comment by Mallelamphogift** [comment]
https://github.com/features#code-hosting/DE24R48-9LK6393-GRD7YSM-Z6C56ZN
