### ISSUE TITLE
Deleted tag is not removed from history

### ISSUE THREAD

**Issue by unru006** [desktop/desktop#15150]
### The problem

I created a tag within GitHub Desktop and pushed that to the origin.
In the browser I deleted the tag then. This change is not reflected back into my GitHub Desktop, a fetch/pull does not trigger the desktop app to update. The deleted tag is still visible in the history.

### Release version

Version 3.0.5 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Create tag in desktop app
2. Push to origin
3. Delete tag in the browser
4. Fetch changes from the server
5. As a result: the tag is still available locally

**Comment by steveward** [comment]
Thanks for the issue @unru006. GitHub Desktop does not support deleting tags that have been pushed to the remote. See [this comment](https://github.com/desktop/desktop/issues/9938#issuecomment-638779503) for the reasoning behind that. I'm going to close this issue out.
