### ISSUE TITLE
Initial publish of local repository to GitHub hangs on pushing to origin

### ISSUE THREAD

**Issue by GaryREM** [desktop/desktop#15153]
### The problem

Trying to do initial push of local repository to GitHub.

Repository is created on GitHub when I "Publish Branch". 
However the push appears to hang
<img width="279" alt="2022-08-22_11-46-12" src="https://user-images.githubusercontent.com/8797938/185963740-7e07008c-c35b-4b21-bc45-92ed78d10628.png">
.

### Release version

3.0.5 (x64)

### Operating system

macOS 13

### Steps to reproduce the behavior

1. Open GitHub Desktop by clicking on link in browser for GitHub repository
2. Click on Publish Branch button
3. Watch Total count up during transfer
4. Watch as arrows continue to spin

### Log files

[2022-08-22.desktop.production.log](https://github.com/desktop/desktop/files/9395817/2022-08-22.desktop.production.log)

**Comment by GaryREM** [comment]
Note that pushing from my IDE worked without any problems.

**Comment by steveward** [comment]
Thanks for the report @GaryREM. How large is the repository you are trying to push in GitHub Desktop? Unfortunately the log file isn't showing the push status, so it's unclear if it's timing out or just taking a long time to complete.

**Comment by GaryREM** [comment]
The local repo was around 250MB.

Each time I would start up GitHub Desktop, it would indicate I needed to publish. It would look like it was publishing but would hang. After 5 - 10 minutes I would give up. Finally, I did a push from my IDE and very quickly it was done. Going back to GitHub Desktop, I saw that the transfer was complete. It was only after doing the IDE push that bI could see content in the GitHub repo in my browser.

Gary

**Comment by steveward** [comment]
Thanks for the update. I'm going to close this out since you resolve the issue, but let us know if you run into this again and we can investigate further.

**Comment by MichaelTiemannOSC** [comment]
I found this issue because I have the same problem.  I guess I'll have to open a fresh issue with the exact same name and description, since the OP said it so well.  I am also coming from a Mac...

**Comment by GriffinSego** [comment]
Same problem

**Comment by benmoto** [comment]
Same problem, also if you init repository with manual upload of single file GitHub Desktop says you need to fetch it first - I click fetch, it does "something" and than I try to publish again with same result... that piece of software just does not work even from the very start...

**Comment by momiah** [comment]
just happened to me. Not sure if its because Im publishing with loads of new changes and assets which is taking long to upload or whether its timedout. no logs are provided. Also I can remove the files from the incoming/outgoing field of the IDE source control
