### ISSUE TITLE
Add git binary to PATH

### ISSUE THREAD

**Issue by Seb33300** [desktop/desktop#15160]
### The feature request

I am not sure if this issue is only related to Windows, but when we click on "Open in Windows Terminal" menu, if the git command is not registered in our PATH, this popup appears:

![image](https://user-images.githubusercontent.com/915273/186363362-592abc27-24d6-41df-a837-45abc02a0bb5.png)

If I click on `Install Git` button this open my browser to a page that explain how to install git.
But Git is already installed on my computer, GitHub desktop already comes with a git binary.

If I manually add the binary installed by GitHub Desktop to my path, the popup disappear:
```
C:\Users\[Username]\AppData\Local\GitHubDesktop\app-3.0.5\resources\app\git\cmd
```

BTW, when we install GitHub Desktop, this line is added to the PATH:
```
C:\Users\[Username]\AppData\Local\GitHubDesktop\bin
```
Which is the path to "github desktop" binary, I dont think this is useful to add it to the PATH?
Maybe this is a mistake and the desired path was the previous one?

### Proposed solution

I think, GitHub Desktop should automatically add (or update when the version changes) the bundled git binary to the PATH.
And replace the `Install Git` button, instead of opening a web page, add the git binary to the PATH.

### Additional context

In my opinion, it's better to use the same binary for command line and GitHub Desktop.
Because GitHub Desktop has an automatic update feature that can also update the git binary version.

If we install a different separate binary to use git in command line, this can result in a different git version used by GitHub Desktop or command line.

**Comment by niik** [comment]
Hi @Seb33300, thanks for reaching out. The version of Git that we ship alongside GitHub Desktop is a [customised build of Git](https://github.com/desktop/dugite-native) with all features not required by GitHub Desktop stripped away. It's not a general purpose Git installation and as such we don't intend to add it to the path for external consumption. A number of years ago in what we now call GitHub Desktop classic (specifically GitHub for Windows) we used to install a Git shell environment alongside GitHub Desktop but that had a number of problems (such as us shipping "proven" old versions of Git with backports to keep GitHub Desktop stable meaning users couldn't use the latest and greatest features of Git).

When we shipped the current generation of GitHub Desktop we intentionally chose not to conflate the Git system we use internally with what users were running in their shell environment.

So while your proposed solution is slick and would likely work for a decent chunk of our users we're not able to provide a complete, and up-to-date, Git CLI using the Git we embed for our internal purposes.

> Which is the path to "github desktop" binary, I dont think this is useful to add it to the PATH?

This path is added to allow users to run the `github` command line utility which lets you do things like `github .` in your command line environment to open the current folder in GitHub Desktop. It's not the path to the GUI application.

I hope that helps explain things!

**Comment by Seb33300** [comment]
Hello @niik 

In my case I dont really need the full git and the custom build shipped with GitHub Desktop is enough for me.
I also like to be consistent in the git version I use in my system.
That's why I will continue to manually add git path to my environment variables.

But I am bored to always update it everytime GitHub Desktop provide a new git version.
Can you please consider to update the path with the embedded git during app update in the case you can find it in the environment variables?

**Comment by mirddes** [comment]
this should definitely be a feature.
