### ISSUE TITLE
Account type not being reported correctly

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#1516]
It looks like the `enterpriseAccount` property is only being submitted when it's set to `true`. This property should be sent when equal to `false` as well.

**Comment by joshaber** [comment]
I couldn't reproduce this. The JSON sent from the app seemed to always include `enterpriseAccount` even when `false`.

**Comment by joshaber** [comment]
This is still happening with 0.5.4. I haven't figured out where we're losing this data 😞

**Comment by joshaber** [comment]
I think I've narrowed this down to a problem further up in our stats pipeline. Closing.
