### ISSUE TITLE
Linking to a wrong remote repo (GitHub Desktop).

### ISSUE THREAD

**Issue by CaptainUnknown** [desktop/desktop#15174]
### The problem

GitHub Desktop is linking my current local repository to a wrong one. If I use Git from Power Shell it works fine. I tried re-installing Desktop app a lot of times it doesn't work. I also tried removing & then adding back the repository, it changes its name to the old one. Although the commit history shows commits from new repository but if I right click & select view on GitHub it shows wrong remote repo.

### Release version

Version 3.0.6 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

(I'm not sure if that'd recreate the issue but I'm writing what I think happened that caused this problem.)
- Create a repo & clone it locally.
- Change the repo name from GitHub Web.
- Remove the repo & delete from local file.
- Create a new repo with same exact name & directory.
(It should now be linked to the old one.) 

### Log files

[2022-07-28.desktop.production.log](https://github.com/desktop/desktop/files/9433334/2022-07-28.desktop.production.log)

**Comment by niik** [comment]
I believe this is related to https://github.com/desktop/desktop/issues/11326 and (to some extent) https://github.com/desktop/desktop/issues/8206.

Are you able to try cloning the repository again?

**Comment by CaptainUnknown** [comment]
Thanks @niik! This issue was resolved. Check out [Pull #12308](https://github.com/desktop/desktop/pull/12308) for more info.

**Comment by niik** [comment]
Thanks for reporting back @CaptainUnknown!
