### ISSUE TITLE
github desktop not working on mac

### ISSUE THREAD

**Issue by PratteekShaurya** [desktop/desktop#15189]
### The problem

I have installed the latest version of github desktop from [](https://desktop.github.com/beta/) , but whenever I try to open the application I am getting a message "Github dektop quit unexpectedly"

### Release version

3.0.6-beta3

### Operating system

macOS Monterey 12.2.2

**Comment by steveward** [comment]
Thanks for the issue @PratteekShaurya. Have you tried a fresh installation to see if that helps?

It would also be helpful if you could open `Console.app` and see if there are any errors shown there when the application crashes on your machine.
