### ISSUE TITLE
Apparently unnecessary sign-in popups when GH Desktop is run

### ISSUE THREAD

**Issue by guardrex** [desktop/desktop#15181]
### The problem

Hello,

For no apparent reason, I'm getting these constant requests to sign in every time I open GH Desktop.

These never appeared before and they have no effect on my use of GH. I'm currently logged in with my account, and all GH Desktop behaviors are functioning normally without my having to use this popup to sign in.

### Release version

Version 3.0.6 (x64)

### Operating system

Windows 11 Pro (10.0.22000 Build 22000)

### Steps to reproduce the behavior

Just open the GH Desktop app. I think this popup is appearing every time I open the app.

### Log files

[2022-08-27.desktop.production.log](https://github.com/desktop/desktop/files/9437882/2022-08-27.desktop.production.log)

### Screenshots

![githubpopup](https://user-images.githubusercontent.com/1622880/187028439-7beac953-d12e-4b23-8ee2-317c335ba41c.jpg)

**Comment by guardrex** [comment]
**_Ah! This looks like a duplicate._**

I'll track on #15163 for this. I'm having the same problem as reported there.

**Comment by sergiou87** [comment]
Hi all! We just released 3.0.7 with the fix a few hours ago.

> **Warning**
> If you have installed either the latest beta or one of the test builds I shared (3.0.7-test1 and 3.0.7-test2), **DO NOT** install 3.0.7 unless you don't mind losing your repositories on GitHub Desktop and re-adding them there. They **won't** be removed from your local disk, don't worry about that, they're just removed from the **repository list** inside of GitHub Desktop. This is because those beta and test builds use [Electron](https://electronjs.org) v19, while the latest 3.0.7 has Electron v17 and won't be able to open the repository database once it's been migrated to Electron v19.
>
> We will release a new production build soon with Electron v19 that you can update to. I will let you know again when that happens.

If ☝️ this ☝️ warning doesn't affect you, or you don't mind re-adding all your repos to GitHub Desktop, you can update immediately from the About dialog. If it doesn't find a release (**it's not enabled to _all_ users yet**), try hold <kbd>Alt</kbd> on your keyboard and then click on the `Ensure Last Version` button to force the upgrade:

https://user-images.githubusercontent.com/1083228/187416390-01ee032d-8dca-4635-ab0e-a3c4c87e4c5d.mov

You can also download it from https://desktop.github.com

Thank you for your patience!! 🙇‍♂️
