### ISSUE TITLE
"Push" doesn't work!

### ISSUE THREAD

**Issue by Ruthlomyst** [desktop/desktop#15187]
### The problem

Hello,

My issue lies in the sector of pushing an existing repository. Under "Current repository", I find my earlier-used username "Green-Eyed-Teen" https://i.imgur.com/hUdPIeR.png

I'm signed in with my current account with the new username "Scorpius07" and yet, this happens. https://i.imgur.com/l5J4aDr.png

Earlier, when I had used the "desktop tutorial" when I found myself completely lost, it worked and after I clicked under "Current repository", it showed under "Scorpius07".

I hope there's a solution to this. Thank you!

### Release version

Version 3.0.6 (x64)

### Operating system

Windows 10 

### Steps to reproduce the behavior

1. Change your Github username. Wait for 2-3 days. Click on "Add an existing repository on your hard drive"
2. Select a folder
3. Click on "Current repo"

### Log files

[2022-08-28.desktop.production.log](https://github.com/desktop/desktop/files/9440026/2022-08-28.desktop.production.log)

### Screenshots

https://i.imgur.com/hUdPIeR.png
https://i.imgur.com/l5J4aDr.png

**Comment by steveward** [comment]
@Scorpius07 thanks for the issue. It looks like the `origin` remote URL of your repository is pointing to your old account. Can you go to `Repository` > `Repository Settings` > `Remote` and see if it is pointing to right URL? You can update it directly there as well.

**Comment by Ruthlomyst** [comment]
@steveward I changed the URL to _https://github.com/Scorpius07/City-Skyline.git_

However, I still doesn't work. It shows 
![image](https://user-images.githubusercontent.com/85307012/187369900-ad1f81da-66c7-4889-a370-a55cc80beefa.png)
and after publishing, 
![image](https://user-images.githubusercontent.com/85307012/187369952-f1761095-5c51-4a51-a8c6-08beca05c7b1.png)

**Comment by steveward** [comment]
Could you share a fresh log file from GitHub Desktop?

It looks like GitHub Desktop is showing the publish option -- try opening the command line (Repository > Open in <command_line>` and running a `git fetch` to see if that succeeds.

**Comment by Ruthlomyst** [comment]
Log File: [2022-08-30.desktop.production.log](https://github.com/desktop/desktop/files/9455771/2022-08-30.desktop.production.log)

What I'm getting after running `git fetch` is like this:
![image](https://user-images.githubusercontent.com/85307012/187520272-9757f492-c3a7-4a35-894d-6e4b4a8e9f74.png)

**Comment by steveward** [comment]
I took a look and it seems like that repository doesn't exist under your account, which is why you would be encountering these errors. Are you trying to create a new repository on GitHub?

**Comment by Ruthlomyst** [comment]
Well yeah!

**Comment by steveward** [comment]
You can run `git remote remove origin` and then you should be able to publish the repository from GitHub Desktop. That should get things working. I'm going to close this out.
