### ISSUE TITLE
Connect to Github

### ISSUE THREAD

**Issue by DarioArias-SB** [desktop/desktop#15197]
### The problem

Even though I'm logged in, it keeps asking every 10 seconds to log in over and over again. I have tried with the browser validation and at first says ok you can close this tab and 10 secs later ask again to log in, I have tried the code and it does the same thing.

### Release version

3.0.6

### Operating system

Windows 10

### Screenshots

![image](https://user-images.githubusercontent.com/77754941/187252571-f351cea2-4153-4bd4-ad1d-966ab1309d47.png)

**Comment by steveward** [comment]
Thanks for the issue @DarioArias-SB. See [this comment](https://github.com/desktop/desktop/issues/15163#issuecomment-1230548540) for the existing issue and beta build with a fix for this. I'm going to close this out.

**Comment by sergiou87** [comment]
Hi all! We just released 3.0.7 with the fix a few hours ago.

> **Warning**
> If you have installed either the latest beta or one of the test builds I shared (3.0.7-test1 and 3.0.7-test2), **DO NOT** install 3.0.7 unless you don't mind losing your repositories on GitHub Desktop and re-adding them there. They **won't** be removed from your local disk, don't worry about that, they're just removed from the **repository list** inside of GitHub Desktop. This is because those beta and test builds use [Electron](https://electronjs.org) v19, while the latest 3.0.7 has Electron v17 and won't be able to open the repository database once it's been migrated to Electron v19.
>
> We will release a new production build soon with Electron v19 that you can update to. I will let you know again when that happens.

If ☝️ this ☝️ warning doesn't affect you, or you don't mind re-adding all your repos to GitHub Desktop, you can update immediately from the About dialog. If it doesn't find a release (**it's not enabled to _all_ users yet**), try hold <kbd>Alt</kbd> on your keyboard and then click on the `Ensure Last Version` button to force the upgrade:

https://user-images.githubusercontent.com/1083228/187416390-01ee032d-8dca-4635-ab0e-a3c4c87e4c5d.mov

You can also download it from https://desktop.github.com

Thank you for your patience!! 🙇‍♂️
