### ISSUE TITLE
error cloning

### ISSUE THREAD

**Issue by BobLfish** [desktop/desktop#15196]
### The problem

Cloning into '<redacted path>\github\iPhone-Code-Samples'...
remote: Enumerating objects: 664, done.        
remote: Total 664 (delta 0), reused 0 (delta 0), pack-reused 664        
Receiving objects: 100% (664/664), 5.94 MiB | 27.79 MiB/s, done.
Resolving deltas: 100% (312/312), done.
error: invalid path 'DependentPicker/build/DependentPicker.build/Debug-iphonesimulator/DependentPicker.build/Objects-normal/i386/DependentPickerViewController.o~>'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

Would you like to retry cloning ?

### Release version

Version 3.0.6 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

clone a repository using URL

**Comment by steveward** [comment]
@BobLfish thanks for the issue. It looks like the `DependentPickerViewController.o~>` file has a `>` at the end, which is an illegal character on Windows. You will need to remove that character from the filename in order to clone the repository to a Windows machine. Editing the filename on GitHub would be the easiest way to fix this. Let me know if I can help with anything else.

**Comment by BobLfish** [comment]
There are several repositories that have the same problem. Also, it is not my repository. I really thought I would report the bug and let the owner fix everything

Sent from my iPad

On Aug 29, 2022, at 12:11 PM, Steve Ward ***@***.***> wrote:

﻿

@BobLfish<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBobLfish&data=05%7C01%7C%7C749d61eb85bc4c90d8ea08da89f2559c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637973971160665291%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lBrOBxXaIqu%2BE1%2BBoO6%2FYv6yynJ3Sbs3NVTDz9TbOy0%3D&reserved=0> thanks for the issue. It looks like the DependentPickerViewController.o~> file has a > at the end, which is an illegal character on Windows. You will need to remove that character from the filename in order to clone the repository to a Windows machine. Editing the filename on GitHub would be the easiest way to fix this. Let me know if I can help with anything else.

**Comment by steveward** [comment]
@BobLfish unfortunately there isn't much we can do about this from our end -- you'll need to open an issue in the specific repositories and ask the owner to rename the files if you want to use them on Windows. [Here](
http://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions
) are the naming conventions for reference.

**Comment by BobLfish** [comment]
Ok, thanks. I’ll let the owners know. It might help to post something about it. If there is something, I couldn’t find it which is why I sent the bug report.

Oh, BTW, it is something that happens after a repository has been active for a while. I first noticed this with ones I had been using just fine and then got the error message when fetching the latest.

Sent from my iPad

On Aug 29, 2022, at 1:08 PM, Steve Ward ***@***.***> wrote:

﻿

@BobLfish<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBobLfish&data=05%7C01%7C%7Cd29f3810356546048ec008da89fa3f71%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637974005141589753%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wTT3UtCYkw1wY9iKmPMpiJ8kmwws73EhjnraP7JuzZY%3D&reserved=0> unfortunately there isn't much we can do about this from our end -- you'll need to open an issue in the specific repositories and ask the owner to rename the files if you want to use them on Windows. Here<https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fmsdn.microsoft.com%2Fen-us%2Flibrary%2Fwindows%2Fdesktop%2Faa365247(v%3Dvs.85).aspx%23naming_conventions&data=05%7C01%7C%7Cd29f3810356546048ec008da89fa3f71%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637974005141589753%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=34Mx%2Fm29oZ%2BIENaum2bGq2UCiW1vvCSbBAXA7XsPFO0%3D&reserved=0> are the naming conventions for reference.
