### ISSUE TITLE
Github Desktop Size adjustment error

### ISSUE THREAD

**Issue by amazingabyrd** [desktop/desktop#15199]
### The problem

I can only adjust the borders a small amount, and this is causing the commit button to be blocked until I close and reopen the software. 

### Release version

cannot find

### Operating system

Windows 10 

### Steps to reproduce the behavior

Open Github desktop adjust borders.

**Comment by steveward** [comment]
Thanks for the issue @amazingabyrd. This sounds similar to https://github.com/desktop/desktop/issues/13940 -- what scaling is your monitor set to?

**Comment by amazingabyrd** [comment]
My monitor is set to 130%

**Comment by steveward** [comment]
Thanks, then you are hitting #13940. You can follow along there for updates -- I'm going to close this out.
