### ISSUE TITLE
Add "Open with GitHub Desktop" to Context Menu

### ISSUE THREAD

**Issue by RudraSen2** [desktop/desktop#15205]
### The feature request

Suppose I have a local repository and I want to add it to GitHub Desktop. Then I saw that when I right-click on File Explorer/Finder, there is no option to add it to the GitHub desktop. This feature should be a must and will save a lot of time.

### Proposed solution

It will improve accessibility and ease of use.

### Additional context

Nothing :)

**Comment by steveward** [comment]
Thanks for the feedback @RudraSen2. This is being tracked in https://github.com/desktop/desktop/issues/5373. I'm going to close this out -- you can follow along there for updates.
