### ISSUE TITLE
Can you provide simplified Chinese?

### ISSUE THREAD

**Issue by skyblued** [desktop/desktop#15219]
### The feature request

**希望可以提供简体中文**

### Proposed solution

**希望可以提供简体中文**

**Comment by sergiou87** [comment]
Thanks for contributing @skyblued. At this time we do not have language localization in GitHub Desktop, but this is something that we would like to do in the future. I don't have a timeline for when that may happen as it would require quite a bit of work by the team. I'm sorry that I don't have better news at this time.

PS: Nice profile picture 😄

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/GitHub-Desktop-Chinese-Language-Pack
