### ISSUE TITLE
Very lagging

### ISSUE THREAD

**Issue by sornpakorn** [desktop/desktop#15215]
### The problem

Face with very lagging (Delay) situation. Try uninstall and re-install it. The lagging situation have been the same.

### Release version

3.0.7

### Operating system

Windows 10

### Steps to reproduce the behavior

All the time, program open

**Comment by steveward** [comment]
Thanks for the issue @sornpakorn. We are tracking these performance trends in https://github.com/desktop/desktop/issues/13586. Are you running any antivirus/security software on this machine? That can often be a cause of performance degradation after an update.

It would also be helpful if you could upload the log file from GitHub Desktop. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
