### ISSUE TITLE
Minimum Font Size

### ISSUE THREAD

**Issue by anthumchris** [desktop/desktop#15216]
### The feature request

The smallest font size we can use is currently limited by the app. Could we allow the UI to render a font size smaller than 12px?

### Proposed solution

Some users prefer bigger font sizes, which is currently provided by GitHub Desktop via the zoom feature (keyboard shortcut `⌘`+`+` on mac). Could we also allow users to reduce the font size to the smallest size of their choosing? This allows more information to display on the screen.

**Comment by steveward** [comment]
Thanks for the issue @AnthumChris, I'm going to add this to https://github.com/desktop/desktop/issues/3543 which covers adjustability of font sizes in the app.

**Comment by anthumchris** [comment]
@steveward Any chance this can keep this open to maintain its isolated, small-scope?

Issue https://github.com/desktop/desktop/issues/3543 is almost 5 years old. While being related and potentially sharing overlap, that issue is entirely distinct and separate from the specificity of this request.

**Comment by rclements-redhat** [comment]
I have a 4k screen. I need a magnifying glass to see GitHub Desktop fonts.
