### ISSUE TITLE
Add a copy summary button inside the history tab 

### ISSUE THREAD

**Issue by hadisiren** [desktop/desktop#15214]
### The feature request

Dear team,

Adding a copy button inside the history tab for the commit banner so the user can copy the summary to be used in another commit or maybe to be shared with colleagues.

### Proposed solution

Add a button next to the summary in the history tab to copy the summary of the selected commit.

Please, find the attached

![guthub desktop](https://user-images.githubusercontent.com/95363158/187845643-f2a1f318-a0c6-425a-815f-b3268923938d.PNG)

Thanks in advance

**Comment by steveward** [comment]
Thanks for the issue @hadisiren. I'm going to close this in favor of https://github.com/desktop/desktop/issues/7518 where we are tracking this feature. You can follow along there for updates.
