### ISSUE TITLE
GitHub Desktop won't start

### ISSUE THREAD

**Issue by ItzJerry317** [desktop/desktop#15218]
### The problem

This issue is weird. I think there's a update (version 3.0.6), after the update, the program can't start and it doesn't show in the task manager. I've been struggled for this for a week, and i found out version 3.0.5 can run properly.
I think this is a problem of version 3.0.6, please fix :)

(Windows 11 22H2)

### Release version

3.0.6

### Operating system

Windows 11 22H2(Insider preview)

### Steps to reproduce the behavior

1.Double click exe file
2.Nothing happened

### Log files

Can't find log files because version 3.0.6 can't start

### Screenshots

https://user-images.githubusercontent.com/85010676/188035247-ad0b36da-fac5-4cf0-9981-c9b32c6756a0.mp4

### Additional context

Already found out how to solve.
Just simply open version 3.0.5 and everything works well

**Comment by sergiou87** [comment]
Hi @ItzJerry317 ! 👋 

Could you try downloading the latest version (3.0.7) from https://desktop.github.com and see if that works?

**Comment by 5150og** [comment]
I'm not sure what's going on,, I'm not a programmer, i start school in a
few months. But, i staked some bitcoin which I've lost, is this what your
referring to?
