### ISSUE TITLE
3.0.7 version update not available via Help | About GitHub Desktop

### ISSUE THREAD

**Issue by darkred** [desktop/desktop#15210]
### The problem

I have GitHub Destop 3.0.6 x64 installed on Win11.
I noticed yesterday in [Stable Release Notes](https://desktop.github.com/release-notes/) that v3.0.7 was released. I confirmed the above by going to https://desktop.github.com/ and downloading latest 'GitHubDesktopSetup-x64.exe' the version of which is `3.0.7.0` .

The issue is that when I go to: Help | About GitHub Desktop, there's no prompt to update to 3.0.7.

### Release version

3.0.6

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Go to: Help | About GitHub Desktop
2. Click "Check for Updates"
3. You'll see "You have the latest version (last checked just now)".

### Log files

[log.zip](https://github.com/desktop/desktop/files/9464560/log.zip)

### Screenshots

![](https://user-images.githubusercontent.com/723651/187773468-c0c04bab-173b-4b9b-a09d-b1f3d8b79c5f.gif)

**Comment by tsvetilian-ty** [comment]
@darkred thanks for reaching out! Could you upload a log file "Help > Show logs..."? Also, you mentioned downloading the latest version. Did you try to install it from the downloaded exe?

**Comment by darkred** [comment]
Ok, I uploaded the latest 2022-08-31.desktop.production.log zipped in the OP. 
I didn't try to install it from the downloaded exe because I thought to maintain the current issue situation, in order to be able to provide more details, if needed.

**Comment by tsvetilian-ty** [comment]
I'm unable to reproduce the issue 🤔 I guess you can try to use the downloaded installer to update your version. If more reports come in or you continue having problems updating, we can reopen this issue to investigate further. 

Could you confirm if installing the `exe` updates your version?

**Comment by darkred** [comment]
Yes, the `exe` updates my version: 
![screenshot](https://user-images.githubusercontent.com/723651/187772910-be8b22ec-acf7-467d-8b39-276d4e70ce35.jpg).

Thanks for offering to help. So I'm closing this.

**Comment by sergiou87** [comment]
Hi @darkred !

This is normal as we started rolling out releases slowly, so in case we made a mistake and introduced a regression, we don't spread it too quickly.

Right now it's deployed to 50% of users (probably gonna increase it to 100% today). In the future, if you want to force an upgrade, you can press <kbd>Alt</kbd> on your keyboard and the `Check for Updates` button will change:

https://user-images.githubusercontent.com/1083228/187416390-01ee032d-8dca-4635-ab0e-a3c4c87e4c5d.mov

**Comment by darkred** [comment]
Thanks a lot for the detailed reply!
