### ISSUE TITLE
Add a "Force Push" menu item

### ISSUE THREAD

**Issue by hubgit** [desktop/desktop#15211]
### The feature request

After performing an action like `git reset` outside GitHub Desktop, I'd like to be able to force push the current branch.

### Proposed solution

Add a "Force Push" menu item to the Repository menu.

### Additional context

Since https://github.com/desktop/desktop/pull/13384 the easiest workaround is to right-click the latest commit in the History tab and amend the commit message. When the commit is amended, the "Push origin" button changes to "Force push origin".

**Comment by tietie1234** [comment]
genshin impact
