### ISSUE TITLE
Problem on push branch (error: dst refspec master matches more than one)

### ISSUE THREAD

**Issue by slawkens** [desktop/desktop#15212]
### The problem

Hello,

not sure, but I think that started happening after updating to the latest version of GitHub Desktop (today).

I am getting strange message saying:
error: dst refspec master matches more than one
error: failed to push some refs to 'https://github.com/xitobuh/myaac-plugins.git'

When trying to push.

### Release version

Version 3.0.7 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Make changes to branch
2. Commit
3. Push branch from the menu "Push $remote_name"

### Log files

2022-08-31T21:44:09.618Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: myaac-plugins - slawkens (has token)
2022-08-31T21:44:10.101Z - error: [ui] `git -c credential.helper= push github-desktop-xitobuh pr/6:master --progress` exited with an unexpected code: 1.
stderr:
error: dst refspec master matches more than one
error: failed to push some refs to 'https://github.com/xitobuh/myaac-plugins.git'

### Screenshots

![image](https://user-images.githubusercontent.com/16687302/187791097-ba6b9f2c-567b-4e1d-b5f2-c28889075092.png)

**Comment by steveward** [comment]
@slawkens thanks for the issue. This most often seems to be caused by having a tag with the same name as the branch (see [this StackOverflow](https://stackoverflow.com/questions/9378760/git-push-local-branch-with-same-name-as-remote-tag). Can you run `git tag` from the command line and see if that could be causing the issue?

**Comment by slawkens** [comment]
Hello,

sorry for late answer.

You are completely right, there was branch with same name on remote.

I didn't saw it, because it was pushed by automate script, that has created a release with tag "master".

Dummy me!

Can be closed, sorry if reopened!
