### ISSUE TITLE
Switching between menu items shows disabled items on hover

### ISSUE THREAD

**Issue by Phoqe** [desktop/desktop#1521]
### Description
When clicking on a menu item, for example "View", you can hover over disabled menu items and display their content.

### Version
**GitHub Desktop version:** 0.5.3
**OS version:** Microsoft Windows [Version 6.1.7601]

### Steps to Reproduce

1. Start the app
1. Click on a menu item
1. From that menu item hover over a disabled menu item like "Repository" or "Branch", this is when no repository is selected.

**Expected behaviour:** Disabled menu items should not display content.

**Actual behaviour:** Disabled menu items display content, but only on hover when switching from an enabled menu item.

**Reproduces how often:** 100%

https://i.gyazo.com/956ce45577e7c6ee3ca157c34fe07525.mp4

**Comment by Zaelot** [comment]
Accidentally recreated this issue as #3391, it has a bit more detailed information.
The #3029 is also related.
