### ISSUE TITLE
Not enough memory resources are available to process this command

### ISSUE THREAD

**Issue by gatorlanphear** [desktop/desktop#15217]
### The problem

I try to "Sign in to your GitHub.com account to access your repositories." from the desktop app, I am sent to the browser to "continue with browser" to sign in.
And I get an error code and cannot sign in.

### Release version

3.07 (x64)

### Operating system

Win 11

### Steps to reproduce the behavior

1. Download and open Github desktop
2. Under FILE open "Options"
3. Choose "Sign in" with GitHub.com (not enterprise)
4. Click "Continue with browser" from pop up "Sign in using browser"
5. Browser (chrome) says, "Open GitHubdesktop.exe?" so I click "open githubdesktop.exe"
6. Get Error Not enough memory resources are available to process this command.
7. REPEAT.

### Log files

[2022-09-01.desktop.production.log](https://github.com/desktop/desktop/files/9473611/2022-09-01.desktop.production.log)
[2022-09-01.desktop.production.log](https://github.com/desktop/desktop/files/9473612/2022-09-01.desktop.production.log)

### Screenshots

![Screenshot 2022-08-28 121554](https://user-images.githubusercontent.com/112341620/188019399-7d8179dc-3ec3-4302-a99a-0c040a6cd348.jpg)

**Comment by sergiou87** [comment]
Hi @gatorlanphear ! 👋 

I'm not sure what this is about, but seems to happen when the app tries to store your GitHub user token in the Windows Credentials Manager. Could you try rebooting your machine and try again? Hopefully that's all you need 🤞

**Comment by gatorlanphear** [comment]
I have rebooted several times. It has not changed the result.
Is there another solution?
Gator

**Comment by tsvetilian-ty** [comment]
Another report on the subject: https://github.com/desktop/desktop/issues/15226
The context is the same... the error appears when GitHub Desktop tries to save the credentials in the credential manager. Could you check if you have `GitHub - {your_github_url}` in your credential manager (open search > search for "Credential Manager" > Windows Credentials)? Also, in https://github.com/desktop/desktop/issues/12712, running GitHub Desktop as admin fixed the issue.

**Comment by gatorlanphear** [comment]
I deleted an older credential to make space for github credentials.

**Comment by travmason** [comment]
> Another report on the subject: https://github.com/desktop/desktop/issues/15226
> The context is the same... the error appears when GitHub Desktop tries to save the credentials in the credential manager. Could you check if you have `GitHub - {your_github_url}` in your credential manager (open search > search for "Credential Manager" > Windows Credentials)? Also, in https://github.com/desktop/desktop/issues/12712, running GitHub Desktop as admin fixed the issue.

I do not have GitHub - anything in Credential Manager and it does not work if run as administrator.

**Comment by tsvetilian-ty** [comment]
It looks like the issue is related to too many entries in Windows Credential Manager. At some point the os calls `CredWrite` and it fails with `ERROR_NOT_ENOUGH_MEMORY` 😞 Visual Studio Code has the same issue in the ["Troubleshooting keychain issues"](https://code.visualstudio.com/docs/editor/settings-sync#_troubleshooting-keychain-issues) section of its docs. Some users report that it works properly once they remove some of the entries in the Credential Manager.

Could you try to run `cmdkey /list` (through PowerShell as Administrator) to see how many entries you have?

**Comment by gatorlanphear** [comment]
I was able to delete a credential and it worked! Thanks for your help!

**Comment by travmason** [comment]
it worked but I've had to delete production credentials to make it work. It won't last.

**Comment by maxineves** [comment]
¡Pude eliminar una credencial y funcionó! ¡Gracias por tu ayuda bro!

**Comment by gatorlanphear** [comment]
I have opened the credential manager and I do NOT have any listing for
GitHub.
Solutions?
Gator

**Comment by TommySTYP** [comment]
This solution always work for me.

Go to Control Panel -> User Accounts -> Manage your credentials -> Windows Credentials 

Before do anythings below, please do not forget Back up Credentials to make sure you did not remove important credentials accidentally.

After backed up then remove unnecessary or no longer use credentials such as mapping drive, credentials related to old software that you've uninstalled, etc. This way help to free up space of Credentials Manager. 

Try to open Github Desktop and see if the problem has been gone to the wind. If yes, congratuation and you will see "Github - https://....." on Generic Credentials

**Comment by st4rdog** [comment]
Again solved by deleting tons of credentials. About 100+ starting with XblGrts in my case.

Now Roblox Studio also logs in properly.

Is bizarre that so many apps are relying on this feature that clearly doesn't work.

**Comment by Tjibi** [comment]
It works if you delete some old credentials. As others mentioned, there is probably an error with older credentials existing and then it throws an automatic error. I did not have to run the application in admin. I did not have to reboot the computer. I just deleted some credentials :)

**Comment by brads59** [comment]
I had a million microsoft xbox live creds in credential manager. Had to delete them all but doing so manually would have been ludicrous. Here is powershell for loop that fixed mine:
`cmdkey /list | ForEach-Object {
    if ($_ -match "XblGrts|Xbl\|") {
        $target = ($_ -split ": ")[1]
        cmdkey /delete:$target
    }
}`

**Comment by tankorsmash** [comment]
> I had a million microsoft xbox live creds in credential manager. Had to delete them all but doing so manually would have been ludicrous. Here is powershell for loop that fixed mine: `cmdkey /list | ForEach-Object { if ($_ -match "XblGrts|Xbl\|") { $target = ($_ -split ": ")[1] cmdkey /delete:$target } }`

This worked for me. So strange that there's a limit on this at all. Fixed the missing semicolon

```pwsh
cmdkey /list | ForEach-Object { if ($_ -match "XblGrts|Xbl\|") { $target = ($_ -split ": ")[1]; cmdkey /delete:$target } }
```
