### ISSUE TITLE
Full name of repo not showing in 'Current repository' selection window

### ISSUE THREAD

**Issue by kkotherx** [desktop/desktop#15229]
### The problem

- The repo names, when longer they don't get displayed in the 'Current repository' window.
- One has to hover over the entries in GUI to see, which is very cumbersome with the font.
- Especially when repo names have common prefix, the window is unusable unless one hovers the mouse on the entry.
- To auto resize the 'Current repository' width.

### Release version

3.0.7

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Have multiple repos whose names are longer with common prefix (Eg: OrgA.application.server.component.oracle, OrgA.application.server.component.teradata, etc)
2. Clone the repos locally in your computer.
3. Now view the repo names in the 'Current repository' selection window

**Comment by tidy-dev** [comment]
@kkotherx Thanks for the reporting this issue! I am going to close it in favor of https://github.com/desktop/desktop/issues/4569 as our current tracking issue for this concern.
