### ISSUE TITLE
Not enough memory resources are available to process this command

### ISSUE THREAD

**Issue by travmason** [desktop/desktop#15226]
### The problem

Trying to authenticate in desktop, fails with the error as per the title

### Release version

Greyed out so can't tell

### Operating system

Windows 11 

### Steps to reproduce the behavior

1. Click 'clone repo from internet'
2. Click 'continue in browser'
3. Error appears

### Log files

[2022-09-03.desktop.beta.log](https://github.com/desktop/desktop/files/9484105/2022-09-03.desktop.beta.log)

### Additional context

Happens in prod version, beta version, if I run as normal user or as administrator. Same result every time.
Have uninstallde, rebooted, reinstalled, uninstalled again, rebooted, installed beta version, etc. Deleted cache files, deleted %appdata folder, etc, etc. Nothing works, it's broken. Please fix it I can't use this machine for dev work.

**Comment by tsvetilian-ty** [comment]
@travmason thanks for reaching out! The same issue has been reported in https://github.com/desktop/desktop/issues/15217. I will close this issue so we have one place to follow for updates https://github.com/desktop/desktop/issues/15217.
