### ISSUE TITLE
Inline comments in Swift sources break code highlighting

### ISSUE THREAD

**Issue by yakovmanshin** [desktop/desktop#15238]
### The problem

The Swift code that follows an inline (`/* … */`) comment isn’t highlighted in the diff viewer.

### Release version

3.0.7

### Operating system

macOS 12.5.1

### Steps to reproduce the behavior

1. Add a `/* … */`-style comment followed by code in a `.swift` file;
2. Commit the change;
3. Open the diff viewer.

### Screenshots

![](https://user-images.githubusercontent.com/4648742/188638144-9ba3078d-3a57-4706-bfbb-2d401ebbb3eb.png)

### Additional context

Fixing this will likely require changes in the upstream CodeMirror library ([issue](https://github.com/codemirror/codemirror5/issues/6981)).

**Comment by niik** [comment]
I can no longer reproduce this so I'm assuming an update of our syntax modes from CodeMirror solved the issue

![Image](https://github.com/user-attachments/assets/8b9385ee-5df1-421c-be9d-a6fbb4f036ef)

Please let us know if you experience this again
