### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by NeatCode12** [desktop/desktop#15235]
### The problem

Hi,

I am using GitHub Desktop Version 3.0.7 (x64), and having issue to clone or push to a repository that i am a contributor (and member)  there.
The error appear when i try to push or clone is:

Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.

I tried 1 & 2, not resolved, 3 not relevant, 4 checked, not resolved, 5-6, not relevant, 7 i don't understand.

Help?

### Release version

3.0.7

### Operating system

Windows 10

### Steps to reproduce the behavior

Run GitHub Desktop, choose the relevant repositoy, hit Push origin

**Comment by tidy-dev** [comment]
@NeatCode12 Sorry you are having issues. Would you mind uploading your log files for the time that this occurred?

To access the log files go to the menu and select Help > Show Logs

**Comment by NeatCode12** [comment]
[2022-09-13.desktop.production.log](https://github.com/desktop/desktop/files/9556962/2022-09-13.desktop.production.log)
Attached, thanks

**Comment by Cook299** [comment]
I don't know who you are but need to tell y'all I don't know nothing about this stuff so when everyone does this I get mad and bust my fones up I in around 300 bucks in two months because of this so please pass in on I don't know how to do this. thank you

**Comment by sergiou87** [comment]
@NeatCode12 looks like the repo URL is wrong? `git@github.com/Neat-Applied/ReDent-Nova-CordlessMotor.git` should be `git@github.com:Neat-Applied/ReDent-Nova-CordlessMotor.git` if I'm not wrong (see how the first `/` should be `:`)

Is that helpful?

**Comment by NeatCode12** [comment]
No, i changed it in the repository settings, but still getting the error like above

**Comment by sergiou87** [comment]
Could you share your logs again? The previous ones you attached said that `git@github.com/Neat-Applied/ReDent-Nova-CordlessMotor.git` wasn't a repository, so I wonder what it says now.

I guess you have access to this: https://github.com/Neat-Applied/ReDent-Nova-CordlessMotor 

You can also try to change the repo URL to `https://github.com/Neat-Applied/ReDent-Nova-CordlessMotor.git` from the Repository Settings and see if that works.

**Comment by NeatCode12** [comment]
I have tried it but i still get the same error in the log:
fatal: 'https@github.com/NeatCode12/Hospitech-CuffGuard.git' does not appear to be a git repository
fatal: Could not read from remote repository.

**Comment by sergiou87** [comment]
@NeatCode12 you wrote `https@github.com...` and it should be `https://github.com...`

**Comment by NeatCode12** [comment]
I cannot change in the repository settings to ://, the sign @ is used instead, anyway i still receive the same error after i change to https instead of git

**Comment by sergiou87** [comment]
Weird, maybe you can do it from a terminal (⚠️ **IMPORTANT:** make a backup of the repo first, just in case something breaks ⚠️ ) :
```bash
$ git remote remove origin
$ git remote add origin https://github.com/Neat-Applied/ReDent-Nova-CordlessMotor.git
```

If that doesn't work either, cloning it again like this is probably the best option:

![image](https://user-images.githubusercontent.com/1083228/189906457-53051030-c849-488b-9019-68491cbc8f73.png)

**Comment by NeatCode12** [comment]
$ git remote -v
$ git remote add origin https://github.com/Neat-Applied/ReDent-Nova-CordlessMotor.git
$ git remote -v
origin  git@github.com/Neat-Applied/ReDent-Nova-CordlessMotor.git (fetch)
origin  git@github.com/Neat-Applied/ReDent-Nova-CordlessMotor.git (push)

It doesn't change to https://, but to git@

**Comment by NeatCode12** [comment]
When i try to clone, it provides the error:
From the log: fatal: 'git@github.com/Neat-Applied/ReDent-Nova-CordlessMotor.git' does not appear to be a git repository
fatal: Could not read from remote repository.

**Comment by sergiou87** [comment]
> It doesn't change to https://, but to git@
🤯 

`git@github.com/Neat-Applied/ReDent-Nova-CordlessMotor.git` is definitely the wrong format so I understand why would that fail.

In any case this is weird… checking the git config stuff, there seem to be [some config parameters to rewrite URLs](https://git-scm.com/docs/git-config#Documentation/git-config.txt-urlltbasegtinsteadOf), I wonder if you have some of them.

Could you run `git config --list` in your repo and see if there is anything suspicious? Feel free to share it here after redacting any stuff you don't want to make public.

**Comment by NeatCode12** [comment]
i ran the command, it returns in one of the lines:
url.git@.insteadof=https://

**Comment by sergiou87** [comment]
There you have it! Try running `git config --unset 'url.git@.insteadof'`

That should remove the entry from `git config --list`. Then, try again the commands from https://github.com/desktop/desktop/issues/15235#issuecomment-1245373894:
```bash
$ git remote remove origin
$ git remote add origin https://github.com/Neat-Applied/ReDent-Nova-CordlessMotor.git
```

Changing the URL from `Repository Settings` should work now too

**Comment by NeatCode12** [comment]
Thanks! i manually edited the git config using:
git config --global -e
i removed the [url "git@"]
        insteadOf = https://
 and now i succeed to clone, fetch or push with no error, thanks again!

**Comment by sergiou87** [comment]
Yay!! I'm glad it worked 😄 Closing now…
