### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by niik** [desktop/desktop#1524]
We're getting a few RangeError, looks like it's limited to one or a few installations at the moment ([rollup](https://haystack.githubapp.com/desktop/rollups/d4250d5fcd308f07ca9a2a64cce72626))

```
RangeError: Invalid string length
    at Socket.onChildStdout (child_process.js:279:13)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

[This issue](https://github.com/nodejs/node-v0.x-archive/issues/14170) seems to indicate it could be due to not being able to allocate enough memory but it's a very old issue so I don't know how much to read into it. Regardless it'd be real nice if we could get a sense of what command we were executing when this occurred.

**Comment by shiftkey** [comment]
I can reproduce this via the file we stumbled on in https://github.com/desktop/desktop/issues/1818#issuecomment-305758541
