### ISSUE TITLE
Allow setting of default file explorer

### ISSUE THREAD

**Issue by jacoby149-pt** [desktop/desktop#15248]
### The feature request

Github Desktop lets you choose default editor and default shell in settings which I really like!

Github Desktop should have options for switching default file explorer.
On Mac I use QSpace Pro. I don't use Finder.

<img width="612" alt="Screen Shot 2022-09-07 at 11 44 36 AM" src="https://user-images.githubusercontent.com/110410159/188921556-27d446e4-b887-49ad-8599-d62d1886cb2a.png">

Currently, the only choice is to show repos in Finder, and it cannot be changed in the settings.

### Proposed solution

Add a setting to change the default file explorer to an application other than Finder.

**Comment by steveward** [comment]
Thanks for the issue @jacoby149-pt. I'm going to close this in favor of https://github.com/desktop/desktop/issues/13812. You can follow along there for updates.
