### ISSUE TITLE
Cloning into 'C:\Ashish\github\rbiconferences'... fatal: unable to access 'https://github.com/aisdevelopers/rbiconferences.git/': Received HTTP code 404 from proxy after CONNECT

### ISSUE THREAD

**Issue by aisdevelopers** [desktop/desktop#15265]
### The problem

Cloning into 'C:\Ashish\github\rbiconferences'...
fatal: unable to access 'https://github.com/aisdevelopers/rbiconferences.git/': Received HTTP code 404 from proxy after CONNECT

### Release version

Cloning into 'C:\Ashish\github\rbiconferences'... fatal: unable to access 'https://github.com/aisdevelopers/rbiconferences.git/': Received HTTP code 404 from proxy after CONNECT

### Operating system

Cloning into 'C:\Ashish\github\rbiconferences'... fatal: unable to access 'https://github.com/aisdevelopers/rbiconferences.git/': Received HTTP code 404 from proxy after CONNECT

### Steps to reproduce the behavior

Cloning into 'C:\Ashish\github\rbiconferences'...
fatal: unable to access 'https://github.com/aisdevelopers/rbiconferences.git/': Received HTTP code 404 from proxy after CONNECT

### Log files

Cloning into 'C:\Ashish\github\rbiconferences'...
fatal: unable to access 'https://github.com/aisdevelopers/rbiconferences.git/': Received HTTP code 404 from proxy after CONNECT

### Screenshots

Cloning into 'C:\Ashish\github\rbiconferences'...
fatal: unable to access 'https://github.com/aisdevelopers/rbiconferences.git/': Received HTTP code 404 from proxy after CONNECT

### Additional context

Cloning into 'C:\Ashish\github\rbiconferences'...
fatal: unable to access 'https://github.com/aisdevelopers/rbiconferences.git/': Received HTTP code 404 from proxy after CONNECT

**Comment by Angkitbharata** [comment]
Clmoabj

**Comment by Angkitbharata** [comment]
Mgo

**Comment by sergiou87** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
