### ISSUE TITLE
Manage multiple GitHub Accounts

### ISSUE THREAD

**Issue by samdiefenbacher** [desktop/desktop#15269]
### The feature request

I would like the ability to easily use multiple GitHub accounts without signing in every time to switch accounts.

### Proposed solution

In Options -> Accounts allow easy switching between Github.com accounts/users without having to logout of the other.

**Comment by tsvetilian-ty** [comment]
@samdiefenbacher thanks for your feedback! The feature is discussed in https://github.com/desktop/desktop/issues/3707. Feel free to subscribe to it. I will close this issue as a duplicate.

**Comment by geoidesic** [comment]
@tsvetilian-ty You closed this issue as a duplicate but the ticket you referenced is also closed! Why?
