### ISSUE TITLE
Unable to publish branch from Github desktop

### ISSUE THREAD

**Issue by NanditaHazra2022** [desktop/desktop#15268]
Error message: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.

**Comment by steveward** [comment]
@Nandita-Hazra this error indicates the repository does not exist -- can you go to the menu in GitHub Desktop and select `Repository` > `Repository Settings` > `Remote` and verify that the URL there points to an existing repository that you have access to?

If you continue to have issues please share the log file from GitHub Desktop. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
