### ISSUE TITLE
SSH User Password 

### ISSUE THREAD

**Issue by Maceo-p** [desktop/desktop#15271]
### The problem

GitHub Desktop ask me for a SSH User password for git@git.isartrina.com since a week.
I don't know why.
I don't even know what a SSH User password is.

### Release version

Version 3.0.8 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Open Github Desktop
2. Try to do anything
3. Github desktop ask me for a SSH key Password
4. I click on cancel a dozen time 
5. Everything works fine for 20 minutes
6. The pop-up is back and I have to reclick on cancel a dozen time

### Screenshots

![image](https://user-images.githubusercontent.com/67322934/189669444-2dcd3322-54fd-4065-a0a6-a05b5d562ccc.png)

**Comment by steveward** [comment]
@Maceo-p thanks for the issue. Are you working with any repositories that could be trying to fetch submodules?

**Comment by Maceo-p** [comment]
Nope, never used one of those

**Comment by sergiou87** [comment]
@Maceo-p do you have any repository in your list that could be hosted on git.isartintra.com?

**Comment by Maceo-p** [comment]
I looked at it and yes.
I deleted them and I don't have the problem anymore, thanks for your help
