### ISSUE TITLE
Publishing repository requires authentification

### ISSUE THREAD

**Issue by TuTAH1** [desktop/desktop#15279]
### The problem

I get "requires authentification" error when trying to publish repository on GutHub.com
![Скриншот 14-09-2022 125706_1](https://user-images.githubusercontent.com/15982179/190096137-59ead6c0-ff96-4300-a5b0-52db5ad55495.jpg)
But I already loggined in!
![Скриншот 14-09-2022 125837_1](https://user-images.githubusercontent.com/15982179/190096168-e53c8395-af01-4fc0-82b8-a104076eac37.jpg)

### Release version

3.0.5

### Operating system

Windows 10 Pro 21H2

### Steps to reproduce the behavior

1. Create a project
2. Go to the Github desktop, File → Add local repository → Choose...
3. "The directory does not appear to be a Git repository. Would you like to [create a repository](link) here instead?
4. Click "create a repository"
5. Create repository
6. Publish repository
7. see error

### Log files

[2022-09-14.desktop.production.log](https://github.com/desktop/desktop/files/9564098/2022-09-14.desktop.production.log)

### Additional context

This project was published via GitLab and had own .git files, but I deleted .git folder and .gitattributes file before making step 2

**Comment by sergiou87** [comment]
Hello @TuTAH1 ! 👋 

Not sure how this happened, but it looks like despite being signed in, the app doesn't have the token needed to authenticate your git operations. Could you log out and then log in again and see if that fixes the issue? 🤞

**Comment by TuTAH1** [comment]
> Could you log out and then log in again and see if that fixes the issue? 🤞

Yes, it fixed the issue

**Comment by steveward** [comment]
Glad to hear that got things working!
