### ISSUE TITLE
cygheap base mismatch error

### ISSUE THREAD

**Issue by Anish-M-code** [desktop/desktop#15270]
### The problem

Unable to clone or push any git repo

### Release version

3.0.7

### Operating system

Windows 10

### Steps to reproduce the behavior

Just trying to clone any repo gives error.
File> Clone Repository give any repo it shows error

### Log files

Cloning into 'C:\Users\Good Boy\Documents\GitHub\anish-m-code\anish-m-code'...
remote: Enumerating objects: 39, done.        
remote: Counting objects: 100% (39/39), done.        
remote: Compressing objects: 100% (26/26), done.        
remote: Total 39 (delta 12), reused 0 (delta 0), pack-reused 0        
Receiving objects: 100% (39/39), 9.30 KiB | 1.33 MiB/s, done.
Resolving deltas: 100% (12/12), done.
      0 [main] sh (17616) C:\Users\Good Boy\AppData\Local\GitHubDesktop\app-3.0.7\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x194B408/0x197B408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      1 [main] sh 396 dofork: child -1 - forked process 17616 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Good Boy\AppData\Local\GitHubDesktop\app-3.0.7\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      0 [main] sh (3316) C:\Users\Good Boy\AppData\Local\GitHubDesktop\app-3.0.7\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x194B408/0x199B408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
1323085 [main] sh 396 dofork: child -1 - forked process 3316 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Good Boy\AppData\Local\GitHubDesktop\app-3.0.7\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      0 [main] sh (11468) C:\Users\Good Boy\AppData\Local\GitHubDesktop\app-3.0.7\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x194B408/0x18CB408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
3459042 [main] sh 396 dofork: child -1 - forked process 11468 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Good Boy\AppData\Local\GitHubDesktop\app-3.0.7\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      0 [main] sh (15408) C:\Users\Good Boy\AppData\Local\GitHubDesktop\app-3.0.7\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x194B408/0x19BB408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
7772090 [main] sh 396 dofork: child -1 - forked process 15408 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Good Boy\AppData\Local\GitHubDesktop\app-3.0.7\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      0 [main] sh (8552) C:\Users\Good Boy\AppData\Local\GitHubDesktop\app-3.0.7\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x194B408/0x18FB408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
15915781 [main] sh 396 dofork: child -1 - forked process 8552 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Good Boy\AppData\Local\GitHubDesktop\app-3.0.7\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: Resource temporarily unavailable

Would you like to retry cloning ?

### Additional context

Tried looking for cygwin.dll couldn't find any. Tried rebooting it didn't work either.

**Comment by tsvetilian-ty** [comment]
@Anish-M-code thanks for reaching out! Usually, Mandatory ASLR causes cygheap errors. You can read more on the topic in [Enable Mandatory ASLR triggers cygheap errors](https://github.com/desktop/desktop/blob/67635154fa89e7ee408a9d7ff43eb8ed228a5368/docs/known-issues.md#enable-mandatory-aslr-triggers-cygheap-errors)

**Comment by b166er** [comment]
you need to exclude ASLR for git executables. This PowerShell Command helped me to solve this issue (run powershell window as administrator):

```ps1
Get-Item -Path "C:\Program Files\Git\usr\bin\*.exe" | %{ Set-ProcessMitigation -Name $_.Name -Disable ForceRelocateImages }
```

source: https://stackoverflow.com/a/48446934/3557623
