### ISSUE TITLE
github auto-uninstall

### ISSUE THREAD

**Issue by Xero00000000** [desktop/desktop#15278]
### The problem

after I installed github yesterday for working on unity with a group I found it not to be anywhere on my pc today and I needed to install it again, I dont know how or why it happened

### Release version

Version 3.0.8 (x64)

### Operating system

windows 10

### Log files

[2022-09-12.desktop.production.log](https://github.com/desktop/desktop/files/9561502/2022-09-12.desktop.production.log)
[2022-09-13.desktop.production.log](https://github.com/desktop/desktop/files/9561503/2022-09-13.desktop.production.log)

### Additional context

cant find where the program is on my pc even now? I pinned it to my taskbar

**Comment by sergiou87** [comment]
Looks like the app cannot find itself either, which is what causes this line in the logs you shared:
> Error: The application is missing a dependency it needs to check and install updates. This is very, very bad.

Do you have any antivirus that might be detecting GitHub Desktop as potentially dangerous and either deleting it or putting it in quarantine? We've seen that in the past with the git stuff bundled within GitHub Desktop, personally it's the first time to happen with the whole app 🤔

**Comment by Xero00000000** [comment]
I have the typical windows antivirus, havent downloaded a new one yet tho I've been considering to replace the windows one since it takes a lot of memory for no reason, an issue which is aparently very common

the antivirus usually notifies me when it quarantines, deletes, or otherwise finds something suspicious and it hasnt for github

I have been using yesterday night and today morning since I posted this, still cannot find where it is or anything, no matter how I look for it, I can find the folder with the repositories but that's all I can find

I had an issue with merge conflict and I was trying to solve it for hours, github couldnt locate git on my pc so I tried downloading it, once I did I found that it still couldnt locate it, and so I looked how to set up git with github

when I tried it, I found that I couldnt find git anywhere on my pc either, had to download it again and pin it ln my dashboard also, when I tried setting it up it couldnt find the folder where the passwords would be, and even when I set up the passwords it seemed not to create it, I couldnt find it anywhere just like with git and github

I dont know why this is happening, the programs very clearly are on my pc otherwise they wouldnt work nor be able to open from my desktop pins, but nothing seems to be able to call them or find them on my files, this is the first time this has happened to me that I can recall

(I am currently writing this on my phone, but I can send my newest logs later once I am back in my house)

**Comment by sergiou87** [comment]
> github couldnt locate git on my pc so I tried downloading it

In this case, GitHub Desktop uses its own bundled git, so it will never use the one you download separately. At that point I guess the app was already removed from your machine 🤯 

I wonder… did you have a banner saying `An updated version of GitHub Desktop is available and will be installed at the next launch. See what's new or restart GitHub Desktop`?

**Comment by Xero00000000** [comment]
no I didnt get anything like that

**Comment by sergiou87** [comment]
Thanks! At least we can rule out problems in the auto-update system 😌 

I'll leave this open labeled with `investigation-needed`, but I think this was probably something else external to GitHub Desktop 😕

**Comment by Xero00000000** [comment]
oki, thank you

I'm sending my logs but I dont think they'll be much help

[2022-09-13.desktop.production.log](https://github.com/desktop/desktop/files/9595081/2022-09-13.desktop.production.log)
[2022-09-14.desktop.production.log](https://github.com/desktop/desktop/files/9595083/2022-09-14.desktop.production.log)
[2022-09-18.desktop.production.log](https://github.com/desktop/desktop/files/9595084/2022-09-18.desktop.production.log)
[2022-09-12.desktop.production.log](https://github.com/desktop/desktop/files/9595085/2022-09-12.desktop.production.log)

**Comment by sergiou87** [comment]
As you say, I don't see anything relevant in those logs :(

Out of curiosity: what installer do you use? The EXE file or the MSI file?

**Comment by Xero00000000** [comment]
I used the EXE file I'm pretty sure

**Comment by steveward** [comment]
@Xero00000000 I'm going to close this issue out as stale, since unfortunately we were unable to diagnose any specific causes from the log files and information you shared. If you encounter this again please let us know and we can dig in further. Thanks for using GitHub Desktop!

**Comment by shyed2001** [comment]
On my Windows 11 Thinkpad Lenovo laptop the Github desktop took longer to get updated on 11/05/2024 night, on my office desktop Dell brand PC Core i7 2013 model, the Github desktop app got auto-deleted this morning, 12/05/204.
