### ISSUE TITLE
can you.   Open previous versions? 

### ISSUE THREAD

**Issue by caslanbigeyes** [desktop/desktop#15273]
It's not as easy to use as before. Before, there was no error when cutting branches. Now it keeps reporting errors. It's really bad. Our project is very large. At present, we haven't solved this verification

**Comment by caslanbigeyes** [comment]
I hope to open the previous version. Thank you. I hope to receive a version of about 2.5 and send it to my mailbox 781650249@qq.com

**Comment by caslanbigeyes** [comment]
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/53009552/189797974-b2a203b9-3e19-49d4-8e3c-e56b3c6b4f65.png">

**Comment by sergiou87** [comment]
Hi @caslanbigeyes 👋 

It seems you have a post-checkout hook (a script/check that runs after changing branches) that is not passing. Could you share your post-checkout hook (redacting any sensible parts of it) so we can take a look?
