### ISSUE TITLE
filter history

### ISSUE THREAD

**Issue by manweill** [desktop/desktop#1527]
need filter history

**Comment by shiftkey** [comment]
@manweill can you elaborate? There's a section in the [CONTRIBUTING.md](https://github.com/desktop/desktop/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion) about the sort of details that helps us understand more about these sorts of requests.

**Comment by manweill** [comment]
filter commit  history by name，account，tag

**Comment by joshaber** [comment]
Thanks @manweill! I'm gonna roll this into #1543. Feel free to follow along there.
