### ISSUE TITLE
[MacOS] GUI failing to render proreprly

### ISSUE THREAD

**Issue by ZeeWanderer** [desktop/desktop#15287]
### The problem

After the latest update GUI is glitchy - either shows a blank window the color of background or mostly blank window with some broken and unresponsive pieces of GUI here and there. Trying to interact with the window sometimes causes some GUI elements to appear briefly.

### Release version

3.0.8

### Operating system

MacOS 12.6 (21G115)

### Log files

[2022-09-15.desktop.production.log](https://github.com/desktop/desktop/files/9574492/2022-09-15.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/8377469/190385119-34b808ca-9e29-4c22-b07a-c175e37d2fd7.png)
![image](https://user-images.githubusercontent.com/8377469/190386644-070e62ca-6b92-41f1-9b19-3429077d986c.png)

### Additional context

I tried completely reinstalling the app - it didn't help.

**Comment by steveward** [comment]
@ZeeWanderer thanks for the issue. Can you try resetting the app to see if that helps?

1. Close GitHub Desktop
2. Delete all of the files under `~/Library/Application Support/GitHub Desktop/`
3. Restart GitHub Desktop

Unfortunately you will need to log in and add your repositories again via drag-and-drop. Sorry for the trouble. Let me know if that helps.

**Comment by ZeeWanderer** [comment]
After deleting `~/Library/Application Support/GitHub Desktop/` and restarting it, it now looks like this:
<details>
  <summary>Screenshot</summary>
  
![image](https://user-images.githubusercontent.com/8377469/190421439-fa4dc859-dd42-4746-ad52-180f3e110fdf.png)

</details>

[2022-09-15.desktop.production.log](https://github.com/desktop/desktop/files/9575827/2022-09-15.desktop.production.2.log)


BTW: Something similar recently happened to `Visual Studio Code`, same thing with the GUI. As far as i understand the common denominator seems to be Electron.

**Comment by sergiou87** [comment]
Could you press <kbd>Command</kbd>+<kbd>Option</kbd>+<kbd>I</kbd> while it's in that state? It should show Chromium's Developer Tools, and maybe in the `Console` tab you will see some kind of error (don't type anything there or the app will crash).

If you don't see anything, press <kbd>Command</kbd>+<kbd>R</kbd> from the Dev Tools to restart the app and hopefully see some error message then 🤞

**Comment by ZeeWanderer** [comment]
Developer tools are unresponsive and flickering, can't switch to `Console`. `Command`+`R` makes it flicker harder:
<details>
  <summary>Dev Tools Screenshot</summary>
  
![image](https://user-images.githubusercontent.com/8377469/190445632-731fa882-e260-411c-9c2d-a7f3a3a96463.png)

</details>

<details>
  <summary>Dev Tools Video</summary>
  
[![image](https://user-images.githubusercontent.com/8377469/190445632-731fa882-e260-411c-9c2d-a7f3a3a96463.png)](https://user-images.githubusercontent.com/8377469/190446993-a05f855f-d3d7-4346-a51f-93928933601b.mp4)

</details>

**Comment by sergiou87** [comment]
That is… interesting 😐 

Could you please try the previous 3.0.7 and see if that one works?
For Apple silicon (arm64): https://centralreleases.blob.core.windows.net/github-desktop/releases/3.0.7-38727e62/GitHubDesktop-arm64.zip
For older Macs (x64): https://centralreleases.blob.core.windows.net/github-desktop/releases/3.0.7-38727e62/GitHubDesktop-x64.zip

**Comment by ZeeWanderer** [comment]
@sergiou87 `3.0.7` works fine.
[2022-09-15.desktop.production.log](https://github.com/desktop/desktop/files/9577040/2022-09-15.desktop.production.3.log)

Is there a way i can prevent autoupdate for the time being without keeping the app in `read-only` volume?

**Comment by sergiou87** [comment]
I'm afraid it's not possible 😢 Version 3.0.8 includes an upgrade in Electron from v17 to v19 (see #15239 )

Could you run v3.0.8 from the terminal like `/Applications/GitHub\ Desktop.app/Contents/MacOS/GitHub\ Desktop` and see if the app outputs something there?

Thanks a lot for your help and patience 🙇‍♂️🙇‍♂️🙇‍♂️

**Comment by ZeeWanderer** [comment]
@sergiou87 
output:
```
objc[2173]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb4c3caec8) and /Applications/GitHub Desktop.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x106b24ce0). One of the two will be used. Which one is undefined.
```

**Comment by niik** [comment]
Hey @ZeeWanderer, could you try disabling hardware acceleration by launching GitHub Desktop from the terminal with the following command

```
GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1 open -a "GitHub Desktop"
```

**Comment by ZeeWanderer** [comment]
@niik 
With disabled acceleration 3.0.8 works as expected.

**Comment by niik** [comment]
Cool, at least we've narrowed it down somewhat then. What machine are you running on? We see this on occasion but it's very rare and usually caused by either a hardware issue or a graphics driver issue (on Windows). Have you restarted your machine recently? You could try following any of the numerous [guides](https://www.lifewire.com/troubleshooting-mac-display-problems-4121097) out there on troubleshooting your macOS graphics.

**Comment by ZeeWanderer** [comment]
@niik Well, it is actually a VMware VM. I know, should have told that from the start, but in my experience that tends to get the issue closed quickly with a `not our problem` tag equivalent and no help or diagnostics at all. 
Thank you for helping me.

Btw, seems like all updated electron apps on VM have the same problem, at least all those I use. Having an option to disable `Hardware Acceleration` on macos, preferably from the system menu since it is not Electron and therefore not affected, might be a good idea, just in the case of users like me.
