### ISSUE TITLE
I get this error when pushing a <1MB file: The remote disconnected. Check your Internet connection and try again.

### ISSUE THREAD

**Issue by Ahmedsk143** [desktop/desktop#15285]
### The problem

I get this error when trying to upload a less than 1 MB file (The remote disconnected. Check your Internet connection and try again.)
The file type is mp3
And it shows when I try to push anything that is larger than 500kb 

What I tried already:
1. Cleared cache and cookies
2. Tried Chrome, Firefox, Edge, Incognito
3. Changed my IPv4 to google DNS
4. Disabled my adblocker extension
5. Tried a different network connection

I want to mention that I upload files all the time on different platforms, including Linkedin, google drive, youtube, and more 

### Release version

Version 3.0.7 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Add some audio tracks to your local repo
2. Commit and push

### Log files

[2022-09-14.desktop.production.log](https://github.com/desktop/desktop/files/9571773/2022-09-14.desktop.production.log)
[2022-09-15.desktop.production.log](https://github.com/desktop/desktop/files/9571774/2022-09-15.desktop.production.log)

### Screenshots

![Captured by Ahmed Khalil 385](https://user-images.githubusercontent.com/52580137/190313779-5a8f3ce9-6abe-4de2-8157-acc557b4e111.png)

**Comment by sergiou87** [comment]
Hello @Ahmedsk143 ! 👋 

I see this in your logs:
```
2022-09-15T04:12:35.364Z - error: [ui] `git -c credential.helper= push origin main:main --progress` exited with an unexpected code: 1.
stderr:
Enumerating objects: 5, done.
Counting objects:  20% (1/5)
Counting objects:  40% (2/5)
Counting objects:  60% (3/5)
Counting objects:  80% (4/5)
Counting objects: 100% (5/5)
Counting objects: 100% (5/5), done.
Delta compression using up to 4 threads
Compressing objects:  33% (1/3)
Compressing objects:  66% (2/3)
Compressing objects: 100% (3/3)
Compressing objects: 100% (3/3), done.
Writing objects:  25% (1/4)
Writing objects:  50% (2/4)
Writing objects:  75% (3/4)
Writing objects: 100% (4/4)
Writing objects: 100% (4/4), 939.62 KiB | 85.42 MiB/s, done.
Total 4 (delta 1), reused 0 (delta 0), pack-reused 0
error: RPC failed; curl 55 Send failure: Connection was aborted
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date

(The error was parsed as 4: The remote disconnected. Check your Internet connection and try again.)
```

Unfortunately this type of error can often just be caused by a connection issue. Are you trying to push a large number of files? Are you on a reliable network? Are you behind any sort of proxy or firewall? If you can try pushing on a different network that would help narrow down the issue.

Some users have also had success switching to use SSH instead of HTTPS. If you're interested in learning how to set a new SSH key you can follow [this guide](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent).

**Comment by Ahmedsk143** [comment]
> 

No, I'm trying to push a **single** file at a time.
Yes, My network is **reliable**, recently uploaded some videos on LinkedIn and an online conversion tool, and uploading was fast with no problems.
I'm **not** behind any proxy server and my windows firewall is off.
I've tried my mobile network but the signal is weak so it can't be conclusive, but I'll try a public network or visit a friend and test it out.

Using SSH is an alternative that may work and may not but it is not a solution, but thanks for pointing it out.

**Comment by steveward** [comment]
@Ahmedsk143 if you're going to be pushing asset files like mp3s I would recommend looking into using Git LFS, since it handles those types of files better. See [this article ](https://docs.github.com/en/repositories/working-with-files/managing-large-files) for information. GitHub Desktop includes Git LFS support. You get 1GB of free storage and bandwidth per month on GitHub.

**Comment by Ahmedsk143** [comment]
> @Ahmedsk143 if you're going to be pushing asset files like mp3s I would recommend looking into using Git LFS, since it handles those types of files better. See [this article ](https://docs.github.com/en/repositories/working-with-files/managing-large-files) for information. GitHub Desktop includes Git LFS support. You get 1GB of free storage and bandwidth per month on GitHub.

I know about LFS, but 1MB is not large, is it?
I somehow managed to upload the files via the web version, so it is not urgent to upload the files.
I just want help for future uploads; because this happens with image files as well as any file that is near the ~500KB even if it is a heavy code file.

I'd appreciate any suggestions or things to try out

**Comment by sergiou87** [comment]
@Ahmedsk143 it's hard to say, because it seems to be `git` what's somehow failing to push those files. Have you tried running `git push` from a terminal and see if that works? 🤔

**Comment by Ahmedsk143** [comment]
You were right the problem was the network spsificaly my WLAN card. 
I connected via a LAN cable and everything is pushed successfully
Thank you all
