### ISSUE TITLE
ERROR UNIX [Permission Denied]

### ISSUE THREAD

**Issue by EuCarrion** [desktop/desktop#15288]
Hi!
I downloaded GitHub Desktop and haven't been able to login from the app. 
GitHub Desktop Version 3.0.8 (x64)
macOS High Sierra 10.13.6

Every time I try to log in it opens the browser (I've already tried with chrome, firefox and Safari with the same results), and the page it opens asks me if I want to allow it to open the GitHub Desktop, to which I click "ALLOW" and then I get a pop window on the program with the following message: ERROR UNIX [Permission Denied].

I've read a two threads here with a similar problem. I checked the permissions of the folder the app was in, and made sure it is read & write. But I'm still getting the same Error when I try to sign in. 

Can you help solve this please?

GitHub Desktop Version: Version 3.0.8 (x64)
[2022-09-15
![Screen Shot 2022-09-15 at 9 39 46 AM](https://user-images.githubusercontent.com/113618060/190487616-8a73c4dd-5eb7-491e-bb10-0a37f0c88ab4.png)
.desktop.production.log](https://github.com/desktop/desktop/files/9578218/2022-09-15.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @EuCarrion. Is GitHub Desktop in the `/Applications` directory on your machine? Is this a completely fresh install, or did it possibly happen after an update to the app?

We just released 3.0.8 so it would be helpful if you could try 3.0.7 to see if that works. You can download that from here:

https://centralreleases.blob.core.windows.net/github-desktop/releases/3.0.7-38727e62/GitHubDesktop-x64.zip

**Comment by EuCarrion** [comment]
Hi Steve!
Thank you for your quick answer. It is a completely fresh install as you
called it.
I will download the older version and let you know how it goes.
fingers crossed!

Eu

**Comment by EuCarrion** [comment]
I just tried with the older version of the program and got the same error
message. :(

**Comment by sergiou87** [comment]
I think this error is logged here: https://github.com/desktop/desktop/blob/177c480a46bed850f569afcd358931f808d35c8e/app/src/lib/stores/accounts-store.ts#L85
So the problem is when the app tries to store your GitHub credentials (or more specifically a token associated to your GH user and GitHub Desktop). 

Do you know if you have access to the keychain with your user? Maybe poke around with the `Keychain Access` app on macOS and see if you can navigate and see passwords and certificates there 🤔

**Comment by ahudock** [comment]
OP hasn't responded but I'm having the same issue with Version 3.1.5 (x64) (macOS 12.6.1 (21G217)). My user does have Keychain Acccess.

Edit: More...this is a fresh install, extracted and moved to /Applications.
