### ISSUE TITLE
Make "merge conflict resolving" modal wider

### ISSUE THREAD

**Issue by ralphjsmit** [desktop/desktop#15295]
### The feature request

Probably a very small change, but it would be nice if the modal to resolve merge conflicts would become wider if there is the space. Currently many filenames are truncated, so this makes it very difficult to look up the correct file in projects with multiple identical filenames in different folders.

### Proposed solution

This modal would become wider. This would benefit people who have identical filenames in their project, but in different folders.

<img width="561" alt="Schermafbeelding 2022-09-16 om 18 32 24" src="https://user-images.githubusercontent.com/59207045/190687065-74bafbcd-896f-48f9-84cb-697b780090c4.png">

### Additional context

Thanks!

**Comment by steveward** [comment]
Thanks for the feedback @ralphjsmit. For reference you can hover over the filename to see the full path -- is that a helpful solution? 

This is being tracked in https://github.com/desktop/desktop/issues/6851, so I'm going to close this out and reference this issue there.

**Comment by ralphjsmit** [comment]
@steveward Thanks a lot for the fast response and pointing that hovering also works! Hadn't figured that out yet, but that's certainly helpful. Thanks!
