### ISSUE TITLE
actions unrelated to welcome wizard are blocked while welcome wizard is active

### ISSUE THREAD

**Issue by BrianHenryIE** [desktop/desktop#1529]
### Version

**GitHub Desktop version:** 0.5.3

**OS version:** MacOS 10.12.3

### Steps to Reproduce

1. do a fresh install of Desktop
1. select the top `GitHub Desktop` menu item
1. click Preferences

**Expected behaviour:** application shows Preferences

**Actual behaviour:** nothing

**Comment by shiftkey** [comment]
> Another issue: at this screen, using the main menu (GitHub Desktop) and Preferences doesn't work at all. Neither does About GitHub Desktop. 

Can you clarify what you mean here by "doesn't work at all"? Was the entire menu unresponsive? Was the menu interactive (it displayed, you could hover over items), but nothing seemed to occur when you clicked the menu item?

> When first launching the desktop client on the page titled Sign into GitHub.com, I entered my username, pressed the tab key to move to the password box and Forgot Password became the focused element. The expected behaviour is for the password input to become active, then the Sign In button.

#1513 has been opened to change this. Let's see where that ends up.

**Comment by BrianHenryIE** [comment]
As I tried to use the menu to find the GitHub Desktop version, the menu appeared, but upon selecting About GitHub Desktop or Preferences, nothing happened. So, yes, it was interactive, I could hover over and it would highlight, things appeared normal, but when I clicked, the menu disappeared (as felt normal) but the expected dialog box did not appear.

My apologies for missing 1513 – I looked through the first six pages of issues but overlooked it.

**Comment by BrianHenryIE** [comment]
Here's a quick video of the menu not working:
https://www.youtube.com/watch?v=mJD2O9BHBus

**Comment by shiftkey** [comment]
Thanks for the video. The root cause of this is that we're ignoring menu events while in the welcome wizard (because we want you to complete the wizard).

That's Not Great, and we probably should disable or show a different menu at that time (because all those options aren't available).

**Comment by shiftkey** [comment]
@BrianHenryIE I updated the initial description to reflect the issue with the menu. Let me know if I missed anything.

**Comment by niik** [comment]
> That's Not Great, and we probably should disable or show a different menu at that time (because all those options aren't available).

Yup, we should incorporate this into [getMenuState](https://github.com/desktop/desktop/blob/2435ba5f9cb4c0474c15ade8374b162f904638cc/app/src/lib/menu-update.ts#L71) so that it knows whether we're in the welcome flow and can disable (or preferably hide) top level menu items that don't do anything.
