### ISSUE TITLE
down arrow in history not stable

### ISSUE THREAD

**Issue by iking7** [desktop/desktop#15290]
### The problem

In branch history, if you hold the up arrow key you can scroll through all of your history and when the top is reached it will cycle from the bottom again. If you try to do the same holding the down arrow key it will not cycle starting from the top and you will need to perform a click on a history item from your history list before you can select an item again and use the down arrow key to navigate through the list again.

### Release version

3.0.6

### Operating system

Mac OS 12.6

### Steps to reproduce the behavior

<img width="646" alt="Screen Shot 2022-09-15 at 6 47 07 PM" src="https://user-images.githubusercontent.com/28670203/190521728-20ca5bd2-d0a4-4d6a-9b1c-d416483bd2ec.png">

### Screenshots

in repro step

**Comment by IMTHETRUTH2** [comment]
`README.md`

**Comment by steveward** [comment]
Thanks for the issue @iking7, this is being tracked in https://github.com/desktop/desktop/issues/7679 so I'm going to close this out.
