### ISSUE TITLE
Diff additions and subtracts icon has too little right margin

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#15298]
### The problem

I noticed the diff addition/subtraction markers no longer have enough right margin

### Release version

3.0.8 (arm64)

### Operating system

macOS 12.6 (21G115)

### Steps to reproduce the behavior

1. Make a change
2. Select the change in Desktop
3. Review the diff

###### Changes 

<img width="1083" alt="Screen Shot 2022-09-16 at 11 27 46 AM" src="https://user-images.githubusercontent.com/1715082/190707419-88ff4df2-a5c0-47e0-97f8-12a567c5941c.png">

###### History 

<img width="1281" alt="Screen Shot 2022-09-16 at 11 30 48 AM" src="https://user-images.githubusercontent.com/1715082/190707653-810a9741-7f37-4130-bf98-843eac87efee.png">

###### Earlier version of Desktop

<img width="511" alt="Screen Shot 2022-09-16 at 11 32 21 AM" src="https://user-images.githubusercontent.com/1715082/190707897-b6ca47df-e54f-48c8-a31e-a2f14e548ee0.png">

### Additional context

I'm unsure if this is a new problem or if I just started paying attention.

**Comment by iAmWillShepherd** [comment]
I think it's worth adding at least a few pixels worth of margin, even if there are no spaces in the diff, because, at a glance, the `+/-` appear to be part of the change.

Maybe distinguishing the `+/-` in the UI would solve ☝🏽 perhaps something like a sub gutter could work. Although, I do understand if that may not be technically feasible since the `+/-` markers are returned in the diff computation. 

**E.g.,**

```diff
diff --git a/profile/README.md b/profile/README.md
index 9cb3140..d0484cb 100644
--- a/profile/README.md
+++ b/profile/README.md
@@ -40,4 +40,4 @@ Get in touch with us or learn more about OneSignal through the channels below.

 # :rocket: Careers

-Interested in delivering customer messages at scale? Check out our [**Careers**](http://onesignal.com/careers) page and join OneSignal!
+Are you interested in delivering customer messages at scale? Check out our [Careers](http://onesignal.com/careers) and join our fast-growing team and help us continue to build the most widely-used customer engagement solution!
```

**Comment by iAmWillShepherd** [comment]
I am closing this since the rendering behavior doesn't affect my ability to copy and paste content from the diff.

**Comment by iAmWillShepherd** [comment]
Re-opening because someone on my stream said they see spaces for markdown files. Will leave it to you to confirm whether this is a bug 😅

**Comment by niik** [comment]
:wave: @iAmWillShepherd!

> Re-opening because someone on my stream said they see spaces for markdown files. Will leave it to you to confirm whether this is a bug 😅

My guess here is that they were viewing diffs using the split diff mode which does add an "artificial" margin next to the diff line status.

<img width="101" alt="image" src="https://user-images.githubusercontent.com/634063/190973877-a89f0aaa-ff68-4fde-bac6-48830bd46463.png">

> I think it's worth adding at least a few pixels worth of margin, even if there are no spaces in the diff, because, at a glance, the `+/-` appear to be part of the change.

I agree, and that would also match GitHub.com's behavior.

<img width="108" alt="image" src="https://user-images.githubusercontent.com/634063/190973586-6426f8c0-71e6-46ab-989f-04ff5f9ef26c.png">

I'll mark this as a bug but since we're planning on rendering the unified diff using the split diff engine in the future I would assume that we won't be pursuing a solution for CodeMirror but instead wait until we can get the split diff engine ready.

**Comment by niik** [comment]
Hey @iAmWillShepherd, going through a bunch of old issues and came across this. Hope you're doing great!

We replaced CodeMirror as the engine for rendering unified diffs in v3.3.5 so both the unified diff and the split diff should behave the same now and add some margin between the diff line status and the contents.

:v:
