### ISSUE TITLE
Update from upstream/master perpetually greyed out

### ISSUE THREAD

**Issue by guidezpl** [desktop/desktop#15299]
### The problem

The `Update from upstream/master` menu is perpetually greyed out. Is this a bug or a problem with my setup?

```
git remote -v
origin	https://github.com/guidezpl/flutter.git (fetch)
origin	https://github.com/guidezpl/flutter.git (push)
upstream	https://github.com/flutter/flutter.git (fetch)
upstream	https://github.com/flutter/flutter.git (push)
```

### Release version

Version 3.0.8 (x64)

### Operating system

macOS

### Log files

[2022-09-16.desktop.production.log](https://github.com/desktop/desktop/files/9586793/2022-09-16.desktop.production.log)

### Screenshots

<img width="335" alt="Screenshot 2022-09-16 at 21 44 05" src="https://user-images.githubusercontent.com/6655696/190718270-7e18f4ef-86d3-420d-b1b8-f447017b5b21.png">

The branch exists and I'm able to do it manually:
<img width="460" alt="Screenshot 2022-09-16 at 21 45 26" src="https://user-images.githubusercontent.com/6655696/190718476-f1cb2f5f-2558-4b76-bea3-347a137f8d84.png">

**Comment by niik** [comment]
Hey @guidezpl, thanks for reaching out and sorry for the inconvenience here. I'm glad you found a workaround. I've opened #15309 which should hopefully address this problem.

**Comment by guidezpl** [comment]
Thanks!
