### ISSUE TITLE
The changes I pushed in Github Desktop are not showing up in the website

### ISSUE THREAD

**Issue by Raza1996** [desktop/desktop#15303]
### The problem

I made a simple change to my code, just modified the placement of some div and the change showed up in Github Desktop. I pushed them without a hassle but I can't see them on my website. It's been around 10 hours now and still no changes.

### Release version

Version 3.0.8 (x64)

### Operating system

Windows 11

**Comment by niik** [comment]
Hey @Raza1996, thanks for reaching out. Are you able to see your changes when you look at your repository on GitHub.com? Once you push your changes GitHub Desktop has no control over what happens with them so if your changes make it up to GitHub.com you'll have to reach out  If you have a general support question please check out [GitHub support](https://support.github.com) or the [GitHub Community Forum](https://github.community).

Best of luck!

**Comment by Raza1996** [comment]
I can only make changes when I manually add files to the GitHub website
repository. Pushing changes on the desktop app does not do anything.

**Comment by steveward** [comment]
Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Raza1996** [comment]
Sent from Mail for Windows From: Steve WardSent: September 20, 2022 11:11 AMTo: desktop/desktopCc: Raza1996; MentionSubject: Re: [desktop/desktop] The changes I pushed in Github Desktop are not showing up in the website (Issue #15303) Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by steveward** [comment]
@Raza1996 you won't be able to upload a log file via email reply, you will need to add it as an attachment in an issue comment.

**Comment by Raza1996** [comment]
[2022-09-20.desktop.production.log](https://github.com/desktop/desktop/files/9620286/2022-09-20.desktop.production.log)
[2022-09-21.desktop.production.log](https://github.com/desktop/desktop/files/9620287/2022-09-21.desktop.production.log)
[2022-09-17.desktop.production.log](https://github.com/desktop/desktop/files/9620288/2022-09-17.desktop.production.log)
[2022-09-18.desktop.production.log](https://github.com/desktop/desktop/files/9620289/2022-09-18.desktop.production.log)
[2022-09-19.desktop.production.log](https://github.com/desktop/desktop/files/9620291/2022-09-19.desktop.production.log)

**Comment by Sherry3552** [comment]
I have made changes in android studio, but there's no single change in github desktop. anyone plzz guide me

**Comment by One-eyed-warrior** [comment]
my changes aren't being reflected in the github repo when i pushed through the desktop app, what went wrong? a week's worth of changes are just not there

**Comment by steveward** [comment]
@One-eyed-warrior please open a new issue and fill out the template so we can assist you further. Thanks!

**Comment by mcamper** [comment]
Your issue may be you're missing ".gitattributes" inside your repository files. Make sure you have that added.
