### ISSUE TITLE
I tried made a multilingual platform

### ISSUE THREAD

**Issue by yasuking0304** [desktop/desktop#15304]
# I tried made a multilingual platform
- If it is good, I would like to make a pull request.

# Pros
- Assist more foreign engineers
- The language part is shared by cli and render

# Cons
- In the current structure, there is no choice but to embed the language and build it without extracting the language file as a separate file.
- There are more than 150 modified files this time, and there is too much modification risk to respond at once
- LocalStorage cannot be used because the source is shared between cli and render

# Check OS
- Windows 10
- MacOS Monterey (x64)

# Base version
Version 3.0.8

# Snap shot
![WS000009](https://user-images.githubusercontent.com/111163564/190899825-15bd7fc3-7e9f-45c8-b197-229a7d0999ca.JPG)

![スクリーンショット 2022-09-18 20 19 06](https://user-images.githubusercontent.com/111163564/190899830-d4262bb7-4c5a-4f53-bafb-afed4606840b.png)

# Used OSS
i18next , i18next-parser

# Flow
1. If there is an environment variable "GITHUB_DESKTOP_LANG", set it to that language
2. If not, get the language with "Intl.NumberFormat().resolvedOptions().locale"
3. Set to "en" if not in the judgment table

# Yet
- Only Japanese has been translated
- Error messages are caught by jest, so they are not translatable.
- Date check format in test, so the multilingual part is passed with en-US setting
- Procedures for creating multilingual translation documents have not been created.

# this repository
https://github.com/yasuking0304/desktop

**Comment by niik** [comment]
Hey @yasuking0304, thanks for reaching out. That's some impressive work you've done there with translating to Japanese. We agree with you that translating the application will lead to more people being able to use the application comfortably. It's really interesting to see how you chose to set up the project and I hope we can use it for inspiration as we move closer to being able to localize the application.

As I'm sure you're aware, however, localizing an application goes far beyond the initial translation efforts. We'd have to have a process in place for translating new resources on-demand in time for our releases and we don't have that just yet but it's something we're looking into.

I've sent a link to your project to all the engineers working on GitHub Desktop. Thank you so much for sharing this!
