### ISSUE TITLE
Seems that I can't configure the "Root" folder to add existing repositories

### ISSUE THREAD

**Issue by mWaltari** [desktop/desktop#1530]
Seems that I can't configure the "Root" folder to add existing repositories

In older program I could jsut point out the directory and it would add all the projects already there.

Or it is not very clear how to do that...

**Comment by shiftkey** [comment]
@mWaltari yes, the ability to "scan" for repositories hasn't been ported across.

You can drag and drop folders onto the application if you want a quick way to add the repositories you're interested in.

**Comment by niik** [comment]
Gonna close this out as the original question has been answered but feel free to open a separate issue if this is something you would like to see implemented!

**Comment by niik** [comment]
xref #1574
