### ISSUE TITLE
Add local repo doesnt work

### ISSUE THREAD

**Issue by lukasareskog** [desktop/desktop#15305]
### The problem

When im trying to add a local repo, located under C:\Users\lukas\source\repos\project 
github desktop somehow thinks it's located under C:\Users\lukas
![image](https://user-images.githubusercontent.com/79976921/190901465-9298fcf5-180f-413f-a329-1fbb3baf709b.png)

That makes it import 121477 files. Idk why it just doesn't want to go further than users. 

### Release version

3.0.8

### Operating system

Windows 11

### Screenshots

![image](https://user-images.githubusercontent.com/79976921/190901520-8cf1cdc9-3fdb-4c5b-b7bc-6115d74e547d.png)
![image](https://user-images.githubusercontent.com/79976921/190901534-9194c92b-4f1e-404c-9633-920f61ab4cba.png)

**Comment by niik** [comment]
Hey @lukasareskog, without more context it's hard to guess at the problem but if I had to I would guess that the directory you're trying to import (`C:\Users\lukas\source\repos\project`) is not yet a Git repository (i.e. there's no .git folder there) and at the same time you've accidentally made your home directory (`C:\Users\lukas`) into a .git repository. You should be able to verify this by checking to see if there's a `.git` folder in your home directory (note that it may be hidden so you'd need to turn [enable showing hidden files and directories](https://support.microsoft.com/en-us/windows/show-hidden-files-0320fe58-0117-fd59-6851-9b7f9840fdb2)).

Assuming making your home directory into a git repository was a mistake (it usually is) you can either delete the `.git` folder or rename it to something like `_git` which should resolve the issue for you.

Hope that helps!
