### ISSUE TITLE
Pull all repositories with one click

### ISSUE THREAD

**Issue by nirbd** [desktop/desktop#15310]
### The feature request

After not working for a while I need to go through all the repositories and pull changes. could be nice to do it in one click.
Probably most users will enjoy this time saver very much

### Proposed solution

see above

### Additional context

see above

**Comment by steveward** [comment]
Thanks for the issue @nirbd. GitHub Desktop automatically fetches and fast-forwards your repositories in the background (see [this explanation](https://github.com/desktop/desktop/issues/4950#issuecomment-397694857). Adding a `Pull all` has been previously discussed in #2460 and #6482, but at this time we have not decided to move forward with this request. There are also scenarios where problems can arise when performing a pull (like merge conflicts).

I'm going to close this out, but let me know if you have any further questions.
