### ISSUE TITLE
Github desktop cannot pull or push to github repositories

### ISSUE THREAD

**Issue by mys2kor** [desktop/desktop#15312]
### The problem

When I try to pull or push, I get error in Github Desk top. The error messages very here are a couple of them. It was working fine just minutes ago & it does not work anymore!

`fatal: unable to access 'https://github.com/bosch-bgsw-top99-ops/dochub-customer-approval.git/': schannel: failed to receive handshake, SSL/TLS connection failed`

`fatal: unable to access 'https://github.com/bosch-bgsw-top99-ops/dochub-customer-approval.git/': Received HTTP code 503 from proxy after CONNECT`

![grafik](https://user-images.githubusercontent.com/109787441/190992174-e9784d28-31bf-4464-b8bc-643b10ad3022.png)

### Release version

3.0.7

### Operating system

Windows 10

### Log files

[2022-09-19.desktop.production.log](https://github.com/desktop/desktop/files/9597845/2022-09-19.desktop.production.log)

**Comment by steveward** [comment]
@mys2kor thanks for the report. The number of network errors I'm seeing in the log seem to point to a proxy/firewall issue. Are you behind a proxy/firewall on this machine?

**Comment by mys2kor** [comment]
@steveward Yes. I work behind the firewall of my company and I use the proxy to connect the applications to the internet (I use https://github.com/genotrance/px proxy). 
Please note that, I have been using GitHub desktop for more that a month now in the same environment & it worked fine. Just yesterday it started throwing these error (i have changed any network or proxy settings).

I tried pulling a Repo & it worked!!!! Again, I did not do ANY network or proxy setting changes! You can close this issue if you like since the application started working again but may be look into what was going on yesterday. Thanks.

**Comment by niik** [comment]
Hey @mys2kor, chances are there was some temporary problem with your proxy which we don't have any control over. I'm happy to hear you were able to get it working again!
