### ISSUE TITLE
Middle mouse button starts a squash operation

### ISSUE THREAD

**Issue by aybe** [desktop/desktop#15313]
### The problem

If somehow you happen to click with middle mouse button to start scrolling without using mouse wheel and you move before the cursor mouse changes to scroll, the software will consider it as a drag operation for squash.

This is nasty because many times you want to scroll down without using the mouse wheel, you have to be extremely careful to release the middle button else you'll inadvertently do some squash.

This behavior is unlike any other software, check out your web browser for instance.

### Release version

Version 3.0.8 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. go to history
2. hold middle button
3. move the mouse down
4. history is scrolled down but commit is also dragged for squash

### Log files

[2022-09-19.desktop.production.log](https://github.com/desktop/desktop/files/9600248/2022-09-19.desktop.production.log)

### Screenshots

![GitHubDesktop_QDncXBAYbk](https://user-images.githubusercontent.com/1537591/191051765-a3c37509-5bba-41a3-8d1a-9eccd10cbe6c.gif)

**Comment by ChiriVulpes** [comment]
I believe this one could be fixed by simply using this early return when `event.button === 1` here: 
https://github.com/desktop/desktop/blob/0af1e999b480cbe6542d0e98eedfb1703ddb080c/app/src/ui/lib/list/list.tsx#L1070

As someone who prefers middle click to scroll this bug catches me all the time, so I'd be super happy if it could be fixed

**Comment by BlackStartx** [comment]
Thanks for fixing this~ ^-^ 🌺 

Probably the most invasive issue I've ever found using the app, glad it's gone!
Have a nice day! ❤️ 
###### Came here just to say thanks after reading the changelog :3
