### ISSUE TITLE
Press the Enter key to push a commit while the user selected the Commit message textbox

### ISSUE THREAD

**Issue by andrewhong04** [desktop/desktop#15316]
### The feature request

Press the Enter key to push a commit while the user selected the Commit message textbox

### Proposed solution

It's a way for the user to keep their hand on the keyboard to increase productivity.

**Comment by niik** [comment]
Hey @novialriptide, thanks for reaching out! We totally agree that keyboard productivity is important. By GitHub convention you can press Command+Enter (or Ctrl+Enter) while writing your commit message to create the commit. 


For more keyboard shortcuts please see our [keyboard documentation](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/overview/keyboard-shortcuts#branches)

**Comment by andrewhong04** [comment]
I should've known this before creating this issue.. Sorry.
