### ISSUE TITLE
Github For Desktop White Green on MacOS Mojave VM

### ISSUE THREAD

**Issue by Saheber** [desktop/desktop#15324]
### The problem

When I installed the application and opened it up I could see only a white screen and nothing else, I even tried developer tools but that would just show black screen and no text. I even tried to use the command of disabling hardware acceleration but couldn't find where to paste. My septs are 8gb Ram and a i3 3220 which has shared 2 and 2 in Vm Ware Pro

### Release version

Latest

### Operating system

MacOS

### Screenshots

Screenshot 2022-09-21 at 6.50.45 AM

**Comment by niik** [comment]
Hey @Saheber, thanks for reaching out. This sounds very similar to https://github.com/desktop/desktop/issues/15287 who were also experiencing graphics issues while running in a VM. Could you try disabling hardware acceleration by launching GitHub Desktop from the terminal with the following command and see if that solves your issue?

```
GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1 open -a "GitHub Desktop"
```

**Comment by Saheber** [comment]
Ya I tried to use this but can u explain me how do I use this Command
elaborately as I am kinda newbie in this stuff

**Comment by steveward** [comment]
@Saheber you can open up `Terminal.app` and cut and paste the command directly in there to see if that gets things working.

**Comment by Saheber** [comment]
Thanks, I'll check it out. And will update u soon Thanks again for such
quick response. Appreciated.

**Comment by gittethis** [comment]
Same issue here on Monterey 12.6.
The workaround works, thou !

**Comment by Saheber** [comment]
Done Mates The Issue is resolved

**Comment by opxdelwin** [comment]
Can I have like a default launch parameter to disable hardware acceleration? Can't be using terminal always to launch GitHub
