### ISSUE TITLE
error: RPC failed; curl 56 Failure when receiving data from the peer

### ISSUE THREAD

**Issue by agnibi** [desktop/desktop#15333]
### The problem

I'm trying to clone a repository with URL from Azure Git Hub.

After some time I got error:

Cloning into 'C:\Github\HMDP'...
remote: Azure Repos        
remote: Found 172304 objects to send. (2057 ms)        
Receiving objects: 100% (172304/172304), 13.17 GiB | 7.79 MiB/s, done.
error: RPC failed; curl 56 Failure when receiving data from the peer
Resolving deltas: 100% (51828/51828), done.

### Release version

3.0.8 (x64)

### Operating system

Windows 10

### Log files

stderr:
Cloning into 'C:\Github\abcde'...
remote: Azure Repos        
remote: 
remote: Found 172304 objects to send. (2057 ms)        
Receiving objects:   0% (1/172304)
Receiving objects:   1% (1724/172304)
Receiving objects:   2% (3447/172304)
Receiving objects:   3% (5170/172304)
Receiving objects:   4% (6893/172304)
Receiving objects:   5% (8616/172304)
Receiving objects:   6% (10339/172304)
Receiving objects:   7% (12062/172304)
Receiving objects:   8% (13785/172304)
Receiving objects:   9% (15508/172304)
Receiving objects:  10% (17231/172304)
Receiving objects:  11% (18954/172304)
Receiving objects:  12% (20677/172304)
Receiving objects:  13% (22400/172304)
Receiving objects:  14% (24123/172304)
Receiving objects:  15% (25846/172304)
Receiving objects:  16% (27569/172304)
Receiving objects:  17% (29292/172304)
Receiving objects:  18% (31015/172304), 8.00 MiB | 15.31 MiB/s
Receiving objects:  19% (32738/172304), 8.00 MiB | 15.31 MiB/s
...
...
...
Receiving objects: 100% (172304/172304), 13.17 GiB | 8.02 MiB/s
Receiving objects: 100% (172304/172304), 13.17 GiB | 7.79 MiB/s, done.
error: RPC failed; curl 56 Failure when receiving data from the peer

**Comment by sergiou87** [comment]
Hello @agnibi !

We've seen this issue in the past when users have some kind of antivirus, firewall or proxy installed. If so, trying to disable or properly configure them usually gets things working. We've also seen this when users have unstable internet connection.

Please, let us know if that's your case!

**Comment by agnibi** [comment]
Hi,

thanks for quick reply. 

As this is my company PC, there is antivirus running and PC is behind a firewall. I cannot change that.

I'm not using a proxy and my internet connection is stable. 

Receiving objects is 100% and the issue happens afterwards. Any ideas what I could do to get it running?

**Comment by sergiou87** [comment]
Only things I can think are:
1. Trying to clone from command line to see if you get the same error (my bet is you will)
2. Ask a coworker to clone it to see if it works on a different company machine.

That will get us some more data points 🤞

**Comment by bjlay2000** [comment]
Hi, I am actually having the same error.  I am testing out tools for non technical users.  Using Sourcetree and also command line both work without issues.

I am cloning from an Azure DevOps url using PAT.

![image](https://user-images.githubusercontent.com/29758759/192789880-93132c7e-29db-4b1d-91ee-c763ced8fbfb.png)

Command Line
![image](https://user-images.githubusercontent.com/29758759/192794620-49d39333-7e11-402e-8075-0beb5d327e95.png)


This seems to be the error when there is a network issue:
![image](https://user-images.githubusercontent.com/29758759/193040180-8dd04685-a3a5-4771-90d5-f0dada5e2c22.png)

**Comment by bjlay2000** [comment]
A little more info.  We are using Zscaler and I was able to have our security guys disable the tool while I tested the clone process.  It worked successfully.  So the issue is definitely with an antivirus software but there is room for improving GitHub Desktop.  As I said earlier, Sourcetree and some other tools work without disabling the AV software.

**Comment by agnibi** [comment]
It is not be possible to do anything without AV software in my company. I'm hoping for a solution in GitHub Desktop.

**Comment by steveward** [comment]
@agnibi unfortunately it's possible that your firewall/proxy is filtering traffic and causing this issue -- are you able to clone the repository from the command line? You could try performing the initial clone from the command line and then see if you are able to push changes via GitHub Desktop. That would help narrow down the issue.

**Comment by agnibi** [comment]
Hi,

good news: Cloning the repository with "git clone" on command line is working fine.

Thanks for help

**Comment by ParthMovaliya** [comment]
i have issue like this :

> Cloning into 'D:\portfolio\node_modules\.cache\gh-pages\https!github.com'...
> error: RPC failed; curl 56 Recv failure: Connection was reset
> error: 2325 bytes of body are still expected
> fetch-pack: unexpected disconnect while reading sideband packet
> fatal: early EOF
> fatal: fetch-pack: invalid index-pack output

now what i can do?
thanks in advance

**Comment by aloyziuz** [comment]
Disabling my antivirus works for me (i'm using Kaspersky Free)

**Comment by dsrink** [comment]
it seems that this is a compatibility issue on TLS layer, which is fixed in more recent curl versions (which git client relies on for the https/TLS part). For me, problem was solved by upgrading libcurl package to 8.3.0.

**Comment by mhardin18** [comment]
> it seems that this is a compatibility issue on TLS layer, which is fixed in more recent curl versions (which git client relies on for the https/TLS part). For me, problem was solved by upgrading libcurl package to 8.3.0.

Do you have any information of what version of curl this was fixed in?  

I am dealing with curl on zOS and suspect this could be my culprit to this issue. Currently we are running v7.77.0.   
Unfortunately, upgrading curl on the zOS is not as easy as sudo apt upgrade

**Comment by calentis** [comment]
it worked when i closed windows antivirus!

**Comment by letanloc1998** [comment]
Hi, anyway to fix this issue on GitHub Desktop?
I can download by using git command but cannot use GitHub Desktop to clone some repositories.

**Comment by letanloc1998** [comment]
I think GitHub desktop has some wrong configuration with timeout.
This issue happens when the repo size is large and the connection is slow.

**Comment by mh-spinapala** [comment]
I'm seeing the below error when cloning nia-um repository via GitHub desktop and command line. 	

error: RPC failed; curl 56 Failure when receiving data from the peer
error: 1440 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

Any suggestions?

**Comment by letanloc1998** [comment]
> I'm seeing the below error when cloning nia-um repository via GitHub desktop and command line.
> 
> error: RPC failed; curl 56 Failure when receiving data from the peer error: 1440 bytes of body are still expected fetch-pack: unexpected disconnect while reading sideband packet fatal: early EOF fatal: fetch-pack: invalid index-pack output
> 
> Any suggestions?

Let's try:

```
git config --global pack.window 1
git config --global pack.depth 1
```

**Comment by letanloc1998** [comment]
I fixed with configurations:

```
git config --global pack.window 1
git config --global pack.depth 1
```


More configurations (if those configurations above which doesn't work):

```
git config --global pack.packSizeLimit 1g
git config --global pack.deltaCacheSize 1g
git config --global pack.windowMemory 1g
git config --global core.packedGitLimit 1g
git config --global core.packedGitWindowSize 1g

git config --global http.postBuffer 10g
git config --global http.maxRequestBuffer 10g
git config --global https.postBuffer 10g
git config --global https.maxRequestBuffer 10g

git config --global pack.window 1
git config --global pack.depth 1
git config --global pack.threads 128
```


More configurations (if those configurations above which doesn't work):

```
git config --global http.lowSpeedLimit 100
git config --global http.lowSpeedTime 300
```

**Comment by Trasqual** [comment]
Hey cheers, 

git config --global pack.window 1
git config --global pack.depth 1

these worked for me!

**Comment by AbuTharHatem95** [comment]
remote: Enumerating objects: 1256, done.
remote: Counting objects: 100% (1256/1256), done.
remote: Compressing objects: 100% (566/566), done.
error: RPC failed; curl 92 HTTP/2 stream 7 was not closed cleanly: CANCEL (err 8)
error: 1333 bytes of body are still expected
**Are there any solutions to these errors?
-Good internet connection
-The firewall is disabled

**Comment by barracuda156** [comment]
Years pass, and this is still broken with `git clone`.

**Comment by letanloc1998** [comment]
> Years pass, and this is still broken with `git clone`.

Did you try my solution?
https://github.com/desktop/desktop/issues/15333#issuecomment-2178522745

I read the document from git in 2 weeks to find this solution
One person confirms that it works: https://github.com/desktop/desktop/issues/15333#issuecomment-2198472837

**Comment by devabubaker** [comment]
don't do anything just change your internet connection!

**Comment by leonardojyanez** [comment]
I cannot clone repo, like above issue

**Comment by letanloc1998** [comment]
> I cannot clone repo, like above issue

https://github.com/desktop/desktop/issues/15333#issuecomment-2178522745

**Comment by Sobanbabuv** [comment]
remote: Enumerating objects: 14678, done.
remote: Counting objects: 100% (4716/4716), done.
remote: Compressing objects: 100% (715/715), done.
remote: Total 14678 (delta 4223), reused 4001 (delta 4001), pack-reused 9962 (from 1)
Receiving objects: 100% (14678/14678), 198.72 MiB | 987.00 KiB/s, done.
Resolving deltas: 100% (10711/10711), done.
Updating files: 100% (522/522), done. 

thanks it works for me!

**Comment by lightning-sagar** [comment]
@letanloc1998 bro it not working what should i do??

**Comment by HichemTab-tech** [comment]
> [@letanloc1998](https://github.com/letanloc1998) bro it not working what should i do??

same :"(

**Comment by danmirror** [comment]
try this 

$ git clone --depth 1 https://github.com/opencv/opencv.git. 

if still problem you need upsize first

$ git config --global http.postBuffer 1048576000

reference : https://catatandeveloper.id/error-rpc-failed-curl-git-clone/

**Comment by lightning-sagar** [comment]
hey @HichemTab-tech !
reinstall git.. i will be fixed

**Comment by PranDNV** [comment]
> try this
> 
> $ git clone --depth 1 https://github.com/opencv/opencv.git.
> 
> if still problem you need upsize first
> 
> $ git config --global http.postBuffer 1048576000
> 
> reference : https://catatandeveloper.id/error-rpc-failed-curl-git-clone/

thw post buffer aproach worked for me
