### ISSUE TITLE
Combined file view

### ISSUE THREAD

**Issue by 9mm** [desktop/desktop#15330]
### The feature request

I really want to switch to Github Desktop 2 from the native app version, but I just can't until there's a way to view ALL the file changes beneath each other simply by scrolling.

This made the old app so efficient to see changes, now for files with lots of file changes I literally have to click each and every single file which is madness.

### Proposed solution

Offer an option to replace the middle (files) column with a stacked view of diffs for each file, exactly like the v1 desktop app

**Comment by steveward** [comment]
Thanks for the feedback @9mm. This has been previously requested in https://github.com/desktop/desktop/issues/5218 so I'll reference this issue there and close it out. You can follow along there for updates.
