### ISSUE TITLE
Cannot publish repository, fatal: the remote end hung up unexpectedly at 100%

### ISSUE THREAD

**Issue by Aperico-com** [desktop/desktop#15335]
### The problem

I am trying to publish a repository to github.com with github desktop. I tried several times but as soon as I get to 100% on the write step it fails. See log below:

`Enumerating objects: 8134, done.
Counting objects:   0% (1/8134)
Counting objects:   1% (82/8134)
Counting objects:   2% (163/8134)
Counting objects:   3% (245/8134)
Counting objects:   4% (326/8134)
Counting objects:   5% (407/8134)
Counting objects:   6% (489/8134)
Counting objects:   7% (570/8134)
Counting objects:   8% (651/8134)
Counting objects:   9% (733/8134)
Counting objects:  10% (814/8134)
Counting objects:  11% (895/8134)
Counting objects:  12% (977/8134)
Counting objects:  13% (1058/8134)
Counting objects:  14% (1139/8134)
Counting objects:  15% (1221/8134)
Counting objects:  16% (1302/8134)
Counting objects:  17% (1383/8134)
Counting objects:  18% (1465/8134)
Counting objects:  19% (1546/8134)
Counting objects:  20% (1627/8134)
Counting objects:  21% (1709/8134)
Counting objects:  22% (1790/8134)
Counting objects:  23% (1871/8134)
Counting objects:  24% (1953/8134)
Counting objects:  25% (2034/8134)
Counting objects:  26% (2115/8134)
Counting objects:  27% (2197/8134)
Counting objects:  28% (2278/8134)
Counting objects:  29% (2359/8134)
Counting objects:  30% (2441/8134)
Counting objects:  31% (2522/8134)
Counting objects:  32% (2603/8134)
Counting objects:  33% (2685/8134)
Counting objects:  34% (2766/8134)
Counting objects:  35% (2847/8134)
Counting objects:  36% (2929/8134)
Counting objects:  37% (3010/8134)
Counting objects:  38% (3091/8134)
Counting objects:  39% (3173/8134)
Counting objects:  40% (3254/8134)
Counting objects:  41% (3335/8134)
Counting objects:  42% (3417/8134)
Counting objects:  43% (3498/8134)
Counting objects:  44% (3579/8134)
Counting objects:  45% (3661/8134)
Counting objects:  46% (3742/8134)
Counting objects:  47% (3823/8134)
Counting objects:  48% (3905/8134)
Counting objects:  49% (3986/8134)
Counting objects:  50% (4067/8134)
Counting objects:  51% (4149/8134)
Counting objects:  52% (4230/8134)
Counting objects:  53% (4312/8134)
Counting objects:  54% (4393/8134)
Counting objects:  55% (4474/8134)
Counting objects:  56% (4556/8134)
Counting objects:  57% (4637/8134)
Counting objects:  58% (4718/8134)
Counting objects:  59% (4800/8134)
Counting objects:  60% (4881/8134)
Counting objects:  61% (4962/8134)
Counting objects:  62% (5044/8134)
Counting objects:  63% (5125/8134)
Counting objects:  64% (5206/8134)
Counting objects:  65% (5288/8134)
Counting objects:  66% (5369/8134)
Counting objects:  67% (5450/8134)
Counting objects:  68% (5532/8134)
Counting objects:  69% (5613/8134)
Counting objects:  70% (5694/8134)
Counting objects:  71% (5776/8134)
Counting objects:  72% (5857/8134)
Counting objects:  73% (5938/8134)
Counting objects:  74% (6020/8134)
Counting objects:  75% (6101/8134)
Counting objects:  76% (6182/8134)
Counting objects:  77% (6264/8134)
Counting objects:  78% (6345/8134)
Counting objects:  79% (6426/8134)
Counting objects:  80% (6508/8134)
Counting objects:  81% (6589/8134)
Counting objects:  82% (6670/8134)
Counting objects:  83% (6752/8134)
Counting objects:  84% (6833/8134)
Counting objects:  85% (6914/8134)
Counting objects:  86% (6996/8134)
Counting objects:  87% (7077/8134)
Counting objects:  88% (7158/8134)
Counting objects:  89% (7240/8134)
Counting objects:  90% (7321/8134)
Counting objects:  91% (7402/8134)
Counting objects:  92% (7484/8134)
Counting objects:  93% (7565/8134)
Counting objects:  94% (7646/8134)
Counting objects:  95% (7728/8134)
Counting objects:  96% (7809/8134)
Counting objects:  97% (7890/8134)
Counting objects:  98% (7972/8134)
Counting objects:  99% (8053/8134)
Counting objects: 100% (8134/8134)
Counting objects: 100% (8134/8134), done.
Delta compression using up to 12 threads
Compressing objects:   0% (1/7770)
Compressing objects:   1% (78/7770)
Compressing objects:   2% (156/7770)
Compressing objects:   3% (234/7770)
Compressing objects:   4% (311/7770)
Compressing objects:   5% (389/7770)
Compressing objects:   6% (467/7770)
Compressing objects:   7% (544/7770)
Compressing objects:   8% (622/7770)
Compressing objects:   9% (700/7770)
Compressing objects:  10% (777/7770)
Compressing objects:  11% (855/7770)
Compressing objects:  12% (933/7770)
Compressing objects:  13% (1011/7770)
Compressing objects:  14% (1088/7770)
Compressing objects:  15% (1166/7770)
Compressing objects:  16% (1244/7770)
Compressing objects:  17% (1321/7770)
Compressing objects:  18% (1399/7770)
Compressing objects:  19% (1477/7770)
Compressing objects:  20% (1554/7770)
Compressing objects:  21% (1632/7770)
Compressing objects:  22% (1710/7770)
Compressing objects:  23% (1788/7770)
Compressing objects:  24% (1865/7770)
Compressing objects:  25% (1943/7770)
Compressing objects:  25% (1989/7770)
Compressing objects:  26% (2021/7770)
Compressing objects:  27% (2098/7770)
Compressing objects:  28% (2176/7770)
Compressing objects:  29% (2254/7770)
Compressing objects:  30% (2331/7770)
Compressing objects:  31% (2409/7770)
Compressing objects:  32% (2487/7770)
Compressing objects:  33% (2565/7770)
Compressing objects:  34% (2642/7770)
Compressing objects:  35% (2720/7770)
Compressing objects:  36% (2798/7770)
Compressing objects:  37% (2875/7770)
Compressing objects:  38% (2953/7770)
Compressing objects:  39% (3031/7770)
Compressing objects:  40% (3108/7770)
Compressing objects:  41% (3186/7770)
Compressing objects:  42% (3264/7770)
Compressing objects:  43% (3342/7770)
Compressing objects:  44% (3419/7770)
Compressing objects:  45% (3497/7770)
Compressing objects:  46% (3575/7770)
Compressing objects:  47% (3652/7770)
Compressing objects:  48% (3730/7770)
Compressing objects:  49% (3808/7770)
Compressing objects:  50% (3885/7770)
Compressing objects:  51% (3963/7770)
Compressing objects:  52% (4041/7770)
Compressing objects:  52% (4054/7770)
Compressing objects:  53% (4119/7770)
Compressing objects:  54% (4196/7770)
Compressing objects:  55% (4274/7770)
Compressing objects:  56% (4352/7770)
Compressing objects:  57% (4429/7770)
Compressing objects:  58% (4507/7770)
Compressing objects:  59% (4585/7770)
Compressing objects:  60% (4662/7770)
Compressing objects:  61% (4740/7770)
Compressing objects:  62% (4818/7770)
Compressing objects:  63% (4896/7770)
Compressing objects:  64% (4973/7770)
Compressing objects:  65% (5051/7770)
Compressing objects:  66% (5129/7770)
Compressing objects:  67% (5206/7770)
Compressing objects:  68% (5284/7770)
Compressing objects:  69% (5362/7770)
Compressing objects:  70% (5439/7770)
Compressing objects:  71% (5517/7770)
Compressing objects:  72% (5595/7770)
Compressing objects:  73% (5673/7770)
Compressing objects:  74% (5750/7770)
Compressing objects:  75% (5828/7770)
Compressing objects:  76% (5906/7770)
Compressing objects:  77% (5983/7770)
Compressing objects:  78% (6061/7770)
Compressing objects:  79% (6139/7770)
Compressing objects:  79% (6204/7770)
Compressing objects:  80% (6216/7770)
Compressing objects:  81% (6294/7770)
Compressing objects:  82% (6372/7770)
Compressing objects:  83% (6450/7770)
Compressing objects:  84% (6527/7770)
Compressing objects:  85% (6605/7770)
Compressing objects:  85% (6651/7770)
Compressing objects:  86% (6683/7770)
Compressing objects:  87% (6760/7770)
Compressing objects:  88% (6838/7770)
Compressing objects:  89% (6916/7770)
Compressing objects:  90% (6993/7770)
Compressing objects:  90% (6999/7770)
Compressing objects:  91% (7071/7770)
Compressing objects:  92% (7149/7770)
Compressing objects:  93% (7227/7770)
Compressing objects:  93% (7278/7770)
Compressing objects:  94% (7304/7770)
Compressing objects:  95% (7382/7770)
Compressing objects:  95% (7432/7770)
Compressing objects:  96% (7460/7770)
Compressing objects:  96% (7500/7770)
Compressing objects:  97% (7537/7770)
Compressing objects:  97% (7591/7770)
Compressing objects:  98% (7615/7770)
Compressing objects:  98% (7649/7770)
Compressing objects:  98% (7654/7770)
Compressing objects:  98% (7678/7770)
Compressing objects:  98% (7688/7770)
Compressing objects:  99% (7693/7770)
Compressing objects:  99% (7695/7770)
Compressing objects:  99% (7701/7770)
Compressing objects:  99% (7707/7770)
Compressing objects:  99% (7723/7770)
Compressing objects:  99% (7737/7770)
Compressing objects:  99% (7741/7770)
Compressing objects:  99% (7744/7770)
Compressing objects:  99% (7748/7770)
Compressing objects:  99% (7749/7770)
Compressing objects: 100% (7770/7770)
Compressing objects: 100% (7770/7770), done.
Writing objects:   0% (1/8134)
Writing objects:   0% (15/8134), 300.70 MiB | 300.99 MiB/s
Writing objects:   0% (63/8134), 619.47 MiB | 309.88 MiB/s
Writing objects:   1% (82/8134), 619.47 MiB | 309.88 MiB/s
Writing objects:   2% (163/8134), 619.47 MiB | 309.88 MiB/s
Writing objects:   3% (245/8134), 619.47 MiB | 309.88 MiB/s
Writing objects:   4% (326/8134), 619.47 MiB | 309.88 MiB/s
Writing objects:   5% (407/8134), 619.47 MiB | 309.88 MiB/s
Writing objects:   6% (489/8134), 619.47 MiB | 309.88 MiB/s
Writing objects:   7% (570/8134), 781.85 MiB | 312.86 MiB/s
Writing objects:   8% (653/8134), 781.85 MiB | 312.86 MiB/s
Writing objects:   9% (733/8134), 781.85 MiB | 312.86 MiB/s
Writing objects:  10% (814/8134), 781.85 MiB | 312.86 MiB/s
Writing objects:  11% (895/8134), 781.85 MiB | 312.86 MiB/s
Writing objects:  12% (977/8134), 946.53 MiB | 315.71 MiB/s
Writing objects:  12% (994/8134), 946.53 MiB | 315.71 MiB/s
Writing objects:  12% (1026/8134), 999.96 MiB | 25.53 MiB/s
Writing objects:  12% (1026/8134), 1019.37 MiB | 25.69 MiB/s
Writing objects:  12% (1035/8134), 1.01 GiB | 25.90 MiB/s   
Writing objects:  13% (1058/8134), 1.01 GiB | 25.90 MiB/s
Writing objects:  14% (1139/8134), 1.03 GiB | 22.54 MiB/s
Writing objects:  14% (1157/8134), 1.06 GiB | 19.52 MiB/s
Writing objects:  14% (1163/8134), 1.10 GiB | 12.74 MiB/s
Writing objects:  14% (1177/8134), 1.14 GiB | 5.72 MiB/s 
Writing objects:  14% (1185/8134), 1.19 GiB | 43.90 MiB/s
Writing objects:  14% (1190/8134), 1.23 GiB | 44.12 MiB/s
Writing objects:  14% (1205/8134), 1.28 GiB | 43.84 MiB/s
Writing objects:  14% (1212/8134), 1.32 GiB | 43.76 MiB/s
Writing objects:  14% (1218/8134), 1.36 GiB | 44.13 MiB/s
Writing objects:  15% (1221/8134), 1.36 GiB | 44.13 MiB/s
Writing objects:  15% (1226/8134), 1.40 GiB | 43.62 MiB/s
Writing objects:  15% (1230/8134), 1.45 GiB | 43.35 MiB/s
Writing objects:  15% (1254/8134), 1.49 GiB | 42.91 MiB/s
Writing objects:  15% (1260/8134), 1.54 GiB | 39.75 MiB/s
Writing objects:  15% (1260/8134), 1.57 GiB | 38.05 MiB/s
Writing objects:  15% (1260/8134), 1.61 GiB | 36.64 MiB/s
Writing objects:  15% (1260/8134), 1.65 GiB | 35.83 MiB/s
Writing objects:  15% (1260/8134), 1.67 GiB | 34.27 MiB/s
Writing objects:  15% (1260/8134), 1.69 GiB | 31.06 MiB/s
Writing objects:  16% (1302/8134), 1.70 GiB | 29.38 MiB/s
Writing objects:  16% (1306/8134), 1.70 GiB | 29.38 MiB/s
Writing objects:  17% (1383/8134), 1.70 GiB | 29.38 MiB/s
Writing objects:  18% (1465/8134), 1.71 GiB | 27.67 MiB/s
Writing objects:  18% (1500/8134), 1.72 GiB | 25.97 MiB/s
Writing objects:  18% (1507/8134), 1.75 GiB | 22.49 MiB/s
Writing objects:  18% (1513/8134), 1.77 GiB | 21.46 MiB/s
Writing objects:  18% (1521/8134), 1.80 GiB | 22.39 MiB/s
Writing objects:  18% (1527/8134), 1.81 GiB | 21.89 MiB/s
Writing objects:  18% (1533/8134), 1.83 GiB | 20.71 MiB/s
Writing objects:  18% (1539/8134), 1.84 GiB | 19.68 MiB/s
Writing objects:  18% (1542/8134), 1.86 GiB | 18.77 MiB/s
Writing objects:  19% (1546/8134), 1.88 GiB | 18.22 MiB/s
Writing objects:  19% (1566/8134), 1.90 GiB | 18.94 MiB/s
Writing objects:  19% (1578/8134), 1.92 GiB | 19.64 MiB/s
Writing objects:  19% (1588/8134), 1.94 GiB | 20.39 MiB/s
Writing objects:  19% (1594/8134), 1.96 GiB | 21.17 MiB/s
Writing objects:  19% (1596/8134), 1.99 GiB | 22.17 MiB/s
error: RPC failed; curl 55 Send failure: Connection was aborted
send-pack: unexpected disconnect while reading sideband packet
Writing objects:  20% (1627/8134), 2.05 GiB | 32.65 MiB/s
Writing objects:  21% (1709/8134), 2.05 GiB | 32.65 MiB/s
Writing objects:  21% (1767/8134), 2.05 GiB | 32.65 MiB/s
Writing objects:  22% (1790/8134), 2.05 GiB | 32.65 MiB/s
Writing objects:  23% (1871/8134), 2.05 GiB | 32.65 MiB/s
Writing objects:  24% (1953/8134), 2.05 GiB | 32.65 MiB/s
Writing objects:  25% (2034/8134), 2.05 GiB | 32.65 MiB/s
Writing objects:  26% (2115/8134), 2.05 GiB | 32.65 MiB/s
Writing objects:  27% (2197/8134), 2.05 GiB | 32.65 MiB/s
Writing objects:  28% (2278/8134), 2.05 GiB | 32.65 MiB/s
Writing objects:  29% (2359/8134), 2.05 GiB | 32.65 MiB/s
Writing objects:  30% (2441/8134), 2.05 GiB | 32.65 MiB/s
Writing objects:  31% (2522/8134), 2.22 GiB | 68.04 MiB/s
Writing objects:  32% (2603/8134), 2.22 GiB | 68.04 MiB/s
Writing objects:  33% (2685/8134), 2.22 GiB | 68.04 MiB/s
Writing objects:  33% (2752/8134), 2.55 GiB | 137.34 MiB/s
Writing objects:  34% (2766/8134), 2.55 GiB | 137.34 MiB/s
Writing objects:  34% (2772/8134), 2.70 GiB | 170.53 MiB/s
Writing objects:  34% (2781/8134), 2.83 GiB | 191.23 MiB/s
Writing objects:  34% (2781/8134), 2.84 GiB | 178.00 MiB/s
Writing objects:  34% (2781/8134), 2.84 GiB | 104.69 MiB/s
Writing objects:  34% (2781/8134), 2.85 GiB | 33.87 MiB/s 
Writing objects:  34% (2781/8134), 2.86 GiB | 8.00 MiB/s 
Writing objects:  34% (2781/8134), 2.87 GiB | 7.91 MiB/s
Writing objects:  34% (2781/8134), 2.88 GiB | 7.83 MiB/s
Writing objects:  34% (2781/8134), 2.88 GiB | 7.86 MiB/s
Writing objects:  34% (2781/8134), 2.89 GiB | 7.87 MiB/s
Writing objects:  34% (2781/8134), 2.90 GiB | 7.86 MiB/s
Writing objects:  34% (2781/8134), 2.91 GiB | 7.85 MiB/s
Writing objects:  34% (2781/8134), 2.91 GiB | 7.76 MiB/s
Writing objects:  34% (2781/8134), 2.92 GiB | 7.73 MiB/s
Writing objects:  34% (2781/8134), 2.93 GiB | 7.76 MiB/s
Writing objects:  34% (2781/8134), 2.94 GiB | 7.83 MiB/s
Writing objects:  34% (2781/8134), 2.94 GiB | 7.78 MiB/s
Writing objects:  34% (2781/8134), 2.95 GiB | 7.77 MiB/s
Writing objects:  34% (2781/8134), 2.96 GiB | 7.74 MiB/s
Writing objects:  34% (2781/8134), 2.97 GiB | 7.66 MiB/s
Writing objects:  34% (2781/8134), 2.97 GiB | 7.56 MiB/s
Writing objects:  34% (2781/8134), 2.98 GiB | 7.56 MiB/s
Writing objects:  34% (2781/8134), 2.99 GiB | 7.60 MiB/s
Writing objects:  34% (2781/8134), 3.00 GiB | 7.62 MiB/s
Writing objects:  34% (2781/8134), 3.00 GiB | 7.76 MiB/s
Writing objects:  34% (2781/8134), 3.01 GiB | 7.87 MiB/s
Writing objects:  34% (2781/8134), 3.02 GiB | 7.87 MiB/s
Writing objects:  34% (2781/8134), 3.03 GiB | 7.83 MiB/s
Writing objects:  34% (2781/8134), 3.03 GiB | 7.76 MiB/s
Writing objects:  34% (2781/8134), 3.04 GiB | 7.71 MiB/s
Writing objects:  34% (2781/8134), 3.05 GiB | 7.69 MiB/s
Writing objects:  34% (2781/8134), 3.06 GiB | 7.71 MiB/s
Writing objects:  34% (2781/8134), 3.06 GiB | 7.71 MiB/s
Writing objects:  34% (2781/8134), 3.07 GiB | 7.73 MiB/s
Writing objects:  34% (2781/8134), 3.08 GiB | 7.73 MiB/s
Writing objects:  34% (2781/8134), 3.09 GiB | 7.77 MiB/s
Writing objects:  34% (2781/8134), 3.10 GiB | 8.00 MiB/s
Writing objects:  34% (2781/8134), 3.10 GiB | 8.16 MiB/s
Writing objects:  34% (2781/8134), 3.11 GiB | 8.30 MiB/s
Writing objects:  34% (2781/8134), 3.12 GiB | 8.51 MiB/s
Writing objects:  34% (2781/8134), 3.13 GiB | 8.44 MiB/s
Writing objects:  34% (2781/8134), 3.14 GiB | 8.49 MiB/s
Writing objects:  35% (2847/8134), 3.14 GiB | 8.49 MiB/s
Writing objects:  35% (2922/8134), 3.14 GiB | 8.16 MiB/s
Writing objects:  36% (2930/8134), 3.14 GiB | 8.16 MiB/s
Writing objects:  36% (2977/8134), 3.15 GiB | 7.07 MiB/s
Writing objects:  36% (2989/8134), 3.19 GiB | 5.54 MiB/s
Writing objects:  36% (2989/8134), 3.38 GiB | 18.76 MiB/s
Writing objects:  36% (2993/8134), 3.58 GiB | 19.88 MiB/s
Writing objects:  36% (2993/8134), 3.76 GiB | 27.61 MiB/s
Writing objects:  37% (3010/8134), 3.94 GiB | 35.23 MiB/s
Writing objects:  37% (3025/8134), 3.94 GiB | 35.23 MiB/s
Writing objects:  38% (3091/8134), 4.08 GiB | 41.42 MiB/s
Writing objects:  39% (3173/8134), 4.09 GiB | 41.36 MiB/s
Writing objects:  39% (3226/8134), 4.09 GiB | 41.36 MiB/s
Writing objects:  40% (3254/8134), 4.09 GiB | 42.09 MiB/s
Writing objects:  41% (3335/8134), 4.09 GiB | 42.09 MiB/s
Writing objects:  42% (3418/8134), 4.09 GiB | 42.09 MiB/s
Writing objects:  43% (3498/8134), 4.09 GiB | 42.09 MiB/s
Writing objects:  44% (3579/8134), 4.09 GiB | 65.37 MiB/s
Writing objects:  45% (3661/8134), 4.09 GiB | 65.37 MiB/s
Writing objects:  45% (3677/8134), 4.10 GiB | 51.97 MiB/s
Writing objects:  46% (3744/8134), 4.11 GiB | 39.66 MiB/s
Writing objects:  46% (3772/8134), 4.11 GiB | 39.66 MiB/s
Writing objects:  47% (3823/8134), 4.11 GiB | 39.66 MiB/s
Writing objects:  48% (3905/8134), 4.11 GiB | 114.16 MiB/s
Writing objects:  49% (3986/8134), 4.12 GiB | 76.34 MiB/s 
Writing objects:  50% (4067/8134), 4.12 GiB | 76.34 MiB/s
Writing objects:  51% (4149/8134), 4.12 GiB | 76.34 MiB/s
Writing objects:  52% (4230/8134), 4.12 GiB | 76.34 MiB/s
Writing objects:  52% (4234/8134), 4.12 GiB | 76.34 MiB/s
Writing objects:  53% (4313/8134), 4.12 GiB | 76.34 MiB/s
Writing objects:  54% (4393/8134), 4.12 GiB | 76.34 MiB/s
Writing objects:  55% (4474/8134), 4.12 GiB | 76.34 MiB/s
Writing objects:  56% (4556/8134), 4.12 GiB | 76.34 MiB/s
Writing objects:  57% (4637/8134), 4.12 GiB | 38.87 MiB/s
Writing objects:  58% (4718/8134), 4.13 GiB | 9.43 MiB/s 
Writing objects:  59% (4800/8134), 4.13 GiB | 9.43 MiB/s
Writing objects:  60% (4881/8134), 4.13 GiB | 9.43 MiB/s
Writing objects:  61% (4962/8134), 4.13 GiB | 9.43 MiB/s
Writing objects:  62% (5044/8134), 4.13 GiB | 9.43 MiB/s
Writing objects:  62% (5048/8134), 4.13 GiB | 9.43 MiB/s
Writing objects:  63% (5125/8134), 4.13 GiB | 9.43 MiB/s
Writing objects:  64% (5207/8134), 4.13 GiB | 9.43 MiB/s
Writing objects:  65% (5288/8134), 4.13 GiB | 9.43 MiB/s
Writing objects:  66% (5369/8134), 4.14 GiB | 10.37 MiB/s
Writing objects:  66% (5376/8134), 4.14 GiB | 10.37 MiB/s
Writing objects:  66% (5393/8134), 4.14 GiB | 9.76 MiB/s 
Writing objects:  67% (5450/8134), 4.15 GiB | 9.91 MiB/s
Writing objects:  68% (5532/8134), 4.15 GiB | 9.91 MiB/s
Writing objects:  68% (5604/8134), 4.15 GiB | 5.49 MiB/s
Writing objects:  69% (5613/8134), 4.15 GiB | 5.49 MiB/s
Writing objects:  70% (5694/8134), 4.15 GiB | 5.49 MiB/s
Writing objects:  71% (5776/8134), 4.15 GiB | 5.49 MiB/s
Writing objects:  72% (5857/8134), 4.20 GiB | 10.51 MiB/s
Writing objects:  72% (5871/8134), 4.20 GiB | 10.51 MiB/s
Writing objects:  73% (5938/8134), 4.20 GiB | 10.51 MiB/s
Writing objects:  74% (6020/8134), 4.21 GiB | 10.87 MiB/s
Writing objects:  74% (6059/8134), 4.21 GiB | 7.92 MiB/s 
Writing objects:  74% (6060/8134), 4.21 GiB | 7.92 MiB/s
Writing objects:  75% (6101/8134), 4.21 GiB | 7.92 MiB/s
Writing objects:  75% (6164/8134), 4.25 GiB | 10.85 MiB/s
Writing objects:  76% (6182/8134), 4.25 GiB | 10.85 MiB/s
Writing objects:  77% (6264/8134), 4.25 GiB | 10.85 MiB/s
Writing objects:  77% (6308/8134), 4.27 GiB | 11.73 MiB/s
Writing objects:  77% (6323/8134), 4.28 GiB | 12.50 MiB/s
Writing objects:  78% (6345/8134), 4.28 GiB | 12.50 MiB/s
Writing objects:  79% (6426/8134), 4.28 GiB | 12.50 MiB/s
Writing objects:  79% (6496/8134), 4.30 GiB | 13.99 MiB/s
Writing objects:  80% (6508/8134), 4.31 GiB | 14.61 MiB/s
Writing objects:  80% (6511/8134), 4.33 GiB | 22.67 MiB/s
Writing objects:  80% (6529/8134), 4.34 GiB | 17.43 MiB/s
Writing objects:  80% (6546/8134), 4.36 GiB | 17.21 MiB/s
Writing objects:  80% (6565/8134), 4.38 GiB | 18.94 MiB/s
Writing objects:  80% (6577/8134), 4.39 GiB | 18.80 MiB/s
Writing objects:  81% (6589/8134), 4.39 GiB | 18.80 MiB/s
Writing objects:  81% (6613/8134), 4.41 GiB | 19.34 MiB/s
Writing objects:  81% (6625/8134), 4.43 GiB | 17.92 MiB/s
Writing objects:  81% (6640/8134), 4.44 GiB | 18.56 MiB/s
Writing objects:  81% (6656/8134), 4.46 GiB | 17.77 MiB/s
Writing objects:  82% (6670/8134), 4.48 GiB | 18.27 MiB/s
Writing objects:  82% (6688/8134), 4.48 GiB | 18.00 MiB/s
Writing objects:  82% (6711/8134), 4.49 GiB | 16.68 MiB/s
Writing objects:  82% (6723/8134), 4.50 GiB | 14.77 MiB/s
Writing objects:  82% (6735/8134), 4.52 GiB | 15.56 MiB/s
Writing objects:  83% (6752/8134), 4.52 GiB | 15.56 MiB/s
Writing objects:  84% (6833/8134), 4.53 GiB | 16.45 MiB/s
Writing objects:  85% (6915/8134), 4.53 GiB | 16.45 MiB/s
Writing objects:  86% (6996/8134), 4.53 GiB | 16.45 MiB/s
Writing objects:  87% (7077/8134), 4.53 GiB | 16.45 MiB/s
Writing objects:  88% (7158/8134), 4.53 GiB | 15.82 MiB/s
Writing objects:  89% (7240/8134), 4.53 GiB | 15.82 MiB/s
Writing objects:  90% (7321/8134), 4.53 GiB | 15.82 MiB/s
Writing objects:  91% (7402/8134), 4.53 GiB | 15.82 MiB/s
Writing objects:  92% (7484/8134), 4.53 GiB | 15.82 MiB/s
Writing objects:  92% (7535/8134), 4.53 GiB | 15.82 MiB/s
Writing objects:  93% (7565/8134), 4.53 GiB | 15.82 MiB/s
Writing objects:  94% (7646/8134), 4.54 GiB | 15.08 MiB/s
Writing objects:  94% (7712/8134), 4.54 GiB | 12.67 MiB/s
Writing objects:  95% (7728/8134), 4.54 GiB | 12.67 MiB/s
Writing objects:  96% (7810/8134), 4.54 GiB | 11.50 MiB/s
Writing objects:  97% (7890/8134), 4.54 GiB | 11.17 MiB/s
Writing objects:  97% (7947/8134), 4.54 GiB | 11.17 MiB/s
Writing objects:  98% (7972/8134), 4.54 GiB | 11.17 MiB/s
Writing objects:  99% (8053/8134), 4.54 GiB | 11.17 MiB/s
Writing objects:  99% (8128/8134), 4.55 GiB | 2.57 MiB/s 
Writing objects:  99% (8128/8134), 4.73 GiB | 13.60 MiB/s
Writing objects:  99% (8129/8134), 4.91 GiB | 25.60 MiB/s
Writing objects: 100% (8134/8134), 5.04 GiB | 33.28 MiB/s
Writing objects: 100% (8134/8134), 5.04 GiB | 27.14 MiB/s, done.
Total 8134 (delta 1950), reused 2556 (delta 194), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

(The error was parsed as 4: The remote disconnected. Check your Internet connection and try again.)
2022-09-22T09:43:33.692Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2022-09-22T09:43:34.037Z - info: [ui] [AppStore] loading 1 repositories from store
2022-09-22T09:43:34.038Z - info: [ui] [AppStore] found account: Aperico-com (Aperico-com)
2022-09-22T09:43:34.050Z - info: [ui] [BranchPruner] Last prune took place 4 minutes ago - skipping
2022-09-22T09:43:34.448Z - info: [ui] Subscribed 'Aperico-com' to Alive channel
2022-09-22T09:43:36.467Z - info: [ui] launching: 3.0.8 (Windows 10.0.19044)
2022-09-22T09:43:36.478Z - info: [ui] execPath: 'C:\Users\Master\AppData\Local\GitHubDesktop\app-3.0.8\GitHubDesktop.exe'
2022-09-22T09:43:37.649Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.719s)
`

### Release version

Version 3.0.8 (x64)

### Operating system

Windows 10

### Log files

[2022-09-22.desktop.production.log](https://github.com/desktop/desktop/files/9624503/2022-09-22.desktop.production.log)

**Comment by steveward** [comment]
@Aperico-com thanks for the issue. It looks like the push operation is timing out due to the size of the repository (over 5GB). GitHub generally recommends keeping repository size under 1GB for optimal performance. If you're working with large files in this repository I would recommend looking into using Git LFS -- see [these articles](https://docs.github.com/en/repositories/working-with-files/managing-large-files) for how to get started working with large files.

Some users have also had success switching to use SSH instead of HTTPS. If you're interested in learning how to set a new SSH key you can follow [this guide](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent).

I'm going to close this issue out, but if you have any further questions let me know.

**Comment by Aperico-com** [comment]
@steveward thank you for the reply, but this information is not new to me. I always do research before bothering to make an issue. Using LFS for large repos was the first that popped up and I am using it. I have activated it via git command line locally and set the use LFS in the settings for the repo at github.com. Can you think of anything else? What about the lines "error: RPC failed; curl 55 Send failure: Connection was aborted
send-pack: unexpected disconnect while reading sideband packet"

**Comment by steveward** [comment]
@Aperico-com that just means the push is timing out. I would recommend trying on a different network to see if you have success there. Using SSH like I mentioned above could also be a viable workaround.
