### ISSUE TITLE
Dealing with unhandled exceptions

### ISSUE THREAD

**Issue by niik** [desktop/desktop#1534]
We're seeing that in some scenarios it's possible to get stuck in a feedback loop between the `AppStore` and our `uncaughtException` handler.

Our [uncaughtException handler](https://github.com/desktop/desktop/blob/4275f0c7352fe88cb3dfdc2136eb96223362a212/app/src/ui/index.tsx#L50-L54) reports the error to haystack, logs it to disk, and then posts it to the dispatcher. The dispatcher in turns hands it off to the `AppStore` which emits an update. _If_ the uncaught exception was thrown somewhere in the render path due to invalid state (see #1519) the emitted update from the AppStore will trigger it again.

@joshaber short circuited the `uncaughtException` handler in #1517 but it's still possible that components will asynchronously cause a re-render. Basically, when we get an uncaught exception all bets are off as far as the state of the app is concerned.

After some discussion we settled on a new app part (along main, shared, renderer) that takes over when the app gets an unhandled exception. When such an exception occurs the renderer will ship the error off to the main process which will be responsible for logging it to haystack, writing to our log files, closing the renderer and spawing this new app part in a new window and provide it with some details that we can present to the user.

**Comment by joshaber** [comment]
@niik you're working on this, right?

**Comment by niik** [comment]
@joshaber Indeed, sorry about that
