### ISSUE TITLE
Continue merge BUG

### ISSUE THREAD

**Issue by TWalew** [desktop/desktop#15345]
### The problem

Sometimes when I open the tool it says do you want to continue to merge and wants to merge all of our old branches and deleted components into the dev branch. It's awful all of the deleted components folders appear in the source and I have to delete those manually. Also, All deleted branches appear in the tool and I have to delete those manually too. 

As a team leader, I will forbid the tool for all of the team if this bug continues to happen. 

### Release version

Version 3.0.8 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Shut down the PC for the weekend.
2. On Monday start the PC.
3. Open VS CODE with the repo.
4. Open GitHub Desktop.
5. Make changes in VS CODE in any file.

OBSERVE THE NONSENSE!!!

**Comment by steveward** [comment]
Thanks for the issue @TWalew, and apologies for the frustration. Can you share the specific actions you were taking in GitHub Desktop when you encountered these issues? Any further details or screenshots you can share would be helpful to debug what happened.

>All deleted branches appear in the tool and I have to delete those manually too.

Branches merged and deleted on GitHub are automatically removed from your local repository in GitHub Desktop after 2 weeks (if you have not checked out the branch locally in the meantime).

**Comment by TWalew** [comment]
It happens when I turn on my PC after I've left it off for the weekend. The first thing I see when opening it is a prompt message to continue or abort the merge which is strange since I didn't merge anything and when aborting I can see that it's trying to merge old and deleted files in the develop branch. Those are files that we deleted or moved to different folders and it tries to push the old files to the develop branch. I will continue using it and provide screenshots next time it happens. And also all of the deleted branches appear even though I've set up GitLab to delete the branch after merging with develop and I manually delete this branch in my GitHub Desktop after that since I'm the only one that accepts pull requests.

**Comment by TWalew** [comment]
It happened again

![image](https://user-images.githubusercontent.com/13393093/193518267-6c60e398-1f33-4405-a8a6-2c0465289586.png)

![image](https://user-images.githubusercontent.com/13393093/193518408-4d5e00c4-4e6e-4451-a7df-aace497de356.png)

**Comment by TWalew** [comment]
All of those are deleted files months ago

**Comment by TWalew** [comment]
![image](https://user-images.githubusercontent.com/13393093/193522166-374affcc-5ae6-44bc-942d-8cb5f774554a.png)
Also here are all of the deleted branches again reappearing again

**Comment by TWalew** [comment]
Started manually deleting those again and I saw a branch deleted 2 months ago.

![image](https://user-images.githubusercontent.com/13393093/193522698-f9b8a4fe-4d97-480b-a4ac-bd0f24048b80.png)

**Comment by TWalew** [comment]
This is so frustrating that if that keeps happening, I will forbid the tool for the whole team!!!

**Comment by tidy-dev** [comment]
@TWalew Curious if your store your repositories on a cloud based storage such as google-drive, dropbox. etc..?

**Comment by TWalew** [comment]
You are a lifesaver I managed to find my problem and it was the OneDrive cloud storage that made backups and backed up the old files that's why GitHub Desktop was freaking out. 
Thanks a lot, we can close this issue. ❤️
