### ISSUE TITLE
Google Drive causing desktop.ini errors when closing files to it.

### ISSUE THREAD

**Issue by cluemaster-robert** [desktop/desktop#15343]
I think I figured out why the GitHub desktop application gives non-stop
desktop.ini errors.   I was saving my cloned repositories to my Google
Drive on my local PC.  It causes anything inside to make the GitHub Desktop
app give nonstop errors.  I moved everything to my local D:\ internal hard
drive, and the errors stopped.   Something about the virtual files in the
google drive technology causes huge issues with your desktop app.  Can this
be looked into and fixed possibly?

_Originally posted by @steveward in https://github.com/desktop/desktop/issues/14619#issuecomment-1212113171_

**Comment by niik** [comment]
Hey @cluemaster-robert, we've highly recommended against keeping Git repositories in Dropbox in the past as it's been a source of a lot of problems for folks (regardless of them using GitHub Desktop, just Git, or other tools).

Cloud drives such as GDrive, DropBox etc [are notorious for corrupting Git repositories](https://stackoverflow.com/a/32364075/2114). I'd recommend that you move your repository outside of your Google Drive directory to prevent similar things from happening in the future.
