### ISSUE TITLE
cannot install desktop on win11

### ISSUE THREAD

**Issue by Mother-Screng** [desktop/desktop#15341]
### The problem

During the install, it asks me if i want to upload a folder, create a new repository, or download one.  when i pick download, i get an error that my 64GB machine is out of memory, and installation is stuck at that stage. 

### Release version

it is greyed out

### Operating system

Windows 11 Insider Preview (10.0.22622.601) (KB5017384)

### Steps to reproduce the behavior

Double click .exe to install Desktop. Click on Clone a repository from the internet.  select sign into GitHub.  Receive out of memory error.

**Comment by steveward** [comment]
Thanks for the report @Mother-Screng. This is being tracked in https://github.com/desktop/desktop/issues/15217. You can try the steps in https://github.com/desktop/desktop/issues/15217#issuecomment-1236989284 to see if that resolves things for you.

I'm going to close this out, but let me know if that doesn't get things working and we can investigate further.
