### ISSUE TITLE
VSCodium on Mac M1 (arm64) not detected as external editor

### ISSUE THREAD

**Issue by daniel-ciaglia** [desktop/desktop#15348]
### The problem

VSCodium is not detected as external editor

VSCodium:
```
Version: 1.71.2
Release: 22258
Commit: cea9d1a4b17966719d8c5f3cdd914480f7cec47c
Date: 2022-09-15T18:10:26.611Z (1 wk ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No
```

# Fix
- Identifier: `defaults read /Applications/VSCodium.app/Contents/Info CFBundleIdentifier`
- add identifier `com.vscodium` to https://github.com/desktop/desktop/blob/development/app/src/lib/editors/darwin.ts#L47

### Release version

Version 3.0.8 (arm64)

### Operating system

MacOS 12.6 arm64

**Comment by steveward** [comment]
Thanks for the issue and PR @daniel-ciaglia!
