### ISSUE TITLE
Robert Taak report bug

### ISSUE THREAD

**Issue by AatroxPegger** [desktop/desktop#15351]
### The problem

Ik heb de game opgestart en de console detecteerde direct dat er een connectie probleem was met een code. Het zegt dat het eind stuk van de code niet bestaat. De code staat in index.html bij polyfill.js:1188:20.

### Release version

Version 3.0.8 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

```mermaid
flowchart TB
A[vscode opgestart] 
B[Game opgestart op google via Live Server]
C[Ik heb de console open gedaan]
D[De console detecteerd een bug]
E[Een uncaught error was gevonden waar er geen conectie kon gemaakt worden]
F[Het zegt dat het eind stuk van de code niet bestaat]
G["reject(new Error(extensionAPIs.runtime.lastError.message));" moest er in de plaats gebeuren]
H[De bug kan je terugvinden bij polyfill.js:1188:20 van index.html]

A-->B
B-->C
C-->D
D-->E
E-->F
F-->G
G-->H
```

**Comment by niik** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
