### ISSUE TITLE
Changing Ignored Files fails with a CRLF error

### ISSUE THREAD

**Issue by ThirtySomething** [desktop/desktop#1535]
### Description

By changing the ignored files, the git error message "fatal: LF would be replaced by CRLF in .gitignore" appears.

### Version

**GitHub Desktop version:** 0.5.3

**OS version:** Microsoft Windows Version 6.1.7601

### Steps to Reproduce

1. Open a github project from your project list.
1. Open the "Repository" menu in the menu bar.
1. Select "Repository settings" in the menu.
1. Select "Ignored files" in the dialog.
1. Change something inside the edit field, for example manually delete and retrype an existing entry. Don't forget to press the enter key.
1. Click the "Save" button.
1. On the lower left fill out the commit dialog and press "Commit to master".
1. The error message "fatal: LF would be replaced by CRLF in .gitignore" appears in a dialog box.

**Expected behaviour:** The line endings should not be changed. The file .gitignore is already switched to Windows line endings.

**Actual behaviour:** Looks like the line endings are changed to be in Unix format.

**Reproduces how often:** Every test by changing the file .gitignore using the new Github Desktop software.

### Logs

Could not find any logfile of the software.

**Comment by shiftkey** [comment]
@ThirtySomething nice find!

Could you also include the contents of your global `.gitconfig` - I think there's a value in there we haven't anticipated.

**Comment by ThirtySomething** [comment]
Hello @shiftkey ,

the content of my `.gitconfig`  file is

> [user]
> 	name = ThirtySomething
> 	email = \<my email address here\>
> [core]
> 	autocrlf = true
> 	safecrlf = true
> 	autorrlf = true
> [merge]
> 	tool = kdiff3
> [mergetool "kdiff3"]
> 	path = \<path to program\>
> [diff]
> 	guitool = kdiff3
> [difftool "kdiff3"]
> 	path = \<path to program\>
> [gui]
> 	recentrepo = \<path to repo\>
> [filter "lfs"]
> 	clean = git-lfs clean -- %f
> 	smudge = git-lfs smudge -- %f
> 	process = git-lfs filter-process
> 	required = true
>

**Comment by shiftkey** [comment]
@ThirtySomething Apologies for the delay on this. I've traced it to the use of `core.safecrlf = true` which, as per [the docs](https://git-scm.com/docs/git-config#git-config-coresafecrlf), seems to be doing it's thing:

> If true, makes Git check if converting `CRLF` is reversible when end-of-line conversion is active. Git will verify if a command modifies a file in the work tree either directly or indirectly. For example, committing a file followed by checking out the same file should yield the original file in the work tree. If this is not the case for the current setting of `core.autocrlf`, Git will reject the file. The variable can be set to "warn", in which case Git will only warn about an irreversible conversion but continue the operation.

My gut feeling here is that we need to respect the `autocrlf` or `safecrlf` settings here when updating the gitignore file. It should be easy to get this flow into a sample repository, but at least we know where the problem lies.

PS: `core.autorrlf` isn't a know config value, I gather that's just a typo.

**Comment by shiftkey** [comment]
Making a start on some tests here, but line endings are Danger Zone™ and need some thought so I'm not sure where to prioritize this:

https://github.com/desktop/desktop/compare/respect-your-line-endings?expand=1

Probably for the M6 milestone, cc @jsohaber for feels

**Comment by ThirtySomething** [comment]
Hello @shiftkey ,

you're right, line endings are danger zone. Usually I edit the <code>.gitignore</code> in my favorite editor which keeps the format of the line endings. For my side I judge the bug with an average to low priority.

And you're right again - <code>core.autorrlf</code> is a typo. Thanks for hint, I've removed it from my config.

**Comment by joshaber** [comment]
>@jsohaber

new username who dis

I'm gonna stick it in the 1.0 milestone for now.
