### ISSUE TITLE
RangeError: Invalid string length (History can't be opened / Github Desktop crashes)

### ISSUE THREAD

**Issue by Reecstuff** [desktop/desktop#15355]
### The problem

# You have long waiting Time upon clicking on **History**?
# You get stuck waiting for **History** to open?
# Your Github Desktop crashes after a few seconds and you see the error ``RangeError: Invalid String Length`` as posted in the screenshot down below?
<br/>
So congratulation you have a commit message in your History that is too long for the UI to load 🎉 <br/>
This happens because you used **Squash and merge** too often in your repo. **Squash and merge** generates a commit message description that includes all of your commits and all commits of other **Squash and merge** commits. After using this for a while your message gets so long it increases the loading time of your history and in the end crashes GitHub Desktop. You can also reproduce this behavior with every other Git Client, like Git Fork if you click on the bugged commit. Because GitHub Desktop loads your history in the background after startup it crashes after a few seconds upon finding the string the UI can't handle.

# How to solve this (until it is fixed)?
That's easy "just" make a new repo and delete the old one.
The complete history ist bugged because of this and you can only open the history via ``git log`` in a command line tool like Git Bash.

Save your local files and remove all git related files / folders from your project. Delete your old Repo on the server. Create a new Repository and clone it, drag your old files into your new repository, commit, push and done.

# How to prevent this from happening?
Currently you should not use **Squash and merge** and just use normal **merge**.
Or you could amend your commit after **Squash and merge** before pushing and delete the description.

# What would I except of Squash and merge?
Squash and merge should not generate a description which includes all commits. I just need a Title like "Squash and merge ``otherbranch`` into ``currentbranch``" instead of the currently misleading message "Squashed commit of the following:". Most of the time you only see the title and the description is one click too far away.

### Release version

3.0.8

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Setup new Repo
2. Create two or more branches beside ``main`` (I name them here ``branch1`` and ``branch2``
3. **Squash and merge** ``main`` into ``branch1``
4. Commit multiple commits into ``branch1`` (the more the better)
5. **Squash and merge** ``branch1`` into ``main``
6. **Squash and merge** ``main`` into ``branch2``
7. Commit multiple commits into ``branch2``
8. **Squash and merge** ``main`` into ``branch2``
9. **Squash and merge** ``branch2`` into ``main``
10. Repeat steps 3-9

With this setup you should only have "Squashed commit of the following:" commits in your history, so the commit messages stack up nicely and the description string of your commits gets longer and longer. After some time you will notice that your history loads slower and gets stuck after more commits. If you go even further Github Desktop will show you the expected Error ``RangeError: Invalid string length``.

An important thing to note: All your other Repos are still working in Github Desktop, just switch to them and the history opens as expected.

### Screenshots

![Invalid_String_Length_Error](https://user-images.githubusercontent.com/26374772/192094450-fd3e109b-59d5-4028-83b4-e654760a30ae.png)

### Additional context

As @steveward mentioned in #13006 I should put this into a new Issue and here it is.

**Comment by suhasabhishek** [comment]
@Reecstuff Can I work on this?

**Comment by adnan-nazir** [comment]
Facing the same issue.

<img width="597" alt="Screenshot 2024-01-22 at 6 02 54 PM" src="https://github.com/desktop/desktop/assets/107183643/a771210a-95fe-4961-bcda-b96b409362ae">

**Comment by adnan-nazir** [comment]
History is not loading and its continuously throws exception "**RangeError: Invalid string length**
"

<img width="965" alt="Screenshot 2024-01-22 at 6 06 40 PM" src="https://github.com/desktop/desktop/assets/107183643/125ab92f-1fe0-43c3-9624-44314dbf32de">

**Comment by adnan-nazir** [comment]
I'm facing the same issue on MacBook Pro (15-inch, 2019).  
Not only the cases written above. Github is unable to merge code properly, even I  GitHub desktop application is crashing and throwing the exception(attached screenshot).

<img width="595" alt="Screenshot 2024-01-23 at 3 13 00 PM" src="https://github.com/desktop/desktop/assets/107183643/021c986d-89c3-4ceb-ac30-c3c5a4c91083">

**Comment by niik** [comment]
Alright, I finally found some time to take a look at this. The reproduction steps here essentially aim to create a huge commit message. This happens because of Git's automatic commit message generation when doing `git merge --squash`.

Squashing a bunch of commits from one branch will generate a message similar to this:

```
Squashed commit of the following:
    
    commit 4837624bafb3598dca0281b992977732e13e0880
    Author: Markus Olsson <j.markus.olsson@gmail.com>
    Date:   Thu Nov 21 12:05:27 2024 +0100

   Oh hai
```

Squashing that one more time will indent and append the previous commit message

```
    Squashed commit of the following:
    
    commit 4837624bafb3598dca0281b992977732e13e0880
    Author: Markus Olsson <j.markus.olsson@gmail.com>
    Date:   Thu Nov 21 12:05:27 2024 +0100
    
        Squashed commit of the following:
    
        commit bc24766bf859deb6b49fea6edda531cff5449f39
        Author: Markus Olsson <j.markus.olsson@gmail.com>
        Date:   Thu Nov 21 12:03:34 2024 +0100
```

And so on and so forth, done enough times this will create a commit message that exceeds V8's maximum string length of 500Mb and crash the app. Now, while it'd be a nice improvement if we offered the user a chance to edit the commit message when squashing this type of back and forth squashing operation would cause a commit message of equal length if performed on the command line. Having a commit message that long is at best not useful and at worst a huge detriment to performance and storage costs and should be avoided. I don't know if there's a workflow that would require this type ping-pong squashing but I'm assuming so since this issue exists. Ultimately though this seems like an issue with the flow rather than a technical one. While Desktop could certainly deviate from Git's built-in behavior and generate a commit message that doesn't include all the details from the commits that made up the squash commit I'm assuming there was a reason Git made it do so by default and not being a squash enthusiast myself I don't feel like I have enough context to make a call on that.

Moving on to the second part of the problem though, when presented with a commit where the message exceeds 500Mb Github Desktop will crash. That part we can fix though the priority of fixing it is debatable since it should be exceedingly rare to have commit messages exceeding 500Mb (Iyou wouldn't ever be able to push that to GitHub, due to our size limitations).

Regardless, let's start with a reproduction that ignore the squashing in favor of just creating a huge commit. Here's a quick and dirty approach: 

```shell
% echo "WHAT HAVE I DONE" > README.txt
% git add README.txt 
% cat /dev/urandom | base64 | fold -w 72 | cat <(echo -e "The World's Most Descriptive Commit Message\n") - | head -c 629145600 | git commit -F -
```

I'm gonna take a look at this as part of the other large git output work I'm doing

**Comment by yanimda** [comment]
> ### Sorun
> # **Geçmiş'e** tıkladığınızda uzun süre beklemeniz mi gerekiyor ?
> # **Tarihin** açılmasını beklerken sıkışıp kaldınız mı ?
> # Github Masaüstünüz birkaç saniye sonra çöküyor ve `RangeError: Invalid String Length`aşağıdaki ekran görüntüsünde gösterilen hatayı mı görüyorsunuz?
> 
> Tebrikler, Geçmişinizde kullanıcı arayüzünün yükleyemeyeceği kadar uzun bir commit mesajınız var 🎉
> Bunun nedeni deponuzda **Squash and merge**'i çok sık kullanmanızdır. **Squash and merge**, tüm commit'lerinizi ve diğer **Squash and merge** commit'lerinin tüm commit'lerini içeren bir commit mesajı açıklaması oluşturur. Bunu bir süre kullandıktan sonra mesajınız o kadar uzun olur ki geçmişinizin yükleme süresini artırır ve sonunda GitHub Desktop'ı çökertir. Hatalı commit'e tıkladığınızda Git Fork gibi diğer tüm Git İstemcilerinde de bu davranışı tekrarlayabilirsiniz. GitHub Desktop, başlatma işleminden sonra geçmişinizi arka planda yüklediği için kullanıcı arayüzünün işleyemediği dizeyi bulduktan sonra birkaç saniye sonra çöker.
> # Bu sorunu nasıl çözebiliriz (düzeltilene kadar)?
> Bu kolay "sadece" yeni bir depo oluştur ve eskisini sil. Bu yüzden tam geçmiş hatalıdır ve geçmişi yalnızca Git Bash gibi bir komut satırı aracıyla açabilirsiniz .`git log`
> 
> Yerel dosyalarınızı kaydedin ve projenizden git ile ilgili tüm dosyaları/klasörleri kaldırın. Sunucudaki eski Deponuzu silin. Yeni bir Depo oluşturun ve klonlayın, eski dosyalarınızı yeni deponuza sürükleyin, commit edin, push edin ve tamamdır.
> 
> # Bunun olmasını nasıl önleyebiliriz?
> **Şu anda Squash ve merge** kullanmamalı ve sadece normal **merge** kullanmalısınız . Ya da **Squash ve merge'den** sonra commit'inizi değiştirebilir ve push'tan önce açıklamayı silebilir ve birleştirebilirsiniz.****
> 
> # Squash ve merge'den ne beklerim?
> Squash ve merge, tüm commit'leri içeren bir açıklama üretmemelidir. Şu anda yanıltıcı olan "Squash and merge into" mesajı yerine sadece "Squash and merge `otherbranch`into " gibi bir Başlığa ihtiyacım var `currentbranch`:". Çoğu zaman sadece başlığı görürsünüz ve açıklama bir tık uzaktadır.
> 
> ### Sürümü yayınla
> 3.0.8
> 
> ### İşletim sistemi
> Windows 11
> 
> ### Davranışı yeniden üretme adımları
> 1. Yeni Depo Kurulumu
> 2. Yan yana iki veya daha fazla dal oluşturun `main`(bunlara burada isim veriyorum `branch1`ve`branch2`
> 3. **Ezmek ve** `main` birleştirmek`branch1`
> 4. Commit multiple commits into `branch1` (the more the better)
> 5. **Squash and merge** `branch1` into `main`
> 6. **Squash and merge** `main` into `branch2`
> 7. Commit multiple commits into `branch2`
> 8. **Squash and merge** `main` into `branch2`
> 9. **Squash and merge** `branch2` into `main`
> 10. Repeat steps 3-9
> 
> With this setup you should only have "Squashed commit of the following:" commits in your history, so the commit messages stack up nicely and the description string of your commits gets longer and longer. After some time you will notice that your history loads slower and gets stuck after more commits. If you go even further Github Desktop will show you the expected Error `RangeError: Invalid string length`.
> 
> An important thing to note: All your other Repos are still working in Github Desktop, just switch to them and the history opens as expected.
> 
> ### Log files
> _No response_
> 
> ### Screenshots
> ![Geçersiz_Dize_Uzunluğu_Hatası](https://user-images.githubusercontent.com/26374772/192094450-fd3e109b-59d5-4028-83b4-e654760a30ae.png)
> 
> ### Additional context
> As @steveward mentioned in #13006 I should put this into a new Issue and here it is.
