### ISSUE TITLE
Unable to push, clone, or create new repos with Github Desktop, Git Kraken or Bit Bucket.

### ISSUE THREAD

**Issue by AngrySpartan** [desktop/desktop#15358]
### The problem

I have been using git Kraken until recently. I had GPG Keys set up and was using them fine. The did not expire and suddenly no longer worked. I kept getting and LFS.locksveried error. I tried to follow all of the advice I found, and set the option to false. Irritated, I thought I would give the Desktop version another try. It couldn't even find my keys. So I loaded my SSH Keys.  I have since revoked and deleted all of the keys and made new ones. Nothing was working. Now if I have it set up for only SSH keys. For whatever reason it keeps trying to just pull from a temp file. I am completely unable to use Git with any kind of GUI application. 
<img width="523" alt="Gitdesktop_Error" src="https://user-images.githubusercontent.com/11233939/192112916-82138657-e110-424d-9ae8-20acf30a8baf.png">

### Release version

Version 3.0.8 (x64)

### Operating system

Device name	Angry-MSI-Dev Processor	12th Gen Intel(R) Core(TM) i9-12900H   2.90 GHz Installed RAM	32.0 GB (31.7 GB usable) Device ID	33DCB148-049D-4C0A-A91C-50003C178E20 Product ID	00355-60684-32545-AAOEM System type	64-bit operating system,

### Log files

[2022-09-24.desktop.production.log](https://github.com/desktop/desktop/files/9639320/2022-09-24.desktop.production.log)

### Screenshots

<img width="523" alt="Gitdesktop_Error" src="https://user-images.githubusercontent.com/11233939/192112947-1ead195a-79b2-4cbe-9aff-604a86537d1a.png">

**Comment by tsvetilian-ty** [comment]
@AngrySpartan thanks for reaching out! You're receiving a `Permission denied (publickey)`, meaning that the server rejected your connection. In the [troubleshooting section](https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey) of GitHub docs, you could check several suggestions on how to fix it.
