### ISSUE TITLE
Always Crash

### ISSUE THREAD

**Issue by ahmedsaidzahran** [desktop/desktop#15366]
When open the app, it always crash, aslo in many cases when push commit it crashes, so I had to undo the commit and make it again 
![2022-09-26_16-16-38](https://user-images.githubusercontent.com/17543324/192299864-79ea574d-bfd9-461f-9146-5950572694fd.png)

**Comment by steveward** [comment]
Thanks for the issue @ahmedsaidzahran, this is being tracked in https://github.com/desktop/desktop/issues/15355 so I'm going to close this issue out.

If you have any additional steps you can share about how you ran into this bug please feel free to add them to that issue.
