### ISSUE TITLE
Quick switch between accounts

### ISSUE THREAD

**Issue by Hesham-Dev-LY** [desktop/desktop#15364]
### The feature request

Please facilitate the process of switching between accounts in the way you see fit for you, daily I log out of one account and enter another, this process is not practical.

### Proposed solution

 I wish to save accounts for easy switching between them

**Comment by steveward** [comment]
Thanks for the issue @Hesham-Dev-LY. This is being tracked in https://github.com/desktop/desktop/issues/3707 -- you can follow along there for updates.
