### ISSUE TITLE
Can pull but not push private gist

### ISSUE THREAD

**Issue by CTimmerman** [desktop/desktop#15360]
### The problem

![image](https://user-images.githubusercontent.com/9662163/192174678-1273233f-908f-4c74-809f-f744a720adf6.png)

Even though I've authenticated GitHub Desktop in my browser and it can clone my private gist from that browser.

### Release version

Version 3.0.8 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Clone a private gist to prove auth works. Try to push to it.

### Additional context

Also fails in VS Code:
`[2022-09-26T01:02:22.289Z] remote: Repository not found.`

That's for the private gist i had no problem updating from VS Code before.

This is for trying to push to a public gist:
```
[2022-09-26T01:03:03.485Z] > git log --oneline --cherry master...master@{upstream} -- [55ms]
[2022-09-26T01:03:03.976Z] > git pull --tags origin master [484ms]
[2022-09-26T01:03:03.976Z] From https://gist.github.com/6d1fc20c3fb61ef0ba3e2d6de2c582ce
 * branch            master     -> FETCH_HEAD
[2022-09-26T01:03:05.215Z] > git ls-files --stage -- C:\Users\C\Documents\code\OOM_killer\OOM_killer.py [45ms]
[2022-09-26T01:03:05.274Z] > git cat-file -s <some hash i can't find> [53ms]
[2022-09-26T01:03:05.334Z] > git show --textconv :OOM_killer.py [51ms]
[2022-09-26T01:03:05.730Z] > git push origin master:master [1748ms]
[2022-09-26T01:03:05.730Z] remote: Permission to write to gist denied.
fatal: unable to access 'https://gist.github.com/6d1fc20c3fb61ef0ba3e2d6de2c582ce/': The requested URL returned error: 403
```

**Comment by CTimmerman** [comment]
Command line git login fixed using personal access token (PAT) from https://github.com/settings/tokens
Microsoft documentation is fractured lately.
```
D:\Games\CockatricePortable\data\decks>git pull
<Cancel GUI prompt>
Logon failed, use ctrl+c to cancel basic credential prompt.
Username for 'https://github.com': CTimmerman
Password for 'https://CTimmerman@github.com': <Paste PAT here>
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 10 (delta 7), reused 10 (delta 7), pack-reused 0
Unpacking objects: 100% (10/10), 2.97 KiB | 7.00 KiB/s, done.
From https://github.com/CTimmerman/decks
   8c9cfcf..83e3d2f  master     -> origin/master
error: Your local changes to the following files would be overwritten by merge:
        Licia.cod
        deck_ranks.txt
Please commit your changes or stash them before you merge.
Aborting
Updating 8c9cfcf..83e3d2f
```

That also fixed pushing in VS Code, but not GitHub Desktop. I regenerated the token again and pasted into GitHub Desktop's password box, which fixed that, unlike CLI git's GUI password box, but CLI git's CLI password input worked again.

**Comment by steveward** [comment]
Thanks for the issue @CTimmerman. This is a known bug -- when trying to push commits to a gist, GitHub Desktop will fall back to basic authentication and not detect your current credentials. As a workaround for this you should be able to drop into the command line and run a `git push` to push your changes. 

See https://github.com/desktop/desktop/issues/2973 for more information about some of the known issues with using gists in GitHub Desktop.  I am going to reference this issue in #2973 and close it out for the time being as we're not prioritizing gists in GitHub Desktop at this time.
