### ISSUE TITLE
Black screen after first run

### ISSUE THREAD

**Issue by ajsb85** [desktop/desktop#1536]
### Description

Black screen after first run.

### Version 

**GitHub Desktop version:** 0.5.3

**OS version:** Microsoft Windows [Version 10.0.16193.1001]

### Steps to Reproduce

1. Install
1. Run the app

**Expected behaviour:** Normal window

**Actual behaviour:** Black window

**Reproduces how often:** 100%

### Logs

2017-05-17T07:48:52.846Z - error: Uncaught exception on main process

**Comment by tierninho** [comment]
Believe this is related to: https://github.com/desktop/desktop/issues/1502

**Comment by ajsb85** [comment]
And #1436

**Comment by niik** [comment]
> 2017-05-17T07:48:52.846Z - error: Uncaught exception on main process

@ajsb85 Is that the only thing you see in the log files? No exception stack in close proximity to that?

**Comment by ajsb85** [comment]
Yes @niik 

No more lines for the log.

**Comment by ajsb85** [comment]
Nice to test:

https://github.com/electron/electron/issues/2479#issuecomment-130307655

**Comment by joshaber** [comment]
@ajsb85 We haven't been able to reproduce this. Are you still seeing it on 0.6.0?

**Comment by ajsb85** [comment]
It's works.

Maybe related to Windows Insider program and NVidia drivers.

**Comment by LaurentFromParis** [comment]
There is the same issue with chrome. It must be launched without graphic acceleration.
Is there such an option for githubdesktop ?

**Comment by niik** [comment]
> There is the same issue with chrome. It must be launched without graphic acceleration.
> Is there such an option for githubdesktop ?

There's no such option at the moment. If you'd like to take a stab at adding it Electron has a method called [disableHardwareAcceleration](https://electron.atom.io/docs/api/app/#appdisablehardwareacceleration) that we could call prior to the app ready event. We could toggle it using an environment variable perhaps.
