### ISSUE TITLE
Github Desktop not reading folder contents Mac OS

### ISSUE THREAD

**Issue by Zlitchufdux** [desktop/desktop#15370]
### The problem

After I have cloned a git repo using Github Desktop, I create a C# program from Visual Studio 2022 (Mac) and add my files and such in it. So, the structure looks like this:

**class-demo-09-26-Zlitchufdux** (Git Cloned Folder)
     **Demo** (Folder)
          **Demo926** (Subfolder)
              **bin** (Subfolder)
               Demo.csproj (File)
               **obj** (Subfolder)
               Program.cs (File)
          Demo926.sln (File)
     README.md (File)

After I save, I go to Github desktop to commit and push back up to the master branch, but the app only sees the folder **Demo** and does not see the files or subfolders in the folder. 

I tested to see if it would see regular files and it does. But will not read the files and subfolders in **Demo** folder.

If I commit and push, it only pushes the **Demo** folder to the repository but with no files or subfolders in it.

I cannot get Github desktop to see the files or subfolders within the **Demo** folder I created. 

### Release version

3.0.8

### Operating system

Mac OS

### Additional context

![SCR-20220926-i34](https://user-images.githubusercontent.com/76977280/192385318-e19e43cb-9da9-4a1f-a6fb-5219d7d92a9c.jpeg)
![SCR-20220926-i8h](https://user-images.githubusercontent.com/76977280/192385331-b597eee1-756f-455c-8825-7be2b3503989.jpeg)

**Comment by tsvetilian-ty** [comment]
Hey @Zlitchufdux 👋 Git doesn't track empty folders! Do you have any files inside the folders?

**Comment by Zlitchufdux** [comment]
@tsvetilian-ty There are folders inside of that folder as well as files inside of that folder and Github desktop will not see the files within the folder so I can push it back to the repository

**Comment by Zlitchufdux** [comment]
> Hey @Zlitchufdux 👋 Git doesn't track empty folders! Do you have any files inside the folders?

There are folders inside of that folder as well as files inside of that folder and Github desktop will not see the files within the folder so I can push it back to the repository

**Comment by tsvetilian-ty** [comment]
Could you run `git status` from the command line?

**Comment by Zlitchufdux** [comment]
> Could you run `git status` from the command line?

It says this


On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .DS_Store

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Demo926/

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by Zlitchufdux** [comment]
![SCR-20220926-kzm](https://user-images.githubusercontent.com/76977280/192389173-01d10a0f-9e7a-4820-9cb6-31594095bf2f.jpeg)

**Comment by Zlitchufdux** [comment]
Here is a better example to show that there are files in that folder and that Github Desktop will not see that they exist.

![SCR-20220926-kzm](https://user-images.githubusercontent.com/76977280/192389271-e411c3a3-e2bd-4e93-b431-b1a6a2b90248.jpeg)

**Comment by tsvetilian-ty** [comment]
Strangely, Demo926 is registered as an empty file 🤔 Are you using submodules? Also, could you share your log file (Help > Show logs in ...)?

I see you have another folder with the same name as your current `class-demo-09-28-....`, which is strange as well 🤔

**Comment by Zlitchufdux** [comment]
> Strangely, Demo926 is registered as an empty file 🤔 Are you using submodules? Also, could you share your log file (Help > Show logs in ...)?
> 
> I see you have another folder with the same name as your current `class-demo-09-28-....`, which is strange as well 🤔

it is odd that it’s registered as an empty file, and as we can see, it actually has files in it.

I had to run to work unfortunately, but I can share the logs when I get home. 

Sub modules in Visual Studio?! I am drawing a blank on what that is or where it is located. I am doing this for college. So it’s new to me.

Ignore the second folder, that was a test for something 

I tested this multiple times with the same results that GitHub won’t read the folders and items in it

**Comment by aminwafi** [comment]
I am also facing similar issue, did you discover any fix for this

**Comment by Bugrabugra** [comment]
My solution was pretty simple. I was using Nest.js' CLI tool to create projects inside a git repo (a giant mono repo) and the files were missing at GitHub Desktop. The thing was CLI was creating its own git repo inside projects so basically it was git repo inside another git repo so my GH Desktop was not showing me the files. I have deleted the inner git repos inside my projects so everything is fine.

**Comment by cssninja** [comment]
If this helps .. when I have my Github folder open on my Mac .. then push code to the Github repo online (using Github Desktop) .. the Github Desktop app will keep requesting to update the repo (only they are dB files or something, .DS_store) .. so I have to push that code again, sometimes a few times until it stops .. then I found that by simply CLOSING the Mac Github folder it solves this problem .. that is .. it is a caching issue, where the open Mac folder is not updating it's cache, so by simply closing it the folder UPDATES PROPERLY. I may not be fully getting it but I know that if the folder is CLOSED then Github Desktop will stop asking to push dB files to the online GIthub repo. Ref: https://stackoverflow.com/search?q=.ds_store+mac

**Comment by piyushdaryanani** [comment]
Ramin

**Comment by IAmKio** [comment]
> My solution was pretty simple. I was using Nest.js' CLI tool to create projects inside a git repo (a giant mono repo) and the files were missing at GitHub Desktop. The thing was CLI was creating its own git repo inside projects so basically it was git repo inside another git repo so my GH Desktop was not showing me the files. I have deleted the inner git repos inside my projects so everything is fine.

It's 2026 and this was the solution for me - Anchor CLI created it's own Git repo
