### ISSUE TITLE
Cherrypicking to new branch hidden when navigated away to different screen resulting in disabling cherrypick

### ISSUE THREAD

**Issue by pkongara-mn** [desktop/desktop#15371]
### The problem

Cherrypicking is disabled forever when the user navigated away to a different screen during cherrypicking to a new branch. 

Steps to Reproduce:
1. Navigate to branch history and select commits to cherrypick.
2. This opens a popup for branch selection.
3. Click on a new branch.
4. Navigate to any other screen, this will hide cherrypicking to the branch selection popup.
5. This also disables further cherrypick options

### Release version

Version 3.0.8 (x64)

### Operating system

Windows

### Steps to reproduce the behavior

Steps to Reproduce:
1. Navigate to branch history and select commits to cherrypick.
2. This opens a popup for branch selection.
3. Click on new branch.
4. Navigate to any other screen, this will hide cherrypicking to branch selection popup.
5. This also disables further cherrypick option.

### Screenshots

![CherryPickDisabled](https://user-images.githubusercontent.com/55270662/192433763-b5e78a97-12e1-4857-a9f5-cb425055b730.PNG)

**Comment by steveward** [comment]
Thanks for the report @pkongara-mn. This looks like the same issue as https://github.com/desktop/desktop/issues/13977. I'm going to reference this issue there, and close this out. You can follow along there for updates.

You should be able to resolve this by restarting the app.
