### ISSUE TITLE
Cannot Uninstall Machine Wide Installer 2.5.3.0

### ISSUE THREAD

**Issue by davideverall** [desktop/desktop#15373]
### The problem

I have an old version of the Github Desktop Machine-Wide Installer (2.5.3.0) and am unable to uninstall as the msi no longer exists on the machine.

I have tried to uninstall with newer versions of the msi using `msiexec /x` however this also fails due to incorrect version msi.

Is there an archive to download old versions of the machine wide installer?

### Release version

2.5.3.0

### Operating system

Windows 10

**Comment by steveward** [comment]
Thanks for the issue @davideverall. Have you tried using [Microsoft's Program Install and Uninstall Troubleshooter](https://support.microsoft.com/en-us/topic/fix-problems-that-block-programs-from-being-installed-or-removed-cca7d1b6-65a9-3d98-426b-e9f927e1eb4d)? That may be the quickest way to remove it from your system.

**Comment by davideverall** [comment]
Thanks for your suggestion.

I can confirm that the Microsoft Troubleshooter did the trick! The issue can be closed now.

Kind regards

David
