### ISSUE TITLE
Clone spring-boot project error

### ISSUE THREAD

**Issue by shadowoss** [desktop/desktop#15381]
### The problem

Clone spring-boot project error

### Release version

Version 3.0.8 (x64)

### Operating system

Windows11

### Log files

Cloning into 'D:\project\spring\spring-boot'...
remote: Enumerating objects: 723456, done.        
remote: Counting objects: 100% (453/453), done.        
remote: Compressing objects: 100% (216/216), done.        
remote: Total 723456 (delta 95), reused 422 (delta 88), pack-reused 723003        
Receiving objects: 100% (723456/723456), 146.16 MiB | 15.53 MiB/s, done.
Resolving deltas: 100% (319304/319304), done.
error: unable to create file spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/test/resources/org/springframework/boot/gradle/plugin/NativeImagePluginActionIntegrationTests-reachabilityMetadataConfigurationFilesFromFileRepositoryAreCopiedToJar.gradle: Filename too long
error: unable to create file spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/test/resources/org/springframework/boot/gradle/tasks/buildinfo/BuildInfoIntegrationTests-notUpToDateWhenExecutedTwiceWithFixedTimeAndChangedGradlePropertiesProjectVersion.gradle: Filename too long
error: unable to create file spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/test/resources/org/springframework/boot/gradle/tasks/bundling/BootJarIntegrationTests-whenAResolvableCopyOfAnUnresolvableConfigurationIsResolvedThenResolutionSucceeds.gradle: Filename too long
Updating files: 100% (8620/8620), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

Would you like to retry cloning ?

**Comment by ShadowOSS** [comment]
1.

**Comment by shadowoss** [comment]
git config --global core.longpaths true
