### ISSUE TITLE
problemas al intentar loguearme desde la aplicación desktop

### ISSUE THREAD

**Issue by maykolltwin** [desktop/desktop#15386]
### The problem

intento loguearme desde la aplicación desktop. me remite hacia el logueo de la página web y cuando me redirecciona nuevamente a la aplicación desktop entonces se queda en el mismo lugar y no se loguea localmente.

### Release version

Version 3.0.8 (x64)

### Operating system

windows 10

### Screenshots

![imagen](https://user-images.githubusercontent.com/114093040/193125222-2072ed86-65ef-4c4f-902b-515c436553c4.png)

**Comment by sergiou87** [comment]
Hola @maykolltwin !

Es posible que tengas instalado algún antivirus o firewall? Alguna vez ocurre que cuando sacamos actualizaciones, los antivirus/firewall/loquesea bloquean archivos o conexiones de GitHub Desktop y causan estos problemas. Prueba a desactivar tu antivirus/firewall (y quizás a reinstalar GitHub Desktop) y después a ver si funciona el login 🤞

**Comment by EVerjanoPerez** [comment]
Hola buenas, espero que me puedan ayudar.
Cuando le doy en "sing in usisng your browser"  a "continue with browser" se queda ahí pillado.

![image](https://user-images.githubusercontent.com/71347366/217320304-3710be20-2357-4a73-812b-a98953d6db97.png)
