### ISSUE TITLE
Zoom out (Ctrl+-) not working

### ISSUE THREAD

**Issue by pawa2007** [desktop/desktop#15380]
### The problem

Go to **View > Zoom out** or hit **Ctrl+-**, the view does not change. Zoom in works fine.

### Release version

Version 3.0.8 (x64)

### Operating system

Windows 11 Pro (Version 21H2) (OS build 22000.978)

### Steps to reproduce the behavior

1. Go to **View > Zoom out** or hit **Ctrl+-**, the view does not change. Zoom in works fine.

**Comment by tsvetilian-ty** [comment]
@pawa2007 thanks for reaching out! Are you using `-` from the numpad?

**Comment by pawa2007** [comment]
@tsvetilian-ty I am using `-` from the regular keyboard (the one with the `-` and the `_` on it).

**Comment by tidy-dev** [comment]
@pawa2007 Are you expecting to zoom out to below 100%? 

Desktop does not support that. Thus, if you zoom in to something like 110%, 125%, 150%, then the zoom out function will work to decrease it, but you cannot zoom out farther than 100%.

**Comment by pawa2007** [comment]
@tidy-dev Yes. I was trying to zoom out below 100%. Can we please add this as a feature request?
