### ISSUE TITLE
Doesn't look like we ever prune log files

### ISSUE THREAD

**Issue by niik** [desktop/desktop#1540]
Just spotted this working on #1534.

![image](https://cloud.githubusercontent.com/assets/634063/26146547/d8076a92-3af0-11e7-9ebf-d11dd8d696da.png)

We really ought to clean up logs after some reasonable amount of time, say 14 days or so

**Comment by shiftkey** [comment]
Idea: see if we can repurpose whatever logic is used in [`winston-logrotate`](https://www.npmjs.com/package/winston-logrotate) - which supports keeping N files - and get those into [`winston-daily-rotate-file`](https://www.npmjs.com/package/winston-daily-rotate-file) which we're currently using...
