### ISSUE TITLE
jump to a specific file in changes 

### ISSUE THREAD

**Issue by talwgx** [desktop/desktop#15403]
### The feature request

if i have a long list of changed files (10-100s), there isn't the ability to jump to a specific file in that list that I could find. I have to select all the files, right click, copy paths to a text editor, search there, and  then try to correlate the line number to the actual list back in my GH desktop (OSX).

### Proposed solution

Add the ability to jump to a file in the "Changes" list by typing its name etc..

**Comment by tidy-dev** [comment]
@talwgx Thank you for the suggestion. This feels like along the same lines as https://github.com/desktop/desktop/issues/6407. I am going to close this in favor of tracking feedback there.
