### ISSUE TITLE
Can't Find Repository It was last seen

### ISSUE THREAD

**Issue by fxairell99** [desktop/desktop#15406]
### The problem

I put my desktop to sleep for I think around 2 to 3 hours, I didn't have any commit at the current, but when I wanted to use Github Desktop, it already was like this.
![image](https://user-images.githubusercontent.com/109941074/193735334-b4988345-0e2c-4966-b6a4-1f394b076d70.png)

I don't know how to handle this problem as I already have been convenient using Github Desktop. Things I have tried to solve the problem:
1. Remove and add local repository again
2. Remove all %APPDATA%\GitHub Desktop\ data
3. Uninstall and install Github Desktop again

How can I solve the problem? Even when I create new clone repository, the prompt still appear while before that the screen doesn't have a problem.

### Release version

3.0.8

### Operating system

Windows 11 Pro

### Steps to reproduce the behavior

1. Open Github Desktop
2. If there is repository open, then the error will already be there
3. Add local repository
4. Find local repository folder and click to add local repository
5. The error will be there
6. Clone new repository
7. Select new folder to store into local repository
8. The error will be there

### Log files

[2022-10-04.desktop.production.log](https://github.com/desktop/desktop/files/9702843/2022-10-04.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/109941074/193736165-a7526d84-072c-4177-9e12-9ab1f30b1c7a.png)

**Comment by tidy-dev** [comment]
@fxairell99 Thank you for reaching out. ~~Could you provide the logs for when you try to add this repository to Desktop? You can find them by going to Help > Show logs in explorer~~ Nvm.. scrolled through them the first time.

**Comment by tidy-dev** [comment]
Curious if you could try moving the repository to another directory? Wondering if it could be related to access or whether the repository is stored in cloud storage environment?

**Comment by fxairell99** [comment]
Hello. I had moved the repository to another directory above it, and it worked. I had made several new folder to test whether it just the folder related. It is currently solved as I clone the repository to directory above it. Is it a bug for Github Desktop to be like that?

**Comment by tidy-dev** [comment]
I don't think it is bug... If GitHub Desktop cannot read the directory that the repository is placed in, it will show what you are seeing -> it cannot find it. My assumption is there is some reason in your environment that GitHub Desktop cannot read that directory. But, I don't know how to reproduce it. If you have more information about the difference in directories that would be appreciated. 

Since your issue appears resolved, I am going to close it unless it can be determined that this is unique to GitHub Desktop.

**Comment by Glasgray** [comment]
I also had this issue, for me it was due to changes in the repo folder contents. For instance when my code saved outputs to the repo folder, it resulted in Github Desktop being unable to access the repo due to there being changed contents in the folder. When I tidied the folder up by putting the new outputs in a single folder, Github Desktop could 'find' the repo again.

**Comment by afdhalrashid** [comment]
> I also had this issue, for me it was due to changes in the repo folder contents. For instance when my code saved outputs to the repo folder, it resulted in Github Desktop being unable to access the repo due to there being changed contents in the folder. When I tidied the folder up by putting the new outputs in a single folder, Github Desktop could 'find' the repo again.

Kindly share your steps solving this issue as I am also experiencing it now

**Comment by Glasgray** [comment]
I removed anything like folders or files that were extra i.e. not R code and R project file from the folder where the GitHub repository was located. So all that remained was the R code files and R project file, after this I restarted GitHub and located the repository and it worked again.

**Comment by yskooo** [comment]
> > I also had this issue, for me it was due to changes in the repo folder contents. For instance when my code saved outputs to the repo folder, it resulted in Github Desktop being unable to access the repo due to there being changed contents in the folder. When I tidied the folder up by putting the new outputs in a single folder, Github Desktop could 'find' the repo again.
> 
> Kindly share your steps solving this issue as I am also experiencing it now

 Hey, have you already fixed it? I am also experiencing it lol

**Comment by taugspurgermakino** [comment]
same problem here

**Comment by Pumpsekkar** [comment]
this just happened to me after i end tasked some background app with a red little box icon and then shut off my computer woke up and now its stuck on  this please help!

**Comment by petermalmquistcmb** [comment]
I got the same issue, when I ran git status I got: **fatal: unterminated line in .git/packed-refs:**.
I removed the file, then it worked after GitHub desktop refreshed the repo.

**Comment by daahl** [comment]
I am also experiencing this issue now. After generating C files from simulink, Github Desktop can no longer find the local repo.

**Comment by steveward** [comment]
@daahl can you share the log file from GitHub Desktop? You may be hitting an issue where the status output is too large (https://github.com/desktop/desktop/issues/15586).

**Comment by daahl** [comment]
> @daahl can you share the log file from GitHub Desktop? You may be hitting an issue where the status output is too large (#15586).

@steveward I'm not sure which parts could be sensitive or not, so I've been liberal with the masking. Let me know if I removed anything important needed to find the issue.

"2023-03-30T13:49:21.082Z - info: [main] Using toast activator CLSID {XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}
2023-03-30T13:49:21.636Z - info: [ui] [AppStore] loading 8 repositories from store
2023-03-30T13:49:21.637Z - info: [ui] [AppStore] found account: daahl (daahl)
2023-03-30T13:49:21.951Z - info: [ui] launching: 3.2.0 (Windows 10.0.22621)
2023-03-30T13:49:21.967Z - info: [ui] execPath: 'C:\Users\XXXXXX\AppData\Local\GitHubDesktop\app-3.2.0\GitHubDesktop.exe'
2023-03-30T13:49:22.459Z - info: [ui] Subscribed 'daahl' to Alive channel
2023-03-30T13:49:22.900Z - info: [ui] Stats reported.
2023-03-30T13:49:28.785Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 1.427s)
2023-03-30T13:49:54.812Z - info: [ui] [AppStore] adding repository at C:\Users\XXXXXX\OneDrive - XXXXXXXX\XXXXXX_XXXXXXXXXXXXX\BitcrazeSharedFolder\project2023-group-01 to store
2023-03-30T13:49:57.263Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 8 repositories took 6.4s of which 1.6s paused, total 8.0s"

**Comment by steveward** [comment]
I'm not seeing the specific error there. Is that log portion from a day where you experienced the issue?

**Comment by anatolii-kotov** [comment]
Have this error on macOS, pressing **locate** button and select the same path helps

**Comment by bobwolff-cpi** [comment]
I also encountered this on MacOS M2 processor. The log complaint is:

```
2023-05-21T21:34:52.991Z - info: [ui] [AppStore] adding repository at /Users/XXXX/dev/YYYY to store
2023-05-21T21:34:54.303Z - info: [ui] Executing isUsingLFS: git lfs track (took 1.301s)
2023-05-21T21:34:54.330Z - info: [ui] [BranchPruner] Last prune took place 5 hours ago - skipping
2023-05-21T21:34:55.677Z - error: [ui] 'git status' emitted 32079959 bytes, which is beyond the supported threshold of 20000000 bytes
2023-05-21T21:34:56.930Z - error: [ui] 'git status' emitted 32079959 bytes, which is beyond the supported threshold of 20000000 bytes
```

I will note that this morning I did do a 'doxygen' run for the first time and so it created a ton of files down in the tree. I'm betting this is the "culprit" but certainly not intuitive at least.

By adding to `.gitignore` my `doxygen-docs/`, the issue goes away and GH Desktop recognizes the repo again.

**Comment by darndtjrbcs** [comment]
I'm experiencing the same problem. My repo is stored on OneDrive. I've seen others have similar issues. What's going on?

**Comment by virtuabart** [comment]
I'm also experiencing the same issue. Even though I have told it where the repository was. Github Desktop cannot find it.

I just backed up my Windows folder repository.

I removed the repository from Github Desktop.

Then I cloned it again. Make sure the target destination is empty. Let it recreate the vault or repository folder.

Then it worked again.

**Comment by K2-Projekte** [comment]
i ran into this problem also, then i cloned 140GB again and it worked for a day, but after a windows update 
"Windows 11, version 22H2" i ran into this again...
due to githubs new  lfs price policy i am not willing to do clones every three days!
OS:Win11 
Git Desktop Version 3.3.1 (x64) 
Log File excerpt:
2023-09-21T06:18:27.205Z - info: [main] Using toast activator CLSID {XXXXXXXXXXX}
2023-09-21T06:17:53.233Z - info: [ui] Subscribed 'XXXXXXXX' to Alive channel
2023-09-21T06:18:16.659Z - info: [ui] [BranchPruner] Last prune took place 23 hours ago - skipping
2023-09-21T06:18:16.723Z - error: [ui] `git config -z --local user.name` exited with an unexpected code: 128.
stderr:
fatal: --local can only be used inside a git repository
I assume, it's a problem with the .git directory handling or an auth problem in the codebase of this current GitDesktop V 3.3.1 (x64)... See here an old post from 2018: https://github.com/desktop/desktop/issues/5291

**Comment by dobsonddev** [comment]
> I removed anything like folders or files that were extra i.e. not R code and R project file from the folder where the GitHub repository was located. So all that remained was the R code files and R project file, after this I restarted GitHub and located the repository and it worked again.

THANK YOU SO MUCH. This has been so insanely annoying for me as ALL of my repositories i was managing through github desktop would randomly be lost or corrupted. I have a few extra files in my /github/ directory, like branchcleanup.sh for example. After deleting them, github desktop is now recognizing my repos again.

What was weird was that it would only "forget" repos after a bit of time, which really obfuscated the troubleshooting for me. 

Appreciate you, thank you for the fix, cheers!

**Comment by LowLevelLemmy** [comment]
i still dont understand the fix can someone explain in dumbass terms?

**Comment by vandor5676** [comment]
I had this problem too after a windows update

It seems like my config file in .git/config was corrupt (the file is called config and has no extension)
after deleting it I was able to add my repository again

You may need to add some info into your config file to get everything working again
Here's mine 
```
[core]
    repositoryformatversion = 0
    filemode = false
    bare = false
    logallrefupdates = true
    symlinks = false
    ignorecase = true
[submodule]
    active = .
[remote "origin"]
    url = <Your repo url here 👈>
    fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
    remote = origin
    merge = refs/heads/main
```

Hope that helps someone 🙂

**Comment by DonSylver** [comment]
I have had this same issue. I didn't have any extra files to delete in the missing repo folder. 
The problem happened after I had been using git commands in the terminal (Mac OS). 

I got the GitHub Desktop to locate the repo again by:
- going to my command terminal and locating my GitHub folder using the bash `cd `command, 
- then into the missing repo folder which I can still see in the file directory, 
-removing the instance of ".git" from the repo folder using `rm -fr .git`, 
- confirming that ".git" is gone using`ls -a` command
- then adding it back in using `git init` to build the ".git" file again so GitHub Desktop can now read the folder.

So it is something like below:
```
username@DonSylver-MacBook-Pro % cd GitHub
username@DonSylver-MacBook-Pro GitHub % cd Missing_Repo_Folder_Name
username@DonSylver-MacBook-Pro Missing_Repo_Folder_Name % git init
Initialized empty Git repository in /Users/username/GitHub/Missing_Repo_Folder_Name/.git/
username@DonSylver-MacBook-Pro Missing_Repo_Folder_Name % rm -fr .git
username@DonSylver-MacBook-Pro Missing_Repo_Folder_Name % ls -a
.		.DS_Store	.gitignore	.settings	src
..		.classpath	.project	pom.xml		target
username@DonSylver-MacBook-Pro Missing_Repo_Folder_Name % git init
Initialized empty Git repository in /Users/username/GitHub/Missing_Repo_Folder_Name/.git/
username@DonSylver-MacBook-Pro Missing_Repo_Folder_Name % ls -a
.		.classpath	.project	src
..		.git		.settings	target
.DS_Store	.gitignore	pom.xml
username@DonSylver-MacBook-Pro Missing_Repo_Folder_Name %
```
Now go to GitHub Desktop and Add the repo. It should find it now.

**Comment by VicVector** [comment]
same 'can't find' problem, but different route to the problem. I have github desktop open, I've cloned a fresh repository into a new  folder. I can put files into the folder and they appear in the changes column, can be committed and pushed... EXCEPT if I put TOO many files (too large) in there, at which point it can't find the folder anymore. directing it to the folder doesn't help. The only way I can have it 'refind' is to remove some of the files until it automatically relocates itself. So I commit those files, push, and then add more, bit by bit. I don't know what the size threshhold is so it's trial and error. Considering the project is 380GB, this is a time consuming process. Ideas?

**Comment by steveward** [comment]
@VicVector if your project is 380GB then that is going to cause a number of issues. You're likely hitting https://github.com/desktop/desktop/issues/15586. You'll need to look into using [Git LFS](https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage) to manage this repository and likely commit you initial commit using the command line. You should then be able to work with the repository in GitHub Desktop.

**Comment by SSCalifornia** [comment]
@VicVector your issue pointed me in the right direction for my issue. I hadn't added a gitignore for node_modules, plugins and the like. Adding that fixed my issue.

**Comment by JuniorDjjr** [comment]
> I also had this issue, for me it was due to changes in the repo folder contents. For instance when my code saved outputs to the repo folder, it resulted in Github Desktop being unable to access the repo due to there being changed contents in the folder. When I tidied the folder up by putting the new outputs in a single folder, Github Desktop could 'find' the repo again.

**Fixed for me too.** I had created a backup of a big folder adding a "." in the start of the folder name, moving this folder outside the root project folder (that is, removing this folder) fixed the issue.

**Comment by ArialBlack** [comment]
In my case, its happened once I installed node modules with 'npm i'.
After adding node_modules/ folder into .gitignore, the problem was fixed.

**Comment by pratheekrajan** [comment]
In my case, a program was accessing files in the repo. Closing the program fixed it immediately.

**Comment by meenbeese** [comment]
I had the same issue and the reason was because I had set an invalid value in my Git config while debugging another issue.

**Comment by QuintenVedder** [comment]
i had this issue too, the fix for me was:
check all corrupted files ( git fsck --full )
remove corrupted file(s) ( rm .git/objects/../...... )
and then ( git fetch --all )

**Comment by justingolden21** [comment]
If you rename the folder of the git repo then github desktop cannot find it. I spent a long time on this but resolved by deleting the repo from github desktop then file > add local repo and adding it.

**Comment by jmorgadosoares** [comment]
I had this issue after running
```
git rm -rf --cached .
git add .
```
I suspect the number of changes exceeded what Github Desktop could handle. Committing the changes via command line `git commit` fixed it

**Comment by Stardidi** [comment]
In my case it was adding vcpkg. 

Adding this to my .gitignore fixed it:

```
# vcpkg
vcpkg_installed/
```

**Comment by MattBruce-IHC** [comment]
I had similar issue where some of my repos suddenly stopped being able to be located. 

Git Desktop didn't give any helpful information but running "git branch" in the cli showed an error in .git/config. Looking at the file showed that the file was missing a closing quote mark after the branch names in the merge lines. 

I'm unsure what caused this and why it was only on certain repos but re-adding the closing quote mark on the merge lines meant I was able to re-add the repos to git desktop

**Comment by cesarlugojr** [comment]
My issue was that my folder was in my desktop on mac and my desktop was in my iCloud. Changed it to be directly under my user folder

**Comment by AliSMAmin** [comment]
Git status revealed git index corruption in the CLI
