### ISSUE TITLE
GitHub Desktop - trouble connecting to existing local repository

### ISSUE THREAD

**Issue by LeighWardle2** [desktop/desktop#15419]
Hi everyone,

I've using GitHub Desktop (Windows).

I have just switched to a new PC.

I have copied all my files to the new PC.

I've made a few changes to the local repository.

Now I've struck a problem.

My local file setup uses this folder:

D:\Development\git-repos\APSDS-5.0-vb6 (so the GitHub repo is APSDS-5.0-vb6).

I can't remember what command I used, but it pulled all my GitHub code into this folder:

D:\Development\git-repos\APSDS-5.0-vb6\APSDS-5.0-vb6

My 2 questions are:

Is it safe to delete D:\Development\git-repos\APSDS-5.0-vb6\APSDS-5.0-vb6?

What would have been the right way to link to my existing files in D:\Development\git-repos\APSDS-5.0-vb6 ?

Hopefully, it can all be done in GitHub Desktop.

Regards,

Leigh

**Comment by steveward** [comment]
@LeighWardle2 thanks for the issue. It sounds like you created a new repository inside directory. Was there an existing `.git` directory in your original `APSDS-5.0-vb6`? You can drag-and-drop the existing repository into GitHub Desktop to add it. If it is not an existing repository it will prompt you to initialize a new repository inside the directory.

It should be safe to delete the duplicate `APSDS-5.0-vb6` directory if nothing is in there that you don't need.

**Comment by LeighWardle2** [comment]
Thanks, [steveward](https://github.com/steveward), for your suggestions.

Yes, there an existing .git directory in my original APSDS-5.0-vb6.

Doing a drag-and-drop of the existing repository into GitHub Desktop to add it worked its magic!

**Comment by steveward** [comment]
Glad to hear that got things working! I'll close this issue out, but let me know if you have any further questions.
