### ISSUE TITLE
EMFILE: too many open files

### ISSUE THREAD

**Issue by fp-nschneegas** [desktop/desktop#15411]
### The problem

Error: EMFILE: too many open files, open 'C:\Users\NICOLE~1\AppData\Local\Temp\GitHubDesktop-lfs-progress-g11c6S\GitHubDesktop-lfs-progress'

Version: 3.0.8
OS: Windows 10.0.19044

![image](https://user-images.githubusercontent.com/84933269/193948846-8283447b-730d-4d2a-b1f5-b6172f72c179.png)

### Release version

3.0.8

### Operating system

Windows 10.0.19044

### Steps to reproduce the behavior

Happens while cloning a repository 

### Screenshots

![image](https://user-images.githubusercontent.com/84933269/193948846-8283447b-730d-4d2a-b1f5-b6172f72c179.png)

**Comment by steveward** [comment]
Thanks for the issue @fp-nschneegas. There is a previous issue tracking this in https://github.com/desktop/desktop/issues/5268. Are you only experiencing this issue with one specific repository?

**Comment by fp-nschneegas** [comment]
@steveward No, just this repository so far

**Comment by steveward** [comment]
@fp-nschneegas thanks, is this a public repository that I could try cloning to see if I can reproduce the issue?
