### ISSUE TITLE
Explicitly set $GIT_SEQUENCE_EDITOR when launching from cli `github .`

### ISSUE THREAD

**Issue by devinrhode2** [desktop/desktop#15413]
### The problem

rebase stuff pops open my `$GIT_SEQUENCE_EDITOR` (vscode)

### Release version

Version 3.1.1 (arm64)

### Operating system

macOS 12.6

### Additional context

`github .` should override `$GIT_SEQUENCE_EDITOR` to point to itself.

**Comment by steveward** [comment]
Thanks for the issue @devinrhode2. Just to make sure I understand correctly -- when you're in the middle of a rebase and run `github .` to open GitHub Desktop VSCode is being launched? If you can share specific steps to reproduce this that would be great, thanks!

**Comment by devinrhode2** [comment]
Doesn't matter what the rebase state is. The state that matters is the value of `$GIT_SEQUENCE_EDITOR` when `github .` is run.

**Comment by devinrhode2** [comment]
When the github app runs rebase commands, it should probably set `sequence.editor` and/or `GIT_SEQUENCE_EDITOR` to point to itself. https://stackoverflow.com/questions/29094595/git-interactive-rebase-without-opening-the-editor

**Comment by devinrhode2** [comment]
I believe this would repro:
Precondition:
1. When you run `git commit --allow-empty` it opens vscode. When you run `git rebase -i master` it opens vscode. (Set `EDITOR` and/or `GIT_EDITOR` in shell profile, and/or set `core.editor` in `~/.gitconfig`.

Repro:
1. Set `GIT_SEQUENCE_EDITOR` in your shell profile and/or set `sequence.editor` in your `~/.gitconfig` to vscode.
2. Run a rebase thing in the github app: shuffle order or two commits, for example.
3. Notice that vscode opens with the `git-rebase-todo` file for the rebase.
4. The commits inside of vscode are not shuffled already. Close file. Rebase completes, but commits have not been shuffled.

**Comment by devinrhode2** [comment]
So, here: 
https://github.com/desktop/desktop/blob/b3732f6639d417f3d602fd7283508b8382930a6b/app/src/lib/git/rebase.ts#L577
we can see `-c sequence.editor=cat` being used

Just above this, `gitEditor` is set to `:`, which is set to `GIT_EDITOR`.
- Maybe set `GIT_SEQUENCE_EDITOR` in addition to `GIT_EDITOR`?

Maybe on this line:
https://github.com/desktop/desktop/blob/b3732f6639d417f3d602fd7283508b8382930a6b/app/src/lib/git/rebase.ts#L389
you want to add some sort of `-c sequence.editor=:` or `-c sequence.editor=cat`

**Comment by devinrhode2** [comment]
The TLDR is:
If a user has GIT_SEQUENCE_EDITOR and sequence.editor set to vscode, it should not interfere with any rebase operations done with github desktop.

**Comment by devinrhode2** [comment]
I am working on a bugfix now :)

I did find that the `sequence.editor` gitconfig setting has no bearing on the issue.

Repro:
1. Simply set `GIT_SEQUENCE_EDITOR` to something like `code --wait`
2. Try shuffling commits in github desktop app
3. Notice that vscode opens, commits are not shuffled, if you close git-rebase-todo file without making any changes, commits do not get shuffled.

**Comment by steveward** [comment]
Thanks for all the details @devinrhode2, that's helpful!

**Comment by devinrhode2** [comment]
Hey @steveward, I actually stopped working on this. I thought it'd be easy to jump in and fix quickly, but then I thought about how to update the tests, and didn't want to consider all the possible edge cases that would need to be addressed.
