### ISSUE TITLE
Ability to expand Current branch tab

### ISSUE THREAD

**Issue by boorac** [desktop/desktop#15417]
### The feature request

To the best of my knowledge, the `Current branch` tab is always fixed in size. As a consequence, long branch names get truncated. If branches share a common prefix, the name of the branch can not be easily understood, until the mouse is hovered over and the tooltip appears.

Example branches: 
1. `feature/this-is-a-very-long-prefix-for-all-branches-issue-1` -> `feature/this-is-a-very-long...``
2. `feature/this-is-a-very-long-prefix-for-all-branches-issue-2` -> `feature/this-is-a-very-long...``

### Proposed solution

The ability to expand the `Current branch` tab, similarly to the way `Current repository` can be expanded.

**Comment by steveward** [comment]
Thanks for the issue @boorac! We are tracking this in https://github.com/desktop/desktop/issues/4569 so I'm going to close this issue out.
