### ISSUE TITLE
please update on the ubantu desktop of linux also please 

### ISSUE THREAD

**Issue by kasinadhsarma** [desktop/desktop#15412]
### The feature request

the third parties are giving us the wrong desktop to us so please do the official desktop of GitHub 
![image](https://user-images.githubusercontent.com/81065703/193964773-72b28c3f-bdb0-4aa5-8477-ef99f700aaa9.png)
us 

### Proposed solution

please update the official update as soon as possible on Linux also please

**Comment by sergiou87** [comment]
Thanks for the issue @kasinadhsarma . At this time there are no official builds of GitHub Desktop available for Linux, but a former developer of GitHub Desktop maintains a fork with Linux builds available for download:

https://github.com/shiftkey/desktop/releases

You can also follow along with https://github.com/desktop/desktop/issues/1525 for updates about an official Linux release.
