### ISSUE TITLE
Notifications occur for every check if any fail

### ISSUE THREAD

**Issue by ofek** [desktop/desktop#15422]
### The problem

Notifications occur for every PR check if any fail, see https://github.com/DataDog/integrations-core/pull/13053

I think Codecov temporarily failed while results were being uploaded for every job then went green. Maybe that's happening multiple times, rapidly? I'm getting dozens of failed message pop-ups but not hundreds

### Release version

Version 3.1.1 (x64)

### Operating system

Windows 10

**Comment by ofek** [comment]
> but not hundreds

Actually it is...

**Comment by sergiou87** [comment]
😱😱😱

In theory that should only happen for every PR where you're the author, and only when the CI jobs run and fail. I wouldn't expect anything like what you describe unless you have hundreds of PRs and they all initiate CI jobs simultaneously (or rapidly) and all fail.

Do you think that's what happened to you?

**Comment by ofek** [comment]
Nope just 1 PR w/ hundreds of checks for AZP

**Comment by sergiou87** [comment]
It should only send 1 notification per check suite 😱 And from what I see, your PR should only have 1 check suite with many many check runs. Is it possible that check suite affects multiple different PRs?

**Comment by ofek** [comment]
No

**Comment by ofek** [comment]
Please feel free to modify https://github.com/DataDog/integrations-core/blob/master/datadog_checks_base/datadog_checks/base/__about__.py in a PR to test

**Comment by ofek** [comment]
btw this is new behavior, like within the last month or 2

**Comment by sergiou87** [comment]
Thanks for the info! If you've seen this recently (we haven made changes in notifications on the GitHub Desktop side for a long time), maybe the behavior changed on the backend side. I will investigate and, if I can't find the reason, I will create a test PR in that repo as you suggest. Thank you again!!

**Comment by ofek** [comment]
Did that reproduce?

**Comment by sergiou87** [comment]
Nope, I didn't get a notification at all 😞 Which might be a different bug/issue.

However I tried with this other one #15451 and managed to get multiple notifications for it. More specifically I got 1 notification per check suite (group of checks), per individual commit that got their checks running. In this case, there were two check suites, one with only 1 check and the other one with 4 checks:

![image](https://user-images.githubusercontent.com/1083228/195356116-589e70fd-024f-4d06-b963-a7fc667d2296.png)

I pushed 10 commits **individually** that made both of them fail, so I got 10 * 2 = 20 notifications:
![2022-10-12 at 15 32](https://user-images.githubusercontent.com/1083228/195356403-d11ddee9-53d5-4eab-82d2-498039f30823.png)


Looking at the `Checks` of the PR you linked, it has 10 check suites:
![2022-10-12 at 15 33](https://user-images.githubusercontent.com/1083228/195356611-e4116b0a-1259-4971-8955-6f0e3ba47940.png)

It also has 5 commits, 4 of which failed, so you should have received up to 40 notifications while working on it:
![2022-10-12 at 15 34](https://user-images.githubusercontent.com/1083228/195356849-1679a902-9669-4365-80e0-1462660e98cd.png)

This is just the reasoning, not sure if it matches what you have experienced. You mention hundred of notifications, but I really hope that's not literal 😂  Although 40 is not a low number either.

One thing GitHub Desktop could do is showing notifications only for check suites affecting the very last commit of a PR, so at least we avoid nagging the user too much if they push commits many times in a short period of time. If you still think you got notifications for every single failed check within those check suites, I'll have to investigate further when I'm able to repro it.

**Comment by sergiou87** [comment]
I made a few changes (and fixes) on the backend side and at least I didn't get many notifications. @ofek could you give it a try and let me know?

I still have more fixes to do on the app side, but I'd love to know if the changes I've made already on the backend have any impact on the behavior you saw 🤞

**Comment by ofek** [comment]
missed this, thanks!!!
