### ISSUE TITLE
No se interpretan los acentos, muestra este carácter �

### ISSUE THREAD

**Issue by MiguelLopezAnpworks** [desktop/desktop#15428]
### The problem

Estoy tratando de subir un código, donde existe un mensaje con acento, pero GitHub Desktop me muestra: comun�quese  cuando debería mostrar comuníquese, antes no sucedía me pasa con la versión reléase y con la beta.

### Release version

Version 3.1.1 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1.- Solo hago el commit y se ve.

### Screenshots

<img width="1280" alt="error_github_desktop" src="https://user-images.githubusercontent.com/82952995/194666759-43cee09a-ed38-48ae-8a2d-5ddad66bf92d.png">

**Comment by sergiou87** [comment]
Hola!

Qué editor utilizas para escribir el código? Es posible que haya cambiado la codificación en la que guarda los ficheros? Se puede ver en la captura que muestras que el "antes" (la parte en rojo) muestra bien la vocal con la tilde `í`, pero no en el "después" (parte en verde), lo que me hace sospechar que no es un problema de GitHub Desktop sino del editor de código que utilices. Comprueba a ver si se están guardando en UTF-8.

PD: te aconsejo que escribas los bug reports en inglés, así mis compañeros podrán ayudarte también si yo no estoy disponible 😄

**Comment by MiguelLopezAnpworks** [comment]
Hola @sergiou87, muy amable por responder.

Lo primero es confirmar que me quedo claro a futuro levantar el post en inglés, gracias.

Mi editor es Microsoft Visual Basic 6.0, que por lo visto deja el formato en ANSI, con esto entiendo que no puedo configurar GitHub Desktop para que me interprete los caracteres especiales :(  

Lo que me mueve el piso es que, según yo antes no me sucedía esto, y no he actualizado mi versión (Versión 3.1.1 (x64)) 

Muy amable por tu pronta respuesta 👍

**Comment by sergiou87** [comment]
Wow! Con Visual Basic 6.0 aprendí yo a programar hace 23 años 😂 Qué buenos recuerdos 🥲 

Si tienes posibilidad, una cosa que puedes hacer es ejecutar `git diff` desde la terminal y mirar si ahí aparece bien la tilde, o directamente probar algún otro cliente de git de GUI como SourceTree. Si en ellos también se muestra mal la tilde, me temo que el problema está en otro lado y no en GitHub Desktop.

Ya me dirás qué resulta de esas pruebas 🤞
