### ISSUE TITLE
Commit author tooltips may have scroll bars

### ISSUE THREAD

**Issue by haykam821** [desktop/desktop#15424]
### The problem

In some cases, such as a very long email address, the tooltip for a commit author's avatar may overflow the container. The tooltip handles overflow by scrolling, but since this tooltip isn't meant to be interactive, the tooltip will just disappear if the user tries to focus or mouse into the tooltip to scroll it.

This issue could be fixed by improving text wrapping within the tooltip. Simply making the tooltip interactive would also solve this issue but provide the poor user experience of including an unnecessary toolbar. While out of scope for this issue, both fixes combined would have the additional benefit of allowing users to copy an author's email address.

### Release version

GitHub Desktop 3.1.1

### Operating system

macOS 12.5.1

### Steps to reproduce the behavior

1. Open the commit history tab in the desktop/desktop repo
2. Find a commit with an author that has a long email address, such as f2aafb0ee561b30fcc46b1520e8348d207149048
3. Hover over the author's avatar

### Screenshots

<img width="301" alt="Commit author tooltip with scroll bar" src="https://user-images.githubusercontent.com/24855774/194422698-89886ebb-de9e-40f5-a8ee-573c9d1ff7f4.png">

**Comment by salkasov1999** [comment]
Приоритет убери пожалуйста

**Comment by Menono87** [comment]
> Приоритет убери пожалуйста
