### ISSUE TITLE
Could not open editor(e.g. Xcode) when double click filename table row in "Changes" pane.

### ISSUE THREAD

**Issue by r-plus** [desktop/desktop#1542]
### Description

Could not open editor(e.g. Xcode) when double click filename table row in "Changes" pane.

### Version

**GitHub Desktop version:** [version 0.5.3]
**OS version:** [version 10.12.4]

### Steps to Reproduce

1. Double click filename in "Changes" pane.

**Expected behaviour:**

Open double clicked file in editor that feature is implemented in GitHub Desktop ver.222.

**Actual behaviour:**

No effect.

**Reproduces how often:**

Always.

**Comment by stevemoser** [comment]
I would add to this right click to open the file in an external editor or reveal in Finder, etc.

**Comment by joshaber** [comment]
We made the conscious decision not to implement this, but we'd welcome an issue around @stevemoser's suggestion of right-clicking.

**Comment by stevemoser** [comment]
I created #1566 for the right click functionality.

**Comment by r-plus** [comment]
Okey, thanks all guys.

**Comment by koenpunt** [comment]
> We made the conscious decision not to implement this

@joshaber where was that decision based on? And what about a keyboard shortcut then?

**Comment by joshaber** [comment]
@koenpunt Unfortunately that decision was made in our closed team chat 😞 I think a keyboard shortcut would be reasonable.

**Comment by koenpunt** [comment]
@joshaber I see, but that doesn't give much clarity. Just trying to understand why this feature, that was present in the previous version, has no change of getting in the new version

**Comment by joshaber** [comment]
Yeah, sorry @koenpunt, I should have provided some more context there 😅 

If I recall, and it's been a while, our thinking was mainly that it was a difference in behavior between Mac and Windows which wasn't a high enough priority to special case for just Mac.

That said, if we get a lot of feedback around this we can always revisit it.
