### ISSUE TITLE
Feature Request: Search in history

### ISSUE THREAD

**Issue by fluffynuts** [desktop/desktop#1543]
### Description

A really useful feature would be to be able to search (free-form text) for commits containing that text as well as files containing that text which were touched in a commit. This would make it easy to track history of files.

### Version

**GitHub Desktop version:** 0.5.3

**OS version:** Microsoft Windows [Version 10.0.15042]

### Steps to Reproduce

This isn't an issue, per se, and there are no real "steps to reproduce". I'd imagine a quick search textbox on the history view where I could type in some text and get matching relevant commits.

**Comment by alrz** [comment]
The search box should also look up author, commit hash and changed file names in the commit.

**Comment by rlabrecque** [comment]
Recommendation: This should display with ctrl+f and pop up in the history pane. First implementation should probably just be the commit message. Everything else should probably be under some kind of prefix like @username is here?

**Comment by alrz** [comment]
> Everything else should probably be under some kind of prefix like @username

That's a good idea. We could use some other prefix for files (to find commits that modify those files)

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by suntsu42** [comment]
Does that really not work?
This seems like a core feature to me.

**Comment by zuigz** [comment]
Hi,
  I'm also expecting this feature. I want to search a change in history and show the files and modification. 

   I'm concerning this because I’m checking the change log at this page: https://www.opendataplane.org/developers/changelog/index.html#opendataplane-1-17-0-0 , and for example I need to know what following description actually does. Normally I will try to search “streamlined queue”in history. 

  _

_Streamlined Queue Implementation
The ODP Reference Implementation now uses a ring model for implementing ODP queues. This results in greatly improved efficiency for queue operations. The default maximum queue depth used is 4096 elements, and this information is returned via the odp_queue_capability() API._

_

**Comment by billygriffin** [comment]
I'm going to remove `future proposal` here in favor of #7022 as that nicely lays out what pain this inflicts today and how someone works around it. I'd love to hear others weigh in on that issue if you're interested in it, specifically in terms of how the problem surfaces and what you do instead today.

**Comment by JosephTLyons** [comment]
Check into Sublime Merge's commit search for inspiration.  It is absolutely amazing what all can be included in a search in their Git client.  Now, I don't entirely think that it needs to be that extensive, but it would be great to have at least some ability to search through commits.

**Comment by erlandl4g** [comment]
Why Github Desktop cannot have at least half the search possibilities Sublime Merge has after 3 years since this request has been made? It is also crazy not to have ability to compare two different commits or to see a change log on a specific file..

**Comment by igroglaz** [comment]
Folks, this is highly needed function.. Without it I had to switch to other Git GUI.

**Comment by mesqueeb** [comment]
@billygriffin that sadly doesn't cover being able to search for a commit by name, while this issue does. Can you please add back the label?

**Comment by igroglaz** [comment]
I myself switched to Git Extensions client (https://github.com/gitextensions/gitextensions) cause of this feature. It works there like charm.

**Comment by bigahuna** [comment]
Sourcetree also has a good search inside the commit history...

**Comment by vdheuvel** [comment]
@billygriffin that sadly doesn't cover being able to search for a commit by name, while this issue does. Can you please add back the label? [2]

Tbh this is really basic, necessary functionality for users who have more than 30 commits in their branch...

**Comment by fs185109** [comment]
installed it yesterday but should uninstall it today in reason it is useless without history search....

**Comment by smalos** [comment]
Search in history together with a shortcut ctrl+f would be more than favourable.

**Comment by mesqueeb** [comment]
@joshaber can you add back the future-proposal label?

It got unrightfully removed. Based on claims that another thread covers it while it does not at all.

**Comment by subspacefield** [comment]
I had to load Sourcetree so I could search commit history. My use case was I needed to find commits on a development branch to cherry pick to another branch.

**Comment by titusdecali** [comment]
Jesus, this was opened 5. YEARS. AGO. Can we just get a simple commit search already?!?

**Comment by JosephTLyons** [comment]
The ways in which GitHub Desktop is developed are so entirely strange.  It seems like so many things, requested by its users, are just entirely dismissed, with no explanation what-so-ever.  I really, really ... don't get it.

**Comment by fluffynuts** [comment]
the fact that it's 5 years old should give you the answer

move along - this is not the git ui you're looking for

if I could close my own issues on this repo, I would - holding on to this is pointless: it's quite plain that the people invested in this project don't care about this (rather trivial) feature

fwiw, check out lazygit and learn more of the CLI to get what you want

**Comment by rlabrecque** [comment]
Hah, same with my issues that I opened 5 years ago. I was so excited for this project given SourceTree's state at the time. But we've gained so many more options in the last 5 years, it's fine that this one doesn't cater to us, just use something else (Fork in my case) as soon as you 'graduate' beyond the what this tool can provide you.

**Comment by sfeinstein-goodrx** [comment]
just installed and was shocked that search wasn't a feature and saddened when I found this issue.  A response would be nice, GH team!

**Comment by ignacio-rh** [comment]
Lol this is crazy! No way to search????

**Comment by mesqueeb** [comment]
@joshaber can you please reopen the issue

**Comment by leo9py** [comment]
This **_is_** a core feature and not having a search feature within the history makes navigating my monolithic repositories extremely difficult with hundreds of commits per hour.

**Comment by Shinyshark1** [comment]
Can this feature please be implemented? I am trying to search for a commit to revert, but I am now forced to scroll through a long list of commits to achieve this.

**Comment by fluffynuts** [comment]
@MaximvanMaanen I really, really doubt this will ever be implemented, so, not knowing enough about what you're trying to achieve, one of these may help:

1. if you're looking for commit comment text, `git log --oneline | grep <whatever you're looking for>`
2. if you're looking for the commit in which a certain code line was last modified, I'd suggest `git blame <path to file>`

hope this helps.

**Comment by suntsu42** [comment]
I've solved this problem by using smartgit instead...

**Comment by Shinyshark1** [comment]
> 

Thanks Fluffynuts, I appreciate your help. My issue is not a big one, so I did not need to do these things. After a few minutes of scrolling I found it. I just find it odd that a tool used to support Version Control does not have such a basic feature such as searching for different versions.

**Comment by JacquesDoubell** [comment]
Indeed a basic, but useful feature that's sorely missing.

Gittyup is worth a try :)

**Comment by fluffynuts** [comment]
also check out the (imo rather fantastic) lazygit: https://github.com/jesseduffield/lazygit - wherein you can focus the commits pane and type `/` to search, ala vim.

**Comment by fluffynuts** [comment]
@JacquesDoubell this is the first time I've seen GittyUp - giving it a shufty! As much as I like the console, it would be nice to have a gui to recommend to others who are more console-adverse :D

**Comment by collinph** [comment]
This issue is closed. So how do we search? It's certainly not obvious.

**Comment by fluffynuts** [comment]
> This issue is closed. So how do we search? It's certainly not obvious.

you don't - issue was abandoned

**Comment by rsodre** [comment]
please reopen!

history search field is: select brach to compare???
I never used that and EVERY DAY need to search for commits.
btw, both features can co-exist

**Comment by ghnp5** [comment]
It looks like this issue was closed in favor of #7022
