### ISSUE TITLE
Disable auto-update 

### ISSUE THREAD

**Issue by laps-tallinnas** [desktop/desktop#15438]
### The feature request

Hello, facing issues with fetching data, please make updates optional, not mandatory.  

### Proposed solution

Make a checkbox to allow updates or vice versa, disable updates.

**Comment by laps-tallinnas** [comment]
Linking issue  #15437

**Comment by sergiou87** [comment]
Hello! 👋  We're tracking this request in https://github.com/desktop/desktop/issues/3410, so I'm gonna close this issue in favor of that one. Please, subscribe to https://github.com/desktop/desktop/issues/3410 if you wanna get notified when we do any work on it.
