### ISSUE TITLE
Rollback Icon

### ISSUE THREAD

**Issue by cnnutaa** [desktop/desktop#15452]
### The feature request

I need a rollback icon.

### Proposed solution

Now, I can rollback with right click and discard changes.
But, it can be more easy. 
You can add a rollback icon left side or right side of any file row of changed files list for discard changes.

**Comment by steveward** [comment]
Thanks for the request @cnnutaa. At this time we don't have any plans of adding this type of option to the changes list, but thanks for letting us know you'd like to see this. I'm going to close this out.
