### ISSUE TITLE
It's must be official version for the Ubuntu operating system

### ISSUE THREAD

**Issue by delgec** [desktop/desktop#15456]
Why no development for linux operating systems?

**Comment by niik** [comment]
Please see https://github.com/desktop/desktop/issues/1525 and in particular the response at the top

> We have no immediate plans to support an official Linux version, but we continue to evaluate it alongside our other priorities and we know it's important to many people out there. I also know "maybe someday" is a disappointing response and I apologize for that. We're enormously grateful that @shiftkey has built a fork (https://github.com/shiftkey/desktop) and that many people are using that successfully, but @shiftkey is only one person and I hope people will understand that he's not always able to keep it entirely up to date with the official version.
> 
> I assure you that if/when we're able to commit to supporting a Linux version, we'll update this issue accordingly, and I appreciate your ask for a more "official" answer.
>
