### ISSUE TITLE
Add progress bar when pushing to origin

### ISSUE THREAD

**Issue by rickdonnelly** [desktop/desktop#15457]
### The feature request

The desktop app on macOS hangs a lot more often than in the past when pushing to origin from a local directory. The circular arrows spin, sometimes for hours on what should be a simple commit. Other times it takes a long time but at least something is going on. But the program gives absolutely no clue as to whether it is broken or just slow. A progress bar or count would seem simple to do and make the desktop app a lot more informative. 

### Proposed solution

A progress bar will immediately alert the user as to whether the app has stalled pushing to origin or is simply proceeding slowly. There is nothing the user can do about the latter, but knowing the former will save users an immense amount of time.

**Comment by steveward** [comment]
Thanks for the issue @rickdonnelly. There is a progress bar built into the `Push origin` button:

<img width="272" alt="Screen Shot 2022-10-14 at 4 41 39 PM" src="https://user-images.githubusercontent.com/721500/195940013-5d539db6-e65d-49d4-a2cd-a018157269ae.png">

If you're hitting long Git operation times, then I'd be happy to take a look at what might be causing this. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. 

I'm going to close this out, but feel free to reply with a log file so we can investigate the push issues further.

**Comment by Predulus** [comment]
Hi Steve.  If there is a progress bar built in, as you say, I'm certainly not seeing it.

![image](https://github.com/desktop/desktop/assets/39788392/fa1acd89-fa4c-4c17-94ab-455204eb0cfc)
