### ISSUE TITLE
Can't fetch due to fatal ssl/tls error

### ISSUE THREAD

**Issue by HaHongDo** [desktop/desktop#15450]
### The problem

I keep getting "fatal: unable to access '<repo link>': schannel: failed to receive handshake, SSL/TLS connection failed" every time i click fetch. This has never happened before and now suddenly I can't check for any updates on my repo. 
I have searched to see how others deal with this error and this is what i've tried:
1. restart Github Desktop
2. reinstall Git
3. reinstall Github Desktop
4. run git config --global http.sslBackend schannel in cmd
But none of it worked.

### Release version

Version 3.1.1 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Open Github Desktop
2. Click fetch

### Log files

[2022-10-12.desktop.production.log](https://github.com/desktop/desktop/files/9764121/2022-10-12.desktop.production.log)

### Screenshots

![Screenshot 2022-10-12 174132](https://user-images.githubusercontent.com/63568276/195322815-04b4f9b0-5730-4966-aa7c-779e221b6f5d.png)

**Comment by steveward** [comment]
@HaHongDo thanks for the issue. This can often occur on corporate networks, see [this note](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#certificate-revocation-check-fails). 

You can try setting the revocation check to false to see if that gets things working:

`git config --global http.schannelCheckRevoke false`

Let me know if that helps.

**Comment by HaHongDo** [comment]
Thanks, @steveward, this works for me.

**Comment by steveward** [comment]
Glad to hear that got things working!
