### ISSUE TITLE
Give an ability to use default shell on Windows

### ISSUE THREAD

**Issue by SaschaNaz** [desktop/desktop#1546]
### Description

GitHub Desktop on Windows always opens Command Prompt even when the Win+X is set to use PowerShell

### Version

**GitHub Desktop version:** 0.5.3

**OS version:** Windows 10.0.15063

### Steps to Reproduce

1. Repository->Open command prompt
2. It always opens Command Prompt

**Expected behaviour:** A shell opening button should be able to open PowerShell

**Actual behaviour:** No PowerShell option

**Reproduces how often:** 100%

#### Additional Information

It seems a previous issue discussed about this but without a solution implemented: https://github.com/desktop/desktop/issues/809#issuecomment-275713986

**Comment by UzEE** [comment]
Personally, I'd like to have the option of choosing between Cmd, PowerShell, or Bash/Zsh etc. (on Windows 10) or any custom terminal emulator like the previous desktop app did.

I really like the PoshGit environment from the previous desktop app and that's how I use git primarily on my system. I'd like to have the option to go back to that.

**Comment by joshaber** [comment]
We're already tracking this in https://github.com/desktop/desktop/issues/888. Feel free to follow along there!
