### ISSUE TITLE
git repo updates are fine on web page are not updated in the destop app.

### ISSUE THREAD

**Issue by ajmeerkhaja2001** [desktop/desktop#15461]
### The problem

every change and new Repo that I have uploded on git hub are not updated in the destop app but showing fine in browser

### Release version

3.1.1 

### Operating system

windows 11

**Comment by sergiou87** [comment]
Hello @ajmeerkhaja2001 !

Could you describe the steps to reproduce the behavior so we understand better what the problem is?

Thank you!
