### ISSUE TITLE
Support multiple GitHub Enterprise Accounts

### ISSUE THREAD

**Issue by trummerfeld** [desktop/desktop#15467]
### The feature request

I would like to be able to use more than one GitHub Enterprise within the GitHub Desktop Client.

### Proposed solution

This feature is especially useful for developers in the enterprise sector, where multiple GitHub Enterprise are used (e.g. for each client).

**Comment by steveward** [comment]
Thanks for the issue @trummerfeld. This is something that we're thinking through and are tracking feedback for in https://github.com/desktop/desktop/issues/3707 (even though that issue is closed). I'm going to close this issue out, but you can follow along in #3707 for updates.
