### ISSUE TITLE
Yarn precommit

### ISSUE THREAD

**Issue by dioannou30** [desktop/desktop#15476]
### The problem

A few versions before the current and latest written below, the yarn precommit hook triggered automatically on commit. 
That does not happen now.

### Release version

Version 3.1.1 (x64)

### Operating system

MacOs Monterey 12.6

### Steps to reproduce the behavior

1. Commit local changes to branch
2. Wait till commit ends
3. No build files found

**Comment by steveward** [comment]
Thanks for the issue @dioannou30. Have you tried committing via the command line to verify it isn't an issue with the pre-commit hook?

**Comment by ssara1549** [comment]
> ### The problem
> A few versions before the current and latest written below, the yarn precommit hook triggered automatically on commit. That does not happen now.
> 
> ### Release version
> Version 3.1.1 (x64)
> 
> ### Operating system
> MacOs Monterey 12.6
> 
> ### Steps to reproduce the behavior
> 1. Commit local changes to branch
> 2. Wait till commit ends
> 3. No build files found
> 
> ### Log files
> _No response_
> 
> ### Screenshots
> _No response_
> 
> ### Additional context
> _No response_
