### ISSUE TITLE
Font hinting behavior on Windows is inconsistent and causing visual pain

### ISSUE THREAD

**Issue by SaschaNaz** [desktop/desktop#1547]
### Description

Some UI components uses RGB-based subpixel font hinting when other components uses gray antialiasing, thus causes pain on eye.

1. Repository tab. The tab elements has proper subpixel hinting whereas the commit list just uses normal antialiasing.

   ![image](https://cloud.githubusercontent.com/assets/3396686/26152396/b8dceab0-3b41-11e7-9d48-10f50deb7590.png)

2. Code diff. No subpixel hinting at all. See 'DOMH' part which has worst hinting.

   ![image](https://cloud.githubusercontent.com/assets/3396686/26152413/c9ca8832-3b41-11e7-9c63-a6908fdfe719.png)

### Version

**GitHub Desktop version:** 0.5.3

**OS version:** 10.0.15063

**Expected behaviour:** Subpixel font hinting for all texts

**Actual behaviour:** Subpixel hinting for parts of texts

**Reproduces how often:** 100%

**Comment by niik** [comment]
Yeah, this is terrible but there's not a whole lot we can do about it. In some cases we're able to turn on subpixel antialiasing (see #1452 for example) but in most cases we can't. Chromium can't do subpixel antialiasing when it has to merge GPU layers.

For our lists we're able to enable it as long as they don't scroll. The moment they do chrome puts in a transparent scroll overlay that triggers layer merging and thus we loose subpixel antialiasing.

If anyone has any tricks up their sleeves I'm all ears, https://bugs.chromium.org/p/chromium/issues/detail?id=227101 does not look promising.

**Comment by SaschaNaz** [comment]
To workaround, can we use larger font size as the previous client did? The new client uses smaller font size and thus is affected harder.

**Comment by joshaber** [comment]
It doesn't sound like there's anything actionable for us here. Users can use Zoom to increase the font size, and we can hope Chromium has some tricks up their sleeves to improve text rendering on Windows.
