### ISSUE TITLE
I can't to connect to the repository with GitHub desktop

### ISSUE THREAD

**Issue by Baliarda** [desktop/desktop#15473]
### The problem

When I want to pull changes with GIT Desktop appear this message

![image](https://user-images.githubusercontent.com/34553148/196285471-b3d2c762-f711-4ebe-a8bb-4880a1ccea28.png)

We always use desktop to push or pull.

### Release version

3.1.1

### Operating system

Windows Server 2019

### Steps to reproduce the behavior

1. Go to the repository
2. Press Fetch to origin
3. Appear the message

### Log files

[2022-10-17.desktop.production.log](https://github.com/desktop/desktop/files/9804635/2022-10-17.desktop.production.log)

### Additional context

In other local server (to develop) we can use the GIT Desktop without problems

**Comment by steveward** [comment]
@Baliarda thanks for the issue. Have you tried logging out and then logging back in to your account?

**Comment by Baliarda** [comment]
Yes. Yesterday I tried to do that but didn´n start the login. Today I try again and I can. Thanks for your help

**Comment by steveward** [comment]
Glad to hear that got things working for you. I'm going to close this out.
