### ISSUE TITLE
GitHub desktop can still resize the window on the border when the window is maximized

### ISSUE THREAD

**Issue by lhyzf** [desktop/desktop#15483]
### The problem

GitHub desktop can still resize the window on the border when the window is maximized.
Can be observed under multiple monitors.

### Release version

Version 3.1.1 (x64)

### Operating system

Windows 10 21H2 (19044.2130)

### Steps to reproduce the behavior

1. PC with at least two screens.
2. Maximize GitHub desktop at any screen.
3. Put mouse in screen edge, you will see mouse change to resize icon.
4. Resize the GitHub desktop window.
5. You can see the resized window, and it does not have the boder shadow.

**Comment by steveward** [comment]
Thanks for the report @lhyzf. This was previously reported in https://github.com/desktop/desktop/issues/14017, so I'm going to close this out in favor of that existing issue. You can follow along there for updates.
