### ISSUE TITLE
Items in github desktop not showing up in Windows search

### ISSUE THREAD

**Issue by TaurVil** [desktop/desktop#15482]
Hello, I'm running Github Desktop with Windows 11 and I'm finding that the search function works fine for my non-Github files, but the Github directories are being ignored by the search. I can manually change the indexed locations to include the github files, but it then reverts back to hiding them after a few minutes. Any ideas about how to fix this?

**Comment by angusdev** [comment]
This is the problem of Windows. Refer to [Search index excludes any folder with a .git subfolder](https://www.reddit.com/r/Windows10/comments/mc1dra/search_index_excludes_any_folder_with_a_git/) for solution

> try to add c:\folder\.git to excluded and remove c:\folder\ from excluded

**Comment by steveward** [comment]
Thanks for the issue @TaurVil -- I'm going to close this out since @angusdev provided a helpful solution to this issue.
