### ISSUE TITLE
error: cannot spawn .git/hooks/pre-push: No such file or directory

### ISSUE THREAD

**Issue by Stilt1234** [desktop/desktop#15499]
### The problem

I cannot push the commit I made to my local repo to the remote repo

### Release version

Version 3.1.2 (x64)

### Operating system

Windows 10 Home Edition

### Steps to reproduce the behavior

1. Go to Github Desktop
2.  Do a commit to the local repo
3.  Push the origin
4. Wait for some time

### Log files

[2022-10-21.desktop.production.log](https://github.com/desktop/desktop/files/9837626/2022-10-21.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/97039901/197162511-44cc724d-5004-4347-880a-fce0649562e5.png)

**Comment by Stilt1234** [comment]
If anyone see's this pls help me.
This is a very important commit I need to push to my remote repo

**Comment by angusdev** [comment]
Did you try the suggestion in this link:

https://stackoverflow.com/questions/43754644/git-pre-push-issue-no-such-file-or-directory

**Comment by Stilt1234** [comment]
Thx @angusdev you helped a lot!
