### ISSUE TITLE
Add spyder IDE support to github desktop

### ISSUE THREAD

**Issue by lakshyaelite** [desktop/desktop#15492]
### The feature request

Add support to add spyder python IDE as GitHub desktop's default IDE

### Proposed solution

The benefit of it will be that users who program python using spyder IDE and github

**Comment by steveward** [comment]
Thanks for the issue @lakshyagithub. At this time GitHub Desktop only supports editors that have been specifically integrated into the application. You can find the details of how this works along with the supported editors here:

https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md

We happily accept pull requests to integrate new editors. There is also a tracking issue where we are collecting feedback about better support for external editors: https://github.com/desktop/desktop/issues/7033

**Comment by steveward** [comment]
GitHub Desktop now provides support for [adding custom editors](https://docs.github.com/en/desktop/configuring-and-customizing-github-desktop/configuring-a-default-editor-in-github-desktop?platform=windows#configuring-a-custom-editor), so you can add Spyder IDE by following the steps in that linked help article. I'm going to close this out.

**Comment by lakshyaelite** [comment]
That's amazing! Thank you very much!
