### ISSUE TITLE
"Show Logs in Finder" results in no action

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1550]
Under Help menu, the item "Show Logs in Finder" does not do anything on a Mac.

v0.0.53, OSX 10.11.5

Reproduce:
- Open Desktop on Mac
- Select "Show Logs in Finder" from Help menu

<img width="499" alt="screen shot 2017-05-17 at 9 35 31 am" src="https://cloud.githubusercontent.com/assets/14828183/26156581/ca3738ea-3ae4-11e7-91e3-2ff9acdf5d99.png">

**Expected behaviour:** Logs in finder should open

**Actual behaviour:** Nothing opens

**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
@tierninho interesting - could this be due to the folder not existing on disk (like, we only create the folder when we need to, and the logger is instantiated lazily)?

**Comment by shiftkey** [comment]
I can reproduce this on the production build, but it works fine when running in dev mode 🤔

**Comment by joshaber** [comment]
Aha! So it doesn't work if the `logs` directory doesn't exist. We create it lazily the first time we log, so if we haven't logged anything, it won't exist.

It'd be nice to fix this but I'm gonna dereprioritize it since it only matters in the case where we haven't had to log.

**Comment by shiftkey** [comment]
> Aha! So it doesn't work if the `logs` directory doesn't exist.

🤦‍♂️ 

Marking this one as `up-for-grabs` - we should create the folder if it doesn't exist before we try and open it - that should make it all work.
