### ISSUE TITLE
Creating a new branch sometimes requires app restart

### ISSUE THREAD

**Issue by albertbori** [desktop/desktop#15501]
### The problem

Creating a new branch doesn't update the branch list nor switch to the new branch. An app restart fixes the issue.
This issue is not always reproducible, but I have experience it about once per week for the past few weeks

### Release version

3.1.2 (x64)

### Operating system

MacOS 12.6

### Steps to reproduce the behavior

1. Modify files in a branch without committing the modifications
2. Create a new branch (fig. A)
3. Choose to bring your changes to the new branch (fig. B)
4. Click "Switch Branch" (fig. C)

Expected results: The current branch should switch to the new branch that you just created and you should see your modified files in the navigator on the left.

Actual results: No change to the current branch. Modified files continue to show in the navigator on the left, as if they are still part of the previous branch. (fig. A)

Fig. A
![Screen Shot 2022-10-21 at 9 11 37 AM](https://user-images.githubusercontent.com/1742709/197205289-c2773bbc-f938-496c-bb23-36e41892dac2.png)

Fig. B
![Screen Shot 2022-10-21 at 9 11 54 AM](https://user-images.githubusercontent.com/1742709/197205305-1d1b023e-25c8-4333-bfe5-a4923eef8b74.png)

Fig. C
![Screen Shot 2022-10-21 at 9 12 02 AM](https://user-images.githubusercontent.com/1742709/197205318-663750e9-6ddc-43b3-8b9d-01631563f87d.png)

Note: I tried to upload multiple screenshots at once, but the bug form gave the following error: "Something went really wrong, and we can't process that file. Try Again." I had to upload them one at a time.

### Log files

[2022-10-21.desktop.production.log](https://github.com/desktop/desktop/files/9839327/2022-10-21.desktop.production.log)

**Comment by steveward** [comment]
@albertbori are you still encountering this issue? I've tried to reproduce it but have so far been unsuccessful.

**Comment by albertbori** [comment]
This issue happened to me once last week, but is occurring far less frequently than before. Note that this was happening against a Github enterprise repo.

Feel free to close this issue and I'll reopen it if it becomes a prevalent issue again.

**Comment by niik** [comment]
> Feel free to close this issue and I'll reopen it if it becomes a prevalent issue again.

:+1:
