### ISSUE TITLE
[macOS] "The user name or passphrase you entered is not correct." due to App Translocation after updating

### ISSUE THREAD

**Issue by gingerbeardman** [desktop/desktop#15513]
### The problem

Recently (the past 2 versions) when the app updates itself and I restart it, I am no longer logged in.

The app seems to be under translocation/gatekeeper protection and it's quite a hassle to get it to work properly. 

Login works, but ability to push remains broken. Restarting repeats the process

### Release version

3.1.2

### Operating system

macOS 12.6.1

### Steps to reproduce the behavior

1. use macOS
1. let app auto-update
1. restart app

### Log files

[2022-10-25.desktop.production.log](https://github.com/desktop/desktop/files/9856270/2022-10-25.desktop.production.log)

### Screenshots

<img width="420" alt="Screen shot 2022-10-25 at 01 55 03" src="https://user-images.githubusercontent.com/49612/197657379-a4d098e2-ff38-4432-9f94-27d8b2900d3a.png">

<img width="624" alt="Screen shot 2022-10-25 at 01 54 45" src="https://user-images.githubusercontent.com/49612/197657383-4b80bc37-1345-498c-9a71-44d85ec1be2c.png">

### Additional context

To workaround the issue:

1. move the app somewhere out of Applications (I chose Documents)
1. zip the app using macOS Finder built in compress menu item 
1. delete the original app
1. unzip the zip to get the app back
1. move the app to Applications folder
1. delete zip if it's still there

**Comment by steveward** [comment]
@gingerbeardman thanks for the report. Previously when we've seen the `The user name or passphrase you entered is not correct' error locking and unlocking the `login` keychain in `Keychain Access.app` has resolved it. Have you tried that to see if it resolves the issue?

**Comment by gingerbeardman** [comment]
Curious! 

However, my login keychain is already unlocked. So, no, it does not resolve the issue for me.

I have the zip & unzip workaround, but I'm wondering why it's needed.

It would be great if the Desktop could detect it was running under App Translocation and... do or prompt something?

**Comment by gingerbeardman** [comment]
Just had this again updating in-app from 3.1.2 to 3.1.5 on macOS 12.6.3

My workaround this time was different: simply download latest through the website and install manually through unzip, mount, drag-and-drop, open.

Bizarre that installing through the in-app update ends up with the app being in App Translocation purgatory.

**Comment by gingerbeardman** [comment]
Happened again with the most recent update 3.2.1

Can't remember if I was upgraded to any interim releases.

- 3.2.0
- 3.1.8
- 3.1.7
- 3.1.6

**Comment by gingerbeardman** [comment]
And again with 3.2.3

**Comment by gingerbeardman** [comment]
Still happening

- 3.2.6

**Comment by gingerbeardman** [comment]
happened again with 

- 3.2.9

**Comment by gingerbeardman** [comment]
3.3.1 OK

**Comment by gingerbeardman** [comment]
3.3.3 OK

**Comment by gingerbeardman** [comment]
3.3.4 OK

**Comment by niik** [comment]
@gingerbeardman :wave: Going through stale issues, are you still experiencing this issue?

**Comment by gingerbeardman** [comment]
I'm currently on 3.4.5 and have not had it for a while. 

Closing. Will reopen if it happens again.
