### ISSUE TITLE
Incorrect text selection box on long wrapped line

### ISSUE THREAD

**Issue by saschanaz** [desktop/desktop#1551]
### Description

Text selection box appears across multiple lines when the selected line is long and wrapped

![image](https://cloud.githubusercontent.com/assets/3396686/26156760/517188e8-3b52-11e7-8ce9-5a9b2ef1ad20.png)

### Version

**GitHub Desktop version:** 0.5.3

**OS version:** 10.0.15063

### Steps to Reproduce

1. Select a long wrapped line
1. Check the selection box

**Expected behaviour:** The box shouldn't appear across the lines

**Actual behaviour:** It appears across the lines

**Reproduces how often:** 100%

**Comment by mdiep** [comment]
You're also unable to select anything from any wrapped lines.

![selection](https://cloud.githubusercontent.com/assets/1302/26258649/8fc9a746-3c93-11e7-9a90-69ff39a5e84e.png)

I tried to select `scanner.currentLine`. But when I copy and paste, it's only ever `nnableError(message`.

**Comment by xlc** [comment]
Selection is very bad. Select & copy & paste always missed the first character for me

**Comment by shiftkey** [comment]
> Select & copy & paste always missed the first character for me

@xlc if this is the behaviour I suspect it is, this has been fixed in #2499 and will go out in the next upate.

**Comment by adamreisnz** [comment]
Any chance this issue could be prioritised for a fix? Copying code from commits is something quite common and it would be great if it would work properly.

**Comment by j-f1** [comment]
I’m looking into removing CodeMirror altogether, which should resolve this issue.
