### ISSUE TITLE
Authentification for non-GitHub repositories

### ISSUE THREAD

**Issue by ibot3** [desktop/desktop#1552]
### Description

It's not possible to use foreign git repositories (e.g. when you're hosting a git server yourself)  at the moment. The option to use custom credentials for the authentification is missing.
However, this function existed in the old version.

### Version

**GitHub Desktop version:** 0.5.3

**OS version:** Microsoft Windows [Version 10.0.14393]

**Comment by niik** [comment]
Thanks for opening this @ibot3, I believe this is captured in #852 so please follow along there.
