### ISSUE TITLE
Can't ask credentials for an LFS authentication

### ISSUE THREAD

**Issue by Noxalus** [desktop/desktop#15534]
### The problem

Hello everyone,

I have a repository that I want to clone with GitHub Desktop, but this repository has something special because it uses an AWS server to store its LFS files and this AWS server needs credentials to retrieve the files.

On most of Git client, it will work since a window shows up asking for LFS credentials, but in Github Desktop it does nothing, just waiting.

### Release version

3.1.2

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Go to File > Clone Repository
2. Click on URL tab and type the repository URL that has its LFS files on an AWS server
3. It should stuck to "Updating files: 100%" forever

### Log files

I have this:

`2022-10-27T09:30:19.094Z - info: [ui] [AppStore.getAccountForRemoteURL] no generic credentials found for 'git@gitlab.com:[REPO].git'`

But even if we can think it's related, I think it's actually not because I have the same message for another repository that use Gitlab with LFS files but on the Gitlab servers and it's working as expected!

### Screenshots

![image](https://user-images.githubusercontent.com/1321964/198248326-43c52cc7-dc69-4ec7-9507-b1ce695be95b.png)

**Comment by steveward** [comment]
Thanks for the issue @Noxalus. This was previously reported in https://github.com/desktop/desktop/issues/11575. I mentioned a potential workaround in [this comment](https://github.com/desktop/desktop/issues/11575#issuecomment-780117373) -- would that be a potential solution for you?

**Comment by tackoman** [comment]
> ### The problem
> Hello everyone,
> 
> I have a repository that I want to clone with GitHub Desktop, but this repository has something special because it uses an AWS server to store its LFS files and this AWS server needs credentials to retrieve the files.
> 
> On most of Git client, it will work since a window shows up asking for LFS credentials, but in Github Desktop it does nothing, just waiting.
> 
> ### Release version
> 3.1.2
> 
> ### Operating system
> Windows 11
> 
> ### Steps to reproduce the behavior
> 1. Go to File > Clone Repository
> 2. Click on URL tab and type the repository URL that has its LFS files on an AWS server
> 3. It should stuck to "Updating files: 100%" forever
> 
> ### Log files
> I have this:
> 
> `2022-10-27T09:30:19.094Z - info: [ui] [AppStore.getAccountForRemoteURL] no generic credentials found for 'git@gitlab.com:[REPO].git'`
> 
> But even if we can think it's related, I think it's actually not because I have the same message for another repository that use Gitlab with LFS files but on the Gitlab servers and it's working as expected!
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/1321964/198248326-43c52cc7-dc69-4ec7-9507-b1ce695be95b.png)
> 
> ### Additional context
> _No response_

**Comment by Noxalus** [comment]
Arf, sorry, I didn't see that there was already an issue for that 😰 

I did a fresh installation of Windows 10 on a virtual machine and installed: Git, Git LFS, and GitHub Desktop. I generated a new SSH key and added it to GitLab and started to clone the repository.

In this context, `git config credential.helper` returns `manager-core`.

I tried the solution in the other issue adding this to my `~/.gitconfig`:

```
[credential "https://my-aws-url.com"]
    helper = store
```

And I cloned the repository using Git Bash. Now, I have a `.git-credentials` next to the `.gitconfig` file containing this:

```
https://[USERNAME]:[PASSWORD]@my-aws-url.com
```

Unfortunately, when I try to clone the same repository it doesn't work 😢 It's always stuck to the `Updating files: 100%` step. (I even reboot the virtual machine to be sure, but the problem persists)

However, if I try to clone the repository using Git Bash again, I don't have the credentials window anymore, I can retrieve LFS file directly, so the `store` thing seems to work anyway. 🤔 

And I still don't have much info in the GitHub Desktop log.

I was wondering, I know that some Git clients seem to use the Windows authentication manager for that, I also tried to add the credentials in there, but GitHub Desktop doesn't seem to use it. Can it be a solution to be sure the plain text credentials don't stay in a file?

Thanks a lot in advance for your help! 🙏

**Comment by Noxalus** [comment]
To complete my previous message, I also tried to open the freshly cloned (with Git Bash) repository in GitHub Desktop to see if I could push/pull LFS files, and unfortunately, it's waiting forever too:

![image](https://user-images.githubusercontent.com/1321964/198555510-37d380ef-543f-4e16-b91d-fd0e7e860b42.png)

And I have no message in the log related to this issue 😢

**Comment by steveward** [comment]
Consolidating into https://github.com/desktop/desktop/issues/11575.
