### ISSUE TITLE
Shift+DownArrow cannot select multiple commits in History tab

### ISSUE THREAD

**Issue by angusdev** [desktop/desktop#15536]
### The problem

In History tab, can use Shift+UpArrow to select multiple continous items.  But Shift+DownArrow can only select 1 or 2 items.  See the screenshot video for details.

### Release version

3.1.2

### Operating system

darwin-arm64

### Steps to reproduce the behavior

**Steps**
1. Go to History tab
2. Select first item
3. Press Shift+DownArrow
4. Press Shift+DownArrow again

***Expected***
Items 1-3 are selected

***Actual***
Only Item 2 is selected

### Screenshots

https://user-images.githubusercontent.com/34896/198418693-f2c8bb8c-bcab-4ca3-a557-8c025e8cdb7a.mov

### Additional context

`List` use `selectedRows` to determine the `selectionOrigin` and `lastSelection`. However `selectedRows` is sorted by decending order in `CommitList` in favour of cherry-pick handling. 

For example, when select row 5 and press up-arrow, `selectedRows = [5, 4]`. Then further press up-arrow will see `selectionOrigin = 5`, `lastSelection = 4`, `direction = 'up'`, so the next selected row = 3.

However, when select row 5 and press down-arrow, `selectedRows = [6, 5]` since it is sorted.  Then further press down-arrow wil see `selectedOrigin = 6`, `lastSelection = 5`, so the next selected row = 6, which the new `selectedRows = [6]`, then `[7, 6]`, `[7]`, `[8, 7]` etc.

https://github.com/desktop/desktop/blob/e6465802a25887c42747acbb07b1902af24e728f/app/src/ui/lib/list/list.tsx#L603-L611

https://github.com/desktop/desktop/blob/e6465802a25887c42747acbb07b1902af24e728f/app/src/ui/history/commit-list.tsx#L277-L287

There are four solutions:
1. Do not use `selectedRows` to determine `selectionOrigin` and `lastSelection`.  Instead explicit store these two values in states.  It is based on assumption that `selectRows` is passed by parent and not guaranteed in order of selection made. In this case needs to handle different keyboard and mouse events.  
2. Do not sort `selectedRows` in `CommitList` and handle the ordering of commits in function applying cherry-pick.  It is based on assumption that the order `selectedRow` should not be altered.
3. Remove `selectedRows` from `List.props`.  `selectedRows` should be internal state of `List` only. May add a `initialSelectedRows` for initialization only.
4. In `CommitList`, keep a separate unsorted copy of `selectedRows` and pass in `render()` instead of using the sorted `selectedSHAs`.  This is the simplest solution to solve this particular issue, but `selectedRows` may still be misused by other components.

https://github.com/desktop/desktop/blob/e6465802a25887c42747acbb07b1902af24e728f/app/src/ui/history/commit-list.tsx#L401-L408

**Comment by sergiou87** [comment]
I think @tidy-dev has some thoughts about this. Thanks for looking into it!
