### ISSUE TITLE
goto vscode on line

### ISSUE THREAD

**Issue by jonlepage** [desktop/desktop#15532]
### The feature request

Can we have on right click in the line `open in vscode` ? 
To go on the current file open in vscode ?

![image](https://user-images.githubusercontent.com/24865815/198115678-fdee92fb-6699-46ad-849b-35a35f86d8a3.png)

### Proposed solution

![image](https://user-images.githubusercontent.com/24865815/198115689-13fd2a93-52a9-4201-90b8-f00d096cc154.png)

**Comment by angusdev** [comment]
You can right click the filename to open in external editor

![github](https://user-images.githubusercontent.com/34896/198119138-210ee1f6-1628-49c1-bb3c-654dc5b5a992.png)

**Comment by steveward** [comment]
Thanks for the issue @djmisterjon. I know a number of editors support command line arguments to launch into specific lines in a file, but at this time this isn't likely something we'd implement right now. I'm going to add this to https://github.com/desktop/desktop/issues/5083 where we are tracking feedback about allowing for custom editor commands.
