### ISSUE TITLE
Unable to select different external editor from Integrations menu

### ISSUE THREAD

**Issue by NinjaFocks** [desktop/desktop#15543]
### The problem

When trying to change my default external editor I have an empty dropdown option and cannot select a different program.

### Release version

3.1.3-beta2

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. Click File
3. Click Options
4. Click Integrations
5. Click the External editor dropdown to open it

### Log files

[2022-10-31.desktop.production.log](https://github.com/desktop/desktop/files/9900150/2022-10-31.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/13572598/198984530-76bb08ad-fbe9-4e47-8c62-990b1c085417.png)

**Comment by steveward** [comment]
@NinjaFocks thanks for the issue. What other editors do you have installed on your system? We have a list here of supported editors:

https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/configuring-and-customizing-github-desktop/configuring-a-default-editor

If you're not seeing a specific editor from that list we can investigate why it might not be showing up.

**Comment by parkonabeach** [comment]
I have same issue.

**Comment by AlexH263128** [comment]
I aslo experience the same issue I want to change it to visual studio but it doesnt let me

**Comment by steveward** [comment]
@AlexH263128 Visual Studio is not officially supported in the app as an integration, but the [latest beta version](https://github.com/desktop/desktop#beta-channel) supports selecting a custom editor. That will allow you to select Visual Studio.

**Comment by Bond-Addict** [comment]
> [@AlexH263128](https://github.com/AlexH263128) Visual Studio is not officially supported in the app as an integration, but the [latest beta version](https://github.com/desktop/desktop#beta-channel) supports selecting a custom editor. That will allow you to select Visual Studio.

Except it won't open even if you give the it devenv.exe path as a custom editor.

**Comment by Bond-Addict** [comment]
![Image](https://github.com/user-attachments/assets/7f2f9e5a-288c-4f29-ab79-21df3a32be26)

Still opens in vscode even though it shows it will open in nodepad++ which isn't even an option I use

![Image](https://github.com/user-attachments/assets/d8538e0a-b5ae-44a0-b0f6-fcd66aa552cc)

**Comment by dannychen123** [comment]
> [@AlexH263128](https://github.com/AlexH263128) Visual Studio is not officially supported in the app as an integration, but the [latest beta version](https://github.com/desktop/desktop#beta-channel) supports selecting a custom editor. That will allow you to select Visual Studio.

Excuse me, it still exists  the problem that changing custom editor.  I want to transfer from Visual Studio Code to Trae, but it can't. Could you provide some solutions, thank u.
