### ISSUE TITLE
Github Desktop is still trying to send deleted files.

### ISSUE THREAD

**Issue by DennisRodriguez** [desktop/desktop#15541]
### The problem

I have 1 png file which is about 190MB. After removing it from the repository and publishing it to Github it's giving me an error saying that it exceeds the file restriction of 100MB. 

I tried running the following commands in git bash but the repositories are unchanged.

git filter-branch --index-filter "git rm -rf --cached --ignore-unmatch Receipt Image/RPH/1b1.png" HEAD
git filter-branch --tree-filter 'rm -f Receipt Image\RPH\1b1.png' -- --all
git filter-branch --index-filter 'git rm -r --cached --ignore-unmatch Receipt Image/RPH/1b1.png' HEAD

I used the ff command to remove the file

git rm "Receipt Image/RPH/1b1.png"
git commit -m "remove Receipt Image/RPH/1b1.png"

### Release version

Version 3.1.2 (x64)

### Operating system

Windows 11 64bit

### Screenshots

![Error Img1](https://user-images.githubusercontent.com/18585718/198882225-e8fe992e-ef08-4dd0-a1a4-63077f127990.png)
![Error Img2](https://user-images.githubusercontent.com/18585718/198882240-3377c87b-747c-40c6-a3b1-8927cdff1d29.png)

**Comment by steveward** [comment]
@DennisRodriguez there are a couple of solutions in the ["Removing sensitive data"](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#purging-a-file-from-your-repositorys-history) help article that should be able to remove that file from your repository.

I hope that helps! I'm going to close this out, but let me know if you are unable to resolve this and we can investigate further.
