### ISSUE TITLE
Show current branches in repository list

### ISSUE THREAD

**Issue by FredWabs** [desktop/desktop#15544]
### The feature request

My application is composed of several packages, and I have one repository per package.
When I switch from one branch to another (master for example), I do so on several repositories, but not necessarily all of them.
I have to check several times to be sure that each repository is on the right branch, selecting each repository one after the other.

### Proposed solution

It would be nice to see on the same view the current branch for each of the repositories.
![View Branch](https://user-images.githubusercontent.com/70717486/198995736-66a477ff-75eb-4fbf-9257-b79cc8313886.png)

**Comment by steveward** [comment]
Thanks for the feedback @FredWabs, I'm going to add this to https://github.com/desktop/desktop/issues/8158 where we are tracking this request.
