### ISSUE TITLE
Unable to log in to GitHub Desktop

### ISSUE THREAD

**Issue by Emenchena** [desktop/desktop#15540]
### The problem

I am entering a real password and username on git hub desktop but it doesnt log in

### Release version

dhhnf

### Operating system

hed

### Log files

bxvc 

### Screenshots

bd cv 

### Additional context

 f nv

**Comment by steveward** [comment]
@Emenchena GitHub Desktop should prompt you to authenticate via your browser -- it sounds like you may be trying to authenticate via the authentication failed dialog which will not work. See [this help article](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/installing-and-authenticating-to-github-desktop/authenticating-to-github) for steps on how to authenticate.

I'm going to close this out, but let me know if you continue to have issues and we can investigate further.
