### ISSUE TITLE
change my repository from private to public

### ISSUE THREAD

**Issue by Dev-Emmyy** [desktop/desktop#15557]
i have been trying to change my repository privacy from private to public but the change visibility isn't working.

**Comment by steveward** [comment]
@Gunna9999 this issue tracker is for GitHub Desktop -- you will need to follow [this article](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility) to change your repository visibility in your browser.
