### ISSUE TITLE
Github Desktop can't see the VS Code

### ISSUE THREAD

**Issue by Fokser665** [desktop/desktop#15552]
![image](https://user-images.githubusercontent.com/60878939/199505530-8c308273-0af0-4c33-9062-f6b02bbf617e.png)

I have Pop_Os! on my laptop and I have installed VS Code on it. I can't find the answer why Github Desktop doesn't see VS Code on my computer...

**Comment by tidy-dev** [comment]
Hi @Fokser665 ! 👋 Issues related to the unofficial Linux fork of GitHub Desktop can be filed here:

https://github.com/shiftkey/desktop/issues

At this time we only officially provide support for macOS and Windows.

Sorry!
