### ISSUE TITLE
Block 'drag n drop' of existing repos

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1555]
Users shouldn't be able to drag n drop an existing repo in Desktop. Need some kind of messaging.

v0.5.3, OSX 10.11.5

Reproduce
- Drag an existing repo in Desktop
- Fetch occurs

**Expected behaviour:** Warning for user that repo already exists.

**Actual behaviour:** Fetch occurs, and user can drag n drop the same repo multiple times

**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
For reference, the Classic Windows app will just focus on the existing repository when you try to re-add it. I think the Mac app does the same thing.

> Fetch occurs, and user can drag n drop the same repo multiple times

If you now have multiple instances of the application in the repository list, that's a bug.

**Comment by tierninho** [comment]
Yes, it's just a re-focus. Feel free to close if needed.

**Comment by shiftkey** [comment]
@tierninho :thumbsup:
