### ISSUE TITLE
The github desktop

### ISSUE THREAD

**Issue by Laurence3480** [desktop/desktop#15551]
### The feature request

Can the github desktop use Chinese?

### Proposed solution

Make a Chinese version of GitHub Desktop.

**Comment by steveward** [comment]
Thanks for the issue @Laurence3480. At this time we do not have language localization in GitHub Desktop, but this is something that we would like to do in the future. I don't have a timeline for when that may happen as it would require quite a bit of work by the team. I'm sorry that I don't have better news at this time.

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/GitHub-Desktop-Chinese-Language-Pack
