### ISSUE TITLE
Add option to enable the native window frame on windows

### ISSUE THREAD

**Issue by edo9300** [desktop/desktop#15554]
### The feature request

Hi, i'd like to know how possible would it be to add an option to enable/disable the native window frame on windows and prevent github from drawing its own decorations, so that it would look like this.
![immagine](https://user-images.githubusercontent.com/18705342/199613289-ede2b8c2-c002-4637-924e-5598bb9e85b0.png)
(I manually modified my local install with the needed changes, but it would be nice to have such option in the main program.)

### Proposed solution

Just a little change for someone who prefer server side decorations and likes the white titlebar in windows 10, shouldn't be an issue interfering too much with the program, it would also remove the need for a patch that is being applied on the linux "port" of github desktop https://github.com/shiftkey/desktop/commit/c020d905f65b97b9adc8d82c06de3db42b04c457 as it could just reuse the same option.

**Comment by steveward** [comment]
Thanks for the issue @edo9300. This is being tracked in https://github.com/desktop/desktop/issues/1585. I'll close this out and reference this issue there.
