### ISSUE TITLE
Feature Request: File Explorer

### ISSUE THREAD

**Issue by alrz** [desktop/desktop#1556]
Change "Changes" tab to "Files" with a search box (similar to https://github.com/desktop/desktop/issues/1543) to filter (wildcard-aware) all files including unchanged ones, in order to view, edit, log, blame, open in explorer, etc. 

**SmartGit** has something like this today.

**Comment by shiftkey** [comment]
> all files including unchanged ones, in order to view, edit, log, blame, open in explorer, etc.

@alrz there's a lot to unpack here. Could you describe a couple of _workflows_ here that this change would enable, and the details around why this is helpful? It'd be nice to discuss the breadth of this idea beyond just the UI change.

**Comment by alrz** [comment]
You can't view, edit, log, blame files that are not externally changed, because they would not show up in the "Changes" tab. Note: this request is assuming that we're going to have context actions on those files .

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
@alrz Thanks for this idea as well. However, similarly, it's not super clear what problem this is solving and we view Desktop more as a workflow tool to help you as you're writing code, and less as a repo file explorer. I'm going to remove `future-proposal` to reflect that we don't plan to implement this, and we'll continue to listen to users to understand if there are problems in Desktop that could be solved by more robust interaction with files themselves. Thanks again.
