### ISSUE TITLE
Keep GitHub Desktop Current

### ISSUE THREAD

**Issue by drewtwitchell** [desktop/desktop#15560]
### The feature request

Right now, GitHub desktop periodically fetches and prompts user to pull origin for the base branch. I would like to see an option that always keeps Github desktop in sync with anything merged into the base branch and then show the changes between the base branch and your active branch.  There have been too many times I raise a PR and need to hit the update branch button. I would like to see that just happen automatically so that the branch I am working on which is based on the branch with active changes automatically updates. This way I can quickly resolve any conflicts and get the latest changes to a given branch, especially in an active team where many merges are happening often.

### Proposed solution

Github desktop automatically updates the current branch with the newly merged changes so that the editor flags conflicts and you as the user doesn't override changes or need to hit the update branch when raising a PR. This will greatly assist in keeping our development agile and less conflicts.

**Comment by niik** [comment]
Hey @drewtwitchell, thanks for the feedback! While I can certainly see workflows where automatic merging from the default branch would make things more streamlined there are unfortunately much too many scenarios where it would cause confusion and unexpected behavior. This is also why we only fast forward local branches to their tracking branches as long as the branch isn't the currently checked out branch.

So if you're working on a feature branch we will fast forward the default branch in the background periodically so you could try making it a habit to hit Cmd+Shift+U in your feature branch before pushing, that will merge the default branch into the feature branch if there are any changes that your branch is missing.

We are interested in finding ways to notify users of scenarios like this as long as they then can choose to take action or not. We did have a notification for when the default branch had diverged from the current but lack of use and a non-optimal design and implementation made us rip it out. It's entirely possible that we'd bring that back in the future though.
