### ISSUE TITLE
This error usually occurs when a fatal SSL/TLS alert is received

### ISSUE THREAD

**Issue by chuongmep** [desktop/desktop#15577]
### The problem

fatal: unable to access 'https://github.com/specklesystems/speckle-docs.git/': schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). More detail may be available in the Windows System event log.

### Release version

3.1.2

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Open Github 
2. Fetch origin
3. See error

### Log files

[2022-11-08.desktop.production.log](https://github.com/desktop/desktop/files/9956596/2022-11-08.desktop.production.log)

### Screenshots

![ảnh](https://user-images.githubusercontent.com/31106432/200445412-39a08656-e842-4377-a8d1-0a1300d855c8.png)

### Additional context

This is new problem with my computer in company, don't have any problem when use laptop at home.

**Comment by sergiou87** [comment]
Hey @chuongmep ! 👋 

Looking at your logs, it says:
> fatal: unable to access 'https://github.com/chuongmep/speckle-docs.git/': schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). **More detail may be available in the Windows System event log.**

Could you check if there is anything relevant in the Window System event log?

In any case, this issue seems to be caused by having a proxy, or a firewall or antivirus messing with https connections (for example, see https://github.com/desktop/desktop/issues/15440). Is that your case?

**Comment by chuongmep** [comment]
@sergiou87 same with my case , problem cause just when I use final version upgrade.
Bad new is I can't see any event from my computer in company.
![ảnh](https://user-images.githubusercontent.com/31106432/200534412-62811b6e-1911-428f-9107-572e5d31f4bb.png)

**Comment by steveward** [comment]
@chuongmep do you encounter this error when working with Git from the command line? Can you each out to someone in your company IT department to see if they have an idea of what may be interfering with your connection?

**Comment by chuongmep** [comment]
@steveward  don't have any problem when I use git, FYI
![ảnh](https://user-images.githubusercontent.com/31106432/200730400-8d23a626-2680-4594-9140-c0de51df026a.png)

**Comment by steveward** [comment]
It definitely seems likely that something on your network or machine is blocking GitHub Desktop. Can you reach out to someone in your company IT department about this?

**Comment by chuongmep** [comment]
Hi @steveward , you are correct. I contacted with IT in Company and this  file GithubAuth.Exe blocked by IT , many thanks !
