### ISSUE TITLE
Latest (3.1.2) install failure The application "Github Desktop.app" can't be opened on M1 macOS Monterey 12.6.1 

### ISSUE THREAD

**Issue by sujit-p** [desktop/desktop#15576]
### The problem

I got a new M1 macbook pro last week, it has macOS Monterey 12.6.1. As it is a work laptop, cannot upgrade to latest OS.
I downloaded the apple silicon version of GitHub Desktop v 3.1.2, extracted zip, tried to run the app and i get this error:
![image](https://user-images.githubusercontent.com/21952256/200444659-1d2ceb51-93c9-496f-a1c5-6e2676a006de.png)
Copying the app to Applications folder also causes the same error message

### Release version

3.1.2

### Operating system

MacOS Monterey

### Steps to reproduce the behavior

Try to run the latest build.

### Screenshots

![image](https://user-images.githubusercontent.com/21952256/200444861-41f166d9-7a27-4f05-a84b-3f22132055ad.png)

**Comment by steveward** [comment]
Thanks for the report @sujit-p. Is this a work machine that restricts what applications you can run? Have you tried rebooting your machine to see if that helps?

**Comment by sujit-p** [comment]
It is a work machine, it does not restrict anything. I have installed lot of common dev tools on it without any issues. I tried rebooting as well. My colleague who got the same model mac as I few months back has no issues running the latest github desktop , but that might be because he had an older version, and it installed fine and auto-update worked fine but new installs fail.

**Comment by sujit-p** [comment]
Is it possible to get an older version of github desktop for M1 mac?

**Comment by sujit-p** [comment]
![image](https://user-images.githubusercontent.com/21952256/201766281-fd13009a-472b-4a5d-83f1-f5c2f7f236c9.png)

I tried running it from terminal and got this error:
The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x60000114cea0 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}

**Comment by sujit-p** [comment]
Well, finally I zipped and copied over the GitHubDesktop app from the colleague on whose mac, it works.
And that copied over app work perfectly on my mac. Both macs have the exact same hardware and software. I'm suspecting something wrong in the latest Apple Silicon installer.

**Comment by steveward** [comment]
I'm going to close this out as the initial issue was resolved, and we haven't had any further reports of installation problems on Apple Silicon.

**Comment by davidfrey** [comment]
I was having the same issue on a Macbook Pro M1. When attempting to open the app from the terminal I get the following error. I have tried downloading and running both x64 and arm64 packages.

```
The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600003c16610 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}
```

I've even attempted to try an a Macbook Pro Intel and get a similar error that ultimately indicated the application was damaged and could harm my computer. 

Out of desperation I tried reinstalling the latest x64 package on my Intel mac, confirmed that it was working, then airdropped the application directly to the M1 mac. For whatever reason this worked.

I'm not sure if this is helpful or not. I had never installed the desktop app on my M1 before in case that has any relevance to the situation. I even tried beta downloads for both x64 and arm64. The only difference I can imagine without dumping a ton of investigation time is that I unpacked the zips on my Intel and that somehow produced a different result than the Apple silicone.

**Comment by callmedeeray** [comment]
> Well, finally I zipped and copied over the GitHubDesktop app from the colleague on whose mac, it works. And that copied over app work perfectly on my mac. Both macs have the exact same hardware and software. I'm suspecting something wrong in the latest Apple Silicon installer.

I was having this EXACT same problem.  On my work computer, no restrictions on what I can install (to my knowledge), same error message in the terminal, etc.  I have been googling for days and days to figure out what's wrong.  Lo and behold, GitHub Desktop still works on my personal Macbook Pro, same year, same OS, etc, so I tried zipping up that .app file and opening it on my work computer.  BOOM it works!  THANK YOUUU @sujit-p  !!!
