### ISSUE TITLE
Branch Tree View

### ISSUE THREAD

**Issue by zeelsheladiya** [desktop/desktop#15571]
### The feature request

easy to understand commit, changes, and history graph with branch tree view. It can give us visual information about branches and the current working directory instead of a branch list primarily when you work in a group. Both place Change and History tabs have a list view. Sometimes I have the same file name in a different folder and I made changes it seems a bit confusing to me so in the change tab can we make a tree view of changes with the directory and its folder? and also branch tree view in history tab.

### Proposed solution

![image](https://user-images.githubusercontent.com/46935793/200227653-39884f98-633f-4065-b74d-8b44bba36616.png)

![image](https://user-images.githubusercontent.com/46935793/200225794-837965f5-8759-4c61-8f81-c6218b2f6bc7.png)

**Comment by steveward** [comment]
Thanks for the issue @zeelsheladiya, I'm going to add this to https://github.com/desktop/desktop/issues/2417 where we are collecting feedback about this feature.

**Comment by Inoy1st** [comment]
Oh when?
I need the branch tree view.

**Comment by noway13011996** [comment]
I need the branch tree view.
