### ISSUE TITLE
Can't login to Github account on Github desktop

### ISSUE THREAD

**Issue by ArturLX** [desktop/desktop#15573]
### The problem

When i try to login to my github account on github desktop via browser i'm recieving an error message in the github client

### Release version

3.1.1-linux1

### Operating system

Manjaro/KDE

### Screenshots

![2022-11-07_13-47](https://user-images.githubusercontent.com/112889284/200314589-d0de6fe2-2e65-4581-b4c9-80d4b317a39b.png)

**Comment by sergiou87** [comment]
@ArturLX issues related to the unofficial Linux fork of GitHub Desktop can be filed here:

https://github.com/shiftkey/desktop/issues

At this time we only officially provide support for macOS and Windows.

Sorry!

**Comment by ArturLX** [comment]
i see thank you!
