### ISSUE TITLE
Repositories are shown as "not found" when they have too many changes (`git status` output is too large)

### ISSUE THREAD

**Issue by srinivassivaratri** [desktop/desktop#15586]
![Screenshot (377)](https://user-images.githubusercontent.com/94376763/200813418-58eb0225-1571-4a54-b6a4-8953e2901f54.png)
![Screenshot (378)](https://user-images.githubusercontent.com/94376763/200813426-1dcafc97-feb0-4625-890a-edea5c2c9b33.png)
![Screenshot (379)](https://user-images.githubusercontent.com/94376763/200813428-97f97d44-c436-47f9-9116-bacf8c0d5d64.png)

I have been tinkering with this issue for the past 4 days, though I have tried other  references, they didn't provide me the proper solution. I hope you resolve my issue.

**Comment by sergiou87** [comment]
While we investigate the reason behind this issue, could you try moving those repositories to another folder? Let's say to Documents. I wonder if it has anything to do with that.

Other than that, it'd be super helpful if you could attach your logs. To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by srinivassivaratri** [comment]
I tried moving those folders to documents but there is no use, it is showing me the same error as before when the folder is on the desktop.

**Comment by srinivassivaratri** [comment]
![Screenshot (380)](https://user-images.githubusercontent.com/94376763/200870430-b83f26b3-4d83-48ed-a57a-1cb3057ac904.png)
 I experienced issues for the past 3 days.

**Comment by steveward** [comment]
@Curious41099 can you upload the most recent log file from that directory? You can drag-and-drop it directly into an issue comment to upload it. Thanks.

**Comment by srinivassivaratri** [comment]
[2022-11-09.desktop.production.log](https://github.com/desktop/desktop/files/9973889/2022-11-09.desktop.production.log)

this is the most recent log file I have in my directory. 
Thanks.

**Comment by srinivassivaratri** [comment]
> @Curious41099 can you upload the most recent log file from that directory? You can drag-and-drop it directly into an issue comment to upload it. Thanks.

[2022-11-09.desktop.production.log](https://github.com/desktop/desktop/files/9973889/2022-11-09.desktop.production.log)

**Comment by sergiou87** [comment]
Thanks for your logs! Looking at them, I think this is the problem:
```
error: [ui] 'git status' emitted 28676952 bytes, which is beyond the supported threshold of 20000000 bytes
```

That repository you're trying to add has so many changes that GitHub Desktop cannot even process them (more specifically, the output of running `git status` in your repo is too large). However, instead of displaying an error alert (as it should), it's just marking it as "not a repository" or "not found". In order to fix this, you will need to use the terminal to either commit or discard changes until they get to a reasonable amount and then I think GitHub Desktop should be able to open your repository.

To confirm this, just run `git status` in your repository from a terminal, and check if there are many many changes in there.

**Comment by srinivassivaratri** [comment]
> Thanks for your logs! Looking at them, I think this is the problem:
> 
> ```
> error: [ui] 'git status' emitted 28676952 bytes, which is beyond the supported threshold of 20000000 bytes
> ```
> 
> That repository you're trying to add has so many changes that GitHub Desktop cannot even process them (more specifically, the output of running `git status` in your repo is too large). However, instead of displaying an error alert (as it should), it's just marking it as "not a repository" or "not found". In order to fix this, you will need to use the terminal to either commit or discard changes until they get to a reasonable amount and then I think GitHub Desktop should be able to open your repository.
> 
> To confirm this, just run `git status` in your repository from a terminal, and check if there are many many changes in there.

Hii Sergiou, thanks for taking your time out. can you please break it down In order to fix this, you will need to use the terminal to either commit or discard changes until they get to a reasonable amount and then I think GitHub Desktop should be able to open your repository?

" To confirm this, just run git status in your repository from a terminal, and check if there are many many changes in there.

these above lines for me to proceed forward. 

Also, can you give me the step-by-step process of how to go resolve this issue"

thanks,
Srinivas

**Comment by steveward** [comment]
To commit from the command line you will need to install [Git for Windows](https://git-scm.com/download/win) if you have not done so already. Once that's installed you can open Git and `cd` into your repository directory. Then commit the changes using `git add -A` followed by `git commit -m "commit message here"` to commit your changes. You can then run `github .` to open the repository directly in GitHub Desktop. Let us know if that doesn't get things working.

**Comment by sraka1** [comment]
@sergiou87 this is still an issue. For example, inadvertently changing the gitignore file can easily cause this issue (since there could be many files that are newly not ignored).

**Comment by andrealesani** [comment]
This issue also appears when some library in your project (*cough cough* ultralytics yolo) automatically downloads huge datasets for training and you are not fast enough to add those to the .gitignore.

It would be nice to receive a warning or something like that for this kind of situations when `git status` fails.

**Comment by steveward** [comment]
Reported again in https://github.com/desktop/desktop/issues/19405.
