### ISSUE TITLE
Authentication failed with Github Enterprise Server

### ISSUE THREAD

**Issue by daniel31079** [desktop/desktop#15581]
### The problem

Hello,

we are using Github Enterprise Server Version 3.5.6 and we currently migrated our Server into our Azure Cloud and changed its DNS Name - however it still should be reachable with the old DNS name.

In Sourcetree everything is working, but with Github Desktop i am getting the following error everytime i try to something e.g. fetch origin:
![image](https://user-images.githubusercontent.com/70377161/200563050-45135ee6-b552-43aa-82d7-85de9c362298.png)

According to our firewall to azure nothings gets blocked from Github Desktop - does anyone have an idea why it is giving me this error? 

I already tryed to relogin in Github Desktop with my Enterprise Server account using the new DNS Name, the Login works, but i cant do anything.
![image](https://user-images.githubusercontent.com/70377161/200563410-694606eb-88e0-4aec-b5c5-4d0c04fc73d8.png)

I also tryed reinstalling GH Desktop, still nothing changed.

Log:
![image](https://user-images.githubusercontent.com/70377161/200564486-ace6aab6-efed-444c-8e52-ea4a7c06f655.png)

Is it possible that is related that there is still the old DNS name in the reference for the repository? How do i change that one? As you can see i relogged in and already used the new DNS name.

Git Version i use is 2.35.2.windows.1

### Release version

3.1.2 (x64)

### Operating system

Windows 10 Enterprise 21H2

### Steps to reproduce the behavior

1. Open GH Desktop 
2. Log in with the GH Enterprise Server Account
3. Try to Fetch

### Log files

wont attach Logfiles, added Screenshot in Problem description

### Screenshots

see Problem Description

**Comment by sergiou87** [comment]
Weird. It says "Anonymous access denied" and "Authentication failed…" so I think it's not a DNS thing since it's managing to reach it, just failing the authentication.

However, it looks like the GHES domain name you used to sign in (`azeuwqi...`) doesn't match the domain where the repo is hosted (`atmarq...`), and GitHub Desktop uses that domain name of the repo to look for the account credentials to use. Could you sign out, and then sign in again but this time provide your GHES URL with the same domain name as the repository?

I _think_ that should make it work 🤞

**Comment by daniel31079** [comment]
Hey @sergiou87 thanks for the fast reply!

i tryed what you mentoined, now i am getting a new error: 
![image](https://user-images.githubusercontent.com/70377161/200582328-2c7583a3-658f-4c03-abbd-80062727542b.png)


Do i need to create an access token for GH Desktop?

I just read about this article, but the last upgrade for our Server has been made earlier to the Azure Migration.
https://docs.github.com/en/enterprise-server@3.3/rest/apps/oauth-applications

**Comment by sergiou87** [comment]
Hmmm but is your GHES instance hosted in the `atmar...` domain name? I also see the app is trying to hit `azeu.../login/oauth/access_token`, where does that `azeu...` come from? 🤔 

![2022-11-08 at 15 26](https://user-images.githubusercontent.com/1083228/200590683-33922c71-eed8-4cab-8671-aea499f7cf20.png)

Regarding using an access token… maybe? I mean, if it's a repo hosted in a GHES instance, the very same token you get when you sign in, is the one Desktop should use to operate with your repository. Only if your repository is not hosted by GitHub or your GHES instance you need an access token from wherever your repo is hosted. Does that make sense?

**Comment by daniel31079** [comment]
ATMAR was the old DNS name, AZEUW is the new one.

There has been a redirection created if someone uses ATMAR to AZEUW - but it seems like in this case this doesnt work.

I could fix the problem by deleting GH Desktop and then delete the Files in Appdata - those were left after uninstallation.

After that i reinstalled it, resigned with AZEUW - it still asked me for credentials for ATMAR - seems like this is saved somewhere else?

The curiousity is that it is now working ? You have any idea where the old DNS could possibly be saved and why it was refering to it? Of course the case can be closed if its easier for you guys since i guess you have other stuff todo.

Thanks for your help!

**Comment by sergiou87** [comment]
I have no idea how is that possible 🤔 Maybe Electron caches some of that stuff for us? In any case I'm very happy it's working now!!

Yeah as you say I'm gonna close this now. If we see this happening often, we'll dig more into it. Thank you for reporting back and for your patience 🙇‍♂️
