### ISSUE TITLE
doesnt detect changes

### ISSUE THREAD

**Issue by Enghellcraft** [desktop/desktop#15584]
### The problem

G desktop doesn't detect any changes i have made, I tried reinstalling and clonning again but it doest seem to get new information

### Release version

Version 3.1.2 (x64

### Operating system

windows 10

**Comment by CyberPunkRules** [comment]
I will help with a response sometime tomorrow if that’s ok….

C. Salcido

**Comment by tsvetilian-ty** [comment]
@Enghellcraft thanks for reaching out! Could you attach the full log files? The Help > Show Logs in Explorer menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.
