### ISSUE TITLE
Folder is potentially unsafe error

### ISSUE THREAD

**Issue by burakgunbatan** [desktop/desktop#15597]
### The problem

After auto-installation of Github Desktop - version 3.1.2, I have got this error. Software is identifying my folder as unsafe.
Could you please help me to fix it?

![image](https://user-images.githubusercontent.com/44951660/201123078-0549aeca-c722-4cba-86bd-bb8908995107.png)

### Release version

Github Desktop - version 3.1.2

### Operating system

Windows 10

### Log files

[2022-11-10.desktop.production.log](https://github.com/desktop/desktop/files/9981943/2022-11-10.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/44951660/201123671-1d07da85-f6d6-4a4a-b7fd-754b843fa44f.png)
![image](https://user-images.githubusercontent.com/44951660/201123776-8ad33ea7-ba7a-49b3-842f-051831ba199e.png)

**Comment by steveward** [comment]
@burakgunbatan I asked for some information about your system setup in the other issue you opened -- we can investigate this error in that issue as well. For reference we don't recommend storing repositories in file syncing services like OneDrive as it can cause issues. I'm going to close this out in favor of https://github.com/desktop/desktop/issues/15598.
