### ISSUE TITLE
Permission denied' 'exit status 255'

### ISSUE THREAD

**Issue by burakgunbatan** [desktop/desktop#15598]
### The problem

After auto-installation of Github desktop v3.1.2, I have started to get an error when I trying to open the tool.
Could you please help me to fix it?

You can find the log file and screenshot below.

### Release version

Github Desktop - version 3.1.2

### Operating system

Windows 10

### Log files

[2022-11-10.desktop.production.log](https://github.com/desktop/desktop/files/9982081/2022-11-10.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/44951660/201129597-ee55922b-9f8e-4c33-9e03-b8d1a7811502.png)

**Comment by steveward** [comment]
@burakgunbatan thanks for the issue. Just to confirm -- is this a fresh installation of GitHub Desktop?

Based on the error t looks like your `.gitconfig` is in `H://` -- is this a network drive that you've mapped your HOME directory to? Any information you can share about your system setup would be helpful for us in debugging this issue.

**Comment by burakgunbatan** [comment]
Hi Steveward,

It is not a fresh installation. I am already using the github desktop software and installed it last year to my laptop.
H is not my one drive or cloud based folder. Files are in my local folder.

**Comment by sergiou87** [comment]
@burakgunbatan Is it possible that some other git instance is locking that `.gitconfig`? I'd suggest you either take a look at the Task Manager, looking for rogue `git` instances, or just reboot your PC and try again.

Please, let us know if that helps 🤞
