### ISSUE TITLE
Always HEAD main/master

### ISSUE THREAD

**Issue by Kuranes** [desktop/desktop#15596]
### The feature request

Similar to the "periodically fetch repositoy" option I really miss in all git tools a "Always reset master/main to Latest HEAD"  checkbox option per repo (obv not default) as if we just cloned it, automatically. (ideally with a user script triggered on update).
(main/master or any branch but main/master makes most sense)

Many times we have repo + our fork out of github and we want to be able to build tools our-selves from scratch and follow evolution of fork source master/main branch to compare code/binaries with our fork/states

If afraid of making people loose work, a second checkbox (or combobox with multiple choice) that is a "Force reset" ( as in no stash, no warning of any sort, just want the HEAD of main/master/whatever branch we are on)

### Proposed solution

- Compare easily user fork with source fork
- Users can maintain their own set of tools based repository
- no need to update manually
- Main/master is in fact most of the time locked anyway (cannot push/edit directly on it)
- Most repo I clone I don't have any write on it, makes sense to always keep it up to date
-

**Comment by steveward** [comment]
Thanks for the issue @Kuranes. I'm going to reference this issue in https://github.com/desktop/desktop/issues/8509 where we are tracking overall improvements to forks.
