### ISSUE TITLE
Capital "I" and lowercase "l" are nearly identical

### ISSUE THREAD

**Issue by justingolden21** [desktop/desktop#15603]
### The feature request

Proposing using a font where "I" and "l" don't look nearly visually identical (as they do here as well). I assume this is due to using `Segoe UI` which is the OS default and in Github's font stack, which is a gorgeous font I might add, but confusing lowercase L and capital I makes it a poor choice for programming.

Thankfully (and obviously) the diff viewer shows a monospace font where the differences are quite clear.

### Proposed solution

Changing the font stack to use a font with a distinct lowercase L and capital I

### Additional context

![image](https://user-images.githubusercontent.com/30274440/201247816-66567a9a-e5b4-48d6-802d-357e372e87d9.png)

![image](https://user-images.githubusercontent.com/30274440/201247852-2c85a025-50af-42a1-81a5-34ca516a662d.png)

What does this say? "pollIdx" is what it says, but how many Ls and Is? The code diff shows an obvious diff between lowercase L and capital I.

**Comment by Ares8440** [comment]
(I) we I'll be replaced with (L)

**Comment by niik** [comment]
Hey @justingolden21, thanks for the feedback! Changing our font stack is not something we're looking to do right now. Adhering to the current platform's default font stack is a conscientious design decision to make our application feel at home within the rest of our users' applications. This also matches the behavior of GitHub.com which use the platform variable width font stack for things like filenames and the platform monospace font for code. I think there are ways we can help alleviate this in the future though. We've entertained the idea of a more versatile commit editor for example that could certainly help by providing a monospace mode for writing commits for those users where adhering to a strict commit format is important.
