### ISSUE TITLE
Discard Changes Should Notify User When Files Are In Use

### ISSUE THREAD

**Issue by AlanLivingston** [desktop/desktop#15601]
### The feature request

When files are open in another application, GitHub desktop cannot discard the changes.  However, it does not notify the user that the files are locked.  It just leaves the files in the Changes list.

### Proposed solution

A dialog should appear indicating the files are opened in another application.

### Additional context

The repo contains Word and Excel docs. If I open one in Excel (or Word), modify and save a file, but don't close Excel, I see the changed file show up in GitHub Desktop, but I cannot discard the change.

Looking at the log, this line was added each time I attempted to discard changes:

2022-11-10T20:25:16.535Z - info: [ui] No submodules found. Skipping "git submodule status"

**Comment by steveward** [comment]
Thanks for the issue @AlanLivingston. Discarding should work even if a file is open unless the files are specifically locked by another application or there is a leftover `index.lock` file from a crashed process. Would you mind sharing the log file from GitHub Desktop so I could see if there are any underlying errors that could give an idea of what's going on here?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by AlanLivingston** [comment]
Hi @steveward,

I've attached a log.

[2022-11-10.desktop.production.log](https://github.com/desktop/desktop/files/9984375/2022-11-10.desktop.production.log)

This repo contains Word and Excel docs.  If I open one in Excel (or Word), modify and save a file, but don't close Excel, I see the changed file show up in GitHub Desktop, but I cannot discard the change.

Looking at the log, this line was added each time I attempted to discard changes:

2022-11-10T20:25:16.535Z - info: [ui] No submodules found. Skipping "git submodule status"

**Comment by steveward** [comment]
@AlanLivingston are you still having any issues with this? I can see that the repository is on a B:/ drive, which could be causing issues as well if that is a network drive. I'm going to close this out as stale, but let me know if you're still having any problems and we can dig into this further.

**Comment by AlanLivingston** [comment]
@steveward Yes, I still see this issue.

I've tested this with the latest version 3.31 (x64) on a local C: path and still see the issue, so I don't think having the content on the B drive is the root cause.

I assume it's because Word has the file locked, and won't allow changes.  It's disconcerting for someone new to Git, but as I have become accustomed to GitHub's many quirks, I can usually figure out why changes aren't discarded.

I don't think closing as completed is appropriate.  WONT FIX or something similar would be more approriate.
