### ISSUE TITLE
cannot write keep file0b.keep': Filename too long   when   git desktop

### ISSUE THREAD

**Issue by 208yunyao** [desktop/desktop#15609]
### The problem

cannot write keep file0b.keep': Filename too long  
after set "git config core.longpaths true"  ,it also happen

### Release version

3.12

### Operating system

windows10

### Steps to reproduce the behavior

Cloning into 'C:\Users\ljun2\OneDrive - Intel Corporation\Documents\GitHub\containers.docker.p4language.p4verification\sources\containers.docker.p4language.p4verification\s\containers.docker.p4language.p4verification'...
remote: Enumerating objects: 359, done.        
remote: Counting objects: 100% (110/110), done.        
remote: Compressing objects: 100% (44/44), done.        
remote: Total 359 (delta 78), reused 85 (delta 66), pack-reused 249        
Receiving objects: 100% (359/359), 65.54 KiB | 684.00 KiB/s, done.
Resolving deltas: 100% (213/213), done.
fatal: cannot write keep file 'C:/Users/ljun2/OneDrive - Intel Corporation/Documents/GitHub/containers.docker.p4language.p4verification/sources/containers.docker.p4language.p4verification/s/containers.docker.p4language.p4verification/.git/objects/pack/pack-9d35929d4c04f4d08ea7d8d652adbf64e577350f.keep': Filename too long
fatal: fetch-pack: invalid index-pack output

Would you like to retry cloning ?

### Log files

Cloning into 'C:\Users\ljun2\OneDrive - Intel Corporation\Documents\GitHub\containers.docker.p4language.p4verification\sources\containers.docker.p4language.p4verification\s\containers.docker.p4language.p4verification'...
remote: Enumerating objects: 359, done.        
remote: Counting objects: 100% (110/110), done.        
remote: Compressing objects: 100% (44/44), done.        
remote: Total 359 (delta 78), reused 85 (delta 66), pack-reused 249        
Receiving objects: 100% (359/359), 65.54 KiB | 684.00 KiB/s, done.
Resolving deltas: 100% (213/213), done.
fatal: cannot write keep file 'C:/Users/ljun2/OneDrive - Intel Corporation/Documents/GitHub/containers.docker.p4language.p4verification/sources/containers.docker.p4language.p4verification/s/containers.docker.p4language.p4verification/.git/objects/pack/pack-9d35929d4c04f4d08ea7d8d652adbf64e577350f.keep': Filename too long
fatal: fetch-pack: invalid index-pack output

Would you like to retry cloning ?

### Screenshots

Cloning into 'C:\Users\ljun2\OneDrive - Intel Corporation\Documents\GitHub\containers.docker.p4language.p4verification\sources\containers.docker.p4language.p4verification\s\containers.docker.p4language.p4verification'...
remote: Enumerating objects: 359, done.        
remote: Counting objects: 100% (110/110), done.        
remote: Compressing objects: 100% (44/44), done.        
remote: Total 359 (delta 78), reused 85 (delta 66), pack-reused 249        
Receiving objects: 100% (359/359), 65.54 KiB | 684.00 KiB/s, done.
Resolving deltas: 100% (213/213), done.
fatal: cannot write keep file 'C:/Users/ljun2/OneDrive - Intel Corporation/Documents/GitHub/containers.docker.p4language.p4verification/sources/containers.docker.p4language.p4verification/s/containers.docker.p4language.p4verification/.git/objects/pack/pack-9d35929d4c04f4d08ea7d8d652adbf64e577350f.keep': Filename too long
fatal: fetch-pack: invalid index-pack output

Would you like to retry cloning ?

**Comment by steveward** [comment]
@208yunyao thanks for the issue. You should be able to resolve this by running the following command:

`git config --global core.longpaths true`

This will allow you to bypass the Windows limit of 260 charachters. I'm going to close this out, but let me know if you have any further problems.
