### ISSUE TITLE
Why command execution doesn't pending there in some scenarios?

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#15618]
### The problem

When binary file locked(opened) in local worktree, and then pull the file, the pull command will stop and waiting user input as below:
![image](https://user-images.githubusercontent.com/5396286/201615562-d6390622-0785-4311-a857-b59e2e66a455.png)

But in GitHub Desktop, it doesn't work like that, it finished the execution directly with answer `no`. Does anyone know why it doesn't stop there? and how to let it stop and accept input when the git command asks user input? Which means make the git command execution interactively when it asks user input. Thanks in advance.

### Release version

3.1.2

### Operating system

Windows 10

**Comment by niik** [comment]
Hey @TerryChan, I'm afraid you'd have to implement that for each command individually. Desktop runs all of its command non-interactively as there are way too many scenarios where Git could pause for input that we're not able to handle.
