### ISSUE TITLE
fatal: unable to access 'https://github.com/[GithubOrgName]/[RepoName].git/': .netrc parser error

### ISSUE THREAD

**Issue by kellyrmartin** [desktop/desktop#15612]
### The problem

Anytime I try and push or pull changes I get the following

fatal: unable to access 'https://github.com/[GithubOrgName]/[RepoName].git/': .netrc parser error

### Release version

3.1.2

### Operating system

macOS Ventura

### Steps to reproduce the behavior

1. Click Fetch origin

### Log files

[2022-11-12.desktop.production.log](https://github.com/desktop/desktop/files/9995918/2022-11-12.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/3556384/201494719-ffc2dc52-90e3-4772-9c9b-0c8bcb88b8ab.png)

**Comment by steveward** [comment]
Thanks for the report @kellyrmartin. It looks like something in your `.netrc` file is causing issues with operations. Have you configured credentials for GitHub in your `.netrc` file?

**Comment by kellyrmartin** [comment]
I cleared out the contents of my .netrc file and that seems to have corrected it. Thank you

**Comment by steveward** [comment]
Glad to hear that go things working!
