### ISSUE TITLE
Open In Specific Line By VSCode In Diff Page

### ISSUE THREAD

**Issue by mefengl** [desktop/desktop#15622]
### The feature request

In the diff page, add a right-click option that can jump to a specific line.

### Proposed solution

Much more convenient

### Additional context

https://stackoverflow.com/questions/39453951/open-file-at-specific-line-in-vscode
`Code.exe --goto "C:\file path\filename.txt:450:11" `
a command like this may achieve this function.

**Comment by niik** [comment]
@mefengl Thanks for the suggestion! I think this would be a great addition though we would need to find a solution that's more generic than just VS Code. I think some way for us to indicate which of our supported external editors has the capability to jump to a line would be ideal. I'm going to close this in favor of https://github.com/desktop/desktop/issues/14476 and add a copy of my reply there.
