### ISSUE TITLE
Double Click Jump To The File

### ISSUE THREAD

**Issue by mefengl** [desktop/desktop#15621]
### The feature request

instead of right-clicking in a file, then clicking on  `Open in VSCode`, add an option that makes double-click do it directly.

### Proposed solution

Much more convenient

**Comment by niik** [comment]
Hey @mefengl, thanks for the suggestion. I'm not convinced that adding a default double-click action is the way to go but there's certainly a fair bit of interest as this feature has been suggested in the past https://github.com/desktop/desktop/issues/1542, https://github.com/desktop/desktop/issues/2620, https://github.com/desktop/desktop/issues/3276 https://github.com/desktop/desktop/issues/4019. Not including that feature in the electron version of Desktop was a conscious decision, see https://github.com/desktop/desktop/issues/2620#issuecomment-328665777

> We made the conscious decision not to add it back in the rewrite... If I recall, and it's been a while, our thinking was mainly that it was a difference in behavior between Mac and Windows which wasn't a high enough priority to special case for just Mac.

I'm going to roll this into #2620, please indicate your support for this feature by adding a 👍 reaction to that issue. The fact that #2620 is closed does not mean we will not consider it, only that we're not considering it at this moment.
