### ISSUE TITLE
git graph

### ISSUE THREAD

**Issue by unrulife** [desktop/desktop#15623]
### The feature request

Add the git graph to github desktop like sourctree or vscode, and then the github desktop
is prefect!

### Proposed solution

The git graph will make it more intuitive for users to view the version history.

**Comment by niik** [comment]
Hey, thanks for reaching out! This looks very similar to the request in https://github.com/desktop/desktop/issues/9452 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date with any development happening in that area.

**Comment by unrulife** [comment]
Got it. Thanks.
