### ISSUE TITLE
mac GitHub Clienet, Pushing to origin hangs sometimes

### ISSUE THREAD

**Issue by RainerPri** [desktop/desktop#15637]
### The problem

Sometimes if i push a changed project to Github, the Push did not finished!
If i close the GithibCleient and Fetch from origin, there are noch changes.
So it looks that the Push was sucessfull.

### Release version

3.1.2

### Operating system

Ventura 13.0.1

### Screenshots

<img width="1171" alt="Bildschirm­foto 2022-11-17 um 16 33 51" src="https://user-images.githubusercontent.com/23703667/202489271-3495a9f8-0253-48f6-ab37-0816a7a83763.png">

**Comment by RainerPri** [comment]
I Tryed to close GithubClient.
After a restart the project was not published.
i pused again and now it can push the project complete.

**Comment by steveward** [comment]
Glad to hear things are working again @RainerPri. If you run into this again it would be helpful if you could share the log file to give us some more information about the issue. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.

I'm going to close this out, but let us know if you have any further problems.

**Comment by RainerPri** [comment]
Hello @steveward attached the logfile.

Thank you and BR from Austria
Rainer

[2022-11-17.desktop.production.log](https://github.com/desktop/desktop/files/10033452/2022-11-17.desktop.production.log)
