### ISSUE TITLE
Creating a Commit takes several minutes to finish or sometimes never completes

### ISSUE THREAD

**Issue by bgpedersen** [desktop/desktop#15631]
### The problem

Creating a commit, gets stuck at "Comitting ...". In the message under, it looks like the commit was made, but the UI is not updated and the program is stuck in what looks like it is still comitting. Closing the program helps, but the problem reappears soon after again.

### Release version

Version 3.1.2 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. make file changes
2. go to "Gihub Desktop"
3. write a commit description
4. press commit

### Log files

[2022-11-16.desktop.production.log](https://github.com/desktop/desktop/files/10021048/2022-11-16.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/3582953/202165021-bd4eb675-ec4d-4531-a1a1-df1ccb05d378.png)

**Comment by steveward** [comment]
Thanks for the report @bgpedersen. I can see instances where committing is taking a long time:

```
2022-11-16T09:44:21.344Z - info: [ui] [Timing] Action 'create commit' for 'DineroRegnskab/dinero-web-2.0' took 1113.848s
```

A few questions to help narrow this down:

- Are there any pre-commit hooks running that could be causing this? 
- Are you running any antivirus/security software that could be slowing down Git operations? 
- Have you tried committing via the command line to see if you encounter similar performance issues there?

**Comment by bgpedersen** [comment]
@steveward Thanks for getting back to me.

I want to say, that Github Desktop has worked flawlessly for more than a year, it just started happening a few days ago. My computer configurations have not changed.

- There is no pre-commit hooks
- I don't run any virus or security software. We are running on a VPN, but that never caused problems before and only give access to company specific things, and don't restrict anything.
- comitting (or pulling/fetching) via git command line works perfectly fine

**Comment by bgpedersen** [comment]
@steveward Github Desktop seems to be working fine again now, already for several days. Maybe it was not connected to Github Desktop, but Git itself, hard to say. But i just wanted to let you know, so maybe the issue should be closed.

**Comment by steveward** [comment]
Glad to hear things are working now! I'll close this out.
