### ISSUE TITLE
i cant pull, please help -  getting odd error

### ISSUE THREAD

**Issue by seanHayden** [desktop/desktop#15633]
### The problem

please advice based on the error, i cant pull form my repo, tried re installing the repo, but that fails too

### Release version

git hub desktop

### Operating system

pc

### Screenshots

![image](https://user-images.githubusercontent.com/41623998/202193212-673e0b9d-0b6c-40b7-aa8d-f2a595e75da7.png)

**Comment by steveward** [comment]
@seanHayden thanks for the issue. Unfortunately this error can happen for a number of reasons, like a slow connection or pulling a large number of changes causing a timeout. 

How large is the repository you are trying to fetch from? Are you on a reliable connection, and if possible are you able to try a different network to see if that succeeds? You can also test your connection speed to GitHub at https://github-debug.com/.
