### ISSUE TITLE
You have a REALLY easy opportunity to help educate the Git world about Git Commands. 

### ISSUE THREAD

**Issue by ap-coder** [desktop/desktop#15634]
### The feature request

I have been working with git for some time now and after managing and setting up many different cicd/ pipelines and development environments I have come to one really big conclusion when using git and helping others fix the problems they run into.  **IT IS ALOT OF COMMANDS TO MEMORIZE AND TRAIN YOUR SELF ON WHILE AT THE SAME TIME KEEPING UP WITH GIT'S NEW CHANGES.**

Sorry for the caps. Just wanted to be direct about how much this can help the git users all over the world with very little work on your part. I hope you agree with me and decide to implement the enhancement to your awesome tool. 

### Proposed solution

I propose you add a command output view. Similar to SublimeText Ide with the command flag turned on.  This way instead of your program just doing all the work for everyone. We can decide to actually learn what your awesome client is running to make them happen.  

I do not think there is a program out there that has the ability to help people learn git commands, flow, and best of all debugging like your program has the opportunity to do. 

This would help people new to git learn how to run there work flow without wiping out or conflicting with everyone else because they used the wrong commend.  You could have a new window open up or like developer tools in browsers let it be docked or undock to separate window.   Better yet have a third tab next  to current ones you already have.

>  Changes   |   History   | { Commands | Console }
(see image in next section for example mockup)

**If I was going to create this I would have Boolean setting to control the output to the console.**

**CONSOLE OUTPUT DETAIL:**
* Commands Only 
* Commands & Error responses
* Full Output. 

Anyway i hope you see the advantage to this. You would become the most used tool in the world almost overnight.  Maybe if you decide to add this very helpful idea into your Awesome Client you can include me.  I am a software developer myself and would be excited to work on something that could help so many people.  

I understand there are people who know everything but in my experience with operating systems, and software updates such as git improvements it would be AWESOME to have a tool in place to learn the new updates and changes while seeing them in action. 

> Let me know your thoughts on my idea of course.  Hope you agree. 

PS. If you are not aware of the sublime command to output its commands while they run in real time you can download the free version of SublimeText and open console under view.  In the console input enter the command **sublime.log_commands(True)** and you can see what I am speaking about that is similar.   This of course is not as used and likes as git but if shows python processes pretty well. 

More Sublime Command Flags You Can Try:
* sublime.log_input(True); 
* sublime.log_commands(True); 
* sublime.log_result_regex(True);

For all I know you already have it doing something similar so your developers can verify what it is actually running and if this is the case can you please share it with the rest of us as we would love to have it available. 

### Additional context

![gitconsole](https://user-images.githubusercontent.com/58571584/202313419-7daf7b05-ebea-4766-9f43-4da953b3ef70.jpg)

**Comment by steveward** [comment]
Thanks for the feedback @ap-coder! This has been something that has been discussed in the past in https://github.com/desktop/desktop/issues/1570, but at this time we don't have any plans to implement this type of feature into GitHub Desktop. If you are interested in seeing more of what's going behind the scenes on you can go to `View` > `Toggle Developer Tools` > `Console`. This will show a running output of what the app is doing.

There are also applications that have been built specifically with the goal of teaching how to use Git from the command line. The [Git-it](https://github.com/jlord/git-it-electron) project is a great example.

I'm going to close this out, but I'll reference this issue in #1570 as well. You can follow along there for any potential updates about this.
