### ISSUE TITLE
Desktop doesn't automatically refresh for a newline change. I have to select another file and back to the same file for checking that change

### ISSUE THREAD

**Issue by ThePiyushAggarwal** [desktop/desktop#15638]
### The problem

The red icon at the end of the file doesn't get changed when I delete or add the newline from the end of the file.
I have to select another file and then come back to this file to check if there are any changes.

![image](https://user-images.githubusercontent.com/27003616/202500465-48a9fdec-c62e-4a24-bf90-5aa00f5c891d.png)

### Release version

3.1.2

### Operating system

Windows 10

**Comment by Mina012015** [comment]
> ### المشكلة
> لا يتم تغيير الرمز الأحمر في نهاية الملف عندما أحذف أو أضف السطر الجديد من نهاية الملف. لا بد لي من تحديد ملف آخر ثم العودة إلى هذا الملف للتحقق مما إذا كانت هناك أية تغييرات.
> 
> ![صورة](https://user-images.githubusercontent.com/27003616/202500465-48a9fdec-c62e-4a24-bf90-5aa00f5c891d.png)
> 
> ### الإصدار
> 3.1.2
> 
> ### نظام التشغيل
> نظام التشغيل Windows 10
> 
> ### خطوات إعادة إنتاج السلوك
> _لا يوجد رد_
> 
> ### ملفات الدخول
> _لا يوجد رد_
> 
> ### لقطات
> _لا يوجد رد_
> 
> ### سياق إضافي
> _لا يوجد رد_

**Comment by Mina012015** [comment]
اريد المساعده
