### ISSUE TITLE
Global option in Preferences to ignore .DS_Store

### ISSUE THREAD

**Issue by chadagreene** [desktop/desktop#15644]
### The feature request

Macs create invisible files named [`.DS_Store`](https://en.wikipedia.org/wiki/.DS_Store) in every folder, and these files are automatically updated on an ongoing basis. 

The problem: The `.DS_Store` files are rarely, if ever, useful to anyone. They primarily exist as clutter in every folder of every repo created by Mac users, unless they're dealt with manually by creating another clutter file called `.gitignore`. I suspect there are not many cases where `.DS_Store` files need to be archived or continually updated on GitHub. [From the looks of it, most people don't want `.DS_Store` files cluttering their repos](https://www.google.com/search?client=firefox-b-1-d&q=github+.ds_store), yet no clear, straightforward solution exists to deal with them elegantly. 

### Proposed solution

Create a global option in the GitHub Desktop Preferences menu to ignore `.DS_Store` files. Ideally this would be turned on by default. 

### Additional context

Here's an example of a repo in which I haven't changed any files, but GitHub Desktop think I need to push changes to origin. The only changes here are the automatic updates that have been made to the invisible `.DS_Store` files. 

<img width="498" alt="Screen Shot 2022-11-18 at 11 47 26 AM" src="https://user-images.githubusercontent.com/15901019/202780077-5cc2e4e9-3caa-4080-b547-6f5811655176.png">

**Comment by steveward** [comment]
Thanks for the issue @chadagreene. Generally we push away from adding niche options like this, especially if they can already be configured in GitHub Desktop. Right-clicking and choosing `Ignore file` is the best current solution on a per-repository basis, and since it's something that only needs to be initially done once I feel that it isn't too big of a pain point for many users unless they have already accidentally committed the file (and in that case the menu item wouldn't help either).

Another good option is to use the global .gitignore to ignore specific files across all repositories on your local machine. See [this help document](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer) for more information about setting that up.

**Comment by chadagreene** [comment]
I wholeheartedly disagree, @steveward! It's hardly a niche issue, as it affects literally every Mac user. I suspect it's a far more niche group of users who _want_ to perpetually update the `.DS_Store` files in their repos. 

To give a sense of the scale of the problem, I've got dozens of repos, and each one contains multiple folders and subfolders and subsubfolders. This means hundreds of `.DS_Store` files to manually click through and manually set the rules for. It seems like such a simple and humane fix to let users ignore hidden files by default.

**Comment by steveward** [comment]
Thanks for the feedback. I don't disagree it's something users encounter, but it is quickly solvable by the steps I shared above. I did take a look through previous issues as well and this isn't something that we've seen reported, which is generally what we use to gauge specific changes/improvements like this. 

> This means hundreds of .DS_Store files to manually click through and manually set the rules for. It seems like such a simple and humane fix to let users ignore hidden files by defaul

You shouldn't need to do this if you use the 'Ignore all `.DS_store` Files' option from the context menu. The global `.gitignore` option I mentioned above will also negate this for all repositories on your machine.

**Comment by chadagreene** [comment]
@steveward Thanks for the suggestion, but I don't see an option to "Ignore all `.DS_store` Files". If this option is available on Mac, then it sounds like a perfect solution, and it would be great if it were discoverable. Or perhaps I'm missing something very obvious? 

<img width="500" alt="Screen Shot 2022-11-28 at 2 33 48 PM" src="https://user-images.githubusercontent.com/15901019/204387001-0abd0095-d25f-4893-92c8-ecc2c542115d.png">

**Comment by steveward** [comment]
It looks like there may be an issue with the `Ignore All` functionality for dotfiles -- you should see it on other files. I'll investigate what's causing that and open an issue, but you can also workaround that by directly editing the `.gitignore` from `Repository` > `Repository Settings` > `Ignored Files`.

**Comment by chadagreene** [comment]
Thanks @steveward, I'll give that a shot!

**Comment by cblc** [comment]
I wish to vote up for @chadagreene 's suggestion. I'm a developer for multiplatform code, but my main development machines are Macs, from which I either crosscompile to other OSs, or build from virtual machines. I had never used GitHub Desktop before, I just installed it today. The first thing I did was to clone a repository. This was fine. Then, the second thing I did was navigate in the cloned dir. Then GitHub Desktop told me my local dir had changes (the .DS_Store files), and I thought "hey!, they didn't disable .DS_Store syncing by default!, let's see where can we disable that"... just to find that there's no setting, and that the "Ignore All" option doesn't work for .DS_Store. So, I just want to reinforce @chadagreene comment that this is not niche at all: in fact it was the second thing I wanted to do when I used GitHub Desktop for the first time.

**Comment by cblc** [comment]
Anyway, thinking about it twice, editing **.gitignore**, is perhaps better practice, so that we understand what's going on rather than having a blackbox app that does things we don't know.

**Comment by sveinbjornpalsson** [comment]
the right-click ignore of .ds_store if you do it to the file in the root first. Then all the others follow.

**Comment by BenjaminGittins** [comment]
adding .DS_Store does not filter the file out at all.  This issue maybe in part related to Visual Studio Code's gitlab plugin. This needs addressing. ---> in the interim this may help people: https://www.askwoody.com/forums/topic/how-to-disable-the-creation-of-ds_store-files-on-mac/

**Comment by BenjaminGittins** [comment]
This is a serious problem, that requires someone that uses mac, to actually fix.  This remains an issue with the latest version of GitLab.

**Comment by SermetPekin** [comment]
I had the same problem and I think that this two step process solves the problem until a permanent solution comes to 
desktop at least. 

STEP 1 (adding .DS_Store to `.gitignore` file)
> .gitignore file 
``` {.gitignore file }
.DS_Store
```
> terminal

``` {cmd}
git add .gitignore
git commit -m "Add .DS_Store to .gitignore"
```
STEP 2 (deleting all .DS_Store files from terminal)
> terminal
``` cmd
find . -name .DS_Store -print0 | xargs -0 git rm --ignore-unmatch --cached
git commit -m "Remove all annoying  .DS_Store files from repo :)"
git push

```

**Comment by RyanWendell** [comment]
I hope we see an update addressing this. 

Currently the only solutions are:

1. add to .gitignore but then deal with folders not properly deleting when switching branches (it leaves behind empty folders since .DS_Store is inside and wasn't removed by git)
2. Leave it and deal with it constantly wanting to commit the changes to .DS_Store every few seconds
3. Turn off .DS_Store from being generated with unknown consequences to the rest of macOS

All not great choices. 

When I am working in something like VS Code it's super annoying to have these empty folders left behind when switching branches. 

I guess the best work around could be to create a hook that searches and then removes the .DS_Store files but... really just seems like something that should be a default at this point.

**Comment by jjimenez1984** [comment]
I support the original request.  Giving GitHub Desktop the option of ignoring these files altogether so that they are never suggested as a file that would be added to the repository is the most elegant solution and will literally save thousands of hours of development time for users.

**Comment by arthurauffray** [comment]
I support this!

**Comment by bhanu951** [comment]
```
# Quick and easy one line command to setup a global .gitignore file and ignore macOS .DS_store files globally
git config --global core.excludesfile "~/.gitignore" &&  echo .DS_Store >> ~/.gitignore
```

source [gist](https://gist.github.com/lpheller/5d977e0108464f03c42d46b2b0cd64ca)
