### ISSUE TITLE
[macos]I can't see any ui in my github desktop,Is anyone seen like this?

### ISSUE THREAD

**Issue by leemanvin** [desktop/desktop#15647]
My desktop app can't use, please help! 
![image](https://user-images.githubusercontent.com/82501944/202826959-1b2c78da-d52b-458d-bce2-8fa52ee50f45.png)
In this image, I can't see any button or any app ui , i don't know what's going on.
My macOS is  Monterey 12.6, i download app from here:https://desktop.github.com, Did I install it the wrong way? But I've installed it a few times and it's been like this.

**Comment by Jimimaku** [comment]
> Meine Desktop-App kann nicht verwendet werden, bitte helfen Sie! ![image](https://user-images.githubusercontent.com/82501944/202826959-1b2c78da-d52b-458d-bce2-8fa52ee50f45.png)In diesem Bild kann ich keine Schaltfläche oder App-Benutzeroberfläche sehen, ich weiß nicht, was los ist. Mein macOS ist Monterey 12.6, ich lade die App von hier herunter: https://desktop.github.com, habe ich es falsch installiert? Aber ich habe es ein paar Mal installiert und es war so.

**Comment by steveward** [comment]
Sorry for the trouble @leemanvin, can you try resetting GitHub Desktop by following these steps?

1. Close GitHub Desktop
2. Delete all of the files under `~/Library/Application Support/GitHub Desktop/`
3. Restart GitHub Desktop

Let me know if that does not get things working for you.
