### ISSUE TITLE
Password Not Working

### ISSUE THREAD

**Issue by Bezeball** [desktop/desktop#15652]
### The problem

Bitbucket password not working. I'm already using a dedicated password in Bitbucket for the GitHub Desktop app.

### Release version

Version 3.1.2 (x64)

### Operating system

Windows 10

**Comment by steveward** [comment]
Thanks for the issue @Bezeball. Have you generated an authentication token for GitHub Desktop to use? Is it possible the token expired? See [this guide](https://github.com/desktop/desktop/blob/development/docs/integrations/bitbucket.md) for reference on how to set that up.

**Comment by Bezeball** [comment]
I solved it. I had to delete the passwords GitHub Desktop had saved in some place in Windows where it saved them. After that it worked.

**Comment by steveward** [comment]
Glad to hear things are working now!
