### ISSUE TITLE
Add Sync button

### ISSUE THREAD

**Issue by stevemoser** [desktop/desktop#1565]
### Description

GitHub for Mac simplified fetching/pulling/syncing with a Sync button. I would like to see this functionality come to GitHub Desktop.

**Comment by joshaber** [comment]
We made the conscious decision to 👢 the Sync button this time around. While it _did_ simplify some things, it also caused a lot of confusion.

The current button should do what you want most of the time. Are there cases where it falls short?

**Comment by tnrich** [comment]
I really miss the sync button too (or actually the ability to hit Cmd-S and have everything sync). Is there some way we can allow users to enable the functionality, but not have it be the default?

Thanks for the cool new tool!

**Comment by niik** [comment]
For those interested in our reasoning and our thinking when developing the new flow for staying up to date there's [a write up in one of our early design exploration issues](https://github.com/desktop/desktop/issues/549#user-content-magic-sync-button)

**Comment by tskarman** [comment]
Same here, I am using "GitHub for Windows" for exactly two things:

- pressing "Alt +S" to quickly sync my main repo.
- quickly clone GitHub repositories.

I hope I'll find more use cases with the new client, but quickly pressing "Alt + S" I would really miss.

**Comment by stevemoser** [comment]
Mostly I wanted an easy setup for non-technical people (GitHub for poets) to edit their GitHub pages site offline. Many times they have few or no other contributors. So telling them to hit CMD+S to save like they do in other apps is easier than telling them to shift-CMD-P (to pull changes they might have made on the site) then CMD-P. Thanks for the link to the discussion. I forgot to search for closed issues before creating this issue.

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by joshaber** [comment]
@j-f1 pointed out in https://github.com/desktop/desktop/issues/2751#issuecomment-329966649:

>The only difference AFAIK is that if your local branch is both ahead of and behind the remote, it will pull and merge on the first click, and you have to click again to push.

I wonder if we should change that so that clicking the button always tries to catch you all the way up?

**Comment by j-f1** [comment]
> I wonder if we should change that so that clicking the button always tries to catch you all the way up?

From #549:

> If you’re both ahead and behind, we’ll make you do a pull before giving you the ability to push. This is similar to what Sync does today except we will do a pull and merge but we will **not automatically push that merge commit**. Instead **we'll leave that action to the user so that we'll never push a result that they're not comfortable with**. We might consider updating the button text in this state to something like 'Pull and merge'.

(emphasis mine)

**Comment by ethan-zhang-rs** [comment]
Personly I really hate the new pull/push button in the latest version, a freezing issue on this button occurs quite often. I had to roll back to ver.223 to get the sync button back to make things just work fine.

**Comment by hyiltiz** [comment]
If what @billygriffin said really means `Sync` button is officially never coming back, then I'll start considering to answer `Just download from Github` when people say what is a good "git software" to use.

**Comment by billygriffin** [comment]
@hyiltiz We hope you will! 😄 We definitely want to keep things as intuitive as possible and remove points of potential pain and frustration at every opportunity, so it's always a balancing act, but we're confident in this decision at present.

**Comment by devinrhode2** [comment]
I am trying to figure out exactly what the "Sync" button used to do and create a simple command line alias.. if it's not too complicated. Does anyone know what exactly it used to do?

**Comment by julien-c** [comment]
`git pull --rebase && git push`

**Comment by saschanaz** [comment]
I'd say just `git pull && git push`. The pull behavior can just follow the configured default. (`git config pull.rebase`)

**Comment by DanJBower** [comment]
I really like the sync feature which is present in other IDEs such as VS Code but understand why it isn't in GitHub Desktop at the minute.

However, couldn't an option be added so that the user can choose to use a sync button instead of the more granular button if they desire too?

**Comment by dannybeckett** [comment]
I'd also like a Sync button for: Fetch, Pull, Push
