### ISSUE TITLE
Show all external editors as Open In options in menu bar

### ISSUE THREAD

**Issue by wiverson** [desktop/desktop#15662]
### The feature request

Show all of the available editors in the Repository menu. Setting the default in the preferences sets the default editor for the hot key.

### Proposed solution

Many users use multiple editors (e.g. JetBrains products, Visual Studio Code, the upcoming Fleet, etc) depending on their needs. It would be nice to be able to open a repo in any of the available editors from the menu bar.

### Additional context

This seems like a relatively straight-forward way to deal with users using multiple editors for various projects. A more technically accurate but much more complex implementation would be to add code to determine the IDE in use for the project by introspecting the files stored, but this is both more complicated and still doesn't address users who had different preferences (e.g. repo uses VSCode but user prefers WebStorm).

**Comment by steveward** [comment]
Thanks for the feedback @wiverson. I'm going to add this to https://github.com/desktop/desktop/issues/12195 where we are tracking the support for per-repository editor selection. You can follow along there for updates.
