### ISSUE TITLE
Github Desktop not connecting to repo

### ISSUE THREAD

**Issue by Andrew-Furr** [desktop/desktop#15667]
### The problem

While attempting to Push a branch from my local machine to Github, I'm being told the remote was disconnected and to check my internet connection. However, everything seems fine, and the rest of Desktop is working properly. I've tried closing and re-opening to no avail. Is there something else I can do?

### Release version

3.1.2

### Operating system

Windows 10 Enterprise

**Comment by Andrew-Furr** [comment]
Restarting computer helped. Was trying to avoid that, but it is what it is.

**Comment by Nathaniel97299** [comment]
Find out how to access the NCIC database
