### ISSUE TITLE
Want to support grouping

### ISSUE THREAD

**Issue by SouthXia** [desktop/desktop#15666]
### The feature request

I want to have a group that can be customized and push by group. See the figure above for details.
![image](https://user-images.githubusercontent.com/49887877/203296128-7370d71a-1741-48e5-9eff-84a69fc6280e.png)

### Proposed solution

**Hope to support it**

### Additional context

![image](https://user-images.githubusercontent.com/49887877/203296128-7370d71a-1741-48e5-9eff-84a69fc6280e.png)

**Comment by steveward** [comment]
Thanks for the feedback @SouthXia. Pushing by group isn't something that is supported in GitHub Desktop, and isn't likely something that we'll implement at this time. You can use the command line to push a subset of commits. Here's how to do that:

`git push origin commit-SHA:branch`

So if you have three commits A (4d3bf9) - B (e55b5f) - C (c109e0) and wanted to push A and B to your `master` branch you would run this command:

`git push origin e55b5f:master`

I hope that helps!

**Comment by SouthXia** [comment]
Well, although this is not what I want
