### ISSUE TITLE
Suddenly unable to access WSL2 repos in Github Desktop

### ISSUE THREAD

**Issue by nfsa-ewan** [desktop/desktop#15664]
### The problem

I have recently become unable to add or access WSL2 or local desktop repos using Github Desktop. 

Github Desktop Version 3.1.2 (x64)

About a month ago our SOEs were updated to Win 10 v22H2 build 19045.2251

Default Distribution: Ubuntu-20.04
Default Version: 2
Windows Subsystem for Linux was last updated on 29/03/2022
WSL automatic updates are on.
Kernel version: 5.10.102.1

If i try to add an existing repo the blue 'Add Repository' button remains greyed out
![image](https://user-images.githubusercontent.com/50893856/203184080-e04ec40e-3b3c-49e8-9469-f92168d874f9.png)

When i try to create a new repo i get an error: 
![image](https://user-images.githubusercontent.com/50893856/203184148-5d8bb7a3-e8bf-4502-8a94-222243d4623a.png)

![image](https://user-images.githubusercontent.com/50893856/203184172-7f573d0a-1c50-4179-993b-12d330bb350b.png)

I have tried removing github desktop, clearing remaining appdata/local files and reinstalling to no avail. 

I haven't had much luck finding other examples of this issue. Clearly not using the right keywords. 

### Release version

Version 3.1.2 (x64)

### Operating system

Win 10

**Comment by nfsa-ewan** [comment]
I get the same ConfigValueinPath error when trying to add a new repo to my C:\Users\user\Documents\ folder

**Comment by niik** [comment]
Hey @nfsa-ewan, thanks for reaching out.  Is this happening on multiple machines? Are you running any specific antivirus/security software that could be interfering with updates to GitHub Desktop? We've seen this error pop up (https://github.com/desktop/desktop/issues/15031) when users run strict security software and/or permissions which break the installation. 

Echoing the suggestion in that thread I would recommend deleting the `%LocalAppData%\GitHubDesktop` directory and reinstalling to see if that helps at all. If you're able to temporarily disable any antivirus software I would recommend doing that as well, although I understand that is not always possible.
