### ISSUE TITLE
Cannot see window border for resizing purposes

### ISSUE THREAD

**Issue by dbeavon** [desktop/desktop#15672]
### The problem

When using the desktop, the window border is not visible.  Notice in the screenshot (lower right) that I'm hovering my mouse randomly over whitespace to try and find the border of this application window:

![image](https://user-images.githubusercontent.com/21175830/203651584-66707cfc-acb7-42c4-8fe4-c8a122254af3.png)

This is not how a windows application should work.  By definition, windows have window frames.

### Release version

Version 3.1.2

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Run github desktop on windows with light theme and no fancy window effects (shadows etc)

### Log files

n/a

### Screenshots

See problem statement above

**Comment by JannesMeyer** [comment]
I also have this problem, but I think it's already tracked in #1585
