### ISSUE TITLE
Unified diff doesn't support middle mouse scroll

### ISSUE THREAD

**Issue by sybrew** [desktop/desktop#15675]
### The problem

In unified diff display mode, scrolling on Windows via the middle mouse won't scroll all the way.

### Release version

3.1.2

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Make large changes;
2. Set Diff mode to Unified;
3. Try scrolling diff using the middle mouse button;
4. Scroll stops after only a short distance.

**Comment by sergiou87** [comment]
Hey @sybrew! 👋 

Thank you for your report ❤️  I think this has been fixed in beta thanks to #15444 , and will be deployed to production builds when we're confident about that change.

If you want to try the beta now, you can download it from https://desktop.github.com/beta
