### ISSUE TITLE
Unable to upload large file using github desktop

### ISSUE THREAD

**Issue by U009DAM** [desktop/desktop#15678]
i'm encountering below error when uploading large file using github desktop

LFS: Put "https://github-cloud.s3.amazonaws.com/alambic/media/206871534/d5/99/d5997375706a3fcffc17fbfbdf4045d4dcb24039bb11c60b29c24835df15006e?actor_id=43374074&key_id=0&repo_id=176473875": read tcp 127.0.0.1:59913->3.5.20.19:443: i/o timeout
error: failed to push some refs to 'https://github.com/****/*******.git'

**Comment by DestanyHope9780** [comment]
> i'm encountering below error when uploading large file using github desktop
> 
> LFS: Put "https://github-cloud.s3.amazonaws.com/alambic/media/206871534/d5/99/d5997375706a3fcffc17fbfbdf4045d4dcb24039bb11c60b29c24835df15006e?actor_id=43374074&key_id=0&repo_id=176473875": read tcp 127.0.0.1:59913->3.5.20.19:443: i/o timeout
> error: failed to push some refs to 'https://github.com/****/*******.git'

![Screenshot_20221124-093450.png](https://user-images.githubusercontent.com/118973031/203821561-0dc50faa-cb13-4b80-bd4f-e9193adb5c28.png)

**Comment by tsvetilian-ty** [comment]
@U009DAM 👋 
You could try `git config lfs.activitytimeout 60` to increase the time the client will wait for the next TCP read or write. You could also check https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-config.adoc for more information on timeout configurations
