### ISSUE TITLE
/usr/bin/env: ‘ruby’: No such file or directory

### ISSUE THREAD

**Issue by anko20094** [desktop/desktop#15677]
### The problem

/usr/bin/env: ‘ruby’: No such file or directory when try:
1.Just commit changes;
2.Change branch;
3.Publish branch

There are a pre-commit hooks that our team uses to check for lint errors before committing.

NodeJS v16.18.1

I've been able to commit changes, push commits on the branch and publish the branch through VScode

### Release version

GitHub Desktop Version 3.0.5-linux1 (x64)

### Operating system

Ubuntu 22.04.1 LTS (kernel 5.15.0-53-generic)

### Screenshots

![2022-11-24_12-59](https://user-images.githubusercontent.com/31440971/203767899-3cec5e81-2b6e-48ba-bdb4-64376affa9ec.png)

**Comment by steveward** [comment]
Thanks for the issue @anko20094. At this time we are unable to provide official support for the Linux fork of GitHub Desktop. I'd recommend searching the issues in https://github.com/shiftkey/desktop to see if there is an existing related issue to this error you are experiencing.
