### ISSUE TITLE
Scan hard drive fro repos and (selectively?) add them

### ISSUE THREAD

**Issue by Kuranes** [desktop/desktop#15674]
### The feature request

Developpers have now terabytes of disk and thus probably a lots of repository lying around, either for work, hobby, investigation
Finding the app so good, I'd like to add all repos to it... but that means a reaaaaaaally long manual process

### Proposed solution

- scan hard drives for .git
- list them all with checkbox and a "select all checkbox"
- all checked are added.

### Additional context

( a .git folder search give me here 3164 folder )

**Comment by steveward** [comment]
Thanks for the feedback @Kuranes, I'll add this to https://github.com/desktop/desktop/issues/1574 where we are tracking this request.
