### ISSUE TITLE
pushing to origin will not be finish

### ISSUE THREAD

**Issue by RainerPri** [desktop/desktop#15685]
### The problem

I will push a project to github but it will not be finish.
Also after more than 10 minutes it is still doing anithing.

In the past a closing from GithubDesktop and Restart help's, but not now.

What can i do to push the project to GitHub.

### Release version

Version 3.1.2 (x64)

### Operating system

Ventura 13.0.1

### Steps to reproduce the behavior

push to origin

### Log files

[2022-11-25.desktop.production.log](https://github.com/desktop/desktop/files/10094351/2022-11-25.desktop.production.log)

### Screenshots

<img width="1203" alt="Bildschirm­foto 2022-11-25 um 17 53 36" src="https://user-images.githubusercontent.com/23703667/204029565-1c1f7fd9-a23c-4055-bc30-c47a1ce43fdd.png">

**Comment by RainerPri** [comment]
I have installed the GithubClient on a paralells Windows10 installation.
With the Windows GithubClient it was possible to push the local repository to Github.

So it looks like a problem in the GithubClient for macOS.

**Comment by steveward** [comment]
@RainerPri thanks for the issue. Unfortunately the log file isn't showing any specific errors related to the push operation in your screenshot, but I do see at least one successful push operation in the log file:

```
2022-11-25T09:48:02.833Z - info: [ui] Executing push: git -c credential.helper= push origin main:main --progress (took 1.436s)
```

Are you able to reproduce this issue across multiple repositories?
