### ISSUE TITLE
> #verified

### ISSUE THREAD

**Issue by michaelshadell25** [desktop/desktop#15684]
> #verified
> #Instagram 
> #account
> #bagde 

@michaelshadell25 ![.trashed-1671677062-repository-open-graph-template.png](https://user-images.githubusercontent.com/115744944/203663588-f87738d6-f129-4a1a-a239-8424dd77ae3a.png)

_Originally posted by @michaelshadell25 in https://github.com/michaelshadell25/automatic-disco/issues/6#issuecomment-1325771057_

**Comment by AHMEDHAMDOUN01000** [comment]
> C

**Comment by AHMEDHAMDOUN01000** [comment]
@AHMEDHAMDOUN01000
