### ISSUE TITLE
Not able to access repo with ssh

### ISSUE THREAD

**Issue by AdhDyslexie** [desktop/desktop#15688]
### The problem

When trying to clone, push or pull to repo with SSH it will just load indefinitely it makes no progress, nor does it give any logs as to why it's doing so. This happens to Repo's on both Bitbucket & GitHub. https seems to work fine though for GitHub.

Clean install did not fix... nor did creating a new SSH key

### Release version

3.1.2

### Operating system

Windows 11 home 22H2

### Steps to reproduce the behavior

Problem seems to be with Windows 11 22H2? 

I managed to reproduce problem on a second device just by updating it to Windows 11 22H2. Second Device **was** on windows 10 22H1 & then 22H2. Could still access Repo's via SSH, then updated to windows 11 22H2, on first attempt same result as main device

### Screenshots

![Repo Problem](https://user-images.githubusercontent.com/58058476/204114738-7f567769-7bbf-4162-b8d0-52e4802047a5.png)
![Repo Problem2](https://user-images.githubusercontent.com/58058476/204114740-ffbe26a0-e911-4298-83a9-05e43b9ff910.png)
![Repo Problem3](https://user-images.githubusercontent.com/58058476/204114741-fb022338-314b-4e89-a0b8-b4cdb073163f.png)

**Comment by AHMEDHAMDOUN01000** [comment]
> ### المشكلة
> عند محاولة استنساخ أو دفع أو سحب الريبو باستخدام SSH ، سيتم تحميله إلى أجل غير مسمى ، ولا يحقق أي تقدم ، ولا يعطي أي سجلات حول سبب قيامه بذلك. يحدث هذا ل Repo على كل من Bitbucket و GitHub. يبدو أن https يعمل بشكل جيد على الرغم من GitHub.
> 
> التثبيت النظيف لم يصلح ... كما لم يتم إنشاء مفتاح SSH جديد
> 
> ### إصدار الإصدار
> 3.1.2
> 
> ### نظام التشغيل
> ويندوز 11 هوم 22H2
> 
> ### خطوات إعادة إنشاء السلوك
> يبدو أن المشكلة مع ويندوز 11 22H2؟
> 
> تمكنت من إعادة إنتاج المشكلة على جهاز ثان فقط عن طريق تحديثه إلى Windows 11 22H2. **كان**الجهاز الثاني على ويندوز 10 22H1 ثم 22H2. لا يزال بإمكانه الوصول إلى ريبو عبر SSH ، ثم تحديثه إلى windows 11 22H2 ، في المحاولة الأولى نفس النتيجة مثل الجهاز الرئيسي
> 
> ### ملفات السجل
> _لا يوجد رد_
> 
> ### لقطات الشاشة
> ![مشكلة الريبو](https://user-images.githubusercontent.com/58058476/204114738-7f567769-7bbf-4162-b8d0-52e4802047a5.png) ![مشكلة الريبو2](https://user-images.githubusercontent.com/58058476/204114740-ffbe26a0-e911-4298-83a9-05e43b9ff910.png) ![مشكلة الريبو3](https://user-images.githubusercontent.com/58058476/204114741-fb022338-314b-4e89-a0b8-b4cdb073163f.png)
> 
> ### سياق إضافي
> _لا يوجد رد_

**Comment by steveward** [comment]
Thanks for the report @AdhDyslexie. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by AdhDyslexie** [comment]
[2022-11-28.desktop.production.log](https://github.com/desktop/desktop/files/10107081/2022-11-28.desktop.production.log)

**Comment by steveward** [comment]
Thanks for sharing that, unfortunately I'm not seeing any SSH specific errors in the log file. Normally if the SSH auth fails it would throw an initial authentication error. Does running `ssh git@github.com` from the command line succeed?

**Comment by AdhDyslexie** [comment]
I got this message back when running the command `ssh git@github.com` in a Git bash terminal.

"PTY allocation request failed on channel 0
Hi AdhDyslexie! You've successfully authenticated, but GitHub does not provide shell access.
Connection to github.com closed." 

Same message on seconds device.

Also, even though I can't ssh clone, pull or push with GitHub desktop I can still do so using Git bash?

**Comment by steveward** [comment]
@AdhDyslexie the `"PTY allocation request failed on channel 0` error could be causing this. What happens if you try and run a `git push` from the command line using SSH?

**Comment by AdhDyslexie** [comment]
Well opening the repo in git bash & using commands `git push` `git pull` & `git fetch` all work fine. That's just what I've been doing in the meantime :). It's just when trying to use GitHub desktop pull, push or fetch that the progress wheel just runs indefinitely 

![image](https://user-images.githubusercontent.com/58058476/208780629-6ed42cd9-357b-47aa-8d70-ba5824ea15dd.png)

**Comment by steveward** [comment]
@AdhDyslexie is this still an issue you're experiencing? Unfortunately the log file isn't showing anything helpful -- it does look like GitHub Desktop is finding your Bitbucket account:

```
2022-11-28T19:57:03.893Z - info: [ui] [AppStore.getAccountForRemoteURL] found generic credentials for 'bitbucket.org' and 'AdhDysleixe'
```

Is HTTPS working for Bitbucket?

**Comment by AdhDyslexie** [comment]
Yes, HTTPS still work's for bitbucket. 

Went & retested everything again to see if problem was still persisting. made sure I was on the latest version of GitHub desktop, still same result. SSH still only working on Git bash. 

made sure I was up to date on windows as well and reinstalled GitHub desktop, problem still persisting.

Log from fresh install 
[2023-02-01.desktop.production.log](https://github.com/desktop/desktop/files/10552992/2023-02-01.desktop.production.log)

**Comment by steveward** [comment]
I'm not seeing any SSH error sin the log, this looks like HTTPS:

```
2023-02-01T03:11:58.514Z - info: [ui] [AppStore.getAccountForRemoteURL] no generic credentials found for 'https://AdhDyslexie@bitbucket.org/Gamingninja5115/clone-test.git'
2023-02-01T03:12:01.346Z - info: [ui] Executing clone: git -c credential.helper= -c init.defaultBranch=main clone --recursive --progress -- https://AdhDyslexie@bitbucket.org/Gamingninja5115/clone-test.git C:\Jonty\CloneTest\Bitbucket\clone-test (took 2.771s)
2023-02-01T03:12:01.347Z - error: [ui] `git -c credential.helper= -c init.defaultBranch=main clone --recursive --progress -- https://AdhDyslexie@bitbucket.org/Gamingninja5115/clone-test.git C:\Jonty\CloneTest\Bitbucket\clone-test` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\Jonty\CloneTest\Bitbucket\clone-test'...
remote: Invalid credentials
fatal: Authentication failed for 'https://bitbucket.org/Gamingninja5115/clone-test.git/'

```

The error is saying `no credentials found`, which would indicate it can't find your Bitbucket token, and is not related to SSH. Are you using the correct clone URL for SSH with Bitbucket?

I also quickly tested working with a Bitbucket repository using SSH, and experienced no issues. If you continue to have problems I'd recommend reaching out to their support team. I'm going to close this out.
