### ISSUE TITLE
Husky pre-commit throws error.

### ISSUE THREAD

**Issue by Dharmang92** [desktop/desktop#15687]
### The problem

While committing to a repo, husky pre-commit hook runs github desktop throws error as below,

"Running pre-commit hook
/usr/bin/env: ‘bash’: No such file or directory
husky - pre-commit hook exited with code 127 (error)"

While committing from terminal such as windows powershell (windows terminal), the hook runs properly with no issues.

### Release version

Version 3.1.2 (x64)

### Operating system

Windows 10 x64

### Steps to reproduce the behavior

1. Commit to <branch-name>.
2. error is reproduced.

**Comment by JosefBredereck** [comment]
Looks like #12562

**Comment by Dharmang92** [comment]
Yes, actually I found this issue #12562 after some searching and I only did one of the solution (not all of them) mentioned by [CameronJThomas](https://github.com/CameronJThomas).

By any chance is it a bug or just the way github desktop works?

**Comment by steveward** [comment]
I'm going to close this in favor of #12562. @Dharmang92 you can follow along there for updates.
