### ISSUE TITLE
VSCodium not detected as External Editor (macOS 12.6)

### ISSUE THREAD

**Issue by JoseGuillermoAraya** [desktop/desktop#15682]
### The problem

VSCodium is not showing in external editor options of Github Desktop

### Release version

3.1.2 (x64)

### Operating system

macOS 12.6

### Screenshots

![Screen Shot 2022-11-25 at 11 59 32](https://user-images.githubusercontent.com/14060312/204011293-b8ca48ed-3be5-40fc-9c8e-f6853b296a38.png)

### Additional context

VSCodium and Github Desktop installed with homebrew.
`defaults read /Applications/VSCodium.app/Contents/Info CFBundleIdentifier` returns `com.vscodium`
`app-path com.vscodium` returns `/Applications/VSCodium.app`

**Comment by AHMEDHAMDOUN01000** [comment]
F

**Comment by AHMEDHAMDOUN01000** [comment]
**  F** @ #

**Comment by AHMEDHAMDOUN01000** [comment]
****

**Comment by steveward** [comment]
Should be fixed by https://github.com/desktop/desktop/pull/15349.
