### ISSUE TITLE
Search Subfolders for repos

### ISSUE THREAD

**Issue by bohrasankalp** [desktop/desktop#15696]
### The feature request

Expecting to select parent folder and application should automatically search the subfolders for the git repos instead to add each repository manually.

### Proposed solution

Expecting to select parent folder and application should automatically search the subfolders for the git repos instead to add each repository manually.

**Comment by tidy-dev** [comment]
This seems along the same lines as https://github.com/desktop/desktop/issues/1574 -> going to add it there.
