### ISSUE TITLE
error: RPC failed; curl 56 Failure when receiving data from the peer 

### ISSUE THREAD

**Issue by tpgpoojak** [desktop/desktop#15707]
### The problem

remote: Enumerating objects: 59140, done.
remote: Counting objects: 100% (450/450), done.
remote: Compressing objects: 100% (219/219), done.
remote: Total 59140 (delta 267), reused 369 (delta 224), pack-reused 58690
Receiving objects: 100% (59140/59140), 202.70 MiB | 4.47 MiB/s, done.
error: RPC failed; curl 56 Failure when receiving data from the peer
Resolving deltas: 100% (44631/44631), done.
Updating files: 100% (578/578), done.

### Release version

using cmd as well not working

### Operating system

Windows 10

**Comment by steveward** [comment]
Thanks for the report @tpgpoojak. Are you on a reliable connection? Have you tried pushing from a different network to see if that succeeds?

It would also be helpful to know if you are behind a firewall or proxy that could be interfering with your connection.

**Comment by tpgpoojak** [comment]
Hi,

thanks for quick reply.

I already tried with different network but same error occur

Also try with CMD still find same issue

As this is my company PC, there is antivirus running and PC is behind a firewall. I cannot change that.

I'm using a proxy and my internet connection is stable.

Previously it was working fine, issue generate from two weeks ago

**Comment by steveward** [comment]
@tpgpoojak are you still experiencing this issue? Unfortunately there is not much we can do about network timeouts from our end. You could try switching to SSH if you are consistently encountering network errors to see if you have better success. If you have questions about setting that up, let me know.
