### ISSUE TITLE
Recent Repositories list

### ISSUE THREAD

**Issue by darrens280** [desktop/desktop#15708]
### The feature request

GitHub Desktop (v3.1.2, on Windows 10)

When selecting Current Repository button in top left corner, the UI shows a list of recently used repositories, however it only shows the last 3 used repos. Please can the ability to customize this list be added, ie: view more than just 3 repos; and perhaps allow user to choose how those recent ones are ordered/sorted. Thanks

### Proposed solution

Improved user experience with this additional customization.

**Comment by tidy-dev** [comment]
@darrens280  Thank you for the suggestion. We are tracking feedback for managing regularly used repositories in #8183. I am going to reference your issue there and close this one in favor if that tracking issue.
