### ISSUE TITLE
Can't fetch origin

### ISSUE THREAD

**Issue by code-zebra-java** [desktop/desktop#15716]
### The problem

Recently I created and deleted a branch in my organization's repository and ever since then I haven't been able to fetch the origin. However, I am the only one experiencing this issue other people in the organization repository haven't been facing this issue.

### Release version

Version 3.1.2 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Open Github desktop
2. Click organizations
3. Open Team 8622
4. Open the repository called 2022 robot
5. Open repository in github desktop
6. click fetch origin

### Log files

[2022-11-28.desktop.production.log](https://github.com/desktop/desktop/files/10147333/2022-11-28.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/73904245/205460882-3499d9df-07b8-416a-a3db-4cbba3a52936.png)

**Comment by steveward** [comment]
@code-zebra-java thanks for the issue -- unfortunately it looks like your local repository is corrupt. You should be able to resolve it by following these steps from the command line to delete the ref:

1. Open the repository in the command line (Repository > Open in <command_line>`
2. Run `rm .git/refs/remotes/origin/temi`
3. Run `git fetch`

Let me know if that does not get things working.

**Comment by code-zebra-java** [comment]
> @code-zebra-java thanks for the issue -- unfortunately it looks like your local repository is corrupt. You should be able to resolve it by following these steps from the command line to delete the ref:
> 
> 1. Open the repository in the command line (Repository > Open in <command_line>`
> 2. Run `rm .git/refs/remotes/origin/temi`
> 3. Run `git fetch`
> 
> Let me know if that does not get things working.

Thank you for earlier, but it doesn't work it says something about rm not being a command
![Screenshot_20221205_114926](https://user-images.githubusercontent.com/73904245/205818640-684286bf-082b-47ed-9c4d-cb733f79de18.png)

**Comment by steveward** [comment]
If you're using the command prompt (and not Git for Windows) then you can run `del` instead of `rm`. Or you can manually navigate to the file and delete it from File Explorer (you will need to enable hidden files/folders on Windows).

**Comment by TetsuyaNarra** [comment]
I checked the logs and it says I am not logged in but when I checked the OPTIONS it says I am logged in, so I logged out then logged in. It's working now.
