### ISSUE TITLE
not able to run 

### ISSUE THREAD

**Issue by ryca01** [desktop/desktop#15717]
### The problem

![image](https://user-images.githubusercontent.com/94887086/205485708-0fd914b4-789d-42e1-a6ae-887cc388a6fb.png)

### Release version

latest

### Operating system

windows 10

### Steps to reproduce the behavior

![image](https://user-images.githubusercontent.com/94887086/205485715-87190e47-61cb-413b-bd66-9b7b7ca416f1.png)

### Log files

![image](https://user-images.githubusercontent.com/94887086/205485713-91332bee-e07f-421d-bac3-c6e106d81fb0.png)

### Screenshots

![image](https://user-images.githubusercontent.com/94887086/205485711-f5de7b32-db0d-41d5-9366-09f26b371325.png)

### Additional context

![image](https://user-images.githubusercontent.com/94887086/205485724-67046e3d-ddd8-4b39-afc8-514ed94f4575.png)

**Comment by steveward** [comment]
@ryca01 can you share details of the specific issue you are having with GitHub Desktop? The screenshot is showing any errors, so any information you can share would be helpful. Thanks.
