### ISSUE TITLE
Can't clone a repository because the name it too long

### ISSUE THREAD

**Issue by mozzila04** [desktop/desktop#15712]
### The problem

Giving an error when trying to clone a repository with a bit longer name

### Release version

3.1.2

### Operating system

Windows 11

### Steps to reproduce the behavior

(At first create a longer repository )
File
Clone repository
Choose that long rep to be cloned
Getting error when cloning

### Screenshots

![image](https://user-images.githubusercontent.com/57716608/205333870-d55cc9fe-3efe-44f6-9ccb-c7af3b9e9950.png)

**Comment by steveward** [comment]
@mozzila04  thanks for the issue. You should be able to resolve this by running the following command:

`git config --global core.longpaths true`

This will allow you to bypass the Windows limit of 260 charachters. I'm going to close this out, but let me know if you have any further problems.
