### ISSUE TITLE
Make repo on organization with desktop

### ISSUE THREAD

**Issue by Akul2010** [desktop/desktop#15722]
Hello, I'm trying to make a repo in my organization with GitHub desktop, but I can't find anything for this. I'm using my personal account, how would I go about this? Thank you!

**Comment by tsvetilian-ty** [comment]
Hey @Akul2010 👋 When you click the "Publish" button on a new repo, you should be able to select an organization.
![publish-to-org](https://user-images.githubusercontent.com/9341546/205679004-c66d59e9-5c3a-4f3d-b399-247523c24dae.gif)

**Comment by Akul2010** [comment]
Thanks! Couldn't find it earlier.
