### ISSUE TITLE
Command failed macOS Ventura M1

### ISSUE THREAD

**Issue by Tioranat** [desktop/desktop#15727]
### The problem

I use Github Desktop on mac for some time. Recently I updated the OS to Ventura, now 13.0.1
When the internal git at .../app/git/bin/git is used it always generate an error *Command failed* popup.

I did the following:

#### Reinstall
I removed and reinstalled the application several times.

#### Other git
I was able to use the default Mac git for commands like status, add and commit on my repositories.

#### Logfiles
I checked the logfiles with no good information in it beside the execution has failed.

#### Manual
I run the command manually and got a <code>bus error</code> always

### Release version

3.1.2. arm64

### Operating system

macOS Ventura 13.0.1

### Steps to reproduce the behavior

1. Installation after deinstallation
2. Use existing setup for repositories
3. Wait for error popups

### Log files

Multiple of these: 

    2022-12-05T08:30:04.548Z - error: [ui] Error performing periodic fetch for '***/***' 
    Error: Command failed: /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git rev-list --left-right --count main...origin/main --

    at ChildProcess.exithandler (node:child_process:408:12)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:526:28)
    at Pipe.<anonymous> (node:net:687:12)

### Additional context

I installed Github Desktop for Ubuntu and could use it with the same repository without issues.

**Comment by niik** [comment]
Hey @Tioranat, thanks for reaching out. Are your repositories on external USB drives or mounted network drives?  We've had some reports (https://github.com/desktop/desktop/issues/15539) of this happening when people upgrade to Ventura and it appears something has changed in Ventura such that Git is failing when operating on a repository on an external drive.

**Comment by Tioranat** [comment]
Hi @niik , thanks for your comment. The source code is located on a Ubuntu machine. The Mac access it over a mounted network drive (Samba).
The Github Desktop Ubuntu is able to access the files very direct.

Do you require a special network drive setup ?
Anyhow, it was working before.

**Comment by Tioranat** [comment]
Another observation:

This is one of the failed commands:
`/Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 --`
When entered on Mac on the mounted folder in the root of the project it runs without error.

**Comment by steveward** [comment]
I'm going to close this in favor of #15539. I was able to reproduce this issue as well on my machine with a Samba mounted drive. @Tioranat I'd recommend following along in #15539 for updates about this issue as we investigate.
