### ISSUE TITLE
Fix ur program

### ISSUE THREAD

**Issue by KamiKaZe112** [desktop/desktop#15726]
### The problem

My git hub is bugging bugging.
When I try to start a new project it says fatal: bad config line 1 in file H://.gitconfig. And i dont even know what that means so please fix this so I do not fail my programming class.
BLM.

### Release version

IDK

### Operating system

IDK

**Comment by steveward** [comment]
Thanks for the issue. It looks like there is a problem with the first line in the `.gitconfig` file Git uses. Can you navigate to the file in the error message ( H://.gitconfig) and open it to see if there is anything in the first line that could be causing this? Feel free to share the contents of the file as well if that's easier.

**Comment by Mina012015** [comment]
changelog.json
ماذا عليا ان افعل
