### ISSUE TITLE
Issue with connection to GitHub

### ISSUE THREAD

**Issue by rkolesar** [desktop/desktop#15724]
### The problem

I have created a new repository local drive OSD. Used GitHub Desktop to create the repository locally. And it can push to origin fine no issues. BUT when I use GitHub Desktop to go to the repository it is wrong. Going  to a different older repository.  OSDOLD.
I do not understand what is going on.

### Release version

Version 3.1.2 x64

### Operating system

Windows 10

### Additional context

![Capture1](https://user-images.githubusercontent.com/116391706/205525866-6cb99251-7c11-4bf8-b9bd-c6fa584c98ef.JPG)
![Capture2](https://user-images.githubusercontent.com/116391706/205525872-ab9e8628-c8f6-49fd-ac8e-0f4d268c1a35.JPG)

**Comment by steveward** [comment]
@rkolesar apologies for the delay. This is likely a caching issue, and you can take some steps to resolve this if you're still having problems. Here's how:

1. Open `Developer Tools` (View > Toggle Developer Tools)
2. Click the `Application` tab
3. Select 'Clear Storage' from the list
4. Click 'Clear Site Data' to clear out the cached data 
5. Restart GitHub Desktop

This will 'reset' GitHub Desktop, so you will need to add your repositories back again. I'm going to close this out, but let me know if that does not get things working.
