### ISSUE TITLE
Authentication failed. You may not have permission to access the repository.

### ISSUE THREAD

**Issue by sunk818** [desktop/desktop#1572]
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Added local repository, unable to push to remote repository

I get this error when I try to push or fetch:

`Authentication failed. You may not have permission to access the repository. Open options and verify that you're signed in with an account that has permission to access this repository.`

On Chocolate-Covered Yaks (3.3.4.0) 50415df, I'm already set up with the Stash (Atlassian) server and change sync changes. The 0.5.3 beta did not bring in my local repositories. I had to add them manually, and I don't have a way to authenticate to Stash. I thought it would ask or re-ask for password, but doesn't seem to work.

I tried to ssh to stash on port 22 and got connection refused. I can browse via web browser on port to stash and see my repositories.

Could it be that Git is not installed? When I tried to open Command Prompt inside GitHub desktop, I got this error about being unable to locate Git. I don't really know where to go from here...

![170517-01](https://cloud.githubusercontent.com/assets/6989799/26168728/fb8313a0-3aef-11e7-8c93-1b027175ea87.jpg)

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** [version here]

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behaviour:** [What you expected to happen]

**Actual behaviour:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by joshaber** [comment]
We don't currently support authenticating with non-GitHub repositories. We're tracking that work in #852. Feel free to follow along there.

**Comment by sunk818** [comment]
In GitHub Windows program, I was able to work around by add local repository and then make commits to Stash (Bitbucket?) afterwards. So, I wasn't sure why the functionality stopped working in the Beta.

**Comment by Altiano** [comment]
I also try similar thing with GitHub for Windows. All I had to do is to copy-paste id_rsa.pub.
In Github Desktop, where is this file?

**Comment by mk485eg** [comment]
same problem any idea how to fix please

**Comment by j-f1** [comment]
@mk485eg Can you open a new issue and fill out the template so we can help you better?
