### ISSUE TITLE
Better support for "includes"

### ISSUE THREAD

**Issue by driverkt** [desktop/desktop#15734]
### The feature request

Here is an example of what I have set up. It may be atypical, but hopefully this is still a valid feature request: 

When managing my dotfiles, I have a global `.gitconfig` that is common to all machines/environments. That `.gitconfig` includes the following: 

```
[include]
  path = .gitconfig.local
```

In this way, the global settings for certain values can be set on a per-machine/per-environment basis. Github Desktop always updates `~/.gitconfig` with `[user]` values without following the `[include]` to see where else it might be "included" (or already exist). 

I found [issue 12041](https://github.com/desktop/desktop/issues/12041), but it seems this is still broken. 

See [`--[no-]includes`](https://git-scm.com/docs/git-config#Documentation/git-config.txt---no-includes) for context.

### Proposed solution

Support `[include]` such that the `[user]` value can be sourced from any/all included files. 

In my example above, some useful config values to have in `.gitconfig.local` might be: 

```
[user] 
  name = <value here>
  email = <value here>

[credential]
  helper = <platform-specific value>

[diff]
  guitool = <platform-specific tool>
```

Hopefully this further demonstrates the usefulness of this feature.

**Comment by steveward** [comment]
Thanks for the feedback @driverkt. This does look similar to #12041 so I'm going to add this feedback there in the interest of keeping our issue tracker consolidated and close this out.
