### ISSUE TITLE
tongue

### ISSUE THREAD

**Issue by senolfndk** [desktop/desktop#15731]
### The feature request

can you add turkish language

### Proposed solution

language options

**Comment by steveward** [comment]
Thanks for the issue @senolfndk. Unfortunately we don't have the bandwidth to be able to work on translating GitHub Desktop at this time, but this is something we would like to work on in the future. Thanks for sharing your interest in seeing this implemented.

**Comment by senolfndk** [comment]
> sorun için teşekkürler@senolfndk. Ne yazık ki şu anda GitHub Desktop'ı çevirmek için çalışacak bant genişliğine sahip değiliz, ancak bu, gelecekte üzerinde çalışmak istediğimiz bir konu. Bunun uygulandığını görmekle ilgilendiğiniz için teşekkür ederiz.
hopefully we'll see this option in the near future
