### ISSUE TITLE
[Feature Request] Add an option to disable register x-github-desktop-auth:// protocol automaticlly

### ISSUE THREAD

**Issue by xmha97** [desktop/desktop#15739]
### The feature request

Hi,
I using the portable version of GitHub Desktop.
The x-github-desktop-auth:// protocol is added every time I open the app.
This causes the protocol to malfunction.

### Proposed solution

![image](https://user-images.githubusercontent.com/23485114/206053808-1fd74d08-14d7-4462-bf20-3c383a63ff13.png)

**Comment by niik** [comment]
Hey @xmha97, thanks for reaching out. GitHub Desktop does not have a portable version and we don't have any plans of supporting a portable version at this time. The `x-github-desktop-auth` protocol is required to support authenticating in the application and not registering it would effectively disable signing in. Sorry to not have better news for you.
