### ISSUE TITLE
Open In PyCharm functional does not work properly for python projects

### ISSUE THREAD

**Issue by kossman** [desktop/desktop#15735]
### The problem

"Open In PyCharm" button does not work properly

### Release version

Version 3.1.2 (x64)

### Operating system

MacOS Ventura 13.0.1 (22A400) Intel

### Steps to reproduce the behavior

1. Go to GitHub Desktop
2. Select the python project
3. Select any of commits at opened branch
4. On any of changed files open a context menu
5. Click on Open In PyCharm
6. PyCharm opens without navigation to necessary (selected) file 

### Log files

[2022-12-06.desktop.production.log](https://github.com/desktop/desktop/files/10164891/2022-12-06.desktop.production.log)

### Additional context

PyCharm 2022.3 (Professional Edition) 
Build #PY-223.7571.203, built on November 30, 2022

**Comment by steveward** [comment]
Thanks for the report @kossman. I tested this out a bit and didn't hit the issue when PyCharm was initially closed. However, once I opened a file in PyCharm and selected another file to open from GitHub Desktop I was able to reproduce the behavior. Do you have any other JetBrains IDEs installed to test this out on? I currently only have PyCharm as well.

**Comment by kossman** [comment]
@steveward I have only one installed PyCharm IDE. I've suggested that maybe a few opened projects (at one PyCharm IDE) may break this functionality, but closing all other projects didn't fix the issue

**Comment by LALLIE14** [comment]
Hello

Tell me can someone hack me through Github?

**Comment by kossman** [comment]
@steveward hi! Any updates on the issue? :)

**Comment by farhaanshaikh19** [comment]
After recent recent Github Desktop/PyCharm updates, this is now working for me again!

Github Desktop: Version 3.1.3 (x64)
PyCharm: PyCharm 2022.3.1 (Professional Edition) Build #PY-223.8214.51, built on December 20, 2022

**Comment by kossman** [comment]
Issue fixed, ticket already not needed

**Comment by HarshGajraSUNY** [comment]
I still see the issue.
