### ISSUE TITLE
i cant discard changes from my database...

### ISSUE THREAD

**Issue by MohamedOfalah** [desktop/desktop#15749]
### The problem

cant discard, it shows: Saved working directory and index state On main: !!GitHub_Desktop<main>
error: unable to unlink old 'testcorrect_vragen.db': Invalid argument
fatal: Could not reset index file to revision 'HEAD'.

### Release version

latest

### Operating system

windows

**Comment by steveward** [comment]
@MohamedOfalah thanks for the report. This error means the file is being locked by another application -- I would recommend closing any other applications that could have that database file open and then try to see if that gets things working. Let me know if you have any further issues.

**Comment by MohamedOfalah** [comment]
I fixed it in another way but yours is better, i will do that next time,
thanks!
