### ISSUE TITLE
Open in external editor shortcut does not work when there's a pending merge conflict

### ISSUE THREAD

**Issue by dackmin** [desktop/desktop#15756]
### The problem

At any given time, I can open a repository in my favorite external editor (vscode here, for context) using the `cmd+shift+a` shortcut (on macos), but when there's a merge conflict to resolve, and even if the merge conflict prompt is not opened, gh desktop doesn't want to open the editor anymore.

I just realized the same thing happens to the `About GitHub Desktop` menu even when the merge conflicts prompt is not opened, so I guess it has something to do with it blocking the UI like an opened prompt.

----

Hi 👋 

I don't know if it's really a bug or an intended behavior, but it has always bugged me so I thought I'd share my frustration with the world.

I can't find any related issue, open or closed, so I'm gonna go ahead and create this one, feel free to close it if it's a duplicate.

### Release version

Version 3.1.2 (arm64)

### Operating system

macOS Ventura 13.0.1 (22A400)

### Steps to reproduce the behavior

1. Introduce a merge conflict between two branches
2. Dismiss the merge conflict prompt by clicking anywhere around it, so you just end up with the `Resolve conflicts to continue merge into ...` warning on top
3. Try to open your external editor using `cmd+shift+a` or even the `About GitHub Desktop` menu

### Log files

The action doesn't generate any log, I think it's a faulty "expected behavior" (if I may)

### Screenshots

<img width="746" alt="Capture d’écran 2022-12-09 à 10 00 45" src="https://user-images.githubusercontent.com/1873323/206664481-1e6965b1-ee88-4a6f-86e5-4836db080e07.png">

**Comment by cicakkobeng8p** [comment]
👍

**Comment by steveward** [comment]
Thanks for the issue @dackmin. This looks like the same report as https://github.com/desktop/desktop/issues/14236 (and also https://github.com/desktop/desktop/issues/6429), where menu items are disabled when merge conflicts are present. I'll add this to #14236.
