### ISSUE TITLE
Creating a branch is hidden in the File menu

### ISSUE THREAD

**Issue by Haacked** [desktop/desktop#1575]
I recently tried to create a new branch and was confused by the interface on how to do so. There was no option in the `Branch` menu to create one. Likewise, the [first comment on my blog post](http://haacked.com/archive/2017/05/16/github-beyond-the-browser/#comment-3309921358) about this release was...

> It seems that I cannot create a branch from the Beta. Does it still under developing?

So I think there's definitely a mismatch between expectations here. In the context of Desktop, I'm not even sure the "File" menu makes sense. At the very least, I'd like to have `New Branch` and `New Repository` menu items within the `Branch` and `Repository` menus respectively.

**Comment by joshaber** [comment]
Put this in 1.0 to consider.

**Comment by niik** [comment]
xref https://github.com/desktop/desktop/issues/1639

**Comment by kazzkiq** [comment]
Found this Issue after facing the same confusion.

IMO, the action for new branch should be found in Branch tab, so a minimal change like adding a button there should do lots in terms of usability. Example:
![123](https://cloud.githubusercontent.com/assets/1953194/26280173/af5d226a-3d9f-11e7-83ca-e8a154634a09.png)

**Comment by BasThomas** [comment]
Being able to create a branch directly from the "Filter" text would also be a nice to have, IMHO.

**Comment by joshaber** [comment]
Opened https://github.com/desktop/desktop/issues/1757 to track moving the menu item specifically.

**Comment by joshaber** [comment]
We're gonna consider this done until we get more feedback.

**Comment by 01nad54** [comment]
Что значит - отзывы?
