### ISSUE TITLE
left project list add pin function

### ISSUE THREAD

**Issue by corleonePeng** [desktop/desktop#15750]
### The feature request

in project list has many item.
i think have function select some one or more pin to the list top ?
thank, i want many plepeo need this function.

### Proposed solution

select some one or more pin to top, i think this code is simple.

**Comment by steveward** [comment]
Thanks for the request @mikePengW. This is being tracked in https://github.com/desktop/desktop/issues/8183, but at this time we don't have any plans to work on this. This may change in the future, though. I'll reference this issue there, and feel free to leave a 👍🏻 to the original issue comment to indicate your interest in this feature.
