### ISSUE TITLE
Linux: Cannot locate projects on external drive after reboot automatically by same path

### ISSUE THREAD

**Issue by Watcher3056** [desktop/desktop#15762]
### The problem

Cannot locate projects on external drive after reboot automatically by same path

### Release version

3.1.1

### Operating system

Linux

### Steps to reproduce the behavior

Linux:
1) Attach external drive to PC
2) Create project on external drive
3) reboot your system
4) open github desktop and it will popup window "Cant locate the project"

### Additional context

I can manually specify project location again(path is unchanged), but it will force github desktop to re-index whole project, which is consume some time, CPU and battery charge. This is bad when you working with only one project and especially bad when there is several projects with such behaviour from github-desktop.

**Comment by 1231111-cyber** [comment]
little lv DLQ but!

**Comment by niik** [comment]
Hey @Watcher3056, GitHub Desktop doesn't officially support Linux so if this is a specific condition that only happens on Linux you would probably have better luck opening an issue in the [unofficial Linux fork](https://github.com/shiftkey/desktop). That said there should be a small "Check again" link that you can click which should let you avoid specifying the path manually.

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/634063/207279480-cc5bfe6b-90f1-4254-99c9-2cfd80438fbb.png">

> but it will force github desktop to re-index whole project, which is consume some time, CPU and battery charge

Just as an aside there's very little difference in adding a repository to Desktop for the first time and say, switching to an already existing repository. GitHub Desktop does very little internal state-keeping and instead relies on executing Git commands which will have to be executed regardless of whether the repository is unknown or known to Desktop.

Hope that helps!
