### ISSUE TITLE
Again hanging on checkin in a project

### ISSUE THREAD

**Issue by RainerPri** [desktop/desktop#15765]
### The problem

Sometimes if i like to check in a project, GitHub Desktop is hanging in macOS.
The problem is on different projects!

On Windows it is never a problem!

### Release version

Version 3.1.2 (x64)

### Operating system

13.0.1 (22A400)

### Steps to reproduce the behavior

Push a project to origin!

### Log files

[2022-12-11.desktop.production.log](https://github.com/desktop/desktop/files/10203135/2022-12-11.desktop.production.log)

### Screenshots

<img width="680" alt="Bildschirm­foto 2022-12-11 um 20 57 14" src="https://user-images.githubusercontent.com/23703667/206925818-11276f51-268b-4d52-9e14-9b8225788c65.png">

**Comment by sergiou87** [comment]
@RainerPri does it work when you run the `git push` command from the terminal?

**Comment by RainerPri** [comment]
@sergiou87 i never have tryed it over the terminal.
What i have to do? I am not confirmed with the terminal commands.

**Comment by sergiou87** [comment]
@RainerPri you just need to open the Terminal app, then type `cd <path to your repository>` (for example `cd Documents/GitHub/MyRepository`), and finally type `git push`.

Other thing you could try is opening Developer Tools from `View -> Toggle Developer Tools`, select the `Console` tab, and see if there are any weird messages or errors when the app is pushing and gets stuck.

**Comment by RainerPri** [comment]
Hello @Sergio,Thank you for the info!I will try it.Unfortunately i am on a busines trip now and can try it in 10 days.Thank you and BR Rainer ---Immer Gut Licht und vergesst die schatten nicht!Rainerhttps://primosch.artAm 14.12.2022 um 13:20 schrieb Sergio Padrino ***@***.***>:﻿
@RainerPri you just need to open the Terminal app, then type cd <path to your repository> (for example cd Documents/GitHub/MyRepository), and finally type git push.
Other thing you could try is opening Developer Tools from View -> Toggle Developer Tools, select the Console tab, and see if there are any weird messages or errors when the app is pushing and gets stuck.

**Comment by steveward** [comment]
I'm going to close this out due to inactivity -- @RainerPri if you are still having issues let us know and we can investigate further.
