### ISSUE TITLE
Legal cleanup

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#1576]
From @mlinksva:

>a few comments on the license notices available (as 'Acknowledgements') from the `GitHub Desktop | About GitHub Desktop` menu:
>
>- I see that some dependencies listed only show the name of the license and don't include a copy of the license. That's fine if the dependency doesn't provide a copy of the license itself, but the [first such dependency I checked](https://github.com/webpack/loader-utils) does provide a copy, which ought be included in the acknowledgements
>- It'd be nice to include the project's MIT license at the top, as the Terms and Conditions don't grant any other license for the app. Take a look at `Atom | View License`.
>- Along those lines, I suggest the 'linktext' to be 'License and Open Source Notices' rather than 'Acknowledgements' (also reflecting what the Terms and Conditions say to expect)
>- I can't select or copy text in the acknowledgements popup (unlike the T&C one). Just an annoyance. If it weren't just a bunch of friendly open source licenses though, it would really unfriendly behavior.

**Comment by shiftkey** [comment]
> I see that some dependencies listed only show the name of the license and don't include a copy of the license. That's fine if the dependency doesn't provide a copy of the license itself, but the first such dependency I checked does provide a copy, which ought be included in the acknowledgements

This seems to be a feature of `legal-eagle` - for licenses that it knows and have no variation, it hides the text. Might be a bit of work to change this behaviour and get it merged in the upstream project. @mlinksva how strongly do you feel we should be displaying the full license for these?

**Comment by joshaber** [comment]
☝️ That would also mean Atom has the same behavior, since we're both using `legal-eagle`.

**Comment by shiftkey** [comment]
Examples from the Atom license tab:

<img width="954" src="https://cloud.githubusercontent.com/assets/359239/26200346/0081c500-3c11-11e7-895d-41df75e31673.png">

**Comment by mlinksva** [comment]
> This seems to be a feature of legal-eagle - for licenses that it knows and have no variation, it hides the text.

I don't see where legal-eagle does this. I think at least for the example I pointed out, legal-eagle isn't detecting the license from the `LICENSE` file, so is getting the license from `package.json` and as a result does not include the contents of `LICENSE`. Probably detection could be improved, and `LICENSE` contents should be included in all cases.

I'll open an issue or maybe even a PR to fix legal-eagle Monday.

**Comment by shiftkey** [comment]
@mlinksva I think it's this section: https://github.com/atom/legal-eagle/blob/master/src/legal-eagle.coffee#L48-L60 that's the `package.json` work.

If we want these known cases to also provide the license text, it should be as simple as assigning the text of this license to`licenseText` on [this line](https://github.com/atom/legal-eagle/blob/master/src/legal-eagle.coffee#L60).

**Comment by mlinksva** [comment]
@shiftkey https://github.com/atom/legal-eagle/pull/13
