### ISSUE TITLE
Support linux through flatpak

### ISSUE THREAD

**Issue by solecram** [desktop/desktop#15769]
### The feature request

Hi, my name is Marcelo, I'm from Brazil and I'm 24 years old. I really liked the Github Desktop tool and despite using Windows I am also a Linux user, I would like to know if it would be possible to port a version to the penguin operating system, specifically in the flatpak packaging format (which would possibly facilitate support and distributing the program to more distributions without as much work). Well that's it, I look forward to your feedback, and thanks in advance for your time.

### Proposed solution

Create a version for Linux operating systems via the flatpak packaging format.

**Comment by tsvetilian-ty** [comment]
Hello @m4k1fu 👋  GitHub Desktop doesn't officially support Linux, but there is a fork (unofficial) that adds support for different Linux distributions: https://github.com/shiftkey/desktop In the "Other Distributions" section of the docs you can find a link to [flathub](https://flathub.org/apps/details/io.github.shiftey.Desktop)

**Comment by solecram** [comment]
> Hello @m4k1fu wave GitHub Desktop doesn't officially support Linux, but there is a fork (unofficial) that adds support for different Linux distributions: https://github.com/shiftkey/desktop In the "Other Distributions" section of the docs you can find a link to [flathub](https://flathub.org/apps/details/io.github.shiftey.Desktop)

Is there no possibility of offering a version dedicated to Linux by default? Another thing that would make it easier in case of a negative answer would be to add the possibility of setting an alternative path to the one offered by default in the vscode options and in the terminal itself.

**Comment by tsvetilian-ty** [comment]
There is always  a possibility you could follow https://github.com/desktop/desktop/issues/1525 for updates on the topic
