### ISSUE TITLE
fatal: missing object ee9ed4f68dcf3c57392bb4789b017b19d0a55d76 for refs/remotes/origin/Addresses

### ISSUE THREAD

**Issue by Morons** [desktop/desktop#15776]
### The problem

Whenever I enter GitHub Desktop I get 
`fatal: missing object ee9ed4f68dcf3c57392bb4789b017b19d0a55d76 for refs/remotes/origin/Addresses`

### Release version

Version 3.1.2 (x64)

### Operating system

Win 10

### Steps to reproduce the behavior

Whenever I enter GitHub Desktop

### Screenshots

![Screenshot 2022-12-13 131610](https://user-images.githubusercontent.com/22202038/207303750-8cde66c9-9c93-488e-9517-fa8279d53c58.png)

**Comment by sergiou87** [comment]
That sounds like something is wrong in your repository. Could you try running `git gc` from the command line in your repo and see if that fixes it?

**Comment by ffernandosantos** [comment]
Estou com erro parecido. Como posso resolver? 
![Screenshot_3](https://github.com/user-attachments/assets/3ac7fdd5-5271-4a56-bd4c-fbbde4b8f472)

**Comment by JAWAD-ASGHAR** [comment]
this likely means your local Git metadata is corrupted, specifically in
.git/refs/heads/ 
or 
.git/logs/refs/heads/

not sure how to fix.....
