### ISSUE TITLE
Upload Check/ X Mark

### ISSUE THREAD

**Issue by DoubleDaveEnt** [desktop/desktop#15779]
### The feature request

When pushing from the Desktop to the Online Repo., can we get a Green Check Mark or Red X next to the file after it has been uploaded?  This way if we have a large upload we can monitor the progress to determine how much is left to upload load or at the very least can we get a Percentage Uploaded in the bar with the Push to Origin on the right side.

### Proposed solution

This would help users that have large uploads to understand how much time is left to upload or what the progress is.

**Comment by steveward** [comment]
Thanks for the issue @DoubleDaveEnt. There is a progress bar built into the `Push origin` button:

<img width="272" alt="Screen Shot 2022-10-14 at 4 41 39 PM" src="https://user-images.githubusercontent.com/721500/195940013-5d539db6-e65d-49d4-a2cd-a018157269ae.png">

I hope that helps!
