### ISSUE TITLE
Add Fleet as external editor option

### ISSUE THREAD

**Issue by valentinegb** [desktop/desktop#15772]
### The feature request

Currently, there is no external editor option for [Fleet](https://jetbrains.com/fleet), which is the editor I primarily use.

### Proposed solution

If Fleet was added as an option for the external editor setting, this would be a convenient way to quickly open projects in it.

**Comment by niik** [comment]
Hey @valentinegb, thanks for reaching out. Given that we support a whole slew of JetBrains editors chances are adding support for Fleet wouldn't be all that tricky if you'd like to take a stab at it. There's [some documentation](https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md) on adding new editor which would be a good starting point.

**Comment by valentinegb** [comment]
Alright, I'll take a look.

**Comment by valentinegb** [comment]
It's not quite working... I got it to recognize I have Fleet installed and open Fleet, but it doesn't open the repository I'm on specifically, it just opens whatever my last project was.

Fleet does have a CLI that opens specific files and directories (`fleet [path]`). Is there a way to do that instead within GitHub Desktop?

**Comment by tsvetilian-ty** [comment]
👋  @valentinegb JetBrains Fleet is only available through JetBrains Toolbox, and GitHub Desktop doesn't support it. I opened a PR with support for Toolbox and respectively Fleet.

**Comment by valentinegb** [comment]
Pull request was merged, closing the issue
