### ISSUE TITLE
protocol ' https' is not supported when spaces in URL

### ISSUE THREAD

**Issue by joerg1985** [desktop/desktop#15774]
### The problem

Adding a leading space to the git URL will cause an error `fatal: protocol ' https' is not supported` while fetching the repository. If the settings dialog is called again the space is not shown, but the ./git/config file will still contain the wrong URL.

### Release version

3.1.2 (x64)

### Operating system

Windows 10 x64

### Steps to reproduce the behavior

Repository > Repository settings... > Primary remote respository (origin)
add a space e.g. change "https://my.url" to " https://my.url"

**Comment by steveward** [comment]
Closing as this was fixed in #15821.

**Comment by zemgeez** [comment]
thanks for that
