### ISSUE TITLE
Support for multiple remotes in GitHub Desktop

### ISSUE THREAD

**Issue by chris-c-thomas** [desktop/desktop#15797]
### The feature request

I, like many others, would like to see multiple remotes supported in GitHub Desktop. 

### Proposed solution

Allow users to add other remotes for their repositories from within the GUI.

### Additional context

I'm sure this feature request might get closed like others haved.

It seems a little silly that GitHub CLI clone command automatically creates an origin and upstream remote for a user's forked repo. I definitely make use of multiple remotes and if I were to use a GUI it's impossible to use GitHub's application.

Some users on my team would benefit from having that feature in the GUI that don't know git very well from the command line.

It seems to be deliberately blocked from being added or something as it's been highly requested since the beginning, many other git GUIs have it, and I can't seem to find a reason why it's not being added.

Both non technical and veteran software developers can benefit from this feature.

**Comment by steveward** [comment]
Thanks for the feedback @chris-c-thomas, I'm going to add this to https://github.com/desktop/desktop/issues/1442. 

>It seems a little silly that GitHub CLI clone command automatically creates an origin and upstream remote for a user's forked repo. I definitely make use of multiple remotes and if I were to use a GUI it's impossible to use GitHub's application.

GItHub Desktop does support upstream remotes. If you look in the branches list you should see `upstream/<branch_name>`, which you can select when you want to update your local forked repository with the upstream repository. Let me know if you have any questions about that functionality.

**Comment by blazejkrzak** [comment]
Most of the IDEs have multiple repo support. That is not nice to not have it in official Github tool

**Comment by raacampbell** [comment]
@steveward it does not really seem to have the feature. Say I maintain a repo and someone forks it. I might want to add their fork as a remote and check it out. Currently this is not possible.

**Comment by wolfebrian2120** [comment]
The current version does not support adding additional remotes. We should be able to add another remote manually and sync the branches. We can do this via command line, there is no reason we shouldn't be able to through the github GUI.

**Comment by netcore-jroger** [comment]
Any updates now?

**Comment by bonbonsiregar** [comment]
any updates? for now i'm using sourcetree and it's been working great but I wish github desktop add the feature.

**Comment by HeeMa6** [comment]
[US-22-Fratric-XMPP-Stanza-Smuggling.pdf](https://github.com/user-attachments/files/19384725/US-22-Fratric-XMPP-Stanza-Smuggling.pdf)

**Comment by HeeMa6** [comment]
> มีการอัปเดตใด ๆ หรือไม่? สําหรับตอนนี้ฉันใช้ SourceTree และใช้งานได้ดี แต่ฉันต้องการให้ github desktop เพิ่มคุณสมบัตินี้

[2020-02-12-code-of-conduct.md](https://github.com/user-attachments/files/19384782/2020-02-12-code-of-conduct.md)
