### ISSUE TITLE
Portable release ?

### ISSUE THREAD

**Issue by crazy-max** [desktop/desktop#1579]
Hi,

I've created a small wrapper named [github-desktop-portable](https://github.com/crazy-max/github-desktop-portable) but i was wondering if you had planned to do one day a portable version of this app?

Thanks

**Comment by rlabrecque** [comment]
Some notes about what I want to see from this if it happens:

This should never store anything outside of the current folder except for git repos of course. All settings should live in ./settings/ or something like that if in portable mode.
It should not install the auto update service unless specifically set in the options.

I'll happily start this on the weekend.

**Comment by shiftkey** [comment]
> i was wondering if you had planned to do one day a portable version of this app?

No current plans.

**Comment by crazy-max** [comment]
And concerning auto updates, they are some issue and i don't know if it's linked to the wrapper :

![image](https://cloud.githubusercontent.com/assets/1951866/26179399/d3dc4384-3b63-11e7-87b5-db6b834b9282.png)

**Comment by shiftkey** [comment]
@crazy-max if you can detect that you're running in "portable" mode you can probably disable those update checks.

@desktop/electron have you seen any other projects go down this path? Any tips?

**Comment by kevinsawicki** [comment]
> have you seen any other projects go down this path? Any tips?

Yeah, Atom did a bunch of work to support this, I think it should be pretty much reusable for Desktop:

* https://github.com/atom/atom/pull/8442
* https://github.com/atom/atom/pull/13426

/cc @damieng

**Comment by rlabrecque** [comment]
I'll be getting on it either way if someone doesn't beat me to it, it's not
that hard.

**Comment by rlabrecque** [comment]
> Defaulting to looking for the user config/data folder (.atom in our case) alongside the .exe means the user would likely wipe it away when manually updating (auto update definitely would if it worked at all). We therefore put the .atom folder one level above, e.g. e:\.atom and e:\atom\atom.exe

That seems terrifying. Do you guys basically rm -rf the whole e:\atom\ directory during an update? What if I accidentally install into C:\atom.exe, does updating wipe my drive? I've never really had a problem with storing user content in folder in portable applications.

**Comment by shiftkey** [comment]
Marking this as `future-proposal` as I'm not sure if we're planning to do this before the 1.0 release. @desktop/core feel free to comment otherwise if you have feels.

Going to close this out and revisit as part of our next planning session. Thanks for the input everyone!

**Comment by demondevin** [comment]
### GitHub Desktop Portable
I was just wandering around and saw this open issue and figured I should share my [GitHub Desktop Portable][G1] which is packaged in accordance with the [PortableApps.com][P1] [format specifications][P2]. I hope this PAF compliant portable variant is useful for those who are looking for a reliable, portable launcher for [GitHub Desktop][C1]. See further below for more information on my version of GitHub Desktop Portable.

### Related Question
Is there a dedicated link to download an archived (_.zip_) version of GitHub Desktop in both 32/64-bit variants? I'd rather not have to keep updating my portable build each time a new stable build of GitHub Desktop is released. I'd like to just create a portable installer which connects and downloads from these two download links depending on the end-users preference and/or system's bit depth and go from there.

I have taken into account that GitHub Desktop is highly active in it's development; so I've added the means for the portable launcher to compensate for any newly found changes during runtime and update the portable build accordingly. However it'd be much more advantageous on my part to just create a stand-alone portable installer which uses a link to download an archive and extract the program from; thus eliminating the need to package the program with every new release.

### GitHub Repository
* [GitHub Project Page][G1]
* [Download Latest Release][G2]

### Features
* Packaged in [PortableApps.com][P1] format (**[PAF][P2]**) for easy integration.
* Self-sustaining; no need to update this package as it should update itself.
* During runtime, _drop-and-drop_ capabilities should be in working order so to add a local repo, just drag the repo's folder onto GitHub Desktop and voila! 
* During runtime, when you're browsing [GitHub.com][C2], you can click the green _Clone_ button and select `Open in Desktop` and it'll open in GitHub Desktop Portable as expected.

Please read the ReadMe file on the GitHub project page for a larger list of included features. More to come.. 

Thanks GitHub!

=)

[G1]: https://github.com/demondevin/GitHubDesktopPortable
[G2]: https://github.com/demondevin/GitHubDesktopPortable/releases
[C1]: https://desktop.github.com/
[C2]: https://github.com/
[P1]: https://portableapps.com/
[P2]: https://portableapps.com/manuals/PortableApps.comLauncher/ref/paf/

**Comment by j-f1** [comment]
@demondevin FYI we don’t support a 32-bit version of GitHub Desktop at this time.

**Comment by demondevin** [comment]
@j-f1 Thank you. I figured as much but just wanted to be sure anyway.

**Comment by jreimone** [comment]
@daemondevin, unfortunately I couldn't execcute your portable client because administration right are required.

**Comment by billygriffin** [comment]
Hi folks, after discussing this internally we think the value of working on other features outweighs supporting a portable version of the app. If there are specific reasons why you have a strong preference for a portable version though, we'd love to hear about those as we may be able to surface some problems that could potentially help improve the app as is. Thanks for the idea!

**Comment by jreimone** [comment]
When someone wants to contribute to a Github project but has no administrative rights. Being able to use a nice git client was great

**Comment by shiftkey** [comment]
> When someone wants to contribute to a Github project but has no administrative rights. Being able to use a nice git client was great

@jreimone you don't need administrative rights to install and use GitHub Desktop

**Comment by shiftkey** [comment]
@jreimone if you'd like us to investigate please open a fresh issue and provide details about what you're experiencing

**Comment by ibrahemesam** [comment]
> 
> ### GitHub Desktop Portable
> 
> I was just wandering around and saw this issue and figured I should share my [GitHub Desktop Portable](https://github.com/demondevin/GitHubDesktopPortable) which is packaged in accordance with the [PortableApps.com](https://portableapps.com/) [format specifications](https://portableapps.com/manuals/PortableApps.comLauncher/ref/paf/). I hope this PAF compliant portable variant is useful for those who are looking for a reliable, portable launcher for [GitHub Desktop](https://desktop.github.com/). See further below for more information on my version of GitHub Desktop Portable.
> ### Related Question
> 
> Is there a dedicated link to download an archived (_.zip_) version of GitHub Desktop in both 32/64-bit variants? I'd rather not have to keep updating my portable build each time a new stable build of GitHub Desktop is released. I'd like to just create a portable installer which connects and downloads from these two download links depending on the end-users preference and/or system's bit depth and go from there.
> 
> I have taken into account that GitHub Desktop is highly active in it's development; so I've added the means for the portable launcher to compensate for any newly found changes during runtime and update the portable build accordingly. However it'd be much more advantageous on my part to just create a stand-alone portable installer which uses a link to download an archive and extract the program from; thus eliminating the need to package the program with every new release.
> ### GitHub Repository
> 
>     * [GitHub Project Page](https://github.com/demondevin/GitHubDesktopPortable)
> 
>     * [Download Latest Release](https://github.com/demondevin/GitHubDesktopPortable/releases)
> 
> 
> ### Features
> 
>     * Packaged in [PortableApps.com](https://portableapps.com/) format (**[PAF](https://portableapps.com/manuals/PortableApps.comLauncher/ref/paf/)**) for easy integration.
> 
>     * Self-sustaining; no need to update this package as it should update itself.
> 
>     * During runtime, _drop-and-drop_ capabilities should be in working order so to add a local repo, just drag the repo's folder onto GitHub Desktop and voila!
> 
>     * During runtime, when you're browsing [GitHub.com](https://github.com/), you can click the green _Clone_ button and select `Open in Desktop` and it'll open in GitHub Desktop Portable as expected.
> 
> 
> Please read the ReadMe file on the GitHub project page for a larger list of included features. More to come..
> 
> Thanks GitHub!
> 
> =)

thanks ☺

**Comment by BMD4E** [comment]
Any news?

**Comment by steveward** [comment]
@BMD4E we still do not have plans to offer an official portable version of GitHub Desktop. Are there any specific reasons you would prefer a portable version?

**Comment by grloch** [comment]
> @BMD4E we still do not have plans to offer an official portable version of GitHub Desktop. Are there any specific reasons you would prefer a portable version?

I have two accounts on Github, a personal one and a account i use for work.

I don't want to mix they, because they are for different purposes, so, everytime i want to work in a personal repository i need to logout on my client, log in my personal account, then i need to do it again to back on my work account.

If i had a portable version of the client, i could just leave it on a folder and use it there, so i could have two accounts, with two cliends working in parallel. (this is just one aplication)

As a college student, i could have it on a pendrive while working on some code, commit my code on college and still work on it on a another computer later.

I think this is a great feature, there is many applications for it.

**Comment by BMD4E** [comment]
I have the same thought, I would like to be able to use Github everywhere on my pendrive without having to install Github on others computers and without admin rights

**Comment by Toshiba1127** [comment]
I need portable version too, or at least be able to install to other drives, because my SSD drive which is C drive is too small.

Funny facts is smaller companies are able to make portable version even their software size is small, while big companies aren't able too. Not being able to do makes me feel like developers are amateurs and do not know how to manage the directory :/

**Comment by bakomon** [comment]
Alternative: https://github.com/desktop/desktop/issues/3707#issuecomment-1803014584

**Comment by mikeukeul** [comment]
“Il est temps que GitHub et GitHub Desktop franchissent le pas vers une interface universelle et multilingue. Les extensions de traduction ne suffisent pas : elles bricolent là où une solution native apporterait cohérence, fiabilité et inclusion. Dans un monde où l’IA traduit le sumérien, pourquoi nos outils modernes ne pourraient-ils pas traduire toutes les langues vivantes ? Arrêtons le cloisonnement des pensées et ouvrons le monde des possibles.”
