### ISSUE TITLE
Can't download macOS installer

### ISSUE THREAD

**Issue by lshearer** [desktop/desktop#1580]
### Description

Unable to access the macOS installer from the website links.

### Version

**GitHub Desktop version:** 0.5.4

**OS version:** macOS

### Steps to Reproduce

1. Go to https://desktop.github.com/ and click `Download for macOS` **_OR_** go to https://github.com/desktop/desktop and click `macOS` under `Where can I get it?`.

**Expected behaviour:** It will load an installer of some kind.

**Actual behaviour:** I get taken to https://desktop.githubusercontent.com/github-central/releases/0.5.4-530c75f8/GitHubDesktop.zip which loads as
```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>4DBB1562747250DF</RequestId>
<HostId>
V9aQq91lmEPG1057hGUGoe+mAAzUxFImVsIbCKjpPjOpOpMPa65w87G/1UI7ltRo5SfQGLi6X8g=
</HostId>
</Error>
```
It appears that either the URL is wrong or the S3(?) object has not been made public.

**Reproduces how often:** 100%

**Comment by joshaber** [comment]
Thanks for letting us know @lshearer! Can you confirm that https://s3.amazonaws.com/github-central/releases/0.5.4-530c75f8/GitHubDesktop.zip works for you?

**Comment by carlweis** [comment]
The s3 download link worked for me. Thank you.

**Comment by joshaber** [comment]
This should be fixed now 💥

**Comment by lshearer** [comment]
Thanks!
