### ISSUE TITLE
cant install github desktop

### ISSUE THREAD

**Issue by HatDuaa** [desktop/desktop#15805]
### The problem

I cant install github destop in my PC.

### Release version

newest version at 12/20/2022

### Operating system

windows 11

### Steps to reproduce the behavior

step 1: I go to https://desktop.github.com/ and then dowload the newest version.
step 2: I run file exe 
step 3: Windows 11 shows an error 

### Log files

[SquirrelSetup.log](https://github.com/desktop/desktop/files/10261417/SquirrelSetup.log)

### Screenshots

![image](https://user-images.githubusercontent.com/118889331/208484799-403127c4-f0ea-482d-a345-657b313f071d.png)

**Comment by steveward** [comment]
Thanks for the report @HatDuaa. Unfortunately the installation log file isn't showing anything specific to GitHub Desktop. Are you running any antivirus or security software that could be interfering with the installation? Have you previously been able to install GitHub Desktop on this machine?

**Comment by HatDuaa** [comment]
I have never installed GitHub Desktop on this machine. I have the default windows antivirus but i tried disabling it and installing github again but it still doesn't work

**Comment by roadbike831** [comment]
Hi Normally if something is closed, it means it has been solved and not a issue for others? but
yet I tried to install it this morning. Go through setup launcher, but nothing after that? No Error at all?

**Comment by steveward** [comment]
@roadbike831 if you are having issues installing GitHub Desktop please open a new issue and fill out the template so we can assist you further. Thanks!

**Comment by 24039890** [comment]
can't install github
