### ISSUE TITLE
LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 

### ISSUE THREAD

**Issue by x-jeff** [desktop/desktop#15803]
### The problem

Error occurs when pushing changes to GitHub:
LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 

MacOS Ventura 13.1
GitHub Desktop Version : Version 3.1.2 (x64)
Git Version : 2.19.0

### Release version

Version 3.1.2 (x64)

### Operating system

MacOS Ventura 13.1

**Comment by steveward** [comment]
@x-jeff thanks for the issue. Unfortunately this is usually caused by a network issue, and isn't something that we can directly resolve on our end. Are you behind a proxy or firewall that could be causing this?
