### ISSUE TITLE
Push Origin Creating Problem with Remote Disconnection Error.

### ISSUE THREAD

**Issue by cyberseef** [desktop/desktop#15816]
### The problem

I have been trying to push my files on GitHub repository but after the compression of objects, the push gives an error while writing objects. It provides the error of remote connection disconnected which I confirmed is absolutely connected but the Github Desktop app refuses to push and accepts there is no connection problem.

### Release version

Version 3.1.2 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Launch GitHub Desktop.
2. Commit changes.
3. Click on 'Push Origin'

### Log files

[2022-12-22.desktop.production.log](https://github.com/desktop/desktop/files/10286354/2022-12-22.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/55156432/209121187-65c8166d-a7c9-4b56-8360-64d17b477761.png)

**Comment by kitswas** [comment]
Does `git push` on the command line succeed for your repository?

**Comment by cyberseef** [comment]
Didn't try that in terminal because the focus this time was to just push it through the app as I was in a hurry.
________________________________

**Comment by steveward** [comment]
@cyberseef are you still encountering this issue? It looks like you're hitting this error:

```
error: RPC failed; curl 55 Send failure: Connection was aborted
send-pack: unexpected disconnect while reading sideband packet
```

You could try the solution I [mentioned here](https://github.com/desktop/desktop/issues/9367#issuecomment-604621104) to push smaller chunks -- that may be a workaround if you are trying to push a large changeset and are continually hitting timeouts.

I'm going to close this out, but let me know if I can answer any further questions.
