### ISSUE TITLE
Not Opens files in RubyMine

### ISSUE THREAD

**Issue by Faq** [desktop/desktop#15815]
### The problem

It does not open specific file in RubyMine, opens just RubyMine

RubyMine 2022.3
Build #RM-223.7571.183, built on November 29, 2022

### Release version

Version 3.1.2 (arm64)

### Operating system

MacOS 13.1

### Steps to reproduce the behavior

A)
1. when opened repository with local changes
2. click on file and choose option "Open in RubyMine"
3. it opens rubyMine but not the specific *.slim or *.rb file
No error shows in log file.

B)
1. when opened repository with local changes
2. click on file and choose option "Open with Default program"
3. it opens specific rb, file in xcode, that is OK.

C)
1. when opened repository with local changes
2. click on *.slim file and choose option "Open with Default program"
3. gives error, that file not associated with any program.
From macos finder, when doubleclick on *.slim file, it opens in rubymine
Also error entry is written in logfile.

### Log files

[2022-12-22.desktop.production.log](https://github.com/desktop/desktop/files/10285310/2022-12-22.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/322016/209091595-9329f1e0-4b20-420c-86db-0fba942371d4.png)

**Comment by Faq** [comment]
hmm or this is rubyMines issue, mentioned also here https://youtrack.jetbrains.com/issue/RUBY-30654/RubyMine-no-longer-open-associated-files-in-MacOS

**Comment by emt420769** [comment]
?

**Comment by Faq** [comment]
That was bug in RM, fixed with RubyMine 2022.3.1
Build #RM-223.8214.60, built on December 21, 2022
