### ISSUE TITLE
GitHub Desktop not finding RStudio as External Editor

### ISSUE THREAD

**Issue by ericvmai** [desktop/desktop#15810]
### The problem

I recently upgraded to RStudio 2022.12.0 Build 353 and Github Desktop can no longer find RStudio as an external editor. I could previously open my RStudio project directly from Github Desktop, but now I have to open the folder and just open the .rproj 

This is a bit inconvenient. I try to go to the options to set an external editor and RStudio is not even available.

Anyone else having this issue?

### Release version

2022.12.0 Build 353

### Operating system

Windows 11

**Comment by steveward** [comment]
Thanks for the report @ericvmai. I installed RStudio and was able to reproduce this. It looks like they changed RStudio (the organization) to "Posit Software", which [changed the 'Publisher' string](https://github.com/desktop/desktop/blob/87fd61879f2ae9cfb2e6f210f6c4a998e950ad72/app/src/lib/editors/win32.ts#L360):

```
    Hive: HKEY_LOCAL_MACHINE\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall


Name                           Property
----                           --------
rstudio                        DisplayName     : RStudio
                               DisplayVersion  : 2022.12.0+353
                               Publisher       : Posit Software
                               UninstallString : C:\Program Files\RStudio\Uninstall.exe
                               NoRepair        : 1
                               NoModify        : 1
                               DisplayIcon     : C:\Program Files\RStudio\rstudio.exe
                               StartMenu       : RStudio
````

I'll open a PR to get this updated.

**Comment by laccawu** [comment]
I have the problem, too. I hope the problem will be solved soon

**Comment by DennisNyabuto** [comment]
Thanks for the raising the issue. I have been struggling with the same issue.

**Comment by Simon-h20** [comment]
Yes I also have the same issue with this release version running on Macbook OS Ventura 13.1

**Comment by CGMoreh** [comment]
Same issue here, just updated RStudio.
