### ISSUE TITLE
other language (chinese)

### ISSUE THREAD

**Issue by Wangjn258** [desktop/desktop#15818]
### The feature request

i hope desktop can support change language(such as chinese).
cause i am Chinese and i am not good at english(i fell sorry about that but i really like this application).

of casuse, if your team doesn't have enough money to employ person to do this, just Initiate a donate.

thank you.

### Proposed solution

i don't konw about how to translate a app from english to other language . but i think just change the **UI** it will not diffcute, you can just use the translator(such as _Google translator_ , _Deepl_).

**Comment by tidy-dev** [comment]
Thanks for the suggestion @Wangjn258! At this time we do not have language localization in GitHub Desktop, but this is something that we would like to do in the future. I don't have a timeline for when that may happen as it would require quite a bit of work by the team. I'm sorry that I don't have better news at this time.

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/GitHub-Desktop-Chinese-Language-Pack

**Comment by steveward** [comment]
@Johnserf-Seed we ask that you please do not spam existing issues with links to your personal project, even if your project is related to GitHub Desktop. Spamming issues with links is a violation of our code of conduct. Thanks.

**Comment by iamqiz** [comment]
it is time to support other language by load language file , such as json, and community will help to translate english version file  to other languages

**Comment by iamqiz** [comment]
it is time to support other language by load language file , such as json, and community will help to translate english version file to other languages
