### ISSUE TITLE
git init not working 

### ISSUE THREAD

**Issue by ROOKIEsarthak** [desktop/desktop#15811]
[2022-12-21.desktop.production.log](https://github.com/desktop/desktop/files/10278949/2022-12-21.desktop.production.log)
### The problem

![Screenshot_20221221_160813](https://user-images.githubusercontent.com/98842340/208886013-4a21ddf0-ebf0-46ec-b2d9-d1fcda70793a.png)
Unable to initialize any folder into a github repo by 
git init command . 

It says permission denied and am unable to work .
### Release version

Git 2.39.0

### Operating system

windows 11

**Comment by steveward** [comment]
Thanks for the report @ROOKIEsarthak. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by ROOKIEsarthak** [comment]
The log file for today. Please look into it I am unable to work . Thank you
.

**Comment by steveward** [comment]
You'll need to upload the log file as an attachment directly to this issue. Unfortunately email replies do not transfer attachments.

**Comment by ROOKIEsarthak** [comment]
attached the log file . Please have a loot at it .

**Comment by steveward** [comment]
Thanks, it looks like the specific issue is with your `D:` directory:

```
fatal: could not create work tree dir 'D:\projects\portfolio-v3': Permission denied
```

Can you verify the correct read/write permissions are set for that drive? Is this an external drive?

**Comment by ROOKIEsarthak** [comment]
No, it's not.
It's in my hard drive .
Can you please elaborate about the
Read / write permissions on the drive .

Thank you.

**Comment by steveward** [comment]
[This article](https://www.thewindowsclub.com/change-files-and-folders-permissions-in-windows-10) has some tips on resolving file/folder permissions on Windows. Feel free to share a screenshot of the permissions view if you need assistance.

**Comment by ROOKIEsarthak** [comment]
Issue solved. 
Thank you for your help
