### ISSUE TITLE
GitHub Desktop doesn't detect change in Unity Project

### ISSUE THREAD

**Issue by ItzK3ky** [desktop/desktop#15824]
### The problem

I am changing up scripts and prefabs in Unity and GitHub Desktop doesnt detect the changes. I therefore can't commit and push the changes.

### Release version

Version 3.1.2 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Open Unity project
2.  Change something in the project
3. See that GitHub Desktop says "0 changed files"

### Log files

N/A

**Comment by ItzK3ky** [comment]
I'm stupid I didnt open the right folder in Unity incase anyone in the future may have the same problem

**Comment by Cade6408** [comment]
> I'm stupid I didnt open the right folder in Unity incase anyone in the future may have the same problem

Wdym you didn't open the right folder, because my friend is having the same issues

**Comment by enlguy** [comment]
Same issue, and I'm in the correct folder.  Yesterday, it happened where I had to open and close GH Desktop several times before it recognized changes.  Now it's happening again, and it's not detecting changes at all.  I don't have permissions to reopen the issue, but don't see another ticket like this.  I hope someone at GitHub will reopen and explore this.
