### ISSUE TITLE
Host Disconnected

### ISSUE THREAD

**Issue by betawarrior12** [desktop/desktop#15822]
### The problem

I keep trying to push a branch to origin but it keeps saying "host disconnected check internet and try again"

### Release version

Version 3.1.2 (x64)

### Operating system

Windows 7

### Log files

[2022-12-26.desktop.production.log](https://github.com/desktop/desktop/files/10303437/2022-12-26.desktop.production.log)

**Comment by steveward** [comment]
@betawarrior12 thanks for the issue. It looks like the push is timing out. Are you still encountering this issue? 

This error is usually caused by network issues -- are you on a reliable network connection? Does this happen in multiple repositories?

**Comment by betawarrior12** [comment]
This problem doesn't occur anymore it was because of the file I was uploading was a mp4 file and some of the others were 20mb and above thanks for the feedback
