### ISSUE TITLE
Open PR in Desktop when Desktop is closed doesn't switch to the PR branch

### ISSUE THREAD

**Issue by Haacked** [desktop/desktop#1582]
Repro steps

1. Make sure `GitHub Desktop.exe` is not running.
2. Make sure the repository is already cloned locally and added to Desktop.
3. Click open PR in Desktop on a pull request. Here's [an example](x-github-client://openRepo/https://github.com/Haacked/todo-app?branch=design-changes-for-don).

Expected: `GitHub Desktop.exe` is launched, given focus, __and switches to the PR branch__.
Actual: `GitHub Desktop.exe` is launched, given focus, __and DOES NOT switch to the PR branch__.

Note that the branch switching works fine when `GitHub Desktop.exe` is already running. I did not test the case when Desktop is not running and the repository is not yet cloned.

version: 0.5.4
OS: Windows 10

**Comment by shiftkey** [comment]
@haacked is this a PR from a local branch or from a fork?

**Comment by Haacked** [comment]
Local branch.

**Comment by Haacked** [comment]
Note that it works fine when Desktop is already running.

**Comment by shiftkey** [comment]
@haacked I've not been able to trigger this on `0.5.5` - either for local branch or a forked repository. Do you see the fetch kick in after focusing the app? Maybe that's failing and we're unable to switch to the right branch...

**Comment by Haacked** [comment]
@shiftkey So here's a clue. When I Open PR for a repository that I haven't even cloned yet, it doesn't even attempt to clone it. It just launches Desktop and fetches for whatever happened to be the last selected repository.

**Comment by shiftkey** [comment]
Welp, looks like we're not tracking the details passed when the protocol handler is invoked on that initial launch:

<img width="349" src="https://cloud.githubusercontent.com/assets/359239/26229062/3110b764-3c82-11e7-921d-84a12ffc0e9d.png">

That would explain most of this behaviour.
