### ISSUE TITLE
Requires Authentication

### ISSUE THREAD

**Issue by OktayUrekli** [desktop/desktop#15838]
### The problem

I added a project to my github but ı can not second one . when ı click to publish repository ı take 'Requires Authentication' error. How can ı fix it.

### Release version

Version 3.1.2 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1.click to commit to main
2.  click to publish repository
3. 'Reauires Authentication' error

### Log files

[2022-12-28.desktop.production.log](https://github.com/desktop/desktop/files/10318071/2022-12-28.desktop.production.log)
[2022-12-29.desktop.production.log](https://github.com/desktop/desktop/files/10318072/2022-12-29.desktop.production.log)
[2022-12-27.desktop.production.log](https://github.com/desktop/desktop/files/10318073/2022-12-27.desktop.production.log)

### Screenshots

![Ekran görüntüsü 2022-12-29 101237](https://user-images.githubusercontent.com/99287769/209916707-696f1247-a844-45e3-ab8c-3291eb4acff8.png)

**Comment by OktayUrekli** [comment]
S.O.S

**Comment by tidy-dev** [comment]
Hi @OktayUrekli! It would appear you are not currently authenticated. I would suggest going to `File > Options` menu, Select the `Accounts` tab and under the `GitHub.com` heading click the `sign out` button and then click the `sign in` button to reauthenticate. Then try publish your repository again. Reach back out if this doesn't get it working for you.
