### ISSUE TITLE
cannot push anymore. Getting error

### ISSUE THREAD

**Issue by byblo** [desktop/desktop#15836]
### The problem

This is the error I get when trying to push my lastest commit using Github Desktop.
What is wrong?

`Enumerating objects: 15, done.
Counting objects: 100% (15/15), done.
Delta compression using up to 2 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 1.30 KiB | 190.00 KiB/s, done.
Total 8 (delta 7), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (7/7), completed with 7 local objects.        
remote: fatal: did not receive expected object e1edad554950cf2e8ea4f2a9f65468625372f316        
To https://github.com/byblo/Tomb1Main.git
 ! [remote rejected]   develop-difficulty -> develop-difficulty (failed)
error: failed to push some refs to 'https://github.com/byblo/Tomb1Main.git'`

### Release version

3.1.2 x64

### Operating system

Windows 7 x64

### Log files

[2022-12-29.desktop.production.log](https://github.com/desktop/desktop/files/10317604/2022-12-29.desktop.production.log)

**Comment by byblo** [comment]
Also, when trying to clone again I get this error:
`Cloning into 'E:\GitHub\Tomb1Main-develop-difficulty'...
remote: Enumerating objects: 24598, done.        
remote: Counting objects: 100% (985/985), done.        
remote: Compressing objects: 100% (530/530), done.        
remote: fatal: unable to read e1edad554950cf2e8ea4f2a9f65468625372f316        
remote: aborting due to possible repository corruption on the remote side.
fatal: early EOF
fatal: fetch-pack: invalid index-pack output`

**Comment by waspdscv** [comment]
#
[Uploading Google_Android_Security_2017_Report_Final.pdf…]()

**Comment by waspdscv** [comment]
> vacancies [,;;*(%$'$%&](ill-advised)

**Comment by steveward** [comment]
@byblo thanks for the report. Unfortunately it looks like the remote repository may be corrupt. You could try running `git fsck` in the local repository to see if that returns any errors, but I would recommend reaching out to [GitHub Support](https://support.github.com/) if there is a specific issue with the remote repository. I'm going to close this out, but feel free to follow up if there are any specific problems with GitHub Desktop that we can assist with.
