### ISSUE TITLE
GitHub Desktop won't let me add a local repository

### ISSUE THREAD

**Issue by MCpracticesforskills** [desktop/desktop#15834]
### The problem

I tried to add a local repository, but GitHub Desktop does not recognize the local folder as a Git repository. The **Add Repository** button is unclickable. It instead recommends creating a new repository.
<img width="1515" alt="Screenshot 2022-12-28 at 11 47 44 AM" src="https://user-images.githubusercontent.com/72710813/209864735-ecc9017c-878e-409d-ab2d-34c43ae88562.png">

### Release version

Version 3.1.2 (arm64)

### Operating system

mac OS Ventura version 13.0.1

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. Select File
3. Select Add Local Repository

### Log files

[2022-11-15.desktop.production.log](https://github.com/desktop/desktop/files/10316145/2022-11-15.desktop.production.log)

### Screenshots

<img width="396" alt="Screenshot 2022-12-28 at 11 53 38 AM" src="https://user-images.githubusercontent.com/72710813/209865340-b26a00ca-9ce0-4f99-9ec4-bf7df116e89b.png">

### Additional context

It is a react application created on my laptop.

**Comment by kvten** [comment]
This happens when the folder is missing 1 or more of the following:
- `.git` (folder)
- `.gitattributes` (single file)
- `.gitignore` (single file, not present if you haven't enabled it)

Since these are hidden files by default, you can show them on macOS by pressing "Cmd" + "Shift" + "." inside your folder.

If they're missing, click "create a repository" to create a new one.

**Comment by tidy-dev** [comment]
@MCpracticesforskills Exactly what @kenf1 said. You will likely need to create a repository out of the project folder.  I am closing this, but feel free to message back if that doesn't get things working.

**Comment by MCpracticesforskills** [comment]
Thank you. That worked 👍🏾

**Comment by enlguy** [comment]
Not helping me - I have a .gitignore and .gitattributes, but it keeps ignoring ALL the files, and trying to create an empty repo from a folder of hundreds of files.  It's not recognizing anything.
