### ISSUE TITLE
Open source the current OS X native app under a different name

### ISSUE THREAD

**Issue by dan-passaro** [desktop/desktop#1583]
Hi GitHub,

I'm not sure where to ask this question, but if you're open sourcing this new project and ending support for the native OS X app, please release the OS X app's source code with an open source license.

I am a huge fan of the OS X app, and as a developer, I would be happy to contribute patches to ensure the app continues functioning.  I am sure there are other OS X users who would also be interested in supporting the GitHub OS X client as a community project. Of course I expect this to require a rebranding; I humbly and lazily suggest "Macgit" as a name for an unsupported open source project that's disconnected from the GitHub brand.

I understand and empathize with the decision to use Electron to write cross platform desktop applications. I simply wish that, in light of this project being developed as open source, that you consider releasing the source code for the native OS X app as-is with no support, so the OS X user community can benefit from all the hard work that went into it and continue its development.

**Comment by rlabrecque** [comment]
Yeah that would be really cool. Might as well release the old windows one like this as well.

**Comment by niik** [comment]
Thank you for opening this, while we have no immediate plans to open-source the old clients we've heard your feedback and I imagine this is something we'll discuss internally. For now I'd like to keep this repository and its issues centered around the client that we're developing at the moment so I'm going to close this out.

Suggestions, bugs, etc about the old clients can be submitted through our [support form](https://github.com/contact)
