### ISSUE TITLE
Incorrect time in logs and commits.

### ISSUE THREAD

**Issue by 1337cookie** [desktop/desktop#15832]
### The problem

I just downloaded Github desktop and made a commit and merge and it appears to be the wrong time.  They show as 12 hours ago on the Github website. 

Start of the log file: `2022-12-27T18:16:39.933Z` which is UTC, my local time would've been +13. 

Commits I make through git cli or VSCode don't appear this way. 

### Release version

3.1.2 (x64)

### Operating system

Windows 10 

### Log files

[2022-12-27.desktop.production.log](https://github.com/desktop/desktop/files/10310270/2022-12-27.desktop.production.log)

**Comment by tidy-dev** [comment]
Hi @1337cookie, Would you mind providing screenshots of the commit that is wrong and how you expect to see it on Github.com?

**Comment by 1337cookie** [comment]
This commit was made at 7:25pm through github desktop. But you can see that it says 7:25am. I hadn't modified the file or made the commit any earlier than 7pm. 
![image](https://user-images.githubusercontent.com/15826769/210005403-49c15d1b-0e89-48df-af1f-78484234fe02.png)

Attempting to reproduce this morning at 6:44am it shows the correct time. 
![image](https://user-images.githubusercontent.com/15826769/210005547-3e9084af-e772-4587-b300-cdb8033a0369.png)

Perhaps this is limited to first launch after install or maybe only happens in conjunction with there being enough time since the last commit etc. That said, I've had no success reproducing this after uninstalling (and deleting appdir) and attempting to create commits or new repos. Feel free to re-open this if you find anything.
