### ISSUE TITLE
When gitlab token expires, can we have a way to re-authenticate?

### ISSUE THREAD

**Issue by michealroberts** [desktop/desktop#15844]
### The feature request

Currently, I use short lived Gitlab tokens to authenticate a repository on Github desktop. Today is the day one of my tokens has expired since using the IDE.

I have found that there seems to be no way to re-authenticate with a repository, instead it pop-up window shows to Open Preferences, which leads to a dead end.

<img width="603" alt="Screenshot 2022-12-30 at 12 13 05" src="https://user-images.githubusercontent.com/84131395/210069109-e814a4ba-06f5-4888-b94e-1c986e29a8f6.png">

Which takes me to this:

<img width="605" alt="Screenshot 2022-12-30 at 12 13 31" src="https://user-images.githubusercontent.com/84131395/210069147-dd75bd4c-507a-49d6-8866-a5c989579c6a.png">

Which is a dead-end as far as I can tell.

I've tried:

`git config --local --edit`

To see if I can update my token, but there doesn't seem to be any store of it.

Is there a way within the IDE to re-authenticate with an external provider that uses a token based password (or any password?)

Also, what would be the temporary workaround for authenticating?

### Proposed solution

If a username and password have been used to authenticate to a repo, when that password expires (or changes), the prompt should re-appear.

### Additional context

N/A

**Comment by tidy-dev** [comment]
Hi @michealroberts, unfortunately the error we receive for this is not specific enough to tell which problem on that error dialog is yours.

I sounds like the second bullet applies to you.
" - You may need to log out and log back in to refresh your token. "

Thus, you made it to right preferences screen, just need to click "Sign out" and then sign back in.
