### ISSUE TITLE
Clone Directory Messes Up When Changing URL

### ISSUE THREAD

**Issue by Look-Its-Sky** [desktop/desktop#15842]
### The problem

When adding 

### Release version

3.1.2

### Operating system

MacOS Ventura 13.1

### Steps to reproduce the behavior

1.) Clone from a URL
2.) Paste a URL and append two '/'s to the end of the URL
ex: 
Before - https://github.com/citra-emu/citra.git
After - https://github.com/citra-emu/citra.git//
3.) The clone directory should go back a folder each time a / is removed or added

### Screenshots

https://user-images.githubusercontent.com/67021158/210036453-a2881160-1e75-4c91-86ad-0aad6805de95.mp4

### Additional context

Also sorry if I did something wrong this is my first issue.

**Comment by Shivareddy-Aluri** [comment]
@tidy-dev @sergiou87 what should be done here?
we are using `dirname` in app/src/ui/clone-repository/clone-repository.tsx -> updateUrl .. 
in Unix when we give `dirname /Users/xyz/Documents/GitHub/desktop//` it will give the output directory as `/Users/xyz/Documents/GitHub` .
this shouldn't happen and we have to avoid it ?

**Comment by tidy-dev** [comment]
Without any investigation into current code, I would assume that we will want to sanitize the input from the repository URL before making modifications the the local path output. But, until this can be done, it is simple enough to tab down to the local path and modify it to whatever is your preferred target directory.

**Comment by Shivareddy-Aluri** [comment]
so should i fix it? @tidy-dev
