### ISSUE TITLE
Open with GitHub Desktop Does Not Auto-launch App on Apple Silicon

### ISSUE THREAD

**Issue by syntheticperson** [desktop/desktop#15852]
### The problem

I want to be able to use the Open with GitHub Desktop option on a github repo.  
<img width="501" alt="Screen Shot 2023-01-01 at 9 01 53 AM" src="https://user-images.githubusercontent.com/119148/210178988-ae493d5a-9f9a-4a2a-a1db-9ee19c91762e.png">

However, instead of launching the Github Desktop app, it takes me to the https://desktop.github.com/ webpage.

The Github Desktop app works on my Apple Silicon M1.  
<img width="1002" alt="Screen Shot 2023-01-01 at 9 04 42 AM" src="https://user-images.githubusercontent.com/119148/210179044-ccbee04c-53e5-4681-9c84-738c9f8d0efd.png">

I don't want to have to copy and paste the repo url each time, how to I get the app to auto-launch?

Thanks

### Release version

Version 3.1.2 (arm64)

### Operating system

macOS Monterey 12.4 (21F79)

### Steps to reproduce the behavior

1. Go to https://github.com/raman-at-pieces/youtube-bookmarker-starter-code
2. Left mouse the green Code button
3. Left mouse the Open with GitHub Desktop

<img width="443" alt="Screen Shot 2023-01-01 at 9 08 09 AM" src="https://user-images.githubusercontent.com/119148/210179149-8ab1620e-896c-4fef-b58f-d6c84744cfd8.png">

**Comment by syntheticperson** [comment]
Mysteriously, this started working.

**Comment by czerwinskilukasz1** [comment]
[SOLVED]

I experienced the same issue after installing GitHub Desktop on M3 – when I click on "Open with GitHub Desktop", it redirected me to https://github.com/apps/desktop , even though I already installed GitHub Desktop from this very page.
What did not work:
* Re-trying a couple of times
* Restarting Chrome.

What **worked**:
* Logging in into github.com. After that, it immediately started working:

<img width="1096" alt="Image" src="https://github.com/user-attachments/assets/5551d792-8488-4142-9930-a23f4fa6905c" />
