### ISSUE TITLE
Repository Crash

### ISSUE THREAD

**Issue by Jeshuwa422** [desktop/desktop#15850]
### The problem

I'm a beginner in software engineering the last eight weeks or so marks my study period in software engineering. I made several mistakes that kept me stagnate in my course of study. Im strange to the workings of Github Desktop. I open gitbash and in the process open several gitbash terminal on my system. After completing my assigned task project and made effort to commit the project to my git. The process failed and I try to get the exist key for vi on the terminal. This also failed. I guess I crudely closed the terminal.

For hours I battled with the project it was not working. Later, I worked on it again and tried to push the project to my git from my external terminal. The response is that I can not commit because either there is a repository running or the repository in my gitbash have crashed. I checked for which repository is running simultaneously with the project work at hand. I couldn't.

Please this is the **_Bug I encountered, which state my repository has crashed_**. I don't how to resolve it, how can it be solved. This is my email. ukutajoshua@gmail.com  

Below is the screenshot response. ![Uploading IMG_20221231_042954_356.jpg…]()

This are the usernames on my github Jeshuwa22 and Jeshuwa422.

Thank you. 

### Release version

December 2022 version

### Operating system

Window 10

### Screenshots

![Uploading IMG_20221231_042954_356.jpg…]()

### Additional context

below the Screenshort is the response recieved.

**Comment by steveward** [comment]
@Jeshuwa422 thanks for the issue. Unfortunately it looks like your image didn't finish uploading to make it through.

Could also you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment in this issue from a day where you experienced the crash.

**Comment by Jeshuwa422** [comment]
I have uninstalled the GitHub desktop from my laptop system when it
happened during that holiday period when I running behind class schedules
and deadline.

I can't trace it, again. It was GitHub 32 version. It was a difficult for
me that time. All the options available for me is to uninstall the that
version and if possible by+pass GitHub desktop.

Presently, I want to join the two accounts on GitHub that I created into
one . Jeshuwa22 and Jeshuwa422. I don't know how to do that.


Thank you Sir

**Comment by steveward** [comment]
@Jeshuwa422 it isn't possible to join two accounts, but you can transfer repositories. 

https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

You can reach out to [GitHub Support](https://support.github.com/) if you have further questions.
