### ISSUE TITLE
cloning repository fails, but git CLI clone does it successfully

### ISSUE THREAD

**Issue by perdigao1** [desktop/desktop#15856]
### The problem

I just tried to do a cloning of a fork of a project

https://github.com/perdigao1/reikna

and it fails with an error message related to folder /doc/source/_themes @ 0700f0f . It could be that the folder is trying to clone as an unusual name with '@' character, but there is something else unusual

In the command line, running `git clone  https://github.com/perdigao1/reikna.git` runs successfully.

### Release version

3.1.12

### Operating system

Windows 11

### Steps to reproduce the behavior

As described in

**Comment by steveward** [comment]
Thanks for the report @perdigao1. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by perdigao1** [comment]
[2023-01-03.desktop.production.log](https://github.com/desktop/desktop/files/10387222/2023-01-03.desktop.production.log)

**Comment by steveward** [comment]
@perdigao1 I'm seeing an interesting error in the log file:

```
Cloning into 'C:/Users/Luis-work/Desktop/Others/Reikna_fork/reikna/doc/source/_themes'...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.3]: errno=Unknown error
```

Any chance you have antivirus or other security software on this machine, or are behind a restrictive proxy/firewall? It looks like something is blocking the connection from completing, and we've often seen cases where GitHub Desktop binaries get flagged and cause issues like this. Do other network operations succeed in GitHub Desktop (i.e. fetch/push)?

**Comment by perdigao1** [comment]
I am happy to provide more details if needed. My major concern is that this website is fully public and I should not provide security details about my personal PC. Is there is a more private and trustworthy channel?
The problem may be the fact that is a windows 11 machine. In the past I had a few weird issues and different behaviour compared with windows10

**Comment by steveward** [comment]
@perdigao1 are you still having issues cloning from GitHub Desktop?
