### ISSUE TITLE
PR preview modal opens PRs to fork instead of upstream

### ISSUE THREAD

**Issue by advaith1** [desktop/desktop#15866]
### The problem

When clicking "Create Pull Request" in the preview modal, it creates a PR to the main branch in the fork repository, instead of the main branch in the upstream repository. When creating the PR without previewing, it works properly.

correct URL: https://github.com/advaith1/discord-api-docs/pull/new/thread-member-ids-preview (PRs to upstream/main)
wrong URL: https://github.com/advaith1/discord-api-docs/pull/new/main...thread-member-ids-preview (PRs to fork/main)

The settings should make it create in the upstream:
![image](https://user-images.githubusercontent.com/11778454/210705002-a990aea9-c453-4fb7-9600-5c8bf8915114.png)

### Release version

Version 3.1.3-beta4 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Have a fork repo set up in the "contribute upstream" mode
2. Make a branch, make a commit, and publish it
3. In the blue suggestion box, click "Preview Pull Request"
4. In the modal, click "Create Pull Request"

### Screenshots

Wrong behavior:
![image](https://user-images.githubusercontent.com/11778454/210705515-b5aa9905-d81c-40a9-b353-74ae3c249187.png)
![image](https://user-images.githubusercontent.com/11778454/210705534-4f780175-f8e8-480c-83dd-306d7fe8aaf1.png)

Correct behavior:
![image](https://user-images.githubusercontent.com/11778454/210705582-1d6f8964-c72e-43f0-80f6-d3ffcc5d1f99.png)
![image](https://user-images.githubusercontent.com/11778454/210705477-91aaf350-b56b-4799-a627-6c29baf70440.png)
![image](https://user-images.githubusercontent.com/11778454/210705491-c443f1f7-4b65-44b5-947c-0f008ffb976d.png)

**Comment by sergiou87** [comment]
Thank you for your report! @tidy-dev made some fixes around this in #15754 , so I'll assign the issue to her

**Comment by steveward** [comment]
I'm going to close this out as this no longer appears to be an issue. @advaith1 if you're still encountering any edge cases around this please let us know!
