### ISSUE TITLE
Github Desktop Cloning

### ISSUE THREAD

**Issue by UmaMaheswariGajjarapu-EATON** [desktop/desktop#15869]
Hello, 
Whenever I try to clone from github.com to github desktop it is asking for credentials. I am unable to login with my credentials.

Thankyou,
Uma

**Comment by steveward** [comment]
@UmaMaheswariGajjarapu-EATON thanks for the issue. You shouldn't need to enter your credentials in GitHub Desktop, as authentication is done via browser flow. See [this guide](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/installing-and-authenticating-to-github-desktop/authenticating-to-github) for authentication steps. If you run into issues let us know.
