### ISSUE TITLE
Third-party plugin support?

### ISSUE THREAD

**Issue by andrewhong04** [desktop/desktop#15867]
### The feature request

Visual Studio Code supports external plugins such as themes, tools, etc. I think that GitHub Desktop would benefit from supporting such plugins as well.

### Proposed solution

A more personalized experience will happen if this feature gets implemented.

**Comment by yks-ny** [comment]
htt[]() ps://gcs.amateur-engineer-blog.com/2021/05/c4c1b723-title-logo.png

**Comment by steveward** [comment]
Thanks for the issue @novialriptide. This has been previously discussed in https://github.com/desktop/desktop/issues/1718, but at this time it isn't something we have planned to do. I'm going to close this out to help keep our issue tracker manageable, but it may be something we revisit again in the future. Thanks for using GitHub Desktop.
