### ISSUE TITLE
Cannot install MSI package in Windows 10

### ISSUE THREAD

**Issue by cesar1791** [desktop/desktop#15868]
### The problem

I´ve downloaded the MSI package GitHubDesktopSetup-x64.msi and run it. Some dialog window opens for few seconds showing some progress bar and disappears. I don´t get any error messages, but nothing seems to be installed. 

### Release version

GitHubDesktopSetup-x64.msi

### Operating system

Windows 10

**Comment by steveward** [comment]
Thanks for the report. To get some more information about why the installation is failing it would be helpful if you could send over the log file that the Squirrel installer generates.

You should be able to find the log file here:

`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`

If no log file is being generated there you should be able to find one in the `SquirrelTemp` directory:

`%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

Please upload that in this issue as an attachment.

**Comment by primer97** [comment]
@steveward there are no %LocalAppData%\GitHubDesktop\ or %LocalAppData%\SquirrelTemp folders at all, I run the MSI installer, and it disappears after 1 second. 
There is something that prevent your installer to complete and your installer does not provide any information, so on one can answer your question.

**Comment by steveward** [comment]
@primer97 those directories will be `C:\Users\<Your_user>\AppData\Local\GitHubDesktop` or `C:\Users\<Your_user>\AppData\Local\SquirrelTemp`. 

Are you running any antivirus or other security software that could be causing this?
