### ISSUE TITLE
Cannot switch to different branch using GitHub Desktop

### ISSUE THREAD

**Issue by czharinasp** [desktop/desktop#15863]
### The problem

When attempting to switch to a different branch, GitHub Desktop froze up and nothing happens. 
I've already done Turtoise CVS -> Cleanup, but to no avail.
Please find attached log file.

### Release version

3.1.2

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Go to Current Branch
2. Switch branch

### Log files

[2023-01-04.desktop.production.log](https://github.com/desktop/desktop/files/10344998/2023-01-04.desktop.production.log)

**Comment by steveward** [comment]
@czharinasp thanks for the report. It looks like there is an index.lock file that is preventing the checkout:

```
fatal: Unable to create 'D:/CAE/CrewManagement/.git/index.lock': File exists.
```

Deleting that file should resolve this issue. Let me know if that doesn't get things working!
