### ISSUE TITLE
Command Failed error upon opening app

### ISSUE THREAD

**Issue by AnnaSLRomero** [desktop/desktop#15865]
### The problem

I open the Github Desktop app and immediately this error pops up and every single one I close pops up with another one. Up to a specific error it closes and then the desktop is open, but now it is asking me to publish a branch that I have not created. This error then keeps popping up again once I have clicked through all these errors when I just minimize the tab.

I had the regular mac OS version, but I thought this might have been the problem so I deleted it and re-installed it but the problem still happened. Then I decided to use the apple silicon version and still the problem persisted.

### Release version

Version 3.1.3-beta4 (arm64) and the non apple silicon version

### Operating system

mac OS Ventura 13.0.1

### Log files

2022-12-04T03:45:53.302Z - info: [ui] [BranchPruner] Last prune took place 23 hours ago - skipping
2022-12-04T07:30:14.148Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 1.548s)
2022-12-04T15:03:33.704Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 1.068s)
2022-12-04T18:52:02.036Z - info: [ui] [BranchPruner] No branches to prune.
2022-12-04T18:52:02.285Z - info: [ui] Stats reported.
2022-12-04T21:16:06.406Z - warn: [ui] getFetchPollInterval: failed for AnnaSLRomero/PSYCH505
TypeError: Failed to fetch
    at Mt (/webpack:/[name]/app/src/lib/http.ts:152:10)
    at Sn.request (/webpack:/[name]/app/src/lib/api.ts:1401:28)
    at Sn.getFetchPollInterval (/webpack:/[name]/app/src/lib/api.ts:1439:35)
    at Eo.getFetchInterval (/webpack:/[name]/app/src/lib/stores/helpers/background-fetcher.ts:136:38)
    at Eo.performAndScheduleFetch (/webpack:/[name]/app/src/lib/stores/helpers/background-fetcher.ts:117:33)

### Screenshots

<img width="1440" alt="Screenshot 2023-01-04 at 12 16 58 PM" src="https://user-images.githubusercontent.com/73443036/210683103-84b7122b-6d9b-4751-a8cf-003b7a08f327.png">
<img width="1440" alt="Screenshot 2023-01-04 at 12 17 01 PM" src="https://user-images.githubusercontent.com/73443036/210683109-6ed61c16-77fe-4f42-a0f6-69a60d131bdd.png">
<img width="1440" alt="Screenshot 2023-01-04 at 12 17 04 PM" src="https://user-images.githubusercontent.com/73443036/210683110-31bed0d8-e287-4776-b9c8-e3812b751293.png">
<img width="1440" alt="Screenshot 2023-01-04 at 12 17 06 PM" src="https://user-images.githubusercontent.com/73443036/210683113-761feee5-bb88-45ab-ba34-b448f3f573fc.png">
<img width="1440" alt="Screenshot 2023-01-04 at 12 17 08 PM" src="https://user-images.githubusercontent.com/73443036/210683115-73413f74-ebfd-491e-ba13-4b7b109900dc.png">
<img width="1440" alt="Screenshot 2023-01-04 at 12 17 10 PM" src="https://user-images.githubusercontent.com/73443036/210683117-81ec9744-3ff9-4277-8760-41339fd86081.png">
<img width="1440" alt="Screenshot 2023-01-04 at 12 17 11 PM" src="https://user-images.githubusercontent.com/73443036/210683120-b80686a8-cd11-42d0-b9f0-e665c664059f.png">
<img width="1440" alt="Screenshot 2023-01-04 at 12 17 13 PM" src="https://user-images.githubusercontent.com/73443036/210683121-df72e68b-da85-4bfd-88b2-ac147f722dd9.png">
<img width="1440" alt="Screenshot 2023-01-04 at 12 17 15 PM" src="https://user-images.githubusercontent.com/73443036/210683123-7b2819fd-8739-45c9-b926-20f7d0a08cdf.png">
<img width="1440" alt="Screenshot 2023-01-04 at 12 17 37 PM" src="https://user-images.githubusercontent.com/73443036/210683124-a08f5376-a55a-41c8-8728-80262b7c5f5b.png">
<img width="1440" alt="Screenshot 2023-01-04 at 12 17 40 PM" src="https://user-images.githubusercontent.com/73443036/210683125-d020fb06-4b5c-4613-8411-1706a00c2b42.png">
<img width="1440" alt="Screenshot 2023-01-04 at 12 17 41 PM" src="https://user-images.githubusercontent.com/73443036/210683127-3e843d88-c679-4115-adce-34f79a06157f.png">
<img width="1440" alt="Screenshot 2023-01-04 at 12 17 44 PM" src="https://user-images.githubusercontent.com/73443036/210683129-d7417ad8-88e4-4ec6-908e-7dd5989dc559.png">
<img width="1440" alt="Screenshot 2023-01-04 at 12 17 46 PM" src="https://user-images.githubusercontent.com/73443036/210683131-283bb4dc-a635-4504-83fe-17f335bd9c6e.png">
<img width="1440" alt="Screenshot 2023-01-04 at 12 17 48 PM" src="https://user-images.githubusercontent.com/73443036/210683132-6fca69a7-933e-4e6c-ad6b-1fd71dd11b9e.png">
<img width="1440" alt="Screenshot 2023-01-04 at 12 17 49 PM" src="https://user-images.githubusercontent.com/73443036/210683134-88f1d45b-5692-4093-a7cf-1bdd95095589.png">
<img width="1440" alt="Screenshot 2023-01-04 at 12 17 51 PM" src="https://user-images.githubusercontent.com/73443036/210683136-54cff59e-9072-4cf6-a614-86e686326d2a.png">
<img width="1440" alt="Screenshot 2023-01-04 at 12 17 53 PM" src="https://user-images.githubusercontent.com/73443036/210683137-44d300b6-2926-4b13-8a86-c875ffba5b36.png">

**Comment by steveward** [comment]
@AnnaSLRomero thanks for the report. Would you mind uploading the entire log file from GitHub Desktop from a day you experienced this issue? Thanks!

**Comment by AnnaSLRomero** [comment]
Hi Steve,

This is the log on the day:
[2023-01-04.desktop.beta.log](https://github.com/desktop/desktop/files/10396605/2023-01-04.desktop.beta.log)
[2023-01-04.desktop.production.log](https://github.com/desktop/desktop/files/10396606/2023-01-04.desktop.production.log)

**Comment by steveward** [comment]
This does look like an app installation issue. Can you also try fully reinstalling the app to see if that helps?

1. Close GitHub Desktop
2. Delete all of the files located in `~/Library/Application Support/GitHub Desktop/`
3. Fully reinstall GitHub Desktop
