### ISSUE TITLE
Deleted branch from Desktop is still linked to an issue

### ISSUE THREAD

**Issue by overjoied** [desktop/desktop#15874]
### The problem

I have created a branch from an issue. When I realized I have the wrong source, I deleted it from Github Desktop both locally and remote. The branch was deleted, but it still appears as a linked branch to the issue. Although, when you click the branch it redirects to 404 page. 

Is there a way to remove the branch entirely?

### Release version

Version 3.1.3 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

Assuming you have created a branch linked to an issue.

1. Create a branch from an issue.
2. Delete the branch (both local and remote) from the Github Desktop.

**Comment by steveward** [comment]
@overjoied thanks for the issue. I'd recommend asking this in the [community forum](https://github.com/community) or by reaching out to [GitHub Support](https://support.github.com), as this is not a specific issue with GitHub Desktop.
