### ISSUE TITLE
Handle diff of doc/docx / xls/xlsx / pdf

### ISSUE THREAD

**Issue by Malimalo** [desktop/desktop#15875]
### The feature request

Hi, i'm using Github Desktop to manage text-files but also doc/docx, xls/xlsx and pdf files.
It would be very useful to allow Github Desktop to show somehow the diff of such files inside the interface instead of the generic note "This binary file has changed".
It is available for pictures (ex: png) with the display of the previous version and the new version of the picture directly in the Github desktop.

### Proposed solution

I don't know.

**Comment by qingzhiku** [comment]
您好，您的邮件，我已经收到的，O(∩_∩)O谢谢！

**Comment by steveward** [comment]
Thanks for the request @qingzhiku. Diffing these types of files requires external tools, and we are tracking support for that in https://github.com/desktop/desktop/issues/1765. You can follow along there for updates. I'm going to close this out.

**Comment by mbyt** [comment]
@steveward thanks for the info. If tracking support for external diff tool is tracked in #1765 , why is the status of #1765 "closed" and not "open"?

**Comment by TheColonel2688** [comment]
@steveward Why does the official documentation say that PDFs are supported?  https://docs.github.com/en/repositories/working-with-files/using-files/working-with-non-code-files#rendering-pdf-documents

I have tried it the client treats PDFs as simple binary files.

**Comment by steveward** [comment]
@TheColonel2688 that documentation is for GitHub the website, which can render PDFs. GitHub Desktop does not support this.
