### ISSUE TITLE
Configurable button in branch bar

### ISSUE THREAD

**Issue by Tilation** [desktop/desktop#15876]
### The feature request

Would be nice to have an optional button or buttons next to the fetch button, as that part of the GUI is quite empty, and could be beneficial for large projects.

The buttons should be configurable per user, or saved in the repository so everyone have the same button when cloning the repository.

### Things that can be configured:
- Button name
- Button description
- Button Icon
- Button action / command:
  - Open a file with the default program.
  - Run a script.

### Proposed solution

The branch toolbar is mostly empty, having custom actions up there could improve the collaborative experience, some commands that come to mind are:
- Custom local security / integrity / analyzer checks before pushing to origin.
- Opening complex projects.

### Example
A button that opens a sln with visual studio, with a hearth icon.
![image](https://user-images.githubusercontent.com/48564654/211029199-d9762d2a-8bde-4af4-958c-afbd8421730c.png)

**Comment by steveward** [comment]
Thanks for the request @Tilation. We've had similar requests in the past for custom actions (see https://github.com/desktop/desktop/issues/5336 for example), but at this time this isn't something that we're planning to focus on implementing in GitHub Desktop. We may reconsider this again in the future, so thanks for letting us know you'd like to see this implemented.
