### ISSUE TITLE
Unknown error continously

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#15879]
### The problem

Git returned an unexpected exit code '3221225477' which should be handled by the caller (getStatus).'

### Release version

Version 3.1.3 (x64

### Operating system

Win 11

### Log files

[2023-01-06.desktop.production.log](https://github.com/desktop/desktop/files/10361778/2023-01-06.desktop.production.log)

### Screenshots

![Uploading git issue.png…]()

**Comment by steveward** [comment]
@Kiran-rgs thanks for the report. I'm seeing a number of access/permission denied errors in the log file. 

```
error launching git: Access is denied.
```
```
    0 [sh] sh 309 dofork: child -1 - CreateProcessW failed for 'C:\Users\Black Wizard\AppData\Local\GitHubDesktop\app-3.1.3\resources\app\git\usr\bin\sh.exe', errno 13
/mingw64/libexec/git-core/git-sh-setup: fork: Permission denied
```

Has this error just recently started occurring? Are there any restrictions on your machine or antivirus/security software that could be causing GitHub Desktop to be prevented from working correctly?

**Comment by ghost** [comment]
Actually, I reset my window and it upgrades to win-10 to win-11. After that it causes issues.
I'm not aware of Antivirus/OS restrictions.
________________________________

**Comment by steveward** [comment]
Could you try performing a fresh installation of GitHub Desktop by following these steps?

Here's how to do that:

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `%AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that helps at all.

**Comment by ghost** [comment]
Hello,
I tried the suggested steps. After signing in, while cloning the repository gives the below error message.


Img 1 -- This Repo was successfully created. but give this error while pulling or fetching changes.
[cid:eb3bea6b-706f-485f-9023-5069187e225a]

img 2 -- while cloning another branch.
[cid:73d20dd0-d1c8-4a0c-a447-7c6c970f3478]
________________________________

**Comment by steveward** [comment]
Unfortunately your screenshots didn't make it through since email replies do not support screenshots. Are you able to upload them directly to this issue, or share the output?

**Comment by ghost** [comment]
Hello Steve,
I think it's because of Organisation security I can't attache screenshot to outer email.

So here is some error messages:

  1.  While clone branch

Cloning into 'D:\7. Work\4. Extrapreneursindia\RGS Git Codebase\rgs-cms-frontend-application'... remote: Enumerating objects: 3249, done.         remote: Counting objects: 100% (259/259), done.         remote: Compressing objects: 100% (188/188), done.         fatal: fetch-pack: invalid index-pack output

Would you like to retry cloning rgs-cms-frontend-application?


  1.  While pull changes.
 Unknown error


  1.  Git returned an unexpected exit code '3221225477' which should be handled by the caller (getStatus).'


________________________________

**Comment by steveward** [comment]
That looks like the clone is failing. Can you try cloning the repository that is failing via the command line with more verbose output to see if we can trace where it is failing?

`GIT_TRACE=1 git clone <repository_URL>`

You also mentioned organization security -- is it possible something else in your network is causing this?

**Comment by ghost** [comment]
Before it's working fine with Win-10. I thinks it's related something Win-11. Now able to clone somehow but still giving "Unknown error" message.
________________________________

**Comment by steveward** [comment]
@Kiran-rgs I have a Windows 11 machine that is working without issue, so I think there is a specific permission/security issue on your machine that is causing this. I would recommend reaching out to someone in your organization to see if there is anything that could be causing these errors. We've seen everything from antivirus to group policy settings cause issues like this.

**Comment by Rafasac** [comment]
A mi me aparece el error en un equipo con Windows Server
![Error desconocido Github](https://github.com/desktop/desktop/assets/30601624/2b343c83-82c5-4149-adde-80ddf8f90a82)

**Comment by dampetlagithub** [comment]
sir anybody help me because of  GitHub also same error occurring

**Comment by dampetlagithub** [comment]
![Screenshot (26)](https://github.com/desktop/desktop/assets/151711989/3d2bfd6e-f9cc-4f26-a0f0-7ac0f9990577)

**Comment by steveward** [comment]
@dampetlagithub please open a new issue and fill out the template if you're still encountering this error. Thanks!
