### ISSUE TITLE
Shortcut to open a new command prompt

### ISSUE THREAD

**Issue by xt0rted** [desktop/desktop#1587]
### Description

In the native version you could press <kbd>`</kbd> to open your preferred command prompt  of choice. I'd like to see this return as it's much easier than using the Repository > Open command prompt menu.

### Version

**GitHub Desktop version:** 0.5.4
**OS version:** Win10 Creators Update (10.0.15063)

**Comment by shiftkey** [comment]
@desktop/core first off, feels on making a keyboard shortcut for "Open in Terminal"/"Open in command prompt"?

**Comment by Haacked** [comment]
I feel we should give it a shot! I know it may have platform specific complications, but if we can dream it, we can code it! 😄

**Comment by shiftkey** [comment]
@Haacked :thumbsup: but the next question I had was whether we wanted it to be <kbd>`</kbd> or something more formal...

**Comment by manparvesh** [comment]
Hi all,
As I mentioned in #1545, I think if there is a tab in the settings window for setting the keyboard shortcuts, it would be better to let the user choose the shortcut for a terminal by themselves. What do you think?

**Comment by rlabrecque** [comment]
Definitely let the user choose, defaulting to ` seems fine though. Are there platform issues with this? It should just call the same function as open-in-shell basically.

**Comment by Haacked** [comment]
> but the next question I had was whether we wanted it to be <kbd>`</kbd> or something more formal...

![why-not-both](https://cloud.githubusercontent.com/assets/19977/26182766/1c266d16-3b2f-11e7-86e1-0a3d17bcad07.gif)

I always saw <kbd>`</kbd> as an alias to the formal command, which we also had.

Also, I believe the "Doom Mode" keyboard shortcut was @shanselman's favorite feature of Desktop and if we don't bring it back, he'll hunt us down. For the PR value of Scott demoing it all the time, it's worth it to me. 😄

**Comment by shiftkey** [comment]
@rlabrecque 

> Definitely let the user choose, defaulting to ` seems fine though. 

Let's talk about overriding this in #1545 and focus this issue on giving this menu item a keybinding.

> Are there platform issues with this? 

We choose keyboard shortcuts based on what feels appropriate for each platform. On the macOS side this maps to <kbd>Command + T</kbd> and it doesn't handle <kbd>`</kbd> at all.

@haacked

> I always saw <kbd>`</kbd> as an alias to the formal command, which we also had.

For reference, I'm pretty sure this was <kbd>F5</kbd> or <kbd>F8</kbd> or both?

> For the PR value of Scott demoing it all the time, it's worth it to me. 😄

That's fine. I just wanted to ensure we were setting up something consistent for both platforms.

**Comment by joshaber** [comment]
This was done in https://github.com/desktop/desktop/pull/2385.
