### ISSUE TITLE
CLion support

### ISSUE THREAD

**Issue by PiedrasAi** [desktop/desktop#15881]
### The feature request

When is CLion support being added to desktop?  Thanks!

### Proposed solution

CLion is the IDE to use for Rust, C, and C++. It has a debugger built in. It will benefit the Rust Programmers.

**Comment by steveward** [comment]
Thanks for writing in. At this time GitHub Desktop only supports editors that have been specifically integrated into the application. You can find the details of how this works along with the supported editors here:

https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md

CLion should be supported on Windows, but it looks like support has not yet been added on macOS.
