### ISSUE TITLE
Improve how Visual Studio Code is being detected

### ISSUE THREAD

**Issue by Booplicate** [desktop/desktop#15885]
### The feature request

It seems GitHub Desktop relies on registry to check if VSC has been installed. Not every installation process adds the keys to the registry, I could add those myself, but I don't think that would be a good solution. I think this is excessive and complicates the whole process. I want to propose to instead use `PATH` to check if VSC is available (like how git does it). Maybe even being able to just specify the path directly via a dialog.

### Proposed solution

Check if Visual Studio Code is in `PATH` when trying to find the editor in the system.

**Comment by steveward** [comment]
Thanks for the issue @Booplicate, you can follow along in https://github.com/desktop/desktop/issues/14666 for updates about editor detection improvements. I'm going to close this out.

**Comment by Booplicate** [comment]
Missed that one, it's pretty much what I wanted, yeah. Hope to see it soon, thanks for your work.
