### ISSUE TITLE
Different behavior for diff-across-commits, oldest-newest vs newest-oldest

### ISSUE THREAD

**Issue by keitherskine** [desktop/desktop#15883]
### The problem

Diff across commits ( #14682 ) is great (many thanks!), but I appear to be seeing a difference in behavior depending on the order in which I select the range of commits.  For the exact same contiguous range of commits in a branch, if I select the oldest commit first and then shift-select the newest commit, I get the differences I would expect.  On the other hand, if I select the newest commit first and then shift-select the oldest commit, I sometimes get a different set of file differences.  In the second case, I often get a message about "unreachable commits".  (I suspect the issue might be related to merge commits.)

Is this expected behavior?  It would seem odd to get a different result when the same range of commits is selected, regardless of how that range was selected.

### Release version

Version 3.1.3 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Using the panel on the left that shows the History of a branch as a series of commits in a vertical list, newest at the top.
2. Click on a commit, the commit turns blue.
3. Shift-click on an earlier commit (above the first commit), the range of commits between the two selected commits turns blue and the file differences are shown in the main panel.  Note those file differences.
4. For the same range of commits, click on the earlier (higher) commit first, then shift-click on the older (lower) commit.  The same commits as before should turn blue and the file differences are shown in the main panel.  Note the differences.

In my experience, those two sets of file differences are not always the same.

**Comment by tidy-dev** [comment]
@keitherskine Thanks for report. We had a [fix for another range selection](https://github.com/desktop/desktop/pull/15549) bug a while back. I suspect there may be a regression here.
