### ISSUE TITLE
Problem with repository using both submodules and git LFS.

### ISSUE THREAD

**Issue by mcDandy** [desktop/desktop#15886]
### The problem

I got some files missing on repository which uses both git lfs and submodules

### Release version

3.1.2

### Operating system

Windows 11

### Steps to reproduce the behavior

We will setup [Thrive](https://github.com/Revolutionary-Games/Thrive) here. [Setup guide for thrive](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/setup_instructions.md)

1. make sure you have all files (I did full setup) (I had commit a28bf33e72c58470ff7ca1b3abd48272d1e28f02 or before before I discovered this)
{
git clone --recursive https://github.com/Revolutionary-Games/Thrive
// I am not sure if submodule update was the problem, I do not know how to setup it as if it was cloned on that comit
git submodule update --init --recursive
}
2. Setup the project to be able to tell missing image assets
3. update using GUI and switch to radiotrophy branch
4. run Thrive (Godoot or Thrive might crash for the first time becouse missing assets)
5. switch to master
6. Try starting new game in thrive (did that thru auto-evo exploring tool after 100 generations)

### Log files

[2023-01-07.desktop.production.log](https://github.com/desktop/desktop/files/10368008/2023-01-07.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the issue @mcDandy. Unfortunately we don't have the bandwidth to debug specific issues with setups like this, but if you're able to share a specific error or bug we can investigate further. We recently made a number of submodule improvements, and GitHub Desktop should update submodules on checkout (see https://github.com/desktop/desktop/pull/15240). 

Could you check if `git submodule update --init --recursive` resolves the issue?
