### ISSUE TITLE
Ability to make the file list wider

### ISSUE THREAD

**Issue by xt0rted** [desktop/desktop#1588]
### Description

I'm running on a 27" 4k @ 150% scaling and the electron version of the app generally feels smaller than the old native version. For the most part this isn't an issue but for things like the file list the maximum width is half that of the native version. I'd like to be able to make this wider now that the file paths are no longer shown in the wider portion of the window.

![image](https://cloud.githubusercontent.com/assets/831974/26182158/35fa2d12-3b44-11e7-9850-0226ec2230ea.png)

According to the dev tools this is set to  `350px`, I'd like to see a max width closer to `600px`. I'm also noticing the file sorting isn't the same between both versions, not that that really matters.

![image](https://cloud.githubusercontent.com/assets/831974/26182312/64a7498c-3b45-11e7-84de-5b4bb3208b29.png)

### Version

**GitHub Desktop version:** 0.5.4
**OS version:** Win10 Creators Update (10.0.15063)

**Comment by shiftkey** [comment]
> I'm also noticing the file sorting isn't the same between both versions, not that that really matters.

Happy to look into this in a separate issue if you want to put together a repro of it.

**Comment by xt0rted** [comment]
Comparing the two versions shows that the old version scaled that list. So if the window was up to 50% the width of my screen it would max out at ~350px, but as the window got wider it would also get wider until at full width it was at ~600px. Having it be able to auto size like that would be awesome.

**Comment by joshaber** [comment]
I've actually wanted this too 👍

**Comment by niik** [comment]
For anyone who'd like to take a stab at this the `Resizable` component for the file list lives in [repository.tsx](https://github.com/desktop/desktop/blob/432738e426f83c309375291f0d5da86132f167ae/app/src/ui/repository.tsx#L111-L122) and it [supports overriding the maximum width](https://github.com/desktop/desktop/blob/432738e426f83c309375291f0d5da86132f167ae/app/src/ui/resizable/resizable.tsx#L7-L11) making for an excellent first contribution!

**Comment by rlabrecque** [comment]
Any downside to having the maximumWidth set to window.innerWidth / 2?
That feels more natural to me. Two problems when trying it out: If you resize the window then it doesn't resize the Resizable until the window loses focus, and the `sidebar-section` toolbar button doesn't update until you manually resize the Resizable.

**Comment by shiftkey** [comment]
> Any downside to having the maximumWidth set to window.innerWidth / 2?

I'd relax this even more, like VSCode does. Here's how far you can drag their sidebar:

<img width="1051" src="https://cloud.githubusercontent.com/assets/359239/26299659/e3547338-3edb-11e7-9c13-f2c48fa013a5.png">

My only concern would be if the diffs look squashed, but I'll leave it up to others to test this out to see if there's a sweet spot.

**Comment by rlabrecque** [comment]
My initial feeling was to set it to window.innerWidth - (the_size_of_toolbar_buttons * 2). So yeah, something like that could work as well.

**Comment by joshaber** [comment]
As per https://github.com/desktop/desktop/issues/1816, we're 👍 on increasing the max size:

>Also agree that we should allow a larger maximum width for the file list / sidebar. In the short term, let's allow the sidebar to be resized until there's no more space. We'll set a max width so that the branch and push/pull buttons aren't squished horizontally. In the long term, we can determine the max width dynamically based on how much space we need to fit information in the branch and push/pull button.

**Comment by hjobrien** [comment]
I figure the maxWidth of this component should be overridden in [repository.tsx](https://github.com/desktop/desktop/blob/master/app/src/ui/repository.tsx) but I'd like to make the max width equal to the `window.innerWidth - (<branch button width> - <push/pull button width>)` but I'm a little new to tsx/jsx so I was wondering if there is a sensible way to access those widths in `repository.tsx`. I'm thinking the right way would be to add a prop to RepositoryView.

**Comment by j-f1** [comment]
I like how DevDocs handles truncation in this case.

By default, the content is truncated:
<img width="369" alt="not hovered" src="https://user-images.githubusercontent.com/25517624/28435783-7acf00ac-6d62-11e7-8dac-582425d8cf33.png">

However, when hovering over the item, it expands to show the full text, “breaking out” of the list
<img width="369" alt="hovered" src="https://user-images.githubusercontent.com/25517624/28435782-7ac73d18-6d62-11e7-8bad-2916a2bf29e4.png">

Since the full title is displayed elsewhere in the window when the file is selected, this behavior only works when the item isn’t selected.

**Comment by mastef** [comment]
As mentioned in #2440 - Is there any reason for the maximumWidth being `495` actually? This is not wide enough for my use-case. There's a lot of space for the diff, which is unused, but I can't read the long filenames in the tiny left-side list. Would be great to not have an arbitrary maximum width - or just make it 80% of the window or something. I'd like to decide myself how wide I want that list, or if I want to focus on the diff.

![githubdesktop](https://user-images.githubusercontent.com/762297/30390870-b074c1ec-98e1-11e7-9c6b-4f3566914eb7.png)

**Comment by mastef** [comment]
Especially since the path display cuts off _both_ in the middle of the path with some `...` and cuts off the end of the filename as well with `....` - why?

**Comment by niik** [comment]
> As mentioned in #2440 - Is there any reason for the maximumWidth being 495 actually? This is not wide enough for my use-case. There's a lot of space for the diff, which is unused, but I can't read the long paths in the tiny left-side list. Would be great to not have an arbitrary maximum width - or just make it 80% of the window or something. I'd like to decide myself how wide I want that list, or if I want to focus on the diff.

See https://github.com/desktop/desktop/issues/1816#user-content-wider-file-list

> we should allow a larger maximum width for the file list / sidebar. In the short term, let's allow the sidebar to be resized until there's no more space. We'll set a max width so that the branch and push/pull buttons aren't squished horizontally. In the long term, we can determine the max width dynamically based on how much space we need to fit information in the branch and push/pull button.

In other words, the reason that maxWidth is 495 is that it was the quickest way to alleviate some pain users had by allowing them a sidebar wider than 350px. We have nothing at all against a dynamic calculation of the max width but that required a little bit more engineering effort as we'd have to ensure that the sidebar resizes when the window width shrinks and scales back up when the window width expands. We'd love to see a PR that deals with the dynamic resize and allows for resizing the sidebar up to the point where the toolbar buttons still fit.

> Especially since the path display cuts off both in the middle of the path with some ... and cuts off the end of the filename as well with .... - why?

So they definitely shouldn't be doing that and I'm unable to reproduce it locally. Here's what it should do

![ellipsis](https://user-images.githubusercontent.com/634063/30418437-3c9e8aee-9933-11e7-871d-75e18394db0b.gif)

I'd love to get to the bottom of that, could you please open an issue about it and add some details about your setup? In particular I'd like information about your display resolution and DPI settings.

**Comment by lcucurachi** [comment]
I think this should be reopened. The changed files list is not resizable anymore. I find it hard to review changes when I cannot see the full filenames.

**Comment by chyde80** [comment]
> I think this should be reopened. The changed files list is not resizable anymore. I find it hard to review changes when I cannot see the full filenames.

same here

**Comment by niik** [comment]
@chyde80, @LoKKeR96 please open a new issue describing the behavior you're seeing. The changed files list is definitely still resizable so there must be something else going on in y'all's setup

**Comment by chyde80** [comment]
using latest chrome, no special extensions that would interfere, I see no way to resize the file list. Am I being stupid? I would expect to be able to drag the area near the scroll bar to widen or narrow it.

**Comment by niik** [comment]
@chyde80 Ah, I see where the confusion stems from. This is the repository and issue tracker for GitHub Desktop. I believe what you're referring to is the web interface of GitHub.com. Please visit our [GitHub Community Discussions](https://github.com/orgs/community/discussions/) to leave feedback on the website.

**Comment by chyde80** [comment]
ah, yes you are correct. I'm sorry, I'm referring to the file list in a PR on github.com

**Comment by lcucurachi** [comment]
@chyde80 for reference, I posted a request here https://github.com/orgs/community/discussions/67849
Would be helpful if you upvoted it.
