### ISSUE TITLE
CipherTrust Manager issue with a valid SSL certificate

### ISSUE THREAD

**Issue by maxtzd** [desktop/desktop#15894]
Hey everyone,

I just setup Client-side encryption with Google Workspace and and the software called CipherTrust Manager from Thales.
The CipherTrust Manager's software is a Virtual Machine on Google Cloud created by Thales. The default web interface is in https but with an autosigned certificate. I would like to put my own certificate and get a secure solution for our client. 

there is no shell access possible, we can only use the section "external CA" from the web interface.

I used these commands to create 2 certificate with certbot with challenge DNS-01 verification

`sudo certbot certonly --manual --preferred-challenges dns -d "cse.htc.ageona.fr"`

`sudo certbot certonly --manual --preferred-challenges dns -d "*.ageona.fr"`

The commands above worked and gave me those files 'cert.pem' 'chain.pem' 'fullchain.pem' 'privkey.pem'.

As you can see i generated a certificate for cse.htc.ageona.fr, this is a redirection with AAA type who redirect the client on the virtual machine.
And a wildcard certificate.

My question is, where should I put my file on the CipherTrust Manager Software to get my website secure, should I convert my cert into another extension or am I missing something ?

Thanks for your help I hope I send all the necessary informations !

**Comment by steveward** [comment]
@maxtzd this issue tracker is for GitHub Desktop, it looks like you are looking for support for a different project. I'm going to close this out.

**Comment by maxtzd** [comment]
Okay my bad sorry if i'm bothering you
