### ISSUE TITLE
Infinite loading loop during fetching and pushing

### ISSUE THREAD

**Issue by martenjurgens** [desktop/desktop#15899]
### The problem

I started encountering the issue a week ago where I couldn't fetch/push in a certain repository, but after trying to fix it by uninstalling Github Desktop completely I'm now unable to fetch/push in all of my repositories.

Fetching will just get stuck in an infinite loop and I'm unable to push any changes. Pushing/pulling only works using CMD.

### Release version

3.1.3 (x64)

### Operating system

Windows 11 Pro

### Steps to reproduce the behavior

1. Press fetch in any repository
2. Get stuck in infinite loop

### Log files

[2023-01-10.desktop.production.log](https://github.com/desktop/desktop/files/10380743/2023-01-10.desktop.production.log)

### Screenshots

![fetch](https://user-images.githubusercontent.com/55079581/211506377-673982d3-93c2-4311-8cf9-e43b42aab436.png)

**Comment by steveward** [comment]
Thanks for the report @martenjurgens. Are you behind a proxy or firewall? Are you running any antivirus or other security software on your machine that could be interfering with GitHub Desktop?

**Comment by martenjurgens** [comment]
@steveward Not behind any firewalls or proxies, and no antivirus or other security software either. It started happening overnight.

**Comment by steveward** [comment]
Thanks -- I'm only seeing this error in the log:

```
2023-01-10T08:46:10.094Z - warn: [ui] getFetchPollInterval: failed for avar3d/showroom-admin
TypeError: Failed to fetch
```

Unfortunately that doesn't give us much to go on. If you're interested you could go to `View` > `Toggle Developer Tools` and take a look at the `Console` and `Network` tabs during attempting a fetch operation to see if anything shows up there that could give a better indication of what specifically is failing. Let me know if that shows anything interesting.
