### ISSUE TITLE
Use the OS-native title bar.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [desktop/desktop#15898]
### The feature request

Use the title bar that is native to the operating system.

### Proposed solution

This shall improve consistency.

### Additional context

There's no benefit to drawing your own. At least provide the option.

**Comment by niik** [comment]
This issue lacking important information like which operating system you're using. Without outlining the benefits of using a native window frame or a comparison/analysis between the two approaches this is not actionable. Generally speaking the Desktop application uses custom components where we deem those necessary for the aesthetic or functionality of the application.

**Comment by RokeJulianLockhart** [comment]
@niik, I really, really don't want to be annoying, but aren't the advantages rather obvious?
1. Visual consistency;
2. Space to move the title-bar that isn't replaced by functional objects that prevent movement, such as, in GitHub Desktop's case, the menu bar; and
3. The ability to use the icon to close it via double-click, which is currently prevented.

I didn't want to encompass these as merely “accessibility”, because although that might have worked, it seemed disingenuously non-specific. However, those are all obviously concerns for accessibility.

I hope that that has supplemented the request enough for you to consider reopening it.

@yereverluvinunclebert

**Comment by RokeJulianLockhart** [comment]
@niik, this isn't specific to any one OS, and I use multiple. Should I just put the newest? I didn't state an OS because I didn't want this to solely apply to one OS.
