### ISSUE TITLE
Usability issue - Scroll bar overlaps with drop down button on MAC OS

### ISSUE THREAD

**Issue by ittaibaratz** [desktop/desktop#15895]
### The problem

When merging our main branch having a long list of changes, I found it hard to click the drop down button because the scroll bar often overlaps with it. This might be a MAC OS specific issue:

![image](https://user-images.githubusercontent.com/1454683/211386398-a81116d6-039e-409f-88dc-cc0349ecfac7.png)

Not a high priority problem, but would be nice to have them not overlap as this adds time when going through a long list of conflicts. 

Thank you!

### Release version

3.1.3

### Operating system

MAC OS Ventura 13.1

### Steps to reproduce the behavior

1. Merge a branch with a long list of conflicts
2. Scroll through the conflicted files on MAC OS
3. Observe scroll bar overlaps with the drop down.

### Screenshots

![image](https://user-images.githubusercontent.com/1454683/211386398-a81116d6-039e-409f-88dc-cc0349ecfac7.png)

**Comment by steveward** [comment]
Thanks for the report @ittaibaratz, this is being tracked in https://github.com/desktop/desktop/issues/6199 so you can follow along there for updates.
