### ISSUE TITLE
Files aren't sorted the same as in the native version

### ISSUE THREAD

**Issue by xt0rted** [desktop/desktop#1589]
### Description

Carrying this over from #1588. The file list isn't sorting the same as in the native version. At first it seemed like a number of files were different but after going through some commits it looks like it's just the first two in this image. I'm guessing it's how the file extensions are handled between the two versions. As mentioned in the other issue, I don't think this is really matters but I'm bringing it up in case there really is something wrong.

![image](https://cloud.githubusercontent.com/assets/831974/26182158/35fa2d12-3b44-11e7-9850-0226ec2230ea.png)

### Version

**GitHub Desktop version:** 0.5.4
**OS version:** Win10 Creators Update (10.0.15063)

**Comment by shiftkey** [comment]
@xt0rted i'm feeling a bit lazy - is there a public commit I can use to dig into this and see what's changed between the two?

**Comment by xt0rted** [comment]
That repo is private but I found a public one with similar files https://github.com/zelbar/CAPIS/commit/29a4fa020b1041f92763bc91b0e2da9d83c732dc

**Comment by shiftkey** [comment]
>  As mentioned in the other issue, I don't think this is really matters but I'm bringing it up in case there really is something wrong.

I thought this was due to how we were computing the diff, but these two methods return the same output on my test environment.

The classic Windows app does this to get the files listed in a commit:

```
 git diff-tree f0072e2d21d02fe942bb79491a1ee626e11d98df^{tree} f0072e2d^^{tree} --name-status -r
```

The new Electron app does this:

```
git log f0072e2d21d02fe942bb79491a1ee626e11d98df -C -M -m -1 --name-status
```

Closing this out as it's minor (and we're not going to go back and fix this in the classic app).
