### ISSUE TITLE
Add contrasting 1 pixel thick window border.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [desktop/desktop#15896]
### The feature request

Add a contrasting 1 pixel thick window border to differentiate between the window and other windows for when shadows are disabled via ms-settings:easeofaccess-display or when using the classic theme of Windows 7.

### Proposed solution

This shall allow the window to be discerned despite removal of such differentiators.

### Additional context

Ideally, this should be unnecessary, because this software should not override the DWM, but it appears to even draw its own window controls, so this is the next best approach.

**Comment by steveward** [comment]
Thanks for the request @rokejulianlockhart, I'll add this to https://github.com/desktop/desktop/issues/1585.
