### ISSUE TITLE
Merging branches not merging all files and changes.

### ISSUE THREAD

**Issue by MrPixel101** [desktop/desktop#15893]
### The problem

When merging branches. not all files will be seen as conflicting or changed. as well as newly added files not being merged into the branch.

### Release version

Version 3.1.3 (x64)

### Operating system

Windows 10

**Comment by steveward** [comment]
Thanks for the issue @MrPixel101. Unfortunately we won't be able to assist without further information. Can you share some screenshots and further details of the issues you are experiencing?

**Comment by MrPixel101** [comment]
@steveward. I was able to temp fix it by creating a new branch and manually transferring files to it other than the .git folder. from what I can recreate it is that when you attempt to revert changes of a merge it locks that file to no longer be seen as conflicting/edited when merging.

**Comment by steveward** [comment]
Glad to hear things are working now.
