### ISSUE TITLE
 Description of a tag

### ISSUE THREAD

**Issue by DuverneyOrtiz** [desktop/desktop#15900]
### The feature request

When creating a tag it would be essential to add a text box to create a description of the tag.
![image](https://user-images.githubusercontent.com/32425795/211575448-42b7bd0c-494e-456d-a6a3-8a01773e6871.png)

### Proposed solution

Allows clarity on what has been done in each of the versions of the tag

**Comment by steveward** [comment]
Thanks for the feedback @DuverneyOrtiz, I'm going to add this to https://github.com/desktop/desktop/issues/12995.
