### ISSUE TITLE
Support for Projects

### ISSUE THREAD

**Issue by BIEMAX** [desktop/desktop#15901]
### The feature request

Would be interesting if we have support for GitHub projects in desktop application. This could be useful to SCRUM master's, AGILE or even product manager/owner.

![image](https://user-images.githubusercontent.com/47108057/211578008-7ba68e0a-a718-4503-a71a-0d3fb7ee0805.png)

### Proposed solution

-Allow users and manager to control their own projects, with issues, tasks and delivery dates.
-Allow manager to create and manage milestones and projects.

**Comment by steveward** [comment]
Thanks for the feedback @BIEMAX, I'll add this to https://github.com/desktop/desktop/issues/12791 where we are tracking support for Projects in GitHub Desktop.
