### ISSUE TITLE
Use mine / theirs option for conflicts?

### ISSUE THREAD

**Issue by farhanWM** [desktop/desktop#15908]
### The feature request

I mostly use Sourcetree for my projects but I have to use Github Desktop for my current project. In my experience using Sourcetree, when there is a conflict, you could just right click and select to resolve using my version versus their version. 

I wish Github has this feature. It would make life easier. I read some people mention to use editor to resolve conflicts. But, I am working with Unity scene files and you cannot just use an editor to resolve conflicts. 

So to have the option to use mine versus theirs like in Sourcetree, would be helpful. So that people could choose which version to use for the current commit. And then, they can manually merge or readd the missing items that cause the conflicts in the first place after. 

Currently, there is only an option to discard and it will discard all new changes without letting us to select to use the new version as the resolution for the commit.

### Proposed solution

Added Use mine / theirs option for any conflicts as alternative to an actual merge.

**Comment by steveward** [comment]
Thanks for the issue @farhanWM. You should see the option to select ours/theirs in the dropdown:

<img width="453" alt="Screenshot 2023-01-12 at 11 10 55 AM" src="https://user-images.githubusercontent.com/721500/212120912-b71478e8-d636-43b8-a74e-23f0f916fe3d.png">

Let me know if you have any questions about this!

**Comment by farhanWM** [comment]
Both of devs are using the same branch and the other person pushed their changes, and then I just pull those changes to merge into my local files. After I pull, the file turned into a broken/conflicted file. No pop up like in your screenshot appears. Right click on the conflicted file, doesn't reveal any options like above. I could only revert changes which makes all of my local changes gone.
