### ISSUE TITLE
Fetch origin show upto date even it has changes to pull

### ISSUE THREAD

**Issue by ArunKumar-webdev** [desktop/desktop#15906]
### The problem

Take pull from origin and change to different folder still its show upto date.
![image](https://user-images.githubusercontent.com/69241947/211799426-b32c4f20-a9f4-4c07-b88e-475b438af747.png)

### Release version

Version 3.1.3 (x64)

### Operating system

windows 11

### Steps to reproduce the behavior

Take pull from origin and change to different folder still its show upto date.

### Screenshots

![image](https://user-images.githubusercontent.com/69241947/211799645-fa1c808d-b9ea-42e3-8003-edfd613d537c.png)

**Comment by steveward** [comment]
@ArunKumar-webdev thanks for the issue. I'm not sure I understand -- are you changing branches or changing repositories when you say "change to different folder"? You will need to confirm that changes exist on the remote repository.  If you can share further details and screenshots I can assist you further, but at this time there are no known issues with fetching so I am going to close this issue out.
