### ISSUE TITLE
ERROR: Cannot read properties of undefined

### ISSUE THREAD

**Issue by tseflcz** [desktop/desktop#15904]
### The problem

I met an error that Cannot read properties of undefined (reading 'replace') after my anti-virus software attack the GitHub Desktop. Then I add GitHub Desktop to white list, and it dos not work when I launch Desktop again. I still met the same error and can not use the Desktop. Desktop report this error when I make each action, and I cannot publish my branch.

### Release version

3.1.3 (x64)

### Operating system

Windows 10 22H2

### Steps to reproduce the behavior

1. vrv anti-virus software attack the GitHub Desktop
2. add GitHub Desktop to white list and launch again
3. report the error that Cannot read properties of undefined (reading 'replace')

### Log files

[2023-01-11.desktop.production.log](https://github.com/desktop/desktop/files/10388342/2023-01-11.desktop.production.log)

### Screenshots

<img width="307" alt="uTools_1673403446006" src="https://user-images.githubusercontent.com/66352689/211703617-a6f269d9-4f7f-460c-a0d2-e528207fc594.png">

**Comment by steveward** [comment]
Thanks for the report. Based on the log file it does look like there are issues with your installation. Can you try performing a fresh installation by following these steps?

Here's how to do that:

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `%AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that does not get things working.

**Comment by tseflcz** [comment]
Thanks for your reply. I tried following these steps you suggested, but unfortunatrly it does not work.
After Reinstall GitHub Desktop, the error doe not appear immediately. But it occured once I cloned my repository from the Internet, or add a existing repository from my PC.

**Comment by steveward** [comment]
Thanks for the update. When you whitelisted GitHub Desktop did you include these two specific directories?

`%AppData%\GitHub Desktop`
`%LocalAppData%\GitHubDesktop`

If you only whitelisted the specific application file then that could be the cause of the continuation of this problem.

**Comment by tseflcz** [comment]
Well, I exactly included these two specific directories when I whitelisted GitHub Desktop. However, these two specific directories locate a little differently than what you provided. I do not know if this counts, but I just lauched GitHub Desktop automatically and did not choose where to launch.
%AppData%\Roaming\GitHub Desktop
%AppData%\Local\GitHubDesktop

**Comment by steveward** [comment]
The specific directories should be this:

`C:\Users\<User>\AppData\Local\GitHubDesktop`
`C:\Users\<User>\AppData\Roaming\GitHub Desktop`

I'm also seeing this error in the log file:

```
2023-01-11T01:53:45.810Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
```

It also looks like something in your network could be blocking GitHub Desktop as well, so I would recommend looking into that as well if you are still encountering issues.
