### ISSUE TITLE
Custom title bar doesn't respond to action on double-click

### ISSUE THREAD

**Issue by mnquintana** [desktop/desktop#1590]
### Description
The custom title bar doesn't respond to double-clicks on macOS.

### Version
**GitHub Desktop version:** 0.5.4
**OS version:** macOS Sierra 10.12.5

### Steps to Reproduce

1. Double click on the title bar
1. Nothing happens

**Expected behaviour:** The window either maximizes, minimizes, or does nothing based on the user's `AppleActionOnDoubleClick` setting.

**Actual behaviour:** Nothing happens on double click

**Reproduces how often:** Always

**Comment by shiftkey** [comment]
Atom and VSCode seems to handle this fine, so perhaps this is on us to handle. Marking it as up-for-grabs` - if someone can find the code that does this for either project they're more than welcome to have a go at applying that here.

**Comment by rlabrecque** [comment]
Just tried this on Windows and it works fine here, so OSX label?
