### ISSUE TITLE
Stash in Github dekstop

### ISSUE THREAD

**Issue by ujsain** [desktop/desktop#15912]
### The feature request

I accidentally overwrite a stash in a branch in GITHUB DEKSTOP. Is there any way to recycle my progress . I explored some solutions but they were using git bash not desktop. I think deleted files move in recycle bin .But i am not able to find it.

### Proposed solution

So What I want is a button named("View Stash History"). And it will magically locate to recycle bin or place where it is in pc.

**Comment by steveward** [comment]
Thanks for the issue @20032006. You should be able to recover the stash -- you will need to find the log file from the day this happened. You can access the log by going to `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

Then you will want to search for a line like this:

` [ui] Dropped stash 'b947c54873415d875d5e4e0d941c443716e1c81e' associated with main`

You can then copy that SHA and run the following command from the command line:

`git stash apply b947c54873415d875d5e4e0d941c443716e1c81e`

That should recover the lost changes. I hope that helps!
