### ISSUE TITLE
Github Desktop won't show branches from repo

### ISSUE THREAD

**Issue by rehtse-studio** [desktop/desktop#15914]
### The problem

The are newly created branches on the repo, I'm using bitbucket, and when I got and changed branches on the GitHub desktop the branch is not there.  I cannot find it.  This has never happened before

### Release version

Version 3.1.3 (x64

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Create a new brach on your repo
2. try and find it on the GitHub desktop branch

### Log files

[2023-01-12.desktop.production.log](https://github.com/desktop/desktop/files/10402277/2023-01-12.desktop.production.log)

### Screenshots

![GitHubDesktop_oZhhUFT4sd](https://user-images.githubusercontent.com/75736387/212087680-a9b58eab-746c-4bb7-8936-e8cf6e8a2699.png)
![brave_VdfVrj8HjH](https://user-images.githubusercontent.com/75736387/212087686-f7097a83-316f-4273-98bc-d0fc0c805d5f.jpg)

**Comment by tsvetilian-ty** [comment]
Hey @rehtse-studio thanks for reaching out! The first screenshot shows that the last fetch was 17 hours ago, and the second (from bitbucket) shows that the last commit was 12 hours ago. Could you try to click "Fetch origin" and then try to search for the branch?

**Comment by rehtse-studio** [comment]
.....................................................
Yep.................... that fixed it 😳
🙈😳
My apologies, Thank you for helping me😊.

Learning something new every day😁

**Comment by steveward** [comment]
Glad to hear things are working now!
