### ISSUE TITLE
change name of repository in desktop app

### ISSUE THREAD

**Issue by Damianv7** [desktop/desktop#15916]
### The feature request

it should be poseable to easly change name of repository on desktop app. 
there are some weird options but i do not see change name option in conteks menu and even in setings
f2 also is not working

i'm happy its working good, but it reminds little bit this stupid git comands grrr 

### Proposed solution

there should be change name option in schrout - f2, settings and even in contex menu

**Comment by tsvetilian-ty** [comment]
@Damianv7 👋 You could use "Create alias" to create a name alias for the repo. I hope that helps!
