### ISSUE TITLE
Adding in Git-flow

### ISSUE THREAD

**Issue by JenuelDev** [desktop/desktop#15911]
### The feature request

It would be awesome if theirs a way to easily create branches like in the git flow. Here is a cheat sheet you might able to get an idea of how it works. [https://danielkummer.github.io/git-flow-cheatsheet/cheat sheet idea](https://danielkummer.github.io/git-flow-cheatsheet/)

### Proposed solution

As you all know projects have development and master/main branch. With the git-flow, it can help us easily create a deployment, bugfix, or feature additions.

**Comment by steveward** [comment]
Thanks for the issue @BroJenuel. This has been previously discussed in #2139, and is something we haven't prioritized yet but may consider down the road. It's a very specific workflow that we would need to consider, and ensure we're not making the UX significantly poorer for those who don't use this workflow. Thanks for letting us know you'd like to see this!
