### ISSUE TITLE
add local repository should have autosuggestions/completion

### ISSUE THREAD

**Issue by rlabrecque** [desktop/desktop#1591]
Basically just typing D:\ would show you a drop down selectable list of folders under it.

**Comment by shiftkey** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

It's also relatively isolated from the rest of the application, so it would be ideal if someone wanted to have a go at implementing this. I'll tag this as `help wanted` if someone wants to explore this further.

**Comment by billygriffin** [comment]
Thanks for the idea! Given that we haven't seen this come up as a pain point for others and nobody has picked it up, I'm going to close it. As always we aren't opposed to revisiting, and thanks again.
