### ISSUE TITLE
Checkout Git Tags

### ISSUE THREAD

**Issue by HesseM** [desktop/desktop#15913]
### The feature request

Similiar to switching out branches i would like to have an option to checkout git tags 

### Proposed solution

i want to be able to switch to a release version of my repository. i have one repository for a library where i need to swtich between different releases depending on the situation.

**Comment by steveward** [comment]
@HesseM you can create a new branch off of a tagged commit by right-clicking on the commit in the `History` view and selecting `Create Branch from Commit`. I hope that helps!

**Comment by HesseM** [comment]
@steveward i would like to only checkout the tag without creating a branch
