### ISSUE TITLE
Nonresponsive after conflict occurs during commit

### ISSUE THREAD

**Issue by greglindquist** [desktop/desktop#15938]
### The problem

Within the last 1-2 weeks, the 'merge conflicts' dialog will pop up, but nothing is clickable. If I restart github deskop, the options become clickable again.

### Release version

 3.1.3

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Commit code to branch that already has updates and the update contains changes to one of the files you're about to push.
2. Push to branch and wait for the 'merge conflicts' dialog to pop up. My pop up has vs code as the default editor to handle conflicts. 
3. One this dialog shows, nothing is clickable, however; hover states still work.

### Log files

[2023-01-15.desktop.production.log](https://github.com/desktop/desktop/files/10421190/2023-01-15.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @greglindquist. I'm seeing the conflicts in the log file, but also this error:

```
2023-01-15T20:46:45.734Z - error: [ui] Could not load old contents for syntax highlighting
RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
```

This is similar to a report in https://github.com/desktop/desktop/issues/15486 where Git operations were hanging with the same error. Does this happen in multiple repositories? Is the repository this is happening in a large repository?

**Comment by greglindquist** [comment]
Hey @steveward  - really good questions! I've only noticed it in 1 of the repositories and admittedly is pretty big with lots of images. I'll try a few others and see if I can recreate it in a few of the smaller ones we maintain. Thanks!

**Comment by steveward** [comment]
@greglindquist following up again here to see if you have been able to reproduce this. Thanks!

**Comment by greglindquist** [comment]
Hey @steveward  - sorry for the delay. I have not been able to within the last month or so. Thanks!
