### ISSUE TITLE
SSH issue?

### ISSUE THREAD

**Issue by AP-Engineering** [desktop/desktop#15933]
### The problem

error: Load key "C:\\Users\\*****\\AppData\\Local\\Temp/.git_signing_key_tmpiAZKkJ": invalid format?

fatal: failed to write commit object

### Release version

3.1.3 x64

### Operating system

windows 10

### Steps to reproduce the behavior

1 'make a change to the repository'
2 'commit to master'
3 'error'

**Comment by steveward** [comment]
@AP-Engineering thanks for the report. This issue is being tracked in https://github.com/desktop/desktop/issues/15302. If you need a workaround you can switch to using a GPG key, which should work without issue. I'm going to close this out.

**Comment by Okudajohnoke** [comment]
Ok how can it work here anytype
