### ISSUE TITLE
中文

### ISSUE THREAD

**Issue by auspiceshirley** [desktop/desktop#15942]
### The feature request

能选择GitHub的语言吗？我英语不是很好。

### Proposed solution

增加语言模块。或者安装语言插件。

**Comment by sergiou87** [comment]
Thanks for the suggestion @peishiyue0217! At this time we do not have language localization in GitHub Desktop, but this is something that we would like to do in the future. I don't have a timeline for when that may happen as it would require quite a bit of work by the team. I'm sorry that I don't have better news at this time.
