### ISSUE TITLE
Pressing enter in the commit summary doesn't create the commit

### ISSUE THREAD

**Issue by xt0rted** [desktop/desktop#1594]
### Description

Pressing <kbd>Enter</kbd> in the summary box doesn't create the commit while <kbd>Ctrl</kbd> + <kbd>Enter</kbd> does. In the native version both would create the commit.

### Version

**GitHub Desktop version:** 0.5.4
**OS version:** Win10 Creators Update (10.0.15063)

**Comment by shiftkey** [comment]
> In the native version both would create the commit.

I think this one was just some inconsistent behaviour we've cleaned up.

I'm not quite sure where we ended on this discussion, but I'll let @desktop/core chime in on their memories.

**Comment by joshaber** [comment]
I don't feel strongly either way :shrug:

**Comment by radumg** [comment]
* As a user :*
We used to have to resort to pressing `Shift`+`Enter` to introduce a new line in the classic environment.
The new behaviour is what I would have expected and a much simpler workflow.

**Comment by SidneyNemzer** [comment]
In the native version, `Enter` would create the commit if the summary input was focused. If the description was focused it would create a new line.

I'm so used to hitting `Enter` in the summary box. It would be great if `Ctrl` + `Enter` vs just `Enter` in the summary box was configurable at least.

**Comment by donokuda** [comment]
I would rather keep the current behavior where hitting Enter doesn't submit the form.

Having <kbd>Ctrl</kbd> + <kbd>Enter</kbd> as an explicit submit command prevents any confusion of what hitting <kbd>Enter</kbd> (and <kbd>Shift</kbd> + <kbd>Enter</kbd>) does with other fields (such as the description.)

If the argument for having <kbd>Enter</kbd> create a commit is that the previous version originally did this, then I'm 👎 on changing this behavior given that it doesn't currently block a workflow.

**Comment by niik** [comment]
I agree with @donokuda, this was an inconsistency between the platforms and while unlearning muscle memory is hard we do believe that this is the better of the two routes. I'm going to close this issue but thanks to everyone who contributed to the discussion!

**Comment by alandball** [comment]
In the old Github for Windows it would commit on enter. Slack sends message on enter(by default), and so does WhatsApp and a plethora of other apps. I'm liking the new look, but haven't yet uninstalled the native client, and might be using it after testing the new app for the day.

@niik "Unlearning muscle memory is hard" will be impossible when all the other apps are still submit on enter. If a setting could be provided, it would be great!

**Comment by steveward** [comment]
Mentioned by @omzy83 in https://github.com/desktop/desktop/issues/4481:

>However if you think about how forms work on webapps, pressing enter in an input field will normally submit the form.
>
>Could we at least have an option?
