### ISSUE TITLE
New repo creation path inconsistent depending on method used

### ISSUE THREAD

**Issue by adamlui** [desktop/desktop#15943]
### The problem

When creating a new repo using File > New repository, then choosing root folder of intended repo contents as "Local path" > Create repository, a subdirectory is created instead.

However, if creating a new repo using File > Add local repository, then choosing same root folder as "Local path" and clicking "create a repository" in the warning it's not a Git repository > Create repository, the .git folder/files are created directly in the selected path.

### Expected behavior

1st method should create .git folder/files exactly in selected path to be consistent w/ 2nd method's identical action button (it even warns you to try adding repo if it detects .git folder/files in the exactly selected path, so there's no reason to strangely create them using a subpath if the selected one is the one even being validated)

### Release version

3.1.3 (x64)

### Operating system

Windows 10 Home version 22H2 build 19045.2364 experience 120.2212.4190.0

**Comment by steveward** [comment]
Thanks for the issue @adamlui, this is being tracked in https://github.com/desktop/desktop/issues/9651 so I will add this feedback there where we are tracking refactoring these flows.
