### ISSUE TITLE
Stashes being lost

### ISSUE THREAD

**Issue by ChrisSargent** [desktop/desktop#15947]
### The problem

In the last week, I have seemingly successfully stashed two independent (large) changes on their individual branches which when later returned to have not been there.

There is nothing in the GH desktop logs to say that the stashes ever took place but even when I do a stash now, there is no entry in the log until I restore the stash.

In addition, I have not found anything in the git logs (using reflog etc.) which was related to my stashes.

I figured the first time was probably some error by me but after than experience, I've been extra careful with my stashes and now it has happened again.

### Release version

3.1.3 (x64)

### Operating system

macOS Monterey 12.6.2

### Log files

[2023-01-13.desktop.production.log](https://github.com/desktop/desktop/files/10429908/2023-01-13.desktop.production.log)

**Comment by steveward** [comment]
@ChrisSargent thanks for the report. Did you also try running a `git stash list` from the command line to check if any stashes were shown there? 

If the stash was accidentally discarded it should also be recoverable, see my [comment here](https://github.com/desktop/desktop/issues/15912#issuecomment-1380608475) about this.

>In addition, I have not found anything in the git logs (using reflog etc.) which was related to my stashes.

Stashes aren't shown in the reflog , but you can run `git reflog show --all` to include them, if that's helpful.

**Comment by ChrisSargent** [comment]
@steveward thanks for your reponse. After further investigation I discovered an overzealous `clean` script that was doing

```sh
find . -type d -name logs -exec rm -rf '{}' +
```

It was intended to only clean testing log files but ofc it was also removing the `logs` folder from the `.git` folder.

I will close this issue but one thing I'm confused on is why the stashes didn't appear in the Github application logs...
