### ISSUE TITLE
Show repository path in title bar

### ISSUE THREAD

**Issue by zspitzer** [desktop/desktop#15952]
### The feature request

It would be really useful to have the path of the repository on the title bar

I'm aways hovering over the the repository name to see the path to the repository, as I a maintainer for an open source project and have multiple copies of the same repo checked out ( for different releases )

### Proposed solution

Either show the path next to the repo name in the menu, or path on the title on the main menu

**Comment by steveward** [comment]
Thanks for the request @zspitzer. This has been previously discussed in various issue, but at this time we don't have plans to make this change. I'd recommend using aliases (right-click on repo -> `Create Alias`) to differentiate between local repositories of the same name.
