### ISSUE TITLE
Clarification: Is this officially made by GitHub? Does it work with non-github repos?

### ISSUE THREAD

**Issue by neoneye** [desktop/desktop#15955]
### The feature request

The name says `GitHub Desktop`. 

Can I trust that it's made by GitHub/Microsoft?

Does it only work with github? What about non-github repos, such as bitbucket, gitlab.

### Proposed solution

Make it more clear if it's a GitHub product, or not related to GitHub products.

If it's being made by GitHub/Microsoft, is it a dedicated team that is working on it. Is it 5 developers, 10 developers or more.

If it's not being made by GitHub, is it a solo developer, or only by open source pull-requests.

Explain if it works with bitbucket, gitlab?

### Additional context

I'm looking for an alternative to SourceTree that is less crash prone.

How serious is `GitHub Desktop`. Is it a good replacement. There is no tree branch visualization, so I'm concerned if I should be doing git merges with this tool. There is no grouping of repos. It doesn't remember my preferences, if I tap `History`, then it's forgotten when I switch to another repo.

Clarifying if it's made by GitHub/Microsoft, then I would be less concerned.

**Comment by niik** [comment]
Hi @neoneye, thanks for reaching out! Yup, GitHub Desktop is an official GitHub application developed by us here at GitHub and community contributors from all over! The first version of GitHub Desktop was called GitHub for Mac and [shipped over 11 years ago!](https://github.blog/2011-06-22-announcing-github-for-mac/) You can see an overview video of the product on [GitHub's YouTube page](https://www.youtube.com/watch?v=l7uo1d3R0Wo).

You can download it from https://desktop.github.com, the documentation lives on [docs.github.com](https://docs.github.com/en/get-started/using-github/github-desktop) and it's listed on [GitHub's Feature page](https://github.com/features) (alongside our other client apps like CLI and Mobile).

> Explain if it works with bitbucket, gitlab?

For non-GitHub endpoints GitHub Desktop functions as a Git client, meaning you can push, pull, fetch, commit, merge etc. When used with GitHub.com functionality specific to GitHub lights up (such as pull requests, issue autocompletion, @-mentions, co-authors, and much much more).

We hope you'll like it!
