### ISSUE TITLE
2FA login support for Gitlab Auth

### ISSUE THREAD

**Issue by Imgkl** [desktop/desktop#15967]
### The feature request

When the 2FA is enabled for Gitlab user, the auth fails and can't push the code to repo. 

### Proposed solution

Need a new dialog box to enter 2FA to validate and push the data to repo

**Comment by steveward** [comment]
@Imgkl you can use a personal access token to work with GitLab from GitHub Desktop if 2FA is enabled. See [this guide](https://github.com/desktop/desktop/blob/development/docs/integrations/gitlab.md) for details on how to set that up. Let me know if you have any questions.

**Comment by Imgkl** [comment]
@steveward Thanks, It worked.
