### ISSUE TITLE
GitHub stuck when "Pushing to origin".

### ISSUE THREAD

**Issue by Berrie09** [desktop/desktop#15961]
Hello!

I am quite new to GitHub and recently really started working with it. 

When i was working on a project, i wanted to push the changes i made and it has been stuck even since at the same place in the progress bar.

I have read other issues with pushing a lot of things at once. And that could be the case since i added a lot of images. I tried to delete a few so instead of 13 i have 7 or so. But it still does not want to push and stays stuck on the same place.

What can i do to fix this?

Thanks!

**Comment by fisherman159** [comment]
It's enough to be you, be happy, if you come, I will come

18 Oca 2023 Çar 11:36 tarihinde Sniper ***@***.***> şunu
yazdı:
