### ISSUE TITLE
Version for Ubuntu

### ISSUE THREAD

**Issue by marcelobingo** [desktop/desktop#15968]
### The feature request

It would be very interesting Version for Ubuntu

### Proposed solution

It would be very interesting Version for Ubuntu

**Comment by steveward** [comment]
Thanks for the issue @marcelobingo. At this time there are no official builds of GitHub Desktop available for Linux, but a former developer of GitHub Desktop maintains a fork with Linux builds available for download:

https://github.com/shiftkey/desktop/releases

You can also follow along with https://github.com/desktop/desktop/issues/1525 for updates about an official Linux release.
