### ISSUE TITLE
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

### ISSUE THREAD

**Issue by dmitriyfirer** [desktop/desktop#15969]
### The problem

Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
All variables(PATH) set correctly. Python run fine

### Release version

Version 3.1.4 (x64)

### Operating system

Windows10

### Steps to reproduce the behavior

on commit

**Comment by steveward** [comment]
@dmitriyfirer it looks like you were looking for support for a different project. This issue tracker is for GitHub Desktop If you have any specific questions about GitHub Desktop please let us know.
