### ISSUE TITLE
Problem when trying to commit on my repo

### ISSUE THREAD

**Issue by bcarusodev** [desktop/desktop#15963]
Hi, this happens only with GitHub Desktop, if i use `git commit -m 'Commit Msg'` command it works normally.

And only happens on my Windows desktop, not in my Mac. Why?

![image](https://user-images.githubusercontent.com/29601669/213349644-dfcb7c0f-e5eb-42ff-a74a-2ce0b295e642.png)

Thanks

**Comment by steveward** [comment]
Thanks for the issue @silvergraphs. At this time we don't have great support for hooks in GitHub Desktop. This has been previously reported in https://github.com/desktop/desktop/issues/12562 and https://github.com/desktop/desktop/issues/12586. The hooks will run inside of GitHub Desktop's environment which means they won't necessarily have access to the same environment variables as you'd normally have when using the command line. Some users have had success in resolving this by modifying their system path. I'd recommend taking a look at the issues I linked above, as there are some potential workarounds you can try.
