### ISSUE TITLE
Reactively update UI when branches/index/files change, even when not in foreground

### ISSUE THREAD

**Issue by deanrad** [desktop/desktop#15962]
### The feature request

I was hoping, since it'd been many updates since [9070](https://github.com/desktop/desktop/issues/9070) was closed, that there'd be interest in keeping the UI up to date. A lot of new features are going in, but I'm still frustrated that the UI updating doesn't feel reactive, but needs to be prompted - it feels very CLI to me, exactly what I use this tool to get away from!

Just a thought to revive!

### Proposed solution

An entire monitor could just be devoted to the current diffs of the PR! 
Unit test fails would be instantly explained by the diffs right in front of yo.
Less RSI resulting from tabbing or clicking focus to GH just to see what the current diffs are.

As to what programming techniques would achieve this, a`fs-watch` or even a one-second poll could serve to update the UI without consuming much resources, right?

**Comment by steveward** [comment]
Thanks for the issue @deanrad. We discussed this internally today and our concerns around resource usage for this type of feature have not changed. I know that isn't what you were hoping to hear, but we are a small team and have to focus our priorities accordingly. If this is something we continue to hear feedback on we can reconsider it again in the future. I'm going to close this out, but thanks for taking the time to share this feedback along with ideas for how we could approach shipping this feature.
