### ISSUE TITLE
Github Desktop Hangs when pushing to main

### ISSUE THREAD

**Issue by velara3** [desktop/desktop#15964]
### The problem

The app hangs. More info here, 
https://github.com/desktop/desktop/issues/14331#issuecomment-1396407510

Since I was able to upload by using small chunks my request is to see if maybe there can be the following: 

- cancel push button (i closed the app) 
- preference for http post buffer
- option to clear the cache 
- upload progress during push

I don't know where things are at with this information: 
<img width="318" alt="image" src="https://user-images.githubusercontent.com/1084127/213358362-18087132-f195-45c5-94d8-4f2372be7cea.png">

### Release version

Version 3.1.4 (x64)

### Operating system

OSX 13.0.1

### Steps to reproduce the behavior

1. commit the project (large project)
2. push it to main

it hangs. see screenshots in the related post:  

https://github.com/desktop/desktop/issues/14331#issuecomment-1396407510

Clearing the cache didn't help. I updated the http post buffer and I committed and pushed multiple small chunks of files instead of the whole project to get it updated. I don't know if either fixed the issue or not but I have it uploaded successfully that way. This post is mainly about the issues mentioned in the description.

**Comment by steveward** [comment]
@velara3 thanks for the issue. Setting `http.postBuffer` should no longer be as necessary thanks to improvements made to Git, but it is one of the commonly recommended steps due to having previously been a helpful solution. Unfortunately the push timeouts there can be various causes that are usually outside of the control of GitHub Desktop like repository size, network speed, and proxies.

We are tracking potential for canceling clones in https://github.com/desktop/desktop/issues/2082, but canceling a push isn't something that we have seen requests for and is likely not something we would implement. I'm going to close this out, but let me know if you have any further questions.

**Comment by velara3** [comment]
One more bit of info. After breaking up commits and pushes in to smaller
set of files it did *seem* to hang at one spot. No, progress indications,
but I let it run for about 5-10min and it did complete successfully. But
with the larger commit I had waited over an hour before canceling it (by
closing the app). It might have eventually completed. Thanks for looking
into it.

**Comment by velara3** [comment]
I have just launched Github Desktop and it appears I had a typo in setting the postBuffer amount and I'm not getting this error message when trying to commit: 

> fatal: bad numeric config value '157286400softwareupdate' for 'http.postbuffer': invalid unit

I tried to update it with the following command: 

>git config --global http.postBuffer 157286400

And received a new message:  

>warning: http.postbuffer has multiple values
>error: cannot overwrite multiple values with a single value
       Use a regexp, --add or --replace-all to change http.postBuffer.

What should I do?

**Comment by steveward** [comment]
@velara3 you can run `git config --global --unset http.postBuffer` to unset the config, or manually edit the file using `git config --global --edit`.

**Comment by velara3** [comment]
If I may, 

`git config --global --unset http.postBuffer`

Returns: 
>warning: http.postbuffer has multiple values

And when I use the edit option it still shows the previous values: 
```
[http]
        postBuffer = 257286400
        postBuffer = 157286400softwareupdate
```

Is there a file I can drag into vscode and then remove the http section? 
Quick update, I edited it in VI and removed that section manually and saved. It is now gone. I pushed again and did not received errors and it appears to have worked successfully.

**Comment by steveward** [comment]
Ah, I didn't realize that command would fail if there are multiple values. I'm glad to hear you were able to get things working.

**Comment by KiranJodhani** [comment]
Hi I still face the issue
Github Desktop version : 3.1.7 (x64)
Mac OS : 13.0.1 (22A400)
If there is small size change it works but for large (i.e around 10-20 mb) it stuck

**Comment by webgnar** [comment]
restarting my computer fixed it
