### ISSUE TITLE
Linux: Git lfs files does not fetch.

### ISSUE THREAD

**Issue by Watcher3056** [desktop/desktop#15976]
### The problem

Git LFS files won`t fetch by github-desktop. Fetching, repository lfs init - does not help at all. Only manual "git lfs pull" from command line helps, but even after this action github-desktop marks lfs-files that was loaded as "changed".

### Release version

3.1.1

### Operating system

Linux

**Comment by steveward** [comment]
@Watcher3056 at this time we do not provide official support for the Linux versions of GitHub Desktop. I would recommend opening an issue in https://github.com/shiftkey/desktop, which is where issues with the Linux fork are being tracked.
