### ISSUE TITLE
Implement Filterable/Searchable Activity Log Interface

### ISSUE THREAD

**Issue by johnottone** [desktop/desktop#15986]
### The feature request

Implement a new Activity Log tab or interface to provide users with insight into their log data for any and/or all activities performed through Github Desktop and provide a mechanism to display, export, print, or otherwise view the activity log data based on user filters.

### Proposed solution

What I am proposing, is on the main interface, provide a new tab, section, or a menu item to open a new window, that would display a user's activity log for a specified set of real-time filters and a real-time search box. The user can export the activity log and/or possibly print the results based on the selected filters. It would be nice to have something like this so the user can keep up with all of the projects they have cloned, when they were cloned, and the paths to those local repositories. Likewise, the user may want to be able to easily see which cloned repos have been removed, etc...

Currently, Github Desktop stores the log files at the following location:
"C:\Users\{WINDOWS_USERNAME}\AppData\Roaming\GitHub Desktop\logs\XXXX-XX-XX.desktop.production.log"

The mockups show sample data that is already present in the log files, and presumes that the removal action would need to be added to the logs as well.

### Additional context

Click on the Activity Log Menu Item:

![github-desktop-activity-log-menu-button](https://user-images.githubusercontent.com/112649342/214221131-82661423-b4ad-47f4-8266-70bc594fe409.png)

Github Desktop launches a new Activity Log Window:

![github-desktop-activity-log-window](https://user-images.githubusercontent.com/112649342/214221142-bca1086e-210f-4b6c-a0f6-1b9c8ca9d57e.png)

**Comment by tidy-dev** [comment]
@johnottone Thank you for this suggestion. However, given the small number of users who would make use of a feature that is not core to interacting with git or GitHub, we do not plan to support it. As you mentioned, you can always access the logs and search them with your favorite text editor. :)  Thus, I am closing this issue.

**Comment by johnottone** [comment]
@tidy-dev 

Hi. I think that it is more of a feature for interacting with the application that is interacting with git/github, and it is a valid request. Please reconsider.

**Comment by tidy-dev** [comment]
@johnottone This is absolutely a valid request! Features of this nature have been proposed and discussed in the past. See https://github.com/desktop/desktop/issues/1570, and the current decision is that we do not plan to support any logging interaction whether that be as extensive as you propose or as simple as just "git commands" indicated in the linked issue. 

Also to note, an issue being closed does not indicate that we would never reconsider. Other users are welcome to comment here explaining why they would enjoy the feature and more helpfully thumbs up (easier to query on) this issue to voice support; and if it became a highly requested feature, we may revisit.
