### ISSUE TITLE
[Temporary fix] Stuck on Fetching origin after upgrade to Windows 11

### ISSUE THREAD

**Issue by pikawika** [desktop/desktop#15983]
### The problem

After upgrading from Windows 10 to Windows 11 22H2 GitHub desktop gave various errors related to repositories which are hosted on a GitLab server requiring SSH key authentication. After reinstallign GitHub desktop and adding existing repo's from disk GitHub is stuck on 'fetching origin'. The logs don't show anythong related to the requested fetch instruction. Cloning, fetching etc works well using git from CMD.

> As per [Issue #15796](https://github.com/desktop/desktop/issues/15796), unchecking "Use system OpenSSH (recommended)" solves this issue.

### Release version

3.1.4 (x64)

### Operating system

Windows 11 22H2 64 bit

### Steps to reproduce the behavior

1. Clone a repo using SSH from a GitLab server using CMD
2. Add the local repo to GitHub desktop, either by dragging and dropping or by the "Add local repository" option
3. Try to interact with this just added repository, i.e. fetch
4. GitHub Desktop hangs on "Fetching origin"

### Log files

[2023-01-23.desktop.production.log](https://github.com/desktop/desktop/files/10482588/2023-01-23.desktop.production.log)

**Comment by steveward** [comment]
@pikawika it looks like you were able to resolve this issue, so I'm going to close this out to keep our issue tracker manageable.
