### ISSUE TITLE
Add support for removing multiple local/cloned repositories at once using checkboxes in the repository list.

### ISSUE THREAD

**Issue by johnottone** [desktop/desktop#15987]
### The feature request

Removal of multiple local/cloned repositories is time-consuming. A user must click on each individual repository, then right click and select "Remove" from the context menu. Then, based on their "Prompts" settings, has to select whether to actually delete the repository or keep the files, but remove the repository from the tracked list.

### Proposed solution

I am proposing, that in the repository list on the left-hand side of Github Desktop, add checkboxes beside each repository AND its username. This would allow the current user to remove repositories from multiple local directories cloned from a single user by clicking on the user checkbox, which would select all repositories cloned from that user, or remove repositories cloned from several different users, that appear in the list. 
For instance, say I cloned 4 different repositories from John Smith, and 3 different repositories from Jane Smith, and I wanted to remove all of John Smiths repositories that I had previously cloned, all I would need to do is put a check beside of John Smith and all of John Smiths repositories would be removed from my local machine. Likewise, say I wanted to remove all of John Smiths and only one of Jane Smiths, but I wanted to do it all it once. I would place a check in the box beside John Smith, then scroll down and put a check beside the single Jane Smith repository I wanted to remove,

### Additional context

![remove-multiple-repos](https://user-images.githubusercontent.com/112649342/214227160-1217924a-6ab3-4df6-bd32-b2848bd43ed7.png)

**Comment by tidy-dev** [comment]
@johnottonne Thank you for this suggestion and wanting to improve GitHub Desktop!

However, this is likely of low use case as the vast majority of our users have less than 5 repositories and those that have more, do not delete in high frequency. Additionally, deleting and removing is a destructive action that we want to be cautious about introducing a way to accidentally delete a repository unintentionally (Select one too many). Thus, we are not going to consider this feature at this time.

Even tho this issue is being closed, if we were to get a large number of users providing similar feedback, we may reconsider addressing the core issue of not being able to delete multiple repositories at once. Thanks again.

**Comment by johnottone** [comment]
Well, others have posted about how their repository lists start looking messy when they have a lot of cloned repositories. Its hard to believe that "the majority" of users have less than 5 repositories cloned. That really doesnt seem realistic to me. My company has like 10 repositories and each of our developers clone those projects, plus each developer has their own projects that fellow employees clone. If I am working on a specific project, I use the search on github to find repositories matching my research parameters and will end up pulling 5 or more projects in preparation for my research and will eventually end up testing the cloned repositories, and while the majority of the time, I end up only keeping one of those repositories, and remove the rest because they did not work correctly or did not do exactly what I was looking for. Until i get a chance to go in and clean those repos up they sit in the list taking up space and let's face it, the repository list has a single filter box, which really does not help with organizing or managing a list for THOSE OF US who do have more than 5 repos. But, ok, if you say "the majority" of people only have 5 or less repositories in their list and this wouldnt benefit anyone, then ok.

**Comment by johnottone** [comment]
@tidy-dev 
After careful reconsideration, I have determined that you closing this before anyone even got a chance to see it was pretty spiteful in my opinion. Also, I dont know what kind of workloads you manage, but I think I speak for myself and many other people, when I say that I have more than 5 repositories. My company alone has over 15 repositories and that doesnt include all of the Microsoft repos that I subscribe to and follow, and even contribute to., not just on this account but my personal account as well. For instance...

There is 
Windows Universal Samples
Windows Community Toolkit
Several different template studios
Power Toys
Monaco Editor
WebView2
Wpf

I mean that right there is more than 5 repositories. And you cant with any seriousness try to tell me that I am the only person on github experiencing issues with the management of repositories on Github Desktop. I would like for you to reinstate my functionality request so that others might have a chance to voice their opinions about it as opposed to you quickly closing it within 2 hours after it was posted. It took me longer to create the screenshots and mockups than it did for you to single handedly squash this before the community even got a chance to look at it.  And to add to this functionality there should be a way for us to star or favorite our most used repositories. If you choose not to reopen this, I will post it again and again until its given a chance to be seen. Im glad that your workload is so small and that you have less than 5 repositories to keep up with. But the majority of us have alot more than 5 and as such, we need a better way to manage it. Just because you dont see any use for it, does not mean the community doesnt need it.

**Comment by larsvilhuber** [comment]
I second (third) the need to do "spring cleaning". At any point in time, one might be working on 5-6 repositories, but over time, those might be different ones. Looking at the laptop that I've used for the past 5 years, I have several dozen. Tedious to clean up.

**Comment by gearak** [comment]
+ 1 for this :))

**Comment by Nilpo** [comment]
+1 here as well. I have accumulated over 100 repositories over the years and deleting them individually is a non-starter. How this isn't an option is just beyond me. You can still have safe guards in place when performing a destructive action in bulk. It's common practice to fork a current project for tinkering or exploring and then have no further need of it. I don't know a single user with less than 5 repositories.

**Comment by johnottone** [comment]
Honestly, I can only assume, that @tidy-dev may have misunderstood the request. As they refer to "destructive actions" and "deletion frequencies". I was not talking about any "destructive action" that **_DELETES_** an actual repository from Github. **The request was to remove the "local link to the cloned repository in Github Desktop" and actually remove the locally cloned repositories from the USER'S machine...** **_I NEVER requested to delete the original repository from Github, which, I agree with @tidy-dev , must be done through the normal procedure_**. I am still at a loss when I try to understand the logic of why the requests were closed before the topic could be discussed with the team and before anyone could get a chance to even look at them. I later made a request to re-open them, in hopes that more time would be taken to actually understand what was being requested before just closing a valid and simple feature request., for which I was admonished.

Ultimately, I had to stop using Github Desktop for everything except for a few customer repositories. It became a nightmare to manage my corporate/customer repos along with my personal/research repos. Productivity came to a halt due to the lack of organization tools. So, instead of cloning, I've opted to right click and save the zip file from the Github page in a browser, for all of the repos I just want to test, research, or learn from. The disorganized experience has caused a major disconnect on projects to which I was contributing. 

It was stated above, that the "vast majority" of its users only manage <5 repos at any given time. That's most likely due to the fact that managing any more than that becomes extremely tedious, and those users have realized that it just doesn't scale for larger-than-average workloads (which would be ≥5 repos).  I worked well into the early morning hours fleshing both the requests out, and creating mocked up screens and what not, and finally posted the requests at about 4am EST or something, and when I woke a few hours later, I was disheartened to say the least, when I saw that BOTH the organizational requests had already been closed before anyone could even read them, and now, they remain obscure and ultimately forgotten. It would be interesting to see a graph showing "GithubDesktop-User Managed-Repository-Percentage Comparison" based on ACTUAL DATA.

**Comment by larsvilhuber** [comment]
I should note that I was able to do a fully destructive "spring cleaning" by removing the local store (on Windows, somewhere in AppData - not exactly the easiest to access). It deleted *all* entries, and from there I could remove (*manually*) the individual repositories on disk (ironically, Windows provides checkboxes for removing multiple directories). I absolutely agree with @johnottone that I would like to see a user survey that asks users about how many repositories they *wish* to use/clean/manage/etc.

**Comment by sulay-tw** [comment]
+1

**Comment by nikishyn** [comment]
+1

**Comment by rafa-lopes-pt** [comment]
Same here! I actually found this issue page while googling a way to bulk delete repos...so...

**Comment by johnottone** [comment]
@rafa-lopes-pt 
and 
@larsvilhuber 

Thank you so much for the support of this feature request. I really don't think it's too big of an ask, especially since it would take less time to code it then it actually took me to mockup the screens and write up the request. I mean this request could be implemented in minutes...They could even implement it in such a way that the user would knowingly have to select a checkbox in their settings like:

` [x] Enable the selection and removal of multiple cloned repositories. (WARNING! THIS WILL REMOVE/DELETE LOCALLY CLONED REPOSITORIES FROM YOUR DEVICE, INCLUDING FILES AND DIRECTORIES, AND WILL ALSO REMOVE THEIR CORRESPONDING ENTRIES IN GITHUB DESKTOP. `

Sadly, they told me they would ban me if I tried to reopen or repost this request, yet they closed the request before anyone could even read it...so it just got swept under the rug. Who needs a logical and consistent user experience anyway? So, someone else would have to make a new request and then reference my request to get their attention and let them know this is a real problem being experienced by more than just a handful of users.

**Comment by koson** [comment]
Hi, I've found the same problem.
I've cloned hundreds of repos to my local directory, in my teaching course students do their homework in .md files and send pull requests to ask me to score them. I can read their lab result on the GitHub web interface but the best for me (and my internet traffic) is to read on vscode md preview.
Today I try to clean up those cloned repos and settle here by the direction of Google.

The dirty solution I found is moving the local file to another directory then trying to access those repos on the GitHub desktop and answering "Remove" and then the GitHub Desktop remove it for me one-by-one.

don't know about the other solutions, but it works for me with fewer mouse clicks.

**Comment by hannahbellelee** [comment]
Yeah this needs to happen. Reopen it and actually let other people see the request. I don't think anyone has than 5 locally cloned repositories. I mean who is this catering to @tidy-dev, how many locally cloned repositories do you use? I've got 100's cloned locally. Whoever this decision is catering to, must not have a heavy workload.

@tidy-dev 
 I think its time to revisit this. I think if this entry had not been scrapped before people got to see it it would have pulled more interest. Whats so hard about putting some checkboxes and deleting LOCALLY CLONED REPOSITORIES?

**Comment by tidy-dev** [comment]
👋  Hey all, this issue was discussed by the entire Desktop team and the data point I referenced was pulled from user data (not an assumption). To reiterate, please add a thumbs up and comment describing how this feature would help you and we may revisit in the future.

**Comment by larsvilhuber** [comment]
@tidy-dev thanks for engaging. I'm not a marketing guy, so far be it to second guess that. I've taught a bunch of economists how to use Desktop, and at the end of each training, there are 15-30 newbie users with 3-4 repositories, and me with 50+. The median user is thus low-count, but the power user is high-count. I also postulate - but your user data should be able to demonstrate - that the frequent user is high count, but the occasional user is low count. Thus, I encourage you to consider supporting the power users out there - who are high-count and high-frequency.

**Comment by Sarah8020** [comment]
I work on a team where people are regularly accumulating 10s of repositories on their local machine (somewhere between 20-100 on their machine at a time). 

We have run into situations where this would be useful, for "spring cleaning" as mentioned above, but also when someone has many repositories that have been moved locally and need to be repath'ed. It is easy enough to fix the paths via drag + drop, but a pain to remove the now duplicated items (which are indistinguishable, since Desktop doesn't "refresh" the paths or anything so you can't tell a repo is not pathed correctly until you click into it).

+1

**Comment by hannahbellelee** [comment]
at the risk of sounding obvious, the way it would help is that those of us that had MORE THAN 5 LOCAL REPOS, ie... any significant workload, wouldnt have to spend all afternoon or all day deleting each local repository manually, Examples of projects to remove...local repos that dont build, dont work correctly, arent completed,  or deleting local repos that didnt quite have the functionality I was after, or perhaps because i just wanted to clean up my files bcause there too many distractions. or any number of other reasons. 

PS: I wish my users would mock-up all their requests like this.
