### ISSUE TITLE
Feature request: Repository list folders

### ISSUE THREAD

**Issue by rlabrecque** [desktop/desktop#1598]
Just simple folders for organizing repos inside the client. Most clients have something like this I.E. SourceTree had:
![image](https://cloud.githubusercontent.com/assets/2047188/26184461/6da800ce-3b42-11e7-86db-635864a53635.png)

Additional notes:

- You should be able to specify the folder during add time.
- Dragging in a folder should just add it to the global namespace.
- Folders should be collapsable and that state should be stored between runs.
- Folders should have a context menu where you can rename and delete them.
- Deleting should probably just dump all the repos into the parent.
- Filters should probably work on both folders and all repos.
- Drag and drop repos to include them in a folder.

**Comment by xt0rted** [comment]
This is similar to what's talked about in #1533

**Comment by rlabrecque** [comment]
Ah yeah, I wasn't aware that it already split repos up between local and remote!

The GitHub/Organization 'group' could definitely be the default for any repos that do have github as the default remote, and then it would be nice if you could move them from that point?

**Comment by mlantz** [comment]
As a member of 6 orgs this level of organization would mean the world to me personally.

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by noamtamim** [comment]
This request is pretty popular, judging by the votes and duplicates (I was about to suggest it myself, but found this one).
7.5 months later, this is still not on your roadmap (but much more complex features are).

**Comment by billygriffin** [comment]
Thanks for the idea! I'm removing `future proposal` in favor of #6460 which tries to capture *all the things*™️ in a more unified way since there have been so many different implementation ideas suggested.
