### ISSUE TITLE
Languages add request

### ISSUE THREAD

**Issue by lemonorangeapple** [desktop/desktop#15998]
### The feature request

Add more languages in the language selection function.

### Proposed solution

Add language selection function in menubar.
Add commity of more language translate in [_Crowdin_](https://crowdin.com/).
This will let commity of _Github Desktop_ join more people of other country.

**Comment by steveward** [comment]
Thanks for the suggestion @lemonorangeapple. At this time we do not have language localization in GitHub Desktop, but this is something that we would like to do in the future. I don't have a timeline for when that may happen as it would require quite a bit of work by the team. I'm sorry that I don't have better news at this time.
