### ISSUE TITLE
Feature request: Additional information for each repo in the repository view

### ISSUE THREAD

**Issue by rlabrecque** [desktop/desktop#1599]
This was my favourite feature of the old SourceTree which they got rid of when they killed their repository bookmarks sidebar. Just being able to see at a quick glance what the state of your repos is in. If you have uncommitted changes, or need to fetch changes was a part of my workflow that I had no idea how much I relied on it until it was gone.

Example:
![image](https://cloud.githubusercontent.com/assets/2047188/26184544/e5d453f4-3b42-11e7-82cc-1affaeaf53cc.png)

**Comment by joshaber** [comment]
I _think_ this is essentially the same as #678, so I'm gonna close this. Feel free to add on to that issue.
