### ISSUE TITLE
default remote setting https/ssh

### ISSUE THREAD

**Issue by NoPlanNomad** [desktop/desktop#15993]
### The feature request

currently cloning a repository trough desktop defaults to https.

but depending on the repository settings this might have to be changed to ssh if you want to use the terminal.

### Proposed solution

use ssh by default if remote requires that for CLI.

or create a setting where the default behavior can be selected.

**Comment by tidy-dev** [comment]
@NoPlanNomad Thank you for reaching out! If you want GitHub Desktop to use SSH for a given repository, you must clone it as an SSH repository by using the SSH clone path with cloning or you can change the remote to the SSH clone path in GitHub Desktop Repository Settings and GitHub Desktop will use ssh for that repository.

 `Repository > Repository Settings > Remote`
![image](https://user-images.githubusercontent.com/75402236/214288776-349f8f0c-fe85-4ad5-b625-cacb16f01fdc.png)
![image](https://user-images.githubusercontent.com/75402236/214288851-6bf273ce-218b-45ef-afc1-c3585fa78c42.png)

^ In that example, I would change the remote to `git@github.com:desktop/desktop.git` if I wanted it to be SSH.
