### ISSUE TITLE
Stuck on "Fetching origin", high CPU

### ISSUE THREAD

**Issue by preciselytom** [desktop/desktop#15990]
### The problem

The application gets stuck showing `Fetching origin, Hang on...` several times per week, usually after the laptop has been sleeping. The `GitHub Desktop Helper (GPU)` and `GitHub Desktop Helper (Renderer)` consume about 50% CPU together, and `WindowServer` another 40%. I have no other heavy applications running.

The application is still responsive; I can switch to a different repo and then the CPU drops and the button works. Switching back to this particular repo (which is my main one), the button shows the spinner again and the CPU usage is back up.

Quitting and starting the application again fixes the problem temporarily.

Please let me know if I can help debug this.

### Release version

Version 3.1.4 (arm64)

### Operating system

macOS Ventura 13.1 (22C65)

### Steps to reproduce the behavior

It happens randomly for a particular repository (which is private), usually after the laptop has been sleeping.

### Log files

[2023-01-24.desktop.production.log](https://github.com/desktop/desktop/files/10488783/2023-01-24.desktop.production.log)

### Screenshots

<img width="1580" alt="Screenshot 2023-01-24 at 11 49 22" src="https://user-images.githubusercontent.com/38493203/214272711-464be0b4-7bb6-4e1e-86af-8f25027e2af6.png">

**Comment by steveward** [comment]
Thanks for the report @preciselytom. Is this a large repository with a large number of branches? Is interesting to see that it's hanging up on one specific repository. I can see that the refresh is taking a while here:

```
2023-01-24T10:46:18.606Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 10 repositories took 3.9s of which 347.8s paused, total 351.6s
```

Can you try disabling the background fetching that GitHub Desktop does to see if that helps with performance? You can do that by going to `GitHub Desktop` > `Preferences` > `Advanced` and disabling 'Periodically fetch and refresh status of all repositories.' 

Let me know if that helps with this issue.

**Comment by preciselytom** [comment]
Thanks for the tip! I have disabled the background fetching and will let you know whether that makes a difference.

The repository has 7000 commits and 140 (mostly stale) branches, so it's busy but not enormous.

When the application is not stuck, the "Fetch origin" button only takes ~5 seconds when pressed, but when stuck it can run for hours.

**Comment by steveward** [comment]
In the interest of keeping our issue tracker manageable I'm going to close this out, but let us know how that works out. We also have a broader issue for tracking performance at https://github.com/desktop/desktop/issues/10625 where I'll add this.

**Comment by preciselytom** [comment]
It did actually not help. `Periodically fetch and refresh status of all repositories` has been turned off the whole day, but the application is nonetheless stuck spinning with `Fetching origin` and hogging CPU when I open the laptop.
