### ISSUE TITLE
schannel: failed to receive handshake, SSL/TLS connection failed

### ISSUE THREAD

**Issue by SudikshaRIL** [desktop/desktop#15999]
Description:  while cloning project from github, I am seeing this error on my cmd
GitHub Desktop : git version 2.37.2.windows.2
Operating system : Windows 10
Steps to Reproduce : Not really sure what has lead this.
Expected Behavior : Should clone project without any error. Earlier it could clone. Not really sure what lead to problem.
Actual Behavior : Cannot clone and its showing the error -  fatal: unable to access 'https://github.com/mrusamamuzaffar/get_device_information.git/': schannel: failed to receive handshake, SSL/TLS connection failed
Additional Information: 
![image](https://user-images.githubusercontent.com/111279290/214559896-f9f3eb57-7a7b-465e-b04c-bee0383f11e5.png)

**Comment by niik** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project, in this case it's looking like you're having issues with [Git for Windows](https://github.com/git-for-windows/git) though it doesn't look like a bug to me as much as either a network issue, a date/time issue, or a corporate proxy which intercepts traffic. Either way you should probably upgrade to the latest version of Git (2.39.1) before opening an issue with the G4W project.

Best of luck!
