### ISSUE TITLE
macOS version 3.1.4 (x64) comes back as latest during update check

### ISSUE THREAD

**Issue by DigiH** [desktop/desktop#16010]
### The problem

Seeing the release of 3.1.5 I was wondering why the usual automatic update didn't kick in, but checking for updates manually also produces a **You have the latest version** message.

<img width="462" alt="Screenshot 2023-01-26 at 11 34 39" src="https://user-images.githubusercontent.com/17110652/214815050-c76eec53-f239-4f1e-82d4-268617e49aaf.png">

### Release version

3.1.4

### Operating system

macOS 10.15.7

### Steps to reproduce the behavior

Open the 'About GitHub Desktop' menu item and **Check for Updates**

**Comment by sergiou87** [comment]
Hello! Right now 3.1.5 is enabled only for 50% of our users, as we make sure it doesn't introduce regressions. You can force the app to upgrade by pressing <kbd>Option</kbd> or <kbd>Alt</kbd> and then click on the "Check for updates" button (now renamed to "Ensure latest version") to get the latest update, see #14883

I hope that helps!

**Comment by DigiH** [comment]
Perfect, thanks for the hint!
