### ISSUE TITLE
commits from PR branch are marked as undo-able

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#1601]
### Description

You can view a PR's commits in Desktop by (if you have push rights) clicking the link next to the merge button:

<img width="651" alt="screen shot 2017-05-18 at 1 31 27 pm" src="https://cloud.githubusercontent.com/assets/359239/26185437/58da5b74-3bce-11e7-9e42-c4e508b1c045.png">

This sets up your local repository with a branch checked out containing those commits:

<img width="751" alt="screen shot 2017-05-18 at 1 32 20 pm" src="https://cloud.githubusercontent.com/assets/359239/26185459/72905104-3bce-11e7-9594-939cf41ee06d.png">

However, because this branch is unpublished, the commit form displays the fact that you can undo this commit:

<img width="291" alt="screen shot 2017-05-18 at 1 32 44 pm" src="https://cloud.githubusercontent.com/assets/359239/26185472/866d1fb8-3bce-11e7-800b-eb4914ceebb2.png">

### Version

**GitHub Desktop version:** 0.5.4

**OS version:** `Microsoft Windows [Version 10.0.15063]`

### Steps to Reproduce

1. Open the app, ensure you have signed into an account
1. Find a PR against a repository you have push rights (so you can see the merge dialog)
1. Add the repository to your application (this isn't important, it just speeds things up)
1. Click the 'Open in Desktop' link
1. Desktop should focus, switch to the repository, fetch from the other remote and checkout a branch named `pr/XXXX` where `XXXX` is the ID

**Expected behaviour:** no option to "Undo Commit" should be visible here

**Actual behaviour:** I can undo this commit

**Reproduces how often:** Only ran through this one, but I'm pretty sure it's consistent

**Comment by tierninho** [comment]
@shiftkey So i tested this against `0.8.1-beta2` and here are the results (seems fixed?):

Followed the steps and the result after clicking `Open in Desktop` link was:
- Branch switched was smooth and fetch occured
- no `undo` button shown on Changes tab
- the commit was shown in History tab

<img width="663" alt="screen shot 2017-08-25 at 12 51 18 pm" src="https://user-images.githubusercontent.com/14828183/29723928-7f25f518-8994-11e7-95ba-9de313a4f940.png">
<img width="764" alt="screen shot 2017-08-25 at 12 51 02 pm" src="https://user-images.githubusercontent.com/14828183/29723929-7f272e6a-8994-11e7-827a-af00e2b21151.png">
<img width="1131" alt="screen shot 2017-08-25 at 12 54 47 pm" src="https://user-images.githubusercontent.com/14828183/29723953-9c461740-8994-11e7-92fe-5aa7790d3f8f.png">

Happy to test again. Feel free to close if indeed fixed.

**Comment by j-f1** [comment]
@tierninho You’ve checked out `tierninho-patch-1`, which is the actual PR branch. @shiftkey had `pr/1600` checked out, which is not the actual PR branch.

**Comment by billygriffin** [comment]
I tried reproing this several times and wasn't able to do so, so I'm closing this as part of our work on improving Undo and adding amend.
