### ISSUE TITLE
can't find "project" last seen at "path"

### ISSUE THREAD

**Issue by mosyukri** [desktop/desktop#16019]
### The problem

I using MacOS was unable to open or retrieve or locate project file that is inside user folders.
every time I click locate and select project folder, it will return error 

Failed to execute getStatus: EAGAIN

### Release version

version 3.1.4

### Operating system

MacOS Ventura 13.2

### Screenshots

![IMG_0190](https://user-images.githubusercontent.com/68844132/215058457-267c5b61-1635-4cc0-9e56-a7ef4efd11ee.jpeg)

**Comment by steveward** [comment]
Thanks for the report @mosyukri. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by mosyukri** [comment]
hi @steveward 
here are the logs
 [2023-01-27.desktop.production.log](https://github.com/desktop/desktop/files/10524305/2023-01-27.desktop.production.log)
[2023-01-28.desktop.production.log](https://github.com/desktop/desktop/files/10524306/2023-01-28.desktop.production.log)

**Comment by steveward** [comment]
Thanks for sharing those logs. I'm seeing a few errors in the log file:

```
GitError: error: cannot fork() for remote-https: Resource temporarily unavailable
```

```
 exited with an unexpected code: 128.
stderr:
Cloning into '/Users/syukri/Desktop/Work/BDF_CRM_API'...
error: cannot fork() for /Applications/GitHub Desktop.app/Contents/Resources/app/desktop-trampoline/desktop-trampoline: Resource temporarily unavailable
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

We've normally seen these errors on Windows. Is there anything unusual about your macOS setup -- i.e. any security software that could be interfering with GitHub Desktop? Has GitHub Desktop previously worked on this system? This is likely a system specific issue -- have you noticed problems with any other applications?
