### ISSUE TITLE
Unable to locate Git

### ISSUE THREAD

**Issue by Grey-Wind** [desktop/desktop#16017]
### The problem

I have Git installed, but when I use the Command Prompt in the software, It says Git is not installed. The reality is that you cannot detect that Git has been installed after an update.
Note: It can be used in the past

### Release version

3.1.5

### Operating system

Win 10

### Steps to reproduce the behavior

1. right click repo
2. click open in command prompt
3. then see unable to locate git, but I can use git without github desktop(Git bash is still usable)

Note:I never use Git Gui

**Comment by tidy-dev** [comment]
👋 @Grey-Wind Thanks for reaching out. However, when you open a repository in command prompt  (even if through GitHub Desktop shortcut), then it is all based on what is set up on your system same as if you opened the command prompt from your start menu.  My assumption would be that t[here is not a PATH ](https://www.answerlookup.com/how-add-git-windows-path-environment-variable) variable set up for it or setup correctly for it. You could also try reinstalling Git. 

(Closing this issue as it is not GitHub Desktop issue)
