### ISSUE TITLE
more language support

### ISSUE THREAD

**Issue by Grey-Wind** [desktop/desktop#16016]
### The feature request

Can it add more language support? Such as Chinese, Russian and more.

### Proposed solution

Maybe I can make some Chinese content in my spare time

**Comment by tidy-dev** [comment]
Thanks for the issue @Grey-Wind . At this time we do not have language localization in GitHub Desktop, but this is something that we would like to do in the future. I don't have a timeline for when that may happen as it would require quite a bit of work by the team. I'm sorry that I don't have better news at this time.

**Comment by Johnserf-Seed** [comment]
look here
https://github.com/Johnserf-Seed/GitHub-Desktop-Chinese-Language-Pack
