### ISSUE TITLE
Add a web version

### ISSUE THREAD

**Issue by MichelDiz** [desktop/desktop#16025]
### The feature request

Just a web version that I can run via Docker and access a headless Linux distro via Path binding. 

### Proposed solution

Make a "web" build and have a dockerfile for this.

### Other solution

Or maybe add a ~local repository via NFS or ssh.

### Additional context

My context is, I have a Linux Container running Alpine and it is my development server. Running Docker(nested virtualization) and other services. All my codes are on this machine, where I have data replication, snapshots and duplicate backups (I've learned a lot from life... Backup is of such importance that few people are aware of).

On the host I isolate everything from the Dev environment. All my work is inside LXC and on the host I do other activities. This way, as LXC has no GUI, I am unable to use the Github desktop. I can use remote VsCode for this, but I wish I had more than one options.

**Comment by niik** [comment]
Hey @MichelDiz, thanks for reaching out. Given that Linux isn't officially supported by Desktop at this time I'm afraid there's not much I can do to help here. It's possible that you could run the [unofficial Linux fork](https://github.com/shiftkey/desktop) in a docker container and use something like [ssh's x-forwarding](https://unix.stackexchange.com/questions/12755/how-to-forward-x-over-ssh-to-run-graphics-applications-remotely) to make the window appear on your local machine though that would require a subset of x11 dependencies to be installed on the container as well.

I think, as you suggest, that a better approach would be to mount the docker filesystem (or parts of it) locally and use Desktop as if the repository lived on your local machine.

Best of luck!
