### ISSUE TITLE
Clone from Azure DevOps works fine, but authentication fails when I try to push

### ISSUE THREAD

**Issue by adremeaux** [desktop/desktop#16023]
### The problem

I cloned my Azure DevOps repo from the instructions on this page: https://github.com/desktop/desktop/blob/development/docs/integrations/azure-devops.md

The clone had some issues with GitLFS but once I sorted that it worked fine. I've tried to make a commit and push it and am getting an auth error. If I try to push via the command line I have to sign into my Microsoft account but then it works fine.

Here is the relevant bit from the logs:

023-01-27T18:19:15.253Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Plants_Game - adremeaux (has token)
2023-01-27T18:19:31.074Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-01-27T18:19:31.622Z - info: [ui] [AppStore] loading 7 repositories from store
2023-01-27T18:19:31.622Z - info: [ui] [AppStore] found account: adremeaux (adremeaux)
2023-01-27T18:19:31.673Z - info: [ui] [BranchPruner] Last prune took place 3 minutes ago - skipping
2023-01-27T18:19:31.769Z - info: [ui] launching: 3.1.4 (Windows 10.0.22621)
2023-01-27T18:19:31.773Z - info: [ui] execPath: 'C:\Users\adrem\AppData\Local\GitHubDesktop\app-3.1.4\GitHubDesktop.exe'
2023-01-27T18:19:32.213Z - info: [ui] Subscribed 'adremeaux' to Alive channel
2023-01-27T18:19:34.948Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Plants_Game - adremeaux (has token)
2023-01-27T18:20:00.259Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: Authentication failed for '[redacted for privacy]'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)

### Release version

3.1.4

### Operating system

Windows 11

**Comment by steveward** [comment]
Thanks for the issue @adremeaux. Any chance the access token was created with read-only permissions instead of read/write? That's the only guess I have about why cloning would work, but pushing fails. I'd recommend recreating the token as a first step to see if that gets things working.

**Comment by adremeaux** [comment]
If I recreate the token, how do I set it in GitHub Desktop? The only time it's prompted me for the token is during the clone itself. I'd prefer to not have to clone the entire repo again.

**Comment by adremeaux** [comment]
You know if I jam my token right into the repo url in repo settings (https://login:token@...) it works, but I wager I probably shouldn't do that.

**Comment by steveward** [comment]
@adremeaux you can remove the existing token from the Windows Credential Manager, and then you should be prompted to enter it again .

**Comment by adremeaux** [comment]
It does not prompt me to reenter my credentials after removing them.

**Comment by SgtFlex** [comment]
Chiming in to say that this is the message that pops up. I tried removing the azure token from Windows credential manager and it still does not prompt me for anything.

![image](https://github.com/desktop/desktop/assets/11985467/a07ba001-a44b-4c30-97a1-c1ba439dcea9)

(I am also using Azure DevOps and experiencing the same issue. Can push to repo just fine through CLI but does not work with GitHub Desktop).

**Comment by tooOpen** [comment]
I have same problem please answer us !!!!
github desktop!!! Microsoft!!!
#16900

**Comment by sergiou87** [comment]
Hopefully this is already fixed with the latest auth-related changes #18700 

Otherwise let us know and we will reopen it!
