### ISSUE TITLE
"Checking for updates failed" nuisance prompt in offline environment

### ISSUE THREAD

**Issue by DaJoNel** [desktop/desktop#16022]
Beginning in version 3.1.5, it appears that a setting to automatically check for updates on program launch was added with no way to disable the functionality. I do my work in an offline environment, so this results in a nuisance prompt every time I launch the program. Please add an option to disable automatic update checking.

**Comment by steveward** [comment]
Thanks @DaJoNel, I'll add this to https://github.com/desktop/desktop/issues/3410 where we are tracking this.

**Comment by DaJoNel** [comment]
This is resolved in version 3.2.1. I don’t think #3410 has been, though.
