### ISSUE TITLE
Edit->Select All menu option does nothing

### ISSUE THREAD

**Issue by rlabrecque** [desktop/desktop#1602]
### Description
In the Changes view the Edit->Select all button seems to do nothing.

### Version

**GitHub Desktop version:**

0.5.4

**OS version:**

Windows 10 1703

### Steps to Reproduce

**Expected behaviour:**

I'm not sure? Selecting all of the files? That seems really weird.

**Actual behaviour:**

Nothing.

http://i.imgur.com/Ad5zQah.gifv

**Reproduces how often:** 

100%

#### Additional Information

The whole Edit menu seems... pointless?

**Comment by shiftkey** [comment]
Cross-referencing some recent issues where we talk about the Edit menu being a bit confusing - https://github.com/desktop/desktop/issues/1379 https://github.com/desktop/desktop/issues/1392

**Comment by rlabrecque** [comment]
Ah yeah, looks like niik is on it already!

I still feel like the Undo issue would have been confusing too at some point.  They just don't seem very relevant in this context. Programs like Chrome, Microsoft Edge, Slack, and Discord don't have Undo/Redo/Select All etc as buttons anymore but all support ctrl+z/y, ctrl+a still.

I could just rename this issue to discuss the edit menu in general if wanted.

**Comment by niik** [comment]
> Ah yeah, looks like niik is on it already!

I fixed the bug with the select all menu item not working in https://github.com/desktop/desktop/pull/1383. This is a platform convention menu item that refers to text selection. If you open up a view that allows you to select text (like the a commit with a description) it should work fine.

> I still feel like the Undo issue would have been confusing too at some point. They just don't seem very relevant in this context. Programs like Chrome, Microsoft Edge, Slack, and Discord don't have Undo/Redo/Select All etc as buttons anymore but all support ctrl+z/y, ctrl+a still.

I believe this is sufficiently answered in https://github.com/desktop/desktop/issues/1541#issuecomment-302059241 but feel free to add to that issue if you want. The edit menu is a platform convention and I'm very hesitant to not provide the items that users expect there. That said the undo thing seems to be causing some confusion so perhaps we should consider adding an `Undo commit` item next to the undo menu item or something like that.

I'm going to close this out and refer to the other issues for more discussion.
