### ISSUE TITLE
Adding Zed as a supported editor

### ISSUE THREAD

**Issue by JosephTLyons** [desktop/desktop#16026]
### The feature request

Hello,

I'm Joseph - I work at [Zed Industries](https://zed.dev).  We're working on a new editor that we believe will be in public beta in the near future.  At what place, developmentally, would Zed need to be in order for the Desktop team to feel comfortable with accepting a pull request to add support to open repos and files within Zed?  I'm interested in adding Zed support, but I'd rather wait to do so if the PR wouldn't be accepted until say Zed was at 1.0.

Thanks

### Proposed solution

N/A

**Comment by xnousnow** [comment]
Looking forward to it!

**Comment by JosephTLyons** [comment]
I opened a PR, but understandably, it was closed because Zed is still private alpha - that will be changing soon! 😉

**Comment by Iswaqasahmed** [comment]
@JosephTLyons  can I know the release date of Zed?

**Comment by JosephTLyons** [comment]
> @JosephTLyons  can I know the release date of Zed?

Zed is in public beta right, for macOS users, and we will have support for other platforms at some point near our 1.0 release (not sure when this will be, but it's not in the near term).

https://zed.dev/download

**Comment by Kiloneie** [comment]
Any follow ups ? It's been a few years.
