### ISSUE TITLE
Add JetBrains DataSpell to external editor

### ISSUE THREAD

**Issue by jm-rivera** [desktop/desktop#16020]
### The feature request

While most of JetBrains IDEs are recognised, that isn't the case for DataSpell. DataSpell is their IDE for DataScience work.

I have DataSpell installed but it is not listed under integrations.
<img width="588" alt="image" src="https://user-images.githubusercontent.com/7374450/215101099-d0440cb3-1f2e-4c08-ba78-8fc522ff101f.png">

This issue persists even on version 3.1.5 (arm64) even though there have been improvements to how other JetBrains IDEs are handled.

### Proposed solution

Various issues in the past have documented the challenges with getting the desktop app to recognise JetBrains IDEs as external editors - including DataSpell.

I have successfully experimented with adding DataSpell to this list.

https://github.com/desktop/desktop/blob/8e42a071b10fca2d30772982342782b552fe9a7d/app/src/lib/editors/darwin.ts#LL17-L20C5

My proposal - which I'd be happy to contribute - is to add DataSpell to the list.

**Comment by Nguyenpham89** [comment]
![2FBE25CA-AD20-45E9-9307-67D40144D9A9](https://user-images.githubusercontent.com/125356525/231559584-2adcae04-1d27-452d-ae32-93fc3f9f6919.jpeg)
nguyenpham89
