### ISSUE TITLE
Discard changes for newly created files does not work

### ISSUE THREAD

**Issue by crea7or** [desktop/desktop#16035]
### The problem

When new files has been added to the repo, not it's impossible to delete it via context menu item "Discard changes..".

### Release version

Version 3.1.5 (x64)

### Operating system

Windows 10 x64

### Steps to reproduce the behavior

1) Add file to the tracked repo.
2) Right click on the newly added file and select menu item "Discard changes..."

### Log files

2023-01-30T11:16:30.495Z - info: [ui] No submodules found. Skipping "git submodule status"
2023-01-30T11:16:31.276Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 1.669s)
2023-01-30T11:16:33.614Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 2.248s)

**Comment by sergiou87** [comment]
I just tried this and it works perfectly for me. Is there anything special about that repository? (being in a network drive, or something like Dropbox/OneDrive…)

**Comment by crea7or** [comment]
> I just tried this and it works perfectly for me. Is there anything special about that repository? (being in a network drive, or something like Dropbox/OneDrive…)

Oh yes, it's a mapped drive ... No a network one, but local. Is it a problem?

**Comment by sergiou87** [comment]
We've seen issues deleting files in the past because Desktop first tries to move them to the Recycle Bin, but that's not possible in some scenarios. Maybe this is one of them?

In that case, Desktop should warn you about this problem and ask you to delete the file permanently (instead of moving it to the Recycle Bin). Are those 3 lines all the logs you have? 😕

**Comment by crea7or** [comment]
Yes, that's all that I have. I'll try to take look at this code in the sources and maybe return with PR :)
