### ISSUE TITLE
line ending changes on discard changes

### ISSUE THREAD

**Issue by sousou99** [desktop/desktop#16038]
### The problem

On Windows system.
Set autocrlf to false In config.
core.autocrlf=false
Checkout a file, origin line ending is LF.
Do some change in the file and save it, line ending is still LF.
right click the file on GitHub.
Select "discard changes"
The line ending is changed to CRLF

### Release version

3.1.5 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

On Windows system.
Set autocrlf to false In config.
core.autocrlf=false
Checkout a file, origin line ending is LF.
Do some change in the file and save it, line ending is still LF.
right click the file on GitHub.
Select "discard changes"
The line ending is changed to CRLF

### Log files

[2023-01-30.desktop.production.log](https://github.com/desktop/desktop/files/10536969/2023-01-30.desktop.production.log)

**Comment by sergiou87** [comment]
I cannot reproduce this issue. Is it possible you have other settings like core.eol or some git attributes that could make this change?

**Comment by sousou99** [comment]
it's highly reproducible on my computer.
I also manage to reproduce it on another computer.
It happens everytime on file with eol=LF.
I checked my git config.

no core.eol defined.
core.autocrlf=false

**Comment by steveward** [comment]
@sousou99 can you open the repository in the command line and share the full output of `git config --list --show-origin` so that we can verify there isn't a config issue here?

**Comment by steveward** [comment]
@sousou99 I'm going to close this out as we haven't heard back from you, but let us know if you are still having issues and we can investigate further.

**Comment by sousou99** [comment]
Sorry, I didn't have time on this.
Here is the result of git config.

file:C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/etc/gitconfig	core.symlinks=false
file:C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/etc/gitconfig	core.autocrlf=false
file:C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/etc/gitconfig	color.interactive=true
file:C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/etc/gitconfig	color.ui=auto
file:C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/etc/gitconfig	pack.packsizelimit=2g
file:C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/etc/gitconfig	help.format=html
file:C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/etc/gitconfig	http.sslcainfo=%(prefix)/ssl/certs/ca-bundle.crt
file:C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/etc/gitconfig	diff.astextplain.textconv=astextplain
file:C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/etc/gitconfig	rebase.autosquash=true
file:C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/etc/gitconfig	filter.lfs.required=true
file:C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/etc/gitconfig	credential.helper=manager
file:C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/etc/gitconfig	credential.https://dev.azure.com.usehttppath=true
file:C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/etc/gitconfig	include.path=C:/Program Files (x86)/Git/etc/gitconfig
file:C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/Git/etc/gitconfig	include.path=C:/Program Files/Git/etc/gitconfig
file:C:/Program Files/Git/etc/gitconfig	diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/etc/gitconfig	filter.lfs.required=true
file:C:/Program Files/Git/etc/gitconfig	http.sslbackend=openssl
file:C:/Program Files/Git/etc/gitconfig	http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/etc/gitconfig	core.autocrlf=false
file:C:/Program Files/Git/etc/gitconfig	core.fscache=true
file:C:/Program Files/Git/etc/gitconfig	core.symlinks=false
file:C:/Program Files/Git/etc/gitconfig	core.editor="C:\\Program Files\\Notepad++\\notepad++.exe" -multiInst -notabbar -nosession -noPlugin
file:C:/Program Files/Git/etc/gitconfig	pull.rebase=false
file:C:/Program Files/Git/etc/gitconfig	credential.helper=manager-core
file:C:/Program Files/Git/etc/gitconfig	credential.https://dev.azure.com.usehttppath=true
file:C:/Program Files/Git/etc/gitconfig	init.defaultbranch=master
file:C:/Users/pliu/.gitconfig	credential.http://brigit.lln.iba:5000.provider=generic
file:C:/Users/pliu/.gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/pliu/.gitconfig	filter.lfs.process=git-lfs filter-process
file:C:/Users/pliu/.gitconfig	filter.lfs.required=true
file:C:/Users/pliu/.gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/pliu/.gitconfig	user.name=pliu
file:C:/Users/pliu/.gitconfig	user.email=pliu@iba-group.com
file:C:/Users/pliu/.gitconfig	merge.tool=tortoisemerge
file:C:/Users/pliu/.gitconfig	merge.bc3.driver=C:/Program Files (x86)/Beyond Compare 3/BCompare.exe
file:C:/Users/pliu/.gitconfig	merge.bc3.name=bc3
file:C:/Users/pliu/.gitconfig	merge.bc3.recursive=true
file:C:/Users/pliu/.gitconfig	merge.bc3.cmd=C:/Program Files (x86)/Beyond Compare 3/BCompare.exe
file:C:/Users/pliu/.gitconfig	mergetool.bc3.path=c:/Program Files (x86)/Beyond Compare 3/bcompare.exe
file:C:/Users/pliu/.gitconfig	credential.https://gitee.sw.goiba.net.provider=generic
file:.git/config	core.repositoryformatversion=0
file:.git/config	core.filemode=false
file:.git/config	core.bare=false
file:.git/config	core.logallrefupdates=true
file:.git/config	core.symlinks=false
file:.git/config	core.ignorecase=true
file:.git/config	submodule.source/libraries/image-reconstruction/cbct-reconstruction.url=http://pliu:imagximagx@brigit.lln.iba:5000/cbct-reconstruction
file:.git/config	gui.wmstate=zoomed
file:.git/config	gui.geometry=1034x563+30+30 426 255
file:.git/config	lfs.repositoryformatversion=0
file:.git/config	remote.origin.url=https://gitee.sw.goiba.net/pt/ai/adapt-insight.git
file:.git/config	remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config	branch.master.remote=origin
file:.git/config	branch.master.merge=refs/heads/master

And I do see a warning on the GUI.
![image](https://user-images.githubusercontent.com/18554688/225349579-c8281617-8ab8-454e-a8ff-817dfb439b3e.png)
