### ISSUE TITLE
Invoking certain menu items breaks Aero Snap state

### ISSUE THREAD

**Issue by rlabrecque** [desktop/desktop#1603]
**GitHub Desktop version:** 

0.5.4

**OS version:** 

Windows 10 1703

### Steps to Reproduce

1. Snap the Github Desktop window to half your screen using Win+Left/Right keys
1. Open any Dialog (About, Clone Repo, Add repo, etc)

**Actual behaviour:**

http://i.imgur.com/aruOJ5S.gifv

**Comment by niik** [comment]
Reproduced. That's pretty annoying.

@rlabrecque Gold star for including a gif ⭐️

**Comment by niik** [comment]
Looks like this happens whenever we execute a menu item that ends up sending an ipc message back to the renderer. Clicking on `View -> Changes` for example reproduces this.

**Comment by rlabrecque** [comment]
> Gold star for including a gif ⭐️

Ironically I only found this because I setup my windows this way to capture a different problem!
