### ISSUE TITLE
Fix update notifications to be non-disruptive to end user tasks

### ISSUE THREAD

**Issue by OliKei** [desktop/desktop#16034]
### The problem

github desktop constantly interrupts end user work when using keyboard only, disrupts the foreground window's user tasks, such as typing a document or source code, and asks for a user prompt to trigger software updates of github, even when the github windows is not in focus. 
This interrupts efficient keyboard input and shall be stopped. Apple provides APIs to show notification messages without interruptions, so please make use of these kind of software notifications. 
<img width="292" alt="Bildschirm­foto 2023-01-30 um 7 53 23 AM" src="https://user-images.githubusercontent.com/55189440/215408423-539dd978-5e88-4c5e-a0fb-fb75100949c8.png">

Specifically if github has no focus the appearance of this update dialog must be avoided to not disturb users while typing, specifically when typing without constantly tracking the screen.

### Release version

Version 3.1.2 (x64)

### Operating system

macOS

### Steps to reproduce the behavior

1. Work on your favorite word processor of source code editor.
2. Work as long as github interrupts with the dialog shown in the screenshot.

### Screenshots

<img width="292" alt="Bildschirm­foto 2023-01-30 um 7 53 23 AM" src="https://user-images.githubusercontent.com/55189440/215408589-91997ec7-dc7f-4cb2-a694-3f662a4cc154.png">

**Comment by niik** [comment]
Hey @OliKei, thanks for reaching out. Could you tell us a little more about your current setup and about how you installed GitHub Desktop? That authentication dialog is not something that I'd expect you to see and I'd like to understand what the difference is between your environment and mine. Are you an administrator of your machine?

For reference, GitHub Desktop will automatically download updates in the background but it is not designed to prompt the user while it's doing so. It downloads the update and then shows a message in the app itself that informs the user that an update is available and ready to install. Did you install Desktop via https://desktop.github.com or through some other means?

**Comment by sergiou87** [comment]
This is probably the same as #13956, where _somehow_ the app's files permissions changed, and restoring your machine using Migration Assistant seems to be the common reason.
