### ISSUE TITLE
Cannot view Avatar in GHE Repo

### ISSUE THREAD

**Issue by yellis** [desktop/desktop#1604]
### Description

I have a number of repos loaded, all from my GHE (if that makes a difference). Avatars are showing broken images in all of the history lines

### Version

**GitHub Desktop version:** 0.5.4

**OS version:** Microsoft Windows 10.0.15063

### Steps to Reproduce

1. Open GH Desktop
2. Go to any rep, history tab

**Expected behaviour:** see avatars on history lines

**Actual behaviour:** broken images

**Reproduces how often:** Every time I open the app

### Logs

[2017-05-17.desktop.production.log.txt](https://github.com/desktop/desktop/files/1010110/2017-05-17.desktop.production.log.txt)

**Comment by shiftkey** [comment]
Closing in favour of https://github.com/desktop/desktop/issues/821 which has more details about the issue.
