### ISSUE TITLE
Client does not recognize deleted tags from GitHub

### ISSUE THREAD

**Issue by ariffjeff** [desktop/desktop#16046]
### The problem

Tags deleted from GitHub website directly do not get reflected in GitHub Desktop when you click the Fetch origin button.

### Release version

Version 3.1.5 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. In GitHub Desktop, create a tag on a commit
2. Push it to the GitHub repo
3. Delete the tag directly on the GitHub website (releases page in the tags tab)
4. Click the Fetch origin button in GitHub Desktop
5. You will see that the commit history does not get updated to reflect that the tag was deleted

**Comment by sergiou87** [comment]
`git fetch` and `git pull` from the command line don't seem to do delete the tag locally either, so I'm inclined to think this is "expected behavior" or, at least, a scenario that wasn't considered. I'll label this as an enhancement for further discussion.

Thanks for your report!

**Comment by niik** [comment]
Seems we're getting a few of these lately. I did write up an answer in https://github.com/desktop/desktop/issues/16032#issuecomment-1408219629 which is applicable here as well.

> [...] Unfortunately this is by design. Git itself will not ever automatically delete a tag that's been fetched from the upstream without the user explicitly telling it to do so. See https://git-scm.com/docs/git-tag#_on_re_tagging for more information about why this is the case.
> 
> In order to get rid of the deleted tag you currently have to manually execute `git tag -d TAGNAME` locally.
> 
> I'm closing this as GitHub Desktop relies on the underlying functionality of Git here so there's nothing for us to do. For supporting deleting tags from GitHub Desktop please see https://github.com/desktop/desktop/issues/9938
