### ISSUE TITLE
The download button linked with a wrong url

### ISSUE THREAD

**Issue by xiaobsh** [desktop/desktop#16058]
![image](https://user-images.githubusercontent.com/88483240/216609991-5e083b65-8da7-4f0f-8a29-02cb39b7b718.png)
It is redirected to https://github.com/github-desktop/releases/3.1.5-08d57d4b/GitHubDesktopSetup-x64.exe, a wrong url.
Is it allowed to submit the feedback here?

**Comment by niik** [comment]
Hey @xiaobsh, yup, you're absolutely okay to submit that feedback here. I am however not able to reproduce this myself. That link should go to `https://central.github.com/deployments/desktop/desktop/latest/win32` which in turn redirects to the proper url `https://desktop.githubusercontent.com/github-desktop/releases/3.1.5-08d57d4b/GitHubDesktopSetup-x64.exe`.

```shellsession
% curl -sI https://central.github.com/deployments/desktop/desktop/latest/win32|grep location
location: https://desktop.githubusercontent.com/github-desktop/releases/3.1.5-08d57d4b/GitHubDesktopSetup-x64.exe
```

Could you provide some more details on what browser you're using, what operating system, whether you're using any browser extensions or anti-virus solutions on your machine?

Thanks!

**Comment by xiaobsh** [comment]
![Snipaste_2023-02-03_21-57-45](https://user-images.githubusercontent.com/88483240/216621648-484934f1-482b-4014-8e1e-91c23b62bb73.png)
Edge, v109.0.1518.70 (stable) (64 bit)

**Comment by xiaobsh** [comment]
> 嘿@xiaobsh，是的，您绝对可以在此处提交反馈。但是，我自己无法重现这一点。该链接应该转到该链接，然后重定向到正确的网址。`https://central.github.com/deployments/desktop/desktop/latest/win32``https://desktop.githubusercontent.com/github-desktop/releases/3.1.5-08d57d4b/GitHubDesktopSetup-x64.exe`
> 
> ```
> % curl -sI https://central.github.com/deployments/desktop/desktop/latest/win32|grep location
> location: https://desktop.githubusercontent.com/github-desktop/releases/3.1.5-08d57d4b/GitHubDesktopSetup-x64.exe
> ```
> 
> 您能否提供有关您使用的浏览器，操作系统，是否在计算机上使用任何浏览器扩展或防病毒解决方案的更多详细信息？
> 
> 谢谢！



> 嘿@xiaobsh，是的，您绝对可以在此处提交反馈。但是，我自己无法重现这一点。该链接应该转到该链接，然后重定向到正确的网址。`https://central.github.com/deployments/desktop/desktop/latest/win32``https://desktop.githubusercontent.com/github-desktop/releases/3.1.5-08d57d4b/GitHubDesktopSetup-x64.exe`
> 
> ```
> % curl -sI https://central.github.com/deployments/desktop/desktop/latest/win32|grep location
> location: https://desktop.githubusercontent.com/github-desktop/releases/3.1.5-08d57d4b/GitHubDesktopSetup-x64.exe
> ```
> 
> 您能否提供有关您使用的浏览器，操作系统，是否在计算机上使用任何浏览器扩展或防病毒解决方案的更多详细信息？
> 
> 谢谢！



> Hey @xiaobsh, yup, you're absolutely okay to submit that feedback here. I am however not able to reproduce this myself. That link should go to `https://central.github.com/deployments/desktop/desktop/latest/win32` which in turn redirects to the proper url `https://desktop.githubusercontent.com/github-desktop/releases/3.1.5-08d57d4b/GitHubDesktopSetup-x64.exe`.
> 
> ```
> % curl -sI https://central.github.com/deployments/desktop/desktop/latest/win32|grep location
> location: https://desktop.githubusercontent.com/github-desktop/releases/3.1.5-08d57d4b/GitHubDesktopSetup-x64.exe
> ```
> 
> Could you provide some more details on what browser you're using, what operating system, whether you're using any browser extensions or anti-virus solutions on your machine?
> 
> Thanks!

![Snipaste_2023-02-03_21-57-45](https://user-images.githubusercontent.com/88483240/216621648-484934f1-482b-4014-8e1e-91c23b62bb73.png)
Edge, v109.0.1518.70 (stable) (64 bit)

**Comment by xiaobsh** [comment]
> Hey @xiaobsh, yup, you're absolutely okay to submit that feedback here. I am however not able to reproduce this myself. That link should go to `https://central.github.com/deployments/desktop/desktop/latest/win32` which in turn redirects to the proper url `https://desktop.githubusercontent.com/github-desktop/releases/3.1.5-08d57d4b/GitHubDesktopSetup-x64.exe`.
> 
> ```
> % curl -sI https://central.github.com/deployments/desktop/desktop/latest/win32|grep location
> location: https://desktop.githubusercontent.com/github-desktop/releases/3.1.5-08d57d4b/GitHubDesktopSetup-x64.exe
> ```
> 
> Could you provide some more details on what browser you're using, what operating system, whether you're using any browser extensions or anti-virus solutions on your machine?
> 
> Thanks!

![Snipaste_2023-02-03_21-57-45](https://user-images.githubusercontent.com/88483240/216621648-484934f1-482b-4014-8e1e-91c23b62bb73.png)
Edge, v109.0.1518.70 (stable) (64 bit)

**Comment by xiaobsh** [comment]
> Hey @xiaobsh, yup, you're absolutely okay to submit that feedback here. I am however not able to reproduce this myself. That link should go to `https://central.github.com/deployments/desktop/desktop/latest/win32` which in turn redirects to the proper url `https://desktop.githubusercontent.com/github-desktop/releases/3.1.5-08d57d4b/GitHubDesktopSetup-x64.exe`.
> 
> ```
> % curl -sI https://central.github.com/deployments/desktop/desktop/latest/win32|grep location
> location: https://desktop.githubusercontent.com/github-desktop/releases/3.1.5-08d57d4b/GitHubDesktopSetup-x64.exe
> ```
> 
> Could you provide some more details on what browser you're using, what operating system, whether you're using any browser extensions or anti-virus solutions on your machine?
> 
> Thanks!

Sorry, there might be something wrong with my browser settings. I tried it in another browser and it worked normally. It can also work in InPrivate Tab in Edge or with a new user config in Edge.
I'll try to find the reason by myself, thanks.

**Comment by neo-seeker** [comment]
The redirects to download page happen when you are not logged in to your Github account in the browser you are using. I was getting the same issue and then post logging in to my Github account the redirects stopped and would direclty open the Github Desktop app for cloning.
