### ISSUE TITLE
Virus Warning: refused to launch

### ISSUE THREAD

**Issue by JackSalzman** [desktop/desktop#16065]
### The problem

GitHub Desktop refuses to launch and gatekeeper thinks that its definitely a virus.

### Release version

Latest

### Operating system

macOS 13.1

### Steps to reproduce the behavior

Go to applications
open GitHub Desktop
error occurs (see screenshot)

### Screenshots

![Screenshot 2023-02-04 at 10 16 44 PM](https://user-images.githubusercontent.com/107004479/216790038-41a69879-b418-4292-b0dd-f702bf3c6745.jpg)

### Additional context

GitHub Desktop Arm version

**Comment by u-l-y** [comment]
@JackSalzman https://www.malwarebytes.com/blog/news/2023/02/github-revokes-several-certificates-after-unauthorized-access

**Comment by sergiou87** [comment]
As @u-l-y mentions, we think this is related to the recent revocation of the signing certificates. You can find more information here: https://github.com/desktop/desktop/issues/16052

Also, are you sure it was in the latest version? The last version affected by this should be 3.1.1.

**Comment by jack58865** [comment]
same happened with me

**Comment by shyed2001** [comment]
A few months ago my GitHub Desktop just vanished from my computer, then came back again. Yesterday I could not git push to the main. Today the update for GitHub desktop got blocked as a virus. Now it got uninstalled. What to do now?
