### ISSUE TITLE
Sign in Problem

### ISSUE THREAD

**Issue by ARehman07** [desktop/desktop#16067]
### The problem

Im not able to sign in github desktop. When it redirects to browser for sign in  then after sign in process browser shows a pop up to open desktop app despite of clicking on open desktop app in browser github app is still waiting for the browser to redirect

### Release version

3.1

### Operating system

Windows 10

### Steps to reproduce the behavior

Install the app.
Open and click on login using github account.
Sign in on browser and after completion click on open github app

### Screenshots

![Screenshot (8)](https://user-images.githubusercontent.com/81951169/216812550-167922f9-ee8e-4419-a0d0-2f8a47da19fc.png)

**Comment by niik** [comment]
Hey @ARehman07, thanks for reaching out. Could you try switching your OS default browser to another browser temporarily to see if that fixes the issue? It appears you've got both Brave and Firefox installed. Other users have reported being able to sign in after switching their default browser, please give that a go and let us know!
