### ISSUE TITLE
Add support for INI files

### ISSUE THREAD

**Issue by ajtruckle** [desktop/desktop#16066]
### The problem

INI files are simple text files but the software is saying it is a binary file. I should be able to see INI text files.

### Release version

3.1.6 beta 2

### Operating system

Windows 11

### Steps to reproduce the behavior

Add a INI file to your project and make changes so that the file gets listed as modified. Select it to see the changes.

### Log files

I don't think the logs are relevant.

### Screenshots

![GitHub](https://user-images.githubusercontent.com/7985331/216812382-f897feae-6870-418c-9f43-a8d6fc521c13.jpg)

**Comment by steveward** [comment]
@ajtruckle thanks for the issue. It's likely the file encoding is causing the `.ini` files to be viewed as binary. I'd recommend looking into the [working-tree-encoding](https://git-scm.com/docs/gitattributes#_working_tree_encoding) feature Git has which allows you to work around this issue.

Since this isn't a specific problem with GitHub Desktop I'm going to close this out, but let me know if you have any further questions.

**Comment by ajtruckle** [comment]
@steveward Having just momentarily glanced that link it seems very complicated. Why doesn't is have some visual examples or a video tutorial? I don't think I will worry. TortoiseGit already supports it:
![TortoiseGit](https://user-images.githubusercontent.com/7985331/217065901-32f08beb-ebcd-41b4-aa4d-209d96f98956.jpg)
So I don't see why I need to fiddle with extra maintenance of other data files for what should already be known as a text file.

**Comment by steveward** [comment]
@ajtruckle unfortunately Git just doesn't handle diffing UTF-16 out of the box which I can see that file is. There are workarounds like I mentioned but they do require configuration, and at this time it isn't something we plan to make configurable directly in GitHub Desktop. You would need to add something like this to your repository's `.gitattributes` file:

`*.ini          text working-tree-encoding=UTF-16LE eol=CRLF`

You could try that out to see if it gets things working.

**Comment by ajtruckle** [comment]
@steveward Doesn't work.

1. Created the file in the same folder as the ini files.
2. I pushed the new `.gitattributes` file to server.
3. I started GitHub Desktop and INI files still show as binary .

What did I do wrong?

Also, when I have the above file in place then TortoiseGit can no longer push. It complained. I think it is because according to NotePad++ my INI files are UTF-16 LE **BOM**.

**Comment by ajtruckle** [comment]
@steveward  I tried changing it to:

`*.ini          text working-tree-encoding=UTF-16LE-BOM eol=CRLF`

Still does not work in GutHub Desktop.

**Comment by steveward** [comment]
You can check by running this command to see if things are set correctly:

`git check-attr -a <filename>.ini`

Is there an existing `.gitattributes` file that could possibly be taking precedence here?

**Comment by ajtruckle** [comment]
@steveward It says:

```
$ git check-attr -a MeetSchedAssist_Labels_ZUL.INI
MeetSchedAssist_Labels_ZUL.INI: text: set
MeetSchedAssist_Labels_ZUL.INI: working-tree-encoding: UTF-16LE-BOM
MeetSchedAssist_Labels_ZUL.INI: eol: CRLF
```

But Github Desktop says:

![GD](https://user-images.githubusercontent.com/7985331/217267339-b87d79ee-95c0-45ad-8a40-f1291f3b5147.jpg)

I only have the one file in the folder where the INI files are.

**Comment by tdalon** [comment]
This is annoying
