### ISSUE TITLE
unborn HEAD "branch unknown"

### ISSUE THREAD

**Issue by DoFitO-dev** [desktop/desktop#16062]
### The problem

When i click on github desktop and open my repository the "main" branch is not showing in the desktop app and when i checked the repository in the github web it was there. it was alos showing "unknown branch" in the branch section in github desktop.

### Release version

3.1.5 (x64)

### Operating system

Windows 10

### Log files

Error: ----

fatal: cannot lock ref 'HEAD': unable to resolve reference 'refs/heads/main': reference broken

Logs: ----

[2023-02-01.desktop.production.log](https://github.com/desktop/desktop/files/10607947/2023-02-01.desktop.production.log)
[2023-02-04.desktop.production.log](https://github.com/desktop/desktop/files/10607948/2023-02-04.desktop.production.log)

**Comment by niik** [comment]
Hey @DoFitO-dev, thanks for reaching out. Is this issue still occurring? I'm looking at your logs and it seems there's something going wrong when cloning the repository and I'm wondering if this could have been a temporary hiccup on the remote side

```
remote: Total 48 (delta 24), reused 36 (delta 12), pack-reused 0        
fatal: bad object refs/heads/main
error: [...] did not send all necessary objects
```

**Comment by DoFitO-dev** [comment]
@niik it's working when I delete the folder and clone it again but after a day or when I open it after some hours the error comes again so it's like i have delete and clone again everytime

**Comment by steveward** [comment]
Could you open the repository in the command line and run `git fsck` and let us know the full output of that command? That should hopefully give some more information about what might be happening here.

**Comment by DoFitO-dev** [comment]
@steveward it's working fine now, no problems are there, so i am gonna close this issue. Thank you..
