### ISSUE TITLE
Add option to select text encoding for diffs

### ISSUE THREAD

**Issue by goslife** [desktop/desktop#1607]
I would like The new desktop github have option to select text encoding for push code except UTF-8 in Option setting.

**Comment by shiftkey** [comment]
>  select text encoding for push code

Git doesn't care about your encodings when it comes time to store and send blobs around. Is this related to how things are displayed in the app? Do you have some examples which show the problem?

**Comment by goslife** [comment]
For example in Classic Desktop Github for Windows. I develop PHP project for direct print slip that php_printer.dll module not support UTF-8. I must use TIS-620 for Thai language in slip. When I commit code, The preview code of change not show character in Thai language that can easily be understood as pictured.
![2017-05-20_10-00-26](https://cloud.githubusercontent.com/assets/919501/26272494/f11cb028-3d43-11e7-9cd8-162adc6f7b25.jpg)
If the new desktop github can select text encoding for push or **preview** code except UTF-8, it solve this problem.

**Comment by shiftkey** [comment]
@goslife this looks like our diff output isn't handling your encodings correctly, which is a known limitation.

I started experimenting with this a while ago in #634, which I would like to revive at some point, but there are some UX questions that I didn't really get to tackle at the time, and integrating the details we can gather in the clients with our existing encoding detection work in GitHub itself needs to be explored more.

**Comment by shiftkey** [comment]
This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.
