### ISSUE TITLE
How can I recover the lost stashes, when the repository from GitHub Desktop is deleted?

### ISSUE THREAD

**Issue by Ali10442** [desktop/desktop#16078]
### The problem

My repository from the GitHub was deleted, I had few stashed changes in the repository, now I'm unable to find the stashed changes after cloning the repository again. 
Need help in restoring the stashed changes which were never dropped but are lost.

### Release version

Version 3.1.5 (x64)

### Operating system

Windows 10

**Comment by niik** [comment]
Hi @Ali10442, thanks for reaching out, sorry to hear you're running into problems!

Stashes are stored locally on your machine (see [git-stash](https://git-scm.com/docs/git-stash)) so if you have deleted the repository from your local machine then those stashes will unfortunately be lost along with any other changes that you have yet to push to the remote.

If you haven't deleted the repository but have lost a stash there's a good chance that it can be recovered by using the reflog. and then restoring them using git cherry-pick. This will require a little fiddling around in the command line but fortunately there are plenty of guides out there on how to restore lost commits. See for example https://www.geeksforgeeks.org/recovering-lost-commits-in-git/ and https://rewind.com/blog/how-to-restore-deleted-branch-commit-git-reflog/.

I'm going to close this issue out as it, however unfortunate, doesn't appear to be a bug with GitHub Desktop per se but rather an unexpected consequence of how Git stores stashes. I hope you are able to recreate your stashed changes and feel free to comment here if you think my answer is lacking or you need more information.

**Comment by Ali10442** [comment]
I do have the repository in my local machine, however I'm unable to run the commands you mentioned above there since there is no .git folder (since the repository has been deleted from GitHub Desktop), could you help me further on this? I do have the logs

**Comment by niik** [comment]
> there is no .git folder (since the repository has been deleted from GitHub Desktop)

If there's no .git folder then we're not going to have any luck with those commands as that's where Git stores all the data (including stashes). Deleting the repository from GitHub Desktop does not delete the .git folder though so I think I'm missing something here. Did you select the option to also move the repository to trash when you removed it from Desktop? If that's the case then the .git folder (and the entire repo) should be in your recycle bin/trash.

**Comment by Ali10442** [comment]
I somehow managed to retrieve the old repository, now when I'm trying to run the command git reflog, I'm getting this error : fatal: your current branch 'master' does not have any commits yet

I believe this is because I recently cloned the repository again, however ideally I shouldn't be getting this error because I'm running this command in the old repo itself

**Comment by Ali10442** [comment]
I further dug deeper and found a stash file in .git > refs folder with some numbers and special characters something like this : 3¬'ß«?Š©BL:WT°r7ÒåÊù‡.F!ø®¬sø

can this be used to restore my stashed changes? 
I also have the logs from the date when I stashed changes, where I do see the stash entry data, however there is no dropped stash (data/number) listed there

**Comment by niik** [comment]
That doesn't look like what I'd expect to see in the stash ref. It should look like an ordinary commit id. Is it possible your `.git` folder got corrupted somehow or you didn't restore it properly? Either way you could try running `git reflog --all` to see if there's anything to find in the reflog. You can also run `git fsck` to see if your repo appears to be corrupted.

**Comment by Ali10442** [comment]
Those commands didn't help either!! Would replacing the .git folder in the new repo with the old one help?

**Comment by niik** [comment]
You have to be more specific, what happened when you ran those commands?

You said earlier that you had logs that showed "the stash entry data". What data is that. You could try looking for lines in that log file that look similar to `git stash show 603a9e56d98ec9b1741250bd750e7dfd36ec900d`. That SHA towards the end of the file would be the id of a stash entry (though it could be from any repository). You could try copying and pasting that into your terminal to see if that stash object exists in the .git folder you're working with now.

> Would replacing the .git folder in the new repo with the old one help?

No, the `.git` folder is self-contained and contains all the data stored in the repository (committed files, branches, stashes etc).

**Comment by Ali10442** [comment]
I did not get anything on running this - git reflog --all and for this command -  git fsck, this is what I got: Checking object directories: 100% (256/256), done.
notice: HEAD points to an unborn branch (master)
notice: No default references
 
I did not find any similar line in that log with "git stash show ", however I do see the popped stash with commit ID, on running commands git stash apply [stash_hash], I see this error 
$ git stash apply 60ed3b8fd0c62919b8b989837f1481b0f691a105
fatal: '60ed3b8fd0c62919b8b989837f1481b0f691a105' is not a stash-like commit
