### ISSUE TITLE
can we have reorderable remote repo profile setting ,so we can sync our repo to diffrenent git host just with a single click.

### ISSUE THREAD

**Issue by Bian-Sh** [desktop/desktop#16085]
### The feature request

can we have a reorderable remote repo profile  settings ,so we can sync our repo to diffrenent git host just with a single click or simply drag the profile to the top of the profile list .
Sorry for my Chinglish，哈哈~
![image](https://user-images.githubusercontent.com/24520547/217461818-142bf336-285c-4d7b-b97c-a040960b3bb0.png)

### Proposed solution

 we can sync our repo to diffrenent git host just with a single click

**Comment by steveward** [comment]
Thanks for the feedback @Bian-Sh. Multi-remote support has been previously requested in https://github.com/desktop/desktop/issues/1442, I'll reference this issue there.
