### ISSUE TITLE
Issue on opening page 

### ISSUE THREAD

**Issue by gerardol29** [desktop/desktop#16081]
### The problem

I have created a new repository and cannot open the link (gerardol29.github.pe), even though I have already attached the documents to the github carpet.

### Release version

Version 3.1.6

### Operating system

Windows

### Log files

![gtb1](https://user-images.githubusercontent.com/121451020/217339153-5939154d-2cbf-4435-9d65-887c4c86315b.png)
![gtb](https://user-images.githubusercontent.com/121451020/217339156-ca051114-8e6b-4838-9915-fd1807175a14.png)

### Screenshots

![image](https://user-images.githubusercontent.com/121451020/217339185-a132597a-d073-4d29-99ca-11c41d03190f.png)
![image](https://user-images.githubusercontent.com/121451020/217339191-a1b27227-e008-48a7-abef-6908ab8e9dac.png)

**Comment by steveward** [comment]
@gerardol29 this issue tracker is for GitHub Desktop, I'd recommend asking for assistance on the Pages section of the GitHub Community Forum:

https://github.com/orgs/community/discussions/categories/pages

I hope that helps!
