### ISSUE TITLE
Github Desktop shows 0 files changed

### ISSUE THREAD

**Issue by jmikell821** [desktop/desktop#16084]
### The problem

I've edited and saved files in my editor (Madcap Flare), but Github Desktop shows 0 files changed, even though when they're committed and pushed, the changes appear in Github. I extensively use GH Desktop for file comparison, so I depend on this feature a lot. I've also deleted and re-added the repo but the same issue persists. 

Files edited/saved: 
![image](https://user-images.githubusercontent.com/57149392/217411277-72cc0154-d173-480c-9ef8-06f3e0d13cd8.png)

0 changed files in Github _should_ show file diff, but it's blank: 
![image](https://user-images.githubusercontent.com/57149392/217411367-5e5feefd-93d1-4a67-8815-b1146ea7d06d.png)

### Release version

3.1.6

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Edit/save files in editor. 
2. Select "Changed" tab in GH Desktop. 
3. Observe that there are no changed files, no diff to compare. 
4. Committed changes do appear in actual Github browser.

**Comment by niik** [comment]
Hey @jmikell821, thanks for reaching out.

> 4\. Committed changes do appear in actual Github browser.

Based on this it sounds like you're making the commit outside of Desktop then, in that editor in your first screenshot perhaps? Does your changes show up in the History tab?

**Comment by jmikell821** [comment]
@niik yes, I committed the changes via my editor, because Desktop wouldn't let me. I prefer to push/pull/commit from Desktop. Changes do appear in the History tab once committed. Also, not sure if it matters, but I'm running Windows 10 on a virtual machine. I use Desktop on my Mac with no issues. 

![image](https://user-images.githubusercontent.com/57149392/217572349-6fca91d8-25c7-4544-aa95-4481803df98f.png)

**Comment by jmikell821** [comment]
I was able to get this to work, so closing for now. Will reopen if the issue persists.

**Comment by HohJD** [comment]
Hi @jmikell821 can you share how you resolve this error, I having similar experience

**Comment by ActiveTutorial** [comment]
me to
Edit:
I forgot to press the "Push to Origin" Button make sure you press that
