### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by jusjiayi** [desktop/desktop#16093]
### The problem

I commit my work on my new computer
![error](https://user-images.githubusercontent.com/50310983/217763074-cb94df0b-cc69-4fba-9f66-d82167f24f4a.PNG)

### Release version

no idea

### Operating system

windows 10

### Steps to reproduce the behavior

Push Origin

**Comment by sergiou87** [comment]
👋 Hello! Have you signed in from Settings -> Accounts? That should be enough 🤞
