### ISSUE TITLE
Not a feature, but I guess really good improvement

### ISSUE THREAD

**Issue by miraving** [desktop/desktop#16099]
### The feature request

I often work with the program. and I often notice that there is an inconvenience in understanding which branch is currently active because the branch name is not fully displayed. 
If possible, please increase the width of the branch switching control. 

### Proposed solution

increase the width of the branch switching control

**Comment by steveward** [comment]
Thanks for the feedback @miraving! I'll reference this in https://github.com/desktop/desktop/issues/4569 where we are tracking this issue.
