### ISSUE TITLE
Show conflicted files

### ISSUE THREAD

**Issue by Mike-3** [desktop/desktop#16092]
### The feature request

I did a compare to branch. Below it shows me that I have conflicts. Is there a way to view the conflicting files?
![grafik](https://user-images.githubusercontent.com/70719484/217737470-cec14b6a-9a56-4333-b852-d116b89dbdf7.png)

I don't want to do a merge, I just want to fix the conflicts in advance.

### Proposed solution

Show conflicted files

**Comment by tidy-dev** [comment]
:wave: The only way to resolve the conflict is to merge one branch into the other. The typical workflow if you are trying proactively resolve conflicts before merging a feature/change into a main working branch is that you would merge the main branch into a feature branch 

If you only want to see what the conflicts are, you could start the merge process and then abort without resolving them.
