### ISSUE TITLE
Switch Between Multiple Accounts on Github Desktop

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#16104]
### The feature request

I regularly use various accounts for work and personal use. Is there anyway to add multiple personal accounts in Github Desktop ?

### Proposed solution

Multiple account switch could really benefit various users depending on their usage.

**Comment by anju-coco** [comment]
電波の子に血がある話している拡散に警察疑惑のとこ・・

**Comment by niik** [comment]
Hey @harish-csusb, thanks for reaching out. There's no way to add multiple GitHub.com accounts to Desktop at this time. You can have one GitHub.com account and one GitHub Enterprise Server account. We are tracking support for multiple accounts in https://github.com/desktop/desktop/issues/3707. Please subscribe to that issue to follow along with any development.

**Comment by drewkovihair** [comment]
This is not an acceptable response to the issue...? We should not be tied down to a single account and should be able to login and logout with multiple accounts while keeping the GitHub repos for each account. Is that possible or no, without the word salad.

**Comment by steveward** [comment]
@drewkovihair this is something we're planning to support in the future, please follow along in https://github.com/desktop/desktop/issues/3707.

**Comment by jfferreira97** [comment]
better get on it sooner rather than later rather than wasting time recreating devin

**Comment by eyuperdogan** [comment]
+1

**Comment by krishzala** [comment]
I've one personal account and one working account if multiple accounts are accessible with GitHub desktop that should be a very good idea. Please take note of this...

**Comment by caspar-uneti** [comment]
This feature is a massive gap currently. Working with multiple accounts is very painful.

**Comment by faheemstepsharp** [comment]
Please fix this MAIN ISSUES :( i have to make another user account to use a sample thing

**Comment by Xonatron** [comment]
This is important enough to move to another client. Please add this feature.

**Comment by benjaminpartida** [comment]
i really need this feature ! second this

**Comment by dante-militello** [comment]
Holy sh** is unacceptable not to have this feature on 24 😢

**Comment by JSensebe-work** [comment]
With so many people working from home these days, this is a real issue.

**Comment by ashishanand7** [comment]
lol the most important feature to a client like this over bash commands doesn't exist.

**Comment by mdziedzic-ct** [comment]
<img width="166" alt="Screenshot 2024-09-30 at 4 26 21 PM" src="https://github.com/user-attachments/assets/39657910-f878-457d-b252-7a176940e03f">
based on the closed designation I am guess there is no time table

**Comment by doyajii1** [comment]
I end up sign out and sign in to different account every time. Multiple account solution would be real nice. please? 🙏

Ex. GitHub Desktop OSX UI > "GitHub Desktop" from top menu  > "Settings" > "Account" tab - "Sign Out of GitHub.com" > "Sign Into GitHub.com" > Choose the other account in browser login.

**Comment by officialstareye** [comment]
This is required, why is this not a feature in 2024? Tell your seemingly junior product manager to prioritize this so that people don't end up switching to different clients please.

**Comment by valence-fred** [comment]
I Cant wait enough for this feature

**Comment by dyram-ivoyant-eng** [comment]
@niik, please prioritize & implement this 😩

![image](https://github.com/user-attachments/assets/93ec0ad3-f647-40e6-9703-1df5a178ba01)

**Comment by calvinmiguel** [comment]
I also need this. What is the Github team doing!

**Comment by ThePayr** [comment]
How can this not be added already? This speaks so bad of the GitHub Desktop dev team...

**Comment by afrolisbon** [comment]
Still waiting for this feature :)

**Comment by hariPrasadCoder** [comment]
We want this!!!

**Comment by Heryk13** [comment]
we need this!!!

**Comment by IRediTOTO** [comment]
world need this :D

**Comment by jivansupe** [comment]
I encountered this.. but then wrote a script to do this switching more easy on just a command. This could be used to access the repos using cmd. 
Attaching a README file and the script file. Update the dummy_sh.txt to your credentials, rename the file and make it work. Use README if you are stuck anywhere. 

Happy Switching Account 🎉🤩

[README.md](https://github.com/user-attachments/files/18146157/README.md)
[dummy_sh.txt](https://github.com/user-attachments/files/18146178/dummy_sh.txt)

**Comment by al786999** [comment]
still not a thing?? I thought I was going crazy

**Comment by riyajmulla-jet** [comment]
we need this

**Comment by Github-MuhammadNiazi** [comment]
There are so many ways we can resolve this issue. Startup selection, Easy switching, Dual apps. The end user needs this badly.

**Comment by tomichGIT** [comment]
As a profesor in a web developer institute you would understand how IMPORTANT this feature is. Please add it soon (FYI we are in 2025 now)

**Comment by jfferreira97** [comment]
After thinking deeply about this for the last few months, this change isn't really worth it.
With the way tech is going, sometimes at the end of the day all we have to show for it is a darker green square on github.

Let it be, let's do everything from the same account.

**Comment by tylerrrkd** [comment]
it is now 2025, what?

**Comment by blksmr** [comment]
we need that thang

**Comment by jjunk93** [comment]
plz..

**Comment by ankit-olatech** [comment]
Can't believe such basic functionality is not given in the first place....wake up!

**Comment by Xonatron** [comment]
Is there a way for us to have GitHub prioritize this feature?

**Comment by Xonatron** [comment]
I noticed this issue was closed at some point, so I started a new issue and linked it back to this discussion: https://github.com/desktop/desktop/issues/20028

**Comment by tomsoffroad** [comment]
I think having the same kind of interface/account selector as google would be so nice... 

Where one could easily swap from a work account back to home account and visa versa. 
You can be logged into multiple accounts, and be able to switch to the one you want... (work repo to personal repo)

**Comment by HaydenSexton** [comment]
how is this still not a thing

**Comment by YSStudios** [comment]
Hurry

**Comment by FamilyGuy1999** [comment]
how is it that hard to addd account switching

**Comment by dogadogan** [comment]
Any updates? @niik @steveward?

**Comment by IRediTOTO** [comment]
I follow this issue from 2023 :D someone like me?

**Comment by YeapAsmir** [comment]
Note that the github cli already offers to do `gh auth switch`

**Comment by Sodj** [comment]
If both the CLI and the Website provide this feature, how can you say it's not worth it?

**Comment by chuongmep** [comment]
+1, why it closed ?

**Comment by skaboy71** [comment]
Wow ... really??  Since 2018?? C'mon!!

**Comment by marzooq703** [comment]
I can build this feature, anyone ready to collaborate with me?

**Comment by ashmankumar** [comment]
As a workaround you can set up an ssh profile for your alternative account (the one that isn't logged in using Github desktops auth) and clone your repositories. You can add git managed repos via SSH to Github Desktop using the add existing repos option. It asks you for your passphrase the first time and then you can work with it as normal.

It will show up in the 'others' section though so there is no organisation if you have other accounts.  You also can't select view on github

**Comment by OgPenguu** [comment]
I managed to create this project but they need a "valid token", which i have no idea how to create/find so i just gave up on the project very quickly haha

https://github.com/OgPenguu/Github-Desktop-Switcher

**Comment by KCBF** [comment]
It’s already January 2026. Is this still not implemented?

**Comment by OgPenguu** [comment]
> It’s already January 2026. Is this still not implemented?

i guess so lol

**Comment by areeb-rehman-dev** [comment]
Are there any chances that this feature gets implemented?

Edit: February 2026

**Comment by OgPenguu** [comment]
@areeb-rehman-dev its not even hard, but it appears as if they dont want to impliment it..

**Comment by Sodj** [comment]
With how many AI agents and bots there are, this could've been vibe-coded in matter of minutes
Not that I condone submitting unadultrated AI slop code but at this point I'll take whatever over having to login using 2FA

**Comment by GaneshMBabu** [comment]
<img width="640" height="362" alt="Image" src="https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExaW14ZXg0dXY5YnN2Mnh6OWttMzE0aG4zaXljNTI0cXFvenAzczNyYSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/pFZTlrO0MV6LoWSDXd/giphy.gif" />

**Comment by dante-militello** [comment]
> Holy sh** is unacceptable not to have this feature on 24 😢

I wrote this comment in Sept 2024, 17 months ago, why Github decided not to reply to us?

**Comment by sebastien-d-me** [comment]
It would be so nice to add this feature !

**Comment by GaneshMBabu** [comment]
Using SourceTree now.

**Comment by tomsoffroad** [comment]
One funny reason why this may not be implemented now since Microslop now controls the platform, is that Visual Studio programmers may be caught in rut of "only one GIT repo per project"... The feature has only been out since 2022... 
I was a Java programmer trying to help some .NET coders, and I was watching them set me up by bringing in all of these other Projects that contained DLL dependencies so that the main app would build... I asked a 'forking' question... and I got back:
"Why would anyone ever need multiple GIT repos in the same project"  
lol

**Comment by Jas0n99** [comment]
> Using SourceTree now.

Oh wow, just installed and I see that you can configure lots of accounts... nice! Exactly what I needed. Guess github desktop is getting the uninstall after all these years.

**Comment by vsueiro** [comment]
Personal and Enterprise account switching sounds like a very common use case

**Comment by itsemerson** [comment]
I do not understand why this has still not been implemented. Devs often have personal and work GitHub accounts that are not Enterprise level. Please implement a way to switch accounts or add multiple github.com accounts. And how did this issue get closed, with no resolution in the app? Like others say, you can do this via CLI and the website, why not implement this in the app?

**Comment by franzcasca** [comment]
Perhaps this helps as a workaround (if this is a known solution, just disregard it; just writing this post in case it helps someone): 
1. Have a browser window logged to your account 1 and a different browser window logged to your account 2. (In my case, I even use a different Google profile on each browser). 
2. Select the browser window with the account you swish to switch to.
3. Go to GitHub Desktop > File > Options
4. In Options > Accounts, sign out of the current user account (I'm not using Enterprise mind you)
5. Now click on the "Sign into GitHub.com" button.
6. Click on "Continue with browser". It will take you to the last browser window you had selected. 
7. Once it's done, just click on Fetch from GitHub Desktop, the user should have switched and you should be ready to go. 
And voilá. 
Maybe not an ideal instant switching feaure but at least a workaround perhaps? 
Good luck and success in your projects!

**Comment by itsemerson** [comment]
Thanks for the workaround @franzcasca . Not ideal, but it looks like that will work for me

**Comment by expocees** [comment]
Still waiting for that feature since 2022...

**Comment by GI-STANDARDS** [comment]
Use [GITmaxed](https://github.com/GI-STANDARDS/GITmaxed/releases/tag/v1.0.1)

**Comment by Convincible** [comment]
I got two GitHub Desktop accounts working side-by-side with Sandboxie Plus on Windows using the same GitHub Desktop installation and the same repos.

Rather than an account switcher, it allows you to have two separate shortcuts, one to open GitHub Desktop normally, and another to open it signed in to some other account. Both can run at once.

1. Install Sandboxie Plus and create a Standard sandbox, e.g. `GitHubPersonal`.

2. In that sandbox's settings, give **Direct Access** to the folder(s) containing your Git repositories. This is important so the sandboxed GitHub Desktop works on the real working tree and `.git` directory rather than sandboxed copies.

3. Create a shortcut for the sandboxed account:

   `"C:\Program Files\Sandboxie-Plus\Start.exe" /box:GitHubPersonal "%LOCALAPPDATA%\GitHubDesktop\Update.exe" --processStart GitHubDesktop.exe`

   Using `Update.exe --processStart GitHubDesktop.exe` means the shortcut keeps working when GitHub Desktop updates; you don't need to point at a particular `app-x.y.z` folder.

5. Start the normal shortcut and sign into account 1.

6. Start the sandboxed shortcut and sign into account 2.

7. In the sandboxed GitHub Desktop, go to **File → Options → Git** and set the name/email you want commits from that account to use. Sandboxie virtualises the global `.gitconfig` write, so the normal GitHub Desktop instance can keep a different global Git identity.

Sandboxie may show `SBIE2205 Service not implemented: ConsoleInit (C00000D4)` for `git.exe`; in my testing this warning did not prevent Git operations from working. You can ignore it.

**Comment by ManiacalDorito** [comment]
Still waiting for this to be added. Insane this isn't a feature yet..... Convincible that seems like a pretty good solution but it's unfortunate it has to be that complicated. Will be using that from now on
