### ISSUE TITLE
Getting "Checking for updates failed" every morning

### ISSUE THREAD

**Issue by jeffpapp** [desktop/desktop#16109]
### The problem

Every morning after I wake up my computer I seem to get an error message saying "Checking for updates failed" in the GitHub app.  After clicking close everything seems to work fine for the rest of the day. 

### Release version

3.1.5

### Operating system

Windows 10 v10.0.19044

### Steps to reproduce the behavior

1. Leave GitHub desktop open when leaving the computer the previous day
2. Wake up the computer in the morning
3. Check the GitHub desktop app and see the error

### Log files

[2023-02-10.desktop.production.log](https://github.com/desktop/desktop/files/10709327/2023-02-10.desktop.production.log)

### Screenshots

<img width="304" alt="image" src="https://user-images.githubusercontent.com/1260960/218141210-736106fa-0f80-400e-b808-61a8c8d32183.png">

**Comment by tsvetilian-ty** [comment]
Thanks for the report @jeffpapp! It looks like this issue is already described in https://github.com/desktop/desktop/issues/16057 and marked as a bug. 

I'll close this issue, so we follow the progress in one place https://github.com/desktop/desktop/issues/16057
