### ISSUE TITLE
FATAL: unable to access 'http://xxxxxxxxxxxxxxxx.git/': Recv failure: Connection was reset

### ISSUE THREAD

**Issue by StepinArtem** [desktop/desktop#16107]
### The problem

I try "fetch origin" and receive this message
"FATAL: unable to access 'http://xxxxxxxxxxxxxxxx.git/': Recv failure: Connection was reset"

BUT in VScode everything is working!!!

### Release version

Version 3.1.6 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. Click "Fetch origin"
3. See error

### Log files

[2023-02-10.desktop.production.log](https://github.com/desktop/desktop/files/10708444/2023-02-10.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/57948884/218119077-826cdc5f-79c5-4d52-90dc-5dc3af4bec6d.png)

**Comment by steveward** [comment]
Thanks for the report @StepinArtem. Are you behind a firewall or proxy that could be interfering with your connection to GitHub? Are you running any antivirus or other security software on this machine that could be blocking GitHub Desktop?

**Comment by StepinArtem** [comment]
@steveward  YES! Antivirus and CiscoAnyConnect work. Yesterday work, day before yesterday work and etc. Nothing has changed!

**Comment by steveward** [comment]
@StepinArtem we upgraded the version of Git that ships with GitHub Desktop this week, which can sometimes result in those updated binaries getting flagged by security software.

I noticed the URL in the clone failure is http:// -- is this an internal repository? Any details you can share about your setup would be helpful, but you will likely need to reach out to someone for assistance internally. 

Does this error happen if you try to clone a repository from github.com?

**Comment by StepinArtem** [comment]
@steveward, ok! Its my github
<img width="548" alt="image" src="https://user-images.githubusercontent.com/57948884/218151002-3c767b7c-627f-49c8-b76a-2657c439fe9a.png">

**Comment by steveward** [comment]
Just to confirm --do Git operations work from the command line? You mentioned things working in VSCode, so I'm guessing you were using VSCode's Git integration.

If Git is working from the command line and VSCode without issue then it's definitely something on your machine or network blocking GitHub Desktop. I'd recommend reaching out internally to someone in your organization to see if you can get this solved, as there isn't anything we can do about this from our end. I'm sorry that I don't have better news.
