### ISSUE TITLE
[code suggestion] multiples of `||` into Array.includes

### ISSUE THREAD

**Issue by noformnocontent** [desktop/desktop#1610]
> https://github.com/desktop/desktop/blob/master/app/src/models/app-menu.ts#L247-L252
```ts
export function itemMayHaveAccessKey(item: MenuItem): item is IMenuItem | ISubmenuItem | ICheckboxMenuItem | IRadioMenuItem {
  return item.type === 'menuItem' ||
    item.type === 'submenuItem' ||
    item.type === 'checkbox' ||
    item.type === 'radio'
}
```

maybe have it converted to:
```ts
['menuItem', 'submenuItem', 'checkbox', 'radio'].includes(item.type)
```
?

not sure if TS supports it though

**Comment by shiftkey** [comment]
According to the [Typescript sandbox](https://www.typescriptlang.org/play/index.html):

<img width="298" src="https://cloud.githubusercontent.com/assets/359239/26198327/fba6fd1e-3c08-11e7-83aa-33bb36bffa22.png">

**Comment by noformnocontent** [comment]
yeah, i tried `tsc` locally -- same result, but according to https://github.com/Microsoft/TypeScript/issues/2340 it should have been worked since TS 2.1.5

how is array of strings not a direct descendent of Array :thinking:

**Comment by shiftkey** [comment]
@noformnocontent [Probably because we're not on ES7 yet](https://github.com/desktop/desktop/blob/6a11e8480a5bb0294c3ded1205b32773a181b8f9/tsconfig.json#L5), which seems to be a requirement.

**Comment by noformnocontent** [comment]
yeah, switching to ES7 is probably too big of a change for this issue to be fixed
