### ISSUE TITLE
Include the current branch name in the repo list tooltips

### ISSUE THREAD

**Issue by EasyRhinoMSFT** [desktop/desktop#16112]
### The feature request

I prefer to avoid committing unfinished work and find stashing to be a pain (just personal preference). Instead, I have multiple clones of several repos that I work in frequently. Since the repos list only shows the name of the repo, I sometimes have to iterate through clones of the same repo in order to find the right one. It would be handy if the tooltip shown for each clone included the name of current branch.

### Proposed solution

Provide an additional piece of useful at-a-glace information about each clone.

### Additional context

![GitHub-Desktop-tooltip](https://user-images.githubusercontent.com/32752981/218160108-25c8d9c0-b0d6-4a2a-8d44-b3671c3d5e38.png)

**Comment by steveward** [comment]
Thanks @EasyRhinoMSFT, I'm going to add this to https://github.com/desktop/desktop/issues/8158 where we are collecting feedback about showing the branch name in the repo list.

**Comment by EasyRhinoMSFT** [comment]
Great, thanks @steveward
