### ISSUE TITLE
Remote repository suddenly local only

### ISSUE THREAD

**Issue by peterkxie** [desktop/desktop#16115]
### The problem

I have a remote repository I have been using with Github Desktop for a while, and suddenly today GitHub desktop has the message `This repository is currently only available on your local machine.` I cannot fetch or push anything to the remote repository, and under Repository > Repository Settings > Remote I only get the option to publish. git CLI still works and I can fetch and push to the remote repository, and the output of `git remote --v` looks correct. `git fsck` also reported no problems. 

It also still gets updates correctly. I.E on Github desktop I cannot fetch origin, if it was last fetched 31 minutes ago when I fetch again it will stay last fetched 31 minutes ago in Github Desktop, but if I run `git fetch` in command line it will say last fetched just now in github desktop. There have been no changes to the repo or the location, and other repos under the same organization are also detected correctly as remote. 

I have restarted computer, re-installed GitHub Desktop, removed ~/Library/Application Support/GitHub Desktop and re-installed, removed repo in GitHub Desktop and re-added in, and it still is considered local. No errors or logs as it is just considered a local repository.

### Release version

Version 3.1.6 (arm64)

### Operating system

macOS Monterey v12.2.1

**Comment by steveward** [comment]
@peterkxie thanks for the report. Just to confirm, does the remote URL show up in `Repository` > `Repository Settings` > `Remote`? 

You could also take a look at the Developer Tools to see if anything shows up there as incorrect. You can go to `View` > `Toggle Developer Tools` > `Application` and go to the `IndexedDB` > `Database` section to take a look at the stored repository values. You can manually clear things out there as well to try and ensure any cached data is cleared out. The `Clear site data` option will clear out everything. Let me know if that helps.

**Comment by peterkxie** [comment]
@steveward thanks for the response! The remote URL does not show up in Repository > Repository Settings > Remote, I'll attach a screenshot with what it looks like 
<img width="598" alt="image" src="https://user-images.githubusercontent.com/22454194/218549926-9d9cb29b-96b0-4d7a-a99b-10ed10da2ab9.png">

running `git remote --v` in the command line does look correct to me, showing
```
origin  git@github.com:***/******.git (fetch)
origin  git@github.com:***/******.git (push)
```
I'll play around with the developer tools and see if I can find anything weird. I tried the `clear site data` but not sure if I did the correct steps. For me I removed repo, then opened dev tools, then went to application tab and selected clear site data, is that the correct order? What's weird is I downloaded a similar tool to Github Desktop to check if this repo was connected to the remote repo correctly and it was there, so it's only not working in Github Desktop right now.

Edit:
One thing I noticed that was string was under `IndexedDB` -> `Database` -> `repository` -> `path` the entry for the non-working repo the `githubRepositoryID` is `null`
<img width="279" alt="image" src="https://user-images.githubusercontent.com/22454194/218552047-1c124431-f85d-423c-8ed2-18da54573a0a.png">

I added a working repo from the same workspace and that repository id is one
<img width="250" alt="image" src="https://user-images.githubusercontent.com/22454194/218552196-9df7adab-a11e-4591-8a65-378b90293bdf.png">
and there is no entry for the first repo under `githubRepositoryID` DB. Possibly because it is detected as a local repository only

**Comment by steveward** [comment]
Selecting `Clear Site Data` and then restarting the app should trigger a clean reset, and force you to log in/add your repositories again. I would expect that to resolve things, but if it doesn't you could also grab a fresh clone of the repository if the remote repository is up-to-date with the local repo to see if that fixes it.

**Comment by peterkxie** [comment]
Unfortunately `Clear Site Data` didn't change anything for me. Ended up re-cloning the repository in a different location and copying over the `.git` folder contents and that seemed to work, so will close this issue as it is resovled for me. Appreciate the help @steveward
