### ISSUE TITLE
Desktop positioning in Windows

### ISSUE THREAD

**Issue by manparvesh** [desktop/desktop#1612]
### Description

When Github desktop is tiled in Windows, after running any keyboard shortcut, the size and positioning changes to default. 

### Version
**GitHub Desktop version:**  0.5.4
**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce
- Tile the Github desktop on your desktop
![1](https://cloud.githubusercontent.com/assets/6629115/26198651/70f82670-3bf9-11e7-89fb-74bdea590c39.png)

- Run any keyboard shortcut (eg. `Ctrl + Shift + N`)
- You will see this
![2](https://cloud.githubusercontent.com/assets/6629115/26198660/7979deba-3bf9-11e7-9246-f17a7a19e960.png)

**Expected behaviour:** The window positioning and size shouldn't be changed

**Actual behaviour:** It changes

**Reproduces how often:** always

### Logs
There is no log file created for today

**Comment by shiftkey** [comment]
@manparvesh thanks for the report!

This has been fixed in #1606 and will be available in the next update.
