### ISSUE TITLE
Github desktop 3.1.6 does not support simplified Chinese after updating  How to turn off the update function

### ISSUE THREAD

**Issue by qwer630701** [desktop/desktop#16127]
### The feature request

Simplified Chinese is not supported after upgrade

Want to stop updating

But how to close the software when it will be automatically updated?

### Proposed solution

Open a function to close the update

**Comment by steveward** [comment]
Thanks for the issue @qwer630701. Can you share what specifically broke after the update? GitHub Desktop does not have language localization at this time. We also have an existing issue about non-UTF-8 encoding issues with diffs (https://github.com/desktop/desktop/issues/3923).

**Comment by qwer630701** [comment]
The login window will pop up after the update, and the version before the update can pull the code normally
No matter how many times you enter the correct account password, it will still pop up, resulting in failure to pull
This problem also exists when using the latest version of TortoiseGit
The way I think now is whether I can stop the automatic update, but I can't find the location of the settings
@steveward 
![QQ截图20230215154443](https://user-images.githubusercontent.com/20468881/218965378-799a6043-9a3f-4e82-b6f0-8d5e436f79d7.png)

**Comment by qwer630701** [comment]
> Thanks for the issue @qwer630701. Can you share what specifically broke after the update? GitHub Desktop does not have language localization at this time. We also have an existing issue about non-UTF-8 encoding issues with diffs (#3923).
The login window will pop up after the update, and the version before the update can pull the code normally
No matter how many times you enter the correct account password, it will still pop up, resulting in failure to pull
This problem also exists when using the latest version of TortoiseGit
The way I think now is whether I can stop the automatic update, but I can't find the location of the settings

**Comment by steveward** [comment]
@qwer630701 can you try logging in by going to `File` > `Options` > `Accounts`? You won't be able to authenticate via the dialog you shared, since that's only usable for third-party hosting services.

**Comment by qwer630701** [comment]
@steveward
I have logged in to github. Now I need to access the private git built by others,
Its private git path contains Simplified Chinese, which makes the latest version of github desktop unusable
However, versions before 3.1.5 can be submitted and pulled normally
I downloaded a 2.9.4 version of github desktop online
It can be used normally, but it is always updated from time to time and then unavailable
![image](https://user-images.githubusercontent.com/20468881/219527215-681594a9-082f-48fd-b484-22b74727bedf.png)

**Comment by steveward** [comment]
@qwer630701 can you share a log file or the error from the log file that is occurring when you work with the private Git repository? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by qwer630701** [comment]
2023-03-03T09:56:55.510Z - info: [main] Using toast activator CLSID {xxx}
2023-03-03T09:56:56.243Z - info: [ui] [AppStore] loading 12 repositories from store
2023-03-03T09:56:56.244Z - info: [ui] [AppStore] found account: qwer630701 (SYY)
2023-03-03T09:56:56.734Z - info: [ui] launching: 3.2.0 (Windows 10.0.19044)
2023-03-03T09:56:56.746Z - info: [ui] execPath: 'C:\Users\admin\AppData\Local\GitHubDesktop\app-3.2.0\GitHubDesktop.exe'
2023-03-03T09:56:57.849Z - info: [ui] Subscribed 'qwer630701' to Alive channel
2023-03-03T09:56:58.597Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.906s)
2023-03-03T09:57:01.774Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 1.766s)
2023-03-03T09:57:01.775Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: repository 'http://xxx.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2023-03-03T09:57:09.553Z - info: [ui] storing generic credentials for 'xxx' and 'myName'
2023-03-03T09:57:10.336Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: repository 'xxx' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
@steveward

**Comment by steveward** [comment]
@qwer630701 thanks for sharing that. What happens if you try to perform a `git fetch` from the command line in this repository? I'd like to know if a similar error is shown in the output.
