### ISSUE TITLE
my files are not uploaded

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#16123]
### The feature request

.......

### Proposed solution

......

### Additional context

......

**Comment by steveward** [comment]
@Shikha12359 please fill out the template and upload a log file so that we can help you further. Thanks!

**Comment by Shikha4554** [comment]
I want to know how to solve my issue 
![Uploading IMG_20230213_064227.jpg…]()

**Comment by steveward** [comment]
@Shikha4554 it looks like your screenshot didn't upload correctly. If you could upload the log file I can take a look to see if there are any errors.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
