### ISSUE TITLE
External editor add option Open in Visual Studio

### ISSUE THREAD

**Issue by h2ls** [desktop/desktop#16124]
### The feature request

External editor add option Open in Visual Studio

### Proposed solution

![image](https://user-images.githubusercontent.com/33386249/218379905-20d66383-7911-401a-bad4-64ed3eeb6dc6.png)

**Comment by steveward** [comment]
Thanks for the feedback @azlis, this is being tracked in https://github.com/desktop/desktop/issues/12946 so you can follow along there for updates.
