### ISSUE TITLE
Misattribution warning about private email even though private email is disabled

### ISSUE THREAD

**Issue by codefrau** [desktop/desktop#16126]
### The problem

I'm getting the misattribution warning even though my local setting matches my primary email address in GitHub.

The message is "The email in your global git config (me@example.com) doesn't match your GitHub account" even though me@example.com is in fact my GitHub account email.

I want to use that public primary email for my commits, and always have been. 

Pressing "Update Email" in the warning popup replaces my local email with my private account email (123456+me@users.noreply.github.com) even though "Keep my email addresses private" is disabled in my account, and I have never enabled it.

### Release version

 3.1.6 

### Operating system

macOS 12.6.3

### Steps to reproduce the behavior

1. Click avatar icon with warning badge in commit pane
2. See wrong message claiming the correct primary email is wrong
3. click "update email"
4. wrong email (private) is written into `~/.gitconfig`

Expected: there should be no warning in the first place

### Additional context

This may be related to #15795 but that report does not mention private email addresses.

**Comment by steveward** [comment]
@codefrau thanks for the issue. Can you try logging out of your GitHub account in GitHub Desktop and then logging back in? I'd also recommend running `git config --list --show-origin` to verify there aren't any stray config options that are set.

**Comment by codefrau** [comment]
`git config --list --show-origin` only shows my actual email, not the private one (I only learned about private emails due to this issue today, I've never used it – if that was for education, mission accomplished 😉).

Instead of logging out and logging back in I restarted the app, and that appears to have fixed it too.

Thank you! Feel free to close.

**Comment by steveward** [comment]
Glad to hear things are working now!
