### ISSUE TITLE
Branch diff count widget

### ISSUE THREAD

**Issue by moritztim** [desktop/desktop#16134]
### The feature request

Add the `a-b-count-widget` which shows how many commits a branch differs from the default branch as seen on GitHub.

### Proposed solution

Just copying this over from the website would be a great addition to add some more information at a glance to the otherwise quite empty UI that could just fit this little widget

### Additional context

*GitHub:*
![image](https://user-images.githubusercontent.com/90388353/218830487-ef5d322d-ed27-462f-97e8-514af9c39e17.png)

*GitHub Desktop:*
![image](https://user-images.githubusercontent.com/90388353/218829352-8a5393e3-9bd4-48a0-97a2-b8c897f48ab4.png)

**Comment by steveward** [comment]
Thanks for the feedback @moritz-t-w, I'm going to add this to https://github.com/desktop/desktop/issues/8048 where we are tracking improvements to the branch list. For reference you can currently use the `Select Branch to Compare...` option in the `History` tab to see the ahead/behind count.
