### ISSUE TITLE
Support editing staged commit names and descriptions

### ISSUE THREAD

**Issue by PunkPun** [desktop/desktop#16130]
### The feature request

Currently if I want to edit a commit I must resort to using git interactive rebase. Github desktop does provide some renaming capabilities, but they are limited:

1. Amending - drawback: you can only edit the last commit
2. Reordering commit to be the last - drawback: a lot of work if rebase conflicts are present
3. Squashing - drawback: it requires a commit to squash, and empty commits are forbidden

I'd like to be able to simply just edit commit name / description in github desktop without any caveats.

### Proposed solution

<img width="241" alt="Screenshot 2023-02-14 at 12 31 21" src="https://user-images.githubusercontent.com/37534529/218709907-eb34dab7-6d7e-4eda-9709-2d02eb6005c0.png">

Add an edit commit option

### Additional context

I usually need this feature after #16129 runs its course

**Comment by steveward** [comment]
Thanks for the feedback @PunkPun! We're have an existing issue about this in https://github.com/desktop/desktop/issues/5219, so I'm going to close this out and reference it there.
