### ISSUE TITLE
repo is shown as public repository, so cannot push but only publish

### ISSUE THREAD

**Issue by sbern4** [desktop/desktop#16132]
### The problem

Whenever I try to push a commit, I am asked to login to publish my repository. It seems a similar issue to #5936, but I could not find a solution.

### Release version

3.1.6

### Operating system

Windows 10

### Steps to reproduce the behavior

1. modify a file in the repo
2. commit the change
3. press push origin
4. it asks to publish repository
![image](https://user-images.githubusercontent.com/125288102/218731719-87b9ba89-afde-45d6-9266-6569ad6f8741.png)

### Log files

[2023-02-14.desktop.production.log](https://github.com/desktop/desktop/files/10732081/2023-02-14.desktop.production.log)

**Comment by steveward** [comment]
@sbern4 you will need to log in to your GitHub account in order to push a repository, even if it is public. Let me know if you have any further issues after doing that.

**Comment by sbern4** [comment]
This was not needed previously. 
I mean, I have a login coming with my company, done through AZURE AD, so I am not sure what should I do in GitHub Desktop.

**Comment by sbern4** [comment]
As additional note, my repo is not public. From other issues I found, the repo is shown with the PC icon, but it should have the padlock icon besides it.
Looking at my projects settings, I see it is set as Internal

![image](https://user-images.githubusercontent.com/125288102/218976161-f7ccde36-48cc-4782-8604-3ece5e393a65.png)
