### ISSUE TITLE
Add local path to repositories in the repository list to be able to distinguish between multiple checkouts

### ISSUE THREAD

**Issue by henningpd** [desktop/desktop#16139]
### The feature request

When having multiple checkouts of the same repository on disk, the only way to identify them is by hovering over each one making it tedious to locate the right one.

![image](https://user-images.githubusercontent.com/69513267/219008544-6f43bc24-76ad-4acc-9366-c51d5ba43c3e.png)

### Proposed solution

Show the local checkout path for each repository

**Comment by steveward** [comment]
@henningpd thanks for the feedback. You can right-click and use `Create Alias` for the repositories you need to differentiate. We're also tracking feedback about showing the branch name in the repository list in https://github.com/desktop/desktop/issues/8158, so you can follow along there for updates. I'm going to close this out.
