### ISSUE TITLE
Displaying unchanged files in the list of changed files

### ISSUE THREAD

**Issue by KaushikPalteru24** [desktop/desktop#16142]
### The problem

In the github desktop, the unchanged files are being displayed in the list of changed files.

### Release version

3.1.7

### Operating system

Windows 10

**Comment by steveward** [comment]
@KaushikPalteru24 thanks for the report. There are likely file mode or line endings changes causing this. Can you share a screenshot of what you are seeing in the diff?

**Comment by Andrej730** [comment]
Using 3.1.7-beta1 on Windows 11 and have similar issue - even discarding changes doesn't help.


https://user-images.githubusercontent.com/9417531/219152077-b3fe98b0-615d-41f9-86e7-86a3108bb697.mp4

The file contents (if it's any important):
```bash
python3 extract_concepts_from_xmi.py ../schemas/IFC.xml
python3 to_pset.py ../schemas/IFC.xml psd
python3 parse_xmi.py ../schemas/IFC.xml
python3 to_express.py ../schemas/IFC.xml IFC.exp
python3 express_to_xsd.py IFC.exp IFC.xsd
python3 change_log.py ..
python3 parse_examples.py ..
```

**Comment by steveward** [comment]
@Andrej730 can you run `git diff` from the command line on one of those files that you are unable to discard?

**Comment by Andrej730** [comment]
@steveward
```
git diff code\create_resources.sh
diff --git a/code/create_resources.sh b/code/create_resources.sh
old mode 100755
new mode 100644
```

**Comment by steveward** [comment]
@Andrej730 those are file mode changes. If you want to ignore them you can run `git config core.filemode false`.

**Comment by Andrej730** [comment]
thank you, it worked for me
