### ISSUE TITLE
Could not install

### ISSUE THREAD

**Issue by anacesponda** [desktop/desktop#1614]
<img width="779" alt="screen shot 2017-05-18 at 8 51 17 am" src="https://cloud.githubusercontent.com/assets/11823844/26200989/31d5477c-3ba7-11e7-84f7-da71d8309d0e.png">

**Comment by shiftkey** [comment]
This looks like #1564 or #1538 which seem related to detecting displays.

@anacesponda do you have any external monitors connected to your machine?

**Comment by anacesponda** [comment]
@shiftkey Yes, I have monitors connected to my machine. I just opened it again and it worked. Sorry I created an issue for this.
