### ISSUE TITLE
Client can bypass branch protection with pushed commits

### ISSUE THREAD

**Issue by ariffjeff** [desktop/desktop#16146]
### The problem

Unless I am misunderstanding how branch protection works (I probably am or I made a mistake somewhere else), it appears GitHub Desktop has the ability to just push commits to a branch on GitHub that has branch protection enabled which is specifically set up to block this type of action.

### Release version

Version 3.1.7 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Go to your remote main branch and enable branch protection in the settings for the main branch (I only enabled "Require a pull request before merging" in this case, I left "Require approvals" disabled).
2. In your local repo, create any arbitrary file, `test.txt` in this case.
3. In GitHub Desktop, commit the change and push it to main branch.
4. I expect an error from GitHub Desktop failing to push the commit saying something like it can't push directly to main because of the branch protection but no such thing happens. Looking at the remote repo shows that `test.txt` made it there successfully.
5. Ironically attempting to forcefully delete the latest commit using CLI actually gets blocked by the branch protection:
    1. `git reset --hard <COMMIT_ID>` (COMMIT_ID will be the second to last ID)
    2. `git push --force`

Surely, I'm just misunderstanding something here.

**Comment by steveward** [comment]
@ariffjeff if you're trying to block admins from also pushing then you need to enable specific rules. See [this section](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#do-not-allow-bypassing-the-above-settings) of the docs:

>By default, the restrictions of a branch protection rule do not apply to people with admin permissions to the repository or custom roles with the "bypass branch protections" permission in a repository.

I hope that helps!

**Comment by ariffjeff** [comment]
Ah no idea how I missed that option. Thank you! Sorry for wasting your time.
