### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by gwonsuji** [desktop/desktop#16149]
### The problem

Authentication failed keeps occurring when I clone. I repeatedly logged in and logged out and deleted it, but it was useless.

I already issued tokens and tried putting the password tokens in the picture below, but it keeps failing.

![image](https://user-images.githubusercontent.com/60372704/219583222-09e398f0-8309-4cf0-a89a-a16044955f88.png)

And I can't push. The following message appears continuously.

Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.

### Release version

3.1.7(x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. clone repository
2. local path select
3. clone button click

### Log files

[2023-02-17.desktop.production.log](https://github.com/desktop/desktop/files/10764553/2023-02-17.desktop.production.log)

**Comment by steveward** [comment]
@gwonsuji you will need to log in by going to `File` > `Options` > `Accounts`. See [this article](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/installing-and-authenticating-to-github-desktop/authenticating-to-github). Let me know if that does not get things working.

**Comment by gwonsuji** [comment]
@steveward
I unlogged in this page and tried again more than 5 times, but the same error message occurred... The personal laptop I linked a year ago works normally, but the same error occurs on the computer. I tried both main and master, but it was also the same.

![image](https://user-images.githubusercontent.com/60372704/220019832-168816dd-6ed9-4262-a52d-37f32e614479.png)
![image](https://user-images.githubusercontent.com/60372704/220020739-6a9da4f4-f130-4497-8734-2d0250193481.png)
