### ISSUE TITLE
Update roadmap.md

### ISSUE THREAD

**Issue by Andrej730** [desktop/desktop#16144]
Update https://github.com/desktop/desktop/blob/development/docs/process/roadmap.md
There is also project [Desktop Housekeeping](https://github.com/desktop/desktop/projects/36) but it wasn't updated for 2 months too..

It would be nice to be able to keep track of what's going on and what to expect in the future.

**Comment by steveward** [comment]
@Andrej730 thanks for the issue, I'll make a note of this for when we have changes to add there. You can take a look at recent PRs for upcoming changes to GitHub Desktop. We do try and set expectations in the roadmap itself:

>We'll attempt to update this intermittently as priorities evolve, but can't guarantee that it stays up to date over time.
