### ISSUE TITLE
No login request for remotes?

### ISSUE THREAD

**Issue by kevinvanryck** [desktop/desktop#1615]
No "login details" window pops up when synchronising a repository with a remote which is my own git server.

### Description
When using a remote for a repository, which isn't GitHub, I used to get the window asking me to login (GitHub desktop); but with the new beta, it just says it failed to sign in without requesting my sign in details. I use it with my own local git servers; but it's a pity I cannot use the new beta with them.

### Version
**GitHub Desktop version:** 0.5.4

3.3.4 (Github desktop) => works!

0.5.4 (Github desktop beta) => does **not work**.

**OS version:** Microsoft Windows [Version 10.0.14393]

### Steps to Reproduce

1. Clone repository from my own git server
2. Add local repository in github app
3. Set repository->remote settings to .git URL
4. Sync
5. On old version: login is requested. On new version: authentication failed without any possibility to login is displayed.

**Expected behaviour:** Request login details

**Actual behaviour:** Fails authentication without giving me a chance to provide my credentials.

**Reproduces how often:** 100% of the time

**Comment by shiftkey** [comment]
We plan to support this before 1.0.

Closing in favour of the existing issue: https://github.com/desktop/desktop/issues/852
