### ISSUE TITLE
Connot Login in GitHub Desktop

### ISSUE THREAD

**Issue by Shabbir-Khan-12** [desktop/desktop#16160]
### The problem

I was trying to clone a repository and failed to do so multiple times, then I tried to log out and sign in again but now Github Desktop won't sign me in. 

### Release version

Latest

### Operating system

Windows 64-bit

**Comment by steveward** [comment]
@Shabbir-Khan-12 are you attempting to log in by going to `File` > `Options` > `Accounts`? Logging in via the authentication failure dialog will not succeed. Let me know if that does not get things working.

**Comment by ghost** [comment]
This is the same issue I am facing right now. I signed out of GitHub and now it just won't let me sign back in. 
I did try to login multiple times using **File > Options > Accounts > Sign In** But, no success. 
GitHub Desktop version : 3.1.7 (x64)
Windows 11 (22H2)
