### ISSUE TITLE
context menu in repo list

### ISSUE THREAD

**Issue by kristofer** [desktop/desktop#1616]
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

context menu in repository list... should have Open in Github, Open in Terminal and Open in Atom and Open in Finder just like the old Desktop for Mac did.

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

0.5.3

The operating system you are running on may also help with reproducing the
issue:

 macOS Sierra 

### Steps to Reproduce

always

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

context menu in repository list... should have Open in Github, Open in Terminal and Open in Atom and Open in Finder just like the old Desktop for Mac did.

menu just says "remove"

**Reproduces how often:** [What percentage of the time does it reproduce?]
always

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by joshaber** [comment]
Thanks! We're already tracking this in #1554. Feel free to follow along there.
