### ISSUE TITLE
Push to origin visual bug

### ISSUE THREAD

**Issue by Zabriskije** [desktop/desktop#16174]
### The problem

The `Push to origin` section displays a visual bug when uploading more than one file at a time

### Release version

Version 3.1.7 (arm64)

### Operating system

macOS Ventura 13.2.1 (22D68)

### Steps to reproduce the behavior

1. Add more than one file to the local repo
2. Commit
3. Push to origin

### Screenshots

https://user-images.githubusercontent.com/101254295/219987208-50909480-eba0-44e9-996a-5bce894676dc.mov

**Comment by steveward** [comment]
Thanks for the issue @Zabriskije, we are tracking this in https://github.com/desktop/desktop/issues/14608 so I'm going to close this out.
