### ISSUE TITLE
my github desktop app cannot connect to the browser

### ISSUE THREAD

**Issue by vicyvic** [desktop/desktop#16176]
### The problem

my github desktop app cannot connect to the browser

### Release version

Version 3.1.7 (x64)

### Operating system

windows10

### Steps to reproduce the behavior

go to file 
click onfile
scroll down to options
on accounts click on github.com sign in
![image](https://user-images.githubusercontent.com/125852768/220033818-3da0077d-9302-4ba1-90ee-ce7d4d79e9a0.png)

**Comment by AfreyAwsome** [comment]
me too

**Comment by AfreyAwsome** [comment]
I finally made it. First,I upgraded my git.exe to the newest version and used the git command to clone a repository randomly. After that, I tried to log in again by github desktop app and  it did work finally.

**Comment by AfreyAwsome** [comment]
I finally made it. First,I upgraded my git.exe to the newest version and used the git command to clone a repository randomly. After that, I tried to log in again by github desktop app and  it did work finally.
