### ISSUE TITLE
Copy user OS and Desktop build version

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1617]
We should add the ability for the user to copy to the clipboard the following at minimum:

- GitHub build version
- OS of the user
- anything else?

Suggest adding it here:
<img width="496" alt="screen shot 2017-05-18 at 9 52 14 am" src="https://cloud.githubusercontent.com/assets/14828183/26205454/ca6d7fc4-3baf-11e7-8d6c-a2623c5d7d63.png">

This will help with accurately getting data for bug reporting and troubleshooting.

**Comment by joshaber** [comment]
Relatedly, I wonder if we could provide those values as part of the URL in Help > Report Issue…

**Comment by joshaber** [comment]
Indeed, https://github.com/desktop/desktop/issues/new?title=test&body=bleh seems to work.

**Comment by j-f1** [comment]
See also #1935 and #1948.

**Comment by sanjayyepuri** [comment]
Hi @tierninho, I wanted to start contributing and was wondering if I could try to solve this.

**Comment by j-f1** [comment]
@sanjayyepuri Check out #1965. I’m sure they’d welcome a PR.

**Comment by tierninho** [comment]
@sanjayyepuri Hi, anything labeled `up-for-grabs` is available for you (or anyone) to submit a PR for review. Thanks!

**Comment by http-request** [comment]
Now it looks like that:

![screen shot 2017-12-19 at 19 26 51](https://user-images.githubusercontent.com/6680179/34167362-a2e01cfe-e4f2-11e7-8d7b-aab5b17c2fb6.png)

and when you click on the Version link then you get  `1.0.11-beta0` in clipboard. 
So, what is the outcome of this task? it should be like: `OS: MacOS Username: SmartUser GitHub Desktop Version: 1.0.11-beta0` in clipboard when I click on the version link or I have to add three different links to this dialog?

**Comment by shiftkey** [comment]
Where did we end up on this @desktop/core? Do we want to spend more time in here? Personally, I think the log files already do a good job of tracking build/OS/account information at runtime...

**Comment by niik** [comment]
> Where did we end up on this @desktop/core? Do we want to spend more time in here? Personally, I think the log files already do a good job of tracking build/OS/account information at runtime...

I concur

**Comment by joshaber** [comment]
Agreed!
