### ISSUE TITLE
Bug since updte 2 Feb

### ISSUE THREAD

**Issue by Morons** [desktop/desktop#16178]
### The problem

Sudenly, after 2 Feb update several of my Git'have this issue

fatal: missing object ee9ed4f68dcf3c57392bb4789b017b19d0a55d76 for refs/remotes/origin/Addresses

### Release version

Version 3.1.7 (x64)

### Operating system

Edition	Windows 10 Pro Version	22H2 Installed on	‎2021/‎10/‎28 OS build	19045.2604 Experience	Windows Feature Experience Pack 120.2212.4190.0

### Screenshots

![image](https://user-images.githubusercontent.com/22202038/220057698-beae26c6-70f8-43ea-837f-4497403946c0.png)

**Comment by steveward** [comment]
Thanks for the issue. Unfortunately it looks like there is an issue with your local repository. Can you try running `git gc` from the command line in your repo and see if that fixes it?
