### ISSUE TITLE
Not REcognizing VS Code

### ISSUE THREAD

**Issue by SFUnity** [desktop/desktop#16173]
### The problem

I tried to open my repository in VS Code through the Github Desktop App. It said I hadn't installed VS Code. Why is that?

### Release version

3.1.7

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Click Control + Shift + A
2. Read the error message

**Comment by steveward** [comment]
@SFUnity did you restart GitHub Desktop after installing VS Code? That's one thing that can cause this issue. Let me know if that is not the case.
