### ISSUE TITLE
Add shortcut for "Discard changes" action

### ISSUE THREAD

**Issue by gtimur7** [desktop/desktop#16180]
### The feature request

In current version it is required to use context menu ("right click") on file to discard changes.
Shortcut will help to made it easier, using only keyboard.

Shortcut for "Discard all changes..." action doesn't always fit.

### Proposed solution

It can be same as in GitExtensions - to press `R` to reset changes.
Can be any shortcut, if possible - one symbol without modifiers.

Steps:

1. File in commit is selected
2. Press `R`
3. Shows dialog "Are you sure want to discard changes? Yes/No/ [x] don't ask me again"
4. If "yes" - changes are discarded for selected file, focus moved to next file.

**Comment by steveward** [comment]
Thanks for the issue @gtimur7. This was previously requested in https://github.com/desktop/desktop/issues/16180, and at this time is not something that we plan to implement. I'll reference this issue there for future consideration.

**Comment by adnaneh** [comment]
Hey @steveward @gtimur7 I've added a PR to do this: https://github.com/desktop/desktop/pull/21164
I think @thennothinghappened comment makes a lot of sense: https://github.com/desktop/desktop/issues/8050#issuecomment-2126278220
