### ISSUE TITLE
Highlighted text is unreadable

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1618]
If user highlights some text in a diff and the text wraps as part of a paragraph, then some the text is in white font color, making it very hard to read against a light green background.

v0.0.55, OSX 10.11.5

Reproduce
- Open a diff with lots of text
- Highlight part of one paragraph

<img width="762" alt="screen shot 2017-05-18 at 10 57 19 am" src="https://cloud.githubusercontent.com/assets/14828183/26208924/5a0fc82c-3bb9-11e7-9516-1d662c7a3b24.png">

**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
To reproduce this, hold ALT/Option while dragging (in case you're not sure).

@tierninho the root cause of this seems to be the ability to select two parts of a line that wraps, and I think it will require a fix to Codemirror (I'm pretty sure we're on the latest version).

**Comment by tierninho** [comment]
Seems fixed, closing
