### ISSUE TITLE
Mermaid.js integration (or relevant) for GitHub desktop commit mapping

### ISSUE THREAD

**Issue by projektorius96** [desktop/desktop#16186]
### The feature request

As titled . Everyone knows remotely it is already integrated: [github/docs](https://docs.github.com/en/repositories/viewing-activity-and-data-for-your-repository/understanding-connections-between-repositories#viewing-a-repositorys-network) 

### Proposed solution

- On the basis of mermaid by @knsv or relevant tooling write a prototype (interface?) to implement network (mapping) for commits with interactive traversing suggestions for cherry-picking, user-friendly relative traversing using `HEAD~` or `HEAD^`, etc.
- I am thinking about starting relevant project or at least actively contributing to, but I am not sure whether it should be framework oriented, or framework agnostic solution .

### Additional context

---

_p.s. I assume this would require to understand git internals, which is not daunting for a curious can-do developer, also some OAuth request tooling such as cURL for CLI based remote procedures or API based gRPC ._

Cheers

**Comment by niik** [comment]
Hey @projektorius96, thanks for reaching out. I believe this is the same kind of request as https://github.com/desktop/desktop/issues/9452, i.e. a visual graph representation of the commit history, so I'll close this issue in favor of that. Cheers!

**Comment by projektorius96** [comment]
> Hey @projektorius96, thanks for reaching out. I believe this is the same kind of request as #9452, i.e. a visual graph representation of the commit history, so I'll close this issue in favour of that. Cheers!

Sorry for duplicating myself, I'll have a look, cheers !
