### ISSUE TITLE
Retain default text when committing

### ISSUE THREAD

**Issue by ajtruckle** [desktop/desktop#16184]
### The feature request

A commit shows some default text, eg:
![Commit](https://user-images.githubusercontent.com/7985331/220290518-f5f846dc-ba04-4a6d-bf7b-171ba2e66ceb.jpg)
The issue for me is that I want to click and prefix the default text with a ag, eg: [MSA-123]. This is so associate the commit with my Jira ticket.

### Proposed solution

Can you please provide a way for us to begin with the default text? At the moment if I click it to change it it will wipe it out. Maybe a button to indicate "edit default text". This button becomes disabled when the text has been modified. It enables again if the user deletes all the text.

**Comment by steveward** [comment]
Thanks for the issue. We are tracking support for commit templates in https://github.com/desktop/desktop/issues/3242, so I'd recommend following along there for updates.

**Comment by ajtruckle** [comment]
@steveward I am not sure how cloning is is related to this?
