### ISSUE TITLE
GitHub Desktop hangs while trying to clone a repository containing a submodule

### ISSUE THREAD

**Issue by pawa2007** [desktop/desktop#16181]
### The problem

I am trying to clone a repository that contains a submodule. Desktop hangs while it tries to clone the repository. 

### Release version

3.1.7 (x64)

### Operating system

Windows 11 Pro

### Steps to reproduce the behavior

1. Go to File > Clone Repository and provide the GitHub URL of the repository.
2. Desktop starts the cloning process and hangs. Screenshot provided below in Screenshots section.

### Log files

[2023-02-20.desktop.production.log](https://github.com/desktop/desktop/files/10785294/2023-02-20.desktop.production.log)

### Screenshots

<img width="960" alt="image" src="https://user-images.githubusercontent.com/21964536/220133235-a3ef0f19-9745-47d7-8787-c0c652f2f967.png">

**Comment by steveward** [comment]
@pawa2007 thanks for the issue. It looks like this submodule is missing:

```
remote: Repository not found.
fatal: repository 'https://github.com/TwioTech/casagusto-test.git/' not found
```

You can work around this by cloning directly from the command line using `git clone`. We're also tracking this issue in https://github.com/desktop/desktop/issues/3242 if you'd like to follow along for updates.

**Comment by minipunch** [comment]
Yes, can confirm, this is annoying for my contributors lol

Would be nice if there was an option to skip the submodules or at least some more user friendly way of failing so people aren't always telling me they "get stuck" there and don't contribute

In my case the submodule repo does indeed exist, they just might not have access to it

**Comment by Kobold** [comment]
Just ran into this myself with GH Desktop 3.4.18 on Windows 10, with it stalling on clone when trying to clone  the submodule `git@github.com:jpescador/hugo-future-imperfect.git`. Trying it with https now, but it would be nice to be able to just skip it, as this is for non-technical users.
