### ISSUE TITLE
Friend can’t push commits

### ISSUE THREAD

**Issue by Blobicycake** [desktop/desktop#16183]
Sorry if there isnt much detail, I’m still a little new to this.

When my friend pushes from github desktop, the commits dont seem to be received by the repository (nothing changes or goes into history). He is doing it exactly how I do it, and can pull my changes successfully.

**Comment by ghost** [comment]
> Sorry if there isnt much detail, I’m still a little new to this.
> 
> When my friend pushes from github desktop, the commits dont seem to be received by the repository (nothing changes or goes into history). He is doing it exactly how I do it, and can pull my changes successfully.

Tsg

**Comment by steveward** [comment]
@Blobicycake unfortunately there isn't much we can do without further information. Can you share some screenshots or a log file from your friend's machine?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. 

The log file will show us if the push is completing.
