### ISSUE TITLE
Commit Date and Time

### ISSUE THREAD

**Issue by Eslam-Ahmed-SE** [desktop/desktop#16195]
### The problem

If the time is not correct on the pc committing and pushing, the time gets set incorrectly on the history tab (this means I can push in the past and in the future), this can be changed by getting the date and time of the push from the server rather than the local time of the commit.

### Release version

Version 3.1.7 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

- Change the time on windows 
- make a commit
- push the commit

**Comment by niik** [comment]
Hey @Eslam-Ahmed-SE, thanks for reaching out. This is a result of Git being an offline version control system that functions locally without the need for an internet connection. Each user crafts commits on their own machines and push those commits to remotes. Without a central authority to stamp and verify commits metadata like dates, author, etc become as trustworthy as the party you're receiving those changes from. See https://git-scm.com/about/distributed for more information.

For some applications [signed commits](https://docs.github.com/en/github-ae@latest/authentication/managing-commit-signature-verification/signing-commits) can be utilized to be able to prove the identify of the commit author but for most applications the verification of the pusher by the host is more than good enough.
