### ISSUE TITLE
Branch Compare by File - Easy Way

### ISSUE THREAD

**Issue by rtfmoz2** [desktop/desktop#16197]
### The feature request

Enable a file view of branch compare

### Proposed solution

Automatically create a hidden or temporary branch from current then do a merge and squash into it from the branch you are comparing. Use the "always accept incoming" merge option to prevent conflicts. Now compare the original branch with this temporary one. You will have one temporary commit on the left and all the files. Even better hide commit pane so you just have the file view and they can walk through the files to see what they want.

### Additional context
![image](https://user-images.githubusercontent.com/40995106/220814987-d7f69f05-a38b-4d60-bdfd-7047bef1b72c.png)
_No response_

**Comment by rtfmoz2** [comment]
This is a partial solution to https://github.com/desktop/desktop/issues/6757
This is especially useful for branches with many commits as doing this manually is quite painful.

**Comment by tidy-dev** [comment]
@rtfmoz2 Thanks for the suggestions. I am not sure this is different than the issue you referenced. I am going to close this and put your feedback there.
