### ISSUE TITLE
Feature request: Grab and scroll diffs by line numbers

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1619]
Within a diff, a user can click to scroll up/down the entire diff while highlighting text along the way, however this is not possible if the same action is done in the line numbers section. 

Currently, the user can only scroll to the border of the app, then they are forced to use the mouse.

<img width="897" alt="screen shot 2017-05-18 at 10 57 47 am" src="https://cloud.githubusercontent.com/assets/14828183/26209274/564a8ec4-3bba-11e7-9943-3ee958faefa8.png">

This would be a nice feature in order to select/deselect multiple lines. 

On build v0.0.55, OSX 10.11.5

**Comment by joshaber** [comment]
💯 👍 We're tracking this in #658.
