### ISSUE TITLE
how do you fix "A commit summary is required to commit"

### ISSUE THREAD

**Issue by a-asen** [desktop/desktop#16203]
### The problem

how do you fix "A commit summary is required to commit"

There exists no longer a single "conflict", yet the "app" is stuck on this (see picture). 

Uninstall the app does not change anything. 

Lots of fun.

Best part, it is "resolved". And it is still the same.

### Release version

3.1.8

### Operating system

Win 10

### Screenshots

![image](https://user-images.githubusercontent.com/98240487/221052219-03d0f303-a9b8-4daa-917a-b57088bda022.png)

![image](https://user-images.githubusercontent.com/98240487/221053279-ef84a47f-f19d-4f2e-b9c6-f16b9d7bd861.png)

**Comment by a-asen** [comment]
*deleted repository and created a new one resolved this shit

**Comment by k-rowley** [comment]
Really? You have to completely delete the repository and create a "new" one?

**Comment by chellegrace855** [comment]
you can just add the commit summary

**Comment by Suuds** [comment]
just write comment about commit in field  "Summary"

**Comment by danmaster01** [comment]
Okay thanks

**Comment by Crizz64** [comment]
> just write comment about commit in field "Summary"

Master on hacking!!!!!!!
