### ISSUE TITLE
Add pin option to have often used repos easily accessible

### ISSUE THREAD

**Issue by ThimoDEV** [desktop/desktop#16205]
### The feature request

When switching repositories in github desktop I get a very long list of all the repositories on my pc. It would be amazing if I can select a few to always be on top.

### Proposed solution

The benefit of this feature is an improved UX. Users don't have to always scroll and search where that specific repo is to select it. ALso if they have similar named repos from different organisations they wont accidently pick the wrong one.

### Additional context

![image](https://user-images.githubusercontent.com/68739517/221145250-9a2173f4-d73b-473e-ac3b-1fbc2bf789ee.png)

A mockup of how this might look like

**Comment by steveward** [comment]
Thanks for the feedback @ThimoDEV, although at this time we don't have plans to add this to GitHub Desktop I'll reference this issue in https://github.com/desktop/desktop/issues/8183 where we are tracking feedback about this.
