### ISSUE TITLE
Hello, getting a fetch error in github desktop, please help.

### ISSUE THREAD

**Issue by 4qmbjamil** [desktop/desktop#16201]
### The problem

When I am fetching from my origin repo I am getting the below error:

![image](https://user-images.githubusercontent.com/109686876/220927692-6bc2b042-f1be-4deb-b56c-3c448d740bf9.png)

### Release version

Version 3.1.8 (x64)

### Operating system

Windows 10

### Log files

[2023-02-23.desktop.production.log](https://github.com/desktop/desktop/files/10814205/2023-02-23.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/109686876/220928637-b4eacf3b-cfa7-4fad-b86f-d50c4eeda301.png)

**Comment by steveward** [comment]
@4qmbjamil thanks for the issue. I'm seeing this error in the log file:

```
error: cannot open '.git/FETCH_HEAD': Permission denied
```

Can you verify the correct permissions are set for the directory the repository is in?
