### ISSUE TITLE
Can't do pull request or public branch

### ISSUE THREAD

**Issue by Ankook** [desktop/desktop#16209]
### The problem

can't to do push or pull request in github desktop

### Release version

Version 3.1.8 (arm64)

### Operating system

Mac os Ventura 13.2.1

### Screenshots

<img width="1440" alt="Screenshot 2023-02-24 at 21 27 55" src="https://user-images.githubusercontent.com/52046510/221261724-cd411666-ff1a-4dbd-9d68-1e0ffc5360e4.png">

**Comment by sergiou87** [comment]
Hello!

Do you have an antivirus, firewall or proxy by any chance? Those usually cause issues like the one you report 🤔

**Comment by Ankook** [comment]
No, maybe local ISPs are learning to disable sites

**Comment by steveward** [comment]
@Ankook unfortunately there isn't much we can do about these types of connectivity errors from our end. I would recommend trying to work with GitHub Desktop on a different network to see if you are able to narrow down what might be causing the issue here. I'm going to close this out.
