### ISSUE TITLE
Please have options to "create patch" in right click menu when selecting several changes.  

### ISSUE THREAD

**Issue by chenFlyingkite** [desktop/desktop#16204]
### The feature request

Please have options to "create patch" in right click menu when selecting several changes.  
It is useful when user want to provide the changes as files to others.

### Proposed solution

 By implementation : git diff > mypatch.patch

### Additional context

If Github Desktop team have no time to implement, maybe I can help on the development.

My Github : https://github.com/chenFlyingkite
My LinkedIn : https://www.linkedin.com/in/建志-陳-999693227/

**Comment by steveward** [comment]
Thanks for the issue @chenFlyingkite. The ability to create patch files likely isn't something that we would implement in GitHub Desktop, as our focus is on the pull request development flow (see [GitHub Flow](https://docs.github.com/en/get-started/quickstart/github-flow)). If you need to create patch files you can quickly jump into the command line to accomplish that. I'm going to close this out, but thanks for using GitHub Desktop!

**Comment by chenFlyingkite** [comment]
OK.
Thanks for your response, and I will also visit [GitHub Flow](https://docs.github.com/en/get-started/quickstart/github-flow) for details.

**Comment by shahzaibm10c** [comment]
It would still be really useful if we could have this feature, as it would save time and reduce the need to switch to the command line or external tools.
