### ISSUE TITLE
Unable to fetch authenticated user.

### ISSUE THREAD

**Issue by FrankLiang3196** [desktop/desktop#16216]
### The problem

When I tried to log in to my github account. It shows the error message: Unable to fetch authenticated user.
At first, I was unable to fetch origin, but it shows "fatal: unable to access 'https://github.com/xxx.git/': Failed to connect to 127.0.0.1 port 7890 after 2041 ms: Couldn't connect to server"
Then I tried to re-login but shows a new error. Is this a network error?

### Release version

Version 3.1.8 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Go to "File -> Options"
2. Click on "Sign in"
3. Click on "Continue with browser"
4. Click on "Open GitHubDesktop.exe"
5. Then the error shows.

### Log files

[2023-02-27.desktop.production.log](https://github.com/desktop/desktop/files/10835948/2023-02-27.desktop.production.log)

### Screenshots

<img width="302" alt="issue" src="https://user-images.githubusercontent.com/48574666/221471156-a23083c0-e823-4fda-829f-97ac6b9e7448.png">

**Comment by sergiou87** [comment]
Hello @FrankLiang3196 👋 

This usually happens to users that run an antivirus, firewall or behind a proxy. Is any of those your case? If so, could you temporarily disable them and see if the app works as expected then? 🤞

**Comment by KrishnapadDas** [comment]
I am facing the same issue
