### ISSUE TITLE
Attempting to commit fails

### ISSUE THREAD

**Issue by DefNotCrawf** [desktop/desktop#16218]
### The problem

I recently downloaded 'GitHub Desktop' and 'Git for Windows'; after cloning a repository (TempeHS/2023IST-Website-Crawford.Lieu) and I set it up in GitHub Desktop. After the files are properly on my local drive (C:), I edit a .html file. After the desired edits were made and making sure that the edit was properly detected in GitHub Desktop, I type in my summary and description. I click on 'Commit to **main**', and then the error message appears. The error message is as follows:

> `error: Couldn't load public key CA47EF9CE4A8491A: No such file or directory?`
> 
> `fatal: failed to write commit object`

### Release version

Version 3.1.8 (x64)

### Operating system

Windows 10 (22H2)

### Steps to reproduce the behavior

1. Clone a repository in GitHub Desktop.
2. Makes changes to the files where files are stored.
3. Add a summary and description.
4. Click 'Commit to **main**'
5. See the error message

### Log files

[2023-02-27.desktop.production.log](https://github.com/desktop/desktop/files/10838979/2023-02-27.desktop.production.log)

### Screenshots

![Screenshot 2023-02-27 220820](https://user-images.githubusercontent.com/110504159/221548428-e6a73bc0-2313-4e07-890b-dc665d4b4a9a.png)

### Additional context

It seems that the same text appears succeeding for the `public key` error.

**Comment by sergiou87** [comment]
Hey @DefNotCrawf ! 👋 

Have you set anything up to sign commits? It's possible that you have a `gpg.format` setting in C:/Users/<YourUser>/.gitconfig that you must remove.

**Comment by DefNotCrawf** [comment]
This is the .gitconfig file (converted into a .txt file for upload purposes).
[gitconfig.txt](https://github.com/desktop/desktop/files/10843769/gitconfig.txt)

P.S. I see the same string of characters in there

**Comment by DefNotCrawf** [comment]
I've also removed the `signing key =` variable to see if that works.

**Comment by DefNotCrawf** [comment]
Doesn't work; I get a `fatal: either user.signingkey or gpg.ssh.defaultKeyCommand needs to be configured` error.

**Comment by DefNotCrawf** [comment]
Fixed the problem; I had gpg signing enabled by accident.
I set:
```
[commit]
	gpgSign = false
```
and
```
[tag]
	gpgSign = false
```

**Comment by sergiou87** [comment]
@DefNotCrawf I think you can remove all these lines related to gpg signing:
```
	signingkey = CA47EF9CE4A8491A
[commit]
	gpgsign = true
[gpg "x509"]
	program = smimesign
[gpg]
	format = ssh
```

In any case, happy to know that you got it working!

**Comment by DefNotCrawf** [comment]
Thanks!
