### ISSUE TITLE
The default avatar should be local

### ISSUE THREAD

**Issue by alrz** [desktop/desktop#1621]
```js
const DefaultAvatarURL = 'https://github.com/hubot.png'
```
This should a local image (in case of failure in image loading, etc) or we could use:

- the first letter of author's name (or two letters for first and last name) to make that distinguishable.
- an auto generated avatar

**Comment by joshaber** [comment]
Agreed we should do something better and probably something local 👍 This'll need some design input.

**Comment by niik** [comment]
@caneroj1 sent us a screenshot of what the welcome flow looks like when GitHub.com can't be reached (see https://github.com/desktop/desktop/issues/1840). Given that offline users connecting to an Enterprise instance would see the same thing I recon this is something we should fix fairly soon and as such I'm gonna ask that we break this issue up and start out by just storing the hubot avatar image locally and hold off on the alternate avatar designs until I or @donokuda have some spare time.
