### ISSUE TITLE
UI not visible but i can see menu MacOs 10.13.6

### ISSUE THREAD

**Issue by ankitakratech** [desktop/desktop#16211]
### The problem

When I click on the GitHub desktop app icon from Dock, it shows nothing apart from the top menu of the GitHub desktop.

![Screen Shot 2023-02-25 at 12 18 03 PM](https://user-images.githubusercontent.com/53000973/221343164-1b71a6e2-7317-401a-98b1-c35ee17ddd7e.png)

### Release version

3.1

### Operating system

Mac OS 10.13.6

### Steps to reproduce the behavior

1. Click the GitHub Desktop icon from docker

![Screen Shot 2023-02-25 at 12 18 03 PM](https://user-images.githubusercontent.com/53000973/221343244-068203af-4ca5-46f2-9a1e-ef603e7ae63e.png)

### Log files

[2023-02-25.desktop.beta.log](https://github.com/desktop/desktop/files/10830476/2023-02-25.desktop.beta.log)

**Comment by sergiou87** [comment]
Hello! Sorry about that, it was a regression introduced in 3.1.9-beta1 that was impossible to spot in development builds 😞 

In order to fix it, you need to download the latest beta again from https://desktop.github.com/beta
