### ISSUE TITLE
Signing a commit failed

### ISSUE THREAD

**Issue by DefNotCrawf** [desktop/desktop#16222]
### The problem

I go to sign a commit with a GPG key (it worked before), I went to commit and then I ran into an error.
It said:
```
gpg: skipped "3B71B14A": No secret key
gpg: signing failed: No secret key
error: gpg failed to sign the data
fatal: failed to write commit object
```

### Release version

Version 3.1.8 (x64)

### Operating system

Windows 10 (22H2)

### Steps to reproduce the behavior

1. Make changes to the cloned repository.
2. Commit to main.
3. See the error message

### Log files

[2023-02-28.desktop.production.log](https://github.com/desktop/desktop/files/10848337/2023-02-28.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/110504159/221803952-2c219b63-7d42-42b5-82dc-804bb8e81f2c.png)

### Additional context

Commits were verified that were made after the GPG key was made. Although, after a shutdown of my computer the commits were unable to be done.

**Comment by DefNotCrawf** [comment]
Yeah, GitHub Desktop is buggy for me, eh? (Referencing [Issue #16218](https://github.com/desktop/desktop/issues/16218))

**Comment by steveward** [comment]
@DefNotCrawf in #16218 you mentioned you had enabled gpg signing by accident. If you are wanting to use it, you'll need to check your configuration to verify things are set correctly. Have you set your gpg key and gpg program in your `.gitconfig`?

**Comment by DefNotCrawf** [comment]
Yeah, I wanted to have GPG signing on. It was working (it was marked as verified) when I signed a commit directly after. After a shutdown, the signing did not work. (Although I didn't edit the .gitconfig file before or after the shutdown.)

**Comment by DefNotCrawf** [comment]
I don't know why it will fail even after not touching anything after verifying a commit.

**Comment by DefNotCrawf** [comment]
No comments have been made after my comment after 7 days, closing as stale.

**Comment by steveward** [comment]
I'd take a look at https://gist.github.com/xavierfoucrier/c156027fcc6ae23bcee1204199f177da to reference that things are configured correctly.

**Comment by DefNotCrawf** [comment]
Oh thanks!
