### ISSUE TITLE
Visual Studio showing Deleted Git Hub Repository

### ISSUE THREAD

**Issue by Pantology360** [desktop/desktop#16223]
### The problem

Visual Studio showing 2 Deleted Git Hub Repository 
and the manage branches on drop down menu on visual studio on git menu
has the delete disabled
have googled a few things but cannot find a solution
trying to use visual studio interface if possible
hoping you can help
Stephen

### Release version

Version 3.1.8 (x64)

### Operating system

Windows10

**Comment by steveward** [comment]
@Pantology360 this issue tracker is for GitHub Desktop, unfortunately we are unable to provide help for Visual Studio. I'd recommend asking for assistance at their community:

https://developercommunity.visualstudio.com/VisualStudio
