### ISSUE TITLE
I can't fetch anymore

### ISSUE THREAD

**Issue by XcreatorVco** [desktop/desktop#16221]
### The problem

After a merge error, my partners recovered the project and everything was fine, but in my PC, the github desktop lost track and couldn't fetch their changes, and now i'm stuck here trying to find out what to do
I've tried reinstalling both the game archives and github itself, but nothing changed
I've tried to 
git remote set-head origin --auto
git gc
 but it didn't worked either

### Release version

Version 3.1.8 (64x)

### Operating system

Windows 10

### Screenshots

![image](https://user-images.githubusercontent.com/110833816/221681102-b4038c0d-bfcd-424d-9fa7-5578453e4e1b.png)

**Comment by steveward** [comment]
@XcreatorVco can you run `git fsck` in your local repository and let me know what the output of that shows?

**Comment by daviramoncl** [comment]
wat the
