### ISSUE TITLE
Add an option to open with PhpStorm, WebStorm, or any IDE it can find.

### ISSUE THREAD

**Issue by JenuelDev** [desktop/desktop#16236]
### The feature request

It would be awesome if their is an option to open project depending on what IDE installed on my system, that way its a lot easier to  open project in IDE.

### Proposed solution

Add options in the Repository tab alongside "Open In Visual Studio"

**Comment by steveward** [comment]
Thanks for the feedback @BroJenuel, I'm going to add this to https://github.com/desktop/desktop/issues/12195 where we are tracking per-repo editor selection.
