### ISSUE TITLE
Issue about toolchain/Python

### ISSUE THREAD

**Issue by sky7d** [desktop/desktop#16233]
I'm desperate . i've got this thing 

D:\Try\flipperzero-firmware-wPlugins>fbt
Extracting Windows toolchain..Eccezione durante la chiamata di "ExtractToDirectory" con "2" argomento/i: "Il file
'D:\Try\flipperzero-firmware-wPlugins\gcc-arm-none-eabi-10.3-x86_64-windows-flipper\VERSION' esiste già."
In D:\Try\flipperzero-firmware-wPlugins\scripts\toolchain\windows-toolchain-download.ps1:35 car:1
+ [System.IO.Compression.ZipFile]::ExtractToDirectory("$toolchain_zip_t ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : IOException

Extracting Windows toolchain..Eccezione durante la chiamata di "ExtractToDirectory" con "2" argomento/i: "Il file
'D:\Try\flipperzero-firmware-wPlugins\gcc-arm-none-eabi-10.3-x86_64-windows-flipper\VERSION' esiste già."
In D:\Try\flipperzero-firmware-wPlugins\scripts\toolchain\windows-toolchain-download.ps1:35 car:1
+ [System.IO.Compression.ZipFile]::ExtractToDirectory("$toolchain_zip_t ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : IOException

Impossibile trovare il percorso specificato.
FBT: starting toolchain upgrade process..
Extracting Windows toolchain..Eccezione durante la chiamata di "ExtractToDirectory" con "2" argomento/i: "Il file
'D:\Try\flipperzero-firmware-wPlugins\gcc-arm-none-eabi-10.3-x86_64-windows-flipper\VERSION' esiste già."
In D:\Try\flipperzero-firmware-wPlugins\scripts\toolchain\windows-toolchain-download.ps1:35 car:1
+ [System.IO.Compression.ZipFile]::ExtractToDirectory("$toolchain_zip_t ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : IOException

Impossibile trovare il percorso specificato.
Python path configuration:
  PYTHONHOME = 'D:\Try\flipperzero-firmware-wPlugins\toolchain\x86_64-windows\python'
  PYTHONPATH = (not set)
  program name = 'python'
  isolated = 0
  environment = 1
  user site = 0
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = 'D:\Try\flipperzero-firmware-wPlugins\toolchain\x86_64-windows\python\Lib'
  sys._base_executable = 'D:\\Python\\python.exe'
  sys.base_prefix = 'D:\\Try\\flipperzero-firmware-wPlugins\\toolchain\\x86_64-windows\\python'
  sys.base_exec_prefix = 'D:\\Try\\flipperzero-firmware-wPlugins\\toolchain\\x86_64-windows\\python'
  sys.platlibdir = 'DLLs'
  sys.executable = 'D:\\Python\\python.exe'
  sys.prefix = 'D:\\Try\\flipperzero-firmware-wPlugins\\toolchain\\x86_64-windows\\python'
  sys.exec_prefix = 'D:\\Try\\flipperzero-firmware-wPlugins\\toolchain\\x86_64-windows\\python'
  sys.path = [
    'D:\\Python\\python311.zip',
    'D:\\Try\\flipperzero-firmware-wPlugins\\toolchain\\x86_64-windows\\python\\Lib',
    'D:\\Try\\flipperzero-firmware-wPlugins\\toolchain\\x86_64-windows\\python\\DLLs',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00004868 (most recent call first):
  <no Python frame>

(fbt) D:\Try\flipperzero-firmware-wPlugins>

Can you help me?

**Comment by steveward** [comment]
@sky7d this issue tracker is for [GitHub Desktop](https://desktop.github.com/). It looks like you are looking for support for a different repository hosted on GitHub.
