### ISSUE TITLE
Briefly broke my program

### ISSUE THREAD

**Issue by carlrthomas** [desktop/desktop#16237]
### The problem

Broke my project and across loading several commits I ended up with critical errors in Eclipse because GitHub was not correctly compiling all of the files from all recent commits, but instead a hodgepodge of different files from different commits since the branch I made.

### Release version

GitHub Desktop 3.1.8

### Operating system

Windows 11 22H2 (22621.1265)

### Steps to reproduce the behavior

0 clue. I just had 3 branches I was running. I branched off to one, then branched from there, then it was broken. Tried returning to main but that was also broken. Branched again then returned to main and it was magically fixed.

**Comment by sergiou87** [comment]
Hey @bihazards ! 👋 

Thanks for your report, I'm glad you managed to solve the issue. Unfortunately it's hard to tell what could be wrong… maybe some changes that were (or were not) carried over to the new branch?

In any case, I don't think there is much we can do about it if you're unable to reproduce it 😞 Please, let us know if it happens again. If so, please try to capture as much data as you can (like a screenshot of what the repo looks like on Desktop, logs, etc.), that way we can start investigating 🤞
