### ISSUE TITLE
Sub-accounts

### ISSUE THREAD

**Issue by Bashamega** [desktop/desktop#16232]
### The feature request

Hey:)
So I love GitHub and GitHub desktop.
I have an idea for it>
So, GitHub desktop only enables one account, even if I reinstalled the app, but people can have multiple accounts. For example, I have 2 GitHub accounts, this one and my other account, sometimes, I want to use GitHub desktop for my work account. But I can't switch between the accounts. I must make this account a contributor. and I would not like this.

### Proposed solution

I think Github desktop can have an option like the discord desktop to switch between accounts.
![4](https://user-images.githubusercontent.com/110662505/222132138-fb5ca77b-f3d7-4bf2-8adf-d16eacd8c29f.png)

### Additional context

I hope you think about it. Thanks!

**Comment by sergiou87** [comment]
Hey @Bashamega! Thanks for reaching out 💖  There's no way to add multiple GitHub.com accounts to Desktop at this time. You can have one GitHub.com account and one GitHub Enterprise Server account. We are tracking support for multiple accounts in https://github.com/desktop/desktop/issues/3707. Please subscribe to that issue to follow along with any development.

**Comment by Bashamega** [comment]
> Hey @Bashamega! Thanks for reaching out 💖 There's no way to add multiple GitHub.com accounts to Desktop at this time. You can have one GitHub.com account and one GitHub Enterprise Server account. We are tracking support for multiple accounts in #3707. Please subscribe to that issue to follow along with any development.

Thanks
