### ISSUE TITLE
Use commit template from gitconfig

### ISSUE THREAD

**Issue by TheGlorySaint** [desktop/desktop#16245]
### The feature request

I'd like to see an option where it is possible to select in the settings that GitHub desktop should load/use the commit template specified in the gitconfig, if any is specified and the option is enabled.

### Proposed solution

Option in GitHub Desktop Settings where User can enable to use gitconfig commit template if any is specified

**Comment by steveward** [comment]
Thanks for the feedback @TheGlorySaint, we are tracking support for commit templates in https://github.com/desktop/desktop/issues/8698 so you can follow along there for updates.
