### ISSUE TITLE
Batch conflicts resolving

### ISSUE THREAD

**Issue by horans** [desktop/desktop#16243]
### The feature request

![image](https://user-images.githubusercontent.com/12060804/222608806-fb433f98-e28d-4d7e-aaa9-6bf33c6569ec.png)

"Resolve conflicts before Merge" works fine, but it gets a little annoying when we have tons of conflicts.
In my case, we have to include production folder in git, and it will come up with multiple conflicts from time to time.
If I don't want to focus and click so many times, then I will have to do a "TAB, TAB, ENTER, ENTER, ENTER" loop all the way down to the bottom.

It will be life saver if a "batch conflicts resolving" feature is supported.

### Proposed solution

We can add a checkbox in front of each conflict item, and adding batch resolve options to the footer of current dialog.

**Comment by steveward** [comment]
Thanks for the issue @horans, I'm going to group this with https://github.com/desktop/desktop/issues/16199, which is the same request. I'll add your feedback there.
