### ISSUE TITLE
Automatically push tags when pushing a tagged commit

### ISSUE THREAD

**Issue by ImRodry** [desktop/desktop#16249]
### The feature request

It would be nice to have GitHub Desktop automatically push all tags in pushed commits to the remote. I found no other way to do that other than through the command line

### Proposed solution

This could be a setting and/or a warning before pushing to prevent accidentally pushing tags that shouldn't be pushed. Furthermore, there should also be a button on the tag to push it to the remote if it hasn't been already in order to allow users to push only select tags

**Comment by niik** [comment]
Hey @ImRodry, at this time we only support pushing tags that have been created from within Github Desktop itself. We don't want to accidentally push tags created for local use. If your workflow requires that you push tags created by external tools (CLI, build scripts etc) you could try setting the global (or per-repo) config setting [`push.followTags`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-pushfollowTags) which will push all tags on every push (regardless of the push being done through the CLI or through GitHub Desktop).

**Comment by ImRodry** [comment]
Oh that works for me, I didn't know that was a setting. Thanks!
