### ISSUE TITLE
Cloning a wiki fails

### ISSUE THREAD

**Issue by steveward** [desktop/desktop#1624]
### Description

Cloning a wiki in the app or via the `Clone in Desktop` button on the wiki's page fails.

### Version

**GitHub Desktop version:** 0.5.3

**OS version:** macOS 10.12.4

### Steps to Reproduce

1. Open a wiki on GitHub
2. Click `Clone in Desktop`

**Expected behaviour:** [What you expected to happen]

The wiki is cloned.

**Actual behaviour:** [What actually happened]

The app returns a `We couldn't find that repository` error. Console shows a 404, e.g.:`GET https://api.github.com/repos/<user>/<repo>.wiki 404`.

**Reproduces how often:** 100%

**Comment by niik** [comment]
I feel like we've fixed this several times over in the classic apps 😄

**Comment by joshaber** [comment]
lol that was my exact thought too. This ol' chestnut.

**Comment by shiftkey** [comment]
![](https://media.giphy.com/media/91X2MlgF7dHsA/giphy.gif)

**Comment by KingOfBadHabits** [comment]
Anyone have the fix yet?

**Comment by joelzamboni** [comment]
+1

**Comment by mumcs01** [comment]
Though the error is gone, anyone else actually getting this to work. Now it just hangs when you press Clone happily spinning away forever. 
![github problem](https://user-images.githubusercontent.com/28830298/27489127-0cc0ed3c-57ff-11e7-8b2f-4b5ff5fd5021.PNG)

**Comment by shiftkey** [comment]
@mumcs01 I can see the same behaviour on 0.6.2 on macOS - poking at the developer tools log I don't see the `git clone` command starting, so there's probably something in there we've missed.

**Comment by shiftkey** [comment]
Thankfully this was a minor regression - see @2097 for the fix. I'll close this out, but in the meantime you can use "Clone in Desktop" to get the repository into the app.
