### ISSUE TITLE
Search for changes by file name in the history

### ISSUE THREAD

**Issue by ZeoNish** [desktop/desktop#16247]
### The feature request

Search for changes by file name in the history.

Implement a search for all commits where the file was changed by its name.

### Proposed solution

Implement an in-app search in the history section

**Comment by steveward** [comment]
Thanks for the feedback @ZeoNish, this is being tracked in https://github.com/desktop/desktop/issues/7022 so I would recommend following along there for updates. Thanks for using Desktop!
