### ISSUE TITLE
Can't login with github account

### ISSUE THREAD

**Issue by igen0101z** [desktop/desktop#16253]
### The problem

After login with browser, Github Desktop show this message. I can't even read it.
<img width="480" alt="image" src="https://user-images.githubusercontent.com/40468296/222902591-903123eb-aa38-4c8d-a528-d6b56abf2fc4.png">

### Release version

Version 3.2.0 (x64)

### Operating system

Windows 11 22621.1265

### Steps to reproduce the behavior

1. Go to Options
2. Click on Sign in
3. Click on Continue with browser
4. Show the error message

### Log files

[2023-03-04.desktop.production.log](https://github.com/desktop/desktop/files/10888367/2023-03-04.desktop.production.log)

### Additional context

Github Desktop works on my other computer running windows10

**Comment by niik** [comment]
Hey @igen0101z, thanks for reaching out. This error is coming from Windows when we attempt to store your credentials (see https://github.com/desktop/desktop/issues/12712#issuecomment-891059379). I have no idea why it would be unreadable though, I suspect something odd may be going on with your machine. Have you ever been able to sign in to GitHub Desktop on this machine? One user did report being able to clear this error by opening credential manager and deleting any old GitHub credentials in there: https://github.com/desktop/desktop/issues/12712#issuecomment-1236430799.

**Comment by igen0101z** [comment]
Thanks a lot.
I sloved it by using administrator to open Github Desktop.
