### ISSUE TITLE
Failed to create child process during git pull from main branch

### ISSUE THREAD

**Issue by edgarcnp** [desktop/desktop#16255]
### The problem

I tried to pull from my main branch, the files are pulled correctly but then this error showed up:

0 [main] sh 712 dofork: child -1 - forked process 29568 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\user\AppData\Local\GitHubDesktop\app-3.2.0\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
1102871 [main] sh 712 dofork: child -1 - forked process 32708 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\user\AppData\Local\GitHubDesktop\app-3.2.0\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
3195761 [main] sh 712 dofork: child -1 - forked process 9176 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\user\AppData\Local\GitHubDesktop\app-3.2.0\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
7304668 [main] sh 712 dofork: child -1 - forked process 18500 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\user\AppData\Local\GitHubDesktop\app-3.2.0\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
15408981 [main] sh 712 dofork: child -1 - forked process 31576 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\user\AppData\Local\GitHubDesktop\app-3.2.0\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: Resource temporarily unavailable

### Release version

Version 3.2.0 (x64)

### Operating system

Windows 11 Pro

### Steps to reproduce the behavior

1. git pull from main branch
2. the files are pulled correctly but the errors keep showing up

### Log files

[2023-03-05.desktop.production.log](https://github.com/desktop/desktop/files/10892945/2023-03-05.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/56579802/222982940-65a52d8a-1261-4908-bf9d-5334741c3a61.png)

### Additional context

I've tried reinstalling Github Desktop but the issue still persist, even with turning off my AV (Kaspersky) the issue still persist.

**Comment by niik** [comment]
Hey @PecorinoDev, thanks for reaching out. This error is usually caused by Mandatory ASLR, please see https://github.com/desktop/desktop/blob/development/docs/known-issues.md#enable-mandatory-aslr-triggers-cygheap-errors

Please try disabling mandatory ASLR and let us know if that helped!

**Comment by edgarcnp** [comment]
Hi @niik , thanks for the respond. I've managed to disable the mandatory ASLR and it solves my issue, thank you once again and have a nice day!
