### ISSUE TITLE
Folder features

### ISSUE THREAD

**Issue by Bikeshtri** [desktop/desktop#16258]
### The feature request

It will be good to have a folders for arrange the repository in the repository view section

### Proposed solution

Implement a feature to add folder in the repository view section.
- Need to have a option to create folder in repository view
- Need an option for add repositories inside the created folder  
- Need an option for move existing repositories inside the folder (drag and drop)

**Comment by niik** [comment]
Thanks for the feedback @Bikeshtri. See [this comment](https://github.com/desktop/desktop/issues/10201#issuecomment-658693653) for more information about why we do not have plans to implement repository grouping at this time. 

One workaround is to use the repository alias feature and then use that to filter by a specific alias prefix. I hope that helps.
