### ISSUE TITLE
Two-factor Authentication for Enterprise

### ISSUE THREAD

**Issue by adjohnson916** [desktop/desktop#1625]
### Description

Can't get two-factor authentication to work for Enterprise. Is that supposed to be supported at this time?

### Version

**GitHub Desktop version:** 0.5.5

**OS version:** macOS Sierra 10.12.4 (16E195)

### Steps to Reproduce

Attempt to authenticate to Enterprise with credentials. No prompt for a two-factor authentication code is displayed. Same experience both in app and with "Sign in using your browser".

App shows error:
> The server responded with an error while attempting to authenticate (500)
> 
> Internal Server Error

![screen shot 2017-05-18 at 12 48 03 pm](https://cloud.githubusercontent.com/assets/615381/26216043/4a4cee4c-3bc8-11e7-9ab6-07476b7b55a6.png)

**Expected behaviour:** Authenticate correctly with two-factor.

**Actual behaviour:** Errors.

**Reproduces how often:** Consistently.

### Logs

I don't see a folder called `~/Library/Application Support/GitHub Desktop/logs` or anything but an IndexedDB log with `ls ~/Library/Application\ Support/GitHub\ Desktop/**/*.log`.

#### Additional Information

Feel free to ask.

**Comment by joshaber** [comment]
@adjohnson916 Could you try opening the dev tools to see if there's anything logged in there? Go to View > Toggle Developer Tools to see them.
