### ISSUE TITLE
Theme Background

### ISSUE THREAD

**Issue by Bashamega** [desktop/desktop#16257]
### The feature request

I think it would be nice if you added themes to the GitHub desktop.

### Proposed solution

I think you can make multiple themes like VS Code

**Comment by niik** [comment]
Hey @Bashamega, thanks for reaching out. At the moment we have two themes built into the app, a Light and a Dark theme and we're investigating adding a high contrast mode to these themes. At this point we don't have any plans of adding more themes but we appreciate the suggestion!

<img width="615" alt="image" src="https://user-images.githubusercontent.com/634063/223070360-1752ed43-8562-43fd-8219-0bb63cb24f4e.png">

**Comment by Bashamega** [comment]
> Hey @Bashamega, thanks for reaching out. At the moment we have two themes built into the app, a Light and a Dark theme and we're investigating adding a high contrast mode to these themes. At this point we don't have any plans of adding more themes but we appreciate the suggestion!
> 
> <img alt="image" width="615" src="https://user-images.githubusercontent.com/634063/223070360-1752ed43-8562-43fd-8219-0bb63cb24f4e.png">

Thanks
