### ISSUE TITLE
I still remember the old times when the visual graph was there, I'd really like this back please

### ISSUE THREAD

**Issue by Deus-nsf** [desktop/desktop#16267]
### The feature request

The visual graph really helps beginners a lot by visualizing the evolution of the branches in real time, please bring it back it really is the most important thing this software has ever done...

### Proposed solution

It will help a lot when you want to start new projects with beginners for example, they already have the complexity of learning new tech, if git can be simplified for them that'll be a great thing, I know the visual graph helped me immensely when I started with git back in the days.

**Comment by steveward** [comment]
Thanks for the feedback @Deus-nsf, please follow along in https://github.com/desktop/desktop/issues/9452 for updates about this feature.
