### ISSUE TITLE
Github Desktop is committing unstaged files

### ISSUE THREAD

**Issue by dylanjt** [desktop/desktop#16260]
### The problem

I carefully selected the files and hunks I wanted included in my commit using Github Desktop. Then I pressed commit. I was surprised to see that many unstaged files were included in the commit, and had to "undo" the commit.

### Release version

Version 3.2.0 (arm64)

### Operating system

MacOS 13.0.1

### Steps to reproduce the behavior

1. Stage changes for commit, leaving some changes unstaged
2. Press commit
3. Observe that unstaged changes were included in the commit

**Comment by dylanjt** [comment]
Closing, discovered this was due to an internal misconfigured git hook.

**Comment by BirgitPohl** [comment]
I removed my githook and discovered this is still the case for me that "unstaged files" are being committed.
Is unchecking the checkmark not supposed to indicate that the file will not be committed?
