### ISSUE TITLE
Changes are still visible after commit

### ISSUE THREAD

**Issue by romanmyshchyshyn** [desktop/desktop#16264]
### The problem

When I commit my changes they are still visible. And when I try to commit again I see an error message 'There are no changes to commit'.

![image](https://user-images.githubusercontent.com/38398964/223476764-5f6894c4-d068-443e-a5f4-792ef2dfe067.png)

### Release version

3.2.0

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Make some changes
2. Commit them
3. Wait until loading disappears
4. Changes are still present

### Log files

[2023-03-07.desktop.production.log](https://github.com/desktop/desktop/files/10911429/2023-03-07.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/38398964/223476764-5f6894c4-d068-443e-a5f4-792ef2dfe067.png)

**Comment by steveward** [comment]
Thanks for the issue @2end. Here's the full error output i'm seeing in the log:

```
2023-03-07T15:55:45.932Z - error: [ui] `git commit -F -` exited with an unexpected code: 1.
stdout:
On branch features/75495-Build-Provisional-Invoice]-Amount-column-+-Sales-Ops-AC-for-both-Chile-&-SGP
Your branch is ahead of 'origin/features/75495-Build-Provisional-Invoice]-Amount-column-+-Sales-Ops-AC-for-both-Chile-&-SGP' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

(The error was parsed as 17: There are no changes to commit.)
```

The output is showing that there are changes that need to be pushed. 🤔 Can you open the repository in the command line and run `git status` and let me know the output? I'd also recommend trying to commit directly in the command line to see if that shows any further helpful output:

`git add -A`
`git commit -m "your commit message"

Let me know if that shows anything interesting.

**Comment by romanmyshchyshyn** [comment]
@steveward this is the result of git status when I committed via GitHub Desktop
![image](https://user-images.githubusercontent.com/38398964/223634935-fa900255-6e42-47ef-9f87-851af1e6e9c6.png)

the result when I commit via command line
![image](https://user-images.githubusercontent.com/38398964/223635571-23e74c2e-ef8b-47cd-8730-8a0be802d0c8.png)

However, when I commit via command line and change focus to GitHub Desktop app then changes disappear
![image](https://user-images.githubusercontent.com/38398964/223635835-f8d71c92-991e-4b0c-8d04-02abaa0ffb14.png)

**Comment by steveward** [comment]
It looks like there is a trailing space in the directory name that is likely causing the "no such file or directory" error. I'd recommend trying to fix that to see if it resolves things, as trailing spaces aren't allowed on Windows.

**Comment by romanmyshchyshyn** [comment]
@steveward Thank you! this solved the issue

**Comment by steveward** [comment]
Glad to hear things are working now!
