### ISSUE TITLE
Unable to Fetch Origin (using Github Desktop)

### ISSUE THREAD

**Issue by bglassettUSIN** [desktop/desktop#16271]
### The problem

I am using Github desktop to retriee changes in a branch of my repository.  I am able to switch branches in this repository (named Snowflake-Datalake-Curated-Transactional); however when I try to Fetch Origin I recieve the following error:

remote: Enumerating objects: 124, done.        
remote: Counting objects: 100% (117/117), done.        
remote: Compressing objects: 100% (54/54), done.        
remote: Total 88 (delta 56), reused 62 (delta 34), pack-reused 0        
fatal: unresolved deltas left after unpacking
fatal: unpack-objects failed

How can I attempt to resolve this issue?

### Release version

3.2.0

### Operating system

Windows 10

### Steps to reproduce the behavior

1.  change current repository
2. change to desired branch
3. Click on Fetch Origin.

### Log files

[2023-03-08.desktop.production.log](https://github.com/desktop/desktop/files/10922763/2023-03-08.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/64502588/223772766-2e7b37d3-e0bd-49ae-adfb-1121bf968f56.png)

**Comment by steveward** [comment]
@bglassettUSIN thanks for the issue. Can you open the repository in the command line and run `git fsck` and let me know if that shows any errors in the output?
