### ISSUE TITLE
SquirrelTemp AppData

### ISSUE THREAD

**Issue by Giles-W** [desktop/desktop#16275]
I found that after using GitHub Desktop for a few years on the same machine, there is a problem with the update delivery system, which I believe is Squirrel.

I found that my SquirrelTemp folder in AppData (Windows 2019 Server), is sitting at 6.2Gb. All of these files are related to GitHub Desktop updates.

Auto cleanup needs to be addressed. This is naturally something we shouldn't be needing to do manually.

**Comment by steveward** [comment]
@Giles-W thanks for the report. We've made improvements to prevent this (see https://github.com/desktop/desktop/pull/15416), so this should no longer be an issue.
