### ISSUE TITLE
For language selection requirements

### ISSUE THREAD

**Issue by Sdeo-Dun** [desktop/desktop#16278]
### The feature request

Request that you be able to add a selection of languages

### Proposed solution

Added the ability to select "language"

**Comment by niik** [comment]
Thanks for the issue @BaiDei202101. At this time we do not have language localization in GitHub Desktop, but this is something that we would like to do in the future. I don't have a timeline for when that may happen as it would require quite a bit of work by the team. I'm sorry that I don't have better news at this time.

**Comment by BaiDei202101** [comment]
Thank you very much @niik  feel very sorry to know this incident, but I am full of confidence in your ability to work! I hope your leaders are receptive. No country has a large national language! Then we can try to give him only a framework, as for the specific language, they will work out! Look! How about that?

**Comment by BaiDei202101** [comment]
Thank you very much @niik . feel very sorry to know this incident, but I am full of confidence in your ability to work! I hope your leaders are receptive. No country has a large national language! Then we can try to give him only a framework, as for the specific language, they will work out! Look! How about that?

**Comment by Sdeo-Dun** [comment]
Thank you very much @niik . Feel very sorry to know this incident, but I am full of confidence in your ability to work! I hope your leaders are receptive. No country has a large national language! Then we can try to give him only a framework, as for the specific language, they will work out! Look! How about that?

**Comment by Sdeo-Dun** [comment]
Ok! I see! Thank you very much @niik .
