### ISSUE TITLE
Improve error message when Enterprise is too old

### ISSUE THREAD

**Issue by lpd8-chaff** [desktop/desktop#1628]
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

GitHub Desktop version 0.5.5 is having trouble connecting to my GitHub Enterprise instance.  The error it displays after entering my credentials is "Cannot read property 'Symbol(Symbol.iterator)' of undefined"

Server info and login credentials were thoroughly verified.

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

GitHub Desktop version: 0.5.5

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

Microsoft Windows [Version 6.1.7601]

### Steps to Reproduce

1. Under Options --> Accounts --> Enterprise --> Sign in
2. Entered enterprise server address
3. Clicked Continue
4. Entered username and password
5. Clicked Sign in
6. Read error message
7. Copied error message
8. Submitted error report...

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behaviour:** [What you expected to happen]

**Actual behaviour:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by joshaber** [comment]
@lpd8-chaff Thanks for reporting this! Could you check dev tools and paste any errors in here? You can get to them from View > Toggle Developer Tools.

**Comment by amellnik** [comment]
![image](https://cloud.githubusercontent.com/assets/7132414/26224151/fa89bd96-3bd5-11e7-9396-f958d63b7da3.png)

![image](https://cloud.githubusercontent.com/assets/7132414/26224175/13dbac82-3bd6-11e7-8425-97c8a0d48df6.png)

**Comment by shiftkey** [comment]
@lpd8-chaff @amellnik my gut feeling on this is that it's related to older versions of GitHub Enterprise. Do you know which version you are connecting to?

**Comment by amellnik** [comment]
@shiftkey  2.4, and I bet you're right =)

**Comment by shiftkey** [comment]
Sigh. @joshaber do you remember which version of GHE our changes made it into? 2.8?

**Comment by amellnik** [comment]
I can confirm that 2.8 works.

**Comment by shiftkey** [comment]
@amellnik thanks for confirming!

In theory we [show a message](https://github.com/desktop/desktop/blob/89b71a704007cd62b45db6ebdb279abd8deadc0b/app/src/lib/dispatcher/sign-in-store.ts#L230) with a hint that we only support 2.8 or later, but I guess we need to handle this error too which occurs later in the flow.

**Comment by dumptruckusa** [comment]
I have the same problem using GitHub Enterprise 2.7 using Mac OS 10.11.6.
