### ISSUE TITLE
Github "Can't Find" Repo, I use "Locate," finds, after few seconds, back to "Can't find"

### ISSUE THREAD

**Issue by masterchinchilla** [desktop/desktop#16285]
### The problem

I didn't move the repo. I realized the root folder wasn't backing up in my OneDrive, so I force-uploaded it there. Nothing changed in the local directory, but somehow this caused Github to "lose" the repo. When I try to open it, it pops up with a message "Can't find [repo name]." Under this it displays "It was last seen at" a directory where the repo is located which has not changed. I click "Locate" and select that same folder. It seems to work for a few seconds (but it says "publish branch" up top, even though the branch was already published). But then it jumps back to the "Can't find" screen.
I tried searching for this issue on google but am not finding it.
I had uncommitted changes, so I don't want to re-clone from Github.
Please help.

### Release version

Version 3.2.0 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

Open Github Desktop
Repo home displays "Can't find [repo name]" even though repo wasn't moved
I click "Locate" button and select folder where repo has always been
Seems to work, but after a few seconds, returns to "Can't find" screen

### Log files

[2023-03-09.desktop.production.log](https://github.com/desktop/desktop/files/10932808/2023-03-09.desktop.production.log)
[2023-03-08.desktop.production.log](https://github.com/desktop/desktop/files/10932809/2023-03-08.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/47091399/224064466-56905426-a80a-4d8a-aabf-9e4880848ff6.png)
![image](https://user-images.githubusercontent.com/47091399/224064512-fd212b4e-6a0c-4998-88b8-ffd1afd057bb.png)

**Comment by steveward** [comment]
@masterchinchilla thanks for the issue. Storing repositories in OneDrive can sometimes cause issues like this. Can you try temporarily moving your repository out of OneDrive and then try removing/adding it back to GitHub Desktop?

If that doesn't resolve things then there may be an issue with the repository database -- you could try "resetting" the app and adding your repositories back via drag-and-drop. Here's how to do that:

1. Close GitHub Desktop 
2. Open File Explorer and remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop

**Comment by VividPups** [comment]
didnt work

**Comment by sambamuel2** [comment]
For anyone having the same issue - Just close your project. Or just try repeatedly. its using ghost magic or something because mine just started working again

**Comment by herbertcwang** [comment]
I had to commit/push everything by command prompt (windows) and github desktop worked again.  This required a few steps:
- 'git add .'
- 'git commit -m "commit msg" '
- 'git push' 
- I had a few errors between these steps that gpt helped me with as well

**Comment by emmercm** [comment]
Making a commit also fixed it for me, but I did an empty one:

```shell
git reset
git commit --allow-empty --message='Empty commit'
```
