### ISSUE TITLE
Error: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

### ISSUE THREAD

**Issue by MuthoniKinyua** [desktop/desktop#16297]
I am getting this error when trying to add a vagrant box in my command prompt.Please help to resolve the issue

**Comment by yawpreko** [comment]
I've been facing the same issue for the past 4 days. Hope we get answers.

**Comment by MuthoniKinyua** [comment]
I found a solution.Add --insecure to the vagrant box

**Comment by steveward** [comment]
If you are encountering this issue in GitHub Desktop you can read the [section of our known issues document ](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#certificate-revocation-check-fails) for steps on how to resolve this error.

**Comment by yawpreko** [comment]
Omg! Thank you so much MuthoniKinyua. You've saved me days of struggle. Download successful! I'm grateful for getting back to respond.

**Comment by MuthoniKinyua** [comment]
You are welcome.Happy coding

**Comment by T-olorunwa** [comment]
Thank you so much. I have been encountering the same issue for some time now
