### ISSUE TITLE
Unable to give workflow scope to Github Desktop

### ISSUE THREAD

**Issue by euangeleo** [desktop/desktop#16296]
I'm using GitHub Desktop from the command line in Unbuntu 22.04. I've authenticated with GitHub.com in Github Desktop.

I'm trying to push a local repo (which uses a workflow) to GitHub.com, but when I do, I get an error:

```
user@machine:path$ git push -u origin main
Enumerating objects: 68, done.
Counting objects: 100% (68/68), done.
Delta compression using up to 16 threads
Compressing objects: 100% (55/55), done.
Writing objects: 100% (68/68), 911.25 KiB | 28.48 MiB/s, done.
Total 68 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/<org>/<redacted>.git
 ! [remote rejected] main -> main (refusing to allow an OAuth App to create or update workflow `.github/workflows/docs.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/<org>/<redacted>.git'

```

I've found [instructions online](https://www.johneverettcase.com/post/2021/07/22/git-workflow-access-token.html) for adding the appropriate scope to an existing personal access token. However, the token that is being used by GitHub Desktop (listed using `gh auth token`) does not show up in the list of personal access tokens in my Developer Settings on GitHub.com. How can I grant the needed scope to the authentication method being used by GitHub Desktop?

**Comment by euangeleo** [comment]
RESOLVED by logging out of GitHub Desktop and logging in again with the new PAT.

**Comment by linonetwo** [comment]
Simply relogin Not working for me.
