### ISSUE TITLE
No drop down to select Default Editor

### ISSUE THREAD

**Issue by crmarksiv** [desktop/desktop#16295]
### The problem

New Install.  When I go to File>Options> Integration the help says I should get a dropdown so I can select an editor.  I do not get the drop down.

### Release version

3.2.0*(x64) 

### Operating system

windows 10

### Steps to reproduce the behavior

File 
Options
Integrations 

only drop down is for Shell

**Comment by steveward** [comment]
@crmarksiv if you do not have any external editors currently installed then the dropdown will not be present, and you should see a recommendation to install Visual Studio Code. See the list of supported editors [here](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/configuring-and-customizing-github-desktop/configuring-a-default-editor). Let me know if you have any further issues.
