### ISSUE TITLE
Suddenly Github Desktop stopped working today with disabled app icon, please help to install

### ISSUE THREAD

**Issue by sumasan** [desktop/desktop#16291]
### The problem

![Screen Shot 2023-03-10 at 3 44 23 PM](https://user-images.githubusercontent.com/105495462/224292500-4d39b75c-7710-484d-9deb-95f3eaa30580.png)
![Screen Shot 2023-03-10 at 3 58 27 PM](https://user-images.githubusercontent.com/105495462/224292765-52e32eda-d37d-4917-95d1-928d6e7c4e94.png)

### Release version

3.2.0

### Operating system

Mac OS 10.12.6

### Steps to reproduce the behavior

1. found disabled icon in application folder, after clicking app icon , shows the error as attached picture
2. moved github desktop app to thrash
3. emptied thrash
4. installed latest version github desktop 3.2.0 from website
5. app get installed , but App Icon will be disabled look as attached 
6. after clicking app icon , shows the error as attached pic

### Screenshots

![Screen Shot 2023-03-10 at 3 58 21 PM](https://user-images.githubusercontent.com/105495462/224294889-3b85c103-1774-404f-a3d9-5d66efc74902.png)
![Screen Shot 2023-03-10 at 3 44 23 PM](https://user-images.githubusercontent.com/105495462/224294904-ed7fbf58-895a-4a1f-9558-4eaa7ddf2ff5.png)

**Comment by sergiou87** [comment]
I'm sorry but with the recent Electron upgrade in v3.1.8 (see #16155), we inadvertently dropped support for that macOS version, and now 10.13 is the minimum required.

We're updating the documents to reflect this new reality. Unfortunately, there is no way to solve this and you will need to upgrade your macOS installation if you want to use the latest versions of the app.

In case it's helpful, here you can download v3.1.7, which is the last working version on macOS 10.12: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.1.7-97eef004/GitHubDesktop-x64.zip

However, beware it will try to auto-update every time you open it 😕

**Comment by sumasan** [comment]
Thank you so much for the info

**Comment by sumasan** [comment]
![Screen Shot 2023-03-10 at 5 20 25 PM](https://user-images.githubusercontent.com/105495462/224309048-7b71f8ad-b739-4aca-a114-fe66ce25176c.png)
