### ISSUE TITLE
Publish GitHub Desktop on Windows in the Microsoft Store

### ISSUE THREAD

**Issue by Sergio0694** [desktop/desktop#16303]
### The feature request

The new Microsoft Store allows unpackaged applications to be published as well (see [here](https://blogs.windows.com/windowsdeveloper/2021/09/28/microsoft-store-more-apps-more-open/) and [here](https://blogs.windows.com/windowsexperience/2021/06/24/building-a-new-open-microsoft-store-on-windows-11/)), meaning all kinds of apps are welcome (not just packaged MSIX apps like in the past). Currently, GitHub Desktop also has an MSI installer, but this is only available for download from https://desktop.github.com/. I would like to request also publishing GitHub Desktop in the Microsoft Store. This would make it much easier for Windows users to download it, and it would also benefit from other features built-in into Windows (for instance, App Restore).

### Proposed solution

The request is just for publishing GitHub Desktop in the Microsoft Store. Keeping an unpackaged app is fine, so no additional work is needed. It's really mostly just about creating a submission in the Store for the MSI installer, and providing the necessary info.

**Comment by niik** [comment]
Thanks for reaching out and providing so much detail here. Our MSI unfortunately isn't a general purpose installer like the Microsoft store would expect, instead it's meant to be used for machine-wide installations (our default installer is per-user and doesn't require admin privileges). See https://github.com/desktop/desktop/issues/776#issuecomment-334378889 for more detail on that. So I don't think uploading our MSI to the MS store is the way to go here. Regardless I'm closing this issue in favor of https://github.com/desktop/desktop/issues/12524 but copying your well written issue into that more terse issue.
