### ISSUE TITLE
Launch desktop from the commandline

### ISSUE THREAD

**Issue by cameronmcefee** [desktop/desktop#1630]
(apologies for ignoring the bug report format, this is more of a question)

In the previous iteration of Desktop, I could launch the app from the command line like `github .`, which doesn't seem to work now. Have I missed an option to enable this, or do I have to set it up manually?

**Comment by niik** [comment]
Hey @cameronmcefee! Long time no see! We currently don't have that but we're tracking it in https://github.com/desktop/desktop/issues/696.

There's some hacks down there that might be interesting in the meantime like https://github.com/desktop/desktop/issues/696#issuecomment-301899759.

I'm gonna close this out but please add any comments you might have to that issue.

**Comment by cameronmcefee** [comment]
:+1: Good to hear from you. Thanks!
