### ISSUE TITLE
Can't commit S§$%

### ISSUE THREAD

**Issue by neubern** [desktop/desktop#16304]
### The problem

I have been trying to use Git for the last 3 days. My experience is ABYSMAL. Truly horrible

I can't event start, how wrong are things in the User Experience perspective. 
Trying to commit your files to a server is harder than committing a crime! 
I'm using Git to make a backup of my Unity files (2.3gb). The size is wrong though, cause Git is ignoring my .gitignore.... Both of them! (One in root, one in the folder with my assets). Even using the default .gitignore provided as a template doesn't fix much (My library folder always get committed?).

Then, after I try uploading all files (either using github or terminal), I get a Remote Disconnect.
I already followed every damn tutorial about changing internet speed velocity minimum, or changing the buffer size of files, even SSH keys. Nothing works here!

I tried uploading my folders one by one. I add the File / Folder, then commit:
Look what I get:
`neubern@Danilos-MacBook-Pro XYX % git add ./ProjectSettings/ 
neubern@Danilos-MacBook-Pro XYX % git commit ./ProjectSettings/
On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .DS_Store

no changes added to commit (use "git add" and/or "git commit -a")
`
Fuckin A! Making me go in circles!

After all this time trying to commit a single folder, how is it that is so hard to get this working?!
An GUI Interface, but it's horrible. Have you guys ever heard of FTP? Remember the Interface? Drag and Drop files?
It seems the Git Design Team took everything mankind learned about user experience and said: "fuck this".

### **I can't believe that zipping a file, and putting it in a Chinese USB stick is proving more efficient than your service.** 

As much as want to use your service for what it can offer, I have been unable to use it, and my experience with it drew me farther away from using it.

### Release version

latest

### Operating system

MacOs

### Steps to reproduce the behavior

Install GIT. Your problems start

**Comment by niik** [comment]
He @neubern. While I can understand your frustration, your comment is considered a violation of the [Desktop Code of Conduct](https://github.com/desktop/desktop/blob/development/CODE_OF_CONDUCT.md) as it was unprofessional and derogatory. You may consider this an official warning.

I'm going to close this issue. If you have actionable feedback or a specific problem related specifically to GitHub Desktop (this is not a general support repository for Git) feel free to open a new one, staying to the template and refraining from unprofessional language.

Please consult the available [documentation](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github) on working with large files and large repositories before you do so.
