### ISSUE TITLE
Changes are not reflected to commit

### ISSUE THREAD

**Issue by priyashanmuganathan** [desktop/desktop#16314]
### The problem

I have changed lot of files in a branch code . While trying to commit, some changed files are not shown in the changes list. But file changes are present in EDI ,not reflected in GITHUB. I have faced this issue many times. The same file code changes are reflected in others github.

### Release version

Version 3.2.0 (x64)

### Operating system

windows 10

### Steps to reproduce the behavior

Change content in files
some changed files are present in github changes list

**Comment by steveward** [comment]
@priyashanmuganathan thanks for the issue. Just to confirm, are your files being saved in your editor? If you don't have autosave enabled then your changes won't appear until they are saved. I'm not sure what editor you are using but wanted to make sure that wasn't a potential cause.

The other thing to check would be the `.gitignore` in your repository. Can you verify that the missed files have not been added to your `.gitignore`? You can check your `.gitignore` by going to `Repository` > `Repository Settings` > `Ignored Files`.

**Comment by BhavinPanchal001** [comment]
I encountered an error where changes I made appeared in the Changes tab after fetching data from the main branch, but disappeared after completing a pull. Additionally, the changes were not present in my local folder. This issue does not occur consistently, but only occasionally
