### ISSUE TITLE
Change remote URL for a repository

### ISSUE THREAD

**Issue by Sebastien-Remy** [desktop/desktop#16319]
### The problem

I change remote directory in setting everything works well and pushes are send to the new remote directory but when I click on the View on GitHub button it's open a webpage with the old repository

### Release version

Version 3.2.0 (arm64)

### Operating system

macOS Ventura 13.2.1

### Screenshots

Setting new directory remote
<img width="581" alt="Capture d’écran 2023-03-14 à 19 36 36" src="https://user-images.githubusercontent.com/55869882/225104665-91e7abf9-9aac-4bf9-acb9-6da07ae3dde4.png">

After clicking view on GitHub :(
<img width="599" alt="Capture d’écran 2023-03-14 à 19 36 56" src="https://user-images.githubusercontent.com/55869882/225104788-8d2f0281-3c97-4e5c-b5cc-87976520b8e7.png">

**Comment by steveward** [comment]
Thanks for the report @Sebastien-Remy. This was previously reported in https://github.com/desktop/desktop/issues/7690, I'll bump that issue up.
