### ISSUE TITLE
GitHub Desktop failed to launch

### ISSUE THREAD

**Issue by Zac-Garby** [desktop/desktop#1631]
### Description

I tried to open gh desktop, and it immediately crashed, giving me the following message:

![screen shot 2017-05-18 at 21 04 44](https://cloud.githubusercontent.com/assets/19708658/26221217/a3781434-3c0d-11e7-9b66-568b27ee658e.png)

**Comment by joshaber** [comment]
Thanks! We're already tracking this in #1564. Feel free to follow along there!
