### ISSUE TITLE
New login procedure through Browser - missing logout function

### ISSUE THREAD

**Issue by int-red** [desktop/desktop#16322]
### The problem

With the new login procedure through Browser I can authorize GitHub Desktop, but I can not find anywhere how to log out / deauthorize GitHub Desktop.

### Release version

3.2.0

### Operating system

Windows 10

**Comment by steveward** [comment]
@int-red thanks for the issue. Once you log in via your browser you can log out by going to `File` > `Options` > `Accounts` and selecting `Sign Out`.

**Comment by int-red** [comment]
Thanks for the quick feed back!

That's hidden very well ;)
I think this should be accessible more easily.
