### ISSUE TITLE
Ability to pin repos in main repo list

### ISSUE THREAD

**Issue by benpritchard** [desktop/desktop#16327]
### The feature request

I have about 20 repos in my repo list across multiple accounts. I work with about 8 of them regularly, and about 5 of them very regularly (switching among them multiple times per hour). 

The recent list stores the last 3 repos accessed, which means I'm frequently hunting amongst the other repos in my list which are grouped by account, so it's not a straightforward alphabetical lookup.

I can (and sometimes do) use the filter, but that's also slow and gets annoying to do frequently.

### Proposed solution

For my use-case, expanding the Recent list to 5 or 6 would be ok, but I understand this would impact everyone else who may not want up to 6 items at the top of their repo list. Plus it doesn't solve the order of repos changing each time in the recent list.

My requested solution for this is to allow users to pin repos to the top in whatever order they want.

Pinning repos would not change existing functionality for users (recents stay the same) but would allow users like me who switch among lots of repos to keep the most accessed at the top and in a predictable order.

This would remove a daily annoyance for me and benefit all users who frequently switch among more than 3 repos.

### Additional context

Thanks - keep up the good work!

**Comment by steveward** [comment]
Thanks for the feedback @benpritchard. I'll add this to https://github.com/desktop/desktop/issues/8183 where we are collecting feedback about this. When we revisited the repository list we chose not to implement this, but it may be something we consider again in the future. Thanks for letting us know you'd like to see it implemented.
