### ISSUE TITLE
I have a mistake with an excessively long filename.

### ISSUE THREAD

**Issue by rangerdirector** [desktop/desktop#16329]
### The problem

I use the tool to open https://github.com/spring-projects/spring-boot.git
I have a mistake with an excessively long filename.
I use the commond line to open git clone -c core.longpaths=true https://github.com/spring-projects/spring-boot.git
Errors disappear

### Release version

Version 3.2.0 (x64)

### Operating system

Windows 11 Pro

**Comment by steveward** [comment]
@rangerdirector it sounds like you were able to resolve this with `core.longpaths`, which is the recommendation if you are on Windows and have a path length over 260 characters. This is a known issue with Windows, so I'm going to close this out.
