### ISSUE TITLE
Looking for version other than one installed of JetBrains Fleet

### ISSUE THREAD

**Issue by valentinegb** [desktop/desktop#16323]
### The problem

When I select Repository > Open in Fleet, an error messages appears stating that it was unable to find the executable for Fleet at an invalid path to a version I no longer have installed, since I updated Fleet.

### Release version

3.2.1-beta1 (arm64)

### Operating system

macOS 13.3 Beta (22E5236f)

### Log files

[2023-03-15.desktop.beta.log](https://github.com/desktop/desktop/files/10981281/2023-03-15.desktop.beta.log)

### Screenshots

<img width="467" alt="Screenshot 2023-03-15 at 7 53 48 AM" src="https://user-images.githubusercontent.com/35977727/225349551-2808ddc0-6c62-43a1-a24b-9106cfbcd0f6.png">

### Additional context

I have Fleet 1.16.89 installed.
This problem seems to be resolved by restarting GitHub Desktop after updating Fleet.

**Comment by steveward** [comment]
Thanks for the report @valentinegb, I'm going to add this to https://github.com/desktop/desktop/issues/14666 where we are tracking making our editor integrations more robust.
