### ISSUE TITLE
Give the "Current branch" (dropdown) button more space

### ISSUE THREAD

**Issue by Jay-o-Way** [desktop/desktop#16342]
### The problem

Simple thing: The width of the dropdown button is constricted, trimming off many of the info.

### Release version

3.2.0

### Operating system

Windows 10

### Screenshots

![image](https://user-images.githubusercontent.com/65828559/226110005-2d2e0b55-d4bf-419d-bed0-cbcee81fe353.png)

**Comment by steveward** [comment]
Thanks for the feedback @Jay-o-Way, this is being tracked in https://github.com/desktop/desktop/issues/4569 so you can follow along there.
