### ISSUE TITLE
Why does pressing any key below "0 changed files" draws a white rectangle?

### ISSUE THREAD

**Issue by aybe** [desktop/desktop#16344]
### The problem

Get the software in the following state, i.e. 0 changed files, it will look like this:

![GitHubDesktop_3lhWDnkA4j](https://user-images.githubusercontent.com/1537591/226222006-40ad5783-ba28-42ec-9489-cec7ed411f2c.png)

Now with the mouse, click in the area below "0 changed files", then, press any key; see a white rectangle being drawn for no reason:

![GitHubDesktop_1o1dl9ueTA](https://user-images.githubusercontent.com/1537591/226222088-16041280-5846-43cc-9d3e-fa97e546994d.png)

### Release version

Version 3.2.0 (x64)

### Operating system

Windows 10

**Comment by tidy-dev** [comment]
@aybe Thanks for the report! This is intended functionality. The list is a focusable element. This is to support screen readers being able to focus it and read that there are no changes in the list.

**Comment by aybe** [comment]
Got it, thanks!
