### ISSUE TITLE
Please support VimR as external editor for GitHub Desktop

### ISSUE THREAD

**Issue by unicman** [desktop/desktop#16354]
### The feature request

https://github.com/qvacua/vimr is good wherein it has file explorer and markup and html built-in split windows which are user-friendly compared to typical VI. 

It doesn't show up for selection in GitHub Desktop.

### Proposed solution

Please add VimR for external editor for GitHub Desktop. Thanks.

### Additional context

Ref: https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md

**Comment by Bavuett** [comment]
cc @AndrewDMC

**Comment by Elmar-Wiese** [comment]
There is no one working on this one right now right?

**Comment by steveward** [comment]
@Elmar-Wiese I don't see any open PRs for this integration, so you're welcome to work on it!
