### ISSUE TITLE
Enhancement: Discard All Changes available from File Column Header

### ISSUE THREAD

**Issue by andrewtobin** [desktop/desktop#1635]
### Description

It would be natural if the context menu for applying changes to all files was available on the Changes column header rather than in the context menu of the files themselves.

I was looking to perform a discard all changes, but could not get a context menu on the column header, and found it by right-clicking the file itself.  It would feel more natural if the actions that applied to all files were on the header.

### Version

**GitHub Desktop version:** 0.5.5

**OS version:** Microsoft Windows [Version 10.0.14393]

### Steps to Reproduce

1. Create files in the repository directory
1. Right-click on the header for the changes - where it says "x files changed" - expected context not there.
1. Right-click on an individual file - context for all files in an individual file.

**Expected behaviour:** Right-click on Changes column header to show context for actions on all files.

**Actual behaviour:** Context for changes on all files is present on right-clicking an individual file instead.  No context menu on column header.

**Reproduces how often:** 100%

### Logs

N/A

#### Additional Information

N/A

**Comment by niik** [comment]
Thank you @andrewtobin. Yes, we should definitely do this. It's been on my list to create issues for this, see https://github.com/desktop/desktop/issues/1338

> - [ ] @niik to write up issue(s) for discarding changes

This all goes to show that if you procrastinate for long enough problems goes away by themselves :trollface:

I think we should move the discard all up to the header and also add it to the app menu for discoverability. We've also talked about a 'Discard selected files' option such that you can check a bunch of files and discard them but the terminology gets a little confusing there.
