### ISSUE TITLE
Clone: fatal: unable to access 'https://github.com/<username>/<repo-name>.git/': Send failure: Connection was reset

### ISSUE THREAD

**Issue by MarceloMansilla** [desktop/desktop#16359]
### The problem

I am not able to clone my repo by using Gitbash. Before I could do it but now I can not.

Here a screenshot from Bash

![imagen](https://user-images.githubusercontent.com/93406406/227133945-7230c7c2-8cf3-436d-8781-3c7f366f69cb.png)

Here is the result

$ git config --list --show-origin
file:C:/Program Files/Git/etc/gitconfig diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/etc/gitconfig filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/etc/gitconfig filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/etc/gitconfig filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/etc/gitconfig filter.lfs.required=true
file:C:/Program Files/Git/etc/gitconfig http.sslbackend=openssl
file:C:/Program Files/Git/etc/gitconfig http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/etc/gitconfig core.autocrlf=true
file:C:/Program Files/Git/etc/gitconfig core.fscache=true
file:C:/Program Files/Git/etc/gitconfig core.symlinks=false
file:C:/Program Files/Git/etc/gitconfig pull.rebase=false
file:C:/Program Files/Git/etc/gitconfig credential.helper=manager
file:C:/Program Files/Git/etc/gitconfig credential.https://dev.azure.com.usehttppath=true
file:C:/Program Files/Git/etc/gitconfig init.defaultbranch=master
file:C:/Users/MARCELO/.gitconfig        filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/MARCELO/.gitconfig        filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/MARCELO/.gitconfig        filter.lfs.process=git-lfs filter-process
file:C:/Users/MARCELO/.gitconfig        filter.lfs.required=true
file:C:/Users/MARCELO/.gitconfig        user.name=***************
file:C:/Users/MARCELO/.gitconfig        user.email=***************
file:C:/Users/MARCELO/.gitconfig        user.signingkey=***********
file:C:/Users/MARCELO/.gitconfig        http.sslverify=false
file:C:/Users/MARCELO/.gitconfig        http.sslbackend=openssl
file:C:/Users/MARCELO/.gitconfig        http.sslcainfo=C:\Program Files\Git\mingw64\ssl\cert.pem
file:C:/Users/MARCELO/.gitconfig        gpg.program=gpg
file:C:/Users/MARCELO/.gitconfig        tag.gpgsign=true
file:C:/Users/MARCELO/.gitconfig        commit.gpgsign=true

In case of having any idea about this issue, I will appreciate your help,

Thanks in advance

### Release version

Version 3.2.0 (x64)

### Operating system

Windows 10

**Comment by steveward** [comment]
@MarceloMansilla this issue tracker is for GitHub Desktop and not for support for Git from the command line, but normally this error is caused by a variety of possible connection issues. I would verify there isn't anything in your network interfering with your connection.
