### ISSUE TITLE
not able to login azuredevops code using my credentials

### ISSUE THREAD

**Issue by saideswar** [desktop/desktop#16361]
### The problem

I am not able to close the repo from azure devops repository thry url

### Release version

version 3.2.0 

### Operating system

windows

**Comment by steveward** [comment]
@saideswar you can follow [this guide](https://github.com/desktop/desktop/blob/development/docs/integrations/azure-devops.md) for steps on setting up Azure DevOps repositories in GitHub Desktop. Let me know if that does not work.
