### ISSUE TITLE
Pull to origin does not appear

### ISSUE THREAD

**Issue by Pdalla** [desktop/desktop#16363]
### The problem

[2023-03-22.desktop.production.log](https://github.com/desktop/desktop/files/11052491/2023-03-22.desktop.production.log)
When committing the Fetch button does not change to Push

### Release version

3.2.0 

### Operating system

Windows 10

**Comment by steveward** [comment]
@Pdalla thanks for the issue. Can you share a screenshot of what you are seeing in GitHub Desktop?

**Comment by Pdalla** [comment]
[image: image.png]

Guys, as you can see, the Fetch appears when it should change to "push"
when doing the fetch it changes to push but before doing the commit it
already changes to "push" alone. In this image I already committed the
changes and even so it did not change from "fecth" to "push"

Em qui., 23 de mar. de 2023 às 17:23, Steve Ward ***@***.***>
escreveu:

**Comment by steveward** [comment]
Unfortunately your screenshot did not make it through since screenshots can not be sent via email reply. Can you upload it directly?

**Comment by Pdalla** [comment]
![image](https://user-images.githubusercontent.com/83130505/227634752-f030a121-df79-4946-afd1-7ad17ac4be88.png)

**Comment by steveward** [comment]
@Pdalla that screenshot shows an uncommitted change -- when you commit it are you not seeing the `Push` option?

**Comment by Pdalla** [comment]
Correct.

Em seg., 27 de mar. de 2023 às 15:55, Steve Ward ***@***.***>
escreveu:

**Comment by sergiou87** [comment]
Could you commit the changes, switch to the `History` tab, and then take a screenshot?

Thank you!
