### ISSUE TITLE
建议增加树形结构展示，已暂存和未暂存分开显示。

### ISSUE THREAD

**Issue by hhun** [desktop/desktop#16364]
### The feature request

建议增加**树形结构展示**，**已暂存**和**未暂存**分开显示。

### Proposed solution

建议增加**树形结构展示**，**已暂存**和**未暂存**分开显示。

### Additional context

![文件夹树形结构](https://user-images.githubusercontent.com/19625243/227250911-c5b097ec-6657-4c15-b974-e47a15ce49f7.jpeg)

_No response_

**Comment by tidy-dev** [comment]
Google translate:
**Title:** It is recommended to add a tree structure display, which is displayed separately from the staged and unstaged
**Feature Request:** It is recommended to add a tree structure display, and the temporary storage and non-temporary storage are displayed separately.
**Proposed Solution:** It is recommended to add a tree structure display, and the temporary storage and non-temporary storage are displayed separately.

**Comment by tidy-dev** [comment]
Thanks for the issue @hhun, I'm going to add this to https://github.com/desktop/desktop/issues/2417 where we are collecting feedback about this feature.
