### ISSUE TITLE
Preview/Create Pull Request button infrequently greyed out

### ISSUE THREAD

**Issue by Jiralite** [desktop/desktop#16368]
### The problem

Ever since 3.2.0, this button (and its other variant) are infrequently greyed out. I have found the following workarounds to resolve this issue:

1. Clicking on the dropdown and selecting an option no longer greys it out.
2. Opening developer tools and refreshing GitHub Desktop.

I switched to the beta release to see if this issue persists. It does.

I had a quick look through the logs, but nothing seems to be of interest.

### Release version

Version 3.2.1-beta1 (arm64)

### Operating system

macOS Ventura 13.2.1

### Steps to reproduce the behavior

1. Create a branch
2. Add some commits
3. [Unknown step]
4. Publish it

I also encountered this by switching to a branch that does not yet have a pull request.

### Log files

[2023-03-23.desktop.beta.log](https://github.com/desktop/desktop/files/11054972/2023-03-23.desktop.beta.log)

### Screenshots

<img width="624" alt="image" src="https://user-images.githubusercontent.com/33201955/227320686-5b3ab319-4f85-4f76-b8e1-b98289d53b7d.png">

**Comment by tidy-dev** [comment]
@jiralite Thanks for the report! I have not been able to reproduce this yet. But, it sounds like an intermittent bug, so I am going to add a bug to it. If you find any clear repro steps, please let us know. I have a feeling some state variable is not reliably up to date on initial render.

**Comment by tidy-dev** [comment]
And as I say that.. I get it to happen. :D 
This is convoluted and maybe there is simpler repro step:
1. Have a published branch 
2. In Changes view, see that the preview pull request button is enabled
3. Go to history, revert the last commit
4. Go to changes view, hit undo button
5. discard all undone changes

The preview pull request will be disabled; 

Anything that incurs a rerender of the no changes area fixes it. Examples:
1. going to history and back to changes.
2. Toggling the create/pull request review dropdown (as mentioned by user)
3. Switching Repos
4. Switching Branches

Hunch is that something is changing that is not causing an `emitUpdate` to fire.
