### ISSUE TITLE
Cherry-picking into a branch with a failing Git hook fails with no feedback

### ISSUE THREAD

**Issue by Jiralite** [desktop/desktop#16369]
### The problem

When cherry-picking a commit into a branch **with conflicts** that fails Git hooks (in my case, [husky](https://github.com/typicode/husky)), GitHub Desktop switches back to the prior branch with no changes (or errors).

I have uploaded a video for additional context. If you watch this _very closely and very carefully_, you can see for a split second there _is_ an error modal that dismisses immediately.

### Release version

3.2.1-beta2 (arm64)

### Operating system

macOS Ventura 13.2.1

### Steps to reproduce the behavior

Ensure you have two branches where the target branch utilises husky.

1. Cherry-pick a commit from the source branch to the target branch
2. There must be a conflict. Resolve it
3. Ensure husky fails (hardcode `exit 1`)

### Log files

[2023-03-23.desktop.beta.log](https://github.com/desktop/desktop/files/11055513/2023-03-23.desktop.beta.log)

### Additional context

https://user-images.githubusercontent.com/33201955/227340289-6eb8047b-fd39-4290-b810-d49aec15d6c7.mp4

**Comment by steveward** [comment]
Thanks for the issue @Jiralite, I'm going to group this into https://github.com/desktop/desktop/issues/15286.
