### ISSUE TITLE
Group and Rearrange My Repositories

### ISSUE THREAD

**Issue by maarxx** [desktop/desktop#16365]
### The feature request

I have a lot of repositories within my Github Desktop and they fit into several different thematic groupings. I am often quickly switching between repositories within the same thematic grouping. But right now they only group based on Owner/Organization, and then alphabetically.

### Proposed solution

In the repository listing, it would be really cool if I could manually create categories (like Owner/Organization) and put repositories in different categories and rearrange the order they appear within the categories.

### Additional context

![githubDesktopCategories](https://user-images.githubusercontent.com/7416299/227268735-be0716d2-98ad-4210-a28f-b5a8d3880418.png)

**Comment by steveward** [comment]
Thanks for the feedback @maarxx. See [this comment](https://github.com/desktop/desktop/issues/10201#issuecomment-658693653) for more information about why we do not have plans to implement repository grouping at this time. 

One workaround is to use the repository alias feature and then use that to filter by a specific alias prefix. I hope that helps.
