### ISSUE TITLE
Certificate mismatch

### ISSUE THREAD

**Issue by sybrew** [desktop/desktop#16374]
### The problem

Launching GitHub Desktop v3.2.0 (x64), I'm greeted with this message:

![image](https://user-images.githubusercontent.com/7662236/227637176-0ffdba31-3710-40cb-90df-75d1331277b4.png)

### Release version

3.2.0

### Operating system

Windows 10 Pro 22H2

### Steps to reproduce the behavior

1. Open GitHub Desktop.
2. That's it.

**Comment by sybrew** [comment]
This is likely unrelated but to clear my mind, at https://desktop.github.com/, the "Help" link leads to another site with a certificate mismatch:
![image](https://user-images.githubusercontent.com/7662236/227637607-59d1e78a-8e4e-480a-844f-33545f512702.png)

**Comment by kmanadkat** [comment]
Facing Same issue
Version 3.2.1-beta2 (arm64)

**Comment by kskatserra** [comment]
![74B1E220-95B8-4E61-8DA3-C2EA686290E2](https://user-images.githubusercontent.com/128838082/227650884-a5e4705a-11d4-428e-ac60-66bb6c3af7be.png)

**Comment by sergiou87** [comment]
If this is happening system-wide, I'd recommend to reboot or try again a few hours/days later. Sorry!
