### ISSUE TITLE
Github desktop is not opening

### ISSUE THREAD

**Issue by valarpirai** [desktop/desktop#1638]
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

[Description of the issue]

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** [version here]

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behaviour:** [What you expected to happen]

**Actual behaviour:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by niik** [comment]
@valarpirai I'm sorry to hear you're having problems launching the app but without any details about the problem we're not going to be able to help you out. Please open an issue and fill out the issue template with the information it asks for so that we can debug this issue with you.

**Comment by wangtoday** [comment]
I have a same cannot open problem today. 

I use a windows 10.

When clicking the GitHub icon, the app opened, but it keeps minimum and sticks on the taskbar. The main window does not pop out but with a window+tab, you can see it was there.

I tried to uninstall GitHub and install it back, but not work. Finally, I find the way to solve this problem.

see the image below. 

![wahh](https://user-images.githubusercontent.com/18587068/31479387-8e9adede-af62-11e7-82c2-ad6d345b0f9e.png)

Hope will help someone, who use Google "Github cannot open" and go here.

**Comment by shiftkey** [comment]
@wangtoday are you running multiple monitors? This might be related to #2107.

**Comment by wangtoday** [comment]
@shiftkey Thanks,

Yes, after changing to Maximized to run the app, now everything is all good.

But this really confused me when first happened.  :)

**Comment by Kamaltejveerapaneni** [comment]
I am a windows user.Got this when  I tried to open Github desktop.

Git could not be found at the expected path: 'C:\Users\admin\AppData\Local\GitHubDesktop\app-1.0.10\resources\app\git\cmd\git.exe'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.

When I tried to reopen, currently I am getting it like this
![capture](https://user-images.githubusercontent.com/31327193/33865190-383481d4-deb6-11e7-908c-32e47d0eddef.PNG)

Need help regarding this

**Comment by shiftkey** [comment]
@Kamaltejveerapaneni please open a fresh issue and fill out the provided template

**Comment by Kamaltejveerapaneni** [comment]
Its working fine when I reinstalled it

**Comment by LocoLeo** [comment]
OS: Mac OS X Sierra
Downloaded app: Feb 18, 2018

Previously had already installed GitHub Desktop version.  it wouldn't function as well.
Also had  GitHub for Mac.


I had the same issue.  I would open the app and would get a blank screen within the app.
Logs weren't helpful.

I uninstalled all apps from Mac, dropping into trash can.
Went to ~/Libarary/Application Support/

and rm -r (completely removed) GitHub for Desktop
renamved GitHub for Mac (adding backup in name - GitHub for Mac_backup) because i didn't want to remove that
and then reinstalled app.

This fixed my problem.

**Comment by ifcquery** [comment]
I have the same problem with github desktop on windows 10. After updating to 2.0.1 one week ago, github does not start any more... does anyone have solution that works?

**Comment by shiftkey** [comment]
@ifcquery if you would like us to troubleshoot this issue please open a fresh issue and fill out the bug report template
