### ISSUE TITLE
Re-open #2620

### ISSUE THREAD

**Issue by JVimes** [desktop/desktop#16384]
### The feature request

#2620 was closed with "if we get a lot of feedback around this we'll reopen" and it has gotten a lot of positive feedback since then. Can we at least re-open it? 

### Proposed solution

Re-open #2620

**Comment by sergiou87** [comment]
Hey! I'm revisiting this with the team. We might not get back to you in the next few days because we're a bit busy, but we'll try to make a decision about this soon. Meanwhile, I'll close this 😅  Sorry!
