### ISSUE TITLE
Desktop misidentifying Default Branch

### ISSUE THREAD

**Issue by thinkyhead** [desktop/desktop#16394]
### The problem

Desktop is mistaking a checked-out branch from a fork (which is from a closed checked-out PR) as the default branch. This checked-out branch has the same name (in the fork) as the origin/upstream default branch, which might be confusing the code that identifies the default branch.

### Release version

3.2.0

### Operating system

macOS

### Steps to reproduce the behavior

It's not clear whether any particular procedure will cause this to manifest, but you can try this:

- Check out a remote branch from a fork that is the same branch-name as your default, giving it a name that comes alphabetically before the name of your default branch.
  (e.g., `git checkout theremote/main -b aardvark_from_theremote`)
- Use Desktop as usual. Quit it, restart it, etc.
- Possibly, Desktop will begin to misidentify that branch as the default.

### Log files

I checked the logs, and there is nothing useful.

### Screenshots

![image](https://user-images.githubusercontent.com/698003/227831640-cbffc8c1-a247-4ca2-a195-446a352d2fc8.png)

The correct default branch for my project's upstream and origin repos is `bugfix-2.1.x`. The `git branch -v` command identifies the branch as `bf2_quiret_refactor_PR_24911 ... [quiret/bugfix-2.1.x: ...]`.

It appears that Desktop has a glitch in identifying the correct default branch (`upstream/bugfix-2.1.x`) — probably because "bf2_" comes alphabetically _before_ "bugfix..." and the loop scanning for the default branch is either assuming that `quiret` is an alias for `upstream` (which it is not) or it's just picking the first `repo/bugfix-2.1.x` it finds in the `git branch -v` output and exiting without checking further down the list for the `upstream/...` variant.

**Comment by thinkyhead** [comment]
Indeed! Renaming the branch so that it falls alphabetically after "bugfix" prevents Desktop from identifying it as the default branch.

**Comment by sergiou87** [comment]
Does it make a difference if you switch the Fork Behavior in the `Repository -> Repository Settings…` dialog?
