### ISSUE TITLE
Optionally show error messages when update failures occur

### ISSUE THREAD

**Issue by jmullaney14** [desktop/desktop#16399]
### The feature request

Create a new option in Options->Prompts to enable or disable popup messages when an update occurs. My company network is disconnected from the internet so the improvement discussed in 3.1.5 release notes (#15530) forces an error message every time we open the app.  Luckily, deleting Update.exe makes the probably go away.  Possible duplicate of #3410.

### Proposed solution

Some users do not prefer or need an error message when an update failure occurs. Evidenced by the fact that this was not a mandatory popup until version 3.1.5. Creating an option to opt-out of error message in Options->Prompts seems to make sense.

### Additional context

Popup title is "Error", message is "Checking for updates failed".

**Comment by sergiou87** [comment]
Hey @jmullaney14 ! 👋 

Sorry about that. This got fixed in #16306 and that fix is available in the latest beta. We intend to make a non-beta release at some point next week, and that will include the fix too.
