### ISSUE TITLE
The purpose of File menu is vague

### ISSUE THREAD

**Issue by SaschaNaz** [desktop/desktop#1639]
The File menu in the new client is not really about "files". The current content is:

```
New repository
New branch
---
Add local repository
Clone repository
---
Options
Exit
```

It's really about repositories and branches, which respectively have their own menu 'Repository' and 'Branch'.

I think something should be done here, the File menu may lose everything except Options and Exit items.

**Comment by niik** [comment]
Folding this into https://github.com/desktop/desktop/issues/1575
