### ISSUE TITLE
Custom number of "Recent Repositories"

### ISSUE THREAD

**Issue by JakubSteplowski** [desktop/desktop#16402]
### The feature request

In the current version you can only see the 3 most recently used repositories.
In a real world scenario the list of total repositories can be double or triple digit, with a double digit number of recently used.
Please make the software more handy to use, don't force the user to search manually in the list for no reason.

### Proposed solution

Allow the user to change the default value of "3" for the amount of recent repositories in the list.
Add a new option in the "Advanced" section.

You discared in the past the possibility to mark repos as favorites or pin them to top (_I'm still waiting for a valid reason_).
So, instead of adding a new feature, make the currently available one more customizable to make everyone happy.

Thanks in advance for your understanding.

**Comment by sergiou87** [comment]
Hey! Thank you for your suggestion ❤️ 

We're trying to avoid adding more and more settings unless there is no other option. But I personally think changing the way those repos get to the top (pinning them) makes more sense than having a setting to increase how many recent repos are there. For now, however, we have no plans on changing the repository list, as we have other priorities and this is a small team with very limited resources 😢 

I'm sorry, I know this is not the answer you were hoping for, but it's all we have 😓
