### ISSUE TITLE
GitHub Desktop : The remote disconnected. Check your Internet connection and try again.

### ISSUE THREAD

**Issue by ChengxuHe** [desktop/desktop#16405]
### The problem

I keep getting a message of **"The remote disconnected. Check your Internet connection and try again."** after pushing. 

### Release version

Version 3.2.0 (x64)

### Operating system

Windows 10/11

### Log files

$ git push
Enumerating objects: 999, done.
Counting objects: 100% (999/999), done.
Delta compression using up to 16 threads
Compressing objects: 100% (992/992), done.
error: unable to rewind rpc post data - try increasing http.postBuffer
error: RPC failed; curl 65 seek callback returned error 1
send-pack: unexpected disconnect while reading sideband packet
Writing objects: 100% (994/994), 5.80 GiB | 17.64 MiB/s, done.
Total 994 (delta 97), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

### Screenshots

![微信图片_20230328180546](https://user-images.githubusercontent.com/99346921/228315295-d05d7589-ef6e-47af-a50e-0e66d49205f8.png)

**Comment by steveward** [comment]
Thanks for the issue. Here's the error that's causing the push failure:

```
error: unable to rewind rpc post data - try increasing http.postBuffer
error: RPC failed; curl 65 seek callback returned error 1
```

You can try increasing the http.postbuffer using the following command:

`git config --global http.postBuffer 2097152000`

Let me know if that helps.

**Comment by ChengxuHe** [comment]
> Thanks for the issue. Here's the error that's causing the push failure:
> 
> ```
> error: unable to rewind rpc post data - try increasing http.postBuffer
> error: RPC failed; curl 65 seek callback returned error 1
> ```
> 
> You can try increasing the http.postbuffer using the following command:
> 
> `git config --global http.postBuffer 2097152000`
> 
> Let me know if that helps.

I tried, but its still not working for me. My internet is decent and I am using cable connection so I dont think it is a connection issue.

![屏幕截图 2023-03-28 191356](https://user-images.githubusercontent.com/99346921/228330390-cd35bfc6-1d83-4543-8267-05f0302f5a95.jpg)

**Comment by sergiou87** [comment]
@mrwillhe are you behind a proxy or do you have any kind of firewall or antivirus enabled? If so, could you try disabling them temporarily?

Are you connected through a VPN?

**Comment by ChengxuHe** [comment]
> @mrwillhe are you behind a proxy or do you have any kind of firewall or antivirus enabled? If so, could you try disabling them temporarily?
> 
> 
> 
> Are you connected through a VPN?

No I am not behind a proxy and I don't have anyway firewall or antivirus enabled (only the protection from Windows itself). I am not connecting via a VPN.

**Comment by motebfz** [comment]
--Sent from Yandex Mail for mobile29.03.2023, 15:11, "mrwillhe" ***@***.***>:

@mrwillhe are you behind a proxy or do you have any kind of firewall or antivirus enabled? If so, could you try disabling them temporarily?
Are you connected through a VPN?

No I am not behind a proxy and I don't have anyway firewall or antivirus enabled (only the protection from Windows itself). I am not connecting via a VPN.

**Comment by datasciencesystems** [comment]
I have the same problem. Yesterday it worked for the same repository. But today it did not. HELP!!!!!!!!!!!!

**Comment by DazzaJay** [comment]
Same issue here, Except I'm getting the issue after about 1GB sent (50%) uploaded.
No VPN, Connected to Fiber Optic, and nothing else on my network loses connection at the same time.
Changing the Buffer had no effect.

**Comment by StefanosNtouvlis** [comment]
Same issue, saw in another thread that it has to do with the file size.

**Comment by KirkGamesLLC** [comment]
same issue

**Comment by eirikhalv** [comment]
Having the same issue here.

**Comment by KirkGamesLLC** [comment]
The repo was setup to HTTP instead of SSH, so I now use SSH instead of HTTP. Simply changing the remote repo from http... to git@github.com:OrganizationName/RepoName.git
to use my already installed SSH setup fixed the issue for me.

**Comment by DazzaJay** [comment]
> The repo was setup to HTTP instead of SSH, so I now use SSH instead of HTTP. Simply changing the remote repo from http... to [git@github.com](mailto:git@github.com):OrganizationName/RepoName.git to use my already installed SSH setup fixed the issue for me.

Where do I make this change? In the settings menu for github desktop?

**Comment by owlboy** [comment]
`git config --global http.postBuffer 2097152000`

This was suggested earlier, and worked in my case using a standard https connection.

@DazzaJay You can set this in `Repository` -> `Repository Settings…` -> `Remote` -> `Primary remote repository (origin)`.
But you will need your SSH keys setup on your system for GitHub. That part I can't help with.

**Comment by iamnikitakhare** [comment]
You can increase the number means 2099152000
In place of 2097152000 @eirikhalv

**Comment by xor6502** [comment]
Hit this same issue today, fresh Fedora 40 install. New GitHub repo and copied files across, commit and push generated the same error.

I wasn't sure if this would apply as GitHub Desktop is a flatpak but I performed the quoted fix from @steveward and it fixed the issue up.

Thanks @steveward 

> Thanks for the issue. Here's the error that's causing the push failure:
> 
> ```
> error: unable to rewind rpc post data - try increasing http.postBuffer
> error: RPC failed; curl 65 seek callback returned error 1
> ```
> 
> You can try increasing the http.postbuffer using the following command:
> 
> `git config --global http.postBuffer 2097152000`
> 
> Let me know if that helps.

**Comment by soniamun** [comment]
> Thanks for the issue. Here's the error that's causing the push failure:
> 
> ```
> error: unable to rewind rpc post data - try increasing http.postBuffer
> error: RPC failed; curl 65 seek callback returned error 1
> ```
> 
> You can try increasing the http.postbuffer using the following command:
> 
> `git config --global http.postBuffer 2097152000`
> 
> Let me know if that helps.

thank you! this helped!

**Comment by shortcurb** [comment]
> The repo was setup to HTTP instead of SSH, so I now use SSH instead of HTTP. Simply changing the remote repo from http... to [git@github.com](mailto:git@github.com):OrganizationName/RepoName.git to use my already installed SSH setup fixed the issue for me.

I just ran into this problem and following these instructions to set my repo to use SSH, and then also adding my SSH key to github, worked for me.

**Comment by JAMvlc** [comment]
> You can increase the number means 2099152000 In place of 2097152000 @eirikhalv

Thanks Nikita!

**Comment by sgtkoolaid** [comment]
it does this for me. i tried the buffer part and it does it no matter what.

**Comment by NdegwaJulius** [comment]
> `git config --global http.postBuffer 2097152000`
> 
> This was suggested earlier, and worked in my case using a standard https connection.
> 
> @DazzaJay You can set this in `Repository` -> `Repository Settings…` -> `Remote` -> `Primary remote repository (origin)`. But you will need your SSH keys setup on your system for GitHub. That part I can't help with.



> Thanks for the issue. Here's the error that's causing the push failure:
> 
> ```
> error: unable to rewind rpc post data - try increasing http.postBuffer
> error: RPC failed; curl 65 seek callback returned error 1
> ```
> 
> You can try increasing the http.postbuffer using the following command:
> 
> `git config --global http.postBuffer 2097152000`
> 
> Let me know if that helps.

This worked for me too 2024!

**Comment by AlvaretA** [comment]
> Thanks for the issue. Here's the error that's causing the push failure:
> 
> ```
> error: unable to rewind rpc post data - try increasing http.postBuffer
> error: RPC failed; curl 65 seek callback returned error 1
> ```
> 
> You can try increasing the http.postbuffer using the following command:
> 
> `git config --global http.postBuffer 2097152000`
> 
> Let me know if that helps.

Worked for me, Sept 2024

**Comment by UneebKari** [comment]
> Thanks for the issue. Here's the error that's causing the push failure:
> 
> ```
> error: unable to rewind rpc post data - try increasing http.postBuffer
> error: RPC failed; curl 65 seek callback returned error 1
> ```
> 
> You can try increasing the http.postbuffer using the following command:
> 
> `git config --global http.postBuffer 2097152000`
> 
> Let me know if that helps.

Thanks man, it helps

**Comment by confid-d** [comment]
Changed from a WIFI connection to better (WIRED) connection and was able to make this work.

I was getting:

Writing objects: 100% (30/30), 129.72 MiB | 12.78 MiB/s
Writing objects: 100% (30/30), 138.19 MiB | 11.28 MiB/s, done.
Total 30 (delta 9), reused 0 (delta 0), pack-reused 0 (from 0)
error: RPC failed; curl 55 LibreSSL SSL_read: LibreSSL/3.3.6: error:1404C3FC:SSL routines:ST_OK:sslv3 alert bad record mac, errno 0
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date

(The error was parsed as 5: The remote disconnected. Check your Internet connection and try again.)

I tried changing buffer size as suggested.  All of my failures were relying on a WIFI connection.  When I changed to a WIRED connection it worked just fine NO FAILURE.  Guessing something was timing out ...

**Comment by milk-powderr** [comment]
> Thanks for the issue. Here's the error that's causing the push failure:
> 
> ```
> error: unable to rewind rpc post data - try increasing http.postBuffer
> error: RPC failed; curl 65 seek callback returned error 1
> ```
> 
> You can try increasing the http.postbuffer using the following command:
> 
> `git config --global http.postBuffer 2097152000`
> 
> Let me know if that helps.

this worked for me, thank you

**Comment by marllonramoss** [comment]
> Thanks for the issue. Here's the error that's causing the push failure:
> 
> ```
> error: unable to rewind rpc post data - try increasing http.postBuffer
> error: RPC failed; curl 65 seek callback returned error 1
> ```
> 
> You can try increasing the http.postbuffer using the following command:
> 
> `git config --global http.postBuffer 2097152000`
> 
> Let me know if that helps.

Worked for me too on my Mac, thanks!

**Comment by shawshubham** [comment]
I have been trying to push the Hugo website but keep on getting the same error. I have tried multiple ways to fix it, one or the other will fix the issue as per your root cause: 

**1) First of all try switching your internet connection:** 
Given you might have superfast fiber connection I am having 900mbps plan, still faced the problem. This was the root cause for me. Switch to different wifi or mobile hotspot and try pushing to git, check whether it works for you as there can be packet lose or other network related issue.


**2) Changing the buffer size, as shown below this might solve the problem for some:**
Increasing buffer size to 500MB:
```bash
git config --global http.postBuffer 524288000
```
Also, executed the below command:
```bash
git config --global http.lowSpeedLimit 0
git config --global http.lowSpeedTime 999999
```

**3) Switching to SSH from HTTPS**
Step 1:  Generate a new SSH Key
```
ssh-keygen -t ed25519 -C "your_email@example.com"
```
Replace "your_email@example.com" with your actual GitHub email.
Then, when prompted:
	•	Press Enter to accept the default file location:
(It will save to ~/.ssh/id_ed25519)
	•	You can skip setting a passphrase unless you want extra protection

You should see something like:
```
Your identification has been saved in /Users/yourname/.ssh/id_ed25519
```

Step 2: Add your public key to GitHub
```
cat ~/.ssh/id_ed25519.pub
```
Copy the entire output — it looks like:
```
ssh-ed25519 AAAAC3... your_email@example.com
```
Now go to:
👉 https://github.com/settings/keys
	•	Click “New SSH key”
	•	Paste the copied key
	•	Give it a name (e.g., “MacBook Pro”)
	•	Click “Add SSH key”

Step 3: Tell git to use SSH
```
cd path/to/your-project
git remote set-url origin git@github.com:YOUR_USERNAME/your-project.git
```
Confirm via:
```
git remote -v
```
You should see now:
```
origin  git@github.com:YOUR_USERNAME/your-project.git (fetch)
origin  git@github.com:YOUR_USERNAME/your-project.git (push)
```

Step 4: Push your code via SSH: 
```
git push -u origin main
```

**Comment by mcNuggets1** [comment]
Still happens
