### ISSUE TITLE
User image missing in GitHub Enterprise connections

### ISSUE THREAD

**Issue by IdanAdar** [desktop/desktop#1640]
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

The user profile image is missing, when connecte to a GitHub Enterprise instance.

### Version

**GitHub Desktop version:** 0.5.5

The operating system you are running on may also help with reproducing the
issue:

**OS version:** macOS 10.12.5

### Steps to Reproduce

1. Add a GitHub Enterprise connection

**Expected behaviour:** To see the user profile image

**Actual behaviour:** User profile image is missing

<img width="122" alt="screen shot 2017-05-19 at 8 05 47" src="https://cloud.githubusercontent.com/assets/7255583/26234033/5abbba2c-3c6a-11e7-97b9-2cde706a892c.png">

**Reproduces how often:** 100%

**Comment by niik** [comment]
Closing this in favor of #821
