### ISSUE TITLE
GitHub Desktop not working, Command line working

### ISSUE THREAD

**Issue by joembedded** [desktop/desktop#16404]
### The problem

Without any reason GitHub Desktop suddenly does not work any more for some of my repos, but for others it works.
Also command line is working on all repos... How can I fix this error? I have no idea any more. Re-installation of GitHub Desktop did not help. Thanks! Jo

```
2023-03-28T15:52:18.239Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand master` exited with an unexpected code: 128.
stderr:
@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:uNiVztksCsDhcc0u9e8BujQXVUpKZIDTMczCvj3tD2s.
Please contact your system administrator.
Add correct host key in C:\\Users\\jwick/.ssh/known_hosts to get rid of this message.
Offending RSA key in C:\\Users\\jwick/.ssh/known_hosts:1
Host key for github.com has changed and you have requested strict checking.
Host key verification failed.
fatal: Could not read from remote repository.

```

### Release version

3.2.0

### Operating system

Win11

**Comment by steveward** [comment]
@joembedded this issue is due to GitHub's public key changing. See [this blog post.](https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/). There are steps in that blog post for how you can resolve this, but let me know if you have any questions.
