### ISSUE TITLE
Connecting to enterprise repo via oauth in browser 404

### ISSUE THREAD

**Issue by 31337-4554551n** [desktop/desktop#16418]
### The problem

Attempting to connect to an enterprise git repo via oauth gives a 404 error in the browser.
This was not the case with the windows client I set up a few months back to the same repo.

### Release version

3.1.6 and 3.1.7-linux1and 2.8.1-linux1

### Operating system

Pop os

### Steps to reproduce the behavior

Open git desktop (flatpak or deb)
Connect to enterprise repo
enter repo
Open in browser
get 404 error

**Comment by steveward** [comment]
@31337-4554551n GitHub Desktop is not officially supported on Linux, and at this time the Linux fork does not support Enterprise authentication. See https://github.com/shiftkey/desktop/issues/72.

**Comment by 31337-4554551n** [comment]
> @31337-4554551n GitHub Desktop is not officially supported on Linux, and at this time the Linux fork does not support Enterprise authentication. See [shiftkey#72](https://github.com/shiftkey/desktop/issues/72).

I'm sorry, I'm too dumb to understand that thread.
Is the verdict "doesn't work-won't fix", and there's no work around?
