### ISSUE TITLE
Merge error since 28/3/2023

### ISSUE THREAD

**Issue by Gyflux-Deng** [desktop/desktop#16411]
### The problem

Hello, I have encountered a merge error with my teammate since 28/3/2023 on my project GST8% Gongfu Golf. We have tried to merge branches after 1 person committed and we edited different stuff, but we old codes remain without the updated code. we deleted commented code on 1 side it still remains there the moment we merge. even the git hub desktop does not complain about merge conflicts / complain. i cannot reproduce the bug, but it happens 2 time since 28/3/2023

### Release version

Version 3.2.0 (x64)

### Operating system

Windows 11 

### Log files

[2023-03-28.desktop.production.log](https://github.com/desktop/desktop/files/11097406/2023-03-28.desktop.production.log)
[2023-03-29.desktop.production.log](https://github.com/desktop/desktop/files/11097407/2023-03-29.desktop.production.log)

### Additional context

Thanks for helping. Have the pleasure of working in GitHub.

**Comment by sergiou87** [comment]
Thanks for your report and kind words! ❤️ 

I wonder if either the app or the repo were in an inconsistent state. I cannot reproduce this problem either 😕  If it happens again, please take screenshots and new logs and let us know. Sorry I can't be of more help!
