### ISSUE TITLE
Help me out

### ISSUE THREAD

**Issue by MPG360** [desktop/desktop#16419]
### The problem

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: -

### Release version

Version 3.2.0 (x64)

### Operating system

windows 11

**Comment by steveward** [comment]
@MPG360 it looks like you seeking support for a different project hosted on GitHub. This issue tracker is for GitHub Desktop -- if you have any specific questions about that application please let us know.

**Comment by MPG360** [comment]
Okay bro thank you so much for your reply, please I am trying to install
and run avatarify on my computer and use it on zoom. So I have downloaded
anaconda according to the instructions to download the application. Please
I will be glad if you could be of help to me. Thank you
