### ISSUE TITLE
Apply diff

### ISSUE THREAD

**Issue by biast12** [desktop/desktop#16417]
### The feature request

The feature request is about both being able to export .diff files and being about to import .diff files and add the code

### Proposed solution

makes it so much easier to share versions with other users on a branche without needing to push it to an actual branche, like imagine a project were not everyone got push access, having being able to just send a .diff file if there's something small

overall do i think it would be a really good and useful feature that a lot could use, even without realizing it + the app should already have the tools to just apply the differens, the command line tool does at least

### Additional context

https://everythingdevops.dev/how-to-create-and-apply-a-git-patch-with-git-diff-and-git-apply-commands/

**Comment by steveward** [comment]
Thanks for the issue @biast12. The ability to create patch files likely isn't something that we would implement in GitHub Desktop, as our focus is on the pull request development flow (see [GitHub Flow](https://docs.github.com/en/get-started/quickstart/github-flow)). If you need to create patch files you can quickly jump into the command line to accomplish that. I'm going to close this out, but thanks for using GitHub Desktop.

**Comment by biast12** [comment]
that's sad to see, especially because it would help the flow for some, i mean i have encountered a good handful of times it would be super useful already
