### ISSUE TITLE
Cannot Push Since RSA key Change

### ISSUE THREAD

**Issue by KennethEvans** [desktop/desktop#16423]
### The problem

I get an error trying to push through GitHub Desktop even after changing my known_hosts file as described in the documentation. Other programs such as GitExtensions and command-line git work ok.  In particular this works:

```
$  ssh -T git@github.com
Hi KennethEvans! You've successfully authenticated, but GitHub does not provide shell access.

```
and

```
$ ssh-keygen -lf .ssh/known_hosts
3072 SHA256:uNiVztksCsDhcc0u9e8BujQXVUpKZIDTMczCvj3tD2s github.com (RSA)
...

```
However GitHub Desktop still gets the error dialog shown below.

### Release version

Version 3.2.0 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Open GitHub Desktop and do "Push github at the top.

### Log files

[2023-03-30.desktop.production.log](https://github.com/desktop/desktop/files/11113935/2023-03-30.desktop.production.log)

### Screenshots

![Screenshot-GitHubDesktop-23-03-30_12-37](https://user-images.githubusercontent.com/19721186/228906213-b236d000-7d37-4054-ad7b-27d52209f0a2.png)

**Comment by steveward** [comment]
@KennethEvans thanks for the issue. Can you go to `File` > `Options` > `Advanced` and see if the option to use openSSH is selected under `SSH`?

**Comment by KennethEvans** [comment]
Yes, Use system OpenSSH is checked.

**Comment by steveward** [comment]
@KennethEvans Have you restarted GitHub Desktop since updating the key?

**Comment by battsteam** [comment]
No and how do I find out my stampOn Mon, Apr 10, 2023 at 1:16 PM Steve Ward ***@***.***> wrote:
@KennethEvans Have you restarted GitHub Desktop since updating the key?

**Comment by KennethEvans** [comment]
@Steve Ward: Yes, I have restarted it many times. It sees commits but can cannot push. Fortunately Git Extensions works, and I use it. Command line also works. Github Desktop does  not.

**Comment by KennethEvans** [comment]
This issue continues. It makes GitHub Desktop useless. No one is even assigned to it.

**Comment by steveward** [comment]
Apologies @KennethEvans, I was out of office. Can you try unchecking the "Use system OpenSSH" I mentioned above? There have been a few other reports of SSH issues around having that enabled.

**Comment by KennethEvans** [comment]
I tried that. Now it just keeps showing the wait cursor and nothing happens. See screenshot.

For this project it says it is trying to push a commit as well as a tag. There should be no tag. I added a tag with Git Extensions today, but it is pushed. (I used it to make a release.) I did **not** enter the tag in  GitHub Desktop.

![Screenshot-chrome-23-05-01_23-18](https://user-images.githubusercontent.com/19721186/235572624-0e7aac4a-9985-4c0b-a593-c7819dd15587.png)

**Comment by KennethEvans** [comment]
I fixed it. I deleted all the entries with github.com or an IP address from my known hosts file. I turned Use system OpenSSH back on. On trying a fetch it added a new sha2 key, which seems to be what it is using. It seems to be working again.

Clearly GitHub Desktop uses the known_hosts files differently from other applications.

Maybe this will help if someone else has the problem.

**Comment by steveward** [comment]
Glad to hear things are working now.
