### ISSUE TITLE
Github Desktop hanging while cloning.

### ISSUE THREAD

**Issue by andrewkm** [desktop/desktop#16424]
### The problem

Trying to clone a repository.
Have cloned several, but for some reason this one is completely hanging.

### Release version

3.2.0 (x64)

### Operating system

Windows 11 Pro Build 23419

### Steps to reproduce the behavior

1. Go to File > Clone Repository and provide the GitHub URL of the repository.
2. Desktop starts the cloning process and hangs. Screenshot provided below in Screenshots section.

### Log files

[2023-03-30.desktop.production.log](https://github.com/desktop/desktop/files/11114956/2023-03-30.desktop.production.log)

### Screenshots

![bQsk2xp](https://user-images.githubusercontent.com/1013725/228933348-42862467-dc48-4b1d-83b8-4c3a58aaf6f2.png)

### Additional context

Unsure if related to: https://github.com/desktop/desktop/issues/16181 as I am not getting the same error as that issue.

**Comment by steveward** [comment]
@andrewkm thanks for the issue. I'm not seeing any errors in the log file, so the operation could be just taking a while to complete. How large is the repository you are trying to clone? I see the repository has submodules as well, which can increase the clone time quite a bit depending on their size.

To test if you are hitting #16181 you could try cloning via the command line without the submodules (which is the default operation).

**Comment by andrewkm** [comment]
This was my problem due to not having SSH setup on my GitHub. All is well now, apologies.

**Comment by steveward** [comment]
Glad to hear things are working now.
