### ISSUE TITLE
加入可选语言

### ISSUE THREAD

**Issue by ModestOscar** [desktop/desktop#16422]
### The feature request

没有语言选项，对0基础英语的使用者很不友好

### Proposed solution

加入多选语言选项

**Comment by 2233skice** [comment]
view it on unsubscribe

**Comment by steveward** [comment]
Thanks for the issue. At this time we do not have language localization in GitHub Desktop, but this is something that we would like to do in the future. I don't have a timeline for when that may happen as it would require quite a bit of work by the team. I'm sorry that I don't have better news at this time.
