### ISSUE TITLE
Icons not present in Repository Settings dialog

### ISSUE THREAD

**Issue by sweezyio** [desktop/desktop#16432]
### The feature request

Currently, icons are displayed next to menu items in the main Options dialog. (See below)
![image](https://user-images.githubusercontent.com/33377824/229305119-1b04fb10-a0ae-40ee-89c9-176992d34670.png)

However, in the Repository Settings dialog, there are no such icons:
![image](https://user-images.githubusercontent.com/33377824/229305159-bb2dc83f-51e5-41a7-97e1-37ec6eb9ffea.png)

### Proposed solution

Adding icons to the Repository Settings dialog (like how there are in the Options dialog) will make Desktop more consistent and add visual indicators for users.

For Remote we can use [server](https://primer.style/design/foundations/icons/server-16)
For Ignored Files we can use either [file-removed](https://primer.style/design/foundations/icons/file-removed-16) or [diff-ignored](https://primer.style/design/foundations/icons/diff-ignored-16)
For Git config we can use [git-commit](https://primer.style/design/foundations/icons/git-commit-16)
For Fork behavior we can use [git-branch](https://primer.style/design/foundations/icons/git-branch-16) 

### Additional context

From some light digging, it seems straightforward to add icons to the existing menu. As simple as importing the octicons then adding them to the tabs in the TabBar.

**Comment by tidy-dev** [comment]
Suggestion:  [Repo fork icon](https://primer.style/design/foundations/icons/repo-forked-24) for Fork behavior.

**Comment by sweezyio** [comment]
For Ignored Files, `diff-ignored` didn't look quite right and `file-removed` for some reason isn't included in [`octicons.generated.ts`](https://github.com/desktop/desktop/blob/development/app/src/ui/octicons/octicons.generated.ts). (I even tried regenerating the file with `yarn generate-octicons` and it still was not present)

I eventually settled on using the file octicon and I think it fits:
![image](https://user-images.githubusercontent.com/33377824/230261434-a859521e-da24-4795-9490-faad7da79a18.png)
