### ISSUE TITLE
Git Desktop Cloning Hanging For Private Repositories with Submodules

### ISSUE THREAD

**Issue by hwangh95** [desktop/desktop#16447]
### The problem

I am trying to clone a private repository with submodules. Whenver I try to clone it, the process hangs, and the desktop GUI, ssh.exe, and git.exe needs to be manually closed through task manager.

My SSH keys are setup correctly, and cloning the repository with or without --recurse-submodules works perfectly fine in this repository on the CLI.

For reference, I have tried cloning a public repository with submodules and it seems to work perfectly fine.

I also tried cloning without --recurse-submodules in the CLI, and add the local repository using the desktop GUI. The repository loads and I can switch between branches, but fetching, pushing, and pulling does not work.

### Release version

3.2.0 (x64)

### Operating system

Windows 11 Pro Build 22621

### Steps to reproduce the behavior

    Go to File > Clone Repository and provide the GitHub URL of the private repository.
    Desktop starts the cloning process and hangs.

OR

    Clone Repository Locally using CLI
    Add repository locally
    Cannot Fetch, Pull, or Push

### Log files

[2023-04-03.desktop.production.log](https://github.com/desktop/desktop/files/11139406/2023-04-03.desktop.production.log)

### Screenshots

![Screenshot clone](https://user-images.githubusercontent.com/22336846/229543710-37f4be8a-baa1-44fd-bcda-1255739d48db.png)

![Screenshot push](https://user-images.githubusercontent.com/22336846/229543225-178088af-7be8-4da8-9e10-c69cede4a96f.png)

### Additional context

This is a similar issue to #16181 and #16424

**Comment by steveward** [comment]
@hwangh95 thanks for the report. I'm seeing a few errors:

```
stderr:
warning: encountered old-style '/c/Users/HuidongHwang/.gitignore' that should be '%(prefix)//c/Users/HuidongHwang/.gitignore'
fatal: repository 'TwioTech/Soeder' does not exist
```

Can you verify that you have permissions to access the repository? Insufficient permissions will cause the whole clone operation to fail since it can't clone the submodule. We're tracking this in https://github.com/desktop/desktop/issues/3242. 

I'm also seeing this error that looks to be occurring when switching branches:

```
2023-04-03T14:08:09.189Z - error: [ui] `git -c credential.helper= checkout --progress origin/customer_test -b customer_test --recurse-submodules --` exited with an unexpected code: 1.
stderr:
error: Entry 'OCA/bank-statement-import/.copier-answers.yml' not uptodate. Cannot merge.
error: Submodule 'OCA/bank-statement-import' could not be updated.
error: Cannot update submodule:
	OCA/bank-statement-import

Aborting
```

Is that what you're seeing when fetching fails?

**Comment by hwangh95** [comment]
Hello, the first issue was just a syntax error for my gitignore which I fixed.

Yes I do have permissions to access to repository, I could clone the entire repository with --recurse-submodules when I accessed it using the command line.

The error that shows when switching branches only seems to occur when switching branches. Whenever I try to fetch, pull, or push, it just hangs without any error message

**Comment by steveward** [comment]
@hwangh95 apologies for the delay, I was looking into a similar SSH issue in https://github.com/desktop/desktop/issues/16542 and was able to reproduce the issue with SSH hanging that you are seeing. 

Going to  to File > Options > Advanced and deselecting the option to use the system OpenSSH things got things working again -- could you test that to see if it gets things working for you as well? I marked the other issue as a bug for investigate.
