### ISSUE TITLE
Indicate the maximum length of the commit message before cut

### ISSUE THREAD

**Issue by Andrej730** [desktop/desktop#16456]
### The feature request

Currently the app is showing lightbulb icon when 50 characters met but sometimes you do need a bit more and it's nice to know the point where the commit message will be cutted (I guess it's at 72 symbols) and the rest of it will go to commit description.

### Proposed solution

Something like this from #13075 or option with greying/redding out characters would be perfect. 

![image](https://user-images.githubusercontent.com/9417531/230043277-113b72e9-a171-4d9e-9187-5ae77740503f.png)

**Comment by steveward** [comment]
Thanks for the issue @Andrej730, I'm going to roll this into https://github.com/desktop/desktop/issues/14255 to consolidate requests about the commit message length.
