### ISSUE TITLE
Could not resolve host: github.com with out SU permission

### ISSUE THREAD

**Issue by ahsantahir01** [desktop/desktop#16450]
### The problem

i getting error fatal: unable to access 'https://github.com/Klipper3d/klipper/': Could not resolve host: github.com
but when i use SU its work but i want this work without su

### Release version

111

### Operating system

linux

### Steps to reproduce the behavior

$ git clone https://github.com/KevinOConnor/klipper ##
Cloning into 'klipper'...
fatal: unable to access 'https://github.com/KevinOConnor/klipper/': Could not resolve host: github.com
$ sudo su
root@localhost:/home/print3D# git clone https://github.com/KevinOConnor/klipper ##
Cloning into 'klipper'...
remote: Enumerating objects: 45044, done.

**Comment by niik** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
