### ISSUE TITLE
unable to access

### ISSUE THREAD

**Issue by santoshhanwante** [desktop/desktop#16459]
### The problem

fatal: unable to access 'https://github.com/exponentsoftware/santoshhanwante_unix_basic_commands_1679329498.git/': Failed to connect to github.com port 443 after 12248 ms: Connection refused
I am trying to do push the commit but it shows this error please anyone can help me.

### Release version

not in desktop i used as a link 

### Operating system

windows 10

### Screenshots

![Capture](https://user-images.githubusercontent.com/119409186/230099921-8379ddf3-caf0-4a4f-976a-ec4611a59916.PNG)

**Comment by steveward** [comment]
@santoshhanwante this issue tracker is specifically for GitHub Desktop, but it looks like you are behind a proxy or firewall that is blocking your connection.

You can configure a proxy by using this command:

`git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`

Replace `proxyuser` with your proxy username and `proxypwd` with your proxy password. Also, `proxy.server.com:8080` needs to point to the URL of your proxy server.

I hope that helps.
