### ISSUE TITLE
RPM Install instructions request:

### ISSUE THREAD

**Issue by MartinVonReichenberg** [desktop/desktop#16464]
### RPM Install instructions request:

Hello, 

I would like to ask for a **.SPEC file** and/or **.SRPM package** either for Fedora or openSUSE.
I want to add GitHub Desktop `github-desktop` application into [Open Build Service](https://build.opensuse.org/) (OBS).

Just provide it by adding it into any _build/packaging_ directory . . . 

Thank you in advance!
Martin

**Comment by steveward** [comment]
Thanks for the issue @MartinVonReichenberg. At this time there are no official builds of GitHub Desktop available for Linux, but a former developer of GitHub Desktop maintains a fork with Linux builds available for download:

https://github.com/shiftkey/desktop/releases

You can also follow along with https://github.com/desktop/desktop/issues/1525 for updates about an official Linux release.

**Comment by MartinVonReichenberg** [comment]
I see, 
I posted it into a wrong _repository_, it was meant to be in the other repository (the Linux fork)...

Thanks for the heads-up!

Martin
