### ISSUE TITLE
Installing on linux (gnu) aarch64

### ISSUE THREAD

**Issue by ah-ha-admin** [desktop/desktop#16466]
### The feature request

Just create brand new installation for linux fear 

### Proposed solution

Install manually on cli

### Additional context

Termux-GNu-Aarch64-Shell-Bash

**Comment by ah-ha-admin** [comment]
@mtodd @probablycorey @mutle

**Comment by ah-ha-admin** [comment]
#

**Comment by ah-ha-admin** [comment]
Duplicate of #

**Comment by avilajosmar02-cmyk** [comment]
> ### La solicitud de función
> Simplemente cree una nueva instalación para el miedo a Linux
> 
> ### Solución propuesta
> Instalar manualmente en CLI
> 
> ### Contexto adicional
> Termux-GNu-Aarch64-Shell-Bash

Termux-GNu-Aarch64-Shell-Bash
