### ISSUE TITLE
github desktop does not ignore .DS_Store

### ISSUE THREAD

**Issue by wiliki** [desktop/desktop#16461]
### The problem

We have .DS_Store in .gitignore, however, the github desktop program on MacOS Version 3.2.0 (arm64) does not ignore them.
<img width="574" alt="image" src="https://user-images.githubusercontent.com/7444381/230134647-ba02a259-0310-497a-8a2b-df1b3fa9b46d.png">

### Release version

Version 3.2.0 (arm64)

### Operating system

MacOS

### Steps to reproduce the behavior

right click on file brd/.DS_Store and select ignore file (add to .gitignore)
<img width="386" alt="image" src="https://user-images.githubusercontent.com/7444381/230135077-0abd31a1-60db-4366-a3bf-328b21c90f96.png">

File appears. in .gitignore, but it is still included in changed files.

**Comment by wiliki** [comment]
Duplicate issue. Closing

**Comment by gaviral** [comment]
Duplicate to which issues?

**Comment by jeffreytunison** [comment]
Duplicate to which issue @wiliki ??
