### ISSUE TITLE
git push --mirror Integration

### ISSUE THREAD

**Issue by gspeed0689** [desktop/desktop#16471]
### The feature request

Users in loosely bound organizations (such as universities) might want to create a mirrored repository instead of transferring ownership of a repository to the organization itself. 
It would be nice to have GitHub Desktop manage the ability to push my user managed repositories to my organization without having the user move to the command line and run the command as mentioned [in the GitHub Documentation](https://docs.github.com/en/repositories/creating-and-managing-repositories/duplicating-a-repository). 

### Proposed solution

In the configuration of a repository, have a field for a mirror repository git address. 
Then in the repository drop down menu, add a "Push to Mirror Repository" function. 

### Additional context

I have created two mock ups, this first one is the configuration option in the repository settings. 
![mirror repo setting](https://user-images.githubusercontent.com/6378547/230376117-7563db4d-5b47-44c8-bc09-cc0ce43c17e8.png)

This second one is for push function in the repository drop down menu. 
![push mirror button](https://user-images.githubusercontent.com/6378547/230376355-2e122c0f-b3ae-4275-b74a-545d09614196.png)

**Comment by steveward** [comment]
Thanks for the feedback @gspeed0689. We're generally against providing numerous flag options. There is a good workaround -- you can use `git config remote.<remote_name>.mirror true` to set a local repository as a mirror (the same as using the `--mirror` flag), and GitHub Desktop will respect that config setting. I hope that helps. I'm going to close this out.
