### ISSUE TITLE
Cannot login with github

### ISSUE THREAD

**Issue by devduttabain** [desktop/desktop#16470]
### The problem

github desktop for windows won't sign in using github. it's showing the loading spinner. 

### Release version

 3.2.0 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Go to 'File'
2. Go to 'Options..'
3. In 'Accounts' tab in GitHub.com section click 'Sign In' button
4. Click 'Continue with browser'

### Log files

2023-04-06T12:18:04.858Z - info: [main] Received possible protocol arguments: 3
2023-04-06T12:18:04.876Z - info: [main] Processing protocol url

**Comment by steveward** [comment]
@devduttabain thanks for the report. What browser are you using? One thing to try would be to switch the default browser on your machine to see if that works. We've seen issues with specific browsers in the past, and also with users running Windows on macOS in a VM with software like Parallels. 

This looks like the same issue as https://github.com/desktop/desktop/issues/11410., so I'm going to close this out, but let me know if switching your default browser gets things working.
