### ISSUE TITLE
cant make a branch on github desctob

### ISSUE THREAD

**Issue by monohi** [desktop/desktop#16473]
### The problem

I keep trying to make a branch but it wont work
![image](https://user-images.githubusercontent.com/98226150/230433638-8ec431e8-c7ff-4ebc-b07c-1e4c59cc1d74.png)
thanks

### Release version

newest

### Operating system

windows 10

### Steps to reproduce the behavior

make a branch

### Screenshots

![image](https://user-images.githubusercontent.com/98226150/230434101-9444a2d0-c5b1-42c1-a3fe-0af1c6f28fad.png)

**Comment by steveward** [comment]
@monohi thanks for the issue. In the background I can see the 'unborn HEAD' message, which indicates that your current branch does not have any commits on it. Once you make a commit on your default branch you'll be able to create a new branch. I hope that helps!

**Comment by monohi** [comment]
![image](https://user-images.githubusercontent.com/98226150/230434714-1e652908-cda9-4098-a108-4fe182e508f8.png)
its Version 3.2.1 (x64)

**Comment by monohi** [comment]
thanks
