### ISSUE TITLE
Not fetching origin

### ISSUE THREAD

**Issue by wire-fire** [desktop/desktop#16482]
### The problem

Not sure what happened, but the main branch of my repository doesn't exist anymore and I cannot fetch origin to regain it. Every time I try to fetch the origin it just stops and gives me an error message.

### Release version

3.2.1

### Operating system

Windows 10

### Steps to reproduce the behavior

Click fetch origin
get error message:
error: cannot lock ref 'refs/remotes/origin/HEAD': unable to resolve reference 'refs/remotes/origin/HEAD': reference broken
error: could not remove reference refs/remotes/origin/HEAD
From https://github.com/wire-fire/ErMo
 - [deleted]         (none)     -> origin/HEAD
remote: Enumerating objects: 39, done.        
remote: Counting objects: 100% (39/39), done.        
remote: Compressing objects: 100% (24/24), done.        
remote: Total 37 (delta 11), reused 35 (delta 10), pack-reused 0        
fatal: bad object refs/heads/main
error: https://github.com/wire-fire/ErMo.git did not send all necessary objects

**Comment by steveward** [comment]
Thanks for the issue @wire-fire. Can you try cleaning up the broken ref manually to see if you are then able to fetch again? This should be the right one:

`rm refs/remotes/origin/main`

and then run `git fetch` to grab the ref again.
