### ISSUE TITLE
Give us ability to download previous release of GitHub Desktop

### ISSUE THREAD

**Issue by findawei** [desktop/desktop#16485]
### The feature request

It happens that I accidentally update my GitHub desktop and suddenly I'm faced with a new commit bug, causing me to lose hours trying to debug.

### Proposed solution

Make all previous versions of Github Desktop available for download.

### Additional context

ASAP, please thank you.

**Comment by krisu5** [comment]
Forced auto-update makes it useless for installing previous versions.

**Comment by steveward** [comment]
Thanks for the feedback @findawei. Making previous releases of GitHub Desktop available is something we've discussed. I'll mark this as an enhancement for future consideration. We're also tracking opting out of auto-update in https://github.com/desktop/desktop/issues/3410.

**Comment by d-kleine** [comment]
Would be nice to have a setting to choose whether to have auto-update turned on or off.
And yes, it would be nice to have access to prior releases downloads once you run into trouble with a new version.

**Comment by pichpeym4n** [comment]
pich

**Comment by markuswinter** [comment]
GitHub Desktop installed an update and now no longer runs as my system (macOS 10.14.6) does not fulfill the minimum requirement of macOS 10.15. Which programmer is so dumb to NOT CHECK THE SYSTEM before installing an incompatible update??? Seriously??? And download an older version? Nah, just buy a new computer. I'm livid - that incompetence is staggering!

**Comment by ThioJoe** [comment]
You can find the old installers for previous versions through the WinGet packages repo here:
https://github.com/microsoft/winget-pkgs/tree/master/manifests/g/GitHub/GitHubDesktop

You'd go into the folder for the version you want, then go to the `GitHub.GitHubDesktop.installer.yaml` file and look for the `InstallerUrl` lines (There's one for MSI and one for EXE version). There seems to be a delay from when you go to the downloader link in your browser to when it starts downloading, but give it a minute and it should download.

**Comment by d-kleine** [comment]
> You can find the old installers for previous versions through the WinGet packages repo here:
> https://github.com/microsoft/winget-pkgs/tree/master/manifests/g/GitHub/GitHubDesktop

This might be a workaround for Windows users, but not for macOS users.

**Comment by ThioJoe** [comment]
> > You can find the old installers for previous versions through the WinGet packages repo here:
> > https://github.com/microsoft/winget-pkgs/tree/master/manifests/g/GitHub/GitHubDesktop
> 
> This might be a workaround for Windows users, but not for macOS users.

Ah good point. Looks like fortunately they use the same directory structure for all build versions, so you should be able to simply replace the filename in the last part with the one for mac.

Specifically, while Windows versions are:
* `GitHubDesktopSetup-x64.exe`
* `GitHubDesktopSetup-x64.msi`

The Mac versions seem to be:
* `GitHubDesktop-arm64.zip` (Apple Silicon)
* `GitHubDesktop-x64.zip` (Intel)

So you can still look up the URL in the WinGet repo, and then for example say you wanted the version 3.0.0, where the windows installer URL is:
`https://desktop.githubusercontent.com/github-desktop/releases/3.0.0-b9edf655/GitHubDesktopSetup-x64.exe`

You could then replace the last part to get:
`https://desktop.githubusercontent.com/github-desktop/releases/3.0.0-b9edf655/GitHubDesktop-arm64.zip`

**Comment by steveward** [comment]
@markuswinter you can download 3.3.13 (the last version compatible with your macOS version) from this link and it shouldn't bother you more with auto-updates: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.13-1b0804db/GitHubDesktop-x64.zip

**Comment by d-kleine** [comment]
I still think it would be helpful to have an option for downloading a previous release at https://desktop.github.com/

**Comment by igodfried-datasense** [comment]
So how can we disable auto update? Particularly since the new pre-commit hooks bug I need to stay on the old version and don't want it auto updating. This is very important until you fix that bug.

**Comment by steveward** [comment]
@igodfried-datasense renaming the `C:\Users\<your_user>\AppData\Local\GitHubDesktop\Update.exe` file will prevent auto-updating. What specific hook issue are you encountering?

**Comment by igodfried-datasense** [comment]
Thanks. I just did that. This is the one I'm running into on the upgraded version: https://stackoverflow.com/questions/78695471/pre-commit-error-missing-config-value-git-config-value-0 or I guess someone also mentioned here https://github.com/desktop/desktop/issues/18945 but the fix didn't work for me or others on my team so just downgrading.

**Comment by steveward** [comment]
Previous releases will now be accessible at https://github.com/desktop/desktop/releases. Thanks to @sergiou87 for his work on getting this set up, and for uploading all the previous releases! ✨
