### ISSUE TITLE
Stashed files got erased

### ISSUE THREAD

**Issue by Rakesh-Nair-er** [desktop/desktop#16488]
### The problem

Stashed files of  got erased after selecting and right clicking STASH option. Checked the Stash files and log - apparently nothing got stashed when clicked. This issue happened for the first time.

### Release version

3.2.1 (x64)

### Operating system

Windows 10

**Comment by steveward** [comment]
Thanks for the report @Rakesh-Nair-er. We should be able to recover the stash -- you will need to find the log file from the day this happened. You can access the log by going to Help > Show Logs in Finder (macOS) or Explorer (Windows).

Then you will want to search for a line like this:

 `[ui] Dropped stash 'b947c54873415d875d5e4e0d941c443716e1c81e' associated with main`

You can then copy that SHA and run the following command from the command line:

git stash apply b947c54873415d875d5e4e0d941c443716e1c81e

That should recover the lost changes if the stash was dropped. Let me know if that helps.

**Comment by MamaC1974** [comment]
I am just learning anybody help me get this right
