### ISSUE TITLE
New look, lost the knowledge of linked/cloned repos

### ISSUE THREAD

**Issue by Jay-o-Way** [desktop/desktop#16501]
### The problem

Thanks for updating the app. Now, When I start it, I can _see_ the repos that I have previously cloned to my computer, but Desktop has forgotten that these are already cloned. Now, when I select any of them, Desktop wants me to clone it again. But that shouldn't happen, and I can't use the existing folder because it's already occupied. And I'm not feeling much for downloading **everything** again.

### Release version

3.2.1

### Operating system

Windows 10, 22H2

### Log files

[2023-04-10.desktop.production.log](https://github.com/desktop/desktop/files/11191984/2023-04-10.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/65828559/230944787-e6accce6-eb15-48d9-bf89-6d16dba8fe38.png)
![image](https://user-images.githubusercontent.com/65828559/230944818-c944c0fe-5067-4055-a91c-ab3a9d491d8d.png)

**Comment by tidy-dev** [comment]
Hi @Jay-o-Way! It looks like the app has completely reset, and does not know the locations of your repositories that are already downloaded. You can add them back without cloning. Click on the "Add an Existing Repository" to find it through the file finder. Another quick way to add them is to drag and drop the repository folder onto the Desktop app and you can do multiple this way if you store all your repositories in one directory by selecting repository folders to drag and drop.
