### ISSUE TITLE
When I right click the “current repository” area and select the option “Open in Windows Terminal” it does not open the repository 

### ISSUE THREAD

**Issue by taoliu12** [desktop/desktop#16505]
### The problem

When I right click the “current repository” area and select the option “Open in Windows Terminal” it does not open the repository in the correct directory in Windows terminal, but rather Windows terminal opens in this directory :/mnt/c/Windows... How do I get it to opening the correct directory in Windows terminal?

The correct directory would be “ ~/git/reponame ”
But instead windows terminal opens in ” /mnt/c/Windows ”

### Release version

Version 3.2.1 (x64)

### Operating system

Windows 10

### Screenshots

![2023-04-10 13_45_59-Settings](https://user-images.githubusercontent.com/5350036/230995709-466b57b2-427e-4192-b812-28cec4d7100b.jpg)

**Comment by steveward** [comment]
Thanks for the report @taoliu12. Do you have Windows Terminal set to run in elevated mode? See [this issue](https://github.com/desktop/desktop/issues/16102) for reference.

**Comment by taoliu12** [comment]
@steveward I gave Github Desktop elevated mode ("run as admin") but I am still getting the same behavior. I also tried uninstall and reinstall GH Desktop.

If you or anyone has any more ideas to try it would be appreciated, thanks.

**Comment by tsvetilian-ty** [comment]
Hey @taoliu12 👋 I have a few questions that might help us narrow down the possible issue:
- I see you're using a Linux profile in the terminal. Could you try to set the Default Profile to "Power Shell" or "Command Prompt" and check if you still get the wrong directory?
- What is the "Starting directory" that you're profile uses? (Settings > Profiles > <Your profile>)
- Could you try to add the repo in your C drive or any other Windows accessible path? (your windows drives are reachable through `/mnt/` directory in your Linux distro)

> You don't have to elevate the GitHub Desktop executive permissions if you don't use `Run this profile as Administrator` for your terminal profile!
