### ISSUE TITLE
Bottom controls do not stay inside window

### ISSUE THREAD

**Issue by Jay-o-Way** [desktop/desktop#16502]
### The problem

Items at the bottom do not move back up, becoming unreachable.

### Release version

3.2.1

### Operating system

Windows 10, 22H2

### Steps to reproduce the behavior

Open main window, start small, see the "pro tip" and "clone" elements.
Increase the height of wiindow, then move back.

### Screenshots

![Window resize](https://user-images.githubusercontent.com/65828559/230950725-124d4695-2533-485a-8ad1-d01a30c79ad7.gif)

**Comment by steveward** [comment]
Thanks for the report @Jay-o-Way. I was able to reproduce this as well on both macOS and Windows.
