### ISSUE TITLE
Hide Recent Repos

### ISSUE THREAD

**Issue by 9mm** [desktop/desktop#16519]
### The feature request

This is an incredibly frustrating feature. I have about a dozen repos and it duplicates only SOME of the repos. Worst of all, it makes it extremely hard to see at a glance which repo I want, because the ordering breaks my muscle memory when I go to look in a repo where I expect it to be, given that only SOME are duplicated. So sometimes I look above, and other times its not there.

Please please allow hiding this

### Proposed solution

Make a checkbox to hide this section

**Comment by steveward** [comment]
Thanks for the feedback @9mm, I'll add this to https://github.com/desktop/desktop/issues/15244 where are tracking this.

**Comment by ghost** [comment]
> ### طلب الميزة
> هذه ميزة محبطة بشكل لا يصدق. لدي حوالي اثني عشر ريبو وهو يكرر فقط بعض المستودعات. الأسوأ من ذلك كله ، أنه يجعل من الصعب للغاية رؤية الريبو الذي أريده في لمحة ، لأن الطلب يكسر ذاكرة عضلاتي عندما أذهب للبحث في الريبو حيث أتوقع أن يكون ، بالنظر إلى أن البعض فقط مكرر. لذلك في بعض الأحيان أنظر أعلاه ، وأحيانا أخرى ليس هناك.
> 
> يرجى السماح بإخفاء هذا
> 
> ### الحل المقترح
> إنشاء خانة اختيار لإخفاء هذا القسم
> 
> ### سياق إضافي
> _لا يوجد رد_
