### ISSUE TITLE
Pushing to origin won't complete.

### ISSUE THREAD

**Issue by rkedge** [desktop/desktop#16514]
### The problem

While trying to push changes, GitHub Desktop is stuck. 
<img width="524" alt="Screenshot 2023-04-11 at 11 40 02 AM" src="https://user-images.githubusercontent.com/5322900/231231089-d7a861ac-fefa-4e25-8480-0a021d6e10a4.png">

Suspect it may be related to intermittent network connectivity, but I do not have a way to reproduce this bug.

### Release version

Version 3.2.1 (arm64)

### Operating system

macOS Ventura 13.2.1 (22D68)

### Steps to reproduce the behavior

Intermittent error
1. Click the push to origin box at the top of the window.

### Log files

[2023-04-10.desktop.production.log](https://github.com/desktop/desktop/files/11202887/2023-04-10.desktop.production.log)
[2023-04-11.desktop.production.log](https://github.com/desktop/desktop/files/11202888/2023-04-11.desktop.production.log)

### Screenshots

<img width="524" alt="Screenshot 2023-04-11 at 11 40 02 AM" src="https://user-images.githubusercontent.com/5322900/231232276-7cd7be76-8456-445a-be40-a600f14aa79e.png">

**Comment by steveward** [comment]
@rkedge this does look like a network issue:

`error:02FFF036:system library:func(4095):Connection reset by peer`

Are you using a VPN or behind a firewall/proxy server? Are you able to test on a different network? I would also try performing a push via the command line to see if you encounter the same error.

**Comment by rkedge** [comment]
@steveward agreed.
I would not expect have to restart GitHub Desktop to reset the connection.

**Comment by steveward** [comment]
@rkedge at this time we don't have a way to cancel Git operations in GitHub Desktop, but this is something that has been previously requested in https://github.com/desktop/desktop/issues/14095. 

Were you able to try pushing from the command line as well?

**Comment by rkedge** [comment]
@steveward I had no issues pushing from the command line. And once I quit and restarted GitHub Desktop I was able to push again. I suspect the first push failed due to network issues, and GitHub Desktop didn't recognize it as a failure, but instead was waiting for a response. Perhaps there should be a timeout in the loop.

**Comment by steveward** [comment]
Thanks for the update, glad to hear things are working now.
