### ISSUE TITLE
"Authentication failed. Some common reasons include" - Error when trying to push branch up

### ISSUE THREAD

**Issue by jordankeen** [desktop/desktop#16517]
### The problem

Hi there, I got the below error yesterday when trying to push in github desktop. I tried to follow all of the steps to create a new SSH key and what not but have had no luck. 

<img width="799" alt="Screen Shot 2023-04-11 at 8 25 50 PM" src="https://user-images.githubusercontent.com/17208340/231321193-cf007ba5-4747-4859-97bb-9dcf275a219e.png">

When I use this command 'ssh -T git@github.com', it continually asks me (yes/no)?

When I try to push with terminal it gives me the below warning, but allows me to push when I say 'yes'

```
Warning: the ECDSA host key for 'github.com' differs from the key for the IP address '140.82.112.3'
Offending key for IP in /Users/keenoo7/.ssh/known_hosts:9
Matching host key in /Users/keenoo7/.ssh/known_hosts:12
Are you sure you want to continue connecting (yes/no)?
```

In my logs, I'm seeing the error 'Host key verification failed.' when I try to push.

### Release version

3.2.1

### Operating system

mac 10.15.7

### Steps to reproduce the behavior

1. when trying to push a branch up to the remote

### Log files

[2023-04-12.desktop.production.log](https://github.com/desktop/desktop/files/11206132/2023-04-12.desktop.production.log)

**Comment by steveward** [comment]
@jordankeen this is due to GitHub's RSA SSH Host Key changing -- see [this blog post](https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/). Removing the old key from your `~.ssh/known_hosts` file should get things working in GitHub Desktop. Let me know if you have any issues.

**Comment by jordankeen** [comment]
Thanks for the help @steveward - when I tried to run the second command from that blog post I got the below error,

```
-bash: jq: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17745    0 17745    0     0   122k      0 --:--:-- --:--:-- --:--:--  122k
curl: (23) Failed writing body (0 != 1361)
```


Right now, if I try to test my SSH connection using this,
`ssh -T git@github.com`

I get the below error,

```
Warning: the ECDSA host key for 'github.com' differs from the key for the IP address '140.82.113.3'
Offending key for IP in /Users/keenoo7/.ssh/known_hosts:6
Matching host key in /Users/keenoo7/.ssh/known_hosts:13
```

**Comment by steveward** [comment]
@jordankeen you should just be able to edit the known_hosts file to remove the old public key. It should be the first key in that file with the `github.com` prefix.

**Comment by jordankeen** [comment]
@steveward - I removed the first line that contained github.com prefix, but do I need to also remove the other 3 lines here? I'm still getting the same error in github desktop

![Uploading Screen Shot 2023-04-15 at 1.57.16 PM.png…]()
