### ISSUE TITLE
Can't fetch from github repository with github desktop.

### ISSUE THREAD

**Issue by mapeed123** [desktop/desktop#16524]
### The problem

I cant fetch from my origin after a friend pushed edits to the branch. Our group is three people, including me, and I'm the only one who can't fetch the most recent commits my friends have pushed.
 

### Release version

3.2.1 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Go to github desktop, into main repository and branch.
2. Click on Fetch Origin.
3. Fetch Origin says "Never Fetched"
4. Get error window.

### Log files

[2023-04-12.desktop.production.log](https://github.com/desktop/desktop/files/11214782/2023-04-12.desktop.production.log)

### Screenshots

![FetchError](https://user-images.githubusercontent.com/80853400/231553883-93d81d63-6033-46de-ab3f-a29dfe76a8fe.png)

**Comment by steveward** [comment]
Thanks for the report @AimRecked. Normally 'invalid argument' errors are a result of an illegal character being present in a filename. Windows has some specific reserved characters that you can find a list of here:

https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#naming-conventions

Unfortunately the problematic file isn't being shown in the error output, but if you try and clone the repository again to a different location it should show the file path. You could also take a look at the recent commits to see if one of those characters was added in a new file. Let me know if that helps!

**Comment by mapeed123** [comment]
Thanks for replying @steveward, appreciate the reply.

I tried to clone the repository but it says I can't because it tells me that Git Hub can only clone to empty folders. Also, when you say "[...] one of those characters was added in a new file.", do you mean in the name of the file, or it's contents?

Thank you.

**Comment by steveward** [comment]
>I tried to clone the repository but it says I can't because it tells me that Git Hub can only clone to empty folders. 

Make sure you clone to a new directory without the existing repository, since there will be a name conflict. 

>in the name of the file, or it's contents?

The name of the file is what I've normally seen cause this error.

**Comment by mapeed123** [comment]
It started working for some reason. But thank you for the help.

**Comment by battsteam** [comment]
my computer to is saying i have virises
