### ISSUE TITLE
Github desktop always try to change line ending to "CRLF"

### ISSUE THREAD

**Issue by sousou99** [desktop/desktop#16522]
### The problem

![image](https://user-images.githubusercontent.com/18554688/231508068-57f42801-c209-49ea-94c3-4480e2cc2e3e.png)

Please stop it.

My local configure already set core.autocrlf to false.
![image](https://user-images.githubusercontent.com/18554688/231508389-8e84f5c3-e296-49b5-bd50-44f91eb971fb.png)

### Release version

3.2.1

### Operating system

windows 10

**Comment by sousou99** [comment]
Found the root cause.
It's due to a configure file embeded in GitHub Desktop.
![image](https://user-images.githubusercontent.com/18554688/231509124-1a894c79-b979-4329-9bff-fa24ff9f8a77.png)
It set core.autocrlf to true.
and this is hidden in command "git config --list"
Could you stop putting a hidden config in the package?
Or make it visible.

**Comment by steveward** [comment]
@sousou99 thanks for the issue. Generally it's recommended to configure line-ending settings in the global `.gitconfig` file or on a per-repo basis by using the `.gitattributes` file (see our [help article](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings) about this). Is there a specific reason you decided to set it in the system `.gitconfig` instead? 

I'll close this out as resolved, but let me know if you have any further questions.

**Comment by sousou99** [comment]
Did you really read my text?
The problem is , no matter where I set it, it will be overrided by the config file from Github Desktop installation.

**Comment by steveward** [comment]
The system level `.gitconfig` in the Git that comes bundled with GitHub Desktop will not override the local `.git/config`or global .`gitconfig`. The hierarchy is system -> global -> local, with each level overriding the previous. See [this section](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup) in Pro Git for reference.

**Comment by sousou99** [comment]
OK, I know what you mean.
The .gitconfig bundled with Github Desktop does not override global or local .gitconfig.
But it can override system level config.
This is still problematic.
Since there is no hint to the user.
If I didn't talk with you, I never know the rule.
Is there any reason to override system config in a hidden way?
Since it's not visible with git config --list.
The issue is hard to be found.
If it could not be avoid, at least, give some hint or feedback on the GUI.

**Comment by steveward** [comment]
Thanks for the feedback. I agree that is confusing -- I'll make a note to add this to our help docs about configuration. Sorry for the confusion!

**Comment by sousou99** [comment]
ok, thank you!

**Comment by insideClaw** [comment]
This decision makes a mockery of the big motto on the GitHub Desktop landing page - "Experience Git without the struggle", which later continues with "Focus on what matters instead of fighting with Git."

I'm an experienced Git user but not usually on Windows. I've seen colleagues struggle with scripts not working and not knowing their editor silently converts everything to CRLF, so I knew what to look out for. What surprised me is just how convoluted fixing this is:
- There's no mention of this happening
- There's nothing I could find in the GitHub Desktop options menu
- Setting `git config --global core.autocrlf false` with Git Bash is ignored

Had to navigate as shown in the above screenshot, to the obscure directory `C:\Users\<user>\AppData\Local\GitHubDesktop\app-3.4.5\resources\app\git\etc` in order to change that default. Might have to rethink the motto with such decisions...

**Comment by LostOnTheLine** [comment]
> This decision makes a mockery of the big motto on the GitHub Desktop landing page - "Experience Git without the struggle", which later continues with "Focus on what matters instead of fighting with Git."
> 
> I'm an experienced Git user but not usually on Windows. I've seen colleagues struggle with scripts not working and not knowing their editor silently converts everything to CRLF, so I knew what to look out for. What surprised me is just how convoluted fixing this is:
> 
>     * There's no mention of this happening
> 
>     * There's nothing I could find in the GitHub Desktop options menu
> 
>     * Setting `git config --global core.autocrlf false` with Git Bash is ignored
> 
> 
> Had to navigate as shown in the above screenshot, to the obscure directory `C:\Users\mario\AppData\Local\GitHubDesktop\app-3.4.5\resources\app\git\etc` in order to change that default. Might have to rethink the motto with such decisions...

I've literally been driving myself crazy trying to fix this. 
I've changed the following files & nothing seems to fix it. When I edit a file locally & use Notepad++, ensuring it's `[LF]`, it always tells me when I'm committing that it's converting the files from `[LF] to [CRLF]` but I want them to stay in `[LF]`.  
`C:\Users\LostOnTheLine\AppData\Local\GitHubDesktop\app-3.4.15\resources\app\git\etc\gitconfig`
`C:\Users\LostOnTheLine\AppData\Local\GitHubDesktop\app-3.4.16\resources\app\git\etc\gitconfig`
`L:\git\_repos\LostOnTheLine\Anime-Dub-Calendar\.git\config`
