### ISSUE TITLE
Feature request: rebase

### ISSUE THREAD

**Issue by ofek** [desktop/desktop#1652]
First off, fantastic work on the new app! It can almost replace command line (for me).

Specifically, I would really like 2 things:

1. to be able to create a fork, clone locally, then `git pull --rebase` the original repo into my local master. basically just like the current merge option but instead with rebasing.
2. create a new branch from local master then rebase new branch from master. this also might be achieved via no. 1

Thanks!

**Comment by andymac4182** [comment]
We use rebase a lot internally to keep our master tree as clean as possible. 

1. Fetch
2. Rebase
3. Push

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by ofek** [comment]
@joshaber May I ask why? When one has an open PR and there are changes to master (this situation arises frequently), the customary way to resolve such a conflict is to rebase. It's canonical, really.

Example PRs just from this repo:
https://github.com/desktop/desktop/pull/155#issuecomment-233094591
https://github.com/desktop/desktop/pull/1677#issuecomment-306655782

**Comment by joshaber** [comment]
@ofek It's a matter of prioritization. We're a small team with limited bandwidth. Rebasing could be a valuable feature, but we don't think it's as important as the other work we've chosen to prioritize.

**Comment by cnielsen-socotra** [comment]
Atlassian SourceTree has this feature now, in case it helps prioritize this, if the roadmap changes.

**Comment by billygriffin** [comment]
I'm removing the labels on this so it's easier to track the things that we're going to focus on, and there's an open issue for #3422 that we'll use to track rebasing.

**Comment by ktravelet** [comment]
+1, just build in the command `git pull --rebase --autostash` to a button, it's that easy! :P

**Comment by ampinsk** [comment]
Hi everyone,

Thanks for expressing interest in rebasing in GitHub Desktop, and for taking the time to explain your use cases with us. For that, we truly thank you!

This week, we’re exploring the future of rebasing on GitHub Desktop and would love to understand your workflow and get your reaction to some designs we have made.

If you would be open to a 30 minute User Interview with a few of our GitHub Desktop Core team, fill out [this form](https://docs.google.com/forms/d/1tD_jVbKr-KzsMSqVmwmZRCcQnjuw_5K8vrnnpid6yxk/viewform?edit_requested=true) by the end of the day today.

We’re still in our “Research Phase” so any and all thoughts you have are absolutely welcome! If you have any follow up questions for us before filling out the survey, we’d be happy to answer them.

Thank you!

**Comment by ktravelet** [comment]
@ampinsk I just filled it out with my enterprise credentials.  The use case for me is pretty simple.  If I'm revisiting an old branch, I always want to update it with the latest upstream branch just in case there are changes with the files I'm working on.  I'd rather see and fix merge conflicts early on the old branch before I spend time developing the old branch and not see the merge conflicts until the pull request.  Feel free to reach out!

**Comment by KaneHart** [comment]
Oh wow I'm newbie with Github overall but our team suffering this Merge branch 'master' of spam and noticed this.

How can Github not be supporting this day one out the door? It seems insane that you want people to have this spam up none stop using your client if you have more then 1 person using your program....

I know I'm coming off but clearly someone needs to learn prioritizing a bit better. I googled more on the subject and all I can see is people making jokes and fun of teams with these commits and here your forcing it on us.
