### ISSUE TITLE
cannot clone or push :Unsupported proxy syntax in 'socks:127.0.0.1:9150

### ISSUE THREAD

**Issue by utc425937** [desktop/desktop#16520]
### The problem

When cloning it shows :Cloning into 'C:\Users...
fatal: unable to access 'https://github.com/.......git/': Unsupported proxy syntax in 'socks:127.0.0.1:9150'
9150 is tor listening port but i am not using tor that time neither do i use vpn or proxy,I did download tor and used it a couple weeks ago.
How can i solve that?

### Release version

Version 3.2.1 (x64)

### Operating system

windows

### Steps to reproduce the behavior

1.download torbrowser bundle
2.start it
3.close it
4.start github desktop and clone a repository

### Log files

[2023-04-12.desktop.production.log](https://github.com/desktop/desktop/files/11212801/2023-04-12.desktop.production.log)

### Screenshots

![bug](https://user-images.githubusercontent.com/122073426/231498318-9d16766d-d93f-4366-b8e9-47278bef4326.png)

**Comment by steveward** [comment]
@utc425937 can you share the output of `git config --list --show-origin` from the command line? That should show if there are any existing proxy settings configured.
