### ISSUE TITLE
Windows Desktop GitHub won't start after failed update v3.2.0?

### ISSUE THREAD

**Issue by rumsey68** [desktop/desktop#16521]
### The problem

Windows Desktop GitHub won't start after failed update this morning. Pretty sure it was because my PC was low on disk space.

Think it was updating from 3.2.0 to 3.2.1. Looking in "Squirrel-Update.log" (attached) i can see various errors including low disk space message.

I am happy to reinstall as long as I don't lose my current setup.

### Release version

3.2.0 but won't start so can't confirm

### Operating system

windows 10 64 bit

### Log files

[Squirrel-Update.log](https://github.com/desktop/desktop/files/11213172/Squirrel-Update.log)

**Comment by steveward** [comment]
@rumsey68 If you're out of disk space that could definitely cause any update failure. Reinstalling won't affect your locally cached data, as that is stored separately in %AppData%. Let me know if a reinstall gets things working for you.

**Comment by rumsey68** [comment]
Have reinstalled and seems OK now thanks

**Comment by steveward** [comment]
Glad to hear things are working now!
