### ISSUE TITLE
Non-Github Repository Support

### ISSUE THREAD

**Issue by jacob-maristany** [desktop/desktop#1653]
### Description

In the previous release of Github Desktop (non-Electron version), I am able to sync with TFS/VSTS repositories added via the "Add Local Repository" action.  The old Github Desktop client would prompt for credentials and authenticate properly.  However, this new Electron client prompts with an Error saying "Authentication Failed...." and instructs to sign in with an account in the preferences that has access to that repository.  However, the account pane only allows the addition of Github and Github Enterprises.  Is the able to authenticate and use the the client with other non-github repositories going to be supported in the new client? 

### Version

**GitHub Desktop version:** 0.5.5

**OS version:** macOS 10.12.4

### Steps to Reproduce

1. Clone a non-github repository (from TFS or VSTS)
2. "Add Local Repository" from the Github Desktop Client (Electron beta)
3.  Attempt to pull.

**Expected behaviour:** Github prompts for credentials 

**Actual behaviour:** Github shows an error message that the current Github credentials cannot authenticate

**Reproduces how often:** 100%

**Comment by niik** [comment]
Hey @jacob-maristany, we're tracking this issue over in #852 so please subscribe to that issue to follow along!
