### ISSUE TITLE
All text blurred out first install

### ISSUE THREAD

**Issue by Dantorior** [desktop/desktop#16530]
### The problem

All text blurred out can't read anything, if this is feature I what to turn it off.

### Release version

Version 3.2.1 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Install
2. Log in using git account
3. Click "Finish"
4. All text blurred out can't read anything

### Screenshots

![1](https://user-images.githubusercontent.com/59513717/231841112-ca49516b-3b12-4c18-8358-15c1cb59f5c5.png)

**Comment by tsvetilian-ty** [comment]
Thanks for the report @Dantorior. Could you try the steps suggested in https://github.com/desktop/desktop/issues/14190#issuecomment-1069594613? Depending on your video driver version, you might have additional FXAA settings!

**Comment by Dantorior** [comment]
Thanks @tsvetilian-ty that helped with text, but ghost menus after closing them are still there.
![изображение](https://user-images.githubusercontent.com/59513717/231873827-d0f14c1a-17ac-47bd-ab0c-146d9f8baa6c.png)

**Comment by tsvetilian-ty** [comment]
Try to play more with the settings in the Nvidia panel. The reason for that type of issue is usually anti-aliasing settings, but they can vary between Nvidia driver versions. You can check this https://github.com/desktop/desktop/issues/16413#issuecomment-1493372495

**Comment by Dantorior** [comment]
Yup, in my case it was MFAA messing up.
