### ISSUE TITLE
git reset --hard HEAD^ doesnt work

### ISSUE THREAD

**Issue by Reene-Ramos** [desktop/desktop#16537]
### The problem

was trying to work this out with a person on discord but nothing works
![image](https://user-images.githubusercontent.com/115441807/231911725-a33a79ad-1f32-4bce-87fb-653c26072461.png)

### Release version

Version 3.1.2 (x64)

### Operating system

Windows 10 Home

**Comment by Reene-Ramos** [comment]
**I was in the right directory**

**Comment by tidy-dev** [comment]
👋 Hi @Reene-Ramos! GitHub Desktop does not currently implement `git reset --hard`, and it is unclear what you are trying to accomplish. 

Note: resetting hard will delete your recent changes, but if that is what you are trying to do:
1. Opening the repository in GitHub Desktop. 
     - This assumes you have a git repository set up in GitHub Desktop.
3. Go to the the 'Repository" many menu and "Open in [your selected command line]" 
     - This should open your repository directory in your command line.
4. Input the git command you want. 

I am going to close this as it does not appear to be an issue with GitHub Desktop's functioning.

**Comment by manudevelopia** [comment]
I came across same issue on windows using cmd on vscode, I solved changing terminal from `cmd` to `git bash`
