### ISSUE TITLE
How about putting a "+" between keyboard shortcuts on the No local Changes page?

### ISSUE THREAD

**Issue by yasuking0304** [desktop/desktop#16549]
### The feature request

How about putting a "+" between keyboard shortcuts on the No local Changes page?

### Now
![WS000001_1](https://user-images.githubusercontent.com/111163564/232810496-e737291c-9780-4b8d-968d-5939a32f407e.JPG)

### Feature Request
![WS000002](https://user-images.githubusercontent.com/111163564/232810520-a341dd3d-d1bb-4e09-8baa-a825518a0e0c.JPG)

### Proposed solution

Modify app\src\ui\changes\no-changes.tsx

Now
```TypeScript
  private renderDiscoverabilityKeyboardShortcut(menuItem: IMenuItemInfo) {
    return menuItem.acceleratorKeys.map((k, i) => <kbd key={k + i}>{k}</kbd>)
  }

```

Feature Request
```TypeScript
   private renderDiscoverabilityKeyboardShortcut(menuItem: IMenuItemInfo) {
    return menuItem.acceleratorKeys.map((k, i) => {
      return menuItem.acceleratorKeys.length === i + 1 ? (
        <kbd key={k + i}>{k}</kbd>
      ) : (
        <>
          <kbd key={k + i}>{k}</kbd>
          <>+</>
        </>
      )
    })
  }
```

**Comment by niik** [comment]
I think there's a platform difference here. On Windows keyboard shortcuts are typically shown with `+` whereas on macOS they're typically not.

We specifically handle this case for application menus:

https://github.com/desktop/desktop/blob/ea202db14474b3fca0be2d406cec309f1728511b/app/src/ui/app-menu/menu-list-item.tsx#L79-L84

So we'd be happy to take a look at a PR for this but we'd need it to be platform specific.

**Comment by yasuking0304** [comment]
I see. I should fix it like this.

app\src\ui\changes\no-changes.tsx
https://github.com/desktop/desktop/blob/58b8bea53fde1e19be32f68a11a4a3358a4d3ee0/app/src/ui/changes/no-changes.tsx#L227-L230
```TypeScript
  private renderDiscoverabilityKeyboardShortcut(menuItem: IMenuItemInfo) {
    return menuItem.acceleratorKeys.map((k, i) => {
      return __DARWIN__ ? (
        <kbd key={k + i}>{k}</kbd>
      ) : menuItem.acceleratorKeys.length === i + 1 ? (
        <kbd key={k + i}>{k}</kbd>
      ) : (
        <>
          <kbd key={k + i}>{k}</kbd>
          <>+</>
        </>
      )
    })
  }
```
Windows
![WS000003](https://user-images.githubusercontent.com/111163564/233096907-5ec3d0b3-1f4a-425e-b307-aa526b6e9542.JPG)

Mac OS
![スクリーンショット 2023-04-19 22 50 44](https://user-images.githubusercontent.com/111163564/233098069-7a34fa8d-cc65-460d-bada-337a77c6471a.png)
