### ISSUE TITLE
GitHub Desktop create same branch when first time push by GitHub Desktop

### ISSUE THREAD

**Issue by emptylight370** [desktop/desktop#16540]
### The problem

When I push my code to remote main branch, GitHub Desktop will create a new `master` branch at remote branch when I use GitHub Desktop for the first time. And that new remote `master` branch is as same as the former `master` branch, and it can't be show at remote server(`GitHub Repository branch`)(only show one branch), but it can be show at local git tree or log. At local git can see two branch in same name. And at Git Graph it display in `remotename/HEAD`(see at screenshot).

### Release version

version 3.2.1(x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Add a new local git repository in GitHub Desktop
2. Push commits to remote repository
3. Open VSCode and switch to git source control page
4. See the remote branch(By Extension GitLens) or Git Graph(By Extension Git Graph)

### Screenshots

![image](https://user-images.githubusercontent.com/61617417/232322764-156e3096-2b6c-440b-91e0-52e8ba2893fd.png)

**Comment by tidy-dev** [comment]
👋 @lingfengyu-dreaming Sorry for your issue. I tried the reproductions steps you have listed and here is my result. 

![Git log graph output showing `Head -> main`, `origin/main`, `origin/Head`](https://user-images.githubusercontent.com/75402236/232482623-26973446-9d1a-4e1a-98c2-080aaf9d36a1.png)

That is what I would expect. Is there anything different about your git configuration that may be giving you a different result?

**Comment by emptylight370** [comment]
I'm not sure whether it is the designed result, if it is, that might be not a bug, and this issue can be closed
