### ISSUE TITLE
Allow users to undo the changes of the selected file with the Del/Delete key

### ISSUE THREAD

**Issue by andrewhong04** [desktop/desktop#16548]
### The feature request

![image](https://user-images.githubusercontent.com/35881688/232807476-b0fad3da-2e10-4f76-a07a-db9451c17ed1.png)
When trying to work on my bed, I do not have easy access to my mouse and when trying to work with GitHub Desktop I noticed that there's no easy solution to delete the file that has been selected, you can only deselect the file.

### Proposed solution

Allow users to undo the changes of the selected file with the Del/Delete key

**Comment by steveward** [comment]
Thanks for the issue @novialriptide, I'm going to add this to https://github.com/desktop/desktop/issues/11924.
