### ISSUE TITLE
Profiles feature

### ISSUE THREAD

**Issue by sudhakarbx** [desktop/desktop#16551]
### The feature request

It would be a nice feature to have a profiles feature or a similar feature to filter repositories by label

**Use case**

- When working a product, product will have its own repositories, it would be difficult to filter repositories related to the product
- When working on multiple client projects, it would nice to have filter repositories

### Proposed solution

An profile feature would be great to configure repositories per client or per project and so on.

**Comment by steveward** [comment]
Thanks for the feedback @b-sudhakar. See [this comment](https://github.com/desktop/desktop/issues/10201#issuecomment-658693653) for more information about why we do not have plans to implement repository grouping at this time. 

One workaround is to use the repository alias feature and then use that to filter by a specific alias prefix. I hope that helps.
