### ISSUE TITLE
Example of repository asset (/repo/owner/assets/userID/guid)?

### ISSUE THREAD

**Issue by tomasreimers** [desktop/desktop#16553]
### The feature request

Hello,

I'm working on an extension to GH Desktop, and I am confused by this bit of code: 

https://github.com/desktop/desktop/blob/ea202db14474b3fca0be2d406cec309f1728511b/app/src/main-process/authenticated-image-filter.ts#L10-L11

Do you happen to have an example of such an asset? Or when one might come into existence? 

Thanks,
Tomas

### Proposed solution

N/a

**Comment by sergiou87** [comment]
In a **private** repo, create an issue or pull request and upload an image to its description. When the markdown body of that issue/PR is retrieved from the API, you will get that kind of URL for the uploaded image. I hope that helped! 😄

**Comment by tomasreimers** [comment]
Hmm, I think I'm missing something. 

When I upload to github.com, I get the following path: https://user-images.githubusercontent.com/1188925/233099814-7f480a78-17d1-445f-8ec2-5599dc98b38b.png

When I upload to GHES, I get the following path: https://HOST/storage/user/5/files/953b5f46-f8fb-4722-8c14-7d9175e658a3

I'm querying the API with GraphQL: 

```
query { 
  repository(owner: "REPO", name: "NAME") {
		issue(number: 4) {
			body,
			bodyHTML
		}
	}
}
```

Is there a different API or mechanism to upload? Do happen to have a working example?

**Comment by tomasreimers** [comment]
Also, @sergiou87, apologies, i can't seem to open this - so followed up here: 

https://github.com/desktop/desktop/issues/16560

Sorry for the dupe
