### ISSUE TITLE
Show a confirmation dialog before... Pushing to the 'main'/'master' branch

### ISSUE THREAD

**Issue by simenness** [desktop/desktop#16555]
### The feature request

"Show a confirmation dialog before... **Pushing to the 'main'/'master' branch**"

### Proposed solution

Add an option for "Show a confirmation dialog before... **Pushing to the 'main'/'master' branch**"
and of course the accompanying dialog box.

### Additional context

Nice to have for when you have those tiny changes that don't need to go through the whole PR process...

**Comment by tidy-dev** [comment]
👋 @simenness Thanks for the suggestion. Currently, GitHub Desktop implements a warning on branches with branch [protection rules setup](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule). Whether your can push is determined by how your repository is configured. GitHub Desktop is not going to be able to implement something that can bypass that. 

![CleanShot 2023-04-19 at 09 11 48](https://user-images.githubusercontent.com/75402236/233085529-2755e63b-e2e3-457c-91fc-98f05f1c2d6f.png)

**Comment by simenness** [comment]
Wasn't thinking of one that bypasses any rules... just as a friendly reminder that I/we are about to push to 'main'...

**Comment by tidy-dev** [comment]
Oh. Sorry for the misunderstanding. Still yet, Desktop's protected branch warning at the time of commit is our approach for warning users and currently do not have plans to make that warning more aggressive (like a confirmation modal).

**Comment by simenness** [comment]
Im not getting that warning though :/
![image](https://user-images.githubusercontent.com/27001067/233274234-387fd2a4-a239-4698-a35a-1f07afc2f6ad.png)

with this setting on 'main' (I was here):
![image](https://user-images.githubusercontent.com/27001067/233399168-21a42db1-a07b-4e4b-b1f2-7957557d0ddb.png)

Do I need more rules enabled to get the warning?

**Comment by tidy-dev** [comment]
I believe it is because you are added to that exception list.

**Comment by simenness** [comment]
After thorough testing these work to make it show, I have to have these three active...
![image](https://user-images.githubusercontent.com/27001067/233397365-a3c9402c-4c94-4acd-8429-2a051c11a0ae.png)
![image](https://user-images.githubusercontent.com/27001067/233397490-6892d75a-37e1-4c77-88e5-4ef9da657d78.png)


and it doesn't matter if i'm in... 
![image](https://user-images.githubusercontent.com/27001067/233398984-5420f6c1-b64c-4065-bd1e-8a63ceb6ab0e.png)
...or not

I got the...
![image](https://user-images.githubusercontent.com/27001067/233398968-2a3ccdb2-6cc2-4278-9893-d9a3de2c44cb.png)
though I still got the "[remote rejected] main -> main (protected branch hook declined)" error when pushing... as expected. 👌🏻

that's all from me.
