### ISSUE TITLE
1) Pinned repos, 2) Sort repos, or 3) Repos used most

### ISSUE THREAD

**Issue by uxrobinson** [desktop/desktop#16561]
### The feature request

3 recent repos is inadequate as it presumes that there is no need to switch to a fourth repo. Additionally, the process of selecting a new repo outside of the recent repo list means that, of course, an action is then taken with that repo, that could be for example pushing a commit, meaning that the user experience is "search for repo, select repo, perform action". At this point, the repo is added to the recent repo list, but the action has already been enacted on that repo. By adding the repo to the recent list, this then knocks a recent repo from the list, but because the action has already been performed on this now recent repo, it is more likely that the next action would need to be performed on the repo knocked from the recent repo list As such, as is often the case, the next action to be performed may or may be related to a repo in the recent repo list. Statistically, the repo that is most likely to require an action is the repo that is was the least recent to be interacted with, and the most recently interacted with repo has already been interacted with. Of course I understand that in some cases an individual may simply be working within a single repo, but if you are working on a project that is modular, this is not going to be the case. Absolutely introduce a "sort by most recent" feature, or a "pinned repos" feature, as both of these solutions enable easy access to recent repos. Where the current user experience breaks down is in that a recent repo list which is limited to 3 is always going to prioritise the repo that has already been interacted with.

### Proposed solution

1) Pinned repos allowing the user to decide which repos are important and are required for the current work in hand.  2) Sort option over all repos or all repos per account, by recent. 3) Adapt most recent repos to repos used most, meaning that GitHub Desktop just keeps a tally of average repo use, meaning that repos the user uses regularly are not automatically unseated by a quick switch and action taken on another repo which is not regularly used.

**Comment by tidy-dev** [comment]
Hi @uxrobinson. Thanks for the great feedback. I have added it to the issue we are tracking feedback on our recent repo implementation.  Just because the issue is closed does not mean we might not revisit based on user feedback. Thus, I have added your feedback there and am going to close out this. Thanks again!
