### ISSUE TITLE
Save "External Editor" for every Repository

### ISSUE THREAD

**Issue by nghuyy** [desktop/desktop#16564]
### The feature request

Save "External Editor" for every Repository replace Global config
Some project using Android Studio and some using VS Code or Webstorm, we lost more time to change this by click Option and select Another editor

### Proposed solution

Save config in .ghdesktop file for every repository, or another solution

**Comment by tidy-dev** [comment]
@nghuyy Thanks for the suggestion. I have added your feedback to the tracking issue.
