### ISSUE TITLE
Open Project in IDE

### ISSUE THREAD

**Issue by Airn5475** [desktop/desktop#16565]
### The feature request

I love GitHub Desktop and often start there when working with a project.  I am a .NET Developer and use Visual Studio as my IDE.
If I start with GitHub Desktop, to open a Solution (.sln) into Visual Studio, I hit "Show in Explorer" and then double click the .sln file to fire it up.  While not a big deal, it would be nice to not have to open Windows Explorer.

### Proposed solution

Would it be possible for Desktop to identity projects/files and offer the option to "Open in...."?
If my repo has an .sln file could Desktop be smart enough to suggest "Open in Visual Studio"?

**Comment by steveward** [comment]
Thanks for the feedback @Airn5475, we are tracking this in https://github.com/desktop/desktop/issues/12946 so I'm going to reference this issue there and close this out.
