### ISSUE TITLE
Github Desktop not asking for GPG key passphrase

### ISSUE THREAD

**Issue by Com6235** [desktop/desktop#16569]
### The problem

When signing commits with GPG key is enabled, github desktop doesn't ask for a passphrase, so I'm getting error: 
error: gpg failed to sign the data
fatal: failed to write commit object

### Release version

3.2.1

### Operating system

Windows 10 64-bit

### Steps to reproduce the behavior

1. Enable signing commits with GPG key
2. Make a change in a project
3. Open Github Desktop and try to commit
4. Here you are!

### Log files

(The error was parsed as 39: null)
2023-04-20T15:24:25.964Z - info: [ui] [Timing] Action 'create commit' for 'Com6235/buscript' took 0.552s
2023-04-20T15:26:56.608Z - error: [ui] `git commit -F -` exited with an unexpected code: 128.
stderr:
error: gpg failed to sign the data
fatal: failed to write commit object

**Comment by steveward** [comment]
@Com6235 thanks for the issue. GPG signing isn't fully supported in GitHub Desktop, but a user wrote a [helpful guide](https://gist.github.com/paolocarrasco/18ca8fe6e63490ae1be23e84a7039374) that walks through how to get it working. I hope that helps!

**Comment by NitkarshChourasia** [comment]
Good stuff.
