### ISSUE TITLE
stash of branch is lost if coming back to it is aborted because of unresolved conflicts

### ISSUE THREAD

**Issue by kaelyavel** [desktop/desktop#16577]
### The problem

When you are on branch A that has changes that aren't commited and decide to leave the branch for another branch B without commiting them but by letting Github Desktop stash them automatically, you actually lose them if you try to comeback on branch A from branch B if this one had unresolved conflicts and the branch change haven been aborted because of that.

(You find out that you lost the stashed changes on branch A after resolving the conflicts on branch B and switch to branch A again).

Normally, when you leave branch A with automatically stashed changes for branch B, and comeback to branch A, you find your changes still stashed. But because of that attempted return from B to A that failed due to the unresolved conflicts on B, after resolving the conflicts, you find out that you lost your stash on branch A.

I experienced this issue multiple times.

### Release version

3.2.1

### Operating system

Windows 10 21H2 19044.2846

### Steps to reproduce the behavior

- Leave branch A with uncommitted changes that will be automatically stashed for branch B
- Somehow, make branch B have conflicts and don't resolve them
- Try to go back to branch A from branch B and you will be prompted with a message that says that it's impossible without resolving the conflicts
- Resolve the conflicts on branch B
- Leave branch B for branch A
- You'll find that your automatically stashed changes have been lost

### Additional context

It happened to me several times.

**Comment by steveward** [comment]
Thanks for the report @kaelyavel. I'll take a look to see if I can reproduce this behavior. We should be able to recover the stash -- you will need to find the log file from the day this happened. You can access the log by going to Help > Show Logs in Finder (macOS) or Explorer (Windows).

Then you will want to search for a line like this:

` [ui] Dropped stash 'b947c54873415d875d5e4e0d941c443716e1c81e' associated with main`

You can then copy that SHA and run the following command from the command line:

`git stash apply b947c54873415d875d5e4e0d941c443716e1c81e`

That should recover the lost changes. Let me know if that helps.

**Comment by kaelyavel** [comment]
Hello @steveward ,

Thank you very much for your answer.

I checked the logs and found three lines of that type among the following block of lines : 

```
2023-04-20T16:25:47.019Z - info: [ui] [Timing] Action 'stash and checkout' for 'thes/hub' took 47.211s
2023-04-20T16:32:52.818Z - info: [ui] [Timing] Action 'create commit' for 'thes/hub' took 0.021s
2023-04-20T16:34:01.027Z - info: [ui] [AppStore. _dropStashEntry] dropped stash with commit id 77dda55c0ce010aefcb215c671a1eb77e6301641
2023-04-20T16:34:09.015Z - info: [ui] [AppStore. _dropStashEntry] dropped stash with commit id c4ad0f2899189a9c4adbba674e82d594df59a79d
2023-04-20T16:34:12.301Z - info: [ui] [AppStore. _dropStashEntry] dropped stash with commit id 0db27c59f4de9d4a1f69ec4d730fcb77ae08e684
2023-04-20T16:36:44.134Z - info: [ui] [Timing] Action 'checkout branch from list' for 'thes/hub' took 0.001s
2023-04-20T16:36:50.165Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: hub - kaelyavel (has token)
2023-04-20T16:36:50.538Z - info: [ui] [createDesktopStashEntry] a stash was created successfully but exit code 1 reported. stderr: 
```
I actually didn't search to retrieve the stash because I cloned the project from scratch again as I recently updated the dev branch and my stashed changes weren't really big.

Thank you for much for the tip. I'll make sure to use it if I ever forget to resolve my conflicts again before wanting to switch back to a branch that has automatically stashed changes.

**Comment by steveward** [comment]
@kaelyavel I tried to reproduce this, but have unsuccessful so far. I resolved conflicts on Branch B but my stashed changes on A were still there when I switched branches. It's possible I missed a step or you hit an edge case, so let me know if you run into this again or are able to reliably reproduce it. I'm going to close this out for now, thanks again for the report.
