### ISSUE TITLE
Eclipse Window Builder has an empty pallete

### ISSUE THREAD

**Issue by RayWinestone** [desktop/desktop#16574]
### The problem

Just installed latest verison of Eclipse and Window Builder but the pallete is empty (see attachments)
<img width="943" alt="Screenshot 2023-04-21 at 09 36 10" src="https://user-images.githubusercontent.com/131442337/233594881-70e42253-dac1-418b-8d7c-b8cb80af9cf1.png">
<img width="1006" alt="Screenshot 2023-04-21 at 09 38 19" src="https://user-images.githubusercontent.com/131442337/233594899-3004a19c-7081-4743-a450-f945708ba951.png">

### Release version

Version 3.2.1 (x64)

### Operating system

OSX Ventura 13.2.1

**Comment by steveward** [comment]
@RayWinestone this issue tracker is for [GitHub Desktop](http://desktop.github.com), it looks like you were looking for support for a different project hosted on GitHub, I'd try opening an issue there: https://github.com/eclipse/windowbuilder.
