### ISSUE TITLE
Uninstalling doesn't fix protocol registry key

### ISSUE THREAD

**Issue by stealthgyro** [desktop/desktop#1657]
I was having a huge issue due to the fact the new electron build doesn't have a dark mode so when I went to use the old version again I had to actually edit the registry key under

Computer\HKEY_CLASSES_ROOT\x-github-client\shell\open\command

to use the GitHub classic.

**Comment by shiftkey** [comment]
@stealthgyro thanks for the context. Not sure how best to do this, given the [declarative syntax](https://github.com/desktop/desktop/blob/3dc8738e711131047f9973398a5dac08e2cd206e/script/build#L89-L90) for protocol handlers is macOS-only and we have to do it at [runtime](https://github.com/desktop/desktop/blob/3af2eee3bcdafe8992da4f7f08f75ce7db8a7699/app/src/main-process/main.ts#L98) on Windows.

**Comment by bfred-it** [comment]
```sh
brew install duti
duti -s com.github.GitHub x-github-client
```

I had also deleted GitHub app support files and removed some file associations with `lsregister -u ~/.Trash/GitHub\ Desktop.app`, but that might not be necessary

Thanks to: 
http://krypted.com/mac-security/lsregister-associating-file-types-in-mac-os-x/
https://github.com/moretension/duti

**Comment by joshaber** [comment]
Now that [GitHub Desktop 1.0](https://github.com/blog/2437-announcing-github-desktop-1-0) is out, we don't have any plans to support the old protocol.

Please feel free to open issues for bugs you find or features you'd like to see in the new app!
