### ISSUE TITLE
white space problem in differences between local files and remote

### ISSUE THREAD

**Issue by florinbuzec** [desktop/desktop#16575]
### The problem

In the 'Current repository' list of changed files there are (mostly bash files) that apeear as different from GitHub repository versions because of some whitespace interpretation or something.
I must say my Git config contains 'LF' on as end of line separator.

### Release version

3.2.1 (x64)

### Operating system

Windows 10 64-bit

### Steps to reproduce the behavior

1. Select repository
2. In "Changes" there are xx changed files that have no content changes
3. Selecting Diff options -> x Hide whitespace changes will display that "Only whitespace changes found"
There must be a way to see exactly what are exactly the changes that it sees

### Screenshots

![Screenshot_124](https://user-images.githubusercontent.com/108538975/233611512-5223e3cc-8b28-409b-bae5-98848acfda29.png)

### Additional context

[~/.gitconfig]

```ini
# ...
[core]
        autocrlf = false
```

**Comment by tidy-dev** [comment]
:wave: @florinbuzec Does this file have changes that are not white space changes (spaces, tabs, empty lines)?

It would seem you just want to uncheck the "Hide whitespace changes" if you are wanting to see all changes to the file (including whitespaces). But, maybe I am misunderstanding.

**Comment by florinbuzec** [comment]
I think the only differences is the chmod of the executables.
Already having the files with LF end line (instead of CRLF as in many cases it would throw this difference), there is no other difference than probably the chmod from my local version and the repository internal structure.

**Comment by steveward** [comment]
I'm going to group this into https://github.com/desktop/desktop/issues/11685 which is a previously reported issue of this behavior.
