### ISSUE TITLE
Reopen Feature Request 15986 and 15987

### ISSUE THREAD

**Issue by johnottone** [desktop/desktop#16583]
### The feature request

Recently, I posted a few feature requests that were quickly closed down for the following reasons.

"given the small number of users who would make use of a feature that is not core to interacting with git or GitHub"

"this is likely of low use case as the vast majority of our users have less than 5 repositories and those that have more, do not delete in high frequency"

Am I the only person using Github Desktop that has more than 5 repositories? Am I the only person that wants to see the exact dates I cloned a repository, or the date that I removed a repository from my local machine? I was just asking for some checkboxes and maybe a way to favorite or pin a few repos in that unmanageable left-side List of repos. Mainly to manage the repo list a little easier. I mean if there is no support for such features, then I will gladly admit I was wrong and will start work on my own client to manage my github repositories, but I dont think it was right to close my request within such a short period before the community even got a chance to see the post. I mean it was my fault for posting it at the hour in which I did, but it wasnt even up for 4 hours before it was closed. 

[Original Feature Request #15986](https://github.com/desktop/desktop/issues/15986)
You already are keeping a text file of this log, why not just display the actions to users so they can easily keep track of when and what they are doing in regards to a history / action / command log.
[Original Feature Request #15987](https://github.com/desktop/desktop/issues/15987)
What list is complete without checkboxes to select / manage multiples? Or pin a few items to the top of the list as favorites, or priorities. 

### Proposed solution

Please see the original post 

[Original Feature Request #15986](https://github.com/desktop/desktop/issues/15986)
[Original Feature Request #15987](https://github.com/desktop/desktop/issues/15987)

### Additional context

[Original Feature Request #15986](https://github.com/desktop/desktop/issues/15986)
[Original Feature Request #15987](https://github.com/desktop/desktop/issues/15987)

**Comment by niik** [comment]
Hey @johnottone. I understand that you're frustrated but be aware that your language, and the repeated opening of a previously closed issue is considered a violation of the [Desktop Code of Conduct](https://github.com/desktop/desktop/blob/development/CODE_OF_CONDUCT.md) as it was unprofessional and derogatory. You may consider this an official warning.

I'm going to close this issue and point you back to the answer given in the original issue. Closing an issue is a strong signal that we're not planning on working on it in the near term. We re-evaluate issues (even closed ones) on an ongoing basis and the question at hand here isn't the number of repositories that our users manage but whether or not the team believes this particular feature should be a priority over other work and we don't believe it should. When a member of the Desktop team responds to an issue they speak for all of us.

If you have actionable feedback or a additional context that you believe would cause us to reconsider prioritising the ability to delete more than one repository at a time feel free to add that to the original issue while refraining from unprofessional language.

**Comment by johnottone** [comment]
@niik 

What language? I didn't say anything out of line. I wasn't derogatory to anyone. This was a legitimate feature request that was closed before anyone even had a chance to look at it... All I was doing was asking that it be opened so the community would have a chance to see it. And this is the only time I have ever asked to reopen anything. And all I did was post a link to them. I didn't reopen them at all. I was asking YOU to reopen them so the community would be able to see them and comment on them. And I do have actionable feedback. I posted screenshots in the feature request. 

Did you read the feature requests? You yourself have 61 repositories. Im sure you may only have a subset of those in your Giuthub Desktop, but for me I have a repository for each customer. I have over 5 customer. Also, When I am doing research, I have to clone or fork a repository, such as the MSIX tools and installer libraries. Its not a huge ask for such a standard feature. And my requests were well thought out and well planned, with mock-ups and screenshots. They took a quite a bit of research, and I posted everything needed, and as a developer myself,  would be pretty easy to implement and would save every user that DOES have over 5 repositories a great deal of time. The other moderator said that the majority of users have less than 5 repositories and that was the reason he shut my request down. I'm sorry but every developer I know has way more than 5 repos, so... I thought I would ask you to reopen the closed feature requests and give the community a chance to look it over and discuss it and either agree or disagree. My problem is that my request was never given that opportunity. Me asking the moderator(s) to reopen something ONE TIME is not the same thing as "repeated opening of a previously closed issue". It is a plea for someone else to review the request on its merit. Why do you have a feature request forum if you're not going to let anyone even read someone else request? 

I am pretty confident, that whether or not you use my request or not, eventually, there will be checkboxes added to the repository list, so users can manage multiple repos at one time. Its a valid and very standard UI feature. It's not like I was asking for the moon.
