### ISSUE TITLE
Unable to publish the repsitory to Git

### ISSUE THREAD

**Issue by ArchanaHandral** [desktop/desktop#16602]
### The problem

While trying to publish repo from TFS to Git via GitHub Desktop I am getting Error that "I do not have permission to create Repo or  Repo exists". Same I am able to publish from Visual Studio.

### Release version

3.2.1

### Operating system

Windows 10 Enterprise

### Screenshots

![image](https://user-images.githubusercontent.com/87002637/234500885-84ef3bd9-a624-46c5-8922-cc4fc34c8229.png)

**Comment by sergiou87** [comment]
Hello! Without the logs it's hard to understand what could be the problem, but in this case it could be you're not logged in GitHub.com (from Desktop go to `Settings` -> `Accounts`)? That's the only reason I can think of if you're able to create it from Visual Studio 😕 

If you could attach your logs I can take a look in case there is anything else going on 🤔 

Thank you!
