### ISSUE TITLE
[macOS] Alacritty was disappeared from the shell list 

### ISSUE THREAD

**Issue by ansidev** [desktop/desktop#16614]
### The problem

Alacritty was disappereared from the shell list.

The root cause is Alacritty changed its bundled name ID since version 0.11.0

https://github.com/alacritty/alacritty/blob/ead65221ebe06ff5689e65b866d735d4365d0e9e/CHANGELOG.md?plain=1#L82

### Release version

3.2.2 and other versions (because of the root cause)

### Operating system

macOS

### Steps to reproduce the behavior

1. Install latest versions of GitHub Desktop and Alacritty. 
2. Open Settings, and go to the Integrations > Shell.

**Comment by steveward** [comment]
Thanks for the report @ansidev! If you'd like to contribute a PR to fix this you should just need to update [this line](https://github.com/desktop/desktop/blob/8c57df32ad48c71750f694a63e4c8cf907e41dad/app/src/lib/shells/darwin.ts#L38).

**Comment by sukhiboi** [comment]
I created a PR to fix this. Could you please review it.

**Comment by lhvy** [comment]
I'll make a PR for this with the suggested approach outlined [here](https://github.com/desktop/desktop/pull/16660#discussion_r1188475748).
