### ISSUE TITLE
Pages not loading

### ISSUE THREAD

**Issue by Djoudjou59** [desktop/desktop#16611]
### The problem

After deleting the HTML index of the "Main" branch and replacing it, Pages does not want to open my site anymore.

### Release version

3.2.1

### Operating system

Windows 11

### Steps to reproduce the behavior

Click on : https://djoudjou59.github.io/Jeracraft-Survival-Map/

### Screenshots

![image](https://user-images.githubusercontent.com/129606232/235069764-700c1778-db4c-43b8-a162-d3ecd40aae08.png)

**Comment by sergiou87** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
