### ISSUE TITLE
"Changed files" label is off-center

### ISSUE THREAD

**Issue by jspahrsummers** [desktop/desktop#1662]
### Description

<img width="252" alt="screen shot 2017-05-20 at 11 53 33" src="https://cloud.githubusercontent.com/assets/432536/26275190/24c3592c-3d53-11e7-9ccd-311189d1c1c1.png">

Looks like the "changed files" label is centered _between_ the checkbox and the divider, when I would expect the label to be centered between the divider and the edge of the window.

### Version

**GitHub Desktop version:** 0.5.5
**OS version:** macOS 10.12.4

### Steps to Reproduce

1. Install for the first time, and set up
1. Add an existing repository to the app

**Comment by niik** [comment]
I bet this is my doing with the work I was doing to associate the label with the checkbox. I'll take another look at it. Thanks @jspahrsummers!

**Comment by niik** [comment]
Turns out my memory is shit, I've already fixed this (although it's not merged yet) in #1289, more specifically in https://github.com/desktop/desktop/commit/ec54fa1bea22fb18d66f662394864f5bfd3107fc#diff-3345dc8f5a42d8f53854a19ca571b542R24

I'll close out this issue once #1289 lands
