### ISSUE TITLE
Deleted Folders cloned from Github Desktop

### ISSUE THREAD

**Issue by jesszheng124** [desktop/desktop#16620]
### The problem

When I attempt to delete files cloned from the Github Desktop app, they reappear in the trash for some reason. Even after deleting them again, they reappear in the trash days later. Could you let me know what I should do?

### Release version

3.2.2

### Operating system

MacOS Ventura 13.3.1

**Comment by steveward** [comment]
@jesszheng124 Thanks for the issue. Are you discarding the files/changes in GitHub Desktop, or deleting them in Finder? When you say "even after deleting them again", are you saying that they reappear in the trash after you have already emptied the trash?

**Comment by jesszheng124** [comment]
Yes I meant to say they reappear in the trash after I already emptied the trash!

**Comment by steveward** [comment]
If the files were previously committed then they would still exist in your repository's history, so if you checkout out another branch that still had those files they would reappear in Finder. I'm not sure why files would reappear in the Trash, though.

**Comment by jesszheng124** [comment]
Is there a way to delete this issue from desktop/desktop repo or at least make the visibility private? I don't think this is issue is helpful for anyone and I like to keep things like this private!

**Comment by steveward** [comment]
@jesszheng124 I can delete the issue, although it isn't something that we generally do unless there is specific content that we need to remove. You can edit previous replies or the issue itself if there's something specific you would like to remove.

**Comment by jesszheng124** [comment]
I would like the entire issue to be deleted! Thank you!

**Comment by jesszheng124** [comment]
Please have this entire issue deleted from this support repo! Thank you!
