### ISSUE TITLE
This file is empty 

### ISSUE THREAD

**Issue by codeproff** [desktop/desktop#16630]
### The problem

I am writing code in vs code but the git is not showing the code rather it is giving me "This file is empty"
![Screenshot (27)](https://user-images.githubusercontent.com/132269968/235627622-87b01cf9-77e9-4cf0-9ab6-54418191e3df.png)

### Release version

Version 3.2.2 (x64)

### Operating system

Windows 11

**Comment by steveward** [comment]
@codeproff have you saved the changes in VSCode? They won't appear in GitHub Desktop until they are saved in VSCode. VSCode also has an AutoSave functionality you can enable from the File menu if that's helpful.

**Comment by codeproff** [comment]
Thanks for the help.
