### ISSUE TITLE
The default directory for cloning should be %USERPROFILE%/Documents/GitHub

### ISSUE THREAD

**Issue by SaschaNaz** [desktop/desktop#1663]
### Description

When you first clone a repo the client gives `%USERPROFILE% as a default directory (that is, `C:\\Users\\(username)\\`) whereas the previous client gave `%USERPROFILE%/Documents/GitHub`.

### Version

**GitHub Desktop version:** 0.5.5

**OS version:** Windows 10.0.15063

### Steps to Reproduce

1. Clone a repo
1. See what the client gives for default directory

**Expected behaviour:** `%USERPROFILE%/Documents/GitHub` (that is, `C:\\Users\(username)\Documents\GitHub`)

**Actual behaviour:** Just %USERPROFILE%

**Reproduces how often:** When you first clone a repo after installation (or update?). After cloning once it seems to remember previous directory.

**Comment by zhuowei** [comment]
The default path is specified on https://github.com/desktop/desktop/blob/master/app/src/ui/lib/default-dir.ts#L7 . It doesn't look too hard to change: is the old Mac app's default path ~/Documents/GitHub as well?

**Comment by shiftkey** [comment]
>  is the old Mac app's default path ~/Documents/GitHub as well?

@joshaber do you recall what the fallback value is for Classic MacOS?

**Comment by iAmWillShepherd** [comment]
I think this enhancement should also allow the user to specify a default location.

**Comment by shiftkey** [comment]
> I think this enhancement should also allow the user to specify a default location.

Even if we update this setting behind the scenes as soon as the user chooses a different folder when creating a repository or cloning a repository?

**Comment by shiftkey** [comment]
@iAmWillShepherd my gut feel is to just change this behaviour (if we can agree on a common location) without going through the process of making it a configurable setting - because we should update this whenever you change it as part of your workflow...

**Comment by joshaber** [comment]
>@joshaber do you recall what the fallback value is for Classic MacOS?

It was `~/GitHub`.

**Comment by jrogby** [comment]
Why have the different behavior running on macos than on windows? I think it should be possible to set default folder in settings (with alternative of using last used path if wanted). I cant grasp why it should be a good idea defaulting to a specific folder, that is very much a user specific setting!
