### ISSUE TITLE
'View on Github' opening current branch

### ISSUE THREAD

**Issue by alexius544** [desktop/desktop#16644]
### The feature request

Currently, if I am in a separate branch, the 'View on Github' button opens the primary branch. Perhaps, a toggle in the settings for whether or not it shall open in the active branch or only in the main could be beneficial :)

### Proposed solution

It will make it easier to get to the current branch, eliminating the need to change it over... might just be me though

**Comment by alexius544** [comment]
On MacOS

**Comment by steveward** [comment]
Thanks for the issue @alexius544. The `View on GitHub` option is intended to just open the repository on GitHub (with the default branch). You can go to `Branch` > `View Branch on GitHub` to view the current branch. I hope that helps!
