### ISSUE TITLE
Ignore Function not works even add specific path into ignore list

### ISSUE THREAD

**Issue by Mark-Zhang-007** [desktop/desktop#16649]
### The problem

The file still in the changed list even add it into ignore file list.

### Release version

Version 3.2.3 (x64)

### Operating system

Windows 10

**Comment by steveward** [comment]
@Mark-Zhang-007 thanks for the issue. If the files have been previously committed you will need to run `git rm --cached <filename>` from the command line to ignore the file.  See [this guide](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files) for details. Let me know if you have any further questions.
