### ISSUE TITLE
Reactivate "Closed" issue - Ghost Deleted Branches (GitHub Desktop)

### ISSUE THREAD

**Issue by modernmusician** [desktop/desktop#16656]
### The problem

This issue is currently still active and needs to be reclassified from "Closed":

https://github.com/desktop/desktop/issues/5893

### Release version

3.2.3 (arm64)

### Operating system

Mac Ventura

**Comment by steveward** [comment]
Thanks for the feedback @modernmusician, but in the future please don't open issues asking to reopen existing issues. We still track feedback even if an issue is closed.
