### ISSUE TITLE
Transparent .webp difference displayed incorrectly

### ISSUE THREAD

**Issue by AtaTrkgl** [desktop/desktop#16657]
### The problem

When displaying the difference of a .webp file with transparency, all of the methods except "2-up" shows the older version behind the new one.

Check the screenshots for a more clear example

### Release version

Version 3.2.3 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Create a .webp file with transparent background
2. Change the file (pixels with `alpha != 0`)
3. View the differences from the GitHub Desktop app.

### Screenshots

- **2-up**
   ![image](https://user-images.githubusercontent.com/27922283/236640468-1bd5b339-7e88-4580-a315-1e9e600cb06d.png)
- **Swipe**
   ![image](https://user-images.githubusercontent.com/27922283/236640478-aec6b3d8-489c-4bf3-a0d0-b56eb36c0164.png)

### Additional context

You can check the commit I had the issue with: https://github.com/espale-studios/website/commit/43f2fa09f98f67f878593b4db7f358ce6fdd5590

**Comment by steveward** [comment]
Thanks for the report @AtaTrkgl, I'll mark this as a bug for the team to investigate.

**Comment by Psychpsyo** [comment]
This also affects PNGs:

![image](https://github.com/desktop/desktop/assets/60073468/54bbd71d-0c01-40d0-8498-3ccacc0f25a4)

![image](https://github.com/desktop/desktop/assets/60073468/bf5d9a02-0821-48df-a375-321d7c93b6f1)

**Comment by vchelaru** [comment]
I keep seeing updates, they keep having bug fixes but *not* this one :(

This is making png diffing nearly impossible for the games I'm working on.

**Comment by Psychpsyo** [comment]
I am going to look into this and open a PR.
