### ISSUE TITLE
Referencing an issue in commit text behind the code viewer

### ISSUE THREAD

**Issue by joexn** [desktop/desktop#16650]
### The problem

Referencing an issue in commit text shows the autocomplete popup behind the code viewer so you can't see it.

### Release version

Version 3.2.3 (arm64)

### Operating system

macOS 13.1

### Steps to reproduce the behavior

Enter (#) in the commit title box and the autocomplete which lists open issues to reference is behind the code viewer.

### Screenshots

<img width="309" alt="Screenshot 2023-05-05 at 12 47 16" src="https://user-images.githubusercontent.com/17342019/236450217-c7866577-7397-4deb-9d32-23def04bb6e1.png">

**Comment by sergiou87** [comment]
It seems #16425 caused this issue. I don't see a way of fixing this while keeping the fixes introduced in that PR, other than extracting the autocomplete popup out of that component, maybe using portals as we do with tooltips?

**Comment by sdsoldi** [comment]
Same on windows 3.2.3
