### ISSUE TITLE
Starred rep's and main menu in Github Desktop 

### ISSUE THREAD

**Issue by SantaLaMuerte** [desktop/desktop#16653]
### The feature request

Plz add a feature to see and clone starred repos (with lists) and maybe some main menu like in mobile app . Thanks a lot for contributing such great project.  Beta view and options is extra helpfull!

### Proposed solution

1. Add a new button panel/menu with starred repos (with search and list view) 
2. Create a main menu with homepage - with some *For you* And *Followerd* folders. Thx
3. And plz add subfolders/sublists in lists

### Additional context

:shipit:

**Comment by steveward** [comment]
Thanks for the feedback @hastalamuerte. We likely won't implement starring features directly into GitHub Desktop in the near term, but you can quickly clone a starred repository from github.com using the `Code` > `Local` > `Open with Desktop`

>And plz add subfolders/sublists in lists

It sounds like you're interested in a tree view, which we are tracking feedback for in https://github.com/desktop/desktop/issues/2417. You can follow along there for updates about this.
