### ISSUE TITLE
Windows 11- Github Desktop fails to clone repository

### ISSUE THREAD

**Issue by k1tsu3** [desktop/desktop#16662]
### The problem

I can't clone a repository in Github Desktop on my Windows 11

### Release version

GitHub Desktop 3.2.3 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1.Go to 'Clone a repository'
2.Click on 'any private or public repository'
3.Click clone
4.Github Desktop errors out at 100% completion.

### Log files

2023-05-07T23:45:18.088Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/tegal1337/CiLocks.git - k1tsu3 (has token)
2023-05-07T23:45:26.338Z - info: [ui] Executing clone: git -c credential.helper= -c init.defaultBranch=main clone --recursive --progress -- https://github.com/tegal1337/CiLocks.git C:\Users\nicole\OneDrive\Documents\MyFiles\GItHub\New folder\CiLocks (took 8.241s)
2023-05-07T23:45:26.346Z - error: [ui] `git -c credential.helper= -c init.defaultBranch=main clone --recursive --progress -- https://github.com/tegal1337/CiLocks.git C:\Users\nicole\OneDrive\Documents\MyFiles\GItHub\New folder\CiLocks` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\Users\nicole\OneDrive\Documents\MyFiles\GItHub\New folder\CiLocks'...
remote: Enumerating objects: 389, done.        
remote: Counting objects:   0% (1/160)        
remote: Counting objects:   1% (2/160)        
remote: Counting objects:   2% (4/160)        
remote: Counting objects:   3% (5/160)        
remote: Counting objects:   4% (7/160)        
remote: Counting objects:   5% (8/160)        
remote: Counting objects:   6% (10/160)        
remote: Counting objects:   7% (12/160)        
remote: Counting objects:   8% (13/160)        
remote: Counting objects:   9% (15/160)        
remote: Counting objects:  10% (16/160)        
remote: Counting objects:  11% (18/160)        
remote: Counting objects:  12% (20/160)        
remote: Counting objects:  13% (21/160)        
remote: Counting objects:  14% (23/160)        
remote: Counting objects:  15% (24/160)        
remote: Counting objects:  16% (26/160)        
remote: Counting objects:  17% (28/160)        
remote: Counting objects:  18% (29/160)        
remote: Counting objects:  19% (31/160)        
remote: Counting objects:  20% (32/160)        
remote: Counting objects:  21% (34/160)        
remote: Counting objects:  22% (36/160)        
remote: Counting objects:  23% (37/160)        
remote: Counting objects:  24% (39/160)        
remote: Counting objects:  25% (40/160)        
remote: Counting objects:  26% (42/160)        
remote: Counting objects:  27% (44/160)        
remote: Counting objects:  28% (45/160)        
remote: Counting objects:  29% (47/160)        
remote: Counting objects:  30% (48/160)        
remote: Counting objects:  31% (50/160)        
remote: Counting objects:  32% (52/160)        
remote: Counting objects:  33% (53/160)        
remote: Counting objects:  34% (55/160)        
remote: Counting objects:  35% (56/160)        
remote: Counting objects:  36% (58/160)        
remote: Counting objects:  37% (60/160)        
remote: Counting objects:  38% (61/160)        
remote: Counting objects:  39% (63/160)        
remote: Counting objects:  40% (64/160)        
remote: Counting objects:  41% (66/160)        
remote: Counting objects:  42% (68/160)        
remote: Counting objects:  43% (69/160)        
remote: Counting objects:  44% (71/160)        
remote: Counting objects:  45% (72/160)        
remote: Counting objects:  46% (74/160)        
remote: Counting objects:  47% (76/160)        
remote: Counting objects:  48% (77/160)        
remote: Counting objects:  49% (79/160)        
remote: Counting objects:  50% (80/160)        
remote: Counting objects:  51% (82/160)        
remote: Counting objects:  52% (84/160)        
remote: Counting objects:  53% (85/160)        
remote: Counting objects:  54% (87/160)        
remote: Counting objects:  55% (88/160)        
remote: Counting objects:  56% (90/160)        
remote: Counting objects:  57% (92/160)        
remote: Counting objects:  58% (93/160)        
remote: Counting objects:  59% (95/160)        
remote: Counting objects:  60% (96/160)        
remote: Counting objects:  61% (98/160)        
remote: Counting objects:  62% (100/160)        
remote: Counting objects:  63% (101/160)        
remote: Counting objects:  64% (103/160)        
remote: Counting objects:  65% (104/160)        
remote: Counting objects:  66% (106/160)        
remote: Counting objects:  67% (108/160)        
remote: Counting objects:  68% (109/160)        
remote: Counting objects:  69% (111/160)        
remote: Counting objects:  70% (112/160)        
remote: Counting objects:  71% (114/160)        
remote: Counting objects:  72% (116/160)        
remote: Counting objects:  73% (117/160)        
remote: Counting objects:  74% (119/160)        
remote: Counting objects:  75% (120/160)        
remote: Counting objects:  76% (122/160)        
remote: Counting objects:  77% (124/160)        
remote: Counting objects:  78% (125/160)        
remote: Counting objects:  79% (127/160)        
remote: Counting objects:  80% (128/160)        
remote: Counting objects:  81% (130/160)        
remote: Counting objects:  82% (132/160)        
remote: Counting objects:  83% (133/160)        
remote: Counting objects:  84% (135/160)        
remote: Counting objects:  85% (136/160)        
remote: Counting objects:  86% (138/160)        
remote: Counting objects:  87% (140/160)        
remote: Counting objects:  88% (141/160)        
remote: Counting objects:  89% (143/160)        
remote: Counting objects:  90% (144/160)        
remote: Counting objects:  91% (146/160)        
remote: Counting objects:  92% (148/160)        
remote: Counting objects:  93% (149/160)        
remote: Counting objects:  94% (151/160)        
remote: Counting objects:  95% (152/160)        
remote: Counting objects:  96% (154/160)        
remote: Counting objects:  97% (156/160)        
remote: Counting objects:  98% (157/160)        
remote: Counting objects:  99% (159/160)        
remote: Counting objects: 100% (160/160)        
remote: Counting objects: 100% (160/160), done.        
remote: Compressing objects:   1% (1/79)        
remote: Compressing objects:   2% (2/79)        
remote: Compressing objects:   3% (3/79)        
remote: Compressing objects:   5% (4/79)        
remote: Compressing objects:   6% (5/79)        
remote: Compressing objects:   7% (6/79)        
remote: Compressing objects:   8% (7/79)        
remote: Compressing objects:  10% (8/79)        
remote: Compressing objects:  11% (9/79)        
remote: Compressing objects:  12% (10/79)        
remote: Compressing objects:  13% (11/79)        
remote: Compressing objects:  15% (12/79)        
remote: Compressing objects:  16% (13/79)        
remote: Compressing objects:  17% (14/79)        
remote: Compressing objects:  18% (15/79)        
remote: Compressing objects:  20% (16/79)        
remote: Compressing objects:  21% (17/79)        
remote: Compressing objects:  22% (18/79)        
remote: Compressing objects:  24% (19/79)        
remote: Compressing objects:  25% (20/79)        
remote: Compressing objects:  26% (21/79)        
remote: Compressing objects:  27% (22/79)        
remote: Compressing objects:  29% (23/79)        
remote: Compressing objects:  30% (24/79)        
remote: Compressing objects:  31% (25/79)        
remote: Compressing objects:  32% (26/79)        
remote: Compressing objects:  34% (27/79)        
remote: Compressing objects:  35% (28/79)        
remote: Compressing objects:  36% (29/79)        
remote: Compressing objects:  37% (30/79)        
remote: Compressing objects:  39% (31/79)        
remote: Compressing objects:  40% (32/79)        
remote: Compressing objects:  41% (33/79)        
remote: Compressing objects:  43% (34/79)        
remote: Compressing objects:  44% (35/79)        
remote: Compressing objects:  45% (36/79)        
remote: Compressing objects:  46% (37/79)        
remote: Compressing objects:  48% (38/79)        
remote: Compressing objects:  49% (39/79)        
remote: Compressing objects:  50% (40/79)        
remote: Compressing objects:  51% (41/79)        
remote: Compressing objects:  53% (42/79)        
remote: Compressing objects:  54% (43/79)        
remote: Compressing objects:  55% (44/79)        
remote: Compressing objects:  56% (45/79)        
remote: Compressing objects:  58% (46/79)        
remote: Compressing objects:  59% (47/79)        
remote: Compressing objects:  60% (48/79)        
remote: Compressing objects:  62% (49/79)        
remote: Compressing objects:  63% (50/79)        
remote: Compressing objects:  64% (51/79)        
remote: Compressing objects:  65% (52/79)        
remote: Compressing objects:  67% (53/79)        
remote: Compressing objects:  68% (54/79)        
remote: Compressing objects:  69% (55/79)        
remote: Compressing objects:  70% (56/79)        
remote: Compressing objects:  72% (57/79)        
remote: Compressing objects:  73% (58/79)        
remote: Compressing objects:  74% (59/79)        
remote: Compressing objects:  75% (60/79)        
remote: Compressing objects:  77% (61/79)        
remote: Compressing objects:  78% (62/79)        
remote: Compressing objects:  79% (63/79)        
remote: Compressing objects:  81% (64/79)        
remote: Compressing objects:  82% (65/79)        
remote: Compressing objects:  83% (66/79)        
remote: Compressing objects:  84% (67/79)        
remote: Compressing objects:  86% (68/79)        
remote: Compressing objects:  87% (69/79)        
remote: Compressing objects:  88% (70/79)        
remote: Compressing objects:  89% (71/79)        
remote: Compressing objects:  91% (72/79)        
remote: Compressing objects:  92% (73/79)        
remote: Compressing objects:  93% (74/79)        
remote: Compressing objects:  94% (75/79)        
remote: Compressing objects:  96% (76/79)        
remote: Compressing objects:  97% (77/79)        
remote: Compressing objects:  98% (78/79)        
remote: Compressing objects: 100% (79/79)        
remote: Compressing objects: 100% (79/79), done.        
Receiving objects:   0% (1/389)
Receiving objects:   1% (4/389)
Receiving objects:   2% (8/389)
Receiving objects:   3% (12/389)
Receiving objects:   4% (16/389)
Receiving objects:   5% (20/389)
Receiving objects:   6% (24/389)
Receiving objects:   7% (28/389)
Receiving objects:   8% (32/389)
Receiving objects:   9% (36/389)
Receiving objects:   9% (37/389), 1.11 MiB | 1.08 MiB/s
Receiving objects:  10% (39/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  11% (43/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  12% (47/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  13% (51/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  14% (55/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  15% (59/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  16% (63/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  17% (67/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  18% (71/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  19% (74/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  20% (78/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  21% (82/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  22% (86/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  23% (90/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  24% (94/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  25% (98/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  26% (102/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  27% (106/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  28% (109/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  29% (113/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  30% (117/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  31% (121/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  32% (125/389), 1.71 MiB | 1.12 MiB/s
Receiving objects:  32% (127/389), 2.36 MiB | 1.17 MiB/s
Receiving objects:  33% (129/389), 2.36 MiB | 1.17 MiB/s
Receiving objects:  34% (133/389), 2.36 MiB | 1.17 MiB/s
Receiving objects:  35% (137/389), 2.36 MiB | 1.17 MiB/s
Receiving objects:  36% (141/389), 2.36 MiB | 1.17 MiB/s
Receiving objects:  37% (144/389), 2.36 MiB | 1.17 MiB/s
Receiving objects:  38% (148/389), 2.36 MiB | 1.17 MiB/s
Receiving objects:  39% (152/389), 2.94 MiB | 1.16 MiB/s
Receiving objects:  40% (156/389), 2.94 MiB | 1.16 MiB/s
Receiving objects:  41% (160/389), 2.94 MiB | 1.16 MiB/s
Receiving objects:  42% (164/389), 2.94 MiB | 1.16 MiB/s
Receiving objects:  43% (168/389), 2.94 MiB | 1.16 MiB/s
Receiving objects:  44% (172/389), 2.94 MiB | 1.16 MiB/s
Receiving objects:  45% (176/389), 2.94 MiB | 1.16 MiB/s
Receiving objects:  46% (179/389), 2.94 MiB | 1.16 MiB/s
Receiving objects:  46% (181/389), 4.22 MiB | 1.19 MiB/s
Receiving objects:  47% (183/389), 4.22 MiB | 1.19 MiB/s
Receiving objects:  48% (187/389), 4.22 MiB | 1.19 MiB/s
Receiving objects:  48% (189/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  49% (191/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  50% (195/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  51% (199/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  52% (203/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  53% (207/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  54% (211/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  55% (214/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  56% (218/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  57% (222/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  58% (226/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  59% (230/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  60% (234/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  61% (238/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  62% (242/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  63% (246/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  64% (249/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  65% (253/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  66% (257/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  67% (261/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  68% (265/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  69% (269/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  70% (273/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  71% (277/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  72% (281/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  73% (284/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  74% (288/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  75% (292/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  76% (296/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  77% (300/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  78% (304/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  79% (308/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  80% (312/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  81% (316/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  82% (319/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  83% (323/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  84% (327/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  85% (331/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  86% (335/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  87% (339/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  88% (343/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  89% (347/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  90% (351/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  91% (354/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  92% (358/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  93% (362/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  94% (366/389), 4.86 MiB | 1.20 MiB/s
Receiving objects:  94% (367/389), 6.11 MiB | 1.23 MiB/s
Receiving objects:  95% (370/389), 6.70 MiB | 1.23 MiB/s
Receiving objects:  96% (374/389), 6.70 MiB | 1.23 MiB/s
Receiving objects:  96% (376/389), 7.31 MiB | 1.23 MiB/s
remote: Total 389 (delta 120), reused 75 (delta 75), pack-reused 229        
Receiving objects:  97% (378/389), 7.93 MiB | 1.22 MiB/s
Receiving objects:  98% (382/389), 7.93 MiB | 1.22 MiB/s
Receiving objects:  99% (386/389), 7.93 MiB | 1.22 MiB/s
Receiving objects: 100% (389/389), 7.93 MiB | 1.22 MiB/s
Receiving objects: 100% (389/389), 8.25 MiB | 1.21 MiB/s, done.
Resolving deltas:   0% (0/178)
Resolving deltas:   1% (2/178)
Resolving deltas:   2% (4/178)
Resolving deltas:   3% (7/178)
Resolving deltas:   4% (8/178)
Resolving deltas:   5% (9/178)
Resolving deltas:   6% (12/178)
Resolving deltas:   7% (13/178)
Resolving deltas:   8% (15/178)
Resolving deltas:   9% (17/178)
Resolving deltas:  10% (18/178)
Resolving deltas:  11% (20/178)
Resolving deltas:  12% (23/178)
Resolving deltas:  13% (24/178)
Resolving deltas:  15% (27/178)
Resolving deltas:  16% (29/178)
Resolving deltas:  17% (31/178)
Resolving deltas:  19% (34/178)
Resolving deltas:  20% (36/178)
Resolving deltas:  21% (38/178)
Resolving deltas:  22% (40/178)
Resolving deltas:  24% (43/178)
Resolving deltas:  25% (45/178)
Resolving deltas:  27% (49/178)
Resolving deltas:  29% (52/178)
Resolving deltas:  30% (54/178)
Resolving deltas:  31% (56/178)
Resolving deltas:  32% (57/178)
Resolving deltas:  33% (60/178)
Resolving deltas:  34% (61/178)
Resolving deltas:  35% (63/178)
Resolving deltas:  36% (65/178)
Resolving deltas:  37% (67/178)
Resolving deltas:  38% (68/178)
Resolving deltas:  40% (72/178)
Resolving deltas:  41% (73/178)
Resolving deltas:  42% (75/178)
Resolving deltas:  43% (77/178)
Resolving deltas:  44% (79/178)
Resolving deltas:  45% (81/178)
Resolving deltas:  46% (83/178)
Resolving deltas:  47% (84/178)
Resolving deltas:  48% (86/178)
Resolving deltas:  49% (88/178)
Resolving deltas:  51% (91/178)
Resolving deltas:  52% (93/178)
Resolving deltas:  53% (96/178)
Resolving deltas:  54% (97/178)
Resolving deltas:  55% (98/178)
Resolving deltas:  56% (100/178)
Resolving deltas:  57% (102/178)
Resolving deltas:  58% (104/178)
Resolving deltas:  59% (106/178)
Resolving deltas:  60% (107/178)
Resolving deltas:  61% (109/178)
Resolving deltas:  62% (111/178)
Resolving deltas:  63% (113/178)
Resolving deltas:  64% (115/178)
Resolving deltas:  65% (116/178)
Resolving deltas:  66% (118/178)
Resolving deltas:  67% (120/178)
Resolving deltas:  68% (122/178)
Resolving deltas:  69% (123/178)
Resolving deltas:  70% (125/178)
Resolving deltas:  71% (128/178)
Resolving deltas:  73% (130/178)
Resolving deltas:  74% (132/178)
Resolving deltas:  75% (134/178)
Resolving deltas:  76% (136/178)
Resolving deltas:  77% (138/178)
Resolving deltas:  79% (141/178)
Resolving deltas:  80% (143/178)
Resolving deltas:  81% (145/178)
Resolving deltas:  82% (146/178)
Resolving deltas:  83% (148/178)
Resolving deltas:  84% (150/178)
Resolving deltas:  85% (152/178)
Resolving deltas:  86% (154/178)
Resolving deltas:  87% (155/178)
Resolving deltas:  88% (157/178)
Resolving deltas:  89% (160/178)
Resolving deltas:  90% (161/178)
Resolving deltas:  91% (162/178)
Resolving deltas:  92% (164/178)
Resolving deltas:  93% (166/178)
Resolving deltas:  94% (169/178)
Resolving deltas:  95% (170/178)
Resolving deltas:  96% (171/178)
Resolving deltas:  97% (173/178)
Resolving deltas:  98% (175/178)
Resolving deltas:  99% (177/178)
Resolving deltas: 100% (178/178)
Resolving deltas: 100% (178/178), done.
error: invalid path '.github /FUNDING.yml'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

### Screenshots

![image](https://user-images.githubusercontent.com/132856640/236708647-7e0353c6-8c17-4688-983e-8a9df79bbcbe.png)

### Additional context

The machine is installed just few minutes before I experienced this problem.

**Comment by sergiou87** [comment]
👋 

Could you try cloning it in a different folder **out of OneDrive**? OneDrive, Dropbox, etc. are known to cause issues with git repositories, so maybe that's what's giving you trouble. Let us know if that works 🤞
