### ISSUE TITLE
"A branch with that name already exists." error when trying to resolve conflicts using desktop

### ISSUE THREAD

**Issue by WlodekM** [desktop/desktop#16664]
### The problem

When i tried to resolve the merge conflicts in github desktop an error appeared saying "A branch with that name already exists."

### Release version

3.2.2

### Operating system

Windows 10 home

### Steps to reproduce the behavior

1. Go to pull request with to many conflicts
2. Scroll down to where it says "This branch has conflicts that must be resolved"
3. Click "open this in GitHub Desktop"
4. See the error

### Log files

[2023-05-08.desktop.production.log](https://github.com/desktop/desktop/files/11419860/2023-05-08.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/75479945/236787432-05055753-39e3-42db-bdcc-c355c4c6e891.png)

**Comment by WlodekM** [comment]
I updated to 3.2.3 and the error still appears

**Comment by steveward** [comment]
@WlodekM I'm seeing this error:

```
2023-05-08T09:17:41.774Z - error: [ui] `git -c credential.helper= checkout --progress upstream/develop -b develop --recurse-submodules --` exited with an unexpected code: 128.
stderr:
fatal: a branch named 'develop' already exists
```

Any chance you have a stash named `develop`? That can cause errors like this. You can run `git stash list` to check. Can you also share the output of `git branch -a` from the command line?

**Comment by WlodekM** [comment]
> @WlodekM I'm seeing this error:
> 
> ```
> 2023-05-08T09:17:41.774Z - error: [ui] `git -c credential.helper= checkout --progress upstream/develop -b develop --recurse-submodules --` exited with an unexpected code: 128.
> stderr:
> fatal: a branch named 'develop' already exists
> ```
> 
> Any chance you have a stash named `develop`? That can cause errors like this. You can run `git stash list` to check. Can you also share the output of `git branch -a` from the command line?

um i don't know what is a stash so i probably don't have one

**Comment by steveward** [comment]
Apologies, I missed that this was an upstream branch. You're hitting [this issue](https://github.com/desktop/desktop/issues/4527). The current workaround is to compare changes of your current branch to upstream and merge through that. You can find this option by going to `Branch` > `Compare to Branch`. You should then be able to see the merge conflicts when comparing the upstream and origin branches. I'm going to close this out since we are tracking this issue, but let me know if you have any further questions.
