### ISSUE TITLE
Sub module index not updating

### ISSUE THREAD

**Issue by maxizrinUX** [desktop/desktop#16665]
### The problem

When I try to switch to a branch, I get an error.

### Release version

3.2.3 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Try to switch to a branch that's recently.
Get the error.

### Log files

[2023-05-08.desktop.production.log](https://github.com/desktop/desktop/files/11421088/2023-05-08.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/96064674/236824327-59c3f935-2142-4cd4-b6f7-1d65ca78e5c8.png)

### Additional context

This started happening recently.
Older branches, older than 2 months, or local branches, can be switched to without issue.

Using a terminal to run the following:
`git submudule update --remote`
Fixes the issue temporarily.

**Comment by maxizrinUX** [comment]
The local repo died, and now I can't clone it, crashes when it gets to the submodules.

**Comment by steveward** [comment]
Thanks for the issue @maxizrinUX. This looks like the same issue as https://github.com/desktop/desktop/issues/13016. 
You can workaround this by removing the following lines from the `.git/config`:

```
[submodule]
    active = .
```

Let me know if that helps.

**Comment by maxizrinUX** [comment]
Sorry, I switched to using SourceTree.
