### ISSUE TITLE
Compare Branch Feature - Merge and Normal Commit Comparison Jumbling - GitHub Desktop

### ISSUE THREAD

**Issue by febtech** [desktop/desktop#16669]
### The problem

When I go to the compare branch feature in GitHub Desktop and click on either Ahead or Behind after comparing the current branch with another branch, if there are many different commits and I click on one of them after being active in another, very often,  the details of the wrong commit (usually a merge commit) is being shown when I make the normal commit active. This has only been an issue in the past few months. It wasn't like this earlier.

### Release version

Version 3.2.3 (x64)

### Operating system

Windows 11

**Comment by steveward** [comment]
Thanks for the report @febtech. Would you be able to record a short video of this behavior? Unfortunately issues like this can be difficult to reproduce.

It would also be helpful if you could upload the log file from GitHub Desktop. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
