### ISSUE TITLE
Many issues with the Dev

### ISSUE THREAD

**Issue by Schawktoronto** [desktop/desktop#16683]
### The problem

We are deleting Dev Branches and they are showing up for my team members.
We are having huge issue getting the wrong flow and files and having to delete dev branches and start from scratch.

Can you advise on the fix and will the list in the App show an accurate list soon?

### Release version

3.2.3 x64

### Operating system

Mac 11.7.6

### Log files

Most of this week and today in particular.

**Comment by steveward** [comment]
Thanks for the report @Schawktoronto. I'm not sure I fully understand the issue -- is the problem that branches are being deleted in the remote repository on GitHub but then not in GitHub Desktop? GitHub Desktop does not automatically delete local branches until 14 days after the remote branch has been deleted. Any extra details you can share about the issue you are experiencing would be helpful, thanks.
