### ISSUE TITLE
Discarding changes for 660 files causes ENAMETOOLONG

### ISSUE THREAD

**Issue by SaschaNaz** [desktop/desktop#1668]
### Description

"Discard all changes" with 660 files causes ENAMETOOLONG.

### Version

**GitHub Desktop version:** 0.5.5

**OS version:** Windows 10.0.15063

### Steps to Reproduce

1. Make some changes with large number of files
1. "Discard all changes"

**Expected behaviour:** The work should be done quickly

**Actual behaviour:** It takes too long and throws an error after deleting all changed files

**Reproduces how often:** 100%

![image](https://cloud.githubusercontent.com/assets/3396686/26278595/78922f70-3dd9-11e7-917c-228421d00121.png)

### Logs

No log was there.

**Comment by Hillery21** [comment]
Hi . I know one tool that can help "Long path tool" . It solves this kind of problem. I've been using it for months now and it really works fine. :) It is really helpful
