### ISSUE TITLE
You may not have access error

### ISSUE THREAD

**Issue by rever96** [desktop/desktop#16685]
### The problem

trying to pull or push from a repo on second account results in 
`The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.`
error without the possibility to give auth username and pass.

### Release version

3.2.3 (arm64)

### Operating system

Mac

**Comment by steveward** [comment]
@rever96 thanks for the issue. If you want to verify you are logged in you can go to `GitHub Desktop` > `Preferences` > `Accounts`. I would also recommend verifying that you have the correct read/write permissions for the repository (if it is not a repository that is owned by your account).

**Comment by rever96** [comment]
I fixed the issue removing the repo and relocate it opening from file > local repository.
Than it asked me email and pass and i regain the access to pull and push.

**Comment by hejj93** [comment]
I  was facing the same issue, what I did:

-List repositories
-Right Click Open in Command Prompt 
-git status 
-git push
-Return to Github Desktop Window and click on Push
