### ISSUE TITLE
Different IDEs for different repos

### ISSUE THREAD

**Issue by liebdash** [desktop/desktop#16690]
### The feature request

Right now, when I set a default IDE (e.g. IntelliJ), it becomes my default IDE for all of my repos. But some repos I would like to open in different IDEs. I have some python projects I'd like to open in PyCharm, some JS projects I'd like to open in VSCode, etc. 

### Proposed solution

I'd like to be able to set a global default and a repo-level default that overrides the global default.

So for example, let's say my global default is VSCode. I have repo X which I set the repo-level default to be IntelliJ. When I open repo Y, it opens in VSCode since I have not set any default for it.

**Comment by steveward** [comment]
Thanks for the feedback @liebdash. This is being tracked in https://github.com/desktop/desktop/issues/12195 so you can follow along there for updates.
