### ISSUE TITLE
Create new branch deleted my files

### ISSUE THREAD

**Issue by mbkfincom** [desktop/desktop#16695]
### The problem

I had a some pending changes, I wanted to move these to a new branch called "force-safe-price". 
I clicked branch -> new -> force-safe-price

Popup: "stash changed" or "bring changes with me"
I've clicked "bring changes with me".
The new branch shows up but there is no pending change or stashed file.

I've tried to chech the logs but I don't see any useful hash I could use for recovery.

### Release version

3.2.3

### Operating system

Windows 10

### Steps to reproduce the behavior

Make some changes
Create new branch
Click "bring changes with me"

### Log files

[2023-05-15.desktop.production.log](https://github.com/desktop/desktop/files/11475084/2023-05-15.desktop.production.log)

### Additional context

The reason why I was creating a new branch was trying to make npm work.
After one year of running this project without any trouble (sveltekit with vite) today It was not working, I thought it was some of my changes even if I didn't touch any config files, but I wanted to try the production version to see if it was working on my pc or not. So maybe I'm thinking on locked files inside the project folder, but idk...

**Comment by steveward** [comment]
@mbkfincom thanks for the issue. If you selected `bring changes....` then nothing would have been stashed, and your changes should be there as uncommitted changes. Can you open the repository in the command line and run the command `git reflog`? That may give us a better idea of what happened here. I would also recommend checking the Recycle Bin to see if any of the files are there.
