### ISSUE TITLE
GitHub account switching

### ISSUE THREAD

**Issue by HeCorr** [desktop/desktop#16709]
### The feature request

I have two GitHub accounts, one for work and a personal one. When switching between projects, which happens quite often, I also need to switch accounts (or I can't push changes), and the steps to do so are quite repetitive:

1. Sign out from account A on GitHub Desktop
2. Sign out from account A on browser
3. Sign in into account B on browser
4. Sign in into account B on GitHub Desktop

### Proposed solution

I propose the creation of an account switcher mechanism, that would allow a user to sign in into multiple accounts at the same time and switch between them at any time by selecting one of them from a drop-down menu (check screenshots below).

Selecting a different account from the list would make it the active one, updating the profile picture as well as the session cookies used for interacting with GitHub (pushing, pulling, etc), while the other account's session data is kept on disk.

### Additional context

I've slightly modified the current Accounts tab in the Options window as an example of what the UI could look like:

![2023-05-16 21-25-10](https://github.com/desktop/desktop/assets/75134774/47975382-c870-4396-a82e-18e08f589124)

![2023-05-16 21-25-02](https://github.com/desktop/desktop/assets/75134774/34f16c93-8771-4d6d-8870-4bc4cb96867b)

**Comment by HeCorr** [comment]
I would like to implement this myself but I'm not sure where to start. I'll be checking out the code soon to try to figure out how the current system works and how I could modify it.

Suggestions are welcome!

**Comment by ferferga** [comment]
Github ToS explicitly forbids multiple accounts

**Comment by HeCorr** [comment]
I did not know that.

**Comment by steveward** [comment]
Thanks for the interest in this @HeCorr. We are tracking feedback about this in https://github.com/desktop/desktop/issues/3707 if you would like to follow along there for updates.

**Comment by masonwheeler** [comment]
> Github ToS explicitly forbids multiple accounts

The the ToS is broken and needs to be revised.  There are any number of perfectly legitimate reasons to have multiple accounts, such as keeping one's employment and personal dev work separate.  It should forbid *the abuse of* multiple accounts (sock-puppeting, etc) but to forbid having multiple accounts is simply absurd.

**Comment by Husain01** [comment]
> > Github ToS explicitly forbids multiple accounts
> 
> The the ToS is broken and needs to be revised. There are any number of perfectly legitimate reasons to have multiple accounts, such as keeping one's employment and personal dev work separate. It should forbid _the abuse of_ multiple accounts (sock-puppeting, etc) but to forbid having multiple accounts is simply absurd.

And how does GitHub even track if a user has multiple accounts? There are dozens of legitimate cases especially people having personal and work accounts which they use both of. GitHub Team should now really think coz this isn't a big feature to implement. I've seen workarounds and it can be implemented similarly too.

**Comment by HeCorr** [comment]
I agree. I am by no means abusing any sort of resource limits or anything like that. In fact, both of my accounts together utilize way less than what a single (more active) account would. It really is just to disassociate one's repos from the other and keep things separate. I hope they understand that.

**Comment by ferferga** [comment]
Here's the source for all the ones interested: https://docs.github.com/es/site-policy/github-terms/github-terms-of-service#b-account-terms

The subtitle has a brief summary, but you can read all the "small letter" directly from the source (not me) there. 


In case I wasn't clear enough, I'm not pronouncing myself whether I agree with GitHub in this policy or not, I'm just presenting a fact. Also, any quick Google search about this topic will give you relevant results from Twitter, SO, etc that confirm that they indeed enforce this.

**Comment by repository23** [comment]
it is not good that it is still with browser

**Comment by casbloem** [comment]
You can add multiple accounts and there is an account switcher on the website.

**Comment by eduardocruz** [comment]
As of March 2024, I can clearly see a "Switch" account option on Github web. 

If it allows for the web, it should allow for the desktop client. 

And a reference: 
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/switching-between-accounts

**Comment by kcherr1** [comment]
Ok, we can't have multiple FREE accounts. How about giving us a convenient way to switch from free to a paid account and back again? Or among different paid accounts? I work for different companies and have my own personal account. It's annoying to go through the multiple steps to switch to a different account, then even after switching I have to manually change my email for some reason. At least have the email auto switch after logging into a different account. Removing any (unecessary) work in this process would be appreciated.

**Comment by CyanHyprPsychic** [comment]
i might be a little stupid but i feel like this would be a nonissue if we were capable of installing multiple instances of the desktop program onto the same computer so that different executables can hold different logins. 

it'd be clunky but itd still be better than having to open a web browser, open the account settings, change accounts, log out of the desktop app, then log into the desktop app again. 
you could use shortcut names to differentiate work from personal

**Comment by GI-STANDARDS** [comment]
JUST USE GITmaxed & all set
