### ISSUE TITLE
Add support for repository rules

### ISSUE THREAD

**Issue by vaindil** [desktop/desktop#16707]
[Repository rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets) ([announced here](https://github.blog/changelog/2023-04-17-introducing-repository-rules-public-beta/)) are the next version of branch protection rules, they use different endpoints to manage and have some different logic. I'm currently working on implementing support for them, this issue will track that work.

### Limitations
- The initial implementation will not check whether the current user can bypass the rules.
- Only repository-level rules are currently supported due to a pending internal bug fix.

#### Restrict creations
- [x] Display a warning in the "create a branch" popup when the user types a branch name that's disallowed by a ruleset
- [x] Display a warning in the commit area if an unpublished branch will fail to publish because its name is disallowed

#### Metadata restrictions
- [x] Display warning in "create a branch" popup if branch name metadata rule doesn't match
- [x] Display warning in commit area if any rules don't match configured metadata restrictions for:
  - [x] Commit message
  - [x] Commit author email address

#### Other rules
- [x] Many of the rules won't be handled in a special way beyond a generic warning in the commit area. I'm open to hearing if we could support these though, as I'm not the most familiar with this program! These include:
- restrict updates
- require linear history
- require signed commits
- require deployments to succeed before merging
- require status checks to succeed before merging

#### Still investigating
- [ ] The "require a pull request" rule will probably display a warning in the commit area that prompts the user to open a PR instead
- [ ] "Block force pushes" could theoretically display a warning, but I don't know that there's a good place to display it
- [ ] "Restrict deletions" (of branches) could also theoretically display a warning, but I don't see much benefit here because they'll get the error by clicking the button--I don't really see a value add here.
- [ ] I have a warning implemented for commit author email addresses not matching the pattern (by tweaking the existing [commit message avatar component](https://github.com/desktop/desktop/blob/291d632825a349856bc1f49b77104705e745473d/app/src/ui/changes/commit-message-avatar.tsx)). Is there a similar spot a warning could be shown for the committer email?

**Comment by CHEFSUSHIWILL1** [comment]
#5881 #17322 #17469 #17472 #17466 @vaindil @mtodd 

- [ ] @

```css
``
``` @probablycorey @mutle @mislav ### **[](url)**
``` 
```python
```swift
```javascript
/
``` 
``` 
``` 
``` 

> [``]( CHEFSUSHIWILL1/YouTube)
Duplicate of #10041
