### ISSUE TITLE
Node engine not working on commit

### ISSUE THREAD

**Issue by randresf-linc** [desktop/desktop#16701]
### The problem

while trying to commit a change there is a error modal saying some steps failed but the error is related to the node engine, which i understand since the version of the project its not the same as the terminal default and the pre-commit will try to run some tasks (test, lint, etc), so how can i provide the version to the terminal that the app uses behind the scenes? It should check for nvm file first and use that node version, or its not supported?

### Release version

Version 3.2.3 (arm64)

### Operating system

Mac Monterrey 12.6.2

### Steps to reproduce the behavior

1. modify any file from the github project
2. go to the app and provide a commit message
3. click on commit blue button
4. you will see the error

### Screenshots

![Screen Shot 2023-05-15 at 3 53 46 PM](https://github.com/desktop/desktop/assets/121959847/70e23602-51cc-4347-a26c-c25b9f9d1657)

### Additional context

i can replicate this issue from terminal by opening a new one, moving to the project folder and trying to commit a change, after running `nvm install` it will work

**Comment by steveward** [comment]
@randresf-linc apologies for the delay. If you launch GitHub Desktop from the Terminal it should use the same environment. You'll just need to install the command line tool (`GitHub Desktop` > `Install Command Line Tool...`) and then run `github .`. Let me know if that doesn't get things working.

**Comment by michealroberts** [comment]
@steveward This still doesn't seem to work, even when using the environment from the command line. Please can this just get fixed in 2023 🙏
