### ISSUE TITLE
Authentication error with confusing log 

### ISSUE THREAD

**Issue by C-J-Lin** [desktop/desktop#16715]
### The problem

Hello! Tried to commit to a repo that I definitely have access to. The repo is not archived, but I'm new to git so it might be something I'm doing - but on a previous encounter I re-installed and restarted which led to resolution.

In this encounter, no joy - so here I am looking for help. I logged out in GIT and tried to log back in and wasn't able to get a resolution.

### Release version

Version 3.2.3 (arm64)

### Operating system

MAC 12.6.3 Monterey

### Steps to reproduce the behavior

1. Launch Git. 
2. Hit push upstream on a previously attempted push.
3. Receive error 

### Log files

[2023-05-17.desktop.production.log](https://github.com/desktop/desktop/files/11499549/2023-05-17.desktop.production.log)

### Screenshots

<img width="1019" alt="Screen Shot 2023-05-17 at 6 55 18 PM" src="https://github.com/desktop/desktop/assets/130051624/2868f0c3-0579-4a7a-8fe2-05c2b56e0dad">

**Comment by steveward** [comment]
@C-J-Lin thanks for the issue. I'm not seeing any authentication errors in the log, but based on the screenshot it looks like you are trying to push to the `upstream` remote of your fork. Can you verify that you have push access to the parent repository of your fork?
