### ISSUE TITLE
Repositories from last version of GitHub do not show in list after upgrade.

### ISSUE THREAD

**Issue by programmer94** [desktop/desktop#1672]
### Description

After updating to the beta from the old desktop client, GitHub seems to have forgotten about my cloned repositories.

### Version

**GitHub Desktop version:** 0.5.5

**OS version:** Windows 10

### Steps to Reproduce

1. Update to the new desktop client.
1. Open the new desktop client.
1. Witness the emptiness of the repository list for the new desktop client.

**Expected behaviour:** I expected to see the repositories that I had cloned on the previous version of GitHub Desktop.

**Actual behaviour:** No repositories appear in the list.

**Reproduces how often:** 100% (Out of 1 time)

**Comment by shiftkey** [comment]
> After updating to the beta from the old desktop client, GitHub seems to have forgotten about my cloned repositories.

We made the decision early on to not invest time in migrating from the existing apps. This limitation is mentioned [in the README](https://github.com/desktop/desktop#where-can-i-get-it) but wasn't really communicated broadly.

We haven't thought about smoothing out the transition as part of 1.0 to help people switch over to the new app, but I suspect this would be a good things to do.

**Comment by joshaber** [comment]
Tracking this in #186.
