### ISSUE TITLE
View not updating after commit on Mac

### ISSUE THREAD

**Issue by simonsoho** [desktop/desktop#16722]
### The problem

after a commit happens the interface does not update. It still shows the files that HAD changes prior to the commit and there is no option to push the commit

quit Github and relaunch it and you get the correct view - no uncommitted file and the option to push the changes

this is consistent every time behaviour  on latest release

### Release version

Version 3.2.3 (arm64)

### Operating system

Mac OS Ventura 13.3.1 (a) (22E772610a) 

### Steps to reproduce the behavior

 make a commit

### Log files

[2023-05-18.desktop.production.log](https://github.com/desktop/desktop/files/11513951/2023-05-18.desktop.production.log)

**Comment by sergiou87** [comment]
I'm sorry @simonsoho , is this what doesn't work for you?

https://github.com/desktop/desktop/assets/1083228/b2f8572e-e008-4d72-972f-d4362ba8dc25

After I make the commit, the changed files disappear and the new commit shows up in the list of commits.

**Comment by sergiou87** [comment]
Could you post a video of what you see? 🙏  Thank you!
