### ISSUE TITLE
application problem

### ISSUE THREAD

**Issue by ParadisePrAp** [desktop/desktop#16726]
### The problem

i cant find github after downloading it and now cant open it cuz there is not icon/app to open it
i have to reinstall to use it again.
:(

### Release version

latest on may 19

### Operating system

Windows 10 Home

### Steps to reproduce the behavior

1. download it 
2. use the app
3. close it
4. now youre doomed cuz no way to open it

### Screenshots

![image](https://github.com/desktop/desktop/assets/88097174/e3542baa-38be-4431-9ba2-ee2bd9ff536b)

**Comment by steveward** [comment]
@ParadisePrAp thanks for the issue. There should be a desktop shortcut created during the installation process. You can also go to `%LocalAppData%\GitHubDesktop\` to find the application. Is it possible your machine isn't indexing applications?

**Comment by ParadisePrAp** [comment]
Hello,
@steveward 

I want to express my sincere gratitude for your help with my desktop icon issue. You were very kind and patient to guide me through the steps of finding the icon in the windows files and creating a shortcut on the desktop. Your solution helped me to access the app that I needed without any hassle. You saved me a lot of time and frustration.

You are a very knowledgeable and helpful person. I appreciate your generosity and willingness to share your expertise on the application problems. You are a great asset to the online community.

Thank you once again for your assistance. I hope to learn more from you in the future.

Sincerely,
@ParadisePrAp
