### ISSUE TITLE
github authentication issues

### ISSUE THREAD

**Issue by JangHoChan** [desktop/desktop#16738]
### The problem

![image](https://github.com/desktop/desktop/assets/77651701/effe42d2-7b43-4e48-ac26-e2c7b4413f6e)

i wrote the correct id and password. i checked with github and it was right. But github desktop insists that i'm not authenicated.

### Release version

Version 3.2.3 (x64)

### Operating system

windows 10

### Steps to reproduce the behavior

1. go to github desktop
2. push contents
3. the error message appears

### Screenshots

![image](https://github.com/desktop/desktop/assets/77651701/a4c18709-659b-4d6e-8576-e040e7c09210)

**Comment by sergiou87** [comment]
Did you sign in on GitHub Desktop from Preferences -> Accounts?

![image](https://github.com/desktop/desktop/assets/1083228/89735c08-f0ef-4aa0-bb0f-5526c0b4ec0c)
