### ISSUE TITLE
Convert the Windows powershell scripts to javascript

### ISSUE THREAD

**Issue by rlabrecque** [desktop/desktop#1673]
This will be nice for cross compilation.

There's two very simple scripts introduced in ffef11db2f71d99734c1624a3477fd0f757fb602, and have been unchanged since then. I'm assuming they were just from Native and there was just no reason to convert them over at the time.

Any thoughts of concerns?

Helps get closer to #48 as well.

**Comment by shiftkey** [comment]
> This will be nice for cross compilation.

It's not clear to me what we're referring to when we talk about cross-compilation here. Could you elaborate on what you're trying to do?

> Any thoughts of concerns?

These files should be hidden behind the `APPVEYOR` environment variable (the cleanup step isn't, that's probably some cleanup we can do) and the code-signing itself is only possible on Windows proper.

**Comment by rlabrecque** [comment]
I'm building GHD for win32 from linux (and it works fine!)

The purpose of this is just to cleanup some build time platform specific stuff. Given how simple those two scripts are, hoisting them right into script\package as functions should be no big deal right?

It seems like one day code signing might work on macOS and Linux one day:
https://github.com/electron-userland/electron-builder/issues/314
https://github.com/electron/windows-installer/issues/27

**Comment by joshaber** [comment]
Cross-compilation isn't a goal or priority right now, so I'm gonna close this.
