### ISSUE TITLE
Application does not refresh often enough

### ISSUE THREAD

**Issue by mobynet1** [desktop/desktop#16750]
### The feature request

A Refresh button is needed if the external repository updates are not reflected immediately.

I know I have a repository that has some pending commits and when the GitHub Desktop is first opened, no new activity is reflected. Even when the app is open and an uncommitted update is made, there is a significant delay in the time the app indicates a commit, push, or pull is available to be made.

### Proposed solution

React to and reflect changes made in a repository immediately
Add a refresh button so that the repository status can be reevaluated.

### Additional context

I love this tool! It beats SourceTree by a mile. In fact GitHub smashes Atlassian Jira and Bitbucket! Now, if the refresh thingy worked better!! ;-)

**Comment by sergiou87** [comment]
Thank you for your kind words! 💖 

We recently introduced the ability to fetch at any time, which (correct me if I'm wrong) should be what you're looking for. It's either in the `Repository` menu, or in the toolbar (maybe hidden under the dropdown):

![2023-05-23 at 11 12](https://github.com/desktop/desktop/assets/1083228/cd9b3a0a-a054-4dc4-8546-a0b63ac68911)
![2023-05-23 at 11 12](https://github.com/desktop/desktop/assets/1083228/b21db5ca-a0d8-42f5-beae-649d0b4ec181)
![2023-05-23 at 11 13](https://github.com/desktop/desktop/assets/1083228/78adcf4c-6aeb-41d6-8074-8e0d71b58c15)

Does that help you at all?

**Comment by mobynet1** [comment]
Hi @sergiou87,

I did notice this either yesterday or this morning by happenstance. I do like this feature, but that is not quite what I was trying to convey.

I have 18 repositories that I am using GitHub Desktop to track. If I make a change to one of those repositories and then look at the current repository tab as shown in the next image:

![GitHub Desktop](https://github.com/desktop/desktop/assets/124538071/bf8ea0ac-af35-4f4f-9101-51948f663b7e)

The dots indicating something has changed do not become active for a significant amount of time after a change. They eventually do become highlighted (the changed dot), but I would like for this to be either way more responsive or provide a refresh button so the repository statuses can be updated on request.

Does that make sense?

Thanks!
Steve

**Comment by sergiou87** [comment]
Oh! So you meant refreshing the repository list, perfect 👍 

I will label this as `enhancement` but we don't have the bandwidth right now to discuss about this, so we can't commit to anything at all 😅 

I can tell we'd rather improve our current "auto-refresh" logic than adding a button, __but__ adding a button might be the best approach. That's what we'd need to discuss.

Sorry I don't have anything better at this point!

**Comment by steveward** [comment]
I'm going to consolidate this feedback into https://github.com/desktop/desktop/issues/13700 which is a previous issue requesting a "Fetch all" option.
