### ISSUE TITLE
Pausing.

### ISSUE THREAD

**Issue by Rise0956** [desktop/desktop#16761]
### The feature request

Sometimes a Repository can be Multiple Gigabytes large, and cloning it from online can take forever, and having to restart the process because of outside influences like blackouts or bad internet can be annoying.

### Proposed solution

Maybe, if we had the ability to pause the cloning of a URL Repository, and be able to continue wherever it left off.

**Comment by steveward** [comment]
Thanks for the feedback @Rise0956, I'm going to group this into https://github.com/desktop/desktop/issues/2082 which is a related request for canceling.
