### ISSUE TITLE
Uninstalling app does not remove x-github-client URL scheme handler

### ISSUE THREAD

**Issue by tonyarnold** [desktop/desktop#1676]
I have uninstalled the macOS version of GitHub Desktop, however the `x-github-client` custom URL scheme has been left behind. Clicking "Open In Desktop" on GitHub.com continues to try to open  GitHub Desktop, rather than my chosen client (Tower).

This is the error that's shown:

<img width="670" alt="screen shot 2017-05-21 at 14 39 04" src="https://cloud.githubusercontent.com/assets/4802/26281181/44eae9fa-3e33-11e7-98dd-1beff8db2a2f.png">

I've rebuilt my LaunchServices database, and used Hazel to completely uninstall GitHub Desktop to no avail.

**Comment by iancorbitt** [comment]
I to am having this issue.

**Comment by joshaber** [comment]
Unfortunately there's no way for GitHub.com to test what protocols can be opened by your computer. So after you've installed GitHub Desktop Beta, it will always use the `x-github-client://` protocol.

If other apps want to piggyback on the protocol, they'll need to handle that change.

**Comment by iancorbitt** [comment]
I'm just trying to use the old Desktop client. I've go so far as to manually remove all traces of it and reinstall, to no avail.

**Comment by latenitefilms** [comment]
I'm also having this issue. Has anyone found a workaround?

Unfortunately the GitHub Desktop Beta is missing some functionality I need, so I really want to go back to the stable release.

**Comment by landonth** [comment]
I made a simple greasemonkey userscript to workaround this issue for now:

https://github.com/landonth/github-desktop-protocol-fix

Hope this helps those affected looking for an interim solution.

**Comment by steveharoz** [comment]
To make sure it's clear, this issue occurs on Windows too. Do the developers have any workaround?

**Comment by landonth** [comment]
@steveharoz maybe i'm wrong, but it's been a few months already so i doubt the developers will be providing an official workaround for legacy protocol handlers at this point.

the userscript workaround i posted above should work for any git client that is expecting git-windows:// or git-mac://
it simply replaces any occurrences of x-github-client:// found in ahref attributes.

**Comment by drakeet** [comment]
@landonth Great! Your userscript workaround saved me. Now I can continue using the old GitHub Desktop (v223) happily. Thank you very much!

**Comment by joshaber** [comment]
Now that [GitHub Desktop 1.0](https://github.com/blog/2437-announcing-github-desktop-1-0) is out, we don't have any plans to support the old protocol.

Please feel free to open issues for bugs you find or features you'd like to see in the new app!
