### ISSUE TITLE
Provide 'Projects' functionality like the Github mobile app

### ISSUE THREAD

**Issue by rossajmcd** [desktop/desktop#16775]
### The feature request

Could the MacOS Github app provide 'Projects' functionality like the mobile app? Feature parity or progress towards it would be useful - it is convenient to use 'native' or close to 'native' apps across platforms.

### Proposed solution

Offer a view and ability to interact with 'Projects' per the mobile app.

**Comment by steveward** [comment]
Thanks for the feedback @rossajmcd, I'm going to add this to https://github.com/desktop/desktop/issues/12791 where we are tracking this.
