### ISSUE TITLE
multiple repos

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#16777]
### The problem

remote only shows one remote repo (principal)

while my repo is clearly configured to have more than one. and no way to switch between remotes

Branches are displayed only from this one. 

### Release version

3.2.3

### Operating system

Windows 10

### Steps to reproduce the behavior

Repositoty _> repository settings

**Comment by steveward** [comment]
Thanks for the issue @leonardobravo-utilities, we are tracking feedback about this in https://github.com/desktop/desktop/issues/1442 if you would like to follow along.

GItHub Desktop does support upstream remotes. If you look in the branches list you should see `upstream/<branch_name>`, which you can select when you want to update your local forked repository with the upstream repository. Let me know if you have any questions about that functionality.
