### ISSUE TITLE
Guthub desktop should allow for a second window of the same respository

### ISSUE THREAD

**Issue by jmarx** [desktop/desktop#16776]
### The feature request

I can't open two windows of github desktop with the same repository.
Is there no way to do this? It seems like a basic mandatory feature to me.

### Proposed solution

When looking at the code within a specific repository, I need the ability to have a second window with the same code so I can compare commits, cherry picks etc. This seems like a no-brainer to me for an application like this. Having to switch branches on the same window and try to memorize the code for comparison is very difficult and seems to defeat the purpose for a comparison application like this in the first place. If there is a way to do this, can someone please point me in the right direction?

Thanks!

**Comment by steveward** [comment]
Thanks for the feedback @jmarx, I'm going to add this to https://github.com/desktop/desktop/issues/3606 where we are tracking this feature. The issue is closed due it not being planned at the moment, but it may be something we look into again in the future.
