### ISSUE TITLE
Remove the app from my device

### ISSUE THREAD

**Issue by Okayhfd** [desktop/desktop#16787]
### The problem

The app is disturbing my phone device, remove it and delete it permeant

### Release version

Save all data in this device and delete the app

### Operating system

Disable the app and delete it permeant

### Log files

I don't want the app, delete it and never install it

### Screenshots

Help me remove the app in phone device, it has been disturbing my phone device

### Additional context

Disable the app and remove it from all devices

**Comment by Okayhfd** [comment]
Remove the app from all devices and delete it permeant

**Comment by Okayhfd** [comment]
Remove the app from all devices and delete it permeant

**Comment by steveward** [comment]
@Okayhfd this issue tracker is for GitHub Desktop, not a phone application.
