### ISSUE TITLE
"Access is denied" when selecting "Open in RStudio"

### ISSUE THREAD

**Issue by ericvmai** [desktop/desktop#16793]
### The problem

I try to open my R project up through RStudio using the "Open in RStudio" option. When doing this, I get the following error:
![image](https://github.com/desktop/desktop/assets/30978780/d744daf5-0cec-48cf-aff8-ac5eed21d1c9)

I can open in Windows Explorer just fine and GitHub Desktop is still connected to my repo. My folders don't have any restrictions on them that would deny me access. 

This is just a minor inconvenience, but seems like it could be a GitHub Desktop issue?

### Release version

Version 3.2.3 (x64)

### Operating system

Windows 10

### Log files

[2023-05-26.desktop.production.log](https://github.com/desktop/desktop/files/11580520/2023-05-26.desktop.production.log)

**Comment by mbmaxwell** [comment]
I'm having this same issue. Will share if I'm able to find a fix.

**Comment by tesla-dubois** [comment]
Hi there. Any insight on this? I'm having the same issue. I just updated R and Rstudio and thought maybe that could be the reason, but either way I haven't found a solution yet.

**Comment by steveward** [comment]
My guess is this was related to a change in RStudio. I've opened a support ticket with them to see if we can track down what may be causing this.

**Comment by steveward** [comment]
May be resolved with RStudio Desktop 2024.09.0+375 according to the latest comment in the tracking issue.

**Comment by steveward** [comment]
@mbmaxwell @tesla-dubois @ericvmai are any of you still experiencing this issue when using `Open in RStudio` from GitHub Desktop? I'm going through old issues and am hoping we can close this out. Thanks!

**Comment by ericvmai** [comment]
Not having this issue anymore.

**Comment by steveward** [comment]
Thanks for following up! I'll close this out as resolved.
