### ISSUE TITLE
Unable to push local changes to remote repository

### ISSUE THREAD

**Issue by dar-dev** [desktop/desktop#16804]
### The problem

Unable to push local changes to remote repository.

Here's the error : 

Enumerating objects: 29, done.
Counting objects: 100% (29/29), done.
Delta compression using up to 8 threads
Compressing objects: 100% (12/12), done.
Writing objects: 100% (15/15), 1.44 KiB | 1.44 MiB/s, done.
Total 15 (delta 10), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (10/10), completed with 10 local objects.        
To https://github.com/MikOfClassX/libgdx.git
 ! [remote rejected]     classx -> classx (failed)
error: failed to push some refs 

> to 'https://github.com/MikOfClassX/libgdx.git'

### Release version

Version 3.2.3

### Operating system

Windows 10

### Steps to reproduce the behavior

Go on repository 
Click on "Push origin" button 
Error: 

Enumerating objects: 29, done.
Counting objects: 100% (29/29), done.
Delta compression using up to 8 threads
Compressing objects: 100% (12/12), done.
Writing objects: 100% (15/15), 1.44 KiB | 1.44 MiB/s, done.
Total 15 (delta 10), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (10/10), completed with 10 local objects.        
To https://github.com/MikOfClassX/libgdx.git
 ! [remote rejected]     classx -> classx (failed)
error: failed to push some refs 

> to 'https://github.com/MikOfClassX/libgdx.git'

### Screenshots

![immagine](https://github.com/desktop/desktop/assets/55930104/e3666ca6-ac14-489c-9eb2-1c2e5e4bb0cc)

**Comment by dar-dev** [comment]
Additionally, the problem has gone by reverting the master to previous commit. It's very strange because this is a server error. I suspect is hiding something on server side, because we committed changes locally with no errors.

**Comment by sergiou87** [comment]
Weird! If it's working again, I'm gonna close it. Feel free to reopen (or ping me if you can't reopen) if the problem persists 🤞
