### ISSUE TITLE
WHERE DO I PAY U THERE IN THE DARKNESS??

### ISSUE THREAD

**Issue by NLPsixteen** [desktop/desktop#16815]
I dont find where to choose product and where to pay, neither where to donate.

Best Regards

NLPsixteen
Peter Bergün
Sweden
Mail me plz: PB1966PB@GMAIL.COM

**Comment by steveward** [comment]
@NLPsixteen you can find GitHub's pricing plans here:

https://github.com/pricing

I hope that helps. If you have further questions I'd recommend asking [here](https://github.com/orgs/community/discussions/categories/new-to-github).
