### ISSUE TITLE
password

### ISSUE THREAD

**Issue by Elihle46** [desktop/desktop#16814]

**Comment by Elihle46** [comment]
Password for : 
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/Elihle46/alx-pre_course.git/'

**Comment by steveward** [comment]
@Elihle46 if you are having issues with GitHub Desktop please fill out the issue template so we can assist you further.
