### ISSUE TITLE
Easy thing to do, for letting the user know progress..

### ISSUE THREAD

**Issue by ar-visions** [desktop/desktop#16810]
### The problem

You have to mouse over to see the push progress.  Anyway you have the model data it looks like and it would be useful to display it differently rather than needing to hover over.

### Release version

3.2.3

### Operating system

macOS

### Steps to reproduce the behavior

...

**Comment by steveward** [comment]
Thanks for the issue @ar-visions. You should see push progress like this:

<img width="272" alt="Screen Shot 2022-10-14 at 4 41 39 PM" src="https://user-images.githubusercontent.com/721500/195940013-5d539db6-e65d-49d4-a2cd-a018157269ae.png">

The full output is truncated, but the progress bar gives a good indication of the state of the operation. I'm going to close this out but let me know if I'm misunderstanding the feedback here.
