### ISSUE TITLE
Cannot commit after removing GPG key

### ISSUE THREAD

**Issue by harshfeudal** [desktop/desktop#16824]
### The problem

I have a problem about commit my repo after removing the GPG key because I failed to setup. I found the instruction link on here:
https://stackoverflow.com/questions/50785728/how-to-remove-gpg-key-from-github

### Release version

Version 3.2.3 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Simply commit a repo by clicking the "Commit" blue button from GitHub Desktop.GitHub

### Log files

[2023-06-03.desktop.production.log](https://github.com/desktop/desktop/files/11643111/2023-06-03.desktop.production.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/87577447/cce0c835-1690-4c06-b203-ae7b235bb898)

**Comment by steveward** [comment]
@harshfeudal thanks for the issue. It looks like GPG signing is still enabled:

```
stderr:
error: cannot spawn E:\Trung Son\Code Project\Cpp Massive Projects\Discord Anime Bot\Tsukasa Tsukuyomi: Permission denied
error: gpg failed to sign the data
fatal: failed to write commit object
```

This line in your `.gitconfig` is likely causing the issue:

```
[commit]
  gpgsign = true
```

Let me know if removing that doesn't get things working.
