### ISSUE TITLE
Branch Comparison - Per File Preview

### ISSUE THREAD

**Issue by rtfmoz2** [desktop/desktop#16829]
### The feature request

Enable a  branch compare which open a preview of the file changes

This feature request has been re-submitted as the other discussions and responses do not adequately satisfy this requirement.

### Proposed solution

On activation of branch compare

1. Scripting to create a hidden or temporary branch from current.  Perform a merge (always accept incoming) and squash into it from the branch you want to compare. Now compare the original branch with this temporary one. 
2. In current software you will have one temporary commit on the left and all the files. Now If you **_turn off_** the  commit pane you just have the file view and they can walk through the files to see what they want.  

Done.

### Additional context
![image](https://user-images.githubusercontent.com/40995106/220814987-d7f69f05-a38b-4d60-bdfd-7047bef1b72c.png)

**Comment by steveward** [comment]
Thanks for the feedback @rtfmoz2. I'm going to roll this into https://github.com/desktop/desktop/issues/6757.
