### ISSUE TITLE
会装软件不，问也不问，就随便找个文件夹装了

### ISSUE THREAD

**Issue by AShine17cm** [desktop/desktop#16826]
### The feature request

会装软件不，问也不问，就随便找个文件夹装了

### Proposed solution

会装软件不，问也不问，就随便找个文件夹装了

**Comment by steveward** [comment]
@AShine17cm The installer we use (Squirrel) does not allow for customizing the installation directory.  See [this response](https://github.com/desktop/desktop/issues/10768#issuecomment-706096056) for some more details. You can follow along in https://github.com/desktop/desktop/issues/1086 for installation improvements, but at this time we don't have any plans to change the installation experience.
