### ISSUE TITLE
Use latest stable version of electron

### ISSUE THREAD

**Issue by fisforfaheem** [desktop/desktop#16830]
### The feature request

Faster startup: Electron apps built with SDK 25 will start up faster than Electron apps built with SDK 22. This is due to a number of factors, including the use of a newer version of Chromium and Node.js, as well as a number of performance optimizations that have been made to the Electron framework.
Improved responsiveness: Electron apps built with SDK 25 will be more responsive than Electron apps built with SDK 22. This is due to a number of factors, including the use of a newer version of Chromium and Node.js, as well as a number of performance optimizations that have been made to the Electron framework.
Reduced memory usage: Electron apps built with SDK 25 will use less memory than Electron apps built with SDK 22. This is due to a number of factors, including the use of a newer version of Chromium and Node.js, as well as a number of performance optimizations that have been made to the Electron framework.

### Proposed solution

The use of a newer version of Chromium, which is more efficient than older versions.
The use of a newer version of Node.js, which is more efficient than older versions.
A number of performance optimizations that have been made to the Electron framework.

**Comment by steveward** [comment]
Thanks for the issue @fisforfaheem, we're in the process of upgrading to a more recent version of Electron (see https://github.com/desktop/desktop/issues/16830).

**Comment by fisforfaheem** [comment]
Thanks, hope to see latest vscode INSIDERS gets the update soon

**Comment by fisforfaheem** [comment]
still its on chromium 108, instead of 105
