### ISSUE TITLE
When referencing issues/prs, the list got cut off by the divider

### ISSUE THREAD

**Issue by EvanNotFound** [desktop/desktop#16833]
### The problem

When using `#` to reference issues/pull requests, the issues/pull requests list got cut off by the divider. See the screenshots.

### Release version

Version 3.2.3 (arm64)

### Operating system

macOS Ventura 13.1 (22C65)

### Steps to reproduce the behavior

1. Open Github Desktop
2. Type `#` in the summary or description box in any repo
3. The issues/pull requests list will be cut off

<img width="1072" alt="Screenshot 2023-06-04 at 2 03 06 PM" src="https://github.com/desktop/desktop/assets/68590232/f29bd672-d061-40fe-a8ae-20fc64b80458">

### Screenshots

<img width="1072" alt="Screenshot 2023-06-04 at 2 00 52 PM" src="https://github.com/desktop/desktop/assets/68590232/88dc92fd-608b-4c88-89d8-53551a9d5bc8">
<img width="1072" alt="Screenshot 2023-06-04 at 2 01 10 PM" src="https://github.com/desktop/desktop/assets/68590232/0fd1200b-8fe9-432b-a18c-7caefafdd75c">

**Comment by steveward** [comment]
Thanks for the report @EvanNotFound, this will be fixed in the next release (see https://github.com/desktop/desktop/pull/16651).
