### ISSUE TITLE
UI doesn't show option of stashed changes after branch rename

### ISSUE THREAD

**Issue by OmkarK05** [desktop/desktop#16853]
### The problem

After renaming a branch in GitHub Desktop, the option to view stashed changes is no longer available in the UI. However, I confirmed via the command line that the stashed changes do still exist.

### Release version

Version 3.2.3 (arm64)

### Operating system

macOS 13.2.1

### Steps to reproduce the behavior

1. Create a new branch.
2. Make changes to code.
3. Stash the changes.
4. Rename the branch.
5. Stashed changes are not visible in the UI, but they are present when checked via the command line.

### Log files

-

### Screenshots

--

### Additional context

-

**Comment by steveward** [comment]
Thanks for the issue @OmkarK05, this will be resolved by https://github.com/desktop/desktop/pull/16512.
