### ISSUE TITLE
"View on GitHub" menu item is disabled for GitHub Gist repos

### ISSUE THREAD

**Issue by tedmiston** [desktop/desktop#16862]
### The problem

Expected: "View on GitHub" menu item is enabled and triggering it opens the Gist page for a GitHub Gist repo.

Actual: "View on GitHub" menu item is disabled and there is no way to trigger it.

### Release version

Version 3.2.4-beta1 (x64)

### Operating system

macOS Monterey

### Steps to reproduce the behavior

1. Clone a repo from GitHub Gist (any Gist repo)
2. Add the repo to GitHub Desktop
3. Ctrl-click on the repo in the "Current Repository" name for the contextual menu
4. Observe that the "View on GitHub" menu item is not functioning as expected

### Screenshots

<img width="390" alt="image" src="https://github.com/desktop/desktop/assets/366688/c098db66-6142-4bca-a5e5-4db2eaa69744">

**Comment by steveward** [comment]
Thanks for the issue @tedmiston. Gists unfortunately aren't something that we have had time to prioritize and have only heard minimal feedback about over the years. We have a tracking issue (https://github.com/desktop/desktop/issues/2973) for improving Gist support, but at this time it isn't on our list of priorities. It may be something we consider again in the future, though. I'll reference this issue there and close this out.

**Comment by tedmiston** [comment]
@steveward You're just going to close the issue as "wontfix" after 1 hour???

What's the point of even having open issues to submit a bug report in the first place if you're just going to ignore them?!

*"Improve our Gists experience"* is not a duplicate of *"'View on GitHub' functionality is broken for 1 of the 2 types of repos on GitHub"*...

---

How can this be a difficult bug to fix?  Just tweak a missing regex or config bit somewhere etc...  I'm shocked the official response from GitHub Staff on GitHub's client working with GitHub's server is to just dismiss the bug report without even trying to fix it...  The icing on the 🍰 is closing it as "Completed" by doing... nothing...

**Comment by moritztim** [comment]
@steveward This is such a simple fix. Fair enough, you're not doing a full gists integration but you could at least just have this button work so you can open it.

**Comment by moritztim** [comment]
Took a look at the code and wow this is complicated.
https://github.com/desktop/desktop/blob/c024236097f179b9153c9b7c2bdb63f327e809cf/app/src/models/repository.ts#L170-L176
https://github.com/desktop/desktop/blob/c024236097f179b9153c9b7c2bdb63f327e809cf/app/src/models/repository.ts#L108-L112
https://github.com/desktop/desktop/blob/c024236097f179b9153c9b7c2bdb63f327e809cf/app/src/models/repository.ts#L88-L91

Still seems doable but I can see now that it's not totally trivial.
