### ISSUE TITLE
Endless fetching

### ISSUE THREAD

**Issue by Mika5652** [desktop/desktop#16868]
### The problem

When I have opened Github Desktop on mac longer (through the night), then I always see endless fetching.
Even when I make commit and tried to push changed, it doesn't work and I have to restart whole application. After that everything works again.

### Release version

Version 3.2.3 (arm64)

### Operating system

macOS Ventura 13.4 (22F66)

### Steps to reproduce the behavior

1. Open Github Desktop with some Github repo in there.
2. Make them open through the night (during the sleep of mac).
3. Next day, open mac and go to opened Github Desktop.
4. You should see endless fetching.

### Screenshots

<img width="310" alt="Snímek obrazovky 2023-06-10 v 9 34 39" src="https://github.com/desktop/desktop/assets/15653162/90a781a6-2177-4293-99e2-44b2c65acca0">

**Comment by steveward** [comment]
Thanks for the report @Mika5652. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Mika5652** [comment]
Hi, thanks for fast response and sorry for not attaching log files immediately.

[2023-06-10.desktop.production.log](https://github.com/desktop/desktop/files/11727404/2023-06-10.desktop.production.log)

**Comment by steveward** [comment]
I'm not seeing anything in the log file you sent over that indicates a background fetch hanging, but there may be more details in another log file. If you're able to reproduce this consistently it would be helpful to know if anything interesting is shown in the developer tools. To do this you can go to View > Toggle Developer Tools and take a look at the Console and Network tabs during the hanging fetch operation to see if anything shows up there that could give a better indication of what specifically is hanging.

**Comment by nich2408** [comment]
Hi, I have the same issue, hope this info can help.

### **Release version**
Version 3.2.6 (x64)

### **Operating system**
Windows 10 Version 10.0.19045 Build 19045

### **Steps to reproduce the behavior**
Boot PC.
Open Github Desktop with some Github repo in there.
Fetch starts automatically, you'll see endless fetching; sometimes it also occurs again after the first try.

### **Log files**
[2023-06-30.desktop.production.log](https://github.com/desktop/desktop/files/11914422/2023-06-30.desktop.production.log)

### **Screenshots**
![1](https://github.com/desktop/desktop/assets/98348348/baa86717-64a9-4ce8-aeb5-f8e3eaf27a3c)

![2](https://github.com/desktop/desktop/assets/98348348/03e9375b-266c-4e57-a8f3-bc4e576448aa)

### **Additional context**
During the endless fetching I did simple Internet connection check and it's fine (tested by opening GitHub on browser). I also had some old remote repositories which I could not connect to them anymore, so I deleted them before doing the test from the scratch.

**Comment by gustaflindqvist** [comment]
Is this issue resolved or just auto closed? I have the same issue still in 3.3.9. Could it be connected to GPG and SSH connection? 

Did you guys solve it @Mika5652 or @nich2408?

**Comment by Mika5652** [comment]
No I don't solve that, but I don't reach the same problem for a long time now.

**Comment by gustaflindqvist** [comment]
> No I don't solve that, but I don't reach the same problem for a long time now.

Check! Where you using GPG keys or SSH for the repo when you had the problem?

**Comment by nich2408** [comment]
> Is this issue resolved or just auto closed? I have the same issue still in 3.3.9. Could it be connected to GPG and SSH connection?
> 
> Did you guys solve it @Mika5652 or @nich2408?

I didn't see it anymore.

**Comment by Mika5652** [comment]
> > No I don't solve that, but I don't reach the same problem for a long time now.
> 
> 
> 
> Check! Where you using GPG keys or SSH for the repo when you had the problem? 

If I remember I used GPG before, but I switched to sign commits using 1Password, so maybe that solves the problem? I'm not sure.
