### ISSUE TITLE
We want an easy way to manage tags

### ISSUE THREAD

**Issue by b4st1en** [desktop/desktop#16874]
### The feature request

Why cant we just "move" an existing tag as simple as it is using GitLab ?

Why do we have to create a release first and then delete it just to create a new tag ?

### Proposed solution

Make a better UI to manage tags

**Comment by b4st1en** [comment]
Woops that is not the "github" Issues board, but the GitHub Desktop one.. sorry

**Comment by steveward** [comment]
@b4st1en no problem, you can leave feedback like that here: https://github.com/orgs/community/discussions/

**Comment by b4st1en** [comment]
Anyway.. this may apply both, to GitHub but also GitHub Desktop ?
(sorry not sure as I do prefer to use IDE integrated git client..)

**Comment by Dexter775** [comment]
On Jun 12, 2023, at 8:23 AM, b4st1en ***@***.***> wrote:﻿
Woops that is not the "github" Issues board, but the GitHub Desktop one.. sorry
