### ISSUE TITLE
Request: Remembering Marked Files

### ISSUE THREAD

**Issue by razzraziel** [desktop/desktop#16871]
### The feature request

When restarting Github Desktop, it automatically [marks all the changes](https://i.imgur.com/iCeKUKW.png) to be included even if we set differently before closing it down. 

### Proposed solution

It would be better if it remembers which files are marked or not.

**Comment by steveward** [comment]
Thanks for the issue @razzraziel, this is being tracked in https://github.com/desktop/desktop/issues/5870 so I'll close this out and reference this issue there.
