### ISSUE TITLE
Default clone path with placeholders

### ISSUE THREAD

**Issue by rigor789** [desktop/desktop#16872]
### The feature request

When working with many repositories, it's helpful to organize cloned repositories in specific directories.

Ideally, I'd like to set a default clone path, ie.
```
~/Code/{owner}/{repo}
```

Right now, I have to manually change the `{owner}` in the path when cloning a new repo.

### Proposed solution

Add a new setting in Preferences to allow setting the default clone path, supporting optional placeholders:
 - `{owner}`
 - `{repo}`

### Additional context

![image](https://github.com/desktop/desktop/assets/879060/46e42c3c-5a10-4e86-907c-82af031c97ae)

**Comment by steveward** [comment]
Thanks for the feedback @rigor789, I'm going to add this to https://github.com/desktop/desktop/issues/5449 where we are tracking this feature.

**Comment by rigor789** [comment]
Thanks @steveward - sorry for missing that one, didn't come up in my search.
