### ISSUE TITLE
Option to only use absolute dates everywhere instead of pretty but useless relatives ones

### ISSUE THREAD

**Issue by b4st1en** [desktop/desktop#16873]
### The feature request

Let people decide if they prefer :
-  a pretty but useless relative date
- a real date

### Proposed solution

Add a profile option to define the way people want to see dates

### Additional context

Same as https://github.com/desktop/desktop/issues/4573 that was closed without any valid reason

**Comment by b4st1en** [comment]
Woops that is not the "github" Issues board, but the GitHub Desktop one.. sorry..

But if the linked issue is still valid, could you consider reopening it and close this one ? :-)

**Comment by steveward** [comment]
Closing in favor of #4573.
