### ISSUE TITLE
Worthless

### ISSUE THREAD

**Issue by DocHammerSr** [desktop/desktop#16882]
Your documentation is obviously written by experts, who make sometimes unrealistic assumptions about user knowledge.  I have been a long time VB programmer hobbyist. I have written many programs, include a compact database manager, scheduling programs, personal accounting programs, and a graphical war game simulation (+more). Because you neglect to explain basic principles and terms, your voluminous documentation is unintelligible, making your software worthless.  I have already wasted too much time on your product. Please delete my account.

**Comment by steveward** [comment]
@DocHammerSr this issue tracker is for GitHub Desktop, if you have specific feedback about the documentation for that product let me know. You can find a helpful glossary of GitHub terms in [the glossary](https://docs.github.com/en/get-started/quickstart/github-glossary), or our [getting started guides](https://docs.github.com/en/get-started). If you want to delete your account you can read how to do that [here](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-personal-account/deleting-your-personal-account). I hope that helps.

**Comment by VODINHCUONG90** [comment]
Tui cần tien
