### ISSUE TITLE
Screenshot from my Windows 10 start menu:

### ISSUE THREAD

**Issue by Katrina2828** [desktop/desktop#16888]
Screenshot from my Windows 10 start menu:
![image](https://user-images.githubusercontent.com/86600423/198383215-fb6ba2e1-d4f7-4fc6-acdb-edf60e86c5bb.png)

_Originally posted by @Metehan-Altuntekin in https://github.com/desktop/desktop/issues/15432#issuecomment-1293986299_

**Comment by Metehan-Altuntekin** [comment]
What was this issue for? @Katrina2828
