### ISSUE TITLE
Make avatar un-focusable

### ISSUE THREAD

**Issue by percyhanna** [desktop/desktop#16887]
### The problem

It seems that a recent change has made the avatar image in the sidebar focusable. However, I cannot actually interact with it at all, or click on it. I'm curious why it's focusable if I can't do anything with it? I have become very accustomed to tabbing from the file list to the commit message input, but now there is an extra focusable element for seemingly no reason.

Can the avatar image be made un-focusable again please?

![Screenshot 2023-06-13 at 5 12 37 PM](https://github.com/desktop/desktop/assets/125077/c694444d-c45b-44a0-8704-7f9b426d2e51)

### Release version

Version 3.2.3 (x64)

### Operating system

macOS 13.4

### Steps to reproduce the behavior

1. Focus on the file selection sidebar ("Changed files")
2. Press tab

**Expected behaviour**
The "Summary" commit message input is focused.

**Actual behaviour**
The avatar image is focused, but is not actionable (cannot click, press space or enter key to do anything).

Is this button meant to allow me to change profiles that I am committing as? If so, then it's either not working, or maybe shouldn't be focusable if I only have a single profile available? I would still prefer that the tab index allow easier navigation from the file list to the commit message, as that is a much more common action than changing the author of a commit.

### Screenshots

![Screenshot 2023-06-13 at 5 12 37 PM](https://github.com/desktop/desktop/assets/125077/96d0250e-9614-4589-9418-82426129fe00)

**Comment by sergiou87** [comment]
Hello @percyhanna ! 👋  Thanks for your report 💖 

I'm surprised you cannot interact with it. We added a popover with info about the commit identity you're using:
![image](https://github.com/desktop/desktop/assets/1083228/38c20a5b-fe40-4262-8dce-77b341ae2587)

Try updating to 3.2.4 (About -> <kbd>Option</kbd> + click on `Check for updates`) if you can't see it right now.

I hope that helps! We'll need to leave the avatar focusable for accessibility reasons, as long as we allow interacting with it.

**Comment by Johnjohnnyjingles** [comment]
Why are you all hacking my account

**Comment by percyhanna** [comment]
> Try updating to 3.2.4 (About -> Option + click on `Check for updates`) if you can't see it right now.

I'm using 3.2.3, and it's not showing an update as being available. I am not using the Beta channel, and I'm using arm64 (Apple Silicon).

<img width="308" alt="Screen Shot 2023-06-16 at 12 01 37 PM" src="https://github.com/desktop/desktop/assets/125077/86c1c250-932d-4fb9-9618-2371222fec72">

However, even if I could, I would argue that the tabbing/focusing of this element is not ideal, since this is not something I am likely to change frequently per repository. Once I change the author for one repository, it is likely to stay the same forever. I commit multiple times per day, and I do not need to or care about the author every time I commit.

**Comment by percyhanna** [comment]
Also, I'm not sure if it's relevant, but I have some special configuration in my `~/.gitconfig`:

```
[includeIf "gitdir:~/work/"]
  path = ~/work/.work-gitconfig
```

I have multiple repositories that live under `~/work/*`, and this allows me to override the author for all of these repos (to use my work account), whereas my personal repos live in a different directory.

I was able to update to 3.2.4 on my Intel Mac. I see the following:

![Screenshot 2023-06-16 at 12 12 58 PM](https://github.com/desktop/desktop/assets/125077/92de667f-b795-45af-81d0-337d8bdeba46)

I am still unable to interact or do anything with it. Since I am overriding the author in my git config, could we make that input non-focusable?
