### ISSUE TITLE
Not updating default branch 

### ISSUE THREAD

**Issue by doleswapnil-splus** [desktop/desktop#16891]
### The problem

I updated default branch on github but its not updating in gitHub desktop app

### Release version

3.2.4(x64)

### Operating system

Windows 10 Pro

**Comment by steveward** [comment]
@doleswapnil-splus thanks for the issue. I was unable to reproduce this issue -- the default branch correctly updated. Did you click `Fetch origin` to update the local repository after changing the default branch?

**Comment by DigiH** [comment]
@doleswapnil-splus 

Have a look at your repo settings. The default branch is only being taken over correctly if you have it set to Fork Behaviour - **For My Own Purposes**, but NOT if **To Contribute to The Parent Repository** - at least for me like this with the latest release.

Hope this helps.
