### ISSUE TITLE
Temporary local save commit description

### ISSUE THREAD

**Issue by Gagafeee** [desktop/desktop#16895]
### The feature request

When user is writing a commit desc, but don't commit and close the app, 
⇾ Save this desc and re load it at the next time

### Proposed solution

The aim is to give the user the possibility of accumulating, for example, a modification list
1st day I write
```
- Added some functionnality
- Removed this one
```
and another day I finish my update and I will commit it
```
- Added some functionnality
- Removed this one
//recovered from other time
- Fixed ...
- ...
```
Then, when I work for a few days, I don't lose my previous comments.

**Comment by steveward** [comment]
@Gagafeee thanks for the issue -- there's a previous issue https://github.com/desktop/desktop/issues/3664 that is requesting persisting the commit message/summary after a restart of the app. Does that align with what you're requesting here?

**Comment by Gagafeee** [comment]
Yes, that was the idea, I didn't see it, 
thanks
