### ISSUE TITLE
Most recent branches not shown in Recent Branches list

### ISSUE THREAD

**Issue by mark-turner** [desktop/desktop#16897]
### The problem

When attempting to switch to a new branch, the Recent Branches list typically does not show the actual most recent branch(es). If I don't know the branch name, I have to open GitHub on the web, where the Active Branches list does show the most recent branches.

After typing the branch name in the GitHub Desktop branch filter field, it of course finds the branch, and thereafter shows it in the recent branches list.

It's obviously inconvenient and somewhat frustrating to not simply see the list of branches sorted by date, or at least correctly surfacing the four most recent ones.

### Release version

 3.2.3 (arm64)

### Operating system

macOS 13.4

### Steps to reproduce the behavior

1. Click to open Current Branch menu
2. "Recent Branches" section is seemingly not ordered by date or alphabetically. Most recent branches may not even be shown.
3. Open GitHub on the web, where the "Active Branches" list correctly shows the most recent branches in date order.
4. Enter the desired branch name in GitHub Desktop to find it.

### Log files

[2023-06-15.desktop.production.log](https://github.com/desktop/desktop/files/11754364/2023-06-15.desktop.production.log)

### Additional context

I have experienced the same behavior on a second Mac running 12.6.6

**Comment by steveward** [comment]
Thanks for the issue @mark-turner. The recent branches list uses the reflog to find the most recent branches that were checked out locally, so if your branch hasn't been checked out it does not appear there. There's some discussion around this in the still-open https://github.com/desktop/desktop/issues/5155, so I'll add this there.
