### ISSUE TITLE
Commits aren't synced when hitting "Push origin"

### ISSUE THREAD

**Issue by Studio384** [desktop/desktop#1689]
### Description

When a commit has been made, clicking "Push origin" will show the whole proces but once it is done the commit has still not been pushed.

### Version

**GitHub Desktop version:** 0.5.3+

**OS version:** Windows 10 version 1703

### Steps to Reproduce

1. Create a new commit
2. Hit "Push origin"

**Expected behaviour:** The commit gets synced

**Actual behaviour:** The commit isn't synced

**Reproduces how often:** All the time

### Logs

No errors shown in log.

**Comment by shiftkey** [comment]
@Studio384 can you include some screenshots of the before/after so we can understand this better?

**Comment by Studio384** [comment]
@shiftkey, there isn't really a "before/after". Anyways:

Before:
![1](https://cloud.githubusercontent.com/assets/1693592/26312260/50f41d0a-3f07-11e7-9e17-34c201fa4fe7.png)

During:
![2](https://cloud.githubusercontent.com/assets/1693592/26312258/50e504b4-3f07-11e7-811b-1fdea6775968.png)

After:
![3](https://cloud.githubusercontent.com/assets/1693592/26312259/50ea6526-3f07-11e7-9f2b-2e10c7d66ddc.png)

**Comment by tierninho** [comment]
I noticed this same error with the unborn branch error https://github.com/desktop/desktop/issues/1450 

@Studio384 possible to retry with the console in View > Toggle Dev tools open. Please provide a screenshot if something found. Thanks!

**Comment by joshaber** [comment]
Closing until more information is provided.

**Comment by Studio384** [comment]
I think I've found a way to reproduce this:

1. On GitHub.com, open a pull request from a branch to master
2. In GitHub Desktop, rename the branch with an open pull request
3. GitHub Desktop will now fail to sync the renamed branch

**Comment by shiftkey** [comment]
@Studio384 are there any errors in the dev tools panel ( **View** | **Toggle Dev tools**) when this occurs? This will help us understand the underlying issue.

**Comment by Studio384** [comment]
There are no errors.

**Comment by joshaber** [comment]
Thanks @Studio384! I've been able to reproduce this.
