### ISSUE TITLE
[3.2.4] Unable to fetch authenticated user

### ISSUE THREAD

**Issue by afbora** [desktop/desktop#16901]
### The problem

After upgrading on 3.2.4 I started getting login error. 

I installed 3.2.3 and it works fine.
https://central.github.com/deployments/desktop/desktop/3.2.3/win32

### Release version

3.2.4

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Fresh install
2. Go to `File > Options`
3. Try to sign-in to your github.com account
4. See `unable to fetch authenticated user` error

### Log files

2023-06-15T14:02:57.020Z - info: [ui] [SignInStore] initializing OAuth flow
2023-06-15T14:02:57.028Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=xxx&scope=repo%20user%20workflow&state=8ecd7892-faeb-4ef3-aea7-90102eda7792
2023-06-15T14:02:58.619Z - info: [main] Received possible protocol arguments: 4
2023-06-15T14:02:58.621Z - info: [main] Processing protocol url
2023-06-15T14:02:58.621Z - info: [ui] [Dispatcher] requesting authenticated user
2023-06-15T14:02:58.711Z - info: [main] Received possible protocol arguments: 3
2023-06-15T14:02:58.720Z - info: [main] Processing protocol url
2023-06-15T14:02:58.726Z - warn: [ui] requestOAuthToken: failed with endpoint https://api.github.com
TypeError: Failed to fetch
    at Nt (C:\Users\BORA\AppData\Local\GitHubDesktop\app-3.2.4\webpack:\app\src\lib\http.ts:152:10)
    at C:\Users\BORA\AppData\Local\GitHubDesktop\app-3.2.4\webpack:\app\src\lib\api.ts:2010:28
    at C:\Users\BORA\AppData\Local\GitHubDesktop\app-3.2.4\webpack:\app\src\lib\oauth.ts:52:23
    at Object.dispatchURLAction (C:\Users\BORA\AppData\Local\GitHubDesktop\app-3.2.4\webpack:\app\src\ui\dispatcher\dispatcher.ts:1810:30)
    at EventEmitter.<anonymous> (C:\Users\BORA\AppData\Local\GitHubDesktop\app-3.2.4\webpack:\app\src\ui\index.tsx:352:14)
    at EventEmitter.emit (node:events:513:28)
    at Object.onMessage (node:electron/js2c/renderer_init:2:9151)
2023-06-15T14:02:58.726Z - info: [ui] [SignInStore] error with OAuth flow
Error: Unable to fetch authenticated user.
    at Object.dispatchURLAction (C:\Users\BORA\AppData\Local\GitHubDesktop\app-3.2.4\webpack:\app\src\ui\dispatcher\dispatcher.ts:1814:32)

### Additional context

3.2.3 works great.

**Comment by sergiou87** [comment]
Hey @afbora ! 👋  Thanks for your report.

Looking at the changes included in 3.2.4 (#16838) I don't see anything that could affect signing in. I just tried it out and it worked as expected. Could you try again and see if, maybe, that was a temporary server error that is already fixed? 🤔

**Comment by afbora** [comment]
@sergiou87 I can reproduce the issue easily on 3.2.4 even deleted app data in `C:\Users\USER\AppData\Roaming\GitHub Desktop`. Then I uninstall 3.2.4 and install 3.2.3. Works great as expected 🤷‍♂️

**Comment by sergiou87** [comment]
None of the changes in https://github.com/desktop/desktop/compare/release-3.2.3...release-3.2.4 since 3.2.3 include anything related to signing in 🤯 

Could you try the latest beta from https://desktop.github.com/beta/ and see if it happens there?

**Comment by afbora** [comment]
I've tested the beta and no luck, same with 3.2.4. 3.2.3 still works for every fresh install.

**Comment by afbora** [comment]
@sergiou87 Is there a part you want me to test or debug?

**Comment by sergiou87** [comment]
@afbora I wonder if you have other machines where you can test it, and/or if you can try from another network (maybe using a cell phone internet connection instead of your home/work wifi?)

We can't see anything code related that could affect this, so we believe it must be something related to your setup, environment or ISP 🤔

**Comment by afbora** [comment]
I couldn't test on an another Windows machine but 3.2.4-beta works on MacOS.

I've tested 3.2.4 on Windows again. Still same. But I've another clue. May be you've an idea about that. Process `Checking for updates` is always running, not ending. Even if I never click the button.

![image (15)](https://github.com/desktop/desktop/assets/3393422/407f591b-2c9b-4691-aeee-1fc6786b1efd)

After for a while:

![image (16)](https://github.com/desktop/desktop/assets/3393422/abfcbd92-6090-4558-ac00-202553229d57)

**Comment by afbora** [comment]
I found source of issue. 3.2.4 works when I disabled Kaspersky Internet Security or just exclude listening HTTPS/443 port from Kaspersky. But I have still not idea about how 3.2.3 still working and 3.2.4 doesn't working 🤔 And similar issue https://github.com/desktop/desktop/issues/3125

**Comment by afbora** [comment]
Issue resolved. Maybe it will help some friends.

Today I contacted Kaspersky technical support via remote connection. They were unable to resolve the issue on Kaspersky Internet Security and told me that Internet Security is now outdated and to update it with [Kaspersky Standard](https://www.kaspersky.com/standard). We upgraded for free and it was fixed 🎉

**Comment by steveward** [comment]
Glad to hear things are working for you now!

**Comment by boriswinner** [comment]
I had the same issue.
The problem is, my ISP blocked Github (Russia).
I turned VPN and everything worked fine.

Very bad that the error message in the app is uninformative. It could save me a lot of time.

**Comment by weishanlee** [comment]
I also had problems when using version 3.2.4. Uninstalling 3.2.4 and returning to 3.2.3 makes things shining and working!

**Comment by da41b94c** [comment]
У меня была такая проблема.
Не обновлялся Github Windows, не клонировались проекты. 
Выяснил, что это Kaspersky Total Security блокирует/ограничивает соединения по 443 порту.
Решить проблему можно сняв галочку для 443 порта в Настройки/Настройка сети/Контролируемые порты (Выбрать)
![KTS](https://github.com/user-attachments/assets/0e0d5652-8920-4eeb-92aa-ba1de680dbd8)
