### ISSUE TITLE
Show if an inactive branch is behind the remote branch, and allow pulling updates to the branch.

### ISSUE THREAD

**Issue by bradlis7** [desktop/desktop#16902]
### The feature request

I would like to see if any of my branches are behind (and seeing if they are ahead would be helpful too). And have the ability to pull a branch that isn't the active one. It's nice if I'm wanting to merge from changes in another branch.

GitLens had this functionality that was nice.

### Proposed solution

In the branch dropdown, show ahead/behind counts, and then right click to pull into that branch.

**Comment by steveward** [comment]
Thanks for the feedback @bradlis7, I'm going to add this into https://github.com/desktop/desktop/issues/8048 where we are tracking this.
