### ISSUE TITLE
Recurring issue: Identified in #14936

### ISSUE THREAD

**Issue by tsmcgrath** [desktop/desktop#16903]
### The problem

Trying to check in a very small change to a private repo that is 149.1 Mb with no large files. I get this error:
"The remote disconnected. Check your Internet connection and try again."

I searched and see it already exists as issue #14936 but it is closed and while various suggestions are made to fix it there is not a definitive post on the solution. I will go try some of those but I'm opening this ticket because the problem is still occurring and no fix is concretly identified.

Github Desktop

### Release version

Version 3.2.1 (arm64)

### Operating system

Mac M1 Ventura 13.4

### Steps to reproduce the behavior

Make a change to a repo
Try to push the commit

### Additional context

It was working fine in a different repo a few days ago.

**Comment by tsmcgrath** [comment]
This worked for me:
git config --global http.postBuffer 157286400

I could push commits from the desktop after this.

**Comment by abcnishant007** [comment]
> git config --global http.postBuffer 157286400

@tsmcgrath thanks, this worked for me as well; any ideas on where I could read about it? why this specific number 157286400` It seemsto be 150MB; 157286400/ (1024*1024) = 150? or why `postBuffer`?
