### ISSUE TITLE
Operating system no longer supported.

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#16910]
### The problem

I am currently running Windows 10 Enterprise version 22H2 and seeing the unsupported banner after updating to GitHub Desktop version 3.2.4 (x64).

Computer Info:
Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎11/‎22/‎2020
OS build	19045.3086
Experience	Windows Feature Experience Pack 1000.19041.1000.0

### Release version

Version 3.2.4 (x64)

### Operating system

Windows 10

**Comment by niik** [comment]
Hey @ugujral1, thanks for reaching out! That's unexpected, Windows 10 and above is certainly still supported so we're trying to figure out why your machine would trigger that check. Could you please open the developer tools (View menu -> Toggle Developer tools) and type the following into the console

```
require('os').release()
```

Please let us know what that tells you and we'll continue investigating on our end

**Comment by ghost** [comment]
@niik Hey sorry about the delay American holiday on Monday. But `require('os').release()` returned '6.2.9200'.

**Comment by steveward** [comment]
@ugujral1 thanks for getting back to us. Can you verify that compatibility mode has not been turned on for GitHub Desktop? To do this go to the Start Menu, search for GitHub Desktop, then right-click and select `Open file location`. Next right-click on the GitHub Desktop shortcut and select `Properties` > `Compatibility`. Verify that compatibility mode has not been turned on.

Let us know what that shows.

**Comment by ghost** [comment]
@steveward Hey, yes that checkbox was checked and set for Windows 8. I don't remember if I had done that initially or if it was a default setting but unchecking that and restarting removed the unsupported banner warning.

**Comment by steveward** [comment]
I'm glad to hear that got things working! I'm going to close this out, thanks for your help debugging this.
