### ISSUE TITLE
History is confusing

### ISSUE THREAD

**Issue by mdiep** [desktop/desktop#1691]
### Description

The linear history presented by Desktop atm is confusing. It seems to show _all_ commits in topological order. This is confusing.

### Version
**GitHub Desktop version:** 0.5.3
**OS version:** macOS 10.12.5

### Steps to Reproduce

1. Open a repository that had multiple long-running branches merged
1. Look at history

**Expected behaviour:** [What you expected to happen]

Maybe only show the merge commits (this is what classic Desktop did). I'm a big fan of this approach because I think in terms of PRs.

Maybe sort commits by time.

**Actual behaviour:**

All commits are shown and aren't sorted by time. This makes it very hard to find a particular commit in History. (I often do this to look at the diff for a particular commit.)

**Comment by ikriz** [comment]
History is indeed very confusing.. I'm missing the insight into branch history, which branch is where in the commit list.

**Comment by luukdv** [comment]
Would also prefer the way classic Desktop handled this (1 commit when merging a branch), `master` branches tend to get very confusing the way it is now.

**Comment by joshaber** [comment]
We agree! We plan to address this as part of 1.1, under the heading of "Relationship to _X_": https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md#11

**Comment by joshaber** [comment]
I _think_ our work around exposing the [relationship between branches](https://github.com/desktop/desktop/issues/2639) for 1.1 will touch on this, so I'm gonna track it over there.

💖
