### ISSUE TITLE
GitHub desktop continually prompts for login credentials

### ISSUE THREAD

**Issue by juongithub** [desktop/desktop#16914]
### The problem

I'm using git repositories on bitbucket and until the latest GitHub desktop update I've never had any problems, but I don't know if the update and the problems I'm having are connected. As per the title, the problem is that github desktop keeps asking me for login credentials to my repositories which is very annoying. There is no exact pattern, but using git from the command line I have no problems (I tried using git on the command line several times at the GitHub desktop credentials request).

### Release version

Version 3.2.3 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

No specific steps, but it happens on all my repositories and also on non-mine repositories that I work on.

### Log files

2023-06-17T19:36:25.185Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 1.140s)
2023-06-17T19:37:17.834Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 1.511s)
2023-06-17T19:37:17.834Z - error: [ui] 'git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin' exited with an unexpected code: 128.
stderr:
remote: Invalid credentials
fatal: Authentication failed for 'https://bitbucket.org/****'  `[intentionally removed]`

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options. `i'm logged in`
- You may need to log out and log back in to refresh your token. `already done several times`
- You do not have permission to access this repository. `absolutely this is not true`
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits. `not archived`
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account. `using HTTPS`
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service. `using HTTPS`
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.) `I'm already using a Personal Access Token`

**Comment by godstime147** [comment]
Hello, Good day my responders in blockchain. It’s been one year and a week now since my phone got spoiled, however, I’ve not been able to log into my blockchain wallet account! although, I transferred all my coin from another blockchain account into the current account wallet which I’m looking for now. So due to the trust I was having with my other phone I couldn’t screenshot my 12 recovery key and now I’ve not been able to remember the gmail account which I used in registering my blockchain account. But I have my transaction address

**Comment by sergiou87** [comment]
Hello! 👋 

Since it's a Bitbucket repo what's failing, and given there are no changes related to authentication in the latest versions, I'd recommend you to try with a new Personal Access Token, and/or at least see if using that PAT from the command line works.

**Comment by juongithub** [comment]
I have already changed the PAT 2 times, same behavior. From the command line it never gives me problems.

**Comment by sergiou87** [comment]
Have you tried the very same command used by Desktop? More specifically: `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin`

That eliminates any credential helper you might be using. Maybe with that you see the same behavior in the command line 🤔 

Another question: does your repo have submodules? You can run `git submodule` in it to see if there are any. I ask this because _maybe_ it's one of the submodules what's causing the auth issues here 🤔

**Comment by juongithub** [comment]
> Have you tried the very same command used by Desktop? More specifically: `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin`

Thanks for the reply, the command in question always prompts me for the password even from the command line. Looking at the GitHub Desktop logs, things changed on June 7th, until then the problem didn't happen. However, "git fetch", "git push" and "git fetch --progress --prune --recurse-submodules=on-demand origin" from the command line never ask me for my login credentials.


> Another question: does your repo have submodules? You can run `git submodule` in it to see if there are any. I ask this because _maybe_ it's one of the submodules what's causing the auth issues here 🤔

there are no submodules in any of my repositories

**Comment by sergiou87** [comment]
Thank you @juongithub ! Something that is not clear to me (maybe I missed it) is… when Desktop prompts you the credentials and you enter them, does it work or you get an auth error?

**Comment by juongithub** [comment]
> when Desktop prompts you the credentials and you enter them, does it work or you get an auth error?

thanks [@sergiou87](https://github.com/sergiou87), after entering the credentials everything works fine, but if some time passes (random), I am asked again for the credentials at the next operation (e.g., fetch, push).

**Comment by juongithub** [comment]
> ### Release version
> Version 3.2.3 (x64)

same with Version 3.2.4 (x64)

**Comment by sergiou87** [comment]
Check the Windows Credentials Manager where you should find your credentials for GitHub Desktop. However, if you have many credentials stored, it might fail to store new ones. I'd recommend you to try and remove some of the existing ones and see if that helps.

**Comment by juongithub** [comment]
> Check the Windows Credentials Manager where you should find your credentials for GitHub Desktop. However, if you have many credentials stored, it might fail to store new ones. I'd recommend you to try and remove some of the existing ones and see if that helps.

Thanks @sergiou87, the problem is the one you described. Clearing the GitHub credentials in Windows Credentials Manager fixed the problem.

**Comment by sergiou87** [comment]
Yay! I'm glad it worked 😄 Thank you for your patience! 💖

**Comment by juongithub** [comment]
Thanks for your help

**Comment by Woudjee** [comment]
I have exactly the same problem and I tried the approach suggested by you, but this did not fix my problem. Any other suggestions? I have had this problem for a while now and it is highly annoying.

**Comment by keithtoop** [comment]
Same here. I have to change to SourceTree and this is really anonying. If you particularly having multiple repos and try to save PAT per repo individually. Once triggered integration options, all PATs saved just gone. Tried install/uninstall and Credential Manager, none of them worked.

**Comment by sergiou87** [comment]
@Woudjee @keithtoop we're very sorry about this. It's a known issue due to some recent changes. Please, take a look at https://github.com/desktop/desktop/issues/18586#issuecomment-2128857818 for the current solution in beta and let us know if that helped.
