### ISSUE TITLE
I can't access my repositories

### ISSUE THREAD

**Issue by rikaduz** [desktop/desktop#16915]
### The problem

Cloning into 'E:\gits\CareCompass11'...
remote: Enumerating objects: 310, done.        
remote: Total 310 (delta 0), reused 0 (delta 0), pack-reused 310        
Receiving objects: 100% (310/310), 268.58 KiB | 2.95 MiB/s, done.
Resolving deltas: 100% (67/67), done.
C:\Users\PC\AppData\Local\GitHubDesktop\app-3.2.4\resources\app\git\mingw64\libexec\git-core\git-submodule: line 610: cmd_: command not found

Would you like to retry cloning ?

### Release version

Version 3.2.4 (x64)

### Operating system

Windows 10 Home 22H2

**Comment by sergiou87** [comment]
Would you mind trying these two versions and let us know if any or both of them work? 

We'd like to pinpoint the issue and see if it has anything to do with our submodules update in 3.1.0.

3.1.1: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.1.1-a170ddea/GitHubDesktopSetup-x64.exe
3.0.8: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.0.8-c41b1670/GitHubDesktopSetup-x64.exe

If it happens on 3.1.1 but not on 3.0.8, at least we will know which changes caused this 🤔 

Thank you! 💖

**Comment by rikaduz** [comment]
Im doing it...

**Comment by rikaduz** [comment]
3.1.1 gave me a different error:


Cloning into 'E:\xamp2\htdocs\CareCompass-BT'...
remote: Enumerating objects: 158, done.        
remote: Counting objects: 100% (158/158), done.        
remote: Compressing objects: 100% (107/107), done.        
remote: Total 158 (delta 34), reused 156 (delta 32), pack-reused 0        
Receiving objects: 100% (158/158), 191.45 KiB | 2.39 MiB/s, done.
Resolving deltas: 100% (34/34), done.
      0 [main] sh (6684) C:\Users\PC\AppData\Local\GitHubDesktop\app-3.1.1\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x10BB408/0x11EB408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      0 [main] sh 1065 dofork: child -1 - forked process 6684 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\PC\AppData\Local\GitHubDesktop\app-3.1.1\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
1102153 [main] sh 1065 dofork: child -1 - forked process 13096 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\PC\AppData\Local\GitHubDesktop\app-3.1.1\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      0 [main] sh (12784) C:\Users\PC\AppData\Local\GitHubDesktop\app-3.1.1\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x10BB408/0x135B408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
3207189 [main] sh 1065 dofork: child -1 - forked process 12784 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\PC\AppData\Local\GitHubDesktop\app-3.1.1\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      0 [main] sh (584) C:\Users\PC\AppData\Local\GitHubDesktop\app-3.1.1\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x10BB408/0x138B408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
7301991 [main] sh 1065 dofork: child -1 - forked process 584 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\PC\AppData\Local\GitHubDesktop\app-3.1.1\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      0 [main] sh (7040) C:\Users\PC\AppData\Local\GitHubDesktop\app-3.1.1\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x10BB408/0x12CB408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
15402943 [main] sh 1065 dofork: child -1 - forked process 7040 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\PC\AppData\Local\GitHubDesktop\app-3.1.1\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: Resource temporarily unavailable

**Comment by rikaduz** [comment]
Will now try the second version

**Comment by rikaduz** [comment]
The 3.0.8 version gives me the same error ...

**Comment by rikaduz** [comment]
I've rebooted the system between installs...

**Comment by rikaduz** [comment]
Hi guys, Any help on this matter.

Here's what I have done to try to fix the issue. 

- I have deactivated ASLR - reboot  - no joy
- I have reinstalled git for windows - reboot - no joy
- I have reinstalled all 3 latest versions of GitHub - reboot 3x - no joy
- I have deactivated my firewall - reboot - no joy
- I have created different repositories and tried to clone them into my machine - no joy
- I have uninstalled Git and GitHub, and reinstalled them in a different drive - reboot 2x  - no joy
- I am running out of options...

**Comment by rikaduz** [comment]
> Would you mind trying these two versions and let us know if any or both of them work?
> 
> We'd like to pinpoint the issue and see if it has anything to do with our submodules update in 3.1.0.
> 
> 3.1.1: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.1.1-a170ddea/GitHubDesktopSetup-x64.exe 3.0.8: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.0.8-c41b1670/GitHubDesktopSetup-x64.exe
> 
> If it happens on 3.1.1 but not on 3.0.8, at least we will know which changes caused this 🤔
> 
> Thank you! 💖

Error in all versions...

**Comment by rikaduz** [comment]
I have now created a repository from my local folder to see the error result

> Updating 057983a..374fa16
Fast-forward
 Testing.txt | 1 +
 1 file changed, 1 insertion(+)
 create mode 100644 Testing.txt
C:\Users\PC\AppData\Local\GitHubDesktop\app-3.2.4\resources\app\git\mingw64\libexec\git-core\git-submodule: line 610: cmd_: command not found<

In my understanding this means ("command not found") that the system can't find the program it's trying to execute. In this case, the "cmd_" command appears to be missing or unrecognizable and refers to line 610 on that specific file.

So from line 604 to line 610 we have:

``# "--cached" is accepted only by "status" and "summary"
if test -n "$cached" && test "$command" != status && test "$command" != summary
then
	usage
fi

"cmd_$(echo $command | sed -e s/-/_/g)" "$@"``

This should not be the error then as the problem is from behind this file.  it seems like the command variable is not getting set, which indicates that none of the arguments passed to the script match the commands defined in the case statement. The result is that when the script attempts to call a function using the command variable (with cmd_$(echo $command | sed -e s/-/_/g) "$@"), the command variable is empty, leading to an error.

I would have to know these scripts to understand my problem. It would be nice if someone could help @sergiou87

**Comment by sergiou87** [comment]
🤯 thank you for testing those versions! I hoped 3.0.8 would work.

The things you have tried make sense. Since I don't have a clear idea of what could be wrong, I would add these to try to pinpoint the issue:
- If you have an antivirus, disable it (then uninstall & reinstall Desktop, to make sure no files are quarantined/deleted by the antivirus).
- If you have another Windows machine, try it there.
- Try running the very same `git clone` command as Desktop (you will find it in the logs) from the command line and see if you get the same error.

**Comment by rikaduz** [comment]
> 🤯 thank you for testing those versions! I hoped 3.0.8 would work.
> 
> The things you have tried make sense. Since I don't have a clear idea of what could be wrong, I would add these to try to pinpoint the issue:
> 
> * If you have an antivirus, disable it (then uninstall & reinstall Desktop, to make sure no files are quarantined/deleted by the antivirus).
> * If you have another Windows machine, try it there.
> * Try running the very same `git clone` command as Desktop (you will find it in the logs) from the command line and see if you get the same error.

From the suggestions above I have:

- Turned off antivirus, firewall  (both because I have wireglass)
- uninstall and reboot, Reinstall and reboot. Test - no joy

- Try in another machine - Yes, on a Windows Surface worked perfectly.

**Comment by sergiou87** [comment]
> Try in another machine - Yes, on a Windows Surface worked perfectly.

🤯🤯🤯

Well, at least we know something on your machine must be causing this. It sounds like something an antivirus would do (since they tend to quarantine/delete GitHub Desktop's files sometimes), but you already ruled that out. Is it possible that when you disable your antivirus, then Windows Defender gets enabled? Just making sure we rule out that option.

Is there any difference you can make between your Surface and your regular machine? (OS version, software installed, configuration…)
