### ISSUE TITLE
Forever Cloning

### ISSUE THREAD

**Issue by dahn24** [desktop/desktop#16911]
### The problem

I attempted to clone Mission Planner but it stopped on the "Checking Connectivity" page. How do I solve this problem? It had been going on for four hours.

### Release version

the newest version by the time I post this (I can't really check because I am using parallels)

### Operating system

Windows 11

### Screenshots

<img width="972" alt="Screenshot 2023-06-17 at 6 14 21 AM" src="https://github.com/desktop/desktop/assets/136778005/a8f3f1fb-9dd7-49dd-a02a-b8ac98ddd211">

**Comment by steveward** [comment]
Thanks for the report @dahn24. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by dahn24** [comment]
@steveward here is my log files
[Log Files.txt](https://github.com/desktop/desktop/files/11778023/Log.Files.txt)

**Comment by dahn24** [comment]
> Thanks for the report @dahn24. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.


@steveward here is the log files
[Log.Files (1).txt](https://github.com/desktop/desktop/files/11782070/Log.Files.1.txt)

**Comment by steveward** [comment]
@dahn24 unfortunately the log file isn't showing any specific clone errors. How large is the repository you are trying to clone? Are you able to clone any repositories?
