### ISSUE TITLE
My repos don't show up in the list in GH Desktop

### ISSUE THREAD

**Issue by DJ45X** [desktop/desktop#16913]
### The problem

I recently did a fresh install of windows. But this problem has persisted for nearly a year now. When I log into github desktop, The list that should show all of my already existing repos just doesn't show anything. I did try using the URL method and it's still not evening cloning a repo form URL. There shouldn't be an issue especially if it's my own repo. 

![image](https://github.com/desktop/desktop/assets/93067044/b55e03e1-3984-445f-94d9-530c5cd44856)

### Release version

3.2.3 (x64)

### Operating system

windows 10

### Steps to reproduce the behavior

There are no steps. Open github desktop and the list of repos is just empty.

### Log files

[2023-06-10.desktop.production.log](https://github.com/desktop/desktop/files/11779623/2023-06-10.desktop.production.log)
[2023-06-17.desktop.production.log](https://github.com/desktop/desktop/files/11779624/2023-06-17.desktop.production.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/93067044/31921772-b678-4af9-9a87-a3238587e43f)

**Comment by niik** [comment]
Hey @DJ45X, thanks for reaching out!

We're still looking into what might be happening with your repository list. It sure seems like the API is returning data that we don't expect. In the meantime you can clone repositories using the open in desktop button in your web browser:

![image](https://github.com/desktop/desktop/assets/634063/b3d8b789-94d4-4d99-ad59-4a30b2aee10f)

Or you can clone using the URL-method you mentioned. If you do use that method you have to copy the URL from the repository page, i.e. `https://github.com/desktop/desktop` and nothing else. In your log files I can see an attempt to clone a repository where you've copied the url for a specific tree (`/tree/ask-refactor/`) as well and that's likely why it didn't work that time.

**Comment by steveward** [comment]
@DJ45X i'm going to close this out, if you are still having issues please let us know and we can investigate further!

**Comment by DJ45X** [comment]
> @DJ45X i'm going to close this out, if you are still having issues please let us know and we can investigate further!

No worries! Not sure if there was a recent update, but recently my repos started showing up for me again. Thank you guys for this crucial tool in my workflow 😄
