### ISSUE TITLE
push error

### ISSUE THREAD

**Issue by HamadDeveloper** [desktop/desktop#16924]
fatal: unable to access 'https://github.com/HamadDeveloper/my-first-repo.git/': Could not resolve host: github.com

**Comment by steveward** [comment]
@HamadDeveloper this error usually indicates a DNS or other network issue. Are you behind a firewall or proxy that could be interfering with GitHub Desktop?

**Comment by Hirammm80** [comment]
> fatal: unable to access 'https://github.com/HamadDeveloper/my-first-repo.git/': Could not resolve host: github.com
>
