### ISSUE TITLE
ssh authentication failing

### ISSUE THREAD

**Issue by nushiamme** [desktop/desktop#16931]
### The problem

I have tried this in git bash and on the Desktop client, and am going in circles trying to fix my ssh authentication problem. 
When I run git push, I get this error:
_Load key "C:\\Users\\nushi/.ssh/id_rsa": Operation not supported on socket
CreateProcessW failed error:193
ssh_askpass: posix_spawnp: Unknown error
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists._

I have tried 
1. following the instructions on this page: https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/
2. adding a new ssh key, 
3. Running the following commands:
$ eval "$(ssh-agent -s)"
> Agent pid 16188
$  ssh-add -l -E sha256
> 256 SHA256:bcit+Vl1FRE775WLQcqU2+qX+/qjNs/NtTIgMPHVpNs nushiamme@gmail.com (ED25519)

So I do seem to have a functioning ssh key.

When I run the following, I get warnings
$ ssh -T git@github.com
> Warning: the ECDSA host key for 'github.com' differs from the key for the IP address '140.82.113.3'
> Offending key for IP in /c/Users/nushi/.ssh/known_hosts:1
> Matching host key in /c/Users/nushi/.ssh/known_hosts:8

And when I enter the passphrase for the key, I get:
> Hi nushiamme! You've successfully authenticated, but GitHub does not provide shell access.

### Release version

Version 3.2.4 (x64)

### Operating system

Windows 10 Home

**Comment by steveward** [comment]
@nushiamme thanks for the issue. For the host key error you can remove the entry from the `~/.ssh/known_hosts` file.

Can you go to `File` > `Options` > `Advanced` and see if you have the option to use the system OpenSSH selected? If so, try temporarily unselecting that to see if things work. That should help narrow down the issue.

**Comment by nushiamme** [comment]
Hi Steve,

I did try the system OpenSSH yesterday and that initially didn't work, but
I tried a few more things later and it seems to work with Github Desktop
now.

However I'd much prefer to use git bash, and I'm still having trouble
with authentication on bash.

With git push I get the following error repeatedly, no matter whether I
load a new ssh key, change the known_hosts file for github.com, or whatever
else.

$ git push
> Load key "C:\\Users\\nushi/.ssh/id_rsa": Operation not supported on socket
> CreateProcessW failed error:193
> ssh_askpass: posix_spawnp: Unknown error
> ***@***.***: Permission denied (publickey).
> fatal: Could not read from remote repository.

>Please make sure you have the correct access rights and the repository
exists.

Thanks,
Anusha Shankar
Rose Postdoctoral Fellow
Lab of Ornithology
Cornell University
Book a meeting with me: https://anushashankar.youcanbook.me/
Personal website: http://anushashankar.weebly.com/

**Comment by sergiou87** [comment]
From what I read in https://github.com/microsoft/vscode-remote-release/issues/7934 that might be either the file doesn't exist (the path `C:\\Users\\nushi/.ssh/id_rsa` definitely looks weird with that mix of `\\` and `/`) or you don't have permission to access it. Is any of those correct?

**Comment by nushiamme** [comment]
Hello,

Sorry for the delay on this. I don't seem to have permission. With Github
desktop I seem to be able to fetch and push 1/20 times. The other times it
says login failed. With git bash, I don't seem to be able to pull or push,
and still get this error:








*Load key "C:\\Users\\nushi/.ssh/id_rsa": Operation not supported on
socketCreateProcessW failed error:193ssh_askpass: posix_spawnp: Unknown
***@***.*** ***@***.***>: Permission denied (publickey).fatal:
Could not read from remote repository.Please make sure you have the correct
access rightsand the repository exists.*

The file definitely exists at C:\Users\nushi\.ssh\id_rsa, even though the
file path looks weird with the slashes.

Thanks,
Anusha Shankar
Rose Postdoctoral Fellow
Lab of Ornithology
Cornell University
Book a meeting with me: https://anushashankar.youcanbook.me/
Personal website: http://anushashankar.weebly.com/

**Comment by steveward** [comment]
@nushiamme I'm going through old issues -- is this something you are still experiencing in GitHub Desktop,or can we close it out? Thanks!
