### ISSUE TITLE
Extend the branch name length in the top bar

### ISSUE THREAD

**Issue by frankhli843** [desktop/desktop#16937]
### The feature request

Right now when we have a very long branch name the name gets cut off
<img width="1072" alt="image" src="https://github.com/desktop/desktop/assets/51806469/0d048060-4dc4-41cf-986c-368e8a86e2f6">

Its very normal for the branch name to get longer when working in large companies that like to follow the convention
users/`[my user id]`/`[JIRA ticket]`-`[camal case description]`

### Proposed solution

My recommendation is that when there is enough space we should dynamically adjust the space name. We can place the button to the right
<img width="1438" alt="image" src="https://github.com/desktop/desktop/assets/51806469/3e39c1ce-c357-4245-b2ba-90dc6bfa6e12">

Alternatively you can switch the branch name location with the right hand side button and give the rest of the space for branch name. 
![image](https://github.com/desktop/desktop/assets/51806469/ba0eaf84-78fe-485c-aa14-349a7bde1eaa)

Please don't mind my terrible photo editing skills here but you get the idea.

**Comment by steveward** [comment]
Thanks for the issue @frankhli843! I'll bump up https://github.com/desktop/desktop/issues/4569 where we are tracking this.
