### ISSUE TITLE
Old versions aren't removed when updating to a new one

### ISSUE THREAD

**Issue by Studio384** [desktop/desktop#1693]
### Description

During my previous report I noticed that my ```AppData``` folder has a folder for both GitHub version 0.5.3 and 0.5.5. The 0.5.3 version is still fully functional.

### Version

**GitHub Desktop version:** N/A

**OS version:** Windows 10 version 1703

### Steps to Reproduce

1. Install GitHub
2. Update GitHub
3. Go to ```AppData\Local\GitHubDesktop```

**Expected behaviour:** The folder ```app-0.5.5``` exists.

**Actual behaviour:** The folder ```app-0.5.3``` and ```app-0.5.5``` exist.

**Reproduces how often:** So far for every update I've done.

### Logs

N/A

**Comment by shiftkey** [comment]
@Studio384 what's inside the `app-0.5.3` folder at this point? [There's some work that Squirrel.Windows does around cleaning up old files](https://github.com/Squirrel/Squirrel.Windows/blob/33baa7ad6035ad69fdb4bd2adf75717660cd8435/src/Squirrel/UpdateManager.ApplyReleases.cs#L590-L611) and I'm curious what state things are in for you...

**Comment by Studio384** [comment]
As mentioned above, it is a fully operational, out-dated version, of GitHub Desktop 0.5.3.
![knipsel](https://cloud.githubusercontent.com/assets/1693592/26312767/f0f5870c-3f08-11e7-9e9c-ce4d00b69f4a.PNG)

**Comment by rlabrecque** [comment]
Same here, this seems consistent with other squirrel based applications though.. :/

**Comment by terales** [comment]
`SquirrelSetup.log` has such log:
```
…
2017-05-30 22:57:23> ApplyReleasesImpl: Fixing up tray icons
2017-05-30 22:57:23> ApplyReleasesImpl: cleanDeadVersions: for version 0.5.8
2017-05-30 22:57:23> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.5.5       <-- !!!
2017-05-30 22:57:23> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.5.8
2017-05-30 22:57:31> Program: Starting Squirrel Updater: --processStartAndWait GitHub Desktop.exe
…
```

**Comment by joshaber** [comment]
This seems to be a Squirrel.Windows behavior, but it does eventually delete old versions, as we saw in https://github.com/desktop/desktop/issues/2373.
