### ISSUE TITLE
FLUTTER : GET CLI command NOT WORKING

### ISSUE THREAD

**Issue by Vikas100702** [desktop/desktop#16941]
https://stackoverflow.com/q/74687529/20291957

Hello, I 'm new to flutter Get CLI and I have the same error asked in the above link. Please help me.
Thank You

**Comment by steveward** [comment]
@Vikas100702 this issue tracker is for GitHub Desktop, you'll need to reach out to that project for assistance.

**Comment by Vikas100702** [comment]
> @Vikas100702 this issue tracker is for GitHub Desktop, you'll need to reach out to that project for assistance.

Sorry, don't understand, could you please explain what I have to do? Thankyou.
