### ISSUE TITLE
I can't make a repository of my game

### ISSUE THREAD

**Issue by Metalmariox** [desktop/desktop#16954]
### The problem

I tried to make a repository of my game but it just made a junk folder in my game's folder.

### Release version

3.2.4

### Operating system

Windows 11

### Steps to reproduce the behavior

Try to make a new repository
go to your game
it makes a junk folder

### Additional context

Please help I'm so confused

**Comment by sergiou87** [comment]
Hello @Metalmariox ! 👋

Could you explain in more detail the steps you took so we can help you more effectively?

Thank you!
