### ISSUE TITLE
Could not lock config file: No such file or directory when publishing a github folder

### ISSUE THREAD

**Issue by Tasha53505** [desktop/desktop#16951]
### The problem

See video attached
https://github.com/desktop/desktop/assets/76188956/f5668ec4-d1b9-44a7-87bd-68b0c84d85f5

![image](https://github.com/desktop/desktop/assets/76188956/17887d78-13ef-4f4d-a1b9-36f704edfab8)

Steps taken:
-  Click Publish Repo
- Get the error shown in image and video (above)
- When trying to publish again, says the repo already exists.
- Meaning, when I go into my github account, it IS there.
- When I try and clone it FROM my github account - this error appears:
- 
![image](https://github.com/desktop/desktop/assets/76188956/183c5d5b-f2ca-4296-beeb-2091e31d8916)
![image](https://github.com/desktop/desktop/assets/76188956/91ccbd3f-c273-43d3-9719-952b8bd6dbc5)

"Retry Clone" Just loops the error message over and over again.
    

### Release version

Version 3.2.4

### Operating system

Windows 10

**Comment by sergiou87** [comment]
Hey @Tasha53505 ! 👋  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Tasha53505** [comment]
[2023-06-22.desktop.production.log](https://github.com/desktop/desktop/files/11837630/2023-06-22.desktop.production.log)
@sergiou87  Hope this helps !

**Comment by sergiou87** [comment]
Thank you @Tasha53505 💖 

The only thing I see in the logs that could cause issues is the fact that you're storing your repositories in a folder that is synced via OneDrive. Solutions like OneDrive or Dropbox are known to cause problems with git repositories 😞  Could you try creating the repository somewhere out of the `'C:\Users\<your-user>\OneDrive` and see if it works? 🤞

**Comment by Tasha53505** [comment]
@sergiou87  Thanks !  That worked! I did it in 
C:\Users\xxxx\source\repos

**Comment by Tasha53505** [comment]
Don't use Onedrive
