### ISSUE TITLE
VSCode Intellisense is warning

### ISSUE THREAD

**Issue by yasuking0304** [desktop/desktop#16963]
### The problem

selected-commits.tsx causes VSCode to output warnings
https://github.com/desktop/desktop/blob/development/app/src/ui/history/selected-commits.tsx#L216-224

Reason: Comparing Number Interface to number Type.

### Release version

3.2.4

### Operating system

Windows10, Mac OS Monterey

### Screenshots

![WS000011](https://github.com/desktop/desktop/assets/111163564/f5e20d6f-583f-4df9-9502-f83418b1bf29)

### Additional context

It can be solved by type conversion as shown below, but it is unclear whether the event argument needs to be the TypeScript Number interface.

```TypeScript
  private onDescriptionBottomChanged = (descriptionBottom: Number) => {
    if (this.historyRef) {
      const historyBottom = this.historyRef.getBoundingClientRect().bottom
      this.setState({
        hideDescriptionBorder: Number(descriptionBottom) >= historyBottom,
      })
    }
  }

```

**Comment by niik** [comment]
Thanks for the heads up @yasuking0304. This is due to VS Code using TS 5 by default now (we're still on TS 4.x). I've opened #16975 to address this
