### ISSUE TITLE
On startup node error

### ISSUE THREAD

**Issue by ginagr** [desktop/desktop#16969]
### The problem

When I turn on my macbook pro 2019, I have the Github Desktop app automatically open. But once I try to push any commit I get this error: 
```env: node: No such file or directory```
I have to close the app and re-open it for it to then work. Any ideas on what I need to do to fix this?

Thank you!

### Release version

3.2.6

### Operating system

MacBook Pro Ventura 13.4.1

### Steps to reproduce the behavior

1. Have Github Desktop auto-open on login.
2. Try to commit a file.
3. Error message shows until the app is closed and re-started.

### Log files

[2023-06-23.desktop.production.log](https://github.com/desktop/desktop/files/11850339/2023-06-23.desktop.production.log)

**Comment by steveward** [comment]
@ginagr thanks for the issue. Do you have any pre-commit hooks in this repository that could be causing this error? You can check by opening the `.git/hooks/pre-commit` file in your repository.

**Comment by ginagr** [comment]
yes, here is my pre-commit file: 
```
#!/usr/bin/env node
'use strict';

// Generated by ghooks. Do not edit this file.

var fs = require('fs');
var path = require('path');
var nodeModulesPath = '/Users/ggr/Desktop/desktop/arammu/arammu/src/kendo-angular-pdf-export/node_modules';
var ghooks = getGhooksEntryPoint();

if (checkForGHooks(ghooks)) {
  require(ghooks)(nodeModulesPath, __filename);
}

function getGhooksEntryPoint() {
  try {
    require('ghooks');
    return 'ghooks';
  } catch (e) {
    return getGhooksAbsoluteEntryPoint();
  }
}

function getGhooksAbsoluteEntryPoint() {
  var worktree = getWorkTree();
  if (worktree) {
    return path.resolve(__dirname, '../', worktree, 'node_modules', 'ghooks');
  }
  return path.resolve(nodeModulesPath, 'ghooks');
}

function checkForGHooks(ghooksPath) {
  try {
    require(ghooksPath);
  } catch (e) {
    warnAboutGHooks();
    return false;
  }
  return true;
}

function getWorkTree() {
  try {
    return getWorkTreeFromConfig(getConfigFileContent());
  } catch (e) {
    return null;
  }
}

function getConfigFileContent() {
  var configFile = path.resolve(__dirname, '../config');
  var fileStat = fs.statSync(configFile);
  if (fileStat && fileStat.isFile()) {
    return fs.readFileSync(configFile, 'utf8');
  }
  return '';
}

function getWorkTreeFromConfig(configFileContent) {
  var worktreeRegEx = /\[core\][^]{0,}worktree = ([^\n]{1,})[^]{0,}/;
  return worktreeRegEx.test(configFileContent) ? configFileContent.replace(worktreeRegEx, '$1') : '';
}

function warnAboutGHooks() {
  console.warn( // eslint-disable-line no-console
  'ghooks not found!\n' + 'Make sure you have it installed on your "node_modules".\n' + 'Skipping git hooks.');
}

```

I no longer use `kendo-angular-pdf-export` so could delete that reference if that is what is causing the error. 
Thank you for the quick response!

**Comment by ginagr** [comment]
I just swapped my `.git/hooks/pre-commit` file to the sample one provided in the `.git/hooks/` folder however on I am still seeing the same error message unfortunately.

**Comment by ginagr** [comment]
Okay I removed the entire hooks folder and it now seems to be back to working! Thank you.
