### ISSUE TITLE
operating system is no longer supported. updates disabled

### ISSUE THREAD

**Issue by SteveA-Nmm** [desktop/desktop#16962]
GitHub Desktop is throwing this error message that the OS is not supported. But I have other computers with the same OS i don't get this error message. What's wrong?
My OS is:
Edition  Windows 10 Pro
Version  22H2
Installed  4/27/2021
OS build  19045.3086
Experience  Windows Feature Experience Pack 1000.19041.1000.0

**Comment by sergiou87** [comment]
Hey @SteveA-Nmm ! 👋

If you right click on GitHub Desktop's shortcut, and click on Properties, could you check if you have a Compatibility mode enabled to simulate an older Windows version?

Removing that should fix the issue.

**Comment by SteveA-Nmm** [comment]
Thank you
