### ISSUE TITLE
Github page redirected to custom domain

### ISSUE THREAD

**Issue by ritikeshgupta** [desktop/desktop#16972]
Hi,
I have a github page website `ritikeshgupta.github.io` and its being redicred to `ritikeshgupta.com`. I tried deleting the custom domain in the `pages` section of `code and automation` and also deleted the DNS record in google domains.

**Comment by steveward** [comment]
@ritikeshgupta thanks for the issue. This issue tracker is for GitHub Desktop, for help with GitHub Pages I'd recommend asking on the [GitHub Pages discussion area](https://github.com/orgs/community/discussions/categories/pages). I hope that helps!
