### ISSUE TITLE
when the repo changes name the local dir is not renamed

### ISSUE THREAD

**Issue by sergenti** [desktop/desktop#16973]
### The problem

title

### Release version

last

### Operating system

linux

### Steps to reproduce the behavior

1. rename the repo both via gh desktop or gh web
notice that the name changes in the desktop interface, but the local folder does not change automatically

**Comment by sergenti** [comment]
yeah it's stupid but it confuses me a lot when I'm using the terminal lol, i see in gh desktop the repo name yet i have to CD into a differently named dir

**Comment by niik** [comment]
Hey @fylls, thanks for reaching out! Renaming the repository locally is not something we can do safely. Users might rely on the location in scripts, submodules from other repositories, or simply editing files in said repository with their editor. We can't reliably detect whether renaming the directory is safe nor do we expect that this is a behavior users would expect of the app. I appreciate that it can cause confusion but we think the alternative may cause even more confusion.

Sorry to not have better news for you!
