### ISSUE TITLE
Changes are not popping up

### ISSUE THREAD

**Issue by leticiascudeller** [desktop/desktop#16970]
### The problem

It is not the first time that the changes I am making in my code are not showing in Git Deskop

### Release version

Version 3.2.4 (x64)

### Operating system

Mac Intel

**Comment by steveward** [comment]
@leticiascudeller thanks for the issue. Does your repository have a `.gitignore` file that could be causing changes to not appear? You can check this directly in GitHub Desktop by going to `Repository` > `Repository Settings` > `Ignored Files`.
