### ISSUE TITLE
Pop Stash on New Branch

### ISSUE THREAD

**Issue by bigmountainstudio** [desktop/desktop#16971]
### Problem - Steps to Reproduce
1. Make a change to the current branch.
2. Stash changes.
3. Create new branch.
4. Pop stash on new branch is disabled.

You have to open Terminal to pop the stash on the new branch.

### Proposed solution

If there are stashes present, keep the stash button/menu option enabled.

**Comment by niik** [comment]
Hey @bigmountainstudio, thanks for reaching out! Stashes in GitHub Desktop are tied to the particular branch they were created on. You can read more about our reasoning for that in https://github.com/desktop/desktop/issues/6107.

For what you're trying to accomplish it seems not stashing your changes and creating a new branch directly with the uncommitted changes would achieve the same end result. When you attempt to change branches or create a new one with uncommitted changes in your working directory GitHub Desktop will automatically create a temporary stash entry, set up the new branch, and apply those changes there. Let me know if that sounds like something you could use.

> 4. Pop stash on new branch is disabled.

Which button/menu are you referring to here? I'm not aware that we have an action like this.
