### ISSUE TITLE
Github Desktop wont recognize some editors in Ubuntu, Linux

### ISSUE THREAD

**Issue by Jgevans23** [desktop/desktop#16978]
### The problem

Forgive me for my poor Linux experience if my question is unclear. I am running Ubuntu 22.04.2 LTS and installed DataSpell from the terminal using snapd.
My computer recognizes dataspell as an IDE and I can set it as my OS's default IDE. Despite that, Github Desktop will not recognize it in the "External editor" drop down (file>options>integrations>external editor). I have restarted my computer and nothing has changed. The only available IDEs are visual studio code, GEDIT, and GNome text editor. 

This could be a bug or maybe I am missing something...

Thank you

### Release version

Version 3.1.1-linux1 (x64)

### Operating system

Ubuntu 22.04.2 LTS

### Steps to reproduce the behavior

1. Install Github Desktop from online download
2. Install Dataspell from snapd
3. Attempt to change external editor

**Comment by steveward** [comment]
@Jgevans23 for support for the Linux repository you can open an issue in https://github.com/shiftkey/desktop, which is where the Linux fork is maintained. You can find supported editors for Linux [here](https://github.com/shiftkey/desktop/blob/linux/docs/technical/editor-integration.md#linux).
