### ISSUE TITLE
Add "Git Bash (via Windows Terminal)" and "PowerShell (via Windows Terminal)" to Integrations/Shell option

### ISSUE THREAD

**Issue by ChiriVulpes** [desktop/desktop#16980]
### The feature request

When Windows Terminal is a user's primary terminal, being able to open the repository in Git Bash via the Windows Terminal is sometimes preferable than opening a standalone Git Bash application. (See similar previous request: #14071)

### Proposed solution

I think this is as simple as the following:

In `enum Shell`, add:
```ts
WindowTerminalGitBash = 'Git Bash (via Windows Terminal)',
WindowTerminalPowerShell = 'PowerShell (via Windows Terminal)',
```

In `shells/win32.ts`, in the following section of `getAvailableShells`:
```ts
if (windowsTerminal != null) {
  shells.push({
    shell: Shell.WindowTerminal,
    path: windowsTerminal,
  })
}
```
Add two new shell definitions:
```ts
shells.push({
  shell: Shell.WindowTerminalGitBash,
  path: windowsTerminal,
  extraArgs: ['-p "Git Bash"'],
})
shells.push({
  shell: Shell.WindowTerminalPowerShell,
  path: windowsTerminal,
  extraArgs: ['-p "PowerShell"'],
})
```

And finally, in `launch`, add two more cases to `Shell.WindowTerminal`:
```ts
case Shell.WindowTerminal:
case Shell.WindowTerminalGitBash:
case Shell.WindowTerminalPowerShell:
```
And support `extraArgs`:
```ts
return spawn(windowsTerminalPath, ['-d .', ...foundShell.extraArgs ?? []], { shell: true, cwd: path })
```

Note: Adding a profile to the args passed to wt doesn't actually do anything if the user has removed them from their Windows Terminal profiles list, so it's not going to cause errors for people. It'll just open the default command prompt profile.

### Additional context
I've tested out the above code changes and they seem to work, here's a little demonstration of what it looks like:

![image](https://github.com/desktop/desktop/assets/6081834/508c2ac7-9a90-4555-83de-23d3458dd855)
![image](https://github.com/desktop/desktop/assets/6081834/d9096545-ff44-4884-9089-f81fa38cbf3c)
![image](https://github.com/desktop/desktop/assets/6081834/9f7766d5-75ca-4d02-95e6-cbf18596c36d)

Side note: If this gets approved, I can submit the changes as a pull request. Let me know!

**Comment by ChiriVulpes** [comment]
Side note: If this gets approved, I can submit the changes as a pull request. Let me know!

**Comment by steveward** [comment]
Thanks for opening this issue @ChiriVulpes, and apologies for the delay in getting back to you. We discussed this internally and think the initial approach sounds good. Feel free to open a pull request and we can get this moving forward. Thanks!

**Comment by ChiriVulpes** [comment]
I still need this every so often and it's a bit of a chore to have to either rebuild my local copy of github desktop to get new updates or to manually open git bash to the repository. I've been rebasing my pull request every couple months. Hoping y'all could take a look at it at some point? It's okay if y'all have changed your minds of course. Thanks for your time either way!

**Comment by steveward** [comment]
@ChiriVulpes it looks like thanks to the custom shell integration option this issue is resolved, so I'm going to close this out.
