### ISSUE TITLE
Squash popup still present after Stash and Squash

### ISSUE THREAD

**Issue by DigiH** [desktop/desktop#16986]
### The problem

As previously reported and fixed with

https://github.com/desktop/desktop/issues/16605

the behaviour of a persistent Squash popup is still present when using **Stash Changes and Continue** when squashing with uncommitted changes.  

### Release version

3.2.6 

### Operating system

macOS

**Comment by steveward** [comment]
Thanks for reporting this @DigiH, like you reported it looks like the case where uncommitted changes are present does still trigger this scenario. With no uncommitted changes squashing works as expected. 

/cc @tidy-dev

**Comment by ghnp5** [comment]
I was going to report this. This seems to be still happening to me.

**Comment by jtouzy** [comment]
In version 3.2.3, even without stashing, after any squash of commits the popup always stays.
(Ex with a simple squash of two commits in the History tab, without any changes)

**Comment by DigiH** [comment]
@jtouzy - see the link in my original issue above, in which this was originally reported, and consequently fixed with the 3.2.4 release.

With the currently release the issue only remains after Stash and Squash.

**Comment by Andrej730** [comment]
Getting it too on Version 3.2.10-beta1 (x64)

**Comment by steveward** [comment]
PR to fix in https://github.com/desktop/desktop/pull/17630. Going to close this out since https://github.com/desktop/desktop/issues/17627 is tracking it.
