### ISSUE TITLE
Fetch is not working on upstream

### ISSUE THREAD

**Issue by Zidras** [desktop/desktop#16988]
### The problem

Since GH does not support forking my own repository, I created a new repository with a different name and cloned the "original" into it. As both share the same core code, I commit to the "original" and intend to sync these commits onto the new repo while preserving author attribution, and for that the "new" repository has remote upstream setup to `upstream/main` of the "original" repo.

Now, on Github Desktop the Fetch button does **not** fetch from upstream, leaving me with no choice but to resort to command line and `git fetch upstream main` (with the pain of having a merge commit every time, but that's out of scope of this report).

### Release version

Version 3.2.6 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Have 2 repos: original and new
2. Set remote upstream on new repo, pointing to original main branch
3. Commit to original repo
4. Fetch or Pull on new repo, it never updates and always report as up to date

### Log files

[2023-06-27.desktop.production.log](https://github.com/desktop/desktop/files/11885724/2023-06-27.desktop.production.log)

### Screenshots

Fetched:
<img width="183" alt="image" src="https://github.com/desktop/desktop/assets/10605951/2fd95b90-5115-477f-8500-8769b72dbf71">

No difference found:
![image](https://github.com/desktop/desktop/assets/10605951/dcba4921-3c25-4bd1-9a26-7eb5d66609e7)

![image](https://github.com/desktop/desktop/assets/10605951/188c4cdb-080c-4c98-aa76-f8ea9ffce2e0)

**Comment by steveward** [comment]
Thanks for the issue @Zidras. Currently GitHub Desktop only shows the `upstream` remote if the repository is classified as a fork. We are tracking multi-remote support in https://github.com/desktop/desktop/issues/1442 which would allow you to work around this. I'm going to close this out.

**Comment by Zidras** [comment]
> Thanks for the issue @Zidras. Currently GitHub Desktop only shows the `upstream` remote if the repository is classified as a fork. We are tracking multi-remote support in #1442 which would allow you to work around this. I'm going to close this out.

Hi @steveward thanks for the reply. Just for my understanding, the referenced issue is marked as "Closed". Is this something already implemented, or currently flagged as future to-do?
