### ISSUE TITLE
Usage data checkbox can't be deselected during setup

### ISSUE THREAD

**Issue by mgood** [desktop/desktop#1698]
### Description

I just downloaded the Github Desktop beta and am going through the initial setup. On the screen "Make GitHub Desktop Better" I tried to deselect "Yes, submit anonymized usage data", but the checkbox stays selected.

### Version

**GitHub Desktop version:** 0.5.6
**OS version:** 10.12.4

### Steps to Reproduce

1. Download GitHub Desktop beta
1. Start setup process
1. Logged in using the browser authentication flow
1. Click the checkbox next to "Yes, submit anonymized usage data" to attempt to deselect it

**Expected behaviour:** checkbox should be deselected

**Actual behaviour:** checkbox did not change

**Reproduces how often:** 100%

### Logs

```
2017-05-22T18:00:35.971Z - info: Opt in reported.
2017-05-22T18:05:39.162Z - info: Opt in reported.
```

#### Additional Information

After finishing the initial setup, I can open to the preferences panel and disable the usage data checkbox.

**Comment by joshaber** [comment]
Bah, good catch! Thanks for letting us know @mgood. I opened https://github.com/desktop/desktop/pull/1699 to fix this.
