### ISSUE TITLE
Autocrlf in gitconfig does nothing

### ISSUE THREAD

**Issue by TheAncientDodo** [desktop/desktop#16995]
### The problem

I don't want GitHub Desktop to change the line endings in my files, so have set autocrlf to false in the gitconfig file.
But even after restarting GitHub Desktop, when I want to commit a file with "LF" line endings, I get a little notification that all "LF" endings will be changed to "CRLF".
![image](https://github.com/desktop/desktop/assets/138017959/8acf0ba5-553a-4f8d-9afb-6e3a6b7089e2)

Am I doing something wrong or is this a bug?

### Release version

Version 3.2.6 (x64)

### Operating system

Windows 10

**Comment by steveward** [comment]
@TheAncientDodo thanks for the issue. Can you run open the repository in the command line and run `git config --list --show-origin` to verify that there are no other options set for the local `.git/config`? That would override the global `.gitconfig`.

**Comment by TheAncientDodo** [comment]
@steveward I have run the command, in the result I can see two other gitconfig files, one for my user and a ".git/config", but none of those contains a autocrlf option.

Thanks for your fast reply btw :)

**Comment by steveward** [comment]
Are you seeing uncommitted changes in GitHub Desktop right now that are showing as file mode changes? It looks like that message is in your editor/IDE, so it could be showing that even though the changes will be ignored by Git.

**Comment by TheAncientDodo** [comment]
Via notepad++, I have changed all EOLs in a script to LFs, since I need them to be LFs (they were CRLFs before).
GitHub Desktop then shows "No content changes found" and displays that little notification with the tooltip that all LFs will be changed to CRLF
![image](https://github.com/desktop/desktop/assets/138017959/600bf526-fb6f-4e00-9bb3-f2d3fd72c3d1)

**Comment by steveward** [comment]
What happens if you try to discard those changes in GitHub Desktop?

**Comment by TheAncientDodo** [comment]
Then GitHub Desktop shows no changes, but also all of the line endings are CRLF again.
And I need them to be LF...

**Comment by steveward** [comment]
If the line endings have been changed you can follow the steps mentioned here:

https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#refreshing-a-repository-after-changing-line-endings
