### ISSUE TITLE
Regarding support for Eclipse IDE

### ISSUE THREAD

**Issue by vivekanandhiremath** [desktop/desktop#16991]
### The feature request

well most people also use the Eclipse IDE also why the Git Hub Desktop don't have support for Eclipse IDE for External Editor options

### Proposed solution

Add the Eclipse IDE as External Editor as an option

**Comment by steveward** [comment]
Thanks for writing in. At this time GitHub Desktop only supports editors that have been specifically integrated into the application. You can find the details of how this works along with the supported editors here:

https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md

We happily accept pull requests to integrate new editors. There is also a tracking issue where we are collecting feedback about better support for external editors: https://github.com/desktop/desktop/issues/7033

**Comment by yuzawa-san** [comment]
I have also looked into this. I have a [working branch](https://github.com/desktop/desktop/compare/development...yuzawa-san:desktop:eclipse-integration?expand=1) ready for macOS, but it would appear Eclipse does not currently fulfill the `the editor supports opening a directory, not just a file` requirement. The IDE _can_ open directories. However, it always goes to the import project workflow. I am working on a PR into Eclipse to try to make it smarter (i.e. open the directory in the "Project Explorer") which mimics the 'open directory' operation of other IDE's in this integration list. I do not have any Windows machines to work with.

Do the maintainers of this project want a PR even if the open directory functionality is a little bit off (at least currently)?
