### ISSUE TITLE
Authentication failed when I cloning the project

### ISSUE THREAD

**Issue by dgo312** [desktop/desktop#16992]
### The problem

Unable to fetch the latest codebase from Repository after providing the credentials it's says authentication failed

### Release version

Version 3.2.6 (x64

### Operating system

Windows 10 

### Steps to reproduce the behavior

GIthudesktop app
click on file
clone the repository 
provide the github url under URL
asking username and password PFA
given user name and git hub password
getting Authentication failed

### Screenshots

![image](https://github.com/desktop/desktop/assets/99326205/9baeef70-7922-44c2-8b26-410912695ccf)

**Comment by steveward** [comment]
@dgo312 thanks for the issue. Can you go to `File` > `Options` > `Accounts` and verify that you are logged in to your GitHub account there?

**Comment by LOVEALWAYS2024** [comment]
So... how do I approach the issue
