### ISSUE TITLE
visual artifacts

### ISSUE THREAD

**Issue by ido555** [desktop/desktop#17005]
### The problem

there are strange visual artifacts that appear by just using the app.. for example: opening/closing menus , clicking buttons, etc..

### Release version

3.2.6 x64

### Operating system

Windows 10 22H2 build 19045.2604

### Steps to reproduce the behavior

https://github.com/desktop/desktop/assets/13142010/77533aca-dfed-47fb-8875-b82b7c61af71

**Comment by niik** [comment]
Hey @ido555, looks like something odd is going on either with your graphics card drivers or the graphics card itself. Have you rebooted your machine recently?

You can try launching GitHub Desktop with GPU accelerated rendering turned off to verify that it is indeed related to the GPU  by setting the GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION environment variable to 1 by running `set GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1` in cmd.exe and restarting your machine or by setting it through the UI following a guide like this: https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0

Note that you may have to restart your machine for the changes to take effect.

**Comment by ofek** [comment]
I am experiencing this as well after upgrading to Windows 11, although in the form of artifacts directly outside the window on the top left. Note that as far as I remember after upgrading this did not happen but rather came about within the last few days.

![Screenshot 2023-07-03 212606](https://github.com/desktop/desktop/assets/9677399/ab5b93aa-3845-4074-ba17-6a19f2eb5785)

**Comment by ofek** [comment]
Upgrading GPU drivers and restarting fixed the issue
