### ISSUE TITLE
Open in VS Code Navigation Issue

### ISSUE THREAD

**Issue by nareshNishad** [desktop/desktop#17009]
### The problem

Facing a issue where clicking on "Open in VS Code" to open a repository directs me to the recently opened VS Code window, rather than opening the requested repository directly. As a result, manual navigation is required to access the desired repository.

### Release version

Version 3.2.6 (arm64)

### Operating system

Mac

**Comment by steveward** [comment]
Thanks for the report @nareshNishad. I tested this out and was unable to reproduce the issue on macOS. Are you using the standard installation of VS Code?

**Comment by nareshNishad** [comment]
Hi @steveward, yes I am using the standard installation.
This problem only happened when one of the VS code windows is in full-screen, in such case on click of "Open in VS code" it takes me to the last VS code window which is in full-screen setup.

**Comment by steveward** [comment]
Thanks for those details, I was able to reproduce this in full-screen mode. Turns out this was previously reported, and is an upstream issue. See https://github.com/desktop/desktop/issues/14675#issuecomment-1136904683. I'm sorry that I don't have better news.
