### ISSUE TITLE
SSH prompt asking for passphrase when not required

### ISSUE THREAD

**Issue by ludndev** [desktop/desktop#17001]
### The problem

I noticed this problem just after updating to version 3.2.6 of GitHub Desktop. 
It keeps asking me to enter my SSH passphrase even when there's no action in progress requiring it. When I click on "Cancel", the prompt asking for the passphrase comes back after a few seconds, until I close the software.

### Release version

3.2.6

### Operating system

Windows 10 Build 19045

### Screenshots

![image](https://github.com/desktop/desktop/assets/54596310/1b48ff1a-ffa0-42e7-bc3c-761b7558fefd)

**Comment by sergiou87** [comment]
Do you have other repositories in your repository list that might require that passphrase? 

I wonder if maybe GitHub Desktop is fetching those other repositories and one or more of them uses SSH.

**Comment by ludndev** [comment]
I tried with a gist, a remote and a local repository : same issue.

**Comment by ludndev** [comment]
Maybe it's trying to background check some repositories. I just don't want to make it remember my passphrase.

**Comment by sergiou87** [comment]
> Maybe it's trying to background check some repositories. I just don't want to make it remember my passphrase.

Yeah, that's exactly what I'm wondering 🤔 Any of your other repos uses SSH?

**Comment by ludndev** [comment]
@sergiou87 many of them. I keep auth for a while, but It keeps prompting

**Comment by steveward** [comment]
@ludndev can you go to File > Options > Advanced and see if you have the option to use the system OpenSSH selected?
