### ISSUE TITLE
need of option to theme change

### ISSUE THREAD

**Issue by Raghuveer22** [desktop/desktop#17006]
### The feature request

Need to change between light and dark theme 

### Proposed solution

add a settings option to toggle between the themes

**Comment by niik** [comment]
Hey @Raghuveer22, thanks for reaching out. You can find the option to change themes under the Appearance tab in Settings (macOS) or Options (Windows)

<img width="676" alt="image" src="https://github.com/desktop/desktop/assets/634063/8c5cb994-0596-4932-b88d-b4b7a7aaabc7">

**Comment by Raghuveer22** [comment]
thaanks you
