### ISSUE TITLE
More languages

### ISSUE THREAD

**Issue by Grey-Wind** [desktop/desktop#17008]
### The feature request

Add support for more languages
Such as Chinese, Russian, French, German and other languages

### Proposed solution

You can try using crowdin or directly submit a translation using PR, and after approval, adopt it to the next version or update it online

### Additional context

I think I can help with the translation
I provided tooltips translation for MCreator

**Comment by Grey-Wind** [comment]
I think the application of translated text can learn from the use of MCreator

**Comment by niik** [comment]
Thanks for the feedback @Grey-Wind. At this time we do not have plans to provide multilingual support in GitHub Desktop due to the bandwidth it would require from the team, but this may be something we reconsider again in the future. Please see #8289 for further information.
