### ISSUE TITLE
Manually stashed changes do not display in Github Desktop

### ISSUE THREAD

**Issue by sun-xm** [desktop/desktop#17013]
### The problem

If use manually stash a local change, the change will not display in Github Desktop. But if the change is stashed by "Stash all changes" in Github Desktop, "View your stashed changes" is displayed.

### Release version

3.2.6(x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. make a local change
2. go to command line
3. git stash
4. switch back to Github Desktop
5. check if "View your stashed changes" is displayed

**Comment by CietyGoblin** [comment]
nice

**Comment by niik** [comment]
Hey @sun-xm, thanks for reaching out. This behavior is per-design, see https://github.com/desktop/desktop/issues/6107 for our reasoning around choosing this implementation.

Going to close this in favor of https://github.com/desktop/desktop/issues/12699 which is requesting a similar feature.
