### ISSUE TITLE
Allow Maps to ping Public Portable Potties

### ISSUE THREAD

**Issue by Silvrbckw** [desktop/desktop#17020]
### The feature request

Allow on Google Maps, a feature to Ping where public portable toilets is at in Michigan and surrounding states with a lot of construction and service workers. 

### Proposed solution

It will add a feature or upgrade to web3 and phones. Real time reports. Can scan QR codes to find locations to alternative bathrooms.

### Additional context

Google Maps
Waze
Bing
AI
Web3
Dapps

**Comment by niik** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
