### ISSUE TITLE
Member avatar does not update when 2 commits have same name.

### ISSUE THREAD

**Issue by Jugg3rPL** [desktop/desktop#17021]
### The problem

There are 2 commits with same name 1 commit by person A and 2nd by person B
When you click on commit by person A and then on commit by person B.
Avatar on commit changes does not change.

### Release version

Version 3.2.6 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Have 2 commits with same name done by diffrent people.
2. Press one first commit and check avatar.
3. Press on second commit and check avatar.
4. On second commit avatar shouldn't change.

### Additional context

Video:
https://github.com/desktop/desktop/assets/137120926/8e3c40aa-9ebd-4c13-9f93-f305de6d0cf5

**Comment by steveward** [comment]
Thanks for the report and video @Jugg3rPL. Is this just happening in a specific subset of commits, or are you seeing it in multiple instances?
