### ISSUE TITLE
I can't download lfs file

### ISSUE THREAD

**Issue by stevenweish** [desktop/desktop#17022]
### The feature request

My account have 1GB Git LFS Data Storage and Bandwidth,But I can't download the lfs files in (https://github.com/snap-research/articulated-animation)?

step 1, I can't download in linux shell command (I have config the git username and password and email)
step 2, I also can'd download in windows Git BASH command (I have config the git username and password and email)
step 3, I also can'd download in GitHub Desktop

Please tell me why? 

ps：the information
Error downloading object: checkpoints/mgif256.pth (58b796e): Smudge error: Error downloading checkpoints/mgif256.pth (58b796e31f763ccfbb240f959c9d92c2afe8a6e57da303e07d8fabd1f2921c68): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

### Proposed solution

Please tell how I cound do.

**Comment by steveward** [comment]
@stevenweish thanks for the issue. It looks like you exceeded your monthly LFS bandwidth, which is what this error is indicating:

`This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`

You'll need to purchase additional bandwidth, see this article: https://docs.github.com/en/billing/managing-billing-for-git-large-file-storage/about-billing-for-git-large-file-storage

I hope that helps!
