### ISSUE TITLE
Create Pull Request option is disabled

### ISSUE THREAD

**Issue by arunrajpolus** [desktop/desktop#17023]
### The problem

I am a web developer and I have been using GitHub Desktop app for committing all the changes to the remote repository. Every time after I pushed the code, there was an option in the Branch tab for creating pull request.

Now the option is disabled for me. 

Please help me to figure this out !!
![githubIssue](https://github.com/desktop/desktop/assets/52557341/ef742cdc-a734-4a2a-b488-08fefe94b455)

### Release version

Version 3.2.4

### Operating system

Windows OS

### Steps to reproduce the behavior

1. Open GitHub Desktop app
2. Click on Branch menu on the top
3. Look for Create Pull Request option
4. See the error. It is currently disabled

**Comment by tidy-dev** [comment]
Hi @arunrajpolus! Sorry for your troubles. Based on all of the disabled menu items, it would appear the GitHub Desktop is not detecting that repository as a GitHub repository. Could that be the case?
