### ISSUE TITLE
Add an option in the Repository menu to open the repo in Git Shell

### ISSUE THREAD

**Issue by Yohanna** [desktop/desktop#1703]
### Description

The GitHub Native Desktop client had an option to open the current repo in Git Shell. It'll be helpful to add that option to the Electron client as well.

### Version

**GitHub Desktop version:** 0.5.6

**OS version:** Windows 10 x64 [Version 10.0.15063]

#### Additional Information

This is related to #1587

**Comment by shiftkey** [comment]
@Yohanna we made some changes in the Electron app to not ship a standalone command line shell. You can read about this process in #340. We've replaced this with a simpler `Open in command prompt` experience, with a prompt to help you set up Git if we can't find Git on your path.

So for now we're not going to take a dependency on Git Shell, but we're open to ideas around making the command line experience better in the future and helping get those ideas into upstream projects like Git for Windows.

**Comment by Yohanna** [comment]
How about adding an option for the user to choose their own shell?
So you'd continue to use `cmd.exe` as the default shell on Windows and have an extra option in the Options menu that by default points to `cmd.exe` but can be changed to Git Shell?

**Comment by shiftkey** [comment]
@Yohanna we're tracking this in https://github.com/desktop/desktop/issues/888 - please add your feedback there
