### ISSUE TITLE
Unable to run cadnano2

### ISSUE THREAD

**Issue by runcyclexcski** [desktop/desktop#17049]
### The problem

Hi Shaun, I was in the process of formatting cadnano2 output for a supplementary figure, and I could not launch it this time. I was launching it per instructions in the original PDF file. The install was done on Feb 22, 2022. It must be something trivial, I apologize if it is. This is the output when launching from the github per instructions. Must have to do with environmental variables, but I haven't changed anything since the install. The cadnanoqt.py script seems to be there (screenshot below)

C:\Users\ostap bender\Documents\GitHub\cadnano2>python main.py
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    cadnano.initAppWithGui()
  File ".\cadnano.py", line 43, in initAppWithGui
    from cadnanoqt import CadnanoQt
  File ".\cadnanoqt.py", line 8, in <module>
    util.qtWrapImport('QtWidgets', globals(),  ['qApp', 'QApplication', 'QUndoGroup'])
  File ".\util.py", line 103, in qtWrapImport
    assert(False)  # Have not found a suitable qt framework
AssertionError

### Release version

Version 2.9.4 (x64)

### Operating system

Win 10 

### Screenshots

![20230709_132416](https://github.com/desktop/desktop/assets/23055342/6c762ff4-aa20-4f63-ba00-e482d01e6b95)

### Additional context

![20230709_132329](https://github.com/desktop/desktop/assets/23055342/d01e5f8c-8093-4d9b-84ce-3ea5d79326c6)

**Comment by sergiou87** [comment]
Hello @runcyclexcski 👋 

This is GitHub Desktop's repository, so we cannot help you with cadnano2. Maybe you can ask in https://github.com/douglaslab/cadnano2 instead?

Sorry!
