### ISSUE TITLE
Custom groups in sidebar

### ISSUE THREAD

**Issue by rickhopkins** [desktop/desktop#17055]
### The feature request

Repository lists become too long in the sidebar. I propose adding the ability to create custom groupings of repositories.

### Proposed solution

Allow users to create custom groups in the repository side bar so that the user can control how the repositories display instead of just seeing a giant list.

### Additional context

![image](https://github.com/desktop/desktop/assets/1536701/00e65b73-6f49-4b71-8b1b-c65d4add3faa)

**Comment by Redhunt2013** [comment]
Personally, I work with 70+ repositories, and I believe that having the ability to group repositories based on specific criteria would greatly improve efficiency and organization.

**Comment by steveward** [comment]
Thanks for the feedback @rickhopkins. See [this comment](https://github.com/desktop/desktop/issues/10201#issuecomment-658693653) for more information about why we do not have plans to implement repository grouping at this time.
