### ISSUE TITLE
Commit created on Github Desktop doesn't appear on Github Graphic Interface commits

### ISSUE THREAD

**Issue by SimplyA-Coder** [desktop/desktop#17056]
### The problem

So recently, on my first run of Github Desktop, I uploaded over 32,000 files to my repository just as a way to add in some more assets to a few pages. Once the commit was created, I went to the graphic interface and checked there, however it does not appear. So does this mean the commit failed to create, or is this an issue with Github API?

### Release version

3.2.3 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Create a huge commit
2. Navigate to your repository's commits on the graphic interface
3. Expect your commit not appearing

### Log files

[2023-07-10.desktop.production.log](https://github.com/desktop/desktop/files/12009292/2023-07-10.desktop.production.log)

**Comment by sergiou87** [comment]
Hey @SimplyA-Coder ! 👋 

I do see in your logs you did a commit, I can't tell if it was successful or not (since it had many changes and Desktop is known to have issues dealing with those), but I don't see you _pushing_ the commit to the repo. Did you push your changes to GitHub?
