### ISSUE TITLE
Github Desktop won't launch on Pop_OS! - GPU process isn't usable.

### ISSUE THREAD

**Issue by fbnlsr** [desktop/desktop#17065]
### The problem

When trying to launch Github Desktop from the dock/windows manager, nothing happens.

When trying to launch straight from the terminal, I get this error:

```
(node:49876) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
[49876:0712/111341.890083:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
[1]    49876 trace trap (core dumped)  github-desktop
```

Environment:

- Pop_OS! 22.04 LTS
- GNOME 42.9

Launching Github Desktop using `--disable-gpu-sandbox` seem to fix the problem.

### Release version

2.8.1-linux1

### Operating system

Pop_OS! 22.04 LTS

### Steps to reproduce the behavior

Either:

- Click on Github Desktop's icon in the doc or from the launcher
- Run `github-desktop` from the terminal

**Comment by sergiou87** [comment]
Hey @fbnlsr ! 👋  Issues related to the unofficial Linux fork of GitHub Desktop can be filed here:

https://github.com/shiftkey/desktop/issues

At this time we only officially provide support for macOS and Windows.

Sorry!
