### ISSUE TITLE
how to debug source code in vscode

### ISSUE THREAD

**Issue by yuyixiaoxiang** [desktop/desktop#17063]
### I need help how to directly debug the source code in vscode!

Now,I can use yarn start to run the client

![image](https://github.com/desktop/desktop/assets/8126407/9ca349aa-bfbc-48ad-9a77-f23971a30166)

and i noticed the process is that,first build the project and then use spawn to start a subprocess to run the desktop client.
everything looks perfect！
But t want to know how to config the launch.json file to directly debug the code for better understand the source code。

**Comment by NewUnlocker** [comment]
> Necesita ayuda sobre cómo depurar directamente el código TS en VSCODE

**Comment by NewUnlocker** [comment]
necesito ayuda

**Comment by yuyixiaoxiang** [comment]
> necesito ayuda
> 
> 

what does it mean 😅

**Comment by steveward** [comment]
Thanks for the issue @yuyixiaoxiang. At this time we don't support debugging in VSCode. There was previous discussion around this in https://github.com/desktop/desktop/issues/6433. I hope that is helpful.
