### ISSUE TITLE
fatal: unable to access '[any repo] :getaddrinfo() thread failed to start

### ISSUE THREAD

**Issue by Vendaciousness** [desktop/desktop#17069]
### The problem

Using git pull gives me this error with any repo I have and I have no idea how to fix it. I've tried reinstalling git and GitHub Desktop, since they both give the same error:

fatal: unable to access 'https://github.com/AUTOMATIC1111/stable-diffusion-webui.git/': getaddrinfo() thread failed to start

### Release version

Version 3.2.6 (x64)

### Operating system

Windows 10 2H22

### Steps to reproduce the behavior

1. Open GitHub Destop, or Git bash in a repo directory.
2. Click 'Fetch Origin', or type 'git pull'

**Comment by steveward** [comment]
@Vendaciousness thanks for the issue. This looks like a cURL error. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Vendaciousness** [comment]
Sure!  Here ya go.  The trouble started yesterday evening.
[2023-07-13.desktop.production.log](https://github.com/desktop/desktop/files/12041300/2023-07-13.desktop.production.log)

**Comment by steveward** [comment]
Thanks for sharing that. Are you behind a firewall or proxy that could be interfering with your connection? Are you running any antivirus software? It'd also be helpful to know if you are encountering the same error when attempting Git operations from the command line.

**Comment by Vendaciousness** [comment]
That's the strange thing. I'm not behind a firewall or anything and nothing has changed on the software side with the setup on my PC, except I did have to uninstall and reinstall the drivers for my network card. I used the same drivers as before exactly, from the same installation exe from Realtek.

I am having the exact same issue with regular Git, when using it from a bash prompts, but I can use pip from the same prompt with no issues.

Here's a cap from when I try using Git:
```
 MINGW64 /g/Code/stable-diffusion-webui (master)
$ git pull
fatal: unable to access 'https://github.com/AUTOMATIC1111/stable-diffusion-webui
.git/': getaddrinfo() thread failed to start
```
So far, I've tried using Windows Repair Toolbox and the Net Repair AIO to reset all the network settings for Windows 10 with no change in Git.

-V

**Comment by Vendaciousness** [comment]
I'm not sure what happened initially to cause the issue, but I was able to fix the error like this:
1. Launch Git bash as Administrator (Type Git in Start Menu, then right-click on 'Git bash' and select 'Run as Administrator').
2. Change to the repo directory (not sure if this is necessary)
3. Type these commands:
```
git config --system --unset credential.helper
git config --system http.sslverify false
git config --system http.sslcainfo 'C:\Program Files (x86)\Git\mingw32\ssl\certs\ca-bundle.crt'
```
After that, git pull worked in bash and Pulls in Git Desktop worked fine, as well, both in this repo and all the others I have tried.
I apologize if any of these are extraneous and if this problem had nothing to do with Git Desktop.  I'm just a technical artists and my understanding of certificates is totally basic.

Thanks for trying to help!

-V

**Comment by RyuSeiri** [comment]
This command should fix it:
```sh
netsh advfirewall firewall add rule name="Localhost TCP Dynamic Ports" dir=in action=allow protocol=TCP localip=127.0.0.1 localport=49152-65535
netsh advfirewall firewall add rule name="Localhost TCP Dynamic Ports Out" dir=out action=allow protocol=TCP remoteip=127.0.0.1 remoteport=49152-65535
```
