### ISSUE TITLE
The file directory is opened behind the github desktop

### ISSUE THREAD

**Issue by md-shamim-ahmad** [desktop/desktop#17071]
### The problem

When I click on the choose  button for add an existing repository 
![vlcsnap-2023-07-13-22h21m40s239](https://github.com/desktop/desktop/assets/56692841/34337c16-e923-4597-8b0b-69e59ded354f)
But the file directory was opened behind the ```github desktop``` like this
![vlcsnap-2023-07-13-22h21m48s873](https://github.com/desktop/desktop/assets/56692841/40a89958-1ef8-4401-92de-4e7a89d29457)

### Release version

GitHubDesktop-linux-3.2.5

### Operating system

Ubuntu

### Screenshots

Here I have added a video to further clarify

https://github.com/desktop/desktop/assets/56692841/6e530f2d-a2e3-4d7b-9fa3-d4e54ecbb0d8

**Comment by MandiJo1988** [comment]
Video was not long enough

**Comment by steveward** [comment]
Thanks for the issue @Md-Shamim-Ahmmed. It looks like you are using the Linux fork of GitHub Desktop, which is not officially supported by GitHub. You can open an issue about this in the fork:

https://github.com/shiftkey/desktop/issues
