### ISSUE TITLE
Can't push my project

### ISSUE THREAD

**Issue by E1mpire** [desktop/desktop#17073]
### The problem

I can't push my code to the repositories
I had unset all my http.proxy
error code:
fatal: unable to access 'https://hub.fastgit.org/E1mpire/HelloMaker-STM32.git/': Recv failure: Connection was reset
Pushing to https://hub.fastgit.org/E1mpire/HelloMaker-STM32.git

### Release version

Version 3.2.6 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

go to github desktop
push my code to main branch
error

**Comment by steveward** [comment]
@E1mpire it looks like you are pushing to a non-GitHub repository, and are encountering a connection issue. Based on the error it looks like the connection is being closed by the remote server. I would recommend reaching out to FastGit for assistance. I'm not familiar with FastGit, but when using a third-party hosting server you also need to create a token for authentication to use with GitHub Desktop (see our other guides [here](https://github.com/desktop/desktop/blob/development/docs/integrations)). I hope that helps.
