### ISSUE TITLE
Cloning always crash between 60% and 70%

### ISSUE THREAD

**Issue by YourIraqifriend** [desktop/desktop#17076]
### The problem

I can't clone a repository to github desktop, tried all ways and in different  file folders, but it still always crash, my internet is good and I have did this 7 times before to 7 different repositories

### Release version

3.2.6

### Operating system

windows

### Steps to reproduce the behavior

1 - choose a repository
2- go to code
3- clone to desktop
4- wait until crash

### Log files

[2023-07-15.desktop.production.log](https://github.com/desktop/desktop/files/12062220/2023-07-15.desktop.production.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/119034417/3acdfe1d-d441-4652-8da3-5410c30f4793)

**Comment by tidy-dev** [comment]
Hi! I noticed in your error that you are attempting to clone to a `OneDrive` folder. Git often has issues when trying to work in cloud directories. Could you try cloning to a found that is not a cloud folder?

**Comment by YourIraqifriend** [comment]
I already cloned it on non cloud yet the same result

**Comment by steveward** [comment]
@AhmedPashaAlSaid is this happening only for one specific repository? You mentioned that you cloned seven other repositories successfully, so I wanted to confirm if one repository is causing this or if it is happening with multiple repos.

**Comment by JanPlayer2** [comment]
I had a similar issue - disabling the VPN solved the problem.
