### ISSUE TITLE
Github destop app locked in full screen mode

### ISSUE THREAD

**Issue by MattSkea** [desktop/desktop#1707]
Hi,

My github desktop app is locked in full screen mode, after I selected "view"->"toggle full screen". When I try and exit full screen mode by pressing "alt", I can see the apps navigation menu where I can select "view"->"Toggle full screen" or press "f11" the app changes back to a windowed view from full screen view but the window is black and I can't click on anything. When I start the app up again it switches back to full screen mode, and the cycle goes on.
After reinstalling the app it goes to full screen mode also.

Is there an easy way to fix the bug?

**Comment by niik** [comment]
Looks like this is the same as https://github.com/desktop/desktop/issues/1436. Gonna close this out and move the conversation over there. @MattSkea if you could comment on that issue with some details about your operating system and setup (like, do you have multiple monitors, do you have DPI scaling enabled etc) that would be fantastic

**Comment by niik** [comment]
Correction, moving to #1502

**Comment by matrix09** [comment]
I just solved this problem. my steps below:

1 : uninstall github client
2 : remove githubdesk folder in your C:/user/username/AppData/Local
3：remove githubdesk folder in your C:/user/username/AppData/Roaming

After then I redownload Github Desktop Client and install it, then problem solved:)

**Comment by saikrishna106** [comment]
Hey, every body! This is simple problem guys. Just press ALT+F. you will see menu options so enter into view options then press the Toggle fullscreen it will end up. so be cool and think.

**Comment by hafizaslami** [comment]
Press F11

**Comment by glenshewchuck** [comment]
On my Mac (High Sierra) it's Shift-F

**Comment by Craigjw** [comment]
This issue sucks, wasted a good 10 minutes of my life.

**Comment by alvim452** [comment]
alt +F     GOOD           It works

**Comment by akhilalekha** [comment]
I have this problem too, I just updated github desktop and it right away opens in full screen. I'm on Windows 8.1 and alit + f4 doesn't work - it's a shortcut to shut down windows ? :-1:

**Comment by Cadris** [comment]
> Press F11

This Works
On Windows 10

**Comment by wolfstock** [comment]
This seems very... non-intuitive.   Pretty much any Windows app I've ever used, until this one, you could use either <esc> to exit full-screen mode and/or it had the standard Windows dash-box-X in the upper-right corner for controls.   I had to do google search to find out how to take it out of full-screen mode; which seems odd for such a basic function!

Edit: I see there is also the Windows full-screen mode, which does have the dash-box-X; so I guess two different "full-screen modes".

**Comment by lstudley** [comment]
Irritating!!!!!! had to google how to get out of fullscreen.

**Comment by aripix** [comment]
alt+F works on Windows
Thankiuuuuu!!

**Comment by kinivasu** [comment]
thanks Alt+F4 works

**Comment by nikita-one** [comment]
And this issue dates 5 years back... Appalling UX

**Comment by PeterEbili** [comment]
Thanks it worked @mild0wl
