### ISSUE TITLE
Desktop app Preview pull request error

### ISSUE THREAD

**Issue by R0z3** [desktop/desktop#17083]
### The problem

The problem is well outlined here:
https://github.com/desktop/desktop/issues/16368
However, selecting the drop down does not seem to help this time.

### Release version

Version 3.2.6 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

It seems to be "random", but

Steps to reproduce the behavior
Create a branch
Add some commits
[Unknown step]
Publish it

### Log files

[2023-07-10.desktop.production.log](https://github.com/desktop/desktop/files/12071096/2023-07-10.desktop.production.log)
[2023-07-14.desktop.production.log](https://github.com/desktop/desktop/files/12071097/2023-07-14.desktop.production.log)
[2023-07-17.desktop.production.log](https://github.com/desktop/desktop/files/12071099/2023-07-17.desktop.production.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/44166357/9628f733-7548-41f9-9d78-8a530aeab67d)

### Additional context

New install today

**Comment by steveward** [comment]
Thanks for the report @R0z3. Are you able to reliably reproduce this? I've tried a few scenarios out and have been unsuccessful. Is it happening in multiple repositories for you?

**Comment by R0z3** [comment]
I only have on repository that I edit.
Every branch I create has the same issue.

**Comment by steveward** [comment]
Would you mind creating a new repository to see if you are able to reproduce this? We haven't had any further reports of this, and I've been unable to reproduce this, so it'd be helpful to narrow down if it is a specific issue with this repository. Thanks!

**Comment by R0z3** [comment]
I created a new depository and added a random commit.

I do not seem to have the same error.

Kind regards

Rose Barfield
Product Owner Qt
Bricsys, part of Hexagon
LinkedIn<https://www.bricsys.com/?utm_campaign=Bricsys-EmailSignature&utm_source=email&utm_medium=email&utm_content=bricsys-email-signature>
bricsys.com<https://www.bricsys.com/?utm_campaign=Bricsys-EmailSignature&utm_source=email&utm_medium=email&utm_content=bricsys-email-signature>

[A black text on a white background  Description automatically generated]<https://www.bricsys.com/?utm_campaign=Bricsys-EmailSignature&utm_source=email&utm_medium=email&utm_content=bricsys-email-signature>

**Comment by steveward** [comment]
Thanks for testing that. I think trying to reset the local cache would be a good next step.

Here's how to reset the application:

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop

You will need to log in and add your repository again. Let me know if that helps.

**Comment by rnxm** [comment]
This also happens to me.

More information:
I cloned refilc/naplo and selected the 'dev' branch. After that, I constantly see the "Preview your Pull Request from your current branch" option. 
![image](https://github.com/desktop/desktop/assets/63553775/7bf6ce3b-dff6-4274-b079-32e8c358c96f)
When I click on 'Preview Pull Request', it's empty
![image](https://github.com/desktop/desktop/assets/63553775/1b08bc11-71cb-46c9-85a5-c087fdc5814d)
Deleting %APPDATA%/GitHub Desktop/'s contents doesn't solve the issue.

**Comment by R0z3** [comment]
For those interested: adding the repository again fixed this issue for me.

**Comment by steveward** [comment]
Thanks for sharing that update @R0z3!
