### ISSUE TITLE
Explorer context menu entry "Open in GitHub Desktop"

### ISSUE THREAD

**Issue by encr123** [desktop/desktop#17089]
### The feature request

A new entry is added to the explorer context menu to open a folder with GitHub Desktop. (Entry should only be visible if it is in the folder context menu. So if you right-click in an empty field in a folder, not on a file)

When this context menu entry is clicked, GitHub Desktop will check if a .git exists and will open this repository. If it already exists in GitHub Desktop, it will open it, and if not it will "Add existing repository..."

If there is no .git folder, an info text will be displayed.

### Proposed solution

1. If you want to add an existing repository you currently have to open GitHub Desktop and click "Add existing repository..." and search or paste the path to your repo. With the new feature, you can just navigate to your repo folder where the .git is located, click right-click and click "Open in GitHub Desktop". Now GitHub Desktop automatically adds a new existing repository with the path you navigated in.

2. If you want to open GitHub Desktop with a specific repository you have to open GitHub Desktop, click on "Current repository" and chose the repo you want to change. With the new feature, you just have to press the "Open in GitHub Desktop" in the context menu in the folder and GitHub Desktop will automatically open the repo. 

This can speed up the development process because in my case I normally have the folder opened in the explorer because I opened the project file I am working with.

### Additional context

The name "Open in GitHub Desktop" can surely be changed 😄

**Comment by steveward** [comment]
Thanks for the feedback @encr123! I'm going to add this to https://github.com/desktop/desktop/issues/5373 where we are tracking this.
