### ISSUE TITLE
Doesn't find Editor

### ISSUE THREAD

**Issue by grafst** [desktop/desktop#17081]
### The problem

Github claims there is no Editor (Vscode) installed even though it is.

### Release version

3.2.2

### Operating system

Windows 11

### Steps to reproduce the behavior

Ctrl+Shift+A

**Comment by steveward** [comment]
Thanks for the report @grafst. Are you running the standard install of VSCode? 

There was a previous report where an old installation left behind caused this -- may be worth checking. See [this comment](https://github.com/desktop/desktop/issues/13798#issuecomment-1407408950).

**Comment by ShadowWalker918** [comment]
No. This was prematurely released.

**Comment by grafst** [comment]
I installed it using [scoop](scoop.sh).
Maybe that's the problem?

**Comment by steveward** [comment]
I haven't tested installing VScode using scoop, but that could be a possibility. I would try the regular installation out to see if that's the issue.
