### ISSUE TITLE
Update submodules

### ISSUE THREAD

**Issue by alexrodi** [desktop/desktop#17088]
### The feature request

Would like to be able to do a simple submodule update from the UI.

### Proposed solution

To have an "Update all submodules" option/button that simply runs `git submodule update --recursive --remote`

**Comment by steveward** [comment]
Thanks for the issue @alexrodi. GitHub Desktop does recursively update submodules on checkout, fetch, and pull (see https://github.com/desktop/desktop/pull/5154). I'm going to close this out, but if I'm misunderstanding this request please let me know.

**Comment by alexrodi** [comment]
@steveward I understand the feature you're describing, however, this isn't what I meant to say.

The feature I intended to request is when the user is the one updating the module(s), so, not fetching/checking-out/pulling a commit from origin, but introducing the change to be committed locally.

Say, for example, there are new commits on submodule X and I wish to use the latest one on my branch - so I do `git submodule update X --remote` (or omit the name to update all) and then do `git add X`, `git commit ...` and `git push`

Thanks for your attention, and I hope I was able to explain it better this time 😄

**Comment by Mafiadoener36** [comment]
i have the same problem!
