### ISSUE TITLE
Separate the Fetch/Pull and the Push button into two side-by-side buttons

### ISSUE THREAD

**Issue by DeflateAwning** [desktop/desktop#17094]
### The feature request

The Fetch/Pull button and the Push button should be two separate buttons. I just spammed the Pull button, but accidentally pushed. 

### Proposed solution

I want the Fetch/Pull button and the Push button to be side-by-side

**Comment by steveward** [comment]
Thanks for the feedback @DeflateAwning. You can go to `Repository` > `Fetch` to force a fetch/pull, or use the shortcuts shown there. At this time we don't have plans to change this since there is also a selectable dropdown available in the button itself to force a fetch.
