### ISSUE TITLE
token recoery

### ISSUE THREAD

**Issue by EmeanaDaniel** [desktop/desktop#17090]
i closed my token unknowingly on my GitHub tutorial and don't know how to recover it so I can share to my group to view my work.

**Comment by steveward** [comment]
@EmeanaDaniel it sounds like you are referring to a personal access token, which you can read more about [here](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens). If you have any questions about GitHub Desktop let us know, or you can reach out with other general questions to [GitHub Support](https://support.github.com/).

**Comment by oscarllann** [comment]
https://github.com/desktop/desktop/issues/17087#issue-1811135186
