### ISSUE TITLE
Github Desktop doesn't uninstall cleanly

### ISSUE THREAD

**Issue by NH-OL** [desktop/desktop#17102]
### The problem

After uninstalling GithubDesktop, some files are left behind.
All are located in the following folder (or its subfolders):
C:\Users\<username>\AppData\Local\GitHubDesktop
Specifically:
   .dead
   Update.exe
   app-3.2.6\squirrel.exe
   app-3.2.6\v8_context_snapshot.bin

Expected behaviour is for all traces of the program to be removed.

### Release version

3.2.6

### Operating system

Win10

### Steps to reproduce the behavior

1. Install GitHubDesktop
2. Open it
3. Close it.
4. Uninstall it.

**Comment by oscarllann** [comment]
ok

**Comment by steveward** [comment]
Thanks for the issue @oscarllann. This is the behavior of the installer GitHub Desktop uses (Squirrel.Windows). At this time migrating to a different installer isn't on our radar, but it is something that has been discussed in https://github.com/desktop/desktop/issues/1086. I'm going to close this out, but thanks for the feedback here.
