### ISSUE TITLE
Feature: Add-in folder branches in a repo directory

### ISSUE THREAD

**Issue by SimplyA-Coder** [desktop/desktop#17106]
### The feature request

One feature I'd like to request is to separate branches for a repository into different folders (e.g. a repository directory contains two folders, one "master" and one "beta"). This would be much better to use for as my work gets messy overlapping commits on the same repo published into a different branch.

### Proposed solution

Hopefully, if someone has lots of branches within their repository, they'd be able to work better instead of commits overlapping.

**Comment by tidy-dev** [comment]
@SimplyA-Coder Thank you for the suggestion. Usually release (production, beta, test, development) management is done through managing release branches and different people and teams do this different ways. I would recommend to a web search on "Git Flows" or "Git Workflows" to see what might suit your needs.

A very common pattern is to maintain a "production" branch and then a branch of whatever other release stages you may have such as "beta", "test" and "development". Then, when changes become ready for one of those channels, you merge the commits or branch into those branches and maybe even [tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) your new version. 

Hope this helps! GitHub Desktop is not likely to implement a specific form of release management and thus I am closing this issue. If I misunderstood your use case, feel free to comment back.

**Comment by malego87** [comment]
> ### The feature request
> One feature I'd like to request is to separate branches for a repository into different folders (e.g. a repository directory contains two folders, one "master" and one "beta"). This would be much better to use for as my work gets messy overlapping commits on the same repo published into a different branch.
> 
> ### Proposed solution
> Hopefully, if someone has lots of branches within their repository, they'd be able to work better instead of commits overlapping.
> 
> ### Additional context
> _No response_

Lobuziaki38gmail.com

**Comment by malego87** [comment]
🙏

**Comment by malego87** [comment]
Apple cloud bec

**Comment by malego87** [comment]
@malego87 
@michihackgmail
