### ISSUE TITLE
GUI for Github Desktop not Showing. Only the header of GitHub Desktop showing and not working.

### ISSUE THREAD

**Issue by NabilahWork** [desktop/desktop#17115]
### The problem

Have installed the latest version of GitHub either with apple silicon and not apple silicon version, the GUI for GitHub Desktop not showing. The only thing that I can see is the header of GitHub Desktop but that is not working too.
Have downloaded the beta version of GitHub Desktop and still having the same problem.

### Release version

3.2.6

### Operating system

macOS 13.4.1 

### Steps to reproduce the behavior

1. Download the GitHub Desktop through the GitHub website https://desktop.github.com for macOS.
2. Open the GitHub desktop after download it.
3. The header of the GitHub desktop only showing.
4. Click on the header and nothing happens.

### Log files

[2023-07-25.desktop.production.log](https://github.com/desktop/desktop/files/12162467/2023-07-25.desktop.production.log)

### Screenshots

<img width="1284" alt="Screenshot 2023-07-25 at 10 44 18 PM" src="https://github.com/desktop/desktop/assets/119833700/2eeda4db-2934-4a1c-afba-af053f7badca">

**Comment by steveward** [comment]
@Jane1101-hash thanks for the report. It looks like hardware acceleration is disabled based on what is shown in the log file -- have you tried launching GitHub Desktop with it enabled as well?

**Comment by NabilahWork** [comment]
Yes I have tried it when it was enabled but still hitting the same issue. Anyway of enabling the hardware acceleration back?

**Comment by steveward** [comment]
Running `GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1 open -a "GitHub Desktop"` from the Terminal launches Desktop with hardware acceleration on (changing from 1 to 0 will turn it off). How did you disable it previously?

**Comment by NabilahWork** [comment]
Previously I run this command GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1 open -a "GitHub Desktop" in the terminal.

**Comment by NabilahWork** [comment]
@steveward I've uninstall and install again the GitHub Desktop and it's getting the attached logs.
[2023-07-29.desktop.beta.log](https://github.com/desktop/desktop/files/12207152/2023-07-29.desktop.beta.log)

**Comment by steveward** [comment]
@Jane1101-hash can you try fully removing GitHub Desktop and reinstalling to see if that helps?

This is the command you'll need to run:

`rm -rf ~/Library/Application\ Support/GitHub\ Desktop`

**Comment by NabilahWork** [comment]
@steveward I'm able to get the GUI Github Desktop now. 
I'll proceed to close this issue. 
Appreciate your help. 
Thanks.
