### ISSUE TITLE
Tab indentation too wide

### ISSUE THREAD

**Issue by Krizald18** [desktop/desktop#17117]
### The feature request

When using tabs (instead of spaces) for indentation GitHub Desktop shows it like it is about 8 spaces wide (no matter how you set it up it in your text editor).

Using spaces
![spaces](https://github.com/desktop/desktop/assets/119136016/964a12d0-16ed-43bf-8fbb-73c946588a6e)

Using tabs (2 spaces wide in text editor)
![Tabs](https://github.com/desktop/desktop/assets/119136016/607c6e87-991e-405e-a18c-6ab98ab96ae0)

### Proposed solution

The feature would be a config option to change how many spaces a tab represents.

### Additional context

This may be a good reason to use GitHub Desktop for coders that use tabs as a standard (C# users for example).

**Comment by steveward** [comment]
Thanks for the feedback @Krizald18, this is being tracked in https://github.com/desktop/desktop/issues/15561 so you can follow along there for updates.
