### ISSUE TITLE
Unable to login to github desktop

### ISSUE THREAD

**Issue by adithyan-sivaraman** [desktop/desktop#17118]
### The problem

I am unable to login to github desktop. After entering credentials in browser github keeps loading and does not allow to log in

### Release version

Version 3.2.6 (x64)

### Operating system

windows 11

### Steps to reproduce the behavior

1. Go to File->options->Sign in
2. Click on Continue with browser
3. Enter credentials in the browser

### Screenshots

![image](https://github.com/desktop/desktop/assets/124238686/55666e86-a849-4f92-806a-d5177252db95)
![image](https://github.com/desktop/desktop/assets/124238686/4493658a-491d-49e5-be83-82595c2c740d)

**Comment by steveward** [comment]
@adithyan-sivaraman thanks for the report. What browser are you using on your machine? Could you try temporarily changing the default browser to see if that resolves the issue?
