### ISSUE TITLE
Unable to multi select files in the change set list 

### ISSUE THREAD

**Issue by chikuba** [desktop/desktop#1712]
I can't multi select by holding down cmd or shift to select a bunch of files. 
This is something I missed in the old app, and in the new one too. 
I wan't to be able to select files and then toggle, discard or ignore them.
This is the only feature I'm missing, and not having it is making my life very hard :( I can't sit and toggle 1000 files if I need to remove a pod that I accidentally added. 

<img width="962" alt="screen shot 2017-05-23 at 14 49 30" src="https://cloud.githubusercontent.com/assets/2025561/26354936/13738752-3fc7-11e7-8f49-5879ad6fa1a9.png">

**Comment by g-plane** [comment]
+1

**Comment by joewiz** [comment]
+1 for multiple selection in the Changes tab

Also, GitHub Desktop for Mac app had a menu item, Repository > Discard Changes to Selected Files, that effectively enabled the discard operation on multiple files:
  
> <img width="286" alt="screen_shot_2017-05-25_at_11_17_55_am" src="https://cloud.githubusercontent.com/assets/59118/26456713/e8af1f9c-413b-11e7-8ea4-6ecbab082889.png">

This menu item is missing in the current beta:

> <img width="193" alt="screen_shot_2017-05-25_at_11_20_00_am" src="https://cloud.githubusercontent.com/assets/59118/26456799/315d6640-413c-11e7-9648-8d7df41e487f.png">

**Comment by stephenbe** [comment]
Both seems closed referencing each other...

**Comment by shiftkey** [comment]
@stephenbe this one is still open

**Comment by alanaasmaa** [comment]
+1

**Comment by luketf** [comment]
+1 for sure. I have found this lack of functionality to be really annoying.

**Comment by JamiePrentice** [comment]
+1

**Comment by shiftkey** [comment]
After we support selecting multiple files, we should test and ensure that multiple files can be checked/unchecked in sync. See #2439 for the discussion on this.

**Comment by shiftkey** [comment]
After we support selecting multiple files, we should support "Discard Selected Files" from the context menu for these files. See #2481 for more details.

**Comment by arknano** [comment]
+1 This is one of the features missing in Desktop that makes it very hard to switch from more complicated frontends, but is a very simple and common task.

**Comment by gloinart** [comment]
+1 Really need this

**Comment by cdc-dpbrown** [comment]
+1 I'd like to ignore 3386 files after a build. Can't ignore multiple files in VS 2015 either. I'll give 2017 Community a try.

**Comment by shiftkey** [comment]
> You can just ignore the output and build folders.

Yes! Also, check out the default [VisualStudio.gitignore](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore) - this should help cover most of the things that VS generates...

**Comment by cdc-dpbrown** [comment]
@shiftkey 

**Thank you.** That's great. I just checked it in. 

[dpb]

**Comment by nicolasbadia** [comment]
+1

**Comment by LautaroL20** [comment]
When is this going to be implemented? We really need this.

**Comment by iAmWillShepherd** [comment]
At the moment, the core team is working to get version 1.1 shipped. I've added the _help-wanted_ label to open this up to the community. Unfortunately, I am not able to give a timeline for when this feature will get implemented.

**Comment by stevemoser** [comment]
FYI until the keyboard shortcuts are implemented you can right click on the "2 changed files" header and select "Discard All Changes...".

**Comment by everhardt** [comment]
@stevemoser That will also discard changes to files that are not selected.

**Comment by cameronsamuels** [comment]
I agree that this option should be added as it would've been used by me many times.

**Comment by woz5999** [comment]
I wouldn't have upgraded to the new version if I'd known this functionality was removed.

**Comment by icosamuel** [comment]
I started to work on [a fix for this](https://github.com/icosamuel/desktop/tree/feature/multiple-file-selection) It's rather tedious because all of the lists were made with single selection in mind.

**Comment by LautaroL20** [comment]
@icosamuel Keep up the work! Your effort will make all of us prevent frustration when using the gith app. Keep us updated on your progress since we are really interested in this feature.

**Comment by icosamuel** [comment]
The multi-selection is done. See my PR for more details and to follow the review and integration process

**Comment by dustincaruso** [comment]
@icosamuel - re: your comment from 9 days ago - what's your "PR"? "personal repo", "private repo" ???

**Comment by j-f1** [comment]
@dustincaruso it’s a **p**ull **r**equest, in this case #4188.
