### ISSUE TITLE
Running Fetch on a forked repo throws an error

### ISSUE THREAD

**Issue by brandonh6k** [desktop/desktop#17126]
### The problem

If I do a `fetch` against a forked repo where I don't have access (at all) to the upstream parent, I get an error about the repo not existing.

![GitHubDesktopError](https://github.com/desktop/desktop/assets/101275235/8395abc6-88e1-40aa-b10a-51378274146c)

That's even with my Fork Behavior setting set to the child repo (the My own purposes setting).

![GitHubDesktopRepoForkBehavior](https://github.com/desktop/desktop/assets/101275235/7088061c-3caf-4cfd-a457-ec3f5504af1a)

GitHub Desktop seems to still do a `fetch` when I click the button, but still pops up with the error.  Doing a `pull` after `fetch` tells me that there are available commits works just fine with no errors.

### Release version

3.2.7

### Operating system

Windows 10 (x64)

### Steps to reproduce the behavior

1. Create a fork from a private repo, then revoke your permissions on that parent repo.
2. Clone the forked repo
3. Click Fetch in GH Desktop

**Comment by steveward** [comment]
Thanks for the report @intrado-bfhunt. This is being tracked in https://github.com/desktop/desktop/issues/3715, and unfortunately the only workaround right now is to delete the upstream remote from the command line. GitHub Desktop will add the remote back once the app is restarted.
