### ISSUE TITLE
When I use GitHub Desktop to update from the upstream repository, I can't find the tag versions. 

### ISSUE THREAD

**Issue by An-Jhon** [desktop/desktop#17121]
### The problem

When I use GitHub Desktop to update from the upstream repository, I can't find the tag versions.
There are a number of tag versions in the upstream repository, as follows
![image](https://github.com/desktop/desktop/assets/44490800/5c1096c6-51cd-454c-b36f-4f073eafdfae)
But I can't find them on my GitHub desktop.
![image](https://github.com/desktop/desktop/assets/44490800/89d41add-6800-4b59-8fbd-b1e7ce8bbe77)

### Release version

Version 3.2.6 (arm64)

### Operating system

MacOS 13.2.1

**Comment by steveward** [comment]
@An-Jhon thanks for the issue. At this time it isn't possible to search for tags in GitHub Desktop, but this is being tracked in https://github.com/desktop/desktop/issues/15702. I'm going to reference this issue there and close this out.

**Comment by tidy-dev** [comment]
Other info, you can see tags in GitHub Desktop in the history view. Just not searchable as in dotcom.

![CleanShot 2023-07-26 at 10 21 10](https://github.com/desktop/desktop/assets/75402236/f87556f0-69ca-4002-a359-2852fb196337)

**Comment by An-Jhon** [comment]
Thank you guys for your answers. Any chance the feature will be added in the future?

**Comment by An-Jhon** [comment]
And...How can I update my forked repository to the specified version? Not the latest version.

**Comment by An-Jhon** [comment]
In my previous use, once my window showed tags and I selected one of the versions to update! But when I used GitHub Desktop again it disappeared!

**Comment by tidy-dev** [comment]
> Thank you guys for your answers. Any chance the feature will be added in the future?

Sorry, it is not currently on the road map. 

> And...How can I update my forked repository to the specified version? Not the latest version.

Sounds like you would like to checkout the repository at a specified tag. You can right click on the commit with a tag and use the "Create Branch from Commit" menu item. If you have [the beta version](https://desktop.github.com/beta/), there is a "Checkout Commit" menu item as well to checkout the commit in a detached head state if you don't like create branches. Tho, branches are safer and detached heads can behave in unexpected ways.
