### ISSUE TITLE
Need better refresh!

### ISSUE THREAD

**Issue by mobynet1** [desktop/desktop#17123]
### The feature request

I requested this several weeks ago and got feedback from someone on your team that my suggestion of either adding a refresh button to the overall app, or react to changes in the code far faster was a good idea, but I got no sense of when something like this can be done. I do remember you were not keen on the refresh button, but...

In order to get all 22 of my repositories properly committed before a build, I need to make sure that all of the changes to all the repos have been committed. The only way I can see this now is to go through at least half of them opening the "Current repository" dropdown to get the list to eventually refresh. You would think that closing the GitHub Desktop and then reopening it would do an immediate refresh, but it does not (at least that I can see...) The lag is really not livable. I waste a ton of time making sure all of the repos are up-to-date before a build - something I am doing multiple times a day for our startup's new app.

### Proposed solution

I propose:

1. Refresh the list immediately upon starting the app
2. Adding a refresh button to refresh all repos in the list
3. Listen to the repo folders or at least to the .git folders for immediate refresh

I know it is a minor irritation to many, but I am the only developer, build master, repo owner, janitor, grounds keeper, etc. in my very small company with tons of work to get done for a fund raising demo of our app and I do not have the time to continually refresh the repo's in the list or opening all of the solutions and checking the git page for changes. How difficult can a refresh button be in the short term until you implement a better listening workflow?

I'm seriously not trying to be difficult... I am seriously trying to be effective and productive, though!!

Thanks for listening to my oratory! :-) Steve

**Comment by steveward** [comment]
@mobynet1 thanks for the feedback, but in the future we ask that you don't open duplicate issues. As this is being tracked in https://github.com/desktop/desktop/issues/13700 I'm going to close this out.

My recommendation if you need this functionality would be to use a script that allows you to quickly update all the repositories. Git has a [`for-each-repo` command](https://git-scm.com/docs/git-for-each-repo) you could use to do this, or there are likely other scripts that are available that others have written.

**Comment by mobynet1** [comment]
Steve,

Thanks for your reply.

a) I could not find my original issue - I did try!
b) The refresh issue is not just to help me see what needs to be pulled or
pushed, it is to give me a look at all of my repos' status'.

As a dig, SourceTree does what I am asking for here, but I hate Atlassian
and I hate Bitbucket even more!

Anyways, I will be patient. I just wanted to make sure people were
listening!! :-)
Steve

**Comment by JoshMcCullough** [comment]
I just downloaded GH Desktop because I have a ton of repos and I wanted a quick view at their status. I am crushed to find that there is no refresh button or that the UI doesn't auto-refresh, listen for changes, etc. I use the terminal for everything related to Git, so I guess I'll go back to that. 🤷‍♂ 

Edit: Maybe I'm wrong here ... I see some indicators "loading in" when I have the repo menu open but very slowly / randomly.

Edit 2: All of the indicators did eventually update, it probably took 5 minutes for ~120 repos on a fast machine.
