### ISSUE TITLE
Cannot install GitHub Desktop on Windows 11

### ISSUE THREAD

**Issue by Nevrai** [desktop/desktop#17127]
### The problem

I get the following error whenever I attempt to install GitHub Desktop using GitHubDesktopSetup-x64.exe, installed from [desktop.github.com](https://desktop.github.com/).

<img width="259" alt="Screenshot 2023-07-27 133837" src="https://github.com/desktop/desktop/assets/59761487/72a78269-e02e-472e-ba6f-9b1e2b37dcd1">

## What I’ve tried
* Restarting my computer.
* Running the installer as an administrator.
* Checking Task Manager for any running programs with ‘GitHub’ in the name.
* Running the Windows .NET repair tool (NetFxRepairTool.exe).
* Running `sfc /scannow`.
* Deleting the SquirrelTemp and Temp folders.

I also tried installing it via the .msi file: GitHubDesktopSetup-x64.msi. However, I just seee this pop-up, and nothing happens once it disappears:

<img width="322" alt="Screenshot 2023-07-27 134110" src="https://github.com/desktop/desktop/assets/59761487/7dbe48ac-3640-4bf2-83fa-8867e5251471">

I’ve seen the same issue posted here, but I couldn’t solve it using any of the solutions that people recommended or that worked for them.

## Hardware Information
* **OS:** Windows 11 Home 22H2
* **Hard drive:** SSD

### Release version

N/A

### Operating system

Windows 11

**Comment by steveward** [comment]
Thanks for the report @DeleteMetaInf. Are you running any antivirus/security software on this machine?

To get some more information about why the installation is failing it would be helpful if you could send over the log file that the Squirrel installer generates.

You should be able to find the log file here:

`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`

If no log file is being generated there you should be able to find one in the `SquirrelTemp` directory:

`%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

Please upload that as an attachment.

**Comment by d41ly** [comment]
I'm having seemingly the same issue as the OP on my Windows 11 machine. His description matches what I'm experiencing perfectly.

There are no log files to the shared. After the files are extracted to their destination, installation terminates immediately. No additional files are generated. Attempting to execute Update.exe manually leads to a 'file not found' error.

The .msi installer doesn't seem to create anything at all, and no dialog windows appear during execution.

There are no entries in the system log files either.

Please advice! Thank you.

**Comment by steveward** [comment]
@d41ly are you trying a fresh installation? Are you running any antivirus or other security software on your machine?

**Comment by mzvarik** [comment]
Same issue... for no reason it stopped working, so I wanted to reinstall, but it's impossible... also cannot uninstall, because the files don't exist, but it is listed in "Remove programs"
Error log is completely empty.

**Update: Turning off AVG worked.**

**Comment by nrush23** [comment]
Similar problem as @mzvarik happened to me. While GitHub Desktop was open, AVG gave a warning that GitHubDesktop\Update.exe was missing and then the app stopped working. Uninstalling or reinstalling gave an error due to the missing file. Checked out my Local folder, and it was completely empty. Temporarily uninstalling AVG let me reinstall without error.

**Comment by ai-patch** [comment]
I am getting a similar error
![image](https://github.com/user-attachments/assets/66ac489c-a43d-460d-ac00-99bbaa3f894c)
When I open up the setup log (SquirrelSetup.log) there is nothing in it
I have already tried:
- restarting the PC
- sfc /SCANNOW
- .net Repair Tool
- the .msi version (the deployment tool gets installed and nothing else happens)
- using the winget command to install it also leads to the exact same error
- The only antivirus I am using in Windows Defender (I have also tried turning off real time protection in that, however that also does not change anything)

**Comment by isikyus** [comment]
> There are no entries in the system log files either.

Which system logs are you looking at?

I'm seeing what looks like the same issue, and I can see two "⚠️ Warning" messages in Event Viewer, under Windows Logs > Application after I try to run the installer:

> Access to C:\Users\\\<user name>\AppData\Local\SquirrelTemp\Update.exe has been restricted by your Administrator by the default software restriction policy level.

and

> Access to C:\ProgramData\\\<user name>\SquirrelTemp\Update.exe has been restricted by your Administrator by the default software restriction policy level.

I've already had to ask my administrator to permit the installer itself. I've written again to ask them to permit the SquirrelTemp exe's as well, and I'll see how that goes.

**Comment by isikyus** [comment]
My issue seems to be broadly the same thing as https://github.com/desktop/desktop/issues/16604. I've written a comment there as well: https://github.com/desktop/desktop/issues/16604#issuecomment-2451054027

**Comment by marianrda** [comment]
I'm experiencing a similar issue. When I'm trying to install it as an admin too it gives me the window mentioning installation has failed. Tried deleting the SquirrelTemp folder as well. But it kept getting created as i'm trying the installation.
