### ISSUE TITLE
Publishing private repo to GitHub hangs

### ISSUE THREAD

**Issue by ParkerRobb** [desktop/desktop#17139]
### The problem

When I publish a private repository to my GitHub account for the first time, the process hangs around 60-70% and appears to never finish.

If I quit and restart GitHub Desktop, and click `Publish` again, it appears to be able to connect to the remote that was created before and finish pushing the branch.

There seems to be something stopping the process between adding the remote and pushing the branch.

### Release version

3.2.6

### Operating system

macOS 12.6.2

### Steps to reproduce the behavior

1. Import an existing local repository into GitHub Desktop.
2. Click `Publish repository: Publish this repository to GitHub` in the top toolbar.
3. Enter name for repository, and select the `Private` option; Click `Publish`.
4. Publish progress stops 60-70% of the way through, continues spinning indefinitely.

### Log files

[2023-07-29.desktop.production.log](https://github.com/desktop/desktop/files/12207833/2023-07-29.desktop.production.log)
[2023-07-24.desktop.production.log](https://github.com/desktop/desktop/files/12207834/2023-07-24.desktop.production.log)

**Comment by steveward** [comment]
@ParkerRobb thanks for the issue. Unfortunately I'm not seeing anything specific in the log file that shows the push operation hanging. Does pushing regular commits after the initial publish work without issue? How large was the repository you were trying to publish?

**Comment by ParkerRobb** [comment]
Pushing anything only works (without issue) after I restart the GitHub app.

It's happened with several repositories of varying sizes: 600-KB, 65.4-MB, 20.2-MB.

**Comment by steveward** [comment]
Those repository sizes definitely shouldn't be an issue. Anything unusual about your network that could be causing this, like a firewall or other security software?

**Comment by ParkerRobb** [comment]
Not that I know of. I use no security software. If it was a firewall, why would it work fine after restarting the app?

**Comment by steveward** [comment]
Just trying to cover any different possibilities of previous issues we've seen. It'd be helpful to know if anything shows up in the Developer Tools that may give a better idea of what's happening. Can you go to `View` > `Toggle Developer Tools` and see if anything interesting is shown in the Console or Network tab when you publish? That may show what specifically is hanging.
