### ISSUE TITLE
Checkout fails on Windows if a file name is a reserved name followed by an extension

### ISSUE THREAD

**Issue by maurice-w** [desktop/desktop#17149]
### The problem

When cloning [opnsense/tools](https://github.com/opnsense/tools), the checkout fails:

```
error: invalid path 'config/23.7/aux.conf'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
```
`aux.conf` is a file,
`23.7` is a directory which contains multiple files,
`config` is a directory which only contains the `23.7` subdirectory.

Windows allows creating a folder named `23.7`, so this can't be the issue. Maybe GitHub Desktop tries to create a single folder named `config\23.7`?

### Release version

3.2.7

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Click on 'Clone a repository from the Internet...'
2. Click on 'URL'
3. Enter `opnsense/tools`
4. Click on 'Clone'
5. See error

### Screenshots

![image](https://github.com/desktop/desktop/assets/28608887/25e950b7-a35e-4602-b80e-96d86ef953ec)

**Comment by steveward** [comment]
@maurice-w thanks for the issue. Unfortunately `aux` is a [reserved filename](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions) on Windows, which causes the checkout to fail. You could fork the repository and rename the file directly on GitHub to workaround this, or open an issue directly in the repository to ask if it could be renamed. I hope that helps!

**Comment by maurice-w** [comment]
@steveward Thanks for looking into this. The file is not named `aux` though, but `aux.conf`. Windows indeed doesn't let me create a file named `aux` (interesting), but `aux.conf` works fine.

![image](https://github.com/desktop/desktop/assets/28608887/9e3ce34e-cc90-4db0-9645-6d7037336e39)

**Comment by steveward** [comment]
Hmm, the docs say this:

>Also avoid these names followed immediately by an extension; for example, NUL.txt and NUL.tar.gz are both equivalent to NUL. For more information, see [Namespaces](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#win32-file-namespaces).

**Comment by steveward** [comment]
You could try setting this to bypass the issue:

`git config --global core.protectNTFS false`

**Comment by maurice-w** [comment]
Sounds more like a recommendation than a hard requirement, doesn't it?
Thanks, I'll try the workaround.

**Comment by maurice-w** [comment]
Yes, this worked! Thanks a lot! I'll change the issue's title for future reference.

**Comment by eses-wk** [comment]
This also works for checking out branches with weird emoji as filename, such as 1️⃣, 2️⃣
