### ISSUE TITLE
Unable to update Mac application

### ISSUE THREAD

**Issue by slavag** [desktop/desktop#17141]
### The problem

Unable to update Mac application :
`Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. See https://github.com/Squirrel/Squirrel.Mac/issues/182 for more information.`

Application is located in the Application folder and not in Download.
<img width="396" alt="image" src="https://github.com/desktop/desktop/assets/511540/f5783a3e-4a09-4e43-b001-714544bbeae5">

### Release version

3.2.7

### Operating system

MacOS 13.4.1

### Steps to reproduce the behavior

1. Go to GitHub Desktop option
2. About
3. Click "Check for Update"
4. Got error

### Log files

[2023-07-30.desktop.production.log](https://github.com/desktop/desktop/files/12208666/2023-07-30.desktop.production.log)

### Screenshots

<img width="606" alt="image" src="https://github.com/desktop/desktop/assets/511540/15b1499d-146b-4c0c-86ab-aa846d9c9452">

### Additional context

MacBook Pro M1 Max

**Comment by yunruse** [comment]
It may be that the app is somehow still considered "quarantined" despite being moved out of the Downloads folder.

On the Terminal, try entering the following command:

```sh
xattr -d com.apple.quarantine "/Applications/GitHub Desktop.app"
```

If the result is blank, the app was indeed quarantined and should hopefully now be fixed; otherwise you will get

```
xattr: /Applications/GitHub Desktop.app: No such xattr: com.apple.quarantine
```

which would indicate something more strange is causing the issue.

**Comment by slavag** [comment]
@yunruse Empty result
<img width="669" alt="image" src="https://github.com/desktop/desktop/assets/511540/a8da72f8-b6a5-4f88-a3c9-679e3d2688e0">

**Comment by yunruse** [comment]
@slavag seems like that may have been the problem; did it fix the issue, can you update now?

**Comment by slavag** [comment]
Yes, seems to be working fine now.
Thanks

**Comment by steveward** [comment]
Glad to hear things are working now and thanks so much for helping troubleshoot this @yunruse!
