### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by DannyBaine-Entity** [desktop/desktop#17140]
### The problem

I keep getting this error.
No matter the combination I use

### Release version

Version 3.2.6 (x64)

### Operating system

Windows 11

### Screenshots

![GitHub Desktop 29_07_2023 21_30_05](https://github.com/desktop/desktop/assets/137898784/7895db3b-9d68-4141-8bc0-dc0e3833a7a4)

**Comment by steveward** [comment]
@DannyBaine-Entity are you able to log in by going to `File` > `Options` > `Accounts`? That dialog is for authenticating to third-party services that require a token.

**Comment by katiemattews** [comment]
Deactivate authentication and block all the device on my Google accounts and Facebook and WhatsApp and Google chat using head chat and professional sit to overview and hidden on secret chatroom and groups and pages pin please block all hidden chat on my phone device inifinix hot8

**Comment by katiemattews** [comment]
Deactivate authentication on my phone device infinix hot 8 and block all hidden pages and group using professional site to overview and overlay and chatting with my families and friends

**Comment by DannyBaine-Entity** [comment]
> 

Yes

**Comment by steveward** [comment]
@DannyBaine-Entity it sounded like you were able to get things working, I'm going to close this out but let me know if you are still having issues.
