### ISSUE TITLE
Cloning a repo through Github Desktop causes all files to be untracked in Git CLI

### ISSUE THREAD

**Issue by mcoirad** [desktop/desktop#17156]
### The problem

![image](https://github.com/desktop/desktop/assets/13713560/03a97c02-dc64-4727-9e10-b3dce48e1b30)

Github Desktop does not seem to be playing well with Git CLI as I am getting hundreds of untracked files when cloning a repo.

When I do a diff I don't see any differences but Git seems to think all lines of all files are different somehow.

![image](https://github.com/desktop/desktop/assets/13713560/77942c09-20b2-43c1-93d5-020e934b960a)

### Release version

Version 3.2.6 (x64)

### Operating system

Windows 11 Enterprise

### Steps to reproduce the behavior

When I:

- Clone a repo locally
- Switch to a branch using Github Desktop
- run `git status` in command line it takes awhile as all files are apparently now untracked

Now can't easily switch branches through command line because of hundreds of untracked files, but can through Github Desktop

An issue may be that I am using Github Desktop on Windows, while using the git command line on ubuntu running under WSL.
However, both seem to be using Git 2.41.0

**Comment by steveward** [comment]
@mcoirad thanks for the issue. This is likely a file mode or line endings issue since you're using Ubuntu. What does `git diff` show if you run it on one of the files from the command line?

**Comment by mcoirad** [comment]
Believe this was a line ending issue coming from switching between Github Desktop on Windows and git command line in WSL, thanks!
