### ISSUE TITLE
git stash issue

### ISSUE THREAD

**Issue by DH30124** [desktop/desktop#17153]
### The problem

I ran git stash on the GitHub Desktop app. (30+ changed files)
but there is nothing in the Stash list.
how can I restore data?
The strange thing is that when I run `Stash all changes` for the first time, the list of changed files is emptied, and after a bit, it is displayed as `25 changed files`.
After running `Stash all changes` again, it was completely gone.
Previously, nothing like this had happened.

### Release version

Version 3.2.6 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Currently, I can not reproduce the behavior.

my behavior was the following:
```
- open the GitHub Desktop application on Windows 10
- there were 30+ changed files in the 'Changes' tab
- right click on '30+ changed files' and select 'Stash all changes' (first action)
- the list of changed files was emptied.
- In less than 1s, '25 changed files' displayed again.
- so I ran again 'Stash all changes' (second action)
- all changes were completely gone. there is nothing in the list of changed files and stash list
```

### Log files

...
(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2023-08-01T10:55:55.948Z - info: [ui] [createDesktopStashEntry] a stash was created successfully but exit code 1 reported. stderr: 
2023-08-01T10:55:56.041Z - info: [ui] Dropped stash '287077b420aa818bef2c85dfc072a66113f03461' associated with main
2023-08-01T10:55:56.152Z - info: [ui] Executing createStashEntry: git stash push -m !!GitHub_Desktop<main> (took 4.591s)
2023-08-01T10:55:56.926Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 2.016s)
...

**Comment by steveward** [comment]
We should be able to recover the stash using that SHA. Try running this command:

`git stash apply 287077b420aa818bef2c85dfc072a66113f03461`

That should recover the lost changes. Let me know if it doesn't.
