### ISSUE TITLE
Untrusted server problem

### ISSUE THREAD

**Issue by U391127** [desktop/desktop#17157]
### The problem

when users try to sign in GitHub Enterprise, They get this error:
GitHub Desktop cannot verify the identify of (github enterprise url). The certificate is invalid or untrusted.

### Release version

3.2.6

### Operating system

Windows 10 Enterprise

### Screenshots

![screen1](https://github.com/desktop/desktop/assets/141156146/14d0b1d6-bb14-4443-883d-b7178ebb7a21)
![screen2](https://github.com/desktop/desktop/assets/141156146/5b6ab6ca-4c73-449d-a2bf-27265e1176eb)

**Comment by steveward** [comment]
@U391127 thanks for the report. Is this a self-signed certificate? Does clicking `Add certificate` not resolve the issue?

**Comment by geomorillo** [comment]
how to stop this message i know my server is unsecure but this window appearing every 5 seconds is really anoying please how to disable it

**Comment by Tarmogos** [comment]
Same shit for me. Let me out i am not intresses of others issues i have my is

Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Jhobanny Morillo ***@***.***>
Skickat: Friday, July 12, 2024 10:18:43 PM
Till: desktop/desktop ***@***.***>
Kopia: Subscribed ***@***.***>
Ämne: Re: [desktop/desktop] Untrusted server problem (Issue #17157)


how to stop this message i know my server is unsecure but this window appearing every 5 seconds is really anoying please how to disable it

**Comment by geomorillo** [comment]
Not working still happening on Version 3.4.15 (x64)
