### ISSUE TITLE
Ability to rebase to a previous commit, aka git reset.

### ISSUE THREAD

**Issue by Zenodeon** [desktop/desktop#17161]
### The feature request

We should like to have the ability to go several commits back built into the app similar to the feature 'git reset'.

### Proposed solution

Having an option 'Rebase to commit' or 'Reset branch to commit' or similar show up along with other commit options when right-clicking the commit in the history tab.

### Additional context

An alternative solution to this requires having other git software like fork, or creating a new branch from the selected commit is time-consuming and requires a lot of steps.

**Comment by steveward** [comment]
Thanks for the issue @Zenodeon, the ability to checkout a previous commit will be in an upcoming release, see https://github.com/desktop/desktop/issues/10068. That will leave you in a detached HEAD state. Will that be helpful?

We've had discussions around reset in the past, see https://github.com/desktop/desktop/issues/5860#issuecomment-428959691 for our thinking around this. At this time it still isn't on our radar, but thanks for letting us know you would like to see this implemented.

**Comment by mcmartincerny** [comment]
Hi @Zenodeon, I wrote a short guide on how to enable it: https://github.com/desktop/desktop/issues/5860#issuecomment-1705689506
