### ISSUE TITLE
DNS issue

### ISSUE THREAD

**Issue by Mariballardin** [desktop/desktop#17170]
### The problem

I have created a domain from namecheap using my github student pack. After that, my websites that are hosted in github automatically redirect to another website with "/name-of-repository (same website that I have created in namecheap). 

I dont see any possibility of removing this domain here. It does not allows me.
I also do not have a CNAME file on my repositories.
I need help finding the solution. 
Thank you

### Release version

github 

### Operating system

mac

### Steps to reproduce the behavior

Go to my repository
Access the link. ex: https://mariballardin.github.io/guessthenumber
It redirects to: http://devwiz.me/guessthenumber

**Comment by steveward** [comment]
@Mariballardin thanks for the issue. This issue tracker is for GitHub Desktop, if you have a specific question about GitHub Pages you can ask it here: https://github.com/orgs/community/discussions/categories/pages

I hope that helps!
