### ISSUE TITLE
honor '~/.git-config' [commit] section

### ISSUE THREAD

**Issue by Zweihorn** [desktop/desktop#17175]
### The problem

Apparently, good git commit message style requires to separate subject from body with a blank line.

Unfortunately, the GitHub Desktop deletes any leading empty line in a body of a new commit. At least this happens to me with GitHub 3.2.7 (and earlier) on macOS and I found no easy way to change this.

Please note a `git config --global commit.cleanup verbatim` did not help. Apparently, GitHub Desktop **ignores the "[commit]" section of the '~/.git-config'** and always enforces a "--cleanup=whitespace", if I am correct.

Naturally, there would be CLI git but _GitHub Desktop should honor more of '~/.git-config'_ thus IMO making this worth a bug report and not just a feature request.

### Release version

3.2.7

### Operating system

macOS 11.7.9

### Steps to reproduce the behavior

1. Git global setup `git config --global commit.cleanup verbatim` via CLI
2. Establish a new commit via GitHub Desktop in the "Changes" of a branch view
3. Try to introduce leading empty lines in the description of a.m. commit
4. Activate the "Commit ..." button
5. View the (unwanted) outcome of an apparent "--cleanup=whitespace" in the "History" of same branch view

### Log files

`% cat ~/.gitconfig`

```
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
[user]
	name = Zweihorn
	email = 4863737+Zweihorn@users.noreply.github.com
[init]
	defaultBranch = main
[commit]
	cleanup = verbatim
```

### Screenshots

![GHD_Changes](https://github.com/desktop/desktop/assets/4863737/7ada5142-7e22-4051-b18f-5201645d10df)

![GHD_History](https://github.com/desktop/desktop/assets/4863737/2ae8cef3-5fb1-4406-a101-608cd6b9f899)

### Additional context

ref [git-commit - cleanup](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---cleanupltmodegt)

ref [General Commit Message Guidelines](https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53)

ref [MacPorts Commit Messages Guidelines](https://trac.macports.org/wiki/CommitMessages)

**Comment by tidy-dev** [comment]
Copied from #17179

### The feature request

Apparently, good git **commit message** style requires to **separate subject from body with a blank line**.

IMO the GitHub Desktop App should provide an easy feature to accomplish this without editing the global Git config.

Thus the apparent default behaviour of a "--cleanup=whitespace" could continue and as a **new optional feature** for a new commit just one empty line could be added to separate subject from body with a blank line.

### Proposed solution

Avoid complexity and do not honour the [commit] section nor edit the global Git config.

The new optional feature should:
1. be configurable in the "Preferences" window under "Git"
2. provide just one empty line to separate subject from body with a blank line for any new commit
3. stay independent from the global Git config if applicable

Example GUI given below:

![GHD_Feature-request01](https://github.com/desktop/desktop/assets/4863737/391c4602-fbd1-46af-941b-47d691bedc8e)

### Additional context

ref [git-commit - cleanup](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---cleanupltmodegt)

ref [General Commit Message Guidelines](https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53)

ref [MacPorts Commit Messages Guidelines](https://trac.macports.org/wiki/CommitMessages)

ref #17175

**Comment by tidy-dev** [comment]
To address the original issue. GitHub Desktop does trim the body input as a means to remove unintended introduction of whitespace (not through git, but programmatically as input validation). However, it automatically adds the expected newline between the summary and description. We do not apply `--cleanup=whitespace`

You can find the logic here:

The commit formatting:
https://github.com/desktop/desktop/blob/2e5f7947e18e178a0494f28f1ccb7bc798a5aafa/app/src/lib/format-commit-message.ts#L18

The createCommit method.
https://github.com/desktop/desktop/blob/bc69ee8a6f9f29395e5abc6aaa8004f71040bb83/app/src/lib/git/commit.ts#L15 

Here is some images showing that it does:

Input:
![image](https://github.com/desktop/desktop/assets/75402236/35e08292-363d-457e-999f-6b5ccb57eb4a)

Output in CLI (showing whitespace)
![image](https://github.com/desktop/desktop/assets/75402236/d5467564-0091-449e-8f96-5f8e4129f712)

Screenshot of our logic showing the `\n\n` being added
![image](https://github.com/desktop/desktop/assets/75402236/cec99edb-e35b-4b2e-b555-05b173abe8df)

**Comment by tidy-dev** [comment]
If you view your commits in the command line, are you not seeing the newlines?

**Comment by Zweihorn** [comment]
Oh silly me and this was a most embarrassingly misjudgement from my side. Obviously, I misinterpreted a reasonable complaint from a third party and totally overreacted.

A basic `git log` would have shown the technical details and would have helped me to avoid causing unnecessary effort.

**However, I would like to thank for the able and kind advice of this great community.** Please accept my sincere apologies for any inconvenience.

🌻
