### ISSUE TITLE
separate subject from body with a blank line in any new commit (option)

### ISSUE THREAD

**Issue by Zweihorn** [desktop/desktop#17179]
### The feature request

Apparently, good git **commit message** style requires to **separate subject from body with a blank line**.

IMO the GitHub Desktop App should provide an easy feature to accomplish this without editing the global Git config.

Thus the apparent default behaviour of a "--cleanup=whitespace" could continue and as a **new optional feature** for a new commit just one empty line could be added to separate subject from body with a blank line.

### Proposed solution

Avoid complexity and do not honour the [commit] section nor edit the global Git config.

The new optional feature should:
1. be configurable in the "Preferences" window under "Git"
2. provide just one empty line to separate subject from body with a blank line for any new commit
3. stay independent from the global Git config if applicable

Example GUI given below:

![GHD_Feature-request01](https://github.com/desktop/desktop/assets/4863737/391c4602-fbd1-46af-941b-47d691bedc8e)

### Additional context

ref [git-commit - cleanup](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---cleanupltmodegt)

ref [General Commit Message Guidelines](https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53)

ref [MacPorts Commit Messages Guidelines](https://trac.macports.org/wiki/CommitMessages)

ref #17175

**Comment by tidy-dev** [comment]
@Zweihorn Since this is a follow to your first issue, I am going to close it and place a copy of this issue in the comments there just to keep things easier to follow
