### ISSUE TITLE
GitHub Desktop unable to handle cloning repository which contain submodules

### ISSUE THREAD

**Issue by trclst** [desktop/desktop#17180]
### The problem

I tried to clone a repository with submodules and it does not work.

### Release version

3.2.7

### Operating system

Microsoft Windows 11

### Steps to reproduce the behavior

1. Click "Clone a repository from the Internet..."
2. Enter URL https://github.com/shinchiro/mpv-winbuild-cmake

### Log files

```
remote: Enumerating objects: 6756, done.        
remote: Counting objects: 100% (1128/1128), done.        
remote: Compressing objects: 100% (147/147), done.        
remote: Total 6756 (delta 1048), reused 1004 (delta 979), pack-reused 5628        
Receiving objects: 100% (6756/6756), 4.90 MiB | 163.00 KiB/s, done.
Resolving deltas: 100% (4856/4856), done.
      0 [main] sh 766 dofork: child -1 - forked process 19048 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\user\AppData\Local\GitHubDesktop\app-3.2.7\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
1063490 [main] sh 766 dofork: child -1 - forked process 20448 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
```

**Comment by steveward** [comment]
Thanks for the issue @trclst. This error is usually caused by Mandatory ASLR, please see https://github.com/desktop/desktop/blob/development/docs/known-issues.md#enable-mandatory-aslr-triggers-cygheap-errors. Try disabling mandatory ASLR and let us know if that does not get things working!

**Comment by trclst** [comment]
In fact with ASLR disabled I was able to clone the repository successfully. Thank you.

Please allow me this side note, I am not a security expert but to me it seems relatively unsafe to have to disable ASLR just to clone project with submodules. To turn ASLR on and off successfully, you must also reboot. 

I turned it back on right after that. This will probably cause me more problem with the said repository in the future.

**Comment by kryz360** [comment]
> Thanks for the issue @trclst. This error is usually caused by Mandatory ASLR, please see https://github.com/desktop/desktop/blob/development/docs/known-issues.md#enable-mandatory-aslr-triggers-cygheap-errors. Try disabling mandatory ASLR and let us know if that does not get things working!

Thanks !!! i have this problem since two days, some nodes suddenly don't work no more and i try your solution and it was that, i can't do the update or the installation no more completly (ultimatesdupscaler and reactor)
