### ISSUE TITLE
Pull tags

### ISSUE THREAD

**Issue by OverLordGoldDragon** [desktop/desktop#17185]
### The feature request

e.g. `git checkout tags/0.6.3`.

#4829 concerns commit tags.

<img src="https://github.com/desktop/desktop/assets/16495490/2a90ce14-c7c8-4194-8fde-0444e1e3a2f7" width="350">

### Proposed solution

Switching to another release version without using `git`.

**Comment by tidy-dev** [comment]
Similar to https://github.com/desktop/desktop/issues/17121 and https://github.com/desktop/desktop/issues/15702. Likely same intent of wanting to search and checkout tags.

**Comment by OverLordGoldDragon** [comment]
#15702
