### ISSUE TITLE
Allow rebase when up to date

### ISSUE THREAD

**Issue by Martin-Narvar** [desktop/desktop#17181]
### The feature request

If you want to rebase your code on another branch (usually main or master) the rebase is much easier if you merge that branch first, however GitHub desktop does not allow this.

After merging main into my current branch, if I drop down the list of branches and click the "Choose a branch into merge into ..." then choose the "main" branch, the blue button at the bottom is disabled and has a message next to it saying "This branch is up to date with ..."

This would make sense for the "Create merge commit" option, but it does not make sense for the "Rebase" option.

### Proposed solution

When choosing "Rebase" as the merge method, the button to to begin the merge is always enabled, even if the branch you are merging is up to date.

**Comment by sergiou87** [comment]
Sorry @Martin-Narvar , I didn't see this issue 😳 I'm already working on this as you can see in #17331 

I'm gonna close this issue in favor of https://github.com/desktop/desktop/issues/17260 which is where I discussed about it.
