### ISSUE TITLE
GitHub Desktop gets slow, because of excessive subprocess creation

### ISSUE THREAD

**Issue by staabm** [desktop/desktop#17193]
### The problem

when doing pretty simple operations in the github desktop ui, looking at the windows process manager shows a lot of process creation in the background. even just switching branches or pulling changes from a remote repo seem to create tens of processes.

e.g
- GitHubDesktop.exe
- conhost.exe
- git.exe
- ssh.exe

in our corporation we are forced to use antivirus software (because GDPR) which in turn is scanning all these processes.
I can see github desktop beeing really sluggish because of the anti virus doing its job on all these processes.
its kind of unusable right now, but other software on the same computer works fast enough - working on a high end lenovo thinkpad P1 Gen5 with a 12th i9 gen intel cpu 32 GB Ram etc

I think github desktop would see a major perf boost if it could reduce process usage. maybe there is some low haning fruit in reducing/combining existing stuff so less processes are required..?

### Release version

3.2.7 (x64)

### Operating system

windows 11 Pro x64 22H2

### Steps to reproduce the behavior

1. do some basic operation in the UI
2. watch the windows process manager and see subprocesses beeing spawned
3. see the antiviurs jumpting to the top of the process list while working in github desktop

### Screenshots

![grafik](https://github.com/desktop/desktop/assets/120441/7f67bcdf-09da-4cc6-aef1-62e1b8ec500e)

### Additional context

we are using [Panda Security](https://www.pandasecurity.com) a WatchGuard antivirus product

**Comment by steveward** [comment]
Thanks for the report @staabm. We are aware of antivirus software causing these issues. Is there any chance you can whitelist applications? That's the workaround we often recommend.

We already have a few issues tracking performance so I'm going to close this one out and consolidate it into https://github.com/desktop/desktop/issues/13586, which is our most recent issue around performance.
