### ISSUE TITLE
cannot sign in

### ISSUE THREAD

**Issue by Pedroso0417** [desktop/desktop#17190]
### The problem

I already authenticate my user and password but still is not working

### Release version

current version

### Operating system

windows 10

### Screenshots

![image](https://github.com/desktop/desktop/assets/136574676/050ff832-a9a4-4a1a-aa30-29f1801a855c)

**Comment by steveward** [comment]
@Pedroso0417 thanks for the issue. Is authentication hanging when you attempt to authenticate via browser flow? If you can share some further details that will help us assist you further.
