### ISSUE TITLE
GitHub deskto does not create a fork

### ISSUE THREAD

**Issue by 3f6a** [desktop/desktop#17195]
### The problem

In this page: https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/adding-and-cloning-repositories/cloning-and-forking-repositories-from-github-desktop?platform=mac

it is stated that:

> In GitHub Desktop, if you attempt to clone a repository that you don't have write access to, a fork is automatically created for you.

However, when I try to clone a remote repository that I do not own (and do not have write rights to), no fork is created.

### Release version

Version 3.2.7 (arm64)

### Operating system

macOS

**Comment by steveward** [comment]
Thanks for the reminder that I need to update this @3f6a! See https://github.com/desktop/desktop/issues/13165. The prompt will be shown when attempting to push to a repository you do not have push access to. Apologies for the confusion!
