### ISSUE TITLE
Constant string of errors that can only be stopped with a restart of computer

### ISSUE THREAD

**Issue by brayne** [desktop/desktop#17208]
### The problem

This issue has been going on for months and I'm not sure of the specific trigger. I'm using the latest version of GitHub Desktop and the latest version of Ventura on an Apple Silicon Mac. The local GitHub repository is stored on a Linux server, networked via Samba. When the error pops up, clicking the "close" button just starts looping through the same two errors over and over. Once the error starts I'm unable to do any commits. Quitting and relaunching GitHub Desktop makes no difference. Restarting the computer will make the error go away, but only for a brief time. So if I want to commit I restart the computer, launch GitHub Desktop, do my commit straight away (while it's still working) and then usually in around 5 to 10 minutes the errors start up again.

### Release version

Version 3.2.7 (arm64)

### Operating system

Ventura 15.5 (Apple Silicon)

### Steps to reproduce the behavior

1. Launch GitHub
2. Launch a project into BBEdit
3. Do some work
4. Go back to GitHub after a while and the errors start popping up.

### Log files

[2023-08-11.desktop.production.log](https://github.com/desktop/desktop/files/12318110/2023-08-11.desktop.production.log)

### Screenshots

![Screenshot 2023-08-11 at 11 46 52 am](https://github.com/desktop/desktop/assets/1421504/fc0986e0-c3d6-4cae-9314-28df499a834c)
![Screenshot 2023-08-11 at 11 46 45 am](https://github.com/desktop/desktop/assets/1421504/05c8d1d4-2e4e-43bd-b2c9-c2d272d63844)

**Comment by steveward** [comment]
@brayne apologies for the delay. This has been previously reported in https://github.com/desktop/desktop/issues/17208, but unfortunately it has been difficult for us to reproduce and investigate further. I would recommend following along there for updates.
