### ISSUE TITLE
Pause - Resume capability

### ISSUE THREAD

**Issue by hossein530** [desktop/desktop#17217]
### The feature request

When trying to clone large projects or fetching large update, any internet disconnection will break the download process and this is really frustrating. this is the first desktop app I have seen with this problem.

### Proposed solution

-

**Comment by Mhudzmhudz** [comment]
How do do that?

**Comment by steveward** [comment]
Thanks for the request @hossein530. Unfortunately Git itself doesn't support pause/resume functionality, so at this time this won't be something we will be able to support. There was a similar request in [this issue](https://github.com/desktop/desktop/issues/8367#issuecomment-536523194), along with some potential solutions. If you are hitting specific network errors you can also share those and we can see if there is anything we can help with to get those to succeed.
