### ISSUE TITLE
Resolve conflicts before merge

### ISSUE THREAD

**Issue by itstalmeez** [desktop/desktop#17215]
### The problem

Open cmd, your tool of choice, or close to resolve manually

### Release version

3.2.7

### Operating system

Windows

### Screenshots

![Screenshot (892)](https://github.com/desktop/desktop/assets/87268503/caf7c573-8594-408b-ad07-3056b16afff0)

**Comment by AngeNTF** [comment]
> ### The problem
> Open cmd, your tool of choice, or close to resolve manually
> 
> ### Release version
> 3.2.7
> 
> ### Operating system
> Windows
> 
> ### Steps to reproduce the behavior
> _No response_
> 
> ### Log files
> _No response_
> 
> ### Screenshots
> ![Screenshot (892)](https://user-images.githubusercontent.com/87268503/260212662-caf7c573-8594-408b-ad07-3056b16afff0.png)
> 
> ### Additional context
> _No response_

Job well done thaniı

**Comment by AngeNTF** [comment]
Never work everyone

**Comment by tidy-dev** [comment]
@itstalmeez Could you please fill out the entire issue template including steps to reproduce so we can better understand the issue you are having?
