### ISSUE TITLE
TimeStamp and user account 

### ISSUE THREAD

**Issue by Pretty023** [desktop/desktop#17226]
### The problem

When i create a branch as a member of an organization Github displays the updated by (the organization) instead of the user who created the branch and logged in as . The updated time is always behind 

### Release version

Version 3.2.7 

### Operating system

Windows 11

### Screenshots

![git](https://github.com/desktop/desktop/assets/107463917/7f6014a4-4cc1-4270-ad8f-92528643e3e1)

**Comment by sergiou87** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
