### ISSUE TITLE
Issue cloning a repo with "git" in the end of the name

### ISSUE THREAD

**Issue by moxie-coder** [desktop/desktop#17221]
### The problem

There's an issue where an error would show up when you try to clone a repo with "git" in the name, specifically an error where it said the repo doesn't exist, in spite of it existing, and having an good internet connection.

### Release version

3.2.7

### Operating system

Windows 11 (x64)

### Screenshots

![image](https://github.com/desktop/desktop/assets/124418090/c949643d-7459-4793-8660-cfc2421632e0)

**Comment by steveward** [comment]
@MemeHovy can you verify that you have the correct access permissions for this repository, since it is owned by a different user? You will need to be added as a collaborator in order to access a private repository under another user's account.

**Comment by moxie-coder** [comment]
> @MemeHovy can you verify that you have the correct access permissions for this repository, since it is owned by a different user? You will need to be added as a collaborator in order to access a private repository under another user's account.

I can confirm I have write access to the repository.

![image](https://github.com/desktop/desktop/assets/124418090/e786308f-c975-463e-9389-d42c10febcd8)

**Comment by steveward** [comment]
Can you try going to `File` > `Clone Repository` and hitting the refresh button there to see if that refresh shows the repository in the list?

**Comment by moxie-coder** [comment]
> Can you try going to `File` > `Clone Repository` and hitting the refresh button there to see if that refresh shows the repository in the list?

I've tried this and it shows up, and I can clone it from there without no problems.

**Comment by sergiou87** [comment]
Thanks for your report @MemeHovy !

I've been able to reproduce the issue, and it seems to be related to [these regexes](https://github.com/desktop/desktop/blob/57baa548770bfde5c23737783d50048d9432e7ab/app/src/lib/remote-parsing.ts#L27-L27) we use, where we strip the `.git` pattern at the end… but the `.` should be escaped (otherwise it takes __any__ character before `git` like `-` in your case 😱 )

I will submit a fix ASAP
