### ISSUE TITLE
Cannot install github desktop

### ISSUE THREAD

**Issue by hadi-aist** [desktop/desktop#17236]
### The problem

Attempted multiple times to download and install GitHub Desktop. Windows dialogue box states that "Installation has failed." It prompts me to check the setup log for more information

### Release version

3.28

### Operating system

22H2 build 22621.2134

### Log files

[SquirrelSetup.log](https://github.com/desktop/desktop/files/12369767/SquirrelSetup.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/102711194/9103080a-aab8-44b7-a3a5-2366f1506aee)

**Comment by steveward** [comment]
@hadi-aist thanks for the issue. I'm seeing this error in the log file:

```
2023-08-17 20:10:29> Program: Install path C:\Users\ahmad\AppData\Local\GitHubDesktop already exists, burning it to the ground
2023-08-17 20:10:30> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.IO.IOException: The file or directory is corrupted and unreadable.
```

Can you go try deleting the `C:\Users\ahmad\AppData\Local\GitHubDesktop` mentioned above to see if that resolves this issue? If that doesn't work then it may be worth running `chkdsk` from the command line to verify there aren't any disk issues like the error mentioned.

**Comment by hadi-aist** [comment]
I cannot delete `C:\Users\ahmad\AppData\Local\GitHubDesktop` because `C:\Users\ahmad\AppData\Local\GitHubDesktop2\app-3.2.8\resources\app` folder has been corrupted or unreadable. I resolved it with rename `GitHubDesktop` folder.

**Comment by ojolanre** [comment]
[Uploading SquirrelSetup.log…]()
Currently experiencing the same issues as the OP and the solution above didn't resolve mine.

**Comment by roshaant** [comment]
has anyone found solution to this problem?

**Comment by ojolanre** [comment]
> has anyone found solution to this problem?

I recently wiped my PC and it installed, couldn't find a working solution

**Comment by Lady-kimi** [comment]
> Cargando SquirrelSetup.log… Actualmente estoy experimentando los mismos problemas que el OP y la solución anterior no resolvió los míos.

same, pls solution ...

**Comment by marianrda** [comment]
@ojolanre @roshaant @Lady-kimi Today I experienced the same issue in my windows 10 pro version when tried to install GH-version 3.4.21. Tried all the suggested solutions but none worked. Tried installing older versions starting from 3.4.20 but it didn't worked too.

However, I randomly picked 3.4.13 which released in Jan,25 which worked fine for me.
