### ISSUE TITLE
Group filenames based on directory

### ISSUE THREAD

**Issue by iosifnicolae2** [desktop/desktop#17246]
### The feature request

We would like to be able to select an entire directory easier and then commit it.

### Proposed solution

Allow the user to group the displayed filenames in a hierarchical view.

**Comment by steveward** [comment]
Thanks for the feedback @iosifnicolae2! It sounds like you are interested in a tree view, which has been requested by quite a few other users. Currently it isn't on our radar, but I'll reference this in https://github.com/desktop/desktop/issues/2417 where we are tracking this feedback.

**Comment by iosifnicolae2** [comment]
hmm, but both tasks are being closed and no news on this front for the last 2 years..

**Comment by mesqueeb** [comment]
@steveward can you re-open #2417 ?
