### ISSUE TITLE
I cannot select an empty folder for cloning

### ISSUE THREAD

**Issue by prabeshbista** [desktop/desktop#17249]
### The feature request

I want to upload the html and CSS file on github from the Github desktop app. However, I cannot select an empty folder to clone. I want to upload the whole folder so I use Github desktop

### Proposed solution

I dont know

**Comment by sergiou87** [comment]
Hello @prabeshbista ! 👋 

Have you already created a repository on https://github.com ? Could you show me a screenshot of the exact error you're getting?

Thank you!
