### ISSUE TITLE
Check for updates not showing a new version is available

### ISSUE THREAD

**Issue by tomsepper** [desktop/desktop#17247]
### The problem

Check for updates not showing a new version is available

### Release version

Version 3.2.8 (arm64)

### Operating system

macOS 13.5.1

### Steps to reproduce the behavior

- Go to GithubDesktop menu
- Click on About
- Click on Check for Updates

The result will be "You have the latest version" even though there is a newer version available on the [website](https://desktop.github.com/).

**Comment by tidy-dev** [comment]
👋 We roll out releases progressively to prevent major bugs from spreading quickly.

In any case, you can skip this process by pressing <kbd>Option</kbd>  an clicking on the `Check for Updates` button in the About dialog.

**Comment by tomsepper** [comment]
Clicking the "check for updates" button does not result in a new version showing as available.
