### ISSUE TITLE
the git hub window not display

### ISSUE THREAD

**Issue by liping012345** [desktop/desktop#17243]
### The problem

I have  used the Git Hub Desktop for many years, But yesterday it did not work. it yet shows in Dock, and when I click it , I can see it in the menu on the top as "Github Desktop" on the right if the Apple icon. but I clicked all the sub menus anyway, the git  window did not display. 

### Release version

all versions

### Operating system

Mac OS Monterey 12.6

### Steps to reproduce the behavior

Step1: Click the GitHub Desktop on the dock
Result: The Git Hub Window does not show, but the "Github Desktop" menu shows in the top of menu on the right of the apple icon

Step2: Click the"Github Desktop"  menu's sub menu, such as "About Git hub desktop", "File->Clone Repository", and so on.
Result: The Git Hub Window does not show, only help menu is on working

### Log files

there is not any error logs.

### Screenshots

![Image 2023-8-18 at 10 14](https://github.com/desktop/desktop/assets/142490896/2ee12f77-281e-4a08-8381-7366433cf0af)
![Image 2023-8-18 at 10 15](https://github.com/desktop/desktop/assets/142490896/4e9605c2-fb69-471b-9bdc-1dba422a18b9)
![Image 2023-8-18 at 10 15](https://github.com/desktop/desktop/assets/142490896/be0e7ce6-292c-4033-8646-08212fb0e836)

**Comment by steveward** [comment]
@liping012345 thanks for the issue. Can you try fully removing GitHub Desktop and reinstalling to see if that helps?

This is the command you'll need to run:

`rm -rf ~/Library/Application\ Support/GitHub\ Desktop`

Let me know if that helps.
