### ISSUE TITLE
Filter displayed files

### ISSUE THREAD

**Issue by iosifnicolae2** [desktop/desktop#17245]
### The feature request

I would like to be able to filter the files which will be commited easier (For example I would like to commit all files which path contains XYZ)

### Proposed solution

Add an option to filter the displayed files based on our search criteria.

**Comment by steveward** [comment]
Thanks for the issue @iosifnicolae2, this is being tracked in https://github.com/desktop/desktop/issues/6407 if you would like to follow along there for updates. I'm going to close this out.
