### ISSUE TITLE
fatal: unable to access 'https://github.com/Leaovo-man2/Leaovo-man2.github.io.git/': Failed to connect to github.com port 443 after 21054 ms: Couldn't connect to server

### ISSUE THREAD

**Issue by Leaovo-man2** [desktop/desktop#17250]
### The problem

`fatal: unable to access 'https://github.com/Leaovo-man2/Leaovo-man2.github.io.git/': Failed to connect to github.com port 443 after 21054 ms: Couldn't connect to server·`
是网络错误

### Release version

3.2.9

### Operating system

Windows 10

### Steps to reproduce the behavior

1.提交更改
2.推送更改
3.检查问题

### Log files

[2023-08-19.desktop.production.log](https://github.com/desktop/desktop/files/12385501/2023-08-19.desktop.production.log)

**Comment by sergiou87** [comment]
Seems like there is a problem accessing https://github.com from your computer. Can you access https://github.com from your browser? 🤔

**Comment by Leaovo-man2** [comment]
I can access github, but the speed is not good and network errors often occur 😑。


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Sergio Padrino ***@***.***>
发送时间: Tuesday, August 22, 2023 1:22:43 AM
收件人: desktop/desktop ***@***.***>
抄送: Leaovo-man2 ***@***.***>; Author ***@***.***>
主题: Re: [desktop/desktop] fatal: unable to access 'https://github.com/Leaovo-man2/Leaovo-man2.github.io.git/': Failed to connect to github.com port 443 after 21054 ms: Couldn't connect to server (Issue #17250)


Seems like there is a problem accessing https://github.com from your computer. Can you access https://github.com from your browser? 🤔

**Comment by sergiou87** [comment]
That sounds like a problem external to GitHub Desktop… I'm sorry but I don't think we can help with this issue 😞
