### ISSUE TITLE
New files not showing up in github desktop in windows 10

### ISSUE THREAD

**Issue by Zoltan45** [desktop/desktop#17258]
### The problem

New files in my local clone of my repository on my windows machine are not showing up in Github Desktop or Atom as changes to the repo.  Deletions and changes still get picked up by both.  Only new files are not being detected.  The files are not in my gitignore list.

### Release version

3.2.9 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

add a file to a cloned repo, check github desktop to see if it shows up in the repo history

**Comment by Zoltan45** [comment]
also note: I logged out and back in, did not solve the issue. I also deleted and re-cloned the repo

**Comment by sergiou87** [comment]
@Zoltan45  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Zoltan45** [comment]
[2023-08-21.desktop.production.log](https://github.com/desktop/desktop/files/12399141/2023-08-21.desktop.production.log)

**Comment by Lokhillo** [comment]
https://github.com/desktop/desktop/files/12399141/2023-08-21.desktop.production.log

**Comment by sergiou87** [comment]
Thank you @Zoltan45 ! Unfortunately I don't see anything in those logs related to the issue you reported 😞 

Could you try running `git status` from a terminal in your repository and let me know what output you get from it?

**Comment by Zoltan45** [comment]
I already added the file by uploading on the website.

Refresh index: 100% (29604/29604), done.
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean


just added a new file and here is the output:

On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

**Comment by mycriptomir** [comment]
(Без темы)
среда, 23 авг 2023 ⋅ 2:30AM – 2:50AM
Москва, стандартное время - Москва

Присоединиться в Google Meet
https://meet.google.com/woj-gzsk-oim?hs=224




Организатор
***@***.***
***@***.***

Гости
***@***.***– организатор
***@***.***
Посмотреть сведения обо всех гостях  
https://calendar.google.com/calendar/event?action=VIEW&eid=NjhvbThjcjNjNWdtOGI5cDZnczNjYjlrNzVnbThiYjFjNG9qZWJiNWNvcjZhZTltYzhyNjJkMzNjbyByZXBseStiYXhlY3dpYnR0czNnemY0em9lMzY3b2M2and3ZmV2Ym5oaGc1d2l2Z3lAcmVwbHkuZ2l0aHViLmNvbQ&tok=MjAjbWFzc2hpa3lhbkBnbWFpbC5jb205MzgyMDVmZGE0YTg1YmRmZjM5OGM0MDRjYTVkMjU5NTk0NWNkZWVj&ctz=Europe%2FMoscow&hl=ru&es=0

Отправьте ответ пользователю  
***@***.*** и  
посмотрите дополнительные сведения о мероприятии:  
https://calendar.google.com/calendar/event?action=VIEW&eid=NjhvbThjcjNjNWdtOGI5cDZnczNjYjlrNzVnbThiYjFjNG9qZWJiNWNvcjZhZTltYzhyNjJkMzNjbyByZXBseStiYXhlY3dpYnR0czNnemY0em9lMzY3b2M2and3ZmV2Ym5oaGc1d2l2Z3lAcmVwbHkuZ2l0aHViLmNvbQ&tok=MjAjbWFzc2hpa3lhbkBnbWFpbC5jb205MzgyMDVmZGE0YTg1YmRmZjM5OGM0MDRjYTVkMjU5NTk0NWNkZWVj&ctz=Europe%2FMoscow&hl=ru&es=0.
Присутствие необязательно.

~~//~~
Приглашение из Google Календаря: https://calendar.google.com/calendar/

Вы получили это письмо, так как добавлены в список гостей мероприятия.  
Чтобы перестать получать уведомления об этом мероприятии, отклоните данное  
приглашение.

Если вы перешлете это приглашение, получатель сможет отправить ответ на  
него организатору, чтобы его добавили в список гостей, приглашать других  
людей вне зависимости от статуса собственного приглашения, а также изменить  
ваш ответ.

Дополнительная информация:  
https://support.google.com/calendar/answer/37135#forwarding.

**Comment by Zoltan45** [comment]
I have a feeling my account is bugged after enabling two factor authentication

**Comment by steveward** [comment]
@Zoltan45 can you share the `.gitignore` from that repository? It's possible something was inadvertently added that is preventing new files from being detected. I would also recommend creating a new repository and testing there, to check if any global ignore patterns are set as well.

**Comment by Zoltan45** [comment]
@steveward I think you are on it.  I have never changed the gitignore, FWIW.  new repo created on my machine worked fine.  I kept trying my different mame focused repos and none worked but when i tried a non-mame repo, it works, so something in the mame gitignore file, but what? i do not know.

[gitignore.txt](https://github.com/desktop/desktop/files/12431969/gitignore.txt)

**Comment by steveward** [comment]
That does look like the issue. The `/*` line is causing those files to be ignored.  That syntax is often used if you want to exclude everything except a specific folder. The `/*/` line will cause files in folders to also be ignored, so you'll likely want to remove that line as well. I'd recommend taking a look at the [examples](https://git-scm.com/docs/gitignore#_examples) for syntax if there is something specific you are wanting to accomplish in your .gitignore.

Since we've identified that this isn't an issue with GitHub Desktop I'm going to close this out. Let me know if you have any other questions.

**Comment by Zoltan45** [comment]
@steveward I appreciate the help, but at the same time, this git ignore has been in two of my repos for quite awhile. Any idea why it just started acting this way now?  The last time I attempted to add files to either repo, Github Desktop and Atom worked fine.  Can not be sure about command line TBH.

Thanks again.

**Comment by Zoltan45** [comment]
@steveward Its ok to say the problem is between my shoulders. I see that now :)  Thanks to those who took the time to look into it.
