### ISSUE TITLE
Error opening Github Desktop on Mac

### ISSUE THREAD

**Issue by JamesWWilson** [desktop/desktop#17255]
### The problem

![image](https://github.com/desktop/desktop/assets/28519905/37d2cd0a-7f96-4463-983c-cac38521acbe)
When attempting to open Github Desktop, I encounter the attached screenshot, which depicts the System Settings icon with no text. The box shows no indication of what the associated error is. 

I believe the issue is likely tied to an error I made during installation when I approved the associated package install request and canceled the process during installation when I wanted to double check the install. The process is no longer available. 

**Which files should I be attempting to remove?** I deleted the application multiple times and files associated with it to no avail. 

### Release version

3.2.9

### Operating system

Ventura 13.4 (22F66)

### Steps to reproduce the behavior

Download Github Desktop

Say yes when it asks you to install additional packages

Close application before download can be completed. 

### Log files

********************************
Finder: DRDeviceCopyDeviceForBSDName(disk4s1) failed

********************************
Finder: DRDeviceCopyDeviceForBSDName(disk4s1) failed

********************************
Finder: DRDeviceCopyDeviceForBSDName(disk4s1) failed

********************************
Finder: DRDeviceCopyDeviceForBSDName(disk4s1) failed

********************************
Finder: DRDeviceCopyDeviceForBSDName(disk5s1) failed

********************************
Finder: DRDeviceCopyDeviceForBSDName(disk5s1) failed

### Screenshots

![image](https://github.com/desktop/desktop/assets/28519905/37d2cd0a-7f96-4463-983c-cac38521acbe)

**Comment by steveward** [comment]
@JamesWWilson any application files can be removed by running this:

`rm -rf ~/Library/Application\ Support/GitHub\ Desktop`

Let me know if that doesn't get things working.

**Comment by JamesWWilson** [comment]
Thank you! I did run that command in the terminal and restarted my mac, and was able to return to the previous window and install Rosetta properly this time. See screenshot attached. Issue solved. 
![image](https://github.com/desktop/desktop/assets/28519905/10a302b7-53af-49b8-a1c9-498181384f3b)
