### ISSUE TITLE
can't add non-github repos

### ISSUE THREAD

**Issue by isomorphisms** [desktop/desktop#1725]
```git clone http://blizzard.coli.uni-saarland.de/root/blizzard_training_data/tree/CSTR```

### Description

```
fatal: http://blizzard.coli.uni-saarland.de/root/blizzard_training_data/tree/CSTR/info/refs not valid: is this a git repo?
```

### Version

Windows 10
**GitHub Desktop version:** Version `0.5.7`

same problem at command line git `version 2.11.0.windows.1`

same problem at gh desktop `Chocolate-Covered Yaks (3.3.4.0) 50415df`

**OS version:** Version 10.0.14393

**Expected behaviour:** clone the repo

**Actual behaviour:** nothing

**Reproduces how often:** 100%

### Logs

> If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

Can't find `%APPDATA%`.

**Comment by shiftkey** [comment]
This is a GitLab remote - see #852 for the tracking issue for that feature.
