### ISSUE TITLE
I tried cloning a Gitlab self-managed server doesn't ask for credentials like it used to

### ISSUE THREAD

**Issue by GreenSheepGaming** [desktop/desktop#17268]
### The problem

I recently made a Gitlab self-managed server when I cloned a repository it used to ask for a username and password now it just says authentication error I tried on the stable ver and beta ver both seem not to ask for credentials. Does anyone have a fix?

### Release version

Version 3.2.10-beta1

### Operating system

Windows 11 Enterprise

### Screenshots

some of it is in German but most of it is in English
![image](https://github.com/desktop/desktop/assets/103353833/3bccdc62-8738-4c18-888f-de3f1b5f81c9)

**Comment by sergiou87** [comment]
Looks like there is a different issue there which is preventing Desktop from even trying to clone. It seems the HTTPS certificate of your self-managed server has expired. Either renewing that or maybe even enabling HTTP access should fix this. Please take a look and let us know!

**Comment by GreenSheepGaming** [comment]
Ok I will take a look
