### ISSUE TITLE
GHES loging still not working

### ISSUE THREAD

**Issue by mscott3k** [desktop/desktop#17265]
### The problem

After updating to v3.2.9 I am unable to login to my companies enterprise instance. Looking at the git repo, I saw the change log mentioned another fix for this issue in 3.2.10-beta and tried updating to see if this resolved my issue, but it hasn't. 

This summary below applies to both 3.2.9 and 3.2.10-beta.

When siging into GHES through the options, the login is sucessful through the browser login. 
![image](https://github.com/desktop/desktop/assets/45612304/9bafe485-5ed2-4ba2-841a-6ec96bb369b7)

But when I try to interact with any repo new or existing I get an "Authetication Failed" error message. 
![image](https://github.com/desktop/desktop/assets/45612304/c0905876-ea05-4435-ab62-5c16901c2f60)

Checking the logs I see this authentication failed message: 
![image](https://github.com/desktop/desktop/assets/45612304/21a4c407-bcab-4414-8b56-ef408353465a)

When I try to login using username and password I recieve the error that username and password is incorrect
![image](https://github.com/desktop/desktop/assets/45612304/cdb83de3-a0af-4fc2-8fae-ac1a422d4324)

The username and password is confirmed working by logging into GHES web portal. 

### Release version

3.2.10-beta

### Operating system

WIndows 10 Professional

**Comment by sergiou87** [comment]
Weird 🤔 I don't think we have changed anything that could affect this, but I might be wrong!

Could you try using username and password from the command line directly and see if that works?

**Comment by mscott3k** [comment]
My enterprise IT broke our region replication at the same time as this update was pushed, once that was fixed this issue was also resolved. My apologies!
