### ISSUE TITLE
Rebase is disabled if merge was done first

### ISSUE THREAD

**Issue by PunkPun** [desktop/desktop#17260]
### The problem

When people mess up the git workflow this bug prevents them from fixing it. Specific situation here is `merge` was accidentally used, and to fix it `rebase` is needed to be run, yet the github desktop UI prevents the user from doing so.

Fwiw in terminal `git rebase` works just fine

### Release version

3.2.9

### Screenshots

"There are no commits on the current branch to rebase"

<img width="241" alt="Screenshot 2023-08-22 at 00 17 11" src="https://github.com/desktop/desktop/assets/37534529/712bbe64-de6f-43b6-925a-268188e124cd">

**Comment by sergiou87** [comment]
Hey @PunkPun ! 👋 

Thanks for your report, could you write some detailed steps to reproduce this problem?

**Comment by PunkPun** [comment]
1. clone a branch
2. make some changes on the clone
3. make some changes on the original branch
4. merge the original branch into the clone
5. you aren't allowed to rebase the clone onto the original

This can happen often when asked to update a pull request onto the newest upstream branch

**Comment by sergiou87** [comment]
This is happening with a fork, right? Because I don't think step (4) is even possible in a regular repository.

**Comment by sergiou87** [comment]
If I understand it right, after merging you get into this kind of state:

```mermaid
%%{init: { 'gitGraph': { 'mainBranchName': 'upstream/main'}} }%%
gitGraph
   commit
   branch main
   commit
   checkout upstream/main
   commit
   checkout main
   merge upstream/main
```

And you wish to rebase to clean that merge commit up and end up like this:

```mermaid
%%{init: { 'gitGraph': { 'mainBranchName': 'upstream/main'}} }%%
gitGraph
   commit
   commit
   branch main
   commit
```

Is that right?

**Comment by PunkPun** [comment]
That looks about right.

Just to reiterate `git rebase upstream/main` is all that it takes takes for the cleanup. I'd just like to be able to do the same with github desktop as consistently as with git. Or more specifically help people who don't have git setup do this

**Comment by mungojam** [comment]
@PunkPun This has wound me up for ever :) Thank you for raising and getting it fixed. I assumed it was just a git limitation
