### ISSUE TITLE
UI problem

### ISSUE THREAD

**Issue by josee333** [desktop/desktop#17261]
### The problem

The interface looks very pixelated and since it keeps the images or the letters when you change to another branch, it has visual optimization problems.

### Release version

Last

### Operating system

Windows 11

**Comment by ShivamNimbalkar** [comment]
josee333  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by josee333** [comment]
Hi, this is the information:2023-08-22T00:10:04.564Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 1.091s)2023-08-22T00:10:05.246Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 1.9s of which 0.0s paused, total 1.9s2023-08-22T00:18:59.325Z - info: [ui] [Timing] Action 'checkout branch from list' for 'eon-back' took 0.000s2023-08-22T00:19:01.416Z - info: [ui] [Timing] Action 'stash and checkout' for 'eon-back' took 0.749s2023-08-22T00:25:07.586Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 0.1s of which 0.0s paused, total 0.1s2023-08-22T00:25:10.669Z - info: [ui] [Timing] Action 'checkout branch from list' for 'eon-back' took 0.482s2023-08-22T00:25:14.639Z - info: [ui] [AppStore. _popStashEntry] popped stash with commit id 5cfd540ca12433f276a9996e2869b3449437adc22023-08-22T04:40:54.688Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}2023-08-22T04:40:55.258Z - info: [ui] [AppStore] loading 2 repositories from store2023-08-22T04:40:55.466Z - info: [ui] launching: 3.2.9 (Windows 10.0.22621)2023-08-22T04:40:55.469Z - info: [ui] execPath: 'C:\Users\joser\AppData\Local\GitHubDesktop\app-3.2.9\GitHubDesktop.exe'2023-08-22T04:41:14.269Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 1.072s)2023-08-22T04:41:17.299Z - info: [ui] [Timing] Action 'checkout branch from list' for 'eon-back' took 0.000s And screenshot: As you can see, it has a kind of ghost effect when I change branches, it stays that way until I move from the repository and also the source gets pixelated. José Carlos Hernández De: SHIVAM GAJANAN NIMBALKAREnviado: lunes, 21 de agosto de 2023 22:39Para: desktop/desktopCC: josee333; MentionAsunto: Re: [desktop/desktop] UI problem (Issue ***@***.*** Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by sergiou87** [comment]
Hey @josee333 ! 👋 

Unfortunately we can't see your screenshot. If you posted it via email, please try using GitHub's UI to do so. Thanks!

**Comment by josee333** [comment]
Sorry, its that!
Hi, this is the information:
2023-08-22T00:10:04.564Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 1.091s)
2023-08-22T00:10:05.246Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 1.9s of which 0.0s paused, total 1.9s
2023-08-22T00:18:59.325Z - info: [ui] [Timing] Action 'checkout branch from list' for 'eon-back' took 0.000s
2023-08-22T00:19:01.416Z - info: [ui] [Timing] Action 'stash and checkout' for 'eon-back' took 0.749s
2023-08-22T00:25:07.586Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 0.1s of which 0.0s paused, total 0.1s
2023-08-22T00:25:10.669Z - info: [ui] [Timing] Action 'checkout branch from list' for 'eon-back' took 0.482s
2023-08-22T00:25:14.639Z - info: [ui] [AppStore. _popStashEntry] popped stash with commit id 5cfd540ca12433f276a9996e2869b3449437adc2
2023-08-22T04:40:54.688Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-08-22T04:40:55.258Z - info: [ui] [AppStore] loading 2 repositories from store
2023-08-22T04:40:55.466Z - info: [ui] launching: 3.2.9 (Windows 10.0.22621)
2023-08-22T04:40:55.469Z - info: [ui] execPath: 'C:\Users\joser\AppData\Local\GitHubDesktop\app-3.2.9\GitHubDesktop.exe'
2023-08-22T04:41:14.269Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 1.072s)
2023-08-22T04:41:17.299Z - info: [ui] [Timing] Action 'checkout branch from list' for 'eon-back' took 0.000s
 
And screenshot: 
As you can see, it has a kind of ghost effect when I change branches, it stays that way until I move from the repository and also the source gets pixelated.
![Captura de pantalla 2023-08-21 224129](https://github.com/desktop/desktop/assets/61714872/71993770-0bdc-4ba1-b986-e400382636e1)

**Comment by sergiou87** [comment]
That is really weird… have you tried to reboot your machine and make sure graphics drivers are up-to-date? 🤔

**Comment by josee333** [comment]
Yes, I already restarted my computer and even the graphics. It also happens on my work computer, this started happening last week

**Comment by sergiou87** [comment]
Do both machines have the same graphics card and Windows version? We haven't seen other reports like this, so I wonder what's special about your two computers 🤔

**Comment by josee333** [comment]
No, my personal computer has an NVIDIA 3050 TI laptop graphics card with a RYZEN 5 5000 series and my work computer is the integrated graphics of a RYZEN 5 RADEON 5000 series processor.

**Comment by steveward** [comment]
@josee333 have you changed the [scaling](https://support.microsoft.com/en-us/windows/view-display-settings-in-windows-37f0e05e-98a9-474c-317a-e85422daa8bb) on these machines at all?

**Comment by niik** [comment]
Hey @josee333, looks like something odd is going on either with your graphics card drivers or the graphics card itself.

You can try launching GitHub Desktop with GPU accelerated rendering turned off to verify that it is indeed related to the GPU  by setting the GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION environment variable to 1 by running `set GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1` in cmd.exe and restarting your machine or by setting it through the UI following a guide like this: https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0

Note that you may have to restart your machine for the changes to take effect.

Please let us know if that helped!

**Comment by josee333** [comment]
@niik Hello, I was able to solve the problem. I recently changed my monitor cable from hdmi to DP, but what I didn't realize is that nvidia graphics needs a DP to usb C driver. I installed that driver for DP use and it worked fine, giving me A lot of doubt is that in the only programs that this ghost effect happened to me, it was only in Visual studio code and Github for desktop

**Comment by niik** [comment]
Glad to hear you were able to resolve it!
