### ISSUE TITLE
GitHub Desktop Add Local Repository Issue

### ISSUE THREAD

**Issue by bilawal-cyber** [desktop/desktop#17262]
### The problem

When I drag the project into the GitHub desktop to create a new repository, it says "The directory does not appear to be a Git repository. Would you like to create a repository here instead?". And then I click the option to create a repository. fill out the details. and click "Create repository". The local repository is created and my project now has the .git folder.
But the GitHub desktop didn't go to the current repository window. Instead, it says again "The directory does not appear to be a Git repository. Would you like to create a repository here instead?". And it goes on and on. until I clicked the cancel button and then I can go to the current repository window.

### Release version

Version 3.2.7 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Paste any project folder into the GitHub desktop.
2. Click on create a repository.
3. Fill out project details and again click on "Create repository"

### Log files

[2023-08-21.desktop.production.log](https://github.com/desktop/desktop/files/12405496/2023-08-21.desktop.production.log)
[2023-08-22.desktop.production.log](https://github.com/desktop/desktop/files/12405497/2023-08-22.desktop.production.log)

**Comment by sergiou87** [comment]
Thanks for your report @bilawal-cyber ! I just submitted a fix in https://github.com/desktop/desktop/pull/17263

Despite getting back to the "add existing repo" dialog you're seeing, you repo should've been correctly created. This is mostly a cosmetic (but very confusing) issue.
