### ISSUE TITLE
See current branch in repository selector

### ISSUE THREAD

**Issue by iwllyu** [desktop/desktop#17274]
### See current branch in repository selector 
I use [git-worktree](https://git-scm.com/docs/git-worktree) so I have multiple "copies" of the same repository. While it's very fast to switch between these repos, it's confusing because I'm not sure what branch is on each repo.

Here's what I see in Git Desktop
<img width="761" alt="image" src="https://github.com/desktop/desktop/assets/5480967/3486b977-558f-4467-9a06-e328b421b8b2">

Here's a similar view from Sourcetree
<img width="846" alt="image" src="https://github.com/desktop/desktop/assets/5480967/92d3a6ab-a3f3-4026-a3b8-a379ef58c8b3">

### Proposed solution

Display the current branch on the right side of the repository selector

**Comment by steveward** [comment]
Thanks for the request @iwllyu, I'm going to add this to https://github.com/desktop/desktop/issues/8158 where we are tracking this feature.
