### ISSUE TITLE
Add option to ignore directory to .gitignore through mouse context menu

### ISSUE THREAD

**Issue by Zvendson** [desktop/desktop#17273]
### The feature request

Just as simple as the titles says. I would love to have something like this.
Should just analyse if the newly added file is in a directory (and/or sub-directories) and add the suggestion(s).
Would limit it to max. 2 sub-directory to not run into a huge mouse context menu.

### Proposed solution

I think its quite clear how it would benefit us. Its mostly useful for new projects or new features.

For my personal example. I have a project that creates a directory and create log files and other file types in there. I have to manually add the directory to `.gitignore`. Just think it adds a small nice experience using desktop.

Cheers.

### Additional context

![image](https://github.com/desktop/desktop/assets/25896065/c3b117c8-d12f-48ff-afda-8b2d78123e0d)

**Comment by steveward** [comment]
Thanks for the issue @Zvendson! I'm going to reference this in https://github.com/desktop/desktop/issues/1203 where we are tracking this.
