### ISSUE TITLE
No list of repositories in the window "Clone a repository"

### ISSUE THREAD

**Issue by h8nor** [desktop/desktop#17275]
### The problem

Signed in is performed. The list of repositories is not visible.

### Release version

3.2.9

### Operating system

Windows 10

### Steps to reproduce the behavior

1. I press keys combination the <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>O</kbd>
2. I try to update repositories list in the tab `Github.com`

### Screenshots

<details><summary>Screenshot after step 2</summary>

![403](https://github.com/desktop/desktop/assets/6163937/65147279-677a-4abd-93e6-4bd89be63449)

![log](https://github.com/desktop/desktop/assets/6163937/d6fec40e-592e-49ed-8551-224818203739)

</details> 

### Additional context

<details><summary>An attempt to cloning a private repository leads to a similar mistake.</summary>

![clone](https://github.com/desktop/desktop/assets/6163937/642b7037-c2b9-41d0-af85-eb766ee793f3)

But after a repeated attempt, the repository is cloned.

![retry](https://github.com/desktop/desktop/assets/6163937/8ea9857b-826b-4ab5-b073-ab419e11d0ac)

Done.

</details>

**Comment by steveward** [comment]
Thanks for the report @h8nor. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by h8nor** [comment]
Unfortunately I can't provide the log for today.

**Comment by h8nor** [comment]
Today I tried to clone the repository. The situation was repeated, but it was not possible to clone my private repository.

![error](https://github.com/desktop/desktop/assets/6163937/69d1f491-17ef-445c-8d03-9be2dfdf6d67)
Log is [there](https://github.com/desktop/desktop/files/12428584/2023-08-24.desktop.production.log).

**Comment by steveward** [comment]
It looks like there is a token issue:

```
2023-08-24T10:35:49.611Z - info: [ui] [AppStore] found account: h8nor (h8nor)
2023-08-24T10:35:49.637Z - info: [ui] [BranchPruner] Last prune took place 4 minutes ago - skipping
2023-08-24T10:35:50.272Z - warn: [ui] Error refreshing account 'h8nor'
Error: Cannot update an account which doesn't have a token: h8nor
```

Have you already tried signing out/signing back in? You could also manually reset the app to see if that gets things working:

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop

You will need to log in and add your repositories again, which can be done quickly in bulk by drag-and-drop.

Let me know if that helps.

**Comment by h8nor** [comment]
Yes, the solution helped me. Thanks for help. What could it be?

The interesting thing is that I renamed the old directory and after signing back in I closed the app and renamed it back. I can see all my repos!

I recently connected to another server, entered my login and password as indicated in the window on screenshot #16992. I do not know if this could affect and where the passwords are stored.
