### ISSUE TITLE
"Summary" field loses focus when switching back to the application

### ISSUE THREAD

**Issue by aybe** [desktop/desktop#17283]
### The problem

The workflow:

1. edit some stuff on the IDE and save files
2. switch to application with Alt-Tab
3. click on summary
4. enter a message and commit with Ctrl-Enter

Trying do that a second time (beside step 3) simply won't work, the focus to summary field is lost.

If I Shift-Tab it focuses the committer field, if I Tab it focuses the description field, i.e. it's lost in between.

Using the console to see [focused element](https://developer.chrome.com/docs/devtools/accessibility/focus/), it is `body.platform-win32.theme-dark`, i.e. the window whereas if I look for summary it is `input#__autocompleting-text-input`.

**This used to work back then.**

Right now the fix is to Tab once to go description then Shift-Tab to go back to summary.

### Release version

Version 3.2.9 (x64)

### Operating system

Windows 11

### Log files

The log looks broken, now it's 12:43PM but last entry is 10:33AM, did some commits between but they're not being shown.

[2023-08-26.desktop.production.log](https://github.com/desktop/desktop/files/12445120/2023-08-26.desktop.production.log)

**Comment by niik** [comment]
Hey @aybe, thanks for reaching out and thanks for the detailed reproduction steps. I've just merged https://github.com/desktop/desktop/pull/17307 to address this and it should make it into the next production release in a few weeks. You can also consider switching to our beta channel (instructions in the README) which we release to more frequently.

**Comment by aybe** [comment]
Thank you!
