### ISSUE TITLE
Cloning and sign-in not working and crashing browser (Opera)

### ISSUE THREAD

**Issue by 192933488S** [desktop/desktop#17299]
### The problem

The cloning and sign-in is not working.

It forced the browser to restart completely, shattering several working URLs, disabling addons, etc.

Cycle does not complete, asks for another "open in browser" and over-runs the existing open browser, etc.

### Release version

3.2.9

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Run GHD
2. Try to clone a repository from GH
3. Go through the external-login cycle (browser) -- latest Opera in my case 101.0.4843.58
4. The cycle does not complete, the browser gets hard restarted, addons become disable, "near reset level"

**Comment by niik** [comment]
Hi @192933488S, sorry to hear you're having problems. Could you try temporarily changing your system default browser to another browser to rule out issues with your current one?

**Comment by 192933488S** [comment]
Thanks for the fast response.

Confirming that works with default set to 'Chrome'. There, the login screen is loading + MFA. In Opera, nothing is showing or loading.

**Comment by niik** [comment]
Glad to hear you were able to work around it!
