### ISSUE TITLE
Error : `Command failed: /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git log`

### ISSUE THREAD

**Issue by lucaszischka** [desktop/desktop#17303]
### The problem

When I open GitHub desktop I get the following error:

```
Command failed: /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git log 720ddbd1371fef2a09cc1ab65fc503df37767f9c --date=raw --max-count=1 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color --
```

### Release version

Version 3.2.9 (arm64)

### Operating system

macOS 14.0 Beta (23A5328b)

### Log files

[2023-08-29.desktop.production.log](https://github.com/desktop/desktop/files/12465532/2023-08-29.desktop.production.log)

### Screenshots

<img width="1470" alt="Screenshot 2023-08-29 at 16 16 50" src="https://github.com/desktop/desktop/assets/63545066/83369013-e1e9-4b2d-909f-d4ca118bbe80">

**Comment by steveward** [comment]
@lucaszischka thanks for the issue. It looks like a specific commit is causing issues in your repository:

`Error: Could not load commit: '720ddbd1371fef2a09cc1ab65fc503df37767f9c'`

Can you open the repository in the command line and run the command `git fsck` to see if there are any identifiable issues in your repository?

**Comment by lucaszischka** [comment]
Hello @steveward,
Thank you for your quick answer! After I removed and re-added the Project to GitHub Desktop, the issue disappeared. I can currently not reproduce it anymore. However im quite sure that this was not an issue with the git repository itself. Closing the issue it for now, as no longer reproduce-able.
