### ISSUE TITLE
Group repositories into categories and subcategories

### ISSUE THREAD

**Issue by crar01** [desktop/desktop#17302]
### The feature request

I have a lot of repositories and I want to organize them into categories, for example:
- Personal
  - Conquer the world
- Work
  - Team XForce
  - Team Justice League
  - Team Avengers
- University
- Others
- etc...

### Proposed solution

- Add a similar dropdown to the "Current Repository" dropdown, to select the category and show the repositories of that category
- Add a new option to the "Category" dropdown, to create a new category (edit, delete, etc...)
- Add an option to the repository to add it to any category (or create a new one)

**Comment by steveward** [comment]
Thanks for the feedback @crar01. See [this comment](https://github.com/desktop/desktop/issues/10201#issuecomment-658693653) for more information about why we do not have plans to implement repository grouping at this time. 

One workaround is to use the repository alias feature and then use that to filter by a specific alias prefix. I hope that helps.
