### ISSUE TITLE
Unable to open browser to sign in to Github Desktop

### ISSUE THREAD

**Issue by chiruplayer** [desktop/desktop#17300]
### The problem

I am trying to login to Github Desktop. It is supposed to open a browser so that I can enter my credentials. However, that isn't happening. It is waiting for something, and I cant login.

![image](https://github.com/desktop/desktop/assets/8570787/8f5dd710-bc75-49d0-9869-fe61bae84630)

![image](https://github.com/desktop/desktop/assets/8570787/41becae4-2e44-4cda-bd5c-8664d8a1de9e)

### Release version

Version 3.2.9 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

file > options > Accounts
Click on sign in
Continue with browser

### Log files

[2023-08-28.desktop.production.log](https://github.com/desktop/desktop/files/12456498/2023-08-28.desktop.production.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/8570787/8f5dd710-bc75-49d0-9869-fe61bae84630)

![image](https://github.com/desktop/desktop/assets/8570787/41becae4-2e44-4cda-bd5c-8664d8a1de9e)

**Comment by niik** [comment]
Hi @chiruplayer, sorry to hear you're having problems. Could you try temporarily changing your system default browser to another browser to rule out issues with your current one?
