### ISSUE TITLE
Unable to commit with Signed Commit Rule and SSH

### ISSUE THREAD

**Issue by elawad** [desktop/desktop#17309]
### The problem

Hello, I just upgraded GH Desktop, but now can no longer commit.
We have Rulesets that require signed commits, and have SSH setup for verified commits.
Before the upgrade today, all was working. Now I get an error message in Desktop preventing commits.

Please see screenshots / gitconfig below.

### Release version

3.3.0 (arm64)

### Operating system

macOS Ventura 13.5

### Steps to reproduce the behavior

Setup SSH on macOS and Github.
Add GH Ruleset to require Commit Signature.
Try to commit using Desktop.
Unable to commit even though SSH signed commits is active, and verified by previous commits.

#### Error:
<img width="390" alt="desktop-error" src="https://github.com/desktop/desktop/assets/313249/ff998d3f-6236-4d90-919b-9721529405ad">

#### Rulesets:
<img width="500" alt="rulesets-signed-commits" src="https://github.com/desktop/desktop/assets/313249/59803aa9-c309-483a-b5b6-cd6555fe5352">

#### SSH Commits:
<img width="700" alt="ssh-commits" src="https://github.com/desktop/desktop/assets/313249/f31cb3a2-d6b1-4c06-b1a6-dabe2a06a506">

#### .gitconfig
```
[user]
  name = <name>
  email = <email>
  signingKey = ~/.ssh/id_ed25519.pub

[credential]
  helper = osxkeychain

[gpg]
  format = ssh

[commit]
  gpgSign = true
```

**Comment by vaindil** [comment]
I'm taking a look at this now, should be a quick fix.

**Comment by elawad** [comment]
Thanks for the prompt feedback!

**Comment by tidy-dev** [comment]
@elawad We have pulled the release from auto updating and downloading until the hotfix can be released. It looks like it will be tomorrow before it will be released. You can redownload 3.2.9 from https://desktop.github.com/ to get unblocked. Thank you for the quick report! We had only released to 25% of our user base so your report may very well have prevented other users from being impacted while we get the fix out. 🙇

**Comment by elawad** [comment]
Awesome, glad it was caught early. And I'll revert for now, until the hotfix is out.

Thanks again.

**Comment by tidy-dev** [comment]
The hotfix is out. We are still proceeding with a slow roll out. Thus, you may or may not see the auto update at this time. If you want the latest anyhow, you can download it via holding the option key down in the about dialog to see the "Ensure Latest Version" button, or re-downloading it again from the website.
