### ISSUE TITLE
Configuration file for new repo creation

### ISSUE THREAD

**Issue by SwamiKannan** [desktop/desktop#17312]
### The feature request

Automatically update gitignore based on a configuration file. For example, I can configure github desktop to automatically update my .gitignore on new repo creation to ignore all .env files or any specific .json / api key files (name specified in the proposed configuration). 

### Proposed solution

Reduce the risk of leaking keys or any other security-related data in case the .gitignore file is not updated before committing / pushing the changes

**Comment by steveward** [comment]
Thanks for the issue @SwamiKannan. It sounds like you are interested in repository templates, which would support this type of feature. Repository templates allow you to have a configured repository base that you can use when creating a new repository. We are tracking support for this in https://github.com/desktop/desktop/issues/7902, but at this time implementing this feature is not on our radar.

If you're interested I would also recommend checking out [secret scanning](https://docs.github.com/en/code-security/secret-scanning/push-protection-for-users), which can provide push protection to help prevent secrets from being leaked. I hope that helps!
