### ISSUE TITLE
Option window closing when I switch to GIT or Advanced tab

### ISSUE THREAD

**Issue by gaalalexandru** [desktop/desktop#1731]
### Description
Option window (Ctrl + ,) automatically closes when I switch to GIT or Advanced tab

### Version
**GitHub Desktop version:** Version 0.5.7 (beta)
**OS version:** Windows 7 Professional with SP1 - Microsoft Windows [Version 6.1.7601]

### Steps to Reproduce
1. Open Github desktop application
2. Open options menu
3. Switch to GIT or Advanced tab

**Expected behaviour:** Option window not to close automatically
**Actual behaviour:** [Option window closes automatically
**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
I _think_ this is the same as #1724, which has been fixed in #1726 and should be available with the next update.
