### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by LukeChagastec** [desktop/desktop#17316]
### The feature request

If possible, create a window on the installator of windows, to let the user choose the directory of installation.

### Proposed solution

It can benefit's adminitrators or uses by choosing the destination of the files.

An example of it, is when you have a SSD, with the OS installed in it, and other stuff in another drive.

**Comment by steveward** [comment]
Thanks for the feedback @LukeChagastec. The installer we use (Squirrel) does not allow for customizing the installation directory.  See [this response](https://github.com/desktop/desktop/issues/10768#issuecomment-706096056) for some more details. You can follow along in https://github.com/desktop/desktop/issues/1086 for installation improvements, but at this time we don't have any plans to change the installation experience.

**Comment by Welding-Torch** [comment]
Hey I just installed GitHub Desktop and I have this same issue. I try to install my programs on D: to save space, and not being able to choose where to install programs is a huge pain.
