### ISSUE TITLE
Left clicking a file shortly after scrolling in the changed files list does not select the the file

### ISSUE THREAD

**Issue by bjornenalfa** [desktop/desktop#17323]
### The problem

For about half a second after scrolling in the changed files list the first left click you do will not select the file under the cursor, instead you have to double click it to select the file. This hasn't been much of an issue until recently when #16562 went live. Even though the first click does not seem to register, a double click will still open the file in the external editor. This means that selecting a file after scrolling will open it in the external editor, which is annoying.

### Release version

3.2.9

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Have enough changed files that the changed files list becomes scrollable.
2. Put your mouse cursor over a file.
3. Scroll down one step.
4. Click within 0.5 seconds and observe that nothing happens.
5. Scroll down one step again.
6. Double click within 0.5 seconds and observe that the file under the cursor gets selected and is opened in the external editor.

**Comment by steveward** [comment]
Thanks for the report @bjornenalfa. I've been trying to reproduce this, but have been unsuccessful so far. Any chance you can upload a short video of this behavior? There's likely something I'm missing. Thanks!
