### ISSUE TITLE
Add an advanced setting for default descriptions in commits

### ISSUE THREAD

**Issue by jonobr1** [desktop/desktop#17326]
### The feature request

Some projects I contribute to run complex github actions when pushing commits. When working on a PR I occasionally forget to add the `[skip ci]` and the action runs.

### Proposed solution

It would be an awesome setting to add a Default description to every commit message. One that pre-populated the "description" text field on the Github Desktop interface. Currently when committing it looks like this:

<img width="280" alt="Screenshot 2023-09-01 at 1 24 42 PM" src="https://github.com/desktop/desktop/assets/220033/d7b6118c-9288-4b64-a8d2-0ec868c5e451">

---

But it would be super handy to have a setting on your profile to default the description to be of your liking. Like:

<img width="281" alt="Screenshot 2023-09-01 at 1 24 58 PM" src="https://github.com/desktop/desktop/assets/220033/318674fb-02e7-49db-950b-dccdfad21d7f">

**Comment by steveward** [comment]
@jonobr1 thanks for the issue. Would support for commit templates align with what you are looking for here? We are tracking that in https://github.com/desktop/desktop/issues/8698.

**Comment by jonobr1** [comment]
That would totally do it. Thank you!

**Comment by steveward** [comment]
Thanks, I'll close this out.
