### ISSUE TITLE
Submodule access issues causes failures

### ISSUE THREAD

**Issue by gabelepoudre** [desktop/desktop#17325]
### The problem

I have come to see the following error frequently at my company. We use a monorepo which holds (almost) all of the code for our various projects. One of these projects uses a submodule I do not have access to.
```
fatal: not a git repository: ../../../../.git/modules/embedded/[witheld]/[witheld]/[witheld]
fatal: could not reset submodule index
```
withhelds being the path towards a submodule which I do not have access

This error corrupts my repo, mangling it to the point that I get the "Can't find [repo]" screen. This only tends to happen when I switch to a branch (including dev after a merge) that contains embedded changes, or when pulling new changes. Once in this corrupt state, other git managers begin to fail as well, with the same error.
The workaround to this error, oddly, is to delete the embedded folder (in the monorepo, not in .git) and then discard the changes. The checkout will have failed, but the repo is uncorrupted and can be discovered.

Markedly, other git clients (TortoiseGit) do not cause this issue when switching.

My guess has been that it is because I do not have access to the submodule that it fails. Either way, this submodule error probably shouldn't result in an un-findable repo

This error occurs on multiple computers

### Release version

3.3.1

### Operating system

Windows 11 Home

### Steps to reproduce the behavior

Note: untested, but can generally estimate how it would be
1. create a repo_1 on account_1, private
2. create a repo_2 on account_1, private
3. allow account_2 to see/contribute to repo_2
4. set up repo_1 as a submodule to repo_2
5. make changes in the dir containing submodule on account_1
6. pull changes on account_2 via GithubDesktop

### Log files

some information has been replaced with placeholders in the log

[2023-09-01.desktop.production.log](https://github.com/desktop/desktop/files/12500482/2023-09-01.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the issue @gabelepoudre. Have you tested this out in the command line as well to see if you are able to reproduce this? This looks similar to what has been reported in https://github.com/desktop/desktop/issues/13016, and in that issue it seemed like it was an issue with Git from the command line as well.

One workaround would be to set the submodule that you don't have access to as not active in the repository's `.git/config`.

```
[submodule "foo"]
   active = false
   url = https://example.org/foo
```

Let me know if that helps.
