### ISSUE TITLE
Repository settings popup closing on tab switching

### ISSUE THREAD

**Issue by xEtarusx** [desktop/desktop#1732]
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

The repository settings popup disappears after clicking on one of the tabs.

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** 0.5.7

The operating system you are running on may also help with reproducing the
issue:

**OS version:** Microsoft Windows [Version 10.0.10586]

### Steps to Reproduce

1. Click on "Repository" in the menu
1. Click on "Repository settings..."
1. Click on "Remote" or "Ignored files" tab to let the popup disappear.

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behaviour:** Simply switch tabs instead of closing the popup

**Actual behaviour:** The popup is closing itself when switching tabs

**Reproduces how often:** Everytime

**Comment by shiftkey** [comment]
I _think_ this is the same as #1724, which has been fixed in #1726 and should be available with the next update.
