### ISSUE TITLE
Unable to pull, push, or fetch private repo, also can't push to repo with write access

### ISSUE THREAD

**Issue by remenkemi** [desktop/desktop#17328]
### The problem

I'm the owner of an organization with a private repository. Whenever I try to pull, push, or fetch the origin of this private repo, I get the error in picture 1. It works on Windows, but not Linux.
When I push to one of the organization's repositories that I have admin access to, I get picture 2. I can commit locally but not push. Once again a Linux-only issue.

### Release version

3.2.9-linux1 (x64)

### Operating system

Linux Mint 21.2 (Victoria)

### Steps to reproduce the behavior

1. On a Linux machine, pull from, push to, or fetch a private repository your organization owns (I haven't tried it with a repo under my personal account, but the organization I own has one)

### Log files

[2023-09-03.desktop.production.log](https://github.com/desktop/desktop/files/12504950/2023-09-03.desktop.production.log)

### Screenshots
1.
![image](https://github.com/desktop/desktop/assets/64425497/676bb3f4-ebe1-4bb1-af08-a01de2263fbf)
2.
![image](https://github.com/desktop/desktop/assets/64425497/4c73c06c-a5fe-48bc-b211-4af2e332c624)

**Comment by steveward** [comment]
@crazytimtimtim this looks like the issue:

```
2023-09-03T00:24:34.228Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: Although you appear to have the correct authorization credentials, the `Stratosphere-Studios` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
```

You'll likely need to request permission to use GitHub Desktop on Linux for your org. At this time we don't provide any official support for the Linux fork, but I hope that helps.
