### ISSUE TITLE
Set The Editor Per Repository

### ISSUE THREAD

**Issue by grafst** [desktop/desktop#17334]
### The feature request

The problem is for some projects I use vscode, for some phpstorm and for some pycharm.
This makes the "Open in external Editor" Shortcut literally unusable for me.

### Proposed solution

Override the editor per repository.

Deluxe version would be to recognize the correct editor fromt the .vscode or .idea folders.

### Additional context

<img width="386" alt="2023-09-04_11-25-00" src="https://github.com/desktop/desktop/assets/8471055/8cc38165-dd78-4cf5-b234-971aa8e63dc7">

**Comment by steveward** [comment]
Thanks for the issue @grafst, this has been previously requested in https://github.com/desktop/desktop/issues/12195 so you can follow along there for updates.
