### ISSUE TITLE
The sentiment of the phrase "Focus on what matters instead of fighting with Git" is negative

### ISSUE THREAD

**Issue by JayDoubleu** [desktop/desktop#17338]
### The feature request

The sentiment of the phrase "Focus on what matters instead of fighting with Git" is negative. The word "fighting" implies that Git is a difficult or frustrating tool to use. The phrase is suggesting that you should spend your time on more important things than struggling with Git.

### Proposed solution

Use other ways to express the same sentiment in a more positive way such as:

`GitHub Desktop is a graphical user interface (GUI) for the Git version control system.`

**Comment by steveward** [comment]
Thanks for the feedback here @JayDoubleu. We're using this phrasing to express what GitHub Desktop offers as a product -- it makes it easy to do Git operations that can often be a bit confusing for beginners and advanced users alike. At this time we're not going to change this wording, but I'll make a note of it internally.
