### ISSUE TITLE
Precommit hooks don’t work

### ISSUE THREAD

**Issue by sapegin** [desktop/desktop#1734]
GitHub Desktop can’t run precommit hook, at least when using husky.

### Description

I can’t commit anything using GitHub Desktop. I have this in my `package.json`:

```json5
{
  // ...
  "devDependencies": {
    "husky": "^0.13.3",
    "lint-staged": "~3.4.2",
  },
  "scripts": {
    "precommit": "lint-staged"
  }
}
```

### Version

**GitHub Desktop version:** 0.5.7

**OS version:** 10.12.5

### Steps to Reproduce

1. Try to commit any changes via GitHub Desktop having a precommit hook.

**Expected behaviour:**

No errors when precommit hooks return no error.

**Actual behaviour:**

I see this error:

```
Commit failed - exit code 1 received, with output: '> husky - npm run -s precommit

env: node: No such file or directory

> husky - pre-commit hook failed (add --no-verify to bypass)
> husky - to debug, use 'npm run precommit''
```

(`npm run precommit` works fine. I can commit via command line without any issues.)

**Reproduces how often:**

Always.

### Logs

I don’t have any logs for today.

**Comment by niik** [comment]
I believe this is another problem with our Git shell not inheriting environment variables such as PATH on Windows, cc https://github.com/desktop/desktop/pull/1578#issuecomment-302387698

**Comment by sapegin** [comment]
Looks like so! ;-)

**Comment by joshaber** [comment]
I'm gonna roll this into #1796 so that we can track the underlying cause.
