### ISSUE TITLE
Blank (empty message) error dialog

### ISSUE THREAD

**Issue by MalcolmHannah** [desktop/desktop#17358]
### The problem

When checking for updates, a blank error dialog is shown.

I suspect the reason for the failure to check for updates relates to my company's IT infrastructure (e.g. blocking some network traffic), but I'm raising this ticket to highlight the blank error dialog.  The blank error gives my IT team nothing to investigate.

### Release version

3.3.1

### Operating system

Windows 10 (21H2 Build 19044.3086)

### Steps to reproduce the behavior

1. From the Help menu, select **About Github Desktop**.
2. In the dialog that appears, click **Check for Updates**.
The dialog displays "Checking for Updates..." for one or two seconds, then a blank error dialog is shown.
4. Click the error dialog's **Close** button.
5. Now the previous dialog is shown, but the "Checking for Updates..." is still active (busy indicator spins for ever).

### Log files

I'd prefer not to upload the entire log file.  The corresponding lines are:

2023-09-08T13:20:07.625Z - error: [ui] Error checking for updates
undefined: 
2023-09-08T13:20:48.274Z - error: [ui] Error checking for updates
undefined: 

### Screenshots

![empty-error-message](https://github.com/desktop/desktop/assets/19389579/0367aa4a-4aa9-4a15-82c3-8d14e008d419)
![after-closing-empty-error-message](https://github.com/desktop/desktop/assets/19389579/0890f4e3-367b-4158-9d96-79a36ca67862)

### Additional context

This problem is very repeatable and has been happening for a few weeks.

But somehow, the automatic update-checking does occasionally work, because I have been prompted to "restart Github Desktop to update", and those updates have succeeded, I think.

**Comment by steveward** [comment]
Thanks for the issue @MalcolmHannah. Did some digging and this looks like it was also reported in https://github.com/desktop/desktop/issues/16057#issuecomment-1492095308. I'll mark this as a bug for the team to investigate.

**Comment by steveward** [comment]
I'm going to consolidate this into https://github.com/desktop/desktop/issues/16057 by reopening that issue.
