### ISSUE TITLE
Can't clone or publish repo's

### ISSUE THREAD

**Issue by Igetsisss** [desktop/desktop#17359]
### The problem

I can't do anything basically no cloning no pulling no pushing no fetching. Its been like this since I got it like 5 days ago and I can't get it to work without errors like

fatal: unable to access 'https://github.com/Igetsisss/udfasdsdadsad.git/': CONNECT tunnel failed, response 401

Cloning into '/Users/underwoodja/Downloads/footballFRONTEND'...
fatal: unable to access 'https://github.com/Igetsisss/footballFRONTEND.git/': CONNECT tunnel failed, response 401

Would you like to retry cloning ?

### Release version

Version 3.3.1 (arm64)

### Operating system

MacBook Air 2022 Apple m2 8gb Mac OS 13.4.1

### Steps to reproduce the behavior

Go to GitHub desktop
Try to clone or publish a repository
and get this error
(for cloning)
<img width="955" alt="Screenshot 2023-09-08 at 10 38 43 AM" src="https://github.com/desktop/desktop/assets/98964802/ef8fc603-26c8-4354-b535-b75cc10d1bce">
(for publishing repo) 
<img width="953" alt="Screenshot 2023-09-08 at 10 39 12 AM" src="https://github.com/desktop/desktop/assets/98964802/3745b96a-1518-4dc7-8498-0c6127807099">

### Log files

[2023-09-06.desktop.production.log](https://github.com/desktop/desktop/files/12560952/2023-09-06.desktop.production.log)
[2023-09-08.desktop.production.log](https://github.com/desktop/desktop/files/12560953/2023-09-08.desktop.production.log)

**Comment by steveward** [comment]
@Igetsisss thanks for the issue. This looks like a problem with your network -- are you behind a proxy or firewall that could be interfering with GitHub Desktop?

**Comment by Igetsisss** [comment]
> @Igetsisss thanks for the issue. This looks like a problem with your network -- are you behind a proxy or firewall that could be interfering with GitHub Desktop?

yes i am, it's my schools proxy

**Comment by Igetsisss** [comment]
> 

also I can clone stuff from vscode so I don't know why it doesn't affect that

**Comment by steveward** [comment]
@Igetsisss since GitHub Desktop has its own bundled version of Git there will often be cases where command line Git (which VSCode is using) will work, but GitHub Desktop will be blocked. Is there an IT department you could reach out to in your school about this? You may just need to configure the proxy settings on your machine, depending on the setup.
