### ISSUE TITLE
中文版

### ISSUE THREAD

**Issue by max-fmx** [desktop/desktop#17356]
### The feature request

把菜单做成自动识别系统语言
只要菜单就够了
所有未学过英文的GitHub桌面的用户再也不用翻译英文了

**Comment by steveward** [comment]
Thanks for the issue @max-fmx. At this time we do not have language localization in GitHub Desktop, but this is something that we would like to do in the future. I don't have a timeline for when that may happen as it would require quite a bit of work by the team. I'm sorry that I don't have better news at this time.
