### ISSUE TITLE
Cant access my pages tab keeps asking for varification of domain

### ISSUE THREAD

**Issue by Goku-Cartel** [desktop/desktop#17350]
### The problem

I uploaded a static webpage but now i made some change and new repository  but github pages keeps asking me to verify the domain and i dont have a domain

### Release version

Latest

### Operating system

Windows 10

### Steps to reproduce the behavior

Sign in
Settings
Pages

### Screenshots

![20230906_124340](https://github.com/desktop/desktop/assets/98645131/56db02c7-174a-4761-bc13-9d6e9a3fb029)

### Additional context

Im not part of an organisation

**Comment by sergiou87** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
