### ISSUE TITLE
Unable to resolve reference 'refs/heads/heads/Microsoft/master'

### ISSUE THREAD

**Issue by SaschaNaz** [desktop/desktop#1736]
### Description

Pushing commits on [my TypeScript fork](https://github.com/SaschaNaz/TypeScript) shows this error:

![2017-05-24 2](https://cloud.githubusercontent.com/assets/3396686/26398668/23a1de82-40b5-11e7-8145-bab06f3a6e59.png)

Push works well regardless of the error.

### Version

**GitHub Desktop version:** 0.5.7

**OS version:** Windows 10.0.15063

### Steps to Reproduce

1. Push any commit on forked repository
1. See error
1. Click anywhere to dismiss the error dialog

**Expected behaviour:**

* Error shouldn't occur
* Error shouldn't be dismissed by clicking backdrop area

**Actual behaviour:** Error occurs and be dismissed by clicking backdrop area

**Reproduces how often:** 100%

### Logs

No logs.

**Comment by shiftkey** [comment]
Looks like we're double counting `heads` in `refs/heads/heads/Microsoft/master`.

Could you run this command against the repository to show what the tracking information is for the repository: `git config -l --local`

**Comment by SaschaNaz** [comment]
Here it is:

```
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
core.hidedotfiles=dotGitOnly
remote.origin.url=https://github.com/SaschaNaz/TypeScript.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
remote.Microsoft.url=https://github.com/Microsoft/TypeScript.git
remote.Microsoft.fetch=+refs/heads/*:refs/remotes/Microsoft/*
branch.paramListIndentFix.remote=origin
branch.paramListIndentFix.merge=refs/heads/paramListIndentFix
branch.shorterParamListIndentFix.remote=origin
branch.shorterParamListIndentFix.merge=refs/heads/shorterParamListIndentFix
branch.Microsoft/master.remote=Microsoft
branch.Microsoft/master.merge=refs/heads/master
branch.formatTernary.remote=origin
branch.formatTernary.merge=refs/heads/formatTernary
branch.Microsoft/release-1.7.remote=Microsoft
branch.Microsoft/release-1.7.merge=refs/heads/release-1.7
branch.fixMultiLineIndentation.remote=origin
branch.fixMultiLineIndentation.merge=refs/heads/fixMultiLineIndentation
branch.listIndent.remote=origin
branch.listIndent.merge=refs/heads/listIndent
branch.arraybufferview.remote=origin
branch.arraybufferview.merge=refs/heads/arraybufferview
branch.allowArguments.remote=origin
branch.allowArguments.merge=refs/heads/allowArguments
branch.newformat.remote=origin
branch.newformat.merge=refs/heads/newformat
branch.es3-d-ts.remote=origin
branch.es3-d-ts.merge=refs/heads/es3-d-ts
```

**Comment by shiftkey** [comment]
[We probably need to do something more robust here](https://github.com/desktop/desktop/blob/3dc8738e711131047f9973398a5dac08e2cd206e/app/src/lib/dispatcher/app-store.ts#L1445)

**Comment by shiftkey** [comment]
So I've got a good explainer on what's happening here - and it's to do with `Microsoft/master` being an ambiguous reference:

 - the created branch is named `Microsoft/master`
 - `Microsoft/master` is also shorthand for the `master` ref on the `Microsoft` remote

What Git does in this case is add an extra prefix to make things clear. Here's the difference:

<img width="675" src="https://user-images.githubusercontent.com/359239/26947955-0331978e-4c6b-11e7-956c-0d5b1e7cdbf1.png">

And when we're looking at it in Desktop:

<img width="356" src="https://user-images.githubusercontent.com/359239/26947888-b9b9df58-4c6a-11e7-8c1d-e22022f2a3de.png">

So `heads` is added `explicitly` to the local ref, and `remotes/` is added to the upstream ref. The `remotes/` prefix is fine to keep around, we just need to be cleverer when converting the branch name to a qualified ref.
