### ISSUE TITLE
Custom Repository Organization via Favorites

### ISSUE THREAD

**Issue by eliyahu-kriel** [desktop/desktop#17366]
### The feature request

Adding a feature that allows users to mark specific repositories as favorites. 
This can be achieved by clicking on a star icon next to the repository name.
Once marked as a favorite, the repository will always appear at the top of the repository list, possibly following the "Recent Repositories" section. 
Importantly, users will have the flexibility to mark multiple repositories as favorites, providing a versatile way to manage and access their preferred repositories.

In addition to allowing users to mark repositories as favorites, we could consider implementing a drag-and-drop functionality. This feature would empower users to create fully custom-ordered lists, providing a more intuitive and personalized repository management experience.

### Proposed solution

The proposed solution aims to enhance GitHub Desktop by introducing a new feature that allows users to mark repositories as favorites. This feature will enable users to easily access their most frequently used repositories by placing them at the top of the repository list, following the "Recent repositories" section.

Implementation Details:

- Favorite Icon: A star icon will be added next to each repository name in the GitHub Desktop interface. Users can click on this star icon to mark a repository as a favorite.

- Favorite Repositories Section: Below the "Recent repositories" section, a new section called "Favorite repositories" will be introduced. This section will display all repositories that the user has marked as favorites.

- Multiple Favorites: Users will have the flexibility to mark multiple repositories as favorites. When a repository is marked as a favorite, it will appear in the "Favorite repositories" section.

- Drag-and-Drop Reordering: To provide users with greater control over the order of their favorite repositories, a drag-and-drop feature will be implemented. Users can rearrange the order of their favorite repositories in the "Favorite repositories" section.

- Persisting Favorites: The list of favorite repositories will be stored locally on the user's machine, ensuring that their favorite repositories remain the same across sessions.

Benefits to GitHub Desktop and Its Users:

- Improved Accessibility: Users will be able to quickly access their most important repositories without scrolling through the entire list.

- Enhanced User Experience: The ability to mark repositories as favorites and reorder them provides a customizable and intuitive user experience.

- Increased Productivity: Users can prioritize repositories that are actively being worked on, leading to increased productivity.

- Consistency Across Sessions: The persistence of favorite repositories ensures that users don't have to repeatedly mark repositories as favorites every time they use GitHub Desktop.

Overall, implementing the ability to mark repositories as favorites in GitHub Desktop will enhance the usability and efficiency of the application, making it more user-friendly and valuable to its users.

**Comment by tidy-dev** [comment]
@eliyahu-kriel Thank you for such a detailed feature request. We are collecting feedback for this feature https://github.com/desktop/desktop/issues/8183. At this time we do not have plans to change the repository list, but we may reconsider again in the future thus, I am going to copy your feedback to that issue.
