### ISSUE TITLE
Allow Pinning of certain branches

### ISSUE THREAD

**Issue by malisancube** [desktop/desktop#17381]
### The feature request

The pinning feature would allow for the user to pin some branches, enabling them to be on the top. This helps making it simpler to navigate between branches that the user is working on at the same time.

### Proposed solution

Enable pinning of branches on the Branch context menu.

**Comment by steveward** [comment]
Thanks for the issue @malisancube, this is being tracked in https://github.com/desktop/desktop/issues/15767 so you can follow along there for updates.
