### ISSUE TITLE
Create a branch dialog blocks new branch creation when upstream does not allow new branches

### ISSUE THREAD

**Issue by aalismo** [desktop/desktop#17382]
### The problem

We have a repo in our enterprise account that has branch protection rules. We cannot create new branches on that repo.

I have forked the repo and cloned my fork in my local. I want to create a new branch, based on a branch from upstream. The "Create a Branch" dialog shows an error and create branch button is disabled.

![CreateABranch](https://github.com/desktop/desktop/assets/39249278/7b37b32d-63f1-4ee6-89e1-5a16508b1691)

I see the following request being made to check for branch rules:

Request URL: https://api.github.com/repos/corpupstream/Repo/rules/branches/test2
Request Method: GET
`Response: 
[
  {
    "type": "deletion",
    "ruleset_source_type": "Repository",
    "ruleset_source": "corpupstream/Repo",
    "ruleset_id": 19388
  },
  {
    "type": "creation",
    "ruleset_source_type": "Repository",
    "ruleset_source": "corpupstream/Repo",
    "ruleset_id": 19388
  },
  {
    "type": "non_fast_forward",
    "ruleset_source_type": "Repository",
    "ruleset_source": "corpupstream/Repo",
    "ruleset_id": 19388
  }
]
`
This check seems to be incorrect. Branch Creation rules in upstream should not stop me from creating a branch on my local clone.

### Release version

3.3.1

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Create a ruleset in an existing repo and under Branch Protections turn on "Restrict creations" option
2. Fork the above repo
3. Clone it to your local using Github Desktop. Choose "I will be using this fork... To contribute to the parent repository" fork behavior.
4. Try to create a branch based off the "main" repo from upstream repo.

**Comment by tidy-dev** [comment]
:wave: @aalismo Thank you for raising this issue! 

Likely this was on oversight on how forks handle repo rules. We are discussing as a team to make sure there isn't an edge case for adhering repo rules when using a fork. But, in general, we agree with your assessment so I am going to mark this as a bug.

**Comment by CyberPunkRules** [comment]
Wow.
