### ISSUE TITLE
Issues with Husky Hooks When Committing via GitHub Desktop on Windows

### ISSUE THREAD

**Issue by ignatremizov** [desktop/desktop#17385]
### The problem

While trying to commit changes to a Vue.js Vite project using GitHub Desktop, I encountered an error related to Husky pre-commit hooks. The error suggests a PATH issue where the `npm` executable could not be found, despite it being properly set up on my system. Committing via the windows command prompt did not produce this error, suggesting an environment or PATH discrepancy within GitHub Desktop's internal environment.

Error encountered: `/bin/bash: C:/Program Files/nodejs/npm: No such file or directory husky - pre-commit hook exited with code 127 (error)`

### Release version

Version 3.3.1 (x64)

### Operating system

Windows 10, version 22H2, OS build 19045.3324

### Steps to reproduce the behavior

1. Have a project with Husky hooks set up and Node.js installed at the default Windows path (C:/Program Files/nodejs/).
2. Make a change in the project and try to commit it using GitHub Desktop.
3. Observe the error related to the Husky pre-commit hook failing to find the npm executable.

### Log files

[2023-09-13.desktop.production.log](https://github.com/desktop/desktop/files/12600879/2023-09-13.desktop.production.log)

### Additional context

The PATH as reported by the error seems to have the correct directories, including the one where Node.js and npm are installed (C:/Program Files/nodejs/). However, it seems GitHub Desktop might not be correctly using or interpreting this PATH when running Git hooks.

**Comment by ignatremizov** [comment]
Ah, I see it is a duplicate report of #12562, #12586, and #17103.

As suggested in [#12586 (comment)](https://github.com/desktop/desktop/issues/12586#issuecomment-1223600474), by prioritizing the `C:\Program Files\Git\bin` directory in the `PATH` environment variable, I resolved the GitHub Desktop commit issue on my Windows system:

1. **Root Cause**: GitHub Desktop seems to be invoking a Unix-like environment under the hood. This environment requires the actual Git binaries found in `C:\Program Files\Git\bin` rather than the Command Prompt-adapted version in `C:\Program Files\Git\cmd`.

2. **Solution**: Adjusted the `PATH` to prioritize `C:\Program Files\Git\bin` over both `C:\Program Files\Git\cmd` and `C:\Windows\system32`. This ensures GitHub Desktop finds and uses the correct Git binary.

3. **Implications**: This adjustment might cause any Command Prompt usage of `git` to directly use the Git binary from the `bin` directory, skipping the `cmd` directory's environment setup. However, the core Git operations remain consistent, and for most users, there likely won't be a noticeable difference when using Git from the Command Prompt.

**Comment by steveward** [comment]
@ignat980 thanks for the issue, and I'm glad to hear you were able to resolve it. Since we have had quite a few previous reports of this I'm going to make a note to write this up in  our [known issues document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md) for future reference until we can better support hooks.

**Comment by TheMikeyRoss** [comment]
> I'm going to make a note to write this up in our [known issues document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md) for future reference until we can better support hooks.

Hi @steveward , any update on this part?

**Comment by TheMikeyRoss** [comment]
I used [SourceTree](https://www.sourcetreeapp.com/) it works smoothly with no issue with husky hooks

**Comment by Fairweather13024** [comment]
> Ah, I see it is a duplicate report of #12562, #12586, and #17103.
> 
> As suggested in [#12586 (comment)](https://github.com/desktop/desktop/issues/12586#issuecomment-1223600474), by prioritizing the `C:\Program Files\Git\bin` directory in the `PATH` environment variable, I resolved the GitHub Desktop commit issue on my Windows system:
> 
> 1. **Root Cause**: GitHub Desktop seems to be invoking a Unix-like environment under the hood. This environment requires the actual Git binaries found in `C:\Program Files\Git\bin` rather than the Command Prompt-adapted version in `C:\Program Files\Git\cmd`.
> 2. **Solution**: Adjusted the `PATH` to prioritize `C:\Program Files\Git\bin` over both `C:\Program Files\Git\cmd` and `C:\Windows\system32`. This ensures GitHub Desktop finds and uses the correct Git binary.
> 3. **Implications**: This adjustment might cause any Command Prompt usage of `git` to directly use the Git binary from the `bin` directory, skipping the `cmd` directory's environment setup. However, the core Git operations remain consistent, and for most users, there likely won't be a noticeable difference when using Git from the Command Prompt.

I moved the Git bin and Git cmd in my system path environment paths as you said above the system 32 path and it worked 🥳

**Comment by zongzi531** [comment]
> Ah, I see it is a duplicate report of #12562, #12586, and #17103.
> 
> As suggested in [#12586 (comment)](https://github.com/desktop/desktop/issues/12586#issuecomment-1223600474), by prioritizing the `C:\Program Files\Git\bin` directory in the `PATH` environment variable, I resolved the GitHub Desktop commit issue on my Windows system:
> 
> 1. **Root Cause**: GitHub Desktop seems to be invoking a Unix-like environment under the hood. This environment requires the actual Git binaries found in `C:\Program Files\Git\bin` rather than the Command Prompt-adapted version in `C:\Program Files\Git\cmd`.
> 2. **Solution**: Adjusted the `PATH` to prioritize `C:\Program Files\Git\bin` over both `C:\Program Files\Git\cmd` and `C:\Windows\system32`. This ensures GitHub Desktop finds and uses the correct Git binary.
> 3. **Implications**: This adjustment might cause any Command Prompt usage of `git` to directly use the Git binary from the `bin` directory, skipping the `cmd` directory's environment setup. However, the core Git operations remain consistent, and for most users, there likely won't be a noticeable difference when using Git from the Command Prompt.

Thanks! It's work for me.

**Comment by Bond-Addict** [comment]
Adding this to my husky pre-commit file worked.

```
#!/bin/sh

# Temporarily add Git Bash to PATH if it's not already in the PATH
if ! command -v bash &> /dev/null
then
    export PATH="$PATH:/c/Program Files/Git/usr/bin"
fi
```

**Comment by dennis-easypost24** [comment]
Here’s a concise reply https://stackdev.space/questions/what-could-be-causing-the-husky-pre-commit-hook-to-fail-on-a-windows-system

**Comment by whats2000** [comment]
> Ah, I see it is a duplicate report of [#12562](https://github.com/desktop/desktop/issues/12562), [#12586](https://github.com/desktop/desktop/issues/12586), and [#17103](https://github.com/desktop/desktop/issues/17103).
> 
> As suggested in [#12586 (comment)](https://github.com/desktop/desktop/issues/12586#issuecomment-1223600474), by prioritizing the `C:\Program Files\Git\bin` directory in the `PATH` environment variable, I resolved the GitHub Desktop commit issue on my Windows system:
> 
> 1. **Root Cause**: GitHub Desktop seems to be invoking a Unix-like environment under the hood. This environment requires the actual Git binaries found in `C:\Program Files\Git\bin` rather than the Command Prompt-adapted version in `C:\Program Files\Git\cmd`.
> 2. **Solution**: Adjusted the `PATH` to prioritize `C:\Program Files\Git\bin` over both `C:\Program Files\Git\cmd` and `C:\Windows\system32`. This ensures GitHub Desktop finds and uses the correct Git binary.
> 3. **Implications**: This adjustment might cause any Command Prompt usage of `git` to directly use the Git binary from the `bin` directory, skipping the `cmd` directory's environment setup. However, the core Git operations remain consistent, and for most users, there likely won't be a noticeable difference when using Git from the Command Prompt.

Well, this actually works for me! For some reason, it needs above the `C:\Windows\system32`.

**Comment by erentaymaz** [comment]
Updating my husky pre-commit file from 

`npx lint-staged
` to `npx.cmd lint-staged
`

worked for me!
