### ISSUE TITLE
Ignored files fail to be removed from Changes list while on an unborn branch

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1739]
After selecting all my files and clicking `Discard all changes`, the files remain in the Changes list and the diff section updates to the "no file selected" graphic. Note my branch is "unborn" which may render this bug as moot.

Additionally, when attempting to go to the Ignored tab in the Repo settings modal, it automatically closes right away.

v0.0.57, OSX 10.11.5

Reproduce:
- Add changed files
- Select all and try to discard

<img width="1126" alt="screen shot 2017-05-24 at 8 19 17 am" src="https://cloud.githubusercontent.com/assets/14828183/26402934/435185ee-405a-11e7-996f-f65b28b16dfc.png">

Expected result: all files are removed.

Logs: nothing specific to files

**Comment by joshaber** [comment]
@tierninho Could you copy and paste that whole exception stack trace in here?

**Comment by tierninho** [comment]
Console kept repeating the same thing:
<img width="1124" alt="screen shot 2017-05-24 at 9 43 18 am" src="https://cloud.githubusercontent.com/assets/14828183/26406154/779af4a6-4065-11e7-99f4-0851f7369c94.png">

**Comment by tierninho** [comment]
cannot reproduce, closing.
