### ISSUE TITLE
Ruleset rejects branches that should pass the rule

### ISSUE THREAD

**Issue by Vince-Law** [desktop/desktop#17392]
### The problem

Assuming I have a repository with the rule for branch naming: `^(minor|feature|bugfix)\/.*(ABC|DEF|GHI)-[0-9]+.*`
when I try creating branch with name feature/ABC-12345-test using Github Desktop there is a validation error saying "Branch name feature/ABC-12345-test" is restricted by repo rules. At the same time it lets me create same branch using Web version.

### Release version

Version 3.3.1 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Setup metadata restriction:
Applies to: Branch name
Requirement: must match a given regex pattern
Matching pattern: `^(minor|feature|bugfix)\/.*(ABC|DEF|GHI)-[0-9]+.*`
2. Try creating branch with name feature/ABC-12345-some-branch-name 
3. Validation error occurs

**Comment by tidy-dev** [comment]
@Vince-Law Thank you for raising this issue. I am able to reproduce, and am actively looking for a fix.

In the mean time the only work arounds I have for you is:
1.  To turn off the rule or allow bypassing of the rule temporarily in the web interface. 
2. Use CLI
3. Download [3.2.9](https://centralreleases.blob.core.windows.net/github-desktop/releases/3.2.9-a98d46c0/GitHubDesktopSetup-x64.exe). It will attempt to auto update tho, and likely will be Monday before a hotfix can be released - May get a beta sooner.

**Comment by tidy-dev** [comment]
While fixing this I found another work around.. which is actually another bug... 
![image](https://github.com/desktop/desktop/assets/75402236/0bddf900-5df7-44b5-a5b1-02b010b666d5)
If you use the above to enter in a branch name and hit create branch, the create branch dialog does not run the repo rules on open 🤦  and will allow you to submit it as long as you don't edit the name.

**Comment by tidy-dev** [comment]
@Vince-Law The fix for this is now released to beta and you can [download beta](https://desktop.github.com/beta/) to get unblocked until the prod release is out. :)

**Comment by tidy-dev** [comment]
@Vince-Law This has been shipped to production. We roll production releases out gradually and therefore you may not see an automatic update right away. You can however [redownload it ](https://desktop.github.com/) or [force a check for updates](https://github.com/desktop/desktop/pull/14883) by pressing `Alt` key while checking for updates in the about dialog to go ahead and get the latest version.
