### ISSUE TITLE
GitHub Desktop untracked files

### ISSUE THREAD

**Issue by cquinto100** [desktop/desktop#17399]
### The problem

In GitHub Desktop, how to configure so that it does not track some files?

### Release version

Version 3.3.1 (x64)

### Operating system

Windows 10

**Comment by sergiou87** [comment]
From within GitHub Desktop, if you have changed files that you wish to ignore, you can right-click on such files and select "Ignore this file".

You can also use the menu Repository -> Repository Settings and edit the .gitignore file from the Ignore Files section of the dialog.

I hope that helps!
