### ISSUE TITLE
Can't push my commit

### ISSUE THREAD

**Issue by Giodosvani** [desktop/desktop#17398]
### The problem

Maybe is a problem at my side, but i still need help

when i try to push my commit, the app says "The remote disconnected. Check your Internet connection and try again.". My connection is working well.
I was going to restart the app, then it says "Instaling update... Do not close Github Desktop while the update is in progress. Closing now may broke your instalation"

Already checked for updates manually, but it causes the same "remote disconnected" error that i said above.

I don't know how to check the instalation progress 

### Release version

Version 3.3.1 (x64)

### Operating system

Windows 10

**Comment by sergiou87** [comment]
We have seen these kind of issues when users have firewall or antivirus installed. Sometimes even when users have wireless connections, and then switching to a wired network fixed the problem. VPNs are another common cause for them.

Could any of those be the reason for your issue?

**Comment by iamnikitakhare** [comment]
You can try this...maybe you facing post buffer
```cmd

``` 

> git config --global http.postBuffer 157286400

**Comment by Giodosvani** [comment]
> We have seen these kind of issues when users have firewall or antivirus installed. Sometimes even when users have wireless connections, and then switching to a wired network fixed the problem. VPNs are another common cause for them.
> 
> Could any of those be the reason for your issue?

I'm using a computer with the default windows antivirus, it has no wireless connection, and i did'nt touch the firewall, at least on the last days. The unique VPN i used was the opera GX vpn, but it already disabled
i already did commits on this project before, it is the portfolio one

**Comment by Giodosvani** [comment]
> You can try this...maybe you facing post buffer
> 
> > git config --global http.postBuffer 157286400

**Comment by Giodosvani** [comment]
> You can try this...maybe you facing post buffer
> 
> > git config --global http.postBuffer 157286400

how, or where i do it? i'm still a beginner with git/github

**Comment by steveward** [comment]
@Giodosvani can you share the log file from GitHub Desktop? That may show some more information about what is happening. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Giodosvani** [comment]
> @Giodosvani can you share the log file from GitHub Desktop? That may show some more information about what is happening. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

@steveward I tried to attach the file, but failed, so here is his content:

#####
2023-09-19T15:18:04.232Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-09-19T15:18:05.466Z - info: [ui] [AppStore] loading 8 repositories from store
2023-09-19T15:18:05.467Z - info: [ui] [AppStore] found account: Giodosvani (Giovani Oliveira)
2023-09-19T15:18:05.645Z - info: [ui] launching: 3.3.1 (Windows 10.0.19045)
2023-09-19T15:18:05.645Z - info: [ui] execPath: 'C:\Users\giodo\AppData\Local\GitHubDesktop\app-3.3.1\GitHubDesktop.exe'
2023-09-19T15:18:06.142Z - info: [ui] Subscribed 'Giodosvani' to Alive channel
2023-09-19T15:18:06.677Z - info: [ui] Stats reported.
2023-09-19T15:18:22.845Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: portfolio - Giodosvani (has token)
2023-09-19T15:18:26.992Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 7 repositories took 1.3s of which 0.0s paused, total 1.3s
2023-09-19T15:18:37.018Z - info: [ui] Executing push: git -c credential.helper= push origin main:main --progress (took 14.156s)
2023-09-19T15:18:37.019Z - error: [ui] `git -c credential.helper= push origin main:main --progress` exited with an unexpected code: 1.
stderr:
Enumerating objects: 38, done.
Counting objects:   2% (1/38)
Counting objects:   5% (2/38)
Counting objects:   7% (3/38)
Counting objects:  10% (4/38)
Counting objects:  13% (5/38)
Counting objects:  15% (6/38)
Counting objects:  18% (7/38)
Counting objects:  21% (8/38)
Counting objects:  23% (9/38)
Counting objects:  26% (10/38)
Counting objects:  28% (11/38)
Counting objects:  31% (12/38)
Counting objects:  34% (13/38)
Counting objects:  36% (14/38)
Counting objects:  39% (15/38)
Counting objects:  42% (16/38)
Counting objects:  44% (17/38)
Counting objects:  47% (18/38)
Counting objects:  50% (19/38)
Counting objects:  52% (20/38)
Counting objects:  55% (21/38)
Counting objects:  57% (22/38)
Counting objects:  60% (23/38)
Counting objects:  63% (24/38)
Counting objects:  65% (25/38)
Counting objects:  68% (26/38)
Counting objects:  71% (27/38)
Counting objects:  73% (28/38)
Counting objects:  76% (29/38)
Counting objects:  78% (30/38)
Counting objects:  81% (31/38)
Counting objects:  84% (32/38)
Counting objects:  86% (33/38)
Counting objects:  89% (34/38)
Counting objects:  92% (35/38)
Counting objects:  94% (36/38)
Counting objects:  97% (37/38)
Counting objects: 100% (38/38)
Counting objects: 100% (38/38), done.
Delta compression using up to 4 threads
Compressing objects:   3% (1/32)
Compressing objects:   6% (2/32)
Compressing objects:   9% (3/32)
Compressing objects:  12% (4/32)
Compressing objects:  15% (5/32)
Compressing objects:  18% (6/32)
Compressing objects:  21% (7/32)
Compressing objects:  25% (8/32)
Compressing objects:  28% (9/32)
Compressing objects:  31% (10/32)
Compressing objects:  34% (11/32)
Compressing objects:  37% (12/32)
Compressing objects:  40% (13/32)
Compressing objects:  43% (14/32)
Compressing objects:  46% (15/32)
Compressing objects:  50% (16/32)
Compressing objects:  53% (17/32)
Compressing objects:  56% (18/32)
Compressing objects:  59% (19/32)
Compressing objects:  62% (20/32)
Compressing objects:  65% (21/32)
Compressing objects:  68% (22/32)
Compressing objects:  71% (23/32)
Compressing objects:  75% (24/32)
Compressing objects:  78% (25/32)
Compressing objects:  81% (26/32)
Compressing objects:  84% (27/32)
Compressing objects:  87% (28/32)
Compressing objects:  90% (29/32)
Compressing objects:  93% (30/32)
Compressing objects:  96% (31/32)
Compressing objects: 100% (32/32)
Compressing objects: 100% (32/32), done.
Writing objects:   2% (1/35)
Writing objects:   5% (2/35)
Writing objects:   8% (3/35)
Writing objects:  11% (4/35)
Writing objects:  14% (5/35)
Writing objects:  17% (6/35)
Writing objects:  20% (7/35)
Writing objects:  22% (8/35)
Writing objects:  25% (9/35)
Writing objects:  28% (10/35)
Writing objects:  31% (11/35)
Writing objects:  34% (12/35)
Writing objects:  37% (13/35)
Writing objects:  40% (14/35)
Writing objects:  42% (15/35)
Writing objects:  45% (16/35)
Writing objects:  48% (17/35)
Writing objects:  51% (18/35)
Writing objects:  57% (20/35)
Writing objects:  60% (21/35)
Writing objects:  62% (22/35)
Writing objects:  65% (23/35)
Writing objects:  71% (25/35)
Writing objects:  74% (26/35)
Writing objects:  77% (27/35)
Writing objects:  80% (28/35)
Writing objects:  82% (29/35)
Writing objects:  85% (30/35)
Writing objects:  88% (31/35)
Writing objects:  91% (32/35)
Writing objects:  94% (33/35)
Writing objects:  97% (34/35)
Writing objects:  97% (34/35), 1.71 MiB | 146.00 KiB/s
error: RPC failed; HTTP 408 curl 22 The requested URL returned error: 408
send-pack: unexpected disconnect while reading sideband packet
Writing objects:  97% (34/35), 88.20 MiB | 7.09 MiB/s 
Writing objects: 100% (35/35), 88.20 MiB | 7.09 MiB/s
Writing objects: 100% (35/35), 187.27 MiB | 14.52 MiB/s, done.
Total 35 (delta 3), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

(The error was parsed as 4: The remote disconnected. Check your Internet connection and try again.)
2023-09-19T15:20:08.206Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: portfolio - Giodosvani (has token)
2023-09-19T15:20:21.399Z - info: [ui] Executing push: git -c credential.helper= push origin main:main --progress (took 13.177s)
2023-09-19T15:20:21.455Z - error: [ui] `git -c credential.helper= push origin main:main --progress` exited with an unexpected code: 1.
stderr:
Enumerating objects: 38, done.
Counting objects:   2% (1/38)
Counting objects:   5% (2/38)
Counting objects:   7% (3/38)
Counting objects:  10% (4/38)
Counting objects:  13% (5/38)
Counting objects:  15% (6/38)
Counting objects:  18% (7/38)
Counting objects:  21% (8/38)
Counting objects:  23% (9/38)
Counting objects:  26% (10/38)
Counting objects:  28% (11/38)
Counting objects:  31% (12/38)
Counting objects:  34% (13/38)
Counting objects:  36% (14/38)
Counting objects:  39% (15/38)
Counting objects:  42% (16/38)
Counting objects:  44% (17/38)
Counting objects:  47% (18/38)
Counting objects:  50% (19/38)
Counting objects:  52% (20/38)
Counting objects:  55% (21/38)
Counting objects:  57% (22/38)
Counting objects:  60% (23/38)
Counting objects:  63% (24/38)
Counting objects:  65% (25/38)
Counting objects:  68% (26/38)
Counting objects:  71% (27/38)
Counting objects:  73% (28/38)
Counting objects:  76% (29/38)
Counting objects:  78% (30/38)
Counting objects:  81% (31/38)
Counting objects:  84% (32/38)
Counting objects:  86% (33/38)
Counting objects:  89% (34/38)
Counting objects:  92% (35/38)
Counting objects:  94% (36/38)
Counting objects:  97% (37/38)
Counting objects: 100% (38/38)
Counting objects: 100% (38/38), done.
Delta compression using up to 4 threads
Compressing objects:   3% (1/32)
Compressing objects:   6% (2/32)
Compressing objects:   9% (3/32)
Compressing objects:  12% (4/32)
Compressing objects:  15% (5/32)
Compressing objects:  18% (6/32)
Compressing objects:  21% (7/32)
Compressing objects:  25% (8/32)
Compressing objects:  28% (9/32)
Compressing objects:  31% (10/32)
Compressing objects:  34% (11/32)
Compressing objects:  37% (12/32)
Compressing objects:  40% (13/32)
Compressing objects:  43% (14/32)
Compressing objects:  46% (15/32)
Compressing objects:  50% (16/32)
Compressing objects:  53% (17/32)
Compressing objects:  56% (18/32)
Compressing objects:  59% (19/32)
Compressing objects:  62% (20/32)
Compressing objects:  65% (21/32)
Compressing objects:  68% (22/32)
Compressing objects:  71% (23/32)
Compressing objects:  75% (24/32)
Compressing objects:  78% (25/32)
Compressing objects:  81% (26/32)
Compressing objects:  84% (27/32)
Compressing objects:  87% (28/32)
Compressing objects:  90% (29/32)
Compressing objects:  93% (30/32)
Compressing objects:  96% (31/32)
Compressing objects: 100% (32/32)
Compressing objects: 100% (32/32), done.
Writing objects:   2% (1/35)
Writing objects:   5% (2/35)
Writing objects:   8% (3/35)
Writing objects:  11% (4/35)
Writing objects:  14% (5/35)
Writing objects:  17% (6/35)
Writing objects:  20% (7/35)
Writing objects:  22% (8/35)
Writing objects:  25% (9/35)
Writing objects:  28% (10/35)
Writing objects:  31% (11/35)
Writing objects:  34% (12/35)
Writing objects:  37% (13/35)
Writing objects:  40% (14/35)
Writing objects:  42% (15/35)
Writing objects:  45% (16/35)
Writing objects:  48% (17/35)
Writing objects:  51% (18/35)
Writing objects:  57% (20/35)
Writing objects:  60% (21/35)
Writing objects:  62% (22/35)
Writing objects:  65% (23/35)
Writing objects:  71% (25/35)
Writing objects:  74% (26/35)
Writing objects:  77% (27/35)
Writing objects:  80% (28/35)
Writing objects:  82% (29/35)
Writing objects:  85% (30/35)
Writing objects:  88% (31/35)
Writing objects:  91% (32/35)
Writing objects:  94% (33/35)
Writing objects:  97% (34/35)
Writing objects:  97% (34/35), 1.71 MiB | 152.00 KiB/s
error: RPC failed; HTTP 408 curl 22 The requested URL returned error: 408
send-pack: unexpected disconnect while reading sideband packet
Writing objects: 100% (35/35), 86.86 MiB | 7.25 MiB/s 
Writing objects: 100% (35/35), 187.27 MiB | 15.04 MiB/s, done.
Total 35 (delta 3), reused 0 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

(The error was parsed as 4: The remote disconnected. Check your Internet connection and try again.)
2023-09-19T19:18:15.681Z - info: [ui] [BranchPruner] Last prune took place 4 hours ago - skipping
2023-09-19T23:18:13.927Z - info: [ui] [BranchPruner] Last prune took place 8 hours ago - skipping

**Comment by sergiou87** [comment]
@Giodosvani you can try @iamnikitakhare 's suggestion of entering
```
git config --global http.postBuffer 157286400
```

either on Windows' command line or, if you have installed Git for Windows, on Git Bash.
