### ISSUE TITLE
Windows installer not working

### ISSUE THREAD

**Issue by badrul1** [desktop/desktop#17391]
### The problem

I have tried both the regular and the .msi installer.
The regular installer fails with the log message:
` SingleGlobalInstance: Failed to grab lockfile, will retry: C:\Users\xxx\AppData\Local\SquirrelTemp\badru\AppData\Local\Temp\.squirrel-lock-02B29704ED5A2DC023B2E8D62C13E22F129D9606: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\xxx\AppData\Local\SquirrelTemp\xxx\AppData\Local\Temp\.squirrel-lock-02B29704ED5A2DC023B2E8D62C13E22F129D9606'.`

The msi file just ends without any erorr messages and without it being installed.

I do not have any antivirus runing that would be blocking it. 

### Release version

GitHubDesktopSetup-x64 v3.3.1

### Operating system

Windows

**Comment by steveward** [comment]
To get some more information about why the installation is failing it would be helpful if you could send over full the log file that the Squirrel installer generates.

`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`

If no log file is being generated there you should be able to find one in the `SquirrelTemp` directory:

`%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

Please send that over as an attachment. Thanks!

**Comment by badrul1** [comment]
@steveward Sure thing - here you go.
[Squirrel-Install.log](https://github.com/desktop/desktop/files/12619707/Squirrel-Install.log)

**Comment by steveward** [comment]
~~Are you running any antivirus or other security software on this machine that could be blocking the installation from completing?~~ Apologies, I missed that you said you weren't running antivirus.

Can you also check to see if there is anything in the Event Viewer that might shed some light on why the installation is failing?

1. Open `Event Viewer`
2. In the left sidebar, expand "Windows Logs" and select "Application"
3. In the right sidebar, select "Filter Current Log..." and check the "Error" event level.

Let me know if you see anything related to GitHub Desktop there.

**Comment by badrul1** [comment]
The only error messages was when I had two installations at the same time and it told me "Product: GitHub Desktop Deployment Tool -- Error 1500. Another installation is in progress. You must complete that installation before continuing this one.".
[win_app_log.csv](https://github.com/desktop/desktop/files/12676205/win_app_log.csv)

There were some "Information" messages which were written around the same time as one of my failed installs - have attached

**Comment by steveward** [comment]
@badrul1 did you try running the regular installer as well to see if that showed anything interesting? Previously we've seen this and it was due to a system issue (https://github.com/desktop/desktop/issues/9415).

A few more things:
- What specific version of Windows are you running? (We've seen users try to install on Windows Server operating systems and hit issues like this, so I just want to confirm that isn't the case.)
- Does the `C:\Users\xxx\AppData\Local\SquirrelTemp\xxx\AppData\Local\Temp` exist if you try and navigate there in File Explorer? if so, can you verify the access permissions are set correctly?
