### ISSUE TITLE
delete account

### ISSUE THREAD

**Issue by KannaLeeTech** [desktop/desktop#17390]
### The problem

I have deleted this account using google search it said it was deleted but is is not deleted on my desktop. I have another account I prefer to use without it being associated with this account on the app desktop. The account I deleted is iamkiannalee@gmail.com

### Release version

mac

### Operating system

macbook

**Comment by steveward** [comment]
@KannaLeeTech this issue tracker is for GitHub Desktop, if you need to delete your GitHub account you can find steps for how to do that [here](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-personal-account/deleting-your-personal-account).
