### ISSUE TITLE
Automatically set up the GPG Key for Verified Commits

### ISSUE THREAD

**Issue by SnowballXueQiu** [desktop/desktop#17401]
### The feature request

I think you can automatically set up the GPG Key for GitHub Desktop, so that when pushing commits, it can get a Verified Commits.

### Proposed solution

- You can add a New blank in GitHub called GitHub Desktop Security. In that page, users can connect  their trust GitHub Desktop to GitHub. Then GitHub automatically sets up the GPG Key. It is no use to show to users or others. It just for the inner communication between GitHub and GitHub Desktop. After setting up, when users push therir commits, they will gain a Verified tag.
- Apart from these, this is not meaning this is not security. All the actions are taken by GitHub, as long as GitHub makes sure this is absulutely security, it just security.
- Addition: this GPG Key can not be used in other place.

<br />

- Thank You! 

### Additional context

![image](https://github.com/desktop/desktop/assets/97330394/737e1727-c810-465e-acf0-41f191bcbbee)

**Comment by sergiou87** [comment]
Hello! We are tracking all GPG signing improvements on GitHub Desktop in this other issue: https://github.com/desktop/desktop/issues/78

I will close this in favor of that one.
