### ISSUE TITLE
 Unable to give workflow scope to Github Desktop #16296 

### ISSUE THREAD

**Issue by linonetwo** [desktop/desktop#17409]
### The problem

Enumerating objects: 38, done.
Counting objects: 100% (34/34), done.
Delta compression using up to 8 threads
Compressing objects: 100% (19/19), done.
Writing objects: 100% (22/22), 24.97 KiB | 4.99 MiB/s, done.
Total 22 (delta 11), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (11/11), completed with 6 local objects.        
To https://github.com/tiddly-gittly/TiddlyWiki-CPL
 ! [remote rejected] master -> master (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/gh-pages.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/tiddly-gittly/TiddlyWiki-CPL'

### Release version

Version 3.3.1 (x64)

### Operating system

MacOS latest

**Comment by sergiou87** [comment]
Could you try signing out and then signing in again from Desktop? Hopefully when you sign back in, it should acquire the right scope for your token 🤞

**Comment by linonetwo** [comment]
I already sigin/signout by using "loging with desktop" 2 times, and problem still happened.

I use web side to edit the file instead.

**Comment by sergiou87** [comment]
@linonetwo  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by linonetwo** [comment]
[2023-09-20.desktop.production.log](https://github.com/desktop/desktop/files/12669314/2023-09-20.desktop.production.log)

Thanks for patience, I just create a new clean log, try commit push, and sign out, re sigin in, and push again

**Comment by sergiou87** [comment]
Thank you! I can see how the app requests signing in with the `workflow` scope:
```
2023-09-20T06:30:33.602Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=390c72d9-d2d6-4b9f-a0e6-58e34044a2eb
```

Could you open https://github.com/settings/connections/applications/de0e3c7e9973e1c4dd77 and check if it has the workflow scope there? You should see something like this:
![2023-09-20 at 08 47](https://github.com/desktop/desktop/assets/1083228/7ab21063-cbaa-4e9d-96b2-3588b676e2fa)

**Comment by linonetwo** [comment]
<img width="1568" alt="截屏2023-09-20 15 54 31" src="https://github.com/desktop/desktop/assets/3746270/d797d7e0-92c3-4fa1-99ea-a25c72628245">

Sure, it is there

**Comment by sergiou87** [comment]
Ok let's try this: could you click on that `Revoke Access` button and then sign out and in again from GitHub Desktop?

I don't see why could this happen :thinking: Are you able to push a workflow file to any other repository from desktop?

**Comment by linonetwo** [comment]
> could you click on that `Revoke Access` button and then sign out and in again from GitHub Desktop?

This doesn't work!

> Are you able to push a workflow file to any other repository from desktop?

Yes, this is strange, I can push workflow modification to https://github.com/tiddly-gittly/tiddlywiki-calendar , but can't push to https://github.com/tiddly-gittly/TiddlyWiki-CPL

Is this related to some repository setting? Anything else I can do?

[2023-09-20.desktop.production.log](https://github.com/desktop/desktop/files/12671962/2023-09-20.desktop.production.log)

**Comment by sergiou87** [comment]
That's the only thing I can think of 🤔 I don't remember if there is such a setting for repos, but I can't see how you would be able to push changes to one repo and not to the other, both under the same org 🤔 

Please check with the repo's admin in case there is anything they set up to limit this.

**Comment by linonetwo** [comment]
Surely I'm the admin of repo and org, and I also try to add my self as admin here

![截屏2023-09-21 18 25 03](https://github.com/desktop/desktop/assets/3746270/ef17b33f-ca1f-4a62-8471-d20158e81254)

And I try revoke PAT and re-login, but not working still...

**Comment by linonetwo** [comment]
The log say `Authentication failed`, maybe it is related to https

```
To https://github.com/tiddly-gittly/TiddlyWiki-CPL
 ! [remote rejected] master -> master (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/gh-pages.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/tiddly-gittly/TiddlyWiki-CPL'

2023-09-21T10:28:00.625Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 75.517s)
2023-09-21T10:28:00.635Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
ssh: connect to host git.light-field.tech port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Settings.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
- ```

**Comment by linonetwo** [comment]
Sorry for the bordering! It was my mistake!

I was trying to check if it is https/ssh issue, and found the repo address was messed up by other programs that will add a PAT to the repo uri, and it forget to clean it up!

<img width="403" alt="截屏2023-09-21 18 30 15" src="https://github.com/desktop/desktop/assets/3746270/52173d18-063b-4317-8dab-d02e6dbaa532">

```
https://linonetwo:ghp_dT4xxxxxx@github.com/tiddly-gittly/TiddlyWiki-CPL
```

After restore it back to https://github.com/tiddly-gittly/TiddlyWiki-CPL , everything works fine again!

**Comment by linonetwo** [comment]
Hope this issue will help someone googled here...

Or maybe you can try add the full repo URL to the log, so this can be easily spot out, when someone rise an issue.

**Comment by sergiou87** [comment]
Ohhh! Nice catch! Thanks for reaching back with the solution ❤️  And I'm glad you got it working! 😄
