### ISSUE TITLE
GitHub Desktop creates a local branch with the same name as an existing branch on the remote (origin) by default 

### ISSUE THREAD

**Issue by SaraAshraf12** [desktop/desktop#17403]
### The problem

I am using GitHub Desktop app, and when opening branch already exist on the remote ,the app creates one with the same name locally, how can I stop that?

### Release version

Version 3.3.1

### Operating system

mac os

**Comment by steveward** [comment]
@SaraAshraf12 thanks for the issue. This is the standard behavior in Git when running a `git checkout` from the command line as well. Are you wanting to be able to customize the local branch name?

**Comment by SaraAshraf12** [comment]
@steveward I just want to open the branch when I am opening it, don't want this duplication

**Comment by steveward** [comment]
Git can't work locally on your machine without using tracking branches that track the remote branches. I'd recommend reading up on how branching works in Git -- this is a helpful section: https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches.

**Comment by SaraAshraf12** [comment]
but this doesn't happen with master
