### ISSUE TITLE
[Bug] Shows conflicts not as resolved

### ISSUE THREAD

**Issue by moxie-coder** [desktop/desktop#17404]
### The problem

There's an issue where conflicts that were solved show up as not solved (as shown in the screenshot provided), and when it does, it sometimes goes back to showing up not being solved. However, the counter showing the conflicts doesn't increase.

### Release version

3.3.1

### Operating system

Windows 11

### Screenshots

![image](https://github.com/desktop/desktop/assets/124418090/1b350e75-9901-4ecc-9298-30c364f50747)

**Comment by sergiou87** [comment]
@MemeHovy  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by moxie-coder** [comment]
> @MemeHovy Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

[2023-09-18.desktop.production.log](https://github.com/desktop/desktop/files/12674318/2023-09-18.desktop.production.log)

Here

**Comment by sergiou87** [comment]
Thank you @MemeHovy !

I can't see anything specific, but I do see this:
```
D:/Hope-Engine-Legacy/.git/index.lock
```

Is it possible you have some other git client (maybe VS Code's?) or somehow a git instance was force-closed while doing some work? I'd suggest to reboot your computer, make sure that `D:/Hope-Engine-Legacy/.git/index.lock` file doesn't exist (or just delete it after rebooting) and then trying again.

If it still doesn't work, please share again new logs so I can take a look!

**Comment by moxie-coder** [comment]
I do happen to use visual studio code with the git plugin, and git in command prompt so one of those might've conflicted with each other, however I can confirm the file does not exist

**Comment by moxie-coder** [comment]
at this point, I've not been able to reproduce this issue again, so I'm gonna close this for now
