### ISSUE TITLE
Enterprise repos are being published automatically

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1741]
Enterprise repos are publishing automatically without the user clicking the publish button. This does not affect dotcom repos.

V0.0.57, OSX 10.11.5

Reproduce:
- Sign in as Enterprise user
- File > New Repo, fill out form
- Click publish button, modal opens
- Switch to Enterprise tab

Expected result: Publish occurs once user clicks "publish repo" button

<img width="482" alt="screen shot 2017-05-24 at 9 58 07 am" src="https://cloud.githubusercontent.com/assets/14828183/26407117/3aa07988-4068-11e7-846d-eb7ac368013f.png">

Console actions:
<img width="1123" alt="screen shot 2017-05-24 at 9 57 02 am" src="https://cloud.githubusercontent.com/assets/14828183/26407152/4ef43e92-4068-11e7-9bcf-808334fd11ba.png">

**Comment by shiftkey** [comment]
This feels like #1724 (but submitting the form) and it should be fixed by #1726. Are you able to reproduce this on `master`?

**Comment by shiftkey** [comment]
Or just `0.5.8` which was just published?

**Comment by tierninho** [comment]
Bug is gone with `0.5.8`, closing 👍
