### ISSUE TITLE
"Merge into current branch" conflict checker out of sync (Race Condition)

### ISSUE THREAD

**Issue by kaster14** [desktop/desktop#17420]
### The problem

When selecting "branch" "merge into current branch" a pop up displays the list of available branches.
By default the top branch is selected and Github desktop starts checking for merge conflicts between the current branch and the default branch.
If another branch is selected before the conflict check on the default branch completes the merge status that gets displayed will be inaccurate and it will be overwritten with the merge status of the default branch instead of showing the merge status of the selected branch. (race condition)

What should happen is that when a branch is selected any current conflict checks should be aborted and then the currently selected branch should have it's merge conflict check started.

### Release version

Version 3.3.1 (x64)

### Operating system

Windows 10 pro, Version 10.0.19045, Build 19045

### Steps to reproduce the behavior

I believe this problem is exacerbated by having my current branch be many commits out of sync with the default branch so this will be more repeatable if you have the following setup:
- Have your default branch be many commits out of sync with your current branch, enough so that it takes more time to complete the merge check than it does for you to click on a non default branch in the "merge into current branch" popup menu.
- Have the branch you are going to have merged into the current branch only be a commit or two different than the currently selected branch so it's merge check completes quickly (or at least quicker than the check against the default branch)

1. Go to the "branch" drop down
2. Select "Merge into current branch"
3. Quickly select a branch (that is not your default branch or active branch) to have merged into your currently selected branch
4. Wait - you will see the conflict status for the branch you selected get displayed, wait some more and it will get overwritten with the conflict status from the default branch. 

### Screenshots

The attached image shows how I have selected the "JF-v0.2.11-base-branch" but the status that is displayed is for my default branch (dev)
 
![Screenshot 2023-09-21 110543](https://github.com/desktop/desktop/assets/13577286/2469ce9c-7e7e-41e6-be35-113c2fcf532d)

**Comment by steveward** [comment]
Thanks for reporting this @kaster14. I was also able to reproduce this with a repository by checking out a branch that was hundreds of commits behind. I'll mark this as a bug for us to look into.

**Comment by kaster14** [comment]
> Thanks for reporting this @kaster14. I was also able to reproduce this with a repository by checking out a branch that was hundreds of commits behind. I'll mark this as a bug for us to look into.

Thanks for looking into it!

**Comment by Kevinarmy132** [comment]
Hello

**Comment by steveward** [comment]
This should be fixed once https://github.com/desktop/desktop/pull/17934 is shipped. ✨
