### ISSUE TITLE
Create a New Branch option is removed from context menu

### ISSUE THREAD

**Issue by ArunKumar-webdev** [desktop/desktop#17422]
### The problem

right clicking on current branch give you option to create a new branch but after the update its removed
![image](https://github.com/desktop/desktop/assets/69241947/092a67b9-4fc4-41ee-8397-98ef7063aa23)

### Release version

Version 3.2.6 (x64)

### Operating system

Windows 11

### Screenshots

![image](https://github.com/desktop/desktop/assets/69241947/07897302-1f3e-400e-b147-05706f636f99)

**Comment by sergiou87** [comment]
As far as I can tell, "Create New Branch" was never an option in that context menu, sorry 😅 [I just looked at the code](https://github.com/desktop/desktop/blob/abf8a692f0467a338641abd85e122302d4b8c0b8/app/src/ui/branches/branch-list-item-context-menu.tsx) and the last change in that file was almost 2 years ago.
