### ISSUE TITLE
Github Installation

### ISSUE THREAD

**Issue by JonOnTheHub** [desktop/desktop#17432]
. i can't install github on my laptop. 

anytime i use the download site (https://desktop.github.com/), it takes me to https://desktop.githubusercontent.com/github-desktop/releases/3.3.3-abf8a692/GitHubDesktopSetup-x64.exe and pulls up the "This site can’t be reacheddesktop.githubusercontent.com took too long to respond." error message. 

i'm on windows 11 .

**Comment by sergiou87** [comment]
It works for me… could you try from a different machine or network?

**Comment by JonOnTheHub** [comment]
different machine? i don't have that, different network, i will and get back to you
