### ISSUE TITLE
Unable to deploy code - blocked 

### ISSUE THREAD

**Issue by lvega77** [desktop/desktop#17437]
In the last few weeks I've been attempting to deploy a code for an assignment unsuccessfully.  I attempted with Netlify, and the deployment continually failed and timed out.  I attempted to create an account with Vercel.com, because other students were having success with it, but Vercel won't give me access because it says that my github account is blocked.  I just created another account with Heroku and it won't connect with my github account stating that remote was closed and authorization was denied.  Every time I get an e-mail from github saying that a new connection was created, but somehow the connections do not work.  I'm going to try things on my end, like pausing some of the enhanced protections I have running on my Anivirus software, but if there is something in the configuration in github that could be causing this.  Can someone please give me instructions on were to look?

**Comment by sergiou87** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
