### ISSUE TITLE
The ability to search through edited files

### ISSUE THREAD

**Issue by DylanDevelops** [desktop/desktop#17433]
### The feature request

Currently, when working with small changes, everything is fine, but sometimes, you imported something like an SDK or something similar where many files are changed, and finding certain files can be a pain in the ass.

### Proposed solution

I suggest putting a search bar below "976 changed files" to make it easier to find specific files to untick.

<img width="246" alt="Screenshot 2023-09-23 at 3 51 10 PM" src="https://github.com/desktop/desktop/assets/48571264/c21afdd3-7288-41c1-87a7-463b03bc7761">

### Additional context

What I am proposing:

<img width="421" alt="Screenshot 2023-09-23 at 4 09 48 PM" src="https://github.com/desktop/desktop/assets/48571264/ef21185c-8ed6-48b1-af85-7c0ca84d11ed">

**Comment by sergiou87** [comment]
Thanks for your suggestion @DylanDevelops ! But we're already tracking it in https://github.com/desktop/desktop/issues/6407 so I'm gonna close this one in favor of that. I'd recommend you to subscribe to that issue so you're notified whenever we make progress on it 😄
