### ISSUE TITLE
Can't open Github Desktop with newly updated version

### ISSUE THREAD

**Issue by blackdow1** [desktop/desktop#17434]
### The problem

I am getting an "Entry Point Not Found" error with the following description; "The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library". I had used the Github Desktop successfully on Sept. 12, so I am assuming that one of the new updates is the cause. Either the Sept. 19 version 3.3.2 or the Sept. 21 version 3.3.3 may be the cause. Is there any way to reinstall a previous version?

### Release version

3.3.3

### Operating system

Windows 8

### Steps to reproduce the behavior

Click to open Github Desktop version 3.3.3 on Windows 8 and get the "Entry Point Not Found" error.

**Comment by sergiou87** [comment]
Windows 8 is not supported anymore by GitHub Desktop. I assume you upgraded from a pretty old version. The latest version compatible with Windows 8 is v3.2.3, and you can download it from this URL: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.2.3-70384014/GitHubDesktopSetup-x64.exe

I'm gonna close this issue assuming that's the solution, but let me know if I'm wrong! 😅

**Comment by MaplePhoenex** [comment]
In case anybody else is still looking, this version works on Windows 8.1

[/MaplePhoenex/Github-Desktop-2.2.4](https://github.com/MaplePhoenex/Github-Desktop-2.2.4)
