### ISSUE TITLE
'Failed to fetch' stuck in refreshing repository

### ISSUE THREAD

**Issue by LisePetculescu** [desktop/desktop#17446]
### The problem

Almost every time i fetch, pull or push a repository on my desktop, it takes forever to 'Refresh repository' and then i'm stuck waiting to be able to push or pull. 

### Release version

Version 3.3.3 (x64)

### Operating system

widows 10 Home

### Steps to reproduce the behavior

1. open github desktop.
2. open a repository, work on it, save changes, and push.
3. OR fetch repository from github
4. get stuck waiting for it to refresh

### Log files

[2023-09-26.desktop.production.log](https://github.com/desktop/desktop/files/12730053/2023-09-26.desktop.production.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/124042840/7024d7f6-b2c6-4536-b85f-48b4f5b24248)

**Comment by steveward** [comment]
@LisePetculescu thanks for the issue. Unfortunately the log file isn't showing much information about why the fetch is failing. Do other network operations, like cloning and pushing work without issue? 

Could you also try manually fetching from the command line to see if any errors occur? Here's what you can run:

`git fetch --progress --prune --recurse-submodules=on-demand origin`

Let me know if that succeeds.

**Comment by LisePetculescu** [comment]
Hey, I'm not sure with cloning, but pushing also triggers the problem. 
I didn't have any issues when I work on my laptop, only with my desktop computer. 

I'm not sure if I'm doing it wrong but nothing happens when I run the command you wrote in git bash?

**Comment by steveward** [comment]
Is there anything running on this machine that could be interfering with Git operations, like security/antivirus software, or a proxy/firewall?

**Comment by LisePetculescu** [comment]
I have no idea 🥲

**Comment by steveward** [comment]
Can you try running these two commands and let me know the output?

```
ping -n 10 github.com
tracert github.com
```

**Comment by LisePetculescu** [comment]
Admin@DESKTOP-9OP2O1J MINGW64 ~/Documents/GitHub/members-results-OOP (main)
$ ping -n 10 github.com

Pinging github.com [140.82.121.4] with 32 bytes of data:
Reply from 140.82.121.4: bytes=32 time=14ms TTL=55
Reply from 140.82.121.4: bytes=32 time=15ms TTL=55
Reply from 140.82.121.4: bytes=32 time=16ms TTL=55
Reply from 140.82.121.4: bytes=32 time=15ms TTL=55
Reply from 140.82.121.4: bytes=32 time=14ms TTL=55
Reply from 140.82.121.4: bytes=32 time=14ms TTL=55
Reply from 140.82.121.4: bytes=32 time=15ms TTL=55
Reply from 140.82.121.4: bytes=32 time=15ms TTL=55
Reply from 140.82.121.4: bytes=32 time=16ms TTL=55
Reply from 140.82.121.4: bytes=32 time=18ms TTL=55

Ping statistics for 140.82.121.4:
    Packets: Sent = 10, Received = 10, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 14ms, Maximum = 18ms, Average = 15ms

Admin@DESKTOP-9OP2O1J MINGW64 ~/Documents/GitHub/members-results-OOP (main)
$ tracert github.com

Tracing route to github.com [140.82.121.4]
over a maximum of 30 hops:

  1     1 ms     1 ms     1 ms  192.168.1.1 
  2     4 ms     3 ms     4 ms  10.0.50.1 
  3     5 ms     7 ms     4 ms  10.0.50.223 
  4     5 ms     5 ms     3 ms  ae20-0.alb2nqp7.dk.ip.tdc.net [87.53.191.250] 
  5    16 ms    14 ms    15 ms  ae0-0.ffm2nqp1.de.ip.tdc.net [83.88.0.126] 
  6    21 ms    14 ms    17 ms  de-cix.fra.github.com [80.81.196.79] 
  7     *        *        *     Request timed out.
  8     *        *        *     Request timed out.
  9    16 ms    15 ms    15 ms  lb-140-82-121-4-fra.github.com [140.82.121.4] 

Trace complete.

**Comment by steveward** [comment]
@LisePetculescu since your network seems to be able to access GitHub without issue my guess is something on your machine/network is specifically blocking GitHub Desktop. Is this a personal machine or work/school? If there is someone you can reach out to that could provide information about any security software that could be running that would be helpful. Unfortunately there isn't much we can do about network issues like this from our end.
