### ISSUE TITLE
Github Desktop on Windows 11 Blurry at Random Times

### ISSUE THREAD

**Issue by hayhut** [desktop/desktop#17444]
### The problem

Github Desktop blurs random parts of the window at differing intensities and at random intervals. Sometimes it is crisp, other times it looks very blurred.

Uninstalling and reinstalling doesn't work, nor does a restart. Only happens on this machine, on both monitors (which have differing resolutions).

### Release version

Version 3.3.3 (x64)

### Operating system

Windows 11 Pro version 22H2 OS Build 22621.2283 Windows Feature Experience Pack 1000.22662.1000.0

### Steps to reproduce the behavior

Opened Github Desktop and clicked around.

### Log files

[2023-09-26.desktop.production.log](https://github.com/desktop/desktop/files/12729844/2023-09-26.desktop.production.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/67342286/1ec8a039-7592-42ca-b878-0efedd656b49)
![image](https://github.com/desktop/desktop/assets/67342286/94d2eb74-4114-4a9b-bb00-0e52945897b7)

### Additional context

Tried Version 3.3.3-beta2 (x64) for fun, didn't fix my issue.

**Comment by steveward** [comment]
Thanks for the report @hayhut. We've had some previous reports of this on macOS (https://github.com/desktop/desktop/issues/9541), but not Windows. A few questions:

1. Any scaling settings on your machine, or multi-monitors?
2. Do you roughly remember when this started happening? (i.e. after a recent update)

One thing you could try would be to disable hardware acceleration to see if that helps at all. Here's how to do that:

1. Open PowerShell
2. Run the command `$env:GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1`

Let us know if that helps at all.

**Comment by hayhut** [comment]
1. No scaling settings, all are at default on my monitors, i.e. 100% scaling in Windows settings. 
2. Wednesday or Thursday of last week. I update my graphics card frequently (Nvidia RTX 2080 update 537.42.), so I may have updated it sometime last week, but I have seen no other blur issues like this in other Electron apps or any graphical issues in general.

Disabling hardware acceleration did not help.

**Comment by hayhut** [comment]
Mystery solved. I opened ClipChamp today and noticed the same issue, and checked my other lesser used Electron apps and saw VS code and Obsidian had the issue. However, I don't have the issue in Slack and Discord.

I did some light research and found [this comment](https://github.com/electron/electron/issues/18344#issuecomment-1368824655) that resolved my issue by disabling FXAA in Nvidia Control Panel and restarting everything. After that, I am now seeing clearly again.
![image](https://github.com/desktop/desktop/assets/67342286/bd019931-bea0-4522-8ffc-71dc30856f99)

This is seemingly a known Electron issue, so I'll close this issue.

**Comment by sirBdone** [comment]
That's amazing! Thank you so, so much! I couldn't be happier with how quickly you responded and of course, with how perfectly you provided the right answer!

**Comment by Aurkcoe** [comment]
I tried disabling hardware acceleration and also set Anti-aliasing FXAA to Off. The problem still persists.

**Comment by mrfhenix** [comment]
windows 11 Home 24H4 (latest updates)
Gpu MX550
screen resolution 
![image](https://github.com/user-attachments/assets/c663bdff-5d42-44b4-9b2a-a902ffd09517)
FSAA OFF was the solution so far ( lattest release GITHUB DESKTOP)
had the Issue
