### ISSUE TITLE
not publishing branch

### ISSUE THREAD

**Issue by hpx07** [desktop/desktop#17455]
### The problem

I have uploaded files to GitHub desktop but when I go to publish my project it shows "The remote disconnected. Check your Internet connection and try again" error  but at same time I am able to send you this report on internet. I don't know what it is but if this have any solution please give or if it is a bug than please fix it.

### Release version

3.3.3.0

### Operating system

Windows 10

### Steps to reproduce the behavior

1. click on current repository.
2. select your repository
3. upload files, enter summary than click "Commit to main".
4. click on publish branch 

### Log files

[2023-09-27.desktop.production.log](https://github.com/desktop/desktop/files/12740969/2023-09-27.desktop.production.log)

### Screenshots

![Screenshot 2023-09-27 220054](https://github.com/desktop/desktop/assets/123539641/ba389adf-02a5-4739-ad74-9312b50efc63)

**Comment by steveward** [comment]
Thanks for the issue @preet96cr. Here's the error I'm seeing:

```
error: RPC failed; HTTP 408 curl 22 The requested URL returned error: 408
Writing objects:  36% (4/11), 4.31 MiB | 100.00 KiB/s
Writing objects:  45% (5/11), 4.31 MiB | 100.00 KiB/s
send-pack: unexpected disconnect while reading sideband packet
```

Some users have had success modifying the http.postbuffer:

```
git config --global http.postBuffer 157286400
```

I would try that to see if it helps with this issue.

**Comment by mikuldeejay** [comment]
Main issue?
