### ISSUE TITLE
Blurry App

### ISSUE THREAD

**Issue by sirBdone** [desktop/desktop#17452]
### The problem

The entire app is showing blurry. 
![image](https://github.com/desktop/desktop/assets/67079134/2ef93607-951e-4eb9-a869-61e6a3fe0192)
![image](https://github.com/desktop/desktop/assets/67079134/253604b0-f355-42e0-8919-64385d2308d7)

### Release version

Version 3.3.3-beta2 x64

### Operating system

Windows 11 

### Steps to reproduce the behavior

1. Just open the app
2. Stare at the text
3. It will slowly go blurry, then clear back up, then go blurry again, etc. 

### Screenshots

![image](https://github.com/desktop/desktop/assets/67079134/f3836688-973d-4629-9518-5509c4de829e)

### Additional context

Every version that I've tried has been blurry. I have an Alienware x17 with an Nvidia 3080 16gb graphics card. Fully updated. It runs great on my work computer, so it feels specific to my machine, but idk what to do differently. Any help would be greatly appreciated.

**Comment by steveward** [comment]
@sirBdone thanks for the report. Another user hit this issue and was able to find a [workaround](https://github.com/desktop/desktop/issues/17444#issuecomment-1736417091) -- could you try that to see if it also works for you?

**Comment by niik** [comment]
Judging by https://github.com/desktop/desktop/issues/17444#issuecomment-1740255065 it appears you were able to solve your issue @sirBdone? I'll close this out but if you're still experiencing it please let us know and we can open this issue back up.
