### ISSUE TITLE
pulling request issue

### ISSUE THREAD

**Issue by ReymerTriana** [desktop/desktop#17457]
### The problem

Can't make a pull request because the button is disabled. This happened in the preview pull request mode.

### Release version

Version 3.3.3 (x64)

### Operating system

windows

### Steps to reproduce the behavior

1. create a commit 
2. select preview pull request
3. select the destiny branch 
4. try to press create pull request button

**Comment by steveward** [comment]
Thanks for the report @ReymerTriana. This has been reported in https://github.com/desktop/desktop/issues/17083, so you can follow along there for updates has we investigate. I'm going to close this out.
