### ISSUE TITLE
Cant install github desktop

### ISSUE THREAD

**Issue by ValenAalvarez** [desktop/desktop#17465]
Hello! I'm going to explain my problem.
I download the git hub desktop from the official website. The problem is when I want to install it. Sometimes the screen that says "GitHub desktop is being installed. It'll be launched once is installed" pops up, and sometimes it doesn't appear. The problem is that it never installs and I can never open it. Nothing appears in the task manager either. I've tried re-downloading it a bunch of times, I've tried the .msi, I've tried deactivating the antivirus and nothing has worked, always the same thing, it doesn't open. I am using the Windows 11 22h2 version. I look forward to possible solutions, thanks!

**Comment by ValenAalvarez** [comment]
In the event viewer it tells me this:
![Captura de pantalla (322)](https://github.com/desktop/desktop/assets/143666723/e7706604-411e-4ec0-8188-3917e9afabe1)

**Comment by ValenAalvarez** [comment]
Squirrel log and event viewer:
[Squirrel-Install.log](https://github.com/desktop/desktop/files/12770699/Squirrel-Install.log)
![Captura de pantalla (322)](https://github.com/desktop/desktop/assets/143666723/941f1fee-394a-4d81-bf32-fee667571f0a)

**Comment by ValenAalvarez** [comment]
Some help?

**Comment by steveward** [comment]
@ValenAalvarez it looks like there is a possible access issue based on the Squirrel logs:

```
[29/09/23 15:47:39] warn: ApplyReleasesImpl: Failed to delete key: C:\Users\valen\AppData\Local\GitHubDesktop\GitHubDesktop.exe: System.UnauthorizedAccessException: No se puede escribir en la clave del Registro
```

Are you aware of any security settings in place on your machine that could be causing this? What antivirus software are you running?

**Comment by ValenAalvarez** [comment]
I don't have any antivirus installed on my PC. And I also tried deactivating Windows Defender

**Comment by steveward** [comment]
Have you had issues installing any other[ Electron applications](https://www.electronjs.org/apps)?

**Comment by ValenAalvarez** [comment]
I downloaded the visual studio code to check and i didn't have any type of problem. Apparently it's just git hub desktop.

**Comment by steveward** [comment]
Can you open an elevated command prompt and run `sfc /scannow` to see if there are any system issues that could be causing this?

**Comment by ValenAalvarez** [comment]
"Windows Resource Protection found no violations
of integrity."

**Comment by ValenAalvarez** [comment]
so there is no solution?:((

**Comment by steveward** [comment]
Unfortunately I'm running out of ideas here -- this seems to be a system-specific issue. Could you try creating a new user account on this machine to test if you are able to install GitHub Desktop there?

**Comment by valenaalvarez02** [comment]
yessss! On another Windows user it let me install it without a problem! Apparently it is a problem with the main user since not even passing the files from one user to another will let me open it. At least I can open github desktop. Thank you so much!!

**Comment by ValenAalvarez** [comment]
Yessss! On another Windows user it let me install it without a problem! Apparently it is a problem with the main user since not even passing the files from one user to another will let me open it. At least I can open github desktop. Thank you so much!!

**Comment by steveward** [comment]
I'm glad to hear that got things working for you! Since we've narrowed down this is a specific issue with a local Windows user account I'm going to close this out.
