### ISSUE TITLE
Add support for Cursor IDE in MacOSX

### ISSUE THREAD

**Issue by bjorntechCarl** [desktop/desktop#17462]
### The feature request

I suggest adding support to the new Cursor IDE (https://www.cursor.so/) so that GitHub projects can be opened in Cursor directly from the Github Desktop Client.

### Proposed solution

Add support for Cursor by creating a new entry in [app/src/lib/editors/darwin.ts](https://github.com/desktop/desktop/blob/development/app/src/lib/editors/darwin.ts).

**Comment by veeeeep** [comment]
Yes please!

**Comment by Santiago-sk** [comment]
And Windows too

**Comment by Raen11** [comment]
Шоб вы без меня делали,лодари!

**Comment by Willaiem** [comment]
Please add for Windows too!
