### ISSUE TITLE
Return key should delete the repo

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1746]
Hitting the return key on a Mac should delete the repo, as it would be the same as hitting the `Yes` button. The default is currently `No`, which is not the expected result.

v0.5.8, OSX 10.11.5

Reproduce:
- try deleting a repo by hitting `return` key when the modal appears

<img width="1121" alt="screen shot 2017-05-24 at 1 10 40 pm" src="https://cloud.githubusercontent.com/assets/14828183/26416058/a04b3c4a-4082-11e7-9c9c-8fa6543545d2.png">

Other modals seems to work fine.

**Comment by joshaber** [comment]
I'd actually go the other way on this and argue that since it's a destructive action, `No` should be the default button. So really it should be the default dark blue.

**Comment by tierninho** [comment]
that works too 👍

**Comment by joshaber** [comment]
I'll close this and open a new issue 👍

**Comment by joshaber** [comment]
Opened https://github.com/desktop/desktop/issues/1751
