### ISSUE TITLE
Error connecting github desktop to github enterprise

### ISSUE THREAD

**Issue by jesuskado** [desktop/desktop#17475]
### The problem

Error connecting github desktop to github enterprise, the error is copy in the imagen.
my account en the enterprise is jkado@gdmseeds.com

### Release version

3.3.3 

### Operating system

windows 10 pro 64 Bits

### Steps to reproduce the behavior

1- go to file
2- select options
3- sing in in to option github enterprise
4- type the url (format https://github.enterprise.com) is posible to error. Version enterprise is the url parameter https://github.com/enterprise
5- click on continue button and this error apear.

### Screenshots

![image](https://github.com/desktop/desktop/assets/19189507/470d5715-0b21-4340-8a82-f7d519e39cd3)

### Additional context

account is enterprise an i have licencisng for EA contract

**Comment by steveward** [comment]
@jesuskado if you're using GitHub Enterprise Cloud you can log in directly through the `github.com` account section. Let me know if that does not get things working!
