### ISSUE TITLE
Urgent Assistance Needed: Lost VB6 Source Code after GitHub Desktop Setup

### ISSUE THREAD

**Issue by cacimboerp** [desktop/desktop#17477]
Dear Git Support Team,

I hope this message finds you well. I am writing to seek urgent assistance in resolving a critical issue I've encountered with GitHub Desktop. Approximately five days ago, I set up GitHub Desktop for version control of my VB6 project, and unfortunately, I have lost my entire source code during the process.

The project is written in Visual Basic 6 (VB6), and it represents a significant amount of work that I cannot afford to lose. Despite my best efforts, I have been unable to recover the source code and am currently at a loss on how to proceed.

Here are some details about the situation:

After setting up GitHub Desktop, I initiated a repository for my VB6 project and performed an initial commit.
At some point during the process, the source code files seem to have been deleted or overwritten, and I can no longer find them in the local directory or in the GitHub repository.
I have checked the repository history and tried various commands in Git, but I have not been able to retrieve the missing code.
I am unable to find any backup copies of the source code on my local machine, and I did not have an external backup of the project.
I am reaching out to your team with the hope that you can provide guidance and support to help me recover the lost source code of my VB6 project. It is crucial to my work, and I am willing to follow any instructions or provide additional information to facilitate the recovery process.

If there are any specific steps or commands that I should execute in GitHub Desktop or Git to recover the lost files, please let me know. I am eager to resolve this issue as soon as possible and get back to working on my project.

I understand the importance of maintaining proper version control and ensuring the security of source code, and I am committed to learning from this experience to prevent such incidents in the future.

Thank you for your prompt attention to this matter, and I look forward to your guidance and assistance in recovering my VB6 source code.

**Comment by steveward** [comment]
@cacimboerp sorry to hear you're having trouble. Could you open the repository in the command line (go to the file menu -> Repository -> `Open in command line`) and run the command `git reflog`?

That should give an overview of what has happened in your repository -- please share that output here.

If you did make an initial commit than the files should be recoverable. You can also try right-clicking on that commit in the `History` tab and selecting `Create branch from commit` to create a new branch off of that commit. That will allow you to verify if your files are present there.

**Comment by cacimboerp** [comment]
C:\Users\carlo\Desktop\Cacimbo Versao>git reflog
fatal: your current branch '8.0.2023.42' does not have any commits yet

**Comment by cacimboerp** [comment]
![2023-10-03 08 14 56 (3)](https://github.com/desktop/desktop/assets/54618351/b65ef0b6-e1b5-46ad-9f97-aec35b06fb0d)
![2023-10-03 08 14 56 (4)](https://github.com/desktop/desktop/assets/54618351/5547eed3-b365-4104-b7db-8c926113b5d2)
![2023-10-03 08 14 56 (5)](https://github.com/desktop/desktop/assets/54618351/18f094b6-82ef-4331-9757-eda18407c281)
![2023-10-03 08 14 56 (6)](https://github.com/desktop/desktop/assets/54618351/9753c6d2-f9ae-438c-bbb2-b8acb027c2ce)
![2023-10-03 08 14 56](https://github.com/desktop/desktop/assets/54618351/3355fd98-e322-488d-b29e-14224bcb3d64)
![2023-10-03 08 14 57](https://github.com/desktop/desktop/assets/54618351/dd4e0bd5-2136-40d4-bb77-786bf7321a45)
![2023-10-03 08 14 55 (2)](https://github.com/desktop/desktop/assets/54618351/f7c15634-580e-4251-80f0-a425743326b5)
![2023-10-03 08 14 55 (3)](https://github.com/desktop/desktop/assets/54618351/f0118951-2a67-4552-9ac8-2716a4ebecc4)
![2023-10-03 08 14 55 (4)](https://github.com/desktop/desktop/assets/54618351/48d89d46-c9eb-4b57-971d-081ef78fe16d)
![2023-10-03 08 14 55 (5)](https://github.com/desktop/desktop/assets/54618351/d30a8d52-eedf-46c2-8926-a8660792550d)
![2023-10-03 08 14 55](https://github.com/desktop/desktop/assets/54618351/a6e131f4-981f-46ae-84f9-1a3b4e72e507)
![2023-10-03 08 14 56 (2)](https://github.com/desktop/desktop/assets/54618351/877c054f-7840-4d16-86b2-bcb01e8fcdb2)

**Comment by cacimboerp** [comment]
0a8b452b47f0ccd7556a6fe73821af7b197735dd 22cc037d8110ba5e5fc8df9025bf0ecc04c1871b Cacimbo <admin@cacimboerp.com> 1642026679 +0100	commit: 2022
22cc037d8110ba5e5fc8df9025bf0ecc04c1871b 22cc037d8110ba5e5fc8df9025bf0ecc04c1871b Cacimbo <admin@cacimboerp.com> 1648337262 +0100	checkout: moving from 8.2021.0.9 to 8.0.2022.12
22cc037d8110ba5e5fc8df9025bf0ecc04c1871b 22cc037d8110ba5e5fc8df9025bf0ecc04c1871b cacimboerp <admin@cacimboerp.com> 1688086521 +0100	checkout: moving from 8.0.2022.12 to 8.0.2023.15
22cc037d8110ba5e5fc8df9025bf0ecc04c1871b 22cc037d8110ba5e5fc8df9025bf0ecc04c1871b cacimboerp <admin@cacimboerp.com> 1691443051 +0100	checkout: moving from 8.0.2023.15 to 8.0.2023.26
22cc037d8110ba5e5fc8df9025bf0ecc04c1871b 22cc037d8110ba5e5fc8df9025bf0ecc04c1871b cacimboerp <admin@cacimboerp.com> 1695843692 +0100	reset: moving to HEAD
22cc037d8110ba5e5fc8df9025bf0ecc04c1871b 22cc037d8110ba5e5fc8df9025bf0ecc04c1871b cacimboerp <admin@cacimboerp.com> 1695843697 +0100	checkout: moving from 8.0.2023.26 to 8.0.2023.42
22cc037d8110ba5e5fc8df9025bf0ecc04c1871b acd196c96c94750089d85d1fb5d104f0700c0266 cacimboerp <admin@cacimboerp.com> 1695861827 +0100	checkout: moving from 8.0.2023.42 to master
acd196c96c94750089d85d1fb5d104f0700c0266 22cc037d8110ba5e5fc8df9025bf0ecc04c1871b cacimboerp <admin@cacimboerp.com> 1695861843 +0100	merge 8.0.2023.42: Fast-forward
22cc037d8110ba5e5fc8df9025bf0ecc04c1871b 22cc037d8110ba5e5fc8df9025bf0ecc04c1871b cacimboerp <admin@cacimboerp.com> 1695861863 +0100	checkout: moving from master to 8.0.2023.42
22cc037d8110ba5e5fc8df9025bf0ecc04c1871b 0a8b452b47f0ccd7556a6fe73821af7b197735dd cacimboerp <admin@cacimboerp.com> 1695890196 +0100	reset: moving to 0a8b452b47f0ccd7556a6fe73821af7b197735dd
0a8b452b47f0ccd7556a6fe73821af7b197735dd 0a8b452b47f0ccd7556a6fe73821af7b197735dd cacimboerp <admin@cacimboerp.com> 1695890493 +0100	reset: moving to HEAD
0a8b452b47f0ccd7556a6fe73821af7b197735dd 22cc037d8110ba5e5fc8df9025bf0ecc04c1871b cacimboerp <admin@cacimboerp.com> 1695890493 +0100	checkout: moving from 8.0.2023.42 to master
22cc037d8110ba5e5fc8df9025bf0ecc04c1871b 0a8b452b47f0ccd7556a6fe73821af7b197735dd cacimboerp <admin@cacimboerp.com> 1695890543 +0100	reset: moving to 0a8b452b47f0ccd7556a6fe73821af7b197735dd
0a8b452b47f0ccd7556a6fe73821af7b197735dd 6c0d3a6917e04f298b4a73b136054bae0e8cea93 cacimboerp <admin@cacimboerp.com> 1695890553 +0100	reset: moving to 6c0d3a6917e04f298b4a73b136054bae0e8cea93
6c0d3a6917e04f298b4a73b136054bae0e8cea93 dbdcf4d256de89e721a2db510e5adc1abbce7e16 cacimboerp <admin@cacimboerp.com> 1695890602 +0100	commit: 2022
dbdcf4d256de89e721a2db510e5adc1abbce7e16 6c0d3a6917e04f298b4a73b136054bae0e8cea93 cacimboerp <admin@cacimboerp.com> 1695897602 +0100	reset: moving to 6c0d3a6917e04f298b4a73b136054bae0e8cea93
6c0d3a6917e04f298b4a73b136054bae0e8cea93 a928a1a2590f3be089d476058f4e1bb4584cbf4e cacimboerp <admin@cacimboerp.com> 1695897653 +0100	commit: 2022
a928a1a2590f3be089d476058f4e1bb4584cbf4e 6c0d3a6917e04f298b4a73b136054bae0e8cea93 cacimboerp <admin@cacimboerp.com> 1695897711 +0100	reset: moving to 6c0d3a6917e04f298b4a73b136054bae0e8cea93
6c0d3a6917e04f298b4a73b136054bae0e8cea93 e3328d20d0b5432f5149da5c91075911cc6844c3 cacimboerp <admin@cacimboerp.com> 1695897718 +0100	reset: moving to e3328d20d0b5432f5149da5c91075911cc6844c3
e3328d20d0b5432f5149da5c91075911cc6844c3 2fe282ef9f5edfdff3ea9619a5d5774416c49816 cacimboerp <admin@cacimboerp.com> 1695897733 +0100	commit: 2022
2fe282ef9f5edfdff3ea9619a5d5774416c49816 0826b922862ea559fe6e171114586f5bac4876b7 cacimboerp <admin@cacimboerp.com> 1695898745 +0100	revert: Revert "2022"
0826b922862ea559fe6e171114586f5bac4876b7 f47c1fb8e8d1f136a77f4d50b25fe289d23ae730 cacimboerp <admin@cacimboerp.com> 1695898761 +0100	revert: Revert "Revert "2022""
f47c1fb8e8d1f136a77f4d50b25fe289d23ae730 6f5a2a5600173d984f9439cdf2d310d28b3ba0d4 cacimboerp <admin@cacimboerp.com> 1695898819 +0100	revert: Revert "Revert "Revert "2022"""
6f5a2a5600173d984f9439cdf2d310d28b3ba0d4 3dbe080e0615f77a285d260b260cc8803421c1fe cacimboerp <admin@cacimboerp.com> 1695898851 +0100	revert: Revert "Revert "Revert "Revert "2022""""
3dbe080e0615f77a285d260b260cc8803421c1fe 26864b6b46a85a05f5899e3af58200df64927797 cacimboerp <admin@cacimboerp.com> 1695898866 +0100	revert: Revert "Revert "Revert "Revert "Revert "2022"""""
26864b6b46a85a05f5899e3af58200df64927797 d43c2ea516949428a91e4a25e4262bb5247a6816 cacimboerp <admin@cacimboerp.com> 1695898889 +0100	revert: Revert "Revert "Revert "Revert "Revert "Revert "2022""""""
d43c2ea516949428a91e4a25e4262bb5247a6816 f9127b661d8019f99562f2e9019875ece8195f0f cacimboerp <admin@cacimboerp.com> 1695898981 +0100	revert: Revert "Revert "Revert "Revert "Revert "Revert "Revert "2022"""""""
f9127b661d8019f99562f2e9019875ece8195f0f 34f257de8b71bee458d2d6fbd768b96bcc587e85 cacimboerp <admin@cacimboerp.com> 1695899000 +0100	revert: Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "2022""""""""
34f257de8b71bee458d2d6fbd768b96bcc587e85 bb25cc1d707f7cb614acdf08505951148b7f770a cacimboerp <admin@cacimboerp.com> 1695899019 +0100	revert: Revert "2022"
bb25cc1d707f7cb614acdf08505951148b7f770a 2170bb481a89c378b2f09b27563a7eee7390cca7 cacimboerp <admin@cacimboerp.com> 1695899345 +0100	revert: Revert "Revert "2022""
2170bb481a89c378b2f09b27563a7eee7390cca7 0a8b452b47f0ccd7556a6fe73821af7b197735dd cacimboerp <admin@cacimboerp.com> 1695899387 +0100	checkout: moving from master to 8.0.2023.42
0a8b452b47f0ccd7556a6fe73821af7b197735dd 22cc037d8110ba5e5fc8df9025bf0ecc04c1871b cacimboerp <admin@cacimboerp.com> 1695899395 +0100	checkout: moving from 8.0.2023.42 to 8.0.2023.26
22cc037d8110ba5e5fc8df9025bf0ecc04c1871b 22cc037d8110ba5e5fc8df9025bf0ecc04c1871b cacimboerp <admin@cacimboerp.com> 1695899419 +0100	checkout: moving from 8.0.2023.26 to 8.0.2023.15
22cc037d8110ba5e5fc8df9025bf0ecc04c1871b 22cc037d8110ba5e5fc8df9025bf0ecc04c1871b cacimboerp <admin@cacimboerp.com> 1695899423 +0100	checkout: moving from 8.0.2023.15 to 8.0.2023.26
22cc037d8110ba5e5fc8df9025bf0ecc04c1871b 0a8b452b47f0ccd7556a6fe73821af7b197735dd cacimboerp <admin@cacimboerp.com> 1695899424 +0100	checkout: moving from 8.0.2023.26 to 8.0.2023.42
0a8b452b47f0ccd7556a6fe73821af7b197735dd 0a8b452b47f0ccd7556a6fe73821af7b197735dd cacimboerp <admin@cacimboerp.com> 1696270676 +0100	reset: moving to HEAD
0a8b452b47f0ccd7556a6fe73821af7b197735dd 22cc037d8110ba5e5fc8df9025bf0ecc04c1871b cacimboerp <admin@cacimboerp.com> 1696270678 +0100	checkout: moving from 8.0.2023.42 to 8.0.2023.26
22cc037d8110ba5e5fc8df9025bf0ecc04c1871b 0a8b452b47f0ccd7556a6fe73821af7b197735dd cacimboerp <admin@cacimboerp.com> 1696272710 +0100	checkout: moving from 8.0.2023.26 to 8.0.2023.42
0a8b452b47f0ccd7556a6fe73821af7b197735dd 22cc037d8110ba5e5fc8df9025bf0ecc04c1871b cacimboerp <admin@cacimboerp.com> 1696272780 +0100	checkout: moving from 8.0.2023.42 to 8.0.2023.26
22cc037d8110ba5e5fc8df9025bf0ecc04c1871b 0a8b452b47f0ccd7556a6fe73821af7b197735dd cacimboerp <admin@cacimboerp.com> 1696272814 +0100	checkout: moving from 8.0.2023.26 to 8.0.2023.42
0a8b452b47f0ccd7556a6fe73821af7b197735dd 0a8b452b47f0ccd7556a6fe73821af7b197735dd cacimboerp <admin@cacimboerp.com> 1696281428 +0100	reset: moving to HEAD
0a8b452b47f0ccd7556a6fe73821af7b197735dd 22cc037d8110ba5e5fc8df9025bf0ecc04c1871b cacimboerp <admin@cacimboerp.com> 1696281434 +0100	checkout: moving from 8.0.2023.42 to 8.0.2023.26
22cc037d8110ba5e5fc8df9025bf0ecc04c1871b 8bdcf734687ca360c67e22ec8043a76556a36f4a cacimboerp <admin@cacimboerp.com> 1696284153 +0100	revert: Revert "2022"
8bdcf734687ca360c67e22ec8043a76556a36f4a d801aeed75f768a3204c5fa74c25c98feeb37b6f cacimboerp <admin@cacimboerp.com> 1696284160 +0100	revert: Revert "Revert "2022""
d801aeed75f768a3204c5fa74c25c98feeb37b6f aab62dc28194d006849b449a17eb88d7c5d7b5a0 cacimboerp <admin@cacimboerp.com> 1696284165 +0100	revert: Revert "Revert "Revert "2022"""
aab62dc28194d006849b449a17eb88d7c5d7b5a0 b0b53194bdc2393fb8d84c5dbd484a958df969c3 cacimboerp <admin@cacimboerp.com> 1696284180 +0100	revert: Revert "comparticipacoes backoffice"
b0b53194bdc2393fb8d84c5dbd484a958df969c3 116a545d72b94a68aca4461b4052f32af6ac4d57 cacimboerp <admin@cacimboerp.com> 1696284206 +0100	revert: Revert "Merge branch 'master' into 8.0.2020.150"
116a545d72b94a68aca4461b4052f32af6ac4d57 196fad45fd9c379596621879940820d8859b814b cacimboerp <admin@cacimboerp.com> 1696284232 +0100	revert: Revert "1 - Adicionado bloqueio de venda para artigos bloqueados no inventário"
196fad45fd9c379596621879940820d8859b814b 0a8b452b47f0ccd7556a6fe73821af7b197735dd cacimboerp <admin@cacimboerp.com> 1696284263 +0100	checkout: moving from 8.0.2023.26 to 8.0.2023.42
0a8b452b47f0ccd7556a6fe73821af7b197735dd 0a8b452b47f0ccd7556a6fe73821af7b197735dd cacimboerp <admin@cacimboerp.com> 1696284316 +0100	reset: moving to 0a8b452b47f0ccd7556a6fe73821af7b197735dd
0a8b452b47f0ccd7556a6fe73821af7b197735dd 196fad45fd9c379596621879940820d8859b814b cacimboerp <admin@cacimboerp.com> 1696284316 +0100	checkout: moving from 8.0.2023.42 to 8.0.2023.26
196fad45fd9c379596621879940820d8859b814b 0a8b452b47f0ccd7556a6fe73821af7b197735dd cacimboerp <admin@cacimboerp.com> 1696284375 +0100	checkout: moving from 8.0.2023.26 to 8.0.2023.42
0a8b452b47f0ccd7556a6fe73821af7b197735dd 6c0d3a6917e04f298b4a73b136054bae0e8cea93 cacimboerp <admin@cacimboerp.com> 1696284393 +0100	reset: moving to 6c0d3a6917e04f298b4a73b136054bae0e8cea93
6c0d3a6917e04f298b4a73b136054bae0e8cea93 e3328d20d0b5432f5149da5c91075911cc6844c3 cacimboerp <admin@cacimboerp.com> 1696284400 +0100	reset: moving to e3328d20d0b5432f5149da5c91075911cc6844c3
e3328d20d0b5432f5149da5c91075911cc6844c3 0db9f8a505f52c4419f043b79cdcffc93d79c476 cacimboerp <admin@cacimboerp.com> 1696284409 +0100	reset: moving to 0db9f8a505f52c4419f043b79cdcffc93d79c476
0db9f8a505f52c4419f043b79cdcffc93d79c476 0000000000000000000000000000000000000000 cacimboerp <admin@cacimboerp.com> 1696284419 +0100	Reverting first commit
0000000000000000000000000000000000000000 79af031c274f358652dceeb6c05a64299cb5099e cacimboerp <admin@cacimboerp.com> 1696316692 +0100	commit (initial): recover 8.0.2023.42
79af031c274f358652dceeb6c05a64299cb5099e 79af031c274f358652dceeb6c05a64299cb5099e cacimboerp <admin@cacimboerp.com> 1696316913 +0100	checkout: moving from 8.0.2023.42 to recover_from_42
79af031c274f358652dceeb6c05a64299cb5099e 79af031c274f358652dceeb6c05a64299cb5099e cacimboerp <admin@cacimboerp.com> 1696317934 +0100	checkout: moving from recover_from_42 to 8.0.2023.42
79af031c274f358652dceeb6c05a64299cb5099e 79af031c274f358652dceeb6c05a64299cb5099e cacimboerp <admin@cacimboerp.com> 1696319243 +0100	checkout: moving from 8.0.2023.42 to recover_from_42
79af031c274f358652dceeb6c05a64299cb5099e 79af031c274f358652dceeb6c05a64299cb5099e cacimboerp <admin@cacimboerp.com> 1696319253 +0100	checkout: moving from recover_from_42 to 8.0.2023.42
79af031c274f358652dceeb6c05a64299cb5099e 79af031c274f358652dceeb6c05a64299cb5099e cacimboerp <admin@cacimboerp.com> 1696319259 +0100	checkout: moving from 8.0.2023.42 to recover_from_42
79af031c274f358652dceeb6c05a64299cb5099e 2170bb481a89c378b2f09b27563a7eee7390cca7 cacimboerp <admin@cacimboerp.com> 1696319619 +0100	checkout: moving from recover_from_42 to master

**Comment by steveward** [comment]
I see a "reverting first commit" line -- that looks like a potential cause? I see a number of reverts so it's difficult to discern what specifically may have happened. Were you able to try creating a new branch off of a previous commit? We can also use the SHAs in the reflog output to recover your changes.

**Comment by cacimboerp** [comment]
I want to express my sincere gratitude to the entire team for the incredible support I received. By reading a bit more and with the help of the `git reflog` command, I was able to recover the lost data. Sometimes, it's in challenging situations that we learn and grow the most. Once again, thank you for always being ready to assist. It may not seem like it, but this assistance was truly invaluable. I'm now implementing changes in a more correct and secure manner. Together, we're unstoppable! 🙌💻 #AmazingTeam #Gratitude #LearningExperience
