### ISSUE TITLE
Multiple Github Accounts

### ISSUE THREAD

**Issue by jgascoignetaylor-godaddy** [desktop/desktop#17474]
### The feature request

The ability to use more than one account for github.com. 

### Proposed solution

Allow the abilty to sign into multiple accounts from `Settings=>Accounts` (not just github.com and enterprise).  

Then when you'd be able to select the account when you're choosing a respository in Github desktop.

### Additional context

I sometimes like to work on opensource during working hours and sometimes I like to not show my company user. Currently I have to sign out and in which is a pain, having the option would make things a lot simpler. 

Edit: Currently I use the command line and I do it privately as I've had experience in the past where one a repo community sees companyx and expects more commitment (very few and far between but it's not unheard of).

**Comment by steveward** [comment]
Thanks for the feedback @jgascoignetaylor-godaddy, you can follow along in https://github.com/desktop/desktop/issues/3707 for updates about this feature.
