### ISSUE TITLE
Haven't been able to make time to get back to this. Going to close for now, I will reopen when I get a chance to revisit

### ISSUE THREAD

**Issue by Mistiterane** [desktop/desktop#17470]
Haven't been able to make time to get back to this. Going to close for now, I will reopen when I get a chance to revisit

_Originally posted by @tidy-dev in https://github.com/desktop/desktop/issues/15391#issuecomment-1424300907_

**Comment by mikuldeejay** [comment]
Try again

**Comment by Mistiterane** [comment]
> ```
>           Haven't been able to make time to get back to this. Going to close for now, I will reopen when I get a chance to revisit
> ```
> 
> _İlk olarak tarafından gönderildi@tidy-dev# 15391'de [(yorum)](https://github.com/desktop/desktop/pull/15391#issuecomment-1424300907)_

open adreses
