### ISSUE TITLE
Reverse the button colors on the certain modals

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1748]
Reverse the button colors and default actions on the Discard file confirmation modal to follow the Mac guidelines.

<img width="431" alt="screen shot 2017-05-24 at 1 44 23 pm" src="https://cloud.githubusercontent.com/assets/14828183/26417465/4636894e-4087-11e7-9f1c-bc250a7ee078.png">

<img width="442" alt="screen shot 2017-05-24 at 1 36 26 pm" src="https://cloud.githubusercontent.com/assets/14828183/26417126/3b858032-4086-11e7-968e-9a61d6cd03d1.png">

v 0.5.8, OSX

**Comment by joshaber** [comment]
Nope, this is right 😄 Because it's a destructive action, the Cancel button should be the default.
