### ISSUE TITLE
Select all does not work in commit message field

### ISSUE THREAD

**Issue by gingerbeardman** [desktop/desktop#17487]
### The problem

Select All system edit function does not work in the commit message field.

This is annoying hen you want to change that message to something else entirely, as you have t backspace to delete it rather than selecting all and retyping.

### Release version

3.3.3

### Operating system

macOS 12.7

### Steps to reproduce the behavior

1. enter some text in commit message
2. press the system keyboard shortcut for "select all"
3. notice nothing happens

### Screenshots

![Screen shot 2023-10-03 at 21 38 28](https://github.com/desktop/desktop/assets/49612/58ed0ab9-545b-4322-8013-50b3e7a383ad)

### Additional context

Workaround
- use menu item Edit > Select All 
- this works

**Comment by steveward** [comment]
Thanks for reporting this @gingerbeardman. I was unable to reproduce this on macOS 13.6. Just to confirm, is this the behavior you're referring to?

https://github.com/desktop/desktop/assets/721500/e2988ae5-5582-46f8-8490-a3c4cc07e1d9

**Comment by gingerbeardman** [comment]
That is the behaviour! 

It simply didn't do it. 

I've just reinstalled and it's now working. Very odd.
