### ISSUE TITLE
[IDE] RustRover IDE Support

### ISSUE THREAD

**Issue by SnowballXueQiu** [desktop/desktop#17480]
### The feature request

Recently, a new IDE from Jet Brains was launched called RustRover, and I hope that Git Desktop can support this compiler.

### Proposed solution

Just recognize [RustRover](https://www.jetbrains.com/rust/) like other ides

### Additional context

![image](https://github.com/desktop/desktop/assets/97330394/55f3a4ea-4859-42fe-9bf8-ef8b13f20c7d)

**Comment by steveward** [comment]
GitHub Desktop now provides support for [adding custom editors](https://docs.github.com/en/desktop/configuring-and-customizing-github-desktop/configuring-a-default-editor-in-github-desktop?platform=windows#configuring-a-custom-editor), so you can add RustRover by following the steps in that linked help article. I'm going to close this out.
