### ISSUE TITLE
No syntax highlight for .cc files (c++)

### ISSUE THREAD

**Issue by Andrej730** [desktop/desktop#17503]
### The problem

Should be self-descriptive. Not sure if I'm missing something.
![image](https://github.com/desktop/desktop/assets/9417531/b1a4fa18-e0f6-41d7-8818-49251374d562)

### Release version

Version 3.3.4-beta1 (x64)

### Operating system

Windows 11

**Comment by steveward** [comment]
Thanks for the issue @Andrej730. I was able to reproduce this with the `.cc` extension, but with the `.cpp` extension syntax highlighting works as expected.

**Comment by DylanDevelops** [comment]
I can try to work on this issue. @steveward this is my first time contributing to GitHub Desktop. Would you mind pointing me in the direction of where I find the syntax highlighting code?

**Comment by DylanDevelops** [comment]
Hopefully, this issue has been fixed! Feel free to take a look at the attached pull request.

**Comment by Andrej730** [comment]
Thanks for the fix for .cc files.
Just noticed there is a similar issue about the .hh files
![image](https://github.com/desktop/desktop/assets/9417531/cd7bb681-47bb-4db3-9762-c4b7919fc278)

@steveward should I open a new issue?

**Comment by DylanDevelops** [comment]
@Andrej730 If this is something we want to fix, maybe we should list all file extensions that aren't currently supported and then implement them all in one big pull request. Let me know because it's really easy to add syntax highlighting to new file extensions.

**Comment by Andrej730** [comment]
@DylanDevelops 
Sure, that makes sense. 
Not sure what other file extensions are missing but tested and found a few more: makefile, .bat, .cmake, .cmd, .cxx, .hxx, .xsd.

**Comment by sergiou87** [comment]
👋 

If you submit a PR to fix this issues, please also submit one to desktop/highlighter-tests just like I did in https://github.com/desktop/highlighter-tests/pull/58 with sample files that we can use to test your fix.

Thank you!

**Comment by DylanDevelops** [comment]
I created two pull requests. Please let me know if I implemented any of these incorrectly.

Main Pull Request: https://github.com/desktop/desktop/pull/17651
Highlighting Tests: https://github.com/desktop/highlighter-tests/pull/59
