### ISSUE TITLE
The Create Pull Request button is always greyed out

### ISSUE THREAD

**Issue by cfrupp** [desktop/desktop#17502]
### The problem

In GitHub desktop, the Create Pull Request button is always greyed out. This has been true ever since I installed it in June 2023.

I tried the workaround of selecting Create Pull Request (or Preview Pull Request) from the drop-down, but the button is still greyed out.
 
This button does work correctly for most of my teammates (all using the same Desktop version, working in the same repos)
 
Incidentally, the View on GitHub button is also greyed out and unresponsive. Ctrl-shift-G has no effect. 

### Release version

3.3.3 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Launch GitHub Desktop
2. Make sure I'm not in the main branch
3. Make sure all changes are committed and pushed
4. Hover over Create Pull Request button. It's greyed out and unresponsive.

### Screenshots

<img width="566" alt="image" src="https://github.com/desktop/desktop/assets/109383744/c6e40dfe-1bab-4cca-ba07-926d3c0d78b1">

**Comment by steveward** [comment]
Thanks for the report @cfrupp. Since the `View on GitHub` button is also disabled it sounds like there is a caching bug that's causing the app to think the repository isn't published on GitHub. Are you seeing this issue in multiple repositories?

**Comment by cfrupp** [comment]
Hi Steve,
Yes, it seems to apply to all the repos in our organization (at least all the repos I’ve looked at).
C.

**Comment by rstolley** [comment]
Adding to this since I work with @cfrupp. We tried to uninstall and reinstall GitHub Desktop with them and other co-workers and the problem wasn't resolved.

We also tried logging in and out of GitHub.

Is there anything else we should try?

**Comment by steveward** [comment]
You can try clearing out the locally cached data, which a fresh install doesn't do. Here's how to 'reset' the app:

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop

You will need to log in and add your repositories again, which can be done quickly in bulk by drag-and-drop.

**Comment by steveward** [comment]
Previous reports of this: https://github.com/desktop/desktop/issues/17083, https://github.com/desktop/desktop/issues/16368

**Comment by rstolley** [comment]
That worked for @cfrupp and me! Thank you!

![image](https://github.com/desktop/desktop/assets/91505556/15357be3-502b-4abc-bfb9-80802c5fb24a)

**Comment by steveward** [comment]
Great, glad to hear that got things working!
