### ISSUE TITLE
does not download

### ISSUE THREAD

**Issue by Memchuk** [desktop/desktop#17510]
### The problem

at startup, it gives an error related to the lack of access, running as an administrator leads to a request not to do so

### Release version

3.3.4-beta2

### Operating system

Windows 11

### Steps to reproduce the behavior

at startup GitHubDesktopSetup-x64.exe
.msi just crashes.

### Log files

[Squirrel-Install.log](https://github.com/desktop/desktop/files/12830299/Squirrel-Install.log)
[SquirrelSetup.log](https://github.com/desktop/desktop/files/12830300/SquirrelSetup.log)

### Screenshots

![Снимок экрана 2023-10-06 135953](https://github.com/desktop/desktop/assets/121396162/5d28fe88-2561-4085-b423-9e03a5422606)

### Additional context

half a year ago, everything worked, reinstalled Windows, does not pump.

**Comment by steveward** [comment]
@Memchuk thanks for the issue. Are there any restrictions on this machine that could be causing this? Are you running any antivirus or other security software that could be interfering with the installation?

**Comment by Memchuk** [comment]
> @Memchuk спасибо за проблему. Существуют ли какие-либо ограничения на этом компьютере, которые могли быть причиной этого? Используете ли вы какой-либо антивирус или другое программное обеспечение безопасности, которое могло бы помешать установке?

perhaps this is a consequence of the virus software, but I could not solve the problem on my own, although now everything else is working stably.

**Comment by Memchuk** [comment]
It's decided.
Apparently, due to the impact of malware, the file system was damaged. 
Solution: Create a new local account for windows. (such a proposal was born due to the fact that all applications showed an error in appdata and temp)
