### ISSUE TITLE
my upload speeds are no longer viable

### ISSUE THREAD

**Issue by Apollo428** [desktop/desktop#17517]
### The problem

so for the past 2 years i have not had any issues with my upload speeds into github. but idk whats happened in the past few days my upload speeds will not go above 200 kib/s. everywhere else uploads and downloads are fine. from youtube to google drive. everything uploads with good speed. i dont know what to do to fix this. i have restarted my internet router, restarted the application, changed the upload size and restarted my pc multiple times. i have no metered connections at all. Upload usually times out after 4 hours. 

hopefully someone here knows what to do. 

### Release version

Version 3.3.3

### Operating system

Windows 10

### Screenshots

![image](https://github.com/desktop/desktop/assets/99304390/fdcf252b-9c4b-4a68-9d9a-90722317ecf4)

**Comment by 01883320008** [comment]
jakariyahossn6@gmail.com

**Comment by 01883320008** [comment]
https://www.dictionary.com/games/quizzes/wotd-quiz-week-of-september-25-2023

**Comment by 01883320008** [comment]
https://www.dictionary.com/games/quizzes/wotd-quiz-week-of-september-25-2023

**Comment by 01883320008** [comment]
jakariyahossn6@gmail.com

**Comment by 01883320008** [comment]
01883320008

**Comment by steveward** [comment]
@Apollo428 thanks for the issue. Unfortunately there isn't much we can do about upload speeds from our end. If you are having issues pushing a set of changes you can try using the command line to push a subset of commits by using the following command:

`git push origin commit-SHA:branch`

For example, if you have three commits A (4d3bf9) - B (e55b5f) - C (c109e0) and wanted to push A and B to your `main` branch you would run this command:

`git push origin e55b5f:main`

You could also try switching to using SSH to see if you have better success. See [this guide](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) for setting up a new SSH key.

You will also need to change the URL of your repository to use SSH. You can do this in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. You will want the URL to look like `git@github.com:<user>/<repo>.git`. 

I would also recommend going to https://github-debug.com/ and then sharing the output with [GitHub Support](https://support.github.com/) to see if they can assist. I'm going to close this out as this is a connection problem and not a specific issue with GitHub Desktop, but let me know if you have any further questions.
