### ISSUE TITLE
Website giving error 404 whole time even tough my actions are all okay 

### ISSUE THREAD

**Issue by Kenjidef33** [desktop/desktop#17515]
### The feature request

I can't open my website anymore and i don't know how to fix that i always get a 404 error code but all my pages deployments are green 

how can i fix this beceause this is becoming a real pain in my ass 

### Proposed solution

By giving tips how to fix error on pages so that my website can be fixed 

### Additional context

I have nothing else to say except im feeling hopeless and i want this problem to be fixed fast

**Comment by steveward** [comment]
@Kenjidef33 this issue tracker is for GitHub Desktop, I would recommend reaching out to [GitHub Support](https://support.github.com/) for assistance.
