### ISSUE TITLE
Import legacy Mac app's configuration

### ISSUE THREAD

**Issue by benguild** [desktop/desktop#1752]
Is there a plan to import the configuration of the legacy Mac desktop client into the new one? I downloaded the new Electron-based beta... but logged out in it because none of my stuff was there. (downloaded the old version instead)

Would be great to be prompted in the new one when it's ready to migrate all of my stuff even though I already opened it once. Digging the new icon for it!

**Comment by joshaber** [comment]
Thanks @benguild! We're already tracking this in #186.

**Comment by gingerbeardman** [comment]
Which is closed with no resolution @joshaber
