### ISSUE TITLE
Hangs when verifying 2FA code on Linux with GitHub Enterprise

### ISSUE THREAD

**Issue by kleinen** [desktop/desktop#1753]
### Description

Hangs when verifying 2FA code on Linux with GitHub Enterprise

### Version

**GitHub Desktop version:** 0.5.4-alpha2-25 from https://github.com/gengjiawen/desktop/releases
**OS version:** Ubuntu 14.04.1  (kernel: 3.19.0-80-generic) running the MATE window manager
* GitHub Enterprise version:** 2.9

### Steps to Reproduce

1. Install debian into environment
1. Open terminal window and run 'desktop'.  GitHub Desktop GUI will open.
1. Sign into Github Enterprise
![image](https://cloud.githubusercontent.com/assets/5710666/26420223/9be12ffc-4087-11e7-84ae-679c18720beb.png)

1. Enter server url, and then credentials.
![image](https://cloud.githubusercontent.com/assets/5710666/26420254/ad66de02-4087-11e7-97c9-53c2c4504ef0.png)
![image](https://cloud.githubusercontent.com/assets/5710666/26420277/bddbd2d8-4087-11e7-961e-c2da7bb3d65a.png)

1. Enter 2FA code and then press verify
![image](https://cloud.githubusercontent.com/assets/5710666/26420537/76609d02-4088-11e7-9106-73353e564af7.png)

1. Verify button starts doing its spinning action, but the screen never changes to being logged in.  Rest of GUI is still responsive, but also reflective of not being logged in.

**Expected behaviour:** To get logged in as normal

**Actual behaviour:** I get hung up at the verify screen and never get past it.

**Reproduces how often:** 100% (tried 10 times, all 10 failed)

### Logs
I am not able to find any logs from Github Desktop other than what is being output to standard out (console)

#### Console Output
ATTENTION: default value of option force_s3tc_enable overridden by environment.
cat: standard output: Bad file descriptor

**Comment by shiftkey** [comment]
@kleinen my initial gut feeling on this is that `app.setAsDefaultProtocolClient` is specific to [macOS and Windows only](https://electron.atom.io/docs/api/app/#appsetasdefaultprotocolclientprotocol-path-args-macos-windows), and while we [do set this for all platforms](https://github.com/desktop/desktop/blob/0897141f8f455c9eb76d8b8263073fdb8a0529c9/app/src/main-process/main.ts#L150) the actual code for this is [a no-op on Linux](https://github.com/electron/electron/blob/964b210ce02cb67e883e03a41efdadc3d3a558e5/atom/browser/browser_linux.cc#L41-L44). Here's the [Windows](https://github.com/electron/electron/blob/964b210ce02cb67e883e03a41efdadc3d3a558e5/atom/browser/browser_win.cc#L191) implementation to contrast. That would explain why nothing is happening.

Are you able to "Open in Desktop" from the browser? Maybe if there's a way to set this manually as a workaround we can confirm the authentication flow is working. But that doesn't address the lack of protocol handler support.

cc @desktop/electron for thoughts/feels on making `app.setAsDefaultProtocolClient` work on all platforms

**Comment by kleinen** [comment]
> Alpha works on Ubuntu 16.04.2, even with MFA

@hron84 with Github Enterprise 2.9?  Figured I would move this thread to the issue I was requested to create for this.

**Comment by hron84** [comment]
@kleinen No, I tried MFA only with GitHub.com and it works with that perfectly. With GHE, I have no experience nor have any system to try it out. If someone can provide me a sample access, I could try it out.

**Comment by kleinen** [comment]
Sadly, the system I have at my disposal is not available outside of my company's firewall.  If anyone working on this project has one that we can use to test, it would be most appreciated.

**Comment by kleinen** [comment]
@shiftkey To answer your question about "can I open in desktop from a browser".  I don't think so.  When I open Chrome on Ubuntu, I don't get the "Open in Browser" link.  But when I do the same in Chrome on Win10 (on a system where Github Desktop is installed) I get the "Open in Desktop" link right beside the "Download ZIP" link.

**Comment by kleinen** [comment]
Anyone from @desktop/electron have any opinions on the linux platform support, maybe specifically for `app.setAsDefaultProtocolClient`?

**Comment by shiftkey** [comment]
@kleinen it looks like the way out of this is a bit different, and can't be done at runtime as per https://github.com/electron/electron/issues/4857#issuecomment-201124281

**Comment by shiftkey** [comment]
> When I open Chrome on Ubuntu, I don't get the "Open in Browser" link. 

This is probably because we have some server-side checks on GitHub that you have installed Desktop before we show that button, and as we only supported Mac and Windows apps we don't show that button for other OSes.

**Comment by kleinen** [comment]
Digging into some of the github issues, it seems chromium has this working:  https://src.chromium.org/viewvc/chrome/trunk/src/chrome/browser/shell_integration_linux.cc

**Comment by shiftkey** [comment]
@kleinen as this is something that I believe needs to be fixed in Electron itself, I'm going to close this out and refer to the upstream issue tracking this request: https://github.com/electron/electron/issues/6440

**Comment by kleinen** [comment]
@shiftkey sounds good.  Thanks for the info on the other issue.  I hadn't seen it yet.
