### ISSUE TITLE
Inform the user that no remote is specified

### ISSUE THREAD

**Issue by moritztim** [desktop/desktop#17552]
### The feature request

![image](https://github.com/desktop/desktop/assets/90388353/ddde7c73-4cbe-4301-b62a-0f16686f9c0f)
*no remote specified*
![image](https://github.com/desktop/desktop/assets/90388353/f2c227dd-91e8-4634-86ad-ec78615db40a)
*"fatal: no path specified; see 'git help pull' for valid url syntax"*
When trying to interact with the remote while none is set, you get this error message, which might be confusing, especially because it's not directed at a user of gh desktop but at a user of git, telling you to consult git help.

### Proposed solution

I think this condition should have either its own error message or perhaps the push/pull button shouldn't even be there, instead a message saying that there's no remote specified and a button that leads to settings.

**Comment by steveward** [comment]
@moritz-t-w thanks for reporting this. If a remote isn't present the `Publish` option should be shown. I tried to reproduce this behavior was unable to -- are there any details I'm missing that could help me reproduce this? If I run `git remote remove origin` the `Publish` option correctly appears again.

**Comment by moritztim** [comment]
Hmm.. Yes I was messing around a bit, so it was probably some edge case. It might have been a submodule too and I may have manually deleted the `.gitmodules` file in a freak accident. Can't remember if this was that and I don't have time right now to figure it out atm. I'll get back to this when I do.

**Comment by steveward** [comment]
Thanks for the update! I'm going to close this out, but we can always reopen and investigate further.

**Comment by moritztim** [comment]
Note to self: it was something to do with submodules and manual fucking around
