### ISSUE TITLE
i can not create a live link for my project

### ISSUE THREAD

**Issue by sayedNamat-Mosavi** [desktop/desktop#17562]
### The problem

i can not create a live link for my project

### Release version

2023

### Operating system

windows

### Log files

i can not create a live link for my project

### Screenshots

i can not create a live link for my project

### Additional context

i can not create a live link for my project

**Comment by steveward** [comment]
@sayedNamat-Mosavi this issue tracker is for GitHub Desktop, it sounds like you are having issue with a different project or another area of GitHub. I'd recommend reaching out for help at the [GitHub Community Forum](https://github.com/orgs/community/discussions/).
