### ISSUE TITLE
Failed to launch report - cannot read property 'screen' of undefined at o.exports

### ISSUE THREAD

**Issue by vanm** [desktop/desktop#1756]
### Description

Github Desktop was open and my laptop went to sleep.  When I opened it back up, I saw this error message.

### Version

**GitHub Desktop version:** 0.5.6

**OS version:** Mac OS 10.12.5

### Steps to Reproduce

**Expected behaviour:** [What you expected to happen]

App launches

**Actual behaviour:** [What actually happened]

App fails to launch

**Reproduces how often:** [What percentage of the time does it reproduce?]

I closed the App and restarted and was unable to reproduce the issue. It launched just fine.

<img width="726" alt="screen shot 2017-05-24 at 1 36 23 pm" src="https://cloud.githubusercontent.com/assets/231196/26424545/6f8c87cc-4086-11e7-8b80-5724ea79a9d6.png">

**Comment by joshaber** [comment]
Thanks! We think this was fixed in 0.5.7. Go to the GitHub Desktop > About GitHub Desktop menu and click "Check for Updates".
