### ISSUE TITLE
Move "New Branch…" into the "Branch" menu

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#1757]
Splitting this off #1575 as I think it's an easy, quick win.

It's currently in the "File" menu. Move it to the "Branch" menu.

**Comment by iAmWillShepherd** [comment]
Are there any opinions on where in the **Branch** menu it should be placed?

**Comment by iAmWillShepherd** [comment]
Should we move these to the  **Repository** menu?
![2017-05-25_10-28-51](https://cloud.githubusercontent.com/assets/1715082/26457226/0388c086-4135-11e7-8893-5b97a1c098b1.jpeg)

**Comment by joshaber** [comment]
>Should we move these to the Repository menu?

Maaaybe. But for now we haven't received any feedback that I know of around where these live.
