### ISSUE TITLE
Searching commit by its name

### ISSUE THREAD

**Issue by Jedrzej94** [desktop/desktop#17575]
### The feature request

In the UI in the "History" tab (shortcut: `Ctrl + 2`).

There's an input: "Select branch to compare...".

Is there any particular reason why there's no search-input to find/**filter** commits history by commit name? In our environment, we are pushing commits with issue's ID from Jira (e.g.: BEE-0001).

I'd like to filter commits with commit name in the history tab.

### Proposed solution

Add search input to filter commits by commit name (or description)

**Comment by steveward** [comment]
Thanks for the issue @Jedrzej94. This is being tracked in https://github.com/desktop/desktop/issues/7022 so I'm going to add this feedback there.
