### ISSUE TITLE
Contenu github truste

### ISSUE THREAD

**Issue by ger1964jou** [desktop/desktop#17583]
### The problem

Contenu de traduction mal interprété de son origine. Code source et indise et visual studio engine de Google map et outil d application imap geodaltales. Pour le contenu manquant à l éducation de github universe 2023. 

### Release version

g.dev

### Operating system

g.dev/github.com

### Additional context

Contenu dois rétablir quoi lui.

**Comment by tidy-dev** [comment]
@Gerard19742608jourdain Thank you for reaching out. Unfortunately, no one on the team speaks what google translate says is "French". 

Google translate:

> Translation content misinterpreted from its origin. Source code and indise and visual studio engine of Google map and imap geodaltales application tool. For content missing from github universe 2023 education.


From that I do not believe this is related to GitHub Desktop and an closing.
