### ISSUE TITLE
Github Desktop for Mac - clone repo failure

### ISSUE THREAD

**Issue by dmiyamasu** [desktop/desktop#1758]
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

I am attempting to clone my public repo (https://github.com/dmiyamasu/dmiyamasu.git) on my local mac (OSX Sierra) . I am receiving an error on the 'clone repository' prompt.

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** 0.5.8

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** 10.12.1

### Steps to Reproduce

1. Open Githb for mac application
2.   Sign into my github account in the desktop app
3. Attempt to clone my repo (https://github.com/dmiyamasu/dmiyamasu.git)
4. see error message and cannot proceed.

![image](https://cloud.githubusercontent.com/assets/508468/26431369/17ebc51e-40c2-11e7-92be-2e00bca8cc86.png)

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behaviour:** I expect the repo to be cloned to my local machine

**Actual behaviour:** I cannot get past the 'clone repo' prompt error message

**Reproduces how often:** I have tried this 5-6 times. I have signed out of the desktop app, signed back in twice and still not working.

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`

[2017-05-25.desktop.production.log.zip](https://github.com/desktop/desktop/files/1027635/2017-05-25.desktop.production.log.zip)

 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by shiftkey** [comment]
@dmiyamasu it looks like in the screenshot you are able to clone (despite the warning). On my side I was able to clone after providing the full URL with `.git` on the end.

The logs do show this lookup is trying some strange combinations for the owner and repository alias:

```
2017-05-25T00:41:58.007Z - error: fetchRepository: not found for 'dmiyamasu' and 'dmiyamasu/dmiyamasu'
Error: {
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
...
2017-05-25T00:41:58.060Z - error: fetchRepository: not found for '' and 'dmiyamasu/dmiyamasu'
Error: {
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
...

Do you remember what other inputs you were trying here to get it into this state? It'd be nice to handle those better in the app...

**Comment by joshaber** [comment]
Closing until we get more information.
