### ISSUE TITLE
Tray/task bar icon & app background mode

### ISSUE THREAD

**Issue by Hacksore** [desktop/desktop#17587]
### The feature request

Many apps live nicely out of sight and github desktop would be a nice candidate for that.

This would allow you to get notified on PRs without having to have the app open/visible and it can instead run in the background.

### Proposed solution

- add a [`Tray` impl](https://www.electronjs.org/docs/latest/api/tray)
- add a setting to allow you to [hide the icon from the dock on macOS](https://www.electronjs.org/docs/latest/api/dock#dockhide-macos)

**Comment by tidy-dev** [comment]
@Hacksore Thanks for opening this. However, you can read more context around why we do not plan to support in the following issue: https://github.com/desktop/desktop/issues/7291#issuecomment-483310026. As such as I am closing this as not planned.
