### ISSUE TITLE
EULA

### ISSUE THREAD

**Issue by DIEGOHJJACOBO** [desktop/desktop#17585]
End-User License Agreement

This End-User License Agreement (EULA) is a legal agreement between you (either as an individual or on behalf of an entity) and GitHub, Inc. regarding your use of GitHub's desktop applications, including GitHub DesktopTM for Mac and Windows and associated documentation (the "Software"). IF YOU DO NOT AGREE TO ALL OF THE TERMS OF THIS EULA, DO NOT INSTALL, USE OR COPY THE SOFTWARE.

Summary

You must agree to all of the terms of this EULA to use this Software.
If so, you may use the Software for free and for any lawful purpose.
This Software automatically communicates with GitHub servers for three reasons: (1) to receive and install updates; (2) to send error reports; and (3) to send anonymized usage information. You can view sample data to see what information is sent, and you may opt out of sending the anonymized usage data.
This Software is provided "as-is" with no warranties, and you agree that GitHub is not liable for anything you do with it.
You really ought to just go ahead and read the whole EULA. It's not all that long. You should not only rely on this summary.
The Agreement

By downloading, installing, using, or copying the Software, you accept and agree to be bound by the terms of this EULA. If you do not agree to all of the terms of this EULA, you may not download, install, use or copy the Software.

The License

This EULA entitles you to install as many copies of the Software as you want, and use the Software for any lawful purpose consistent with this EULA. Your license to use the Software is expressly conditioned upon your agreement to all of the terms of this EULA. This software is licensed, not sold. GitHub reserves all other rights not granted by this EULA.

The Restrictions

When using the Software you must use it in a manner that complies with the applicable laws in the jurisdiction(s) in which you use the Software.
You may not sell, resell, rent, lease or exchange the Software for anything of value.
You may redistribute the software, but it must include this EULA and you may not repackage or bundle the Software with any other software.
You may not remove or alter any proprietary notices or marks on the Software.
Privacy Notices

The Software automatically communicates with GitHub servers for three purposes: (1) updating the Software; (2) sending error reports; and (3) sending anonymized usage data so we may improve the Software. If you would like to learn more about the specific information we send, please visit https://desktop.github.com/usage-data/. You may opt out of sending the anonymized usage data, but if you do not want the Software to update automatically or send error reports, you must uninstall the Software.

Automatic Software Updates. The Software communicates with GitHub (and sends information described at the URL above) to determine whether there are any patches, bug fixes, updates, upgrades or other modifications to improve the Software. You agree that the Software may automatically install any such improvements to the Software on your computer without providing any further notice or receiving any additional consent. This feature may not be disabled. If you do not want to receive automatic updates, you must uninstall the Software.
Error Reports. In order to help us improve the Software, when the Software encounters certain errors, it will automatically send some information to GitHub about the error (as described at the URL above). This feature may not be disabled. If you do not want to send error reports to GitHub, you must uninstall the Software.
Anonymized Usage Data. GitHub collects anonymized data about your usage of the Software to help us make it more awesome. Approximately once a day the Software sends such data (as described in more detail at the URL above) to GitHub's servers. If you do not want to send anonymized usage data to GitHub, you may opt out by changing your settings in the Preferences view.
Open-Source Notices

Certain components of the Software may be subject to open-source software licenses ("Open-Source Components"), which means any software license approved as open-source licenses by the Open Source Initiative or any substantially similar licenses, including without limitation any license that, as a condition of distribution of the software licensed under such license, requires that the distributor make the software available in source code format. The Software documentation includes copies of the licenses applicable to the Open-Source Components.

To the extent there is conflict between the license terms covering the Open-Source Components and this EULA, the terms of such licenses will apply in lieu of the terms of this EULA. To the extent the terms of the licenses applicable to Open-Source Components prohibit any of the restrictions in this Agreement with respect to such Open-Source Component, such restrictions will not apply to such Open-Source Component. To the extent the terms of the licenses applicable to Open-Source Components require Licensor to make an offer to provide source code in connection with the Product, such offer is hereby made, and you may exercise it by contacting support@github.com

Intellectual Property Notices

The Software and all worldwide copyrights, trade secrets, and other intellectual property rights therein are the exclusive property of GitHub. GitHub reserves all rights in and to the Software not expressly granted to you in this EULA.

The names GitHub, GitHub Desktop, GitHub for Mac, GitHub for Windows, Atom, the Octocat, and related GitHub logos and/or stylized names are trademarks of GitHub. You agree not to display or use these trademarks in any manner without GitHub's prior, written permission, except as allowed by GitHub's Logos and Usage Policy: https://github.com/logos.

Disclaimers and Limitations on Liability

THE SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, AND NO WARRANTY, EITHER EXPRESS OR IMPLIED, IS GIVEN. YOUR USE OF THE SOFTWARE IS AT YOUR SOLE RISK. GitHub does not warrant that (i) the Software will meet your specific requirements; (ii) the Software is fully compatible with any particular platform; (iii) your use of the Software will be uninterrupted, timely, secure, or error-free; (iv) the results that may be obtained from the use of the Software will be accurate or reliable; (v) the quality of any products, services, information, or other material purchased or obtained by you through the Software will meet your expectations; or (vi) any errors in the Software will be corrected.

YOU EXPRESSLY UNDERSTAND AND AGREE THAT GITHUB SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF GITHUB HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES) RELATED TO THE SOFTWARE, including, for example: (i) the use or the inability to use the Software; (ii) the cost of procurement of substitute goods and services resulting from any goods, data, information or services purchased or obtained or messages received or transactions entered into through or from the Software; (iii) unauthorized access to or alteration of your transmissions or data; (iv) statements or conduct of any third-party on the Software; (v) or any other matter relating to the Software.

GitHub reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Software (or any part thereof) with or without notice. GitHub shall not be liable to you or to any third-party for any modification, price change, suspension or discontinuance of the Software.

Miscellanea

If you configure the Software to work with one or more accounts on the GitHub.com website or with an instance of GitHub Enterprise, your use of the Software will also be governed by the GitHub.com website Terms of Service and/or the license agreement applicable to your instance of GitHub Enterprise.
The failure of GitHub to exercise or enforce any right or provision of this EULA shall not constitute a waiver of such right or provision.
This EULA constitutes the entire agreement between you and GitHub and governs your use of the Software, superseding any prior agreements between you and GitHub (including, but not limited to, any prior versions of the EULA).
You agree that this EULA and your use of the Software are governed under California law and any dispute related to the Software must be brought in a tribunal of competent jurisdiction located in or near San Francisco, California.
Please send any questions about this EULA to support@github.com.

**Comment by niik** [comment]
Hi, this issue doesn’t appear to be actionable I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.
