### ISSUE TITLE
Github Destkop not letting me change account

### ISSUE THREAD

**Issue by LucasWalica** [desktop/desktop#17582]
### The problem

Basically I have 2 github accounts, one for personal use and the other one that I had to create because of my studies, basically the problem is that I can not change between accounts in github destkop which is quite annoying.

Anyways, thanks for reading it and I wish a nice day.

### Release version

Version 3.3.4 (x64)

### Operating system

windows 10

### Steps to reproduce the behavior

1-Signed in an Account
2-Signing out
3-Trying to sign in again entering other account
4-When navigator windows prompts(in this case mozilla developer) to introduce your credentials it doest charge and it stays signed in the first account.

**Comment by tidy-dev** [comment]
@LucasWalica Thanks for reaching out.  What you will need to do is sign into the account you want to sign into on GitHub.com before attempting to sign in in Desktop. 

Your repro steps should be:
1. On GitHub.com, sign out of Account A
2. On GitHub.com, sign in of Account B.
3. In GitHub Desktop, sign out of Account A
4. In GitHub Desktop, sign in 

It will redirect to GitHub.com and log into the currently logged in account.
