### ISSUE TITLE
Every update recreates desktop shortcut

### ISSUE THREAD

**Issue by tivac** [desktop/desktop#1759]
### Description

Every time GitHub Desktop downloads a new version it recreates the desktop shortcut. I've deleted it multiple times because I don't want it there.

### Version

**GitHub Desktop version:** 0.5.8

**OS version:** `Microsoft Windows [Version 10.0.15063]`

### Steps to Reproduce

1. Install GitHub Desktop
2. Delete the desktop shortcut
3. Wait for a new build to be downloaded and installed in the background
4. Note that a new desktop shortcut has been created

**Expected behaviour:** The shortcut stays removed and is not recreated

**Actual behaviour:** The shortcut is recreated

**Reproduces how often:** 100% of the time when a new build is downloaded & installed.

**Comment by shiftkey** [comment]
This behaviour lives in `Squirrel.Windows` and it sounds like this behaviour isn't exposed to the application: https://github.com/Squirrel/Squirrel.Windows/issues/831

**Comment by GeorgeWL** [comment]
Okay. I've even weirder. Every tick makes it come back.

https://streamable.com/x60h0

This is me deleting it. The very next second it comes back.
