### ISSUE TITLE
Enumerating objects: 4, done. Counting objects: 100% (4/4), done. Delta compression using up to 4 threads Compressing objects: 100% (3/3), done. Writing objects: 100% (3/3), 492 bytes | 246.00 KiB/s, done. Total 3 (delta 1), reused 0 (delta 0), pack-reused 0 remote: Resolving deltas: 100% (1/1), completed with 1 local object.         To https://github.com/Maersk-Global/ifsapp10-customer-solution.git  ! [remote rejected] topic -> topic (cannot lock ref 'refs/heads/topic': 'refs/heads/topic/tratlk/IDP-210-new-development' exists; cannot create 'refs/heads/topic') error: failed to push some refs to 'https://github.com/Maersk-Global/ifsapp10-customer-solution.git'

### ISSUE THREAD

**Issue by tejeswini22295** [desktop/desktop#17597]
### The feature request

Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 4 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 492 bytes | 246.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.        
To https://github.com/Maersk-Global/ifsapp10-customer-solution.git
 ! [remote rejected] topic -> topic (cannot lock ref 'refs/heads/topic': 'refs/heads/topic/tratlk/IDP-210-new-development' exists; cannot create 'refs/heads/topic')
error: failed to push some refs to 'https://github.com/Maersk-Global/ifsapp10-customer-solution.git'

### Proposed solution

Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 4 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 492 bytes | 246.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.        
To https://github.com/Maersk-Global/ifsapp10-customer-solution.git
 ! [remote rejected] topic -> topic (cannot lock ref 'refs/heads/topic': 'refs/heads/topic/tratlk/IDP-210-new-development' exists; cannot create 'refs/heads/topic')
error: failed to push some refs to 'https://github.com/Maersk-Global/ifsapp10-customer-solution.git'

**Comment by sergiou87** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by riteshKumar-cyber** [comment]
this is my food -delivery project
