### ISSUE TITLE
Issue with My GitHub Account

### ISSUE THREAD

**Issue by moloruntomiwa31** [desktop/desktop#17598]
Dear Support Team,

I am writing to seek assistance with a recent issue I've encountered on my GitHub account. Over the past few days, my account has been flagged as spam, resulting in a restriction that prevents me from authorizing third-party applications. The specific message I receive is: "You are marked as spam, and therefore cannot authorize a third-party application."

This situation is affecting my ability to push code from my text editor, which, in turn, is impeding my productivity. I kindly request a review and resolution of this issue as soon as possible.

Thanks.

**Comment by steveward** [comment]
@moloruntomiwa31 you will need to reach out to [GitHub Support](https://support.github.com/) to get this resolved. This issue tracker is specifically for GitHub Desktop.
