### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by ZhonghuaYin** [desktop/desktop#17595]
### The problem

The undo button can not display well when the file path is long.

### Release version

latest

### Operating system

MacOS 13.5 (22G74)

### Screenshots

<img width="739" alt="image" src="https://github.com/desktop/desktop/assets/82427193/43f3ff29-8d65-4931-b70b-200ab3ba62e1">

**Comment by sergiou87** [comment]
Thanks for your report! I was able to reproduce the issue, and I think it was caused by this change: https://github.com/desktop/desktop/pull/17373 😞 

I will look into this
