### ISSUE TITLE
Show commits behind/ahead

### ISSUE THREAD

**Issue by tyhrstan** [desktop/desktop#17607]
### The feature request

It would be great if it would be possible to see how many commits a branch is ahead or behind.

### Proposed solution

On the web when selecting a branch it shows the amound of commits ahead or behind. A similar information box in the desktop client would be great so you can instantly see if your branch is behind the root.

**Comment by steveward** [comment]
Thanks for the issue @tyhrstan, I'm going to roll this into https://github.com/desktop/desktop/issues/8048 where we are tracking enhancements to the branch list.

For reference you can go to `History` > `Select Branch to compare` to see the ahead/behind counts.
