### ISSUE TITLE
Expand button disappeard

### ISSUE THREAD

**Issue by rockmandash** [desktop/desktop#17608]
### The problem

<img width="799" alt="image" src="https://github.com/desktop/desktop/assets/7580792/ceaf1527-51ee-424e-8a7f-f831f5a6963f">

### Release version

Version 3.3.4 (arm64)

### Operating system

Sonoma 14.0（23A344）

**Comment by sergiou87** [comment]
Hey @rockmandash !

Is that file bigger than 256 KB? We have a limitation for syntax highlighting that we're also applying for diff expansion: https://github.com/desktop/desktop/blob/2f6b27161cc65480f67dd0ab6626fcfc52a6c1c9/app/src/ui/diff/syntax-highlighting/index.ts#L19-L27

**Comment by rockmandash** [comment]
No, it's just 50 lines of simple code. I've also included a screencast and discovered that this problem only occurs upon initial startup.

https://github.com/desktop/desktop/assets/7580792/b74c2431-a5db-4a8e-a963-d67ff2b822d2

**Comment by sergiou87** [comment]
Thanks for that screencast, it's really helpful 🙏 

However, I'm unable to get the app into that state 🤯 I see it fixes itself when you switch between files.

Are you able to reproduce this issue in a different repository or in a different machine?
