### ISSUE TITLE
Combine Changes and History panels

### ISSUE THREAD

**Issue by alensiljak** [desktop/desktop#17609]
### The feature request

I would like to have just one combined view, instead of separate Changes and History. They technically show the same information in the panels.

### Proposed solution

The most practical way would be to have the top-most item of the History view display the current changes. Any other item shows the historic node, as it does now.
Considering the application practically ignores the Staged/Unstaged Git states, it is even easier to implement as no Staged panel is required. The layout for both views is identical.

Benefits: 
- Removes redundant switching between the current changes and history. 
- Makes it easier to see the commit history *and* the current changes at the same time.
- Regains some screen realestate by removing the Changes/History buttons.

### Additional context

I hope the description is clear enough but here is a quick mock-up anyway:

![image](https://github.com/desktop/desktop/assets/462445/bba76cfb-cd55-4b2f-8d70-c50a2b0b13d7)

The marked block would be used for the current changes. It would be visually separate from the rest of the history (i.e. border, title or some other visual perk).

**Comment by alensiljak** [comment]
Additionally, this whole History/Changes panel could then be collapsible, to allow for even more screen realestate when working on the current changes and focusing on the diff window.

**Comment by alensiljak** [comment]
As an example, here's a screenshot from GittyUp:

![image](https://github.com/desktop/desktop/assets/462445/e7b67d1d-f2b5-4aba-8d02-8eeba5757d58)

**Comment by steveward** [comment]
Thanks for the issue @alensiljak! At this time we do not have any plans of making this major of a change in the GitHub Desktop interface, but we do appreciate the feedback. I'm going to close this out, but thanks again for taking the time to share the improvements you'd like to see to GitHub Desktop.
