### ISSUE TITLE
Vigilant Mode in GitHub Desktop

### ISSUE THREAD

**Issue by samkhan1** [desktop/desktop#17603]
### The feature request

Requesting feature for: 

- Signing commits and tags using personal SSH or PGP keys for distinguishing between "verified" and "unverfied" contributions to a projects as per [GitHub's Vigiant mode.](https://docs.github.com/en/authentication/managing-commit-signature-verification/displaying-verification-statuses-for-all-of-your-commits) 

GitHub desktop currently pushes to remote using HTTPS mode, with the user having given GitHub Desktop app OAuth authorization. An added layer of security, or a seperate mode of security involving SSH and PGP keys, can allow the user to have control over verifyed vs unverified commits for different projects, wherein, the different projects can be allowed to use a seperate SSH or PGP key with required expiration date for the key.  

### Proposed solution

A way to include signed and unsigned SSH or PGP keys, in the GitHub Desktop Prefrence settings, which can then be used during `git push` in respective projects. 

The keys can be generated and managed using a separate application that most probably does not have to be integrated into GitHub Desktop. A method for selecting and using an existing key from its accessible location in a mounted drive or folder, could be sufficient. 

If an application to generate and manage SSH and PGP keys were to be included with GitHub Desktop as an addition, it could greatly improve the user experience for switching between keys for different projects.

**Comment by sergiou87** [comment]
Hello! We are tracking all GPG signing improvements on GitHub Desktop in this other issue: https://github.com/desktop/desktop/issues/78

I will close this in favor of that one.
