### ISSUE TITLE
Github desktop not able to use in M2 MacOS

### ISSUE THREAD

**Issue by dhapolapankaj** [desktop/desktop#17616]
### The problem

I tried tried downloading the Github desktop on my Mac PC.
After unzip and on double clicking, I am getting attached error message

<img width="423" alt="Screenshot 2023-10-24 at 1 26 54 PM" src="https://github.com/desktop/desktop/assets/29034223/11f3ecaf-c86f-4822-a51a-fb93077f0a8e">

I tried brew and getting SHA256 error

<img width="1210" alt="Screenshot 2023-10-24 at 1 34 46 PM" src="https://github.com/desktop/desktop/assets/29034223/f7c92e11-6fe0-4a26-8ecf-84a588443462">

Any suggestions please?

### Release version

3.3.4

### Operating system

MacOS - Apple M2 Pro

### Steps to reproduce the behavior

1. Goto https://desktop.github.com/
2. Click on "Download for macOS" button
3. Double click on downloaded zip file
4. double click on unzipped "Github Desktop.app" file
5. The application can't be opened message box pops up

### Screenshots

Already shared in description

**Comment by goldstone23** [comment]
may be this is a hardware glitch try to spend more time downloading it from the start firstly restart your laptop.

**Comment by sergiou87** [comment]
Hey @dhapolapankaj!

I can't tell about the `brew` issue, but it seems you have downloaded the Intel version of the app from https://desktop.github.com

The link for Apple silicon is here:


![Image](https://github.com/desktop/desktop/assets/1083228/4f5339d6-9589-4a61-aa16-279c99bab225)

It should be this: https://central.github.com/deployments/desktop/desktop/latest/darwin-arm64

Please let me know if that helps!

**Comment by dhapolapankaj** [comment]
Hi @sergiou87 
I had tried that link earlier and tried again but having same error popup.

Any more ideas?

<img width="568" alt="Screenshot 2023-10-24 at 3 43 52 PM" src="https://github.com/desktop/desktop/assets/29034223/b4efe5c8-1c51-4c77-87ba-16a510d0304f">

**Comment by dhapolapankaj** [comment]
@goldstone23 restart didn't helped.

**Comment by sergiou87** [comment]
@dhapolapankaj could you open the `Console` app, filter by `GitHub Desktop`, start recording events and then try to open the app?

Any issues should show up in there 🤞 



![Image](https://github.com/desktop/desktop/assets/1083228/310e0139-70eb-4672-814b-cd2bc1fe5f4d)

**Comment by dhapolapankaj** [comment]
Hi @sergiou87 
Thanks for taking this up.

Attaching log.
Hope this helps.

[Github Desktop console log](https://github.com/desktop/desktop/files/13121756/Github.Desktop.console.log)

**Comment by sergiou87** [comment]
Thank you for that! It's really weird… could you try moving the app to `/Applications` before opening it?

Another question: is that a work machine? Does it have any kind of anti-virus or anti-malware software in it?

I wonder if that kind of software is removing or blocking part of GitHub Desktop, and that's causing the error…

**Comment by dhapolapankaj** [comment]
I tried dragging the app in the applications. Still getting same error

<img width="400" alt="Screenshot 2023-10-25 at 5 55 35 PM" src="https://github.com/desktop/desktop/assets/29034223/110e4a51-e531-40ea-bb07-e01dcc918617">

Yeah, this is work machine and recently I installed lot of other apps like VSCode, MSOffice apps etc...
They all got installed properly.

**Comment by sergiou87** [comment]
That is so strange 😕 
 
Could you right-click on the `.app` file, then `Show package contents`, and then check if you have `Contents/PlugIns` and `Contents/Extensions` in there?

**Comment by dhapolapankaj** [comment]
Yeah, Those folders are missing.

<img width="400" alt="Screenshot 2023-10-26 at 6 34 55 PM" src="https://github.com/desktop/desktop/assets/29034223/5ce83c54-1765-4b00-b730-edc38d6895e8">

**Comment by dhapolapankaj** [comment]
Sorry. That was accidental click on close

**Comment by sergiou87** [comment]
Sounds like that machine has some kind of anti-virus or anti-malware software installed. I'd recommend you to disable it temporarily and/or contact the admin of your IT department to work out the problem with them 😕 

Unfortunately, I don't think there is anything we can do about it with the information we have 😞 So, at least for now, I'm gonna close this issue.
