### ISSUE TITLE
Unable to install Github Desktop app in 

### ISSUE THREAD

**Issue by YashRB9** [desktop/desktop#17610]
I am trying to install github desktop in my remote desktop app.
![github](https://github.com/desktop/desktop/assets/107021183/0b61ca33-696c-4ec4-9b33-7716da81c4d4)

Please help me to fix this issue & install.

**Comment by steveward** [comment]
Thanks for the issue @YashRB9. Can you click `Open Setup Log` and share that file as an attachment in this issue? That should give us some more information about why the install is failing.

**Comment by sergiou87** [comment]
Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by sergiou87** [comment]
Could you click on that `Open Setup Log` and share its contents with us? 🙏

**Comment by YashRB9** [comment]
If I click on open Setup Log nothing will open.


 
 




​
​​NOTICE[v1b2c3d4e5f6]
Please Consider the Environment before printing this Email
This email was sent from within the Reckitt Benckiser Group plc group of companies (http://www.reccol.com). This email (and any attachments or hyperlinks within it) may contain information that is confidential, legally privileged or otherwise protected from disclosure. If you are not the intended recipient of this email, you are not entitled to use, disclose, distribute, copy, print, disseminate or rely on this email in any way. If you have received this email in error, please notify the sender immediately by telephone or email and destroy it, and all copies of it.
​We have taken steps to ensure that this email (and any attachments) are free from computer viruses and the like. However, it is the recipient's responsibility to ensure that it is actually virus free. Any emails that you send to us may be monitored for the purposes of ascertaining whether the communication complies with the law and our policies.
From: Sergio Padrino ***@***.***>
Sent: Monday, October 23, 2023 8:36 PM
To: desktop/desktop ***@***.***>
Cc: Alapati, Yasaswini (Contractor) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [desktop/desktop] Unable to install Github Desktop app in (Issue #17610)


Could you click on that Open Setup Log and share its contents with us? 🙏

**Comment by steveward** [comment]
Can you go to `%LocalAppData%\SquirrelTemp\SquirrelSetup.log` and see if the installation log can be found there?

Please send that over as an attachment.

**Comment by YashRB9** [comment]
PFA.


 
 




​
​​NOTICE[v1b2c3d4e5f6]
Please Consider the Environment before printing this Email
This email was sent from within the Reckitt Benckiser Group plc group of companies (http://www.reccol.com). This email (and any attachments or hyperlinks within it) may contain information that is confidential, legally privileged or otherwise protected from disclosure. If you are not the intended recipient of this email, you are not entitled to use, disclose, distribute, copy, print, disseminate or rely on this email in any way. If you have received this email in error, please notify the sender immediately by telephone or email and destroy it, and all copies of it.
​We have taken steps to ensure that this email (and any attachments) are free from computer viruses and the like. However, it is the recipient's responsibility to ensure that it is actually virus free. Any emails that you send to us may be monitored for the purposes of ascertaining whether the communication complies with the law and our policies.
From: Steve Ward ***@***.***>
Sent: Thursday, October 26, 2023 1:17 AM
To: desktop/desktop ***@***.***>
Cc: Alapati, Yasaswini (Contractor) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [desktop/desktop] Unable to install Github Desktop app in (Issue #17610)


Can you go to %LocalAppData%\SquirrelTemp\SquirrelSetup.log and see if the installation log can be found there?

Please send that over as an attachment.

-

**Comment by steveward** [comment]
@YashRB9 unfortunately attachments don't come through in email replies, you will need to upload the log file directly in this issue.

**Comment by YashRB9** [comment]
​
​​NOTICE[v1b2c3d4e5f6]
Please Consider the Environment before printing this Email
This email was sent from within the Reckitt Benckiser Group plc group of companies (http://www.reccol.com). This email (and any attachments or hyperlinks within it) may contain information that is confidential, legally privileged or otherwise protected from disclosure. If you are not the intended recipient of this email, you are not entitled to use, disclose, distribute, copy, print, disseminate or rely on this email in any way. If you have received this email in error, please notify the sender immediately by telephone or email and destroy it, and all copies of it.
​We have taken steps to ensure that this email (and any attachments) are free from computer viruses and the like. However, it is the recipient's responsibility to ensure that it is actually virus free. Any emails that you send to us may be monitored for the purposes of ascertaining whether the communication complies with the law and our policies.
From: Alapati, Yasaswini (Contractor) ***@***.***>
Sent: Thursday, October 26, 2023 2:27 PM
To: desktop/desktop ***@***.***>; desktop/desktop ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [EXTERNAL] Re: [desktop/desktop] Unable to install Github Desktop app in (Issue #17610)

PFA.

From: Steve Ward ***@***.******@***.***>>
Sent: Thursday, October 26, 2023 1:17 AM
To: desktop/desktop ***@***.******@***.***>>
Cc: Alapati, Yasaswini (Contractor) ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [desktop/desktop] Unable to install Github Desktop app in (Issue #17610)


Can you go to %LocalAppData%\SquirrelTemp\SquirrelSetup.log and see if the installation log can be found there?

Please send that over as an attachment.

-

**Comment by YashRB9** [comment]
[Squirrel-Install.1.log](https://github.com/desktop/desktop/files/13189119/Squirrel-Install.1.log)
[Squirrel-Install.log](https://github.com/desktop/desktop/files/13189121/Squirrel-Install.log)

**Comment by YashRB9** [comment]
Attached log please check.

**Comment by steveward** [comment]
Thanks for the log file. This looks like the issue:

```
[26/10/23 14:21:22] fatal: Finished with unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\YAlapati\AppData\Local\GitHubDesktop\app-3.3.4-beta3\resources\app\git\usr\bin\basenc.exe' is denied.
```

Are you running any antivirus or security software on the machine that could be preventing the installation from completing?

**Comment by YashRB9** [comment]
Might be but am not sure as it's an office laptop and logged into client Machine. Any possible solution if yes that we can use GitHub desktop?


 
 




​
​​NOTICE[v1b2c3d4e5f6]
Please Consider the Environment before printing this Email
This email was sent from within the Reckitt Benckiser Group plc group of companies (http://www.reccol.com). This email (and any attachments or hyperlinks within it) may contain information that is confidential, legally privileged or otherwise protected from disclosure. If you are not the intended recipient of this email, you are not entitled to use, disclose, distribute, copy, print, disseminate or rely on this email in any way. If you have received this email in error, please notify the sender immediately by telephone or email and destroy it, and all copies of it.
​We have taken steps to ensure that this email (and any attachments) are free from computer viruses and the like. However, it is the recipient's responsibility to ensure that it is actually virus free. Any emails that you send to us may be monitored for the purposes of ascertaining whether the communication complies with the law and our policies.
From: Steve Ward ***@***.***>
Sent: 27 October 2023 19:35
To: desktop/desktop ***@***.***>
Cc: Alapati, Yasaswini (Contractor) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [desktop/desktop] Unable to install Github Desktop app in (Issue #17610)


Thanks for the log file. This looks like the issue:

[26/10/23 14:21:22] fatal: Finished with unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\YAlapati\AppData\Local\GitHubDesktop\app-3.3.4-beta3\resources\app\git\usr\bin\basenc.exe' is denied.

Are you running any antivirus or security software on the machine that could be preventing the installation from completing?

-

**Comment by YashRB9** [comment]
Any update to fix this issue?

From: Alapati, Yasaswini (Contractor)
Sent: Friday, October 27, 2023 8:20 PM
To: desktop/desktop ***@***.***>; desktop/desktop ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [EXTERNAL] Re: [desktop/desktop] Unable to install Github Desktop app in (Issue #17610)

Might be but am not sure as it's an office laptop and logged into client Machine. Any possible solution if yes that we can use GitHub desktop?


 
 




​
​​NOTICE[v1b2c3d4e5f6]
Please Consider the Environment before printing this Email
This email was sent from within the Reckitt Benckiser Group plc group of companies (http://www.reccol.com). This email (and any attachments or hyperlinks within it) may contain information that is confidential, legally privileged or otherwise protected from disclosure. If you are not the intended recipient of this email, you are not entitled to use, disclose, distribute, copy, print, disseminate or rely on this email in any way. If you have received this email in error, please notify the sender immediately by telephone or email and destroy it, and all copies of it.
​We have taken steps to ensure that this email (and any attachments) are free from computer viruses and the like. However, it is the recipient's responsibility to ensure that it is actually virus free. Any emails that you send to us may be monitored for the purposes of ascertaining whether the communication complies with the law and our policies.
From: Steve Ward ***@***.******@***.***>>
Sent: 27 October 2023 19:35
To: desktop/desktop ***@***.******@***.***>>
Cc: Alapati, Yasaswini (Contractor) ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [desktop/desktop] Unable to install Github Desktop app in (Issue #17610)


Thanks for the log file. This looks like the issue:

[26/10/23 14:21:22] fatal: Finished with unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\YAlapati\AppData\Local\GitHubDesktop\app-3.3.4-beta3\resources\app\git\usr\bin\basenc.exe' is denied.

Are you running any antivirus or security software on the machine that could be preventing the installation from completing?

-

**Comment by sergiou87** [comment]
Hey @YashRB9 ! If it's a work machine, we'd recommend you to contact the admin of your IT department to work out the problem, because it seems they have some antivirus or anti-malware software installed that is preventing GitHub Desktop from being installed.

At least with the info we have, we don't see anything we can do to fix this, so I'm gonna close this issue 😓 Sorry!
