### ISSUE TITLE
MacOS: failed to commit or detect local changes

### ISSUE THREAD

**Issue by shunnnli** [desktop/desktop#17615]
### The problem

Hi, 

I have a repo rested on a server from our school and github desktop used to work perfectly but suddenly following error occured.

1. Initiaially, github desktop can detect my changes but when I commit I receive following error: 
**Command failed: /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git commit -F -**
2. Once I closed this error dialoge, github desktop can no longer detect my changes
3. I saved a version of .git elsewhere in my local path, and once I replace the repo path .git folder with the saved .git folder, I can recreate step 1 but the error will still occurs

Thanks a lot!

### Release version

Version 3.3.4 (arm64)

### Operating system

Sonoma 14.0 (23A344)

### Log files

[2023-10-23.desktop.production.log](https://github.com/desktop/desktop/files/13090146/2023-10-23.desktop.production.log)
[2023-10-24.desktop.production.log](https://github.com/desktop/desktop/files/13090147/2023-10-24.desktop.production.log)

### Screenshots
![image](https://github.com/desktop/desktop/assets/44044548/9c2c3c23-0733-4190-a2ab-9f9c31128d19)
![image](https://github.com/desktop/desktop/assets/44044548/9f9b69f6-1331-4910-89bc-ca28212f82b5)
![image](https://github.com/desktop/desktop/assets/44044548/bbff5d53-1406-4610-aedc-56292d969a39)

**Comment by steveward** [comment]
@shunnnli thanks for the issue. I'm seeing a couple of errors in the log file. This is the first error that seems to indicate an access issue:

```
GitError: fatal: not a git repository (or any parent up to mount point /Volumes)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

Where is your repository stored on disk? I would try moving it to a standard location in your user folder to see if that helps. You mentioned moving the `.git` directory, which could also have caused this issue.

I'm also seeing a lock file error:

```
fatal: Unable to create '/Volumes/MICROSCOPE/Shun/Analysis/NeuroDAP/.git/index.lock': File exists.
```

This can normally be resolved by deleting the lock file and then attempting the Git operation again.

**Comment by shunnnli** [comment]
Thanks for the quick replay @steveward. I stored my repo on the server (which is accessed on my computer through /Volumes). Once I've connected+accessed the server I didn't see this issue again.

I've tried to delete index.lock multiple times, nothing work still after I've deleted it

UPDATE: I'm getting these two errors now constantly
Command failed: /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git log HEAD --date=raw --max-count=100 --skip=0 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color --

Command failed: /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 --

**Comment by steveward** [comment]
@shunnnli are you still encountering this error when working with GitHub Desktop?
