### ISSUE TITLE
Failed to execute installGlobalLFSFilter: UNKNOWN

### ISSUE THREAD

**Issue by lodhis2** [desktop/desktop#17617]
### The problem

issue with GitHub Desktop . The error appears when loading GitHub Desktop with a repo already active. We have also tried cloning a new repo, and any repo also gets a similar error message. It would also appear the Add local repository section of GitHub Desktop is non working (Choose and Add repository buttons do very little).

### Release version

Version 3.3.4 (x64)

### Operating system

Windows 11 Enterprise

### Steps to reproduce the behavior

1.Open GitHub Desktop

### Screenshots

![github](https://github.com/desktop/desktop/assets/148862099/44200455-2167-42a4-83e8-c49587108d98)

**Comment by lodhis2** [comment]
got resolve

**Comment by diego-mmg** [comment]
How did you solve this? I am having the same issue. It started randomly one day, and does not even go away after a fresh reinstall.

**Comment by sebastianompreis** [comment]
started appearing for me as well recently, reinstall does not help.
