### ISSUE TITLE
can't download github desktop

### ISSUE THREAD

**Issue by squeewy** [desktop/desktop#17624]
### The problem

i need to use github a lot and wanted to download the desktop version, but when i download the installer it does not work. van anyone help me?

### Release version

64 bit

### Operating system

windows 10

**Comment by steveward** [comment]
Thanks for the issue @squeewy. To get some more information about why the installation is failing it would be helpful if you could send over the log file that the Squirrel installer generates.

You should be able to find the log file here:

`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`

If no log file is being generated there you should be able to find one in the `SquirrelTemp` directory:

`%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

Please send that over as an attachment.

**Comment by squeewy** [comment]
[SquirrelSetup.log](https://github.com/desktop/desktop/files/13167972/SquirrelSetup.log)

**Comment by steveward** [comment]
I'm not seeing anything in the log file indicating why the setup is failing. Can you share some specific details about when the installation is failing? Are you running any security or antivirus software that could be preventing the installation?

**Comment by squeewy** [comment]
no im not, i only get this screen and then nothing happens

![image_2023-10-30_165432506](https://github.com/desktop/desktop/assets/145121904/f4a04e91-1379-4811-bb30-b3ad70660d44)

**Comment by steveward** [comment]
Can you see if Event Viewer is showing anything during the installation process?

**Comment by squeewy** [comment]
i dont see anything in the event viewer

**Comment by sergiou87** [comment]
Do you have any kind of antivirus that you can temporarily disable?

**Comment by squeewy** [comment]
no i dont, i only have what i have with windows

**Comment by steveward** [comment]
@squeewy apologies for the delay in getting back to you. Are you still unable to install GitHub Desktop? If so, I would recommend deleting the Squirrel Temp directory and then try installing again:

`C:\Users\<your-user>\AppData\Local\SquirrelTemp`

Let me know if that helps.

**Comment by Mikesalimon** [comment]
I have been trying to download GitHub on my desktop, but my web browser is unable to reach the page. what should be done in this regard?
