### ISSUE TITLE
The problem is that no one can see my projects on my GitHub account.

### ISSUE THREAD

**Issue by KantemirMirza** [desktop/desktop#17625]
### The problem

The problem is that no one can see my projects on my GitHub account.

### Release version

Version 3.3.4 (x64)

### Operating system

windows 10

**Comment by KantemirMirza** [comment]
You are marked as spam, and therefore cannot authorize a third party application.

**Comment by tsvetilian-ty** [comment]
@KantemirMirza thanks for the issue, but it doesn't look like it's related to GitHub Desktop.

You can check out [this discussion](https://github.com/orgs/community/discussions/67196) regarding your problem. 

I will close this issue!
