### ISSUE TITLE
Squash commit dialog box reappears when squashing with stashing

### ISSUE THREAD

**Issue by notxcain** [desktop/desktop#17627]
### The problem

When you have multiple changed files and you create a commit from some of them and then squash it with an existing commit, the app suggests you to stash the uncommitted changes, but after that the squash dialog reappears again.

### Release version

3.3.3 (x64)

### Operating system

MacOS 12.6.7

### Steps to reproduce the behavior

1. Create a commit (A)
2. Change two files
3. Commit changes in one of the files (B)
4. Squash A with B
5. A squash dialog appears
6. A stash dialog appears
7. The squashing happens
8. An empty squash dialog reappears

**Comment by sergiou87** [comment]
Thanks for your report! I was able to reproduce the issue, seems similar to this other one https://github.com/desktop/desktop/pull/16632 @tidy-dev fixed a while ago.
