### ISSUE TITLE
Pull Request on a renamed branch

### ISSUE THREAD

**Issue by Pauldro** [desktop/desktop#17626]
### The problem

If you have an already saved branch on remote let's say origin/pual

If you rename the branch locally to paul, then try to create a pull request from the desktop app, it will try to compare to the name from the local branch instead of what the branch name is on remote, so it will try to reference the pull request paul even though on remote that same branch is named pual

### Release version

3.3.4 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Create a branch (example pual) save push it to remote
Rename branch locally (example: paul) , you see on the fetch origin button it references the original branch name for the remote
Make commits
Push to remote
Create pull request

### Screenshots

![image](https://github.com/desktop/desktop/assets/5648224/88c05397-7b10-447d-8e7a-11039b0d0ca8)

Example of branch is renamed on local, and what the original branch name is on remote

![image](https://github.com/desktop/desktop/assets/5648224/7ed47753-e31e-46ce-8083-ac8ba8d559fb)
Example of when trying to create a pull request from that renamed local branch

**Comment by sergiou87** [comment]
Great catch! 💖 I was able to reproduce this bug, I will submit a PR with the fix, should be an easy one 😄
