### ISSUE TITLE
Undo button inside merge conflicts dialog not shown correctly

### ISSUE THREAD

**Issue by philipplentzen** [desktop/desktop#17622]
### The problem

Inside the dialog for merge conflicts, the undo button is not shown correctly on already resolved conflicts when the file path is very long.

### Release version

Version 3.3.4-beta3 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Resolve a merge conflict on files with long file paths

### Screenshots

![image](https://github.com/desktop/desktop/assets/29258187/7d56758f-8077-4b16-9cb9-4ab1c78d4513)

**Comment by sergiou87** [comment]
Thanks for your report @philipplentzen !! Please, update to the latest beta (3.3.5-beta1) because it should include the fix from https://github.com/desktop/desktop/pull/17596

Let me know if that works! 🤞
