### ISSUE TITLE
Locks up when exiting full screen. Stuck in full screen permanently.

### ISSUE THREAD

**Issue by bretthunity** [desktop/desktop#1762]
### Description

Locks up when exiting full screen. Stuck in full screen permanently.

### Version

**GitHub Desktop version:** 0.5.8

**OS version:** Microsoft Windows [Version 10.0.14393]

### Steps to Reproduce

1. Enter full screen
2. Exit full screen

**Comment by niik** [comment]
Hey @bretthunity, we're tracking this issue over in https://github.com/desktop/desktop/issues/1502 so please subscribe to that issue!
