### ISSUE TITLE
History Filter

### ISSUE THREAD

**Issue by KMastalerz** [desktop/desktop#17621]
### The feature request

Im a sucker when it comes to using UI, So i came to preffer using desktop application instead of command lines. 
One feature I would absolutely love is to have filters on History Tab

### Proposed solution

Add new block below selecting branch to compare for filters, Apply filters on history tab by: 

1. Author
2. Dates (Allow Range)
3. Phrase

**Comment by sergiou87** [comment]
We're tracking this kind of feature from https://github.com/desktop/desktop/issues/7022 so I will close this in favor of that issue

Thanks for your suggestion!
