### ISSUE TITLE
stashed changes are missing 

### ISSUE THREAD

**Issue by yekota-copart** [desktop/desktop#17632]
### The problem

Stashed changes are missed when restored.

### Release version

Version 3.3.4 (x64)

### Operating system

windows 11

### Steps to reproduce the behavior

I have changes in branch A
Clicked on change to branch B. branch A changes got stashed.
came back to branch A
made some changes in branch A even tough there are changes in branch A
fetched the latest code and it is showing conflicts
resolved conflicts
and clicked on restore stashed changes.
And BOOM. my changes are gone.
IT MADE ME LOOSE MY 2 HRS TIME.

### Log files

[2023-10-27.desktop.production.log](https://github.com/desktop/desktop/files/13187837/2023-10-27.desktop.production.log)

### Additional context

PLEASE FIX AS EMERGENCY. NEVER GONNA TRUST LOCAL AGAIN

**Comment by steveward** [comment]
Thanks for the issue @yekota-copart. If the stash was dropped it should be recoverable, see my [comment](https://github.com/desktop/desktop/issues/15912#issuecomment-1380608475) about this. I'm not seeing any dropped stashes in the log file you attached, though.

You can run `git reflog show --all` from the command line to include stashes in the reflog to see if it's recoverable from there. Let me know what that shows.
