### ISSUE TITLE
Broken Merge Conflict Window UI

### ISSUE THREAD

**Issue by kurttomlinson** [desktop/desktop#17638]
### The problem

The merge conflict window is not handling long filenames well. Long filenames push the "Open in Visual Studio Code" button off the edge of the window making it un-clickable in some circumstances.

### Release version

Version 3.3.4 (arm64)

### Operating system

macOS Ventura 13.5.2

### Steps to reproduce the behavior

1. Check out a branch that has merge conflicts with `master`.
2. Click "Branch" --> "Update from master".

### Screenshots

<img width="518" alt="Screenshot 2023-10-30 at 9 15 20 AM" src="https://github.com/desktop/desktop/assets/1914753/8f2af45a-1d1c-4de3-8e1d-cd51c09f0fab">

**Comment by sergiou87** [comment]
Sorry about that! We think that should've been fixed by https://github.com/desktop/desktop/pull/17596

We will get that fix out soon 🤞
