### ISSUE TITLE
Dropdown Ui bug during Rebase

### ISSUE THREAD

**Issue by ArslanAmeer** [desktop/desktop#17646]
### The problem

The Drop-down and Check icon are not appearing properly, they are squished. This happens when i am rebasing my branch and github appears to show conflicts.

### Release version

Version 3.3.4 (x64)

### Operating system

Windows 11 Pro

### Steps to reproduce the behavior

1. Rebase branch
2. On conflict notify dialog

### Screenshots

![image](https://github.com/desktop/desktop/assets/34485088/4ec5034c-197a-4b59-bf6d-26e5c70e857f)

**Comment by sergiou87** [comment]
Sorry about that! We think that should've been fixed by https://github.com/desktop/desktop/pull/17596

We will get that fix out soon 🤞

**Comment by ArslanAmeer** [comment]
@sergiou87  Thank You
