### ISSUE TITLE
Can't authenticate since 3.3.4

### ISSUE THREAD

**Issue by egorchikunov** [desktop/desktop#17655]
### The problem

Authentication doesn't work for me since upgrading to 3.3.4
I've tried reverting back to 3.3.3, it worked fine, but auto-upgrade bumped it right back.
3.3.5 and 3.3.6-beta.1 do not work either.

Trying to "check for updates" returns "The operation couldn’t be completed. Operation not permitted: Operation not permitted"
Trying to sign-in, after a succesful login into github, returns "Unable to fetch authenticated user"

I've already tried:
* Reinstalling
* Removing and creating a new ssh key
* Beta version
* Singing out of github and signing in again

Other Git GUI tools (GitKraken, SmartGit, WebStorm, VSCode) and terminal work fine.

### Release version

3.3.5

### Operating system

MacOS 14.0 m2

### Steps to reproduce the behavior

1. Go to "Github Desktop"
2. Open "Settings" -> "Accounts"
3. Press Sign in
4. Press Authorize in the broswer
5. See the error

### Log files

[2023-11-01.desktop.production.log](https://github.com/desktop/desktop/files/13229683/2023-11-01.desktop.production.log)

### Screenshots

<img width="583" alt="Screenshot 2023-11-01 at 17 53 54" src="https://github.com/desktop/desktop/assets/144012557/d446ea7f-7507-4d09-a97d-c2e69f224e31">
<img width="392" alt="Screenshot 2023-11-01 at 17 59 18" src="https://github.com/desktop/desktop/assets/144012557/2810caf7-32ad-49c0-9475-c22448934d19">

**Comment by niik** [comment]
Hey @egorchikunov, thanks for reaching out, sorry to hear you're having issues. Unfortunately the log file didn't prove to be helpful in troubleshooting this issue.

Could you try opening the Developer tools by selecting the "View" menu and "Toggle Developer Tools". Once opened try signing in again and see if the dev tools console provide any more insights as to why to requests are failing.

It seems even the SSH command is being prevented from accessing the network which isn't something I've seen before. Are you using any security software on your machine or a proxy, corporate management tools etc?

**Comment by egorchikunov** [comment]
So I turned on the dev tools, tried to sign in and it... worked?
I've even tried to sign out and sign in again, and everything seems to be working fine. 
Not sure if this is related to running with the dev tools, network changes or just a bizarre coincidence but it seems to be fixed after having this problem for over a week %)

Thank you!
