### ISSUE TITLE
Ask a feature for add more commit options

### ISSUE THREAD

**Issue by willser** [desktop/desktop#17665]
### The feature request

Hi team,
    I noticed there is `--amend` when I want to commit.But If I want to use other options like [--no-verify](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---no-verify),I have to use command line.Maybe I miss something,I did a search in this repository' issue page but got nothing and nor in desktop.If I miss something please ignore this issue.
    Thank you.

### Proposed solution

A input would be nice.People could type options they want and desktop append that to git command.

**Comment by steveward** [comment]
Thanks for the issue @willser. The option to bypass pre-commit hooks is being tracked in https://github.com/desktop/desktop/issues/9351, so I'm going to close this out. You can follow along there for updates.
