### ISSUE TITLE
Multiple selection for basic executions

### ISSUE THREAD

**Issue by DevDyna** [desktop/desktop#17678]
### The feature request

Many times i fall on same situation : ignore many files with differents directories and i need to add it one by one on git ignore

### Proposed solution

A simple solution that can be very usefull on this case was adding a "button executor" that execute same command at all selection example multiple "add to gitignore"

**Comment by DevDyna** [comment]
i didn't see that if i press ctrl+ click i can select multiple files...

**Comment by DanielYamini** [comment]
Unsubscribe
