### ISSUE TITLE
Scrollbars appear in diff view with large blocks of whitespace

### ISSUE THREAD

**Issue by Repiteo** [desktop/desktop#17672]
### The problem

Diffs containing *huge* blocks of whitespace now cause a scrollbar to appear for the affected line. This is in contrast with the website's expected behavior of truncating the whitespace visually, but still letting it persist for purposes of copying. Admittedly, don't know if the website has a perfect implementation (highlights trail over), but I believe it's preferable to the scattered scrollbar solution we currently have.

### Release version

Version 3.3.5 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

I'm not 100% sure what makes the scrollbar appear, as it won't necessarily happen for just any large block of whitespace. With that said, after some testing, my best guess from local testing is **176** characters of whitespace (for some reason). In the repo I realized this was happening in, this was as large as the window could get before the scrollbar disappeared for this specific line.

![23-11-03 10-23-09 GitHubDesktop](https://github.com/desktop/desktop/assets/17489292/f51f02b9-08f3-49b9-9969-898c46fac008)

Notably, the trailing slash still drops as expected. The line in question was:

```cpp
public:                                                                                                                                                                                \
```

### Log files

Not applicable.

### Screenshots

GitHub Desktop behavior:

https://github.com/desktop/desktop/assets/17489292/75e8be8a-1fa4-46d1-87e8-1623a562eebd

Website behavior:

https://github.com/desktop/desktop/assets/17489292/50545037-863a-408d-849b-f2765c304c6f

### Additional context

Potentially a minor regression from #17428

**Comment by sergiou87** [comment]
Hey @Repiteo ! Thanks for your report, but I'm unable to reproduce the issue on macOS nor Windows, using both the latest production and beta versions, it never shows the scrollbar and it works as the website.

Is there anything special about your setup like your display's DPI or scaling…?

**Comment by DanielYamini** [comment]
Unsubscribe
