### ISSUE TITLE
> I had this issue using `pnpm` as the package manager in one of my git repos. I added `C:\Program Files\Git\usr\bin` which contains `cygpath.exe` to my `PATH` environment variable, and that resolved the issue.

### ISSUE THREAD

**Issue by sathish099** [desktop/desktop#17677]
> I had this issue using `pnpm` as the package manager in one of my git repos. I added `C:\Program Files\Git\usr\bin` which contains `cygpath.exe` to my `PATH` environment variable, and that resolved the issue.

Yes it is working. but it takes more time a single line of code! why? @meena-erian

_Originally posted by @SATHISH099 in https://github.com/desktop/desktop/issues/10326#issuecomment-1793422305_

**Comment by DanielYamini** [comment]
Unsubscribe

**Comment by sathish099** [comment]
yeah! your are right. but when push the commit it took long time to pushing a commit around single line of code I tested.[7min]

I think it should be formatting everything and every pushing commit why?
