### ISSUE TITLE
@sjorford thanks for the issue. Is your local disk nearly full? That would definitely cause this issue, but unfortunately there isn't much we can do from our end for cases like this. We try to keep our installation size as minimal as we can, and we are tracking opting out of auto-updates in https://github.com/desktop/desktop/issues/3410 if you'd like to follow along there.

### ISSUE THREAD

**Issue by T0o0ZfEEk0** [desktop/desktop#17676]
@sjorford thanks for the issue. Is your local disk nearly full? That would definitely cause this issue, but unfortunately there isn't much we can do from our end for cases like this. We try to keep our installation size as minimal as we can, and we are tracking opting out of auto-updates in https://github.com/desktop/desktop/issues/3410 if you'd like to follow along there.

I'm going to close this out, but let me know if you have any further questions.

_Originally posted by @steveward in https://github.com/desktop/desktop/issues/17667#issuecomment-1792597449_

**Comment by DanielYamini** [comment]
Unsubscribe it

**Comment by DanielYamini** [comment]
Unsubscribe
