### ISSUE TITLE
Errors for push/pull on an unpublished branch

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1767]
1) We should disable the `pull` menu item while a repo is unpublished as it produces a console `no remotes` error, and cannot be used anyhow by the user.

<img width="1125" alt="screen shot 2017-05-25 at 8 44 37 am" src="https://cloud.githubusercontent.com/assets/14828183/26450944/d3b884fc-4127-11e7-9180-5a64862e7ac9.png">

2) Similarly, if a commit is made but unpublished, with dotcom the recipient of the repo, we should disable the user from the `push` menu item, as it can result in them selecting the Enterprise tab. This results in two errors, an `unsafe user agent` error and an aborted `SSL handshake` as the repo is eventually published to Enterprise despite being committed to dotcom.

<img width="1118" alt="screen shot 2017-05-25 at 8 46 20 am" src="https://cloud.githubusercontent.com/assets/14828183/26450985/0387f35c-4128-11e7-89ac-62aab6e9067a.png">
<img width="1123" alt="screen shot 2017-05-25 at 8 48 27 am" src="https://cloud.githubusercontent.com/assets/14828183/26450986/038ad536-4128-11e7-848e-a442392b5395.png">

v 0.5.8, OSX 10.11.5

Reproduce:
- Sign in a dotcom and Enterprise user
- File > new repo, with Read Me
- Initial commit should show in Changes, with dotcom as default
- Select Push from menu
- Choose Enterprise

Logs empty.

**Comment by shiftkey** [comment]
> 1) We should disable the `pull` menu item while a repo is unpublished as it produces a console `no remotes` error, and cannot be used anyhow by the user.

Same as #1448 and this will be fixed in #1764.

> 2) Similarly, if a commit is made but unpublished, with dotcom the recipient of the repo, we should disable the user from the `push` menu item, as it can result in them selecting the Enterprise tab. 

I _think_ this is covered by #1764 (disable the `push` menu item for unpublished branch) but the steps here are a bit unclear - does triggering a `push` from the menu show the Publish dialog somehow?

> This results in two errors, an unsafe user agent error and an aborted SSL handshake as the repo is eventually published to Enterprise despite being committed to dotcom.

The `aborted SSL handshake` message here is interesting, and my psychic debugger is curious whether there's something in between, like a proxy, that's mucking with the handshake process. But I think that's separate to the rest.

**Comment by tierninho** [comment]
Thanks for the update on the potential fixes.

> does triggering a push from the menu show the Publish dialog somehow?

Yes, the Publish modal appears.

**Comment by shiftkey** [comment]
> Yes, the Publish dialog appears.

Alright, that's hella confusing, but we should be blocking that as part of #1764.

Anything else in this issue you want to focus on?

**Comment by tierninho** [comment]
Nope, all good 👍
