### ISSUE TITLE
Mailnet

### ISSUE THREAD

**Issue by Adidasuz** [desktop/desktop#17681]
### The problem

Mail.net app ochilishini istaganlar bormi @

### Release version

Net

### Operating system

8

### Steps to reproduce the behavior

App

### Log files

App net mail

### Screenshots

A1b2s3

### Additional context

@adidasuz
 net mail app

**Comment by DanielYamini** [comment]
Unsubscribe

**Comment by DanielYamini** [comment]
Unsubscribe
