### ISSUE TITLE
Desktop keeps opening VS Code when clicking on files in the changelist

### ISSUE THREAD

**Issue by emmadesilva** [desktop/desktop#17685]
### The problem

After a recent update, I can barley work with the file changelist (which is 90% of why I use GitHub Desktop) without it opening VS Code. I think this happens when I double click, but it feels like it happens quite randomly as well. 

Edit: I just observed a file being opened after alt-tabbing to Desktop. So it definitely does not only happen with double clicks.

It would be great if we could get a setting to disable this as it's quite distracting to my workflow.

### Release version

Version 3.3.5

### Operating system

Windows 10

**Comment by DanielYamini** [comment]
Unsubscribe

**Comment by steveward** [comment]
Thanks for the report @caendesilva. I tested this out on Windows and was unable to reproduce this issue. Any chance you have single-click set to open on Windows?

If you could share a short recording of this behavior that would be helpful as well.

**Comment by emmadesilva** [comment]
> Thanks for the report @caendesilva. I tested this out on Windows and was unable to reproduce this issue. Any chance you have single-click set to open on Windows?
> 
> If you could share a short recording of this behavior that would be helpful as well.

I've also on Windows. I don't see single-click anywhere on the settings for Desktop. I since the issue is quite random I don't think I'll be able to get a recording of it. However, double clicking on a filename in either of these areas screenshotted open up the file in Code, however I'm not sure if that's related to the issue of them randomly opening.

![image](https://github.com/desktop/desktop/assets/95144705/fca8bfe3-7c18-48c1-b95f-2d609883f8cc)
![image](https://github.com/desktop/desktop/assets/95144705/8e8f0cf7-60f2-4bf8-9d3f-1065236fbc22)

**Comment by steveward** [comment]
Apologies, I should have clarified that the single-click option is a system `Mouse` setting for Windows. Some searching also seems to indicate that that having a low double-click speed can also sometimes cause issue with single-clicks being registered as double-clicks.

We haven't heard any other reports of this, so it seems like a system-specific issue. I'm going to close this out for the time being, but if you're able to consistently reproduce it we can look into this further.

**Comment by emmadesilva** [comment]
Hey again @steveward! I think I have localized the issue that makes this feel random. The problem seems to be that the double click register does not take into account the file clicked. If you click *anywhere* in the Desktop window, and then on a file on the changelist, the file will open in the editor. This also happens when the first click is to stage changes, or even when you click to focus the window. I think the presumed behaviour would be that a file would only be opened if I double click *on that file*, not on somewhere else, and then the file. I think the fix would be to make sure that the open action only gets called when you both clicks in a double click are on the file entry.

https://github.com/desktop/desktop/assets/95144705/e0ed24a0-f45e-4585-8e62-74c03e23fcc2

**Comment by rusXL** [comment]
I have the same issue. It is very annoying

**Comment by emmadesilva** [comment]
> I have the same issue. It is very annoying

@steveward Can we reopen this?

**Comment by GTechMicah** [comment]
Something similar seems to be happening for me on the latest release, I'm clicking around github desktop and suddenly when I click on a file in the file lists it opens, i've used github desktop for a while and I've never had this happen before.

**Comment by Intoprelised** [comment]
This has happened to me for half a year it is beyond annoying

**Comment by GTechMicah** [comment]
> Something similar seems to be happening for me on the latest release, I'm clicking around github desktop and suddenly when I click on a file in the file lists it opens, i've used github desktop for a while and I've never had this happen before.

Never mind, I think it was an issue with my mouse double-clicking instead of single clicking
