### ISSUE TITLE
Lapce to be added as an editor

### ISSUE THREAD

**Issue by rowanfr** [desktop/desktop#17684]
### The feature request

Lapce is an editor which satisfies the requirements for an external editor laid out [here](https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md). It should be added to the list of external editors to enable easy integration with "Open External Editor".

### Proposed solution

The solution would be to add Lapce to the list of external editors by following the guide laid out [here](https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md).
The relevant information for Windows is:
The GUID is: `392AA50E-C04B-4B05-A8C7-215A7DDAF46A`
It's stored within: `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{392AA50E-C04B-4B05-A8C7-215A7DDAF46A}`
DisplayName: `Lapce`
Publisher: `Lapce`

The InstallLocation is blank in the registry but it's by default installed in: `C:\Program Files\Lapce\` as `Lapce.exe`

### Additional context

It is a fairly new editor that is still under development but at this point it is functional enough to warrant integration and seems to have a bright future as a faster alternative to vscode.

**Comment by DanielYamini** [comment]
Unsubscribe

**Comment by steveward** [comment]
GitHub Desktop now provides support for [adding custom editors](https://docs.github.com/en/desktop/configuring-and-customizing-github-desktop/configuring-a-default-editor-in-github-desktop?platform=windows#configuring-a-custom-editor), so you can add Lapce by following the steps in that linked help article. I'm going to close this out.
