### ISSUE TITLE
Diff pane remains empty for changed and moved files before commit

### ISSUE THREAD

**Issue by joegoerlich** [desktop/desktop#17696]
### The problem

When I change and rename/move files GitHub Desktop does not always recognize this. Once I stage the changes in VS-code, GitHub Desktop starts showing those files as moved (blue-arrow-right icon) but the diff pane says 'The file was renamed but not changed'. 
After I commit the changes and display the commit in the history, the diff pane shows the changes.

### Release version

Version 3.3.5 (arm64)

### Operating system

macOS

### Steps to reproduce the behavior

1. Change a file and rename or move it.
2. Display the changes in GitHub Desktop.
3. Stage the files in VS-Code.
4. Display the changes in GitHub Desktop.
5. Commit the changes in GitHub Desktop.
6. Display the changes in the commit history of GitHub Desktop.

**Comment by steveward** [comment]
@joegoerlich thanks for the issue. I wasn't able to reproduce any issues with rename detection. How are you renaming/moving the files? 

If you want Git to properly track the renames then I would recommend using the `git mv <old_filename> <new_filename>`.

**Comment by joegoerlich** [comment]
@steveward you're right, my issue is caused by renaming files in the explorer pane of VS-code. I could reproduce that. I will check if this situation can be omitted by using a 'git mv' extension for VS-code.

**Comment by joegoerlich** [comment]
@steveward you're right, my issue is caused by renaming files in the explorer pane of VS-code. I could reproduce that. I will check if this situation can be omitted by using a 'git mv' extension for VS-code.
