### ISSUE TITLE
Commit Date is not showing

### ISSUE THREAD

**Issue by kavinda-inusha** [desktop/desktop#17690]
### The problem

​
​I want to report one more issue related to the latest version of Git Desktop 3.3.5. 

Not seeing the exact date of the commit, seeing **** ago.

It's not user friendly and showing date is must need functionality.

### Release version

3.3.5

### Operating system

Windows

### Screenshots

![Screenshot 2023-11-06 211843](https://github.com/desktop/desktop/assets/4889716/fcf8e141-1b12-4bd5-8067-330ed36235e2)

**Comment by steveward** [comment]
@kavinda-inusha you can hover over "x days ago" to view the exact timestamp of the commit. I hope that helps!

**Comment by kavinda-inusha** [comment]
Hi @steveward  - ​Is there any way to make the date always visible without hovering ?

**Comment by steveward** [comment]
Not at this time, but this was requested in https://github.com/desktop/desktop/issues/14611 if you would like to follow along for updates.
