### ISSUE TITLE
The app ignores “Tab size preference” setting

### ISSUE THREAD

**Issue by Const-me** [desktop/desktop#17700]
### The problem

There’s a setting on github.com which says “Tab size preference”.
I have changed it to 4.

However, your Windows software ignores the setting, and there’s no local preference to change it.

You should either respect my preference I have set on github.com, or expose a local-only setting in the desktop app.

### Release version

Version 3.3.5 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Open web browser
Navigate to github.com and login.
Go to https://github.com/settings/appearance, change the value to 4.
Install the desktop app, and commit a change in a file which uses tabs for indentation.

Expected result: tab size = 4
Actual result: tab size = 8 which is way too wide, only usable on large 4k display.

**Comment by steveward** [comment]
Thanks for the issue @Const-me, work is being done in https://github.com/desktop/desktop/pull/17469 to allow for changing the tab size. I'm going to close this out.
