### ISSUE TITLE
unable to commit submodules changes from superproject

### ISSUE THREAD

**Issue by gencer** [desktop/desktop#1770]
### Description

Cannot commit & push submodule changes. I can only commit after I commit submodule separately before committing on superproject. Otherwise, an error below is thrown.

### Version

**GitHub Desktop version:** 0.5.8
**OS version:** Windows 10 (1703) x64

### Steps to Reproduce

1. Change something in your submodule and open GitHub Desktop
2. You will see the change as `{SHA1}-dirty`.
![image](https://cloud.githubusercontent.com/assets/1711576/26461037/520e3a02-4184-11e7-8409-d2413c58a287.png)
3. Click on Commit
![image](https://cloud.githubusercontent.com/assets/1711576/26461047/58a465c6-4184-11e7-9ed4-baac5cde302e.png)

**Expected behavior:** Should commit my changes as usual **with** submodule.

**Actual behavior:** `Commit failed - exit code 1 received` given.

**Reproduces how often:** Always

### Logs

No informative logs. (No logs for this case)

#### Additional Information

If I commit changes in submodule before committing on superproject then GitHub Desktop is able to push and/or commit changes. While submodule is already synced, it no longer dirty. At this point I can commit to superproject.

So, If I manually commit & push on submodule:

![image](https://cloud.githubusercontent.com/assets/1711576/26461084/7c5c669e-4184-11e7-8a9a-4638bd75295a.png)

Now I can commit this together with superproject.

**Comment by Dreaddisk** [comment]
Hi. I have the same problem. But I was reading your Additional Information, I don't know how to do anything of the sort. Could you or anybody please, explain this for dummies?

**Comment by AdamBebko** [comment]
I'm having the same problem

**Comment by Zeterro** [comment]
I'm having the same issue, my project is a Unity Project.

**Comment by plyoung** [comment]
Same problem here in version 1.4.3.
I would expect automatic handling of the sub-module when committing and pushing the main.

**Comment by cisne** [comment]
Experiencing the same issue here

**Comment by EliasBu** [comment]
I've got the same problem.

**Comment by tomkivlin** [comment]
+1

**Comment by BeyondEarthRP** [comment]
+1

**Comment by tdm1223** [comment]
I've got the same problem.

**Comment by CarlosOnline** [comment]
+1

**Comment by EwoutH** [comment]
+1, same issue.

**Comment by jjehl** [comment]
+1

**Comment by brianlagunas** [comment]
Same problem

**Comment by jjehl** [comment]
After som investigation, in my case it is not a problem. It is the way git works. You should have your module AND your submodule define in github desktop. And you should :
1 - Commit your change in your submodule
2 - Commit the change in the link to the submodule from your top projetct.
It is the way it works with git, so the same wiwth github. 
The definition of the submodule in github is NOT done automatically, you have to define the repo of your sub module in addition with your top project.

**Comment by sp-stuart-harrison** [comment]
+1 for this - please address it soon! 🥳

**Comment by jjehl** [comment]
> +1 for this - please address it soon! 🥳

Have you really add your submodule in your module in github desktop ? You should replace the file with the files of your submodule, if not, github desktop can not know where is your submodule. The dirt-commit is totally a normal bahaviour with submodule, meaning your submodule is not commit so you can not commit the module...

**Comment by sgbaird** [comment]
Per jjehl's comment, by adding the submodule as a GitHub Desktop repository (Ctrl+O, navigate to submodule directory, "Add repository"), the changes can be committed (and pushed) there. I already had followed some of the suggestions [here](https://git-scm.com/book/en/v2/Git-Tools-Submodules) such as doing `git checkout master` (working directory as submodule directory), and `git config push.recurseSubmodules on-demand`, which may or may not be necessary for you. You can access the git bash terminal to enter these commands via `Ctrl+``

**Comment by sgbaird** [comment]
> Per jjehl's comment, by adding the submodule as a GitHub Desktop repository (Ctrl+O, navigate to submodule directory, "Add repository"), the changes can be committed (and pushed) there. I already had followed some of the suggestions [here](https://git-scm.com/book/en/v2/Git-Tools-Submodules) such as doing `git checkout master` (working directory as submodule directory), and `git config push.recurseSubmodules on-demand`, which may or may not be necessary for you. You can access the git bash terminal to enter these commands via `Ctrl+(backquote character)` Ctrl+`

Using a new computer now, and when I try to pull the top-level which has changes at the submodule level, the submodule keeps going to a detached HEAD state.. However, the `--remote` flag in `git submodule update --remote --merge` is apparently not supported in GitHub Desktop.

**Comment by sergiou87** [comment]
We've made a few improvements in this regard in #15176 

We hope that's enough for most cases! If not, we'll gather feedback again with this new experience and work on top of that 😊
