### ISSUE TITLE
Option to always display commit date and time in History list

### ISSUE THREAD

**Issue by HughWarrington** [desktop/desktop#17702]
### The feature request

Currently, the History panel shows commit dates in an approximate, prose description, like "yesterday" or "14 months ago".

The actual commit date/time can be found by hovering the mouse over the approximate description.

This makes certain kinds of task very slow: for example, the task I have just been trying to solve in a busy repository: 'find the first commit made on October 10th 2022'. I have to do some kind of binary chop hovering the mouse over many of the approximate descriptions.

In fact, the approximate date/time descriptions are never useful to me. I'm speculating that they exist to help people who work in a context where one developer might say "check that commit I made two days ago". But I work on a team with members in many timezones, so there is no common point of reference for what "yesterday" etc means.

I would like an option to always display the full commit date and time in the History panel, instead of the approximate textual description.

I think there is some support for this in the comments on #5395.

### Proposed solution

Add an option to always display commit date and time in the History list.

Or simpler, just always show the full date/time in this view, and get rid of the approximate description entirely. But I suppose since the decision was made to show the date/time in its current 'approximate' form, the authors might have established that some people prefer it this way.

**Comment by chrisdlee1** [comment]
The full date would be much preferred for myself as well. Vague terms contain less information than the actual date and uses as much space or more, I don't see the point.

**Comment by steveward** [comment]
Thanks for the issue @HughWarrington. In the interest of keeping our issue list consolidated I'm going to add this to https://github.com/desktop/desktop/pull/17469, which is an existing issue tracking this request.

**Comment by HughWarrington** [comment]
> Thanks for the issue @HughWarrington. In the interest of keeping our issue list consolidated I'm going to add this to https://github.com/desktop/desktop/issues/14611, which is an existing issue tracking this request.

Hi @steveward, I think you might have put in the wrong ticket number, as that looks like an unrelated issue?

**Comment by steveward** [comment]
Apologies, https://github.com/desktop/desktop/issues/14611 is the correct one.

**Comment by HughWarrington** [comment]
OK, that other ticket requests four or five different things, including one change that was already put forward, implemented but rejected at the PR stage ([14754](https://github.com/desktop/desktop/pull/14754)). Seems to me this ticket is smaller, more focused, doesn't contain a rejected idea, and therefore should be preferred.

**Comment by aicam** [comment]
Any update on this feature?

**Comment by chodorowicz** [comment]
Finding a PR from a specific date is quite cumbersome with those vague dates. 😬

**Comment by tksuoran** [comment]
"committed 2 weeks ago" is _the most useless thing_ in github. The exact date is what I need. Please fix. Thanks.

**Comment by Devanshjain2110** [comment]
git show --no-patch --format=%ci {commit}

This command should help for someone who needs this urgently. 

P.S : - I would also appreciate the above feature

**Comment by hmChris** [comment]
please please please stop with last week, 2 weeks ago, etc.  Use the date!

**Comment by avgojzack** [comment]
git show --no-patch --format=%ci {commit} only works for commits, not all the various other dates shown on Github (PR approval,  merge, etc)

**Comment by ratnikov** [comment]
I ran into this, but seems like hovering over the "2 weeks ago" gives you the actual date: 
<img width="1018" alt="Screenshot 2024-08-05 at 9 13 39 AM" src="https://github.com/user-attachments/assets/acaf8e88-9cdf-4e85-b2fe-6bc7aed703bc">

Hopefully that work around is good enough (it's good enough for me).

**Comment by steelbytes** [comment]
come on ... it's been [insert unspecified amount of time here] that this has been driving me nuts.

**Comment by steelbytes** [comment]
although us coders are trying to do precise work, github doesn't want to give us precise tools.    :face_palm:

**Comment by chandrapol** [comment]
Instead of `5 weeks ago`, I would prefer exact date.

**Comment by alikazi-sonder** [comment]
I am regretting moving from Bitbucket to Github. Github is missing so many basic features like accurate date and time formats, automatic team allocation when creating Pull Request, automatic list of commits when creating Pull Request, authentication for third party access to repo is such a pain and so on. Horrible.

**Comment by mgussekloo** [comment]
I would really like exact dates in history as well.

**Comment by harrymattison** [comment]
please

**Comment by dutchdata** [comment]
seriously

**Comment by impishlucy** [comment]
Pathetic

**Comment by starkers** [comment]
so frustrated I can't just see when things happened, even just on the website..

<img src="https://media1.giphy.com/media/YDEiyrRLa6ATrSNQND/giphy.gif"/>

**Comment by attheshow** [comment]
Just adding a +1 for this request. 😊🏅

**Comment by pablott** [comment]
I also think this is an issue. And is not just in the history, but also in the commit view.
This does not really tell me much...
<img width="246" alt="Screenshot 2024-10-26 at 9 33 32" src="https://github.com/user-attachments/assets/3556435e-5415-4cb3-881b-f62b3d587e48">

**Comment by tluijken** [comment]
So, one of the actions/cache calls has failed us for a few days. Could you let me know if we did something in our repository which caused it, or a commit on the actions repo? But I'm not getting any further than version 4.1.2 was created somewhere last week, making it very hard to have a timeline of events leading up to this.

**Comment by jeffchensonos** [comment]
I need the exact date! Man, is it so hard to make this little change? Nobody ever listen!

**Comment by sadawespj** [comment]
Same here!!! If I could just hover over and see the exact timestamp, it would save me trouble!

**Comment by jeffchensonos** [comment]
Can someone escalate this?

**Comment by MuhammadSYahyaS** [comment]
From business perspective, this feature is really needed for accurate reporting of work history. Github should show exact date by default, or at least give us the option.

**Comment by eqperes** [comment]
Adding to the number of people that find this essential

**Comment by kaktooss** [comment]
I want to understand when the code was delivered to production, but i see "Released last week" which gives me a window of 7 days to guess. Could we please have a way to know when exactly that happened, i do not know - setting to display a date instead, pop-up window, hover tooltip, anything, please!

**Comment by ratnikov** [comment]
> I want to understand when the code was delivered to production, but i see "Released last week" which gives me a window of 7 days to guess.

Have you tried hovering over it? For me it renders the time stamp. (I still wish it renders it immediately, but it's clear that GitHub is not very interested in our opinion at this point).

**Comment by JosephDevlin** [comment]
Can we please get some traction on this surely very simple change. Both views have use but we need both.

**Comment by hiraditya** [comment]
the issue is closed but the issue is still there. hovering over all the comments is annoying. Ideally, I'd like to have a setting that allows me to see the exact date all the time. A typical use case for me is when re-requesting feedback. In the repo I contribute to it is typical to wait for a week before pinging the reviewers on a PR. It quickly becomes frustrating to hover over the comments to find out the exact date.

**Comment by attheshow** [comment]
You're right about this issue being closed for some reason. I noticed that one of the other cross-linked issue that's essentially the same request is also tagged as "not planned." Maybe @steveward who closed the issue might be able to comment as to why? 🙏

**Comment by michaelstrupp-wexinc** [comment]
Having to hover over each time entry ("2 days ago") to see a precise timestamp doesn't allow one to quickly scan a series of commits or actions to get a sense of the chronology. Honestly,  GitHub, does _anyone_ prefer "2 days ago"?

**Comment by Hayder-Sobrinho** [comment]
Dear god, nothing yet!!!!!

**Comment by tallneil** [comment]
Please use real dates and times for PRs

**Comment by qneill-sifive** [comment]
Hi GitHub people.  Please add an option to allow 
### Showing TimeStamps in the UI as FULL UTC dates/times, with options to render in the browser timezone or in the commit timezone ...

**Comment by perryjaa** [comment]
Please use real dates and times!   The general descriptions like "1 month ago" is not useful.

**Comment by dphinazee** [comment]
+1 on this request, my company creates medical software and it is very important to us and the FDA to log dates. Making it always display and therefore be copiable would save us a great deal of time.

**Comment by DSDexheimer-DosedDaily** [comment]
+1, bump, etc... the current value is NOT helpful.

**Comment by dan-ih** [comment]
How does one get the full date when viewing from a mobile browser? you can't 'hover' to get the tooltip.

**Comment by elcilerdenbiri** [comment]
> How does one get the full date when viewing from a mobile browser? you can't 'hover' to get the tooltip.

Once up on a time …: [galaxy s4 screen has hover](https://stackoverflow.com/questions/16666965/floating-touch-on-galaxy-s4)

**Comment by Nexesenex** [comment]
No one cares about "x days ago, y weeks ago, z months ago", when you can simply have the DATE!
Could you Github guys take this seriously, and use actual dates like EVERYONE, and i mean EVERYONE, is using?
This is exasperating.

**Comment by Koriagami** [comment]
+1 from me, in hopes for a better future

**Comment by serajahmad01** [comment]
+1

**Comment by iharzh** [comment]
+1

**Comment by FaroJoaoFaro** [comment]
+1
a simple option in the settings could toggle between showing the exact timestamp or the current "x days ago"

**Comment by Nexesenex** [comment]
I support this change to absolute date/time as well.

> +1 a simple option in the settings could toggle between showing the exact timestamp or the current "x days ago"

And so, those who like to reflect on "long ago" can keep it as it is, and those who like exact dates can have it their way.

**Comment by rickydazla** [comment]
A toggle/config option here would be most welcome! Every few months I check and sigh

**Comment by JamieS1211** [comment]
+1

**Comment by ceciliaccwei** [comment]
+1

**Comment by keefertaylor** [comment]
+1

**Comment by LalaDK** [comment]
+1

**Comment by HughWarrington** [comment]
Please, do not comment saying just '+1'. Every time you do that, you are spamming 50+ people. To show support you could 'like' the original issue report at the top of this page. Even that is unlikely to have any effect, since this ticket has been closed for two years and I doubt the Github dev team have the time to read discussions on closed tickets.

@steveward closed this ticket in favour of #14611, but wrongly in my opinion, since that other ticket is vague and mixes up multiple things. It might be better to open a new, focussed ticket. If you do that, you could mention that there is broad support for the change -- see #5395, #9147, #14611, #17456, #17690, #17702, #17828, #17976, #18136, #18273, #18442, #18443, #18959, #19154, #19469, #19549.
