### ISSUE TITLE
Unable to find Visual Studio Code as an external editor

### ISSUE THREAD

**Issue by mfahadagri04** [desktop/desktop#17710]
### The problem

The only external editor option I have is Rstudio but I would like to use Visual Studio Code

### Release version

Version 3.3.5 (x64)

### Operating system

Windows 10

### Screenshots

![image](https://github.com/desktop/desktop/assets/126353489/92a01c5c-3c71-43f0-b69c-a43af766dac0)

**Comment by tsvetilian-ty** [comment]
@mfahadagri04 thanks for the issue. Visual Studio Code is one of the supported external editors. If you don't see it in the dropdown, please make sure you install it through the [installation executable](https://code.visualstudio.com/). 

Perhaps, it is possible not to see it if you're using a portable version or version installed through Windows package managers.

**Comment by Uimun** [comment]
Hello @tsvetilian-ty, I saw your pull request related to exploring external editors. I'm working with an external drive editor and I need a copy of your work. If you don't mind, can I download the program version of #14843?

**Comment by tsvetilian-ty** [comment]
The code committed to GitHub Desktop is under [MIT license](https://github.com/desktop/desktop/blob/development/LICENSE), so it's ok :) 

Let's not spam this issue, please!

> [!NOTE]  
> If you decide to build from #14843 , beware that all points @tidy-dev make in [this comment](https://github.com/desktop/desktop/pull/14843#issuecomment-1534869242) are completely valid!

**Comment by steveward** [comment]
@mfahadagri04 if you installed VSCode while GitHub Desktop was will also need to restart GitHub Desktop for the editor to be detected. Let us know if that does not get things working and we can investigate further!
