### ISSUE TITLE
branch default > A > B, switch to B, update from branch could offer "from A"

### ISSUE THREAD

**Issue by i-make-robots** [desktop/desktop#17713]
### The feature request

Branch default > A > B.  later, update A from default.   
When I update B it should be from A, but desktop only offers from default.

### Proposed solution

Offer the entire list of parent branches for update from.  leaves options open to other uses cases, solves my problem at the same time.

Thank you!

### Additional context

I'm working on a branch of Marlni 3D printer firmware.  the default I use is bugfix-2.1.x.
I make a branch, bugfix-2.1.x-polargraph.  Then I make another from that, bugfix-2.1.x-m5 (specific config files for one machine).
Recently I update from upstream and apply changes to -polargraph.  Now I want to bring -polargraph changes to -m5.  but github desktop only offers "update from bugfix-2.1.x".  I would have to go to the github website and change the default branch to alter this value and that feels really wrong.  Like "I must be doing this wrong" wrong.

**Comment by steveward** [comment]
@i-make-robots thanks for the issue. You can merge changes from any branch by going to `Branch` > `Merge into Current Branch`. You'll see a list of your branches. The `Update from default branch` option is intended to allow for a quick way to get a feature/topic branch up-to-date with the default. If you have any other questions let me know!
