### ISSUE TITLE
META Files

### ISSUE THREAD

**Issue by Blazzer10200** [desktop/desktop#17718]
### The problem

Hello, I run my own FiveM it's very important that all files transfer safley over to the vps using github desktop and github browser to make it happen. It will fetch all file name such as LUA files but when it transfer over files that are in META Formate github desktop does not detect that file formate I am very confused please help.

### Release version

3.3.5

### Operating system

Windows 11

### Steps to reproduce the behavior

1. fetch origin 
2. does not pull META files but everything else it will pull

### Screenshots

![image](https://github.com/desktop/desktop/assets/121213450/5d2c95b8-e754-41a9-98a4-6af3b991964c)

![image](https://github.com/desktop/desktop/assets/121213450/8497c7a1-35d5-4d10-935a-32dba1ad04b9)

**Comment by steveward** [comment]
@Blazzer10200 thanks for the issue. Does your repository contain a `.gitignore` file? You mentioned fetching, but I'm unsure if you're expecting changes to be appearing. If the meta files are being ignored it would cause the changes to not appear in GitHub Desktop.

You can check your `.gitignore` by going to `Repository` > `Repository Settings` > `Ignored Files`.

**Comment by Blazzer10200** [comment]
Hello, when it comes to GitHub I’m not the smartest rock in the box but I
can sure check when I am home I will let you know soon as possible!

**Comment by Blazzer10200** [comment]
I am in the settings of my repositories but I cannot find the Ignored Files that you are talking about. like I said im the smartest when it comes to this type of stuff sorry if i confuse you.
![image](https://github.com/desktop/desktop/assets/121213450/57a15c4a-7532-4642-96cf-a1a55a4abc5f)

**Comment by steveward** [comment]
Apologies, you can check this directly in GitHub Desktop by going to Repository > Repository Settings > Ignored Files.

<img width="666" alt="Screenshot 2023-11-13 at 1 21 12 PM" src="https://github.com/desktop/desktop/assets/721500/55afaffa-03e6-4412-8cf3-b69817602233">

**Comment by Blazzer10200** [comment]
It seems my clothing pack for mys server had some META Files in it and back then I might have clicked ignore all META Files could I just stash the clothing pack and it will be ignored that way ?

**Comment by Blazzer10200** [comment]
Success! I have got it to work thanks to you, thanks for the support man!

**Comment by steveward** [comment]
I'm glad to hear things are working now! I'm going to close this out.

**Comment by Blazzer10200** [comment]
Awesome, thank you so much!

**Comment by Blazzer10200** [comment]
Hello, sorry for bothering you again is it possible to add a folder to the folder that is linked to github desktop and github desktop does not detect it ?

**Comment by steveward** [comment]
Git does not track empty directories -- does the folder have files in it?

**Comment by Blazzer10200** [comment]
It has files in the folder but the files are extremely large and I don't want them to upload to the github if that makes sense I could send photos for example

**Comment by Blazzer10200** [comment]
Sorry this is very difficult to explain

**Comment by Blazzer10200** [comment]
So here my repository 
![image](https://github.com/desktop/desktop/assets/121213450/5e77dacf-bfd7-4070-8615-2bdd3dd746ce)

I have all my assets in here, they are all uploaded via github desktop

Here inside [cosmic]
![image](https://github.com/desktop/desktop/assets/121213450/a7d425a9-4b74-4fad-b4dc-5f8e5ab36855)
I would like a folder called [clothing] for my clothing pack but I don't want to commit it or push it just want to keep it were it's at for example 

![image](https://github.com/desktop/desktop/assets/121213450/4633aa06-36aa-4e4a-ac60-b78fa8c7d0b3)

Is there an option for that ?

**Comment by steveward** [comment]
You can ignore that directory by adding it to the `.gitignore` file (you can edit that directly in GitHub Desktop). You would add this line:

`[clothing]/`
