### ISSUE TITLE
Remove git tag `release-7000`

### ISSUE THREAD

**Issue by TayouVR** [desktop/desktop#17716]
### The problem

automated tools like package managers use the git tags to find the latest release. 
For some reason there is a tag titled `release-7000`, which seems unintentional and incorrect. See: https://github.com/desktop/desktop/tags https://github.com/desktop/desktop/releases/tag/release-7000

I think that tag should be removed as there does not seem to actually be a version 7000 at all.

Related issue: https://github.com/ScoopInstaller/Extras/issues/12205

### Release version

release-7000

### Operating system

Windows (any)

### Steps to reproduce the behavior

1. install scoop (https://scoop.sh)
2. `scoop bucket add extras`
3. `scoop install github`

**Comment by tsvetilian-ty** [comment]
@TayouVR thanks for the report. I'm tagging @tidy-dev to check it out :)

**Comment by tidy-dev** [comment]
@tsvetilian-ty Thank you for the tag. Apologies for the erroneous tags, I was doing some UX testing and unintentionally pushed those. If those tags have been pulled to a local copy, feel free to delete them locally.

**Comment by TayouVR** [comment]
thank you! 

scoop users, who had the release 7000 installed need to manually downgrade to 3.3.5 (or any older version), not sure if this affected any other package managers.
`scoop install github@3.3.5`
