### ISSUE TITLE
i cant log in

### ISSUE THREAD

**Issue by Bas-jpg** [desktop/desktop#17722]
### The problem

i cant log in anymore, when i click on log in with browser it takes me to a white chrome screen and puts github desktop stuck on "sign in using your browser".
i also cant use github desktop to open a repository now for some reason.

### Release version

the latest

### Operating system

windows 11

### Screenshots

![Schermafbeelding 2023-11-14 111759](https://github.com/desktop/desktop/assets/143513561/eb6b6c34-cf0e-4726-8139-04fe66f4361d)

**Comment by steveward** [comment]
Thanks for the issue @Bas-jpg. Could you try temporarily switching your default browser on Windows to see if that resolves this issue?
