### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by KONETISUPRIYA** [desktop/desktop#17725]
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 8 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 368 bytes | 368.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.        
remote: error: GH006: Protected branch update failed for refs/heads/KONETISUPRIYA-patch-15.        
remote: error: Changes must be made through a pull request.        
To https://github.com/sure-trust/G11_SQL-PowerBI.git
 ! [remote rejected] KONETISUPRIYA-patch-15 -> KONETISUPRIYA-patch-15 (protected branch hook declined)
error: failed to push some refs to 'https://github.com/sure-trust/G11_SQL-PowerBI.git'

**Comment by steveward** [comment]
@KONETISUPRIYA thanks for the issue. Based on the error output it looks like you are trying to push to a protected branch. You will likely need to create a new branch and submit a PR against the protected branch, depending on how branches are configured for this repository. You may need to reach out to the user who is an admin of the org for further information. See [this article](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches) for more information on protected branches. 

I'm going to close this out, but let me know if you have any other questions about GitHub Desktop.
