### ISSUE TITLE
Changes are not updating

### ISSUE THREAD

**Issue by tharunquickride** [desktop/desktop#17723]
### The problem

fatal: unable to access 'https://github.com/idisha/QuickTaxiServer.git/': Failed to connect to github.com port 443 after 32210 ms: Couldn't connect to server

### Release version

latest version

### Operating system

windows 10

**Comment by steveward** [comment]
Thanks for the issue. Are you behind a proxy server? You can configure GitHub Desktop to work with a proxy by running the following command from the command line (you will need to [install Git for Windows](https://git-scm.com/download/win) if you have not already):

`git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`

Replace `proxyuser` with your proxy username and `proxypwd` with your proxy password. Also, `proxy.server.com:8080` needs to point to the URL of your proxy server.

Let me know if that doesn't get things working.

**Comment by tharunquickride** [comment]
Yes, Thank You
