### ISSUE TITLE
GitHub Desktop did not open the repository  IDE ( Visual Code)  

### ISSUE THREAD

**Issue by olgalis** [desktop/desktop#17724]
### The problem

When I crea te a new Repository and try to open it with "Open the repository in your external editor", I press the button "Open in Visual Code" and nothing happens. This issue I have already a few month. 

### Release version

Version 3.3.5 (x64)

### Operating system

Windows 10 Enterprise

### Steps to reproduce the behavior

1. Open a new Repository 
2. On the main Menu press the button "Open in Visual Studio COde "
3. Nothing happened 

### Log files

Error: spawn C:/Java/AdoptOpenJDK/jdk-15.0.2.7-hotspot/bin ENOENT
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_errnoException (node:internal/errors:620:12)
    at Process.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Version: 3.3.5
OS: Windows 10.0.19045

### Screenshots

![image](https://github.com/desktop/desktop/assets/87602024/ffc424e6-3504-4c6f-ad04-744d232a6189)

### Additional context

Visual Code version 

1.84 (1. November 2023)

**Comment by tsvetilian-ty** [comment]
@olgalis thanks for the report. Your issue looks similar to https://github.com/desktop/desktop/issues/14129 you can try a potential solution in [this comment](https://github.com/desktop/desktop/issues/14202#issuecomment-1072376656).
