### ISSUE TITLE
Ignore execution_count (And other misc. diffs) for jupyter notebooks.

### ISSUE THREAD

**Issue by NPap0** [desktop/desktop#17728]
### The feature request

I'm working with jupyter notebooks and github desktop. The issue is that when I change code and try to push with github desktop, upon checking diffs, I see diffs(lines) like execution_count which are different but they do not offer valuable information to me. Making it harder for me to see the code changes that matter.
I understand jupyter notebooks are json files at the lowest level but should there be a way to ignore those lines?

### Proposed solution

If it can't be generalized, what I'm essentially asking is:
Create a method to prevent the display of 'execution_count' in the diff panel of display diffs.

### Additional context

I'm attaching a screenshot as an example.
![image](https://github.com/desktop/desktop/assets/94050501/065756cc-02cf-4a2b-84d8-e250a6064a22)

**Comment by steveward** [comment]
Thanks for the issue @OneCodeToRuleThemAll. Better diffing for Jupyter notebooks has been previously requested in https://github.com/desktop/desktop/issues/12121. Using something like nbdime would allow for ignoring:

https://nbdime.readthedocs.io/en/latest/config.html#configuring-ignores

At this time we don't have plans to implement any type of custom diffing directly into the app, so I'm going to close this out. I'm sorry that I don't have better news.
