### ISSUE TITLE
Git Hub desktop and website wont sync 

### ISSUE THREAD

**Issue by Tippacanoe88** [desktop/desktop#17726]
My git hub desktop application wont sync password information, in order to push repos to their origin. This isnt the first time this issue has happened. Im hoping this is something that i am doing wrong that i can learn more about. But GHD has worked fine until it ended my session.

**Comment by tsvetilian-ty** [comment]
@Tippacanoe88 thanks for reaching out. Could you please fill out the issue form? This information from the form is important to catch or narrow down the issue, and it will be easier for someone to help you.
