### ISSUE TITLE
Push Origin in renamed branch

### ISSUE THREAD

**Issue by juanmiguel3801** [desktop/desktop#17736]
### The problem

Al dar click en push origin/renamed_branch se sube a origin/old_name_branch

### Release version

3.3.5

### Operating system

windows 10

**Comment by steveward** [comment]
Thanks for reaching out @juanmiguel3801.

I'm not sure I understand the issue -- can you share a few more details or screenshots of the issue you are experiencing?

**Comment by juanmiguel3801** [comment]
It's working now. It was my mistake, I think.
