### ISSUE TITLE
What was the last version of GitHub Desktop that supported Windows 7?

### ISSUE THREAD

**Issue by andrewdaviddeyoung** [desktop/desktop#17730]
I'm running Windows 7 Pro 64-bit, which I completely recognize it is no longer supported, either by GitHub or Microsoft.  **But I'd like to attempt installing GitHub Desktop on Windows 7 anyway (at my own risk).**

[This discussion](https://github.com/desktop/desktop/issues/17209) from a few months ago provides a link to the installer for GitHub Desktop 3.2.4. In [the discussion](https://github.com/desktop/desktop/issues/17209), [the contributor tidy-dev said that "the Electron upgrade that resulted in removing support for windows < 10."](https://github.com/desktop/desktop/issues/17209#issuecomment-1677203754)

Does anyone know when "the Electron upgrade" was introduced?  If so, is there any way I can download the installer for the version before that (which may or may not be 3.2.4)?

**Comment by sergiou87** [comment]
According to [our changelog](https://github.com/desktop/desktop/blob/5f3a2bb6c7e1db324ffb38045aed8c39e64da389/changelog.json#L252), it was 3.2.4 the version that removed support for older Windows versions, but AFAICT that's the version that disabled auto-updates for those older Windows versions.

The latest one that actually works on those is 3.2.6:
- GitHub Desktop 3.2.6 for Windows: https://github.com/desktop/desktop/releases/tag/release-3.2.6

I hope that works!

**Comment by gloeyisk** [comment]
> * GitHub Desktop 3.2.6 for Windows: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.2.6-de80a354/GitHubDesktopSetup-x64.exe
> 

The link is not working anymore. Do you've any mirrors?

**Comment by tidy-dev** [comment]
@gloeyisk We recently moved our storage so old download links won't work. But in conjunction, we added a page where you can find all past releases. https://desktop.githubusercontent.com/

**Comment by rjsdotorg** [comment]
I made the mistake of trying a new beta install on this Win7 machine and it not only failed, but it hosed the existing install.
Download of 
https://desktop.githubusercontent.com/releases/3.2.6-de80a354/GitHubDesktopSetup-x64.exe
and reinstall luckily brought it back.

**Comment by tidy-dev** [comment]
3.2.6 release page: https://github.com/desktop/desktop/releases/tag/release-3.2.6
