### ISSUE TITLE
Pycharm not recognised

### ISSUE THREAD

**Issue by Cedric-Ab** [desktop/desktop#17738]
### The problem

Pycharm is not recognised as external editor by GitHub Desktop.

However it was working before & I didn't change any settings on GitHub Desktop / PyCharm.. Any ideas why this happened suddenly?

same/similar to issue https://github.com/desktop/desktop/issues/15016

### Release version

Version 3.3.6-beta2 (x64)

EDIT: also in Version 3.3.6-beta3 (x64), same thing

### Operating system

Windows 10

### Screenshots

![image](https://github.com/desktop/desktop/assets/142994683/32a4dca7-4ab1-49f4-bcd0-477fb25c1dc0)

**Comment by steveward** [comment]
Thanks for the report @Cedric-Ab, I'll take a look and see if anything's changed that could have broken this.

**Comment by Cedric-Ab** [comment]
I just updated Pycharm CE on my laptop from 2023.2.4 I think to 2023.2.5 and now GitHub Desktop also suggests regular Pycharm that isn't CE, tho on my laptop I got the GitHub Desktop version 3.3.6-beta3.
![image](https://github.com/desktop/desktop/assets/142994683/eb968b85-de9c-4c91-99f7-d4099b60fca1)

**Comment by Cedric-Ab** [comment]
@steveward I reinstalled pycharm on 2023.2.5 via jetbrains toolbox and it didn't work, but reinstalling GitHub Desktop somehow resolved the error. 
So my main problem is now resolved, but the problem I have in the other comment isn't resolved yet.

**Comment by steveward** [comment]
I just tested this out and PyCharm is showing up as an option so I'm going to close this out.

**Comment by Sahin3892** [comment]
Hello,

i have the Same issue with pycharm 2024.2
my GitHub Desktop dont find it.
Can anybody Help me

**Comment by Cedric-Ab** [comment]
@Sahin3892 
Try reinstalling everything and also make sure that the folders pycharm was installed to are deleted

**Comment by Sahin3892** [comment]
> @Sahin3892 
> Try reinstalling everything and also make sure that the folders pycharm was installed to are deleted
> 
> 

I try it but its not working i dont know why.
I re installed Windows before i reinstalled i dont have any problems it was allways a Option

**Comment by Cedric-Ab** [comment]
> > Try reinstalling everything and also make sure that the folders pycharm was installed to are deleted
> 
> I try it but its not working i dont know why. I re installed Windows before i reinstalled i dont have any problems it was allways a Option
try this: 
![image](https://github.com/user-attachments/assets/f56e4f47-fb8d-410c-9ae2-b8a836f8bf5f)

seems like they added a way to make this not so much a problem anymore

**Comment by Sahin3892** [comment]
No i dont have this 
![image](https://github.com/user-attachments/assets/70e7dab9-ead0-41bf-a079-7a9ea1ce220f)

**Comment by Cedric-Ab** [comment]
@Sahin3892 
get yourself the beta

**Comment by Sahin3892** [comment]
![image](https://github.com/user-attachments/assets/de984663-2e38-41f1-b552-40973fb6148b)

now i have this but i cant choose

**Comment by Cedric-Ab** [comment]
@Sahin3892 maybe reselect it?

**Comment by Sahin3892** [comment]
I try but i cant i can only select Shell 
![image](https://github.com/user-attachments/assets/e7460fad-d51a-4087-82e4-824678af0ac9)

**Comment by Cedric-Ab** [comment]
@Sahin3892 
[#19162](https://github.com/desktop/desktop/issues/19162)
created a bug report for that

**Comment by Sahin3892** [comment]
Where can i report this ?

**Comment by Cedric-Ab** [comment]
@Sahin3892 
I already reported it for you, it would be under issues.

**Comment by Sahin3892** [comment]
Thank you

**Comment by Cedric-Ab** [comment]
@Sahin3892 
In the meantime download visual studio code so you then can select it properly?

**Comment by Sahin3892** [comment]
![image](https://github.com/user-attachments/assets/47a5a910-06e6-48aa-9558-9a893a9558f3)

That Workt with download visual studio code but i dont know why in my old windows version i dont have any problems
