### ISSUE TITLE
Managing Issues

### ISSUE THREAD

**Issue by okunamayanad** [desktop/desktop#17749]
### The feature request

Let people manage issues of repositories from GitHub Desktop.

### Proposed solution

This will help GitHub Desktop users to stay inside one designated app for their work. Opening a web browser to check Issues feels clunky and sometimes leads to loosing yourself in the web (like watching a *short* YouTube video.. we all know how this cycle continues.) 

### Additional context

After they downoad their repository from GitHub/upload their repository to Github, fill in the unused space next to "Fetch origin" with Issues tab.
![image](https://github.com/desktop/desktop/assets/108594296/f99d1faa-314f-4bbc-b205-267f751c9219)
*the screenshot was taken in the minimum width of the app*

**Comment by tidy-dev** [comment]
@okunamayanad Thank you for the suggestion. I will add your feedback to https://github.com/desktop/desktop/issues/8989 where we are tracking issues interaction with GitHub Desktop.
