### ISSUE TITLE
Can't authorize with right username and password!

### ISSUE THREAD

**Issue by O-Danylchuk** [desktop/desktop#17740]
### The problem

I was trying to clone repo and program asked me to authorize, what i did, but program said that authentification failed, but username and password was 100% right

### Release version

3.3.5

### Operating system

Fedora Linux 39

### Screenshots

![image](https://github.com/desktop/desktop/assets/145114504/f48912a4-2f1e-4d08-b96e-72fd72e6e1d3)

**Comment by steveward** [comment]
@O-Danylchuk we don't provide official support for the Linux fork, but you should be able to log in from the Preferences menu. That dialog is only for specific authentication methods. See https://docs.github.com/en/desktop/installing-and-authenticating-to-github-desktop/authenticating-to-github-in-github-desktop.
