### ISSUE TITLE
visual studio option is not available and only showing android studio option

### ISSUE THREAD

**Issue by sumithkumar123** [desktop/desktop#17743]
### The feature request

visual studio option is not available and only showing android studio option

### Proposed solution

visual studio option is not available and only showing android studio option

### Additional context

visual studio option is not available and only showing android studio option

**Comment by steveward** [comment]
Thanks for the issue @sumithkumar123 -- we're tracking Visual Studio support in https://github.com/desktop/desktop/issues/12946. Unfortunately there are some issues with integrating VS (see https://github.com/desktop/desktop/pull/13395#discussion_r757799482), but you can follow along for updates. We also have https://github.com/desktop/desktop/issues/7033 open which is tracking broader improvements to our editor integrations.

You can also use the `Open with Default Program` option from the file context menu to open files with the default system application. I hope that's helpful! I'm going to close this out.
