### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by brennanMKE** [desktop/desktop#1774]
### Description

In the native Mac version it was possible to copy the hash for a commit which is necessary for running some commands on the command-line for Git tasks which the desktop tool does not handle. The new React Native version does not allow for copying the hash.

### Version

**GitHub Desktop version:** 0.5.8

The operating system you are running on may also help with reproducing the
issue:

**OS version:** macOS Sierra 10.12.4

### Steps to Reproduce

1. View a repository in the desktop app
1. Select a commit in History
1. Try to select and copy the hash

**Expected behaviour:** 

It should be possible to select and copy the hash.

**Actual behaviour:** 

It is not possible to select or copy the hash.

**Reproduces how often:** 

Always.

### Logs

N/A

#### Additional Information

The macOS version for the native desktop allowed for copying the has all the time. I often have to use the git command-line for my regular work as well as other tools which use the commit hashes so copying the hash from the desktop tool that I use is important.

**Comment by niik** [comment]
Hey @brennanMKE, thank you for opening this! We're currently tracking this in https://github.com/desktop/desktop/issues/1501 so please head over there and subscribe to the issue to follow along.
