### ISSUE TITLE
The repository does not seem to exist anymore, only in GUI

### ISSUE THREAD

**Issue by emilpaulitz** [desktop/desktop#17758]
### The problem

When fetching a specific repository, I always get asked for the passphrase of my ssh key twice and then the "The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed." Error. Pushing changes weirdly does work however, and git pull with the shell works fine. This was preceded by me deleting a branch on the website that the GUI still was on. Now, I can change the branch, deleted the branch also in my GUI, signed out and in, re-installed the GUI, tried all feasible options regarding authentication, but the error persits. 

### Release version

Version 3.3.5 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Not sure how to reproduce. But maybe:
Check out a specific branch
Delete the branch on the website
The bug might occur

### Log files

[2023-11-22.desktop.production.log](https://github.com/desktop/desktop/files/13438668/2023-11-22.desktop.production.log)

**Comment by tidy-dev** [comment]
@emilpaulitz Thank you for reaching out. I was looking through your log and noticed that there were two references `ChrisResl/coin_treewas_mp` and `fbaumdicker/coin_treewas_mp`. Is it possible the upstream remote is not correct?

Could you try re-cloning the repository in a new directory and see if the error persists?

**Comment by emilpaulitz** [comment]
Yes, I also tried that and didnt work, whether I re-clone in the old or a new location on my pc. I am working on fbaumdicker/coin_treewas_mp, which is a fork of ChrisResl/coin_treewas_mp.

**Comment by emilpaulitz** [comment]
Primary remote repository (origin) ist set to
`https://github.com/fbaumdicker/coin_treewas_mp.git`

**Comment by tidy-dev** [comment]
Maybe we are seeing a permissions issue with `ChrisResl/coin_treewas_mp` or that repository doesn't exist or has been renamed. Either is the same bug reported in or is similar to https://github.com/desktop/desktop/issues/3715. 

Could you try the suggestion there?

```
$ git remote remove upstream
```

**Comment by emilpaulitz** [comment]
Indeed, I cannot access the original repo ChrisResl/coin_treewas_mp. The suggestion fixes the issue until I close and re-open the GUI. Then, the behaviour is the same as before.

**Comment by tidy-dev** [comment]
Yes.. Unfortunately that appears to be what is described in that bug. 

https://github.com/desktop/desktop/issues/3715#issuecomment-919617129. 

I am sorry there isn't a better work around at this time.  I am going to close this thread in favor of tracking it in that issue.

**Comment by emilpaulitz** [comment]
Thanks for your help! Strange that the error only occurred today, as I could not access the original repo before either

**Comment by fedesentito** [comment]
The error is still present

**Comment by SoaibHaque** [comment]
I commented on this issue with a solution [#3715 (comment)](https://github.com/desktop/desktop/issues/3715#issuecomment-2227278110).
