### ISSUE TITLE
Add a search bar belowe history to filter branch's commits

### ISSUE THREAD

**Issue by gazmendsahiti** [desktop/desktop#17759]
### The feature request

A search bar to filter/search the history of the branch by commit message similar to the "Select Branch to Compare".
Placed above or below the "Select Branch to compare".

### Proposed solution

When working on a project with multiple teams and branches it would help when you want to see if a specific branch has been merged or search for a specific commit.

**Comment by tidy-dev** [comment]
Thank you for the suggestion!

We are tracking this feature request in https://github.com/desktop/desktop/issues/7022. I am going to close it in favor of that.
