### ISSUE TITLE
Repo can be accessed from the Trash

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1775]
We should block users from drag+drop'ing repo into Desktop from the Trash can as files are still linked back to the Trash.

<img width="954" alt="screen shot 2017-05-25 at 2 09 51 pm" src="https://cloud.githubusercontent.com/assets/14828183/26464123/a748f8b6-4154-11e7-82b4-52373a0a18df.png">

400 errors as expected:
<img width="1124" alt="screen shot 2017-05-25 at 2 20 46 pm" src="https://cloud.githubusercontent.com/assets/14828183/26464324/62d28cf0-4155-11e7-9e81-57f7c0656e5b.png">

v0.5.8, OS X 10.11.5

**Comment by joshaber** [comment]
This would certainly involve some regret, but I don't think we need to do anything here to prevent it.
