### ISSUE TITLE
Collaboration 

### ISSUE THREAD

**Issue by Ninja-mann07** [desktop/desktop#17760]
### The feature request

Authentication Failed

We were unable to authenticate with github/ninja-mann07/italhippo. Please enter your username and password and try again.

#17755 

Requesting info on retrieving my personal access token...🥷.🫡...

### Proposed solution

# A first-level heading
### A third-level heading 
#will spread good karma and fortune for GitHub!♕

### Additional context

n/a

**Comment by tidy-dev** [comment]
@Ninja-mann07 Thanks for reaching out. Here is a the GitHub documentation about [managing your personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens). Hope that helps.
