### ISSUE TITLE
Use exclude functionality from Git

### ISSUE THREAD

**Issue by mvandermade** [desktop/desktop#17763]
### The feature request

I need to change some proxy parameters when working.
So each time I commit I should be very careful not to tick the box:
![afbeelding](https://github.com/desktop/desktop/assets/33425497/5975b88c-2d8b-42d1-b13c-aa07c8503fdd)

I found out Git has a functionality called exclude.
https://medium.com/@dave_lunny/exclude-files-from-git-without-committing-changes-to-gitignore-986fa712e78d

But when I changed the file `.git/info/exclude` to:
```
# git ls-files --others --exclude-from=.git/info/exclude
# Lines that start with '#' are comments.
# For a project mostly in C, the following would be a good set of
# exclude patterns (uncomment them if you want to use them):
# *.[oa]
# *~
nginx/conf.nginx
```

It still commits the file.

### Proposed solution

Some way to mark excluded files. Or give a warning when committing files that are excluded (which is nice too).

### Additional context

Exclude and ignore may be easily confused. Perhaps "commit warning" is better terminology?

**Comment by DylanDevelops** [comment]
Is adding your file to your `.gitignore` something that could fix your issue?

**Comment by mvandermade** [comment]
Yes that would work.
Problem is that the file now is uncommitable for the rest of the collaborators.
After your suggestion I clarified some things for myself:

Exclude:
The example I showed was with a tracked file. Then the exclude doesn't apply since it only works for untracked files.
-> For untracked files Github Desktop behaves like it should... issue can be closed.

More background information:

Gitignore:
Works for both tracked and untracked files. But tracked files cannot be modified/removed without special commands: https://stackoverflow.com/questions/13541615/how-to-remove-files-that-are-listed-in-the-gitignore-but-still-on-the-repositor

Update-index:
For "excluding" tracked files. (error's when file specified is not tracked):
```git update-index --assume-unchanged "hello.txt"```
And the reverse:
```git update-index --no-assume-unchanged "hello.txt"```
https://dev.to/nickraphael/git-assume-unchanged-for-when-you-want-git-to-ignore-an-edit-for-a-while-2lig

Thanks for your help! I found a tool to work around my issue 👍

**Comment by DylanDevelops** [comment]
Glad to hear it @mvandermade!

**Comment by marc-w** [comment]
Why not provide access to the `.git/info/exclude` file?

It is like a local `.gitignore` - super handy for testing scripts or other files you never want to leak into the repo. Huge fan for almost 20 years. 

I use this all the time, and Git Tower has this in the GUI

**Comment by mvandermade** [comment]
I tried using the `.git/info/exclude` file, but GitHub desktop still sees changes to that file.
I entered "README.md" in the `.git/info/exclude` file

With `update index --assume-unchanged ` it is not staged.

I'm unfamiliar with Git Tower, thanks I'll see how it works there.

--edit--
I tried Git Tower and when excluding a file like README.md it asks also to untrack the file.

**Comment by marc-w** [comment]
Yes, you need to untrack to exclude.  

Also, this is a weirdness of Git I don't understand well: you may need to purge various caches for the exclusion to take effect.

I perform a full cache clear, then reset the head, and everything works as expected.

If you have tracked files you don't want in the diff but keep tracked, use `--assume-unchanged`.

My productivity increases with exclude use because I use a lot of testing scripts and bootstrapping scripts in my workflow that should never make it to repo. I often do all the things you are not supposed to do, and to exclude don't worry about the consequences, like hard-coding creds, custom bootstrapping, scripts that reset databases, etc.  I always read my whole diff before comitting to origin.

**Comment by mvandermade** [comment]
Nice, I always managed my excludes from .gitignore, never knew about exclude. Thanks for the info about some handy tools to use with Git!

**Comment by marc-w** [comment]
This feature is strong but underutilized and not discussed (exclude). 

You can go pretty far. For example, I use a pattern that automatically excludes any file starting with `scratch`. 

Just some RegX.  

You can name a directory and ignore the directory and all its contents too. 

Obviously, if you use a broad pattern, be careful you don't collide your logic.
