### ISSUE TITLE
Force push option is missing

### ISSUE THREAD

**Issue by kaarthicksiyer** [desktop/desktop#17766]
### The problem

I am using Github desktop version 3.3.5 arm 64 for mac. 
Recently I wanted to do a force push but realized that the force push option was missing under my Repository menu item. 

### Release version

3.3.5 arm64

### Operating system

Mac

### Steps to reproduce the behavior

Click Repository

### Screenshots

<img width="412" alt="Screenshot 2023-11-24 at 10 52 15 AM" src="https://github.com/desktop/desktop/assets/119481867/8137b9dd-0679-478e-8052-0aee72c86f85">

**Comment by tidy-dev** [comment]
@kaarthicksiyer The force push option is only available in GitHub Desktop when [we can detect a diverged state.](https://github.blog/changelog/2023-01-27-github-desktop-improves-force-pushing-and-fetching-along-with-many-great-open-source-contributions/#force-pushing-and-fetching). Hope that helps clarify why the Forced push option won't always be available.

**Comment by Tarrgon** [comment]
I know this is old, but, this option should be available at all times. Desiring to revert accidental commits without history is a normal and useful feature. Not sure why we are obfuscating the git cli like this.
