### ISSUE TITLE
My total repository is 55 but showing only 2

### ISSUE THREAD

**Issue by ArifulSikder** [desktop/desktop#17769]
### The problem

My total repository is 55 but showing only 2

### Release version

Version 3.3.5 (x64)

### Operating system

windows 10

### Screenshots

![image](https://github.com/desktop/desktop/assets/67917301/a0ed9e85-f289-42cf-9b4c-b272859cf981)

**Comment by tidy-dev** [comment]
@ArifulSikder Thank you for reaching out! GitHub Desktop's repository list only shows the repositories you have added to GitHub Desktop for it to manage. It does not automatically show all the ones on GitHub.com (remote) nor does automatically detect all locally cloned. Here is some documentation on [how to clone (aka add) your remote repositories to GitHub Desktop.](https://docs.github.com/en/desktop/adding-and-cloning-repositories/cloning-and-forking-repositories-from-github-desktop) and here is some documentation on [how to add local (already cloned) repositories to GitHub Desktop](https://docs.github.com/en/desktop/adding-and-cloning-repositories/adding-a-repository-from-your-local-computer-to-github-desktop).
