### ISSUE TITLE
GitHub Desktop  An additional image was submitted to the master's location

### ISSUE THREAD

**Issue by kiannaDill** [desktop/desktop#17773]
### The problem

![联想截图_20231125091338](https://github.com/desktop/desktop/assets/108788805/c817d950-d3bf-40c8-a1a2-5dbd29c431a8)

### Release version

版本 3.2.0 (x64)

### Operating system

win11

**Comment by tidy-dev** [comment]
@kiannaDill Could you please fill out the entire issue template? As of now, I am not sure if your concern relates to GitHub Desktop.
