### ISSUE TITLE
Possibility to integrate OBSIDIAN.md as supported editors

### ISSUE THREAD

**Issue by Falcion** [desktop/desktop#17772]
### The feature request

Is there any way to add support to OBSIDIAN.md as one of editors in list for github desktop? So you could open repository's folder just as vault (obsidian's name for workspace).

### Proposed solution

Github brings together a sufficient number of versatile people from different professions around projects, mostly, developers, but it also can be some writers of both technical documentation and just any creative direction: and https://obsidian.md/ is one of the most popular softwares for this purposes with native support for markdown.

### Additional context

OBSIDIAN's org-link: https://github.com/obsidianmd/

**Comment by tidy-dev** [comment]
@Falcion Thank you for the suggestion! We are happy to review community pull requests for adding external editors. Here is some documentations on [editor requirements](https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md#my-favourite-editor-xyz-isnt-supported), and here is an [example PR of a previous contributor](https://github.com/desktop/desktop/pull/17120).

**Comment by steveward** [comment]
GitHub Desktop now provides support for [adding custom editors](https://docs.github.com/en/desktop/configuring-and-customizing-github-desktop/configuring-a-default-editor-in-github-desktop?platform=windows#configuring-a-custom-editor), so you can add Obsidian by following the steps in that linked help article. I'm going to close this out.
