### ISSUE TITLE
Add files filter

### ISSUE THREAD

**Issue by 192933488S** [desktop/desktop#17774]
### The feature request

As part of typical build packages, numerous "machine files" (auxiliaries, temps, data containers, whatever) are committed, which are not really content files. This is often so, because builds are inside the same folder as source files. Separations for small projects are not per se light or economic, etc. Thus, it would be handy, to filter inside Desktop the particular file extension, such as *.c, instead of having always "absolute numbers" such as "30 changed files".

Kind Regards

### Proposed solution

Include a file or extension filter at top in Changes and History. Ctrl+F is only available within the selected file.

**Comment by tidy-dev** [comment]
@192933488S Thank you for the suggestion! We are tracking feedback for that in https://github.com/desktop/desktop/issues/6407. I am closing this in favor of that issue.
