### ISSUE TITLE
Github Desktop won't launch

### ISSUE THREAD

**Issue by DreamOrbital** [desktop/desktop#17779]
### The problem

After installing Github Desktop, the application will not open including from command prompt and does not appear in the taskbar, start menu or Task Manager. I can see it in the directory AppData/Local/GitHubDesktop. I have tried restarting my computer, reinstalling GitHubDesktop, uninstalling my antivirus software, using regsvr32 msi.dll. I have also tried deleting the app- folder from the directory. None of the solutions in issues #3757, #11141 or #6835 seem to work.

### Release version

3.3.5

### Operating system

Windows 11 23H2

### Steps to reproduce the behavior

Install GitHubDesktop
Go to AppData/Local/GitHubDesktop open GitHubDesktop.exe

### Log files
[Squirrel-Install.log](https://github.com/desktop/desktop/files/13491957/Squirrel-Install.log)

[
[Squirrel-UpdateSelf.log](https://github.com/desktop/desktop/files/13491936/Squirrel-UpdateSelf.log)
](url)

**Comment by niik** [comment]
Thanks for the report! Unfortunately as you might imagine we can't reproduce this. I suspect either the installation itself has gone awry or there's something happening during startup preventing the app from loading. We need to try to locate some log file or error message to troubleshoot this..

Are there any files in Desktop's log folder? (`%APPDATA%\GitHub Desktop\logs`) If so please attach the most recent one.

It would also be helpful if you could send over the log file that the Squirrel installer generates.

You should be able to find the log file here:

%LocalAppData%\GitHubDesktop\SquirrelSetup.log

If no log file is being generated there you should be able to find one in the SquirrelTemp directory:

%LocalAppData%\SquirrelTemp\SquirrelSetup.log

Please send that over as an attachment.

**Comment by DreamOrbital** [comment]
[Squirrel-Install.log](https://github.com/desktop/desktop/files/13502109/Squirrel-Install.log)

**Comment by steveward** [comment]
Thanks for the log file @DreamOrbital. I'm not seeing anything helpful there, unfortunately. Could you open Event Viewer on Windows to see if there is anything helpful there that is showing up when you attempt to open GitHub Desktop?

**Comment by DreamOrbital** [comment]
No, I can't see any events related to GitHub Desktop.

**Comment by steveward** [comment]
Any issues opening other applications? When you re-installed, did you fully delete both the GitHub Desktop directories in `%LocalAppData%` and `%AppData%`?

One thing I would also recommend trying is to create a new user account on this machine to see if you are able to install there.
