### ISSUE TITLE
GitHub Desktop GUI disappears after a few seconds and everything turns white

### ISSUE THREAD

**Issue by nilslindemann** [desktop/desktop#17786]
### The problem

(I searched for "white screen" in these issues, found nothing relevant)

When starting GitHub Desktop version 3.3.3-linux2 (installed via the Linux Mint package manager) after a few seconds the application GUI disappears and everything inside the application window becomes white.

User _mfleuti_ today posted a temporary solution as comment in the Linux Mint package manager GUI:

In the console, run:

```
sudo flatpak update --commit=91f4274313a1c6702fa1ce365e40e14ee474055af1c00a7bad2776d2a921972e io.github.shiftey.Desktop
```

This will revert to an earlier commit, so that we can keep working with that until a fix is available.

Full quote of _mfleuti_'s comment:

> The software is great but in the latest commit there's some bug with GTK and the whole screen becomes white which renders the application unusable. To fix this I reverted to the last working commit like this: `sudo flatpak update --commit=91f4274313a1c6702fa1ce365e40e14ee474055af1c00a7bad2776d2a921972e io.github.shiftey.Desktop`. After that I have disabled the package update for the time being. You can get a list of all commits with this command: `flatpak remote-info --log flathub io.github.shiftey.Desktop`

### Release version

3.3.3-linux2

### Operating system

Linux Mint, up-to-date

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. Wait a few seconds
3. The usual GUI disappears and everything inside the window turns white

**Comment by steveward** [comment]
Thanks for the issue @nilslindemann. At this time we don not provide official support for the Linux fork of GitHub Desktop. I would recommend following along in this issue:

https://github.com/shiftkey/desktop/issues/958

I hope that helps.

**Comment by nilslindemann** [comment]
@steveward Thanks for the link, seems I was in the wrong repo. Installing the `3.3.5-linux2` non-flatpak version [fixed it](https://github.com/shiftkey/desktop/issues/958#issuecomment-1832668958) for me.
