### ISSUE TITLE
Bulk removing missing repositories from Github Desktop

### ISSUE THREAD

**Issue by SRNissen** [desktop/desktop#17793]
### The feature request

Problem:

Updating the Github Desktop (GD) state for multiple repositories that have been moved/deleted is a heavy workflow.

You have to use the Locate wizard multiple times, or remove them one by one and then re-add them.

### Proposed solution

A button that simply forgets all repos would work (I'll re-add them by bulk-dragging their new locations into GD) but I suspect other users might prefer a more granular solution e.g. checkmarks by each repo or something. I develop libraries, not UX, I'm sure you have people that can come up with better solutions.

### Additional context

Outside of GD I have moved many repositories, approximately like:

    mv -rd repos/project1 repos-company/project1
    mv -rd repos/project2 repos-company/project2
    ...
    ... //all company repos moved to repos-company
    ... //only personal repos remain in /repos
    ...
    mv -rd repos/ repos-personal/

There we go, clean split.

Next step:

**EITHER:** Manually go, one by one, through hundreds of repos in GD, wait for GD to pop up the `Cant Find "repo-name"` page and go through `Locate` for each of them.

**OR:** Manually go, one by one, through hundreds of repos in GD, wait for GD to pop up the `Cant Find "repo-name"` page and go through `Remove` for each of them.

**OR:** Uninstall GD and purge all local data, re-install GD, re-authenticate GD with github.com, then bulk re-add repos by dragging them over from my file explorer.

To be clear *my problem* is solved, because I'm just going to do that last one and uninstall GD to get a clean slate.

But this is the third time I have a problem that kind-of looks like this, so I thought I'd make a feature request.

**Comment by steveward** [comment]
Thanks for the feedback @SRNissen! I'm going to add incorporate this into https://github.com/desktop/desktop/issues/1574 which is a closed enhancement for adding all repositories back to GitHub Desktop. We haven't heard previous feedback about removing all repositories and re-adding them -- it's more along the lines of being able to scan for all repositories.

If you want to quickly remove all repositories from GitHub Desktop without uninstalling you can manually delete the locally cached data by going to `View` > `Toggle Developer Tools` > `Application` > `Storage` and using the `Clear site data` option. You will need to restart GitHub Desktop and then log in again as well.

**Comment by DereC4** [comment]
> Thanks for the feedback [@SRNissen](https://github.com/SRNissen)! I'm going to add incorporate this into [#1574](https://github.com/desktop/desktop/issues/1574) which is a closed enhancement for adding all repositories back to GitHub Desktop. We haven't heard previous feedback about removing all repositories and re-adding them -- it's more along the lines of being able to scan for all repositories.
> 
> If you want to quickly remove all repositories from GitHub Desktop without uninstalling you can manually delete the locally cached data by going to `View` > `Toggle Developer Tools` > `Application` > `Storage` and using the `Clear site data` option. You will need to restart GitHub Desktop and then log in again as well.

Thank you
