### ISSUE TITLE
Bookmark favorite branches

### ISSUE THREAD

**Issue by arochettesteinberg** [desktop/desktop#17792]
### The feature request

I would like to be able to bookmark or pin some branches by right-clicking on them. Bookmarked branches could just appear at the top of the suggestion in the branch text field or even be specifically highlighted within the app, maybe as a regular bookmar bar then.

### Proposed solution

It will quicken changing between most used branches.

**Comment by steveward** [comment]
Thanks for the feedback @arochettesteinberg. This has been previously requested in https://github.com/desktop/desktop/issues/15767, so I'll add your feedback there and close this out.
