### ISSUE TITLE
There is no Pull origin or Pull origin with rebase in the Desktop UI

### ISSUE THREAD

**Issue by dezhimou** [desktop/desktop#17798]
### The problem

When open GitHub Desktop, I cannot find Pull origin button or menu anywhere. I have to use Branch->Update from master to synchronize my local branch codes.

### Release version

Version 3.3.5 (x64)

### Operating system

Windows 10

### Screenshots

![image](https://github.com/desktop/desktop/assets/33645539/f941867b-bd99-4d02-a613-9489ae2dec6c)

**Comment by steveward** [comment]
@dezhimou thanks for the issue. The `Pull origin` option will show up where `Fetch origin` is when there are new changes in the remote repository that need to be pulled to your local repository. The `Branch` > `Update from master` option pulls in changes from your local default branch to your current branch. I hope that helps explain things!
