### ISSUE TITLE
Feature request: Create branch from commit should base branch name from commit message

### ISSUE THREAD

**Issue by emmadesilva** [desktop/desktop#17799]
### The feature request

When creating a branch from a commit, it would be helpful if the branch name is prefilled with the kebab case version of the commit name

### Proposed solution

If a commit named "Add a new cool feature" is made and the user uses the create branch from commit feature the branch name is prefilled to be "add-a-new-cool-feature"

**Comment by tidy-dev** [comment]
@caendesilva Thank you for the suggestion! However, this feature suggestion is targeted towards a specific workflow where the commit summary always reflects the intended branch name. The "create a branch from commit" feature can be used for many workflows such as checking out a repository at a specific tag or place in time to test behavior before other changes. In those other workflows, this may not be helpful or even confusing. 😟  We are going to close this for now, but if we receive more interest (thumbs up the issue if you find this and want it too) in the feature we may reconsider.
