### ISSUE TITLE
Hitting Enter does not create new branch when basing off non-default branch

### ISSUE THREAD

**Issue by Haacked** [desktop/desktop#1780]
Repro steps (GitHub Desktop v0.5.8 on Windows):

1. In a repository with more than one branches, select `File` > `New branch`
2. Type in a name and hit `Tab` to select the base branch. Hit down arrow to select something other than `master`.
3. Hit `Enter`

Expected: The branch is created.
Actual: Nothing happens.

I noticed if I hit `SHIFT`+`Tab` to give focus back to the branch name, then hitting `Enter` works. The problem seems to be that hitting `Enter` when the branch list has focus doesn't do anything.

**Comment by tierninho** [comment]
Confirming the same, however it does work if you keep tabbing once you made your selected base branch. Not ideal though.

Whole `class="vertical-segmented-control"` is highlighted:
<img width="794" alt="screen shot 2017-05-26 at 9 28 30 am" src="https://cloud.githubusercontent.com/assets/14828183/26496515/dcfa62aa-41f5-11e7-9fa3-09c2f904c747.png">
