### ISSUE TITLE
Please display commit dates not relative 

### ISSUE THREAD

**Issue by PhilippeGanter** [desktop/desktop#17828]
### The feature request

Please display dates in the commit list as "04/12/2023" or "12/04/2023", not "2 days ago"

### Proposed solution

Display dates in the commit list as "04/12/2023" or "12/04/2023", not "2 days ago"

**Comment by steveward** [comment]
Thanks for the issue @PhilippeGanter. You can hover over the relative date to see the absolute date. I hope that helps! We're also tracking feedback about this in https://github.com/desktop/desktop/issues/14611.
