### ISSUE TITLE
Transient Fetch Origin error (maybe IPv6 issue):  fatal: unable to access [URL] Recv failure: Connection was reset

### ISSUE THREAD

**Issue by ripvlan** [desktop/desktop#17824]
### The problem

Github desktop has recently begun reporting a Fatal Error message.   It has been working fine for about a year and only recently began reporting this error.  We use AzureDevOps (dev.azure.com) for our repositories.   It doesn't fail every time - most of the time (it works 1 in 10 times). If one retries the operation over and over again it eventually works.

Short story: changing the IPv6 priority (see below) has resolved the problem (such that IPv4 is preferred)

Many online searches later I stumbled across a discussion regarding github desktop and ipv6, and that's when I remembered that I had reset my network about a month ago.  This appears to have changed the priority.

This lead me to change the IPv6 priority via "netsh"  See this article for the steps that I followed https://kb.firedaemon.com/support/solutions/articles/4000160803-prioritising-ipv4-over-ipv6-on-windows-10-and-11

### Release version

Version 3.3.5 (x64)

### Operating system

Windows 10 PRO x64 (Version 10.0.19045 Build 19045)

### Steps to reproduce the behavior

1. Open Github Desktop
2. Press Fetch origin tab

### Log files

2023-12-05T17:01:53.770Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2023-12-05T17:01:54.836Z - info: [ui] [AppStore] loading 3 repositories from store
2023-12-05T17:01:55.084Z - info: [ui] launching: 3.3.5 (Windows 10.0.19045)
2023-12-05T17:01:55.086Z - info: [ui] execPath: 'C:\Users\mike.jones\AppData\Local\GitHubDesktop\app-3.3.5\GitHubDesktop.exe'
2023-12-05T17:01:56.225Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.165s)
2023-12-05T17:02:01.827Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://dev.azure.com/{hidden}/data%20extraction/_git/Data_Team/': Recv failure: Connection was reset

2023-12-05T17:06:30.400Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://dev.azure.com/{hidden}/rcx/_git/rcx/': Recv failure: Connection was reset

**Comment by steveward** [comment]
Thanks for sharing this @ripvlan! I'm going to make a note of this for future reference in case we see further reports of this. Did you ever encounter this issue with GitHub repositories as well?

**Comment by ripvlan** [comment]
> Thanks for sharing this @ripvlan! I'm going to make a note of this for future reference in case we see further reports of this. Did you ever encounter this issue with GitHub repositories as well?

Thanks for the reply.  

I don't use any github repositories on a regular basis.  Although I did clone MassTransit via github desktop this morning - but I used the new network configuration.

I'll revert my network settings and try to reproduce it next week using both the azdevops and github repositories.

**Comment by steveward** [comment]
I tested this out a bit on my Windows machine in an Azure DevOps test repo I have set up and wasn't able to reproduce any issues. I'm going to close this out for the time being but let us know if you have any further updates. Thanks again for reporting this.
