### ISSUE TITLE
Cant Delete Changes

### ISSUE THREAD

**Issue by HenaryKyaw** [desktop/desktop#17826]
### The problem

When trying to delete changes, files do not delete and stay in the list even after repeat attempts.

### Release version

Version 3.3.5

### Operating system

Windows 10

### Steps to reproduce the behavior

Go to a clone repository and try to delete all changed files.

### Screenshots

![Screenshot (1953)](https://github.com/desktop/desktop/assets/143761240/c6af7092-092d-404c-92cc-f31c688e7338)

**Comment by steveward** [comment]
Thanks for the issue @HenaryKyaw. Just to confirm -- are you trying to discard the changes in GitHub Desktop or delete the files locally in File Explorer?

**Comment by HenaryKyaw** [comment]
Apologies for the late response @steveward !
I was trying to discard the changes in GitHub Desktop, yes.

**Comment by steveward** [comment]
Thanks for the update -- is this a network/mapped drive, or possibly a drive in WSL? We've seen some issues in the past in those specific scenarios.
