### ISSUE TITLE
Polish: Fix tabindex of username/password fields

### ISSUE THREAD

**Issue by albinekb** [desktop/desktop#1783]
### Description

![kapture 2017-05-26 at 3 31 57](https://cloud.githubusercontent.com/assets/5027156/26477152/ea762a5e-41c3-11e7-934d-f2f5075e4c3a.gif)

### Version

**GitHub Desktop version:** 
Can't get version without signing in 😄 

**Expected behaviour:** Password field should be focused after pressing tab in username field, this is how 99% of login forms work 💅 

**Actual behaviour:** Forgot password link is focused

**Comment by shiftkey** [comment]
The proposal to change this has been opened in https://github.com/desktop/desktop/pull/1513
