### ISSUE TITLE
Change highlight not shown when adding newline

### ISSUE THREAD

**Issue by PatrickMatthiesen** [desktop/desktop#17834]
### The problem

I have a similar issue to #11553, but I don't need a long input, and the issue is in both unified and split view.
It seems that if the change is highlighted if it is only the current line is changed. Adding a new line next to the change that should be highlighted, causes the highlight to disappear.

Without change and expected behavior:
![image](https://github.com/desktop/desktop/assets/43612965/d8ab1388-d96e-4a8c-9c75-e4c6747b411a)

My change:
![image](https://github.com/desktop/desktop/assets/43612965/207580dc-7b00-4a4e-b266-d599f30a4319)

Or Just with a new line:
![image](https://github.com/desktop/desktop/assets/43612965/21a649cb-ef82-4d17-bef9-f33167d4abf3)

### Release version

3.3.5

### Operating system

Windows 11 Home (Build: 22631.2715)

### Steps to reproduce the behavior

1) Make a change on a line
2) Add a new line after the modified line

### Log files

[2023-12-06.desktop.production.log](https://github.com/desktop/desktop/files/13591363/2023-12-06.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the issue @PatrickMatthiesen. I'm going to add this into https://github.com/desktop/desktop/issues/2700 -- you can follow along there for any updates to this.
