### ISSUE TITLE
Every file shows up as new file

### ISSUE THREAD

**Issue by bick** [desktop/desktop#17847]
### The problem

This happens all day. Basically, I'm working in my repo and GitHub Desktop shows every file in the repo as being added. But it's not because if you try to commit the code, it says there are no new changes. 

### Release version

Version 3.3.6

### Operating system

macOS 14.1.1

### Steps to reproduce the behavior

1. Have repo open
2. About 5 minutes later, all files in the repo will all show as new files. 

### Screenshots

![Screenshot of GitHub Desktop](https://github.com/desktop/desktop/assets/12536625/cb11fa94-56dd-42ab-829c-ea03b6a0baff)

**Comment by steveward** [comment]
@bick this if often due to file mode or line ending changes. Can you open the repository in the terminal and run `git diff` against one of the changed files?

**Comment by bick** [comment]
@steveward when I run `git diff app/admin/users.rb`, I get a blank response.

**Comment by steveward** [comment]
Can you share the output of `git config --list --show-origin` to see if there are any configuration options that could be causing this?

**Comment by bick** [comment]
@steveward Here is what is output when I use `git config --list --show-origin`:
```
bick@Owens-MacBook-Pro ~ % git config --list --show-origin
file:/opt/homebrew/etc/gitconfig        credential.helper=osxkeychain
file:/Users/bick/.gitconfig     filter.lfs.smudge=git-lfs smudge -- %f
file:/Users/bick/.gitconfig     filter.lfs.process=git-lfs filter-process
file:/Users/bick/.gitconfig     filter.lfs.required=true
file:/Users/bick/.gitconfig     filter.lfs.clean=git-lfs clean -- %f
file:/Users/bick/.gitconfig     user.name=REDACTED
file:/Users/bick/.gitconfig     user.email=REDACTED
```

**Comment by steveward** [comment]
Thanks, it doesn't seem like a line endings or file mode change issue. What is the exact error output when you try to commit your changes? 

Also, could you upload the log file from GitHub Desktop so that I could see if that shows anything helpful? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by bick** [comment]
@steveward Here is a screenshot of the error message
![CleanShot 2023-12-12 at 13 28 44@2x](https://github.com/desktop/desktop/assets/12536625/139fb950-49a3-42b2-b796-7fe7eaa40192)

Here is a link to the log: https://pastebin.com/yW2Qkns4

**Comment by steveward** [comment]
Can you also share what `git status` is showing from the command line?

The only error I'm seeing is this:

```
2023-12-12T01:17:38.579Z - info: [ui] [fetchAllRepoRulesets] unable to fetch all repo rulesets | repos/spoteasy/spoteasy/rulesets
Error: Upgrade to GitHub Pro or make this repository public to enable this feature.
```

I'm not sure if/why this could cause the local repository to have issues, but seeing what the command line shows should help narrow down if this is an edge case with repository rules that is causing this behavior in GitHub Desktop.

**Comment by bick** [comment]
@steveward Here is the output when I run `git status`: https://pastebin.com/gUJ1GJfN

Not sure why it thinks I modified all of these files, I haven't touched any of them. If I commit eventually, it will commit with only the files I actually changed.

**Comment by bick** [comment]
@steveward I think I see what is causing this. It might have something to do with iCloud. I have the files in my Documents directory. I have moved all of my repos out of iCloud and to my user folder and now I don't run into this issue anymore.
