### ISSUE TITLE
wth why

### ISSUE THREAD

**Issue by Debiloid3000** [desktop/desktop#17841]
### The problem

i cant clone repository

### Release version

3.3.4

### Operating system

Windows 10

### Log files

remote: Enumerating objects: 407356, done.
remote: Counting objects: 100% (39022/39022), done.
remote: Compressing objects: 100% (5898/5898), done.
error: RPC failed; curl 56 Failure when receiving data from the peer
error: 3176 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by letanloc1998** [comment]
I have the same issue, no more logs to know what's happened?
