### ISSUE TITLE
When a repo is checked out twice, put some kind of file system path data into the repo list so they can be distinguished.

### ISSUE THREAD

**Issue by m4ttheweric** [desktop/desktop#17840]
### The feature request

Currently, if you check out a repo twice with the same name, in the repo list they are indistinguishable unless you hover and look at the path:

![Screenshot 2023-12-07 at 9 14 05 AM](https://github.com/desktop/desktop/assets/49927862/9c28ed23-375f-4c25-8f3b-bba41f22bd18)

When you hover, you can see the file system path:

![Screenshot 2023-12-07 at 9 14 14 AM](https://github.com/desktop/desktop/assets/49927862/083b033c-ac4f-43e3-9d0f-e7283020ddae)

### Proposed solution

If two repos have the same name in the list, show the path either in a subtitle area or parenthetically so hovering is not the only way to tell them apart.

**Comment by steveward** [comment]
Thanks for the issue @m4ttheweric. We implemented the alias feature specifically for cases like this -- you can right-click and select `Create alias` to differentiate repositories of the same name. I hope that helps!
