### ISSUE TITLE
I cant clone a respositoy into git hub desktop again after ive deleted it. I needs it 

### ISSUE THREAD

**Issue by MaximusTheGladiator** [desktop/desktop#1784]
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

[Description of the issue]

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** [version here]

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behaviour:** [What you expected to happen]

**Actual behaviour:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by MaximusTheGladiator** [comment]
Its https://github.com/general-ai-challenge/Round1 <-- this repository and git hub desktop says "The destination already exists"

**Comment by shiftkey** [comment]
@MaximusTheGladiator it sounds like you already have the repository (or a folder with this same name) on your system. You can add this using the **File** | **Add Local Repository** flow, or drag and drop the folder onto the application.

As GitHub Desktop will not clone a new repository to overwrite an existing folder, and without more information about the steps leading up to this, I believe this behaviour is by design.

**Comment by MaximusTheGladiator** [comment]
Thank you!!

**Comment by MaximusTheGladiator** [comment]
Now that ive done this, I'm not sure how I'm supposed to use it...

I don't know how to add Curses to Python.

weve tried to use pip, but all versions of Python weve tried have said that
there is either an issue with syntax, or that a command that tells the
system to upload curses isn't recognized. Weve tried Python 3.6.1, 2.7.10.
2.7.13, and 3.5.0 and it hasn't worked primarily for syntax reasons when I
copied and pasted. The version of curses Were trying to "connect" with
whatever Version of Python always matches, for example, We used
*curses‑2.2‑cp36‑cp36m‑win_amd64.whl*  when using Python 3.6.1, on 64 bit
version.

Weve only got the warning that that command isn't recognized when using
Python 2. 7.10 "probably because it may be outdated"

Also, is Python really the best place to be running the environment?

And  If I run the environment In Python do I have to use Python to make the
agent?

What other Coding languages could I use to run the environment and make the
agent?

Thank you in advance *"Sorry for this extreme overhaul of questions"*


On Fri, May 26, 2017 at 8:26 PM, Maximus Smith <maximillian0000000@gmail.com
> wrote:

> Thank you!!
>
> On Thu, May 25, 2017 at 10:34 PM, Brendan Forster <
