### ISSUE TITLE
Open Github Repo in Default Browser After Publishing Local Repo

### ISSUE THREAD

**Issue by etimezz** [desktop/desktop#17865]
### The feature request

When a user publishes a local repository to Github, after they click the 'Publish Repository' button in the form window, the Github repository is automatically opened in the system default browser.

### Proposed solution

I think that this will benefit Github Desktop users as a signifier of success in publishing their repository and as a convenient way to access and inspect the remote repository upon publishing.

### Additional context

See the below screenshot of the form that is submitted prior to this feature.
<img width="754" alt="Screenshot 2023-12-12 at 1 01 42 PM" src="https://github.com/desktop/desktop/assets/153581641/1297e92c-6a78-409d-8efa-0c387006dddb">

**Comment by steveward** [comment]
Thanks for the issue @etimezz. Redirecting to a browser right after publish likely isn't something we would implement at this time, but thanks for the feedback on this! You can quickly open your newly published repository in the browser by using the CMD/CTRL+SHIFT+G shortcut. I hope that helps!
