### ISSUE TITLE
Application doesn't show on Mac M1 Sonoma

### ISSUE THREAD

**Issue by splintor** [desktop/desktop#17868]
### The problem

I used the app for a few years on my Mac M1. Suddenly one day the app stopped working.
When I start the app, I see the app menu, and it behaves normally, except no window is shown.
When I select items in the menu, such as **Add Local Repository**, nothing happens, but the menu items under **File** become disabled.
I tried looking if it might be running on another desktop, but I only have once desktop.
I tried running the beta version, and also the intel version, but to no avail. I just don't see any window of the GitHub Desktop app - only menu. The appears in the dock and in the list of running apps (when I press Cmd+Tab).

### Release version

3.3.7-beta2

### Operating system

MacOS M1 Sonoma 14.1.2 (23B92)

### Steps to reproduce the behavior

1. Start the app. Expect to see a window opened.

### Log files

The log only shows:
info: [ui] Subscribed 'splintor' to Alive channel

### Screenshots

<img width="652" alt="image" src="https://github.com/desktop/desktop/assets/243549/abce88d5-aedb-4a36-8bf6-bd6b1c59831b">

**Comment by steveward** [comment]
Thanks for the report @splintor. Can you try deleting the following directory and then try launching GitHub Desktop again?

`~/Library/Application Support/Github Desktop/IndexedDB`

Let me know if that gets things working.

**Comment by splintor** [comment]
Yes!!
It forgot all my repositories, but I can add them and get back to work with GitHub Desktop. Thanks!
