### ISSUE TITLE
GithubApp Show In Explorer - Messes up Win.  Explorer navigation

### ISSUE THREAD

**Issue by Wolf1098** [desktop/desktop#17874]
### The problem

Something about the way its invoke it, messes with explorers default config, and seems to partially override what the user has set in windows. drawing both layouts of the quick access pane, one by the user set in windows, and one from being instantiated by githubs opening of the folder.

### Release version

3.3.6

### Operating system

win11 x64

### Steps to reproduce the behavior

have a default user, signed into microsoft after installed, so user called user, maybe the hyphen in my last name. but something is messing with the quick access pane, and I want it to stop please.

### Screenshots

![Screenshot (273)](https://github.com/desktop/desktop/assets/11269584/57ac8952-4516-4302-a47b-e46895672ed7)
![Screenshot (274)](https://github.com/desktop/desktop/assets/11269584/df72839f-65c1-4c39-bb17-9fce1eb2f643)

**Comment by steveward** [comment]
Thanks for the report @Wolf1098. This was previously reported in https://github.com/desktop/desktop/issues/13543, so I'll add this issue there and mark that for us to investigate.
