### ISSUE TITLE
Branch menu have all item disabled after stash for rebase

### ISSUE THREAD

**Issue by Maxd63** [desktop/desktop#17875]
### The problem

When I rebase my branch with ongoing changes, the popup saying "cannot rebase : you have unstaged changes" appear. After accepted to stash, all items in the branch menu become disable.

This can be resolved by doing alt+tab.

### Release version

3.3.6

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Make unstaged changes
2. Rebase your branch with other
3. Get the stash error
4. Accept and "Stash changes and continue"
5. Open the branch menu

### Screenshots

![image](https://github.com/desktop/desktop/assets/42872193/a93b0875-9bea-49f9-ace6-9bbd3fcf2862)

**Comment by steveward** [comment]
Thanks for the issue @Maxd63. This is being tracked in https://github.com/desktop/desktop/issues/7991 -- I'll bump that issue up. Switching from the `Changes` to `History` tab should get things working again as well.
