### ISSUE TITLE
Clone failed: Filename too long on Windows 11

### ISSUE THREAD

**Issue by rcgardne** [desktop/desktop#17882]
### The problem

Unable to clone repositories with too long of filenames on Windows 11 using GitHub Desktop.

### Release version

GitHub Desktop: Version 3.3.6 (x64)
Git: 2.43.0.windows.1

### Operating system

Windows 11 Pro for Workstations; OS Build = 22621.2861

### Steps to reproduce the behavior

# 1 - Ensure Windows OS allows long file names
## 1.1 - Edit Registry

1. Right-click Windows Start, then select Run. Type `regedit`
2. Click `Yes` to allow this app to make changes to your device
3. Within the opened registry editor, use the left navigation pane to navigate to `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem`
4. Double-click the entry `LongPathsEnabled`
5. Within the opened dialog, ensure the `Value data:` input value is set to `1`
6. If you changed `Value data:` input value, you will need to restart your machine

## 1.2 - Edit Group Policy

1. From the Windows taskbar search box, type `Edit group policy`
2. Within the `Local Group Policy Editor`, locate the `Computer Configuration` within the left navigation pane
3. Navigate to `Computer Configuration\Administrative Templates\System\Filesystem`
4. Double-click the `Enable Win32 long paths` setting entry
5. Within the opened dialog, click the `Enabled` option, then click the `Apply` button, then the `OK` button

# 2 - Clone a repo with file path longer than 260 characters

1. Open `Github Desktop`
8. Click dropdown `Select a repository`
9. Click dropdown `Add`
10. Choose option `Clone repository...`
11. Within the dialogue, click the tab `URL`
12. Enter a URL for a repo with long names; for example: `https://github.com/airbytehq/airbyte.git`
13. Click button `Clone`
14. Notice a resultant `Clone failed` dialog window

### Screenshots

![image](https://github.com/desktop/desktop/assets/44753721/460e1e54-365a-40a1-8cec-2aa1bebff668)

### Additional context

I also ran the following command on the terminal:

```bash
git config --system core.longpaths true
```

and also was able to clone from the terminal:

```bash
git clone https://github.com/airbytehq/airbyte.git
```

This gives me some confidence that the issue lies with GitHub Desktop

**Comment by rcgardne** [comment]
Forgot to mention that I also ran the following command on the terminal:

```bash
git config --system core.longpaths true
```

and also was able to clone from the terminal:

```bash
git clone https://github.com/airbytehq/airbyte.git
```

This gives me some confidence that the issue actually lies with GitHub Desktop

**Comment by niik** [comment]
Hey @rcgardne, thanks for reaching out. What version of Git do you have installed on your machine?

**Comment by rcgardne** [comment]
> Hey @rcgardne, thanks for reaching out. What version of Git do you have installed on your machine?

git version 2.43.0.windows.1

**Comment by dscho** [comment]
> `git config --system core.longpaths true`

@rcgardne In general, it is not a good idea to modify the system config of Git for Windows. Could you run `git config --global core.longpaths true` instead and see whether this fixes the problem for you?

**Comment by rcgardne** [comment]
> In general, it is not a good idea to modify the system config of Git for Windows. Could you run `git config --global core.longpaths true` instead and see whether this fixes the problem for you?

@dscho After executing `git config --global core.longpaths true` I was able to clone the longpath repo via GitHub Desktop - Thanks!

**Comment by dscho** [comment]
Hooray!

**Comment by tsvetilian-ty** [comment]
@rcgardne, I see your problem is resolved, so I'm closing the issue!
