### ISSUE TITLE
Show branch name in right-hand side of repository selector menu

### ISSUE THREAD

**Issue by jameswalkerhall** [desktop/desktop#17880]
### The feature request

Please show current branch name in selector menu, in the area shown in screenshot

### Proposed solution

As we our sofrware uses various libraries, we often work on matching branches of different libraries.  For example at critical time of stablising a release candidate, all libraries get a branch for that release. This will prevent mistakes in using wrong combination of branches.

### Additional context

![Screenshot 2023-12-15 222223](https://github.com/desktop/desktop/assets/118645168/15bc2796-922f-4d7e-a465-db23edbb2870)

**Comment by steveward** [comment]
Thanks for the issue @jameswalkerhall, this enhancement is being tracked in https://github.com/desktop/desktop/issues/8158 so you can follow along there for updates. I'll reference this issue there as well.
