### ISSUE TITLE
Docker crashes at startup

### ISSUE THREAD

**Issue by 45552e369** [desktop/desktop#17891]
### The problem

Diagnostics ID:     6030096B-6FF5-45F3-9A52-759D8110347C/20231218113100

### Release version

Docker Desktop issue

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Start Docker Desktop
2. Attempt to select options at start up screen before it disappears.
3. Receive error: Unexpected WSL error

Have tried all options, Quit, diagnose, reset Factory defaults.

Have Uninstalled - restarted - downloads fresh - reinstall multiple times & get same issue 

### Log files

.

### Screenshots

![image](https://github.com/desktop/desktop/assets/154229532/d367056a-0a64-498b-b31f-4938d6d5683b)
![image](https://github.com/desktop/desktop/assets/154229532/e19d3b12-a44a-4cb4-9b3f-4a09292b7a6d)
![image](https://github.com/desktop/desktop/assets/154229532/13f86967-d002-41e8-8759-bfeae2b6e6d7)

### Additional context

.

**Comment by moxie-coder** [comment]
this isn’t the right repository for this issue, [report it here](https://github.com/docker/for-win) as this is the repository for github desktop

**Comment by tsvetilian-ty** [comment]
As @MemeHovy mentioned, this is the GitHub Desktop repo. I will close the issue!
