### ISSUE TITLE
cant clone repository from internet

### ISSUE THREAD

**Issue by Neposedov225** [desktop/desktop#17895]
### The problem

![изображение_2023-12-20_225450872](https://github.com/desktop/desktop/assets/136234128/4b18cf66-0d30-4776-ac93-fa675a99c22f)
Trying to download HOI4 mod. Ive already downloaded it once some time ago, but it deleted itself and I needed to redownload it. I tried to download it but Im getting this error each time I try. I tried to download different mod, but it didnt work.

### Release version

Version 3.3.6 (x64)

### Operating system

Windows 10

**Comment by tisaconundrum2** [comment]
What happens when you click on the `retry clone`?

**Comment by sanechekmyflow** [comment]
Uhh

**Comment by Neposedov225** [comment]
> What happens when you click on the `retry clone`?
@tisaconundrum2 
same error (sry, I wasnt able to reply)

**Comment by 5150og** [comment]
Why you trying to clone my reposatory

**Comment by Krperson88** [comment]
How .g I'm new here.  Just jumped in the game

Sent
Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tisaconundrum2** [comment]
I think ultimately if you can't get this to work, just try cloning from the terminal, and then link Desktop to the folder.

**Comment by tidy-dev** [comment]
@Neposedov225 Seconding @tisaconundrum2, have you tried cloning via the command line? That error would lead me to think you may not have stable internet connect and if so cloning via the command line may not work either.

**Comment by Neposedov225** [comment]
Guys, it seems like I just had wifi problems for a couple days (even tho everything else worked fine), but now everything works. Thanks everyone who tried to help me!
