### ISSUE TITLE
Please re-open #9156 - Seting to hide recent repositories

### ISSUE THREAD

**Issue by serg3y** [desktop/desktop#17893]
### The feature request

Please see [issue](https://github.com/desktop/desktop/issues/9156)

### Proposed solution

Please see https://github.com/desktop/desktop/issues/9156

**Comment by niik** [comment]
If you have context to add that's not adequately captured in an issue and that you feel would influence our decision feel free to open up a new issue but please refrain from creating new issues only to request reopening old ones without adding any helpful context. We do re-evaluate closed issues either when new context arises, our product planning changes, or on user requests. As we stated in https://github.com/desktop/desktop/issues/11598#issuecomment-917204596 please use the reactions feature on the original issue to indicate that this is something you'd like. We continually look at our top issues with lots of reactions or interactions to influence our feature planning.

**Comment by serg3y** [comment]
Ok. But everything has already been said by many people, many times, in multiple requests. It's a small change and would make for a big improvement. No matter how much I use Desktop i still get confused when see the same repos appear twice in the list...

**Comment by rumrunner0** [comment]
It's true. This option is a tiny little feature that can significantly enhance the appearance of the repository list. I can confirm that I'm often confused when navigating through my repository list section. This little easy-to-implement (hope so) feature would make the app just BETTER.

**Comment by marclammerding** [comment]
Please implement!

**Comment by quisido** [comment]
>We continually look at our top issues with lots of reactions or interactions to influence our feature planning.

_Do you, though?_
