### ISSUE TITLE
Support for scalar and sparse-checkout

### ISSUE THREAD

**Issue by brasky** [desktop/desktop#17901]
### The feature request

Problem: Using the clone feature in GitHub Desktop defaults to using `git clone <url>`

Feature Request: 
Add the ability to run: 
- `scalar clone <url>` 
- `git sparse-checkout set <dir1> ... <dirN>`
- `git sparse-checkout add <dir>`

Supporting these features would assist organizations with less technical git users to adopt scalar and sparse-checkout for use with large repositories.

### How it helps GitHub Desktop and its users

The use-case for this feature that I am advocating for is game development. Games are typically in large repos (by disk size and by file count) where the person/machine cloning the repo is typically not interested in getting the entire thing.

Today to solve this problem studios use a competitor, Perforce, which allows users to specify client workspaces in a GUI application (P4V) and only sync specific folders.

The primary arguments against switching to git in the gaming industry are:
| Argument | Response |
|--------|--------|
| Git doesn't handle large binary file diffs well | ✅ Solved with Git LFS and this is integrated into GitHub Desktop |
| Git does not support syncing only the folders I need to do my work (partial clone) | ❌Scalar bundles all the features required together and makes them easy to use, but is not supported in Github Desktop for the people who need it most (artists). | 
| Git doesn't have a GUI application for non-technical people to use and avoid the command line | ❌ GitHub Desktop is more approachable and easier to use than P4V but it does not support all the features required for day-to-day use |
| Git doesn't support exclusive checkout | ❌ While LFS does support this, it is not available in GitHub Desktop. I think this is a separate issue as it is not related to scalar and scalar is arguably more impactful. It looks like there was conversation on #8419 recently. |

Most people in the games industry don't know that all of these problems are already solved if you can use a terminal. Upon learning about all of these new(ish) developments in git and realizing it's possible to get away from P4, they will eventually respond with, "but what about the artists". 

I believe the lack of feature complete git UI is the final blocker.

**Comment by tidy-dev** [comment]
@brasky Thank you for the well-written suggestion! This appears to be similar in request to #12567. Thus, I have copied your feedback there and closing this in favor of having one tracking issue.
