### ISSUE TITLE
Empty folders repositories

### ISSUE THREAD

**Issue by raoalihassan228** [desktop/desktop#17908]
### The problem

When I am adding new local repositories on github via github desktop then the sub folders are not shown , only one empty folder is showing

### Release version

latest

### Operating system

hp i5 intel core5

**Comment by tidy-dev** [comment]
@raoalihassan0228 Is it possible that the sub folders are empty? [Git will not track empty directories](https://archive.kernel.org/oldwiki/git.wiki.kernel.org/index.php/GitFaq.html#Can_I_add_empty_directories.3F). They will be tracked once there are files in them. Many people will work around this by adding a hidden file or a simple readme if having the empty directory is if high importance.

**Comment by raoalihassan228** [comment]
![Screenshot (56)](https://github.com/desktop/desktop/assets/139099370/515b10f8-8fb5-4a46-806c-f4d5e3c3c4a6)

@tidy-dev  It shows "**This file is empty**" for all files (which are non-empty) in one repository.

**Comment by tidy-dev** [comment]
@raoalihassan0228 Interesting. Are those files`.js` or `.ts` files? In the screenshot, it doesn't show them as having a file extension. Curious if that could be the issue?

**Comment by tidy-dev** [comment]
Also, could you upload the logs `To access the log files go to the menu and select Help > Show Logs` for the time you are seeing this?

**Comment by raoalihassan228** [comment]
> @raoalihassan0228 Interesting. Are those files`.js` or `.ts` files? In the screenshot, it doesn't show them as having a file extension. Curious if that could be the issue?

**Comment by raoalihassan228** [comment]
> > @raoalihassan0228 Interesting. Are those files`.js` or `.ts` files? In the screenshot, it doesn't show them as having a file extension. Curious if that could be the issue?

these are the folders which have `.tsx` files, but these files are not showing, it shows them as empty

**Comment by steveward** [comment]
@raoalihassan0228 can you share the contents of the `.gitignore` for your repository? You can check it in GitHub Desktop. by going to `Repository` > `Repository Settings` > `Ignored Files`.

**Comment by raoalihassan228** [comment]
@steveward 
![Screenshot (58)](https://github.com/desktop/desktop/assets/139099370/4920aec0-23cc-4875-a62d-a60d3b395cbc)
Here is `Ignored files` which is empty

**Comment by steveward** [comment]
@raoalihassan0228 can you open the repository in the command line ('Repository' > 'Open in...') and see if `git status` shows the same output?

**Comment by raoalihassan228** [comment]
![Screenshot (60)](https://github.com/desktop/desktop/assets/139099370/663c329e-dab2-4074-9b6d-738bbeb4bc03)
@steveward @tidy-dev  when  I try to push my folder on github, then the `.git` folder makes atomatically, please look at screenshot

**Comment by raoalihassan228** [comment]
![Screenshot (61)](https://github.com/desktop/desktop/assets/139099370/2223450a-ebd7-4a90-b9b7-8a124c41449d)
these are in the `.git` folders

**Comment by steveward** [comment]
@raoalihassan0228 is the CodSoft directory your main repository? Are the other three folders (like your todo-app) also supposed to be separate repositories? If you have nested .git directories that could be causing issues.
