### ISSUE TITLE
Scroll position resets when scrolling after expanding collapsed (unchanged) lines

### ISSUE THREAD

**Issue by antialiasis** [desktop/desktop#17900]
### The problem

Lately I've been having a problem with GitHub desktop where the scroll position is consistently reset to the top when I try to scroll after expanding some collapsed lines, and generally does it again shortly after the initial jump too. See attached screen recording.

https://github.com/desktop/desktop/assets/1326447/f1ea47cc-9e0b-451c-a5df-a73a27c0ea60

### Release version

3.3.6 (x64)

### Operating system

MacOS Sonoma 14.2.1

### Steps to reproduce the behavior

1. Look at a diff for a file that has a large number of collapsed unchanged lines.
2. Click the expand button on the left next to some of the collapsed lines.
3. Scroll down (I've had the issue both scrolling down with a mouse wheel, trackpad, and the down arrow key).

**Comment by tidy-dev** [comment]
@antialiasis [This is fixed ](https://github.com/desktop/desktop/issues/17776)in beta. It will ship to production in the next release. However, that will not be till after the new year, you are welcome to [try the latest beta](https://desktop.github.com/beta/).
