### ISSUE TITLE
git files in sub folder of local repo

### ISSUE THREAD

**Issue by pmcmahon0** [desktop/desktop#1792]
### Description

Because of our in-house containerized runtime environment our git config files are not under the top-level folder for the repo--'repo-name', for example. Instead it is in a sub-folder called 'git'--'repo-name/git'. As such the name of the repo in the desktop UI is 'git'. Granted, there is a tooltip that will show the path to the local repo, but it would be nice to be able to assign a name to it.

This was not a problem with an older version of desktop.

**GitHub Desktop version:** [0.5.8]

**OS version:** [10.9.5]

**Comment by joshaber** [comment]
Would #664 help with this issue?

**Comment by pmcmahon0** [comment]
Yes, https://github.com/desktop/desktop/issues/664 would help, thanks. Closing this.
