### ISSUE TITLE
github desktop update issues

### ISSUE THREAD

**Issue by Dan-Essin** [desktop/desktop#17926]
### The problem

1 - No status message that update is running until you try to quit
2 - update runs endlessly but threaten dire consequences if quit 
3 - no setting to configure app updates

### Release version

 3.2.3

### Operating system

win 11

### Steps to reproduce the behavior

1 - launch
2 - quit
3 - get notified not to quit
4 - wait 20 minutes
5 - update not done downloading

### Log files

[2023-12-26.desktop.production.log](https://github.com/desktop/desktop/files/13773655/2023-12-26.desktop.production.log)

**Comment by tidy-dev** [comment]
@Dan-Essin Did you quit anyway and what happened when you re-opened?

It is true that it can lead to an incomplete update process if you quit mid update. If you do that and are experiencing issues after launching, I would recommend uninstalling and installing directly from the latest at desktop.github.com.

**Comment by Repairman-Running** [comment]
> ### ปัญหา
> 1 - ไม่มีข้อความสถานะที่การอัปเดตกำลังทำงานอยู่จนกว่าคุณจะพยายามออก 2 - การอัปเดตจะทำงานอย่างไม่มีที่สิ้นสุด แต่อาจส่งผลร้ายแรงหากออกจาก 3 - ไม่มีการตั้งค่าเพื่อกำหนดค่าการอัปเดตแอป
> 
> ### รุ่นที่วางจำหน่าย
> 3.2.3
> 
> ### ระบบปฏิบัติการ
> ชนะ 11
> 
> ### ขั้นตอนในการทำซ้ำพฤติกรรม
> 1 - เปิดตัว 2 - ออก 3 - รับการแจ้งเตือนไม่ให้ออก 4 - รอ 20 นาที 5 - อัปเดตยังดาวน์โหลดไม่เสร็จ
> 
> ### ไฟล์บันทึก
> [26-12-2023.desktop.production.log](https://github.com/desktop/desktop/files/13773655/2023-12-26.desktop.production.log)
> 
> ### 5544391:Repairman_Running-186920305815223213612.php-FAILED_PRCONDITION+855881@googlegroup.com
> _855881:Repairman_Running-543202+1097603@google.com_
> 
> ### Repairman_Running
> _FAILED_PRCONDITION_
