### ISSUE TITLE
Merge request dialog: Error merge information

### ISSUE THREAD

**Issue by GengShengJia** [desktop/desktop#17929]
### The problem

![企业微信截图_da3af112-e252-4e14-9c38-93e3e29f43e3](https://github.com/desktop/desktop/assets/61140247/a529b585-8f3d-4d36-90e6-65b6e084f4d6)

After opening the Merge dialog, Immediately select the branches to merge, but Merge prompts to merge the **root node**。
Whether this problem can be solved

### Release version

Version 3.3.6 (arm64)

### Operating system

Macos14.0

**Comment by tidy-dev** [comment]
@ShengjiaGeng I am unable to reproduce this behavior. Is it a consistent behavior? Could you provide the logs for the time it happened and a screen share showing the issue?

**Comment by GengShengJia** [comment]
![Kapture 2023-12-28 at 09 24 21](https://github.com/desktop/desktop/assets/61140247/7b71dd8c-4191-4d3e-9757-1fba14c62912)

This is a question of probability，i think it may be that the main branch query is too slow, the branchs i chose loads faster than the main branch, so this situation is happened🙏

**Comment by tidy-dev** [comment]
@ShengjiaGeng Thanks for the reply and the report. I was able to reproduce by forcing a slow first merge check in the code. I have fix to prevent using stale branch selection data.

**Comment by GengShengJia** [comment]
Thanks for your answer, I will continue to pay attention to the development of the desktop

**Comment by rizwan123912** [comment]
Happy birthday to you
