### ISSUE TITLE
Github desktop while conflicts

### ISSUE THREAD

**Issue by SandrikaJanjghava** [desktop/desktop#17933]
### The problem

Hello. On Macbook, when merging branches, if there is some conflict, when you click on finder, it does not show.  When you see it in "Force quit applications" window, the "Finder" is not reposnding, it crashes the Finder app. Macbook Pro 2021 M1, macOs Sonoma 14.0 .

### Release version

3.3.6

### Operating system

macOs Sonoma 14.0

**Comment by tidy-dev** [comment]
@SandrikaJanjghava I was able to reproduce.  Thank you for the report.

I also tried open the repository in finder or a file in the changes list in finder. Both work as expected.

**Comment by SandrikaJanjghava** [comment]
Thanks for you answer. Maybe dependes on other things? Also have written version of Github desktop and Macos, maybe something else?

**Comment by tidy-dev** [comment]
> Also have written version of Github desktop and Macos, maybe something else?

Seeing as I know this has not always been the case, I am suspecting that either with an Electron or with an macOS update there has been some change in how the opening in finder works. I was able to fix it by using the same logic from the changes list in this location, but I have not nailed down the cause.
