### ISSUE TITLE
when repository list expanded, tab order should not leave repository list

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1793]
User with no repos can use the `tab` button to navigate out the Repo list, and hit the new repo options in the background. At some point the Repo list should be forcibly closed as it blocks the user from seeing the `Create New Repo` button.

<img width="1083" alt="screen shot 2017-05-26 at 10 55 48 am" src="https://cloud.githubusercontent.com/assets/14828183/26499949/440164f6-4202-11e7-9600-33a9a8c408b9.png">
<img width="1090" alt="screen shot 2017-05-26 at 10 55 59 am" src="https://cloud.githubusercontent.com/assets/14828183/26499950/440727ce-4202-11e7-9782-2cacba64f20b.png">

v0.5.8 OSX 10.11.5

**Comment by tierninho** [comment]
related to #1500

**Comment by say25** [comment]
Looked into this when attempting to fix #1500 with #2014. Why is it even possible to click the "RepoList" button when there are no cloned repos? I feel like the button should be disabled. Maybe I am wrong? Its also kinda weird to me that with no repos the escape key doesn't dismiss the "RepoList" either.

**Comment by joshaber** [comment]
Yup, that's what https://github.com/desktop/desktop/issues/1476 is tracking. The button shouldn't be there if there are no repositories.

**Comment by shiftkey** [comment]
> At some point the Repo list should be forcibly closed as it blocks the user from seeing the `Create New Repo` button.

I think the focus here should stay _within_ the repository list when it's expanded, and the things underneath should not be accessible. But I'm hazy on how we're managing focus and tab order in the app so I need to dig into this again.

**Comment by tierninho** [comment]
Closing this as it has not come up enough times to be validated as a real problem.
