### ISSUE TITLE
Submodule contents not visible in commit

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1794]
If a user is only committing folders, then the content should appear in the Changes files, or at least be exposed in a manner where the user can drill down to see the file content, else Desktop just says `the file is empty`. 

Also, the Changes list says `X changed files` which is technically wrong as file ≠ folder.

V 0.5.8, OSX 10.11.5

Reproduce:
- Add new folder to local (make sure it is only commit change)

<img width="767" alt="screen shot 2017-05-26 at 11 24 38 am" src="https://cloud.githubusercontent.com/assets/14828183/26501182/cf178972-4206-11e7-85df-afaf9f32f13e.png">

**Comment by shiftkey** [comment]
@tierninho show me what the corresponding `git status` output is for this repository, so I can have a go at recreating this...

**Comment by tierninho** [comment]
@shiftkey Here is the output:
<img width="554" alt="screen shot 2017-05-26 at 11 42 06 am" src="https://cloud.githubusercontent.com/assets/14828183/26501735/6b8bed9c-4208-11e7-99dd-244cbeb97b12.png">

I had removed the repo, and then added it back in locally (if it makes a difference). Then I noticed the folders ready to be committed. I believe they are other repos as part of testing repo within a repo. Bizarre I know 😄

**Comment by shiftkey** [comment]
@tierninho you caught me before the edit. This is how we do it in the app:

`git status --porcelain=2 --untracked-files=all --branch`

**Comment by shiftkey** [comment]
>  I believe they are other repos as part of testing repo within a repo. 

Oh, this tidbit is interesting. Sounds like they might be (untracked) submodules, which might be something we're not handling well.

**Comment by tierninho** [comment]
Upgraded git to version 2.13.0. Tried again and everything worked normally.

Console logs for the push:
<img width="1112" alt="screen shot 2017-05-26 at 2 29 40 pm" src="https://cloud.githubusercontent.com/assets/14828183/26507773/e27d9a88-421f-11e7-8bce-c858b2756d24.png">

**Comment by tierninho** [comment]
Closing this as it has not come up enough times to be validated as a real problem.

**Comment by Tronadis** [comment]
I noticed this behaviour today, with GitHub Desktop version 3.2.4 (x64).
