### ISSUE TITLE
created new file or folder is not show in GitHub desktop changes files list

### ISSUE THREAD

**Issue by ajitrai123** [desktop/desktop#17946]
### The feature request

I am Using GitHub Desktop I am creating a new folder and file on local then  I am going to commit on GitHub server but in changes files list these folder and files are not so I am looking all application features but there are no any button for refresh list and due to these problem I am not able to commit new folder and files.

### Proposed solution

after refresh option user can find those folder in changes list and then easily and make his commit easily.

**Comment by steveward** [comment]
@ajitrai123 thanks for the issue. For reference, Git does not track empty folders, so if your folder does not have any files it will not appear in GitHub Desktop.

If files are not appearing it's possible you have a .gitignore file that is causing those files to be ignored. You can check this by going to `Repository` > `Repository Settings` > `Ignored Files`. If you can share the contents of your `.gitignore I can verify if that is the issue.
