### ISSUE TITLE
Allow Pinning Repos

### ISSUE THREAD

**Issue by arunim2405** [desktop/desktop#17953]
### The feature request

When dealing with 100s of repos, it would be nice to have the ability to pin the repos which I frequently use to top.

### Proposed solution

Allow users to pin repositories, once Pinned, They will be displayed in a separate section called Pinned like Recent on the top

**Comment by tidy-dev** [comment]
@arunim2405 Thank you for the suggestion! We are tracking feedback for this in #8183. Thus, I am going to close this in favor of tracking it there.

**Comment by hrgdavor** [comment]
> @arunim2405 Thank you for the suggestion! We are tracking feedback for this in #8183. Thus, I am going to close this in favor of tracking it there.

ATM https://github.com/desktop/desktop/issues/8183 is closed, why not just say taht you will not implement it, even it is requested 2019
