### ISSUE TITLE
Tag show wrong name in desktop

### ISSUE THREAD

**Issue by LiuAoran** [desktop/desktop#17952]
### The problem

the name of tag in Desktop looks like:
![image](https://github.com/desktop/desktop/assets/108785628/743225d3-f7e1-453a-9632-7c534aefa10d)
but it's really name is:
![image](https://github.com/desktop/desktop/assets/108785628/161832d1-0b66-4f8c-b6c4-45fe46d9d441)
I can't see the right name

### Release version

3.3.6

### Operating system

Windows 11

**Comment by tidy-dev** [comment]
@LiuAoran Thank you for the report. I have a fix up for review. :)

**Comment by LiuAoran** [comment]
Thanks👍

**Comment by LiuAoran** [comment]
> @LiuAoran Thank you for the report. I have a fix up for review. :)

thanks! 👍
