### ISSUE TITLE
Unable to see stashes in Git Desktop, where as it can be seen on VS

### ISSUE THREAD

**Issue by ajaycxpo** [desktop/desktop#17958]
### The problem

Hello Team,
I am unable to see stashes in Git Desktop, where as it can be seen on Visual Studio.
I don't know for some reason its displayed in Git

Thanks,
Ajay

### Release version

3.3.6

### Operating system

Windows 10 x64

**Comment by steveward** [comment]
Thanks for the issue @ajaycxpo. This behavior is per-design, see https://github.com/desktop/desktop/issues/6107 for our reasoning around choosing this implementation.

I'm going to close this in favor of https://github.com/desktop/desktop/issues/12699, which is a tracking issue for similar feature.
