### ISSUE TITLE
Add Hard Branch Reset to UI

### ISSUE THREAD

**Issue by omnipitous** [desktop/desktop#17960]
### The feature request

This is a mix of a bug and a feature.. I have periodically had my Github UI get into a state for a given branch where it shows I have changes to push UP as well as pull down even though I've made absolutely no changes locally to the branch. This happens very typically when someone else has force pushed / rebased the branch but I've seen it "just happen" (ergo I can't see a clear trigger.. it just suddenly sees a bunch of files marked as changed).  

### Proposed solution

Easy Button on the Branch menu to Hard Reset ANY branch from Origin. Currently have to drop to command line to get this done.

### Additional context

![NoLocalChanges](https://github.com/desktop/desktop/assets/5626621/6dd32ffc-6ead-4bb7-ab94-db2f1687b870)

**Comment by steveward** [comment]
Thanks for the issue @omnipitous, I'm going to add this to https://github.com/desktop/desktop/issues/5860 where we are tracking feedback about this.
