### ISSUE TITLE
Can't sign in on Steam Deck (Linux). It says "The name org.freedesktop.secrets was not provided by any .service files"

### ISSUE THREAD

**Issue by dragon3025** [desktop/desktop#17964]
### The problem

When I sign in it opens the browser, closes it real fast, then gives me the error: "The name org.freedesktop.secrets was not provided by any .service files".

### Release version

Version 3.3.6-linux3 (x64)

### Operating system

Steam Deck

### Log files

Clicking Help > Show Logs in your File Manager didn't do anything.

**Comment by sergiou87** [comment]
@dragon3025  issues related to the unofficial Linux fork of GitHub Desktop can be filed here:

https://github.com/shiftkey/desktop/issues

At this time we only officially provide support for macOS and Windows.

Sorry!

**Comment by dragon3025** [comment]
Oh, I found the issue in their issue tracker. For anyone who finds this, the issue being tracked here: https://github.com/shiftkey/desktop/issues/986
