### ISSUE TITLE
Problem while opening in vs code

### ISSUE THREAD

**Issue by Rvk18** [desktop/desktop#17962]
### The problem

I have attached the screenshot

### Release version

Version 3.3.6 (x64)

### Operating system

Windows 11

### Screenshots

![Screenshot 2024-01-05 125120](https://github.com/desktop/desktop/assets/130183569/54807269-11e8-4d47-9c93-82d2170a3844)

**Comment by steveward** [comment]
@Rvk18 thanks for the issue -- please see [this comment](https://github.com/desktop/desktop/issues/14202#issuecomment-1072376656) to verify your `Comspect` variable is correct. Let me know if that doesn't get things working.
