### ISSUE TITLE
Please display actual commit dates in commit history

### ISSUE THREAD

**Issue by cfrupp** [desktop/desktop#17976]
### The feature request

In the GitHub Desktop History tab, please allow commit dates to appear as the actual date (e.g. 2 January 2023) instead of a relative value (e.g. 6 days ago).

### Proposed solution

We are almost never interested in the elapsed time. We want to locate a specific commit (e.g. "Fred made this change last Tuesday"), and we don't want to do unnecessary mental arithmetic.

If many users prefer the elapsed time, please consider making this configurable.

**Comment by steveward** [comment]
Thanks for the issue @cfrupp . You can hover over the relative date to see the absolute date (the same as on github.com). We're also tracking feedback about this in https://github.com/desktop/desktop/issues/14611.

**Comment by snielsson** [comment]
Yes, please make it configurable - super annoying when reviewing a list of releases just saying "last month"  why? I think most developers would just prefer precise date timestamp.
