### ISSUE TITLE
Update "Install Git" link

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#1797]
We [are currently](https://github.com/desktop/desktop/blob/3dc8738e711131047f9973398a5dac08e2cd206e/app/src/ui/install-git/install.tsx#L40) linking to an old subsection of https://help.github.com/articles/set-up-git. We should instead link to https://help.github.com/articles/set-up-git/#setting-up-git.

**Comment by divayprakash** [comment]
On it!
