### ISSUE TITLE
Authentication issue while using Github Desktop.

### ISSUE THREAD

**Issue by Krushna-Pranab** [desktop/desktop#17971]
### The problem

Whenever I click on fetch origin, I see the following message.

Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.

I have tried logging out and logging in but still get the same results. Please help me with it.

### Release version

Version 3.3.6 (x64)

### Operating system

Windows 11

### Log files

[2024-01-05.desktop.production.log](https://github.com/desktop/desktop/files/13852043/2024-01-05.desktop.production.log)

### Additional context

I am working on a web dev project. I started by cloning the repo using a personal access token. But for 2 months, I have been unable to either fetch or push my contributions to the main branch.

**Comment by steveward** [comment]
@Krushna-Pranab thanks for the issue. Can you verify you have the correct access permissions for the repository you are working with? Are you encountering this issue on personal repositories? If you can clone repositories from your own GitHub account then this is a specific access permissions with the repository you are trying to work with.

**Comment by GQ16** [comment]
@Krushna-Pranab  I have the same issue. I'm using SSH verification, and when I do it through my IDE (Eclipse, in this case) I have no problems at all pushing,pulling,fetching, etc. But when I try to fetch from or use GitHub Desktop in any way, I get the exact same error you're sharing.

@steveward @sergiou87 
I believe it has to do with some conflicts between my local git and GitHub desktop. When I clone a repo from github to my downloads folder using GitHub Desktop, I have no issues comparing, pushing, fetching, etc. But when I open a repo from my git folder that is cloned from my GitHub repo, or when I try to clone it straight from GitHub into GitHub desktop and land it in my local Git folder, I get the error:
![image](https://github.com/desktop/desktop/assets/107271596/d7ef1136-8d96-4144-a18f-8d293944d7ba)
