### ISSUE TITLE
IntelliJ is not integrated anymore since Windows Version 3.3.6 (x64)

### ISSUE THREAD

**Issue by mengmengh2022** [desktop/desktop#17986]
### The problem

I would like to report the following issue:
IntelliJ is not integrated anymore since Windows Version 3.3.6 (x64)
In the past, IntelliJ was integrated. This is an incompatible change with the version update.

### Release version

3.3.6 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Click on File -> Options
2. Click on Integrations
3. Open drop down of "External editor".
4. IntelliJ is not in the drop down.

### Screenshots

![image](https://github.com/desktop/desktop/assets/119863146/772ccd6a-79cb-4e3f-b995-6d7db8b66144)

**Comment by steveward** [comment]
Thanks for the report @mengmengh2022, it's possible JetBrains made a change that broke this. I'll take a look.

**Comment by mengmengh2022** [comment]
Hi @steveward, thanks for checking it!

**Comment by mengmengh2022** [comment]
My IntelliJ version is: 
IntelliJ IDEA 2023.3.2 (Ultimate Edition)
Build #IU-233.13135.103, built on December 20, 2023

**Comment by steveward** [comment]
I just tested this on a Windows 10 machine and IntelliJ was showing up correctly in GitHub Desktop:

<img width="656" alt="Screenshot 2024-01-11 at 11 48 37 AM" src="https://github.com/desktop/desktop/assets/721500/46dadf1b-dada-42b8-ad15-a9b09a72f5e3">

Did you install this via the standard installer or by using Jetbrains Toolbox?

**Comment by mengmengh2022** [comment]
Strange, I installed with standard installer.

**Comment by steveward** [comment]
Hmm, do you have any other JetBrains IDEs? Curious to see if any others are having this same issue on your machine.

**Comment by mengmengh2022** [comment]
Hi @steveward, thanks for the question, I only have this Intellij installed. I have no idea why it stopped to support the IDEA.

**Comment by mengmengh2022** [comment]
Do you know if there are any logs from Github that I can send you to analyze?

**Comment by steveward** [comment]
Can you try installing another JetBrains IDE to see if you are able to reproduce this? We [generate a string](https://github.com/desktop/desktop/blob/development/app/src/lib/editors/win32.ts#L95) to match the registry key used for JetBrains IDEs, so that would help narrow down the issue.

**Comment by mengmengh2022** [comment]
Sure! I installed the Jetbrains IDE "aqua" windows version from the official webpage. In Github desktop, it is still not supported.
![image](https://github.com/desktop/desktop/assets/119863146/304dfe2a-dfcd-46d4-b163-32a94adde69d)
![image](https://github.com/desktop/desktop/assets/119863146/69efe238-21ad-4329-8092-9c0d18f6900c)

**Comment by tsvetilian-ty** [comment]
Hey there @mengmengh2022. Aqua is not a good candidate for the test since it's still in preview and is not supported by GitHub Desktop yet. A better choice is to try PyCharm, for example!

I also tested with the same version of Intellij Idea and didn't have any issues:
![image](https://github.com/desktop/desktop/assets/9341546/fac47464-cb41-456e-a744-7405594f2590)

Could you check if `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\IntelliJ IDEA 2023.3.2` is available in your Windows registry? We use this address to find your version of Intellij Idea specifically.

**Comment by mengmengh2022** [comment]
Hello @tsvetilian-ty , thanks for the reply. I checked my registry, I only have `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\IntelliJ IDEA 2021.2` but not `"...\IntelliJ IDEA 2023.3.2"` in my registry. Is that the cause?

**Comment by tsvetilian-ty** [comment]
@mengmengh2022 that is the reason for the issue! Your IDEA entry is too old (after the start of 2024). GitHub Desktop will detect entries that are from the [last two years](https://github.com/desktop/desktop/blob/211ef8fc58356d6335256e9515ba698f0002d941/app/src/lib/editors/win32.ts#L96). 

You could try to reinstall your IntelliJ IDEA (uninstall and install again) to see if it will update the registry entry and the GitHub Desktop detection.

**Comment by mengmengh2022** [comment]
Hi @tsvetilian-ty, after the reinstallation it works now, thank you a lot for the solution!

**Comment by DmytroFesyk** [comment]
Hi @tsvetilian-ty 
I have the same issue, I am just curious why this 2 years limit is exists?
When I update IntelliJ IDEA the registry value not updated ( it is how updates works), you suggest reinstalling the application but this action requires reinstallation all plugins, this is not what I would like to do.
If there is any chance to lift the limitations in 2 years?

**Comment by DmytroFesyk** [comment]
I believe that 50 will be enough to cover all possible issues associated with this :smiley:
