### ISSUE TITLE
Canoot login on git lab with git hub account

### ISSUE THREAD

**Issue by xbkappa** [desktop/desktop#17988]
### The problem

I cannot login on git lab with my github account i put down the email and the password and says couldnt connect with git lab

### Release version

3.3.6

### Operating system

windows 11

**Comment by steveward** [comment]
@xbkappa thanks for the issue. To authenticate with Gitlab using GitHub Desktop you can follow [this guide](https://github.com/desktop/desktop/blob/development/docs/integrations/gitlab.md). I hope that helps!
