### ISSUE TITLE
Select Multiple files at once to discard them

### ISSUE THREAD

**Issue by stephenbe** [desktop/desktop#1799]
### Description
I would like to see the possibility to select multiple files in the changes view

### Version
**GitHub Desktop version:** 0.5.8
**OS version:** Windows 7

### Steps to Reproduce
![github for windows](https://cloud.githubusercontent.com/assets/3018441/26509728/0b07a5d6-4228-11e7-9297-09183a4c2c88.gif)

Here you can see I would like to do : 
1. Select first file
2. press shift
3. Select second file **everything in between gets selected**
4. Right click on selection and click discard

Something similar to this : 
![github for windows2](https://cloud.githubusercontent.com/assets/3018441/26511366/b208d2ae-422f-11e7-8f3c-bd2b1d0e8c35.gif)

**Expected behaviour:** When I click the second file, every file in between would be selected

**Actual behaviour:** The first file gets deselected (basically you can select only one file at a time)
**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
This has been previously reported in #1712. Please add your feedback there.

**Comment by chikuba** [comment]
Hold on, did @shiftkey just close both of them, linking them to each other?

**Comment by gloinart** [comment]
+1 ! Really need this

**Comment by Nicktz** [comment]
Cannot understand why I still have to manually select hundreds of commits.. My only option when selecting multiple files is to discard or ignore them collectively, not to select them all for commit: 

![image](https://user-images.githubusercontent.com/14888246/49082327-295cfc80-f252-11e8-9117-3cc9621fcb3c.png)

Please add a multi-select option here....

**Comment by shiftkey** [comment]
@Nicktz apologies for the delay in replying. With multiple items entered you can press <kbd>Space</kbd> or <kbd>Enter</kbd> to include/exclude them in the commit.
