### ISSUE TITLE
Stuck at Rebasing branch

### ISSUE THREAD

**Issue by NunoG-ND** [desktop/desktop#17994]
### The problem

For some reason I had selected a branch that doesn't exist anymore, and there was selecting a rebase for the branch with lots of files to be added. I then discard all of those files. 
Now I continue to have on "changes" tab the button with text "Continue rebase" and I cannot change the branch because its disabled.

### Release version

Version 3.3.6 (x64)

### Operating system

Windows 11

### Screenshots

![image](https://github.com/desktop/desktop/assets/136073460/fe0438fe-133e-4ec5-b534-e47c4710ae6e)

**Comment by steveward** [comment]
Thanks for the report @NunoG-ND. If you're stuck in a rebase you should be able to get out of it by running `git rebase --abort` from the command line. 

I can also take a look at the log file to see if that shows anything helpful about what might have happened. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
