### ISSUE TITLE
Fetch timestamp displaying incorrectly

### ISSUE THREAD

**Issue by anthonyryanrusso** [desktop/desktop#18003]
### The problem

The timestamp within the fetch button is displaying last fetched 24 years ago.

I've done the following to try and remedy the issue:
1. Uninstalled/Re-installed GitHub Desktop
2. Synced date/time within Windows with their provided sync button
3. Tried to fetch again after all of this

### Release version

3.3.6

### Operating system

Windows 11

### Screenshots

![last fetched](https://github.com/desktop/desktop/assets/11683876/e9287a8d-030b-404a-94ba-f5aeb2e3b925)

**Comment by steveward** [comment]
Thanks for the report @anthonyryanrusso! I checked and we haven't seen any other previous reports of this. Do other timestamps show correctly, like commits in the `History` view?

**Comment by anthonyryanrusso** [comment]
Yes all of the commits in history view show the correct timestamp.

**Comment by steveward** [comment]
Can you try clearing out the cached data to 'reset' the app?

1. Close GitHub Desktop
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop

You will need to log in and add your repositories again, which can be done quickly in bulk by drag-and-drop.

Let me know if that helps.

**Comment by anthonyryanrusso** [comment]
This didn't help but after some thought I looked at the date/time of the folders of where the local repos were being stored and it turned out to be an issue with my NAS date/time.

**Comment by steveward** [comment]
Glad to hear you were able to get things resolved!
