### ISSUE TITLE
Ignore folder

### ISSUE THREAD

**Issue by ajtruckle** [desktop/desktop#18002]
### The feature request

It is possible to add a new option to Ignore a folder to this context menu:

![image](https://github.com/desktop/desktop/assets/7985331/5a6f8b40-1772-4944-89c1-b1e319b3cdc2)

### Proposed solution

For example, I would like an easy way to exclude the `Inno\S-140` folder and everything in it, no matter the file type.

**Comment by steveward** [comment]
@ajtruckle this will be coming once https://github.com/desktop/desktop/pull/17894 is merged and released -- I hope that helps!

**Comment by ajtruckle** [comment]
I got fed-up waiting for this to be released officially so I downloaded the beta. Worked well. Only thing I noticed was:

![image](https://github.com/desktop/desktop/assets/7985331/5557ac77-d561-46e0-bb1e-4866324c6ed7)

The comment about the line endings going from LF o CRLF.

But it all seems fine.

I'll stick with the beta now.
