### ISSUE TITLE
Program not showing up

### ISSUE THREAD

**Issue by scearythecat** [desktop/desktop#18007]
### The problem

After downloading the github desktop the program does not show up anywhere i am having issues with this please resolve this as soon as posiible and when you search for the github desktop the setup shows up not the actual program.
![image_2024-01-12_123303504](https://github.com/desktop/desktop/assets/148261659/56b6e1c2-441c-4684-916e-ba8123298919)

### Release version

Version 3.3.7-beta3 (x64)

### Operating system

Windows 11

**Comment by steveward** [comment]
@munnu32 thanks for the issue. Did the installation complete successfully? There should be a shortcut added to your desktop if it completed. 

If the installation is failing it would be helpful if you could send over the log file that the Squirrel installer generates.

You should be able to find the log file here:

`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`

If no log file is being generated there you should be able to find one in the `SquirrelTemp` directory:

`%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

Please send that over as an attachment.
