### ISSUE TITLE
The branch list doesn't render some branches if you use the scroll bar

### ISSUE THREAD

**Issue by DNin01** [desktop/desktop#18012]
### The problem

When you're on the dropdown menu that shows the branches of a repository and there are a lot of them, if you use the scroll bar to scroll down, not all the list items show up. Instead, below a certain point, there are blank spaces where the branch names would show up.

This isn't exclusively visual - you can't click these hidden list items either, so they must be culled or something.

Using the arrow keys to navigate and scrolling with auto-scroll (middle click) seems to behave as expected. Haven't tried with a touchpad.

Not only is this a problem for users whose scroll wheels are suffering from issues but also during times where you may want to efficiently scroll long distances by using the scroll bar.

### Release version

Version 3.3.6 (x64)

### Operating system

Windows 11 23H2

### Steps to reproduce the behavior

1. Check out any repository. For the best results, check out a repository with a lot of branches, or create your own.
2. Click the "Current branch" button to open the dropdown menu.
3. Scroll around with the scroll wheel. Everything's fine.
4. Scroll to the top, then scroll down with the scroll bar. Below a certain point, the branch names are instead replaced by a blank space.
5. Use the scroll wheel and everything will re-appear.
6. Scroll to the bottom, then scroll up with the scroll bar. Some of the branch names are instead replaced by a blank space.

### Screenshots

https://github.com/desktop/desktop/assets/106490990/66ff45a6-5ff4-4ee2-b2de-95491bcc56a1

### Additional context

Window size: 960x660 (screen size does affect it)

It seems to me like offscreen list items aren't rendered (in order to save resources), but they also aren't updated when the scroll bar is used.

I am not aware of any other lists that have this issue, though there may be some.

**Comment by niik** [comment]
Hey @DNin01, thanks for reaching out and letting us know about this. I believe I found the issue and fixed it in #18019 which will be included in the next production release which should be out within a couple of weeks!
