### ISSUE TITLE
Local Commit Problem

### ISSUE THREAD

**Issue by Pranav1173** [desktop/desktop#18013]
### The problem

When I try to push local commits to the Git hub, I get a 'remote disconnected' error. In spite of good internet connectivity, I have faced the same problem several times.

### Release version

Version 3.2.3 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Push Local commit to origin after making changes in local repository.

**Comment by niik** [comment]
Hey @Pranav1173, sorry to hear you're having problems. The `remote disconnected` error comes from Git and means that either there was an interruption in transit over the Internet or the GitHub servers closed the connection. Common reasons for the latter are that the repository you're trying to push exceeds the [limits that GitHub enforces](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#).

Unfortunately there's not much that the GitHub Desktop app can do to resolve either of these so I'll have to refer you to https://docs.github.com/en/get-started/using-github/troubleshooting-connectivity-problems to troubleshoot your issue.

**Comment by Pranav1173** [comment]
Thank you 😊
