### ISSUE TITLE
"Unable to open shell" Diaglog to suggestion on how to open the "Shell Settings" dialog

### ISSUE THREAD

**Issue by yasuking0304** [desktop/desktop#18016]
### The feature request

1. Open "GitHub Desktop"
2. remove Git Bash.
3. Menu [Repository] -> [Open in Git Bash]
4. When the "Unable to open shell"  dialog is displayed, click "Open Options"
![WS000013](https://github.com/desktop/desktop/assets/111163564/880eab50-436d-4fb1-aa8a-71ececc6612f)
5. The "Advanced" tab of the "Option" dialog opens.

### Proposed solution

It is better to open the "Intergrations" tab of the "Option" dialog

### Additional context

Now
https://github.com/desktop/desktop/blob/development/app/src/ui/app.tsx#L2625-L2630
```TypeScript
  private onShowAdvancedPreferences = () => {
    this.props.dispatcher.showPopup({
      type: PopupType.Preferences,
      initialSelectedTab: PreferencesTab.Advanced,
    })
  }
```
After:
Change the function name to match the actual situation.
```TypeScript
  private onShowIntegrationsPreferences = () => {
    this.props.dispatcher.showPopup({
      type: PopupType.Preferences,
      initialSelectedTab: PreferencesTab.Integrations,
    })
  }
```
It's called from two places, so I'll fix that as well.

**Comment by niik** [comment]
Hey @yasuking0304, I agree that we should be opening the integrations tab and the solution you outlined is how I would have done it myself. Would you like to open up a PR so that we can review the changes?
