### ISSUE TITLE
Multiple buttons for multiple editors?

### ISSUE THREAD

**Issue by auriorx** [desktop/desktop#18027]
### The feature request

Currently I can choose between either VS Code or Jetbrains Rider to open my repository.

However, some repositories are OAS contracts, which I would like to open in VS Code, and others are .NET solutions I wish to open in Jetbrains Rider.

### Proposed solution

Would it be possible to have all (desired) editor choices as a button?

### Additional context

![image](https://github.com/desktop/desktop/assets/58956648/c0fa137f-3b64-40d4-8b5a-6d7a4ab61bad)

**Comment by tidy-dev** [comment]
Hi @auriorx, This appears to be a similar/duplicate request to https://github.com/desktop/desktop/issues/12195. I am closing it in favor of tracking feedback there. Thanks!
