### ISSUE TITLE
issues with mindtap/cengage school assigments

### ISSUE THREAD

**Issue by ArielTristan** [desktop/desktop#18025]
### The problem

A lot of people in my class are having issues with doing assignments. I am missing a calcualtion assignment grade button and sometimes the run button doesnt work or takes a while to load. Now I am having issued with running my code and nothing updating. 

### Release version

i do not see this option

### Operating system

11

**Comment by tidy-dev** [comment]
@ArielTristan Hi! Sorry for your frustrations, However, this is the issue tracker for GitHub Desktop - a git client for GitHub. It does not run code nor calculate grades.
