### ISSUE TITLE
Conflicts Resolution Binary files not working

### ISSUE THREAD

**Issue by ValentinaLagatta97** [desktop/desktop#18028]
### The problem

While trying to replicate a binary file conflict, to check out the feature to decide which one to keep, GitHub decided to handle it on its own and simply destroy the corrupted file both on the main and the one in the change list.

The conflict I was trying to recreate: https://www.youtube.com/watch?v=XZvQNlh6VQY

### Release version

 3.3.6 (x64)

### Operating system

Windows 10

**Comment by steveward** [comment]
Thanks for the report @Valhallaeiru. This is a known issue, see https://github.com/desktop/desktop/issues/9846 where we are tracking this. I'll bump this up for us to look at again.
