### ISSUE TITLE
Create merge commit button stays disabled in 3.3.7 (works in 3.3.6)

### ISSUE THREAD

**Issue by chrisrueger** [desktop/desktop#18037]
### The problem

In 3.3.6 when I want to merge a branch into my current branch I see an enabled "Create a merge commit" button like this:

<img width="497" alt="image" src="https://github.com/desktop/desktop/assets/188422/6ac2c5df-b67e-463d-99e3-7fa7c31d2508">

When I click the button I see a modal with choices how to resolve. 

**Problem:**
In 3.3.7 this "Create a merge commit" is disabled. I cannot click it anymore. Thus I am stuck. 

Rolled back to 3.3.6. today. 

### Release version

3.3.7

### Operating system

MacOS 14.2.1 

### Steps to reproduce the behavior

1. Merge another branch into current branch which causes merge conflicts.

### Screenshots

<img width="497" alt="image" src="https://github.com/desktop/desktop/assets/188422/6ac2c5df-b67e-463d-99e3-7fa7c31d2508">

**Comment by tidy-dev** [comment]
@chrisbbreuer Thank you for the report! We will be shipping a fix to production soon.

**Comment by tidy-dev** [comment]
@chrisrueger Release 3.3.8 is out. 

Note: We do staggered auto update rollouts so it is possible that if you hit "Check for updates" it will not show yet, if so, you can download the latest (3.3.8) from desktop.github.com or wait till the rollouts reach your machine.

**Comment by Ofa234** [comment]
Closed

**Comment by Alirm1** [comment]
struct node {
    int stno;
    char name[20];
    struct node *link;
};
