### ISSUE TITLE
Creating a branch while `Open branch with GitHub Desktop` is selected does not work as expected

### ISSUE THREAD

**Issue by J43fura** [desktop/desktop#18032]
### The problem

When creating a branch while `Open branch with GitHub Desktop` is selected, it does not work as expected, and asks the user to Clone instead of directly switching to that branch.
Update: This happens only while doing this from inside of a GitHub project.
![Github-Branch-Error](https://github.com/desktop/desktop/assets/73950268/26713fb4-d876-4f90-99e2-239f99e6d2ac)

### Release version

Version 3.1.1-linux1 (x64)

### Operating system

Ubuntu 22.04

### Steps to reproduce the behavior

When creating a branch while `Open branch with GitHub Desktop` is selected, it does not work as expected, and asks the user to Clone instead of directly switching to that branch.
1. On the browser in an issue, click on `Development` & click `create a branch`
2. Select `Open branch with GitHub Desktop`
3. Unexpected behavior
![Github-Branch-Error](https://github.com/desktop/desktop/assets/73950268/26713fb4-d876-4f90-99e2-239f99e6d2ac)

### Screenshots

![image](https://github.com/desktop/desktop/assets/73950268/f320eaf4-0f68-45a5-b75a-f4a328c883bd)
![image](https://github.com/desktop/desktop/assets/73950268/32c35c5f-4378-42d4-b025-348bfc63b4b5)
![Github-Branch-Error](https://github.com/desktop/desktop/assets/73950268/26713fb4-d876-4f90-99e2-239f99e6d2ac)

### Additional context

I  started getting this just today and i also noticed the UI has changed on the browser's GitHub, im not sure if this is related.
Update: This happens only while doing this inside of a GitHub project. (That is also where the new UI is visible, not sure if its a coincidence)

**Comment by steveward** [comment]
@J43fura thanks for the issue. I just tested this out and everything worked correctly on my machine running macOS. This may be specific to the Linux fork of GitHub Desktop, which at this time we do not provide official support for. You can open an issue there directly to report this:

https://github.com/shiftkey/desktop/issues

I'm going to close this out, but let me know if you are able to reproduce this on macOS or Windows and we can investigate further.
