### ISSUE TITLE
Encoding and question signs

### ISSUE THREAD

**Issue by abogerNicotech** [desktop/desktop#18030]
### The problem

I have some problems with displaying characters in the GitHub Desktop. My file vers.info is in cp1251 encoding. And .gitattributes contains the next line "*.info  working-tree-encoding=C
![problem example](https://github.com/desktop/desktop/assets/109514373/e4608285-3ff2-4083-85a8-c5f6880a5607)
P1251  eol=CRLF". In the new part of the file i see correct cyrillic characters, but in the old part I see question signs inside diamonds on the cyrillic characters places.

### Release version

Version 3.3.6 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Create file with new extansion.
2. Type something using cyrillic characters.
3. Commit it
4. type something more.
5. See the problem.

### Screenshots

![problem example](https://github.com/desktop/desktop/assets/109514373/9c215987-20c7-49a1-a80e-be1e7d9dc20b)

**Comment by steveward** [comment]
Thanks for the report @abogerNicotech. I'm going to add this to https://github.com/desktop/desktop/issues/3923 where we are tracking this issue.
