### ISSUE TITLE
images are not showing 

### ISSUE THREAD

**Issue by seshadrianadasu** [desktop/desktop#18048]
i have an issue on git hub that is images are not showing  and  debug the page there are three error are found 
<img width="958" alt="Screenshot 2024-01-14 195424" src="https://github.com/desktop/desktop/assets/153181738/78fa0165-eea1-4e35-b48f-ee0d4d007bd1">

i am search so many stuff about this topic but nothing is work,.
please help me!

**Comment by sergiou87** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
