### ISSUE TITLE
git desktop stuck in pulling origin

### ISSUE THREAD

**Issue by bryanhubbard** [desktop/desktop#18044]
### The problem

I am having an issue with git desktop sitting at the 'pulling origin' for a specific repo.

### Release version

3.3.8

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Open Git Desktop
2. Select pull from origin

### Log files

[2024-01-18.desktop.production.log](https://github.com/desktop/desktop/files/13980817/2024-01-18.desktop.production.log)

### Screenshots

<img width="325" alt="image" src="https://github.com/desktop/desktop/assets/95835923/c9240ae6-1a79-446e-b464-04e5f8eed369">

### Additional context

I have tried removing and reinstalling the application. The issue still happens.

Also tried removing the directory. I get a 'this folder is in use by another application' error. I restarted, deleted the folder, issue still happens during the pulling process.

**Comment by tidy-dev** [comment]
@bryanhubbard Is this repository stored in a cloud directory? That usually interferes with Git. Try moving the repository to a non-cloud managed directory and see if that resolves it.

**Comment by bryanhubbard** [comment]
Issue was related to a file in the repo. Once the file was removed, the repo was then able to be pulled with no issue.
