### ISSUE TITLE
Cannot authenticate for non-GitHub repositories

### ISSUE THREAD

**Issue by EricRabil** [desktop/desktop#1804]
### Description

There is no GUI-based method to authenticate for a non-GitHub repository. The original Github Desktop client has this functionality (it will pop-up prompting for the password.

### Version

**GitHub Desktop version:** 0.5.8

**OS version:** 10.12.5

### Steps to Reproduce

1. Add a local repository that requires authentication for fetching (is private)
2. Attempt to fetch origin
3. It will tell you to sign in with an account authorized to access the repository in the preferences screen, but there is no screen to do so.

**Expected behaviour:** Ability to authenticate for a private local/non-GitHub repository

**Actual behaviour:** No way to authenticate for a private local/non-GitHub repository

**Reproduces how often:** 100%

### Logs

[2017-05-27.desktop.production.log.zip](https://github.com/desktop/desktop/files/1033221/2017-05-27.desktop.production.log.zip)

**Comment by shiftkey** [comment]
We are tracking this in https://github.com/desktop/desktop/issues/852
