### ISSUE TITLE
silently force pushed to a protected branch without asking for "pull request"

### ISSUE THREAD

**Issue by wamicha** [desktop/desktop#18045]
### The problem

I created a repo so I'm the admin. I made the default branch as protected with pull-request and 2-people review required before merging. I also added the CODEOWNERS file in .github. Then I checked it out and made some changes using GitHub Desktop. I made some changes and committed the changes. Then G Desktop prompted me to push to origin so I did. It went through without warning. This behavior is inconsistent with online operation: when I did the same online, I was shown an option: "create a pull request or push bypassing the rules". 
I understand as admin, I might be able to bypass the rules, but at least I should see a warning.

### Release version

Version 3.3.6 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. check out the default branch (as admin) that is protected with pull-request rules activated and the CODEOWNERS file inserted.
2. update the readme.md file.
3. commit and push to origin. The changes are pushed through.

**Comment by steveward** [comment]
Thanks for the report @wamicha. Are you using the Branch protection rules (located at https://github.com/user/repo/settings/branch_protection_rules/) or the repo rules (located at https://github.com/user/repo/settings/rules)?

I was unable to reproduce this in either case, so it would be helpful to know the specific settings you have enabled as well.
