### ISSUE TITLE
Github Desktop encountered an error

### ISSUE THREAD

**Issue by Tini79** [desktop/desktop#18052]
### The problem

Here's I attach my issue in image, hope it can be solved soon.

### Release version

3.3.8

### Operating system

WIndows 10.0.22621

### Steps to reproduce the behavior

After clicking on Ctrl + Shift + A or even on Open in Visual Studio Code button

### Screenshots

<img width="505" alt="image" src="https://github.com/desktop/desktop/assets/97665722/636aa029-eec6-432a-ba93-f5440e25e965">

**Comment by sergiou87** [comment]
Could you open the command prompt and share the output of echo `%PATH%`?

If `System32` is not in your `PATH`, you will see that `ENOENT` error. You will need to edit your `PATH` by following [this article](https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/) and adding the following line:

`C:\Windows\system32`

**Comment by EloyParga** [comment]
![image](https://github.com/desktop/desktop/assets/99491519/71d0fc6d-2980-4236-96cb-d4fe6827ecb4)

A mi me sale algo muy parecido, en mi caso es que no encuentra el jdk, este error me sucede tanto al lanzar VS desde GitHub DT como al usar el NPM con Node.js. He reinstalado e instalado y el jdk si existe en dicha ruta.

![image](https://github.com/desktop/desktop/assets/99491519/bd3c6184-87da-42d5-9b75-1fd911fb2c93)

**Comment by Tini79** [comment]
> Could you open the command prompt and share the output of echo `%PATH%`?
> 
> If `System32` is not in your `PATH`, you will see that `ENOENT` error. You will need to edit your `PATH` by following [this article](https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/) and adding the following line:
> 
> `C:\Windows\system32`

**Comment by Tini79** [comment]
I added C:\Windows\System32 to my PATH and it solved the problems. It works now, thanks @sergiou87
