### ISSUE TITLE
Repository already deleted

### ISSUE THREAD

**Issue by bipin912** [desktop/desktop#18059]
### The problem

I already deleted the previous repository. I wanted to add new repository through github application but the deleted repository gets activated while adding existing repository from my harddrive in github desktop.

### Release version

3.3.8

### Operating system

Windows 11

**Comment by steveward** [comment]
@bipin912 thanks for the issue. Did you delete the repository on disk, or just remove it from GitHub Desktop? I'm not sure what you mean when you say repository gets activated -- can you share a few more details or share screenshots of what you are experiencing?

**Comment by Satoshin-Btc** [comment]
just moved
