### ISSUE TITLE
Pushing to origin never finish

### ISSUE THREAD

**Issue by yosrawerfelli** [desktop/desktop#18050]
### The problem

I wanted to push my work to an already existing project created by my colleague, after cloning the project and adding my work, commiting then when i push, it doesn't show me percentage just pushing to origin stuck forever!
I tried changing my network it didn't work also. 

### Release version

Version 3.3.8 (x64)

### Operating system

Windows 10

### Log files

[2024-01-19.desktop.production.log](https://github.com/desktop/desktop/files/13991318/2024-01-19.desktop.production.log)

### Screenshots

![Capture](https://github.com/desktop/desktop/assets/121724824/2e9b0eca-27e7-41b6-8316-5ab9751bffef)

**Comment by steveward** [comment]
@yosrawerfelli thanks for the issue. It looks like the push is timing out:

```
Total 217 (delta 28), reused 0 (delta 0), pack-reused 0
error: RPC failed; curl 6 Recv failure: Connection was reset
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date

(The error was parsed as 4: The remote disconnected. Check your Internet connection and try again.)
```

 if you are having issues pushing a set of changes you can try using the command line to push a subset of commits by using the following command:

`git push origin commit-SHA:branch`

For example, if you have three commits A (4d3bf9) - B (e55b5f) - C (c109e0) and wanted to push A and B to your `main` branch you would run this command:

`git push origin e55b5f:main`

There are also some HTTP timeout config operations that may help, or at lease provide additional diagnosis about the timeout. One user previously had success with these commands:

`git config --global http.lowSpeedLimit 1000`
`git config --global http.lowSpeedTime 20`

The `lowSpeedLimit` configures the minimum bytes per second, and the `lowSpeedTime` is the number of seconds. If the operation is lower than that threshold for the set time it will timeout. Adjusting those values may help with timeouts.

You could also try switching to using SSH to see if you have better success. See [this guide](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) for setting up a new SSH key.

You will also need to change the URL of your repository to use SSH. You can do this in GitHub Desktop by going to `Repository` > `Repository Settings` > `Remote`. You will want the URL to look like `git@github.com:<user>/<repo>.git`. 

I hope that helps! I'm going to close this out as this is a connection problem and not a specific issue with GitHub Desktop, but let me know if you have any further questions.
