### ISSUE TITLE
I need help with The General AI challenge

### ISSUE THREAD

**Issue by MaximusTheGladiator** [desktop/desktop#1805]
I don't know how to add Curses to Python.

weve tried to use pip, but all versions of Python weve tried have said that there is either an issue with syntax, or that a command that tells the system to upload curses isn't recognized. Weve tried Python 3.6.1, 2.7.10. 2.7.13, and 3.5.0 and it hasn't worked primarily for syntax reasons when I copied and pasted. The version of curses Were trying to "connect" with whatever Version of Python always matches, for example, We used  curses‑2.2‑cp36‑cp36m‑win_amd64.whl  when using Python 3.6.1, on 64 bit version. 

Weve only got the warning that that command isn't recognized when using Python 2. 7.10 "probably because it may be outdated"

Also, is Python really the best place to be running the environment?

And  If I run the environment In Python do I have to use Python to make the agent?

What other Coding languages could I use to run the environment and make the agent? 

Thank you in advance "Sorry for this extreme overhaul of questions"

**Comment by MaximusTheGladiator** [comment]
why'd you close it?

**Comment by niik** [comment]
@MaximusTheGladiator: this is the repository for the open-source project GitHub Desktop and it doesn't look like your question is related to this project.

**Comment by MaximusTheGladiator** [comment]
I need to add curses to run the environment which Is what the agent will be using for imput and output.

In order to test my agent, I need an environment, which I need CURSES for..
