### ISSUE TITLE
Amend not copy anymore the previous message

### ISSUE THREAD

**Issue by m21-cerutti** [desktop/desktop#18061]
### The problem

Ammend feature does not fill by default the previous message commit anymore.
Is it wanted, or there is a change in the workflow to enable it again ?

### Release version

Version 3.3.8 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Make a commit with one file
2. Ammend it by right clicking on the history (make sure you not have write a commit message)
3. See that the message is not filled with the previous one, but the default update <file>

**Comment by sergiou87** [comment]
That behavior changed a bit in https://github.com/desktop/desktop/pull/17879

There is a regression but not sure if it's what you're referring to. When you say the message "is not filled with the previous one", what do you mean by "previous one"?

**Comment by sergiou87** [comment]
This is what I see:

https://github.com/desktop/desktop/assets/1083228/1c5a3213-62bb-4aa9-af72-0927c802478a

Could you share a video with your steps to reproduce it?

**Comment by m21-cerutti** [comment]
Here my simplest usecase. (you can ignore the sound capture ^^')
https://github.com/desktop/desktop/assets/23432929/c5a1db06-4390-415a-86d4-ed21f53105ba
Before the message was filled with the previous commit message, here would be Test.

**Comment by palhal** [comment]
I can confirm that this is happening with the latest update (3.3.8). Very annoying.

**Comment by m21-cerutti** [comment]
Steps to reproduce:
1. Make a new commit with a message
2. Go to history
3. Amend new commit
4. See the commit message

Expected: The previous commit message (if none were write) is retrieve.
Same behaviour as undo.

Result: We loose the previous commit message we ha put at step 1.

I have reproduced it on another computer on 3.3.8 version, Windows 11, x64

**Comment by sergiou87** [comment]
@m21-cerutti I am unable to reproduce this behavior anymore, even following those steps or what you show in the video 😭  (I like that song btw ❤ )

Could you try the latest beta from https://desktop.github.com/beta to see if the behavior changes?

**Comment by sergiou87** [comment]
Oh, I found the problem. This only happens with repos not hosted on GitHub 🤦‍♂  Let me take a look…

**Comment by ghnp5** [comment]
Came here to report this. (Hosted in Gitea)

Thanks for reporting, and thanks for fixing!

**Comment by HeCorr** [comment]
@sergiou87 Thanks for fixing this!

It seems however that cancelling the amend (by clicking "Stop amending") doesn't clear the commit summary and description, but I can't remember if it used to. Is this the expected behavior or could it be another regression?
