### ISSUE TITLE
Support user created plugins

### ISSUE THREAD

**Issue by Wardergrip** [desktop/desktop#18062]
### The feature request

Similar to VS Code, VS and many other software the most developers use, it supports in some way user created plugins or extensions. This allows for developers to streamline and customise their experience using the software.

These plugins could add buttons, change UI layout or UI colors amongst other things.

For a practical example: in the Unity game engine, certain files are saved in YAML. Manually solving merge conflicts of these type of files will often create corrupted results. Unity ships a UnityYAMLMerge tool with their engine, but using it requires some commands. For in the game industry, dealing with the CMD is difficult for non-devs like designers and artists. Having an extra button in Github desktop that could run a command in the repository would be amazing.

### Proposed solution

Plugin or extension support

**Comment by steveward** [comment]
Thanks for the issue @Wardergrip! This is something that has been brought up before, but at this time it isn't on our radar to implement. I'm going to add this to https://github.com/desktop/desktop/issues/1718 where we are tracking feedback around this.
