### ISSUE TITLE
netbeans

### ISSUE THREAD

**Issue by Thoko28** [desktop/desktop#18065]

**Comment by Thoko28** [comment]
My old bed beans projects are not connecting to net beans after installing the apache version

**Comment by steveward** [comment]
@Thoko28 this issue tracker is for GitHub Desktop. If you are having issues with NetBeans you will need to reach out to JetBrains for support.

**Comment by Thoko28** [comment]
Dear Steve
Thank you very much for your email. I have seen JetBrains I will contact them

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
