### ISSUE TITLE
update to npm@5 for great justice

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#1806]
Opening up this issue to track upgrading all the things and do some testing:

 - [ ] local testing of new `package-lock.json`
 - [ ] CI builds
 - [ ] documentation
 - [ ] giving everyone time to get up to date before merging cc @desktop/core

Random pointers from the [release notes](https://github.com/npm/npm/releases/tag/v5.0.0):

 - `npm` will `--save` by default now.
 - better use of the local cache, for situations where you have no internet access
 - [`npm install` is sooooo much faster](https://twitter.com/maybekatz/status/865393382260056064)

TODO:

 - will we get a new version of node-gyp which fixes #1766 ?

**Comment by shiftkey** [comment]
It looks like `npm@5` has some changes that affect how we rely on an `npm prune && npm install` to get everything up to date - my gut feeling is an untracked `package-lock.json` file at the root is hanging around and affecting whenever you try to update a package.

I've pinned to `npm@4.6.1` for now on the CI servers (see #1611) until I can get a chance to dive into this properly.

**Comment by gengjiawen** [comment]
Should we put node-gyp in dev dependency?

**Comment by shiftkey** [comment]
FYI: if you try running `npm@5.4.0` you might encounter this issue when running `npm i` after the first successful `npm install`: https://github.com/npm/npm/issues/17858
