### ISSUE TITLE
Push origin still showing, after pushing the commits. 

### ISSUE THREAD

**Issue by JorianRoelofsen** [desktop/desktop#18075]
### The problem

Push origin still showing, after pushing the commits. 
The commits are pushed on the branch.

### Release version

Version 3.3.8 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

I don't know.

1. I committed.
2. Tried to push.
3. Pushes to server.
4. Commits show again.

### Screenshots

![image](https://github.com/desktop/desktop/assets/93914476/5d9130c6-182a-416f-a399-e5c8128171e5)
![image](https://github.com/desktop/desktop/assets/93914476/14ab71d5-60d0-4e6a-90d0-0284be75cd5f)

**Comment by steveward** [comment]
Thanks for the report @JorianRoelofsen. Can you try manually triggering a fetch (Menu -> Repository -> Fetch) to see if that fixes things?

**Comment by JorianRoelofsen** [comment]
I found out it was a problem with double branches.
First branch was feat/ect.
Second branch was Feat/ect.

After deleting one of the branches, it fixed itself.

**Comment by steveward** [comment]
Glad to hear things are resolved now!
