### ISSUE TITLE
GitHub Desktop automatic update triggering virus alert

### ISSUE THREAD

**Issue by jakni0672** [desktop/desktop#18072]
Since yesterday our users are receiving virus alerts when they open GitHub Desktop and the automatic update process launches (we use Kaspersky Endpoint Security as our anti-virus solution)
It's a heuristuc detection (PDM.Trojan.Win32.Generic), so probably a false positive - but just wanted to see if you're aware or if you have any info about this?
The detection is triggered by %localappdata%\GitHubDesktop\Update.exe and also seems to affect %localappdata%\SquirrelTemp\tempa and tempb folders
Let me know if you need any further information

Best Regards
James

**Comment by steveward** [comment]
@jakni0672 thanks for reporting this. This often happens with various antivirus vendors after we release updates to GitHub Desktop, and is a false positive. Normally these resolve themselves, but if needed it may be worth reaching out to Kaspersky if you have a support account with them.

**Comment by Hosam11** [comment]
also with avast. avast remove the .exe

**Comment by Arjunpride15** [comment]
you could also uninstall your current antivirus and install apps like Avira or Bitdefender

**Comment by aukgit** [comment]
+1 facing it. It is happening with Avast @steveward steveward 

The Dangers of Malware on GitHub - Ophtek
https://ophtek.com/the-dangers-of-malware-on-github/#:~:text=GitHub%20is%20a%20wildly%20popular,increasingly%20used%20to%20spread%20malware.

**Comment by steveward** [comment]
@Hosam11 you can [add exceptions in Avast ](https://support.avast.com/en-us/article/antivirus-scan-exclusions/#mac)to resolve this.

**Comment by aukgit** [comment]
> @Hosam11 you can [add exceptions in Avast ](https://support.avast.com/en-us/article/antivirus-scan-exclusions/#mac)to resolve this.

This is not the right way. You need to improve the rep. Discuss with total virus

**Comment by HotNoob** [comment]
*bump* happening again. \w avast

**Comment by baxsm** [comment]
bump this is a headache

**Comment by lagabyok** [comment]
Avas puso en cuarentena mi github desktop y tengo trabajo que terminar que puedo hacer ayuda el virus esta en el update.exe geberic me decia

**Comment by scottdavort** [comment]
Now with Norton.

____________________________

Details

Threat name: IDP.Generic
Threat type: Miscellaneous - This is an app that you may have unknowingly installed and that may harm your computer performance.
Status: Threat detected
Detected by: Behavioral Protection
On PC from: 10/23/24, 4:26 PM
Last Used: 10/23/24, 11:09 PM
Startup Item: No

Few users
Hundreds of users in the Norton Community have used this file.

Very new
This file was released 12 hours ago.

High
The file risk is high.
____________________________

Activity

Path | Type | Status
C:\Users\Scott\AppData\Local\GitHubDesktop\Update.exe | File | Infected
C:\Users\Scott\AppData\Local\GitHubDesktop\Update.exe | Process | Infected

**Comment by henno-o** [comment]
> Now with Norton.
> 
> Details
> 
> Threat name: IDP.Generic Threat type: Miscellaneous - This is an app that you may have unknowingly installed and that may harm your computer performance. Status: Threat detected Detected by: Behavioral Protection On PC from: 10/23/24, 4:26 PM Last Used: 10/23/24, 11:09 PM Startup Item: No
> 
> Few users Hundreds of users in the Norton Community have used this file.
> 
> Very new This file was released 12 hours ago.
> 
> High The file risk is high.
> 
> Activity
> 
> Path | Type | Status C:\Users\Scott\AppData\Local\GitHubDesktop\Update.exe | File | Infected C:\Users\Scott\AppData\Local\GitHubDesktop\Update.exe | Process | Infected

Same with AVG

**Comment by steveward** [comment]
@henno-o @scottdavort thanks for reporting that. Normally these resolve after a period of time, but if needed I would recommend excluding those files from scanning.

**Comment by ZombieStriker** [comment]
Just got the same error from AVG. I did the automatic update for github desktop, and it flagged the auto updater.exe. So,  I re-downloaded the installer, and now its saying the installer is infected with the same "generic" threat.

I haven't opened github desktop in a while, so this might not be a new thing, and may have just started to happen when others were starting to report it.

**Comment by rellampec** [comment]
Norton Internet Security quarantined latest update and install file (as I tried reinstall after failed update).

```
desktop.githubusercontent.com/releases/3.4.16-ba997388
```

- Threat name: **IDP.Generic**

Curiously, when I follow the link _More info_ in the Origin TAB, I am landed to [this Norton's page](https://safeweb.norton.com/report/show?url=https:%2F%2Fdesktop.githubusercontent.com%2Freleases%2F3.4.16-ba997388%2FGitHubDesktopSetup-x64.exe) that flags as 🟢**SAFE** the download !!

![Image](https://github.com/user-attachments/assets/c8776696-32cf-43f1-aa78-6f9c29081f28)

It might probably have been that my Norton hasn't updated its table for _file insights_? (asking for reboot 😃 ). After reboot I could install with no problems:

![Image](https://github.com/user-attachments/assets/d2015827-6a9b-4af9-8399-661970e9355b)

Any idea on what IDP.Generic threat is and how come Norton would detect it in your installation package?
