### ISSUE TITLE
Enable user to force push...

### ISSUE THREAD

**Issue by PaddleStroke** [desktop/desktop#18074]
### The feature request

![image](https://github.com/desktop/desktop/assets/19984177/c92d365d-a3f6-4ab0-b93f-405bce8340ab)

I want to force push changes to my branch and I can't? This failsafe of hidding force push option is extremely annoying.

This is my first experience with git desktop and I keep running in annoying things where it tries to force me to behave a certain way and this is very annoying. I have to force push this branch and I can't. 

### Proposed solution

Just put a button 'force push' with many warnings if necessary...
Or maybe add a setting 'no kid failsafe' checkbox that make force push appears...

**Comment by PaddleStroke** [comment]
Note I'm 100% sure that I was only 1 commit ahead because I went back to git gui where I clicked on 'push' and it worked, without the need of force pushing.

**Comment by tidy-dev** [comment]
@PaddleStroke Force push is available when Desktop detects a diverged state. I believe you needed to fetch so Desktop could detect that. https://github.blog/changelog/2023-05-03-github-desktop-makes-force-pushing-and-fetching-easy-and-adds-pull-request-comment-notifications/#force-pushing-and-fetching

**Comment by PaddleStroke** [comment]
The user should be able to force push even if there is a diverged state. Removing the capability entirely is needless babysitting.

If you want to close this issue it should not be as completed but as not planed. Because it is not completed.
