### ISSUE TITLE
Github desktop has encountered an error

### ISSUE THREAD

**Issue by gideonler** [desktop/desktop#18073]
### The problem

When I try to open github desktop open in vscode, it prevented me from doing so. It was working fine the previous day, so Im not sure what went wrong
![error](https://github.com/desktop/desktop/assets/26820528/7b6de801-7151-4ed4-90b4-8fe5e71fb605)

### Release version

3.3.8

### Operating system

Windows 10.0.19045

**Comment by steveward** [comment]
Could you open the command prompt and share the output of echo %PATH%?

If System32 is not in your PATH, you will see that ENOENT error. You will need to edit your PATH by following [this article](https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/) and adding the following line:

C:\Windows\system32

Let me know if that doesn't get things working.

**Comment by gideonler** [comment]
I have already added C:\Windows\system32 to my path in the env variables, but it is still not working. Do you know whats the possible reason?
![error2](https://github.com/desktop/desktop/assets/26820528/199c0dea-86e9-45d3-8b1f-dd7b994546f6)
