### ISSUE TITLE
How Do I add curses to python?

### ISSUE THREAD

**Issue by MaximusTheGladiator** [desktop/desktop#1807]
I don't know how to add Curses to Python.
weve tried to use pip, but all versions of Python weve tried have said that there is either an issue with syntax, or that a command that tells the system to upload curses isn't recognized. Weve tried Python 3.6.1, 2.7.10. 2.7.13, and 3.5.0 and it hasn't worked primarily for syntax reasons when I copied and pasted. The version of curses Were trying to "connect" with whatever Version of Python always matches, for example, We used  curses‑2.2‑cp36‑cp36m‑win_amd64.whl  when using Python 3.6.1, on 64 bit version. 
Weve only got the warning that that command isn't recognized when using Python 2. 7.10 "probably because it may be outdated"

**Comment by niik** [comment]
Again, please see my response in #1805, this repository doesn't have anything to do with your question which should probably be asked in a forum related to the project you're working on or on a general purpose Q/A site like stackoverflow.
