### ISSUE TITLE
So much wasted space

### ISSUE THREAD

**Issue by chronvas** [desktop/desktop#18088]
### The problem

Why is there so much wasted space? That coould be used at least to not truncate the branch name

### Release version

3.3.8

### Operating system

Any

### Screenshots

<img width="1604" alt="Screenshot 2024-01-26 at 11 28 21" src="https://github.com/desktop/desktop/assets/8863897/218da666-0a7f-4413-bdb4-682d2157e102">

**Comment by steveward** [comment]
Thanks for the issue @chronvas. This is being tracked in https://github.com/desktop/desktop/issues/4569 so I'm going to close this out.
