### ISSUE TITLE
wrong user name 

### ISSUE THREAD

**Issue by bondar-217** [desktop/desktop#18085]
### The problem

<img width="1512" alt="image" src="https://github.com/desktop/desktop/assets/126788617/00e21f03-e35f-4890-afcc-6e9414eb856d">

I can't continue logging in:
the username must be different, the username bondar cannot be changed

### Release version

Version 3.3.8 (arm64)

### Operating system

macOS Sonoma 14.3

**Comment by steveward** [comment]
@bondar-217 that prompt is for your SSH password. If you are trying to authenticate to GitHub Desktop you can go to `GitHub Desktop` > `Settings` > `Accounts`. Let me know if you have any further questions.
