### ISSUE TITLE
Can't select last diffed line.

### ISSUE THREAD

**Issue by JorensM** [desktop/desktop#18081]
### The problem

When selecting diffs that I want to commit, I am unable to select the last line in my file.

Here is a screenshot to demonstrate.

![diff issue](https://github.com/desktop/desktop/assets/17122123/b62cfdf6-431d-4349-b61e-ba7371c9bc60)

As you can see all the lines are selected, but when I click on the last line, nothing happens.

### Release version

 3.3.8 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Do some changes in your file including the last line
2. Try to separately select the last line in GitHub Desktop

**Comment by steveward** [comment]
Thanks for the report @JorensM. I was able to reproduce this as well, I'll mark this as a bug for us to look into.

**Comment by sergiou87** [comment]
This seems to happen when there is no newline at the end of the file (before and after). I will investigate 🕵
