### ISSUE TITLE
Feature request - toggle full screen button

### ISSUE THREAD

**Issue by keyvankr** [desktop/desktop#1809]
### Description

Hi, I have a fairly simple suggestion. I wonder if you could **add** a **"Exit fullscreen" button** for leaving fullscreen without having to press the f11/toggle key.
**Explain why this enhancement would be useful to GitHub Desktop users:**
It's useful for people who're just new and used the menu "view" instead of pressing the f11 key and don't know really how to revert.

here's a quick paint "sketch" I've made for the suggestion:
![suggestion](https://cloud.githubusercontent.com/assets/26793065/26524953/55942b4a-4347-11e7-9854-c4e786fe17c7.png)

### Version

**GitHub Desktop version:** 0.5.8

**OS version:** Microsoft Windows [Version 10.0.15063]

#### Additional Information
ps: this is my very first issue that i've created on github, so I hope I'm not doing anything wrong 😨

**Comment by shiftkey** [comment]
Given there are already two options here:

  - press <kbd>ALT</kdb> to show the menu, then pressing View | Toggle Fullscreen
  - <kbd>F11</kbd>

I'm not sure how I feel about adding a third. I'll let @donokuda or @niik chime in on their feels about this.

**Comment by niik** [comment]
> I'm not sure how I feel about adding a third.

Yeah, I'm not a fan of adding an explicit button either but I appreciate that it's not very discoverable right now and I think @keyvankr raises a good point.

I think there are ways we can make this more discoverable without adding a button. First off I think we should make the app menu on Windows appear when you move your mouse to the topmost part of the screen while in full screen. I had intended to do this as part of my menu work but didn't have time to get to it.

Second, I think a notification similar to that of the zoom notification that just landed in #1720 could help out as well.

![screen shot 2017-05-29 at 14 47 49](https://cloud.githubusercontent.com/assets/634063/26550399/dc21f520-447d-11e7-9a7e-291b4759364b.png)

**Comment by keyvankr** [comment]
@niik , really a fan of the second. just like when you go fullscreen on a youtube video and you get the little floating notification. better than the suggestion i've made to be honest 😅

**Comment by shiftkey** [comment]
> First off I think we should make the app menu on Windows appear when you move your mouse to the topmost part of the screen while in full screen.

Yep, I really like this idea. The macOS menu behaves like this when in fullscreen, but we get that for free so :thumbsup: for consistency.

> Second, I think a notification similar to that of the zoom notification that just landed in #1720 could help out as well.

Also nice!

**Comment by donokuda** [comment]
>  First off I think we should make the app menu on Windows appear when you move your mouse to the topmost part of the screen while in full screen. I had intended to do this as part of my menu work but didn't have time to get to it.

@niik Is this something we should track in a separate issue (and then close out this one?)

**Comment by niik** [comment]
> @niik Is this something we should track in a separate issue (and then close out this one?)

Yeah, that sounds like a good idea 👍

**Comment by joshaber** [comment]
Created https://github.com/desktop/desktop/issues/2270 to track that 💥
