### ISSUE TITLE
Minimum Height

### ISSUE THREAD

**Issue by daveycodez** [desktop/desktop#18094]
### The problem

Remove minimum height restriction, brand new MacBook and the app is going under my dock literally.

### Release version

All

### Operating system

All

**Comment by Nikola35a** [comment]
100XLEGENDX

**Comment by steveward** [comment]
Thanks for the feedback @LeakedDave, this has been previously discussed in https://github.com/desktop/desktop/issues/1702 and since you commented there I'm going to close this out.
