### ISSUE TITLE
Merge branch for every commit

### ISSUE THREAD

**Issue by oscarmanzelli** [desktop/desktop#18100]
### The problem

We are figuring out that for every commit the application is generating a merge

### Release version

3.3.8

### Operating system

Windows 11

### Screenshots

![image](https://github.com/desktop/desktop/assets/121856457/3c1f84d1-7316-49c1-a98e-7bdc9d080b5f)

**Comment by steveward** [comment]
@oscarmanzelli thanks for the issue. Those are merge commits, and are used if fast-forwarding isn't possible (see this [guide](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging) for various merge methods). I would also verify that you don't have `--no-ff` set in your local `.git/config`, as that could be creating more merge commits even if they aren't necessary. You can check this by running `git config --local --list`. Let me know if you have any other questions.
