### ISSUE TITLE
Summary is not automatically copied.

### ISSUE THREAD

**Issue by NaBian** [desktop/desktop#18105]
### The problem

In the old version, summary and description can be automatically copied while latest can't.

### Release version

3.3.8 (x64)

### Operating system

Windows 10 19044.3086

### Screenshots

![demo1](https://github.com/desktop/desktop/assets/17383395/51a11f4f-c3a6-412d-8d36-566542c8338c)

**Comment by steveward** [comment]
Thanks for the report @NaBian, this has been fixed by https://github.com/desktop/desktop/pull/18083 and will be in an upcoming release.
