### ISSUE TITLE
Question for Installation Error of Github Desktop

### ISSUE THREAD

**Issue by jhlee36** [desktop/desktop#18103]
Could you please help to solve this problem as below?

This problem is occurred when I double click this application to install the Github desktop.

Please kindly check the log that I attached.

Thanks in advance!

[SquirrelSetup.log](https://github.com/desktop/desktop/files/14092978/SquirrelSetup.log)

**Comment by steveward** [comment]
Thanks for the issue. I'm not seeing anything in the Squirrel log related to the installation of GitHub Desktop. Can you share a few more details or a screenshot of what's happening when you attempt the installation? Do you have any antivirus/security software running on this machine that could be interfering with the application?
