### ISSUE TITLE
All my github repositories are missing

### ISSUE THREAD

**Issue by abhishekt28** [desktop/desktop#18110]

**Comment by abhishekt28** [comment]
![image](https://github.com/desktop/desktop/assets/44369250/c5ef64ef-5824-478f-b546-ee3d51cb5abc)

**Comment by steveward** [comment]
@abhishekt28 you will need to reach out to [GitHub Support](https://support.github.com/) for assistance. This issue tracker is specifically for GitHub Desktop.
