### ISSUE TITLE
Keyboard shortcut to delete a branch is not working on Mac

### ISSUE THREAD

**Issue by dre-atc** [desktop/desktop#18112]
### The problem

When deleting a branch, the menu says that the keyboard shortcut for it on Mac is `shift+CMD+D` but when I try that on multiple keyboards, nothing happens.

### Release version

3.3.6 (arm64)

### Operating system

macOS Ventura 13.6.2

### Steps to reproduce the behavior

1. Open GitHub Desktop.
2. Create or switch to another branch.
3. Use Shift+CMD+D.
4. Observe that the branch has not been deleted.

**Comment by steveward** [comment]
Thanks for the report @dre-atc. I tested things out and shortcut is working on my machine (macOS 14.3). Any chance something else is mapped to this shortcut that is overriding Desktop? See [conflicting shortcuts](https://support.apple.com/guide/mac-help/change-a-conflicting-keyboard-shortcut-on-mac-mchlp2864/13.0/mac/13.0).

**Comment by dre-atc** [comment]
I just checked the shortcuts menu and nothing is conflicting. Also used the keyboard viewer to verify that the expected buttons are being pressed and all of them show up. Deleting appears to be the only branch-related shortcut that doesn't work. The shortcuts for creating a new branch and renaming a branch are working fine.

**Comment by sergiou87** [comment]
Have you tried this on another machine or just rebooting your machine?

As @steveward , I haven't been able to reproduce the issue 😕
