### ISSUE TITLE
"Command Failed" dialog box appears on Github Desktop for Mac.

### ISSUE THREAD

**Issue by 4troDev** [desktop/desktop#18116]
### The problem

A "failed command" error related to formatting appears in Github Desktop when trying to commit to any new and old repositories. This issue started around January 28, 2024.

### Release version

3.3.8 (x64)

### Operating system

macOS Sonoma V 14.2.1

### Steps to reproduce the behavior

1. Launch GitHub Desktop.
2. Wait a couple of minutes, using other apps (for using vscode) [This might also happen right after opening the desktop app]
3. Switch back to GitHub Desktop
4. See the error dialog and the screenshot below)

### Log files

[2023-08-16.desktop.production.log](https://github.com/desktop/desktop/files/14126118/2023-08-16.desktop.production.log)
[2023-08-29.desktop.production.log](https://github.com/desktop/desktop/files/14126119/2023-08-29.desktop.production.log)
[2023-09-03.desktop.production.log](https://github.com/desktop/desktop/files/14126120/2023-09-03.desktop.production.log)
[2023-09-04.desktop.production.log](https://github.com/desktop/desktop/files/14126122/2023-09-04.desktop.production.log)
[2023-09-06.desktop.production.log](https://github.com/desktop/desktop/files/14126123/2023-09-06.desktop.production.log)
[2023-11-24.desktop.production.log](https://github.com/desktop/desktop/files/14126124/2023-11-24.desktop.production.log)
[2023-12-01.desktop.production.log](https://github.com/desktop/desktop/files/14126125/2023-12-01.desktop.production.log)
[2023-12-07.desktop.production.log](https://github.com/desktop/desktop/files/14126126/2023-12-07.desktop.production.log)
[2023-12-13.desktop.production.log](https://github.com/desktop/desktop/files/14126128/2023-12-13.desktop.production.log)
[2024-01-02.desktop.production.log](https://github.com/desktop/desktop/files/14126129/2024-01-02.desktop.production.log)
[2024-01-03.desktop.production.log](https://github.com/desktop/desktop/files/14126130/2024-01-03.desktop.production.log)
[2024-01-21.desktop.production.log](https://github.com/desktop/desktop/files/14126131/2024-01-21.desktop.production.log)
[2024-01-29.desktop.production.log](https://github.com/desktop/desktop/files/14126133/2024-01-29.desktop.production.log)
[2024-01-30.desktop.production.log](https://github.com/desktop/desktop/files/14126134/2024-01-30.desktop.production.log)
[2024-02-01.desktop.production.log](https://github.com/desktop/desktop/files/14126135/2024-02-01.desktop.production.log)

### Screenshots

<img width="973" alt="Screenshot 2024-02-01 at 8 32 46 AM" src="https://github.com/desktop/desktop/assets/86755192/0d508388-3693-42b5-afc5-d8d1c56ac07a">
<img width="973" alt="Screenshot 2024-02-01 at 8 32 52 AM" src="https://github.com/desktop/desktop/assets/86755192/1d35a23c-c13c-475f-b868-26eaba19b887">
<img width="973" alt="Screenshot 2024-02-01 at 8 33 07 AM" src="https://github.com/desktop/desktop/assets/86755192/aa7a93cd-b17d-457c-8142-1d72c3d2058f">

**Comment by steveward** [comment]
Thanks for the report @4troDev. Are you storing repositories on a network (Samba) drive? That was the one previous case where we've seen this (https://github.com/desktop/desktop/issues/15539). Most users claimed Sonoma 14.2 fixed it, but it looks like you're on that version.

**Comment by 4troDev** [comment]
> Thanks for the report @4troDev. Are you storing repositories on a network (Samba) drive? That was the one previous case where we've seen this (https://github.com/desktop/desktop/issues/15539). Most users claimed Sonoma 14.2 fixed it, but it looks like you're on that version. 

no all my repositories are store locally in my computer and only way that i found that works around the issue for now is using the web version of vscode provide by github since after that error vscode won't let me commit any repos using the terminal or commit buttons.

**Comment by steveward** [comment]
If VSCode also isn't working then this seems like it could be a system issue. What happens if you try to commit via the terminal?

**Comment by 4troDev** [comment]
commands such as commit and push won't work/respond but any other command like help works

**Comment by sergiou87** [comment]
Hey @4troDev a few questions:
1. Do you run any kind of antivirus running on your system?
2. What's the output of the git commands when you run them from the terminal?
3. Does this happen with repositories cloned from the terminal?

**Comment by 4troDev** [comment]
I don't use a VPN, but I've had no issues with Cloudflare DNS.

It seems that the command line is working fine now. However, sometimes it fails to recognize the git commands. For example, when I tried to commit, I had to try multiple times as it did not register the message `git commit -m "test"`. I'm now also able to use the source control extension within the Visual Studio Code application once again.

No, it doesn't happen when using the clone command within the terminal but I still get the same errors from the desktop app.

**Comment by sergiou87** [comment]
Sorry I didn't mean a VPN but an antivirus or antimalware, some kind of software scanning your files looking for virus or other kinds of malicious software. Those sometimes prevent certain files from running (or even delete them or put them in quarantine)

**Comment by 4troDev** [comment]
I don't have any antivirus software installed.

**Comment by sergiou87** [comment]
Do you have any other machines where you could try this?

**Comment by 4troDev** [comment]
unfortinally i don't

**Comment by steveward** [comment]
Can you run `git fsck` from the command line on that "jsgcorp.com" repository to see if it returns anything?

This error is showing up in the log:

```
error: rev-list died of signal 10
error: https://github.com/JSGC-NY/jsgccorp.com.git did not send all necessary objects
```

**Comment by 4troDev** [comment]
I try running the command multiple times the return I get is `zsh: bus error  git fsckies:  47% (121/256)`
<img width="432" alt="Screenshot 2024-02-16 at 8 35 14 AM" src="https://github.com/desktop/desktop/assets/86755192/e111af5f-f0c7-4cfd-9067-5498fc20e045">

**Comment by steveward** [comment]
Unfortunately since you're encountering errors in the Git command line as well it seems like this is a broader system issue. The bus errors we've seen like this were all caused by using SMB shares. Have you tried running Disk Utility First Aid to see if there are any filesystem issues?

**Comment by 4troDev** [comment]
> Unfortunately since you're encountering errors in the Git command line as well it seems like this is a broader system issue. The bus errors we've seen like this were all caused by using SMB shares. Have you tried running Disk Utility First Aid to see if there are any filesystem issues?

Couldn't find any file system issues but it seems to happen for that specific repo now

**Comment by ZoeB** [comment]
Hi!

> ```
> error: rev-list died of signal 10
> ```

I just got this exact same error on a completely unrelated repository of my own, and a Web search revealed this page as the only other example I can find.  You know what I just did in my own repo?  I added some brackets to a directory name.  (And then tried to push to a non-Mac NAS.)

I see this is in your log file:

> ```
> /Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)
> ```

Is that directory name new?  If so, that might explain the issue.  Maybe Git over Samba doesn't like brackets in ~~filenames or~~ directory names..?

**Comment by 4troDev** [comment]
personally to get it fix i restarted my github desktop app like i reinstall the app and link all the repositories again and that some how fixed the problem i had since none of the instructions i got worked some how so i recommend you to try the steps they left here and if they don't work delete and reinstall the app and after link all the repositories again

**Comment by 4troDev** [comment]
> personally to get it fix i restarted my github desktop app like i reinstall the app and link all the repositories again and that some how fixed the problem i had since none of the instructions i got worked some how so i recommend you to try the steps they left here and if they don't work delete and reinstall the app and after link all the repositories again 

but i also recommend you to also reported it in a separate issues since more experience people would be able to see it
