### ISSUE TITLE
Discarding or stashing changes still leaves them in the changes

### ISSUE THREAD

**Issue by Hesuri** [desktop/desktop#18123]
### The problem

When trying to discard or stash changes in Github Desktop, the changes will not disappear from the changes section. I'm developing a game with Unreal Engine 5.2.1 with other people and no one else is having this problem. We're also using Git LFS.

### Release version

3.3.8

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Go to current repository
2. Select changes you want to discard/stash
3. Right-mouse-click on the changes
4. Try to discard or stash the changes
5. The changes will go to the stash or the recycle bin but also stay in the changes

### Screenshots

![git](https://github.com/desktop/desktop/assets/56963530/5439ad3c-6bcf-4cdc-934f-aabb4fe48fb0)

**Comment by steveward** [comment]
Thanks for the report @Hesuri. I tried reproducing this but have been unsuccessful so far. A couple of questions:

- Does discarding files that aren't binary work without issue?
- Are you storing this repository in WSL, a network drive, or a file syncing service? We've seen some edge cases in those scenarios.

**Comment by shoshoy2018** [comment]
> ### The problem
> When trying to discard or stash changes in Github Desktop, the changes will not disappear from the changes section. I'm developing a game with Unreal Engine 5.2.1 with other people and no one else is having this problem. We're also using Git LFS.
> 
> ### Release version
> 3.3.8
> 
> ### Operating system
> Windows 10
> 
> ### Steps to reproduce the behavior
> 1. Go to current repository
> 2. Select changes you want to discard/stash
> 3. Right-mouse-click on the changes
> 4. Try to discard or stash the changes
> 5. The changes will go to the stash or the recycle bin but also stay in the changes
> 
> ### Log files
> _No response_
> 
> ### Screenshots
> ![git](https://private-user-images.githubusercontent.com/56963530/301826748-5439ad3c-6bcf-4cdc-934f-aabb4fe48fb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MDQ2MzcsIm5iZiI6MTcwNjkwNDMzNywicGF0aCI6Ii81Njk2MzUzMC8zMDE4MjY3NDgtNTQzOWFkM2MtNmJjZi00Y2RjLTkzNGYtYWFiYjRmZTQ4ZmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDIwMDUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMzU3NmVlNTM0ZjI3YzJkM2Q3YjVhMTJiZjI4ZmM0OGZiYmM0OTVlNTkzOWE2NWNhZTlkZWMzNDU1OGU3ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o1kRvX45RGFhuFt42IeOC2Dj4DCQEvcYRJHD73ubP4o)
> 
> ### Additional context
> _No response_

**Comment by Hesuri** [comment]
> Thanks for the report @Hesuri. I tried reproducing this but have been unsuccessful so far. A couple of questions:
> 
> * Does discarding files that aren't binary work without issue?
> * Are you storing this repository in WSL, a network drive, or a file syncing service? We've seen some edge cases in those scenarios.

Yes, discarding other files does work.
The repository is solely on my hard drive.

**Comment by steveward** [comment]
You can use the command line and run `git clean -f` to force the changes to be discarded. Let me know if this still persists after doing that.

**Comment by Hesuri** [comment]
The problem still remains. I think it's caused by Git LFS.

**Comment by steveward** [comment]
I found this [StackOverflow question ](https://stackoverflow.com/questions/71236993/git-lfs-cannot-discard-file-changes-encountered-files-that-should-have-been-poi) that has a potential solution -- could you try that to see if it resolves this?

**Comment by steveward** [comment]
I'm going to close this out as we have not heard back, but let me know if you're still having this issue and we can investigate further.

**Comment by oguzhantorayev** [comment]
You have the Unreal editor still open so it's not gonna discard your changes on GitHub. You need to close the editor to do it

**Comment by 300mice** [comment]
> You have the Unreal editor still open so it's not gonna discard your changes on GitHub. You need to close the editor to do it

No this issue persists if the editor is closed

**Comment by mrtckane84** [comment]
This is definitely a bug.

What's more, it prevents switching branch. - "you have changes that will be overwritten!" (with no 'do it anyway' button, of course) ...

**Comment by FelixDraconis** [comment]
We have just developed this problem in the past few months after a year of running just fine.  My whole team constantly has to check in random image / font / asset file changes, often with no actual change.  I call this 'Git Jail'.  It seems to be getting worse.

Closing Unity does nothing.  Reverting and shelving does nothing.  It is definitely a Git problem and might have something to do with LFS.

The only way to unblock yourself is to check in those files, good or bad, and hope you didn't accidentally revert someone's work.

GitHub Desktop 3.4.3 if it matters.

Dodging the problem by closing it and saying 'not our problem' by tossing out cryptic command line nonsense and hoping people can 'muck it out for themselves' is exactly the problem with Git's development track.  The problem is not solved.

**Comment by mrtckane84** [comment]
As of 27/09/24 - still a problem, and this happened to me a few weeks ago and the resolution did even more damage and took a while to row back from.

**Comment by mrtckane84** [comment]
As of 22/10/24 - still a thing.

This solution works: https://stackoverflow.com/questions/18536863/git-refuses-to-reset-discard-files
But be warned, it triggers a full re-import in unity - expect to get very little done -_-

...literally no idea why this is 'closed' as 'completed' - that's just aggravating.

**Comment by shadowsora211** [comment]
I just had this issue with a uasset for the first time today

But I switched branch, selected stash the changes, switched back, discarded the stach... seems to be normal now?

**Comment by mrtckane84** [comment]
> I just had this issue with a uasset for the first time today
> 
> But I switched branch, selected stash the changes, switched back, discarded the stach... seems to be normal now?

At a certain point this can compound.

You select 'discard' and the changes leap into the changes panel on the left, and stay in the stash as well, so now you can't discard and when you try to switch branch it will say 'stash changes?' and when you say 'yes' it will sperg out as the stash is already laden.
