### ISSUE TITLE
The name is not activatable

### ISSUE THREAD

**Issue by mdshehabsk** [desktop/desktop#18121]
### The problem

I am using Arch Linux. I downloaded GitHub-desktop after completing the installation process when I am trying to get a signing it opens my default browser and shows me an error that 

>  ### The name is not activatable

I will give an error screenshot image

### Release version

Version 3.3.6-linux3 (x64)

### Operating system

Arch linux

### Screenshots

![github-desktop-error](https://github.com/desktop/desktop/assets/85302877/01a8e319-610c-4663-8f58-2c1f8ee0df55)

**Comment by sergiou87** [comment]
@mdshehabsk issues related to the unofficial Linux fork of GitHub Desktop can be filed here:

https://github.com/shiftkey/desktop/issues

At this time we only officially provide support for macOS and Windows.

Sorry!

**Comment by paulo1403** [comment]
I have the same problem, any solution?

**Comment by CampbellRankine** [comment]
Not that I know of, Paulo


Regards,

DR CAMPBELL RANKINE

***@***.******@***.***>

mobile  +61 (0)412 222 966   |   GPO Box 998, Adelaide, South Australia 5001

[cid:d15aed35-409c-43fb-9286-f39807938d3b]

Liability limited by a scheme approved under Professional Standards Legislation.

[cid:b6636bb1-d960-4ace-b33d-ea7ac8f6939c]



This email, and any files transmitted with it, contains confidential information which may be subject to legal privilege.  Confidentiality and privilege are not waived if you are not the intended recipient of this email.  If you are not the intended recipient, please delete it and notify Campbell Rankine by email.  Although reasonable precautions are taken, Campbell Rankine does not warrant this transmission or attachments are free from viruses or similar malicious code and does not accept liability for any consequences to the recipient consequent upon opening or using this email.  You are strongly advised to check any attachments prior to use.

P Please consider the environment before printing this email.



________________________________

**Comment by dpa-snyder** [comment]
You have to have the gnome-keyring installed and setup.
this is the fix from the same error on shiftkey.

remove github-desktop-bin
delete the GitHub Desktop folder in ~/.config
install gnome-keyring with pacman -S gnome-keyring
reinstall github-desktop-bin with the AUR package manager you use
have system default browser singed into github account you wish to use
launch github desktop, sign in... 

works - i'm running Arch via EndeavourOS with hyprland

**Comment by mpolinowski** [comment]
```
yay -R github-desktop-bin
rm -rf ~/.config/GitHub\ Desktop
```

```
sudo pacman -S gnome-keyring
```


```
yay -S github-desktop-bin

 -> error installing: [/home/myuser/.cache/yay/github-desktop-bin/github-desktop-bin-3.3.12_linux2-1-x86_64.pkg.tar.zst /home/myuser/.cache/yay/github-desktop-bin/github-desktop-bin-debug-3.3.12_linux2-1-x86_64.pkg.tar.zst] - exit status 1
```


```
sudo rm -rf /usr/lib/debug/opt/github-desktop
```

```
yay -S github-desktop-bin

error: failed to commit transaction (conflicting files)
github-desktop-bin-debug: /usr/lib/debug/.build-id/0e/48bda45b629abf17c9e1707389dd6112734489 exists in filesystem (owned by github-desktop-debug)
github-desktop-bin-debug: /usr/lib/debug/.build-id/0e/48bda45b629abf17c9e1707389dd6112734489.debug exists in filesystem (owned by github-desktop-debug)

...
```

```
sudo rm -rf /usr/lib/debug/.build-id
```

```
yay -S github-desktop-bin
````

works on a fresh EndeavourOS with hyprland installation 👍🏻

**Comment by mdshehabsk** [comment]
@mpolinowski thanks for your response. I am not a Arch user anymore last 2 months I am using Fedora and its working fine for me

**Comment by mpolinowski** [comment]
This seems to be an EndeavourOS 'feature'. I was using this on Manjaro before without any issues ~ EOS just misses the keyring 😆

**Comment by Edian-the-professional-idiot** [comment]
> You have to have the gnome-keyring installed and setup. this is the fix from the same error on shiftkey.
> 
> remove github-desktop-bin delete the GitHub Desktop folder in ~/.config install gnome-keyring with pacman -S gnome-keyring reinstall github-desktop-bin with the AUR package manager you use have browser singed into github account you wish to use launch github desktop, sign in...
> 
> works - i'm running Arch via EndeavourOS with hyprland

Not sure if it breaks anything but I only installed the key ring via pacman, no uninstalling needed. works fine for me now. thanks for the fix!

**Comment by XBEAST1** [comment]
> You have to have the gnome-keyring installed and setup. this is the fix from the same error on shiftkey.
> 
> remove github-desktop-bin delete the GitHub Desktop folder in ~/.config install gnome-keyring with pacman -S gnome-keyring reinstall github-desktop-bin with the AUR package manager you use have browser singed into github account you wish to use launch github desktop, sign in...
> 
> works - i'm running Arch via EndeavourOS with hyprland

Thank You So Much Works Like a Charm 💓

**Comment by Ghoul4500** [comment]
> ```
> yay -R github-desktop-bin
> rm -rf ~/.config/GitHub\ Desktop
> ```
> 
> ```
> sudo pacman -S gnome-keyring
> ```
> 
> ```
> yay -S github-desktop-bin
> 
>  -> error installing: [/home/myuser/.cache/yay/github-desktop-bin/github-desktop-bin-3.3.12_linux2-1-x86_64.pkg.tar.zst /home/myuser/.cache/yay/github-desktop-bin/github-desktop-bin-debug-3.3.12_linux2-1-x86_64.pkg.tar.zst] - exit status 1
> ```
> 
> ```
> sudo rm -rf /usr/lib/debug/opt/github-desktop
> ```
> 
> ```
> yay -S github-desktop-bin
> 
> error: failed to commit transaction (conflicting files)
> github-desktop-bin-debug: /usr/lib/debug/.build-id/0e/48bda45b629abf17c9e1707389dd6112734489 exists in filesystem (owned by github-desktop-debug)
> github-desktop-bin-debug: /usr/lib/debug/.build-id/0e/48bda45b629abf17c9e1707389dd6112734489.debug exists in filesystem (owned by github-desktop-debug)
> 
> ...
> ```
> 
> ```
> sudo rm -rf /usr/lib/debug/.build-id
> ```
> 
> ```
> yay -S github-desktop-bin
> ```
> 
> works on a fresh EndeavourOS with hyprland installation 👍🏻

Works perfectly on Arch. Thanks

**Comment by arturfast** [comment]
I fixed it by installing a notification daemon. You can find a list of them here: https://wiki.archlinux.org/title/Desktop_notifications

**Comment by mohdlatif** [comment]
> You have to have the gnome-keyring installed and setup. this is the fix from the same error on shiftkey.
> 
> remove github-desktop-bin delete the GitHub Desktop folder in ~/.config install gnome-keyring with pacman -S gnome-keyring reinstall github-desktop-bin with the AUR package manager you use have system default browser singed into github account you wish to use launch github desktop, sign in...
> 
> works - i'm running Arch via EndeavourOS with hyprland

Thank you so much

**Comment by MRK0x** [comment]
in arch inux you can use this for fix it 
nano ~/.local/share/applications/github-desktop.desktop
Exec=env --unset=WAYLAND_DISPLAY /usr/bin/github-desktop
Save and exit (Ctrl+X, Y, Enter).
sudo pacman -S --needed libxcrypt gnome-keyring
for Wayland
sudo pacman -S xdg-desktop-portal xdg-desktop-portal-wlr
Then restart:
systemctl --user restart xdg-desktop-portal.service
try this 
github-desktop --disable-gpu-sandbox --disable-seccomp-filter-sandbox

or open it normal

**Comment by ytcyde** [comment]
Gets me stuck in a login loop.

> in arch inux you can use this for fix it nano ~/.local/share/applications/github-desktop.desktop Exec=env --unset=WAYLAND_DISPLAY /usr/bin/github-desktop Save and exit (Ctrl+X, Y, Enter). sudo pacman -S --needed libxcrypt gnome-keyring for Wayland sudo pacman -S xdg-desktop-portal xdg-desktop-portal-wlr Then restart: systemctl --user restart xdg-desktop-portal.service try this github-desktop --disable-gpu-sandbox --disable-seccomp-filter-sandbox
> 
> or open it normal

**Comment by andremalenfant** [comment]
> You have to have the gnome-keyring installed and setup. this is the fix from the same error on shiftkey.
> 
> remove github-desktop-bin delete the GitHub Desktop folder in ~/.config install gnome-keyring with pacman -S gnome-keyring reinstall github-desktop-bin with the AUR package manager you use have system default browser singed into github account you wish to use launch github desktop, sign in...
> 
> works - i'm running Arch via EndeavourOS with hyprland

Thanks a lot. Did not have to uninstall/install GH desktop though.
