### ISSUE TITLE
Select IDE for different projects

### ISSUE THREAD

**Issue by diedyesterdaywashere** [desktop/desktop#18128]
### The feature request

Some people use different IDEs for different projects, and at the time of writing this, I could not find a way to make github desktop open one project with VSCode, and another one with IntelliJ IDEA.

### Proposed solution

This could be a setting when cloning a repository, or it could be in the context menu when right clicking it in the list/top left corner.
It would save time so people don't need to open the project in explorer and opening the project file by hand, instead they'll just set an IDE, and then use the open with IDE button in GitHub Desktop.

**Comment by sergiou87** [comment]
Thanks for the issue @diedyesterdaywashere -- this is being tracked in https://github.com/desktop/desktop/issues/12195 so you can follow along there for updates. I'm going to close this out.
