### ISSUE TITLE
Github Desktop won't open without crashing on Mac M1 Processor

### ISSUE THREAD

**Issue by sahgilbert** [desktop/desktop#18138]
### The problem

When I open the latest version of Github Desktop on Mac OS Sonoma 14.3, it crashes immediately.

### Release version

It crashes before I can check but it's the latest version on 6th Feb 2024

### Operating system

Mac OS Sonoma 14.3

### Steps to reproduce the behavior

Download latest version of Github Desktop.
Move downloaded app to Applications folder.
Open app.
Observe crash

### Log files

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               GitHub Desktop [16627]
Path:                  /Applications/GitHub Desktop.app/Contents/MacOS/GitHub Desktop
Identifier:            com.github.GitHubClient
Version:               3.3.9-beta1 (3.3.9-beta1)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-02-06 00:02:39.8988 +0000
OS Version:            macOS 14.3 (23D56)
Report Version:        12
Anonymous UUID:        1ED14A19-1659-16B1-30B5-80B10892C62D

Time Awake Since Boot: 850 seconds

System Integrity Protection: enabled

Notes:
PC register does not match crashing frame (0x0 vs 0x11A3AD4E6)

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [16627]

Error Formulating Crash Report:
PC register does not match crashing frame (0x0 vs 0x11A3AD4E6)

Thread 0 Crashed:: CrBrowserMain Dispatch queue: com.apple.main-thread
0   Electron Framework            	       0x11a3ad4e6 node::AsyncResource::get_async_id() const + 9155430
1   Electron Framework            	       0x11960132a v8::internal::SetupIsolateDelegate::SetupBuiltins(v8::internal::Isolate*, bool) + 5913274
2   Electron Framework            	       0x1195fe2f6 v8::internal::SetupIsolateDelegate::SetupBuiltins(v8::internal::Isolate*, bool) + 5900934
3   Electron Framework            	       0x1195fd1ab v8::internal::SetupIsolateDelegate::SetupBuiltins(v8::internal::Isolate*, bool) + 5896507
4   Electron Framework            	       0x1196087e2 v8::internal::SetupIsolateDelegate::SetupBuiltins(v8::internal::Isolate*, bool) + 5943154
5   Electron Framework            	       0x119609d27 v8::internal::SetupIsolateDelegate::SetupBuiltins(v8::internal::Isolate*, bool) + 5948599
6   Electron Framework            	       0x1194303ff v8::internal::SetupIsolateDelegate::SetupBuiltins(v8::internal::Isolate*, bool) + 4008847
7   Electron Framework            	       0x11949a27c v8::internal::SetupIsolateDelegate::SetupBuiltins(v8::internal::Isolate*, bool) + 4442636
8   Electron Framework            	       0x11949a4e1 v8::internal::SetupIsolateDelegate::SetupBuiltins(v8::internal::Isolate*, bool) + 4443249
9   Electron Framework            	       0x11a3f6569 node::AsyncResource::get_async_id() const + 9454569
10  Electron Framework            	       0x11a4125cb node::AsyncResource::get_async_id() const + 9569355
11  Electron Framework            	       0x11a412e65 node::AsyncResource::get_async_id() const + 9571557
12  Electron Framework            	       0x1171056ee v8::internal::compiler::CodeAssemblerVariable::IsBound() const + 5166
13  Electron Framework            	       0x116c94c8a 0x116ac1000 + 1916042
14  Electron Framework            	       0x117104be1 v8::internal::compiler::CodeAssemblerVariable::IsBound() const + 2337
15  CoreFoundation                	    0x7ff806cf3716 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
16  CoreFoundation                	    0x7ff806cf36b9 __CFRunLoopDoSource0 + 157
17  CoreFoundation                	    0x7ff806cf3488 __CFRunLoopDoSources0 + 215
18  CoreFoundation                	    0x7ff806cf20f8 __CFRunLoopRun + 919
19  CoreFoundation                	    0x7ff806cf1799 CFRunLoopRunSpecific + 557
20  HIToolbox                     	    0x7ff811aa99d9 RunCurrentEventLoopInMode + 292
21  HIToolbox                     	    0x7ff811aa97e6 ReceiveNextEventCommon + 665
22  HIToolbox                     	    0x7ff811aa9531 _BlockUntilNextEventMatchingListInModeWithFilter + 66
23  AppKit                        	    0x7ff80a263c39 _DPSNextEvent + 880
24  AppKit                        	    0x7ff80ab6d804 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1304
25  AppKit                        	    0x7ff80a2551b2 -[NSApplication run] + 603
26  Electron Framework            	       0x117106436 v8::internal::compiler::CodeAssemblerVariable::IsBound() const + 8566
27  Electron Framework            	       0x1171045c1 v8::internal::compiler::CodeAssemblerVariable::IsBound() const + 769
28  Electron Framework            	       0x11a41312d node::AsyncResource::get_async_id() const + 9572269
29  Electron Framework            	       0x11a3d8a8f node::AsyncResource::get_async_id() const + 9333007
30  Electron Framework            	       0x11944c090 v8::internal::SetupIsolateDelegate::SetupBuiltins(v8::internal::Isolate*, bool) + 4122656
31  Electron Framework            	       0x11944da42 v8::internal::SetupIsolateDelegate::SetupBuiltins(v8::internal::Isolate*, bool) + 4129234
32  Electron Framework            	       0x1194499ef v8::internal::SetupIsolateDelegate::SetupBuiltins(v8::internal::Isolate*, bool) + 4112767
33  Electron Framework            	       0x117225c2d v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 17053
34  Electron Framework            	       0x117226c77 v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 21223
35  Electron Framework            	       0x117226a8f v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 20735
36  Electron Framework            	       0x117225525 v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 15253
37  Electron Framework            	       0x117225627 v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 15511
38  Electron Framework            	       0x116eea82b ElectronMain + 155
39  dyld                          	       0x204c12386 start + 1942

**Comment by sergiou87** [comment]
Hey @sahgilbert  it seems you're running the Intel version of the app. Have you tried the build specific for Apple silicon machines?

You can find it here: https://central.github.com/deployments/desktop/desktop/latest/darwin-arm64?env=beta

I hope that one works 🤞
