### ISSUE TITLE
randomly started getting "Failed to connect to github.com port 443 after 21048 ms: Couldn't connect to server"

### ISSUE THREAD

**Issue by ozgurkaderoglu** [desktop/desktop#18137]
fatal: unable to access 'https://github.com/user/The_Influence.git/': Failed to connect to github.com port 443 after 21048 ms: Couldn't connect to server
how do I solve this?
I did not even change anything or switch computers. I am not on a different wifi network than usual.

**Comment by steveward** [comment]
Thanks for the issue @ozgurkaderoglu. Are you behind a proxy or firewall? This could just be a temporary network issue, but this error is normally caused by a proxy, firewall, or DNS issue.

**Comment by ozgurkaderoglu** [comment]
Thanks for response. Me and my mates fixed it. It was a windows update that
turned the firewall on. We turned it off and it is fixed.

6 Şub 2024 Sal 00:31 tarihinde Steve Ward ***@***.***> şunu
yazdı:

**Comment by steveward** [comment]
Glad to hear things are working again!

**Comment by Jeremy-DX** [comment]
This error may be caused by your local VPN. When I close my local VPN, it works again.

**Comment by Jusaca01** [comment]
I don't have local VPN and just a year later, I faced the same problem. Thanks, but I think that before the problem I didn't turn off windows firewall

**Comment by davidnmbond** [comment]
I had the same symptom.

Disconnected and re-connected my OpenVPN client and instantly fixed.

**Comment by Jusaca01** [comment]
[like]  JUAN FRANCISCO SANZ CAVERO reacted to your message:
________________________________

**Comment by finorix079** [comment]
I have the same problem with my MacBook Pro.

Strangely, it is resolved for a random period of time after a restart. Then the same problem would come up again.

**Comment by dm-for-git** [comment]
Anyone else is facing this error again? this morning when using git(command line or and other git client apps):
"failed to connect to github.com port 443 after xxx ms"
Last night I still could access Github, but now I can't anymore.
I'm on MacOS Tahoe 26.2, I've tried Github desktop v3.5.5
