### ISSUE TITLE
Option to show actual timestamp for commits instead of "X days ago".

### ISSUE THREAD

**Issue by jonfullglass** [desktop/desktop#18136]
### The feature request

I find that i nearly always hover over the "X days ago" to get the timestamp for a commit. This is pretty key IMO for a fast moving team that makes multiple commits per day. For example, a deploy may be triggered by a commit, and i'd like to be able to quickly match up exactly which of today's deploys were caused by which commit, or quickly scan for which commits happened before/after a particular deploy.

### Proposed solution

There could be an option somewhere, named something like "Always show timestamps" (where true = use timestamp, false = use estimates) or "Use Estimated times" (true = use estimates, false = use timestamps". Default to the current behavior, sure, but allow people to customize what they see without resorting to custom stylesheets that will break if something in github changes.

**Comment by jakebullet70** [comment]
I am chasing some bugs right now and this would be very handy.

**Comment by steveward** [comment]
I'm going to consolidate this into https://github.com/desktop/desktop/issues/14611 where we are tracking this. Thanks for the feedback!
