### ISSUE TITLE
Cannot sign back in to Github Desktop

### ISSUE THREAD

**Issue by icyaiste** [desktop/desktop#18144]
### The problem

Cannot sign back in to Github Desktop.  When i need to authenticate with website, I press authenticate and then desktop version just loads forever without signing in.  
Github Desktop version 3.3.8
![Screenshot 2024-02-06 220635fff](https://github.com/desktop/desktop/assets/143514332/c1361e7b-baa9-4d98-8e65-7c0a9ca07bb0)

### Release version

3.3.8

### Operating system

Windows 11 Home

**Comment by sergiou87** [comment]
Hey @icyaiste 

Could you try temporarily changing your system default browser to another browser to rule out issues with your current one?

If that doesn't work I would also recommend rebooting your machine to see if that helps 🤞

**Comment by icyaiste** [comment]
It actually worked today and I didn’t do anything

Med vänlig hälsning, Aistė Smolenskaitė

**Comment by steveward** [comment]
Glad to hear things are working again!

**Comment by marcusx2** [comment]
I have the same problem, same operation system, trying a different browser doesn't work.
