### ISSUE TITLE
Bug report: GitHub desktop suddenly resetted and shows get started.

### ISSUE THREAD

**Issue by kwankiu** [desktop/desktop#18140]
### The problem

I didn't do anything, today when I open GitHub Desktop as usual it shows get started instead of my local repository.

The GitHub folder at Documents is still there, it just seems reset and need me to re-add each of my repository manually from file path.

### Release version

3.3.8 (arm64)

### Operating system

macOS 14.0 (Apple M1)

### Steps to reproduce the behavior

Just open GitHub Desktop as usual

### Log files

[2024-01-30.desktop.production.log](https://github.com/desktop/desktop/files/14178256/2024-01-30.desktop.production.log)
[2024-02-06.desktop.production.log](https://github.com/desktop/desktop/files/14178257/2024-02-06.desktop.production.log)

**Comment by sergiou87** [comment]
Hello @kwankiu 

That usually happens when an older version of Desktop is launched, and it's incompatible with the stored settings and repository list.

Is there a chance you manually installed an older version of Desktop (that later got auto-updated to the latest one)?

**Comment by kwankiu** [comment]
No idea, as I remember the last time i closed GitHub Desktop, I were only browsing with chrome to do school work. 
(before I closed the app I was deleting files from the mac settings -> general -> storage, but I didnt delete anything related to GitHub, only deleted some really large VM files)

The next day when I open GitHub Desktop it appears with the Get Started screen.

**Comment by sergiou87** [comment]
Does GitHub Desktop keep forgetting your repositories or it only happened that one time?

**Comment by kwankiu** [comment]
No, it seems only happened once.

**Comment by steveward** [comment]
Since this was a one-off issue I'm going to close this out, but let us know if you run into this again in the future!
