### ISSUE TITLE
GitHub Desktop does not respect `remote.pushDefault` or `branch.<name>.pushRemote`

### ISSUE THREAD

**Issue by ahmetsait** [desktop/desktop#18154]
### The problem

GitHub Desktop does not pick up `remote.pushDefault` or `branch.<name>.pushRemote` config parameters and always tries to push to `branch.<name>.remote` instead.

### Release version

3.3.9-beta1 (x64)

### Operating system

All

### Steps to reproduce the behavior

The following commands demonstrate a successful push to remote 'myfork' on my machine, you can test the same by replacing `https://github.com/ahmetsait/github-desktop.git` with the url of your own fork.
```sh
git clone https://github.com/desktop/desktop.git
cd desktop/
git remote add myfork https://github.com/ahmetsait/github-desktop.git
git commit --allow-empty -m "."
git config remote.pushDefault myfork
git push
```
GitHub Desktop still shows "↑ Push origin" and fails with a permission error when clicked.

### Screenshots

![image](https://github.com/desktop/desktop/assets/8372246/c5cbbf75-25de-4b2f-a6b4-2afcec29ef3c)

**Comment by sergiou87** [comment]
Hey @ahmetsait 

I'm sorry you're having trouble with that. Unfortunately GitHub Desktop is designed in such a way that simplifies interactions with forks by limiting the usage of different remotes.

If you want to work from a fork on GitHub Desktop, you should clone the fork and then choose whether you want to contribute to the parent repository, or just work on the fork itself. You can change this at any time from the `Repository` -> `Repository Settings…` menu.

**Comment by ahmetsait** [comment]
GitHub Desktop's "Push" button should do the same thing as `git push` which is currently not the case. These config options allow users to easily pull from many different remotes and push to their forks where they have write access without having to manually specify remote/branch names every time.

I understand that you guys are probably dealing with tons of user requests but it is very disheartening to see legitimate issues not getting acknowledged.
