### ISSUE TITLE
Inconsistent File Selection Behavior During Commits

### ISSUE THREAD

**Issue by albiorixvimal** [desktop/desktop#18155]
### The problem

When using GitHub Desktop to commit changes, the application is incorrectly committing all changed files in the repository even when only a single file is explicitly selected for the commit. This issue disrupts the workflow and prevents precise control over version history and changesets.

### Release version

Version 3.3.8 (x64)

### Operating system

Windows 10 Pro

### Steps to reproduce the behavior

- Open GitHub Desktop and navigate to a repository with multiple changed files.
- In the "Changes" tab, you can see the list of files that have been modified.
- Select only one file from the list of changed files by clicking on the checkbox next to the file name, ensuring that all other files remain unselected.
- Enter a commit message in the summary field.
- Click on the "Commit to [branch name]" button to commit the changes.
- After the commit, navigate to the "History" tab to view the recent commit.
- Click on the latest commit to see the details and list of files included in the commit.

Expected Behavior:
Only the selected file should be included in the commit, as per the user's selection.

Actual Behavior:
The commit includes all changed files in the repository, not just the file that was explicitly selected for the commit.

Environment:

GitHub Desktop version: [Version 3.3.8 (x64)]
Operating System and version: [Windows 10 Pro]

**Comment by sergiou87** [comment]
I cannot reproduce this behavior. Does it happen in all repositories? Could you share a video reproducing the problem so we can see if there is anything specific that you did and we didn't?
