### ISSUE TITLE
Incorrect merge for binary files

### ISSUE THREAD

**Issue by kaster14** [desktop/desktop#18168]
Caught this but it would have messed up a release and been a costly patch, please please please get this issue fixed!! :-)

In my use case I had a commit that had changes to an xlsx file (binary files, Desktop won't show the diffs, side note I created a diff and merge program for .xlsx files because of this specific shortcoming in Github desktop...)

Steps to reproduce:
1. Have .xlsx file tracked in the repo
2. Make a change to it, commit changes
3. Cherry pick commit to another branch
Note, when I cherry picked I drag and dropped it into the target branch, also I may have also had multiple commits selected, (some of which were strictly changes to non binary files) when dragging and dropping, I do not know if that specific use case is related or not

In the target branch that received the cherry pick the commit showed up as "no files in commit" upon checking the binary file my changes were not there!

In the screenshots you can see that the changes were present on the "dev" branch where they were made and on the "JF-v0.2.11-base-branch" where the commit was cherry picked to, the commit shows no files were changed.

PR # 331 with changes to 2 xlsx files:
![dev branch with xlsx changes](https://github.com/desktop/desktop/assets/13577286/ee0217b5-5b1f-4892-99ed-f8a6f001af8d)

Cherry picked commit PR # 331, changes are missing:
![target base branch missing changes](https://github.com/desktop/desktop/assets/13577286/b30dc51d-edb3-4ea7-920a-af9102f386a1)

_Originally posted by @kaster14 in https://github.com/desktop/desktop/issues/12931#issuecomment-1729856357_

**Comment by tidy-dev** [comment]
@kaster14 Thank you for opening this issue, tho I believe it is still the same issue reported in #12931 and we are tracking feedback on that issue there. I am going to close this in favor of tracking it there.
