### ISSUE TITLE
Offline Built In AI Commit Name Generator

### ISSUE THREAD

**Issue by wisamidris7** [desktop/desktop#18179]
### The feature request

I Always Starving When Writing Commit Name And I Some Times Do That
![image](https://github.com/desktop/desktop/assets/104096256/53eef162-eddf-4123-9f7e-f3cfec0f4a22)

And If There Gonna Be Built In Feature For Commit Name Writing

### Proposed solution

...

**Comment by steveward** [comment]
Thanks for the issue @wisamidris7, this is being tracked in https://github.com/desktop/desktop/issues/17439 so you can follow along there for updates!
