### ISSUE TITLE
authentication fails for https://{username}@github.com remote

### ISSUE THREAD

**Issue by craftedsystems** [desktop/desktop#1817]
### Description

Can not access my private GitHub repository as the remote syntax isn't handled by the application.

### Version

**GitHub Desktop version:** 0.5.8
**OS version:** macOS 10.12.5

### Steps to Reproduce

1. Open Local Repository (private GitHub repository)
1. Trying to Push
1. Error: Athentication failed.
1. Logging out and in again.
1. Trying to Push
1. Error: Athentication failed.

![screen shot 2017-05-29 at 17 22 13](https://cloud.githubusercontent.com/assets/26137287/26555188/386922ca-4494-11e7-941b-7e53655ac509.png)

**Expected behaviour:** Pushing commit
**Actual behaviour:** Authentication fails
**Reproduces how often:** 100%

### Logs

```log
2017-05-29T09:25:29.011Z - info: Opt in reported.
2017-05-29T09:25:29.565Z - info: Stats reported.
```

#### Additional Information

This issue does not appear with the current (stable) GitHub Desktop client.

**Comment by shiftkey** [comment]
@craftedsystems could you open the Dev Tools and see if there's any errors there? I get the feeling this is related to #1796 which is being worked on, but I'd like to confirm this is the case...

**Comment by EisenbergEffect** [comment]
I'm having the same issue, but for a public repository for which I'm the admin. Here's what I'm seeing in the dev tools:

<img width="759" alt="error" src="https://cloud.githubusercontent.com/assets/131485/26557367/cb185c1a-4455-11e7-863d-7c682475874e.png">

**Comment by shiftkey** [comment]
@EisenbergEffect @craftedsystems ooh, another question - HTTPS or SSH remote?

**Comment by EisenbergEffect** [comment]
Is this something that's dependent on how the repository was originally cloned?

**Comment by shiftkey** [comment]
@EisenbergEffect yeah, if you run this command from the terminal in the repository you should see the remote URL:

```
git remote -vv
```

We haven't gotten around to proper support for SSH remotes (see #1795 for example) and I wanted to confirm that you're using a HTTPS remote (which we do default to if you've cloned the repository in Desktop)

**Comment by EisenbergEffect** [comment]
Here's what I've got:

```
origin	git@github.com:aurelia/logging.git (fetch)
origin	git@github.com:aurelia/logging.git (push)
``` 

Do HTTPS remotes work with two-factor auth?

**Comment by shiftkey** [comment]
Cool, that sounds like we're on the right track.

> Do HTTPS remotes work with two-factor auth?

@EisenbergEffect we handle the 2FA flow when you sign into your GitHub account in the app, and the authorization token we use then is stored locally for use with your Git operations. So if you switch it over to a HTTPS remote we'll pass that token through to the Git operations.

```
git remote set-url origin https://github.com/aurelia/logging.git
```

**Comment by alshenetsky** [comment]
I'm having the same issue.

![2017-05-29 20 28 07](https://cloud.githubusercontent.com/assets/8052634/26557893/61aed986-44ad-11e7-808d-08e2f466aebb.png)

**Comment by shiftkey** [comment]
@alshenetsky unfortunately that's a different issue which we're tracking in #1653

**Comment by craftedsystems** [comment]
@shiftkey here is a screenshot of the console when selecting `Fetch origin`
![screen shot 2017-05-29 at 20 51 32](https://cloud.githubusercontent.com/assets/26137287/26559631/0a88f516-44b1-11e7-8000-1d2c1946ba86.png)

**Comment by shiftkey** [comment]
@craftedsystems ah, the `craftedsystems@github.com` syntax isn't currently supported. If you drop that off from the remote that should get you back to a happy place.

```
git remote set-url origin https://github.com/craftedsystems/{name}.git
```

**Comment by craftedsystems** [comment]
@shiftkey now everything is fine again. Thx 👏

**Comment by shiftkey** [comment]
@craftedsystems you're welcome. I'll leave this open a bit to get the @desktop/core input on whether we want to capture the `username@github.com` authentication syntax as a proper issue, as I expect we'll have some compatibility issues if we don't handle it at some stage...

**Comment by EisenbergEffect** [comment]
I can confirm the remote switch to https works as well. Much thanks!

**Comment by Saturate** [comment]
I'm having this issue on a VSTS git repo on HTTPS.

**Comment by shiftkey** [comment]
@Saturate that's a slightly different issue, see #1653 for that tracking task

**Comment by joshaber** [comment]
> I'll leave this open a bit to get the @desktop/core input on whether we want to capture the https://username@github.com authentication syntax as a proper issue

Opened https://github.com/desktop/desktop/issues/1826.

**Comment by shiftkey** [comment]
@joshaber gonna close this out as I think that's everything

**Comment by prageethw** [comment]
this could be 2fa enabled in your account...
