### ISSUE TITLE
Automatically detects the most-appropriate IDE for current repository to call by CMD+SHIFT+A.

### ISSUE THREAD

**Issue by ShikiSuen** [desktop/desktop#18170]
### The feature request

Title: Automatically detects the most-appropriate IDE for current repository to call by CMD+SHIFT+A.

Description: Different repository holds different projects. Currently, GitHub Desktop app only allows users to specificy only one IDE to open current repository by CMD+SHIFT+A.

### Proposed solution

Suppose that you have different repositories managing an app's Xcode project and homepage, and he wants to use Xcode to open the Xcode project (and VSCode for the homepage repo). In this case, you want this feature request to be considered.

### Additional context

N/A

**Comment by tidy-dev** [comment]
@ShikiSuen Thank you for the suggestion. This is a very similar request to https://github.com/desktop/desktop/issues/12195 and therefore, I am going to capture your feedback there.
