### ISSUE TITLE
Wont let me publish branch from github desktop to github.

### ISSUE THREAD

**Issue by snurdlgod** [desktop/desktop#18189]
### The problem

Ive been trying to upload my repo from github desktop but keep getting a error that a file is missing but i check the directory and it is there. How could this be fixed

### Release version

3.3.8

### Operating system

windows 10

### Log files

[2024-02-17.desktop.production.log](https://github.com/desktop/desktop/files/14320270/2024-02-17.desktop.production.log)

**Comment by snurdlgod** [comment]
also forgot to mention this is the error i keep getting 

Git LFS upload failed:
  (missing) games/drift-hunters/dh.data.unityweb (b50603116417bb1d472acf0c2e76a5b560da960486081b4f257b0afcb8d9ab09)
hint: Your push was rejected due to missing or corrupt local objects.
hint: You can disable this check with: `git config lfs.allowincompletepush true`

**Comment by steveward** [comment]
Thanks for the report @snurdlgod. You could try running this from the command line (Repository -> Open in command line):

`git lfs fetch --all origin <branch-name>`

That should get things working and fetch the missing objects, but let me know if you have any further issues!
