### ISSUE TITLE
GitHub Desktop Download error

### ISSUE THREAD

**Issue by Geetika-Sachdeva** [desktop/desktop#18186]
### The problem

Getting this error 
![1be498ce-ab22-48bf-8deb-fdb0060ba1e1](https://github.com/desktop/desktop/assets/73252231/2b1f6196-72ff-4b4e-b8a2-d75685344b6b)

I have 64 bit Windows 7 version

### Release version

I dont know

### Operating system

64 bit Windows 7

### Steps to reproduce the behavior

1. Downloaded the set up file
2. Run the set up file
3. got error - dynamic link library kernel32.dll not found.

### Screenshots

![image](https://github.com/desktop/desktop/assets/73252231/820b1030-5dec-4951-9f25-32b4e82fc29c)

**Comment by sergiou87** [comment]
Unfortunately, Windows 7 is not supported anymore 😞 

The latest version available for Windows 7 is 3.2.6 and you can download it from here:
- GitHub Desktop 3.2.6 for Windows: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.2.6-de80a354/GitHubDesktopSetup-x64.exe
