### ISSUE TITLE
Github Desktop with VSCode Remote Development 

### ISSUE THREAD

**Issue by NazariiShvets** [desktop/desktop#18199]
### The feature request

Our team has a setup with Remote SSH, where we connect to remote machine via VSCode extension and developing direcly on that machine.

This posses a limitation on our tools, and one of them is Github Desktop. UX of Github Desktop is far supperior than VSCode Source Control and we rely on it. Using bare commands or UI provided by VSCode Source Control makes our life miserable

Best case solution would be "native" VSCode Extension

Critial features:
- "Changes" tab "as is" (checkboxes for files + commit form)
- "Branches" dropdown "as is" (with ability to switch between branches and create new branch + move all uncommited changes to it)
- "History" tab "as is" ("Undo commit", "Ammend commit")
- "Publish/Pull/Push branch"

Rest of them would be nice to have, but limited set of features would be sufficient

### Proposed solution
VSCode Remote Development Window runs with all extentions installed for my local VSCode. Thats why I see it as easiest way to integrate

AFAIK VSCode Extension can render custom view, so there is possibility to pack whole frontend and run it within webview provided by extention

**Comment by steveward** [comment]
Thanks for the issue @NazariiShvets. I'm going to add this to https://github.com/desktop/desktop/issues/11667 where we are tracking feedback about this feature.
