### ISSUE TITLE
Problems handeling jetbrains pycharm with community and professional version

### ISSUE THREAD

**Issue by Cedric-Ab** [desktop/desktop#18200]
### The problem

EDIT (updated problem):

GitHub Desktop doesn't recognize pycharm when installed with jetbrains toolbox.

OLD problem:
I once had pycharm community edition on my laptop and it showed "pycharm community edition" and for some reason also "pycharm" (as of the professional version), probably because I had the professional version on an other profile.
Now I uninstalled the community edition on this profile and installed the professional version.
But now when I try to open it from GitHub Desktop it gives the this error:
![image](https://github.com/desktop/desktop/assets/142994683/b9eee3e9-0706-48f1-83d6-90c26ca9dc7e)

### Release version

3.3.9-beta2 (x64)

### Operating system

Windows 10

### Additional context

The correct location for pycharm is:
"C:\Users\UserName\AppData\Local\Programs\PyCharm Professional\bin\pycharm64.exe"

OLD:
I have even deleted everything inside of the jetbrains folder
![image](https://github.com/desktop/desktop/assets/142994683/d5be1608-42de-4411-b4c3-3cc8344a239c)
I installed pycharm via the jetbrains toolbox, maybe this causes problems. Also the community editions I had installed previously were most likely installed directly.

**Comment by steveward** [comment]
@Cedric-Ab thanks for the issue. Did you restart GitHub Desktop after installing the new professional edition? The app needs a restart in order to properly detect the new installation. Let me know if that doesn't get things working.

**Comment by Cedric-Ab** [comment]
@steveward I did all that and even reinstalled GitHub Desktop

**Comment by steveward** [comment]
What version of PyCharm is being shown in the Integrations -> External Editor list?

**Comment by Cedric-Ab** [comment]
No version, that’s the thing

**Comment by steveward** [comment]
Could you check the registry to see the version of PyCharm shown there? You'll want to check `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\` and look for PyCharm.

**Comment by Cedric-Ab** [comment]
There somehow is no pycharm there. 
This seems like a problem with the way editors are getting detected or a problem with pycharm installation via the jetbrains toolbox.
![image](https://github.com/desktop/desktop/assets/142994683/dfa5eaa0-24c1-4172-9212-a36b759a3762)

**Comment by Cedric-Ab** [comment]
This somehow now fixed

**Comment by Cedric-Ab** [comment]
This somehow now fixed
