### ISSUE TITLE
Copyright Year is Outdated on desktop.github.com

### ISSUE THREAD

**Issue by DylanDevelops** [desktop/desktop#18208]
### The problem

The copyright year states that it is copyrighted in 2023 but the main github.com website states 2024.

What it looks like:
<img width="466" alt="Screenshot 2024-02-23 at 11 24 47 AM" src="https://github.com/desktop/desktop/assets/48571264/15d50289-147f-45e0-b3bd-8b26532dd4d9">

I don't know what desktop.github.com is hosted on, but I can fix it if someone points me in the right direction. If it is something only GitHub staff can access then I can't.

### Release version

WEBSITE

### Operating system

Chrome OS

**Comment by steveward** [comment]
Thanks @DylanDevelops! The repo hosting the marketing site is internal so I'll get this updated there.

**Comment by steveward** [comment]
This will actually auto-update on our next deployment to the marketing site. Thanks again!

**Comment by DylanDevelops** [comment]
Sweet perfect! And no problem! :)
