### ISSUE TITLE
NII planning extras

### ISSUE THREAD

**Issue by SonomaticMatthewFleming** [desktop/desktop#18219]
### The problem

I'm working on a the NII project SI2146. When I load the SIMS model for the vessel V-0291 and go to the NII planning page, there are labels for a previous vessel superimposed over the vessel. I can delete most of them, except the 'tan to tan' and 'OD' labels. I have tried restarting SIMS and deleting the labels from the previous model, but this did not work. 

![image](https://github.com/desktop/desktop/assets/100136075/2e320fb2-0448-4ea4-b4c7-688d21928cdc)

### Release version

Version 3.3.8 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Open the SIMS model for V-0291
2. Click on the NII planning page
3. Extra labels are apparent

### Log files

[2024-Feb-26__06.32.39.log](https://github.com/desktop/desktop/files/14400852/2024-Feb-26__06.32.39.log)

**Comment by sergiou87** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
