### ISSUE TITLE
login problem

### ISSUE THREAD

**Issue by shailendrasaurav** [desktop/desktop#18229]
### The problem

i am trying to logout from github dekstop which has emaild1 ,even in my browser it has emailid2 but whenever i am trying to sign out it goes in the browser and emailid1 is logged in again in github dekstop

### Release version

new

### Operating system

windows 10

**Comment by moxie-coder** [comment]
it uses the account that is logged in on GitHub, you have to log out on GitHub then login to the account you’re trying to use

**Comment by steveward** [comment]
@shailendrasaurav what @moxie-coder said is correct, browser authentication requires your default browser to be logged in on github.com to the account you want to log in with to GitHub Desktop. We're tracking support for multiple accounts in https://github.com/desktop/desktop/issues/3707 if you'd like to follow along. I'm going to close this out, but let me know if you have any further questions.
