### ISSUE TITLE
Can't pull changes though UI can fetch remote commit gap

### ISSUE THREAD

**Issue by OSA413** [desktop/desktop#18228]
### The problem

Recently GitHub desktop started to throw "Authentication failed" errors for repositories I has logged in for a long ago. Re-entering credentials didn't help. The repositories in question are located on a self-hosted GitLab instance.

Currently I'm using git CLI to push and pull to the remote repositories, this way works.

### Release version

3.3.9

### Operating system

Windows 10

### Steps to reproduce the behavior

Several ways of reproduction:

1. Try to clone a repo from a self-hosted password protected GitLab instance
2. You get the error

Another way:

1. Clone a repo with git CLI
2. Add the repo locally to GitHub Desktop
3. GitHub Desktop fails to pull and push (thought it looks like it can fetch)

### Log files

```
2024-02-27T10:02:42.370Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
remote: HTTP Basic: Access denied. The provided password or token is incorrect or your account has 2FA enabled and you must use a personal access token instead of a password. See https://gitlab.urfu.ru/help/topics/git/troubleshooting_git#error-on-git-fetch-http-basic-access-denied
fatal: Authentication failed for 'https://[redacted].git/'
```

### Additional context

It works from git CLI

**Comment by steveward** [comment]
Thanks for the issue @OSA413. Are you generating an authentication token for GitHub Desktop to use with your GitLab account? Your regular username/password won't work -- see this [guide](https://github.com/desktop/desktop/blob/development/docs/integrations/gitlab.md).

**Comment by OSA413** [comment]
Yes, creating and using PAT worked. But why did it suddenly stopped working with just the password?

**Comment by OSA413** [comment]
I mean, my git CLI configured to username and password and it still works.

**Comment by steveward** [comment]
@OSA413 I'm not sure on all the specifics from GitLab's end, but if 2FA is enabled a token is required. I'm going to close this out since it's been resolved.

**Comment by OSA413** [comment]
@steveward Now (3.3.11) it won't accept even the PAT as password, it was working last week with the same PAT

Upd: either it doesn't work with specific repositories, or it may have problems when a submodule is located in another (second) private GitLab instance
