### ISSUE TITLE
Selecting deleted repo should show error message

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1822]
If a user selects a deleted repo for the Repo list, there is no error message even though a `fetch` occurs. If the user is already on the respective repo and clicks `fetch`, the error message appears. 

Shouldn't we surface the below message in both instances?

<img width="596" alt="screen shot 2017-05-30 at 10 35 41 am" src="https://cloud.githubusercontent.com/assets/14828183/26588692/04130f00-4524-11e7-8bb2-7b80893ecb12.png">

v0.5.8, OS X 10.11.5

**Comment by joshaber** [comment]
>If a user selects a deleted repo for the Repo list, there is no error message even though a fetch occurs.

How does a fetch occur? Doesn't the app show the Missing Repo view?

**Comment by tierninho** [comment]
To clarify, the deleted repos refer to those that are no longer on dotcom, but still on Desktop.

Seeing `executing: fetch: git -c credential.helper= fetch --progress --prune origin` in the console when I select the repo from the Repo list. Only see the missing repo dialogue when actually clicking the `fetch` button.

**Comment by joshaber** [comment]
Ahhh, I see, thanks for clarifying 👍 

That's the correct behavior. We only want to show the error dialog for user-initiated actions.
