### ISSUE TITLE
Eliminated repository keeps coming back

### ISSUE THREAD

**Issue by Pedre117** [desktop/desktop#18220]
### The problem

I want to push a new repository, which I had already included in an previous github repository that I eliminated due to issues with it. When I try to upload the repository it gets put in the old github repository and that causes an error when I try to push the changes in a commit as it says that the repository doesn't exist anymore.

### Release version

3.2.6

### Operating system

Windows 11

### Screenshots

![Screenshot 2024-02-26 103153](https://github.com/desktop/desktop/assets/126193501/33205306-faf9-45ab-ae98-524764e50317)

**Comment by steveward** [comment]
Thanks for the issue @Pedre117. Just to clarify -- did you delete the repository on GitHub? If the remote doesn't exist you can update it in `Repository` > `Repository Settings` > `Remote`. If you can share a few more details and differentiate between what you're trying to do with the local vs remote repository I can assist more.
