### ISSUE TITLE
"Commit To Main" button not active?

### ISSUE THREAD

**Issue by CanAhmet-Darama** [desktop/desktop#18224]
### The problem

"Commit To Main" button is not active. But there should be no reason for that. The last time I published a commit the same way

### Release version

3.3.9

### Operating system

Windows 10

### Screenshots

![2024-02-27_04-14-37](https://github.com/desktop/desktop/assets/100282560/d1f4edb3-aa58-447d-9060-fb47887b304d)

**Comment by tidy-dev** [comment]
@CanAhmet-Darama Just to clarify, are there changes to commit? 

Could you upload the log file for the day you experienced this? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs
