### ISSUE TITLE
it will not push

### ISSUE THREAD

**Issue by tamil126** [desktop/desktop#18221]
### The problem

Uploading LFS objects:   0% (0/101), 0 B | 0 B/s, done.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to push some refs to 'github.com:tamil126/MSS.git'

### Release version

Version 3.3.9 (x64)

### Operating system

windows 11

### Screenshots

![image](https://github.com/desktop/desktop/assets/138356000/68a60260-e615-4748-ab85-f890706894e1)

**Comment by steveward** [comment]
@tamil126 this error is due to needing to purchase more LFS data packs. See this article for more information:

https://docs.github.com/en/billing/managing-billing-for-git-large-file-storage/about-billing-for-git-large-file-storage

If you have further questions I would recommend reaching out to [GitHub Support](https://support.github.com/).

I'm going to close this out.
