### ISSUE TITLE
Writing to the locked network drive

### ISSUE THREAD

**Issue by aly-fly** [desktop/desktop#18222]
### The problem

GitHub Desktop app tries to write onto the Z: drive which is shared read-only network mapped drive. If I disconnect that drive, it works fine. Why not write temporary stuff and other settings into the system folder together with other settings?

### Release version

3.3.9 (x64)

### Operating system

Win 10

### Steps to reproduce the behavior

1. Create a temporary drive (USB flash drive, network drive, etc)
2. Set permissions of the complete drive to read-only
3. Open GitHub app. Error appears. _warning: error running C:\Users\yyyy\AppData\Local\GitHubDesktop\app-3.3.9\resources\app\git\mingw64\bin\git.exe 'config' '--includes' '--global' '--replace-all' 'filter.lfs.clean' 'git-lfs clean -- %f': 'error: could not lock config file Z://.gitconfig: Permission denied' 'exit status 255'
Run `git lfs install --force` to reset Git configuration._
4. or in the app go to File - Options - Save. _error: could not lock config file Z://.gitconfig: Permission denied_

**Comment by steveward** [comment]
@aly-fly thanks for the report. It looks like GitHub Desktop is looking for your global .gitconfig file there. Have you modified anything on your system (like HOMEDRIVE/HOMEPATH) to point to that drive? This can often be the case on corporate networks.

**Comment by aly-fly** [comment]
You are right the Cmd and Set commands return:
```
HOMEDRIVE=Z:
HOMEPATH=\
```
Looks like this is managed by our company policy.. However I am able to change these variables. Looks like it would be working patch to reassign these before running git :)

**Comment by steveward** [comment]
Glad to hear we were able to track that down! I'm going to close this out.
