### ISSUE TITLE
%ProgramData%\Microsoft\Windows\UUS\State\_active.uusver is suddenly showing up as change in my repo

### ISSUE THREAD

**Issue by nerminba** [desktop/desktop#18223]
### The problem

This must be a bug, this just started showing up and it never happened to me before using Github for many years. I can discard it but it comes up again, I do not want to be adding this to gitignore since it doesnt make sense, my app is not in the same directory or on the same drive.

Check the attached screenshot, its weird bug!

### Release version

3.3.9

### Operating system

Win 11

### Steps to reproduce the behavior

No clue how to get this reproduced, I guess this is complicated issue, it just started showing up. I only remember running npx react-devtools in the terminal inside Vs Code in the folder of my application few minutes before I noticed this bug I'm reporting. But this coudnlt be the cause.

### Screenshots

![image](https://github.com/desktop/desktop/assets/443080/71eeb919-8d20-48b5-a30b-90693118c458)

**Comment by tanmaysarin** [comment]
facing this issue as well, any suggested resolutons?

**Comment by nerminba** [comment]
Well after I faced this I inspected my app folder and found that the folder in sceenshot was actually added there, I'm 95% sure it's react-native debug tools that added it, so I decided to leave it there and added it to my .gitignore. Try that...
/%ProgramData%/
![image](https://github.com/desktop/desktop/assets/443080/e073a716-efb8-4ed7-b030-7cc1f0570e98)

**Comment by nerminba** [comment]
If gitignore doesn't work directly, it's possible that the directory has already been added to the Git index. The .gitignore file only prevents untracked files from being added to the index; it does not affect files that have already been tracked by Git. If you have any changes commit them, except this folder and then use the git rm --cached command to remove the files from the index while keeping them on your disk: git rm -r --cached "%ProgramData%". Now .gitignore will take effect and you should not see that folder popup anymore.

**Comment by hugs7** [comment]
I think this might be an Expo specific issue, not a Git one. @nikocraft, it looks like you were developing an Expo app as am I when I see this issue. Not an issue for me on other repos.

It appears somewhere the environment variable is not being expanded, though again I don't think this is a git issue.

**Comment by nerminba** [comment]
You are right, it was non-issue. I forgot how but I solved it :)

**Comment by hugs7** [comment]
You reckon it's worth opening an issue with Expo CLI? I agree it's pretty minor but nonetheless it is clearly a bug. It's also inconsistent for me - on my PC the folder doesn't appear, but on my laptop it does whenever I start expo.

If you remember how to solve it, I'd appreciate if you could post.

**Comment by ImBard** [comment]
I'm using expo when i open the devTools debug it's added to project.
