### ISSUE TITLE
The top warning in diff(right) panel will lead to not showing bottom lines

### ISSUE THREAD

**Issue by horans** [desktop/desktop#18237]
### The problem

If we have a warning showing on the top of the diff panel, it seems to "occupy" a certain height of the container, and the last lines at the bottom not showing properly.

> This diff contains a change in line endings from 'LF' to 'CRLF'

### Release version

3.3.9

### Operating system

Window 11

### Steps to reproduce the behavior

1. Go to "changes".
2. Switch to a file with a top warning.
3. Go to the diff/right panel, and scroll to the bottom.

### Screenshots

correct display without warning: 
![image](https://github.com/desktop/desktop/assets/12060804/c7c6fb80-06e0-48ac-ab20-0e5c399de91b)

wrong display with a top warning:
![image](https://github.com/desktop/desktop/assets/12060804/91eb5a3e-c9d0-49d2-afe1-c4894f44a3bf)

### Additional context

A sample of top warning: https://github.com/desktop/desktop/issues/18225

**Comment by sergiou87** [comment]
@horans thanks for your report! I've fixed this issue in #18239
