### ISSUE TITLE
Can bundled Git binary be used in place of system Git (as Apple Git upgrade)?

### ISSUE THREAD

**Issue by MagnusOxlund** [desktop/desktop#18234]
The [installation chapter](https://github.com/git-guides/install-git#install-git) of GitHub's official Git Guide mentions GitHub Desktop as a way to install Git on macOS:

> Install Git Using GitHub Desktop
> 
> Installing GitHub Desktop will also install the latest version of Git if you don't already have it. With GitHub Desktop, you get a command line version of Git with a robust GUI. Regardless of if you have Git installed or not, GitHub Desktop offers a simple collaboration tool for Git.

However, after installing GitHub Desktop, `which git` still points to the default system installation at `/usr/bin/git`, and any mention of command-line Git is notably absent throughout the app. Although there is indeed a Git binary inside the application package at `GitHub Desktop.app/Contents/Resources/app/git/bin/git`, I don't get the impression the bundled Git version is actually intended to be used on the command line, in spite of the language used in the guide. 

I'm also having trouble cloning using the binary. Git is complaining about a missing templates directory:

```
warning: templates not found in //share/git-core/templates
```

Is there a straightforward way to use the bundled version of Git as a system-wide replacement for Apple Git?

Related issue: https://github.com/github/training-kit/issues/920

**Comment by MagnusOxlund** [comment]
Related issue: https://github.com/github/training-kit/issues/920

**Comment by steveward** [comment]
Thanks for the issue @MagnusOxlund. See [this response](https://github.com/desktop/desktop/issues/15160#issuecomment-1225386551) for an explanation about why we don't recommend trying to use GitHub Desktop's bundled Git. 

I'll work on getting that guide updated, as it is outdated and was created for the previous version of GitHub Desktop that was closed-source.

**Comment by MagnusOxlund** [comment]
Thank you, @steveward. That comment explains a lot. I appreciate your looking into updating the guide. Thanks for the help.

**Comment by MagnusOxlund** [comment]
Looks like the [macOS section](https://github.com/git-guides/install-git#install-git-on-mac) of the Git Guide installation chapter has been updated:


> Install Git on Mac
> 
> Most versions of MacOS will already have Git installed, and you can activate it through the terminal with git version. However, if you don't have Git installed for whatever reason, you can install the latest version of Git using one of several popular methods as listed below:
> 
> Install Git From an Installer
> 
> Navigate to the latest [macOS Git Installer](https://sourceforge.net/projects/git-osx-installer/files/git-2.23.0-intel-universal-mavericks.dmg/download?use_mirror=autoselect) and download the latest version.
> Once the installer has started, follow the instructions as provided until the installation is complete.
> Open the command prompt "terminal" and type git version to verify Git was installed.
> Note: [git-scm](https://git-scm.com/download/mac) is a popular and recommended resource for downloading Git on a Mac. The advantage of downloading Git from git-scm is that your download automatically starts with the latest version of Git. The download source is the same [macOS Git Installer](https://sourceforge.net/projects/git-osx-installer/files/git-2.23.0-intel-universal-mavericks.dmg/download?use_mirror=autoselect) as referenced in the steps above.
> 
> Install Git from Homebrew
> 
> [Homebrew](https://brew.sh/) is a popular package manager for macOS. If you already have Homwbrew installed, you can follow the below steps to install Git:
> 
> Open up a terminal window and install Git using the following command: brew install git.
> Once the command output has completed, you can verify the installation by typing: git version.


Thank you once again for the help, @steveward.
