### ISSUE TITLE
GitHub Desktop ignore global .gitignore

### ISSUE THREAD

**Issue by Kresilas** [desktop/desktop#18240]
### The problem

in https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files?platform=mac it is mentioned:
"[Configuring ignored files for all repositories on your computer](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files?platform=mac#configuring-ignored-files-for-all-repositories-on-your-computer)

You can tell Git to always ignore certain files or directories when you make a commit in any Git repository on your computer. For example, you could use this feature to ignore any temporary backup files that your text editor creates.

To always ignore a certain file or directory, add it to a file named ignore that's located inside the directory ~/.config/git. By default, Git will ignore any files and directories that are listed in the global configuration file ~/.config/git/ignore. If the git directory and ignore file don't exist yet, you may need to create them."

But in fact it is not working for GitHub Desktop Version 3.3.8 (x64) on Mac mini (fin 2014) with macOS 12.7.3 (21H1015).

After losing a lot of time, I had to add local .gitinore;

### Release version

3.3.8

### Operating system

macOS 12.7.3 (21H1015)

**Comment by steveward** [comment]
Thanks for the report @Kresilas. i just tested this out on macOS and GitHub Desktop did successfully ignore files that were added to the global ignore file. Is it possible some of the files had been previously committed in your repository?

**Comment by badjano** [comment]
I'm on windows, and I can't make github desktop ignore stuff on my ~\.gitignore_global
