### ISSUE TITLE
"Semantic check all button" does not always work

### ISSUE THREAD

**Issue by aybe** [desktop/desktop#18248]
### The problem

Looks like it's #18201.

As you can see, it works for the group of 5 lines, but not for the group of 2 lines:

https://github.com/desktop/desktop/assets/1537591/2bc804b2-1908-4392-bb6d-98d0275cda8f

### Release version

3.3.10-beta1

### Operating system

Windows 11

### Log files

[2024-03-04.desktop.beta.log](https://github.com/desktop/desktop/files/14478747/2024-03-04.desktop.beta.log)

**Comment by tidy-dev** [comment]
@aybe Thank you for the report. This will be resolved in https://github.com/desktop/desktop/pull/18232 and shipped in the a future beta. We went ahead and shipped to beta knowing of a few edge cases to get beta testing underway.

**Comment by aybe** [comment]
Thank you :)
