### ISSUE TITLE
Copying pasting broken format

### ISSUE THREAD

**Issue by rthom91** [desktop/desktop#18249]
### The problem

Copying multiple lines in Split mode results in broken format when pasted into code editor.

### Release version

3.3.9

### Operating system

Windows 10

### Screenshots

![code1](https://github.com/desktop/desktop/assets/47700786/d52deeac-492e-4247-8ccd-3020857cc228)
![code2](https://github.com/desktop/desktop/assets/47700786/e531f6ed-63cb-44c6-8ac7-915ad1badb7c)

**Comment by rthom91** [comment]
Used to work normally until a recent Desktop update.

**Comment by sergiou87** [comment]
@rthom91 could you try the latest beta from https://desktop.github.com/beta and see if it works fine there?

**Comment by rthom91** [comment]
Just updated to 3.3.10 release. Still happens.

**Comment by sergiou87** [comment]
@rthom91 yes, 3.3.10 is the same as 3.3.9 with small fixes. However, the latest beta from https://desktop.github.com/beta has significant differences around how diffs are built and rendered.

Please, give the latest beta a try and let us know if it fixes the issue.

**Comment by rthom91** [comment]
Still exists on beta.

**Comment by rthom91** [comment]
I reverted to 3.3.8 and it works normally again.

**Comment by sergiou87** [comment]
> I reverted to 3.3.8 and it works normally again.

Thank you, that info is very valuable. We will investigate the issue.

**Comment by tidy-dev** [comment]
@rthom91 This should be fixed in 3.3.11. Thank you again for reporting the issue.

**Comment by RemyMalaya** [comment]
> ### The problem
> 
> Copying multiple lines in Split mode results in broken format when pasted into code editor.
> 
> ### Release version
> 
> 3.3.9
> 
> ### Operating system
> 
> Windows 10
> 
> ### Steps to reproduce the behavior
> 
> _No response_
> 
> ### Log files
> 
> _No response_
> 
> ### Screenshots
> 
> ![code1](https://github.com/desktop/desktop/assets/47700786/d52deeac-492e-4247-8ccd-3020857cc228)
> 
> ![code2](https://github.com/desktop/desktop/assets/47700786/e531f6ed-63cb-44c6-8ac7-915ad1badb7c)
> 
> 
> 
> ### Additional context
> 
> _No response_
