### ISSUE TITLE
Persistent path error for local repos

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1824]
When typing a local path in the `Add a local repository` dialogue, there a multiple `Uncaught (in promise) Error: Unable to find path to repository on disk` errors in the console until Desktop recognizes the path as "correct".

Possible to halt the errors until the user actually submits the desired path?

Reproduce:
- Add a new local repo and type jibberish in the path field

v0.5.8, OSX 10.11.5

<img width="1129" alt="screen shot 2017-05-30 at 11 29 36 am" src="https://cloud.githubusercontent.com/assets/14828183/26591522/ed079f44-452b-11e7-864d-a200de8c98ee.png">

**Comment by joshaber** [comment]
Are those errors presented to the user? Or just logged in the console?

**Comment by tierninho** [comment]
Just logged in the console. Ok if it's clogged up with the same thing repeating?

**Comment by joshaber** [comment]
It's less than ideal, just trying to get a sense for the scope of the problem.

**Comment by joshaber** [comment]
Closing since it's not user facing.
