### ISSUE TITLE
Githup Desktop working slowly

### ISSUE THREAD

**Issue by CheiHong** [desktop/desktop#18247]
### The problem

The Github Desktop working slowly and sometimes no response.

### Release version

Version 3.3.9 (x64)

### Operating system

Windows 10 

### Steps to reproduce the behavior

1. Select a repositary.
2. Click the History, it will take very long time to load the history and seems whole desktop no response .
3. Click the commit in history, it also take very long time to show the contain.

### Log files

[2024-03-04.desktop.production.log](https://github.com/desktop/desktop/files/14477264/2024-03-04.desktop.production.log)

### Screenshots

<img width="668" alt="github_slow" src="https://github.com/desktop/desktop/assets/143679222/53ca9cfd-89cf-4187-b320-98886e67ef48">

**Comment by steveward** [comment]
Thanks for the report @CheiHong. I do see some slow operations in the log file. Are you running any antivirus/security software on this machine that could be causing this? That's the most common cause of these performance issues that we've seen.

**Comment by CheiHong** [comment]
Yes, my system installed antivirus software by company. 
Anyway, I will keep monitor this if it alway happen with antivirus sofware running.
thank you.

**Comment by DongJu-Na** [comment]
Is there any way to use github desktop with antivirus?
