### ISSUE TITLE
issue cloning repository

### ISSUE THREAD

**Issue by iamtariqsidd** [desktop/desktop#18243]
Cloning into 'D:\laragon\www\eager2travel'...
remote: Enumerating objects: 2709, done.        
error: RPC failed; curl 56 Failure when receiving data from the peer
error: 3481 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

my internet is working well but I'm still getting this issue

**Comment by steveward** [comment]
Thanks for the issue @iamtariqsidd. Are you behind a proxy server that could be interfering with your connection?

Unfortunately there isn't much from our end that we can do regarding network issues. If continue to have issues you could try cloning the repository using SSH. See [this guide](https://docs.github.com/en/authentication/connecting-to-github-with-ssh) for information about setting it up.

**Comment by Noman12n** [comment]
#18243.github/CONTRIBUTING.md### 

> [`_****_`](url
[Uploading 2024-cio-agenda-ebook.pdf…]()
)

**Comment by letanloc1998** [comment]
I have the same issue, does GitHub down?
