### ISSUE TITLE
All branches not showing on dropdown

### ISSUE THREAD

**Issue by aaronjwhipple87** [desktop/desktop#18242]
When pressing the "branches" button it doesn't show all branches

**Comment by steveward** [comment]
Thanks for the issue @aaronjwhipple87. Can you share some more details about this? It's difficult to assist without any further information. If you think there are missing branches it would be helpful if you could run `git branch -a` from the command line, as that will list the local and remote repositories. We can then see if that differentiates from what GitHub Desktop is showing.

**Comment by aaronjwhipple87** [comment]
It was related to the issues from this morning and since has been resolved.Aaron J WhippleOn Mar 1, 2024, at 12:58 PM, Steve Ward ***@***.***> wrote:﻿
Thanks for the issue @aaronjwhipple87. Can you share some more details about this? It's difficult to assist without any further information. If you think there are missing branches it would be helpful if you could run git branch -a from the command line, as that will list the local and remote repositories. We can then see if that differentiates from what GitHub Desktop is showing.

**Comment by Bethany91live** [comment]
Yes agree to have it all done and sent out

**Comment by JCs3lma** [comment]
Is this resolved??

On my end it shows no search bar to it. It was working yesterday.

![image](https://github.com/desktop/desktop/assets/88816788/d2a3750a-6de8-4c14-866c-1fe9e33260ef)

**Comment by steveward** [comment]
@JCs3lma that screenshot is from GitHub the website, this issue tracker is for GitHub Desktop.
