### ISSUE TITLE
Open all selected files when clicking "Open with ..." with multiple files selected

### ISSUE THREAD

**Issue by mike-mike-mike-mike-mike** [desktop/desktop#18254]
### The feature request

It's convenient to view a change, right-click the file and open it in my editor. Sometimes, I'd like to open multiple or all changed files shown in GH desktop, but when I select multiple and click "Open in ..." it only opens the one I right-clicked on. It would be nice if it opened all selected files instead.

### Proposed solution

It would be especially useful when you are just opening your IDE and don't have any files open. Then you could be right back into your change set with one command, rather than having to search and open all the files yourself or right-clicking to open them one-by-one in GH desktop.

### Additional context

![image](https://github.com/desktop/desktop/assets/75824353/c8b4fca5-7733-46b3-b225-59fb20100137)

**Comment by steveward** [comment]
Thanks for the feedback @mike-mike-mike-mike-mike! I'm going to group this into https://github.com/desktop/desktop/issues/16262 where we are tracking this.

**Comment by mike-mike-mike-mike-mike** [comment]
@steveward thank you, sorry I did not see that one. I also re-discovered that you can double click files to open them, which is much faster than using the right click menu 🎉
