### ISSUE TITLE
Reverting a commit should signoff automatically

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [desktop/desktop#18255]
### The feature request

For reasons too sad and complicated to explain, I contribute to a project that uses DCO signoffs.  I add all these DCO signoffs to every single one of my commits.  Recently I had reason to revert a commit.  GitHub Desktop reverted the commit, but without any interface asking me to manually sign off, and the reverted commits failed the DCO test.  The repo I was working in forbade the recommended `git push --force ...` action.  I ended up manually collecting my changes, blowing away the branch, abandoning my Pull Request, then creating a new branch and pull request.

### Proposed solution

Reverting a commit creates no copyrightable or claimable intellectual property, so there should logically be no need to sign off on a commit that's reverted.  But if there are any signoffs in the commit being reverted, they should be mentioned in the reversion, to preserve the arrow of time (and making the commit a truly invertible operation).

### Additional context

It would be great to have a setting that allows the user to stipulate a signoff message to apply to every commit, and to have that signoff applied to any commit reversion.  As it is, the DCO process makes using the GitHub desktop app a miserable experience, error prone, and often a large time-suck when DCO signoffs are missed.

**Comment by sergiou87** [comment]
Hello @MichaelTiemannOSC 👋 

Just curious, how do you add that DCO signoff to the commit from GitHub Desktop when you make a commit? Is that something you do manually?

**Comment by MichaelTiemannOSC** [comment]
Fully manually.  I paste this text into my commits:

```
Signed-off-by: Michael Tiemann <72577720+MichaelTiemannOSC@users.noreply.github.com>
```

**Comment by sergiou87** [comment]
Thanks for the quick response. If you add that manually when the commit is made, I can't see how it could do the same automatically when it's reverted.

May I suggest to amend the commit right after reverting it?
1. Revert commit
2. Amend revert commit (from the History view, right click on the revert commit and then select amend)
3. Paste that text to the commit description.

I think that should do what you're looking for 🤞
