### ISSUE TITLE
Cant find file

### ISSUE THREAD

**Issue by KemuntoSereti** [desktop/desktop#18263]
### The problem

I was trying to add a new repository, after moving the folder to a new location. I removed it and tried to add it anew. Then I started getting the message, can't find"file". I waited and tried a couple of times but still not able to do so.

### Release version

3.3.10(x64)

### Operating system

Windows 11 Pro

### Steps to reproduce the behavior

 Go to File
Click on Add Local Repository
Choose path, browse to the path of the repository
Click on the tab  "Add Repository"

### Log files

[2024-03-07.desktop.production.log](https://github.com/desktop/desktop/files/14523732/2024-03-07.desktop.production.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/88021643/d8607c1f-bbcb-49ea-a3d9-5a1a36de1b67)

**Comment by steveward** [comment]
Thanks for the issue @KemuntoSereti. I'm not seeing any errors related to this specific repository in the log file. Can you click `Remove`, and then try dragging-and-dropping the repository back into GitHub Desktop to see if that gets things working?
