### ISSUE TITLE
Show actual dates in history screen instead of 29 days ago, or a month ago.

### ISSUE THREAD

**Issue by thewhistler1** [desktop/desktop#18273]
### The feature request

When I'm looking through the history the dates are written as 29 days ago, a month ago instead of an actual date. Which would be fine if it was under three days or so. But the entire list is that way. It would actually be much easier to find issues on specific dates if it just showed the date instead of 2 months ago. That is very vague and you don't know what the actual day was that it was updated.

### Proposed solution

Show actual date for anything over 3 days ago instead of showing 29 days ago, or a month ago.

### Additional context

Thanks.

**Comment by steveward** [comment]
Thanks for the issue @thewhistler1, I'm going to add this to https://github.com/desktop/desktop/issues/14611 where we are collecting feedback about this. For reference you can hover over the relative date to see the absolute date.

**Comment by jottevanger** [comment]
I'd love this to happen too. Very glad to know about the hover feature, but it would be great to be able to scan the list of commits for the relevant date rather than hover. Who needs the relative date anyway?
