### ISSUE TITLE
Can't Pull or clone this error

### ISSUE THREAD

**Issue by DorobantuRares** [desktop/desktop#18271]
I am encountering the following error/s when trying to clone my project

Cloning into 'D:\D\DodgeTheEdges'...
remote: Enumerating objects: 69160, done.        
remote: Counting objects: 100% (6722/6722), done.        
remote: Compressing objects: 100% (3219/3219), done.        
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 7705 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

Please help me

**Comment by sergiou87** [comment]
Hey @TheNuclearChicken , this appears to be a problem with the internet connectivity between you and GitHub.com (assuming it is GitHub.com you're connecting to). There's not much GitHub Desktop can do to solve this so I would suggest following the steps in the [Troubleshooting connectivity problems](https://docs.github.com/en/get-started/using-github/troubleshooting-connectivity-problems) guide.

You can use the [GitHub Debug](https://github-debug.com/) tool to test your connectivity to GitHub.com and, if necessary, submit a support request to our support team.

**Comment by DorobantuRares** [comment]
Thanks, I did contact my provider and this does seem to be the case!
