### ISSUE TITLE
Release notes for GitHub desktop are a bit confusing

### ISSUE THREAD

**Issue by CaioteMazzA** [desktop/desktop#18275]
### The feature request

When I check for GitHub desktop's release notes, I get confused because the way they're written is specifying what is the software behaviour after the bugfix. However, there's a **FIXED** tag beside it, so it feels like it's saying that the **new** behavior was fixed and is no longer present in the new version. This forces me to open the issue and go through all of its description and sometimes its history.

As an example:
![image](https://github.com/desktop/desktop/assets/162727002/1d377e19-4589-4542-95c6-b5533229a563)

In that example, it feels like what was fixed is **"new lines not being added when pasted"**, but the issue is the opposite. What was fixed is that it was adding new lines before and after fixed, it doesn't.

### Proposed solution

Writing the issue that was fixed (the bug) instead of the behavior after fix took place.

### Additional context

I'm not really sure if I chose the correct issue category.

**Comment by tidy-dev** [comment]
👋 @CaioteMazzA Thank you for the feedback. We have an [established process for writing release notes](https://github.com/desktop/desktop/blob/development/docs/process/writing-release-notes.md#fixed). I can see definitely see your point about the "Fixed" tag. However, release notes are meant to reflect the current behavior of the app.  The type tags of "fixed", "improved", "added", "new", or "deleted" are more to give context about how the change came about -- are we fixing a problem or adding a feature. 

Of course, that said, it is engineers making these notes and I know personally my release notes could probably benefit from more clarity. For example, upon further reflection, it may have been helpful to mention in the above line that the new lines added were "erroneous" and maybe better stated as "blank or screen reader only content". Thank you for calling it out and I will strive for clearer verbiage in the future.
