### ISSUE TITLE
unable to connect with local machine

### ISSUE THREAD

**Issue by PunamDeore** [desktop/desktop#18287]
### The problem

I am not able to connect to local machine and do operations

### Release version

Version 3.3.11 (x64)

### Operating system

windows 10

**Comment by steveward** [comment]
Thanks for the report @PunamDeore. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by PunamDeore** [comment]
D:\Fullstack Development with AI\Assignment\12-node-server-information>git add .
warning: in the working copy of 'node_modules/.package-lock.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'node_modules/http/README.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'node_modules/http/package.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'package-lock.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'package.json', LF will be replaced by CRLF the next time Git touches it

D:\Fullstack Development with AI\Assignment\12-node-server-information>git commit -m "first commit"
[master (root-commit) 3fe342c] first commit
 6 files changed, 113 insertions(+)
 create mode 100644 node_modules/.package-lock.json
 create mode 100644 node_modules/http/README.md
 create mode 100644 node_modules/http/package.json
 create mode 100644 package-lock.json
 create mode 100644 package.json
 create mode 100644 server.js

D:\Fullstack Development with AI\Assignment\12-node-server-information>git branch -M main

D:\Fullstack Development with AI\Assignment\12-node-server-information>git remote add origin https://github.com/PunamDeore/testcode.git

D:\Fullstack Development with AI\Assignment\12-node-server-information>git push -u origin main
fatal: unable to access 'https://github.com/PunamDeore/testcode.git/': CONNECT tunnel failed, response 404

D:\Fullstack Development with AI\Assignment\12-node-server-information>                                                 
[2024-03-11.desktop.production.log](https://github.com/desktop/desktop/files/14567109/2024-03-11.desktop.production.log)
[2024-03-12.desktop.production.log](https://github.com/desktop/desktop/files/14567110/2024-03-12.desktop.production.log)

**Comment by steveward** [comment]
Thanks for sharing that output. The `CONNECT tunnel failed` error indicates a network issue. Are you behind a proxy or firewall that could be interfering with your connection?
