### ISSUE TITLE
i have problem to open GitHub desktop app its showing this error in EventLog

### ISSUE THREAD

**Issue by AyushBhagat151105** [desktop/desktop#18286]
hii coders i have problem to open GitHub desktop app its showing this error in EventLog

45187 Application Error Faulting application name: GitHubDesktop.exe, version: 3.3.8.0, time stamp: 0x651560bd...

Please help me to Solve this problem

_Originally posted by @AyushBhagat151105 in https://github.com/desktop/desktop/issues/3757#issuecomment-1987273638_

**Comment by steveward** [comment]
@AyushBhagat151105 thanks for the report. Has GitHub Desktop previously worked on your machine? Are you running any antivirus or security software that could be interfering with the application launching?

You could also try a fresh reinstall -- here's how to do that:

1. Open File Explorer
2. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
3. Go to `%AppData%` and delete the `GitHub Desktop` directory
4. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that helps at all.

**Comment by AyushBhagat151105** [comment]
@steveward bro i already tried everything and ever way of i delete Github Desktop reinstall it but it's not working

**Comment by badder9631** [comment]
jimmyyyyyyyyyyyyyyy

**Comment by steveward** [comment]
@AyushBhagat151105 can you confirm whether or not you are running any antivirus or other security software on this machine? Has GitHub Desktop previously worked on this machine?

**Comment by AyushBhagat151105** [comment]
@steveward i am using windows defender 
![Screenshot 2024-03-12 211108](https://github.com/desktop/desktop/assets/103896902/5f70e5d5-a898-4001-b7be-b37108e8ddbf)


this is error seen in my defender's Protection history

**Comment by steveward** [comment]
I'm not seeing anything there related to GitHub Desktop. Can you see if there is a log file here?

`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`

If no log file is being generated there you should be able to find one in the `SquirrelTemp` directory:

`%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

Please send that over as an attachment.

**Comment by AyushBhagat151105** [comment]
@steveward  i find the file you want 
[SquirrelSetup.log](https://github.com/desktop/desktop/files/14600688/SquirrelSetup.log)
