### ISSUE TITLE
Github LFS

### ISSUE THREAD

**Issue by Mashimaro7** [desktop/desktop#18298]
### The feature request

Make Github LFS trackable via Github Desktop. I don't see why we can't have a right click file > add to LFS in here? Took me forever  to figure out how to do it via console, and i have a non-tech savy client who can't figure it out.

### Proposed solution

Add an add to LFS on right-click

**Comment by steveward** [comment]
Thanks for the feedback @Mashimaro7. I'm going to add this to https://github.com/desktop/desktop/issues/6055 where we are tracking this request.
