### ISSUE TITLE
Support custom editor on a per-repo basis (JetBrains support)

### ISSUE THREAD

**Issue by bick** [desktop/desktop#18293]
### The feature request

We use multiple JetBrains products at our company, and it would be nice if we could set which code editor we use on a per repo basis. Some of my projects are C# so they would use Rider, others are JavaScript so they'd use WebStorm, and others are Python so they'd use PyCharm.

### Proposed solution

Add an option that allows you to set which text editor that a specific repo would use to open the project instead of a single global option.

**Comment by steveward** [comment]
Thanks for the issue @bick! We're tracking this feature in https://github.com/desktop/desktop/issues/12195, so I'm going to cross-reference this issue there and close this out.
