### ISSUE TITLE
error: failed to push some refs to 'https://github.com/NinjaNezumiProductions/Tora.git'

### ISSUE THREAD

**Issue by NinjaNezumi** [desktop/desktop#18295]
### The problem

error: failed to push some refs to 'https://github.com/NinjaNezumiProductions/Tora.git'

### Release version

latest

### Operating system

windows 11

### Steps to reproduce the behavior

click push

### Log files

error: failed to push some refs to 'https://github.com/NinjaNezumiProductions/Tora.git'

### Screenshots

error: failed to push some refs to 'https://github.com/NinjaNezumiProductions/Tora.git'

### Additional context

error: failed to push some refs to 'https://github.com/NinjaNezumiProductions/Tora.git'

**Comment by steveward** [comment]
Thanks for the report @NinjaNezumi. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by NinjaNezumi** [comment]
Done.


    On Thursday, March 14, 2024 at 07:24:01 AM MDT, Steve Ward ***@***.***> wrote:  
 
 


Thanks for the report @NinjaNezumi. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by steveward** [comment]
@NinjaNezumi unfortunately log files don't make it through email replies -- you will need to upload it directly in this issue.

**Comment by NinjaNezumi** [comment]
I'm sorry about that!
[2024-03-14.desktop.production.log](https://github.com/desktop/desktop/files/14622368/2024-03-14.desktop.production.log)

**Comment by NinjaNezumi** [comment]
It's been a week, are you guys unable to help me?

**Comment by steveward** [comment]
@NinjaNezumi can you try disabling mandatory ASLR to see if that resolves this issue?

See [this guide](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#enable-mandatory-aslr-triggers-cygheap-errors).

**Comment by NinjaNezumi** [comment]
Ok I will try tonight

**Comment by NinjaNezumi** [comment]
I'm sorry I have no idea how to do this.

    On Wednesday, March 27, 2024 at 10:02:48 AM MDT, Steve Ward ***@***.***> wrote:  
 
 


@NinjaNezumi can you try disabling mandatory ASLR to see if that resolves this issue?

See this guide.

**Comment by NinjaNezumi** [comment]
IT WORKED!  Thank you so much!  But - the link you gave me was a bad link.  my friend had to give me this link to show me how to do it:

https://techcommunity.microsoft.com/t5/windows-security/turn-on-mandatory-aslr-in-windows-security/m-p/1186989?fbclid=IwAR1nSZPScadPmrG-GKT01CAC4I_87HOj00dpdT7sTccaL2U0nMWfEQiZI54

please adjust your information.

**Comment by steveward** [comment]
Hmm, the link works for me. I'm glad to hear things are working now!
