### ISSUE TITLE
Search Changes Function 

### ISSUE THREAD

**Issue by Mashimaro7** [desktop/desktop#18299]
### The feature request

Please add a way to search through your changes by typing the name. I've had many a time where i'm looking for one change in 10k+(after installing some large package or something) and i have to scroll through them to find that one change manually...

### Proposed solution

Just a basic search bar that lets you type a name and it narrows the changes down based on what you type.

**Comment by steveward** [comment]
Thanks for the feedback @Mashimaro7. This is being tracked in https://github.com/desktop/desktop/issues/6407, so I'm going to reference this issue there.

**Comment by Jaimi** [comment]
We've been hoping for this since 2018.
