### ISSUE TITLE
DOESNT WORK

### ISSUE THREAD

**Issue by choclateisgoodcandy** [desktop/desktop#18301]
### The problem

DOESNT WORK ON CHROMEBOOKS OR ANY TYPE OF LAPTOP EVEN THOUGH IT STATES IT DOES

### Release version

9.0.7

### Operating system

h trh3bjn egfcv

### Steps to reproduce the behavior

htcreafgbvwnytherbthv64yj6uenc

### Log files

DOESNT WORK ON CHROMEBOOKS OR ANY TYPE OF LAPTOP EVEN THOUGH IT STATES IT DOES

### Additional context

DOESNT WORK ON CHROMEBOOKS OR ANY TYPE OF LAPTOP EVEN THOUGH IT STATES IT DOES

**Comment by steveward** [comment]
@choclateisgoodcandy this issue tracker is for GitHub Desktop -- it sounds like you are looking for support for a different project so I'm going to close this out.
