### ISSUE TITLE
Github Desktop beta does not launch after auto update on macOS High Sierra

### ISSUE THREAD

**Issue by splorp** [desktop/desktop#18316]
### The problem

I had been previously running GitHub Desktop 3.3.9-beta2, which automatically updated to 3.3.12-beta2 this morning.

When relaunching the updated application, the following message appeared:

> “You can’t use this version of the application “GitHub Desktop” with this version of macOS.”

Reverting to the current stable release (3.3.11) solves the problem.

Apparently, one of the more recent beta versions changed the system requirements.

The application should ***not*** automatically update if the system requirements change beyond the current OS version.

### Release version

3.3.12-beta2

### Operating system

macOS High Sierra (10.13.6)

### Steps to reproduce the behavior

1. Launch application
2. Message dialog appears

**Comment by sergiou87** [comment]
Thank you for your report. It seems Electron v27 dropped support for macOS High Sierra and Mojave. We will disable auto-update in those cases.

**Comment by splorp** [comment]
Thanks for the information. This auto-update things has been an issue for a long time.

**Comment by sergiou87** [comment]
@splorp could you download the latest beta from https://desktop.github.com/beta ?

That one should work and show you a banner saying GitHub Desktop won't be updated because your operating system is no longer supported. Could you confirm, please? 🙏 

Thank you in advance 💖

**Comment by splorp** [comment]
@sergiou87 Confirmed. The banner displays in the main window, as well as the “About GitHub Desktop” dialog box.

The only other thing I noticed was that the [supported operating systems](https://docs.github.com/en/desktop/overview/supported-operating-systems-for-github-desktop) page linked from the banner and the dialog box still reports “macOS 10.13 or later” as being supported.

![image](https://github.com/desktop/desktop/assets/29835/4b5693e9-5762-47cc-bea0-1d35b9d0d4aa)

**Comment by sergiou87** [comment]
Thank you @splorp 🙏 

Yes, the documentation is still outdated, but I submitted a PR to our internal repo to fix that at the same time as I fixed this issue.

Thank you for all your help and patience!

**Comment by splorp** [comment]
You’re welcome.

**Comment by bsabiston** [comment]
I don't understand.  There is no way to disable the auto-update in the old high-sierra compatible version?  What good does it do to add it to a new version?  I just restored my old version via Time Machine.  How do I keep it from auto-updating?

**Comment by splorp** [comment]
As shown in the screenshot above, I’m running the 3.3.12-beta3 version of Desktop and auto-updating is disabled.

**Comment by sergiou87** [comment]
Version 3.3.13 is the latest one supported on macOS High Sierra and won't auto-update, here you have the download links:
- Intel: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.13-1b0804db/GitHubDesktop-x64.zip
- Apple Silicon: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.13-1b0804db/GitHubDesktop-arm64.zip

However, given recent vulnerabilities found around git and GitHub Desktop itself, I'd recommend you to upgrade macOS in order to support the newest version of GitHub Desktop, stay up-to-date, and be protected against those vulnerabilities 🙏
