### ISSUE TITLE
Expandable width for Current Branch name selection toolbar

### ISSUE THREAD

**Issue by mountainash** [desktop/desktop#18326]
### The feature request

It would be a nice feature ✨ if the "current branch" section in the toolbar could be increased in width.

There are already quite a few vertical panels that can be resized - but currently this *isn't* one 😿  

<img width="1178" alt="Screenshot 2024-03-19 at 20 24 34" src="https://github.com/desktop/desktop/assets/27637/e444756a-e3c3-4008-9381-b3b82c5f11a5">

### Proposed solution

By click-dragging/resizing the divider with the "Fetch" action/button.

**Comment by steveward** [comment]
Thanks for the issue @mountainash. This is being tracked in https://github.com/desktop/desktop/issues/4569 so I'm going to close this out.
