### ISSUE TITLE
PhpStorm not showing in Select External Editor in Windows

### ISSUE THREAD

**Issue by milan-sahana** [desktop/desktop#18338]
### The feature request

PhpStorm 2023.3.6 not showing in Select External Editor option, How can I add in manually?

### Proposed solution

Please provide a option so that I can add External editor by choosing the .exe file

**Comment by tidy-dev** [comment]
@milan-sahana Sorry you are having trouble seeing PHPStorm in the external editor option. PHPStorm should be supported unless you have installed it via JetBrains Toolbox. Is that how you installed it?
