### ISSUE TITLE
Useeer name

### ISSUE THREAD

**Issue by Victor0710032086** [desktop/desktop#18336]
Good day. I would like to delete or if possible change my user name. I inadvertantly used a user name with too much information. I have tried going to 'Accounts' but have not found anywhere I could delete this account. Please help.

Regards
Victor

'

**Comment by tidy-dev** [comment]
@Victor0710032086 Thank you for reaching out. However, this is the issue tracker for GitHub Desktop. For issues with GitHub.com, please search or open a discussion in the [GitHub Community Discussions](https://github.com/orgs/community/discussions). With a quick search, I found [this discussion post entitled "how to change my GitHub username?" ](https://github.com/orgs/community/discussions/101785) that looks like it may pertain your question.
