### ISSUE TITLE
PR:#18201 has not yet been released

### ISSUE THREAD

**Issue by yasuking0304** [desktop/desktop#18337]
### The problem

I noticed this while looking at the release notes for 3.3.12
It looks like the following features have been added.

Added semantic and keyboard accessible check all button for a groups of consecutive selectable rows in the diff - [#18201](https://github.com/desktop/desktop/issues/18201)

However, in 3.3.12 it has not yet been added and the Accessibility Tab is not displayed.
(In front of the screen)

It seems to work when I dev build it as a trial.
(Back of the screen)
![WS000018](https://github.com/desktop/desktop/assets/111163564/04c3185a-ffc2-49ae-9e33-0a2d60bfe557)

### Release version

3.3.12

### Operating system

Windows10, Mac OS Monterey

### Steps to reproduce the behavior

1. Open "GitHub Dektop"
2. [menu] > File > Options...

### cause
blocked in enableBetaFeatures
https://github.com/desktop/desktop/blob/879b2c634cf63e83bcb8d3fcded47ca22f9c6b75/app/src/lib/feature-flag.ts#L105

### How to fix it
now
```TypeScript
export const enableDiffCheckMarksAndLinkUnderlines = enableBetaFeatures
```
after
```TypeScript
export const enableDiffCheckMarksAndLinkUnderlines = () => true
```

I think it would be better to remove this enableLinkUnderlines() judgment as well.
https://github.com/desktop/desktop/blob/development/app/src/ui/preferences/preferences.tsx#L277-L282

**Comment by tidy-dev** [comment]
@yasuking0304 Thank you for reaching out! We did intentionally only ship the semantic check all with this ship. You can use the feature with the mouse as has been there for a few years, but now it is also keyboard accessible. We are planning the visual changes for a future release.
