### ISSUE TITLE
Authenticate failed

### ISSUE THREAD

**Issue by Srikanthreddya60** [desktop/desktop#18340]
While cloning the url it shows we are unable to authenticate with Github.com. please enter username and password to try again.
After entering the credentials still it shows same

**Comment by steveward** [comment]
Thanks for the report @Srikanthreddya60. Can you verify you are logged in by going to `File` > `Options` > `Accounts`?

If you continue to have issues it would be helpful if you could share the log file from GitHub Desktop. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
