### ISSUE TITLE
Calculating/Submitting grade for assignment

### ISSUE THREAD

**Issue by amethystmcmaster** [desktop/desktop#18353]
Hi, 

I have been trying to get an assignment to process the last two days. The assignment is due tonight. I checked to see if extensions needed to be updated, reset the assignment, and rebuilt the container with no success. This extremely frustrating as I am not sure who to reach out to or what the next steps are in general. I included a screenshot to show the latest result when trying to calculate the grade. 

![Screenshot 2024-03-24 103256](https://github.com/desktop/desktop/assets/158854595/8928a70d-2a7d-436a-9447-54b201d29530)

Thank you for your time.

**Comment by sergiou87** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
