### ISSUE TITLE
Not able to push the code to remote

### ISSUE THREAD

**Issue by praveensunatbooker** [desktop/desktop#18359]
### The problem

Whenever I tried to push my code to Remote, I get this error: **_The remote disconnected. Check your Internet connection and try again_**
<img width="353" alt="GitHub Desktop Issue" src="https://github.com/desktop/desktop/assets/164946899/ebf9cbe3-9c09-4b75-be9a-644ca889bf1b">

### Release version

 3.3.12 

### Operating system

Windows Server 2019

### Steps to reproduce the behavior

1. Enter Summary & Description, 
2. Then click on Commit to Master. 
3. Click on Push Origin

### Screenshots

<img width="353" alt="GitHub Desktop Issue" src="https://github.com/desktop/desktop/assets/164946899/046c9f01-511a-46de-95e7-ffb96d408705">

**Comment by steveward** [comment]
Thanks for the report @praveensunatbooker. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by praveensunatbooker** [comment]
Thanks for the reply.

Hereby I am attaching the latest log file from GitHub Desktop.

Also, we get similar error when we try to commit via GIT BASH

Failed to connect to localhost port 3000 after 1279 ms: Couldn't connect to server

FYI, we are using GOGS Git Flavour SCM for our project. We are able to access the repo directly via GOGS UI console & able to commit our changes (file-by-file, which is very tedious).

Please let me know if you need any other info.



Thanks & Regards,
Praveen Sundar

**Comment by steveward** [comment]
Are you behind a firewall or proxy server that could be interfering with your connection? Unfortunately there isn't anything we can do about that from our end.

You can go to [GitHub Debug](https://github-debug.com/) to test your connection to GitHub.

**Comment by praveensunatbooker** [comment]
Hi Steve,

Yes, we are behind a firewall.

These are the results from GitHub Debug tests:

fatal: unable to access 'https://github.com/github/debug-repo/': Failed to connect to github.com port 443 after 21099 ms: Couldn't connect to server
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Pinging github.com [140.82.121.3] with 32 bytes of data:
Reply from 140.82.121.3: bytes=32 time=24ms TTL=51
Reply from 140.82.121.3: bytes=32 time=24ms TTL=51
Reply from 140.82.121.3: bytes=32 time=24ms TTL=51
Reply from 140.82.121.3: bytes=32 time=24ms TTL=51
Reply from 140.82.121.3: bytes=32 time=24ms TTL=51
Reply from 140.82.121.3: bytes=32 time=24ms TTL=51
Reply from 140.82.121.3: bytes=32 time=23ms TTL=51
Reply from 140.82.121.3: bytes=32 time=24ms TTL=51
Reply from 140.82.121.3: bytes=32 time=23ms TTL=51
Reply from 140.82.121.3: bytes=32 time=25ms TTL=51

Ping statistics for 140.82.121.3:
    Packets: Sent = 10, Received = 10, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 23ms, Maximum = 25ms, Average = 23ms
Tracing route to github.com [140.82.121.4]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  172.18.200.254
  2     1 ms     1 ms     1 ms  194.73.98.130
  3     1 ms     1 ms     1 ms  217.33.95.237
  4     7 ms     7 ms     6 ms  86.189.33.180
  5     9 ms     9 ms     9 ms  core3-hu0-6-0-0.faraday.ukcore.bt.net [194.72.16.240]
  6     9 ms     9 ms     9 ms  166-49-209-132.gia.bt.net [166.49.209.132]
  7     *        *        *     Request timed out.
  8    11 ms    10 ms    10 ms  ldn-bb1-link.ip.twelve99.net [62.115.127.100]
  9    17 ms    17 ms    17 ms  prs-bb1-link.ip.twelve99.net [62.115.135.25]
10     *        *       26 ms  ffm-bb1-link.ip.twelve99.net [62.115.123.12]
11    25 ms     *        *     ffm-b11-link.ip.twelve99.net [62.115.124.117]
12    32 ms    24 ms    24 ms  github-ic-350972.ip.twelve99-cust.net [62.115.182.171]
13     *        *        *     Request timed out.
14     *        *        *     Request timed out.
15    24 ms    24 ms    24 ms  lb-140-82-121-4-fra.github.com [140.82.121.4]

Trace complete.

Please advice

Thanks & Regards,
Praveen Sundar

**Comment by steveward** [comment]
@praveensunatbooker it looks like you'll need to configure your firewall to allow git operations and GitHub Desktop to connect to GitHub. Unfortunately there isn't anything further we can do from our end -- you will need to reach out to your IT department to assist with that. You can find a list of IP addresses that need to be whitelisted here: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-githubs-ip-addresses

I hope that helps. I'm going to close this out. If you have further issues connecting to GitHub I would recommend reaching out directly to [GitHub Support](https://support.github.com/).
