### ISSUE TITLE
Message popup "You'll need a new app to open this ms-gamingoverlay link"

### ISSUE THREAD

**Issue by budiony** [desktop/desktop#18357]
### The problem

Since version 3.3.12 x64 on Windows 10, this message constantly pops up: "You'll need a new app to open this ms-gamingoverlay link". Diff display is "split" if this matters and nothing fancy in the settings of the app. The popup opens mostly when the app is in background. Very hard to take a screenshot, since the popup disappears on mouse out.

### Release version

3.3.12

### Operating system

Windows 10, build 19045

**Comment by tidy-dev** [comment]
👋 @budiony Thank you for reaching out. That error is not one that is produced by the GitHub Desktop app. However I did f[ind this reddit that seems to relate it to the Game Bar](https://www.reddit.com/r/Windows10/comments/8b59bo/youll_need_a_new_app_to_open_this_msgamingoverlay/). Could you try turning that off and see if it still persists?

**Comment by budiony** [comment]
Hi, disabling the sh*tty Windows Game Bar was first to try (also disabled the Windows game bar service). PC restarted, however, the popup comes from the GitHub app itself, since it appears on top of it (very hard to take a screenshot or show device manager's processes list). This is very weird situation.

**Comment by jacortinas** [comment]
@budiony Doing some googling it looks like there are other issues that could be happening, and it might even involve changing registry values. Is this issue still occurring?

**Comment by budiony** [comment]
Win registry editing was not performed (at least not manually). The problem disappeared after several reboots and windows disk cache cleanup (not sure this is the real reason but it's OK).
