### ISSUE TITLE
Feature request: Sync fork with GitHub Desktop

### ISSUE THREAD

**Issue by d-kleine** [desktop/desktop#18361]
### The feature request

I may have overlooked this, but is there any kind of feature that allows to sync the fork with GitHub Desktop? If have checked the issue tickets and did not find related to this topic.

In GitHub itself, [this can be done quite easily](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork). 
![GitHub sync a fork](https://docs.github.com/assets/cb-75616/mw-1440/images/help/repository/sync-fork-dropdown.webp)

### Proposed solution

As a feature, it would be great if you "fetch origin" a fork with GitHub Desktop, it would be great to display if there are updates in the original repo that can be synced with this fork just with a click on a button like "sync fork" here:
![GitHub Desktop](https://i0.wp.com/user-images.githubusercontent.com/75402236/235489783-3e4c8290-fd79-48da-b446-03c43e82697a.gif?ssl=1)

**Comment by steveward** [comment]
Thanks for the request @d-kleine. There isn't a `Sync fork` button like on github.com, but you can merge upstream branches into your local branches in GitHub Desktop a few ways.

- There is a menu item to update from upstream/main in the `Branch` menu list, or you can use the `CMD/CTRL+SHIFT+U` keyboard shortcut.
- If you go to `Branch` -> `Merge into current branch` you will see the `upstream/<branch>` branches listed, and you can select other branches to merge from as well. 

I'm going to close this out, but if you have any further questions let me know. I'll make a note to verify this is showcased in our docs as well.
