### ISSUE TITLE
Incorrect formatting of plot text when using Cview

### ISSUE THREAD

**Issue by SonomaticDominykasStaugaitis** [desktop/desktop#18369]
### The problem

When using the 'Display the C-scan and a distribution' or 'Display the C-scan and a histogram' tab in Cview, titles and legend labels that use the underscore character are displayed incorrectly. The character following the underscore gets displayed as a subscript. 

 'Display the C-scan and a distribution' tab

![image](https://github.com/desktop/desktop/assets/162311690/3e315374-1063-4585-8f88-4ee0881d0c7a)

'Display the C-scan and a histogram' tab 

![image](https://github.com/desktop/desktop/assets/162311690/58ab576e-6c0d-4a40-8fb7-f21ba4900b64)

### Release version

Version 3.3.10 (x64)

### Operating system

Windows 11 Enterprise

### Steps to reproduce the behavior

1. Load a file whose filename contains underscores 
2. Select the file name in the bottom right corner to make it visible
3. Go to either of the two distribution windows using the buttons at the top

**Comment by sergiou87** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
