### ISSUE TITLE
Allow making the changes/history list wider

### ISSUE THREAD

**Issue by Grinderofl** [desktop/desktop#1836]
### Description

Currently, the sidebar with list of files for Changes and messages for History is limited to 350px. While it's possible to see the full path of the file by clicking on it, if there's a lot of characters in the path, the list itself makes it really difficult.

### Version

**GitHub Desktop version:** 0.5.8

The operating system you are running on may also help with reproducing the
issue:

**OS version:** Win 10 Enterprise V 1511 Build 10586.916

### Steps to Reproduce

1. Open the application
2. Switch to a repository
3. Attempt to adjust the width of Changes/History

**Expected behaviour:** Able to expand the width to see all file names like Github Desktop (non-beta) did

**Actual behaviour:** Able to expand only up to 350px width

**Reproduces how often:** 100%

#### Additional Information

This is the feature (plus "Open in Visual Studio" to lesser extent) which deters me from using it at the moment. It's too hard to read compared to the previous version for individual file names. Row heights could be increased for that as well (or at least made configurable).

**Comment by shiftkey** [comment]
@Grinderofl we are already tracking this in #1588 - please add any additional feedback you have there. Thanks!
