### ISSUE TITLE
Untrusted Server ( A Certificate Issue )

### ISSUE THREAD

**Issue by TPR048** [desktop/desktop#18377]
### The problem

Github desktop is unable to verify the identity of the server, therefore getting untrusted server or certificate error. 

### Release version

Version 3.3.12 (x64)

### Operating system

Windows 10 Enterprise

### Screenshots

![image](https://github.com/desktop/desktop/assets/110598656/2fd05ba2-39bb-478b-9e53-b1e5b19ad5cb)

**Comment by jacortinas** [comment]
Hello, @TPR048 as far as I can tell the certificates for `github.com` and therefore `alive.github.com` are correct.

Is it possible you are behind a VPN or proxy? A system restart has solved this issue for some users in the past, I would also attempt that.

**Comment by TPR048** [comment]
Hi Jose,

Sorry, for delay in response.

I overlooked that email. Now I'm not getting trusted server issue therefore you can close the ticket from your end.

Sure I will reach out to you in case I face this issue again.




Best Regards,

Tej Prakash
Software Engineer
EDI/Integrations Platform
APMT EDI Capability
Mob:- +91 9582402440

***@***.***

Planned leaves : 24th to 26th and 29th to 30th April
National holidays : 9th and 11th April



Classification: Internal

**Comment by siacovinospita** [comment]
I just got the same error message.

**Comment by NikitaGamer64** [comment]
Does Zapret Discord Youtube have anything to do with this?

**Comment by justingolden21** [comment]
I understand when you don't have Internet access this might popup once or twice. But it popups up infinitely many times. The moment you close it, it pops up again. It makes Desktop ENTIRELY UNUSABLE without internet. Desktop used to be fine without internet. Imagine if the git terminal was unusable offline. It's kind of absurd that I can't use this and have to use command line just to change repos and branches and commit offline. I've tried about 30+ times and get untrusted server every time. Must've been some Desktop update that messed it up. I hope they fix it soon.

**Comment by nickpunt** [comment]
This happened to me just now.

<img width="733" height="470" alt="Image" src="https://github.com/user-attachments/assets/147dbda0-cce9-4ef2-bea8-4ff42763a458" />
<img width="638" height="373" alt="Image" src="https://github.com/user-attachments/assets/4409e813-2be5-450e-a8d0-0fd4ec9357e8" />
