### ISSUE TITLE
File added to git ignore but still appearing in commit

### ISSUE THREAD

**Issue by paccale** [desktop/desktop#18372]
### The problem

I added a file to git ignore but it still appears in commit summary via github desktop.

### Release version

3.3.12

### Operating system

Windows 10

### Screenshots

![bugjpg](https://github.com/desktop/desktop/assets/91796899/44e80551-0985-4eea-9d27-961ed0d6b3aa)

**Comment by Rexogamer** [comment]
not a Desktop issue but a (somewhat confusing!) part of how Git works. you'll need to delete the file, commit the deletion then restore it. the easiest way should be to move it outside the repository's folder, commit then put it back?

**Comment by jacortinas** [comment]
@paccale Was the above advice of deleting the file if necessary a solution?

**Comment by paccale** [comment]
Fixed, thank you very much!
