### ISSUE TITLE
Allow multiple stashes

### ISSUE THREAD

**Issue by DavidTheExplorer** [desktop/desktop#18380]
### The feature request

Allow more than 1 stash per repository, exactly like it's possible in Gitkraken. 

### Proposed solution

Super useful... this allows working on multiple stuff at the same time - without the need to commit stuff you don't want to.

**Comment by Mhs7mm** [comment]
اللهم صل على محمد وعلى ال محمد

**Comment by jacortinas** [comment]
Thank you for your suggestion, @DavidTheExplorer. I'll mark this issue as an enhancement for consideration in the future.

**Comment by tidy-dev** [comment]
Closing this in favor of this tracking issue https://github.com/desktop/desktop/issues/12699
