### ISSUE TITLE
login Issue

### ISSUE THREAD

**Issue by I-M-GHOST** [desktop/desktop#18386]
### The problem

I am unable to sign in my another Github account in Github desktop. I wanted to push my code with another account . but I can't sign in my another account.  

### Release version

Version 3.3.5 

### Operating system

windows 10

**Comment by steveward** [comment]
@I-M-GHOST thanks for the issue. At this time GitHub Desktop does not support multiple accounts, but this is on our radar and is being tracked in https://github.com/desktop/desktop/issues/3707.

You will need to log out of your existing account and then log in with the second account until that feature is implemented. Sorry that I don't have better news.

**Comment by I-M-GHOST** [comment]
thanks for your response. I hope it will be fixed soon.
