### ISSUE TITLE
Feature Request: Add a "Sync" Indicator

### ISSUE THREAD

**Issue by JosephTLyons** [desktop/desktop#1839]
### Description

Unless I entirely missed it in the original Desktop, I never saw an indicator to let us know our local repo was older than the remote repo and that we should sync.  Unless this feature is already implemented, it would be great to have it added.

### Version

**GitHub Desktop version:** [0.5.8]

**Comment by shiftkey** [comment]
@JosephTLyons we've done away with the Sync button (see ongoing discussions in #1565) in favour of a more contextual fetch/pull/push button.

This is what the top part of the repository looks like now when you have commits to pull into your branch:

<img width="719" src="https://cloud.githubusercontent.com/assets/359239/26630625/edfbbd74-45dd-11e7-8a64-138eb465d7e0.png">

Let me know if there's any other feedback you have around this feature.

**Comment by JosephTLyons** [comment]
Awesome.  Is 16 in this context commits on the remote that need to be pulled down?  I just downloaded the new beta, but haven't had a chance to work on multiple machines to test how outdated local repos might look in the app.

**Comment by shiftkey** [comment]
@JosephTLyons that's exactly right

**Comment by JosephTLyons** [comment]
@shiftkey perfect!  This is exactly what I was looking for.. and more!
