### ISSUE TITLE
Git tree diagram

### ISSUE THREAD

**Issue by Bryksin** [desktop/desktop#18390]
### The feature request

Hi

So far git repo history is displayed as a long list of text per commit, however, there are no diagram showing the git tree with nice dots per commit and branch lines to see what was merged to where, so I am very much missing this view in the app.

Would be nice to add it

### Proposed solution

the way I would add it is on the left side before the list of the tree, just make another panel on the left
It would be awesome if you could click on the commit inside the history and it would automatically highlight the node on the graphic tree. 

### Additional context

As a reference, we can look at GitKraken
![GitKraken](https://www.gitkraken.com/wp-content/uploads/2022/03/index-thumbnail.png)

**Comment by steveward** [comment]
Thanks for the feedback. I'm going to add this to https://github.com/desktop/desktop/issues/2417 where we are tracking feedback about this feature.

**Comment by steveward** [comment]
Apologies, https://github.com/desktop/desktop/issues/9452 is what I meant.
