### ISSUE TITLE
I Clicked on the Restore Button but all my codes deleted

### ISSUE THREAD

**Issue by DeepashreeRay** [desktop/desktop#18391]
### The problem

I had some stashed changes. when I change the branch, I click on the restore button, but all my codes are deleted from GitHub.

### Release version

3.3.12 (x64)

### Operating system

windows

**Comment by steveward** [comment]
@DeepashreeRay Sorry to hear you're having trouble.

We should be able to recover the stash -- you will need to find the log file from the day this happened. You can access the log by going to Help > Show Logs in Finder (macOS) or Explorer (Windows).

Then you will want to search for a line like this:

` [ui] Dropped stash 'b947c54873415d875d5e4e0d941c443716e1c81e' associated with main`

You can then copy that SHA and run the following command from the command line:

`git stash apply b947c54873415d875d5e4e0d941c443716e1c81e`

That should recover the lost changes. Let me know if that does not get things working for you.

**Comment by yzababababab** [comment]
###

**Comment by yzababababab** [comment]
187.2.4.6
