### ISSUE TITLE
error: RPC failed; curl 55 Recv failure: Connection was reset

### ISSUE THREAD

**Issue by wsrinivas** [desktop/desktop#18401]
### The problem

![image](https://github.com/desktop/desktop/assets/25058762/aa3861dd-d892-44fa-970b-50b50e4e8e63)

I have tried this 4 times, using the Desktop hub as well as command line and everytime it crashed with

C:\Users\sri\Documents\GitHub\Clairelewis>git push
Enumerating objects: 7400, done.
Counting objects: 100% (7400/7400), done.
Delta compression using up to 8 threads
Compressing objects: 100% (7323/7323), done.
error: RPC failed; curl 55 Recv failure: Connection was reset
send-pack: unexpected disconnect while reading sideband packet
Writing objects: 100% (7400/7400), 90.90 MiB | 10.94 MiB/s, done.
Total 7400 (delta 607), reused 0 (delta 0), pack-reused 0 (from 0)
fatal: the remote end hung up unexpectedly
Everything up-to-date

### Release version

Version 3.3.12 (x64)

### Operating system

Win 10 Pro

### Steps to reproduce the behavior

Trying to push to main branch as first time initial commit
Press "Publish branch"

### Log files

[2024-04-02.desktop.production.log](https://github.com/desktop/desktop/files/14844548/2024-04-02.desktop.production.log)

**Comment by sergiou87** [comment]
Hey @wsrinivas, this appears to be a problem with the internet connectivity between you and GitHub.com (assuming it is GitHub.com you're connecting to). There's not much GitHub Desktop can do to solve this so I would suggest following the steps in the [Troubleshooting connectivity problems](https://docs.github.com/en/get-started/using-github/troubleshooting-connectivity-problems) guide.

You can use the [GitHub Debug](https://github-debug.com/) tool to test your connectivity to GitHub.com and, if necessary, submit a support request to our support team.

We've also seen this issue in the past when users have some kind of antivirus, firewall or proxy installed. If so, trying to disable or properly configure them usually gets things working. We've also seen this when users have unstable internet connection.

Please, let us know if that's your case!
