### ISSUE TITLE
Error with github in archlinux 

### ISSUE THREAD

**Issue by Zeroprograming** [desktop/desktop#18409]

**Comment by Zeroprograming** [comment]
![image](https://github.com/desktop/desktop/assets/115946815/89987ea4-1102-44f8-a70e-a5cfcaa56510)

**Comment by sergiou87** [comment]
issues related to the unofficial Linux fork of GitHub Desktop can be filed here:

https://github.com/shiftkey/desktop/issues

At this time we only officially provide support for macOS and Windows.

Sorry!
