### ISSUE TITLE
Missing Icons on macOS

### ISSUE THREAD

**Issue by caneroj1** [desktop/desktop#1840]
### Description

I downloaded the macOS client from the download page this morning. There are a few missing icons on the **Configure Git** page.

### Version

**GitHub Desktop version:** 0.5.8

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** macOS Sierra 10.12.5

### Steps to Reproduce

1. Download client
2. On a fresh install, navigate to the **Configure Git** page
3. Observe missing icons

<img width="473" alt="screen shot 2017-05-31 at 8 46 59 am" src="https://cloud.githubusercontent.com/assets/3110602/26632786/4a3690f4-45df-11e7-85c5-5966ae9c85dd.png">

**Comment by niik** [comment]
@caneroj1 I suspect this was related to the [brief outage that GitHub experienced](https://twitter.com/githubstatus/status/869895419685457920) just a little while ago. I'm gonna close this out and refer you to #1621 where we are planning on loading this image from disk instead of over the network.
