### ISSUE TITLE
Log Selected

### ISSUE THREAD

**Issue by johndpope** [desktop/desktop#18411]
### The feature request

I need the behaviour exactly as sourcetree 

### Proposed solution

download sourcetree - see historical changes on 1 file across many git commits.

### Additional context

.

**Comment by sergiou87** [comment]
Thank you for your request. Could you elaborate a bit more about the feature in the issue description, please?

**Comment by johndpope** [comment]
<img width="1293" alt="Screenshot 2024-04-04 at 10 14 49 pm" src="https://github.com/desktop/desktop/assets/289994/4b0f1d0f-3ccf-4d5b-b034-292267950f07">

this git commit shows 3 file changes.
but I need to find more info on 1 file - I right mouse click - log selected
<img width="605" alt="Screenshot 2024-04-04 at 10 17 33 pm" src="https://github.com/desktop/desktop/assets/289994/72c04ada-12fb-4a81-8905-3ef3c5960b8f">



it gives me an exhaustive list of every commit to that specific file -  i don't always use this - but i use it enough to make me need to switch back to sourcetree 
<img width="1096" alt="Screenshot 2024-04-04 at 10 15 00 pm" src="https://github.com/desktop/desktop/assets/289994/da4fcd3e-bac4-46f1-8aa6-88df20919799">

**Comment by steveward** [comment]
Thanks for clarifying the feature you're looking for. We are tracking this in https://github.com/desktop/desktop/issues/11990 so I'll reference this issue there and close this out. You can follow along there for updates.

**Comment by johndpope** [comment]
Thanks for the reset combined lines in latest update. please fix https://github.com/desktop/desktop/issues/11990
