### ISSUE TITLE
"Semantic check all button" still not working right

### ISSUE THREAD

**Issue by aybe** [desktop/desktop#18421]
### The problem

As you can see, I'm trying to deselect the 2nd block but it isn't working at all:

https://github.com/desktop/desktop/assets/1537591/98f3ca59-07ae-4179-8e8e-7c82599b03e3

😤🤣

Thanks!

### Release version

3.3.13-beta1 (x64)

### Operating system

Windows 11

### Log files

[2024-04-05.desktop.beta.log](https://github.com/desktop/desktop/files/14884420/2024-04-05.desktop.beta.log)

**Comment by tidy-dev** [comment]
@aybe Thank you for the report!

Do you have reproduction steps that you can reliably get the app in that state? So far, I have had no luck reproducing.

**Comment by tidy-dev** [comment]
I figured it out. A work around if you notice weird check all buttons is to hit the history tab and then return the changes tag for a fresh render. Appears I have a caching issue.

Other simple workaround: toggle between split and unified diff.

Repro steps found:

1. Open a file of moderate length. I used desktop's readme.
2. Delete (probably any modification really) a chunk of lines. I deleted lines 70-90.
3. Go to Desktop to see the deletion in the changes view.
4. Return to editor and undo that modifications and make a new modification. I undid the change in 2 and deleted lines 32-42 and lines 105-107
5. Return to desktop to see incorrect check all buttons spanning the entire side of the two hunks. Likely still associated with lines 70-90.

**Comment by aybe** [comment]
> @aybe Thank you for the report!
> 
> Do you have reproduction steps that you can reliably get the app in that state? So far, I have had no luck reproducing.

Tried pretty much everything, until undo-ing a commit, it reappeared!



> I figured it out. A work around if you notice weird check all buttons is to hit the history tab and then return the changes tag for a fresh render. Appears I have a caching issue.
> 
> Other simple workaround: toggle between split and unified diff.
> 
> Repro steps found:
> 
> 1. Open a file of moderate length. I used desktop's readme.
> 2. Delete (probably any modification really) a chunk of lines. I deleted lines 70-90.
> 3. Go to Desktop to see the deletion in the changes view.
> 4. Return to editor and undo that modifications and make a new modification. I undid the change in 2 and deleted lines 32-42 and lines 105-107
> 5. Return to desktop to see incorrect check all buttons spanning the entire side of the two hunks. Likely still associated with lines 70-90.

That's right, switching to history tab fixes the problem! 🥳

**Comment by aybe** [comment]
I have found a good repro! 🤣

- open the app
- commit first block
- close the app
- reopen the app
- undo last commit
- now there's a blue bar joining the 2 blocks -> bug is there🐛

https://github.com/desktop/desktop/assets/1537591/a8174558-7152-4a88-a40c-8d74161f7347

**Comment by tidy-dev** [comment]
Thank you! I have a fix up for review and will get it into beta soon.

**Comment by tidy-dev** [comment]
Released in 3.3.14-beta2

**Comment by aybe** [comment]
Amazing, thank you! 🥳👌
