### ISSUE TITLE
Why is a stash tied to a branch?

### ISSUE THREAD

**Issue by shivamka1** [desktop/desktop#18426]
### The feature request

The stash should not be tied to any branch! This is not an expected behaviour. 
Consider the following workflow:
```bash
$ git clone git@github.com:desktop/desktop.git
$ git checkout -b fix/README
$ cat "Hello" >> README.md
$ git stash
$ git checkout -b fix/docs
$ git stash apply
```

Currently, the changes to the `README.md` get tied to the branch `fix/README` which means I can't follow the aforementioned workflow!

### Proposed solution

Don't tie stashed to any particular branch. It is not an expected behaviour. You can have a look at other git client. I can confirm this works fine in Sourcetree.

**Comment by tidy-dev** [comment]
@iamsmkr Thanks for the feedback. We are tracking feedback around stashing in https://github.com/desktop/desktop/issues/12699. Thus, I am closing in favor of tracking that feedback there. It is not quite the same issue, but the other ticket is discussing more flexibility around making and popping stashes.

**Comment by tidy-dev** [comment]
Also linking to https://github.com/desktop/desktop/issues/13156
