### ISSUE TITLE
Officially Support Linux

### ISSUE THREAD

**Issue by adnansiddiqui-dev** [desktop/desktop#18425]
### The feature request

We can't use the forked github desktop on Organization repo. We want official Github Desktop for linux

### Proposed solution

All the linux users can use the full potential and fun of the Github Desktop

**Comment by robbertakse** [comment]
gh pr checkout 22277

**Comment by adnansiddiqui-dev** [comment]
> gh pr checkout 22277

I don't understand what you are saying

**Comment by steveward** [comment]
Thanks for the issue @adnansid99. You can also follow along with https://github.com/desktop/desktop/issues/1525 for updates about an official Linux release.
