### ISSUE TITLE
Github Desktop won't open

### ISSUE THREAD

**Issue by LesleyM27** [desktop/desktop#18432]
### The problem

My GIthub Desktop does not open on my windows PC. 

### Release version

3.3.13

### Operating system

Windows 11

**Comment by sergiou87** [comment]
Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by LesleyM27** [comment]
After I installed the .exe file. The app itself didn't launch

**Comment by steveward** [comment]
To get some more information about why the installation is failing it would be helpful if you could send over the log file that the Squirrel installer generates.

You should be able to find the log file here:

`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`

If no log file is being generated there you should be able to find one in the `SquirrelTemp` directory:

`%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

Please send that over as an attachment.

If you're running any antivirus software I would also recommend temporarily disabling it to see if that resolves the issue.

**Comment by LesleyM27** [comment]
[SquirrelSetup.log](https://github.com/desktop/desktop/files/14907186/SquirrelSetup.log)

**Comment by LesleyM27** [comment]
I also tried disabling my windows defender, still doesn't work.

**Comment by LesleyM27** [comment]
Any fix to the solution?

**Comment by steveward** [comment]
I'm not seeing anything in the log file related to GitHub Desktop. Could you try performing a fresh installation of GitHub Desktop by following these steps?

Here's how to do that:

1. Open File Explorer
2. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
3. Go to `%AppData%` and delete the `GitHub Desktop` directory
4. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that helps at all.

**Comment by LesleyM27** [comment]
I just did all that. Still doesn't work

**Comment by steveward** [comment]
Is anything showing up when you attempt to open the app? Do you see any GitHub Desktop processes running in Task Manager?

Could you also open up PowerShell and run the following command and let me know the output to see if there is anything related to GitHub Desktop?

`Get-EventLog -LogName "Application" -EntryType "Error" -Newest 20  | Format-Table  Index, Source, Message`

**Comment by LesleyM27** [comment]
so when I try to open the app, the cursor shows the loading thingy but it never opens. On the task manager,
 it appears and then disappears when I try to open it.

**Comment by LesleyM27** [comment]
![Screenshot 2024-04-09 204058](https://github.com/desktop/desktop/assets/164345022/d3a8b4b9-2561-4c85-8664-dc183ba6b8ce)

**Comment by LesleyM27** [comment]
That's what powershell shows me

**Comment by steveward** [comment]
Unfortunately i'm running out of ideas about why GitHub Desktop is not working. Can you open Event Viewer and see if there is *anything* there related to GitHub Desktop? 

Also, do you know what the NextSink.exe application is that is shown in that output? A quick search isn't turning up much and I'm wondering if that is something on your system that could be causing issues.

One thing you can try would be to create a new user account on your Windows machine and try to install GitHub Desktop there. That's often a good test to see if there is a specific issue with your user profile.

**Comment by LesleyM27** [comment]
I tried that. Still not working

**Comment by steveward** [comment]
Do you know what the NextSink.exe application is that is referenced in Event Viewer?

**Comment by LesleyM27** [comment]
I am not sure what that NextSink.exe is but I got it to work. Thank you

**Comment by steveward** [comment]
Glad to hear things are working now!

**Comment by atipicodev** [comment]
@LesleyM27 I am having the same problem. How did you manage to make it work, if you may share? Thanks.

**Comment by steveward** [comment]
@marcelSage if you're having problems launching GitHub Desktop you can open a new issue so that we can assist you further.

**Comment by Dylan-Madigan** [comment]
I would also really like to know how you got it working, I'm having the same issue after having it installed just a few weeks but I'm not sure I care enough to spend hours on it lol.

**Comment by LesleyM27** [comment]
> I would also really like to know how you got it working, I'm having the same issue after having it installed just a few weeks but I'm not sure I care enough to spend hours on it lol.

I reset my computer and installed it again and it worked after the reset.
