### ISSUE TITLE
History code not showing

### ISSUE THREAD

**Issue by EdisonAlushaj** [desktop/desktop#18435]
### The problem

the code that is changed in history it's not showing in my github desktop. When i try at my colleague it works fine.

### Release version

Version 3.3.13 (x64)

### Operating system

Windows 11

### Screenshots

![Github-issue](https://github.com/desktop/desktop/assets/96665518/91d31eaa-6f63-4b5a-b8cc-a2b65364b3f7)

**Comment by steveward** [comment]
Thanks for the report @EdisonAlushaj. Are you saying that a different machine is showing the diff in GitHub Desktop? A quick search for this filetype seems to indicate that it's a binary file type and is not recommended to be added to your repository, so it should be ignored. See [this doc](https://learn.microsoft.com/en-us/visualstudio/extensibility/internals/solution-user-options-dot-suo-file?view=vs-2022) from Microsoft. I'm going to close this out.

**Comment by EdisonAlushaj** [comment]
No all the types of changes are not showing (Javascript files, CSS files etc). It just shows "No content changes found".

**Comment by steveward** [comment]
Do you have a `.gitattributes` file in this repository?

Can you open the repository in the command line and run `git diff <file>` to see what that outputs?

Can you also try creating a new repository to see if you encounter this issue diffing a simple text file?
