### ISSUE TITLE
Use portable Sublime Text as External Editor

### ISSUE THREAD

**Issue by Justin-JHG** [desktop/desktop#18433]
### The feature request

hi there, 

currently GitHub Desktop supports using Sublime Text as External Editor
just wondering is there a way to configure it so that Desktop can use portable Sublime Text as External Editor? 

### Proposed solution

allow users to configure External Editor by updating a configuration file

**Comment by steveward** [comment]
@Justin-JHG thanks for the issue. At this time Sublime Text portable is not on the list of supported editors. There are some qualifications for an editor to be detected by GitHub Desktop, see the [editor integration doc](https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md). There needs to be an install entry in the registry for the editor to be properly detected by GitHub Desktop.

We do want to make our editor detection more robust, and this is being tracked in https://github.com/desktop/desktop/issues/7033 and may allow for supporting portable editors.

I'll keep this open and label it as an enhancement.

**Comment by Justin-JHG** [comment]
thank you @steveward and the team, GitHub Desktop is great. 
looking forward to this coming soon

**Comment by steveward** [comment]
GitHub Desktop now provides support for [adding custom editors](https://docs.github.com/en/desktop/configuring-and-customizing-github-desktop/configuring-a-default-editor-in-github-desktop?platform=windows#configuring-a-custom-editor), so you can add the portable version of Sublime Text by following the steps in that linked help article. I'm going to close this out.
