### ISSUE TITLE
多个 stash

### ISSUE THREAD

**Issue by DargonLee** [desktop/desktop#18430]
### The feature request

现在Stash 某个改动之后，再次 Stash 后会把第一个 Stash 给覆盖掉

### Proposed solution

可以参考 SourceTree 的 git 管理工具，可以 Stash 多个代码改动。

### Additional context

期待在下个版本增加这个功能，我还是很喜欢用 GithubDestop 的，不然我就直接换 SourceTree 了

**Comment by steveward** [comment]
Thanks for the feedback @DargonLee. Support for multiple stashes is being tracked in https://github.com/desktop/desktop/issues/12699. You can follow along there for updates.
