### ISSUE TITLE
Display the exact (not relative) date of the commit

### ISSUE THREAD

**Issue by Qf4ctor** [desktop/desktop#18442]
### The feature request

Display absolute dates. Replace "Author · X months ago" by "Author · 2023-03-01".

### Proposed solution

Right now, in the History tab, the commits have a description of  "Author · X months ago". Allow us to display "Author · 2023-03-01" please. We can already tell that it was 12 months ago from the date. Thanks!

**Comment by tidy-dev** [comment]
@Qf4ctor Thank you for the feedback. We are tracking use of non-relative or friendly dates in this issue https://github.com/desktop/desktop/issues/14611. Closing this issue in favor of that tracking issue.
