### ISSUE TITLE
Can't clone repo from an organization I created

### ISSUE THREAD

**Issue by livethetruth** [desktop/desktop#18448]
Hello, I move two repos from my personal account to a newly created organization I own. Github Desktop doesn't let me clone either repo, or publish a new one to my organization. I get this error:

"Authentication failed. You may not have permission to access the repository. Open options and verify that you're signed in with an account that has permission to access this repository."

Any idea what could be wrong, or what I need to do? I could commit to this until I moved it to the organization I own, and now can't clone it through Github Desktop.

**Comment by tidy-dev** [comment]
@livethetruth Thank you for reaching out. Could you try Settings/Options > Accounts and Sign Out and Sign back in?

**Comment by livethetruth** [comment]
Yeah, I did. I also just installed Github Desktop on a fresh Ubuntu install, and had the same issue.

This is the error I get. If I try to sign in to my personal account through this window, it tries, and then takes me right back to here.

![Screenshot from 2024-04-12 00-16-49](https://github.com/desktop/desktop/assets/10328743/cf281a5d-4975-4e61-bbde-5bf7b4e3bff7)

**Comment by steveward** [comment]
@livethetruth if you're using the Linux fork then you're likely encountering https://github.com/shiftkey/desktop/issues/217. I'm going to close this out as we don't provide official support for the Linux fork over here, but I'd recommend taking a look through the issue I linked for assistance. I hope that helps.

**Comment by livethetruth** [comment]
Thank you!
