### ISSUE TITLE
Displayed commit date is obfuscated by "x days ago" or "x months ago" instead of reporting the date 

### ISSUE THREAD

**Issue by SrgSteak** [desktop/desktop#18443]
### The problem

I rather often need to be able to see when a specific commit has been submitted but the history now shows unhelpful information like "22 days ago". Why do I have to do mental gymnastics with leap years and varying month lengths to find out when a specific commit was?

### Release version

3.3.13

### Operating system

Mac OS Sonoma 14.4.1

### Steps to reproduce the behavior

Go to a repository with commits
Click on the "History" tab
The list will show not the date but "x days ago"

### Screenshots

![image](https://github.com/desktop/desktop/assets/8882558/2bf8b082-487c-40d3-9e4f-e548b32544a6)

**Comment by DanielRouxSA** [comment]
You can hover over the x ago text and it will display the actual date in a tooltip, but I agree it can be somewhat hindering when trying to establish exactly when a commit was made.

**Comment by SrgSteak** [comment]
That’s a helpful reply! ThanksAm 10.04.2024 um 16:10 schrieb Daniël Roux ***@***.***>:﻿
You can hover over the x ago text and it will display the actual date in a tooltip, but I agree it can be somewhat hindering when trying to establish exactly when a commit was made.

**Comment by tidy-dev** [comment]
@SrgSteak Thank you for the feedback. We are tracking use of non-relative or friendly dates in this issue https://github.com/desktop/desktop/issues/14611. Closing this issue in favor of that tracking issue.
