### ISSUE TITLE
Repository deleted from Pc

### ISSUE THREAD

**Issue by NLStevenson** [desktop/desktop#18447]
### The problem

Repository for a game I'm working on was deleted between uses of github desktop. Files not in folder, trash, anywhere that I can see. including log for last commit and then log on day issue found. Receiving error "Can't Find Mythora_Dev" as the repository is no longer in the folder. Folder is "/home/nate/Documents/GitHub/Mythora_Dev"

I can reload repository from github, but I believe this is unexpected/unwelcome behavior for desktop.

### Release version

3.3.12-linux2

### Operating system

Linux: Ubuntu

### Log files

[2024-03-28.desktop..log](https://github.com/desktop/desktop/files/14936424/2024-03-28.desktop.log)
[2024-04-01.desktop..log](https://github.com/desktop/desktop/files/14936426/2024-04-01.desktop.log)

**Comment by steveward** [comment]
@NLStevenson thanks for the report. At this time we don't provide official support for the Linux repository, but I would recommend opening an issue in the Linux fork for tracking to see if anyone else from the community has encountered this issue. You can find that issue tracker here:

https://github.com/shiftkey/desktop/issues

**Comment by K4P0NI** [comment]
> ### The problem
> Repository for a game I'm working on was deleted between uses of github desktop. Files not in folder, trash, anywhere that I can see. including log for last commit and then log on day issue found. Receiving error "Can't Find Mythora_Dev" as the repository is no longer in the folder. Folder is "/home/nate/Documents/GitHub/Mythora_Dev"
> 
> I can reload repository from github, but I believe this is unexpected/unwelcome behavior for desktop.
> 
> ### Release version
> 3.3.12-linux2
> 
> ### Operating system
> Linux: Ubuntu
> 
> ### Steps to reproduce the behavior
> _No response_
> 
> ### Log files
> [2024-03-28.desktop..log](https://github.com/desktop/desktop/files/14936424/2024-03-28.desktop.log) [2024-04-01.desktop..log](https://github.com/desktop/desktop/files/14936426/2024-04-01.desktop.log)
> 
> ### Screenshots
> _No response_
> 
> ### Additional context
> _No response_
