### ISSUE TITLE
Deleted tag and recreated on different commit is not reflected in client

### ISSUE THREAD

**Issue by mrkmcnamee** [desktop/desktop#18456]
### The problem

We rerolled a patch which involved deleting a release and the associated tag, and then creating a new release with the same tag on a later commit. This all worked fined in GitHub web, but the GitHub client did not move the tag to the new commit after fetch origin, which is confusing.

### Release version

3.3.13

### Operating system

Windos 11 Pro

### Steps to reproduce the behavior

1. Web: Create tag and release on branch, say master.
2. Client: Fetch origin. Tag is shown on last commit on master.
3. Client: Make new commit on master and push.
4. Web: Delete tag and release.
5. Web: Recreate tag and make new release from the new commit.
6. Client Fetch origin. Tag is still shown on old commit.

### Screenshots

Client after retagging shows tag on old commit:

![image](https://github.com/desktop/desktop/assets/46104536/8ae2a66c-2b0d-4006-b919-c573a329a552)

Web shows tag on new commit:

![image](https://github.com/desktop/desktop/assets/46104536/f51d01bb-cdbe-481a-99f3-fb6b78e1a330)

**Comment by steveward** [comment]
@mrkmcnamee thanks for the report. Git won't update the tag locally -- see this [comment](https://github.com/desktop/desktop/issues/9946#issuecomment-639611586) for some more information about this. I'm going to close this out, but let me know if you have any further questions.

**Comment by mrkmcnamee** [comment]
Hi @steveward!
OK, so Git doesn't update the tag locally by default. But it is possible to do? [StackOverflow ](https://stackoverflow.com/questions/9662249/how-to-overwrite-local-tags-with-git-fetch) suggests: `git fetch origin --tags --force` or a variation of that.

So, do I have to manually run this command or is it possible to do this in the GitHub client?

**Comment by steveward** [comment]
You'll have to manually run that command, there isn't a way to do this in GitHub Desktop as of yet.
