### ISSUE TITLE
don't know why

### ISSUE THREAD

**Issue by j-vitali** [desktop/desktop#18454]
### The problem

<img width="859" alt="Screenshot 2024-04-12 alle 08 24 26" src="https://github.com/desktop/desktop/assets/161858414/5f5da2f1-31b4-4234-a88c-132a24dae9e3">
![Uploading Screenshot 2024-04-12 alle 08.26.15.png…]()

### Release version

latest

### Operating system

mac

### Additional context

basically it happens because i have that names of branches:
**feat/profileserfice/organizations
feat/profileserfice/organizations-groups**

**Comment by j-vitali** [comment]
<img width="859" alt="Screenshot 2024-04-12 alle 08 32 15" src="https://github.com/desktop/desktop/assets/161858414/8abbff5c-cb65-4912-b28a-5dbabe7ff800">

**Comment by steveward** [comment]
Thanks for the report @j-vitali. Can you open the the repository in the command line and run the following commands?

`git fsck`
`git branch -a`

Let me know the output of those.
