### ISSUE TITLE
repository not updading

### ISSUE THREAD

**Issue by satishimpex** [desktop/desktop#18459]
### The problem

the files are showing changed on local repository but not showing on github.com

### Release version

3.3.13 (x64)

### Operating system

window 10

**Comment by Alijutt00** [comment]
###indian bank

**Comment by Alijutt00** [comment]
https://github.com/desktop/desktop/issues/18459#issue-2242263304 zzz

**Comment by steveward** [comment]
@satishimpex thanks for the issue. Can you share some further details about the issue you're experiencing? Have you committed the changes and are encountering errors when you attempt to push them to GitHub?
