### ISSUE TITLE
make the Licenses dialog easier to navigate

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#1846]
### Description

After the changes in #1611, the Licenses dialog contains a lot of license text for all the projects that we bundle in GitHub Desktop. Capturing a task for someone who is visually inclined who wants to take a shot at polishing this view.

### Version

**GitHub Desktop version:** aae658c
**OS version:** macOS 10.12.4

### Steps to Reproduce

1. Launch the Application
1. Under the **GitHub Desktop** menu item, select **About GitHub Desktop**
1. Click **License and Open Source Notices** link

**Visual Feedback:** 

 - it should be easier to scroll the list without getting lost in all the license text.
 - the fixed width of the license text leads to some overflow - it'd be nice if we could reduce that somewhat
 - we should make the Desktop section stand out from the rest of the licenses

**Comment by terales** [comment]
<details>
  <summary>My suggestion is two use a two column layout. Click to open an example from current master branch.</summary>
  <img src="https://cloud.githubusercontent.com/assets/1920639/26652222/d3137d74-4657-11e7-887b-feef2ada8d4a.png">
</details><br>


Names of projects will be links to the repositories and source text could be opened with click on the icon.
What do you think?

**Comment by j-f1** [comment]
@terales How about also adding the SPDX identifier after the package name?

**Comment by terales** [comment]
This will add some noise with a lot of repeated data. If we need to always see a license name we can create scroll like in Windows Phone. See example [from 2:47 to 02:52 in "Windows Phone 7 Announcements & Demo's from MIX 11 with Joe Belfiore"](https://channel9.msdn.com/Blogs/Windows-Phone-7/Windows-Phone-7-Announcements--Demos-from-MIX-11-with-Joe-Belfiore).

**Comment by j-f1** [comment]
@terales That looks even better.

**Comment by billygriffin** [comment]
This seems like it might be nice, but since we haven't seen a ton of evidence that anyone is being harmed by the current layout, I'm going to close this. Obviously we can reopen if it becomes something worth focusing on. Thanks!

**Comment by golfstok** [comment]
Thanks

Hent Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Billy Griffin <notifications@github.com>
Sendt: Thursday, April 16, 2020 12:02:20 AM
Til: desktop/desktop <desktop@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: Re: [desktop/desktop] make the Licenses dialog easier to navigate (#1846)


Closed #1846<https://github.com/desktop/desktop/issues/1846>.
