### ISSUE TITLE
Created Branch in JIRA does not show in GitHub while searching

### ISSUE THREAD

**Issue by richelleramirez** [desktop/desktop#18469]
### The problem

I have created a jira ticket, created a branch in the Jira ticket in the correct Repository.
Then I go to github desktop, selected the repository, Fetch origin, then Pull the seen committed branch.
Then I try to search for that branch, it does not show.
I was able to do the same thing last night, now its not the same case anymore.

### Release version

Version 3.3.13 (x64)

### Operating system

Windows 10

**Comment by steveward** [comment]
@richelleramirez thanks for the report. Is this a repository that is hosted on GitHub?

**Comment by Igor19792910** [comment]
[1707649189019.pdf](https://github.com/desktop/desktop/files/15000616/1707649189019.pdf)
