### ISSUE TITLE
Add Profile Settings 

### ISSUE THREAD

**Issue by Chasewp** [desktop/desktop#18474]
### The feature request

Kinda complicated must login to github website then to change Profile settings, i hope at next version can implemented this feature also at the apps the options only Account, Integration, Git, Appirance, Notification, Prompt, and Advance 
cant settings the profile via github desktop must via browser

### Proposed solution

just use github desktop for change profile settings not need open the browser

**Comment by steveward** [comment]
Thanks for the issue @Chasewp. We'll likely never duplicate the available options for configuring your GitHub account, as the intent of GitHub Desktop isn't to mirror github.com's functionality. I'm going to close this out, but let me know if you have any further questions.
