### ISSUE TITLE
Move to Electron Stable version 30

### ISSUE THREAD

**Issue by fisforfaheem** [desktop/desktop#18478]
### The feature request

This is help with ARM64 windows on ARM support

### Proposed solution

upgrade Electron to latest stable release

**Comment by steveward** [comment]
@fisforfaheem thanks for the issue. We just updated to v28, and intentionally lag behind the latest releases, but thanks for letting us know you'd like to see this. I'm going to close this out, but let me know if you have any further questions.

**Comment by fisforfaheem** [comment]
Sure, I would like to know, whether Fluent UI would be adapted for windows 11 ? Also would like to tell thst is there an easy Way to rename the commits.. using this app

**Comment by steveward** [comment]
> Sure, I would like to know, whether Fluent UI would be adapted for windows 11 ?

I can't answer that as that looks like a Microsoft project, I'd recommend taking a look at their [repository](https://github.com/microsoft/fluentui).

> Also would like to tell thst is there an easy Way to rename the commits.. using this app

You can amend your most recent commit to change the commit message, see [this guide](https://docs.github.com/en/desktop/managing-commits/amending-a-commit-in-github-desktop).
