### ISSUE TITLE
I get some errors

### ISSUE THREAD

**Issue by MrScautHD** [desktop/desktop#18489]
### The problem

Hello, when im starting the github desktop app it tell me about errors and it do not let me push something without an error.

### Release version

3.3.13

### Operating system

Windows 11

### Log files

[2024-04-20.desktop.production.log](https://github.com/desktop/desktop/files/15047477/2024-04-20.desktop.production.log)

### Screenshots

![grafik](https://github.com/desktop/desktop/assets/65916181/0cd26c16-1451-4dcd-bacf-0b379dcf086b)

**Comment by steveward** [comment]
Thanks for the report @MrScautHD. Are you running any security software on this server that could be interfering with the app? 

It looks like the underlying git commands are throwing this error:

```
2024-04-20T07:53:06.152Z - error: [ui] `git log 55ace50b14732c6e2fbc8d36bf574f8559bcdccd --date=raw --max-count=1 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color --` exited with an unexpected code: 3221225477.
```

Has GitHub Desktop previously worked on your machine without this error?

**Comment by MrScautHD** [comment]
> Thanks for the report @MrScautHD. Are you running any security software on this server that could be interfering with the app?
> 
> It looks like the underlying git commands are throwing this error:
> 
> ```
> 2024-04-20T07:53:06.152Z - error: [ui] `git log 55ace50b14732c6e2fbc8d36bf574f8559bcdccd --date=raw --max-count=1 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color --` exited with an unexpected code: 3221225477.
> ```
> 
> Has GitHub Desktop previously worked on your machine without this error?

I has just the windows defender, but even if i disable it this errors are coming.

And yea a few months ago it worked fine on this pc.

**Comment by steveward** [comment]
@MrScautHD are you still encountering this issue? If so, it may be worth trying a fresh install:

Here's how to do that:

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `%AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that helps at all.

**Comment by MrScautHD** [comment]
Still not fixed:

ERROR with the reinstallation:
[2024-06-15.desktop.production.log](https://github.com/user-attachments/files/15846019/2024-06-15.desktop.production.log)

**Comment by MrScautHD** [comment]
Any other ideas? @steveward

**Comment by MrScautHD** [comment]
Hello, this erros did come because my pc had some virus but thx anyways for help!
