### ISSUE TITLE
I Dont Have An Option To Publish 

### ISSUE THREAD

**Issue by KeishaV29** [desktop/desktop#18480]
Hi I'm using Github for an assignment and I'm having difficulty publishing my work from my Github desktop to the Github website. Please help as I am losing time in submitting my assignment and nothing that I have tried is working. Including creating a new folder and a new account.

**Comment by steveward** [comment]
@KeishaV29 Sorry to hear you're having trouble. Can you share some more details or screenshots of what you're seeing in GitHub Desktop?

The `Publish` option will be present if the repository has not been created on GitHub. If you're trying to push to an existing repository you'll see `Push origin`.

**Comment by KeishaV29** [comment]
Hi Steve,

Thank you for your swift response. I've created a folder on my desktop and
have coded using VSCODE. I then downloaded Github desktop to try to publish
my repository to the Github website with no success. I dont have the option
to publish, only push and the only repository that is showing on the Github
website is an old one that I deleted 3 weeks ago. It keeps showing up as
New Project ( I've attached) This has become a major stressor in my life as
I can't figure out just how to get my document to show on Github.com. I've
tried to upload it directly but it's saw that the files are large (I've
attached). I've provided screenshots, please help me.

**Comment by steveward** [comment]
@KeishaV29 unfortunately your screenshots won't come through via email reply, you'll need to drag-and-drop them into an issue comment here to upload them.

If you go to `Repository` > `Repository Settings` > `Remote` in GitHub Desktop does the URL there point to the correct repository on GitHub?
