### ISSUE TITLE
Occasionally cannot start/detect GPG agent

### ISSUE THREAD

**Issue by Vectorial1024** [desktop/desktop#18484]
### The problem

I have enabled GPG key signing on commit.

Sometimes, especially when committing for the first time of the day, I got this popup message saying GH Desktop cannot sign my commits:

```
gpg: error running '/usr/lib/gnupg/keyboxd': probably not installed
gpg: failed to start keyboxd '/usr/lib/gnupg/keyboxd': Configuration error
gpg: can't connect to the keyboxd: Configuration error
gpg: error opening key DB: No Keybox daemon running
gpg: skipped "587FDC3BDC79957A": Input/output error
gpg: signing failed: Input/output error
error: gpg failed to sign the data
fatal: failed to write commit object
```

Would this be a potential problem of GitHub Desktop?

### Release version

3.3.14

### Operating system

Windows 11

### Screenshots

![image](https://github.com/desktop/desktop/assets/17726797/d39930f8-c8ce-4712-b0cd-a2b9372ca9f4)

### Additional context

Manually starting the keybox daemon will fix this; e.g. ref https://superuser.com/questions/1153101/why-does-git-complain-that-no-gpg-agent-is-running

> The following command starts the gpg-agent on Windows:
> `gpg-connect-agent reloadagent /bye`

Alternatively, committing via e.g. SourceTree at least once will somehow start the GPG agent, and then I can continue using GitHub Desktop for more commits on the same day.

Would much prefer GitHub Desktop to handle the daemon-start for me.

**Comment by steveward** [comment]
@Vectorial1024 thanks for the issue, and apologies for the delay here. We've seen this reported in https://github.com/desktop/desktop/issues/14274, but haven't dug into it as of yet. I'm going to close this out and reference this there.
