### ISSUE TITLE
Godot Git Ignore not updated for Godot 4

### ISSUE THREAD

**Issue by mich-gamedev** [desktop/desktop#18486]
### The problem

While Godot 3 uses .import/ for it's cache files, Godot 4 now uses .godot/, which isn't included in the godot template

### Release version

Version 3.3.14 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Go to `File/New Repository...`
2. Pick `Godot` in `Git ignore` setting
3. open the `.gitignore` file

### Screenshots

![image](https://github.com/desktop/desktop/assets/150397626/b40e9842-249a-423e-88a4-2de8cc4d373e)

**Comment by steveward** [comment]
Thanks for the report @mich-gamedev. It does look like our gitignore submodule is due for an update -- I'll add it to our board to get updated.
