### ISSUE TITLE
How do I stop upgrading Version 3.3.3

### ISSUE THREAD

**Issue by pa3axa** [desktop/desktop#18485]
### The problem

I running V3.3.3 on OSX 10.14 how do I stop the auto upgrade. Every time I start the
application its gets updated to a new V 3.3.14 that is no longer working on
my OSX 10.14 install.

### Release version

3.3.3

### Operating system

OSX 10.14.6

### Steps to reproduce the behavior

1 Open Github Desktop, new version gets loaded and overwrites V3.3.3 into
a no longer supported V3.3.14.

**Comment by sergiou87** [comment]
@pa3axa you can download 3.3.13 (the last version compatible with your macOS version) from this link and it shouldn't bother you more with auto-updates: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.13-1b0804db/GitHubDesktop-x64.zip

I hope that helps!

**Comment by pa3axa** [comment]
Yes works ! Thanks for the quick reaction to solve this.

**Comment by StefaniaContu** [comment]
Works for me as well!! Thanks!!
