### ISSUE TITLE
not login to git desktop opeing browser page suddenly crashing this browser page

### ISSUE THREAD

**Issue by JKGlobalItSolutions** [desktop/desktop#18499]
### The problem

not login to giot desktop opeing browser page suddenly crashing this browser poage  and this probnlem is arround i month 

### Release version

vdnv

### Operating system

ghd

### Log files

dhf

### Screenshots

[
![Screenshot (5)](https://github.com/desktop/desktop/assets/163848085/ffb653d2-3767-4fbb-9ac8-9e35434fa10c)
](url)

### Additional context

not login to giot desktop opeing browser page suddenly crashing this browser poage  and this probnlem is arround i month

**Comment by steveward** [comment]
Thanks for the report @JKGlobalItSolutions. I'm not sure I fully understand the issue -- when you click `Continue with browser` is your browser not opening correctly? If you can share some further details or maybe a short video of the issue I can assist further.
