### ISSUE TITLE
Installation of OPEN SYSTEMS PHARMACOLOGY SUITE - VERSION 11 UPDATE 3

### ISSUE THREAD

**Issue by zt1947** [desktop/desktop#18498]
I have downloaded and installed the OPEN SYSTEMS PHARMACOLOGY SUITE - VERSION 11 UPDATE 3. The Installation Validation report indicated a serious error indicated in the enclosed file [There is something wrong with the Open Systems Pharmacology.docx].

I have also downloaded the expression database GENEDB_human.expressionDb. However, when I tried to add a metabolizing enzyme to any of the individuals created for my project, I could not load the enzyme's expression by interrogating the expression database. The only option that the PKSim made available to enter the enzyme's levels manually. Will this be fixed once the installation is completed without errors.
[There is something wrong with the Open Systems Pharmacology.docx](https://github.com/desktop/desktop/files/15061768/There.is.something.wrong.with.the.Open.Systems.Pharmacology.docx)

**Comment by sergiou87** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
