### ISSUE TITLE
Pushing a commit

### ISSUE THREAD

**Issue by ajtruckle** [desktop/desktop#18491]
### The problem

I am using the beta version.

When I push a commit that includes a link to my public issue ticket, it usually just shows that a commit was pushed on the ticket.

But what it did this time was close my public ticket!

So I opened it, ammended and force pushed. It closed the public ticket again.

What is it doing this?

### Release version

Version 3.3.15-beta1 (x64)

### Operating system

Windows 11

### Log files

[2024-04-20.desktop.beta.log](https://github.com/desktop/desktop/files/15048266/2024-04-20.desktop.beta.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/7985331/def79996-d98a-462c-b265-a8f0c4076404)

![image](https://github.com/desktop/desktop/assets/7985331/2349ad0c-9825-47d4-a38a-887c7bf35747)

### Additional context

It normally does just this:

![image](https://github.com/desktop/desktop/assets/7985331/1ca9dbc8-c1a9-4506-b368-e5881cd4cd42)

**Comment by steveward** [comment]
@ajtruckle thanks for the issue. It sounds like you are pushing directly to the default branch, which will close the issue if it detects one of the [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). 

The general recommendation is to work with branches and then the pull request will close the issue when the it is merged to the default branch. I hope that helps explain things -- let me know if you have any questions!

**Comment by ajtruckle** [comment]
@steveward 
So if I use a branch and always push to that it will never automatically close the ticket? Then I merge it.

Can we switch this feature off? I like to be in control and choose when to close.

I ended up reverting to latest stable GitHub Desktop.

**Comment by steveward** [comment]
@ajtruckle this is a function of GitHub (the website), and not anything in GitHub Desktop. GitHub detects the keyword and closes the issue. Using a branch will not close the issue until the branch is merged into the default branch. There isn't a way to turn this off in github.com -- you would just need to not use the keywords if you don't want this behavior.
