### ISSUE TITLE
Unable to Authenticate through browser

### ISSUE THREAD

**Issue by emalmud** [desktop/desktop#18502]
### The problem

Im unable to authenticate through the browser. The page opens in chrome correctly and I am able to navigate all the pages, but when i am redirected back to github desktop I get an Error.

This is a work account with github and I am able to use ghp and ssh keys to access the repositories with "gh" and "git" command line tools, but am unable to clone through the github dekstop tool.

### Release version

3.3.14 arm64

### Operating system

MacOS Sonoma 14.4.1

### Steps to reproduce the behavior

1. Github Desktop Open > Settings > Accounts > Sign into Github.com
2. Continue with browser
3. Step through authorization on chrome (No errors)
4. Arrive back at github desktop with "An unknown error occurred."

### Log files

```
2024-04-22T19:31:05.938Z - info: [ui] [SignInStore] initializing OAuth flow
2024-04-22T19:31:05.948Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=7660f547-4807-48e0-b59a-0017171721f0
2024-04-22T19:31:09.946Z - info: [main] Processing protocol url
2024-04-22T19:31:09.946Z - info: [ui] [Dispatcher] requesting authenticated user
2024-04-22T19:31:10.363Z - info: [ui] [SignInStore] account resolved
2024-04-22T19:31:10.363Z - info: [ui] [AppStore] adding account emalmud (emalmud) to store
2024-04-22T19:31:10.400Z - error: [ui] Error adding account 'emalmud'
Error: An unknown error occurred.
```

### Screenshots

<img width="1008" alt="Screenshot 2024-04-22 at 2 33 38 PM" src="https://github.com/desktop/desktop/assets/167043317/37d9e977-5ba0-4013-a417-9a3e5507e118">

### Additional context

I am able to sign in with browsers on other apps including gitkraken.

I have also tried reinstalling the application a few times and using older versions.

**Comment by steveward** [comment]
Thanks for the report @emalmud. Have you previously been able to successfully authenticate on this machine? Are there any restrictions in place on this machine that could be causing access/permission issues?

Unfortunately that error isn't giving us much to go on. We've had one report of this previously in https://github.com/desktop/desktop/issues/17970, and I've asked there to see if they have any further information that we could go on to determine why this is happening.

**Comment by emalmud** [comment]
I did find the solve for this. I had to clear the cache on chrome. Unsure exactly why. And just to note reinstalling chrome DID NOT clear the cache.

**Comment by emalmud** [comment]
I did find the solve for this. I had to clear the cache on chrome. Unsure exactly why. And just to note reinstalling chrome DID NOT clear the cache.

**Comment by steveward** [comment]
Glad to hear things are working now, and thanks for sharing that update!

**Comment by guneskahraman** [comment]
Hey @steveward, I've the same issue. I'm trying to sign into my companies account at github.com from github desktop. However, it fails same like unknown error after login is redirected from browser. I cleared the cache, I've changed the browser to authenticate and none of them worked. It was working totally fine until few days ago. 
The strange thing is, some of the repo's which I downloaded long ago are still authenticated and I can keep using these ones. Some others are not authenticated anymore and I can't do any remote git operations on them. I also cannot clone new repo.
Can you help me on this?
