### ISSUE TITLE
Github Desktop on WSL 

### ISSUE THREAD

**Issue by neokofg** [desktop/desktop#18505]
### The feature request

Please optimize GD on WSL repositories; it's very slow. Fetching the repo takes about 10 seconds, and operations like pulling and committing, e.t.c are also slow compared to native Windows repositories.

### Proposed solution

Maybe try running Git on WSL if the files are on the WSL disk. I guess currently it's just accessing Git through \\$wsl\.

**Comment by steveward** [comment]
Thanks for the report @neokofg. We've had some previous reports of this, I'll reference this in our main issue tracking performance as well (https://github.com/desktop/desktop/issues/10625).

**Comment by JoryHogeveen** [comment]
> Maybe try running Git on WSL if the files are on the WSL disk. I guess currently it's just accessing Git through \$wsl.

I think this is the best option indeed. Using PhpStorm for Git through WSL works great and I believe it indeed switches to git on WSL instead of Windows.

**Comment by aleixrodriala** [comment]
I went ahead and built exactly this — a fork that runs git natively inside WSL via a small daemon, so no more 9P overhead: [GithubDesktopWSL](https://github.com/aleixrodriala/GithubDesktopWSL)

It's like the VS Code Remote WSL extension but for GitHub Desktop. Patch-based so it auto-syncs with upstream releases, and installs side-by-side. Happy to hear feedback from anyone who tries it!

**Comment by BijjuXD** [comment]
> I went ahead and built exactly this — a fork that runs git natively inside WSL via a small daemon, so no more 9P overhead: [GithubDesktopWSL](https://github.com/aleixrodriala/GithubDesktopWSL)
> 
> It's like the VS Code Remote WSL extension but for GitHub Desktop. Patch-based so it auto-syncs with upstream releases, and installs side-by-side. Happy to hear feedback from anyone who tries it!

Hello  @aleixrodriala , thank you. This is what I exactly needed.
