### ISSUE TITLE
Secure Connection Failed in when opening desktop.github.com

### ISSUE THREAD

**Issue by Cedric-Ab** [desktop/desktop#18506]
### The problem

![image](https://github.com/desktop/desktop/assets/142994683/08b2db86-fee9-4adf-9ea8-2e47ab5b172e)
![image](https://github.com/desktop/desktop/assets/142994683/6d32da76-9a60-4ee0-a30b-35e8aeac37bf)

happend on librewolf, which to my knowledge is a firefox fork

### Release version

None

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Go to "https://desktop.github.com/"

**Comment by steveward** [comment]
@Cedric-Ab I'm not able to reproduce this issue in other browsers, and a quick search seems to show a few results of this happening with librewolf/Firefox for other sites, along with some potential resolutions (see https://appuals.com/pr-end-of-file-error/). I would recommend trying a different browser on your system to see if that succeeds.

Here's a direct link to download GitHub Desktop in Windows as well, in case you need that:

https://central.github.com/deployments/desktop/desktop/latest/win32

**Comment by Cedric-Ab** [comment]
That’s about what was to be expected.
I just thought I should report it, because it literally sais so right there.
And thx
