### ISSUE TITLE
Authentication failed in Github desktop

### ISSUE THREAD

**Issue by loganadin-bhuvanaganesan** [desktop/desktop#18504]
[Uploading 2024-04-24.desktop.production.log…]()
### The problem

<img width="804" alt="image" src="https://github.com/desktop/desktop/assets/113963377/2b50b256-5c00-444a-95f1-25afe73cdab1">
 i cannot push or pull from any of GitHub repo but i can access all via browsers 

### Release version

Version 3.3.14 (x64)

### Operating system

windows 11

### Screenshots

<img width="604" alt="image" src="https://github.com/desktop/desktop/assets/113963377/fc5330b6-0515-418e-a425-f012a733c780">

**Comment by sergiou87** [comment]
Thanks for your report @loganadin-bhuvanaganesan  but unfortunately your logs weren't uploaded correctly 😞 Could you post them again, please?

**Comment by loganadin-bhuvanaganesan** [comment]
[2024-04-24.desktop.production.log](https://github.com/desktop/desktop/files/15092252/2024-04-24.desktop.production.log)

@sergiou87   plz check the log 

i have move move my all repo to support ssl url 
via **git remote set-url origin git@github.com** 
and logout it works

**Comment by sergiou87** [comment]
Can you access those repositories with your user from github.com?

**Comment by viviy228** [comment]
I have the same error at work too, and I can access the repository from github.com and even IntelliJ.

It would give me these errors from time to time
![requiresAuth](https://github.com/desktop/desktop/assets/37194238/415b9aee-2b7f-44a4-9929-281d622e6914)
![redirect](https://github.com/desktop/desktop/assets/37194238/6d9565ae-6682-4be4-878d-ab060e430a7f)
