### ISSUE TITLE
Not able to fetch origin , push code etc even though i logged in.

### ISSUE THREAD

**Issue by uni-parth-p-shah** [desktop/desktop#18508]
### The problem

![image](https://github.com/desktop/desktop/assets/116708378/3e901895-92e5-4245-bd4e-fe8576d4d1fc)

I have tried logging in through my ID and password, my ID and SSH key, I made a new SSH key and tried, i tried logging out and logging in and I even deleted and reinstalled the app. But no matter what I do now I'm not able to do anything on github desktop anymore. It was working just a day ago.

### Release version

Version 3.3.14 (x64)

### Operating system

Windows

### Steps to reproduce the behavior

Logged in on github desktop from long before.
Suddenly not able to perform any operations like fetch origin, push code in any repo.

**Comment by uni-parth-p-shah** [comment]
![image](https://github.com/desktop/desktop/assets/116708378/036b59c5-df1c-440d-82cf-21fe4e473420)


when i try to clone repos, it asks me for this. But it does not verify my password nor my PAT. Even the new ones

**Comment by steveward** [comment]
Thanks for the report @uni-parth-p-shah. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. 

You won't be able to log in via the "Authentication dialog" -- that's used for third-party services.

**Comment by uni-parth-p-shah** [comment]
[logs.zip](https://github.com/desktop/desktop/files/15104043/logs.zip)
here's the log files you requested.

**Comment by uni-parth-p-shah** [comment]
note that git bash is working fine. i am able to pull my org's repos etc.

**Comment by uni-parth-p-shah** [comment]
![image](https://github.com/desktop/desktop/assets/116708378/24d193f3-d14f-4dcb-a1d8-a3224148b421)
i am able to push from gitbash

**Comment by uni-parth-p-shah** [comment]
![image](https://github.com/desktop/desktop/assets/116708378/5bfcbf0a-0db3-4664-ae63-9e69d5b0ae9a)


seeing this issue frequently as well. some operations are not working

**Comment by steveward** [comment]
It looks like you're hitting a SSH permissions issue. You can follow the steps in this article to troubleshoot that:

https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey

Let me know if that doesn't get things working.
