### ISSUE TITLE
SET  PASSWORD

### ISSUE THREAD

**Issue by salifou-root163** [desktop/desktop#18500]
### The problem

I can't push/pull to my private git because Github Desktop didn't prompt me to enter my password, and I can't find anywhere to configure the  password. 
When I try to push or pull, it just spins indefinitely. However, when I do the same actions with Git Bash, it asks for my password and works fine.

### Release version

Version 3.3.14 (x64)

### Operating system

windows 11 pro

### Steps to reproduce the behavior

create un private git repos
clone the repos 
try to pull or push with github desktop

### Log files

nothing in log for this problem because there is no crash but infinite spin.

### Screenshots

![Capture d'écran 2024-04-22 150948](https://github.com/desktop/desktop/assets/50051019/78384b97-8078-44a6-bd2f-dd6ba692f58a)

### Additional context

my repos is on o2switch 

https://www.o2switch.fr/

**Comment by steveward** [comment]
Thanks for the report @salifou-root163. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. 

The log file should hopefully provide some information about why the fetch is failing.

**Comment by salifou-root163** [comment]
Hello, as I mentioned, I have nothing in the logs, just an infinite loading.

https://github.com/desktop/desktop/assets/50051019/bf694915-55e4-4f63-893f-f758d2061fad

**Comment by steveward** [comment]
Can you share a few details about the server setup? Is it o2switch an actual Git hosting provider, or are you storing repos on a private server with your own setup? Generally for third-party services you will need to generate a token and then use that to authenticate -- see our guides here:

https://github.com/desktop/desktop/blob/development/docs/integrations/

It may be easiest to set up a new SSH key and use that to work with these repositories in GitHub Desktop depending on the setup you have. See this [guide for reference](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent).
