### ISSUE TITLE
Github Desktop should not use ADO PATs for authentication

### ISSUE THREAD

**Issue by webbsk** [desktop/desktop#18516]
### The feature request

Use the proper Microsoft authentication that everyone else uses instead of requiring ADO PATs that are insecure and dangerous.

### Proposed solution

I assume you can use something like Visual Studio credential provider or AAD auth but literally anything is better than ADO PATs.

**Comment by webbsk** [comment]
Specifically, ADO PATs encourage checking in to code bases which leads to security incidents. Currently this is the only authentication Github for Windows provides for using Visual Studio Online/ADO.

**Comment by niik** [comment]
:wave: we just shipped GitHub Desktop 3.4.2-beta2 to our [beta channel](https://desktop.github.com/beta/). This includes support for using [Git Credential Manager](https://gh.io/gcm). It's currently off by default but you can enable it in Settings under the advanced tab. We believe this will address the authentication problems outlined in this issue.

<img width="608" alt="Screenshot of Desktop's advanced preferences section with a highlight around the new option to enable Git Credential Manager" src="https://github.com/desktop/desktop/assets/634063/5d4da983-7663-49dd-bb7b-ce51ee9d2d3a" />

When Git Credential Manager (GCM) is enabled all credentials for third-party (i.e. Azure Devops, BitBucket, GitLab etc) will be handled, and stored, outside of GitHub Desktop. GCM supports browser-sign in to many popular services and will avoid the need to create personal access tokens (PATs). 

Please download our beta version from https://desktop.github.com/beta/ to give this a go and please report back with your experience. We'll be collecting feedback in our beta channel which will inform when we make this available to all users. Installing the beta version will not clear your preferences or tracked repositories and you can switch to the production version by simply downloading the latest version from https://desktop.github.com.
