### ISSUE TITLE
fetch prompt is bothersome to deal with when not saving passwords

### ISSUE THREAD

**Issue by orochi02** [desktop/desktop#18515]
### The feature request

try it yourself, seriously. its one of the most massive oversights in imo one of the best git clients.
sure, you may suggest saving passwords but that is just sidestepping the issue and not a real fix.

### Proposed solution

enable a check button to disable auto fetch

**Comment by niik** [comment]
Hey, thanks for reaching out! This looks very similar to https://github.com/desktop/desktop/issues/10687 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date with any development happening in that area.
