### ISSUE TITLE
Github Desktop does not recognize local changes

### ISSUE THREAD

**Issue by talhaali-2003** [desktop/desktop#18518]
### The problem

Hey, I just recently installed github on my new PC and whenever I clone a repository from my account and open it up in desktop in VS code any changes I made arent detected! When I connect to github through the terminal everything works normally but github desktop will not detect changes.

### Release version

Version 3.3.11 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Fresh install github desktop
2. Go to clone a repo upon startup
3. See if after opening up your project in VSCODE that changes are detected

### Log files

No log files for this!

**Comment by sergiou87** [comment]
Thanks for your report!

Could you post screenshots or a video showing the problem? I have no idea why this could happen 🤔
