### ISSUE TITLE
why is everyone getting an error?

### ISSUE THREAD

**Issue by pavlentei** [desktop/desktop#18512]
### The problem

for some reason everyone gets a 404 error when they follow the link to my repository

### Release version

GitHub Desktop 3.3.14

### Operating system

windows 10

### Screenshots

![photo1712831478](https://github.com/desktop/desktop/assets/110096482/046f73ed-811e-4321-935a-422614f98cd6)

**Comment by pavlentei** [comment]
незнаю

**Comment by steveward** [comment]
@pavlentei you'll need to reach out to [GitHub Support](https://support.github.com/) for assistance with GitHub Pages -- we aren't able to assist with that here.
