### ISSUE TITLE
Can't open Github Desktop due to "unrecoverable error"

### ISSUE THREAD

**Issue by woxi-sara** [desktop/desktop#18511]
### The problem

Starting suddely this afternoon, I can no long open let alone use Desktop. Once it loads, I get this error message:

RangeError: Invalid string length
    at u.<anonymous> (file:///app/renderer.js:2:1477037)
    at u.emit (node:events:517:28)
    at x (file:///app/renderer.js:2:634365)
    at R (file:///app/renderer.js:2:634195)
    at k.push (file:///app/renderer.js:2:634979)
    at u.push (file:///app/renderer.js:2:644799)
    at c (file:///app/renderer.js:2:663595)
    at u.a [as _transform] (file:///app/renderer.js:2:663281)
    at u._read (file:///app/renderer.js:2:645260)
    at u._write (file:///app/renderer.js:2:645099)

I've been using squash and merge pretty freely lately and I've read that this issue could be due to the length of those squashed commit messages. However, the issue persists across all repositories.

**Comment by steveward** [comment]
Thanks for the report @woxi-sara! Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by woxi-sara** [comment]
Here you go!
[2024-04-24.desktop.production.log](https://github.com/desktop/desktop/files/15110748/2024-04-24.desktop.production.log)

**Comment by sergiou87** [comment]
@woxi-sara Is it possible this only happens with a specific branch of a specific repo? The branch `sandbox` of the repo `prediction-os` maybe. I think it breaks when running `git log origin/sandbox..sandbox --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color --` on that branch 🤔

**Comment by woxi-sara** [comment]
It does seem to be most persistent on the sandbox branch. But I have also gotten that error on production, and on my migration-functions repo as well.

**Comment by woxi-sara** [comment]
Hi @sergiou87 any updates on this? It is still blocking me (particularly on the sandbox branch). Thanks.

**Comment by woxi-sara** [comment]
@sergiou87  any updates? Thanks!

**Comment by steveward** [comment]
@woxi-sara this has been previously reported in https://github.com/desktop/desktop/issues/15355 (the user was using squash and merge there as well). I'll bring this up for discussion in our team sync but at this time I don't have a good workaround for getting this working in GitHub Desktop. I'll take a look at reproducing it.

**Comment by steveward** [comment]
@woxi-sara we discussed this in our team sync this week and are looking into ways to prevent the app from crashing when this error occurs. 

There are a couple of workarounds you can use to see if that gets things working again in GitHub Desktop. If the problematic squashed commit is the most recent commit in your repository, you can amend the commit to change the commit message. See [this article.](https://docs.github.com/en/desktop/managing-commits/amending-a-commit-in-github-desktop). If the commit has already been pushed you will need to use the command line, as GitHub Desktop does not allow you to amend a commit that has been pushed to the remote repository. You will need to open the repository in the command line and run the following command:

`git commit --amend -m "your new commit message"`

If the problematic commit is further back in your repository's history you can use the rebase command to modify the commit message on the command line. There's a helpful guide [here](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message#amending-older-or-multiple-commit-messages) that walks through how to do that.  

If you run into any issues with those solutions (or if they don't resolve the issue), let us know.
