### ISSUE TITLE
skipped bytes in pushed images (0D)

### ISSUE THREAD

**Issue by kickofitall** [desktop/desktop#18519]
### The problem

While pushing images to the repository some bytes are skipped. In my test only `0D`. This leads to decoding errors with PNGs or screwed up JPGs.

### Release version

3.3.14 (x64)

### Operating system

Win10 x64

### Steps to reproduce the behavior

1. add image to repository
2. commit and push
3. compare the local file with the one in the repository

### Screenshots

**local version**
![github-desktop-logo_lokal](https://github.com/desktop/desktop/assets/3729807/aeec6359-b3de-429b-bee9-3250d3edbcfa)

**repository version (PNG decoding error)**
![github-desktop-logo_git](https://github.com/desktop/desktop/assets/3729807/f9638412-75d0-44ca-97c3-ad69b092fe4f)

**diff**
![github-desktop-logo_diff](https://github.com/desktop/desktop/assets/3729807/80cd073b-905a-4b52-baaa-9a28b7c021b5)

**Comment by Manchago** [comment]
![Uploading abstract.jpeg…]()
