### ISSUE TITLE
Git unable to clone public or private repositories

### ISSUE THREAD

**Issue by dreward** [desktop/desktop#18525]
Trying to clone the following public repository:
https://github.com/NVIDIA/cuda-samples/tree/master/Samples/5_Domain_Specific/nbody
I get an authentication errors and asked to log in again

**Comment by steveward** [comment]
@dreward you'll want to use the URL `https://github.com/NVIDIA/cuda-samples` to clone -- the one you're using will result in the clone failure you're encountering.

**Comment by dreward** [comment]
Thanks
