### ISSUE TITLE
Can no longer push or pull to repository 

### ISSUE THREAD

**Issue by travelertt** [desktop/desktop#1852]
### Description

After I updated GitHub Desktop to version 0.5.9, I'm unable to push or pull to my repo. I'm also unable to do the same in terminal.

### Version

**GitHub Desktop version:** 0.5.9

**OS version:** Mac 10.12.5

### Steps to Reproduce

Try to Fetch Origin, or Push.
Error popup with message:

> Error
> Authentication failed. You may not have permission to access the repositry. Open preferences and verify that you're signed in with an account that has permission to access this repository.
> 

I'm logged in. And I do have access to the repository. 

I was able to do access/push/pull the repository May 26, 2017. There has been no changes to my system. Or the repository settings.

I have tried signing out and signing back in with the app. Error still appears.

**Reproduces how often:** Now. 100%

### Logs

[desktop-production-logs.zip](https://github.com/desktop/desktop/files/1043037/desktop-production-logs.zip)

**Comment by niik** [comment]
@travelertt Could you run the command `git remote -v` in your repository folder and paste the output here?

Have you been building GitHub Desktop from source at any time since May 26th?

**Comment by jipexu** [comment]
Hi i have similar(perhaps) probleme after an upgrade (2 days ago) of MAc sierra 10.12.5 since i have those messages
on github desktop beta (0.5 9):
ERROR: Authentication error: Authentication required: You must have push access to verify locks
error: failed to push some refs to 'https://github.com/jipexu/npds_dune.git'

on github Hasty Things Done Hastily (223)
GIT ERROR
2017-06-01 11:41:10.264 GitHub Desktop Login[4336:181623] AskPass with arguments: (
    "/Applications/GitHub Desktop.app/Contents/MacOS/GitHub Desktop Login",
    "Username for 'https://github.com': "
)
2017-06-01 11:41:10.304 GitHub Desktop Login[4337:181629] AskPass with arguments: (
    "/Applications/GitHub Desktop.app/Contents/MacOS/GitHub Desktop Login",

huum i really lost .... any help thanks

**Comment by jipexu** [comment]
if i run this 

PowerBookSSDjpb:~ jpb$ git remote -v
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
PowerBookSSDjpb:~ jpb$

**Comment by jipexu** [comment]
and with BBEdit git log i have this error
fatal: could not read Username for 'https://github.com': Device not configured

**Comment by joshaber** [comment]
@jipexu Your errors seem to be about the older GitHub Desktop, while this repository is for issues with the new GitHub Desktop Beta. Please contact support support@github.com.

**Comment by jipexu** [comment]
this is also on this new  .... ? no ?
on github desktop beta (0.5 9):
ERROR: Authentication error: Authentication required: You must have push access to verify locks
error: failed to push some refs to 'https://github.com/jipexu/npds_dune.git'

**Comment by joshaber** [comment]
@jipexu It looks like that error comes from Git LFS. See https://github.com/git-lfs/git-lfs/issues/2219 for more info.

**Comment by jipexu** [comment]
thanks i will investigate - so where i have to post ? to not pollute this issue ?

**Comment by joshaber** [comment]
@jipexu I'd recommend opening an issue on the Git LFS repository.

**Comment by jipexu** [comment]
ok thanks

**Comment by travelertt** [comment]
ac	ucg7@svn-634.devcloud.hosting.acquia.com:ucg7.git (fetch)
ac	ucg7@svn-634.devcloud.hosting.acquia.com:ucg7.git (push)
origin	git@github.com:UCG/UCG7.git (fetch)
origin	git@github.com:UCG/UCG7.git (push)

**Comment by travelertt** [comment]
Pushing and Fetching working today, I don't know what changed to make it work now. I did upload a new public key to my account after this problem started yesterday. But, it didn't immediately fix the problem. Perhaps I need to wait for some sort of propagation?

**Comment by chrisgrande** [comment]
I'm being hit with this as well using Tower on the Mac, the old GitHub Desktop worked, it then auto updated (223) with a new version of git-lfs (2.2.1) and not it no longer works...

**Comment by joshaber** [comment]
Very odd!

It looks like there aren't any outstanding issues left, so I'm gonna close this.

**Comment by drakeet** [comment]
I am also using the old GitHub Desktop(v223) and faced the same note. I solved it. Try `rm .git/hooks/pre-push` and push again.

I love the old GitHub Desktop(v223) very much!

**Comment by j-f1** [comment]
@drakeet Please note that the old Desktop will be deprecated fairly soon; although you’ll still be able to use the classic app, it won’t get any more support or updates. If there’s something you don’t like about the new app, please open an issue and tell us about it!

**Comment by bphilipnyc** [comment]
Seeing this issue in GitHub Desktop 1.0.4 and Mac 10.13

**Comment by joshaber** [comment]
@bphilipnyc Could you open a new issue and fill out the issue template please? Thanks!

**Comment by bphilipnyc** [comment]
after installing Git LFS, this seems to resolve itself.  Removing the hooks did not have any impact for me.

**Comment by sumayaSalihs** [comment]
I had the same issue because I changed my username. Resigning in my GitHub Desktop up solved it. Try logging out and then logging back in if you made and major changes in your gitHub account.

**Comment by fho-wtag** [comment]
After facing the issue I found that I was signed out from github.com on github desktop. Singing in again solved the issue for me.

**Comment by LevanTsereteli** [comment]
Signing out and signing in again to the GitHub desktop solved the problem for me.
