### ISSUE TITLE
Tooltip for truncated tags in commit history entries

### ISSUE THREAD

**Issue by haykam821** [desktop/desktop#18526]
### The feature request

Currently, when more than one tag is present for a given commit, one tag is shown, while the others are unlabeled and hidden behind the first tag. There is no way to see the other tags without clicking into the commit and looking at the commit details panel for its list of tags. I believe that same full tag information should be available as a tooltip in the commit list.

### Proposed solution

I believe that having a tooltip in this situation would reduce developers' context-switching from moving focus from the commit list entry to the commit details.

### Additional context

![Visual demonstration of the issue](https://github.com/desktop/desktop/assets/24855774/e6e5884b-2946-49cf-aa35-1d34df9fb73a)

If this feature request is accepted, I would be interested in submitting a pull request to implement the feature.

**Comment by steveward** [comment]
Thanks for the issue @haykam821. We are tracking this in https://github.com/desktop/desktop/issues/9687 so I'm going to close this out and add your feedback there.

**Comment by steveward** [comment]
> If this feature request is accepted, I would be interested in submitting a pull request to implement the feature.

I'll bring this up with the team for discussion and get back to you -- thanks for your interest in contributing!

**Comment by steveward** [comment]
@haykam821 thanks again for your interest in contributing. I brought this up with the team, and there were some accessibility concerns around adding this as a tooltip. Due to these concerns we aren't looking to have this implemented at this time, but it will hopefully be something we can reconsider again in the future as we continue to improve the app.
