### ISSUE TITLE
"Reset to commit..." appears greyed out

### ISSUE THREAD

**Issue by Andrej730** [desktop/desktop#18524]
### The problem

It seems "Reset to commit..." button in commit context menu always appears greyed out if commits were pushed before.

Not sure if it's just me but I use `git reset` sometimes to reset to some old commit, so that all changes would become unstaged and  I could review and perhaps discard some of them (usually during testing or debugging). Since "Reset to commit" doesn't work I either use `git reset xxxxxx` in command line or I squash all commits and then undo (btw doesn't appear too if changes were already pushed but it does appear after squashing).

Would be nice if "Reset to commit" would either work in this situtation or would show some tooltip on hover so I could understand why it's locked.

![image](https://github.com/desktop/desktop/assets/9417531/ff3f287c-5bf1-49c5-8647-4af088ce1fe9)

### Release version

Version 3.3.15-beta1

### Operating system

Windows 11

**Comment by steveward** [comment]
@Andrej730 apologies for the delay in responding here. The `Reset to commit` option will only be available up to the most-recent pushed commit in your repository. See this [help article](https://docs.github.com/en/desktop/managing-commits/resetting-to-a-commit-in-github-desktop) for further details about this functionality.

**Comment by Andrej730** [comment]
@steveward but shouldn't there be a tooltip to make it more intuitive?

**Comment by mw108** [comment]
> @Andrej730 apologies for the delay in responding here. The `Reset to commit` option will only be available up to the most-recent pushed commit in your repository.

This doesn't seem to be always the case. Or there is a different reason why it is disabled? In all my repositories "Reset to Commit ..." is always grayed out, no matter how far I go back.

![image](https://github.com/user-attachments/assets/78f5ea43-8c58-480b-8fbb-a4db3c70c480)

**Comment by Andrej730** [comment]
> This doesn't seem to be always the case. Or there is a different reason why it is disabled? In all my repositories "Reset to Commit ..." is always grayed out, no matter how far I go back.

Are you sure commits from the screenshot are not yet pushed? 

![image](https://github.com/user-attachments/assets/5c1771f5-74f8-4af7-9316-dd04917a5a51)

**Comment by mw108** [comment]
Ok, I see. I misunderstood the function and description then. Is there a way to reset to a (pushed) commit using the GitHub desktop app?

**Comment by Andrej730** [comment]
> Ok, I see. I misunderstood the function and description then. Is there a way to reset to a (pushed) commit using the GitHub desktop app?

No.

**Comment by kokoskiwi** [comment]
> > Ok, I see. I misunderstood the function and description then. Is there a way to reset to a (pushed) commit using the GitHub desktop app?
> 
> No.

how else can i do it? @Andrej730

**Comment by Andrej730** [comment]
> how else can i do it? [@Andrej730](https://github.com/Andrej730)


@kokoskiwi 
Two options:
- using command line - use `git reset xxxxx` where `xxxx` is a parent commit to the one you want to reset
- using Github Desktop - sometimes when I'm lazy opening up command line and then I would make commits I want to reset as "not pushed".
	E.g. if you need to reset just the last commit, you can right click on it and use "Amend", then just keep the same commit description and commit it. Since it's timestamp changed, it's no longer pushed and you will be able to reset to the commit next to it.
	If you need to reset more than just one commit, sometimes it's possible to reorder them (works using drag'n'drop in Github Desktop) - then both commits also become not pushed and you can reset them.
