### ISSUE TITLE
Please add Brackets Support

### ISSUE THREAD

**Issue by prozachweb** [desktop/desktop#18521]
### The feature request

Github desktop does not currently support brackets as an external editor.

### Proposed solution

Could you please support brackets as an external editor for Github Desktop?

### Additional context

Brackets is free, lightweight, has its own set of hotkeys, supports opening folders, and it's simple. I would highly prefer to use Github Desktop, but I could use a built-in plugin in Brackets.

**Comment by steveward** [comment]
Thanks for the issue. Brackets is on our list of supported editors, see this document:

https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md

If you are on macOS you will need to ensure the command line shortcut is installed by going to `File` > `Install Command Line Shortcut`. If you installed Brackets with GitHub Desktop open you will need to restart the app to detect the new editor.

I'm going to close this out, but let me know if that doesn't get things working.

**Comment by aclight** [comment]
FWIW, the GUID used for Brackets on Windows might be incorrect:

https://github.com/desktop/desktop/blob/889a892d918ed3215b78ad6747861efb363e240a/app/src/lib/editors/win32.ts#L291-L297

After installing an older version of Brackets, its uninstall information was located under `{43086E55-5B37-4DA8-852F-EEC6C75ECFE9}`. I then installed the most recent version (2.1.3) and uninstall info for that version uses `{DECDF311-E886-4879-A6BF-39B2C7F07862}`.

I don't personally use Brackets and have no experience developing a TypeScript app, so I'm not prepared to create and test a proper PR for this change.
