### ISSUE TITLE
Get Version using Command Line

### ISSUE THREAD

**Issue by auxtern** [desktop/desktop#18529]
### The feature request

Is there a way to find out the version of Github Desktop installed using command line?

This is a simple thing but can be used to check whether the application is available or not just by running the "github" command in the terminal/cmd.

### Proposed solution

For example, if you carry out the command

github '-version' or similar can display the currently installed desktop version of github.

![github](https://github.com/desktop/desktop/assets/11439797/f0ef3a44-8a1a-43c1-8955-65e6f982c3fc)

**Comment by steveward** [comment]
@auxtern thanks for the issue. There isn't a way to query the version using the command line -- are you only wanting this to check if the app is running? There's likely a way to script this using available tools like PowerShell without something needing to be directly added to GitHub Desktop.

**Comment by auxtern** [comment]
Thank you for your answers. I don't want to check the application is running or not. But want to check whether it is installed or not and get the version. Is it possible to get the same version information as in this control panel:
![github-2](https://github.com/desktop/desktop/assets/11439797/0ab04bcf-7901-495f-998f-15bf0ab9b14b)

**Comment by auxtern** [comment]
For now you can use power shell:
![github](https://github.com/desktop/desktop/assets/11439797/2308018d-70e1-4fbe-8de8-a5cc27a75774)


**app.ps1**
```
param (
    [string]$programName
)

if (!([Diagnostics.Process]::GetCurrentProcess().Path -match '\\syswow64\\')) {
  $uninstallPath = "\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\"
  $uninstallWow6432Path = "\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\"

  $results = @()

  if (Test-Path "HKLM:$uninstallWow6432Path") { $results += Get-ChildItem "HKLM:$uninstallWow6432Path" }
  if (Test-Path "HKLM:$uninstallPath") { $results += Get-ChildItem "HKLM:$uninstallPath" }
  if (Test-Path "HKCU:$uninstallWow6432Path") { $results += Get-ChildItem "HKCU:$uninstallWow6432Path" }
  if (Test-Path "HKCU:$uninstallPath") { $results += Get-ChildItem "HKCU:$uninstallPath" }

  $filteredResults = $results | ForEach-Object {
    if ($_.PSPath) {
        try {
            $itemProperty = Get-ItemProperty $_.PSPath -ErrorAction Stop
            return $itemProperty
        } catch {
            return $null
        }
    } else {
        continue
    }
  } | Where-Object {
    $_.DisplayName -and !$_.SystemComponent -and !$_.ReleaseType -and !$_.ParentKeyName -and ($_.UninstallString -or $_.NoRemove)
  } | Sort-Object DisplayName

  $filteredResults | ForEach-Object {
    if ($_.DisplayName -eq $programName) {
        "$($_.DisplayName)||$($_.DisplayVersion)"
    }
  }

}
```

**Comment by steveward** [comment]
I'll close this out as this isn't something we've heard previous feedback about, but thanks for sharing that script for others to make use of!
