### ISSUE TITLE
Merging a pull request corrupts RC2 file

### ISSUE THREAD

**Issue by ajtruckle** [desktop/desktop#18527]
### The problem

I had a branch called Scintilla which I created a pull request for in GitHub Desktop.

Then, in my browser I accepted the pull request (I have not deleted the branch).

Then I went to my master branch in GD and pulled the request down. It all appeared to work.

But, when I went to compile in VS2022 it had an issue with the RC2 file.

I opened the RC2 file in Notepad and it had gibberish. It was UTF16- LE encoded.

I went to my physical backup of the Scintilla branch and replaced the file. My local version is not corrupted and is still UTF-16 LE encoded. Now VS2022 compiles.

I am very concerned that the RC2 file I ended up with was not usable and don't want this to happen again.

Thank you.

### Release version

Version 3.3.14 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

See previous comments.

### Log files

[2024-04-28.desktop.production.log](https://github.com/desktop/desktop/files/15143038/2024-04-28.desktop.production.log)

**Comment by steveward** [comment]
@ajtruckle thanks for the report. I don't see how this would have been caused by GitHub Desktop, but Git does have issues diffing UTF-16 files unless you specifically configure your `.gitattributes` file. That still wouldn't result in the file becoming corrupted, though. If you're able to reproduce this in a test repository we can dig into it further.

**Comment by ajtruckle** [comment]
Actually, the merge was done by GitHub online. That is where I merged. Then I pulled it down.

I had already configured the file you mentioned in the root of my repository:

```
*.rc2 text
```

Although it makes no difference. I will can't view it in GitHub Desktop anyway.
