### ISSUE TITLE
Bring Back Visual Branch Trees?

### ISSUE THREAD

**Issue by mikeytag** [desktop/desktop#1853]
The newest Beta for GitHub Desktop did away with the view that shows the current branch you are on vs another one. I found this view incredibly useful to know if I need to update from the Default Branch or another one. Any way to bring it back? Attached is the view from the old Github Desktop for Mac that I'm talking about.

![screen shot 2017-05-31 at 3 41 27 pm](https://cloud.githubusercontent.com/assets/219403/26657305/e5df6ad4-4617-11e7-853c-9c8a42fb1865.png)

**Comment by joshaber** [comment]
Thanks for opening this up! We're tracking this over at #1634, so feel free to follow along there.

**Comment by mikeytag** [comment]
Thanks @joshaber! Sorry about that. I should have searched through the open issues a little harder. ;-)

**Comment by joshaber** [comment]
No worries 😄

**Comment by heshamelmasry77** [comment]
where is the tree :S :S the new desktop is shit honestly

**Comment by AbowlofStew** [comment]
visual branch trees was the only reason i ever used desktop I would use the I would use git bash for everything but use git desktop top see the branch changes it was really useful please bring it back

**Comment by kihot122** [comment]
Is there any update on whether this feature might be back in Desktop?
