### ISSUE TITLE
Streamline file uploads and file deletions

### ISSUE THREAD

**Issue by Kusanagi-Kasuga** [desktop/desktop#18537]
### The feature request

It is very complicated to have to upload each file, because it does not allow me to upload a folder with files, you should complement it.
Regarding the deletion of files; implement it, it is difficult to have to delete approximately 100 files that are of no use to me.

Find a way to make it more accessible.

### Proposed solution

Find a way to make it more accessible. Allow to upload folders with files and please put multiple selection to delete several files, and your executable is very horrible to work on it is everything but github.

**Comment by steveward** [comment]
@Kusanagi-Serizawa thanks for the issue. GitHub Desktop doesn't have an "upload" function, you commit your changes in the app and then can push them up to GitHub. You can commit multiple files at a time, you don't need to push each file individually. 

If you have specific examples or questions about how to use GitHub Desktop I'd be happy to help further. You can also find our help docs [here](https://docs.github.com/en/desktop).
