### ISSUE TITLE
Stash created outside application doesn't show up (i.e. not named !!GitHub_Desktop<branch>)

### ISSUE THREAD

**Issue by aybe** [desktop/desktop#18534]
### The feature request

**Version:**

3.3.15-beta1 (x64)

Suppose the following scenario:
- you have 10 files waiting to be committed
- you only want to stash 5 specific files, not possible from GitHub Desktop so you use Visual Studio Code
- the stash created is visible in Visual Code
- the stash created is **not** visible in GitHub Desktop

**Example:**

Created the stash in Visual Studio Code but it doesn't show up:

![image](https://github.com/desktop/desktop/assets/1537591/bceb32fc-f077-4383-9b7d-0a35e8b6ec21)

Now as I see the image, I realize there is `!!GitHub_Desktop<branch>`, renaming it works: 🥳

![image](https://github.com/desktop/desktop/assets/1537591/0bcaa552-d827-49b5-b4b5-a8800393b098)

### Proposed solution

Can the software show up stashes it didn't create itself?

and/or

Could selectively stashing files be possible from the software itself?

Thanks!

**Comment by steveward** [comment]
Thanks for the issue @aybe. This behavior is per-design, see https://github.com/desktop/desktop/issues/6107 for our reasoning around choosing this implementation.

I'm going to close this in favor of https://github.com/desktop/desktop/issues/12699 which is requesting a similar feature.
