### ISSUE TITLE
Stuck on "Refreshing repository"

### ISSUE THREAD

**Issue by Is0kaze** [desktop/desktop#18541]
### The problem

It was working excellent until I had problems with my hard drive leading me to format the computer, since then the program has not worked properly, reinstalling it does not solve the problem

Also for some reason the CPU starts working at 99% when the repository is refreshing.
### Release version

3.3.14

### Operating system

Windows 10

### Log files

[2024-05-02.desktop.production.log](https://github.com/desktop/desktop/files/15182398/2024-05-02.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the issue @Is0kaze. I'm seeing a few errors in the log file:

```
Error: Cannot update an account which doesn't have a token: Is0kaze
```

```
2024-05-02T00:06:17.285Z - warn: [ui] Failed trying to find Git on PATH
Error: Command failed: C:\Windows\System32\where.exe git
```

Can you try logging out and then logging back in to GitHub Desktop to see if that gets things working for you?

**Comment by Is0kaze** [comment]
> Thanks for the issue @Is0kaze. I'm seeing a few errors in the log file:
> 
> ```
> Error: Cannot update an account which doesn't have a token: Is0kaze
> ```
> 
> ```
> 2024-05-02T00:06:17.285Z - warn: [ui] Failed trying to find Git on PATH
> Error: Command failed: C:\Windows\System32\where.exe git
> ```
> 
> Can you try logging out and then logging back in to GitHub Desktop to see if that gets things working for you?

I tried everything and nothing worked, in the end I had to delete and reinstall the repository from scratch which solved the problem (although it was a headache to download back the repository which weighs about 15 GBs).

anyway thanks for helping me!
