### ISSUE TITLE
Failing Build due to regeneratorRuntime

### ISSUE THREAD

**Issue by hjobrien** [desktop/desktop#1854]
### Description
Following the setup and building desktop instructions in setup.md  fails while running `npm start` with the error:
```
/Users/Hank/GitHub/desktop/dist/GitHub Desktop-dev-darwin-x64/GitHub Desktop-dev.app/Contents/Resources/app/main.js:8175
    return __awaiter(this, void 0, void 0, regeneratorRuntime.mark(function _callee() {
                                           ^

ReferenceError: regeneratorRuntime is not defined
    at Object.reportError (/Users/Hank/GitHub/desktop/dist/GitHub Desktop-dev-darwin-x64/GitHub Desktop-dev.app/Contents/Resources/app/main.js:8175:44)
    at process.<anonymous> (/Users/Hank/GitHub/desktop/webpack:/app/src/main-process/main.ts:94:14)
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:300:26)
```

### Version

**GitHub Desktop version:** 0.5.9
**Commit:** 11b3ec1def362e8507f5312c2bab9a270003ac06
**OS version:** macOS 10.12.5
Node, npm and python versions all exactly match setup.md

### Steps to Reproduce

1. download a fresh copy of desktop/desktop repo
2. follow instructions in `docs/contributing/setup.md`
3. after running `npm start` the error occurs

**Expected behaviour:** development build of application should launch

**Actual behaviour:** reference error causes a fatal exception which terminates the launch process

**Reproduces how often:** 100%

### Logs:
 no log generated after failed build

#### Additional Information:
This seems like some sort of missing dependency in package.json so `npm install` didn't grab it, but the error persists after manually running `npm install regenerator-runtime`. I read that there was something with typescript and async/await back in August (#241) but I'm not sure if that is still relevant.

**Comment by shiftkey** [comment]
Not sure what's happening here, but here's couple of similar issues for Electron projects - seems to be related to webpack but also very vague:

- https://github.com/electron-userland/electron-builder/issues/1570
- https://github.com/uber/deck.gl/issues/231

**Comment by arusakov** [comment]
I faced this error. You don't need babel for your electron related scripts.

**Comment by hjobrien** [comment]
well I'm still confused then, because I tried uninstalling babel but the error persists. More googling indicates that this is tied to babel-polyfill, so are you saying that electron bundles babel internally or that it supports similar functionality.

**Comment by arusakov** [comment]
@hjobrien
Show me webpack config that you use for electron part of application

**Comment by shiftkey** [comment]
@arusakov the only babel plugin we use is [here](https://github.com/desktop/desktop/blob/68a6f481f9f3f890de4779239f7a5af368d0be69/app/webpack.production.js#L8)

**Comment by hjobrien** [comment]
@arusakov 
so there isn't a `webpack.config` file in the `node_modules/electron` folder, but there are a couple config files that seem to deal with babel, specifically this one in [fork-ts-checker-react-babel-karma-gulp](https://gist.github.com/hjobrien/7115ade9ee197afdf4dd00fb4563cfd6) and one in [react-babel-karma-gulp](https://gist.github.com/hjobrien/aec3f7b9ae0a3be45b70c0ae2e8cd25e).

**Comment by joshaber** [comment]
@hjobrien Were you ever able to figure this out? I can't reproduce this locally.

**Comment by hjobrien** [comment]
@joshaber I haven't figured it out yet, but I found this babel [issue](https://github.com/babel/babel/issues/4107) that I think might be related, so I'm looking into it. It is confusing that it seems un-reproducable though, which makes me think it could be a local thing, though I'm having trouble figuring out what that could be.

**Comment by hjobrien** [comment]
are there any differences in the output of `npm run build:dev` on your computer @shiftkey (here's [mine](https://gist.github.com/hjobrien/e3e1d36856897e981a077a908c8b1693)). I'm a little new to webpack, so I wonder if I'm not spotting some error which is causing my regenerator problems?

**Comment by shiftkey** [comment]
@hjobrien that output all looks as expected

**Comment by hjobrien** [comment]
Okay I fixed it. I was cleaning out some files from my home directory and I suspect I had an old cache somewhere, an old .npm folder, or an old .babelrc file which was causing the error. I can't say exactly which file it was that fixed it, but its working now so I'm going to close this
