### ISSUE TITLE
Unable to clone bigger repositories

### ISSUE THREAD

**Issue by SanjaySiddharth** [desktop/desktop#18550]
### The problem

Hey team !

I was trying to clone this repository "https://github.com/WeblateOrg/weblate.git" to my system and during the process of downloading it , I received an fatal error and the cloning gets cancelled.
The error I received is :
```
Cloning into 'D:\opensource\PROPER\weblate'...
remote: Enumerating objects: 741948, done.        
remote: Counting objects: 100% (4175/4175), done.        
remote: Compressing objects: 100% (811/811), done.        
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 9 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

Would you like to retry cloning ?
```
Please help me out with this issue .

### Release version

Version 3.3.14 (x64)

### Operating system

Windows 10 Pro

### Steps to reproduce the behavior

1. Go to "https://github.com/WeblateOrg/weblate"
2. Click on the code button and press on the github desktop option.
3. Once the desktop app opens up , choose a the location and click on clone

### Log files

[2024-05-03.desktop.production.log](https://github.com/desktop/desktop/files/15202681/2024-05-03.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the issue @SanjaySiddharth. Unfortunately there isn't anything GitHub Desktop can do about clone timeouts, we're just relaying the underlying Git operations which are timing out.

There are some HTTP timeout config operations that may help, or at lease provide additional diagnosis about the timeout. One user previously had success with these commands:

`git config --global http.lowSpeedLimit 1000`
`git config --global http.lowSpeedTime 20`

The `lowSpeedLimit` configures the minimum bytes per second, and the `lowSpeedTime` is the number of seconds. If the operation is lower than that threshold for the set time it will timeout. Adjusting those values may help with timeouts.

If neither of those suggestions work it may be worth trying to set [up a SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh), which some users have had more success with when encountering network issues. You could then clone the repository using the SSH remote.

**Comment by SanjaySiddharth** [comment]
Thank you @steveward  ! This fix worked for me !
