### ISSUE TITLE
Can't fetch from github repository with github desktop.

### ISSUE THREAD

**Issue by Fatima0527** [desktop/desktop#18553]
Hi,
I can’t fetch/ pull or push repository in the GitHub desktop. The fetch origin says never fetched and I also get an error.

The operating system 
macOS 
![IMG_0288](https://github.com/desktop/desktop/assets/112697120/49b07634-3941-4542-bf94-862af7a747e9)

**Comment by steveward** [comment]
@Fatima0527 thanks for the issue. It looks like there may be an issue with your local repository. Could you open in the repository in the terminal and run the command `git fsck`? Let me know the output of that command -- it should give us more info about the issues you're experiencing.

**Comment by Fatima0527** [comment]
Hi, thanks for your response @steveward, the problem is solved. I deleted the repository from my laptop than re clone.

**Comment by steveward** [comment]
I'm glad to hear things are working now.
