### ISSUE TITLE
Ctrl + Shift + A not working after installing ARC Browser

### ISSUE THREAD

**Issue by milan-sahana** [desktop/desktop#18552]
### The feature request

Ctrl + Shift + A not working after installing ARC Browser, even after uninstalling the Browser too.

### Proposed solution

Ctrl + Shift + A not working after installing ARC Browser, even after uninstalling the Browser too. If any one have any solution please comment.

**Comment by Nukiver** [comment]
Thats because Arc creates a link on your desktop with a hotkey shortcut integrated.
When uninstalling, the shortcut is not deleted -> CTRL + SHIFT + A is still occupied by the shortcut on the desktop. 

Solution:
Change the shortcut of the link or delete the shortcut of arc. 

@ arc devs: Maybe integrate the deletion of the link on uninstall / not integrate the shortcut to have a hotkey.

**Comment by milan-sahana** [comment]
> Thats because Arc creates a link on your desktop with a hotkey shortcut integrated. When uninstalling, the shortcut is not deleted -> CTRL + SHIFT + A is still occupied by the shortcut on the desktop.
> 
> Solution: Change the shortcut of the link or delete the shortcut of arc.
> 
> @ arc devs: Maybe integrate the deletion of the link on uninstall / not integrate the shortcut to have a hotkey.

not working after deleting the shortcut too, I had reinstalled the Github desktop then only CTRL + SHIFT + A works.

**Comment by Nukiver** [comment]
> > Thats because Arc creates a link on your desktop with a hotkey shortcut integrated. When uninstalling, the shortcut is not deleted -> CTRL + SHIFT + A is still occupied by the shortcut on the desktop.
> > Solution: Change the shortcut of the link or delete the shortcut of arc.
> > @ arc devs: Maybe integrate the deletion of the link on uninstall / not integrate the shortcut to have a hotkey.
> 
> not working after deleting the shortcut too, I had reinstalled the Github desktop then only CTRL + SHIFT + A works.

But that means Arc was not the only program holding back your CTRL + SHIFT + A
I had the same issue with the shortcut and the link was the problem for me → I don't have GitHub desktop installed; I also don't know myself around the program, so maybe check out the settings or, if GitHub desktop creates a link on your desktop on install, check that out. Arc definitely blocks CTRL + SHIFT + A with the link and upon deleting the link, for me, everything works fine.

Edit: After the link deletion, a PC restart might help aswell

**Comment by niik** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!

**Comment by nojaf** [comment]
I have this in vscode and JetBrains products as well. Did anyone ever found a solution for this?
Reboot did not solve anything for me.

**Comment by ajaykumarn3000** [comment]
> I have this in vscode and JetBrains products as well. Did anyone ever found a solution for this? Reboot did not solve anything for me.

1. Find a **Arc Browser icon** (maybe a shortcut of Arc on desktop)
2. **Right click** and Go to **properties**
3. Change the **Shortcut key** to whatever you like
<img width="277" alt="image" src="https://github.com/desktop/desktop/assets/104309385/ba6102d1-2744-434a-b7ba-a70fabe88f90">

**Comment by RealHaywoodJ** [comment]
### SOLVED/FIXED
/
\


> FULL GUIDE BELOW


/
\

**_I wanted to give anyone who maybe having issues with this issue in the Future that may be scouring the internet or using AI (something I tried) looking for a fix._** 

`I have provided the Fix Below (Outlined Step By Step 1-5)`

STEP #1 Download **EVERYTHING** Program [I Provided the Secure Link Below to "VoidTools.com" the OG Developer]

(This is an Offline Local File Explorer/File Search Tool [_This application will help you search your entire computer for the file that we will be hunting_]) [https://www.voidtools.com/downloads/](url)

STEP #2 After Install Completes, Type in "ARC.lnk" into the Everything Search Bar at Top.

STEP #3 You will/should see the ARC.lnk pop up, you will then right click on it, then select Properties.

STEP #4 Highlight on the Ctrl+Shift+A (Shortcut Input) Then delete it. It will then indicate (None) if on Windows, Now Click Apply and OK. You Can now Close out of the Properties Tab and Close Everything Browser/File Explorer.

STEP #5 Re-Open GitHub Desktop and now try to use the Shortcut Crtl+Shift+A ((It should now work without issue))



`--OPTIONAL-- Without EVERYTHING (Only If you dont want to use Everything.exe File Explorer)
`


STEP #1 You can try to search for the Arc.lnk Shortcut/File using Windows File Explorer then repeat steps #3 thru #5


### PLEASE NOTE:

> Do not use any other link for downloading the recommended program (Everything) other than the official link of which I provided above, but if you dont feel safe using that link, you can simply Google (Everything by Void Tools)

**Comment by RealHaywoodJ** [comment]
I also crossposted this to the GitHub SubReddit

[https://www.reddit.com/r/github/comments/1lqvqu5/github_desktop_issue_conflict_trying_to_open_repo/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button](url)
