### ISSUE TITLE
Get an error when installing on CENTOS7 with error message: "Invalid version flag: or"

### ISSUE THREAD

**Issue by vharihar2** [desktop/desktop#18551]
I followed the instructions at https://www.matthewthom.as/mirrors/#github-desktop to install Gitgub-desktop on my CENTOS7 Linux system.

I wasn't able to import the GPG key, kept getting an error msg "key 1 import failed". I tried several workarounds, none seemed to work. Eventually I disabled the GPG checking with "yum --nogpgcheck install ..." (even though not recommended, I admit) and that seemed to go ahead. But down the line, it failed with the following error:

```
...
(6/6): epel/x86_64/primary_db                              | 7.0 MB   00:45     
Resolving Dependencies
There are unfinished transactions remaining. You might consider running yum-complete-transaction, or "yum-complete-transaction --cleanup-only" and "yum history redo last", first to finish them. If those don't work you'll have to try removing/installing packages by hand (maybe package-cleanup can help).
--> Running transaction check
---> Package github-desktop.x86_64 0:3.3.12.linux2-1 will be installed
Error: Invalid version flag: or

```
How do I resolve this?

**Comment by steveward** [comment]
@vharihar2 thanks for the issue. For assistance with the unofficial Linux fork I'd recommend opening an issue directly in the fork, as we don't provide support for that here. You can find that issue tracker here:

https://github.com/shiftkey/desktop/issues

I'm going to close this out.
