### ISSUE TITLE
git push isn't working

### ISSUE THREAD

**Issue by RamonaTigier** [desktop/desktop#18569]
### The problem

Updated to 3.3.15 (x64) today 
After update I tried to push a commit, nothing happens "Hold on..."
Pushing via cmd is possible.

### Release version

3.3.15 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. commit
2. click push

### Log files

[2024-05-08.desktop.production.log](https://github.com/desktop/desktop/files/15251247/2024-05-08.desktop.production.log)

**Comment by niik** [comment]
👋 sorry to hear you're having problems pushing. We are investigating and we'd appreciate if you could run `git remote -v` in the affected repo and share the output (redacting if necessary)

**Comment by RamonaTigier** [comment]
Hi, 
thank you for feedback. 
when running the command I see following:
`R:\Unreal Engine\Unreal Projects\ClementineOnline>git remote -v
origin  https://github.com/RottenFuture/ClementineOnline.git (fetch)

origin  https://github.com/RottenFuture/ClementineOnline.git (push)`

![image](https://github.com/desktop/desktop/assets/8641007/0eaec807-ffcd-4f0b-bab6-eef5cd9be6c6)

**Comment by niik** [comment]
@RamonaTigier We're preparing a new release which hopefully addresses this issue and at the very least should give us more data to troubleshoot. We expect to publish this to our beta channel in a little bit and we'd really appreciate it if you could try it out once it's shipped so that we know if we can go ahead and release that to everyone.

We'll reply back here as soon as the update has shipped with instructions on how to get the latest release.

**Comment by niik** [comment]
@RamonaTigier We've just published 3.3.16-beta1 and would appreciate if you could download it from https://desktop.github.com/beta/ and give it a go and report back to us with the results.

If you're still not able to push please attach a log file again so that we can troubleshoot further

**Comment by tidy-dev** [comment]
@RamonaTigier We have released the changes in beta to 3.3.16, but we do a slow rollout so you may not see an automatic update until it completes over the next few days. However, you can download the latest at https://desktop.github.com/ if you would like it sooner.

We would love an update on whether you are still see this issue in the new version.

**Comment by tidy-dev** [comment]
We are still seeing reports of this and are tracking under. https://github.com/desktop/desktop/issues/18579 

Could you confirm if your repository is using Git LFS?

**Comment by RamonaTigier** [comment]
Yes, that's right, I use git lfs for large files.

**Comment by niik** [comment]
@RamonaTigier thanks, we fixed an issue related to Git LFS in version 3.3.17. Please make sure you're on the latest version and let us know if that solves your issue

**Comment by RamonaTigier** [comment]
![image](https://github.com/desktop/desktop/assets/8641007/3770a6fb-88e1-4fbb-9d01-101b3887f87d)
tried beta 3.3.18. 
With that version, it was possible to pull and push.

[2024-05-10.desktop.beta.log](https://github.com/desktop/desktop/files/15271026/2024-05-10.desktop.beta.log)

**Comment by niik** [comment]
Great, thanks for reporting back and sorry for the inconvenience!

**Comment by RamonaTigier** [comment]
Thank you for fast fixing it!

**Comment by RahimovAbdurahmon** [comment]
Hi, I am pushing an empty repository, it load for a long time but does not work. Is there any solution for it
