### ISSUE TITLE
Unable to sign-out or sign-in in github desktop

### ISSUE THREAD

**Issue by sanketthomre** [desktop/desktop#18566]
### The problem

When I am trying to pull any changes it gives me error as:
Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.

But when I go back to account settings 
![image](https://github.com/desktop/desktop/assets/35454550/b237f0c6-e4b2-4024-a177-7817a92260aa)

Not allowing me signout.
![image](https://github.com/desktop/desktop/assets/35454550/9bf2daf3-9425-4657-a5b2-28256f084da9)

### Release version

Version 3.3.14 (x64)

### Operating system

Windows 11

**Comment by steveward** [comment]
@sanketthomre thanks for the issue. This could just be a problem with the token GitHub Desktop stores for authentication. Have you tried logging out and logging back in?

If that does not get things working, it would be helpful if you could send over the log file from GitHub Desktop. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by sanketthomre** [comment]
Hi,
As the sign in/sign out option was not available, I have re-installed the github desktop and did the sign in and it worked now.
I am not sure why re-installation was required
Thanks,
Sanket
________________________________

**Comment by steveward** [comment]
Glad to hear this is resolved, I'm going to close this out.
