### ISSUE TITLE
Unable to authenticate in azure dev ops using Personal Access Token

### ISSUE THREAD

**Issue by guilhermeaugvieira** [desktop/desktop#18568]
### The problem

When try to authenticate the following error is presented in application interface

![image](https://github.com/desktop/desktop/assets/50804184/e356802f-b06b-4cf2-b539-f9678bb7c5ab)

### Release version

3.3.15

### Operating system

Windows

### Steps to reproduce the behavior

1. Try to fetch origin from any azure dev ops repository

### Log files

[2024-05-08.desktop.production.log](https://github.com/desktop/desktop/files/15250332/2024-05-08.desktop.production.log)

### Additional context

Downgrading the version to 3.3.14, the same error doesn't happen

**Comment by guilhermeaugvieira** [comment]
Some informations where replaced in log file by security

**Comment by Onik97** [comment]
Same Issue here, started happening once I updated my Desktop

**Comment by sergiou87** [comment]
Thank you for your reports, we're looking into this 🕵

**Comment by sergiou87** [comment]
We have deployed a test build that hopefully fixes this. Could you give it a try? Here you have the download links:

- macOS (Intel): https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.15-a629673f/GitHubDesktop-x64.zip
- macOS (Apple silicon): https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.15-a629673f/GitHubDesktop-arm64.zip
- Windows: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.15-a629673f/GitHubDesktopSetup-x64.exe
- Windows (MSI): https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.15-a629673f/GitHubDesktopSetup-x64.msi

**Comment by sergiou87** [comment]
( ⚠ I deleted a previous message where I posted the wrong links pointing to v3.3.15 🤦‍♂ Sorry about that, this comment has the links to the right version ⚠ )

@guilhermeaugvieira @Onik97  We have deployed a test build (3.3.16-test1) that hopefully fixes this. Could you give it a try? Here you have the download links:

- macOS (Intel): https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.16-test1-8ca474ae/GitHubDesktop-x64.zip
- macOS (Apple silicon): https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.16-test1-8ca474ae/GitHubDesktop-arm64.zip
- Windows: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.16-test1-8ca474ae/GitHubDesktopSetup-x64.exe
- Windows (MSI): https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.16-test1-8ca474ae/GitHubDesktopSetup-x64.msi

**Comment by guilhermeaugvieira** [comment]
I did the test in windows environment, it works perfectly @sergiou87 

Waiting anxiously for the 3.3.16 release

**Comment by niik** [comment]
@guilhermeaugvieira @Onik97  We've just published 3.3.16-beta1 and would appreciate if you could download it from https://desktop.github.com/beta/ and give it a go and report back to us with the results.

If you're still not able to push please attach a log file again so that we can troubleshoot further

**Comment by guilhermeaugvieira** [comment]
I'll test and report here if it's ok

**Comment by guilhermeaugvieira** [comment]
It's ok, working correctly @niik

**Comment by wgotti-iqmetrix** [comment]
It's indeed working with the **Version 3.3.16-beta1** from https://desktop.github.com/beta/. Before that, with 3.3.15, I couldn't access my Azure Repos

**Comment by tidy-dev** [comment]
@guilhermeaugvieira and @wgotti-iqmetrix . We have released the fix to our production channel in 3.3.16, but we do a slow rollout so you may not see an automatic update until it completes over the next few days. However, you can download the latest at https://desktop.github.com if you would like it faster.

Thank you for the prompt report and testing our fixes. ❤

**Comment by Onik97** [comment]
@tidy-dev @sergiou87 All good now, thank you 
![image](https://github.com/desktop/desktop/assets/18009030/9a2dc27f-15a3-45dd-bc17-a07c9ec00d04)

**Comment by wangkkyy** [comment]
Still the same problem on Version 3.3.17-beta1 (x64).

**Comment by niik** [comment]
@wangkkyy Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by wangkkyy** [comment]
> @wangkkyy Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.
> 
> The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

Here is the log.
[2024-05-10.desktop.production.log](https://github.com/desktop/desktop/files/15269780/2024-05-10.desktop.production.log)

**Comment by niik** [comment]
@wangkkyy I see that you're using repositories over unencrypted http, we fixed a regression related to this scenario in #18589 and we've released it to our beta channel. Could you please try installing our beta version from https://desktop.github.com/beta/ and try again?

**Comment by wangkkyy** [comment]
> @wangkkyy I see that you're using repositories over unencrypted http, we fixed a regression related to this scenario in #18589 and we've released it to our beta channel. Could you please try installing our beta version from https://desktop.github.com/beta/ and try again?

This works. Thanks a lot.
