### ISSUE TITLE
git push isn't working

### ISSUE THREAD

**Issue by Taiizor** [desktop/desktop#18579]
### The problem

Updated to 3.3.16-beta1 (x64) today
After update I tried to push a commit, nothing happens "Hold on..."
Pushing via cmd is possible.

### Release version

3.3.16-beta1

### Operating system

Windows 11 24H2

### Steps to reproduce the behavior

1. Commit
2. Click push

### Log files

[2024-05-09.desktop.beta.log](https://github.com/desktop/desktop/files/15256105/2024-05-09.desktop.beta.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/41683699/d5bce399-2a28-4e3d-974e-5098a0e6a81f)

**Comment by tidy-dev** [comment]
@Taiizor We are investigating and we'd appreciate if you could run `git remote -v` in the affected repo and share the output (redacting if necessary)

Or opening Repository -> Repository Settings and share a screenshot of the Remote section of that dialog. Thank you!

**Comment by Taiizor** [comment]
![image](https://github.com/desktop/desktop/assets/41683699/93e639a2-236b-4ede-a172-7c54aea17f95)
![image](https://github.com/desktop/desktop/assets/41683699/f71cf37b-ac31-4c29-b264-b1208d1bc8df)

Not: When I couldn't do it through GitHub Desktop, I used the `git push` command.

**Comment by tidy-dev** [comment]
Thank you for that. These may be long shots.

- Would you mind logging out and back in in desktop?
- If above does not work, try cloning your repository again?

**Comment by tidy-dev** [comment]
^ Just a note, the above suggestions are likely not to help because I forked your repo and tried a simple commit and push and it is failing.

**Comment by Taiizor** [comment]
I tried to commit with 4 different repositories, and I couldn't commit to Sucrose only.
The repositories were two private and two public.

**Comment by ghostWDFR** [comment]
> I tried to commit with 4 different repositories, and I couldn't commit to Sucrose only. The repositories were two private and two public.

I guess I have same issue.

7 hours ago I made commit on a prev. version and everything was just fine, but after update I can't make commits :c

**Comment by tidy-dev** [comment]
Thank you for trying! We believe we have narrowed down the issue and it is only impacting Git LFS repos. @ghostWDFR is your repository a Git LFS repo as well?

**Comment by Taiizor** [comment]
> Thank you for trying! We believe we have narrowed down the issue and it is only impacting Git LFS repos. @ghostWDFR is your repository a Git LFS repo as well?

The two public repositories I tried were previously using Git LFS but have been disabled later. I don't think this error is related to LFS. Because there was an issue with Sucrose but not with my other repository.

**Comment by tidy-dev** [comment]
@Taiizor or @ghostWDFR Would either of you mind [trying the latest beta (3.3.17-beta1)](https://desktop.github.com/beta/) and letting us know if it gets things working for you?

**Comment by ghostWDFR** [comment]
> @Taiizor or @ghostWDFR Would either of you mind [trying the latest beta (3.3.17-beta1)](https://desktop.github.com/beta/) and letting us know if it gets things working for you?

Hello!

I tried to check updates but it say that I'm using latest version, so I still can't do anything

![image](https://github.com/desktop/desktop/assets/85042983/5bb7a0a1-9831-43d2-a138-f54651e62931)

**Comment by niik** [comment]
@ghostWDFR Could you please try holding down <kbd>Alt</kbd> (or <kbd>Option</kbd> if you're on macOS) on your keyboard and then clicking on the `Check for updates` button (it'll change its text to Ensure latest version). Thanks!

**Comment by ghostWDFR** [comment]
> @ghostWDFR Could you please try holding down Alt (or Option if you're on macOS) on your keyboard and then clicking on the `Check for updates` button (it'll change its text to Ensure latest version). Thanks!

Sorry for a long delay. Now everything works fine, thanks! :)

**Comment by morwoen** [comment]
I have found an interesting side effect from this change. Sharing here to confirm if this is expected or if I should create a separate issue.

I am using a private LFS server. With specifying the following `.lfsconfig` I was getting the auth token GitHub Desktop was using (I'm guessing) in the lfs request headers which allowed the server to verify the user without requiring specific actions (fully transparent for the users).
```
[remote "origin"]
lfsurl = ....

[lfs]
locksverify = true

[lfs "...."]
access = "basic"
```

After this change I am now getting the prompt to authenticate, having to create a token manually and provide that as password.

I appreciate this is rather non-standard setup as many people wouldn't use a private LFS servers, however, the convenience was tremendous before this update so I wanted to confirm :)

**Comment by morwoen** [comment]
@tidy-dev , is this something you can confirm ^

**Comment by tidy-dev** [comment]
@morwoen Thanks for reaching out. It could be tangentially related. Can you [try the latest beta](https://desktop.github.com/beta/) and see if you are still experiencing this?

**Comment by morwoen** [comment]
@tidy-dev thanks for looking into it. I tried the latest beta, shows up as 3.3.19-beta2. I am seeing the same behaviour. When I hit push it pops up an Authentication failed modal asking for username and password for the domain of the private LFS server.

![image](https://github.com/desktop/desktop/assets/5834873/353cd12d-71f6-4ae1-8848-f6efed84cb84)

**Comment by morwoen** [comment]
To add some more context, when using git directly (cli, not GH Desktop) I see similar behaviour - I try to push, Git LFS will ask for credentials to the LFS server which will be saved in the Windows Credentials store for future use. 

The switch happened between 3.3.16 and 3.3.17 which is why I thought this change was the cause.

**Comment by tidy-dev** [comment]
Your issue does appear unrelated to this current issue. Do you mind opening a new issue to track this? And upload a log as part of that ticket pls.
