### ISSUE TITLE
Multiple instances in Windows to allow working at 2 projects at the same time.

### ISSUE THREAD

**Issue by HTD** [desktop/desktop#18577]
### The feature request

The problem is, I can run another instance of GitHub Desktop for Windows. Whenever I try to run it again, it just activates the active window. I work on 2 screens, I have 2 versions of a project and I need to version control them side by side - looking at 2 screens. Unfortunately - it's not possible. GitHub Desktop does not allow this and it's the only part of my toolchain that has such limitation. I have 2 VSCode instances with projects. I have 2 STM32Cube32 instances at once. It all works perfectly, the GitHub Desktop is the one exception that kind of breaks my workflow.

### Proposed solution

Just let it create a separate instance, as long as it has different current repository.

**Comment by steveward** [comment]
Thanks for the request @HTD. I'm going to add this to https://github.com/desktop/desktop/issues/3606 where we are tracking feedback about this.
