### ISSUE TITLE
Help, I have a disco, everything that can flickers

### ISSUE THREAD

**Issue by MishaelBoss** [desktop/desktop#18572]
### The problem

Github flickers a lot when you go to different tabs and do something. But sometimes it works fine, then it starts again.

### Release version

With 3.3.14

### Operating system

System: Windows 11 23H2 Assembly: 22631.3527 X64
CPU: Ryzen 5 2600x
Video card: NVIDIA GTX 1650 drivers:  552.22

### Steps to reproduce the behavior

After updating github from 3.3.14 April 16, 2024.

### Log files

[2024-05-08.desktop.production.log](https://github.com/desktop/desktop/files/15252512/2024-05-08.desktop.production.log)
[2024-05-05.desktop.production.log](https://github.com/desktop/desktop/files/15252948/2024-05-05.desktop.production.log)
[2024-05-06.desktop.production.log](https://github.com/desktop/desktop/files/15252949/2024-05-06.desktop.production.log)
[2024-05-07.desktop.production.log](https://github.com/desktop/desktop/files/15252950/2024-05-07.desktop.production.log)

### Screenshots

![Снимок экрана 2024-05-08 205312](https://github.com/desktop/desktop/assets/115126386/dcceb6af-2a9c-4285-a627-7234ccbbd406)
![Снимок экрана 20
![Снимок экрана 2024-05-08 170831](https://github.com/desktop/desktop/assets/115126386/4f0db439-e835-46cd-8601-773170d6f0e4)
24-05-08 170533](https://github.com/desktop/desktop/assets/115126386/f3f573fe-43ed-4e48-977b-a5b3e3e7b4ba)

**Comment by steveward** [comment]
Thanks for the report @MishaelBoss. Can you share details about your system setup? We've seen a couple of other recent reports of this as well, but have not reproduced the behavior. 

It'd be helpful if you could try following these steps to see if it resolves the issue:

1. Right-click the GitHub Desktop shortcut
2. Open `Properties`
3. In the end of the target field add `--disable-gpu`

It should look something like this:
![image](https://user-images.githubusercontent.com/9341546/228938964-bb31edae-646a-4d8a-b4f6-790f18608109.png)

**Comment by MishaelBoss** [comment]
Oh, it's working for now

**Comment by niik** [comment]
Happy to hear you got it resolved @MishaelBoss!

**Comment by sybrew** [comment]
It's a gsync issue. Disabling gsync "resolves" the issue, as does offloading the UI to the CPU. Doing so won't help with productivity as it slows down the interface.

**Comment by cheapsunglassescrew** [comment]
> Thanks for the report @MishaelBoss. Can you share details about your system setup? We've seen a couple of other recent reports of this as well, but have not reproduced the behavior.
> 
> It'd be helpful if you could try following these steps to see if it resolves the issue:
> 
> 1. Right-click the GitHub Desktop shortcut
> 2. Open `Properties`
> 3. In the end of the target field add `--disable-gpu`
> 
> It should look something like this: ![image](https://user-images.githubusercontent.com/9341546/228938964-bb31edae-646a-4d8a-b4f6-790f18608109.png)

This solved the problem. I have GSYNC on.
