### ISSUE TITLE
After updating, remotes for some repositories get changed

### ISSUE THREAD

**Issue by aclight** [desktop/desktop#18585]
### The problem

This morning Desktop said I should update so I did. I am now using Version 3.3.17 (x64) on Windows 11. IIRC I had also updated earlier this week so the previous version I was using was very recent. Based on what I remember being in the changelog, I think I was using 3.3.14.

After the updated version started up, I clicked the "Pull origin" button and got an error message: "The remote branch does not exist.". I then noticed that the "Current repository" dropdown button says "MIES" but it should say something else (probably "igor"). I clicked on that button to see all of my repositories and the organization of several of them are wrong. Here's what I see:
![image](https://github.com/desktop/desktop/assets/16308324/9d57987a-b1af-4848-85b5-5fdce0ee4800)

The only clone of MIES that I have on my system is the last MIES in the list (yellow highlight). That's a local clone of a public repository https://github.com/AllenInstitute/MIES. The other three "MIES" items listed there (blue highlight) are actually three different clones of a private repository (https://github.com/wavemetrics/igor). If I hover over the three blue checkouts I see the right path for the clone on my local disk but the wrong organization and name of the repo:
![image](https://github.com/desktop/desktop/assets/16308324/07111e56-26cb-4d01-9bfc-45549aaca9f8)

For each of the clones highlighted in blue, I selected it and selected Repository->Open in Git Bash. I then executed:
```
$ git remote -v
origin  https://github.com/AllenInstitute/MIES.git (fetch)
origin  https://github.com/AllenInstitute/MIES.git (push)
```
That origin is consistent with what Desktop is showing in the UI, but it's not right. The origin for each of these blue clones should be:
```
origin  https://github.com/wavemetrics/igor.git (fetch)
origin  https://github.com/wavemetrics/igor.git (push)
```

I'm not 100% certain that updating Desktop caused this problem but everything was working at the end of the day yesterday and updating Desktop was about the first thing I did this morning, so I'm pretty certain this is the cause.

I closed Desktop and opened the .git/config file for one of the blue repositories. I then fixed the remote url to be correct:
```
$ git remote -v
origin  https://github.com/wavemetrics/igor.git (fetch)
origin  https://github.com/wavemetrics/igor.git (push)
```

Then I opened Desktop. I'm now able to successfully pull, but it still shows the name of this repository as "MIES", and the Pull requests tab are all pull requests from AllenInstitute/MIES, not wavemetrics/igor (I clicked the refresh button and that didn't change anything). If I select the Repository->View on GitHub menu item it takes me to https://github.com/AllenInstitute/MIES. So there must be something in Desktop that isn't updating correctly even after I manually changed the remote for this repository.

### Release version

Version 3.3.17 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Update GitHub Desktop

### Log files

[2024-05-09.desktop.production.log](https://github.com/desktop/desktop/files/15263741/2024-05-09.desktop.production.log)

**Comment by steveward** [comment]
@aclight sorry for the trouble here! Could you try clearing the local cache to fix the repository issue?

Here's how to do that:

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop

You will need to log in and add your repositories again, which can be done quickly in bulk by drag-and-drop. Let us know if that doesn't resolve the issue.

Also, if it's helpful, you can right-click on repositories and use the `Create Alias` option to give an alias to repositories that have the same name.

**Comment by aclight** [comment]
@steveward I'll give that a try. I assume you want me to try after fixing the remotes in .git/config for all of the checkouts that got messed up at the time of the upgrade?

**Comment by steveward** [comment]
That's correct. Did all of your repositories have modified remote URLs?

**Comment by aclight** [comment]
> That's correct. Did all of your repositories have modified remote URLs?

No, only the three that had `https://github.com/wavemetrics/igor.git` as the remote. Those three are the only repositories that used that remote. Others (the qtbuild ones in the original screenshot) are on GH under our org but are a different repo (`/qtbuild.git` instead of `/igor.git`).

**Comment by aclight** [comment]
BTW, clearing the local cache after fixing the remotes on the repositories did fix the problem. Thanks.
