### ISSUE TITLE
Credenciales google storage

### ISSUE THREAD

**Issue by davdgil** [desktop/desktop#18587]
Quiero subir al gitHub todo mi proyecto pero me dice que  

 —— Google Cloud Service Account Credentials ——————————        
remote:        locations:        
remote:          - commit: 4d3926fd38cdb418de37fac5aacf8deb7937f003        
remote:            path: backend/credentials/winged-journey-421817-9e637523c9ea.json:1        
remote:             
remote:        (?) To push, remove secret from commit(s) or follow this URL to allow the 

y bueno, que no hay manera de desabilitarlo, y tampoco puedo hacer nada porque lo tengo en un comit que no me deja ni eliminar, me da igual subir ese tipo de archivo porque es para un trabajo de la uni, pero esque no puedo hacer nada ya, no hay una opcion directa que te permita habilitar la subida de cualquier fichero

**Comment by steveward** [comment]
@davdgil are you using GitHub Desktop, or is this a push from the command line? 

It looks like you need to remove a credential from your commit to resolve this issue. See this [guide](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository) and [this article](https://docs.github.com/en/code-security/secret-scanning/push-protection-for-repositories-and-organizations) for more information. If you have any further questions I would recommend reaching out to [GitHub Support](https://support.github.com/).
