### ISSUE TITLE
Should Desktop Electron import data from Desktop Classic?

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#186]
We talked about this a bit at the mini-summit and in https://github.com/desktop/desktop/issues/184.

Should Desktop Electron import Desktop Classic's data? The most meaningful bits are:

- Tracked repositories.
- Logged-in users.

**Comment by kexic** [comment]
We would like to use the new GitHub Desktop Beta, but we have almost 200 independent projects that we follow.  Without a clone discovery mechanism we can't begin to help out.  Please consider at least a directory "rediscover" option where Beta looks in the default directory for newly added folders.

I understand that the connection to the online repositories would take further effort, but for those of us who have been using the desktop extensively, re-cloning our code library may not be a realistic request.

+1 for existing clone foler importing

**Comment by j-f1** [comment]
You can drag and drop the clones into Desktop, @kexic.

**Comment by joshaber** [comment]
Our current answer here is no.

We can revisit this later if we want, but right now there's no action to be taken.

**Comment by Haacked** [comment]
Perhaps we should at least consider documentation or a FAQ answer. For example, it might not be clear to folks that if they have a bunch of clones in the same directory, they could select all their folders and drag them en masse into the new Desktop.

For most users, this is a fine migration strategy because Desktop clones everything to the same folder. So if you don't constantly tweak things, it works great.

**Comment by joshaber** [comment]
That's a great point 👍 I'll raise that on the docs tracking issue.

**Comment by makhnovskiy** [comment]
Had to search on how to import from previous version. This helped. Would definitely be easier with a migration utility, initial launch ability to import repo's or quick message on how to migrate via drag and drop on your homepage https://desktop.github.com/. Either way, thanks for your hard work!

**Comment by danilaml** [comment]
Is there at least some way to quickly get the list of dirs of all repos known to the old GitHub for Windows? I have quite a few repositories, each stored in their specific location(s), so even with drag'n'drop migrating them to new app is not a pleasant prospect. I'd have to manually go through all the repos, open them in explorer and import into a new app.

So yeah, at least the option to import all repositories from the old app would be really nice.  And should work for most cases without any additional problems, assuming that you use the same GH account for all of them.

**Comment by makhnovskiy** [comment]
@danilaml Try searching for all .git files with unique parent folders. Not sure how you would go about with Windows, but Mac or Linux, pretty easy. find / -name ".git". Still a manual drag and drop operation per each single repo... :( 

https://stackoverflow.com/questions/2020812/how-can-i-view-all-the-git-repositories-on-my-machine

**Comment by danilaml** [comment]
@makhnovskiy wouldn't that also include git repositories not added to GitHub for Windows app (if there are any)? For example, tracked/created by some IDE.

**Comment by j-f1** [comment]
I’m pretty sure you can also drag and drop multiple folders at once into Desktop, and it should add them all.

**Comment by makhnovskiy** [comment]
@danilaml Good point... Would be awesome to have that auto migrate tool.

**Comment by gingerbeardman** [comment]
Well this kind of sucks.

No note in the classic app that there was a new one available.
No way to migrate.

I think you could have made this easier for your customers.

**Comment by pmn** [comment]
Hiya @gingerbeardman. I'm sorry that you were surprised by the new version of Desktop and the lack of a migration path between old and new. That sucks, and I know it's frustrating. 

I don't work with the Desktop team at GitHub any more (or at GitHub at all 😅). However, https://desktop.github.com has been updated for awhile to tell people about the new application. Multiple applications were replaced by the new GitHub Desktop (GitHub for Windows, and GitHub for Mac, specifically), and I think the decision to not offer an upgrade path was a good one -- the new Desktop was rewritten from the ground up, and there were / are too many opportunities to get migration wrong, putting people's setup in a bad state. If I were still at GitHub, I'd continue to advocate against an automated migration between the applications but do agree that some kind of notice would be nice. cc'ing @Haacked here, who will know the right folks at GitHub to decide if and what to do here.

**Comment by gingerbeardman** [comment]
I guess things changed a lot sine 2016

**Comment by pmn** [comment]
Although I have no means to do anything about it; how would you have wanted a migration feature to work? What would have been migrated? (And if the answer is 'everything', please enumerate so we're on the same page as to what that means 😀). Is your primary concern discovering existing git repos in a working directory, something else?

**Comment by gingerbeardman** [comment]
Yes, if it just imported the list of repos that would be enough. 

To import nothing is just a big 🖕 and seems quite arrogant from the outside, as you implied in 2016

**Comment by orangebowlerhat** [comment]
I don't have anything to add to this conversation except backing up gingerbeardman's description of the situation. My solution is going to be not using the new app until I see specific evidence that its worth the time to find all those different folders. The previous app is still available and still functioning so there is no reason to lose the time and deal with any possible problems this might cause.

**Comment by j-f1** [comment]
That hypothetical setup could be shortened by using `npx`.

**Comment by gingerbeardman** [comment]
You can manipulate plists on MacOS using the built in shell utility `plistbuddy`

http://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man8/plistbuddy.8.html
