### ISSUE TITLE
See update list in Help menu

### ISSUE THREAD

**Issue by xpagedeveloper** [desktop/desktop#18605]
### The feature request

It would be good to access a list of the changed things with the different versions in the help menu.
You get a item about it when there is a new version if you do upgrade without viewing it it's gone.

### Proposed solution

Add a menu item Release Update

**Comment by sergiou87** [comment]
Hello @xpagedeveloper 

In the About dialog there is a link to the release notes, which can be found here:
- For production versions: https://desktop.github.com/release-notes/
- For beta versions: https://desktop.github.com/release-notes/?env=beta

I hope that helps!
