### ISSUE TITLE
I wish the tool could support something like “break-and-repeat”

### ISSUE THREAD

**Issue by vfp9** [desktop/desktop#18603]
### The feature request

There is a high probability that the tool will terminate in the process of cloning the repository locally due to the network and will have to clone it again from scratch. It would be very useful to have a feature similar to the breakpoint transfer feature.

### Proposed solution

Can the tool refer to other software download tools for the intermittent transfer function?

### Additional context

The online reason for this assumption is prevalent in China.

**Comment by steveward** [comment]
Thanks for the request @vfp9. Unfortunately at this time Git doesn't have this type of functionality, so this won't be something we can implement in GitHub Desktop. There are some clone options that we may look into in the future, like https://github.com/desktop/desktop/issues/18166 and https://github.com/desktop/desktop/issues/3480, which would help with larger repositories.

I'm going to close this out.
