### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by herobrinePerssion** [desktop/desktop#18619]
### The problem

when I update the latest version  Version 3.3.17 (x64)      fetch or push  I have this error
![image](https://github.com/desktop/desktop/assets/19695046/b370a9d5-175b-40a6-8889-e163c9f860ca)
![image](https://github.com/desktop/desktop/assets/19695046/a7f30110-c992-4a3b-a64d-c22a764b69bf)

### Release version

Version 3.3.17

### Operating system

Windows 10 professional  version 19045.3930

**Comment by niik** [comment]
Thanks for the report! Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by herobrinePerssion** [comment]
[2024-05-15.desktop.production.log](https://github.com/desktop/desktop/files/15318877/2024-05-15.desktop.production.log)

**Comment by steveward** [comment]
Thanks for sharing the log file @herobrinePerssion. It looks like you're using a self-hosted Git server -- can you share a few more details about your setup? Is this a GitLab server?

**Comment by Monsoonexe** [comment]
I'm experiencing this same problem on 3.3.18. I tested it. Before updating, a fetch was no problem. After updating, a fetch raises this error. My repository is hosted on a network drive on a different machine. Is it a new requirement that I MUST be logged into a github account even if I'm not using any repositories host on GitHub.com?

**Comment by aolszowka** [comment]
#18586 strikes again here.

If you look at the log this particular user has multiple different Git Repositories located on the same host (192.168.2.19:82), chances are they probably had distinct PAT's associated to each one of them which has now confused the update. I suspect if you were to look at your Credential Manager and wipe out any previous credentials you'd get solved, however if you were trying to use distinct PAT's for each of those repos you're now outta luck!

**Comment by Yarflam** [comment]
Since the last update, I'm disconnected every time 😰
Sometimes just after a push to the remote server.

Is it possible to rollback?

Edit: Okay I made it:
- Download an older version on [uptodown](https://github.en.uptodown.com/windows/versions) (3.3.12)
- Install it!
- Close the app if it started automatically. Rename the file `Update.exe` in the folder
- Start it. Awesome!

**Comment by herobrinePerssion** [comment]
> Thanks for sharing the log file @herobrinePerssion. It looks like you're using a self-hosted Git server -- can you share a few more details about your setup? Is this a GitLab server?

you are right   I am using gitlab GitLab Community Edition [12.4.2](https://gitlab.com/gitlab-org/gitlab-foss/-/tags/v12.4.2)  to manage my local and github repos .  I tried to roll back .  as long as  desktop  autonatically updated . this authentication error come back again

**Comment by herobrinePerssion** [comment]
> #18586 strikes again here.
> 
> If you look at the log this particular user has multiple different Git Repositories located on the same host (192.168.2.19:82), chances are they probably had distinct PAT's associated to each one of them which has now confused the update. I suspect if you were to look at your Credential Manager and wipe out any previous credentials you'd get solved, however if you were trying to use distinct PAT's for each of those repos you're now outta luck!

thanks for sharing. It works!! 
 I tried delete all my self-hosted gitlab credentials and updated to  Version 3.3.19-beta1 .  logging in  my localhost gitlab account . everything goes normal again ！

**Comment by steveward** [comment]
I'm going to close this issue out since you seem to have things working now.
