### ISSUE TITLE
Branches Update 

### ISSUE THREAD

**Issue by sarrazer24** [desktop/desktop#18629]
### The problem

my teammates are updating their branches but it doesnt show up, this error is showing up isnteadremote: Enumerating objects: 286, done.        
remote: Counting objects: 100% (286/286), done.        
remote: Compressing objects: 100% (138/138), done.        
remote: Total 286 (delta 162), reused 255 (delta 131), pack-reused 0        
Receiving objects: 100% (286/286), 571.90 KiB | 1.24 MiB/s, done.
Resolving deltas: 100% (162/162), completed with 25 local objects.
fatal: bad object refs/remotes/origin/sarra-frontend
error: https://github.com/riham-esi/2cp-project.git did not send all necessary objects

Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
error: bad ref for .git/logs/refs/remotes/origin/sarra-frontend
fatal: bad object refs/remotes/origin/sarra-frontend
fatal: failed to run repack
error: task 'gc' failed

### Release version

Version 3.3.18 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1- go to my branch
2- click on fetch origin

### Screenshots

![Screenshot 2024-05-17 001632](https://github.com/desktop/desktop/assets/161450232/a44179f8-b1bd-4cde-8563-cdfc0c044435)

**Comment by steveward** [comment]
@sarrazer24 thanks for the issue. Unfortunately this looks like a problem with the repository. Can you open the repository in the command line (`Repository` > `Open in...`) and run the command `git fsck`? Please let me know the full output of that command.
