### ISSUE TITLE
Detect changes to be pushed in all repositories when viewed using top left dropdown

### ISSUE THREAD

**Issue by sidhant-khamankar** [desktop/desktop#18621]
### The feature request

Detect changes to be pushed in all repositories are viewed using dropdown. Show blue dot on repositories which has local changes yet to pushed to remote repository. 

### Proposed solution

User won't have to switch each repository one by one to check in which repositories he has made local changes which aren't pushed to remote. 

### Additional context

![image](https://github.com/desktop/desktop/assets/63101268/08be5436-ff9e-47aa-ab6d-c6de75464890)

**Comment by steveward** [comment]
Thanks for the feedback @sidhant-khamankar. We do show this in the repository list:

![Image](https://github.com/desktop/desktop/assets/721500/daa3f2e1-ecd9-4c0e-9b0d-9f16047ede70)

I would verify by going to `Options/Preferences` > `Advanced` to ensure you have `Show status icons in the repository list` enabled.
