### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by jonaspetraska7** [desktop/desktop#18623]
### The problem

The PAT token gets lost on this scenario : 
1. Have this configuration of repositories added : (with last version that works, 3.3.14)
    (No submodules, nothing special on any of these repo's)
    Repo A : Gitlab private (company) repo 1 (domain 1) (Ssh)
    Repo B : Gitlab private (company) repo 2 (domain 1) (Ssh)
    Repo C : Gitlab private (company) repo 3 (domain 1) (Ssh)
    Repo D : Gitlab private (company) repo 4 (domain 1) (Ssh)
    Repo E : Azure DevOps private (company) repo 1 (domain 2) (PAT)
    Repo F : Azure DevOps private (company) repo 2 (domain 3) (PAT)
3. Updating to 3.3.18
4. Getting prompted with authentication failure on Repo F.
5. Regenerating PAT on DevOps.
6. Logging in with PAT on Repo F. 
7. Repo F works normally, fetching.
8. Switching to Repo E. Fetching.
9. Getting the same error.
10. Switching BACK to Repo F. Fetching.
11. The PAT token I added just seconds ago, is lost, seeing same authentication error again.
12. The Repo's A, B, C, D work fine, even after update.

### Release version

3.3.18

### Operating system

Windows 11

### Steps to reproduce the behavior

The PAT token gets lost on this scenario : 
1. Have this configuration of repositories added : (with last version that works, 3.3.14)
    (No submodules, nothing special on any of these repo's)
    Repo A : Gitlab private (company) repo 1 (domain 1) (Ssh)
    Repo B : Gitlab private (company) repo 2 (domain 1) (Ssh)
    Repo C : Gitlab private (company) repo 3 (domain 1) (Ssh)
    Repo D : Gitlab private (company) repo 4 (domain 1) (Ssh)
    Repo E : Azure DevOps private (company) repo 1 (domain 2) (PAT)
    Repo F : Azure DevOps private (company) repo 2 (domain 3) (PAT)
3. Updating to 3.3.18
4. Getting prompted with authentication failure on Repo F.
5. Regenerating PAT on DevOps.
6. Logging in with PAT on Repo F. 
7. Repo F works normally, fetching.
8. Switching to Repo E. Fetching.
9. Getting the same error.
10. Switching BACK to Repo F. Fetching.
11. The PAT token I added just seconds ago, is lost, seeing same authentication error again.
12. The Repo's A, B, C, D work fine, even after update.

**Comment by sergiou87** [comment]
Thanks for your report! This looks similar to #18586 but I think you shouldn't run into this problem if, as you mention, repos E and F are hosted on different domain names (vs let's say `dev.azure.com`), since the current implementation shares credentials across all repos hosted on the same domain name (even if they have different paths).

Can you confirm `domain 2` and `domain 3` for repos E and F is correct?

**Comment by jonaspetraska7** [comment]
I'm very sorry, that's true, the domain names are the same, but different companies (paths) as you mentioned : 
Repo E : https://dev.azure.com/Company1/SomeProject
Repo F : https://dev.azure.com/Company2/AnotherProject

**Comment by aolszowka** [comment]
Yeah you're going to get burned here by exactly what was described in #18586 due to multiple pats for multiple organizations, Bummer! I went ahead and updated with a single comment that would get you workable for at least one of the orgs: https://github.com/desktop/desktop/issues/18586#issuecomment-2112715698

**Comment by CharlieDismuke** [comment]
👍🏽 #18586

**Comment by veskoanfinity** [comment]
I have same problem with 3.3.18

**Comment by chintingtan** [comment]
follow. i have authentication issue after update to 3.3.18 today
[2024-05-20.desktop.production.log](https://github.com/desktop/desktop/files/15374035/2024-05-20.desktop.production.log)

**Comment by sergiou87** [comment]
Hello 👋 

Please, try the latest beta (3.3.19-beta2) from https://desktop.github.com/beta which includes support for multiple git credentials on the same host based on different repository paths and let us know if it works.

After updating, you might need to re-enter your credentials for your Azure DevOps repositories.

For hosts other than `dev.azure.com`, you might need to set `useHttpPath` to `true` for whatever domain your repos are hosted on. For example, for gitlab:

`git config --global credential.https://gitlab.com.useHttpPath true`

Thank you for your patience 🙏

**Comment by chintingtan** [comment]
Hi sergiou87,
Thanks for your reply.
I have tried 3.3.19-beta2 but it does not work.
[2024-05-27.desktop.beta.log](https://github.com/desktop/desktop/files/15453445/2024-05-27.desktop.beta.log)

However, when i rollback to version 3.3.5, it works. i dont see the authentication issue anymore.
Hope this can be fixed soon.
Thanks.

**Comment by sergiou87** [comment]
Thanks for your report @chintingtan 

I'm looking at your logs and your issue seems slightly different:
```
fatal: detected dubious ownership in repository at '\\10.6.0.12\vesp\IOPU\FW\RT_Bootloader/.git'
'\\10.6.0.12\vesp\IOPU\FW\RT_Bootloader/.git' is owned by:
	'S-1-5-21-1645522239-1563985344-1417001333-19748'
but the current user is:
	'S-1-5-21-1645522239-1563985344-1417001333-4503'
To add an exception for this directory, call:

	git config --global --add safe.directory '\\10.6.0.12\vesp\IOPU\FW\RT_Bootloader/.git'
fatal: Could not read from remote repository.
```

Would you mind filing a new issue with your logs so we can help you there more effectively? Thank you 🙏

**Comment by chintingtan** [comment]
Ok sure. i will file a new issue.
Thanks.

**Comment by sergiou87** [comment]
You can download 3.4.0 now from https://desktop.github.com (auto-updates are rolled out progressively and might take longer)

Closing this now, thank you for your patience 🙏

**Comment by jonaspetraska7** [comment]
3.4.0 fixed the issue, thank you very much :)
