### ISSUE TITLE
github desktop for mac has been flagged as malware by 2/66 antiviruses, possibly due to invalid signatures.

### ISSUE THREAD

**Issue by geekazodium** [desktop/desktop#18624]
https://www.virustotal.com/gui/file/87ce40617255aee7be4c8ee12e7c0a0897878858e801f11a0fe548ea2d63524a/details
invalid signatures, what is happening here?

I downloaded github desktop from the website.
(https://desktop.github.com/)

**Comment by steveward** [comment]
Thanks for reporting this @geekazodium, we are tracking this in https://github.com/desktop/desktop/issues/18549.
