### ISSUE TITLE
Add project groups

### ISSUE THREAD

**Issue by deguangchow** [desktop/desktop#18630]
### The feature request

When there are many projects, we hope to provide grouping functionality, just like GitLab.

### Proposed solution

<img width="230" alt="0D4244A2-DC7D-4b87-9C24-2DF35EF67C08" src="https://github.com/desktop/desktop/assets/33080600/72056812-4aeb-45b0-88fb-e3c53003e5db">

**Comment by steveward** [comment]
Thanks for the feedback @deguangchow. See [this comment](https://github.com/desktop/desktop/issues/10201#issuecomment-658693653) for more information about why we do not have plans to implement repository grouping at this time. 

One workaround is to use the repository alias feature (right-click -> `Create alias`) and then use that to filter by a specific alias prefix. I hope that helps.
