### ISSUE TITLE
Are there any official plans to add Simplified Chinese language?

### ISSUE THREAD

**Issue by houhoufm** [desktop/desktop#18631]
### The feature request

Are there any official plans to add Simplified Chinese language? The version I'm currently using is developer Chinese, but with each version update, there are various translation issues that arise

### Proposed solution

Many users will benefit, thanks to the developers!

**Comment by steveward** [comment]
Thanks for the issue @houhoufm. At this time we do not have language localization in GitHub Desktop, but this is something that we would like to do in the future. I don't have a timeline for when that may happen as it would require quite a bit of work by the team. I'm sorry that I don't have better news at this time.
