### ISSUE TITLE
Can't change to another branch due to 'file too long' error

### ISSUE THREAD

**Issue by mr185221** [desktop/desktop#18632]
### The problem

Hi,

I can't change to another branch due to 'file too long' error.
It would be good if git desktop app allows me to change the file name and proceed.
![git error](https://github.com/desktop/desktop/assets/78154215/98969806-aab7-4cb2-bfbc-593d68ad066d)

### Release version

Version 3.3.18 (x64)

### Operating system

Windows 10 HF 22H2

### Steps to reproduce the behavior

1. Create a longer folder name with 72 characters and file name with 85 characters
2. check-in and push the changes
3. Try to change to another branch.

### Log files

[2024-05-17.desktop.production.log](https://github.com/desktop/desktop/files/15347524/2024-05-17.desktop.production.log)

### Screenshots

![git error](https://github.com/desktop/desktop/assets/78154215/cb808105-be72-48ca-aed6-e1e92eb4f049)

**Comment by steveward** [comment]
@mr185221 it looks like you're hitting Windows limitation on file path lengths. You can workaround this issue by running the following command:

`git config --global core.longpaths true`

I'm going to close this out, but let me know if that does not get things working!

**Comment by mr185221** [comment]
Thank you, Steve

It worked.

-Richard
