### ISSUE TITLE
Browser authentication produces error message "requires authentication"

### ISSUE THREAD

**Issue by mirelesde** [desktop/desktop#18633]
### The problem

Signing in through any browser results in the application displaying "Requires authentication". I've tried incognito windows, logging out of github.com so that it asks for my credentials. This issue is happening in my workplace in general. 
![image](https://github.com/desktop/desktop/assets/67396467/adf122fb-d038-4561-b285-e9426bbc2871)

### Release version

Version 3.3.18 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Open GitHub desktop
2. Go to file > options
3. Press "Sign into GitHub.com"
4. Log in on web browser and allow it to open GitHub Desktop
5. The error message "Requires authentication" appears

### Log files

[2024-05-15.desktop.production.log](https://github.com/desktop/desktop/files/15354386/2024-05-15.desktop.production.log)

Today after deleting Git and GitHub desktop and removing credentials:
[2024-05-17.desktop.production.log](https://github.com/desktop/desktop/files/15354345/2024-05-17.desktop.production.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/67396467/a71b51bf-61c7-469a-8858-ede50feb22b2)

**Comment by steveward** [comment]
Thanks for the report @mirelesde. Are you behind a proxy or firewall that could be interfering with authentication?

Can you also try resetting GitHub Desktop to see if that helps?

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop and try logging in

You will also need to add your local repositories again, which can be done quickly in bulk by drag-and-drop.

**Comment by ysq-ALX** [comment]
Hi @steveward,
I'm also having this issues since last week. I tried uninstall and reinstall GitHub Desktop but it doesn't work. Everytime when the browser is trying to navigate back to GitHub Desktop, this error message "Requires authentication" appears. 

I'm using MacOS system.
