### ISSUE TITLE
Repeat the authentication

### ISSUE THREAD

**Issue by weixihd** [desktop/desktop#18644]
### The problem

Always prompt for authentication when pulling, pushing, deleting branches, and so on

### Release version

3.3.19-beta1

### Operating system

Windows 10

### Steps to reproduce the behavior

An authentication window always pops up when you pull or push code

### Log files

[2024-05-20.desktop.beta.log](https://github.com/desktop/desktop/files/15372292/2024-05-20.desktop.beta.log)

### Screenshots

![1](https://github.com/desktop/desktop/assets/162430720/460cf1b5-da39-41a6-80ea-acd12977578f)

**Comment by sergiou87** [comment]
Hey @weixihd 👋  Thank you for your report and sorry for the inconvenience.

From what I see in your logs, you have multiple repositories stored on `codeup.aliyun.com`. Do you need different credentials to access them?

**Comment by weixihd** [comment]
Hello. Thank you very much for your reply. These repositories use the same credentials. We use our respective user names and passwords as credentials and do not use personal access tokens as account passwords.

**Comment by sergiou87** [comment]
Hello 👋 

Please, try the latest beta (3.3.19-beta2) from https://desktop.github.com/beta which includes support for multiple git credentials on the same host based on different repository paths and let us know if it works.

After updating, you might need to re-enter your credentials for your Azure DevOps repositories.

For hosts other than `dev.azure.com`, you might need to set `useHttpPath` to `true` for whatever domain your repos are hosted on. For example, for gitlab:

`git config --global credential.https://gitlab.com.useHttpPath true`

Thank you for your patience 🙏

**Comment by sergiou87** [comment]
You can download 3.4.0 now from https://desktop.github.com (auto-updates are rolled out progressively and might take longer)

Closing this now, thank you for your patience 🙏
