### ISSUE TITLE
 Feature Request: Support for Managing Multiple Remotes in GUI

### ISSUE THREAD

**Issue by shivamgaur99** [desktop/desktop#18657]
### The feature request

GitHub Desktop currently lacks support for managing multiple remotes through its graphical user interface (GUI). This feature request aims to address this limitation and provide users with the ability to seamlessly manage multiple remote repositories directly within GitHub Desktop.

### Proposed solution

Introduce a dedicated interface within GitHub Desktop that allows users to add, remove, and switch between multiple remotes associated with their repositories. This interface could include options to:

Add new remotes by specifying the remote URL and a custom name.
Remove existing remotes.
Select a default remote for push/pull operations.
Easily switch between remotes when viewing branches, commits, and pull requests.

### Additional context

It's important to note that while GitHub Desktop currently supports basic remote management for the default "origin" remote, there is no built-in functionality for managing additional remotes. As a result, users often resort to using the terminal, which may not be ideal for everyone.

Incorporating support for managing multiple remotes directly within the GitHub Desktop GUI would align with the tool's goal of providing a seamless and user-friendly Git experience. This feature would cater to the needs of users who frequently collaborate across multiple remote repositories and contribute to enhancing GitHub Desktop's overall usability.

**Comment by steveward** [comment]
Thanks for the feedback @shivamgaur99. I'm going to add this to https://github.com/desktop/desktop/issues/1442 where we are tracking this feature.
