### ISSUE TITLE
Github Desktop won't open

### ISSUE THREAD

**Issue by aoak4085** [desktop/desktop#18655]
### The problem

I was using github desktop to solve a merge when the window froze. Since then every time I try to open github desktop, the menu bar and dock both show the app as running normally, but nothing appears. I have tried restarting the computer and reinstalling github desktop, but the issue persists. 

If I reinstall it will still ask for administrator permission to open the app, but no window appears after this. If I try deleting the app without quitting first, my mac warns me that I cannot delete an app that is currently running, even though there is no window open.  I am also unable to use any of the menu options even though github desktop indicates it is running, including 'About Github Desktop' and 'Settings'.

I have tried installing the arm64, x64, and beta versions but always have the same issue.

### Release version

3.3.18

### Operating system

Mac OS Sonoma 14.3 (M3)

### Steps to reproduce the behavior

1. Download Github Desktop for Silicon Mac
2. Open zip file
3. Move app to applications folder
4. Open Github Desktop
5. Press 'allow' to grant permission

### Log files

[2024-05-19.desktop.production.log](https://github.com/desktop/desktop/files/15382540/2024-05-19.desktop.production.log)

### Screenshots

![Screenshot 2024-05-21 at 9 12 58 am](https://github.com/desktop/desktop/assets/142380728/5d59c78f-af55-4d80-b6bc-911a5a0f3654)

**Comment by steveward** [comment]
Sorry to hear you're having trouble @alexoakleuu. To fully remove the app and reinstall you can run this command:

`rm -rf ~/Library/Application\ Support/GitHub\ Desktop`

I would try that and then reinstall -- let me know if that does not get things working for you.

**Comment by aoak4085** [comment]
Hi Steve, thanks for the reply. That worked a treat - was able to reinstall and is now working properly
