### ISSUE TITLE
Support Git Credential Helpers

### ISSUE THREAD

**Issue by deanward81** [desktop/desktop#18654]
### The feature request

My organization has started severely restricting the lifetime of PATs issued from Azure DevOps. Unfortuantely, that means I have to go generate a new PAT and enter the details into GitHub Desktop every 7 days. When using `git` from the CLI I have it configured to use the [Git Credential Manager](https://github.com/git-ecosystem/git-credential-manager) to allow me to use OAuth to authenticate to DevOps.

### Proposed solution

Use the configured Git credential helper instead of popping up a username/password dialog to authenticate to services that support OAuth.

### Additional context

This has been asked about before [here](https://github.com/desktop/desktop/issues/13787)- some services cannot be authenticated to with just a username and password - they need the additional context provided by the configured credential helper.

I tried configuring the bundled `git` to use the Git Credential Manager from the CLI and it works correctly. When I tried to use it from the UI it still pops the username and password dialog. I also tried symlinking `git.exe` to my correctly configured system git, but it doesn't work from the UI either.

**Comment by niik** [comment]
Hi @deanward81, thanks for reaching out. We've heard reports of restricted PAT lifetimes on Azure Devops and I wanted to get you a little update here. I've opened #18700 which adds experimental support specifically for Git Credential Manager (GCM). Note that this isn't generic credential helper support as your title suggests but reading your issue it seems that for you at least the specific need is for GCM.

It's still pending review but assuming all goes well we intend to ship this feature to our beta channel to gather feedback. Hopefully you'll be able to help us test this once that lands on beta.

**Comment by niik** [comment]
Hey @deanward81, we just shipped GitHub Desktop 3.4.2-beta2 to our [beta channel](https://desktop.github.com/beta/). This includes support for using [Git Credential Manager](https://gh.io/gcm). It's currently off by default but you can enable it in Settings under the advanced tab. We believe this will address the authentication problems outlined in this issue.

<img width="608" alt="Screenshot of Desktop's advanced preferences section with a highlight around the new option to enable Git Credential Manager" src="https://github.com/desktop/desktop/assets/634063/5d4da983-7663-49dd-bb7b-ce51ee9d2d3a" />

When Git Credential Manager (GCM) is enabled all credentials for third-party (i.e. Azure Devops, BitBucket, GitLab etc) will be handled, and stored, outside of GitHub Desktop. GCM supports browser-sign in to many popular services and will avoid the need to create personal access tokens (PATs). 

Please download our beta version from https://desktop.github.com/beta/ to give this a go and please report back with your experience. We'll be collecting feedback in our beta channel which will inform when we make this available to all users. Installing the beta version will not clear your preferences or tracked repositories and you can switch to the production version by simply downloading the latest version from https://desktop.github.com.

**Comment by deanward81** [comment]
@niik amazing, thank you so much, downloading it now!
