### ISSUE TITLE
GitHub Desktop (MacOS ARM) is stuck with "Fetching origin - Hang on..."

### ISSUE THREAD

**Issue by taiyokato** [desktop/desktop#18663]
### The problem

As the title says, every time after I switch a branch within a repo the Pull/Push/Fetch button is stuck at "Fetching origin".
Git commands are still possible with other CLI tools but this button and system menu for Pull/Push/Fetch are unable to perform.

### Release version

3.3.18 (arm64)

### Operating system

MacOS Sonoma 14.5

### Log files

~ removed logs ~

### Screenshots

<img width="231" alt="image" src="https://github.com/desktop/desktop/assets/5071602/3a69499d-dceb-4f16-860f-25eaf107b38c">

**Comment by niik** [comment]
Thanks for the report! Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by taiyokato** [comment]
Hi @niik , thanks for looking into this. 
Here are logs from past 3 days (I have masked the org/repo names just in case - hope it's ok)

[2024-05-21.desktop.production.log](https://github.com/desktop/desktop/files/15410880/2024-05-21.desktop.production.log)
[2024-05-22.desktop.production.log](https://github.com/desktop/desktop/files/15410881/2024-05-22.desktop.production.log)
[2024-05-23.desktop.production.log](https://github.com/desktop/desktop/files/15410882/2024-05-23.desktop.production.log)

**Comment by steveward** [comment]
@taiyokato apologies for not getting back to you here. I can see background operations taking. along time:

`2024-05-21T08:54:11.398Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 3 repositories took 2.5s of which 4358.3s paused, total 4360.8s`

That should not be taking that long for only 3 repositories. Are you running any antivirus or security software that could be causing this?

If you're no longer experiencing this issue, please feel free to close this out as well.
