### ISSUE TITLE
Github Issues Browsing, Create, Commit & Edit

### ISSUE THREAD

**Issue by ygbr** [desktop/desktop#1866]
### Description

We should be able to view the repository issues and comments thread, create new Issues, Edit Issues and Comment on Issues

### Feature Set

- [ ] List All Repository Issues under a Issues Tab on the left bar. Issues should be displayed on the left container (where diffs are shown)
- [ ] Search Issues using Github search predicates as we can in the site
- [ ] Filter Issues by Author, Labels, Projects, Milestones, Assignees
- [ ] Sort Issues using the same options as in the site
- [ ] Create new Issue with Title, Assignees, Labels, Projects, Milestones
- [ ] Allow Markdown on Issue Creation body with full support to Github Markdown, File Uploads, Syntax Highlighting and Preview
- [ ] Display the entire issue history with comments, PRs and CI Integrations
- [ ] Allow to Close and Reopen Issues
- [ ] Comment on Issues with full support to Github Markdown, File Uploads, Syntax Highlighting and Preview

**Comment by shiftkey** [comment]
@ygbr thanks for this idea!

As we're focused on the current 1.0 timeline and getting to parity with the existing applications, I'm going to label this as `future-work` and close it out so our issue tracker doesn't become overwhelming. We'll come back to some of these more ambitious ideas to re-evaluate them in the future.

**Comment by billygriffin** [comment]
I'm going to remove the label future proposal label here in favor of #2376 which more clearly articulates a problem that we're trying to solve with issue creation in the Desktop app. Generally, we do not consider Desktop to be a local version of GitHub.com, but rather a workflow tool, so we try to focus on specific problems in the context of your work as opposed to replacing the functionality of GitHub in the browser.
