### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by Ankit-Christian** [desktop/desktop#18664]
### The problem

In GitHub Desktop version 3.3.18, whenever we fetch or change a branch, it repeatedly asks for authentication. So please, either disable auto-update or allow version 3.3.14 to continue. Thank you.

### Release version

3.3.18

### Operating system

Windows 10

**Comment by steveward** [comment]
Thanks for the report @Ankit-Christian. Are you working with an Azure DevOps repository?

Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by herobrinePerssion** [comment]
delete all credits from your credentials-management . update to the latest beta version . it may help  it works for me .
i'm using self-hosted gitlab

**Comment by sergiou87** [comment]
Hello 👋 

Please, try the latest beta (3.3.19-beta2) from https://desktop.github.com/beta which includes support for multiple git credentials on the same host based on different repository paths and let us know if it works.

After updating, you might need to re-enter your credentials for your Azure DevOps repositories.

For hosts other than `dev.azure.com`, you might need to set `useHttpPath` to `true` for whatever domain your repos are hosted on. For example, for gitlab:

`git config --global credential.https://gitlab.com.useHttpPath true`

Thank you for your patience 🙏

**Comment by Lodi87** [comment]
gh repo clone discourse/discourse-ai

**Comment by hanogin** [comment]
> Hello 👋 
> 
> Please, try the latest beta (3.3.19-beta2) from https://desktop.github.com/beta which includes support for multiple git credentials on the same host based on different repository paths and let us know if it works.
> 
> After updating, you might need to re-enter your credentials for your Azure DevOps repositories.
> 
> For hosts other than `dev.azure.com`, you might need to set `useHttpPath` to `true` for whatever domain your repos are hosted on. For example, for gitlab:
> 
> `git config --global credential.https://gitlab.com.useHttpPath true`
> 
> Thank you for your patience 🙏 

Using the beta version slove the problem for me.

Thank you

**Comment by lalsha4o** [comment]
How to build software in GitHub

**Comment by sergiou87** [comment]
You can download 3.4.0 now from https://desktop.github.com (auto-updates are rolled out progressively and might take longer)

Closing this now, thank you for your patience 🙏
