### ISSUE TITLE
Microsoft File Explorer integrates Git: What's the future of GitHub Desktop?

### ISSUE THREAD

**Issue by EwoutH** [desktop/desktop#18660]
As The Verge [reports](https://www.theverge.com/2024/5/21/24161785/microsoft-windows-file-explorer-version-control-7z-tar):

> **Microsoft is making File Explorer more powerful with version control**
> _The Windows file navigator will natively interface with your Git_
> 
> At Build, Microsoft now says it’s adding native version control to File Explorer by integrating systems like Git, letting you see new changes and comments directly from the app.
>
>![image](https://github.com/desktop/desktop/assets/15776622/55be8bcf-1b59-4dd8-9431-f27466e6244f)

Considering this, I'm curious what the future of GitHub Desktop is. Will it remain available as a more powerful tool, or wil Explorer replace it in the long term?

**Comment by steveward** [comment]
Thanks for the issue @EwoutH. There have been a wide variety of Git and GitHub clients and integrations released in the 10+ years that GitHub Desktop has been around, and we have no plans to discontinue our development and support of the app. Thanks for your interest!
