### ISSUE TITLE
Github Desktop "The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed"

### ISSUE THREAD

**Issue by viorelstroe** [desktop/desktop#18661]
### The problem

Version: 3.3.18
Github Desktop gives the following error when i try to fetch origin or push a commit
![image](https://github.com/desktop/desktop/assets/104901923/eb11a977-7e68-4754-8326-7222905a70b7)

logs:
> 2024-05-21T20:33:16.912Z - info: [ui] Migrating credentials gitlab.com/xxx/qa-infrastructure → gitlab.com
2024-05-21T20:33:16.929Z - info: [ui] [AppStore] loading 31 repositories from store
2024-05-21T20:33:17.157Z - info: [ui] launching: 3.3.18 (Windows 10.0.22621)
2024-05-21T20:33:17.159Z - info: [ui] execPath: 'C:\Users\<user.name>\AppData\Local\GitHubDesktop\app-3.3.18\GitHubDesktop.exe'
2024-05-21T20:33:19.376Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
remote: The project you were looking for could not be found or you don't have permission to view it.
fatal: repository 'https://gitlab.com/xxx/project1.git/' not found

> 2024-05-21T20:37:23.626Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
remote: The project you were looking for could not be found or you don't have permission to view it.
fatal: repository 'https://gitlab.com/xxx/project1.git/' not found

> (The error was parsed as 9: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)

There is nothing that I do locally with the files and even more it works well everything if I downgrade to 3.3.14
After downgrade logs:
>2024-05-21T20:42:30.235Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 1.552s)
2024-05-21T20:42:31.781Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 1.544s)
2024-05-21T20:42:31.827Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 30 repositories took 87.9s of which 0.0s paused, total 87.9s

### Release version

3.3.18

### Operating system

Windows 10.0.22621 (win11)

### Steps to reproduce the behavior

1. Have existing private repo on gitlab.com using 3.3.14
2. Update to last version
3. Try to fetch or push
4. Error

**Comment by sergiou87** [comment]
Do you have more gitlab repositories? Do any of them work?

There is a recent regression (that will hopefully be fixed soon) where hosts that support different credentials per repo aren't working. This might be one of those cases, but I'm surprised `git` is reacting as if the repo doesn't exist (vs there is an authentication error).

**Comment by sergiou87** [comment]
Hello 👋 

Please, try the latest beta (3.3.19-beta2) from https://desktop.github.com/beta which includes support for multiple git credentials on the same host based on different repository paths and let us know if it works.

After updating, you might need to re-enter your credentials for your Azure DevOps repositories.

For hosts other than `dev.azure.com`, you might need to set `useHttpPath` to `true` for whatever domain your repos are hosted on. For example, for gitlab:

`git config --global credential.https://gitlab.com.useHttpPath true`

Thank you for your patience 🙏

**Comment by viorelstroe** [comment]
> Do you have more gitlab repositories? Do any of them work?
> 
> There is a recent regression (that will hopefully be fixed soon) where hosts that support different credentials per repo aren't working. This might be one of those cases, but I'm surprised `git` is reacting as if the repo doesn't exist (vs there is an authentication error).

Tried and this is the output:
![image](https://github.com/desktop/desktop/assets/104901923/1b8e6c12-53f2-47ba-b8f6-9f1a755e5901)

No credentials have been asked to update.

Logs:
> 2024-05-27T12:18:23.924Z - error: [ui] `git -c credential.helper= -c init.defaultBranch=main clone --recursive --progress -- https://gitlab.com/xxx/xxx-jint-test C:\gitlab\xxx\xxx-jint-test` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\gitlab\xxx\xxx-jint-test'...
remote: The project you were looking for could not be found or you don't have permission to view it.
fatal: repository 'https://gitlab.com/xxx/xx-jint-test.git/' not found

Downgrading to 3.3.14 cloning a new project was possible without any credentials.

**Comment by sergiou87** [comment]
@viorelstroe That's so strange 😞  Could you share your whole log file ? At least include the lines with `askPassHandler:` so we can understand better what the app is doing regarding your credentials.

I assume that gitlab repo is private, right? Does it require a specific token to access it or the same as other gitlab repos you might have?

**Comment by viorelstroe** [comment]
@sergiou87 It is a private repo and I use a PAT. Login to gitlab is with SSO

[2024-05-27.desktop.production - cleaned.log](https://github.com/desktop/desktop/files/15465767/2024-05-27.desktop.production.-.cleaned.log)

Hope this makes things clear

**Comment by sergiou87** [comment]
@viorelstroe thank you, that's much better, yes 🙏 

Those logs don't show the latest beta 3.3.19-beta2, but gives me an idea of what could be the problem. If you have git installed in your system, please run `git config --global credential.https://gitlab.com.useHttpPath true` (and the same for any other domain where your repos are hosted), and then install the latest beta from https://desktop.github.com/beta again.

You will be asked for credentials once again (and it will ask once per every gitlab repo you have) but then it should work 🤞 

Please let us know if that helps and if it doesn't, please share your logs again from 3.3.19-beta2. Thank you!

**Comment by viorelstroe** [comment]
I ran the command `git config --global credential.https://gitlab.com.useHttpPath true` and use the beta.
The application behave as you mentioned, it asks for credentials for each repo, but it works.

Thanks for the workaround. 🤝  

I should expect this in a release, instead of making use of beta?

**Comment by sergiou87** [comment]
You can download 3.4.0 now from https://desktop.github.com (auto-updates are rolled out progressively and might take longer)

Closing this now, thank you for your patience 🙏
