### ISSUE TITLE
Unable to access 2nd repository on Gitlab and unable to Update from Master on main repository

### ISSUE THREAD

**Issue by sarahr4888** [desktop/desktop#18662]
### The problem

I have 2 potentially related bugs or a 2 single ones. 

Our environment: we have 2 projects in a self-hosted gitLab environment where we must provide an access token for each project. Project 1 is our main project/site and it has 5 branches + master/main. Each person works on their own branch. On this project under our own branch we can commit and fetch, but none of us are unable to Update from Master. Nothing pulls down to update the branch and it tells us our repository on our computer is up to date. It is not. If I move to someone else's branch I am able to Fetch but not Update from Master.

Project 2 is our secondary project for documentation and also has 5 branches. We experience the same issue as in bug #18588(https://github.com/desktop/desktop/issues/18588) on this branch. I took the advice there and removed the value for genericGitAuth/username/[server] and this forced a new login and I was able to finally commit on that branch. (I will have to wait for others in India to upload overnight to say whether Update from Master is working on this branch.)

I additionally have a third personal repository to GitHub. This however does not appear to be causing any problems.

The issue started on May 16, 2024. I attaching 3 logs: May 15 where almost everything was working, May 16 when everything stopped working and today's May 21.

### Release version

3.3.18(x64)

### Operating system

Windows10 22H2 Build 19045, 4291

### Log files

[2024-05-15.desktop.production.log](https://github.com/desktop/desktop/files/15396060/2024-05-15.desktop.production.log)

[2024-05-16.desktop.production.log](https://github.com/desktop/desktop/files/15396062/2024-05-16.desktop.production.log)

[2024-05-21.desktop.production.log](https://github.com/desktop/desktop/files/15396063/2024-05-21.desktop.production.log)

### Screenshots

Error thrown when trying to commit.

![image](https://github.com/desktop/desktop/assets/30124016/e2e8a7f7-9169-4759-b670-e614ebf9379b)

**Comment by sergiou87** [comment]
Hello 👋 

Please, try the latest beta (3.3.19-beta2) from https://desktop.github.com/beta which includes support for multiple git credentials on the same host based on different repository paths and let us know if it works.

After updating, you might need to re-enter your credentials for your Azure DevOps repositories.

For hosts other than `dev.azure.com`, you might need to set `useHttpPath` to `true` for whatever domain your repos are hosted on. For example, for gitlab:

`git config --global credential.https://gitlab.com.useHttpPath true`

Thank you for your patience 🙏

**Comment by sarahr4888** [comment]
Hi,

Sorry I missed this last week. With the additional git config using useHttpPath on the beta, the logging in between repos appears to be working. The other issue of not updating from master is still there. (I was hoping for some magic :) )

Updated: 
It looks like when I'm pushing it's also doing a merge back into my branch now of our master/main branch, where we used to have to use update from master.

Thanks.

**Comment by steveward** [comment]
:wave: we just shipped GitHub Desktop 3.4.2-beta2 to our [beta channel](https://desktop.github.com/beta/). This includes support for using [Git Credential Manager](https://gh.io/gcm). It's currently off by default but you can enable it in Settings under the advanced tab. We believe this will address the authentication problems outlined in this issue.

<img width="608" alt="Screenshot of Desktop's advanced preferences section with a highlight around the new option to enable Git Credential Manager" src="https://github.com/desktop/desktop/assets/634063/5d4da983-7663-49dd-bb7b-ce51ee9d2d3a" />

When Git Credential Manager (GCM) is enabled all credentials for third-party (i.e. Azure Devops, BitBucket, GitLab etc) will be handled, and stored, outside of GitHub Desktop. GCM supports browser-sign in to many popular services and will avoid the need to create personal access tokens (PATs). 

Please download our beta version from https://desktop.github.com/beta/ to give this a go and please report back with your experience. We'll be collecting feedback in our beta channel which will inform when we make this available to all users. Installing the beta version will not clear your preferences or tracked repositories and you can switch to the production version by simply downloading the latest version from https://desktop.github.com.
