### ISSUE TITLE
The auto update should check the OS version for new version.

### ISSUE THREAD

**Issue by q1208c** [desktop/desktop#18666]
### The problem

I working in mac os 10.13.6 and Github Desktop 3.3.8, all it work fine.
But ,when I restart computer(or just restart Github Desktop), It will update to newer version(I don't know the number), and it said, it should run on mac os 10.15 or later.
I try to resinstall the old version (3.3.8), it works OK. but , when I restart, again ... 
I try to find how to disable auto update, but ,no way. 
how ?

### Release version

3.3.8

### Operating system

mac os 10.13.6

**Comment by niik** [comment]
Hey @q1208c, thanks for reaching out! The [change to disable auto-updates](https://github.com/desktop/desktop/pull/18320) for users on macOS versions 10.14 and lower was added in version 3.3.14 (released on April 16th). Unfortunately we don't have the infrastructure at the moment for older versions to check OS compatibility before downloading an update so we rely on users staying relatively up to date.

Unfortunately it appears that the change to disable updates potentially shipped in the same version as the one that upgraded Electron to the version which dropped support for 10.13. I haven't verified this myself yet but judging from the release notes it sure seems that way. If true then that's our mistake and we do apologize for it. Could you please try downloading 3.3.14 just to verify that it won't launch? The binary is available here: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.14-b6c1402e/GitHubDesktop-x64.zip

If that version won't launch please let me know and I'll see about different solution

**Comment by q1208c** [comment]
I tried, the Application icon looks like:
<img width="128" alt="屏幕快照 2024-05-22 19 24 24" src="https://github.com/desktop/desktop/assets/8043231/a2c3938a-da01-486c-ba65-c8e785f5c074">

when click, it said: 
```
current version application 'Github Desktop.app" can not working with current macOS version.
you use macOS 10.13.6. The Application require macos 10.15 or later.
```
<img width="422" alt="屏幕快照 2024-05-22 19 24 09" src="https://github.com/desktop/desktop/assets/8043231/d3c9c10c-14fb-492a-9a42-6d436740d064">

the following is current version, looks, it downloading the update automatic ...
![屏幕快照 2024-05-22 16 37 26](https://github.com/desktop/desktop/assets/8043231/d1e48e09-7126-4361-8df0-63432eded7ed)

**Comment by tidy-dev** [comment]
The check for this was [introduced in beta 3.3.12-beta3](https://github.com/desktop/desktop/issues/18316#issuecomment-2007708932). Thus, likely [3.3.12 is the last version](https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.12-a21e55b3/GitHubDesktop-x64.zip) for this.

There was some confusion around release notes on this one because we didn't catch that electron caused this so it was reverted only on release PRs I believe.

**Comment by q1208c** [comment]
> The check for this was [introduced in beta 3.3.12-beta3](https://github.com/desktop/desktop/issues/18316#issuecomment-2007708932). Thus, likely [3.3.12 is the last version](https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.12-a21e55b3/GitHubDesktop-x64.zip) for this.
> 
> There was some confusion around release notes on this one because we didn't catch that electron caused this so it was reverted only on release PRs I believe.

I tried 3.3.12, It looks like worked, and the update is disabled too.
![屏幕快照 2024-05-22 20 12 32](https://github.com/desktop/desktop/assets/8043231/dffe363d-3289-4f74-a589-b05fdb1d9510)

**Comment by q1208c** [comment]
> The check for this was [introduced in beta 3.3.12-beta3](https://github.com/desktop/desktop/issues/18316#issuecomment-2007708932). Thus, likely [3.3.12 is the last version](https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.12-a21e55b3/GitHubDesktop-x64.zip) for this.
> 
> There was some confusion around release notes on this one because we didn't catch that electron caused this so it was reverted only on release PRs I believe.

I tried 3.3.12, It looks like worked, and the update is disabled too.
![屏幕快照 2024-05-22 20 12 32](https://github.com/desktop/desktop/assets/8043231/dffe363d-3289-4f74-a589-b05fdb1d9510)

**Comment by q1208c** [comment]
> The check for this was [introduced in beta 3.3.12-beta3](https://github.com/desktop/desktop/issues/18316#issuecomment-2007708932). Thus, likely [3.3.12 is the last version](https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.12-a21e55b3/GitHubDesktop-x64.zip) for this.
> 
> There was some confusion around release notes on this one because we didn't catch that electron caused this so it was reverted only on release PRs I believe.

I tried 3.3.12, It looks like worked, and the update is disabled too.
![屏幕快照 2024-05-22 20 12 32](https://github.com/desktop/desktop/assets/8043231/dffe363d-3289-4f74-a589-b05fdb1d9510)

**Comment by jaslavin** [comment]
I verified this on MAC OS version 10.13.6 (High Sierra) as well. You get the no longer supported message from GitHub Desktop version 3.3.12, but it still works! Thank you very much for the help!
