### ISSUE TITLE
my report

### ISSUE THREAD

**Issue by StellaAkpan32** [desktop/desktop#18669]
please i want to change my user name

**Comment by steveward** [comment]
@StellaAkpan32 this issue tracker is for GitHub Desktop. You can see how to change your GitHub handle here:

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/changing-your-github-username

If you have further questions please reach out to [GitHub Support](https://support.github.com/).
