### ISSUE TITLE
unable to commit to main

### ISSUE THREAD

**Issue by danzaki23** [desktop/desktop#18668]
### The feature request

![commit error](https://github.com/desktop/desktop/assets/168427107/70ff66a5-99d9-4c2b-9922-a76e79655957)

### Proposed solution

so that new users will find their way out easily

**Comment by steveward** [comment]
Thanks for the issue @danzaki23. Can you go to `File` > `Options` > `Git` and verify that your name and email address are set? See [this article](https://docs.github.com/en/desktop/configuring-and-customizing-github-desktop/configuring-git-for-github-desktop#configuring-your-global-author-information) for more information. Let me know if that does not get things working!

**Comment by danzaki23** [comment]
They are not set
