### ISSUE TITLE
GitHub destkop can't handle azure devops anymore (dev.azure.com) with multiple git creds 

### ISSUE THREAD

**Issue by danielkoek** [desktop/desktop#18667]
### The problem

I have multiple auth's for devops, since i work for a company that has many tenants in devops.

For whatever reason GitHub Desktop can't handle that even the say it does.

I can perfectly make it work with VS code/cmd or whatever but I am a long time user of github desktop so prefer that.I

### Release version

3.3.18

### Operating system

Windows

### Steps to reproduce the behavior

Get 1user with 2 orginasations. 

eg https://org1@dev.azure.com/org1/_git/project1 and https://org2@dev.azure.com/org2/_git/project2

That both have the same user d.koek for example, 

When you go to project1, everything is fine, until you switch to project2 and it will then remove both.

### Log files

fatal: Authentication failed for '#REPLACED WITH THE EXAMPLE#https://org1@dev.azure.com/org1/_git/project1#REPLACED WITH THE EXAMPLE#'

(The error was parsed as 4: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2024-05-22T11:27:54.124Z - info: [ui] askPassHandler: auth failed, deleting dev.azure.com credential
2024-05-22T11:27:56.323Z - info: [ui] askPassHandler: no account found for dev.azure.com
2024-05-22T11:27:58.196Z - info: [ui] askPassHandler: user cancelled generic git authentication
2024-05-22T11:27:58.970Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 3.091s)

**Comment by danielkoek** [comment]
#18664, #18644, #18635 and #18635 all seem to be the same issue as this one....

**Comment by danielkoek** [comment]
And to help more people out, it is also found here #18623 and #18586 That last one gave some suggestions that don't seem to work for me anyway, please fix this by not just checking the domain, but also by either checking whatever is before the @ or by going to subfolders for the check to auth...

**Comment by herobrinePerssion** [comment]
delete all credits from your  credentials-management .   update to the latest beta version .  it may help

**Comment by danielkoek** [comment]
That makes zero difference, the problem isn't that the creds aren't wiped correctly, it is that it can't differentiate between dev.azure.com/org1 and org2, and azure devops has a specific PAT token for each, so when you switch repo's to say org2 it will look for a general dev.azure.com PAT, find the one of org1, sees it doesn't work, remove that one and ask for creds, so you end up with everything wiped.


The beta channel makes no difference, it is the path that has to be taken into account or the first part of the URL (org1@) (devops cloning will always do https://org1@dev.azure.com/org1/_git/proj, which is wrong in the docs of github desktop btw cause it states it is the username@dev.azure.com but that is invalid, it is org, which in the case of a personal project your username! https://github.com/desktop/desktop/blob/development/docs/integrations/azure-devops.md

**Comment by sergiou87** [comment]
We're working on this, sorry for the inconvenience. We will try to deploy a beta build with the fix soon 🙏

**Comment by shenrique38** [comment]
I have the same problem. This is making my life be in the deepest of hell. Please fix that soon.

**Comment by sergiou87** [comment]
Hello 👋 

Please, try the latest beta (3.3.19-beta2) from https://desktop.github.com/beta which includes support for multiple git credentials on the same host based on different repository paths and let us know if it works.

After updating, you might need to re-enter your credentials for your Azure DevOps repositories.

For hosts other than `dev.azure.com`, you might need to set `useHttpPath` to `true` for whatever domain your repos are hosted on. For example, for gitlab:

`git config --global credential.https://gitlab.com.useHttpPath true`

Thank you for your patience 🙏

**Comment by sergiou87** [comment]
You can download 3.4.0 now from https://desktop.github.com (auto-updates are rolled out progressively and might take longer)

Closing this now, thank you for your patience 🙏

**Comment by niik** [comment]
:wave: we just shipped GitHub Desktop 3.4.2-beta2 to our [beta channel](https://desktop.github.com/beta/). This includes support for using [Git Credential Manager](https://gh.io/gcm). It's currently off by default but you can enable it in Settings under the advanced tab. We believe this will address the authentication problems outlined in this issue.

<img width="608" alt="Screenshot of Desktop's advanced preferences section with a highlight around the new option to enable Git Credential Manager" src="https://github.com/desktop/desktop/assets/634063/5d4da983-7663-49dd-bb7b-ce51ee9d2d3a" />

When Git Credential Manager (GCM) is enabled all credentials for third-party (i.e. Azure Devops, BitBucket, GitLab etc) will be handled, and stored, outside of GitHub Desktop. GCM supports browser-sign in to many popular services and will avoid the need to create personal access tokens (PATs). 

Please download our beta version from https://desktop.github.com/beta/ to give this a go and please report back with your experience. We'll be collecting feedback in our beta channel which will inform when we make this available to all users. Installing the beta version will not clear your preferences or tracked repositories and you can switch to the production version by simply downloading the latest version from https://desktop.github.com.
