### ISSUE TITLE
Graphical bug making laptop unusable

### ISSUE THREAD

**Issue by LO-0116** [desktop/desktop#18678]
### The problem

After using the computer with github desktop open for a few hours, a weird graphical bug start appearing: when the app's window gains focus (with the mouse entering the window or hovering over buttons), the window shows vertical scan lines that blurs its content. It flickers briefly then disappears.

A few hours/app usages after this initial behavior has been seen, the entire computer screen will be blurred by shifting vertical lines **even after the app has been closed**.

Restarting the computer will fix the effect, but it returns a few hours after the app has been reopened (reopening right away does not recreate the issue)

### Release version

Version 3.3.18 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

Open github desktop app, use computer normally with software editors and internet browsers open, periodically commit and push using the app. Issue may appear after a few hours.

**Comment by steveward** [comment]
Thanks for the report @LO-0116. See my comment [here](https://github.com/desktop/desktop/issues/18572#issuecomment-2101060343) to see if it resolves things for you. Some users have mentioned that G-Sync can cause this as well.
