### ISSUE TITLE
Github Projects

### ISSUE THREAD

**Issue by ygbr** [desktop/desktop#1867]
### Description

We should be able to browse the repository Projects, Render the Kanban and allow to move issues between columns and add new cards

Depends on #1866

**Comment by shiftkey** [comment]
@ygbr thanks for this idea!

As we're focused on the current 1.0 timeline and getting to parity with the existing applications, I'm going to label this as `future-work` and close it out so our issue tracker doesn't become overwhelming. We'll come back to some of these more ambitious ideas to re-evaluate them in the future.

**Comment by DevAndArtist** [comment]
GitHub issues, milestones and projects is what I'm personally really looking forward to. It would increase my workflow a lot if I had a native app that provides me everything I need for work (git and project management).

**Comment by billygriffin** [comment]
Hi folks, thank you so much for the idea. I'm removing future proposal here to indicate that we have no plans to integrate GitHub Projects into Desktop. As GitHub Desktop is not intended to be a one for one replacement for the functionality of GitHub.com, there will always be things available on GitHub generally that are not available in the Desktop app. We try to prioritize things based on what's most valuable to people in the context of their local workflows, and as of now we haven't seen a ton of evidence that this is the case. In addition, with automation on project boards hooked into pull requests being merged, issues closed as a result, etc. we think that functionality works best on the website. Thanks for the suggestion and we're always open to reconsidering as we continue to learn more.
