### ISSUE TITLE
Unable to deserialize JSON string to object, SyntaxError

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1868]
Was trying to publish a repo while logged in, but kept seeing these `Unable to deserialize JSON string to object` errors in the console. Repo was published successfully, regardless. Repo is new and not a dupe.

Reproduce:
File > New Repo
Follow steps and publish

v0.5.9, OSX 10.11.5

<img width="1133" alt="screen shot 2017-06-01 at 1 47 50 pm" src="https://cloud.githubusercontent.com/assets/14828183/26693357/de6768aa-46d1-11e7-96a0-07c560916be9.png">

**Comment by shiftkey** [comment]
My gut feeling on this is that something has changed with the error reporting from octokat here: https://github.com/desktop/desktop/blob/0b2411081848fe7e9ab0fcd4920ccbf22929e24d/app/src/lib/api.ts#L325-L336 that we need to handle better. Should be easy to trigger by recreating the "already exists" error.

**Comment by joshaber** [comment]
This was fixed as part of #2080.
