### ISSUE TITLE
Dashboard data abnormal, I can't always see the latest news.

### ISSUE THREAD

**Issue by warmthsea** [desktop/desktop#18682]
### The problem

I checked all (Picture 1) but always getting data exception.
Most of the time it’s Picture 1, sometimes it’s Picture 2, I think it’s always Picture 2, because Picture 2 is the correct one that includes everything.

## Figure 1
![image](https://github.com/desktop/desktop/assets/45450994/34c00638-890b-4697-a523-9607b737204f)

## Figure 2 （error）
![image](https://github.com/desktop/desktop/assets/45450994/97a0ea8e-64d3-4ecc-a57b-1f26baa70a32)

## Figure 3 （correct）
![image](https://github.com/desktop/desktop/assets/45450994/cf63264a-4f24-4a87-ae14-ff7d3780aef6)

### Release version

last

### Operating system

win11 / desktop / websidee / iphone

### Additional context

![screenshots](https://github.com/desktop/desktop/assets/45450994/7904c00f-a849-4fa3-ab94-6fbb5c4ce110)

**Comment by warmthsea** [comment]
![screenshots](https://github.com/desktop/desktop/assets/45450994/7904c00f-a849-4fa3-ab94-6fbb5c4ce110)

**Comment by steveward** [comment]
@warmthsea this issue tracker is for GitHub Desktop, for problems related to GitHub the website you will need to reach out to [GitHub Support](https://support.github.com/).

**Comment by warmthsea** [comment]
> @warmthsea this issue tracker is for GitHub Desktop, for problems related to GitHub the website you will need to reach out to [GitHub Support](https://support.github.com/).

OK. Thanks.
