### ISSUE TITLE
GitHub Desktop Update Issue from Files

### ISSUE THREAD

**Issue by evarikkad** [desktop/desktop#18699]
### The problem

Hello!
I was programming and I encountered an issue where GitHub desktop wouldn't update my changes so I could push them. The repository was created 15 minutes ago, so I was pretty confused. I clicked "Open in Visual Studio Code" and it showed the old version of the code (without the changes version).

### Release version

3.3.18

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Create a repo
2. Drag and Drop a folder into the upload a file section
3. Clone the repo on GitHub desktop
4. Change the code

### Additional context

I am programming the the VEX V5RC competition and the vex.h header file also wasn't defined in the version when I clicked "Open with Visual Studio" but was in the original competition. The extention for VEX also wasn't activated too.

**Comment by TIJBRAND1996** [comment]
Que tengo que hacer?

**Comment by evarikkad** [comment]
Sorry, I seemed to have fixed the problem. It was the location of the file.
