### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by chintingtan** [desktop/desktop#18693]
### The problem

![image](https://github.com/desktop/desktop/assets/49709262/a984a4c1-6c01-456b-942f-844d24650c99)
I am unable to push or pull to/from my remote repo after upgraded to 3.3.18 few days ago.

It works file when i rollback to 3.3.5

### Release version

3.3.18

### Operating system

Windows10

### Log files

[2024-05-27.desktop.production.log](https://github.com/desktop/desktop/files/15454254/2024-05-27.desktop.production.log)

**Comment by niik** [comment]
Hey @chintingtan, thanks for reaching out. 3.3.5 is a rather old version so I really wouldn't recommend you stay on that for longer than necessary.

Do you have Git installed on your system? If you do could you try running `git config --global --add safe.directory '\\10.6.0.12\vesp\IOPU\FW\ANDiS\RTFW\RTSRC/.git'` and then retrying the pull?

It seems we're incorrectly detecting dubious ownership errors from Git as auth failures so I'm gonna tag this as a bug while we investigate.

**Comment by sergiou87** [comment]
Thank you @chintingtan 🙇‍♂ 

Looking at your logs, the problem seems to be this:
```
fatal: detected dubious ownership in repository at '\\10.6.0.12\vesp\IOPU\FW\RT_Bootloader/.git'
'\\10.6.0.12\vesp\IOPU\FW\RT_Bootloader/.git' is owned by:
	'S-1-5-21-1645522239-1563985344-1417001333-19748'
but the current user is:
	'S-1-5-21-1645522239-1563985344-1417001333-4503'
To add an exception for this directory, call:

	git config --global --add safe.directory '\\10.6.0.12\vesp\IOPU\FW\RT_Bootloader/.git'
fatal: Could not read from remote repository.
```

If you have been using 3.3.5 (very old release) it's probable this problem was introduced in a different version. I see git 2.39.4 introduced a check for that "dubious ownership": https://github.com/git/git/blob/b9cfe4845cb2562584837bc0101c0ab76490a239/Documentation/RelNotes/2.39.4.txt#L27-L32

I wonder if the problem for you was introduced when we upgraded from git 2.39.3 to 2.43.3 in GitHub Desktop v3.3.13. I can suggest to try these two versions:
- v3.3.12: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.12-a21e55b3/GitHubDesktopSetup-x64.exe
- v3.3.13: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.13-1b0804db/GitHubDesktopSetup-x64.exe

Could you tell us if those work? If my theory is correct, 3.3.12 should work and 3.3.13 shouldn't.

**Comment by chintingtan** [comment]
i have tried both 3.3.12 and 3.3.13. Both versions are working fine.
[2024-05-28.desktop.production.log](https://github.com/desktop/desktop/files/15462844/2024-05-28.desktop.production.log)

**Comment by sergiou87** [comment]
Thank you for checking… could you try this 3.3.17 then?

- https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.17-9a535f40/GitHubDesktopSetup-x64.exe

This is just to pinpoint where the error came from.

In any case I agree with @niik that the best solution right now is to run that command while we fix how we parse that (new) error.

**Comment by chintingtan** [comment]
@niik @sergiou87 
thanks for looking into this error.

3.3.17 works fine too. 
So only 3.3.18 showing this error.
running below command does not help
git config --global --add safe.directory '\\10.6.0.12\vesp\IOPU\FW\io2\FW/.git'

[2024-05-28.desktop.production.log](https://github.com/desktop/desktop/files/15467063/2024-05-28.desktop.production.log)

**Comment by sergiou87** [comment]
Thank you @chintingtan

So it's probably the latest git upgrade to v2.43.4 what introduced this change in behavior.

Looking at the command you posted, it lacks one `\` before the IP:
`git config --global --add safe.directory '\\10.6.0.12\vesp\IOPU\FW\io2\FW/.git'`

Could that be the reason why it didn't work?

**Comment by chintingtan** [comment]
i run again with
git config --global --add safe.directory '\\\10.6.0.12\vesp\IOPU\FW\io2\FW/.git'

also not working

**Comment by chintingtan** [comment]
Hi,
Appreciate if anybody is looking into this problem.
Let me know if more info is needed.

Thanks.

**Comment by markbrill-insphire** [comment]
I've had two users report the same issue to me this week.  We're using GitHub Desktop with Azure Devops hosted git.
One of them was prompted for his PAT on one repo and getting this same error on a second repo.  He tried rebooting and the second repo prompted for a PAT which he entered and then it worked.
Based on this we had the second guy reboot and this didn't immediately help but after a few click of fetch it then prompted for the PAT code and then worked.
I've not had this specific error but my client prompted for re-entry of PAT codes for no good reason (they hadn't expired), across multiple repo's.

**Comment by Arjunpride15** [comment]
> ### The problem
> ![image](https://private-user-images.githubusercontent.com/49709262/334057104-a984a4c1-6c01-456b-942f-844d24650c99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTkzODIsIm5iZiI6MTcxNzY1OTA4MiwicGF0aCI6Ii80OTcwOTI2Mi8zMzQwNTcxMDQtYTk4NGE0YzEtNmMwMS00NTZiLTk0MmYtODQ0ZDI0NjUwYzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA3MzEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZmYzYTYwZGQ5OGM0MGQ0MmQxZDIyZTM1NzRkM2I3N2Q1YjI5YWZjYWUzYWQwMTJlNWM3ZDI3NzZiMzRhZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pix-fWzNoqWSnE7V49wzWhSrj7DuG6dnPXFcdPZvJs0) I am unable to push or pull to/from my remote repo after upgraded to 3.3.18 few days ago.
> 
> It works file when i rollback to 3.3.5
> 
> ### Release version
> 3.3.18
> 
> ### Operating system
> Windows10
> 
> ### Steps to reproduce the behavior
> _No response_
> 
> ### Log files
> [2024-05-27.desktop.production.log](https://github.com/desktop/desktop/files/15454254/2024-05-27.desktop.production.log)
> 
> ### Screenshots
> _No response_
> 
> ### Additional context
> _No response_

Please apply for 2FA on Github.

**Comment by sergiou87** [comment]
This should've been fixed on the latest version, and you might need to enter credentials again but after that it should work. Sorry for the inconvenience 🙏
