### ISSUE TITLE
Pre-commit handler no longer finds npx or other apps

### ISSUE THREAD

**Issue by mkahvi** [desktop/desktop#18705]
### The problem

After updating to 3.4.0, pre-commit handler no longer finds npx despite it being perfectly there

This worked fine in 3.3.18 or whatever I had prior.

npx and other tools are located fine in any terminal I run, nothing changed there.

### Release version

3.4.0

### Operating system

Windows 11

### Steps to reproduce the behavior

Have any pre-commit hook that uses npx?

### Log files

```
2024-05-29T22:25:57.466Z - error: [ui] `git commit -F - --amend` exited with an unexpected code: 1.
stderr:
.husky/pre-commit: line 4: npx: command not found
husky - pre-commit hook exited with code 127 (error)
husky - command not found in PATH=/mingw64/libexec/git-core:/mingw64/bin:/usr/bin:/c/Users/Mayflower/bin:/mingw64/bin:/mingw64/usr/bin:undefined
```

**Comment by mkahvi** [comment]
Re-installing 3.3.18 via chocolatey solves this problem for me temporarily. Hoping the problem can be fixed on latest tho.

**Comment by iilyushenok** [comment]
This should be considered a blocker bug. Husky hooks don't work at all, I personally can't commit or pull.

**Comment by jasonyuealt** [comment]
found the same problem in 3.4.0，and reinstall 3.3.18 solved this
![image](https://github.com/desktop/desktop/assets/107463221/78a71ed4-8e7e-4c0b-b3ab-b845429b7e95)

**Comment by simonfoxenano** [comment]
Confirmed - github-desktop 3.4.0 breaks husky running on Windows. Cannot find `npx.cmd` with this latest version.

Rolled back to the previous version and it's working again and I can commit, but Github Desktop auto downloads the latest update and is sitting there waiting for me to restart the program to update. Until they fix this I'm going to have to keep uninstalling and reinstalling an older version every time I close the program or restart the computer.

My husky pre-commit: 
```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [[ "$OS" == "Windows_NT" ]]; then
  npx.cmd lint-staged
else
  npx lint-staged
fi

```

**Comment by MrSergo15** [comment]
Encountering the same issue with finding `python3` for pre-commit scripts. 

![image](https://github.com/desktop/desktop/assets/43544208/e3d960d4-71ec-4539-8c65-07d1e6772939)


The current workaround is downgrading to 3.3.18, but is getting quite tedious with auto updating to 3.4.0 repeatedly.

**Comment by andylwelch** [comment]
I found this download url worked for [v3.3.18](https://central.github.com/deployments/desktop/desktop/3.3.18/win32). Also, rename the `Update.exe` and it will break the auto-update process...

**Comment by tidy-dev** [comment]
Closed in favor of tracking https://github.com/desktop/desktop/issues/18739
