### ISSUE TITLE
`error: cannot spawn ssh-keygen: No such file or directory` on commit

### ISSUE THREAD

**Issue by mderriey** [desktop/desktop#18701]
### The problem

When committing, I get the following error:

```console
error: cannot spawn ssh-keygen: No such file or directory
error: 
fatal: failed to write commit object
```

Committing on the command line works wihtout me having to enter the SSK key passphrase.

### Release version

Version 3.4.0 (x64)

### Operating system

Windows 11 23H2 (22631.3593)

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. Pick some files to be committed
3. Type a commit message
4. Click on the "Commit to <branch>" button

### Log files

[2024-05-29.desktop.production.log](https://github.com/desktop/desktop/files/15484317/2024-05-29.desktop.production.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/6102639/88cdf03e-e52c-4f4f-891f-84ed7a373a74)

### Additional context

I'm using SSH to sign commits, and as mentioned above it works from the command line.

Relevant parts of the `.gitconfig` file in my user directory:

```ini
[user]
  signingkey = C:/Users/me/.ssh/id_ed25519.pub
[credential]
  helper = manager
[gpg]
  format = ssh
[commit]
  gpgsign = true
```

**Comment by cjee21** [comment]
My SSH signing set-up was working fine earlier today. Now same error happens after GitHub Desktop auto updated disrupting productivity.

**Comment by JovannMC** [comment]
Can confirm this also just happened to me after auto-updating to v3.4.0 today, using SSH and Windows 11 23H2.
Using v3.3.18 from my local files lets me commit.
[2024-05-31.desktop.production.log](https://github.com/user-attachments/files/15514523/2024-05-31.desktop.production.log)

**Comment by cjee21** [comment]
Fortunately I retained GitHub Desktop 3.3.18 installer so can downgrade. Confirm that downgrading fixes it. Now if only there is a way to disable the auto-update that runs immediately and will be applied on app restart...

**Comment by HotCakeX** [comment]
Have the same problem.

**Comment by mohit-nagaraj** [comment]
+1 same problem

**Comment by Lulalaby** [comment]
can repro

**Comment by AnonymousWP** [comment]
Same issue here.

**Comment by ben-HMRC** [comment]
Same issue on Windows 10. I can run ssh-keygen from the Git Bash prompt, but it doesn't work from GitHub desktop.

**Comment by luiz-matias** [comment]
Same issue here on WIndows 11.

The workaround was to disable default commit signing from my `.gitconfig` file:
```
[user]
	name = My name
	email = myemail@email.com
	signingkey = C:/Users/me/.ssh/id_ed25519.pub
[gpg]
	format = ssh
[commit]
	gpgsign = false     <-- set it to false, github desktop will work again
```

Obviously that will make your commits not verified which is not ideal for security, but will do the trick

**Comment by HotCakeX** [comment]
I'm just gonna never close GitHub desktop and continue to work like this 😀

![image](https://github.com/desktop/desktop/assets/118815227/41a313ac-000e-4088-9f99-9ff816d2637e)

Btw this is only for beta, right?

**Comment by AnonymousWP** [comment]
What worked for me is continuing to use Git via the command line (open in Windows Terminal), via here:

![image](https://github.com/desktop/desktop/assets/50231698/168e702b-1858-4402-aa71-ade4f5414191)

> Btw this is only for beta, right?

No, it's a stable version: https://desktop.github.com/release-notes/

**Comment by HotCakeX** [comment]
@AnonymousWP wow, i'm always using the beta versions and thought it was isolated to beta channel. It's a big issue and idk how it wasn't caught before stable release...specially since it's open source and many non-Microsoft people have eyes on it...

**Comment by AnonymousWP** [comment]
> @AnonymousWP wow, i'm always using the beta versions and thought it was isolated to beta channel. It's a big issue and idk how it wasn't caught before stable release...specially since it's open source and many non-Microsoft people have eyes on it...

Probably because not many people sign their commits I think, lol, and maybe because those who have their commits signed, use the CLI. Maybe that's why.

**Comment by wehrlean** [comment]
+1 same problem

**Comment by andreasmuelder** [comment]
same problem

**Comment by Wesley-TCP** [comment]
Running into the same issue. Commit signing is required in my repos, so this is a show stopper.

**Comment by JLeverDynaGen** [comment]
Is this caused by [Pull 18676](https://github.com/desktop/desktop/pull/18676 )

Based on the dugite change from 2.71 to 3.0.0-rc0
https://github.com/desktop/dugite/compare/v2.7.1...v3.0.0-rc0#diff-306dbfea8f7832de093113811764230e517e31516a8daa67a2c32a6dada8b9fc

I am suspicious of the new lib/git-environment.ts line 94, vs the deleted line 80 in dugite: 

[    env.PATH = `${gitDir}\\${mingw}\\bin;${gitDir}\\${mingw}\\usr\\bin;${env.PATH}`](https://github.com/desktop/dugite/blob/bde5f3d8214eb1e8613c67c68c45df7b5b1fbdd0/lib/git-environment.ts#L94)

Shouldn't that line be `env.PATH = ${gitDir}\\${mingw}\\bin;${gitDir}\\${mingw}\\usr\\bin;${Process.env.PATH}` ?

**Comment by AnonymousWP** [comment]
And why has nobody of the team replied or looked into this yet? Do we need to mention them? This is a very critical bug I'd say and 5 days or a week of radio silence.

**Comment by andreasmuelder** [comment]
@niik could you have a look at this?

**Comment by ParadoxV5** [comment]
I believe my issue has the same root cause:
```
error: cannot spawn gpg: No such file or directory
error: gpg failed to sign the data
fatal: failed to write commit object
```
GPG is in `PATH` and `%LOCALAPPDATA%\GitHubDesktop\app-3.4.1-beta1\resources\app\git\cmd\git.exe commit` in Command Prompt commits normally.
Setting `gpg.program` to an absolute path also works this issue around.

**Comment by Lulalaby** [comment]
@ParadoxV5's fix is gold, setting this in my global git config helped (i'm using ssh):
```ini
[gpg]
	format = ssh
	program = C:\\Program Files (x86)\\GnuPG\\bin\\gpg.exe
[gpg.ssh]
	program = C:\\Program Files\\OpenSSH\\ssh-keygen.exe
[gpg.x509]
	program = C:\\Program Files (x86)\\GnuPG\\bin\\gpgsm.exe
```

**Comment by nordowl** [comment]
What worked for me was adding this in my global git config:
```.gitconfig
[gpg.ssh]
	program = C:\\Program Files\\Git\\usr\\bin\\ssh-keygen.exe

```

**Comment by tidy-dev** [comment]
👋 Sorry for the frustration. This has the same root cause as this [tracking ticket for hooks failing](https://github.com/desktop/desktop/issues/18739). You can [download 3.3.18](https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.18-e85f51b7/GitHubDesktopSetup-x64.exe). It will unfortunately try to auto update. Keep an eye on that hooks tracking ticket for an update, we will try to get a fix out tomorrow.

**Comment by AnonymousWP** [comment]
A new version is out: https://desktop.github.com/release-notes/ so you can update.

**Comment by HotCakeX** [comment]
> A new version is out: https://desktop.github.com/release-notes/ so you can update.

Thank you, just updated and works normally again!
also beta release notes 
https://desktop.github.com/release-notes/?env=beta
