### ISSUE TITLE
F5 to fetch origin

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#18718]
### The feature request

Pressing f5 should fetch origin

### Proposed solution

Pressing f5 should fetch origin

**Comment by steveward** [comment]
@IssueDescription thanks for the issue. You can use `Command/Ctrl+Shift-T` to fetch in GitHub Desktop. You can find the full list of available shortcuts [here](https://docs.github.com/en/desktop/overview/github-desktop-keyboard-shortcuts). I hope that helps!
