### ISSUE TITLE
Authentication failure using PAT

### ISSUE THREAD

**Issue by kylelabowski** [desktop/desktop#18716]
### The problem

I use a PAT to authenticate to GitLab from GitHub desktop. I was able to authenticate to clone/read from my GitLab repositories, but I'm unable to push any new commits. I suspect that I'm using the wrong PAT - I have two different PAT's, and one is read-only, so I may be using that one. But I don't see an option anywhere to enter a new PAT, only an error message.
![image](https://github.com/desktop/desktop/assets/62751616/ca9b19f2-f011-4c09-85e0-8a63abacc019)

### Release version

3.3.18 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Push commit to origin
2. Receive "Authentication failure" error, with no option to enter PAT

**Comment by sergiou87** [comment]
You might need to run `git config --global credential.https://gitlab.com.useHttpPath true` from your command line, then install version 3.4.0 from https://desktop.github.com (we're rolling it out to all users progressively via auto-updates)

**Comment by kylelabowski** [comment]
The 3.4.0 build seems to have fixed it, I was able to enter my new PAT after getting the authentication failure there. Thanks!
