### ISSUE TITLE
Again and again asking of username password while commiting anything

### ISSUE THREAD

**Issue by adrush-khatri** [desktop/desktop#18717]
### The problem

Asking the username and password while commiting anything

### Release version

Version 3.3.18 (x64)

### Operating system

windows 11

**Comment by sergiou87** [comment]
Please, try version 3.4.0 from https://desktop.github.com (we're rolling it out to all users progressively via auto-updates)

If you're using GitLab repositories, you might need to run `git config --global credential.https://gitlab.com.useHttpPath true` from your command line

**Comment by Rotem-Konstantinos** [comment]
> Please, try version 3.4.0 from https://desktop.github.com (we're rolling it out to all users progressively via auto-updates)
> 
> If you're using GitLab repositories, you might need to run `git config --global credential.https://gitlab.com.useHttpPath true` from your command line

This resolved my issue.
Thanks
