### ISSUE TITLE
Show "Open this repository in Explorer" when there are no changes?

### ISSUE THREAD

**Issue by swarupsro** [desktop/desktop#1871]
in github for desktop [windows] version we can access file repository directory directly in our computer but in beta version we can't do that .. please add this feature.

**Comment by shiftkey** [comment]
@swarupsro it's not quite clear to me what we're referring to. Could you please elaborate (with screenshots) on this feature?

**Comment by swarupsro** [comment]
First Check : Github For Desktop
![screenshot_66](https://cloud.githubusercontent.com/assets/7780919/26723023/4e8c7b60-47b4-11e7-96f7-1c660e2136f0.jpg)
we can go directly to file manager but in beta version of Github for Desktop we can't go the file manager.

**Comment by shiftkey** [comment]
@swarupsro that link was removed as part of the UI redesign. There's other ways to do this from the new app:

 - Menu: **Repository** | **Open in Explorer/Finder**
 - keyboard shortcut - see menu item

I'll let @donokuda or @niik chime in on their feels about this UI change.

**Comment by hazendaz** [comment]
Just to add my two cents...the current spaceship icon and no files selected in the window are pretty useless.  At least the link to open provides value to me as a user.  I'm sure I'll become an expert over time with keyboard shortcuts and those are important but links are just as important in guiding those less familiar on how to use the application.  It's like having self documentation right in the view.
