### ISSUE TITLE
Browser-based login should use PKCE

### ISSUE THREAD

**Issue by leastprivilege** [desktop/desktop#1872]
I really like your login experience - especially the one via the browser (IMHO the old-school username/password is not needed at all).

But please use PKCE for your OAuth request to protect the callbacks from code interception.

see 

https://tools.ietf.org/html/rfc7636
https://tools.ietf.org/html/draft-ietf-oauth-native-apps-11

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by shiftkey** [comment]
@leastprivilege as I understand it, this requires changes to the client and server to add support, right? 

If so, this is a lot more than just making changes to GitHub Desktop.

**Comment by onovotny** [comment]
It requires a server to support, and is usually optional on the client. The client can send the PKCE parameters on the auth, then for code redemption, the IdP most honor it. I don't believe there's any requirement that the client must use PKCE unless the server chooses to enforce that.

**Comment by shiftkey** [comment]
> It requires a server to support

There isn't really much point tracking an issue here until the server supports it, and we'd need buy-in from other teams to take this further. I'm figuring out who to loop in about this, stay tuned.

**Comment by leastprivilege** [comment]
Agreed. First your security guys must be convinced that PKCE is a useful feature for your oauth server ;)

 Then they can make it optional, and once the client supports it, the can make it mandatory to avoid downgrading.

**Comment by billygriffin** [comment]
Hi folks, we discussed this with our security team and we've evaluated this as relatively low risk. As such, we don't think it should be prioritized relative to other work we have planned. However, we will continue to evaluate the risk on an ongoing basis and consider prioritizing this in the future. Thanks for weighing in, we really appreciate it.
