### ISSUE TITLE
Official Linux version support instead of a fork.

### ISSUE THREAD

**Issue by Hridoy-EL** [desktop/desktop#18724]
### The feature request

If the whole project is open source, then why isn't there a Linux version available? I was working with the fork for a long time, but it turns out that those versions have a limitation on the OAuth enabled organizations. This official app doesn't have that issue. So, it would be really great if we could have an official build for Linux based distros.

### Proposed solution

I guess a lot of GitHub users are also Linux user. So having an official Linux build of this app will help a lot of people. Please build a Linux version of this app officially so that we Linux users can have this app too.

**Comment by sergiou87** [comment]
There are no plans to add official support for Linux, but if anything changes you can also follow along with https://github.com/desktop/desktop/issues/1525 for updates about an official Linux release.
