### ISSUE TITLE
Cant login on different os after changing passworld

### ISSUE THREAD

**Issue by PWaksman** [desktop/desktop#18726]
### The problem

So I got a new laptop (mac) for the company, where they asked me to login with my github account and create an ssh key.
Ok, so since I didn't use github for ages, I went over the normal process of reseting the passworld. Which was already extremelly slow.
You change the passworld, it say it was changed successfully, then I try to login on a different computer with different browser and different os, and it keep saying the passworld is wrong,
So I went back to my personal windows, login successfully in github, went back on the mac, can't login.
went back on github, update the passworld again, went back on mac, got the ip block becasue to many failure....
Really?

It is like you change your passworld, but it has a huge delay to update the server, in the mean time you get blocked if you try from another computer.

Don't tell me about browser cache, its another computer with another OS. And yes, I make sure the keyboard is set correctly and wrote down the passworld in a text editor just in case it was not having the same out put for the symbols.

That is just ridiculous. If there is such delay, add this kind of stuff at the email like "please wait bewteen 10 to 15 minutes before trying again, to allow our servers to sync up".

So what probably happens is the OS and IP are different and it falls under the security stuff to avoid account theft. Which would be fine if it works properly, but get locked for false positive? it should allow me to unlock it from here (personal lap top with windows where I'm already logged in). Now I can't work, great.

### Release version

browser

### Operating system

Mac 14.5

**Comment by sergiou87** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
