### ISSUE TITLE
fatal: Could not write new index file

### ISSUE THREAD

**Issue by Readmit0** [desktop/desktop#18732]
### The problem

I keep getting these errors when I try to change a file and commit to master.

### Release version

3.4.0

### Operating system

Windows 10

### Steps to reproduce the behavior

It happens at random when I make changes.

### Screenshots

![image](https://github.com/desktop/desktop/assets/129572688/44d86b77-bf0c-4501-a751-08583eae7155)

**Comment by tidy-dev** [comment]
👋 @Readmit0 Thanks for reaching out. Is this repository stored on an kind of cloud storage sometimes they can causes errors like this?

([Related issue caused by cloud storage](https://github.com/desktop/desktop/issues/6036))
