### ISSUE TITLE
Github desktop is not case sensitive with branch names

### ISSUE THREAD

**Issue by BrunogalliTP** [desktop/desktop#18731]
### The problem

Github is case sensitive and lets you create the two branches with same name but with different case, for example if there are two branches, one named "branch-name" and another "BRANCH-NAME". But github desktop is not case sensitive and mistakes it as the same branch and this generates malfunction, showing commits of one as local and cant push them to remote.

### Release version

Version 3.4.0 (arm64)

### Operating system

macOS Sonoma 14.5

**Comment by steveward** [comment]
Thanks for the report @BrunogalliTP. Git (and therefore GitHub Desktop) doesn't handle case-sensitive branch names well on Windows and macOS (since the filesystems are not case-sensitive). 

What does the output of `git branch -a` show from the command line?
