### ISSUE TITLE
local hooks stopped working after updating to latest verison.

### ISSUE THREAD

**Issue by eyalpazu** [desktop/desktop#18739]
### The problem

local hooks stopped working after updating to the latest version (Version 3.4.0 (x64)).
The command line works without problems, but it fails to find Python when using the GitHubDesktop GUI.
Error message: "/usr/bin/env: ‘python’: No such file or directory"

### Release version

Version 3.4.0 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Create local hook that uses python.
path: .git/hooks/prepare-commit-msg
And try commit using GitHubDesktop.

### Screenshots

![GitHubDesktopProblem](https://github.com/desktop/desktop/assets/55686040/4b9ea3bd-cadc-48cf-b83d-624efe5a323b)

**Comment by andylwelch** [comment]
My pre-commit hooks also failed after updating to `3.4.0` in Windows. I get `command not found` for the tools that used to work, e.g. `npm`, `yarn`. I have been attempting fixes related to path `C:\Program Files\Git\bin` and the import order without any luck. Following this thread now for any more ideas.

**Comment by ivoyip1101** [comment]
> My pre-commit hooks also failed after updating to `3.4.0` in Windows. I get `command not found` for the tools that used to work, e.g. `npm`, `yarn`. I have been attempting fixes related to path `C:\Program Files\Git\bin` and the import order without any luck. Following this thread now for any more ideas.

I have same problem after updating to 3.4.0 in Windows!

**Comment by jroach-cordel** [comment]
I'm running into this issue when trying to run pwsh.exe as well.

**Comment by CalebSmith0801** [comment]
Same issue here. I have to use the exact file path in my hooks for it to work now.

**Comment by ciso-davidpham** [comment]
Same issue, wsl2 pre-commit hooks working just fine until this latest update, I've checked the environment variables and everything is setup correctly, pointing to where the git binary is in AppData, getting
 '/usr/bin/env: ‘bash’: No such file or directory'

**Comment by splitice** [comment]
Best part is github in all their wisdom doesnt publish older builds. So if you get auto-updated to a broken version you better find a new client.

**Comment by andylwelch** [comment]
I found this download url worked for [v3.3.18](https://central.github.com/deployments/desktop/desktop/3.3.18/win32). Also, rename the `Update.exe` and it will break the auto-update process...

**Comment by glundgren93** [comment]
I think this could've been the root cause.
https://github.com/desktop/desktop/pull/18676

**Comment by tidy-dev** [comment]
👋 The embedded version of Git was recently updated for security reasons. Does anyone have the latest version ([2.45.2](https://www.git-scm.com/)) Git installed and can successfully run the hooks from the command line?

**Comment by TheMikeyRoss** [comment]
I have the latest git `2.45.2` on windows and I have the latest github desktop version `3.4.0` and I'm still having the same issues where any command I use in a git hook will result in a `command not found` error

**Comment by fbastien** [comment]
@TheMikeyRoss With your setup, does this error only occur within GitHub Desktop, or does it also occur when executing `git commit` command lines?

**Comment by TheMikeyRoss** [comment]
@fbastien It only occurs within the github desktop app. When I make a commit via the terminal the husky hooks run successfully and I face no issues.

I even installed Atlassian Sourcetree to test it out and I faced no issues. So I'm 100% confident the issue is strictly happeniing when I try to make a commit with the Github Desktop app.

**Comment by fbastien** [comment]
Thanks for the clarification

**Comment by master-lou** [comment]
Hello,
maybe this will help someone, I ran into the issue of command not found after I updated to 3.4.0, I spent most of yesterday trying to get it to work with no success, at the end, I deleted the local repository, and cloned it from remote, everything is back to normal, I could commit, merge, and everything expected from GithubDesktop is working
so delete your repository ( you can commit your work from CLI ) and clone a new one

**Comment by asfo** [comment]
> Hello, maybe this will help someone, I ran into the issue of command not found after I updated to 3.4.0, I spent most of yesterday trying to get it to work with no success, at the end, I deleted the local repository, and cloned it from remote, everything is back to normal, I could commit, merge, and everything expected from GithubDesktop is working so delete your repository ( you can commit your work from CLI ) and clone a new one

In the case you use Husky, you just "uninstalled it" so, it's not a real fix, you need to run again `npm run prepare` (or something like that) and then the error will show up again...

**Comment by tidy-dev** [comment]
@asfo I tried adding a simple husky pre-commit hook with no luck reproducing this issue. Would you (or anyone) mind sharing your hook setup that I might be able to reproduce it?

**Comment by CalebSmith0801** [comment]
@tidy-dev My `.husky\pre-commit` file looks like so:
```
#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx.cmd lint-staged -q
```

This results in the following error
```
.husky/pre-commit: line 4: npx.cmd: command not found
husky - pre-commit hook exited with code 127 (error)
```

[EDIT] 
`npx.cmd` is in `C:\Program Files\nodejs\` which I have set in my system PATH variable. This used to work before v3.4.0.

**Comment by TheMikeyRoss** [comment]
> npx.cmd is in C:\Program Files\nodejs\ which I have set in my system PATH variable. This used to work before v3.4.0.

@CalebSmith0801 It seems PATH variables are ignored in the latest update

**Comment by MeridianGH** [comment]
> > npx.cmd is in C:\Program Files\nodejs\ which I have set in my system PATH variable. This used to work before v3.4.0.
> 
> @CalebSmith0801 It seems PATH variables are ignored in the latest update

I can confirm this, it looks like an issue with MinGW replacing/overwriting the path.

I'm getting the following error message when trying to commit with a husky commit-msg hook (see [my other comment on this](https://github.com/desktop/desktop/issues/12586#issuecomment-2148191965)):
```
.husky/commit-msg: line 4: npx.cmd: command not found
husky - commit-msg script failed (code 127)
husky - command not found in PATH=/mingw64/libexec/git-core:/mingw64/bin:/usr/bin:/c/Users/[my username]/bin:/mingw64/bin:/mingw64/usr/bin:undefined
```

The `undefined` at the end of the `PATH` makes me a bit suspicious... Is the Windows `PATH` supposed to be appended there?

I tried downgrading to `Version 3.3.14 (x64)` and the hook worked again. But that is definitely no permanent solution.

EDIT: Yes, it looks like the Windows `PATH` is definitely missing. I tried echoing the `PATH` from within the hook while running `Version 3.3.14 (x64)` and it had the entirety of the Windows `PATH` appended:
```
/mingw64/libexec/git-core:/mingw64/bin:/usr/bin:/c/Users/[my username]/bin:/mingw64/bin:/mingw64/usr/bin:/c/Program Files/Mozilla Firefox:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files/WireGuard:/c/Program Files/Docker/Docker/resources/bin:/c/Program Files/dotnet:/c/Program Files/nodejs:/c/Program Files/Git/cmd:/c/Program Files/Git/bin:/c/Users/[my username]/AppData/Local/Microsoft/WindowsApps:/c/Users/[my username]/AppData/Local/GitHubDesktop/bin:/c/Program Files/Git/cmd:/c/Program Files/Git/bin:/c/Users/[my username]/AppData/Local/JetBrains/Toolbox/scripts:/c/Users/[my username]/AppData/Roaming/npm:/c/Users/[my username]/AppData/Local/Microsoft/WindowsApps
```

**Comment by TheBlubb14** [comment]
> > > npx.cmd is in C:\Program Files\nodejs\ which I have set in my system PATH variable. This used to work before v3.4.0.
> > 
> > 
> > @CalebSmith0801 It seems PATH variables are ignored in the latest update
> 
> I can confirm this, it looks like an issue with MinGW replacing/overwriting the path.
> 
> I'm getting the following error message when trying to commit with a husky commit-msg hook (see [my other comment on this](https://github.com/desktop/desktop/issues/12586#issuecomment-2148191965)):
> 
> ```
> .husky/commit-msg: line 4: npx.cmd: command not found
> husky - commit-msg script failed (code 127)
> husky - command not found in PATH=/mingw64/libexec/git-core:/mingw64/bin:/usr/bin:/c/Users/[my username]/bin:/mingw64/bin:/mingw64/usr/bin:undefined
> ```
> 
> The `undefined` at the end of the `PATH` makes me a bit suspicious... Is the Windows `PATH` supposed to be appended there?
> 
> I tried downgrading to `Version 3.3.14 (x64)` and the hook worked again. But that is definitely no permanent solution.
> 
> EDIT: Yes, it looks like the Windows `PATH` is definitely missing. I tried echoing the `PATH` from within the hook while running `Version 3.3.14 (x64)` and it had the entirety of the Windows `PATH` appended:
> 
> ```
> /mingw64/libexec/git-core:/mingw64/bin:/usr/bin:/c/Users/[my username]/bin:/mingw64/bin:/mingw64/usr/bin:/c/Program Files/Mozilla Firefox:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files/WireGuard:/c/Program Files/Docker/Docker/resources/bin:/c/Program Files/dotnet:/c/Program Files/nodejs:/c/Program Files/Git/cmd:/c/Program Files/Git/bin:/c/Users/[my username]/AppData/Local/Microsoft/WindowsApps:/c/Users/[my username]/AppData/Local/GitHubDesktop/bin:/c/Program Files/Git/cmd:/c/Program Files/Git/bin:/c/Users/[my username]/AppData/Local/JetBrains/Toolbox/scripts:/c/Users/[my username]/AppData/Roaming/npm:/c/Users/[my username]/AppData/Local/Microsoft/WindowsApps
> ```

seems the same as https://github.com/desktop/desktop/issues/18701#issuecomment-2147972434

**Comment by sergiou87** [comment]
Thank you all for digging into this. If it's related to the PATH, it might be caused by these changes: https://github.com/desktop/dugite/pull/563

We'll keep digging 🕵

**Comment by MeridianGH** [comment]
@TheBlubb14 Yup, that seems to be it!

**Comment by sergiou87** [comment]
Ok I think we've got it… that PR I linked in my previous comment changes the way we grab and modify the `PATH` environment variable… or more accurately the `Path` env variable.

`process.env` allows case-insensitive access to variables on Windows, but when we do `...process.env` we break that, and after that point we cannot use `env.PATH` to access the existing path on Windows, we should use `env.Path`.

Thank you all again for your help diagnosing the issue 🙇‍♂  We'll try to get a fix out ASAP

**Comment by TheMikeyRoss** [comment]
@sergiou87 You get 'em Loofy 🤩

**Comment by paulvales** [comment]
same problem with `/usr/bin/env: ‘php’: No such file or directory` when committing

**Comment by tidy-dev** [comment]
👋 We believe we have fix. Would any one mind verifying with this [3.4.1-test1 build](https://centralreleases.blob.core.windows.net/github-desktop/releases/3.4.1-test1-50936ea7/GitHubDesktopSetup-x64.exe)?

**Comment by JMazurie** [comment]
> 👋 We believe we have fix. Would any one mind verifying with this [3.4.1-test1 build](https://centralreleases.blob.core.windows.net/github-desktop/releases/3.4.1-test1-50936ea7/GitHubDesktopSetup-x64.exe)?

This build fixed the issue for me (described in #18768), thanks a bunch !

**Comment by MeridianGH** [comment]
> 👋 We believe we have fix. Would any one mind verifying with this [3.4.1-test1 build](https://centralreleases.blob.core.windows.net/github-desktop/releases/3.4.1-test1-50936ea7/GitHubDesktopSetup-x64.exe)?

+1, this build seems to fix the issue. Echoing the `PATH` also now shows the correct path with the Windows `PATH` appended again. Thanks for the fix! 👍

**Comment by mkahvi** [comment]
> 👋 We believe we have fix. Would any one mind verifying with this [3.4.1-test1 build](https://centralreleases.blob.core.windows.net/github-desktop/releases/3.4.1-test1-50936ea7/GitHubDesktopSetup-x64.exe)?

Confirmed to be working for me as well (for #18705).

**Comment by JLeverDynaGen** [comment]
> 👋 We believe we have fix. Would any one mind verifying with this [3.4.1-test1 build](https://centralreleases.blob.core.windows.net/github-desktop/releases/3.4.1-test1-50936ea7/GitHubDesktopSetup-x64.exe)?

Coming from #18701, this build fixes signed commits

**Comment by TheMikeyRoss** [comment]
![YES](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExbWF1aXl1Y3N4cTl5NnNvczZscTgwZzJ4OHEybnhqN2xxMmN6bWlrdCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/DffShiJ47fPqM/giphy.gif)

**Comment by tidy-dev** [comment]
Released! You can now upgrade to 3.4.1 ([download here](https://desktop.github.com/)) 🎉 

Thanks again everyone! 💖

**Comment by anupam-softeon** [comment]
Thanks alot for fixing this issue. Much awaited fix. 🎉🎉🎉

**Comment by east-shine** [comment]
@tidy-dev I'm still having issues with version 3.4.1(arm64)

**Comment by tidy-dev** [comment]
@east-shine I am sorry to hear that. It is likely a different root cause. Could you open a new issue to track it? (Please remember to include logs)

**Comment by exde37b2** [comment]
maybe this helps others.
Having in use 3.4.1, I had run 
_nvm install fancy.new.version
nvm use fancy.new.version_

and ended up with the same problem described above. After running
_nvm use good.old.version_

GitHubDesktop is working again

**Comment by MeridianGH** [comment]
> maybe this helps others.
> Having in use 3.4.1, I had run 
> _nvm install fancy.new.version
> nvm use fancy.new.version_
> 
> and ended up with the same problem described above. After running
> _nvm use good.old.version_
> 
> GitHubDesktop is working again

Have you checked the official Husky instructions for use with NVM?
https://typicode.github.io/husky/how-to.html#node-version-managers-and-guis

**Comment by rahul-singh-bv** [comment]
This issue is with GitHub desktop. When I commit from CLI, it works. I just downgraded GitHub Desktop and it works but does not work with 3.4.2

**Comment by jflemingframe** [comment]
still happening to me

**Comment by hqxc-bacon** [comment]
![image](https://github.com/user-attachments/assets/2f835a46-f917-47a3-ac86-9287461ce36f)

**Comment by hqxc-bacon** [comment]
> ![图像](https://private-user-images.githubusercontent.com/155507069/356538951-2f835a46-f917-47a3-ac86-9287461ce36f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTU1NDAsIm5iZiI6MTcyMzE5NTI0MCwicGF0aCI6Ii8xNTU1MDcwNjkvMzU2NTM4OTUxLTJmODM1YTQ2LWY5MTctNDdhMy1hYzg2LTkyODc0NjFjZTM2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwOTIwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmFlNWM1ZGYzNDczYTY2OGU1ZjY5NjEwNmY2M2U0OTEyNTYzOTFlMzg4MDI4MGY5M2E1YjgwY2ZmNmFhMDZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WfIbeOObY6PuitFulbGUHT5Uj91GezUDeyifZNGs5x4)

![image](https://github.com/user-attachments/assets/568a139e-a7a9-4b09-8169-2c74f27a6c42)
I still have the problem and the solutions above don't fix it

**Comment by Drumstix42** [comment]
Also still having the issue here. Works in CLI, works in VSCode, broken in Github Desktop. Used to work in Github Desktop just fine.

Weirdly this comment helps https://github.com/desktop/desktop/issues/12586#issuecomment-892436293 but it's not a great solution, as it makes the change OS specific...

**Comment by petter-eikeland** [comment]
I am also having this issue on 3.4.3 ARM version (Apple Silicon). Downgrading to v. 3.3.18 fixed the issue for me

**Comment by octavemuhirwa** [comment]
I am also having this issue on 3.4.5 (arm64) apple m2.

**Comment by pidark** [comment]
I have the same issue Version 3.4.4 on Ubuntu 24.10.
I've solved editing  /usr/share/applications/github-desktop.desktop 


[Desktop Entry]
Name=GitHub Desktop
Comment=Simple collaboration from your desktop
GenericName=GitHub Desktop
**Exec=bash -c "PATH=MY_PATH github-desktop"**
Icon=github-desktop
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Utility;
MimeType=x-scheme-handler/x-github-client;x-scheme-handler/x-github-desktop-auth;x-scheme-handler/x-github-desktop-dev-auth;


Where you can find MY_PATH and replace it with 

`echo $PATH `

on terminal.

Hope this help someone.

**Comment by ColeDCrawford** [comment]
Yep, this is still an issue on 3.4.9 (Mac M1)

**Comment by toyota-167** [comment]
> .cmd

i got the same issue like this and i fix it by follow your solution, and the error is gone. thanks a lot for you.

![Image](https://github.com/user-attachments/assets/e8d22edb-6701-40db-adde-07880740ff87)

**Comment by thelsevier** [comment]
I used to have this issue in v3.4.16. I upgraded to v3.4.18 (arm64, on a Mac) and commit just worked. Nothing in the release notes about it, but I'm glad it's fixed now 👍
