### ISSUE TITLE
Git LFS Authentication behaviour change between 3.3.16 and 3.3.17

### ISSUE THREAD

**Issue by morwoen** [desktop/desktop#18734]
### The problem

I am using a private Git LFS server which uses GitHub to authenticate & authorise the users. On GH Desktop versions up to (including) 3.3.16 when pushing to LFS the `Authorization` header used [basic authorization format](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization#basic) with the password value being a token. That token appeared to be the token GH Desktop was using to push to GH.

This feature was extremely useful as it meant that the usage of a private LFS server was completely transparent to developers and didn't need to create tokens manually.

Since version 3.3.17 (last tested with 3.3.19-beta2) when I try to push I get an Authentication failed modal asking for a username and password for the private LFS server url.

![image](https://github.com/desktop/desktop/assets/5834873/a0d25478-226d-44fb-aae4-2e4f999864c4)

If I create a token and supply it as a password (user read-only, no additional access is required by the server) the credentials get stored in Windows Credentials Store and pushing is possible again. This is not ideal as now every developer has to create a token manually and provide it to GH Desktop. 

After comparing 3.3.16 and 3.3.17 I have identified #18579 as the only change that touches LFS explicitly, however, the effect I found wasn't mentioned in any release notes so it seems unintended.

### Release version

3.3.17

### Operating system

Windows 11

### Log files

[2024-06-01.desktop.beta.log](https://github.com/user-attachments/files/15522046/2024-06-01.desktop.beta.log)

**Comment by sergiou87** [comment]
I'm afraid that previous behavior posed a high-severity vulnerability and therefore had to be fixed: https://github.com/desktop/desktop/security/advisories/GHSA-2g23-3f32-64gr

I understand how it could be convenient in certain scenarios like the one you describe, but it would otherwise be dangerous.

**Comment by morwoen** [comment]
Thanks for confirming 👍
