### ISSUE TITLE
Error when pull/push 

### ISSUE THREAD

**Issue by ToanTQ2019** [desktop/desktop#18752]
### The problem

when i pull push code on ver 3.3.4, error cant 
![image](https://github.com/desktop/desktop/assets/91871956/34e26300-6549-43bc-a835-fd6a0231d552)

### Release version

ver 3.3.4

### Operating system

win10

**Comment by sergiou87** [comment]
Closing as duplicate of #18729 

Would you mind dropping your log files there? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

Thank you 🙏

**Comment by Nic-vdwalt** [comment]
Getting the same error
