### ISSUE TITLE
Fail to authenticate via browser

### ISSUE THREAD

**Issue by MaximeS5** [desktop/desktop#18750]
### The problem

When I try to sign into GitHub.com on the app via my browser (Google Chrome), it opens a tab that closes immediately then prompt an error on the app stating: "requires authentication".

### Release version

3.4.0 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1 -  Go to File -> Options...
2 - In Accounts, click on "Sign into Github.com"
3 - Click on "Continue with browser"

### Log files

[2024-06-03.desktop.production.log](https://github.com/user-attachments/files/15535775/2024-06-03.desktop.production.log)

**Comment by tidy-dev** [comment]
@MaximeS5 These kind of errors are usually due to a firewall interferring with the authentication network calls. Do you have a firewall and if so, can you turn it off and try again to verify if that is the issue?

**Comment by MaximeS5** [comment]
Hi @tidy-dev, unfortunately, I can't turn off my firewall as I am on my company's computer. That should be the problem, thanks !

**Comment by steveward** [comment]
Thanks for the update @MaximeS5. Are you able to reach out to someone in your company to see if they can allow GitHub Desktop through your firewall? Unfortunately there isn't much we can do about this from our end.

**Comment by MaximeS5** [comment]
I'll try to make it work with my IT dept. Thank you for your help !
