### ISSUE TITLE
Github desktop not correctly creating symlink files in win10

### ISSUE THREAD

**Issue by TheNumenorean** [desktop/desktop#18751]
### The problem

When checking out a branch with a soft symlink on it, windows does not see the file as a symlink, just a regular file with a path in it. If i recreate the symlink, git reports no change in the file, but the symlink starts working.

### Release version

3.4.0

### Operating system

win10

### Steps to reproduce the behavior

1. Create a branch
2. Create a new relative soft symlink to another directory in the repo.
3. switch back to main
4. switch back to the branch
5. Try to follow the symlink

**Comment by TheMikeyRoss** [comment]
Try updating to v3.4.1

**Comment by TheNumenorean** [comment]
Tried, didnt seem to help. On the latest version i still had to manually delete the invalid files and create the symlinks.

**Comment by steveward** [comment]
@TheNumenorean thanks for the issue. Symlinks can be problematic with Git on Windows. Are the symlinks pointing to a file within the repository? Did you run `git config --global core.symlinks true` to enable support?

**Comment by TheNumenorean** [comment]
Sorry for the delay, yes the links are pointing to a file within the same repo, the path is relative, and github at least acknowledges them as being symlinks. I also have duplicated the issue on another computer, and explicitly tried running `git config --global core.symlinks true` and then checking out the new branch, still getting the same problem.

**Comment by TheNumenorean** [comment]
But, i tested it using the git CLI as well which got me curious when it still didn't work, and after some more experimenting i have found that somehow the local git config had `core.symlinks=false`. No idea why that would have had a value in it, since i certainly didnt set it, but after fixing that it is working now.

(i.e. run `git config core.symlinks true` instead)
