### ISSUE TITLE
Add "sync fork" option

### ISSUE THREAD

**Issue by wiiznokes** [desktop/desktop#18754]
### The feature request

Its anoying to always have to go the the github fork page, click on the sync fork button, and fetch changes. I would like a button that does all this in Github Desktop.

### Proposed solution

.

**Comment by tidy-dev** [comment]
@wiiznokes Thank you for reaching out. We don't have a fork button, but you can [check out this comment on a similar issue on a couple ways you can bring your fork up to date with it's upstream](https://github.com/desktop/desktop/issues/18361#issuecomment-2020498793).
