### ISSUE TITLE
Updating to latest GitHub Desktop on macOS makes GitHub Desktop forget the passwords

### ISSUE THREAD

**Issue by stephane-s1** [desktop/desktop#18759]
### The problem

I updated to the latest GitHub Desktop version (Version 3.4.0 (x64)) as suggested in the GitHub Desktop application and when I then tried to pull things, the app complained that it could not authenticate and requested me to enter my account name and password.

It was working fine before the update.

I was able to find the ID and password in the keychain as created by the app. So there's no reason the app itself should not be able to find the entries it created. Or if some changes were made to the application (bundle identifier, codesignatures, etc.) this is the kind of things that should be told to the end user before performing the updates of the GitHub Application.

### Release version

Version 3.4.0 (x64)

### Operating system

macOS 14.4.1 (23E224)

### Steps to reproduce the behavior

1. Update GitHub Desktop.app from itself.
2. Try to pull things.

=> you need to authenticate when it wasn't necessary before.

**Comment by tidy-dev** [comment]
@stephane-s1 After reauthenticating, is everything working as expected?

**Comment by stephane-s1** [comment]
Yes.

**Comment by tidy-dev** [comment]
Great. Thanks for confirming. There was a recent security release and an unfortunate side effect is that some users of third party hosts may be required to re-authenticate.
