### ISSUE TITLE
ssh-keygen error with 3.4.0

### ISSUE THREAD

**Issue by ben-HMRC** [desktop/desktop#18753]
### The problem

When I try to commit I get: "error: cannot spawn ssh-keygen: No such file or directory error: 
fatal: failed to write commit object". 

Committing worked fine before and nothing changed about the configuration that I'm aware of. This started on version 3.4.0. Committing from Git Bash works fine.

### Release version

3.4.0

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Commit a change to a repo
2. Error pops up

### Log files

[2024-06-04.desktop.production.log](https://github.com/user-attachments/files/15545343/2024-06-04.desktop.production.log)

**Comment by wehrlean** [comment]
Similar Error see #18701

**Comment by tidy-dev** [comment]
Closing in favor of https://github.com/desktop/desktop/issues/18701
