### ISSUE TITLE
Cannot access gitlab repository

### ISSUE THREAD

**Issue by MacleodMoreSapere** [desktop/desktop#18762]
### The problem

I have been using this for a project for months with no issues, but today it required a sign-in to my account that doesn't seem to work/is very user unfriendly

### Release version

3.4.0

### Operating system

Windows 11 business

### Steps to reproduce the behavior

Trying to publish branch or fetch origin

**Comment by steveward** [comment]
@MacleodMoreSapere thanks for the report. Once you authenticate again using a GitLab token it should get things working. The prompt to authenticate again was caused by a change in a recent release. Let me know if you continue to have issues after authenticating again.
