### ISSUE TITLE
Unable to push my changes through github desktop

### ISSUE THREAD

**Issue by cnidadavole-conga** [desktop/desktop#18761]
### The problem

Unable to push my changes through github desktop. Getting following error:
.git/hooks/pre-push: line 32: node: command not found
error: failed to push some refs to 'https://github.com/congaengr/cpq-core'
![image](https://github.com/desktop/desktop/assets/63345908/193dc6f6-f863-49fb-b685-e7c7d80882b5)

### Release version

Version 3.4.0 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

Commit changes and getting the errors

**Comment by jasonSchroeder89** [comment]
This also breaks using third-party hook-tools such as Husky.

**Comment by steveward** [comment]
Thanks for the report @cnidadavole-conga. We are tracking this in https://github.com/desktop/desktop/issues/18739 -- please follow along there for updates about this issue.
