### ISSUE TITLE
Cannot run 

### ISSUE THREAD

**Issue by tylers-epilog** [desktop/desktop#18763]
### The problem

I have a bash script that is used as a pre-commit hook. This pre-commit hook looks like this:

```
#!/bin/sh

echo path: $PATH

pwd=$(pwd -W)
echo pwd: $pwd
sh $pwd/.githooks/pre-commit
```

I don't believe the contents of `.githooks/pre-commit` are too important except to say that they make calls to `cargo` because it's a Rust program.

When I try to make a commit in GitHub Desktop, I get the following error:

> path: /mingw64/libexec/git-core:/mingw64/bin:/usr/bin:/c/Users/TylerS/bin:/mingw64/bin:/mingw64/usr/bin:undefined
> pwd: C:/Users/TylerS/Documents/rust/epilog-print-api
> ~/Documents/rust/epilog-print-api ~/Documents/rust/epilog-print-api
> Checking formatting...
> ./scripts/commit-check-formatting.sh: line 5: cargo: command not found

Note that the `PATH` contains `undefined` which is a pretty good indication that the `PATH` is messed up.

Note that if I try to make a commit through PowerShell, the commit hook (and thus the commit) work as expected with no errors.

This did not used to be an issue. It started sometime in the past week or so.

### Release version

3.4.0

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Make some changes
2. Try to make a commit in GitHub Desktop
3. Error message appears

### Log files

[2024-06-04.desktop.production.log](https://github.com/user-attachments/files/15571015/2024-06-04.desktop.production.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/97969355/b85efff3-0501-4f84-b9dd-cb373fa5c2d2)

**Comment by tidy-dev** [comment]
@tylers-epilog Sorry for the frustration. Closing this in favor of this [tracking ticket](https://github.com/desktop/desktop/issues/18739). You can [download 3.3.18](https://centralreleases.blob.core.windows.net/github-desktop/releases/3.3.18-e85f51b7/GitHubDesktopSetup-x64.exe). It will unfortunately try to auto update. Keep an eye on that tracking ticket, we will try to get a fix out tomorrow.
