### ISSUE TITLE
i cant pull request . my repo is gitlab

### ISSUE THREAD

**Issue by yapching** [desktop/desktop#18775]
### The problem

Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.

### Release version

Version 3.4.1 (x64)

### Operating system

windows 11

### Screenshots

![1123](https://github.com/desktop/desktop/assets/20835163/1813d8b0-7b14-4596-97a7-b8d1aa23a064)

**Comment by sergiou87** [comment]
@yapching does the app prompt you for credentials?

**Comment by Avoltance** [comment]
App was not constitent on when it shows you the credential prompt. I got multiples inputs from my team using GitHub Desktop than they had to press multiple times the main action "fetch/pull/push" button before getting it, often otherwise displaying the error popup in the screenshot above.

**Comment by yapching** [comment]
Now is ok .. i think theres update yester in guthub desktop

yapkumosoft

**Comment by steveward** [comment]
@yapching glad to hear things are working now!
