### ISSUE TITLE
Add/Connect multiple account

### ISSUE THREAD

**Issue by TolgaDurman** [desktop/desktop#18779]
### The feature request

I work for a company that recently gave me a new email address and wants me to use it to sign up for a Github account. Every time I want to access my personal account, it annoys me to sign out, log in using the web client, choose one of my accounts, return to the client, and edit the profile to reflect the new account.

### Proposed solution

Improve the user experience for users by including the option to connect multiple accounts.

**Comment by tidy-dev** [comment]
@TolgaDurman Thanks for reaching out. We are tracking feedback for this issue in https://github.com/desktop/desktop/issues/3707. Thus, I am closing in favor of that one.
