### ISSUE TITLE
"Tree view" in UI for all commits and branches

### ISSUE THREAD

**Issue by Duna** [desktop/desktop#18776]
### The feature request

SourceTree and GitKraken provide a UI representation for all commits; we need this feature in our app as well.

### Proposed solution

UI Tree View

### Additional context

All other apps have this feature, why is missing from here?

**Comment by tidy-dev** [comment]
@Duna Thank you for reaching out! We are tracking feedback for a history graph in https://github.com/desktop/desktop/issues/9452. Thus, I am closing in favor of that issue.
