### ISSUE TITLE
Add a Github Desktop package to AUR

### ISSUE THREAD

**Issue by yvan-sraka** [desktop/desktop#1878]
Hello everybody,

I think it might be easy to create a GitHub Desktop package for ArchLinux and put it on [ArchLinux User Repository (AUR)](https://aur.archlinux.org/). Do you think this is a good idea? I can of course help to do that!

Thank you in advance,

**Comment by joshaber** [comment]
Hi @yvan-sraka! We'd welcome Linux support (cc #1525) but we don't have any Linux expertise on the team. So any publishing or packaging would need to be automated.

**Comment by hamaminatu** [comment]
I agree :D

**Comment by yvan-sraka** [comment]
AUR is often the first place where packages are available before being on the list of community packages, just like the [atom](https://www.archlinux.org/packages/community/x86_64/atom/) editor!
Installing a package available on AUR is often done by a wrapper around `pacman` (the default handler for ArchLinux packages) such as `yaourt`.

Some of the work done by `yaourt`, when installing a package, can download the latest software sources before building it, and packing it for `pacman`a bit like the [FreeBSD Ports](https://en.wikipedia.org/wiki/FreeBSD_Ports) system or the more recent [Homebrew](https://brew.sh/index_fr.html) for MacOS.
These packages can be compiled from a snapshot of a Git repository, and are marked with the suffix `-git`.
For example :
- https://aur.archlinux.org/packages/ghi/ (`tar.gz` of v1.2.0)
- https://aur.archlinux.org/packages/ghi-git/ (git snapshot)

In this case, the creation of the package does not necessarily have to be "automated", we just have to write the few scripts of the AUR package and maybe add the installation of the package to the continuous integration tests.
I could write these scripts when the Linux version will be efficient, but maybe it would be appropriate to create a new repository to store these configuration files separately?

Thank you for all your answers,

**Comment by shiftkey** [comment]
Given this is dependent on #1525 I'm going to mark this as something to evaluate in the future, once we've made some inroads on Linux support. Going to close this out to ensure the issue tracker isn't overwhelming us.

**Comment by hron84** [comment]
@joshaber What expertise do you need for the Linux version? I've ten years in Linux and I know CI/CD systems a little bit, maybe I can help or just provide you some pointers for this problem if you consider taking a community help for this issue.

**Comment by joshaber** [comment]
@hron84 https://github.com/desktop/desktop/issues/1525 is the tracking issue for Linux support. From my perspective, for Linux support to land, we would need:

1. CI
2. Automated release builds
3. Someone who's willing to be pinged to look at Linux-specific PRs 😄

**Comment by mikelpint** [comment]
@yvan-sraka I am working on an AUR package for GitHub Desktop. The name is github-desktop and the current version is 0.7.1-beta4. It is based in the gengjiawen/desktop repository.

**Comment by billygriffin** [comment]
I'm going to remove `future-proposal` here as this issue is referenced in #1525 and that's still a dependency for this to move forward. Thanks for the input folks.
