### ISSUE TITLE
GitHub Desktop got uninstalled autometically.

### ISSUE THREAD

**Issue by shyed2001** [desktop/desktop#18780]
### The problem

A few months ago my GitHub Desktop just vanished from my computer, then came back again. Yesterday I could not git push to the main. Today the update for GitHub desktop got blocked as a virus. Now it got uninstalled. What to do now?

### Release version

GitHub Desktop 3

### Operating system

Windows 10

### Additional context

A few months ago my GitHub Desktop just vanished from my computer, then came back again. Yesterday I could not git push to the main. Today the update for GitHub desktop got blocked as a virus. Now it got uninstalled. What to do now?

**Comment by shyed2001** [comment]
GitHub Desktop 3.4.1, now can not find the github desktop app. Yesterday it was showing  - Not sure who the author is, about  my Git Push attempts. Then the restart GitHub Desktop to update linked showed up. after pressing that it closed and after that anti virus blocked the software. Then it vanished again. My AVG and Avast antivirus software are disabled now. but problem persists.

**Comment by steveward** [comment]
@shyed2001 thanks for the report. It's likely that your antivirus software interfered with the update. I would try a fresh reinstallation.

Here's how to do that:

1. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
2. Go to `%AppData%` and delete the `GitHub Desktop` directory
3. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that does not get things working.

**Comment by gzeeel** [comment]
Hello @steveward, I am having the same issue as @shyed2001. 
- Had troubles with the 'command not found' few days ago.
- Then yesterday GitHub Desktop closed itsefl while I was away from keyboard, and I couldn't launch it again.

I've done the steps 1 & 2 from your last message, but when trying to reinstall with the .exe, I get an error, here are the logs from SquirrelSetup.log.

I tried with Administrator rights and with the .msi file too. The .msi file does nothing

![image](https://github.com/desktop/desktop/assets/56316342/fdb516cc-aed7-40a3-b941-522aa39d13b4)

`15908> 2020-11-28 13:05:59> ApplyReleasesImpl: Starting fixPinnedExecutables
15908> 2020-11-28 13:05:59> ApplyReleasesImpl: fixPinnedExecutables: newCurrentFolder: app-0.0.308
15908> 2020-11-28 13:05:59> ApplyReleasesImpl: fixPinnedExecutables: enumerating path C:\Users\antho\AppData\Roaming\Microsoft\Windows\Start Menu failed: System.UnauthorizedAccessException: L'accès au chemin d'accès 'C:\Users\antho\AppData\Roaming\Microsoft\Windows\Start Menu\Programmes' est refusé.
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileSystemEnumerableIterator 1.AddSearchableDirsToStack(SearchData localSearchData)
   à System.IO.FileSystemEnumerableIterator 1.MoveNext()
   à System.Collections.Generic.List 1..ctor(IEnumerable 1 collection)
   à System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   à System.IO.DirectoryInfo.GetFiles(String searchPattern, SearchOption searchOption)
   à Squirrel.UpdateManager.ApplyReleasesImpl.fixPinnedExecutables(SemanticVersion newCurrentVersion)`

**Comment by shyed2001** [comment]
> @shyed2001 thanks for the report. It's likely that your antivirus software interfered with the update. I would try a fresh reinstallation.
> 
> Here's how to do that:
> 
> 1. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
> 2. Go to `%AppData%` and delete the `GitHub Desktop` directory
> 3. Reinstall GitHub Desktop from http://desktop.github.com
> 
> Let me know if that does not get things working.

I had to change my PC, so I did not have that issue again. Nice to know how to manually uninstall Girhub Deskto.

**Comment by tidy-dev** [comment]
Thank you for checking back. Glad you got things working.
