### ISSUE TITLE
The app periodically asks me for my repo credentials

### ISSUE THREAD

**Issue by neolib** [desktop/desktop#18799]
### The problem

I am not sure if it is "by design", but to me it's a serious problem now.

I believe the credentials should be asked once like what I have in Terminal.

Yesterday, GD asked again for my git credentials and I don't know why it always failed my username and password. Now every time I try Repository->Pull or something similar, it greets me with an error dialog:

Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Settings.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.

I believe this problem occurred first in version 3 series.

### Release version

3.4.1

### Operating system

macOS Sonoma

**Comment by neolib** [comment]
BTW, I have no problems if I do `git pull` using a Terminal window.

**Comment by neolib** [comment]
Oh, yesterday I had many (about 20) git-credential-osxkeychain processes after I resumed macOS from sleep. Each one of the processes asked me for my macOS account password to access the keychain. I had to use Activity Monitor to kill them all.

**Comment by neolib** [comment]
Log off and log in does not help. Even a reboot won't.

**Comment by sergiou87** [comment]
Is your repository hosted on GitHub?

 Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by neolib** [comment]
There too many git related processes!

![截屏2024-06-11 08 35 39](https://github.com/desktop/desktop/assets/10727052/7b7bce15-eadc-44ce-8d1d-cc7b4accb052)
![截屏2024-06-11 08 35 35](https://github.com/desktop/desktop/assets/10727052/d03ea367-9a42-4409-99b7-c45ab1d437dd)
![截屏2024-06-11 08 35 29](https://github.com/desktop/desktop/assets/10727052/a45b40fb-52a6-4d4c-977f-fac39be19616)

**Comment by neolib** [comment]
> Is your repository hosted on GitHub?
> 
> Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

Oh, I forgot to reply this.

I did not use GitHub, but I believe GD is also designed for generic repos. My repos are hosted by a third party provider.

**Comment by niik** [comment]
Hey @neolib, we just shipped GitHub Desktop 3.4.2-beta2 to our [beta channel](https://desktop.github.com/beta/). This includes support for using [Git Credential Manager](https://gh.io/gcm). It's currently off by default but you can enable it in Settings under the advanced tab. We believe this will address the authentication problems outlined in this issue.

<img width="608" alt="Screenshot of Desktop's advanced preferences section with a highlight around the new option to enable Git Credential Manager" src="https://github.com/desktop/desktop/assets/634063/5d4da983-7663-49dd-bb7b-ce51ee9d2d3a" />

When Git Credential Manager (GCM) is enabled all credentials for third-party (i.e. Azure Devops, BitBucket, GitLab etc) will be handled, and stored, outside of GitHub Desktop. GCM supports browser-sign in to many popular services and will avoid the need to create personal access tokens (PATs). 

Please download our beta version from https://desktop.github.com/beta/ to give this a go and please report back with your experience. We'll be collecting feedback in our beta channel which will inform when we make this available to all users. Installing the beta version will not clear your preferences or tracked repositories and you can switch to the production version by simply downloading the latest version from https://desktop.github.com.

**Comment by pver** [comment]
This beta version and activating the credential manager solved my authentications problems as well now

**Comment by steveward** [comment]
I'm going to close this out, but let us know if you're still having issues after setting up the Git Credential Manager @neolib.
