### ISSUE TITLE
Settings uses outdated "Preferences" name in "Open...in your external editor" link

### ISSUE THREAD

**Issue by obviousaurus** [desktop/desktop#18793]
### The problem

Not a bug, just text that needs updating: "Preferences" should be the newer "Settings" in the _Open the repository in your external editor_ panel

### Release version

3.4.1

### Operating system

macOS 14.5

### Steps to reproduce the behavior

1. Navigate to a branch with no local changes
2. Read the text under "Open the repository in your external editor"

Expected:
"Select your editor in **Settings**"

Actual:
"Select your editor in Preferences"

### Screenshots

<img width="500" alt="image" src="https://github.com/desktop/desktop/assets/17000416/be7c64ea-47f4-4552-8891-be85f57d35d3">

<img width="500" alt="image" src="https://github.com/desktop/desktop/assets/17000416/8bb5ccf2-3fea-4c16-beb2-b4d8988ad7e3">

### Additional context

It's possible "Preferences" is still used in other places of the app, as well.

**Comment by sergiou87** [comment]
Good catch! Probably missed it in #16907
