### ISSUE TITLE
Unable to install GitHub Desktop onto my "E://" Drive

### ISSUE THREAD

**Issue by echoless3484** [desktop/desktop#18795]
### The problem

Hey there, trying to install GitHub Desktop onto my internal hard drive labelled "E://" and I am unable, the installer just goes right to my "C://" drive.

### Release version

Version 3.4.1 (x64)

### Operating system

Windows 11 Pro Version 23H2 (OS Build 22631.3672)

**Comment by steveward** [comment]
@echoless3484 thanks for the issue. Currently it is not possible to customize the installation location of GitHub Desktop. This is a constraint in the installation framework we use, Squirrel.Windows (see https://github.com/Squirrel/Squirrel.Windows/issues/314). At this time we do not have plans of changing the installer we use for GitHub Desktop.
