### ISSUE TITLE
Displaying info about running commit-hook

### ISSUE THREAD

**Issue by JonasJore** [desktop/desktop#18791]
### The feature request

It would be cool to have info about commit-hooks running for repositories with this set-up after clicking on commit, before pushing the commit.

### Proposed solution

Today, when the blue commit button is clicked in repos with configured commit-hooks, the user is just presented with the faded commit-button with spinner enabled until the commit-hook is done running. It would be nice for the user to have some info about what commit hook is running, what tasks it is performing and if it runs okay or not.

**Comment by steveward** [comment]
Thanks for the feedback @JonasJore! I'm going to add this to https://github.com/desktop/desktop/issues/9351 where we are tracking providing output for hooks and giving an escape hatch if they fail.
