### ISSUE TITLE
calling fetch origin on any branch seem to trigger pull origin on other branches as well

### ISSUE THREAD

**Issue by BitByAVampire** [desktop/desktop#18794]
### The problem

say i have a branch called 'develop' and another branch called 'feature'. if the feature branch has updates from the remote repo when i call fetch origin on develop, the updates to the feature branch are pulled. i don't agree with this behaviour as it is different from the git command line. 

further more, the updates when they are pulled in this way do not trigger my post-merge hook. so it is another problem with it. 

### Release version

Version 3.4.1

### Operating system

macOS 14.5

**Comment by steveward** [comment]
@BitByAVampire thanks for the issue. Git by default does fetch all branches, unless a branch is specific (i.e. `git fetch origin main`).

It sounds like you're more interested in disabling automatic fast-forward, which has been previously discussed in https://github.com/desktop/desktop/issues/8146. If you'd like to disable fast-forwarding you can set this config option:

`git config --global merge.ff false`

This will apply to all repositories -- you can omit the global if you want to set it on a per-repo basis. I hope that helps!

**Comment by BitByAVampire** [comment]
im fine with the fetch step. its the pull step. i dont like that it pulls on other branches just because i clicked fetch origin on my current branch.
