### ISSUE TITLE
Cant push to origin

### ISSUE THREAD

**Issue by elenix** [desktop/desktop#18804]
### The problem

I have commit my git and ready to push it to the origin which is I put on my local disk. but its said Authentication failed. I have tried login and logout many times but still didn't work. But when I try using command line push using Git Bash, its working. Please fix the windows app, I prefer graphical than using command line

### Release version

 3.4.1

### Operating system

Windows 11

### Screenshots

![Screenshot 2024-06-10 154203](https://github.com/desktop/desktop/assets/13548129/8e893b47-51d8-40d2-86a0-2323355363a4)

**Comment by sergiou87** [comment]
Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by elenix** [comment]
[2024-06-10.desktop.production.log](https://github.com/user-attachments/files/15765068/2024-06-10.desktop.production.log)
This the log file i found inside the folder

**Comment by steveward** [comment]
@elenix here's the error I'm seeing:

```
2024-06-10T07:41:56.172Z - error: [ui] `git -c credential.helper= push origin master:master --progress` exited with an unexpected code: 128.
stderr:
fatal: detected dubious ownership in repository at 'E:/Unity/UTMSPACE-VR-PICO/.git'
'E:/Unity/UTMSPACE-VR-PICO/.git' is on a file system that does not record ownership
To add an exception for this directory, call:

	git config --global --add safe.directory E:/Unity/UTMSPACE-VR-PICO/.git
````

You should be able to resolve this by running the `git config --global --add safe.directory E:/Unity/UTMSPACE-VR-PICO/.git` command mentioned in that error. Let me know if that doesn't get things working.

**Comment by elenix** [comment]
I see. I have added that git command line and the problem is fixed. Thanks

**Comment by steveward** [comment]
Glad to hear things are working now!
