### ISSUE TITLE
Access denied when trying to access start menu

### ISSUE THREAD

**Issue by Devcom439** [desktop/desktop#18801]
### The problem

When trying to open the setup file for Github Desktop I get a popup window with an error. When I checked the log file that was given it told me permission was denied when trying to access the start menu. The possible problem is that I'm on a computer within an organization. Any help on this?

### Release version

I have no idea, but the download link is "https://central.github.com/deployments/desktop/desktop/latest/win32"

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Download the setup file at `"https://desktop.github.com/"`.
2. Open the file.

### Log files

9008> 2024-01-15 13:25:53> Program: Starting Squirrel Updater: --install .
9008> 2024-01-15 13:25:54> Program: Starting install, writing to C:\Users\bas.devlies\AppData\Local\SquirrelTemp
9008> 2024-01-15 13:25:54> Program: About to install to: C:\Users\bas.devlies\AppData\Local\Discord
9008> 2024-01-15 13:25:54> SingleGlobalInstance: Grabbing lockfile with timeout of 00:00:10
9008> 2024-01-15 13:25:54> CheckForUpdateImpl: Reading RELEASES file from C:\Users\bas.devlies\AppData\Local\SquirrelTemp
9008> 2024-01-15 13:25:54> CheckForUpdateImpl: Remote version 1.0.9030 differs from local 
9008> 2024-01-15 13:25:54> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
9008> 2024-01-15 13:25:54> ApplyReleasesImpl: Writing files to app directory: C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030
9008> 2024-01-15 13:26:00> ApplyReleasesImpl: Moving file C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\lib\net45\d3dcompiler_47.dll to C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\d3dcompiler_47.dll
9008> 2024-01-15 13:26:00> ApplyReleasesImpl: Moving file C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\lib\net45\app.ico to C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\app.ico
9008> 2024-01-15 13:26:00> ApplyReleasesImpl: Moving file C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\lib\net45\chrome_100_percent.pak to C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\chrome_100_percent.pak
9008> 2024-01-15 13:26:00> ApplyReleasesImpl: Moving file C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\lib\net45\chrome_200_percent.pak to C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\chrome_200_percent.pak
9008> 2024-01-15 13:26:00> ApplyReleasesImpl: Moving file C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\lib\net45\ffmpeg.dll to C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\ffmpeg.dll
9008> 2024-01-15 13:26:00> ApplyReleasesImpl: Moving file C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\lib\net45\Discord.exe to C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\Discord.exe
9008> 2024-01-15 13:26:00> ApplyReleasesImpl: Moving file C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\lib\net45\icudtl.dat to C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\icudtl.dat
9008> 2024-01-15 13:26:00> ApplyReleasesImpl: Moving file C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\lib\net45\installer.db to C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\installer.db
9008> 2024-01-15 13:26:00> ApplyReleasesImpl: Moving file C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\lib\net45\libEGL.dll to C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\libEGL.dll
9008> 2024-01-15 13:26:00> ApplyReleasesImpl: Moving file C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\lib\net45\libGLESv2.dll to C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\libGLESv2.dll
9008> 2024-01-15 13:26:00> ApplyReleasesImpl: Moving file C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\lib\net45\resources.pak to C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\resources.pak
9008> 2024-01-15 13:26:00> ApplyReleasesImpl: Moving file C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\lib\net45\snapshot_blob.bin to C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\snapshot_blob.bin
9008> 2024-01-15 13:26:00> ApplyReleasesImpl: Moving file C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\lib\net45\updater.node to C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\updater.node
9008> 2024-01-15 13:26:00> ApplyReleasesImpl: Moving file C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\lib\net45\vk_swiftshader.dll to C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\vk_swiftshader.dll
9008> 2024-01-15 13:26:00> ApplyReleasesImpl: Moving file C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\lib\net45\vulkan-1.dll to C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\vulkan-1.dll
9008> 2024-01-15 13:26:00> ApplyReleasesImpl: Moving file C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\lib\net45\v8_context_snapshot.bin to C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\v8_context_snapshot.bin
9008> 2024-01-15 13:26:00> ApplyReleasesImpl: Moving file C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\lib\net45\vk_swiftshader_icd.json to C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\vk_swiftshader_icd.json
9008> 2024-01-15 13:26:01> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\Discord.exe]
9008> 2024-01-15 13:26:02> Utility: Process Started: C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\Discord.exe --squirrel-install 1.0.9030, pid 13172
9008> 2024-01-15 13:26:05> Utility: Received exitcode 0 from process C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\Discord.exe
9008> 2024-01-15 13:26:05> ApplyReleasesImpl: ran C:\Users\bas.devlies\AppData\Local\Discord\app-1.0.9030\Discord.exe, pid 11540
9008> 2024-01-15 13:26:05> ApplyReleasesImpl: Starting fixPinnedExecutables
9008> 2024-01-15 13:26:05> ApplyReleasesImpl: fixPinnedExecutables: newCurrentFolder: app-1.0.9030
9008> 2024-01-15 13:26:05> ApplyReleasesImpl: fixPinnedExecutables: enumerating path C:\Users\bas.devlies\AppData\Roaming\Microsoft\Windows\Start Menu failed: System.UnauthorizedAccessException: Access to path C:\Users\bas.devlies\AppData\Roaming\Microsoft\Windows\Start Menu\Programma's denied.
   by System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   by System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   by System.IO.FileSystemEnumerableIterator`1.MoveNext()
   by System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   by System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   by System.IO.DirectoryInfo.GetFiles(String searchPattern, SearchOption searchOption)
   by Squirrel.UpdateManager.ApplyReleasesImpl.fixPinnedExecutables(SemanticVersion newCurrentVersion)
9008> 2024-01-15 13:26:05> ApplyReleasesImpl: Updating shortcut C:\Users\bas.devlies\Desktop\Discord.lnk
9008> 2024-01-15 13:26:05> ApplyReleasesImpl: Fixing up tray icons
9008> 2024-01-15 13:26:05> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.9030
9008> 2024-01-15 13:26:05> ApplyReleasesImpl: cleanDeadVersions: exclude current version folder app-1.0.9030

### Screenshots

![image](https://github.com/desktop/desktop/assets/145280509/3feab864-13fb-4cdb-a22b-c1e1d28a3f32)

**Comment by gzeeel** [comment]
Same issue I reported in comments of [https://github.com/desktop/desktop/issues/18780](https://github.com/desktop/desktop/issues/18780)

**Comment by steveward** [comment]
@gzeeel that portion of the log file looks like it's related to Discord, not GitHub Desktop. Are you running any antivirus or other security software on this machine that could be blocking the installation?

**Comment by gzeeel** [comment]
@steveward Yes I am running Avast. I cannot disable it as it is a business computer. Indeed, I've seen that the logs are talking about Discord, but it's all the logs that have been opened by the GitHubDesktopSetup-x64.exe when it failed

**Comment by steveward** [comment]
Are you able to take a look at Avast to see if GitHub Desktop is being blocked?

https://support.avast.com/en-us/article/use-antivirus-blocked-allowed-apps

Can you also share the specific version of Avast you are running? I'd like to reach out to them to see if we can prevent this from happening.

**Comment by Devcom439** [comment]
> Are you able to take a look at Avast to see if GitHub Desktop is being blocked?

Avast is not installed on this computer. I also cannot find some other anti-virus software that is installer on this laptop.

**Comment by Devcom439** [comment]
> @.gzeeel that portion of the log file looks like it's related to Discord, not GitHub Desktop. Are you running any antivirus or other security software on this machine that could be blocking the installation?

The log file, for some reason, indeed looks like the installation of some other software like `Discord`. This is not the case, because when I clicked the "open log file" button it showed me that log. It has more to do with the `"Squirrel updater"` I think.

**Comment by steveward** [comment]
@Devcom439 apologies, I mentioned @gzeeel but was intending to reply to you. Discord and GitHub Desktop both use the Squirrel installer, and the log file is shared.

There is a Desktop-specific log file here:

`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`

Can you see if that's available?

You mentioned belonging to an organization -- are there any restrictions in place? Is there anyone you can reach out to about that?

**Comment by Devcom439** [comment]
@steveward Wow. I didn't really expect this, but for some reason `the installer works now`. I really appreciate your help so far. I also checked the path you gave me (`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`), but it does not exist on my machine. To elaborate more on the organization part: I'm still in school and (of course) there are admins in the work group. There might be a possibility that they get alerted when someone tries to download an executable that's blocked or not known and that they manually accepted it. I highly doubt that since there are more than 250+ students in my school. 

**Screenshot from just now**
![image](https://github.com/desktop/desktop/assets/145280509/60f612a4-7f1f-4e4c-87a6-22ba583d03da)

**Comment by steveward** [comment]
I'm glad to hear things are working for you now. I'm going to close this out, but let me know if you run into any further issues.
