### ISSUE TITLE
Prosody (inserts into to Postgres Database)

### ISSUE THREAD

**Issue by rcraiss** [desktop/desktop#18816]
### The problem

Prosody ist in Lua geschrieben und setzt HTML/XML-Nachrichten in Textform um (chat über XMPP). Ich habe eine Postgres-Datenbank, die die Daten übernimmt. Die Datenbank ist "prosody", die Tabelle heisst "prosodyarchive" und in einem Feld "value" werden die Textnachrichten gespeichert. Leider wird beim Import das HTML-Tag mitgeliefert, was das Lesen erschwert. Ich suche nach einer Möglichkeit, dies in einem Importfilter abzuwenden. Hättet ihr eine Idee über eine Componente in Lua über ein PGSQL-Skritp die HTML-Tags zu entfernen.

### Release version

Version 3.4.1 (x64)

### Operating system

Fedora 40

### Steps to reproduce the behavior

<message to='lbx1889@chat.web.intrafrigo.com' id='purple9e8db21a' type='chat' from='dispo@chat.web.intrafrigo.com/TBwo8d6xcqto' xml:lang='en'><body>neuer Test mit dem Versucht HTML zu umgehen</body></message>

### Additional context

Im Prinzip müsste nur der body-Text erhalten bleiben. Versuche es mit Lula in den Griff zu bekommen waren mißlungen. VIelleicht klappt es mit PG Postgresql. Es sollen nämlich lediglich die Archivdaten verkürzt werden. Die Datenkommunikation darf nicht davon betroffen sein.

**Comment by steveward** [comment]
@rcraiss this issue tracker is for GitHub Desktop. It sounds like you are looking for help for a project hosted on GitHub. I would recommend asking for help on https://github.community.
