### ISSUE TITLE
Unable to login Github Desktop

### ISSUE THREAD

**Issue by johnrosik** [desktop/desktop#18813]
### The problem

I tried to login with my github account at my Desktop, it worked in my laptop. First time i received a message that said i had insufficient memory to finish the command, but i initialized Github Desktop as admin, and now there is a different problem. Just load infinitely.

### Release version

3.4.1

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Go to File
2. Click on Options
3. Click on Sign into Github.com
4. Continue with Browser
5. Authorized
6. Infinite loading.

### Log files

[2024-06-11.desktop.production.log](https://github.com/user-attachments/files/15781248/2024-06-11.desktop.production.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/68259151/be591f55-30ee-483c-9496-73c589735931)

**Comment by steveward** [comment]
Thanks for the report @johnrosik. I'm seeing this error in the log:

```
2024-06-11T02:07:55.988Z - info: [ui] [AppStore] adding account johnrosik (João Rosiak) to store
2024-06-11T02:07:55.989Z - error: [ui] Error adding account 'johnrosik'
Error: N�o h� recursos de mem�ria dispon�veis suficientes para processar este comando.
```

This error can happen if there are too many credentials in the Credential Manager. See [this workaround](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#not-enough-resources-error-when-signing-in). Let me know if that does not get things working.

**Comment by johnrosik** [comment]
Removed the credentials, but still not working.

**Comment by steveward** [comment]
@johnrosik can you share the log file again so I can verify you're still encountering the same error?

**Comment by johnrosik** [comment]
[2024-06-14.desktop.production.log](https://github.com/user-attachments/files/15844384/2024-06-14.desktop.production.log)

Here, i just tried to Login, started Github Desktop as Admin, and got the log.

**Comment by johnrosik** [comment]
And again, just spinned infinitely for like 10 minutes and nothing.

**Comment by steveward** [comment]
Unfortunately the log file isn't showing much information about why authentication may be failing, but I'm not longer seeing the previous error. Is there anything in your network that could be causing this, like a firewall or proxy?

**Comment by johnrosik** [comment]
I dont know, how can i check this?

**Comment by steveward** [comment]
@johnrosik I'm sorry for the delay. Are you still encountering this issue? If this is a corporate network/machine I would recommend reaching out to someone in your organization to see if there's anything that could be causing this.
