### ISSUE TITLE
Authentication failed for Azure Devops: no longer lets me enter the username

### ISSUE THREAD

**Issue by mattumotu** [desktop/desktop#18811]
### The problem

I am attempting to work on an existing repo, the Auth has failed (I assume PAT expired).
Not usually an issue, I have regenerated creds in azure but Github Desktop won't let me enter the username any more, instead it appears hardcoded to my organisation name.
Previously you could enter username and password, now it only lets you enter password.
Therefore I can't authenticate to the repo.

### Release version

3.4.1 (x64)

### Operating system

Windows 10 Enterprise

### Steps to reproduce the behavior

I am connecting to a git repo hosted on azure. This has been working for months, with the occasional re-auth (presumably as pat's expire). I usually regenerate credentials in azure and use that username and password and everything is ok.
When I had to re-auth today it no longer lets me enter the username, instead it appears set to my organisation name and unchangeable.

![image](https://github.com/desktop/desktop/assets/8266061/5833c219-94c1-4fe6-86c3-825fb0f76ed0)

I notice in azure when you clone a repo it provides the url like `https://<org name>@dev.azure.com/<org name>/<project name>/_git/<repo name>`.:
![image](https://github.com/desktop/desktop/assets/8266061/db58d976-522c-44ec-bc4e-2c501d4c2ca8)

I'm _guessing_ github desktop is taking `<org name>@dev.azure.com` and using <org name> as the username, which is incorrect. (Although I could be barking up the wrong tree)

Based on https://github.com/desktop/desktop/blob/development/docs/integrations/azure-devops.md (linked on the 'authentication failed' popup), it suggests using `https://<username>@dev.azure.com/<username>/<project_name>/_git/<repository_name>` but the images on that page still show you can enter the username and password, not fixed username.

Command line git seems to be working, when I did `git fetch` it opened a visual studio popup asking me to log on to azure,  did that and command line works, but github desktop still can't auth.

How can I specify the username so I can auth to my repo?

### Log files

[2024-06-10.desktop.production - clean.log](https://github.com/user-attachments/files/15774305/2024-06-10.desktop.production.-.clean.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/8266061/dff54000-c446-4819-ae08-994eafb02754)
Can't enter username, used to be able to

**Comment by mattumotu** [comment]
Looks like this was introduced in https://github.com/desktop/desktop/pull/18651 (based on description). I could do with a workaround

**Comment by mattumotu** [comment]
Similar issue reported in https://github.com/desktop/desktop/pull/18651, which says it was fixed in 3.4.0, this issue is in 3.4.1 so either different issue or reintroduced

**Comment by sergiou87** [comment]
@mattumotu that seems to be git's behavior, actually. We introduced that because git asked Desktop for the password only (assuming that part in the URL was the username already).

You can open the Repository -> Repository Settings… menu, and change the remote URL to remove that part (`@` sign included). That should change the behavior and allow you to enter your own username.

Let us know if that helps 🙏

**Comment by mattumotu** [comment]
@sergiou87 That seems to work thanks.
bit annoying I've got to update all repos but at least I'm unblocked!

it's a bit odd that git command line worked, and azure devops gives you the wrong url, but maybe it was a recent change and they haven't caught up yet

**Comment by sergiou87** [comment]
Just curious, did you try to just enter your PAT with that org as username? I think that's what Desktop used to do before…

In any case, closing this now. I'm happy it works for you now 😄

**Comment by mattumotu** [comment]
I've set it back to the original url, and tried with just the password and it works.
How bizarre. 
I didn't even try that, I'm no security expert but I _assumed_ using the wrong username wouldn't work. 
I guess that's an interesting choice from azure.

Thanks for your help and explanation of how desktop works 'under the hood'
