### ISSUE TITLE
commit message text area is really too small

### ISSUE THREAD

**Issue by janimatic** [desktop/desktop#18817]
### The feature request

Six years later, can you finally increase the size of the commit message text area ?
It was requested many times....
https://github.com/fork-dev/Tracker/issues/193
We spend time describing the commits correctly, this is important...
Thanks!

### Proposed solution

Increasing the size of commit text area doesn't sound too difficult...
Obviously a resizable area would be even better, but I don't really care personnally, as long as the area is large enough : 
Let's make it simple and quick to fix !

**Comment by steveward** [comment]
@janimatic thanks for the issue. There's a previous issue about expanding the commit message area, see https://github.com/desktop/desktop/issues/1646. I'm going to reference this there and close this out.
