### ISSUE TITLE
Unable to push changes

### ISSUE THREAD

**Issue by madhuk1218** [desktop/desktop#18812]
### The problem

Hi,

I am unable to push my changes as it is prompting for password. When entered correct password, it is throwing error. Attached are the log files.

### Release version

Version 3.4.0

### Operating system

Windows

### Log files

[2024-06-10.desktop.production.log](https://github.com/user-attachments/files/15777536/2024-06-10.desktop.production.log)
![Screenshot 2024-06-10 141648](https://github.com/desktop/desktop/assets/133898471/888b3b50-23dd-4f48-ad76-eb8a5a65238e)

**Comment by steveward** [comment]
@madhuk1218 it looks like you're authenticating to a BitBucket repository. Are you using a token to authenticate? See [this guide](https://github.com/desktop/desktop/blob/development/docs/integrations/bitbucket.md) for the steps needed to create a token. Let me know if that does not get things working.
