### ISSUE TITLE
Misleading alert text

### ISSUE THREAD

**Issue by BJORN-VINTHER** [desktop/desktop#18815]
### The problem

When I want to delete a local branch it prompts me with the test:
> Delete **remote** branch `xyz`?
> This action cannot be undone

In this case the branch is not remote, it is local. I haven't pushed anything. It is misleading and can be confusing whether I am deleting something that affects others.

It correctly differentiated between local and remote branches in earlier versions

### Release version

Version 3.4.1 (x64)

### Operating system

Windows

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. Create a new branch without pushing it
3. Delete the branch
4. The alert will now show with the text that it is a __remote__ branch

### Screenshots

![image](https://github.com/desktop/desktop/assets/97097933/b4202fc8-7d4a-4d12-aed9-5ddae7cd29dc)

**Comment by tidy-dev** [comment]
@BJORN-VINTHER Thanks for the report. This has been fixed in https://github.com/desktop/desktop/issues/18706. It is already shipped to beta so likely will be in one of the next production release.
