### ISSUE TITLE
Commit Size

### ISSUE THREAD

**Issue by RamonaTigier** [desktop/desktop#18829]
### The feature request

Since I often have commits that are larger than 2GB, I always have to try out by eye how many parts I divide the commit into. It would be nice if the changes tab also displayed the size of the currently checked files in addition to the number of files.

### Proposed solution

In addition to the number of files, the changes tab shows how much memory the currently selected files together require.

### Additional context

i.e.
![image](https://github.com/desktop/desktop/assets/8641007/b8698ea4-0f8f-4d33-94e4-33dd824f514f)

**Comment by steveward** [comment]
Thanks for the issue @RamonaTigier. I'll mark this as an enhancement for future consideration.

**Comment by kitt159** [comment]
This issue is similar to #18736.

**Comment by steveward** [comment]
Thanks @kitt159, I'm going to close this out and add it to https://github.com/desktop/desktop/issues/18736.
