### ISSUE TITLE
commit does not work, when comitt sign/verification has been enable

### ISSUE THREAD

**Issue by MKFeuer** [desktop/desktop#18827]
### The problem

my problem is, if i add a file in the folder for the repository on my pc an will be commit that, i got this error message
![Screenshot 2024-06-12 202145](https://github.com/desktop/desktop/assets/91680831/bafc03ec-9ae2-4606-94ee-e263a1113baf)

i have commit sign/verification enabled and with alll other programms like vscode, intellijy IDE worked fine. 

only in Github Desktop not.

i hope this issue will be fixed

### Release version

3.4.1

### Operating system

Windows 11

**Comment by steveward** [comment]
@MKFeuer thanks for the report. Can you verify the GPG path is correct? If you haven't set it in your `.gitconfig` then that's likely the issue. There's a helpful guide [here](https://gist.github.com/xavierfoucrier/c156027fcc6ae23bcee1204199f177da) a user wrote up that walks through configuring GPG with GitHub Desktop.

**Comment by MKFeuer** [comment]
yes i set the right path and my system can resolve the path 

it work in all other programs, but only in github desktop not. 

i looked into the guide and i have followed this steps, but it doesn't work

**Comment by MKFeuer** [comment]
@steveward thanks for you help. 

i founded a solution right now. I have to add the path to gpg into my system variables 


i hope eveyone can help this awnser
