### ISSUE TITLE
gitIgnore not working for folders with "." in the name

### ISSUE THREAD

**Issue by nchettiar** [desktop/desktop#18820]
### The problem

gitIgnore not working for folders with "." in the name such as "API.Tests"

The gitignore entry: "/API.Tests/bin" does not ignore the bin folder here, it works properly for my API/bin folder though..
![image](https://github.com/desktop/desktop/assets/29254311/3832526e-aa55-470f-ae85-33a11756d951)

### Release version

Version 3.4.1 (x64)

### Operating system

windows 11

**Comment by steveward** [comment]
@nchettiar thanks for the issue. Have those files been previously committed in your repository? If so, they won't be ignored until the command `git rm --cached <file>` is run. Let me know if that isn't the case.

**Comment by nchettiar** [comment]
> @nchettiar thanks for the issue. Have those files been previously committed in your repository? If so, they won't be ignored until the command `git rm --cached <file>` is run. Let me know if that isn't the case.

Thank you, I ran the following command: `git rm --cached -r API.Tests/bin` and it worked!
Can you tell me why this needed to be done, vs when it did not need to be done for my other folders?

**Comment by steveward** [comment]
The `git rm --cached` command is necessary only if the files you want to ignore are already being tracked by Git. Since the other files had not yet been tracked by Git they did not have this issue.
