### ISSUE TITLE
Not sensitive to case change in filename

### ISSUE THREAD

**Issue by vincentvanhees** [desktop/desktop#18831]
### The problem

While investigating https://github.com/r-lib/pkgdown/issues/2658 I noticed that GitHub Desktop fails to recognise case changes in filenames.

For example `contributing.md` => `Contributing.md` is not recognised. This is problematic because it makes it extremely hard to make change across repository branches. We first need to delete the file in each branch and then commit the file again with the revised filename. Would it be possible that GitHub Desktop is updated to be case sensitive for file names?

### Release version

Version 3.4.1 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Commit a file to a repo.
2. Change the case of the file name
3. I am not seeing this change in the 'changes' panel of the GitHub Desktop, there is nothing to commit.

**Comment by steveward** [comment]
Thanks for the issue @vincentvanhees. This is the expected behavior of Git -- see [this comment](https://github.com/desktop/desktop/issues/2672#issuecomment-329011490) for a detailed explanation. I'm going to close this out, but let me know if you have any further questions.

**Comment by steveward** [comment]
Also, if you want to rename a file to change the case, you can use this command:

`git mv filename.txt FILENAME.txt`

I hope that helps.
