### ISSUE TITLE
User Account Switcher

### ISSUE THREAD

**Issue by rhopkins-languagebird** [desktop/desktop#18835]
### The feature request

It would be great if we could get a simple user account switcher. I have multiple github accounts that are used over multiple organizations and companies that I contract for. I'd like to be able to easily switch between those accounts without having to go into the settings.

### Proposed solution

I would propose a user account switcher in the top right that when clicked drops down with simple user information and the ability to switch accounts.

**Comment by steveward** [comment]
Thanks for the request @rhopkins-languagebird. We are tracking this in https://github.com/desktop/desktop/issues/3707 -- you can follow along there for updates.
