### ISSUE TITLE
Expanded Branches list should be closed when switching between Changes/History

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1883]
If a user selects the either the Changes/History list from the View menu, the Repo/Branches list should automatically close if they are open.

v 0.5.9, OSX 10.11.5

**Comment by joshaber** [comment]
I _think_ this is fine. Nothing's broken so far as I can tell. I don't know of a use case for it, but I also don't know that it's a problem 😄 

Feel free to re-open if you disagree!
