### ISSUE TITLE
Can't discard changes

### ISSUE THREAD

**Issue by SeanOBrien2702** [desktop/desktop#18834]
### The problem

I am trying to discard changes I made to a PNG file. I tried with github desktop and the command line to get rid of the local change and restore what is in the repository. Initially it was just the one file "Catz_Rabbit_2.png" had the problem where I could not discard the change. I have linked a screen shot showing it has an error with that file when I try changing branches. I tried testing it out with other PNGs by deleting them. When I delete I see that it the symbol beside the name of it in github desktop changes to red which should happen but when I try discarding it will revert to being considered a changed file. 

### Release version

Version 3.4.1 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Change or delete any png file
3. Try to discard changes 

### Log files

[2024-06-14.desktop.production.log](https://github.com/user-attachments/files/15844038/2024-06-14.desktop.production.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/43837594/293c6cef-068b-4d04-9cda-0afc8e3eea95)

### Additional context

When trying to discard the change nothing will happen in github desktop but a version of the file will be put into the recycle bin.

**Comment by SeanOBrien2702** [comment]
I have tried on another machine with the same issue. I also tested other repositories and I am not having any problems.

**Comment by steveward** [comment]
Thanks for the issue @SeanOBrien2702. I'm seeing this in the log file, which aligns with what you're saying:

```
2024-06-14T21:24:08.350Z - error: [ui] `git -c credential.helper= checkout --progress main --recurse-submodules --` exited with an unexpected code: 1.
stderr:
error: Your local changes to the following files would be overwritten by checkout:
	Assets/Hisa Cube Animal/Sprites/Sprites 1.0 & 1.1/Catz_Rabbit_2.png
Please commit your changes or stash them before you switch branches.
Aborting

(The error was parsed as 38: Unable to switch branches as there are working directory changes which would be overwritten. Please commit or stash your changes.)
```

Is there any other application that has these files open? 

If you want to try forcing a discard from the command line you can run `git checkout -- <path/to/file>.  If you want to force a discard for **all** files you can run `git reset --hard HEAD`. Let me know if either of those commands causes the same issue you are experiencing in Desktop.

**Comment by SeanOBrien2702** [comment]
The fixed the issues. I believe the issue was something related to end line differences. I changed my .gitattributes file according to the recommendations in the Handle Line Endings "Get Started" page. I had to reimport the files into the project but I am no longer running into the issue.
