### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by arbyruns** [desktop/desktop#18846]
### The problem

We have a short lived token (7 Days) using Azure DevOps and this is causing authentication failed when the token expires. 

![image](https://github.com/desktop/desktop/assets/2520545/a5f1798f-707d-4353-bb88-8909da29ef1f)

### Release version

3.4.1

### Operating system

Mac Sonoma 

### Steps to reproduce the behavior

1. Have a Azure repo PAT expire

### Log files

```
(The error was parsed as 4: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Settings.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2024-06-19T14:37:58.336Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin (took 1.881s)
2024-06-19T14:37:58.337Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: Authentication failed for 'https://office.visualstudio.com/DefaultCollection/<removed>/_git/client-android/'

(The error was parsed as 4: Authentication failed. Some common reasons include:
```

### Screenshots

![image](https://github.com/desktop/desktop/assets/2520545/a5f1798f-707d-4353-bb88-8909da29ef1f)

**Comment by sergiou87** [comment]
Thanks for your report @arbyruns 

Could you try the latest beta from https://desktop.github.com/beta and on Settings -> Advanced, enable Git Credential Manager? It should make your experience much much better:


![Image](https://github.com/user-attachments/assets/e5f0affb-5e59-452e-ad83-eee710585456)

Please, let us know if that works! 💖

**Comment by diolan12** [comment]
> Thanks for your report @arbyruns
> 
> Could you try the latest beta from https://desktop.github.com/beta and on Settings -> Advanced, enable Git Credential Manager? It should make your experience much much better:
> 
> ![Image](https://private-user-images.githubusercontent.com/1083228/341235610-e5f0affb-5e59-452e-ad83-eee710585456.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMTIxMTAsIm5iZiI6MTcxOTAxMTgxMCwicGF0aCI6Ii8xMDgzMjI4LzM0MTIzNTYxMC1lNWYwYWZmYi01ZTU5LTQ1MmUtYWQ4My1lZWU3MTA1ODU0NTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjFUMjMxNjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmU3NzEwNzM3MWQxZjNiNTZiYmJhZjRhOGRlODFmMmI2MmNkNDc5ZTRmODc3NzZlYTkzYjRjODMxMzM0NDA4ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EuhskW4eCtxkqUc_poo9_bbhPn0bgwG9ftXVWiqTQlw)
> 
> Please, let us know if that works! 💖

I'm having the same issue with failed authentication. My repo is in GitLab and my Personal Access Token is expired.
I tried what you suggest and this works as expected. I can confirm this fix my issue.

**Comment by arbyruns** [comment]
I don't have an active repro at the moment, but will check if this works for me mid next week.

**Comment by arbyruns** [comment]
This worked, thank you!
