### ISSUE TITLE
Facing Authentication error

### ISSUE THREAD

**Issue by Raviraph23** [desktop/desktop#18847]
### The problem

I am using bitbucket as the working repository, after the recent update, my github desktop is showing issues with the repo like.

Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.
.

### Release version

Version 3.4.1 (x64)

### Operating system

Windows 11

**Comment by sergiou87** [comment]
Thanks for your report @Raviraph23 

Could you try the latest beta from https://desktop.github.com/beta and on Settings -> Advanced, enable Git Credential Manager? It should make your experience much much better:


![Image](https://github.com/user-attachments/assets/e5f0affb-5e59-452e-ad83-eee710585456)

Please, let us know if that works! 💖
