### ISSUE TITLE
Browser authentication produces error message "requires authentication"

### ISSUE THREAD

**Issue by ArjunAnilKumar1** [desktop/desktop#18844]
### The problem

Signing in through any browser results in the application displaying "Requires authentication".Even after multiple attempts its not authenticating .

### Release version

Version 3.4.1 (x64)

### Operating system

Windows 10 Enterprise for Virtual Desktops

### Steps to reproduce the behavior

Open GitHub desktop
Go to file > options
Press "Sign into GitHub.com"
Log in on web browser and allow it to open GitHub Desktop
The error message "Requires authentication" appears

### Log files

[2024-06-19.desktop.production.log](https://github.com/user-attachments/files/15900316/2024-06-19.desktop.production.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/159743834/bf65c7f3-87ad-4b9b-92ff-26908ad58665)

**Comment by steveward** [comment]
Thanks for the report @ArjunAnilKumar1. This type of error usually indicates a firewall or proxy is interfering with authentication. Is there anything in your network that could be causing this?

**Comment by ArjunAnilKumar1** [comment]
This is my work laptop so probably yes

**Comment by steveward** [comment]
Thanks for the update. Is there anyone in your organization who you could reach out to about this? Unfortunately this isn't something that we can assist with on our end. You can find a list of IP addresses referenced in [this article](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-githubs-ip-addresses) if that's helpful as well.
