### ISSUE TITLE
Not able to search branch in Compare changes

### ISSUE THREAD

**Issue by febyopen** [desktop/desktop#18855]
### The problem

not able search branch in compare changes screen when we create new pull request

### Release version

release-3.4.2-beta3

### Operating system

mac os

**Comment by utkarsh-unravel** [comment]
I am facing same issue while raising Pull request

**Comment by ranjeet-zyod** [comment]
Is there any other alternative, facing same issue

**Comment by niik** [comment]
👋 Thanks for reaching out. I'm trying to reproduce this but I must be missing something. Could you please add a screen shot of where you're seeing this issue and the steps you're taking to get there?

Cheers!

**Comment by febyopen** [comment]
it's now working fine
