### ISSUE TITLE
Error AcquireCredentialsHandle failed: SEC_E_INTERNAL_ERROR (0x80090304) with any action

### ISSUE THREAD

**Issue by AlekzzR** [desktop/desktop#18853]
### The problem

With any action in Github Desktop an error window appears: fatal: unable to access 'http://git-autotests.sbis.ru/autotests/fed.git/': schannel: AcquireCredentialsHandle failed: SEC_E_INTERNAL_ERROR (0x80090304).
When checking for updates, an Error window also appears, but empty, without details
![image](https://github.com/desktop/desktop/assets/78024857/2893fe82-380b-40b9-9c08-4089daccca02)

Any actions with git via the console or other git clients work

### Release version

3.4.1

### Operating system

Win10/x64

### Steps to reproduce the behavior

Any action: pull, fetch

### Log files

[2024-06-21.desktop.production.log](https://github.com/user-attachments/files/15924013/2024-06-21.desktop.production.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/78024857/38e48819-bb4c-4e11-b231-71cc5c612b82)

**Comment by niik** [comment]
Hey @AlekzzR, thanks for reaching out. This is not an error we're familiar with. Some light googling led me to https://github.com/jeroen/curl/issues/127 and the follow-up issue https://github.com/curl/curl/issues/2262 which seems to point the finger towards client certificates.

Unfortunately this looks to be an issue specific to your environment and as such might be beyond the scope of what we're able to provide support for. Are you able to clone/fetch etc using just Git for Windows in the terminal?

**Comment by AlekzzR** [comment]
Hello, @niik! I did a little research and I came to the conclusion that the problem is on my computer. Github Desktop uses its own version of git. The same error occurs if you install another git client and in the settings you choose not the standard installed git, but an external one. I copied the local git folder to the installed git folder in the Github Desktop folder and the problem went away. More precisely, she is, but I was able to isolate her.

plus, it doesn't work to navigate through PowerPoint links. Also the certificate error

**Comment by niik** [comment]
@AlekzzR Do you know what version of Git you replaced the internal one with? GitHub Desktop currently ships with 2.43.4 in production and 2.45.1 in beta.

**Comment by AlekzzR** [comment]
@niik Hi! System git work in 2.35.1 and this version ok. Fork, which not work too use 2.42 (work if install in settings system ver git). I dont know how check version In GitHub Desktop

**Comment by steveward** [comment]
@AlekzzR are you still encountering this issue or can we close it out as resolved? Thanks.

**Comment by AlekzzR** [comment]
> @AlekzzR are you still encountering this issue or can we close it out as resolved? Thanks.

Hi! You can close it. We decided to delete the CryptoPro software from the computer
