### ISSUE TITLE
Remote origin path containing spaces is truncated on the Repository settings screen

### ISSUE THREAD

**Issue by andrewhenry3** [desktop/desktop#18860]
### The problem

I'm accessing remote repositories through Windows file system, and their paths contain embedded spaces.

Actual access to the remote is OK once git config --add safe.directory is run, and the git config file contains the correct path.

But when the Repository settings screen is brought up, the repository path is only displayed up to the first space, and truncates there.

### Release version

3.4.1 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Under Repository - Repository Settings, enter a file system path containing spaces in Remote - Primary remote repository
Save and return to the screen - the value will be truncated.

**Comment by Rocket4Ship13** [comment]
Under Repository - Repository Settings, enter a file system path containing spaces in Remote - Primary remote repository
Save and return to the screen - the value will be truncated.

- What file is needed?

**Comment by niik** [comment]
Thanks for the report @andrewhenry3, I've opened #18876 to address this bug!
