### ISSUE TITLE
WINGET CLI doesn't work

### ISSUE THREAD

**Issue by Robertblazor** [desktop/desktop#18863]
### The problem

<img width="791" alt="image" src="https://github.com/desktop/desktop/assets/96743273/b8a6dbcd-54e6-49e2-b85d-caee18800905">

### Release version

3.4.1

### Operating system

Windows on x64

### Screenshots

<img width="788" alt="image" src="https://github.com/desktop/desktop/assets/96743273/3bee8735-0748-44bc-8f3e-bcbfbf229e67">

**Comment by Robertblazor** [comment]
I think the winget package manager have the different software than the GitHub Desktop we are talking about.

**Comment by Robertblazor** [comment]
I think it's also kind of funny that I have to upgrade GitHub.GitHubDesktop.Beta within the application as the WINGET package manager doesn't even have the most updated beta version of the software that is owned by the owner of GitHub.

**Comment by niik** [comment]
Hey @Robertblazor, thanks for reaching out. The only official source for GitHub Desktop is the installer located on https://desktop.github.com. We do not publish packaged to WinGet or other package managers. 

While we cannot recommend using unofficial sources you'll have to reach out to the maintainer of that package for support.
