### ISSUE TITLE
Renaming a commit

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#18862]
### The feature request

if you have an old commit message that you want to make more clear, click a button to simply rename it, github desktop does the annoying git command magic in the background

### Proposed solution

Rename commit message button

**Comment by niik** [comment]
Hey @IssueDescription, thanks for reaching out. I would love this feature myself. For now the best tip I can give you is that the most recent commit can easily be undone (which will pop the commit message back into the editable area) to quickly change the message.

We're tracking editing commit messages in https://github.com/desktop/desktop/issues/5219 so I'm going to close this issue in favor of that!
