### ISSUE TITLE
Open in Visual studio Code shortcut is not working

### ISSUE THREAD

**Issue by SridharS-Square** [desktop/desktop#18885]
### The feature request

Open the repository in external editor which is Ctrl + shift + A 

### Proposed solution

easy way to open the repository in our personal IDE

**Comment by niik** [comment]
There's too little information in this issue for me to be able to provide any valuable help. I'm going to close this issue but feel free to open a new one where you fill out the entire issue template and provide as much feedback as you possibly can. Like whether or not you're able to open Visual Studio Code by clicking on the menu item (under the Repository menu). If that works then the most likely explanation is that some other tool on your machine has taken over the Ctrl+Shift+A shortcut (as was the case in https://github.com/desktop/desktop/issues/18552).

**Comment by SridharS-Square** [comment]
Thank you @niik. Yeah, you are correct I am using multiple IDEs for development. The other IDE took these shortcuts.
