### ISSUE TITLE
when a branch has no commits but is behind HEAD, rebase is disabled in the menu

### ISSUE THREAD

**Issue by cellog** [desktop/desktop#18883]
### The problem

When a branch is branched off of `main`, and then new commits are pulled down from `main`, the button for `Rebase` is disabled, even though `git rebase main` in the command-line does move the branch to the latest commit

### Release version

3.4.1

### Operating system

Mac OS X 14.5

**Comment by steveward** [comment]
@cellog thanks for the issue. I'm not able to reproduce this behavior. Are you able to consistently reproduce it? I tested a few scenarios and the rebase button was not disabled. Are you seeing it in the rebase popover?



![Image](https://github.com/user-attachments/assets/3af87811-26cb-43f4-be80-af930c47d714)
