### ISSUE TITLE
Multi-account support

### ISSUE THREAD

**Issue by tristan-f-r** [desktop/desktop#18891]
### The feature request

In November of 2023, GitHub [added multi-account support to their web dashboard](https://github.blog/changelog/2023-11-03-multi-account-support-on-github-com/), which isn't a feature that exists in desktop. The feature for GitHub's website is mainly for managing enterprise vs. personal accounts, but the account switcher also supports multiple GitHub-owned accounts (i.e. work and personal). 

### Proposed solution

In File -> Options -> Accounts, there should be an ability to manage multiple GitHub-owned accounts.

### Additional context

#16709

**Comment by steveward** [comment]
@LeoDog896 thanks for the issue. This is being tracked in https://github.com/desktop/desktop/issues/3707, please follow along there for updates.
