### ISSUE TITLE
Provide feedback so dialogs do not seem to freeze.

### ISSUE THREAD

**Issue by andrewtobin** [desktop/desktop#1889]
### Description

When I have performed actions like discarding all changes on a large set of files, or creating a new repository, the dialogs have stayed up after I have confirmed and the app seems to have stalled or frozen, or behaved like I have not confirmed the dialog.  The dialog remains up and I am guessing actions are occurring in the background.

It would be good if the dialog was to close and an action indicator was presented instead.

### Version

**GitHub Desktop version:** 0.5.9

**OS version:** Microsoft Windows [Version 10.0.14393]

### Steps to Reproduce

1. A large set of changes to discard/commit.
1. Perform the relevant action.
1. Confirm the dialog.
1. Wonder why the dialog is still up.
1. Wonder what Github Desktop is doing if anything as the dialog is still up.

**Expected behaviour:** Dialog to disappear and some indication of action - a spinner, or a github cat shredding my files (discard) or storing the changes (commit) or similar.

**Actual behaviour:** Dialog and an unresponsive Github Desktop.

![Stalled screen](https://cloud.githubusercontent.com/assets/520748/26768425/25a53910-49eb-11e7-8534-ceb1f892e0b8.png)

That's not going to tell you much, but that dialog has been clicked minutes ago and nothing indicates it has or that it's doing anything.

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Logs

N\A

#### Additional Information

N\A

**Comment by niik** [comment]
Yeah, we should totally do this. We have a dialog loading state that we leverage in most of our dialogs. I imagine we've just missed it in the case of discarding changes. I'll take a look at it
