### ISSUE TITLE
The ability to set application preferences per repository

### ISSUE THREAD

**Issue by ahosokawa** [desktop/desktop#18894]
### The feature request

Desktop has a nice feature that allows you to set your preferred external editor and shell. However, this preference is at the root level and applies to all repositories. It would be really nice if this was a repository-level setting so I could, for example, have VS Code as my preferred editor for some repos and PyCharm as my preferred editor for my Python-based repositories.

### Proposed solution

Make the application preferences a per repository setting. Different editors are better for different languages and frameworks, and thus, it is valuable to be able to specify an editor per repository.

**Comment by steveward** [comment]
Thanks for the issue @ahosokawa, we are tracking this in https://github.com/desktop/desktop/issues/12195 so I'm going to add this feedback there.
