### ISSUE TITLE
Stored credentials on Windows seems to have encoding issues

### ISSUE THREAD

**Issue by niik** [desktop/desktop#189]
We're currently using keytar to store credentials in the ancient Windows Credential Manager and it looks like either it can't deal with unicode or we're not passing the arguments correctly somehow.

![image](https://cloud.githubusercontent.com/assets/634063/17227425/95e27e90-550e-11e6-9304-8e5c8d655062.png)

That dash there is one of @joshaber's [fancy en-dashes](https://github.com/desktop/desktop/blob/master/app/src/shared-process/auth.ts#L66). We should probably figure out if this can end up corrupting usernames/passwords (probably not passwords since they should all be tokens) and adjust accordingly.

**Comment by vbfox** [comment]
I sent a PR to keytar to fix that :)

![2017-05-23 22_06_42-credential manager](https://cloud.githubusercontent.com/assets/131878/26374202/c60cd250-4004-11e7-99c5-dc4a363934c9.png)

**Comment by joshaber** [comment]
That is awesome @vbfox! ✨

**Comment by joshaber** [comment]
_assigning @shiftkey and he's assigned to review https://github.com/atom/node-keytar/pull/66_
