### ISSUE TITLE
Android client

### ISSUE THREAD

**Issue by I21b** [desktop/desktop#18902]
### The feature request

Android client developed for devices that are designed for work.

### Proposed solution

Easier to use Git features.

**Comment by steveward** [comment]
@I21b there's a [GitHub Mobile](https://github.com/mobile) application available for Android. I hope that helps!

**Comment by I21b** [comment]
> @I21b there's a [GitHub Mobile](https://github.com/mobile) application available for Android. I hope that helps!

push   pull   commit 😭
