### ISSUE TITLE
Cant open external editor Android Studio

### ISSUE THREAD

**Issue by andrespineda** [desktop/desktop#18914]
### The problem

From the Desktop Git app, I click on "Open in Android Studio" and I get the following error message:    Error: spawn C:\Program Files\Android\Android Studio\bin\studio64.exe EACCES
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at __node_internal_errnoException (node:internal/errors:623:12)
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Version: 3.4.1
OS: Windows 10.0.22631

### Release version

Version 3.4.1 (x64)

### Operating system

Windows 11 Pro 23H2

### Steps to reproduce the behavior

Login to Desktop Github.
Select Open in Android Studio
Get the error message

### Log files

[2024-06-30.desktop.production.log](https://github.com/user-attachments/files/16043011/2024-06-30.desktop.production.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/2908774/5d4377ab-d2f3-49a9-9666-33f0061d5086)
![image](https://github.com/desktop/desktop/assets/2908774/32ea3500-3ca1-49fc-8846-07a9e0c7fe82)

**Comment by sergiou87** [comment]
Is Android Studio running already before you click on `Open in Android Studio`? If so, is it running as an administrator?

**Comment by andrespineda** [comment]
Yes, I had Android Studio open as Administrator.  I have been opening both VS Code and Android Studio as Administrator for some time to get around some Github issues.

Even if it wasn't, shouldn't it have provided a better error message? That was a crash.

**Comment by andrespineda** [comment]
Yes, Android studio is open with Administrator rights. It works with VS Code, but not Android Studio.


________________________________

**Comment by steveward** [comment]
@andrespineda have you previously been able to open Android Studio from GitHub Desktop without issue? We've had a few varying reports of EACCES errors, but unfortunately they seem to have a variety of causes (one user had to install a KB update and it was resolved, for instance).
