### ISSUE TITLE
Behavior of `Merge into current branch (Rebase)` changed?

### ISSUE THREAD

**Issue by SpriteOvO** [desktop/desktop#18910]
### The problem

`Merge into current branch` rebased commits on the current branch.

### Release version

3.3.18-linux1 (x64)

### Operating system

ArchLinux

### Steps to reproduce the behavior

Let's say, I have 2 branches:

```
A -> B -> C -> D (branch `dev`)
      \-> E -> F (branch `dev-next`)
```

where `E` `F` was committed earlier than `C` `D`.

1. Switch to branch `dev`.
2. Click `Branch` -> `Merge into current branch...`, select `dev-next` branch.
3. Click `Rebase` button.

Expected to see commits on branch `dev`:

```
A -> B -> C -> D -> E -> F (branch `dev`)
```

Actually see:

```
A -> B -> E -> F -> C -> D (branch `dev`)
```

**Comment by steveward** [comment]
@SpriteOvO thanks for the issue. This sounds like https://github.com/desktop/desktop/issues/15282, but are you stating that this behavior changes recently for you?
