### ISSUE TITLE
Long branch name cut-off in Rename Branch

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1891]
The button to rename your branch is cut-off if the branch name is too long.

Reproduce:
- Create long branch name
- File > Rename...

v 0.5.9, OSX 10.11.5

<img width="646" alt="screen shot 2017-06-05 at 9 10 39 am" src="https://cloud.githubusercontent.com/assets/14828183/26785199/37d9ba96-49cf-11e7-8541-aa9fcd140a4b.png">

**Comment by Chance9025** [comment]
Should the button expand to accommodate the additional text, add an ellipsis and omit the remaining text at a certain point, reduce the font size, something else? I don't think I have the technical ability to fix it myself, but it would seem best if it was agreed upon on how it should be fixed first.

**Comment by joshaber** [comment]
Yes, truncating with an ellipsis would be a fine solution 👍
