### ISSUE TITLE
Mac update never installed 

### ISSUE THREAD

**Issue by devtobo** [desktop/desktop#1892]
I have installed GitHub Client in /Applications (prompt to ask my administrator password). Launching the software using my user (not admin) I can see GitHub downloading the update, but doesn't prompt for the administrator password = not installed, downloading again on next launch and repeating this broken process. In the end, I don't have the last version of the software.

**Comment by joshaber** [comment]
This sounds like a bug in the auto-updater framework Electron uses: https://github.com/Squirrel/Squirrel.Mac/issues/157
