### ISSUE TITLE
[Important][Urgent] need Switch between multiple GitHub accounts quickly

### ISSUE THREAD

**Issue by mackding123** [desktop/desktop#18926]
### The feature request

need Switch between multiple GitHub accounts quickly.
Usually a programmer will have 2 github accounts, a work account and a personal account.
It's too inefficient to manually switch accounts every time.
We need smarter operations

### Proposed solution

need Switch between multiple GitHub accounts quickly

**Comment by mackding123** [comment]
Looking forward to your reply, thank you

**Comment by sergiou87** [comment]
@mackding123 thanks for the issue. This is being tracked in https://github.com/desktop/desktop/issues/3707, please follow along there for updates.
