### ISSUE TITLE
No of lines added or edited - File wise

### ISSUE THREAD

**Issue by imhariprakash** [desktop/desktop#18928]
### The feature request

Currently, GitHub Desktop displays the total number of lines added or edited commit-wise. It would be beneficial to have a similar feature that provides file-wise statistics.

### Proposed solution

Currently, GitHub Desktop displays the total number of lines added or edited commit-wise. It would be beneficial to have a similar feature that provides file-wise statistics.

**Comment by sergiou87** [comment]
A contributor added that info in this PR: https://github.com/desktop/desktop/pull/13957

But then we decided to remove it for design + accessibility reasons in a revamp of the commit summary header (https://github.com/desktop/desktop/pulls?q=is%3Apr+author%3Atidy-dev+is%3Aclosed+commit+summary+expansion)

Sorry!
