### ISSUE TITLE
Oauth tokens should be visible and revokable in the user's account settings

### ISSUE THREAD

**Issue by seanthegeek** [desktop/desktop#18921]
### The feature request

The official GitHub apps use an authentication token that is not visible or revokable anywhere in your account. When I reported this through the bug bounty program, I was told this is by design!

### Proposed solution

Any application or token with access to the account should appear in the list of account tokens — including for GitHub applications. Each listing should Include the application name, the user agent that added it, UTC timestamps for when the token was created and last used, and a big button to revoke it. An email should also be sent when a token is created.

**Comment by axi0m** [comment]
I support this enhancement as well.

**Comment by seanthegeek** [comment]
Turns out I was just looking in the wrong spot. Oops! https://github.com/settings/applications
