### ISSUE TITLE
Getting a authentication error

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#18933]
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for

please help me to solve this error

**Comment by sergiou87** [comment]
Hello @kiranshelake 

If you open `Settings -> Account`, are you signed in your GItHub account? If you are, please Sign Out and then Sign In again.

**Comment by ghost** [comment]
still i am  getting that error
