### ISSUE TITLE
GitHub Desktop website redesign

### ISSUE THREAD

**Issue by Studio384** [desktop/desktop#18936]
### The feature request

Late last month the [GitHub Desktop website](https://github.com/apps/desktop) was revamped with a new design and new URL.

However, aside from the website's redesign, it is also showing GitHub Desktop screenshots that look completely different from the GitHub Desktop we have right now.

<img width="1248" alt="Hero_15" src="https://github.com/desktop/desktop/assets/1693592/2b0083ab-41f8-434a-bb2d-433163cdaeb4">

Are these just marketing mock-ups or is this an actual planned redesign of the app? If it is the later, I'm _slightly_ concerned with how much space this new UI seems to waste. If it's the former then... why?

### Proposed solution

Include the community in any potential redesign (and tackle some of the long standing issues in the design while we're at it).

**Comment by tidy-dev** [comment]
@Studio384 Thank you for the feedback. These are only marketing images. There is no app redesign planned.

**Comment by xezrunner** [comment]
> These are only marketing images. There is no app redesign planned.

That's very unfortunate. I was looking forward to the new design after seeing the site update.
