### ISSUE TITLE
Не могу пользоваться програмой 

### ISSUE THREAD

**Issue by Kefisto** [desktop/desktop#18932]
### The problem

Не могу пользоваться програмой 
![изображение](https://github.com/desktop/desktop/assets/99140797/eaa8173a-f9a3-4564-be74-8ef8f45157c8)
![изображение](https://github.com/desktop/desktop/assets/99140797/41c081a4-16a7-431e-9b02-1830960c3274)
![изображение](https://github.com/desktop/desktop/assets/99140797/b822a22d-f591-46c9-91b3-797e7082f9eb)
![изображение](https://github.com/desktop/desktop/assets/99140797/f5897e98-2c2c-4ac6-85ce-390befac78fb)

### Release version

3.4.2

### Operating system

Windows 11 Pro

### Log files

[2024-07-04.desktop.production.log](https://github.com/user-attachments/files/16092317/2024-07-04.desktop.production.log)

### Screenshots

![изображение](https://github.com/desktop/desktop/assets/99140797/eaa8173a-f9a3-4564-be74-8ef8f45157c8)
![изображение](https://github.com/desktop/desktop/assets/99140797/41c081a4-16a7-431e-9b02-1830960c3274)
![изображение](https://github.com/desktop/desktop/assets/99140797/b822a22d-f591-46c9-91b3-797e7082f9eb)
![изображение](https://github.com/desktop/desktop/assets/99140797/f5897e98-2c2c-4ac6-85ce-390befac78fb)

**Comment by sergiou87** [comment]
It looks like a faulty installation, or an antivirus messing with the app. Could you temporarily disable your antivirus and reinstall the app and see if that works?
