### ISSUE TITLE
Application does not appear in start menu after installing using winget

### ISSUE THREAD

**Issue by Quadx117** [desktop/desktop#18944]
### The problem

After installing the latest version (3.4.2) using winget on a brand new Windows 11 laptop, the appication does not appear in the start menu.

Rebooting didn't change anything.

Removing and reinstalling through winget again, but from an admin terminal and rebooting, didn't change anything.

Using the installer from the official website works as expected. Listing the application in winget after installing from the installer shows the same information (name, version, id, source) as when installing using winget.

The application does get installed and works if launched manually from %localappdata%, but is not found in the start menu nor using search from the taskbar if installed directly from winget.

### Release version

3.4.2 (x64)

### Operating system

Windows 11 Home 23h2

### Steps to reproduce the behavior

1. Open a terminal
2. install using winget (winget install GitHub.GitHubDesktop)
3. Click on the start menu or use the search from the taskbar and Github Desktop is not found

**Comment by sergiou87** [comment]
I'm sorry but winget releases [are managed by the community](https://github.com/desktop/desktop?tab=readme-ov-file#community-releases), we don't officially support them. Unfortunately, I have no idea who exactly could help you out with this… 😕
