### ISSUE TITLE
github desktop wont install

### ISSUE THREAD

**Issue by zxabriel** [desktop/desktop#18943]
### The problem

When I try to install github desktop, it gives me this error

### Release version

3.4.2

### Operating system

windows 10 (64bit)

### Steps to reproduce the behavior

1. Launch the installer

### Log files

[Squirrel-Install.log](https://github.com/user-attachments/files/16118057/Squirrel-Install.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/174918289/3db84808-d09e-475b-97d8-286eab73babd)

**Comment by sergiou87** [comment]
It seems you don't have access to the installation folder: `System.UnauthorizedAccessException: Access to the path 'C:\Users\User\AppData\Local\GitHubDesktop' is denied.`

Could you try to reboot your machine, then uninstall the existing GitHub Desktop installation, and then install it again? 🤞
