### ISSUE TITLE
Cannot Run Cloned Reprisitory Because of Dotnet error

### ISSUE THREAD

**Issue by KeremBoncuk** [desktop/desktop#18949]
### The problem

Hi,
After, cloning reprisitory when clicked open with visual studio button, I get the following error:
Error: spawn C:\ProgramFiles\dotnet\ ENOENT
    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)
    at __node_internal_errnoException (node:internal/errors:690:12)
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Version: 3.4.2
OS: Windows 10.0.22631

I searched and maybe it is because of my visual studio dotnet extension settings error, however I am new in coding world and wanted to report this issue if there could be found any solution for this.
If this issue is not related to github desktop I apologize for it. Also the error mentions that my operating system is 10 but it is 11 and I am sure off that.
Kind Regards,
Kerem

### Release version

3.4.2

### Operating system

windows 11

**Comment by steveward** [comment]
Thanks for the issue @KeremBoncuk. Could you open the command prompt and share the output of echo `%PATH%`?

If `System32` is not in your `PATH`, you will need to edit your `PATH` by following [this article](https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/) and adding the following line:

`C:\Windows\system32`
