### ISSUE TITLE
Show absolute date/time in commit log

### ISSUE THREAD

**Issue by winzig** [desktop/desktop#18959]
### The feature request

Currently the UI shows relative timestamps in the commit log, which is way too imprecise when looking at older dates. 

![screenshot 2024-07-11 at 11 21 36](https://github.com/desktop/desktop/assets/127062/e69f82f5-6f29-4511-8bc3-715b51ba2f7a)

### Proposed solution

There should be an option to switch to absolute timestamps, ideally in ISO 8601 or some other easily scannable format beginning with YYYY-MM-DD. I also think it would be nice if the user could decide between UTC or local display of the timestamp, but in any case I would default it to local timezone.

**Comment by steveward** [comment]
@winzig thanks for the feedback. This is being tracked in https://github.com/desktop/desktop/issues/14611, so you can follow along there for updates.
