### ISSUE TITLE
Need some explanation for this one

### ISSUE THREAD

**Issue by robincee** [desktop/desktop#18950]
Hi guys,

Sorry for not using a template, cause this is not really an issue, more a request to clarify what i see + maybe you guys made a booboo or a double booboo! Or it's just us - the end users LOL. Interesting to see witch one it is / what is really going on.

Cloning the Unreal source repo as an example, cause this is a huuuuge repository.

![image](https://github.com/desktop/desktop/assets/1320261/e7f8145c-52a8-4849-ab70-77249ba4b962)

Uploading this image. I've been staring at this and i figured:
- it's my busted up asus laptop wireless intel device (or driver)
- my old unsupported bios
- my dear isp provided wireless router (witch works fine on a wired device)
- the 'crappy' Nvidia / Intel dual cards (or the updated driver i see loads of gamers complain about) (dual cards: lots of people report problems with) (but work fine for me) 
- or anything else i've forgot to mention (has been a long day debugging this silly lil thing).

But i do want to find out if the mbps on the right (github desktop) is really correct, cause the one on the left (task manager) seem to be the actual speed (and lots closer to the one reported on my wired device). And i have not started any other thing using git that i know of, nor any open command console somewhere, just clicked on the link to download the unreal engine repo via the Github desktop - and this is what i see (After debugging this for +3 hours, so forgive me not using the template, just trying to share this experience, now going for some tea).

Best!
Rob

ps Note: a 'continue' button might be an idea? Just off the top of my head: so you can continue downloads (clones) that broke down without having to remove the folder, i did some restarts lol.

**Comment by sergiou87** [comment]
35.5 Mbps / 8 = 4.43 MB/s so I think it's pretty close, right?

Am I missing something? 😳😳😳
