### ISSUE TITLE
can't install github desktop Windows 11

### ISSUE THREAD

**Issue by yorhyun** [desktop/desktop#18952]
![Screenshot 2024-07-11 031600](https://github.com/desktop/desktop/assets/167117072/9b196429-0bb3-4ff3-a100-afd19a730aeb)

What I’ve tried
- Running the installer as an administrator.
- Restarting my laptop.
- Running sfc /scannow.
- Deleting the SquirrelTemp and github desktop folders.

[Squirrel-Install.log](https://github.com/user-attachments/files/16168626/Squirrel-Install.log)

**Comment by sergiou87** [comment]
It seems it's trying to "grab the lockfile" and it can't. Can you try to delete that file manually? It's located in `C:\Users\GF65 Thin 10SDR\AppData\Local\Temp\.squirrel-lock-0022E56F34051D85F65AF012BAF3CAA39A4DB189`

**Comment by yorhyun** [comment]
I tried, but it didn't work, so I attempted to fix the problems using Windows Update, and it worked. Thank you for your help.
