### ISSUE TITLE
Save what files where not added to the index (checkbox unchecked) (tracked file)

### ISSUE THREAD

**Issue by wiiznokes** [desktop/desktop#18957]
### The feature request

I often change a variable in a Makefile, like `DEBUG=1` or smgt. I would like Github desktop to remember that i don't want to commit this file, after an app restart.

### Proposed solution

Save this state

edit:

Sorry for the title, i didn't know how to describe this precisely

**Comment by steveward** [comment]
Thanks for the feedback @wiiznokes! I'm going to add this to https://github.com/desktop/desktop/issues/3664 where we are tracking this. Please follow along there for updates.
