### ISSUE TITLE
error trying to clone https://github.com/ZiqiaoPeng/SyncTalk

### ISSUE THREAD

**Issue by Toolfolks** [desktop/desktop#18956]
### The problem

Cloning into 'D:\techy\talkingHeads\SyncTalk'...
remote: Enumerating objects: 277, done.        
remote: Counting objects: 100% (113/113), done.        
remote: Compressing objects: 100% (58/58), done.        
remote: Total 277 (delta 86), reused 59 (delta 55), pack-reused 164        
Receiving objects: 100% (277/277), 29.52 MiB | 34.35 MiB/s, done.
Resolving deltas: 100% (108/108), done.
error: invalid path 'data/Please place the data file.'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

Would you like to retry cloning ?

### Release version

Version 3.4.1 (x64)

### Operating system

win 10

### Steps to reproduce the behavior

1. Clone with GitHub desktop

### Log files

[2024-07-11.desktop.production.log](https://github.com/user-attachments/files/16177026/2024-07-11.desktop.production.log)

**Comment by steveward** [comment]
@Toolfolks thanks for the issue. It looks like there is a path issue in the repository you are trying to clone:

`error: invalid path 'data/Please place the data file.'`

From Microsoft:

> Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not. However, it is acceptable to specify a period as the first character of a name. For example, ".temp".

You could submit a PR to [modify that filename](https://github.com/ZiqiaoPeng/SyncTalk/tree/main/data), or you could set a specific Git config option to ignore this:

`git config --global core.protectNTFS false`

Please note that this config option could have side effects. I hope that helps!
