### ISSUE TITLE
Not able to clone or push changes to the github repo

### ISSUE THREAD

**Issue by MonikaK123** [desktop/desktop#18953]
### The problem

Whenever trying to push the changes to git repo, getting a popup to sign in to enterprise url, after giving all the details getting the below error:
Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.

### Release version

Version 3.4.2 (x64)

### Operating system

Windows

### Steps to reproduce the behavior

Open in Explorer
Add some changes
Push some changes
<img width="710" alt="image" src="https://github.com/desktop/desktop/assets/97428769/1a033a9e-c10b-44cf-985a-688ab01ac5fe">

**Comment by sergiou87** [comment]
Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by MonikaK123** [comment]
[2024-07-11.desktop.production.log](https://github.com/user-attachments/files/16175394/2024-07-11.desktop.production.log)

**Comment by sergiou87** [comment]
Hmmm it seems there've been too many attempts to sign in from your IP address, and the GitHub Enterprise server where your repo is hosted is complaining about that. Either wait for some time or contact your admin to see if there is any issues hitting the `/api/v3/meta` endpoint of your GitHub Enterprise instance 🤞
