### ISSUE TITLE
I get an Unknown error when trying to commit but commit works fine from RStudio and git bash

### ISSUE THREAD

**Issue by spsanderson** [desktop/desktop#18965]
### The problem

I try to commit and get a message of Unknown error. I can commit fine from RStudio and git bash.

### Release version

Version 3.4.1 (x64)

### Operating system

Windows 11 Home

### Steps to reproduce the behavior

1. Click on button "Commit to development"

### Log files

[2024-07-13.desktop.production.log](https://github.com/user-attachments/files/16202163/2024-07-13.desktop.production.log)

### Screenshots

![image](https://github.com/user-attachments/assets/1e47d128-54b9-4aa5-97c3-3abcf37f6acf)

**Comment by sergiou87** [comment]
Do you have any antivirus or firewalls that you can temporarily disable? If so, please disable them, reinstall GitHub Desktop and then try again 🤞 Let us know if that helps.

**Comment by spsanderson** [comment]
I do not have any installed but i will uninstall and reinstall the software and see if that works.

**Comment by spsanderson** [comment]
Just did that and it still produces the same error, I can however as previously click on the create pull request and it works.

[2024-07-15.desktop.production.log](https://github.com/user-attachments/files/16235244/2024-07-15.desktop.production.log)

**Comment by spsanderson** [comment]
[2024-07-15.desktop.production.log](https://github.com/user-attachments/files/16235184/2024-07-15.desktop.production.log)

**Comment by sergiou87** [comment]
Could you try with other repositories and see if it works there? Trying to narrow down the scope of this issue 🤔

**Comment by spsanderson** [comment]
Works fine with other repos, i’m thinking of updating github, deleting from
local and cloning

Thoughts?

Steven P Sanderson II, MPH
Amazon Author Profile
<https://www.amazon.com/stores/Steven-P.-Sanderson/author/B0CZ157DHK?ref_=pe_2466670_811284380&isDramIntegrated=true&shoppingPortalEnabled=true>
Book on Lulu <http://goo.gl/lmrlFI>
Personal Site <http://www.spsanderson.com>

**Comment by sergiou87** [comment]
Yeah, if you don't want to risk deleting something you shouldn't, you can even just clone the repository again in a different folder and see if it works there 🤞

**Comment by spsanderson** [comment]
I'll give it a try now

**Comment by spsanderson** [comment]
that seemed to work, so I'm going to overwrite the old with the newly cloned

**Comment by spsanderson** [comment]
closing
