### ISSUE TITLE
New GitHub Desktop UI?

### ISSUE THREAD

**Issue by shdwmtr** [desktop/desktop#18969]
### The problem

Has the GitHub Desktop app gotten a UI update? I see on the [Github Desktop page](https://github.com/apps/desktop) that the UI is much different from my local version, however It appears I'm on the latest version, and I'm also on beta. 

### Release version

Version 3.4.3-beta1 (x64)

### Operating system

Windows 11 

### Steps to reproduce the behavior

Download and run the latest version of Github Desktop

**Comment by Dave0000000David** [comment]
Yes 68

**Comment by sergiou87** [comment]
As mentioned in https://github.com/desktop/desktop/issues/18936#issuecomment-2210702530, these are just marketing images. Sorry about the confusion.
