### ISSUE TITLE
Keeps saying authentication failed

### ISSUE THREAD

**Issue by zenstorm** [desktop/desktop#18966]
### The problem

Authentication Failed pop up appears: "We were unable to authenticate with `https://gitlab.com/`.  Please enter your username and password to try again."
I do this, but no luck.  I hit enter and it keeps pulling for a period of time, then throws up another popup:  
"Authentication failed. Some common reasons include: etc"

I've been using GitHub Desktop for a year now, and all of a sudden it's needed authentication.  My programmer didn't change anything.  I didn't change anything.  

I'm absolutely logged into my account.  I see my icon in the app.   I log into and out of github.  Into and out of GHDesktop.   Still the same issue.  I'm flummoxed.  

### Release version

Latest

### Operating system

Windows 10 Home

### Steps to reproduce the behavior

1. Perform any action.  
2.  Popup appears

### Log files

[2024-01-27.desktop.production.log](https://github.com/user-attachments/files/16202327/2024-01-27.desktop.production.log)
[2024-01-23.desktop.production.log](https://github.com/user-attachments/files/16202328/2024-01-23.desktop.production.log)
[2024-01-24.desktop.production.log](https://github.com/user-attachments/files/16202329/2024-01-24.desktop.production.log)
[2024-01-25.desktop.production.log](https://github.com/user-attachments/files/16202330/2024-01-25.desktop.production.log)
[2024-01-26.desktop.production.log](https://github.com/user-attachments/files/16202331/2024-01-26.desktop.production.log)

**Comment by sergiou87** [comment]
Thanks for your report, however those logs belong to January.

Please, make sure you're in the latest version (3.4.2) from https://desktop.github.com and then open Preferences -> Advanced and make sure `Use Git Credential Manager` is checked:

![Image](https://github.com/user-attachments/assets/e0098453-b393-474b-8986-d2e2ffd0dbc9)

Once it is, next time you do anything with a GitLab repo, you will be prompted to sign into GitLab and everything should Just Work™ 🤞 

Please, let us know if that helps.

**Comment by Sergio0694** [comment]
This works for me, but for some reason, only the second time. That is:
- I click on "fetch"
- I get the dialog saying authentication failed
- I close it
- I click on "fetch" again
- _Now_ I get the credential manager dialog where I can select my MSFT account

I'm on 3.4.2.

**Comment by sergiou87** [comment]
@Sergio0694 does it still happen or only happened the first time?
