### ISSUE TITLE
Should desktop/desktop README.md continue to reference fork shiftkey/desktop? [UNFOUNDED supply chain poisoning concern - so NOT A WORRY]

### ISSUE THREAD

**Issue by tim-littlefair** [desktop/desktop#18963]
### The problem

README.md in the desktop/desktop project advises that the project does not officially support Linux, but that there is a fork at https://github.com/shiftkey/desktop which does.

I installed the fork on my Ubuntu 24.04 box some time ago (possibly before dist-upgrading from 23.10), following the instructions on shiftkey/desktop for adding the project's APT repository at apt.packages.shiftkey.dev.

I think that this was working fine at the time of installation, but when I do an 'apt update' now I get the following messages:

Ign:8 https://apt.packages.shiftkey.dev/ubuntu any InRelease
Ign:8 https://apt.packages.shiftkey.dev/ubuntu any InRelease
Err:8 https://apt.packages.shiftkey.dev/ubuntu any InRelease
Certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. [IP: 13.107.246.32 443]

I'm not the first person to notice this problem - for example a reddit thread at  https://www.reddit.com/r/Ubuntu/comments/1cqspwu/certificate_verification_failed_the_certificate/
talks about it and reports that contacting shiftkey about the problem has proved difficult (I haven't tried myself).

One of the replies on that thread suggests using the URL https://www.ssllabs.com/ssltest/analyze.html?d=apt.packages.shiftkey.dev to diagnose the TLS problem.  When I do that (today, from my home in Western Australia) I get a page including this:

![image](https://github.com/user-attachments/assets/8792ffab-901e-4f16-b427-e0caa473cf48)

In the reddit thread, there is reassurance that normal APT behaviour will prevent updates from that site being trusted while the certificate issue remains unresolved, however this still represents a  danger to users both in that existing installs will not be patched for security issues, and that it may be possible to downgrade the URLs to http-without-s in order to work around the problem (I don't know whether current APT tolerates this and don't plan to test it).

I have no way of knowing whether this means that the apt.packages.shiftkey.dev site is now under the control of a bad actor, but I think that desktop/desktop might want to consider whether their documentation should continue to direct users to shiftkey/desktop while this situation remains resolved.  Note that control of the APT update site is obviously a completely separate consideration from whether the forked code hosted on Github contains malicious elements.

NB I am aware that desktop/desktop have closed ticket #18931 relating to first-party Linux support, so it may be that the risk can be addressed by adding install instructions for a package built and hosted by desktop/desktop rather than the owners of the fork.

Apologies for the length of this ticket, and also if it's already been raised but I missed it in my brief scan of your open issues.

### Release version

README.md hosted on github.com

### Operating system

Linux

**Comment by tim-littlefair** [comment]
Apologies for not completing the 'Steps to reproduce ..' section.  The required steps are as follows:

Follow the instructions below using the first of the two alternative feeds proposed, i.e. apt.packages.shiftkey.dev.

![image](https://github.com/user-attachments/assets/2537e04c-a0f4-4007-a36a-336e294a91cc)

These instructions appear at https://github.com/shiftkey/desktop, the only remedial action from desktop/desktop which would be required would be to remove references to the shiftkey/desktop fork until the repository shiftkey recommend people to use is unambiguously safe to trust.

I haven't done any checking in relation to the second proposed feed.  A reference to one dangerous feed is enough to make the other suspect anyway in my book.

**Comment by tim-littlefair** [comment]
I just confirmed that I do have this installed on my system.  The Help/About box looks like this:

![image](https://github.com/user-attachments/assets/8376ee58-15a4-4c67-bd23-00dd1fd50a73)

Not sure if this information helps to identify when trust in the repo broke (I generally update this system at least once a week unless I am away from home).

**Comment by sergiou87** [comment]
Thank you for your report 💖 

It seems the maintainer of the fork (who also works at GitHub) is aware of the issue and has fixed it in the past, so it doesn't look like the repo has been taken over: https://github.com/shiftkey/desktop/issues/1062

I'd recommend you to chime in there or at least subscribe to that issue to get progress updates, but for now I don't think we need to make any changes to our README file. We will keep an eye on this, though, so thanks again!

**Comment by tim-littlefair** [comment]
@sergiou87 thanks for the rapid response, and the reference to @shiftkey's ticket which gives context and shows that the repo is actively owned by a good actor who is on top of the issue.

It's clear to me that the supply chain suspicion was completely unfounded, so I've amended the title of the ticket as best I could to prevent future searchers who see the ticket title only from suspecting @shiftkey of being or enabling a bad actor - you are welcome to amend the title yourself or suggest an alternate title if you don't like the shouty way I've done this
