### ISSUE TITLE
Authentication failed when using repos cloned with SSH

### ISSUE THREAD

**Issue by hengst85** [desktop/desktop#18961]
### The problem

We are using SSH keys in our team. The keys and git config files are stored on Onedrive and we are using the enviroment variable HOME to make the new directory known in the system.

HOME = C:\Users\<username>\OneDrive - azureford\Home

In our development enviroment it is important, that several repos are stored on defined local locations on our PCs.
Therefore we are using scripts to clone several repos with SSH to defined local locations.
 
When I add these script and SSH cloned repos to GitHub Desktop, I get authentication errors on fetch/pull/push.
In the bash I have no problems working with the repos. 

Any idea to solve my problem?

### Release version

Version 3.4.2 (x64)

### Operating system

Windows 10

### Log files

[2024-07-12.desktop.production.log](https://github.com/user-attachments/files/16190126/2024-07-12.desktop.production.log)

### Screenshots

![image](https://github.com/user-attachments/assets/0ba892ee-e84e-44b4-b356-1bac6053e1be)

**Comment by sergiou87** [comment]
From what I see in your logs, it looks like your machine is unable to resolve github.com:
```
stderr:
ssh: Could not resolve hostname github.com: No such host is known. 
fatal: Could not read from remote repository.
```

Do you have any issues accessing github.com from your browser? Does your machine run behind a proxy, firewall or something like that?

**Comment by hengst85** [comment]
Yes and no. I have the problem with the GitHub Desktop in both cases, when I am in the VPN (then with proxy), but also when I am not in the VPN.
But I have no issues accessing github.com from my browser or working with the bash. 
For working inside the VPN, we are using a config file inside your $HOME/.ssh folder:

```
Match Host github.com exec "ping -n 1 internet.ford.com"
  User git
  ProxyCommand connect -H internet.ford.com:83 %h %p
```

**Comment by sergiou87** [comment]
In any case this seems to be an issue with your network configuration 😕 I can't think of anything on Desktop's side making github.com unreachable 🤔 

I'll be happy to reopen if I'm wrong about this, though! But I can't see how can we help you with this issue, sorry 😥
