### ISSUE TITLE
Error when cloning an organization repository

### ISSUE THREAD

**Issue by reques6e** [desktop/desktop#18971]
### The problem

Start cloning a repository belonging to an organization. even if you enter an account login and token, it gives an error. 

### Release version

Version 3.3.12-linux2 (x64)

### Operating system

Kali linux 

### Steps to reproduce the behavior

Start cloning an organization-owned repository

### Log files

Cloning into '/home/reques6e/Documents/GitHub/TeamInfo'...
remote: Repository not found.
fatal: repository 'https://github.com/AbkhazianDevelopers/TeamInfo.git/' not found

(The error was parsed as 9: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2024-07-14T17:32:22.137Z - info: [ui] [BranchPruner] Last prune took place 4 hours ago - skipping
2024-07-14T17:32:23.442Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: CloudWebCamera - reques6e (has token)
2024-07-14T17:32:47.923Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 4 repositories took 0.9s of which 0.0s paused, total 0.9s
2024-07-14T17:33:19.488Z - info: [ui] [Timing] Action 'create commit' for 'AbkhazianDevelopers/CloudWebCamera' took 0.255s
2024-07-14T17:33:20.189Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: CloudWebCamera - reques6e (has token)

### Screenshots

![image](https://github.com/user-attachments/assets/ea5043ff-8d6f-4cb6-be66-ea267b55ce71)

**Comment by reques6e** [comment]
By the way, if you do it through regular console git, everything works

**Comment by reques6e** [comment]
![image](https://github.com/user-attachments/assets/d5a2cb94-7a37-481d-b7d4-7b71ce375f46)
![image](https://github.com/user-attachments/assets/2eed0832-3b5a-450e-9ebf-8fd0787cc552)

**Comment by sergiou87** [comment]
Are you signed in on Preferences -> Account? If so, could you try signing out and in again?

**Comment by reques6e** [comment]
I logged out and zoned into my account, several times.
![image](https://github.com/user-attachments/assets/400fc37c-6221-4f8c-8412-a9bc21ce516d)

**Comment by reques6e** [comment]
I've tried reinstalling GitHub Desktop. 

```bash
wget -qO - https://apt.packages.shiftkey.dev/gpg.key | gpg --dearmor | sudo tee /usr/share/keyrings/shiftkey-packages.gpg > /dev/null
sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/shiftkey-packages.gpg] https://apt.packages.shiftkey.dev/ubuntu/ any main" > /etc/apt/sources.list.d/shiftkey-packages.list'
sudo apt update && sudo apt install github-desktop
```

[6feda47](https://gist.github.com/berkorbay/6feda478a00b0432d13f1fc0a50467f1)

**Comment by sergiou87** [comment]
Does anything from this issue help you? https://github.com/desktop/desktop/issues/18767 🤞

**Comment by reques6e** [comment]
No. But I had this problem before, I fixed it by simply deleting the repository with the same name in `/home/reques6e/Documents/GitHub/`

**Comment by steveward** [comment]
@reques6e I'm glad to hear things are working. For future reference, we recommend opening/searching for issues about the Linux fork of GitHub Desktop in that[ issue tracker](https://github.com/shiftkey/desktop/issues).
