### ISSUE TITLE
Bug on pull/push

### ISSUE THREAD

**Issue by MarkusLuan** [desktop/desktop#18981]
### The problem

Sometimes when I try to do a pull or a push, it returns an error: "fatal: unable to access 'https://github.com/{ORGANIZATION}/{REPOSITORY}': schannel: failed to receive handshake, SSL/TLS connection failed"

### Release version

3.4.2 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1- Select some repository
2- Do any commit
3- Click on "Push Origin"

### Log files

[2024-07-15.desktop.production.log](https://github.com/user-attachments/files/16235691/2024-07-15.desktop.production.log)

### Screenshots

![image](https://github.com/user-attachments/assets/8bfa999c-6500-4d02-9cc6-75a12b31d38b)

**Comment by steveward** [comment]
@MarkusLuan thanks for the report. Are you behind a firewall or proxy server that could be interfering with your connection to GitHub?
