### ISSUE TITLE
maybe on ubuntu?

### ISSUE THREAD

**Issue by su322** [desktop/desktop#18992]
### The feature request

Hello! Maybe you can develop an edition on ubuntu or on other Linux versions? Thanks. It's a little funny, haha.

### Proposed solution

You saw.

**Comment by sergiou87** [comment]
Thanks for the issue @su322 . At this time there are no official builds of GitHub Desktop available for Linux, but a former developer of GitHub Desktop maintains a fork with Linux builds available for download:

https://github.com/shiftkey/desktop/releases

You can also follow along with https://github.com/desktop/desktop/issues/1525 for updates about an official Linux release.
