### ISSUE TITLE
Bring git reset option to context menu when right-clicking specific commit in repo history

### ISSUE THREAD

**Issue by wezzzyrek1** [desktop/desktop#18998]
### The feature request

Would be nice to have 'git reset' function in context menu when right clicking a commit in repo history. Selecting the reset would reset repo to specific commit (--hard) and do push -f

### Proposed solution

Would avoid a need to run command, since git reset --hard or -- soft are frequently used functions

**Comment by steveward** [comment]
@wezzzyrek1 thanks for the issue. GitHub Desktop does have a reset option, see [this help article](https://docs.github.com/en/desktop/managing-commits/resetting-to-a-commit-in-github-desktop). There is not an equivalent of `git reset --hard` at this time, but you can discard the changes after resetting to get the equivalent. I hope that helps.
