### ISSUE TITLE
Always notify "untrusted server"

### ISSUE THREAD

**Issue by angelolr** [desktop/desktop#18996]
### The problem

There is no way to stop the popup "Untrusted server" and it's impossible to add a certificate.
![Screenshot 2024-07-18 162352](https://github.com/user-attachments/assets/e283ea83-290d-4a13-b4af-44ce3d7a3135)

### Release version

3.4.3-beta2

### Operating system

Windows 11

**Comment by steveward** [comment]
@angelolr thanks for the report. We got another recent report of this in https://github.com/desktop/desktop/issues/18991. Is this a self-hosted Gitlab server?

**Comment by angelolr** [comment]
Yes, It is

**Comment by steveward** [comment]
Thanks, I'm going to consolidate this into #18991 for tracking purposes. Please follow along there for updates.

**Comment by Felashmurda** [comment]
Felashmurda

**Comment by Felashmurda** [comment]
#18991

**Comment by Felashmurda** [comment]
USA 
Felashmurd
February 8 2000
Male

**Comment by geomorillo** [comment]
still happening on Version 3.4.9 (x64

**Comment by geomorillo** [comment]
Not working still happening on Version 3.4.15 (x64)

**Comment by Walnutwax** [comment]
Not working still happening on Version 3.4.18 (x64)

![Image](https://github.com/user-attachments/assets/3dd02232-11e4-4c0e-b989-bb932b95f3c5)
