### ISSUE TITLE
Redirection problem

### ISSUE THREAD

**Issue by MrCuddles19** [desktop/desktop#18993]
My web browser fails to redirect me to the app during the log in process

**Comment by steveward** [comment]
Thanks for the report @MrCuddles19. Have you tried changing the default browser on Windows to see if that resolves the issue?

There's also a known issue where authentication fails if the app is set to run in admin mode. Here's how you can check that:

1. Open the start menu and search for GitHub Desktop
2. Right-click and select `Open file location`
3. Right-click on GitHub Desktop and select `Properties`
4. Go to the `Compatibility` tab
5. Under `Settings`, uncheck `Run this program as administrator`

Let me know if that helps.
