### ISSUE TITLE
While cloning or fetching repo from gitlab I get this error - "The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed."

### ISSUE THREAD

**Issue by mihaidobre** [desktop/desktop#18990]
### The problem

Whenever I want to clone a new repository using Github desktop I get the following error:

The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.

Currently this version is not usable.

### Release version

Version 3.4.2 (x64)

### Operating system

Windows

### Log files

(The error was parsed as 9: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)

### Screenshots

![image](https://github.com/user-attachments/assets/558ea1b4-b861-4c74-976a-6697f3e86084)

**Comment by sergiou87** [comment]
Could you open Preferences -> Advanced and enable `Use Git Credential Manager`? That should ask you to log into gitlab and hopefully be able to clone/fetch the repository with that 🤞

**Comment by mihaidobre** [comment]
Hello @sergiou87 , thanks for replying.

Indeed by enabling the "Use Git Credential Manager" it worked.

Once again thanks for your valuable feedback. 

p.s: In windows the option is under file -> options -> advanced

**Comment by sergiou87** [comment]
I'm glad it worked! Thanks for letting us know 🙏

**Comment by dwowens** [comment]
I have the same problem.  I was able to clone the repository with command line tools.  But, desktop gives me that same error whenever I try to "Fetch origin".  I've enabled "Use Git Credential Manager".... same results.   (version 3.4.2 (arm64))

**Comment by BucketsKeebler** [comment]
I've enabled Git Credential Manager but still experience the error when fetching origin.
