### ISSUE TITLE
github desktop cannot verify the identity of '' issue

### ISSUE THREAD

**Issue by Parangat1** [desktop/desktop#19005]
### The problem

github desktop cannot verify the identity of '' issue

issue wasnt there before upgrading to this version

### Release version

Version 3.4.2 (x64)

### Operating system

windows 10 (64 bit)

### Screenshots

![Screenshot (158)](https://github.com/user-attachments/assets/aff61672-c301-4ef5-9542-2b03fc9f43df)

**Comment by steveward** [comment]
@Parangat1 thanks for the issue. We're looking into this in https://github.com/desktop/desktop/issues/18991, so I'm going to close this out and reference it in that issue. Is this also a GitLab self-hosted instance?
