### ISSUE TITLE
Github Desktop login to github gist fails

### ISSUE THREAD

**Issue by Yzi** [desktop/desktop#19008]
### The problem

I usually use Github Desktop to manage github gist, by cloning the gist url and logging in with github token. After upgrading to 3.4.2, it prompts that the verification failed.

### Release version

3.4.2

### Operating system

Windows 11

### Log files

[2024-07-23.desktop.production.log](https://github.com/user-attachments/files/16342679/2024-07-23.desktop.production.log)

### Screenshots

![2024-07-23 093643](https://github.com/user-attachments/assets/b05ba474-fe3f-403d-90d7-e32655cd1d9e)

**Comment by tidy-dev** [comment]
Able to reproduce. 

Cloning succeeded, pushing fails.

Other Notes:

I attempted in a previous version and it requested my username/password and I provided my username and a PAT and worked. Evidently, treated as an third-party authentication.

**Comment by tidy-dev** [comment]
In 3.4.2, we switched to using Git Credential Manager. I believe it to be checking for `github.com` and trying to run authentication like a regular GitHub repository as opposed to `gist.github.com`.  You must use a token. 

A [workaround I found](https://stackoverflow.com/questions/70407167/using-git-credentialmanager-with-github-tokens-for-gists) is to open repository settings and set your remote to be like:

```https://<token>@gist.github.com/username/gistsha```

Mine looks like (with token removed):

```https://<token>@gist.github.com/tidy-dev/6752709d3994c8b9608a4b9d64c498b2.git```

**Warning: This is not preferable as it does store your token in plain text.**

You can also use the command line and it will prompt you for your username/password where you provide your username and a pat.

**Comment by tidy-dev** [comment]
@Yzi  The fix has shipped [to the latest beta](https://desktop.github.com/beta/).  

By default, it will allow you to enter a PAT like before OR a easier experience is to enable the Git Credential Manager by going to Settings > Advanced and checking "Use Git Credential Manager".
