### ISSUE TITLE
bug with GitHub Desktop during commit

### ISSUE THREAD

**Issue by MykhayloOdesa** [desktop/desktop#19004]
### The problem

during commiting such error appeared/

Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <>) not allowed

### Release version

Version 3.4.2 (x64)

### Operating system

Windows

**Comment by steveward** [comment]
@MykhayloOdesa thanks for the issue. Can you go to `File` > `Options` > `Git` and verify that your name and email are set?
