### ISSUE TITLE
不支持自定义安装.

### ISSUE THREAD

**Issue by AkazaAkaria** [desktop/desktop#19006]
### The feature request

不支持自定义安装.

### Proposed solution

不支持自定义安装.

### Additional context

不支持自定义安装.

**Comment by steveward** [comment]
Thanks for the issue @AkazaAkaria, at this time we do not have plans of changing our installer, but this feedback is being tracked in https://github.com/desktop/desktop/issues/1086 if you would like to follow along there for any updates.
