### ISSUE TITLE
[Feature ] Progress of Multilingual Support?

### ISSUE THREAD

**Issue by RSS1102** [desktop/desktop#19018]
### The feature request

Has there been any change in the progress of multilingual support?

https://github.com/desktop/desktop/issues/8289
I have seen many people requesting multilingual configuration, but there has been no progress for a long time.

### Proposed solution

Of course, the support for various languages can put pressure on the maintenance team. We can add a JSON processing file on the desktop, which allows users to add self translation for multiple languages locally.
```ts
{
cn:{},
ra:{},
....
};

### Additional context

_No response_

**Comment by steveward** [comment]
Thanks for the issue @RSS1102. At this time there are no new updates on multilingual support in GitHub Desktop. We are a small team with a focused list of priorities, and at this time we don't have the bandwidth to take this on. Thanks for your continued interest, and I'm sorry that I don't have better news.

**Comment by RSS1102** [comment]
@steveward 
ok， This may seem like unfortunate news, but if necessary, I can try to solve the problem. If you like.
Because this issue seems to have been frequently raised as early as 2021.🙁🙁
