### ISSUE TITLE
Closing the window while in full screen doesn't exit full screen

### ISSUE THREAD

**Issue by ungb** [desktop/desktop#1901]
### Description

Exiting in full screen doesn't exit full screen

### Version

**GitHub Desktop version:** 0.5.9

**OS version:**
Mas OS Sierra 10.12.5 (16F73)

### Steps to Reproduce

1. Open GIthub Desktop 
2. Go to full screen
3. Close github desktop

![close](https://cloud.githubusercontent.com/assets/5624870/26802853/eefd52b0-49f6-11e7-9d1b-7679f00584cb.gif)

**Expected behaviour:** [What you expected to happen]
Goes back to the other window that is open

**Actual behaviour:** [What actually happened]
Window goes blank leads to confusing experience.  

NOTE: if you completely close the application, it goes back to the other workspace but if there's no windows open for github desktop it should go back too.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

/cc @tierninho

**Comment by ungb** [comment]
Hmm, Actually just noticed that slack has the same behavior, but atom goes back to the old window.  I feel like it's a bad experience, but I guess it's low pri?

**Comment by joshaber** [comment]
Huh, this is probably because we hide the window instead of closing it. We could try hiding the whole app instead of just the window, maybe.
