### ISSUE TITLE
Rebase not functional

### ISSUE THREAD

**Issue by kamapcrazy** [desktop/desktop#19014]
### The problem

try to rebase feature branch onto master branch doesn't work.

### Release version

Version 3.4.2 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Checkout "feature" branch
2. Open "History" tab
3. Select "master" branch under textbox "Select branch to compare..."
![image](https://github.com/user-attachments/assets/6afdb24a-0d6a-4daf-a9ee-70b09c3b372a)
4. Select "Rebase" option at the bottom of sidebar
![image](https://github.com/user-attachments/assets/b3323cc7-7056-4af8-a84d-96d5ea1b9d1e)
5. Click "Rebase" button

**Comment by steveward** [comment]
@kamapcrazy thanks for the issue. Is the rebase option disabled? Does the video in https://github.com/desktop/desktop/issues/17892 align with what you are seeing as well?

**Comment by kamapcrazy** [comment]
Hi @steveward ,

That way works for me
![image](https://github.com/user-attachments/assets/cd85554b-0743-4959-8275-f4b5292cbcb4)

But it's better if can do here (for now, when I click "Rebase", nothing happen)
![image](https://github.com/user-attachments/assets/72aa55fb-d7fe-47f1-ac9a-859b2fcbc714)



Thanks

**Comment by steveward** [comment]
Thanks for the screenshots. I think you're encountering https://github.com/desktop/desktop/issues/17892, which should hopefully be resolved by https://github.com/desktop/desktop/pull/19031. I'd recommend following along there for updates and then checking to see if you are still able to reproduce this issue after that ships.
