### ISSUE TITLE
Nuisance prompts for ssh key passphrase & "remember passphrase" doesn't work

### ISSUE THREAD

**Issue by jmos-spare** [desktop/desktop#19019]
### The problem

The app repeatedly prompts me for my SSH key passphrase throughout the day, triggered by a background fetch. If I enter my passphrase and check the "Remember passphrase" box, at some point I will be prompted again on a future background fetch. However, the prompt is clearly not required; if I trigger an action manually, I'm not prompted and the action succeeds. I only have two repos added to GitHub Desktop, and I can confirm both work for manual actions without prompting for a passphrase. Something somewhere is remembering the passphrase, but sometimes it doesn't work for background fetch.

### Release version

3.4.2

### Operating system

macOS Sonoma 14.5

### Steps to reproduce the behavior

1. Have an SSH key with a passphrase, with that passphrase added to ssh-agent or whatever
  - may be relevant: I'm also using the following settings in my ~/.ssh/config:
  ```
  Host *
    UseKeychain yes
    ControlMaster auto
    ControlPath /tmp/%r@%h:%p
    ControlPersist yes
  ```
2. Clone a repo or two via SSH with that key from the command line
3. Add that/those repo(s) to GitHub Desktop
4. Wait for a background fetch

### Log files

[2024-07-26.desktop.production.log](https://github.com/user-attachments/files/16392516/2024-07-26.desktop.production.log)

This was the first thing I did this morning:
- look at GitHub Desktop which had been open overnight
- saw the passphrase prompt
- entered my passphrase & checked "Remember passphrase"
The fetch seemed to complete without errors after that, or at least the UI didn't surface any errors to me.

**Comment by sergiou87** [comment]
There seem to be errors fetching, hence why it doesn't actually store the passphrase you entered 😕 

```
stderr:
mux_client_request_session: read from master failed: Broken pipe
ssh_dispatch_run_fatal: Connection to 140.82.113.4 port 22: Broken pipe
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Does it work if you select that repository and fetch manually?

**Comment by jmos-spare** [comment]
> Does it work if you select that repository and fetch manually?

Yes, I can manually fetch either of the two repositories I have added at any time, and I'm not prompted for a password when I do.

I suspect my ssh configuration (specifically the ControlPersist setting) is causing intermittent connection failures. I just wish those intermittent failures didn't cause spurious auth prompts; auth isn't the reason the action failed in this instance, the command simply needs to be retried.

**Comment by sergiou87** [comment]
@jmos-spare I think you're right, I've changed the logic to only delete the passphrase if the reason for failing is an auth error. Would you mind trying out a test build? I will prepare one tomorrow if you'd like.

Thank you! 🙏

**Comment by jmos-spare** [comment]
Would be happy to try a test build!

**Comment by sergiou87** [comment]
@jmos-spare here you have it!

- macOS (Apple silicon): https://centralreleases.blob.core.windows.net/github-desktop/releases/3.4.3-test2-79ed69f3/GitHubDesktop-arm64.zip
- macOS (Intel): https://centralreleases.blob.core.windows.net/github-desktop/releases/3.4.3-test2-79ed69f3/GitHubDesktop-x64.zip
- Windows: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.4.3-test2-79ed69f3/GitHubDesktopSetup-x64.exe

I also made a change so Desktop doesn't prompt for the SSH passphrase of a repository unless it's selected (i.e. it won't do that for background fetching).

Let me know if that works better 🙏  Thanks for all your help!! 💖

**Comment by jmos-spare** [comment]
Looks good so far! I'll keep watching it today but I haven't seen an auth prompt from the test build yet. Thank you for the quick fix!

**Comment by jmos-spare** [comment]
Zero auth prompts from the test build 🎉 I think that's solved it! Thanks again!

**Comment by sergiou87** [comment]
Thanks for testing it and letting us know 🙇‍♂
