### ISSUE TITLE
DataRay camera offset issue in !TB_PTC_4.1.1.py

### ISSUE THREAD

**Issue by SVS-Labuser** [desktop/desktop#19021]
### The problem

DataRay cameras being run with !TB_PTC_4.1.1.py have their offsets set higher than 1.5. They need to remain at 1.5.

### Release version

!TB_PTC_4.1.1.py

### Operating system

Windows 10

### Steps to reproduce the behavior

all contained in script

**Comment by steveward** [comment]
@SVS-Labuser this issue tracker is for GitHub Desktop, it looks like you are trying to find support for another repository on GitHub, so I'm going to close this out.
