### ISSUE TITLE
Getting error while starting desktop

### ISSUE THREAD

**Issue by cw-pratik** [desktop/desktop#1902]
### Description

I am not able to open any of my local repositories on my desktop.
I get the following error

"fatal: open /dev/null or dup failed: No such file or directory"

### Version

**GitHub Desktop version:** 0.5.9

**OS version:** Microsoft Windows [Version 10.0.10586]

### Steps to Reproduce

1. Start github desktop
1. The above error shows up repeatedly

**Expected behaviour:** It should start properly and show which files are not committed

**Reproduces how often:** This is now occuring every time I start github desktop

There is nothing there in the log file except for "info: Stats reported."

**Comment by cw-pratik** [comment]
Found the issue. The issue was not with github desktop. Even gitbash stopped working. 
On further investigating the issue found that the /dev/nul for my windows was not working. 

https://answers.microsoft.com/en-us/windows/forum/windows_10-files/windows-10-device-not-working-devnull/358dd2bb-880a-420c-af6c-133ef79be9c5

This helped in fixing the issue

**Comment by delowarhym** [comment]
hello pratik hurry up, you try again i seem you will can it .
