### ISSUE TITLE
unity commit code when create new project 

### ISSUE THREAD

**Issue by HungBuii** [desktop/desktop#19025]
### The problem

so many files (> 20.000 files or > 40.000 files)

### Release version

3.4.2 (x64)

### Operating system

Windows

**Comment by sergiou87** [comment]
Unfortunately, there is a limitation in Node that prevents GitHub Desktop from processing so many changes. Please, use the command line to make that first commit with something like:
```
git commit -a -m "First commit"
```

And then everything should work as expected again 🤞 

Related: https://github.com/desktop/desktop/issues/15486#issuecomment-1422264891
