### ISSUE TITLE
GitHub Desktop Hang in Version 3.4.2 (x64) RangeError ERR_CHILD_PROCESS_STDIO_MAXBUFFER

### ISSUE THREAD

**Issue by keaedwar** [desktop/desktop#19020]
### The problem

Brought up GitHub Desktop, went to one of my repos and was stepping through the changes made to each file, after the second file, I was unable to select the third file and GitHub Desktop stopped responding. 

### Release version

3.4.2 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

I can't reproduce this on demand, but here are the steps (the log is attached)

1. Brought up GitHub Desktop
2. Selected one of my repos from the Current repository list
3. I stepped through each change starting from the top
4. after the second file
5. I was unable to select the third file
6. GitHub Desktop stopped responding.
7. Brought up Windows Task Manager
8. Task Manager didn't show GitHubDesktop as hung or anything but the app was not responding.
9. Task Chain only showed two subtasks (GitHub Desktop & GitHubDesktop.exe)
10. Selected End Task
11. Restarted GitHub Desktop app
12. Went through steps above (2-5) without any hang.
13. Brought up Windows Task Manager
14. Task Manager shows four sub tasks 1-GitHub Desktop and 3-GitHubDesktop.exe
15. Seems to work fine now.
16. Logs show RangeError

### Log files

[2024-07-26.desktop.production.log](https://github.com/user-attachments/files/16392860/2024-07-26.desktop.production.log)

### Additional context

Probably got the ERR_CHILD_PROCESS_STDIO_MAXBUFFER as reported in the log file and wasn't able to recover from the error. Not sure why the maxbuffer error happened. Could have been a burp on the github enterprise server.

**Comment by steveward** [comment]
Thanks for the report @keaedwar. I'm going to add this to https://github.com/desktop/desktop/issues/15486 where we are tracking reports of this issue.
