### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by dwinfield23** [desktop/desktop#19022]
GitHub Desktop was unable to store the account token in the keychain. Please check you have unlocked access to the 'login' keychain. This is what I see when I try to sign in.

**Comment by steveward** [comment]
Thanks for the report @dwinfield23. We've had previous reports of this (see https://github.com/desktop/desktop/issues/17892), but have not seen many recently. Previously it was resolvable by unlocking and then locking `Keychain Access` again. See [this document](https://github.com/desktop/desktop/issues/17892). Let me know if that helps.
