### ISSUE TITLE
CTRL+F doesn't show matching words in green commit lines

### ISSUE THREAD

**Issue by kyle-sylvestre** [desktop/desktop#19033]
### The problem

when you bring up the CTRL+F input box in the commit change window, matching words in green commit lines will not change their background color.

### Release version

Version 3.4.2 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

make a commit, search for a word that exists before and after the change.

### Screenshots

![Untitled2](https://github.com/user-attachments/assets/214d5e69-08ba-4567-8770-a90a320fb251)

**Comment by tidy-dev** [comment]
@kyle-sylvestre Thanks for the report. Closing as a duplicate of https://github.com/desktop/desktop/issues/18323
