### ISSUE TITLE
Add a search for the Changes list of files.

### ISSUE THREAD

**Issue by SniperED007** [desktop/desktop#19037]
### The feature request

Please add a search option for the Changes list of files.

### Proposed solution

Please add a search option for the Changes list of files.

**Comment by steveward** [comment]
Thanks for the feedback @SniperED007. We are tracking this in https://github.com/desktop/desktop/issues/6407, you can follow along there for updates about this feature.

**Comment by Annie602942** [comment]
> Thanks for the feedback @SniperED007. We are tracking this in https://github.com/desktop/desktop/issues/6407, you can follow along there for updates about this feature.
