### ISSUE TITLE
Cannot View History of SQL File in GitHub Desktop

### ISSUE THREAD

**Issue by stevenmg** [desktop/desktop#1904]
### Description

I cannot view the history of an SQL file in GitHub Desktop. The text area simply says "The binary file has changed. Open file in external program."

### Version

**GitHub Desktop version:** 0.5.9

**OS version:** Windows 10

### Steps to Reproduce

1. Clone repository with sql file
2. Open the history tab
3. Attempt to view a specific change

**Comment by shiftkey** [comment]
@stevenmg can you provide some information about the repository so we can investigate further:

 - can you show a screenshot of the problem commit, and the file Git is trying to diff?
 - is the repository public, so we can troubleshoot things quicker from our side?

**Comment by stevenmg** [comment]
The repository is not public, but I'll try to give some more info here. The file I am trying to compare is a unicode text file with a .sql extension. It is a PostgreSQL database schema dump created with the pg_dump utility. As for the commit, there is no specific problem commit, GitHub Desktop is simply incapable of rendering the file at all. It is a 4MB file so that could be the reason as well, but 4MB is easily handled by even the simplest text editors such as Notepad, and other Git Windows clients handle it without any trouble.

**Comment by shiftkey** [comment]
@stevenmg thanks for the extra information. This might be related to how Git detects binary content. If you have Git on the command line, you should be able to run this command and see what Desktop is displaying:

```
git log [commit] -m -1 --first-parent --patch-with-raw -- [path-to-sql-file]
```

> The file I am trying to compare is a unicode text file with a .sql extension. 

I need to refresh my memory and find the area of the Git source that covers how Git detects binary files, but the fact we're talking about Unicode (and not just UTF-8) makes me think this is an important point.

**Comment by stevenmg** [comment]
Below is the output from running the command above.

```
Author: Steve Glick <sglick@*********>
Date:   Sat May 27 03:02:53 2017 -0400

    Schema dump at 5/27/2017 3:02:53 AM

:100644 100644 edcfe06... 4f358dd... M  schema.sql

diff --git a/schema.sql b/schema.sql
index edcfe06..4f358dd 100644
Binary files a/schema.sql and b/schema.sql differ
```

**Comment by shiftkey** [comment]
@stevenmg cool, good to know we're on the right track at least. I'm not sure how fixable this issue is, but I'll at least give some back story on what Git is doing here.

**Comment by shiftkey** [comment]
I believe the part of Git that you're running into is [this function](https://github.com/git/git/blob/master/xdiff-interface.c#L199):

```c
#define FIRST_FEW_BYTES 8000
int buffer_is_binary(const char *ptr, unsigned long size)
{
	if (FIRST_FEW_BYTES < size)
		size = FIRST_FEW_BYTES;
	return !!memchr(ptr, 0, size);
}
```

[`memchr`](http://man7.org/linux/man-pages/man3/memchr.3.html) is a simple function to scan for the presence of a character - in this case the `0` character.  And 8000 characters is a lot of chances for something unexpected to get caught in this.

[This Stackoverflow answer](https://stackoverflow.com/a/28145968/1363815) has some other details, and suggests a way to enable it to tell Git "this is fine, treat it as a text file".

I'm going to close this out as it's not something that we can fix explicitly in Desktop - it'll need upstream changes and probably some long discussions.
