### ISSUE TITLE
Request: for "Github desktop" app, make it remember last commits when about to commit new changes

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [desktop/desktop#19044]
### The feature request

On Android Studio, each time you choose to commit the changes, it auto-fills from last commit.
It also has a button of history for the last commits right there, to auto-fill from the chosen one.

### Proposed solution

Please offer these features too right in the commit UI.

### Additional context

Here's a video of how it looks like on Android Studio:

[studio64_2024-07-31_22-35-28.zip](https://github.com/user-attachments/files/16446401/studio64_2024-07-31_22-35-28.zip)

And how it looks like in Github-desktop app:

![image](https://github.com/user-attachments/assets/96b56d79-fc04-4449-889c-f415a687c515)

It is said that Android Studio will have a button for suggesting the commit text by itself, by checking out the code. 
For some reason it's grayed for me right now.

**Comment by steveward** [comment]
@AndroidDeveloperLB Thanks for the issue. https://github.com/desktop/desktop/issues/17439 may be what you are interested in -- essentially having Copilot look at your changes and write a commit message for you. Does that issue align with what you are looking for?

**Comment by AndroidDeveloperLB** [comment]
@steveward I wrote the AI feature as a side request. 
The basic one is what I wrote above it, including a video, and should be much easier: Just have a history of previous ones, have an easy way to auto-fill from a selection, and offer the recent one by default.

Please watch the video.

BTW, can you please answer why on Github Desktop it's split to title&message, yet on Android Studio and TortoiseGit it's just a textbox of "message" alone?
Is it possible to have it merged like there?

**Comment by steveward** [comment]
> BTW, can you please answer why on Github Desktop it's split to title&message, yet on Android Studio and TortoiseGit it's just a textbox of "message" alone?
> Is it possible to have it merged like there?

We chose to separate the summary and description, and this is not something we have any plans to change. 

In the interest of keeping things consolidated I'm going to add this into https://github.com/desktop/desktop/issues/1646 where there has been previous discussion about implementing a history of commit messages.

**Comment by AndroidDeveloperLB** [comment]
Can you please make it customizable (a toggle in the settings to have just message instead of title&message)? Usually I don't need a title, but a message about all changes instead. Also it's nicer to have all tools be consistent with one another.

About the previous commits messages, thank you. I hope it won't be forgotten there...
