### ISSUE TITLE
GitHub: fatal: bad boolean config value ''*'' for 'core.safecrlf'

### ISSUE THREAD

**Issue by gjcarver** [desktop/desktop#19049]
### The problem

GitHub: fatal: bad boolean config value ''*'' for 'core.safecrlf'

### Release version

Version 3.3.18 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Any interaction with the Github site.

### Log files

[2024-08-01.desktop.production.log](https://github.com/user-attachments/files/16455134/2024-08-01.desktop.production.log)

### Additional context

No useful advice on how to fix this online.

**Comment by sergiou87** [comment]
Could you run `git config --list --show-origin` from that repository? You should see some kind of `core.safecrlf=*` line in there and the file where that value is set. If you didn't add that config yourself, please remove it and try again.

**Comment by gjcarver** [comment]
It was just a mess: the terminal was opening in the wrong directory because I had made a copy of one project and stripped it down to just the core files I needed to debug a problem section so I could load it to GitHub so I could get some advice, and I didn't notice it was in the wrong directory, so I ended up editing the wrong files, but got it eventually.
