### ISSUE TITLE
performance issues when using latest version

### ISSUE THREAD

**Issue by orochi02** [desktop/desktop#19057]
### The problem

when i use github desktop and try to do stuff that interacts with the remote it starts to get **really** slow to the point some operations timeout and/or fail with authentication failed.

it is **not** an authentication failure, as previous operations in the same "_action_" seem to work just fine with the same ssh key + password (albeit as i mentioned it takes a long time).

the issues seem to mostly reside with fetching and pulling. pushing seems to be okay?

the aforementioned timeouts/fails occured for me when i tried to push commits but it doesnt seem to stem from the pushing itself.

### Release version

3.4.3

### Operating system

win10

### Steps to reproduce the behavior

fetch/pull from remote

### Additional context

tried with intellij and intellij seems to be normal. so issue seems to lie with github desktop.
i installed github desktop from scoop

**Comment by orochi02** [comment]
ofc if nobody seems to have similar issues feel free to close.

**Comment by sergiou87** [comment]
@orochi02 I think we have seen this from time to time but just rebooting or something like that solves the issue, so it might just be temporary for whatever reason 😕

**Comment by orochi02** [comment]
well, i have just downgraded to 3.4.2 and the isssues were gone. imma update back to 3.4.3 and see if the issue sticks around

**Comment by steveward** [comment]
@orochi02 are you running any antivirus/security software?

**Comment by orochi02** [comment]
> @orochi02 are you running any antivirus/security software?

positive

**Comment by orochi02** [comment]
> well, i have just downgraded to 3.4.2 and the isssues were gone. imma update back to 3.4.3 and see if the issue sticks around

btw i wrote the message above on friday and today is monday and still have the same issues.
yes i did shut down the pc on friday and started it today

**Comment by steveward** [comment]
If you are running antivirus software it may be worth trying to temporarily disable it to see if it helps at all with the performance issues. Let us know how that goes!

**Comment by orochi02** [comment]
tbh i dont think thats the issue because as i mentioned before the former version runs smoothly.
disabling the antivirus might be difficult also as this laptop is property of my current workplace and disabling the antivirus is not gonna be easy **but** i can try testing out the latest version on my personal laptop.
I will provide an update when ive tried it out

**Comment by steveward** [comment]
We commonly see these issues after releasing updates since it can trigger things in a/v software. I'm going to close this out and add it to https://github.com/desktop/desktop/issues/10625.
