### ISSUE TITLE
I log out in settings but can still pull and push commits

### ISSUE THREAD

**Issue by derzorngottes** [desktop/desktop#19059]
### The problem

I am trying to log in and out so that I can forcibly refresh the account state to try and deal with [this other issue about deleted branches still showing up in the dropdown](https://github.com/desktop/desktop/issues/5893) (PLEASE FIX THIS PLEASE!)

However when I log out, I still see my user account and am still able to pull and push commits. I am logged out in the settings view only, it appears.

### Release version

3.4.2

### Operating system

Windows 10

### Steps to reproduce the behavior

1. In en existing repo, logged in. Go to File > Options > Accounts.
2. Click on Sign out of GitHub.com, sign out appears to complete
3. Return to repo view, still appear to be logged in, can still fetch, create, and push commits.

### Log files

[2024-08-02.desktop.production.log](https://github.com/user-attachments/files/16474115/2024-08-02.desktop.production.log)

**Comment by derzorngottes** [comment]
Update: this persists even after uninstalling and reinstalling the application...

**Comment by steveward** [comment]
@derzorngottes logging out of the application does not remove your local repositories from GitHub Desktop, and the data persists after uninstalling as well unless you manually delete the application directories. Are you just wanting to prune branches that have been deleted on the remote?

**Comment by steveward** [comment]
You should not be able to push any commits if you are logged out, though, unless you are pushing to a third-party Git hosting service. Committing will still work since that is a local action, and you are not pushing anything up to the remote repository.
