### ISSUE TITLE
Github desktop app opens two vs code windows 

### ISSUE THREAD

**Issue by iFAXec** [desktop/desktop#19062]
### The problem

Hi, 
When I click "Open in Visual Studio Code", git hub opens two VS code windows.  Would you know why this is happening and how to resolve this? 

### Release version

Version 3.4.2 (x64)

### Operating system

Windows 10

**Comment by steveward** [comment]
@iFAXec thanks for the report. I think we've had a previous report similar to this, but I'm unable to dig it up at the moment. Can you try switching to a different default editor to see if you experience the same behavior there?
