### ISSUE TITLE
could you please look at these detai ls upon my g84 5g belived to be hacked modded i need to figure out how this keeps happening.

### ISSUE THREAD

**Issue by gazza242424** [desktop/desktop#19069]
### The feature request

C:\Users\GAZZA>c:/e/fastboot getvar all
(bootloader) kernel: uefi
(bootloader) version-bootloader[0]: MBM-3.0-uefi-c54f1b094a7-240611-U1TC
(bootloader) version-bootloader[1]: S34.22-64-18-2-31594
(bootloader) product: bangkk
(bootloader) board: bangkk
(bootloader) secure: yes
(bootloader) hwrev: PVT
(bootloader) radio: EUAPEM
(bootloader) storage-type: UFS
(bootloader) emmc: N/A
(bootloader) ufs: 256GB SKhynix H9QT1GGCN6X147 FV=A003 WB=2048
(bootloader) ram: 12GB SKHYNIX LP4x DIE=24Gb M5-M8=06 07 00 55
(bootloader) cpu: SM_STRAIT 1.0
(bootloader) serialno: ZT322K24NB
(bootloader) cid: 0x0032
(bootloader) channelid: 0x00
(bootloader) uid: C91770C4001A90E1
(bootloader) token: inactive
(bootloader) securestate: flashing_unlocked
(bootloader) factory-modes: disabled
(bootloader) verity-state: enforcing (0)
(bootloader) iswarrantyvoid: yes
(bootloader) max-download-size: 805306368
(bootloader) reason: Volume down key pressed
(bootloader) imei: 350162395956430
(bootloader) imei2: 350162395956448
(bootloader) esimid:
(bootloader) meid:
(bootloader) date: 11-18-2023
(bootloader) sku: XT2347-2
(bootloader) carrier_sku: XT2347-2
(bootloader) battid: SB18D88239
(bootloader) battery-voltage: 4486
(bootloader) iccid:
(bootloader) cust_md5:
(bootloader) max-sparse-size: 268435456
(bootloader) poweroffalarm: 0
(bootloader) ro.carrier: retgb
(bootloader) ro.build.fingerprint[0]: motorola/bangkk_ge/bangkk:14/U1TCS
(bootloader) ro.build.fingerprint[1]: 34.22-64-18-2/31594-b8200:user/rel
(bootloader) ro.build.fingerprint[2]: ease-keys
(bootloader) ro.build.version.qcom: LA.UM.9.16.r1-14900-MANNAR.QSSI14.0
(bootloader) version-baseband[0]: M6375_HI434_21.545.02.160R BANGKOK5G_P
(bootloader) version-baseband[1]: VT_EUAPEMDSDS_CUST
(bootloader) kernel.version[0]: Linux version 5.4.254-moto-g512c2e8a948c
(bootloader) kernel.version[1]:  (nobody@android-build) (Android (687736
(bootloader) kernel.version[2]: 6 based on r383902b1) clang version 11.0
(bootloader) kernel.version[3]: .2 (https://android.googlesource.com/too
(bootloader) kernel.version[4]: lchain/llvm-project b397f81060ce6d701042
(bootloader) kernel.version[5]: b782172ed13bee898b79), LLD 11.0.2 (https
(bootloader) kernel.version[6]: ://android.googlesource.com/toolchain/ll
(bootloader) kernel.version[7]: vm-project b397f81060ce6d701042b782172ed
(bootloader) kernel.version[8]: 13bee898b79)) #1 SMP PREEMPT Tue Jun 11
(bootloader) kernel.version[9]: 09:38:42 CDT 2024
(bootloader) git:xbl: MBM-3.0-uefi-779c2128af-240611
(bootloader) git:xbl_config: MBM-3.0-uefi-779c2128af-240611
(bootloader) git:abl:
(bootloader) MBM-3.0-uefi-c54f1b094a7-240611-U1TCS34.22-64-18-2-315
(bootloader) git:rpm: MBM-3.0-uefi-970346eb-240611
(bootloader) git:tz: MBM-3.0-uefi-3277c6236-240611
(bootloader) git:hyp: MBM-3.0-uefi-3277c6236-240611
(bootloader) git:devcfg: MBM-3.0-uefi-3277c6236-240611
(bootloader) git:keymaster: MBM-3.0-uefi-2bbb3ced-240611
(bootloader) git:storsec: MBM-3.0-uefi-2bbb3ced-240611
(bootloader) git:uefisecapp: MBM-3.0-uefi-2bbb3ced-240611
(bootloader) git:prov: MBM-3.0-uefi-3277c6236-240611
(bootloader) git:qupfw: MBM-3.0-uefi-3e19f77-240611
(bootloader) frp-state: no protection (0)
(bootloader) current-slot: a
(bootloader) running-bl-slot: _a/_a
(bootloader) running-boot-lun: 1
(bootloader) slot-count: 2
(bootloader) slot-successful:_a: yes
(bootloader) slot-successful:_b: no
(bootloader) slot-unbootable:_a: no
(bootloader) slot-unbootable:_b: no
(bootloader) slot-retry-count:_a: 6
(bootloader) slot-retry-count:_b: 0
(bootloader) logical-block-size: 0x1000
(bootloader) erase-block-size: 0x1000
(bootloader) is-userspace: no
(bootloader) pcb-part-no: SP69A6PU3J
(bootloader) snapshot-update-status: none
(bootloader) primary-display: tm_nt37703_U8_1080x2400_655_dsc_vdo
(bootloader) secondary-display:
(bootloader) fdr-allowed: yes
all: listed above
Finished. Total time: 0.247s

C:\Users\GAZZA>c:/e/fastboot getvar all
(bootloader) kernel: uefi
(bootloader) version-bootloader[0]: MBM-3.0-uefi-c54f1b094a7-240611-U1TC
(bootloader) version-bootloader[1]: S34.22-64-18-2-31594
(bootloader) product: bangkk
(bootloader) board: bangkk
(bootloader) secure: yes
(bootloader) hwrev: PVT
(bootloader) radio: EUAPEM
(bootloader) storage-type: UFS
(bootloader) emmc: N/A
(bootloader) ufs: 256GB SKhynix H9QT1GGCN6X147 FV=A003 WB=2048
(bootloader) ram: 12GB SKHYNIX LP4x DIE=24Gb M5-M8=06 07 00 55
(bootloader) cpu: SM_STRAIT 1.0
(bootloader) serialno: ZT322K24NB
(bootloader) cid: 0x0032
(bootloader) channelid: 0x00
(bootloader) uid: C91770C4001A90E1
(bootloader) token: inactive
(bootloader) securestate: flashing_unlocked
(bootloader) factory-modes: disabled
(bootloader) verity-state: enforcing (0)
(bootloader) iswarrantyvoid: yes
(bootloader) max-download-size: 805306368
(bootloader) reason: Volume down key pressed
(bootloader) imei: 350162395956430
(bootloader) imei2: 350162395956448
(bootloader) esimid:
(bootloader) meid:
(bootloader) date: 11-18-2023
(bootloader) sku: XT2347-2
(bootloader) carrier_sku: XT2347-2
(bootloader) battid: SB18D88239
(bootloader) battery-voltage: 4480
(bootloader) iccid:
(bootloader) cust_md5:
(bootloader) max-sparse-size: 268435456
(bootloader) poweroffalarm: 0
(bootloader) ro.carrier: retgb
(bootloader) ro.build.fingerprint[0]: motorola/bangkk_ge/bangkk:14/U1TCS
(bootloader) ro.build.fingerprint[1]: 34.22-64-18-2/31594-b8200:user/rel
(bootloader) ro.build.fingerprint[2]: ease-keys
(bootloader) ro.build.version.qcom: LA.UM.9.16.r1-14900-MANNAR.QSSI14.0
(bootloader) version-baseband[0]: M6375_HI434_21.545.02.160R BANGKOK5G_P
(bootloader) version-baseband[1]: VT_EUAPEMDSDS_CUST
(bootloader) kernel.version[0]: Linux version 5.4.254-moto-g512c2e8a948c
(bootloader) kernel.version[1]:  (nobody@android-build) (Android (687736
(bootloader) kernel.version[2]: 6 based on r383902b1) clang version 11.0
(bootloader) kernel.version[3]: .2 (https://android.googlesource.com/too
(bootloader) kernel.version[4]: lchain/llvm-project b397f81060ce6d701042
(bootloader) kernel.version[5]: b782172ed13bee898b79), LLD 11.0.2 (https
(bootloader) kernel.version[6]: ://android.googlesource.com/toolchain/ll
(bootloader) kernel.version[7]: vm-project b397f81060ce6d701042b782172ed
(bootloader) kernel.version[8]: 13bee898b79)) #1 SMP PREEMPT Tue Jun 11
(bootloader) kernel.version[9]: 09:38:42 CDT 2024
(bootloader) git:xbl: MBM-3.0-uefi-779c2128af-240611
(bootloader) git:xbl_config: MBM-3.0-uefi-779c2128af-240611
(bootloader) git:abl:
(bootloader) MBM-3.0-uefi-c54f1b094a7-240611-U1TCS34.22-64-18-2-315
(bootloader) git:rpm: MBM-3.0-uefi-970346eb-240611
(bootloader) git:tz: MBM-3.0-uefi-3277c6236-240611
(bootloader) git:hyp: MBM-3.0-uefi-3277c6236-240611
(bootloader) git:devcfg: MBM-3.0-uefi-3277c6236-240611
(bootloader) git:keymaster: MBM-3.0-uefi-2bbb3ced-240611
(bootloader) git:storsec: MBM-3.0-uefi-2bbb3ced-240611
(bootloader) git:uefisecapp: MBM-3.0-uefi-2bbb3ced-240611
(bootloader) git:prov: MBM-3.0-uefi-3277c6236-240611
(bootloader) git:qupfw: MBM-3.0-uefi-3e19f77-240611
(bootloader) frp-state: no protection (77)
(bootloader) current-slot: a
(bootloader) running-bl-slot: _a/_a
(bootloader) running-boot-lun: 1
(bootloader) slot-count: 2
(bootloader) slot-successful:_a: yes
(bootloader) slot-successful:_b: no
(bootloader) slot-unbootable:_a: no
(bootloader) slot-unbootable:_b: no
(bootloader) slot-retry-count:_a: 6
(bootloader) slot-retry-count:_b: 0
(bootloader) logical-block-size: 0x1000
(bootloader) erase-block-size: 0x1000
(bootloader) is-userspace: no
(bootloader) pcb-part-no: SP69A6PU3J
(bootloader) snapshot-update-status: none
(bootloader) primary-display: tm_nt37703_U8_1080x2400_655_dsc_vdo
(bootloader) secondary-display:
(bootloader) fdr-allowed: yes
all: listed above
Finished. Total time: 0.153s

### Proposed solution

dunno advice needed i keep getting this happening,on multiple of fones from bck in 2021 till now i just know that shared storage 
isnt what my andriod shud have i i noticed the change 

### Additional context

please advise upon the info i sent thanks gareth robinson

**Comment by gazza242424** [comment]
what is clang version 11

**Comment by spiralgang** [comment]
> ### The feature request
> 
> C:\Users\GAZZA>c:/e/fastboot getvar all
> (bootloader) kernel: uefi
> (bootloader) version-bootloader[0]: MBM-3.0-uefi-c54f1b094a7-240611-U1TC
> (bootloader) version-bootloader[1]: S34.22-64-18-2-31594
> (bootloader) product: bangkk
> (bootloader) board: bangkk
> (bootloader) secure: yes
> (bootloader) hwrev: PVT
> (bootloader) radio: EUAPEM
> (bootloader) storage-type: UFS
> (bootloader) emmc: N/A
> (bootloader) ufs: 256GB SKhynix H9QT1GGCN6X147 FV=A003 WB=2048
> (bootloader) ram: 12GB SKHYNIX LP4x DIE=24Gb M5-M8=06 07 00 55
> (bootloader) cpu: SM_STRAIT 1.0
> (bootloader) serialno: ZT322K24NB
> (bootloader) cid: 0x0032
> (bootloader) channelid: 0x00
> (bootloader) uid: C91770C4001A90E1
> (bootloader) token: inactive
> (bootloader) securestate: flashing_unlocked
> (bootloader) factory-modes: disabled
> (bootloader) verity-state: enforcing (0)
> (bootloader) iswarrantyvoid: yes
> (bootloader) max-download-size: 805306368
> (bootloader) reason: Volume down key pressed
> (bootloader) imei: 350162395956430
> (bootloader) imei2: 350162395956448
> (bootloader) esimid:
> (bootloader) meid:
> (bootloader) date: 11-18-2023
> (bootloader) sku: XT2347-2
> (bootloader) carrier_sku: XT2347-2
> (bootloader) battid: SB18D88239
> (bootloader) battery-voltage: 4486
> (bootloader) iccid:
> (bootloader) cust_md5:
> (bootloader) max-sparse-size: 268435456
> (bootloader) poweroffalarm: 0
> (bootloader) ro.carrier: retgb
> (bootloader) ro.build.fingerprint[0]: motorola/bangkk_ge/bangkk:14/U1TCS
> (bootloader) ro.build.fingerprint[1]: 34.22-64-18-2/31594-b8200:user/rel
> (bootloader) ro.build.fingerprint[2]: ease-keys
> (bootloader) ro.build.version.qcom: LA.UM.9.16.r1-14900-MANNAR.QSSI14.0
> (bootloader) version-baseband[0]: M6375_HI434_21.545.02.160R BANGKOK5G_P
> (bootloader) version-baseband[1]: VT_EUAPEMDSDS_CUST
> (bootloader) kernel.version[0]: Linux version 5.4.254-moto-g512c2e8a948c
> (bootloader) kernel.version[1]:  (nobody@android-build) (Android (687736
> (bootloader) kernel.version[2]: 6 based on r383902b1) clang version 11.0
> (bootloader) kernel.version[3]: .2 (https://android.googlesource.com/too
> (bootloader) kernel.version[4]: lchain/llvm-project b397f81060ce6d701042
> (bootloader) kernel.version[5]: b782172ed13bee898b79), LLD 11.0.2 (https
> (bootloader) kernel.version[6]: ://android.googlesource.com/toolchain/ll
> (bootloader) kernel.version[7]: vm-project b397f81060ce6d701042b782172ed
> (bootloader) kernel.version[8]: 13bee898b79)) #1 SMP PREEMPT Tue Jun 11
> (bootloader) kernel.version[9]: 09:38:42 CDT 2024
> (bootloader) git:xbl: MBM-3.0-uefi-779c2128af-240611
> (bootloader) git:xbl_config: MBM-3.0-uefi-779c2128af-240611
> (bootloader) git:abl:
> (bootloader) MBM-3.0-uefi-c54f1b094a7-240611-U1TCS34.22-64-18-2-315
> (bootloader) git:rpm: MBM-3.0-uefi-970346eb-240611
> (bootloader) git:tz: MBM-3.0-uefi-3277c6236-240611
> (bootloader) git:hyp: MBM-3.0-uefi-3277c6236-240611
> (bootloader) git:devcfg: MBM-3.0-uefi-3277c6236-240611
> (bootloader) git:keymaster: MBM-3.0-uefi-2bbb3ced-240611
> (bootloader) git:storsec: MBM-3.0-uefi-2bbb3ced-240611
> (bootloader) git:uefisecapp: MBM-3.0-uefi-2bbb3ced-240611
> (bootloader) git:prov: MBM-3.0-uefi-3277c6236-240611
> (bootloader) git:qupfw: MBM-3.0-uefi-3e19f77-240611
> (bootloader) frp-state: no protection (0)
> (bootloader) current-slot: a
> (bootloader) running-bl-slot: _a/_a
> (bootloader) running-boot-lun: 1
> (bootloader) slot-count: 2
> (bootloader) slot-successful:_a: yes
> (bootloader) slot-successful:_b: no
> (bootloader) slot-unbootable:_a: no
> (bootloader) slot-unbootable:_b: no
> (bootloader) slot-retry-count:_a: 6
> (bootloader) slot-retry-count:_b: 0
> (bootloader) logical-block-size: 0x1000
> (bootloader) erase-block-size: 0x1000
> (bootloader) is-userspace: no
> (bootloader) pcb-part-no: SP69A6PU3J
> (bootloader) snapshot-update-status: none
> (bootloader) primary-display: tm_nt37703_U8_1080x2400_655_dsc_vdo
> (bootloader) secondary-display:
> (bootloader) fdr-allowed: yes
> all: listed above
> Finished. Total time: 0.247s
> 
> 
> C:\Users\GAZZA>c:/e/fastboot getvar all
> (bootloader) kernel: uefi
> (bootloader) version-bootloader[0]: MBM-3.0-uefi-c54f1b094a7-240611-U1TC
> (bootloader) version-bootloader[1]: S34.22-64-18-2-31594
> (bootloader) product: bangkk
> (bootloader) board: bangkk
> (bootloader) secure: yes
> (bootloader) hwrev: PVT
> (bootloader) radio: EUAPEM
> (bootloader) storage-type: UFS
> (bootloader) emmc: N/A
> (bootloader) ufs: 256GB SKhynix H9QT1GGCN6X147 FV=A003 WB=2048
> (bootloader) ram: 12GB SKHYNIX LP4x DIE=24Gb M5-M8=06 07 00 55
> (bootloader) cpu: SM_STRAIT 1.0
> (bootloader) serialno: ZT322K24NB
> (bootloader) cid: 0x0032
> (bootloader) channelid: 0x00
> (bootloader) uid: C91770C4001A90E1
> (bootloader) token: inactive
> (bootloader) securestate: flashing_unlocked
> (bootloader) factory-modes: disabled
> (bootloader) verity-state: enforcing (0)
> (bootloader) iswarrantyvoid: yes
> (bootloader) max-download-size: 805306368
> (bootloader) reason: Volume down key pressed
> (bootloader) imei: 350162395956430
> (bootloader) imei2: 350162395956448
> (bootloader) esimid:
> (bootloader) meid:
> (bootloader) date: 11-18-2023
> (bootloader) sku: XT2347-2
> (bootloader) carrier_sku: XT2347-2
> (bootloader) battid: SB18D88239
> (bootloader) battery-voltage: 4480
> (bootloader) iccid:
> (bootloader) cust_md5:
> (bootloader) max-sparse-size: 268435456
> (bootloader) poweroffalarm: 0
> (bootloader) ro.carrier: retgb
> (bootloader) ro.build.fingerprint[0]: motorola/bangkk_ge/bangkk:14/U1TCS
> (bootloader) ro.build.fingerprint[1]: 34.22-64-18-2/31594-b8200:user/rel
> (bootloader) ro.build.fingerprint[2]: ease-keys
> (bootloader) ro.build.version.qcom: LA.UM.9.16.r1-14900-MANNAR.QSSI14.0
> (bootloader) version-baseband[0]: M6375_HI434_21.545.02.160R BANGKOK5G_P
> (bootloader) version-baseband[1]: VT_EUAPEMDSDS_CUST
> (bootloader) kernel.version[0]: Linux version 5.4.254-moto-g512c2e8a948c
> (bootloader) kernel.version[1]:  (nobody@android-build) (Android (687736
> (bootloader) kernel.version[2]: 6 based on r383902b1) clang version 11.0
> (bootloader) kernel.version[3]: .2 (https://android.googlesource.com/too
> (bootloader) kernel.version[4]: lchain/llvm-project b397f81060ce6d701042
> (bootloader) kernel.version[5]: b782172ed13bee898b79), LLD 11.0.2 (https
> (bootloader) kernel.version[6]: ://android.googlesource.com/toolchain/ll
> (bootloader) kernel.version[7]: vm-project b397f81060ce6d701042b782172ed
> (bootloader) kernel.version[8]: 13bee898b79)) #1 SMP PREEMPT Tue Jun 11
> (bootloader) kernel.version[9]: 09:38:42 CDT 2024
> (bootloader) git:xbl: MBM-3.0-uefi-779c2128af-240611
> (bootloader) git:xbl_config: MBM-3.0-uefi-779c2128af-240611
> (bootloader) git:abl:
> (bootloader) MBM-3.0-uefi-c54f1b094a7-240611-U1TCS34.22-64-18-2-315
> (bootloader) git:rpm: MBM-3.0-uefi-970346eb-240611
> (bootloader) git:tz: MBM-3.0-uefi-3277c6236-240611
> (bootloader) git:hyp: MBM-3.0-uefi-3277c6236-240611
> (bootloader) git:devcfg: MBM-3.0-uefi-3277c6236-240611
> (bootloader) git:keymaster: MBM-3.0-uefi-2bbb3ced-240611
> (bootloader) git:storsec: MBM-3.0-uefi-2bbb3ced-240611
> (bootloader) git:uefisecapp: MBM-3.0-uefi-2bbb3ced-240611
> (bootloader) git:prov: MBM-3.0-uefi-3277c6236-240611
> (bootloader) git:qupfw: MBM-3.0-uefi-3e19f77-240611
> (bootloader) frp-state: no protection (77)
> (bootloader) current-slot: a
> (bootloader) running-bl-slot: _a/_a
> (bootloader) running-boot-lun: 1
> (bootloader) slot-count: 2
> (bootloader) slot-successful:_a: yes
> (bootloader) slot-successful:_b: no
> (bootloader) slot-unbootable:_a: no
> (bootloader) slot-unbootable:_b: no
> (bootloader) slot-retry-count:_a: 6
> (bootloader) slot-retry-count:_b: 0
> (bootloader) logical-block-size: 0x1000
> (bootloader) erase-block-size: 0x1000
> (bootloader) is-userspace: no
> (bootloader) pcb-part-no: SP69A6PU3J
> (bootloader) snapshot-update-status: none
> (bootloader) primary-display: tm_nt37703_U8_1080x2400_655_dsc_vdo
> (bootloader) secondary-display:
> (bootloader) fdr-allowed: yes
> all: listed above
> Finished. Total time: 0.153s
> 
> 
> ### Proposed solution
> 
> dunno advice needed i keep getting this happening,on multiple of fones from bck in 2021 till now i just know that shared storage 
> isnt what my andriod shud have i i noticed the change 
> 
> ### Additional context
> 
> please advise upon the info i sent thanks gareth robinson

_______________________

It looks like you're running the `fastboot getvar all` command to retrieve various details about your Android device. This command is useful for getting information about the bootloader, hardware, and other system properties[43dcd9a7-70db-4a1f-b0ae-981daa162054](https://commandmasters.com/commands/fastboot-common/?citationMarker=43dcd9a7-70db-4a1f-b0ae-981daa162054 "1")[43dcd9a7-70db-4a1f-b0ae-981daa162054](https://xdaforums.com/t/getvar-all-info.2269309/?citationMarker=43dcd9a7-70db-4a1f-b0ae-981daa162054 "2").

From the output you provided, it seems like your device has a UEFI kernel, a secure bootloader, and a variety of hardware specifications. However, you mentioned that you're experiencing issues with shared storage on multiple phones since 2021.

Here are a few steps you can take to troubleshoot and potentially resolve the issue:

1. **Check for Software Updates**: Ensure that your device's software is up to date. Sometimes, updates can fix bugs and improve system stability.

2. **Factory Reset**: If the issue persists, consider performing a factory reset. This will erase all data on your device, so make sure to back up important information before proceeding.

3. **Custom ROMs**: If you're comfortable with advanced troubleshooting, you might consider installing a custom ROM. Custom ROMs can offer different features and optimizations that might resolve your issue.

4. **Storage Management Apps**: Use storage management apps to monitor and manage your device's storage. These apps can help identify and resolve storage-related issues.

5. **Consult Forums**: Websites like XDA Developers have active communities where you can find advice and solutions from other users who might have faced similar issues[43dcd9a7-70db-4a1f-b0ae-981daa162054](https://xdaforums.com/t/getvar-all-info.2269309/?citationMarker=43dcd9a7-70db-4a1f-b0ae-981daa162054 "2").

If you need more specific guidance or have additional details to share, feel free to let me know!

[43dcd9a7-70db-4a1f-b0ae-981daa162054](https://commandmasters.com/commands/fastboot-common/?citationMarker=43dcd9a7-70db-4a1f-b0ae-981daa162054 "1"): [CommandMasters](https://commandmasters.com/commands/fastboot-common/)
[43dcd9a7-70db-4a1f-b0ae-981daa162054](https://xdaforums.com/t/getvar-all-info.2269309/?citationMarker=43dcd9a7-70db-4a1f-b0ae-981daa162054 "2"): [XDA Forums](https://xdaforums.com/t/getvar-all-info.2269309/)
