### ISSUE TITLE
Can't pull commits

### ISSUE THREAD

**Issue by guastucciaf** [desktop/desktop#19066]
### The problem

This message is shown when I try pull the commits: "fatal: bad object refs/remotes/origin/HEAD
error: https://github.com/guastucciaf/DevMedia-FrontEnd.git did not send all necessary objects"

### Release version

3.4.3 (x64)

### Operating system

Windows 10 Pro

**Comment by felipedrumond** [comment]
After the latest update I can't pull anything from Git Desktop, but from command prompt it works.

**Comment by steveward** [comment]
@guastucciaf thanks for the issue. Can you open the repository in the command line and run `git fsck` and let me know the output?

You may be able to resolve this by deleting the bad HEAD object and then running `git fetch --prune origin`. Let me know if that helps.
