### ISSUE TITLE
Hide Files in Changes View

### ISSUE THREAD

**Issue by mrmwiebe** [desktop/desktop#19075]
### The feature request

I would love to be able to "hide" unwanted files from the Changes tab. I don't want them fully ignored and added to the .gitignore, and I can't commit those files either because that would mess up other contributor's work. I just want to temporarily add them to a hidden list so my local copy of Github Desktop will always mark them as excluded and hidden from the Changes tab until the next time Github Desktop is opened, or hidden files is toggled off.

### Proposed solution

My changes tab often gets cluttered with files that Unity generates automatically and it gets annoying to constantly work around those files, making sure they are unchecked and will not be committed. It's nice that Github desktop already doesn't recheck those files if I've made further changes, but if I made a couple changes at once and I want to make separate commits for different files, it's frustrating to wade through all the files I know that I won't ever commit.

### Additional context

I work on a large project with many team members in Unity. Often after pulling from main, Unity will generate some atlas or meta files that I do not want to recommit and they will constantly appear in the Changes tab and I have to go through and uncheck them all manually. The tech lead said it would be annoying to fix just for me, so having this option on my end would be awesome.

**Comment by steveward** [comment]
Thanks for the feedback @mrmwiebe. We have an existing issue https://github.com/desktop/desktop/issues/6407 for filtering the changes list. Would that approach be helpful? There's another [user in that issue ](https://github.com/desktop/desktop/issues/6407#issuecomment-2199225363)who mentioned using Unity as well.

**Comment by mrmwiebe** [comment]
Ah thank you for the speedy response and for the links!

I think filtering would work because usually I'm working in specific folders so, perhaps if I could filter out everything but the folders i'm working in would be great.

Then for it to be truly useful, I can save filters and set one as default so it just auto-filters out as I'm working.

That help clarify? I can also respond to the existing issue as well if that helps.

**Comment by steveward** [comment]
Thanks, that's helpful! In the interest of keeping things consolidated I'm going to add this to #6407 since this is an idea that we're exploring.

**Comment by buzzkirill** [comment]
I also have this exact request and unfortunately the filter thing added in #20220 does not address it at all. I wonder if it were possible to add an "ignored files" option to that filter (not actually using git ignore, because that only complicates things).
