### ISSUE TITLE
Not added path in c automatically

### ISSUE THREAD

**Issue by Sarkheelmughal** [desktop/desktop#19073]
### The problem

In my android studio im getting Unable to find git in your PATH even after installing the git desktop version

### Release version

Version 3.4.3 (x64)

### Operating system

window 11

### Steps to reproduce the behavior

installed git and using it for my projects

### Log files

no available

### Screenshots

no

### Additional context

no

**Comment by steveward** [comment]
@Sarkheelmughal thanks for the issue. GitHub Desktop has its own custom version of Git for the app to use, so you will need to download Git for Windows separately:

https://git-scm.com/download/win

Let me know if you have any other questions.

**Comment by Sarkheelmughal** [comment]
Thanks.
I installed the git through Android studio and its now working fine.
