### ISSUE TITLE
Horizontal scrolling in diffs is not working while zoomed

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1907]
User cannot scroll horizontally in the diffs. Some files allow you to scroll partially, but not the the entire length of the file. Other files have no scroll bar whatsoever.

Zoom in, notice scroll bar or lack of it:
<img width="1165" alt="screen shot 2017-06-06 at 11 47 26 am" src="https://user-images.githubusercontent.com/14828183/26838466-27eb8954-4aae-11e7-89bd-536913b68ff1.png">
<img width="1167" alt="screen shot 2017-06-06 at 11 47 35 am" src="https://user-images.githubusercontent.com/14828183/26838465-27e3fad6-4aae-11e7-87de-659f0b3dae6f.png">

Zoom out, notice lack of scroll bar:
<img width="1165" alt="screen shot 2017-06-06 at 11 47 50 am" src="https://user-images.githubusercontent.com/14828183/26838469-28ac79de-4aae-11e7-9284-e00a7f531bdf.png">
<img width="1165" alt="screen shot 2017-06-06 at 11 47 58 am" src="https://user-images.githubusercontent.com/14828183/26838467-27ed79bc-4aae-11e7-9e55-2c44d78fb07d.png">

v0.5.9, OSX 10.11.5

**Comment by percyhanna** [comment]
I've found some issues with scrolling vertically in the diff as well.

**Comment by joshaber** [comment]
@percyhanna What sorts of issues? Are they also when zoomed in?

**Comment by percyhanna** [comment]
Here's a screen recording of the "bouncing" effect. No zooming. I am simply scrolling straight down, but the bouncing should be fairly clear (hopefully).

![scrolling](https://user-images.githubusercontent.com/125077/27197425-636ca188-51cb-11e7-8d52-2b8d630fa24a.gif)

**Comment by percyhanna** [comment]
The bouncing doesn't seem to occur on a brand new file, only on a file that has a more complex diff.

**Comment by joshaber** [comment]
@percyhanna Thanks, that looks like a manifestation of https://github.com/desktop/desktop/issues/1380.  If you're able to reproduce it consistently, especially after relaunching the app, please let me know in that issue!

**Comment by percyhanna** [comment]
@joshaber Yup, seems fixed after restart. Thanks 👍

**Comment by tierninho** [comment]
Cannot repro, closing.
