### ISSUE TITLE
Unable to push tags when branch name is main

### ISSUE THREAD

**Issue by tunaingot** [desktop/desktop#19082]
### The problem

Unable to push tags when branch name is main.
Changing the branch name to master will push the tag and also create the tag on the web.

### Release version

Version 3.4.3 (arm64)

### Operating system

macOS 14.6.1（23G93）

**Comment by tunaingot** [comment]
Unable to push tags when branch name is main

**Comment by steveward** [comment]
Thanks for the report @tunaingot. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by tunaingot** [comment]
2024-08-07 : I got an error when generating tags in the main branch.

2024-08-08 : Generating tags in the master branch did not result in an error.
** There may be a few errors as we were trying different things.



[2024-08-07.desktop.production.log](https://github.com/user-attachments/files/16562370/2024-08-07.desktop.production.log)
[2024-08-08.desktop.production.log](https://github.com/user-attachments/files/16562372/2024-08-08.desktop.production.log)

**Comment by steveward** [comment]
Thanks, the error looks like what I expected:

```
error: src refspec リピータ機能削除 matches more than one
error: failed to push some refs to 'https://github.com/tunaingot/WaterChecker.git'
```

If you have a branch and a tag that share the same name it can cause this issue. I would recommend deleting the `main` tag and renaming it so that you can prevent this issue. Let me know if you have any further questions.

**Comment by tunaingot** [comment]
Thank you for your answer.
I will give it a try.

I appreciate your prompt reply.
