### ISSUE TITLE
i cant sync my work between vscode and github

### ISSUE THREAD

**Issue by Ali-is-cool** [desktop/desktop#19083]
### The problem

when i try to sync my code in vscode to github an error message appears
![Screenshot (711)](https://github.com/user-attachments/assets/77508c88-9b57-4023-afbd-aa242a659ace)

### Release version

3.4.3 (x64)

### Operating system

windows 11

### Steps to reproduce the behavior

1. I go to source control and  press sync settings
2. see error

### Screenshots

![Uploading Screenshot (711).png…]()

**Comment by steveward** [comment]
@Ali-is-cool this issue tracker is for GitHub Desktop, we are not able to assist with support for VSCode. I would recommend opening the log and asking for help here: https://github.com/orgs/community/discussions/.
