### ISSUE TITLE
Support for Positron as editor

### ISSUE THREAD

**Issue by kv9898** [desktop/desktop#19087]
### The feature request

Currently VS Code and VS Codium are supported as default editors, while Positron, a new VS Codium-based IDE developed by Posit, is not yet supported by Github Desktop. 

### Proposed solution

Add Positron to the list of supported default editors.

### Additional context

Please see https://github.com/posit-dev/positron for the project.

**Comment by kv9898** [comment]
I hope what I provided in #19088 is helpful.

**Comment by sergiou87** [comment]
Hello 👋 

As mentioned in the PR, we recently added a way for users to just select any executable file and use it as editor or shell: #18954

That will be for now on the preferred way of using editors not in the hardcoded list of Desktop. You can give it a try in the latest beta from https://desktop.github.com/beta
