### ISSUE TITLE
Please Add File History option.

### ISSUE THREAD

**Issue by helpforsoftware** [desktop/desktop#19094]
### The feature request

sometimes we need to see a specific file's older commits and check for the line differences between old commits(old history)

### Proposed solution

it would be nice to see an option ,when we right click the file and as the popup menu appears , see an option  "compare.."  or "see differences." , and when we click compare ,there could be list of old history(revisions) of the file. and when i select two revisions from the list it compares selected two revisions. i could compare a revision with the latest revision or sometimes i could compare two older revisions i selected.
.i appreciate your work on contributing the project. Thank you.

**Comment by steveward** [comment]
Thanks for the feedback @helpforsoftware. This is being tracked in https://github.com/desktop/desktop/issues/11990, so I'm going to close this out and add your request there.
