### ISSUE TITLE
LFS push - Endless loop and mem leak

### ISSUE THREAD

**Issue by megerlms** [desktop/desktop#19099]
### The problem

Pushing a commit containing at least one large file (reproducable with 1GB and 3.5 GB) leads to an endless loop and memory leak.
The push seems to finish. So the tooltop says 1 completed 3.5GB/3.5GB but then it starts again from the beginning. This process never stops. In addition the computers memory is consumed in big chunks, so that after some complete rounds the PC stucks because all available memory is eaten up.
Because the push is not abortable the only solution is to reboot the PC.

In between there is a short period when the tooltip says 1 completed NaN/3.5GB (maybe it helps).

The data seems not to be pushed, because on the LFS storage only a few bytes (assumably meta data) of allocated space is shown.

This behaviour is completly reproducable. Spend two days on trying to solve it somehow, but failed.

The behaviour is reproducable on Windows 11 Pro as well as on Windows 10 Pro.

The usage of LFS with smaller files (tested with 2MB) worked without any problems.

### Release version

3.4.3 (x64)

### Operating system

Windows 10 Pro / Win 11 Pro

### Steps to reproduce the behavior

1. Create a new Repo
2. clone it with Github Desktop
3. Command shell (out of github desktop): git lfs install 
4. Add a big file (mine was WinData/image.wim) to the filesystem
5. git track WinData/image.wim
6. Commit in Github desktop
7. Push in Github desktop
=> Hanging up in circling the LFS upload

### Log files

[2024-08-12.desktop.production.log](https://github.com/user-attachments/files/16600574/2024-08-12.desktop.production.log)
[2024-08-13.desktop.production.log](https://github.com/user-attachments/files/16600575/2024-08-13.desktop.production.log)
[2024-08-07.desktop.production.log](https://github.com/user-attachments/files/16600576/2024-08-07.desktop.production.log)

### Screenshots

![Screenshot 2024-08-13 155456](https://github.com/user-attachments/assets/2b2e33fc-9b45-4f2d-80f6-e7a8b96d6d0d)

**Comment by steveward** [comment]
Thanks for the detailed report @megerlms, I'll take a look and see if I can reproduce this on my Windows machine.

**Comment by steveward** [comment]
I tested this out with a 1.3GB binary file and was unable to reproduce the issue, but I am on a gigabit connection so the file uploaded fast. How fast is your internet connection?

There is a config option for LFS to help with timeouts:

`git config lfs.activitytimeout 60`

This config sets the maximum time in seconds that the HTTP client will wait for the next TCP read or write. Let me know if that helps.

Do you encounter the same issue pushing via the command line?

**Comment by megerlms** [comment]
Hi Steve!
Actually I do have only an upload rate of about 10MBit/s.

I already tried to set the config you proposed (found on stackoverflow) with no effect. I even pushed up this setting to 3600 but it didn't help.

I will try to push it on command line.

**Comment by steveward** [comment]
Is your LFS storage a separate server outside of GitHub? There was a report of that causing processes to be created: https://github.com/desktop/desktop/issues/18671.
