### ISSUE TITLE
Light

### ISSUE THREAD

**Issue by Daniellasss** [desktop/desktop#19105]
### The problem

I am trying to run a bot in Python, but I get the error 'NameError: name 'TOKEN' is not defined'.

### Release version

YR

### Operating system

Windows 11 Pro

### Steps to reproduce the behavior

1.Installed the 'python-telegram-bot' library.
2.Wrote the code for the bot.
3.Ran the script and got an errors.

### Log files

The bot should run without errors.
I get the error NameError: name 'TOKEN' is not defined.

### Additional context

from telegram import Update
from telegram.ext import Updater, CommandHandler, MessageHandler, filters, CallbackContext

#Функція для стартової команди
def start(update: Update, context: CallbackContext) -> None:
    update.message.reply_text('Привіт! Я автовідповідач. Напишіть мені щось!')

#Функція автовідповідач
def auto_reply(update: Update, context: CallbackContext) -> None:
    user_message = update.message.text #Отримуємо текст користувача
    response = f'Ви написали: {user_message}' #Формуємо відповідь
    update.message.reply_text(response) #Відповідаємо користувачу

def main():
    #Вставте свій токен тут
    TOKEN = 'Your TOKEN'

    updater = ('TOKEN')

    #Отримуємо диспечер для обробки повідомлень
    dispatcher = updater.dispatcher

#Додаємо обробники
dispatcher.add_handler(CommandHandler("start", start))
dispatcher.add_handler(MessageHandler(filters.text & ~filters.command, auto_reply))

#Запускаємо бота
updater.start_polling()

#Залишаємо бота працювати до зупинки
updater.idle()

if __name__ == '__main__':
    main()

**Comment by steveward** [comment]
@Daniellasss this issue tracker is fro GitHub Desktop, it looks like you are seeking support for a different project hosted on GitHub.
