### ISSUE TITLE
Gitmoji commit presets

### ISSUE THREAD

**Issue by YoavTC** [desktop/desktop#19104]
### The feature request

Add [Gitmoji](https://gitmoji.dev/) preset support for commit types. Allow/Force(?) users to select a commit preset along with the summery.
## From This:
> Lazyload home screen images.
 Fix  onClick event handler
 Bump version 1.2.0
 (components): Transform classes to hooks
 Add analytics to the dashboard
 Support Japanese language
 (account): Improve modals a11y
## To This:
>⚡️ Lazyload home screen images.
🐛 Fix onClick event handler
🔖 Bump version 1.2.0
♻️ (components): Transform classes to hooks
📈 Add analytics to the dashboard
🌐 Support Japanese language
♿️ (account): Improve modals a11y

### Proposed solution

# My Suggestion Mockup:
![2024-08-13 23-37-19_2](https://github.com/user-attachments/assets/2baaa943-b894-4db7-a178-da8416cefdd9)

**Comment by steveward** [comment]
Thanks for the issue @YoavTC.  This is an interesting idea, but we would likely implement something like commit templates (https://github.com/desktop/desktop/issues/17113) over this. If we get more feedback about this we can reopen and revisit, but I'm going to close this out for the time being.
