### ISSUE TITLE
Timeout and error when fetching from remote git repository

### ISSUE THREAD

**Issue by krstan4o** [desktop/desktop#19109]
### The problem

Fetching from repository often is having long loading and a timeout with error message with stack trace

### Release version

Version 3.4.3 (x64)

### Operating system

Microsoft Windows 11 Pro

### Steps to reproduce the behavior

Click the Fetch button

### Log files

# Popup with Close button: 
Updating 13684117..6e78087e
Fast-forward
 src/components/ordering/preview/contract.tsx | 6 +++---
 src/styles/dev.scss                          | 4 +++-
 2 files changed, 6 insertions(+), 4 deletions(-)
      0 [main] sh (27556) C:\Users\krastanp\AppData\Local\GitHubDesktop\app-3.4.3\resources\app\git\usr\bin\sh.exe: *** fatal error - add_item ("\??\C:\Users\krastanp\AppData\Local\GitHubDesktop\app-3.4.3\resources\app\git", "/", ...) failed, errno 1
Stack trace:
Frame         Function      Args
0007FFFFABC0  00021005FE8E (000210288F3A, 00021026AB81, 000000008000, 0007FFFF8B30) msys-2.0.dll+0x1FE8E
0007FFFFABC0  0002100467F9 (0007FFFFAC5A, 0007FFFFABC0, 000000000000, 000000000000) msys-2.0.dll+0x67F9
0007FFFFABC0  000210046832 (0007FFFF9BC0, 000000000001, 000000008000, 000000000001) msys-2.0.dll+0x6832
0007FFFFABC0  00021007CDDA (000700000000, 000000000000, 0007FFFFCC18, 000000000000) msys-2.0.dll+0x3CDDA
1DAEEA49EA7B2BC  00021017E765 (000000000000, 000000000000, 00000000017C, 000000000000) msys-2.0.dll+0x13E765
0007FFFFCD30  000210046E60 (000000000000, 000000000000, 000000000000, 000000000000) msys-2.0.dll+0x6E60
000000000000  000210045AC3 (000000000000, 000000000000, 000000000000, 000000000000) msys-2.0.dll+0x5AC3
0007FFFFFFF0  000210045B74 (000000000000, 000000000000, 000000000000, 000000000000) msys-2.0.dll+0x5B74
End of stack trace
Loaded modules:
000100400000 sh.exe
7FFABCA10000 ntdll.dll
7FFABB9D0000 KERNEL32.DLL
7FFAB9FE0000 KERNELBASE.dll
7FFABAA40000 USER32.dll
7FFABA4E0000 win32u.dll
000210040000 msys-2.0.dll
7FFABB390000 GDI32.dll
7FFABA390000 gdi32full.dll
7FFABA6A0000 msvcp_win.dll
7FFABA510000 ucrtbase.dll
7FFABC3F0000 advapi32.dll
7FFABA7D0000 msvcrt.dll
7FFABA8E0000 sechost.dll
7FFABA4B0000 bcrypt.dll
7FFABB1E0000 RPCRT4.dll
7FFAB9470000 CRYPTBASE.DLL
7FFAB9F60000 bcryptPrimitives.dll
7FFABC4B0000 IMM32.DLL

**Comment by steveward** [comment]
Thanks for the report @krstan4o. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by krstan4o** [comment]
Done: line 170

[2024-08-14.desktop.production.log](https://github.com/user-attachments/files/16630442/2024-08-14.desktop.production.log)

**Comment by CietyGoblin** [comment]
792354

**Comment by sergiou87** [comment]
Do you always get that stack trace after a timeout? Does it happen with every repository or only with a specific one?

**Comment by krstan4o** [comment]
> Do you always get that stack trace after a timeout? Does it happen with every repository or only with a specific one?

Yes

**Comment by sergiou87** [comment]
@krstan4o could you try the same repositories and everything else from a different machine? (Even a Virtual Machine could work for this test).

Just trying to pinpoint where the problem lies… if it's related to your repos, to your machine, network… Thank you!

**Comment by krstan4o** [comment]
@sergiou87 i think its because of my machine / networking => i have VPN and when this VPN goes down seems like git is not able to respond
