### ISSUE TITLE
Can't sign in "unable to fetch authenticated user"

### ISSUE THREAD

**Issue by chocolate-byte** [desktop/desktop#19113]
### The problem

[2024-08-16.desktop.production.log](https://github.com/user-attachments/files/16634696/2024-08-16.desktop.production.log)

Using win10 chrome,edge. The redirect works but log in failed.
May I know what's blocking me from logging in on github desktop?

### Release version

3.4.3

### Operating system

win10

**Comment by sergiou87** [comment]
Are you running Kaspersky Internet Security? That was the cause of this issue for [another user](https://github.com/desktop/desktop/issues/16901#issuecomment-1597068643) of GitHub Desktop who was running Kaspersky. 

If you're not running that version of Kaspersky I would recommend looking at this documentation to see if you can prevent GitHub Desktop from being scanned:

https://support.kaspersky.com/KESWin/11/en-US/165718.htm
