### ISSUE TITLE
github desktop not installing !

### ISSUE THREAD

**Issue by Bader975** [desktop/desktop#19112]
### The problem

i can't install github desktop

### Release version

i can't see it

### Operating system

Apple M3 Pro macOS sonnoma 14.6.1 (23G93)

### Screenshots

<img width="854" alt="Screenshot 1446-02-12 at 10 39 29 AM" src="https://github.com/user-attachments/assets/a69804c0-3bad-419a-be5a-ce097f64bcd7">

<img width="1027" alt="Screenshot 1446-02-12 at 10 37 30 AM" src="https://github.com/user-attachments/assets/b000684f-6697-49d6-a2d3-9c1a7ec8fad8">

**Comment by sergiou87** [comment]
Thanks for the issue @Bader975 To get some more information about why the installation is failing it would be helpful if you could send over the log file that the Squirrel installer generates.

You should be able to find the log file here:

`~/Library/Caches/com.github.GitHubClient.ShipIt`

Please send that over as an attachment.

**Comment by Daniellasss** [comment]
thank you @Bader975 Try uninstalling and installing again, it might help

**Comment by Bader975** [comment]
> `~/Library/Caches/com.github.GitHubClient.ShipIt`

it didn't work i tried it couple times

**Comment by Bader975** [comment]
> thank you @Bader975 Try uninstalling and installing again, it might help

it didn't work i tried it couple times

**Comment by Bader975** [comment]
> Thanks for the issue @Bader975 To get some more information about why the installation is failing it would be helpful if you could send over the log file that the Squirrel installer generates.
> 
> You should be able to find the log file here:
> 
> `~/Library/Caches/com.github.GitHubClient.ShipIt`
> 
> Please send that over as an attachment.

i did't find the log file

**Comment by Daniellasss** [comment]
> > Спасибо@Bader975Попробуйте удалить и установить снова, это может помочь.
> 
> это не сработало, я пробовал пару раз
check if it is installed correctly, you need to enter the command in the terminal git --version, if it doesn't help, try downloading from the official website

**Comment by Bader975** [comment]
It worked! I was installing the wrong version, which was intended for Intel Macs. However, I have an M3 Mac, so I needed to download the Apple Silicon version.
The version information wasn't very clear to me.

Thank you! @sergiou87  I appreciate your time and effort.

**Comment by Bader975** [comment]
> > > Спасибо@Bader975Попробуйте удалить и установить снова, это может помочь.
> > 
> > 
> > это не сработало, я пробовал пару раз
> > check if it is installed correctly, you need to enter the command in the terminal git --version, if it doesn't help, try downloading from the official website

@Daniellasss thank you , it worked for me
