### ISSUE TITLE
Github desktop doesn't update after removing repo from github

### ISSUE THREAD

**Issue by ArianN8610** [desktop/desktop#19121]
### The problem

I mistakenly first pushed a sub-branch to github via github desktop and that branch became my default branch. After that, I completely deleted the repo from github, but github desktop still shows that my repo is on github and the default branch also shows wrong. Can I make the github desktop and everything go back to before I uploaded my repo to github and everything is fine. I have important commits and files and I can't reset commit or create a new repo from scratch.

### Release version

3.4.3 (x64)

### Operating system

Windows 11

### Screenshots

![image](https://github.com/user-attachments/assets/5582cf97-4e31-406e-80d1-7ebe09d7a9e8)
![image](https://github.com/user-attachments/assets/63508c27-c8cc-46fa-ab99-a814368e4fc0)

**Comment by tidy-dev** [comment]
@ArianN8610 I would suggest:

1. Republishing your repository
2. Making sure the branch you want as your default is published/pushed.
3. Go to your repository settings and switch your Default branch.
4. Fetch in GitHub Desktop.

lmk if that helps.
