### ISSUE TITLE
 G++ Compiler problem

### ISSUE THREAD

**Issue by Muhammed-Husam-ElDeen** [desktop/desktop#19122]
I downloaded the (gbd,gcc, and g++) from msys2 and wanted to run the code shown in the photo
using the (G++ Compiler) I wanted to run the file and this popped up
(the prelaunchtask 'c/c++: gcc.exe build active file'terminated with exit code -1)
I installed the (code runner extension) and was able to run the code but I am still concerned about the earlier error

![Screenshot 2024-08-17 230905](https://github.com/user-attachments/assets/9431cb92-319b-4bd8-a249-613e17d22e56)

**Comment by sergiou87** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
