### ISSUE TITLE
Feature Request: Support Multiple Stashes per Branch

### ISSUE THREAD

**Issue by DavidHJong** [desktop/desktop#19134]
#### Current Behavior
GitHub Desktop currently allows only one stash per branch. Creating a new stash overwrites the previous one, limiting flexibility in managing work-in-progress changes.

#### Proposed Change
Implement support for multiple stashes per branch, similar to Git's native functionality.

#### Benefits
1. Improved workflow management
2. Greater flexibility in handling multiple sets of changes
3. Reduced risk of losing work

### Proposed solution

1. Add a "Stash List" view in the GitHub Desktop UI
2. Modify the stash creation process to allow naming/describing each stash
3. Implement stash application, deletion, and management features

#### Additional Considerations
- Sync multi-stash functionality with GitHub.com for consistency across platforms
- Provide clear documentation on how to use and manage multiple stashes

**Comment by tidy-dev** [comment]
@DavidHJong Thank you for the feedback. I have added it to https://github.com/desktop/desktop/issues/12699. Feel free to add a thumbs up to that issue to support it.
