### ISSUE TITLE
The remote disconnected. Check your Internet connection and try again.

### ISSUE THREAD

**Issue by eliasrafaael** [desktop/desktop#19133]
### The problem

quando tento fazer um push esta a vir The remote disconnected. Check your Internet connection and try again. por favor resolvam estiu tentando colocar um projecto

### Release version

3.4.3

### Operating system

windows 10

### Steps to reproduce the behavior

![Uploading Captura de ecrã 2024-08-17 103434.jpg…]()

### Screenshots

![Uploading Captura de ecrã 2024-08-17 103434.jpg…]()

**Comment by tidy-dev** [comment]
@eliasrafaael Thank you for reaching out! Could you please upload the log file for this day?
