### ISSUE TITLE
sugestão- Adicionar a convenção de commits no Guia de Contribuição

### ISSUE THREAD

**Issue by 00Fabi** [desktop/desktop#19131]
### The feature request

Não

### Proposed solution

Adicionar informações referentes a padronização das mensagens dos commits no Guia de Contribuição .

### Additional context

Inserir uma tabela demostrando os tipos de commits e uma descrição a respeito do seu uso.

**Comment by 00Fabi** [comment]
Não há

**Comment by tidy-dev** [comment]
@00Fabi Thank you for reaching out! Unfortunately, no one on our team speaks Portuguese (what google translate identifies the above text as). The translation does not seem to reflect information about GitHub Desktop. Thus, I am going to close this, please respond back  if you can provide more detail.


Google translation:

Title: 
> suggestion- Add the commit convention in the Contribution Guide

The feature request:
> No

Proposed Solution:
>Add information regarding the standardization of commit messages in the Contribution Guide.

Additional context
> Insert a table showing the types of commits and a description of their use.
