### ISSUE TITLE
Can't create a local repo

### ISSUE THREAD

**Issue by gwilku** [desktop/desktop#19137]
### The problem

I have a folder, which itself is a github repo clone (let's call it BaseGame). It has a directory (BaseGame/Mods) included in .gitignore.
I want to create a repository for a specific mod in the Mods folder (i.e. BaseGame/Mods/Sample).

GitHub will not let me create a new repo, telling me to add an existing one instead, but when I select the BaseGame/Mods/Sample path, the directory is completely ignored, and Github adds the Origin repo instead.

### Release version

3.4.3

### Operating system

Windows 11

### Steps to reproduce the behavior

Follow the description.

**Comment by tidy-dev** [comment]
@gwilku Thanks for reaching out! I tried to reproduce and I somewhat could. 

1. Created a repository called "Test"
2. Created a folder called "groups"
3. Went to GitHubDesktop, added folder of "groups" to gitignore and committed.
4. Added a folder called "group1" to the "groups" directory and added a Readme.md to it.
5. Returned to GitHubDesktop. (GitHub desktop correctly did not show this in the changes list)
6. Hit "Create new Repository."
7. Selected the path of {location/of/repository/}/groups/group1
8. Saw the error of "This directory appears to be a Git repository. Would you like to add this repository?".
9. Added a "Name" of "group1" (The error went away)
10. Hit Create Repository.


I believe you have found a bug in our git directory error detection, but you can bypass it. 

Other notes: You might appreciate [submodules](https://gist.github.com/gitaarik/8735255)?

**Comment by gwilku** [comment]
Hi,

Thanks for looking into it. I;m afraid though, that the result of your steps will be a repo in ../groups/group1/group1

At least that's what happens in my case, although I have no readme.md file, not sure if that makes a difference.

Will look into submodules topic as well.

**Comment by tidy-dev** [comment]
> Thanks for looking into it. I;m afraid though, that the result of your steps will be a repo in ../groups/group1/group1

Ah! I always get foiled by that. But, the same thing should work with one directory step up.

**Comment by tidy-dev** [comment]
Ah. I see. Also see if I try to point it at a directory that already exists it, it does block with that error.

**Comment by gwilku** [comment]
Yes, that's the thing. So if I give the path location/groups/ and specify the name group1, GitHub only allows to Add a repository, but, the bug is:
it doesn't add location/groups/group1, but just the location/ itself

**Comment by gwilku** [comment]
a workaround is to rename an existing groups1 directory, create a new repo called group1, and then copy the content over, but that's just a workaround.

**Comment by tidy-dev** [comment]
Yes. The copying over works. Also, if you have Git installed outside of Desktop, you can navigate to the directory in the command line and use the command `git init`. Then, add that repository to Desktop.

**Comment by gwilku** [comment]
That's another way to tackle it, but I don't have git. Kind of the whole point of GitHub desktop was not to need git ;)
