### ISSUE TITLE
Make "Open In {IDE}" button with pulldown

### ISSUE THREAD

**Issue by EvgenyAlterman** [desktop/desktop#19144]
### The feature request

I use at least 2 IDEs on daily basis and being able to use Open in button with pulldown may be very handy.

### Proposed solution

Make `Open in {IDE}` button with a small chevron on like star and fork buttons on github site
where user could directly open other than default IDE

Probably same for terminals will be very hadny
![image](https://github.com/user-attachments/assets/8625d5c3-c08f-41a5-b3f4-db0baa9f0500)

**Comment by tidy-dev** [comment]
@EvgenyAlterman Thank you for reaching out! This is being tracked in https://github.com/desktop/desktop/issues/18737. I have copied your feedback there, but another helpful thing is to thumbs up tracking issues you want to show support for.
