### ISSUE TITLE
[Feature Request] Choose account for each repo

### ISSUE THREAD

**Issue by angeousta** [desktop/desktop#19157]
### The feature request

It would be nice to be able to set git credentials (user, email, psw/token) for each repo.

Very useful to people working on different projects with different github users

### Proposed solution

A new setting for each repo for choosing github account associated to that repo

**Comment by steveward** [comment]
@angeousta thanks for the issue. We're tracking support for multiple accounts in https://github.com/desktop/desktop/issues/3707, I'll add this feedback there and I'd recommend subscribing to that issue.
