### ISSUE TITLE
Add preference to always show date and time

### ISSUE THREAD

**Issue by latenitefilms** [desktop/desktop#19154]
### The feature request

Currently GitHub Desktop will helpfully show "2 months ago" for example, and if you hover your mouse over you'll see the full date. However, there's cases where I always want to see the full date in the user interface. Hovering my mouse over the dates just slows things down.

### Proposed solution

Could you please add an option to the preferences to "always show full date/time"?

### Additional context

<img width="335" alt="image" src="https://github.com/user-attachments/assets/5a2a4cdd-aa1e-4b91-9efd-5225f862edcd">
<img width="456" alt="image" src="https://github.com/user-attachments/assets/65bbf768-8a0c-4c96-b2dd-bc83f88205a1">

**Comment by steveward** [comment]
Thanks for the issue @latenitefilms. This is the behavior that mirrors github.com, but we are tracking feedback about this in https://github.com/desktop/desktop/issues/14611. I'll drop your request into that issue.

**Comment by antonydandrea** [comment]
There is no Universe where "2 months ago" is helpful.
The biggest issue is that you can't hover on MOBILE! Whats so hard to understand about this, why is there so much pushback for a simple thing.
