### ISSUE TITLE
Cannot spawn the ask-pass-trampoline

### ISSUE THREAD

**Issue by richred** [desktop/desktop#1916]
Hi
### Description

When i try send my project on GitHub i get error:

error: cannot spawn C:\Users\Admin\AppData\Local\GitHubDesktop\app-0.5.9\resources\app\static\ask-pass-trampoline.bat: No such file or directory
fatal: could not read Username for 'https://github.com': terminal prompts disabled

![error](https://user-images.githubusercontent.com/26653363/26846640-07dcbf8e-4b03-11e7-977e-bd58b762f099.png)

### Version

**GitHub Desktop version:** 0.5.9

**OS version:** Windows Version 10.0.15063

### Steps to Reproduce

1. Create repository
![screenshot_2](https://user-images.githubusercontent.com/26653363/26846131-7861ca30-4b01-11e7-88c4-8915e55a8e29.png)
2. Add the first commit
![screenshot_3](https://user-images.githubusercontent.com/26653363/26846534-9b601f86-4b02-11e7-9268-e2cc5ef88fc7.png)
3. Trying to send my file on GitHub
![screenshot_4](https://user-images.githubusercontent.com/26653363/26846632-036e11fa-4b03-11e7-987e-ff5dbc1dfd34.png)
4. Click Publish repository and get an error
![error](https://user-images.githubusercontent.com/26653363/26846740-6027aac8-4b03-11e7-93e1-03ffc07a7bfd.png)

**Expected behaviour:** Wanted to see my index.html on GitHub repository "richred/richred.github.io"

**Actual behaviour:** i get error

**Reproduces how often:** all time

1) GIF. Error
![bandicam-2017-06-06-22-10-48-544](https://user-images.githubusercontent.com/26653363/26847764-d93c6fd6-4b06-11e7-8943-244b572407df.gif)

2) GIF. The repository is created on GitHub
![bandicam-2017-06-06-22-13-40-592](https://user-images.githubusercontent.com/26653363/26847767-dbd954d4-4b06-11e7-9587-ea43004ea387.gif)

Thank for help!

**Comment by shiftkey** [comment]
We had #1873 reported earlier which feels similar, but you've provided more detail here for us to work with so I'm going to close that one in favour of this.

So there's two things to distinguish here in the "Publish Repository" flow:

 - creating the repository using the GItHub API - this seems to have succeeded
 - publishing the commits on your current branch - this is the error you're seeing

The latter requires us to set up a `GIT_ASKPASS` environment which passes your credentials to git.exe as part of the `git push`. I'm not entirely sure why this is happening, but that's some context to help start things off!

**Comment by richred** [comment]
I will wait for update that solves the problem. Thanks!

**Comment by joshaber** [comment]
@richred Can you check to see if `C:\Users\Admin\AppData\Local\GitHubDesktop\app-0.5.9\resources\app\static\ask-pass-trampoline.bat` exists on your machine?

I almost wonder if this is a Squirrel problem. If that file doesn't exist, it sure sounds like installation failed.

**Comment by richred** [comment]
@joshaber I've checked this before. I reinstalled the program several times

**Comment by richred** [comment]
@joshaber, @shiftkey After a while, I had problems with the nodejs, and I decided to reinstall Windows. And now  GitHub Desktop works.
Thank you very much for participating in solving the problem!

**Comment by joshaber** [comment]
Great, thanks for letting us know!

**Comment by cjingcheng** [comment]
what do i have to do,when i face that 

![bug](https://user-images.githubusercontent.com/46876640/59030173-d0ba8c00-8892-11e9-884f-f73979aea466.png)

**Comment by steveward** [comment]
@cjingcheng we have seen a few causes of this error. One common one has been the modification of the following registry entry:

`HKEY_CURRENT_USER\Software\Microsoft\Command Processor\autorun`

Could you check to see if this registry entry has possibly been modified on your machine?

We've also seen special characters in Windows user account names cause this, but that does not look like it would be an issue in this instance. It would also be helpful to know if you are running any antivirus/security software that could be interfering with GitHub Desktop.

**Comment by cjingcheng** [comment]
I checked my registry. The picture is below. I looked at the information on the Internet and didn't find that I had changed it.
Is there any possibility of other wrong reasons?
Thank you very much for your help.




------------------ 原始邮件 ------------------
发件人: "Steve Ward"<notifications@github.com>;
发送时间: 2019年6月7日(星期五) 凌晨2:16
收件人: "desktop/desktop"<desktop@noreply.github.com>;
抄送: "who care"<2719121279@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [desktop/desktop] Cannot spawn the ask-pass-trampoline (#1916)




@cjingcheng we have seen a few causes of this error. One common one has been the modification of the following registry entry:
 
HKEY_CURRENT_USER\Software\Microsoft\Command Processor\autorun
 
Could you check to see if this registry entry has possibly been modified on your machine?
 
We've also seen special characters in Windows user account names cause this, but that does not look like it would be an issue in this instance. It would also be helpful to know if you are running any antivirus/security software that could be interfering with GitHub Desktop.

**Comment by AnokhinaM** [comment]
Hello, I have the same issue.
Have you solved it?
Do you need any screenshots or any other information?

I've reinstalled GitHub several times, now I have versions installed: 2.1.0, 2.0.4, 2.03 - all of them gives the error. 

In my registry I don't have such registry entry at all:
HKEY_CURRENT_USER\Software\Microsoft\Command Processor\autorun

**Comment by AnokhinaM** [comment]
> Hello, I have the same issue.
> Have you solved it?
> Do you need any screenshots or any other information?
> 
> I've reinstalled GitHub several times, now I have versions installed: 2.1.0, 2.0.4, 2.03 - all of them gives the error.
> 
> In my registry I don't have such registry entry at all:
> HKEY_CURRENT_USER\Software\Microsoft\Command Processor\autorun

![image](https://user-images.githubusercontent.com/39983318/61851086-964a9400-aebe-11e9-8500-783246c1dd9e.png)

**Comment by cjingcheng** [comment]
No, I didn't solve the problem.
Because I can't find the registry prompted by the staff in my computer.

Maybe this is some unknown bug.


------------------ 原始邮件 ------------------
发件人: "AnokhinaM"<notifications@github.com>;
发送时间: 2019年7月25日(星期四) 下午2:28
收件人: "desktop/desktop"<desktop@noreply.github.com>;
抄送: "who care"<2719121279@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [desktop/desktop] Cannot spawn the ask-pass-trampoline (#1916)




Hello, I have the same issue.
 Have you solved it?
 Do you need any screenshots or any other information?
 
I've reinstalled GitHub several times, now I have versions installed: 2.1.0, 2.0.4, 2.03 - all of them gives the error.
 
In my registry I don't have such registry entry at all:
 HKEY_CURRENT_USER\Software\Microsoft\Command Processor\autorun

**Comment by steveward** [comment]
@AnokhinaM and @cjingcheng the registry entry can also be modified in the following location:

`HKEY_LOCAL_MACHINE \ Software \ Microsoft \ Command Processor \ AutoRun`

I would check there as well to see if that has been modified.

**Comment by markc-dsoft** [comment]
What should the value of the AutoRun entry be?

**Comment by steveward** [comment]
@markc-dsoft I'd recommend leaving it empty/deleting it -- see [this blog](https://devblogs.microsoft.com/oldnewthing/20071121-00/?p=24433) for some interesting insights into how it can affect your system.

**Comment by markc-dsoft** [comment]
@steveward - Do we have a better solution here than "reinstall Windows"?  My error is slightly different in that it says "**No error**" after ask-pass-trampoline.bat instead of "No such file or directory".  I've uninstalled and reinstalled Github Desktop, rolled back settings, gone back to all available System Restore Points, etc.

**Comment by markc-dsoft** [comment]
> > @richred Can you check to see if `C:\Users\Admin\AppData\Local\GitHubDesktop\app-0.5.9\resources\app\static\ask-pass-trampoline.bat` exists on your machine?
> > I almost wonder if this is a Squirrel problem. If that file doesn't exist, it sure sounds like installation failed.

@Sameedahmad replied: 
> My file doesnot exist what should i do i have re-installed it already;

If you're not using version 0.5.9, substitute your actual version # in the path when you look for the ask-pass-trampoline.bat file

**Comment by markc-dsoft** [comment]
Here's a solution:  put the username and password/token in the URL

https://name:password@github.com/username/repo.git

**Comment by Coloured-glaze** [comment]
I re-install him and the problem was solved.
