### ISSUE TITLE
Change Language!!!

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#19168]
### The feature request

I wish I could choose the language in the settings. I can't read English.

### Proposed solution

I wish I could choose the language in the settings. I can't read English.

**Comment by samugarinoko** [comment]
> ### 機能リクエスト
> 設定で言語を選べたらいいのにと思います。英語が読めません。
> 
> ### 提案された解決策
> 設定で言語を選べたらいいのにと思います。英語が読めません。
> 
> ### 追加のコンテキスト
> _応答なし_

**Comment by ghost** [comment]
Implementing a language change could make a lot of people happy. I would be happy too. So, GitHub users, if you see this, please implement it.

**Comment by ghost** [comment]
*This is using Google Translate
