### ISSUE TITLE
Cannot open any file at all 

### ISSUE THREAD

**Issue by tommiecas** [desktop/desktop#19167]
### The problem

This started after Rider crashed, and I have no idea why or how it happened. Here's the error code: Error: spawn C:\Program Files\JetBrains\JetBrains Rider 2024.1.4\bin\rider64.exe EACCES
    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)
    at __node_internal_errnoException (node:internal/errors:690:12)
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Version: 3.4.3
OS: Windows 10.0.22631

### Release version

Version 3.4.3 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

Open GitHub Desktop.
Try to open my project in JetBrains Rider.
Get the error above.

### Log files

[2024-08-27.desktop.production.log](https://github.com/user-attachments/files/16759242/2024-08-27.desktop.production.log)
[2024-08-26.desktop.production.log](https://github.com/user-attachments/files/16759246/2024-08-26.desktop.production.log)

### Screenshots

<img width="457" alt="github" src="https://github.com/user-attachments/assets/b0118475-bc9a-4f03-ae09-8237fa9085cc">

**Comment by tommiecas** [comment]
I've even tried uninstalling and reinstalling GitHub Desktop, and it still comes up with an error.

**Comment by steveward** [comment]
@tommiecas have you tried a restart of your machine? We've had a few reports of these EACCESS errors and unfortunately it seems they can be caused by a variety of things.

**Comment by tommiecas** [comment]
Yeah, I've restarted a few times. I've even uninstalled and re-installed
the program. And it happens every time. I can't open it at all....

**Comment by sergiou87** [comment]
Does the file exist at that exact path?

**Comment by tommiecas** [comment]
Yes, it does. That hasn't changed.

**Comment by tommiecas** [comment]
If I start a completely new project, it still encounters the error.

**Comment by steveward** [comment]
Have you tried reinstalling Jetbrains Rider?

**Comment by steveward** [comment]
@tommiecas can you try reinstalling Jetbrains Rider like I mentioned above? It may also be worth trying to use JetBrains Toolbox, as some users have worked around various issues by using that.

**Comment by steveward** [comment]
Closing as stale -- @tommiecas if you're still experiencing this let us know.
