### ISSUE TITLE
After push in RepoA i'm suddenly in RepoB

### ISSUE THREAD

**Issue by mscrocdile** [desktop/desktop#19172]
### The problem

I have multiple repositories. 
I select one repo and click commit.
Suddenly i'm in another repo.
It behaves still the same until i delete repo from github desktop and clone it again. Then it is ok.
This happens randomly so i don't know how to reproduce it.

### Release version

3.4.3

### Operating system

Windows 11

### Steps to reproduce the behavior

I dont know how to reproduce it. It happens appeoximately once a month, maybe more.

**Comment by steveward** [comment]
@mscrocdile thanks for the report. Unfortunately it's difficult for us to investigate something without reproducible steps or video/screenshots. If you can share that we can assist further, but until then I'm going to close this issue out as it isn't something we've heard other reports of.

You can share the log file from a day this happened and I can take a look to see if there is anything unusual. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
