### ISSUE TITLE
Adding a file to gitignore doesn't work

### ISSUE THREAD

**Issue by FlorianHimsl** [desktop/desktop#19176]
### The problem

I am trying to ignore this file called UserSettings\Layouts\default-2022.dwlt
Which should be pretty important to ignore for a unity project where different people have different layouts.

I looked it up and apparently the issue is that the file is being tracked so it can't be ignored. 
I use github desktop which doesn't come with a way to untrack files. Why wouldn't ignore just overwrite the tracking status of the files? Why wouldn't ignoring just work?

### Release version

Version 3.4.3 (x64)

### Operating system

Win 10

**Comment by steveward** [comment]
@FlorianHimsl thanks for the issue. This is correct -- you will need to run `git rm --cached <file>` to ignore files that are being tracked by Git already. 

We have an open issue around this in https://github.com/desktop/desktop/issues/2537. I'll reference this issue there.

**Comment by FlorianHimsl** [comment]
How do I "run" that code? I don't think github desktop has a console.
So does this mean it there will be an update eventually so that ignoring actually works how it should in the future?

**Comment by steveward** [comment]
You'll need to open the repository in the command line (from the file menu > `Repository` > `Open in command line`). You'll need to have Git installed as well if you haven't already installed it.

This is something we would like to fix, but I don't have a timeline for when that may happen.
