### ISSUE TITLE
Preference for tab size

### ISSUE THREAD

**Issue by Const-me** [desktop/desktop#19178]
### The Feature Request

When source code has tabs, github uses tab size = 8.
When there're many tabs, the diff view is borderline unusable, too wide.

Please conder doing at least one of the following:
1. Add a preference for tab size which defaults to 4 or maybe 3.
2. Apply the value you already have on your server at https://github.com/settings/appearance

### Proposed Solution

I fix locally by inserting the following first line in `resources\app\renderer.css`
```
* { tab-size: 4; }
```
However, every update reverts to the default.

**Comment by steveward** [comment]
Thanks for the issue. This setting is available in Settings/Preferences -> Appearance -> Diff -> Tab size. I hope that helps!

**Comment by CietyGoblin** [comment]
https://btcmall.cc/#/register?ic=979574
