### ISSUE TITLE
Github Desktop UI Unresponsive

### ISSUE THREAD

**Issue by sabrinatowne** [desktop/desktop#19175]
### The problem

I have tried to use Github Desktop and the UI is not loading correctly. I have uninstalled and reinstalled, restarted the computer, and this still seems to be an issue. I have attached a screenshot of the issue. It seems like when I interact with a repository, Github Desktop shows the file changes, but the UI is blurry. 

### Release version

Not Viewable

### Operating system

Sonoma 14.6

### Steps to reproduce the behavior

1. Open Github Desktop

### Log files

![Screenshot 2024-08-28 at 1 54 01 PM](https://github.com/user-attachments/assets/49fa9d34-f4d9-455c-b2e4-248237b5cd31)

**Comment by steveward** [comment]
Thanks for reporting this @sabrinatowne. Could you try running this command and then restarting GitHub Desktop to see if it helps with the issue?

`rm -rf ~/Library/Application\ Support/GitHub\ Desktop/IndexedDB`

Let me know if that helps.
