### ISSUE TITLE
Sidebar for Switching Repository

### ISSUE THREAD

**Issue by tianrui-qi** [desktop/desktop#19173]
### The feature request

I am a Mac user, and I keep all my code on GitHub. I have gotten used to using GitHub Desktop to manage all my local repositories: switch to repo in GitHub Desktop and use shortcuts to open repositories in VSCode or Finder. However, currently switching repositories is done through a dropdown menu, which requires an extra click every time I switch repositories, making it quite cumbersome.

### Proposed solution

Is it possible to make the dropdown menu for switching repositories similar to the “Show Sidebar” button in Safari on Mac? There could be two states:

1. Collapsed Sidebar: Switch repositories using a dropdown menu, which is the current method.

<img width="200" alt="Screenshot 2024-08-28 at 05 57 50" src="https://github.com/user-attachments/assets/a9b0673f-d0d4-4f30-94a0-1754ab52aba9">

2. Expanded Sidebar: All repositories are listed in a sidebar format, and this sidebar would be on the left of the (Change | History) sidebar.

<img width="200" alt="Screenshot 2024-08-28 at 05 58 17" src="https://github.com/user-attachments/assets/a1bd24b9-0841-4d1f-abe3-f279b1285767">

**Comment by steveward** [comment]
Thanks for the issue @tianrui-qi. Feedback about this is being tracked in https://github.com/desktop/desktop/issues/16175, so I'm going to close this out and add your comments there.

You can also use `Command+T` to quickly open the repository list and save yourself a mouse click. I hope that helps!
