### ISSUE TITLE
Infinity loadong 

### ISSUE THREAD

**Issue by Olsney** [desktop/desktop#19170]
### The problem

When i try to push repository even if its only gitignore files, first init, i get infinitive loading.
Please fix and help!
![image](https://github.com/user-attachments/assets/48dc7de5-df6b-4cc0-b60b-32d2ca707cc3)

### Release version

last

### Operating system

Windows 11

### Screenshots

![image](https://github.com/user-attachments/assets/6dcbd724-db5d-4461-8ffe-930edb65ee05)

**Comment by steveward** [comment]
Thanks for the report @Olsney. It looks like you are trying to push a fairly large amount of changes, which could be causing this.

Could you upload the log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Olsney** [comment]
It's always happens even when i try just to push initial commit :( 
![image](https://github.com/user-attachments/assets/00ec00d5-b881-419a-ab6b-53c0cb53e279)
[2024-08-28.desktop.production.log](https://github.com/user-attachments/files/16784374/2024-08-28.desktop.production.log)
[2024-08-27.desktop.production.log](https://github.com/user-attachments/files/16784375/2024-08-27.desktop.production.log)
It's a logs in this file from screenshot in this message, where absolutely same issue happen :( It's absolutely in all projects which i'm trying to push - i can't push and publish nothing :( 


> Thanks for the report @Olsney. It looks like you are trying to push a fairly large amount of changes, which could be causing this.
> 
> Could you upload the log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Olsney** [comment]
If it needs, it's logs from project in first screenshot in first message in topic "Transformations tasks" with many changes, i also uploading it in this message
![image](https://github.com/user-attachments/assets/b27fb312-b0c0-43e9-9ac4-28873ae630c5)
[2024-08-28.desktop.production.log](https://github.com/user-attachments/files/16784425/2024-08-28.desktop.production.log)
[2024-08-27.desktop.production.log](https://github.com/user-attachments/files/16784426/2024-08-27.desktop.production.log)

**Comment by steveward** [comment]
Thanks for sharing the log file. Here's the error I'm seeing:

```
2024-08-28T00:15:52.341Z - error: [ui] Trampoline client error
Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)
    at __node_internal_errnoException (node:internal/errors:690:12)
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
```

Are you running any antivirus or other security software on this machine that could be causing this?

**Comment by Olsney** [comment]
And 

> Thanks for sharing the log file. Here's the error I'm seeing:
> 
> ```
> 2024-08-28T00:15:52.341Z - error: [ui] Trampoline client error
> Error: read ECONNRESET
>     at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)
>     at __node_internal_errnoException (node:internal/errors:690:12)
>     at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
> ```
> 
> Are you running any antivirus or other security software on this machine that could be causing this?

I have Norton security and Avast antiviruses on PC, i can delete and check if something happens
But i deactiveted it yesterday, when i tried to fix this :( 
Wait a sec, i'm deleting and will write to you

**Comment by Olsney** [comment]
> Thanks for sharing the log file. Here's the error I'm seeing:
> 
> ```
> 2024-08-28T00:15:52.341Z - error: [ui] Trampoline client error
> Error: read ECONNRESET
>     at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)
>     at __node_internal_errnoException (node:internal/errors:690:12)
>     at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
> ```
> 
> Are you running any antivirus or other security software on this machine that could be causing this?

Omg, you was right - after deleting antiviruses I get possibility to push and publish repozitories.... Thank you so much!

**Comment by steveward** [comment]
I'm glad to hear that got things working. If you want to continue to use specific antivirus software they likely have an allow list that you could add GitHub Desktop to (here's [Norton for example](https://support.norton.com/sp/en/us/home/current/solutions/v3672136)).
