### ISSUE TITLE
Github desktop merge conflict when using terminal

### ISSUE THREAD

**Issue by danialtajalli** [desktop/desktop#19187]
### The problem

When issuing a request which has merge conflict using terminal, if terminal is terminated mid process, github desktop ignores file conflicts and behaves as if both changes are approved.

### Release version

3.3.14

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Create a file in github which has a conflict with local files
2. Pull using terminal
3. Kill the process when a merge message is needed
4. Pull using app (notice a pull is still necessary and pull button is still available)
5. Now, without any merge conflicts, a push is possible

**Comment by steveward** [comment]
Thanks for the report @danialtajalli, and apologies for the delay in getting back to you here. I tested this out and created a merge conflict:

![Image](https://github.com/user-attachments/assets/e2e6bc7d-3c58-4bbc-b2d1-06872918badf)

But GitHub Desktop showed me that a conflict needed to be resolved:

![Image](https://github.com/user-attachments/assets/d40ed4ff-17ef-4e21-ab7e-382ebdef9e34)

I'm guessing something differs in what I did in step 3. If you can provide more specific reproduction steps or screenshots that would be helpful, as so far I'm unable to reproduce this.
