### ISSUE TITLE
Error when pushing to remote

### ISSUE THREAD

**Issue by jianlianggao** [desktop/desktop#19180]
### The problem

Enumerating objects: 66, done.
Counting objects: 100% (66/66), done.
Delta compression using up to 8 threads
Compressing objects: 100% (49/49), done.
error: RPC failed; curl 56 LibreSSL SSL_read: LibreSSL/3.3.6: error:1404C3FC:SSL routines:ST_OK:sslv3 alert bad record mac, errno 0
fatal: the remote end hung up unexpectedly
Writing objects: 100% (49/49), 4.14 MiB | 8.63 MiB/s, done.
Total 49 (delta 17), reused 3 (delta 0), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

### Release version

2.6.0

### Operating system

MacOS Sonoma 14.5

**Comment by steveward** [comment]
Thanks for the issue @jianlianggao. Are you behind a proxy or firewall that could be interfering with your connection?

**Comment by jianlianggao** [comment]
Thanks for reply. I am not behind a proxy/firewall. I use my home wifi.

Best,
Jianliang

From: Steve Ward ***@***.***>
Date: Friday, 30 August 2024 at 14:59
To: desktop/desktop ***@***.***>
Cc: Gao, Jianliang ***@***.***>, Mention ***@***.***>
Subject: Re: [desktop/desktop] Error when pushing to remote (Issue #19180)
This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



Thanks for the issue @jianlianggao<https://github.com/jianlianggao>. Are you behind a proxy or firewall that could be interfering with your connection?

**Comment by steveward** [comment]
Do you see this same issue when pushing from the terminal? Unfortunately this is likely a network issue, and there isn't much we can do about those from our end.

You can run `openssl s_client -connect github.com:443` to test your connect from the command line as well. Let me know if that returns anything interesting.

**Comment by jianlianggao** [comment]
Hi Steve,

Thank you. I got the following message (very long return text, I enclose part of it) after running the line,

openssl s_client -connect github.com:443
Connecting to 20.26.156.215
CONNECTED(00000005)
depth=2 C=US, ST=New Jersey, L=Jersey City, O=The USERTRUST Network, CN=USERTrust ECC Certification Authority
verify return:1
depth=1 C=GB, ST=Greater Manchester, L=Salford, O=Sectigo Limited, CN=Sectigo ECC Domain Validation Secure Server CA
verify return:1
depth=0 CN=github.com
verify return:1
---
Certificate chain
 0 s:CN=github.com
   i:C=GB, ST=Greater Manchester, L=Salford, O=Sectigo Limited, CN=Sectigo ECC Domain Validation Secure Server CA
   a:PKEY: id-ecPublicKey, 256 (bit); sigalg: ecdsa-with-SHA256
   v:NotBefore: Mar  7 00:00:00 2024 GMT; NotAfter: Mar  7 23:59:59 2025 GMT
 1 s:C=GB, ST=Greater Manchester, L=Salford, O=Sectigo Limited, CN=Sectigo ECC Domain Validation Secure Server CA
   i:C=US, ST=New Jersey, L=Jersey City, O=The USERTRUST Network, CN=USERTrust ECC Certification Authority
   a:PKEY: id-ecPublicKey, 256 (bit); sigalg: ecdsa-with-SHA384
   v:NotBefore: Nov  2 00:00:00 2018 GMT; NotAfter: Dec 31 23:59:59 2030 GMT
 2 s:C=US, ST=New Jersey, L=Jersey City, O=The USERTRUST Network, CN=USERTrust ECC Certification Authority
   i:C=GB, ST=Greater Manchester, L=Salford, O=Comodo CA Limited, CN=AAA Certificate Services
   a:PKEY: id-ecPublicKey, 384 (bit); sigalg: RSA-SHA384
   v:NotBefore: Mar 12 00:00:00 2019 GMT; NotAfter: Dec 31 23:59:59 2028 GMT
---
Server certificate

Best,
Jianliang

From: Steve Ward ***@***.***>
Date: Friday, 30 August 2024 at 16:49
To: desktop/desktop ***@***.***>
Cc: Gao, Jianliang ***@***.***>, Mention ***@***.***>
Subject: Re: [desktop/desktop] Error when pushing to remote (Issue #19180)
This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



Do you see this same issue when pushing from the terminal? Unfortunately this is likely a network issue, and there isn't much we can do about those from our end.

You can run openssl s_client -connect github.com:443 to test your connect from the command line as well. Let me know if that returns anything interesting.

**Comment by steveward** [comment]
Just to confirm, are you trying to push to github.com or is this a repository hosted somewhere else?

**Comment by jianlianggao** [comment]
Hi Steve,

Thank you. I tried to push my local to the github.com/imperialcollegelondon . I found the problem now. I used an older version of GitHub desktop on my MacBook. I deleted my old one and downloaded a newer one. It works now.

Best regards,
J

From: Steve Ward ***@***.***>
Date: Wednesday, 11 September 2024 at 20:58
To: desktop/desktop ***@***.***>
Cc: Gao, Jianliang ***@***.***>, Mention ***@***.***>
Subject: Re: [desktop/desktop] Error when pushing to remote (Issue #19180)
This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



Just to confirm, are you trying to push to github.com or is this a repository hosted somewhere else?

**Comment by steveward** [comment]
Closing as reesolved.
