### ISSUE TITLE
Current branch selector fits branch name

### ISSUE THREAD

**Issue by catalinsminticiucglobant** [desktop/desktop#19191]
### The feature request

<img width="3120" alt="aint_this_stupid_anon" src="https://github.com/user-attachments/assets/8378b1e0-dd7c-46e4-8954-aa89d21c6dfc">

### Proposed solution

Current branch selector fits branch name

**Comment by steveward** [comment]
Thanks for the issue @catalinsminticiucglobant. This is being tracked in https://github.com/desktop/desktop/issues/4569, you can follow along there for updates.
