### ISSUE TITLE
Having different IDE's for different projects

### ISSUE THREAD

**Issue by aakash-acquia** [desktop/desktop#19209]
### The feature request

Many a times it happens is that JetBrains has a different IDE for every language and also sometimes people prefer different IDE's for different projects.

Now Github Desktop Selects one IDE and assumes thats valid for every project.

For Example:
I am in a Ruby Project and want to use RubyMine
<img width="1167" alt="image" src="https://github.com/user-attachments/assets/b1491557-5629-4844-bb6a-e6bebce192a2">
but Github Desktop shows Goland which i selected for other projects.

Now If i will change it to RubyMine it will be changed for all the projects.

### Proposed solution

We should have a option to select and save the IDE till project level.
And also a option to select default editor in case the selected IDE is missing from the system OR its a new project.
<img width="1167" alt="image" src="https://github.com/user-attachments/assets/a7503b19-f487-42ff-b936-e4328c9a0c5a">

**Comment by steveward** [comment]
Thanks for the feedback @aakash-acquia, this feature is being tracked in https://github.com/desktop/desktop/issues/12195 so you can follow along there for updates.

**Comment by aakash-acquia** [comment]
Thanks @steveward for  the update. really excited for this feature
