### ISSUE TITLE
Push origin -> Error: The remote disconnected. Check your Internet connection and try again.

### ISSUE THREAD

**Issue by Handfast** [desktop/desktop#19206]
### The problem

Title says almost everything. I have checked my connection and everything works as normal.

### Release version

Version 3.4.3 (x64)

### Operating system

MacOS Version 14.6.1 (23G93)

### Log files

[2024-09-05.desktop.production.log](https://github.com/user-attachments/files/16886582/2024-09-05.desktop.production.log)

**Comment by sergiou87** [comment]
Seems to happen on certain repositories. Take a look at https://github.com/desktop/desktop/issues/19174#issuecomment-2316004812 and let me know if that helped 🤞 

`git config --global http.postBuffer 157286400` worked for that user, so maybe… 🤞

**Comment by Handfast** [comment]
Thanks Sergio!
It did the trick, git config --global http.postBuffer 157286400.

It’s a repo that by now has a pretty long history and most of us have always run via Github Desktop (and Xcode), since we're not very much of terminal type users/developers. It would make sense if config needs to be updated over time, to also handle days with a bit of traffic jam.

=:·) Jens @ Headlong Development

**Comment by sergiou87** [comment]
I'm glad it worked! Enjoy! ✨
