### ISSUE TITLE
Repos will not switch in desktop app. 

### ISSUE THREAD

**Issue by HorizonServicesdc** [desktop/desktop#19210]
### The problem

I cannot switch my repos to upload any files. When I switch repo and upload anything it just switches back to the deleted repo. I have un installed and reinstalled, I cannot remove it from git, I have remade the same named repo and tried to delete it no nothing changes it.

https://github.com/user-attachments/assets/3ddad6b0-f334-4ce3-a27b-2a3055e72777

[2024-09-05.desktop.production.log](https://github.com/user-attachments/files/16894979/2024-09-05.desktop.production.log)

### Release version

3.4.4

### Operating system

Win 10

### Steps to reproduce the behavior

Shown in video below

https://github.com/user-attachments/assets/8a8a135f-bccc-41bb-a368-bad7f8c3314d

### Log files

[2024-09-05.desktop.production.log](https://github.com/user-attachments/files/16895027/2024-09-05.desktop.production.log)

### Screenshots

I provided a video

**Comment by HorizonServicesdc** [comment]
I like the app so much better please fix this

**Comment by steveward** [comment]
Thanks for the issue @HorizonServicesdc. This is likely due to caching. Did you rename the local folder, or rename the remote repository on GitHub? What does `Repository` > `Repository Settings` > `Remote` point to?
