### ISSUE TITLE
seemless and clean cursor integration or other editor integrations for windows

### ISSUE THREAD

**Issue by mratanusarkar** [desktop/desktop#19219]
### The feature request

I already saw #900 #19158 #18954 and similar issues and PRs,

but still, in my current GitHub Desktop version 3.4.3 (x64), I don't see cursor as an option in `File > Options > Integrations`

Ideally, would love to see a seamless cursor integration with GitHub Desktop, and the same extended to similar other editors.

### Proposed solution

The ideal solution would be, based on the selected `External editor` in `File > Options > Integrations`:

![image](https://github.com/user-attachments/assets/d16ecb21-b8d6-4b3f-9462-7a4c68e0fac8)

It would reflect everywhere, be it on right-clicking on the repo, in the home action prompts UI area, and every where else.
Eg: If I have integrated cursor, all places in the GUI will reflect the same.

![image](https://github.com/user-attachments/assets/16ea7f82-bda5-4275-a76f-23cff3ba9c4e)

### Additional context

It would be cool to see this integration which will enhance the end-user experience and help them easily integrate their favorite editor with GitHub Desktop.

**Comment by sergiou87** [comment]
This was already done in #19158, but only available in beta for now. You can try it out from https://desktop.github.com/beta
