### ISSUE TITLE
The new integrations feature removes quotes

### ISSUE THREAD

**Issue by ChiriVulpes** [desktop/desktop#19218]
### The problem

Trying to replicate what I had in #16980 with the new feature and I can't get it to work for multiple reasons.

This issue is regarding the "Arguments" input, which seems to strip out all quotes I put in. 

The command I have to run is `wt -p "Git Bash" -d %TARGET_PATH%`, and so theoretically I'd select the `wt` executable in the "Path" input and put `-p "Git Bash" -d %TARGET_PATH%` in the "Arguments" input, but on saving, this changes to `-p Git Bash -d %TARGET_PATH%`, which does not work at all

### Release version

3.4.4

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Put quotes around an argument in the "Arguments" input.

### Additional context

I am able to workaround this issue by making a custom `.bat` file in another folder that gives custom arguments to `wt`, but it's a little silly that I have to do that

**Comment by sergiou87** [comment]
Submitted a fix in #19224

Thanks for your report! 💖 🙇‍♂

**Comment by sergiou87** [comment]
@ChiriVulpes could you try out this test build with the fixes for the two issues you reported? I'll leave links for other platforms too in case someone else ran into this:

- Windows: https://desktop.githubusercontent.com/releases/3.4.5-test1-752de305/GitHubDesktopSetup-x64.exe
- macOS (Intel): https://desktop.githubusercontent.com/releases/3.4.5-test1-752de305/GitHubDesktop-x64.zip
- macOS (Apple silicon): https://desktop.githubusercontent.com/releases/3.4.5-test1-752de305/GitHubDesktop-arm64.zip

**Comment by sergiou87** [comment]
Fixed in the latest v3.4.5 that can be downloaded from https://desktop.github.com

Auto-updates will rollout progressively.

**Comment by ChiriVulpes** [comment]
Oh, sorry, I missed that you asked me to test it. I was just coming back to say that this issue in particular doesn't seem to be working in 3.4.5 either 😖 The input works now, but it still seems to be breaking down arguments by spaces when it actually runs the command. 

IE, I set up a .bat to intercept the command to print out the arguments it's getting passed, and with arguments `-p "Git Bash" -d %TARGET_PATH%`, I get:
```
"C:\git\ext\github-desktop\wt.bat"
-p
Git
Bash
-d
C:\git\node\chiri
```

**Comment by sergiou87** [comment]
@ChiriVulpes  It seems to work fine here:

What I entered:
![Image](https://github.com/user-attachments/assets/2285ff0e-67c9-484b-a2a7-70992fae9ecc)

The array of arguments:
![Image](https://github.com/user-attachments/assets/a837363f-0180-4541-968b-6c2289e2b8d8)

Could you replace `-p "Git Bash" -d %TARGET_PATH%` with something else, save it, and then enter `-p "Git Bash" -d %TARGET_PATH%` again? Maybe the migration from what you had to the new format broke it for you

**Comment by ChiriVulpes** [comment]
Hmm based on your screenshot it really seems like it shouldn't be splitting it into multiple arguments. I tried switching around the order of the arguments that I had to your order and it did actually happen to work with `wt.exe` — but switching back to my argument order makes it not work again.

## Doing a full test with the arguments in your order, ie `-d %TARGET_PATH% -p "Git Bash"`, with a breakpoint on the `return spawn` line:

### Printing them out individually using a `test.bat`:
```bat
echo %0>test.txt
echo %1>>test.txt
echo %2>>test.txt
echo %3>>test.txt
echo %4>>test.txt
echo %5>>test.txt
```

`args` at breakpoint:
![image](https://github.com/user-attachments/assets/c063c416-82de-408f-8a7d-1249b6d244d3)

I get the result:
```
"C:\git\ext\github-desktop\test.bat"
-d
C:\git\node\chiri
-p
Git
Bash
```

### Trying the same thing with `node.exe` as my Path and this `test.js` file as an input:
```js
require("fs").writeFileSync("test.txt", JSON.stringify(process.argv))
```

`args` at breakpoint:
![image](https://github.com/user-attachments/assets/15928b6e-3698-4a13-91ba-bb87260881fd)

I get:
```json
["C:\\Users\\Chiri\\AppData\\Roaming\\nvm\\v20.11.1\\node.exe","C:\\git\\ext\\github-desktop\\test.js","--","-d","C:\\git\\node\\chiri","-p","Git","Bash"]
```

So unrelatedly, it seems like for some reason `wt.exe` happens to work with `-p` being broken into multiple arguments, but only if it's after `-d` or after another argument or something?

But the core issue still seems to be here, that it's still breaking up "Git Bash" into multiple arguments, and I don't know why. I have zero idea why `spawn` would be causing the argument array to be further broken down. I've never seen that behaviour before

**Comment by ChiriVulpes** [comment]
You know, come to think of it, I looked through some other `spawn` calls in `win32.ts` and it appears like [quotes are actually added around them](https://github.com/desktop/desktop/blob/development/app/src/lib/shells/win32.ts#L407). It makes me think maybe this is just how `spawn` works, it just calls `.join(" ")` on the parameters and that's it

**Comment by sergiou87** [comment]
That is true… but I also checked and this current approach works well 🤯 

https://github.com/user-attachments/assets/bbb1d531-d07b-476e-95f2-3f47cb2bd10b

**Comment by ChiriVulpes** [comment]
As stated in the above, wt.exe happens to work with the value for -p broken into multiple parameters if they're at the end. It's still breaking it into multiple arguments, wt just happens to work with the specific order you're doing this

**Comment by sergiou87** [comment]
Sorry, I missed that part. I can repro the issue if I move the parameter to the beginning, as you say. From what I can see, this only happens on Windows when the option `shell: true` is passed to `spawn`, otherwise it works. At the same time, if I add quotes to all arguments, it only works when `shell: true` 🤦‍♂ 

I will submit a fix/workaround/hack and deploy a beta with it. I don't think we will ship it to production for a while, so if you can test it once it's out, we'd really appreciate it 🙇‍♂

**Comment by sergiou87** [comment]
@ChiriVulpes The latest beta from https://desktop.github.com/beta should include that fix, please give it a try and let us know if you ran into anything else! 💖

**Comment by ChiriVulpes** [comment]
Works as expected now! Thank you so much!

**Comment by mody369** [comment]
???????????????????????????????????????????????????????


fuck uuyuhyuyuyuyuyu
