### ISSUE TITLE
Ability to pin a repo

### ISSUE THREAD

**Issue by CitroenGames** [desktop/desktop#19212]
### Feature Request

Imagine having 100 repositories on your computer, but for this week, you only plan to work on two. Instead of searching for them every time, you could simply pin these two repositories for easy access, making it quick and easy to switch between them.

The idea is to add a "pin" feature in the same location where the rest of your repositories are listed, as shown below:  
![image](https://github.com/user-attachments/assets/5e5225a7-d6c4-4330-beb7-0ce037c5ebf3)

### Proposed Solution

This feature would allow users to conveniently pin selected repositories, ensuring they are always easily accessible without needing to search through the full list.

**Comment by sergiou87** [comment]
Thank you for this feature request 🙏  We are collecting feedback for this feature https://github.com/desktop/desktop/issues/8183. At this time we do not have plans to change the repository list, but we may reconsider again in the future thus, I am going to copy your feedback to that issue.
