### ISSUE TITLE
Text Alignment on Changed File List

### ISSUE THREAD

**Issue by davimack** [desktop/desktop#19215]
### The feature request

On the list of changed files, they are aligned with the standard text alignment of text to the left.  In projects with long paths, this is inconvenient as one needs to expand that pane to show the actual file name.  In cases where there is a mixture of long and short paths, it becomes difficult to pick out the file name.

For example:
IssueTracker\IssueTracker\Areas\TurnoverChecklists\Views\OnboardingProcess\MenuItems.cshtml
IssueTracker\IssueTracker\Areas\VOC\Views\Home\Index.cshtml

### Proposed solution

A right-align button would address this issue.  If that button were to align to the last path separator, that would be ideal, 'though that would admittedly be above and beyond

### Additional context

![image](https://github.com/user-attachments/assets/d96905aa-9247-4ca0-b5fb-b2ddc4619838)

**Comment by tidy-dev** [comment]
@davimack  Thank you for the feedback. We have a few issues tracking improvement suggestions for the change list. This one is akin to https://github.com/desktop/desktop/issues/19016  in terms of long paths making scanning harder. I am going to add your feedback there as another option for solving the issue.

**Comment by davimack** [comment]
Thank you!

 

As I’m sure you know: there are some really deep paths out there!
