### ISSUE TITLE
UNLISTED

### ISSUE THREAD

**Issue by SantaLaMuerte** [desktop/desktop#19225]
### The feature request

Plz add an UNLISTED folder in stars, that will auto collect all stared repos, if them not presented in users list. 

### Proposed solution

Automatically or manual create list (in starts) called Unlisted.
it will collect to himself all your starred repos which is not presented at least in one user lists! PLZ

### Additional context

Thx

**Comment by SantaLaMuerte** [comment]
NO ITS NOT ACCIDENTALLY

**Comment by steveward** [comment]
@hastalamuerte it sounds like you are wanting to provide feedback for github.com. You can do that here: https://github.community.

**Comment by SantaLaMuerte** [comment]
> @hastalamuerte it sounds like you are wanting to provide feedback for github.com. You can do that here: https://github.community.

https://github.com/orgs/community/discussions/147751

Thanks for answer , i create a thread on Discussion, but there is total ignore. I understand that its a pre New Year time, but honestly i am not first and for shure not last user wich ask about it. Maybe you can help , to spot the light on that COOL FEATURE REQUEST ) Thanks.
