### ISSUE TITLE
Cannot clone any repository on github desktop

### ISSUE THREAD

**Issue by supmalladi26** [desktop/desktop#19226]
![image](https://github.com/user-attachments/assets/3975957d-aeb2-4b62-871d-8fe53a7abead)

I somehow cannot clone anything on my github desktop. It is giving me an "Unknown error".

Also, when I open my github desktop, it gives me this message :
![image](https://github.com/user-attachments/assets/3d9068c7-bbbc-4f61-badb-9993163eaae4)

**Comment by tidy-dev** [comment]
@supmalladi26 Thank you for reaching out. That error would indicate to me that part of the installation or recent update failed to install.

Could you try doing a fresh install?

1. Close GitHub Desktop
2. Remove all of the files in `%LOCALAPPDATA%\GitHubDesktop\` (Assuming Windows, remove files `~/Library/Application Support/GitHub Desktop` for macOS)
3. Reinstall GitHub Desktop from http://desktop.github.com/

Let me know if that gets it working for you!

**Comment by supmalladi26** [comment]
I tried and it worked after I tried cloning as an admin. it was for work so I had to use admin rights.

**Comment by tidy-dev** [comment]
@supmalladi26 Sounds like you got it working? 

Requiring admin rights is not typical. It would indicate that your regular user doesn't have permission to install where you are attempting to install. Hopefully that helps in tracking down what needs to change in your environment. But, as this appears to be an environment setup issue, I cannot help much further.
