### ISSUE TITLE
Copying text from a commit copies "-" and "+" characters

### ISSUE THREAD

**Issue by simonlast** [desktop/desktop#1923]
### Description

When I copy text from a commit, it also copies "-" and "+" characters at the beginning of the line. This is annoying because I have to strip them out when I paste them elsewhere.

### Version

**GitHub Desktop version:** 0.5.9

### Steps to Reproduce

1. Make a commit.
2. Copy some text that was added or deleted, then paste it elsewhere.

**Comment by niik** [comment]
Closing as a duplicate of #1499
