### ISSUE TITLE
Github Desktop Publish Branch

### ISSUE THREAD

**Issue by Absolutionism** [desktop/desktop#19230]
### The problem

I have a fork of a project so I can create PRs. But when creating a branch inside the desktop program, and publish the branch. The publish branch never goes away. So then I can't do any pulls.

### Release version

3.4.4

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Create a new branch based off another branch
2. Makes some edits to files
3. Publish Branch
4. Publish branch never goes away

### Screenshots

https://github.com/user-attachments/assets/b8a0b95d-9df3-48b0-a035-41241eedb29c

**Comment by Absolutionism** [comment]
Closing and reopening desktop does not fix

**Comment by Absolutionism** [comment]
I ended up just deleting the repository from my github desktop and the directory. Re-cloned and it's fixed now.

**Comment by steveward** [comment]
Glad to hear things are working now!
