### ISSUE TITLE
Github desktop download page not up?

### ISSUE THREAD

**Issue by WarFiN123** [desktop/desktop#19246]
### The problem

I had opened the github desktop a few hours back to install on another pc and now when i open it again it shows me this:
![image](https://github.com/user-attachments/assets/2c00b30c-0414-4044-842c-10db1a88bf9b)

Im clicking the download button on [this site](https://github.com/apps/desktop/) however it just shows the error

The release notes page also seems to be broken

### Release version

N/A

### Operating system

Windows

### Steps to reproduce the behavior

1. Go to [this site](https://github.com/apps/desktop/)
2. Click the download now button or the releases button

### Screenshots

![image](https://github.com/user-attachments/assets/4a8d8926-1c0f-45ab-ab68-bf614802f691)
![image](https://github.com/user-attachments/assets/2b39aa3d-a4ef-4bd4-b0b0-2e5e2e560a86)

**Comment by idMysteries** [comment]
https://github.com/desktop/desktop?tab=readme-ov-file#where-can-i-get-it
This link works

**Comment by WarFiN123** [comment]
> https://github.com/desktop/desktop?tab=readme-ov-file#where-can-i-get-it This link works

Yea I just ended up downloading the build from this repo but I thought I needed to report this anyway

**Comment by tidy-dev** [comment]
@WarFiN123 Thank you for reporting! We are working to correct it now. 

In the mean time, you can find a full list of releases at https://desktop.githubusercontent.com/

**Comment by tilemanrenovations** [comment]
Yea I see what you’re talking about. I’m not sure what that was. Thanks for sharing. Let me know if you  need anything else.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by WarFiN123** [comment]
> @WarFiN123 Thank you for reporting! We are working to correct it now.
> 
> In the mean time, you can find a full list of releases at https://desktop.githubusercontent.com/

Note: The releases page also does not work

**Comment by tidy-dev** [comment]
Thanks for heads up! I cannot reproduce and it is hosted separately from desktop.github.com. Can you tell me what it is doing when you go to https://desktop.githubusercontent.com/?

**Comment by jtruitt1** [comment]
@tidy-dev, the link you provided works for me, but the ["release notes" page](https://desktop.github.com/release-notes/) linked from the [main GH Desktop page](https://github.com/apps/desktop/) doesn't.

**Comment by tidy-dev** [comment]
Ah yes. I misunderstood and thought @WarFiN123 was referring to release page that has all the past releases. 

The sites using the host `https://desktop.github.com` are known to be down.  (https://desktop.github.com/release-notes/ and https://desktop.github.com/download)

**Comment by tidy-dev** [comment]
https://desktop.github.com is back online (note, you may have to clear browser cache to see it again)

**Comment by WarFiN123** [comment]
> https://desktop.github.com is back online (note, you may have to clear browser cache to see it again)

The landing page was always online, it's the subpages that don't work:

![Screenshot_20240912_203118](https://github.com/user-attachments/assets/49461942-c6e0-4ccc-b024-2b5cc73db732)

**Comment by WarFiN123** [comment]
> https://desktop.github.com is back online (note, you may have to clear browser cache to see it again)

Nvm, thank you!!!

**Comment by tidy-dev** [comment]
Thank you again for the report. The landing page is actually hosted at github.com/apps/desktop and direct call to desktop.github.com would redirect to that. Only desktop.github.com/download and desktop.github.com/release-notes do not redirect back to github.com/apps/desktop. In this case, desktop.github.com went down so github.com/apps/desktop and pages  github.com/apps/desktop/* were still working.
