### ISSUE TITLE
Allow bypassing of commit hooks or push hooks using gui

### ISSUE THREAD

**Issue by jmechamFD** [desktop/desktop#19247]
### The feature request

I would like the ability to bypass pre-commit hooks or pre-push hooks when using the github desktop cli. This would be the equivalent functionality as the --no-verify flag used to bypass the hooks when using the cli.

### Proposed solution

I think you could add this option as a dropdown arrow that is apart of the commit button and push button.
Or you could allow us to right click the button to see this option that we can select.

**Comment by tilemanrenovations** [comment]
I agree that your idea is good. Work on it. I will be glad to help as soon as I clear backlog.

**Comment by jmechamFD** [comment]
I've never developed an Electron app so I won't be helpful in implementing this feature. But sounds good thank you for the quick response.

**Comment by tidy-dev** [comment]
@jmechamFD Thank you for reaching out! We are tracking improvement for commit hook failures in https://github.com/desktop/desktop/issues/9351. I am closing in favor of tracking there.

This idea has been floated before there and the past stance that we have communicated on it is that we would prefer not to add this option as a dropdown (as commit hooks are not used by the vast majority of users), but on failure have a something like a "try again with no verify flag" option in the failure dialog.
