### ISSUE TITLE
loadstring(game:HttpGet"https://raw.githubusercontent.com/UserDevEthical/Loadstring/main/CokkaHub.lua")()

### ISSUE THREAD

**Issue by jijdeV-3bopni-hihquf** [desktop/desktop#19244]

**Comment by MrAkaaZaki** [comment]
My is not working

**Comment by Xsh52** [comment]
J

**Comment by niewiem3** [comment]
how do i download this?

**Comment by Bahrani2** [comment]
https://raw.githubusercontent.com/londnee/code/refs/heads/main/Fisch.lua

**Comment by sarah2491222** [comment]
d

**Comment by Dcdnkbddx** [comment]
loadstring(game:HttpGet("https://raw.githubusercontent.com/londnee/code/refs/heads/main/Fisch.lua"))()

**Comment by Dcdnkbddx** [comment]
loadstring(game:HttpGet("https://raw.githubusercontent.com/londnee/code/refs/heads/main/Fisch.lua"))()

**Comment by Dcdnkbddx** [comment]
https://raw.githubusercontent.com/londnee/code/refs/heads/main/Fisch.lua
