### ISSUE TITLE
can't clone

### ISSUE THREAD

**Issue by Bola-Philip** [desktop/desktop#19250]
### The problem

Cloning into 'D:\projects\New folder\ostooo'...
remote: Enumerating objects: 8186, done.        
remote: Counting objects: 100% (13/13), done.        
remote: Compressing objects: 100% (10/10), done.        
error: RPC failed; curl 56 Failure when receiving data from the peer
error: 1356 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

Would you like to retry cloning 

### Release version

Version 3.4.5 (x64)

### Operating system

Windows 10

### Additional context

i tried puffer and everything it didn't help

**Comment by Bola-Philip** [comment]
bug

**Comment by steveward** [comment]
Thanks for the issue @Bola-Philip. Can you try running this command to see if it gets things working?

`git config --global http.postBuffer 157286400`

Let me know if that helps.

**Comment by tidy-dev** [comment]
Closing as stale.
