### ISSUE TITLE
unable to push repository to github

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#19258]
### The problem

when i say publish repository it says sign in git hub, when i sign in it says continue in web browser and just doesnt go anywhere.i have github logins

### Release version

3.4.3(x64)

### Operating system

windows 10 pro

### Screenshots

![Screenshot (1263)](https://github.com/user-attachments/assets/efb3f04b-b016-467f-9196-83ed3b9b6208)

**Comment by tidy-dev** [comment]
@keketsomakhoali Thank you fro reaching out. Could you please upload the logs from the day this occurred (or if you can reproduce)?
