### ISSUE TITLE
Cannot push these commits as they contain an email address marked as private on GitHub.

### ISSUE THREAD

**Issue by Mopzilla** [desktop/desktop#19254]
### The problem

I am new to GitHub and created a repository to store my project. I am using GitHub desktop and when I hit "Publish Branch" I get the error:

`Cannot push these commits as they contain an email address marked as private on GitHub. To push anyway, visit https://github.com/settings/emails, uncheck "Keep my email address private", then switch back to GitHub Desktop to push your commits. You can then enable the setting again.`

I've looked at a dozen issue posts and stackoverflow posts, with them all providing the same solution. I need to either set the noreply email in the GitHub desktop app for my repository, or set it using `git`.

I've tried both, I also used both `git config user.email` and `git config --global user.email` with both printing out the correct no-reply email.

Yet GitHub desktop still throws the same error. I tried restarting GitHub desktop, redownloading, updating Git, nothing seems to change it.

I don't have a clue what I am doing wrong :(

### Release version

Version 3.4.5 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

It happens when I click `Publish Branch`

### Log files

[2024-09-13.desktop.production.log](https://github.com/user-attachments/files/16990527/2024-09-13.desktop.production.log)

### Screenshots

![image](https://github.com/user-attachments/assets/f656fbe5-e0fc-4de3-886d-550e22da9536)

**Comment by Mopzilla** [comment]
Decided to disable the security check so I could upload my project and noticed when I checked the commit it indeed comitted with the wrong email. For some reason it's using my private email even though I have it set to use my noreply in Github Desktop.

**Comment by steveward** [comment]
Glad to hear you were able to get things working again. Like the error mentions, the private setting needs to be changed or the history of your repository needs to be rewritten in order to push.

**Comment by tilemanrenovations** [comment]
I really appreciate all your help. I sure can use some more when you have time.
