### ISSUE TITLE
Still can't open anything in Rider, and yes, I tried rebooting my computer and re-installing GitHubDesktop

### ISSUE THREAD

**Issue by tommiecas** [desktop/desktop#19251]
### The problem

I cannot open a repository from GitHub Desktop into Rider. I get this error, and it restarts. I already filed a bug about this, and was told to reboot my computer, and uninstall/reinstall GitHub. I did both things and neither worked. Please advise... 

![GitHubError](https://github.com/user-attachments/assets/ad331cc5-2497-4230-8304-82043155f83c)
![GitHubError](https://github.com/user-attachments/assets/bc512cf4-67ca-4760-afdb-8613b444b959)
![GitHubError](https://github.com/user-attachments/assets/f95f0123-aa6f-4eb8-b867-304ff352ef2b)
![GitHubError](https://github.com/user-attachments/assets/976bfd11-b2c0-4dff-ad4b-2e9251ca56d3)

### Release version

Version 3.4.5-beta2 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1) Click "Open in JetBrainsRider" on the homepage of GitHubDesktop. 

### Log files

[2024-09-12.desktop.beta.log](https://github.com/user-attachments/files/16985981/2024-09-12.desktop.beta.log)
[2024-09-12.desktop.production.log](https://github.com/user-attachments/files/16985982/2024-09-12.desktop.production.log)

### Screenshots

![GitHubError](https://github.com/user-attachments/assets/09b03f45-d111-4a5f-8e19-60d007dcb361)
![GitHubError](https://github.com/user-attachments/assets/c864a643-23de-4786-96c9-f733b986ad8d)

**Comment by steveward** [comment]
@tommiecas let's keep this going in the original issue https://github.com/desktop/desktop/issues/19167.
