### ISSUE TITLE
History Search  tab

### ISSUE THREAD

**Issue by Rootjhon** [desktop/desktop#19261]
### The feature request

Search gitcommit in History tab
1. click "History tab"
2. input string, eg.  "update version"
3. show me Commits which summary match input string. ("update version")

![image](https://github.com/user-attachments/assets/16e51b8d-2e13-47a9-a351-2da77e8d9f15)

### Proposed solution

-

**Comment by tidy-dev** [comment]
@Rootjhon Thank you for reaching out. We are tracking feedback for this feature in https://github.com/desktop/desktop/issues/7022. Feel free to add a thumbs up to the issue to voice your support.
