### ISSUE TITLE
Is there a way to unlock a file (from git lfs) when discarding changes in github desktop

### ISSUE THREAD

**Issue by PeteBaker1** [desktop/desktop#19268]
### The feature request

Unlock File when discarding changes

### Proposed solution

Avoids Manual Unlocking

**Comment by steveward** [comment]
@PeteBaker1 thanks for the issue. Managing Git LFS file locking is something that has been previously discussed in https://github.com/desktop/desktop/issues/8419, but at this time is not on our radar. I'll reference this issue there for tracking purposes. Thanks for the feedback.
