### ISSUE TITLE
PNG image fail to push

### ISSUE THREAD

**Issue by raymondhalimm** [desktop/desktop#19263]
### The problem

Cannot push PNG image through Github desktop after update. Error message "The remote disconnected. Check your Internet connection and try again."
<img width="1072" alt="Screenshot 2024-09-15 at 01 23 25" src="https://github.com/user-attachments/assets/1e488cf8-bbf6-43a6-bf4d-099e9c656fec">

### Release version

Version 3.4.5 (x64)

### Operating system

MacOs 14.6.1 

### Steps to reproduce the behavior

Commit with PNG image
Push

**Comment by tidy-dev** [comment]
@raymondhalimm Thank you for reaching out. Could you upload the logs for when this happened?

**Comment by raymondhalimm** [comment]
Total 9 (delta 2), reused 0 (delta 0), pack-reused 0 (from 0)
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Everything up-to-date

(The error was parsed as 5: The remote disconnected. Check your Internet connection and try again.)

These are the logs when the error shows up. @tidy-dev 
Thank you for the response

**Comment by mogikanen9** [comment]
Have exactly same problem - after update of GitHub desktop to the latest version cannot push a repo with "The remote disconnected. Check your Internet connection and try again."

My MacOS version is Monterey 12.7.6
GitHub desktop version is "3.4.5 (x64)"

Logs:
```
ompressing objects: 100% (22/22), done.
Writing objects:   4% (1/22)
Writing objects:   9% (2/22)
Writing objects:  13% (3/22)
Writing objects:  18% (4/22)
Writing objects:  22% (5/22)
Writing objects:  27% (6/22)
Writing objects:  31% (7/22)
Writing objects:  36% (8/22)
Writing objects:  40% (9/22)
Writing objects:  45% (10/22)
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
send-pack: unexpected disconnect while reading sideband packet
Writing objects:  45% (10/22), 1.07 MiB | 707.00 KiB/s
Writing objects:  50% (11/22), 1.07 MiB | 707.00 KiB/s
Writing objects:  54% (12/22), 1.07 MiB | 707.00 KiB/s
Writing objects:  54% (12/22), 11.41 MiB | 5.58 MiB/s 
Writing objects:  59% (13/22), 11.41 MiB | 5.58 MiB/s
Writing objects:  63% (14/22), 11.41 MiB | 5.58 MiB/s
Writing objects:  68% (15/22), 11.41 MiB | 5.58 MiB/s
Writing objects:  72% (16/22), 11.41 MiB | 5.58 MiB/s
Writing objects:  77% (17/22), 11.41 MiB | 5.58 MiB/s
Writing objects:  81% (18/22), 11.41 MiB | 5.58 MiB/s
Writing objects:  86% (19/22), 11.41 MiB | 5.58 MiB/s
Writing objects:  90% (20/22), 11.41 MiB | 5.58 MiB/s
Writing objects:  95% (21/22), 11.41 MiB | 5.58 MiB/s
Writing objects: 100% (22/22), 11.41 MiB | 5.58 MiB/s
Writing objects: 100% (22/22), 14.12 MiB | 6.68 MiB/s, done.
Total 22 (delta 1), reused 0 (delta 0), pack-reused 0 (from 0)
fatal: the remote end hung up unexpectedly
Everything up-to-date

(The error was parsed as 5: The remote disconnected. Check your Internet connection and try again.)
2024-09-17T02:00:35.301Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 4 repositories took 1.2s of which 0.0s paused, total 1.2s
```

**Comment by steveward** [comment]
@mogikanen9 you can try running this command to see if it helps:

`git config --global http.postBuffer 157286400`

Let me know if that gets things working.

**Comment by mogikanen9** [comment]
Hi @steveward, tried `git config --global http.postBuffer 157286400` - it helped - I could successfully push the repo. Thanks a lot for the help.

**Comment by steveward** [comment]
Glad to hear that got things working!
