### ISSUE TITLE
ARM Version of 3.4.5 flagged by VirusTotal

### ISSUE THREAD

**Issue by mihelm** [desktop/desktop#19270]
### The problem

Hi

The ARM version of 3.4.5 is being flagged by VirusTotal:

https://www.virustotal.com/gui/file/56b1908907f49ee2b97946f9117f74ac237f3c58e12f7505a763d928a3be8801/detection

The reason appears to be an attempt to contact `push.apple.com`:
https://www.virustotal.com/gui/file/56b1908907f49ee2b97946f9117f74ac237f3c58e12f7505a763d928a3be8801/behavior

Cheers, michael.

### Release version

3.4.5

### Operating system

Any

### Steps to reproduce the behavior

Download ARM version of 3.4.5 and upload on www.virustotal.com

**Comment by steveward** [comment]
Thanks for letting us know about this @mihelm. I'll reach out to see if we can get this resolved.

**Comment by steveward** [comment]
Latest check shows this as resolved. Closing.
