### ISSUE TITLE
Delete Tag on GitHub website, but Not reflected in GitHub Desktop

### ISSUE THREAD

**Issue by tunaingot** [desktop/desktop#19277]
### The problem

- Create Tag on GitHub Desktop -> Push
- Delete Tag on GitHub website
- GitHub Desktop -> Fetch, But Tag not Deleted

GitHub Desktop can not delete Tag.

### Release version

Version 3.4.5 (arm64)

### Operating system

macOS 14.6.1（23G93）

**Comment by tunaingot** [comment]
<img width="1134" alt="スクリーンショット 2024-09-18 16 34 29" src="https://github.com/user-attachments/assets/1ca8165e-4e8d-494c-83dc-c283cc4412fd">

<img width="1195" alt="スクリーンショット 2024-09-18 16 36 47" src="https://github.com/user-attachments/assets/7afac2be-0af9-43f0-8d81-bee2cf4761d7">

<img width="1128" alt="スクリーンショット 2024-09-18 16 36 07" src="https://github.com/user-attachments/assets/f8d61022-0505-40a6-96bc-02b2bb3627bd">

**Comment by tunaingot** [comment]
<img width="1127" alt="スクリーンショット 2024-09-18 16 42 16" src="https://github.com/user-attachments/assets/0ac49c1f-165a-4dcc-a6ab-3032dffb9930">
<img width="1195" alt="スクリーンショット 2024-09-18 16 36 47" src="https://github.com/user-attachments/assets/6976b309-3807-4ad0-a6ce-bf0fa0e97605">
<img width="1128" alt="スクリーンショット 2024-09-18 16 36 07" src="https://github.com/user-attachments/assets/e73df57b-bf05-412c-aa07-8f78b9c662f6">

**Comment by steveward** [comment]
@tunaingot thanks for the issue. GitHub Desktop does not automatically prune tags that have been deleted in the remote repository, but you can run this command from the terminal to do that:

`git fetch --prune --prune-tags`

See [the official Git documentation](https://git-scm.com/docs/git-fetch#_pruning) for specifications on how this works.

At this time we don't have this functionality available in GitHub Desktop. You could set your .gitconfig with the [`fetch.pruneTags` option](https://git-scm.com/docs/git-config#Documentation/git-config.txt-fetchpruneTags) if you'd like to turn this on by default.

**Comment by tunaingot** [comment]
Thank you for your response.
I have successfully resolved the issue.
