### ISSUE TITLE
git authentification

### ISSUE THREAD

**Issue by Beni-niyogisubizo** [desktop/desktop#19280]
### The problem

can I get a description why my git is not authenticating to ubuntu?

### Release version

Version 3.4.5 (x64)

### Operating system

windows 10

### Screenshots

<img width="941" alt="Screenshot 2024-09-18 172758" src="https://github.com/user-attachments/assets/5974a799-4c6e-4b4e-8ee6-ae1f9e66c597">

**Comment by steveward** [comment]
@Beni-niyogisubizo this issue tracker is for GitHub Desktop. You can see steps to authenticate via the command line here:

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github#authenticating-with-the-command-line
