### ISSUE TITLE
Unity's material changes are not recorded with Github

### ISSUE THREAD

**Issue by sunilcreativesighter** [desktop/desktop#19288]
### The problem

As I change the Unity material properties, nothing is getting recorded in the Changes to commit.
When I create a new Unity material, it'll show that there's a new material, but the properties when changed, it doesn't reflect.

### Release version

Version 3.4.5 (x64)

### Operating system

Windows

### Steps to reproduce the behavior

1. Add a Unity Material
2. Change color and other properties

**Comment by steveward** [comment]
@sunilcreativesighter thanks for the issue. This is likely due to the files being in your `.gitignore`. You can see what's ignored by going to `Repository` > `Repository Settings` > `Ignored files`.

I'm going to close this out, but let me know if that's not the case.

**Comment by sunilcreativesighter** [comment]
Hi, Thanks for the reply,

Here is the Git ignore configuration -

# This .gitignore file should be placed at the root of your Unity project
directory
#
# Get latest from
https://github.com/github/gitignore/blob/master/Unity.gitignore
#
/[Ll]ibrary/
/[Tt]emp/
/[Oo]bj/
/[Bb]uild/
/[Bb]uilds/
/[Ll]ogs/
/[Uu]ser[Ss]ettings/

# MemoryCaptures can get excessive in size.
# They also could contain extremely sensitive data
/[Mm]emoryCaptures/

# Asset meta data should only be ignored when the corresponding asset is
also ignored
!/[Aa]ssets/**/*.meta

# Uncomment this line if you wish to ignore the asset store tools plugin
# /[Aa]ssets/AssetStoreTools*

# Autogenerated Jetbrains Rider plugin
/[Aa]ssets/Plugins/Editor/JetBrains*

# Visual Studio cache directory
.vs/

# Gradle cache directory
.gradle/

# Autogenerated VS/MD/Consulo solution and project files
ExportedObj/
.consulo/
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# Unity3D generated meta files
*.pidb.meta
*.pdb.meta
*.mdb.meta

# Unity3D generated file on crash reports
sysinfo.txt

# Builds
*.apk
*.aab
*.unitypackage

# Crashlytics generated file
crashlytics-build.properties

# Packed Addressables
/[Aa]ssets/[Aa]ddressable[Aa]ssets[Dd]ata/*/*.bin*

# Temporary auto-generated Android Assets
/[Aa]ssets/[Ss]treamingAssets/aa.meta
/[Aa]ssets/[Ss]treamingAssets/aa/*


Actually, new materials are being recorded or even when renamed.
When the properties are changed such as color and so on, these are not
recorded.

But, my partner uses Source tree to push and pull for the same repo, and at
his end, all these properties are being recorded

Thanks & Regards,
*Sunil N*

**Comment by th3W3n** [comment]
I am having the same issue here. Unity 2022.3.52f1 + VSCode 1.95.3
