### ISSUE TITLE
autocomplete should mention teams as well as users

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#1928]
### Description

When filling out text anywhere on GitHub, you can autocomplete to mention teams as well as people. For example:

<img width="436" src="https://user-images.githubusercontent.com/359239/26893744-963de8cc-4b92-11e7-88ab-eafb9df2a607.png">

This doesn't work the same in the current application - it only lists users:

<img width="331" src="https://user-images.githubusercontent.com/359239/26893783-bb0c3e6a-4b92-11e7-80dc-91912d6aa485.png">

**Comment by joshaber** [comment]
I _believe_ this will require github/github changes, as which teams are mentionable depends on the user.

**Comment by shiftkey** [comment]
@joshaber fair point. I was also thinking about if we could use the [teams API]( https://developer.github.com/v3/orgs/teams/#list-teams) directly to get the same effect but that requires OAuth [scopes](https://github.com/desktop/desktop/blob/2bea367b70e984dee7c006d12b6c9e147f3f624a/app/src/lib/api.ts#L22-L25) changes as we don't ask for `read:org`. 🤔

**Comment by billygriffin** [comment]
Since we haven't seen this as something people are desiring, I'm going to close it for now. Thanks!
