### ISSUE TITLE
Worktree support in desktop app.

### ISSUE THREAD

**Issue by amitdhiman000** [desktop/desktop#19307]
### The feature request

I can't see my git worktrees in desktop app. Would be great to have that.

### Proposed solution

We can have worktrees list right under the each repository.

### Additional context
<img width="1725" alt="GithubApp" src="https://github.com/user-attachments/assets/4d97b7ec-4905-48d9-84c7-3dc4d671865c">

_No response_

**Comment by steveward** [comment]
Thanks for the issue @amitdhiman000. This is being tracked in https://github.com/desktop/desktop/issues/907, so you can follow along there for updates.

**Comment by scottcorgan** [comment]
Might be a good time to rethink not implementing this since worktrees are everywhere now

**Comment by MaxLikesCode** [comment]
Claude Code uses worktrees a lot (which is good) but not being able to see them in GitHub Desktop is annoying. Please add this feature.

**Comment by nikolailehbrink** [comment]
They integrated it 🥳
