### ISSUE TITLE
Add a "Fetch all" button

### ISSUE THREAD

**Issue by lefrost** [desktop/desktop#19301]
### The feature request

A "Fetch all" button, either next to the "Fetch origin" button and/or somewhere under the Repository tab in the menu bar. It would do what "Fetch origin" does, but for every repository. The fetch doesn't have to be simultaneous; I just don't want to repeatedly click "Fetch origin" for x repositories every time I boot up the client:

![this](https://github.com/user-attachments/assets/dbc39efe-7d9a-4f21-93e5-64c61ae12837)

### Proposed solution

Saves time, less clicking. "Focus on what matters instead of fighting with Git."

**Comment by steveward** [comment]
Thanks for the feedback @lefrost. This is being tracked in https://github.com/desktop/desktop/issues/13700, so you can follow along there for updates.
