### ISSUE TITLE
GITHUB Desktop wont open at all

### ISSUE THREAD

**Issue by Aleg21-11** [desktop/desktop#19315]
I downloaded GitHub Desktop but it doesnt open either when just installing nor when i try to open in it in my %appdata% files. I can't find it in my windows explorer either, but when I open the control Panel I see the github Desktop app there, until I click it and then it dissapears. I dont know what the problem is. I have tried 

Uninstalling and Installing again
Deleted the files in %LOCALAPPDATA% and %APPDATA%
Running the installer as Admin

**Comment by sergiou87** [comment]
Are you using the EXE or MSI installer?

Can you try deleting this directory and then attempt a new installation to see if it makes any difference?

` C:\Users\<your-user>\AppData\Local\SquirrelTemp`

**Comment by Aleg21-11** [comment]
I am using EXE installer.
I also tried what you told me and it still didn't work, app doesn't even start after the installation is supposedly finished

Sorry for closing and opening, pc lagged a bit.

**Comment by sergiou87** [comment]
Do you have anything at all in `C:\Users\<your-user>\AppData\Local\GitHubDesktop` or `C:\Users\<your-user>\AppData\Roaming\GitHubDesktop` ? Any log files in there? 🤔
