### ISSUE TITLE
Rebase can not work

### ISSUE THREAD

**Issue by cyk2018** [desktop/desktop#19317]
### The problem

Suppose I have two branchs, A and B, and I add some commits in A, I want to  get this update to B.
First I try to set HEAD at A and click rebase, then the tool say: this branch is up to date.
Then I try to set HEAD at B and click rebase, then the tool show there are something happening but nothing changed.

### Release version

3.4.5

### Operating system

Win11

### Steps to reproduce the behavior

simple to reproduce.

**Comment by sergiou87** [comment]
Is this the same as #17892?

**Comment by cyk2018** [comment]
> Is this the same as #17892?这是否与 #17892 ？

Yes， I watch the video, should I close my issue?

**Comment by sergiou87** [comment]
No worries, I will close it for you 😄  You can subscribe to that issue if you want to get updates.

The good news is we already have a Pull Request open to fix the problem: https://github.com/desktop/desktop/pull/19031

Thanks for your report anyway! 💖
