### ISSUE TITLE
Broken syntax higlight in Typescript files using template literal types

### ISSUE THREAD

**Issue by pmrotule** [desktop/desktop#19311]
### The problem

The syntax highlighting get broken in Typescript files as soon as I use [template literal types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html).

### Release version

Version 3.4.2 (x64)

### Operating system

macOS Sonoma v14.5

### Steps to reproduce the behavior

1. Create a `.ts` file with the following content:

```ts
export enum COLORS {
  red = 'red',
  blue = 'blue',
  yellow = 'yellow',
}

export const FOO = 'bar'

export type Options = {
  path: `/${string}`
  color: `${COLORS}`
}

export interface BrokenSyntaxHighlight {
  isBroken: boolean
}

export type MoreOptions = {
  secondaryColor: `${COLORS}`
}

export interface StillBroken {
  isBroken: boolean
}

export const ABC = '123'
```

2. Select it in Github Desktop to see a preview of the file content
3. You'll notice the syntax breaking from the first use case of a template literal type

### Screenshots

<img width="662" alt="image" src="https://github.com/user-attachments/assets/a52ce35e-8fe8-4311-99e3-e09864272189">

**Comment by sergiou87** [comment]
Hmmm could you update to the latest 3.4.5? It works fine here…

![Image](https://github.com/user-attachments/assets/47a6c2f3-e40a-405f-81ca-625731f5ce87)

**Comment by pmrotule** [comment]
> Hmmm could you update to the latest 3.4.5? It works fine here…

@sergiou87 I updated to 3.4.5 and the issue is gone...

It has been annoying me for a long time, I'm happy to see it finally fixed 🙌
