### ISSUE TITLE
Github Desktop app continues to get more and more blurry

### ISSUE THREAD

**Issue by RimFaxxe** [desktop/desktop#19321]
### The problem

Hey!
In nvidia's control panel I disabled anti aliasing for the github desktop app, but it still becomes super blurry and often impossible to read. In the logs I don't see anything that would point to why the app goes blurry.

### Release version

3.4.5 x64

### Operating system

Windows 10 22H2

### Steps to reproduce the behavior

1. Launch the GitHub app
And that's it, it's kind of fine under Changes, but under History it goes super blurry

### Log files

[2024-09-27.desktop.production.log](https://github.com/user-attachments/files/17165135/2024-09-27.desktop.production.log)

### Screenshots

![image](https://github.com/user-attachments/assets/6655a37e-f2ff-4f5d-8fb8-5f5d8e752a04)

### Additional context

My GPU doesn't seem to be failing, I'm only experiencing issues with the github app and I already disabled FXAA for the app and that didn't really fix the problem.

**Comment by sergiou87** [comment]
Could you try editing the app's shortcut (the one you use to open the app, from the Desktop or the start menu) and add the `--disable-gpu` parameter to see if that resolves this issue?

**Comment by RimFaxxe** [comment]
> Could you try editing the app's shortcut (the one you use to open the app, from the Desktop or the start menu) and add the `--disable-gpu` parameter to see if that resolves this issue?

It's embarassing to admit that I don't really know where I'm supposed to add this parameter... ^^' in properties I don't see anything about parameters

**Comment by sergiou87** [comment]
Not embarrassing at all! I'm sorry, I assumed everyone knows how to do that 😅 

In the properties dialog, just add ` --disable-gpu` at the end of the `Target` text field, like this:

![Image](https://github.com/user-attachments/assets/4a4b5e82-906f-4e55-a622-01fd839c4804)

**Comment by RimFaxxe** [comment]
Okay so I just did that and it's still blurry... The image sharpens for a moment but then gets blurry again

**Comment by sergiou87** [comment]
Weird… 😞 

Does it happen with other Electron apps? (Like Visual Studio Code or Slack)

**Comment by RimFaxxe** [comment]
> Weird… 😞
> 
> Does it happen with other Electron apps? (Like Visual Studio Code or Slack)

Nope, I don't use visual studio code either way so I never checked

**Comment by steveward** [comment]
Have you tried any of the steps mentioned in this [Microsoft help article](https://support.microsoft.com/en-us/windows/fix-apps-that-appear-blurry-in-windows-10-e9fe34ab-e7e7-bc6f-6695-cb169b51de0f)?

There are some options there for troubleshooting blurry apps. It'd also be helpful to know if you are using multiple displays, or if there is anything else custom on your machine that could be causing this.

**Comment by RimFaxxe** [comment]
> Have you tried any of the steps mentioned in this [Microsoft help article](https://support.microsoft.com/en-us/windows/fix-apps-that-appear-blurry-in-windows-10-e9fe34ab-e7e7-bc6f-6695-cb169b51de0f)?
> 
> There are some options there for troubleshooting blurry apps. It'd also be helpful to know if you are using multiple displays, or if there is anything else custom on your machine that could be causing this.

I looked at the article but it isn't really anything helpful, I'm only using my laptop's display at 1920 x 1080, nothing has been customized recently. Not sure what could have caused it, it was kind of sudden?

**Comment by sergiou87** [comment]
Have you rebooted your laptop since this started? I wonder if that would fix it. Otherwise we plan to release soon an update that might (or might not) fix this 🤔  🤞

**Comment by RimFaxxe** [comment]
> Have you rebooted your laptop since this started? I wonder if that would fix it. Otherwise we plan to release soon an update that might (or might not) fix this 🤔 🤞

Yeah, rebooting didn't help either T^T Fingers crossed the update will fix the issue..

**Comment by RimFaxxe** [comment]
I noticed something. I'm installing star stable online to play through the halloween event and the star stable launcher got blurry like github...

**Comment by steveward** [comment]
@EmilyBondevik another user mentioned this:

>The issue was caused by Nvidia's global Antialiasing settings—specifically, the FXAA and Multi-Frame Sampled AA (MFAA) options being turned on. Restoring the default values resolved the blurred UI and font issue

I know you mentioned you turned off antialiasing, but I wanted to confirm those other options were turned off as well.

**Comment by RimFaxxe** [comment]
> @EmilyBondevik another user mentioned this:
> 
> > The issue was caused by Nvidia's global Antialiasing settings—specifically, the FXAA and Multi-Frame Sampled AA (MFAA) options being turned on. Restoring the default values resolved the blurred UI and font issue
> 
> I know you mentioned you turned off antialiasing, but I wanted to confirm those other options were turned off as well.

For now it looks like turning off MFAA fixed it, I'll see if it comes back, because last time it did come back randomly

**Comment by steveward** [comment]
Closing as resolved.
