### ISSUE TITLE
Publish button says "Publish this branch to GitHub" even when the repo is not hosted on GitHub

### ISSUE THREAD

**Issue by dizco** [desktop/desktop#1932]
### Description

Using a tfs git server to host my repo, the UI still reads "Publish this branch to GitHub". This could potentially lead to some confusion, because the button actually publishes to the remote repo, not necessarly GitHub.

### Version

**GitHub Desktop version:** 0.5.9

**OS version:** Microsoft Windows [Version 10.0.14393]

### Steps to Reproduce

1. Create a git server not on GitHub
2. Clone repo to local machine
3. Add local repo in GitHub desktop

![Screenshot](https://user-images.githubusercontent.com/7740408/26901741-e5f06edc-4ba4-11e7-9212-4124f76b5877.PNG)

**Expected behaviour:** Button text should represent the actual remote server. Could be something like this for non-GitHub hosted repos : "Publish this branch to remote" or simply "Publish this branch"

**Actual behaviour:** "Publish this branch to GitHub"

**Reproduces how often:** Always

**Comment by joshaber** [comment]
Thanks for opening this! We're already tracking this at https://github.com/desktop/desktop/issues/1498. Feel free to follow along there.
