### ISSUE TITLE
Unintended 'Modified' Tooltip Display When Navigating Changed Files with Arrow Keys

### ISSUE THREAD

**Issue by FelixLisczyk** [desktop/desktop#19325]
### The problem

When navigating through the list of changed files in the commit history using the arrow keys, a 'Modified' tooltip appears automatically above the 'Modified' icon for the selected file.

### Release version

Version 3.4.5 (arm64)

### Operating system

macOS 15.0 (24A335)

### Steps to reproduce the behavior

1. Open the GitHub Desktop app and navigate to a repository.
2. Go to the "History" tab and select a commit with multiple changed files.
3. Use the arrow keys to navigate through the list of changed files.
4. Observe the 'Modified' tooltip popping up above the file icons as you move between files.

**Expected Behavior:**
The 'Modified' tooltip should not appear unless the user hovers over the 'Modified' icon with the mouse cursor.

**Actual Behavior:**
The 'Modified' tooltip appears automatically as the user navigates through the list using the arrow keys.

### Screenshots

![gh-desktop-modified](https://github.com/user-attachments/assets/1b1fc3e9-e8cd-4804-949b-b52bd59c6a1c)

**Comment by sergiou87** [comment]
Hello 👋  I understand how this can feel annoying, but it was actually an accessibility requirement, and therefore expected (and intended) behavior 😅

**Comment by FelixLisczyk** [comment]
Hi @sergiou87,

Thank you for your response and for explaining the reasoning behind the behavior. I completely understand the importance of accessibility features, and I appreciate the effort to make the app more inclusive.

However, I was wondering if it would be possible to have an option to disable this specific tooltip behavior for users who might find it unnecessary or distracting. Since there is already an accessibility section in the settings, perhaps this could be added as a configurable option. This way, users can customize their experience according to their preferences without impacting those who rely on such features.

Thank you for considering this suggestion!
