### ISSUE TITLE
Not able to commit changes

### ISSUE THREAD

**Issue by gabriemoinfo** [desktop/desktop#19323]
### The problem

When I try to commit some changes on my branch, i got this message. 
![gitPush](https://github.com/user-attachments/assets/5c7339ea-e2c6-41e8-9ac4-95d1c1ead696)

At this point, I've already confirm that there is no changes left.
And I had reset the branch to the origin with "git reset --hard origin/branchsName"

### Release version

Version 3.4.5 (x64)

### Operating system

Windows 10

### Screenshots

![gitPush](https://github.com/user-attachments/assets/67083bd7-7e83-4d67-8c82-f37e6c3bf945)

https://github.com/user-attachments/assets/41dc6b06-64f2-4fae-bc42-5a2076d4a085

**Comment by steveward** [comment]
@gabriemoinfo thanks for the issue. Can you select `Repository` > `Pull` to pull down any new changes that are on the remote repository? That should update your local branch and allow you to push.

Let me know if that does not get things working.
