### ISSUE TITLE
Merge into current branch keyboard shortcut not working

### ISSUE THREAD

**Issue by armand-colin** [desktop/desktop#19337]
### The problem

I am trying to merge a branch into the current branch using Ctrl + Shift + M, but the pop-up never shows. It's working properly on macOS, but not on my windows machine. Other shortcuts work.

### Release version

3.4.5 (x64)

### Operating system

Windows 11 Professional (10.0.22631 Build 10.0.22631)

### Steps to reproduce the behavior

1. Go to any repo
2. Press Ctrl + Shift + M
3. Nothing happens

### Additional context

I'm having the issue for a few months now, and I tried re-installing the app, just in case. Did not solve my issue.

**Comment by steveward** [comment]
Thanks for the report @armand-colin. I just tested this on my Windows machine and the shortcut worked as expected. Is there any chance there is another application or custom system shortcut that is overriding GitHub Desktop?
