### ISSUE TITLE
search bar for staged files in the left most pane

### ISSUE THREAD

**Issue by bturner1273** [desktop/desktop#19338]
### The feature request

it'd be super nice to be able to search changed files in the staging panel, it gets hard to find things when the commits are large

### Proposed solution

add a (ctrl/cmd + f) hotkey to search staged files

**Comment by steveward** [comment]
Thanks for the feedback @bturner1273, this is being tracked in https://github.com/desktop/desktop/issues/6407. You can follow along there for updates.
