### ISSUE TITLE
After updating, local files are gone

### ISSUE THREAD

**Issue by skalliger** [desktop/desktop#19331]
### The problem

I've been using GitHub Desktop for months for easier pushing/committing of small changes. In the latest version however, I recently started GitHub Desktop again and most of my local files are just gone. Pulling is also not working.

### Release version

3.4.5

### Operating system

Windows 10

### Steps to reproduce the behavior

I have my own public GitHub repository, where I commit to from two locations (Windows client and Linux server).
I just started my Windows client again after a week and I can't pull/sync the repository. 

### Screenshots

![image](https://github.com/user-attachments/assets/e323cb3f-ffbd-4957-8286-01fcc7c2cdf9)

**Comment by steveward** [comment]
@skalliger thanks for the issue. It looks like all those files are showing up as deleted. If you did not intend to do that you can right-click on `56 changed files` and select `Discard All Changes`. This should restore those deleted changes.

The error popup you're seeing seems like an installation issue. Could you share the full log from GitHub Desktop?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
