### ISSUE TITLE
Desktop VsCode error

### ISSUE THREAD

**Issue by toftke** [desktop/desktop#19335]
### The problem

When opening repository in VsCode from Github Desktop I get an error that doesn't open VsCode and exits out of Github Desktop.

![image](https://github.com/user-attachments/assets/99ca1e20-161c-4215-8b2b-0db82f8e93cf)

### Release version

3.4.5

### Operating system

Windows 10.0.19045

### Steps to reproduce the behavior

1. Open Github Desktop
2.  Select Repository and Branch
3.  Click open in Visual Studio Code

### Log files

[2024-09-30.desktop.production.log](https://github.com/user-attachments/files/17195567/2024-09-30.desktop.production.log)

### Screenshots

![image](https://github.com/user-attachments/assets/99ca1e20-161c-4215-8b2b-0db82f8e93cf)

**Comment by steveward** [comment]
Thanks for the issue @toftke.

Could you open the command prompt and share the output of echo `%PATH%`?

If `System32` is not in your `PATH`, you will need to edit your `PATH` by following [this article](https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/) and adding the following line:

`C:\Windows\system32`

Let me know if that doesn't get things working.

**Comment by toftke** [comment]
Yeah, echo %PATH% gives me

C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\Common Files\Oracle\Java\java8path;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\PuTTY\;C:\Users\toftk\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Users\toftk\AppData\Local\GitHubDesktop\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Users\toftk\AppData\Local\Microsoft\WindowsApps;\MinGw\bin;C:\Users\toftk\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\toftk\AppData\Local\GitHubDesktop\bin;

**Comment by toftke** [comment]
I also get the same error when trying to edit the Global Git config file

**Comment by steveward** [comment]
> I also get the same error when trying to edit the Global Git config file

Is this happening when you try to open that file in VSCode?  Does VSCode open without issue on your machine?
