### ISSUE TITLE
No Help Tutorial In GitHub Desktop.

### ISSUE THREAD

**Issue by corinthian13** [desktop/desktop#1933]
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

[Description of the issue]

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** [version here]

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behaviour:** [What you expected to happen]

**Actual behaviour:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

If you are dealing with a performance issue or regression, attaching a
[Timeline profile](https://github.com/desktop/desktop/blob/master/docs/contributing/timeline-profile.md)
of the task will help the developers understand the runtime behaviour of the
application on your machine.

**Comment by shiftkey** [comment]
@corinthian13 please fill out the issue template to help us understand your issue better.

**Comment by corinthian13** [comment]
I don't see much need for elaboration.
There simply isn't any useful guidance on how to actually use GitHub on the GitHub Desktop 'Help' menu.
I go into my installed GitHub Desktop, set up a remote repositary, set up a local repositary project, add a new file to the local proj, try all the buttons supposedly there to enable me to push the changed proj up to the GitHub remote repo - and no changes are effected.

I think we all would like to have less HYPE on GitHub and more EXPLANATION ON HOW IT WORKS ON A PRACTICAL LEVEL.

**Comment by shiftkey** [comment]
@corinthian13 we have a collection of Help guide that are accessible from the [Desktop site](https://desktop.github.com/) (but not linkable from within the app, we should make that more discoverable) - https://help.github.com/desktop-beta/guides/

Could you have a look over those and see if they help you with getting familiar with the app?

**Comment by shiftkey** [comment]
I've opened https://github.com/desktop/desktop/issues/1963 to track making it easy to navigate from the app to the User Guides, to help with discoverability.

**Comment by corinthian13** [comment]
There's a lot more wrong with the GitHub Desktop GUI than simply providing a link to the Guides pages.

For one thing, it isn't really a proper GUI.
SOME things can be done via the GUI dialogs.
But for other - often IMPORTANT- things like creating a new remote repositary or even just a special folder within an existing remote repo, the Guide pages just order us back once again to the painful old command line interface.
I just don't see any reason to create such a limited GUI for GitHub Desktop. It's not as if there were a problem with coding up a dialog box for these tasks that presently require command-line involvement.
It is costs a few bucks to hire coders to do this (and hopefully test the code too, in case GH management think the users will do all this en passant . . .) then go and hire them and ask us for $5 a head to pay them. For most of us, convenience really is worth something.

Contrarily, the set-up process involves a check through the GitHub users' email addresses to find the remote repo. This might be a help if one were storing all one's repos on one's root folder. But I expect many will want to subdivide their repos into distinct folders, e.g. portfolio (for one's own runnable projects), downloads (for stuff coded by others that a GitHub account holder may want to share), images (if you have anything that special to share), etc.
I think the layout used by most FTP clients, with local folder on the left and remote folder on the right sides of the screen  would be convenient here. Also a simple means of graphically creating new remote/local folders for projects.

I know that GitHub is an open source thing. But there is no sense in just writing software that - for all its eventual usefulness after you finally get the hang of it all - is counter-intuitive to learn and awkward to use.
