### ISSUE TITLE
Allow manually fetching from remotes other than origin

### ISSUE THREAD

**Issue by j-f1** [desktop/desktop#1934]
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

Currently, the app only allows fetching from the `origin` remote. For forked repositories, this is the fork, meaning that there is no way to update from the original repository. This could be remedied by adding a dropdown section of the button that pops up a list of remotes to fetch from. There should also be a way to change the default remote to avoid having to open the dropdown each time.

### Version

**GitHub Desktop version:** 0.5.9 (that should really be selectable so I don’t have to re-type it 🙂)

**OS version:** 10.12.3

### Steps to Reproduce

1. Open a forked repository in GitHub Desktop
1. Click the “Fetch” button to download new commits from the fork’s parent

**Expected behaviour:** The button offers a choice of which repository to fetch from

**Actual behaviour:** The button only downloads commits from the fork

**Reproduces how often:** Always

**Comment by shiftkey** [comment]
> (that should really be selectable so I don’t have to re-type it 🙂)

Oops. This is tracked in #1935

**Comment by shiftkey** [comment]
@j-f1 this was a recent change we made - see #1435 for context. Forked repositories are probably something we should revisit, but I don't think we've got any smarts yet around this.

I'll also point you to #1442 which is an open issue for us to discuss workflows involving multiple remotes.

**Comment by joshaber** [comment]
Thanks for the suggestion!

We're planning to address this more specifically by adding first-class support for forks.

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by steveward** [comment]
Removing the `future-proposal` label in favor of https://github.com/desktop/desktop/issues/1442.
