### ISSUE TITLE
GitHub Desktop tries to fetch the remote upstream of a fork

### ISSUE THREAD

**Issue by mbochmann** [desktop/desktop#19346]
### The problem

User A has access to the private repositories of organization B and forks repository R as S into organization C.
User D only has access to organization C and clones repository S.
If user D tries to fetch, GitHub Desktop tries to fetch the upstream and gets the response that the repository was not found.
GitHub Desktop only shows one remote (origin) in the repository settings.
After removing the remote upstream with the Git shell, fetching in GitHub Desktop works as expected.

### Release version

3.4.5

### Operating system

Windows 11

### Screenshots

![IMG-20241002-WA0002~2](https://github.com/user-attachments/assets/312b6624-b139-4716-ac17-d18b839e3c9a)
![IMG-20241002-WA0005~2](https://github.com/user-attachments/assets/7af042fe-dd34-4da7-8826-539a752b8261)
![IMG_20241002_180032](https://github.com/user-attachments/assets/a8fe32e5-84a9-4d87-a5b7-38db4ffb6fae)

**Comment by steveward** [comment]
Thanks for the issue @mbochmann. This is being tracked in https://github.com/desktop/desktop/issues/3715. I'll reference this issue there.
