### ISSUE TITLE
Default Local Repos Folder

### ISSUE THREAD

**Issue by gmcoates101** [desktop/desktop#19349]
### The feature request

It would be nice to be able to specify a Local Repos Folder so that when cloning a repository the app always starts from that specific folder. I think it current start in C:\Users\<name>\... which I guess is fine for some, maybe most but having that as an option would be excellent.

I looked for it, if its there and I missed it sorry about that.

### Proposed solution

Add an additional part in Settings to allow the user to specify that specific folder.

**Comment by steveward** [comment]
Thanks for the feedback @gmcoates101. The local path is "sticky", in that whatever you choose will persist to your next clone or when you create another new repository.  We are tracking feedback about the default location in https://github.com/desktop/desktop/issues/13017, so I'll add this feedback there as well.
