### ISSUE TITLE
Unable to Clone

### ISSUE THREAD

**Issue by SYAMDEV-AJ** [desktop/desktop#19357]
### The problem

When  i try to clone a repository, it shows some error. kindly resolve the issue.
I am hereby attaching the screenshot for reference.

![Screenshot (187)](https://github.com/user-attachments/assets/f573efed-e9b4-4b68-bf1f-634e03895d12)

### Release version

Version 3.4.6 (x64)

### Operating system

Windows 10 Enterprise

### Screenshots

![Uploading Screenshot (187).png…]()

**Comment by steveward** [comment]
Thanks for the issue @SYAMDEV-AJ. Some users have had also success running this command to try and prevent timeouts:

`git config --global http.postBuffer 157286400`

Let me know if that does not get things working.
