### ISSUE TITLE
Resize the push/fetch button to fit longer description texts 

### ISSUE THREAD

**Issue by lostminds** [desktop/desktop#19356]
### The feature request

The button for fetching origin and pushing to origin in the top bar is too small to fit the full detail text when doing operations that take a little time and show progress of uploads/downloads is shown in the details. So instead you just get a cut off text with ellipsis ...

![Screenshot 2024-10-07 at 09 35 34](https://github.com/user-attachments/assets/cc59e527-2c62-4e74-8159-a80028f1a627)

### Proposed solution

Make the button a little bigger, or have it resize to be bigger if the content doesn't fit.

**Comment by tidy-dev** [comment]
@lostminds Thanks for reaching out! Resizable toolbar buttons has [shipped to beta.](https://desktop.github.com/beta/). Feel free to check it out there.
