### ISSUE TITLE
Infinite Fetch

### ISSUE THREAD

**Issue by Engazan** [desktop/desktop#19365]
### The problem

Infinite Fetch

### Release version

3.4.6

### Operating system

Windows 11

### Steps to reproduce the behavior

1. add existing repo to github desktop
2. remove ssh key
3. click fetch

### Screenshots

https://github.com/user-attachments/assets/f22c82eb-0f88-4748-9ac1-44255fdc754a

### Additional context

i expect that i get prompt to add token / credentials and not infinite fetching

**Comment by steveward** [comment]
Thanks for the report @Engazan. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Engazan** [comment]
> Thanks for the report @Engazan. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

sadly there are no logs generated when i click Fetch and its infinite loading 

only logs i get is when i open github desktop but its uselesss, also it happends every day :/ i cant use githubdesktop features i need use Jetbrains IDE buttons for this ( dont want use commands )

```
2024-10-09T05:18:54.514Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-10-09T05:18:54.742Z - info: [ui] [AppStore] loading 2 repositories from store
2024-10-09T05:18:54.935Z - info: [ui] launching: 3.4.6 (Windows 10.0.22631)
2024-10-09T05:18:54.936Z - info: [ui] execPath: 'C:\Users\XXXXX\AppData\Local\GitHubDesktop\app-3.4.6\GitHubDesktop.exe'
```

**Comment by steveward** [comment]
@Engazan tested this out quickly on macOS and did not experience the issue (authentication failed dialog was shown correctly), but there are some cases where SSH can hang on Windows. Can you check to see whether `File` > `Options` > `Advanced` > `Network and credentials` > `Use system openSSH` is selected? If it is, try unsetting it to see if it changes this behavior.

**Comment by Engazan** [comment]
> @Engazan tested this out quickly on macOS and did not experience the issue (authentication failed dialog was shown correctly), but there are some cases where SSH can hang on Windows. Can you check to see whether `File` > `Options` > `Advanced` > `Network and credentials` > `Use system openSSH` is selected? If it is, try unsetting it to see if it changes this behavior.

that fixed everything for me, i disabled it and clicked fetch and all was fetched and updated :), thanks

**Comment by steveward** [comment]
Glad to hear that got things working.
