### ISSUE TITLE
Can the language be made more localized? For example, in Chinese or Japanese?

### ISSUE THREAD

**Issue by 1234567845246** [desktop/desktop#19368]
### The feature request

As the title suggests, or alternatively, provide an interface for users to organize it themselves.

### Proposed solution

Or we could follow the example of Visual Studio Code and allow users to register themselves, and I would be happy to contribute to that effort.

**Comment by steveward** [comment]
Thanks for the issue. At this time we do not have language localization in GitHub Desktop, but this is something that we would like to do in the future. I don't have a timeline for when that may happen as it would require quite a bit of work by the team. I'm sorry that I don't have better news at this time.
