### ISSUE TITLE
Switching branches does not switch and spins forever (Git-LFS)

### ISSUE THREAD

**Issue by gkoreman** [desktop/desktop#1936]
### Description

I have created a new repository using GitHub Enterprise. It includes some large files (~70mb) but overall is quite small and has very little history. It is using Git-LFS. There are two branches, master and dev.  Cloning the repository is quite fast (master doesn't include any large binary files) but switching branches to dev hangs indefinitely. The switch to branch button continues to show the rotating spinner and I see that there is a Git LFS process and multiple git for windows processes running in the background, all taking 0% cpu.
Interestingly, Git for Desktop eventually shows some files as being modified in my local environment. The current branch still shows as master, but all of the text files have been updated with the dev line changes as if they were new additions to my workspace for the master branch. None of the git-lfs files show up in my workspace.

### Version

**GitHub Desktop version:**  0.5.9
**OS version:** Windows 10

### Steps to Reproduce

1. Create a repo with no git-lfs files in master
1. Create a branch with git-lfs files
1. Clone the repository in GitHub Desktop
1. Switch from master to the new branch

**Expected behaviour:** Branch should switch from master to dev, or show an error relating to git-lfs

**Actual behaviour:** Git for desktop appeared to never complete the action and eventually polluted the master branch with files from the dev branch.

**Reproduces how often:** 100%. Tried about 10 times, cloning a new one each time.

### Logs

2017-06-08T00:39:54.937Z - error: fetchMetadata: unable to load metadata from 'https://XXXOurServerAddressXXX.com/api/v3/meta' as a fallback
TypeError: Failed to fetch

#### Additional Information

I have used Git-LFS with other git GUI's, but not with GitHub Desktop, so if there is some first time login thing that needs to happen, it isn't happening.

Cloning and switching between branches using the command line and other Git GUI's works as expected.

**Comment by shiftkey** [comment]
@gkoreman yeah, our Git LFS support isn't quite there - see #69 for the UI work and I'm pretty sure we need to some more testing on our side around the Git operations.

> Git for desktop appeared to never complete the action and eventually polluted the master branch with files from the dev branch.

If you **View** | **Toggle Developer Tools** do you see any console errors? This will help provide context to why Git isn't completing...

**Comment by shiftkey** [comment]
No point going through the steps to reproduce this, because I know we're not tailing the output of the file passed to`GIT_LFS_PROGRESS` when invoking any Git operations (see https://github.com/git-lfs/git-lfs/pull/1469 for info) which we need to do to track progress.

We have #2226 tracking that task. Please follow along with that!
