### ISSUE TITLE
Commit Input field

### ISSUE THREAD

**Issue by martinflischman** [desktop/desktop#19367]
### The feature request

Please redesign the commit input field area. It's so tiny. Even in full-screen mode, the block stays small. When there are many commits, it can be annoying to say the least to add commits.

### Proposed solution

Make it bigger - Redesign the app's UI and so doing you'll make the UX better.

**Comment by steveward** [comment]
Thanks for the issue @MartinFlischman. I'm going to add this to https://github.com/desktop/desktop/issues/1646 where we are tracking feedback around this.
