### ISSUE TITLE
No such host is known. (Port 9418)

### ISSUE THREAD

**Issue by ShafqatHaider** [desktop/desktop#19364]
### The problem

When I am publishing a branch on click the button in github desktop I find an error "fatal: unable to look up https (port 9418) (No such host is known. )"
how to resolve this

### Release version

1

### Operating system

windows 10

**Comment by steveward** [comment]
@ShafqatHaider the Git protocol uses 9418, but that is no longer in use. Can you go to `Repository` > `Repository Settings` > `Remote` and see what the URL there is? You'll want to use `https://github.com/<user>/<repo>.git`.
