### ISSUE TITLE
Kind of scary.

### ISSUE THREAD

**Issue by 743859910** [desktop/desktop#19366]
一下子更新这么多发行版.我差点还以为遭黑客攻击了呢！
So many releases at once. I almost thought I was hacked!
![Screenshot_2024-10-08-19-41-04-832_com.tencent.androidqqmail.jpg](https://github.com/user-attachments/assets/ae745493-c216-44d5-931e-6888527df7da)

![Screenshot_2024-10-08-19-41-09-957_com.tencent.androidqqmail.jpg](https://github.com/user-attachments/assets/bbb46292-4224-48de-9d20-7deb47a091a3)

![Screenshot_2024-10-08-19-41-15-909_com.tencent.androidqqmail.jpg](https://github.com/user-attachments/assets/bdb9bc13-10f5-4ba3-b49f-f34fd1778f1a)

**Comment by sergiou87** [comment]
Sorry about that! It should be done by now 😳

**Comment by DigiH** [comment]
WHF. In all my years on GitHub I've never seen such an old version release spam , and the first time this happens it is from GitHub Desktop themselves 🙄 

Off into the shame corner for some embarrassment contemplation! 😜 

Unsubsribing, just to be on the safe side.
