### ISSUE TITLE
About download

### ISSUE THREAD

**Issue by Icicle-Yang** [desktop/desktop#19392]
### The problem

I couldn't download the desktop github

### Release version

All of them

### Operating system

Macos

**Comment by niik** [comment]
Hi @Icicle-Yang, thanks for reaching out. Unfortunately there's not nearly enough information in your issue for us to be able to help you. I'm going to close this issue but if you're still experiencing problems downloading GitHub Desktop please open a new issue and add plenty of detail around what you're experiencing, any error messages you might be encountering, what you've tried so far and preferably add some screenshots as well to help us help you.
