### ISSUE TITLE
Como usar

### ISSUE THREAD

**Issue by jarah2** [desktop/desktop#19394]
Olá sou meio leigo nesse ramo, gostaria de saber se poderiam fazer um vídeo demostrativo de como usar, se for possivel desde ja agradeço

**Comment by niik** [comment]
Olá, obrigado por entrar em contato!

Há vários vídeos tutoriais no YouTube feitos por meus usuários do GitHub Desktop. Quanto aos vídeos oficiais, veja esta visão geral de alto nível do que é o GitHub Desktop: https://www.youtube.com/watch?v=l7uo1d3R0Wo. Você também pode ver esta apresentação do GitHub universe 2022 mostrando alguns dos recursos do GitHub Desktop: https://www.youtube.com/watch?v=qUYkRWGWntE.

Veja também este pequeno vídeo demonstrando como fazer commit de código usando o GitHub Desktop: https://www.youtube.com/watch?v=SSunLwWSNjU.

Por fim, visite nosso site de documentação que existe em várias versões traduzidas: https://docs.github.com/pt/desktop.

Espero que ajude!
