### ISSUE TITLE
Support basic Markdown in commit messages

### ISSUE THREAD

**Issue by Desoroxxx** [desktop/desktop#19393]
### The feature request

GitHub supports parts of markdown in commit messages, it would be great if GitHub desktop did the same.

### Proposed solution

Here is how it looks in GitHub desktop:
![image](https://github.com/user-attachments/assets/a3797760-3db2-4cdf-9d2d-972f3095d2d1)

Here is how it looks on GitHub:
![image](https://github.com/user-attachments/assets/1a523b41-b629-4657-985c-4ce1cd4829e5)

**Comment by niik** [comment]
Hey, thanks for reaching out! This looks very similar to the request in https://github.com/desktop/desktop/issues/18104 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date with any development happening in that area.
