### ISSUE TITLE
text completely blurry and unreadable in version 3.4.6

### ISSUE THREAD

**Issue by Ruth-R-Kelly** [desktop/desktop#19391]
### The problem

Hi, 
I am having difficulties with version 3.4.6 on windows 10 pro - 64bit OS. 
The text shows up unreadable on most tabs (see image).  

I have tried using an older version 3.4.0 - which works fine. But then seems to automatically update to 3.4.6 and stop working correctly again.  

Any advice? Many thanks, 

Ruth
![github_desktop](https://github.com/user-attachments/assets/11b313c0-eabd-4dc8-a2bf-cee6e5d3857e)

### Release version

3.4.6

### Operating system

Windows 10 pro

**Comment by Sahar21170** [comment]
@cosmorama

**Comment by niik** [comment]
Hi @Sahar21170, thanks for reaching out. Looks like something odd is going on either with your graphics card drivers or the graphics card itself. Have you rebooted your machine recently?

You can try launching GitHub Desktop with GPU accelerated rendering turned off to verify that it is indeed related to the GPU  by setting the GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION environment variable to 1 by running `set GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1` in cmd.exe and restarting your machine or by setting it through the UI following a guide like this: https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0

Note that you may have to restart your machine for the changes to take effect.

Please also make sure that you're using the latest version of your graphics driver.

**Comment by niik** [comment]
@Ruth-R-Kelly We got a report in https://github.com/desktop/desktop/issues/19397#issuecomment-2411213519 that suggests disabling Nvidia's global antialiasing:

> The issue was caused by Nvidia's global Antialiasing settings—specifically, the FXAA and Multi-Frame Sampled AA (MFAA) options being turned on. Restoring the default values resolved the blurred UI and font issue. @niik thanks for the help, disabling the GPU was another solution, that worked in the case of the VSCode.

Perhaps that's something you could try as well?
