### ISSUE TITLE
Blured / unreadable UI

### ISSUE THREAD

**Issue by jacekroszkowiakdev** [desktop/desktop#19397]
### The problem

Windows 11 has nVidia/Intel graphics and two screens; the UI is blurred and unreadable. 

### Release version

3.3.14 (x64)

### Operating system

Windows 11

### Screenshots

![github desktop](https://github.com/user-attachments/assets/1c212fee-9e27-4342-ac0d-1464621ffce4)

**Comment by niik** [comment]
Hi @jacekroszkowiakdev, thanks for reaching out. Looks like something odd is going on either with your graphics card drivers or the graphics card itself. Have you rebooted your machine recently?

You can try launching GitHub Desktop with GPU accelerated rendering turned off to verify that it is indeed related to the GPU  by setting the GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION environment variable to 1 by running `set GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1` in cmd.exe and restarting your machine or by setting it through the UI following a guide like this: https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0

Note that you may have to restart your machine for the changes to take effect.

Please also make sure that you're using the latest version of your graphics driver.

**Comment by jacekroszkowiakdev** [comment]
@niik Thank you for the prompt response. All drivers are up to date, as well as Windows 11. I'm using a Lenovo Legion laptop with an RTX 3700 and Intel Arc, connected and two screens. The external monitor, connected via HDMI, shows more (extreme) blurriness compared to the laptop screen. The laptop's screen resolution is 2560x1600, while the external monitor's is 1920x1080. Several other Electron-based apps also have this issue, though I was only able to fix it in VSCode. I'll try the guide and share my results here.

**Comment by jacekroszkowiakdev** [comment]
The issue was caused by Nvidia's global Antialiasing settings—specifically, the FXAA and Multi-Frame Sampled AA (MFAA) options being turned on. Restoring the default values resolved the blurred UI and font issue. @niik thanks for the help, disabling the GPU was another solution, that worked in the case of the VSCode.

**Comment by niik** [comment]
@jacekroszkowiakdev Thanks for reporting back, that context is really helpful and something we can pass on to others experiencing similar issues!
