### ISSUE TITLE
Repo fails to load if output of status is > 20MB

### ISSUE THREAD

**Issue by kristiangerkman** [desktop/desktop#19405]
Just deleted **bunch** of csv files locally and now my repo wont load

it just fails silently* on this screen (*there is error in the developer console)

![gitdeskerr](https://github.com/user-attachments/assets/debf3fec-95a2-45ac-89a8-ba6f064fb4e2)

https://github.com/desktop/desktop/blob/9e8f058b6fd26180e93f254575cd93d091095dec/app/src/lib/git/status.ts#L32-L38
https://github.com/desktop/desktop/blob/9e8f058b6fd26180e93f254575cd93d091095dec/app/src/lib/git/status.ts#L219-L224

I get that this is very unusual situation, but IMO some sort of "couldn't load git status" just like VSCode has (small popup) would be nice, instead of silent death

**Comment by steveward** [comment]
Thanks for the issue @kristiangerkman. This is being tracked in https://github.com/desktop/desktop/issues/19405, and is something that we're planning to address. I'm going to close this out and reference it in the issue I linked.
