### ISSUE TITLE
.gitignore files shows in "changed files" list

### ISSUE THREAD

**Issue by NilsSve** [desktop/desktop#19409]
### The problem

Why is files that have been added to .gitignore file keep popping up in the "changed files" list in the GitHub Desktop app?

### Release version

3.4.6

### Operating system

Windows 10 & 11 Pro

### Steps to reproduce the behavior

none needed

**Comment by steveward** [comment]
@NilsSve if a file has been previously committed you will need to run the following command to ignore the file in Git:

`git rm --cached <file>`

See [this article](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files) for more information.
