### ISSUE TITLE
Provide "ignore whitespace" option when viewing diff

### ISSUE THREAD

**Issue by christophfriedrich** [desktop/desktop#1940]
### Description

There should be an option to ignore whitespace changes when comparing file versions in the diff view.

### Version

**GitHub Desktop version:** Chocolate-Covered Yaks (3.3.4.0) 50415df

**OS version:** Microsoft Windows [Version 10.0.14393]

### Steps to Reproduce

1. Look at a diff
1. Notice you didn't actually change much in that file, just added/removed some linebreaks etc.
1. Feel the need to ignore those uninteresting changes
1. Note that there's no option for this very basic diffing task

**Expected behaviour:** Have checkbox "ignore whitespace" that, when checked, causes the diff view to show "real" changes only

**Actual behaviour:** No such checkbox

**Reproduces how often:** 100%

#### Additional Information

Despite intensive googling I couldn't find any info whether such an option exists, so I assume it doesn't. It would be a VERY handy feature.

**Comment by shiftkey** [comment]
This is really tricky to set up with vanilla Git - [this](https://stackoverflow.com/a/33159593/1363815) seems to be the best guide, but I've not tried it myself to confirm that it still works - but if someone else wants to dig into that and find their setup we can then chat about how possible it would be to plug into Desktop itself.

One warning: by hiding the whitespace in diffs you remove the ability to partially commit files. I want to tread lightly here with any changes to how diffs work, and things like #1499 and #173 are features from the existing apps that we should address first.

**Comment by christophfriedrich** [comment]
Other git GUIs have this option - I regularly change over to GitKraken when I need to check there was nothing but whitespace changed and switch back to Desktop once I confirmed that.

I don't get why hiding whitespace should restrict partial committing -- staging line 15 will still stage line 15, no matter whether line 10 has been excluded or not. At least that's what I'm thinking, but then again I'm absolutely no git expert...

**Comment by shiftkey** [comment]
> I don't get why hiding whitespace should restrict partial committing -- staging line 15 will still stage line 15, no matter whether line 10 has been excluded or not. At least that's what I'm thinking, but then again I'm absolutely no git expert...

In Desktop at least the diff that you see in the UI is the same one that we then go and apply to Git. It should be fine, but as someone who has been involved with implementing hunk commits twice on two different platforms, I'm just nervous about breaking things. 

Anyway, here's a quick example experimenting with this on the command line - this is how we'd enable this for Desktop:

```diff
$ git diff   
diff --git a/app/src/ui/repository-settings/repository-settings.tsx b/app/src/ui/repository-settings/repository-settings.tsx
index 0bc39e0ba..549633641 100644
--- a/app/src/ui/repository-settings/repository-settings.tsx
+++ b/app/src/ui/repository-settings/repository-settings.tsx
@@ -98,10 +98,11 @@ export class RepositorySettings extends React.Component<IRepositorySettingsProps
     if (tab !== RepositorySettingsTab.Remote) { return null }
 
     const remote = this.state.remote
-    if (!remote) { return null }
+    if (!remote) { return null      }
 
     const disabled = remote.url.length === 0
 
+    hello
     return (
       <DialogFooter>
         <ButtonGroup>
(END)
```

And here's what happens when you add `-w` which seems to be good enough. I'm not sure if there's other flags that users want.

```diff
$ git diff -w
diff --git a/app/src/ui/repository-settings/repository-settings.tsx b/app/src/ui/repository-settings/repository-settings.tsx
index 0bc39e0ba..549633641 100644
--- a/app/src/ui/repository-settings/repository-settings.tsx
+++ b/app/src/ui/repository-settings/repository-settings.tsx
@@ -102,6 +102,7 @@ export class RepositorySettings extends React.Component<IRepositorySettingsProps
 
     const disabled = remote.url.length === 0
 
+    hello
     return (
       <DialogFooter>
         <ButtonGroup>
```

And even after enabling that, there's some things we'd need to think about around the UX of this feature:

  - does this become a preference that users opt-in for? Or do they just want this to be enabled this when looking at a file? Or both? 
  - when the user has enabled ignoring whitespace and a file only has whitespace changes left, what do we show to the user?

**Comment by christophfriedrich** [comment]
Your example looks like you concentrated on whitespace within a line. While that's handy too, I'd (personally) primarily use this feature to ignore indentation changes and new line insertions/deletions (the kind of things you do when you cleanup someone else's code).

In this screenshot for example, I'd mostly want that the tool disregards the indentation of `return "asdf";` and the removal of the original line 4:

![git ignore whitespace ux with checkbox - code only](https://user-images.githubusercontent.com/17781682/27512390-7592ac2a-593e-11e7-90ab-69bc4ec3781e.png)

But yeah, ignoring that the curly bracket `{` was moved to the end of the previous line would be nice too. So in fact, this whole diff would be "empty".

---

As for the UX, this should definitely be opt-in (otherwise users will be confused because they don't get the results they expect) and this should be available when reviewing the changes done to a file. I'd propose a checkbox labelled "ignore whitespace changes" to be placed somewhere in the "changes" tab. This option MUST NOT be placed in the general options - to me it's a feature I'd use "on demand" for a minute or so and then return to "normal" view.

One suiting place would be in the file name header, see screenshot mockup:
![git ignore whitespace ux with checkbox](https://user-images.githubusercontent.com/17781682/27512297-3ceb1eb8-593c-11e7-82f7-82d94a7936db.png)

Alternatively, you could introduce a toolbar (but that only makes sense when there's more than just that checkbox to display down there)
![git ignore whitespace ux with checkbox v2](https://user-images.githubusercontent.com/17781682/27512424-6f2913d2-593f-11e7-9d75-d1a3557fa75f.png)

If there's nothing but whitespace changes, I'd tell the user just that:
![git ignore whitespace ux with checkbox v3](https://user-images.githubusercontent.com/17781682/27512383-3a563294-593e-11e7-8c5f-4cb7cdfd716c.png)

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by jcf120** [comment]
I'd also like to this diff view under 'History'.

**Comment by andrei-pokrovsky** [comment]
I'd like to propose to reopen because it seems quite important :)

**Comment by bigjosh** [comment]
I ended up dropping out of the GUI and looking at the commit on github.com with `?w=1`  appended to the end of the URL. Would be great to also have this checkbox in the GUI.

**Comment by xt0rted** [comment]
Now that this is a first class feature on the website could it be reconsidered for the desktop client? All I'd like is an option to toggle ignoring whitespace, I don't care about doing partial commits with it on. I just want a way to see what's been changed before pushing and without needing to drop to the command line and doing `git diff -b somefile`.

**Comment by shiftkey** [comment]
@xt0rted I'm happy to move this to `help wanted` if someone wants to take a shot at getting this working and opening a PR, and we can noodle on the UX later.

**Comment by xt0rted** [comment]
@shiftkey what option(s) most closely matches the functionality of the website?

**--ignore-space-at-eol**
Ignore changes in whitespace at EOL.

**-b
--ignore-space-change**
Ignore changes in amount of whitespace. This ignores whitespace at line end, and considers all other sequences of one or more whitespace characters to be equivalent.

**-w
--ignore-all-space**
Ignore whitespace when comparing lines. This ignores differences even if one line has whitespace where the other line has none.

**--ignore-blank-lines**
Ignore changes whose lines are all blank.

**Comment by j-f1** [comment]
@xt0rted I’m going to guess that the answer is `-w` since the query parameter is `w`.

**Comment by shiftkey** [comment]
@xt0rted I'd have to go back through the archives to confirm but let's do `-w` for now. We can revisit later if we find it's not accurate.

**Comment by shiftkey** [comment]
@xt0rted I think the component which hosts the checkbox needs to invoke a new function on the dispatcher (like `dispatcher.setIgnoreWhitespaceForDiff()`) which then updates the application state and re-renders the diff using the current setting. But happy to look at a starting PR and take it from there.

**Comment by roger-wernersson** [comment]
How did it go? I'm considering creating a Tamper Monkey script to do it for me locally.

**Comment by say25** [comment]
Interested in taking this on. I got it working more or less. 

<img width="1920" alt="screen shot 2018-11-29 at 7 12 53 am" src="https://user-images.githubusercontent.com/7467062/49224220-7356f700-f3a6-11e8-991a-8edf008c0889.png">

Not sure about the UI/UX though, especially on the changes tab.
Maybe it would go next to the file status symbol? @desktop/design 

<img width="958" alt="screen shot 2018-11-29 at 7 14 20 am" src="https://user-images.githubusercontent.com/7467062/49224252-8b2e7b00-f3a6-11e8-96ee-9c39bd348c53.png">

**Comment by arpan34** [comment]
Can someone please help me with this query: How do I enable "Ignore whitespace for conflicts" via API?

**Comment by robertdeml** [comment]
The "Hide whitespace changes" checkbox is in the settings gear in the upper right-hand side of the diff windows.
