### ISSUE TITLE
Open in GitHub Desktop

### ISSUE THREAD

**Issue by okunamayanad** [desktop/desktop#19406]
### The feature request

A Windows Explorer context menu item for easy access to GitHub Desktop.

Instead of opening the app, press add, add existing repository, locate the folder
just click Open in GitHub Desktop

### Proposed solution

Open in GitHub Desktop context menu item for Windows Explorer, much like;
- Open in Terminal
- Open in Visual Studio
- Open in Git GUI
- Open PowerShell window here
- Open Linux shell here

### Additional context

![image](https://github.com/user-attachments/assets/1a66710d-9633-4be4-aa1e-3493c9508748)

**Comment by niik** [comment]
Hey, thanks for reaching out! This looks very similar to the request in https://github.com/desktop/desktop/issues/5373 so I'm going to close this issue in favor of that. Please subscribe to it to stay up to date with any development happening in that area.

**Comment by okunamayanad** [comment]
How did I miss that one?
Searched for a lot of issues and checked 50~ issues and I miss the one I'm interested in 😅

**Comment by Khanzada1111** [comment]
The text was updated successfully, but these errors were encountered:

**Comment by Khanzada1111** [comment]
The text was updated successfully, but these errors were encountered:

**Comment by Khanzada1111** [comment]
The text was updated successfully, but these errors were encountered:
