### ISSUE TITLE
The new version is very slow

### ISSUE THREAD

**Issue by ZhangHuan0407** [desktop/desktop#19416]
### The problem

GitHub Desktop automatically updated to a new version, but this version is very slow.
This version had some serious framerate drops when I merged in a few pending commits, and was performing much slower than previous older versions.

After you check the date, if it is my problem, please tell me how to try to solve it. It is too stuck at the moment.

### Release version

Version 3.4.6 (x64) 

### Operating system

Windows11

### Log files

[2024-10-17.desktop.production.log](https://github.com/user-attachments/files/17416496/2024-10-17.desktop.production.log)

**Comment by steveward** [comment]
@ZhangHuan0407 thanks for the issue. We've often seen performance issues caused by antivirus software. Are you running any antivirus or other security software on your machine that could be causing this?

**Comment by ZhangHuan0407** [comment]
Yes, I use this antivirus.
www.huorong.cn

But the "real-time file monitoring" function was turned off a long time ago.
![image](https://github.com/user-attachments/assets/2e9e7f7c-3134-47e6-b4d6-8778c50fe90a)

**Comment by steveward** [comment]
Thanks for sharing that. If possible I would recommend trying to temporarily disable it completely to see if it makes any difference. I see a background fetch that is taking a while to complete:

```
2024-10-17T17:07:22.376Z - info: [ui] Opt out reported.
2024-10-17T17:07:23.513Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 29 repositories took 134.6s of which 13.4s paused, total 148.0s
```

You could try disabling this functionality (`File` > `Options` > `Advanced` > `Show status icons...`) to see if it helps at all with this issue as well. Let me know how that goes.

**Comment by ZhangHuan0407** [comment]
Looking at the description of this option, is it trying to fetch all repositories?
I cloned a lot of large repositories, unreal engine, godot, unity reference and so on.
This computer was not used for the last month, and then the github desktop was very stuck.

When was this option added? It shouldn't be turned on by default, right?

**Comment by steveward** [comment]
It fetches in the background to show indicators in the repository list and to keep your repositories up-to-date. If you had large repositories with a large number of changes to pull it could definitely have caused some slowdown due to long-running operations. This option is turned on by default since most users have less than five repositories and won't encounter this issue, but I'll make note of this feedback. Let me know if I can help with anything else.

**Comment by ZhangHuan0407** [comment]
After turning off this switch, the running speed of github desktop has returned to normal in the past two days. Thank you.
