### ISSUE TITLE
Github Dektop doesn't allow me to push commits

### ISSUE THREAD

**Issue by VasluianI0n** [desktop/desktop#19410]
### The problem

After connecting a secondary account to this account, I can't push anything from github desktop, while still being able to do it from git bash

### Release version

3.4.6 

### Operating system

Windows

### Steps to reproduce the behavior

1. Make a local repository of an already existing git repo with an account that doesn't have a secondary account attached
2. Make some changes to the repo
3. Add a secondary account to the github account
4. Commit the changes made and try to push them
You should get an error as written here:
![image](https://github.com/user-attachments/assets/c787db86-2c01-434f-a365-413b03ff7b0d)

### Log files

[2024-10-17.desktop.production.log](https://github.com/user-attachments/files/17411388/2024-10-17.desktop.production.log)

### Screenshots

![image](https://github.com/user-attachments/assets/5d4f048d-fb8f-4824-bd90-bf16a0c24c0d)

**Comment by steveward** [comment]
@VasluianI0n thanks for the report. It looks like you are using WSL. Can you share a few more details about your setup and how you are storing repositories? Are you using any hooks with this repository as well?

**Comment by VasluianI0n** [comment]
Hi, @steveward . I have WSL only installed, I am not using it in any kind of way. I am storing repositories locally in "Documents" folder, the usual process, so there shouldn't be any problem I guess..?

**Comment by VasluianI0n** [comment]
And as far as I know, no, I am not using any hooks with the repository. I tried with any repository to do it, but it doesn't work

**Comment by steveward** [comment]
You mentioned this above:

>After connecting a secondary account to this account, 

Can you clarify what you did here? Logging out of GitHub Desktop and then logging in with a different GitHub account should not cause an issue like this.

**Comment by VasluianI0n** [comment]
I did nothing more than just connecting a secondary account. By that I didn't mean logging out of one account and logging in with another. By that I meant going to settings and adding a secondary account in case your account gets lost, to be able to recover the account through another email

**Comment by steveward** [comment]
Adding a second account would not cause this error. Unfortunately this seems like a system configuration issue, which will be difficult for us to diagnose.l

Can you try to create a new user account on this machine and installing GitHub Desktop there to see if you are able to reproduce this issue? You could also try restoring your system to a known point when GitHub Desktop worked (if possible).

I would also try disabling WSL to see if that makes a difference.
