### ISSUE TITLE
Handle ANSI colour codes in error output

### ISSUE THREAD

**Issue by NashJames** [desktop/desktop#19415]
### The problem

Error output from pre-commit hooks has become unreadable due to ANSI colour codes. Please support them in your error modal.

It would also be great if you could widen the modal!

### Release version

3.4.6

### Operating system

MacOS 14.6.1

### Screenshots

![Screenshot 2024-10-17 at 17 48 02](https://github.com/user-attachments/assets/a3241896-42b7-4167-a82b-ae77ae41bcbe)
![Screenshot 2024-10-17 at 17 58 15](https://github.com/user-attachments/assets/a99c85d9-653c-4eb0-b163-d1c59cbaad3f)

### Additional context

I've been using desktop for a few years and generally love the experience!

This has been the only thing repeatedly bothering me with the app for a long time. I hadn't reported it before as I always assumed it was on your radar and the fix would come eventually. I know there are a few existing issues for the output of pre-commit hooks but I'm really hoping this is an easy fix. It would save me a lot of time running tests again in a separate terminal just to read the output.

Thanks!

**Comment by steveward** [comment]
Thanks for the report @NashJames! I'm going to group this into https://github.com/desktop/desktop/issues/18547.
