### ISSUE TITLE
Wrong branch creation time

### ISSUE THREAD

**Issue by DanielSvoboda** [desktop/desktop#19414]
### The problem

I just created the branch and it shows an 8 hour difference on 'Github Desktop'.
My time zone is GMT-3 . In Windows settings my time zone is `(UTC-03:00) Brasilia`
The branch was created via the browser: https://github.com/user/repository/branches

in the browser, on the same screen where it was created, it appears correctly in time, only on Github Desktop it is wrong.

### Release version

Version 3.4.6 (x64)

### Operating system

Windows 10 22H2 19045.5011

### Steps to reproduce the behavior

1. Access the website: https://github.com/user/repository/branches
2. Click on 'New branch'
3. Write the name of the branch
4. Click on 'New Branch'
5. Open the 'Github Desktop'
6. Click on the 'Current branch' button
7. Search for the created branch
8. Look at the time on the side, it's wrong for me.

### Log files

[2024-10-17.desktop.production.log](https://github.com/user-attachments/files/17416233/2024-10-17.desktop.production.log)

### Screenshots

![image](https://github.com/user-attachments/assets/5c13d772-0334-4c42-9018-a1b162c372b5)

**Comment by steveward** [comment]
@DanielSvoboda thanks for the issue. That timestamp is not the branch creation time, it's the time of the most recent commit made to the branch. When you create a branch that timestamp will be the time of whatever the most recent commit on the parent branch was. I hope that helps.
