### ISSUE TITLE
github desktop re-adds the code back in the local file after i try to discard it

### ISSUE THREAD

**Issue by maiovaio** [desktop/desktop#19421]
### The problem

github desktop re-adds the code back in the local file after i try to discard it and i don't know why it happens

https://github.com/user-attachments/assets/ab4ba818-9fb8-4c0f-a694-978a656ee9fc

### Release version

3.4.6 (x64)

### Operating system

Windows 11 23H2 (OS Build 22361.4317) 64bit

### Steps to reproduce the behavior

1. remove some lines of code and save 2. go to github desktop 3. discard a change

### Additional context

i am using auto-save every time the vscode window loses focus

**Comment by steveward** [comment]
Thanks for the report @maiovaio. I wasn't able to reproduce this -- are you able to consistently reproduce this across multiple repositories?
