### ISSUE TITLE
GitHub Desktop crash when open another branch

### ISSUE THREAD

**Issue by wahyudiZulhaidar** [desktop/desktop#19425]
### The problem

Problem when switching branch and open it with IDE Android Studio

### Release version

Version 3.4.6 (x64)

### Operating system

Edisi	Windows 11 Home Single Language Versi	23H2 Diinstal di	‎27/‎02/‎2023 Build OS	22631.4317 Pengalaman	Windows Feature Experience Pack 1000.22700.1041.0

### Steps to reproduce the behavior

For example we have two branch with different code (main (work on)/ master(original code))

1. On main branch move to master branch
2. After that, open it with the default IDE from Github Desktop
3. Crash

### Log files

Error: spawn C:\Program Files\Android\Android Studio\bin\studio64.exe EACCES
    at __node_internal_captureLargerStackTrace (node:internal/errors:563:5)
    at __node_internal_errnoException (node:internal/errors:690:12)
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Version: 3.4.6
OS: Windows 10.0.22631

### Screenshots

This is the master branch, I want to open it on IDE
![Screenshot (332)](https://github.com/user-attachments/assets/414aca15-299d-4884-b5d7-c40a70883d4d)

This is the main branch that my code works on
![Screenshot (333)](https://github.com/user-attachments/assets/af38f6ed-04f4-4894-9dc6-449fef44024f)

### Additional context

Its normal when I open it on intelliJ, and for Android Studio I set it to Run With Administrator by default

**Comment by steveward** [comment]
Thanks for the report @wahyudizulhaidar. Have you previously been able to open Android Studio from GitHub Desktop without issue? We've had a few varying reports of EACCES errors, but unfortunately they seem to have a variety of causes (one user had to install a KB update and it was resolved, for instance).

**Comment by wahyudiZulhaidar** [comment]
Previously I have no problem to open Android Studio directly on GitHub Desktop, I think this problem appears when I set Android Studio to run as administrator by default

**Comment by steveward** [comment]
Thanks, I'll take a look and see if I can reproduce this as well.

**Comment by steveward** [comment]
@wahyudizulhaidar I set Android Studio to run as admin and was unable to reproduce the crash (I'm also on the same version of Windows 11 as you). Can you see if anything shows up in `Event Viewer` in the `Application` logs that could give a better idea of what's causing this?
