### ISSUE TITLE
allow configuration of multiple external editors

### ISSUE THREAD

**Issue by dkocich** [desktop/desktop#19422]
### The feature request

I have tens of projects; for some simpler edits I sometimes want to open something more lightweight like vscode, next time I want to use Idea, webstorm or android studio... reconfiguring external editor each time is waste of time so I rather sometimes not use Github desktop at all and in the end and open IDe separately elsewhere

### Proposed solution

allow multiselect in settings
![image](https://github.com/user-attachments/assets/6a8000cd-11a7-411e-8b30-8308dc8e802b)

then show multiple buttons here
![image](https://github.com/user-attachments/assets/066ce918-8ecf-4707-adba-99577ee14889)

**Comment by steveward** [comment]
Thanks for the feedback @dkocich. We are tracking the option to set a default editor on a per-repository basis in https://github.com/desktop/desktop/issues/12195, so you can follow along there for updates. I'm going to close this out.
