### ISSUE TITLE
Unable to push codes. 

### ISSUE THREAD

**Issue by raunakjha23** [desktop/desktop#19428]
### The problem

Hi I am not able to push codes. Everytime i try to push, i get this- Uploading LFS objects:   0% (0/1), 0 B | 0 B/s, done.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to push some refs to 'https://github.com/PaymentsAndGovernanceResearchProgram/odpdshfm.git'. NBut my coworkers arent facing this issue.

### Release version

Version 3.4.6 (x64

### Operating system

windows 10

**Comment by steveward** [comment]
> But my coworkers arent facing this issue.

Are they pushing to the same repository? You can see how to check data quotas in [this help article](https://docs.github.com/en/billing/managing-billing-for-your-products/managing-billing-for-git-large-file-storage/viewing-your-git-large-file-storage-usage).

Unfortunately we are not able to assist with Git LFS quota issues, so I'd recommend reaching out to [GitHub Support](https://support.github.com/) for further assistance.
