### ISSUE TITLE
Please stop asking my location

### ISSUE THREAD

**Issue by kakuiho** [desktop/desktop#19427]
### The problem

Github Desktop keep asking my location since Version 3.4.6 (x64) on Windows,
Please stop asking my location, I'm an EU citizen and feel uncomfortable about it.

**It seems that after Windows 11 is updated to 24H2**, all applications will pop up a prompt by default when they are started for the first time: "Do you want to allow this application to obtain GPS or Wifi location?"

### Release version

3.4.6

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Upgrade Github Desktop version to 3.4.6 (x64) ;
2. Clone any repository;
3. Open it.

**Comment by steveward** [comment]
@kakuiho GitHub Desktop doesn't use location data. Are you sure these are coming from GitHub Desktop? I don't have 24h2 yet, so I'm unable to reproduce this. 

Based on the Windows docs, it looks like you should be able to disable these prompts:

![Image](https://github.com/user-attachments/assets/f80225a0-6490-42f7-a834-1d47c1bec0bb)

**Comment by kakuiho** [comment]
I'm sure it's Windows issue. Please ignore and close this.
