### ISSUE TITLE
commit issue

### ISSUE THREAD

**Issue by mohsinyousuf12** [desktop/desktop#19438]
### The problem

Hi 
i am using github Desktop and i am facing an inconsistency issue while commit.
when i commit i still see the files in my uncommit/changes list, it seems commit not working and then i commit again then i will show there is no files.
  

### Release version

Version 3.4.6 (arm64)

### Operating system

Mac Os Ventura 13.4

### Steps to reproduce the behavior

when i commit i still see the files in my uncommit/changes list, it seems commit not working and then i commit again then i will show there is no files.

**Comment by sergiou87** [comment]
That's weird… could you record a video of that behavior? 🤔

**Comment by tilemanrenovations** [comment]
Will this effect mobile performance?

Get Outlook.vip for iOS<https://aka.ms/o0ukef>
________________________________
