### ISSUE TITLE
Error Fatal: refusing to merge unrelated history

### ISSUE THREAD

**Issue by DrAugustine1981** [desktop/desktop#1943]
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

[I am using Git Desktop and added files to a remote repository. I added a description, click commut but at the top right I see a "Pull Origin" Tab. When I click on it gives "Error- fatal: refusing to merge unrelated history. I check on my files if it was uploaded in my GitHub repository online and it wasn't.  Can you help me fix this problem?]

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** [Desktop Beta]

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** [Windows 10 Pro]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behaviour:** [I want to sync files to my GitHub repository online using the GitHub Desktop]

**Actual behaviour:** [Sync tab is not appearing but "Pull Origin" Tab appears and gives me error when clicked]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

If you are dealing with a performance issue or regression, attaching a
[Timeline profile](https://github.com/desktop/desktop/blob/master/docs/contributing/timeline-profile.md)
of the task will help the developers understand the runtime behaviour of the
application on your machine.

**Comment by shiftkey** [comment]
@DrAugustine1981 thanks for this - we're tracking this in #1484 and I need to surface this error properly in `dugite` first https://github.com/desktop/dugite/issues/93
