### ISSUE TITLE
tag / release

### ISSUE THREAD

**Issue by DianaCruzTejada** [desktop/desktop#19436]
I would like to do a realease to create a doi in zenodo but is not possible! there is no field to write the tag version. What could I do?

**Comment by steveward** [comment]
@DianaCruzTejada are you looking for support with GitHub Desktop? It sounds like you may be looking for help with a different project hosted on GitHub.

You can create a tag in GitHub Desktop by right-clicking on a commit in the `History` view and selecting `Create Tag...`.

**Comment by DianaCruzTejada** [comment]
actually I can't find the option in Github desktop and in the interface there is no tag name field.
