### ISSUE TITLE
"Open branch with GitHub Desktop" opens but doesn't checkout

### ISSUE THREAD

**Issue by mihkelvaher** [desktop/desktop#19431]
### The problem

GitHub links open GitHub Desktop, but Desktop isn't checking out to the selected branch.

There is connection between the remote repo and GitHub Desktop because I can manually fetch and choose the created/selected branch from the dropdown.

Same issue with both Chrome and Firefox.

Best guess is that something goes wrong parsing the arguments or they just get omitted. I remember this working in the beginning of the year (Feb-Mar?).

### Release version

3.4.6 (arm64)

### Operating system

OSX 14.5 (M2)

### Steps to reproduce the behavior

In GitHub Projects when creating an entry to the kanban board and after opening it and converting into an issue, there is a section "Development" under which is 
`Create a branch for this issue or link a pull request.`
after which opens a modal with several options including `Open branch with GitHub Desktop`
Click `Create branch`
**GitHub Desktop opens, branch doesn't get checked out**

A similar place is in the repo's main page
* From Code tab > Select another branch > Green `Code` button > `Open with GitHub Desktop`
**GitHub Desktop opens, branch doesn't get checked out**

### Log files

Didn't see anything getting logged.

**Comment by sergiou87** [comment]
Thank you for your report 💖  I see how the website is generating the wrong URL.

Instead of `x-github-client://openRepo/https://github.com/sergiou87/my-repo?branch=my-branch` it's doing `x-github-client://openRepo/https://github.com/sergiou87/my-repo?my-branch` so Desktop can't parse it. Nice catch!

Did it use to open the current branch from the green `Code` button in the repo's main page? 🤔 I can't recall that behavior

**Comment by mihkelvaher** [comment]
> Did it use to open the current branch from the green `Code` button in the repo's main page? 🤔 I can't recall that behavior

Honestly, I can't remember 😅 As mentioned, it broke in the beginning of the year with some larger changes and I *think* there were some other places where it broke. Maybe you can search for `?branch=` (now or from some commit from Jan)? Either way I'd be happy if only the flow from kanban gets fixed.

Green `Code` button - when coming from a connected issue to a specific branch on the Code tab, the button text "Open with GitHub Desktop" makes me think that it'll open the repo from that branch. I know it's the same thing as landing on the repo the first time and immediately hitting `Code`, but it feels different, if that makes sense 😅

**Comment by sergiou87** [comment]
I think you're right @mihkelvaher ! I've submitted a fix to our website that should include the branch in all scenarios described 🤞 I'll let you know when the fix is deployed.

Thank you again for your help! 🙇‍♂

**Comment by sergiou87** [comment]
@mihkelvaher Please give it a try now, my fix was deployed a few minutes ago. Let me know if it still doesn't work somewhere 🤞

**Comment by mihkelvaher** [comment]
Works! 🎉
Both from kanban and green `Code`.
Thank you @sergiou87 🚀
