### ISSUE TITLE
Turn off autofetch

### ISSUE THREAD

**Issue by zkratt** [desktop/desktop#19445]
### The feature request

So, I have Git Desktop, and I cannot find anywhere how to disable autofetch.
Now I'm sitting here with 33GB worth of repository history that is completely irrelevant to me.
Even if I close the app down and manually delete it, the app periodically downloads it right back anyway.
I don't want this, I want my disk space back.

### Proposed solution

Just a simple checkbox to turn this feature off, for those of us who aren't interrested in using this feature, and could use those 33 GB for something more useful.

**Comment by zkratt** [comment]
I mean, until this can get resolved, I guess I'll just have to use a third party application for this but...

**Comment by niik** [comment]
Hey @zkratt, sorry to hear you're having issues with background fetching. We have an issue open for this at https://github.com/desktop/desktop/issues/10687. Please subscribe to that issue to follow any updates in this area.

Before I close this out though could you please elaborate on the part about you "sitting here with 33GB worth of repository history that is completely irrelevant to me". Am I correct in assuming you performed a shallow clone of the repository? And you were never intending to fetch it again?

**Comment by SpencerKlein** [comment]
zkratt is not the only user who is greatly troubled by the inability to turn autofetch off.  It may also drive me away from github.

**Comment by corbin-poteet** [comment]
Shitty fucking application
