### ISSUE TITLE
Unable to push commit, error giving me "The remote disconnected. Check your Internet connection and try again."

### ISSUE THREAD

**Issue by kingmeri** [desktop/desktop#19446]
### The problem

Unable to push commit giving me "The remote disconnected. Check your Internet connection and try again."

My internet connection is fine but I have tried connecting to other network and using a VPN too and still gives me the same error.

The log file is attached below

### Release version

Version 3.4.8 (x64)

### Operating system

macOS Sonoma 14.6

### Log files

[2024-10-23.desktop.production.log](https://github.com/user-attachments/files/17498239/2024-10-23.desktop.production.log)

**Comment by steveward** [comment]
@kingmeri thanks for the issue. It looks like the push is timing out:

```
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
send-pack: unexpected disconnect while reading sideband packet
```

You should be able to resolve this by running the following command:

`git config --global http.postBuffer 157286400`

I'm going to close this out, but let me know if that does not get things working.
