### ISSUE TITLE
Stuck at 'Pushing to origin'

### ISSUE THREAD

**Issue by 1762757171** [desktop/desktop#19450]
### The problem

Always display 'Hang on...' when pushing, no message dialog or anything else.
![image](https://github.com/user-attachments/assets/574bf644-0cbb-4b65-84cb-1e05021cf417)

### Release version

Version 3.4.8 (x64)

### Operating system

Windows 10

### Log files

[2024-10-24.desktop.production.log](https://github.com/user-attachments/files/17509103/2024-10-24.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @1762757171. I'm not seeing anything in the log file related to a push timing out. Are you using HTTPS or SSH with this repository?

**Comment by 1762757171** [comment]
Thanks for reply, I'm using SSH. It's still stuck and spinning![image](https://github.com/user-attachments/assets/608112e9-891f-469e-a03d-d6c5cd68b967) and nothing changed with log. The annoying thing is that this issue only occurs on pc at company, one at home works well.

**Comment by steveward** [comment]
Can you try going to `File` > `Options` > `Advanced` and uncheck the `Use system OpenSSH` checkbox? Let me know if that gets things working.

**Comment by 1762757171** [comment]
It works.
Does this mean I've got some network problem? But Git bash with ssh works well all the time.
Is there any other information I can provide?

**Comment by steveward** [comment]
Glad to hear that got things working.
