### ISSUE TITLE
Account Switch Option

### ISSUE THREAD

**Issue by qasim313** [desktop/desktop#19455]
### The feature request

There should be a mechanism for switching the GitHub account so that we can work on multiple accounts from a single device.

### Proposed solution

Just give the option to Switch accounts, here is an article that may help:
https://code.tutsplus.com/quick-tip-how-to-work-with-github-and-multiple-accounts--net-22574t

**Comment by steveward** [comment]
Thanks for the feedback @qasim313. You can follow along in https://github.com/desktop/desktop/issues/3707 where we are tracking this.
