### ISSUE TITLE
UI doesn't show an update is in progress

### ISSUE THREAD

**Issue by davidlinsley** [desktop/desktop#19458]
### The problem

I clicked on the close icon but it warned me an update was in progress and could break installation if I quit anyway. I clicked cancel, but the main UI still doesn't show an update in progress

### Release version

3.4.6

### Operating system

Windows 11 226100

### Steps to reproduce the behavior

1. Click on Close window

**Comment by steveward** [comment]
Thanks for the feedback @davidlinsley. I'll add this to https://github.com/desktop/desktop/issues/9782.

**Comment by Ahmadstarxs** [comment]
في الاثنين، ٢٨ أكتوبر ٢٠٢٤ ١٠:٤٩ م Steve Ward ***@***.***>
كتب:
