### ISSUE TITLE
Context Menu + Option to View Pull Request on GitHub Website

### ISSUE THREAD

**Issue by DylanDevelops** [desktop/desktop#19453]
### The feature request

Currently, when your branch has a pull request associated with it, you can view it by switching from `Branches` to `Pull Requests`, which will show you the related PRs.

<img width="378" alt="Screenshot 2024-10-25 at 2 42 45 PM" src="https://github.com/user-attachments/assets/9ab4c405-3045-4233-be7d-601f90929873">

When you are in this view, you can only see the PR but can't do anything with it. I specifically want a way to view that pull request on GitHub from that menu.

### Proposed solution

I propose a context menu for when you right-click on a PR to "View on GitHub".

The content menu would look something similar to this. There could be other options but the option mentioned above is specifically the one I want.
<img width="436" alt="Screenshot 2024-10-25 at 2 47 34 PM" src="https://github.com/user-attachments/assets/6dbbd4d8-2170-4831-a875-ee0487ba4d1d">

### Additional context

I would like to work on this feature if the team thinks it is a good idea! Let me know!

**Comment by tidy-dev** [comment]
@DylanDevelops Thank you for the suggestion and wanting to improve GitHub Desktop. Because of some other work around PRs that was discussed recently that would provide this in a way, I am going to put not-planned. But, I will bring it up for discussion next team sync. 

Just in case you didn't know and I know this isn't as quick as what you have suggested here, you can currently click on the pr to check it out, and then in the `Branch` main menu there is a "View Pull Request on GitHub" option.

**Comment by tidy-dev** [comment]
@DylanDevelops If you are still interested in working on this, the team discussed this and we would welcome a PR for this.


 1. Add a context menu to the Pull Request list items (Similar to the branch list context menu) that adds a "View Pull Request on GitHub" context menu item likely to reuse the functions for the main menu `Branch` > `View Pull Request on GitHub` when a pull request is checked out.

Example branch list item context menu:
![Showing the branch list item context menu in the branch list.](https://github.com/user-attachments/assets/557d44d0-f07d-435b-af5b-da2d12894870)


2. We have a context menu on the branch toolbar dropdown button that has all the context menus from the branch list items. We want to have the `View Pull Request on GitHub` added to this context menu when a PR is checked out. 

Showing the branch toolbar dropdown context menu. 
![Showing the branch toolbar dropdown context menu.  ](https://github.com/user-attachments/assets/f355d8fe-f400-40d9-aa11-6fe3ab1c89d7)

**Comment by DylanDevelops** [comment]
@tidy-dev Sweet! I will get on that as soon as I can.

**Comment by DylanDevelops** [comment]
@tidy-dev, I believe I have implemented my idea the way you wanted. You can see it here: #19505
