### ISSUE TITLE
Opening Links with Windows Desktop in Full Screen mode

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1945]
In Windows, Desktop opens the following links in IE, but behind the scenes leaving the novice user somewhat clueless to the fact that it was opened in a browser. 

`Repo > View on GH`
`Branch > Compare on GH`
`See what's new`

Other links like `Help > Report an Issue` are opened in IE, but surfaced in front of Desktop. Perhaps we should be doing the same for all links?

Mac OS had no issues.

v0.5.9, Windows 10

**Comment by shiftkey** [comment]
>  opens the following links in IE, but behind the scenes leaving the novice user 

A couple of questions to narrow this behaviour down:

 - Is this adding a new tab to an existing browser session and not bringing it to focus? Or does this open a new window behind the app?
 - Confirming this is related to IE11 and not Edge?

And looking at the source:

- `Repo > View on GH`
- `Branch > Compare on GH`
- `See what's new`

These all look to go through the `AppStore._openInExternal` method, which just wraps `shell.openExternal`: https://github.com/desktop/desktop/blob/d64e4102aa3945a44b164d6828f0941e3392fb43/app/src/lib/dispatcher/app-store.ts#L1683

 - `Help > Report an Issue`

And this looks the same: https://github.com/desktop/desktop/blob/f200e635cdd741bcf5b23158bd2bf9a3aa06bcbb/app/src/main-process/menu/build-default-menu.ts#L285

**Comment by tierninho** [comment]
> Is this adding a new tab to an existing browser session and not bringing it to focus? Or does this open a new window behind the app?

Good question, but both are not working. Neither a new tab nor a new window bring the browser into focus.

> Confirming this is related to IE11 and not Edge?

Edge

>And this looks the same: 

Looking at the code examples, I see two differences: the "working" example specifically mentions the URL (shouldn't matter), and it also doesn't mention a browser application (`public _openInBrowser`). Perhaps this makes a slight difference? Possible to test removing `openInBrowser` 😬 and see what happens (assuming OS knows how to handle the action)?
