### ISSUE TITLE
Problem to Publish Repo.... from github desktop application 

### ISSUE THREAD

**Issue by Deeppadariya-129** [desktop/desktop#19468]
### The problem

When i publish repo from github desktop it is not posting please review uploaded images. i can not  sign in with my   github account in github desktop give me solution .
![Screenshot 2024-10-30 000510](https://github.com/user-attachments/assets/3e15e612-3d88-48db-8e84-7954edd7f1d5)

### Release version

Version 3.4.6 (x64)

### Operating system

Window 11

### Screenshots

![Screenshot 2024-10-30 000510](https://github.com/user-attachments/assets/928c1453-e4c7-4a81-ab48-1c8cc8e6b1e2)

**Comment by steveward** [comment]
@Deeppadariya-129 can you try switching your default browser on Windows to see if you are able to authenticate to GitHub Desktop?

**Comment by Onetblgf** [comment]
****
