### ISSUE TITLE
unable to checkout working tree - invalid path - path looks valid

### ISSUE THREAD

**Issue by givihuda** [desktop/desktop#19461]
I'm not seeing what the problem is here:

![image](https://github.com/user-attachments/assets/59b3ac64-1586-433a-bc43-98aa4b7e4c7c)

I just installed GitHub Desktop on Windows 11.

**Comment by steveward** [comment]
@givihuda thanks for the issue. The word `aux` is reserved on Windows, so if it's used in a filename it will throw this error. You can workaround this with a specific config option:

`git config --global core.protectNTFS false`

But if it's possible to rename the file that would resolve it as well.  I'm going to close this out, let me know if you have any further questions.
