### ISSUE TITLE
Ability to change from "x days ago" to localize date time format e.g "dd/MM/yy"

### ISSUE THREAD

**Issue by activate-robbieburke** [desktop/desktop#19469]
### The feature request

When looking back through past commits via history, I usually only do this to compare against other data in our organization. e.g. Filling out timesheets (e.g. what did I work on last Monday), or figuring out when a bug was introduced (e.g. what commits where made on the 12th of last month). It's actually really hard to compare this data when the information is presented like "x days ago". See the attached image.
![image](https://github.com/user-attachments/assets/f276d03a-9153-4a40-ba0b-ca621a20915f)

### Proposed solution

I would love the ability to set the date format that's presented to me in the history tab from "x days ago" to a more specific date format. i.e. dd/MM/yy is my localized date format.

**Comment by steveward** [comment]
@activate-robbieburke thanks for the feedback. This is being tracked in #14611, so you can follow along there for updates.

You can also hover over to see the exact timestamp.
