### ISSUE TITLE
Blank slates are really small on hi-res displays

### ISSUE THREAD

**Issue by xt0rted** [desktop/desktop#1946]
### Description

When running on a hi-res display (in this instance it's 4K with Windows set to 150% scaling) the blank slate illustrations are really small.

### Version
**GitHub Desktop version:** 0.6.0 (has existed since they were added)
**OS version:** Win10 CU

### Steps to Reproduce

1. Buy a 4k display
1. Set Windows to 150% scaling
1. 💰

**Expected behaviour:** The illustrations should scale so on hi-res displays they appear larger

**Actual behaviour:** The illustrations don't scale and are really small

**Reproduces how often:** Every time

#### Additional Information

This is a screen shot of my desktop with the application at the approx. size I run it at.

![desktop](https://user-images.githubusercontent.com/831974/26947151-9a2d1ab6-4c5f-11e7-9eb0-293eb0118ecc.png)

**Comment by shiftkey** [comment]
[They're totally SVGs](https://github.com/desktop/desktop/blob/bde7470d418d74aba772452391f66ca6a49410c4/app/src/ui/changes/index.tsx#L35), so I can't think of anything technical preventing this from working.

I don't have access to a 4K display to test this :P so I'm going to mark it as `up-for-grabs` for someone who suffers from having too many pixels to experiment with the scaling side...

**Comment by shimpossible** [comment]
Is the issue it doesn't follow the 'text scaling', or that its just small.   Making it scale with the window is easy.  Making it follow text-scaling is something else
