### ISSUE TITLE
After Push my website Github is not showing some code or file of my document 

### ISSUE THREAD

**Issue by sadafshahab12** [desktop/desktop#19466]
### The problem

I am experiencing an issue where certain files or code changes are not appearing in my GitHub repository after pushing my latest commits. All files are showing but they are not working in live link. kindly solve this problem

### Release version

Version 3.4.8

### Operating system

window 10 22H2

### Steps to reproduce the behavior

go to repository "Complete Event Tracker" https://sadafshahab12.github.io/Complete-Event-Tracker/
and go to the live link
image is not showing, sometime before js file is being pushed and it is showing in repo but it was not working, why am I
<img width="912" alt="Capture" src="https://github.com/user-attachments/assets/7bd36d1e-0bf1-4c04-a1e2-f8c65816902f">
 facing these problems?

### Log files

<div class="mouse-event-box">
            <h2>Mouse Over Event</h2>
            <div class="mouse-event">
              <div class="mouse-event-img" onmouseover="mouseOver()">
                <img src="/images/hcj12.PNG" class="image">
                <p class="image-tag">Word Scramble Game (HTML,CSS, JS) </p>
              </div>
            </div>
          </div>

### Screenshots

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Complete Event Tracker</title>
    <link rel="stylesheet" href="css/style.css" />
    <link rel="stylesheet" href="css/image.css" />
    <link rel="stylesheet" href="css/mouseEvent.css" />
    <link rel="stylesheet" href="css/formsubmit.css" />
    <link rel="stylesheet" href="css/media.css" />
    
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
      integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
  </head>

  <body>
    <div class="container">
      <h1>Complete Event Tracker</h1>
      <div class="event-box">
        <h2>Click Event</h2>
        <p class="counter"></p>
        <div class="clickBtn">
          <button onclick="increment()">Counter</button>
          <button onclick="reset()">Reset</button>
        </div>
      </div>
      <div class="event-box box2">
        <div class="box-2">
          
          <div class="image-event-box">
            <h2>Click Event</h2>
            <div class="image-event">
              <div onclick="leftSlider()" class="slider">
                <i class="fa-solid fa-circle-chevron-left left"></i>
              </div>
              <div onclick="rightSlider()" class="slider">
                <i class="fa-solid fa-circle-chevron-right right"></i>
              </div>
              <div class="image-main-div">
                <div class="imgDiv">
                  <img src="./images/hc6.PNG" class="image" />
                </div>
              </div>
            </div>
          </div>

          
          <div class="mouse-event-box">
            <h2>Mouse Over Event</h2>
            <div class="mouse-event">
              <div class="mouse-event-img" onmouseover="mouseOver()">
                <img src="" class="image" />
                <p class="image-tag"></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <div class="events">
        <div class="box-3">
          <h1>Movement Tracker (On Mouse Move)</h1>
          <div class="box-3-img" onmousemove="movement(event)">
            <img src="./images/next js assignment 5 1.png" />
          </div>
          <div class="size">
            <p class="width">Width : 0</p>
            <p class="height">Height : 0</p>
          </div>
        </div>

        
        <div class="box-4">
          <div>
            <h1>KeyBoard Event</h1>
            <input type="text" placeholder="Press Any Key" class="keyPress" />
            <p class="showKey"></p>
          </div>
          <div class="focus">
            <h1>Focus and Blur Event</h1>
            <input type="text" onfocus="statusFocus()" onblur="statusBlur()" />
            <p>Status:</p>
          </div>
        </div>

        
        <div class="box-5">
          <h1>Drop Down (Mouse Over Event & on Click)</h1>
          <ul class="dropdownhead" onmouseover="showDropDown()">
            <li>Front End Development</li>
          </ul>
          <ul class="dropdownlist">
            <li onclick="hideDropDown()">html</li>
            <li onclick="hideDropDown()">css</li>
            <li onclick="hideDropDown()">js</li>
          </ul>
        </div>
      </div>
      <div class="other-events">
        
        <div class="resize" onresize="reSize()">
          <h1>Window Resize Event</h1>
          <p></p>
        </div>
        
        <div class="form-submit">
          <h1>Form Submit Event</h1>
          <form action="#" onsubmit="formSubmitted(event)">
            <div class="email">
              <label for="email">Email:</label>
              <input type="email" id="email" />
            </div>
            <div class="msg">
              <label for="msg">Message:</label>
              <textarea name="msg" id="msg"></textarea>
            </div>
            <button>Submit</button>
            <p class="submitMsg"></p>
          </form>
        </div>
        
        <div class="drag-drop">
          <h1>Drag and Drop Event</h1>
          <div class="drag-drop-box">
            <div class="drag-pic" draggable="true">
              <img src="./images/next js assignment 5 1.png" />
            </div>

            <div class="drop-pic">Drop here</div>
          </div>
          <p class="drag-drop-msg">Drag the Image</p>
        </div>
      </div>

      
      <div class="media">
        <h1>MediaEvent</h1>
        <div class="video">
          <video controls src="./media/video.mp4">Video</video>
        </div>
        <p class="media-status">Media Status :</p>
        <p class="video-time"></p>
      </div>
    </div>

    <script src="js/app.js"></script>
    <script src="js/mouseover.js"></script>
    <script src="js/keyboard.js"></script>
    <script src="js/dragdrop.js"></script>
  </body>
</html>

**Comment by sadafshahab12** [comment]
I am experiencing an issue where certain files or code changes are not appearing in my GitHub repository after pushing my latest commits. All files are showing but they are not working in live link. kindly solve this problem

**Comment by steveward** [comment]
@sadafshahab12 we can't assist with GitHub Pages help. I'd recommend asking for assistance here:

https://github.com/orgs/community/discussions/categories/pages

**Comment by sadafshahab12** [comment]
> @sadafshahab12 we can't assist with GitHub Pages help. I'd recommend asking for assistance here:
> 
> https://github.com/orgs/community/discussions/categories/pages

What should i do i do not understand?
