### ISSUE TITLE
allow to override the open in the browser url

### ISSUE THREAD

**Issue by mtariqsajid** [desktop/desktop#19475]
### The feature request

If the Git repository is hosted outside of GitHub, the "Open in Browser" feature is disabled. To improve user experience, consider allowing users to manually set the browser URL. This will make it easier for them to view the repository directly.

### Proposed solution

Allow users to override the repository URL in File -> Options.

**Comment by steveward** [comment]
Thanks for the feedback @mtariqsajid. I'm going to group this into https://github.com/desktop/desktop/issues/17846.
