### ISSUE TITLE
Use latest Electron version, also focus on GitHub issues and weekly updates with proper changelogs

### ISSUE THREAD

**Issue by fisforfaheem** [desktop/desktop#19477]
### The feature request

Use latest Electron version, also focus on GitHub issues and weekly updates with proper changelogs

### Proposed solution

Use latest Electron version, also focus on GitHub issues and weekly updates with proper changelogs

**Comment by steveward** [comment]
@fisforfaheem thanks for the feedback. We lag behind Electron versions for stability. You can find our for release notes [here](https://desktop.github.com/release-notes/).

**Comment by fisforfaheem** [comment]
Please atleast use 2 months old stable version its very old version

**Comment by sergiou87** [comment]
Just curious, @fisforfaheem , is there anything specific you're missing from newer Electron versions?

**Comment by fisforfaheem** [comment]
Just the latest version is faster and more robust.
