### ISSUE TITLE
Git repository disappeared 

### ISSUE THREAD

**Issue by raeann108** [desktop/desktop#19472]
### The problem

I was trying to switch branches in my github desktop when I realised that the switching process took way longer than usual. Thinking nothing of it, I closed the github desktop window and reopened the application, when the interface told me that the repository was gone. I was sure that it was not the case as I could still view the repository on github website 

### Release version

Version 3.4.8 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Repository is gone, cannot even clone the repo, but still present on the github website. My other collaborators are also experiencing the same thing 

### Additional context

It just happened suddenly, not sure how to make the repo visible on github desktop again

**Comment by steveward** [comment]
@raeann108 if a status operation hits a specific error it can cause the repository to show as missing, but it will still be present on disk. See https://github.com/desktop/desktop/issues/9049. 

You should be able to drag-and-drop the repository to add it back to GitHub Desktop, or use the locate button. If there's a specific operation that's causing this you may need to use the command line to commit the changes to resolve this.

Let me know if that isn't the issue, but I'm going to close this out.
