### ISSUE TITLE
github desktop does not ask for pgp passwords and fails to commit

### ISSUE THREAD

**Issue by sctech-tr** [desktop/desktop#19482]
### The problem

If you assign a PGP key to sign commits with Git, it will also try to sign commits in GitHub Desktop. **However**, it will fail because it does not prompt you for the password. Then it fails because there is no password provided.

### Release version

Version 3.4.3-linux1 (x64)

### Operating system

Fedora 41 with KDE Plasma

### Steps to reproduce the behavior

1. assign your pgp key with git
2. try to commit
3. see the error

### Log files

particularly this part
```log
stderr:
error: gpg failed to sign the data:
[GNUPG:] KEY_CONSIDERED 57BE156FEB39FB9905BA1299169CABCFA8FDD1CF 2
[GNUPG:] BEGIN_SIGNING H10
gpg: imzalama başarısız: Parola girişi yok
[GNUPG:] FAILURE sign 67108949
gpg: signing failed: Parola girişi yok

fatal: failed to write commit object

(The error was parsed as 40: null)
2024-11-02T10:27:56.547Z - info: [ui] [Timing] Action 'create commit' for 'sctech-tr/website' took 1.443s
```

### Screenshots

![resim](https://github.com/user-attachments/assets/172a6758-84fa-4274-a75d-edbbf28861c9)

### Additional context

It seems like other people are experiencing this as well, but no one specifically talked about this. (correct me if i'm wrong)

**Comment by steveward** [comment]
@sctech-tr thanks for the issue. At this time we don't have official GPG support, but there's a helpful guide a user wrote here to get things working:

https://gist.github.com/xavierfoucrier/c156027fcc6ae23bcee1204199f177da

I'm going to close this out, but let me know if that gets things working.
