### ISSUE TITLE
Not publishing

### ISSUE THREAD

**Issue by StaffordInnovations** [desktop/desktop#19480]
### The problem

The remote disconnected. Check your Internet connection and try again.

My internet connection is up, running and having no problems anywhere else.  I tried signing out and signing back in.  For some reason it won't let me publish

### Release version

3.4.8 x 64

### Operating system

MacOS Sequoia 15.0.1

### Steps to reproduce the behavior

I press the publish to branch button.

### Screenshots

![Screenshot 2024-11-01 at 3 45 13 p m](https://github.com/user-attachments/assets/2de8a3fd-9768-4267-86bc-c87d15a491ae)

**Comment by StaffordInnovations** [comment]
I also restarted my computer and GitHub Desktop

**Comment by steveward** [comment]
Thanks for the report @StaffordInnovations. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by StaffordInnovations** [comment]
[2024-11-01.desktop.production.log](https://github.com/user-attachments/files/17602285/2024-11-01.desktop.production.log)

**Comment by steveward** [comment]
You should be able to resolve this by running this config option:

`git config --global http.postBuffer 157286400`

Let me know if that does not get things working.

**Comment by StaffordInnovations** [comment]
thanks, that worked.  will this be something I have to do again? if so what is the relevancy of the numbers?

**Comment by steveward** [comment]
That config option will stick around in your `.gitconfig`, so you won't have to do it again unless you edit the config or run into it on a different machine. The numbers just increase the buffer size, see [the Git manual](https://git-scm.com/docs/git-config#Documentation/git-config.txt-httppostBuffer).
