### ISSUE TITLE
Unable to install Github Desktop

### ISSUE THREAD

**Issue by Zhowder** [desktop/desktop#19488]
### The problem

Unable to install Github Desktop, when i try to run installer it just said installation failed and check the setup logs

### Release version

-

### Operating system

Windows 11

### Log files

[SquirrelSetup.log](https://github.com/user-attachments/files/17609806/SquirrelSetup.log)

### Screenshots

![image](https://github.com/user-attachments/assets/4d7c9b77-6c5c-4216-886a-3c1b05c64cdc)

**Comment by steveward** [comment]
@Zhowder thanks for the report. Can you delete this directory and then try reinstalling GitHub Desktop?

`C:\Users\N987\AppData\Local\SquirrelTemp`

Let me know if that doesn't get things working.
