### ISSUE TITLE
Sort the branches in the dropdown by last updated at

### ISSUE THREAD

**Issue by theBGuy** [desktop/desktop#19487]
### The feature request

Add default sorting by `last updated at` to the listed branches from the `Current Branch/Branches` dropdown.

### Proposed solution

This would be helpful when working with other developers or switching machines. The filter works to find the branch given you know the name, however always having the most recently changed branch at the top would make ux feel faster a I don't need to see stale branches at the top of the list.

### Additional context

You can see in the picture the most recent is near the bottom, there's another couple branches below it if you scroll down.

![image](https://github.com/user-attachments/assets/d73b67e5-4199-4712-b085-53e967c6177b)

**Comment by steveward** [comment]
Thanks for the feedback @theBGuy. I'm going to add this to https://github.com/desktop/desktop/issues/5155 where we are tracking this.
