### ISSUE TITLE
 running in recovery mode due to a configuration error. Please review the creation logs, update your dev container configuration as needed, and run the "Rebuild Container" command to rectify.

### ISSUE THREAD

**Issue by techkipra** [desktop/desktop#19491]
### The problem

 running in recovery mode due to a configuration error. Please review the creation logs, update your dev container configuration as needed, and run the "Rebuild Container" command to rectify .i have rebulid multiple times still same error 

### Release version

Version 3.4.8 (x64)

### Operating system

windows 11 13 version

### Screenshots

![Screenshot (306)](https://github.com/user-attachments/assets/2dd6867a-5563-498b-ab3c-a3ae93b2c816)

**Comment by akaday** [comment]
# Review creation logs
# (Check logs for specific configuration issues)

# Update dev container configuration
# (Make necessary changes based on logs)

# Rebuild the container
code-insiders . # Open VS Code
Shift + Command + P (Mac) or Ctrl + Shift + P (Windows/Linux)
Type "Rebuild" and select `Codespaces: Rebuild Container`
Select "Rebuild" or "Full Rebuild" in the confirmation dialog

**Comment by steveward** [comment]
@techkipra if you're having an issue with Codespaces I would recommend reaching out to [GitHub Support](https://support.github.com/) for assistance.
