### ISSUE TITLE
Haxe Flixel gitignore template

### ISSUE THREAD

**Issue by macohi** [desktop/desktop#19509]
### The feature request

Just add a git ignore template for haxe flixel
its as simple as

```
/export
```

very simple

### Proposed solution

it benefits haxe devs cause they won't have to make it themselves and if they forget to make one then have some stuff get leaked or something

**Comment by steveward** [comment]
@IdealistCat thanks for the issue. It looks like there isn't a `.gitignore` template for HaxeFlixel at https://github.com/github/gitignore. We pull in the templates from that repository. I'd recommend reading the [contributing guidelines](https://github.com/github/gitignore?tab=readme-ov-file#contributing-guidelines) and then submitting a pull request to add one.
