### ISSUE TITLE
Cannot sign in.

### ISSUE THREAD

**Issue by ZhanZiyuan** [desktop/desktop#19507]
### The problem

Github Desktop shows unknown characters when trying to sign in.

### Release version

Version 3.4.8 (x64)

### Operating system

Microsoft Windows 10.0.19045.5073

### Steps to reproduce the behavior

1. Click on "Clone a repository".
2. Click on "Sign in".
3. Click on "Continue with browser".
4. Back from the browser and see characters with no meanings.

I tried uninstalling Github Desktop and restarting the computer, but the problem is still there.

### Log files

[2024-11-05.desktop.production.log](https://github.com/user-attachments/files/17627835/2024-11-05.desktop.production.log)

### Screenshots

![01](https://github.com/user-attachments/assets/d23b1ba8-46d2-4a7d-8ef6-e1d1b03198f5)
![02](https://github.com/user-attachments/assets/e4e528dc-0319-4185-8aa4-5a3eb11fef94)

**Comment by steveward** [comment]
@ZhanZiyuan thanks for the issue. Are you behind a proxy or VPN that could interfering with authentication? Are you running any security or other antivirus software on this machine? Any details about your configuration you can share would be helpful.

**Comment by ZhanZiyuan** [comment]
Thank you for your reply.

1. I do use a proxy, but the proxy is in the router. Sometimes when that is shut down, I will use the VPN on my PC instead so I could have access to github.com in China.

2. I use no antivirus software but Windows Defender.

3. One more thing is that our office experienced a sudden power cut before I found this issue of GitHub Desktop (I didn't use GitHub Desktop at that time.). All facilities, including servers, routers, and PCs, have been rebooted.

**Comment by steveward** [comment]
Unfortunately without more information about the error it'll be difficult to determine what the issue is, but my guess is that it's related to your network configuration. Have you previously been able to log in to GitHub Desktop? Is there another network you can try authenticating on to help narrow down what the issue might be?

**Comment by ZhanZiyuan** [comment]
Thank you for your kindness. I should give more detailed narrative.

1. (Yes, I could log in to GitHub Desktop before.) At the very beginning, Github Desktop asked for login while Commit, Push and Pull can still work.

2. It showed the window that is the same as in [#18662](https://github.com/desktop/desktop/issues/18662) when committing.

3. I tried uninstalling Github Desktop after several login failures. This is what it looks like now.

![001](https://github.com/user-attachments/assets/bcd47e92-9770-4aff-b5c9-d84ff4d784c9)

**Comment by ZhanZiyuan** [comment]
I still encountered login failures in Version 3.4.9 (x64) on Nov. 7 (UTC+8).

**Comment by steveward** [comment]
Can you send over the log file again? That authentication failure dialog is different, so it should hopefully give a better error with some indication of what the issue is.

**Comment by ZhanZiyuan** [comment]
OK. Here is the log file.

[2024-11-07.desktop.production.log](https://github.com/user-attachments/files/17663185/2024-11-07.desktop.production.log)

**Comment by ZhanZiyuan** [comment]
I referred to the solution in [#16791](https://github.com/desktop/desktop/issues/16791) searching `�ڴ���Դ���㣬�޷����������` in Issues. That did solve my problem. Thank you for your help.

![01](https://github.com/user-attachments/assets/b33b24ff-189a-437e-b6a3-897a8f5c1efc)

**Comment by steveward** [comment]
I'm glad to hear that got things working!
