### ISSUE TITLE
Github Desktop failed to launch

### ISSUE THREAD

**Issue by trupti-karnire** [desktop/desktop#19513]
<img width="766" alt="Screenshot 2024-11-06 at 2 49 39 PM" src="https://github.com/user-attachments/assets/9bd17526-2b0e-4d51-8a37-14bb6985e187">
<img width="766" alt="Screenshot 2024-11-06 at 2 49 39 PM" src="https://github.com/user-attachments/assets/9fd3f840-930a-481f-a4dc-8b075fe7c347">

**Comment by steveward** [comment]
Thanks for the report @trupti-karnire. Can you share a few more details? Specifically it would be helpful to know if you just installed the app, or if this is occurring after an update.

Have you tried performing a fresh installation? You can do so by following these steps:

1. Delete all of the files under `~/Library/Application Support/GitHub Desktop/`
2. Reinstall GitHub Desktop

Let me know if that helps.
