### ISSUE TITLE
No longer able to pull/push/sync

### ISSUE THREAD

**Issue by MichelLalancetteNortera** [desktop/desktop#19510]
### The problem

Since last week I have been unable to pull/push/sync because it stays stuck on "Hang on..."
![image](https://github.com/user-attachments/assets/bb55d781-29cf-401c-885f-aebda154bad9)

I don't believe there are any hidden popups that I need to click and it never errors out.

Github Desktop Version 3.4.8 
git version 2.47.0.windows.1

This has been happening with all my repositories and I tested I can still do these commands using other tools (Fork being one of them).

### Release version

3.4.8

### Operating system

Windows 10 22H2

### Steps to reproduce the behavior

1. Open GitHub desktop
2. select a repository with an available pull
3. Press pull
4. Wait...

### Log files

[2024-11-05.desktop.production.log](https://github.com/user-attachments/files/17638104/2024-11-05.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @MichelLalancetteNortera. Are you using SSH or HTTPS with your repositories?

**Comment by MichelLalancetteNortera** [comment]
SSH to our GitLab Community instance. 
GitLab Community Edition v16.9.1

**Comment by steveward** [comment]
Can you try going to `File` > `Options` > `Advanced` and uncheck the `Use system OpenSSH` checkbox? Let me know if that gets things working.

**Comment by MichelLalancetteNortera** [comment]
This seems to have fixed the issue. Should I keep this setting from now on?

**Comment by steveward** [comment]
@MichelLalancetteNortera you can keep that option disabled since it's working now. I'm going to close this out.
