### ISSUE TITLE
Graphic flash when playing any animation

### ISSUE THREAD

**Issue by hbread00** [desktop/desktop#19516]
### The problem

After updating 3.4.8(I didn't report it in that version, but the issue still exists in 3.4.9), graphic flash when playing any animation, include any UI change. 

https://github.com/user-attachments/assets/1af7d969-0681-4c93-b18a-cd0510c36212

### Release version

3.4.9

### Operating system

Windows 11 24H2

### Steps to reproduce the behavior

1. Open Github Desktop normally
2. Do anything making UI change, include hover on button, play fetch animate

### Log files

2024-11-07T09:41:10.444Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-11-07T09:41:10.732Z - info: [ui] [AppStore] loading 1 repositories from store
2024-11-07T09:41:10.732Z - info: [ui] [AppStore] found account: hbread00 (Bread)
2024-11-07T09:41:10.746Z - info: [ui] [BranchPruner] Last prune took place 5 hours ago - skipping
2024-11-07T09:41:11.069Z - info: [ui] launching: 3.4.9 (Windows 10.0.26100)
2024-11-07T09:41:11.070Z - info: [ui] execPath: 'C:\Users\home\AppData\Local\GitHubDesktop\app-3.4.9\GitHubDesktop.exe'
2024-11-07T09:41:11.849Z - info: [ui] Subscribed 'hbread00' to Alive channel
2024-11-07T09:41:13.462Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 1.238s)
2024-11-07T09:41:14.579Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.116s)

### Additional context

When using screen recording software, unable to fully capture the screen issue, only the area of the right of the Fetch button flashing. So I recording the screen with camera. 
Lowering the monitor's refresh rate, reducing the resolution, and disabling NVIDIA Gsync didn't solve the problem.

Monitor: AOC CQ27G3S
Graphics card: NVIDIA 4060TI
Driver version: Studio 565.90

**Comment by steveward** [comment]
Thanks for the report @hbread00. Do you know if you have any of NVIDIA's global antialiasing options enabled? We've seen that cause similar issues in the past.

You can try launching GitHub Desktop with GPU accelerated rendering turned off to verify that it is indeed related to the GPU  by setting the `GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION` environment variable to 1 by running `set GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1` in cmd.exe and restarting your machine or by setting it through the UI following a [guide like this](https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0).

Note that you may have to restart your machine for the changes to take effect. Let me know if that helps.

**Comment by hbread00** [comment]
> Thanks for the report @hbread00. Do you know if you have any of NVIDIA's global antialiasing options enabled? We've seen that cause similar issues in the past.
> 
> You can try launching GitHub Desktop with GPU accelerated rendering turned off to verify that it is indeed related to the GPU by setting the `GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION` environment variable to 1 by running `set GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1` in cmd.exe and restarting your machine or by setting it through the UI following a [guide like this](https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0).
> 
> Note that you may have to restart your machine for the changes to take effect. Let me know if that helps.

Antialiasing is not enabled.
Disabling GPU acceleration is worked.

**Comment by steveward** [comment]
Thanks, I'm going to close this out, but we'll keep an eye out for continuing reports of this.
