### ISSUE TITLE
GitHub Desktop won't start on Windows

### ISSUE THREAD

**Issue by WechQ** [desktop/desktop#19515]
### The problem

I haven't used GitHub Desktop for more than a few months, when I have to use it again the installed GitHub Desktop won't start, so I tried re-installing and got the same result. Tried deleting GitHub Desktop on both %LocalAppData% and %AppData%, restart, re-install doesn't help.

### Release version

3.4.9

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Run GitHubDesktopSetup-x64.exe
2. See splash screen saying "It'll launch when it's done"
3. Nothing happens

### Log files

[Squirrel-Install.log](https://github.com/user-attachments/files/17657447/Squirrel-Install.log)

**Comment by steveward** [comment]
Thanks for the issue @WechQ. Can you try deleting ` C:\Users\Wech\AppData\Local\SquirrelTemp` and installing again to see if that makes a difference?

**Comment by WechQ** [comment]
Yes, I tried that and got the same result, the folder has only Squirrel-Install.log file.
[Squirrel-Install.log](https://github.com/user-attachments/files/17671770/Squirrel-Install.log)

**Comment by steveward** [comment]
Are you running any antivirus or security software that could be interfering with GitHub Desktop launching?

**Comment by WechQ** [comment]
No, there's no antivirus or security software installed in the PC.

**Comment by steveward** [comment]
Can you take a look in `Event Viewer` and see if there is anything interesting there that could indicate why the app might not be launching? If you have another user profile on this machine it may also be worth installing GitHub Desktop there to see if it works on a different profile.
