### ISSUE TITLE
UI of GITHUB has white lines 

### ISSUE THREAD

**Issue by DreProgrammer** [desktop/desktop#19535]
### The problem

hello these past few days my application have this glitch wherein i dont know why my github desktop is like this
![Screenshot 2024-11-11 230009](https://github.com/user-attachments/assets/201e7df4-9968-4483-a1e4-3cac8d60e310)

### Release version

Version 3.4.9 (x64)

### Operating system

Windows 10

**Comment by sergiou87** [comment]
Could you try editing the app's shortcut (the one you use to open the app, from the Desktop or the start menu) and add the `--disable-gpu` parameter to see if that resolves this issue?

In the properties dialog, just add ` --disable-gpu` at the end of the `Target` text field, like this:

![Image](https://github.com/user-attachments/assets/4a4b5e82-906f-4e55-a622-01fd839c4804)

**Comment by DreProgrammer** [comment]
hello i dont have the shortcut tab in the properties of github

**Comment by sergiou87** [comment]
Hmmm do you have a shortcut in your desktop? Check the properties of that shortcut, it should have the `Shortcut` tab 🤔

**Comment by niik** [comment]
@DreProgrammer if you can't locate the shortcut then you can try setting the GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION environment variable to 1 by running `set GITHUB_DESKTOP_DISABLE_HARDWA`RE_ACCELERATION=1` in cmd.exe and restarting your machine or by setting it through the UI following a guide like this: https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0

Note that you may have to restart your machine for the changes to take effect.

Please also make sure that you're using the latest version of your graphics driver. We've seen reports of disabling NVIDIA's FXAA and Multi-Frame Sampled AA (MFAA) being another solution (see https://github.com/desktop/desktop/issues/19397#issuecomment-2411213519)
