### ISSUE TITLE
Recent Run Configurations only allow 6

### ISSUE THREAD

**Issue by Lars-jnk** [desktop/desktop#19537]
### The problem

You can change the number to max 6 or 7, but you only see the last 6. If you change the number to 8 or larger, you see no more recent configs.

### Release version

IntelliJ IDEA 2024.2.4 (Community Edition) Build #IC-242.23726.103, built on October 23, 2024 Runtime version: 21.0.4+13-b509.26 amd64 (JCEF 122.1.9) VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. Toolkit: sun.awt.X11.XToolkit Linux 6.6.54-2-manjaro GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation Memory: 2970M Cores: 8 Registry:   ide.experimental.ui=true   i18n.locale= Non-Bundled Plugins:   Lombook Plugin (242.23726.38)   Code Iris (2.4-beta)   com.jetbrains.space (242.23726.16)   DBN (3.4.4425.0)   com.vaadin.intellij-plugin (1.3.7) Kotlin: 242.23726.103-IJ Current Desktop: KDE

### Operating system

Manjaro lastest

**Comment by steveward** [comment]
@Lars-jnk it sounds like you are looking for support for a Jetbrains product -- I'd recommend reaching out to them for assistance.

**Comment by Lars-jnk** [comment]
lol, I have no idea how I come here.
