### ISSUE TITLE
cannot view on vs code

### ISSUE THREAD

**Issue by aqsafatima2100** [desktop/desktop#19539]
### The problem

i cloned a repository and then i need to view that on vs code i tried every possible thing to view it there but i am facing some error
![Screenshot 2024-11-12 134520](https://github.com/user-attachments/assets/5c24355f-1877-40fd-9f41-17fee2dcc3d2)

### Release version

latest version

### Operating system

Windows 11

**Comment by steveward** [comment]
@aqsafatima2100 thanks for the report. 

Can you open up PowerShell and run the following commands?

`$Env:Path`
`$Env:ComSpec`

Let me know the output of both those commands.
