### ISSUE TITLE
Stash selected files

### ISSUE THREAD

**Issue by felipedrumond** [desktop/desktop#19538]
### The feature request

At times, users may need to stash one or more files instead of all of them (which is available at "Stash all changes" in the Branch menu).

### Proposed solution

Upon right clicking a file in the changes list, add an option "Stash selected files".
Under the hood, run
**git stash push** _path/to/file1 path/to/file2 path/to/file3_

**Comment by steveward** [comment]
Thanks for the feedback @felipedrumond. This is being tracked in https://github.com/desktop/desktop/issues/11531, so I'm going to reference this issue there and close this out.
