### ISSUE TITLE
Chinese characters appear as garbled text in the Diff interface.

### ISSUE THREAD

**Issue by a690089735** [desktop/desktop#19530]
### The problem

Chinese characters appear as garbled text in the Diff interface.
![image](https://github.com/user-attachments/assets/ce4d2dfd-8655-4846-a30c-87889f485898)
![image](https://github.com/user-attachments/assets/60c974b1-84d7-4112-87f6-c80895ce2e20)

(This issue has existed for a long time)
All descriptions of this issue were translated by AI

### Release version

Version 3.4.9 (x64)

### Operating system

Windows10 and Windows11

**Comment by steveward** [comment]
Thank you for the report @a690089735. This is being tracked in https://github.com/desktop/desktop/issues/3923, I'd recommend following along there for updates. I'm going to close this out and reference this issue there.
