### ISSUE TITLE
Option to display actual dates instead of ...ago

### ISSUE THREAD

**Issue by ddaddy** [desktop/desktop#19549]
### The feature request

In the history view, each commit shows its data as ....ago which makes it hard to locate a specific date.

### Proposed solution

Add a setting that allows date to be shown as proper dates and not `14 months ago`

**Comment by steveward** [comment]
@ddaddy thanks for the issue. This is being tracked in https://github.com/desktop/desktop/issues/14611, so you can follow along there for updates. You can also hover over the relative date to get the timestamp. I hope that helps.
