### ISSUE TITLE
Github desktop encoding utf-8 display error

### ISSUE THREAD

**Issue by WeihanLi** [desktop/desktop#1954]
### Description

utf-8 encoded Chinese character

### Version

**GitHub Desktop version:** [0.6.0]

**OS version:** [Microsoft Windows Version 10.0.15063]

### Steps to Reproduce

1. write Chinese characters in your files
1. view the diff in Github Desktop

![desktop_error](https://user-images.githubusercontent.com/7604648/26964760-97cc49c4-4d25-11e7-8c05-262eaa715b24.png)
![nor](https://user-images.githubusercontent.com/7604648/26964759-97cc4f96-4d25-11e7-9d3c-f531e47208e6.png)

**Comment by joshaber** [comment]
This might be a regression related to the large diff support.

**Comment by shiftkey** [comment]
@WeihanLi @evrmji are you able to share example repositories to help with testing this to identify whether this is just a regression or whether it's something new we need to add?

**Comment by WeihanLi** [comment]
No big diff,Just two file with about twenty lines changes

**Comment by csuhta** [comment]
I'm also having this issue with characters outside the Chinese range:

Example lines:

```ruby
      #{link_to("Original", @resource.image_uri(:original))} •
      #{link_to("Small", @resource.image_uri(:small))} (#{CardImage::Sizes.small.width}×#{CardImage::Sizes.small.height}) •
      #{link_to("Normal", @resource.image_uri(:normal))} (#{CardImage::Sizes.normal.width}×#{CardImage::Sizes.normal.height}) •
      #{link_to("Large", @resource.image_uri(:large))} (#{CardImage::Sizes.large.width}×#{CardImage::Sizes.large.height}) •
      #{link_to("PNG", @resource.image_uri(:png))} (#{CardImage::Sizes.png.width}×#{CardImage::Sizes.png.height})
```

Bad diff render:

![iiulbxgt](https://user-images.githubusercontent.com/769083/26987534-de71074a-4d19-11e7-914b-0f43f1050190.png)

Version 0.6.0, macOS Sierra 10.12.5
