### ISSUE TITLE
fatal: Unable to write file

### ISSUE THREAD

**Issue by takehora** [desktop/desktop#19564]
### The problem

I have been encountering a recurring issue when attempting to commit files. Specifically, I frequently receive the error message:

“fatal: Unable to write new [file name]”.

Despite multiple attempts, the error persists, though occasionally the commit does succeed after several retries.

### Release version

Version 3.4.9 

### Operating system

Windows 11

### Steps to reproduce the behavior

1. create/modifiy a file
2. Click "Commit to main"

### Log files

2024-11-16T00:00:40.298Z - info: [ui] [Timing] Action 'create commit' for 'Spelldata/maildata.jp' took 0.203s
2024-11-16T00:01:15.633Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 8 repositories took 4.0s of which 32.8s paused, total 36.8s

### Screenshots

<img width="300" alt="2024-11-16_08h58_53" src="https://github.com/user-attachments/assets/e22eb527-7d1a-43d0-b52b-77d719eb2f4f">

**Comment by steveward** [comment]
@takehora thanks for the report. A few questions to help debug this:

- Do you get any errors when committing via the command line? 
- Are there any potential permission issues for this location, or is it on a network storage device?
- Are you running any antivirus or other security software?
