### ISSUE TITLE
App doesn't use wayland backend even tho I'm on a wayland session and instead runs via XWayland

### ISSUE THREAD

**Issue by Twig6943** [desktop/desktop#19570]
### The problem

Github desktop uses electron so this should be possible.

### Release version

3.4.8-linux1 (x64)

### Operating system

EndeavourOS

### Steps to reproduce the behavior

Install github desktop

**Comment by sergiou87** [comment]
Hello 👋  Issues related to the unofficial Linux fork of GitHub Desktop can be filed here:

https://github.com/shiftkey/desktop/issues

At this time we only officially provide support for macOS and Windows.

Sorry!
