### ISSUE TITLE
Files marked excluded still being pushed via GUI

### ISSUE THREAD

**Issue by sararielle** [desktop/desktop#19576]
### The problem

I have successfully (using .git/info/exclude) set a particular file to be locally excluded.  (I need to retain the version on my machine as distinct from the version in the main repo.)  However, GitHub Desktop seems to ignore this fact.  (I see that I can uncheck the box but I'll need to do that *every time*, whereas the cmdline exclude persists until reversed.)

### Release version

3.4.9 (arm64)

### Operating system

sequoia 15.1

### Steps to reproduce the behavior

1. edit file
2. add file to .git/info/exclude
3. [file remains in github desktop gui, file appears successfully excluded when git status is run on cmdline]

### Screenshots

<img width="252" alt="Screenshot 2024-11-18 at 6 43 42 PM" src="https://github.com/user-attachments/assets/34685b8c-7e6a-4969-bebc-be8ec5efd44a">
<img width="445" alt="Screenshot 2024-11-18 at 6 43 52 PM" src="https://github.com/user-attachments/assets/e6dbe49c-9282-4b32-b03c-9140ada1ca81">

**Comment by sergiou87** [comment]
Hello @sararielle ! 👋 

Maybe I'm missing something, but the command line screenshot also shows that file. If the file appears in the output of `git status`, it will show up on Desktop 🤔 

So, what do you mean by "file appears successfully excluded when git status is run on cmdline" ?

**Comment by sararielle** [comment]
I’m not great at Git but in my experience things listed (like they are on
the command line) don’t get included in the commit or get overwritten.  I need the file (which exists in other branches) to be different on my branch and remain so, without ever getting committed.

**Comment by sararielle** [comment]
just ignore me. don't worry about it.

**Comment by steveward** [comment]
@sararielle if the file was previously committed you'll need to run this command to ignore it in Git:

`git rm --cached index.php`

**Comment by steveward** [comment]
I'm going to close this out, but let me know if that doesn't get things working.
