### ISSUE TITLE
Chinese characters error

### ISSUE THREAD

**Issue by evrmji** [desktop/desktop#1958]
## Issue
If Chinese characters were writen in file, in Github desktop will show it as garbled, but if will be normally  if it in github. Just like this:
![a](https://user-images.githubusercontent.com/20814857/26967808-3340e142-4d32-11e7-8a29-93284b79b869.jpg)
_The file was encoded by **utf-8.**_

GitHub Desktop version was 0.6.0, was running in **Microsoft windows 10 Enterprise x64 Bulid 14393**.

And:
![b](https://user-images.githubusercontent.com/20814857/26967932-b9c460c2-4d32-11e7-9a0f-06099a9a1fcc.jpg)

**Comment by evrmji** [comment]
#1954 was same issue as this one, it commented earily than this one about two hour

**Comment by joshaber** [comment]
Thanks! We'll track this in https://github.com/desktop/desktop/issues/1954.
