### ISSUE TITLE
Add branch creator

### ISSUE THREAD

**Issue by Miran31** [desktop/desktop#19587]
### The feature request

In the github desktop application ... in branching tab.. there is no way how to see which one is my branch and which one is which branch .. i nned to go the github website to check . its time consuming ... why dont you add who is created the branch ... and last modified .. or can track for each branch .. 
![Screenshot (307)](https://github.com/user-attachments/assets/79c1503a-4091-4067-91a9-6351bc206ada)

### Proposed solution

1. add branch created name in the branch list. so we can know whose branch is this

**Comment by steveward** [comment]
@Miran31 thanks for the issue. If you have this issue it's recommended to prefix your branch names to prevent this, i.e. `steveward-new-feature`. The branch list on GitHub doesn't show a branch creator:

![Image](https://github.com/user-attachments/assets/95aa15a4-d5a3-49dd-9952-69736c9ade4b) 

But the overview does show the most recent commit author. This feedback is also loosely captured in https://github.com/desktop/desktop/issues/8048, which is our tracking issue for branch list improvements:

>The branch creation date doesn't provide any relevant information to me - instead, seeing when the branch was last updated (and possibly by whom) would be more useful.

I'll reference this feedback there and close this out.
