### ISSUE TITLE
Duplicate co-author show duplicate avatar.

### ISSUE THREAD

**Issue by Snoopy1866** [desktop/desktop#19597]
### The problem

If a commit details contains the same `co-authored-by` description as the pull request author, the avatar will replicate in the commits history. However, the above not happened on Github in the broswer.

![image](https://github.com/user-attachments/assets/89f6ed71-73ed-44c3-9675-7b47c50f7f20)

for example, this commit: https://github.com/PyStatPower/PyStatPower/commit/0194343ce46d8736dfee40e2e4970adb89bc687b

### Release version

3.4.10-beta1 (x64)

### Operating system

windows 11 23H2 (22631.4460)

### Steps to reproduce the behavior

1. Fork https://github.com/PyStatPower/PyStatPower.git
2. Go to commit `0194343ce46d8736dfee40e2e4970adb89bc687b`
3. Find the duplicate pre-commit avatars

### Log files

[2024-11-22.desktop.beta.log](https://github.com/user-attachments/files/17867234/2024-11-22.desktop.beta.log)

### Screenshots

![image](https://github.com/user-attachments/assets/9052fbf3-4c58-4e20-8dd6-53de3781ee5e)

![image](https://github.com/user-attachments/assets/7cedebb6-46a6-4c7d-9c8d-844ab8c86e6e)

**Comment by tidy-dev** [comment]
I checked [the logic for getting our commit authors](https://github.com/desktop/desktop/blob/dd6b9b58b3bc6149403b918c4b6df59530d9d53a/app/src/models/avatar.ts#L28) and we:

1. Add the `commit.author`
2. Add the `commit.coAuthors`
3. Add the `commit.committer` if committer !== the author and the commit !== webflow and committer does not match the name and the email of a coAuthor. 

We could improve this logic to loop through the `commit.coAuthors` and only add the coAuthor if it does not match the name and the email of the `commit.author`.
