### ISSUE TITLE
Unable to sync between source repository branch and forked repository branch when existing in Bitbucket.

### ISSUE THREAD

**Issue by ScarletMcLearn** [desktop/desktop#19590]
### The feature request

Given I am in Forked Bitbucket repo branch.
I cannot sync with Upstream Bitbucket repo branch.

### Proposed solution

I should be able to sync with Upstream Bitbucket repo branch.

**Comment by steveward** [comment]
@ScarletMcLearn thanks for the issue. GitHub Desktop doesn't have the same level of integration for third-party hosting services when it comes to forks, but you should be able to get things working by following these steps in the command line:

`git remote add upstream <upstream_remote_URL>`
`git fetch --all`

That will add a new `upstream` remote, and then the fetch command will fetch all the branches from that remote. You should then see the upstream branches in the branch list. I hope that helps!

**Comment by ScarletMcLearn** [comment]
Hello @steveward . Thank you for your response.
Can you please help out with something else?
When I run the commands you suggested and fetch origin, the main from source is shown in branches.
But when I try to make current branch the upstream: main branch, it says error branch with that name already exists.
How do I resolve this issue?
