### ISSUE TITLE
Show the project structure IN THE GUI

### ISSUE THREAD

**Issue by AMDphreak** [desktop/desktop#19609]
### The feature request

Show the project structure in the GUI! Why must this be said? This is so obvious. Making a repository manager without including a way to browse the local repository within the manager is like going to school without ever seeing a teacher. It doesn't work. You need to *show* people things, not just provide a way for them to modify them. I've never liked your GUI, but it's stayed dumb and underdeveloped for a decade now. Use correct design principles when conceptualizing software.

### Proposed solution

Show the project structure in the GUI! Why must this be said? This is so obvious. Making a repository manager without including a way to browse the local repository within the manager is like going to school without ever seeing a teacher. It doesn't work. You need to *show* people things, not just provide a way for them to modify them. I've never liked your GUI, but it's stayed dumb and underdeveloped for a decade now. Use correct design principles when conceptualizing software.

**Comment by tidy-dev** [comment]
@AMDphreak Thank you for your suggestion! However, viewing the files and/or file structure of a repository is not in the scope of GitHub Desktop. However, you may find the shortcuts to open your repository in your file explorer or in your editor helpful. These shortcuts can be found in the main window when there are no changes present as well as under Repository main menu.

**Comment by AMDphreak** [comment]
> @AMDphreak Thank you for your suggestion! However, viewing the files and/or file structure of a repository is not in the scope of GitHub Desktop. However, you may find the shortcuts to open your repository in your file explorer or in your editor helpful. These shortcuts can be found in the main window when there are no changes present as well as under Repository main menu.

"Is not" and "should not" are two different things. It should be in the scope of GitHub Desktop.
Also within the scope of GitHub desktop should be making it bloody obvious to programmers that there is a distinction between their code directory and the local repository that is hidden from view. Both of these are referred to as the "local repository" in the minds of new programmers.

**Comment by AMDphreak** [comment]
Let me remind you that your job as a GUI developer is to provide the mental model for users of the software. Your bad philosophy is that the user should already have a full understanding of the system that your GUI is manipulating. Your GUI toolkit and choice of widgets/controls provides a very poor implementation of mental model.

You Linuxers just never learn. GUI is the main goal of software, not an afterthought to make people shut up about it. Master GUI design, don't just fake it.
