### ISSUE TITLE
Amend any commit in history

### ISSUE THREAD

**Issue by nidegen** [desktop/desktop#19606]
### The feature request

Currently, one can only amend the last commit (it is a great feature).

It would be great to also amend the second or third last commit. Currently I usually commit a WIP and drag&drop-squash it into the older commit.

### Proposed solution

Ideally, it would work like the current amend but just for some later commits too.

I see that it is a bad idea to allow it for any commit, but the same applies for the squashing UI.

**Comment by steveward** [comment]
Thanks for the feedback @nidegen. The ability to amend previous commits would be involved with supporting interactive rebases, which is being tracked in https://github.com/desktop/desktop/issues/12354. You can follow along there for updates.
