### ISSUE TITLE
Undo Discarded Stash Changes

### ISSUE THREAD

**Issue by sinbadthepoet** [desktop/desktop#19601]
### The feature request

In attempting to apply a stash and solve merge conflicts, I pressed discard changes in an attempt to discard the changes to a single file, but it discarded changes across the stash. The stash is now lost, and I am unable to recover it. Those stashed changed should be recoverable in some way.

### Proposed solution

According to [this StackOverflow post](stackoverflow.com/questions/35546133a/how-can-i-undo-discard-changes-in-github-desktop), Github Desktop can already have the version of the file with the changes applied sent to the recycling bin/trash, though it seems this doesn't apply for stashes. Simply ensure this functionality is the same across all types of discards.

**Comment by steveward** [comment]
@sinbadthepoet thanks for the issue. The stashes may be recoverable -- can you share the log file from GitHub Desktop so I can take a look?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
