### ISSUE TITLE
Filter to only tagged commits

### ISSUE THREAD

**Issue by adrianspacely** [desktop/desktop#19618]
### The feature request

Would be great if you could filter to only tagged commits.

### Proposed solution

Tags and releases tab as a filter view version of the commits tab.

### Additional context

I have a mystery bug at work and it would be useful to simply click through tagged commits we attach for releases.

**Comment by tidy-dev** [comment]
@adrianspacely Thank you for the suggestion! We are tracking feedback for being able to find tags more easily in https://github.com/desktop/desktop/issues/15702. Thus, I am closing in favor it. Please add a thumbs up to that issue if you would like to voice your support for it.
