### ISSUE TITLE
GitHub Desktop issues - could not write to index - a lock file already exists

### ISSUE THREAD

**Issue by emmanuelesparza01** [desktop/desktop#19620]
### The feature request

![Screenshot 2024-11-26 134359](https://github.com/user-attachments/assets/7a7c7ec9-1c2f-4d96-adf5-758cae1dc84b)
![Screenshot 2024-11-26 143013](https://github.com/user-attachments/assets/9cadbe4a-d8cb-429a-845c-83340ecb32f2)
I'm not able to stash changes or discard changes and pull from origin into the new branch in GitHub Desktop. 

### Proposed solution

![Screenshot 2024-11-26 134359](https://github.com/user-attachments/assets/e7bf9c08-ff77-4353-92e0-8f9422eebb97)
![Screenshot 2024-11-26 143013](https://github.com/user-attachments/assets/e3006300-2009-4daa-86e3-970950de7009)

### Additional context

![Screenshot 2024-11-26 134359](https://github.com/user-attachments/assets/573dc256-d693-4b6d-b6eb-c3ae117428fd)
![Screenshot 2024-11-26 143013](https://github.com/user-attachments/assets/b5787939-ea34-497f-af23-05fba01c3fc0)

**Comment by tidy-dev** [comment]
@emmanuelesparza01 Thank you for reaching out!

We have seen this issue occur for a couple of reasons:
1. The repository is open in another program locking the files.
2. The repository is stored on a cloud storage and interfering with git.

For 1, close the locking software. For 2, move your repository out of cloud storage.
