### ISSUE TITLE
GitHub Desktop issues

### ISSUE THREAD

**Issue by emmanuelesparza01** [desktop/desktop#19623]
### The problem

I'm having issues with GitHub Desktop right now because whenever I try to right click and select stash changes or discard changes on the deleted files underneath changes. It kept showing an error message. 

### Release version

GitHub Desktop version 3.4.3

### Operating system

Windows 11

### Steps to reproduce the behavior

I'm having issues with GitHub Desktop right now because whenever I try to right click and select stash changes or discard changes on the deleted files underneath changes. It kept showing an error message. 

### Log files

![Screenshot 2024-11-27 100312](https://github.com/user-attachments/assets/266d28b2-58ab-4239-a0f9-e52ba31e229f)

### Screenshots

![Screenshot 2024-11-27 100312](https://github.com/user-attachments/assets/298a255e-cefb-4fe3-99dd-aeb9d31f5c61)

### Additional context

I'm having issues with GitHub Desktop right now because whenever I try to right click and select stash changes or discard changes on the deleted files underneath changes. It kept showing an error message.

**Comment by tidy-dev** [comment]
@emmanuelesparza01 Please respond in https://github.com/desktop/desktop/issues/19620 for your issues.
