### ISSUE TITLE
GitHub Desktop issues

### ISSUE THREAD

**Issue by emmanuelesparza01** [desktop/desktop#19624]
### The feature request

I'm having issues with GitHub Desktop right now because whenever I try to right click and select stash changes or discard changes on the deleted files underneath changes. It kept showing an error message. 

### Proposed solution

I'm having issues with GitHub Desktop right now because whenever I try to right click and select stash changes or discard changes on the deleted files underneath changes. It kept showing an error message. 

### Additional context

![Screenshot 2024-11-27 100312](https://github.com/user-attachments/assets/ed588399-4b88-435e-83a6-b9efa4c122e5)

**Comment by tidy-dev** [comment]
@emmanuelesparza01 Please respond in https://github.com/desktop/desktop/issues/19620 for your issues.
