### ISSUE TITLE
Need search option for commit

### ISSUE THREAD

**Issue by PratikBali** [desktop/desktop#19621]
### The feature request

Search should be added in history 

### Proposed solution

there is nothing from beginning in GitHub desktop to find commits by search text

**Comment by tidy-dev** [comment]
@PratikBali Thank you for the suggestion. We are tracking the feedback for searching commits in https://github.com/desktop/desktop/issues/7022. Closing this in favor of that issue. Please thumbs up that issue to voice your support.
