### ISSUE TITLE
Github Desktop does not install properly. (3.4.9 above)

### ISSUE THREAD

**Issue by Kunstfreiheit** [desktop/desktop#19625]
### The problem

I have noticed that Github Desktop does not install properly on my device since the newest release (yesterday), it has worked before.

### Release version

3.4.9 above, 3.4.8 works

### Operating system

Windows

### Steps to reproduce the behavior

1. Download any installer 3.4.9 or above
2. Try installing
3. it flat out does not work (fails) or only installs a part of the files

### Log files
Installing does not leave logs of its own.
Event viewer Logs are in german. use google translate or ask further questions if needed. may have some unrelated logs in between. Taken from the Application Tab. i redacted some info that seems sensitive. includes multiple deletions of partly installed files and attempts at reinstalling

[Event viewer Logs.txt](https://github.com/user-attachments/files/17939115/Event.viewer.Logs.txt)

### Additional context

i opened github desktop today, fetched the newest state of a private github, and closed it again. then it stopped working (because it presumably updated?)
Multiple combinations of reinstalling different current versions and past versions (latest 3.4.9) and restarting my PC did not work. using the normal installer opens the "installing" window for a split second then closes it immideately, with no logs dispensed in the event manager, but leaving most of the files installed, but not enough for the program to work. running it in administrator does not work. in this state, opening the app does not work (it does not open), administrator or not.
using the system wide installer fails with logs dispensed in the event viewer and no files installed.

**3.4.8 installed successfully.**

**Comment by Kunstfreiheit** [comment]
after i closed the 3.4.8 version and opened it again, it successfully updated to 3.4.9 without problems, which is weird because i definitely tried installing 3.4.9 before.

**Comment by niik** [comment]
Hey @Kunstfreiheit, happy to hear you were able to resolve the issue. If you run into this again please let us know but for now I'm going to close this out. Thanks!
