### ISSUE TITLE
Show Shortcut to open in terminal along other shortcuts

### ISSUE THREAD

**Issue by mfsbo** [desktop/desktop#19631]
### The feature request

When you are on a repo you see following screen 
![image](https://github.com/user-attachments/assets/4a4e356d-6ddd-482b-bc58-9122c6822464)
The shortcuts listed are missing one shortcut that is available in menu. The menu looks like this
![image](https://github.com/user-attachments/assets/b5486474-12a3-43ed-9dda-97bd76cda5e4)
In order to open the repo in terminal the user has to go to menu and click on open in terminal when using mouse. The option to open in Terminal is missing from top screen

### Proposed solution

Show the option to open in terminal with other options. In some scenarios not all these options are needed so it might be better to give user a setting to choose which of these shortcuts should be shown on screen and you can keep Open in Github all the time and not available to be changed and rest of them based on user choice. The order of these can also be a setting.

## Phase I
- Introduce a shortcut similar to "open this repository in your external editor..." called "Open this repository in your terminal"
- show link to options where user can choose which terminal is default. It can be same link as external editor as the options are on same page.
- Show the shortcut to open in terminal
- Show the button to open in terminal

## Phase II
- Allow user to customise which shortcuts to show by ticking them in options
- Allow user to order the shortcuts so they can show their prefferred option on top

### Additional context

Although the ability to open in termional is available via short cut `Ctrl` + &#x60; when a repo a repo is open. This will allow people using mouse to not go to menu and then click similar to Show in Explorer or View on Github. It will also help people understand another function available on repo.

**Comment by niik** [comment]
Hey @mfsbo, thanks for reaching out. This has been discussed and we've decided against adding it in https://github.com/desktop/desktop/issues/6674. Please add a 👍 on that original issue to indicate your support for it. We regularly asses reactions in issues (even closed ones).
