### ISSUE TITLE
User Guides are not accessible from the app

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#1963]
### Description

We have a collection of User Guides that are accessible from the main Desktop site, but no Help menu item to take the user to them exists in the app:

<img width="444" src="https://user-images.githubusercontent.com/359239/26976117-e323a778-4cf8-11e7-82a5-a2a9acdf5812.png">

### Version

**GitHub Desktop version:** 0.6.0

**OS version:** macOS Sierra 10.12.5

### Steps to Reproduce

1. Launch the application.
1. Feel unclear about something.
1. Click the Help menu.

**Expected behaviour:** see a menu item which links to the User Guides: https://help.github.com/desktop-beta/guides/

**Actual behaviour:** no helpful menu item 😢 

**Reproduces how often:** 100%

**Comment by alealues** [comment]
trying to fix

**Comment by shimpossible** [comment]
The build error may be because of #1430
