### ISSUE TITLE
Add commit message "Summary" length counter

### ISSUE THREAD

**Issue by andriipugach** [desktop/desktop#19630]
### The feature request

When using tools to lint and validate commit messages usually there is a limit to message summary (the first line). For example, https://github.com/conventional-changelog/commitlint limits the first line length to 72 or 100 chars depending on the config. It would be user-friendly to see the length of the commit summary on the UI.

### Proposed solution

Display "Summary" characters counter next to the input

**Comment by niik** [comment]
Hey @andriipugach, thanks for reaching out. We don't have any plans of adding a commit message counter per se but I did want to call out our commit message length warning which will show once the summary exceeds 50 characters.

<img src="https://github.com/user-attachments/assets/620791b7-80d4-4932-95f4-db3dcae09f08" width="620" />

<img src="https://github.com/user-attachments/assets/43984028-2c7e-4221-9221-1c7caf019570" width="439" />

See https://github.com/desktop/desktop/issues/2055 for the context that lead up to the existing commit message length warning.
