### ISSUE TITLE
The remote disconnected. Check your Internet connection and try again.

### ISSUE THREAD

**Issue by ewanuno** [desktop/desktop#19634]
### The problem

one particular repository always fails to upload, others are unaffected

the error says: The remote disconnected. Check your Internet connection and try again.

### Release version

Version 3.4.9 (x64)

### Operating system

macOS monterey 12.7.6

### Steps to reproduce the behavior

1. select the repository AtariExportMidiClone
2. click Publish Branch
3. upload fails

### Log files

[2024-11-30.desktop.production.log](https://github.com/user-attachments/files/17965009/2024-11-30.desktop.production.log)

### Screenshots

![image](https://github.com/user-attachments/assets/85fed403-71e1-4655-b912-e5f86a880aca)

**Comment by steveward** [comment]
@ewanuno it looks like the clone is timing out:

```
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
send-pack: unexpected disconnect while reading sideband packet
```

Some users have had also success running this command to try and prevent timeouts:

`git config --global http.postBuffer 157286400`

Let me know if that doesn't get things working.

**Comment by ewanuno** [comment]
ok, that worked, thanks!
