### ISSUE TITLE
"fix my line endings woes" workflow

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#1964]
### Description

We just merged #1906 which is some basic support for displaying when Git detects your line endings have changed in a file. This can be scary, but generally can be fixed once you understand the problem. GitHub has a great resource on this, if you ever find yourself stuck: https://help.github.com/articles/dealing-with-line-endings/

The back story on line endings and Git is best summarized in [this blog post](http://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/), and is highly recommended to steel yourself for what's next.

### First Idea - Sane Defaults

Most line-endings issues come down to the fact that a `.gitattributes` file doesn't exist in the repository, and so Git will fall back to the `core.autocrlf` - and this can vary from machine to machine. 

So a simple `.gitattributes` file like this will go most of the way to preventing issues in the future:

```
* text=auto
```

As per [the docs](https://git-scm.com/docs/gitattributes#gitattributes-Settostringvalueauto):

> When text is set to "auto", the path is marked for automatic end-of-line conversion. If Git decides that the content is text, its line endings are converted to `LF` on checkin. When the file has been committed with `CRLF`, no conversion is done.

### Second Idea - Normalize Repository

After getting things setup, any time you touch an existing file Git will jump up and try and fix up the line endings - being a great annoyance. So why not help them put together a PR to normalize the line endings automagically? Or a new branch they can then just merge into `master`?

This is the CLI version of what we could guide the users through (i'd like to retest this and ensure it's all accurate):

```
git checkout -b normalize-line-endings
rm .git/index
git reset
git add -u
git add .gitattributes
git commit -m "Normalize all the line endings"
```

### Other Thoughts

We haven't really kicked off ideas around workflow and how to do this in the app, so I'm happy to let this sit for now while we tackle more pressing needs.

**Comment by alealues** [comment]
.gitattributes

**Comment by alealues** [comment]
git checkout -b normalize-line-endings
rm .git/index
git reset
git add -u
git add .gitattributes
git commit -m "Normalize all the line endings

**Comment by t7m** [comment]
#1906 isn't really all that helpful. So it warns that line endings are changed... and? I still see hundreds of files are "changed" when only a couple are (bad). Then after checking in the hundreds of files, the GitHub website does correctly show that only a couple files are different (good).

Is a proper fix coming for this?

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by flaminggenius** [comment]
this is a pressing need when we have 300 files that need to be uploaded but we have to go through the individually

**Comment by t7m** [comment]
Somehow this is not at all important to GitHub. :(
