### ISSUE TITLE
Updates are done in the background, which makes the progress of the update unclear when attempting to close the app during an update

### ISSUE THREAD

**Issue by PowerfulBacon** [desktop/desktop#19646]
### The problem

You cannot close the github desktop application when an update is in progress, however it doesn't have any indication as to whether or not an update is installing and it doesn't tell you the progress.

### Release version

Version 3.4.8 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Attempt to close the application while github desktop is installing an update (This is relatively tricky, since there is no way that I can tell to trigger an update instantly. To reproduce this, something will need to be added that simulates or forces the application to start installing an update package)
2. You will be told that you need to wait until the update is complete or the installation will break. There is no indication anywhere that an update is in progress, and no progress bar to tell you how much it has completed.

### Screenshots

![image](https://github.com/user-attachments/assets/13ae27eb-5fcd-489e-b21f-5146b01b6b38)

I am told that I cannot close the application, but there is no progress on the update and no indicator anywhere else that an update is being performed.

This is highly confusing, it tells me that I shouldn't close the application yet it feels like broken behaviour where I would be forced to close the application to fix it (it is unclear if the program is hanging or actually working).

**Comment by steveward** [comment]
Thanks for the feedback @PowerfulBacon. I'm going to add this to https://github.com/desktop/desktop/issues/9782 where we are tracking feedback about having an update progress bar.

**Comment by jimmywho404** [comment]
I still have this issue. Is there something I can do either finish the "update" or remove the screen. This happens to me every time I open GitHub Desktop.

**Comment by sach-indev** [comment]
This is still a problem that's not solved.

**Comment by SherlockCones** [comment]
still not solved

**Comment by crontab** [comment]
This can happen if you quit the app while syncing a repo ("Fetch origin" button). I did it on purpose to see how GitHub Desktop handles it, i.e. does it finish the sync? Does it interrupt it? It probably does finish it but also what I got was this message (in this issue report) on next launch and attempt to quit. Very annoying. It did go away by itself eventually, after several launches/quits.
