### ISSUE TITLE
Possibility to view current branch in repository dropdown

### ISSUE THREAD

**Issue by patricsjoo** [desktop/desktop#19659]
### The feature request

A possibility to enable "view current branch in repository list". This helps a lot if you're using many repositories and want a better overview. It also helps a lot if you have cloned your repository twice in separate folders because of working in multiple branches at the same time.

### Proposed solution

Add a setting in options to "view current branch in repository list".
This enable an extra description in the dropdown for repositories and write "`<Repository-name> (<branch-name>)`" or similar.

**Comment by steveward** [comment]
Thanks for the feedback @patricsjoo. This is being tracked in https://github.com/desktop/desktop/issues/8158, please follow along there and upvote to show your interest. I'm going to close this out.
