### ISSUE TITLE
Prefill the issue template when clicking “Report Issue…”

### ISSUE THREAD

**Issue by j-f1** [desktop/desktop#1965]
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

When clicking “Report Issue…,” the input box has places for the versions of various components. These are not automatically filled out

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** `master`  
**OS version:** N/A

### Steps to Reproduce

1. Click “Report Issue…”

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behaviour:** Version info is automatically prefilled

**Actual behaviour:** Version info not automatically prefilled

**Reproduces how often:** 100%

<sub>Sorry, clicked submit too early</sub>

**Comment by shiftkey** [comment]
We did mention this in https://github.com/desktop/desktop/issues/1617#issuecomment-302413319 but providing a custom `body` argument will overwrite the issue template, so we'd need to have the issue template embedded in the app, pre-populate it and encode it correctly before launching the browser (and hopefully the browser will accept it).

**Comment by j-f1** [comment]
The app could download the template on startup.

**Comment by alealues** [comment]
fixed

**Comment by alealues** [comment]
git rev-parse HEAD

**Comment by shimpossible** [comment]
Only download the template when clicking 'report issue'.  Otherwise people will download all the time even if there are no issues

**Comment by tierninho** [comment]
Perhaps we could just host a form within Desktop which gets posted as an Issue on our repo? A lot of the info could be extracted and pre-populated, like OS, build number, etc...

**Comment by shiftkey** [comment]
This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by billygriffin** [comment]
Given that we use multiple issue templates now and hopefully they're a bit better, if not perfect, at nudging people toward providing the right information, this seems like it'd be trickier to implement for not an enormous benefit. I'm going to remove `future-proposal` to allow for focus on other things. Definitely a cool idea and appreciated @j-f1, so thank you. ❤️
