### ISSUE TITLE
Show more than 5 recent branches

### ISSUE THREAD

**Issue by gitsakos** [desktop/desktop#19664]
### The feature request

I'm often juggling between more than 5 branches at a time.  5 simply is not enough, and I find myself having to dig deeper to recall the name of a working branch I may have created earlier in the day.

### Proposed solution

Three proposed solutions:

1) Simply increase the number of recent branches to 7-10 
2) Provide a user preference for number of recent branches to show
3) Get rid of recent branches entirely and simply sort all branches by most recently used.

### Additional context

I'd prefer option 3) as it provides valuable insight as to your work history over the last several days/weeks/months

**Comment by Jeff9049** [comment]
> ### The feature request
> 
> I'm often juggling between more than 5 branches at a time.  5 simply is not enough, and I find myself having to dig deeper to recall the name of a working branch I may have created earlier in the day.
> 
> ### Proposed solution
> 
> Three proposed solutions:
> 
> 1) Simply increase the number of recent branches to 7-10 
> 2) Provide a user preference for number of recent branches to show
> 3) Get rid of recent branches entirely and simply sort all branches by most recently used.
> 
> 
> ### Additional context
> 
> I'd prefer option 3) as it provides valuable insight as to your work history over the last several days/weeks/months

**Comment by Jeff9049** [comment]
What is the prize money for the payment of the gift 🙏🎁 from the store and GitHub profile to pay me out with money

**Comment by steveward** [comment]
Thanks for the request @gitsakos. This is being tracked in https://github.com/desktop/desktop/issues/14311, so you can follow along there for updates and upvote to show your interest.
