### ISSUE TITLE
Add the ability to recursively discover all repositories under a directory and select which ones to add to the app

### ISSUE THREAD

**Issue by Rekkonnect** [desktop/desktop#19662]
### The feature request

I have tons of repositories, and sometimes I forget to import them in the app. I have to manually add every single one of those repositories, entering the full path of the repository every time. This quickly gets annoying, especially when I've organized all my repositories under a single directory, making it easy to locate the one of interest.

### Proposed solution

Add a button under "add existing repository" about mass-adding repositories that can be discovered under a specific directory. It would traverse the directories recursively until it encounters a .git folder (which will prevent nested Git repositories from being discovered). If it would take long, lazy loading the repositories will be nice to have.

Since some of those repositories may be already imported in the app, the list could initally include all the repositories that are added in the app, showing them as already imported, and then slowly building up showing the unimported ones.

### Additional context

This would be a massive improvement for the reason that repositories are not globally indexed. That way, GitHub Desktop will serve more as a repository manager by making it easier to discover repositories across the file system given a root path.

**Comment by steveward** [comment]
Thanks for the feedback @Rekkonnect. This has been previously discussed in https://github.com/desktop/desktop/issues/1574, but at this time this feature is not on our radar. You can quickly add multiple repositories by bulk selecting them and dragging and dropping them directly into GitHub Desktop. 

I'm going to reference this issue in https://github.com/desktop/desktop/issues/1574 and close this one out.
