### ISSUE TITLE
Add default repo location option

### ISSUE THREAD

**Issue by sour-dani** [desktop/desktop#19675]
### The feature request

Add the ability to set a default location for repos to be located so by default it will choose the default location instead of the previous one.

### Proposed solution

Optional ability to choose a default directory and have that default directory stored until disabled. This would prevent issues where users accidentally clone repos into the previously cloned directory if they click through the options too fast. This would benefit user file management by keeping repos in one location instead of spread across their computer.

**Comment by steveward** [comment]
Thanks for the feedback @sour-dani. We're tracking feedback around this in https://github.com/desktop/desktop/issues/13017 so I'm going to close this out and reference this issue there.

**Comment by steveward** [comment]
Also, by default the app will remember your previous chosen location. So if you choose `~/Code`, that location will persist. When you're saying "previous location", what are you specifically referring to?

**Comment by sour-dani** [comment]
> Also, by default the app will remember your previous chosen location. So if you choose `~/Code`, that location will persist. When you're saying "previous location", what are you specifically referring to?

Just as you said, the previous chosen location. I just didn't say the word "chosen".
