### ISSUE TITLE
Fails To Launch After Update/Install

### ISSUE THREAD

**Issue by MeerkatRS** [desktop/desktop#19674]
### The problem

I had an old version (8.0) of Github Desktop installed that I didn't touch for years, so I updated it to the latest 3.4.9 version. After that it never would open, even if I tried opening it from its install path without using shortcut, I got nothing. So I looked up some fixes online, even the github issues, tried everything from uninstall and deleting files from %appdata% local and roam paths but still didn't work. When I install it pops up with a message that says it'll launch once it's done, but that message disappears after a few seconds then never opens. I've tried the beta version too, but same issue.

### Release version

3.4.9

### Operating system

Windows 11 64 bit

### Steps to reproduce the behavior

Potentially downloading the old 8.0 Github Desktop then updating through the About section might reproduce the same issue?

### Log files

[Squirrel-Install.log](https://github.com/user-attachments/files/18044351/Squirrel-Install.log)
[SquirrelSetup.log](https://github.com/user-attachments/files/18044352/SquirrelSetup.log)

**Comment by steveward** [comment]
Thanks for the report @MeerkatRS. I'm seeing a permissions error:

```
[06/12/24 02:56:04] warn: ApplyReleasesImpl: Failed to delete key: C:\Users\LoadingMeerkat\AppData\Local\GitHubDesktop\GitHubDesktop.exe: System.UnauthorizedAccessException: Cannot write to the registry key.
   at System.ThrowHelper.ThrowUnauthorizedAccessException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.EnsureWriteable()
   at Microsoft.Win32.RegistryKey.DeleteValue(String name)
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
```

Are you running any security or antivirus software that could be causing this?

**Comment by MeerkatRS** [comment]
@steveward I don't use any security or antivirus software, apart from Windows Defender, however I don't see anything being blocked/removed in the protection history, I also added the Github Desktop folder to the exclusion list already and that didn't change anything either.

**Comment by steveward** [comment]
Thanks for the update. Can you try deleting this directory to see if it helps at all?

`%LocalAppData%\SquirrelTemp\`

**Comment by MeerkatRS** [comment]
@steveward Doesn't change anything. I already did that before making the issue and also just tried it again.

**Comment by steveward** [comment]
Can you try creating a new user profile on your machine to see if you are able to install there? That would help rule out some potential issues.
