### ISSUE TITLE
Deleted branches still show locally

### ISSUE THREAD

**Issue by dvrtech-us** [desktop/desktop#19672]
### The feature request

The Github desktop client does not have a clean way to deal with remotely deleted branches. 

An example of this: 
- A XYZ branch is created, the work is done and a PR is created to merge that branch in. 
- A squash merged and deletion is done via the PR
- 
Everyone who worked on XYZ branch will still see their local copy of the branch with no indicator that it was deleted on the remote. 

### Proposed solution

1. Add an icon next to the branches that are remotely deleted, here is a potential mock up:
<img width="274" alt="image" src="https://github.com/user-attachments/assets/f1a04fe4-7f7d-4021-ab62-31674b3d2b3f">
2. It would be nice to have a option to remove remotely deleted branches

### Additional context

See: https://github.com/desktop/desktop/issues/5893
It seems a lot of people don't understand that a remote delete doesn't delete it locally and keep reporting it as a bug

**Comment by steveward** [comment]
@dvrtech-us thanks for the issue, but please don't open new issues if an existing issue has already been closed. We still consider issues even if they have closed, so the best option is to leave feedback and upvote the closed issue. There is also an existing issue for tracking a pruning option in https://github.com/desktop/desktop/issues/13310.

**Comment by dvrtech-us** [comment]
Sorry, I thought it was closed because they thought it was a bug but really isnt.  I didn't see that other issue but that makes sense and thanks for looking at it.

________________________________

**Comment by d-lee-raimondi** [comment]
> [@dvrtech-us](https://github.com/dvrtech-us) thanks for the issue, but please don't open new issues if an existing issue has already been closed. We still consider issues even if they have closed..

Evidently you don't . The original issue (#5893) was sitting out there for 4 years accumulating comments from frustrated users and pleas for a fix. Then it was closed 2 years ago without any meaningful fix or explanation why it was closed, and for the last 2 years users had been begging you to reopen the issue and fix the problem. To no avail
