### ISSUE TITLE
white screen in MacBookPro 2019

### ISSUE THREAD

**Issue by stack-wuh** [desktop/desktop#19678]
### The problem

<img width="1165" alt="image" src="https://github.com/user-attachments/assets/b389c4ce-ca30-4e35-bee4-5e1f7627329b">

### Release version

3.4.9

### Operating system

macos 15.1.1

### Steps to reproduce the behavior

just open app, the screen is white

### Screenshots

<img src="https://src.wuh.site/2024-12/2024-12-08-102647.png" />

**Comment by steveward** [comment]
Thanks for the issue @stack-wuh. Can you try resetting GitHub Desktop by running this command?

`rm -rf ~/Library/Application\ Support/GitHub\ Desktop`

That should hopefully resolve this issue and get things working again. Let me know if it doesn't.
