### ISSUE TITLE
Switch Profile 

### ISSUE THREAD

**Issue by arbabsabir337** [desktop/desktop#19681]
### The feature request

Please add a switch profile option to GitHub Desktop to allow multiple accounts within a single app.

### Proposed solution

Adding a switch profile option to GitHub Desktop would significantly enhance user experience by allowing seamless transitions between multiple accounts. Currently, switching accounts requires logging out and then logging back in, which can be time-consuming and cumbersome, especially for users who manage multiple repositories across different accounts

**Comment by steveward** [comment]
Thanks for the issue @arbabsabir337. This is being tracked in https://github.com/desktop/desktop/issues/3707, so you can follow along there for updates.

**Comment by PadreCarlo** [comment]
Is being tracked, really? It's been being neglected for 7 years I would rather say.
