### ISSUE TITLE
Can't access menu in Welcome flow for Windows

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1968]
In full screen mode, I can't access menu in the Welcome flow. Seems like the exit, toggle dev tools, report an issue and help menu items would be useful to have access to. Tried the `alt` button but no results.

<img width="875" alt="screen shot 2017-06-09 at 1 47 50 pm" src="https://user-images.githubusercontent.com/14828183/26987623-4408a70c-4d1a-11e7-9597-7eb572e334cb.png">

v0.6.0, Windows 10

**Comment by niik** [comment]
@tierninho This is expected behavior, we don't render the app menu at all in the welcome flow on Windows. Was there anything in particular that you needed to access while in the welcome flow?

I'll close this for now but feel free to reopen if you want

**Comment by j-f1** [comment]
@niik 

> Seems like the exit, toggle dev tools, report an issue and help menu items would be useful to have access to

**Comment by tierninho** [comment]
@niik see above comment, but you can make the call if you guys want to add it in. It's just a small inconsistency with what Mac users have access to.
