### ISSUE TITLE
Unable to Clone Repository

### ISSUE THREAD

**Issue by ryancasler** [desktop/desktop#19686]
### The problem

I am unable to clone a repository from Github

### Release version

3.4.9

### Operating system

Windows 10

### Steps to reproduce the behavior

Clone the repository.

### Log files

Cloning into 'E:\Documents\GitHub\templates'...
remote: Enumerating objects: 48599, done.        
remote: Counting objects: 100% (2896/2896), done.        
remote: Compressing objects: 100% (1469/1469), done.        
remote: Total 48599 (delta 1559), reused 2675 (delta 1427), pack-reused 45703 (from 1)        
Receiving objects: 100% (48599/48599), 646.86 MiB | 64.25 MiB/s, done.
Resolving deltas: 100% (30820/30820), done.
Updating files: 100% (5882/5882), done.
      0 [main] sh 1675 child_copy: dll data read copy failed, 0x12D5000..0x12E2010, done 0, windows pid 17804, Win32 error 299
      0 [main] sh 1674 dofork: child -1 - forked process 17804 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
C:\Users\ryanc\AppData\Local\GitHubDesktop\app-3.4.9\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
1080218 [main] sh 1674 dofork: child -1 - forked process 16464 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\ryanc\AppData\Local\GitHubDesktop\app-3.4.9\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      1 [main] sh 1677 child_copy: dll data read copy failed, 0x12A5000..0x12B2010, done 0, windows pid 16648, Win32 error 299
3146034 [main] sh 1674 dofork: child -1 - forked process 16648 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
C:\Users\ryanc\AppData\Local\GitHubDesktop\app-3.4.9\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      0 [main] sh 1678 child_copy: dll data read copy failed, 0x16A5000..0x16B2010, done 0, windows pid 11684, Win32 error 299
7214809 [main] sh 1674 dofork: child -1 - forked process 11684 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
C:\Users\ryanc\AppData\Local\GitHubDesktop\app-3.4.9\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
15287857 [main] sh 1674 dofork: child -1 - forked process 11060 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\ryanc\AppData\Local\GitHubDesktop\app-3.4.9\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: Resource temporarily unavailable

Would you like to retry cloning ?

### Screenshots

![Screenshot 2024-12-09 171838](https://github.com/user-attachments/assets/d647c5ac-8138-4974-b59c-40ec3001ddc8)

**Comment by steveward** [comment]
Thanks for the issue @ryancasler. This error is usually caused by Mandatory ASLR, please see https://github.com/desktop/desktop/blob/development/docs/known-issues.md#enable-mandatory-aslr-triggers-cygheap-errors. Try disabling mandatory ASLR and let us know if that does not get things working!
