### ISSUE TITLE
!Verification script crash

### ISSUE THREAD

**Issue by SVS-Labuser** [desktop/desktop#19693]
### The problem

During Verification BPM Threshold adjusting, I accidentally hit "Enter" prior to entering a new value in the Python script. This caused the script to crash and fail. This was during adjusting Medium gain (not sure if this happens with Low and/or High gains.

![image](https://github.com/user-attachments/assets/cc17a674-00ce-48de-ad94-3bec379214bd)

### Release version

!Verification.py

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Run Verification, let it get to BPM adjustment steps
2. Click on "adjust value" (forgot exact terminology) button
3. Do not enter an adjustment, but just hit Enter

### Screenshots

@
![Verification Crash 12_10_24](https://github.com/user-attachments/assets/ca2deea0-7489-407a-a9a2-5760279af7a0)

**Comment by SVS-Labuser** [comment]
Addendum to this issue. I just ran !Verificaiton.py on this sensor and selected "Analyze Imagery?" (but not the other two options). the script determined that I had "Already confirmed NUCs are acceptable" and finished running. I did not do this, as per above the script crashed during Medium gain analyzation, so I did not confirm either Medium or High (01/02) NUCs

![image](https://github.com/user-attachments/assets/7da7d740-6d3f-4b66-a996-23fa4f3d0710)

**Comment by niik** [comment]
Hi, this issue doesn’t appear to be related to the GitHub Desktop application so I’m going to close this issue but  if you believe that's a mistake feel free to comment and we can revisit.

If you require assistance with a particular project on GitHub it's best to open an issue in the repository of that project. If you have a general support question please check out [GitHub support](https://support.github.com).

Best of luck!
