### ISSUE TITLE
!Verification script error messages

### ISSUE THREAD

**Issue by SVS-Labuser** [desktop/desktop#19696]
### The problem

Received this error message toward beginning of script. Not sure if it's critical, but wanted to report it: 
![image](https://github.com/user-attachments/assets/c23c23b5-12c1-4b0f-901e-2b93eb8fb8de)

### Release version

!Verification.py

### Operating system

Windows 10

### Steps to reproduce the behavior

Run script, wait for the magic.

**Comment by steveward** [comment]
@SVS-Labuser this issue looks like it is for a different project on GitHub. This issue tracker is specifically for GitHub Desktop.
