### ISSUE TITLE
"Delete Tag" menu option is greyed out and cannot be used.

### ISSUE THREAD

**Issue by Arthmoor** [desktop/desktop#19697]
### The problem

When creating a tag on a commit, it is impossible to later remove that tag via the Desktop UI because the option to do so is greyed out.

Deleting the tag via the UI on the GitHub website does not resolve the issue on the local repository copy either.

### Release version

3.4.9

### Operating system

Windows 10

### Steps to reproduce the behavior

Create a tag.
Push the tag to the origin.
Later decide to remove the tag.
Note that you can't because the option is greyed out.

Go to the website, delete the tag from the website UI.
Note that the local repository will not remove the tag that way either.

**Comment by niik** [comment]
Hey @Arthmoor, thanks for reaching out. GitHub Desktop currently doesn't support deleting tags which have already been pushed to the remote. Please see https://github.com/desktop/desktop/issues/9938#issuecomment-638779503 for an explanation of the technical reasons behind this and please add a 👍 reaction to that issue to indicate your support for enabling deleting already pushed tags.
