### ISSUE TITLE
Push Commits Using Old User Details After Logging Out

### ISSUE THREAD

**Issue by merbin2012** [desktop/desktop#19704]
### The problem

In my company, there are two types of projects. In one situation, the same system needs to be used by multiple users on the same computer. To handle this, I log out the previous user, log in as the new user, and then clone the repository to make changes to the project. However, when I push the changes, they are still uploaded with the previous user's details, even though that user has already logged out.

### Release version

Version 3.4.9 (x64)

### Operating system

Windows

### Screenshots

![image_2024_12_11T10_10_02_936Z](https://github.com/user-attachments/assets/dba1e273-f578-4518-90e3-0fb9f88384c0)

**Comment by steveward** [comment]
@merbin2012 your commit details are stored in your `.gitconfig`, and do not change when you log in/log out. You can change this by going to the `Git` section in the `Options` menu, or by clicking the avatar next to the commit pane.

See [this article](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user) for more information about how commit authorship works.
