### ISSUE TITLE
Quickly select files to submit

### ISSUE THREAD

**Issue by linwear** [desktop/desktop#19703]
### The feature request

Please support quick selection of files to be submitted.
In daily submission, we often select some files for submission. Sometimes there are many files in this part, and we can only check them one by one, which is very inefficient. I hope there will be a Mac system like this: for example, if I have 100 files to select, I click the first one with the mouse, and then hold down Shift and click the 100th file to select these 100 files.

### Proposed solution

Quickly select and distinguish the content to be submitted. 100 files only need 2 steps, no need to click 100 times

**Comment by VODINHCUONG90** [comment]
Hãy cùng toi xây dựng nao

**Comment by niik** [comment]
Hey @linwear,  thanks for reaching out. You should be able to do pretty much what you're suggesting by clicking on the first file you'd like to include, holding down shift and clicking on the last one. Once you've gotten all the files you want to include selected you can either press <kbd>Spacebar</kbd> or right click and select "Include Selected Files".

Hope that helps!
