### ISSUE TITLE
Unable to open Visual Studio 2022 as admin

### ISSUE THREAD

**Issue by ALeePS** [desktop/desktop#19712]
### The problem

Hello,

After configuring the devenv.exe to always run as administrator, it is failing to open as an external editor. I have added VS 2022 and GitHub Desktop to my system path. Removing administrator priveledges from visual studio allows it to open with no issues. I have attached a screenshot of the error for reference. Thank you!

### Release version

3.4.9

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Configure custom editor
2. Add path to administrator devenv.exe under "Path"
3. Save
4. Open your repository in external editor

### Screenshots

![image](https://github.com/user-attachments/assets/abfa35ce-2f15-441b-a798-4ebd3952fad9)

**Comment by sergiou87** [comment]
I don't think we can do anything about that… if you really need that, maybe you can also run GitHub Desktop as admin? That would probably fix it 😕
