### ISSUE TITLE
View Pull Request Content Menu Item Showing on Branches with No Pull Request on Current Branch Button

### ISSUE THREAD

**Issue by DylanDevelops** [desktop/desktop#19711]
### The problem

With the newest update and the changes I implemented earlier, I noticed that the option to view pull request is showing up on the current branch navigation bar section.

### Release version

3.4.10

### Operating system

macOS Sequoia 15.2 (24C98)

### Steps to reproduce the behavior

1. Go to a repository
2. Switch your current branch to a branch that doesn't have a pull request active
3. Right-click on the current branch button
4. See the context menu item that doesn't work when clicked

### Screenshots

<img width="323" alt="Screenshot 2024-12-12 at 10 04 22 AM" src="https://github.com/user-attachments/assets/2d3d4d80-5c9e-4ba2-b39c-3292baefb379" />

### Additional context

This is the feature I worked on, and I can try to work on a fix!

**Comment by steveward** [comment]
Thanks @DylanDevelops!

**Comment by DylanDevelops** [comment]
@steveward Just a quick question: is priority-3 higher priority than priority-1 or is it the other way around? I'm just curious 😂

**Comment by steveward** [comment]
@DylanDevelops in our repo `priority-3` is the lowest. Good question, though! 😄

**Comment by DylanDevelops** [comment]
@steveward Good to know! Thanks! Also, if I want to fix this issue, my changes from the original feature don't exist on the `development` branch since the pull request for `releases/3.4.10` has not been merged yet. Should I wait to fix this until that has been merged or can I make a pull request targeting `releases/3.4.10`?

**Comment by DylanDevelops** [comment]
I have fixed the issue! I did this while the new branch was checked out, but I'll wait to commit to whatever you say is the correct branch based on my comment above!

**Comment by DylanDevelops** [comment]
@steveward I ended up figuring out my issue. My forked repository was just out of sync with this one. I created a pull request that should fix the problem!
