### ISSUE TITLE
Branch Merge Results Differ Between Remote and Local

### ISSUE THREAD

**Issue by zeikar** [desktop/desktop#19710]
### The problem

Hello,

I’ve noticed some odd behavior with branch merging recently, and it seems that the behavior differs depending on whether the branch is remote or local. I’d like to request a review of this issue.

I’ve attached some screenshots for reference:

| Screenshot 1 | Screenshot 2 |
|--------------|--------------|
| <img width="443" alt="image" src="https://github.com/user-attachments/assets/81de3d7c-f89a-417b-98cf-b1a2df9ef8d6" /> | <img width="443" alt="image" src="https://github.com/user-attachments/assets/ed42d9c4-5709-4f33-9bfe-133cbb69214c" /> |
| Merging `origin/main` into branch `b`, shows up-to-date. | Merging the **local branch** `main` into branch `b`, shows 11 commits, which shouldn’t exist. |

| Screenshot 3 | Screenshot 4 |
|--------------|--------------|
| <img width="443" alt="image" src="https://github.com/user-attachments/assets/1e13f70b-3dc3-4bfe-8d40-190755b8be1e" /> | <img width="443" alt="image" src="https://github.com/user-attachments/assets/57a04125-f775-427b-ac88-dd7331b6645c" /> |
| Merging branch `b` into branch `c`, inconsistent behavior observed. | Another example of merging branch `b` into branch `c`. |

This doesn’t seem to happen consistently, but to help with testing, I’ve shared the repository I used for testing:
[https://github.com/zeikar/merge-test](https://github.com/zeikar/merge-test).

Thank you!

### Release version

3.4.10-beta3 (arm64)

### Operating system

macOS 15.1.1 (24B91)

### Steps to reproduce the behavior

1. Create a new repository.
2. Create a new branch.
3. Test merging between the local branch and the remote branch.

### Additional context

It seems to work correctly after restarting the application.

**Comment by sergiou87** [comment]
I cannot reproduce the first case with the `main` branch: it shows up as `up to date` with both `main` and `origin/main`. But I can repro the second case.

Thanks for the sample repository!! 🙇‍♂

**Comment by zeikar** [comment]
@sergiou87 Hi,  

Thanks for checking this out!  

I’ve found a simpler way to **consistently reproduce** the issue, although it doesn’t always happen perfectly for the first and second cases. I’ve recorded a video demonstrating the behavior:  

[Video Link](https://github.com/user-attachments/assets/79a1947a-df65-4e40-b9fa-add72fddabdf)  

### Steps to Reproduce:
1. Merge a branch into the current branch.  
2. Immediately try to merge the **same branch** again.  
3. Notice that the commit count is **not zero**, even though the branch has already been merged.  

I also took a look at this [pull request](https://github.com/desktop/desktop/pull/19626/files), where the **merge logic** was updated, and I suspect there could be an issue related to the **cache mechanism**.  

As a test, I modified the [range variable](https://github.com/zeikar/desktop/commit/793b6ee7fdca00fe92c787021f68a3346346f91b) in the code, and it seems to work correctly for me now.  

Let me know if you’d like more details or if I can assist with further testing!  

Thanks again for your help!
