### ISSUE TITLE
github desktop pixel interface 

### ISSUE THREAD

**Issue by santoIN** [desktop/desktop#19727]
### The problem

when i use github desktop the rest of the application start doing pixeling. i tryed to reinstall it , but it continues the issues

### Release version

Version 3.4.10 (x64)

### Operating system

windows 11

### Screenshots

![image](https://github.com/user-attachments/assets/28252997-5f9e-4720-931e-9a7779431cb7)

**Comment by steveward** [comment]
Thanks for the report @santoIN. Are you using an NVIDIA GPU? One user had this issue and shared the following:

>The issue was caused by Nvidia's global Antialiasing settings—specifically, the FXAA and Multi-Frame Sampled AA (MFAA) options being turned on. Restoring the default values resolved the blurred UI and font issue

You can also try launching GitHub Desktop with GPU accelerated rendering turned off to verify that it is indeed related to the GPU  by setting the `GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION` environment variable to 1 by running `set GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION=1` in cmd.exe and restarting your machine or by setting it through the UI following a [guide like this](https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0).

Note that you may have to restart your machine for the changes to take effect. 

I'm going to close this out, but feel free to follow up here with any questions.
