### ISSUE TITLE
The remote disconnected. Check your Internet connection and try again.

### ISSUE THREAD

**Issue by akshitr25** [desktop/desktop#19729]
### The problem

The remote disconnected. Check your Internet connection and try again.
![image](https://github.com/user-attachments/assets/3d447b91-443a-4feb-a97c-61485c8d5bde)

### Release version

Version 3.4.3 (x64)

### Operating system

windows 11

### Steps to reproduce the behavior

publish branch.

### Log files

[2024-12-17.desktop.production.log](https://github.com/user-attachments/files/18161347/2024-12-17.desktop.production.log)

**Comment by sergiou87** [comment]
👋 

Could you try running `git config --global http.postBuffer 157286400` in a terminal and then reopen Desktop?

**Comment by akshitr25** [comment]
Hi, it is still the same

**Comment by tidy-dev** [comment]
@akshitr25 The errors would indicate network limitations (this could be worse if it is rather large repo or repo with large files).  Unfortunately, asides from recommending increased buffer size which sometimes alleviates network limitations; there is little more help we can offer as network limitations are not a bug with GitHub Desktop.

If you suspect that it is an issue with GitHub Desktop, you could [attempt to clone the repository in the command line](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository#cloning-a-repository).
