### ISSUE TITLE
GPG commit error message

### ISSUE THREAD

**Issue by jccguimaraes** [desktop/desktop#1974]
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

I use GPG key in my commits, and when i commit through the app it gives an error.

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** 0.6.0

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** 10.12.5

### Steps to Reproduce

1. write a commit message
2. commit to master

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behaviour:** commit message and ask for password

**Actual behaviour:** `Commit failed - exit code 128 received, with output: 'error: gpg failed to sign the data
fatal: failed to write commit object'`

**Reproduces how often:** every time i have a repository with gpg enabled

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

If you are dealing with a performance issue or regression, attaching a
[Timeline profile](https://github.com/desktop/desktop/blob/master/docs/contributing/timeline-profile.md)
of the task will help the developers understand the runtime behaviour of the
application on your machine.

**Comment by shiftkey** [comment]
Looks like #1815 hasn't completely fixed our GPG integration woes

**Comment by gellerb** [comment]
@shiftkey I'm using Github Desktop 0.6.1 and I wasn't able to sign a commit. Was #1815 suppose to fix this?

**desktop.production.log:**
```
2017-06-21T18:43:43.322Z - error: [ui] `git commit -F -` exited with an unexpected code: 128.
error: gpg failed to sign the data
fatal: failed to write commit object
```

**Comment by shiftkey** [comment]
@jccguimaraes @gellerb so I missed this mention as part of the initial report:

> **Expected behaviour**: commit message and ask for password

We don't have the ability to detect when the commit operation requires user input, so this will continue to fail until we go deeper into #78.

**Comment by shiftkey** [comment]
As a workaround, I'd recommend looking at serving up the password using `gpg-agent` with a setup [like this](https://gist.github.com/bmhatfield/cc21ec0a3a2df963bffa3c1f884b676b) until we can get to this.

**Comment by shiftkey** [comment]
As this is dependent on the work in #78, I've added a comment about this flow to that issue and will close this out. Thanks for the report, please follow along with #78 for implementing this as a first-class feature!
