### ISSUE TITLE
Unable to find new updates post version 3.4.5

### ISSUE THREAD

**Issue by AaronMT** [desktop/desktop#19746]
### The problem

Currently, I am using Github Desktop Version 3.4.5 (arm64) on my MacOS 15.2 (24C101). When I hit check for updates it states that I have the latest version. I am unable to fetch updates to 3.4.X (currently [3.4.12](https://github.com/desktop/desktop/releases/tag/release-3.4.12))
<img width="451" alt="Screenshot 2024-12-18 at 11 06 38 AM" src="https://github.com/user-attachments/assets/9ebe8ca4-d138-4608-9798-cd257c53b5ff" />

There is nothing posted about checking for updates in the production level log in Finder.

### Release version

3.4.5

### Operating system

MacOS 15.2 (24C101)

### Steps to reproduce the behavior

1. About Github Desktop
2. Check for updates

### Log files

[2024-12-18.desktop.production.log](https://github.com/user-attachments/files/18185779/2024-12-18.desktop.production.log)

**Comment by AaronMT** [comment]
The URL in https://github.com/desktop/desktop/blob/ed122640f68757539525ef6d97f510a34ac272b0/script/dist-info.ts#L143 is returning a 404, maybe related?

If I create a query like [1], it is a 404

[1] https://central.github.com/api/deployments/desktop/desktop/arm64/latest?version=3.4.5&env=production

**Comment by DylanDevelops** [comment]
@AaronMT Try holding down `⌥ option` on mac or `alt` on windows and clicking down on `Check for Updates`. This should force fetch any new updates instead waiting until you are included in the roll out.

This update functionality was removed in `v3.4.6` so once your app is updated, clicking on `Check for Updates` will force install the newest version.

If this doesn't work, let us know and then it is some other issue.

**Comment by AaronMT** [comment]
I didn't have to do anything, but I checked again a few days later and an update was available.
