### ISSUE TITLE
version 3.4.12 diffs are broken.

### ISSUE THREAD

**Issue by marticliment** [desktop/desktop#19749]
### The problem

Diffs on version 3.4.12 say the whole file has changed when it has clearly not:
![image](https://github.com/user-attachments/assets/518a031f-c0e8-4c4d-a5fe-d43dff0acfa4)

If any content change is present, the whole file will be shown as changed, and not the specific lines as it should.

### Release version

Version 3.4.12 (x64)

### Operating system

Windows 11 x64

### Steps to reproduce the behavior

Update to GH Desktop 3.4.12

### Log files

[2024-12-18.desktop.production.log](https://github.com/user-attachments/files/18189720/2024-12-18.desktop.production.log)

**Comment by niik** [comment]
Hey @marticliment, thanks for reaching out. We're not able to reproduce this. Is it possible that your editor has changed the line endings from `\n` to `\r\n`? That's a common reason why users end up seeing the whole file as changed.

I'm not ruling out a regression in Desktop but given that we can't reproduce this and that we've had no other reports I have to assume that there's something else going on here. Does this happen with all your projects or just this one? Have you made any changes to your global Git config recently?

Please try running `git diff` in a command prompt while inside your repository and check if the output from Git matches what you see in GitHub Desktop.

**Comment by marticliment** [comment]
My apologies.
The update happened at the same time I disabled autocrlf on git, and I didn't realize this could be the issue.

Thanks for the quick reply
