### ISSUE TITLE
Github Desktop won't open

### ISSUE THREAD

**Issue by Mahdi86ir** [desktop/desktop#19750]
GIthub Desktop doesn't open on my windows 11

i tried searching other solution but they didn't work,

i ran this command : Get-EventLog -LogName "Application" -EntryType "Error" -Newest 20  | Format-Table  Index, Source, Message
and it shows me this:

![image](https://github.com/user-attachments/assets/02642ca5-6d5a-427b-bc31-eb1700925064)

i found this command on Github Desktop won't open #18432 issue

**Comment by steveward** [comment]
Thanks for the report @Mahdi86ir. Could you try performing a fresh installation of GitHub Desktop by following these steps?

Here's how to do that:

1. Open File Explorer
2. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
3. Go to `%AppData%` and delete the `GitHub Desktop` directory
4. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that helps.
