### ISSUE TITLE
Enable copilot in github dektop

### ISSUE THREAD

**Issue by alishah730** [desktop/desktop#19753]
### The feature request

enable copilot in GitHub desktop 

### Proposed solution

this can help 

- enhanced code commit message
- conflict resolution
- code review
- creating better merge commit message for release notes

**Comment by steveward** [comment]
Thanks for the issue @alishah730. We have an existing issue open for generating commit messages in https://github.com/desktop/desktop/issues/17439, so I'm going to close this one out for the time being as this is something we are aware of. If there's a specific Copilot feature you are looking for it would be helpful if you could scope the request with a specific use case. Thanks for your interest!
