### ISSUE TITLE
bitbucket issue

### ISSUE THREAD

**Issue by anjalikardak01** [desktop/desktop#19757]
i am creating a one repository xyz after creating the repository i am copying the code . and then i  open the git desktop and clone this repo in git desktop and then in xyz i am creating a file . after file creation i check in git desktop in changes there is no files are available why

**Comment by steveward** [comment]
@anjalikardak01 thanks for the issue. Can you share some screenshots or steps of what you are doing so that we can better understand this issue? Without further information it will be difficult to assist you.
