### ISSUE TITLE
cannot install githubDesktop (msi64) on windows 10

### ISSUE THREAD

**Issue by primer97** [desktop/desktop#19769]
### The problem

I double click on "GitHubDesktopSetup-x64.msi", 
the "GitHub Deployement Tool" windows opens and quickly close. nothing is made, no installation.
Note, there are no %LocalAppData%\GitHubDesktop\ or %LocalAppData%\SquirrelTemp folder created.

All antivirus are disabled.

### Release version

unkown as it's not installed

### Operating system

windows 10

### Steps to reproduce the behavior

1. run the installer

### Screenshots

![image](https://github.com/user-attachments/assets/df3ac19a-8c2f-4d2c-b302-bd4a8094572c)

**Comment by Arash2117** [comment]
Open this page for me on Instagram. I forgot my password to the Instagram page and I don't have access to any more information.  beautiful._.dream96

**Comment by tidy-dev** [comment]
@primer97 Thank you for reaching out! 
I was unable to reproduce this, I, 
  1. Downloaded the MSI installer.
  2. Ran it.
  3. Located the GitHubDesktopDeploymentTool. Ran it.
  4. Desktop installed. 

But, more importantly, 
Do you require the MSI? Can you [try installing it with the regular installer](https://central.github.com/deployments/desktop/desktop/latest/win32)?

**Comment by primer97** [comment]
indeed regular installer did work, thank you.
