### ISSUE TITLE
Clone fatal and Help-Check for upaates fatal

### ISSUE THREAD

**Issue by linexu** [desktop/desktop#19774]
### The problem

It works fine after the first installation. But after a few minutes, suddenly it won't clone. Uninstalled and reinstalled, the problem persists.

**Cloning into 'D:\github\xxx\xxx'...
fatal: unable to access 'https://github.com/.../.../': Send failure: Connection was reset
Would you like to retry xxx cloning ?**

updates error
Command failed: 4294967295
System.AggregateException: ����һ���������� ---> System.Net.WebException: ���������Ѿ��ر�: ����ʱ�������� ---> System.IO.IOException: �޷�������д�봫������: Զ������ǿ�ȹر���һ�����е����ӡ��� ---> System.Net.Sockets.SocketException: Զ������ǿ�ȹر���һ�����е����ӡ�
   �� System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   �� System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   �� System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   �� System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   �� System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   �� System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   �� System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   �� System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   �� System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   �� System.Net.TlsStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback asyncCallback, Object asyncState)
   �� System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   �� System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   �� System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   �� Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   �� Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.UpdateManager.<CheckForUpdate>d__8.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   �� Squirrel.Update.Program.executeCommandLine(String[] args)
   �� Squirrel.Update.Program.main(String[] args)
   �� Squirrel.Update.Program.Main(String[] args)
---> (�ڲ��쳣 #0) System.Net.WebException: ���������Ѿ��ر�: ����ʱ�������� ---> System.IO.IOException: �޷�������д�봫������: Զ������ǿ�ȹر���һ�����е����ӡ��� ---> System.Net.Sockets.SocketException: Զ������ǿ�ȹر���һ�����е����ӡ�
   �� System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   �� System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   �� System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   �� System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   �� System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   �� System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   �� System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   �� System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   �� System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   �� System.Net.TlsStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback asyncCallback, Object asyncState)
   �� System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   �� System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   �� System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   �� Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   �� Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.UpdateManager.<CheckForUpdate>d__8.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---
Command failed: 4294967295
System.AggregateException: ����һ���������� ---> System.Net.WebException: ���������Ѿ��ر�: ����ʱ�������� ---> System.IO.IOException: �޷�������д�봫������: Զ������ǿ�ȹر���һ�����е����ӡ��� ---> System.Net.Sockets.SocketException: Զ������ǿ�ȹر���һ�����е����ӡ�
   �� System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   �� System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   �� System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   �� System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   �� System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   �� System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   �� System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   �� System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   �� System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   �� System.Net.TlsStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback asyncCallback, Object asyncState)
   �� System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   �� System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   �� System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   �� Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   �� Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.UpdateManager.<CheckForUpdate>d__8.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   �� Squirrel.Update.Program.executeCommandLine(String[] args)
   �� Squirrel.Update.Program.main(String[] args)
   �� Squirrel.Update.Program.Main(String[] args)
---> (�ڲ��쳣 #0) System.Net.WebException: ���������Ѿ��ر�: ����ʱ�������� ---> System.IO.IOException: �޷�������д�봫������: Զ������ǿ�ȹر���һ�����е����ӡ��� ---> System.Net.Sockets.SocketException: Զ������ǿ�ȹر���һ�����е����ӡ�
   �� System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   �� System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   �� System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   �� System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest, Boolean renegotiation)
   �� System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   �� System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   �� System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   �� System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   �� System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   �� System.Net.TlsStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback asyncCallback, Object asyncState)
   �� System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   �� System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   �� System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   �� Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   �� Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.UpdateManager.<CheckForUpdate>d__8.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---

### Release version

Version 3.4.12 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. clone a repository
2. URL
3. fatal

### Screenshots

![image](https://github.com/user-attachments/assets/724222ee-5a1e-4324-b3a0-19b1682054c3)
![image](https://github.com/user-attachments/assets/56696cf6-d660-48aa-b12e-85592e2da0b5)

**Comment by tidy-dev** [comment]
@linexu Thanks for reaching out! Would you be able to upload logs for when these errors occurred?

But based on what you have posted thus far, I would suspect that your network calls are either behind a proxy or an antivirus software is intercepting them.

**Comment by linexu** [comment]
It is not possible to log in without using a proxy.
Uninstalled and reinstalled repeatedly, same error.
Even after using a third-party uninstaller to clean up the WIN10 registry, and then reinstalling, the same error occurs.
I can't do anything about it.

![image](https://github.com/user-attachments/assets/c61042ad-2540-4773-8fcc-112a3a118c04)
![image](https://github.com/user-attachments/assets/b61c9790-e910-4d0e-abdf-245db535b703)

**Comment by linexu** [comment]
And I can connect using the GIT software GITGUI, CLONE.
But this DESKTOP is wrong. The strange thing is that when I just install it, it works fine, and when I CLONE a project, it doesn't work after a few minutes. Until now.

**Comment by linexu** [comment]
Strangely enough within the same LAN I tested with another laptop and it logged in fine, but that is not my work machine.
I still need my current desktop to work.

**Comment by linexu** [comment]
**Thank you very much for your help, it has been resolved.**

![image](https://github.com/user-attachments/assets/df107545-c424-4375-94cb-b2acc9da17fc)
