### ISSUE TITLE
missing repositories with github and github disktop github app

### ISSUE THREAD

**Issue by BillLea** [desktop/desktop#19782]
The problem is that github wont find my repositories when I log in using my browser but will find them when I use the github desktop app. I am thinking I have some how greated two accounts. I would like to consolodate them how can I do that?

**Comment by tidy-dev** [comment]
@BillLea Thanks for reaching out. This is the issue tracker for GitHub Desktop and therefore merging two accounts is not something I can help with specifically. You could [reach out to GitHub support](https://support.github.com/). That said... here is some information that may help you.

1. Are you absolutely sure you created 2 accounts -> That would require 2 emails and going through the sign up process twice on GitHub.com?
   -  What could be happening is that you created some repositories locally.. but you have not published them to GitHub.com yet. Therefore, your repository list in GitHub Desktop shows them, but they would not show in GitHub.com. If this is the case, you should be able to open such repository in GitHub Desktop and GitHub Desktop push button will indicate you can publish the repository. 
  

2. You did create two GitHub accounts and all your repositories are published to 2 separate accounts that you know how to log into separately on GitHub.com. Here is [documentation about transferring ownership of repositories](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) that you can follow to move repositories from one account to another. 
    - If this is the case, I would suggest open the repos you are going to transfer in GitHub Desktop and pushing any branches  that have unpublished changes on them so you make sure to transfer all your current work.
