### ISSUE TITLE
Char level diff and `open with external editor` as in GH 222

### ISSUE THREAD

**Issue by AdOps** [desktop/desktop#1982]
Please give us back character level diffs ~~and line wrapping~~ (seems like it is there already, ups) in diff view, as in GH Desktop v 222

See attachments:
<img width="469" alt="screen shot 2017-06-12 at 16 07 46" src="https://user-images.githubusercontent.com/24861420/27037834-766b1fc4-4f89-11e7-8154-d18e7f90c5b9.png">
<img width="513" alt="screen shot 2017-06-12 at 16 07 35" src="https://user-images.githubusercontent.com/24861420/27037842-7af297de-4f89-11e7-9de3-2227b63507f5.png">

- And `Open with external editor` (contextual right click and !!! `double click`, as in 222):

<img width="546" alt="screen shot 2017-06-12 at 16 22 41" src="https://user-images.githubusercontent.com/24861420/27038505-8ef91bac-4f8b-11e7-8343-9b9121fc4a0c.png">

**Comment by niik** [comment]
Hi @AdOps, we're tracking word-diffs in #173 and open in editor in https://github.com/desktop/desktop/issues/1554 so please subscribe to those issues to follow along!
