### ISSUE TITLE
Surfacing the Zoom limitations

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1983]
When zooming to the minimum or maximum of the app limitations (< 100% or > 200%), I noticed that the Menu option still exists. For example, if the user is already at 100%, shouldn't we grey out the menu item?

Furthermore, perhaps the keyboard command should indicate a notice to the user? The grey flash message we currently use (see pic) could say something like "Minimum zoom reached" or just keep saying "100%". Currently, nothing happens.

<img width="377" alt="screen shot 2017-06-12 at 10 34 27 am" src="https://user-images.githubusercontent.com/14828183/27039048-c34f4de4-4f5a-11e7-9199-4feff77c074a.png">

v.0.6.0

cc @donokuda

**Comment by donokuda** [comment]
> When zooming to the minimum or maximum of the app limitations (< 100% or > 200%), I noticed that the Menu option still exists. For example, if the user is already at 100%, shouldn't we grey out the menu item?

👍 Agree, if the action can't be taken, then we should consider disabling the menu option. 

> Furthermore, perhaps the keyboard command should indicate a notice to the user? The grey flash message we currently use (see pic) could say something like "Minimum zoom reached" or just keep saying "100%". Currently, nothing happens.

I think that it's okay to not have the UI respond (and the zoom notification fade out) when we reach the minimum and maximum zoom. I'm not concerned that a majority of users would find this as a bug given that apps such as Chrome already work this way.

**Comment by tierninho** [comment]
Closing this as it has not come up enough times to be validated as a real problem.
