### ISSUE TITLE
Partial commit now fails for only one of the files in my repo

### ISSUE THREAD

**Issue by xt0rted** [desktop/desktop#1986]
### Description

I have a file in my repo where I'm trying to commit only select lines in it, but it's failing with the message `The requested changes conflict with one or more files in the repository.`

One of the blocks was 2 lines of text that I replaced with a new single line. I couldn't commit this at all, even trying to commit just the removed lines or the added line resulted in an error.

I can commit individual changes just fine with the native client and other edited files commit just fine as well. In the end I `git stash -p` and stashed the few things I didn't want in this commit and then was able to commit the entire file ok.

### Version
**GitHub Desktop version:** 0.6.0
**OS version:** Win10 CU (10.0.15063)

### Steps to Reproduce

I'm unable to reproduce this in any other files. It happened in just this one. I'm not sure if it's relevant or not but I did restore these changes from a stash before continuing work on them. There were no conflicts in this file when I did that and other changes were committed just fine before getting to this file.

**Expected behaviour:** I should be able to select a changed block and commit it

**Actual behaviour:** I'm unable to commit any changes and receive the error `The requested changes conflict with one or more files in the repository.`

**Reproduces how often:** On one file only so far

### Logs

```
2017-06-12T18:40:38.575Z - error: [ui] `git apply --cached --unidiff-zero --whitespace=nowarn -` exited with an unexpected code: 1.
error: patch failed: src/Web/Views/PurchaseSeller/Form.cshtml:71
error: src/Web/Views/PurchaseSeller/Form.cshtml: patch does not apply

(The error was parsed as 24: The requested changes conflict with one or more files in the repository.)
```

#### Additional Information

![image](https://user-images.githubusercontent.com/831974/27049648-ebc354fa-4f7d-11e7-9b26-cae14e3e6751.png)

**Comment by joshaber** [comment]
Thanks @xt0rted! Would you be able to provide us with the files or changes you were trying to commit?

**Comment by xt0rted** [comment]
I ended up working around the issue, I can try restoring the changes and seeing if it happens again though.

**Comment by xt0rted** [comment]
@joshaber I just ran into this issue again with the same file. I setup a private repo on my account and invited you to it. Because of what the code is I can't just posted it in the issue.

**Comment by xt0rted** [comment]
Just updated to 0.6.1 and didn't get the error when trying to commit the same changes. Here's the console output from the commit that worked.
```
Executing unstageAll: git reset -- .
install.ts:31 Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- Form.cshtml
install.ts:31 Executing applyPatchToIndex: git apply --cached --unidiff-zero --whitespace=nowarn -
install.ts:31 Executing createCommit: git commit -F -
install.ts:31 Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z
install.ts:31 Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes
install.ts:31 Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 --
install.ts:31 Executing getCommits: git log e4f2d9bffcae66732f7c62d49722876346315584 --date=raw --max-count=1 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color
install.ts:31 Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- Form.cshtml
install.ts:31 Executing getCommits: git log origin/master..master --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color
install.ts:31 Executing getRemotes: git remote -v
install.ts:31 Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT
install.ts:31 Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z
install.ts:31 Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- Form.cshtml
install.ts:31 Executing getCommits: git log origin/master..master --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color
```

**Comment by joshaber** [comment]
@xt0rted Thanks for sharing that repository with me!

It looks like this was related to the unicode diff bug fixed in https://github.com/desktop/desktop/pull/1970. Since the file contained a unicode character and we'd garble it, the patch couldn't apply.

**Comment by kaster14** [comment]
@joshaber I just experienced this problem, github desktop version 1.6.5
I could not make a partial commit but it did allow me to commit all changes

**Comment by tierninho** [comment]
@kaster14 Sorry you are experiencing issues with partial commits. 

Please submit a fresh issue [here](https://github.com/desktop/desktop/issues/new/choose) if you would like us to take a look. Thanks!
