### ISSUE TITLE
Sort and group license selection to match dotcom

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#1987]
As per @lee-dohm elsewhere:

>Ok, so we could do this with the dropbox:
>
>1. `featured: true` licenses
>1. A separator
>1. `hidden: false` licenses (minus the `featured: true` ones)
>
>And that would be equivalent to the list of licenses that we see presented in the license picker on .com?

**Comment by j-f1** [comment]
On GitHub.com, the featured licenses are **bold**, and there’s no separator.

**Comment by joshaber** [comment]
I don't feel strongly about exactly how they're grouped, just that they are sorted and grouped in the manner specified 👍
