### ISSUE TITLE
Binary diff doesn't show anything, not even a message indicating it's a binary file

### ISSUE THREAD

**Issue by xt0rted** [desktop/desktop#1990]
### Description

In the native client binary files would show a messge indicating the diff is of a binary file, but in this client it shows nothing at all.

### Version
**GitHub Desktop version:** 0.6.0
**OS version:** Win10 CU (10.0.15063)

### Steps to Reproduce

1. Add a file such as a word doc (docx) to your repo
1. Modify it
1. Select the file in the changed file list
1. Look at the diff view for the file

**Expected behaviour:** A message should be shown indicating the file in question is a binary file so there's no diff to view.

**Actual behaviour:** Nothing shows in the diff view

**Reproduces how often:** With every binary file

#### Additional Information

Comparison view with the native client.

![image](https://user-images.githubusercontent.com/831974/27055544-c442c77a-4f92-11e7-984a-108633f831af.png)

**Comment by xt0rted** [comment]
Looks like with 0.6.1 this changed slightly. There's now a message that says `No content changes found`, though that's slightly misleading since there are changes which is why it's showing as modified.

**Comment by shiftkey** [comment]
@xt0rted the changed message was due to #1906 but I don't think this is the same scenario, so I'm curious what is different about your setup.

Could you attach the output of this command:

```
$ git diff HEAD --no-ext-diff --patch-with-raw -- src\Web\Templates\PurchaseAgreement.docx
```

**Comment by xt0rted** [comment]
Running that produces a proper text diff of the changes. I can't post the output here, but it's actually a pretty good representation of the changes and would be immensely helpful to see instead of the traditional "this is a binary file" message.

I have [BeyondCompare](http://scootersoftware.com/) installed, and setup for when I `git difftool`. Are the results of the command you had me run being produced from this or Git itself?

**Comment by xt0rted** [comment]
Just ran this against a test document and this is the output of it.

```diff
diff --git a/Test.docx b/Test.docx
index b97cf96..7f27095 100644
--- a/Test.docx
+++ b/Test.docx
@@ -1 +1,2 @@
-Some test text.
+This is some test text.
+And more here.
```

**Comment by johannesmtwengi** [comment]
amazon.com.   ebay products ebay.com

**Comment by johannesmtwengi** [comment]
www.amazon.co.za

**Comment by johannesmtwengi** [comment]
i feel lucky and my i,m getting billions of dollars

**Comment by xt0rted** [comment]
Not sure if this is related, but when a new `.docx` is added to a folder in the repo it shows the following messaging which also seems inaccurate.

![image](https://user-images.githubusercontent.com/831974/27143652-1c900a62-50fd-11e7-8b9b-f316e57760ca.png)
