### ISSUE TITLE
Diff containing Chinese characters is displayed incorrectly

### ISSUE THREAD

**Issue by Jasonbat** [desktop/desktop#1991]
### Description

[Description of the issue]
Github Desktop can not read Chinese characters

**Comment by Jasonbat** [comment]
When it is facing with chinese characters,it will cause some problems 
like this,what is the solution to this?
![leqe3cbv44 chp kdq0hd_r](https://user-images.githubusercontent.com/29241148/27063016-b3be79c8-5021-11e7-8a1c-20f038636582.png)

**Comment by lee-dohm** [comment]
Do you have a sample file that can reproduce this? I suspect it might be an encoding problem.

**Comment by lee-dohm** [comment]
Also may be a duplicate of #1954.

**Comment by Jasonbat** [comment]
like this file 
[编码测试.txt](https://github.com/desktop/desktop/files/1070118/default.txt)
I think it  is not a file encoding problem because I try to change file encoding UTF-8 or GBK
But it does not work

**Comment by lee-dohm** [comment]
I'm using v0.6.1 of Desktop and I see this:

<img width="408" alt="screen shot 2017-06-12 at 9 08 01 pm" src="https://user-images.githubusercontent.com/1038121/27065622-4a239c14-4fb3-11e7-959f-c826c3c3393d.png">

Are you using the latest version?

**Comment by popperz45** [comment]
Simon

**Comment by Jasonbat** [comment]
yes!I updated my desktop in the noon,it is ok!Thanks!

**Comment by lee-dohm** [comment]
I'm glad to hear it is working for you now @Jasonbat :tada:
