### ISSUE TITLE
Desktop Beta Cannot login to Github Enterprise server with a self-signed certificate in chain

### ISSUE THREAD

**Issue by sgredell** [desktop/desktop#1994]
### Description

Our Github Enterprise server uses a certificate issued from an internal root CA which is self-signed (not something we control).  This was not a problem with the legacy Desktop application, but in the new desktop beta I'm unable to even login.  Using the username and password option just fails with no error message.  Using the "Sign in using your browser" option gets me to our Github Enterprise page where I am able to sign in and authorize the application.  However, when I click the "launch application" prompt that chrome gives me, it fails to sign in with this SSL error:

![image](https://user-images.githubusercontent.com/347551/27088695-6676f938-5026-11e7-9903-e818dca10376.png)

This is on v0.6.1, one of my coworkers reports that he was able to login with v0.6.0, however he is not able to clone any repositories.

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** Version 0.6.1

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** Microsoft Windows [Version 10.0.14393]

### Steps to Reproduce

1. Install a certificate which has a self-signed certificate in it's chain (our root internal CA is self-signed) to Github Enterprise instance
2. Install Github Desktop Beta 
3. Attempt to sign in to Desktop (fails with no error message)
4. Select "Sign in using your browser" and enter username and password in browser
5. Authorize the application
6. Click the "launch Github Desktop" option in the browser

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behaviour:** [What you expected to happen]

**Actual behaviour:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

No relevant information in the *.desktop.production.log

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

This is on v0.6.1, one of my coworkers reports that he was able to login with v0.6.0, however he is not able to clone any repositories.

Any additional information, configuration or data that might be necessary to
reproduce the issue.

If you are dealing with a performance issue or regression, attaching a
[Timeline profile](https://github.com/desktop/desktop/blob/master/docs/contributing/timeline-profile.md)
of the task will help the developers understand the runtime behaviour of the
application on your machine.

**Comment by joshaber** [comment]
Thanks @sgredell! This is a known issue we're tracking at #671.

**Comment by sgredell** [comment]
Huh, thanks.  I'm not sure how I didn't find that in the search.

**Comment by joshaber** [comment]
No worries 😄
