### ISSUE TITLE
Disable Publishing button once clicked

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1995]
When a repo is published, the `Publish repository` button should be disabled as `Status 422` errors are surfaced. 

This fix will also prevent the user from being able to click the `Publish repository` button on the Enterprise tab after clicking it on the GitHub tab (and vice-versa). Yes, it can happen 😄 

<img width="472" alt="screen shot 2017-06-13 at 2 05 20 pm" src="https://user-images.githubusercontent.com/14828183/27097509-71a1f634-5042-11e7-8abe-54705b056641.png">

Reproduce:
- File > New repo
- Fill out details, create
-  Publish repo form, click `Publish repository` button multiple times
- (Also, click `Publish repository` button for dotcom, immediate click same button for Enterprise)

Clicking multiple times on dotcom:
<img width="1211" alt="screen shot 2017-06-13 at 2 06 10 pm" src="https://user-images.githubusercontent.com/14828183/27097510-71a6150c-5042-11e7-8e25-73672b0029f6.png">

If you try to publish on dotcom and Enterprise at same time:
<img width="521" alt="screen shot 2017-06-13 at 2 04 57 pm" src="https://user-images.githubusercontent.com/14828183/27097511-71a64158-5042-11e7-9d06-9a6a6f8ebb13.png">

v0.6.1, OSX 10.11.5

**Comment by j-f1** [comment]
Another option could be to disable the action buttons and change the “Publish Repository” button to say ”Publishing…”
