### ISSUE TITLE
404 errors from API when publishing Enterprise repos

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2001]
Getting a bunch of 404s from the api when successfully publishing repos to Enterprise organization. Also a Syntax error appeared during the process, as seen in pic.

v0.6.1, OSX 10.11.5

Reproduce:
- File > New Repo
- fill out form, submit
- Publish repo to Enterprise org
- Errors should surface, and repo should be successfully published.

Console logs:
<img width="1198" alt="screen shot 2017-06-14 at 10 53 31 am" src="https://user-images.githubusercontent.com/14828183/27139118-26891c0a-50f0-11e7-9ae1-e1831b802cbe.png">

**Comment by joshaber** [comment]
Do these logs surface into a user-level problem? I wouldn't worry too much about the stuff in the log unless there's a concrete issue.

**Comment by tierninho** [comment]
Ok, will close for now unless some action is blocked from a user perspective.
