### ISSUE TITLE
Move the history and changes views into separate panels

### ISSUE THREAD

**Issue by j-f1** [desktop/desktop#2004]
### Description

Currently, there are two tabs on the left side of the window: one for changes since the current commit, and one listing old commits: (click to enlarge)

<img src="https://user-images.githubusercontent.com/25517624/27142037-e46318be-50f7-11e7-8bb1-43f9988e5a00.png" width="325"><img src="https://user-images.githubusercontent.com/25517624/27142038-e4777994-50f7-11e7-94aa-d812601bcaec.png" width="325">

Note that in the second screenshot, there is a list of changed files, just like in the first screenshot. To keep the UI consistent, I suggest these changes:

![screen shot 2017-06-14 at 12 02 58](https://user-images.githubusercontent.com/25517624/27142639-9d9e96a4-50f9-11e7-94c8-df03b43faea6.png)

* Remove the “Changes” tab, and instead show it as the first commit in the list.
* Add a button to the left of the commit title to hide the sidebar if you’re viewing the uncommitted changes
* (potentially) allow double-clicking the ”Uncommitted changes” header to enter a commit message, then press <kbd>enter</kbd> to commit

Picture with the sidebar hidden:

![screen shot 2017-06-14 at 12 21 28](https://user-images.githubusercontent.com/25517624/27143607-eca8e774-50fc-11e7-90f1-11299a8c8553.png)

### Version

**GitHub Desktop version:**  0.6.1
**OS version:** 10.12.3 (16D32)

**Comment by joshaber** [comment]
Thanks for thinking through this @j-f1!

Conceptually I like the idea. GitHub for Windows had a somewhat similar design a while back.

The biggest problem I see is that it takes space away from the diff which needs all the horizontal space it can get. The design compensates for that by making it a toggleable sidebar. But if I'm toggling the sidebar to switch between looking at my local changes and looking at history, it doesn't seem all that different from the tabs we have today.

**Comment by niik** [comment]
Thank you for taking the time to make these mocks @j-f1 

> The biggest problem I see is that it takes space away from the diff which needs all the horizontal space it can get. The design compensates for that by making it a toggleable sidebar. But if I'm toggling the sidebar to switch between looking at my local changes and looking at history, it doesn't seem all that different from the tabs we have today.

@donokuda and I discussed this in the design review today and we agree with what @joshaber is saying here. Horizontal space is at a premium and we want to avoid doing three panes unless we have to (like in the history view). We're also weary of introducing a new concept (an expandable list item). Tabs, while they have shortcomings of their own, are well known and understood.

**Comment by j-f1** [comment]
I just had an idea: what if each commit expanded to show the files changed inside it? This way, there would always be just one panel, leaving more space for the diffs.

**Comment by niik** [comment]
> I just had an idea: what if each commit expanded to show the files changed inside it? This way, there would always be just one panel, leaving more space for the diffs.

Yeah, I think that idea holds a lot of merit. We've discussed doing so in the past and we did, in fact, do that in the classic apps

![image](https://user-images.githubusercontent.com/634063/27422237-b519893a-572d-11e7-8d2a-a865954ea323.png)

Unfortunately this approach isn't non-trivial to implement in an efficient way. Right now we're limited by the need to have fixed-height cell items in our lists in order for virtualization to work (without messing up scrolling). We've also talked about showing all diffs by default in the history view like we do in the classic app on Windows

![image](https://user-images.githubusercontent.com/634063/27422343-13feebde-572e-11e7-9f2b-8023434c338b.png)

Again, this isn't really feasible right now with how we're doing virtualization in lists.

We're certainly not against exploring ways that such a scheme could work in the future but for now it's not in scope of our design goals.

**Comment by j-f1** [comment]
The current virtual list implementation appears to support dynamic row heights:

```typescript
/**
 * The height of each individual row in the list. This height
 * is enforced for each row container and attempting to render a row
 * which does not fit inside that height is forbidden.
 *
 * Can either be a number (most efficient) in which case all rows
 * are of equal height, or, a function that, given a row index returns
 * the height of that particular row.
 */
readonly rowHeight: number | ((info: { index: number }) => number)
```
<sup>[source](https://github.com/desktop/desktop/blob/83cf2812f6064394b2a7924f3f8d7dab79633428/app/src/ui/list.tsx#L86-L95)</sup>
