### ISSUE TITLE
Any commits during Publishing/Pushing get pushed too

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2005]
So if you make a commit while another commit is being published to dotcom or Enterprise, that second commit is pushed up along with the first one. When the user clicks the `Publish` button, the number badge is displayed with the amount of commits to be pushed, however, the user might be unaware that if they make a commit during the publishing process, that it would be immediately pushed, too. 

Perhaps we could temporarily disable the commit button until the publishing process has reached a certain point?

v0.6.1, OSX 10.11.5

Reproduce (Pushing):
- For a currently published repo, add multiple changed files to the queue
- Commit one so the published badge number increments
- Now prep another file for commit without hitting the `Commit to X` button
- Click the `Publish` button and immediately after click the `Commit` button
- Both changes are pushed up to the repo

Expected behavior: the second commit would be separate from the first, prompting the user to publish them separately. On Step 4 above, if the user waits a second or two, the expected behavior holds true.

**Comment by shiftkey** [comment]
@tierninho can we update this issue to differentiate between the publish flow (the publish dialog which takes a repository without any remotes and puts it on GitHub) and push (the repository has a remote, and a long-running operation like pushing new commits you could do other work)? You mention that this repository is published, which should mean the button is for pushing.

**Comment by tierninho** [comment]
> You mention that this repository is published, which should mean the button is for pushing

Yes, initially the test case was for already published repos, and any commits piggybacking on any given push. However, upon further testing, there does not appear to be a difference with either Publishing or Pushing, as in both instances, a commit can be piggybacked.

Here are the steps for an unpublished repo (Publishing):

- Make a new repo with initial files, ie, read me, etc.
- Undo the initial commit and re-commit only some of the files
- Prep the remaining file so the the commit button is "active"
- Publish the repo (after the modal pops up) and immediately click the commit button for the remaining file
- Both sets of commits are pushed up to the new repo

Tested again in `0.8.1-beta2`, Mac

**Comment by shiftkey** [comment]
I'm going to move this to `enhancement` because `git push` only really supports providing refs, and this case is about quickly updating the ref while an operation is in flight.

We've made a decision to push the current branch as part of the publish, and we'd need to have a think about what we do here while the publish and push is happening (block creating the new commit from happening?) and given I've not seen any other feedback about wanting to change this behaviour I think this is low-priority.

**Comment by j-f1** [comment]
Would it be possible to store the SHA of the latest commit on the branch and only push up to that commit? (One edge case would be if someone undid & recommitted the latest commit while the push was happening; perhaps we should hide the undo section as soon as we start the push)

**Comment by tierninho** [comment]
Closing this as it has not come up enough times to be validated as a real problem.

**Comment by mido1966** [comment]
Thank you very one es ok Dankeschön alles ok

‏‫من الـ iPhone الخاص بي‬

‫في 18‏/03‏/2019 الساعة 10:30 م، كتب/كتبت ‏Tiernan L ‏<notifications@github.com<mailto:notifications@github.com>>:‬


Closed #2005<https://github.com/desktop/desktop/issues/2005>.
