### ISSUE TITLE
Clearing the cache on Desktop

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2006]
In the Developer tools, under Application, there is an option to Clear site data, which of course dumps the db and renders the Desktop rather useless.

<img width="1219" alt="screen shot 2017-06-14 at 1 56 11 pm" src="https://user-images.githubusercontent.com/14828183/27147257-15b30ba6-510a-11e7-9a09-f337c819c150.png">

Should we add some type of warning, if possible? Although, I don't think anyone should be tinkering in here without some knowledge of what will happen.

**Comment by joshaber** [comment]
Nah, if someone's poking around in dev tools all bets are off 😄
