### ISSUE TITLE
Adding/removing final new-line does not update error icon in diff view

### ISSUE THREAD

**Issue by ericdrobinson** [desktop/desktop#2019]
### Description

Noticed the missing final endline notification icons (🚫) in the diff view prior to committing a Python script. Adjusted the file in a text editor, adding the final line. Switched back to GitHub Desktop, expecting the warning icon to go away.

It didn't disappear; the icon remained.

It _did_ disappear when I switched to a different repository and back again.

Further testing showed that this works in reverse, as well: removing the final endline does not cause the icon to appear. If any **other** change is _also_ detected (e.g. a single space), the diff view is updated and the symbols appear/disappear as expected.

### Version

**GitHub Desktop version:** 0.6.1

**OS version:** macOS 10.12.5

### Steps to Reproduce

1. Select a Python (or other?) file in the "Changes" tab to show the contents in the diff.
1. Remove (or add) the final newline character in a text editor (with **no** other changes).
1. Switch back to GitHub Desktop and note that the state of the "missing endline" notification is not updated.

**Expected behaviour:** Adding/Removing the final endline character adjusts the state of the notification in the GitHub Desktop diff view.

**Actual behaviour:** Changes involving _only_ the addition/removal of the final endline character do not cause the diff view to update (the notification state does not visually change).

**Reproduces how often:** 100%.

**Comment by shiftkey** [comment]
@ericdrobinson I wasn't able to reproduce the issue as you reported on 0.6.2 - adding a newline at the end of the file was detected by the app, and introducing a change elsewhere in the file would draw the line ending warning.

Here's a GIF of the app in action:

![](https://user-images.githubusercontent.com/359239/27708701-919c9fa0-5cce-11e7-9db1-d3a5e720e945.gif)

There might be some details about your setup that we're missing to isolate this issue. Could you run this command against the repository and attach the output here?

```
git config -l --show-origin
```

**Comment by ericdrobinson** [comment]
@shiftkey I just tried this in 0.6.2 as well and I could not get the bug to reproduce.

Please feel free to close the bug as "fixed" [if accidentally ;D]! And, thanks!

**Comment by ayush-rathore-quartic** [comment]
@ericdrobinson Facing the same behavior, Did you ever find a way to work around this?

**Comment by ayush-rathore-quartic** [comment]
Deleting and adding the same file in 2 commits helped us
