### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by rbmichael** [desktop/desktop#2020]
### Description

The client is giving me the message that an updated version of Github Desktop is available and will be installed at next launch. But every time it launches, it's still the same version; it's not updating. I've tried the "restart now" option it gives me in the message, and I've tried updating via the "Install Update" button under "About GitHub Desktop" -- neither option is working. (The client has previously updated successfully.)

### Version

**GitHub Desktop version:** 0.5.9

**OS version:** Mac OS Sierra 10.12.5

**Comment by joshaber** [comment]
@rbmichael Thanks for opening this up!

Out of curiosity, have you moved the app since you downloaded it? For example, from ~/Downloads to /Applications?

**Comment by rbmichael** [comment]
Hi Josh,

No, I haven't. Could it be because I don't have administrator access, so
the update is failing (silently)? I thought the app had updated
successfully in the past -- but now I'm wondering if I was wrong about that.

Thank you.

**Comment by joshaber** [comment]
>Could it be because I don't have administrator access

Maaaaybe. That's an interesting datapoint at least.

It could also be that the app is being subjected to Gatekeeper's path randomization. Could you try quitting the app, moving it to someplace else, and then try updating again?

**Comment by rbmichael** [comment]
Moving the app out of `/Applications` to another folder allowed it to update. I don't have permissions to change `/Applications`, so I suppose that's the problem. I have other apps that are able to successfully update though -- strange!

**Comment by CarstenPer** [comment]
@ @rbmichael

**Comment by joshaber** [comment]
There are some known issues with Squirrel and `/Applications` permissions (e.g., https://github.com/Squirrel/Squirrel.Mac/issues/157). I'll close this since it's being tracked over there.

**Comment by jordan-bravo** [comment]
To add another data point, I experienced this issue as well when I had GitHub Desktop installed via the employer-managed app store on my Mac.  I resolved it by updating through that app store rather than within GitHub Desktop itself.
