### ISSUE TITLE
Unable to Authenticate Bitbucket repository

### ISSUE THREAD

**Issue by drcjones** [desktop/desktop#2021]
### Description

With Github Desktop 3.3.4.0 I can drag in a git repo url from Bitbucket.com and it will ask for my Bitbucket credentials, then clone the repo. When I try that in GitHub Desktop Beta 0.6.1 Nothing happens when I drag in the URl. If I clone the repo in bash, then open Github Desktop I can add the local repo but cannot fetch, commit, etc. 

### Version

**GitHub Desktop version:** 
0.6.1

**OS version:** 
Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

Part 1
1. Open GitHub Desktop Beta 0.6.1
2. Drag in the URl from Bitbucket.com (https or SSL). See that nothing happens.

Part 2
1. Open bash/cmd.exe and clone repo from Bitbucket.com
2. Open GitHub Desktop Beta 0.6.1
3. Click to Add the local repo
4. Click "Fetch" and see the error message pop up: "Authentication failed. You may not have permission to access the repository. Open options and verify that you're signed in with an account that has permission to access this repository."

**Expected behaviour:** 
Part 1 - Github Desktop should pop up a dialog asking where to clone the repo to.
Part 2 - Github Desktop should open a dialog asking for my Bitbucket username and password, then clone the repository.

**Actual behaviour:** 
Part 1 - Nothing happens.
Part 2 - I get the following error popup: "Authentication failed. You may not have permission to access the repository. Open options and verify that you're signed in with an account that has permission to access this repository."

**Reproduces how often:** 
Every time

### Logs
error: [ui] fetchRepository: not found for '[username]' and 'xxx/yyy'
Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"} GET https://api.github.com/repos/xxx/yyy Status: 404
    at %APPDATA%\Local\GitHubDesktop\app-0.6.1\webpack:\app\~\octokat\dist\node\requester.js:222:1
    at process._tickCallback (internal/process/next_tick.js:103:7)

(The error was parsed as 3: Authentication failed. You may not have permission to access the repository. Open options and verify that you're signed in with an account that has permission to access this repository.)
2017-06-15T18:19:54.883Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
remote: Empty password
fatal: Authentication failed for 'https://[username]@bitbucket.org/xxx/yyy.git/'

(The error was parsed as 3: Authentication failed. You may not have permission to access the repository. Open options and verify that you're signed in with an account that has permission to access this repository.)
error: [ui] `git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes` exited with an unexpected code: 128.
fatal: Not a git repository (or any of the parent directories): .git

(The error was parsed as 27: This is not a git repository.)
error: [ui] `git status --untracked-files=all --branch --porcelain=2 -z` exited with an unexpected code: 128.
fatal: Not a git repository (or any of the parent directories): .git

#### Additional Information
N/A

**Comment by joshaber** [comment]
Thanks @drcjones! This is a known limitation we're tracking at https://github.com/desktop/desktop/issues/852.
