### ISSUE TITLE
Allow the Changes pane to be expanded to a larger width

### ISSUE THREAD

**Issue by charlieturndorf** [desktop/desktop#2022]
### Description

The Changes pane is quite narrow and filenames are cut very short. I tend to work with generated files that have long filenames all ending in the same thing. It's not very helpful to see a long list of "[MyProject]\\[foo]...extGeneratedExtension.cs". In the previous client it was possible to expand the file list to nearly any width as needed.

### Steps to Reproduce

1. Place the cursor over the dividing line between the Changes/History pane and the main code pane. The cursor will change to a horizontal 2-way arrow.
2. Click and drag the divider to the right. The pane will expand up to a point.
3. The pane cannot be expanded to more than 2 inches or so.

### Proposal

Users should be able to resize the Changes pane to any width we want, or at least to about half the screen, especially if the window is maximized.

### Version

**GitHub Desktop version:** 0.6.1

**OS version:** Windows 10.0.15063

**Comment by shiftkey** [comment]
@charlieturndorf thanks for the suggestion. We're already tracking this in #1588, so please follow that issue!

**Comment by charlieturndorf** [comment]
Thank you for letting me know! I'm sorry I didn't find the existing issue.

Charlie


On Jun 16, 2017 6:12 AM, "Brendan Forster" <notifications@github.com> wrote:

Closed #2022 <https://github.com/desktop/desktop/issues/2022>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/desktop/desktop/issues/2022#event-1126581602>, or mute
the thread
