### ISSUE TITLE
Repositories created on browser not showing on desktop app

### ISSUE THREAD

**Issue by sauravokos** [desktop/desktop#2028]
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

I recently created a github repository called "Deep Learning" but it is not showing on the desktop app. The app is showing no repositories at all. Please rectify the problem. Regards

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** 0.6.1

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** 10.0.15063

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behaviour:** [What you expected to happen]

**Actual behaviour:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

If you are dealing with a performance issue or regression, attaching a
[Timeline profile](https://github.com/desktop/desktop/blob/master/docs/contributing/timeline-profile.md)
of the task will help the developers understand the runtime behaviour of the
application on your machine.

**Comment by joshaber** [comment]
Hi @sauravokos, in order for a repository to show up in the app, you'll need to clone it and add it to the app. See https://help.github.com/desktop-beta/guides/getting-started-with-github-desktop/ for more information.

**Comment by akvadrako** [comment]
This is terrible UX.

**Comment by j-f1** [comment]
@akvadrako It’s even worse UX to download any repositories a user forks in the background, without user input. If they’re large, they can take up hard drive space and use up data on metered connections.

**Comment by akvadrako** [comment]
Why should they be downloaded? Just listed would be fine. The point is, I was trying to help a non-programmer friend get started with github today, and it just seemed like Github Desktop was broken. You shouldn't need a getting started guide for this.

**Comment by j-f1** [comment]
Each repository in the list has been downloaded and has a location on your computer (try right-clicking). However, if you go to File → Clone Repository…, you can click on the GitHub.com tab and select the repository to clone from a list without having to memorize URLs.

**Comment by akvadrako** [comment]
I'm aware how it works and wasn't asking for help. I'm saying it's not a good design, hence this issue.

**Comment by Scenario** [comment]
I just installed GitHub Desktop, signed in, and don't see any of my teams or repos. I shouldn't have to start from scratch and have to re-clone dozens of projects.

**Comment by j-f1** [comment]
> I shouldn't have to start from scratch and have to re-clone dozens of projects.

Don’t worry! You can drag-and-drop your current clones onto the app, and it’ll add them for you.

**Comment by iAmWillShepherd** [comment]
@akvadrako sorry GitHub Desktop isn't working out for you. 

> Why should they be downloaded? Just listed would be fine.

As @j-f1 mentioned, we do list your repositories. If what he said doesn't address your issue and you have any constructive feedback to offer, please open a new issue.

**Comment by iAmWillShepherd** [comment]
@Scenario please open a new issue.

**Comment by iAmWillShepherd** [comment]
I've locked this conversation since the original issue is resolved. We now list all repos you have access to in the Clone Dialog on the GitHub.com tab.
