### ISSUE TITLE
search for file by path inside a commit

### ISSUE THREAD

**Issue by wx007** [desktop/desktop#2030]
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

[Description of the issue]

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** [version here]

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behaviour:** [What you expected to happen]

**Actual behaviour:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

If you are dealing with a performance issue or regression, attaching a
[Timeline profile](https://github.com/desktop/desktop/blob/master/docs/contributing/timeline-profile.md)
of the task will help the developers understand the runtime behaviour of the
application on your machine.

**Comment by joshaber** [comment]
@wx007 Could you give us more information? What specifically do you want to find?

**Comment by wx007** [comment]
The ability to locate a particular file in the long list of committed
files.
Since the columns won't open wide enough and the file I'm interested in is
a couple folders deep, I cannot visually locate the file.

My other comment is that this latest "desktop" (web) app is a step
backwards in functionality.

**Comment by j-f1** [comment]
@wx007

> My other comment is that this latest "desktop" (web) app is a step
backwards in functionality.

That’s why this is a beta version. I’m sure they’re hoping to have all of the features in the current native apps (plus more!) for when the app comes out of beta.

**Comment by joshaber** [comment]
>My other comment is that this latest "desktop" (web) app is a step
backwards in functionality.

Are there any other features in particular that you're missing?

**Comment by wx007** [comment]
That's great news, although I don't remember anything about volunteering
for a beta. I just ran the normal update procedure. Is there a way to
download the pre-beta client?

**Comment by j-f1** [comment]
@wx007 See the bottom of [this page](https://desktop.github.com).

**Comment by wx007** [comment]
Thanks!

**Comment by shiftkey** [comment]
This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by shiftkey** [comment]
A similar request but for filtering the changed file list: #3864

**Comment by andrew-sidereal** [comment]
This seems like extremely basic functionality which is missing. In large projects, this is unusable. I need a way to search by file extension, name, etc. It's in every other source control GUI I've used. https://i.imgur.com/ddQa7Ar.png

**Comment by bennettbrowniowa** [comment]
I'm committing a large group of files and have several that offend the 100 MiB limit. I'd like to uncheck them in the GitHub for desktop interface and make the commit. But there are 200 files - contributions to media assets - and I can't find the offending ones easily. Came here and #3864 looking for where this was in the UI. Still not there I guess. My existing workaround is to use OS Finder to find and move the files to another location and then put them back after making the commit.
