### ISSUE TITLE
Change milestone format to be more like how the Visual Studio Code team does it

### ISSUE THREAD

**Issue by jpike88** [desktop/desktop#2035]
Aiming for a 1.0 release is fair enough (I have a similar approach with my project), but I think the 'future-work' label is too ambiguous and not forward-thinking enough.

I recommend the team looks like a more monthly release like schedule, in order to give some sort of expectation of priorities in the near future.

Thoughts?

[Milestone link](https://github.com/Microsoft/vscode/milestones)

**Comment by shiftkey** [comment]
@jpike88 this is very early days, and nothing is set in stone. The core team is catching up soon to reflect on the launch and start planning for the coming months, and this is one of the areas to discuss. Thanks for the input!
