### ISSUE TITLE
Private Repo Error Message

### ISSUE THREAD

**Issue by SmeagolISEP** [desktop/desktop#2036]
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

Publish Repository window error show more information than expected
![screenshot_1](https://user-images.githubusercontent.com/21990458/27253335-4a7cf858-536a-11e7-9c1a-5002367f9680.png)

### Version

**GitHub Desktop version:** 0.6.1

**OS version:** Windows 10 Pro x64

### Steps to Reproduce

1. Make a new local repository
2. Publish it as private with free plan

**Comment by joshaber** [comment]
Thanks! This is really a manifestation of https://github.com/desktop/desktop/issues/2017, so I'll track it over there.
