### ISSUE TITLE
Beta don't ask credentials for private repos

### ISSUE THREAD

**Issue by papydeath95** [desktop/desktop#2043]
### Description

GitHub Desktop Beta don't ask for credentials to work with user restricted repositories, this is a huge problem using services other than GitHub.

Note that the normal version of GitHub Desktop ask for username and password.

### Version

**GitHub Desktop version:** 0.6.1

**OS version:** Microsoft Windows [Versión 10.0.15063]

### Steps to Reproduce

1. Clone a private repo that is not in GitHub from the command line
2. Add it to GitHub Desktop Beta
3. Try to push a change

**Expected behaviour:**

![](http://i.imgur.com/X3xh6MJ.png)

**Actual behaviour:**

![](http://i.imgur.com/KKKmD6y.png)

**Reproduces how often:**

Every time

**Comment by shiftkey** [comment]
@papydeath95 we are tracking this in #852, please follow along there.
