### ISSUE TITLE
Dialogs are closed when moving main window (macOS)

### ISSUE THREAD

**Issue by plashenkov** [desktop/desktop#2056]
### Description

Open a dialog, for example, `File -> Clone Repository`. Try to move GitHub Desktop window. Dialog is closed. Sometimes I start to enter data in dialog's fields. And when I not finished I need to move the app window. Dialog is closed, data is lost. I need to reenter data again.

### Version

**GitHub Desktop version:** 0.6.1

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** macOS Sierra 10.12.5

### Steps to Reproduce

1. Open a dialog
2. Move app window
3. Dialog is closed

**Expected behaviour:** dialog shouldn't close.

**Actual behaviour:** dialog closes.

**Reproduces how often:** always.

**Comment by j-f1** [comment]
Seems like the dialog should ignore clicks on the title bar.

**Comment by joshaber** [comment]
>Seems like the dialog should ignore clicks on the title bar.

Yup, I agree 👍
