### ISSUE TITLE
Can't log in to normal GitHub account after already logging into Enterprise

### ISSUE THREAD

**Issue by gbr** [desktop/desktop#2057]
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

Logging in to my GitHub enterprise account worked fine, but I couldn't afterwards log in to my normal account. If I simply type the username and password, the application hangs (though with the loader animation still rolling); if I use the "Sign in using your browser" option, it says "request to https://api.github.com/user failed, reason self signed certificate in certificate chain"

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** Version 0.6.1

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** macOS Sierra Version 10.12.5

### Steps to Reproduce

1. Log in to Enterprise GitHub account
2. Go to Preferences
3. Log in to normal GitHub account

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behaviour:** [What you expected to happen]

**Actual behaviour:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

If you are dealing with a performance issue or regression, attaching a
[Timeline profile](https://github.com/desktop/desktop/blob/master/docs/contributing/timeline-profile.md)
of the task will help the developers understand the runtime behaviour of the
application on your machine.

**Comment by shiftkey** [comment]
>  if I use the "Sign in using your browser" option, it says "request to https://api.github.com/user failed, reason self signed certificate in certificate chain"

This error seems like a proxy server or something is changing the certificate chain between the Electron app and GitHub itself (to insert itself?). Are you able to connect to GitHub in a regular browser (which one?) or do you get some sort of certificate issue there too?

**Comment by luto65** [comment]
I confirm the same behavior against our own Github Enterprise instance.
I've tried several options and all failed:
- authentication using the GitHub username/password
- authentication using  the browser 
- different ssh keys
Comparing the .gitconfig and also the .ssh/ contents these are very different for the beta compared to the 223 version.
This needs to be fixed before the new Desktop can be used for Enterprise instances.

**Comment by shiftkey** [comment]
@luto65 could you open a new issue and fill out the issue template? You seem to be encountering a different issue to the one initially reported. Thanks!

**Comment by gbr** [comment]
My apologies, it turns out the issue is a more general one with the network configuration from my company (bad private SSL key) and general git transactions. I will close this issue.

**Comment by zen-40** [comment]
Hello
