### ISSUE TITLE
Clarify the user's error message for missing remote origin

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2058]
If a user deletes the `Primary remote repository (origin)` field, and then tries to fetch/push/pull, an unclear error message is shown. The messaging to the user should be clarified into laymen terms.

Current error message:
<img width="504" alt="screen shot 2017-06-19 at 2 12 07 pm" src="https://user-images.githubusercontent.com/14828183/27299364-2cbe46dc-54fa-11e7-9e9a-c540ee6a6954.png">

Field can be deleted and saved, resulting in:
<img width="442" alt="screen shot 2017-06-19 at 2 05 56 pm" src="https://user-images.githubusercontent.com/14828183/27299362-2cb996d2-54fa-11e7-8d35-31bd93b7f08c.png">

Perhaps we should show an example or show the last used path here? 

v.0.6.1, OSX 10.11.5

**Comment by shiftkey** [comment]
@tierninho what's the use case on clearing the remote URL? Should we make that a separate action here to distinguish between editing the remote and removing, to ensure the user doesn't get into this weird state?

**Comment by tierninho** [comment]
@shiftkey Not sure there is a use case for clearing it, but for the novice user they might do such a thing "accidentally" especially since we give the option to. Yes, I would make it a separate action for editing/removing.

**Comment by tierninho** [comment]
Closing this as it has not come up enough times to be validated as a real problem.
