### ISSUE TITLE
Design Sync-up Agenda (June 20)

### ISSUE THREAD

**Issue by donokuda** [desktop/desktop#2060]
Last time on Design Sync: https://github.com/desktop/desktop/issues/1816

Issues marked as "Design": https://github.com/desktop/desktop/issues?q=is%3Aopen+is%3Aissue+label%3Adesign

Issues marked as "Enhancement": https://github.com/desktop/desktop/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement

---

### Action items from last week (in a much harder to parse list):

**Feature request - toggle full screen button** (https://github.com/desktop/desktop/issues/1809)
- [x] We'll take a cue from Chrome/YouTube and show a dialog explaining how to get out of fullscreen mode

**Scrolling diffs are cutoff after long commit message and description** (https://github.com/desktop/desktop/issues/1742)
- [ ] Someone to truncate at around 80 characters and move the remaining portion down to the description section.
- [ ] We still want to rethink the expand/collapse commit messages interaction.

**Improve commit message writing experience** (https://github.com/desktop/desktop/issues/1646)
- [ ]  Allow vertical resizing of the commit form (as well as horizontal resizing of the sidebar.) 

**Ability to make the file list wider** (https://github.com/desktop/desktop/issues/1588)
- [ ] Allow the sidebar to be resized until there's no more space.

**Creating a branch is hidden in the file menu** (https://github.com/desktop/desktop/issues/1575)
- [ ] Show text that says "You can create a new branch from the branch menu" with linking to the Create Branch dialog.

**Better compatibility with password managers** (https://github.com/desktop/desktop/pull/1513)
- [ ] Someone to rework the login screen so that the tab ordering is correct without having to explicitly setting the tab index.

**Make our blankslates a little friendlier**
- [ ] TBDiscussed at next week's mini-summit

---

### Item(s) to discuss

Last week was a lot of backlog work for us (@niik and @donokuda) so I don't think we gain any value adding any more things to talk about for this week before our mini-summit.

- [ ] **Add link to copy SHA to clipboard** (https://github.com/desktop/desktop/pull/1778)

I've been thinking about this more and we could do something like what Atom does here:

<img src="https://user-images.githubusercontent.com/1174461/27317661-b43a3822-553c-11e7-88a8-4a68113413f0.png" width="150" />

**Comment by iAmWillShepherd** [comment]
> Show text that says "You can create a new branch from the branch menu" with linking to the Create Branch dialog.

Where would this text be? Should it be permanently affixed to the top or would we need to scroll down to the bottom of our branch list?

**Comment by joshaber** [comment]
This seems outdated, can we close it @niik @donokuda?

**Comment by niik** [comment]
Yup!
