### ISSUE TITLE
Feature Request : Respect my OS colour selection

### ISSUE THREAD

**Issue by blowdart** [desktop/desktop#2062]
### Description

The Electron version goes its own way when selecting menu colours, ending up with some sort of depressing goth selection which makes me want to listen to The Smiths and drink absinthe.

### Version

**GitHub Desktop version:** 0.6.1

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Open GitHub desktop
1. Wallow in the bleakness of the world

**Expected behaviour:** You obey my happy OS colour selection

**Actual behaviour:** You're emo

**Reproduces how often:** Every time

#### Additional Information

Look at happy nice blue Outlook.
Glare at depressing GitHub desktop.

![snip_20170620072904](https://user-images.githubusercontent.com/796298/27338705-c886a4ca-558a-11e7-8dfe-35204e884873.png)

**Comment by shiftkey** [comment]
I was under the impression you were referring to the accent colour that is part of the Personalization view in Windows:

<img width="825" src="https://user-images.githubusercontent.com/359239/27343448-2cfdbc6a-55e3-11e7-8856-34b7ddc039a3.png">

But it looks like these are part of the "Colourful" them in Office:

<img width="392" src="https://user-images.githubusercontent.com/359239/27343464-4277144c-55e3-11e7-9f91-e7158d207cbb.png">

And differ per app:

<img width="1440" src="https://user-images.githubusercontent.com/359239/27343427-185bfae2-55e3-11e7-8808-4bf8816029bf.png">

So are you interested in us using the accent colour, or personalizing the main colour of the app away from emo black?

**Comment by blowdart** [comment]
Ah you make a good point, I'd forgotten Office is special. The highlight colour would be fine (and funnily enough in my case matches outlook). If you look at it from an accessibility POV then the OS settings for colours, fonts, font sizes etc. are more important than skinning the app, because people set those to affect everything.

**Comment by shiftkey** [comment]
For those of you who are curious, this is a sample that does P/Invoke to get all the immersive colours (as well as your selected one) - I think this is only usable for Win10 and Win8.

https://gist.github.com/paulcbetts/3c6aedc9f0cd39a77c37  (🎩 @paulcbetts)

**Comment by shiftkey** [comment]
>  If you look at it from an accessibility POV then the OS settings for colours, fonts, font sizes etc. are more important than skinning the app, because people set those to affect everything.

Yeah, there is precedence for this in the Electron docs - https://electron.atom.io/docs/api/system-preferences/ - but it needs some Windows love, hence the 20 questions around what to tackle first.

**Comment by shiftkey** [comment]
[Oh look, someone else already added this](https://electron.atom.io/docs/api/system-preferences/#systempreferencesgetaccentcolor-windows)

**Comment by blowdart** [comment]
Then accent colour, and font choices. Because accessibility, and because if you went full skinning someone is going to do hotdog stand and that just needs to stop.

**Comment by shiftkey** [comment]
cc @niik @donokuda for :eyes: and initial thoughts if you have them

**Comment by niik** [comment]
We discussed this in the weekly design review and we feel that customization in one form or another of colors in the app is interesting for the future but out of scope for our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md). 

I'm going to add the future-proposal label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by shiftkey** [comment]
Adding comments from @massivelines over at #3045 

>  By 'light" theme, I really meant the dark bars at the top, maybe like a medium gray. Usually, dark themes are too dark for my setup, I prefer more grayish themes, like the JetBrains ui, even made a different atom ui, https://atom.io/themes/neutral-gray-ui
>
> Check out how Adobe handles their colors and themes in their programs like Photoshop.
(edit > preferences > interface) It has four different brightnesses to choose from.
I know it will be way down the road but allowing us to create our own themes like atom would be pretty cool too.
>
> I know in windows, the personalization settings menu lets you change the color of your start menu and other things. It also controls a 1 - 2px border around programs. I have noticed that some programs set this color and it cannot be changed by the personalization. It could help frame the program, giving it a contrast edge all around. On the ones that cannot be changed, if it is primarily a dark color at the top it is usually a lighter shade and for a light color at the top, it is a darker shade.
>
> I am not sure how these will show up, it does depend on the brightness and colors of the monitor, so what I screenshot won't be what I see on my screen. I am running a color corrected monitor for design work which probably makes the top bar darker on me.
>
> ![dark](https://user-images.githubusercontent.com/10354555/31594972-0207a986-b1fe-11e7-93ce-8732d024bcf0.jpg)
> ![light](https://user-images.githubusercontent.com/10354555/31594973-0216eacc-b1fe-11e7-9a5a-62143097d1bc.jpg)

**Comment by billygriffin** [comment]
Hi @blowdart, thanks so much for the suggestion! Since we now have support for both a dark and light theme, I'm going to remove the `future-proposal` label here. Based on what we've heard from Windows and macOS users, most folks find one of the two themes really useful. Hopefully since this issue was before the dark theme shipped, things are working well for you. Thanks again!
