### ISSUE TITLE
Drag and drop of non-repo folder is rejected

### ISSUE THREAD

**Issue by JeffCohen** [desktop/desktop#2063]
### Description

When I drag/drop a folder from Finder, and that folder isn't a git repo yet, I get a message saying that it "isn't a git repository".

I would expect it to provide the same behavior as the "Add Local Repository" dialog, which lets you "Create and Add Repository" if the selected folder isn't a git repo yet.

### Version

**GitHub Desktop version:** 0.6.1

**OS version:** macOS 10.12.5

### Steps to Reproduce

1. Drag an arbitrary folder (not a git repo) onto the main windown
1. You'll get an error message saying that the folder isn't a repository

**Expected behaviour:** The folder should be converted into a Git repo, just like when you use the Add Local Repository feature.  This was the behavior of the previous Desktop app.

**Actual behaviour:** I get an error message.

**Reproduces how often:** Every time.

**Comment by joshaber** [comment]
Yeah, I think you're right. Let's track this as part of #2065.
