### ISSUE TITLE
Dragging and dropping a directory on to the app should use the Add Repository dialog

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#2065]
See also #2063.

I'm not sure if/how to handle when the user drags more than one directory into the app.

**Comment by JeffCohen** [comment]
My vote would be to reject a drop that has more than one top-level directory (maybe an error message, but a silent rejection is ok too).  

I think the 90% use-case is, you have a folder that you want to publish as a GitHub repo.  So let's just make that easy, and not try to worry about any other edge cases.
