### ISSUE TITLE
Uninstall / Unregister x-github-client

### ISSUE THREAD

**Issue by johanneswuerbach** [desktop/desktop#2069]
### Description

After trying out the beta all "Open in Desktop" links changed to use the `x-github-client` protocol. Uninstalling / trashing the beta seems not to revert the link protocol back to `github-mac` causing the stable version no longer be usable with "Open in Desktop".

### Version

**GitHub Desktop version:** Hasty Things Done Hastily (223) / Version 0.6.1
**OS version:** 10.12.5

### Steps to Reproduce

1. Install GitHub Desktop stable
1. Clicking on "Open in Desktop" opens the app 
1. Install GitHub Desktop beta
1. Clicking on "Open in Desktop" opens the beta
1. Remove  GitHub Desktop beta
1. Install GitHub Desktop stable
1. Clicking on "Open in Desktop" does nothing

**Comment by shiftkey** [comment]
We're tracking the cleanup of the protocol scheme in #1676 but the server-side integration is harder to do because GitHub The Website doesn't know that you've uninstalled the app. Did you sign into your GitHub account as part of testing out the beta?

**Comment by johanneswuerbach** [comment]
Yes, I did. I also tried to re-install and explicitly sign out, but that also didn't work.

**Comment by joshaber** [comment]
Thanks @johanneswuerbach! We'll continue to track this in #1676.
