### ISSUE TITLE
Default clone path goes to iCloud synced folder in OSX

### ISSUE THREAD

**Issue by jpike88** [desktop/desktop#2072]
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

The Documents folder in OSX is synced to iCloud typically. A very bad idea for a default clone path.

I suggest something like ~/user/Projects.

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** 0.6.1

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** OSX Sierra 10.12.5

### Steps to Reproduce

1. Clone a repo to default path

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behaviour:** I'm given a path that's not pointing at an iCloud synced folder

**Actual behaviour:** It didn't

**Reproduces how often:** Every time

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

If you are dealing with a performance issue or regression, attaching a
[Timeline profile](https://github.com/desktop/desktop/blob/master/docs/contributing/timeline-profile.md)
of the task will help the developers understand the runtime behaviour of the
application on your machine.

**Comment by shiftkey** [comment]
🚨 presses @joshaber klaxon for feels 🚨

**Comment by j-f1** [comment]
My Documents folder isn’t synced with iCloud, so I don’t see a reason to store my GitHub clones outside it.

**Comment by jpike88** [comment]
Well that's good for you...? The point is that OSX is designed with iCloud integration in mind, and I dare say a good chunk of OSX users leverage iCloud for certain things for convenience like safari bookmarks, contacts etc. It's an unpleasant surprise to clone and realise an absolute buttload of files are suddenly uploading to the cloud by default. This is an issue and the default behaviour needs to at the very least allow for choosing another folder, indicating that you might be accidentally cloning a repo to your iCloud folder.

**Comment by joshaber** [comment]
I can see an argument either way. For some users, I imagine it's a feature. I think we can wait and see if more folks chime in.

In the meantime, the app will remember the directory you last cloned into, so you can change that default easily.

**Comment by AJLeuer** [comment]
Agreed that GitHub shouldn't default to cloning to the user's `Documents` folder. In addition to the question of whether a user would even want their projects syncing to iCloud, there's the fact that the typical `~/Documents` folder is overcrowded to begin with. It's gone from the place where the user keeps their PDFs and Word docs to the place where seemingly every other application stores its data, making it harder for the user to find their actual documents (though admittedly this problem seems worse on Windows). 

It would be better to save to a directory that was specifically intended for code. If I could suggest an alternative, create a folder named `Developer` in the user's home directory and use this as the default path. macOS actually seems to be aware of `~/Developer`, since when you create a directory with this name it automatically gives it a special folder icon that integrates quite nicely with the other default user folders.

![image](https://user-images.githubusercontent.com/4187383/28543513-a610a79a-7085-11e7-9d16-6433095daba6.png)

Sidenote: If I'm not mistaken Xcode used to use `~/Developer` as its default when saving projects, but these days it seems be defaulting to saving on the Desktop (which besides being a terrible place to save _anything_ comes with the same iCloud syncing issues).

**Comment by MaXFalstein** [comment]
@AJLeuer is correct with the default Xcode Developer folder. My Xcode still saves to this folder but I have it mapped to duplicate to iCloud Drive and to my SANs.

macOS and iCloud Drive are excellent for most user's workflows. I have an iCloud Drive with 180 GB of the 200 GB consumed. All of my repositories are stored in GitHub, iCloud Drive and on my SANs.

I have 40 GB of repositories which is not massive but it is fairly substantial. iCloud Drive sync on a new MacBook is not very much fun unless I connect to a 1 Gbps Internet connection which was possible at my University.

Storing your repositories in iCloud Drive (Documents or general iCloud Drive) is not an issue; corruptions are unlikely to occur. Backups will help and redundancy is everyone's friend.
The data upload to GitHub and iCloud Drive is an issue to some users; however, it is not an issue for me. If I need bandwidth, I can use 4G LTE-Advanced cellular at up to 150 Mbps.

@AJLeuer, I am not sure why your Xcode is saving to the Desktop. I suggest checking your save settings.

**Comment by MaXFalstein** [comment]
@jpike88 are you asking GitHub to implement a feature in GitHub Desktop Settings `⌘+,` whereby the default save path is configurable?

I think this is the best way to resolve the issue you appear to have described.

**Comment by jpike88** [comment]
I'm not worried about corruption or bandwidth for my particular scenario, but it is just not being what I'd consider best practice.

Repos are stored in SVNs and almost always these have an online authority to sync to. To accidentally have that start appearing anywhere else but where it's been explicitly designed to appear is not a good idea IMO. It might be cool for music, documents etc, I think code repos should be treated more conservatively. 

Not just that but it may constitute a security risk as well as create some unpleasant surprises down the line. I just think it's not a good precedent to create.

I agree with @AJLeuer, use a local folder that is seperate from Documents which clearly designates your code folder, and not worry about it appearing anywhere else but where you cloned it to.

**Comment by MaXFalstein** [comment]
@jpike88 I see your points; if the computers were openly available, I would say there is a security risk. It all depends on strength of the passwords for the Apple Mac and the Apple ID. If they have terrible passwords, that would be a potential for risk.

**SVNs and online authority to sync**
That is an interesting point. I think this needs a bit more research. I sync on iCloud to 10 Macs (all of which have Git + GitHub Desktop and have no issues syncing from anywhere.

iCloud handles the changes rather well considering I usually sync using GitHub Desktop opposed to iCloud. iCloud can sync for me if the machine is running in the background.

There might be some unpleasant surprised down the line. We will have to see what happens.

**Comment by jpike88** [comment]
I do think that security is of concern, because it creates a few more attack vectors... if you know someone's Apple ID password, you can just go to iCloud.com (although two-factor authentication can stop that). But if you know the local password to a computer or even just the pin code of their iOS device, then the code is compromised. Which causes legitimate IP theft concerns for enterprises which may have developers that use Github Desktop.

I'd also like to see the opinion also of the guys in GitHub's internal team that works the closest to the 'metal' (i.e. git itself), and what their opinion is. I think the biggest root of the argument comes down to philosophy, or how code (essentially intellectual capital and property) should be treated. And as far as I believe, cloning a repo should do just that, clone not then sync to cloud storage elsewhere.

**Comment by MaXFalstein** [comment]
GitHub Enterprise is another thought entirely.
I think GitHub Desktop Enterprise should include greater control over security.

Mac in the enterprise sector should have a separate Apple ID to personal Apple ID - I do mix mine at times but I tend not to and have corporate and personal storage available.

I think the default for most users should be in their Documents folder in macOS.
I think the level to which you are discussing becomes more serious in enterprise applications of Git/GitHub.

GitHub Desktop Enterprise is what I would suggest for solving this issue in enterprise sectors.

**Comment by jpike88** [comment]
I think security should be taken seriously, enterprise or not. And Github Desktop has a responsibility to lean towards secure practices.

Also, "GitHub Desktop Enterprise" doesn't exist. Not only that, why create another variant of Github Desktop for the sake of a single default setting? It used to be like that, so why is this something that should now be considered an 'enterprise' concern?

**Comment by MaXFalstein** [comment]
In your previous response, you wrote about IP which is mostly professional based situations or private.

An Enterprise version of GitHub Desktop is where it should be if GitHub does not want to put it into the standard GitHub Desktop.

GitHub does have a responsibility to include best practices for security throughout their stack from client's Desktop (only the GitHub Desktop application) to the GitHub servers.

It will be interesting to see what GitHub does.

**Comment by shiftkey** [comment]
Hey all, just dropping some comments in here to let you know we're still mulling this over.

We've had some support issues in the past about repositories which are stored in synchronized folders like this being corrupted, and we recommend to not rely on this as their only way of backing up repositories across machines.

Regarding IP concerns, as a team we are currently happy to defer to how enterprises administer and lock down their machines in their environments, as they have much more experience in this space. If there are specific things we can be doing to play nice with existing tools, we are happy to discuss making those changes.

**Comment by jpike88** [comment]
Also consider the issue regarding dependency management systems, I use NodeJS and my node_modules folder can get a massive amount of files in it. It’s actual footprint is small (a few MB) but the pure number of files can choke up auto sync mechanisms... not to mention that it’s once again not ‘proper’ to be syncing that sort of thing to begin with.

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by reknoZ** [comment]
I'd like to reopen this. I, too, use iCloud Documents & Desktop, but I am also with the free 5 GB and cannot afford any premium package. Yes, I know it's cheap, but I can't afford it. So, I'd like to be able to save my repositories where *I* want them, not where gitHub thinks they should be.

Thanks.

**Comment by j-f1** [comment]
You should be able to save them wherever you’d like — just select the file path you prefer and the app will remember it for you.

**Comment by reknoZ** [comment]
I'm following a YouTube video which creates the repository on the GitHub website and then uses the desktop app to clone it. I didn't see a way to select the local folder when I started the clone, and I don't see a way to change the local folder now that it's already been cloned.

Maybe I'm missing something, but as far as I can tell, this feature doesn't exist.

**Comment by j-f1** [comment]
You should be able to move the cloned folder, then use the “Locate…” button to tell the app the new location.

When you clone another repository, you should see an input field at the bottom of the dialog with the path the clone will have, which you can either change directly or update with the “Browse…” button.

**Comment by reknoZ** [comment]
Yes, I already managed to move it. Next time I create a new one, I'll look out for the option to select destination folder. Thanks.

**Comment by shiftkey** [comment]
> Next time I create a new one, I'll look out for the option to select destination folder. Thanks.

@reknoZ check out the **Local path** option in the clone dialog:

<img width="587"  src="https://user-images.githubusercontent.com/359239/40286090-4e3b462a-5ce7-11e8-894e-b6e23cd4b838.png">

**Comment by reknoZ** [comment]
Thanks, guys! I see it now. Yeah, I just went too fast and didn't see it (or know to look for it) when I cloned the first time. Thanks for helping me and not making me feel *too* stupid.

**Comment by danemacmillan** [comment]
@MaXFalstein I'm interested in knowing how performance of your computer is impacted having `40GB` of repositories in iCloud, which must ultimately be hundreds of thousands of files, if not millions. Doesn't your CPU just go nuts at all hours with the cloning and pulling? This is an avenue I'm interested in exploring for redundancy purposes, and to reduce downtime when switching to a new machine. The idea of having hundreds of thousands of tiny files synchronizing seems like a bad idea; for example, I have a codebase that builds to 98k files. On any given day I could rebuild this code four or five times. That would entail deleting all those files and adding them that many times. Is this a workflow you experience? Is the reason you have `40GB` of data because of binary files, or is that all tiny files?

**Comment by billygriffin** [comment]
Hi folks, thanks for the thoughts here. I'm going to remove the `future-proposal` label here as users can choose where they want to clone repos, and it's not very burdensome to move them if you're cloning from dotcom. This is also only the case for some portion of macOS users, and you're able to configure what's synced to iCloud and what isn't. Thanks for the input, and we're happy to revisit if we see that people are running into trouble from this.

**Comment by defjaf** [comment]
I know this is closed, but I did want to comment that I’ve had some serious problems which seem to be related to having repositories cloned into iCloud-synced folders, which are then separately mirrored onto both a laptop and a desktop. Perhaps because of the latter point, I’ve now had two separate occasions where my iCloud syncing has basically died. It left the two machines in different states but officially both still syncing with iCloud (other iCloud syncing by individual apps still worked). With one machine refusing to complete either uploads or downloads of many files. It seems to have only been continued and completed by removing several cloned repositories from both machines.

**Comment by danemacmillan** [comment]
@defjaf Would you happen to know how many files existed among all the repositories you synced into iCloud? Do you have numerous `node_modules` directories?

**Comment by defjaf** [comment]
@danemacmillan Hmmm, I don't think `node_modules` in particular was a problem. I do seem to some of those scattered around my machine, but mostly in directories that were never in the synced folders (I don't program in node myself).

But I'm sure it was a lot of files all together (especially including all the information stored in the `.git/` directories).

**Comment by omundy** [comment]
I have been seeing students in my classes with this folder in their iCloud/Documents. In their constant effort to dumb down their users and make them dependent on their $ervices, Apple is defaulting to cloud-synced directories whenever possible. If [we know not to store repos in iCloud](https://support.apple.com/en-us/HT201104), shouldn't Github Desktop should warn users when they attempt to use a cloud-synced directory?
