### ISSUE TITLE
No button to make a pull request Beta 0.6.1

### ISSUE THREAD

**Issue by syedusmanali** [desktop/desktop#2074]
Am not able to find the button to create a pull request

**GitHub Desktop version:** Beta 0.6.1
**OS version:** Microsoft Windows [Version 10.0.15063]
**Expected behavior:** Should be a button to create a pull request
**Actual behavior:** No button to create a pull request

**Comment by shiftkey** [comment]
@syedusmanali we're tracking this in #295. Please follow along with that issue.
