### ISSUE TITLE
Add label names for the repository

### ISSUE THREAD

**Issue by coaperator** [desktop/desktop#2078]
I have several repositories in different folders
```
repos/app1/www
repos/app2/www
repos/app3/www
```
When adding / creating a repository, you need a field to add the name of the repository, or it is unclear which repository in the list

![image](https://user-images.githubusercontent.com/6645911/27395321-d34010f6-56c8-11e7-8978-7df72e58c6fb.png)

**Comment by joshaber** [comment]
Thanks for the feedback! We're already tracking this in #1929. Feel free to follow along over there.

**Comment by coaperator** [comment]
@joshaber excellent, thanks!

**Comment by synapse709** [comment]
This should have been in Github desktop from version 1. It's an essential and basic feature.
It's not a big ask, but your users will thank you.
Please add it!
