### ISSUE TITLE
I propose to change the buttons in places

### ISSUE THREAD

**Issue by coaperator** [desktop/desktop#2079]
I propose to change the buttons in places

1. Because we read from the left to the right and we perceive the information in the same way
2. Because it is more logical to have the old changes in the left column, and the new ones in the right column

I draw your attention to the fact that when you run the program a column with new data is allocated - let it remain.
If the "Changes" column is empty, then the "History" column should be highlighted

![image](https://user-images.githubusercontent.com/6645911/27395455-4d6f1df4-56c9-11e7-82c9-0a522d9a3f5a.png)

**Comment by joshaber** [comment]
Hi @coaperator, thanks for opening this!

I believe our thinking was that Changes was more important, and since, as you noted, many of us read left to right, we should put the more important tab first.

I'll leave this open for @niik and @donokuda to make the final determination.

**Comment by coaperator** [comment]
@joshaber Thank you! I made this proposal for the future, when there will be free time to implement this function. I'm sure this would improve UX

**Comment by joshaber** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by coaperator** [comment]
Repeated request for adding improvements. Can we do it?

**Comment by coaperator** [comment]
Repeated request for adding improvements. Can we do it?

**Comment by billygriffin** [comment]
Hi @coaperator, thanks for following up. We still agree with @joshaber's initial read on this that "Changes" is more important for the core functionality of GitHub Desktop, and therefore we're comfortable with it being on the left. Thanks again for the idea!
