### ISSUE TITLE
unable to create branch

### ISSUE THREAD

**Issue by BUTCHPATTERSON** [desktop/desktop#2081]
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

[unable to create readme-edits branch linked to master branch in hello-world repository]

### Version 

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** [0.6.1]

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** [Microsoft Windows 10.0.15063]

### Steps to Reproduce

1. [using the drop down arrow to the right of the master branch to create readme-edits branch.]
1. [after typing "readme-edits' I pressed the ENTER key.  The create branch window went away. readme-edits branch was not listed.  I re-did this step several times with same results.]
1. [the last time I did the steps above I didn't press the ENTER key.  Instead I click the commit to master button several times which resulted in gitattributes under current branch, master.

+# auto detect text files and preform LF normalization
+* text=auto 

I uninstall the GitHub desktop and re-install it again but get the same gitattributes .  there is no drop down arrow to the right of master to create a branch.  

]

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behaviour:** [What you expected to happen]

**Actual behaviour:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]
[github-branch-error.docx](https://github.com/desktop/desktop/files/1092302/github-branch-error.docx)

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

If you are dealing with a performance issue or regression, attaching a
[Timeline profile](https://github.com/desktop/desktop/blob/master/docs/contributing/timeline-profile.md)
of the task will help the developers understand the runtime behaviour of the
application on your machine.

**Comment by tierninho** [comment]
Hi @BUTCHPATTERSON 

> [using the drop down arrow to the right of the master branch to create readme-edits branch.]

> [after typing "readme-edits' I pressed the ENTER key. The create branch window went away. readme-edits branch was not listed. I re-did this step several times with same results.]

> [the last time I did the steps above I didn't press the ENTER key. Instead I click the commit to master button several times which resulted in gitattributes under current branch, master.

Based on the steps you described, it sounds like you are trying to enter the branch name in the search field, like this below. 

<img width="379" alt="screen shot 2017-06-21 at 2 21 26 pm" src="https://user-images.githubusercontent.com/14828183/27400183-49a63dc4-568d-11e7-9ce3-8cf7ec4109bd.png">

Instead, select `Branch` from the menu and click `New Branch`.

<img width="329" alt="screen shot 2017-06-21 at 2 21 14 pm" src="https://user-images.githubusercontent.com/14828183/27400182-49a4f3c4-568d-11e7-8f23-94c11dad844e.png">

**Comment by shiftkey** [comment]
Closing this out as the behaviour has changed between the classic Windows app and the new app, and @tierninho has pointed out the new flow.
