### ISSUE TITLE
Error when publishing repository to GitHub

### ISSUE THREAD

**Issue by HeardMatthew** [desktop/desktop#2083]
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

When I click "Publish repository" on the desktop, if I do something restricted when trying to publish (ex. making a private repository without an upgraded account, making a repository with the same name as another one), I correctly receive an error from the desktop application. However, the error does not seem to be formatted correctly. For example, it will say: 

{"message":"Please upgrade your plan to create a new private repository.","documentation_url":"https://github.com/pricing"} POST https://api.github.com/user/repos Status: 422

This does not appear to be formatted the way your company has intended. Just a heads up!

PS: you've misspelled "summarize" in this form, above the Description section. 

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** [0.6.1]The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** [Microsoft Windows Version 10.0.14393]

### Steps to Reproduce

1. Try to create a new repository on GitHub Desktop, or add a local depository. 
2. Click "Publish directory".
3. Attempt an illegal operation on the next prompt, and click Submit. 

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behaviour:** [A correctly formatted error code]

**Actual behaviour:** [Error code appears misformatted]

**Reproduces how often:** [100%]

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

If you are dealing with a performance issue or regression, attaching a
[Timeline profile](https://github.com/desktop/desktop/blob/master/docs/contributing/timeline-profile.md)
of the task will help the developers understand the runtime behaviour of the
application on your machine.

**Comment by joshaber** [comment]
Thanks! We're already tracking this at https://github.com/desktop/desktop/issues/2017. Feel free to follow along over there!

**Comment by sneistat** [comment]
Thank you for your help.

Sent from my iPad
Susan Neistat
