### ISSUE TITLE
Disable Publish button in Repository Settings if no commits for a new repo

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2086]
If you create a new repo and undo the initial commit the `Publish` button in the main menu is disabled by design, however, you can still access the publish the repo via the Repo Settings modal, which results in an "unborn branch" error.

v0.6.1, OSX 10.11.5

Reproduce:
- Create new repo  (File > New Repo)
- Undo initial commit (`Publish` button should disable)
- Go to Repository > Repo settings
- Click `Publish`, try to publish

The `Publish` button on the repo settings modal should be disabled and/or the text should change to reflect the state.

<img width="916" alt="screen shot 2017-06-22 at 9 08 08 am" src="https://user-images.githubusercontent.com/14828183/27435772-2158b8d0-572b-11e7-8504-eb43b57fa0aa.png">
<img width="448" alt="screen shot 2017-06-22 at 9 11 03 am" src="https://user-images.githubusercontent.com/14828183/27435773-216903c0-572b-11e7-9f6b-9decd087c695.png">

**Comment by shiftkey** [comment]
> If you create a new repo and undo the initial commit the `Publish` button in the main menu is disabled by design, however, you can still access the publish the repo via the Repo Settings modal, which results in an "unborn branch" error.

This makes me think we're going about it the wrong way - we should let the user publish always, and detect when the repository is unborn and skip the attempt to push the branch. There may need to be some UX thoughts about this to distinguish between publish and push, but maybe we just need to make "push" clear that it has nothing to push.
