### ISSUE TITLE
Why two input fields?

### ISSUE THREAD

**Issue by coaperator** [desktop/desktop#2087]
**Explain please, why are there 2 fields for input?**

![image](https://user-images.githubusercontent.com/6645911/27437220-0001fb9c-577b-11e7-911c-315204be10da.png)

**In other GUI clients one field, for example in SourceTree**

![default](https://user-images.githubusercontent.com/6645911/27437536-fe246a98-577b-11e7-9d30-afb3866a4d23.PNG)

**Maybe it will be better to leave one field?**

**PS: How to put a label on a publication?**

**Comment by tierninho** [comment]
@coaperator The `summary` is a mandatory field and is meant for a brief explanation of your commit. The `description` field is for a longer explanation of your commit -- it is optional. Both are unlikely to change.

<img width="1056" alt="screen shot 2017-06-22 at 9 55 08 am" src="https://user-images.githubusercontent.com/14828183/27437899-b07d4e94-5731-11e7-95ce-15275cc97b0f.png">

> How to put a label on a publication?

Do you mean a label on this issue? Use the menu to the right ---->

**Comment by coaperator** [comment]
@tierninho understood everything, thanks!
