### ISSUE TITLE
Question: Release Schedule 

### ISSUE THREAD

**Issue by say25** [desktop/desktop#2088]
Questions:
- What does the release schedule look like? 
- Are you planning a release soon? 
- Do you have typical patterns for releases?
- Would milestones be a good way of tracking these?
- Do we need a releaseSchedule.md?
- Does desktop uses semantic versioning?

**Comment by joshaber** [comment]
Good questions!

>What does the release schedule look like?
>Would milestones be a good way of tracking these?
>Do we need a releaseSchedule.md?

Our releases to date have been ad hoc. Next week the team will be together and we'll talk through this among other issues.

>Are you planning a release soon?

Yup! I'm planning to do one later today.

>Do you have typical patterns for releases?

I'm not sure what exactly you're looking for here. Could you be more specific?

>Does desktop uses semantic versioning?

Semantic versioning is meant for APIs. If we were to have extensions at some point in the future, we'd need to consider this.

**Comment by say25** [comment]
Typical patterns meaning: 
- Do we do a few bug update releases before a major feature release?

- Do we release a long term support release (I’m guessing no on that)?

**Comment by joshaber** [comment]
>Do we do a few bug update releases before a major feature release?

Nothing so formal as that, but we'll probably have a tendency to do bigger releases with new features for the marketing impact.

>Do we release a long term support release (I’m guessing no on that)?

No plans currently.

**Comment by joshaber** [comment]
I'll leave this open and update it after the team talks next week.

**Comment by joshaber** [comment]
This is hopefully addressed by #2144. Let me know if you have any more questions!

**Comment by say25** [comment]
Looks great thanks for considering this @joshaber
