### ISSUE TITLE
API error for publishing repo sans internet connection

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2089]
We should rewrite the api error message for users if the internet is cut ahead of publishing there repo.

Reproduce:
- File > New repo, fill out
- Turn off internet
- Try to click `Publish`

v 0.6.1, OSX 10.11.5

<img width="1175" alt="screen shot 2017-06-22 at 12 21 53 pm" src="https://user-images.githubusercontent.com/14828183/27444948-1348b018-5746-11e7-9cf8-7c38bff17fab.png">

**Comment by shiftkey** [comment]
I get a different error running the `0.6.2` dev build and disabling the WiFi:

<img width="704" src="https://user-images.githubusercontent.com/359239/27509388-cb0c3452-58b0-11e7-8a9b-6614bba8a0d0.png">

We can improve this copy (we rethrow an error here) and clean up the console output as part of this PR.
