### ISSUE TITLE
Add confirmation dialogue for restart of Desktop when an action is being performed

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2093]
When the "see what's new and restart" banner is displayed upon download of the latest build, we should add a confirmation dialogue if a user restarts and an action is still being performed. 

For instance, if a large repo is still cloning and the restart link is clicked, the whole process must be restarted leading to problems like in issue #2082 

Or perhaps we just don't display the banner until the app recognizes no actions being performed?

v0.6.1

**Comment by shiftkey** [comment]
We don't show the "an update is ready" message for cloning or missing repositories, but ensuring you don't update when a clone is in progress is A++. I think disabling the update when we know a clone is in flight is the safest option, but I'll let others share their thoughts on the UX here...

**Comment by j-f1** [comment]
You could run `git` operations that use the network in a totally separate process, then reconnect when the update completes.

**Comment by tierninho** [comment]
Closing this as it has not come up enough times to be validated as a real problem.
