### ISSUE TITLE
Remove ".com" from tooltip

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2094]
Should ".com" be removed from the tooltip upon hover over `View on GitHub` as it might confuse Enterprise users?

<img width="939" alt="screen shot 2017-06-23 at 8 31 31 am" src="https://user-images.githubusercontent.com/14828183/27482274-d1abdc12-57ee-11e7-83ba-502a48e55b91.png">
<img width="329" alt="screen shot 2017-06-23 at 8 47 28 am" src="https://user-images.githubusercontent.com/14828183/27482756-af29d4c6-57f0-11e7-9b61-dca63047340d.png">

v0.6.1

**Comment by j-f1** [comment]
It could also change to show the domain of the GitHub Enterprise instance.

**Comment by shiftkey** [comment]
> It could also change to show the domain of the GitHub Enterprise instance.

I think, to be consistent with the grouping headers, it should also say `GitHub Enterprise`. 

[This does not appear to be the case](https://github.com/desktop/desktop/blob/e2d9e7b3f86b2ed9469697d21a411e5add5b564e/app/src/ui/history/commit-summary.tsx#L200-L209)

**Comment by j-f1** [comment]
How about something like this?

> [View on GitHub Enterprise]

(hover to see title text)

[View on GitHub Enterprise]: https://gstatic.net/generate_204 (View this commit on the-enterprise-domain.com)
