### ISSUE TITLE
Update put GitHub Desktop icon back on desktop

### ISSUE THREAD

**Issue by Studio384** [desktop/desktop#2098]
### Description

After an update, GitHub Desktop will recreate the icon on the desktop.

### Version

**GitHub Desktop version:** 0.6.2

**OS version:** Windows 10, version 1709

### Steps to Reproduce

1. Update GitHub

**Expected behaviour:** The icon isn't recreated

**Actual behaviour:** The icon is recreated

**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
@Studio384 this is already tracked in #1759 - please follow along there.
