### ISSUE TITLE
Repeated error messages when attempting to "upload" small files

### ISSUE THREAD

**Issue by mvpetruzzelli** [desktop/desktop#2100]
When I have attempted to move a folder containing three .do files all 3 KB or smaller to my GitHub Desktop, I receive the following error message:

<img width="623" alt="screen shot 2017-06-23 at 3 09 51 pm" src="https://user-images.githubusercontent.com/29547395/27500701-39b85a20-582f-11e7-8b92-fa67eff9c5a9.png">

The message always comes up in multiples (3-4), and will continue to come up minutes later, as well as in a new session, and even after I uninstalled and reinstalled GitHub desktop.

### Version
**GitHub Desktop version:** [0.6.2]

**OS version:** [10.9.4]

Reproduction:

1. Attempt to move the folder containing the three .do files all of 3 KB or smaller into GitHub desktop
2. Initial message should pop up after a couple of seconds with the above complaint that more than 10 MB would be needed to upload the file. 

**Expected behaviour:** I expected to have the file added to my repository without issue.

**Actual behaviour:** I received the error message and have constantly been receiving it since, and still receive it when I try to upload to GitHub Desktop.

**Reproduces how often:** Reproduces every few minutes, and certainly every time GitHub Desktop is opened.

There was no GitHub Desktop folder in Application Support, otherwise I would provide the log.
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`

**Comment by shiftkey** [comment]
@mvpetruzzelli to clarify this step:

> Initial message should pop up after a couple of seconds with the above complaint that more than 10 MB would be needed to upload the file.

This is related to the output when trying to diff this file - even if this doesn't work, you should be able to commit the file and push it.

Could you see if there is anything interesting under `View | Toggle Developer Tools` and in the Console tab? You should see a `git diff` command failing there.

**Comment by mvpetruzzelli** [comment]
I'm not seeing anything interesting under the console tab. This is what my console tab looks like:
<img width="964" alt="screen shot 2017-06-24 at 12 47 41 pm" src="https://user-images.githubusercontent.com/29547395/27510685-df2e1d58-58db-11e7-9255-3e75ed255ee1.png">

**Comment by joshaber** [comment]
@mvpetruzzelli Would you be able to share your repository with us so that we can try to reproduce it?

**Comment by joshaber** [comment]
Thank you for your issue!

We haven't gotten a response to our questions above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the issue.
