### ISSUE TITLE
Question: Open-source website

### ISSUE THREAD

**Issue by j-f1** [desktop/desktop#2101]
Currently, the website (https://desktop.github.com) is [closed-source](https://github.com/github/desktop.github.com). Since this version of GitHub Desktop is open-source, it would be nice to have the website be open-source, too. However, if you have a reason I don’t know about that requires the website to be closed-source, I understand that.

On an unrelated note, I think it would be clearer if the @desktop team members made their membership public (there’s [a dropdown](https://user-images.githubusercontent.com/25517624/27501594-4e208cf0-583c-11e7-8207-d8c64350a88e.png "that text color though") next to your name [here](https://github.com/orgs/desktop/people)) so other users can tell that you’re not just random people commenting on their issues/PRs.

**Comment by shiftkey** [comment]
@j-f1 the Desktop website is a rather mundane Jekyll site. At this point I'm not sure of the value of open sourcing it - is there something in particular you are missing out on aside from viewing the source?

> On an unrelated note, I think it would be clearer if the @desktop team members made their membership public

I've flipped my bit to make this clear to external contributors, but this is a personal choice for each person to make.

**Comment by joshaber** [comment]
Also note that comments from Core members will have an **Owner** badge on them:

<img width="221" alt="screen shot 2017-06-26 at 8 22 22 am" src="https://user-images.githubusercontent.com/13760/27538988-9c737616-5a48-11e7-924f-ec4139be4cfe.png">

**Comment by Plasmmer** [comment]
Open-source website is good for pull requests, like the Linux version links.

**Comment by shiftkey** [comment]
We have no plans to open source the website at this stage.
