### ISSUE TITLE
Adjust width of line number column based on number of lines in file

### ISSUE THREAD

**Issue by kert-io** [desktop/desktop#2102]
Why are the line number columns so wide?  Minor I know, but annoying to look it.  Can we make it adjust to the size needed or let the user define it?

**Comment by shiftkey** [comment]
Fun fact: I'm not sure. I say this because it was me who [defined this value wayyyyyy back in the day](https://github.com/desktop/desktop/commit/5b48ce64f4085e72ad7ea3be1c0ebd9a3f286784) and I think I was settling on 50px for each column (which seems to fit 7 digits nicely, enough for even the longest file requiring diff-ing).

**Comment by shiftkey** [comment]
I'll leave this open for someone who wants to explore making this flexible based on the column width - but do keep in mind that Git's diff hunks might jump from low numbers to really high numbers - so the column width should be flexible.

**Comment by shiftkey** [comment]
Updated the title to make this issue clearer.

Another thing to point out is that the diff gutters are selectable, and having a large enough hit zone helps with discoverability - we've been talking about improving this in #1688

**Comment by kert-io** [comment]
Thanks for the thorough reply.  Points taken.  I always prefer control and
flexible ui where possible.

**Comment by shiftkey** [comment]
I think, if there are any changes to make to the diff gutter, it'll be based on the resolution of #1688. 

No point tracking this separately at this point.

**Comment by adamreisnz** [comment]
Hi @shiftkey , I just wanted to raise this issue myself, but found this one which had been closed, although seemingly without concrete resolution.

#1688 does not seem to propose a concrete solution for the gutter width. 

Is it possible to reopen this and at least allow us to resize the gutter column like we can resize the left column as well, while design changes in general are being discussed? They are way too large at the moment, there is no way I will ever require 7 characters for a line number.

**Comment by shiftkey** [comment]
@adamreisnz that's a fair point. I'm going to add the `needs-design-input` label here and try and get some input from @donokuda before he goes on holidays about his feels on this suggestion:

> Is it possible to reopen this and at least allow us to resize the gutter column like we can resize the left column as well, while design changes in general are being discussed? 
> ...
> In the old client they were much more narrow and less obtrusive.

**Comment by adamreisnz** [comment]
Thanks, awesome!

Has any thought been given around having a customisable `.githubdesktop/style.scss` or similar with which users could override the styles in the UI? That could solve a lot of these layout related issues, which sometimes just boil down to preference.

**Comment by shiftkey** [comment]
> Has any thought been given around having a customisable `.githubdesktop/style.scss` or similar with which users could override the styles in the UI?

I recall a request for this early in the beta around being able to increase the font size, which we eventually added in #1720. 

Generally speaking, I'd rather not go down the path of this sort of extensibility currently, and instead I think the team would love to understand how people want to tailor their UI to see what we can get into the product in the near term.

**Comment by donokuda** [comment]
> Is it possible to reopen this and at least allow us to resize the gutter column like we can resize the left column as well, while design changes in general are being discussed? They are way too large at the moment, there is no way I will ever require 7 characters for a line number.

The ✨ dream ✨ I have in mind is that we would have a minimum width defined (so that the click target is reasonable) and the actual width of the gutter would be determined by how many lines are in a diff.

For example, if a file has 300 lines, then the width would be wide enough for 3 numbers. If a file has 20 lines, then the width would be wide enough for 3 numbers (I've arbitrarily chose 3 numbers as the minimum.) If a file has 1000 lines, then the width would be wide enough for 4 numbers.

**Comment by adamreisnz** [comment]
I'd be ok with that approach, seems to make sense. If a file does have 1000+ lines, then the gutter width could expand to accommodate for 4 digits or more. But to make it fit 7 numbers by default as currently is the case seems a bit excessive ;)

**Comment by billygriffin** [comment]
> The ✨ dream ✨ I have in mind is that we would have a minimum width defined (so that the click target is reasonable) and the actual width of the gutter would be determined by how many lines are in a diff.

> For example, if a file has 300 lines, then the width would be wide enough for 3 numbers. If a file has 20 lines, then the width would be wide enough for 3 numbers (I've arbitrarily chose 3 numbers as the minimum.) If a file has 1000 lines, then the width would be wide enough for 4 numbers.

We discussed this internally and we're comfortable with this approach if someone wants to take a stab at it.
