### ISSUE TITLE
Option to set default clone path in MacOS

### ISSUE THREAD

**Issue by Sibiraj-S** [desktop/desktop#2106]
### Description

Feature Request. add an option for selecting default path for cloning repository 

### Version

**GitHub Desktop version:**  0.6.2

**OS version:** MacOS Sierra 10.12.5

**Expected behaviour:**  An option to select default path in MacOS

**Actual behaviour:**  the default clone location always points to `Downloads` or `last clone location`. This feature is available for Windows.

**Comment by shiftkey** [comment]
@Sibiraj-S a couple of things to mention:

 - the default clone path is remembered whenever you change it as part of performing a clone, or creating a new repository. 
 - while this was an explicit option in GitHub Desktop on Windows, we settled on this behaviour from the Mac app as it wasn't something that users changed often, and the setting would update without having to make users open the options menu.

**Comment by Sibiraj-S** [comment]
I thought to have an option explicitly will be nicer. If already decided to have this behaviour. Can close this issue.

**Comment by shiftkey** [comment]
@Sibiraj-S thanks for the feedback anyway!

**Comment by Sibiraj-S** [comment]
@shiftkey . I also have another suggestion regarding removing a repo. do I have to open a new issue for that

**Comment by shiftkey** [comment]
>  do I have to open a new issue for that

Please read [this guide](https://github.com/desktop/desktop/blob/master/CONTRIBUTING.md#suggesting-enhancements) and do a search of the open issues to ensure it's not something already being discussed.

**Comment by nlourenco-tsd** [comment]
Request for Windows as well.
