### ISSUE TITLE
sloppy

### ISSUE THREAD

**Issue by lukasa1993** [desktop/desktop#2116]
# The new native
![ffs](https://user-images.githubusercontent.com/1499012/27519035-3867ed5a-59fd-11e7-87fc-cf01a74ebb5d.png)

> Toggle Developer Tools

…

**Comment by j-f1** [comment]
Why is that sloppy?

**Comment by lukasa1993** [comment]
so that's a feature? 
![ddbee6fumaatp4q](https://user-images.githubusercontent.com/1499012/27519203-d8ab1b46-59ff-11e7-88b4-83c001d7b50c.jpg)

**Comment by j-f1** [comment]
That’s a feature — the app is built with React and TypeScript, so it’s useful to be able to open the DevTools to test out a CSS change or debug a new feature.

**Comment by lukasa1993** [comment]
in production ?

**Comment by j-f1** [comment]
I don’t see why it’s a problem to have it in production. [Atom](https://atom.io) has a similar menu item in production, too. If you don’t like it, just don’t click it 😄.

**Comment by shiftkey** [comment]
@lukasa1993 this is something we decided to enable for the beta period so that users could dig information beyond the user-facing errors and log files.

We'll decide closer to the 1.0 milestone whether this is worth continuing to do in the future.

**Comment by lee-dohm** [comment]
@lukasa1993 your comments are a violation of the [Desktop Code of Conduct](https://github.com/desktop/desktop/blob/master/CODE_OF_CONDUCT.md) as they are insulting or derogatory. You may consider this an official warning.

**Comment by lukasa1993** [comment]
could you please point to my violation comment and to the conduct part i violated?

**Comment by lee-dohm** [comment]
> could you please point to my violation comment and to the conduct part i violated?

The title of this issue and as I stated "insulting or derogatory".

> also i am not contributor i just use app still i must follow your contributor conduct?

By submitting an issue you're contributing to the development of GitHub Desktop, so yes, you are expected to follow our code of conduct.
