### ISSUE TITLE
Can I use Github Desktop for private Gitlab server?

### ISSUE THREAD

**Issue by doodlemeat** [desktop/desktop#2118]
I have added my repository through the github desktop client. I am now trying to push a few changes but then it tells me:

"Authentication failed. You may not have permission to access the repository. Open preferences and verify that you're signed in with an account that has permission to access this repository."

I open preferences but I can't find anywhere to enter my credentials. I can only find Github and Github enterprise but neither of those do I use.

**Comment by tierninho** [comment]
Please see issue #852 for tracking of this feature.
