### ISSUE TITLE
Corrupt patch when doing partial commits

### ISSUE THREAD

**Issue by nycdotnet** [desktop/desktop#2123]
### Description

I am trying to commit 15 files to my branch.  For several files I am committing all of the changes, for several I am committing only some of the changes.  I am getting an error after clicking the "Commit to branchname" button: "error: corrupt patch at line 31".

### Version
**GitHub Desktop version:** 602

The operating system you are running on may also help with reproducing the
issue:

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Select all changes in some files and some line changes in other files.

**Expected behavior:** Valid commit

**Actual behavior:** Corrupt patch at line X error.

**Reproduces how often:** It seems to reproduce or not reproduce in my environment consistently.  I can unselect certain files and commit so it does appear to be something specific about my repo and the combination of files selected/line commits selected.  I am going to try to investigate and submit a PR if I can figure it out.  Creating this issue in the meantime.  Likely same issue as #538.

### Logs

```
2017-06-26T21:05:56.303Z - error: [ui] `git apply --cached --unidiff-zero --whitespace=nowarn -` exited with an unexpected code: 128.
error: corrupt patch at line 31
```

#### Additional Information

None

**Comment by nycdotnet** [comment]
I think I've got a fairly solid repro.

The issue happens with files that show the little prohibit symbol in GitHub Desktop at the file end (see "before" line 35 in the attached screenshot).  With my changes, the prohibit symbol shows in the "before" (salmon lines), but is not present in the "after" (green lines).  What does the prohibit symbol represent in this context?

![githubdesktop-issue2123](https://user-images.githubusercontent.com/3755379/27561985-698e8f88-5a98-11e7-9992-4e7c2b5bf97f.PNG)

Anyway - in any file where the "before" version ends with a prohibit symbol, trying to do a partial commit on any set of lines _above_ the block with the prohibit symbol causes a `The requested changes conflict with one or more files in the repository.` error.  Attempting to do a partial commit including any set of lines _below or including_ the "before" prohibit symbol causes a `Corrupt patch at line X` error.

That make any sense?

**Comment by j-f1** [comment]
The icon represents the fact that the file does not have a trailing newline.

**Comment by joshaber** [comment]
Really interesting @nycdotnet! Any chance you could send us the files or the repository?

**Comment by nycdotnet** [comment]
I don't believe I can.  I am going to see if I can repro it in a new project.  Thanks for the info.

**Comment by nycdotnet** [comment]
FYI: The issue does not occur in the latest version of legacy GitHub Desktop for Windows (Chocolate-Covered Yaks (3.3.4.0) 50415df).

**Comment by joshaber** [comment]
>in any file where the "before" version ends with a prohibit symbol, trying to do a partial commit on any set of lines above the block with the prohibit symbol causes a The requested changes conflict with one or more files in the repository. error. Attempting to do a partial commit including any set of lines below or including the "before" prohibit symbol causes a Corrupt patch at line X error.

I was able to reproduce the "corrupt patch" error. Thanks for the detailed description @nycdotnet!

I wasn't able to reproduce the "changes conflict" message, but I'm betting that was the same root cause.

**Comment by nycdotnet** [comment]
great to hear ty
