### ISSUE TITLE
Show in explorer stays in background

### ISSUE THREAD

**Issue by vankesteren** [desktop/desktop#2127]
### Description
Upon pressing `ctrl+shift+f` or _"show in explorer"_ from the menu or the context menu of changed files, file explorer opens properly but its window stays in the background. It would help workflow if focus goes to this window upon activation.

### Version

**GitHub Desktop version:** 0.6.2 

**OS version:** Microsoft Windows [Version 10.0.15063]

**Comment by tierninho** [comment]
@vankesteren The issue you described sounds similar to https://github.com/desktop/desktop/issues/1945. Let me know if your's is different. Thanks.

**Comment by vankesteren** [comment]
@tierninho thanks for the response! It seems similar, but since it's with explorer I don't think it's using `shell.openExternal`. The opening seems to be happening somewhere in [this file](https://github.com/desktop/desktop/blob/77c2146e4094ed50904ecb0c378f245a000e6686/app/src/ui/repositories-list/repository-list-item.tsx).

**Comment by j-f1** [comment]
I think the actual opening is done [here](https://github.com/desktop/desktop/blob/83cf2812f6064394b2a7924f3f8d7dab79633428/app/src/ui/app.tsx#L888-L892).

**Comment by vankesteren** [comment]
You're right of course :)

**Comment by joshaber** [comment]
I vaguely recall seeing an issue where this would happen if the function was called from the renderer. The fix was to call it from the main process instead.

**Comment by joshaber** [comment]
Ah, yeah, here it is: https://github.com/electron/electron/issues/4349. Sounds like a known issue but a simple enough fix.
