### ISSUE TITLE
Question: The Pull Request feature was removed from the new version

### ISSUE THREAD

**Issue by Rovel** [desktop/desktop#2128]
Question:

The Pull Request feature was removed from the new version?
If not where can I find it or do it?

Thanks

**Comment by tierninho** [comment]
@Rovel Does this help? https://help.github.com/desktop-beta/guides/contributing-to-projects/creating-a-pull-request/

**Comment by shiftkey** [comment]
@Rovel it hasn't been removed, it just didn't make the cut for the beta release.

We're tracking this in #295.

**Comment by Rovel** [comment]
Thanks!!!


Filipe Veloso
Diretor de Tecnologia e Operações
Tel. 55 11 2386-2001
Cel. 55 11 99195-3155
www.umanni.com.br
Responda a nossa pesquisa de satisfação:
https://goo.gl/forms/kYP9pK0mShvDgW7F2


2017-06-27 10:08 GMT-03:00 Brendan Forster <notifications@github.com>:
