### ISSUE TITLE
Refactor: Convert components to stateless functional components where possible

### ISSUE THREAD

**Issue by j-f1** [desktop/desktop#2131]
Currently all <sup>[*citation needed*]</sup> of the app’s components are ES6 classes. In many cases, this is unnecessary because the components are pure functions of their props. After going through #2124, I found the following candidates for refactoring:

Notes: 

- 🚫 = rejected, ✅ = done
- `.bind()` means that an event handler function could be replaced with a call to `.bind()` on the passed prop.
- <code>::*Foo*</code> means that the only the *`Foo`* component in the file is in this category.

<details><summary>🚫 <s><strong>Convert <code>this.*</code> to <code>this.state.*</code></strong></s> (12)</summary>

```
app/src/ui/app-menu/app-menu-bar-button.tsx
app/src/ui/app-menu/app-menu.tsx
app/src/ui/changes/sidebar.tsx
app/src/ui/diff/code-mirror-host.tsx
app/src/ui/diff/diff-line-gutter.tsx
app/src/ui/diff/index.tsx
app/src/ui/history/commit-list.tsx
app/src/ui/history/sidebar.tsx
app/src/ui/lib/button.tsx
app/src/ui/resizable/resizable.tsx
app/src/ui/tab-bar.tsx ::TabBar
app/src/ui/terms-and-conditions/terms-and-conditions.tsx
```
</details>

<details><summary><strong>Convert to a functional component</strong> (31)</summary>

```
app/src/ui/app-menu/menu-list-item.tsx
app/src/ui/blank-slate/blank-slate.tsx
app/src/ui/branches/branch.tsx
app/src/ui/changes/changed-file-details.tsx
app/src/ui/changes/no-changes.tsx
app/src/ui/changes/undo-commit.tsx
app/src/ui/cloning-repository.tsx
app/src/ui/delete-branch/index.tsx
app/src/ui/dialog/content.tsx
app/src/ui/dialog/error.tsx
app/src/ui/dialog/footer.tsx
app/src/ui/diff/deleted-image-diff.tsx
app/src/ui/diff/modified-image-diff.tsx
app/src/ui/diff/new-image-diff.tsx
app/src/ui/lib/avatar.tsx
app/src/ui/lib/button-group.tsx
app/src/ui/lib/errors.tsx
app/src/ui/lib/loading.tsx
app/src/ui/lib/path-label.tsx
app/src/ui/lib/rich-text.tsx
app/src/ui/lib/row.tsx
app/src/ui/lib/sign-in.ts (.bind())
app/src/ui/lib/text-area.tsx
app/src/ui/preferences/accounts.tsx (.bind())
app/src/ui/repository-settings/no-remote.tsx
app/src/ui/toolbar/toolbar.tsx
app/src/ui/ui-view.tsx
app/src/ui/updates/update-available.tsx
app/src/ui/welcome/configure-git.tsx (.bind())
app/src/ui/welcome/sign-in-enterprise.tsx (.bind())
app/src/ui/welcome/start.tsx (.bind())
```
</details>

<details><summary> ✅  <strong>Add an <code>&lt;Input /&gt;</code> component that calls onChange with the new value</strong>: #2133, #2134 (3)</summary>

```
app/src/ui/preferences/git.tsx
app/src/ui/repository-settings/git-ignore.tsx
app/src/ui/repository-settings/remote.tsx
```
</details>

<details><summary><strong>Add a helper method that calls <code>preventDefault()</code>, then the handler</strong> (3)</summary>

```
app/src/ui/discard-changes/index.tsx
app/src/ui/lib/call-to-action.tsx
app/src/ui/lib/form.tsx
```
</details>

<details><summary><strong>Add a helper method that calls the handler only if it is present</strong> (3)</summary>

```
app/src/ui/dialog/header.tsx
```
</details>

<details><summary><strong>Uses a lifecycle method</strong> (5)</summary>

`sCU` is `shouldComponentUpdate`, `cWM` is `componentWillMount`

```
app/src/ui/history/commit-list-item.tsx (sCU)
app/src/ui/lib/access-text.tsx (sCU)
app/src/ui/octicons/octicon.tsx (sCU)
app/src/ui/repositories-list/repository-list-item.tsx (sCU)
app/src/ui/welcome/sign-in-dot-com.tsx (cWM, .bind())
```
</details>

<details><summary><strong>Other: Uses complex event handlers</strong> (16)</summary>

```
app/src/ui/changes/changed-file.tsx
app/src/ui/changes/changes-list.tsx
app/src/ui/changes/index.tsx
app/src/ui/diff/binary-file.tsx
app/src/ui/history/file-list.tsx (.bind() ?)
app/src/ui/install-git/install.tsx
app/src/ui/lib/link-button.tsx
app/src/ui/lib/vertical-segmented-control/segmented-item.tsx (.bind())
app/src/ui/missing-repository.tsx (.bind())
app/src/ui/remove-repository/confirm-remove-repository.tsx
app/src/ui/repositories-list/index.tsx
app/src/ui/repository.tsx
app/src/ui/tab-bar.tsx ::TabBarItem
app/src/ui/toolbar/branch-dropdown.tsx
app/src/ui/toolbar/push-pull-button.tsx
app/src/ui/untrusted-certificate/untrusted-certificate.tsx
```
</details>

**Comment by shiftkey** [comment]
@j-f1 alright, this is a lot to unpack so I'll ask some probably obvious high-level questions before we go further:

> **Convert this.\* to this.state.\***

I'm not clear on this one - most of these components seem stateless, and the member properties inside are structured in a certain way so that the event handlers are bound correctly without needing the explicit `bind` (see #590 and #637  for back story) - and `tslint` should catch these exceptions.

Could you elaborate on what you had in mind here?

> **Convert to a functional component**

I had a look into this as part of #2124 and talked a bit with @joshaber about going down this path, and I think the use of `React.SFC` works better for simple components, versus the more complex ones we have that contain functions and event handlers.

I'd like to size up the tradeoffs by using a complex example before we go deeper on this.

> **Add an `<Input />` component that calls onChange with the new value**

We have abstractions for `TextBox` and `TextArea` here. Please elaborate on what you had in mind here.

> **Add a helper method that calls `preventDefault()`, then the handler**
> **Add a helper method that calls the handler only if it is present**

I'm not clear on what's involved here based on the files listed.

**Comment by j-f1** [comment]
> Convert `this.*` to `this.state.*`

These components appeared to use properties on the instance itself to store state, instead of the React `state` property. 

> Convert to a functional component

:+1:

> Add an `<Input />` component that calls onChange with the new value

This wasn’t a specific name. I noticed that those files only used the event object to get `e.target.value`, and then passed it to a handler in `props`. It might be clearer to cut out the middleman here.

> Add a helper method that calls `preventDefault()`, then the handler
> Add a helper method that calls the handler only if it is present

These components could become functional components if these helper methods were created and used, eliminating the need for inline event handlers that access the props.

**Comment by shiftkey** [comment]
> These components appeared to use properties on the instance itself to store state, instead of the React `state` property.

This is a conscious decision we've made to avoid internal state. I'm not clear on the value of re-introducing `state` here when React is clever enough to handle re-rendering when a prop updates, and we can push these props out to higher-level components.

> This wasn’t a specific name. I noticed that those files only used the event object to get `e.target.value`, and then passed it to a handler in props. It might be clearer to cut out the middleman here.

We have a simpler prop on `TextBox` named [`onValueChanged`](https://github.com/desktop/desktop/blob/master/app/src/ui/lib/text-box.tsx#L31-L41) that was designed for just this case. `TextArea` doesn't have this, but #2133 does some cleanup of these examples.

**Comment by j-f1** [comment]
I’ve hidden the `this.*` → `this.state.*` part. I’ll make a PR to add `onValueChanged` to `TextArea`, then apply it to the remaining file.

**Comment by j-f1** [comment]
Here’s an example of a good candidate for a functional component:
Currently (https://github.com/desktop/desktop/blob/d8ae429c2541ae0b2964c8dfe7dfd7396a9056ae/app/src/ui/lib/errors.tsx):
```ts
import * as React from 'react'
import * as classNames from 'classnames'

interface IErrorsProps {
  /** The class name for the internal element. */
  readonly className?: string

  /** The children to be displayed as an error message. */
  readonly children?: ReadonlyArray<JSX.Element>
}

/** An Errors element with app-standard styles. */
export class Errors extends React.Component<IErrorsProps, void> {
  public render() {
    const className = classNames('errors-component', this.props.className)
    return (
      <div className={className}>
        {this.props.children}
      </div>
    )
  }
}
```

🔜 (currently, TSLint warns the props are unused: Microsoft/tslint-microsoft-contrib#339):

```ts

import * as React from 'react'
import * as classNames from 'classnames'

interface IErrorsProps {
  /** The class name for the internal element. */
  readonly className?: string

  /** The children to be displayed as an error message. */
  readonly children?: ReadonlyArray<JSX.Element>
}

/** An Errors element with app-standard styles. */
const Errors: React.SFC<IErrorsProps> = props => {
  const className = classNames('errors-component', props.className)
  return (
    <div className={className}>
      {props.children}
    </div>
  )
}

export { Errors }
```
or, if we’re lucky:
```ts
import * as React from 'react'
import * as classNames from 'classnames'

interface IErrorsProps {
  /** The class name for the internal element. */
  readonly className?: string

  /** The children to be displayed as an error message. */
  readonly children?: ReadonlyArray<JSX.Element>
}

/** An Errors element with app-standard styles. */
export function Errors (props: IErrorsProps) {
  const className = classNames('errors-component', props.className)
  return (
    <div className={className}>
      {props.children}
    </div>
  )
}
```

**Comment by shiftkey** [comment]
@j-f1 yeah, we'd need `tslint` to detect these before we can think about porting any of the components - [the rule](https://github.com/Microsoft/tslint-microsoft-contrib/blob/master/src/reactUnusedPropsAndStateRule.ts) only checks `React.Component` classes in a source file.

**Comment by joshaber** [comment]
Given how big this refactor potentially is, I think we need some justification before we'd accept it. What problem does it solve for us?

**Comment by j-f1** [comment]
@shiftley I found [this article](https://hackernoon.com/react-stateless-functional-components-nine-wins-you-might-have-overlooked-997b0d933dbc) which lists several benefits of functional components, and the upcoming Fiber backend for React may include some more performance goodies.

**Comment by joshaber** [comment]
I agree that functional components are nice, and I even prefer them conceptually, but that article didn't convince me that it's more than a matter of taste.

If we solve the `tslint` rule problem that @shiftkey cited above, I'd be into using functional components going forward. But I'm not convinced it's worth the effort to go back and update all our existing components.

**Comment by j-f1** [comment]
I’m willing to put in the effort.

**Comment by joshaber** [comment]
I think a good first step would be to address the `tslint` rule problem so that new development can use functional components going forward.

**Comment by j-f1** [comment]
It looks like there’s [an ESLint plugin](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unused-prop-types.md) that is better at this than the TSLint plugin, and there appears to be a [`typescript-eslint-parser`](https://www.npmjs.com/package/typescript-eslint-parser) package. Maybe we could begin migrating over to ESLint — it has a larger community, and we can remove rules from TSLint when they become stable in ESLint. There’s [an ESLint TypeScript plugin](https://github.com/nzakas/eslint-plugin-typescript) that has a few rules already, and I’m sure more will be coming soon.

**Comment by j-f1** [comment]
@joshaber How does that sound?

**Comment by joshaber** [comment]
Sorry for the delay, I was on vacation for a bit there 🏖 🎉 

That's an interesting idea. Certainly it'd be nice to move to something more widely used like ESLint. Off the top of my head, a couple thoughts:

1. Would we have to rewrite rules like our [button order rule](https://github.com/desktop/desktop/blob/2c136541ede4341a1b0abccbac4daa94bc12fb8c/tslint-rules/buttonGroupOrderRule.ts)?
1. Now that we're using Prettier, we don't care about style linting.
1. At a certain point, the cure might be worse than the ailment.

**Comment by j-f1** [comment]
> Would we have to rewrite rules like our button order rule?

Probably, but I thought we could run both linters until we have all of the rules moved over.

**Comment by joshaber** [comment]
I'm gonna close this. It'd be a lot of code churn without clear benefit.
