### ISSUE TITLE
Branch > Delete is confusing

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#2136]
1. Go to Branch > Delete.
1. Yes I want to delete.
1. "Nooooooooooo not the remote branch too" 😭 

We should:

1. Steal Windows Classic's design.

**Comment by j-f1** [comment]
Maybe add a checkbox?

> Delete branch `foo`?
> 
> ⚠️ This cannot be undone!
> - [ ] Delete this branch on GitHub

**Comment by donokuda** [comment]
For reference, this is what Windows looks like:

![image](https://user-images.githubusercontent.com/1174461/27885819-41411c60-618e-11e7-867d-7441192c752f.png)
