### ISSUE TITLE
Want Command+T to open terminal back :(

### ISSUE THREAD

**Issue by silver6wings** [desktop/desktop#2138]
Found it removed in the new version TAT

**Comment by joshaber** [comment]
@silver6wings are you asking for the functionality back or the specific shortcut?

**Comment by hariesnurikhwan** [comment]
![screen shot 2017-07-03 at 5 50 00 pm](https://user-images.githubusercontent.com/10152692/27787642-0ea1bb42-6018-11e7-865f-aea7610708e4.png)

Really miss the ability to Open in Terminal using shortcut.

**Comment by niik** [comment]
I think this is a reasonable thing to add, especially if it was a thing in the previous mac app. On Windows we had the [`quake key`, i.e. `~` open the terminal](http://haacked.com/archive/2015/10/29/git-shell/), a feature which I quite liked although I'm not married to that exact shortcut as it doesn't work when you're typing in a text field.

![image](https://user-images.githubusercontent.com/634063/27842142-69a8121c-6107-11e7-9acb-d127d7e66db4.png)

The `CmdOrCtrl+T` shortcut is already taken by the show-repository menu item and I do think that makes sense and matches what, for example, slack uses that shortcut for. It also doesn't work as well on Windows where we don't use the `Terminal` terminology

![image](https://user-images.githubusercontent.com/634063/27842182-dcde4210-6107-11e7-9e1c-4efa124d0438.png)

Either we come up with a new shortcut that works on both platforms, or we use a different one depending on platform (`Ctrl+Shift+C` and `Ctrl+Shift+T` perhaps). I'm open to suggestions here and once we've settled on a shortcut we can open this up for contributions.

**Comment by silver6wings** [comment]
Thank you for keep opening it.~
I'm using Github Desktop for mac and didn't see any ways to open terminal using shortcut,
and found same function shortcut Ctrl + Command + T in SourceTree, and it didn't used in Github Desktop.

**Comment by notxcain** [comment]
Please bind it back to `Cmd + T` It's essential, which I can not say about repository list.

**Comment by Jupakabra** [comment]
Yes, really miss `~` on windows, as I'm heavy command line user and only using the client to preview the changes.

**Comment by iAmWillShepherd** [comment]
Since `Cmd + T` is currently bound to the *Show Repository Menu*, I'm going to go ahead and bind it to `control + ~`.

**Comment by say25** [comment]
Hey as a Mac GitHub Desktop user I find it frustrating that literally the only shortcut that is not Command something is this one. Can we make the terminal/console shortcut CmdOrCtrl+` vs. Ctrl+`? as you can tell it kinda goes against the existing user behavior for shortcuts....

**Comment by j-f1** [comment]
`` Cmd+` `` is used on macOS to toggle between windows in an app.

**Comment by Kurira** [comment]
Yes, should have been just ` if possible.

**Comment by iAmWillShepherd** [comment]
@say25 

> Can we make the terminal/console shortcut CmdOrCtrl+` vs. Ctrl+`? 

Can you pull that into an issue? I'll take care of it today. Or, if you are willing, submit a PR with the change and I'll approve and merge it.

@Kurira 

> Yes, should have been just ` if possible.

We currently do not execute shortcuts without a modifier key, will be going with @say25's suggestion.

@j-f1

>  Cmd+` is used on macOS to toggle between windows in an app.

Is this by convention or is this an OS level shortcut? I just tried it out in Chrome and that command does nothing. In VS Code, that command opens up the terminal.

**Comment by j-f1** [comment]
@iAmWillShepherd

> Is this by convention or is this an OS level shortcut?

It’s a fairly widely-respected convention, and it appears to be OS-level:

<img width="407" alt="screen shot 2017-08-03 at 13 29 51" src="https://user-images.githubusercontent.com/25517624/28934698-e3610758-784f-11e7-9ec3-51f8d606d16a.png">  
<sup>(System Preferences → Keyboard → Shortcuts → Keyboard)</sup>

**Comment by iAmWillShepherd** [comment]
Oh, I thought you were saying ```control + ` ```  changed focus. Do you have any suggestions for a better command than ```control + ` ```  that isn't already mapped? I like ```control + ` ``` as it's something that won't be easily confused and take a shortcut for a more used feature.

**Comment by j-f1** [comment]
There is a precedent for shortcuts using `control` on macOS. For example, ⌃⇥ and ⌃⇧⇥ are used in several apps to switch between tabs, and ⌃T transposes two characters in a text box.

**Comment by say25** [comment]
From what @j-f1 is saying I believe you are correct and overriding a macOS default feels wrong. I also feel that `CmdOrCtrl+T` is weird for repo list. But the only ctrl shortcut being a reasonably important one is also weird
