### ISSUE TITLE
Show a "Please Update" notification in the Classic apps

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#2146]
_(I'm tracking this here even though the work will happen elsewhere, so it doesn't fall through the cracks.)_

We should show a notification in the Classic apps after we release 1.0, pointing users to download the new app.

**Comment by joshaber** [comment]
Moving this to 1.0.x as we'll want to do it after 1.0 is out and stable.

**Comment by joshaber** [comment]
@niik and I talked about this earlier this week and decided that we can make a more compelling case for upgrading post-1.1. So I'm moving this to 1.1.x.

**Comment by nerdneha** [comment]
Closing this as the conversation is now here: https://github.com/desktop/desktop/issues/4285
