### ISSUE TITLE
Fix the CLI to work with dev builds

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#2150]
See https://github.com/desktop/desktop/pull/1925#discussion_r124375222.

We currently hardcode "GitHub Desktop.exe", but dev builds will be called "GitHub Desktop-dev.exe". We should support both.

**Comment by iAmWillShepherd** [comment]
Closing, per conversation with @joshaber 
>... not sure this is a real issue since dev builds can’t be launched standalone
