### ISSUE TITLE
tracking work in progress and external contributors

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#2154]
From https://github.com/desktop/desktop/pull/2153#issuecomment-312044350

> When I’m looking through the issue list, it’s hard to tell which issues are actually up-for-grabs, and which issues already have a PR attached. 

We've been using the assignee to indicate when someone is working on an issue. This works for people who are members of the team (they can add and drop themselves off as needed), but not for contributors who are outside the Desktop org.

I can see two ways out of this:

 - introduce a label. This requires more manual work to ensure things are in sync (when a PR is opened, cross-reference any issues mentioned), but the information is clearer and sits alongside the existing labels. This could be automated using a bot, but I'm not sure if there's any existing examples out there.
 - introduce a team of external contributors to the org, who can then be assigned in the same way as existing org members. This needs some more research to ensure the workflows are accurate, but may also not be clear to people exploring the repository. 

I'm leaning towards the first one, but I'll let this sit for a bit to gather feedback.

**Comment by bopoh13** [comment]
If I understood correctly, then there is a [working tool](https://mapbox.github.io/top-issues/#!desktop/desktop).

**Comment by shiftkey** [comment]
This has sat for a while, but I think we've been fine with doing things manually without introducing any more Process™.
