### ISSUE TITLE
Is the "Ignored Files" textarea too small?

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#2160]
_Split out from https://github.com/desktop/desktop/issues/2155_

<img width="508" alt="screen shot 2017-06-29 at 3 20 53 pm" src="https://user-images.githubusercontent.com/13760/27713038-94161954-5cde-11e7-9fc7-6b0117b220e3.png">

**Comment by iAmWillShepherd** [comment]
It's be nice if we could expose a drop down that allows users to start from a [template](https://github.com/github/gitignore). I'm thinking having that description there is not necessary; putting the description behind a tooltip should allow people who want/need to know what _gitignore_ file is to see it while allowing us to use that space for showing the file's contents.

**Comment by j-f1** [comment]
You could also add a `?` icon with something like the Bootstrap [popover component](http://getbootstrap.com/javascript/#popovers) to make the description easier to read and interact with, if necessary.

**Comment by iAmWillShepherd** [comment]
> You could also add a ? icon with something like the Bootstrap popover component to make the description easier to read and interact with, if necessary.

That's what I was thinking. Of course, I don't know the names of icons so I didn't bother mentioning it.

**Comment by j-f1** [comment]
[`octicon-question`](https://octicons.github.com/icon/question/)

<img width="27" alt="octicon-question" src="https://user-images.githubusercontent.com/25517624/27769124-02214270-5ef1-11e7-90be-8a99db3c09d2.png">

**Comment by donokuda** [comment]
> It's be nice if we could expose a drop down that allows users to start from a template. I'm thinking having that description there is not necessary; putting the description behind a tooltip should allow people who want/need to know what a gitignore file is to see it while allowing us to use that space for showing the file's contents.

I've opened https://github.com/desktop/desktop/issues/2197 to discuss this.

In regards to the textarea being small, I'm curious to what problems users have ran into as a result of not being able resize the textfield (eg, "It's difficult to understand which files are ignored," "It's difficult to add more filetypes," etc.) If we understand this more, then we can figure out whether allowing the text area will solve the problem.

**Comment by donokuda** [comment]
I'm closing out this issue in favor of https://github.com/desktop/desktop/issues/2198
