### ISSUE TITLE
Git LFS settings

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#2161]
The Mac Classic app:

<img width="543" alt="screen shot 2017-06-29 at 3 22 42 pm" src="https://user-images.githubusercontent.com/13760/27713097-d588046a-5cde-11e7-95d0-b3996a373ef9.png">

**Comment by shiftkey** [comment]
Isn't this a dupe of #69?

**Comment by joshaber** [comment]
Totally is 👍
