### ISSUE TITLE
does't support load avatar from gravatar?

### ISSUE THREAD

**Issue by ColinZeb** [desktop/desktop#2164]
os windows 10   
version 0.6.2
ip china

**Comment by tierninho** [comment]
@ColinZeb please fill out the template so we have more details. Thanks!

**Comment by joshaber** [comment]
It is true that we do not load avatars from Gravatar. We only load avatars based on the GitHub account.

**Comment by ColinZeb** [comment]
Will it be supported later?
The previous classic version is supported
@joshaber

**Comment by joshaber** [comment]
It's not on our [roadmap currently](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).
