### ISSUE TITLE
npm ERR! electron-chromedriver@1.7.1 install: `node ./download-chromedriver.js`

### ISSUE THREAD

**Issue by renyaoxiang** [desktop/desktop#2170]
While I use the command ```npm install ``` , it maks error as following. How could I make it no error.
... 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\software\\nodejs\\node.exe" "D:\\software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! electron-chromedriver@1.7.1 install: `node ./download-chromedriver.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-chromedriver@1.7.1 install script 'node ./download-chromedriver.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./download-chromedriver.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-07-01T09_54_15_005Z-debug.log

**Comment by joshaber** [comment]
Could you also provide the `C:\Users\Administrator\AppData\Roaming\npm-cache_logs\2017-07-01T09_54_15_005Z-debug.log` file?

**Comment by renyaoxiang** [comment]
oh, I tried to run 'npm install' many times, different kinds of errors occored.
The key words of errors are keytar, chromedriver, node-gyp...  
I have spend several days to begin with desktop, but finally failed.
Maybe I really need to a guide of video or more detail info to start with,
Take me out of the mud of errors, please.

**Comment by joshaber** [comment]
Let's consolidate this discussion to https://github.com/desktop/desktop/issues/2169.
