### ISSUE TITLE
How to merge remote?

### ISSUE THREAD

**Issue by ofek** [desktop/desktop#2172]
Say:

1. I fork a repo
2. I clone my fork locally
3. Time passes and original master repo becomes n commits ahead of my fork (assuming local is in sync with my origin)

How does one merge the changes so I am up-to-date?

**Comment by niik** [comment]
Hi @ofek,

Staying up to date in a fork is an issue we're looking to tackle as part of our [1.1 milestone in our roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md). The section titled 'Relationship to X` is what we're using to describe the feature you're looking for. We currently don't have a good way to do this in the beta client right now and need to refer you to the terminal to stay up to date with the parent repository.
