### ISSUE TITLE
Exit installer if internet connection cannot be extablished

### ISSUE THREAD

**Issue by RishiTheivendran** [desktop/desktop#2179]
### Description

The latest GitHubDesktopSetup.exe (0.6.2) fails to exit if launched in a corporate network with an internet proxy. Looking at TaskManager, I can see the process just keeps spawning new child processes & never exits. Please update the installer so it informs the user & exits if there is no internet connection.

### Version
**GitHub Desktop version:** 0.6.2
**OS version:** Microsoft Windows [Version 6.3.9600]

### Steps to Reproduce

1. Download & launch GitHubDesktopSetup.exe

**Comment by niik** [comment]
Hi @RishiTheivendran, this sounds like an issue with [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows) the installation and update framework that Electron uses (possibly https://github.com/Squirrel/Squirrel.Windows/issues/537).

Could you tell me a little more about the type of proxy your company uses? I.e. is it set up as the default system proxy (You should be able to see it from Internet Explorer's connection settings)?

**Comment by RishiTheivendran** [comment]
@niik AFAIK it's not a system wide configuration in the OS, so far each tool needs to be configured separately.

For the browser it's done through Internet Options & it's set to "Automatically detect settings".
For Git, it's done through command line using

    git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080

Recently I created #https://github.com/desktop/desktop/issues/2054 to address the same issue in GitHubDesktop, but when I was asked to test 0.6.2 I could not install it. 
I eventually installed 0.6.2 by disconnecting from the corporate network & using a direct internet connection.

**Comment by joshaber** [comment]
@RishiTheivendran If you're still experiencing this issue, could you get grab the contents of the SquirrelSetup.log and paste them in here? You should be able to find it at `%LocalAppData%\GitHubDesktop\SquirrelSetup.log`.

**Comment by RishiTheivendran** [comment]
@joshaber I eventually installed 0.6.2 by disconnecting from the corporate network & using a direct internet connection but find attached the logs from the previous attempt while behind the firewall.
[SquirrelSetup.zip](https://github.com/desktop/desktop/files/1153775/SquirrelSetup.zip)

**Comment by joshaber** [comment]
Thanks @RishiTheivendran ✨ Unfortunately this does appear to be a Squirrel.Windows bug. Ideally it would pick up your proxy settings and do the needful, but it sounds like there's a bug preventing that.

Since this isn't a bug in GitHub Desktop proper, I'm gonna close this.
