### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by ekirkco** [desktop/desktop#2180]
Authentication Failed

### Description

I drag/dropped a couple repositories checked out via Tortoise Git.  When I try to fetch it says it cannot authenticate or that my account doesn't have access.  Here is the actual message:

_Authentication failed. You may not have permission to access the repository. Open options and verify that you're signed in with an account that has permission to access this repository._

### Version

**GitHub Desktop version:** 0.6.2

The operating system you are running on may also help with reproducing the
issue:

**OS version:** Windows 10.0.15063

#### Additional Information

I had to configure a private/public keys for other clients.  Not sure if this is necessary, and I don't see any option anywhere for it.

**Comment by niik** [comment]
Hi @ekirkco, can you tell us a little bit more about these repositories, are they GitHub.com repositories or GitHub Enterprise repositories and are you using ssh or https to connect to them?

You can determine the latter by opening the repository settings dialog in the `Repository` menu and check if the origin remote starts with `https` or `git@github.com`.

**Comment by johneas10** [comment]
Same issue as @ekirkco 

A good example would be this repository. I can't fetch it anymore.
I have all my repositories added via ssh, and they're all from github.com.

I don't see a pattern yet as some of the repositories I have saved seem to be working fine. I will update if I come up with anything more.

GitHub Desktop version: 0.6.2
OS version: macOS Sierra 10.12.5

**Comment by johneas10** [comment]
I think I've narrowed it down to VPN usage. Everything runs okay when the VPN is switched off, but switching it back on causes the errors to return.

I'm a little confused as to why a few repositories seem to be unaffected by this though?

@ekirkco are you using a VPN?

**Comment by joshaber** [comment]
Is it always repositories with SSH remotes that fail authentication?

**Comment by ekirkco** [comment]
To be honest, I forgot about this thread and now I've forgotten exactly what I was doing.  I know I did copy/past a checked out repository and guessing that's what I was meaning.  It very well could have been VPN related, but it seems to be working now with a VPN running.(maybe it was a different VPN client before though)  
To be honest, I don't know if I'm ssh or https.  I just have a URL starting with "git@github.com:"
I don't *think* it's enterprise.  But, I'm also not sure how to see that.
Sorry, just a bunch of worthless answers.  Can probably chalk it up to VPN as the most likely cause.  I'll reply if I run into it again though.

**Comment by joshaber** [comment]
Thanks for following up @ekirkco!

>To be honest, I don't know if I'm ssh or https. I just have a URL starting with "git@github.com:"

FWIW, that's an SSH URL 👍

**Comment by jamez14** [comment]
Experienced this issue with a Bitbucket SSH URL, changing to a `https` URL in the "Repository Settings" fixed the problem.

**Comment by Carlosferrerhernandez** [comment]
He realizado un git push directamente de la consola y a subido correctamente el commit, sin hacer ningún cambio en configuraciones

**Comment by DivyansMahansaria** [comment]
I got the same error message - "Authentication failed. You may not have permission to access the repository. Open options and verify that you're signed in with an account that has permission to access this repository." but in my case the issue was GitHub Desktop -> Repository -> Repository Settings -> Remote Repository URL was pointing to master repository from where I had forked out a code version.  Changing it to correct URL solved the issue.

**Comment by buddike1112** [comment]
I have successfully solved this issue by adding SSH public key to my security settings. I have generated public key using "Git Bash" and Created entry in GitHub Profile -> Settings -> "SSH and GPG Keys" -> "New SSH Keys". I'm using VS 2017 community edition to push and commit my changes. All started to work.

**Comment by vinaysk95** [comment]
Hi, I am facing this issue right now. I am using Git Version 2.19.1 and GitHub Desktop version 1.4.3. Windows OS is 10. Should I open a new issue or can I continue in the same?

**Comment by ramtvg** [comment]
Github desktop works with SSH for enterprise. But private key must be located under /.ssh and private key name must be id_rsa without any password protection

**Comment by shizukanaskytree** [comment]
Sometimes, you only need to sign out from the preference and then login again. 
This is strange but it works for me.

**Comment by CharlesStover** [comment]
I've got this fixed on an Enterprise account by going to `Repository -> Repository settings...` and changing `git@enterprise_domain:Org/Repo.git` to `https://enterprise_domain/Org/Repo.git`.

**Comment by allansendagi** [comment]
> Sometimes, you only need to sign out from the preference and then login again.
> This is strange but it works for me. 

This does work! Thanks

**Comment by gleija** [comment]
> Experienced this issue with a Bitbucket SSH URL, changing to a `https` URL in the "Repository Settings" fixed the problem.

This fixed my problem too.

**Comment by andreypikalov13** [comment]
when I had a problem, I crossed over to my Git Desktop account and the error stopped
