### ISSUE TITLE
Staging line hunks has less visual feedback than old GitHub Desktop

### ISSUE THREAD

**Issue by jamesgecko** [desktop/desktop#2181]
### Description

This is related to (but distinct from) #1688

In the old non-Electron version of GitHub Desktop, there were four visual states the chunk margin could have.

**Selected**
<img width="134" alt="screen shot 2017-07-03 at 2 26 09 pm" src="https://user-images.githubusercontent.com/44252/27804280-06a287ee-5ffc-11e7-9840-05cd349767d9.png">

(User moves mouse over the margin)

**Selected with mouse hover**
<img width="126" alt="screen shot 2017-07-03 at 2 26 19 pm" src="https://user-images.githubusercontent.com/44252/27804286-0ce7e6e4-5ffc-11e7-8c99-8c3fe4dcadf8.png">

(User clicks the mouse)

**Unselected with mouse hover**
<img width="129" alt="screen shot 2017-07-03 at 2 26 28 pm" src="https://user-images.githubusercontent.com/44252/27804303-320d56a2-5ffc-11e7-9db2-7f43e431e69b.png">

(User moves the mouse off the margin)

**Unselected**
<img width="130" alt="screen shot 2017-07-03 at 2 26 35 pm" src="https://user-images.githubusercontent.com/44252/27804310-3dc06f70-5ffc-11e7-91fa-717d527086d7.png">

* * *

GitHub Desktop Beta only has three states, even though the way you stage hunks hasn't changed.

**Selected**
<img width="185" alt="screen shot 2017-07-03 at 2 26 56 pm" src="https://user-images.githubusercontent.com/44252/27804351-8274aab4-5ffc-11e7-91ca-e6a0ab03ee3b.png">

(User moves mouse over the margin)

**Mouse hover** (actually selected)
<img width="184" alt="screen shot 2017-07-03 at 2 27 07 pm" src="https://user-images.githubusercontent.com/44252/27804355-86a35d7e-5ffc-11e7-8319-7ca3da8c1049.png">

(User clicks the mouse)

**Mouse hover** (actually unselected) (Wait, did that click do anything? Nothing changed!)
<img width="184" alt="screen shot 2017-07-03 at 2 27 07 pm" src="https://user-images.githubusercontent.com/44252/27804355-86a35d7e-5ffc-11e7-8319-7ca3da8c1049.png">

(User moves the mouse off the margin)

**Unselected**
<img width="180" alt="screen shot 2017-07-03 at 2 27 16 pm" src="https://user-images.githubusercontent.com/44252/27804365-8fee7cba-5ffc-11e7-84c5-3656f4f9c504.png">

There's no visual feedback when you click the mouse. It feels bad.

### Version

**GitHub Desktop version:** 0.6.2
**OS version:** macOS 10.12.5

**Comment by niik** [comment]
Nice catch @jamesgecko, I should have caught that, I spent ages tweaking the colors in the old app.

I agree, we should have a distinct hover state for selected/deselected. I'm putting this in the design queue to be discussed but IMO it's just a matter of picking the right contrast here before we can open it up for contributions

**Comment by niik** [comment]
We discussed this in the weekly design review and both agree that we should add the fourth state. We should follow the same convention of contrast that we used in the previous apps. We'll accept PRs for this

**Comment by j-f1** [comment]
Do you have the color codes from the native app? my color picker tells me `#5A93E0` for selected, `#116CD5` for selected + hover, and `#97B9E9` for unselected + hover.
