### ISSUE TITLE
Default branch doesn't update when changed on Github repository

### ISSUE THREAD

**Issue by jpike88** [desktop/desktop#2182]
Please summarize the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

I change the default branch on my GitHub repo, and Github desktop doesn't realise it and still thinks master is the default branch

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** 0.6.2

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** OSX Sierra

### Steps to Reproduce

1. update default branch
2. use GitHub desktop
3. observe it not realising it

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behavior:** default branch updates properly
**Actual behavior:** it doesn't

**Reproduces how often:** every time

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

If you are dealing with a performance issue or regression, attaching a
[Timeline profile](https://github.com/desktop/desktop/blob/master/docs/contributing/timeline-profile.md)
of the task will help the developers understand the runtime behavior of the
application on your machine.

**Comment by niik** [comment]
Hi @jpike88, we're tracking this bug in #1489, please subscribe to that to follow along, thanks!

**Comment by Jaffa-Cakes** [comment]
I'm still experiencing this issue.

**Comment by itl-projects** [comment]
Same Issue experienced
