### ISSUE TITLE
Filter on Repo Name should not clear after navigating to a repo

### ISSUE THREAD

**Issue by sorab2142** [desktop/desktop#2186]
Since there is no grouping feature for repos of any sort (by directory, or virtual groups) it is common to use the filter option if the repos have a common part in the name. The issue is that this filter is cleared once you navigate to a particular repo. It would be better to leave it filled.

**Comment by niik** [comment]
I can see both sides of this. The way I typically use the filter is I hit `CTRL+T`, type a repo and hit enter. It would be annoying if I had to manually clear it out for the next round. That said I think there are ways to mitigate that such pre-selecting the text. I'm gonna toss this in the design backlog for discussion but it's not currently in scope of our [roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md) so it might be some time before we get to it.

I'd very much welcome more thoughts and feedback from the community and @desktop/core here as well

**Comment by j-f1** [comment]
Would a PR to select the text when opening the dropdown work for you @niik?

**Comment by niik** [comment]
> Would a PR to select the text when opening the dropdown work for you @niik?

I'm hesitant to make that call without having given it some more thought and talked it through with @donokuda at a design sync-up. As it stands right now I don't consider this to be a bug but rather, as @tierninho categorized it, a possible enhancement.

I definitely welcome more feedback and use-cases in this issue though.

**Comment by donokuda** [comment]
I'd rather not modify the behavior of a text field and instead think about how we can improve navigating repositories in general.

**Comment by niik** [comment]
We've talked through this in our design review and while we're certainly going to come back to improving repository navigation we'd like to take a step back and look at the the entire scope of the problem rather than focusing on solution this early on.

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.
