### ISSUE TITLE
[Error] InitializeSecurityContext failed: Unknown error (0x80092013) 

### ISSUE THREAD

**Issue by abolfazl-ziaratban** [desktop/desktop#2187]
hi
i can't clone repository in desktop.

desktop error
```
Cloning into '...\abolfazl-ziaratban\azDoublyLinkedList'...
fatal: unable to access 'https://github.com/abolfazl-ziaratban/azDoublyLinkedList.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.
```

**Comment by niik** [comment]
Hi @abolfazl-ziaratban, this looks like an error originating from the Windows secure channel system (the framework that deals with TLS handshakes). Could you tell me a little more about your environment? What version of Windows are you running, is this a corporate, university or home network?

**Comment by abolfazl-ziaratban** [comment]
hi @niik .
i disabled my antivirus and reset rule for desktop github , problem solved.
thanks for support.

**Comment by niik** [comment]
Thank you for letting us know @abolfazl-ziaratban, hopefully this can be of help to others encountering the same issue.

**Comment by kunalrsinha** [comment]
HI 
I also get the same issue in cloning the repository.
I have Window 7 Home Basic 64 bit 
Desktop github file version is 1.0.11.0
and product version is 1.0.11.
Please help me in resolving my problem.
Thank you

**Comment by shiftkey** [comment]
@kunalrsinha 

As a workaround, you can revert to the classic OpenSSL behaviour by opening the repository in a shell and running these two commands. 

```
$ git config --global http.sslBackend "openssl"
$ git config --global http.sslCAInfo [path to .pem file]
```

[The PEM file](https://curl.haxx.se/docs/caextract.html) distributed by the cURL team should do the trick.

**Comment by es3** [comment]
Copy cert path from configuration git

> git config http.sslCAInfo
    Return Example: "C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt"

Add to global configuration

> git config --global http.sslBackend "openssl"
> git config --global http.sslCAInfo "C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt"

**Comment by mtkumar82** [comment]
Hi, I am facing same issue. I have window 7, and I am using Phpstorm as php editor for push, Pull my code on git, After implementing the above changes my error message changed with 

Push failed: Failed with error: fatal: unable to access '.git': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version.

May I know please what is this error and How I can resolve this? It was working fine upto yesterday, But when I start work today, I get this issue. Please help.

**Comment by shiftkey** [comment]
@mtkumar82 I think you've been caught out by GitHub disabling TLS 1.0 and 1.1 yesterday. Please ensure you're running an up-to-date version of [Git for Windows](https://gitforwindows.org/).

**Comment by mtkumar82** [comment]
I installed the latest version of git yesterday, But still getting same error.
Push failed: Failed with error: fatal: unable to access error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

**Comment by shiftkey** [comment]
@mtkumar82 please open an issue to the [Git for Windows](https://github.com/git-for-windows/git) project

**Comment by kstatefan40** [comment]
@mtkumar82 @shiftkey I'm experiencing the same issue here - started getting "SSL certificate problem: self signed certificate in certificate chain" last Monday in an enterprise environment. I've tried every solution I can find (including those listed above.) It works fine off the enterprise network at home. I'm using SourceTree.

Was there an issue opened on this?

**Comment by skbehera2008** [comment]
Hi I am also experiencing same issues "nitializeSecurityContext failed: SEC_E_LOGON_DENIED (0x8009030C) - The logon attempt failed"

I am using windows10 & GIT-Windows-1.1.0 version

**Comment by Alexandr59** [comment]
РЕШИЛ ПРОБЛЕМУ ПУТЕМ ЗАПУСКА ПРОГРАММЫ ОТ **ИМЕНИ АДМИНИСТРАТОРА**

**Comment by AndyGee** [comment]
Check your "C:\Users\<user>.gitconfig" for proxy configuration, or anything else that might be providing wrong credentials - Had the same issue, and it turned out to be the corporate proxy settings.

**Comment by upadrian** [comment]
> 
> 
> Copy cert path from configuration git
> 
> > git config http.sslCAInfo
> > Return Example: "C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt"
> 
> Add to global configuration
> 
> > git config --global http.sslBackend "openssl"
> > git config --global http.sslCAInfo "C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt"

this works for me

**Comment by BOYMMM** [comment]
> Copy cert path from configuration git
> 
> > git config http.sslCAInfo
> > Return Example: "C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt"
> 
> Add to global configuration
> 
> > git config --global http.sslBackend "openssl"
> > git config --global http.sslCAInfo "C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt"

this works for me， Thanks

**Comment by MioVisman** [comment]
Running as administrator solves the problem.
Win7 x64

**Comment by alberico-lima** [comment]
if you're behind a corporate proxy update your credentials using git config, it worked for me.

**Comment by kinglinux12** [comment]
Error: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

this the error i am getting while running vagrant up. Any suggestion? Thanks

**Comment by HyunmokMoonAtBagelcode** [comment]
After SSH key setting, I cloned from "SSH" url not "HTTPS". I got success.
