### ISSUE TITLE
Cannot select specific text in diff view on a multiple line

### ISSUE THREAD

**Issue by stephenbe** [desktop/desktop#2189]
### Description

I cannot select the second line of text in the diff view : 
![github for windows](https://user-images.githubusercontent.com/3018441/27867995-58babc18-6169-11e7-8fe1-f8c906f459f9.gif)

### Version

**GitHub Desktop version:** 0.6.2

**OS version:** Microsoft Windows [version 6.1.7601]

### Steps to Reproduce

**Expected behavior:** I want to select the second line (see gif)

**Actual behavior:** Selects the first line

**Reproduces how often:** 100%

**Comment by niik** [comment]
Hi @stephenbe, we're tracking this bug in #1551, please subscribe to that issue to follow along
