### ISSUE TITLE
Improving ignoring/ignored files

### ISSUE THREAD

**Issue by donokuda** [desktop/desktop#2198]
Had a good chat with @IAmWillShepherd on how we can improve ignoring files in GitHub Desktop. I'm opening up this issue for facilitating discussion and we can break up action items into their own issues when we move forward.

Potential opportunities:

- [Making it easy to get add a gitignore via a template](https://github.com/desktop/desktop/issues/2197)
- [Ignoring directories](https://github.com/desktop/desktop/issues/1203)
- Show which files have been ignored
- Unignore directories and files
- Unignore directories and files without modifying the gitignore (something like `git update-index --assume-unchanged`) #1571

**Comment by joshaber** [comment]
I'm gonna close this since it's beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).
