### ISSUE TITLE
posh-git implementation / changing default git shell

### ISSUE THREAD

**Issue by thebigsmileXD** [desktop/desktop#2199]
Please summarize the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

Hello. Just installed this version of GitHub Desktop (i used the non-beta version before), and really liking it.
I saw that there's "Open command prompt". I remember the old GitHub desktop having "Open in Git Shell" and "Open in PowerShell", using posh-git.
I've read through the issues, but haven't found any way to make the "Open command prompt" use posh instead of cmd

To clarify, i am operating on Windows Server 2012 R2

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** 0.6.2

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** Windows Server 2012 R2, Microsoft Windows [Version 6.3.9600]

### Steps to Reproduce

1. Click on "Repository" in the menu
2. Click "Open Command prompt"

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behavior:** Some settings to open posh-git

**Actual behavior:** cmd.exe opens

**Reproduces how often:** 100%

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log

[2017-07-07.desktop.production.log.txt](https://github.com/desktop/desktop/files/1130881/2017-07-07.desktop.production.log.txt)
`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

If you are dealing with a performance issue or regression, attaching a
[Timeline profile](https://github.com/desktop/desktop/blob/master/docs/contributing/timeline-profile.md)
of the task will help the developers understand the runtime behavior of the
application on your machine.

**Comment by niik** [comment]
Hi @thebigsmileXD,

We're tracking allowing users to pick their preferred shell environment in #888, please subscribe to that issue to follow along!
