### ISSUE TITLE
App goes into crash > restart loop without ever showing UI

### ISSUE THREAD

**Issue by revanmj** [desktop/desktop#2204]
### Description

After installing GitHub Desktop nothing seems to hapen, but when you open Task Manager, you can see that GitHub Desktop went into crash > restart loop that is so fast, it cannot be stopped without logging out or restarting a computer.

### Version

**GitHub Desktop version:** 0.6.2

**OS version:** Windows 10.0.15063 (64-bit)

### Steps to Reproduce

1. Install GitHub Desktop (doesn't matter whenever by normal installer or MSI)
1. Open Task Manager
1. Look at GitHub Desktop processes behavior

**Expected behavior:** App launches properly

**Actual behavior:** App goes into crash > restart loop

**Reproduces how often:** Always

### Logs

[2017-07-08.desktop.production.txt](https://github.com/desktop/desktop/files/1132864/2017-07-08.desktop.production.txt)

#### Additional Information

Windows language is set to Polish.

**Comment by coaperator** [comment]
[#2122](https://github.com/desktop/desktop/issues/2122) [#1863](https://github.com/desktop/desktop/issues/1863)

**Comment by niik** [comment]
Hi @coaperator, thanks for reporting this! It seems like this is the same issue as #1875 so please subscribe to that issue for updates

**Comment by niik** [comment]
Sorry, I meant to cc @revanmj in that last comment
