### ISSUE TITLE
Beta missing open to shell

### ISSUE THREAD

**Issue by MaddBomber83** [desktop/desktop#2207]
In Public Release, you can right click on a repository and open in whatever shell you had configured in settings.  This option is missing from the beta.

This is desirable because unlike Open Command Prompt, this logs you into the shell and checks out whatever branch you are looking at.

**Comment by niik** [comment]
Hi @MaddBomber83, I think what you're referring to (being able to select a particular shell to launch) is captured in #888. If that's not what you're referring to please let me know and we'll reopen this
