### ISSUE TITLE
Can't access my GITHUB repository with the new desktop app

### ISSUE THREAD

**Issue by rrobinet** [desktop/desktop#2208]
Hi,

I was running an old version of the github desktop app on my IMac (v10.9x).
Since a few days this one is crashing all the time :

```
Process: GitHub Desktop [7815]
Path: /Applications/GitHub Desktop.app/Contents/MacOS/GitHub Desktop
Identifier: com.github.GitHub
Version: Hasty Things Done Hastily (223)
Code Type: X86-64 (Native)
Parent Process: launchd [357]
Responsible: GitHub Desktop [7815]
User ID: 502

Date/Time: 2017-07-01 16:23:49.573 +0200
OS Version: Mac OS X 10.9.5 (13F1911)
Report Version: 11
Anonymous UUID: 4E50E5BA-5E1E-E5AF-AE5C-F242299BE388

Sleep/Wake UUID: 3344CADF-E24A-4908-B8D1-49A5754B6617

Crashed Thread: 0 Dispatch queue: com.apple.main-thread

Exception Type: EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

Application Specific Information:
Assertion failed: (tokenCount < maxCountIncludingZeroTerminator - 1), function CUIRenditionKeySetValueForAttribute, file /SourceCache/CoreUI/CoreUI-231.1/CoreTheme/ThemeStorage/CUIThemeRendition.m, line 136.
```
So I have downloaded the new version 0.6.2.
Unfortunately I can't connect to my existing github repository anymore (my name and email are ok in the preference menu)
Message is : Repository not found
However if I connect directly on github (https://github.com/rrobinet) and I sign in, and there is no problem to browse my repository.

Any idea of what should be the problem?
NB: This problem was submitted to the Forum and it was recommended to open an official issue with it.
Robert

**Comment by niik** [comment]
Hi @rrobinet,

Could you give us a little more information about what's happening on your end. Are you seeing any error messages or are you not able to find your repository in the new app?

We're currently not importing repositories and settings automatically from the old application so you need to sign in again and add any local repositories that you might have by selecting `Add local repository` undef the `File` menu.

**Comment by rrobinet** [comment]
The issues (Github Desktop v 0.6.2)
1. Do not recognise an exiting Github repository (https://github.com/rrobinet)
2. Do not access correctly an existing local repository (/Users/Robert/Data/Our Documents/Projets Techniques/Domotic/GitHub)


Steps:
1. I launch the github desktop
   In preference I am prompted to sign in (user name / e-mail and password)
2. I sign in successfully with my e-mail and password or using the browser
3. Main windows displays

    Current Repository   No repositories

   And 4 options
   Create a new repository - Clone a repository - Add a local repository
   Alternatively, you can drag and drop a local repository here to add it.

4. So I drop my actual github local directory (or I Add a local repository)
/Users/Robert/Data/Our Documents/Projets Techniques/Domotic/GitHub
or 
/Users/Robert/Data/‘Our Documents’/‘Projets Techniques’/Domotic/GitHub
(adding single quotes with file name with spaces!)

5. A Current EMPTY repository appears, but looking at the actual path I see
/Users/Robert
 in stead of the one specified!

From there a constant error message is displayed (which I can explain because is pointing to nearly my all disk!)

Error
The output from the command could not fit into the allocated stdout buffer. Set options.maxBuffer to a larger value than 10485760 bytes
 
All attempts to specify the actual local directory fails, so I can't get any further

Robert

**Comment by jtlowe** [comment]
I'm not seeing my Github.com repositories either after signing in on the Windows version (0.6.2). I sign in at "File>Options>Accounts". I then go to the repositories dropdown, but do not find these repositories. All I see in this menu are local repositories under "Other".

My "File>Options>Git" information is different than my account that I have logged in with. Don't know if that makes a difference.

**Comment by frankhale** [comment]
@jtlowe you have to manually add them to the UI

`File -> Add Local Repository`

or

`File -> Clone Repository`

Github Desktop does not automatically track any of your existing repositories unless you manually specify them.

**Comment by rrobinet** [comment]
Thanks for the tip but as explained above, it doesn't work

**Comment by joshaber** [comment]
@rrobinet Thanks for the reproduction steps! I just tried this locally and it worked fine, so there much be some nuance here that I'm missing.

Is `/Users/Robert/Data/Our Documents/Projets Techniques/Domotic/GitHub` the path to the actual git repository? What happens if you open that directory in Terminal and run `git status`?

**Comment by rrobinet** [comment]
Here you are:
```
home-iMac:GitHub Robert$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	../../../../../.CFUserTextEncoding
	../../../../../.MacOSX/
	../../../../../.Trash/
	../../../../../.Xauthority
	../../../../../.android/
	../../../../../.atom/
	../../../../../.bash_history
	../../../../../.bash_profile
	../../../../../.bash_profile.macports-saved_2016-09-05_at_12:12:38
	../../../../../.bash_profile.pysave
	../../../../../.cache/
	../../../../../.config/
	../../../../../.cups/
	../../../../../.dir
	../../../../../.dropbox/
	../../../../../.eaglerc
	../../../../../.editrocket/
	../../../../../.eidmwcache/
	../../../../../.filezilla/
	../../../../../.fontconfig/
	../../../../../.gdb_history
	../../../../../.gnupg/
	../../../../../.gtk-bookmarks
	../../../../../.idlerc/
	../../../../../.inkscape-etc/
	../../../../../.jssc/
	../../../../../.kdiff3rc
	../../../../../.keepassx/
	../../../../../.lesshst
	../../../../../.local/
	../../../../../.matlab/
	../../../../../.mono/
	../../../../../.mplayer/
	../../../../../.nchsoftware/
	../../../../../.npm/
	../../../../../.nsmbrc
	../../../../../.oracle_jre_usage/
	../../../../../.packetAnalizerColorThemes
	../../../../../.platformio/
	../../../../../.profile
	../../../../../.profile.macports-saved_2014-08-10_at_11:32:12
	../../../../../.profile.pysave
	../../../../../.rnd
	../../../../../.rs/
	../../../../../.scendix software/
	../../../../../.serverauth.10724
	../../../../../.serverauth.12614
	../../../../../.serverauth.13778
	../../../../../.serverauth.17462
	../../../../../.serverauth.17754
	../../../../../.serverauth.20213
	../../../../../.serverauth.24166
	../../../../../.serverauth.2742
	../../../../../.serverauth.32709
	../../../../../.serverauth.34594
	../../../../../.serverauth.35995
	../../../../../.serverauth.41617
	../../../../../.serverauth.41881
	../../../../../.serverauth.47196
	../../../../../.serverauth.499
	../../../../../.serverauth.639
	../../../../../.serverauth.7999
	../../../../../.serverauth.81435
	../../../../../.serverauth.87545
	../../../../../.spark/
	../../../../../.ssh/
	../../../../../.subversion/
	../../../../../.swt/
	../../../../../.viminfo
	../../../../../.vnc/
	../../../../../.wireshark-etc/
	../../../../../.wireshark/
	../../../../../55.tst
	../../../../../AA.tst
	../../../../../Albums/
	../../../../../Applications/
	../../../../../CEL Robox/
	../../../../
	../../../../../Desktop/
	../../../../../Documents/
	../../../../../Downloads/
	../../../../../Dropbox/
	../../../../../DwithCRC.tst
	../../../../../DwithCRCandLF.tst
	../../../../../DwithLF.tst
	../../../../../DwoLF.tst
	../../../../../Faxes/
	../../../../../I.tst
	../../../../../IwithCRC.tst
	../../../../../IwithCRCandLF.tst
	../../../../../IwithLF.tst
	../../../../../IwoLF.tst
	../../../../../Kits/
	../../../../../Library/
	../../../../../Movies/
	../../../../../Music/
	../../../../../PacketLoggerAutosave2016-05-25 15.59.29 +0000.pklg
	../../../../../Pictures/
	../../../../../Public/
	../../../../../SBConfigData.cmd
	../../../../../SBConfigState.cmd
	../../../../../SBNotifState.cmd
	../../../../../SIR-12.tst
	../../../../../SIR-16.tst
	../../../../../SIR-24.tst
	../../../../../SIR-30.tst
	../../../../../SIR-ErrorCode.tst
	../../../../../SIR-InvalidFormat.tst
	../../../../../SIR-MultiShort.tst
	../../../../../SIR-OnlyOneCorrect.tst
	../../../../../SIR-rubish.tst
	../../../../../SIR-very_long.tst
	../../../../../SIR.tst
	../../../../../Samsung/
	../../../../../Sauveguardes/
	../../../../../Sites/
	../../../../../String.tst
	../../../../../Temporaire/
	../../../../../Twonky Library.twonky/
	../../../../../VirtualBox VMs/
	../../../../../a.tst
	../../../../../d.tst
	../../../../../dump.tst
	../../../../../esptool/
	../../../../../get_au_info.tst
	../../../../../get_config.tst
	../../../../../get_du_eject.tst
	../../../../../get_du_info.tst
	../../../../../get_event.tst
	../../../../../get_notif.tst
	../../../../../get_su_eject.tst
	../../../../../get_su_info.tst
	../../../../../m.tst
	../../../../../mqttfx.log
	../../../../../nokia-contacts.csv
	../../../../../o.tst
	../../../../../packet-1000.tst
	../../../../../put_au_config.tst
	../../../../../put_au_em_config.tst
	../../../../../put_au_we_config.tst
	../../../../../put_cu_config.tst
	../../../../../put_cu_test_config.tst
	../../../../../put_du_config.tst
	../../../../../put_du_control.tst
	../../../../../put_du_eject.tst
	../../../../../put_su_config-old.tst
	../../../../../put_su_config.tst
	../../../../../put_su_eject.tst
	../../../../../put_su_start_eject.tst
	../../../../../put_su_stop_eject.tst
	../../../../../r.tst
	../../../../../set_config.tst
	../../../../../set_du_control.tst
	../../../../../set_du_eject.tst
	../../../../../set_notif.tst
	../../../../../set_su_eject.tst
	../../../../../spark-cli/
	../../../../../spark-repo/
	../../../../../t.tst
	../../../../../twonkymedia/
	../../../../../udp_write.py
	../../../../../x.egg/
	../../../../../x.tst

nothing added to commit but untracked files present (use "git add" to track)
home-iMac:GitHub Robert$ 
```

**Comment by joshaber** [comment]
Thanks @rrobinet!

It looks like `/Users/Robert/Data/Our Documents/Projets Techniques/Domotic/GitHub` _isn't_ itself a repository. But the way git works, it walks up the path until it finds a repository. And it looks like your home directory _is_ a git repository.

I imagine you don't intend for your home directory to be a repository, so I'd recommend deleting the `/Users/Robert/.git` directory. Then try adding your repositories again.

**Comment by rrobinet** [comment]
Thanks Jos
OK, I see a light in the tunnel.
I don't know why a .git file was created under my Home directory, anyway,
looking at the actual top github directory I couldn't see a .git file (even in a very old backup I had).
However under each sub directories there is a .git file
So I deleted it and created a new one (saving the existing one) under the same file name: 
/Users/Robert/Data/Our Documents/Projets Techniques/Domotic/GitHub
This one was just having a .git and Read.me files.
I then copied the old files to the new /GitHub repository and all my files did appears as "Changes".
So I did enter my user and password again and it seems that I have now a "master" somewhere?
Now my next problem is how to synchronise these files with my exiting github repository (https://github.com/rrobinet).
I don't want to create a new one because this one is referenced at several forum places. So I am a little bit afraid to Publish it,  I just want to synchronise.
What should I do?

Robert

**Comment by joshaber** [comment]
@rrobinet Ah, I think I see. So it sounds like your repositories are in the `/Users/Robert/Data/Our Documents/Projets Techniques/Domotic/GitHub` directory, but that directory itself _isn't_ a repository. So instead of adding that directory, add each of the projects within it individually.

**Comment by rrobinet** [comment]
Josh,

Ok it works, I understand (more or less...) now how it works, thanks for your support.

Roberr

**Comment by mondweep** [comment]
Hi - when I try to sign in on github desktop using my github.com account and password, I am told that 'The user name or passphrase you entered in not correct'. However, I have successfully authenticated with same details on github.com and can see my repositories in the browser version.

My github desktop version is 1.1.0

I also reinstalled github desktop version to see if that made a difference - it did not unfortunately.

Will appreciate an appropriate pointer to help troubleshoot further and resolve it.

P.S: By default a local repository comes up as the current repository - a project I had cloned earlier on. That repository isnt part of my github.com repositories. It remains in the 'Current Repository' list even after I reinstalled github desktop.



Thank you!

**Comment by shiftkey** [comment]
> Hi - when I try to sign in on github desktop using my github.com account and password, I am told that 'The user name or passphrase you entered in not correct'.

@mondweep please read [this known issue](https://github.com/desktop/desktop/blob/master/docs/known-issues.md#the-username-or-passphrase-you-entered-is-not-correct-error-after-signing-into-account---3263) as I think you are running macOS and dealing with a keychain issue.
