### ISSUE TITLE
by logging into my account i cannot see the repository created by me from web, though i am able to upload the file from GIT bash to remote repository but on GIT desktop its not showing

### ISSUE THREAD

**Issue by him009verma** [desktop/desktop#2210]
Please summarize the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

[Description of the issue]

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** [version here]

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

If you are dealing with a performance issue or regression, attaching a
[Timeline profile](https://github.com/desktop/desktop/blob/master/docs/contributing/timeline-profile.md)
of the task will help the developers understand the runtime behavior of the
application on your machine.

**Comment by iAmWillShepherd** [comment]
@him009verma can you please provide the version you are running along with steps to reproduce?

**Comment by him009verma** [comment]
i am using version 0.6.2 (GItHubDesktop)

if i am loging on to web , i can see my remote repositories under my
account but when i am trying to see the same from the GitHub Deaktop i
cannot see and i have make sure that i have logged in into the GitHub
Dektop i have checked this under under FIle>options under the Account tab
my id is there and on Git tab its having my name and email id

**Comment by frankhale** [comment]
@him009verma Unless you clone a repo from your account or add an existing one from your machine to Github Desktop it's not going to show in the UI even though you are logged in. In other words it does not automatically pull any of your repositories into the UI from your GH account.

**Comment by iAmWillShepherd** [comment]
@him009verma as @frankhale stated, we do not automatically pull all of your repositories and list them in the _clone_ dialog. You need to manually clone each repository or, if your repositories are already stored locally, you can add them by dragging-and-dropping them into Github Desktop.

**Comment by him009verma** [comment]
Thanks for the assistance :) and clarifications

On Tue, Jul 11, 2017 at 11:12 PM, William Shepherd <notifications@github.com
