### ISSUE TITLE
Error Dialog Disappears When Move Window to Forfront

### ISSUE THREAD

**Issue by darkn3rd** [desktop/desktop#2211]
### Description

I was attempting to note errors, as I was unable to git clone a repository.   I copied some information and pasted it to another program, then I brought GitHub Desktop to the foreground, and the Error dialog is magically closed without user interaction.  I did not want to have the dialog auto-close simply by bringing the window to the foreground; I thought that was what the [Close] button was for.

### Version

**GitHub Desktop version:** `0.6.2`
**OS version:** `Microsoft Windows [Version 10.0.15063]`

### Steps to Reproduce

1. Install GitHub Desktop and Open GitHub Desktop
1. git clone a repository with an invalid character (such as a file name with quote in it made on mac)
1. error dialog comes up
1. switch to another program
1. switch back to atom

**Expected behavior:** Dialog should still be there.

**Actual behavior:** Dialog disappeared without me closing it

**Reproduces how often:** 100%

### Logs

n/a

#### Additional Information

This happens with other dialogs as well, such as About dialog

**Comment by shiftkey** [comment]
@darkn3rd to clarify the behaviour: 

 - I still see the dialog when I alt-tab back to the app
 - the dialog will disappear as soon as I click in any space around the dialog (excluding the menu bar)

I've opened #2332 which I think is the right fix for this.
