### ISSUE TITLE
Can't turn a folder into a repository anymore

### ISSUE THREAD

**Issue by oscarmarcelo** [desktop/desktop#2212]
### Description

I can't drag a folder into the app (beta) to turn it into a repository like in GitHub for Mac/Windows.

### Version

**GitHub Desktop version:** 0.6.2

**OS version:** macOS Sierra 10.12.5 (16F73)

### Steps to Reproduce

1. Drag a regular folder (not a repository) into the app.
2. A error alert appears with the message "`repo path here` isn't a git repository."
3. Nothing else happens...

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behavior:** After the alert, it should the user if the dragged folder should be turned into a repository.

**Actual behavior:** Just shows the error alert and nothing else happens after that.

**Reproduces how often:** Always

### Logs

No logs were created.

**Comment by iAmWillShepherd** [comment]
@oscarmarcelo thanks for your feedback! 😃 

While adding the ability to drag-and-drop arbitrary folders seems like a nice to have, it would fall apart if the user accidentally tried to make `~/Library` or `~/Documents` a repository. These may be extreme cases, but it addresses the root to the problem, arbitrary folders may contain nested directories and so on and so forth.

**Comment by Zac-Garby** [comment]
What would be the problem with making `~/Library` or `~/Documents` a repository?

And I'm not sure if it would work, but would making a confirm dialog box appear when you drag a folder into the app, to make sure you definitely want to make that folder a repository, work?

**Comment by joshaber** [comment]
I tend to agree. I think we should use the "Add Local Repository" dialog so that users can click to initialize a new repository:

<img width="428" alt="screen shot 2017-07-19 at 11 43 08 am" src="https://user-images.githubusercontent.com/13760/28376182-75a2544e-6c77-11e7-8895-6b3ac98abbca.png">

But I feel like maybe I'm missing or forgetting some history. @iAmWillShepherd what do you think?

**Comment by whitecoffee** [comment]
Eh,what's the solution after all...

**Comment by iAmWillShepherd** [comment]
@joshaber Yea, I'd prefer it to be done in the dialog.

**Comment by j-f1** [comment]
I wonder if there should be a list of directories to warn people about when adding. (`/Users/*/Documents`, `C:\*\My Documents`, etc)

**Comment by CodyHenrichsen-CTEC** [comment]
I had been having students use the drag/drop projects into the application for previous versions of github desktop. The dialog option was helpful earlier

**Comment by joshaber** [comment]
As of 0.8.0, we now show the Add dialog, which gives users the option of creating a repository:

<img width="428" alt="screen shot 2017-09-06 at 5 03 22 pm" src="https://user-images.githubusercontent.com/13760/30134512-5e2e87f4-9325-11e7-82e7-57043f99e91e.png">

So I consider this to be complete.

@CodyHenrichsen-CTEC does that match what your students see? Could they be on an older version?

**Comment by CodyHenrichsen-CTEC** [comment]
it just goes to an error screen. I will check the version status when I get to the lab

________________________________
