### ISSUE TITLE
100 MB limit problem

### ISSUE THREAD

**Issue by Resonanz** [desktop/desktop#2213]
Please summarize the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

[Github for Windows Desktop continually tried to upload a large file, even though I exclude it using the right-click, ignore option, and the results of this action is stored in the .gitignore file]

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** [0.6.2]

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** [Windows 10 Pro Insider Preview build 16232 (slow ring, latest)]

### Steps to Reproduce

1. [Deselect the file in the left page (untick it)]
1. [Commit to master]
1. [Push origin]
1. [Wait for ages for it to try uploading the file]
1. [= fail]

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behavior:** [Fast simple upload to Github]

**Actual behavior:** [Sends all the files I think except for the large file]

**Reproduces how often:** [Every time]

### Logs
[2017-07-10.desktop.production.log.txt](https://github.com/desktop/desktop/files/1136589/2017-07-10.desktop.production.log.txt)

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

If you are dealing with a performance issue or regression, attaching a
[Timeline profile](https://github.com/desktop/desktop/blob/master/docs/contributing/timeline-profile.md)
of the task will help the developers understand the runtime behavior of the
application on your machine.

**Comment by iAmWillShepherd** [comment]
I think the issue you are experiencing is due to the file being in the repository already. Ignoring the file does not stop tracking it in Git. As a workaround, you can manually un-track the file by running `git rm --cached <file>`.

**Comment by iAmWillShepherd** [comment]
We should add an option to stop tracking ignored files.

**Comment by Resonanz** [comment]
Okay, so I deleted that repo online and deleted the .git hidden files on my PC, then created a new repo from the PC app. The files were added and I added a .gitignore, but the file that should be being ignored are not. *.afdesign and *.mp4 should be ignored, but the app is insistent upon uploaded them, and it fails because they are over 100 MB.  As an aside, this limit is really annoying for me because a lot of my work is lots of small files, and a few large files to accompany them LOL.

**Comment by iAmWillShepherd** [comment]
We have a solution for large files called [LFS](https://git-lfs.github.com). Did you stop tracking the files in question using the command I suggested from before? A _.gitignore_ file will only ignore files after the fact, not files already being tracked. The order in which you described your steps leads me to believe you added a large file to your repo then added a _.gitignore_ without removing the files from cache.

**Comment by Resonanz** [comment]
Thanks Will. Yes, you would be correct :-)  I have not tried the command line yet (bit scary for a beginner).  The LFS looks like a solution, but on top of complexities on complexities, perhaps I would be better off using OneDrive :-( It does not do versioning, but it is cloud and simple.

**Comment by steveward** [comment]
> perhaps I would be better off using OneDrive :-( It does not do versioning, but it is cloud and simple.

We recommend not storing repositories in OneDrive/Dropbox/Box because a conflict when synchronizing to those services can result in Git data being corrupted.

>Oh, and the git command does not work since I don't have those tools installed.

If you go to the file menu in GitHub Desktop and select `Repository` > `Open command prompt` you will be prompted with a dialog that provides a link to a guide on how to install Git on your machine. Once you've installed Git you can use the command prompt to run Git commands.

If you have any further questions about Git LFS or GitHub Desktop, please feel free to reach out to support@github.com. We'd be happy to help.

**Comment by maheshdadhich12** [comment]
I am also facing same Issue and getting below error while pushing the code in git hub

**The push operation includes a file which exceeds GitHub's file size restriction of 100MB. Please remove the file from history and try again.**

My file is in KB but still getting above error

Please help, how to fix this issue

Regards,
Mahesh Dadhich

**Comment by steveward** [comment]
@maheshdadhich12 could you upload the log file from GitHub Desktop? That should provide the specific path to the large file that is causing the push operation to fail. 

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by harisriaz17** [comment]
**The push operation includes a file which exceeds GitHub's file size restriction of 100MB. Please remove the file from history and try again.**

I'm facing a similar issue when pushing a 2GB project initialized with git LFS. I have no 100MB file in there, yet it still gives me that error. Note: I'm pushing through the desktop client.

**Comment by ayoung81** [comment]
I'm getting this error but it doesn't tell me which file is the culprit and I cannot find anything over 100mb while browsing through the folders manually in finder.

**Comment by tierninho** [comment]
@ayoung81 Try opening your repository in the terminal/command line by using the menu option under the Repository menu. Once opened, then type `ls -lh` to see the files with the files sizes. Hope this helps.

**Comment by StenkinVlad** [comment]
same error 
**The push operation includes a file which exceeds GitHub's file size restriction of 100MB. Please remove the file from history and try again**.
Clean my both local repo at different PC and manualy check for GitHub repo - there are no 100 Mb files...

**Comment by tierninho** [comment]
@StenkinVlad Please [fill a new issue](https://github.com/desktop/desktop/issues/new?template=bug_report.md) with the details.

**Comment by xDope7137** [comment]
Is there a proper way to exclude this file directly without going through Tree File or manually? It becomes pain when it breaks your full repo. And LFS is much costly in different countries.

**Comment by Gastoraf** [comment]
Read this [article ](https://docs.github.com/en/github/managing-large-files/versioning-large-files)should help.
