### ISSUE TITLE
Error while trying to clone forked repository

### ISSUE THREAD

**Issue by viestursGr** [desktop/desktop#2214]
Please summarize the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

The following error occurs while trying to clone my forked repository when GitHub Desktop is not turn on:

![](https://image.prntscr.com/image/Jfwrj9hETFqbXc9L19a2uA.png)

### Version

**GitHub Desktop version:** 0.6.2
**OS version:** Microsoft Windows [Version 10.0.10240]

### Steps to Reproduce

0. Don't have GitHub Desktop turned on
1. Go to GitHub web page of some repository (mine was forked)
2. Press Clone or Download
3. Press Open in Desktop

Repository I got this error in: https://github.com/viestursGr/MultiSlider

**Expected behavior:** Repository begins clonning process.

**Actual behavior:** Got error screen and repository wasn't cloned.

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Logs

Maybe relevant log:

2017-07-11T00:32:54.733Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.133s)

**Comment by iAmWillShepherd** [comment]
@viestursGr, I just tried cloning `https://github.com/viestursGr/MultiSlider` with the client off and it completed with no issue. Could you include your log file, please?

**Comment by shiftkey** [comment]
My psychic debugger thinks this is a problem with how the app was installed, and reproducing it will be a challenge. [This is the failure that is triggering the error](https://github.com/electron/electron/blob/a6ea316a5de1964761a82d9376c23e99eff16d25/lib/browser/init.js#L117-L122).

I'd suggest a cleanup of `%LOCALAPPDATA%\GitHubDesktop` and `%APPDATA%\GitHub Desktop` and a fresh installation to see if it's repeatable for this setup.
