### ISSUE TITLE
Import repository list from previous GitHub Desktop version

### ISSUE THREAD

**Issue by steveharoz** [desktop/desktop#2220]
### Description

When using the previous version of GitHub Desktop (Chocolate-Covered Yaks), I've accumulated many repositories in the left pane. After installing Desktop Beta, I have to individually re-open all of those repositories in the new version.

### Version

**GitHub Desktop version:** 0.6.2

**OS version:** Windows 8.1

### Steps to Reproduce

1. Open several repositories via GitHub Desktop 3.x
1. Install GitHub Desktop Beta

**Expected behavior:** The beta version's repository list is populated with the previous version's repo list

**Actual behavior:** It's empty.

### Annoying Workaround

This needs to be done for all repositories:
1. In the old version, right click each repo
2. Click "Open in Explorer"
3. Drag folder from explorer to the new beta version

**Comment by iAmWillShepherd** [comment]
You can drag-and-drop your existing repositories into GitHub Desktop.

**Comment by steveharoz** [comment]
Hi @iAmWillShepherd. I'm not sure I understand what you mean. I tried dragging a repository from the left pane in the old GitHub Desktop to the new GitHub Desktop. It doesn't work because the old version doesn't let you drag a repository out. The only way that seems to work is to open every repository in explorer one-at-a-time then drag that folder from explorer to the new GitHub Desktop.

**Comment by niik** [comment]
@steveharoz Yeah, we don't currently import tracked repositories from the old client, see https://github.com/desktop/desktop/issues/186 for the tracking issue for that. You're correct that right now you need to drag and drop folders from explorer into the app or use the `Add Local Repository` menu item under the `File` menu.

Note that you can drag and drop multiple repositories at the same time to import them all.
