### ISSUE TITLE
can not go back to default window size

### ISSUE THREAD

**Issue by ecjtusbs** [desktop/desktop#2221]
### Description

[Onec I clicked the 'MAX window size' button(full screen),I can not find the way to resume the default window size]

### Version

**GitHub Desktop version:** [The new native]

**OS version:** [Windows 6.1.7601]

### Steps to Reproduce

1. [Launch the Program]
2. [Click the "Full Screen" button from the menu]
3. [Can not exit fullscreen mode]
4.[Menu bar is hidden in fullscreen mode]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by iAmWillShepherd** [comment]
You can press `F11` to enter and exit full-screen mode on Windows.
