### ISSUE TITLE
Deleting `\`char in `Add local repository` dialog make cursor jumps to end 

### ISSUE THREAD

**Issue by fbehrens** [desktop/desktop#2222]
on
Desktop 0.6.2
Microsoft Windows [Version 10.0.15063]

This doesn't bother me much, 
but maybe you want to fix it

**Comment by iAmWillShepherd** [comment]
Thanks for bringing this to our attention! 👍

**Comment by zachwaugh** [comment]
I've hit this a number of times on Mac (v0.7.0) as well, and I believe it's the same underlying issue. Typing a single character anywhere in the "Add Local Repository" field automatically makes it jump to the end, which is incredibly annoying if you need to go fix the path.

![add-local-repo](https://user-images.githubusercontent.com/21447/28534903-6aeaf0c2-7070-11e7-8513-0b2f3028d71b.gif)

**Comment by shiftkey** [comment]
@zachwaugh thanks for the GIF! I can see the same behaviour in the latest version. I'll see if I can isolate the root cause and get a fix together.
