### ISSUE TITLE
Characters with accents in files encoded with WIN1252 displayed wrong

### ISSUE THREAD

**Issue by mateusviccari** [desktop/desktop#2223]
### Description

When a file managed by git is encoded in WIN1252 / CP1252 and have characters with accents (é, ã, ô) they get displayed with an � in the history viewer, even though the file itself displays correctly when opening with any text editor.

### Version

**GitHub Desktop version:** 0.6.2

**OS version:** Microsoft Windows [version 10.0.15063] 

### Steps to Reproduce

1. Create a file encoded in WIN1252 (CP1252) with accented characters
2. Manage it in version control
3. Commit changes to the repository
4. Check history viewer in GitHub Desktop

**Comment by iAmWillShepherd** [comment]
Closing since this is cover in issue #1607.
