### ISSUE TITLE
Where have all the options gone? 

### ISSUE THREAD

**Issue by JawadS** [desktop/desktop#2228]
### Description

Where have all the options gone where i can specify default locations for pulling repos? make changes to the default bash application and other features? ....

### Version

**GitHub Desktop version:** 0.6.2

**OS version:** Windows 10

**Comment by iAmWillShepherd** [comment]
The new version of Github Desktop uses the last location where it last cloned a repository. Keep in mind that the new version is still in beta and we are actively working on making it feature complete.
