### ISSUE TITLE
Diff isn't highlighting specific line changes

### ISSUE THREAD

**Issue by jtlowe** [desktop/desktop#2230]
### Description

The diff doesn't highlight what specifically changed within a line, in green or red. There is a very light green or red background for the lines that have differences, but the specific changes are not highlighted in the deeper red or green colors as github.com and the older github desktop app show.

I find it more difficult to determine what has changed on each line without the specific highlighting.

### Version

**GitHub Desktop version:** 0.6.2

**OS version:** Windows 10

### Steps to Reproduce

1. Click on a file that has changed to bring up the right diff view pane.

NEW APP DIFF
![github-desktop-diff-highlight](https://user-images.githubusercontent.com/766226/28136239-99337104-670e-11e7-994a-28b55a63cc47.png)

OLD APP DIFF
![github-desktop-diff-highlight-old-app](https://user-images.githubusercontent.com/766226/28136393-2c863734-670f-11e7-9df2-fb3a88423536.png)

**Expected behavior:** Specific line changes are highlighted darker so they stand out

**Actual behavior:** Only the entire line is highlighted

**Reproduces how often:** 100%

**Comment by joshaber** [comment]
Thanks for opening this @jtlowe! We're already tracking this in https://github.com/desktop/desktop/issues/173 so I'm gonna close this as a duplicate.

**Comment by jtlowe** [comment]
I searched first but didn't find 173. Glad to know someone's already on top of this!

Thanks
Jordan

On Jul 17, 2017, at 11:27 AM, Josh Abernathy <notifications@github.com> wrote:

Closed #2230.
