### ISSUE TITLE
Ask before adding LFS hooks

### ISSUE THREAD

**Issue by vsekhar** [desktop/desktop#2236]
### Description

When I open a repo with GitHub Desktop, it silently adds various hooks for LFS. I do not use LFS in this repo and do not have LFS tools installed. This means I cannot do any git operations without the hooks erroring out.

GitHub Desktop should either detect if the repo is already using LFS (and add the hooks silently as it does now) or should ask if I'd like LFS enabled (and add the hooks and command line tools as needed).

As it stands, it feels like a sneaky way of making my repo depend on a code base, feature set and online service that our project has no intention of depending on.

### Version

**GitHub Desktop version:** 223

**OS version:** MacOS 10.12.5

### Steps to Reproduce

1. Open a repo without lfs tools installed
1. Try to commit something

**Expected behavior:** Commit should work

**Actual behavior:** "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-commit."

**Reproduces how often:** 100%

### Logs

N/A

**Comment by joshaber** [comment]
@vsekhar It looks like that's a bug with the classic Mac app. This repository is for the new, Electron-based beta app. So I'm gonna close this so we can focus on that.

You might give the new beta a shot. You can download it from http://desktop.github.com.

**Comment by BanzaiMan** [comment]
I downloaded the client (version 0.8.2) from https://desktop.github.com/ last night (2017-09-13) and this still seems to be the case. Please consider getting a clear consent for this.

**Comment by j-f1** [comment]
@BanzaiMan Please open a new issue and fill out the template, so we can get this fixed 😃
