### ISSUE TITLE
Desktop stops working when the PC is low on memory

### ISSUE THREAD

**Issue by cw-pratik** [desktop/desktop#2238]
### Description

Am running desktop on my PC. Whenever the PC is very low on memory, Github desktop stops working (I get a white screen and can't do anything other than force closing desktop) or starts behaving weirdly. It occasionally also gives errors like "cannot malloc".

### Version

**GitHub Desktop version:** 0.6.2

**OS version:** windows 10 Pro

### Logs

> 2017-07-10T08:27:04.264Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color (took 2.580s)
> 2017-07-10T08:27:09.154Z - info: [ui] Executing getAheadBehind: git rev-list --left-right --count f-elasticsearch-update...origin/f-elasticsearch-update -- (took 1.629s)
> 2017-07-10T08:27:12.569Z - info: [ui] Executing getAheadBehind: git rev-list --left-right --count release-apigateway-webconfig...origin/release-apigateway-webconfig -- (took 1.866s)
> 2017-07-10T08:28:30.611Z - error: [ui] `git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 --` exited with an unexpected code: 3221225794.
> 2017-07-10T08:28:30.994Z - error: [ui] `git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes` exited with an unexpected code: 3221225794.
> 2017-07-10T08:28:39.043Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 8.737s)
> 2017-07-10T08:28:39.362Z - error: [ui] `git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color` exited with an unexpected code: 3221225794.
> 2017-07-10T08:28:39.366Z - error: [ui] `git remote -v` exited with an unexpected code: 3221225794.
> 2017-07-10T08:28:39.423Z - error: [ui] `git var GIT_AUTHOR_IDENT` exited with an unexpected code: 3221225794.
> 2017-07-10T08:29:07.384Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 2.446s)
> 2017-07-10T08:29:07.386Z - error: [ui] `git status --untracked-files=all --branch --porcelain=2 -z` exited with an unexpected code: 128.
> fatal: Out of memory, malloc failed (tried to allocate 149 bytes)
> 
> 2017-07-10T08:29:08.966Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 2.816s)
> 2017-07-10T08:29:08.967Z - error: [ui] `git status --untracked-files=all --branch --porcelain=2 -z` exited with an unexpected code: 128.
> fatal: Out of memory, malloc failed (tried to allocate 132 bytes)
> 
> 2017-07-10T08:29:11.711Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 4.109s)
> 2017-07-10T08:29:11.711Z - error: [ui] `git status --untracked-files=all --branch --porcelain=2 -z` exited with an unexpected code: 128.
> fatal: Out of memory, malloc failed (tried to allocate 131 bytes)
> 
> 2017-07-10T08:29:13.950Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 8.896s)
> 2017-07-10T08:29:13.951Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 6.317s)
> 2017-07-10T08:29:13.951Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 7.539s)
> 2017-07-10T08:29:18.619Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes (took 11.005s)
> 2017-07-10T08:29:18.700Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes (took 13.672s)
> 2017-07-10T08:29:18.756Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes (took 12.374s)
> 2017-07-10T08:29:32.056Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 13.205s)
> 2017-07-10T08:29:36.074Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 4.014s)
> 2017-07-10T08:29:45.805Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 2.306s)
> 2017-07-10T08:29:46.666Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes (took 3.155s)
> 2017-07-10T08:29:48.178Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 4.644s)
> 2017-07-10T08:29:50.772Z - warn: [ui] Unable to deserialize JSON string to object [object Response]
> SyntaxError: Unexpected end of JSON input
> 2017-07-10T08:29:51.197Z - warn: [ui] fetchMentionables: failed for carwale/utils
> Error: API error https://api.github.com/repos/carwale/utils/mentionables/users: Not Modified (304)
>     at Object.<anonymous> (C:\Users\pratik.vasa\AppData\Local\GitHubDesktop\app-0.6.2\webpack:\app\src\lib\http.ts:126:13)
>     at Generator.throw (<anonymous>)
>     at se (C:\Users\pratik.vasa\AppData\Local\GitHubDesktop\app-0.6.2\webpack:\app\src\lib\http.ts:115:4)
> 2017-07-10T08:29:54.912Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 6.502s)
> 2017-07-10T08:30:01.273Z - info: [ui] Executing checkoutBranch: git checkout --progress f-elasticsearch-update -- (took 11.689s)
> 2017-07-10T08:35:23.816Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 4.963s)
> 2017-07-10T08:40:58.972Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 4.594s)
> 2017-07-10T08:46:33.830Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 4.304s)

**Comment by iAmWillShepherd** [comment]
> 2017-07-10T08:29:11.711Z - error: [ui] git status --untracked-files=all --branch --porcelain=2 -z exited with an unexpected code: 128.
fatal: Out of memory, malloc failed (tried to allocate 131 bytes)

It looks like this is failing in `git`, so there is not much I can do to solve that. The UI being blank afterwards seems to be caused by us not handling _Out of memory, malloc failed_. I've created #2241 to solve the UI problem, but without enough memory, the `git` error will persist.
