### ISSUE TITLE
Installation Should ask for some settings rather than assumptions

### ISSUE THREAD

**Issue by GeorgeWL** [desktop/desktop#2242]
For e.g.

[X] Add Shortcut to Desktop 

Many users prefer a clean desktop and to have the shortcuts in the start bar.

[X] Installation location 

Many users have multiple drives 

Can't think of anything else atm.

**Comment by iAmWillShepherd** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our current roadmap.

As an aside, Desktop uses a library called [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows) to install itself. Getting a PR merged there would allow us to take advantage of it in this project.

**Comment by paulcbetts** [comment]
Hi! If you want to consider disabling the Desktop shortcut, you can actually already do this via altering the parameters to your "--createShortcut" call, you can pick the locations explicitly.

**Comment by GeorgeWL** [comment]
@paulcbetts very well,  but that's not user friendly,  and Gh Desktop is supposed to be

**Comment by paulcbetts** [comment]
@GeorgeWL "You" refers to the GitHub Desktop development team, users don't have to do this!

**Comment by GeorgeWL** [comment]
@paulcbetts and is there a way for them to set it as a boolean tickbox option in the initial setup load?

**Comment by paulcbetts** [comment]
@GeorgeWL The first time a Squirrel app runs, it gets a `--squirrel-firstrun` flag, so Desktop could use that flag to decide to show a Welcome Wizard:tm:
