### ISSUE TITLE
"noreply" email is unexpectedly used on configuring page

### ISSUE THREAD

**Issue by SaschaNaz** [desktop/desktop#2244]
### Description

#1019 says the "noreply" email address is used when user checks "Keep my emails private" option but it is used even when the option is not checked.

### Version

**GitHub Desktop version:** 0.6.2

**OS version:** Windows 7

### Steps to Reproduce

1. Install GitHub Desktop
1. Sign in with GitHub

**Expected behavior:** GitHub Desktop should use my public main address to configure git

**Actual behavior:** It uses `@users.noreply.github.com` address

**Reproduces how often:** 100%

![image](https://user-images.githubusercontent.com/3396686/28194739-425cfa70-6881-11e7-8545-57ea48883f7c.png)

**Comment by iAmWillShepherd** [comment]
Thank you for opening this issue! 

The team will look into this. 👍

**Comment by tierninho** [comment]
Tested this and confirming it is a bug. 

Seems selecting the private email option is a one-way street, as you can't go back if you decide to uncheck the option -- hence the problem.

Tested in 0.8.1-beta2. Prereq: remove your email in the `~/.gitconfig` file 

@SaschaNaz I did get past this by opening the `~/.gitconfig` file and entering my email address.

**Comment by joshaber** [comment]
@shiftkey Are you still working on this?

**Comment by shiftkey** [comment]
@joshaber not currently If someone else wants to grab it then :thumbsup: - otherwise I'll revisit next week when I'm not on call.
