### ISSUE TITLE
Is there anyway to discard changes for multiple files?

### ISSUE THREAD

**Issue by JosephTLyons** [desktop/desktop#2246]
### Description

I could be missing something, but I've always wanted to be able to discard changed across multiple files without having to right click and choose the option for each file.  Is there any way to batch discard changes?

### Version

**GitHub Desktop version:** [0.6.2]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by JosephTLyons** [comment]
Shoot, didn't mean to submit this form without adding more or deleting unnecessary fields, had trouble doing this on mobile.

**Comment by iAmWillShepherd** [comment]
Yes, there is!

Just right-click on the header for the change list and select _Discard all changes..._

![2017-07-14_10-19-08 942](https://user-images.githubusercontent.com/1715082/28218368-f1dd3248-687d-11e7-8846-dbe977d8f420.png)

As of right now, there is no way to select the files you want to reset though.

**Comment by JosephTLyons** [comment]
Yep, I knew you could discard all, curious to see if one day a way to choose multiple files will be implemented.

**Comment by iAmWillShepherd** [comment]
Yep, see the issue I created for that. Feel free to give a thumbs up if it captures your use-case.

**Comment by benthroop** [comment]
I would also like this. Respecting the checkboxes would make sense.

**Comment by samjakobcavazos** [comment]
I would like this feature as well. Selecting the files we would like to discard, then right clicking giving an option to discard selected. This shouldn't be difficult to incorporate.

**Comment by j-f1** [comment]
This is being tracked over in https://github.com/desktop/desktop/issues/1712. Please use the 👍 button on that issue to show your support.
