### ISSUE TITLE
Add Flag to Pull Request?

### ISSUE THREAD

**Issue by chasen-bettinger** [desktop/desktop#2247]
### Description

Is there a way to add a flag directly from the GitHub Desktop GUI to a pull / push? I have encountered this error: Unable to merge unrelated histories in this repository. From a google search it appears that the way to solve this error is to use the _--allow-unrelated-histories_ flag with a pull request. Source: https://stackoverflow.com/questions/37937984/git-refusing-to-merge-unrelated-histories

### Version

**GitHub Desktop version:** 0.6.2

**OS version:** Version 10.0.15063

**Comment by iAmWillShepherd** [comment]
Thanks for the question. No, there currently isn't a way to do what you're asking. It is something we're aware of and haven't placed in our priority list yet. For more background, see #1484.

**Comment by gherson** [comment]
good call, Chasen.  I just solved my problem by adding that argument:
>git pull origin master --allow-unrelated-histories
