### ISSUE TITLE
Difficult to get fetch from large number of repositories

### ISSUE THREAD

**Issue by jlperla** [desktop/desktop#2249]
### Description
The basic issue is that if you have a large number of repositories, there is no way to know which one you need to check.  This means you need to manually go through dozens of projects in the "current repository" list and do a Fetch.

Unless I am missing something obvious, I suspect this is a feature request.  My suggestion to solve this problem is twofold:
 * Highlight repositories that have been fetched but not pulled as a different color in the current repository list
 * Add in a "fetch all", which goes through all of the repositories, fetching (and changing the color as required
 * That way, you can look at the dropdown to visually see which ones you need to go and do a "pull", etc. manually.

**Comment by mort666** [comment]
The way the dropdown is done in this beta is not designed for anyone that has a large number of repositories to manage or work with. 

Having a pin-able dropdown that stays open all the time will have a large impact make working with large numbers of repositories. Coupled with extra visual indicators in that list for status of the repository will make this beta GHD usable.

**Comment by jlperla** [comment]
I understand, but even without pinning, this would be a useful feature.
Your competitors, such as smartgit, already have something similar where
favorited repositories do an automatic fetch on a schedule

**Comment by joshaber** [comment]
Thanks @jlperla! We agree this would be nice to have. We're gonna track all the feedback around providing more information in the repository list in https://github.com/desktop/desktop/issues/2259. This is [currently roadmapped](https://github.com/desktop/desktop/blob/df3c0a089ecacea86462fb55244a108d0a419a53/docs/process/roadmap.md#13) for 1.3.
