### ISSUE TITLE
New branches show all historical commits.

### ISSUE THREAD

**Issue by radumg** [desktop/desktop#2250]
### Description

When making a new branch or using existing ones, the new GitHub Deskop app shows all historical commits, including commits made before the branch was created, from the parent/master branch.

It also does not differentiate between parent branch commits inherited when the branch was created and subsequent commits made to the new branch only.

### Version

**GitHub Desktop version:** 0.6.2

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Make a new branch from an existing one (such as master)
2. All the historical commits of the existing branch are shown as part of the new branch
3. Make commits to new branch
4. The new commits show up in the branch `History` alongside the inherited commits.

**Expected behavior:** The newly created branch should not show the historical commits of the parent branch. This is the behaviour in the current (native) Windows desktop app :

![old github](https://user-images.githubusercontent.com/11439624/28246798-37ad8668-6a1a-11e7-9388-520b4a361923.PNG)

If behaviour desired by GitHub PM team has changed between versions, it would be great if the old behaviour was still acknowledged by :
- either adding an option to show/not show historical commits
- visually marking the commits to show they're from different branches (a tag for both, or greyed out parent commits).

**Actual behavior:** The new commits now also appear in GitHub Desktop, but they are not differentiated graphically (or otherwise) in any way in the UI.

![new gitihub inked](https://user-images.githubusercontent.com/11439624/28246799-3dc0d3c0-6a1a-11e7-835b-e4b6fc2ef2e9.PNG)

**Reproduces how often:** 100%

#### Additional Information
I'm loving the speed and clean interface of the new beta desktop app - amazing work team !

**Comment by joshaber** [comment]
Thanks for the suggestion! This is something we currently have on our [roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md#11) for 1.1.

We're already tracking this work in https://github.com/desktop/desktop/issues/1691 so I'm gonna close this.

**Comment by radumg** [comment]
thanks @joshaber for the follow up, hadn't found that previous issue (I looked, obvs not hard enough though).

**Comment by joshaber** [comment]
No worries!

**Comment by alphataubio** [comment]
this is happening again as of Version 3.3.6 (arm64) on macos

**Comment by steveward** [comment]
@alphataubio if you're encountering a bug please open a new issue and fill out the template so we can investigate. Thanks!
