### ISSUE TITLE
Allow collapsing/expanding changes

### ISSUE THREAD

**Issue by shinespeciall** [desktop/desktop#2251]
Sometimes programmer need to replace some special charecters in a whole procedure, file or project, and the App or the github site will show all the difference which will be disgusting when other important change have been made together. So how about seperate these kind of changes as a note and just collapse the parts classified as this kind ?

**Comment by joshaber** [comment]
I'm not sure I understand, could you go in a bit more detail about the distinction between the two types of changes?

**Comment by shinespeciall** [comment]
######    I'm just think that if things will be better if the App or website seperate out the replacement of some kind of string behind the frame showing a file or procedure differences and collapse the lines (only change by replacing some special charectors like functions or menbers etc.  these thing can be find out by "function(" or space+string+space easily ) into one line with a different color and a different note to mark it.

**Comment by shinespeciall** [comment]
And the note for the collepsed line after the number change means nothing if too many things being collepsed, so a replacement note will perhaps be more useful, and anyway we can uncollepse the lines if we like.

**Comment by joshaber** [comment]
It sounds like you're asking for the ability to collapse and expand changes. Do I have that right or am I misunderstanding you?

**Comment by shinespeciall** [comment]
you get it.

**Comment by joshaber** [comment]
This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by shinespeciall** [comment]
okey.
