### ISSUE TITLE
I am not able to open git command promt

### ISSUE THREAD

**Issue by veluguridinesh** [desktop/desktop#2253]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by j-f1** [comment]
Please fill out the issue template so that we can better help you.
