### ISSUE TITLE
Provide warning that new version blocks "open from desktop" from working in the old version

### ISSUE THREAD

**Issue by steveharoz** [desktop/desktop#2255]
### Description

After installing the new Github Desktop, clicking "Open from Desktop" on a repository's github page opens in the new version. But after the new version is uninstalled, "Open from Desktop" no longer works with the old version. Even reinstalling the old version doesn't fix the problem.

### Version

**GitHub Desktop version:** 0.6.2 and 3.3.4.0

**OS version:** Windows 8.1

### Steps to Reproduce

1. Install old version
1. Go to any repository's github page, and click "Clone or Download" -> "Open from Desktop"
1. **It works!**
1. Now install the new version
1. Uninstall the new version
1. (Optionally reinstall the old version)
1. Go to any repository's github page, and click "Clone or Download" -> "Open from Desktop"
1. **It does nothing**

Please warn people that installing the new beta version irrevocably messes up the old version.

**Comment by steveward** [comment]
Thanks for opening this! We're tracking this in https://github.com/desktop/desktop/issues/1676, so I'm going to close this as a dupe.

**Comment by shiftkey** [comment]
Reopening this one as #1676 is a macOS-specific issue (how the app registers registers protocol handlers on Windows is slightly different), and the registering of protocol handlers should work after updating.

@steveharoz could you attach any interesting [log files](https://github.com/desktop/desktop/blob/master/docs/installation.md#log-files) to this issue? This will help with troubleshooting.

**Comment by shiftkey** [comment]
Ugh, I missed this bit:

> Uninstall the new version
> (Optionally reinstall the old version)

Yep, it's #1676.
