### ISSUE TITLE
Menu order should mimic design

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2264]
The menu items are in a different order of the buttons when trying to create a repo. Added polish if we can mimic the order.

<img width="1071" alt="screen shot 2017-07-17 at 2 13 11 pm" src="https://user-images.githubusercontent.com/14828183/28283044-8dd91882-6afa-11e7-86f7-134392f24e9f.png">

v0.6.2, OSX

**Comment by j-f1** [comment]
Which should be changed — the menu or the UI?

**Comment by Zac-Garby** [comment]
I think if either should be changed, it should be the UI, because the if the menu was moved around it would seem less intuitive, but I don't think the user expects the UI to be in any particular order.
