### ISSUE TITLE
Can't show any repository on Github

### ISSUE THREAD

**Issue by CGQAQ** [desktop/desktop#2267]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

#### Additional Information

Github desktop shows that I have no repository on Github, but I surely have

**Comment by steveward** [comment]
👋  @CGQAQ 

Currently we do not list your available repositories in GitHub Desktop, but this is something that we are discussing bringing back. You can follow along in 
https://github.com/desktop/desktop/issues/57 for updates.

There are two options you can use to clone repositories in GitHub Desktop:

1. Go to `File` > `Clone Repository` and enter the URL of the GitHub repository you would like to clone.

2. Go to the repository's page on GitHub and click the green `Clone or download` button and select `Open in Desktop`.

Hope that helps!
