### ISSUE TITLE
Unable to clone WIKI site 

### ISSUE THREAD

**Issue by ir8jim** [desktop/desktop#2269]
### Description
Unable to create a clone of a WIKI site from my GHE site using new GH Desktop client.   

### Version 
Github Desktop client v0.6.2
Running on Windows 10.0.14393
GHE website version 2.10.2

### Steps to reproduce
Step 1 Select a repository from GHE website
Step 2 Select "Wiki" on the Repo
Step 3 Select option to "Clone in Desktop" 

**Expected Behavior**
Wiki would be cloned into its own repo locally

**Actual Behavior** 
When attempted the Desktop Client is launched, the cloning dialog is shown, it processes for a minute or so, then goes away without doing the clone.  

**Additional Information**
Cloning of repositories works w/o any issues.

### Logs
[2017-07-18.desktop.production.zip](https://github.com/desktop/desktop/files/1156713/2017-07-18.desktop.production.zip)

**Comment by joshaber** [comment]
We just release 0.7.0 which should fix this. Give it a shot and let us know if it's still not working as you'd expect!
