### ISSUE TITLE
Accessibility audit

### ISSUE THREAD

**Issue by donokuda** [desktop/desktop#227]
Let's take the opportunity to ensure GHD:9000's accessibility is on point and use this to track anything that needs improvement.

**Comment by joshaber** [comment]
@niik with #1289 landed are we good to close this?

**Comment by niik** [comment]
> @niik with #1289 landed are we good to close this?

Yup! We're certainly not done with our a11y work but we've definitely audited the app and have a good sense of where the weak areas are (CodeMirror being chief among them)
