### ISSUE TITLE
Duplicate shortcut for "Pull" and "Create Pull Request"

### ISSUE THREAD

**Issue by luukdv** [desktop/desktop#2274]
In version `0.7.0`, `Shift + CMD + P` is both 'Pull' and 'Create Pull Request'.

**Comment by haroldangenent** [comment]
See [this shortcut](https://github.com/desktop/desktop/blob/aba262844b1eefabecba68a3f132ec670e6c3167/app/src/main-process/menu/build-default-menu.ts#L198) and [this shortcut](https://github.com/desktop/desktop/blob/aba262844b1eefabecba68a3f132ec670e6c3167/app/src/main-process/menu/build-default-menu.ts#L278]). Added in https://github.com/desktop/desktop/commit/aba262844b1eefabecba68a3f132ec670e6c3167 (from #2195).

**Comment by joshaber** [comment]
Great catch! Thanks for bringing it to our attention.

**Comment by mtclmn** [comment]
Would love to see `Cmd+R` for Create PR like the old Desktop app

**Comment by luukdv** [comment]
Would it be possible to change the PR shortcut instead of removing the Pull shortcut (which also was in place much earlier)? I think the latter one will be used a lot more on a day-to-day basis.

**Comment by joshaber** [comment]
>Would it be possible to change the PR shortcut instead of removing the Pull shortcut

>Would love to see Cmd+R for Create PR like the old Desktop app

Yup, I think this is a better idea. I've updated https://github.com/desktop/desktop/pull/2278 to do this. Thanks for the feedback!
