### ISSUE TITLE
Running multiple times on Windows will fail

### ISSUE THREAD

**Issue by birbilis** [desktop/desktop#2275]
If user accidentally runs multiple times, all instances fail (probably lock files of one another)
At least one of them was showing the following log, probably other was showing different file/folder issue

Make a singleton app. Wonder if Electron supports such a thing (that is when run more times just pass focus to the other copy). Could at least use a lock file and probably warn user that other copy is running and optionally allow removing the lock and tell them to lon off/on to their OS after that if it still fails (so that other hung instances are removed)

> 2017-07-19 11:19:07> Program: Starting Squirrel Updater: --install .
> 2017-07-19 11:19:07> Program: Starting install, writing to ......\AppData\Local\SquirrelTemp
> 2017-07-19 11:19:07> Program: About to install to: ......\AppData\Local\GitHubDesktop
> 2017-07-19 11:19:07> Program: Install path ......\AppData\Local\GitHubDesktop already exists, burning it to the ground
> 2017-07-19 11:19:18> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.IO.IOException: Η πρόσβαση στο αρχείο '......\AppData\Local\GitHubDesktop\packages\GitHubDesktop-0.7.0-full.nupkg' δεν είναι δυνατή για τη συγκεκριμένη διεργασία, επειδή το αρχείο χρησιμοποιείται από άλλη διεργασία.
>    σε System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    σε System.IO.File.InternalDelete(String path, Boolean checkHost)
>    σε System.IO.File.Delete(String path)
>    σε Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
>    σε Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
>    σε System.Threading.Tasks.Task.InnerInvoke()
>    σε System.Threading.Tasks.Task.Execute()
> --- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
>    σε System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    σε Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
> --- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
>    σε System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    σε Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
> --- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
>    σε System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    σε Squirrel.Utility.<>c.<<DeleteDirectory>b__19_1>d.MoveNext()
> --- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
>    σε System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    σε Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
> --- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
>    σε System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    σε Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
> --- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
>    σε System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    σε Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
> 2017-07-19 11:19:18> Unhandled exception: System.AggregateException: Παρουσιάστηκαν ένα ή περισσότερα σφάλματα. ---> System.IO.IOException: Η πρόσβαση στο αρχείο '......\AppData\Local\GitHubDesktop\packages\GitHubDesktop-0.7.0-full.nupkg' δεν είναι δυνατή για τη συγκεκριμένη διεργασία, επειδή το αρχείο χρησιμοποιείται από άλλη διεργασία.
>    σε System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    σε System.IO.File.InternalDelete(String path, Boolean checkHost)
>    σε System.IO.File.Delete(String path)
>    σε Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
>    σε Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
>    σε System.Threading.Tasks.Task.InnerInvoke()
>    σε System.Threading.Tasks.Task.Execute()
> --- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
>    σε System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    σε Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
> --- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
>    σε System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    σε Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
> --- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
>    σε System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    σε Squirrel.Utility.<>c.<<DeleteDirectory>b__19_1>d.MoveNext()
> --- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
>    σε System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    σε Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
> --- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
>    σε System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    σε Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
> --- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
>    σε System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    σε Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
> --- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
>    σε System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    σε System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    σε Squirrel.Update.Program.<Install>d__4.MoveNext()
>    --- Τέλος ιχνηλάτησης στοίβας εσωτερικών εξαιρέσεων ---
>    σε System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    σε System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    σε System.Threading.Tasks.Task.Wait()
>    σε Squirrel.Update.Program.executeCommandLine(String[] args)
>    σε Squirrel.Update.Program.main(String[] args)
> ---> (Εσωτερική εξαίρεση #0) System.IO.IOException: Η πρόσβαση στο αρχείο '......\AppData\Local\GitHubDesktop\packages\GitHubDesktop-0.7.0-full.nupkg' δεν είναι δυνατή για τη συγκεκριμένη διεργασία, επειδή το αρχείο χρησιμοποιείται από άλλη διεργασία.
>    σε System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    σε System.IO.File.InternalDelete(String path, Boolean checkHost)
>    σε System.IO.File.Delete(String path)
>    σε Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
>    σε Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
>    σε System.Threading.Tasks.Task.InnerInvoke()
>    σε System.Threading.Tasks.Task.Execute()
> --- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
>    σε System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    σε Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
> --- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
>    σε System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    σε Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
> --- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
>    σε System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    σε Squirrel.Utility.<>c.<<DeleteDirectory>b__19_1>d.MoveNext()
> --- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
>    σε System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    σε Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
> --- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
>    σε System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    σε Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
> --- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
>    σε System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    σε Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
> --- Τέλος ιχνηλάτησης στοίβας από προηγούμενη θέση όπου δημιουργήθηκε μια εξαίρεση ---
>    σε System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    σε System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    σε System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    σε Squirrel.Update.Program.<Install>d__4.MoveNext()<---
> 
>

**Comment by birbilis** [comment]
Note that I don't remember if it was the installer I had run multiple times or the app itself

**Comment by joshaber** [comment]
That log certainly looks like it was the installer was run again while the app was also running.

The app itself is already a singleton, using the mechanism that Electron provides which, AFAICT uses a lock file as you suggest.

It'd be nice if Squirrel.Windows (the updater/installer framework) were smarter about how it handles this situation, but I don't think GitHub Desktop is doing anything wrong here.
