### ISSUE TITLE
Can't cancel clone operation

### ISSUE THREAD

**Issue by birbilis** [desktop/desktop#2276]
I started clone operation for the wrong GitHub repo (locally cloned the original instead of my online forked version) and I see that I can't cancel.  Given that it is big I may wait for a long time. Not obvious what happens to the clone operation if I close the app and if I will be able to cancel or resume it after running the app again

**Comment by steveward** [comment]
Thanks for opening this @birbilis. I'm going to close it as a duplicate of #2082. Please follow along there for updates.
