### ISSUE TITLE
Error message is incorrect

### ISSUE THREAD

**Issue by chriscn** [desktop/desktop#2279]
When pushing a repo to Github.com; it fails saying there is no internet checking however it should say you do not have a private plan. As I mentioned in my previous issue, #2165  it should be unticked by default.

All that needs to happen is that the error message says "You do not have a paid plan, please upgrade" or that the box is unchecked by default.

![Image showing what is happening](https://user-images.githubusercontent.com/25829276/28378388-e9c5774a-6ca7-11e7-80af-a284a997c3f7.png)

**Comment by joshaber** [comment]
Thanks @chriscn! We'll take a look.

**Comment by chriscn** [comment]
Glad I could help.
