### ISSUE TITLE
Where to find the earlier release GitHub Desktop v223

### ISSUE THREAD

**Issue by drakeet** [desktop/desktop#2295]
Excuse me. I really love the old version of GitHub Desktop for Mac, I don't know **if there is any open source code for GitHub Desktop v223**. I know it has not been updated, but I think if I can get the source code, I can update it for myself or some people.

Thank you very much for your great work!

![image](https://user-images.githubusercontent.com/5214214/28449877-1bf58e66-6e16-11e7-8166-a521a3255508.png)

**Comment by j-f1** [comment]
Thank you for contributing!

I’m pretty sure the source code is at https://github.com/github/Mac, which is not an open-source repository.

If there’s a bug or missing feature cauwsing you to switch back to the old version, please tell us so we can work on fixing it!

**Comment by drakeet** [comment]
@j-f1 Thank you! 

Yes, there is a bug: **I can not use the button "Open in Desktop" with the old GitHub Desktop(v223)**. Specifically, if I only have v223, it does not respond. 

"Open in Desktop" is a very convenient feature, I do not want to lose it. 
![image](https://user-images.githubusercontent.com/5214214/28462272-190ae0ac-6e4d-11e7-872c-21773ae095e4.png)

**Comment by drakeet** [comment]
BTW, I think the "Sync" of _v223_ is a very great design and feature. If the new version of Desktop will also have Sync, maybe I will love it too.
![image](https://user-images.githubusercontent.com/5214214/28462668-bbb98172-6e4e-11e7-8937-abe1ee63355c.png)

**Comment by j-f1** [comment]
@drakeet The “Sync” button was confusing, so it was replaced with a similar button to push or pull.

**Comment by drakeet** [comment]
@j-f1 Understood. But if someone who knows what "Sync" do, will fall in love with it, alas, it's a pity.

**Comment by j-f1** [comment]
The rationale for changing the “Sync” button is explained [here](https://github.com/desktop/desktop/issues/549#user-content-magic-sync-button) and in #1565.

**Comment by joshaber** [comment]
We don't currently have any plans to open source the Classic apps.

> I can not use the button "Open in Desktop" with the old GitHub Desktop(v223). 

That's currently being tracked in https://github.com/desktop/desktop/issues/1676.

Other than that, I think @j-f1 answered everything else so I'm gonna close this. Let me know if I've missed anything!

**Comment by zapjonny** [comment]
I'm really confused with the new Github Desktop too. Is it really any better? How do we compare one branch against another branch like before? It was very easy to merge changes from one branch into another that way...

**Comment by joshaber** [comment]
>How do we compare one branch against another branch like before?

That's something we miss too! We're planning to tackle this in 1.1: https://github.com/desktop/desktop/issues/2639

**Comment by fromdev** [comment]
Luckily I had never deleted the version 220 installer - that had the sync button - I can share on a gdrive or something if you are desperate like me :)

**Comment by j-f1** [comment]
@fromdev The v223 installer is available for the time being at https://central.github.com/mac/latest. However, there are no guarantees about how long that will last.

**Comment by fromdev** [comment]
@j-f1 - Thanks - I downloaded it. Will keep it until new client stabilizes.

**Comment by j-f1** [comment]
@fromdev If there are any specific features you’re missing or issues you’ve encountered, please open issues about them so we can fix them for you!

**Comment by kuehn-sba** [comment]
From the user's point of view, the "classic version" has a more comfortable design. But these are just my thoughts...

**Comment by nitinme** [comment]
Any place I can get the Windows version of the old client app?

**Comment by joshaber** [comment]
@nitinme https://github-windows.s3.amazonaws.com/GitHubSetup.exe, with the same caveats as above 😄

**Comment by jellyfeelings** [comment]
oh thank god. new version is slow, missing major features like "discard selected changes", was basically in no way an improvement (maybe in the long term?)  So hard to find the v223 and so grateful it was linked here

**Comment by dseeker** [comment]
tried the new one but the lack of branch compare turned me off, so useful for quick checks. I hope this version doesn't disappear from the web, much better ATM

**Comment by der-eismann** [comment]
+1 the old version was much better, thanks for the download!

**Comment by ywang04** [comment]
+1 thanks for the link to download the old version :)

**Comment by cdstamper** [comment]
+1 miss the older version, perhaps it would not be out of line to host a legacy app? or at least make the 'new' app better (electrum is slow, and the missing features were incredibly helpful compared to _every_ other git client).

**Comment by zapjonny** [comment]
I'm using the old app and the new app side by side for a month or two and I can just say now that I feel the same way about the new app as I felt first time using it. It just feels so hindering compared to the old one. Being able to easily compare commit history (the two timelines with commit dots!) versus another branch is the real game changing feature for me. There are other limiting features with the new app too but I think they all mostly boil down to that you can't easily compare the current branch with another. You won't know if there are changes (and thus possible conflicts) versus another branch unless you go ahead and merge into that branch. You could of course open a browser and check your PR on github.com but yeah it adds to the slower workflow. With the old client you don't even need a PR. Unless I missed something.

**Comment by zapjonny** [comment]
@jellyfeelings I think you can discard selected changes in the new app. It's kind of hidden, if you right click on the line just above the changed file list on the left side, that feature should pop up.

**Comment by drakeet** [comment]
A long time passed, we still love the old version.

**Comment by shiftkey** [comment]
> There are other limiting features with the new app too but I think they all mostly boil down to that you can't easily compare the current branch with another. 

@zapjonny please have a look at https://github.com/desktop/desktop/issues/2639#issuecomment-333621771 as that's where we're heading with our "relationship between branches" experience

**Comment by pritam-jadhav-avalara** [comment]
+1 for the old version

**Comment by j-f1** [comment]
@pritam-jadhav-avalara Is there anything that you’re missing from the new version?
