### ISSUE TITLE
Let user add a description and expose it next to repo name in the UI

### ISSUE THREAD

**Issue by deborah-ufw** [desktop/desktop#2301]
Hi GitHub,

Thank you for the desktop tool and for GitHub overall. There is no better tool than GitHub out there. 

I have this difficulty in the desktop tool. Often I have several branches of the same repo, one branch for each task assigned to me. For example:

myrepo - branch 1 - globally change font
myrepo - branch 2 - globally update colors
myrepo - branch 3 - fix bug 1
myrepo - branch 4 - fix bug 2
myrepo - branch 5 - develop feature

In my desktop list, here's what I see for my repos:

myrepo
myrepo
myrepo
myrepo
myrepo

There is no way to tell them apart without pecking on each one to see the branch name. The repo list refers to the folder name, which can not be changed without breaking the link to the repo.

I need a way to add a description next to the repo name so I can select the branch I want in one click instead of 5 (or N). Often I have as many as 11 branches.

Creating or editing a .description file, a recommendation I found on StackOverflow, **does NOT work.**

Kind regards,
Deborah

**Comment by shiftkey** [comment]
@deborah-ufw thanks for the suggestion! We have a similar discussion over in #1929 around making it easier to distinguish between repositories with the same name. Please follow along there and add any other feedback you might have.
