### ISSUE TITLE
Add "Go To Line…" command (buttons, menus, or keys) 

### ISSUE THREAD

**Issue by geowar1** [desktop/desktop#2309]
### Description
Whenever GitHub Desktop detects and reloads a diff from disk it returns to the top (losing the place where you're currently viewing diffs).

It would be awesome if it wouldn't do this… ;-)

Regardless of that it would be convenient to have an easy way (other than just the scrollbars) to jump to a specific line of text in the diff's view.

### Version

GitHub Desktop version: Deer Types (222)
OS version: 10.12.6

**Comment by shiftkey** [comment]
> Whenever GitHub Desktop detects and reloads a diff from disk it returns to the top (losing the place where you're currently viewing diffs).

This behaviour is related to the classic Mac app. I'll see if this is reproducible with the Electron app (I suspect it is).

> Regardless of that it would be convenient to have an easy way (other than just the scrollbars) to jump to a specific line of text in the diff's view.

This would be an enhancement to the app, but I'll come back to this after dealing with the first part.

**Comment by shiftkey** [comment]
The scroll position is not reset when the selected file is changed on disk (we don't do anything explicit here to track it, but I think that's okay for now), so I'm going to move on to the rest of the issue.

**Comment by shiftkey** [comment]
> Regardless of that it would be convenient to have an easy way (other than just the scrollbars) to jump to a specific line of text in the diff's view.

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
@geowar1 Same thing here, as we want these future proposals to contain things we intend to reopen and work on at some point, and we haven't seen a ton of evidence here that we should invest in it. As with the other one though (and basically all of our decisions), we're happy to revisit if we think we were wrong. And we really appreciate the suggestions.
