### ISSUE TITLE
Add a way to view "git blame"

### ISSUE THREAD

**Issue by geowar1** [desktop/desktop#2310]
### Description

It would be convenient to be able to toggle on/off a "git blame" column in the file diff views.

### Version

GitHub Desktop version: Deer Types (222)
OS version: 10.12.6

**Comment by shiftkey** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
@geowar1 Thanks for the suggestion! Discussing this internally, we've decided that we're not going to pursue this specifically so I'm going to remove `future-proposal`. However, we are interested in exploring the idea of gaining additional context about the history of a particular file when it's been changed to help inform decision-making and such. This is getting at a similar idea, but we're not sure this is the way we want to approach it. We'll be revisiting that problem space though, and thanks for the idea. 😄

**Comment by rjurney** [comment]
I want this too. Very much.

**Comment by tierninho** [comment]
Another request to implement this: https://github.com/desktop/desktop/issues/9580

**Comment by AlexandruIstrate** [comment]
This is a must. It would be very useful.

**Comment by jornjanssen90** [comment]
a way to view all files in a project and adding right click -> git blame would be very useful

**Comment by steveward** [comment]
Requested in https://github.com/desktop/desktop/issues/13708.

**Comment by yannickrondeau** [comment]
Currently using two different git clients mostly for that specific feature. Would love to have it in Github Desktop.

**Comment by jhundley9109** [comment]
+1 for this feature. The client doesn't need to be super powerful but viewing all the commits to a given file seems pretty basic imo.

**Comment by Harkirat444** [comment]
Please add this feature.

**Comment by SoyDiego** [comment]
Please add this feature @shiftkey

**Comment by BorisMolch** [comment]
was this implemented?

**Comment by adamrpippin** [comment]
This is a significant missing feature.
