### ISSUE TITLE
some Windows users not able to resolve the command line tool

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#2312]
xref https://github.com/desktop/desktop/issues/696#issuecomment-316569042

Known workaround: open a terminal and run this command:

```
%LocalAppData%\GitHubDesktop\app-0.7.0\GitHub Desktop.exe --squirrel-updated
```

Opening this up to track whether follow-up work is necessary.

**Comment by joshaber** [comment]
Judging from https://github.com/desktop/desktop/issues/696#issuecomment-317135447, it looks like either our Squirrel hook isn't being run like we expect it to, or it is being run but is failing really early.

**Comment by joshaber** [comment]
More specifically, it looks like the `squirrel-updated` hook is failing 🤔
