### ISSUE TITLE
Duplicate keyboard shortcut causing confusion

### ISSUE THREAD

**Issue by dbchristopher** [desktop/desktop#2313]
### Description

Github Desktop beta currently lists the shortcut Command + Shift + P for two different commands. Originally that was used to *pull* from remote. Now it is also used for creating a new *pull request*

### Version

**GitHub Desktop version:** 

0.7.0

**OS version:** [version here]

Mac OS 10.12.5

### Steps to Reproduce

![screen_shot_2017-07-24_at_8_37_03_am](https://user-images.githubusercontent.com/238293/28531414-9f978cba-704b-11e7-96e9-39420b4cf549.png)

![screen_shot_2017-07-24_at_8_37_17_am](https://user-images.githubusercontent.com/238293/28531428-a81e475c-704b-11e7-8814-d9eacdf8a6a6.png)

**Expected behavior:** [What you expected to happen]

Command + Shift + P would pull from a remote branch, as originally designed.

**Actual behavior:** [What actually happened]

Command + Shift + P creates a new pull request.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always.

**Comment by shiftkey** [comment]
@dbchristopher thanks for the report.

This has been fixed in #2278 and will be available in the next update.
