### ISSUE TITLE
"Github desktop failed to launch"

### ISSUE THREAD

**Issue by francinirc** [desktop/desktop#2316]
<img width="724" alt="screen shot 2017-07-24 at 15 09 57" src="https://user-images.githubusercontent.com/14060721/28537707-34e4491c-7082-11e7-987c-6c3836b152c8.png">

**Comment by francinirc** [comment]
Running macOS Sierra 10.12.6

**Comment by shiftkey** [comment]
@francinirc can you download the latest version from desktop.github.com? This should have been fixed in `0.7.0` which we published last week.

**Comment by shiftkey** [comment]
See #1875 for the original issue.
