### ISSUE TITLE
question about OAuth scopes

### ISSUE THREAD

**Issue by mathieudutour** [desktop/desktop#2317]
Why does Github Desktop need `user` as an OAuth scope? Wouldn't `user:email` and `read:org` be enough?

| api call        | scope needed           |
| ------------- |:-------------:|
| `fetchRepository` | `repo` |
| `fetchAccount` | only using the field available with no scope |
| `fetchEmails` | `user:email` |
| `fetchCommit` | `repo` |
| `searchForUserWithEmail` | no scope |
| `fetchOrgs` | `read:org` |
| `createRepository` | i'd say `repo` but I'm not sure |
| `fetchIssues` | `repo` |
| `getFetchPollInterval` | `repo` |
| `fetchMentionables` | `repo` |
| `createAuthorization` | using username and password so no scope |

**Comment by shiftkey** [comment]
@mathieudutour the only thing that comes to mind is being able to update the user's profile (for example, adding a new email address) in the future. Changing the scopes in the future requires handling rejection and re-authing the app for the user, so I think we just played it safe here.

**Comment by mathieudutour** [comment]
Got it
