### ISSUE TITLE
Why can't I publish responsitary to github

### ISSUE THREAD

**Issue by kodekahu** [desktop/desktop#2321]
Hi everyone, I am making a repository called Cubix. When I try to publish it the program says Repository publish failed or something like that. Thank you for your help.

**Comment by kodekahu** [comment]
I think it might have been Repository creation failed.

**Comment by shiftkey** [comment]
@kodekahu could you have a look at [the logs files](https://github.com/desktop/desktop/blob/master/docs/installation.md#log-files) to see if there was any additional information around the error?

**Comment by joshaber** [comment]
Thank you for your issue!

We haven't gotten a response to our questions above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
