### ISSUE TITLE
Create new branch from current branch

### ISSUE THREAD

**Issue by jamland** [desktop/desktop#2322]
Can you please make Create New Branch from current branch instead of master?

Looks more logical to me. 
I do it wrongly from master all the time =\9

**Comment by shiftkey** [comment]
@jamland I'm not sure I follow. If you choose **Branch** | **New Branch** from the menu, and your current branch isn't the default branch, you should see a dialog like this:

<img width="454" src="https://user-images.githubusercontent.com/359239/28569396-fa61f6f2-710f-11e7-8706-8aafd1fa75da.png">

Can you confirm what you're seeing, and attach a screenshot if it's something different? Thanks!

**Comment by jamland** [comment]
hey @shiftkey! 
I always see master branch default when click **New Branch**. Here is example:

<img width="246" alt="screen shot 2017-07-25 at 5 18 09 pm" src="https://user-images.githubusercontent.com/188568/28576717-4777d644-715d-11e7-9b24-ef5f749f8886.png">

<img width="430" alt="screen shot 2017-07-25 at 5 16 30 pm" src="https://user-images.githubusercontent.com/188568/28576654-1a2582a4-715d-11e7-9b44-ff8d19840575.png">

**Comment by shiftkey** [comment]
I don't have strong feelings on this, but I think we should keep the first item focused.  But maybe we could invert the order of these items so that the current branch is favoured in this situation?

cc @desktop/core for feels

**Comment by shiftkey** [comment]
@jamland after all the discussions in #2330, I decided to close it out because I still prefer the original intent of this feature (favouring the default branch to encourage the GitHub flow).

Thanks for the feedback around this, and if you've got any more suggestions please open a fresh issue!

**Comment by jamland** [comment]
Ok. I understand your idea
I will try to follow github way in my routine =)
