### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by jpike88** [desktop/desktop#2323]
Probably the same issue as this:

Microsoft/vscode#7426

Unable to update, clicking restart now just closes it and it doesn't actually update.

**Comment by jpike88** [comment]
This is after changing to another admin user. Probably user ownership related but I'm going insane trying to fix it.

**Comment by shiftkey** [comment]
@joshaber not being familiar with Squirrel.Mac, are there some known log files or locations we can poke at to isolate this issue better?

**Comment by shiftkey** [comment]
@jpike88 which version are you currently updating from? And My gut feeling goes to this old issue which talks about updates and running as an admin user https://github.com/Squirrel/Squirrel.Mac/issues/131 but I'd like to dig up the log failures and confirm we're on the right track.

**Comment by joshaber** [comment]
Yep, this is almost certainly related to the Squirrel bugs around privilege escalation. The good news is that they've been fixed, the bad news is that we need to wait for some Electron updates before we can pick up the fix.

**Comment by jpike88** [comment]
I'm in version 0.7.0

This was after my main (admin) account got corrupted and I had to go into recovery mode to make another admin.

**Comment by jpilgrim** [comment]
I have the same issue. Update did not work on any version, latest version which I tried is 0.6.2.
The application is installed in the "Applications" folder, and the user I'm logged in with has no right access to that folder. Other update tools request an admin password during the update process though.

**Comment by jpike88** [comment]
This is beginning to drive me up the wall. It should be treated as a serious bug.

output from /Users/myUserName/Library/Caches/com.github.GitHubClient.ShipIt/ShipIt_stderr.log


`
2017-07-28 10:57:59.093 ShipIt[20037:2412245] Installation error: Error Domain=SQRLShipItRequestErrorDomain Code=2 "Could not read update request" UserInfo={NSLocalizedDescription=Could not read update request, NSUnderlyingError=0x7fc093f0c7d0 {Error Domain=NSCocoaErrorDomain Code=260 "The file “ShipItState.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/root/Library/Caches/com.github.GitHubClient.ShipIt/ShipItState.plist, NSUnderlyingError=0x7fc093f0c660 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}
2017-07-28 10:57:59.095 ShipIt[20037:2412245] ShipIt quitting
`

**Comment by jpike88** [comment]
whose ass do I have to kick? Is it Squirrel's responsibility to push it in a release, or a submodule electron uses?

**Comment by joshaber** [comment]
@jpike88 part of your comment was deleted as a violation of the [Desktop Code of Conduct](https://github.com/desktop/desktop/blob/master/CODE_OF_CONDUCT.md)
as it is unprofessional conduct.

To answer your question, [a PR's](https://github.com/electron/electron/pull/10071) already landed in Electron updating Squirrel.Mac. We now need to wait for the next release of Electron so that it includes the fix.
