### ISSUE TITLE
Show "Verified" badge

### ISSUE THREAD

**Issue by Plasmmer** [desktop/desktop#2339]

**Comment by donokuda** [comment]
Hi @Plasmmer! Are you referring to showing a badge when a commit has been verified by a contributor's GPG key?

**Comment by Plasmmer** [comment]
@donokuda
> Hi @Plasmmer! Are you referring to showing a badge when a commit has been verified by a contributor's GPG key?

Surely :smile:

**Comment by donokuda** [comment]
> Y. Showing it in the commit list and in the commit page.

🆒! Then it looks like this could be something grouped with https://github.com/desktop/desktop/issues/78. We don't have a timeline on this yet, but it's something I imagine we would tackle sometime in the future.

**Comment by joshaber** [comment]
Since this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md) and we already have #78 open tracking PGP support generally, I'm gonna close this.

**Comment by steveward** [comment]
I'm going to consolidate this with https://github.com/desktop/desktop/issues/78 and drop the feedback @DaniellMesquita gave into that issue.
