### ISSUE TITLE
[Suggestion] iOS releases

### ISSUE THREAD

**Issue by Plasmmer** [desktop/desktop#2343]

**Comment by j-f1** [comment]
Unfortunately, Electron doesn’t support iOS. Also, what do you envision the use cases for the app to be? It’s rather difficult to edit code on a mobile device.

**Comment by Plasmmer** [comment]
Do you really think is difficult code on mobile device in plain 2017?
Read this: https://www.scirra.com/blog/186/construct-3-on-mobile

**Comment by donokuda** [comment]
Hi @Plasmmer!

At this moment we don't have plans to support iOS with GitHub Desktop. However, I do imagine in the future that if we do, it would be a separate project and codebase.

I'm going to close out this issue for now but I appreciate the interest in supporting mobile platforms!
