### ISSUE TITLE
Untrusted server

### ISSUE THREAD

**Issue by Plasmmer** [desktop/desktop#2346]
<img src="https://image.prntscr.com/image/xMGyfHGxTpGYkNVNZF3yBw.png"/>

**Comment by shiftkey** [comment]
@Plasmmer a couple of questions:

 - are you running any sort of proxy tool like Fiddler?
 - if you open a browser to `https://api.github.com/zen` what do you see for the browser's security information?

Here's mine on Chrome:

<img width="435" alt="screen shot 2017-07-27 at 9 58 53 am" src="https://user-images.githubusercontent.com/359239/28671242-57ceaecc-72b2-11e7-8e55-009a58f7d45d.png">

**Comment by Plasmmer** [comment]
- Not
- `Keep it logically awesome.`

**Comment by shiftkey** [comment]
As modern day browsers are hiding away the actual certificates they see (sigh!), could you open the URL in Internet Explorer and follow these steps:

 - Click the padlock icon in the URL bar

<img width="805" alt="screen shot 2017-07-27 at 10 32 17 am" src="https://user-images.githubusercontent.com/359239/28672795-1ad4b16a-72b7-11e7-98e5-03b66be34abc.png">

 - Click **View Certificates**

<img width="721" alt="screen shot 2017-07-27 at 10 32 22 am" src="https://user-images.githubusercontent.com/359239/28672801-201b35b8-72b7-11e7-9e06-1060d6cf56ee.png">

 - Attach screenshots of the **General** and **Certificate Path** tabs, so I can see what certificates you are seeing:

<img width="419" src="https://user-images.githubusercontent.com/359239/28672899-65e90e62-72b7-11e7-9abd-0259f19a761d.png">
<img width="417" src="https://user-images.githubusercontent.com/359239/28672904-68e97a66-72b7-11e7-85e1-6f80e2ca796d.png">

**Comment by joshaber** [comment]
Thank you for your issue!

We haven't gotten a response to our questions above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by huchim** [comment]
Hi, I'm receiving same error. I created `GitHubDesktop.exe.config` and `Update.exe.config` and I'm using [Handcrafted FreeProxy](http://www.handcraftedsoftware.org/index.php?page=download&op=getFile&id=2&title=FreeProxy-Internet-Suite).

I configured GIT_SSL_NO_VERIFY (`http.sslverify=false`) variable and `git.exe` works perfectly, but int GitHub Desktop there is no option.

```xml
<configuration>
  <system.net>  
    <defaultProxy>  
      <proxy  
        usesystemdefault="True"  
        proxyaddress="http://10.66.109.13:8096"
        bypassonlocal="True"  
      />  
    </defaultProxy>  
  </system.net>  
</configuration>
```

**Comment by shiftkey** [comment]
@huchim please open a fresh [bug report](https://github.com/desktop/desktop/issues/new?template=bug_report.md) and also include this information:

 - whether you have also set `http.proxy`, which is the recommended approach to tell Git where to find a proxy server: https://github.com/desktop/desktop/issues/7034#issuecomment-470765578
 - where you set `http.sslverify` (this disables SSL/TLS checks, which is different to the proxy issue)
 - whether you are impacted by SChannel issues that can also be involved when working with proxies, as outlined here: https://github.com/desktop/desktop/blob/development/docs/known-issues.md#certificate-revocation-check-fails---3326
