### ISSUE TITLE
[Suggestion] Consider revisions as updates

### ISSUE THREAD

**Issue by Plasmmer** [desktop/desktop#2349]

**Comment by shiftkey** [comment]
@Plasmmer please provide more information.

**Comment by Plasmmer** [comment]
Every new commit/pull request merged, the Desktop app gets updated?

**Comment by shiftkey** [comment]
In terms of updating your repository state, we already perform:

 - background fetching to periodically fetches changes from the remote
 - after fetching we will fast-forward branches you're not currently on in the background.

No need to be interrupted or do anything explicitly. We felt this was more friendly than notifying and making users do things manually.

Is that what you were thinking of, or are there other situations you had in mind?

**Comment by mathieudutour** [comment]
I think he was talking about releasing a new update for GitHub Desktop on every push to master
