### ISSUE TITLE
怎么开展项目分支？

### ISSUE THREAD

**Issue by chengjinshengtaichanyejituan** [desktop/desktop#2352]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by tierninho** [comment]
@chengjinshengtaichanyejituan please fill out the template so we can help you better. thanks.
