### ISSUE TITLE
@-mention suggestion menu does not go away automatically

### ISSUE THREAD

**Issue by cheshire137** [desktop/desktop#2358]
When I use an `@` sign in the commit title, a suggestion will come up and not go away until I hit Esc. It seems like an unaccepted suggestion should go away when the field loses focus, like when I click the commit or undo button.

![suggestion-doesnt-go-away-github-desktop-loop](https://user-images.githubusercontent.com/82317/28735027-1af3cb34-73a9-11e7-8a6a-34399e933027.gif)

I'm using version 0.7.0 in macOS.

**Comment by iAmWillShepherd** [comment]
I think we will replicate what dotcom does and remove the suggestion box when the text box looses focus and reshow it when the user continues typing.

**Comment by donokuda** [comment]
> I think we will replicate what dotcom does and remove the suggestion box when the text box looses focus and reshow it when the user continues typing.

👍 

For example:
![type-key-to-continue](https://user-images.githubusercontent.com/1174461/28797440-0558701e-75dd-11e7-9432-ad7135a0935b.gif)

**Comment by iAmWillShepherd** [comment]
👀 at that GIF action!
