### ISSUE TITLE
Create Pull Request and Pull have same hotkey (macOS)

### ISSUE THREAD

**Issue by JamesToohey** [desktop/desktop#2362]
### Description

The hotkeys are CMD+Shift+P for both, seemingly it always opens a PR and never pulls

<img width="200" alt="screen shot 2017-07-31 at 10 52 08 am" src="https://user-images.githubusercontent.com/2288242/28759279-b6160122-75de-11e7-8c77-40be8b419d91.png">
<img width="243" alt="screen shot 2017-07-31 at 10 52 12 am" src="https://user-images.githubusercontent.com/2288242/28759280-b616d8ae-75de-11e7-9961-257cfd589f7d.png">

### Version

**GitHub Desktop version:** 0.7.0

**OS version:** 10.12.6

**Expected behavior:** CMD+Shift+P to Pull, new hotkey for opening a PR

**Comment by j-f1** [comment]
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #2274, and has been fixed in #2278.

**Comment by JamesToohey** [comment]
Ahh no worries :) I missed those
