### ISSUE TITLE
No support for multiple windows (like old desktop version)

### ISSUE THREAD

**Issue by andyfleming** [desktop/desktop#2363]
There doesn't seem to be support for multiple windows like old desktop version. This is helpful for workflow sometimes (in my experience).

-----

Using GitHub Desktop Beta Version 0.7.0

**Comment by iAmWillShepherd** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our current roadmap.

I'm going to add the future-proposal label to this issue and close it out so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by andyfleming** [comment]
Thanks @iAmWillShepherd. Let me know in the future if you need any more details around a user's workflow with multiple windows.

**Comment by iAmWillShepherd** [comment]
Actually, feel free to add them anytime. Would be super helpful if you did it sooner since it gives us more time to think about it.

**Comment by ericdrobinson** [comment]
I frequently work with multiple projects (and sometimes multiple branches within a single project) simultaneously. The multiple project/branch workspaces are split across virtual desktops (macOS Spaces). Having to drag a single window across all different contexts is painful. What's more, even switching between branches when testing a feature in two separate local repo clones (A/B testing, etc.) can be a headache when having to constantly switch branches back-and-forth within the single-window GitHub Desktop.

This is a pretty large missing feature when compared with legacy (at least on macOS).

**Comment by andyfleming** [comment]
Similarly for me, when working in a project that has a client-side and server-side repo, I like to keep them both open in separate windows. The other use case for me is when working with 2-3 microservices to deliver a feature.

With all of the above, I like to keep 2-3 repo windows open. I use it partly for quickly seeing what changes are uncommitted in which projects. Beyond that though, it would be brutal to flip back and forth between projects all the time in the app.
