### ISSUE TITLE
Add an upstream to forked repositories

### ISSUE THREAD

**Issue by j-f1** [desktop/desktop#2364]
### Description

Currently, cloning a forked repository adds an `origin` remote linking to the fork on GitHub. However, there is no way to fetch changes from the parent, because no remote is added for the parent.

### Version

**GitHub Desktop version:** 0.7.0

**OS version:** macOS 10.12.3 (16D32)

### Steps to Reproduce

1. Fork a repo on GitHub
1. Clone the fork with GitHub Desktop
1. Run `git remote` on the command line

**Expected behavior:** Two remotes are present, with `origin` linking to the fork and `upstream` or *`username-of-parent-repo`* linking to the parent repo

**Actual behavior:** Only the `origin` remote is present

**Reproduces how often:** Always

**Comment by iAmWillShepherd** [comment]
Thanks for creating this issue. We actually already have this on our [roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md) for v1.1, but didn't have an issue for it yet.

**Comment by joshaber** [comment]
Scope for 1.1:

* Add an `upstream` remote to forked repositories
* Include in the periodic fetch

Designs TBD

**Comment by joshaber** [comment]
Is this something we'd do silently and automagically, or would we ask the user, similar to LFS setup?

<img width="422" alt="screen shot 2017-09-05 at 2 54 32 pm" src="https://user-images.githubusercontent.com/13760/30077658-86fc47d8-924a-11e7-9d94-9e27faa2b952.png">

**Comment by j-f1** [comment]
I think it should be automatic since they don’t have to use the remote if they don’t want to, and it shouldn’t cause any issues, unlike LFS which requires that you pay for storage space if you use too much.

**Comment by joshaber** [comment]
I'm leaning that way too. The only case that would cause problems is if they already have an `upstream` remote configured to something else. I gotta think those cases would be vanishingly rare tho.

**Comment by juninhoojl** [comment]
Reaberto
