### ISSUE TITLE
the linter has forsaken our event handlers

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#2371]
It'd be nice to see if we can get our linters to catch scenarios like #2368.

I thought this was already in place but maybe it regressed?

**Comment by iAmWillShepherd** [comment]
This may have been regressed when I integrated prettifier. I removed a bunch of linting rules.

**Comment by iAmWillShepherd** [comment]
I suppose so. My first thought was that I did something given that I was the last person to play with the rules.

**Comment by iAmWillShepherd** [comment]
Gonna close this out since @j-f1 is doing stuff around linting in #2405

**Comment by j-f1** [comment]
Is this fixed, or should I try to include it in my PR?

**Comment by iAmWillShepherd** [comment]
@j-f1 try to include it in your PR please, that seems like the perfect place for it given you are switching us to a different tool.

**Comment by j-f1** [comment]
Could you reopen this then? Since this requires a new rule, I think that this would be a good fit for a separate PR.

**Comment by j-f1** [comment]
Should the rule throw on this code?

```ts
class Foo extends React.Component {
  onMyEvent() {}
}
```

If so, are the criteria:

- is an ordinary method (not `onMyEvent = () => {}`)
- in a class extending `React.Component`
- **and** starts with `on`?

**Comment by j-f1** [comment]
Ping @desktop/core?

**Comment by joshaber** [comment]
It should throw on code like:

```typescript
class Foo extends React.Component {
  public render() {
    return <Thing onWhatever={this.onWhatever}/>
  }

  private onWhatever() {
    
  }
}
```

More descriptively, if a method is passed to a component, it should be bound, preferably using an arrow function.

If basing it on whether the method is passed to a component is too tricky (I really have no idea), then making it a heuristic based on `on*` is better than nothing 👍

**Comment by j-f1** [comment]
@joshaber Does this one look better?

https://astexplorer.net/#/gist/1a7060342476c3bd5a26f4b3b2ac1796/b9b490daeccb30bfffb8ad457c6641788fdd7c23

```js
const Foo = class extends React.Component {
  render() {
    return <Bar onMy={this.onMyEvent} onOther={this.onMyOtherEvent} />
  }
  onMyEvent() {}
//^^^^^^^^^
//onMyEvent is not bound, but it was passed to <Bar /> in the `onMy` prop at 3:27
  onNotPassedToAComponent() {}
  onMyOtherEvent = () => {}
}
```

**Comment by joshaber** [comment]
That looks great 🤘

**Comment by j-f1** [comment]
Found it: [`react-this binding-issue`](https://github.com/Microsoft/tslint-microsoft-contrib/blob/b720cd9827a13c2878d304193544a5b030953ecb/src/reactThisBindingIssueRule.ts). For some reason it’s not working. 😕

I’ve added the rule linked above to the next episode of ESLint integration.
