### ISSUE TITLE
update cleaning up old git.exe when it shouldn't

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#2373]
### Description

@NickCraver reported on Twitter that he encountered this Git error, which is a generic and questionable message when we can't resolve the packaged Git:

![](https://user-images.githubusercontent.com/359239/28799857-99b793b4-7620-11e7-9376-0a71f545a8bf.jpg)

However after this he hasn't been able to launch Desktop at all. No errors, no logs, just silence.

![](https://cloud.githubusercontent.com/assets/24247/18013839/02da86b0-6b8e-11e6-9202-a98eef7cce6f.gif)

### Version

**GitHub Desktop version:** 0.7.0 -> 0.7.2
**OS version:** Windows 10 I guess

### Steps to Reproduce

TBC, seems to be something like this:

 - Open app running 0.7.0
 - Update app to 0.7.x (latest version) (in background? or manually?)
 - Leave app open, keep doing Git things
 - :boom:

**Expected behavior:** The current version's bits are still on disk until the app is closed, and cleaned up In The Future™

**Actual behavior:** Files related to the running app were cleaned up, and now the app doesn't launch. Not sure if these are related, let's assume so.

**Reproduces how often:** lol I have no idea

### Logs

`SquirrelSetup.log` is interesting:

![setup](https://user-images.githubusercontent.com/359239/28800030-4b842206-7621-11e7-835b-14311c49c67e.jpg)

It excluded `0.7.1` and `0.7.2` when cleaning up old versions, but not the running `0.7.0` version. Could this be related to us rolling out delta updates? [Full log is here](https://gist.github.com/NickCraver/5fbeedfaa316960b800e12cacdab22ce#file-squirrelsetup-log)

**Comment by NickCraver** [comment]
I captured the state of `\AppData\Local\GitHubDesktop` in a .7z (it's 217MB). If that's useful at all, happy to upload somewhere. Also of course happy to leave it broken and debug locally for a bit to prevent it from happening to others, just ping me!

**Comment by shiftkey** [comment]
I hate it when my psychic debugger is right:

<img width="671"  src="https://user-images.githubusercontent.com/359239/28800201-0ba78668-7622-11e7-9ea2-850dc2e7bc40.png">

<img width="653" src="https://user-images.githubusercontent.com/359239/28800214-19accbba-7622-11e7-9680-c33d055e5feb.png">

So delta updates maybe don't track the current running app? I'd need to try and reproduce this before I go down that rabbit hole.

**Comment by shiftkey** [comment]
@NickCraver

> If that's useful at all, happy to upload somewhere.

I'd love to look over the current state and see how it fits with my current theory. Feel free to DM me the link whenever you get around to uploading it - it's not a blocker for this.

**Comment by NickCraver** [comment]
Done!

**Comment by shiftkey** [comment]
@NickCraver end user question: looking at the logs, I can see the app tries downloads the update for `0.7.1` at 1pm local time:

```
2017-07-31 13:06:03> FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-0.7.1-full.nupkg
2017-07-31 13:06:06> ApplyReleasesImpl: Writing files to app directory: C:\Users\ncraver.STACKEXCHANGE\AppData\Local\GitHubDesktop\app-0.7.1
```

And then the 0.7.2 delta update downloads a few hours later:

```
2017-07-31 17:05:46> FileDownloader: Downloading url: https://central.github.com/api/deployments/desktop/desktop/latest/RELEASES?version=0.7.0&env=production&id=GitHubDesktop&localVersion=0.7.1&arch=amd64
2017-07-31 17:05:46> FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-0.7.2-delta.nupkg
```

Did you have Desktop running the whole afternoon? Or was it closed (for whatever reason) at some point in the afternoon that might have actually performed the update?

**Comment by NickCraver** [comment]
Open since at least last night, probably a few days at least...been working on Exceptional. It's in a Parallels VM so it'd have paused during MacBook sleep over night, but up since this morning at ~6pm EST.

**Comment by shiftkey** [comment]
@NickCraver another end user question - did you have Desktop pinned to your taskbar?

I've been able to reproduce #2374 just now and I wanted to see whether that might explain why you weren't able to launch the app after updates were applied. This is separate to the issue about updates interfering with the running app, but I want to confirm you still had a working installation at the end, and the broken shortcut would explain why nothing was happening...

**Comment by shiftkey** [comment]
Poking around at the on-disk files that Nick provided, it looks like the original `app-0.7.0` install was left in a partial state, with `resources/app` containing 4 files and no Git installation. The root folder for this version did have the `.dead` file that Squirrel.Windows uses to signal when a version can be cleaned up, but if the app was still running at that point it shouldn't have been removing files in the first place.

**Comment by shiftkey** [comment]
My working theory on this is:

 - version `0.7.0` is launched, and checking for updates in the background
 - update `0.7.1` is available, app detects this
 - app downloads and unpacks new version, cleans up versions older than `0.7.0`
 - app prompts user to restart, user dismisses and keeps working
 - app continues checking for updates in background
 - update `0.7.2` is available, app detects this 
 - app downloads and unpacks new version, cleans up versions older than `0.7.1`
 - `git.exe` is removed, current program is now unusable

One way we could avoid this trap is to stop checking for updates (currently every 4hrs) once an update is found and ready for restarting. That seems reasonable, right @desktop/core?

**Comment by joshaber** [comment]
Yeah, I think that's reasonable 👍 The downside is that we have a messed up updated that goes out, they now have to do the download + restart cycle twice. But that's worth it IMO to avoid breaking the app out from under users.

**Comment by shiftkey** [comment]
> The downside is that we have a messed up updated that goes out, they now have to do the download + restart cycle twice.

I'm okay with this. Looking at the stats reported, the majority of people are still on 0.7.0.

> But that's worth it IMO to avoid breaking the app out from under users.

Yep, I'd rather an app that can be left running for days/weeks without trouble because Stuff Just Works™.
