### ISSUE TITLE
Add ability to remove or clone all missing repositories

### ISSUE THREAD

**Issue by TheGrimSilence** [desktop/desktop#2375]
### Description

Often times a developer will have many projects. Sometimes they may delete or rename projects and project folders and forget to update them in GitHub Desktop. Within the app-menu under `Help` or `File`, should exist an option called `Cleanup Desktop...` with the accelerator `CmdOrCtrl+Alt+C`.

### Behavior

Upon firing `Cleanup Desktop...` GitHub Desktop should run through all repositories that have been added to the app and return a list of missing repositories. Once finished, GitHub Desktop should `popup` a `dialog` displaying the list and give the user the option to run through the list and click to either `Clone`, `Remove`, or `Relocate` the individual repositories.

**Comment by iAmWillShepherd** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our current roadmap.

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by gingerbeardman** [comment]
Would you accept a PR?

**Comment by shiftkey** [comment]
> Would you accept a PR?

It's been a while since we last looked at this, so it'd be nice to have @desktop/core and @desktop/comrades do a "gut check" on what's been proposed, and see if they have any new thoughts on this from a workflow perspective.

**Comment by billygriffin** [comment]
@TheGrimSilence Thanks for the suggestion! Given that we haven't heard this as a pain point from many other users and there was a really nice identification of which repos have issues that shipped in https://github.com/desktop/desktop/pull/4258, I'm going to remove `future-proposal` here. If we see this come up as something that's causing issues for others we're happy to reconsider in the future. Thanks again. 😄
