### ISSUE TITLE
Add ability to create Issues within GitHub Desktop

### ISSUE THREAD

**Issue by TheGrimSilence** [desktop/desktop#2376]
### Description

When noticing an issue or wanting to add an enhancement, users shouldn't have to go out of their way to add one via the GitHub website and then traverse to the repository and issues section. Within the `app-menu` under `Repository` should exist an option called `Create Issue...` with the `accelerator` `CmdOrCtrl+Alt+I`. There are a few ways you could go about this:

- An option within the `app-menu` called `Create Issue...`
- New `sidebar` field called `Issues`

### Behavior

Upon firing `Create Issue...` GitHub Desktop should automatically `GET` the available labels from the repository on GitHub and display the available labels if the user is either the owner or contributor. If the user simply cloned the Repository and is neither contributor nor owner, then GitHub Desktop should only allow the creation of plain issues. For additional functionality, GitHub Desktop could display an `Issues` panel inside of the Sidebar showing all issues and their respective labels. Possibly add a new display to the content area just for issues and their comments and status updates. Issues within the `Issues` panel would display similar to that of the `History` panel in that it would show a list of commits with filter bar to display either open or closed or search via labels.

### Display

If the panel option is chosen then Issues should be displayed similar to Commits. Each Issue should display the user image to the left, the title with a hyphen and issue number in blue, the author under the title preceded by how long ago it was created, and at the cost of being slightly thicker than a commit: labels should be displayed under the author.

**Comment by iAmWillShepherd** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our current roadmap current roadmap.

I added the future-proposal label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by Baneeishaque** [comment]
Any plan to implement this feature?

**Comment by Rexogamer** [comment]
Any plans?

**Comment by tierninho** [comment]
@Rexogamer We’re considering this as part of #2376 . Please follow along there.

**Comment by Rexogamer** [comment]
@tierninho you just linked to this suggestion

**Comment by MakePixelsWork** [comment]
Closed more than 2 years ago. Is this going to become part of the Desktop version? Its super handy to track and resolve issues in one central development area.

**Comment by julienreszka** [comment]
Can we expect this for 2021 ?

**Comment by Gabriel-gn** [comment]
+1 this. I love github desktop as it is very simple to track development without needing a web browser to distract me from work. Im using gitscout for issue tracking but would love issue tracker integrated with github desktop

**Comment by billygriffin** [comment]
Hi folks, we're looking at a more tightly scoped and limited version of this in #8989, so I'm going to remove `future proposal` here. Please feel free to weigh in over there if you have additional context that would be helpful as we explore this further. Thanks!

**Comment by VishalShingote-gep** [comment]
@iAmWillShepherd  can you please add one simple search box for file search while selecting and committing.
Thank You

**Comment by kaanchan** [comment]
This feature currently exists in the mobile app and allows repository maintainers to respond quickly and efficiently to respond to discussions and updates. Would be great to have the same time of centralized and responsive functionality in the desktop version.

**Comment by vgavinash** [comment]
Github desktop still does not ve this feature. Its pending from a long time.

**Comment by faniabdo99** [comment]
Are we doing this or what? especially now with the GitHub projects feature this can make a huge difference.

**Comment by vgavinash** [comment]
Anyone hearing??
