### ISSUE TITLE
Override / Customize the Repo Label

### ISSUE THREAD

**Issue by masteroleary** [desktop/desktop#2380]
It is very difficult for me to select from the correct repository because they are labeled according to the directory name that the repo resides in. This is often not a descriptive folder.

For example, for a project i might have different versions.
MyProject.com > WebForms (current version)
MyProject.com > DotNetCore (v2 in development)

The Github desktop will call these repos WebForms and DotNetCore
It should allow me to set the label of the repo to something of my choosing.
In this example I could call the repos MP WebForms and MP Core. Regardless of how I would choose to label them, it would be more descriptive to me.
![capture](https://user-images.githubusercontent.com/476827/28836386-8adcc5bc-769d-11e7-9f31-076c3b4cfd38.JPG)

**Comment by iAmWillShepherd** [comment]
Closing this because issue #1929 captures your issue. If you have any further comments, please add them there.

🙇
