### ISSUE TITLE
Moving the commit actions to a context menu

### ISSUE THREAD

**Issue by donokuda** [desktop/desktop#2382]
Copying and pasting [my comment](https://github.com/desktop/desktop/pull/2045#issuecomment-319469090) here:

> 
> > The reasoning was that I wanted to separate out actions from commit information.
> 
> I've been Thinking About This UX and I'm not sure if the commit summary is the appropriate place for these actions.
> 
> We currently use a context menu for these types of actions in other places such as the changed files list:
> 
> <img src="https://user-images.githubusercontent.com/1174461/28839292-df7f0148-768e-11e7-9558-60cce5dbd29e.png" width="300" />
> 
> And based on that, I feel like right-clicking on the commit list is a better place for these actions to live:
> 
> <img src="https://user-images.githubusercontent.com/1174461/28842231-8afc2c04-7698-11e7-9ef2-418cf5101d26.png" width="250" />
> 
> Couple of reasons for my thinking:
> 
> 1. It's an interaction we currently use in the app
> 2. We won't be conflating the commit summary section with more UI elements
> 3. I wouldn't consider the actions that we are surfacing apart of a core-workflow. They're actions you would take in special situations (reverting, copying SHA's for cherry-picking or checking out, etc)
> 
> That said, I don't believe my concerns are reasons to hold up this PR given that the main functionality is implemented here, but if we agree on moving these to the commit list I'm more than happy to make that change in a subsequent PR.

This might be worthy of a discussion if anyone has strong feels against moving the actions into a context menu.

**Comment by joshaber** [comment]
I'm a little concerned for discoverability, but I'm down to try it out and see if folks have trouble finding it 👍

**Comment by joshaber** [comment]
And would we wanna scope for this 1.0? I'd lean towards yes?
