### ISSUE TITLE
Showing selected file count at the change list header

### ISSUE THREAD

**Issue by UgurAldanmaz** [desktop/desktop#2389]
### Description

It would be useful that showing selected file count at the change list header.

**Expected behavior:** Showing selected file count besides total, e.g.: 25 changed files (4 selected)

**Actual behavior:** Shows only changed file count, e.g.: 25 changed files

![image](https://user-images.githubusercontent.com/5686267/28935555-9856e212-788d-11e7-9121-8599c1a7d0de.png)

**Comment by iAmWillShepherd** [comment]
I'm not sure I understand this. Can you provide a bit more info here?

**Comment by UgurAldanmaz** [comment]
When not want to commit all changed files and select some of them, I would like to see how many file is selected.

For example, if there are 25 changed files and I select 5 files to commit then header text becomes like that: `25 changed files (5 selected)`
 
Sorry for my late reply.

**Comment by joshaber** [comment]
Ah, I see.

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
@UgurAldanmaz Thanks so much for the idea, and this is potentially interesting. However, we haven't seen this cause confusion for many other users (the differentiation between total files changed and selected files). We're doing more testing and interviews with users as part of our normal development process now, and we'll be sure to look out for this potentially as an issue, but for now we're going to remove `future-proposal` to indicate that it's not something we intend to work on. Thanks again for the suggestion and hope you'll continue to weigh in with other ideas! ❤️
