### ISSUE TITLE
The github cli command errors when used from Powershell

### ISSUE THREAD

**Issue by harveymonster** [desktop/desktop#2396]
### Description

Trying to launch github from powershell results in the following message:
'"C:\Users\Users\{username}\AppData\Local\GitHubDesktop\app-0.7.2\resources\app\static\..\..\..\GitHub Desktop.exe"' is not recognized as an internal or external command, operable program or batch file.

I noticed that the file is actually named GitHubeDesktop.exe (no space). I traced the problem to the following bat file which contained the space in the filename:
C:\Users\{username}\AppData\Local\GitHubDesktop\app-0.7.2\resources\app\static\github.bat

If I modify this file to remove the space, the github command successfully launches GitHub Desktop from powershell.

### Version

**GitHub Desktop version:** 0.7.2

**OS version:** Microsoft Windows [Version 10.0.14393]

### Steps to Reproduce

1. launch powershell
1. type "github"

**Expected behavior:** GitHub Desktop launches

**Actual behavior:** error message about no recognizing "GitHub Desktop.exe"

**Reproduces how often:** 100% of the time (until I changed the github.bat file)

**Comment by shiftkey** [comment]
I think this is due to the executable being renamed to enable delta updates for Windows, and us not updating the batch file. See #2239 for more details. I've opened #2397 to address this.
