### ISSUE TITLE
GIT和开源中国的组织设计不同怎么办

### ISSUE THREAD

**Issue by chengjinshengtaichanyejituan** [desktop/desktop#2398]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by tierninho** [comment]
"What is the difference between GIT and open source China's organizational design?"

**Comment by danqing** [comment]
it's more like: "the designs of git and the "open source china" organization are different. what should i do?"

doesn't seem to be an issue with github desktop though.

**Comment by shiftkey** [comment]
@danqing language barriers aside, this probably isn't the right place. Happy to help point the person to the right location if they have specific questions.
