### ISSUE TITLE
在GIT与开源中国上的组织设计怎样设计才能协调同步

### ISSUE THREAD

**Issue by chengjinshengtaichanyejituan** [desktop/desktop#2399]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by tierninho** [comment]
"How can the design of GIT and open source China be designed to coordinate and synchronize?"
