### ISSUE TITLE
Improve handling of Git tags

### ISSUE THREAD

**Issue by didenko** [desktop/desktop#2400]
### Description

Tags are not listed in any part of the GUI. It is not obvious (short of dropping in to a CLI) how to checkout a specific tag. Once a tag is checked out, the GUI shows the current state as a detached head on a SHA. It is correct, but not helpful.

As tags are now often used to designate releases, tag management and use in the GUI is IMHO a much needed improvement.

### Version

**GitHub Desktop version:** 0.7.2

**OS version:** macOS 10.12.6

### Steps to Reproduce

1. None. The functionality is missing

**Expected behavior:** Have tags present in the GUI equally as prominent as branches

**Actual behavior:** tag management is absent

**Reproduces how often:** inherent to the product

### Logs

N/A

#### Additional Information

N/A

**Comment by j-f1** [comment]
It might also be useful to list any tags in the commits list.

**Comment by shiftkey** [comment]
@didenko I think this is captured in a few other existing issues. Please feel free to add more details about your use cases there.

> It is not obvious (short of dropping in to a CLI) how to checkout a specific tag. 

See #257 for discussion around displaying tags alongside branches, similar to how GitHub the Website does it.

> Once a tag is checked out, the GUI shows the current state as a detached head on a SHA. It is correct, but not helpful.

See #788 for some workflow discussions around detached HEAD.

**Comment by shiftkey** [comment]
@j-f1 

> It might also be useful to list any tags in the commits list.

This can be done fairly easily from the command line but might be expensive to run on large repos:

> `git tag --contains {sha}`

This can also be done for local branches:

> `git branch --contains {sha}`

Would you mind opening a different issue to track this, so we can talk about that separate to this feature? There's probably more details here to think about feature-wise, even if the code to get this from a repo is straightforward...
