### ISSUE TITLE
Allow discarding changes with multiple files selected

### ISSUE THREAD

**Issue by mikeabiezzi** [desktop/desktop#2401]
### Description

Currently, you can only discard one file at a time. It would be convenient to select multiple files and discard the set at one time.

### Version

**GitHub Desktop version:** 0.7.2

**OS version:** macOS 10.12.6

**Comment by joshaber** [comment]
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/desktop/desktop/issues/2248. Please follow that issue for further updates.
