### ISSUE TITLE
Show which tags and branches are on a commit in the history list

### ISSUE THREAD

**Issue by j-f1** [desktop/desktop#2406]
As requested in https://github.com/desktop/desktop/issues/2400#issuecomment-320529738

Currently, there is no display of tags or other branches in the history list. It should be possible to see which commits have branches or tags on them.

Branches could be retrieved via `git branch --contains {sha}`, while tags could be retrieved via `git tag --contains {sha}`

Here’s a mockup of how it could look:

<img width="238" alt="screen shot 2017-08-06 at 16 35 12" src="https://user-images.githubusercontent.com/25517624/29006835-90880b44-7ac5-11e7-88f9-52e4c606919b.png">

**Comment by joshaber** [comment]
Yup, it's good to track this 👍 

Since this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md) I'm gonna label it and close it out.
