### ISSUE TITLE
Please Help Just Installed Github Desktop For WIndows 

### ISSUE THREAD

**Issue by jaycodingninja** [desktop/desktop#2408]
Hello all! I just downloaded GitHub Desktop for Windows. I currently have the GUI open.

On the Git page (https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) under "Installing on Windows" it says:

> Another easy way to get Git installed is by installing GitHub for Windows. The installer includes a command line version of Git as well as the GUI. It also works well with Powershell, and sets up solid credential caching and sane CRLF settings.

I cannot locate where the "command line version of Git" is located. The AppData directory "C:\Users\<user>\AppData\Local\GitHubDesktop\" where the GitHubDesktop .exe is installed does not have a file that contains the command line version of Git nor does it have Powershell.

Also, my PC does not recognize the "Git --version" request in cmd.

Do I need to download the official Git installer as well? Please help.

**Comment by shiftkey** [comment]
@jaycodingninja the command line version of Git referred to in the documentation isn't a part of the new version of Desktop. The back story on that is here, if you're curious: #340.

You have two options to get this command line experience:

 - You can download the latest [Git for Windows](https://git-for-windows.github.io/) release and install that. The new Desktop app has a "Open command prompt" which will open `cmd` and then use this version of Git for your command line interactions. We have plans to support other shell options based on what you have installed: #888 

 - the classic Windows app is still around, and the links are at the bottom of `desktop.github.com`. This classic app can be installed alongside the new Desktop app, but they are two distinct entities - your repositories from one won't appear in the other, for example.

**Comment by kimmiekim** [comment]
Hi I can't find the link to the classic Windows app. Can you please provide the link? I need to install git_shell. Thanks!

**Comment by tierninho** [comment]
@kimmiekim try here: https://github-windows.s3.amazonaws.com/GitHubSetup.exe

**Comment by kimmiekim** [comment]
exactly what i was looking for! thanks so much! @tierninho

**Comment by chilismaug** [comment]
Note that the amazon file link is a 32 bit app.
