### ISSUE TITLE
Can we have feature for an update from the specific branch?

### ISSUE THREAD

**Issue by Pritraj** [desktop/desktop#2410]
Request Feature
### Description

Can we have feature for an update from the specific branch,
Currently, I am using old version for this requirement
But compare to beta old is too much pain...

### Version

**GitHub Desktop version:** 0.7.2

**Comment by j-f1** [comment]
Thanks for contributing!

All new issues now require steps to reproduce (also called "repro steps") the
problem or the behavior you wish to see in GitHub Desktop. We do this so we can
be certain that we are understanding what it is you're describing and don't
prematurely close the issue or implement the wrong feature. If you need help
writing detailed repro steps, please see the [How Can I Contribute? document](https://github.com/desktop/desktop/blob/master/docs/contributing/README.md).

**Comment by steveward** [comment]
👋 @Pritraj. The `Update from <branch>` option in the previous version is the same as the `Merge into <current branch>` option in the beta. This can be accessed by going to the file menu and selecting `Branch`. When you click that you will see a dropdown with a list of branches that you can merge into your currently selected branch. Let us know if that isn't what you're looking for.

**Comment by Pritraj** [comment]
ok, thanks @steveward
