### ISSUE TITLE
How to stash the changes to change branch?

### ISSUE THREAD

**Issue by horsebuzz** [desktop/desktop#2412]
I could not figure out how to stash all my changes as i want to change branch.

**Comment by joshaber** [comment]
There's currently no way to stash changes in the app itself. To do that, you can either drop down to the command line and run `git stash`, or, as I often do, create a "Work in progress" commit which I then undo when I come back to the branch.

**Comment by LeoDupont** [comment]
@joshaber Is there any update about the stash feature?

**Comment by shiftkey** [comment]
@LeoDupont  please look over our upcoming support about managing uncommitted changes in Desktop - https://github.com/desktop/desktop/issues/6107#issuecomment-467197085 - this is currently available on beta for testing and feedback.

**Comment by LeoDupont** [comment]
@shiftkey That's great to hear! Thanks for linking the discussion.

**Comment by aacebo** [comment]
if you change branches from a feature branch it will stack uncommited changes, then just switch back to your branch.
