### ISSUE TITLE
fs.exists is obsolete

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#2415]
@JanPot pointed out while I was working on #2407 that `fs.exists` is obsolete: https://nodejs.org/api/fs.html#fs_fs_exists_path_callback

We have a couple of existing usages of this aside from that PR, where we use `fs.exists` just for the existence of the file (i.e. not reading or writing immediately afterwards), so we should port those to `fs.stat` as I think that's the closest match. But I could be convinced otherwise if someone else has a better suggestion.

Note that `fs.existsSync` is **not** obsolete, so we can keep using that in our tests.

**Comment by j-f1** [comment]
Also, `fs.existsSync` is not obsolete — the reason they got rid of `fs.exists` is because its callback style does not contain an error argument.

**Comment by shiftkey** [comment]
@j-f1 oops, yes, that's the one I meant to point out above. Thanks for the context!
