### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#2423]
Just stumbled upon this:

<img width="1414" src="https://user-images.githubusercontent.com/359239/29098557-4f1a59da-7ce3-11e7-88d4-eaa33a9f439c.png">

> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

Seems like we should [update this](https://github.com/desktop/desktop/blob/4c372df14e53888d423d401323a24e8d6a704f74/app/src/lib/source-map-support.ts#L36) to be less synchronous.

**Comment by joshaber** [comment]
There's a comment about this generally a little further down:

https://github.com/desktop/desktop/blob/4c372df14e53888d423d401323a24e8d6a704f74/app/src/lib/source-map-support.ts#L47-L51

So I'm not sure we have an option. Also note that this synchronous request only happens on dev builds.

**Comment by shiftkey** [comment]
![](https://user-images.githubusercontent.com/359239/29146538-f5b6a41c-7da4-11e7-8a87-c9f7f77fe213.gif)
