### ISSUE TITLE
Git Push - oversize file handle failure not throw exception

### ISSUE THREAD

**Issue by l0stb0y** [desktop/desktop#2427]
### Description

When pushing new repos to GitHub, I would like to see the file restriction exception handled via log entry and a continuation instead of the exception failure. Currently, the exception just stops the whole repo from going up, when a better process would be to log the failure and report on it. 

### Version

**GitHub Desktop version:** [v 0.7.2]

**OS version:** [Mac OS 10.12.6]

### Steps to Reproduce

1. commit large repo locally
2. hit the Publish button
3. wait for it to hit a too large file

**Expected behavior:** [At least tell me the file that caused the issue in the error message so I can quickly find it. But best would be to log the file(s) that wouldn't get transferred and let the upload continue]

**Actual behavior:** [stops the transfer and fails to move all the code to the repo
![screen shot 2017-08-09 at 12 12 30 pm](https://user-images.githubusercontent.com/1054677/29132119-25039d4a-7cfd-11e7-8571-7d0356ec7111.png)
]

**Reproduces how often:**[ 100%]

**Comment by joshaber** [comment]
Thanks for taking the time to contribute!

We're already tracking this generally in https://github.com/desktop/desktop/issues/997. Please follow that issue for further updates.
