### ISSUE TITLE
Suggested I pull before pushing but button doesn't allow it

### ISSUE THREAD

**Issue by cheshire137** [desktop/desktop#2431]
In version 0.7.2 in macOS, I hit the "Push origin" button and got this message:

![github_desktop](https://user-images.githubusercontent.com/82317/29145616-6dd6b46e-7d23-11e7-914f-04ccd840c06d.png)

However, when I hit the "Close" button in the dialog, the "Push origin" button remained the same instead of switching to say "Pull". Clicking "Push origin" again resulted in the same message being displayed. I did a `git pull` in my term and then was able to click the "Push origin" button successfully.

It seems like if the app knows to tell me "pull first, then push again," it would update the Push button to one that would pull instead.

**Comment by joshaber** [comment]
Great shout 👍

**Comment by timtribers** [comment]
I just hit this issue today too.  Is there any reason why this was closed, it's still happening in v1.6.1 on Windows?
