### ISSUE TITLE
GitHub Desktop: shows issues of original repository

### ISSUE THREAD

**Issue by varajan** [desktop/desktop#2435]
### Description

[Description of the issue]

### Version
GitHub Desktop version: 0.7.2
 `git rev-parse HEAD` 17a60c5950654d557a28f942a72fcf4255bb8e5b
OS version: MS Windows 10.0.1563

### Steps to Reproduce
1. Create a repository as user1 (in my case **_varajanko_**), name it bashSeaBattle;
2. Create few issues;
3. Using the Desktop application: download (clone) the repository;
4. Create a repository as user2 (in my case **_varajan_**), name it again bashSeaBattle, choose option to clone from github/varajanko/bashSeaBattle;
5. Create few other issues (other titles)
6. Delete local GitHub folder (%currentUser%/Documents/GitHub);
7. Relogin as user2 in Desktop application, clone repository;
8. Try to commit any changes, type `#` into the comment field.

**Expected behavior:** [What you expected to happen]
The application suggests issues from repository#1 (varajanko/bash..)
See 'issues_list.png' attach;

**Actual behavior:** [What actually happened]
The application suggests issues from current repository#2 (varajan/bash..)
See 'issues_list.png' attach;

**Reproduces how often:** 100%

### Logs
[logs.zip](https://github.com/desktop/desktop/files/1213916/logs.zip)
![issues_list](https://user-images.githubusercontent.com/30838113/29158835-2a759446-7db5-11e7-9543-257450532dfa.png)

**Comment by joshaber** [comment]
Huh, that's an interesting find @varajan! Thanks for reporting it!

**Comment by shiftkey** [comment]
I had a look at recreating this and wasn't able to trigger it.

Here's the steps I went through, which should recreate the issue as the issue store state (which the autocomplete form uses) is not tied to any sort of account state:

 - create two repositories on GitHub - https://github.com/shiftkey/repository-with-issues and https://github.com/shiftkey-tester/repository-with-issues
 - add two issues, with the owner name in the title to make it easier to confirm the source

<img width="354" alt="screen shot 2017-08-14 at 2 26 22 pm" src="https://user-images.githubusercontent.com/359239/29258392-92094a04-80fc-11e7-9386-4b6ee6e3e4c2.png">

 - open Desktop, view developer tools, clear `localStorage` and `window.indexedDB` contents
```
window.localStorage.clear();
indexedDB.webkitGetDatabaseNames().onsuccess = function(event) {
  Array.prototype.forEach.call(event.target.result, indexedDB.deleteDatabase.bind(indexedDB));
}
```
 - restart Desktop
 - sign into GitHub account, complete Welcome Wizard
 - clone `shiftkey/repository-with-issues`, wait a bit to see it fetch the data
 - remove repository through UI
 - clone `shiftkey-tester/repository-with-issues`, wait a bit to see it fetch the data

At this point I can auto-complete and see the expected `shiftkey-tester` issues.

<img width="390" src="https://user-images.githubusercontent.com/359239/29258477-40cf1258-80fd-11e7-9586-50d38e3d7ad2.png">

I can also see in the developer tools that the issues are keyed by two distinct repository IDs:

<img width="1440" src="https://user-images.githubusercontent.com/359239/29258500-8b09d038-80fd-11e7-9e09-27b00037b36f.png">


@varajan coming back to the original steps, these specific steps aren't clear:

> Create a repository as user2 (in my case varajan), name it again bashSeaBattle, choose option to clone from github/varajanko/bashSeaBattle;

Given we're talking about the `varajan` account, should this be `github.com/varajan/bashSeaBattle`?

> Relogin as user2 in Desktop application, clone repository;

It's not clear which repository you cloned here - if this is supposed to be `github.com/varajan/bashSeaBattle` as my comment above suggests then I think we've got the right behaviour.

**Comment by varajan** [comment]
It's not a bug. I was told to clear the "%User%\AppData\Roaming\GitHub Desktop" folder and to re-login to GitHub. Now it shows correct issues. 

Sorry.
