### ISSUE TITLE
allow for modifier keys to be used when selecting changed files

### ISSUE THREAD

**Issue by Secticide** [desktop/desktop#2439]
### Description

When using any git GUI (especially on projects where many changes are made not by the user - such as Unity in my case) I find there are alot of file changes, it would be useful to quick select / commit larger groups of files by using the the modifier keys 'ctrl' (or 'command') & 'shift'.

The expected behaviour would of course be that using 'ctrl' would add the clicked file to the current selection (or remove it if it's already selected) while 'shift' would add all files from the previously selected file to the clicked file to the current selection.

### Version

**GitHub Desktop version:** 0.7.3
**OS version:** macOS Sierra 10.12.6

**Comment by joshaber** [comment]
Thanks for opening this up!

What would shift or command selecting files do? Toggle the checkbox, show multiple diffs in the diff view, something else?

**Comment by Secticide** [comment]
Thanks for the fast response!

I would imagine it to work similarly to Google's Inbox when selecting emails, if you ctrl / command / shift clicked the tick-box; it would tick / untick the box, if you clicked generally on the selectable area, it would highlight it.

The main reason I raised the issue was that if you had 100 files that had been changed, and you only had a single file you wanted to commit, you would have to either:
* Make a copy of the file, discard all, copy the file back, commit,
* Discard, make the change again, commit,
* Right-Click discard all the 99 files you didn't want to commit, commit.

For speed of the app (depending on size of files etc), I would suggest only showing a single diff at any point - I've found with SourceTree that displaying multiple diffs just slows the process down further.

**Comment by joshaber** [comment]
>The main reason I raised the issue was that if you had 100 files that had been changed, and I only had a single file you wanted to commit, you would have to either:

You should be able to click the checkbox in the Changes header to uncheck all the files:

<img width="246" alt="screen shot 2017-08-10 at 10 52 41 am" src="https://user-images.githubusercontent.com/13760/29176523-0e2637b4-7dba-11e7-9571-bfaac065417d.png">

And then check the one file you do want to commit. Does that work for you?

**Comment by Secticide** [comment]
Yeah, that works for me perfectly.

I guess it's more of a workflow thing; if you're faced with a large number of files that have been added / changed / removed and you're not sure where the files are that you have changed, it's sometimes easier to remove the files that you haven't changed to give yourself a better view of the ones that you have.

Am I making sense here?

**Comment by joshaber** [comment]
Yeah, I can see how discarding changes if you're dealing with a large list could make it easier to find the change you're looking for. But I'm not sure if/how that relates to command or shift selecting files... what am I missing?

**Comment by Secticide** [comment]
Thanks again for the responses,

The command / shift selection capabilities would allow for the quick selection of files. Once the files are selected, the right-click menu would allow for quick access to discarding large number of files. Also, if you wanted to commit a large number of files; rather than individually clicking the tick-boxes on each of the files that you wish to commit, you could simply click-shift-click (the tick boxes) to have them 'ticked' and ready to commit.

Does that make things clearer?

**Comment by joshaber** [comment]
Ahhh, I think I get it now! Thanks for your patience.

So it sounds like this is partly captured by #2248, but larger in scope in that it also includes checking/unchecking changes.

**Comment by Secticide** [comment]
No problem, we got there in the end. This has definitely made me realise that I need to explain myself better in my next issue that I open.

Thanks!

**Comment by shiftkey** [comment]
> The expected behaviour would of course be that using 'ctrl' would add the clicked file to the current selection (or remove it if it's already selected) while 'shift' would add all files from the previously selected file to the clicked file to the current selection.

I believe this has been resolved with #4188 which was released in version 1.2.0, but I'll clarify that on macOS it's <kbd>⌘</kbd> and <kbd>Shift</kbd>, and on Windows its <kbd>Control</kbd> and <kbd>Shift</kbd>.
