### ISSUE TITLE
SSL error when publishing repo

### ISSUE THREAD

**Issue by Delano83** [desktop/desktop#2452]
I'm behind a firewall, trying to push a repository and getting this error:
fatal: unable to access '.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

[Version 10.0.14393]

![image](https://user-images.githubusercontent.com/17054064/29237906-2602bb04-7ef6-11e7-906b-0946d44c1c52.png)

Any help is appreciated.

**Comment by shiftkey** [comment]
@Delano83 we're using the SChannel APIs in Windows for validating certificates as part of pushing/pulling/fetching/cloning repositories in Git. 

> I'm behind a firewall,

Are you able to reach GitHub through your browser? If so, which browser? I'd love to understand more about your setup as we're deferring to the OS for validating certificates and we've had a couple of reports like this.

**Comment by shiftkey** [comment]
xref #2414

**Comment by Delano83** [comment]
@shiftkey 
- Yes I can access it through any browser (chrome, firefox, and IE)
- I run Windows 10
- I'm behind a pretty strong firewall

Is there a way to turn SSL off?

By the way, I can't push through the command line either...

**Comment by shiftkey** [comment]
> I'm behind a pretty strong firewall

Which firewall product? I wonder if there's a whitelist apps and confirm it's something outside the Desktop configuration that needs to be tweaked.

**Comment by shiftkey** [comment]
> By the way, I can't push through the command line either...

Which version of Git are you using?

```
$ git --version --build-options
```

If you're also using Git for Windows could you look to see what install options have been configured:

```
# run one of the following commands in cmd.exe
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"

# if all those fail, run Git Bash and try this
$ cat /etc/install-options.txt
```

**Comment by Delano83** [comment]
@shiftkey The firewall is custom coded for the company and is extremely powerful.
In the past, I was able to bypass those restrictions by setting strict-ssl to false. This does not seem to work anymore.

Git Version
git version 2.11.0.windows.3
built from commit: e11df2efb3072fe73153442589129d2eb8d9ea02
sizeof-long: 4
machine: x86

Configuration: 
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

Can I set strict ssl to false on desktop?

**Comment by shiftkey** [comment]
@Delano83 while I don't recommend doing this for various serious reasons, you can disable verifying certificates for the current repository like this:

```
$ git config http.sslVerify "false"
```

Or you can do this globally:

```
git config --global http.sslVerify "false"
```

Given that the issue seems to be specific to your setup, I'm not sure what else we can on the Desktop side.

**Comment by shiftkey** [comment]
> By the way, I can't push through the command line either...

As this isn't a problem specific to Desktop, and there is a workaround, I'm going to close this out.
