### ISSUE TITLE
Copying code copies the line status symbol as well

### ISSUE THREAD

**Issue by adamreisnz** [desktop/desktop#2454]
### Description

When copying code from the diff, it also copies the line status symbol (`+` / `-`) which forces you to then remove that from pasted code.

### Version

**GitHub Desktop version:** 0.7.2
**OS version:** OS X 10.11.5

### Steps to Reproduce

1. Copy code from diff that has changes to a file
2. Past the code
3. Observe that `-` or `+` symbol is pasted as well

![image](https://user-images.githubusercontent.com/490562/29243905-220856c6-7fff-11e7-8035-d2e8d91b9367.png)

![image](https://user-images.githubusercontent.com/490562/29243911-3894f070-7fff-11e7-85ff-cefb404b3262.png)

**Expected behavior:**
For the symbols not to be included in copy paste as is the case in the old version of Github desktop:

![image](https://user-images.githubusercontent.com/490562/29243912-538116a2-7fff-11e7-9785-4e8766e830c8.png)

**Actual behavior:**
They are included.

**Reproduces how often:** 
100%

**Comment by shiftkey** [comment]
@adamreisnz thanks for the report.

This was fixed in #2438 and will be available in the next update!

**Comment by adamreisnz** [comment]
Awesome thanks
