### ISSUE TITLE
Show dot on pending commit/changes on repository list

### ISSUE THREAD

**Issue by gencer** [desktop/desktop#2459]
### Description

Show a dot on updated repository when there is a pending changes to commit.

### Version

All.

**OS version:** Win10

**Expected behavior:** I should expect to show some sign of updated/pending notification

**Actual behavior:** empty.

**Reproduces how often:** All the time.

This is current behavior:
![image](https://user-images.githubusercontent.com/1711576/29263290-d190af4e-80e0-11e7-97ad-49540362f18e.png)

Lets say **api** repository has a pending commits. This would be good to see:

![image](https://user-images.githubusercontent.com/1711576/29263365-164f68f0-80e1-11e7-9a95-dd502cda6de3.png)

**Comment by shiftkey** [comment]
@gencer thanks for the suggestion!

We're tracking this in #678 - please add your feedback there!
