### ISSUE TITLE
Open with external editor runs batch files on windows

### ISSUE THREAD

**Issue by xt0rted** [desktop/desktop#2464]
### Description

Using the new **Open with external editor** feature results in `.cmd` files being run instead of opened in an editor.

I have VS Code installed, and the settings show it's the default editor, but the file isn't opened in it, nor are any others.

### Version

**GitHub Desktop version:** 0.7.3-beta3
**OS version:** Win10 CU

### Steps to Reproduce

1. Add a `.cmd` file to your repo
1. Right click on it and select `Open with external editor`
1. Watch the console open and the file run

**Expected behavior:** The file to open in the default editor of this type (for me it's Notepad/Notepad2) or the default editor selected in the application (VS Code in this case)

**Actual behavior:** The console opens and the file executes

**Reproduces how often:** Every time

### Logs

Nothing shows in the logs relating to opening/running the file.

#### Additional Information

None

**Comment by shiftkey** [comment]
There's two things here which I'll look into:

 - the previous `Open with external editor` behaviour uses `shell.openExternal` and not the work done in #2407:

https://github.com/desktop/desktop/blob/e3acdc1b1767b4b310a47495e74ddf7fcf92c077/app/src/main-process/main.ts#L289

This makes the menu item confusing - maybe we should rename that:

https://github.com/desktop/desktop/blob/e3acdc1b1767b4b310a47495e74ddf7fcf92c077/app/src/ui/changes/changed-file.tsx#L131-L135

 - looking at the repro steps, it might be executing the `.cmd` file by default, which is Not Great, Bob™

**Comment by shiftkey** [comment]
> I have VS Code installed, and the settings show it's the default editor, but the file isn't opened in it, nor are any others.

@xt0rted which settings is this? I'd like to confirm the steps to reproduce this.

I've looked under **Settings** | **Apps** | **Default apps** | **Choose default apps by file type** and I don't have a program registered for  `*.cmd`.

<img width="528" src="https://user-images.githubusercontent.com/359239/29300153-1ebead58-81b7-11e7-8b7d-9283682a24f9.png">

This then fails as expected:

<img width="637" src="https://user-images.githubusercontent.com/359239/29300164-2f47eeaa-81b7-11e7-9f7b-535ecd13555f.png">

**Comment by xt0rted** [comment]
@shiftkey that setting shows the same for me

![image](https://user-images.githubusercontent.com/831974/29300882-6d85e206-8146-11e7-8a4a-44e738d3799c.png)

In Explorer if I right click on the file and select Edit then it opens in Notepad/Notepad2. I think that's where I was thinking the default editor was set.

**Comment by shiftkey** [comment]
Like this?

<img width="375"  src="https://user-images.githubusercontent.com/359239/29301228-0e4d88f2-81be-11e7-8f8c-9da0e918d4d0.png">

**Comment by xt0rted** [comment]
![image](https://user-images.githubusercontent.com/831974/29301266-01814322-8149-11e7-9d5e-879e7b83d930.png)

**Comment by xt0rted** [comment]
This is what's listed in the classic control panel applet for `.cmd`

![image](https://user-images.githubusercontent.com/831974/29301374-af67a3be-8149-11e7-9898-13765c77ad44.png)

**Comment by shiftkey** [comment]
@xt0rted ah, the handler for the `EDIT` verb.  Electron passes `OPEN` for the verb when doing `ShellExecute`, and I thought we had a discussion about this somewhere but maybe I dreamed it:

https://github.com/electron/electron/blob/eb63bea87c299b3c440d6a36ccced3cc9653e1c4/atom/common/platform_util_win.cc#L308-L315

So we can't currently distinguish between OPEN and EDIT usages based on their extension.

**Comment by Aj-ajaam** [comment]
Shiftkey

**Comment by shiftkey** [comment]
@xt0rted could you have a look at what's in your registry for the `Open` verb for `.cmd`? While it's not related to the Open in Existing Editor changes I'd like to try and reproduce this so we can rush out a fix if needed alongside that.

[These instructions](https://superuser.com/a/266274) should help to confirm what I need to configure my machine.

**Comment by xt0rted** [comment]
Here's the `.cmd` branch exported.

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\.cmd]
@="cmdfile"

[HKEY_CLASSES_ROOT\.cmd\PersistentHandler]
@="{5e941d80-bf96-11cd-b579-08002b30bfeb}"
```

**Comment by shiftkey** [comment]
@xt0rted thanks for the help. I wasn't able to reproduce this on my dev environment but I was able to trigger this in a fresh VM.

@desktop/core I'd like to get this fixed - both the confusing menu item and the executing of cmd files when we shouldn't - before shipping the Open in External Editor feature. Pondering more on the fix today, will report back.

**Comment by xt0rted** [comment]
@shiftkey just checked and bash scripts are executed as well

**Comment by shiftkey** [comment]
@xt0rted `.sh` scripts?

**Comment by xt0rted** [comment]
Yup
