### ISSUE TITLE
Feature request: git remote add upstream <url>

### ISSUE THREAD

**Issue by nturaga** [desktop/desktop#2470]
### Description

I'm trying to use the github desktop app. I have my origin setup by default after cloning a repo.

But, I want to set up an upstream remote. I want to emulate, `git remote add upstream <URL>` on the github desktop client.

### Version

**GitHub Desktop version:** [0.7.2]

**OS version:** [10.12.6 (16G29)]

**Expected behavior:** I expect to be able to click on "Repository settings", and be able to add a remote. So, maybe a "new remote" button which leads to "remote name" and "remote url". 

**Actual behavior:** Feature does not exist.

**Comment by shiftkey** [comment]
@nturaga thanks for the suggestion! I've folded this into #1442 where we're tracking multiple remotes scenarios more broadly.

**Comment by gengjiawen** [comment]
@shiftkey Can we provide an option in clone dialog to also clone the upstream if a repo is forked. I think in most cases you would want to do this to sync the code with upstream.

**Comment by shiftkey** [comment]
@gengjiawen we implemented this in https://github.com/desktop/desktop/pull/3199 - please open a new issue if you're not seeing this work as expected!

**Comment by gengjiawen** [comment]
@shiftkey Thanks.
