### ISSUE TITLE
The revocation function is unable to check revocation for the certificate.

### ISSUE THREAD

**Issue by glenndevenish** [desktop/desktop#2471]
### Description

I am running behind a corporation that self-signs its certificates, which means that I get this issue when I try to push any changes.

    fatal: unable to access 'https://github.com/glenndevenish/[repo]/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

### Version

**GitHub Desktop version:** 0.7.2

**OS version:** Microsoft Windows [Version 10.0.10586]

### Steps to Reproduce

(You will probably be unable to reproduce since you have to be in the corporation, although any self-signing corp. might have the same issue)
1. Click publish branch
1. Error message pops up.

**Expected behavior:** Update to occur successfully

**Actual behavior:** Repo *was* created, but no files were created.

**Reproduces how often:** Every time.

### Logs

    2017-08-15T13:38:44.759Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.196s)
    2017-08-15T13:38:44.761Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
    fatal: unable to access 'https://github.com/glenndevenish/[repo].git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

#### Additional Information

None.

**Comment by shiftkey** [comment]
@glenndevenish the version of Git we're using in Desktop uses SChannel, which uses the OS to validate certificates and revocations. This error suggests something is meddling with the revocation step - is there some sort of firewall running locally that might be overriding the OS defaults?

**Comment by shiftkey** [comment]
@glenndevenish thank you for your issue!

We haven't gotten a response to the questions in our comment [here](https://github.com/desktop/desktop/issues/2471#issuecomment-322627127). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by glenndevenish** [comment]
@shiftkey Sorry, I wasn't aware of your comment, for some reason! I managed to solve it myself though, by:

1. finding the keys used by the corporate firewall in the Windows key manager
2. converting them and merging them (as .pem)
3. Added the new key to git using the git for Windows command line (it would be nice if Github desktop had some 'advanced command line' for configuring git)

**Comment by shiftkey** [comment]
@glenndevenish Desktop has it's own system configuration but you can override just about everything in your global `~/.gitconfig` using Git for Windows. Could you tell me more about what configuration values you changed to get this working?

**Comment by glenndevenish** [comment]
@shiftkey Okay, good to know. Git for Windows wasn't installed by default, so that needed sorting.

I used `git config http.sslCAInfo /path/to/certificate.crt` with the certificate I'd saved from the Windows key manager.

**Comment by shiftkey** [comment]
@glenndevenish thanks for that. I'm curious why the use of Windows Certificate Store and SChannel here isn't working for your case, but I'm happy to close this out as resolved. Please comment if there is anything else to add.

**Comment by es3** [comment]
Copy cert path from configuration git

> git config http.sslCAInfo
    Return Example: "C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt"

Add to global configuration

> git config --global http.sslBackend "openssl"
> git config --global http.sslCAInfo "C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt"

**Comment by cool-charac** [comment]
@es3 This worked for me, thanks for posting it.

**Comment by robertmryan** [comment]
I did the above `git config` commands and the "unable to check revocation" error was replaced with a new error:

> Cloning into '[local path]'...<br />
fatal: unable to access '[repo name]': SSL certificate problem: self signed certificate in certificate chain

**Comment by robertmryan** [comment]
@shiftkey Thanks, that identified the offending certificate, namely a Kaspersky cert installed as part of their suite, and once I removed that and rebooted, I can now use git desktop. Thanks!

**Comment by ocdasdebjyoti** [comment]
> Copy cert path from configuration git
> 
> > git config http.sslCAInfo
> > Return Example: "C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt"
> 
> Add to global configuration
> 
> > git config --global http.sslBackend "openssl"
> > git config --global http.sslCAInfo "C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt"

Did this. But now I have a new error:
fatal: unable to access 'https://github.com/owenscorning/MCOE.git/': SSL certificate problem: self signed certificate in certificate chain

**Comment by ocdasdebjyoti** [comment]
> Copy cert path from configuration git
> 
> > git config http.sslCAInfo
> > Return Example: "C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt"
> 
> Add to global configuration
> 
> > git config --global http.sslBackend "openssl"
> > git config --global http.sslCAInfo "C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt"

Did this. But now I have a new error:
fatal: unable to access 'https://github.com/MyOrg/MyRep.git/': SSL certificate problem: self signed certificate in certificate chain

**Comment by ferbatres** [comment]
> 
> 
> Copy cert path from configuration git
> 
> > git config http.sslCAInfo
> > Return Example: "C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt"
> 
> Add to global configuration
> 
> > git config --global http.sslBackend "openssl"
> > git config --global http.sslCAInfo "C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt"

This Worked for me also, thanks.

**Comment by ZYyiwanfuhao** [comment]
It is not that complicated. 

A easy way is to execute the following so that the SSL verify is disabled:

git config --global http.sslVerify false




> > Copy cert path from configuration git
> > > git config http.sslCAInfo
> > > Return Example: "C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt"
> > 
> > 
> > Add to global configuration
> > > git config --global http.sslBackend "openssl"
> > > git config --global http.sslCAInfo "C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt"
> 
> Did this. But now I have a new error:
> fatal: unable to access 'https://github.com/MyOrg/MyRep.git/': SSL certificate problem: self signed certificate in certificate chain
> 
> I ran the following command from the command line and got the same error.. Not sure where to go from here
> 
> ```
> C:\>openssl.exe s_client  -connect www.github.com:443
> CONNECTED(00000234)
> depth=3 DC = com, DC = MYORG, CN = MYORG LLC Root CA
> verify error:num=19:self signed certificate in certificate chain
> ---
> Certificate chain
>  0 s:/businessCategory=Private Organization/jurisdictionC=US/jurisdictionST=Delaware/serialNumber=xxxx/C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=github.com
>    i:/C=US/ST=Ohio/O=MYORG/CN=PASSLSHA2.MYORG.com
>  1 s:/C=US/ST=Ohio/O=MYORG/CN=PASSLSHA2.MYORG.com
>    i:/DC=com/DC=MYORG/DC=corp/DC=na/CN=MYORG LLC Issuing CA 1
>  2 s:/DC=com/DC=MYORG/DC=corp/DC=na/CN=MYORG LLC Issuing CA 1
>    i:/DC=com/DC=MYORG/CN=MYORG LLC Root CA
>  3 s:/DC=com/DC=MYORG/CN=MYORG LLC Root CA
>    i:/DC=com/DC=MYORG/CN=MYORG LLC Root CA
> ---
> Server certificate
> -----BEGIN CERTIFICATE-----
> Mxxxxxx xxxx
> -----END CERTIFICATE-----
> subject=/businessCategory=Private Organization/jurisdictionC=US/jurisdictionST=Delaware/serialNumber=xxxx/C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=github.com
> issuer=/C=US/ST=Ohio/O=MYORG/CN=PASSLSHA2.MYORG.com
> ---
> No client certificate CA names sent
> Peer signing digest: SHA256
> Server Temp Key: ECDH, P-256, 256 bits
> ---
> SSL handshake has read 6995 bytes and written 434 bytes
> ---
> New, TLSv1/SSLv3, Cipher is xxxx-xxxx-xxxx-xxxx-xxxx
> Server public key is 2048 bit
> Secure Renegotiation IS NOT supported
> Compression: NONE
> Expansion: NONE
> No ALPN negotiated
> SSL-Session:
>     Protocol  : TLSv1.2
>     Cipher    : ECDHE-RSA-AES128-GCM-SHA256
>     Session-ID: 519819067501DE8280CADFB76CE8F56B539AB046DF5008B630C6389D5BD5816C
>     Session-ID-ctx:
>     Master-Key: DBB129613C22AA9F47EA258E026052F2C4A3EAD8A54B4B29347E338AD4C7B6CBE33CDCC202A8DC17B2BDB0D2F3085B65
>     Key-Arg   : None
>     PSK identity: None
>     PSK identity hint: None
>     SRP username: None
>     Start Time: 1540838138
>     Timeout   : 300 (sec)
>     Verify return code: 19 (self signed certificate in certificate chain)
> ---
> closed
> ```

**Comment by Zitchas** [comment]
@ZYyiwanfuhao Thanks for providing that. I didn't really want to remove my antivirus' certificates, so a way to disable the "Self signed cert" warning is appreciated.

**Comment by KAZ-SYED-ABUTHAHIR** [comment]
Dear Friends I've found a way out. Blame it on your AV Software. When I paused my AV software and ran the command:
curl -l https:/api.github.com/zen
from the prompt, it told me,
Speak like a human.

**Comment by snannap** [comment]
> > Copy cert path from configuration git
> > > git config http.sslCAInfo
> > > Return Example: "C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt"
> > 
> > 
> > Add to global configuration
> > > git config --global http.sslBackend "openssl"
> > > git config --global http.sslCAInfo "C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt"
> 
> This Worked for me also, thanks.

after applying the above in global . received CApath none message

**Comment by snannap** [comment]
> > > Copy cert path from configuration git
> > > > git config http.sslCAInfo
> > > > Return Example: "C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt"
> > > 
> > > 
> > > Add to global configuration
> > > > git config --global http.sslBackend "openssl"
> > > > git config --global http.sslCAInfo "C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt"
> > 
> > 
> > This Worked for me also, thanks.
> 
> after applying the above in global . received CApath none message

git config --global http.sslverify "false" this statement resolved issue

**Comment by adjenks** [comment]
Similar to the answer by snannap, this disables the revocation check but only for schannel:
`git config --global http.schannelCheckRevoke false`
Suggested here: https://stackoverflow.com/questions/45556189/git-the-revocation-function-was-unable-to-check-revocation-for-the-certificate
This answer also gives nice reasoning why it might be okay or not okay to disable the revocation check.
