### ISSUE TITLE
Push failed - Using Android Studio VCS

### ISSUE THREAD

**Issue by GuillemRoca** [desktop/desktop#2476]
### Description

I just recently updated the github app to the new electron based one and the push through android studio VCS fails every single time. This didn't happen when I had the old github app installed.

Instead I get the following error: Push failed - Failed with error: error: failed to push some refs to 'https://github.com/[repo].git'

### Version

**GitHub Desktop version:** 0.7.2

**OS version:** macOS Sierra 10.12.6

### Steps to Reproduce

1. Try to push a commit done through AS. The message appears

**Expected behavior:** The push should be done with no problem through AS as normally.

**Actual behavior:** The push is not done and has to be done through the GitHub app or terminal.

**Reproduces how often:** Everytime

### Logs

Seems to be working all OK. None relevant.

#### Additional Information

None

**Comment by shiftkey** [comment]
@GuillemRoca thanks for the report! 

Could you open **View | Toggle Developer Tools** when the push failed and see what the underlying Git process is reporting? There should be some more information in the output after the `failed to push some refs to 'https://github.com/[repo].git'` section, as it could be a couple of different reasons why the push failed.

**Comment by GuillemRoca** [comment]
I toggled the developers options and all seems to be working fine. No error is displayed.

I think the issue relies in the communication between Android Studio VCS and the GitHub app if there is any. If the push is done through AS VCS the error appears in the IDE if done through the Github app it doesn't.

Maybe I should try to reinstall AS?

**Comment by shiftkey** [comment]
@GuillemRoca my gut feeling at this point is that the error is transient. The most likely scenario is that the push was rejected because someone had pushed changes that need to be merged locally - we made some improvements in #2445 around this which is available in `0.8.0`.

I'm going to close this out, but feel free to follow up if you see it again!

**Comment by amankriet** [comment]
same problem is with me while pushing changes everytime i reopen my windows and android studio (version 3.1). But when i force push using git bash **(command - *$ git push origin master --force*)** into my repository after that everything in android studio starts working fine again!

**Comment by usmansahi** [comment]
i got also same error while i am uploding or pushing my project .
Failed with error: unable to access 'https://github.com/londonappbrewery/Xylophone-Android.git/': The requested URL returned error: 403 this is errror

**Comment by shiftkey** [comment]
@usmansahi @amankriet please open a new issue with details about how this relates to GitHub Desktop
