### ISSUE TITLE
large images are not scaled to stay inside diff panel

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#2480]
### Description

With the new image diff improvements in #2383 there's a scenario where a large image is drawn outside the diff panel. We shouldn't do this.

### Version

**GitHub Desktop version:** current `master` e.g. 82b1d2377b98208d74aff0337c8f482cef2c1e35
**OS version:** Windows 10

### Steps to Reproduce

1. Clone https://github.com/shiftkey/image-examples 
1. Switch to History tab
1. Select this commit https://github.com/shiftkey/image-examples/commit/10c1cf4d08b884f83332d8ae24e14336c5ad73df
1. Ensure you have `2-up` selected (but the others show this problem too)

**Expected behavior:** 
  - Image does not display outside diff view.
  - Can toggle between different modes.

**Actual behavior:** 
  - Image drawn over top menu.
  - Unable to change diff mode.

<img width="1440"  src="https://user-images.githubusercontent.com/359239/29398473-498201a4-8368-11e7-8ad7-7887caafb759.png">

**Reproduces how often:** 100%

**Comment by joshaber** [comment]
😱 

I think we should fix this for 1.0.

**Comment by joshaber** [comment]
Huh, interestingly I can't reproduce this on Mac 🤔

**Comment by joshaber** [comment]
Hrm, I can't reproduce this in my Windows 8 VM either. Gonna try getting a Windows 10 VM running.

**Comment by joshaber** [comment]
I'm having VMWare troubles with Windows 10, so I'm gonna unassign myself until I'm able to reproduce it.

**Comment by iAmWillShepherd** [comment]
I'm unable to reproduce this issue. Are you still having it?

**Comment by tierninho** [comment]
Was just looking at this too, can't reproduce either.

**Comment by joshaber** [comment]
Gonna 👢 this until we can reproduce it.

**Comment by shiftkey** [comment]
Still reproducible on `0.8.1-beta2` on a Windows 10 VM:

<img width="992" src="https://user-images.githubusercontent.com/359239/29948489-771ee34e-8ef2-11e7-97d2-e72426099600.png">

:thumbsup: to defer until someone else can reproduce this.

**Comment by PragmaticEd** [comment]
Why is this closed, if it still happens?
I uploaded git project [here](https://github.com/PragmaticEd/github-large-image-preview-scale-bug), that reproduces the problem. @tierninho  please open the issue again, till fixed.

**Comment by PragmaticEd** [comment]
I uploaded git project [here](https://github.com/PragmaticEd/github-large-image-preview-scale-bug), that reproduces the problem. @tierninho  please open the issue again, till fixed.

**Comment by niik** [comment]
@PragmaticEd thank you so much for taking the time to create a reproduction repository.

Unfortunately I wasn't able to reproduce this using the repo provided *on macOS*, haven't tested it on Windows 10 yet.

![screen shot 2017-10-18 at 11 40 48](https://user-images.githubusercontent.com/634063/31711703-478684bc-b3f9-11e7-9d6d-b4bd5544c854.png)

@PragmaticEd Are you using multiple monitors or different DPI scaling settings by any chance?

**Comment by tierninho** [comment]
@PragmaticEd thanks for checking in and adding your project. 

As this issue is still open, we will be tracking it here. Your #3075 issue is noted.

**Comment by PragmaticEd** [comment]
@tierninho Yes, that might be it. I have 4k screen, set to 4k resolution and 200% scaling. Just tested. By setting the scaling to 100%, this problem goes away. So the problem is with scaling.  I tried disabling the scaling for the app, like so: http://take.ms/jbXkW  That, usually, fixes the problem for most other apps, but not this time..

**Comment by niik** [comment]
> Yes, that might be it. I have 4k screen, set to 4k resolution and 200% scaling. Just tested. By setting the scaling to 100%, this problem goes away.

Excellent. I think I've got a good sense of what's going on then. The image diff uses a `ResizeObserver` which returns native pixels and then applies them as logical pixels. This has been a problem for us in the past. This should be a fairly straightforward fix of using `offsetWidth` and `offsetHeight` instead like we do in [list.tsx](https://github.com/desktop/desktop/blob/8824fc0ca27e146ffa4fd7365c112d25221614a7/app/src/ui/lib/list/list.tsx#L250). See https://github.com/desktop/desktop/issues/1200 and https://github.com/desktop/desktop/issues/1201 (but note that getClientBoundingRect isn't the answer due to zooming, see https://github.com/desktop/desktop/commit/03a86e5f2d1d755776206bcf6aec5fd62b18101f)

**Comment by j-f1** [comment]
I have a retina screen and I’ve encountered this with (tall?) images.

**Comment by shiftkey** [comment]
#5215 was another report that seems related to this issue

> I added an image to my repository, it's size was 2600x3100 pixels. I previewed it before commiting changes. The 2-up view were selected. The image hided some of the navbar's components, like a layer whichs z-index is incorrect.

**Comment by Yuudaari** [comment]
I use 125% zoom and I have this issue very frequently in an image-heavy repository. It can cover the branch/fetch buttons in the changes view, and always covers the diff view options in the history view. I have to resize down to 100% to work with this repository.

**Comment by fdmarcin** [comment]
Hi! This affects me too on Windows 10, GH Desktop 1.4.3.
The image dimensions are 1532 x 794, and my screen resolution is 1920 x 1080 with 150% scaling.
The menu bar in the screenshot is part of the image in the diff btw.
![gh-desktop-image](https://user-images.githubusercontent.com/25668969/47351145-ae834d80-d6b7-11e8-9747-50a422ab0337.png)

**Comment by gabrielevierti** [comment]
I am still aboe to reproduce this in 1.5.0

**Comment by shiftkey** [comment]
I've been able to reproduce this on Windows 10 and I think it's some combination of scaling and screen real-estate.

This is the commit I'm working with (thanks @AndyThePie for the setup): https://github.com/AndyThePie/pizzaRPG-repo/commit/0233f1c56771ddf2d72f71c800d3f2ac86ef18ed

At 100% scaling on a 1440x900px display, the image diff is scaled down to fit into the space:

<img width="996" src="https://user-images.githubusercontent.com/359239/50742051-8eeec200-11dc-11e9-860a-9cf05217817c.png">

At 200% scaling on a 2560x1440px display, the image is no longer scaled down:

<img width="1990" src="https://user-images.githubusercontent.com/359239/50742081-d6754e00-11dc-11e9-90a8-b6e707ce2cfe.png">

Probably requires some refreshing of what the image diff controls are rendering and whether they care about the available space...
