### ISSUE TITLE
Windows: clicking the window to focus it also closes dialogs

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#2486]
This is especially annoying in light of https://github.com/desktop/desktop/pull/2442.

1. Focus Explorer.
1. Drag a repo on to the app.
1. See the dialog popup.
1. Click somewhere in the app to focus it.
1. Dialog closes.

**Comment by shiftkey** [comment]
Maybe just need to `dismissable=false` the dialog?

**Comment by joshaber** [comment]
It's a more general issue for all dialogs... I don't think we want this behavior for any of them, I was just using Add Repo to illustrate.
