### ISSUE TITLE
Commit button grayed out even though lines are selected

### ISSUE THREAD

**Issue by cheshire137** [desktop/desktop#2490]
I'm in version 0.8.0 in macOS. I had a file with some changed lines. I deselected one of the lines while having several others selected. I can't remember if I had entered a short commit message at this point or not. 🤔 I then switched to my editor and changed some of the lines that had been selected for commit in GitHub Desktop. I did not change the line that I had deselected in GitHub Desktop. When I switched back to GitHub Desktop, I _think_ I entered the short commit message at this point, and some lines were already selected while the one line was still deselected, as I wanted. I noticed, however, that the commit button was grayed out. I clicked the checkbox in the top left to deselect and reselect the file and all its lines, and then deselected the one line I didn't want to commit. This enabled the commit button for me.

Here's a screenshot of the state where some lines were selected, a short commit message was present, but the commit button was disabled:

<img width="477" alt="screenshot_8_17_17__1_31_pm" src="https://user-images.githubusercontent.com/82317/29428557-3e31f710-8353-11e7-9d5c-54e4af087027.png">

**Comment by joshaber** [comment]
It looks like the "include all" checkbox being unchecked is a smoking 🔫 For some reason we thought no files were checked 🤔

**Comment by cheshire137** [comment]
Maybe I modified the contents of all the selected lines and that did it. So I had some lines selected but not all, then I changed in my editor those lines that had been selected, so back in GitHub Desktop those same lines still show as selected but their contents are different?

**Comment by jmmendivil** [comment]
Now the problem is that it does a commit on the full file, not only on the selected lines.

**Comment by j-f1** [comment]
@jmmendivil Can you open a new issue and fill out the template so we can figure out what’s going on?

**Comment by jmmendivil** [comment]
@j-f1 My fault, seems like a [lint-staged issue](https://github.com/okonet/lint-staged/issues/62)

**Comment by shiftkey** [comment]
FYI @jmmendivil this is a known limitation: https://github.com/desktop/desktop/issues/1831#issuecomment-305826579

**Comment by hakunin** [comment]
Just spent half hour cherry picking lines and couldn't push the commit button. Tried enabling the button via web tools and clicking it but its not working.

Version 1.4.2, according to my client its up to date.

**Comment by shiftkey** [comment]
@hakunin this issue was from a while ago (pre-1.0). Would you be able to open a fresh issue with details to help us understand and reproduce what you're seeing on our end?

**Comment by FBalazsBme** [comment]
Same for me as for hakunin.
