### ISSUE TITLE
Copying selected text inside diff doesn't copy all that is visibly selected

### ISSUE THREAD

**Issue by cheshire137** [desktop/desktop#2492]
I'm in 0.8.0 on macOS. When I select some text in the diff and hit Cmd-C to copy it, the first letter is omitted from what is copied:

![select-text-doesnt-copy-all-github-desktop-loop](https://user-images.githubusercontent.com/82317/29431967-77b9d348-835f-11e7-8e0a-542d088a5ecb.gif)

**Comment by michaelpdebus5** [comment]
I see live
?

**Comment by NickCraver** [comment]
I hit this today, very annoying when copying into the comments field =P
