### ISSUE TITLE
Cannot push origin error:"could not read Username for 'https://github.com': terminal prompts disabled"

### ISSUE THREAD

**Issue by LiarOnce** [desktop/desktop#2496]
### Description

I cannot push the new commit and I get an error:
```
ϵͳ�Ҳ���ָ����·����
error: unable to read askpass response from 'X:\Users\LiarOnce.DESKTOP-NRV42PI\AppData\Local\GitHubDesktop\app-0.8.0\resources\app\static\ask-pass-trampoline.bat'
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

### Version

**GitHub Desktop version:** 0.8.0

**OS version:** Windows 10 Pro 1703

### Steps to Reproduce

1. Confirm the changes.

![snipaste_20170818_124350.png](https://i.loli.net/2017/08/18/599672a5314db.png)

2. Add the commit.

![snipaste_20170818_124408.png](https://i.loli.net/2017/08/18/599672b517872.png)

3. Click Push origin and get an error

![snipaste_20170818_124246.png](https://i.loli.net/2017/08/18/599672d3dba93.png)

**Expected behavior:** Push new code.

**Actual behavior:** Get the error.

**Reproduces how often:** All time.

### Logs

Sorry, no logs output.

#### Additional Information

1, GIF Error

![GIF.gif](https://i.loli.net/2017/08/18/599672e9eb0f7.gif)

2, My system language is Simplified Chinese, so I do not know what this line of garbled represents.:

```
ϵͳ�Ҳ���ָ����·����
```

3, The `ask-pass-trampoline.bat` file is exists.

![snipaste_20170818_125657.png](https://i.loli.net/2017/08/18/599673ab9c8e8.png)

**Comment by shiftkey** [comment]
@LiarOnce can you open **File** | **Options** and confirm you are signed into your GitHub account?

**Comment by LiarOnce** [comment]
Yes, I signed.

![snipaste_20170818_131419.png](https://i.loli.net/2017/08/18/599677d1bd4d2.png)

**Comment by LiarOnce** [comment]
I closed this issue because I fixed this bug.
Thanks!

**Comment by shiftkey** [comment]
@LiarOnce I'm glad you were able to resolve this! If you could tell us a bit about the root cause it might also help others in the future.

**Comment by JackDotGriffiths** [comment]
I could really do with a detailed solution to this problem

**Comment by mrlucmorin** [comment]
@LiarOnce as was mentioned by user shiftkey, other users with the same problem would really enjoy knowing how you solved your problem. It's nice for you to be able to come here and ask for help, and you know that other users will do their best to assist you, so don't be shy to share your answer.
