### ISSUE TITLE
Show Repository/Branches List should toggle when clicked or using keyboard short cut

### ISSUE THREAD

**Issue by unknowndomain** [desktop/desktop#2502]
### Description

Clicking or using the keyboard short cut for either Show Repository List or Show Branches List works fine, but if it's open it doesn't hide it again.

### Version

**GitHub Desktop version:** 0.8

**OS version:** 10.12.6 (16G29)

**Comment by iAmWillShepherd** [comment]
Thanks for bringing this to our attention! 👍

**Comment by shiftkey** [comment]
Fixed by #2532
