### ISSUE TITLE
Application title bar is empty consider using the space for the menu current repository and branch

### ISSUE THREAD

**Issue by unknowndomain** [desktop/desktop#2503]
### Description

The title bar of GitHub Desktop litterally has nothing in it other than the three window actions:

![image](https://user-images.githubusercontent.com/147143/29479689-ad46bd66-846b-11e7-8ec0-09f90f182ef0.png)

However there is a busy menu bar underneath which in most other applications on macOS are now combined:

![screen shot 2017-08-18 at 23 20 19](https://user-images.githubusercontent.com/147143/29479764-0f63c688-846c-11e7-9974-3d4f61716b2d.png)
<img width="780" alt="screen shot 2017-08-18 at 23 20 27" src="https://user-images.githubusercontent.com/147143/29479765-0f6585b8-846c-11e7-8942-82802b8367da.png">
![screen shot 2017-08-18 at 23 20 43](https://user-images.githubusercontent.com/147143/29479766-0f68906e-846c-11e7-8e98-1440c38cb236.png)

You can see the last one is Atom which is an Electron app with the proposed changes to the GUI.

Just a quick sketch of how it might look, I'm sure it could be improved.

![image](https://user-images.githubusercontent.com/147143/29480183-6296caec-846e-11e7-9814-bfd6c759354c.png)

**Comment by shiftkey** [comment]
@unknowndomain thanks for the suggestion! I've added this to the triage queue for the core team to   review - we will report back soon...

**Comment by j-f1** [comment]
From https://github.com/desktop/desktop/issues/1816#issuecomment-306946331:

> <img src="https://user-images.githubusercontent.com/25517624/26904563-7ee635d0-4bb0-11e7-8027-2e9a73c42c51.png" alt="dropdown closed" width="325"><img src="https://user-images.githubusercontent.com/25517624/26904564-7efe0af2-4bb0-11e7-979d-16f67e781baf.png" alt="dropdown opened" width="325">
>
> ```css
> /* inline title bar */
> #desktop-app-title-bar {
>   display: none;
> }
> .toolbar {
>   height: 37px;
> }
> .toolbar > :first-child button:first-child {
>   padding-left: 75px;
> }
> .toolbar-button > button {
>   padding: calc(var(--spacing) - 5px) var(--spacing);
> }
> ```

**Comment by unknowndomain** [comment]
@j-f1 That looks pretty close but also needs to add:

`titleBarStyle: ‘hidden-inset’`

**Comment by billygriffin** [comment]
Hi @unknowndomain, thanks for the suggestion! We agree that it would be ideal to have a more integrated title bar with the actions blended in. However, without rethinking the design overall we're not super comfortable with just removing it. Unless we do a larger refresh of the design, we don't think integrating the actions is appropriate, acknowledging that it does unfortunately result in a bit of wasted vertical space. Thanks again!
