### ISSUE TITLE
Open in Github Desktop from External Editor

### ISSUE THREAD

**Issue by bbgdzxng1** [desktop/desktop#2509]
This feature request is the reverse workflow for "Open in External Editor".

There has been some [great work](https://github.com/desktop/desktop/pull/2407) done on re-adding "Open in External Editor" into the Electron version of Github Desktop.  What hooks would be required within Github Desktop for an external editor to be able to return the favor and allow the external editor to "Open in Github Desktop" to complete a unified workflow?

The use case would be...
- Use Github Desktop to view your branches/repos
- Open in Atom.  Use Atom to make your changes, save the file
- Open in Github Desktop and Github Desktop opens at the appropriate repo/branch.
- Use Github Desktop to manage the commits, PRs and syncs to Github or Github Enterprise.

Task Switching between Atom and Github Desktop does work, but it relies on the user then navigating to the repo/branch within Github Desktop after any changes have been made in the external editor.

Atom has done work in http://blog.atom.io/2017/05/16/git-and-github-integration-comes-to-atom.html enabling a direct commit to github.com, but that integration goes some way to shutting out Github Desktop from the commit-side of a unified workflow.  It would be nice if an external editors could have the ability to add an "Open in Github Desktop" feature.

How could an external editor switch to (or launch) Github Desktop at the appropriate repo ready for Github Desktop to do the actual commit?  Are any hooks required on the Github Desktop side of things or it is all up to the editor to call Github Desktop via a command-line launch parameter?

There may be unintended consequences which make this use-case impractical.  Could allowing an external editor to switch the focus of an already-open Github Desktop cause unsaved commit descriptions to be lost in other repos?

**Comment by j-f1** [comment]
There already is a URL scheme used by GitHub.com, and I’m pretty sure it can open a specific repository. The branch in Desktop is loaded from `git`, so it shouldn’t need to get changed.

**Comment by shiftkey** [comment]
@bbgdzxng1 thanks for the interest!

> How could an external editor switch to (or launch) Github Desktop at the appropriate repo ready for Github Desktop to do the actual commit?

Currently there is a command line shim installed on disk for opening the folder:

 - `/usr/local/bin/git` on macOS (requires user to install this)
 - `%LOCALAPPDATA%\GitHubDesktop\bin\github.bat` on Windows

> Are any hooks required on the Github Desktop side of things or it is all up to the editor to call Github Desktop via a command-line launch parameter?

These currently take a path, but we're looking to improve this and add a bit more - see #2372 for the discussion.

>  Could allowing an external editor to switch the focus of an already-open Github Desktop cause unsaved commit descriptions to be lost in other repos?

I did a quick test of this on the latest release, and we're already persisting these values you open a different repository from the command line.

**Comment by iAmWillShepherd** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our current roadmap.

I added the future-proposal label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by ahmadalli** [comment]
@bbgdzxng1 running `github .` command in terminal works for me. I think Editors can run this command too

**Comment by billygriffin** [comment]
Thanks for the idea @bbgdzxng1! This isn't something we hear a lot of and based on discussions with folks it's most frequent that people are already in the repo in Desktop when they're working in their editor and therefore just bouncing back and forth without a lot of friction. It does seem like it'd be a nice to have, but given that we only have control over the Desktop side of things and not over most editors, we're not sure this would be hugely valuable to invest in. I'm going to remove the `future-proposal` label to indicate that we don't intend to work on this directly, but if editor maintainers are interested in an integration, we're more than happy to chat about what that might look like. Thanks again.
