### ISSUE TITLE
Visually differentiate remote branches?

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#251]
From https://github.com/desktop/desktop/pull/247#issuecomment-239496554:

> @haacked: I guess they're useful, but maybe should be grouped in a "remote branches" section or "branches on the server"

Thoughts?

**Comment by Haacked** [comment]
Sorry, I missed @niik's question...

> Can you give a little more detail as to why you feel like this distinction is an important one to make?

I don't have a great reason right now other than I like to know what's going on.

> let us know if you have any extra feels on this last question and we can come back to it

I agree that what we have today is good enough and I'm pretty happy with it. :sparkles:
