### ISSUE TITLE
some inputboxes  support chinese not  well

### ISSUE THREAD

**Issue by oHao** [desktop/desktop#2513]
i want:
`这是一个简单的示例`
and i get:
`这是   一个  简单  的 示例`
it will automatically insert some space

**Comment by iAmWillShepherd** [comment]
Which input elements do this? Also, can you confirm that this only happens in GitHub Desktop and no other Chrome based tool?

**Comment by oHao** [comment]
almost all of file->new/add/clone  repository tag . Now i suspect that it was caused by the input method editor. I retest it  and fond that  it happened on both English and Chinese.

**Comment by shiftkey** [comment]
@oHao could you share screenshots of the specific forms and the textboxes that are causing the problem? We need to narrow it down to confirm it's not something the application is doing - for example #2333 was a workaround for something related to input fields.

**Comment by oHao** [comment]
@shiftkey  #2333 seems to solve my  problem.

**Comment by shiftkey** [comment]
@oHao if there's nothing more to do here (I'm not clear on which version you're running) then I'm happy to close this out - please confirm.
