### ISSUE TITLE
GitHub Enterprise - Fatal SSL Cert Error

### ISSUE THREAD

**Issue by AJ1701** [desktop/desktop#2514]
**Description:**
Version 0.8.0 has a fatal error when connecting to a GitHub enterprise server. Rolling back to a previous version fixes this.

**Error:**
`fatal: unable to access 'https://[GitHub Enterprise address]/[user]/Scripts.git/': SSL certificate problem: self signed certificate in certificate chain
`
(Redacted identifying information)

**Version:**
GitHub Desktop version: 0.8.0

**OS version:** 
Windows 7 SP1

**Steps to Reproduce:**
1. Try pushing/fetching from a GitHub enterprise server

**Reproduces how often:** 100%

Thanks!

**Comment by iAmWillShepherd** [comment]
Thank you for bringing this to our attention. I have applied the `bug` label and we will address it ASAP.

**Comment by shiftkey** [comment]
@AJ1701 

> Rolling back to a previous version fixes this.

Could you tell me which version works for you? This will help to isolate what's changed that's introduced this issue.

**Comment by w60001** [comment]
I can confirm that everything worked in the previous version for me and this regression appeared after an auto upgrade this morning.

**Comment by shiftkey** [comment]
We updated Git from v2.13.0 to v2.14.1 as part of the update from 0.7.2 to 0.8.0, but both versions should be using the Windows Certificate Store (SChannel) to validate certificates. I thought our way of packaging Git was still valid, but maybe [this release](https://github.com/git-for-windows/git/releases/tag/v2.14.0.windows.1) has regressed this.

> It is now possible to switch between Secure Channel and OpenSSL for Git's HTTPS transport by setting the `http.sslBackend` config variable to `"openssl"` or `"schannel"`; **This is now also the method used by the installer (rather than copying libcurl-4.dll files around).**

@w60001 @AJ1701 could you open the problem repository in Git Shell and run this command:

```
$ git config http.sslBackend "schannel"
```

If this makes fetching/pushing/pulling work then we can set this in the system configuration for our version of Git and get a new update out asap.

**Comment by AJ1701** [comment]
@shiftkey 0.7.2 is the most recent version that works for me. 

It also looks like the git command fixed it. The other repository I have still has the issue, but the repository I ran the command on works just fine now.

**Comment by RussellAnderson** [comment]
I can also confirm, running the git command @shiftkey mentioned fixed the ssl issue that I encountered after the update.

**Comment by shiftkey** [comment]
@AJ1701 @RussellAnderson thanks for confirming the fix - #2520 will go out for the next update and will address this at a system level for everyone.
