### ISSUE TITLE
Swap default choice on "Publish Branch?" dialog

### ISSUE THREAD

**Issue by zeke** [desktop/desktop#2515]
When the "Create Pull Request" menu item is selected and the local branch has not yet been pushed to the remote, the following dialog is displayed:

<img width="557" alt="screen shot 2017-08-21 at 8 08 23 am" src="https://user-images.githubusercontent.com/2289/29525681-552e9016-8648-11e7-9775-cbeff71ec7b2.png">

I am of the opinion that "Publish Branch" should be the button that is highlighted by default.

I assume there is a "safety first" rationale baked into this and other defaults, but it seems like most folks will see this dialog when they do intend to push.

**Comment by iAmWillShepherd** [comment]
I believe the button order is intentional, but @desktop/design would know better than I.

**Comment by shiftkey** [comment]
@zeke this is on macOS, correct?

**Comment by zeke** [comment]
> this is on macOS, correct?

Yep. Sorry for omitting that detail.

```
$ uname -a
Darwin Zekes-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

**Comment by joshaber** [comment]
I agree 👍 

This comes from https://github.com/desktop/desktop/pull/2195 and I don't see any design reason stated for the button order. I think we're safe to swap it.

**Comment by donokuda** [comment]
👍 on swapping the default choice to publishing the branch.

**Comment by zeke** [comment]
🙏
