### ISSUE TITLE
Code coverage monitoring

### ISSUE THREAD

**Issue by j-f1** [desktop/desktop#2517]
Currently, although the Desktop codebase includes tests, the code coverage from those tests is not monitored. Should Desktop use a service like [Codecov](https://codecov.io) to upload coverage generated by something like [Istanbul](https://istanbul.js.org)?

Notes:

* To upload data from multiple test suites, something like this might work:
  ```shell
  bash <(curl -s https://codecov.io/bash) -J 'test:unit' -f unit
  bash <(curl -s https://codecov.io/bash) -J 'test:integration' -f integration
  ```
* It might be advantageous to install the [app](https://github.com/apps/codecov) so comments on PRs are by a `codecov[bot]` user instead of `codecovbot`.

**Comment by iAmWillShepherd** [comment]
Marking this for the future. Adding it isn't a priority for our v1.0 release, but would be a good thing to talk about during our next meeting.

**Comment by shiftkey** [comment]
I'm going to reopen this as a chance for someone to experiment with what's available out there

**Comment by shiftkey** [comment]
We have this working in #5636 and have a tracking issue around what we uncover in #5511 so I'm going to close this out as resolved.
