### ISSUE TITLE
Git commit takes a really long time on a specific repo

### ISSUE THREAD

**Issue by radumg** [desktop/desktop#2518]
### Description

GitHub desktop either takes a really long time (5 minutes or more) to commit, but only on a specific repository. I've now also had it fail for the first time ever since switching to the new desktop app.

### Version

**GitHub Desktop version:** 0.8.0

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. make changes to any file in repo
2. commit using GitHub desktop UI
3. GitHub desktop takes more than 5 minutes to commit
4. does not happen on other repositories

The affected repository is a straight-up duplication of this public repo : https://github.com/typicode/json-server 

**Expected behavior:** commit in the usual timeframe, usually under 10 seconds, even for large commits.

**Actual behavior:** commit takes 5 minutes or more. Failed on only 1 occasion, 
**Reproduces how often:** It's slow 100% of the time with this repo but failed only once.

### Logs
Please see attached file for a copy-paste of the error window, to me it looks like it's actually executing the code of the repo, which would be highly dubious.
Also attached the desktop log.

![git error](https://user-images.githubusercontent.com/11439624/29539251-ff110302-86c0-11e7-82f5-3e94e6ca6d09.PNG)
[logs.zip](https://github.com/desktop/desktop/files/1240213/logs.zip)

### Additional information
This affected repository belongs to my organisation whilst most of the other repos are on my own account.

**Comment by iAmWillShepherd** [comment]
Does it take long to commit using the CLI?

**Comment by shiftkey** [comment]
@radumg it looks like the Git pre-commit hook is failing, which blocks the commit from completing. It's hard for me to tell what's in the git commit hook (husky -> NPM -> ???) - could you shed some light on that?

**Comment by radumg** [comment]
thanks @iAmWillShepherd and @shiftkey for the quick take-up.

Just tried with CLI and same behaviour, even when changes are un-staged, see the 2 screenshots.

![git commit](https://user-images.githubusercontent.com/11439624/29540855-8aecc486-86c8-11e7-91ab-b0b74711713d.PNG)
![git unstaged commit](https://user-images.githubusercontent.com/11439624/29540856-8b1f96a4-86c8-11e7-80f8-809062453a83.PNG)

As for the `husky` pre-commit hook : now that I knew what to look for, I dug around the repo and `husky` is a node module and it seems it has some git hooks, see screenshot. It's not something I added, must have been part of the original repo.
![husky hooks](https://user-images.githubusercontent.com/11439624/29540894-bc84a37e-86c8-11e7-8ba7-fd8f2e5aa24f.PNG)

**Comment by j-f1** [comment]
Here’s your culprit:

https://github.com/typicode/json-server/blob/3707376b8ab06e232e0a9bbe34eab9a292305e95/package.json#L61-L69

One of `build`, `test:cli`, `test:server`, or `eslint` is slowing you down.

**Comment by shiftkey** [comment]
@radumg pre-commit hooks in Git will fail Git by returning a non-zero exit code. There might be details in [the log files](https://github.com/desktop/desktop/blob/master/docs/installation.md#log-files) around the actual failure (if you didn't scroll the output of the dialog to the bottom at the time).

**Comment by shiftkey** [comment]
Aha!

```
  19 passing (59s)
  1 failing

  1) cli fixtures/seed.json --no-cors=true "before each" hook for "should not send Access-Control-Allow-Origin headers":
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by shiftkey** [comment]
@radumg so a test in the pre-commit hook failed due to a timeout of 5s (which fits with the slow commit issue) which then caused the commit itself to fail. Closing this out as an external issue.

**Comment by radumg** [comment]
Thanks all for the assistance 🍻 , hadn't dealt with commit hooks (or this much JS) until now.
Will reach out to original repo owner @typicode .
