### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by decryptionz** [desktop/desktop#2519]
So I don't know if this is still added to the desktop application but. I can't find a dark mode added to the desktop app as I'm using this overnight.

https://github.com/desktop/desktop/issues/1515

It's been addressed before and I've seen it added towards the application before listed here:

https://github.com/blog/2169-github-desktop-now-has-a-dark-side

I've done it via css in the developer tools. But there isn't a way to apply it in one sitting. Is it possible?

**Comment by shiftkey** [comment]
@decryptionz please add your feedback to #1515 - as mentioned in the issue, we'll revisit these tasks as part of the next planning session.
