### ISSUE TITLE
Can't change remote for non-GitHub repository

### ISSUE THREAD

**Issue by evromalarkey** [desktop/desktop#2521]
### Description

If I create a new repo and I want to publish it to non-GitHub repository, I have to add remote manually via cmd. In the previous client it was possible to change remote url, now I have only option to publish it to GitHub.

### Version

**GitHub Desktop version:** 0.8.0

**Comment by iAmWillShepherd** [comment]
You can change the remote URL by selecting _Repository -> Repository Settings... -> Remote_.

**Comment by evromalarkey** [comment]
No you can't if you have created new repository with the client. You can change the url only on existing cloned repo.

**Comment by shiftkey** [comment]
@evromalarkey is right, we hide the input for a new repository and instead encourage them to publish:

<img width="493" src="https://user-images.githubusercontent.com/359239/29599219-a5767be0-8811-11e7-85bd-4b4a794aecf4.png">

I think this is the underlying issue:

> If I create a new repo and I want to publish it to non-GitHub repository, I have to add remote manually via cmd.

Not sure what we should do here, open to suggestions.

**Comment by j-f1** [comment]
Maybe there should be an advanced link/button that gives you the text box:

![No thanks, I want to set up a custom remote](https://user-images.githubusercontent.com/25517624/29612642-3bfe4cd8-87d0-11e7-8e4e-cebad11cfe78.png)

**Comment by iAmWillShepherd** [comment]
@evromalarkey 
 
> No you can't if you have created new repository with the client. You can change the url only on existing cloned repo.

Sorry about that, I missed the crucial word _new_ and assumed one you already had.

**Comment by evromalarkey** [comment]
np, anyway shouldn't we reopened this now?

**Comment by donokuda** [comment]
I'm digging the exploration above and tried mocking out the full experience of adding a custom remote. When there's no remote currently set, we can consider showing two buttons for publishing the repo to GitHub and setting up a custom remote:

<img src="https://user-images.githubusercontent.com/1174461/29837773-006898da-8cae-11e7-8aa9-44f5b00ef403.png" width="482" title="0 - remote settings no remote 2x" />

Clicking on the custom remote button presents a new dialog to add the remote:

<img src="https://user-images.githubusercontent.com/1174461/29837775-006d5bf4-8cae-11e7-979a-ddc102350260.png" width="482" title="1 - setup local repository 2x" />

Clicking on "Save & Publish" will save, close the dialog, and begin the publishing process. When a user returns to the settings dialog, the custom URL will be populated just like how it is currently  implemented:

<img src="https://user-images.githubusercontent.com/1174461/29837774-00695df6-8cae-11e7-8c81-a4d534cafeb2.png" width="482" title="2 - remote settings 2x" />

**Comment by iAmWillShepherd** [comment]
Looks good to me

**Comment by j-f1** [comment]
@donokuda What if I don’t enter a GitHub remote into the custom remote setup box? Should it still publish?

**Comment by donokuda** [comment]
> @donokuda What if I don’t enter a GitHub remote into the custom remote setup box? Should it still publish?

Yes, as far as I'm concerned. This should act similar to setting the origin remote via the command line.

**Comment by ErrolSayre** [comment]
This was a feature of the Mac native app… sorely missing it now. Got my +1.

**Comment by ockxdd** [comment]
https://guides.github.com/features/mastering-markdown/

**Comment by iAmWillShepherd** [comment]
I added the future-proposal label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by evromalarkey** [comment]
Any news on this?

**Comment by billygriffin** [comment]
@evromalarkey Thanks for the idea! In discussing this more internally, we don't think there's sufficient demand to warrant supporting this feature. We support cloning from other remotes and intend to continue to do so, but our intent is to continue to invest in making the GitHub Desktop <-> GitHub experience shine. 

We do have docs here explaining how to clone non-GitHub repos (GitLab, BitBucket, and Azure DevOps) in GitHub Desktop: https://github.com/desktop/desktop/tree/development/docs/integrations

Thanks again and hope that helps, even if we're not able to build out this feature in its entirety.
