### ISSUE TITLE
Cannot see list of branches in desktop UI

### ISSUE THREAD

**Issue by yashketkar** [desktop/desktop#2522]
### Description

Cannot see list of branches in desktop UI

### Version

**GitHub Desktop version:** 0.8.1-beta1

**OS version:** Windows 10 ( Microsoft Windows [Version 10.0.15063] )

### Steps to Reproduce

1. Open Github Desktop
2. Click on the current branch dropdown
(I am using it on a Github Enterprise repo)

**Expected behavior:** Show the branches seen here in the desktop UI
![image](https://user-images.githubusercontent.com/3140683/29569776-20523fbe-871a-11e7-83b1-a293630b4598.png)

**Actual behavior:** Cannot see the list of branches
![image](https://user-images.githubusercontent.com/3140683/29569715-f4967cbe-8719-11e7-8e32-0a2017ae2ef5.png)

### Logs

[2017-08-22.desktop.beta.log.txt](https://github.com/desktop/desktop/files/1242287/2017-08-22.desktop.beta.log.txt)

**Comment by tierninho** [comment]
Confirming the same on Mac / Windows for all repos (public/ private/ Enterprise/ local/ dotcom/)

**Comment by Tywholland** [comment]
This is also happening to me as of the latest update that I did this morning

**Comment by shiftkey** [comment]
Just a heads up - if you're encountering this with `0.8.1-beta1` you can switch back to the stable channel by reinstalling from `desktop.github.com` if this is blocking your work.

**Comment by shiftkey** [comment]
Cool, I can't reproduce this in dev mode but I can when it's built for production - so something interesting in #2512 is probably to blame here.

**Comment by shiftkey** [comment]
The root cause of this is our parsing of Git output isn't working. It expects a delimiter string to be included at the end of each line, but it isn't for production output.

Here's the diff of Git's output in both cases (production on left, dev mode on right):

<img width="1406" src="https://user-images.githubusercontent.com/359239/29591988-01669c8c-87e5-11e7-8db0-859eb060ebc1.png">

`1F` is the ASCII code for "unit separator" - not sure if is important to Node and why it might be meddling here to drop these bytes in the stream.

**Comment by shiftkey** [comment]
Narrowing this down to the minification process around this. Here's the arguments being passed in for`0.8.0`:

```
const Z = '1F'
  , Q = _StringfromCharCode(parseInt(Z, 16))
  , ee = ['%(refname)', '%(refname:short)', '%(upstream:short)', '%(objectname)', '%(author)', '%(parent)', '%(subject)', '%(body)', `%${Z}`].join('%00');
  J && J.length || (J = ['refs/heads', 'refs/remotes']);
  const ne = yield U.git(['for-each-ref', `--format=${ee}`, ...J], X.path, 'getBranches')
```

And here's the arguments passed in for `0.8.1-beta1`:

```
const o = yield i.git(['for-each-ref', `--format=${'%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(subject)%00%(body)%00'}`, ...t], e.path, 'getBranches')
```

And while it's neat that it's aggressively inlining the result, it seems to be happy to drop the `%1F` control character from the string.

**Comment by shiftkey** [comment]
FYI: the `0.8.1-beta2` update is now available and contains this fix.
