### ISSUE TITLE
Create Pull Request should become Show Pull Request if one is already opened.

### ISSUE THREAD

**Issue by notxcain** [desktop/desktop#2524]
### Description

`Create Pull Request` opens GitHub to create PR even if one already exists.
It would be very handy to change it to `Show Pull Request` after PR was created.
This was the old behavior in GitHub for Mac

### Version

**GitHub Desktop version:** 0.8.0

**OS version:** OS X 10.11.6 (15G1611)

### Steps to Reproduce

1. Push `Create Pull Request`
1. Create actual PR on GitHub

**Expected behavior:** `Create Pull Request` becomes `Show Pull Request`

**Actual behavior:** `Create Pull Request` opens GitHub to create a PR once again.

**Reproduces how often:** Always

**Comment by iAmWillShepherd** [comment]
Thanks for the suggestion. I've added this to our v1 release.

**Comment by notxcain** [comment]
Cool!

**Comment by joshaber** [comment]
I think this might make more sense to tackle as part of 1.1, where we start to bring in pull request support. 1.0.x is more about bug fixing for 1.0.
