### ISSUE TITLE
Can't see any other branches in Branch Dropdown, please help!

### ISSUE THREAD

**Issue by atheimer** [desktop/desktop#2525]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by j-f1** [comment]
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #2522. Please follow that issue for further updates.

**Comment by iAmWillShepherd** [comment]
This is a duplicate of #2522

**Comment by shiftkey** [comment]
FYI: the `0.8.1-beta2` update is now available and contains this fix.
