### ISSUE TITLE
Make "Discard Changes" the default button in the modal

### ISSUE THREAD

**Issue by cheshire137** [desktop/desktop#2526]
A minor thing, but I think having the "Discard Changes" button selected by default instead of "Cancel" would be preferable. I don't think I would accidentally right-click the sidebar and choose to discard some changes; it feels like a very deliberate action I'd have to take. Because of that, it feels safe + convenient to make the default option in the confirmation modal to go ahead and discard those changes, rather than to cancel that action.

<img width="419" alt="github_desktop" src="https://user-images.githubusercontent.com/82317/29584766-611b47b8-874a-11e7-87d7-1b4bfedd92d6.png">

I'm in version 0.8.0 in macOS.

/cc @desktop/design

**Comment by shiftkey** [comment]
Cross-referencing discussion about the order of these buttons on Windows: #2463

**Comment by tierninho** [comment]
Brought this up in an earlier issue https://github.com/desktop/desktop/issues/1748 and here was Josh's response:

> Nope, this is right 😄 Because it's a destructive action, the Cancel button should be the default.

Feel free to rethink it 😄

**Comment by cheshire137** [comment]
I'd liken it to how you can make the Recycle Bin in Windows behave: by default when you try to delete a file, it will show a confirmation dialog. You can turn off that confirmation step, though, because choosing to delete something isn't a step you're likely to accidentally do. That feels the same as discarding files in this app: I intentionally do it, there isn't a big "DISCARD ALL" button I can accidentally click, so the confirmation just gets in my way.

**Comment by joshaber** [comment]
I wouldn't want to change the default button, but:

>You can turn off that confirmation step, though

I'd be into this 👍 We had this on Mac Classic too:

<img width="439" alt="screen shot 2017-08-31 at 1 23 09 pm" src="https://user-images.githubusercontent.com/13760/29936277-979be3ea-8e4f-11e7-848c-0a9904d6e2a4.png">

**Comment by j-f1** [comment]
The dialog could also do something similar to the system save-changes-on-quit dialog: <kbd>return</kbd> saves, <kbd>escape</kbd> cancels quitting, and <kbd>⌘</kbd>+<kbd>D</kbd> doesn’t save.

**Comment by iAmWillShepherd** [comment]
Just to clarify, are we going to keep the button order the same and add the _Do not show this message again_ option or are we changing the button order in addition to adding the option?

**Comment by joshaber** [comment]
>keep the button order the same and add the Do not show this message again option

☝️ this one
