### ISSUE TITLE
Please include GitHub for VS repos location

### ISSUE THREAD

**Issue by weitzhandler** [desktop/desktop#2528]
### Description

The Visual studio extension stores the repos in _%USERPROFILE%\Source\Repos_.
The Desktop GitHub app repos location should be the same, or at least include the VS repos automatically by default, when installing the app.

### Version

**GitHub Desktop version:** 0.8.0
**OS version:** Window 10.0.15063 Build 15063 Home x64

### Steps to Reproduce

1. Install VS extension and clone some repos
1. Install the Desktop app
1. No repos are there

**Comment by iAmWillShepherd** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our current roadmap.

I added the future-proposal label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by weitzhandler** [comment]
Thanks for your kind response!

**Comment by iAmWillShepherd** [comment]
You're welcome, be sure to keep an eye out on this issue in case it gets prioritized! 🎈

**Comment by billygriffin** [comment]
Hi @weitzhandler, thanks for the suggestion. We don't think there's a huge overlap of people who are using both GitHub for Visual Studio and Desktop to justify investing in making this *just work*, and we haven't heard it as something a lot of people feel like they'd benefit from. So I'm going to remove the `future-proposal` label. Hopefully cloning individually doesn't add too much friction to your normal workflow, and thanks again for the suggestion. We're happy to revisit if we see this popping up more regularly.
