### ISSUE TITLE
utf-8

### ISSUE THREAD

**Issue by Cirbles** [desktop/desktop#2540]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by tierninho** [comment]
@Cirbles Please fill out the template so we have more info to help you. Thanks.
