### ISSUE TITLE
Intellisense for issues by typing "#" failed with more than 30 open issues exist

### ISSUE THREAD

**Issue by grapehunter** [desktop/desktop#2541]
After cloning (or add) a repository, the app will try to get and save **all open issues** for Intellisense  by using API below.
> api/v3/repos/:owner/:repo/issues?state=open  

This API contains an invisible parameter named **per_page** with default value 30, that means you can only get 30 issues at a time.
And of course, you should iterate over the next 30 data until the end by using API below. 
> api/v3/repos/:owner/:repo/issues?state=open&page=2

or
> api/v3/repositories/:repoId/issues?state=open&page=2

But you made a mistake when you were calling this API.
I capture the http requests by fiddler.

![image](https://user-images.githubusercontent.com/3354458/29696840-f585bc3c-897d-11e7-8036-01cf9d395c90.png)

According to the screenshot above, you calling a wrong url with **duplicate "api/v3"**.
I just test this scenario with Mac app.

**Comment by shiftkey** [comment]
@grapehunter is this related to a GitHub or GitHub Enterprise repository?

**Comment by grapehunter** [comment]
@shiftkey GitHub Enterprise repository.  I have not test this issue with github repository.

**Comment by shiftkey** [comment]
@grapehunter thanks for confirming - I can reproduce this with a GitHub Enterprise repository and it comes down to [this line](https://github.com/desktop/desktop/blob/master/app/src/lib/http.ts#L87):

The "next page" header comes with the `/api/v3/` prefix, but the `endpoint` argument already has this prefix included, so it duplicates and errors.

**Comment by grapehunter** [comment]
@shiftkey 👍 & Thanks
