### ISSUE TITLE
Option to delete branch on remote is shown even when branch doesn't exist on remote

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#2543]
1. Delete a branch on the remote
1. Open GitHub Desktop and select the local version of the branch that was deleted on the remote
1. Delete the branch
1. Note that the option to delete branch on the remote is still shown even though it does not exist on the remote

We should only show that check box if the branch is indeed on the remote.

**Comment by wnjnz** [comment]
Is it okay if I take a stab at this?

**Comment by shiftkey** [comment]
@iAmWillShepherd I don't think we'll know the state of the remote branch without doing another fetch, but after that you'll get this message that the upstream ref has been pruned:

```
$ git status
On branch another-branch
Your branch is up-to-date with 'origin/another-branch'.
nothing to commit, working tree clean

$ git fetch --prune
From https://github.com/shiftkey/ha-ha-business
 - [deleted]         (none)     -> origin/another-branch

$ git status
On branch another-branch
Your branch is based on 'origin/another-branch', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)
nothing to commit, working tree clean
```

**Comment by iAmWillShepherd** [comment]
You are right, perhaps it's best to avoid that additional fetch. All we need is for changes to GitHub to be pushed to our app!
