### ISSUE TITLE
Expandable Description Box

### ISSUE THREAD

**Issue by Houdini111** [desktop/desktop#2546]
### Description

When writing longer descriptions, it can be hard to navigate the description properly due to size constraints. While it is possible to expand the description box horizontally (to a limited extent), there is no way to expand it vertically. 

### Version

**GitHub Desktop version:** 0.8.0

**OS version:** Microsoft Windows [Version 10.0.15063]

**Expected behavior:** The top edge of the box should be able to be dragged vertically to expand or shrink the box as needed. Or, at least, be a percent of the height of the window to expand if the GitHub Desktop window gets larger. 

**Actual behavior:** The box has no vertical size changing.

**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
We talked about a horizontal resizable component in #1646, so I'll fold this feedback into that issue. @Houdini111 please keep an eye on that issue.
