### ISSUE TITLE
Suggestion: Would be beneficial if icon shows a badge notification

### ISSUE THREAD

**Issue by mmehta-navomi** [desktop/desktop#2547]
### Description

Suggestion: Would be beneficial if icon shows a badge notification
### Version

**GitHub Desktop version:** 0.8.1-Beta 2

**OS version:** macOS Sierra 10.12.6

### Steps to Reproduce

None. This is suggestion rather than a bug. 
I used Github for Desktop quite often and like each and every feature it offers so far. One suggestion I would like to make is that, it would be better if Github desktop icon shows a badge if there is 'Pull' needs to be one or 'Push' that is waiting for user to do. I know you have notification with in the app but sometime those can be ignored if you don't open a app. A Badge would certainly help. 

**Expected behavior:** Some notification Badge need to show up on App icon

**Actual behavior:** No notification badge when there is Pull or Push requests waiting for repositories

**Reproduces how often:** 100%

**Comment by j-f1** [comment]
Just to clarify so that we discuss the right feature request:

You want the app icon in the Dock/taskbar to get a badge if there are commits on the remote that haven’t been pulled yet, correct?

**Comment by mmehta-navomi** [comment]
That's correct. Also, if items that are committed but haven't been pushed to remote. Badge would certainly help to notice something is waiting for an action (push or pull).

**Comment by iAmWillShepherd** [comment]
@mmehta-navomi , thanks for the suggestion. Adding a badge icon is certainly a good idea that would indeed be cool; however, the Windows and Linux (unofficially) versions of the app would not be able to take advantage of this feature. I will go ahead and mark this as future-proposal though so my team can discuss it further in the future.

Thanks again 🎉

**Comment by mmehta-navomi** [comment]
Ok. Thank you.

**Comment by billygriffin** [comment]
@mmehta-navomi Thanks for the suggestion! Based on feedback from users, we're not convinced that additional notifications/badges when you're not already in Desktop would be that useful. And since this is only macOS-specific, I don't think we've seen enough evidence to support it. I'm going to remove the `future-proposal` label as a result, and if we hear from users that they're dealing with problems where something like this would be beneficial, we're happy to revisit.
