### ISSUE TITLE
"picky" path selector when cloning

### ISSUE THREAD

**Issue by Exarchias** [desktop/desktop#2549]
Hello there.
I noticed that the path selector when cloning is bit picky and probably bit buggy.
It gives very easy the message "path already exists" and "not valid path destination" and it gives a headache to the user when the user is trying to set a path to clone his repository.
It must be some logical mistake behind it.
I apologize for my lazy submit, but it is easy to reproduce the mistake by just trying to clone a repository to a selected by the user folder.
I am using windows 10 and I have the latest version of Github Desktop, (version 0.8.0)
Best Regards.
Robert

**Comment by shiftkey** [comment]
@Exarchias could you please add some detailed instructions to illustrate the behaviour you are seeing with the path selector? While I'm familiar with that area I'd like to understand more about how you are using the app.

**Comment by shiftkey** [comment]
Closing due to inactivty.

@Exarchias if you could provide more details to help recreate the behaviour I'd love to revisit this issue.
