### ISSUE TITLE
Where is dark mode?

### ISSUE THREAD

**Issue by Hebgbs** [desktop/desktop#2557]
I know there are probably a few issues about this already but it's a legitimate question. If it's there in the legacy app, why isn't it there in the beta version pushed front-and-centre on the desktop page?

**Comment by shiftkey** [comment]
> If it's there in the legacy app, why isn't it there in the beta version pushed front-and-centre on the desktop page?

This has been deferred to post 1.0 for a couple of reasons:

 - this was a Windows-only feature
 - the design crew are limited on the work they can take on currently (you can see it all [here](https://github.com/desktop/desktop/projects/2))

We're aware this is a feature a lot of people like, and we're going to [learn from someone's contribution around this](https://github.com/desktop/desktop/pull/2111#issuecomment-312139213) once we free up some bandwidth.

Please follow along with #1515 for when we revisit this as part of our next planning session.
