### ISSUE TITLE
Slow diff rendering of large files causes app to be unresponsive

### ISSUE THREAD

**Issue by benrondeau** [desktop/desktop#2559]
### Description

When you select a large file (usually over 1mb, such as a `map` file), it can take 5-10 seconds for the UI to render a diff on the file and the UI is blocked from all input/output during this time. You can't use the application at all during this time.

I assume this is an intense computational process but can this be delegated to a service worker? This would get it off the main thread and prevent the UI from being blocked during rendering of the file's diff. If not, can the diff be rendered somehow without blocking the main thread?

Or perhaps an option to turn off diff rendering on larger files? You could display a message in the rendering window that says something like "_This is a large file and rendering a diff could take some time? Want to continue? Click here_." This isn't perfect but definitely better than having the application be unresponsive for 10 seconds while it renders a diff for a large file.

### Version

**GitHub Desktop version:** 0.8.1-beta2

**OS version:** Windows 7 Enterprise

### Steps to Reproduce

1. Select a large file, such a `map` file and notice the interface becomes unresponsive until the diff rendering is completed.

**Expected behavior:** UI is not blocked during diff rendering.

**Actual behavior:** UI is blocked during diff rendering

**Reproduces how often:** All the time.

#### Additional Information

Thanks!

**Comment by shiftkey** [comment]
@benrondeau thanks for the report - is there a public commit that I could use to test this out on my side?

See also #1686 which is similar behaviour.

**Comment by benrondeau** [comment]
#1686 Seems to be the exact same issue.

[I created a sample minified file](https://gist.githubusercontent.com/benrondeau/fc8063b543d5a841547e425498e543aa/raw/431356f773cb864744d79651bae66aad1b60a90f/app.min.js) that causes this to occur if you'd like to test it. But any large file seems to do it.

**Comment by shiftkey** [comment]
@benrondeau ok cool, thanks for confirming. Let's move the discussion over to #1686.
