### ISSUE TITLE
Unborn branch should not show branch `rename` and `delete` menu options

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2573]
If a new repo is created and the initial commit is undone, the Branch menu enables both `remove` and `delete` for `master`. 

Upon clicking either nothing happens as they both should remain disabled, unless the branch is not `master`.

Tested in 0.8.1-beta2, mac.

<img width="761" alt="screen shot 2017-08-29 at 1 05 37 pm" src="https://user-images.githubusercontent.com/14828183/29834026-88bcb2a4-8cbb-11e7-90b5-4c2b685750c9.png">

**Comment by shiftkey** [comment]
> enables both `remove` and `delete` for master.

@tierninho this should be `rename` rather than `remove`, right?

**Comment by tierninho** [comment]
> @tierninho this should be rename rather than remove, right?

Yes, oops. (I assume renaming should not be allowed, however one could argue either way.)

**Comment by tierninho** [comment]
Should the `New Branch` menu option also be grayed out? 

If the branch is unborn, I am getting a "fatal: Not a valid object name: 'master'." error message when attempting to create a new branch while the initial commit remains unpublished. 

Alternatively, the message could remain, albeit more user-friendly?

<img width="402" alt="screen shot 2017-09-05 at 8 06 48 am" src="https://user-images.githubusercontent.com/14828183/30051470-aedadf14-9211-11e7-9641-54d8b1ed80fe.png">

**Comment by joshaber** [comment]
>Should the New Branch menu option also be grayed out?

Yup, sounds like it 👍
