### ISSUE TITLE
No internet connection message for Enterprise users

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2574]
For .com user we flash a 'no internet connection message' when trying to publish a repo without a connection, yet for Enterprise we do not give the same message.

Seems like this message should include "check your internet connection" or we should use the same messaging for the .com user.
<img width="424" alt="screen shot 2017-08-29 at 1 58 41 pm" src="https://user-images.githubusercontent.com/14828183/29836208-83e9bacc-8cc2-11e7-960c-cfabbb9f16e7.png">

tested in 0.8.1-beta2, mac.

Reproduce:
- set up new repo to publish to Enterprise
- turn off internet and fill out Enterprise server to trigger messaging

**Comment by shiftkey** [comment]
If someone wants to look into this message, this is the code:

https://github.com/desktop/desktop/blob/c5b0d2ddcf945a265288a584bb53be483f966a54/app/src/lib/dispatcher/sign-in-store.ts#L226-L240

**Comment by agisilaos** [comment]
@shiftkey Looking into that right now, expect a PR from me regarding this issue, soon 🤓
