### ISSUE TITLE
Shell Choice from the GUI! (Also, proper SSH handling?)

### ISSUE THREAD

**Issue by mcmonkey4eva** [desktop/desktop#2577]
Running "`GitHub Desktop Version 0.8.0`" which is latest public at time of writing. (IE, the auto updater says I'm latest, and I'm not running any custom builds or anything)
On Windows 10.

---

I see some mentions in issues and PRs regarding shell choice, but I can't find for the life of me a button anywhere on the Beta Desktop GUI.

I can only find a button to open the windows command prompt, which is quite annoying.

I need it to either open powershell (Which the old github Windows client did), or git bash (Which iirc was as well an option before, and ships by default with any git-windows installation...)

Ideally there'd be a simple option somewhere to choose the user's favorite, and it would override the button that currently opens a command prompt.

ALSO: It would be incredibly helpful if the client ensured a valid SSH key was prepared when this was opened.
The old client did this automatically.

The SSH key is for:
- Pushing to github from command line.
- Easier interaction through github desktop + command line with alternate (SSH key only) git servers.

---

I like the work everyone's been doing here :)
These features above are critical to me being able to use the new client properly.
Let me know if I should split the above into two separate issues, I figured they're fairly well linked together.

**Comment by shiftkey** [comment]
@mcmonkey4eva you didn't miss something - the PR #2473 has been merged, letting you choose between Command Prompt, PowerShell or Git Bash on Windows (if installed), we're just doing a bit of testing before it makes it to the stable channel. Soon!

The issue about creating and registering a new SSH key isn't something that's currently supported in the app. I've added this to #2579, so you can track that there.
