### ISSUE TITLE
Why Rewrite? Comment

### ISSUE THREAD

**Issue by rayjos** [desktop/desktop#2580]
I read the article on:
How Four Native Developers Wrote An Electron App

It is wonderful that you have spent so much thought and effort into the desktop.

I just wanted to comment on concept that selecting web technology boiled down to fast feedback.  Fast feedback is great...necessary.  The justification was that one could maintain a thought through cycling.  While this is emotionally appealing, it may not provide the greatest value in the long run.  Automation and speed are critical.  But documenting concepts and accounting for design decisions provides prolonged value as other can benefit from the progress through more than just the existence of a finished product.  

As such, I am only commenting on the trade off of rapid development and maximized functionality.  How might these two different methods be modeled for systematic development?

Warm regards,
Ray

**Comment by shiftkey** [comment]
@rayjos thanks for the feedback - pun intended!

In addition to the goals around fast feedback, we also [have a suite of unit and integration tests](https://github.com/desktop/desktop/tree/master/app/test) that sit alongside the code to catch regressions, and [supporting documentation](https://github.com/desktop/desktop/tree/master/docs/technical) around more interesting parts of the codebase.

I'm not sure this is the right place for general discussions about software development, but let me know if you have any other questions about Desktop!

**Comment by rayjos** [comment]
Brendan,


Thank you for your prompt response.


It is great to understand that there were additional drivers for the selection process.  My concern was for public awareness.  The article suggested that speed of results was the essential driver.  Leading by example is our fundamental way of learning.  As such, it would have been valuable to state the multiple drivers to the decision - mostly that is wasn't frivolous speed of deployment.


I addressed this issue on this venue as it was the one recommended in the original article.


Communication is great, I appreciate your time.


Ray Joseph, PE
832 586-5854
ray@aarden.us



________________________________
