### ISSUE TITLE
Low contrast for colours in diff/Changes 

### ISSUE THREAD

**Issue by NiklasBr** [desktop/desktop#2586]
### Description

The red/green diff colours have a very low-visibility contrast, making them  hard to spot. As a related bug-fix/feature request I would like for the app to honour the [Accessibility settings for increased contrast](https://support.apple.com/kb/PH25218?locale=en_GB) which should make borders more pronounced.

See the attached image below where the Desktop app (on macOS) has the least contrast of the tree compared services.

![screen shot 2017-08-30 at 15 58 09](https://user-images.githubusercontent.com/279826/29876155-42e87646-8d9c-11e7-8735-5c1b82191648.png)

### Version

**GitHub Desktop version:** 0.8.0

**OS version:** macOS 10.12.6 (16G29)

### Steps to Reproduce

1. View the Changes of a file.

**Expected behavior:** Good, readable, contrasty colours.

**Actual behavior:** User squints all the time to see the colours. :)

**Reproduces how often:** Every time

### Logs

n/a
#### Additional Information

n/a

**Comment by tierninho** [comment]
@donokuda Thoughts?

**Comment by donokuda** [comment]
I agree. We should sync up our diff colors with what we use on the site given that they've chosen the colors with accessibility in mind.

> As a related bug-fix/feature request I would like for the app to honour the Accessibility settings for increased contrast which should make borders more pronounced.

I'd be interested to see if this is possible with Electron. If so, then we could override the border color with a darker value.

**Comment by shiftkey** [comment]
@donokuda I can't see anything accessibility related in Electron's [System Preferences API](https://electron.atom.io/docs/api/system-preferences/). There was a similar request in #1585 but like that one I suspect this needs a PR once we figure out which settings need to be read.

**Comment by NiklasBr** [comment]
Thanks for considering this!

I tried to do some research, and found that [some Windows support were added](https://github.com/electron/electron/pull/7518) in Electron, which in turn may or may not be an [issue inherited from Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=738292&q=component%3AUI%3EAccessibility&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified). Don't know if it helps.

**Comment by adamreisnz** [comment]
I'd like to add a comment from duplicate #2974 to ensure it's captured.

> The font in the new app is also lighter and smaller, further adding to the difficulties in reading it.

Compare old and new apps:

![image](https://user-images.githubusercontent.com/490562/31356797-d9629bdc-ad9b-11e7-823e-ac10a0366f4c.png)

**Comment by adamreisnz** [comment]
@niik Thanks for the work on this item and for increasing the contrast. Are you able to also have a quick look at the font thickness/color and see if you could bump that a bit darker as well (see above screenshots)?
