### ISSUE TITLE
setup forked remote repositories on clone

### ISSUE THREAD

**Issue by browner12** [desktop/desktop#2587]
### Description

In the previous version of desktop, when you cloned a forked repository it would setup both the origin and forked repos in the remotes.

`git remote -v`

### Version

**GitHub Desktop version:** 0.8.1-beta2

**OS version:** 10.12.6

### Steps to Reproduce

1. Fork a public repository.
1. Using Github Desktop, clone the forked repository to your local machine.
1. Run `git remote -v`

**Expected behavior:** The origin and upstream remotes are configured.

**Actual behavior:** Only the origin is configured.

**Reproduces how often:** 100

**Comment by shiftkey** [comment]
@browner12 thanks for the feedback. We're tracking this over in #2364, so please follow along with that issue.

**Comment by browner12** [comment]
thanks. sorry, should have looked first.
