### ISSUE TITLE
macOS app freezes on certain image previews

### ISSUE THREAD

**Issue by dret** [desktop/desktop#2590]
### Description

The macOS app freezes on perviews of certain images. It may be that transparent PNG triggers the bug. The app freezes and must be killed. It will reproducible freeze every single time.

### Version

**GitHub Desktop version:** Has been a bug for a long time. I have submitted many Apple crash reports for it.

**OS version:** various macOS over time.

### Steps to Reproduce

Image selected in left pane. Preview attempt in right pane. App freezes.

**Comment by shiftkey** [comment]
@dret which version of the app are you running?

**Comment by dret** [comment]
On 2017-08-30 21:02, Brendan Forster wrote:
> @dret <https://github.com/dret> which version of the app are you running?

the latest and greatest 223, but this has been the same bug since i 
started using the app quite a while ago.

**Comment by shiftkey** [comment]
@dret unfortunately this is the issue tracker for the new Electron app, which is intended to replace the classic macOS app. I'd like to confirm this problem doesn't affect the new application - is there a public sample repository or file to reproduce this issue?

**Comment by dret** [comment]
On 2017-08-30 21:10, Brendan Forster wrote:
> @dret <https://github.com/dret> unfortunately this is the issue tracker 
> for the new Electron app, which is intended to replace the classic macOS 
> app. I'd like to confirm this problem doesn't affect the new application 
> - is there a public sample repository or file to reproduce this issue?

my apologies. github support on twitter pointed be to this repo.

is there a different repo where i can submit the bug? it is very 
disruptive since when the app restarts and the image is on top in the 
left pane, the app crashes immediately again, ad infinitum, until you 
temporarily remove the image file and then start the app.

**Comment by dret** [comment]
but thanks for the pointer to the new app. i am downloading it now and will give it a try. afaict, the old one is still the "official" one, but if the switch is planned anyway, i might as well switch now.

**Comment by shiftkey** [comment]
@dret they can be installed side by side

**Comment by dret** [comment]
up an running! thanks for the pointer!

**Comment by shiftkey** [comment]
> github support on twitter pointed be to this repo.

If you use [this form](https://github.com/c) you can reach the support inbox for the classic app, but I fear this might not be resolved because of the focus on this new Electron app.

Feel free to open a new issue for any problems you encounter with the new app.
