### ISSUE TITLE
Check For Updates under Github Desktop Menu on Mac

### ISSUE THREAD

**Issue by agisilaos** [desktop/desktop#2593]
Please summarize the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

Now if you want to update the Github app for Mac you have to go trough a lot of steps & is not a common way to update an app like that in macOS. More info you will find below.

### Version

**GitHub Desktop version:** 0.8.0

**OS version:** macOS Sierra 10.12.6 (16G29)

### Steps to Reproduce

1. Github Menu
2. About Github
3. You see the check of updates button

**Expected behavior:** To not see the Check for updates button there.

**Actual behavior:** You see that button there

So my point is that the Check For Updates button it should be more natural & common to be under Github Desktop Menu -> Check for updates & not in the place that's exists right now. Would love to explain things more/ better if there's questions on this issue.

**Comment by tierninho** [comment]
Sounds like you want something like this:
<img width="191" alt="screen shot 2017-08-31 at 12 20 09 pm" src="https://user-images.githubusercontent.com/14828183/29933757-c80fb80c-8e46-11e7-94f0-74cd888c16ee.png">

**Comment by agisilaos** [comment]
Exactly!

**Comment by agisilaos** [comment]
Hey @joshaber I would love to work on that issue. I think it would be a good first step to get into Electron and contribute to Github Desktop. What you think? Already started setting up my environment  . 😻

**Comment by joshaber** [comment]
Thanks for wanting to help out @agisilaos and thanks for asking 💖 

Back In The Day (i.e., a few months ago) we had a "Check for Updates" menu item. It was removed in https://github.com/desktop/desktop/pull/1393:

>This also removes the update-related menu items from the App menu. They were never a good user experience for checking for updates. We now have a better 'Check for updates' flow in the About dialog as well as a nice unobtrusive update notification and periodic polling for new updates.

I don't think our opinion on that has changed. @desktop/design can correct me if I'm wrong.

Any issue in https://github.com/desktop/desktop/labels/help%20wanted or https://github.com/desktop/desktop/labels/bug should be safe to work on though!

**Comment by billygriffin** [comment]
Hi folks, since Desktop updates in the background and the explicit update is available in the "About" section, I'm going to close this. I noticed this was your first ever issue in desktop/desktop @agisilaos, and just wanted to say how grateful I am that you've since become such an integral part of our community. ❤️
