### ISSUE TITLE
introduce some soft limits around diff rendering

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#2596]
The client apps have historically been indifferent to large diffs, whereas GitHub the Website is very rigid about some diffs - requiring users to opt-in to view them.

<img width="1117" alt="screen shot 2017-09-01 at 9 14 53 am" src="https://user-images.githubusercontent.com/359239/29949143-0fb79382-8ef6-11e7-8b00-697ca6c86317.png">

As discussed in https://github.com/desktop/desktop/issues/1686#issuecomment-326443927 - there may be some diff sizes and shapes that make the editor cry (ridiculously long lines with wrapping enabled seems to be what currently hurts Codemirror). Until we have time to revisit our choice of diff experience (post 1.0 at least), I'd love to get some feels from @desktop/core on warning users about large diffs to keep things snappy.

For sake of simplicity and not using it as crutch, I'd rather not make this configurable at all to the user - for diffs over a certain size, display a message first and require the user to click to see it.

**Comment by joshaber** [comment]
👍 💯 

Large diffs like that are rarely meaningful too, so I doubt we're losing much.

**Comment by donokuda** [comment]
I'm also 👍 with not rendering large diffs by default.

**Comment by benrondeau** [comment]
Any update on this issue?

**Comment by joshaber** [comment]
@benrondeau Nothing yet, but this is the place to watch for updates!

**Comment by RichardM99** [comment]
+1

**Comment by joshaber** [comment]
Tentatively throwing this in 1.0.x.

**Comment by wes321** [comment]
![image](https://user-images.githubusercontent.com/1447845/32117531-b96c39d0-bb1c-11e7-90a4-42cfb82d5bde.png)
Thank you  👍
