### ISSUE TITLE
Launch coordination

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#2599]
We're getting close to shipping GitHub Desktop Beta's 1.0, at which time it'll turn into a Real Product and become just "GitHub Desktop." We're tentatively targeting the week of September 18th.

When that happens, we'll be deprecating the existing GitHub Desktop product. Users will still be able to use it, but we'll remove download links, taper off support, and [gently nudge them](https://github.com/desktop/desktop/issues/2146) to the new app.

---

- [x] Blog post - https://github.com/github/blog-posts/pull/1140
- [x] Update docs - https://github.com/github/help-docs/issues/5964
- [x] Update site - https://github.com/github/desktop.github.com/issues/78

**Comment by joshaber** [comment]
@desktop/core Am I missing anything here?

**Comment by j-f1** [comment]
You might want to add a small link to the footer to a page with the classic app downloads and a warning that they’re as-is with no support available.

**Comment by joshaber** [comment]
I don't think we want to provide a link to unsupported apps.

**Comment by joshaber** [comment]
Currently on target for 9/19.

**Comment by joshaber** [comment]
https://github.com/blog/2437-announcing-github-desktop-1-0 💥
