### ISSUE TITLE
Unable to connect after proxy change

### ISSUE THREAD

**Issue by jakepog** [desktop/desktop#2604]
### Description

The app does not recognise changed proxy server settings. Changing the network connection and disabling associated proxy server settings results in app network error. Pushing and fetching fail. 

### Version

GitHub Desktop version: [0.8.0]

**Microsoft Windows 7 Enterprise, SP 1:** [6.1.7601] 

### Steps to Reproduce

1. [Change network connection e.g. Ethernet > WiFi.]
2. [Disable proxy server in Control Panel > Internet Options > Connections > LAN Settings.]
3. [Check internet access in browser e.g. github.com]
4. [In GitHub Desktop, select repository and Fetch Origin.]
5. [Restarting app nor rebooting OS doesn't resolve.]

**Expected behavior:** [Syncing of repository.]

**Actual behavior:** [Fail with error, "fatal: unable to access _http://github.com/user/private_repository.git/_: Couldn't resolve proxy _proxy address_. Even when all proxy server settings is erased, restarted app, rebooted OS.]

**Reproduces how often:** [100%. Independent of network connection type and proxy settings.]

#### Additional Information

2017-09-02T01:03:06.600Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 2.386s)
2017-09-02T01:03:06.601Z - error: [ui] `git -c credential.helper= push origin master:master --progress` exited with an unexpected code: 128.
fatal: unable to access 'https://github.com/jakepog/private_repository.git/': Couldn't resolve proxy 'www-cache'

**Comment by joshaber** [comment]
Hi, sorry for the trouble! What happens if you try to visit `https://api.github.com/zen` in Chrome?

**Comment by jakepog** [comment]
`https://api.github.com/zen` returns the message "Half measures are as bad as nothing at all." in Chrome. 

`netsh winhttp reset proxy` returns 'Direct access (no proxy server).'

**Comment by joshaber** [comment]
That's really odd, I'm not sure why the app would be retaining proxy information on its own 🤔

**Comment by jakepog** [comment]
Perhaps it is a more global git config, as I have resolved the immediate problem through command line per answer here: `https://stackoverflow.com/questions/783811/getting-git-to-work-with-a-proxy-server`. In bash, `git config --global --unset http.proxy ` resolves Github Desktop pushing and pulling problems too. The question now is why git doesn't update from the system settings, and is this a reproducible problem?

**Comment by joshaber** [comment]
Oh great! It's actually more surprising to me that Git picked up the settings to begin with.

Since it sounds the immediate problem is fixed, I'm gonna close this. But please do let us know if you figure anything else out!

**Comment by jakepog** [comment]
Back behind the proxy, neither Github Desktop or git detected the change in network settings. I had to manually set it via command line again.

**Comment by sirusdynamo** [comment]
solved

checked the environment with
echo $http_proxy
echo $https_proxy
echo $HTTPS_PROXY
echo $HTTP_PROXY

and deleted the proxy

**Comment by adsk2050** [comment]
The same thing happened with me today. Even after I am changing the proxy settings through command line, I am getting HTTP 407 errror. I have an Ubuntu machine.

**Comment by shahbazsmartgit** [comment]
fatal: unable to access 'https://github.com/username/keyrings.git/': Failed to connect to mail id.com port 1080: Connection timed out
