### ISSUE TITLE
Stash uncommitted changes when switching between branches

### ISSUE THREAD

**Issue by notxcain** [desktop/desktop#2608]
### Description

On GitHub for Mac, when switching between from branch with uncommitted changes, the default behavior was to stash these changes and unstash them when you get back on branch. I really miss this behavior. It was very handy to quickly switch to some other branch.

### Version
**GitHub Desktop version:** 0.8.0
**OS version:** OS X 10.11.6

### Steps to Reproduce

1. Create new branch, e.g. `foo` from `master`
1. Change some files
1. Switch back to `master`

**Expected behavior:** There are no uncommitted changes

**Actual behavior:** I see uncommitted changes made on branch `foo`

**Reproduces how often:** Always

**Comment by niik** [comment]
Hi @notxcain, we're tracking this over in https://github.com/desktop/desktop/issues/1633, please subscribe there to follow along!
