### ISSUE TITLE
New Feature: Custom CSS

### ISSUE THREAD

**Issue by KyleKing** [desktop/desktop#2609]
**Concept:** With lower quality monitors and bright ambient lighting, the Github Desktop file-diff colors can be difficult to differentiate from the white background because of the low contrast. So I started developing a PR which would allow users to pick a custom CSS file and wanted to get community feedback on the new feature before continuing. Right now Github has plans to develop a dark mode (see a [PR request for a Dark Mode](https://github.com/desktop/desktop/pull/2111) and [another discussion](https://github.com/desktop/desktop/issues/2557#issuecomment-325230725)), but the limiting factor is their bandwidth to implement the feature compared to other higher priority tasks.

**Feature:** What if the alternative styling was user contributed? Users could create custom CSS file and share their version through a Github Gist. In Github Desktop, my PR adds a text input box to the advanced pane of the preferences UI. In the text box, any user can paste the link to a Github Gist (or path to a local CSS file) and the file would be downloaded and loaded by Webpack. Since the CSS file could be shared as a Gist, the latest version could be pulled to keep all users up to date.

**Examples:** There are several examples of custom CSS such as [Nylas/N1](https://github.com/nylas-mail-lives/nylas-mail#themes), a [plugin for Safari/Chrome/etc. called Stylish](https://userstyles.org), and not to mention all of the customization for Atom, Sublime, and other code editors.

I think this would be a cool feature and would be kind of fun to see what the open source community comes up with

**Comment by niik** [comment]
Hi @KyleKing, I'd personally like to see the ability to customize colors and (to some extent) other graphical aspects of the client. Accessibility is a great example of where this makes a ton of sense. That said we're not going to prioritize this until we've gotten [further along](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the future-proposal label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by billygriffin** [comment]
Hi @KyleKing, thanks for the issue! In 1.2.4 we made a dark theme available for Desktop, so hopefully that helps. I'm going to remove the `future-proposal` label here to indicate that we intend to continue to support and iterate on the two existing themes, but we don't intend to build out custom themes in the near future. Thanks again!
