### ISSUE TITLE
Empty `View on GitHub` placeholder showing on right-click

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2615]
When right-clicking a commit in History for an unpublished repo, the menu options include an empty placeholder for the `View on GitHub`. 

As the commit is still pending, the UI for this option should be adjusted.

<img width="702" alt="screen shot 2017-09-05 at 10 34 38 am" src="https://user-images.githubusercontent.com/14828183/30057477-587f5914-9226-11e7-8863-82dab70d4fb7.png">

Additionally, should SHA option be shown as well?

**Comment by joshaber** [comment]
Putting this in 1.0 👍 

>Additionally, should SHA option be shown as well?

I'm not sure I understand the question?

**Comment by tierninho** [comment]
@joshaber Sorry, I meant to say, should the `Copy SHA` in the pic still be visible if repo is unpublished?

**Comment by joshaber** [comment]
Oh yeah, that's fine. The SHA is meaningful still.
