### ISSUE TITLE
Warning message in New Repo modal asks to add an existing repo

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2625]
The warning message in the New Repo modal is asking me to add an existing repo, which would be redundant. 

Ideally, the local path should update as the user types the name of the new repo in.

Should we be checking to see if the repo exists before showing a warning?

<img width="823" alt="screen shot 2017-09-06 at 9 01 34 am" src="https://user-images.githubusercontent.com/14828183/30103757-19d76a5e-92e3-11e7-9eef-6f46b5353be4.png">

0.8.1-beta2, mac

https://github.com/desktop/desktop/blob/aebd9d8759c0b9894ecd6c03fdcdcc4364244b3f/app/src/ui/add-repository/create-repository.tsx#L377

**Comment by joshaber** [comment]
So the problem is that the enclosing directory is a repository already, but you want to create a new repository within it. Do I have that right?

**Comment by tierninho** [comment]
Yes and no. It wasn't my intention to do so, but here are better repro steps:

- add New Repository, click `Create Repository`
- Begin adding another repo with same name and path
- Click `add this repository` link in the warning message instead, as so:
<img width="776" alt="screen shot 2017-09-07 at 1 53 56 pm" src="https://user-images.githubusercontent.com/14828183/30166995-83f74584-93d4-11e7-97b1-6a1d5bea17aa.png">

- "loco-repo" created as the original repo already existed.
- `SetOptions.maxbuffer...` message appears multiple times
<img width="923" alt="screen shot 2017-09-07 at 1 54 16 pm" src="https://user-images.githubusercontent.com/14828183/30167058-b57b0cf8-93d4-11e7-8660-8f23c8943f30.png">

<img width="1138" alt="screen shot 2017-09-07 at 2 02 49 pm" src="https://user-images.githubusercontent.com/14828183/30167242-447f5c38-93d5-11e7-92ee-6e600dbfcbab.png">

**Comment by tierninho** [comment]
cannot repro
