### ISSUE TITLE
Option to handle multiple remotes

### ISSUE THREAD

**Issue by alwindoss** [desktop/desktop#2626]
### Description

Today though I add remote from the command-line I am only able to see the "origin" as the only remote using the Github Desktop client, I should be able to switch to different remote when required. A possible solution could be to have a drop down like we have for branch

### Version
0.8.0

**GitHub Desktop version:** [0.8.0]

**OS version:** [Microsoft Windows [Version 10.0.14393]]

### Steps to Reproduce

Not applicable

**Expected behavior:** [Should be able to switch between multiple remote repos]

**Actual behavior:** [Only able to use origin]

**Reproduces how often:** [100%]

**Comment by niik** [comment]
Hey @alwindoss, we're looking into ways of supporting more than the origin remote, see https://github.com/desktop/desktop/issues/1442. Our [immediate focus](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md), however, will be around forks and upstream remotes (this is what we're calling relationship to x). Once that's landed we'll revisit this issue. For now I'm going to close this and label it future-proposal to keep our issue list manageable.

**Comment by steveward** [comment]
Please follow along in https://github.com/desktop/desktop/issues/1442 for updates.
