### ISSUE TITLE
Fix JSX lambda functions in List

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#2628]
By creating a new lambda each time, we're forcing React to do some unnecessary work.

https://github.com/desktop/desktop/blob/55b01e4371b09b6021a41a9c0b33797b0641b0e9/app/src/ui/list.tsx#L475-L482

**Comment by shiftkey** [comment]
I _think_ the problem here is that these lambdas need to be scoped to `rowIndex`, but I'd happily be proven wrong.

**Comment by joshaber** [comment]
Yeah, that's exactly the problem. So we need to create a `RowItem` component or some such that knows its row index and can pass it back up.
