### ISSUE TITLE
Stop auto-commit with message of initial commit

### ISSUE THREAD

**Issue by CodyHenrichsen-CTEC** [desktop/desktop#2632]
### Description

Creating a local repository makes a default commit with a message of "initial commit"

### Version

**GitHub Desktop version:** [0.8.0]

**OS version:** [10.12.6]

### Steps to Reproduce

1. New Repository
1. Type name of folder/path
1. Create repository

**Expected behavior:** [What you expected to happen]
A repository is made with option to specify a commit message/description and adjust settings including .gitignore

**Actual behavior:** [What actually happened]
all files/folders in the specified folder are added to the repo by default and an initial commit is made.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

**Comment by niik** [comment]
Hey @CodyHenrichsen-CTEC,

Yes, we automatically create the initial commit when a gitignore template, readme file, or license is selected when creating the repository. If you wish to modify the initial commit you can undo it by clicking on the 'Undo' button below the commit message form.

![image](https://user-images.githubusercontent.com/634063/30150802-1d7d1166-93ad-11e7-9a40-7215cf7fbdf3.png)

That will let you modify the contents of each of the committed files as well as the message without creating a new commit should you so choose.

**Comment by CodyHenrichsen-CTEC** [comment]
Sweet!

________________________________
