### ISSUE TITLE
Login to a VisualStudio.com Repo fails with a organizational account

### ISSUE THREAD

**Issue by Wenish** [desktop/desktop#2636]
### Description

If u try to login to a repo from visualstudio.com with a organizational account the authentication fails

### Version

**GitHub Desktop version:** 0.8.0

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Add local repository (choose a repo from visualstudio.com)
2. Fetch origin
3. Fill out the Authentication failed form
4. Save and retry

**Expected behavior:** When u typed in ur email u should be forwarded to ur company login so u can login corectly.

**Actual behavior:** u wont get forwarded and microsoft trys to auth ur company account which obviously fails

**Reproduces how often:** 100%

### Logs

[2017-09-07.desktop.production.zip](https://github.com/desktop/desktop/files/1283703/2017-09-07.desktop.production.zip)

**Comment by niik** [comment]
We currently support the same authentication methods that Git itself supports for non-GitHub repository hosts which in practice means http basic auth. If your host (in this case Visual Studio Online) requires you to perform a web flow authentication you're going to have to create a personal access token from the website and use that as your password, see https://www.visualstudio.com/en-us/docs/setup-admin/team-services/use-personal-access-tokens-to-authenticate.
