### ISSUE TITLE
better UX in Merge Branch dialog when there are no other branches

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2637]
Should we be displaying the Branch > Merge into Current Branch.. option if `master` is the only branch. 

Suggest we grey it out until minimum of two branches ... thoughts?

0.8.1-beta3, Mac

<img width="862" alt="screen shot 2017-09-07 at 9 26 22 am" src="https://user-images.githubusercontent.com/14828183/30156310-daeecdec-93ae-11e7-8972-bc2eb47267e9.png">

**Comment by joshaber** [comment]
My initial thought is that letting the user open the dialog and see they have no other branches is clearer than disabling the menu item.

@desktop/design what do you think?

**Comment by niik** [comment]
> @desktop/design what do you think?

My gut feeling concurs, we shouldn't disable the menu item. That said the merge branch dialog with no other branches than the current isn't great either. I think we could add some UX around that case to make it :sparkles: but unfortunately that'll have to be fairly low down on our list of priorities right now.
