### ISSUE TITLE
Show Repository List menu option also hides the list

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2638]
The `Show Repository list` menu option (⌘T) shows the list as intended, when selected, but it also hides the list, which should be disabled. The other menu selections under the View top-level nav do not function the same, so all actions should be uniform.

Also, the repo list should close if the user selects either `Show Changes` or `Show Branches` from the View menu. Currently they open in the background, behind the Repository list.

<img width="488" alt="screen shot 2017-09-07 at 12 54 14 pm" src="https://user-images.githubusercontent.com/14828183/30164495-4b53d40c-93cc-11e7-81b2-de31aa87864d.png">

tested 0.8.1-beta3, mac

**Comment by shiftkey** [comment]
Related issue #2502 and fix for that #2532 introduced this behaviour

**Comment by joshaber** [comment]
I'm inclined to say that all of those "Show _X_" menu items should really toggle their foldout.

**Comment by j-f1** [comment]
They should probably change to “Hide {foo}” when the foldout is opened.

**Comment by shiftkey** [comment]
I'm going to call this an enhancement more than a bug because it requires work to pass the menu state from the renderer to the main process.

**Comment by shiftkey** [comment]
I think we should only worry abou `Show/Hide Branch List` and `Show/Hide Repositories List` for these menus. `Show Changes` and `Show History` should hide the active popover, if any exists. I say this because `Hide Changes ` or `Hide History` don't make sense from a navigation perspective.

**Comment by j-f1** [comment]
The changes/history items could have checkboxes that toggle between them as needed.

**Comment by tierninho** [comment]
> Also, the repo list should close if the user selects either Show Changes or Show Branches from the View menu. Currently they open in the background, behind the Repository list.

If the Repo list is open, the user can advertently commit a file(s) if one is lying in wait and the user tabs over to the commit button (behind the repo list). Outlier use case, but still not ideal.

**Comment by JordanMussi** [comment]
> I'm inclined to say that all of those "Show X" menu items should really toggle their foldout.

Agreed.

> I think we should only worry abou Show/Hide Branch List and Show/Hide Repositories List for these menus. Show Changes and Show History should hide the active popover, if any exists. I say this because Hide Changes or Hide History don't make sense from a navigation perspective.

No need to worry about the first two either since when you open a menu foldout the open foldout is closed. So you can't have a situation where you have the View menu open when the repositories/branches list foldout is open.
