### ISSUE TITLE
Differentiate conflicted files from other changed files

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#2640]
Design TBD

**Comment by j-f1** [comment]
I think it already does this with a ⚠️ icon instead of the +/-/• icon.

**Comment by joshaber** [comment]
Yeah that's true. We're already doing the bare minimum, but we need to do better.

The problem is that merges can bring in _tons_ of changed files and finding the conflicted ones is a needle-in-the-haystack situation. We need a better way of distinguishing the conflicted files from the other changes brought in by the merge.

For example, that could mean filtering, grouping, something else entirely, etc.

**Comment by niik** [comment]
We talked about this and we think that a good first step is, as has been previously suggested, to sort them ahead of other changed files. Individually they'll still be sorted alphabetically but they'll be visually grouped together. We think that'll make a big difference.

**Comment by j-f1** [comment]
Maybe something like what Atom does ([see this video](https://github.atom.io/videos/github-feature-resolve-conflict.webm) for an example).

**Comment by saul** [comment]
Any plans to add the sorting? This bites me on a weekly basis - a merge brings in 100s changed files and about 3 conflicts. It's pointless trying to find it in the UI - I'm happy to do the code myself.

**Comment by j-f1** [comment]
Everything that doesn’t have the `needs-design-input` label or an assignee is fair game for a pull request. Feel free to contribute!

**Comment by joshaber** [comment]
...which reminded me I needed to add `needs-design-input` to this 😄

**Comment by j-f1** [comment]
It looks like we already had some design thoughts:

[@niik above](https://github.com/desktop/desktop/issues/2640#issuecomment-333904936):
> We talked about this and we think that a good first step is, as has been previously suggested, to sort them ahead of other changed files. Individually they'll still be sorted alphabetically but they'll be visually grouped together. We think that'll make a big difference.

**Comment by joshaber** [comment]
Fair enough 👍

**Comment by billygriffin** [comment]
I'm going to roll this into #5400 as well, and I'll bring over the design thinking from @niik there as well.
