### ISSUE TITLE
Pull request CI status

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#2643]
Show PRs CI status in the pull request list.

Designs TBD. Probably dependent on https://github.com/desktop/desktop/issues/2642.

**Comment by niik** [comment]
So I misinterpreted this issue initially so the design for this is actually incorporated in #2642.

![](https://user-images.githubusercontent.com/634063/30381166-ecce2fe8-989b-11e7-874b-d2947c8136aa.png)

CI status right aligned and vertically centered in the row with 10px margin to the text and `$red-800`, `$green-800` and `$orange-700` for the colors

**Comment by j-f1** [comment]
Looks great!

:two: questions:

1. Where can I click to open the PR on GitHub.com?
2. What happens when I click on the status indicator?
