### ISSUE TITLE
Auto-config upstreams on fork

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#2644]
* Add an `upstream` remote to forked repositories
* Include in the periodic fetch

Designs TBD

**Comment by joshaber** [comment]
Is this something we'd do silently and automagically, or would we ask the user similar to LFS setup?

<img width="422" alt="screen shot 2017-09-05 at 2 54 32 pm" src="https://user-images.githubusercontent.com/13760/30077658-86fc47d8-924a-11e7-9d94-9e27faa2b952.png">

**Comment by j-f1** [comment]
I opened an issue about this in #2364, too.

**Comment by joshaber** [comment]
Oh nice! I'll roll this into that then.
