### ISSUE TITLE
1.1 go go go

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#2645]
Somehow, 1.0 is [really darn close](https://github.com/desktop/desktop/milestone/7) to being done. On to the next one!

![giphy-3](https://user-images.githubusercontent.com/13760/30167414-52702640-93b4-11e7-8c50-efc2faa3d3dd.gif)

## Finishing 1.0

Given how little remains to be done for 1.0, my suggestion is that one person stick around to finish off 1.0 while the rest of us start on 1.1. I'm happy to do that since it'll involve a lot of cross-team coordination, but if someone else really wants to do it, they are welcome 😄 

We might need to pull someone back for bug fixing once 1.0 is out, but we can play that by ear 👂 Depending the volume, the first responder might be able to handle it.

## On to 1.1

I created some 1.1 issues based on [the roadmap](https://github.com/desktop/desktop/blob/552c752609862122932f3c28fc37dd9b104f6290/docs/process/roadmap.md#11) and tossed them in the [1.1 milestone](https://github.com/desktop/desktop/milestone/11).

@desktop/design are working on mocks and we should start getting some soon. In the meantime, for functionality that is fairly well-defined, I think we can use the same [salmon pink brutalist](https://github.com/desktop/desktop/pull/233) approach we used in the early days:

<img width="520" alt="screen shot 2016-08-05 at 5 25 57 pm" src="https://cloud.githubusercontent.com/assets/13760/17451026/b58930da-5b31-11e6-8a9d-58c374971cc5.png">

This'll let us start implementing the underlying functionality without being blocked on designs.

I think [Pull request list](https://github.com/desktop/desktop/issues/2642), [Set conflict resolution tool](https://github.com/desktop/desktop/issues/68), and [Add an upstream to forked repositories](https://github.com/desktop/desktop/issues/2364) are all candidates for this.

## Feature flagging

At our mini-summit, we agreed on using feature flags to land work on `master` that shouldn't be publicly viewable yet. @shiftkey landed [a PR](https://github.com/desktop/desktop/pull/2538) which adds an API to do just that. That would apply for all 1.1 work.

## Wrap up

So the plan I propose is:

1. One person finishes 1.0, everyone else starts on 1.1.
1. Salmon-pink brutalism 🐟🤘 
1. Branches still target `master`.
1. Features for 1.1 should be feature flagged.
1. Features for 1.1 can land undesigned or rough, pending designs.

---

As always, any/all of this is up for discussion. Thoughts? Questions? Concerns? Does this sound like a reasonable way forward?

/cc @desktop/core

**Comment by shiftkey** [comment]
![](https://user-images.githubusercontent.com/359239/30189908-24fbd486-947a-11e7-89e6-267fab48870e.gif)

**Comment by joshaber** [comment]
1.0's out and 1.1 is underway. I think this issue served its purpose 🎉
