### ISSUE TITLE
Background fetch causes selection in repo list to jump

### ISSUE THREAD

**Issue by adamreisnz** [desktop/desktop#2651]
CC @shiftkey
Ref #2451 

A minor issue, but annoying when it happens.

1. Open repo list with <kbd>command</kbd> + <kbd>T</kbd>
2. Go to a repo that you haven't been in for a while
3. Hit enter
4. Immediately hit <kbd>command</kbd> + <kbd>T</kbd> again and use <kbd>down</kbd> to select another repo
5. Observe that the first repo you opened is auto fetching
6. When it's done fetching, it will move the repo selection in the sidebar to the repo that you had first opened, causing your selection to jump to that location

I've captured this behaviour in a gif, hopefully it's clear. The first time I open the repo list after fetch is complete, and it works as expected. The second time, I open it while fetch is in progress, and you can see as I'm moving the selection down one by one, it suddenly jumps forward to angular-seed.

![desktop](https://user-images.githubusercontent.com/490562/30194861-d3f19e24-94a9-11e7-91de-1fab347d1ac6.gif)

It's unlikely to be a major issue on account of it being unlikely you will want to open another repo right after you opened the first one, but it could happen if you selected the wrong one, or if you happen to open a repo when the fetch is in progress.

**Comment by Barathwaja** [comment]
is this still open?

**Comment by adamreisnz** [comment]
Yes, I can confirm that this still happens in the latest version.

**Comment by billygriffin** [comment]
Hi @adamreisnz, thanks for this issue as well! As this hasn't been a thing we've seen from users largely and you pointed out that it is relatively infrequent, would you be ok if I close it as it hasn't had a lot of interest and I haven't seen it reported by other users? I'm hopeful that not getting bogged down in smaller things that are low pain and very infrequent will help us make faster progress on delivering things of higher value for folks. Let me know your thoughts.

**Comment by adamreisnz** [comment]
Yes no problem, I don't think it's been a major issue lately, at least I can't recall it happening frequently 👍
