### ISSUE TITLE
I cannot clone an existing project from GITHUB to my repository. there is an authentication failure

### ISSUE THREAD

**Issue by mprizzo** [desktop/desktop#2654]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by niik** [comment]
Hey @mprizzo, could you please fill out the issue template and provide some logs so that we can help debug this?

**Comment by mprizzo** [comment]
where do I find the issue template and the logs?

**Comment by niik** [comment]
@mprizzo The issue template is the text in the body of your issue. Basically you'd fill out the parts that are enclosed in brackets (`[` `]`)

![image](https://user-images.githubusercontent.com/634063/30204812-19db21e4-9487-11e7-82ed-5885161e3366.png)


> the logs?

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\GitHub Desktop\logs\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

**Comment by mprizzo** [comment]
Description:
![clone0](https://user-images.githubusercontent.com/1315696/30208579-71184506-9494-11e7-9b8d-a94bf77936bc.PNG)
![clone1](https://user-images.githubusercontent.com/1315696/30208581-73baf056-9494-11e7-8c3e-6876423fe6fd.PNG)
![clone2](https://user-images.githubusercontent.com/1315696/30208586-764aff8c-9494-11e7-8e33-7af8d14f9b45.PNG)
![clone3](https://user-images.githubusercontent.com/1315696/30208594-7b6ce840-9494-11e7-9593-cbdbe87b1b74.PNG)

**Comment by mprizzo** [comment]
![image](https://user-images.githubusercontent.com/1315696/30208772-41b089b2-9495-11e7-9e91-d77ac7f02dc4.png)

**Comment by tierninho** [comment]
@mprizzo Looks like https://github.com/ot-angola is not a repository, please try one of your 8 repositories, for example: https://github.com/OT-ANGOLA/boundary
