### ISSUE TITLE
Ignoring files on an unborn branch

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2656]
When a user uses `right-click` to ignore (one or more) files on an unborn branch, the files do not "disappear" from the Changes tab as they are supposed (under a Publish repo). Only upon commit of the `.gitignore` file, do the ignored files "disappear".

Note, this applies to both `Ignore` and `Ignore all x Files` options upon right-clicking. Not 100% of what the correct outcome should be.

Reproduce:
- Create new repo
- undo first commit
- try to ignore a file other than `gitignore`
- if you commit only `gitignore`, the other files are removed on Changes tab

<img width="781" alt="screen shot 2017-09-08 at 1 09 04 pm" src="https://user-images.githubusercontent.com/14828183/30213220-9ccbd250-9497-11e7-8fa8-a252e2d5782c.png">
<img width="726" alt="screen shot 2017-09-08 at 1 12 53 pm" src="https://user-images.githubusercontent.com/14828183/30213302-f9b1e1ee-9497-11e7-9c5e-083bb0b498f8.png">

tested in 0.8.1-beta4. mac osx.

**Comment by kristianpo** [comment]
tierninho opened this Issue a day ago · 0 comments

**Comment by shiftkey** [comment]
This is related to the behaviour of `Undo Commit`, not sure why we didn't pick this up before but whatever, nice corner case:

  - `git update-ref -d HEAD` on the first commit will leave all the files staged
  - you can't ignore a file once it's been staged, as Git is tracking this (related to #2537)
  - you need to `git rm --cached` the staged files to then be able to ignore them
