### ISSUE TITLE
Diffs for moved files

### ISSUE THREAD

**Issue by pforhan** [desktop/desktop#2658]
### Description

When a file is renamed or moved, only the new content is shown, as 100% added lines. 

### Version

**GitHub Desktop version:** Hasty Things Done Hastily (223)

**OS version:** MacOS 10.12.6

### Steps to Reproduce

1. Rename a file with an IDE or git mv
1. Check that entry in github desktop

**Expected behavior:** Either the old file should show up (with 100% deleted lines) or, more usefully, a diff between the old file and new.

**Actual behavior:** filename UI indicates that a move happened, but the diff view is all additions.

**Reproduces how often:** 100%

#### Additional Information

Similar in general to #980

**Comment by shiftkey** [comment]
@pforhan this repository is for issues with the new Electron client. Please use [the contact form](https://github.com/c) to get in touch with our support team about the classic apps.
