### ISSUE TITLE
Install antvel to my computer

### ISSUE THREAD

**Issue by omara256** [desktop/desktop#2661]
Hello,
  Am trying to install antvel on my computer for learning reasons but am failing to install antvel.
i created i cloned and created a repo, so i have the file but i can't seem to get antvel installed in composer, it gives a an error that Uncaught Error: Class 'Symfony\Component\Console\Application' not found
![cd](https://user-images.githubusercontent.com/31730890/30237604-4b263da8-953e-11e7-9d7d-6175f5f19a89.PNG)

**Comment by shiftkey** [comment]
@omara256 you should open an issue against the Antvel project: https://github.com/ant-vel/App
