### ISSUE TITLE
Use the system emoji instead of images

### ISSUE THREAD

**Issue by j-f1** [desktop/desktop#2670]
### Description

1. When entering a commit message, typing `:` then autocompleting an emoji inserts the :shortcode: instead of the actual emoji. This should only happen if the user has entered a proprietary emoji (like `:octocat:` :octocat:)
2. The 👍  emoji appears as <img src="https://user-images.githubusercontent.com/25517624/30249308-f96342fc-9607-11e7-8d83-9851f9714402.png" alt=":+1:" height="16">, which doesn’t look as nice.

### Version

**GitHub Desktop version:** 42b9453eb3b2091cf8f743a96d781b2113804b87

**OS version:** 10.12.3 (16D32)

### Steps to Reproduce

1. Enter `:+1` into the commit message box
1. Accept the 👍 suggestion
1. Note that `:+1:` is inserted, not `👍`
1. Commit
1. Note that the commit message shows <img src="https://user-images.githubusercontent.com/25517624/30249308-f96342fc-9607-11e7-8d83-9851f9714402.png" alt=":+1:" height="16"> instead of 👍

**Expected behavior:** The commit message in the entry field shows `👍`, and the commit in the history view shows `👍`

**Actual behavior:** The commit message in the entry field shows `:+1`, and the commit in the history view shows <img src="https://user-images.githubusercontent.com/25517624/30249308-f96342fc-9607-11e7-8d83-9851f9714402.png" alt=":+1:" height="16">

**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
Fair warning, emoji rendering across OSes varies wildly. Here's Edge on Windows 10:

<img width="520" src="https://user-images.githubusercontent.com/359239/30256122-b1c879d2-96eb-11e7-8217-6652cfd065f1.png">

And here's Chrome on Windows 7 (yep, it's not rendering the characters):

<img width="507" src="https://user-images.githubusercontent.com/359239/30256202-3e54c36a-96ec-11e7-9a41-373c0a0531d7.png">

**Comment by j-f1** [comment]
That’s probably because the `monospace font`doesn’t support them. Still, good point!

**Comment by shiftkey** [comment]
Adding `future-proposal` to this and closing it out to tidy up our backlog. We will revisit this in our next planning session, but I think this is a relatively low priority unless a contributor wants to dig into it and implement fallbacks for platforms that don't support native emoji (or whatever definition we settle on for emoji support).

**Comment by billygriffin** [comment]
Thanks @j-f1! I think this is very similar to the open issue https://github.com/desktop/desktop/issues/4385 and captured there (and referenced now) so I'm going to remove future proposal here.
