### ISSUE TITLE
Option to automatically fetch before commit

### ISSUE THREAD

**Issue by jeffg2k** [desktop/desktop#2673]
### Description

Sometimes I forget to fetch before I commit, resulting in a "Merge branch 'master'".  It would be nice if before committing, it allowed the option of fetching first (particularly if it can see there are no conflicts and completely different files).  Maybe it could build upon options mentioned in #1128.

Would be nice if it could do it automatically if there are no conflicts and possibly prompt if there are conflicts asking if they want to continue.

### Version

**GitHub Desktop version:** 0.8.1
**OS version:** OSX 10.12.6

### Steps to Reproduce

1. Click commit while there are fetches queued 
1. Fetch commits to the repo and then has to go through the merge master process

**Expected behavior:** Allow option to fetch updates before it commits to prevent the merge master.

**Actual behavior:** Commits and then merge master.

**Reproduces how often:** 100%

**Comment by j-f1** [comment]
It might also be good to have a `pull --rebase` option too, so that there aren’t merge commits lying around.

**Comment by joshaber** [comment]
>Sometimes I forget to fetch before I commit, resulting in a "Merge branch 'master'".

Does this cause some sort of problem? I'm trying to understand the root problem to solve here.

**Comment by jeffg2k** [comment]
No, I guess it's more cosmetic.  I'm not even sure why GitHub shows it in commit history unless there is a conflict.  It's one of those underlying git things that nobody really cares to see.  It's like a yellow light when everything is green.

**Comment by mischnic** [comment]
I think jeffg2k means pull and not fetch, so committing before pulling (and doing this oftenresults in many merge commits).

> Expected behavior: Allow option to **pull** before it commits to prevent the merge master.

This might be an extreme example (you don't want to see the network view):
![bildschirmfoto 2017-09-11 um 17 33 32](https://user-images.githubusercontent.com/4586894/30283087-6982b148-9717-11e7-9f74-7eadec8219b3.png)

Generally, this is the users's fault.


> I'm not even sure why GitHub shows "Merge branch 'master'" in commit history unless there is a conflict.

This is not how git works, you should have used `pull --rebase` as j-f1 said.

**Comment by jeffg2k** [comment]
pull --rebase sounds like some command line deep into git weeds stuff that gets in the way.  If it should do a pull --rebase, then do it behind the scenes - I don't need to know about it.

**Comment by joshaber** [comment]
These are interesting ideas for the future, but beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
We're going to be looking at supporting `pull --rebase` in #5953 so I'm going to remove the future proposal label here. Thanks y'all.
