### ISSUE TITLE
Selecting Issue in Summary doesn't autofill issue number

### ISSUE THREAD

**Issue by jeffg2k** [desktop/desktop#2674]
### Description

When you type #, GitHub Desktop provides you with a list of issues.   But if you select one of the issues, it doesn't populate the number for you.  I just have to use it as a reference and type the number myself.

### Version

**GitHub Desktop version:** 0.8.1
**OS version:** OSX 10.12.6

### Steps to Reproduce

1. Start typing a summary and type #.
1. Click on one of the issues
1. The summary does not populate the issue number

**Expected behavior:** I expect that when I click on the issue, it should populate the summary with the issue number.

**Actual behavior:** Nothing happens when you click the issue.

**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
Oops, this is totally a regression. Not sure what happened, but we should get this in for 1.0.
