### ISSUE TITLE
Selecting a block of text in a diff shifts upon moving window pane

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2677]
If you select a specific sentence in a diff, then expand or collapse the `file list` pane, the selected text will shift to another random snippet of text within that diff.

Ideally, the text selected initially should hold. (Note: moving any pane slider can reproduce this bug.)

0.8.1-beta4, mac

<img width="861" alt="screen shot 2017-09-11 at 9 55 18 am" src="https://user-images.githubusercontent.com/14828183/30269266-c71c7e82-96d7-11e7-9d17-11a1aadc7ec0.png">
<img width="856" alt="screen shot 2017-09-11 at 9 55 29 am" src="https://user-images.githubusercontent.com/14828183/30269267-c745026c-96d7-11e7-93c6-344755a4c107.png">

**Comment by joshaber** [comment]
O_o

This looks like a bug at the Codemirror level :hurtrealbad:

**Comment by j-f1** [comment]
Maybe this is an incentive to switch to a custom implementation that uses something like [highlight.js](https://highlightjs.org/) and splits the code into individual lines in a virtualized `List`.

**Comment by shiftkey** [comment]
> This looks like a bug at the Codemirror level :hurtrealbad:

We're a few versions behind the latest version of Codemirror. Maybe it's been fixed upstream?

**Comment by shiftkey** [comment]
Still occurring in `5.29.0`
