### ISSUE TITLE
UX for filters and expanding long descriptions

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2680]
User experience for filters is not consistent across the app, as the Repo and Branch list behave differently. If the Repo list filter is populated, the text is maintained if the user closes the list and returns later. The Branch list is cleared upon each visit. 

<img width="325" alt="screen shot 2017-09-11 at 1 23 49 pm" src="https://user-images.githubusercontent.com/14828183/30276627-fc8a0c02-96f4-11e7-99f8-9165d4e28958.png">

Expanding a long description clears the diff until the description is collapsed. Just wanted to point this out as wasn't sure if it was by intention.

<img width="880" alt="screen shot 2017-09-11 at 1 25 58 pm" src="https://user-images.githubusercontent.com/14828183/30276651-0b801e68-96f5-11e7-91a5-e6e0baa897fc.png">

**Comment by joshaber** [comment]
Yeah, both of these are intentional. We _might_ persist the branches filter depending on feedback, but for now I think it's fine.
