### ISSUE TITLE
Open in Terminal has no effect for non-GitHub hosted repos

### ISSUE THREAD

**Issue by kcmckell** [desktop/desktop#2682]
### Description

The menu item Repository->Open in Terminal works as expected for repositories that are local clones of repos hosted on GitHub.

However, this same workflow does not open a Terminal window/tab when activated from a local-only git repo.

### Version

**GitHub Desktop version:** 0.8.1

**OS version:** OS X 10.12.6

### Steps to Reproduce

1. Set the Current Repository to a repo that exists on the local machine and not on GitHub (listed under "Other" in the sidebar.
1. From the Repository menu, select Open in Terminal.
1. **crickets**

**Expected behavior:** Terminal application should be activated and "cd" to the local path of the repo.

**Actual behavior:** Nothing

**Reproduces how often:** 2/2 for the non-GitHub repos I have.

### Logs

No logs generated today.

#### Additional Information

Can't think of anything else.

**Comment by iAmWillShepherd** [comment]
Thanks for submitting this issue. Unfortunately, I am unable to reproduce it following your steps. Could you send your logs please?

**Comment by kcmckell** [comment]
Thanks for the quick response.  Is there a way to activity logging?  The most recent log files I see in ```~/Library/Application Support/GitHub Desktop/logs``` are from July.

**Comment by kcmckell** [comment]
Aha!

I've narrowed the bug: It only manifests on local repos with whitespace in the path.

**Comment by joshaber** [comment]
Great catch @kcmckell! We'll take another look.
