### ISSUE TITLE
Minimize tooltip doesn't disapear after minimize

### ISSUE THREAD

**Issue by mrbouyou** [desktop/desktop#2683]
V0.8.1-beta4 desktop on Windows 10

Everytime i click on the top-right minimize button i get a sticky "minimize" tooltip that won't disapear.
I have to minimize from the taskbar to not get this bugy tooltip

**Comment by joshaber** [comment]
Thanks for the report, @mrbouyou!

It looks like this is a bug in Electron, the framework on which the app is built. It looks like they're already tracking it in https://github.com/electron/electron/issues/9943, so I'm gonna close this one.
