### ISSUE TITLE
Can't select new local path after moving repo's parent folder

### ISSUE THREAD

**Issue by cmrberry** [desktop/desktop#2685]
### Description

After moving the parent folder of my repository into a new location, I'm unable to update the location for the repositories in Desktop. Trying to do so just gives an error in console. I'm able to remove and then re-add them, but not just update the location.

### Version

**GitHub Desktop version:** 0.8.1
**OS version:** macOS 10.12.6

### Steps to Reproduce

1. Open a local repo in Desktop
2. Open that repo in Finder
3. Move the repo's *parent* folder to a new location
4. Go back to Desktop and get the "Can't find..." error
5. Click the "Locate..." button to choose the new location
6. Select the location and click "Open"

**Expected behavior:** Desktop should re-open the repository with the new path.

**Actual behavior:** The repo doesn't become available in Desktop with the new path. An error with "Unable to find path to repository on disk" appears in Console.

**Reproduces how often:** Every time I follow those steps.

![desktop_locate](https://user-images.githubusercontent.com/7971632/30294578-6c9a1756-96f2-11e7-929e-32417a4ad04b.gif)

### Logs

None present.

#### Additional Information

<details>
<summary>Here's the full console entry:</summary>

```
git-process.js:82 Uncaught (in promise) Error: Unable to find path to repository on disk.
    at git-process.js:82
    at exithandler (child_process.js:224)
    at ChildProcess.errorhandler (child_process.js:236)
    at emitOne (events.js:96)
    at ChildProcess.emit (events.js:191)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213)
    at onErrorNT (internal/child_process.js:367)
    at _combinedTickCallback (internal/process/next_tick.js:80)
    at process._tickCallback (internal/process/next_tick.js:104)
(anonymous) @ git-process.js:82
exithandler @ child_process.js:224
errorhandler @ child_process.js:236
emitOne @ events.js:96
emit @ events.js:191
ChildProcess._handle.onexit @ internal/child_process.js:213
onErrorNT @ internal/child_process.js:367
_combinedTickCallback @ internal/process/next_tick.js:80
_tickCallback @ internal/process/next_tick.js:104
```
</details>

**Comment by joshaber** [comment]
This is a great write-up, thanks @cmrberry!
