### ISSUE TITLE
External editor: no editors found with vs15&17, win10 1703

### ISSUE THREAD

**Issue by ijesonchen** [desktop/desktop#2691]
### Description
env:
windows 10 pro, 1703, August updated.
visual studio 2015 & 2017 installed.
 Open in external editor menu, prompt no suitable editors installed to lunch and try install atom.

### Version

**GitHub Desktop version:** [0.8.1]

**OS version:** [10.0.15063]

### Steps to Reproduce

1. right click repo
1. open in external editor
1. got error: unable to open external editor.

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Logs

2017-09-12T07:13:10.618Z - info: [ui] Stats reported.
2017-09-12T07:13:16.168Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.268s)
2017-09-12T07:18:40.014Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.092s)
2017-09-12T07:21:52.117Z - error: [ui] Error checking for updates
Error: Command failed: 4294967295
System.AggregateException: ����һ���������� ---> System.Net.WebException: �� WebClient �����ڼ䷢���쳣�� ---> System.IO.IOException: �ļ���C:\Users\user\AppData\Local\GitHubDesktop\packages\GitHubDesktop-0.8.1-delta.nupkg��������һ����ʹ�ã���˸ý����޷����ʴ��ļ���
   �� System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   �� System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   �� System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   �� System.Net.WebClient.DownloadFileAsync(Uri address, String fileName, Object userToken)
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.FileDownloader.<DownloadFile>d__2.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.UpdateManager.DownloadReleasesImpl.<>c__DisplayClass2_0.<<DownloadReleases>b__1>d.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.UpdateManager.DownloadReleasesImpl.<DownloadReleases>d__2.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.UpdateManager.<DownloadReleases>d__8.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Update.Program.<Download>d__7.MoveNext()
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   �� System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   �� System.Threading.Tasks.Task`1.get_Result()
   �� Squirrel.Update.Program.executeCommandLine(String[] args)
   �� Squirrel.Update.Program.main(String[] args)
   �� Squirrel.Update.Program.Main(String[] args)
---> (�ڲ��쳣 #0) System.Net.WebException: �� WebClient �����ڼ䷢���쳣�� ---> System.IO.IOException: �ļ���C:\Users\user\AppData\Local\GitHubDesktop\packages\GitHubDesktop-0.8.1-delta.nupkg��������һ����ʹ�ã���˸ý����޷����ʴ��ļ���
   �� System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   �� System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   �� System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   �� System.Net.WebClient.DownloadFileAsync(Uri address, String fileName, Object userToken)
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.FileDownloader.<DownloadFile>d__2.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.UpdateManager.DownloadReleasesImpl.<>c__DisplayClass2_0.<<DownloadReleases>b__1>d.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.UpdateManager.DownloadReleasesImpl.<DownloadReleases>d__2.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.UpdateManager.<DownloadReleases>d__8.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Squirrel.Update.Program.<Download>d__7.MoveNext()<---

    at AutoUpdater.emitError (C:\Users\user\AppData\Local\GitHubDesktop\app-0.8.0\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:58:24)
    at squirrelUpdate.download (C:\Users\user\AppData\Local\GitHubDesktop\app-0.8.0\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:34:21)
    at C:\Users\user\AppData\Local\GitHubDesktop\app-0.8.0\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:89:14
    at ChildProcess.<anonymous> (C:\Users\user\AppData\Local\GitHubDesktop\app-0.8.0\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:71:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
2017-09-12T07:24:05.150Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.230s)
2017-09-12T07:29:33.111Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.192s)
2017-09-12T07:34:59.231Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.311s)
2017-09-12T07:40:24.081Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.161s)
2017-09-12T07:48:24.585Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 157.664s)
2017-09-12T07:53:48.967Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.049s)
2017-09-12T07:59:22.783Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 10.859s)
2017-09-12T08:02:13.159Z - warn: [ui] Unknown URL action: unknown - payload: {"name":"unknown","url":"--squirrel-firstrun"}
2017-09-12T08:02:19.346Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.770s)
2017-09-12T08:02:34.365Z - warn: [ui] Unknown URL action: unknown - payload: {"name":"unknown","url":"--squirrel-firstrun"}
2017-09-12T08:04:15.723Z - info: [ui] Opt out reported.
2017-09-12T08:07:56.660Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.043s)

#### Additional Information

In some old version, win7 pro sp1 with vs13&vs15, when repo selected, I got open in visual studio menu, and it works. I don't remember the version, but it got quite different look with version 0,8

**Comment by shiftkey** [comment]
@ijesonchen the "Open in External Editor" experience in the new application is around opening the current repository - VS2013 and VS2015 do not currently support opening to a folder. The classic Windows application supported opening solution files, which is different to what we targeted for 1.0. We've focused on supporting Atom, VSCode and Sublime as these support opening a folder and are available on Windows, macOS and Linux.

We're discussing other plans in #2487 - please add your feedback there.
