### ISSUE TITLE
can not fix repo list window in UI

### ISSUE THREAD

**Issue by ijesonchen** [desktop/desktop#2692]
### Description

I got repo list when click "Current repository"， but the windows can not be fixed. when I select a repo, the list windows disappears.

### Version

**GitHub Desktop version:** [0.8.1]

**OS version:** [windows 10 pro 10.0.15063]

### Steps to Reproduce

1. click "Current repository", repo list appears.
1. select a repo, the repo list is gone.

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by shiftkey** [comment]
@ijesonchen this is a duplicate of #1593 - please follow along with that issue
