### ISSUE TITLE
Error in newest beta build: The filter.lfs.clean attribute should be "git-lfs clean -- %f"

### ISSUE THREAD

**Issue by mayel** [desktop/desktop#2693]
### Description

My Github desktop beta just updated to the latest release, and I'm now getting this error on launch:

The filter.lfs.clean attribute should be "git-lfs clean -- %f" but is "git lfs clean %f"
Run `git lfs install --force` to reset git config.

### Version

**GitHub Desktop version:** 0.8.1

**OS version:** macOS 10.13 Beta (17A360a)

I also use homebrew and have git 2.14.1 installed via brew.

**Comment by shiftkey** [comment]
@mayel I think you might have been using an older version of `git-lfs` that now clashes with the latest version we've bundled. Can you confirm the version of `git-lfs` you have via homebrew by attaching the output from this command:

```
$ brew list git-lfs
```

I think the advice from that error is what needs to be done, but I'd like to confirm whether we need to handle this in the app. cc @joshaber for feels.

**Comment by mayel** [comment]
@shiftkey I don't have git-lfs installed via brew (and trying to install it fails due to a SHA256 mismatch)

Running the command suggested by the app returns "git: 'lfs' is not a git command."

**Comment by shiftkey** [comment]
@mayel any other Git tools installed on your machine? It sounds like something has added things to your `~/.gitconfig`, whether you have `git-lfs` installed or not.

**Comment by mayel** [comment]
I have the following in my ~/.gitconfig but not sure where it came from. Should I just remove it? 

[filter "lfs"]
        clean = git lfs clean %f
        smudge = git lfs smudge %f
        required = true
        process = git-lfs filter-process

**Comment by shiftkey** [comment]
@mayel you can remove it - Desktop should install itself again on next launch and make that error go away

**Comment by mayel** [comment]
Thanks @shiftkey, that worked.

**Comment by shiftkey** [comment]
@mayel excellent!

**Comment by joshaber** [comment]
Hmm, this makes me think we should include `--force` in our args when we silently install LFS at the global level, for those who have old/messed up setups.

**Comment by shiftkey** [comment]
@joshaber I can get behind that

**Comment by joshaber** [comment]
Though if someone's purposefully _not_ upgrading LFS for some reason, that would make life hard for them.

**Comment by joshaber** [comment]
Yeah, so I think we wanna detect this case and ask the user if we should use `--force` or leave it alone.

**Comment by joshaber** [comment]
Opened https://github.com/desktop/dugite/pull/123 so that we can parse this error.

**Comment by jorisw** [comment]
FWIW I had this problem today with GitHub Desktop 2.6 and removing the lfs filter from `~/.gitconfig` as suggested above resolved the problem.

**Comment by ownmas** [comment]
I have the same problem with GitHub Desktop 2.6.1, but i don't have lfs in gitconfig

**Comment by gwilku** [comment]
The issue is back with GitHub Desktop for Windows.
The solution: 

> WARNING: the "filter.lfs.clean" attribute should be "git-lfs clean -- %f" but is "git lfs clean %f"
> Run `git lfs install --force` to reset git config.

does not apply to Windows version.

Please advise and consider adding platform-specific error messages & troubleshooting.

**Comment by danaavesar** [comment]
> [filter "lfs"]
>         clean = git lfs clean %f
>         smudge = git lfs smudge %f
>         required = true
>         process = git-lfs filter-process

How do I access this file?

**Comment by jorisw** [comment]
Could be `~/.gitconfig` or `yourproject/.git/config`. Use a Terminal or IDE to find and edit the file.

**Comment by danaavesar** [comment]
I am also getting this error when I open Github Desktop on Mac. I updated git on the terminal to the latest version and I also uninstalled and reinstalled the desktop version but I am still getting the error. 

I tried to find the ~/.gitconfig file but couldn't find it. I am not very familiar with terminal and don't know how to edit it from there. I tried to write this "~/.gitconfig" and it says Permission denied.

**Comment by danaavesar** [comment]
Ok, I managed to open and edit it with this command: open ~/.gitconfig. 
I also had what @mayel had in his file:
 [filter "lfs"]
        clean = git lfs clean %f
        smudge = git lfs smudge %f
        required = true
        process = git-lfs filter-process
