### ISSUE TITLE
diff flickering when cursoring up/down with only one file

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#2695]
### Description

When there is one file in the changes list, or one file in the commit details, you can up/down in the list and make the diff flicker due to re-rendering.

### Version

**GitHub Desktop version:** 1.0.0-beta0
**OS version:** macOS Sierra (also reproducible on Windows 10)

### Steps to Reproduce

1. Take an existing repository
1. Modify one file so it appears in the changes list
1. Select that file in the changes list
1. Press up/down

Alternatively

1. Take an existing repository
1. Find a commit that changes exactly one file
1. Select that file in the commit file list
1. Press up/down

**Expected behavior:** no change to file selection, no unnecessary re-rendering of the diff

**Actual behavior:** file diff is re-rendered, appearing as flickering to the naked eye

**Reproduces how often:** 100%

**Comment by tierninho** [comment]
Fixed as of v1.6, ,mac
