### ISSUE TITLE
Add "Open in External Editor" to the No Changes view

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#2701]
We already give users the option of opening the repository in Finder/Explorer:

<img width="304" alt="screen shot 2017-09-12 at 2 40 52 pm" src="https://user-images.githubusercontent.com/13760/30342606-708f20e6-97c8-11e7-8083-4dba4950e984.png">

But more often, I wanna open it in my external editor. So it'd be great to have an "Open in X" button there too.

**Comment by joshaber** [comment]
@niik and I talked about this and he mentioned that it might be a good opportunity to rethink this "No changes" view a bit to be more positive.

**Comment by ncoe** [comment]
I too would like to open files in an external editor like notepad++. Requiring a specific external program does not make sense to me.

**Comment by shiftkey** [comment]
@ncoe we tried to get this in earlier but it seems like the Notepad++ command line experience doesn't let you open a folder like other editors do: https://github.com/desktop/desktop/pull/4120#issuecomment-369901927

**Comment by ncoe** [comment]
Opening a changed file in an external editor was my actual use case, which does work in the latest version when I try it. The prior version just opened the file browser, so I am actually satisfied with the behavior. Carry on :)

**Comment by tierninho** [comment]
@billygriffin In light of https://github.com/desktop/desktop/issues/5686 is this issue still relevant?

**Comment by billygriffin** [comment]
Nope, thanks @tierninho. Superseded by @niik’s work in #5686.
