### ISSUE TITLE
"Open in Visual Studio" button disappeared

### ISSUE THREAD

**Issue by ChadLevy** [desktop/desktop#2703]
### Description

"Open in Visual Studio" button disappears after installing Visual Studio 2017 and uninstalling Visual Studio 2015.

### Version

**GitHub Desktop version:** Chocolate-Covered Yaks (3.3.4.0) 50415df

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. With Visual Studio 2015 installed, install Visual Studio 2017.
1. Uninstall Visual Studio 2015.
1. Observe "Open in Visual Studio" is no longer present.

**Expected behavior:** "Open in Visual Studio" button remains and opens .sln file in either latest version of Visual Studio or in the Visual Studio version selector.

**Actual behavior:** "Open in Visual Studio" button disappears

**Reproduces how often:** 100%. This has happened on both my desktop and laptop with identical configurations.

**Comment by joshaber** [comment]
Hi @ChadLevy, that looks like an issue with the classic GitHub Desktop for Windows app. This repository is for the GitHub Desktop Beta redesign on Electron.

We're tracking GitHub Desktop Beta's ability to open more editors in https://github.com/desktop/desktop/issues/2487.
