### ISSUE TITLE
History section not appear!!

### ISSUE THREAD

**Issue by sherlylovers** [desktop/desktop#2706]
### Description

[Description of the issue]
The newest version of github is history section is cannot appear!!

### Version

**GitHub Desktop version:** [version here]
version 0.8.2

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]
History section on github desktop cannot appear
![1](https://user-images.githubusercontent.com/29877531/30354607-167a7950-9860-11e7-8035-30c230ee63db.png)

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by shiftkey** [comment]
@sherlylovers could you attach the latest logs by opening the **Help** menu and selecting **Show logs in explorer** - the logs within that folder should be organized by date.

**Comment by sherlylovers** [comment]
![2](https://user-images.githubusercontent.com/29877531/30356645-aa4371ee-986c-11e7-9fe4-351c50f6ad97.png)

**Comment by shiftkey** [comment]
@sherlylovers did this get resolved?

**Comment by sherlylovers** [comment]
i still cannot see history section after update the latest version

**Comment by shiftkey** [comment]
@sherlylovers could you attach the contents of the files? There are some interesting errors in there that have been cut off by the screenshot...

**Comment by sherlylovers** [comment]
what content of the files??

**Comment by shiftkey** [comment]
@sherlylovers the contents of the log file from that screenshot

**Comment by sherlylovers** [comment]
![3](https://user-images.githubusercontent.com/29877531/30363262-16ff36fe-9892-11e7-91c2-c31b68d662c0.png)
![4](https://user-images.githubusercontent.com/29877531/30363263-17228f6e-9892-11e7-876b-a41e163176ba.png)
![5](https://user-images.githubusercontent.com/29877531/30363264-1731b908-9892-11e7-979b-eaae1bf92914.png)
![6](https://user-images.githubusercontent.com/29877531/30363265-1754f788-9892-11e7-95f5-2773e130a77c.png)
![7](https://user-images.githubusercontent.com/29877531/30363266-1764b40c-9892-11e7-945c-017eac9aa9a5.png)

**Comment by sherlylovers** [comment]
@shiftkey
