### ISSUE TITLE
Missing first character while copy code in diff panel

### ISSUE THREAD

**Issue by lekhasy** [desktop/desktop#2709]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** 0.8.0

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Change any text file in the repo
1. View diff on github desktop
1. Select some text and press Ctrl+C
1. Goto another text editor and press Ctrl+V

**Expected behavior:** Normal copy - paste behavior

**Actual behavior:** The received text missing the first character

**Reproduces how often:** 100%

### Logs

[2017-09-13.desktop.production.zip](https://github.com/desktop/desktop/files/1298152/2017-09-13.desktop.production.zip)

**Comment by shiftkey** [comment]
Please update to `0.8.2` as this has been fixed in #2499.
