### ISSUE TITLE
New repo: Add description field

### ISSUE THREAD

**Issue by jsejcksn** [desktop/desktop#2719]
### Description

The New Repository dialog is _almost_ just like on the web, except that it lacks a description input field. I've included screenshots at the bottom of this post to juxtapose the two.

I understand the input of the description field to go to two places upon creation of a repo on the web:

  - The description field below the repo title
  - The line below the title in `README.md` if "Initialize this repository with a README" is selected before selecting "Create repository".

It is also my understanding that the description field is specific to GitHub.com repositories, as it does not go into the [`.git/description` file](https://git-scm.com/docs/gitweb#gitweb-descriptionorcodegitwebdescriptioncode) for gitweb, as discussed in [isaacs/github#485](https://github.com/isaacs/github/issues/485). However, it would be convenient to avoid having to utilize the website to manually input the repo description after publishing a new repo.The desktop client could handle this by doing the following:

  1. Allow the user to input a description string below the title (like on the web)
  2. Save it somewhere until the user publishes the repo (someone on the team will know the best location for this—maybe there's already a place—but if not, perhaps at `.git/info/gh-description`?)
  3. As a step of publishing the repo, [set the description field of the repo](https://developer.github.com/v3/repos/#edit) to the user-input string

If this is implemented, then the repo creation for desktop will be in complete parity with the web. 🙌

### Version

**GitHub Desktop version:** 0.8.2

**OS version:** macOS 10.12.6

#### Screenshots

Desktop:  
<img width="400" alt="desktop" title="desktop" src="https://user-images.githubusercontent.com/868251/30399157-54680f6a-9898-11e7-859c-923490f1460e.png">

Web:  
<img width="745" alt="web" title="web" src="https://user-images.githubusercontent.com/868251/30399163-581a5640-9898-11e7-8f53-07d67d41a4b7.png">

**Comment by j-f1** [comment]
Since the repository isn’t automatically published to GitHub, where would you suggest storing it in the meantime? Also, the publish dialog does include a description box.

**Comment by jsejcksn** [comment]
@j-f1 Thanks for responding. I think you're referring to the macOS HIG doc for [Push Buttons](https://developer.apple.com/macos/human-interface-guidelines/buttons/push-buttons/).

If the app is really efforting to follow these guidelines, then aren't many of the other interface aspects that make it consistent across platforms also in violation of them? I see another just in regard to the buttons in that dialog: **Adjust a push button’s width to accommodate the title**.

In this context, I see that consistency between platforms and adherence to macOS HIG seem to be at odds in many cases. Has there been an established position by the team on the ordering of these two priorities? Having an answer to that question might help me (and others) understand whether some platform inconsistencies are intentional or not.

**Comment by jsejcksn** [comment]
@j-f1 I am not aware of the storage architecture of the desktop app or of the specifics of git repository layout, but I did make a suggestion in my original post. See no. 2.

**Comment by joshaber** [comment]
Good catch, thanks @jsejcksn!

On the topic of storage, Git actually has a little-known `.git/description` file we could use.

**Comment by jsejcksn** [comment]
@joshaber I mentioned in my original post the discussion at [isaacs/github#485](https://github.com/isaacs/github/issues/485#issuecomment-149551106), in which @jakirkham said this

> I got a response from GitHub and would like to roughly summarize it here.
>
> The `.git/description` is managed locally and its content is not shared. In short, this would require a change to `git`.

Has something changed about the described situation since then?

**Comment by joshaber** [comment]
I know this is totally my fault, but I don't wanna get too hung up in implementation details right now. My thinking which could be totally wrong, is that when you create a new repository, it exists only locally. So we could store the entered description in `.git/description`. And then when you publish the repository, we can auto populated the description from there.

**Comment by joshaber** [comment]
And indeed, that's exactly what @davidcelis did in https://github.com/desktop/desktop/pull/2723 😆

**Comment by jsejcksn** [comment]
@joshaber Definitely. Hopefully none of that came off as pedantic—I was just trying to make a suggestion for better UX. 😄

**Comment by joshaber** [comment]
Nope, no worries!
