### ISSUE TITLE
Discard changes deletes file instead of discarding changes

### ISSUE THREAD

**Issue by sdwebguy** [desktop/desktop#2721]
### Description

I created a new branch off master and made changes to a TXT file. I then used Desktop to discard changes. It deleted the file on disk and showed the delete would be in the commit. It did not just discard my changes as expected. Reproducible.

### Version

**GitHub Desktop version:** 0.8.0

**OS version:** Windows 10.0.15063

**Comment by joshaber** [comment]
Really weird, it sounds like something went wrong in the step where we restore the previous version.

Could you grab your log files from `%APPDATA%\GitHub Desktop\logs\*.desktop.production.log` and drop them in here?

**Comment by sdwebguy** [comment]
@joshaber Here is my log file from today as it just rolled over (I renamed it to .txt so I could attach it here.) I opened GitHub Desktop, branched off master, made a small CSS change, discarded changed, and the file was gone. Nothing appeared in the log until I closed the application after manually putting the file back into the repo.


[2017-09-14.desktop.production.log.txt](https://github.com/desktop/desktop/files/1301682/2017-09-14.desktop.production.log.txt)

**Comment by joshaber** [comment]
Thanks @sdwebguy!

```
2017-09-14T04:01:31.645Z - error: [ui] `git reset --mixed HEAD -- membercentral/assets/common/css/main.css` exited with an unexpected code: 128.
warning: --mixed with paths is deprecated; use 'git reset -- <paths>' instead.
fatal: Unable to create 'C:/WWWRoot/.git/index.lock': File exists.
```

This is the important entry. It looks like there's an `index.lock` file still sitting around for some reason. Delete that file and it should start working as intended.

**Comment by sdwebguy** [comment]
@joshaber  Actually I think that was something else.

Here is what I just did:
1. Open Github Desktop
2. Branch off master
3. Edit a file and make a change. Change shows up in Github Desktop
4. Right click on file in Github Desktop, select discard changes. Click Discard changes button.
5. File is immediately deleted from disk and shows as deleted file in my branch. There is no index.lock file in my .git folder.
6. I closed Github Desktop and there is nothing written in the log file. Still no lock file.
7. I opened Github Desktop and put the file back into the repo, and my branch shows no changes now. Still nothing in the log.

**Comment by joshaber** [comment]
Huh... that's really odd. @desktop/core any theories?

**Comment by sdwebguy** [comment]
Any ideas? I have to switch clients to SourceTree just to discard changes.

**Comment by shiftkey** [comment]
@sdwebguy I need more details to recreate the issue on my end. In particular this step:

> Edit a file and make a change. Change shows up in Github Desktop

What change was made, and how does it show up in Desktop?

Also, a fresh log file to go with the repro would help understand what's happening underneath.

**Comment by sdwebguy** [comment]
@shiftkey Ive tried this with any type of file -- images, txt files, HTML files, all results in the same issue.
I looked at the log files once I opened Github Desktop and there were no entries in the log so I dont have anything to send to you.

I did record a video showing it happening.

[SampleVideo.zip](https://github.com/desktop/desktop/files/1328214/SampleVideo.zip)

**Comment by shiftkey** [comment]
@sdwebguy thanks for the video. Can you confirm you're on `1.0.1` as well?

**Comment by sdwebguy** [comment]
![image](https://user-images.githubusercontent.com/945871/30814023-d16b077c-a1c3-11e7-8093-c6a15f73fb6e.png)

**Comment by shiftkey** [comment]
I'm still trying to figure out this repro, but talking about the discard changes steps might yield some clues as to what's happening on your setup. In the Dev Tools you can set the Console output to **Verbose** - maybe this will show some clues as to what's not firing for your setup?

<img width="459" src="https://user-images.githubusercontent.com/359239/30839370-c3cc12e0-a2b4-11e7-8f77-01d3547bd843.png">

1. For files that aren't deleted, we invoke Electron's `shell.moveItemToTrash` to preserve the file contents in case you want to go back to that version. That's what's causing the file to be removed from disk for you. But the subsequent steps should restore this file to the previous state.

2. After deleting these new and modified files, we check to see what changes are currently tracked in the index:

```
Executing getIndexChanges: git diff-index --cached --name-status --no-renames -z HEAD
```

3. For files that are staged in the index, we do a reset --mixed. You probably won't see this command, as I don't believe the file was staged (accidental or otherwise) before discarding.

```
Executing reset: git reset --mixed HEAD -- README.md
```

4. Lastly, we should copy files from the index to the working directory, using `checkout-index` and passing in the list of files as standard input.

```
Executing checkoutIndex: git checkout-index -f -u -q --stdin -z
```

@sdwebguy do you see these Git commands when you enable the verbose output in the console and run through those steps? If one of these is failing, that might explain why it's not restoring your file.

**Comment by sdwebguy** [comment]
@shiftkey I see entries and captured them. There were 2 getIndexChanges calls, a git reset call, but no checkoutIndex call. I attached a video and a screenshot of the relevant section of the verbose logging.

![image](https://user-images.githubusercontent.com/945871/30871572-2555d910-a29c-11e7-9173-55f58f57a7bf.png)
[VerboseLogging.zip](https://github.com/desktop/desktop/files/1333922/VerboseLogging.zip)

**Comment by sdwebguy** [comment]
@joshaber I saw that #2764 was included in a recent release, so I am now on 1.0.3 and tried my same workflow as above. While the file deletion still happens, I now immediately get an error dialog box popup with an error message as well when I click on the discard changes action:

```
git reset HEAD --stdin -z` exited with an unexpected code: 128.
fatal: ambiguous argument 'HEAD': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
error @ install.ts:23
```

So now my verbose looks like this:

```
Executing getIndexChanges: git diff-index --cached --name-status --no-renames -z HEAD
install.ts:35 Executing getIndexChanges: git diff-index --cached --name-status --no-renames -z 4b825dc642cb6eb9a060e54bf8d69288fbee4904
install.ts:35 Executing resetPaths: git reset HEAD --stdin -z
install.ts:23 `git reset HEAD --stdin -z` exited with an unexpected code: 128.
fatal: ambiguous argument 'HEAD': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

error @ install.ts:23
t.git @ core.ts:172
_tickCallback @ internal/process/next_tick.js:109
install.ts:35 Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z
install.ts:35 Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes
install.ts:35 Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 --
install.ts:35 Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- membercentral/robots.txt
install.ts:35 Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color --not --remotes
install.ts:35 Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT
```

**Comment by shiftkey** [comment]
@sdwebguy thanks for following up, this is _very_ interesting!

```
fatal: ambiguous argument 'HEAD': both revision and filename
```

This should help reproducing the issue at least. Is this a public repository on GitHub that I can poke at? If not, is there a file named `HEAD` at the root of the repository?

**Comment by sdwebguy** [comment]
@shiftkey This is not a public repo, but yes there is a HEAD at the root of the repo. This new fatal error was introduced in 1.0.3.

**Comment by shiftkey** [comment]
@sdwebguy I've opened #2938 to track that introduced error, but it'd be neat to get more information about the repository contents to uncover the underlying issue, if you can share it...

**Comment by sdwebguy** [comment]
@shiftkey Looking forward to trying it out when it gets released!

**Comment by sdwebguy** [comment]
@shiftkey @joshaber Confirmed this has fixed the issue of discarding changes deleting the file from the repo. Thanks!

**Comment by joshaber** [comment]
Great, thanks for letting us know @sdwebguy!

**Comment by Rubinhuang9239** [comment]
Get my work from entire last week just deleted with same operation.
During my initial push. No more backup, was trying to use Github for backup. Awesome.

**Comment by shiftkey** [comment]
@Rubinhuang9239 could you open a new issue and fill out the template?
