### ISSUE TITLE
Desktop does not use repository's PULL_REQUEST_TEMPLATE.md template

### ISSUE THREAD

**Issue by willmorgan** [desktop/desktop#2729]
### Description

Desktop does not use repository's PULL_REQUEST_TEMPLATE.md template

### Version

**GitHub Desktop version:** Hasty Things Done Hastily (223)

**OS version:** macOS 10.12.6 (16G29)

### Steps to Reproduce

1. I created a repo locally
2. Added it to GitHub Desktop
3. Pushed it to GitHub (manually via remotes etc)
4. Added a `.github/PULL_REQUEST_TEMPLATE.md` file.
5. Created a branch to create a pull request from.

**Expected behavior:** I'd expect to see the pre-populated template in the description box.

**Actual behavior:** It's blank. But on the web interface, it's present.

![image](https://user-images.githubusercontent.com/168688/30425425-1d2a5e28-9941-11e7-93e4-b6df4c5a2e53.png)

**Reproduces how often:** 100%

#### Additional Information

Interestingly it required a restart of my machine in order for GitHub Desktop to recognise it as a GitHub repository - before then, it was treated generically. But the issue persists regardless.

**Comment by joshaber** [comment]
Hi @willmorgan! 😄 It looks like this issue is with the Classic Mac app, but this repository is for issues with the redesigned GitHub Desktop (see https://desktop.github.com).

Since the redesign doesn't include the same PR integration (yet, at least), this issue doesn't apply so I'm gonna close it.

**Comment by willmorgan** [comment]
Oops. Okay, I've filed this with GitHub support instead.

**Comment by j-f1** [comment]
@joshaber Can you put that comment in `issue-triage`?

**Comment by joshaber** [comment]
@willmorgan No worries, and thanks!

>Can you put that comment in issue-triage?

Yup, good shout 👍

**Comment by alison985** [comment]
@willmorgan Did you ever get anywhere with this. I am having the same problem and it's effecting my PRs getting approved.

**Comment by niik** [comment]
> Did you ever get anywhere with this. I am having the same problem and it's effecting my PRs getting approved.

@alison985 It's unlikely that we will go back and work on adding this feature to the old apps. If you open a PR using the new Desktop client we will push/publish automatically and then redirect you to the website to fill out your PR body and title and the PR template is automatically added to the body. If there's anything preventing you from using the new app please file an issue, we'd love to hear about it!

**Comment by willmorgan** [comment]
> Did you ever get anywhere with this. I am having the same problem and it's effecting my PRs getting approved.

@alison985 Nah, I've just been creating my PRs on the web interface which populates for me. Going to give the new apps a try too.
