### ISSUE TITLE
Get Linux test environment set up on Travis

### ISSUE THREAD

**Issue by cheshire137** [desktop/desktop#273]
It'd be cool if this app ran on Linux. Let's get Travis CI running our tests in Linux so we can at least know if some tests pass in other environments but fail specifically in Linux.

**Comment by picandocodigo** [comment]
I've done some work on getting it to run on Travis:
https://travis-ci.org/picandocodigo/desktop/
I can currently run the app in my Linux system with `npm start`. The unit tests pass, but the integration tests don't. Tests fail on Travis too (for different reasons though), but at least the build is there. You can check the code here: https://github.com/picandocodigo/desktop/tree/linux

I'll continue working on it, see if I can find the way to fix these issues.

**Comment by shiftkey** [comment]
Blocked on #2132

**Comment by shiftkey** [comment]
So CircleCI doesn't support [running builds for multiple platforms](https://discuss.circleci.com/t/how-to-use-circleci-for-linux-xcode-in-one-project/693/2) so we're going to have to keep Travis around for anything Linux-related.

**Comment by shiftkey** [comment]
We totally did this in #2808
