### ISSUE TITLE
Ask before installing git-lfs hooks 

### ISSUE THREAD

**Issue by BanzaiMan** [desktop/desktop#2732]
### Description

Adding a git repo which already exists on the file system to the GitHub Desktop results in new hooks `post-checkout` `post-commit` `post-merge` `pre-push`. These all call `git lfs`. This is fine, as long as the user interacts with the repository *exclusively* with GitHub Desktop, but they cause problem if git LFS is not installed on the computer otherwise and the user tries to interact with it with `git`.

### Version

**GitHub Desktop version:** 0.8.2

**OS version:**

    Darwin * 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

### Steps to Reproduce

1. Create a git repo
1. Add it to Desktop
1. Remove `git-lfs` from `$PATH`
1. Go to the git repo directory, and call `git commit` or `git push`

**Expected behavior:**

The command succeeds.

**Actual behavior:**

```sh-session
$ git push origin ha-script-assert

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.

error: failed to push some refs to 'https://github.com/travis-ci/travis-build.git'
```

**Reproduces how often:**

100%

#### Additional Information

This reinstates https://github.com/desktop/desktop/issues/2236.

**Comment by joshaber** [comment]
Could catch 👍 I'm not sure what's going on here but I'll dig into it.

**Comment by BanzaiMan** [comment]
Oh, I meant to really say: "Please ask before installing these hooks." However, it might become too cumbersome if we had to answer for every single one. Maybe offer to install it? Or a preference item? I am not sure what the best UX is.

**Comment by joshaber** [comment]
So when a user adds a new LFS repository, we prompt asking if we should install hooks:

<img width="448" alt="screen shot 2017-09-14 at 11 55 42 am" src="https://user-images.githubusercontent.com/13760/30443848-f77adb9a-994e-11e7-97db-ee2b7d038de2.png">

But it turns out the call we were using to check if a repository uses LFS also installs the hook 😆 The LFS team just added a way to disable that behavior: https://github.com/git-lfs/git-lfs/pull/2584.

**Comment by BanzaiMan** [comment]
Hmmm. I don't remember seeing that modal. Was I supposed to?

**Comment by joshaber** [comment]
You'd see that modal only if you added a repository that was already using LFS. But the way we checked if you were using LFS always added the hook :hurtrealbad:

**Comment by emaloney** [comment]
I just installed GitHub Desktop for Mac. Now all of a sudden I can no longer push from the command line. It is a bit obnoxious for the Desktop app to corrupt my environment to the point that command line git no longer works. I had high hopes for client, but will be deleting it from my Mac immediately before it messes up any other repos. Quite annoyed about this.

**Comment by j-f1** [comment]
@emaloney We’ve got a fix for this issue (see the PR above), and hopefully it’ll be released in the next update. In the meantime, [installing `git-lfs`](https://git-lfs.github.com) should fix the issue. I’m really sorry this is disrupting your work.

**Comment by krisgoku2** [comment]
is this only on mac?
