### ISSUE TITLE
Atom installation is not recognized

### ISSUE THREAD

**Issue by SebastianZimmer** [desktop/desktop#2735]
### Description

I have installed 0.8.2 today and was wondering why GitHub Desktop did not recognize my Atom installation. After a bit of research I found out that `getActiveCodePage()` ( https://github.com/desktop/desktop/blob/master/app/src/lib/shell.ts#L179 ) fails. I think it's because of this regex:

`const chcpOutputRegex = /^Active code page: (\d{1,}).*/`
https://github.com/desktop/desktop/blob/master/app/src/lib/shell.ts#L170

On my system, where the display language is "German", the `chcp` command does return `Aktive Codepage: 850`.

### Version

**GitHub Desktop version:** 0.8.2

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Install Atom and Github Desktop on Windows with German display language
2. Click in Desktop on "Open in external editor"

**Expected behavior:** Atom should open

**Actual behavior:** Atom ist not found by GitHub Desktop

**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
@SebastianZimmer thanks for the report, and the additional detective work!

> On my system, where the display language is "German", the chcp command does return `Aktive Codepage: 850`.

I think I might have to make this regex more relaxed and just scan for the number.

**Comment by j-f1** [comment]
`/\d+/$` should work for most<sup>[citation needed]</sup> cases.

**Comment by charles-passille-smartnets** [comment]
Same problem on Japanese Win10.

**Comment by charles-passille-smartnets** [comment]
@SebastianZimmer 
@shiftkey 

I have a hotfix if you just want to use it, it's not a real solution though.

On line 220, just change `resolve(null)` to `resolve(850)` (in your case for german)
It was 932 for me, etc. It will bypass the regex and just assign your system's language path.

Enjoy :)
