### ISSUE TITLE
The repository has been updated since you last pulled. Try pulling before pushing.

### ISSUE THREAD

**Issue by adamreisnz** [desktop/desktop#2738]
If this error shows up, would it be possible to change the button "Push origin" to "Pull origin"?

![image](https://user-images.githubusercontent.com/490562/30468154-b4aff238-9a3d-11e7-8593-1218cfd2e3d2.png)

Now I'm left with only the push option, which doesn't work, so I have to hunt in the menu to find a pull command or use command line.

Actually, now after about 40 seconds, it changed to "Pull origin" by itself. Guess there might be something wrong with the update of it.

**Comment by shiftkey** [comment]
> Actually, now after about 40 seconds, it changed to "Pull origin" by itself. Guess there might be something wrong with the update of it.

Sounds like we were waiting on a fetch to happen to update the button state.

![](https://media.giphy.com/media/5G98t8QjqBLK8/giphy.gif)

**Comment by shiftkey** [comment]
@adamreisnz looking into the work we did around this in #2445 - we should be doing a fetch behind the scenes as per 7ab75c9982d05f0253e73dd77f5aa043290832d9. So a couple of questions from your logs:

 - do you see the `fetch` happen in the log after the push error?
 - how long does a typical fetch take with this repository?

Normally the fetch would update this button, but maybe we've missed something with this workflow that's different to our background fetch?

**Comment by adamreisnz** [comment]
@shiftkey I don't recall what machine I did it on anymore so not sure if I can dig up the logs, but a fetch usually doesn't take more than 1-2 seconds for that repo.

**Comment by shiftkey** [comment]
@adamreisnz no problem - it should be easy to reproduce, just a bit time-consuming...

**Comment by CruiseMan** [comment]
@joshaber Do you know ETA for this one ?

**Comment by copycatx5** [comment]
It happens again, is there a solution?
<img width="695" alt="2018-08-27 14 38 15" src="https://user-images.githubusercontent.com/5077487/44644499-e434ee80-aa06-11e8-9234-3604ca74d40c.png">

**Comment by newdawnguitar** [comment]
@copycatx5 I clicked 'undo' underneath the commit button. Then the push button changed to fetched. So i fetched. Commited again. Then pushed.

**Comment by MaximePie** [comment]
Clicking 'Undo', fetching, pulling, and commit again worked for me, thanks @newdawnguitar  !

**Comment by acerock6** [comment]
You can go to Repository ->  Pull and then click on Push Origin.

**Comment by indysigner** [comment]
On year in, this problem still hasn't been fixed 🙄

**Comment by tierninho** [comment]
Dropping in to add some clarity to the reproduction steps and paste my logs.

- Commit some stuff to a repo on Desktop
- go to the same repo on Github.com and add a new file
- click `Push origin` on Desktop

Logs:

```
install.ts:23 git -c credential.helper= push origin master:master --progress exited with an unexpected code: 1.
To https://github.com/tierninho/AAAAAAAA.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/tierninho/AAAAAAAA.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

(The error was parsed as 10: The repository has been updated since you last pulled. Try pulling before pushing.)
```

Ideally, the button should look like this if a fetch was performed in the background:
<img width="229" alt="screen shot 2018-10-23 at 9 52 46 am" src="https://user-images.githubusercontent.com/14828183/47377218-8260d000-d6a9-11e8-89de-ce5ee51566e0.png">

For now, the workaround is still: https://github.com/desktop/desktop/issues/2738#issuecomment-416755732

**Comment by yalnjooj** [comment]
create new branch... it well work.

**Comment by shguocc** [comment]
because a team member not push the update project the moment

**Comment by shiftkey** [comment]
Bumping this issue to indicate I think I've got the root cause of this flow:

> Now I'm left with only the push option, which doesn't work, so I have to hunt in the menu to find a pull command or use command line.
> 
> Actually, now after about 40 seconds, it changed to "Pull origin" by itself. Guess there might be something wrong with the update of it.

This feels a lot like something that #6610 will address, and the changes over there should address this so you get immediate feedback after the fetch (and we can change the button label to be `Fetch` rather than `Close`).

**Comment by CQHofsns** [comment]
> @copycatx5 I clicked 'undo' underneath the commit button. Then the push button changed to fetched. So i fetched. Commited again. Then pushed.

You save my time

**Comment by MappingSteve** [comment]
Because this just happened to me, repeating here the work-around for anyone who gets here before the fix rolls out: 

In menu, "Repository > Pull" gets you unstuck.

**Comment by nguyendptse62666** [comment]
1. Click undo dow button Commit to master.
2. Fetch origin.
3. Pull new code.
4. Push your new code.
