### ISSUE TITLE
I cant open GitShell

### ISSUE THREAD

**Issue by KGosebo** [desktop/desktop#2740]
### Description

I've recently installed github for desktop but cant find git shell
### Version

**GitHub Desktop version:** 0.8.2

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by j-f1** [comment]
Thank you for contributing!

We’ve decided not to include a `git` shell in GitHub Desktop. The new version of Desktop bundles its own copy of `git` that’s designed to include only the features needed.

If you’d like to use `git` in a shell, I’d recommend [`git` for Windows](https://git-for-windows.github.io).
