### ISSUE TITLE
connection refused while cloning the repository

### ISSUE THREAD

**Issue by masonreznov** [desktop/desktop#2746]
### Description

[fatal: unable to access 'https://github.com/masonreznov/Hackerearth.git/': Failed to connect to github.com port 443: Connection refused

Error(s) during clone:
git clone failed: exit status 128]

### Version

**GitHub Desktop version:** [0.9.1]

**OS version:** [Windows 8]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by joshaber** [comment]
That sort of error _usually_ means you need to configure git with your proxy. See https://forum.freecodecamp.org/t/git-behind-a-proxy-server/13187 for more information.

**Comment by shiftkey** [comment]
Closing this out as inactive. @masonreznov feel free to reply if you have any further information or questions.
