### ISSUE TITLE
Intellij Idea can't find git.exe!

### ISSUE THREAD

**Issue by johnraychina** [desktop/desktop#2753]
### Description
Cannot run program 'git.exe' : create Process error=2, can not find file.

### Version
**GitHub Desktop version:0.9.1
**OS version:
Windows 10 home
version 1073

### Steps to Reproduce

1.  install github desktop on windows 10 platform
2.  open intellij idea and check out frome github

**Comment by shiftkey** [comment]
The version of Git that comes with GitHub Desktop is not added to your `PATH`. You'll need to install [Git for Windows](https://git-for-windows.github.io/) if IntelliJ requires an existing Git installation to use.

**Comment by KomsunYamwong** [comment]
Hello I found Cannot Run Git   ,File not found: git.exe  
How to fixed this problem..
