### ISSUE TITLE
tooltip gets stuck

### ISSUE THREAD

**Issue by SnaiCrys** [desktop/desktop#2754]
### Description

[Description of the issue]
A pop-up message about minimizing window does not disappear.

### Version

**GitHub Desktop version:** [0.9.1]

**OS version:** [Windows 10 v1703]

### Steps to Reproduce

1. Click on "minimize" before the pop-up message appears.
2. After minimizing, a pop-up message appears at the place where the window is closed.

**Reproduces how often:** [100%]
![clip2net_170917092645](https://user-images.githubusercontent.com/4284827/30518568-607a7b68-9b8a-11e7-8ca0-148c48560b13.png)

**Comment by shiftkey** [comment]
@SnaiCrys thanks for the report. As discussed in #2683, this is a problem with Electron which is being tracked in https://github.com/electron/electron/issues/9943.
