### ISSUE TITLE
Feature Request: Display in header the total of files selected for commit

### ISSUE THREAD

**Issue by abenhamdine** [desktop/desktop#2756]
### Description

Currently, the user could commit some unwanted files, because some files are selected but are not visible in the list (they are in the part of the grid which is not shown when there's a scrollbar).

### Version

**OS version:** Microsoft Windows [version 10.0.15063]

### Steps to Reproduce

1. Make changes in many files
2. Select some files at the end of the list
3. Later, scroll to the bottom of the list
4. Select another file
5. You think you have 1 file to commit, but others files are also selected but no way to be aware of before committing.

**Expected behavior:** Close to 'x files changed', display 'x files selected'

**Actual behavior:** This information isn't displayed

**Comment by shiftkey** [comment]
@abenhamdine thanks for the feedback. We're currently tracking this over in #2389 - please follow along with that issue!
