### ISSUE TITLE
Undoing a reverted commit removes files on an unborn branch

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2764]
The following seems like a potential bug when you revert the initial commit then undo all the changed files. The applies to an unborn branch.

Reproduce:
- create new repo with some files (but do not publish)
- revert the initial commit
- click `undo` for the reverted commit
- click `undo` again

Actual result: all changed files are removed and initial commit removed

Expected result: not 100% sure, but it seems like files should hang around

tested on 1.0.0-beta1, mac

**Comment by sdwebguy** [comment]
Same as https://github.com/desktop/desktop/issues/2721?

**Comment by joshaber** [comment]
@sdwebguy Interesting, maybe! We'll dig into it.

**Comment by shiftkey** [comment]
This is the CLI version of the repro. I'll walk through and explain how this happens, and what we could do about it:

```sh
git add .
git commit -m "first commit"
git revert {first-commit}
# at this point no files exist in the working directory due to the revert
git reset --mixed {first-commit}
# now the deletes are still applied to the working directory, but not staged
# that's the undo step and where the problem lurks
git update-ref -m Reverting first commit -d HEAD
# this only removes the ref
# the files are still deleted from the working directory
git rm --cached -r -f .
# this just cleans up any entries in the index
# the files are already long gone by now
```

We want to preserve as much as possible in this "Undo First Commit" scenario, so maybe a `git checkout -- ` for all removed files before undoing this first commit is the way to fix this.
