### ISSUE TITLE
Include app version in log messages

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#2765]
It'd be nice if our log messages included the app version so that we didn't have to ask users.

**Comment by 525809845102** [comment]
GaiZhan

**Comment by shiftkey** [comment]
@joshaber like, adding an entry with the version and OS details to the log file on launch?

**Comment by joshaber** [comment]
@shiftkey That's an even better idea than I had in mind, so yes, let's pretend that's what I meant 🍻
