### ISSUE TITLE
can not push updates using Github Desktop

### ISSUE THREAD

**Issue by berry33** [desktop/desktop#2766]
### Description

Hello,
I can not push any updates to my github repository from the GitHub Desktop app. when I do I git this error. Git credentials for https://github.com/berry33/repository.berrysrepo.git not found:
exit status 1
error: failed to push some refs to 'https://github.com/berry33/repository.berrysrepo.git'

I have even tried deleting and creating a new account and have also used bash to set my user name and email to the same cardinals that are in the app.  

### Version

**GitHub Desktop version:** [0.9.1]

**OS version:** Microsoft Windows [Version 10.0.15063]
### Steps to Reproduce

1. Log in to GitHub Desktop
2 Commit changes to master 
3 Click the Push Origin button and the top of the GitHub Desktop window

**Expected behavior:** when the push origin button is pressed after a commit is made the apropriate changes will be uploaded to my repository and github.com

**Actual behavior:** When a commit is made and the push to origin button is pressed this error is given: Git credentials for https://github.com/berry33/repository.berrysrepo.git not found:
exit status 1
error: failed to push some refs to 'https://github.com/berry33/repository.berrysrepo.git'

**Reproduces how often:** every time the program is used.

**Comment by joshaber** [comment]
This looks like #2747 so I'm gonna roll it into that. I _think_ the same steps to fix it should work for you too:

It sounds like you were effect by a bug from a release or two back.

First, make sure you're running version 0.9.1 and update if you're not.

Then run `rm .git/hooks/pre-push` from the repository.

You should be good to go after that.
