### ISSUE TITLE
publish issue

### ISSUE THREAD

**Issue by bhartishubham** [desktop/desktop#2771]
### Description

Problem with push request

### Version

**GitHub Desktop version:** 0.9.1

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** Publish the repository

**Actual behavior:**Does not publish everytime

**Reproduces how often:** 100%

### Logs
2017-09-19T05:35:15.564Z - error: [ui] `git -c credential.helper= push origin master:master --progress` exited with an unexpected code: 1.
Remote "origin" does not support the LFS locking API. Consider disabling it with:
  $ git config lfs.https://github.com/bhartishubham/Github-Shubham.git/info/lfs.locksverify false

Git credentials for https://github.com/bhartishubham/Github-Shubham.git not found:
exit status 1
error: failed to push some refs to 'https://github.com/bhartishubham/Github-Shubham.git'

**Comment by shiftkey** [comment]
As mentioned in https://github.com/desktop/desktop/issues/2747#issuecomment-330241490, a bug was introduced where we incorrectly initialized some repositories as Git LFS. The workaround for Windows users:

> Go up to the `Repository` menu and select `Open in Command Prompt`. It'll launch Command Prompt in the repository. Then run copy and paste `del /f .git\hooks\pre-push` into Command Prompt and hit <kbd>Return</kbd>.

Let me know if that gets you back to a happy place!

**Comment by bhartishubham** [comment]
Thx for the Help
