### ISSUE TITLE
Clicking a line in the diff toggles the file in the Changes section

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2772]
Clicking a line item in the diff toggles the checkboxes in the Changes section. Seems like a bug...

<img width="617" alt="screen shot 2017-09-19 at 11 08 59" src="https://user-images.githubusercontent.com/14828183/30589789-621487d2-9d2b-11e7-9daf-543b07ae578f.png">

@desktop/design for feels

tested in 1.0.0-beta3, mac

**Comment by joshaber** [comment]
Yup, that's a feature 😄 If you're toggling lines, we assume you'll want to commit that file.
