### ISSUE TITLE
publishing an unborn repository disabled for no apparent reason

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2773]
If I create a new repo with an unborn branch, and with no commits, then the `Publish` button is not clickable as intended. 

However, the user can go to Repository settings and click the `Publish` button, resulting in a `Not a valid object name: 'master'` error and the nav `Publish` button still greyed out.

Reproduce:
- create new repo with no commits
- go to Repo settings, click publish
- error surfaces, but repo still published
- Publish button in nav area still unclickable

<img width="871" alt="screen shot 2017-09-19 at 12 14 17" src="https://user-images.githubusercontent.com/14828183/30592085-f789aac8-9d34-11e7-9bc3-fa0500cdc5eb.png">

<img width="340" alt="screen shot 2017-09-19 at 12 22 12" src="https://user-images.githubusercontent.com/14828183/30592139-31e4afa6-9d35-11e7-9616-a1a3aa977450.png">

related to #2086 

tested in 1.0.0-beta3, mac

**Comment by shiftkey** [comment]
The `CallToAction` UI component we have here doesn't support disabling the button, but I think we can show a better message here and hide the button:

<img width="465" src="https://user-images.githubusercontent.com/359239/30620835-118a5506-9deb-11e7-8950-821f29bfe63b.png">

Something like:

> The repository contains no commits and cannot be published. Need help? `Learn more` about remote repositories.

Thoughts @desktop/core?

**Comment by niik** [comment]
> The repository contains no commits and cannot be published. Need help? Learn more about remote repositories.

Couldn't we still create the repository via the API and omit the push in this scenario?

**Comment by tierninho** [comment]
Just to clarify, the `CallToAction` button was present, and it did allow me to click it.

**Comment by shiftkey** [comment]
> Couldn't we still create the repository via the API and omit the push in this scenario?

Excellent point - I'll go and check the post-publish code and see if we can relax that to _not_ push for unborn branches. That seems simpler than complicating these dialogs...

**Comment by shiftkey** [comment]
@tierninho actually, i'm not sure those errors are related to `push`:

 - we already wrap the post-publish push in a check to ensure it's not unborn or detached HEAD

https://github.com/desktop/desktop/blob/212ecb783a779d653da8cba4cf5a36796ba0c8e9/app/src/lib/dispatcher/app-store.ts#L1976-L1980

 - the first two `git branch xyz` errors are related to creating a branch, which doesn't seem to be part of this workflow

https://github.com/desktop/desktop/blob/212ecb783a779d653da8cba4cf5a36796ba0c8e9/app/src/lib/git/branch.ts#L15-L24

The third error `422 Unprocessable Entity` is probably the actual publish error, but without the log maybe it's going to be tough to reproduce.

**Comment by tierninho** [comment]
Found the logs, not sure they are going to be very helpful though:

```2017-09-19T10:59:16.624Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.401s)
2017-09-19T11:00:59.173Z - error: [ui] `git merge master` exited with an unexpected code: 1.
CONFLICT (modify/delete): .gitignore deleted in HEAD and modified in master. Version master of .gitignore left in tree.
Automatic merge failed; fix conflicts and then commit the result.

(The error was parsed as 7: We found some conflicts while trying to merge. Please resolve the conflicts and commit the changes.)
2017-09-19T11:01:01.126Z - info: [ui] Executing push: git -c credential.helper= push origin sdfsdfsdfsdfsd:sdfsdfsdfsdfsd --progress (took 11.265s)
2017-09-19T11:01:07.943Z - error: [ui] `git checkout --progress master --` exited with an unexpected code: 1.
.gitignore: needs merge

error: you need to resolve your current index first

2017-09-19T11:04:30.823Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.064s)
2017-09-19T11:42:45.722Z - info: [ui] Executing push: git -c credential.helper= push origin master --set-upstream --progress (took 7.814s)
2017-09-19T11:42:47.576Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.853s)
2017-09-19T12:11:23.885Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 4.118s)
2017-09-19T12:12:28.247Z - error: [ui] `git branch dfsdfsdf` exited with an unexpected code: 128.
fatal: Not a valid object name: 'master'.

2017-09-19T12:12:50.367Z - error: [ui] `git branch dfsdf` exited with an unexpected code: 128.
fatal: Not a valid object name: 'master'.

2017-09-19T12:13:35.965Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.808s)
2017-09-19T12:18:50.849Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.066s)
```

Tried to reproduce this error from the beginning, but no luck. I guess the question is, should clicking `Publish` from the Repo Settings modal be allowed if the main `Publish` button remains greyed out?

I also noticed while retesting that if you create a new branch before undoing the initial commit, and publishing via Repo Settings, that `master` is not accessible via the branch list until you `Update from Default Branch`. 

Repro:
- create new repo, don't publish
- create new branch
- undo all commits

Can't reselect Master branch.

**Comment by shiftkey** [comment]
>  I guess the question is, should clicking `Publish` from the Repo Settings modal be allowed if the main `Publish` button remains greyed out?

I think we should enable the main `Publish` as we seem to be able to handle publishing an unborn repository. I'll leave this open and update the issue to reflect this.

**Comment by tierninho** [comment]
Something seems off. Should  we disable the publish button in this instance?

tested in 1.0.4-beta0, mac

Reproduce:
- make a new repo, undo and delete all commits
- click the `publish repo` button

<img width="360" alt="screen_shot_2017-10-04_at_13 58 32_720" src="https://user-images.githubusercontent.com/14828183/31179053-c0883c08-a912-11e7-94b1-fcdc4045ea64.png">

**Comment by shiftkey** [comment]
@tierninho nice spot - yeah, I think we need this sort of granularity for this button state:

 - unpublished repository, unborn `HEAD` - enabled (can publish repository)
 - unpublished repository, valid branch - enabled (can publish repository and branch)
 - published repository, unborn `HEAD` - disabled (no branch to push)
 - published repository, branch without tracking - enabled (can publish branch)
 - published repository, network action - disabled (don't interfere with existing action)
