### ISSUE TITLE
In-app release notes

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#2774]
We talked about this a little at our mini summit but I forgot to record it.

We'd like to do a better job of telling users about what changes between updates. One part of that would be displaying the release notes in app.

**Comment by joshaber** [comment]
VS Code does this pretty well, I think, in that they automatically show you the changelog when you launch the new version.

That _might_ be too in-your-face? I dunno. I like it. Maybe only for big releases like 1.0 -> 1.1, not for patch updates?

**Comment by j-f1** [comment]
Design idea: add had a ⬇️ arrow on banner telling you that an update is available that toggles the changelog between the app’s current version and the latest version when clicked. Additionally, the banner could be shown after updating, saying “GitHub Desktop has been updated from `0.8.2` to `1.0.0`. [View Changelog](https://google.com/generate_204)”

**Comment by niik** [comment]
> That might be too in-your-face? I dunno. I like it. Maybe only for big releases like 1.0 -> 1.1, not for patch updates?

I concur, I think we should reserve this for bigger features and separate this out from the displaying of release notes completely. I imagine we'll have custom UI for this where we can display images (GIFS!!!) and perhaps even have a multi-step process to introduce a big new feature to users.

---

Here's what we're thinking for displaying release notes in-app. For these mocks I've used actual data from previous releases to illustrate how it will actually look in the app.

<img width="598" alt="screen shot 2017-09-27 at 15 59 32" src="https://user-images.githubusercontent.com/634063/30917702-e81e69ac-a39c-11e7-9506-d3aed42c18bd.png">

Some high-level specs

- You get to this by clicking on the `what's new` link in the update banner just like you do today
- We'll only show the release notes for the version you're upgrading to, not any potential intermediate releases.
- We'll do a custom dialog header to spruce things up a little.
- We'll group individual release note items into three categories (more on this later) which are positioned in one or two columns.

### Categorization

Right now our parsing code on `desktop.github.com` supports these categories `new`, `fixed`, `improved`, `removed`, and `added`. With this we'll group `new`, `added`, and `improved` under Enhancements, `fixed` under Bug Fixes and `removed` plus any items we're unable to parse or which lacks a category under Other.

If, after grouping, we only end up with a single group we'll render that group full width while decreasing the max width of the update dialog by 50px.

<img width="535" alt="screen shot 2017-09-27 at 16 07 44" src="https://user-images.githubusercontent.com/634063/30918158-0677ed64-a39e-11e7-8fb1-79662de7ed52.png">

If there's more than one group the Enhancements group will always be positioned first, in the first column, followed by Bug fixes in the second column. If there's three groups the third, Other, will be positioned in the first column underneath Enhancements.

Illustrated here by a non-balanced version

<img width="579" alt="screen shot 2017-09-27 at 16 10 11" src="https://user-images.githubusercontent.com/634063/30918268-5adfd646-a39e-11e7-9edd-19983736912f.png">

If there'd been any 'Other' items here they'd appear 10px below the last item in the `Enhancements` category.

### Pretext

For some versions it'd be really nice if we could add some text (and possibly graphics but let's not get ahead of ourselves) before the items themselves. Illustrated here by how I think our 1.0 dialog should have looked.

<img width="526" alt="screen shot 2017-09-27 at 16 12 00" src="https://user-images.githubusercontent.com/634063/30918386-b01bc34a-a39e-11e7-86d5-2281af62076b.png">

My thinking here is that if we don't want to change the changelog json format we could add a special tag in our changelog so it'd be something like `"[pretext] Collaborating on..."`. Ideally we'll support markdown here and we'll make sure desktop.github.com doesn't render these special items until we get to designing that view again.

### Specs

- Dialog max height 450px
- Custom dialog header height 100px
- Column width 250px with a one spacer (10px) gutter
- Dialog header, version text, 14px semibold
- Dialog header, date, 11px regular, secondary text color
- Standard margins in dialog content (20px)
- Category headers, 12px semibold
- Release note item text 11px
- One spacer margin between category headers and items
- One spacer margin between items

<img width="576" alt="screen shot 2017-09-27 at 16 24 12" src="https://user-images.githubusercontent.com/634063/30918954-56167e10-a3a0-11e7-8978-73e76bba94ba.png">

**Comment by j-f1** [comment]
That looks awesome @niik! 🎉

:two: ideas:

1. Display the avatar of the person who opened the PR to the left of each item, linked to their GitHub profile.
2. Move the PR link to a PR icon (linked to the PR) with a tooltip containing the PR name and number.

**Comment by joshaber** [comment]
We might wanna give some thought to how this is implemented.

Auto-linking issues is currently done client-side on desktop.github.com, but I've also been planning to add auto-linking user mentions. The code duplication might be acceptable, but we should also at least think through making Central do more of the heavy lifting.

**Comment by joshaber** [comment]
I'm gonna leave this as a stretch goal for 1.1. Feel free to speak up if you don't agree!

**Comment by shiftkey** [comment]
The 1.1 task list seems to be mostly assigned, so I'm going to start hacking on this a bit until something higher-priority appears.

**Comment by shiftkey** [comment]
Moving this to `1.1.x` to focus on QA and helping get the PR integration out sooner.

**Comment by tierninho** [comment]
I have my dev env up and running now, so can help test feature, too.
