### ISSUE TITLE
Launch via command line for current working directory

### ISSUE THREAD

**Issue by jpoehls** [desktop/desktop#2775]
### Command line integration

I'd like to be able to launch the commit/changes UI for my current working directory from the command line.

E.g.,

```
C:\repos\my project> GitHubDesktop
# Launches GitHub Desktop to the Changes UI for me to commit my changes
```

My typical workflow is to do most git operations from the command line but launch a GUI for commits since GUIs are quicker for selecting specific files and lines for the commit.

I use GitExtensions right now which lets me launch `gitex commit` to quickly commit files in my working directory. I'd like to replace GitExtensions with GitHub Desktop in this same workflow.

**Comment by j-f1** [comment]
Try `github .` 😃

**Comment by jpoehls** [comment]
Thanks! That's mostly what I want. I do have a couple nitpicks based on a few minutes of testing that though:

1. `github .` from a sub-directory in my git clone opens a prompt to add a new local repository instead of detecting the local repository I've already added.
2. `github` (without the dot) should have the same behavior as `github .` IMO

**Comment by j-f1** [comment]
I’m working on a better CLI in #2372. I’ll put your ideas over there!

**Comment by jpoehls** [comment]
Thanks! I'll go ahead and close this issue out then.

For anyone finding this in the near future, I've added this PowerShell function and alias in my profile to get the behavior I wanted.

```
function Invoke-GitHub {
    $gitRoot = & git rev-parse --show-toplevel
    if ($LASTEXITCODE -eq 0) {
        & (Join-Path $env:LOCALAPPDATA "GitHubDesktop\bin\github.bat") $gitRoot
    }
}
Set-Alias github Invoke-GitHub -Force
```

**Comment by shiftkey** [comment]
@jpoehls yeah, that first issue sounds like a bug. I've opened #2832 to track it, so you don't need this workaround...
