### ISSUE TITLE
Feature:  Add Git Shell to list of shell's

### ISSUE THREAD

**Issue by MrFlof** [desktop/desktop#2776]
### Description

It would just be a bit more convenient to be able to open the git shell directly from the desktop version, this is a really cool feature that I've been using and it's been fine opening in the command prompt or powershell, but I definitely love the git shell you guys have made as well.

### Version

**GitHub Desktop version:** 1.0

### OS Version

**OS version:** Windows

**Comment by iAmWillShepherd** [comment]
Can you verify that you have GitB Bash installed?

**Comment by iAmWillShepherd** [comment]
This is already possible. Just go to File -> Options -> Advanced -> Shell and select Git Bash.

**Comment by mlafleur** [comment]
I don't believe this user was talking about "Git Bash" but rather the "Git Shell" functionality from the GitHub for Windows client. If they were looking for the same thing I was, it was actually preserving the prompt settings from GitHub for Windows. 

In my case I use PowerShell and prefer the older prompt that included current branch and status information for the repo you're currently in (i.e. `[master ≡]>`).

**Comment by shiftkey** [comment]
@mlafleur "Git Shell" was our name for whatever shell you had configured in GitHub for Windows. We had a long discussion about this in #340 and decided Git Shell was too tied into GitHub for Windows that it wasn't worth porting.

If you're in PowerShell and want that experience back, you can install [posh-git](https://github.com/dahlbyk/posh-git#installation) and choose PowerShell in GitHub Desktop.

**Comment by MrFlof** [comment]
Awesome thanks a ton shiftkey I had no idea this was an option!  Also I am definitely loving the new desktop program!
