### ISSUE TITLE
cannot clone a github repository to the selected local path

### ISSUE THREAD

**Issue by lyrachord** [desktop/desktop#2777]
Just want to clone a github repository,
input a https://github.com/xxx/xxx
select a local path, 
Hint error: local path exists.
even the default path my documents, 
the clone button don't answer me.

let user do feedback from desktop version itself,  avoid providing content information.

Cheers,

**Comment by iAmWillShepherd** [comment]
Can you verify that you do not have a folder in that directory with the same name as your repo?

**Comment by shiftkey** [comment]
This is the same bug as #2830 - putting together a fix for both now.
