### ISSUE TITLE
Pull Request Persistance

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#2779]
We need some way to persist or cache PR API responses. I'm leaning towards using the database, but I'm not married to the idea.

See issue #2642 for more context

**Comment by iAmWillShepherd** [comment]
I'm thinking we can create the PR store as a part of this issue.

**Comment by joshaber** [comment]
Would it also store the CI status info?

**Comment by iAmWillShepherd** [comment]
No, I think the status info is too short-lived.

**Comment by joshaber** [comment]
So that'd just be cached in memory?

**Comment by iAmWillShepherd** [comment]
Yep, but that will be what the next issue is for. 😄

**Comment by shiftkey** [comment]
> Would it also store the CI status info?

From an API perspective [Commit Statuses](https://developer.github.com/v3/repos/statuses/) aren't associated with [Pull Requests](https://developer.github.com/v3/pulls/), so I'd recommend caching those separately with a simple repository+SHA cache instead.

**Comment by joshaber** [comment]
_assigning @iAmWillShepherd as I'm pretty sure he's already working this_
