### ISSUE TITLE
Running GitHubDesktopSetup.exe fails

### ISSUE THREAD

**Issue by PedroLamas** [desktop/desktop#2785]
### Description

Running GitHubDesktopSetup.exe fails!

### Version

**GitHub Desktop version:** 1.0

**OS version:** 1709 (OS Build 16288.1)

### Steps to Reproduce

1. Run GitHubDesktopSetup.exe

**Expected behavior:** To open the setup screen

**Actual behavior:** Shows an error message

**Reproduces how often:** 100% repro

### Logs

[SquirrelSetup.zip](https://github.com/desktop/desktop/files/1316151/SquirrelSetup.zip)

**Comment by shiftkey** [comment]
This is an interesting one:

```
2017-09-20 00:27:32> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.IO.IOException: The process cannot access the file 'C:\Users\pedro\AppData\Local\GitHubDesktop\app-0.5.9\GitHub Desktop.exe' because it is being used by another process.
```

Are you able to nuke whatever is under `%LOCALAPPDATA%\GitHubDesktop` and try that again?

**Comment by PedroLamas** [comment]
A quick reboot seems to have fixed the issue!

I had a previous beta version installed and did try to open it before installing the new one (I wanted to check which GiHub Desktop that shortcut was for), so something might have been locked after I closed it!

**Comment by shiftkey** [comment]
@PedroLamas I'm glad you're back to a happy place! :tada:
