### ISSUE TITLE
Git credentials not found

### ISSUE THREAD

**Issue by kimberly-clark** [desktop/desktop#2786]
### Description

I am trying to push my website origin but an error keeps appearing. The website will not refresh and be pushed to the cloud.

### Version

**GitHub Desktop version:** Version 1.0.0

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Commit repository to master
1. Attempt to push to origin
1. Error message appears

![capture](https://user-images.githubusercontent.com/31423323/30622771-614434f8-9d79-11e7-8527-035b3f9474cf.jpg)

**Expected behavior:** Repository would be pushed to origin and be accessible on the Github website so that it could be published.

**Actual behavior:** The following error message appeared when I tried to push it to the origin: 
Git credentials for https://github.com/wustlcse104/03-review-form-kimberly-clark.git not found:
exit status 1
error: failed to push some refs to 'https://github.com/wustlcse104/03-review-form-kimberly-clark.git'

**Reproduces how often:** Every time I try to push this repository

**Comment by shiftkey** [comment]
@kimberly-clark could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by joshaber** [comment]
This sounds like https://github.com/desktop/desktop/issues/2747.

Try following the instructions in https://github.com/desktop/desktop/issues/2747#issuecomment-330322002 and let us know if it doesn't work!
