### ISSUE TITLE
surface network error when fetching repositories in clone dialog

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2796]
We should surface errors in the clone repo modal if there is no internet connection. The loading icon attempts to load repos and then eventually stops when it realizes there is no connection, however the user is not notified.

<img width="855" alt="screen shot 2017-09-20 at 13 37 10" src="https://user-images.githubusercontent.com/14828183/30646771-9e43d63e-9e09-11e7-8362-8fce43daaff1.png">

This applies to the Github and Enterprise tabs, as the URL shows the following error, which isn't too user-friendly either:

<img width="1026" alt="screen shot 2017-09-20 at 13 37 46" src="https://user-images.githubusercontent.com/14828183/30646770-9de26372-9e09-11e7-9fe8-b4aec7025292.png">

tested v1.0.0, mac

**Comment by shiftkey** [comment]
Tweaked the title to indicate it's related to listing repositories, not the actual clone step

**Comment by shiftkey** [comment]
@tierninho could you open a separate issue for the clone failing due to a network issue? That's going to require some work with our error handlers to surface a better message, which is different to a network issue when looking up repositories for the user.

**Comment by shiftkey** [comment]
Hey @github/design, want to give some input on what a friendly network error might look like here in the list/dialog? Or should we just salmon-pink brutalism up the place for now?

**Comment by ampinsk** [comment]
<img width="426" alt="screen shot 2018-11-21 at 12 43 13 pm" src="https://user-images.githubusercontent.com/10404068/48867455-0f6f7580-ed8b-11e8-98d5-e0c1ed29b409.png">

How's something like this?

cc @billygriffin @donokuda

**Comment by donokuda** [comment]
@ampinsk Looks good to me!

**Comment by ampinsk** [comment]
I was thinking it would try reloading the list. Not totally necessary functionality, so that link could be removed.

**Comment by billygriffin** [comment]
Sounds great @ampinsk, thanks. For whomever picks this up, if there's a nice and fairly simple way to implement the "Try again?" piece of this to attempt to reload the list, that's a nice to have. But implementing it without that would still be a nice step in the right direction.

**Comment by Daniel-McCarthy** [comment]
I would love to give this a try. I took a swing at it and have the functionality working and am now starting to style it to be like the proposed design, and then I can clean up the implementation a bit.

I believe the `Try Again?` should not be a problem. I seem to have that working as expected.

**Comment by billygriffin** [comment]
Awesome, thanks @Daniel-McCarthy! ❤️

**Comment by billygriffin** [comment]
Closing this issue along with the associated PR because we haven't seen evidence from users that this is a very common problem, and the current remedy for it isn't bad. https://github.com/desktop/desktop/pull/6297#issuecomment-472078626
