### ISSUE TITLE
Github Desktop hangs on push to local Gitlab

### ISSUE THREAD

**Issue by wmevius** [desktop/desktop#2797]
### Description

We have a local Gitlab installation which we're happily using with other clients, such as Visual Studio, or git from the command line.

However, Github Desktop always hangs on push (fetching and cloning works fine). We're using HTTP with credentials to connect to Gitlab.

### Version

**GitHub Desktop version:** 1.0.0

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Launch Github Desktop
2. Clone Gitlab repo by using HTTP to connect
3. Make some changes, commit and push

Result: 'Hang on' message and spinning gif forever

**Expected behavior:** Github desktop to push changes

**Actual behavior:** Nothing

**Reproduces how often:** [100%

**Comment by iAmWillShepherd** [comment]
Can you attach your log files please?

**Comment by wmevius** [comment]
It says: we don't support that type :) 

but here it is - after changing the extension (anonymised slightly):
[2017-09-20.desktop.production.log.txt](https://github.com/desktop/desktop/files/1318220/2017-09-20.desktop.production.log.txt)

**Comment by hansenman61** [comment]
Why didn't u just say so please explain how to do that?

**Comment by shiftkey** [comment]
@wmevius thanks for the log! The only thing that's interesting from the log file is the remote repository is `http://` rather than `https://`, but I don't think that's the problem.

In theory, any authentication error should be captured by our [error handler](https://github.com/desktop/desktop/blob/a6594353190ac33c0bc32f898a29328e0b61ddee/app/src/lib/dispatcher/error-handlers.ts#L124-L168) but if you're not getting the prompt then maybe it's a slightly different error message that's slipping through our checks.

I also can't spot the corresponding `git push` operation in the log - are there any errors in the dev tools (press <kbd>Ctrl + Shift + I</kbd> that might not have been flushed to the log?

**Comment by wmevius** [comment]
Hmm interesting – didn’t realize it was an HTML application ☺

Anyway, there’s no errors when I check with the dev tools.

Below is a verbose list of everything that happens when I open the application and click on ‘Push’. As you can see the push is there.

Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z
renderer.js:12 Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes
renderer.js:12 Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 --
renderer.js:12 Executing getCommits: git log origin/master..master --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color
renderer.js:12 Executing getRemotes: git remote -v
renderer.js:12 Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT
renderer.js:12 Executing getRemotes: git remote -v
renderer.js:5 App ready time: 17.221598997712135ms
renderer.js:5 Load time: 519.9134159982204ms
renderer.js:5 Renderer ready time: 313.39500000000004ms
renderer.js:12 Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z
renderer.js:12 Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes
renderer.js:12 Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 --
renderer.js:12 Executing installGlobalLFSFilter: git lfs install --skip-repo
renderer.js:12 Executing getCommits: git log origin/master..master --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color
renderer.js:12 Executing getRemotes: git remote -v
renderer.js:12 Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT
install.ts:35 Executing getRemotes: git remote -v
install.ts:35 Executing push: git -c credential.helper= push origin master:master –progress

It’s a shame that it doesn’t work, as I think Github Desktop is by far the best client out there, especially for people with not so much Git experience.

**Comment by wmevius** [comment]
It's authentication related. When I do a 'git fetch' for that clone from the command prompt I get prompted for my credentials and it works. When I do a 'git push' the credential window keeps popping up and never accepts my credentials.

**Comment by wmevius** [comment]
When I do a 'git push' and just cancel the credential window 4 times it actually pushes....

**Comment by wmevius** [comment]
Is it something to do with lfs? I see this in the config:

[lfs "http://git.internal.esptl.com/LGMA/MRL.git/info/lfs"]
	access = basic

which doesn't exist in other clones, and I get a message 'Remote origin does not support the LFS locking API'

**Comment by j-f1** [comment]
Aha! This looks like it’s caused by https://github.com/desktop/desktop/issues/2812. Can you go to Repository → Open in Command Prompt, then run this command?

```
 git config lfs. http://git.internal.esptl.com/LGMA/MRL.git/info/lfs.locksverify false
```

That should fix the issue.

**Comment by wmevius** [comment]
You are a genius! Thanks! all fixed now :)

**Comment by technoweenie** [comment]
BTW, LFS v2.3.1 contains a fix for this, so you won't have to disable locks verification anymore.

**Comment by HeavyMedaI** [comment]
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/6917144/170012661-0ec497fc-b231-4b4c-84d8-03a689356e76.png">

Hello guys,

I am having this issue right now on MacOS Monterey 12.3.1, Intel Core i9, 16GB RAM
Any recommendation to solve this yet?

Nothing in the log btw.

I did undo it and commit again but it stoped again. 😕

**Comment by ikotovnic** [comment]
same problem
