### ISSUE TITLE
"Open this repository in Explorer" does not open to root directory

### ISSUE THREAD

**Issue by mike-eason** [desktop/desktop#2798]
### Description

Clicking on the "No local changes, would you like to open this repository in Explorer?" link will open the explorer to the directory just above the repository. I'd expect it to open to the root of the repository directory.

This issue is the same with the "Show in Explorer" menu item (Repository -> Show in Explorer).

### Version

**GitHub Desktop version:** 1.0.0

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Set up a new folder with a new git repository.
2. Add the repository to GitHub desktop.
3. Navigate to the repository using the left sidebar and make it the active repository.
4. Repository -> Show in Explorer or click the "No local changes, would you like to open this repository in Explorer?" link.

The explorer will open to the directory above the repository.

For example, if your repository was located in: `C:\Desktop\MyRepo\`, the explorer would open to `C:\Desktop\`

**Expected behavior:** The explorer should open to the directory of the repository, not it's parent.

**Actual behavior:** The explorer opens to the repository's parent directory.

**Reproduces how often:** 100%

### Logs

N/A

#### Additional Information

N/A

**Comment by iAmWillShepherd** [comment]
Thanks for your feedback! 👍

**Comment by shiftkey** [comment]
I think this is a side-effect of using [`shell.showItemInFolder `](https://electron.atom.io/docs/api/shell/#shellshowiteminfolderfullpath) for folders.

> Show the given file in a file manager. If possible, select the file.

Maybe we should be using `shell.openExternal()` with an explicit `file://` path:

> Open the given external protocol URL in the desktop’s default manner. (For example, mailto: URLs in the user’s default mail agent).
