### ISSUE TITLE
In History mode, view/copy individual file, when file is selected

### ISSUE THREAD

**Issue by artivilla** [desktop/desktop#2801]
### Description

Quite frequently I need to revisit or open the file in my editor when I view the  history diff. There currently isn't a way to copy/view the file name as it gives me a count of files changed. Present the relative file name similar to when viewing 'Changes' mode.

**GitHub Desktop version:** 0.9.1

**OS version:** 10.12.6

**Actual behavior:**

![github_desktop](https://user-images.githubusercontent.com/2120159/30662556-75368eba-9e15-11e7-8f72-63d45b0e621a.png)

**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
If someone would like to have a go at contributing this change, #2803 is a similar example - you just need to find the right selector to update in [`app/styles/ui/_file-list.scss`](https://github.com/desktop/desktop/blob/master/app/styles/ui/_file-list.scss).

**Comment by artivilla** [comment]
Oh, I can edit that but I meant I wanted to display the relative dirname/filename similar to show it's shown when in 'Changes' mode:

<img width="945" alt="github_desktop" src="https://user-images.githubusercontent.com/2120159/30677532-2b106726-9e5a-11e7-8f8e-5e05eb839479.png">

**Comment by shiftkey** [comment]
@artivilla I'm not clear on what needs to change - isn't the list of files below the commit header what you are looking for if you want to copy the file path? Or do you want the diff header for the history view to have the same header?

**Comment by artivilla** [comment]
Aaah, right -- it is the item in the list I want to copy. I was initially thinking it needs to be displayed in the header. Will put out a PR. Thanks :)

**Comment by shiftkey** [comment]
@artivilla 👍

**Comment by artivilla** [comment]
So just realized when I copy the file that's longer than the view, it prints the ellipses which we don't want. Might need to revisit this so copying actually copies the file path. Can I reopen this issue.

**Comment by shiftkey** [comment]
@artivilla please open a fresh issue - I think this requires some more thought about the best way to combine "draw the right amount of letters in the available space" with "let the user copy the full path"...
