### ISSUE TITLE
Floating Minimize tooltip on Windows desktop

### ISSUE THREAD

**Issue by ryanfreeth** [desktop/desktop#2805]
### Description

When you minimize by clicking the minimize button in the title bar a floating `Minimize` tooltip is left on the Windows desktop.

### Version

**GitHub Desktop version:** 1.0.0
**OS version:** Microsoft Windows [Version 10.0.10586]

### Steps to Reproduce

1. Minimize GitHub Desktop by clicking minimize in the title bar

**Expected behavior:** No erroneous floating Minimize tooltip

**Actual behavior:** An erroneous floating Minimize tooltip on the Windows desktop

**Reproduces how often:** Always

### Logs

The logs only have info entries for git fetches

#### Additional Information

If you minimize by clicking the icon in the taskbar the floating minimize tooltip does not display.

A quick Google search makes me thing this is a mildly ubiquitous Electron issue

![floating minimize](https://user-images.githubusercontent.com/1455939/30668681-5bd577a6-9e10-11e7-8c28-f6830dc42706.JPG)

**Comment by j-f1** [comment]
Thanks for contributing!

Unfortunately, this is an Electron issue. See electron/electron#9943 for details.

**Comment by iAmWillShepherd** [comment]
Hi @ryanfreeth , thanks for bringing this up! We are aware of this issue and as @j-f1 mentioned, there is an issue for it already.
