### ISSUE TITLE
Drag down commit notes separator to see more detailed notes

### ISSUE THREAD

**Issue by jaanus** [desktop/desktop#2813]
### Description

Currently, the only way to see full commit notes is to click “expand” on them, so they fill the right panel, and you need to separately collapse them. I’d like to expand this panel to see just a bit more, but keep the other info (file list, detailed diffs) there.

### Version

**GitHub Desktop version:** 1.0.0

**OS version:** OS X 10.12.6

### Steps to Reproduce

1. Look at a commit with detailed notes.

**Expected behavior:** I can drag the separator down to see more notes without doing explicit expand/collapse actions.

**Actual behavior:** I need to click “Expand” to see detailed notes (and later “Collapse” to go back).

**Reproduces how often:** 100%

![screen_shot_2017-09-21_at_09_48_21](https://user-images.githubusercontent.com/184253/30682574-ce96eb88-9eb2-11e7-8690-a3d3726b4cc9.png)

**Comment by steveward** [comment]
I'm going to close this out since the commit pane now expands to only the needed amount instead of taking up the entire view.
