### ISSUE TITLE
New app Icon on OS X is really weird

### ISSUE THREAD

**Issue by mourner** [desktop/desktop#2815]
### Description

The new default app icon for GitHub Desktop is very bland and low contrast — it looks like a disabled icon and stands out a lot in the Dock:

![image](https://user-images.githubusercontent.com/25395/30689540-ea1c77e4-9ec9-11e7-9e7a-00a76a21e287.png)

Is this some kind of bug, or is the icon supposed to look like this? Is there a way to roll back to the previous icon with normal contrast/saturation?

### Version

**GitHub Desktop version:** v1.0.0
**OS version:** MacOS High Sierra 10.13

### Steps to Reproduce

1. Look at the app icon.
2. Freak out.

**Expected behavior:** Nice icon.
**Actual behavior:** Weird icon.
**Reproduces how often:** Always.

**Comment by j-f1** [comment]
That looks like a bug. Can you try quitting the app, dragging it out of the dock, then dragging it back in? If that doesn’t work, logging out and logging back in or restarting the computer should fix it.

Here’s what I see:

<img width="93" alt="screen shot 2017-09-21 at 06 20 22" src="https://user-images.githubusercontent.com/25517624/30691254-2ddcf9ac-9e95-11e7-8380-21453f839416.png">

**Comment by mourner** [comment]
Tried it, didn't fix it. I looked at the App package contents and the icons file has those weird light icons too (alongside normal ones):

![image](https://user-images.githubusercontent.com/25395/30691616-fb1e6276-9ed0-11e7-9b92-537d8f24c741.png)

**Comment by mourner** [comment]
Could it be a High Sierra issue?

**Comment by tierninho** [comment]
@donokuda any ideas?

**Comment by shiftkey** [comment]
It's an obscure High Sierra issue - https://github.com/atom/atom/issues/15410#issuecomment-328652472

> Did some research, and apparently `.icns` files generated with Icon Slate.app are the culprit here. Really funny that this impacted mostly Electron apps, as their designers don't use Xcode to generate their app icons.
>
> Started using Icon Creator, and the icon looks great now.

**Comment by joshaber** [comment]
@donokuda could you do the needful to recreate the icon?

**Comment by donokuda** [comment]
> @donokuda could you do the needful to recreate the icon?

Yup. This is something on my radar to do for Desktop and Atom after I upgrade to High Sierra.

**Comment by shiftkey** [comment]
Dropping the `bug` label as we know the root cause and it just requires a refresh of the icon/s.

**Comment by psy2k** [comment]
Just a quick note. This affects only retina (and 4k screens) and only High Sierra! Icons look fine on Sierra.

**Comment by shiftkey** [comment]
> We know the root cause but is it something that'll fix in app updates or am I required to do something as the end user in refreshing the icons?

This should work with an update to the app by us, without any additional work from the user.

**Comment by Starbix** [comment]
Thank you for fixing this!

**Comment by multinerd** [comment]
updated today and it still appears faded. is there a cache folder that needs to be deleted?

**Comment by donokuda** [comment]
@multinerd Can you paste which version you're running? You can find this in the "About GitHub Desktop" menu item in the app menu. I'm currently running `1.0.4-beta0` and am having issues reproducing this. I also feel a little silly asking this 😅, but can you also quit and reopen GitHub Desktop?

<img src="https://user-images.githubusercontent.com/1174461/31087655-b6fde9d8-a752-11e7-80c0-9ee7714bc9b5.png" width="467" />

**Comment by multinerd** [comment]
Im running 1.0.3. Closing and reopening\restarting didn't fix the icon, force closing from activity monitor did. Its the right color now, thanks

**Comment by justinko** [comment]
@multinerd Force closing fixed for me as well. Thanks!

**Comment by WayneEllery** [comment]
I noticed that after updating it doesn't fix it immediately. You need to close the app and re-open it to fix it.

**Comment by danielbayley** [comment]
<kbd>⌘</kbd>-<kbd>click</kbd> on an app in the Dock will reveal that app in Finder but also refresh the icon… no need to reload the app.

**Comment by samhermes** [comment]
After updating, I had to drag the icon out of the dock and reopen the app to get it to display properly.
