### ISSUE TITLE
G-Data virus scan reports a trojan

### ISSUE THREAD

**Issue by do-while** [desktop/desktop#2837]
I have installed the Desktop from Website in the version "Windows 64Bit" on a Windows 10 Pro version 1703, Build 15063.608.

After login with my Github account the virus scan G-Data moved the file to quarantine area.
**Details:**
Datei:     C:\Users\...\AppData\Local\GitHubDesktop\app-1.0.0\resources\app\git\mingw64\libexec\GitHub.Authentication.exe
Infektion: Trojan.RansomKD.12390640 (Engine A)
Status:    Datei in Quarantäne verschoben

Is the alarm real?
or is there a signature problem with G-Data?

**Comment by iAmWillShepherd** [comment]
It is likely a signature problem with G-Data.

**Comment by ChadTaljaardt** [comment]
https://github.com/desktop/desktop/issues/2839

**Comment by joshaber** [comment]
This is something that needs to be reported to the anti-virus vendor as a false positive so they can update their definitions.
