### ISSUE TITLE
`Git Clone Failed: exit status 128` surfaced in Clone modal in conjunction with network error

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2838]
Cloning error was surfaced in the URL tab of the Clone modal when internet connection was turned off on purpose. Perhaps it could be made more user-friendly? This repo was cloned successfully with internet enabled.

<img width="1026" alt="screen shot 2017-09-20 at 13 37 46" src="https://user-images.githubusercontent.com/14828183/30646770-9de26372-9e09-11e7-9fe8-b4aec7025292.png">

related to #2796 and potentially related to: #2830 as the errors are the same

tested v1.0.0, mac

**Comment by Hacklesss** [comment]
I fix that with rename file name compatible with Windows. I mean I had a file as "android:id" and I was getting this error message. After 5-10 minutes I noticed that ":" is not usable in Windows. When GitHub desktop trying to fetching file, system reject this ":"  symbol. Maybe your problem is about that.

**Comment by Jeslopov** [comment]
Hi, I'm getting a similar error, 
```
Cloning into 'E:\ReposClones\angular-cli.wiki'...
fatal: unable to access 'https://github.com/angular/angular-cli.wiki.git/': Couldn't connect to server
Error(s) during clone:
git clone failed: exit status 128
```
This issue is the closest I have found to what im getting, but not pretty sure
Im trying to clone a repo on Github Desktop
OS: W10
Thanks

**Comment by shiftkey** [comment]
@Jeslopov this part of the message is the most interesting:

> `Couldn't connect to server`

This issue is about making the error message more friendly - if you'd like to get to the bottom of this issue please open a new issue, fill out the template and tell us about your setup.

**Comment by shiftkey** [comment]
I'm going to fold this up into #926 which is about being able to retry a clone when it fails, without having to redo the whole clone flow again.

**Comment by lyiriyah** [comment]
having this issue on daemondevin/GitHubDesktopPortable with dialog error:
`fatal: unable to access 'https://github.com/lyiriyah/theta.git/': Failed to connect to github.com port 443: Connection refused`

**Comment by tierninho** [comment]
@lyiriyah Please open a fresh issue with details of your problem and we will be happy to take a look. Thanks.

**Comment by lyiriyah** [comment]
@tierninho will do

**Comment by mikechen66** [comment]
If users forget to configure the git, it has the above-mentioned problem of exit code 128. I use the following methods to solve
the problem.

**1.Install git**

```
$ sudo apt install git 
$ git --version
```
git version 2.25.1

**2. Configure git**

```
$ git config --global user.name "your_user_name"
$ git config --global user.email "your_email_address"

```
**3. Check the configuration**

`$ git config --global --list`

```
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=your_user_name
user.email=your_email_address
```
