### ISSUE TITLE
Github Desktop executes bashrc files as scripts instead of opening in a viewer

### ISSUE THREAD

**Issue by jongarrison** [desktop/desktop#2841]
Double clicking on a bashrc file that is part of an open github repo in the Github Desktop "Uncomitted Changes" tab, launches the file as a script vs showing it in a viewer.

### Description

When viewing the changed files of repo double clicking on a bashrc file or any bash script should open the file in a text editor not launch the file as an executed script.  Launching a script could cause all sorts of problems.

### Version

**GitHub Desktop version:** 223

**OS version:** OSX 10.11.6

**Comment by iAmWillShepherd** [comment]
Thanks for bringing this to our attention!

**Comment by iAmWillShepherd** [comment]
Thanks! It looks like this issue is with the Classic apps, but this repository is for issues with the redesigned GitHub Desktop (see https://desktop.github.com).

Since this issue doesn’t apply so I’m gonna close it.

**Comment by iAmWillShepherd** [comment]
Thanks! It looks like this issue is with the Classic apps, but this repository is for issues with the redesigned GitHub Desktop (see https://desktop.github.com).

Since this issue doesn't apply so I'm gonna close it.
