### ISSUE TITLE
Repeatable "Minimize" Tooltip Glitch

### ISSUE THREAD

**Issue by Seeker9889** [desktop/desktop#2842]
### Description

Minimize Tooltip remains on screen after minimize button is selected. Tooltip remains indefinitely until program is opened again.

### Version

**GitHub Desktop version:** 1.0.0

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Run GithubDesktop
2. Click minimize button in top right of application window

**Expected behavior:** Tooltip, if it appears at all, will disappear after button is selected

**Actual behavior:** Tooltip remains on screen toward the top of my screen on top of any other windows.

**Reproduces how often:** 100%

**Comment by j-f1** [comment]
Thanks for contributing!

Unfortunately, this is an Electron issue. See electron/electron#9943 for details.
