### ISSUE TITLE
Add file context menu in history view

### ISSUE THREAD

**Issue by xPaw** [desktop/desktop#2845]
Desktop 1.0.1 on Windows 10.

There's an context menu (right click) on files when viewing changed files which allows opening it in an external editor. It would be useful to have a similar menu in history view to open a file in external editor or show in explorer.

**Comment by joshaber** [comment]
Thanks @xPaw! I agree that would be nice.

For anyone interested in pursuing this, we'd need to make sure the file still exists on disk before letting the user take any actions.

**Comment by j-f1** [comment]
The app could also checkout the file as it was in that commit to a temporary directory, then open the file from there. I don’t know how that could be changed to work for revealing the file in Finder/Explorer.

**Comment by shiftkey** [comment]
Bumping this issue with the feedback from #3731

> The reason is, I often am looking at a file in the commit history, and I want to quickly navigate directly to that file (to begin working on it again, or view the entire thing in my editor of choice). Currently, I must mannually navigate from the home directory of the repository to where that file is.

**Comment by lewispg228** [comment]
I would definitely love to see this feature happen! Thanks for responding to my submission so quickly, and sorry I didn't find this issue during my initial searching.

**Comment by tooomm** [comment]
I want to see that as well!
I highly suggest not only to allow to open files via context menu, but more intuitively with a simply double click!

>Especially in the `Changes` view that would be great to further work with the file or e.g. fix errors spotted in the in-app diff.

>For `History` tab it makes only sense if it would open the file in the browser at the related commit maybe.

**Comment by stuta** [comment]
I do commits in vscode. This app is not useful without this feature. Should not be hard to do.

**Comment by shiftkey** [comment]
@stuta could you open a new issue and provide more details about what you would like to see supported?

**Comment by crea7or** [comment]
Is there someone who will do this feature or maybe I can try to do it?

**Comment by iAmWillShepherd** [comment]
@crea7or , we'd love it if you tried to give this a shot! 🎉 

Is there any information you need from us to make this easier?

**Comment by crea7or** [comment]
@iAmWillShepherd  I think no, I just need some time to learn about React since I'm C++/C#/Java developer (currently working with chromium sources and github client is the one that can work with it).

**Comment by crea7or** [comment]
Ok, this is my first code in React. I think my code violates a lot of your rules, but can someone review it and maybe help me to send it as pull requst when I'll fix all possible problems?
Only two menu items added (open in explorer/open in default programm) and no checks added for file (presist on the disk or not).
[here is this commit with menu added in repo history](https://github.com/crea7or/desktop/commit/f98569b385607b22ccc1ee690451e9562968a5e5)

**Comment by j-f1** [comment]
@crea7or That looks pretty good to me! Feel free to open a pull request and tell us when you’re ready to review. We generally do our reviews in the context of a pull request, then merge once the changes have been made. Don’t worry about squashing your commits — it’s okay to have many commits in a PR.

**Comment by crea7or** [comment]
@j-f1 [done](https://github.com/desktop/desktop/pull/4037).
