### ISSUE TITLE
GitHub Desktop 1.0.1 Logged in but get authentication failure on push or pull

### ISSUE THREAD

**Issue by e76nystrom** [desktop/desktop#2847]
I am trying to use GitHub Desktop to access a repository that I have been using with Windows Git from Windows 10 64Bit.  I am able to log in with GitHub Desktop but get an an authorization failure when I try to do a push or pull.  The following is extracted from the log file:

2017-09-22T18:15:15.607Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 6.772s)
2017-09-22T18:15:15.617Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. You may not have permission to access the repository. Open options and verify that you're signed in with an account that has permission to access this repository.)

I read over the documentation but did not see anything about setting up a public key similar to what I did for putty and ssh.  Did I miss something?

**Comment by e76nystrom** [comment]
I was able to get it working by adding the public key found in my %USERPROFILE%\.ssh\id_rsa.pub.
%USERPROFILE% is C:\User\(your user name)

Should this be mentioned in the documentation?

**Comment by e76nystrom** [comment]
I tried it on another system that had never had %USERPROFILE%.ssh setup.  There were no messages about needing to setup the public key.  I added RSA key files and a known_hosts file containing github and was able to get that system working also.

**Comment by shiftkey** [comment]
@e76nystrom thanks for the feedback. We're tracking a similar story over in #2579 around helping to setup SSH better, whether it's documentation or in the app itself. Please keep an eye on that issue.

**Comment by heyimalex** [comment]
Simple fix (if you don't care about ssh vs https) is [to change the remote's url](https://github.com/HeardAndSmith/hsdoc-frontend.git). For anyone else who lands here.

**Comment by gtkpr** [comment]
i'm experiencing the exact same issue. i'm brand new to github, hoping to participate in hacktoberfest, but for whatever reason using github is more complicated than coding itself :/

**Comment by joshaber** [comment]
@gtkpr Could you create a new issue and fill out the issue template please? Thanks!

**Comment by gtkpr** [comment]
@joshaber i'm not even going to bother. already uninstalled it. i'll just do my stuff via browser.

**Comment by jborn** [comment]
I've tried copying a github_rsa.pub to id_rsa.pub in %USERPROFILE%\.ssh to no avail.  Still can't clone, fetch, push or pull.  Very frustrating when the classic github desktop just worked.

**Comment by joshaber** [comment]
@jborn Please open a new issue and fill out the issue template so that we're better able to help you.

**Comment by Rodge** [comment]
For me it helped by simply logging out and in again (in File -> Options).

**Comment by leonardosantoslopes** [comment]
As Rodge said, log out and log in back.

It worked.

**Comment by qysnn** [comment]
Yes. After hours of search I finally solved it by logging out and log in again. That is frustrating.

**Comment by whiteboxgaming** [comment]
Im having same issue and I've had Github a long time. I think its time to go shopping
