### ISSUE TITLE
UI to add a .gitattributes to the selected repo

### ISSUE THREAD

**Issue by xt0rted** [desktop/desktop#2850]
### Description

In the native clients (at least on Windows) when you were looking at the repos settings there was a tab to view/add a `.gitattributes` to the repo called **Line endings and attributes**. When creating a repo on GitHub.com there's no UI to add one of these by default, and so when you clone for the first time it's common to need to add one. I'd like this process to be easier since using the app to create a repo does create a `.gitattributes` (not the same content as the native client, see below for comparison).

### Version

**GitHub Desktop version:** 1.0.2-beta0
**OS version:** Win10 Creators Update

### Steps to Reproduce

1. Open a repo's settings
1. Try to find the line endings and attributes settings
1. Come up empty handed
1. Open the native client
1. Rinse
1. Repeat

**Expected behavior:** Some type of UI for adding and managing the `.gitattributes` file just like we have for the `.gitignore` file

**Actual behavior:** There is none

**Reproduces how often:** All the time 😢

#### Additional Information

These are the contents of the file from each of the clients.

**New client**

```
# Auto detect text files and perform LF normalization
* text=auto
```

**Native client**

```
# Auto detect text files and perform LF normalization
* text=auto

# Custom for Visual Studio
*.cs     diff=csharp

# Standard to msysgit
*.doc	 diff=astextplain
*.DOC	 diff=astextplain
*.docx diff=astextplain
*.DOCX diff=astextplain
*.dot  diff=astextplain
*.DOT  diff=astextplain
*.pdf  diff=astextplain
*.PDF	 diff=astextplain
*.rtf	 diff=astextplain
*.RTF	 diff=astextplain
```

**Comment by shiftkey** [comment]
Hey @desktop/design, this isn't a high priority but when you have some cycles it'd be great to get some thoughts on what a workflow in the app like this might look like:

 - detects the repository is in some state that is suboptimal and provides some indicator to the user
 - suggests to the user an action that should be undertaken
 - user can dismiss this (for whatever reason) but most of the time this should be enticing or easy to perform
 - repository is updated, and problem goes away

I touched on the implementation details a bit in #1964, for reference

**Comment by shiftkey** [comment]
@xt0rted as discussed in #1964, this is beyond our current roadmap. Let's see what the Design crew come back with in terms of how this might look in the app, and we'll figure out where to take it from there.

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by billygriffin** [comment]
I'm removing the `future-proposal` label here as we're trying to streamline and prioritize. We'll be tracking this going forward in the issue linked above.
