### ISSUE TITLE
[docs] bulk add local existing repositories

### ISSUE THREAD

**Issue by hcoona** [desktop/desktop#2857]
### Description

I want a new feature to help add many local existing repostiories. Either command line tool or recursively finding helps.

### Version

**GitHub Desktop version:** 1.0.1

**OS version:** Windows 10

**Comment by shiftkey** [comment]
@hcoona currently you can drag-and-drop multiple folders onto the app to add them. That's the best workaround we have at the moment.

**Comment by hcoona** [comment]
Cool! We should have it in document. That's a very useful workaround.

**Comment by shiftkey** [comment]
I've contributed a change to the docs around this. Once it gets :thumbsup: and merged I'll link to it here and close this out.

**Comment by shiftkey** [comment]
This documentation has been updated: https://help.github.com/desktop/guides/contributing-to-projects/adding-a-repository-from-your-local-computer-to-github-desktop/

![](https://user-images.githubusercontent.com/359239/31205744-047664f6-a9bf-11e7-9fbc-f73e8dcb1c19.png)
