### ISSUE TITLE
Login Windows opening randomly even though logged in

### ISSUE THREAD

**Issue by userlip** [desktop/desktop#2860]
### Description

About 4 Github Login windows are opening sometimes randomly even though I am logged in. When I proceed to close them even more open. After closing them all they just keep coming every few minutes
Here's a pic: https://i.imgur.com/m8fyMTe.jpg

### Version

**GitHub Desktop version:** 1.0.1

**OS version:**Microsoft Windows [Version 10.0.15063]

**Comment by shiftkey** [comment]
@userlip I don't believe this is related to GitHub Desktop - is that VSCode that you're using in the background? If so, it doesn't use Desktop's authenticated token and needs to be authenticated separately for a private repository.

**Comment by j-f1** [comment]
Also, I don’t think the new GitHub Desktop provides that UI.

**Comment by shiftkey** [comment]
That UI is from the [Git Credential Manager for Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/) project, which is bundled in Git for Windows.

**Comment by userlip** [comment]
Yeah it is VSCode in the background! So what should I do? It is true that I am using some private repositorys with VSCode. Unfortunately logging in on these windows does not help either.

Thanks for the help!

**Comment by shiftkey** [comment]
@userlip if this is an ongoing issue, I would suggest updating your Git for Windows installation to ensure you are on the latest version of `git-credential-manager`. If that still doesn't resolve it, I'd open an issue with the VSCode project.
