### ISSUE TITLE
Provide download link to old native app for Mac

### ISSUE THREAD

**Issue by Superpencil** [desktop/desktop#2865]
Hi, there was a download link on the website before for the old native version that is now gone, could you point me to one? 

- The old app had a bunch of auto-stashed changes that I now have to manually sort through
- I don't have enough RAM to use this new version I think
- The battery usage is 4x that of the old one so it inhibits my mobility

P.S. I totally understand moving to a unified codebase for all OSes, I'll use this new one once I upgrade to a new Mac

**Comment by joshaber** [comment]
Hi @Superpencil!

For the moment you can still get the old app from https://central.github.com/mac/latest. No guarantees how long that'll last though 😄 

Anecdotally, the new app uses about half the RAM that the old app did and feels faster to me. I'm biased, but you might give it a shot before assuming it'll perform worse.

**Comment by Superpencil** [comment]
Thank you @joshaber I was able to get through all my old stashes! I’m currently using the new app and it’s fine like you said, good job! The only feature I miss is easy base branch selection and merge, it’s possible through a menuitem though 🤘
