### ISSUE TITLE
Select current pull request by default

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#2873]
The pull request list should have the pull request for the current branch selected by default.

**Comment by joshaber** [comment]
(I didn't do this in https://github.com/desktop/desktop/pull/2823 because there's a chicken-and-egg situation with it and https://github.com/desktop/desktop/pull/2871.)

**Comment by iAmWillShepherd** [comment]
I see. Is it cool if we keep this since there is no issue for it? I'll add it to the master issue, so it doesn't get lost (or I forget about it).

**Comment by joshaber** [comment]
Yup, go for it 👍
