### ISSUE TITLE
formatting rules for SCSS files

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#2875]
Context: https://github.com/desktop/desktop/pull/2848

> p.s on saving, the spacing between lines 3/4 get's removed. Is that related to my vscode editor?

We're already prettier-ifying things, but it seems like VSCode is now eager to format these. An `.editorconfig` file at the root would work for all editors that respect this.

For example:

```
# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true

# 4 space indentation
[*.scss]
indent_style = space
indent_size = 4
```

There are some other VSCode specific formatters (and probably things for Atom too) but I'd rather make this generic and let people work wherever they want.

**Comment by j-f1** [comment]
[sass-lint](https://github.com/sasstools/sass-lint) looks like another useful thing to add here for consistency.
