### ISSUE TITLE
Tooltip for “Minimize” Button Gets Stuck on Screen

### ISSUE THREAD

**Issue by patrickdark** [desktop/desktop#2878]
### Description

If you click the “Minimize” button before the “Minimize” tooltip appears, the tooltip displays on screen indefinitely until you return focus to GitHub Desktop. I am able to reproduce this.

### Version

**GitHub Desktop version:** 1.0.1

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Open GitHub Desktop.
2. With the cursor outside of the “Minimize” button (at the top-right of the window), move the cursor onto the button and click it before the “Minimize” tooltip for that button can appear.

**Expected behavior:** The “Minimize” tooltip should never appear.

**Actual behavior:** The “Minimize” tooltip appears and remains on screen indefinitely until the GitHub Desktop window is re-opened.

**Reproduces how often:** 100%.

### Logs

I don’t think logs are applicable here.

#### Additional Information

I discovered how this issue worked via the third-to-last comment (on page two) by soulphish on 2017-07-11 at https://answers.microsoft.com/windows/forum/windows_7-performance/a-tooltip-is-stuck-on-the-desktop-and-will-not-go/debf9394-8bc0-49bd-b060-218faba8925a. (There doesn’t appear to be any method to directly link to the comment.) The meat of the comment:

> I found that the solutions here (on the first page anyway) didn't work.
>
> What resolved it for me, was finding the program that the tooltip was from. For example, my issue was "Minimise" continued to stay on screen. 
>
> This continued to stay until I restored the offending program and then it disappeared. Turns out if I fly up to the minimise icon and click it before it shows the tooltip, the tooltip is still generated, but the window is gone, so it doesn't know to stop the tooltip o something. If I wait for the tooltip to show, and then minimise, it disappears with the window.

My system uses Windows 10, however.

This issue doesn’t seem to occur in applications that use the yellow tooltips in the style of File Explorer or applications that don’t use tooltips for the “Minimize” button like Mozilla Firefox.

**Comment by shiftkey** [comment]
@patrickdark thanks for reporting this!

Unfortunately, this is an Electron issue. See electron/electron#9943 for details.

**Comment by TrevorMullen** [comment]
The Slack Desktop also displays this behaviour.

**Comment by honkmother** [comment]
microsoft
if you can hear me
BRING BACK STEVE BALLMER SO THAT
**THIS SHIT CEASES**
