### ISSUE TITLE
In "Pushing to origin" dialog box, text is cut off b/c the text in the box is too long. 

### ISSUE THREAD

**Issue by rellimmot** [desktop/desktop#2879]
### Description

In the "Pushing to origin" dialog box within the main application window, the upload speed does not show because the text in the box is too long.  For example (at this moment): **Writing objects: 32% (543/1671), 4...** is the cut off text I'm shown under "Pushing to origin"

This doesn't actually bother me very much since I can open Task Manager or Process Hacker and see what the rates are so I'd consider this an improvement recommendation? Not trying to nitpick, so much as trying to help.

### Version

**GitHub Desktop version:** 1.0.0

**OS version:** Microsoft Windows [Version 10.0.14393]
                         Windows 10 v.1607 (creators update, build 14393.1593)
**System Specifics:** 4k resolution (but issue persists when dragged to my 1080p display), 
                                 125% scaling (but this did not change the issue when changed to 100%.

### Steps to Reproduce

1. Upload using GitHub Desktop in Windows.
2. Observe "Pushing to origin" dialog box. If size of upload or number of items is large enough, text will be cut off.

[2017-09-26.desktop.production.log](https://github.com/desktop/desktop/files/1332032/2017-09-26.desktop.production.log)

Check this [GIF Animated](https://i.imgur.com/MSQNt1q.gifv) recording showing this behaviour.

**Expected behavior:** Text in box is not cut off.

**Actual behavior:** Text in box is cut off.

**Reproduces how often:** 100% of the time when the text is long.

#### Additional Information

I'd recommend perhaps having those boxes sized actively scaled to window width, auto-scaling text, or popping up the text contents upon mouse hover.

**Comment by shiftkey** [comment]
> or popping up the text contents upon mouse hover.

@rellimmot I think this is the easiest solution to the problem
