### ISSUE TITLE
Equivalent of "git init" missing?

### ISSUE THREAD

**Issue by JeffCohen** [desktop/desktop#2883]
### Description

The old version of the app allowed one to convert an ordinary folder into a repo by dragging the folder onto the app or selecting "Add Repository".  In either case, the app would prompt if it should turn the folder into a repository (essentially just doing a `git init`), which was very helpful.

Maybe I'm missing something, but now that seems impossible.  When prompted to "Create a Repository" instead, a brand new subdirectory for the repo is created, rather than running `git init` on the selected folder.

### Version

**GitHub Desktop version:** 1.0.1

**OS version:** macOS High Sierra (also reproduced on macOS Sierra)

### Steps to Reproduce

1. Drag an ordinary folder into the app (or use Add Local Repository and choose the folder)
1. You'll get a message saying "This directory does not appear to be a Git repository. Would you like to create a repository here instead?" and the "Add Repository" folder is disabled
1. Click "create a repository here"
1. You get the Create New Repository dialog (which I don't think is necessary)
1. Enter a repo name and click Create Repository
1. Notice that you end up with a new subfolder for the repo

**Expected behavior:** The chosen folder should become a repository in-place

**Actual behavior:** A new subfolder was created

**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
@JeffCohen thanks for the report!

> Notice that you end up with a new subfolder for the repo

Yeah, this doesn't seem right. I'll see if I can re-create this issue.

**Comment by JeffCohen** [comment]
Thanks everyone!  Can't wait for the next release :-)
