### ISSUE TITLE
Unable to clone Gists in Desktop

### ISSUE THREAD

**Issue by cmrberry** [desktop/desktop#2886]
### Description

We have this nifty little button on the top of Gists just like we do for repositories:

<img width="1007" alt="screen shot 2017-09-26 at 12 51 51 pm" src="https://user-images.githubusercontent.com/7971632/30881164-aad79b7e-a2b9-11e7-95ef-9bfaead5a935.png">

However clicking that button does *not* clone the Gist as expected. 

### Version

**GitHub Desktop version:** 1.0.1
**OS version:** macOS 10.12.6

### Steps to Reproduce

1. Go to any Gist, like: https://gist.github.com/jboner/2841832
2. Click the "Download to Desktop" button that links to `x-github-client://openRepo/https://gist.github.com/2841832`

**Expected behavior:** The Gist should be cloned to my Desktop app.
**Actual behavior:** 
- A user reported that they were taken to desktop.github.com after clicking that button, even though they have Desktop installed.
- I was unable to reproduce that ☝️ but got an error every time:
<img width="471" alt="screen shot 2017-09-26 at 1 00 52 pm" src="https://user-images.githubusercontent.com/7971632/30881470-d44d66f4-a2ba-11e7-8c72-4cc76bf4cc56.png">

Note that it *doesn't* exist, because it won't let me clone it. It's a misleading error message in this case a well.

**Reproduces how often:** Every time for me.

### Logs

`2017-09-26T19:57:56.787Z - warn: [ui] Open Repository from URL failed, did not find repository: https://gist.github.com/2841832.git - payload: {"name":"open-repository-from-url","url":"https://gist.github.com/2841832.git"}`

**Comment by j-f1** [comment]
Does changing the “Local Path’ to `/Users/cmrberry/github/latency` work? If so, this error occurs because the app is unable to parse a name from the repository URL.

**Comment by shiftkey** [comment]
I _think_ this might have been fixed by #2863 but I'll confirm this is reproducible on `master`.

**Comment by shiftkey** [comment]
@cmrberry this is occurring because we don't correctly detect Gists in the app, so it won't go and create the folder correctly. I thought this was going to be a simple fix, but it looks like this touches a lot of areas - I've opened #2973 to track these tasks.

In the meantime, you can go and edit the Local Path value which will then enable you to clone the repository down.

**Comment by DixCar** [comment]
I have same problem but 
GitHub Desktop version 1.0.3 (latest at this day)
OS Windows 10 Home

**Comment by WiliTest** [comment]
I also had a problem with this button.
 ● The first time it asks to install the app. I did it again (and again) and it asked me to install the app. An hour later it works. I guess it's a cash issue, the page should maybe be reloaded. If that doesn't work open the URL tab of the desktop app and write a link like that: https://gist.github.com/hj78ad2c234565bhds0540sha.git

● then I ran into another problem: "the destination already exist". I gave up.

**Comment by ssowens** [comment]
Consistently getting the following error: "The destination already exists." If I add "latency" as stated above the error goes away. However, why is this happening? Please assist. 
<img width="451" alt="screen shot 2018-10-05 at 4 55 36 pm" src="https://user-images.githubusercontent.com/3893230/46559825-8a55fd00-c8bf-11e8-8e01-3b434489a82d.png">

**Comment by aghaynes** [comment]
As @shiftkey previously mentioned, changing the default local name to something meaningful/normal (rather than the long names that github assigns) seems to work.

**Comment by theconsultant** [comment]
Changing the default local name to something meaningful worked for me as well.

@shiftkey I don't know if it can be done or not.. but maybe the error message could link to here, or even just tell folks the workaround 'for now' ;-)

**Comment by billygriffin** [comment]
I'm going to roll this into #2886 because we know the experience for managing Gists in Desktop isn't particularly good in a variety of ways, but it's not something we've been able to prioritize and that'll get looked at with the remainder of the future proposals still outstanding.
