### ISSUE TITLE
Development version of Atom is not detected

### ISSUE THREAD

**Issue by 50Wliu** [desktop/desktop#2894]
### Description

Looks like dev versions of Atom (versions that are built locally and not installed through Squirrel) aren't recognized by Desktop 😢.  I skimmed through #2585 and it looks like there are two checks for Atom integration: the existence of an uninstaller and `%localappdata%\Atom\bin\atom.cmd`.  Here's why I think Desktop isn't picking up on my installation (done through the usual `script\build --install`):
1. Since I'm building locally, no uninstaller exists. `Get-Item : Cannot find path
'HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\atom' because it does
not exist.`
2. I am using Atom x64, so the directory is `%localappdata%\Atom x64\bin\atom.cmd`.

### Version

**GitHub Desktop version:** 1.0.1

**OS version:** Microsoft Windows [Version 10.0.16296.0]

### Steps to Reproduce

1. `script\build --install` Atom

**Expected behavior:** Desktop to do its magic Atom integration

**Actual behavior:** No external editors detected

**Reproduces how often:** 100%

### Logs

I have looked at the most recent log and there's nothing interesting.  Mostly just a lot of fetches and clones.

#### Additional Information

I think there's enough info to reproduce the issue.  Please tell me if you need more though!

**Comment by shiftkey** [comment]
@50Wliu yeah, the same thing happens with a portable install because nothing is added to the registry - https://github.com/desktop/desktop/issues/2487#issuecomment-329154847.

Reading over `script\build` and the related `install-application` script, there's no registry work when you pass in `--install`, right? It's just moving files into `%LOCALAPPDATA%\atom` in the right way?

**Comment by shiftkey** [comment]
@50Wliu I'm going to roll this up into #2487 while I figure out where to take this feature.
