### ISSUE TITLE
The unusual icon on mac Dock bar

### ISSUE THREAD

**Issue by evanzhu2013** [desktop/desktop#2898]
### Description

The unusual icon on macOS High Sierra 10.13 

### Version

**GitHub Desktop version:** [1.01]

**OS version:** [macOS High Sierra 10.13 ]

#### Additional Information

<img width="380" alt="2017-09-28 6 05 50" src="https://user-images.githubusercontent.com/7533756/30961643-67b94722-a479-11e7-8132-48e7e70d8e8b.png">

**Comment by joshaber** [comment]
Thanks @evanzhu2013! That's a known bug with High Sierra. We're already tracking it in https://github.com/desktop/desktop/issues/2815.
