### ISSUE TITLE
Discrepancy in wording for opening file with editor

### ISSUE THREAD

**Issue by adamreisnz** [desktop/desktop#2904]
![image](https://user-images.githubusercontent.com/490562/30994961-ac1623f0-a513-11e7-9b03-712acb23b2a7.png)

vs

![image](https://user-images.githubusercontent.com/490562/30994963-b161a316-a513-11e7-8ab9-9aa8aaf23859.png)

This difference in wording is confusing when you are trying to quickly locate a menu item. For example when I want to open a repo in Atom, I know I need to look for "Open in Atom" in the menu. So my brain/eyes quickly scan for "Atom" to locate the menu item.

Then, every time I want to open a single file in Atom, I suddenly need to look for "default program", which always trips me up.

Can we make it consistent and call this context menu item the same, e.g. "Open in Atom"?

**Comment by j-f1** [comment]
The “default program” one actually used the OS’s logic to pick the app to use. For example, it’ll open Preview for image files.

**Comment by adamreisnz** [comment]
Hmmm, that's slightly annoying.

Is it possible to add another menu item above it then, which will be Open in Atom (if Atom is installed)? 99% of the time that's what you'd want, as we are all coding and we'd want to open the changed files with our code editor.

Maybe in the 1% of cases you might want to open a changed image or something.

**Comment by joshaber** [comment]
Yeah I agree the external editor / default program distinction is confusing.

>Is it possible to add another menu item above it then, which will be Open in Atom (if Atom is installed)? 

I think that's a good idea 👍

**Comment by adamreisnz** [comment]
There's another issue related to this, the "Open with default program" actually uses the default program, which happens to be VSCode for me because I just installed that. However, opening from the tree view still opens in Atom.

Personally I'd like to be able to always specify which application I open it with, in case I have multiple editors installed, or at least for both options to be consistent.

**Comment by billygriffin** [comment]
Is this fixed @adamreisnz? 

Right clicking on a file:
<img width="241" alt="Screen Shot 2019-03-15 at 4 26 43 PM" src="https://user-images.githubusercontent.com/5091167/54465106-245b8480-473f-11e9-99c1-65bac0a39807.png">

Repo menu options:
<img width="211" alt="Screen Shot 2019-03-15 at 4 27 31 PM" src="https://user-images.githubusercontent.com/5091167/54465126-3f2df900-473f-11e9-8ae0-edf6bc8cba80.png">

`Open with default program` is still an option (like what was previously mentioned about Preview for image files), but there's also the `Open in [detected editor]` option that should hopefully be clear?

**Comment by adamreisnz** [comment]
Yep! Are you on a big issue clean up mission? :)

**Comment by billygriffin** [comment]
@adamreisnz Thanks! Not sure what gave you that idea! 😄
