### ISSUE TITLE
Can't push to repositories from organisation

### ISSUE THREAD

**Issue by adamreisnz** [desktop/desktop#2908]
I can't seem to push to Github repositories belonging to an organisation that I have permissions to.
Apparently I can pull, but not push.

I tried to see if there are any specific authentication steps to take but couldn't find any. I am logged in and authenticated with the correct user, and I can push to my personal repo's fine.

Any thoughts? Is this an issue with the app? It's happening on both my machines so I doubt it's environmental.

`git push` from command line works fine.

OS X, app version 1.0.2

The only thing that appears in the logs is `Executing push: git -c credential.helper= push origin master:master --progress (took 1.232s)`

Maybe related, but create PR also doesn't work. The app doesn't open the create PR page in the browser for the repo.

**Comment by joshaber** [comment]
👋 

Is the repository categorized under "GitHub" in the repositories list?

>Maybe related, but create PR also doesn't work.

In what way does it not work? Is the menu item enabled?

**Comment by adamreisnz** [comment]
@joshaber 

> Is the repository categorized under "GitHub" in the repositories list?

Yes it is indeed, all my repo's are.

> In what way does it not work? Is the menu item enabled?

The app doesn't open the create PR page in the browser for the repo.

I think this is a separate issue though, because it only happened when you have an unpushed commit, and then click create PR, and answer the resulting warning with "create anyway" That button didn't do anything. I'll raise another issue for it.

**Comment by adamreisnz** [comment]
I've raised another issue for the PR problem -- it happens for any repo.
As for this issue, happy to help you troubleshoot/analyse the problem if you tell me what additional steps you'd like me to take.

**Comment by shiftkey** [comment]
> I can't seem to push to Github repositories belonging to an organisation that I have permissions to.

@adamreisnz organization and team permissions can be granular in this way (read/write/admin) and I think this is what is catching you up. Without poking around the repository it's hard to confirm this, but I think I can help you confirm what you're seeing:

- Browse to the Teams page for your organization: https://github.com/orgs/{org}/teams
- Click the team that you belong to (it might be multiple here)
- Across the top, click the "Repositories" menu item to show the list of repositories
- Find the problem repository, confirm whether it is "read" or "write" permissions for you

**Comment by adamreisnz** [comment]
@shiftkey I've followed the steps you recommended, but as I am the owner of the organisation, I have read/write access to all of them.

> It's not clear to me that this is erroring - it should return a non-zero exit code in this case and hit our error handling. What makes you think this is failing in the app?

Well, I meant that the `git push` command from the command line is working fine, but trying to push from the github desktop application fails with the aforementioned authorization warning.

> Also, long shot - could master be a protected branch on the repository?

Nop, master is not a protected branch in any of the repo's. This problem seems to affect all of my repo's in that organisation.

**Comment by shiftkey** [comment]
> Well, I meant that the git push command from the command line is working fine, but trying to push from the github desktop application fails with the aforementioned authorization warning.

Which warning? I'm not sure from the original message what you're seeing exactly...

**Comment by adamreisnz** [comment]
Pretty sure I had added a screenshot... hmmm. This is what I see:

![image](https://user-images.githubusercontent.com/490562/31065430-b3c5485c-a7a1-11e7-9633-fc9f1324ca1b.png)

**Comment by adamreisnz** [comment]
Do you still need more information for this issue?

**Comment by joshaber** [comment]
Sorry for the delay @adamreisnz! Could you give me an example of a repository you can't push to, so I can dig into it?

**Comment by adamreisnz** [comment]
All repo's at https://github.com/meanie for example

**Comment by shiftkey** [comment]
@joshaber I'm going to pick up #2623 again as that one needs some Windows-fu, but let me know if you want to bounce ideas around about this

**Comment by joshaber** [comment]
@adamreisnz Thanks! I haven't been able to find the rejected logins from the server side, oddly enough.

A few things that would help:

1. Try logging out and back in. I almost wonder if your token was created by an old version of a development build of the app. Orgs with OAuth app restrictions would reject it.
1. In the dev tools, change the logging level to "Verbose" and try again.
1. Take a screenshot or copy and paste the logs in here.

**Comment by adamreisnz** [comment]
@joshaber lifesaver. After logout and log back in it appears to have resolved the issue 👍 

For reference, this was the output from a push with verbose logging on (nothing strange) afaict:

![image](https://user-images.githubusercontent.com/490562/31414129-f23ae6ae-ae78-11e7-8eb3-2b30c74187db.png)

I'll leave it up to you if you want to keep this open to analyse further or close it off.
Thanks!

**Comment by joshaber** [comment]
Awesome, I'm glad to hear it!

It looks like @shiftkey's adding more logging around this in https://github.com/desktop/desktop/pull/3007 so I'm gonna close this.
