### ISSUE TITLE
Reveal in Finder opens in Default Program

### ISSUE THREAD

**Issue by BasThomas** [desktop/desktop#2909]
### Description

If you try to "Reveal in Finder" a file, you'll find GitHub Desktop actually opening the file in the default program. "Open with Default Program" will also open the file in the default program.

### Version

**GitHub Desktop version:** 1.0.2

**OS version:** macOS 10.12.6

### Steps to Reproduce

1. In a repo, have at least one changed file
1. Right click on the file, select Reveal in Finder

**Expected behavior:** Finder will be opened, at the place where the file is located

**Actual behavior:** Opens the file in the default program

**Reproduces how often:** Always

**Comment by joshaber** [comment]
Great catch @BasThomas!

This might be fallout from https://github.com/desktop/desktop/pull/2861? Also relevant is #2876.
