### ISSUE TITLE
Cant Clone Repository With Github Desktop

### ISSUE THREAD

**Issue by TiagoJoseMagalhaes** [desktop/desktop#2912]
Hi im trying to clone one of my repositories but it always seems to fail , i cant commit either i get the following error : 

Cloning into 'C:\Dev\Github\LAIG_T1'...
'C:\Users\TiagoMagalhaes' is not recognized as an internal or external command,
operable program or batch file.
error: unable to read askpass response from 'C:\Users\TiagoMagalhães(11506\AppData\Local\GitHubDesktop\app-1.0.2\resources\app\static\ask-pass-trampoline.bat'
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Error(s) during clone:
git clone failed: exit status 128

**Comment by shiftkey** [comment]
@TiagoJoseMagalhaes thanks for the report! We're tracking this in #2623, so please follow along with that issue.

I have some fresh theories on this, mostly due to this clue from the malformed characters:

> `'C:\Users\TiagoMagalhães(11506\AppData`
