### ISSUE TITLE
macOS dock logo changed color

### ISSUE THREAD

**Issue by kevzdev** [desktop/desktop#2913]
### Description
After an update of GitHub Desktop the dock icon changed color, the color of the icon in the launchpad is still the valid color.

LaunchPad icon:
![LaunchPad icon](https://i.imgur.com/BFSZToL.png)

Dock icon:
![dock icon](https://i.imgur.com/GId2g88.png)

### Version
**GitHub Desktop version:** 1.0.2
**OS version:** macOS High Sierra 10.13 (17A365)

### Steps to Reproduce

1. Get an outdated version of GitHub Desktop
2. Update GitHub Desktop
3. Restart your mac if the problem does not exist

**Expected behavior:** Icon should be the same color

**Actual behavior:** Icon changed color

**Reproduces how often:** 100%

**Comment by joshaber** [comment]
Hi @kevzdev 👋 We're tracking this in https://github.com/desktop/desktop/issues/2815. Feel free to follow along over there!
