### ISSUE TITLE
Create without pushing button does not work

### ISSUE THREAD

**Issue by adamreisnz** [desktop/desktop#2917]
![image](https://user-images.githubusercontent.com/490562/31027895-6d0dddac-a5a8-11e7-877f-80f9353801f8.png)

1. Create a commit, but don't push
2. Create a new PR (⌘R)
3. Dialog shows up as above
4. Press "Create without pushing"
5. Modal closes but nothing happens

Unrelated to #2908 as it happens for any repository.

OS X, app version 1.0.2

**Comment by tierninho** [comment]
Can reproduce this, but nothing in the logs or console.

**Comment by niik** [comment]
Looks like this was accidentally broken in https://github.com/desktop/desktop/pull/2823/commits/852ba4dd265eddbdcf3d488b87fb00cfe4a9154c (#2823). @shiftkey, I see that you're assigned here but judging from the other PRs from you today I'm guessing you've got your hands full already so I'll steal this as part of the first-responder rotation. If you've already got something we can use your stuff but I'll open a PR anyway.

**Comment by adamreisnz** [comment]
:+1:

**Comment by shiftkey** [comment]
@niik you guessed correctly - nice work on getting to the bottom of it :metal:
