### ISSUE TITLE
Large Check in Fails with Connection Time Out

### ISSUE THREAD

**Issue by kmarthak** [desktop/desktop#2921]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by j-f1** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by kmarthak** [comment]
Description

Adding new visual studio project of 30 GB to repository for 1st time. 

Version

GitHub Desktop version: [version here] 1.0.3

OS version: [version here] Windows 10

Steps to Reproduce

Open large visual studio project 
Go to Team Explorer
SYNC Project  

Expected behavior: Add new project to repository on GitHub

Actual behavior: Failed to SYNC

Reproduces how often: [What percentage of the time does it reproduce?] 100%

Logs

Warning: suboptimal pack - out of memory
Error: Out of memory, malloc failed (tried to allocate 39879466 bytes)
Error: failed to read object ffdd6d14186c8a8563a7b36909e41423de4bd731 at offset 12 from .git/objects/pack/pack-940085f7e88d1a5a924575968d20053aee889db9.pack
Error encountered while pushing to the remote repository: Git failed with a fatal error.
fatal: packed object ffdd6d14186c8a8563a7b36909e41423de4bd731 (stored in .git/objects/pack/pack-940085f7e88d1a5a924575968d20053aee889db9.pack) is corrupt
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Pushing to https://github.com/reortiz/PlannerWeb.git
error: failed to push some refs to 'https://github.com/reortiz/PlannerWeb.git'

Additional Information

**Comment by shiftkey** [comment]
@kmarthak thanks for the extra information. This information suggests the issue is related to using Git in Visual Studio:

> Open large visual studio project
> Go to Team Explorer
> SYNC Project

You should use the in-built reporting tools in VS to send this information to the team.
