### ISSUE TITLE
Minimize window

### ISSUE THREAD

**Issue by aayandre** [desktop/desktop#2922]
![githubdesktop](https://user-images.githubusercontent.com/25940107/31032125-3ace36c4-a531-11e7-9bca-167fad4d487c.gif)

### Description

When I minimize Github's window by clicking on minimize button the tooltip stays on my screen.

Obs: I tried on 1.0.3 too.

### Version

**GitHub Desktop version:** 1.0.2

**OS version:** Windows 10

### Steps to Reproduce

1. Minimize screen by button
1. [Second step]
1. [and so on]

**Expected behavior:** Hide the tooltip when I minimize the window.

**Actual behavior:** Tooltip stay on screen.

**Reproduces how often:** 85%

**Comment by j-f1** [comment]
Thanks for reporting this!

We’ve seen this a lot recently, and fixing the issue directly is out of our hands. What do the maintainers think about 🔥ing the tooltips on the close/minimize/maximize buttons?

**Comment by JakubSteplowski** [comment]
I've always have this problem, since the first version I tried (v0.7.1) to the latest (v1.0.3).
It's very annoying.

Please fix this, thanks! :)

**Comment by shiftkey** [comment]
@aayandre @JakubSteplowski you can follow along with the upstream issue https://github.com/electron/electron/issues/9943 which links off to the Chromium bug that goes into some more detail.

> What do the maintainers think about 🔥ing the tooltips on the close/minimize/maximize buttons?

Speaking for myself here, I'm not sure it's worth removing them completely. Here's my thinking:

 - these tooltips are a common feature of Windows apps, and we might get subsequent reports about the lack of tooltips
 - the impact of this is relatively minor (yes, it's a nuisance, but it doesn't affect data)
 - it can be worked around (restore the window to gain control of the tooltip again)

**Comment by JakubSteplowski** [comment]
Another workaround is to minimize the window by clicking directly at the icon on the taskbar, but of course it's not very handy.

**Comment by shiftkey** [comment]
@aayandre @j-f1 @JakubSteplowski anyway, we've got an eye on this issue anyway and we're making noise about it upstream to indicate that it's affecting our users. Thanks for the report!
