### ISSUE TITLE
.gitignore has no effect

### ISSUE THREAD

**Issue by mmxbass** [desktop/desktop#2923]
### Description

.gitignore and right-clicking and selecting "ignore" has absolutely no effect whatsoever on the operation of the program.

### Version

**GitHub Desktop version:** 1.0.3

**OS version:** macOS Sierra 10.12.6

### Steps to Reproduce

1. Right click on file and select "ignore"

**Expected behavior:** File is ignored

**Actual behavior:** File is recognized

**Reproduces how often:** Always

**Comment by shiftkey** [comment]
@mmxbass I think this is related to the fact the file is already tracked by Git when you are trying to ignore it. If that's the case, I've talked a bit more about the options to resolve this here: https://github.com/desktop/desktop/issues/2537#issuecomment-324494447

**Comment by brentjcampbell** [comment]
Exactly the same thing is happening to me, but only with a single UserInterfaceState.xcuserstate file. Every time Xcode opens, git tracks my local changes, and gitignore does nothing.

Desktop version: 1.0.3
OS version: macOS High Sierra 10.13

**Steps to Reproduce:**

Right click on file and select "ignore"
Expected behavior: File is ignored
Actual behavior: File is recognized
Reproduces how often: Always

Same as in the other thread, the file was tracked and committed before the entry in .gitignore was created.

Wildcard expressions don't seem to work either...

**Comment by shiftkey** [comment]
@brentjcampbell as a workaround, you can remove the file with a `git rm [path]` (or delete the file) and commit that change. Then your `.gitignore` rule will be applied correctly when the file exists on disk again.

**Comment by brentjcampbell** [comment]
Cool, thx

**Comment by mmxbass** [comment]
This workaround is, unfortunately, unacceptable for my purposes:

1: The code in the repo must build as-is.
2: Source includes shouldn't be changed (including the one for the empty file), the order and location of includes is EXTREMELY important in this project, as code & data cannot cross 32k boundaries (it's a puzzle) and there is utterly no automation or optimization available. This CANNOT be messed with.
3: The empty file exists entirely for the purpose of people having a place to work on local changes. It gets loaded into a specific location in the program file that is preallocated for it.

From the sound of it, this isn't a "bug" so much as git just not having the necessary maturity to meet my needs.

**Comment by gabessdsp** [comment]
Any update on when this will have some sort of automated resolution?

**Comment by mvandermade** [comment]
Would it be a good suggestion that the GitHub desktop application can throw a notice when you right-click "add to .gitignore" when doing this ?

**Comment by ssucur** [comment]
It would be great if we could edit git from the desktop app, to remove the tracked files. I don't know where to find that file to edit it manually in some way. Guess I'm left with using the command line version for odds and ends that are not yet integrated into the desktop app, like this and cherry picking.

**Comment by Guasco** [comment]
This problem remains even after three Mezzoic eras.
