### ISSUE TITLE
Add ability to group select changed files to commit

### ISSUE THREAD

**Issue by onury** [desktop/desktop#2924]
### Description

When selecting files to commit, it would make it incredibly easy if shift-clicking a check-box auto-selected all in-between. 

#### Example:
you have 100 changed files. In the check-list you want to commit only some of them, say between 30 and 70. So you first click the 30th checkbox and hold down the shift key and click 70th and boom! all in-between are auto-selected — instead of selecting one by one.

Life is short!

### Version

**GitHub Desktop version:** 1.0.1

**OS version:** macOS High Sierra

**Comment by shiftkey** [comment]
@onury thanks for the report! We're already tracking this in #2439, so please follow along with that issue...
