### ISSUE TITLE
Feature Request: Pull from a Remote Repo

### ISSUE THREAD

**Issue by WilliamABradley** [desktop/desktop#2925]
It would be great to have the ability to pull from other remotes than Origin in the GitHub Desktop App, currently there is a Public Repo that I am working on (Remote MS is Microsoft/UWPCommunityToolkit), and I have my own Fork of the Repo as Origin.

Currently there is no way I can see in the GitHub Desktop app to Pull remote, so I have to go to Console and enter `git pull MS`. This would be really handy if it could be done from inside the Desktop app, so it updates the Remote Branches. If we had a `Pull Remote..` option in the Repository drop down that let us pick a Remote to Pull from would be great.

On top of that, it would be nice to be able to add more remotes inside of Repository Settings.

**Comment by joshaber** [comment]
Hi @WilliamABradley 👋 We broadly agree! We're planning to add some niceties around fetching a fork's upstream in https://github.com/desktop/desktop/issues/2364. Feel free to follow along there!
