### ISSUE TITLE
how to add the new version githubdesk external  editor atom?

### ISSUE THREAD

**Issue by yszf** [desktop/desktop#2926]
## I have installed githubdesk 1.0.3 and atom 1.20.1.And I want use githubdesk open file in the atom,but always failed.
![default](https://user-images.githubusercontent.com/31989693/31045316-92fb0e98-a613-11e7-9464-2ce11fcc9129.png)
![default](https://user-images.githubusercontent.com/31989693/31045314-7881b3b4-a613-11e7-9d46-51eec7cb2cd3.png)

**Comment by shiftkey** [comment]
@yszf can you open a PowerShell prompt, run these commands and attach the output:

```
> Get-Item HKCU:\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\atom
> $env:PATH
> gci dir $env:LOCALAPPDATA\\atom\\bin
```

I suspect something is off with the installation, and these are the things that Desktop will check to ensure it can find your Atom installation.

**Comment by yszf** [comment]
Thanks!The following is the runing result.How do I solve the problem.

![default](https://user-images.githubusercontent.com/31989693/31208744-8fd49406-a9b9-11e7-84cd-ceece129ec01.png)

**Comment by shiftkey** [comment]
@yszf it looks like Atom didn't install the shim to `%LOCALAPPDATA%\atom\bin` that we need to launch Atom correctly.

An earlier report of this in https://github.com/desktop/desktop/issues/2585#issuecomment-326901330 pointed to this being a known issue with Atom https://github.com/atom/atom/issues/11450 and to try this workaround:

> You can try running `atom --squirrel-updated` from within the `%LOCALAPPDATA%\atom` folder. This should create the bin folder.

After that Desktop should detect Atom just fine.

I'm going to close this out, but please reply if you still encounter issues.
