### ISSUE TITLE
mouse over notification of minimize window button stays visible

### ISSUE THREAD

**Issue by sthag** [desktop/desktop#2940]
### Description

Hi there,

I'm on Windows 10 64bit and using GitHub Desktop .
If I click the minimize window button in the top right of the window the belonging minimize hover text field stays visible on the desktop.
It happens if the hover field had not showed itself before clicking. That is most of the time because clicking there usually happens quite fast.
After the windows is minimized to the taskbar the small field stays on desktop in front of every other opened window.
It can be hidden by opening the GitHub Desktop window again.
Minimizing by clicking on the taskbar icon prevents the bug.

### Version

**GitHub Desktop version:** 1.0.3

**OS version:** Microsoft Windows [Version 10.0.15063] 64bit

### Steps to Reproduce

1. Open GitHub Desktop
1. Move over and click on minimize window button before hover field is displayed

**Expected behavior:** hover field closes/disappears after window is minimized

**Actual behavior:** hover field stays open above every other window

**Reproduces how often:** Everytime

Greetings,
Stephan

**Comment by niik** [comment]
Thanks for the report, @sthag!

It looks like this is a bug in Electron, the framework on which the app is built. It looks like they're already tracking it in electron/electron#9943, so I'm gonna close this one.
