### ISSUE TITLE
Unable to chance my Settings in the Options window Advanced tab

### ISSUE THREAD

**Issue by petercr** [desktop/desktop#2945]
### Unable to change either the External editor or Shell from the Options menu

When I open the options menu either by clicking its link on the File menu or by pressing `Ctrl + ,` I am unable to save any of the changes that I make there. I am able to choose between the External Editor and the Shell dropdown's. But after I click the `SAVE` button nothing happens. The options window does not close, and does not save any changes made to it. 

### Version

**GitHub Desktop version:** 1.0.3

**OS version:** Microsoft Windows Version 10.0.15063

### Steps to Reproduce

1. Open GitHub desktop
2. Open options menu by pressing `Ctrl + ,`
3. Click the Advanced tab
4. Change either the External Editor or the Shell program by selecting a new one from the drop-down menu.
5. Click the `SAVE` button 

![2017-10-02](https://user-images.githubusercontent.com/26460352/31095264-3fc41f52-a786-11e7-8836-704c99297f26.png)

**Expected behavior:** Expected to save changes and close the options window

**Actual behavior:** Nothing happens when you click the `SAVE` button

**Reproduces how often:** Every time I open GitHub desktop and try to change either setting in the Advanced tab of the options menu. 

### Logs

The only `.log` file I could find in the folder
[SquirrelSetup.log](https://github.com/desktop/desktop/files/1350111/SquirrelSetup.log)

**Comment by j-f1** [comment]
Can you open the console (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>, then switch to the “Console” tab), try clicking the save button again, and report any errors that show up there?

**Comment by petercr** [comment]
Yes here are the 2 errors which show up when I try to change the type of Editor or Shell. Both look to be related to the `git config` settings. 
**Error 1.** 

```git config --global user.name Peter` exited with an unexpected code: 5.
warning: user.name has multiple values
error: cannot overwrite multiple values with a single value
       Use a regexp, --add or --replace-all to change user.name. ```

I have included both the `.log` files for the errors. I will try to resolve the **git** issue myself. 


![image](https://user-images.githubusercontent.com/26460352/31106842-4dae512e-a7bc-11e7-8eaf-730df1458d32.png)

[-1506996155034.log](https://github.com/desktop/desktop/files/1350928/-1506996155034.log)
[-1506996174896.log](https://github.com/desktop/desktop/files/1350929/-1506996174896.log)

**Comment by shiftkey** [comment]
@petercr thanks for the details from the Developer tools!

To confirm the state of your configuration files, could you click the **Repository** menu, select **Open in Command Prompt**, run this command and attach the output to this issue. This will help me provide a workaround and recreate the issue correctly on my end, so we can handle it properly in an update:

```
> git config -l --show-origin
```

**Comment by ikbalarcha** [comment]
How about this

**Comment by petercr** [comment]
@shiftkey Here are the results of running the command  `git config -l --show-origin` from Git Bash. I have also included a screenshot below of running the same command after opening the command prompt `Ctrl + ,` they appear to be the same.

```
$ git config -l --show-origin
file:"C:\\ProgramData/Git/config"       core.symlinks=false
file:"C:\\ProgramData/Git/config"       core.autocrlf=true
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:"C:\\Web Projects\\Git\\mingw64/etc/gitconfig"     http.sslcainfo=C:/Web Projects/Git/                                                                   mingw64/ssl/certs/ca-bundle.crt
file:"C:\\Web Projects\\Git\\mingw64/etc/gitconfig"     http.sslbackend=openssl
file:"C:\\Web Projects\\Git\\mingw64/etc/gitconfig"     diff.astextplain.textconv=astextpla                                                                   in
file:"C:\\Web Projects\\Git\\mingw64/etc/gitconfig"     filter.lfs.clean=git-lfs clean -- %                                                                   f
file:"C:\\Web Projects\\Git\\mingw64/etc/gitconfig"     filter.lfs.smudge=git-lfs smudge --                                                                    %f
file:"C:\\Web Projects\\Git\\mingw64/etc/gitconfig"     filter.lfs.required=true
file:"C:\\Web Projects\\Git\\mingw64/etc/gitconfig"     filter.lfs.process=git-lfs filter-p                                                                   rocess
file:"C:\\Web Projects\\Git\\mingw64/etc/gitconfig"     credential.helper=manager
file:C:/Users/Cruckshank/.gitconfig     filter.lfs.process=git-lfs filter-process
file:C:/Users/Cruckshank/.gitconfig     filter.lfs.required=true
file:C:/Users/Cruckshank/.gitconfig     filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/Cruckshank/.gitconfig     filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/Cruckshank/.gitconfig     user.name=petercr
file:C:/Users/Cruckshank/.gitconfig     user.email=petecruckshank@gmail.com
file:C:/Users/Cruckshank/.gitconfig     user.name=Peter
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.symlinks=false
file:.git/config        core.ignorecase=true
file:.git/config        submodule.active=.
file:.git/config        remote.origin.url=https://github.com/petercr/Wikipedia-Viewer.git
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.master.remote=origin
file:.git/config        branch.master.merge=refs/heads/master
file:.git/config        branch.master.atomprurl=https://github.com/petercr/Wikipedia-Viewer                                                                   .git
```
![2017-10-03](https://user-images.githubusercontent.com/26460352/31152191-08e53078-a869-11e7-8ea6-1fa4d3a22dd5.png)

**Comment by shiftkey** [comment]
@petercr cool, thanks! This is the problem:

```
file:C:/Users/Cruckshank/.gitconfig     user.name=petercr
...
file:C:/Users/Cruckshank/.gitconfig     user.name=Peter
```

While I wait for #2951 you can workaround this issue by removing either one of those values from that file. After that you'll be able to save settings again.

**Comment by petercr** [comment]
@shiftkey Great now that I have resolved the `user.name` issue I am able to change the editor and the shell programs, and save the changes. However, when I switch the shell to Git Bash and tell GitHub Desktop to open it, nothing happens. I checked the inspector for any errors, but there were none. Although this might be another issue 😄

**Comment by shiftkey** [comment]
@petercr please open a new issue if you'd like us to investigate that problem. There's other details like which version of Git for Windows you're running that will help with troubleshooting the issue.
