### ISSUE TITLE
Issue with file preview of large files

### ISSUE THREAD

**Issue by ChristinKalinaFunrock** [desktop/desktop#2955]
### Description

Hello,

I am enjoying to work with Github desktop a lot and I think it is a nice lean alternative to other git clients out there.
I only have one problem: Since a recent update the App needs a loooooooong time opening up as the first file that it finds in the change list is a large binary file (to be precise it is a unity scene). Unfortunately, this makes Github Desktop unusable for me. 
I did not find an option to work around this issue like not showing the change preview for large files or something like this.

Best, 
Christin Kalina

### Version

**GitHub Desktop version:** 1.0.3

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Have a large binary file in your change list (first item in change list)
2. Open the Github Desktop app

**Expected behavior:** GitHub desktop opens up and is ready to be interacted with

**Actual behavior:** GitHub desktop takes ages to show the changes in the large binary file and is not handling input until it loaded the changes.

**Reproduces how often:** Everytime

**Comment by niik** [comment]
Hey @ChristinKalinaFunrock, could you share some more details about the file contents? How large is it and is it truly binary? What does `git diff THATLARGEFILE` do?

**Comment by ChristinKalinaFunrock** [comment]
The file size is 27625 KB and I guess it is not truly binary, as it compares the file text based.

From Unity documentation:
> By default Unity will save scenes and prefabs as binary files. But there is an option to force Unity to save scenes as YAML text based files instead.

**Comment by niik** [comment]
@ChristinKalinaFunrock, excellent, thank you so much for that information. I'm classifying this as a general performance problem with diff rendering of large files. Our current proposed workaround is being discussed over in https://github.com/desktop/desktop/issues/2596 so I'd welcome you to subscribe to that and follow along.
