### ISSUE TITLE
Future Proposal - Brach Tree

### ISSUE THREAD

**Issue by greywolf-luismatos** [desktop/desktop#2958]
Can you add a Brach Tree window like the one from the older version?
![github-for-mac_584497_full](https://user-images.githubusercontent.com/32456727/31173907-56cd37f2-a901-11e7-9655-b27ac6923937.jpg)

**Comment by niik** [comment]
Thanks for the suggestion @greywolf-luismatos!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

Please follow along in https://github.com/desktop/desktop/issues/1634 for any updates to this.
