### ISSUE TITLE
Installation error... now what?

### ISSUE THREAD

**Issue by jeffbaldwin123** [desktop/desktop#2959]
### Description

I am brand new to GitHub. I am running Version 1.0.3. When I installed this on Windows I received the attached error during installation. What do I do now?
![10-4-2017 7-31-56 am](https://user-images.githubusercontent.com/24414988/31176523-be4d0656-a8d8-11e7-8df8-5bb5dd856afa.png)

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by niik** [comment]
hey @jeffbaldwin123, what version of Windows are you running on that machine and are you on a 64 bit or 32 bit system?

**Comment by jeffbaldwin123** [comment]
64 bit Windows 7 enterprise, Service Pack 1, security updates at least every month by our company security team

**Comment by shiftkey** [comment]
Not familiar with this one, but some additional reading that might help:

 - A similar issue reported against VS Code with no clear resolution: https://github.com/Microsoft/vscode/issues/25577
 - An SO thread that digs into whether an unexpected version of `COMCTL32.dll` might be to blame: https://stackoverflow.com/questions/37016803/calling-taskdialogindirect-loader-says-ordinal-345-not-found

**Comment by shiftkey** [comment]
@jeffbaldwin123 could you open a PowerShell prompt and attach the outputs from each of these commands? This will help me understand more about your setup:

`> gci -Path C:\ -Filter comctl32.dll -Recurse -ErrorAction SilentlyContinue -Force | % { $_.FullName }`

This command will list all instances of `comctl32.dll` on disk - these should be under `C:\Windows`.

`> gci -Path C:\ -Filter comctl32.dll -Recurse -ErrorAction SilentlyContinue -Force | % {$_.versioninfo } | Format-Table ProductVersion, FileVersion, FileName -AutoSize`

This will display the versions of each of those files.

**Comment by joshaber** [comment]
Thank you for your issue!

We haven't gotten a response to our questions above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
