### ISSUE TITLE
GitHub randomly automatically launches with a "add local repository" pop-up

### ISSUE THREAD

**Issue by cliv3dev** [desktop/desktop#2961]
### Description

[Description of the issue]
When Github is running or when it is closed, it randomly shows a "add local repository" pop-up.
Local path is filled with : {current repository}\--credentials.
It shows a warning below saying "This directory does not appear to be a Git repository. Would you like to create a repository here instead ?
Two buttons are in the pop-up: "create repository" and "cancel" 

### Version

**GitHub Desktop version:** 1.0.3

**OS version:** Microsoft Windows [version 10.0.16299.0]

### Steps to Reproduce

1. Open GitHub, select any repository, wait for 1 or 2 minutes (or the automatic fetch origin task?)
2. Close GitHub, and wait 1 or 2 minutes.

issue seems to be independent from the repository selected. It did the issue with 

**Expected behavior:** Should not display this pop-up

**Actual behavior:** [What actually happened]

**Reproduces how often:** Many times per day

**Comment by shiftkey** [comment]
@cliv3dev this is the same issues as #2962 - let's move the discussion over there
