### ISSUE TITLE
'Delete Branch' warns that branch already exists on remote after it's deleted

### ISSUE THREAD

**Issue by mrseanbaines** [desktop/desktop#2964]
### Description

When I click on **Branch > Delete...**, I get a popup dialogue saying *"The branch also exists on the remote, do you wish to delete it there as well?"*. This is a useful message, but it always seems to say that, even after I have deleted the branch in GitHub after I merge. I have also tried switching to master and Fetching Origin first and trying again, but I am still getting the same message.

### Version

**GitHub Desktop version:** 1.0.3

**OS version:** 10.12.6

### Steps to Reproduce

1. Create branch in GitHub Desktop
1. Publish branch to GitHub
1. Delete branch in GitHub
1. Click to delete branch in Github Desktop

![image](https://user-images.githubusercontent.com/24367010/31200027-37891afa-a951-11e7-8923-12f8c2715ea5.png)

**Expected behavior:** I expected the branch to be deleted on the remote and thus not be notified otherwise.

**Actual behavior:** I was informed that the branch still exists on the remote, even after having deleted the branch.

**Reproduces how often:** 100%

### Logs

[2017-10-04.desktop.production.log](https://github.com/desktop/desktop/files/1357381/2017-10-04.desktop.production.log)

**Comment by shiftkey** [comment]
We talked about this from an earlier report in #2543, and it comes down to not having done a fetch in the app (in the background or otherwise) that detects the PR branch was merged. 

We talked about a couple of options out of this:

 - "why not force a fetch when deleting?" - this might be more expensive, but maybe we can do a `git fetch origin [branch]` to just check this ref?
 -  "it'd be nice to get push notifications to the app" - we don't currently have the infrastructure to support this, but it'd be hella cool to pull this off

**Comment by tunggerrelease** [comment]
[2017-10-04.desktop.production.log](https://github.com/desktop/desktop/files/1360411/2017-10-04.desktop.production.log)

**Comment by shiftkey** [comment]
So this is the work to check if the branch exists on the remote:

https://github.com/desktop/desktop/blob/c23b1ae24cd82233e4b0cb3503f8fc621cb370d5/app/src/lib/git/branch.ts#L88-L100

If someone wants to pick this up, they could look to making that reusable, so we can check when displaying the form whether the remote exists. That would bypass the need to do a fetch, but still incurs the network penalty.

**Comment by adamreisnz** [comment]
I ran into this as well, and unless I misunderstand, I don't think it's due to a lack of a fetch. I've just seen a fetch happen, and then I went on to clean some branches that had been deleted from the remote previously, and the same checkbox appeared.

**Comment by shiftkey** [comment]
@adamreisnz I _think_ this is because the tracking info still exists on the local branch, which we incorrectly trust when rendering this dialog.

**Comment by JordanMussi** [comment]
Fixed in #3469 😃
