### ISSUE TITLE
How to download old version of Github Desktop binary files?

### ISSUE THREAD

**Issue by ijesonchen** [desktop/desktop#2965]
### Description

I wanna old binary release of github desktop for windows x64. How to download it?
For example, I wanna download 0.0.33, where could I find it?

### Version

**GitHub Desktop version:** [1.0.3]

**OS version:** [Win10 pro 15063.608]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by shiftkey** [comment]
> For example, I wanna download 0.0.33, where could I find it?

That's a _really_ old version. Why are you interested in that?

**Comment by ijesonchen** [comment]
Because I'm not used to the new version, the new style. And the last version I used _maybe_ 0.0.33 (I reinstalled my OS, and lost the old setup file, I'm not sure about the version). 
I develop on win10 pro with visual studio 2015, and I'm really not used to the new version. I reported  some issue like #2691, #2692, and it seem that you changed the feature and some function will not support. 
So I wanna rollback and try some old version.
I tried to compile with the source, both 0.0.33 and the newest version, but failed.
So is there any way to download the old binary release?

**Comment by niik** [comment]
@ijesonchen is it possible that you're talking about the old GitHub Desktop, the one we call classic? It would have looked something like this

![](https://cloud.githubusercontent.com/assets/1024672/9217916/3c5f7d74-4082-11e5-856c-133cae8d342e.png)

That version is no longer supported and will not receive any updates. We can't make any guarantees as to how long it'll continue to work nor for how long the installer will be available but for now you can download it at https://github-windows.s3.amazonaws.com/GitHubSetup.exe.

**Comment by ijesonchen** [comment]
Yes, that's exactly what I want. Thank you very much.
I noticed it's an online setup program. Is there any way I can got a offline setup program so I can have it after os reinstalled?

**Comment by nathanpitman** [comment]
I'm looking for the old Github Desktop too because new Github Desktop does not support simple features such as 'Discard all changes'... any idea where I can grab the Mac version?

**Comment by j-f1** [comment]
@nathanpitman To discard all changes, you can right-click the “X Files Changed” header.

**Comment by nathanpitman** [comment]
Ah brill! Thanks.

**Comment by richlip** [comment]
Hello, 
is there any way to get a full download, not only an installer for 0.0.33? i used the old version before my PC at work got a new setup, so i installed the new version of github and got no possibility to upload my changes because of self certificate problems.

With the old version, i found here (thank you!) it works like a charme...

**Comment by joshaber** [comment]
I _believe_ (someone else feel free to correct me!) that the classic Windows app only had an installer.

**Comment by niik** [comment]
@joshaber That's correct. We were trialing an offline installer but it was never fully tested and ready for widespread use

**Comment by romanfedyshyn** [comment]
@niik and it's no way for build old-classic version on mac?

**Comment by TheJaredWilcurt** [comment]
Was looking for the classic. With every major change this software just get worse and worse in the UX department. Hopefully I can squat on "Classic" indefinitely.

**Comment by leechunhoe** [comment]
Regret the update. I cannot even do branch merging as I want.

**Comment by ryh** [comment]
The `classic` version for macOS:
https://central.github.com/mac/latest
302 to
https://github-central.s3.amazonaws.com/mac/GitHub%20Desktop%20223.zip

**Comment by j-f1** [comment]
@dmitriz Any reason you can’t update to 10.9?

**Comment by izbor** [comment]
I was using Github Desktop for many years. New version (build with Electron?) is slow and has a stupid interface (for example same name projects in different folders and different github repos are shown with the same name).  Why they made it worse? Electron will never be better because it will never be as fast as native app. I was happy with old Github Destop thanks God  I didn't delete it when intsalled electron version.

**Comment by toxi22** [comment]
where you can download offline installer GitHub 3.3.6.1 for Windows x32 and x64?
It is working, wretched and installs automatically ssh-keys and installs GitShell automatically and automatically imports the key into the account on github.com

The new version does not automatically generate ssh certificates during installation and does not have built-in GitShell. All this must be installed separately.

**Comment by herbertmilhomme** [comment]
Is it possible to acquire the version before the latest github desktop classic?
Each time the program starts-up it immediately advertises the new github download, and even when having the newer one registered on the computer, the ad banner never stops and the "remind me later" doesnt seem to do anything to stop it. There's no "permanent" solution, except to downgrade a version before that feature was hardwired into the code. 

Other softwares that do that are similar to adobe acrobat (right after an alternate software is introduced, the final patch to the deprecated model is a permanent hard sale to upgrade, that never ends).

Also, unsupported feature new version does not offer/provide: when old version detected a `.sln` file, it would offer to open in "visual studio community", new version **only** opens "visual studio code", and solution files (as well as other benefits of VS) are not recognized or supported. (Cant work on a "project" as a _project_ only as _individual files_).

**Comment by TheJaredWilcurt** [comment]
I've started an open source project for a cross-platform git GUI. Its design is a combination of the best aspects of several different git GUI's, including the pre-electron version of GitHub for Desktop.

It's very early on (just started it), and will likely be quite a while before a beta release is available, but thought I would mention it here for those interested:

* https://github.com/TheJaredWilcurt/karngdarbo
