### ISSUE TITLE
i cant see my web site

### ISSUE THREAD

**Issue by louiss0** [desktop/desktop#2967]
wha

### Description
I cant find my website any where whats wrong
[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by louiss0** [comment]
I cant go on the site I createdhttp://www.sheltonlouis.github.io/

**Comment by shiftkey** [comment]
@louiss0 this is the issue tracker for the GitHub Desktop project.

Please look over the [GitHub Pages](https://help.github.com/categories/github-pages-basics/) documentation as that might help troubleshoot your issue.
