### ISSUE TITLE
Better user message for the Command Line tool installation?

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2971]
If you back out of the Command Line tool installation by canceling or failing to verify the GitHub Desktop Helper, then an install error message is surfaced saying the installation failed. 

Perhaps we could make this error more user friendly or just not surface it if there is no lingering effect? Seeing the message for the first time made me question if I need to do something to resolve the error. 🤔 

<img width="479" alt="screen shot 2017-10-05 at 11 16 41" src="https://user-images.githubusercontent.com/14828183/31222412-ea8aad72-a9be-11e7-93cd-f548483b4fe5.png">
<img width="804" alt="screen shot 2017-10-05 at 11 14 06" src="https://user-images.githubusercontent.com/14828183/31222411-ea891692-a9be-11e7-9d5e-565ed7123c8d.png">

tested in 1.0.4-beta0, mac

**Comment by shiftkey** [comment]
This one is some low-hanging fruit if someone would like to get involved:

- [This is the handled error, which we pass up to the error handling](https://github.com/desktop/desktop/blob/master/app/src/lib/dispatcher/dispatcher.ts#L949-L951).

 - And [this is the logic for creating the symlinks](https://github.com/desktop/desktop/blob/master/app/src/ui/lib/install-cli.ts).

@tierninho what information do you think is helpful here to surface?

**Comment by tierninho** [comment]
Just reassurance to the user about what action (or non-action) is next. 

Maybe "Failed to remove file at/usr/local/bin/GitHub. Authorization of GitHub Desktop Helper is required."
