### ISSUE TITLE
improve our Gists experience

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#2973]
The original PR to fix #2886 has uncovered a bunch of headaches around how we handle Gists.  I'm going to use this issue to track the various parts of the app that need changes to make it better and break these down into tasks once we've figured out what needs to be done, and it's priority.

The items listed here fall into three different buckets:

 - bugs that interfere with the experience
 - polish to make Gists integrate better into the app
 - features to enhance the overall Gists experience

Bugs should be a priority - we don't want to prevent people using repositories in this way. The other stuff might come down the track, based on our roadmap or interested external contributors.

**If you're interested in this feature, please add your reaction here so we can gauge interest.**

### Cloning

**Feature**: We don't have a way to let users clone their repositories down. This is being tracked in #2953 

**Bug**:  the current "Clone in Desktop" experience doesn't recognise the Gist URL, and displays a confusing message about the folder existing. This was reported in #2886.

### Repository Listing

**Polish**: If you add an existing gist repository to the app, there's no real way to see that it's a Gist - you'll just get the folder name which isn't really user-friendly. And it's also grouped under "Other"

![](https://user-images.githubusercontent.com/359239/31259652-1c01d904-aa94-11e7-8493-f8772b5729d8.png)

For reference, the header to a Gist listing looks like this:

![](https://user-images.githubusercontent.com/359239/31259647-0be13614-aa94-11e7-9f12-6b218a8b2155.png)

So even for a gist containing multiple folders, it will show a filename in the header and use the description as secondary information. Not sure how to make this fit with how we're displaying repositories in the list.

### Push/Pull

**Bug**: when trying to push commits to a gist, it will fall back to the basic authentication. We should detect the `gist.github.com` domain and provide the existing credentials (if found)

### TODO

I need to go back and revisit the domain that GitHub Enterprise sets for where gists are hosted - whether it's a subdomain like `gist.company.com` or `company.com/gist/`, or how to detect this as part of probing the GHE setup. This will likely affect other how we address other things, so let's dig into that first.

cc @desktop/core for any additional thoughts or input

**Comment by shiftkey** [comment]
This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by steveward** [comment]
In #7411 @Phil-Factor ran into the push/pull bug that causes authentication to fail when attempting to push a Gist.

**Comment by billygriffin** [comment]
From @seamusdemora in #9200 

#### Problem 
I have a collection of gists on https://gist.github.com/seamusdemora. I created all of these gists some time ago using the online editor through a browser. I would now like to collect all of these gists, and save them to a local folder on my Mac - just as I do for my other content/repos on GitHub.

However, there seems to be no clean way to do this. I cannot find a way to clone all of my gists at once to a single folder. When I try to clone a single gist, Desktop App insists on having a new/empty directory for each gist! It's as if GitHub's declaration that "each gist is a repo" has suspended common sense from the process of managing them.

Surely, there must be a way to house multiple gists in a single folder, and manage them from the Desktop App just as we do other multi-file repositories?

#### How will it benefit Desktop and its users? :

IMHO, treating multiple gists (which are typically single files) as a single repository would make things intuitive and consistent with how other repos are treated. Managing under the present scheme, which would seem to require creating 100 repos to house 100 gists is confusing and inconsistent. GitHub's site collects all of a user's gists under a single hierarchy in a fashion very similar to the way that a REPO is displayed. Creating 100 repos for 100 individual gists makes navigation & location in Desktop App awkward and time consuming.

**Comment by mbierman** [comment]
Three years? Has this issue been forgotten? My main purpose in raising it is actually to be able to edit the history of a gist if say, private information is accidentally included. 

I’d be happy enough if that were addressed directly I suppose.

**Comment by seamusdemora** [comment]
@mbierman 👍  Yes - this is discouraging... this thread should be titled "Promises and Excuses".

**Comment by steveward** [comment]
Gist push bug reported again in https://github.com/desktop/desktop/issues/13274.

**Comment by steveharoz** [comment]
A four year old issue? Ouch. Is there any plan to fix compatibility with gists? Forget polish, please make it work at all without asking people to use the command line, which requires new software to be installed.

**Comment by RollingHog** [comment]
Same request here. Just ran in this, it is OUCH indeed.

**Comment by Jenni001q3** [comment]
Ph yeah

**Comment by steveward** [comment]
Reported in https://github.com/desktop/desktop/issues/15360.

**Comment by CTimmerman** [comment]
> Reported in #15360.

https://github.com/desktop/desktop/pull/15361 would have solved my issue without exposing this glaring 5-yo bug.

**Comment by steveward** [comment]
From https://github.com/desktop/desktop/issues/16862:

> Expected: "View on GitHub" menu item is enabled and triggering it opens the Gist page for a GitHub Gist repo.
> 
> Actual: "View on GitHub" menu item is disabled and there is no way to trigger it.

**Comment by tedmiston** [comment]
What a joke that 1 of the 2 types of repos on GitHub blatantly breaks in GitHub's own git client and the response is to just immediately close as "wontfix".

What is the point of having an open source client in the first place if you're just going to ignore your users and not actually fix the simple bugs???

**Comment by tedmiston** [comment]
Almost 6 years of GitHub's GUI git client existing and trivial to fix bugs of it not working with GitHub's own backend just get ignored.

Of course you don't hear about this enough from users... what's the point in reporting bugs at all when you: (1) don't actually acknowledge or fix them, and (2) just immediately close them as "Completed" and *actually do* nothing.

Submitting the bug report was a complete waste of time.

Just turn the feature off if you're not going to actually fix your bugs.

**Comment by CTimmerman** [comment]
https://github.com/desktop/desktop/pull/15361/commits/ce7fcd9f4606cd1209f4eb0a4f3155052d46cbb0 helps, but before i unsub from this thread, these client have better UX imo:

1. [SmartGit](https://www.syntevo.com/smartgit/) - [SourceTree](https://www.sourcetreeapp.com/) but prettier and cross-platform. Not free for commerce.
1. SourceTree - Free, good overview. Compares commits in different branches. Only for Windows or Mac.
1. [GitAhead](https://gitahead.github.io/gitahead.com/) - Similar to SourceTree but also for Linux. Dark theme. Can't compare uncommited changes. Case-sensitive commit sort. Selected staged file diffs don't autoexpand. Unsupported.
1. [TortoiseGit](https://tortoisegit.org/) - Explorer shell integration.
1. [GitK](https://www.atlassian.com/git/tutorials/gitk) - Functional but ugly Tcl/Tk interface.
1. [GitG](https://wiki.gnome.org/Apps/Gitg/) - Cleaner and prettier GitK but doesn't autoexpand multi-file diffs.
1. [Guitar](https://github.com/soramimi/Guitar) - Cross-platform Git tree viewer that lacks arbitrary diffs that SourceTree shows. Prettier but harder to use than GitK.
1. [GitKraken](https://www.gitkraken.com/) - Looks over functionality. Hard to switch between commits.
1. [GitFiend](https://gitfiend.com/) - Like [GitKraken](https://www.gitkraken.com/) without the file tree.
1. [Git Gui](https://packages.debian.org/unstable/git-gui) - Ugly alternative to the command line. Launches [Git](https://gist.github.com/CTimmerman/907bff561864be3d79ff0b2a05ddcd15)K for history.
1. Git - Works offline.

**Comment by moritztim** [comment]
Shouldn't this be closed as "not planned"? It isn't completed...

**Comment by steveward** [comment]
As of v3.4.3 (see the PR in https://github.com/desktop/desktop/pull/19009) you can now push to gists using either a token generated from your GitHub account, or by enabling the Git Credential Manager (`Preferences` > `Advanced` > `Network and credential` > `Use Git Credential Manager`). This is necessary due to gists coming from the `gist.github.com` domain. Thanks to @tidy-dev for working on this!
