### ISSUE TITLE
Inform the user that changes were stashed when creating new branch

### ISSUE THREAD

**Issue by jdolan** [desktop/desktop#2982]
### Description

I had changes pending on a feature branch. The branch had been merged down to develop, so I wanted to move my pending changes over to a new branch, based off develop. I clicked the branch button, and asked it to branch from develop. It did, but it also reset my index, seemlingly losing all of my pending changes with no recourse.

After some digging, I found that it had stashed my changes before creating the new branch. Great news! Notifying the user that their changes were stashed would avoid some anxiety ;)

### Version

**GitHub Desktop version:** Hasty Things Done Hastily (223)
**OS version:** OS X 10.12.6 (16G29)

### Steps to Reproduce

1. Have pending changes on branch B, where branch A and B have a common ancestor.
1. Use Github Desktop to create branch C from branch A
1. Note that pending changes are gone, crap pants.

**Expected behavior:** Carry the changes over to the new branch, or at least notify the user that their changes were stashed.

**Actual behavior:** Pending changes were silently stashed.

**Reproduces how often:** 100%

**Comment by j-f1** [comment]
Thanks! It looks like this issue is with the Classic apps, but this repository is for issues with the redesigned GitHub Desktop (see https://desktop.github.com).

We’ve deprecated the classic apps and recommend you switch to the new one.

**Comment by jdolan** [comment]
Whoa, nice. Switched :)
