### ISSUE TITLE
Open in GitHub?

### ISSUE THREAD

**Issue by danqing** [desktop/desktop#2983]
This must have been filed before but I can't find it anywhere. I think the app should have an "Open in GitHub" button that opens the current repo in browser. The old app has a button that opens the current PR, which is good too.

Thanks!

**Comment by agisilaos** [comment]
Hey @danqing I think you already can do that? About your second question I'm not sure if that's in the works already. Maybe @shiftkey can give a bit more info on that.

<img width="461" alt="screen shot 2017-10-08 at 14 51 29" src="https://user-images.githubusercontent.com/10944108/31316544-3935ef38-ac38-11e7-9a05-feb38f3ed049.png">

**Comment by danqing** [comment]
Oh interesting. So here's another feature that's unfortunately hidden in the menu...

Now the request goes back to exposing more things in the UI :)

**Comment by agisilaos** [comment]
Back to your second comment, Interactions with PR's is under development. Hm, I don't think that's the right way to do it because a core feature of the app is to be simple regarding the UI. And that's one of the reasons that makes this app special. At least for me.

**Comment by danqing** [comment]
Well, I agree that we don't want a cluttered UI, but I think we also don't want a menubar app, which it surely looks like now - almost all features other than committing and syncing master are hidden in the top navbar.

I understand that switching to Electron means starting from scratch and it's reasonable to build up features gradually. I hope it's not an intentional design decision that things should be hidden in the menus.

**Comment by niik** [comment]
Looks like this was answered already so I'm gonna close it out!
