### ISSUE TITLE
Why is "cancel" the primary button in the delete branch dialog?

### ISSUE THREAD

**Issue by adamreisnz** [desktop/desktop#2988]
![image](https://user-images.githubusercontent.com/490562/31321693-197ed386-ace6-11e7-8a0b-c6ea6bc4f802.png)

This is very confusing, why is Cancel the primary button here?
I've clicked it by accident several times now when wanting to delete a branch.

Normally actions like "Cancel" or "Back" are the secondary buttons.

**Comment by shiftkey** [comment]
@adamreisnz if you're on macOS, the button order matters in some "destructive" situations. There's more details about this here https://github.com/desktop/desktop/issues/1311.

**Comment by adamreisnz** [comment]
Hmm, that still doesn't clarify really. In the example in that issue the order is switched, and "Cancel" is still the primary button:

![image](https://user-images.githubusercontent.com/490562/31322020-88ee4fc6-aceb-11e7-9596-53144de09ac9.png)

In both of these cases, "Cancel" should be the secondary (non-blue) button.

**Comment by joshaber** [comment]
@adamreisnz that's because that screenshot's from Windows. On Mac, `Cancel` is on the left:

<img width="428" alt="screen shot 2017-10-09 at 9 12 35 am" src="https://user-images.githubusercontent.com/13760/31339788-04550980-acd2-11e7-9e8b-b89d486acaa9.png">


`Cancel` is the default button in the case of destructive actions, as per the HIG:

>Alternatively, when a dialog may result in a destructive action, Cancel can be set as the default button.

**Comment by adamreisnz** [comment]
I still find this very confusing, not sure if I know of any other applications that work this way, whether on Mac or on Windows.

In our own software, when there are potentially very destructive operations, we just force the user through an additional check, like ticking a checkbox to confirm before they can hit the primary button.

I don't think users of Github desktop are computer users of the kind that will consciously click on Discard Changes but then blindly hit enter. Most of us (I think) know what we're doing.
