### ISSUE TITLE
Menu bar should display the signed in user's avatar, with access to 'Accounts' dialog.

### ISSUE THREAD

**Issue by rudifa** [desktop/desktop#2992]
### Description

Currently, **desktop** displays no clear indication of whether the user is signed in or not.
Also, the sign in/out 'Accounts' dialog is hidden under Preferences, which is not immediately obvious to a newcomer.

I suggest that **desktop** should emulate the github web interface and display at the r.h. end of the menu bar the user's avatar when signed in, and 'Sign in' invite otherwise. Clicking on these items should open the 'Accounts' dialog.

### Version

**GitHub Desktop version:** 1.0.3

**OS version:** OS X 10.11.6

### Steps to Reproduce

1. Start desktop 
1. Sign in if not already signed in

**Expected behavior:** An unmistakable indication that you are signed in, preferably the user's avatar in the menu bar

**Actual behavior:** No user avatar or other indication of successful sign in

**Reproduces how often:** 100%

#### Additional Information

See also remarks by @niik in the closed Issue #2980.

**Comment by OiYouYeahYou** [comment]
Help wanted?

**Comment by niik** [comment]
> Help wanted?

We're not ready to open this up for contributions as we don't have a clear and agreed-upon way forward. The issue body outlines one potential way but I'd like to go back and focus on the initial problem which is whether we could make it more clear that you're not signed in to any account. I'll leave my comment from the other thread here regarding this particular suggestion of adding avatars to the menu-/toolbar.

> This was something we had in the classic app on Windows a few years back but we removed it because the consensus at the time was that it didn't enough value to justify taking up such a prominent space in the app. It also added confusion when multiple accounts where in use (GitHub.com and GitHub Enterprise simultaneously) since the app isn't single-user like the website is.

**Comment by niik** [comment]
In order to avoid confusion and to keep our issue backlog manageable I'm going to label this future proposal and close it out for now. We'll revisit issues labeled future-proposal in our planning sessions.

**Comment by billygriffin** [comment]
I think I'd like to roll this into #610, which is focused more on *why* it's important whether you're signed in or not and around commit attribution, and therefore I'm going to remove `future-proposal` here. We'll make sure to consider this as we work toward how we make it more obvious the distinction between your Git info and your GitHub account.
