### ISSUE TITLE
Repos disappear and do not show after cloning

### ISSUE THREAD

**Issue by mKenfenheuer** [desktop/desktop#2997]
### Description

Somehow all my cloned repositories disappeared, and i am not able to clone repositories anymore. 
When i clone a repository, everything goes as expected until the repository is cloned successfully.
After that the folder and its content are being created but the repository is not visible in github desktop.

### Version
**GitHub Desktop version:** 1.03 (latest as of now)
**OS version:** Microsoft Windows 7 [Version 6.1.7601] 

### Steps to Reproduce

1. Download Github Desktop
2. Clone a repo
3. Start using Github Desktop
4. The repositories disappear
5. Clone another repo
6. After successful clone, still no repos visible

**Expected behavior:** Display all repositories

**Actual behavior:** Repositories not visible

**Reproduces how often:** ca. 25%

### Logs
[logs.zip](https://github.com/desktop/desktop/files/1371348/logs.zip)

**Comment by tierninho** [comment]
Looks like the repo is a non-Github repo, which is a current issue: https://github.com/desktop/desktop/issues/852

Core team will also chime in with more thoughts on your issue...

**Comment by mKenfenheuer** [comment]
Yeah after another reboot it's now showing me this:
![2017-10-10 15_33_16-github desktop](https://user-images.githubusercontent.com/26744396/31380891-64201fb8-add0-11e7-9ffa-6911c188f7f5.png)

I just installed the git command line tools to check and i am able to fetch, stage, commit and push:

C:\Users\kenfenheuerm\Documents\GitHub\bi-ausarbeitung>git fetch
C:\Users\kenfenheuerm\Documents\GitHub\bi-ausarbeitung>git add .
warning: LF will be replaced by CRLF in chapter/02_theorie.tex.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in chapter/03_praxis.tex.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in main.tex.
The file will have its original line endings in your working directory.
C:\Users\kenfenheuerm\Documents\GitHub\bi-ausarbeitung>git commit -m "Section 2 finished"
[master 864ca9a] Section 2 finished
 11 files changed, 65 insertions(+), 9 deletions(-)
 create mode 100644 pdf/Android-Apps auf Google Play.pdf
 create mode 100644 pdf/sudo - Debian Wiki.pdf
 create mode 100644 pdf/sudo.pdf
 create mode 100644 resources/Root-Request.webp
 create mode 100644 resources/permissions.png
 create mode 100644 resources/permissions.webp
 create mode 100644 resources/root_request.png
 create mode 100644 resources/top_5_antivir_android.png
C:\Users\kenfenheuerm\Documents\GitHub\bi-ausarbeitung>git push
Counting objects: 16, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (16/16), done.
Writing objects: 100% (16/16), 5.61 MiB | 271.00 KiB/s, done.
Total 16 (delta 4), reused 0 (delta 0)
To https://gitlab.mkenfenheuer.de/mKenfenheuer/bi-ausarbeitung.git
   d967050..864ca9a  master -> master

**Comment by joshaber** [comment]
It sounds like there are at least two problems happening:

1. Your repositories disappeared.
2. Cloning fails.

Let's try to address those separately. First off:

#### Repositories disappeared

How many repositories did you have added to the app? How did you add them? Did they just suddenly disappear or did something cause it?

#### Cloning fails

From your last message, it sounds like it worked, maybe? The logs make it look like authentication failed numerous times.

**Comment by mKenfenheuer** [comment]
### Repositories disappeared

I only had two repos added. Both went missing today morning when i opened github desktop. Yesterday they were still there.

### Cloning fails

Well the cloning does not completely fail. If i clone the repo, the cloning itself succedes but github desktop does not add the repo to the list and it is not visible in the gui.

Maybe the whole bug ist just that github desktop is not recognizing the local repository anymore and therefore removes the repo from the gui. This would also explain why github desktop clones the repo but does not add it to the gui.

**Comment by joshaber** [comment]
Well huh, that's baffling. What happens if you drag and drop a repository on to the app?

**Comment by mKenfenheuer** [comment]
That is actually working.. The repository is back!

**Comment by mKenfenheuer** [comment]
However cloning still does not work...
![2017-10-11 09_15_21-github desktop](https://user-images.githubusercontent.com/26744396/31421402-cfcd6718-ae64-11e7-8527-29c8065e9212.png)

It asks me to publish it to github

**Comment by joshaber** [comment]
🤔 that's really odd.

Let's see if they're still in the database.

1. Go up to the <kbd>View</kbd> menu and select <kbd>Toggle developer tools</kbd>
1. The developer tools should open.
1. Click on the <kbd>Application</kbd> tab.
1. Expand the disclosure arrow next to <kbd>IndexedDB</kbd>.
1. Expand the disclosure arrow next to <kbd>Database</kbd>.
1. Click on the <kdb>Repositories</kdb> row.
1. Take a screenshot and send it over to us.

**Comment by mKenfenheuer** [comment]
I am confused. Repos are back now and also show in the database.
I'll take a screenshot as soon as the problem reoccurs.

**Comment by shiftkey** [comment]
@mKenfenheuer the next update will have some additional diagnostics around this. Please report back if you encounter the issue again.

**Comment by mKenfenheuer** [comment]
Repo disappeared again. Screenshot of the database is attached.

Fyi: i removed all repos and only added the repo bi-ausarbeitung.

![2017-10-12 16_40_02-github desktop](https://user-images.githubusercontent.com/26744396/31493259-1202b928-af6c-11e7-9922-c653bdac98ae.png)

**Comment by joshaber** [comment]
@mKenfenheuer Thanks for taking that screenshot! So that is from after the repositories disappeared and you re-added `bi-ausarbeitung`?

**Comment by mKenfenheuer** [comment]
Yes and no. 

- First I removed all other repos (after gave the log files to you)
- Then i worked with github desktop
- The repo disappeared
- I took the screenshot and attached it to my previous post.

**Comment by joshaber** [comment]
@mKenfenheuer I'm sorry, I think I'm still not entirely understanding 😄 In the screenshot, you're in the `bi-ausarbeitung` repository, so that repository hasn't disappeared. Did other repositories disappear?

**Comment by mKenfenheuer** [comment]
Yeah sorry so the repo shown there is being displayed as a local only repo which should normally be a remote one. So instead of Publish to Github there should be Fetch origin or something like that. 

This time the repo did not completely disappear. So as for now, i can encounter two things:

- The repo completely disappears
- The repo shows as a local repo with the hint to "publish to github"

**Comment by joshaber** [comment]
Hmm, let's see what remote URL `bi-ausarbeitung` has.

Go to the <kbd>Repository</kbd> menu and select <kbd>Repository settings…</kbd>. Take a screenshot and paste it in here.

**Comment by joshaber** [comment]
Thank you for your issue!

We haven't gotten a response to our questions above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by tk185176** [comment]
Hi, is there a fix to this issue? I'm trying to clone a repo, it clones successfully but the repo disappears immediately. : (

**Comment by steveward** [comment]
@tk185176 can you open a new issue and fill out the template? Since this is an old closed issue that will be the best way we can assist you.
