### ISSUE TITLE
Truncate long repo names in panes and modals

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2998]
In the clone repo modal, we are not truncating long repo names with (...) as the modal width does not fit anything above approx 50 characters.

<img width="482" alt="screen shot 2017-10-10 at 12 52 42 pm" src="https://user-images.githubusercontent.com/14828183/31385357-e8c4b8fc-adba-11e7-96d9-0346b3cd7e8d.png">

tested 1.0.4-beta0, mac

**Comment by joshaber** [comment]
Ha, that's great 😆

**Comment by tierninho** [comment]
To whomever picks this up: Truncation should help keep the [username/repo_name] to one line, not two lines as seen in pic.

**Comment by tierninho** [comment]
Let's also toss this fix in there:

<img width="483" alt="screen shot 2017-10-11 at 10 47 42 am" src="https://user-images.githubusercontent.com/14828183/31433589-bb16fa02-ae71-11e7-9421-7ed4c363e224.png">

@desktop/design Wrap or truncate?

**Comment by niik** [comment]
> @desktop/design Wrap or truncate?

👍 Wrap

**Comment by donokuda** [comment]
> @desktop/design Wrap or truncate?

Also 👍 on wrapping 🎁 

> To whomever picks this up: Truncation should help keep the [username/repo_name] to one line, not two lines as seen in pic.

Also 👍 to truncation in the repo list. If we wanted long repo name to wrap, then we'll have to make sure the list cell heights can adjust based on its content. However, my understanding is that there's a little bit of extra work involved for that to happen.

**Comment by niik** [comment]
> Also 👍 to truncation in the repo list. If we wanted long repo name to wrap, then we'll have to make sure the list cell heights can adjust based on its content. However, my understanding is that there's a little bit of extra work involved for that to happen.

~60 characters ought to be enough for everyone - @niik

**Comment by j-f1** [comment]
> ~60 characters

Shouldn’t it truncate based on the list’s width?

**Comment by niik** [comment]
@j-f1 it should, I was aiming for humor by referencing an old apocryphal Bill Gates quote.

**Comment by joshaber** [comment]
The clone modal was fixed in https://github.com/desktop/desktop/pull/3598.

**Comment by agisilaos** [comment]
Since this issue has been fixed in #3598 we should close this issue, right? cc: @shiftkey

**Comment by shiftkey** [comment]
@agisilaos nice spot! As it's been so long ago I retested this to confirm it's been resolved.
