### ISSUE TITLE
UX feature request: show repo status in repo list 

### ISSUE THREAD

**Issue by olivermuc** [desktop/desktop#2999]
Just food for thought:

As I have to work on several repos simultaneously, it would **extremely** helpful to see a repo's status also in the repo list (left sidebar). 
It could be as simple as indicating the status by a flag, eg:
* **red** for new commits available and not synced
* **yellow** changes available 

Currently, I have to manually go through tens of repos to check if I need to sync them etc.

**Comment by joshaber** [comment]
Thanks @olivermuc! I'm gonna group this in with https://github.com/desktop/desktop/issues/2259. Please feel free to follow along over there!

**Comment by billygriffin** [comment]
This came out in the recent 1.3 release (PR here: https://github.com/desktop/desktop/pull/4770), hope it's helpful for you @olivermuc! I'm going to remove the labels since it's now out in the wild.
