### ISSUE TITLE
"Open this in GitHub Desktop" links fail

### ISSUE THREAD

**Issue by PabstMirror** [desktop/desktop#3006]
### Description

Clicking `open this in GitHub Desktop` on github throws error if branch has not been fetched first

### Version

**GitHub Desktop version:** 1.0.4-beta0

**OS version:** Microsoft Windows [Version 6.1.7601]

### Steps to Reproduce

1. Push branch/PR to repo
1. Click `You can also open this in GitHub Desktop` link from github PR
(e.g. `x-github-client://openRepo/https://github.com/acemod/ACE3?branch=test2`)

**Expected behavior:** Switch to new branch

**Actual behavior:** Error (pops up twice), No change in branch

![image](https://user-images.githubusercontent.com/9376747/31412384-78c9ed0e-adda-11e7-828b-061fc5806ed8.png)

**Reproduces how often:** Everytime (as long as it hasn't been fetched first)

### Logs
```
2017-10-10T21:44:02.573Z - info: [ui] launching: 1.0.4-beta0 (Windows 6.1.7601)
2017-10-10T21:44:02.875Z - error: [ui] `git checkout --progress test2 --` exited with an unexpected code: 128.
fatal: invalid reference: test2

2017-10-10T21:44:03.042Z - error: [ui] `git checkout --progress test2 --` exited with an unexpected code: 128.
fatal: invalid reference: test2

2017-10-10T21:44:03.867Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.173s)
```

#### Additional Information

Once the branch is fetched it works fine.
I think it might just need to `fetch` before the `checkout`?

**Comment by shiftkey** [comment]
@PabstMirror thanks for this report. We _are_ doing the fetching here as part of handling open pull requests, but I think the logic for this doesn't handle your case.

https://github.com/desktop/desktop/blob/5a638b712a0c88758a5e3b6c04860fa1565884b6/app/src/lib/dispatcher/dispatcher.ts#L885-L892

It's that second `if (branch) {` check that we'd need to do a fetch for, to handle any branches created externally.

Marking this as `help-wanted` if someone wants to take a swing at it while I deal with my outstanding tasks.

**Comment by AwesomeTech10** [comment]
I don't know how to fix this problem in the code, but you could go up to File > Clone Repository and fill in the repo details. Then just use the Current Branch to change branch (no tags).

Hope this helps for now!

**Comment by shiftkey** [comment]
I think this is an easy enough fix. Moving to 1.1.x.

**Comment by shiftkey** [comment]
This is probably a blunt way to fix this, if someone wants to refine it to fetch the default remote:

```diff
diff --git a/app/src/lib/dispatcher/dispatcher.ts b/app/src/lib/dispatcher/dispatcher.ts
index 9c822d8df..8a6b85785 100644
--- a/app/src/lib/dispatcher/dispatcher.ts
+++ b/app/src/lib/dispatcher/dispatcher.ts
@@ -911,7 +911,8 @@ export class Dispatcher {
       await this.fetchRefspec(repository, `pull/${pr}/head:${branch}`)
     }

-    if (branch) {
+    if (pr == null && branch) {
+      await this.fetch(repository, FetchType.BackgroundTask)
       await this.checkoutBranch(repository, branch)
     }
```
