### ISSUE TITLE
Support Typora as external editor

### ISSUE THREAD

**Issue by fenduru** [desktop/desktop#3015]
### Description

I'm trying to help our design team have a (non-technical) user-friendly experience for creating and updating pull requests for specifications. They author their specs in markdown using [Typora](https://typora.io) so it would be great if we could have an option for `Repository > Open in Typora`

### Version

**GitHub Desktop version:** 1.0.3

**Comment by j-f1** [comment]
Currently, GitHub Desktop only supports opening repositories in applications that can handle opening a folder. Can Typora open a folder?

**Comment by fenduru** [comment]
I've tested on Windows, and it does appear to support opening a folder from the command line - however it seems to not work if there is a trailing slash on the path.

```
# works
"C:\Program Files\Typora\Typora.exe" C:\Users\me\Documents\GitHub\project

# doesn't
"C:\Program Files\Typora\Typora.exe" C:\Users\me\Documents\GitHub\project\
```

**Comment by fenduru** [comment]
FWIW I'm happy to file a PR if someone can point me in the right direction

**Comment by shiftkey** [comment]
@fenduru we don't quite have a good story about platform-specific editors, but we probably should. I have a similar PR open #2941 which you should follow along with.

**Comment by j-f1** [comment]
@shiftkey It [looks](https://typora.io/#download) like it’s cross-platform.

**Comment by shiftkey** [comment]
@j-f1 @fenduru I've written some documentation about what we need from editors to integrate them nicely https://github.com/desktop/desktop/blob/master/docs/technical/editor-integration.md

**Comment by shiftkey** [comment]
I'm going to roll this up into #2487 and ask for people to get involved with contributing (because I don't have the bandwidth currently) once #3038 lands.
