### ISSUE TITLE
"Update From Default Branch" should use the default branch's name

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#3018]
_From https://github.com/desktop/desktop/issues/3016#issuecomment-335913972_

This is something I've run into too. For me, my eyes look for `master` and don't find it.

**Comment by wes321** [comment]
All your master are belong to us 😄

**Comment by MagicMarvMan** [comment]
If the issue is still available, I would like to take it over :octocat:

**Comment by MagicMarvMan** [comment]
How can I start? Unfortunately, Electron does not support dynamic changes to the menu bar ...

**Comment by iAmWillShepherd** [comment]
@MagicMarvMan, here is some code we're using to dynamically update the menu. To see it in action, change your default text editor and notice that the menu updates.

https://github.com/desktop/desktop/blob/4405c3bb22d33b92ed4682072e7e205420c88ef9/app/src/lib/stores/app-store.ts#L1112-L1126

**Comment by orangewords** [comment]
I would like to try my hand at this. Thanks!
