### ISSUE TITLE
Refresh the current PR's CI status periodically

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#3020]
As of https://github.com/desktop/desktop/pull/2918 we load and store the CI status for PRs.

We should also refresh the current PR's CI status periodically. We _could_ be kinda smart:

* We'll probably need to refresh it shortly after they push.
* If the status is pending, refresh pretty frequently (every minute?)
* Once the status goes red or green, we can back off and check less often, until the next push.

**Comment by j-f1** [comment]
Would it be possible to change the GitHub API for statuses to support `?since=` like [`/notifications`](https://developer.github.com/v3/activity/notifications/#parameters)? This way, the API would return an empty array if there are no changes, allowing more-frequent fetches.
