### ISSUE TITLE
Is there a way to get just stable builds?

### ISSUE THREAD

**Issue by xt0rted** [desktop/desktop#3021]
On my laptop the version is 1.0.3 and shows no updates available, on my desktop it shows 1.0.4-beta0 with an update available (just restarted and now it's 1.0.4-beta1).

I'm not sure how my desktop ever got onto the beta channel, but I couldn't find a setting to opt-out and go back to just stable builds. Is there an option for this, and if so how do I switch it?

**Comment by joshaber** [comment]
Sorry about that! There was a bug during the beta period where if you checked for updates you'd get moved onto the beta channel.

You can switch back by downloading a fresh copy from https://desktop.github.com.
