### ISSUE TITLE
Cannot install, stuck on sign into github

### ISSUE THREAD

**Issue by JeffBship** [desktop/desktop#3025]
Installing github desktop gets to the log in portion and gets stuck.  Internet connection is working.  Github.com is up in the browser and signed in (hence ability to post here.)  Using github desktop hangs up on this:

![untitled](https://user-images.githubusercontent.com/21348906/31473148-ab366786-aec0-11e7-826a-1ceb606595ee.png)

**Comment by shiftkey** [comment]
@JeffBship thanks for the report - we're tracking this in #2769 so please follow that issue. I'm going to have another shot today at getting to the bottom of this race condition!
