### ISSUE TITLE
New Branch menu option showing despite no repos

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3029]
The `New Branch...` option under the Branch menu is active despite no repos being in Desktop. The option should be greyed out until one repo is present.

<img width="1088" alt="screen shot 2017-10-12 at 8 32 53 am" src="https://user-images.githubusercontent.com/14828183/31484387-0aab1740-af28-11e7-9f65-ef271ad46bad.png">

1.0.4-beta1, mac

**Comment by shiftkey** [comment]
Unable to reproduce in 1.1.0 on macOS - @tierninho can you see this?

<img width="695" src="https://user-images.githubusercontent.com/359239/36764207-a30f750c-1c7f-11e8-9ae9-137ca521b856.png">
