### ISSUE TITLE
Remove `git directory` warning if no path

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3030]
If there is no path in the New Repo modal, then we should not show the `git directory` warning message as it's inaccurate.

<img width="389" alt="screen shot 2017-10-12 at 9 56 44 am" src="https://user-images.githubusercontent.com/14828183/31487971-2ac89d7a-af34-11e7-89b7-43d44e4e0e9d.png">

tested: 1.0.4-beta1 (Mac OS 10.11.6)

**Comment by joshaber** [comment]
This seems like a recent regression, so I'm gonna throw it in 1.0.x.

**Comment by joshaber** [comment]
Nevermind, doesn't look recent after all.

**Comment by shiftkey** [comment]
This was fixed in #5828 and will go out in `1.5.0`
