### ISSUE TITLE
Scope down 1.1

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#3031]
I've pitched this idea to everyone in 1:1's this week and no one was violently opposed 😈 So let's talk about it all together.

**What if we scoped 1.1 down and shipped it sooner than later?**

## Motivation

1. Maintain some momentum. After the long wait for 1.0, I think it'd be great to show our users and community that the app is moving forward and evolving at a nice pace.
1. We're rapidly approaching the holiday season. Realistically we're not gonna ship anything major from American Thanksgiving (end of November) until mid-January at the earliest. That gives us about a month and a half.
1. Pull request and CI status integration are really nice and I want them sooner than later! 😬 
1. My changing role means we'll have fewer engineering resources, so our velocity will slow.

## Potential Scope

If we decide to scope down 1.1, what exactly would the scope be? (I'm totally pulling this out of my butt. Entirely open to discussion.)

1. Pull request list.
1. Pull request CI status.
1. Auto-config upstreams on forks. (Without this, the PR list isn't terribly useful for forks.)

That means we'd punt on:

1. Relationship to _X_.
1. Conflict resolution lite.
1. In-app release notes.

## Punted Scope

I'd tentatively say we turn the punted scope into 1.2, turn 1.2 into 1.3, etc. But I think that's far enough down the road that we don't need to make that decision right now.

What do you all think?

/cc @desktop/core

**Comment by donokuda** [comment]
I'm 👍 with scoping down given how much iterating that still needs to be done around the designs for Relationship to X.

**Comment by shiftkey** [comment]
:thumbsup: getting the valuable bits out earlier and revisiting our roadmap after the new 1.1 is out works for me

**Comment by iAmWillShepherd** [comment]
I added one piece of conflict resolution to the milestone. Basically, it's just giving people the ability to open their choice of diff tools. 

Also, I put it in this milestone as a nice-to-have, if it doesn't get got to, I don't mind it getting shuffled into the next milestone.

**Comment by joshaber** [comment]
There have been no open revolts and we've talked about this in 1:1s. Forward!
