### ISSUE TITLE
Retain org selection in Publish Repo modal

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3039]
The organization dropdown selection is not retained if toggling between GitHub and Enterprise tabs.

Repro:
- Select org and toggle to other tab
- Org is cleared

I believe this is a regression, although the code says otherwise:

https://github.com/desktop/desktop/blob/964b68b3c7985ce17b48613bdd46cc083d8ab045/app/src/ui/publish-repository/publish.tsx#L226

<img width="458" alt="screen shot 2017-10-13 at 9 39 02 am" src="https://user-images.githubusercontent.com/14828183/31538114-6aa2f850-affc-11e7-8412-1a5bedab5c1a.png">

tested: 1.0.4-beta1, mac

**Comment by joshaber** [comment]
Yeah, we explicitly clear the selected org to fix https://github.com/desktop/desktop/issues/2386.

**Comment by tierninho** [comment]
Sounds good. Closing this issue.
