### ISSUE TITLE
Why isn't Brackets recognised as an External Editor?

### ISSUE THREAD

**Issue by ItsPugle** [desktop/desktop#3041]
### Description

Under **Settings** > **Advanced** on GitHub Desktop doesn't register/acknowledge Brackets as an External Editor.

### Version

**GitHub Desktop version:** 1.0.3

**OS version:** [version here] macOS High Sierra 10.13

### Steps to Reproduce

1. Have [Brackets](https://github.com/adobe/brackets) open.
2. Open GitHub Desktop
3. Go to **Settings** > **Advanced**.
4. Observe 

**Expected behavior:** Desktop recognises Brackets as an External Editor

**Actual behavior:** Desktop doesn't recognise Brackets as an External Editor

**Reproduces how often:** 100%

### Logs
I'm good.

**Comment by tierninho** [comment]
@ItsPugle Thanks for reaching out. We currently do not support Brackets. Currently, GitHub Desktop only supports opening repositories in applications that can handle opening a folder. Can Brackets open a folder?

Please refer our documentation for adding external editors: https://github.com/desktop/desktop/blob/master/docs/technical/editor-integration.md

**Comment by ItsPugle** [comment]
What do you mean by that, @tierninho? Yes, Brackets can open a folder?
I'd hope that every editor (excluding VIM) would be able to open a folder?

**Comment by shiftkey** [comment]
I'm going to roll this up into #2487 and ask for people to get involved with contributing (because I don't have the bandwidth currently) once #3038 lands.

**Comment by emikay** [comment]
Any updates on supporting Brackets?

**Comment by shiftkey** [comment]
@emikay still looking for someone interested in contributing. The [documentation](https://github.com/desktop/desktop/blob/master/docs/technical/editor-integration.md) should contain everything needed to get started.

**Comment by tristanisham** [comment]
I'm interested in contributing. I'm a huge fan of Brackets. I'll see if I can do it.

**Comment by tristanisham** [comment]
I think I did it? (Sorry, I'm kind of new to Github) @shiftkey

**Comment by shiftkey** [comment]
@tristanisham if you're happy with the work, you can submit a pull request: https://github.com/tristanisham/desktop/pull/new/but-with-brackets

**Comment by 3raxton** [comment]
Hey, @shiftkey we will submit a request in a bit. Is there a way to test the build before submitting a pull request?

**Comment by 3raxton** [comment]
What is the best way to test a build before submitting the pull request? Should I package a beta or do something else?

**Comment by j-f1** [comment]
Once you open a PR, our systems will run some automated tests. Don’t worry about having your PR done before you submit it — we usually open a PR as soon as we start working on something.

**Comment by 3raxton** [comment]
Great. I'll go ahead and open a PR. I appreciate your help!

**Comment by francisbarton** [comment]
> 
> 
> @ItsPugle Thanks for reaching out. We currently do not support Brackets. Currently, GitHub Desktop only supports opening repositories in applications that can handle opening a folder. Can Brackets open a folder?
> 
> Please refer our documentation for adding external editors: https://github.com/desktop/desktop/blob/master/docs/technical/editor-integration.md

This link goes to a 404 now

**Comment by shiftkey** [comment]
@francisbarton there was a rename of the default branch #6478 - I've edited the original link

**Comment by christinerogers** [comment]
Hi what's the status of this?  is there PR in progress? Is it stalled or shelved? thanks!
