### ISSUE TITLE
[Error] LFS Smudge - Multiple Values

### ISSUE THREAD

**Issue by mcmonkey4eva** [desktop/desktop#3044]
### Description

An error message! Been appearing for a while, ignored it a lot but it doesn't go away magically so I figured I'll report it.
```
Error running git [config --global filter.lfs.smudge git-lfs smudge -- %f]: 'warning: filter.lfs.smudge has multiple values
error: cannot overwrite multiple values with a single value
       Use a regexp, --add or --replace-all to change filter.lfs.smudge.' 'exit status 5'
Run `git lfs install --force` to reset git config.
```

Seems to be trying to set some git configuration every launch, and failing?

### Version

**GitHub Desktop version:** 1.0.4

**OS version:** Windows 10

### Steps to Reproduce

1. Honestly unsure the initial setup required, some weird pre-existing git configuration probably
1. Launch GitHub Desktop
1. Boom, error messages!

**Comment by joshaber** [comment]
Thanks @mcmonkey4eva! That's a known issue that we're tracking over in https://github.com/desktop/desktop/issues/2984. Feel free to follow along over there!
