### ISSUE TITLE
Error when clicking fetch/push/pull button

### ISSUE THREAD

**Issue by NMS127** [desktop/desktop#3046]
### Description

After updating, when I click the fetch/push/pull button, I get an error window saying:
> watch C:\WINDOWS\TEMP\GitHubDesktop-lfs-progress-URRumJ\GitHubDesktop-lfs-progress EPERM

Apparently it works, but the button text only updates if there are remote changes to pull, or sometimes after pulling. (I haven't tried pushing yet.)

### Version

**GitHub Desktop version:** 1.0.4

**OS version:** Microsoft Windows [Version 6.3.9600]
(Windows 8.1)

### Steps to Reproduce

1. Click the Fetch origin/push/pull button.

**Expected behavior:** Fetch info about the repo/ push or pull changes.

**Actual behavior:** Error message window appears. After closing, the correct effect may have occurred, but the button text is (usually) not changed.

**Reproduces how often:** Always.

### Logs

[2017-10-13.desktop.production.log](https://github.com/desktop/desktop/files/1384096/2017-10-13.desktop.production.log)

**Comment by shiftkey** [comment]
This is related to how we track Git LFS progress - https://github.com/desktop/desktop/pull/2355 

Two things I think we need to do here:

 - handle that `EPERM` error and avoid showing progress
 - understand why this is choosing `C:\Windows\TEMP` instead of `C:\Users\[username]\AppData\Local\Temp\`

@NMS127 could you open a ̦PowerShell prompt and run this command:

```
> Get-ChildItem Env:
```

I'm pretty sure Node is using `%TEMP%` when it creates this file, and on one of my test machines it looks like this:

```
PS C:\Users\shiftkey> Get-ChildItem Env:

Name                           Value
----                           -----
...
TEMP                           C:\Users\shiftkey\AppData\Local\Temp
TMP                            C:\Users\shiftkey\AppData\Local\Temp
...
```

**Comment by NMS127** [comment]
> TEMP                           C:\WINDOWS\TEMP
> TMP                            C:\Users\NATHAN~1\AppData\Local\Temp

I'm not exactly sure why it's there now. At one point, I think I moved it to D:\Temp because a video encoding program needed to store a huge amount of data there. But I haven't moved it recently. So you probably need to look for your files in the same place you store them, whatever it is.

**Comment by shiftkey** [comment]
`TEMP` and `TMP` should be aliased to the same directory, and it should be writeable to the current user. We're just using vanilla Node APIs to create this temporary file, so if you change it back to the path under `AppData` then the error will go away.

**Comment by NMS127** [comment]
Hmm, my System TEMP and TMP were set to C:\WINDOWS\TEMP, but my user TMP was the other one. Making them all point to the same place and combining the files fixed it. Thanks!

Maybe the error message could be more helpful here, but you can resolve if you want.

**Comment by shiftkey** [comment]
@NMS127 i'll leave this open to reproduce the issue and make our error handling better. I'm glad you were able to workaround it!
