### ISSUE TITLE
Add a command palette like Atom

### ISSUE THREAD

**Issue by j-f1** [desktop/desktop#3050]
Many of the useful features of Desktop are currently hidden in [right-click menus](https://github.com/desktop/desktop/issues/2718) or the menubar. Not only are they difficult to find there, they are fairly hard to reach for people who prefer to use the keyboard for everything. A command palette opened by a keyboard shortcut (maybe <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> for Atom compatibility?) would alleviate many of these concerns. Additionally, it would open the door for shortcut customization.

Implementation steps:

- [ ] Create a command-dispatch system
- [ ] Convert all/some actions done in the app in response to user interaction to use the dispatch system
   - [ ] Convert action trigger points (buttons, menu items) to use the dispatch system.
- [ ] Create a command palette using the system
- [ ] Add some internal commands (fetch?) to the system and palette

How does this sound?

**Comment by shiftkey** [comment]
For reference, this came up in the initial redesign in https://github.com/desktop/desktop/issues/549

> **Command palette**
>
> We're still really sold on this but we didn't have time to mock anything, we think this too will be a modal popover accessed through a keyboard shortcut or the menu.

That issue also touches on some scenarios, but I don't know if the @desktop/design crew has gone much further than that (they have been busy).

**Comment by shiftkey** [comment]
Putting this in the design queue to get some current thoughts written up.

**Comment by j-f1** [comment]
ping @desktop/design for 🤔?

**Comment by shiftkey** [comment]
This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by billygriffin** [comment]
Thanks folks for weighing in! After internally discussing this, we're going to remove future proposal as, while we think a command palette could be really cool, we're not sure it's clearly associated with a specific problem many users are facing, and the level of effort would be quite large. We're not opposed to this as a possible solution to a problem down the road but for now we don't intend to support it. Thanks!
