### ISSUE TITLE
Menu and Keyboard shortcut for Fetch

### ISSUE THREAD

**Issue by robrix** [desktop/desktop#3054]
### Description

There are keyboard shortcuts for Push and Pull but not for Fetch. I am honestly unsure if the distinction is always useful, but it would seem to be useful in the case where you’re on a branch with a corresponding remote tracking branch, you’ve *deleted* the remote tracking branch (e.g. after merging a PR), and you want to update `master` with the merge commit before switching back to it (e.g. to avoid your editor environment freaking out when all of the files change out from under it).

If you pull in that case you get an error message because the remote tracking branch is gone.

Conceivably this case also be served by making Pull do a Fetch when it detects that situation.

### Version

**GitHub Desktop version:** 1.0.5-beta0

**OS version:** 10.12.6 (16G29)

### Steps to Reproduce

1. Make a new branch.
2. Publish it to GitHub.
3. Delete the branch on GitHub.
4. Pull, and get the error mentioned above.
5. Search for a Fetch keyboard shortcut because your hands are glued to the keyboard. (I guess that’s sort of an implicit step 0: glue your hands to the keyboard.)

**Expected behavior:** I expected—hoped, really—to find a Fetch menu item & corresponding keyboard shortcut.

**Actual behavior:** I did not find one.

**Reproduces how often:** 100% of the time that I have looked for one, I have not found one.

### Logs

N/A

#### Additional Information

On os x at least, having a menu item for Fetch would confer another couple of benefits:

1. You can search for it using the Help menu, improving discoverability (at least a little bit).
2. You can reassign the keyboard shortcut using System Preferences > Keyboard > Keyboard Shortcuts.

I don’t know if the same is true for other platforms, however.

**Comment by billygriffin** [comment]
Going to combine this with #7805.
