### ISSUE TITLE
The Program think .sql file is a binary file.

### ISSUE THREAD

**Issue by datauduong** [desktop/desktop#3059]
### Description

The Program think .sql file is a binary file, therefore the preview does not show.

### Version

**GitHub Desktop version:** 1.0.4

**OS version:** Windows 10 Pro

### Steps to Reproduce

1. [First step]
Open/Clone GitHub Repository
1. [Second step]
Update .SQL file
1. [Third step]
Navigate to the changes Tab.
1. [Fourth step]
Click on the .sql (Microsoft SQL Server Script) file to Preview

The preview windows show This binary file has changed. Open file in external program.

**Expected behavior:** [What you expected to happen]
The preview of the .sql should be shown instead of (Open file in external program).

**Actual behavior:** [What actually happened]
This binary file has changed. Open file in external program.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% (Tested on 2 machine, the same issue)

**Comment by shiftkey** [comment]
@datauduong thanks for the report. This really feels like an earlier report of this, which we traced to how Git detect binary files: https://github.com/desktop/desktop/issues/1904#issuecomment-310850280.

The linked [Stackoverflow thread](https://stackoverflow.com/questions/28145687/why-does-git-think-my-sql-file-is-a-binary-file/28145968#28145968) talks about a number of ways to workaround this.
