### ISSUE TITLE
App does not refresh account info through API (e.g. name change)

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3066]
If the name (`user[profile_name]`) of a user if updated while logged in to Desktop (in this case Enterprise), then Desktop is not reflecting the change unless the user logs out and back in. 

Should we being checking for updates?

Console logs:
[AppStore] removing account tierninho (null) from store
[AppStore] adding account tierninho (TL) to store

<img width="449" alt="screen shot 2017-10-16 at 11 11 34 am" src="https://user-images.githubusercontent.com/14828183/31607287-b2b91d04-b263-11e7-8766-e58c67c176ee.png">

tested in 1.0.5-beta0, mac

**Comment by joshaber** [comment]
Yeah, that sounds like a bug 👍

**Comment by billygriffin** [comment]
I'm going to roll this into #610 as it's pretty closely related and we should make sure we consider this in thinking through that one.
