### ISSUE TITLE
Redirect Enterprise user to Prefs, i/o surfacing generic auth dialog

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3068]
If an Enterprise user logs out and comes across the generic auth dialog, we should instead redirect them to Preferences as the auth dialog is only meant for logging into arbitrary 3rd party servers.

https://github.com/desktop/desktop/blob/4f17073dd80b867ffafe5dce5a83d5abe8ca57c0/app/src/ui/generic-git-auth/generic-git-auth.tsx#L57

Repro:
- Log out of Enterprise
- Delete a Enterprise repo locally
- Click `clone again`

<img width="432" alt="screen shot 2017-10-16 at 1 48 52 pm" src="https://user-images.githubusercontent.com/14828183/31613647-a9f5ea7c-b27b-11e7-87bb-22040c7a652a.png">

tested in 1.0.5-beta0, mac

**Comment by shiftkey** [comment]
> If an Enterprise user logs and out comes across the generic auth dialog, we should instead redirect them to Preferences as the auth dialog is only meant for logging into arbitrary 3rd party servers.

This means we'd need to do the [probing](https://github.com/desktop/desktop/blob/master/app/src/lib/api.ts#L678-L701) to recognize that it's a GHE server whenever we encounter a new "generic" Git server, right?

**Comment by tierninho** [comment]
I'll default to @joshaber as we chatted about this briefly.

**Comment by joshaber** [comment]
I was thinking about this in the context where your existing authentication with an Enterprise server no longer works, more in line with #1482.

**Comment by joshaber** [comment]
...in which case I think we can just roll it into that issue.
