### ISSUE TITLE
precommit hooks not running on repository 

### ISSUE THREAD

**Issue by domehead100** [desktop/desktop#3074]
### Description

Often repositories have npm scripts that are linux specific and will not run on a Windows shell (not cmd, not Powershell, not Git Bash in Windows).  For example:  
```json
 build: 'rm -fr ./dist && NODE_ENV=production babel ./src --out-dir ./dist --source-maps --copy-files ...
```
This build script works fine in a linux environment but even with "linuxy" shells on Windows will fail with "'NODE_ENV' is not recognized as an internal or external command, operable program or batch file.".  To fix it, you'd have to change it to "set NODE_ENV=production" in the build script and thus would need separate Windows and non-Windows build scripts (or don't use shell commands in the build script at all).

The Windows Subsystem for Linux, however, gives the user an actual Ubuntu bash shell, and build scripts like this run just fine (assuming the user has installed node, npm, etc. in this linux environment). The executable is in C:\Windows\System32\bash.exe.

In the old GitHub for Windows, there used to be an option for a Custom shell, but that couldn't see C:\Windows\System32\bash.exe and would report that the executable did not exist (probably due to 32-bit/64-bit isolation in this bash shell).  Creating a link to this bash shell would get GitHub for Windows to accept it, but it will wouldn't work, throwing the same error noted above about NODE_ENV not being an executable (I've no idea why).

In the new GitHub Desktop, the Custom option is gone (not that it would necessarily work), so the Windows user is out of luck and can't even commit locally (without resorting to using a VM) if there are precommit hooks in place that require, for example, tests to pass.

### Version
**GitHub Desktop version:** Version 1.0.4 (Windows)
**OS version:** Windows 10 v1607 Build 14393.1770

### Steps to Reproduce

1. Try to commit to a forked repo that has a build script as noted above that has a precommit hook requiring tests to pass.  You will not be able to commit, because tests will always fail as noted above.

2.  Open a WSL bash shell and run the test and build script manually from the command line (e.g., npm run test, npm run build).  They both work fine, tests pass, and build completes successfully.

**Expected behavior:** It would be nice to be able to leverage the relatively complete linux environment that WSL provides so as to be able to run shell scripts just like everyone else who is not using Windows.

**Actual behavior:** See steps to reproduce.

**Reproduces how often:** Always

### Logs

[2017-10-17.desktop.production.log](https://github.com/desktop/desktop/files/1389806/2017-10-17.desktop.production.log)

**Comment by shiftkey** [comment]
@domehead100 we haven't brought across the "Custom Shell" environment, but all the code for our current shells on Win32 lives [here](https://github.com/desktop/desktop/blob/master/app/src/lib/shells/win32.ts).

If I write some docs similar to our [Editor Integration](https://github.com/desktop/desktop/blob/master/docs/technical/editor-integration.md) for guidance about adding a new shell, would you be interested in contributing to that? I'm not entirely across the Win32/WSL bridging story these day, but I'm happy to help with testing and reviewing stuff.

**Comment by shiftkey** [comment]
@domehead100 actually, if you're in NPM you should use the trick we have setup for Desktop itself and use [`cross-env`](https://www.npmjs.com/package/cross-env) to prefix these commands.

```
"start": "cross-env NODE_ENV=development node script/start",
```

This will take care of setting the environment variables no matter what platform you're on.

**Comment by domehead100** [comment]
Thanks @shiftkey, I'd be willing to take a look at the editor integration.  I'll let you know after I look at the links you provided.

I couldn't get the "test" script to work using cross-env or cross-env-shell.  Tried in cmd, powershell, Git Bash, and Github Desktop with Git Bash set as my shell.  I could get the script to run without errors if changed the original:
```
"test": " NODE_ENV=test mocha --compilers js:babel-register"
```
to:
```
"test": " cross-env NODE_ENV=test node node_modules/mocha --compilers js:babel-register"
```
But it doesn't actually run the tests.  At least it allows me to commit since the precommit script is "npm run test", which now runs without throwing any errors.

**Comment by shiftkey** [comment]
@domehead100 I've just opened #3140 which documents our shell integration better.

Regarding the issue with running precommit hooks: I'm going to need an isolated reproduction to dig further into it. A good example of this is #3067.

**Comment by shiftkey** [comment]
I've updated this issue to indicate this is more about the commit hooks failing - feel free to open a fresh issue around the WSL support if you would like to see that proceed.
