### ISSUE TITLE
Image preview in diff view overflow entire app

### ISSUE THREAD

**Issue by PragmaticEd** [desktop/desktop#3075]
### Description
Image preview in diff fiew look broken and overflow even header/main top menu.
P.S. Image is gradient from light gray to transparent. 

![github desktop 2017-10-17 03 16 49](https://user-images.githubusercontent.com/19263525/31659848-4da5e140-b2ea-11e7-97f0-61a90f2e15a7.png)

**GitHub Desktop version:** 1.0.4

**OS version:**  Windows 10 2016 LTSB

### Steps to Reproduce

1) add or replace image in git, and view it in app

**Comment by tierninho** [comment]
possibly related to https://github.com/desktop/desktop/issues/2480

**Comment by PragmaticEd** [comment]
@tierninho Yes, yes it is the same. Didn't see existing issue, when i searched. You can close this one.

**Comment by tierninho** [comment]
Thanks @PragmaticEd 

Any steps or setup specifics that you can add to #2480 would be great as some of us had a hard time reproducing the issue.

**Comment by PragmaticEd** [comment]
Why is this closed, if it still happens?
I uploaded git project [here](https://github.com/PragmaticEd/github-large-image-preview-scale-bug), that reproduces the problem. @tierninho  please open the issue again, till fixed.

**Comment by PragmaticEd** [comment]
@tierninho  i added demo repo that explains how to reproduce the bug @ #2480
