### ISSUE TITLE
Can't clone a project that has no master branch

### ISSUE THREAD

**Issue by xem** [desktop/desktop#3076]
### Description

Can't clone a project that has no master branch

### Version

**Github Desktop version** 1.0.4

**OS version:** Windows 10

### Steps to Reproduce

1. try to clone a project that has just a gh-pages branch and no master branch

**Expected behavior:** see the project's history and files

**Actual behavior:** no files are cloned. Github Desktop considers it's on master, but doesn't let me checkout the real gh-pages branch nor publish master

**Reproduces how often:** 100%

![image](https://user-images.githubusercontent.com/1225909/31661931-cefb8234-b33c-11e7-9147-01acf0e61489.png)

**Comment by shiftkey** [comment]
Seems to be specific to this repository, as the clone also fails from the command line:

```
~/src/ git clone https://github.com/xem/attractorandom
Cloning into 'attractorandom'...
remote: Counting objects: 9, done.
remote: Total 9 (delta 0), reused 0 (delta 0), pack-reused 9
Unpacking objects: 100% (9/9), done.
warning: remote HEAD refers to nonexistent ref, unable to checkout.
```

**Comment by iAmWillShepherd** [comment]
@xem given that the same issue is happening in the git CLI, I'm going to close your issue. But is there anything you know to be different/unique about your repo? No reason why I can't still help you out 😄

**Comment by xem** [comment]
Thanks.
I managed to "git checkout gh-pages" using the CLI.
It's the GUI that doesn't do it correctly when I try to clone the project
