### ISSUE TITLE
Auth error for archived repos

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3077]
If a repo is archived the current error isn't entirely helpful as the user still has permission to access the repo (in some regard). Should we update the error or change the messaging altogether? 

> "Authentication failed. You may not have permission to access the repository. Open preferences and verify that you're signed in with an account that has permission to access this repository."

<img width="1021" alt="screen shot 2017-10-17 at 2 33 23 pm" src="https://user-images.githubusercontent.com/14828183/31667821-672d0d74-b348-11e7-87c1-4224d5636d21.png">

tested in 1.0.5-beta0, mac

**Comment by agisilaos** [comment]
What are you thinking as an alternative @tierninho? Would love to work on that as well.

**Comment by iAmWillShepherd** [comment]
@agisilaos, I can work with you on this if you like. Since you are a users of Desktop, I feel like you may have some say in what the message should say.

**Comment by iAmWillShepherd** [comment]
Yes, I was talking about the error message. I think that is sufficient. Would you like to tackle the implementation or should I do it?

**Comment by agisilaos** [comment]
Just did it, PR: #3084

**Comment by tierninho** [comment]
Note, the archive repo feature has now been released to all users.
