### ISSUE TITLE
Get back discarded changes

### ISSUE THREAD

**Issue by Lucas-L** [desktop/desktop#3083]

**Comment by shiftkey** [comment]
@Lucas-L

>  Is it possible to get my files back ?

If you were using right-click -> Discard Changes from the Desktop UI, these changes (new files and modified files) are moved to the Recycle Bin or Trash, depending on your OS.

<img width="469" src="https://user-images.githubusercontent.com/359239/31693501-af156364-b3ea-11e7-8fd4-e6029acc14e0.png">

> Last thing : I can't get another verion of my master cause I never comited these files

Not sure I understand this one.

**Comment by Lucas-L** [comment]
I couldn't find them  in  the bin  ...  Anyway i managed to copy the file from  an  open tab ... Thank you very much  !
