### ISSUE TITLE
pandoc.ps1 missing from 20487b-repo.

### ISSUE THREAD

**Issue by GitHub-Soliman** [desktop/desktop#3088]
### Description

Moin Moin.
Upon cloning, "https://github.com/MicrosoftLearning/20487-DevelopingWindowsAzureAndWebServices"
pandoc.ps1 and template.docx are missing, but can be seen in "https://github.com/MicrosoftLearning/20487-DevelopingWindowsAzureAndWebServices/pull/2/files#diff-7b101bbe393cc766d6e64717df850980" or "https://github.com/MicrosoftLearning/20487-DevelopingWindowsAzureAndWebServices/pull/2/files#diff-549a5117c1c2cbe482b54b8b92e973fb" (found via google).
Does anyone know, why it is not being downloaded or found in the zip-cloned version of the repo for that matter.
Tschüß,
__Michael.

### Version
Git-2.14.2.3-64-bit.exe.

**GitHub Desktop version:** [version here]
1.0.4.

**OS version:** [version here]
Microsoft Windows [Version 6.1.7601]
### Steps to Reproduce

1. clone "https://github.com/MicrosoftLearning/20487-DevelopingWindowsAzureAndWebServices"
2. goto "c:\tmp\20487-DevelopingWindowsAzureAndWebServices\Build"
3. only "Readme.md"  can be found, whilst "pandoc.ps1" and "template.docx"  are missing 

**Expected behavior:** [What you expected to happen]
"pandoc.ps1" and "template.docx"  should be present 
**Actual behavior:** [What actually happened]
"pandoc.ps1" and "template.docx"  are missing 
**Reproduces how often:** [What percentage of the time does it reproduce?]
always

**Comment by niik** [comment]
Hi @GitHub-Soliman,

Those files are part of an open Pull Request against the project and haven't yet been merged. When you clone a repository we automatically checkout the master branch where these files don't exist yet. 

We're working on adding support for checking out pull requests from forks (see #2823) but until that's added you can either clone `AgileJoshua`'s repository directly or click on the computer icon on the right hand side of the diff to check out that PR branch.

![screen shot 2017-10-18 at 13 37 37](https://user-images.githubusercontent.com/634063/31716757-94659c9a-b409-11e7-9c64-a10a2655eca2.png)

Given that this is more of a general Git question and less about GitHub Desktop I'm going to close this issue out but please open a new one if you find other issues with GitHub Desktop.

**Comment by GitHub-Soliman** [comment]
Moin Moin.
Maybe I did something wrong, but cloning "https://github.com/AgileJoshua" requires another password than my users', and hitting the little computer-icon and downloading everything still misses the "pandoc.ps1" and "template.docx" files.
Can they be downloaded manually.
_Tschüß,
__Michael.

**Comment by GitHub-Soliman** [comment]
P.S.: Interesting, using Your instructions on  "x-github-client://openRepo/https://github.com/MicrosoftLearning/20487-DevelopingWindowsAzureAndWebServices?branch=pr%2F2&filepath=Build%2Ftemplate.docx&pr=2" did work (but not on "x-github-client://openRepo/https://github.com/MicrosoftLearning/20487-DevelopingWindowsAzureAndWebServices?branch=pr%2F2&filepath=Build%2Fpandoc.ps1&pr=2").
Ignore my last comment, please. 8^).

**Comment by GitHub-Soliman** [comment]
Moin Moin.
Exceuse, me, please for being a newbie.
Using github takes so much time, if You do not know, where to search for the files or the explanations for explanations for... where to find them.
I am not anymore able to open the "Build/pandoc.ps1" from Your screenshot., in order to click the computer-button (for other files this is not a problem.)
Do You have any ides, where to find it.
_Tschüß,
__Michael.

**Comment by GitHub-Soliman** [comment]
P.S.: Never mind. I debugged it.

**Comment by blogux** [comment]
What is going on ??? Where is this file ??? How to prepare for labs ??? How deliver course ??? No file, no support, nothing. Where is Microsoft ???
