### ISSUE TITLE
Block emoji from being entered as a repo name

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3090]
Emoji shouldn't be allowed in place of a repo name as they are converted anyway to "normal" characters by GitHub.com and Desktop once published.

If you already have a repo with the name`github.com/tierninho/-1` and you decide to create a new repo with an emoji 🐴  as the repo name, the name becomes converted to  "normal" characters as expected. However, if you click "open in GitHub" or "create PR", the existing repo is opened despite the real url being `github.com/tierninho/-`

<img width="451" alt="screen shot 2017-10-18 at 2 34 22 pm" src="https://user-images.githubusercontent.com/14828183/31721629-c5981858-b411-11e7-9344-3b4069ec5c7c.png">
<img width="615" alt="screen shot 2017-10-18 at 2 35 27 pm" src="https://user-images.githubusercontent.com/14828183/31721630-c5b8708a-b411-11e7-9b10-aa330f065e8e.png">

Just remove the Emoji option from the Edit menu?

tested 1.0.5beta0, mac

**Comment by shiftkey** [comment]
@tierninho so emoji (or non-UTF8 characters) in the repository name _don't_ get rejected by the GitHub API? Is that accurate? What does the resulting dotcom repository home page look like?

**Comment by tierninho** [comment]
@shiftkey 

> so emoji (or non-UTF8 characters) in the repository name don't get rejected by the GitHub API?

Correct, they _don't_ get rejected as somewhere along the line, GitHub recognizes the special characters and converts them to `-` as so:

`[AppStore] adding repository at /Users/tierninho/Documents/testing/testtnfnttttdfdfttttt/--x to store`

> What does the resulting dotcom repository home page look like?

Resulting page looks like: https://github.com/tierninho/-a1 for this

<img width="462" alt="screen shot 2017-10-19 at 7 38 29 am" src="https://user-images.githubusercontent.com/14828183/31757368-9bb80f68-b4a0-11e7-90fe-796c97c3d0f3.png">

The controller test in GH/GH would return a 422 for dupes, but I couldn't trigger it for invalid names.

**Comment by camdevcam** [comment]
I've noticed they are still rendering on some accounts, though.

**Comment by Daniel-McCarthy** [comment]
I was taking a look at this last night. If I understand correctly, the issue seems to be that although we sanitize names with the `Create-Repository` dialog, we do not do the same checks in the `Publish-Repository` dialog, which gives the user a chance to potentially put in characters like emojis?

Would it then be sufficient to include this sanitization behavior we do in the `Create-Repository` dialog in the `Publish-Repository` dialog as well? 

Like this:
![peek 2018-10-04 15-07](https://user-images.githubusercontent.com/4957200/46500418-6b386c00-c7e8-11e8-88fb-97d8beba1920.gif)

If so I would be happy to make a pull request for this. Otherwise I would love to understand this issue a little better and what other considerations need to be made.

**Comment by Daniel-McCarthy** [comment]
I noticed this while looking into this Issue:
https://github.com/desktop/desktop/blob/d8e79651a71a0bb72878b6ed465349712be845dd/app/src/ui/add-repository/sanitized-repository-name.ts#L1-L4

It seems that GitHub.com allows repository names to have `_` in addition to `.`, `-`, and the a-z 0-9 characters. The sanitization function filters out `_`. However, it appears GitHub.com does not. I don't see a documented reason in this file, so I was curious if there's some sort of other compatibility issue here.

**Comment by Daniel-McCarthy** [comment]
@tierninho Would adding the repository name sanitization that occurs in the `Create-Repository` dialog to the `Publish-Repository` dialog be a sufficient solution for this issue?

If so, I have the changes required for this ready.  I have extra details about this proposed solution in the comment above.

**Comment by outofambit** [comment]
@Daniel-McCarthy that seems like a sensible approach to me. I'm not sure about the reasoning for filtering out `_` so I think its best to preserve that behavior for now. thank you!

**Comment by Daniel-McCarthy** [comment]
@outofambit Sounds great! I have the changes ready and will get a pull request ready soon.

>I think its best to preserve that behavior for now.

I certainly agree. I was hoping that perhaps this might be an opportunity for some improved documentation to explain this, so I gave it a mention while it was relevant.

**Comment by ednl** [comment]
I found this old thread, sorry. But I think this is relevant: the web interface for Create New Repo still allows emojis (and other "illegal" characters, presumably) and doesn't gave a hint that these will be converted to -.

I actually think they should be allowed (I mean, why not?) but until that is possible & agreed upon, it's probably simpler & cleaner & more obvious & thus better to apply the same sanitiser to the (new) repo name input in the web interface.

**Comment by shiftkey** [comment]
> the web interface for Create New Repo still allows emojis (and other "illegal" characters, presumably) and doesn't gave a hint that these will be converted to -.

This is what I see when I try and specify emoji on the `/new` page:

<img width="468" src="https://user-images.githubusercontent.com/359239/88953292-14c6d800-d26f-11ea-9deb-80773b4d05b5.png">

@ednl if you've found a different place on GitHub that isn't showing this behaviour, please share a screenshot or describe the steps to find it.

**Comment by ednl** [comment]
Oh you are right, that does show. Sorry! (again). However, I think the reason I overlooked it is because the green checkmark in the textbox itself was more prominent to me. That checkmark is deceiving; I am not sure that anyone typing certain characters on purpose which will be converted to "-", would agree that that is worth a green checkmark. The name, as typed, won't be accepted.
