### ISSUE TITLE
Expand list of external editors for GitHub Desktop

### ISSUE THREAD

**Issue by davidfmiller** [desktop/desktop#3092]
### Description

GitHub Desktop doesn't allow applications *other than* Visual Studio Code to be selected as the application's preferred external editor

### Version

**GitHub Desktop version:** 1.0.4

**OS version:** 10.12.6

### Steps to Reproduce

1. Open "Advanced tab" in GitHub Desktop Preferences
2. Note contents of "External Editor" selection list. BBEdit, for instance, is not available.

<img width="433" alt="screen shot 2017-10-18 at 7 43 04 am" src="https://user-images.githubusercontent.com/12614/31725085-4f591612-b3d8-11e7-8c49-c15d5c1bf29d.png">

**Reproduces how often:** Every time

**Comment by davidfmiller** [comment]
<img width="433" alt="screen shot 2017-10-18 at 7 43 04 am" src="https://user-images.githubusercontent.com/12614/31725365-08fa4456-b3d9-11e7-8230-cf6bd2fd5deb.png">

**Comment by j-f1** [comment]
We have a PR open to add BBEdit in #2941. Please follow along there for updates.
We only show supported external editors that you have installed. We currently support Atom, VS Code, and Sublime Text on macOS. Are there any other editors you have installed that we should consider adding?

**Comment by iAmWillShepherd** [comment]
We support more than just VS Code. If you have Sublime or Atom installed, we will also allow those to be used. We are currently working to make adding an external editor easier for those willing to contribute. See the issue @j-f1 referenced.

**Comment by davidfmiller** [comment]
BBEdit is the only text editor that matters. Thanks, everybody!

**Comment by M1DLG** [comment]
I would love to see the Arduino IDE added to the external editors screen too. Would it not be ideal to add an option to add the parameters ourselves to the GitHub desktop application, so we could add the function ourselves. Allowing us to open any code in any editor anytime we wish.

**Comment by MBfromOK** [comment]
Notepad++:

- It has rapidly received adoption by coders
- Supports almost 80 programming languages out of the box including: 
    - Customizable syntax highlighting
    - Syntax folding
    - Auto-completion (customizable)
    - Function list (customizable via PCRE in xml file).
- Users can add their custom code language / style as a user defined language
- Ability to search, search & replace, regex search, regex search & replace
- Supports normal and vertical (column) selection
- Supports Macros, Automation, and ghost typing
- Supports launching from command line
### - Price: Free

**Comment by RishabBorah** [comment]
It would be very helpful if some form of compatibility with Eclipse was possible

**Comment by CSTNicole** [comment]
It would also be helpful if Visual Studio is added to the external editor.

**Comment by maldz3** [comment]
Would really like to see Pycharm be an option too.

**Comment by moidurrahaman15** [comment]
> It would also be helpful if Visual Studio is added to the external editor.thank you very much

**Comment by FlavioZanoni** [comment]
I would like to see PyCharm as an option

**Comment by papirovdavid** [comment]
Please add also Android Studio

**Comment by manasikara** [comment]
Brackets, please!

**Comment by arpajian** [comment]
Surprised no one has asked for Geany?

**Comment by pastansberry-clgx** [comment]
Is there no way to configure your own by selecting an executable? For example the repository I use is mostly controlled *.sql files, so I would prefer to set my SQL editor (Navicat) as the external editor of choice.

**Comment by snoblenet** [comment]
Onivim2 please. By rights, the user should just be able to select any installed app.

**Comment by bolshoibob** [comment]
I would love integration with Geany and an editor!

**Comment by BrianDawe** [comment]
The only option I have here is notepad++ I have numerous ide's installed and would like to use intellij but it's not showing

**Comment by danir-de** [comment]
A support for [Kate](https://kate-editor.org/de/) or [KDevelop](https://www.kdevelop.org/) would be awesome as well.

**Comment by dmnbc** [comment]
what about Qt Creator ?

**Comment by andrasguseo** [comment]
Is this project dead?

I'd like PHP Storm to be added.

**Comment by htbmw** [comment]
I'm surprised this is not a configurable / extensible setting.
There are too many different editors out there and it is pointless to restrict users to a finite set of editors.

Please make this extensible / configurable so that the options are limitless.

**Comment by Daekesh** [comment]
I'd like Rider and Rider for UE to be added. Thanks <3

Or what the guy above me said.

**Comment by Diibee** [comment]
Please add Intellij

**Comment by crunchysteve** [comment]
Why even a menu in "Preferences.../Integrations"? Why not just a button, "Add External Editor", then select an IDE from the "Applications"/"Program Files" folder, enter a file type and save. eg Arduino IDE with association of .ino. Or just build the menu from a list of known IDEs compared to what's in the app folder.

Seriously, how hard can it be? VScode, Atom or Xcode are all too much editor for we microcontroller tweekers.

**Comment by crunchysteve** [comment]
And heck, here we are, 5 years after the initial request, still only 3 editors. And no, I don't want to use VScode with PlatformIO, it's too much editor for the projects I build.

**Comment by steveward** [comment]
@crunchysteve GitHub Desktop supports more than three editors. See the list here:

https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md

You can also follow along in https://github.com/desktop/desktop/pull/14843 for work that is being done to provide greater flexibility for editor integrations.

**Comment by crunchysteve** [comment]
So, latest version, downloaded today, a screenshot...
<img width="1440" alt="Screen Shot 2022-09-22 at 11 26 55 pm" src="https://user-images.githubusercontent.com/46626696/191759905-139b4446-5a2c-4e77-a581-558a00d9c7c8.png">

**Comment by andrasguseo** [comment]
> GitHub Desktop supports more than three editors. See the list here:
> 
> https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md
> 
> You can also follow along in #14843 for work that is being done to provide greater flexibility for editor integrations.

@steveward The guide is great, thanks! However, I'm unable to find the file or even the folder of `app/src/lib/editors/win32.ts`
Any pointers are appreciated.

**Comment by Rexogamer** [comment]
> So, latest version, downloaded today, a screenshot... <img alt="Screen Shot 2022-09-22 at 11 26 55 pm" width="1440" src="https://user-images.githubusercontent.com/46626696/191759905-139b4446-5a2c-4e77-a581-558a00d9c7c8.png">

IIRC, it only lists editors that are installed on your device

**Comment by jessedmatlock** [comment]
Any update on adding Pulsar Edit (Atom fork/replacement) for an external editor??

**Comment by andrasguseo** [comment]
> Any update on adding Pulsar Edit (Atom fork/replacement) for an external editor??

These folks don't seem to car. Sad, sad, sad.

**Comment by steveward** [comment]
Pulsar is being added in https://github.com/desktop/desktop/pull/16220 for macOS.

**Comment by andrasguseo** [comment]
How about PHP Storm?

**Comment by tsvetilian-ty** [comment]
@andrasguseo phpstorm should be available in the external editors list

**Comment by andrasguseo** [comment]
Thanks @tsvetilian-ty .

> @andrasguseo phpstorm should be available in the external editors list

It should be but I'm having trouble finding it. See screenshot:
https://dl.dropboxusercontent.com/s/ypkxakzz1sey7ue/shot_230313_124237.jpg

I also checked the documentation here:
https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md

I'm on Windows, I have trouble finding the mentioned folder:

> The source for the editor integration on Windows is found in [app/src/lib/editors/win32.ts](https://github.com/desktop/desktop/blob/development/app/src/lib/editors/win32.ts).

So where is that  `app/src/lib/editors/win32.ts` folder?

I did a search for the `win32.ts` file, but also couldn't find it.

Any pointers are appreciated.

I just reinstalled it and have the latest version. Still nothing.

**Comment by tsvetilian-ty** [comment]
@andrasguseo I tested it as JetBrains Toolbox installation, and it works as expected.

![image](https://user-images.githubusercontent.com/9341546/225104671-f764f8c9-cf7e-48e9-ad20-8aa999607df6.png)

If you think that there is a problem, please open a [new issue](https://github.com/desktop/desktop/issues/new/choose) 😃
