### ISSUE TITLE
Unusual text select behavior in wrapped diff

### ISSUE THREAD

**Issue by nycdotnet** [desktop/desktop#3094]
### Description

When using the history tab and reviewing an old commit with a change on a very long line (long enough that it wraps in the right-hand panel, and attempting to select text in that old commit, the text will be selected using a block-style select instead of a text-style select.  It seems that the block-style select is just a visual artifact, though.  See attached gif for demo of the bug.

### Version
**GitHub Desktop version:** 1.0.5-beta0
**OS version:** Microsoft Windows [Version 10.0.16299.15]

### Steps to Reproduce

1. Create a repo
1. Make a file with a few fairly long lines of code.
1. Commit that file.
1. Make a change to one of the lines.
1. Commit that change.
1. Go to the History tab.
1. You will see that the lines in the diff are wrapped (this is fine).
1. Try to select part of the top of one of the lines.  You will see the unusual block select behavior.

![multilineselectbug](https://user-images.githubusercontent.com/3755379/31728836-622ddce6-b3fb-11e7-833a-1a7fac96e6ed.gif)

**Expected behavior:** I expect the selected area to behave similarly to highlighting in a typical text editor.

**Actual behavior:** The text selection seems like it's a block select, but based on what gets copied, it's a text select.

**Reproduces how often:** Every time when the text is wrapped.

### Logs
N/A

#### Additional Information
I haven't noticed this before - not sure if this is a regression or not.

**Comment by j-f1** [comment]
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #1551. Please follow that issue for further updates.

**Comment by nycdotnet** [comment]
My sincere apologies. I agree this is a duplicate.  Thank you.
