### ISSUE TITLE
Locked local directory blocks new repo creation

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3099]
///semi-bug/// If a user locks a directory locally, and attempts to create a New Repo within that directory, they are blocked with the following error:

`EPERM: operation not permitted, mkdir '/Users/tierninho/testing/Gggg/1'`

I had locked the directory: Gggg

Console logs:
`install.ts:23 createRepository: the directory at /Users/tierninho/testing/Gggg/1/lockeedddddd is not valid. Error: EPERM: operation not permitted, mkdir '/Users/tierninho/testing/Gggg/1'`

Perhaps we could surface a better error message or run a check ahead of time?

Also, when the user clears the error message, the New Repo modal is surfaced again, however all the data previously entered is cleared... intended functionality? 

v1.0.5beta0, mac

**Comment by shiftkey** [comment]
Switching this to `enhancement` because we do block, and the work here is to ensure the UI also displays this error.

**Comment by tierninho** [comment]
Closing this as it has not come up enough times to be validated as a real problem.
