### ISSUE TITLE
Sync to Github on Commit

### ISSUE THREAD

**Issue by bilal-khan** [desktop/desktop#3100]
### Description

Feature Request: Could we please have an option to automatically push back to Github on each commit. The previous version of the app used to have this setting.

It would be useful to always have the remote branch sync up with the local in case a laptop is lost/destroyed.

### Version

**GitHub Desktop version:** 1.0.4

**OS version:** macOS 10.13

**Comment by shiftkey** [comment]
@bilal-khan thanks for the suggestion. This didn't make the cut for 1.0 as it was never implemented in the Windows version, but you can follow along with the existing issue: #2191
