### ISSUE TITLE
Open repo in editors besides Atom

### ISSUE THREAD

**Issue by chris-c-thomas** [desktop/desktop#3102]
# Description

**Feature Request:** Could we please have an option to open repos in editors besides Atom? I do love Atom, but I also love VS Code, and would love the option to open in both.

It just seems useful to allow multiple editors to be used. 

## Version

**GitHub Desktop Version:** 1.0.4

**OS version:** macOS 10.13

**Comment by niik** [comment]
Hi @chris-c-thomas, good news! We do support Visual Studio Code. If you open Preferences and go to the advanced tab you can select which editor you'd like to use

![screen shot 2017-10-19 at 19 00 39](https://user-images.githubusercontent.com/634063/31783803-d72c0a86-b4ff-11e7-928d-4c65b6e19f2b.png)

We have an issue tracking adding even more external editors over at https://github.com/desktop/desktop/issues/2487

**Comment by chris-c-thomas** [comment]
@niik Well don't I feel dumb. Thanks for this!
