### ISSUE TITLE
Default avatar icons shown for all users

### ISSUE THREAD

**Issue by xxjapp** [desktop/desktop#3112]
### Description

Default avatar icons shown for all users. Even for who has avatar icons.

### Version

**GitHub Desktop version:** 1.0.4
**OS version:** Microsoft Windows [Version 6.1.7601]

### Steps to Reproduce

1. Click History in left panel

**Expected behavior:** User who has avatar icon should displayed his/her own icon.

**Actual behavior:** Only default icon for all users displayed.

**Reproduces how often:** 100%

**Comment by agisilaos** [comment]
Hey @xxjapp thank you for opening this issue. Please check if you're signed in with your GitHub credentials in Github Desktop. You can check that from Github Desktop -> Preferences
![screen shot 2017-10-20 at 13 41 17](https://user-images.githubusercontent.com/10944108/31817418-890d14ce-b59c-11e7-9e27-9854dd067aba.png)

**Comment by tierninho** [comment]
This is a duplicate of https://github.com/desktop/desktop/issues/821

Please track the progress there.

**Comment by joshaber** [comment]
Hmm, I'm not so sure it's a duplicate of #821 yet.

@xxjapp Is this with a GitHub.com repository or a GitHub Enterprise repository?

**Comment by AIKKYU** [comment]
#3112

**Comment by AIKKYU** [comment]
#821

**Comment by xxjapp** [comment]
@joshaber 

This is not a GitHub.com repository or a GitHub Enterprise repository.

**Comment by joshaber** [comment]
Ah, ok. In that case it was probably because the previous versions of the app also loaded avatars from Gravatar. The new versions only log avatars from GitHub.

**Comment by xxjapp** [comment]
@joshaber 
Why? Could this feature be fixed again?

**Comment by joshaber** [comment]
Potentially, yes. We're exploring add Gravatar support back in https://github.com/desktop/desktop/issues/821.
