### ISSUE TITLE
Changes detected not accurate

### ISSUE THREAD

**Issue by flaminggenius** [desktop/desktop#3113]
There seems to be an issue with what files have changed when using desktop client with a unity project as soon as I open unity all the files need to be uploaded again and all that it says is "binary has changed" and there's a yellowish symbol next to the file

**Comment by j-f1** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by iAmWillShepherd** [comment]
I'm not sure if Unity is supported, but one thing that I'd recommend is making sure that you ignore all binary files in your `.gitignore` file. Please attach some logs as well as what version you are using and hopefully, we can work something out 👍

**Comment by AIKKYU** [comment]
#3113

**Comment by shiftkey** [comment]
Closing this out as inactive.

@flaminggenius if you can provide some more details about the issue and why the files might be marked as modified we'd be happy to help troubleshoot further.

**Comment by flaminggenius** [comment]
I wasn't sure how to provide more information but github provides a .got ignore template for unity and c# environments so that fixed it

On a side note maybe make a menu when we create a new locAL repositor to initialize with one of the mgitignore templates

**Comment by shiftkey** [comment]
> I wasn't sure how to provide more information but github provides a .got ignore template for unity and c# environments so that fixed it

The details provided in the issue template (OS, version installed, repro steps) as well as a sample repository would have helped us to understand the issue better, but I'm glad you were able to fix it.

> On a side note maybe make a menu when we create a new locAL repositor to initialize with one of the mgitignore templates

This is already an option to do when creating a new repository:

<img width="566" src="https://user-images.githubusercontent.com/359239/32466941-e1d58092-c39c-11e7-82be-07ec67f91d60.png">
