### ISSUE TITLE
go freezing in windows 10

### ISSUE THREAD

**Issue by AhmadIbrahiim** [desktop/desktop#3118]
it freezes every time i open it with no availability to interact with any button or the menu section 
![image](https://user-images.githubusercontent.com/17949497/31856912-192bdaf8-b6cf-11e7-858b-bd90a48fd289.png)

### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by joshaber** [comment]
Hi @AhmadIbrahiim! Could you please grab the logs from `%APPDATA%\GitHub Desktop\logs\*.desktop.production.log` and upload them here for us to look at? Thanks!

**Comment by shiftkey** [comment]
Closing this out due to inactivity.

@AhmadIbrahiim if you're able to find the logs from around this time please send them through - we're happy to revisit this issue and troubleshoot further.
