### ISSUE TITLE
Show PR Status Description

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#3134]
Each PR status has a description which can be pretty useful; we should expose this info in the UI

**Comment by joshaber** [comment]
I'd consider this a stretch goal for 1.1.

**Comment by niik** [comment]
I think that if we're gonna aim for this in 1.1 we should keep it simple and go with what dotcom does i.e. tooltips of CI status icons which show the full details on hover when there's only one check

![screen shot 2017-11-21 at 15 13 26](https://user-images.githubusercontent.com/634063/33076950-a2cd660c-cece-11e7-82de-35329002f5f1.png)

And combine statuses when there's more than one check

![screen shot 2017-11-21 at 15 11 56](https://user-images.githubusercontent.com/634063/33076891-5e8214de-cece-11e7-85dc-03b92e940644.png)

These would be standard tooltips in our case, obviously.
