### ISSUE TITLE
Error when i try to push origin

### ISSUE THREAD

**Issue by bertil291utn** [desktop/desktop#3137]
**watch E:\WINDOWS\TEMP\GitHubDesktop-lfs-progress-AZB13v\GitHubDesktop-lfs-progress EPERM**

it Just happen when i try to push origin or fetch, but at the end the fetch or push it works, but with this issue

**Comment by shiftkey** [comment]
@bertil291utn I believe this is similar to the earlier report #3046 - could you open a ̦PowerShell prompt and run this command:

```
> Get-ChildItem Env:
```

I'm pretty sure Node is using `%TEMP%` when it creates this file, and on one of my test machines it looks like this:

```
PS C:\Users\shiftkey> Get-ChildItem Env:

Name                           Value
----                           -----
...
TEMP                           C:\Users\shiftkey\AppData\Local\Temp
TMP                            C:\Users\shiftkey\AppData\Local\Temp
...
```

We're using #3046 to track the error handling, and as a workaround you should update `%TEMP%` to a path that is writable by the current user

**Comment by shiftkey** [comment]
@bertil291utn I'm glad you were able to workaround the issue. I'll close this out and look at improving the error handling in #3046.
