### ISSUE TITLE
add right click options to files in history

### ISSUE THREAD

**Issue by gemal** [desktop/desktop#3141]
when I click the history tab it would be nice if I could right click on a changed file and select "open in default editor"

**Comment by joshaber** [comment]
Thanks @gemal! We're already tracking this in https://github.com/desktop/desktop/issues/2845. Feel free to follow along over there!

**Comment by yeliuqiang** [comment]
What kind of occupation do you have

**Comment by yeliuqiang** [comment]
can I be a member of you
