### ISSUE TITLE
Installation Error (SquirrelSetup.log)

### ISSUE THREAD

**Issue by azharhamrat** [desktop/desktop#3143]
I am using Windows 7 32-bit, always error on installation (i am using GitHubDesktopSetup.exe)
, please help, thanks
- Error log attached
[SquirrelSetup.log](https://github.com/desktop/desktop/files/1410202/SquirrelSetup.log)

**Comment by shiftkey** [comment]
@azharhamrat we don't support 32-bit versions of Windows - see #1214 for the related discussion

**Comment by azharhamrat** [comment]
thanks for the support
