### ISSUE TITLE
Fetching/Pulling Wiki Repos in Desktop Struggles

### ISSUE THREAD

**Issue by say25** [desktop/desktop#3147]
### Description
Fetching/Pulling Wiki Repos in Desktop Struggles
### Version
**GitHub Desktop version:** 1.0.4
**OS version:** Windows 10

### Steps to Reproduce

1. Clone a wiki repo.
2. Make changes somewhere else.
3. Try to pull new changes in Desktop.

**Expected behavior:** It pulls the repo.

**Actual behavior:** Nothing

**Reproduces how often:** Seem very frequent. 

### Logs
[2017-10-24.desktop.production.log](https://github.com/desktop/desktop/files/1411586/2017-10-24.desktop.production.log)

#### Additional Information

I wish I could share more its an enterprise wiki repo.

**Comment by joshaber** [comment]
Thanks @say25! We're tracking bugs around wikis in https://github.com/desktop/desktop/issues/2061 so I'm gonna close this. Feel free to follow along over there!
