### ISSUE TITLE
Linux naming

### ISSUE THREAD

**Issue by ziggy42** [desktop/desktop#3150]
### Description

In many places there's the assumption that if the OS is not macOS, then it's Windows.
An example can be found at [app/src/lib/editors/lookup.ts](https://github.com/desktop/desktop/blob/master/app/src/lib/editors/lookup.ts):
```
const menuItemName = __DARWIN__ ? 'Preferences' : 'Options'
```
I think an assumption like this one it's okay, because I'm not aware of a cross-de conventions about which name to use for settings :grin:.

But in other places, it's less great. The real "issue" for me it's "Explorer". For example, in [app/src/ui/changes/no-changes.tsx](https://github.com/desktop/desktop/blob/master/app/src/ui/changes/no-changes.tsx):
```
const opener = __DARWIN__ ? 'Finder' : 'Explorer'
```

I don't think there's a fast way to synchronously get the default file manager name on Linux. 

Visual Studio Code, for example, avoids this issue saying `Open Containing Folder`, I don't know what it shows for macOS and Windows.

Maybe `your File Manager` could be just fine.

### Version

**GitHub Desktop version:** [1.0.5-test1]

**OS version:** [Fedora 26]

### Steps to Reproduce

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by shiftkey** [comment]
:thumbsup: for making this support three platforms.

I have some ideas for introducing this but I can't get to it for a couple of days. @ziggy42 are there other examples you can spot where the Windows value doesn't match with what you'd expect?

**Comment by ziggy42** [comment]
The same "Explorer" issue can be found in `Help -> Show logs in Explorer`.
Other than that I think the Windows values are just fine.

**Comment by shiftkey** [comment]
@j-f1 had a suggestion over in https://github.com/desktop/desktop/pull/3288#issuecomment-345553422

> Alternative solution:
> 
> * Add `menus/<platform>.yml` and `labels/<platform>.yml` files with strings localized to the platform
> * Add a single global variable for each type that contains the data parsed from the appropriate file for the target platfrom
> * Write a function that loads the label from the global. Example: `s('show-in-file-manager')`.
> * [optional] add a custom ESLint rule that ensures that the files all have the same keys and that all `s()` calls return a found key. Alternatively, run a script that generates a typings file containing `export type Label = "key-one" | "key-two" | "et-cetera"` and use the Powers of TypeScript™ to check for you
>
>YAML format:
> ```yaml
> # menus/darwin.yml
> show-logs-in-file-manager: Show Logs in Finder
> show-in-file-manager: Show in Finder
> # ...
```

**Comment by joshaber** [comment]
I might be in the minority here, but I still see these solutions as heavier than the problem itself.

**Comment by niik** [comment]
> I might be in the minority here, but I still see these solutions as heavier than the problem itself. Conditionals are a bummer, but trading them for more complexity isn't a net win, I don't think.

💯 

Let's not overthink this until it becomes a problem for real (l18n). For now adding one more condition seems like the most straightforward approach to the problem that this issue is referring to.

```ts
const opener = __DARWIN__ ? 'Finder' : 
               __WINDOWS__ ? 'Explorer' :
               'your File Manager'
```
