### ISSUE TITLE
Hide menu bar in Linux

### ISSUE THREAD

**Issue by ziggy42** [desktop/desktop#3151]
### Description

The ability to hide the menu bar (as you can do in other apps, like Visual Studio Code) would be great.
GTK3 apps don't use menu bars, so in GNOME the look could be better:
![screenshot from 2017-10-24 23-40-14](https://user-images.githubusercontent.com/4258550/31969389-b6d6f3b8-b914-11e7-996a-b43cbbb210bb.png)
 

### Version

**GitHub Desktop version:** [version here]

**OS version:** [Fedora 26]

### Steps to Reproduce

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

#### Additional Information

**Comment by j-f1** [comment]
GitHub Desktop creates its own menubar on Windows. I wonder if we should do the same on Linux.

**Comment by shiftkey** [comment]
I guess we're not clear on what fits with the platform.

For reference, on Windows we run it in [frameless mode](https://electron.atom.io/docs/api/frameless-window/) (hiding the window frame and the default menu):

https://github.com/desktop/desktop/blob/d4893c7a4979cdda3beabfd380667b6b43191b78/app/src/main-process/app-window.ts#L57-L59

Then we render a menu written in HTML/JS/CSS - this also draws the minimize/maximize/close buttons in the top-right which would exist with the default window frame.

<img width="1003" src="https://user-images.githubusercontent.com/359239/31971733-c670a7fc-b968-11e7-9c6d-f806662d3266.png">

Happy to add additional insight into what we're doing here, if someone is keen to figure what makes sense for Linux users.

**Comment by ziggy42** [comment]
Honestly I don't think that would work well on Linux. 
Just to pick GNOME as an example, by default you have only the close button in the right corner. But you can move the corner and add minimize or maximize.

Having one custom menubar that looks well on every Linux DE, or even just the most popular ones, would be very difficult.

I wouldn't mind to just show/hide the menubar like vscode and slack do. Also because I tend to use keyboard shortcuts anyway :smile:

**Comment by ziggy42** [comment]
![screenshot from 2017-10-25 21-26-51](https://user-images.githubusercontent.com/4258550/32018782-40503954-b9cb-11e7-9e2c-9ae4e0583bc3.png)

**Comment by shiftkey** [comment]
> I wouldn't mind to just show/hide the menubar like vscode and slack do. 

For reference, **Toggle Menu bar** is under the **View** menu:

<img width="552" src="https://user-images.githubusercontent.com/359239/32027569-80b677a0-ba35-11e7-8d59-6720f6894578.png">

You'll then see this message:

<img width="1049" src="https://user-images.githubusercontent.com/359239/32027589-97ccc836-ba35-11e7-82ee-1eef298f0186.png">

And it now looks like this:

<img width="1044" src="https://user-images.githubusercontent.com/359239/32027634-d0053990-ba35-11e7-8186-ef4605e65c0b.png">

**Comment by shiftkey** [comment]
I'm going to mark this as `help wanted` and add some guidance here for someone who wants to dig into this:

  - we can probably see what VSCode does here, if someone wants to go digging into how they control Electron
  - [`app-window`](https://github.com/desktop/desktop/blob/master/app/src/main-process/app-window.ts) is where we set the Electron options for the window, and handle some events
  - [`build-default-menu.ts`](https://github.com/desktop/desktop/blob/master/app/src/main-process/menu/build-default-menu.ts) is how we build the menu - we'll need a new entry here for **Toggle Menu Bar** that acts like a checkbox.

I'm not sure what events we need to propagate around, but I'm happy to look at some code and help figure this out.

**Comment by ziggy42** [comment]
This can be done really easily with [this](https://electron.atom.io/docs/api/browser-window/#winsetmenubarvisibilityvisible-windows-linux) API.

But I'm not sure how to notify the user like `code` does.

**Comment by shiftkey** [comment]
> But I'm not sure how to notify the user like `code` does.

The closest thing I can think of is our zoom indicator, which displays in the center of the screen:

<img width="975" alt="screen shot 2017-11-08 at 9 31 17 am" src="https://user-images.githubusercontent.com/359239/32521453-acf99f90-c467-11e7-9ebb-4e24a9521166.png">

We might be able to repurpose some of it. I'll add `needs-design-input` here to get some UX feedback whenever they have bandwidth - let's not hold up the rest of the work in the meantime.

**Comment by outofambit** [comment]
closing this since linux isn't supported and this has gone almost two years without activity
