### ISSUE TITLE
Git credentials not found when checking out a remote branch with lfs-tracked files in private repo

### ISSUE THREAD

**Issue by zvinless** [desktop/desktop#3155]
### Description
I get an `Error` popup stating that Git credentials were not found when checking out a remote branch with lfs-tracked files in a private repository. The issue goes away once a credential helper is configured in the global git config, i.e. after executing `git config --global credential.helper osxkeychain`

### Version
**GitHub Desktop version:** 1.0.4
**OS version:** macOS High Sierra 10.13

### Steps to Reproduce

1. Create a private git repository on GitHub and init with readme
1. Clone it using the command line
1. Initialize git-lfs for the repository
1. Track "*.jpg" in lfs
1. Commit a .jpg file to the master branch
1. Create a new branch
1. Commit another .jpg to this new branch
1. Push everything up to GitHub
1. On another computer, clone the repo using GitHub Desktop
1. Switch branches to the branch created earlier
1. Observer `Error` popup
1. Dismiss the popup
1. Execute `git config --global credential.helper osxkeychain` in Terminal
1. Try to switch branches again
1. Observe prompt to allow `git-credential-osxkeychain` to use your info stored in github.com
1. Allow
1. Observe that the checkout works now

I created a private test repo on my own account to reproduce (the bulk of the steps to reproduce). If someone wants to become a collaborator to try to repro I'd be happy to set that up.

<img width="962" alt="checkout" src="https://user-images.githubusercontent.com/24303763/31981413-fd370cec-b907-11e7-8ea2-59f0db61917b.png">

**Expected behavior:** The branch is checked out and uses the same credentials that other operations use. I would also expect GitHub Desktop to ignore any external git configuration; I was under the impression that it did all of its own credential stuff

**Actual behavior:** The checkout fails on the first lfs-tracked file with an error popup. Once the credential helper is configured, it seems that GitHub Desktop uses that

**Reproduces how often:** seems to be either 100% or 0%, depending on the configuration

### Logs
[2017-10-25.desktop.production.log](https://github.com/desktop/desktop/files/1413321/2017-10-25.desktop.production.log)

#### Additional Information
- I haven't had any issues when using the fetch/pull button; it seems to only be when checking out a branch
- I have only reproduced this with a private repository
- I have only reproduced this on user accounts WITHOUT a global git credential helper set
    - Once this is set to `osxkeychain`, I get an OS prompt to allow GitHub Desktop to use my keychain and things work as expected
- I have reproduced this using accounts that both do and do not require two-factor authentication

**Comment by joshaber** [comment]
Thanks for opening this @zvinless! It sounds like we're not properly authenticating when switching branches. We'll dig into it.
