### ISSUE TITLE
Unable to sync repositories using GitHub Desktop: fatal error 0x80092012

### ISSUE THREAD

**Issue by askbow** [desktop/desktop#3156]
### Description
Hi
I was trying to use GitHub Desktop to work with my repos, but I get an error like this (when cloning from or publishing to new repos):

fatal: unable to access 'https://github.com/askbow/contact-expand.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - ������� ������ �� ������ ���������� �������� ������ ��� �����������.

### Version

**GitHub Desktop version:** 1.0.4

**OS version:** Microsoft Windows [Version 6.1.7601]

### Steps to Reproduce

1. create new repo in the application
2. add files
3. commit
4. press "publish"

**Expected behavior:** the repo syncs up to Github

**Actual behavior:** Unknown error (0x80092012)

**Reproduces how often:** everytime

### Logs

`2017-10-25T08:40:09.832Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: contact-expand - askbow (has token)
2017-10-25T08:40:10.404Z - error: [ui] `git -c credential.helper= push origin master --set-upstream --progress` exited with an unexpected code: 128.
fatal: unable to access 'https://github.com/askbow/contact-expand.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - ������� ������ �� ������ ���������� �������� ������ ��� �����������.`

#### Additional Information

I tried to curl the URI in the error, and I get this:
`>curl https://github.com/askbow/contact-expand.git/
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>`

**Comment by joshaber** [comment]
Hi @askbow!

We've had a few reports of this specific error, but it's not been made clear to me how we might be misusing the SChannel APIs, so the best advice I have for you is how to switch over to using the classic OpenSSL APIs alongside your own certificate bundle.

Open a shell to your repository and run these command:

```sh
$ git config --local http.sslBackend "openssl"
$ git config --local http.sslCAInfo [path to .pem file]
```

Then test it out with a `git fetch` to ensure it is able to connect to your server.

**Comment by askbow** [comment]
@joshaber 
Thanks for the advice!

As I'm currently facing this issue, would taking any additional info / logs be helpful?

Before I change the settings, I mean.

**Comment by joshaber** [comment]
That is a great question and one I'll have to defer to @shiftkey on.

**Comment by shiftkey** [comment]
@askbow @joshaber I'd love to understand which programs are interfering with SChannel in this way, so I can experiment with this to understand it better - do you know which software on your machine might be to blame?

**Comment by askbow** [comment]
Looks like I found it! TL;DR: The conflict in my case is with CryptoPro CSP.

At first I tried to catch the event in sysinternals process monitor, but that gave nothing. I also tried to kill other processes in my system one-by-one to find who might be messing with this API, again no results.

Then I googled a little and found that this error code for SChannel has more than one mention on github issues pages for different projects. [Here](https://github.com/steffengy/schannel-rs/issues/13) the error is described as 
> CRYPT_E_NO_REVOCATION_CHECK 0x80092012 The revocation function was unable to check revocation for the certificate. 

This pinged in my head: I already had a weird certificate problem with my jabber program last spring. The problem back then was with [CryptoPro CSP](https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fwww.cryptopro.ru%2Fproducts%2Fcsp&edit-text=) - a Russian GOST crypto library. Specifically, I have to use version 3.6 R4.

I uninstalled it, and GitHub desktop started syncing alright.

**Comment by askbow** [comment]
Confirmed it by installing the crypto provider back. This breaks desktop operation as I described above.

On [their support forum](https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=https%3A%2F%2Fwww.cryptopro.ru%2Fforum2%2Fdefault.aspx%3Fg%3Dposts%26m%3D66918) I found a workaround: disable validation by setting DWORD `HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\SecurityProviders\SCHANNEL\ManualCredValidation`  to 1.

Probably not best practice, but will work for the time being.

**Comment by shiftkey** [comment]
@askbow thanks for following up! I'll close this out given we know at least one scenario (and how to workaround it).

**Comment by ACEM7777** [comment]
please the error message attached no idea on how to resolve it. OS Window 8.1 64

![image](https://user-images.githubusercontent.com/29448365/36376833-9c7e4a82-15af-11e8-834b-fbb15034e923.png)
![github cloning error message](https://user-images.githubusercontent.com/29448365/36376903-e6250b08-15af-11e8-9d8b-1c57734aa474.png)

**Comment by demix506** [comment]
Nice. im fix its problem, down Kaspersiky
