### ISSUE TITLE
log-in prompt pop-up does not go away

### ISSUE THREAD

**Issue by JMangiafesto** [desktop/desktop#3158]
### Description

log-in requests via pop-up. Will not permanently go away when logged on, or when form is filled out.

### Version

**GitHub Desktop version:** 1.0.3 (updated to 1.04- latest, same issue)

**OS version:** 10.0.15063

'Windows 10 pro' version 1703 (according to settings)

### Steps to Reproduce

1. open GIT desktop

**Expected behavior:** 
No pop-ups

**Actual behavior:**
pop-ups requesting to log-in, anytime program is open. Anywhere between 1 and 3 pop ups will be open at a given time.

**Reproduces how often:**
100%, and when I fill out the form (by logging on through the pop-up) the pop-up is replaced seconds later, more often than not two pop-ups exist at any given time, and both will re-open upon being closed.

#### Additional Information
Logged-on, submitting pull requests and merging from master perfectly fine, it's not a functionality block, nor are there any log-in issues

<img width="340" alt="git_logged_on" src="https://user-images.githubusercontent.com/25746236/31775811-a133c0e2-b4b7-11e7-924a-bd8430771703.PNG">

<img width="611" alt="git log-in requests" src="https://user-images.githubusercontent.com/25746236/31775812-a1440d4e-b4b7-11e7-86e3-ea9a5f4d7d08.PNG">

I understand that this is possibly an isolated incident, and I only have this issue on one machine, logging in on other PC's doesn't cause the issue to surface. But it's happening on this machine consistently, not sure if there are caching issues or a compatibility problem between the exact GIT/OS versions.

**Comment by joshaber** [comment]
When exactly does that dialog pop up? When you launch the app? When you push or pull?

The dialog itself isn't coming from GitHub Desktop, but from the [Git Credentials Manager for Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows). But I wonder if there's something GitHub Desktop is doing that's causing the dialog to appear.

**Comment by JMangiafesto** [comment]
Bringing up GIT credentials manager- I would like to note that I am using Visual Studio Code as an IDE integrated with my GIT folders. I only assumed it may be a desktop issue due to the icon similarity (black octo-cat).

After further exploration it seems more strictly tied to VSC being open, rather than GIT desktop.
