### ISSUE TITLE
Unable to clone/push/pull from cmd neither github client

### ISSUE THREAD

**Issue by AzgadGZ** [desktop/desktop#3165]
Hi All,

From one day to another I received the issue mentioned below, I didn't change anything related to git neither to SSL or something, any idea what's the issue related? (Im using git over Windows 10)

>git clone https://github.com/AzgadGZ/CommunityPolice_Android.git
Cloning into 'CommunityPolice_Android'...
fatal: unable to access 'https://github.com/AzgadGZ/CommunityPolice_Android.git/': error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied

Git version: git version 2.14.3.windows.1
Windows build: Windows 10, version 1607, OS Build 14393.1066.

**Comment by shiftkey** [comment]
@AzgadGZ it's not clear which version of Git or which build of Windows you are using. Without those it's not really clear where to start troubleshooting beyond Googling for the error message (seems to be related to the version of OpenSSL you are using).

**Comment by AzgadGZ** [comment]
Hi @shiftkey,

Here's the info:

Git version: git version 2.14.3.windows.1
Windows build: Windows 10, version 1607, OS Build 14393.1066.

**Comment by shiftkey** [comment]
@AzgadGZ thanks for that extra details. There are lots of similar reports about "alert access denied" being related to being behind a proxy server - is that something you have to configure to work with Git repositories? Could something have changed recently?

**Comment by AzgadGZ** [comment]
@shiftkey nothing changed recently, i was pushing like a manic one day :P and the day after i wan't unable to do anything related to git

**Comment by shiftkey** [comment]
@AzgadGZ while GitHub Desktop does embed it's own version of Git, all the information here suggests this is related to [Git for Windows](https://git-for-windows.github.io/) and is reproducible.

I've still not been able to reproduce this, so I'd recommend opening an issue over on [their repository](https://github.com/git-for-windows/git/issues) and filling out their issue template. You'll likely get a quicker answer there about what it might be.

**Comment by ajibs** [comment]
Hey guys,

I had this same problem while pulling code from github on my Visual studio code terminal. I found the advice above useful and hacked a solution together following the steps below: 

- I [updated Git][1]. 
- I [updated Git Credential Manager for Windows][2]
- Made some [changes to the registry][3]
- Updated my Visual studio code to the latest version
- Changed my Windows Path for Git from `C:\Program Files (x86)\Git\bin.` Changed it to `C:\Program Files\Git\bin`

[This repo][4] was quite useful.


  [1]: https://git-scm.com/download/win
  [2]: https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases/tag/v1.14.0
  [3]: https://developercommunity.visualstudio.com/content/problem/201457/unable-to-connect-to-github-due-to-tls-12-only-cha.html
  [4]: https://github.com/Microsoft/Git-Credential-Manager-for-Windows

**Comment by wowkin2** [comment]
Had similar error:
`error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version`
Just reinstalled Git and that fixed the issue.

:pushpin: And after installation Path to Git was changed from
`C:\Program Files (x86)\Git\cmd\git.exe`
to
`C:\Program Files\Git\bin\git.exe`

**Comment by somexp** [comment]
I also received an issue similar to what is here. As wowkin2 had: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version. Happened whenever I tried to pull or push, though local commands (add, commit) functioned just fine.

I had GIT 1.9 . . . something

The solution was simply to uninstall GIT and reinstall the new version. I did not do anything else.

**Comment by SINGHPRT** [comment]
While connecting to remote repository to fetch/pull/push etc., had the same error:

fatal: unable to access 'https://github.com/repository.git/': error:1
407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Just reinstalled Git 64-bit in place of 32-bit and that fixed the issue.

After installation, verify the GIT path in Environment variables, it should be: C:\Program Files\Git\bin\git.exe

**Comment by shiftkey** [comment]
I'm going to lock this issue as the recent comments here are related to either [Git for Windows](https://github.com/git-for-windows/git) or [Git Credential Manager for Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows#notice-experiencing-github-pushfetch-problems), which required updating your tools as [GitHub switched off TLS 1.0 and 1.1 support recently](https://blog.github.com/2018-02-23-weak-cryptographic-standards-removed/).
