### ISSUE TITLE
Branches are not displayed in the branches dropdown menu

### ISSUE THREAD

**Issue by neakor** [desktop/desktop#3169]
### Description

As the title says, the branches dropdown menu doesn't display anything but the current branch, a filter text box and a new button. There's no way to switch branches.

### Version

**GitHub Desktop version:** [1.0.5]

**OS version:** [macOS 10.12.6]

### Steps to Reproduce

1. Have multiple branches.
1. Tap on the branches dropdown menu.

**Expected behavior:** [Dropdown menu displays all the branches like the previous version.]

**Actual behavior:** [No branches are displayed.]

**Reproduces how often:** [100% of the time]

**Comment by jgranzow86** [comment]
This issue is present for myself as well.

**GitHub Desktop version:** [1.0.5]
**OS Version:** [macOS 10.13]

I found I am able to type the name of the branch in the filter field then hit enter and it will switch to that branch. No branches show up while typing.

**Comment by kellpossible** [comment]
I also have a similar, perhaps slightly unrelated problem, it only happens for local repositories which have not been pushed to/exist on github.

**GitHub Desktop version:** [1.0.5]
**OS Version:** [Windows 10]

**Comment by shiftkey** [comment]
@kellpossible @jgranzow86 @neakor is there a public repository we can use to test this on our end? This will help speed up troubleshooting.

**Comment by kellpossible** [comment]
@shiftkey I can't share most of them, but one of them is:
http://git.blender.org/cycles.git

Typing part of the name of the branch and hitting enter switches to what a presume would be the first branch in the list, but the list is not shown.
![image](https://user-images.githubusercontent.com/4527338/32087760-dc711e48-bb29-11e7-81ee-e8746d791ba7.png)

Here, without any text in the filter, none of the branches are shown
![image](https://user-images.githubusercontent.com/4527338/32087768-eaacc674-bb29-11e7-88e4-d98bc9771768.png)

**Comment by sharun-gft** [comment]
I am able to reproduce this issue. I have a non-github repository in my case.

**Comment by tierninho** [comment]
Confirming the issue is reproducible in the sample repo provided (http://git.blender.org/cycles.git). No relevant logs found.

**Temporary Workaround**: just type the name of the branch you want to switch to in the branch filter and click `Enter`, and the branch will switch.

**Comment by shiftkey** [comment]
@kellpossible @tierninho yep, I can reproduce this as well using that repository. Looks like something has changed with the output from `git for-each-ref` that we use to generate this list of branches when we updated Git in #3146

**Comment by kevindalmeijer** [comment]
I am having the exact same problem as neakor. Same version of GitHub Desktop, but on Windows 10.

The problem appears when creating a new local repo and adding branches, without publishing to GitHub.

**Comment by shiftkey** [comment]
We've done some work in here to show pull requests alongside branches, so maybe that's introduced something, and the best lead that I have is that deep inside `list.tsx` we have a zero `rowCount` props:

<img width="952" src="https://user-images.githubusercontent.com/359239/32095716-cb69fe14-bb4f-11e7-93fa-aa595f29183a.png">

[Here's the diff between this release and the last one](https://github.com/desktop/desktop/compare/release-1.0.4...release-1.0.5) - I haven't spotted the issue yet, but given this is related to a non-GitHub repository I'd be looking at how we changed up the `render` method in `app/src/ui/branches/index.tsx`:

<img width="649" src="https://user-images.githubusercontent.com/359239/32095967-b7c3777c-bb50-11e7-99e0-b9633f3d8933.png">

**Comment by tierninho** [comment]
> The problem appears when creating a new local repo and adding branches, without publishing to GitHub.

Noticed that publishing the branch resolves the problem. By no means is this a solution... just an observation made while triaging.

**Comment by zainullinramil** [comment]
This issue is present for myself as well.

GitHub Desktop version: [1.0.5]
OS Version: [macOS 10.13]

**Comment by joshaber** [comment]
We just released 1.0.6 which should fix this. Sorry for the hassle everyone!

**Comment by j-greig** [comment]
I'm having this problem again on 1.0.12 / macOS 10.12.6

**Comment by shiftkey** [comment]
@j-greig please open a fresh issue with repro steps

**Comment by arshpreetsingh** [comment]
I am hang the same Problem with my Mac as well.

**Comment by shiftkey** [comment]
@arshpreetsingh please open a new [bug report](https://github.com/desktop/desktop/issues/new?template=bug_report.md) and fill out the issue template so that we're better able to help you.

**Comment by mtcls** [comment]
I faced the same issue.

Switched to `develop` and clicked `Fetch origin`, turns out my session was expired. After login I'm able to see current branches.

**Comment by sfksuperman** [comment]
I'm facing the same issue in v3.1.2 <stable release>. Please fix this!

**Comment by eyucherin** [comment]
Also facing the same issue

**Comment by Reqrefusion** [comment]
Same

**Comment by yeasinx** [comment]
Has the issue hasn't been fixed yet?

**Comment by Reqrefusion** [comment]
> Has the issue hasn't been fixed yet?

Yes

**Comment by VishalPatel9921** [comment]
in my account i have create repository and i have go in setting but in side the setting not showing branch option

**Comment by VishalPatel9921** [comment]
![Screenshot 2024-08-23 134551](https://github.com/user-attachments/assets/a968d395-0e14-4f3d-ba4d-f62c67b7f7de)
![Screenshot 2024-08-23 134551](https://github.com/user-attachments/assets/a3a85cb5-103e-4ead-9ff3-67844447c7ad)
