### ISSUE TITLE
show proper LFS progress

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#3171]
We made a bunch of progress in https://github.com/desktop/desktop/pull/2355 to get the raw LFS progress information in the app. But it's currently just the raw progress, it'd be good to get this information flowing through to the progress side:

 - clone progress bar will fetch LFS assets after
 - checkout progress can include downloading LFS assets
 - fetch/push/pull also

**Comment by joshaber** [comment]
Note that there's an open design question https://github.com/desktop/desktop/pull/2355#issuecomment-330539841:

>I've also run into a new and exciting UX problem.
>
>`lfs clone` downloads files in parallel for ✨  **_super performance_** ✨ But this means it's really hard to show the user a unified, reliable progress bar. File X might be 50% done while File Y is 1% done.
>
>We could show progress in terms of how many files are downloaded (that'd be blocked on https://github.com/git-lfs/git-lfs/issues/2599), but that'll be a little misleading, e.g., if we've downloaded all the small files but have 2 huge files left.

**Comment by delucis** [comment]
Will this include showing upload progress when publishing a new repo? Currently a slow LFS upload doesn’t seem to trigger anything more than the standard rotating arrows to show that publishing is in progress:

![Publishing Repository indicator](https://user-images.githubusercontent.com/357379/32901208-9868db16-caef-11e7-98da-ddf16d0300d1.png)

**Comment by j-f1** [comment]
What version of Desktop are you running @delucis?

**Comment by delucis** [comment]
I just updated to 1.0.9 and I see now although there’s no indicator in the publish modal itself, the progress is shown below “Pushing to origin” in the top bar.

![screen shot 2017-11-17 at 0 56 20](https://user-images.githubusercontent.com/357379/32922378-3cdbb5aa-cb32-11e7-8697-d22b855d44d9.png)

My bad, sorry!

**Comment by simonseyer** [comment]
![untitled](https://user-images.githubusercontent.com/571090/40829693-86b376e4-6584-11e8-851c-76143c38cfee.gif)

When many files are uploaded the file progress is not consistent. As a quick win it may be possible to:
* Only change the currently processed file number when it is larger than the one before (1/84 -> 30/84 but don't jump back to 1/84)
* Show the uploaded file size in MB instead of bytes

**Comment by simonseyer** [comment]
I just pushed via the command line and the output was pretty perfect: `Git LFS: (4 of 225 files) 75.54 MB / 1.37 GB`. Couldn't this output be shown in the UI?

**Comment by billygriffin** [comment]
Sorry for the delay here. @ampinsk and I discussed this this morning and we both agree that @simonseyer's suggestion to leverage the output displayed on the command line seems totally reasonable. I'm tagging as help wanted to indicate that we'd love for a community contributor to give it a go. Thanks for all the input!
