### ISSUE TITLE
Sorry,I can not see my any other branches.

### ISSUE THREAD

**Issue by wuzh1014** [desktop/desktop#3176]
### Description
I can not see my any other branches.
[
![image](https://user-images.githubusercontent.com/6696819/32094140-5a668962-bb31-11e7-9c0e-b6d9646d54b7.png)
]
Only can I switch the branch by typing and clicking.Too troubles.

### Version

**GitHub Desktop version:** [latest 1.0.5]

**OS version:** [win10]

### Steps to Reproduce

1. [update]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by filipsobol** [comment]
Duplicate of https://github.com/desktop/desktop/issues/3169

**Comment by wuzh1014** [comment]
sorry Duplicate of #3169
