### ISSUE TITLE
All branches missing on branch select screen

### ISSUE THREAD

**Issue by anakinjay** [desktop/desktop#3180]
### Description
When I click the drop down to select a branch, no branches display.  If I manually type in a branch name that I know exists into the filter box and hit enter, it does switch to the correct branch, but there's no ability to see what branches are available.

### Version

**GitHub Desktop version:** 1.0.5
**OS version:** Mac OS Sierra 10.12.6

### Steps to Reproduce

1. Added a local repo
2. Clicked the drop down under current branch
3. no branches display

**Expected behavior:** I expected a list of branches to display

**Actual behavior:** no branches displayed

**Reproduces how often:** 100%

### Logs
[2017-10-27.desktop.production.log](https://github.com/desktop/desktop/files/1422031/2017-10-27.desktop.production.log)

**Comment by joshaber** [comment]
Hi @anakinjay, we just released 1.0.6 which should fix this. Sorry for the hassle!
