### ISSUE TITLE
unable to push from desktop

### ISSUE THREAD

**Issue by fr51** [desktop/desktop#3182]
### Description

Since this afternoon, I can't push to origin anymore. GitHub Desktop says I don't have the permission to access my folder, but I'm the owner and only contributor of this folder.

Moreover, I've checked I'm logged in my GitHub account.

### Version

**GitHub Desktop version:** 1.0.6

**OS version:** 10.0.15063

### Steps to Reproduce

1. commit
2. push to origin

**Expected behavior:** files pushed to origin

**Actual behavior:** authentication fails and the files are not pushed to origin

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by joshaber** [comment]
Hi @fr51! Could you please attach the most recent log file from `%APPDATA%\GitHub Desktop\logs\*.desktop.production.log`. Thanks!

**Comment by fr51** [comment]
[2017-10-27.desktop.production.log](https://github.com/desktop/desktop/files/1423435/2017-10-27.desktop.production.log)

Hi @joshaber, here's the log

**Comment by joshaber** [comment]
Thanks @fr51!

As best as I can tell from the log, it looks like pushing succeeds:

```
2017-10-27T18:07:45.443Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 1.239s)
```

But pulling fails:

```
error: [ui] `git -c credential.helper= pull --no-rebase --progress origin` exited with an unexpected code: 1.
Auto-merging WebContent/WEB-INF/web.xml
CONFLICT (content): Merge conflict in WebContent/WEB-INF/web.xml
Automatic merge failed; fix conflicts and then commit the result.

(The error was parsed as 7: We found some conflicts while trying to merge. Please resolve the conflicts and commit the changes.)
```

Is that error being surfaced in the UI? Could you paste a screenshot in here?

**Comment by fr51** [comment]
Hi Josh,

the error about merging isn't so important. It was a try with manual uploading; I know how to fix it, and it occured after the pulling issue.

![authentication](https://user-images.githubusercontent.com/11518598/32283602-1f343824-bf25-11e7-803d-55741bb267bb.jpg)

**Comment by niik** [comment]
Hey  @fr51. Could you attach the log file for the date when you saw that dialog. I'm not seeing anything in the log file that you submitted earlier that correlates to that dialog.

**Comment by fr51** [comment]
Hi @niik,

here's today's log
[2017-11-02.desktop.production.log](https://github.com/desktop/desktop/files/1437449/2017-11-02.desktop.production.log)

In addition, my today's commits are mentioned in desktop but not in my repo on GitHub.

**Comment by fr51** [comment]
one more thing : I can publish a new repo, but not master branche

**Comment by niik** [comment]
I've been looking for an error in these logs but it turns out [we don't treat auth errors as errors](https://github.com/desktop/desktop/blob/master/app/src/lib/git/push.ts#L59) so the log will never show them.

@desktop/core any good ideas on how we can troubleshoot this further?

**Comment by joshaber** [comment]
>one more thing : I can publish a new repo, but not master branche

Can you push new branches?

**Comment by fr51** [comment]
Nope, I can create it but not push.

**Comment by shiftkey** [comment]
> one more thing : I can publish a new repo, but not master branche

This is really interesting, because these two scenarios are slightly different:

 - publishing a new repository uses `api.github.com`, a token created by Desktop as part of the OAuth dance, and potentially proxy settings defined by the OS
 - pushing commits uses `github.com`, the same token created by Desktop and proxy settings defined by Git (long story)

@fr51 have you been able to push branches using command line [Git for Windows](https://git-for-windows.github.io/)? It will probably require you to authenticate, but if it also fails there then maybe it's something network-related that's blocking the push?

If no `origin` remote has been added, you'll also need to do this:

```
git remote add origin [url]
```

**Comment by whackdev** [comment]
I am having this issue as well. I have confirmed my Git settings are the same I use on the GitHub website. I just started using Git on Windows so I thought I was doing it wrong. I searched my issue and saw that GitHub Desktop is the preferred method so I downloaded version 1.0.8 this evening and followed the configuration steps and double checked them in cmd. 

I receive this error in the log when I try:
[2017-11-08.desktop.production.log](https://github.com/desktop/desktop/files/1452548/2017-11-08.desktop.production.log)

**Comment by fr51** [comment]
@shiftkey I'll answer you once I'll make a try this weeekend.

**Comment by joshaber** [comment]
Whoops, looks like our bot got a little too aggressive. Re-opening.

**Comment by fr51** [comment]
Hi again @shiftkey,

I've just installed Git Bash and successfully commited and pushed into the new branch (called "branche") I created two weeks ago.

Now I'd like to transfer the content from _branche_ to _origin_ and delete _branch_

**Comment by joshaber** [comment]
@fr51 You can merge branches by checking out `origin` and then going up to the "Branch" menu and selecting "Merge into current branch…".

Is the original issue solved?

**Comment by fr51** [comment]
@joshaber

Thanks for the tip.

The command line works fine, but the issue's still there in GitHub Desktop

**Comment by joshaber** [comment]
Just to be thorough, could you try logging out and back in to see if that fixes it?

**Comment by fr51** [comment]
No, the issue's still there

**Comment by joshaber** [comment]
@fr51 Specifically what repository are you trying to push to?

**Comment by fr51** [comment]
My repo's called _gestion_banque_JPA_

**Comment by joshaber** [comment]
It looks like that repository was just created, so the failure to authenticate previously is to be expected. We can't easily differentiate between repositories to which you don't have access and repositories which don't exist.

**Comment by fr51** [comment]
We can close the issue because I've successfully pushed a new branch w/ Git GUI.

So, I'll uninstall GitHub Desktop and keep Git GUI.
