### ISSUE TITLE
Automatic stashing before switching

### ISSUE THREAD

**Issue by bfred-it** [desktop/desktop#3185]
### Description

New feature (used to be in GH for Mac):

Automatically stash changes before switching branch. This helps me preserve changes I'm not ready to commit.

### Version

**GitHub Desktop version:** 1.0.5
**OS version:** macOS 10.13

### Steps to Reproduce

1. Be on `branch-a`
1. Make changes without committing
1. Switch to other `branch-b`

**Expected behavior:** Changes should be preserved on `branch-b` (via automatic stashing)

**Actual behavior:** 
```
error: Your local changes to the following files would be overwritten by checkout:`
	your-file.ext
Please commit your changes or stash them before you switch branches.
Aborting
```

**Comment by shiftkey** [comment]
@bfred-it thanks for the feedback. Please follow along with the earlier request for this: #1633

**Comment by bfred-it** [comment]
Ah thanks, I couldn't find it
