### ISSUE TITLE
Github desktop  Window is transparent when trying to open from desktop 

### ISSUE THREAD

**Issue by praveen2710** [desktop/desktop#3187]
### Description

When trying to open Github desktop in shows up in taskbar but nothing is visible on the screen when trying to focus on it I can see a outline of the window it should open but it is completely transparent 

### Version

**GitHub Desktop version:**  Cannot tell since the main window will not open but I tried installing latest version and still seeing issue

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Install Github windows
1. Double click on shortcut icon desktop

**Expected behavior:** I expected to see the github desktop application

**Actual behavior:** Nothing happens 

**Reproduces how often:** 100% of the time

**Comment by praveen2710** [comment]
![github desktop 1](https://user-images.githubusercontent.com/5807651/32137781-0931b38a-bbec-11e7-9273-dbc1c16ecdd5.png)
![github desktop 2](https://user-images.githubusercontent.com/5807651/32137797-4bb820b8-bbec-11e7-9393-c54dacd9844c.PNG)

I would expect the github desktop to show but nothing shows up

**Comment by niik** [comment]
Hi @praveen2710, is it possible that you're using (or have used) multiple monitors on your machine? This sounds very much like https://github.com/desktop/desktop/issues/2107.

There's some workarounds in that thread that you can try (maximizing the window through task manager) or you could try closing GitHub Desktop, deleting `%APPDATA%\GitHub Desktop\window-state.json` and then restarting it.
