### ISSUE TITLE
Dark menu bar blends into Visual Studio

### ISSUE THREAD

**Issue by whatllb** [desktop/desktop#3189]
### Description

The dark menu bar blends with the title/menu bar of Visual Studio 2015. Depending on window positions and monitor settings, it can be VERY difficult to find the top of the Github window (one of my monitors is set a *little bit* darker than the other). More often than I'd expect, with I accidentally click Visual Studio when I want to move the GitHub Desktop window.

Side note: There is a color blending issue, but also GitHub does not have the usual Windows title bar, which makes window border distinction more important. Visual Studio puts a lighter border on its own window borders to help alleviate its own overlap/blending issues.

Common use case: Visual Studio is usually maximized, and GitHub Desktop is not. That means GitHub Desktop is usually on top of Visual Studio.

Here's github desktop over and beside Visual Studio 2015 windows:

![image](https://user-images.githubusercontent.com/28312128/32140086-6bb34918-bc2a-11e7-97b9-778a7c4edc20.png)

**OS version:** Windows 10 64-bit
Visual Studio 2015

**Comment by donokuda** [comment]
> Side note: There is a color blending issue, but also GitHub does not have the usual Windows title bar, which makes window border distinction more important. Visual Studio puts a lighter border on its own window borders to help alleviate its own overlap/blending issues.

I'm 👍 with adding a border to the Desktop interface. A couple of candidates for color that would work well for the border:

`$blue-600`:

<img width="983" alt="screen shot 2017-12-11 at 9 31 35 am" src="https://user-images.githubusercontent.com/1174461/33844789-40f81188-de56-11e7-9490-f6464958ad55.png">

`$gray-700`:

<img width="979" alt="screen shot 2017-12-11 at 9 29 13 am" src="https://user-images.githubusercontent.com/1174461/33844790-410ee926-de56-11e7-98cf-8feac70268cd.png">

Would love any thoughts on whether we should have a border show all the time or only when Desktop is active. If we decide on having a border appear all the time, we could use `$gray-700` for when Desktop isn't in focus and `$blue-600` for when Desktop is in focus.

**Comment by j-f1** [comment]
I feel like the blue color draws too much attention to the border, since links and buttons are also that color. The gray seems to fit in better with the grayscale theme of the non-interactive elements, and it also stands out on a black background.

Just for the sake of curiosity, what does Visual Studio use for its border?

**Comment by donokuda** [comment]
> I feel like the blue color draws too much attention to the border, since links and buttons are also that color. The gray seems to fit in better with the grayscale theme of the non-interactive elements, and it also stands out on a black background.

Yeah, we could also consider using a darker blue to not draw as much attention.

> Just for the sake of curiosity, what does Visual Studio use for its border?

The border that's used in Visual Studio depends on the theme that's being used:

**Light** (Looks like gray)

<img width="568" alt="screen shot 2017-12-11 at 9 48 33 am" src="https://user-images.githubusercontent.com/1174461/33845788-6f01e808-de59-11e7-84a8-6628332b6d06.png">

**Blue**  (Looks like a dark gray or black)

<img width="527" alt="screen shot 2017-12-11 at 9 48 02 am" src="https://user-images.githubusercontent.com/1174461/33845789-6f17c2d6-de59-11e7-9dc5-4abfa0e42c0d.png">

**Dark** (Purple border)

<img width="549" alt="screen shot 2017-12-11 at 9 46 56 am" src="https://user-images.githubusercontent.com/1174461/33845944-eebe32b8-de59-11e7-8bcc-b7eee70efe3f.png">

It also looks like the borders switch between a "focused" and "blurred" state (for example, this is the dark theme blurred / out of focus):

<img width="563" alt="screen shot 2017-12-11 at 9 49 21 am" src="https://user-images.githubusercontent.com/1174461/33845977-063cff14-de5a-11e7-8fb0-9d1c3ad7935f.png">

Last thing to note is that the borders are more like `0.5px` than `1px` on high resolution screens.

**Comment by whatllb** [comment]
BTW, I'm pretty sure I've got the default theme (dark) set for Visual Studio.

**Comment by atifsyedali** [comment]
On OSX, the title bar is unnoticeable. I am often trying to grab the black bar that contains the repository picker/branch picker to try to move the window, because the title bar has
1. No title text
2. Blends into the repository picker bar
3. Blends into the background.

Can we do a normal OSX title bar colour? The black titlebar looks very odd.

![image](https://user-images.githubusercontent.com/8594685/35225064-4455f78a-ff55-11e7-9204-ff228a320ce3.png)

**Comment by donokuda** [comment]
@atifsyedali We don't have plans to update the title bar color; however, letting you drag around the app when the mouse is held down on the toolbar might solve your problem. At the very least, the right side of the toolbar (the empty space after the "Fetch/Push/Pull" button) should be draggable.

**Comment by j-f1** [comment]
@donokuda What do you think about using the inset title bar style and moving the toolbar buttons to the title bar?

**Comment by atifsyedali** [comment]
Honestly I am ok with @donokuda <https://github.com/donokuda>'s suggestion
to make the toolbar draggable. It sounds easy enough to do and takes care
of the usability problem.

**Comment by donokuda** [comment]
> @donokuda What do you think about using the inset title bar style and moving the toolbar buttons to the title bar?

This was something @niik and I explored a while back and didn't care for how it looked.

**Comment by SleepyJay** [comment]
Why are you so dead set against making the title bar a standard OSX color (on OSX)? We are OSX users for consistency. ;)  Right now, it hardly registers as a title bar at all, given that EVERY OTHER window I have open in OSX is grey-ish. It's really off-putting and it makes my eyes go upwards until it hits the first properly-colored title bar (thus skipping your app's title bar). Just asking for a simple theme switcher.

**Comment by nicholaswright** [comment]
Would it be possible to simply have a Light Header (Theme) checkbox in Preferences? I personally find the juxtaposition of the dark header and light body an eyesore, it should be one or the other for the entire UI.

**Comment by thebasa** [comment]
I find all the white an eyesore.  What happened to dark mode?  I just got auto-notified the old version is no longer being actively developed so I switched to this and no dark theme :(

**Comment by j-f1** [comment]
@thebasa see #1515.

**Comment by billygriffin** [comment]
Hi folks - we appreciate this feedback but for now and until we see this come up as an area of frustration more frequently, I'm going to close this out to clarify that we don't intend to pursue anything here at the moment. As with all issues that we close, if there's enough evidence that we ought to support it or it's a widespread enough problem, we're absolutely open to revisiting. Thanks for the issue!

**Comment by tierninho** [comment]
_Comments from @judgej from https://github.com/desktop/desktop/issues/1515#issuecomment-520826810_

Dark theme is nice until you have a dark themed window over a dark themed application, running a dark themed desktop, and NOTHING has any outlines. It's just a big dark screen with text all over it, and no way to find the edges of the windows or know where one window stops and another window starts.

Is there any way around this? Does the dark theme, or the light theme for that matter, have any options for tweaking?

**Comment by judgej** [comment]
@billygriffin what kind of evidence do you need? If it helps, can send a recording of my increased levels of frustration as I swear at my machine as I try to locate black buttons on black bars, on a black background of another black application that lights up a black light to tell me I still have not yet found where the edge of the damn window is. You are ignoring people who have set up their PCs or Macs (it is the same problem on both) to cater for various sight and accessibility issues by overriding their settings for the sake of some kind of branding that someone has decided the app must have. Fine, it's your app and I don't pay for it, but that is not going to help a huge segment of your user base for which this is not just a design aesthetic.

**Comment by billygriffin** [comment]
@judgej As @tierninho mentioned in the other issue, additional information from screenshots and/or a screencast would be super helpful to get a better sense of what your experience is. Thanks for your willingness to share.
