### ISSUE TITLE
Menu bar scaling doesn't persist between sessions

### ISSUE THREAD

**Issue by pfthroaway** [desktop/desktop#3193]
### Description

When adjusting the GUI for scaling because it's far too small to be usable on higher resolutions, the menu bar increases in size so it's usable, also. 150% is pretty good on higher resolutions. However, after closing the application and opening it again, the menu bar is tiny again, and I can't hardly read anything on it. The rest of the GUI scaling persists between sessions, and I can read everything in the large buttons on the screen about my selected repository, branch, changes, and history, just not the menu bar. When I try to reduce the scale to 100% to make the GUI scale the default size, it makes it menu bar even tinier, and completely impossible to read instead of defaulting to the regular size. I can't read the menu bar to be able to merge branches or create/clone new repositories.

### Version

**GitHub Desktop version:** 1.0.6

**OS version:** Windows 10 Professional x64 build 16299

### Steps to Reproduce

1. Open GitHub Desktop.
2. Increase GUI scale with `Ctrl` and `+`. GUI and menu bar both increase properly.
3. Close the application and reopen it.
4. Examine how the menu bar is tiny while all other scaling persists between sessions.

**Expected behavior:** Increase GUI scaling to be readable, close application, open it again, all the GUI stays the size it was when you closed it.

**Actual behavior:** GUI scaling for the menu bar does not persist between sessions.

**Reproduces how often:** Every time I use the application on any computer.

**Comment by tierninho** [comment]
Thanks @pfthroaway Reproduced this. 

<img width="986" alt="screen shot 2017-10-30 at 10 39 53 am" src="https://user-images.githubusercontent.com/14828183/32164104-bff46c70-bd5e-11e7-9958-76294a479f03.png">
