### ISSUE TITLE
app is shown in the task bar but after clicking it the window doenst popup

### ISSUE THREAD

**Issue by lukas2005** [desktop/desktop#3200]
When i launch the app it kinda starts in minimized mode but when i try to click it the main window doesnt pop up
OS: Windows 10

**Comment by OiYouYeahYou** [comment]
Try `WinKey + UpArrow`

**Comment by niik** [comment]
Hi @praveen2710, is it possible that you're using (or have used) multiple monitors on your machine? This sounds very much like https://github.com/desktop/desktop/issues/2107.

There's some workarounds in that thread that you can try (maximizing the window through task manager) or you could try closing GitHub Desktop, deleting `%APPDATA%\GitHub Desktop\window-state.json` and then restarting it.

**Comment by JevinAnderson** [comment]
I'm also experiencing this on my Mac. I use spotlight to open the application, and it appears in my doc, but isn't visible. If I click on the icon, then go to the view menu, i can force a blank screen to appear. 
<img width="1402" alt="screen shot 2017-10-31 at 10 07 13 am" src="https://user-images.githubusercontent.com/3373201/32237999-ac04ec88-be23-11e7-9a58-9ea34f521381.png">
Not very useful. I do use dual monitors, but I shot this screenshot while my mac wasn't plugged in to anything.

I noticed this Monday morning.

**Comment by JevinAnderson** [comment]
I've tried reinstalling the application, and it is still not working. Is there a way to get older versions of the Mac installs?

**Comment by j-f1** [comment]
@JevinAnderson Can you press <kbd>⌥</kbd> <kbd>⌘</kbd> <kbd>I</kbd> and copy-paste any errors here?

**Comment by JevinAnderson** [comment]
@j-f1 here you go.

<img width="1236" alt="screen shot 2017-10-31 at 10 42 38 am" src="https://user-images.githubusercontent.com/3373201/32239620-41673318-be28-11e7-8980-465d1f3db924.png">

The error:

```
"Error
    at w (file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:5:37616)
    at new n (file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:5:85178)
    at file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:5:58164
    at file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:5:44253
    at q (file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:5:41473)
    at $ (file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:5:42131)
    at X (file:///Applications/GitHub%20Desktop.app/Contents/Resources/app/renderer.js:5:41985)
    at <anonymous>"
```

Message

```
"Transaction committed too early. See http://bit.ly/2kdckMn"
```
Name: `"PrematureCommitError"`

**Comment by JevinAnderson** [comment]
@j-f1 I followed these [instructions](https://gist.github.com/naomik/11245234) to completely uninstall the client, then I reinstalled, and everything is working as expected. I'm going to stop tracking this issue now.
