### ISSUE TITLE
Delete branch without switching to it

### ISSUE THREAD

**Issue by adamreisnz** [desktop/desktop#3202]
Pardon me if it's already been asked, but I couldn't locate a similar issue.

One of the things that always bothered me in the old app was that I had to switch to a certain branch before I could delete it. This still appears to be the case in the new app.

Can we get a context menu for right click on a branch in the branches list, and have some options in there, like delete branch?

This way, when I am done with a branch and I have switched back to another and merged it in, I don't need to switch back again, delete the branch, and then switch a third time.

There shouldn't be a need to switch to a particular branch before deleting it as you can also delete another branch via the command line without being on it.

**Comment by niik** [comment]
The old clients used to automatically prune merged local branches (see #750). I'm hoping that we'll be able to get to that at some point which would make deleting local branches manually less of an issue.

That said I don't have anything against also supporting a context menu in the branch list. For now though I'm gonna label this future-proposal and close it out so we can keep our backlog manageable. We'll revisit this in our next planning session.

**Comment by adamreisnz** [comment]
Ok, thanks 👍

**Comment by adamreisnz** [comment]
PS: If you aren't already, may I suggest using [Zenhub](https://www.zenhub.com/) to manage your issues backlog? 

It integrates on top of Github in your browser, and allows you to create as many columns/pipelines as you wish, so you could have one for example "Future proposal" or "Icebox" and put issues that are to be revisited later in there, rather than closing them off. That should still help to keep your actual issues backlog under control.

It's similar to Github's project tab, but a lot better with more functionality.

**Comment by danqing** [comment]
Much needed...

Every time I right click and nothing shows up a kitten dies..

**Comment by billygriffin** [comment]
Hi @adamreisnz, thanks for this. We're working through all the future proposals and it looks like this one should land when https://github.com/desktop/desktop/issues/5803 does, so I'm going to remove the label on this. Just didn't want to you come back to it and wonder what happened.

**Comment by adamreisnz** [comment]
Cheers thanks
