### ISSUE TITLE
Block saving (.) as your git username or email

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3204]
You are allowed to save `.` as your git credentials, however, it causes problems further down the line. When you attempt to commit or revert, there are two similar errors that surface, each saying you cannot save your same as `.`. 

<img width="453" alt="screen shot 2017-10-31 at 11 34 15 am" src="https://user-images.githubusercontent.com/14828183/32219887-fbd210ea-be2f-11e7-99c1-4ccf8a0a78c5.png">

We should block the user from saving their git name or email as a `.` in the `Preferences > Git` modal. Not sure if there are other special characters, et al, that would cause disruption as well.

<img width="401" alt="screen shot 2017-10-31 at 11 33 10 am" src="https://user-images.githubusercontent.com/14828183/32219886-fbafb9b4-be2f-11e7-8f17-bd2af3dbaddd.png">
<img width="603" alt="screen shot 2017-10-31 at 11 33 27 am" src="https://user-images.githubusercontent.com/14828183/32219888-fbfbdd1c-be2f-11e7-8426-0e898655facc.png">

1.0.7-beta0, mac

**Comment by niik** [comment]
For the future implementor of this. It would be spectacular if we could find a way to leverage Git's own validation logic here rather than try to replicate it ourselves.

**Comment by shiftkey** [comment]
@tierninho can you recall the flow to trigger that first error? The second one looks like committing, but I'm curious if we stumble upon it earlier...

**Comment by tierninho** [comment]
@shiftkey took a sec to figure it out, but that error can be surfaced when you revert a commit... in this case the initial commit on an already published repo.

<img width="850" alt="screen shot 2017-11-02 at 8 34 01 am" src="https://user-images.githubusercontent.com/14828183/32314569-d485d0ec-bfa8-11e7-8d01-9a0960727db3.png">

**Comment by nerdneha** [comment]
Looks like they use a function called `crud` to throw this error, see:
https://github.com/git/git/blob/e629a7d28a405e48fae6b064a781a10e885159fc/ident.c#L191-L203

**Comment by shiftkey** [comment]
Nice find @nerdneha. While @niik above suggested that it'd be great if we could get this by invoking Git in some way, the rules themselves haven't changed in at least 9 years:

<img width="783" src="https://user-images.githubusercontent.com/359239/33863940-5852e928-df3e-11e7-87b9-18eb7baabff2.png">

I'd suggest extracting those rules into our app is a fair  compromise.
