### ISSUE TITLE
Typo in the Github Desktop Release Notes

### ISSUE THREAD

**Issue by f4f09d107e** [desktop/desktop#3205]
https://desktop.github.com/release-notes/

In the release notes for version 1.0.5 (October 26th 2017), it should say

"**Linux**: Add Atom and Sublime Text support [...]"

instead of

"**Linx**: Add Atom and Sublime Text support [...]"

**Comment by niik** [comment]
Hey @f4f09d107e, care to open a PR to fix that typo?

**Comment by niik** [comment]
Hey again @f4f09d107e, it turns out this typo was already fixed in https://github.com/desktop/desktop/pull/3184 but the website won't be updated until we do another production release.
