### ISSUE TITLE
Add mouseover+tooltip to reveal subtext of the Publish button?

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3206]
When attempting to publish an unborn repo, you should be able to read the entire message in the subtext of the `Publish branch` button.  Currently it is cutoff leaving certain users wondering what the entire message is. 

I have Desktop fully expanded on a 15" mac:
<img width="264" alt="screen shot 2017-10-31 at 1 53 52 pm" src="https://user-images.githubusercontent.com/14828183/32224815-3306e992-be43-11e7-8b6a-b3ed121ba94e.png">

Should we surface a dialogue or make the button longer? Perhaps best solution is just mouseover+tooltip?

v1.0.6, mac

**Comment by niik** [comment]
Tooltip is certainly a viable option here though I wonder if we couldn't make the messaging even more compact and rid ourselves of the problem that way. In this case we're talking about an unborn HEAD, not necessarily an unborn _repository_. And the context is `Publish branch` so I'm thinking we could just say 'Cannot publish unborn branch` here instead.

**Comment by OiYouYeahYou** [comment]
> Cannot publish unborn branch

1. This tripped me up the first time, It's not really clear the for the novice. Could it be something like `'Nothing has been committed'`? Or can Unborn mean more than 'no commits'?
2. An additional action could be setting focus to the Changes list and use an animation to catch the eye
3. Should there be validation before opening the Publish dialog to confirm that a repo has been "born"?

**Comment by tierninho** [comment]
Saw this one as well in another issue. Looks like a tooltip is already there:

![unnamed](https://user-images.githubusercontent.com/14828183/32263605-ef95a1ba-beda-11e7-9597-ba3c8eb702e3.jpg)

**Comment by shiftkey** [comment]
@tierninho I think that's the progress message whenever a push/pull/fetch is happening, which is separate to this. But I still favour @niik's idea of making it more concise to avoid the need for a tooltip.

**Comment by Venkat5694** [comment]
@shiftkey I have created a new branch and made the changes. But when I try to push the branch I get the following error `Authentication failed. You may not have permission to access the repository. Open preferences and verify that you're signed in with an account that has permission to access this repository.` What am I doing wrong?

**Comment by joshaber** [comment]
@Venkat5694 Could you create a new issue so that we can figure out what's happening?

**Comment by Venkat5694** [comment]
@joshaber I have created #3343 and explained the problem that I face while pushing code. When I try to push my branch via CLI using the command `git push --set-upstream origin fix-unborn-repo-description` , I get the following error message `remote: Permission to desktop/desktop.git denied to Venkat5694.
fatal: unable to access 'https://github.com/desktop/desktop.git/': The requested URL returned error: 403`
