### ISSUE TITLE
Open in Git bash doesn't work

### ISSUE THREAD

**Issue by lekhasy** [desktop/desktop#3210]
### Description

Select **Repository** -> **Open in git bash** or **Ctrl + `** doesn't work.
My computer have git installed and i can open a folder in git bash by **Right click on the folder** -> **Git Bash Here**.
Change the shell option to **PowerShell** or **Command Prompt** in **Advance Option** dialog did resolve the problem, but the **Git Bash** option doesn't work.
### Version

**GitHub Desktop version:** 1.0.6

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Open Git Hub Desktop
1. Select a Repo
1. Select **Repository** -> **Open in git bash** or **Ctrl + `**

**Expected behavior:** A Git Bash window for current repo open

**Actual behavior:** Nothing happend

**Reproduces how often:** 100%

### Logs

[2017-11-01.desktop.production.log](https://github.com/desktop/desktop/files/1433575/2017-11-01.desktop.production.log)

**Comment by shiftkey** [comment]
@lekhasy thanks for the report. This has been fixed in #3194 which will go out in the next update!
