### ISSUE TITLE
Github Desktop freezes entire Windows 10 System

### ISSUE THREAD

**Issue by kpei** [desktop/desktop#3211]
### Description

I have been getting freezing issue recently on my work laptop that's installed with Windows 10 Pro.   The entire OS would freeze, most of the time the mouse as well and there's nothing I can do except do a hard restart on my laptop.  

I noticed that this has been occurring when Github Desktop is also open (idle after some work has been done on it).  I originally had thought it's a chrome issue since the freeze occurs when I'm browsing chrome but the issue stops when I don't have github desktop open.  It had only started occurring a few days after i installed GH desktop.

I can only seem to replicate this issue on my laptop, I run GH desktop at home and have no issues with it so far.

### Version

**GitHub Desktop version:** 10.6

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Have a work laptop with windows 10
1. Make sure to not save any work you have been doing for the past 6 hours
1. Open Github desktop
1. Wait
1. **Bonus side effect**: Your micromanaging boss calls you into the office to ask why there's been zero commits on the project all day

**Expected behavior:** Not Freeze

**Actual behavior:** Froze

**Reproduces how often:** 100% of the time

### Logs
[2017-11-01.desktop.production.log](https://github.com/desktop/desktop/files/1434112/2017-11-01.desktop.production.log)

**Comment by kpei** [comment]
More logs although I'm not too sure which ones terminated with a freeze issue
[2017-10-25.desktop.production.log](https://github.com/desktop/desktop/files/1434121/2017-10-25.desktop.production.log)
[2017-10-26.desktop.production.log](https://github.com/desktop/desktop/files/1434122/2017-10-26.desktop.production.log)
[2017-10-30.desktop.production.log](https://github.com/desktop/desktop/files/1434123/2017-10-30.desktop.production.log)

**Comment by niik** [comment]
Hey @kpei, I'm sorry you're experiencing this issue. Unfortunately those log files didn't provide much of anything to go on.

Speaking from experience with the classic app on Windows these freezes were often caused by either the graphics card or bad memory. Please make sure that you're running on the latest graphics drivers available for your system. Additionally it would be helpful if you could check the Windows Event Log after one of these crashes and see if you can find anything in there that could help debug this.

**Comment by fifou17** [comment]
i have same issue in latest github with new windows 10 build entire desktop freez

**Comment by greytery** [comment]
Me Too. Two days running - Windows 10 system freezes (needing reboot) after a few minutes of the 'Write' window open.
(ITOH - I suppose it discourages verbosity!)

**Comment by shiftkey** [comment]
> Windows 10 system freezes (needing reboot) after a few minutes of the 'Write' window open.

@greytery if this is something you'd like us to investigate please open a fresh issue and fill out the bug report template.

**Comment by greytery** [comment]
Mmmm... after trying to reproduce - nada.   Then, the freeze seems to happen without being anywhere near github after all!!   Browser =Firefox on Win10.
WITHDRAW comment.

**Comment by muzhaqi16** [comment]
I had the same thing happen for the first time this week. I enabled two-factor authentication a couple of weeks ago and out of nowhere, I was asked to log in. When I tried to log in using the authentication key my whole internet connection and computer kind of froze for about 4-5 minutes until I got the prompt to touch my security key from windows. After that everything was fine.
