### ISSUE TITLE
[Feature Request] Open Repository in Atom and Ubuntu for Windows

### ISSUE THREAD

**Issue by adambirds** [desktop/desktop#3214]
# Feature Request
### We currently have the option to open the repository in:

- Command Prompt
- Windows Explorer
- VS Code

### I would like the option to open the repository as well in both of the below:

- Atom (Surprised its not already available, considering its GitHubs)
- Ubuntu for Windows using Windows Subsystem for Linux

**Comment by shiftkey** [comment]
@adambirds thanks for the suggestion

> Atom (Surprised its not already available, considering its GitHubs)

For Windows? This should be covered by all the platforms, need more info about your setup to troubleshoot this further.

> Ubuntu for Windows using Windows Subsystem for Linux

I talked a bit about this over in https://github.com/desktop/desktop/issues/3074 and we have some docs on how to [integrate other shells](https://github.com/desktop/desktop/blob/master/docs/technical/shell-integration.md). It'd be nice to collaborate with someone who knows more about how this currently works as I'm rusty - are you interested?

**Comment by adambirds** [comment]
@shiftkey just saw the "options" menu where you can change between the shell and external editor and can see Atom is an option, there. However I think it would be great to have a feature where you can select more than one shell or editor to appear in the drop down menu. I sometimes prefer different editors depending on what I'm doing.

With regards to the integration into Bash for Windows. I'll take a look at trying to get it integrated i the next week or so.

**Comment by shiftkey** [comment]
@adambirds 

> However I think it would be great to have a feature where you can select more than one shell or editor to appear in the drop down menu. I sometimes prefer different editors depending on what I'm doing.

Let's move this out to a fresh issue to talk about this further. It's not something we thought about when we rolled this out.

> With regards to the integration into Bash for Windows. I'll take a look at trying to get it integrated i the next week or so.

:thumbsup:

**Comment by adambirds** [comment]
I've opened the request for the first thing in #3221. Will update #3074 when I have anything on the Bash for Windows.
