### ISSUE TITLE
i have a windows vista 32 bit

### ISSUE THREAD

**Issue by oscdows** [desktop/desktop#3215]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by joshaber** [comment]
@oscdows we don't support 32-bit versions of Windows - see #1214 for the related discussion.

**Comment by gastonea** [comment]
Josh, please, let's make a 32 bit release!! Which is effort that demand it? Really? I was left without be able to work at this PC... the domain's admin cannot allow me upgrade the SO. Regards, and have you nice day

**Comment by Learning191** [comment]
it may be a very good idea yours to spend :+1:

**Comment by Beemo138** [comment]
Can we PLEASE get a 32 bit supported version? it would make life so much easier...

PLEASE PLEASE PLEASE?????
