### ISSUE TITLE
Can't create merge commit after discarding conflicted changes

### ISSUE THREAD

**Issue by niik** [desktop/desktop#3218]
If you get a merge conflict while merging a branch and discard the only conflicted file (preserving your changes) there's no way to actually commit the merge conflict.

### Setup

```
test markus$ git init conflict-test
Initialized empty Git repository in /Users/markus/GitHub/test/conflict-test/.git/
test markus$ cd conflict-test/
conflict-test markus$ echo "1" > file.txt
conflict-test markus$ git add file.txt 
conflict-test markus$ git commit -m '1'
[master (root-commit) 7a3ddc1] 1
 1 file changed, 1 insertion(+)
 create mode 100644 file.txt
conflict-test markus$ git checkout -b b1
Switched to a new branch 'b1'
conflict-test markus$ echo 2 > file.txt 
conflict-test markus$ git add .
conflict-test markus$ git commit -m '2'
[b1 513af26] 2
 1 file changed, 1 insertion(+), 1 deletion(-)
conflict-test markus$ git checkout master
Switched to branch 'master'
conflict-test markus$ echo "3" > file.txt 
conflict-test markus$ git add .
conflict-test markus$ git commit -m 3
[master 55c4809] 3
 1 file changed, 1 insertion(+), 1 deletion(-)
conflict-test markus$ git checkout b1
Switched to branch 'b1'
```

After this, open GitHub Desktop, update from master, see the conflicted file, discard it and try to commit.

<img width="250" alt="screen shot 2017-11-01 at 22 18 37" src="https://user-images.githubusercontent.com/634063/32298481-b3532420-bf52-11e7-8a94-937172073597.png">

The commit button is disabled since there's no files in the file list even though the conflict has been resolved and a commit is needed.

<img width="353" alt="screen shot 2017-11-01 at 22 18 43" src="https://user-images.githubusercontent.com/634063/32298482-b37999e8-bf52-11e7-84c3-229c9934329e.png">

I suppose we'll have to address this as part of the other conflict resolution work.

**Comment by tierninho** [comment]
I can reproduce this in v2.1 however when clicking the "view conflict " link in the banner it results in the conflict being resolved. 

![Screen Shot 2019-07-19 at 11 42 37 AM](https://user-images.githubusercontent.com/14828183/61567235-8d6b4580-aa1a-11e9-997f-3db3d8c7701d.png)

Clicking `commit merge` results in a commit and the surfacing of the `undo` button, however there are no files to undo.

**Comment by sergiou87** [comment]
It seems to work as expected now 🎉
