### ISSUE TITLE
checkbox in changes moves 1px when hover

### ISSUE THREAD

**Issue by gemal** [desktop/desktop#3223]
using version 1.0.6
when I move my mouse cursor over the checkboxes in the left side of the changes tab the checkbox moves 1px down.
hard to see but it's there

**Comment by niik** [comment]
Hey @gemal, what operating system are you using?

Could you capture a Gif of this behavior using [LiceCap](https://www.cockos.com/licecap/) (or any other screen capture software) and attach it here.
