### ISSUE TITLE
Github desktop refuses to work with cloned projects. 

### ISSUE THREAD

**Issue by outcastdreamer** [desktop/desktop#3227]
![github1](https://user-images.githubusercontent.com/31828694/32371909-b66273b6-c0b8-11e7-8ceb-e6dd26619acd.JPG)
![github2](https://user-images.githubusercontent.com/31828694/32371911-b6ce6b98-c0b8-11e7-9b8f-0c49368a1dd9.JPG)
I am very new to Github (as my profile makes it too obvious) so kindly go easy even if I sound dumb. I am unable to load projects or download on Github desktop if I choose "Open in Desktop" option and this error pops (refer to 2nd image). I have unable to locate someone else having this same problem. It would be amazing if anyone can help me solve this problem or refer me the link to a similar problem to solve this issue. Thanking you for your time and help!

**Comment by tierninho** [comment]
@outcastdreamer Thanks for sharing. Can you add some details so our core team can help resolve your issue.

1. OS version

> If you are on Windows, open `Command Prompt` and attach the output of this
   command: `cmd /c ver`

2. GitHub Desktop version

> What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. 

3. Logs (if any)

> There may be some relevant information in log files generated by GitHub
Desktop: If you are on Windows, attach the most recent log file from:
   `%APPDATA%\GitHub Desktop\logs\*.desktop.production.log`

> The log files are organized by date, so see if anything was generated for
today's date.

**Comment by outcastdreamer** [comment]
[logs.zip](https://github.com/desktop/desktop/files/1441344/logs.zip)
![github3](https://user-images.githubusercontent.com/31828694/32378735-880afe7a-c0d1-11e7-9f3f-561eff8d0f4a.JPG)
![github4 1](https://user-images.githubusercontent.com/31828694/32378736-8845b36c-c0d1-11e7-929b-8618bd37aed4.JPG)
@tierninho   Here I hope this helps. Btw I just updated Github Desktop from 1.0.4 to 1.0.6 and it seems to be working. Though I guess the Log files are going to be helpful nevertheless. Thanks for your time!

**Comment by niik** [comment]
@outcastdreamer Thanks for getting back to us. Glad to hear that it seems to be working now! Since the dialog you posted indicated that it was trying to launch 0.8.1 (a pretty old version) let's hope that was it. If this pops up again please let us know so that we can troubleshoot further.
