### ISSUE TITLE
Give me the option to pause download or uploads to resume them later !

### ISSUE THREAD

**Issue by Mangolicious** [desktop/desktop#3236]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by j-f1** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by Mangolicious** [comment]
Description

Please add the feature to pause and resume downloads, when pushing or fetching, since it is essential for anyone with a limited internet connection.
Version

GitHub Desktop version: 1.0.6

OS version: Windows 7
Steps to Reproduce

- Start download
- Unable to pause or cancel download


Expected behavior: options to pause resume and cancel download

Actual behavior: Unable to pause or cancel download

Reproduces how often: 100%
Logs

**Comment by shiftkey** [comment]
@Mangolicious unfortunately this is more of a Git limitation than something we can address in Desktop.

Git will compute what needs to be pushed whenever a branch updates - the blobs representing the content changes can be the expensive part - and it won't update the branch until it receives all those. This also occurs atomically - either the push completes or fails. I honestly haven't explored whether people have been experimenting with this and whether it's feasible with Git, but I'm open to reading the adventures of others.

Fetches should be a bit easier to manage - the app currently does fetches in the background periodically, and these are no-blocking.
