### ISSUE TITLE
Github Desktop doesn't open

### ISSUE THREAD

**Issue by putaojuice** [desktop/desktop#3237]
### Description

Github Desktop doesn't open after the first launch for github desktop. Github Desktop App runs in background process but the programme doesn't show up in desktop or taskbar. It is also not minimized.
After restarting the computer, I managed to open the app, as i closed it, Github Desktop will not open again. Seems like everytime after i restart i am able to on the app but after I closed it, this problem appears. Tried uninstall, clearing all github files in appdata and reinstalling but the problem still persists. Also tried turning firewall off but it doesnt help.

### Version

**GitHub Desktop version:** 1.0.8

**OS version:** 10.0.15063

### Steps to Reproduce

1. On Github Desktop
2. Github Desktop is on
3. Close Github Desktop
4. On Github Desktop
5. Github Desktop doesn't open, but it is running in background process. It is not minimized or anything.

**Expected behavior:** Github Desktop should be on

**Actual behavior:** Github Desktop doesn't open, but it is running in background process.

**Reproduces how often:** Everytime after I restart my computer

**Comment by shiftkey** [comment]
@putaojuice are you running multiple monitors? There's a couple of issues we're tracking like #2107 that probably require some fixes to Electron.

Could you also attach the `%APPDATA%\GitHub Desktop\window-state.json` file that exists on your machine? This probably hasn't been touched as part of the uninstall/reinstall experience, so it might have some interesting data to help us understand the problem better.

Also, as a workaround you should be able to remove the `%APPDATA%\GitHub Desktop\window-state.json` file and restart the app.

**Comment by putaojuice** [comment]
@shiftkey thanks for the reply! And nope i am not running on multiple monitors. I've tried the methods in #2107 it doesn't seem to work. I've also tried removing the window-state.json file but it also didn't work out.

[https://ufile.io/hcm5o](url)
here is the .json file in my computer.

**Comment by TMJesso** [comment]
I am also having the same problem. Here is the info when it crashes:

Error: Mode github-diff-syntax failed to advance stream.
    at at (app\node_modules\codemirror\lib\codemirror.js:1639:1)
    at dt (app\node_modules\codemirror\lib\codemirror.js:1693:1)
    at tt (app\node_modules\codemirror\lib\codemirror.js:1539:1)
    at %AppData%\Local\GitHubDesktop\app-1.0.7\webpack:\app\node_modules\codemirror\lib\codemirror.js:4063:24
    at Jr.iterN (app\node_modules\codemirror\lib\codemirror.js:5539:8)
    at Bs.iterN (app\node_modules\codemirror\lib\codemirror.js:5651:41)
    at Bs.iter (app\node_modules\codemirror\lib\codemirror.js:6047:14)
    at Do (app\node_modules\codemirror\lib\codemirror.js:4058:1)
    at %AppData%\Local\GitHubDesktop\app-1.0.7\webpack:\app\node_modules\codemirror\lib\codemirror.js:148:21

Version: 1.0.7
OS: Windows 10.0.15063

**Comment by j-f1** [comment]
@TMJesso That’s actually a different issue — see #3249 and @niik’s [comment](https://github.com/desktop/desktop/issues/3249#issuecomment-342735764) on that issue about how to upgrade to get the fix for it.
