### ISSUE TITLE
Request Release

### ISSUE THREAD

**Issue by scottnath** [desktop/desktop#3241]
### Description

Team needs to add `upstream` repos via GitHub desktop. #3199 adds that functionality, but has not been released yet.

Could you please release a version of Desktop with the new features created by #3199?

### Version

**GitHub Desktop version:** 1.0.6
**OS version:** Mac 10.12.6

Thank you!

**Comment by shiftkey** [comment]
@scottnath good shout - I'll do some testing a prep a release when I have the bandwidth!

**Comment by aa369888** [comment]
＿謝謝

2017-11-07 6:34 GMT+08:00 Brendan Forster <notifications@github.com>:

**Comment by shiftkey** [comment]
`1.0.7` has been published!
