### ISSUE TITLE
"GitHub Desktop failed to launch" after latest update

### ISSUE THREAD

**Issue by filipsobol** [desktop/desktop#3249]
### Description

"GitHub Desktop failed to launch" after latest update

### Version

**GitHub Desktop version:** 1.0.7
**OS version:** Windows 10.0.14393

### Steps to Reproduce

1. Restart GitHub Desktop app to install latest update (1.0.7)

**Expected behavior:** N/A

**Actual behavior:** App crashes right after opening

**Reproduces how often:** Always

### Logs

```
Error: Mode github-diff-syntax failed to advance stream.
    at at (app\node_modules\codemirror\lib\codemirror.js:1639:1)
    at dt (app\node_modules\codemirror\lib\codemirror.js:1693:1)
    at tt (app\node_modules\codemirror\lib\codemirror.js:1539:1)
    at C:\Users\<USERNAME>\AppData\Local\GitHubDesktop\app-1.0.7\webpack:\app\node_modules\codemirror\lib\codemirror.js:4063:24
    at Jr.iterN (app\node_modules\codemirror\lib\codemirror.js:5539:8)
    at Bs.iterN (app\node_modules\codemirror\lib\codemirror.js:5651:41)
    at Bs.iter (app\node_modules\codemirror\lib\codemirror.js:6047:14)
    at Do (app\node_modules\codemirror\lib\codemirror.js:4058:1)
    at C:\Users\<USERNAME>\AppData\Local\GitHubDesktop\app-1.0.7\webpack:\app\node_modules\codemirror\lib\codemirror.js:148:21

Version: 1.0.7
OS: Windows 10.0.14393
```

**Comment by shiftkey** [comment]
@filipsobol is there a specific repository you're using at this point? If it's a public repository it might help speed up troubleshooting.

cc @niik for :eyes: on where this might be lurking

**Comment by filipsobol** [comment]
Private BitBucket repo... unfortunately I can't check with other repos, because app crashes immediately:(

**Comment by filipsobol** [comment]
Looks like issue was caused by specific file, but I have no idea what caused it. I noticed what I could change previewed file right before app crashed and when I did, it worked until I selected this file again. I reverted all changes in this file and everything works fine.

¯\(°_o)/¯

**Comment by shiftkey** [comment]
@filipsobol first off, what sort of file is it?

**Comment by filipsobol** [comment]
PHP file, only few lines were changed.

**Comment by shiftkey** [comment]
@filipsobol any details help. I'll see if I can trigger it on my end with some sample PHP repositories.

**Comment by filipsobol** [comment]
I  found the cause of this - "**{$**" (opening curly brace followed by dollar sign). In PHP it's possible to concatenate string and variable like this:

```echo "Welcome {$name}s!"```

**Comment by SeanTaylorVS** [comment]
The same issue is happening for me. Can confirm that it happens when there is '**{$**' in a changed file.

**Comment by emielvangoor** [comment]
Same issue here, also with a `{$` in the changed file.

**Comment by chunfeilung** [comment]
Experiencing the same issue.

It only happens when `{$` is part of a string enclosed in double quotes, like @filipsobol already mentioned.

It doesn’t seem to cause a crash when `{$` is used in other ways like `'Welcome {$name}s!'` and `$foo->{$bar}`.

**Comment by phawxby** [comment]
Same problem, again with a PHP file and a change to string interpolation.

```
Error: Mode github-diff-syntax failed to advance stream.
    at at (app\node_modules\codemirror\lib\codemirror.js:1639:1)
    at dt (app\node_modules\codemirror\lib\codemirror.js:1693:1)
    at tt (app\node_modules\codemirror\lib\codemirror.js:1539:1)
    at C:\Users\Z269CJBB\AppData\Local\GitHubDesktop\app-1.0.7\webpack:\app\node_modules\codemirror\lib\codemirror.js:4063:24
    at Jr.iterN (app\node_modules\codemirror\lib\codemirror.js:5539:8)
    at Bs.iterN (app\node_modules\codemirror\lib\codemirror.js:5651:41)
    at Bs.iter (app\node_modules\codemirror\lib\codemirror.js:6047:14)
    at Do (app\node_modules\codemirror\lib\codemirror.js:4058:1)
    at C:\Users\Z269CJBB\AppData\Local\GitHubDesktop\app-1.0.7\webpack:\app\node_modules\codemirror\lib\codemirror.js:148:21

Version: 1.0.7
OS: Windows 10.0.14393
```

**Comment by karenmt** [comment]
Can confirm on Mac OS 10.13.1, version 1.0.7. It works fine if I remove the line with `{$`, but crashes with that line.

**Comment by Giolegrand** [comment]
i can also confirm that this is an real big issue, added a line that contained `{$` and now its stuck in a loop crashing on the files that have the `{$` in it.

**Comment by niik** [comment]
Thank you all for your help with this! I've been able to reproduce the problem. I'll update as soon as I have a fix or workaround for this.

**Comment by OzanKurt** [comment]
I confirm that the `{$` is the problem.

Changed this:
```php
return "<a href='{$route}'>{$site->name}</a>";
```
to this:
```php
return '<a href="'.$route.'">'.$site->name.'</a>';
```

and it started working...

**Comment by joshaber** [comment]
We just released 1.0.8 with the fix. Thank you all for reporting it and your patience as we fixed it 💖

**Comment by sjw1357** [comment]
crash then restart, then crash, then restart~~  =.= , os: win10 X64

**Comment by niik** [comment]
@sjw1357 If you're unable to launch GitHub Desktop it's not going to automatically update itself to the version which contains the fix for this issue. What's likely happening is that you've got a file with a change which triggers the bug in the repository that you last opened in GitHub Desktop. I can see a few ways to get around the problem. 

 - Temporarily rename the folder where your repository is located such that it won't automatically get loaded when you launch Desktop
 - Add an empty file named 'a.txt' (or something which will cause it to get sorted before any other changes)
 - Temporarily move the changed file out of the repository

Once you've gotten GitHub Desktop to start you can click the Help menu and then 'About GitHub Desktop' to check for, and download, the new update.

Another option is to uninstall GitHub Desktop and then reinstall it using the latest installer from [desktop.github.com](https://desktop.github.com).
