### ISSUE TITLE
Feature request: add "Unified | Split" switch for line diff

### ISSUE THREAD

**Issue by xmcp** [desktop/desktop#3251]
There is a "Unified | Split" switch in the GitHub website.
I think there should be a similar option to show split line diff in the desktop client.

![image](https://user-images.githubusercontent.com/6646473/32492392-13d7cf0c-c3f5-11e7-890d-0c00101a85cc.png)

**Comment by shiftkey** [comment]
@xmcp thanks for the request. I knew we were tracking this somewhere already, so please follow along with #172.

**Comment by alimobappdev** [comment]
What's the purpose of these buttons?
