### ISSUE TITLE
Beta stream for GitHub Desktop?

### ISSUE THREAD

**Issue by IdanAdar** [desktop/desktop#3257]
Is the a beta stream for GitHub Desktop for early build access?
If not, how does one build locally?

**Comment by j-f1** [comment]
> how does one build locally?

See [`docs/contributing/setup.md`](https://github.com/desktop/desktop/blob/master/docs/contributing/setup.md)

**Comment by shiftkey** [comment]
> Is the a beta stream for GitHub Desktop for early build access?

Not through a public URL. I think @desktop/core is :thumbsup: to enabling this - I've proposed a change to support this on our backend, and then I'll update the documentation to share where this can be found. Stay tuned!
