### ISSUE TITLE
Git Console UI integration

### ISSUE THREAD

**Issue by ViRGiL175** [desktop/desktop#3266]
### Description

Is it possible to integrate Git Bash (or any other terminal) in the GitHub Desktop UI?

I like to use Git Bash, and I created pretty graph alias etc. But it is awesome: to view diffs or do interactive adding through GitHub Desktop UI. 

But it is still unhandy for more complex operations and for commits tree analyzing.

And the best compromise I see: to integrate console right inside GitHub UI, there are a lot of empty space on the right:

![Imgur](https://i.imgur.com/AlTBiuJ.png) 

Is it possible? I see a flawless workflow in my dreams...

### Version

**GitHub Desktop version:** 1.0.8

**OS version:** Windows 10

**Comment by j-f1** [comment]
Thanks for contributing @ViRGiL175!

Although this might not be what you’re looking for, <kbd>Ctrl</kbd>+<kbd>`</kbd> will open your terminal to the repository you have open in Desktop.

**Comment by ViRGiL175** [comment]
Yes, I'm tryin' to do it in this way, but single window is a single window, you know :)

**Comment by niik** [comment]
Hey @ViRGiL175, thanks for opening this. I'm going to close this out in favor of https://github.com/desktop/desktop/issues/1586 so please subscribe to that issue.
