### ISSUE TITLE
Feature to see the diff between two branches

### ISSUE THREAD

**Issue by saiKumarGanji** [desktop/desktop#3273]
In Stash Website, We can see the diff changes between 2 branches.
Can we get this feature in Github Desktop.

**Comment by shiftkey** [comment]
@saiKumarGanji I'm not familiar with Stash Website. Would the "Compare on GitHub" button, which opens a browser to a page like [this](https://github.com/desktop/desktop/compare/master...desktop:i-hate-you-registry-with-the-fire-of-a-thousand-suns) be equivalent? Or is there stuff missing?

**Comment by tierninho** [comment]
This looks to be the feature:

![stash3blog_comparebranch](https://user-images.githubusercontent.com/14828183/32599574-444e2372-c53d-11e7-851d-8b24978790bd.png)

**Comment by shiftkey** [comment]
@saiKumarGanji cool, that looks very similar to our `Compare on GitHub` flow. Please try it out and see if there's anything more we can do around that area.

**Comment by saiKumarGanji** [comment]
So, you are saying that this feature in already available in "Github Desktop" windows. I heard thats it available on mac. But i cannot find it on windows.

**Comment by j-f1** [comment]
@saiKumarGanji What version of GitHub Desktop are you running?

**Comment by saiKumarGanji** [comment]
Version 1.0.8 on Windows

**Comment by mkf85** [comment]
Mute the thread

Em 11 de nov de 2017 2:24 PM, Sai Kumar Ganji <notifications@github.com> escreveu:

Version 1.0.8 on Windows

**Comment by shiftkey** [comment]
@saiKumarGanji for a GitHub repository this is where it's hiding:

<img width="994"  src="https://user-images.githubusercontent.com/359239/32997267-8b76a1be-cde1-11e7-94aa-8a39017e596d.png">

**Comment by Diokuz** [comment]
What if my project not on github? Is it possible to view diff between branches?

**Comment by iAmWillShepherd** [comment]
@Diokuz, we will allow you to do just that in the next release of Desktop. Check out #4182 for more details.

**Comment by fords** [comment]
https://help.github.com/en/github/committing-changes-to-your-project/comparing-commits-across-time
