### ISSUE TITLE
搜索框不好用search input don't well work

### ISSUE THREAD

**Issue by e1399579** [desktop/desktop#3279]
使用中文转入法，然后每个字母都会重复好几遍，根本没法打字，version 1.0.8
With chinese input,every char repeat,not expect

**Comment by shiftkey** [comment]
@e1399579 could you share some screenshots or more information about how you are using the app to trigger this issue?

**Comment by joshaber** [comment]
Whoops, looks like our bot got a little too aggressive. Re-opening.

**Comment by shiftkey** [comment]
Closing this out as inactive - @e1399579 if you can provide more details about the issue we are happy to reopen this issue. I also think this might be related to, or a duplicate of, #3354.

**Comment by e1399579** [comment]
[Video_2017-11-24_091726.zip](https://github.com/desktop/desktop/files/1500423/Video_2017-11-24_091726.zip)

**Comment by shiftkey** [comment]
@e1399579 thanks for the video - this is the same as #3354 and I can reproduce this on my machine once I switch to Pinyin.
