### ISSUE TITLE
cannot checkout a ref which exists on multiple remotes

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3281]
When I try to switch branches on my forked repo, i get an error message for each attempt.

```install.ts:23 `git -c credential.helper= checkout --progress gh-pages --` exited with an unexpected code: 128.
fatal: invalid reference: gh-pages```

<img width="934" alt="screen shot 2017-11-09 at 12 59 34 pm" src="https://user-images.githubusercontent.com/14828183/32604587-676d57ae-c54e-11e7-96a7-4d49c5e5354d.png">
<img width="623" alt="screen shot 2017-11-09 at 1 06 21 pm" src="https://user-images.githubusercontent.com/14828183/32604679-cd49f942-c54e-11e7-9837-d6a3c363ee40.png">

Same result no matter if it's `upstream/branch-name` or `origin/branch-name`.

Cloned repo is: https://github.com/tierninho/map.git

Also, perhaps we should tweak the error message to something a little more understandable?

tested in 1.0.9-beta0, mac

**Comment by shiftkey** [comment]
@tierninho can you reproduce this on `1.0.8`?

**Comment by tierninho** [comment]
@shiftkey Yes, switched to prod build `1.0.8` and same thing happened.

**Comment by NickVirtru** [comment]
I am getting this on a particular branch as well.

**Comment by shiftkey** [comment]
Ah, this is probably the missing bit from my repro steps:

> When I try to switch branches on my **forked** repo

@tierninho @NickVirtru could you open the repository in a shell, run this command for me and attach the output? I want to confirm I've got the right setup to handle this properly:

```
$ git remote -vv
$ git branch --all
```

**Comment by NickVirtru** [comment]
@shiftkey I was trying to switch to the `origin 508-final` branch

    C:\Users\Nick\Source\Repos\Virtru\dotnet-v2>git remote -vv
    origin  https://github.com/NickVirtru/dotnet-v2.git (fetch)
    origin  https://github.com/NickVirtru/dotnet-v2.git (push)
    upstream        https://github.com/virtru/dotnet-v2.git (fetch)
    upstream        https://github.com/virtru/dotnet-v2.git (push)

	C:\Users\Nick\Source\Repos\Virtru\dotnet-v2>git branch --all
	* develop
	  feature/508-expiration-dialog-tab-esc
	  feature/MSO-508-settings-dialog-tab-sequence-exit
	  feature/MSO-590-show-attachment-chips-inline
	  feature/MSO-748-Respect-the-users-setting-for-default-compose-mode
	  feature/MSO-757-settings-dialog
	  remotes/origin/508-final
	  remotes/origin/Box-Demo-Excel-Support
	  remotes/origin/HEAD -> origin/develop
	  remotes/origin/bug/MSO-674-date-expiry-illegible
	  remotes/origin/bug/MSO-723-Accounts-being-shown-as-both-main-account-and-a-delegated-account
	  remotes/origin/bug/MSO-747-Outlook-2010-has-a-race-condition-during-initialization-resulting-UI-not-being-initialized
	  remotes/origin/change-button
	  remotes/origin/develop
	  remotes/origin/feature/508-expiration-dialog-tab-esc
	  remotes/origin/feature/Address-Correction-Form
	  remotes/origin/feature/Draft-Protection
	  remotes/origin/feature/MSO-457-Run-SSS-Rules-on-plain-text-and-PDF-attachments
	  remotes/origin/feature/MSO-508-settings-dialog-tab-sequence-exit
	  remotes/origin/feature/MSO-590-show-attachment-chips-inline
	  remotes/origin/feature/MSO-672-508-Compliance-Reading-Pane-Focus
	  remotes/origin/feature/MSO-692-Hide-the-Revoke-/-Expire-/-Disable-Forwarding-Options-in-Inbox
	  remotes/origin/feature/MSO-695-Support-Delegated-Accounts
	  remotes/origin/feature/MSO-700-Dont-enumerate-groups-and-distribution-lists-if-a-Domain-is-Synced
	  remotes/origin/feature/MSO-718-High-DPI-Support
	  remotes/origin/feature/MSO-728-Add-Release-Channels-To-AutoUpdate
	  remotes/origin/feature/MSO-748-Respect-the-users-setting-for-default-compose-mode
	  remotes/origin/feature/MSO-757-settings-dialog
	  remotes/origin/release
	  remotes/origin/testing/high-dpi-support
	  remotes/upstream/508-final
	  remotes/upstream/Box-Demo-Excel-Support
	  remotes/upstream/bug/MSO-674-date-expiry-illegible
	  remotes/upstream/bug/MSO-723-Accounts-being-shown-as-both-main-account-and-a-delegated-account
	  remotes/upstream/bug/MSO-747-Outlook-2010-has-a-race-condition-during-initialization-resulting-UI-not-being-initialized
	  remotes/upstream/develop
	  remotes/upstream/feature/Address-Correction-Form
	  remotes/upstream/feature/Draft-Protection
	  remotes/upstream/feature/MSO-457-Run-SSS-rules-on-plain-text-and-PDF-attachments-with-dtSearch
	  remotes/upstream/feature/MSO-508-settings-dialog-tab-sequence-exit
	  remotes/upstream/feature/MSO-590-show-attachment-chips-inline
	  remotes/upstream/feature/MSO-672-508-Compliance-Reading-Pane-Focus
	  remotes/upstream/feature/MSO-692-Hide-the-Revoke-/-Expire-/-Disable-Forwarding-Options-in-Inbox
	  remotes/upstream/feature/MSO-695-Support-Delegated-Accounts
	  remotes/upstream/feature/MSO-700-Dont-enumerate-groups-and-distribution-lists-if-a-Domain-is-Synced
	  remotes/upstream/feature/MSO-718-High-DPI-Support
	  remotes/upstream/feature/MSO-728-Add-Release-Channels-To-AutoUpdate
	  remotes/upstream/feature/MSO-748-Respect-the-users-setting-for-default-compose-mode
	  remotes/upstream/feature/MSO-757-settings-dialog
	  remotes/upstream/jtg/MSO-748-Respect-the-users-setting-for-default-compose-mode
	  remotes/upstream/release
	  remotes/upstream/testing/high-dpi-support

**Comment by shiftkey** [comment]
@NickVirtru thanks, that helps greatly!

**Comment by yashghelani** [comment]
I'm still having this issue. Has this been resolved? How do I change branches?

**Comment by shiftkey** [comment]
@yashghelani nah, this hasn't been resolved yet. As checking out branches is a pretty fundamental task, I'm going to pull this into the `1.0.x` milestone and see if I can put together a fix :soon:

**Comment by yashghelani** [comment]
Thanks! Keep us posted. Hoping to seeing this fixed soon :)

**Comment by Pa061061** [comment]
3111
