### ISSUE TITLE
[BUG] If I change branch, code in folder will still from previous branch.

### ISSUE THREAD

**Issue by Mlocik97-issues** [desktop/desktop#3287]
### Description

I select another branch, code will still from previous branch.

### Version

**GitHub Desktop version:** 1.0.8

**OS version:** Windows 8.1 

### Steps to Reproduce

1. Change some code
1. Select/chant another branch
1. Code will still

**Expected behavior:** Code change also

**Actual behavior:** Code still

**Reproduces how often:** 100%

#### Additional Information

Editor: VS Code

**Comment by shiftkey** [comment]
@Mlocik97-issues when switching branches, Git will error if there are modified changes in the repository that will be overwritten with changes in the destination branch.

If there are no issues, Git will happily bring across those changed files. This is by design.

If you want to discard all your changes, simply right-click the "XX changed files" text and select "Discard All Changes":

<img width="359" src="https://user-images.githubusercontent.com/359239/32630702-c2f19c40-c5f1-11e7-81f9-36cfd163e670.png">

**Comment by Mlocik97-issues** [comment]
It's designed very bad,.. In the original Github for desktop it was better, the changes were postponed/putted away in the branch, and opened the code in the branch, and after returning back to the first branch the code returned.

**Comment by shiftkey** [comment]
@Mlocik97-issues are you referring to the classic Mac or Windows version?

**Comment by shiftkey** [comment]
> It's designed very bad,.. In the old Github for desktop it was better, the changes were postponed/putted away in the branch, and opened the code in the branch, and after returning back to the first branch the code returned.

Please provide more detailed reproduction steps (and screenshots if it helps) from either the current Desktop app or the old app - it's not clear to me what the expected behaviour is, and how this differs from Git itself.

**Comment by Mlocik97-issues** [comment]
In old Github desktop app:

https://youtu.be/BKr8lbx3uFY?t=12m2s

(How Expected)

**Comment by Mlocik97-issues** [comment]
I will try find old screenshot, or how it worked in old app

**Comment by j-f1** [comment]
I think @Mlocik97-issues is referring to magic stashing (#1633).

**Comment by Mlocik97-issues** [comment]
@j-f1 yes,...

**Comment by shiftkey** [comment]
Cool, then please follow along with #1633.

**Comment by Mlocik97-issues** [comment]
but #1633 is closed.

**Comment by shiftkey** [comment]
@Mlocik97-issues please read this comment: https://github.com/desktop/desktop/issues/1633#issuecomment-312100507
