### ISSUE TITLE
Open In Shell Not Working

### ISSUE THREAD

**Issue by say25** [desktop/desktop#3289]
### Open In Shell Not Working

**GitHub Desktop version:** [1.0.9-beta0]

**OS version:** [Windows 10.0.15063]

### Steps to Reproduce

1. Clone Repo
1. Use open in shell command.
- Also of note `open without Git` button also does nothing

**Expected behavior:** GitBash here works

**Reproduces how often:** 100%

### Logs

[2017-11-10.desktop.beta.log](https://github.com/desktop/desktop/files/1459662/2017-11-10.desktop.beta.log)

#### Additional Information

![image](https://user-images.githubusercontent.com/7467062/32637233-4772d868-c57e-11e7-84c4-8a1bf31326ab.png)

**Comment by shiftkey** [comment]
@say25 thanks for the details.

>  GitBash here works

The check we do here is to see if Git exists on your path. If you installed Git after launching Desktop then it won't have received a refreshed `PATH` environment variable, which might explain it's confusion.

Can you open a plain Command Prompt, run this command and attach the output:

```shellsession
echo %PATH%
```

After that, can you see if relaunching Desktop and trying to open the repository in your shell still has issues?

> Also of note `open without Git` button also does nothing

That sounds like a bug. I'll see if I can reproduce it on my end.

**Comment by say25** [comment]
I've had Git installed for 1 year+, I was just trying to practice keyboard yoga and ran into this issue.

`echo %PATH%` output:

Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\syeh>echo %PATH%
C:\ProgramData\Oracle\Java\javapath;c:\oracle\product\11.2.0\client64\bin;c:\oracle\product\11.2.0\client32\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\PuTTY\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.4\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Amazon\AWSCLI\;C:\Users\syeh\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\syeh\AppData\Local\GitHubDesktop\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;

**Comment by shiftkey** [comment]
`C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Git`

This isn't the path you want. It should be `C:\Program Files\Git\cmd` or `C:\Program Files (x86)\Git\cmd` depending on which version you have installed.

**Comment by say25** [comment]
Tried `C:\Program Files (x86)\Git\cmd;` still no luck

**Comment by say25** [comment]
Noticed I need `C:\Program Files\Git\cmd;` 🤦‍♂️ 

Probably `Open without Git` is related?

**Comment by shiftkey** [comment]
> Probably `Open without Git` is related?

Yes. We look for a path to `git.exe` here so that if you were to run `git status` or a similar command, it would succeed. This is different to the shortcuts to the shells.

**Comment by say25** [comment]
Sounds like this should be closed as user error :(
