### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by MylesLeadbeater** [desktop/desktop#3291]
I've created a repo using GithubDesktop on my mac laptop, pushed it, and I get an Authentication Failed when I attempt to clone this repo using GithubDesktop on my PC (I am logged into the same github account on both computers).

**Comment by shiftkey** [comment]
@MylesLeadbeater could you fill out [the issue template](https://raw.githubusercontent.com/desktop/desktop/master/.github/ISSUE_TEMPLATE.md) with information about your setup and attach the relevant log files to we can troubleshoot the issue further?

**Comment by MylesLeadbeater** [comment]
### Description

Unable to clone repository that I own.


### Version

mac: 1.0.8
pc: 1.0.8


**OS version:** [version here]
mac - 10.13.1
pc - Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1.
use github desktop on mac to create a new repository
2.
attempt to clone repository on pc using github desktop signed in as the same github user


**Expected behavior:** [What you expected to happen]

expecting that the repository will be clones as I'm logged into the same user account over both instances of Github Desktop

**Actual behavior:** [What actually happened]

Github Desktop reports an error: "Could not read from repository. Please make sure you have the correct access rights and the repository exists", "Authentication Failed. you may not have permission to access the repository"

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% so far, out of 4-5 attempts.

[2017-11-10.desktop.production.log](https://github.com/desktop/desktop/files/1459953/2017-11-10.desktop.production.log)

**Comment by shiftkey** [comment]
Looks like a submodule has an SSH remote, which is failing because on Windows in a similar way to #2344:

```
2017-11-10T02:15:12.797Z - error: [ui] `git -c credential.helper= lfs clone --recursive --skip-repo --progress -- https://github.com/MylesLeadbeater/druid_workspace_netbeans_pc.git C:\Users\Myles\Documents\GitHub\druid_workspace_netbeans_pc` exited with an unexpected code: 2.
Cloning into 'C:\Users\Myles\Documents\GitHub\druid_workspace_netbeans_pc'...
remote: Counting objects: 7, done.        
remote: Compressing objects:  16% (1/6)           
remote: Compressing objects:  33% (2/6)           
remote: Compressing objects:  50% (3/6)           
remote: Compressing objects:  66% (4/6)           
remote: Compressing objects:  83% (5/6)           
remote: Compressing objects: 100% (6/6)           
remote: Compressing objects: 100% (6/6), done.        
remote: Total 7 (delta 0), reused 7 (delta 0), pack-reused 0        
Submodule 'druid_lib' (git@github.com:MylesLeadbeater/druid_lib.git) registered for path 'druid_lib'
Cloning into 'C:/Users/Myles/Documents/GitHub/druid_workspace_netbeans_pc/druid_lib'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by MylesLeadbeater** [comment]
damn my bad, this isn't a GithubDesktop issue then. 

Does GithubDesktop support adding/viewing submodules? It doesn't seem to so far?

**Comment by shiftkey** [comment]
@MylesLeadbeater it needs some polish, such as https://github.com/desktop/desktop/issues/1803, https://github.com/desktop/desktop/issues/1794 and https://github.com/desktop/desktop/issues/1770
