### ISSUE TITLE
support configuring proxy server in-app

### ISSUE THREAD

**Issue by japj** [desktop/desktop#3294]
### Description

cloning a repo fails with "could not resolve host: github.com

### Version

**GitHub Desktop version:** 1.0.8

**OS version:** Microsoft Windows [Version 10.0.10586]

### Steps to Reproduce

1. clone any repo from github

**Expected behavior:** [What you expected to happen]
Succeeding cloning repo

**Actual behavior:** [What actually happened]
This fails with:

Cloning into 'D:\GitHub\vsts-node-api'...
fatal: unable to access 'https://github.com/japj/vsts-node-api.git/': Could not resolve host: github.com
Error(s) during clone:
git clone failed: exit status 128

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Logs

2017-11-10T08:58:45.992Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/japj/vsts-node-api.git - japj (has token)
2017-11-10T08:58:46.267Z - error: [ui] `git -c credential.helper= lfs clone --recursive --skip-repo --progress -- https://github.com/japj/vsts-node-api.git D:\GitHub\vsts-node-api` exited with an unexpected code: 2.
Cloning into 'D:\GitHub\vsts-node-api'...
fatal: unable to access 'https://github.com/japj/vsts-node-api.git/': Could not resolve host: github.com
Error(s) during clone:
git clone failed: exit status 128

#### Additional Information

I am behind a corporate firewall, but there is no way to setup a proxy in the github desktop application?

**Comment by joshaber** [comment]
>I am behind a corporate firewall, but there is no way to setup a proxy in the github desktop application?

You can configure the proxy from the command line. See https://stackoverflow.com/questions/783811/getting-git-to-work-with-a-proxy-server for more information.

**Comment by joshaber** [comment]
Whoops, looks like our bot got a little too aggressive. Re-opening.

**Comment by japj** [comment]
I think this might be an identical problem to #3264 

Just asking to understand it better, is the intend that GitHub Desktop users will need to find out how to and do the setup of the proxy manually? I might have expected a more "integrated" proxy setting in the Options page.

**Comment by joshaber** [comment]
>Just asking to understand it better, is the intend that GitHub Desktop users will need to find out how to and do the setup of the proxy manually? I might have expected a more "integrated" proxy setting in the Options page.

Currently, yes. We know that's less than great but it's currently the only solution.

**Comment by jojomaracas** [comment]
Jojomaracas I have a copyright and have made something reimagine-train train?? I what do I do

**Comment by shiftkey** [comment]
Flipping this around to focus on this request rather than the initial issue:

> Just asking to understand it better, is the intend that GitHub Desktop users will need to find out how to and do the setup of the proxy manually? I might have expected a more "integrated" proxy setting in the Options page.

I'll leave this to @iAmWillShepherd to triage further.

**Comment by iAmWillShepherd** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md). I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! 

We will revisit this in our next planning session.

**Comment by billygriffin** [comment]
Please follow along with this in #2789
