### ISSUE TITLE
`Create Pull Request` on branch with existing PR should bring user to conversation tab

### ISSUE THREAD

**Issue by zacharyhalvorson** [desktop/desktop#3299]
Currently, hitting `Create Pull Request` on a branch that already has one, brings the user to a compare page instead of the active PR page.

The expected behaviour here is to bring the user to the PR page if open. Also be nice to expose the PR number in the UI once one has been filed.

**Comment by joshaber** [comment]
Thanks for opening this @zacharyhalvorson!

We agree! We're planning to do this in 1.1 and are tracking it in https://github.com/desktop/desktop/issues/2524. Feel free to follow along there.
