### ISSUE TITLE
Unable to check revocation for the certificate

### ISSUE THREAD

**Issue by ZapTechAdmin** [desktop/desktop#3300]
Version 1.0.8

**GitHub Desktop version: Version 1.0.8

Microsoft Windows [Version 10.0.15063]

I am encountering this issue when trying to push a repo from my computer to github:

fatal: unable to access 'https://github.com/ZapTechAdmin/Mega-Menu.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

Any idea what's going on here?

**Comment by joshaber** [comment]
Hi @askbow!

We've had a few reports of this specific error, but it's not been made clear to me how we might be misusing the SChannel APIs, so the best advice I have for you is how to switch over to using the classic OpenSSL APIs alongside your own certificate bundle.

Open a shell to your repository and run these command:

```sh
$ git config --local http.sslBackend "openssl"
$ git config --local http.sslCAInfo [path to .pem file]
```

Then test it out with a `git fetch` to ensure it is able to connect to your server.

**Comment by joshaber** [comment]
Whoops, looks like our bot got a little too aggressive. Re-opening.

**Comment by AtomicCons** [comment]
@joshaber 
Curious if adding a line or two to this error message to along the lines of 
"This error may have been caused by a SSL proxy or firewall. If this is the case, please install the CA's .pem"
Although that may not be the user's case, seems like a cause to a lot of this error.

**Comment by joshaber** [comment]
We could certainly surface a better error message 👍 💯

**Comment by ZapTechAdmin** [comment]
How would I install the CA's pem?

**Comment by AtomicCons** [comment]
git config --global http.sslCAInfo [path to .pem file]

 you don't have the pem or cert and think your traffic's ssl is filtered,
look in your certificate store and export it as a .pem or x509 if pem is
not an available option. Open that certificate as with a text editor and
you should see the key information.
If you can see that key information and the certificate is not a .pem,
change the .cer to . pem

On Nov 14, 2017 3:56 PM, "Joel Bond" <notifications@github.com> wrote:

How would I install the CA's pem?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/desktop/desktop/issues/3300#issuecomment-344428087>,
or mute
the thread

**Comment by ZapTechAdmin** [comment]
@AtomicCons @joshaber 

When running this from the shell, I get this:

$ git push -u origin master
Counting objects: 358, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (337/337), done.
Writing objects: 100% (358/358), 353.81 KiB | 2.30 MiB/s, done.
Total 358 (delta 181), reused 0 (delta 0)
error: RPC failed; curl 56 Illegal or missing hexadecimal sequence in chunked-encoding
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

**Comment by AtomicCons** [comment]
Looks like a firewall, av, or buffer issues. 
first, try this: `git config --global http.postBuffer 524288000`
then try to push. if no success, try this:  `GIT_CURL_VERBOSE=1 git push`

**Comment by ZapTechAdmin** [comment]
Here is what I got when I tried your first suggestion:

```
$ git config --global http.postBuffer 524288000

$ git push
Counting objects: 374, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (353/353), done.
Writing objects: 100% (374/374), 356.74 KiB | 2.35 MiB/s, done.
Total 374 (delta 187), reused 0 (delta 0)
error: RPC failed; curl 56 Illegal or missing hexadecimal sequence in chunked-encoding
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
```

This is what the other command gave me:
```
$ GIT_CURL_VERBOSE=1 git push
* Couldn't find host github.com in the _netrc file; using defaults
*   Trying 192.30.253.113...
* TCP_NODELAY set
* Connected to github.com (192.30.253.113) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* error setting certificate verify locations, continuing anyway:
*   CAfile: private.pem
  CApath: none
* SSL connection using TLSv1.2 / AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=github.com
*  start date: Mar 10 00:00:00 2016 GMT
*  expire date: May 17 12:00:00 2018 GMT
*  issuer: C=UK; CN=UBT (EU) Ltd.; O=UBT (EU) Ltd.
*  SSL certificate verify result: unable to get local issuer certificate (20), c                                                                                                                ontinuing anyway.
> GET /ZapTechAdmin/Mega-Menu.git/info/refs?service=git-receive-pack HTTP/1.1
Host: github.com
User-Agent: git/2.15.0.windows.1
Accept: */*
Accept-Encoding: gzip
Pragma: no-cache

< HTTP/1.1 401 Authorization Required
< Server: GitHub Babel 2.0
< Content-Type: text/plain
< Content-Length: 54
< WWW-Authenticate: Basic realm="GitHub"
< X-GitHub-Request-Id: D677:102F:19A1EB:2CD647:5A0B82F6
< X-Frame-Options: DENY
<
* Connection #0 to host github.com left intact
* Couldn't find host github.com in the _netrc file; using defaults
* Found bundle for host github.com: 0x3367d20 [can pipeline]
* Re-using existing connection! (#0) with host github.com
* Connected to github.com (192.30.253.113) port 443 (#0)
* Server auth using Basic with user 'Personal Access Token'
> GET /ZapTechAdmin/Mega-Menu.git/info/refs?service=git-receive-pack HTTP/1.1
Host: github.com
Authorization: Basic UGVyc29uYWwgQWNjZXNzIFRva2VuOjIzNzliNmRlMmU4ZDJjZTg3MTA1ZjE                                                                                                                yNmZiZGI5MDU4NDRhMWEyYWU=
User-Agent: git/2.15.0.windows.1
Accept: */*
Accept-Encoding: gzip
Pragma: no-cache

< HTTP/1.1 200 OK
< Server: GitHub Babel 2.0
< Content-Type: application/x-git-receive-pack-advertisement
< Transfer-Encoding: chunked
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Vary: Accept-Encoding
< X-GitHub-Request-Id: D677:102F:19A4AF:2CD69A:5A0B82F7
< X-Frame-Options: DENY
<
* Connection #0 to host github.com left intact
Counting objects: 381, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (360/360), done.
Writing objects: 100% (381/381), 358.25 KiB | 2.54 MiB/s, done.
Total 381 (delta 191), reused 0 (delta 0)
* Couldn't find host github.com in the _netrc file; using defaults
* Found bundle for host github.com: 0x3367d20 [can pipeline]
* Re-using existing connection! (#0) with host github.com
* Connected to github.com (192.30.253.113) port 443 (#0)
* Server auth using Basic with user 'Personal Access Token'
> POST /ZapTechAdmin/Mega-Menu.git/git-receive-pack HTTP/1.1
Host: github.com
Authorization: Basic UGVyc29uYWwgQWNjZXNzIFRva2VuOjIzNzliNmRlMmU4ZDJjZTg3MTA1ZjE                                                                                                                yNmZiZGI5MDU4NDRhMWEyYWU=
User-Agent: git/2.15.0.windows.1
Accept-Encoding: gzip
Content-Type: application/x-git-receive-pack-request
Accept: application/x-git-receive-pack-result
Content-Length: 367006

* We are completely uploaded and fine
< HTTP/1.1 200 OK
< Server: GitHub Babel 2.0
< Content-Type: application/x-git-receive-pack-result
< Transfer-Encoding: chunked
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Vary: Accept-Encoding
< X-GitHub-Request-Id: D677:102F:19A61B:2CDB76:5A0B82F9
< X-Frame-Options: DENY
<



```

**Comment by joshaber** [comment]
That second push looks like it succeeded. Or at least I'm not seeing an error in that log?

**Comment by ZapTechAdmin** [comment]
No, I don’t think it did because looking on the github repo there is nothing there and there should be at least 4 files. I tried something a bit different though. I removed the github remote, and added a gitlab remote. The gitlab push and pull works fine, so it must be something with the github servers or something like that….

**Comment by AtomicCons** [comment]
Joel,
hmmmm.
Are you able to successfully pull?
And try to only push 1 file.

**Comment by ZapTechAdmin** [comment]
Yes, I can pull. I will try to just push one file.

**Comment by shiftkey** [comment]
I'm not sure where this issue has ended up, and we've opened #3326 to address the messaging around the original error. Please open a new issue with details and repro steps if you are still encountering curl issues.
