### ISSUE TITLE
Provide user with option to retry when repository can't be found. 

### ISSUE THREAD

**Issue by lukeify** [desktop/desktop#3301]
### Description

When a repository on removable storage (for me, often a USB stick) is unmounted/ejected from the system while GitHub Desktop is running, the application will switch to a view displaying "Can't find `<repo>`, It was last seen at `<location>`" as shown in the image below.

![screen shot 2017-11-11 at 3 22 57 pm](https://user-images.githubusercontent.com/5379845/32685427-d9e365be-c6f5-11e7-9566-234b5a1732c7.png)

Frequently enough, the location of the repository hasn't actually moved. I've just ejected my drive for the day and slept my machine. When I come back to use it again and replug the drive, I'll be presented with that screen, when either:

1. The application could auto-detect the mounting of a new drive and scan it for matching repositories.
2. The application could simply offer a fourth "Try Again" / "Retry" (don't particularly care about the preferred text) button alongside "Locate...", "Clone Again", or "Remove". 

Sure, I could just locate; but often there isn't a _need_ to. The location hasn't changed, the drive has just been unmounted. Give me a quick option to retry its location without having to select from Finder. 

### Version

**GitHub Desktop version:** 1.0.8
**OS version:** macOS 10.13.0 w/ Supplemental Update

### Steps to Reproduce

1. Have repo on removable storage plugged in and GitHub Desktop set on a repository on that drive.
2. Unmount removable storage.
3. Bring GitHub Desktop into focus.

### Expected behavior

Repository is automatically (via option 1 described above) found, or allows user the option to try again (via option 2 described above).

### Actual behavior

User is presented with screen (image above) offering to "Locate...", "Clone Again", "Remove". 

### Reproduces how often 

Always

### Logs

N/A

#### Additional Information

None.

**Comment by joshaber** [comment]
Huh, that's an interesting use case. Thanks for letting us know @lukeify!

**Comment by nerdneha** [comment]
Hi @lukeify, thanks again for this data point. We've noted it as a suboptimal user interaction, but this is beyond the scope of our current roadmap. For now, the workaround is to re-locate the repo with the `Locate...` button and we'll keep a watch on this.

I am closing it so that we won't get overwhelmed with our backlog but encourage you to keep engaged with us on future issues!

**Comment by iAmWillShepherd** [comment]
@j-f1, we did not add the `future-proposal` label since this is an issue that we won't revisit in the future: there is an already a solution to the problem retry button is supposed to solve.
