### ISSUE TITLE
Critical bug: GitHub desktop belives files are changed which are not

### ISSUE THREAD

**Issue by danielb987** [desktop/desktop#3302]
My repository is a fork of JMRI repository:
https://github.com/danielb987/JMRI

I remove my repository in GitHub Desktop and then delete my JMRI folder om my computer. Then I clone my repository with GitHub Desktop. When GitHub Desktop is done, it tells me that I have five changed files that I should commit.

I can change to another branch in my repository, and then I change back to my main branch, these five files appear again as changed.

This is a critical error since these files has not been changed by me and I should not do a commit with them.

I'm using GitHub desktop version 1.0.8 on Windows 8.1.

**Comment by danielb987** [comment]
This is how GitHub Desktop looks like after I have cloned my JMRI repository.
![github_desktop_1](https://user-images.githubusercontent.com/20255317/32685799-bfdb1bd8-c698-11e7-8056-363170ea17f2.png)

I then select one of my branches in this repository:
![github_desktop_2](https://user-images.githubusercontent.com/20255317/32685800-c020299e-c698-11e7-82c9-711feaf9f318.png)

I then go back to my main branch:
![github_desktop_3](https://user-images.githubusercontent.com/20255317/32685801-c03e67f6-c698-11e7-993c-64d27b733911.png)

I now have these six files that are shown as changed and that GitHub Desktop expect me to do a commit on these files. But I have NOT changed any of these files. For whatever reason, GitHub Desktop fails to clone these files in the correct way.

**Comment by Raul6469** [comment]
Hello @danielb987,
I rather think that your problem comes from Git itself, not GitHub Desktop. Try opening the Git command line, and execute `git status` while you are in the master branch to have an idea on what is going on.

**Comment by danielb987** [comment]
Yes. The problem seems to be that someone has changed the case of some letters in the file names. If the only change is change of case, git fails to handle it on Windows.

**Comment by joshaber** [comment]
Git is case insensitive by default and as such sees no difference between two files with different casings.

There are a few different ways to solve this, depending on what you want to accomplish. See https://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git for more information.

**Comment by danielb987** [comment]
Thanks. But the problem in this case is not that I want to change the case of the filename. The problem is that someone else has changed the case of a filename, and that git now thinks that I have changed the filename since my filename is different from the master.

If someone else has done a commit there the file "filename.java" is changed to "FileName.java", git fails to handle that correctly for me on Windows.

And the interesting part is that if I completely delete the entire project folder on my harddrive and then clone my forked repository, I still get this problem. See the second comment in this thread, the comment with all the pictures. So it doesn't help to delete the files on my harddrive and then clone the files.

Note that I haven't configured Git at all. I don't use command line git. I downloaded GitHub Desktop and only use that on my Windows computer.

**Comment by joshaber** [comment]
Whoops, looks like our bot got a little too aggressive. Re-opening.

**Comment by shiftkey** [comment]
> Note that I haven't configured Git at all. I don't use command line git. I downloaded GitHub Desktop and only use that on my Windows computer.

GitHub Desktop uses an embedded version of Git, so the same command line limitations exist for us. I wrote about a very similar issue to this a while ago (the repository has a tree where entries differ by case, so files would appear changed) and explained about how the filesystem limitations affect Git repositories: https://github.com/desktop/desktop/issues/2672#issuecomment-329011490. This follow-up comment is also worth reading: https://github.com/desktop/desktop/issues/2672#issuecomment-338171399

Aside from changing the repository to be more tolerant on case-insensitive filesystems like macOS and Windows, there's not much else we can do here.

Let me know if you have any additional questions around this.

**Comment by danielb987** [comment]
Thanks to both @joshaber and @shiftkey for your answers.

Can I use the git that is included in GitHub Desktop, and if so, how? I haven't installed git on my Windows computer, I only uses GitHub Desktop on that computer.

It seems from your links that it would help me if I could set core.ignorecase to true. How do I do that?

**Comment by shiftkey** [comment]
> Can I use the git that is included in GitHub Desktop, and if so, how? I haven't installed git on my Windows computer, I only uses GitHub Desktop on that computer.

I'm afraid not - you can grab a command line version of Git from [here](https://git-for-windows.github.io/).

> It seems from your links that it would help me if I could set `core.ignorecase` to true. How do I do that?

I don't recommend doing this as it'll introduce a whole bunch of other problems.

**Comment by vanvught** [comment]
This is still an issue.

**Comment by aukaurea** [comment]
This issue still persist.

**Comment by bastiaanno** [comment]
This issue is still there.

**Comment by Singtah** [comment]
Running on Windows 10 here. Changing `core.filemode` to **false** solved the issue for me. Here's my config : 

```
credential.helper=cache
core.autocrlf=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
```

**Comment by niteshjha1** [comment]
> Running on Windows 10 here. Changing `core.filemode` to **false** solved the issue for me. Here's my config :
> 
> ```
> credential.helper=cache
> core.autocrlf=true
> core.repositoryformatversion=0
> core.filemode=false
> core.bare=false
> core.logallrefupdates=true
> core.ignorecase=true
> ```

Thanks, It worked for me on my mac too by changing it to false in git config file on mac
