### ISSUE TITLE
Desktop can't detect latest VS Code on Win7 x64 (+workaround)

### ISSUE THREAD

**Issue by zistenz** [desktop/desktop#3304]
**Problem:** Windows 7 (x64), fresh install of latest Github Desktop (1.0.8) and Visual Studio Code (1.17+), GD can't detect VSC as editor.

**Causes:** After figuring out how `win32.ts` detects the installed editors and watching the verbose log in dev tools during detection, I found two possible causes:

1. Lately VSC changed its `displayName` key to *"Microsoft Visual Studio Code"*.
2. If you installed VSC to a different Start Menu group (*"utils\VSC"* in my case), detection will also fail because of the non-default `Inno Setup: Icon Group` key value.

**Workaround:** Change both `displayName` and `Inno Setup: Icon Group` keys to *"Visual Studio Code"*. These are under *HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\\{EA457B21-F73E-494C-ACAB-524FDE069978}_is1* on Win7-x64. Re-run Github Desktop detection (File - Options). It should detect VSC correctly now and VSC should appear in the Repository menu. Save the config, then change back both registry keys to their original values. If you ever re-open Options, detection will fail again, so you have to do this every time you change Desktop preferences (until GD will get a better detection).

**Comment by joshaber** [comment]
Thanks @zistenz! If you were interested, a PR with those changes would be great!

**Comment by AtomicCons** [comment]
@joshaber @zistenz 
Added the displayName to pull request #3321

as far as custom install of vsc, I am not sure how we could get it to detect where it would be put. Any ideas?

**Comment by zistenz** [comment]
I think `Icon Group` shouldn't be in the detection rules. It's totally custom and unpredictable because of the possible user input during the VSC setup process. `HelpLink` and the last part of `DisplayIcon` could be better, they're always static it seems.

Or maybe the autodetect isn't as relevant as it looks. What if users able to customize their own editors, including path and etc? It's the Github Desktop app for repo management, everyone hacks and forks everyone's stuff on Git, and want to control over their own stuff. Maybe it should be their responsibility.

**Comment by joshaber** [comment]
The display name change landed in https://github.com/desktop/desktop/pull/3321. Unfortunately my Windows knowledge isn't good enough to provide any advice on on the icon group front.

**Comment by shiftkey** [comment]
> I think Icon Group shouldn't be in the detection rules. It's totally custom and unpredictable because of the possible user input during the VSC setup process. HelpLink and the last part of DisplayIcon could be better, they're always static it seems.

Yeah, don't worry about the mention of icon here. I've opened #3373 to close this out and explain the choices in better detail.
