### ISSUE TITLE
Github sending an automatic ssh request every five minutes does not play nice with external authenticators e.g. Kryptonite

### ISSUE THREAD

**Issue by jm3** [desktop/desktop#3306]
### Description

GitHub Desktop appears to do a git fetch (or the equivalent) automatically every 5 minutes, presumably to keep track of any updates to the remote. For users who use a second-factor SSH authenticator e.g. [Kryptonite](https://krypt.co/), GitHub Desktop's automatic pinging will continually trigger new push requests to your mobile device automatically **every five minutes** so long as the GitHub desktop app is open. 😧 This seems… less than ideal.

### Version

**GitHub Desktop version:** 1.0.8

**OS version:** OS X 10.12.6 (16G29)

### Steps to Reproduce

1. Launch GitHub Desktop
1. Leave it open
1. Receive an unending stream of authentication push notifications so long as the app remains open.

**Expected behavior:**

I realize that this is a non-standard use case, but It Would Be Nice If™ Github Desktop made the ssh query interval configurable, or optional.

**Actual behavior:** Receive many successive authentication push notifications so long as the app remains open.

**Reproduces how often:** 100%

### Logs

`~/Library/Application Support/GitHub Desktop/logs/` does not exist on my mac; ~/Library/Application Support/GitHub Desktop/logs/

#### Additional Information

![github-desktop-krypt](https://user-images.githubusercontent.com/12213/32694466-41898424-c6f5-11e7-8913-a9debcf38b2c.png)

**Comment by joshaber** [comment]
Thanks @jm3! That's a really interesting case. We're already tracking the ability to disable auth-fetching in https://github.com/desktop/desktop/issues/1128 so I'm gonna close this and add your use case over there.
