### ISSUE TITLE
enhancement: optionally show relative dates, not just absolute

### ISSUE THREAD

**Issue by jm3** [desktop/desktop#3307]
### Description

Like Github.com, it would be nice if commit dates were displayed in relative form — e.g. "1 day ago", "2 hours ago", etc. — rather than just "October 2, 2017".

### Version

**GitHub Desktop version:** 1.0.8

**OS version:** OS X 10.12.6 (16G29)

**Expected behavior:** Dates in relative form, with an optional toggle in Settings to switch between absolute and relative dates.

**Actual behavior:** only absolute calendar dates are displayed

**Reproduces how often:** 100%

**Comment by j-f1** [comment]
I’m pretty sure the app already does that for recent dates — a relative date for October 2 wouldn’t be very helpful.

**Comment by jm3** [comment]
@j-f1 doh, you're right. i was looking at an old repo. WORKS_FOR_ME
