### ISSUE TITLE
keyboard events from app menu still triggered when displaying modal

### ISSUE THREAD

**Issue by samdenty99** [desktop/desktop#3308]
### Description

Keyboard events still triggering in modal

### Version

**GitHub Desktop version:** 1.0.9-beta0

**OS version:** Windows

### Steps to Reproduce

1. Open repository settings dialog
2. Press CTRL-B

**Expected behavior:** Keyboard event should be ignored

**Actual behavior:** Branch switcher opens in background

![image](https://user-images.githubusercontent.com/13242392/32699432-7ad37a06-c7ad-11e7-83ce-0260ad67a234.png)

**Comment by tierninho** [comment]
This is reproducible in Windows and Mac (via CMD button), with actions not limited to just 'Branch list'. No logs found.

Should we allow overrides of current modal/dialogue, as there a few dialogues that require acknowledgement before dismissing?
