### ISSUE TITLE
Just some thoughts on the new desktop client UI

### ISSUE THREAD

**Issue by Neon-Ape** [desktop/desktop#3313]
You had an intuitive client (i just started using GitHub in May, never needed any introduction to what was where in the client), then all of a sudden there's this new version.
I think: cool new tech lets get it. I install it, try it out for a few days, uninstalled because what where you thinking?
I'm no Ben Schneiderman, but if you have longer action paths in a new version compared to an old version, that's what our UX professor would call a fail.
Adding a Repository (you know kind of an every day thing) went from 2 clicks to 3, but i really appreciate the shortcuts (Schneiderman's 2nd rule would be proud).
A big plus sign is arguably way more intuitive then a menu tree. (yeah it's only one click more, but you have to find it first, i had a lot more clicks than 3 on my first try)
The same goes for adding branches.
I guess you have a theme going on: 
Step 1: remove one-click options at locations that make sense. 
Step 2: add it to some menu, so i can search for it, who doesn't like a good search?
Step 3: add a shortcut so powerusers will actually be faster in this UI while the UI itself got worse.
(i really really like the shortcuts, but why did all the intuitive UI have to leave?)
Where did branch comparison and graphic branch UI go? I have found no way to reproduce the functionality you had with that. Revert to an older state? Click -> press button. That's fast and really easy to use.
I'm sad that the current client was a sizable step backwards for no apparent reason.

PS: why is there no dark mode? The new client has class based styling, it's easier to do now.

**Comment by j-f1** [comment]
For the dark mode, see #1515. TL;DR: Desktop only has two designers, and time they spend on a dark theme is time not spent on other new features.

**Comment by joshaber** [comment]
Thanks for the feedback @Neon-Ape!

We're still trying to find the right balance of surfacing common functionality while not overwhelming people with buttons. Specifically with respect to the "Add a repository" button, our stats tell us it's _not_ something people use very often. So we've chosen to optimize the blank slate view when there are no repositories, but the rest of the time get the UI out of the way.

>Where did branch comparison and graphic branch UI go? I have found no way to reproduce the functionality you had with that.

We miss it too. We're investigating bringing some of that functionality back in https://github.com/desktop/desktop/issues/2639.
