### ISSUE TITLE
Capitalization changes in file names not detected in windows

### ISSUE THREAD

**Issue by zabi94** [desktop/desktop#3314]
### Description

Renaming a file under windows by changing only capitalization of the file name results in the desktop client not detecting any changes. To actually rename the file in remote I had to change the file name from the github website and then syncing it to my pc.

### Version

**GitHub Desktop version:** Chocolate-Covered Yaks (3.3.4.0) 50415df

**OS version:** Microsoft Windows [Version 10.0.16299.19]

### Steps to Reproduce

In my case it was
1. Have a file named zh_CN.lang just merged from a PR
2. Renamed the file on my machine to zh_cn.lang
3. The client doesn't realize the filename has changed. Restarting it doesn't help

**Expected behavior:** GitHub should list the change under the "changes" tab in order for me to commit

**Actual behavior:** GitHub doesn't list the change

**Reproduces how often:** Everytime a file is renamed by only changing the letters' case

### Logs

The windows path of the logs folder in the issue template seems to be outdated, it doesn't exist.
(`%APPDATA%\GitHub Desktop\logs`)

**Comment by j-f1** [comment]
> GitHub Desktop version: Chocolate-Covered Yaks (3.3.4.0) 50415df

Thanks! It looks like this issue is with the Classic apps, but this repository is for issues with the redesigned GitHub Desktop (see https://desktop.github.com).

The classic app has been deprecated and won’t get any more updates, so we recommend switching to the new version.

**Comment by zabi94** [comment]
Oh, good to know, perfect

**Comment by thibaultmol** [comment]
I'm having the exact same problem. But in the new Electron app version of Desktop

**Comment by j-f1** [comment]
Please open a new issue and fill out the template so we can help you @thibaultmol.

**Comment by shiftkey** [comment]
@thibaultmol @j-f1 I'm pretty sure this is the same as #2672 and I've written up why this is a known issue in this comment: https://github.com/desktop/desktop/issues/2672#issuecomment-329011490
