### ISSUE TITLE
Status indicator fore repos in the list. (changed files etc)

### ISSUE THREAD

**Issue by Rojoss** [desktop/desktop#3315]
**ENCHANCEMENT**
It would be really useful to have some icons in the repo list that indicate the status.
Especialy if you have changed files.
I work in a project with 10 repos and some times it's hard to keep track of what repos I modified.

I previously used SourceTree but that software has just been getting worse and worse with each update.
![image](https://user-images.githubusercontent.com/1093861/32728281-f8040374-c87f-11e7-83f1-92c6c6a07f54.png)

![image](https://user-images.githubusercontent.com/1093861/32728387-6b0e04be-c880-11e7-8c45-a2172409f332.png)

Even if it's only an icon that indicates there are changes that would be good enough, the details if files are modified, removed, added and how many doesn't really matter.
It would be nice if it also showed that the remote branch is ahead but that is not that important for me.

![image](https://user-images.githubusercontent.com/1093861/32728543-033920a2-c881-11e7-8f39-8757d833f138.png)

**Comment by joshaber** [comment]
Thanks @Rojoss! We're currently tracking this broadly in https://github.com/desktop/desktop/issues/2259. Feel free to follow along over there!

**Comment by Rojoss** [comment]
A great, thanks was looking for it but couldn't find it.
