### ISSUE TITLE
The minimize tooltip is still displayed on the desktop

### ISSUE THREAD

**Issue by GuguAbrams** [desktop/desktop#3319]
### Description

The minimize tooltip is still displayed on the desktop when app has been minimized.

### Version

**GitHub Desktop version:** 1.0.8

**OS version:** Server 2008 R2 X64

### Steps to Reproduce

Move to the minimize button quickly, and click it quickly before the tooltip is displayed.

![1](https://user-images.githubusercontent.com/2210040/32756758-ab083274-c916-11e7-8e88-4e80017430f3.jpg)

![2](https://user-images.githubusercontent.com/2210040/32756764-b2c8836a-c916-11e7-9d38-859327315d9d.jpg)

**Comment by j-f1** [comment]
Thanks for contributing!

Unfortunately, this is an Electron issue. See electron/electron#9943 for details.

**Comment by JakubSteplowski** [comment]
Just a suggestion: 
Why can't it be removed at all?
I think everyone on Windows know how to minimize a window, and not every software have the tooltip.

And a question (sorry for my ignorance):
Why it works correctly and looks different on Atom and Visual Studio Code?

Sorry for writing it here, but I think opening another issue about this will be useless.

Thanks.

**Comment by shiftkey** [comment]
> Why it works correctly and looks different on Atom and Visual Studio Code?

@JakubSteplowski both of these apps use the default Windows theme when drawing the window menu. Desktop instead hides this chrome and draws it's own menu to fit better with the dark toolbar (Electron doesn't support this out of the box).

**Comment by JakubSteplowski** [comment]
@shiftkey it's something I noticed now, on v1.0.9 it doesn't occur anymore, did you fix this or it's working just for me for some reason?
It isn't present in the release notes, so I'm asking.

**Comment by shiftkey** [comment]
@JakubSteplowski no, it's just a race condition between drawing the tooltip and making the window disappear using the keyboard. As I mentioned over in #2874:

> As the [original Chromium issue suggests](https://bugs.chromium.org/p/chromium/issues/detail?id=724538), it's a combination of using a tooltip and triggering a certain sequence of window messages (which can occur when you force the window to minimize) that reproduces this.
