### ISSUE TITLE
Open in Powershell - Unable to locate Git

### ISSUE THREAD

**Issue by AtomicCons** [desktop/desktop#3324]
### Description

When trying to open the repo with PowerShell, I get  the error dialog box 'Unable to locate Git'.
![image](https://user-images.githubusercontent.com/22971111/32786558-85e4d06a-c911-11e7-8886-367096758d87.png)
I then click 'Open without Git', the dialog box closes then quickly reopens.

### Version
- GitHub Desktop 1.0.8
- Windows 10 1703
-Git not installed

### Steps to Reproduce
1. Open GitHub Desktop 
2. Click 'Current repository' tab 
3. Right-click repo
4. Click 'Open with powershell'
5. Click Open without Git

**Expected behavior:** I would expect when I click Open without Git, PowerShell is launched in that Directory location.

**Actual behavior:** Dialog box closes then reopens

**Reproduces how often:** Evertime

***Work Around:*** Install Git

**Comment by j-f1** [comment]
Thanks for reporting this!

We’ve fixed the issue in #3290, which should be part of the next update.

**Comment by vczh** [comment]
@j-f1 I download one today and it still repro. When will you release the "next update"?

**Comment by j-f1** [comment]
Can you open a new issue for this and fill out the template @vczh? This sounds like a new bug.

**Comment by vczh** [comment]
@j-f1 Opened

**Comment by caohappy** [comment]
Me too.Hope you fix this issue quickly.

**Comment by j-f1** [comment]
@caohappy We’d appreciate it if you could provide us with some steps to reproduce the problem over in #3923!

**Comment by vczh** [comment]
@j-f1 I remembered that the last time I open exactly the same issue, Github Desktop developers said that this is by design. They won't install posh-git for us forever. You can choose to do them yourself.
