### ISSUE TITLE
Keyboard shortcuts for branch operations

### ISSUE THREAD

**Issue by adamreisnz** [desktop/desktop#3327]
Would it be possible to create some keyboard shortcuts for these two menu items?

![image](https://user-images.githubusercontent.com/490562/32811764-54bf891c-ca06-11e7-8da7-e50f95b6646b.png)

I use them quite frequently and it'd be nice to have a shortcut for them 👍

**Comment by joshaber** [comment]
Yup, I'm into it 👍
