### ISSUE TITLE
Don't always fetch after switching repo's and/or fetch less often

### ISSUE THREAD

**Issue by adamreisnz** [desktop/desktop#3329]
Hi all, a small suggestion for an improvement; 

Currently, every time you switch to a different repository, the first thing the app does is fetch. It does so, even though it may have just done it 5 seconds ago for that same repository.

Would it be possible to keep track of when an (auto) fetch was last done for a repository, and then avoid doing it too often? For example no more than once every minute.

I switch back and forth between different repositories a lot, and this makes the app fetch over and over again, quite redundantly. I think this is bad for 3 reasons:

1) It locks the push/pull button. If after a previous fetch you could already push/pull, you now can't, and have to wait until the fetch is done. To reproduce this, go to a repo, await the fetch, and ensure there's something to push/pull. Then switch to another repo, and then switch back again and try to push/pull.

2) The spinning action is slightly distracting, as you eye naturally is drawn towards movement. While it's nice to know when the app is fetching, if it's doing it _all the time_ it becomes a bit of a nuisance and distraction.

3) A slight waste of resources (processing power, bandwidth, etc).

What do you think?

**Comment by joshaber** [comment]
Yeah I think that's a reasonable request, especially since it _does_ block pushing until it's done.
