### ISSUE TITLE
Failed to parse status line for changed entry

### ISSUE THREAD

**Issue by Puffton** [desktop/desktop#3334]
### Description

Upgraded from the separate/old Github Desktop to this new client (v1.08), getting parse error dialogs.

### Version

**GitHub Desktop version:** 1.08, downloaded version (not compiled by myself).

**OS version:** OS X 10.13.1

### Steps to Reproduce

Every time I start the app, or focus on the apps window, or switch tab in the left menu to "Changes", I get multiple error dialogs. Example:

Failed to parse status line for changed entry: 1 .T N... 120000 120000 100755 6165716e8b408ad09b51d1a37aa1ef50e7f84376 6165716e8b408ad09b51d1a37aa1ef50e7f84376 pdf_linux-x64/lib/libQt5Core.so.5

This was not the case with the old client.

**Comment by joshaber** [comment]
Thanks for opening this @Puffton!

Interestingly, that status line contains a status code that git doesn't document 😱 

What does `git status` on the command line say?

**Comment by joshaber** [comment]
Aha, it means type change!

https://github.com/git/git/blob/89ea799ffcc5c8a0547d3c9075eb979256ee95b8/diff.h#L371

**Comment by Puffton** [comment]
On branch master
	Your branch is up-to-date with 'origin/master'.
	Changes not staged for commit:
	(use "git add/rm <file>..." to update what will be committed)
	(use "git checkout -- <file>..." to discard changes in working directory)

	typechange: pdf_linux-x64/lib/libQt5Core.so.5
	typechange: pdf_linux-x64/lib/libQt5DBus.so.5
	typechange: pdf_linux-x64/lib/libQt5EglFSDeviceIntegration.so.5
	typechange: pdf_linux-x64/lib/libQt5Gui.so.5
	typechange: pdf_linux-x64/lib/libQt5Network.so.5
	typechange: pdf_linux-x64/lib/libQt5Positioning.so.5
	typechange: pdf_linux-x64/lib/libQt5PrintSupport.so.5
	typechange: pdf_linux-x64/lib/libQt5Qml.so.5
	typechange: pdf_linux-x64/lib/libQt5Quick.so.5
	typechange: pdf_linux-x64/lib/libQt5QuickWidgets.so.5
	typechange: pdf_linux-x64/lib/libQt5WebChannel.so.5
	typechange: pdf_linux-x64/lib/libQt5WebEngineCore.so.5
	typechange: pdf_linux-x64/lib/libQt5WebEngineWidgets.so.5
	typechange: pdf_linux-x64/lib/libQt5Widgets.so.5
	typechange: pdf_linux-x64/lib/libicudata.so.56
	typechange: pdf_linux-x64/lib/libicui18n.so.56
	typechange: pdf_linux-x64/lib/libicuuc.so.56
	deleted:    tmp/css

  	no changes added to commit (use "git add" and/or "git commit -a")

**Comment by joshaber** [comment]
Thanks again @Puffton! This should be a straightforward fix.
