### ISSUE TITLE
"minimized" label appears on windows when minimizing github

### ISSUE THREAD

**Issue by rafikalid** [desktop/desktop#3341]
i have an issue with github disktop o windows

when i minimize the app, a tooltip containing "Minimize" appears on the screen, and persist until i open the app again

**Comment by tierninho** [comment]
Thanks for contributing!

Unfortunately, this is an Electron issue. See electron/electron#9943 for details.

**Comment by rafikalid** [comment]
this happens when i click on "minimize" button before the tooltip appears, so it persists there
