### ISSUE TITLE
Github Desktop window outside screen boundaries

### ISSUE THREAD

**Issue by CvanLeeuwenFt** [desktop/desktop#3342]
Since today GitHubDesktop starts but is not visible on the screen.

I'am using GitHubDesktop for a couple of months now. After the last update it does not work anymore.
It looks like that it has been positioned outside the screen boundaries.

The icon is visible on the taskbar and I show also that the application is running.
The same in the taskmanager.

**GitHub Desktop version:** [1.0.8]
OS:
Microsoft Windows [Version 10.0.16299.64]

**Expected behavior:** 
GitHubDesktop window shows up on the screen

**Actual behavior:**

After pushing the icon on the taskbar, the window shows up and move outside the screen.

**Reproduces how often:** 
every time

**Solution:**
Remove  window-state.json
from  \AppData\Roaming\GitHub Desktop

**Comment by tierninho** [comment]
@CvanLeeuwenFt Thanks for reporting. Any screenshots you can share, before one of the core members responds to the issue?

**Comment by CvanLeeuwenFt** [comment]
This file:
![image](https://user-images.githubusercontent.com/13519935/32887499-654bc944-cac4-11e7-96fd-23353e2de22d.png)

**Comment by CvanLeeuwenFt** [comment]
Every time restart GiHubDesktop it moves more and more outside the screen.
After 3 times I need again to delete the window-state.JSON file.
Can it be that  there exist a bug in the positioning algoritme?

**Comment by joshaber** [comment]
This sounds like it could be related to https://github.com/desktop/desktop/issues/2107.

@CvanLeeuwenFt Are you using multiple monitors?

**Comment by CvanLeeuwenFt** [comment]
Yes. however after switching of the secondary monitor the problem was still their.

**Comment by joshaber** [comment]
In that case I'm gonna combine this with https://github.com/desktop/desktop/issues/2107. Feel free to follow along over there.

**Comment by gurkanakcakaya** [comment]
It's an old issue but maybe it can be useful to somebody, to open it you can go to AppData/Roaming/github Desktop/
Rename the Cache folder to Old_Cache or just remove it this will bring you back the dekstop

**Comment by moises-gonzalez** [comment]
- Deleting the cache folder didn't work for me.
- Editing the windows-state JSON file and changing "isMaximized" to **true** made the trick for me...
After this change, close and reopen the application has no trouble. 
I haven't tries reboot the computer yet, but at least there is a workaround. 

I hope this bug could be resolved soon... 

I'm attaching a screenshot of the version I currently have, actually the latest.

![image](https://user-images.githubusercontent.com/16418678/50777295-cacb6b00-1260-11e9-925a-641769808447.png)


Best regards.

**Comment by davidclayton** [comment]
Thank you, editing the window-state worked.  I was using a second monitor, and then tried to use the Surface-Pro on its own to get this behavior.  I used to be able to use Shift-Right Click to do this.

**Comment by JanTimmerman** [comment]
Perhaps interesting to note: The problem for me started when I moved to a different desk, where my screen configuration is different (laptop + fixed display). I rearranged my displays back to the original configuration. ('Select and rearrange display" in Windows) et voila: GitHub Desktop is appearing again.
