### ISSUE TITLE
Unable to push a new branch to remote stream

### ISSUE THREAD

**Issue by Venkat5694** [desktop/desktop#3343]
While attempting to push a new branch I get the following error message.
`Authentication failed. You may not have permission to access the repository. Open preferences and verify that you're signed in with an account that has permission to access this repository.`

Can someone say why this seems to happen?

I'm trying to push changes that I have made to this repository to submit the fix for #3206

**Comment by joshaber** [comment]
Copying from https://github.com/desktop/desktop/issues/3206#issuecomment-344920652:

>When I try to push my branch via CLI using the command 
`git push --set-upstream origin fix-unborn-repo-description` 
 I get the following error message 
>
>`remote: Permission to desktop/desktop.git denied to Venkat5694.
fatal: unable to access 'https://github.com/desktop/desktop.git/': The requested URL returned error: 403`

It looks like you're trying to push directly to `desktop/desktop`, which you don't have permissions for. Fork it first, and then push to your fork.
