### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by fyc1007261** [desktop/desktop#3346]
if you click the minimize button too quickly, the window will be minimized before the message "minimized" is shown. Then the message will be left and cannot be erased until you open desktop again.

**Comment by joshaber** [comment]
Thanks for contributing!

Unfortunately, this is an Electron issue. See electron/electron#9943 for details.

**Comment by lalomartins** [comment]
Even though it's closed, for the sake of people searching in the future — can someone with power please rename the issue to something more meaningful? Like, “Minimize tooltip stays behind when window is minimized”.
