### ISSUE TITLE
Microsoft Pinyin input method not working

### ISSUE THREAD

**Issue by MouseJW** [desktop/desktop#3354]
### Description

使用 GitHub Desktop 新建一个库并为新的库添加描述信息，在用微软拼音输入法输入中文时，会显示一连串的拼音，选择汉字后拼音还会存在

### Version

GitHub Desktop version:  1.0.9

![20171117135651](https://user-images.githubusercontent.com/24412152/32933481-2d27da44-cba5-11e7-8e70-3e9347af719f.jpg)

**OS version: Microsoft Windows 10.0.10240

![20171117140831](https://user-images.githubusercontent.com/24412152/32933010-3e9482d8-cba4-11e7-8bba-28327d782939.jpg)

### Steps to Reproduce

1、打开 Github Desktop
2、选择菜单： File > new repository 
3、聚焦到 Description 输入框
4、将输入法切换到微软拼音
5、随意输入汉字就能发现问题

**Expected behavior:** 

正确的输入库的描述

**Actual behavior:** 

输入的描述里包含有汉字的拼音

**Reproduces how often:**

一直出现

#### Additional Information

![20171117134954](https://user-images.githubusercontent.com/24412152/32932012-fdf51848-cba1-11e7-84cb-1a272d45dde8.jpg)

**Comment by tierninho** [comment]
Steps to reproduce

"1, open Github Desktop
2, select the menu: File> new repository
3, focus to Description input box
4, the input method to switch to Microsoft Pinyin
5, the Chinese characters want to be able to find the problem"

Expected:
"Enter the description of the library correctly"

Actual:
"Enter the description contains the pinyin of Chinese characters"

**Comment by shiftkey** [comment]
I can reproduce this, and before I dig deeper into this I want to provide some context.

When you enable this keyboard and open Notepad, typing a normal character will display a number of options to autocomplete:

<img width="544" alt="screen shot 2017-11-24 at 3 11 54 pm" src="https://user-images.githubusercontent.com/359239/33195209-d74329a0-d129-11e7-933e-d6a90cd23840.png">

When you choose one of these options, it is supposed to replace the character I entered:

<img width="252" alt="screen shot 2017-11-24 at 3 12 00 pm" src="https://user-images.githubusercontent.com/359239/33195228-e9a4b668-d129-11e7-9cbe-9dd66ea1e371.png">

If I try and do the same thing in Desktop, it will append the new character to the text box:

<img width="352" alt="screen shot 2017-11-24 at 3 13 17 pm" src="https://user-images.githubusercontent.com/359239/33195253-12eb9ab4-d12a-11e7-8d3f-bfcf168fe697.png">

Chrome does the right behaviour, so this might be something we've introduced in Desktop. I need to step through the code more closely and figure out what we might be doing wrong.

**Comment by shiftkey** [comment]
This is related to https://github.com/desktop/desktop/pull/2333 and how we manage the caret position. The original issue was specific to "Add Local Repository" so I think we should retest that area and see if there's a better way to fix it...
