### ISSUE TITLE
Unable to setup or link account with github enterprise server

### ISSUE THREAD

**Issue by asishm** [desktop/desktop#3361]
### Description

During Github Desktop setup, unable to sign in to the enterprise server.
Skipping the step during setup and then re-trying to add enterprise account also fails
Cloning from a repo hosted on the work server using the URL fails as well

[Log](https://hastebin.com/higocedoqu.log)

### Version

**GitHub Desktop version:** 1.0.9

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Setup using enterprise account - fails
2. Skip linking account during setup
3. Try to link enterprise account after setup completes or clone repo hosted on that server, also fails
4. Linking account shows an Untrusted Server and has an option to "add certificate". But clicking that does nothing

**Expected behavior:** successfully link account and list my repos

**Actual behavior:** unable to link account 

**Reproduces how often:** 100%

### Logs

https://hastebin.com/higocedoqu.log

#### Additional Information

I can access the repos online through Chrome, although it did show a warning about an untrusted server, which I added the certificate and it let me in through to the login screen to enter my enterprise credentials.

I can also use the git bash cli with the `http.sslVerify` set to `False` and it lets me clone/authenticate (on another device that doesn't have Github Desktop installed)

**Comment by shiftkey** [comment]
Two interesting errors from the log:

```
2017-11-17T22:59:36.033Z - error: [ui] fetchMetadata: unable to load metadata from 'https://github.<>.com/api/v3/meta' as a fallback
TypeError: Failed to fetch
```

```
fatal: unable to access 'https://github.<>.com/<>/<>.git/': schannel: SNI or certificate check failed: SEC_E_WRONG_PRINCIPAL (0x80090322) - The target principal name is incorrect.
Error(s) during clone:
git clone failed: exit status 128
```

@asishm Is there something interesting about the certificate associated with the GitHub Enterprise server that we haven't had to deal with in our testing?

> I can access the repos online through Chrome, although it did show a warning about an untrusted server, which I added the certificate and it let me in through to the login screen to enter my enterprise credentials.

We added support for probing the GitHub Enterprise server and handling self-signed certificates, but if there's a different sort of trust issue here then maybe we need to think about what to do here. What message did Chrome report?

**Comment by asishm** [comment]
@shiftkey I'll ask around IT about the certificate they're using. This will probably happen after the weekend though, since it's past work hours.


![image](https://user-images.githubusercontent.com/1978117/32974274-de463d50-cbca-11e7-9ee0-81ba95270ab4.png)
This is what Chrome showed

**Comment by shiftkey** [comment]
Desktop relies on the Windows Certificate store for it's network and Git operations, using the Chromium networking stack (the same behaviour as Chrome) and [SChannel](https://msdn.microsoft.com/en-us/library/windows/desktop/aa380123%28v=vs.85%29.aspx) respectively.

If the server is available publicly, you could use SSL Labs' [SSL Server Test](https://www.ssllabs.com/ssltest/) to diagnose the issue better.

You _could_ workaround this by adding the certificate to the Certificate store in the appropriate location, but I'd only do that **after** you've confirmed the certificate is configured correctly by the administrators.

**Comment by asishm** [comment]
For now, I cloned the repo using git bash cli (with sslVerify = False) and then added the local repo to Github Desktop which then let me fetch the remote repo by entering my enterprise credentials.
