### ISSUE TITLE
Default .gitattributes overwrites existing one if present

### ISSUE THREAD

**Issue by strafe** [desktop/desktop#3363]
### Description

As briefly mentioned at the end of #3233 if you use `desktop` to create a new repository inside a folder that already contains a `.gitattributes` file the existing one will be overwritten by the default one:
https://github.com/desktop/desktop/blob/71c268042b6040a49cc5307111ef3d819b691486/app/src/ui/add-repository/git-attributes.ts#L4-L13
<hr>

### Version

**GitHub Desktop version:** 1.0.9

**OS version:** Windows 10 Home `10.0.15063 - Build 15063`
<hr>

### Steps to Reproduce

1. Create a folder locally and place any `.gitattributes` file inside it.
1. Use the `New-repository...` on `desktop` to create a new repo inside that folder.
1. See that the `.gitattributes` file has been overwritten.

**Expected behavior:** The default `.gitattributes` is only written when one does not already exist.

**Actual behavior:** Any existing `.gitattributes` file is overwritten.

**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
This one should be a relatively straightforward fix, if someone wants to have a shot.

Here's the problem code:

https://github.com/desktop/desktop/blob/c6a57140efc82fc819826d8230e6276dd2e987d9/app/src/ui/add-repository/create-repository.tsx#L274-L282

We have a helper function for checking the existence of a file - `pathExists`:

```ts
import { pathExists } from '../../lib/file-system'
```

This can be await'd, so you could end up with something like this for a solution:

```ts
try {
  const gitAttributes = Path.join(fullPath, '.gitattributes')
  const gitAttributesExists = await pathExists(gitAttributes)
  if (!gitAttributesExists) {
    await writeGitAttributes(fullPath)
  }
} catch (e) {
  log.error(
    `createRepository: unable to write .gitattributes at ${fullPath}`,
    e
  )
  this.props.dispatcher.postError(e)
}
```
