### ISSUE TITLE
Cannnot clone repository

### ISSUE THREAD

**Issue by azumukupoe** [desktop/desktop#3366]
### Description

[Can't clone]

### Version

**GitHub Desktop version:** [1.0.9]

**OS version:** [Windows 10 Home 1709]

### Steps to Reproduce

1. [Open repository in browser]
1. [click Open in Desktop]
1. [click Clone (on Desktop)]

**Expected behavior:** [repository to be cloned]

**Actual behavior:** [error dialog]

**Reproduces how often:** [100%]

#### Additional Information
[2017-11-18.desktop.production.log](https://github.com/desktop/desktop/files/1484426/2017-11-18.desktop.production.log)

**Comment by shiftkey** [comment]
@azumukupoe this is the underlying error:

```
Cloning into 'C:\Users\azumu\Documents\GitHub\resources'...
fatal: unable to access 'https://github.com/TilesOrganization/resources.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - �����̊֐��͏ؖ����̎�����m�F�ł��܂���ł����B
Error(s) during clone:
git clone failed: exit status 128
```

We've had a few issues with SChannel errors - #3326 is the rollup - and these seem to be related to an SSL proxy interfering with the handshaking process that Git does as part of any network-related operations.

As a workaround, you can revert to the classic OpenSSL behaviour by opening the repository in a shell and running these two commands. 

```
$ git config --global http.sslBackend "openssl"
$ git config --global http.sslCAInfo [path to .pem file]
```

[The PEM file](https://curl.haxx.se/docs/caextract.html) distributed by the cURL team should do the trick.

**Comment by shiftkey** [comment]
@azumukupoe please let me know if you have any further questions about this

**Comment by shwethabetageri** [comment]
root@pglabadmin:/home/pglabadmin# clone https://github.com/frenetic-lang/pyretic.git
clone: command not found
root@pglabadmin:/home/pglabadmin# git clone https://github.com/frenetic-lang/pyretic.git
Cloning into 'pyretic'...
fatal: unable to access 'https://github.com/frenetic-lang/pyretic.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
