### ISSUE TITLE
ind_cargar

### ISSUE THREAD

**Issue by fedepezzola** [desktop/desktop#3371]
Esta función está hecha para cargar desde un .idx. Entonces, suponemos que ya esta ordenado, y deberíamos cargar la lista desde un archivo, lo mas eficiente posible, sin recorrer la lista varias veces.

**Comment by shiftkey** [comment]
Rough translation:

> This function is made to load from a .idx. Then, we suppose that it is already ordered, and we should load the list from a file, as efficiently as possible, without going through the list several times.

@fedepezzola I don't understand what this refers to. Could you share some details about your setup and what Desktop is doing here to help me better understand what you are seeing?
