### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by ram-magplus** [desktop/desktop#3376]
I am unable to login into Github Desktop. I am using latest version of Github is 1.0.9.

![screen shot 2017-11-20 at 12 01 07 pm](https://user-images.githubusercontent.com/22652448/33005147-90e56be0-cdea-11e7-8852-336c9bb9f786.png)

### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [1.0.9]

**OS version:** [OS X EI Capitan 10.11.6]

### Steps to Reproduce

1. [Install Github Desktop]
2. [go to preferences ]
3. [click on Github.com login option]
3. [after enter valid credential it's throughing  on error as attached screen shot]

**Expected behavior:** []

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by tierninho** [comment]
@ram-magplus Any logs you can share? 

See Console in `View > Developer Toggle Tools`, as well as `Help > Show Logs in Finder`. Thank you.

**Comment by shiftkey** [comment]
Yeah, it seems people have had luck with this workaround on different versions of macOS:

> Try opening **Keychain Access.app**. Right-click on the `login` keychain and try locking it and then unlocking it again.

**Comment by Eliijahh** [comment]
@shiftkey solution worked for me, thank you!
