### ISSUE TITLE
Arch Linux AUR PKGBUILD

### ISSUE THREAD

**Issue by immackay** [desktop/desktop#3377]
I've created an install script for Arch Linux: https://aur.archlinux.org/packages/github-desktop-git/

**Comment by shiftkey** [comment]
@immackay that's cool! 💖 

I've added a note to the README about this in #3386 - let me know if there's anything else to add!

**Comment by shiftkey** [comment]
@immackay would you be interested in upstreaming [this patch](https://aur.archlinux.org/cgit/aur.git/tree/github-desktop.patch?h=github-desktop-git) with some documentation to make your life a bit easier?

**Comment by immackay** [comment]
I'm a little unsure, do you mean creating a pull request with that code? I was thinking of doing that, but there's much more terminals available in linux than urxvt, gnome terminal, etc. I was going to look into a way of making it easy for linux end users to add their desired terminal and have it automatically added to the source code on compilation. What are your thoughts on that?

**Comment by shiftkey** [comment]
@immackay 

> I'm a little unsure, do you mean creating a pull request with that code? 

Yep!

>  I was thinking of doing that, but there's much more terminals available in linux than urxvt, gnome terminal, etc.

I'm not fussed about supporting different shells based on what's out there that people are using - as long as they behave in a consistent way and can be launched from Desktop without much effort. Having more of these in the core would mean less hassles for downstream consumers.

> I was going to look into a way of making it easy for linux end users to add their desired terminal and have it automatically added to the source code on compilation.

If you're fine with managing that stuff, then keep going ahead. But feel free to open pull requests to improve the core if it'll make your life easier - I'm happy to bounce ideas around.

**Comment by immackay** [comment]
Okay, I'll see what I can do, thanks!
