### ISSUE TITLE
Missing Gems after installing GitHub Desktop

### ISSUE THREAD

**Issue by christoff-1992** [desktop/desktop#3378]
### Description

Missing Gems after installing GitHub Desktop

### Version

**GitHub Desktop version:** 1.0.9

**OS version:** 10.13.1 (17B48)

### Steps to Reproduce

1. After installing GitHub desktop it appears that many of the required gems are missing from the system.
2. I have manually installed the gems that are missing as and when each error message is displayed.
3. However the system is unable to detect git-cop even though this has been installed, unless it requires a specific version, (Installed the latest).
4. Removing and re-installing GitHub desktop doesn't resolve the issue.

**Expected behavior:** I expect GitHub Desktop to be able to sync back with the Repo

**Actual behavior:** An error message is displayed with information on the missing gem

**Reproduces how often:** 100% of the time

### Logs

> 2017-11-20T10:07:34.891Z - error: [ui] `git commit -F -` exited with an unexpected code: 1.
> [git]: Git Cop not found. To install, run: gem install git-cop --trust-policy MediumSecurity.
> 
> 2017-11-20T10:08:02.878Z - info: [ui] [AppStore] loading 1 repositories from store
> 2017-11-20T10:08:02.879Z - info: [ui] [AppStore] found account: xxxxxx (null)
> 2017-11-20T10:08:04.070Z - info: [ui] launching: 1.0.9 (Mac OS 10.13.1)
> 2017-11-20T10:08:37.749Z - error: [ui] `git commit -F -` exited with an unexpected code: 1.
> [git]: Git Cop not found. To install, run: gem install git-cop --trust-policy MediumSecurity.
> 
> 2017-11-20T10:13:32.573Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.172s)
> 2017-11-20T10:15:32.031Z - error: [ui] `git commit -F -` exited with an unexpected code: 1.
> [git]: Git Cop not found. To install, run: gem install git-cop --trust-policy MediumSecurity.

#### Additional Information

Have recently reinstalled the OS and have updated to High Sierra. (Clean install)

**Comment by shiftkey** [comment]
@christoff-1992 I'm not running on High Sierra yet, so I'm not sure I'm the best person to help with testing this. I'm also not familiar at all with `git-cop`, which seems to then rely on hooks in the Git repository to run.

Could you provide details about setting it up beyond `gem install`, and how your repository hooks are currently configured that will trigger the problem?

**Comment by christoff-1992** [comment]
Thanks @shiftkey - I am also not familiar with `git-cop` other than GitHub desktop throwing up the error message when I try to commit via the desktop application.

The desktop application was missing other gems too, but I was able to resolve the error's by manually installing them. My guess is that the desktop client wants a specific version, do you know where about's the gems are referenced in the project? Il take a look and try to figure out whats a miss.

There is also no other log's than above unless there going somewhere else. I have also tried installing the desktop client via the home-brew command and have tried several versions of the client with no luck.

This is what the client displays when I hit commit.

![screen shot 2017-11-21 at 07 37 11](https://user-images.githubusercontent.com/12499390/33060088-f85a5e26-ce8e-11e7-8421-125af557a3d8.png)

However you can see that `git-cop` is installed when I run `git-cop -v` from terminal.

![screen shot 2017-11-21 at 07 40 08](https://user-images.githubusercontent.com/12499390/33060263-98269582-ce8f-11e7-83c4-71559bc5ab48.png)

**Comment by shiftkey** [comment]
> I am also not familiar with git-cop other than GitHub desktop throwing up the error message when I try to commit via the desktop application.

This error is probably the pre-commit hook, found in `.git/hooks/pre-commit` in the repository. _In theory_, if `git-cop` is on your `PATH` then the script should work - and I guess it depends on what that hook is trying to do. It's hard to say without more information about what's in that hook script. The upgrade to High Sierra is also interesting here, but given the shell can find `git-cop` maybe it's fine now.

> The desktop application was missing other gems too, but I was able to resolve the error's by manually installing them.

What errors were these?

> My guess is that the desktop client wants a specific version, do you know where about's the gems are referenced in the project? Il take a look and try to figure out whats a miss.

We don't use any Gems in the codebase.

**Comment by christoff-1992** [comment]
Thanks @shiftkey - sorry for the late reply I didn't see you response.
I have checked `.git/hooks/` and theres nothing there.

Here is the structure, I have also gone through each file to check for any references to git-cop.

![screen shot 2017-11-24 at 08 36 07](https://user-images.githubusercontent.com/12499390/33202073-f1ce65aa-d0f2-11e7-85c4-311ac82cb0cd.png)

As for the other Gem's I should have kept a record but unfortunately I didn't do so.

**Comment by christoff-1992** [comment]
@shiftkey - Ahh may have found the culprit in the git config, extensions on my local machine. Not sure what has installed this but thank you for the assistance!

```ruby
# Label: Git Cop
# Description: Enforces consistent Git commits.
git_cop() {
  if ! command -v git-cop > /dev/null; then
     printf "%s\n" "[git]: Git Cop not found. To install, run: gem install git-cop --trust-policy MediumSecurity."
     exit 1
  fi

  git-cop --hook --commit-message "${BASH_ARGV[0]}"
}
```
