### ISSUE TITLE
Stash support on github desktop

### ISSUE THREAD

**Issue by smilecs** [desktop/desktop#3379]
### Description

Unlike other source versioning GUI apps(Source tree, Git kraken) github desktop is the only one which doesn't support stashing changes right from the app.

### Version

**GitHub Desktop version:** current version

**OS version:** 10.13.1

### Steps to Reproduce

**Expected behavior:**
1. Have stash button on app bar.
2. Click button, then a dialog comes up asking to name the stash
3. After naming the stash,  all uncommited changes are stashed with name.
4. Stashed items are found on side navigation.

**Actual behavior:** Feature non existent

**Reproduces how often:** N/A

**Comment by shiftkey** [comment]
@smilecs thanks for the feedback. I'll add your notes to the existing issue #2304.

**Comment by abelsond** [comment]
This still doesn't seem to have been solved.  Two years later...

**Comment by steveward** [comment]
@abelsond work is being done on stashing -- you can follow along in https://github.com/desktop/desktop/issues/6987 for progress on this feature. Hope that helps!
