### ISSUE TITLE
Updater fail: shortcut not working

### ISSUE THREAD

**Issue by roha69** [desktop/desktop#3381]
### Description

My company's firewall deny the connection to the github site (to download github desktop). So, the updater try to install update (made an empty folder). 

The issue is: my shortcut on windows desktop is not working. I think, it's linking to the empty folder instead working version.

Please add a check to cancel update if github site is not reachable or option to disable auto updates.

Thanks

### Version

**GitHub Desktop version:** [1.0.8]

**OS version:** [windows 7 pro]

### Steps to Reproduce

1. [First step]
deny connection to desktop.githubusercontent.com
1. [Second step]
install old version of github desktop
1. [and so on]
the updater fail to download and the desktop shortcut don't work 

**Expected behavior:** [the shortcut still using old version]

**Actual behavior:** [the shortcut don't do anything]

**Reproduces how often:** [100%]

### Logs
```
2017-11-17T08:20:21.657Z - error: [ui] Error checking for updates
Error: Command failed: 4294967295
System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> ICSharpCode.SharpZipLib.Zip.ZipException: Cannot find central directory
   � ICSharpCode.SharpZipLib.Zip.ZipFile.ReadEntries()
   � ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(String name)
   � Squirrel.ReleasePackage.<ExtractZipForInstall>d__16.MoveNext()
```

#### Additional Information

Thanks.

**Comment by shiftkey** [comment]
I wonder if this will be fixed when we upgrade Squirrel in #3351

**Comment by shiftkey** [comment]
After blocking all access to the IP address behind `desktop.githubusercontent.com` that I found after a `ping` I got a slightly different error:

```
Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (502) Bad Gateway.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
   ...
```

@roha69 

> My company's firewall deny the connection to the github site (to download github desktop).

Can you clarify what behaviour (in particular the HTTP response code and body, running Fiddler would help for traceability) the firewall is doing here?

**Comment by shiftkey** [comment]
Closing this out as inactive.

@roha69 if you're able to answer the question I have above I'm happy to reopen this and see if we can figure out how to fix it.
