### ISSUE TITLE
Beta Release Notes Don't Point to the Right Place

### ISSUE THREAD

**Issue by say25** [desktop/desktop#3385]
### Beta Release Notes Don't Point to the Right Place

what's new / release notes dont work with beta versions.

### Version
**GitHub Desktop version:** [1.0.10-beta0]

### Steps to Reproduce

1. Open app.
1. See new update.
1. Click `what's new` link or `release notes` in About screen.

**Expected behavior:** See release notes for beta version.

**Actual behavior:** See release notes for last release version.

**Reproduces how often:** `100%`

#### Additional Information

More than will to help solve this issue. 

I know that #2774 might solve this differently. 

I think https://desktop.github.com/release-notes/beta would be cool too. 

![image](https://user-images.githubusercontent.com/7467062/33046461-a5a4c324-ce16-11e7-8f57-b662c94f1bea.png)

**Comment by shiftkey** [comment]
> I know that #2774 might solve this differently.

Kind of. Off the top of my head the things not quite covered by that issue:

 - we serve up the release notes from an API endpoint - we need to teach that endpoint about channels, and also get it to serve up the right content. That might be covered by #2774 implicitly, but its still work that needs to be done alongside.
 - `desktop.github.com` doesn't have a corresponding page to serve up the beta release notes

**Comment by msftrncs** [comment]
The In-App 'what's new' are nice, but since you only see the most recent beta release, so if you missed one, you have to go looking around in the changelog for them.
