### ISSUE TITLE
[feature] Allow 'Show in Explorer' also under 'History' tab

### ISSUE THREAD

**Issue by aybe** [desktop/desktop#3387]
### Description

The 'Show in Explorer' context menu for files in 'Changes' tab is great, however, it'd be even better if that menu was also available when right-clicking a file under 'History' tab.

### Version

**GitHub Desktop version:** 1.0.9

**OS version:** Microsoft Windows [Version 10.0.16299.64]

### Steps to Reproduce

1. click 'History' tab
2. right-click a file in current commit

**Expected behavior:** a context menu like in 'Changes' tab

**Actual behavior:** there's no context menu like in 'Changes' tab

**Reproduces how often:** always

**Comment by shiftkey** [comment]
@aybe thanks for the feedback! Please follow along with the earlier report for this: #2845

**Comment by aybe** [comment]
Sorry, I should have searched first !

Thank you.
