### ISSUE TITLE
Disabled menu items accessible

### ISSUE THREAD

**Issue by Zaelot** [desktop/desktop#3391]
### Description

When the Desktop Client is freshly installed the `Repository` and `Branch` are supposed to be disabled, but you can access them by first opening the active menu next to them and scrolling over sideways. (So from `View`->`Repository` and `Help`->`Branch`. Can't move between the two disabled ones.)

### Version

**GitHub Desktop version:** 1.0.9

**OS version:** Windows 10 Pro, latest update

### Steps to Reproduce

1. Install GitHub Desktop Client
2. Open `View` menu 
3. Scroll sideways (move mouse) over to the disabled `Repository` menu
4. Can also scroll from `View` to `Branch` by moving mouse over the top of the `Repository` (avoiding it).

**Expected behavior:** The disabled menus are inaccessible

**Actual behavior:** Disabled menus are accessible (though most of their items are still disabled)

**Reproduces how often:** 100%

#### Additional Information

Not related, but this _Bug report template_ had `1.` repeatedly in the _Steps to _Reproduce_.

  

Also not related, but the new GitHub Desktop Client doesn't pickup the information from the old GitHub Desktop Client (such as the local repositories, or the settings).

**Comment by Zaelot** [comment]
My bad, it appears the #1521 already addressed this. My report has a bit more information, but irrelevant otherwise.

**Comment by j-f1** [comment]
> Not related, but this Bug report template had `1.` repeatedly in the Steps to Reproduce.

This is intentional. If I write this Markdown:

```markdown
1. one
1. two
1. three
1. four
```

I get this output:

> 1. one
> 1. two
> 1. three
> 1. four

Markdown doesn’t care what numbers are used — only the first one matters.

**Comment by Zaelot** [comment]
Oh, didn't know that. Thanks Jed Fox!
