### ISSUE TITLE
Changing default branch from master to develop not changed in Github Desktop

### ISSUE THREAD

**Issue by pumano** [desktop/desktop#3394]
### Description

I use gitlab and after changing default branch from "master" to "develop" I see everytime in gitlab: default "develop" but Github Desktop not change default branch. I see "master".

### Version

**GitHub Desktop version:** 1.0.9

**OS version:** Win 10 x64 

### Steps to Reproduce

1. Run github desktop (git pull from any branch)
2. Change default branch from master to any other branch
3. default branch not updated in github desktop

**Expected behavior:** Github desktop should update default branch and set it as default branch in branches dropdown list

**Actual behavior:** github desktop not update default branch 

**Reproduces how often:** I test it 1 time and defautl branch not changed

### Logs

Logs only contains stacktraces about updates (it's out of scope of this issue)

**Comment by shiftkey** [comment]
> I use gitlab and after changing default branch from "master" to "develop" I see everytime in gitlab: default "develop" but Github Desktop not change default branch. I see "master".

The "default branch" behaviour in Desktop relies on the GitHub API - for non-GitHub repositories we fall back to Git's behaviour, which will use `master` by convention.

**Comment by shiftkey** [comment]
@pumano let me know if you have any other questions about this!
