### ISSUE TITLE
Clicking on a PR from a fork does nothing

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#3395]
https://github.com/desktop/desktop/blob/1de8b496393a316b23d4492adf6aa9df9f44bd57/app/src/ui/branches/index.tsx#L215-L219

**Comment by joshaber** [comment]
_Probably_ we should add the fork's remote and then check out the ref? This could be a bummer since your list of remotes will grow over time.

We could check out the pull request ref, but then we couldn't push to it if it allowed maintainer collaboration.

@desktop/core @desktop/design Thoughts?

**Comment by joshaber** [comment]
@niik and I talked about this yesterday and agreed that for 1.1, checking out the PR ref is the best route forward. That means we'll also need to explicitly fetch the PR ref (e.g., `git fetch origin pull/:pr_number/head`).

**Comment by shiftkey** [comment]
Some prior art: the "Clone in Desktop" flow handles PRs from forks. 

https://github.com/desktop/desktop/blob/dd54f83a269d6353b5b48ae90d923e6130845ad1/app/src/lib/dispatcher/dispatcher.ts#L889-L910

Feel free to steal liberally.

**Comment by iAmWillShepherd** [comment]
> This could be a bummer since your list of remotes will grow over time.

These are the notes for solving this problem from our mini-planning session.

### Cleanup
1. Initiated when PRs are refreshed
1. Iterate over remotes
1. Delete any remote, using are special magic prefix, not referenced by an open PR 

### Clicking a PR
1. Add a remote with a magic-prefix if needed 
1. Fetch (this will prune unreferenced refs for us)
1. Checkout ref as `pr/[PR Number]`

**Comment by iAmWillShepherd** [comment]
Something to consider is if a user adds a remote under our *namespace* then the URL may not be what we expect, what do we do?

Also Windows has a path length limit, our remote names could cause problems.
