### ISSUE TITLE
What are we gonna do about Git Shell on Windows

### ISSUE THREAD

**Issue by niik** [desktop/desktop#340]
GitHub for Windows has always shipped with a complete git/bash command line environment. It's always been a big selling point, "the easiest way to get git running on your windows machine".  We shared that user-facing environment with the app itself, shelling out for the stuff we couldn't do with libgit2. That has once or twice caused us problems when upgrading since the shell environment could break the ui.

Mac has also shipped with git but their environment has only been used internally by the app and hasn't been made publicly available. A long time ago there was a button in the app to install a command line environment but that was removed after Apple started shipping Git shims in 10.9.

Right now desktop ships with a slimmed down environment for both Mac and Windows which is only meant to be used internally. We need to figure out what we need to do as far as providing a shell environment for users on Windows.

Access to a command line environment is essential for things like conflicts where we currently need to tell the user to go resolve the conflicts themselves. GHfW default cop-out when we hit an unexpected error with git was to let the user launch the shell and figure it out from there (not saying I ever liked that).
### Questions
1. How do we ship it? Exactly as we do today? 7-zip archive unpacked to magic dir and environment launched through GitHub.exe?
2. What kind of interoperability do we want between our internal env and git shell (see #184)
3. Do we want to keep shipping posh-git
4. Do we want to allow custom shells in options like we do today
### Goals
1. Provide a super simple way to get Git onto your Windows machine
2. Provide an [opinionated environment](https://github.com/github/msysgit/blob/devel/etc/gitconfig) with sane defaults and credential support

I know there was talk about a standalone shell thing a while back but I don't know how fleshed out that really was nor do I know if we have time to go for anything other than parity here.

I know this is something near and dear to @shiftkey's heart and I expect him to have a lot to say here, I'm only opening it so that we can start discussing it.

**Comment by niik** [comment]
> Down the road we'll certainly consider how we make the Git experience better, e.g., keeping git up to date.

For reference and as input into future discussion about this, these are the steps and choices I have to make while installing Git for Windows now vs the no-questions-asked automatic installation and configuration approach we took in Classic/Windows.

![image](https://cloud.githubusercontent.com/assets/634063/26144872/d1b1c6e8-3aea-11e7-981d-631dfaa2cb36.png)
![image](https://cloud.githubusercontent.com/assets/634063/26144877/d471f024-3aea-11e7-8bfa-67bf59690072.png)
![image](https://cloud.githubusercontent.com/assets/634063/26144883/d8f3cf1e-3aea-11e7-82cb-386c24c96594.png)
![image](https://cloud.githubusercontent.com/assets/634063/26144891/dbf2ddc2-3aea-11e7-8cfb-18ad9ebc55a7.png)
![image](https://cloud.githubusercontent.com/assets/634063/26144904/e1fe850e-3aea-11e7-968c-65733cdc331f.png)
![image](https://cloud.githubusercontent.com/assets/634063/26144908/e47925fa-3aea-11e7-9cf6-ea687b550000.png)
![image](https://cloud.githubusercontent.com/assets/634063/26144918/e7ebcd78-3aea-11e7-8f35-1cd89980b714.png)
![image](https://cloud.githubusercontent.com/assets/634063/26144922/eb12cb5a-3aea-11e7-9273-15dcdcc8ead6.png)
![image](https://cloud.githubusercontent.com/assets/634063/26144935/f403630a-3aea-11e7-849c-5fcdb9626458.png)
![image](https://cloud.githubusercontent.com/assets/634063/26144951/fca5ef6e-3aea-11e7-91c3-0e5b9a0d6193.png)

**Comment by Haacked** [comment]
Yeah, that's a pain. Is there a way we can do an unattended install with our suggested settings.

One thing that's nice, if you're on PowerShell 5+, you can run the following command to install Posh-Git.

`PowerShellGet\Install-Module posh-git -Scope CurrentUser`

But for it to be added to your profile, you need to edit your PowerShell Profile and add

`Import-Module posh-git`

If we had our own Git Shell icon, we could do that before launching standard Git. But not sure how far we want to go with this.

**Comment by HugoMcPhee** [comment]
Another user perspective here:

> reinstalled windows 
> installed Github Desktop beta 
> tried running"npm install" on a project but "Git not found" (as expected)
> looked for git shell to quickly run "npm install" from
> now trying to figure out best, least involved and least obtrusive way to get git to be able to "npm install again without success

Has it been considered / is it possible to release a standalone version of "git shell" separate from this?
Thanks

**Comment by shiftkey** [comment]
> Has it been considered / is it possible to release a standalone version of "git shell" separate from this?

My goals over the last few months have been to get the things we loved in Git Shell into Git for Windows proper. So far 2FA GitHub Authentication, Git LFS and Windows Certificate lookup support have landed, and we've talked about PowerShell support (and maybe even Posh-Git) down the track but that's more tricky to implement.

What I'd like to know from others on Windows is **what things do you love from Git Shell that aren't available in the vanilla Git for Windows install?**

**Comment by vidartf** [comment]
Just wanted to pipe in and say that for me, the most used features of the old Desktop app are:
 - Staging + committing (love the interface for partial staging + helper for the commit title length).
 - Right-clicking a repo in the repo list -> "Open in Git Shell" to get a posh-git terminal. This is by far the quickest way for me to get a git terminal for any of my repos, regardless of their physical location on disk.

For me, both these features need at least parity before I in good conscience can update. I see that the second feature is now several additional clicks away (open repo list, switch repo, open repository menu, "open command prompt"), and is not yet customizable to point to a posh-git shell(?).

> What I'd like to know from others on Windows is what things do you love from Git Shell that aren't available in the vanilla Git for Windows install?

Tab completion of posh-git. I make so many typos normally, that this is a necessity for me to be productive.

**Comment by shiftkey** [comment]
@vidartf thanks for the information!

We're tracking making the shell customizable in #888 and `posh-git` has a [number of installation options](https://github.com/dahlbyk/posh-git#installation), so while it won't be out-of-the-box like we previously did, I think we can get it pretty close to what the classic Windows app achieved.

**Comment by patrikhuber** [comment]
So, I'm one of these users who used the previous GitHub Windows Desktop app (or whatever it was called), and I basically only used it to use the integrated "Git Shell" Powershell.
Now I installed the new GitHub Desktop app on a new Windows system and found there was no shell to be found.
Also I don't find the instructions in this issue quite clear. So I did the following:

* Install "Git for Windows" or whatever it's called - the one from here: https://git-scm.com/download/win
Click through a ton of options... left most on the default - hopefully that's correct.

I now have a git shell in a MINGW64 window. That's not really what I wanted. Was it really necessary to install a full MINGW64 environment?

I then proceeded with the following:

* Install posh-git, with these commands:
```
PowerShellGet\Install-Module posh-git -Scope CurrentUser
Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
Add-PoshGitToProfile
```

To the best of my understanding, this only installed some powershell scripts, and not another set of git binaries, correct?

I think I'm more or less there now... I've got a new Powershell again with the git status indications on the commandline.

I still don't have the shortcuts that the previous GitHub "git shell" had, e.g. "git st" for "git status".

Maybe this is unrelated but if I've got `MSYS2` installed anyway, can I just install the git from there, and then posh-git on top of that, and be done with it?

In any way, I would consider the current status of things highly confusing and unsatisfactory, or am I missing something?

Thanks!

**Comment by shiftkey** [comment]
@patrikhuber thanks for the feedback!

> I now have a git shell in a MINGW64 window. That's not really what I wanted. Was it really necessary to install a full MINGW64 environment?

The shell you see by default in Git for WIndows is Git Bash. The `MINGW64` mention in the window is from [`MinGW`](http://www.mingw.org/), which is the overall environment on which Git for Windows is based (more information [here](https://github.com/git-for-windows/git/wiki/The-difference-between-MINGW-and-MSYS2)).

> To the best of my understanding, this only installed some powershell scripts, and not another set of git binaries, correct?

Correct. [These scripts](https://github.com/dahlbyk/posh-git/tree/master/src).

> I still don't have the shortcuts that the previous GitHub "git shell" had, e.g. "git st" for "git status".

That sounds like it should be enough, maybe you need to restart the PowerShell prompt?

> Maybe this is unrelated but if I've got `MSYS2` installed anyway (or WSL, for that matter), can I just install the git from there, and then posh-git on top of that, and be done with it? What about the aliases?

I've not spent much time with WSL recently, but I believe it's still all working within the context of a bash shell - so you could use that. But Desktop won't detect if you have that installed, due to how it's separated from Win32, but please open a new issue if you enjoy yourself there and would like to jump out of Desktop to Bash on Ubuntu on Windows and we can look into it further.

**Comment by patrikhuber** [comment]
> The MINGW64 mention in the window is from MinGW, which is the overall environment on which Git for Windows is based (more information here).

Hmm, I'm confused now. That wiki page kind of suggests Git for Windows 2.x is based on MSYS2, not on MINGW64, doesn't it?

If I've already got standalone MSYS2 installed, do I need the Git for Windows package and another set of MINGW64 or MSYS2 files on my disk?

> That sounds like it should be enough, maybe you need to restart the PowerShell prompt?

Hmm no, it doesn't seem like any of the aliases previously present in the GitHub Windows client are present. Where would they be coming from? posh-git? Git for Windows?

(I think I'll not dig deeper into WSL git for now, I'm very happy with PowerShell + posh-git.)

**Comment by shiftkey** [comment]
> That wiki page kind of suggests Git for Windows 2.x is based on MSYS2, not on MINGW64, doesn't it?

They're still both used in various ways in Git for Windows 2.x. The "Git Shell" shortcut you're referring to was a combination of Git for Windows, configuring some environment variables and opening whatever shell you configured in GitHub Desktop.

> If I've already got standalone MSYS2 installed, do I need the Git for Windows package and another set of MINGW64 or MSYS2 files on my disk?

Yes. It should be a bundled dependency of Git for Windows, and it shouldn't clash.

> Hmm no, it doesn't seem like any of the aliases previously present in the GitHub Windows client are present. Where would they be coming from? posh-git? Git for Windows?

If you're in PowerShell, it comes from posh-git. If you're in Git Bash, it comes from Git for Windows (I thought it was [this](https://git-scm.com/book/en/v1/Git-Basics-Tips-and-Tricks#Auto-Completion) but I'm not 100% sure).

**Comment by patrikhuber** [comment]
> Yes. It should be a bundled dependency of Git for Windows, and it shouldn't clash.

Okay sorry, you misunderstood that. I'm not worried about clashing. I don't like stupidly having two instances of essentially the same thing on my harddrive. I've already got MSYS2 standalone, why does Git for Windows have to install _yet another MSYS2/MINGW64 environment_ - I've already got one. On top of that it uses 500 MB of extra space, for something that I've already got. (and 500 MB is not an unnoticeable amount in the age of 250 GB SSDs (notebook)). But we're digressing, that doesn't have too much to do with this issue here I guess :-)

I'll have another look at the aliases tomorrow. I didn't mean auto-completion though (I think that is working) - I meant shortcuts/aliases, so you type `git st` + `ENTER` and it runs `git status` - a shortcut basically, much less to type.

**Comment by shiftkey** [comment]
>  I didn't mean auto-completion though (I think that is working) - I meant shortcuts/aliases, so you type `git st` + `ENTER` and it runs `git status` - a shortcut basically, much less to type.

Ah, aliases! Aliases aren't tied to a particular shell, and are typically stored in your global config. [Here's some more info](https://git-scm.com/book/en/v2/Git-Basics-Git-Aliases) and [here's the ones that we bundled with Git Shell](https://github.com/github/ghfw-build-extra/blob/master/github-extra/resources/gitconfig#L1-L9)

**Comment by patrikhuber** [comment]
> here's the ones that we bundled with Git Shell.

Ah that's awesome! Will add these to my setup, thanks :-) 

It really is quite a pain getting the same setup again like one had before with the GHFW "Git Shell"! Even once one finds this thread. But I think I'm there now.

**Comment by SteveALee** [comment]
Here's a few comments from a user who immeditely noticed the missing shell when installing lastest.

I actually dont use GitHub Desktop much, it's more a quick way to install a bash on windows, as you mention. These days i mostly use VS Code's built in git support and the git lense extension, plus occaisional command line.

GitHub Desktop does still give me two useful things a) a one click clone from github website b) a nice GUI experience when I feel the need for it. 

I've actually been using various bash envs on Windows for years and settled on Git4Windows (MinGW MSys based). I found you used to supply it soI could install both in one go, nice. Lately I saw references to cygwin which was surprising, but you indicate above you customise your version. I tend to use a pretty vannila git setup so don't often hit config issues

The way of git is every now and then you get into a mess and need to switch to incantation and prayer operational mode on the command line. The likely hood of this is reduced when using wrappers like GitHub Desktop, but it can still happend. Thus you do need to supply a CLI env to drop down into, and as observed it need to be configured to match GH Desktop.

Now WSL has largely stabilised perhaps you could use that? But that's only usable on latest Windows update and then syncing of links / Junction is not fully sorted. Probably to complext to config from a windows installer anyway.

Finally when you removed the shell you also seem to remove tha ability to set the directory that repos live in. That's also a deal breaker for me. We still have programs that have path limits.

I hope that is vaguely useful

**Comment by SteveALee** [comment]
Oh PS, my bash config includes a SSH Agent so I don't have to keep supplying HTTP passwords.

**Comment by gethub0100** [comment]
please goto link below  for git-shell 
https://git-scm.com/download/win

**Comment by dahlbyk** [comment]
FYI, discussion about installing posh-git with Git for Windows: https://github.com/git-for-windows/git/issues/1384

**Comment by patrikhuber** [comment]
Incidentally, I just found [this blog post](https://haacked.com/archive/2015/10/29/git-shell/) from 2015. It's from @Haacked who works at GitHub, explaining why they bundled all this together and how much of an awesome and simple experience it creates on Windows, with useful defaults and all that.
So sad that two years later most of that was thrown out of the window.

**Comment by tedry** [comment]
With out the shell this is incomplete.. I don't bother using the desktop without it.

**Comment by j-f1** [comment]
We now recommend using [Git for Windows](http://gitforwindows.org) to get access to a Git environment on Windows.

**Comment by binaryfunt** [comment]
I've created a couple of scripts that allow you to load the old version of GitHub's posh-git module into your current PowerShell session. It's called [git-shell](https://github.com/binaryfunt/git-shell). There's a bit of overhead in setting it up, but I've found it to be exactly what I want.

![Demo](https://raw.githubusercontent.com/binaryfunt/git-shell/master/demo.gif)

**Comment by shiftkey** [comment]
@binaryfunt I'd recommend just using [Posh-Git](https://github.com/dahlbyk/posh-git) using one of their [install methods](https://github.com/dahlbyk/posh-git#installing-posh-git-via-powershellget) as that's been under active development beyond what's currently in classic Desktop.

If there's other parts of the Git Shell experience you're missing, I can help point you to other resources about that.

**Comment by binaryfunt** [comment]
@shiftkey Yeah I guess most people might prefer to just import posh-git to their powershell profile, but I like the behaviour of having a callable session that automatically cd's to my GitHub directory. Plus `git-shell` is less characters to type than `Import-Module posh-git`
