### ISSUE TITLE
Poor Icon Anti Aliasing & Using the Old Icon?

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#3404]
Where can I get the old icon? I liked it better and the new one is full of jaggies.
![2017-11-22_10-39-14](https://user-images.githubusercontent.com/10897523/33117546-7577a160-cf71-11e7-9f0b-6f3043542171.png)

**Comment by shiftkey** [comment]
@RaTcHeT302 which version is this? And which version of Windows? I wonder if it's something related to #3351

**Comment by shiftkey** [comment]
@RaTcHeT302 actually, I don't think this is related to #3351.

For some context, [this](https://github.com/desktop/desktop/blob/master/app/static/logos/icon-logo.ico) is the source icon. Here's the sizes that it contains (I'musing [IconsExtract](http://www.nirsoft.net/utils/iconsext.html) to poke at these):

<img width="492" src="https://user-images.githubusercontent.com/359239/33154095-10264bbc-d03a-11e7-874d-a997c0333d6c.png">

Dragging and dropping the GitHub Desktop shortcut to the taskbar doesn't quite look as clear when comparing it to VSCode and Git Bash (just what I also had placed here on this machine):

<img width="200" src="https://user-images.githubusercontent.com/359239/33153963-2b3b8a3a-d039-11e7-8989-972fee5af339.png">

And here's the icon resources for VSCode and Git Bash to contrast:

<img width="494"  src="https://user-images.githubusercontent.com/359239/33154054-c3a75524-d039-11e7-98a6-1d03ec04f816.png">

<img width="497" alt="screen shot 2017-11-23 at 10 34 04 am" src="https://user-images.githubusercontent.com/359239/33154073-df411bbc-d039-11e7-8f36-c2a8f4e5ff7d.png">

The only real difference I can not between these two is the lack of 64x64px resource for Desktop - maybe this is downscaling to 48x48px in the taskbar. The ordering of these resources might also be involved, but I think that's less minor.

@niik thoughts?

**Comment by niik** [comment]
> @niik thoughts?

Gosh, I don't know man. I feel like I've read that icon MSDN doc a thousand times and still I don't have a good sense of what sizes are actually used. We can definitely add a 64x though. @donokuda do you think you could pick this up when you've got some spare time (lol). Let's add a 64x and a 40x version so that we match what vscode is doing.

@RaTcHeT302 Are you using any DPI scaling on your machine?

**Comment by say25** [comment]
@niik to match VSCode properly a 24x would also need to be added

**Comment by RaTcHeT302** [comment]
@niik no

**Comment by strollingHeifer** [comment]
I'm having this issue as well, using DPI scaling on my Windows computer. The old native client did not have that problem.

**Comment by steveward** [comment]
Closing this out as our icon has been updated.
