### ISSUE TITLE
Window position is retained on secondary monitor even when reverting to single-monitor configuration

### ISSUE THREAD

**Issue by jespersommer** [desktop/desktop#3409]
### Description
When using GitHub Desktop on a Windows 10 multi-monitor system, the application seems to cache/remember its window position. When closing and re-opening the application, the window opens in the same position (presumably by design).

If the application is placed on a secondary monitor (or, any non-primary monitor), and the system is later changed to use only a single monitor, it can become impossible to operate the application. It retains its position outside of the primary (now single) monitor.

As a developer and consulting using a laptop, I often find myself switching between multi-monitor usage (office with dock) and single monitor (at clients or on the road). It is annoying to have to remember to reposition GitHib Desktop to the primary monitor every time it is used on a multi-monitor system.

### Version

**GitHub Desktop version:** 1.0.9

**OS version:** 10.0.15063

### Steps to Reproduce

1. Connect more than one monitor to system
2. Open GitHub Desktop application
3. Place GitHub Desktop on secondary monitor
4. Close/exit GitHub Desktop application
5. Disconnect monitor
6. Launch GitHub Desktop
7. The application is now unreachable, and still positioned on the non-existing secondary monitor

**Expected behavior:**
GitHub Desktop should not position itself on its previous position when that position is not on an active desktop or monitor. If the number of monitors is lower than during its previous session, and its original position not reachable, it should position itself on the primary monitor.

**Actual behavior:**
GitHub Desktop positions itself on a non-existing monitor and becomes unreachable. It also cannot be moved between monitors using hotkeys.

**Reproduces how often:**
100%

**Comment by shiftkey** [comment]
@jespersommer thanks for the detailed feedback!

This really feels like #2107, which I'll roll this feedback into.

**Comment by jespersommer** [comment]
I agree. Apologies for not finding that in my search prior to posting. I feel my explanation is a bit more clear though. :-) Keeping my fingers crossed that this will get actual attention, as I work a lot with multi-monitor setups.
