### ISSUE TITLE
No syntax highlighting for "*.hpp" files.

### ISSUE THREAD

**Issue by oskidan** [desktop/desktop#3413]
### Description

C++ source code in "*.hpp" files has no syntax highlighting.

### Version

**GitHub Desktop version:** v1.0.9

**OS version:** Microsoft Windows [Version 10.0.10586]

### Steps to Reproduce

1. Create/clone any Git repository.
2. Create a file with `.hpp` extension: `test.hpp` for example.
3. Add any C++ code into that file.
4. Commit your changes.
5. Open History tab in GitHub Desktop and select that commit.

**Expected behavior:** C++ syntax must be highlighted.

**Actual behavior:** No C++ syntax highlighting.

**Reproduces how often:** Always.

**Comment by shiftkey** [comment]
@oskidan please have a read of [the documentation](https://github.com/desktop/desktop/blob/master/docs/technical/syntax-highlighting.md) about how we've implemented syntax highlighting, as that also shows how you can improve things - it might just be as easy as associating an extension with the language.

**Comment by oskidan** [comment]
Thanks @shiftkey, I wonder if there's a UI which I could use for associating that extension with C++?
As far as I understood from the document you had pointed me to, the only way I could do that is by modifying `highlighter/index.ts` and building my own GitHub Desktop.

**Comment by j-f1** [comment]
@oskidan The idea is that you would make the change, then submit a PR like #3420 above, which we would merge and include in the next version.
