### ISSUE TITLE
appimage does not work

### ISSUE THREAD

**Issue by mitar** [desktop/desktop#3425]
### Description

I built an appimage 

### Version

**GitHub Desktop version:** master branch, 05086e011acc73b5847742fc3325ee2acb9db2ff and update-electron-builder-linux branch as well

**OS version:** Ubuntu 17.10

### Steps to Reproduce

Built appimage with `yarn package`. Run it.

**Expected behavior:** It runs.

**Actual behavior:** I get the following error:

```
/tmp/.mount_desktoUSq5aI/AppRun: line 61: /tmp/.mount_desktoUSq5aI/app/desktop: No such file or directory
```

**Reproduces how often:** Always.

**Comment by niik** [comment]
Hey @mitar. I'm afraid I don't know enough about AppImages to help you out here. We're super happy to see contributions towards Linux support but we don't have enough experience using Linux ourselves. Perhaps you could try reaching out to some of the authors of previous Linux PRs to see if they could help you?

**Comment by shiftkey** [comment]
I stumbled upon https://github.com/electron-userland/electron-builder/issues/2151 which seems like the same error (but still vague), however it looks like it was fixed in an earlier build.

I haven't got a Ubuntu 17.10 VM to test this on and reproduce this, but I'll put this on my to-do list when I have some spare cycles.

**Comment by mitar** [comment]
So you think it is Ubuntu 17.10 specific? Appimage otherwise works for you?

**Comment by shiftkey** [comment]
@mitar I'm not 100% sure, but I'll keep this in mind next time I'm digging into AppImage stuff

**Comment by mitar** [comment]
Feel free to ping me if I can be of any help.
