### ISSUE TITLE
Add packages to releases

### ISSUE THREAD

**Issue by ziggy42** [desktop/desktop#3428]
### Description

It would be great to have all the packages (`.rpm`, `.AppImage`, `.dmg`...) available in the releases page for stable releases. In this way, even if you don't officially support Linux, we still can download a Linux package without having to build the project.

**Comment by niik** [comment]
Hey @ziggy42. I think this would be a great idea once (if) we start using the releases feature properly. For now our releases page on GitHub.com only lists tags we've made. We added a note about ARCH to the README in https://github.com/desktop/desktop/pull/3386 so I think we'd be happy to have other unofficial sources listed there.

I'm going to close this out for now and we'll revisit if we start using releases properly or when we're ready to look at official linux support.
