### ISSUE TITLE
check availability of remote branches --> offer to delete locally

### ISSUE THREAD

**Issue by tooomm** [desktop/desktop#3446]
### Description

When somebody merges a PR from a branch within the repo, he normally deletes that branch too.
But everybody with a local repo copy has to delete the same branch by hand additionally.

It would be very helpful if the client would recognize remote branch deletions and offer to mirror those locally to keep things clean and uniform.

### Version

**GitHub Desktop version:** 1.0.9

**OS version:** Win 10

**Expected behavior:** offer to delete branch locally too (at best not only when you switch to that branch locally)

**Actual behavior:** client realized that the branch isn't available on remote and the `fetch origin` button switches to `publish branch`

**Comment by niik** [comment]
Hey @tooomm, I'd love to see this as well. We're tracking this feature over in https://github.com/desktop/desktop/issues/750 so please follow along there for any updates.
