### ISSUE TITLE
Pull Request badge does not persist when opening an existing repo

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3454]
When I open an existing repo, the pull request badge is sometimes missing. I couldn't pinpoint the reasoning. Nothing in the logs.

In both instances, I opened another repo then went back to this repo. Even clicking on the same repo triggers it. Are we reseting the view to "show no badge" on each initial visit?

<img width="777" alt="screen shot 2017-11-29 at 12 37 09 pm" src="https://user-images.githubusercontent.com/14828183/33373526-9a10ed06-d502-11e7-943d-4073bfc83d7a.png">
<img width="794" alt="screen shot 2017-11-29 at 12 37 37 pm" src="https://user-images.githubusercontent.com/14828183/33373527-9a2c8980-d502-11e7-8446-732cad8bc53c.png">
<img width="620" alt="screen shot 2017-11-29 at 12 44 28 pm" src="https://user-images.githubusercontent.com/14828183/33373640-1fe50084-d503-11e7-9678-4bccf9f9be54.png">

1.0.10-beta2, mac

**Comment by joshaber** [comment]
I'm betting this is related to #3337, so I'm gonna leave it along until that fix lands.
