### ISSUE TITLE
Linux: spell checking the commit message field

### ISSUE THREAD

**Issue by mitar** [desktop/desktop#3458]
I migrated from Mac OS X to Linux and one feature I really liked while working on Mac OS X that a native input box would spell check my commit messages for me. Now that I moved to Linux I am realizing that there is no spell checker on input field but it would be great if maybe GitHub Desktop would do it on its own.

**Comment by shiftkey** [comment]
@mitar thanks for the feedback! We're tracking this in #1597 - please follow along with that issue.
