### ISSUE TITLE
Cannot push

### ISSUE THREAD

**Issue by ilwwwli** [desktop/desktop#3459]
### Description

Cannot push changes to my OWN repository
It can be done before I added someone to collaborators, but it cannot be done now.

### Version

**GitHub Desktop version:** [1.0.9]

**OS version:** [Microsoft Windows [版本 6.1.7601]]

### Steps to Reproduce

PUSH ORIGIN
and it shows
Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.

ALL repositories have the same problem

**Expected behavior:** [can push]

**Actual behavior:** [cannot push]

**Reproduces how often:** [Everytime]

#### Additional Information
 I can push when i right click the repository -> Open in Git Bash -> typing git push
But I cannot push by clicking the topright push

**Comment by niik** [comment]
Hey @ilwwwli, could you please attach attach the most recent log file from:
   `%APPDATA%\GitHub Desktop\logs\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

**Comment by ilwwwli** [comment]
I have tried it today and it still doesn't work 
[2017-11-30.desktop.production.log](https://github.com/desktop/desktop/files/1520517/2017-11-30.desktop.production.log)
[2017-12-01.desktop.production.log](https://github.com/desktop/desktop/files/1520518/2017-12-01.desktop.production.log)

**Comment by ilwwwli** [comment]
I have tried it today and it works well now, though I don't know why but I think there is no problem at the moment

**Comment by shiftkey** [comment]
@ilwwwli the only things I can see in the logs are errors when pulling, and it can't merge the changes automatically. But feel free to reopen it if you encounter the issue again.

**Comment by AnkitSingh12345** [comment]
Any on have the valid solution. Please help me
