### ISSUE TITLE
Sync private repo icon with auth check

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3461]
The private icon in the repo list does not update at the "same time" as an auth check on permissions (as I logged out my user and turned the repo to private).

Although I get auth dialogue, but as expected the icon to update, giving the user a clear indication of what the problem could be. Once logged back in, the icon changes. Is this by design?

<img width="239" alt="screen shot 2017-11-30 at 10 27 51 am" src="https://user-images.githubusercontent.com/14828183/33423447-2799a530-d5b9-11e7-9abf-75a29c08a856.png">
<img width="967" alt="screen shot 2017-11-30 at 10 23 18 am" src="https://user-images.githubusercontent.com/14828183/33423448-27b8a9d0-d5b9-11e7-8b6e-c7462023ae26.png">

1.0.10-beta2, mac

**Comment by j-f1** [comment]
I don’t think there’s a way to differentiate between a private repository you can’t access (due to being logged out or because you’re not allowed to see it) and a repository that doesn’t exist, so as far as Desktop knows, you could’ve just deleted the repository and tried to push.

**Comment by tierninho** [comment]
@j-f1 Thanks for the input! I guess I'll close it out 👍
