### ISSUE TITLE
Desktop window focus occurs in the background only

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3462]
When using the oAuth to sign-in to Desktop via browser, the Desktop application opens in the background, behind the browser... with focus on Desktop.

I used Chrome, and tested the GitHub.com login.

![cf4945ce-12e1-11e7-89cb-331f5a8d8497](https://user-images.githubusercontent.com/14828183/33423904-76569ca4-d5ba-11e7-808e-ae9b1e0696a0.gif)

Similar to https://github.com/desktop/desktop/issues/973

1.0.10-beta2, mac, Chrome

**Comment by shiftkey** [comment]
@tierninho which version of macOS? I'm 99% sure that foreground/background behaviour is controlled by the OS...

**Comment by tierninho** [comment]
10.11.6

**Comment by niik** [comment]
I've definitely seen this on macOS as well.

**Comment by shiftkey** [comment]
Thinking about this issue again, could a simple [win.focus()](https://electronjs.org/docs/api/browser-window#winfocus) here be a suitable fix? I've opened #4126 to talk about this and experiment further.

**Comment by niik** [comment]
#4126 supposedly fixes this so I'm going to close this out but if anyone encounters this again please comment and we'll reopen.
