### ISSUE TITLE
GitHubDesktop (Windows) spawns many, many git.exe processes (very slow)

### ISSUE THREAD

**Issue by ckarcz** [desktop/desktop#3465]
### Description

GitHubDesktop creates many git.exe processes (seen in in taskmgr) that slow down GitHubDesktop to an unusable pace. Also they appear to hang for long time, even after desktop app is closed. I have reinstalled many times, also uninstalling and reinstalling git and disabling git integration in Visual Studio. After uninstalling GitHubDesktop and just using git extensions and/or Visual Studio GitHub integration, I see no mass git.exe processes or degradation in performance as when using the Desktop client.

### Version

GitHubDesktop for Windows x64

**GitHub Desktop version:** 1.0.9

**OS version:** Windows 7 x64 (Microsoft Windows [Version 6.1.7601])

### Steps to Reproduce

Might be specific to this machine for some rason.

**Expected behavior:** Not spawn so many git.exe processes. Not be so sluggish.

**Actual behavior:** Spawn many git.exe processes. Very sluggish.

**Reproduces how often:** Everytime I install GitHubDesktop on this specific machine.

### Logs

<Cannot attache logs from work>

#### Additional Information

N/A

**Comment by niik** [comment]
Hey @ckarcz, could you please attach attach the most recent log file from:
%APPDATA%\GitHub Desktop\logs\*.desktop.production.log

The log files are organized by date, so see if anything was generated for
today's date.

**Comment by joshaber** [comment]
Thank you for your issue!

We haven't gotten a response to our questions above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by hscanlan** [comment]
I have this exact problem. Just started happening I believe..

https://imgur.com/q8Z29JE

**Comment by ckarcz** [comment]
if you can attack your logs for the github team that would be great as i work in a financial firm and uploading such files is strictly forbidden.

**Comment by pedrojrv** [comment]
Same thing started happening today, desktop crashed

**Comment by Desoroxxx** [comment]
I have this issue; here are my logs:

[2026-01-17.desktop.beta.log](https://github.com/user-attachments/files/24685779/2026-01-17.desktop.beta.log)

[2026-01-16.desktop.beta.log](https://github.com/user-attachments/files/24685782/2026-01-16.desktop.beta.log)

[2026-01-14.desktop.beta.log](https://github.com/user-attachments/files/24685783/2026-01-14.desktop.beta.log)

[2026-01-13.desktop.beta.log](https://github.com/user-attachments/files/24685784/2026-01-13.desktop.beta.log)

It consistently happens on all my Windows machines and has for years, whether I’m using GitHub Desktop Beta or the stable version through updates.

I do use commit signing, and it's possibly related? Sometimes I can't sign and need to quit GitHub Desktop, kill the dozens of Git processes, and once I start GitHub Desktop again, everything works fine.

I can help debug further; I don't do any work protected under an NDA or anything like that!
