### ISSUE TITLE
Deleting local branch still shows delete on remote option after upstream has been deleted from remote

### ISSUE THREAD

**Issue by JordanMussi** [desktop/desktop#3468]
### Description

Currently if you have a copy of a branch locally and on the remote when you attempt to delete from the desktop client you have the option to delete the remote as well. (`The branch also exists on the remote, do you wish to delete it there as well?`)

If the branch is deleted on the remote (e.g. on GitHub.com), the local client still gives the same option even though there is no longer a branch on the remote.

### Version

**GitHub Desktop version:** 1.0.9

**OS version:** Microsoft Windows [Version 10.0.16299.64]

### Steps to Reproduce

1. Create branch a new branch from master
	- Push/pull button shows publish branch
2. Branch -> Delete -> Cancel
	- Popup doesn't show remote branch option (correct - there is no remote branch)
3. Publish branch
	- Push/pull button shows fetch origin
4. Branch -> Delete
	- Gives remote branch option (correct - there is a remote branch)
5. Delete the branch on GitHub.com
6. Fetch origin
	- Push/pull button shows publish branch
7. Branch -> Delete
	- Gives remote branch option (incorrect - no remote branch exists)

**Expected behavior:** In step 7 the remote branch notice should not be shown

**Actual behavior:** In step 7 the remote branch notice is shown despite there not being a remote branch

**Reproduces how often:** Whenever the local branch had an upstream which has since been deleted on the remote

**Comment by tooomm** [comment]
Is this the same as https://github.com/desktop/desktop/issues/2964?

**Comment by JordanMussi** [comment]
Yup duplicate of #2964
