### ISSUE TITLE
I can't push/pull anymore in GitHub Desktop

### ISSUE THREAD

**Issue by Zawodowiec1532** [desktop/desktop#3472]
Hello, I have created a private repository and I can't pull/push/fetch to it. (via Windows Desktop).
The error is:
`Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.`

While using GitKraken its working fine.
Repo isn't archived and I'm owner of it.

Log below.
[2017-11-30.desktop.production.log](https://github.com/desktop/desktop/files/1519043/2017-11-30.desktop.production.log)

**Comment by iAmWillShepherd** [comment]
Hi @Zawodowiec1532! I'm sorry you are having issues with GitHub Desktop.  Looking through your logs, it seems as if we are finding your account on github.com, but we are unable to authenticate it.

Would you mind singing out of the app and signing back in?

**Comment by Zawodowiec1532** [comment]
I did that, result is same.
I have even tried: logout, exit app, launch app, login.. still same issue. :/

**Comment by iAmWillShepherd** [comment]
Are you using 2FA?

**Comment by Zawodowiec1532** [comment]
I went to Repository Settings in Windows Desktop and changed:
`git@github.com:Zawodowiec1532/wsg.git`
to
`https://github.com/Zawodowiec1532/wsg.git`

And it's working. Thanks.

**Comment by iAmWillShepherd** [comment]
That's great!!! FYI, we don't fully support SSH at the moment. Follow issue #2579 to stay up-to-date on SSH support.
