### ISSUE TITLE
Pull request status not refreshing after pushing

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#3476]
On 1.0.10-beta2.

I pushed to https://github.com/desktop/desktop/pull/3228 and expected the PR indicator to show a pending status, but it stayed green.

**Comment by iAmWillShepherd** [comment]
Doesn't #3228 change the `pullRequestUpdater` and the infrastructure around it? Only wondering because merging that PR will likely affect this issue.

**Comment by joshaber** [comment]
Yeah, that _might_ fix the issue. I'll recheck.

**Comment by joshaber** [comment]
Still seems to be an issue.

**Comment by iAmWillShepherd** [comment]
It's definitely an issue on my branch too, #3432. It's causing me some trouble because I rely on those updates to update the menu.

**Comment by iAmWillShepherd** [comment]
I believe PR #3511 should fix the underlying issue causing this.
