### ISSUE TITLE
White Screen of Death on launch (Windows 10)

### ISSUE THREAD

**Issue by RJWoodhead** [desktop/desktop#3478]
When launched, Desktop just displays a white window with no content whatsoever. While I'm all in favor of minimalist UI's, this is perhaps a bit overboard. :)

Just started happening when I launched Desktop today. I have done multiple uninstalls / reinstalls using the latest installer / reboots.

Fully updated Windows 10 install on a i7 with plenty of ram.

I am (literally!) drawing a blank here.

**Comment by j-f1** [comment]
Can you open the developer tools (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>), switch to the “Console” tab, and post anything in there here?

**Comment by RJWoodhead** [comment]
Ah, the developer tools are actually available. I tried them before but must have mistyped.

Here is the console log:

Uncaught (in promise) n
dexie.es.js:1382 Unhandled rejection: AbortError: Transaction aborted
    at IDBTransaction.<anonymous> (file:///C:/Users/DeepThought/AppData/Local/GitHubDesktop/app-1.0.9/resources/app/renderer.js:5:67788)
    at IDBTransaction.<anonymous> (file:///C:/Users/DeepThought/AppData/Local/GitHubDesktop/app-1.0.9/resources/app/renderer.js:5:43032)
ge @ dexie.es.js:1382

**Comment by niik** [comment]
@RJWoodhead thank you for that log data! So it looks like Desktop is unable to create (or upgrade) on or more indexeddb tables. I wonder if the underlying indexeddb files have become corrupt somehow. We could try blowing away all locally stored user data and have it recreate it from scratch. Could you try shutting down Desktop completely and then If locate the `GitHub Desktop` folder in `%AppData%`. It should look a little like this (ignore the highlight)

![](https://user-images.githubusercontent.com/13519935/32887499-654bc944-cac4-11e7-96fd-23353e2de22d.png)

Then try renaming the folder from `GitHub Desktop` to GitHub Desktop.bak` (or something) and then relaunch GitHub Desktop.

**Comment by RJWoodhead** [comment]
Renaming the folder as you suggest and restarting restores functionality. I have saved the folder in case it is needed for any further action.

Thank you for your quick reply, and my apologies for my slow response.

**Comment by niik** [comment]
@RJWoodhead Thanks for checking back in and letting us know how it went. Glad we could get it working for you!
