### ISSUE TITLE
Hitting enter (sometimes?) doesn't select the first item in a filter list

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#3479]
This is a regression. I haven't looked into it yet, but maybe related to https://github.com/desktop/desktop/pull/3447.

**Comment by iAmWillShepherd** [comment]
#3447 _should have_ made it so that a blank filter would do nothing. All filter lists are affected by that PR since I moved the logic to do nothing down to the component level.

**Comment by joshaber** [comment]
Yeah looks like it might be from https://github.com/desktop/desktop/pull/3267.
