### ISSUE TITLE
Preview support - .ico files

### ISSUE THREAD

**Issue by samdenty99** [desktop/desktop#3482]
### Description

Add file preview support for `.ico` files, as Electron supports displaying them.

### Version

**GitHub Desktop version:** 1.0.10-beta3

**Comment by niik** [comment]
Hey @samdenty99. We'd be happy to accept a pull request to add support for `.ico` files. It should be fairly straightforward. Here are the two most relevant parts that one would start working from. It could be as easy as just adding `.ico` here as long as there are no caveats with rendering `.ico` files.

https://github.com/desktop/desktop/blob/05b28f75fac15c1d77c91b205e4384bab371fbf2/app/src/lib/git/diff.ts#L297-L313

https://github.com/desktop/desktop/blob/05b28f75fac15c1d77c91b205e4384bab371fbf2/app/src/lib/git/diff.ts#L75-L78
