### ISSUE TITLE
New Github Desktop Being Replaced by Old Github Desktop

### ISSUE THREAD

**Issue by jimniels** [desktop/desktop#3484]
### Description

I'm having a hard time reproducing this issue, but it keeps happening so I'm filing an issue in hopes that others out there with the same problem will find this and perhaps add more clarity.

For some odd reason, every once and a while, the new GitHub desktop will all of the sudden just be replaced by the old GitHub desktop. It seems to happen if I don't restart my computer for a while. I"ll just go into sleep mode at the end of every work day. And after a couple days, when I open Github Desktop, all of the sudden it will be the previous version of Github desktop. It's like the app package in my Applications folder is being completely overwritten with the old application package. And I have no idea where it's even getting it. 

<img width="121" alt="screen shot 2017-12-02 at 8 17 56 am" src="https://user-images.githubusercontent.com/1316441/33517068-71f574a6-d73a-11e7-838c-b1256be84066.png">

The only way I've found to fix the issue is re-download the "new" Github Desktop and drag it to my Applications folder. It will say "Do you want to overwrite 'Github Desktop'?". I say yes, and then it overwrites the old one with the new one. I load the app back up and I see the new one again.
 
<img width="124" alt="screen shot 2017-12-02 at 8 18 18 am" src="https://user-images.githubusercontent.com/1316441/33517069-75c434a0-d73a-11e7-9ec5-c43e6fd3a60f.png">

Then, after a few days (unfortunately I haven't found a recurring pattern to it), I'll just load up GitHub desktop and for some reason, I'll be back on the old one again.

<img width="121" alt="screen shot 2017-12-02 at 8 17 56 am" src="https://user-images.githubusercontent.com/1316441/33517068-71f574a6-d73a-11e7-838c-b1256be84066.png">

### Version

**GitHub Desktop version:** 1.0.9
**OS version:** macOS Sierra 10.12.6

### Steps to Reproduce

Unfortunately this appears to happen sporadically. I've delayed reporting the bug, trying to find the cause but I haven't been able to find it.

### Logs

Logs from today (when I re-downloaded the new app).

```
2017-12-02T15:18:28.657Z - info: [ui] [AppStore] loading 21 repositories from store
2017-12-02T15:18:28.660Z - info: [ui] [AppStore] found account: jimniels (Jim Nielsen)
2017-12-02T15:18:29.435Z - info: [ui] launching: 1.0.9 (Mac OS 10.12.6)
```

**Comment by niik** [comment]
@joshaber Think we're gonna need your expertise on this one

**Comment by joshaber** [comment]
Wow that is whacky!

The update feeds for these apps are distinct. https://central.github.com/api/mac/latest is the old app, https://central.github.com/api/deployments/desktop/desktop/latest is the new app. So I don't think any wires are getting crossed there.

@jimniels Do you have any automated software deployment system installed? For example, some IT department system? Did you have the old GitHub Desktop installed previously?

**Comment by jimniels** [comment]
@joshaber ha yes, whacky indeed.

Sorry I should've initially provided this background info but yes, I did have the old Github Desktop installed previously. As I recall, I upgraded to the "new" GitHub desktop by downloading the application package and dragging/dropping it into my Applications folder. As for automated software deployment, I'm not precisely sure what software my employer has on my system. There's a separate user at the OS level for the IT group, so there might be something at the low level but nothing I've ever noticed before that updates other software on my system.

**Comment by joshaber** [comment]
My best guess is that the IT system is doing some shenanigans, but it's hard to say for certain. Is there someone in IT you could ask?

My only other theory is that the old GitHub Desktop's update system is left hanging around, and since they're installed in the same place it happily replaces the new app. But it _should_ be doing some verification to prevent this, and I don't know why it would think it needs to update in the first place.

A couple things you could try:

1. Delete GitHub Desktop (whatever version is currently installed), restart, and then install the new GitHub Desktop again.
1. Install the new GitHub Desktop but rename it to something else (e.g., `GitHub Desktop srsly` or something).

**Comment by jimniels** [comment]
Ok, I'm going to ask someone in IT, see if they have a suspicion as to what is going on. As for your other suggestions, I've tried number 1, but I've never tried number 2. So I'll give that a try and we'll see what happens. Thanks!

**Comment by jimniels** [comment]
Update: described my problem to someone in IT and they immediately had an inclination as to where the problem was coming from:

>It seems like the virus protection program could possibly have been trying to manage software updates unsuccessfully in this case...I disabled software updates on your computer so hopefully that solves the problem. 

So I'm going to go ahead and close this issue. If it happens again I can re-open it.

Thanks @joshaber
