### ISSUE TITLE
Update from upstream

### ISSUE THREAD

**Issue by Marsfan** [desktop/desktop#3491]
This could be considered an addition to #2237, which covered the old retrieve from master button. If I remember correctly, it also had the functionality to update from the upstream branch. I am still pretty green for git, and I don't really know how this is done from the command line, so it would be great to have this button back.

**Comment by say25** [comment]
Have you looked at either:
- Merge Into Current Branch - CmdOrCtrl+Shift+M
- Update From Default Branch - CmdOrCtr+Shiftl+U

Both are under the branch menu. The shortcuts only are available in 1.0.10-beta3 though

**Comment by niik** [comment]
Hey @Marsfan, We're planning to handle the specific case of forks in [1.1](https://github.com/desktop/desktop/issues/2364), it's detailed in our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md) under the 'Relationship to X' header which will allow you to merge from the upstream repository.

For the time being you'll have to update from the upstream master manually using the command line.

**Comment by alandball** [comment]
Started using the new app today, very nice!

Just a small workflow snag, with git used as source control from organisation. Working on a new feature, with upstream/<feature>. Other developers contributing to this branch too, so I regularly merge from upstream. Most pull requests go to upstream/dev or if its a new component with weeks of development, upstream/<feature>.

- The old client I would know if there was something new to merge from upstream if the button wasn't greyed out,
- In old client if it was wrong branch I only had to "View Branch" and then select branch and this upstream branch was near top, and then hit it to merge. This would last the rest of the session, so all subsequent merges was one click to merge upstream.
- With new client I click on Branch -> Merge into current bra, or use shortcut key to reduce 2 clicks, and then this upstream branch is between thousands of branches, so I type <feature> and it will sit at bottom of list as upstream/feature

Thanks for getting to here ;)

**Comment by daverogers** [comment]
Does nobody else work out of an integration, epic, or team/project-based branch? Everybody must simply work out of master? That'd be a curious way to work with git with multiple teams working on multiple long-term projects.

If not, when I fork from a branch there's a high probability I'd want to continue to get updates from that branch, no? It would be nice to have "Update From Forked Branch" or "Update From _BRANCHNAME_" in the dropdown.

**Comment by shiftkey** [comment]
@daverogers have you had a chance to look at our Compare tab changes that's slated to ship on Monday? This changes the History tab to become a way to compare and merge from whatever branch in the repository:

![](https://user-images.githubusercontent.com/359239/39613545-4e87a52c-4fab-11e8-8a53-77afaf7e99e2.gif)

This isn't quite as convenient as having an "Update from XYZ" menu item, but feel free to open a fresh issue if you've got ideas about how to take this experience further.
