### ISSUE TITLE
Error cloning, pushing and pulling

### ISSUE THREAD

**Issue by Luigi27m** [desktop/desktop#3498]
InitializeSecurityContext failed: Unknown error (0x80092013) - La funci�n de revocaci�n no puede comprobar la revocaci�n debido a que el servidor de revocaci�n est� sin conexi�n.
Error(s) during clone:
git clone failed: exit status 128

**GitHub Desktop version: 1.0.9

**OS version: Windows 10

**Comment by scottnath** [comment]
Getting this too:

Cloning into `{location}`
fatal: unable to access `{repo url followed by a backslash}`: Server aborted SSL handshake
Error during clone:
git clone failed: exit status 128

This happens on clone/push/pull

**GitHub Desktop version: 1.0.9

**OS version: Mac 10

**Comment by iAmWillShepherd** [comment]
Hi there! Could you please attach a copy of your log files?

**Comment by scottnath** [comment]
@iAmWillShepherd oddly, problem went away. Perhaps with the update to 1.0.10.

thanks for the response

**Comment by iAmWillShepherd** [comment]
That's great!!! Glad things got sorted out 😀 
If you have the issue again, please open a new issue and attach a copy of your logs and reproduction steps.
