### ISSUE TITLE
Keyboard scrolling in Pull Requests is not consistent 

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3499]
When scrolling the Pull Request list, the user should be able to click the `down` arrow and immediately select the top Pull Request, as this is the behavior for the Branch list.

Current behavior: user is stuck in the search filter.

<img width="741" alt="screen shot 2017-12-04 at 11 35 01 am" src="https://user-images.githubusercontent.com/14828183/33572373-9a73ab1a-d8e7-11e7-83da-9c64c316e19e.png">

1.0.10-beta3, osx 10.11

**Comment by tierninho** [comment]
Also, clicking `tab` from the filter should also take the user to the first Pull Request. It currently moves to the random grey selection.

**Comment by tierninho** [comment]
Lastly, when you filter on an existing PR, and then press `up` or `down` arrow, the blue highlighter should select the appropriate result. Currently, nothing happens.

<img width="353" alt="screen shot 2017-12-06 at 1 45 30 pm" src="https://user-images.githubusercontent.com/14828183/33687168-23054be6-da8c-11e7-999e-33a2a5f95300.png">


See the Branch list for the accepted result.

1.0.11-beta0, mac

**Comment by iAmWillShepherd** [comment]
> Also, clicking tab from the filter should also take the user to the first Pull Request. It currently moves to the random grey selection.

Looks like this issue may be related to my work in PR #3511
