### ISSUE TITLE
Get smarter about fetching

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#3502]
> Maaaaybe. But then whenever the background fetcher kicks in, we'll also refresh PRs. Which may be ok, but that duplicates work we're already doing in the pull request updater.

So our options seem to be: (1) make fetch smarter so that it only fetches PRs when not called from the background fetcher, or (2) the background fetcher now refreshes PRs as part of its fetch and the pull request updater is only in charge of the post-push logic.

There's probably some other options I'm not thinking of too 😄 I'd lean towards (1) for now for simplicity's sake, but I'm totally open to other thoughts.

@joshaber made the case that we should only refresh PRs in the fetch function when it's not initiated by the backgroundFetcher.

See PR #3448 for additional context.

**Comment by shiftkey** [comment]
:thumbsup: to the first approach
