### ISSUE TITLE
Ignore System http_proxy Variable for Enterprise Client

### ISSUE THREAD

**Issue by ctmrocks2435** [desktop/desktop#3507]
### Description
I work at a company that has its own Github enterprise. Specifically https://github.company.com
For a lot of applications to work, we have the system environment variables set for http_proxy and https_proxy. The issue is that Github Desktop seems to look at those variables and tries to use them, when since it is an internal domain for our company, it must ignore the proxy settings.

Some method should exist or be added to ignore system http_proxy variables. I have tried adding *.company.com to no_proxy system variable, but it does not seem to do anything.

### Version

**GitHub Desktop version:** 1.0.9
**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce / Expected Behavior

1. Have enterprise account / client.
1. Set system https_proxy and http_proxy variable to company proxy
1. Clone will fail.
1. Unset variables and Clone etc. works.

**Expected behavior:** See above

**Actual behavior:** See above

**Reproduces how often:** 100% of time.

### Logs

See attached
[2017-12-05.desktop.production.log](https://github.com/desktop/desktop/files/1531797/2017-12-05.desktop.production.log)

**Comment by iAmWillShepherd** [comment]
Thank you for taking the time let us know about this!

**Comment by shiftkey** [comment]
@ctmrocks2435 thanks for the detailed issue.

>  The issue is that Github Desktop seems to look at those variables and tries to use them, when since it is an internal domain for our company, it must ignore the proxy settings.

This is behaviour inherited from `libcurl`, the networking stack that Git uses, and it is designed for this sort of scenario - being able to transparently route traffic through a proxy server. 

You're on the right track by setting `NO_PROXY` to exclude hosts, but I don't think it supports wildcards in the hostname. [The source](https://github.com/curl/curl/blob/b7f5345976127f1af2ccad431f6b60d5402e1bde/lib/url.c#L2575) suggests this should either be wildcard `*` or a comma-separated list of the host names:

```c
  /* no_proxy=domain1.dom,host.domain2.dom
   *   (a comma-separated list of hosts which should
   *   not be proxied, or an asterisk to override
   *   all proxy variables)
   */
```

Have you tried setting a couple of hostnames in this way, and seeing if the behaviour of Desktop changes?

**Comment by niik** [comment]
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.
