### ISSUE TITLE
Create Pull Request: Branch name hashes not encoded in URL

### ISSUE THREAD

**Issue by jom** [desktop/desktop#3508]
### Description

Branch names with `#` are not encoded to `%23` when creating a Pull Request from GitHub Desktop.

### Version
Git 2.14.3

**GitHub Desktop version:** 1.0.10

**OS version:** MacOS 10.13.1 (17B1003)

### Steps to Reproduce

1. Create a branch with hash in it (`fix/big-ol-bug#123`). 
2. Branch > Create Pull Request
3. Browser will load and hash isn't encoded (`fix/big-ol-bug%23123`) so I need to reselect the branch name before creating the PR.

**Expected behavior:** It would load:
`https://github.com/org/repo/compare/fix/big-ol-bug%23123`

**Actual behavior:** It loads `https://github.com/org/repo/compare/fix/big-ol-bug#123` and tries to create a PR for nonexistent `fix/big-ol-bug` branch

**Reproduces how often:** 100%

**Comment by iAmWillShepherd** [comment]
Thanks for bringing this to our attention!
