### ISSUE TITLE
Remove the Pull Request badge for new branches

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3510]
When creating a new branch, the Pull Request badge from the existing branch should not be carried over. 

Although, it seems like it eventually updates itself and the badge is removed.

<img width="548" alt="screen shot 2017-12-05 at 12 16 45 pm" src="https://user-images.githubusercontent.com/14828183/33629420-d38b8608-d9b8-11e7-96be-ff6a61323aa8.png">
<img width="494" alt="screen shot 2017-12-05 at 12 16 52 pm" src="https://user-images.githubusercontent.com/14828183/33629421-d419c5f8-d9b8-11e7-9586-f2d77f50277a.png">

1.0.10-beta3, mac

**Comment by iAmWillShepherd** [comment]
I believe this behavior is related to #3337. I'm currently digging to see what's wrong.

**Comment by joshaber** [comment]
Yeah, I'd lump this in with #3337. It's another manifestation of the same underlying problem.
