### ISSUE TITLE
Timeline display missing from GitHub Desktop

### ISSUE THREAD

**Issue by cpcallen** [desktop/desktop#3515]
### Description

The timeline display is missing, as is the option to select the branch to compare against.

### Version

**GitHub Desktop version:** 1.0.10
**OS version:** Mac OS X El Capitan 10.11.6 (15G17023)

### Steps to Reproduce

1. Open GitHub Desktop
1. Look at top of window

**Expected behavior:** ![A timeline display is seen.](https://user-images.githubusercontent.com/5603958/33661792-5f56bd4c-da81-11e7-91b9-cd6d84de88d3.png)

**Actual behavior:** ![No timeline display is seen.](https://user-images.githubusercontent.com/5603958/33661818-6f14d354-da81-11e7-867e-caee12def715.png)

**Reproduces how often:** Always.

### Logs

[2017-12-06.desktop.production.log](https://github.com/desktop/desktop/files/1535117/2017-12-06.desktop.production.log)

#### Additional Information

The timeline display and the ability to compare against different branches was basically the main reason I used GitHub desktop.  The new version is therefore mostly useless; I can get better visualisation from the git command line tools!

**Comment by niik** [comment]
Hey @cpcallen, we're working on adding relationship between branches. Please subscribe to  https://github.com/desktop/desktop/issues/2639 to follow along!
