### ISSUE TITLE
Wording: 'remain on disk' to 'remain on drive'

### ISSUE THREAD

**Issue by vbNETonIce** [desktop/desktop#3516]
https://github.com/desktop/desktop/blob/525936a9aec13202206887ea0ab3e2124d7211ad/app/src/ui/remove-repository/confirm-remove-repository.tsx#L49

not wanting to be pedantic but renaming the warning makes more sense for users of SSDs.

**Comment by iAmWillShepherd** [comment]
Thanks for the feedback!

Given that "drive" doesn't really apply to all technologies either (network shares, SANs, etc), we're not comfortable settling on your currently recommended wording. We would be happy to review a pull request if you want to suggest a better term that would be inclusive of all technologies where data may be stored.

Thanks again for your interest in Desktop :+1:
