### ISSUE TITLE
Cmd-R not opening pull request for active branch

### ISSUE THREAD

**Issue by cheshire137** [desktop/desktop#3518]
I'm in version 1.0.10 on macOS Sierra. I'm experiencing a problem where when I hit Cmd-R to open the existing pull request or create a new pull request for the current branch, it instead opens the wrong pull request in my browser. For example, I'm on a branch that does not have a PR right now, named `fix-flaky-test`. When I hit Cmd-R from GitHub Desktop, it opens an existing pull request for a branch titled `search-nav`.

My current branch was started directly from `master`, and shouldn't include any of the same commits as what are in the `search-nav` branch besides those shared from also starting `search-nav` off of `master`. So it doesn't seem at all related to the branch of the PR Desktop takes me to, except that I have worked on `search-nav` earlier today and it might be remembering that instead of using my current branch?

**Comment by iAmWillShepherd** [comment]
Good catch, I'll look into this one soon. 🙇

**Comment by iAmWillShepherd** [comment]
Looks like this issue may be related to my work in PR #3511

**Comment by tierninho** [comment]
Here is a visual for this bug. The Cmd-R should open the top PR as it is associated with the current branch, not the grey highlighted one which is randomly selected.

<img width="366" alt="screen shot 2017-12-06 at 1 34 34 pm" src="https://user-images.githubusercontent.com/14828183/33686649-709419b6-da8a-11e7-8827-2cfb8e8d0659.png">

**Comment by tierninho** [comment]
I think we should note the `Create Pull Request`(`Cmd-R`) still exists when there is already a PR associated with the active branch, therefore we should consider greying it out.

**Comment by iAmWillShepherd** [comment]
PR #3432 should have made this menu item dynamic and PR #3511 should ensure that the menu item is updated everytime the active branch is changed.
