### ISSUE TITLE
Lots of commits to be pushed = high fans

### ISSUE THREAD

**Issue by cheshire137** [desktop/desktop#3519]
This is a strange one. I had a very old branch that was way behind master. I merged the latest master into my branch but didn't push to GitHub:

![github_desktop](https://user-images.githubusercontent.com/82317/33679960-c513da9e-da85-11e7-9242-6778969bfa68.png)

I continued working on the branch locally but I noticed my MacBook fans were getting louder and louder. I opened Activity Monitor and tried closing some apps that were suspect based on memory and CPU usage, including GitHub Desktop. I restarted GitHub Desktop quickly, though, thinking that if it were the problem, closing it and reopening would fix it.

However, my fans stayed very loud, running at high speed, for ten minutes or more while I kept working. Finally, I thought perhaps it was all those commits sitting around locally that were not yet pushed. I pushed them to GitHub and nearly immediately my MacBook calmed down. Fans settled back to their usual near-silent state with no other changes on my part besides pushing those commits.

I'm not definite that it was GitHub Desktop causing my high fan speeds, but it seems possible. I thought I'd bring it up just in case. I'm on version 1.0.10 on macOS Sierra.

**Comment by iAmWillShepherd** [comment]
This is interesting. Looks like some digging is in order! 🙇

**Comment by iAmWillShepherd** [comment]
What repo and branch were you using? 

I want to recreate this, but I believe we delete all of our old branched for Desktop, so instead of searching for a candidate repo, figured I'd just ask you for yours.

**Comment by cheshire137** [comment]
A super-secret repo, @iAmWillShepherd. 😀

**Comment by timofonic** [comment]
@cheshire137 Uhm, at first I tought a project had fans (as in fanatics) and those pushed lots of commits to it. I got curious and looked at this.

@iAmWillShepherd Any news about this? Can the issue affect other platforms? Has the issue been located?

**Comment by iAmWillShepherd** [comment]
@timofonic No. I was not able to reproduce this before leaving for winter break.

**Comment by Kentwilson33** [comment]
Well call customer support and ask for me personallly and i talk ya through it

**Comment by tierninho** [comment]
As a member of our team could not reproduce and/or the circumstances may be too unique to duplicate, this issue will be closed. Feel free to reopen to investigate further.

**Comment by cheshire137** [comment]
Thanks! I wonder if this is related to increasing memory usage of the GitHub Desktop Helper in macOS as time goes on. I just today had to exit and relaunch the app as it was using over a gig of memory.

**Comment by shiftkey** [comment]
@tierninho you asked me about this in chat but we're already tracking the RAM issue in #3149 which I need to add more information to.
