### ISSUE TITLE
Surfacing Pull Request indicator in the Branch list 

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3520]
We could enhance the branch list by adding a badge with the total amount of associated Pull Requests, so the user knows how many PRs are under each branch.

This would somewhat tie into surfacing which branches can be deleted and which could not, so even a trash-can icon could be present, and those branches with PRs would be greyed out.

<img width="336" alt="screen shot 2017-12-06 at 11 12 08 am" src="https://user-images.githubusercontent.com/14828183/33680682-447a1960-da77-11e7-8f81-1543c79d2cf7.png">

**Comment by j-f1** [comment]
When would you have a branch with multiple PRs? That would be very unusual. Did you want to have the PR ID listed instead?

**Comment by tierninho** [comment]
Yes, good catch. Perhaps just an indicator icon with or without the ID.

**Comment by joshaber** [comment]
IIRC the web UI doesn't allow you to create a PR from a branch that already has a PR associated with it. But adding some sort of indicator that there _is_ a PR makes sense to me 👍

**Comment by iAmWillShepherd** [comment]
Does this need any design input from @desktop/design since we are proposing new UI?

**Comment by joshaber** [comment]
Yeah it does. I don't think we need to prioritize it right now, but it's a good enhancement for the future.

**Comment by j-f1** [comment]
How about replacing the branch icon on the left with a PR icon if there’s a PR attached?

**Comment by shiftkey** [comment]
This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by billygriffin** [comment]
I'm going to remove future-proposal here since we now have #8048 to reflect this.
