### ISSUE TITLE
Should CI status say "Failure" or "failed"?

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3521]
A bit nit-picky, but I think we should use the word "failed" and not "failure" for the CI status check, as "failed" in surfaced in the current UI on GitHub.com:

<img width="812" alt="screen shot 2017-12-06 at 11 22 39 am" src="https://user-images.githubusercontent.com/14828183/33681129-82c2c3ce-da78-11e7-9e27-b62259212628.png">

<img width="503" alt="screen shot 2017-12-06 at 11 33 12 am" src="https://user-images.githubusercontent.com/14828183/33681424-4e83466e-da79-11e7-9bc2-8f4cace55095.png">

Also, "failed" is a clearer message that the action is in the past.

**Comment by j-f1** [comment]
How about `2/2 checks failed`?

**Comment by shiftkey** [comment]
That's this message: 

https://github.com/desktop/desktop/blob/56f6e4c786c20f0c1c58ed2e517621df0f5dff50/app/src/ui/branches/ci-status.tsx#L20-L21

I'm not sure if we have enough context here to represent `X / Y checks passed` without some refactoring. But let's figure out what we want to display here first.

**Comment by shiftkey** [comment]
This has churned a bit since we last looked at it, but #4330 should hopefully address the original question
