### ISSUE TITLE
The pull request number is too sticky in the Current Branch display

### ISSUE THREAD

**Issue by mark-friedman** [desktop/desktop#3526]
### Description

When I switch from a branch that I specified via the 'Pull Requests' list and then switch away to another branch (not a pull request) it still shows the pull request number in the Current Branch display.

### Version

**GitHub Desktop version:** 1.0.11-beta0

**OS version:** 10.12.6

### Steps to Reproduce

1. Switch from a branch that specified via the 'Pull Requests' list.
1. Switch away to another branch (not a pull request).

**Expected behavior:** That the Current Branch display would not shows the pull request number once I'm not in a pull request branch.

**Actual behavior:** The Current Branch display still shows the pull request number.

**Reproduces how often:** 100%

### Logs

No logs appeared to have been generated.

**Comment by shiftkey** [comment]
@mark-friedman thanks for the report. We're already tracking this in #3510, and we're working on a fix for this in https://github.com/desktop/desktop/pull/3511!
