### ISSUE TITLE
Menus are missing while scrolling 

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3537]
Menu are missing if you scroll, perhaps because we are replacing the entire menu vs modifying it in place - an electron limitation.

Repro:
- click Fetch
- select any menu
- scroll across the other menus
- eventually they all go blank. 
- Try to do it as its fetching... might take a few times

<img width="678" alt="screen shot 2017-12-07 at 10 12 07 am" src="https://user-images.githubusercontent.com/14828183/33731673-c1243f88-db38-11e7-8037-f39044ca1955.png">

1.0.11-beta0, mac

**Comment by joshaber** [comment]
https://github.com/electron/electron/issues/528 is the Electron issue about this. The problem is that it's really hard to _update_ the app menu, so instead we recreate it when something changes.

**Comment by tierninho** [comment]
Closing this as it has not come up enough times to be validated as a real problem.
