### ISSUE TITLE
Move away from relying on JS truthiness

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#3538]
See PR #3535 for more context. 

I think we should be explicit in our conditional statements instead of relying on truthiness. This should limit gotchas such as the one referenced above.

```ts
let a: ReadonlyArray<number> | null = null
let s: string | undefined = undefined

if (a) { }
if (a != null) { } //preferred

a = [0, 1, 2, 3]

if (a.length) { }
if (a.length > 0) { } //preferred
```

**Comment by j-f1** [comment]
I’ll take a look at this.

1️⃣ ❓:

Should this throw?

```js
let x: boolean = myFunction()

if (x) { }
```

**Comment by joshaber** [comment]
👍 

```js
if (a !== null) { } //preferred
if (s !== undefined) { } //preferred
```

I'd lump these two together and suggest that we prefer:

```js
if (s != null) { } //preferred
```

It's rare that we care about the distinction between `null` and `undefined`, and I'd go further and say that caring is usually an anti-pattern.

**Comment by iAmWillShepherd** [comment]
The only reason I included `undefined` is that we are using optional types. 

Consider this:
```ts
function foo(obj?: SomeObject) {
  let a = obj.someProperty   //obj can't be null here, but it can be undefined, which means this fails
}
```

In this case, we'd have to check for `undefined`. We've been getting around this issue by relying on the truthiness of `undefined`.

**Comment by iAmWillShepherd** [comment]
Should this throw?

```js
let x: boolean = myFunction()

if (x) { }
```

@j-f1 no it should not. 

The intent behind this issue is that we should be explicit instead of relying on truthiness. I think `booleans` are exempt from this since they are the primitives all other conditional expressions evaluate.

**Comment by joshaber** [comment]
> The only reason I included `undefined` is that we are using optional types. 
> 
> Consider this:
> ```ts
> function foo(obj?: SomeObject) {
>   let a = obj.someProperty   //obj can't be null here, but it can be undefined, which means this fails
> }
> ```
> 
> In this case, we'd have to check for `undefined`. We've been getting around this issue by relying on the truthiness of `undefined`.

Hmm, I'm not sure I understand?

`!= null` coerces `undefined` so that both `null != null` and `null != undefined` are false. Or in other words, it generalizes across both `null` and `undefined`.

**Comment by iAmWillShepherd** [comment]
But `null !== undefined` return `true`. 

I prefer using `===` and `!==` as opposed to `==` and `!=`, but so long as we make sure we remember to use the loose equality operators, we should be fine.

**Comment by joshaber** [comment]
>I prefer using `===` and `!==` as opposed to `==` and `!=`

Me too! To be clear, I'm _only_ talking about the case of `null`. I think differentiating between `null` and `undefined` in the context of an `if` is making a distinction without a difference. What we're trying to check is whether the value is _something_ or _nothing_, regardless of whether the particular form of nothing is `null` or `undefined`. http://adripofjavascript.com/blog/drips/equals-equals-null-in-javascript.html does a better job of explaining this than I think I am doing 😂

**Comment by j-f1** [comment]
> Me too! To be clear, I'm only talking about the case of `null.

In fact, that’s already configured as part of the [`eqeqeq`](https://eslint.org/docs/rules/eqeqeq#smart) 
ESLint rule:

https://github.com/desktop/desktop/blob/f12ff8c4775904bbb44ef6fdb78b26e734c14455/.eslintrc.yml#L65-L67

**Comment by iAmWillShepherd** [comment]
@joshaber that made sense, also thanks for the article. So I'm down for using `==` and `!=` only when checking against `null` or `undefined`.

**Comment by iAmWillShepherd** [comment]
@j-f1 were you intending to tackle this work?

**Comment by j-f1** [comment]
> were you intending to tackle this work?

Yes 👍

**Comment by iAmWillShepherd** [comment]
Could you open a PR to track since I can't assign you to the issue?

**Comment by j-f1** [comment]
> Could you open a PR to track?

Yup. ⬆️ ✅

**Comment by j-f1** [comment]
From my PR above, these appear to be the requirements:

- value is not declared (or inferred) to be a boolean
- value is inside any number `&&`, `||`, or `!` expressions and either:
   - the test of an `if` statement, or
   - the test of a ternary.

**Comment by iAmWillShepherd** [comment]
@j-f1 not sure I understand...

**Comment by j-f1** [comment]
@iAmWillShepherd Those are the requirements for a node to be reported by this rule.

**Comment by iAmWillShepherd** [comment]
Got it.

> value is inside any number &&, ||, or ! expressions and either: 

This threw me off because I read it as a value is in a number, &&, ||, or ! expression.

**Comment by j-f1** [comment]
Looks like I forgot an `of` when typing that part. Edited above to correct.

**Comment by iAmWillShepherd** [comment]
Closing this out since the team has started being explicit with `null` and `undefined` checks.

**Comment by j-f1** [comment]
Aha! https://palantir.github.io/tslint/rules/strict-boolean-expressions/
