### ISSUE TITLE
Repo cloning error dialogue

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3539]
Perhaps we can change the error dialogue to something more understandable to the layman? and do we need some validation on the `url` field? I entered some jiberish in the `url` field and got this:

<img width="448" alt="screen shot 2017-12-07 at 11 14 32 am" src="https://user-images.githubusercontent.com/14828183/33733867-ff1ce9dc-db3f-11e7-948a-9baa8f16140e.png">
<img width="974" alt="screen shot 2017-12-07 at 11 15 47 am" src="https://user-images.githubusercontent.com/14828183/33733870-ff4b191a-db3f-11e7-92f5-92d63e12b50f.png">

1.0.11-beta0, mac

**Comment by j-f1** [comment]
Looks like we should switch to regular `git clone` here.

> `git lfs clone` is deprecated

**Comment by shiftkey** [comment]
This is a job for `dugite` and the [error parsing](https://github.com/desktop/dugite/blob/master/lib/errors.ts) it performs. @tierninho would you mind moving this issue there?

Once we update `dugite` in the app we'll have to handle that new error code here.

**Comment by shiftkey** [comment]
The `git lfs clone` warning will be fixed by #3575

**Comment by tierninho** [comment]
@shiftkey added the bug to: https://github.com/desktop/dugite/issues/155

**Comment by iAmWillShepherd** [comment]
Fixed in #3575
