### ISSUE TITLE
Error after clicking open in command prompt

### ISSUE THREAD

**Issue by xxCoolxx18** [desktop/desktop#3558]
Error: spawn where ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Version: 1.0.10
OS: Windows 10.0.16299

**Comment by shiftkey** [comment]
@xxCoolxx18 could you open the Developer Tools (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>), switch over to **Console** tab, ensure `Verbose` is selected, and try to trigger the issue again.

<img width="913" src="https://user-images.githubusercontent.com/359239/33802542-89f33dce-ddcd-11e7-838d-e11bf5337213.png">

There's some [additional tracing](https://github.com/desktop/desktop/blob/1666431d55ff2570d39d16f64341a7dc35ee249b/app/src/lib/shells/win32.ts#L117-L128) here that might yield some clues as to why `cmd` might not work.

I'm also wondering if `cmd` is on your `PATH` - if `C:\Windows\System32` is missing maybe that's what's going wrong here.

**Comment by maxbed** [comment]
10.12.2017. 07.16, "Brendan Forster" <notifications@github.com> је
написао/ла:

**Comment by shiftkey** [comment]
Closing as inactive.

@xxCoolxx18 if you can reproduce the issue and look at the developer tools I'm happy to revisit this issue.
