### ISSUE TITLE
[Feature request] PR from client like as in old Github

### ISSUE THREAD

**Issue by Mlocik97-issues** [desktop/desktop#3560]
![screenshot_27](https://user-images.githubusercontent.com/31345346/33799507-935bcf70-dd2d-11e7-849f-bc8b6c18b6ce.png)

I really don't like always swapping between client and browser GitHub.

**Comment by shiftkey** [comment]
@Mlocik97-issues thanks for the feedback. We're tracking this in https://github.com/desktop/desktop/issues/295 so please follow along with that issue.
