### ISSUE TITLE
Directory in repo gets first letter of name duplicated in index but not filesystem, can't commit anymore

### ISSUE THREAD

**Issue by DeepMac** [desktop/desktop#3572]
### Description

Using GitHub Desktop to access an internal repo, after checking out code and moving folders around, a commit and push worked fine. but a later fetch created a bizarre issue where the filename of one of the folders has the first letter of the name duplicated. This applies only to the index of the files in GitHub Desktop, not the actual filesystem folders.

Because of this, further commits, pushes or fetches always generate an error, usually about invalid paths.

### Version

**GitHub Desktop version:** 1.0.10

**OS version:** Windows 7 Enterprise

### Steps to Reproduce

1. Clone a repo using the URL option
2. Fetch files
3. In the local filesystem, add a new folder such as "foo bar" and move files into it
4. Commit the changes
5. Push the repo.
6. Do a fetch to synch any changes
7. Observe if recently created folder is now listed with an extra letter, i.e. "ffoo bar" in index.
8. Make a few changes
9. Attempt to commit changes, observe error message.

**Expected behavior:** Foldernames not to change, commits to work

**Actual behavior:** Index munges folder name, loses its mind, Github becomes useless, children cry

**Reproduces how often:** 100% with the specific internal repo, do not know if it happens elsewhere.

### Logs
2017-12-11T15:36:31.381Z - info: [ui] [AppStore] loading 1 repositories from store
2017-12-11T15:36:33.197Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes (took 1.640s)
2017-12-11T15:36:33.525Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.951s)
2017-12-11T15:36:33.852Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 2.478s)
2017-12-11T15:36:34.929Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- 000 README.txt (took 1.059s)
2017-12-11T15:36:36.334Z - info: [ui] launching: 1.0.10 (Windows 6.1.7601)
2017-12-11T15:36:36.854Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.088s)
2017-12-11T15:36:37.915Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 1.022s)
2017-12-11T15:36:40.846Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 4.876s)
2017-12-11T15:38:00.071Z - error: [ui] `git reset -- .` exited with an unexpected code: 128.
error: Invalid path 'prod/\'
fatal: make_cache_entry failed for path 'prod/\'

2017-12-11T15:40:00.743Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.169s)
2017-12-11T15:41:16.253Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.156s)
2017-12-11T15:42:52.246Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.126s)
2017-12-11T15:43:52.905Z - error: [ui] `git reset -- .` exited with an unexpected code: 128.
error: Invalid path 'prod/\'
fatal: make_cache_entry failed for path 'prod/\'

2017-12-11T15:48:15.034Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.138s)
2017-12-11T15:48:16.176Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- prod/\ (took 1.131s)
2017-12-11T15:50:55.919Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.207s)
2017-12-11T15:51:55.592Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.118s)
2017-12-11T15:52:49.754Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.013s)

#### Additional Information

Important note: While the log says the folder name is "prof/\" there are no special characters in the folder name.
I have also verified that I can clone this repo on a RHEL box using git with no errors, and commit changes as well.

I have tried wiping the local repo and re-cloning. Oddly, it will download everything just fine. Only afterwards does it munge the index and refuse future commits. This has eliminated any usefulness in using Github desktop as now I need to copy the files off the local PC to a Linux box, commit them there, and push... Then delete the repo on my Windows system and re-clone.

:/

**Comment by shiftkey** [comment]
@DeepMac are you able to reproduce this issue using just [Git for Windows](https://git-for-windows.github.io/)? That's what we're using in Desktop (we're on 2.15.0 currently, which isn't far behind the latest version 2.15.1), and if we can get a reproduction together from the CLI then it becomes much easier to investigate.

> Observe if recently created folder is now listed with an extra letter, i.e. "ffoo bar" in index.

What command(s) are you using to poke at the index and see this additional character appear?

**Comment by DeepMac** [comment]
@shiftkey I'll test out the CLI version tomorrow and let you know.

As for seeing the extra letter appear, it actually shows up right in the GUI. But the folder entry itself in NTFS is not, as far as I can observe, modified. There's some other shennanigans going on where if I change the name (say "prod" to "foo"), the change is detected in GitHub Desktop but again the GUI is showing it as "ffoo" or "pprod". And not committing.

I had to stop using it for now in a project due to it blocking development, :(

**Comment by DeepMac** [comment]
More info. Internally using BitBucket, which is the working repo.
Installed Git for Windows CLI. Trying to commit existing local clone still gave an error, had to issue an explicit "git rm prod" and then do a commit. Appeared to succeed:

![git2](https://user-images.githubusercontent.com/4560942/34009048-5f58a224-e0d5-11e7-9191-7051f1622341.png)

However, can't push any local changes, too diverged. So I tried to pull and it gives these errors:

  error: Invalid path 'prod/\'
  error: Invalid path 'prod/\'

along with numerous merge conflicts. Note that invalid path message though. No clue why it still does that. I think the original index entry for this got munged. I do not control the upstream server.

Update: Looking at commit in repo browser directly, appears that somehow  Github Desktop created an entry for the files under "prod" named "\". This makes it very unhappy all-around: Git CLI, desktop and the Github business server.

![git3](https://user-images.githubusercontent.com/4560942/34011362-c4a38a06-e0dd-11e7-9858-8f74a4b2f5fa.png)

In Windows NTFS it is not possible to have slashes or backslashes as part of filenames or directories. But the way Windows CLI and Explorer reacts to them in creating or renaming directories is.... creative. It is likely that is where the problem lies. Some examples for devs to test:

1) Open cmd.exe
2) Move to a temp directory
3) Issue these commands  and observe their results
mkdir foo
mkdir foo\foo
dir foo
dir foo\foo
mkdir foo2/
mkdir foo2/foo2
mkdir "foo2/"
dir foo2
dir 
dir /x

You'll see what I mean. I suspect what happened was renaming the folder, I probably typed "prod/" in Explorer. Which correctly created a folder named "prod". GitHub Desktop must have recorded the changes differently somehow, and though there was now a file named "/" inside a folder named "prod".

Further analysis on my end will take time away from the contracting project but hopefully this will lead everyone down the right path. I'll need to manually fix it in our repo on my side.

**Comment by shiftkey** [comment]
@DeepMac thanks for the extra details. There's a couple of things I'm not clear on here:

>  Trying to commit existing local clone still gave an error

Can you recall the error you saw here? I can't see a corresponding commit message in the logs.

> ![](https://user-images.githubusercontent.com/4560942/34011362-c4a38a06-e0dd-11e7-9858-8f74a4b2f5fa.png)

This screenshot is really interesting, because it looks like the index has an entry named `\` which is considered a blob (the internal representation of a file in the Git object database) rather than a tree (the internal representation of a folder in the Git object database).

>  I suspect what happened was renaming the folder, I probably typed "prod/" in Explorer.

This is impressive, because Explorer actively tells me off and blocks me from doing this:

<img width="416" src="https://user-images.githubusercontent.com/359239/34461424-de6a76fa-edff-11e7-8b36-7c92605b6483.png">

> But the way Windows CLI and Explorer reacts to them in creating or renaming directories is.... creative.

If you've somehow tricked Git into creating an entry named `\` in the index, then I can see how files within that directory could be affected. And if Git doesn't consider it a directory internally, trying to stage files under that directory for committing are probably going to confuse it here.

Given this was triggered through an `explorer.exe` case I can't reproduce confidently enough to dig into Git for Windows' behaviour, I'm going to leave this for now and see if we encounter any other cases like this.

**Comment by DeepMac** [comment]
I'll see if I can reproduce it. The workstation in question has various corporate controls installed, could be some other culprit or interaction. Or creative abuse by the end-user, :}

**Comment by stevenktruong** [comment]
I had this issue, too. For me, it was caused by a .git folder inside the folder I wanted to commit.

**Comment by nojdh** [comment]
I had the same issue and I found that the directories getting an extra letter had a .git from an old clone from another repository. Fixed it by simply removing the .git folders from the directories that had the issue.

**Comment by DeepMac** [comment]
@nojdh Was the old .git folder on the Windows filesystem prior to the issue? Or in the repo you cloned?

That may be what happened to me, I'll need to check it in the office today.

**Comment by DeepMac** [comment]
I confirmed it looks like this was the culprit, based on the history I can view. I'm not sure why it happens though.

**Comment by djjd47130** [comment]
I hit the exact same issue, and confirmed that the reason was the problematic folder had an old .git folder from before. This might actually be a "feature", allowing you to put a repo inside of a repo inside of a repo (gitception). So long as you respect those in the .gitignore file.

**Comment by hayden-t** [comment]
just had it happen to me, gui, just gives errors: exit code 1 on commit

**Comment by joshbalsillie** [comment]
Been dealing with this same issue, is there any way to clear out the issue in a command line?
