### ISSUE TITLE
Feature request: Text search in commit diff

### ISSUE THREAD

**Issue by shramee** [desktop/desktop#3573]
### Description

I often make large commits and need to browse through their diffs to find out what I changed in previous commit. For doing this I have to switch to browser coz I need to for example search for a function name. Would be awesome if we can have that available in app itself 😅  😉 

### Version

**GitHub Desktop version:** 1.0.10

**OS version:** 10.13.1

### Steps to Reproduce

Would love it if I could search here...

![image](https://user-images.githubusercontent.com/11048263/33849347-60e4df00-ded6-11e7-836a-9e219236cdb7.png)

**Comment by shiftkey** [comment]
@shramee thanks for the feedback. We're already tracking this in #2306 - please follow along with that issue!
