### ISSUE TITLE
Add "Ignore and delete" option

### ISSUE THREAD

**Issue by nawagers** [desktop/desktop#3577]
When right clicking the file in the "Changes" panel, there is an option to "Ignore" and one to "Ignore all type". Often, I find that the file has already been committed and pushed before, but it never should have been in the first place. It would be great if I could both delete the file and put it in .gitignore for the future at the same time. Currently I'd have to delete the file, commit/push, then change/create the file again, then add it to .gitignore and commit/push again.

**Comment by iAmWillShepherd** [comment]
As a workaround try running this **after** you've committed your _gitignore_ file:

`git clean -xdf && git commit -am "Remove ignored files" ` 

Note that this will remove all files not tracked by git in addition to all file types and paths specified in your _gitignore _ file.

**Comment by shiftkey** [comment]
This is very similar to #2537, and I'm going to close this out in favour of that with some extra context. @nawagers please follow along with that issue.

I'd rather the app handle this transparently then adding an additional menu item. We should warn users when tracked files will be affected by updating your `.gitignore`, and ask them to confirm the action.

I took a shot at implementing this in #3164 but had to put it aside - you can see some of the discussion we had in there around the actual implementation of this.
