### ISSUE TITLE
Clean up the error message

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3579]
When reverting a commit I got an error message that looks to include double "hints" even though it appears to be one sentence.

I believe it should read:

`error: Reverting is not possible because you have unmerged files.`
`hint: Fix them up in the work tree, and then use 'git add/rm <file>',`
`as appropriate, to mark resolution and make a commit.`
`fatal: revert failed`

Current error:
<img width="455" alt="screen shot 2017-12-12 at 9 14 29 am" src="https://user-images.githubusercontent.com/14828183/33898359-06391b92-df1d-11e7-9836-0199f1b4ef06.png">

**Comment by joshaber** [comment]
It looks like this is coming from git itself:

https://github.com/git/git/blob/7668cbc60578f99a4c048f8f8f38787930b8147b/advice.c#L106-L107

https://github.com/git/git/blob/7668cbc60578f99a4c048f8f8f38787930b8147b/advice.c#L48-L65

So to customize this we'd need to parse this error in dugite.

**Comment by tierninho** [comment]
moved to dugite repo: https://github.com/desktop/dugite/issues/156
