### ISSUE TITLE
Github Desktop doesn't support Powershell

### ISSUE THREAD

**Issue by vczh** [desktop/desktop#3581]
### Description

Github Desktop doesn't support either Powershell or cmd.

### Version

**GitHub Desktop version:** 1.0.10
**OS version:** Microsoft Windows [版本 10.0.16299.64]

### Steps to Reproduce

1. File -> Options -> Advanced -> Shell = PowerSHell
2. Right click on a repo cloned from github and select "Open in PowerShell"

**Expected behavior:** Open PowerShell with all the experience just like Github for Windows

**Actual behavior:** 
Prompted a dialog:
```
Unable to locate git

We were unable to locate Git on your system. This means you won't be able to execute any Git commands in the command prompt.
To help you ....
```

**Reproduces how often:** 100%

### Logs

Want to follow the instruction
```
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\GitHub Desktop\logs\*.desktop.production.log`
```
but it turns out that there is no such file on my disk.

#### Additional Information

My machine has Github for Windows installed

**Comment by joshaber** [comment]
Hi @vczh!

We no longer install Git for Windows as part of GitHub Desktop. If you would like to install it, visit https://git-for-windows.github.io.

If you just wanna open Powershell, you should be able to click the "Open without Git" button.

**Comment by vczh** [comment]
@joshaber  So what's the point if you let people open PowerShell in that repo folder but cannot use git?

**Comment by joshaber** [comment]
Many developers use other command line tools in their development process. This gives them a quick way to open a shell in the context in which they are working.
