### ISSUE TITLE
Opening a PR no longer asks the user if they want to push first

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#3583]
This is a regression brought to my attention by @Haacked.

The previous behavior for opening a PR in Desktop was to:
1. Check if the PR has been published, if not, ask user if they want to publish
2. Check if the PR is ahead of the branch on remote if so, ask if the user wants to push first
3. Just create the PR already

**Comment by joshaber** [comment]
Gonna move this to the 1.0.x milestone as we can/should fix this in a patch update.

**Comment by shiftkey** [comment]
I wasn't able to reproduce this with these four flows in the app:

 - create branch, click "Create Pull Request" menu item -> "Push Commits" dialog shown
 - create branch, create commit, click "Create Pull Request" menu item -> "Push Commits" dialog shown
 - create branch, push branch (with no commits), click "Create Pull Request" menu item -> browser opens
 - create branch, create commit, push branch, click "Create Pull Request" menu item -> browser opens

**Comment by shiftkey** [comment]
Acutally, the theory I have about this is nestled in `_openCreatePullRequestInBrowser`:

https://github.com/desktop/desktop/blob/a6627ddc09edbdbfae7dccab6e750364a3beb69a/app/src/lib/stores/app-store.ts#L3068-L3078

Notice that we return early if the repository lacks GitHub information or if the current tip isn't valid. This is a reasonable thing to do, but something we already did earlier in `_createPullRequest`:

https://github.com/desktop/desktop/blob/a6627ddc09edbdbfae7dccab6e750364a3beb69a/app/src/lib/stores/app-store.ts#L2911-L2919

We can skip the second lookup here and just past through `branch` (we do this in the "Push Commits" flow) but maaaaaaybe the first check is also susceptible to failing and returning early.

**Comment by iAmWillShepherd** [comment]
@shiftkey , I was able to reproduce this by doing the following:
1. Create a branch
1. Commit some stuff to the branch
1. Create PR using top bar menu
1. The browser opens to the create PR page

What is expected here is that the Publish Branch dialog is opened.

**Comment by tierninho** [comment]
I cannot reproduce this on 1.0.11-beta0. Expected behavior intact.

**Comment by iAmWillShepherd** [comment]
@tierninho that's odd, I was able to reproduce this. In any case, there was a bug in our code that #3584 addressed.

@Haacked, are you still having this issue?

**Comment by shiftkey** [comment]
@iAmWillShepherd 

> What is expected here is that the Publish Branch dialog is opened.

Are we talking about the "Publish Repository" dialog? Or the "Push Commits" dialog?

**Comment by iAmWillShepherd** [comment]
So I'm am no longer able to reproduce this issue, so I'm going to close. Feel free to reopen @Haacked if you continue to experience it. A gif would be nice too 👍
