### ISSUE TITLE
Where is the "Base Branch selection"?

### ISSUE THREAD

**Issue by greggwon** [desktop/desktop#3592]
I have noticed, after updating github desktop for windows, that the "base branch selection" feature seems to have been removed.  I use this feature a lot, because I branch for changes from a related release which I need to keep in view as my "base" set of changes that I diff against.   I need this facility to be available to me to provide an easy "catch up merge" function in case of bugfixes against those releases etc.  Am I just overlooking where this feature is available?

**Comment by tierninho** [comment]
@greggwon Thanks for reaching out. The base branch is accessed on GitHub.com by selecting the `Compare on GitHub` menu item in the Branch menu:

<img width="284" alt="screen shot 2017-12-13 at 9 06 11 am" src="https://user-images.githubusercontent.com/14828183/33951898-14bf841c-dfe5-11e7-86ab-03e4f3abd7e4.png">
<img width="1117" alt="screen shot 2017-12-13 at 9 06 24 am" src="https://user-images.githubusercontent.com/14828183/33951899-14d69468-dfe5-11e7-87ec-87a49bfb95ce.png">

Your branch must be selected in Desktop first. Let us know if you have any further questions.

**Comment by greggwon** [comment]
This selection is grayed out for me.

**Comment by j-f1** [comment]
Is your repository a GitHub repository?

**Comment by greggwon** [comment]
Some are, some are not.  I just need the functionality that was there before.  I could specify a base branch name, and then either merge from it, or look at the two branch depictions to understand what commits were different between them.  That worked really well.

Gregg

**Comment by tierninho** [comment]
Thanks for the update Greg. 

Is this happening on any branches that are already published to GitHub.com?

**Comment by greggwon** [comment]
I can't check any other repositories except the one GitHub enterprise repo that I have configured in GitHub desktop.  I recently replaced my laptop (this is why I have the new version of desktop installed, and I did copy the repo trees across to the new disk) and can't find the option to add existing repositories into view, in GitHub desktop.  I was able to add the one enterprise desktop, but don't remember how I was able to get it to appear.

The interface I am looking for used to be under the options screen.  I could specify a tree and scan for repositories and add ones that were already cloned, but just not configured in GitHub desktop.

**Comment by j-f1** [comment]
@greggwon You can drag-and-drop your repository directories onto the GitHub Desktop window to add them all at once.

**Comment by shiftkey** [comment]
@greggwon 

> Some are, some are not.  I just need the functionality that was there before.  I could specify a base branch name, and then either merge from it, or look at the two branch depictions to understand what commits were different between them.

I think this will be recovered when we get to #2639 as that doesn't rely on it being a GitHub repository. Please look over the current mockups in https://github.com/desktop/desktop/issues/2639#issuecomment-333621771 and add your feedback to that issue.

> The interface I am looking for used to be under the options screen. I could specify a tree and scan for repositories and add ones that were already cloned, but just not configured in GitHub desktop.

This was a Windows-only feature and hasn't been brought across to the Electron app. We're tracking that in #1574.

**Comment by shiftkey** [comment]
Closing this out as I believe this feedback is captured in existing issues.
