### ISSUE TITLE
Unable to push, because "find: explorer.exe: no such file or directory"

### ISSUE THREAD

**Issue by Mrkvozrout** [desktop/desktop#3604]
I experience the same behavior as in #3208 

The app worked well for a while, but suddenly when pushing, windows explorer is being opened and the action is never completed.

Status tells `find: 'explorer.exe': No such file or directory`.

App version: 1.0.9
OS: Windows 10 64 bit
Git version: 2.10 (something) windows
Repository: https://github.com/Mrkvozrout/ts100

Did not help:

- update to latest 1.0.10
- update git to 2.15.1.windows.2
- remove repository from app and readd it again
- remove .git/hook folder with its content

`git push` from command line works fine.

under .git/hooks I have:
![obrazek](https://user-images.githubusercontent.com/6730275/33965934-01b888ae-e05e-11e7-84da-4cc5c3f3d4be.png)

Log for actions - start app, create new branch, push:
```
2017-12-13T22:34:20.926Z - info: [ui] [AppStore] loading 1 repositories from store
2017-12-13T22:34:20.930Z - info: [ui] [AppStore] found account: Mrkvozrout
2017-12-13T22:34:21.964Z - info: [ui] launching: 1.0.10 (Windows 10.0.16299)
2017-12-13T22:34:31.400Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: ts100 - Mrkvozrout (has token)
2017-12-13T22:34:34.779Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: ts100 - Mrkvozrout (has token)
```

For new empty branch or new branch with commited new file and cmd commands...
```
git --version
set GIT_TRACE=1
set GIT_CURL_VERBOSE=1
git push origin master --progress
```

...I get:
```
git version 2.15.1.windows.2
set GIT_TRACE=1
set GIT_CURL_VERBOSE=1
git push origin master --progress
Everything up-to-date
```
^ Strange, earlier I was able to push changes. No file or other details generated.

```
For ` git config -l --show-origin` I get:
file:"C:\\ProgramData/Git/config"       core.symlinks=false
file:"C:\\ProgramData/Git/config"       core.autocrlf=true
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       diff.astextplain.textconv=astextplain
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    http.sslbackend=openssl
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    diff.astextplain.textconv=astextplain
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    credential.helper=manager
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    core.editor='C:\Program Files (x86)\Notepad++\notepad++.exe' -multiInst -notabbar -nosession -noPlugin
file:C:/Users/Tron/.gitconfig   gui.recentrepo=D:/Workspace/Java/doxia-sitetools-git
file:C:/Users/Tron/.gitconfig   user.name=M
file:C:/Users/Tron/.gitconfig   user.email=M@email.cz
file:C:/Users/Tron/.gitconfig   filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/Tron/.gitconfig   filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/Tron/.gitconfig   filter.lfs.process=git-lfs filter-process
file:C:/Users/Tron/.gitconfig   filter.lfs.required=true
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.symlinks=false
file:.git/config        core.ignorecase=true
file:.git/config        submodule.active=.
file:.git/config        remote.origin.url=https://github.com/Mrkvozrout/ts100.git
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.master.remote=origin
file:.git/config        branch.master.merge=refs/heads/master
file:.git/config        remote.upstream.url=https://github.com/Ralim/ts100.git
file:.git/config        remote.upstream.fetch=+refs/heads/*:refs/remotes/upstream/*
file:.git/config        branch.translation-czech-cs-cz.remote=origin
file:.git/config        branch.translation-czech-cs-cz.merge=refs/heads/translation-czech-cs-cz
file:.git/config        branch.settings-two-lines.remote=origin
file:.git/config        branch.settings-two-lines.merge=refs/heads/settings-two-lines
file:.git/config        branch.translation-czech-double-line.remote=origin
file:.git/config        branch.translation-czech-double-line.merge=refs/heads/translation-czech-double-line
```

I do not hav LFS:
```
$ git lfs track
git: 'lfs' is not a git command. See 'git --help'.
```

Let me know if you need anything else or what should I try.

**Comment by Mrkvozrout** [comment]
@shiftkey I noticed for a few miliseconds there is another error displayed. The button status sequence is following:

- `Publish this branch to GitHub` - before clicking
![obrazek](https://user-images.githubusercontent.com/6730275/34058521-9b8f39c2-e1db-11e7-9f73-a07831c4b10c.png)
- `Hang on...` - after clicking, lasts few seconds
![obrazek](https://user-images.githubusercontent.com/6730275/34058556-b1f35400-e1db-11e7-9a3d-8059d374b2ca.png)
- `find: 'SoundMixer.exe': No such file or directory` - blinks for few miliseconds, just as long to be able to register it
![obrazek](https://user-images.githubusercontent.com/6730275/34058578-c9b96642-e1db-11e7-8922-50026139af32.png)
- `find: 'explorer.exe': No such file or directory` - final button state, lasts forever
![obrazek](https://user-images.githubusercontent.com/6730275/34058588-d9217624-e1db-11e7-8115-f69af2826878.png)

**Comment by Mrkvozrout** [comment]
@shiftkey I noticed for a few miliseconds there is another error displayed. The button status sequence is following:

- `Publish this branch to GitHub` - before clicking
![obrazek](https://user-images.githubusercontent.com/6730275/34058521-9b8f39c2-e1db-11e7-9f73-a07831c4b10c.png)
- `Hang on...` - after clicking, lasts few seconds
![obrazek](https://user-images.githubusercontent.com/6730275/34058556-b1f35400-e1db-11e7-9a3d-8059d374b2ca.png)
- `find: 'SoundMixer.exe': No such file or directory` - blinks for few miliseconds, just as long to be able to register it
![obrazek](https://user-images.githubusercontent.com/6730275/34058578-c9b96642-e1db-11e7-8922-50026139af32.png)
- `find: 'explorer.exe': No such file or directory` - final button state, lasts forever
![obrazek](https://user-images.githubusercontent.com/6730275/34058588-d9217624-e1db-11e7-8115-f69af2826878.png)

**Comment by Mrkvozrout** [comment]
Also after each of this unsuccessful push, there is one `Sound Mixing Utility` and one of `Git for Windows` or `GitHubDesktop.exe` processes left hanging:

![obrazek](https://user-images.githubusercontent.com/6730275/34060102-8f47b3ea-e1e2-11e7-9783-b1b20915d5a7.png)

![obrazek](https://user-images.githubusercontent.com/6730275/34060139-a91936c2-e1e2-11e7-9556-40301c4478d7.png)

**Comment by shiftkey** [comment]
@Mrkvozrout okay, now I'm really puzzled.

Can you click on `Sound Mixing Utility` and select "Open file location" - I want to know where this program is coming from, as I can't seem to find it on my relatively-boring Windows 10 install:

```shellsession
Microsoft Windows [Version 10.0.16299.125]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\shiftkey>cmd /c ver

Microsoft Windows [Version 10.0.16299.125]

C:\Users\shiftkey>cd C:\

C:\>dir SoundMixer.exe /s /p
 Volume in drive C has no label.
 Volume Serial Number is 8007-5E51
File Not Found
```

**Comment by Mrkvozrout** [comment]
@shiftkey `C:\Users\<User>\AppData\Roaming\Microsoft\SoundMixer\SoundMixer.exe`

**Comment by Mrkvozrout** [comment]
@shiftkey So I investigated furthed this SoundMixer executable and it seems to be a mining malware.

I took the steps from [here](https://social.technet.microsoft.com/Forums/windows/en-US/9fb738ab-2f3d-4a07-ac8a-173d63a47f87/cmd-not-working-due-to-an-error-the-error-occurs-on-practically-everything?forum=win10itprogeneral) to remove it and the pushing works again - so no problem with the app in the end. The malware tried to run the mining code each time `cmd` was started.

Thanks for your time and for the question about SoundMixer ;)

**Comment by shiftkey** [comment]
@Mrkvozrout thanks for the extra investigation! I'm glad you were able to work around it!

**Comment by BrendanLindsay** [comment]
Wow, i had the same malware, thanks for letting me know how to get rid of it @Mrkvozrout

**Comment by PalavaNet** [comment]
Observed again March/April 2020.

This time with "FirewallModule" and "FirewallModule.exe" instead of "SoundMixer" and "SoundMixer.exe". The same instructions [here](https://social.technet.microsoft.com/Forums/windows/en-US/9fb738ab-2f3d-4a07-ac8a-173d63a47f87/cmd-not-working-due-to-an-error-the-error-occurs-on-practically-everything?forum=win10itprogeneral) fixed the issue

**Comment by Rumir125** [comment]
Thank you so much!!

**Comment by adarsh-bankopen** [comment]
I am having this in MacOS (Version 12.6). Any idea how to rectify this?

<img width="247" alt="image" src="https://user-images.githubusercontent.com/79446266/200988513-ac3635e0-8e62-465c-9fda-2baad683776f.png">
