### ISSUE TITLE
Keyboard actions become stuck in Pull Request

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3607]
When using `up` and `down` arrows in Pull Request list, they become stuck on whatever pull request is active and user is unable to key moving up/down the list.

Repro:
- Click into filter in PR list
- Press up/down arrow key
- Current PR highlighted will turn blue (as expected)
- try to continue moving up/down with arrow keys, user is stuck

related to #3499 

1.0.12-beta0, mac

**Comment by shiftkey** [comment]
There's a whole bunch of other corner cases here that don't seem to work correctly right now:

 - if you're on `master` or a branch without a PR, select the filter text and then press `ArrowDown`, your cursor leaves the filter textbox but the list doesn't focus on the first item as expected
 - once it ends up in this unknown state, things like mouse clicks aren't handled - you need to switch to branches and then back to pull requests to reset it
