### ISSUE TITLE
Add Pull Request badge number in nav bar if no CI status

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3608]
If CI is turned on, then any previous Pull Requests without CI status are missing the badge number in the top nav bar when the user selects the branch or pull request.

<img width="482" alt="screen shot 2017-12-14 at 9 24 03 am" src="https://user-images.githubusercontent.com/14828183/34005738-c3865612-e0b0-11e7-9954-a2435c5f62c7.png">

I have Travis CI running .... for testing purposes.

1.0.12-beta0, mac

**Comment by iAmWillShepherd** [comment]
After going through our code, I'm not sure we ever presented a badge when on a branch with no status checks.

https://github.com/desktop/desktop/blob/23c470e8ec00da82bdc0e0653b8cbf72046ef00a/app/src/ui/branches/pull-request-badge.tsx#L18-L32

This issue should therefore be labelled an enhancement.
