### ISSUE TITLE
Pull requests get wiped when switching to a repository?

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#3609]
1. Switch to repository A.
1. Open the pull requests list.
1. Note that PRs are loading.
1. Wait for them to finish loading.
1. Switch to a different repository.
1. Switch back to repository A.
1. Open the pull requests list.
1. Note that PRs are loading again.

We _should_ have them cached already from opening the repository the first time. So we shouldn't need to load them again.

**Comment by shiftkey** [comment]
I've not been able to trigger this while testing `1.0.12-beta1` on macOS - are there any extra steps or potential race conditions I'm overlooking?

**Comment by iAmWillShepherd** [comment]
> If you look at the PRs for the different repository before switching back, repository A is fine.
If you don't look at the PRs for the different repository, you encounter the bug

This is good to know, but also sounds like a huge pain to find.

**Comment by shiftkey** [comment]
I've not been able to reproduce this on `master` in the hopes of catching what feels like a race condition. I'll leave this to someone else to dig into.

**Comment by shiftkey** [comment]
@desktop/core unless someone else can reproduce this consistently, I think we should move this into the `1.1.x` milestone...

**Comment by iAmWillShepherd** [comment]
I've made some changes on [this branch](https://github.com/desktop/desktop/compare/load-prs-once) to make identifying the issue easier (at least for me). Going through and cleaning up actually uncovered some opportunities 😏 

Still working on this though.
