### ISSUE TITLE
1111111

### ISSUE THREAD

**Issue by 111333** [desktop/desktop#3612]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by 111333** [comment]
12232133

**Comment by Naginata7168** [comment]
Why did shiftkey close this issue? I spent the last hour answering these questions and you just lost ALL of my work!
