### ISSUE TITLE
error 500 when attempting to download github desktop

### ISSUE THREAD

**Issue by jennevdmeer** [desktop/desktop#3613]
download button on https://desktop.github.com/ returns a 500 response (same for mac and msi links).

**Comment by jennevdmeer** [comment]
works again

**Comment by antn** [comment]
Sorry about that! Everything should be back to normal now. Please let us know if you’re still running into any errors.

**Comment by qubidt** [comment]
It's back down! I'm panicking and I don't have my towel!

**Comment by SofianeOuaari** [comment]
I'm having the 500 error when trying to install the GitHub Desktop.

**Comment by antn** [comment]
@SofianeOuaari sorry about that! Can you try again? It should be fixed. 😄
