### ISSUE TITLE
Unable to Delete local branches because of new "open pull request" dialog.

### ISSUE THREAD

**Issue by sdwebguy** [desktop/desktop#3615]
### Description

Unable to delete a local branch because a dialog box saying I have an open pull request for that branch. There is no open pull request.

### Version

**GitHub Desktop version:** 1.0.11
**OS version:** Windows 10

### Steps to Reproduce

1. Create a local branch. Make code changes. Push branch to origin.
2. In github, open a PR for the branch. A few minutes later, merge the PR into master.
3. In application, try to delete the branch (Branch / Delete...), get message saying I can't.

To "fix it", I need to switch to master, fetch from origin, then switch back to the branch and delete it.

This started with the latest release and is a pain now to have to switch back and forth.

**Comment by tierninho** [comment]
@sdwebguy I can reproduce this, but I was successful in deleting the branch in Desktop after waiting a minute or two for Desktop to catch up. 

Are you still unable to delete the branch in Desktop?

**Comment by sdwebguy** [comment]
@tierninho This is new behavior. I usually don't have the time to wait for Desktop to do its fetch whenever it will do it. After merging the PR and handling the paperwork in our processes, I need to move to the next branch, and now I have to double switch branches just to keep going.

Perhaps it is a symptom of not having a way to manually trigger the fetch/prune, etc. What makes it worse is what actions I have. Here is really what it looks like:

1. Create a local branch. Make code changes. Push branch to origin.
2. In github, open a PR for the branch. A few minutes later, merge the PR into master and delete the branch in origin.
3. In desktop, I am still on the branch, but now the only action I have is to "push to origin" even though I have no changes to make. So Desktop knows something is different, but for some reason defaults to me pushing the branch (now deleted in origin) instead of allowing me to delete it locally like it did before.

**Comment by sdwebguy** [comment]
@tierninho 

I just did it again, and it has been 9 minutes and I still cant delete locally until I switch. My Desktop looks like this:

![image](https://user-images.githubusercontent.com/945871/34053529-009492f0-e17c-11e7-9144-b4d39aa9ceba.png)

No changes to make, no branch in origin (it was deleted), only option is to Publish Branch.

**Comment by joshaber** [comment]
Yeah this does seem problematic. Thanks for bringing it to our attention @sdwebguy!

Maybe the dialog should be advisory, instead of totally blocking the user. @desktop/core what say you?

**Comment by j-f1** [comment]
How about double-checking if the PR is open before showing the dialog box?

**Comment by joshaber** [comment]
We could, but I get nervous about introducing a network call into what _should_ be a local operation.

**Comment by sdwebguy** [comment]
@joshaber I guess I dont see why I shouldn't be able to delete a local branch even if there is an open PR for it.

**Comment by joshaber** [comment]
Yeah, we should let you always delete the local branch.

I think the goal was to prevent deleting the remote branch, similar to how GitHub.com behaves:

<img width="380" alt="screen shot 2017-12-15 at 11 57 33 am" src="https://user-images.githubusercontent.com/13760/34058261-3740e656-e18f-11e7-8355-34d950749479.png">

**Comment by joshaber** [comment]
And the interesting thing is that based on your screenshot we already know it's a local branch, which is why we're showing "Publish Branch" instead of fetch. So I think that's the easy fix here.

**Comment by joshaber** [comment]
@iAmWillShepherd, @nerdneha and I talked through this. We're thinking in the case where a branch has an open pull request, we'll display a different dialog than our current `Delete Branch` dialog. It'll say that there's an open PR, provide a link to it, and allow the user to delete the local branch.

We don't want to let the user delete the remote branch out from under an open PR.

**Comment by Naginata7168** [comment]
May I ask if his screen shot contained my dialog? I would appreciate a copy of it if possible. I really would like it if you could retrieve my full comment. I appreciate any assistance in this matter.
Thanks so Much, TW

**Comment by sdwebguy** [comment]
I dont understand any of what you just said.

**Comment by egoroof** [comment]
Have the same problem. I want to delete local branch even it has open PR. Why not just show same dialog as always but checkbox about remote removing would be disabled an it'll have title description why.

**Comment by lundeen-bryan** [comment]
Was there a resolution to this? I'm having the exact same problem.

**Comment by mochadwi** [comment]
having the same problem, still cannot delete branch (even the PR is already closed)

**Comment by PPL-CCPTC-Rekrutacja** [comment]
![image](https://user-images.githubusercontent.com/62420118/100985605-7a441180-354c-11eb-8744-3633356f5593.png)
same problem

**Comment by santoshD93** [comment]
same issue

**Comment by santoshD93** [comment]
@shiftkey  I think this Issue needs to be re-opened.

**Comment by JPercival** [comment]
Here's a workaround:

```bash
git push origin --delete <branchname>
```

**Comment by NatnaelSisay** [comment]
This worked, Thanks!
