### ISSUE TITLE
Autodetect moved repositories on macOS with “Bookmarks”

### ISSUE THREAD

**Issue by j-f1** [desktop/desktop#3622]
macOS supports [Bookmarks](https://developer.apple.com/documentation/foundation/nsurl/1408344-bookmarkdatawithcontentsofurl?language=objc), blobs of opaque data that allow you to find the path to a file or directory if it’s been changed.

This code snippet uses [`nodobjc`](https://github.com/TooTallNate/NodObjC) to access those NSURL APIs to obtain a `Buffer` with the bookmark, then get back the path (as a string).

```ts
const $ = require('nodobjc')

$.framework('Foundation')

// semiautomatic memory management!
function getPool() {
  const pool = $.NSAutoreleasePool('alloc')('init')
  return () => pool('drain')
}

const drain = getPool()

// get bookmark
const str = $(pathToRepo)
const url = $.NSURL('fileURLWithPath', str)
const serializeErrorRef = $.alloc($.NSError).ref()
// 📖 https://developer.apple.com/documentation/foundation/nsurl/1408344-bookmarkdatawithcontentsofurl?language=objc
const data = $.NSURL('bookmarkDataWithContentsOfURL', url,
                     'error', serializeErrorRef)
if (!data) {
  const err = serializeErrorRef.deref()
  throw err
}
const buf = data('bytes')

// resolve bookmark
const staleRef = // ??? get `BOOL *` instance
const deserializeErrorRef = $.alloc($.NSError).ref()
// 📖 https://developer.apple.com/documentation/foundation/nsurl/1572035-urlbyresolvingbookmarkdata?language=objc
const newURL = $.NSURL('URLByResolvingBookmarkData', $(buf),
                         'options', 0,
                         'relativeToURL', null,
                         'bookmarkDataIsStale', staleRef,
                         'error', deserializeErrorRef)
if (!newURL) {
  const err = deserializeErrorRef.deref()
  throw err
}
// 📖 https://developer.apple.com/documentation/foundation/nsurl/1412925-filesystemrepresentation?language=objc
const path = newURL('fileSystemRepresentation')
```

Note: the NodObjC library doesn’t have T Y P E S, and they’d be nontrivial to write.

**Comment by niik** [comment]
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.
