### ISSUE TITLE
It keeps saying `The user name or passphrase you entered is not correct.`

### ISSUE THREAD

**Issue by tom10271** [desktop/desktop#3625]
### Description

I have reset my password and git cli and SourceTree both work.

### Version

**GitHub Desktop version:** 1.0.11

**OS version:** macOS 10.12.6 (16G1036)

### Steps to Reproduce

1. Last Friday it is still working and once I start working again today this application keeps saying login failed. 

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** I don't know what is going on. I can't tell how to reproduce it

### Logs

```
fatal: Authentication failed for 'https://github.com/101medialab/HypebeastStore.git/'

(The error was parsed as 3: Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open preferences and verify that you're signed in with an account that has permission to access this repository.)
2017-12-18T03:42:52.250Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.825s)
2017-12-18T03:42:52.251Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/101medialab/HypebeastStore.git/'

(The error was parsed as 3: Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open preferences and verify that you're signed in with an account that has permission to access this repository.)
2017-12-18T03:42:58.963Z - info: [ui] storing generic credentials for 'github.com' and 'tom10271'
2017-12-18T03:42:58.990Z - error: [ui] Error saving generic git credentials: tom10271@github.com
Error: The user name or passphrase you entered is not correct.
2017-12-18T03:43:00.852Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.838s)
2017-12-18T03:43:00.854Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/101medialab/HypebeastStore.git/'

(The error was parsed as 3: Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open preferences and verify that you're signed in with an account that has permission to access this repository.)
2017-12-18T03:43:23.382Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.801s)
2017-12-18T03:43:23.383Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/101medialab/HypebeastStore.git/'

(The error was parsed as 3: Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open preferences and verify that you're signed in with an account that has permission to access this repository.)
2017-12-18T03:43:31.069Z - info: [ui] storing generic credentials for 'github.com' and 'tom10271'
2017-12-18T03:43:31.098Z - error: [ui] Error saving generic git credentials: tom10271@github.com
Error: The user name or passphrase you entered is not correct.
2017-12-18T03:43:32.856Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.746s)
2017-12-18T03:43:32.856Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/101medialab/HypebeastStore.git/'

(The error was parsed as 3: Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open preferences and verify that you're signed in with an account that has permission to access this repository.)
```

**Comment by shiftkey** [comment]
@tom10271 we think this is related to Keychain access due to some sort of macOS update:

> Try opening **Keychain Access.app**. Right-click on the `login` keychain and try locking it and then unlocking it again.

**Comment by tom10271** [comment]
It works. Thanks

**Comment by vitoriacalil** [comment]
I was facing the same problem, and after going through Keychain it worked! Thanks

**Comment by 8solo** [comment]
OK, Thanks!

**Comment by neotran85** [comment]
Thank you, @shiftkey you made my day :D

**Comment by vicespi23** [comment]
> @tom10271 we think this is related to Keychain access due to some sort of macOS update:
> 
> > Try opening **Keychain Access.app**. Right-click on the `login` keychain and try locking it and then unlocking it again.

It worked!!!!!!!!!!!!!!!!!!!!!!!!!!! THANK YOU!

**Comment by saamerm** [comment]
> @tom10271 we think this is related to Keychain access due to some sort of macOS update:
> 
> > Try opening **Keychain Access.app**. Right-click on the `login` keychain and try locking it and then unlocking it again.

Using Keychain Access on MacOS Mojave, I was trying to create a Certificate Signing Request (CSR) for an iOS Development Certificate, and I was getting the same error `The user name or passphrase you entered is not correct.`
This solved that issue as well, strangely.

**Comment by coffeefrominternet** [comment]
awesome

**Comment by jx932179932** [comment]
解决了，点赞！

**Comment by cao2358** [comment]
nice

**Comment by tom10271** [comment]
Please do not reply `nice`,  `awesome` whatever again

**Comment by dhingrad** [comment]
Yay Worked !!!

**Comment by ShreyashPromact** [comment]
How to do this for the Virtual machine? Is there any command for the same?

**Comment by soypaduano** [comment]
YES! All day suffering the mysql workbench hassle haha thanks!

**Comment by wanyukang** [comment]
ur saving my life

**Comment by ndunk28** [comment]
Yeayyyyy!!!

**Comment by reggiev** [comment]
Thanks! But this is weird.

**Comment by aminovicnouri** [comment]
> > @tom10271 we think this is related to Keychain access due to some sort of macOS update:
> > > Try opening **Keychain Access.app**. Right-click on the `login` keychain and try locking it and then unlocking it again.
> 
> It worked!!!!!!!!!!!!!!!!!!!!!!!!!!! THANK YOU!
it worked with me too !!!!!!!!!! thank you

**Comment by tjnurmin** [comment]
Couldn't spot the `login` keychain anywhere but finally found it under `File > Lock Keychain "login"` in Keychain Access.

**Comment by jijiechen** [comment]
I solved it by a logout and login the macOS session.
It might because my machine is a work machine and is managed by the organization using Kandji. I recently changed my AD password, and the new password is synced to my mac, the KeyChain Access app is blocking me from locking/unlocking the vaults. 
By re-login using my new password, the issue is gone automatically.
