### ISSUE TITLE
Renaming a branch with an existing Pull Request 

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3628]
I had an existing branch with a pull request and decided to rename the branch, thus creating two branches. I also have two Pull Requests tied to the original branch.

It seems that selecting either of the two PRs leads back to the original branch, but the badge number won't update.

See pics for more details:
<img width="365" alt="screen shot 2017-12-18 at 9 14 10 am" src="https://user-images.githubusercontent.com/14828183/34119023-929f38a2-e3d5-11e7-92c3-9fd7cf537e78.png">

<img width="760" alt="screen shot 2017-12-18 at 9 22 03 am" src="https://user-images.githubusercontent.com/14828183/34119018-92174bb8-e3d5-11e7-9a10-78aad364b61d.png">
<img width="760" alt="screen shot 2017-12-18 at 9 21 51 am" src="https://user-images.githubusercontent.com/14828183/34119020-9235a4b4-e3d5-11e7-9c68-d16a3b103516.png">
<img width="356" alt="screen shot 2017-12-18 at 9 13 40 am" src="https://user-images.githubusercontent.com/14828183/34119021-92572ef4-e3d5-11e7-8786-20b9cbe17bbd.png">
<img width="367" alt="screen shot 2017-12-18 at 9 13 57 am" src="https://user-images.githubusercontent.com/14828183/34119022-927c0cec-e3d5-11e7-8ff6-f9f00f6c8077.png">

1.0.12-beta0, mac

**Comment by billygriffin** [comment]
I'm not sure this actually happens in real life, but I'd love for @niik to consider whether it's worth consideration as part of https://github.com/desktop/desktop/issues/6982, so I'm going to close this and add a bit more context to that issue for him to consider.
