### ISSUE TITLE
Reverting `Update from Default Branch` is problematic

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3630]
If you accidentally hit the `Update from Default Branch` there is a chance that multiple commits are placed in the queue to be pushed. I suggest we have a `undo all` button, as going through the 200+ commits and undoing them results in wasted time (if you were to go this route).

Secondly, hitting `undo` too fast results in a git lock dialogue:

<img width="599" alt="screen shot 2017-12-18 at 11 55 15 am" src="https://user-images.githubusercontent.com/14828183/34125520-556fbf5e-e3eb-11e7-947c-b5c5de199719.png">

Lastly, the menu items are not greyed out when this message is active. I can still access and click on the menu items but nothing happens... as intended.

<img width="517" alt="screen shot 2017-12-18 at 12 03 42 pm" src="https://user-images.githubusercontent.com/14828183/34125576-8bd5b238-e3eb-11e7-8b81-0f0b2eaf8609.png">

Build v1.0.12-beta0. mac

**Comment by shiftkey** [comment]
@tierninho can we the second two items out into distinct issues? They should be handled separately to the original enhancement:

 - The first one needs some design input and thought about UX
 - The second one seems to be something we should fix independent of this. [`undoCommit`](https://github.com/desktop/desktop/blob/0a034d7b75dee14d3025c83be0a9769ef621e53e/app/src/lib/stores/git-store.ts#L492-L514) is wrapped in a promise, but maybe we're not surfacing some state to ensure it can't occur concurrently.
 - Re: the third one - I'm not sure we handle the error dialogs in the same way as others when it comes to disabling the menu, so it's probably A Bug™

**Comment by tierninho** [comment]
Closing this as it has not come up enough times to be validated as a real problem.
