### ISSUE TITLE
The panel with the list of changes for a commit is too small on 4K screens and can't be resized

### ISSUE THREAD

**Issue by Sergio0694** [desktop/desktop#3632]
### Description

The panel with the list of changes for the selected commit (the second one from the left) has a fixed maximum width that's just too small for 4K displays with a small enough scaling, so right now there's a lot of wasted space and filenames with a long path end up getting trimmed.

It'd be great to just be able to resize each panel as much as we like, or at least, to have a higher maximum width for each panel when using the app on a high-resolution screen.

### Version

**GitHub Desktop version:** 1.10.11

**OS version:** Windows 10 Pro Fall Creators Update (build 16299.125)

### Steps to Reproduce

1. Open the app on a 4K screen (or any high-resolution screen)
1. Open a repository, choose the "History" section and select a commit
1. Try to expand the second panel, it gets stuck past a certain threshold

**Expected behavior:** I'd expect the panel to be expanded as much as I'd like

**Actual behavior:** As stated above, the panel gets stuck pretty soon

**Screen**: as you can see I have quite some free space on the right, but I can't use part of it by expanding the second panel some more

![image](https://user-images.githubusercontent.com/10199417/34131258-2aa3ae74-e44b-11e7-8307-3afdaf95aa00.png)

**Comment by joshaber** [comment]
It looks like we're already tracking this in https://github.com/desktop/desktop/issues/2745. Feel free to follow along over there!
