### ISSUE TITLE
Protected branch restrictions ignored when merging from desktop app

### ISSUE THREAD

**Issue by brianlovin** [desktop/desktop#3633]
### Description

I am able to merge code directly into `master` from the desktop tool, despite `master` being a protected branch in our repo that requires both a code review and passing ci tests.

### Version

**GitHub Desktop version:** 1.0.11
**OS version:** MacOS

### Steps to Reproduce

1. Create a branch that tracks an upstream protected branch
2. From the GitHub desktop UI, push to origin
3. Branch bypasses protections and merges into upstream branch

**Expected behavior:** Fail, or warn about protected branch restrictions

**Actual behavior:** Merges branch automatically into protected upstream branch

**Reproduces how often:** 100%

### Logs
NA

#### Additional Information
I have admin permissions in the repo, however in the website UI I am forced to opt-in to override branch protections in order by bypass them with privilege. From the desktop application, I am not warned or restricted from merging into protected branches, regardless of CI states or reviewer status.

**Comment by brianlovin** [comment]
1. Create test branch
<img width="1023" alt="screenshot 2017-12-18 15 14 23" src="https://user-images.githubusercontent.com/1923260/34132826-84a57a6e-e406-11e7-9455-b33573a55e1f.png">

2. Click push to origin
<img width="724" alt="screenshot 2017-12-18 15 14 37" src="https://user-images.githubusercontent.com/1923260/34132828-8693b296-e406-11e7-8674-b3f13d58c146.png">

3. Branch is merged, bypassing restrictions
<img width="1010" alt="screenshot 2017-12-18 15 14 54" src="https://user-images.githubusercontent.com/1923260/34132833-88b1bc3a-e406-11e7-8337-2a39060edbc5.png">

**Comment by shiftkey** [comment]
@brianlovin thanks for the details.

We don't currently track branch protections in the app - we could get this from the GitHub API -  so we won't stop you from doing the merge locally. But I'm curious why the server doesn't reject the push either - could this be related to you being an admin of the repository? 🤔

**Comment by brianlovin** [comment]
@shiftkey yup, most likely because I'm an admin of the repo I was able to bypass it. So I suppose this issue is less of a bug and more of a UI/feature request to respect branch protections in-app. Hope that helps :)

**Comment by shiftkey** [comment]
@brianlovin yup, that totally makes sense 👍

**Comment by shiftkey** [comment]
This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by shiftkey** [comment]
@workobots reported in #4444 that even committing to `master` may be covered by branch protections, and while pushes are blocked this is a chance for the app to catch and warn users at commit time and guide them to the ideal workflow.

**Comment by billygriffin** [comment]
Thanks @brianlovin! Sorry for the delay in dealing with this - we're super interested in branch protections more generally and doing some research on how it's used in various orgs so we can figure out a broader solution here. We'll be tracking that work in #1021 so I'm going to remove `future-proposal` here. Thanks again!
