### ISSUE TITLE
How to compile and bundle a more compact git binary

### ISSUE THREAD

**Issue by hbons** [desktop/desktop#3639]
This is not really an issue, but more a request for advice. I didn't see any other channels for this question, so I hope you don't mind I'm putting it here.

Like GitHub desktop, my [project](https://github.com/hbons/SparkleShare/) bundles git on macOS. I'm trying to automate this process, but whenever I compile git from source the binaries end up being around 400 MB altogether; too large to bundle. Inspecting your Desktop .app shows a much more manageable git bundle of around 30 MB. The only way I can get to the same size is to download a binary release from the official git website, install, and cherry-pick the needed bits, but it's a tedious process.

So I was wondering how you're compiling git to bundle it for your releases and if you're willing to share this knowledge. :)

Thanks!

**Comment by j-f1** [comment]
Thanks for your interest @hbons!

Check out the [dugite](https://github.com/desktop/dugite) and [dugite-native](https://github.com/desktop/dugite-native) repos. This is where the embedded git we use comes from.

**Comment by hbons** [comment]
That's great! Thanks for the quick reply. :)
