### ISSUE TITLE
If authentication fails, Github Desktop requires restart

### ISSUE THREAD

**Issue by zapjonny** [desktop/desktop#3641]
### Description

If authentication fails, Github Desktop requires restart.
Normally when computer is started outside (cafe etc) and I don't have setup wifi access yet but start Github Desktop before that, GD onwards always fails to authenticate to github repositories. I basically need to connect to wifi/network, and THEN start Github Desktop to have it fixed. Did you only test this tool in a safe office environment with stable network conditions?
To me, this happens fairly often.

### Version

GitHub Desktop version  1.0.11 ()

OS version: macOS 10.13.2

### Steps to Reproduce

1. Launch Github Desktop.
2. Connect to WiFi (or other internet network like cable)
3. Try to sync with a previously setup github repository.

**Expected behavior:** In step 3 syncing should work properly

**Actual behavior:**

![screen shot 2017-12-20 at 11 28 17](https://user-images.githubusercontent.com/20237481/34188278-e85ac2b2-e578-11e7-8bda-8cd9c2064e33.png)

**Reproduces how often:** 

100%

### Logs

[2017-12-20.desktop.production.log](https://github.com/desktop/desktop/files/1573966/2017-12-20.desktop.production.log)

#### Additional Information

As mentioned above, if I quit and restart Github Desktop everything works.

**Comment by niik** [comment]
@zapjonny Thank you so much for reporting this. I was able to reproduce this and a fix for the issue has been merged as part of #3649 and will make it into the next stable release which should come out after the holidays.

**Comment by shankar2101** [comment]
give new disktop level

**Comment by shankar2101** [comment]
how to create code .
