### ISSUE TITLE
Local branch cannot be published to github

### ISSUE THREAD

**Issue by pinum314** [desktop/desktop#3643]
![githuberror](https://user-images.githubusercontent.com/4327042/34188353-d30305f2-e4ea-11e7-8e8c-84888e862478.png)

Description
I created a new branch in a private repository and made some updates. I was able to commit the files locally, but when I tried publishing to github I received an error message stating "The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed." 

Version
GitHub Desktop version: 1.0.11

OS version: Windows 10 Home, 64 bit

Steps to Reproduce

1. Open an existing private repository. 
2. Create a new branch
3. Make some changes
4. Commit those changes
5. Push "Publish Branch"

Expected behavior: Syncs, and files are available for collaborators via github repository. 

Actual behavior: Error message stating "The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed." and no uploaded files. 

Reproduces how often: 100%

Logs

Additional Information

**Comment by shiftkey** [comment]
@pinum314 thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide more information to help troubleshoot.

**Comment by pinum314** [comment]
Here's the log file (with filenames changed). 
Thanks!
[edited_log.txt](https://github.com/desktop/desktop/files/1574053/edited_log.txt)

**Comment by shiftkey** [comment]
I don't see a corresponding `git push` operation related to publishing a branch, but these errors here suggest something networking-related occurred on your machine at the time:

```
2017-12-20T03:21:27.673Z - warn: [ui] fetchPullRequests: failed for repository dashrobotics/Project-2.0-firmware
TypeError: Failed to fetch
2017-12-20T03:21:27.676Z - warn: [ui] Error refreshing pull requests for 'Project-2.0-firmware'
TypeError: Failed to fetch
2017-12-20T03:21:28.415Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.664s)
2017-12-20T03:21:28.432Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
fatal: unable to access 'https://github.com/DashRobotics/Project-2.0-firmware.git/': Could not resolve host: github.com
2017-12-20T03:21:30.128Z - warn: [ui] getFetchPollInterval: failed for dashrobotics/Project-2.0-firmware
TypeError: Failed to fetch
```

**Comment by pinum314** [comment]
Problem was that it was a private repository I had read only access to. Got access updated and now it works fine.
