### ISSUE TITLE
Discarding the revision of a submodule destroys the whole submodule

### ISSUE THREAD

**Issue by mhalttu** [desktop/desktop#3647]
### Description

When you have a repository in a GitHub that contains a submodule and you discard the revision change of the submodule, the whole submodule is deleted.

### Version

**GitHub Desktop version:** 1.0.11

**OS version:** OS X 10.12.6

### Steps to Reproduce

1. Checkout a module that includes a submodule
1. Go to the submodule and change the branch
1. Observe the change in GitHub Desktop
1. Discard the change

**Expected behavior:** The submodule reference points back to the original branch and includes the files in that branch

**Actual behavior:** The whole submodule is completely destroyed. The folder is empty.

**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
@mhalttu thanks for the report! This is reproducible on my end, and is probably because we don't special-case submodules when we're discarding changes...
