### ISSUE TITLE
Quick Repo Switcher

### ISSUE THREAD

**Issue by rlm95** [desktop/desktop#3648]
### Description

It would be nice if there was a hotkey/shortcut to quickly open up the repository list. Something like control + k to open it and then it would have a search bar to type in the repo you want to switch to. To make this even better the popup window could show any repositories that currently have uncommitted changes and allow you to quickly choose one of those using arrow keys/tabs

### Version

**GitHub Desktop version:** 1.011

**OS version:** Microsoft Windows [Version 10.0.14393]

**Expected behavior:** Press control + k type into search bar what repository i'm looking for and hit enter to switch to that view

**Actual behavior:** currently not a feature

**Comment by niik** [comment]
Hey @rlm95. <kbd>Ctrl</kbd> + <kbd>T</kbd> (<kbd>⌘</kbd> on macOS) should open the repository list for you and pre-select the filter text box. From there you can use the arrow keys to move up/down the repository list.
