### ISSUE TITLE
Get GitHub on 32 Bit?

### ISSUE THREAD

**Issue by codescratchblocks** [desktop/desktop#3655]
**GitHub Desktop version:** [doesn't show]

**OS version:** [Windows 10 (x32) Build 10.0.16299.125]

**Expected behavior:** [install]

**Actual behavior:** [error]

**Reproduces how often:** [every time I run the installer]

![github error](https://user-images.githubusercontent.com/34673672/34246013-aaa30b28-e5e1-11e7-82c7-ddc444fa06f1.PNG)

**Comment by niik** [comment]
@codescratchblocks We don't support 32-bit versions of Windows - see #1214 for the related discussion.

**Comment by Fancy2209** [comment]
Dugite Native Supports X86 since 2018, what happened to the X86 Desktop Release?

**Comment by WaiJade** [comment]
why couldn't i install this version's GitHub Desktop?
