### ISSUE TITLE
Trying to push branch to read only access repo, the error message suggests repo is not found

### ISSUE THREAD

**Issue by bimsonz** [desktop/desktop#3656]
### Description

Trying to push branch to read only access repo, the error message suggests repo is not found rather than informing user of access issue.

### Version

**GitHub Desktop version:** 1.0.11

**OS version:** Microsoft Windows [Version 10.0.16299.125]

### Steps to Reproduce

1. Clone repo you only have read access too
1. Create and try to push new branch (committing is naturally fine)

**Expected behavior:** To be prompted that i dont have access

**Actual behavior:** Informed that repo is no longer available or deleted.

**Comment by niik** [comment]
Hey @bimsonz, could you please post a screenshot of the error dialog? I'm looking through the error messages now and I wonder if this is the message that you're seeing

> Authentication failed. You may not have permission to access the repository or the repository may have been archived.

**Comment by shiftkey** [comment]
Closing as inactive.

@bimsonz if you can share the screenshot of the error dialog we're happy to revisit this.
