### ISSUE TITLE
Desktop Installer

### ISSUE THREAD

**Issue by git4dummies** [desktop/desktop#3659]
Hello. The latest GitHub desktop installer conflicts with the type of workstation that we have which are VM's that refresh after each log off. Do you have or can you please provide an installer that can be installed per machine and not per user to resolve this issue? It could be that the desktop installer has switches or options we are not aware of that could force the method of installation that we need. Please ask for any clarification if I am not clear.

**Comment by shiftkey** [comment]
We provide an MSI that supports installation for all users on a machine, but this has some limitations:

 - clicking the shortcut at `%PROGRAMFILES(x86)\GitHub Desktop Installer\desktop.exe` will install things to `%LOCALAPPDATA%\GitHubDesktop` 
 - some user-specific data is stored at `%APPDATA%\GitHub Desktop` - if that is also removed after logoff then some settings (like tracked repositories) won't be remembered

<img width="747" src="https://user-images.githubusercontent.com/359239/34278303-d462077a-e6f9-11e7-9853-44e0c51cd6ec.png">

There's an open issue to look at improving this, but it's not currently a priority: #1086

**Comment by shiftkey** [comment]
@git4dummies please try out the current MSI, and add your feedback to #1086 if it doesn't satisfy your requirements.
