### ISSUE TITLE
Unable to clone, fetch, or push on GitHub Desktop

### ISSUE THREAD

**Issue by Denestel** [desktop/desktop#3661]
### Description

Hey whats up, so I was trying to use GitHub Desktop to work with my repos, but I keep getting an error like this (when cloning from or publishing to new repos), i dont understand whats wrong it was working fine a few days ago and i havent installed anything new on my computer since, im having this issue on both my laptop and desktop using GitHub Desktop:

Cloning into 'C:\Users\User\Documents\GitHub\Java'...
fatal: unable to access 'https://github.com/Denestel/Java.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.

### Version

**GitHub Desktop version:** 1.0.11

**OS version:** Windows 10 Home

### Steps to Reproduce

1. Select repository
2. Clone repository

**Expected behavior:** Repository cloned and updated

**Actual behavior:** Unknown error (0x80092013)

**Reproduces how often:** every time

### Logs

2017-12-21T20:42:53.537Z - info: [ui] Executing clone: git -c credential.helper= clone --recursive --progress -- https://github.com/Denestel/Java.git C:\Users\User\Documents\GitHub\Java (took 87.647s)
2017-12-21T20:42:53.538Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://github.com/Denestel/Java.git C:\Users\User\Documents\GitHub\Java` exited with an unexpected code: 128.
Cloning into 'C:\Users\User\Documents\GitHub\Java'...
fatal: unable to access 'https://github.com/Denestel/Java.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.

2017-12-21T21:04:48.179Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/Denestel/Java.git - Denestel (has token)
2017-12-21T21:05:44.833Z - info: [ui] Executing clone: git -c credential.helper= clone --recursive --progress -- https://github.com/Denestel/Java.git C:\Users\User\Documents\GitHub\Java (took 56.652s)
2017-12-21T21:05:44.834Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://github.com/Denestel/Java.git C:\Users\User\Documents\GitHub\Java` exited with an unexpected code: 128.
Cloning into 'C:\Users\User\Documents\GitHub\Java'...
fatal: unable to access 'https://github.com/Denestel/Java.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.

**Comment by shiftkey** [comment]
@Denestel thanks for the report! 

The version of Git embedded in Desktop uses the Windows SChannel APIs for validating certificates as part of the HTTPS handshake. We've had various reports of this failing due to other tools being installed alongside, like anti-virus programs, or being behind some proxy servers. 

As a workaround, you can revert to the classic OpenSSL behaviour by opening the repository in a shell and running these two commands. 

```
$ git config --global http.sslBackend "openssl"
$ git config --global http.sslCAInfo [path to .pem file]
```

The PEM file is just a bundle of public certificates to validate - [the PEM file](https://curl.haxx.se/docs/caextract.html) distributed by the cURL team should do the trick.

**Comment by shiftkey** [comment]
We're working on explaining this error better in #3406. Please follow along with that issue.

**Comment by AndyGee** [comment]
Check your "C:\Users\<user>.gitconfig" for proxy configuration, or anything else that might be providing wrong credentials - Had the same issue, and it turned out to be the corporate proxy settings.

**Comment by AlexejheroYTB** [comment]
I have the same issue

**Comment by davidnlarkin72** [comment]
I have also figured out (Based upon AndyGee's suggestion regarding .gitconfig) that if you are in a real bind you can add to the following section. (This may present security concern but could help in a pinch)

[http]
      sslVerify = false

Then restart the app
