### ISSUE TITLE
GitHub Desktop failed to launch

### ISSUE THREAD

**Issue by cyril31** [desktop/desktop#3663]
### Description

Error: write EOF
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite (net.js:813:14)

Version: 1.0.11
OS: Windows 6.1.7601

### Version

**GitHub Desktop version:** 1.0.11

**OS version:** Windows 6.1.7601

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** I expect that A dialog window will popup that says "Enter the name of the repository (that will be a part of the website’s URL), select if you want to keep the repository private (the website will still be public) and press “Publish Repository”:"

**Actual behavior:** I'm just trying to add a 'summary' & 'description' and upon pressing the "Commit To Master" button, the error appears.

**Reproduces how often:** 100% (Every time I do that, it always show the error)

**Comment by niik** [comment]
Hi @cyril31, could you please attach the most recent log file from:
   `%APPDATA%\GitHub Desktop\logs\*.desktop.production.log`

**Comment by shiftkey** [comment]
Closing as inactive.

@cyril31 if you can share the log files from around the time we can revisit this.
