### ISSUE TITLE
Diff should only show changes in renamed file

### ISSUE THREAD

**Issue by vp2177** [desktop/desktop#3673]
The diff view shows all lines as new, in case of a renamed file. Only changes between the old and the new files should be shown.

It looks as though this might have been fixed in the past (#495), but I am using v`1.0.11` and can reproduce this.

**Comment by shiftkey** [comment]
@vp2177 could you share a reproduction of this (whether it's with a change to be committed or part of an existing commit), to speed up investigating? Maybe something has changed with the underlying Git behaviour...

**Comment by j-f1** [comment]
FWIW, I’m seeing this too — renames show up in history, just not in the changes tab.

**Comment by shiftkey** [comment]
> renames show up in history, just not in the changes tab.

This could be related to the fact that, when committing, a rename isn't detected by Git until both files are staged in the index. Desktop doesn't do this (it defers staging files until you make the commit in the UI), but if you do it in an external program and switch back to Desktop it _should_ show. Maybe that's the difference here?

**Comment by vp2177** [comment]
![rename](https://user-images.githubusercontent.com/451903/34364751-c2ea5940-ea80-11e7-9ad7-ec91ee4e8d53.gif)

**Comment by shiftkey** [comment]
@vp2177 thanks for the details. I'll have a look at reproducing this and see if I can isolate where it has been introduced.

**Comment by j-f1** [comment]
Would it be possible to stage and unstage files when clicking the checkboxes or toggling lines in the diff view?

**Comment by shiftkey** [comment]
@j-f1 unstaging the whole file is relatively easy. Unstaging a specific hunk or line is where things get really problematic. There might be some part of porcelain Git that you can do this in, but I've not looked for it.

**Comment by shiftkey** [comment]
@vp2177 @j-f1 I've got a fix in for the history view in #3892 but detecting renames in the working directory depends on the blobs being staged in the index, and we've already found some corner cases about this which are mentioned [here](https://github.com/desktop/desktop/blob/master/app/src/lib/git/diff.ts#L160-L186).

At this point we'll display the rename if both files are staged outside Desktop:

<img width="609" src="https://user-images.githubusercontent.com/359239/35603828-529d7e9a-0693-11e8-923a-31b19987648f.png">

If they're unstaged (or the new file is untracked) our behaviour mirrors Git:

<img width="840" src="https://user-images.githubusercontent.com/359239/35603807-2e2ac0b8-0693-11e8-9d1a-e8b8f9f27f1d.png">

Please open a fresh issue if you have feelings about this experience, so we can track this.
