### ISSUE TITLE
Unable to clone to local repository from git bash. error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied

### ISSUE THREAD

**Issue by ManamNagarjuna** [desktop/desktop#3677]
### Description

Unable to clone to local repository from git bash. error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied

"https://github.com/ManamNagarjuna/Python.git/"

when i run "**git pull origin master**" command i'm getting the mentioned error. 

### Version

**GitHub Desktop version:** [i'm using Git 2.15.1.2]

**OS version:** [windows 10]

### Steps to Reproduce

1. [git init]
1. [git remote add origin "https://github.com/ManamNagarjuna/Python.git"]
1. [git pull origin master]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by shiftkey** [comment]
> GitHub Desktop version: [i'm using Git 2.15.1.2]

This reproduction seems to be related to the latest [Git for Windows](https://github.com/git-for-windows/git) release rather than GitHub Dkestop. Could you please open an issue there?
