### ISSUE TITLE
Github Desktop not accepting login credentials

### ISSUE THREAD

**Issue by xenon54xenon54** [desktop/desktop#3680]
### Description

Upon opening Desktop, I got the attached error. I disregarded the error, and continued to try and make a commit. I typed in my commit, hit sync, and tried to push origin. I got another error. Since then, I have been unable to log in to my account from Desktop, and every time I attempt to log in to my account, the first error message gets thrown. 

### Version

**GitHub Desktop version:** 1.0.11

**OS version:** 10.13.2

### Steps to Reproduce
I do not know if other users can reproduce this error, and do not know if this is just some weird, isolated, client-side bug.

1. Open Desktop
1. Open preferences
1. Attempt to sign in w/ correct login information

First error (On attempting to log in)
![screen shot 2017-12-25 at 7 33 47 pm](https://user-images.githubusercontent.com/34069040/34343840-a62f9e86-e9aa-11e7-98fb-3c01d7ae1928.png)
Second error (On attempting to commit)
![screen shot 2017-12-25 at 7 37 44 pm](https://user-images.githubusercontent.com/34069040/34343852-2262a480-e9ab-11e7-8a59-59aa8cc01bab.png)

**Reproduces how often:** 100% after at least 6 attempts

### Logs
Desktop did not crash, so there is no crash log.

#### Additional Information

I have copied and pasted my login credentials from my account in case I were simply typing something in wrong consistently.

I am also aware that there is very little information here, so if somebody could tell me specifically what files to retrieve in what directories, that would be very helpful.

**Comment by shiftkey** [comment]
@xenon54xenon54 we've had similar reports of this like #3625 which seem to be related to the keychain not being accessible.

Could you try this?

> Try opening **Keychain Access.app**. Right-click on the `login` keychain and try locking it and then unlocking it again.

**Comment by xenon54xenon54** [comment]
I don't have desktop linked to keychain, but I tried restarting my computer, and it logged me back in with no problems. Thanks for your help.

**Comment by ciconsulting** [comment]
I had that problem too.
