### ISSUE TITLE
Cannot find tools menu

### ISSUE THREAD

**Issue by top1st** [desktop/desktop#3681]
![image](https://user-images.githubusercontent.com/23559697/34346559-d4bfaf50-ea33-11e7-95ca-9a6b9c877974.png)

### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by shiftkey** [comment]
These are now located under the **File** | **Options** top menu.
