### ISSUE TITLE
'SSL certificate problem: unable to get local issuer certificate' when trying to clone repos

### ISSUE THREAD

**Issue by azumukupoe** [desktop/desktop#3684]
### Description

[Cannot clone repositories]

### Version

**GitHub Desktop version:** [1.0.11]

**OS version:** [Microsoft Windows [Version 10.0.17063.1000]]

### Steps to Reproduce

1. [Clone a Repository]
1. [Choose a repository]
1. [and so on]

**Expected behavior:** [Repository cloned]

**Actual behavior:** [Cloning into 'path'...
fatal: unable to access 'url': SSL certificate problem: unable to get local issuer certificate]

**Reproduces how often:** [100%]

### Logs

[2017-12-26.desktop.production.log](https://github.com/desktop/desktop/files/1587027/2017-12-26.desktop.production.log)

**Comment by shiftkey** [comment]
@azumukupoe could you share your Git configuration value by opening a command line and running this command?

```
$ git config -l --show-origin
```

**Comment by azumukupoe** [comment]
Yes

>file:"C:\\ProgramData/Git/config"       core.symlinks=true
file:"C:\\ProgramData/Git/config"       core.autocrlf=true
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    http.sslbackend=schannel
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    diff.astextplain.textconv=astextplain
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.clean=git-lfs clean -- %f
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.smudge=git-lfs smudge -- %f
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.process=git-lfs filter-process
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.required=true
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    credential.helper=manager
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    core.editor=nano.exe
file:C:/Users/azumu/.gitconfig  filter.lfs.required=true
file:C:/Users/azumu/.gitconfig  filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/azumu/.gitconfig  filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/azumu/.gitconfig  filter.lfs.process=git-lfs filter-process
file:C:/Users/azumu/.gitconfig  user.name=azumukupoe
file:C:/Users/azumu/.gitconfig  user.email=azumukupoe1999@gmail.com
file:C:/Users/azumu/.gitconfig  winupdater.recentlyseenversion=2.15.1.windows.2
file:C:/Users/azumu/.gitconfig  http.sslbackend=openssl

**Comment by shiftkey** [comment]
I think I know what's going on, but I haven't had a chance to test this out.

Your Git for Windows has a system Git configuration with these values:

```
[http]
    sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
    sslbackend=schannel
```

GitHub Desktop won't see these values, as it has it's own system configuration file with `http.sslbackend=schannel` set. This means it'll use the Windows Certificate Store to validate server certificates.

In your global `~/.gitconfig` you've set `http.sslbackend` back to the classic `openssl`. GitHub Desktop will use these values, but without also setting `http.sslcainfo` it's going to fail on all clones - because no backing store is found for Desktop.

So you have two options:

 - if you don't need to set `http.sslbackend=openssl` globally, removing that value should make Desktop work
 - if you need `http.sslbackend=openssl` set globally, you should also set `http.sslcainfo` so that GitHub Desktop has a backing store of certificates to validate

Let me know if you have any other questions!

**Comment by azumukupoe** [comment]
@shiftkey Thank You!

**Comment by shiftkey** [comment]
Closing this out as resolved. @azumukupoe let me know if you're still encountering issues.

**Comment by brucepessoa** [comment]
In my case I had the same problem but using VSCode. I've tried to clone repos but shows the same mesage, always: 
Cloning into 'MyProject'...
fatal: unable to access 'https://github.com/theuser/MyProject.git/': SSL certificate problem: unable
to get local issuer certificate
In the Desktop -> file:"H:\\Program Files\\Git\\mingw64/etc/gitconfig"    http.sslbackend=openssl

**Comment by shiftkey** [comment]
@brucepessoa VSCode uses an external version of Git - please report this issue to the [Git for Windows](https://github.com/git-for-windows/git) project, as we can only help you address issues with GitHub Desktop and it's embedded Git.

**Comment by rosadosol** [comment]
Please help
I have a similar problem to clone a repository in OHI-Science I've got this error report cloning from RStudio:
"fatal: unable to access 'https://github.com/OHI-Science/mex.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - La funci�n de revocaci�n no puede comprobar la revocaci�n para el certificado."

**Comment by acartera** [comment]
I am also getting this error. Still! I have tried everything I can find ... hours wasted!! Like so much with GIT there are numerous variations,options, etc etc but nothing definitive.  I simply cannot believe it can be so difficult. Maybe time to switch to another SCM tool

**Comment by steveward** [comment]
@rosadosol I have not used RStudio, but that error you are seeing is the same one that [we have a workaround for](https://github.com/desktop/desktop/blob/master/docs/known-issues.md#certificate-revocation-check-fails---3326). Try that to see if it gets things working for you.

@acartera I would be happy to look into this further with you -- would you mind [filling out our contact form](https://github.com/contact)? Be sure to mention GitHub Desktop, which will ensure it gets routed to me.

**Comment by acartera** [comment]
I am also getting this error. Still! I have tried everything I can find ... hours wasted!! Like so much with GIT there are numerous variations,options, etc etc but nothing definitive.  I simply cannot believe it can be so difficult. Maybe time to switch to another SCM tool

**Comment by acartera** [comment]
Thanks for offer. I don't have anymore time for this.  I just reverted to what I did once a few years which is the standard workaround: sslVerify=false.

**Comment by TheSil** [comment]
If by any chance you are using Kaspersky Internet Security, then note that this issue was recently introduced in some old versions of the software, more about this was discussed here https://github.community/t5/How-to-use-Git-and-GitHub/Getting-quot-SSL-certificate-problem-self-signed-certificate-in/td-p/7531/page/3. It helped for me to just install new version (KIS 2019), and the SSL issues with github went away.

**Comment by mkarlsson** [comment]
I go this error in VS2017 and solved it by opening Git bash anth then $ git config --global http.sslBackend schannel. Thanks to https://stackoverflow.com/questions/16668508/how-do-i-configure-git-to-trust-certificates-from-the-windows-certificate-store

**Comment by zannn3** [comment]
git fetch is the shortcut to solve it

**Comment by Vasudhatapriya** [comment]
SSL certificate problem: certificate has expired.

**Comment by mido1966** [comment]
Dankeschön von euer helfen herzlichen Glückwunsch wünsche alles

‏‫من الـ iPhone الخاص بي‬

‫في 16‏/02‏/2019 الساعة 11:47 ص، كتب/كتبت ‏Vasudhatapriya ‏<notifications@github.com<mailto:notifications@github.com>>:‬


SSL certificate problem: certificate has expired.

**Comment by AnotherSamWilson** [comment]
> git fetch is the shortcut to solve it

Uhhh this worked, but can you explain why? Myself and other devs have been working on this problem all morning and this magically worked. Did it refresh the session?

**Comment by nicks9188** [comment]
git config http.sslVerify false

https://stackoverflow.com/questions/11621768/how-can-i-make-git-accept-a-self-signed-certificate

**Comment by magneticflux-** [comment]
Please don't disable SSL unless you know what you are doing. In my case, updating Git for Windows fixed the issue because my certificates were out of date.

**Comment by treuh** [comment]
installed the latest version git and it worked

**Comment by speich** [comment]
I solved it on windows 10 by enabling "Use the native Windows Secure Channel library" when (re-)installing git instead of "Use the OpenSSL library"

![screenshot](https://user-images.githubusercontent.com/649653/74646195-a5a26f00-5179-11ea-9054-a2c78375adad.gif)

**Comment by girdharpatel** [comment]
Thank you very much speich. I had exact same issue and I solved it using your suggestion. Thanks a lot.
