### ISSUE TITLE
2fa started failing

### ISSUE THREAD

**Issue by tablatronix** [desktop/desktop#3686]
Could not authenticate this morning, get `username or passphrase you entered is incorrect`

Switched to sms, code still failing.

OSX, I have no logs where specified, nor a github desktop folder even.

v 1.0.11
osx 10.13.2

**Comment by lucashoeft** [comment]
I experienced the same. Got logged out (I have 2FA enabled) and the app displayed only `username or passphrase you entered is incorrect`

Its basically this issue, that already got closed: https://github.com/desktop/desktop/issues/3263

You have to open the app Keychain Access and lock and unlock the `login` Keychain. Then it should work.

V 1.0.11
macOS 10.12.6

**Comment by tablatronix** [comment]
Thanks, I did not see that issue. Will try then close

**Comment by shiftkey** [comment]
I'm going to close this out as a known issue as @lucashoeft has cross-referenced the existing issue.

@tablatronix please report back if you're still encountering issues.
