### ISSUE TITLE
Syncing a fork

### ISSUE THREAD

**Issue by vincent3569** [desktop/desktop#3687]
Hi

I made a fork of a project to improve it for my needs.
I read something about syncing a fork (https://help.github.com/articles/syncing-a-fork/), but it needs to use git ui and I am not fluant with it.
I wish to know if there is a way to do that with Github desktop ?

Thanks

**Comment by shiftkey** [comment]
@vincent3569 I think the missing part of this is #2639 - this will let you see the commits added to the upstream repository and merge those into your fork.

Check out the mockups in https://github.com/desktop/desktop/issues/2639#issuecomment-333621771 to understand more and add your feedback to the issue - we should be kicking that off soon!
