### ISSUE TITLE
Re-open: Unable to push, Authentication failed...

### ISSUE THREAD

**Issue by utlco** [desktop/desktop#3697]
### Description

This is the same or related to issue 1852 and is still a problem.

When I try to push to a remote repository I get the following dialog:
<img width="607" alt="screen shot 2017-12-28 at 12 34 28 pm" src="https://user-images.githubusercontent.com/1709797/34422712-f970aa72-ebcb-11e7-8589-10553b9b1f5c.png">

This just started happening for no apparent reason. I still have full access to the repository and GitHub Desktop seems to be signed in so I'm stumped.

I'm using GitHub Desktop version 1.0.11 on MacOS 10.11.6

Any help on this would be greatly appreciated thanks!

### Version

**GitHub Desktop version:** 1.0.11

**OS version:** MacOS 10.11.6

### Steps to Reproduce

**Repository:** ekmmetering/Push3

1. Click on "Push Origin"

**Expected behavior:** Local repository pushed to remote

**Actual behavior:** Error

**Reproduces how often:** 100%

### Logs

[2017-12-28.desktop.production.log](https://github.com/desktop/desktop/files/1592071/2017-12-28.desktop.production.log)

**Comment by j-f1** [comment]
Can you try locking and unlocking your login keychain (in Keychain Access)? We sometimes see the keychain get in a bad state that prevents the app from accessing it.

**Comment by utlco** [comment]
Thanks, but that didn't seem to work. I also tried just deleting all the github login credentials found in Keychain and restarted GitHub Desktop and signed back in. No luck. Oddly, the initial sign in works fine - just the Push can't seem to authenticate...

**Comment by shiftkey** [comment]
@utlco 

```
2017-12-28T20:18:58.767Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
Permission denied (publickey).
fatal: Could not read from remote repository.
```

This looks like you're working with an SSH remote rather than a HTTPS remote. This distinction is important because SSH remotes don't use the keychain for credentials, and instead require a running `ssh-agent` process with the right keys added to do anything network-related.

Can you confirm you have these setup? These two commands will help understand what your current setup looks like:

```
$ ps -ax | grep ssh-agent
$ ssh-add -l
```

**Comment by utlco** [comment]
Your right, I'm using an ssh remote (I can't remember why ssh vs https).
I just deleted my previous rsa key and regenerated a new one and now it seems to work fine! Not sure why since the previous one had been working fine until today...
Anyway, thanks for the help.

For anybody else that runs into this, here are the steps:

1. in ~/.ssh delete your github rsa public and private keys
2. ssh-keygen -t rsa -b 4096 "you@yours.com"
3. ssh-add -K <the-github-private-key-file-you-just-generated>
4. pbcopy <the-github-public-key-file-you-just-generated>
5. From your GitHub account "/settings/SSH and GPG keys"
    delete the previous key then add the new one (pasting it from the clipboard)
6. Et voila.

See: [https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/)
and [https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/)

**Comment by shiftkey** [comment]
@utlco thanks for sharing the details. I'm glad it's back and working!
