### ISSUE TITLE
When you sync a repo, "View on GitHub" will need a tab change to be used

### ISSUE THREAD

**Issue by justalemon** [desktop/desktop#3698]
### Description

When you sync a repository with "History" open, you will need to alternate the tabs to use "View on GitHub for the recent commits.

### Version

**GitHub Desktop version:** 1.0.11
**OS version:** Windows 10 v1709 c16299.125

### Steps to Reproduce

1. Clone a repository from GitHub
1. Create a commit
1. Select the History tab with that commit
1. Sync the repo
1. Right-click and try to select "View on GitHub"

![Repro](https://user-images.githubusercontent.com/11861253/34441743-7702ef88-ec9c-11e7-9c90-1d3a647d9720.gif)

**Expected behavior:** The "View on GitHub" option should be available after the sync.

**Actual behavior:** The option is disabled even if the commit is already on GitHub.
![Capture](https://user-images.githubusercontent.com/11861253/34441462-a8d02a0a-ec9a-11e7-897c-126c552701a3.png)

**Reproduces how often:** Every time.

### Logs
[2017-12-29.desktop.production.log](https://github.com/desktop/desktop/files/1593467/2017-12-29.desktop.production.log)

**Comment by shiftkey** [comment]
@justalemon thanks for the details. This feels similar to #2737, which dealt with remote commits not being added to the history - which we fixed in #3541. In this case we should "discard" from cache and re-add local commits that we know need to be updated.

**Comment by justalemon** [comment]
Yeah, is similar to #2737 but that was for 0.X.X (the old version of GitHub Desktop).

The solution is a bit simple: if the History tab is open, refresh the commits after the sync.

**Comment by soljurami** [comment]
#git config

**Comment by Samuelvey** [comment]
This is useful and learning practice.
