### ISSUE TITLE
Summary of changes to repos: Feature idea

### ISSUE THREAD

**Issue by crspybits** [desktop/desktop#3703]
### Description
Hey folks. I really like this app :). Thanks. One thing that would help because I use this with many repos that have active changes at one time, is a summary at the top-level UI of changes.  This would likely take the form of a new column-- in the place where I've marked with red. Something like an indication of the number of files with changes and whether or not those changes have been committed, staged for pushing. I.e., this would be a summary of a `git status` for each repo.

<img width="386" alt="screen shot 2017-12-30 at 11 35 04 am" src="https://user-images.githubusercontent.com/5758762/34456556-9a72e0ee-ed56-11e7-92c4-82ac74a43c13.png">

**GitHub Desktop version:** 1.0.11
Running on Mac OS

**Comment by shiftkey** [comment]
@crspybits thanks for the feedback!

This is on our roadmap for the 1.3 release, so I'm going to roll this up into our tracking issue #2259. Please follow along with that issue!

**Comment by soljurami** [comment]
Hola desea conocer más a cerca de github y de git

**Comment by soljurami** [comment]
Porque he visto que es muy importante los y ser desarrolladores

**Comment by crspybits** [comment]
Awesome! :).
