### ISSUE TITLE
Unable to access repository over HTTPS

### ISSUE THREAD

**Issue by houghtonap** [desktop/desktop#3713]
### Description

Tried to clone a repository using a URL and it hung for a while, then came back with a fatal message indicating that it was unable to access the repository.

### Version

**GitHub Desktop version:** 1.0.11

**OS version:** Windows 7

### Steps to Reproduce

1. Go to repository in GitHub in browser
1. Click the Clone or Download button
1. Select Use HTTPS link
1. Copy URL
1. Activate GitHub Desktop window
1. Click the Clone a Repository button
1. Click URL tab
1. Paste URL
1. Select local path to download
1. Click Clone button

**Expected behavior:** Clone of the repository.

**Actual behavior:** Hangs for a bit, then get a Fatal error.

**Reproduces how often:** 100%

### Logs

2018-01-02T13:09:37.305Z - info: [ui] [AppStore] loading 0 repositories from store
2018-01-02T13:09:37.322Z - info: [ui] [AppStore] found account: houghtonap (null)
2018-01-02T13:09:37.472Z - info: [ui] launching: 1.0.11 (Windows 6.1.7601)
2018-01-02T13:14:43.760Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/NaturalDocs/NaturalDocs.git - houghtonap (has token)
2018-01-02T13:18:29.137Z - info: [ui] Executing clone: git -c credential.helper= clone --recursive --progress -- https://github.com/NaturalDocs/NaturalDocs.git C:\Downloads\GitHub\NaturalDocs (took 225.329s)
2018-01-02T13:18:29.140Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://github.com/NaturalDocs/NaturalDocs.git C:\Downloads\GitHub\NaturalDocs` exited with an unexpected code: 128.
Cloning into 'C:\Downloads\GitHub\NaturalDocs'...
fatal: unable to access 'https://github.com/NaturalDocs/NaturalDocs.git/': Failed to connect to github.com port 443: Timed out

#### Additional Information

This problem most likely is that GitHub Desktop does not recognize that the workstation is required to have Internet traffic go through a proxy server. Other applications will cause the proxy server credentials dialog box to appear and I enter my credentials and everything works as normal. I never get the proxy server credentials dialog box from GitHub Desktop.

**Comment by shiftkey** [comment]
@houghtonap thanks for the details!

> This problem most likely is that GitHub Desktop does not recognize that the workstation is required to have Internet traffic go through a proxy server.

The configured proxy server needs to be set as part of Git's global configuration. See https://stackoverflow.com/a/19213999/1363815 for a walk-through of how to set this.

> Other applications will cause the proxy server credentials dialog box to appear and I enter my credentials and everything works as normal.

Unfortunately Git isn't quite clear that this is a proxy error, rather than a generic network error. We're tracking making the application handle this better in #3294.

**Comment by sirusdynamo** [comment]
fatal: unable to access 'https://github.com/sirusdynamo/restaurantMenu.git/': Failed to connect to 192.168.43.1 port 44355: Connection timed out
was using a proxyserver HTTP injector
set network proxy to 192.168.43.1 port 44355
now network proxy is set to None

stoppped and connected normally
O.S:ubuntu 16.04 LTS


pls already tried
 git config --global --unset-all https.proxy
git config --global --unset-all http.proxy
git config --list
---------------------------------------
color.ui=auto
push.default=upstream
merge.conflictstyle=diff3
core.editor=code --wait
credential.helper=cache --timeout=3600
user.email=xxxxxxxxxx@gmail.com
user.name=xxxxxxxxxx
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/sirusdynamo/restaurantMenu.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*

**Comment by sirusdynamo** [comment]
solved
checked the environment with
echo $http_proxy
echo $https_proxy
echo $HTTPS_PROXY
echo $HTTP_PROXY

**Comment by joaosantos** [comment]
> resolvido 
> verifiquei o ambiente com 
> echo $ http_proxy 
> echo $ https_proxy 
> echo $ HTTPS_PROXY 
> echo $ HTTP_PROXY 
> e deletei o proxy

Sirius como você achou e deletou o proxy? sou iniciante no git/linux, e de uma hora para outra meu git começou a dar este erro, como procedo para resolvê-lo?

**Comment by sirusdynamo** [comment]
verifique este link de estouro de pilha resolve o problema

after the above commands have been run in the terminal
do
`git config --global --unset https.proxy`
else try
`export http_proxy=`

[https://stackoverflow.com/questions/32268986/git-how-to-remove-proxy](url)

**Comment by joaosantos** [comment]
Hi Sirius, it worked fine by using this command and restarting the machine. Tank you a lot.
