### ISSUE TITLE
How to download git_shell for windows.

### ISSUE THREAD

**Issue by kimmiekim** [desktop/desktop#3714]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** 1.0.11

### Steps to Reproduce

1. [First step] install 1.0.11
1. [Second step] try to find git_shell
1. [and so on]

**Expected behavior:** find git_shell.exe installed with the desktop

**Actual behavior:** no git shell found anywhere

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Logs
no logs

#### Additional Information
The older github desktop install came with git_shell.exe. I can't figure out how to install git_shell with the 
![git_shell](https://user-images.githubusercontent.com/17532796/34490670-91f31c4a-efae-11e7-8751-afe53ed02248.PNG)
newer installation package. can you please instruct how I can install github shell?

**Comment by j-f1** [comment]
Does [Git for Windows](http://gitforwindows.org/) work for you?

**Comment by kimmiekim** [comment]
yes, have that already installed

**Comment by shiftkey** [comment]
Git Shell was not ported over as part of the Electron Desktop client. See #340 for more context.
