### ISSUE TITLE
Too many Undo clicks results in Git Lock

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3717]
Hitting the `undo` button too fast results in a git lock dialogue:
<img width="599" alt="34125520-556fbf5e-e3eb-11e7-947c-b5c5de199719" src="https://user-images.githubusercontent.com/14828183/34502033-9029f8c6-efc6-11e7-8f08-db32ed920ff3.png">

You can reproduce by committing multiple changes, then hitting the `undo` button rapidly. 

Related to: https://github.com/desktop/desktop/issues/3630

>  `undoCommit` is wrapped in a promise, but maybe we're not surfacing some state to ensure it can't occur concurrently.

mac os, 1.0.12-beta0

**Comment by nerdneha** [comment]
Wasn't able to reproduce this using production or beta without changing anything else with my 
machine. I'd imagine there's some extra context here, ex: we need to have an editor open? Given the reproduction steps made exclusively here, I couldn't reproduce this.

Wondering if anyone else has been able to reproduce this.

**Comment by tierninho** [comment]
Closing, can't reproduce either
