### ISSUE TITLE
Files in .gitignore shows in GitHub Desktop and commits on Initial Commit

### ISSUE THREAD

**Issue by William5553** [desktop/desktop#3721]
### Description

Whenever I open GitHub Desktop it keeps asking me to commit files that are in the .gitignore file.

### Version

**GitHub Desktop version:** 1.0.11

**OS version:** Microsoft Windows [Version 10.0.16299.125]

### Steps to Reproduce

1. Launch GitHub Desktop
2. Look on sidebar of repository
3. Files that should not be there are there

**Expected behavior:** The files wouldn't be there

**Actual behavior:** The files are there

**Reproduces how often:** 100%

### Logs

Log file: https://gist.github.com/William5553/488be7388ce4261d5d86bf053bcc7868

**Comment by shiftkey** [comment]
@William5553 you'll need to provide some more details about this to troubleshoot this properly:

 - the contents of the `.gitignore` file at the root of the repository
 - the file names that are marked as ready to commit
 - whether these files are already tracked by Git - changes to `.gitignore` won't affect these files, and they'll need to be deleted (and committed) before they'll be affected

**Comment by William5553** [comment]
.gitignore:
`# eclipse
bin
*.launch
.settings
.metadata
.classpath
.project

# idea
out
*.ipr
*.iws
*.iml
.idea


# gradle
build
.gradle

# other
eclipse
run
*.rar`
File names: eclipse and .idea
Yes
