### ISSUE TITLE
Can't change settings without signing into git

### ISSUE THREAD

**Issue by TheRedSpy15** [desktop/desktop#3725]
### Description

[I want to turn off sharing usage data, but I can't save the settings without signing into git. I get a red banner saying: "Git name field cannot be a disallowed character", I don't have a git account, so this puts me in a bad spot.]

### Version

**GitHub Desktop version:** [1.0.11]

**OS version:** [Windows 10.0.16299]

### Steps to Reproduce

1. [Open settings]
1. [uncheck share usage data]
1. [attempt to click grayed out save button]

**Expected behavior:** [Be able to turn off sharing usage data, and save]

**Actual behavior:** [Get a red banner about signing into git, and can't safe settings]

**Reproduces how often:** [%100]

**Comment by TheRedSpy15** [comment]
I would like to add, I have reinstalled the client

I will try another version, and post here with my findings

**Comment by tierninho** [comment]
@TheRedSpy15 The error you are encountering has been filed here: https://github.com/desktop/desktop/issues/3722 so it will be fixed. For now, I suggest the older build as you mentioned, as the "disallowed character" was a recent change.

Per your issue with usage tracking. Please open the Developer Tools under the View menu. Access the Application tab, Local Storage session, and change the `Stats-opt-out` to 1. Ctrl-R to refresh the Desktop, and you should be good to go. (In main menu, check Prefs > Advanced tab to verify).

<img width="1117" alt="screen shot 2018-01-04 at 10 24 36 am" src="https://user-images.githubusercontent.com/14828183/34578367-879d22d6-f139-11e7-98dd-a95ad3cf52b8.png">
