### ISSUE TITLE
Cmd-R won't open `Create Pull Request` if Dev Tools open

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3726]
If you hit `cmd-R` when the dev tools module is open, it will reload the app instead creating a PR.

OSX, 1.0.12-beta0

**Comment by shiftkey** [comment]
It's a [documented shortcut](https://developers.google.com/web/tools/chrome-devtools/shortcuts) in the DevTools:

<img width="818" src="https://user-images.githubusercontent.com/359239/34581840-477883ba-f168-11e7-9127-c9cf2c8041e8.png">

I don't think we can do much about this in this situation, and I think we handle this fine when DevTools isn't open which is more important.

**Comment by tierninho** [comment]
Sounds good, closing this...
