### ISSUE TITLE
"Show file location in Explorer" - additional feature request for Github Desktop

### ISSUE THREAD

**Issue by lewispg228** [desktop/desktop#3731]
Currently, in the Github Desktop I'm using (1.0.11), you can quickly jump to a repository. This is great, but I'd love to be able to jump directly to a file's location.

![image](https://user-images.githubusercontent.com/601236/34618603-803057d4-f1fc-11e7-8f35-ec17861eebc3.png)

The reason is, I often am looking at a file in the commit history, and I want to quickly navigate directly to that file (to begin working on it again, or view the entire thing in my editor of choice). Currently, I must mannually navigate from the home directory of the repository to where that file is. It's not that big of an issue with small repos, but sometimes a file can be located deep within lots of folders, and I have to remember exaclty where it is. In some of my repos, it can be like 5 or 10 folder deep.

Let me know and thanks!

-Pete

**Comment by shiftkey** [comment]
@lewispg228 thanks for the details. We caught this a bit earlier in #2845 which will mean both file lists (the changes list and the commit file list) are more consistent from a UX perspective.

I'll fold this feedback into that issue as a reminder.

**Comment by prerender-thorny** [comment]
@shiftkey https://skyler-passenger.github.io/VDObDryjZhOBa1jSKvRQha/
