### ISSUE TITLE
`Create New Branch` button hidden in Merge modal

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3733]
The `Create New Branch` button is partially hidden in the `Merge into current branch...` modal.

Reproduce:
- You need at least two branches, choose Master.
- Open `Merge into current branch...`
- Type some jibberish so all branches no shown.

<img width="627" alt="screen shot 2018-01-05 at 8 56 01 am" src="https://user-images.githubusercontent.com/14828183/34620091-1cf5da16-f1f9-11e7-843d-144963a00b79.png">

OS X, 1.0.12-beta0

**Comment by shiftkey** [comment]
> The `Create New Branch` button is partially hidden in the `Merge into current branch...` modal.

Creating a branch shouldn't be an option here. The branch list component should have a way to enable "no branches found" without also providing that option.
