### ISSUE TITLE
Filter results should be shown with emphasis on matched characters

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#3743]
For the `Clone Repository` modal, text is not bold when you type in filter.

## What should happen
<img width="309" alt="screen shot 2018-01-08 at 10 59 29 am" src="https://user-images.githubusercontent.com/14828183/34687261-06cc843a-f463-11e7-9d71-10f2aadaf3a0.png">

## What actually happens
<img width="437" alt="screen shot 2018-01-08 at 10 40 12 am" src="https://user-images.githubusercontent.com/14828183/34687551-e478b164-f463-11e7-8062-fd1a9a9c0dff.png">

This issue was created from #3739

**Comment by sidd607** [comment]
If no one is working on it, I would like to work on it

**Comment by j-f1** [comment]
I’m pretty sure this was fixed in #3873.

**Comment by iAmWillShepherd** [comment]
Hmm, looks like the PR didn't tag this issue as well. 

@j-f1 is correct, this was completed a while ago but was not auto-closed.
