### ISSUE TITLE
How can I see all the files in my cloned repository in my desktop client? it has not worked for years

### ISSUE THREAD

**Issue by renzojsf** [desktop/desktop#3748]
![gat](https://user-images.githubusercontent.com/12319218/34707205-2e2fd0fa-f4da-11e7-8d71-8a5787b8323e.png)

**Comment by iAmWillShepherd** [comment]
The beta of this application was released 8 months ago...

But to answer your question, the client will only show you files that have _changed_, so you need to make a change to one of the files in your repo and you will see it pop up in the **Changes** tab. If you want to see the commits where files have changed, just view the **History** tab.
