### ISSUE TITLE
Surfacing auth error for Enterprise sign-in post oAuth

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3753]
Initial Desktop sign-up process:
After using the `sign-in with the browser` link for Enterprise, I was unable to login (as I expected in my testing), however, I never was shown our generic auth error following the browser's oauth process redirect back to Desktop. 

I purposefully added `www` to the URL, and used `http` instead of `https` to trigger the error. The console caught the `404 requestOAuthToken: failed with endpoint` error but the user should also be notified with our generic messaging.

Reproduce:
- Revert Desktop to initial setup
- Select Enterprise sign via browser
- Manipulate the URL (I added www and used non-SSL)
- Oauth should open in browser and redirect back to Desktop
- No error surfaced to user

<img width="618" alt="screen shot 2018-01-09 at 1 34 49 pm" src="https://user-images.githubusercontent.com/14828183/34745216-9b404750-f544-11e7-9844-9ae1166e35a7.png">

However, repeating the same process from the Preferences modal, results in a surfaced error as intended:
<img width="775" alt="screen shot 2018-01-10 at 11 16 50 am" src="https://user-images.githubusercontent.com/14828183/34790882-138ed470-f5f8-11e7-8d84-8bb0dee1548c.png">

Perhaps we could mirror this error in the sign-up process? (Side note: if we show "continue with the browser" button in above modal, it just creates a loop for the user. Only option should be to cancel.)

mac os x, 1.0.12-beta1

**Comment by shiftkey** [comment]
Tentatively pulling this into 1.1.x as it feels like some low-hanging fruit, but it might need some @desktop/design input to tweak the layout of the Welcome Wizard.

**Comment by iAmWillShepherd** [comment]
@shiftkey, I've moved this to milestone 1.2.x so we can close out 1.1.x.

**Comment by billygriffin** [comment]
This seems to be part of #5686. cc: @niik let me know if you don't think that's the case.

**Comment by tierninho** [comment]
We do surface an auth error if the URL is completing wrong, for example: 
<img width="549" alt="Screen Shot 2019-03-18 at 3 21 46 PM" src="https://user-images.githubusercontent.com/14828183/54573726-8f9c9500-4991-11e9-8f93-e61bd75f234b.png">

However, if we use a valid url but manipulate it by adding `http` and `www`, but the browser<-->Desktop auth will ultimately be rejected with no error messaging except in the console:
<img width="668" alt="Screen Shot 2019-03-18 at 3 17 57 PM" src="https://user-images.githubusercontent.com/14828183/54573707-84496980-4991-11e9-86ed-1874b92ca56c.png">

cc @billygriffin if you feel this needs to be closed...

**Comment by billygriffin** [comment]
I think we ought to let this one surface organically. Closing for now.
