### ISSUE TITLE
Github Desktop doesn't sign in to enterprise account

### ISSUE THREAD

**Issue by nbucklin** [desktop/desktop#3761]
### Description

Cannot sign in to enterprise account from GitHub desktop. Tried to log in by cloning an enterprise project, by the enterprise project's url, or choosing File > Options > Accounts. Can log into enterprise account via GitHub website. Colleague using Windows 10 logs in with no issues. 

### Version

**GitHub Desktop version:** 1.0.12
**OS version:** Windows 6.1.7601

### Steps to Reproduce

1. Click on File > Options > Accounts and select "Enterprise: Sign On"
2. Enter GitHub enterprise address. Tells me it needs to sign on using browser
3. GitHub website opens asking me to allow GitHub Desktop access to GitHub account. Click "Allow"
4. Sometimes the log-in portal for my company opens asking me to enter ID and password. After those are entered a redirect happens and my browser asks to open GitHub Desktop. Other times my company log-in portal appears briefly then signs in automatically and then asks to open GitHub Desktop. 
5. GitHub desktop opens and sign in window appears. Gets stuck on this page and nothing else happens
![capture](https://user-images.githubusercontent.com/31641550/34798817-786d925e-f62b-11e7-9324-df966de9333a.JPG)

**Expected behavior:** GitHub Desktop logs into enterprise account

**Actual behavior:** GitHub Desktop gets stuck on sign in box

**Reproduces how often:** 100%

### Logs

2018-01-10T22:31:23.840Z - info: [ui] [SignInStore] initializing OAuth flow
2018-01-10T22:31:23.850Z - info: [main] opening in browser: https://github.ibm.com/login/oauth/(ID information removed)
2018-01-10T22:31:29.784Z - info: [main] Received possible protocol arguments: 2

#### Additional Information

Can log in to GitHub enterprise website with no issues.
Colleague with Windows 10 logs in without issue.

**Comment by iAmWillShepherd** [comment]
Could you upload your log files so I can have a look?

**Comment by shiftkey** [comment]
@nbucklin from the log it looks like the app isn't receiving the expected number of arguments, so it's not passing the callback into the app.

Could you open PowerShell and attach the output of these two commands:

```
> Get-Item -Path Registry::HKEY_CLASSES_ROOT\x-github-client\shell\open\command
> Get-Item -Path Registry::HKEY_CLASSES_ROOT\x-github-desktop-auth\shell\open\command
```

The second value is the one we're interested in for authentication, but I also want to sanity check the first value.

On my machine the second protocol handler looks like this:

```
    Hive: HKEY_CLASSES_ROOT\x-github-desktop-auth\shell\open


Name                           Property
----                           --------
command                        (default) :
                               "C:\Users\shiftkey\AppData\Local\GitHubDesktop\app-1.0.12\GitHubDesktop.exe"
                               --protocol-launcher -- "%1"
```

I just tested this on `1.0.12` with an up-to-date GHE instance (2.12.2) and was able to sign in fine, but that should give enough information to understand how your setup is different to mine.

**Comment by nbucklin** [comment]
Hi, attached is the output of those commands.

![capture](https://user-images.githubusercontent.com/31641550/34846168-4b986bb8-f6e5-11e7-955f-1c51d5ff3bd9.JPG)

**Comment by shiftkey** [comment]
@nbucklin well, looks like the neither protocol handler has been registered. That's odd.

@niik these should be applied on launch, right?

**Comment by niik** [comment]
> @niik these should be applied on launch, right?

They should but I wonder if there's a problem with the very very first launch. @nbucklin Could you try restarting the application and see if they show up? If they don't then it would appear as if desktop isn't able to write to the registry. Do you have any security restrictions applied to you machine that could prevent that?

**Comment by tedKim5178** [comment]
I have the same issue. I can log in through website but whenever I try to log in through Github Desktop,  somehow it does not work.

**Comment by nbucklin** [comment]
@niik Hi, sorry for the delayed reply. I restarted my computer and tried again- the results were the same as the Power Shell screenshot I showed earlier. I don't know of any security restrictions that would prevent this. Since my first message I've been able to connect to the same enterprise account via Git and the Git GUI. Both work as intended, but I access them using a personal access token. I don't see an option to do this via GitHub Desktop as it redirects to my company's SSO page.

**Comment by shiftkey** [comment]
> I don't know of any security restrictions that would prevent this.

@nbucklin it's a bit of a long shot, but there's a group policy related to registry access that might be involved:

![](https://user-images.githubusercontent.com/359239/32207790-5b2ef734-be52-11e7-9a50-64fe827573b0.png)

There might be a different location in the tree-view on the left-hand side, but if it's enabled that might explain why the app isn't allowed to update the registry.

**Comment by nbucklin** [comment]
@shiftkey Hi, I found these settings and they all said "Not configured". It seems like we might have exhausted the options. My colleagues using Windows 10 have no issues with the app, so maybe it's a sign I should upgrade. Thanks for the help!

**Comment by shiftkey** [comment]
@nbucklin apologies for the delay.

I'm not sure what else this could be, and if you are the only one seeing this then maybe upgrading is the only way out of this.

Let me know if there's anything else we can do to help!

**Comment by maslade** [comment]
I'm experiencing this as well - my symptoms have been identical to @nbucklin's, and the output of my `Get-Item`s are the same as well.  In case this helps shed light, I ended up here after I had successfully installed GitHub Desktop (but did not attempt Enterprise Login), then uninstalled and re-installed without any reboots in between.

**Comment by kaiilin** [comment]
I am running into the same issue and have no clue how to fix it. 
I tried both on Windows 7 and Windows 2008. Neither works.

**Comment by InfoSac** [comment]
I am using v2.1.3, but the issue was, I think, related to the SSL error that has been preventing me from cloning/pushing from the command line and Visual Studio. I believe this because I managed to fix the SSL issue, and was then able to log in with GHD.

I’ve attached the instructions I wrote up on the fix, in case it can help anybody else. Maybe add it to the FAQ? Anyway, if you revise or expand on it, please send me a copy for my notes.

Regards,
Harry L. George IV
Program Analyst, Clinical Informatics
Northern California Healthcare System

**Comment by JoboboHead** [comment]
Same issue, v2.43 & Win 11

**Comment by steveward** [comment]
@JoboboHead please open a new issue and fill out the template so we can assist you further.
