### ISSUE TITLE
Whitespace diff not always highlighted

### ISSUE THREAD

**Issue by koenpunt** [desktop/desktop#3762]
### Description

When having trailing whitespace changes, they do not always show up the same in the diff.

Take for example these 2 screenshots, on the left you see on 2 places trailing whitespace highlighted by a darker red. On the right the same diff, but with an additional blank line, and as you can see; there the trailing whitespace is no longer highlighted.

<img src="https://user-images.githubusercontent.com/351038/34801782-b590644c-f66a-11e7-9c23-25390656c7fc.png" width="300" /><img src="https://user-images.githubusercontent.com/351038/34801732-85924634-f66a-11e7-967a-74dc72439278.png" width="300" />

### Version

**GitHub Desktop version:** 1.0.12
**OS version:** macOS 10.13.2 (17C88)

### Steps to Reproduce

Hard to say, all kind of variations with whitespace changes can cause the inconsistency to happen.

I can try some combinations later, but first wanted to see if this issue is already known, or if someone maybe knows what could cause this.

**Comment by shiftkey** [comment]
@koenpunt thanks for the details. I'm not aware of this specific issue, but we are tracking a limitation with line diffs in #2485 that might be related.

If you're able to reproduce it with a public repository you could try and generate the diff patch so that others can apply it:

```
# to indicate where to apply the patch
$ git rev-parse HEAD

# generate the patch file
$ git diff > diff.patch

# to then apply it
$ git apply diff.patch
```

**Comment by joshaber** [comment]
This is _probably_ #2700. The heuristics we use to do line diffing are less than great and we bail more often than we really should.

I'm gonna close this and track it in #2700.

**Comment by koenpunt** [comment]
Looks like it, I’ll subscribe to that issue
