### ISSUE TITLE
Clear BOM before pushing files to the GitHub server

### ISSUE THREAD

**Issue by bopoh13** [desktop/desktop#3768]
Greetings!
I will try to explain the problem that has occurred in the headings of other issues without the text associated with the encoding of UTF-8.

### Description

The source text in the markup files (MarkDown, html, etc.) is stored in UTF-8. When I save the text in Windows, BOM (**0xEF, 0xBB, 0xBF**) is added to the beginning of the file. (In Linux operating systems, files in the UTF-8 encoding are created without a BOM.) BOM stays when I pushed of data from the _GitHub Desktop_ to the server, which can adversely affect the working of the source code. Usually to remove the BOM used [third-party apps](https://gist.github.com/3664455), such as _Notepad++_, which is not very convenient.
Can _GitHub Desktop_ delete from the BOM files when I push files to the Github server?

### Version

**GitHub Desktop version:** 3.3.4.0

**OS version:** Microsoft Windows [Version 6.1.7601]

### Steps to Reproduce

1. I create a text file through Windows Explorer
1. I type the text and save it in the encoding of UTF-8
1. I change the file extension to MD
1. Does not solve the problem `find . -type f \( -name '*.md' -o -name '*.html' \) -print0 | xargs -0 grep -l ``printf '^\xef\xbb\xbf'`` | xargs sed -i '1 s/^\xef\xbb\xbf//'` **single `**
1. I push the changes to the server

**Expected behavior:** https://github.com/jekyll/minima/blame/a4726e60/index.md#L1

**Actual behavior:** https://github.com/bopoh13/grok/blame/7fb3be1f/index.md#L1

**Reproduces how often:** everytime

**Comment by shiftkey** [comment]
@bopoh13 

> When I save the text in Windows, BOM (0xEF, 0xBB, 0xBF) is added to the beginning of the file.

Which program did you use to save the file?

**Comment by bopoh13** [comment]
@shiftkey, [notepad.exe](https://www.virustotal.com/en/file/233a35e4b579ccde25951f8e543f1d16ae3e7b5b3f29c1d56e691ffb075ced15/analysis/)
I also tried to run scripts through _bash_ and _cmd.exe_ to erase the BOM.

**Comment by shiftkey** [comment]
@bopoh13 I think this is a limitation of `notepad.exe` - I was able to reproduce this issue using the version of notepad that ships in Windows 10.

> Can GitHub Desktop delete from the BOM files when I push files to the Github server?

This isn't the right place to handle these changes - they need to be caught before committing, because after that the file contents ("blobs" in Git terminology) are tied to the created commit. You can't change one without changing the other.

Git itself is not opinionated about the file contents which you add to the repository, and Desktop has no plans to warn about BOMs, so I'd recommend using tools like Notepad++ that you can trust to handle files in a cross-platform way.

**Comment by bopoh13** [comment]
@shiftkey, sorry. I was inattentive. _Bash_ commands work fine. :metal:

**Comment by bopoh13** [comment]
Complexity when using commands specified in the topic is that the line-endings CRLF is replaced by LF. When working in Windows use the tried method with automatic [encoding in UTF-8 without BOM](https://github.com/bopoh13/grok/blob/initial/.gitattributes).
_Inform me if I gave an incomprehensible description. It will need to be edited._ :arrow_up:

**Comment by bopoh13** [comment]
:heavy_check_mark: The [client hook](https://gist.github.com/c55f1538454755fdff71fba0d686e371) must be placed on a local computer in the `REPO\.git\hooks` without extension `.sh`.
The rest will be done by the git himself. The issue is closed once and for all.
