### ISSUE TITLE
Feature Request: Split staged files/lines

### ISSUE THREAD

**Issue by reyronald** [desktop/desktop#3771]
First of all, great job guys! I'm loving the experience of using GitHub Desktop, and the look-and-feel of the product is the one I like the most so far of the tools that I've used!

### Description

Currently, the "Changes" section displays a list of all changed files in the repository that are not yet commited, and it's possible to commit them all at once, or choose specific lines to commit by clicking on them in the diff on the right.

What I would like to have, is a split view of the staged changes in the "Changes" section. With this view, the staged changes would be shown at the top half of the sidebar, while the yet unstaged at the bottom. This would allow me to see staged and unstaged changes in different diffs, instead of simultaneously in one.

I don't know if it it's taboo to mention competitor's products here so call me out on it if it is and I'll edit, but both Visual Studio Code (vscode) and SourceTree have this feature, so seeing it in action there will be worth a thousand words.

![stage-view](https://user-images.githubusercontent.com/7514993/34847719-b5c62554-f6f2-11e7-95f1-73c814737981.gif)

This is extremely useful for my workflow since it allows me to isolate changes I make and review them in the diff without having to commit anything yet. 

### Version

**GitHub Desktop version:** 1.0.12
**OS version:** Microsoft Windows [Version 10.0.15063]

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to detail this. 

There is an on-going discussion about this [here](https://github.com/desktop/desktop/issues/1688#issuecomment-320043903). Could you post the contents of your issue there please?

**Comment by reyronald** [comment]
I saw that issue before posting this one but didn't seem to me that it was about the same exactly.. sorry about that! my bad..

I'll take the discussion there when I get to my laptop, thanks!

**Comment by iAmWillShepherd** [comment]
@reyronald You are right. Initially when I created the issue, I was referring to a very specific thing, but the conversation evolved. Check this [comment](https://github.com/desktop/desktop/issues/1688#issuecomment-320043903).
