### ISSUE TITLE
GitHub Desktop Interactive ideas in MacOS

### ISSUE THREAD

**Issue by srxboys** [desktop/desktop#3776]
Dear GitHub:
               If I clone hundreds of projects, I want to catalog and classify functions of projects, or do note information under the name of projects, which is only for local convenience.

Thanks!!!!
------------------------------------------------------------------------
亲爱的GitHub：
          如果我的clone几百个项目，我想对项目进行目录分类查看的功能，或者在项目名下面进行备注信息，只作为本地方便查看。谢谢！！！！

**Comment by niik** [comment]
Hey @srxboys, thanks for opening this!

There's a few issues already around various forms of repository management such as

- https://github.com/desktop/desktop/issues/1929
- https://github.com/desktop/desktop/issues/1598
- https://github.com/desktop/desktop/issues/2037
- https://github.com/desktop/desktop/issues/2324

While these ideas are interesting for the future, they're beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md). We will revisit them in our next planning session.

If you feel like neither of those issues accurately captures what you want then let me know and we can reopen this issue.

**Comment by maxbed** [comment]
Sent from Mail for Windows 10



Dear GitHub:
If I clone hundreds of projects, I want to catalog and classify functions of projects, or do note information under the name of projects, which is only for local convenience.
Thanks!!!!
亲爱的GitHub：
如果我的clone几百个项目，我想对项目进行目录分类查看的功能，或者在项目名下面进行备注信息，只作为本地方便查看。谢谢！！！！
