### ISSUE TITLE
allow to open files from changed files list in default editor

### ISSUE THREAD

**Issue by tooomm** [desktop/desktop#3784]
### Description

I miss the ability to double click on a file in the "list of files with changes" to open the file.
Especially in the `Changes` view that would be great to further work with the file or e.g. fix errors spotted in the in-app diff.

For `History` tab it makes only sense if it would open the file in the browser at the related commit maybe.

![open_file](https://user-images.githubusercontent.com/9874850/34885281-be6874d2-f7bf-11e7-99d0-917ce6922a25.png)

### Version

**GitHub Desktop version:** 1.0.12
**OS version:** Microsoft Windows [Version 10.0.16299.125]

**Comment by shiftkey** [comment]
@tooomm thanks for the report. We're tracking this in #2845, so please follow along with that issue.

**Comment by digitalmaster** [comment]
This is now being tracked here: https://github.com/desktop/desktop/issues/2620
