### ISSUE TITLE
"create a pr" always creates it against master

### ISSUE THREAD

**Issue by tooomm** [desktop/desktop#3786]
### Description

I just realized this...
After creating a branch based on another branch than default/master and doing changes to it.
When I wanted to PR my changes from the client, it opens the webpage but is showing the wrong base branch and wants to merge the branch into master (always master it looks like?).

This could easily result in a very weird PR being created. :)

Maybe this is a repo specific workflow and one generally doesn't want to merge changes back to a branch he created his branch off? But always want to merge to master?

To improve my workflow:
GitHub Desktop should send to the create pr webpage with correctly comparing the new created branch against the initial branch (which can be different than master):
The link should be: ([source](https://webapps.stackexchange.com/questions/62912/how-to-compare-releases-to-a-specific-branch))
`https://github.com/{username}/{repo}/compare/{target-branch}...{source-branch}` 

*(Damn it, I'm really sorry... before creating an issue I always check and try to find duplicates. And it looks like I always miss them. For this, I couldn't find one either. :D )*

### Version

**GitHub Desktop version:** 1.0.12
**OS version:** Microsoft Windows [Version 10.0.16299.125]

**Comment by tierninho** [comment]
In other words, if a branch was created off the currently checked out branch (not including master), it should appear here (see pic) when the user selects `Create Pull Request` from the menu?

![screen shot 2018-01-12 at 9 29 22 am](https://user-images.githubusercontent.com/14828183/34887474-84d0f58a-f77b-11e7-8356-e1d355efbf58.png)

**Comment by tooomm** [comment]
Yes.

I get this:
![1](https://user-images.githubusercontent.com/9874850/34888250-d147a79e-f7c9-11e7-8935-57db55e503a3.png)

And I expect this:
![2](https://user-images.githubusercontent.com/9874850/34888257-d290313e-f7c9-11e7-8792-474c59aee3e4.png)

The fallback, if `test` doesn't exist any longer, can be master/default branch.

**Comment by shiftkey** [comment]
Some additional feedback:

 - this request goes somewhat against [the GitHub Flow](https://guides.github.com/introduction/flow/), which we are actively trying to encourage in the app
 - we don't currently have a way to track where you branched from in the app. We _could_ walk back in history to find this ref, but that feels unreliable.
 - what if you actually want to target the default branch when opening a PR?

**Comment by shiftkey** [comment]
I'm 👎 on over-complicating this flow here, and following what GitHub The Website does when it's creating a pull request.

Any objections @desktop/core @desktop/comrades?

**Comment by j-f1** [comment]
I agree with your :-1: — it’s not that hard to switch the branch from `master` once in a while.

**Comment by shiftkey** [comment]
I didn't hear any objections about the proposal to follow what GitHub the Website does, so I'm going to close this out.
