### ISSUE TITLE
Add support for launching PowerShell Core shell from Desktop

### ISSUE THREAD

**Issue by saschanaz** [desktop/desktop#3791]
### Description

GitHub Desktop allows me to open Windows PowerShell but not the new [PowerShell Core](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-60?view=powershell-5.1).

### Version

**GitHub Desktop version:** 1.0.12

**OS version:** Windows 10

### Steps to Reproduce

1. Options->Advanced->Shell

**Expected behavior:** I should be allowed to open PSC.

**Actual behavior:** No way to open it, just traditional Windows PowerShell.

**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
@saschanaz please refer to the [documentation](https://github.com/desktop/desktop/blob/master/docs/technical/shell-integration.md) about our shell integration. If someone wants to take a shot at integrating it, I'm happy to help with the review process.

Also, what are the differences between PowerShell and PowerShell Core in terms of installation and usage?

**Comment by saschanaz** [comment]
Installation: Currently Windows users have to install it manually. Not sure future Windows 10 builds will bundle it.
Usage: Generally same but no access to traditional .NET as PowerShell Core is based on new .NET Core.

**Comment by saschanaz** [comment]
The code to add shells seems simple enough but I will wait for https://github.com/PowerShell/PowerShell/pull/5915 as the current App Paths registration is bugged.

**Comment by saschanaz** [comment]
[v6.0.2](https://github.com/PowerShell/PowerShell/releases/tag/v6.0.2) includes https://github.com/PowerShell/PowerShell/pull/5915!
