### ISSUE TITLE
Allow for manual sorting of repositories in the application UI

### ISSUE THREAD

**Issue by IdanAdar** [desktop/desktop#3794]
### Description

I would like for the ability to manually sort the order of repositories that appear in the application UI.

### Version

**GitHub Desktop version:** 1.0.12-beta1

**OS version:** 10.13.2

### Steps to Reproduce

None.

**Expected behavior:** To be able to click&drag repositories in order to order/sort them.

**Comment by shiftkey** [comment]
@IdanAdar thanks for the feedback. We had a similar request for this in https://github.com/desktop/desktop/issues/2324 and I also added a comment about similar ideas in this comment https://github.com/desktop/desktop/issues/2324#issuecomment-317717682.

These ideas are marked as `future-proposal` for consideration, but feel free to add your thoughts to these issues.
