### ISSUE TITLE
Diff highlight: sometimes it works, sometimes it doesn't

### ISSUE THREAD

**Issue by brunnopleffken** [desktop/desktop#3797]
### Description
The image below is self-explanatory. These two lines have exactly the same change (`Coworking` to `@user.coworkings`). But the lines above are highlighted, the others aren't. Why? The same happen with a single `#` sign.

### Version

**GitHub Desktop version:** 1.0.12

**OS version:** Mac OS X High Sierra 10.13.2

### Steps to Reproduce

1. There're no well defined steps, because this kind of issue happen sporadically... But it's easily seen in the commit log of any project.

**Expected behavior:** Both sets of lines should have the same diff coloring behavior.

**Actual behavior:** Sometimes it highlights, sometimes it doesn't.

**Reproduces how often:**  Sometimes the diff highlight just doesn't work, for example, when adding `#` to a line to add a comment, or renaming a variable, adding/removing parameters, etc.

#### Additional Information

![diff_highlight](https://user-images.githubusercontent.com/3427344/34929261-dcfa9358-f9a9-11e7-95a7-fd4b74658d85.png)

<img width="273" alt="screen shot 2018-01-15 at 04 08 52" src="https://user-images.githubusercontent.com/3427344/34929266-e0e7b932-f9a9-11e7-864e-9edb025fb5e7.png">

**Comment by shiftkey** [comment]
@brunnopleffken thanks for the report. There's enough details in here to investigate further on our end, but if you can reproduce this with a public repository you can include the raw diff which will help with troubleshooting:

```shellsession
# to indicate where to apply the patch
$ git rev-parse HEAD

# generate the patch file
$ git diff > diff.patch

# to then apply it
$ git apply diff.patch
```

This also feels similar to #3762 but let's leave both open for now until we've had a chance to dig deeper into the underlying issue.

**Comment by joshaber** [comment]
This is _probably_ #2700. The heuristics we use to do line diffing are less than great and we bail more often than we really should.

I'm gonna close this and track it in #2700.
