### ISSUE TITLE
Unable to switch to a newly created branch

### ISSUE THREAD

**Issue by gebhushan** [desktop/desktop#3800]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by gebhushan** [comment]
Version : 1.0.12
OS Version : Windows 10

Expected behavior: Change to Newly created Branch.
Actual Behvior: Not Changing, but instead is also not redirecting if tried to switch after creating.

**Comment by shiftkey** [comment]
@gebhushan could you please fill out the template? There are important details like repro steps and log files that haven't been provided yet that will help with troubleshooting.

**Comment by gebhushan** [comment]
Sry about not filling the template but, I have simply deleted the clone repository and cloned it again, which solved all my problems.. and the second reason is that the same branch name was created by one of my teammates few months back, and it created little mess.. I'm good now, but thanks for reaching out.. that gives me a confidence that I can always rely on you..!! I appreciate that..!!
