### ISSUE TITLE
Installation does not set path to git.exe in environment variables  

### ISSUE THREAD

**Issue by thecodester** [desktop/desktop#3801]
When installing GitHub Desktop, the path to Git is not set, so when I open up command prompt I cannot issue Git commands.

Worse yet, after setting the environment variable so the command prompt can execute Git commands, the location of Git changes after every new release of GitHub Desktop, so I have to update the path variable.

The path to GitHub Desktop I use is something like: ...\AppData\Local\GitHubDesktop\app-1.0.12\resources\app\git\cmd. So when release 13 comes out, this path will no longer work.

I have no other Git installed.

**Comment by shiftkey** [comment]
@thecodester thanks for the feedback.

We don't recommend using the embedded Git for many reasons, which I previously outlined here: https://github.com/desktop/desktop/issues/3708#issuecomment-354665183

We recommend installing [Git for Windows](https://git-for-windows.github.io/) and ensuring you check the "add to your `PATH`" option in it's installer.

**Comment by breathe67** [comment]
FWIW I just installed Github Desktop for Windows (GD), then I installed Git for Windows to c:\Program Files\git, choosing to update the PATH in the git for windows installer.  After launching GD, it could not find my git installation when I opened my repo in either Git Bash or the Windows command line. I had to move the git path it from my system environment PATH (i.e. c:\Program Files\git) to my user PATH - after which GD found it.

**Comment by st4rdog** [comment]
I just installed, and it messed up the user variable Path with the recommended "minimal wrappers" option. 2.26.2 Windows installer.

It adds to system variable Path fine, but user Path was cut off:

System Path:
...;E:\Programs\General\Git\cmd

User Path:
...;E:\Progr

**Comment by indcoder** [comment]
Hi @shiftkey  The recommendation by [Git SCM](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) [which is de facto git reference] seems to suggest that GitHub desktop will also update the CLI, which is perhaps contrary to what you are advising in https://github.com/desktop/desktop/issues/3708#issuecomment-354665183 

<img width="538" alt="GitHub Desktop scm" src="https://user-images.githubusercontent.com/2099300/109523379-52296780-7ad5-11eb-9db0-db6c913fc2e0.png">

**Comment by shiftkey** [comment]
@indcoder thanks for the heads up. That's related to the classic GitHub Desktop, which shipped a `Git Shell` environment many moons ago.

I thought I'd found and removed all these references across the internet, but it looks like this is the page http://git-scm.com/book/en/v2/Getting-Started-Installing-Git and the source is from here: https://github.com/progit/progit2/blob/master/book/01-introduction/sections/installing.asc

@billygriffin are you able to help shepherd a fix for this?

**Comment by billygriffin** [comment]
Thanks for the shout @shiftkey! PR here: https://github.com/progit/progit2/pull/1622

**Comment by GreatApo** [comment]
As already mentioned by @shiftkey, it is not recommended to use the embedded git.

That been said, here is a workaround:
1. Create a bat file named git.bat under "%USERPROFILE%\AppData\Local\GitHubDesktop\bin" with the following code:
```
@echo off
set p=Path not found
for /d /r "%~dp0\.." %%A in (app-*.*.*) do set p=%%A
"%p%\resources\app\git\cmd\git.exe" %*
```
2. Add this bat in the environment variables or wherever you need it (e.g. VSCode git.path)
