### ISSUE TITLE
Github Link should warn users if they are not logged in

### ISSUE THREAD

**Issue by Joebeazelman** [desktop/desktop#3805]
I have Github Desktop installed and when I click "Open in Desktop" in Chrome the link takes me to the "https://desktop.github.com/" page instead of opening the repo in GitHub.  This happens when I am not logged in.  The responsible script should warn the user that they are not logged instead of sending them to the download page.  Also, if the page hasn't been refreshed and you log into Github from another tab or Windows, the script isn't aware of the users login status.  This can lead the user to conclude something is wrong. 

This can be fixed by simply disabling the button and labeling it with "Log in to Open in Github Desktop" or something shorter.

**Comment by joshaber** [comment]
Thanks for the feedback @Joebeazelman! This is something we're hoping to improve in the future.

**Comment by j-f1** [comment]
(this issue has been closed since there isn’t anything that needs to be changed in this repository)
