### ISSUE TITLE
Can't checkout a branch on a detached head

### ISSUE THREAD

**Issue by mdiep** [desktop/desktop#3807]
### Description
When you're on a detached head, checking out a branch in Desktop doesn't seem to work. 😞 

### Version
**GitHub Desktop version:** 1.0.12
**OS version:** 10.13.2

### Steps to Reproduce

1. Check out a detached head
1. Cmd-B, type `master`, hit enter

**Expected behavior:** Should now be on `master`

**Actual behavior:** Nothing

**Reproduces how often:** Always

### Logs
Nah, there's nothing relevant in the log.

**Comment by shiftkey** [comment]
@mdiep thanks for the repro - I can see this myself.

I'll dig into what we're doing and see if we can put together a fix.
