### ISSUE TITLE
Github page webpage graphics are off.

### ISSUE THREAD

**Issue by kachroolab** [desktop/desktop#3810]
My webpage shows weird layout missing graphic. What could be the problem?

### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by shiftkey** [comment]
@kachroolab I'm not sure this is related to GitHub Desktop - could you share some screenshots and maybe even a URL so we can understand the situation better?

**Comment by kachroolab** [comment]
The URL is "www.kachroolab.org"

**Comment by kachroolab** [comment]
Solved, I had added a link to a website and strangely that had this weird affect. The removal of the website link restored the graphics and layout.

**Comment by shiftkey** [comment]
@kachroolab thanks for the link. If you get stuck in the future, have a read of the GitHub Pages [resources](https://help.github.com/pages/) we provide.
