### ISSUE TITLE
lock the file/line selection controls while a commit is running

### ISSUE THREAD

**Issue by callumlocke** [desktop/desktop#3814]
### Description

I'm working on a large project that has a slow pre-commit hook (> 10 seconds). Several times, I've used the file checkboxes and individual line selection to do a partial commit, and then without realising the commit is still running, I've started selecting more lines for a second commit. Then I realise the first commit is still running, and it's hard to tell from the UI what is going to get committed.

### Version

**GitHub Desktop version:** 1.0.11

**OS version:** macOS Sierra (10.12.6)

### Steps to Reproduce

1. In a project with a slow pre-commit hook, do a partial commit (just select certain files and/or lines, and then click Commit)
1. While that partial commit is running, try to change the selection of lines/files.

**Expected behavior:**

You shouldn't be able to change the file/line selection while the commit is running.

**Actual behavior:**

You can mess with the file/line selection before the commit is complete, so the UI is now in a state that does not reflect what is really going to get committed.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%.

### Additional information

I'm guessing that the selection is fixed from the moment the commit button is clicked, but if this is the case it would be good if the UI could reflect this. To avoid confusion, I suggest disabling all the checkboxes and line selection controls as soon as the commit button is clicked, and re-enabling them once the commit has succeeded or failed.

**Comment by bangly631** [comment]
![snapshot_20180117](https://user-images.githubusercontent.com/33788088/35100654-d35f30d8-fcc9-11e7-9eef-a547cc417661.JPG)

**Comment by bangly631** [comment]
![snapshot_20180117](https://user-images.githubusercontent.com/33788088/35100680-f46c03b4-fcc9-11e7-8adb-2316ac8ce952.JPG)
![snapshot_20180117](https://user-images.githubusercontent.com/33788088/35100675-edf72a4a-fcc9-11e7-958b-aa802044699e.JPG)

**Comment by shiftkey** [comment]
@callumlocke this is an interesting idea, and something that probably needs some design input to ensure the lock/unlock transition isn't overwhelming.

For reference, we're already tracking the `isCommitting` state at the repository level (so we can disable the commit form), and flowing that down into the other components so they can enable/disable themselves is probably worth exploring:

https://github.com/desktop/desktop/blob/6df8a6906c18b70af916039f2e1f38ce0fe98ad1/app/src/ui/repository.tsx#L96

**Comment by iAmWillShepherd** [comment]
What would happen if the commit fails? Should the file remain locked?

**Comment by j-f1** [comment]
I’d say no, because that would prevent you from committing something slightly different to fix the commit.

**Comment by shiftkey** [comment]
@iAmWillShepherd @j-f1 the concept of "locking" is only specific to the UI in Desktop - if the commit fails, everything should be "unlocked" in case the user wants to make changes before trying again

**Comment by iAmWillShepherd** [comment]
Thanks for that clarification, @shiftkey.

**Comment by iAmWillShepherd** [comment]
Fixed in #4042.

**Comment by shiftkey** [comment]
#4042 only addresses the commit form textboxes - this issue is related to the partial committing functionality in the diff view, and remains unresolved.

**Comment by iAmWillShepherd** [comment]
@shiftkey oops, my bad!

**Comment by masungwon** [comment]
@outofambit Could you assign me and @erin-lee to this task? We're almost done with the PR.

**Comment by outofambit** [comment]
@masungwon @erin-lee i can't assign you due to some weird settings on our project but I marked it as in progress on our project board! You're good to go!

**Comment by shiftkey** [comment]
#5341 deals with the changed file checkboxes, but the other part of this is the partial line selections in the diff:

<img width="476" src="https://user-images.githubusercontent.com/359239/43663027-572d387e-973e-11e8-8541-8e8b39f3fc3a.png">

If you wanted to look into that, the relevant property to control the behaviour is `readOnly` in `TextDiff.tsx`:

https://github.com/desktop/desktop/blob/13b21a8984dff413dfb7863209d1b695a8725237/app/src/ui/diff/text-diff.tsx#L76-L83

There might need to be some extra work here to plumb `isCommitting` around - it's been a while since I've been in there...
