### ISSUE TITLE
Branch alphabetising is not case-insensitive

### ISSUE THREAD

**Issue by meyer** [desktop/desktop#3819]
### Description

![image](https://user-images.githubusercontent.com/13781/35131894-743a3c0c-fc7d-11e7-9c70-52b9f2f57480.png)

### Version

**GitHub Desktop version:** 1.0.12

**OS version:** macOS 10.13.2

### Steps to Reproduce

1. Name a branch with an uppercase initial letter.
2. Watch it sort to the top.

**Expected behavior:** Sorting is not affected by case.

**Actual behavior:** Sorting is affected by case.

**Reproduces how often:** 100% of the time, every time

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

The sort order for branch names is intentional. We want to remain consistent with GitHub.com's sort order for branches.

**Comment by meyer** [comment]
@iAmWillShepherd gotcha. That makes sense. Is there a way to file this issue for github.com? I understand _why_ it’s sorting capital letters before lowercase. Just seems quite counterintuitive. I don’t have any context around internal discussions on the matter though.

**Comment by shiftkey** [comment]
>  I understand why it’s sorting capital letters before lowercase. Just seems quite counterintuitive.

This is also how Git lists branches:

```
$ git branch
  AAAAA
  Monkey
* aaab
  master
```

**Comment by meyer** [comment]
@shiftkey git doesn’t seem to have been designed to be first and foremost an _intuitive_ program, so the fact that it doesn’t downcase before sort is entirely unsurprising. Computers will alphabetise uppercase things before lowercase things unless a human intervenes. My assumption is that these git UIs (GitHub, GitHub Desktop) are aiming to be intuitive, which would mean deviating from default git behaviour when the result is improved usability.

The pattern I’m following here is operating system directory listing behaviour. Both Windows and OSX sort files and folder case-insensitively. Scanning one list of things instead of two to find a list item seems intuitive to me, but that might just be my opinion.

**Comment by shiftkey** [comment]
> The pattern I’m following here is operating system directory listing behaviour. Both Windows and OSX sort files and folder case-insensitively. 

That's ideal in this case because these filesystems are case-insensitive by default.

**Comment by meyer** [comment]
@shiftkey whether or not the filesystem is case-insensitive has absolutely no effect on how files are sorted. The Finder sort algorithm was intentionally designed by humans to be _intuitive_. For example, say you have ten files, numbered from 1 to 10. A computer would sort the files like so:

```js
[1, 10, 2, 3, 4, 5, 6, 7, 8, 9]
//  ^^ not great :/
```

Quite useless. So someone at Apple who gave (and hopefully still gives) a shit wrote a custom compare function that sorts files the way that _humans expect things to be sorted_. The result is exactly what you would expect:

```js
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
//                          ^^ there we go
```

That’s why it’s _intuitive_. It just makes sense.

Computer:

![image](https://user-images.githubusercontent.com/13781/35176635-40595546-fd2f-11e7-9d15-25c71831f017.png)

Human:

![image](https://user-images.githubusercontent.com/13781/35176656-63041c48-fd2f-11e7-95d2-bf3e6cedc7a9.png)

I don’t really want to darken too many more pixels on this topic, especially in a closed issue. Thanks for the input. Let me know if you all change your mind, or if there’s somewhere I can create an issue for GitHub.com.

**Comment by shiftkey** [comment]
@meyer apologies for being blunt - this isn't really an issue I've cared about in all my years working with Git, and I've been bitten in the past when I've deviated from Git's behaviour despite meaning well so I'm always a bit nervous about these sorts of situations.

I'll reopen this and let others sound off on it.

**Comment by meyer** [comment]
@shiftkey no worries, nothing to apologise about. I didn’t realise I cared about the topic until I started using GitHub Desktop. I almost never see my branches alphabetically sorted (I use an alias in the CLI that sorts branches by most recent commit) and the two groups thing _really_ stuck out. Seemed like someone missed a spot.

If it’s any use, repositories are sorted case-insensitively by name in the app. On GitHub.com repositories are sorted by most recent commit. Both quite useful sorts.

**Comment by shiftkey** [comment]
This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by billygriffin** [comment]
Thanks for the feedback @meyer! This isn't something we hear super frequently, though I agree that it does make it somewhat confusing. I'm going to roll this into #4327 as it's also related to how we group branches in the app. I can't promise we're going to do anything here as it hasn't surfaced as a pain point from many users, but we'll definitely consider it as we look at whether it makes sense to iterate on the branch ordering/grouping. Thanks again!

**Comment by tms-bwa** [comment]
I am not a computer. I am a human being.
And I want case-insensitive sorting.
