### ISSUE TITLE
no keyboard shortcut for selecting all entries in changes list

### ISSUE THREAD

**Issue by meyer** [desktop/desktop#3821]
### Version

**GitHub Desktop version:** 1.0.12

**OS Version:** macOS

**Expected behavior:**
- Command-A selects all modified files

**Actual behavior:**
- Command-A selects some text.

**Comment by shiftkey** [comment]
@meyer thanks for the feedback.

We're already tracking multi-selection in #1712, so I'll amend this issue to focus on "Select All".

**Comment by shiftkey** [comment]
I was hoping that #4188 would address this, but it looks like **Edit** | **Select All** is hijacked by the application and nothing happens (at least on macOS).

After that lands, I think we'll need to revisit this and see if we can figure out, if the changes list has keyboard focus, select all items in the list.
