### ISSUE TITLE
Issue with commits after latest GitHub Desktop update

### ISSUE THREAD

**Issue by elbertlumenier** [desktop/desktop#3827]
Hello,

After installing the latest GitHub Desktop update, the client crashes when commiting changes. This was tested with committing code to several branches and master.

The error from the desktop client is:

Error: write EOF
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite (net.js:813:14)

Version: 1.0.12
OS: Windows 10.0.16299

Kind Regards,

Elbert Lumenier

**Comment by shiftkey** [comment]
@elbertlumenier we've got a couple of issues which are similar to this (#2041 #3370) and I've not been able to reproduce this on my end - are you able to share a repro of this, or more details about the shape of the commit which triggered the error?

**Comment by elbertlumenier** [comment]
Hi @shiftkey, what information do I need to provide (repro)?
As for the commit, I created a new branch and then imported/overwrote the code from an outside source (offline) machine, which had a more recent version of the same project but was not running Git(Hub).

**Comment by iAmWillShepherd** [comment]
@elbertlumenier we just need the steps you took to get to this error. For an example, check out #3753. Including your logs wouldn't hurt either. Please be sure to review our [guide](https://github.com/desktop/desktop/blob/master/CONTRIBUTING.md#reporting-bugs) for creating issues.

**Comment by shiftkey** [comment]
There's a few of these issues without clear steps to reproduce the issue, so I'm going to close this out in favour of the original issue #2041 which is still open.
