### ISSUE TITLE
Auditing our index.ts|tsx files

### ISSUE THREAD

**Issue by niik** [desktop/desktop#383]
We're using [folders more and more](https://github.com/desktop/desktop/tree/4df70c1ba633703af59760531c93387167c4ecb4/app/src/ui/autocompletion) to logically group classes and components and I think that's fantastic. I wonder, however, if we should consider naming the files after what they contain and leaving the index.ts/index.tsx files as pure export files.

I have too many index.tsx files open in tabs right now and it's harder than it needs to be to find the right one.

Anyone against renaming our index files to what their primary contents is and adding an export-only index.ts in their place?

**Comment by j-f1** [comment]
<details><summary><code>index.{ts,tsx}</code> only containing <code>export * from 'x'</code> and <code>export { foo, bar } from 'x'</code> lines</summary>

```
app/src/lib/dispatcher/index.ts
app/src/lib/editors/index.ts
app/src/lib/git/index.ts
app/src/lib/progress/index.ts
app/src/lib/shells/index.ts
app/src/lib/stats/index.ts
app/src/main-process/menu/index.ts
app/src/ui/about/index.ts
app/src/ui/acknowledgements/index.ts
app/src/ui/add-repository/index.tsx
app/src/ui/app-menu/index.ts
app/src/ui/blank-slate/index.ts
app/src/ui/cli-installed/index.ts
app/src/ui/dialog/index.ts
app/src/ui/diff/image-diffs/index.ts
app/src/ui/editor/index.ts
app/src/ui/generic-git-auth/index.ts
app/src/ui/install-git/index.ts
app/src/ui/lib/vertical-segmented-control/index.ts
app/src/ui/merge-branch/index.ts
app/src/ui/octicons/index.ts
app/src/ui/preferences/index.ts
app/src/ui/publish-repository/index.ts
app/src/ui/repository-settings/index.ts
app/src/ui/resizable/index.ts
app/src/ui/shell/index.ts
app/src/ui/sign-in/index.ts
app/src/ui/terms-and-conditions/index.ts
app/src/ui/toolbar/index.tsx
app/src/ui/untrusted-certificate/index.ts
app/src/ui/updates/index.ts
app/src/ui/welcome/index.ts
```
</details>

<p>

`index.{ts,x}` files that don’t just re-export other exports:

- [ ] [`app/src/crash/index.tsx`](https://github.com/desktop/desktop/blob/master/app/src/crash/index.tsx) — rename to `main.tsx`?
- [ ] [`app/src/ui/autocompletion/index.tsx`](https://github.com/desktop/desktop/blob/master/app/src/ui/autocompletion/index.tsx) — move `Autocompleting*` to `autocompleting-text-input.tsx`, `IAutocompletionProvider` to a new file?
- [ ] [`app/src/ui/branches/index.tsx`](https://github.com/desktop/desktop/blob/master/app/src/ui/branches/index.tsx)
- [ ] [`app/src/ui/changes/index.tsx`](https://github.com/desktop/desktop/blob/master/app/src/ui/changes/index.tsx)
- [ ] [`app/src/ui/create-branch/index.tsx`](https://github.com/desktop/desktop/blob/master/app/src/ui/create-branch/index.tsx)
- [ ] [`app/src/ui/delete-branch/index.tsx`](https://github.com/desktop/desktop/blob/master/app/src/ui/delete-branch/index.tsx)
- [ ] [`app/src/ui/diff/index.tsx`](https://github.com/desktop/desktop/blob/master/app/src/ui/diff/index.tsx)
- [ ] [`app/src/ui/discard-changes/index.tsx`](https://github.com/desktop/desktop/blob/master/app/src/ui/discard-changes/index.tsx)
- [ ] [`app/src/ui/history/index.tsx`](https://github.com/desktop/desktop/blob/master/app/src/ui/history/index.tsx)
- [ ] [`app/src/ui/index.tsx`](https://github.com/desktop/desktop/blob/master/app/src/ui/index.tsx) — rename to `main.tsx`?
- [ ] [`app/src/ui/rename-branch/index.tsx`](https://github.com/desktop/desktop/blob/master/app/src/ui/rename-branch/index.tsx)
- [ ] [`app/src/ui/repositories-list/index.tsx`](https://github.com/desktop/desktop/blob/master/app/src/ui/repositories-list/index.tsx)

**Comment by shiftkey** [comment]
I've removed `src/ui/index.tsx` and `src/crash/index.tsx` from this list because they're referenced as entry points in webpack - so they're slightly different to the others.
