### ISSUE TITLE
unable to install Desktop as regular user on Windows (admin works)

### ISSUE THREAD

**Issue by Anti-Li** [desktop/desktop#3836]
Description
[When I open GitHubDesktop.exe in common user, GitHub Desktop was not downloaded and I can't open it.When I open in Administrator, it can work normally.]

Version
GitHub Desktop version: [The newest version 1.0.12]

OS version: [Windows 10 Home .1709]

**Comment by shiftkey** [comment]
@Anti-Li thanks for the report!

> GitHub Desktop was not downloaded and I can't open it

It's not clear to me what's happening here - the installer should contain everything it needs to install and start, and the installer is designed to work without being elevated to an administrator account.

Could you provide more details about what happens here? Any error messages displayed?

**Comment by nerdneha** [comment]
Hey @Anti-Li, I'm going to close this out due to inactivity but if you can provide more details about the issue, we're happy to re-open and help!

**Comment by jhoobergs** [comment]
Installation works without admin access, but I can't use it without admin access.
When I open the application, it asks me to configure git, but the 'continue' button doesn't do anything (no error message either).
When I run it as administrator, the continue button works.
Hope this helps ?
