### ISSUE TITLE
Make the app available on the OS X App Store?

### ISSUE THREAD

**Issue by yvan-sraka** [desktop/desktop#3837]
Hello,

I do not see any problem related to this in this repository after a quick search.

It could be really nice to let the application available in the OS X App Store! I do not know if there is a restriction or a good reason why the app is not already available now?

Thank you for those who could give me an answer.

**Comment by creyD** [comment]
@yvan-sraka Hey. I believe that it isn't worth it. You have to pay to offer in the macOS App Store (see [here](https://developer.apple.com/support/compare-memberships/)). As the app would still be free (i guess), this would be wasted money, bc they can just host it on their own servers.

**Comment by shiftkey** [comment]
@yvan-sraka thanks for the suggestion!

While Electron apps can be targeted for distribution in the Mac App Store, it's not a scenario we're planning to support - we've already got the infrastructure in place for distributing installers and updating apps.

By not being in the App Store, we're free to publish updates whenever they're ready - without the overhead of the review process.
