### ISSUE TITLE
write EOF when committing large number of files

### ISSUE THREAD

**Issue by davidrajdgl** [desktop/desktop#3848]
### Description

Error: write EOF
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite (net.js:813:14)

### Version

Version: OS: Windows 10.0.16299

**GitHub Desktop version:** 1.0.12

**OS version:** Windows 10.0.16299
### Steps to Reproduce

1. Add some files of big size
1. Try to commit to master

**Expected behavior:** Commiting to Master

**Actual behavior:** It gave me the above mentioned error in a new dialog box.
**Reproduces how often:** Currently I have 10 times and all the 10 times it gave the error

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

Would you mind sharing you log file?

**Comment by davidrajdgl** [comment]
I have found that, I have tried to upload more than 100 files at a time, which caused a problem.
Now, I am uploading set by set which is fewer than 100 files. I am sorry, I dont know how to get the log file. If possible, help me in identifying the log file so that I can share that also

**Comment by j-f1** [comment]
@davidrajdgl The one with the date you encountered the problem in its name should have the information we need.

**Comment by agisilaos** [comment]
@davidrajdgl To find the logs you need to go in the Help menu -> Show Logs in Finder and then as @j-f1 suggested you need to find the one with the date that the issue you wrote about occurred! Hope that helps.

**Comment by shiftkey** [comment]
There's a few of these issues without clear steps to reproduce the issue, so I'm going to close this out in favour of the original issue #2041 which is still open. Please follow along with that issue.
