### ISSUE TITLE
Permission changes are not shown in GitHub Desktop

### ISSUE THREAD

**Issue by tooomm** [desktop/desktop#3858]
### Description

Changes to permissions are shown on the GitHub website, but not in the client:
![file attributes](https://user-images.githubusercontent.com/9874850/35404176-551c2e04-0202-11e8-82c7-bba80701c7a9.png)

### Version

**GitHub Desktop version:** 1.0.12

**OS version:** Microsoft Windows [Version 10.0.16299.125]

**Comment by shiftkey** [comment]
@tooomm thanks for the feedback. We're tracking this in #557, so please follow along with that issue.
