### ISSUE TITLE
noticeable delay when viewing working directory diff for .htaccess file

### ISSUE THREAD

**Issue by alexhawke** [desktop/desktop#3859]
### Description

When viewing the changes for a .htaccess file, GitHub Desktop states "No local changes", then after a delay of around 5 seconds it shows the .htaccess file changes.

This only occurs for uncommited changes, not historical commits.

### Version

**GitHub Desktop version:** 1.0.12

**OS version:** macOS 10.13.2

### Steps to Reproduce

1. Add .htaccess file to repository and commit
2. Make changes to .htaccess and open GitHub Desktop to view changes

**Expected behavior:** Instantly show file changes

**Actual behavior:** 5 second delay before showing changes

**Reproduces how often:** 100%

### Preview

<img width="1054" alt="nochanges" src="https://user-images.githubusercontent.com/849440/35404694-cf626b4e-01fb-11e8-99fe-89e0952d52c1.png">

**Comment by shiftkey** [comment]
@alexhawke can you share some details about your `.htaccess` file, to help with reproducing the issue: 
 
 - What's the size on disk?
 - Are there any long lines that are being changed?

If you can share the file contents that would be great, but even some approximation of the file would help with troubleshooting.

**Comment by shiftkey** [comment]
Closing this out as inactive. @alexhawke if you can answer the questions above we're happy to revisit this issue.
