### ISSUE TITLE
Mac version not opening

### ISSUE THREAD

**Issue by jcgter777** [desktop/desktop#3862]
Every time I open the app, it gives the error:
"GitHub Desktop.app" is damaged and can't be opened. you should move it to the Trash.

If it helps, I have Mac OSX 10.9.4. I've already redownloaded it multiple times.

**Comment by iAmWillShepherd** [comment]
Could you attach your log file to this issue please? 🙏

**Comment by jcgter777** [comment]
I managed to fix it. I just had some "too tight" security settings.

**Comment by AmeeRamy** [comment]
I am an Arab man who does not speak or understand English
Please do not email me anymore
Thank you



________________________________
