### ISSUE TITLE
Default Project Download location option is not available in the software

### ISSUE THREAD

**Issue by aukaurea** [desktop/desktop#3863]
Default Project Download location option is not available in the software.

None of the options shows where to download the  projects as default (directory)

![image](https://user-images.githubusercontent.com/28142889/35436809-0f75f5b6-02ba-11e8-8b58-c3e357aebb73.png)

**Comment by iAmWillShepherd** [comment]
You set your clone path during the cloning process. Note the _Local Path_ text input.

![2018-01-26_09-58-21 023](https://user-images.githubusercontent.com/1715082/35448343-a2133cc0-027f-11e8-8047-8f312d280278.png)
![2018-01-26_09-58-56 607](https://user-images.githubusercontent.com/1715082/35448344-a22ce544-027f-11e8-9140-b9d03dc15120.png)
![2018-01-26_09-59-06 281](https://user-images.githubusercontent.com/1715082/35448345-a23ec4d0-027f-11e8-90b0-565a1149c50f.png)
