### ISSUE TITLE
enhancement: provide search for files in `Changes` tab

### ISSUE THREAD

**Issue by recp** [desktop/desktop#3864]
### Description

I have lot of uncommitted files so I can't find files which I want to commit easily. There are lot of uncommitted stuff because I'm testing some feature then committing it, while doing this I'm making some changes on some files for future. Then I'm working on uncommitted stuff but I change another files... 

Searching / filtering files in `Changes` tab would make things more comfortable. Ordering in  `Changes` tab is also weird. It order files by name but not by folder. 

For instance:
...
`src/light/light.c`
`src/memory.c`
`src/node.c`
`src/pass/pas_out.c`
`src/transform.c` <-- I need to commit this to fix a bug but it is hard to find it in list
`src/transp/transp.c`
...

Expected behavior: first order files by name then order folders by name (recursively)
...
`src/memory.c`
`src/node.c`
`src/transform.c` <-- 
`src/light/light.c`
`src/pass/pas_out.c`
`src/transp/transp.c`
...

or tree view could also help like SourceTree.app

### Version

**GitHub Desktop version:**  1.0.13-beta1

**OS version:** macOS High Sierra, 10.13.3 ( 17D47 )

**Comment by j-f1** [comment]
I opened a PR that added a “filter” box to this list in #2046, If the design team would like me to work off of this code to add a filter box to the changes list, I’d be happy to do so.

**Comment by AmeeRamy** [comment]
I am an Arab man who does not speak or understand English
Please do not email me anymore
Thank you



________________________________

**Comment by j-f1** [comment]
Sorry to bother you, @AmeeRamy. If you go to https://github.com/settings/notifications, you can uncheck all of the “Email” options to avoid getting emails from GitHub.

---

آسف لإزعاجك، @AmeeRamy. إذا ذهبت إلى https://github.com/settings/notifications، يمكنك إلغاء تحديد كل من "Email" خيارات لتجنب الحصول على رسائل البريد الإلكتروني من جيثب.

(ترجمة جوجل المستخدمة، يرجى عذر أي أخطاء)

**Comment by shiftkey** [comment]
@recp thanks for the suggestion!

We have an open proposal for a very similar feature reported in #2030 - the only difference is it was for filtering files in a commit. I've added your suggestion there instead of tracking duplicate issues.

**Comment by andrew-sidereal** [comment]
This seems like extremely basic functionality which is missing. In large projects, this is unusable. I need a way to search by file extension, name, etc. It's in every other source control GUI I've used. https://i.imgur.com/ddQa7Ar.png

**Comment by VinzzF** [comment]
Yes, I can't believe this still isn't a thing. Needed particularly when merging large codebases or introducing GIT versioning to them.

**Comment by Ramazan433** [comment]
https://github.com/Ramazan433/friendly-octo-guide.git

**Comment by Ramazan433** [comment]
https://github.com/Ramazan433/jubilant-pancake.git
