### ISSUE TITLE
COLUMN SELECTION

### ISSUE THREAD

**Issue by kert-io** [desktop/desktop#3874]
Really guys, why is this still option.  According to your closed issues, this was solve in august 2017.  

### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by shiftkey** [comment]
@kert-io I'm not sure I understand the problem or the past issue you are referring to. Could you provide more information?

**Comment by shiftkey** [comment]
Closing this out as inactive. @kert-io if you can answer the questions above I'm happy to revisit this issue.
