### ISSUE TITLE
fatal: unable to access 'https://github.com/': Could not resolve proxy: aproxy

### ISSUE THREAD

**Issue by sajidyar** [desktop/desktop#3878]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. connect a VPN
2. Generate a pull request this will occur on that.
3. I tried after disconnecting the VPN then it was happening again and again, this error isn't going in any way.

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by j-f1** [comment]
Thanks for reaching out!

We require the template to be filled out when submitting all issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀

**Comment by sajidyar** [comment]
![image](https://user-images.githubusercontent.com/34439033/35520552-27cf73c2-0539-11e8-8e86-ffddc0ec2702.png)

**Comment by shiftkey** [comment]
@sajidyar 

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by shiftkey** [comment]
Closing this out as inactive. @sajidyar if you're able to provide the logs when this issue occurs we're happy to revisit this issue.

**Comment by pmb-sd** [comment]
I have the same issue.  
 here is the log entry on my system that is entered right when i try to push a change.

"2018-06-21T23:52:26.112Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: website - pmb-sd (has token)
2018-06-21T23:52:26.149Z - error: [ui] `git -c credential.helper= push origin master:master --progress` exited with an unexpected code: 128.
fatal: unable to access 'https://github.com/PacificMercantileBank/website.git/': Could not resolve proxy: $ProxyAddress"

**Comment by pmb-sd** [comment]
I checked in terminal if I could see $ProxyAddress and I can.

**Comment by pmb-sd** [comment]
Oh and one more nugget. things worked fine till yesterday afternoon... then POOF. not sure what changed.

**Comment by pmb-sd** [comment]
oh, and the old GitHub application works fine. the new one GitHub Desktop is the one with this issue.

**Comment by shiftkey** [comment]
@pmb-sd ` Could not resolve proxy: $ProxyAddress` suggests that it might be a DNS issue - is this happening for all `fetch`/`push`/`pull` operations, or is it intermittent and you see some of these operations succeed without errors in the log file?

**Comment by pmb-sd** [comment]
it effects ALL attempts to connect that I have tried. (I don't use the terminal version of git)  the older GitHub application still works fine, and does the website...

**Comment by Deepak2607** [comment]
Run the below command 
`git config --global --unset http.proxy`

**Comment by dodds-steven** [comment]
I didn’t use this command, but I did find I had a proxy configured in my .bash_profile

Commented out and Poof it works

**Comment by GokulaAdabala** [comment]
Thanks Deepak. It's working. Run the below command in jenkins server 
git config --global --unset http.proxy

**Comment by saiKrishnaAnumu** [comment]
git config --global --unset http.proxy
it worked for me

**Comment by ayushshaz** [comment]
"service apache2 stop " and then it worked for me

**Comment by itzdjelal** [comment]
idk how i do that

**Comment by SUCHITRAGIRI** [comment]
> Run the below command
> `git config --global --unset http.proxy`

Thank you @Deepak2607 It's worked for me.

**Comment by dhrupal78** [comment]
fatal: unable to access 'https://github.com/Hygieia/UI.git/': Could not resolve proxy: proxy.server.com

Can anyone send me a step to solve this issues?

**Comment by itamarorg** [comment]
> Ejecute el siguiente comando
> `git config --global --unset http.proxy`

esto me ha resuelto

**Comment by klesiossss** [comment]
Thank you @Deepak2607 it worked for me!
git config --global --unset http.proxy

**Comment by Rossfear** [comment]
> > Run the below command
> > `git config --global --unset http.proxy`
> 
> Thank you @Deepak2607 It's worked for me.

**Comment by nishkakhendry** [comment]
hi! `git config --global --unset http.proxy` and  `git config --global --unset https.proxy` did not work for me but `export https_proxy=` did. https://stackoverflow.com/questions/32268986/git-how-to-remove-proxy

**Comment by MartinhoMCM** [comment]
> Run the below command
> `git config --global --unset http.proxy`

Thanks, it helped me.

**Comment by aliifam** [comment]
> ### [<img alt="@Deepak2607" width="20" height="20" src="https://avatars.githubusercontent.com/u/34836138?s=60&amp;u=43f5037c1edc0964616fe29eaeb4aea32a76c35a&amp;v=4">](/Deepak2607) ** [Deepak2607](/Deepak2607)**

thank you this work with me

**Comment by tancrede-sallerin** [comment]
None of this worked for me

**Comment by sharjeelyaqoob389** [comment]
can you please help me out how can i solve this problem.

"Cloning into 'TFODCourse'...
fatal: unable to access 'https://github.com/nicknochnack/TFODCourse/': Could not resolve host: github.com"

if you know please email me the answer.

email: [sharjeelyaqoob389@gamail.com](mailto:sharjeelyaqoob389@gamail.com)

**Comment by noudevdls** [comment]
git config --global --unset http.proxy

**Comment by Kassu445K** [comment]
I'm wonder if you help me out how can i solve the bellow problem; thanks 

"git clone https://github.com/mininet-optical/mininet-optical
Cloning into 'mininet-optical'...
fatal: unable to access 'https://github.com/mininet-optical/mininet-optical/': Operation timed out after 300036 milliseconds with 0 out of 0 bytes received"
