### ISSUE TITLE
Commit messages should be wrapped at 72 chars

### ISSUE THREAD

**Issue by fatcerberus** [desktop/desktop#3885]
In the original GitHub for Windows client, long commit messages would automatically be word-wrapped at 72 characters when committed.  This makes commit logs look nice when viewed on the command line.  GitHub Desktop doesn't appear to wrap such messages at all, simply committing the whole message as one long line.  When viewed on the terminal, long messages like this can be wrapped in the middle of a word making them more difficult to read.

Can word wrapping be added, perhaps with a customizable wrap width?  Between this, and the lack of a Dark theme, I think I'll be using the old client for a while longer...

**Comment by niik** [comment]
Hey @fatcerberus, this issue is being tracked in https://github.com/desktop/desktop/issues/62 so please head over there and add your thoughts to the discussion!

**Comment by fatcerberus** [comment]
When I opened this I had a feeling it was something someone would have reported already, but I searched for "word wrap" and turned up no relevant issues.  Turns out I should have searched for "hard wrap" instead.  Go figure. 😄
