### ISSUE TITLE
why am I getting this error?fatal: unable to access 'https://github.com/RacheLev/project-2-personal-page.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

### ISSUE THREAD

**Issue by RacheLev** [desktop/desktop#3889]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by shiftkey** [comment]
@RacheLev the issues you are encountering occurs when using Git on a network that blocks access to the revocation checks when verifying a SSL/TLS connection is secure.

I'm working on getting a fix into Git for Windows here: https://github.com/git-for-windows/git/pull/1450 and once that is fixed we're tracking making this experience more friendly in #3326 to help with applying that fix. Please follow along with that issue for tracking the proper resolution.

To workaround this in the meantime, you can revert to the old OpenSSL behaviour:

```
$ git config --global http.sslBackend "openssl"
$ git config --global http.sslCAInfo [path to .pem file]
```
OpenSSL requires it's own certificate file to use for validation, and [this PEM file](https://curl.haxx.se/docs/caextract.html) distributed by the cURL team should do the trick.

**Comment by RacheLev** [comment]
Thank you! Fixed it. Not getting the error anymore, but for some reason its
not letting me click 'commit to master'.
Why is that?
Thank you!
בתאריך 31 בינו׳ 2018 4:06 לפנה״צ,‏ "Brendan Forster" <
notifications@github.com> כתב:

**Comment by shiftkey** [comment]
@RacheLev please open a new issue and fill out the template - the details will help with troubleshooting

**Comment by Tuchy** [comment]
> git config --global http.sslBackend "openssl"

This just worked fine and helped me fix the Github Desktop problem. Thanks man!

**Comment by SiebeBosch** [comment]
Sorry for the newbie question, but can anyone point out where to execute

`git config --global http.sslBackend "openssl"`?

I tried to execute it in the command prompt, but git is not recognized.

**Comment by tjs-git** [comment]
@SiebeBosch You need to install `git`. https://help.github.com/articles/set-up-git/

**Comment by Zenahr** [comment]
For anyone running into this problem in 2020: Make sure to check your Firewall settings if you're working on a Windows machine. That fixed the issue for me.

**Comment by raspyweather** [comment]
One problem I found on my machine was an out of sync clock. Just in case someone stumbles upon this issue as well.

**Comment by yugantk** [comment]
This command will work -> **git config --global http.sslVerify false**

**Comment by raspyweather** [comment]
> 
> 
> This command will work -> **git config --global http.sslVerify false**

Sure, but it's still a pretty bad choice having to deactivate crypto.

**Comment by FlorisDevreese** [comment]
> For anyone running into this problem in 2020: Make sure to check your Firewall settings if you're working on a Windows machine. That fixed the issue for me.

Do you know which firewall rule was getting in the way?

**Comment by Zenahr** [comment]
@FlorisDevreese I actually deactivated my firewall entirely. Not recommended but it helped in that instance...

The answer is **no**.

**Comment by FlorisDevreese** [comment]
@Zenahr Thanks for your response.

For me [this](https://stackoverflow.com/a/53090169/3506115) was the case.

Fixed it by running:
```cmd
git config --global http.schannelCheckRevoke false
```

**Comment by DryreL** [comment]
> This command will work -> **git config --global http.sslVerify false**

Thank you, it worked!
![image](https://user-images.githubusercontent.com/20909077/126578267-7d93cf80-70d9-4c7c-b481-a9c5de28ba84.png)
