### ISSUE TITLE
commit summary and description not disabled when committing

### ISSUE THREAD

**Issue by Anti-Li** [desktop/desktop#3893]
I submit a new version. When the Desktop is submiting, I can still write the Summary or Describtion. If I write down sth. new there, the version won't be submited.
I think the Desktop should disabled the Summary and Describtion textbox when the project is submiting.
Use a very slow internet connection or submit a very big changes to reappear this bug.

**Comment by shiftkey** [comment]
@Anti-Li thanks for the feedback!

> When the Desktop is submiting, I can still write the Summary or Describtion. If I write down sth. new there, the version won't be submited.

This feels similar to #3814, which talked about locking down the changes if a commit takes a while.

> Use a very slow internet connection or submit a very big changes to reappear this bug.

Committing doesn't depend on your internet connection, but committing a large number of changes is likely to demonstrate this issue

**Comment by shiftkey** [comment]
Marking this as `help-wanted` if someone wants to explore addressing this issue. Happy to share some suggestions and further ideas about how to tackle this.
