### ISSUE TITLE
The Co-authors field is not cleared when creating a commit.

### ISSUE THREAD

**Issue by Haacked** [desktop/desktop#3895]
When I specify Co-authors and then create a commit, the co-authors field remains populated. But the Summary and Description fields are cleared.

This goes against my expectations. I didn't even notice it and ended up creating multiple commits with the same co-author.

I'd expect that when a commit is created, all the commit fields are cleared including Co-authors.

**Comment by shiftkey** [comment]
@Haacked I asked about this last week and got this reply from @niik:

> This is expected and intended behavior. The scenario we're primarily supporting are people who pair during their day and need to make multiple commits with the same attribution

I can empathise with the pain of having to re-add contributors if you're making frequent commits over the course of a session, so I'm fine with that behaviour rather than being over-eager to clear the form.

**Comment by Haacked** [comment]
👍
