### ISSUE TITLE
Using different name/email for Enterprise and GitHub.com accounts

### ISSUE THREAD

**Issue by air237** [desktop/desktop#3898]
### Description

I use the Desktop for Enterprise and GitHub.com accounts as well.
My Enterprise and GitHub.com account email is different.
I don't want to change this only one property when I contribute for a different account.

I'd like to set different email (and name) in the Git tab of the Preferences window.

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** macOS 10.13.3

**Comment by shiftkey** [comment]
@air237 thanks for the feedback! 

> I'd like to set different email (and name) in the Git tab of the Preferences window.

The Git preferences window here is for the global Git configuration, so changing this won't address the issue of managing GitHub and GitHub Enterprise repositories which belong to different accounts.

We had a similar discussion to this in #2829, so please add your thoughts to that issue about this problem.

I also mentioned a workaround in #2829 to set your commit email per-repository through the command line:

```
git config --local user.email myCrpyticUserName@company.com
```

Once you've done that, it will override what Git has setup globally. Hope that helps!

**Comment by air237** [comment]
Thanks!
I'll follow discussion #2829. Sorry for not founding it earlier.
I close this issue.
