### ISSUE TITLE
No "Add Co-Authors" button

### ISSUE THREAD

**Issue by helaili** [desktop/desktop#3899]
### Description

Excited about this new feature I've updated my GitHub Desktop on Mac but I don't have a button to click 😢 

![image](https://user-images.githubusercontent.com/2787414/35624050-129a4030-068e-11e8-8264-64754e047489.png)

### Version

**GitHub Desktop version:**  1.0.13

**OS version:** macOS High Sierra

### Steps to Reproduce

1. Launch Desktop 
1. Add a local repository with non committed changes
1. Scratch my head 

### Logs

[2018-01-31.desktop.production.log](https://github.com/desktop/desktop/files/1681721/2018-01-31.desktop.production.log)

**Comment by j-f1** [comment]
It looks like it’s currently only supported in GitHub repositories right now.

**Comment by helaili** [comment]
Thanks @j-f1 you put me on the right path ✨  

I wasn't logged in github.com within Desktop. Now I am it's showing up! Not sure if it's a feature or a bug though.

**Comment by iAmWillShepherd** [comment]
@helaili, no this is not a bug. We decided we'd focus on delivering a cohesive experience with GitHub.com to start.

**Comment by justingolden21** [comment]
I know this is an old ticket, but is it possible to remove this button from the UI? I've never used this and never will, and hundreds of times a day it takes me an extra tab key to push at home, while at work it's one less tab key. It's muscle memory for something I do thousands of times, and it's inconsistent, and it's for such a minor feature. I'm not saying the option shouldn't exist, just that we should be able to disable it.
