### ISSUE TITLE
Databases Schema Change

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#3903]
I've been putting in work trying to understand the underlying data-model the app uses.

So far, I've produced two diagrams of our application's data model.

**Legend**
* `Database` **green**
* `GitHubUserDatabase` **blue**
* `IssuesDatabase` **orange**
* `PullRequestDatabase` **red**
* ~`StatsDatabase`~

_Note that I did not include the `StatsDatabase` in the ER Diagram._

## Current
![github desktop](https://user-images.githubusercontent.com/1715082/35654545-46581d3c-06b3-11e8-8fb7-56321f43b785.png)

## Proposed [WIP]
![github desktop proposed](https://user-images.githubusercontent.com/1715082/35654553-4ada0a3c-06b3-11e8-96a6-06cb31d99ab5.png)

**Comment by iAmWillShepherd** [comment]
Posting questions I asked in slack here for reference.

> 1. Why are _mentionables_ associated with a `repository` and not a `github_repository`?
> 2. Do we want to maintain referential integrity?
> 3. Should a pull request be associated to a `repository` or `github_repository`?
> 4. Is `github_repository.parent_id` a foreign key? If so, what table does it refer to?

**Comment by iAmWillShepherd** [comment]
Posting response from @shiftkey 

> initial thoughts without diving into the code:
> 1. mentionables are currently only used for autocomplete, and that’s only needed when a repository is local?
> 2. probably, unless we’re fighting the underlying database to achieve it. also, keep in mind that the v3 API now supports returning GraphQL identifiers to assist with migration: https://developer.github.com/changes/2017-12-19-graphql-node-id/
> 3. `githubRepo` makes sense from a data model perspective, especially if we start to do more API-backed features.
> 4. maybe that’s the way to represent a fork from the API?

**Comment by shiftkey** [comment]
Tentatively marking this as `tech-debt` so it doesn't get mixed up with other tasks.

**Comment by iAmWillShepherd** [comment]
I'm actually going to merge this into #2954 since this change is driven by the need to clean up the db.
