### ISSUE TITLE
Multi user

### ISSUE THREAD

**Issue by kevzdev** [desktop/desktop#3909]
GitHub Desktop should have a function where the user could switch to another git user.

We could implement it to switch the `user.email` and `user.name` in the `.gitconfig`.

This would be nice for people that have a work and prive git(hub) account while they work on 1 machine.

**Comment by say25** [comment]
So different non-enterprise accounts?

**Comment by nerdneha** [comment]
@kevzdev thanks for the feedback!

We had a similar discussion to this in #2829, which goes a little more into why we're hesitant to make the change without fully thinking through the consequences this would have on other projects and users who don't juggle two accounts. Please feel free to add your thoughts to that issue about this problem.

@shiftkey also mentions a workaround in #2829 to set your commit email per-repository through the command line:

```
git config --local user.email myCrpyticUserName@company.com
```

Once you've done that, it will override what Git has setup globally. In this way, you can at least differentiate the default email between your two email accounts for your different projects. Hope that helps!

**Comment by kevzdev** [comment]
@nerdneha nice workaround, thanks, but as the name suggests, it's a workaround. Not really handy to do that in every repository each time..

>  the consequences this would have on other projects and users who don't juggle two accounts.  

that would just default to the 1st profile, as how it behaves now, I don't see how that is a consequence?

**Comment by drdavi** [comment]
Descarga Outlook para iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kevzdev** [comment]
@drdavi ?

**Comment by shiftkey** [comment]
@kevzdev talking about the "why" here is essential, rather that just the "what", and #2829 is a great example of that.

Some questions I have about your use case:

> GitHub Desktop should have a function where the user could switch to another git user.
> ...
> This would be nice for people that have a work and prive git(hub) account while they work on 1 machine.

From reading this, it's not clear to me whether you're referring to switching your GitHub account or simply switching the Git `user.name` and `user.email` settings. Can you clarify which one you want to be switching?

> nice workaround, thanks, but as the name suggests, it's a workaround. Not really handy to do that in every repository each time..

You're right in that you need to apply this workaround for each repository that differs from your global configuration settings, but it's a one-time operation.

**Comment by Serkan-devel** [comment]
This might be relevant https://gist.github.com/jexchan/2351996/

**Comment by shiftkey** [comment]
I'm going to close this out as I don't think we received enough information to understand the situation.

Git already supports the ability to configure per-repository settings for commit details, and we're tracking more actionable feedback about managing multiple accounts like #2829.

Please open a fresh issue with more details about your usage if you'd like us to revisit this.
