### ISSUE TITLE
"Discard all changes" not working

### ISSUE THREAD

**Issue by cheshire137** [desktop/desktop#3912]
I'm using version 1.0.13 in macOS. I have two changed files. When I right-click the "2 changed files" header on the left and choose "Discard all changes", nothing happens. Opening the inspector, I see a couple new JS errors appear when I try to discard changes:

- "`git submodule status --` exited with an unexpected code: 128." from install.ts:23
- "Uncaught (in promise) l: fatal: no submodule mapping found in .gitmodules for path" from core.ts:73

**Comment by jonabc** [comment]
Version 1.0.13 on macOS as well.

☝️ Seeing this same error when trying to discard changes for both a single file as well as "Discard all changes"

**Comment by shiftkey** [comment]
@cheshire137 @jonabc thanks for this, I traced the issue back to a malformed `.gitmodules` file:

```
$ git submodule status
fatal: No url found for submodule path '{path}' in .gitmodules
```

I'll wrap this call in better error handling and skip over any work with submodules, if Git doesn't want to co-operate/

**Comment by HedvigS** [comment]
I had this problem, couldn't figure it out. I deleted the folder with the repios, recloned and it persisted. Then I removed the repos from within GitHub desktop and moved the folder to the trash, and recloned again. This time it worked, the changes are discarded proper.
I don't know if this helps, but just in case someone else navigates here and also can't discard changes for some reason.
