### ISSUE TITLE
Ability to Fork and Publish

### ISSUE THREAD

**Issue by say25** [desktop/desktop#3918]
### Description

Ability To Fork and Push to Fork

### Version

**GitHub Desktop version:** 1.0.14-beta1

### Steps to Reproduce

1. Clone a repo you don't have write access to
1. Make changes and commit
1. Attempt to publish branch

**Expected behavior:** The ability to fork, switch my local repos remote to my fork, and actually publish a branch.

**Actual behavior:** Simply get an error message

**Reproduces how often:** 100%

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

1. Would you mind elaborating on your idea a bit? 
    1. Would a fork be automatically created when you attempt to push a branch to a repo you don't have write-privileges on? 
    1. What about the branch, do you envision this flow also creating your branch on your fork? 
    1. Would a PR automatically be created to merge the changes in your branch?

**Comment by say25** [comment]
1. Would you mind elaborating on your idea a bit? `No problem`
    1. Would a fork be automatically created when you attempt to push a branch to a repo you don't have write-privileges on? `Ideally a fork would be created with a copy of the "Default Branch" and Github Desktop would switch the local checkout to that forked repo`
    1. What about the branch, do you envision this flow also creating your branch on your fork? `I would expect to have to re-click the publish button for fork to confirm you wish to create a new branch, rather than commit to the forked master or what not`
    1. Would a PR automatically be created to merge the changes in your branch? `I think a PR would be a separate thing, you may be wishing to space out your changes over multiple commits`

**Comment by iAmWillShepherd** [comment]
@desktop/core any thoughts on this one?

**Comment by niik** [comment]
> @desktop/core any thoughts on this one?

This is something we want to do. It was brought up and discussed briefly during our planning session but did not make it into the next planning cycle. Generally speaking we want to improve functionality around forks overall.

**Comment by shiftkey** [comment]
This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by billygriffin** [comment]
I'm going to remove `future proposal` here as this is something we're interested in looking at and @kuychaco wrote up a more detailed description in #8548. Thanks so much for the issue @say25 and describing your expectations!
