### ISSUE TITLE
Little symbol next to changed repos in repo list

### ISSUE THREAD

**Issue by GiovanniIacopetti** [desktop/desktop#3919]
In the repo list panel, would be nice to know what changed, while offline we work on several repos and I'd prefer not to go hunting for not submitted changes...

Thanks guys, you rock!

**Comment by iAmWillShepherd** [comment]
@GiovanniIacopetti I want to make sure I understand what you're asking for. Are you looking for a visual cue that a repository has unpushed commits?

**Comment by GiovanniIacopetti** [comment]
Exactly :) maybe like the little blue dot next to "Changes" inside the repo! Maybe even uncommitted changes?

**Comment by shiftkey** [comment]
@GiovanniIacopetti thanks for the feedback! We're already tracking a very similar suggestion to this in #2245, so please follow along with that issue.
