### ISSUE TITLE
Can't join as collaborator

### ISSUE THREAD

**Issue by trishadominyk** [desktop/desktop#3925]
### Description

I've been invited as a collaborator of a repository and I've accepted the invitation. Even though I accepted, I checked the repository's contributors tab and I am not included. On my GitHub Desktop I cannot push my commits either because I have no access to the repository. I asked to removed as collaborator and be sent the invitation again but the same thing happened.

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** Microsoft Windows [Version 10.0.16299.125]

### Steps to Reproduce

1. Be sent an invitation to be a collaborator of https://github.com/jareeed/Dental_Clinic/
2. Accept invitation from email
3. Push the commits

**Expected behavior:** Able to push my commits

**Actual behavior:** Prompted an error message that reads "Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository."

**Reproduces how often:** 100% of the time

**Comment by shiftkey** [comment]
@trishadominyk did this get sorted?
