### ISSUE TITLE
Github Desktop closed while committing thousands of chagnes

### ISSUE THREAD

**Issue by amsteel** [desktop/desktop#3933]
Error: write EOF
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite (net.js:813:14)

Version: 1.0.13
OS: Windows 10.0.16299

**Comment by iAmWillShepherd** [comment]
Thanks for opening an issue!

All new issues now require steps to reproduce (also called "repro steps") the
problem or the behavior you wish to see on GitHub Desktop. We do this so we can
be certain that we are understanding what it is you're describing and don't
prematurely close the issue or implement the wrong feature. If you need help
writing detailed repro steps, please see the [How Can I Contribute? document](https://github.com/desktop/desktop/blob/master/CONTRIBUTING.md).

**Comment by rafaeelaudibert** [comment]
Just had the same problem. Making a revert of more than 4000 files and GitHub Desktop closed and showed me this message.

Steps for reproduction:
 • Set up a revert of more than an 'x' number of files (Tried with 4000)
 • Try to revert it
 • The error occurs

**Comment by iAmWillShepherd** [comment]
Thanks for the original details, @rafaeelaudibert? 
* Do you receive the same errors when doing this using the CLI? 
* Would you mind attaching your logs to this issue? 🙇  Those help us 👀 the problem quicker.

**Comment by shiftkey** [comment]
Closing this out as inactive.

@rafaeelaudibert I've had a report in #4086 (similar to your issue), which suggests a recent fix #4058 might also address your issue - it's currently on the [beta channel](https://github.com/desktop/desktop#beta-channel) and will be available in 1.1 when we ship it next week. 

If you can trigger this issue again we can revisit this specific problem with the included log files!
