### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Arioshoma** [desktop/desktop#3937]
### Description

Hello there,
I'm unable to install the GitHub Desktop tool on windows 7 32bit.
The error I get:
https://i.imgur.com/0unUTEV.png
The SquirrelSetup.log content:
https://paste2.org/sUBwDzgN
After clicking on "GitHubDesktopSetup" and GitHub Desktop loading screen I get that error.

### Version

**GitHub Desktop version:** 10.13.0

**OS version:** Windows 7 32bit

**Expected behavior:** Installing GitHub Desktop

**Actual behavior:** Got error

**Comment by tierninho** [comment]
@Arioshoma Unfortunately, we only support 64-bit. We don't currently have any plans to support a 32-bit version.

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #1214. Please follow that issue
for further updates.
