### ISSUE TITLE
Repository does not show

### ISSUE THREAD

**Issue by billyrubin09** [desktop/desktop#3961]
### Description

i just installed the Github desktop and signed into my Github account. A friend invited me to his repository. I successfully accepted the invite, but the repository does not appear on my desktop client. I tried rebooting the client, but no joy. 

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** Windows 6.1.7601

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by j-f1** [comment]
GitHub Desktop only shows you repositories you’ve download onto your computer. If you go to the repository’s page on GitHub, there should be an option under “Clone or Dowload” to “Open in Desktop.” This will prompt you for the location to download the repository to, then add it to the app.

**Comment by billyrubin09** [comment]
I realized my error after I submitted the ticket. Thank you for responding
so quickly. I'm a total n00b.
