### ISSUE TITLE
Add analytics support for co-authoring

### ISSUE THREAD

**Issue by nerdneha** [desktop/desktop#3964]
Pulled from: https://github.com/github/analytics/issues/316 a la @telliott27

> I think a good next step would be to start logging co-authored commits in Desktop. From my perspective, if we could have two measures: one thats the total number of co-authored commits that day, and a second that is the number of co-authored commits pushed to a repo on GitHub that day, that would be enough to answer the questions we've discussed so far.

- [x] total number of co-authored commits per day

**Comment by bluebunny4** [comment]
taking a shower

On Tue, Feb 20, 2018 at 11:48 AM, William Shepherd <notifications@github.com
