### ISSUE TITLE
Changes tab count

### ISSUE THREAD

**Issue by nerdneha** [desktop/desktop#3965]
This is part of #3956 and is for showing the new count in the changes tab header

**Changes:**
- [ ] changes tab header shows `count` for commits (same as the counter component in pull-request-tab?)

**Before:** 
<img width="200" alt="screen shot" src="https://user-images.githubusercontent.com/1834387/36132718-9aa17036-102d-11e8-859e-45c9b14c2288.png">

**After:**
<img width="200" alt="screen shot" src="https://user-images.githubusercontent.com/1834387/36136056-6bebdd24-1043-11e8-92d7-86362e5359c1.png">

**Comment by nerdneha** [comment]
@donokuda @niik just to clarify, does the count represent the # of commits in this branch?

**Comment by donokuda** [comment]
eep! 🤦‍♂️ That's something I didn't clean up and isn't relevant to the feature as a whole, but the number that is being counted are the files changed in the working directory. This might have slipped into the mock-ups during the "hmm, wouldn't this be cool?" step of the design process.

This issue can be closed out and I'll update the images in the other issues accordingly.
