### ISSUE TITLE
Diff too big warning/hint not easily visible

### ISSUE THREAD

**Issue by tooomm** [desktop/desktop#3971]
### Description

Warning/hint not easily visible and badly placed.
I assume the intention is to have it displayed centered, not left aligned?

Also, it could be bold for example.

(the picture seems to be left aligned, too!)

### Version

**GitHub Desktop version:** 1.0.13
**OS version:** Microsoft Windows [Version 10.0.16299.125]

### Additional information
![warning](https://user-images.githubusercontent.com/9874850/35986599-c1d48bf2-0cf9-11e8-9ea1-205cab8f9cd0.png)

**Comment by iAmWillShepherd** [comment]
cc @desktop/design for thoughts.

**Comment by niik** [comment]
Welp, that doesn't look great at all. Seems like it looked a little bit better when it was introduced in https://github.com/desktop/desktop/pull/1893 but I don't believe this ever received design input. I don't think we should use that graphic here and I'm not wild about the messaging either.

I think something like this would be an improvement

<img src="https://user-images.githubusercontent.com/634063/36023997-a0628c72-0d8e-11e8-9c96-c72616d276e5.png" width="650" />

What do you think @donokuda?

**Comment by donokuda** [comment]
Looks fine to me. 👍  Thoughts on making sure the warning is centered in that area? I'm also unsure if we should use the blue primary button or a white secondary button instead, but I'm pretty impartial with that call.

**Comment by niik** [comment]
> Thoughts on making sure the warning is centered in that area?

Horizontally? Yes, definitely, with a max width of around 400px.
Vertically? I tried it out and I believe top align with double margin is the way to go.

> I'm also unsure if we should use the blue primary button or a white secondary button instead, but I'm pretty impartial with that call.

<img src="https://user-images.githubusercontent.com/634063/36028414-24d13f20-0d9f-11e8-9a9b-20f02cf7376b.png" width="650" />

I think you're right, let's go with the secondary.

**Comment by tooomm** [comment]
I would center such a warning horizontally for sure!
Vertically not neccessarly. Could also be 1/3 to the top etc.

About the buttons I can't help too much as I don't know about the underlying concept exactly.

**Comment by perperson1** [comment]
![multixnxx-all things gay -7](https://user-images.githubusercontent.com/36304871/36036288-ca6dc858-0db9-11e8-94c7-e31e5f9f69b7.jpg)
