### ISSUE TITLE
Thousands of changed files should not affect app responsiveness

### ISSUE THREAD

**Issue by danqing** [desktop/desktop#3983]
I have a project with 30k files to commit (from upstream branch). This freezes the entire Desktop app with no button responsive. I can't even switch project since the project switcher is frozen too.

It doesn't take too long to perform operations with the `git` command line, so I'm not sure what exactly is freezing GH Desktop.

**Comment by shiftkey** [comment]
@danqing is it committing in particular that seems to affect the UI? It's not clear to me how to reproduce the issue currently.

**Comment by danqing** [comment]
It's not. Simply having 30k "dirty" files causes the app to freeze. I think one way to repro is to have an unignored `node_modules` with a bunch of dependencies. That will create a ton of files.

**Comment by shiftkey** [comment]
@danqing please also include which OS you are using, the version of Desktop you are running, and any other interesting details about your setup that might be related to this issue.

**Comment by danqing** [comment]
Sure - I'm on osx 10.13.3 with desktop 1.0.13. Pretty standard setup I think.

**Comment by bezigon** [comment]
I have the same problem. GitHub Desktop freezes on 100k recently added files. I have to write a .gitignore file.

**Comment by shiftkey** [comment]
Moving this one into `1.1.x` to see if we can tune things better

**Comment by shiftkey** [comment]
@bezigon @danqing if you're still seeing this issue could you attach a fresh log file - I'm looking into the details about this at the moment, and it'd be nice to see which Git operations are impacting you

**Comment by iAmWillShepherd** [comment]
Fixed in #4443.
