### ISSUE TITLE
No Github.com repo found

### ISSUE THREAD

**Issue by rodolfo-viana** [desktop/desktop#3984]
### Description

My desktop app shows no repository of mine. It is just blank, although I am connected to my account. Some of my repositories are cloned and they work perfectly. But one specific private repo does not appear when I go through "File > Clone repository > GitHub.com"; therefore, it cannot be cloned.

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** Microsoft Windows 10.0.16299.192

### Steps to Reproduce

1. Go through "File > Clone repository > GitHub.com"
2. Expect to find a list of my repositories (which does not happen)

**Expected behavior:** Find all my repositories

**Actual behavior:** Found none of my repositories, athough I can work with the ones already cloned

**Reproduces how often:** Every time in the past 5 days

### Logs

[2018-02-07.desktop.production.log](https://github.com/desktop/desktop/files/1712940/2018-02-07.desktop.production.log)
[2018-02-08.desktop.production.log](https://github.com/desktop/desktop/files/1712941/2018-02-08.desktop.production.log)
[2018-02-10.desktop.production.log](https://github.com/desktop/desktop/files/1712942/2018-02-10.desktop.production.log)

#### Additional Information

![image](https://user-images.githubusercontent.com/25807981/36057884-2e4571a4-0dfc-11e8-8f89-ceac97151cf7.png)

**Comment by iAmWillShepherd** [comment]
I see this line in each one of your logs:
> remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/rodolfo-viana/globo.git/'

Can you try signing out and signing back in?

**Comment by rodolfo-viana** [comment]
It worked! (Which is weird because I had no trouble commiting to the other repos.)
Thanks, @iAmWillShepherd.
I am closing this issue.

**Comment by iAmWillShepherd** [comment]
Glad that worked out 🎉
