### ISSUE TITLE
'file mode changes' only show 'No contents changes found'

### ISSUE THREAD

**Issue by yzbyzz** [desktop/desktop#3993]
### Description

After change file mode, Desktop only show 'No contents changes found' which confuse.
It's better to show something like 'old file mode xxx, new file mode xx'

### Version 

**GitHub Desktop version:** [1.0.13]

**OS version:** [Windows 10]

**Comment by shiftkey** [comment]
@yzbyzz thanks for the feedback! We're tracking this in #557, so please follow along with that issue.
