### ISSUE TITLE
[RBB] Ahead/Behind Toggle

### ISSUE THREAD

**Issue by nerdneha** [desktop/desktop#3997]
This is part of #3956 and shows how your branch has diverged from your target branch (ex: master). This will help you understand what changes can be brought into your branch (behind) and what commits are unique to your branch (ahead).

**User Flow to check functionality:**
- go to compare view with **no toggle** showing
- click on compare tab, click into the "compare a branch..." input, and click on "master" and see:
  - the **toggle appear** in the compare view
  - `Behind (x)` selected by default where x is the # of commits your branch is behind "master" (old view showed commits ahead of master)
  - the commits that are missing from your branch that exist in the target branch
- click on `Ahead (y)` in the toggle where y is the # of commits your branch is ahead of "master" and see:
  - the commits that exist only in your branch and not the target branch
- press "x" in the branch input, select another target branch, and see:
  - the compare view where you can toggle behind/ahead
  - the respective commits listed

**Changes:**
- [x] create toggle
- Behind **(x)** & Ahead **(y)** counts
- [x] `Behind (x)` is selected by default
- [x] default view shows the commits that your branch is behind (relative to the target branch)
- [x] clicking `Ahead (y)` shows commits 
- [x] clicked `Ahead (y)` shows the commits that your branch is ahead (relative to the target branch)

**Other pieces**:
- merging into my branch is in #3998 

**Before (shows "ahead" by default):**
<img width="200" alt="screen shot 2018-02-08 at 2 11 27 am" src="https://user-images.githubusercontent.com/1834387/35967342-6fdd54d4-0c75-11e8-8e4b-f9691b8df380.png">

**After:**
![image](https://user-images.githubusercontent.com/1174461/36275587-58c5b218-122f-11e8-8711-b1ab9822cfe0.png)

**Comment by shiftkey** [comment]
@donokuda mentioned in chat that he'd like to experiment with this toggle against real repository data, so I'm gonna see if I can get a branch together to mimic this experience while we're wrapping up 1.1, even if we throwaway the resulting code.

**Comment by shiftkey** [comment]
I've pushed up `ahead-behind-toggle-spike` which hacks in a rough UX for this: https://github.com/desktop/desktop/compare/ahead-behind-toggle-spike -  try it out!

I cheated and used a tab bar to "emulate" the toggle button, but it should be good enough to get a feel for the feature.

<img width="567" src="https://user-images.githubusercontent.com/359239/36293169-286c6aaa-1327-11e8-8990-43372364b68c.png">

A couple of quick observations based on the time I spent testing this:

 - I found myself glancing up and to the right a lot to remember what branch I was on while doing this - that bit of information seems important to remember "where I am right now" and felt further away from the compare "area".
 - When I was considering whether to merge a branch into this current branch, the "ahead" details - representing the commits on my branch - didn't really feel as relevant as the "behind" details. That might be down to the workflow.
 - Viewing those "ahead" isolated from the whole history, to identify my work that was distinct from the other branch, still feels very useful.

**Comment by j-f1** [comment]
> I found myself glancing up and to the right a lot to remember what branch I was on while doing this - that bit of information seems important to remember "where I am right now" and felt further away from the compare "area".

How about labeling the dropdown with “bump-to-react-16 → master”?

**Comment by nerdneha** [comment]
@donokuda, my voluntary 2💰: if there's no changes to designs for now based on findings, i think we can keep this and potentially **create a user test script** to answer this question better once we get it in a PR

@shiftkey given that you've spiked this feature, do you think the scripted "user flow" and the listed changes are comprehensive? are we missing anything?

**Comment by shiftkey** [comment]
@donokuda @nerdneha I'm happy to proceed as-is and address the UX feels later - whether it's as part of a PR or end-user testing/feedback
