### ISSUE TITLE
[RBB] Merge changes into your branch

### ISSUE THREAD

**Issue by nerdneha** [desktop/desktop#3998]
This is part of #3956 and provides the option to bring changes from a target branch into your branch using a merge button

**User Flow to check functionality:**
- click on compare tab, click into the "compare a branch..." input, and click on "master" and see:
  - `Behind (x)` in the toggle selected with the commits that are missing from your branch that exist in the target branch
  - a **merge button** saying `Merge into my-branch-name`
  - supporting text `This will merge x commits from (target branch name)`
- click on `Ahead (y)` in the toggle where y is the # of commits your branch is ahead of "master" and see:
  - **no merge button**
- click "x" in the branch input, select another target branch, and see:
  - the option to **merge a different target branch's commits into your branch** in the default behind view only
- click back to `Behind (x)` and click on the **merge button** and see: 
  - commits disappear from Behind area and toggle becomes `Behind (0)`
  - Ahead is not affected
- click "x" in the branch input and focus out of the input and see:
  - the recently merged commits included in the history now

**Changes:**
- [x] merge button with text `Merge into (my-branch-name)`
- [x] supporting text below merge button with a count matching x in the `Behind (x)` toggle
- [x] clicked `Merge into (my-branch-name)` merges those changes into your branch
- [x] disabled merge button when there is nothing to merge (ex: after completing a merge)
- [x] reverting on conflict + error message

**Other pieces**:
- toggling is in #3997
- predicting merge conflicts will happen in a later issue

**Before (shows "ahead" by default):**
<img width="200" alt="screen shot 2018-02-08 at 2 11 27 am" src="https://user-images.githubusercontent.com/1834387/35967342-6fdd54d4-0c75-11e8-8e4b-f9691b8df380.png">

**After:**
![image](https://user-images.githubusercontent.com/1174461/36275587-58c5b218-122f-11e8-8711-b1ab9822cfe0.png)

**Comment by nerdneha** [comment]
@donokuda @niik 
- what happens after you merge? do you stay in the view and the behind count becomes `Behind (0)` and the ahead becomes `Ahead (x+y)`? what does the merge button look like (greyed out? hidden)? 
- is there a scenario where the merge button would be greyed out otherwise?
- if they end up in a state where they have merge conflicts, will we have any (temporary) helpful text to resolve?
- is there anything fancy we need to know about scrolling through commits in the "behind" part?

**Comment by niik** [comment]
> what happens after you merge? do you stay in the view and the behind count becomes Behind (0) and the ahead becomes Ahead (x+y)?

Yup, that makes sense to me

>  what does the merge button look like (greyed out? hidden)?

The normal button disabled state

> is there a scenario where the merge button would be greyed out otherwise?

As long as there are commits ready to be merged I can't see such a case. Perhaps we'd disable it while a pull operation is ongoing but we don't do that for committing right now so we can probably punt on it for now.

> if they end up in a state where they have merge conflicts, will we have any (temporary) helpful text to resolve?

We should show a dialog in that case letting the user know that the merge was unsuccessful and then send them of to the commit view to see the conflicts.

> is there anything fancy we need to know about scrolling through commits in the "behind" part?

Not for the initial work but one thing that we both would really like to have in this view is range selections. We haven't yet spec:d that out fully though.

**Comment by iAmWillShepherd** [comment]
> reverting on conflict + error message

I'm a bit confused by this. Does this mean the app should auto-magically revert on conflict? or is it as simple as displaying an error stating there are conflicts?

**Comment by iAmWillShepherd** [comment]
@donokuda, @niik  do you have any thoughts on how we should handle a merge conflict? Should we surface a dialog or show something in the Compare tab?

At the moment, I'm leaning towards this workflow:
1. Merge produces conflict
1. User can get out of it by clicking _discard all changes_
1. Check to see if the `MERGE_HEAD` file exists in the`.git` database
1. If it does, use `git merge --abort` to cleanup things

**Comment by donokuda** [comment]
That sounds reasonable to me, but would this be considered out of scope for RBB? I think users are currently able to find themselves in that situation if they get a conflict from running Branch > Update From Default Branch...

Maybe we can punt on this decision until we start work on Merge Conflicts.
