### ISSUE TITLE
Datetime not displayed for commits (relative date is limited in helpfulness)

### ISSUE THREAD

**Issue by spencer-microsoft** [desktop/desktop#3999]
### Description

Having the datetime of the commit in the History is really helpful, but in recent versions, it only shows the relative time, and it's in the left pane, which gets truncated if the user's name is long. It would be incredibly helpful to have the datetime shown in the main window with the commit ("December 17th 2017 at 3:11pm") rather than in the history pane as a relative date ("a week ago", "4 minutes ago", etc).

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** 10.13.3 (17D47)

### Steps to Reproduce

No specific steps - just a general feature request

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

I can definitely see how knowing the exact date and time a commit was created could be useful 👍

**Comment by shiftkey** [comment]
@spencer-microsoft thanks for the feedback.

For reference, the full timestamp is available by hovering on the tooltip in the history panel:

<img width="464" src="https://user-images.githubusercontent.com/359239/36178929-68b6b2f0-116a-11e8-8645-fcf2e5a69932.png">

We're always striving to be consistent with Desktop, and I think we've overlooked the fact that they also have the relative time in the commit details (and the tooltip shows the absolute time):

<img width="422" src="https://user-images.githubusercontent.com/359239/36183786-e779883c-117f-11e8-8eb9-dab530ddbd65.png">

I think we should do the same thing in the commit details in Desktop:

<img width="434" src="https://user-images.githubusercontent.com/359239/36183791-f1d7336a-117f-11e8-879e-63b62ad48b2b.png">

We have a [component](https://github.com/desktop/desktop/blob/master/app/src/ui/relative-time.tsx) for rendering relative time already, and the commit authors are defined here, if someone is interested in adding in support:

https://github.com/desktop/desktop/blob/458a427b012fe4c6465852905b745fe921221c69/app/src/ui/history/commit-summary.tsx#L296-L305

**Comment by niik** [comment]
Thanks for taking the time to contribute @spencer-microsoft!

Using relative time stamps is a conscious design decision. As @shiftkey pointed out you can get to the exact date by hovering. Relative times are time zone independent, quite compact and doesn't require regional formatting (which is troublesome for us at the moment, see https://github.com/desktop/desktop/pull/1257#issuecomment-296147325

I don't foresee us changing this any time soon so I'm going to close this issue out but we'd welcome a new issue to discuss whether also including the date in the commit details view would make sense. With the addition of co-authors and the redesigned commit list items in the history tab we should revisit that.

cc @donokuda

**Comment by maddes-b** [comment]
+1 for making this an option. "1h ago" is not precise (can be anything from 60 to 119 minutes ago), just give admins all information so they can work without hassle.

**Comment by RobertKrawitz** [comment]
+1 for making this an option, again.  I would be fine with (in fact, I'd prefer) displaying UTC dates and times in ISO 8601 format, which have no timezone issues or regional formatting problems.  I want something efficient, not "friendly".

**Comment by zsbee** [comment]
+1, Last Week / 3 weeks ago is really vague, I would be totally happy with absolute local dates. (let me care about timezones myself if it affects my team). Sometimes you need to collect a timeline for a postmortem and this makes it a lot harder than it should be.

**Comment by RobertKrawitz** [comment]
I don't understand the argument about it being a locale issue if the time can be displayed by hover.  The tooltip clearly can render the date, so why can't it be rendered in other contexts?
