### ISSUE TITLE
add visual indicator that a folder can be dropped on Desktop

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#4004]
A discussion in https://github.com/desktop/desktop/pull/3996 indicates we're not exactly providing any visual indication that you can drop a folder on to Desktop (or that there are now times when you can't).

Currently, we have these two event handlers setup in `app.tsx`:

```ts
    document.ondragover = document.ondrop = e => {
      e.preventDefault()
    }

    document.body.ondrop = e => {
      if (this.state.currentPopup != null) {
        return
      }

      const files = e.dataTransfer.files
      this.handleDragAndDrop(files)
      e.preventDefault()
    }
```

Looking at the MDN docs, [this link](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/dropEffect) suggests that we could do something like this inside the `dragover` event handler: 

```js
e.dataTransfer.dropEffect = 'none';
```

### What To Do

Investigate what happens when split up these event handlers to look like the below snippet. I haven't tested this code, so you might find something unexpected.

```ts
    document.ondragover = e => {
      if (this.state.currentPopup != null) {
        e.dataTransfer.dropEffect = 'none'
      } else {
        e.dataTransfer.dropEffect = 'copy'
      }
 
      // this seems important, we should keep it around
      e.preventDefault()
    }

    document.ondrop = e => {
      e.preventDefault()
    }
```

There's two scenarios to test here with this change:

 - whether the cursor changes when you drag a folder onto Desktop (to indicate it can be added)
 - whether the cursor also changes when a modal is displayed (to indicate that it is being ignored)

There's also probably some cross-platform testing to do here, but we can do that at review time if you don't have access to multiple OSes.

**Comment by agisilaos** [comment]
Currently working on this @shiftkey, opening a PR soon.

**Comment by agisilaos** [comment]
@shiftkey Jus opened a PR #4239
