### ISSUE TITLE
"Downloading update" never get finished

### ISSUE THREAD

**Issue by noersetiawan** [desktop/desktop#4005]
### Description

Opening the about page, the app automatically tried to check for update, after several seconds, it changed from "checking for update" to "downloading update", I checked task manager, the process Update (32 bit) under GitHub Desktop (4) does using the network.

After several seconds, task manager reports GitHub Desktops is not using network anymore. I thought it was doing installation then I left it for > 40 minutes. The "downloading update" seems to be forever, not downloading anything and using high CPU. Re-opening and trying the same procedure again resulted in the same problem.

### Version

**GitHub Desktop version:** 1.0.4

**OS version:** Microsoft Windows [Version 10.0.16299.214]

### Steps to Reproduce

1. Open "Help > About GitHub Desktop"
2. Wait for "checking for update" changes into "downloading update"

**Expected behavior:** The app is updated

**Actual behavior:** Perpetual "downloading update"

**Reproduces how often:** 100%

![screenshot 14 _li](https://user-images.githubusercontent.com/5868000/36187666-7414db40-1179-11e8-80cb-30d35b332e13.jpg)
### Logs

[2018-02-14.desktop.production.log](https://github.com/desktop/desktop/files/1722653/2018-02-14.desktop.production.log)

**Comment by shiftkey** [comment]
@noersetiawan apologies for the delay in following up with this

There's a secondary log file that the updater generates that might help us to understand what's happening. It should be found at `%LOCALAPPDATA%\GitHubDesktop\SquirrelSetup.log` and might have details around why it's gotten stuck.

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @noersetiawan if you're able to find any interesting errors in the logs mentioned in the previous comment please share them so we can troubleshoot further.

**Comment by dntrply** [comment]
I encountered a similar issue. I needed to relaunch GitHub Desktop (Version 1.6.6) as Administrator and the update (to 2.2.3) did complete after about 18 minutes.

**Comment by ProgrammerBruce** [comment]
I just updated from 1.6.6 to 2.3.1, via the GitHub Desktop app self-update mechanism.  It completed without logging in as Administrator, but it took maybe an hour (over a gigabit fiber internet connection).  (I'd given up on it working, but walked away to work on other things, and came back to find it had completed.)  So, lesson learned: sometimes the update process works, though it takes an unexpectedly long time, and it may be difficult to believe that it is actually doing something.

**Comment by lcocea** [comment]
Same problem here on 2020-05-13. If the update is "in progress" and it is expected to take a long time to complete then a progress bar in the About dialog would be helpful.

**Comment by phenry9999** [comment]
I'm experiencing the SAME problem today. Seems like the update process isn't a priority?
I just restarted the app four\five\six times and it stopped nagging me about quitting. Not the smoothest workflow.
What this teaches me is to question doing the update the next time. Is that what you want to teach your users? If not, then I suggest fixing this sooner than later.

**Comment by NopenAI** [comment]
I am facing the same issue. The update never finishes. I updated it using Winget and launched it again. Still stuck in "Downloading Update...". 
What bothers me is that it doesn't let me exit the app while the update is in progress.

**Comment by justingolden21** [comment]
Same here on my windows 10 PC that I haven't touched in months. Full cpu and power usage and never lets me exit.

Used desktop for years and never encountered this until now

**Comment by marcolopes** [comment]
Same problem here! Stuck in "**Downloading update...**"
Version 3.3.4 (x64)

**Comment by marcolopes** [comment]
> I just updated from 1.6.6 to 2.3.1, via the GitHub Desktop app self-update mechanism. It completed without logging in as Administrator, but it took maybe an hour (over a gigabit fiber internet connection). (I'd given up on it working, but walked away to work on other things, and came back to find it had completed.) So, lesson learned: sometimes the update process works, though it takes an unexpectedly long time, and it may be difficult to believe that it is actually doing something.

Actually i was just monitoring the folder **C:\Users\xxx\AppData\Local\GitHubDesktop\packages** and the app IS downloading all the packages (i believe it needs to go through all of them to get to the LATEST one!)

It's VERY VERY SLOW!

You have to be patient!

**Comment by justingolden21** [comment]
I wish I had suggestions for how to fix or more info, or anyway to help here other than just complain, but it definitely seems like this is important, that users today, right now are experiencing this and they can't update, it crashes their PC, and yet this issue is closed.

Can we reopen this issue?

**Comment by aronaronaronaronaron** [comment]
this isnt closed it's happening to me rn

**Comment by raminabolghasemi** [comment]
Uninstall your GitHub Desktop from your pc ( in windows: Control panel> Programs> program and Features) and install the latest version from: https://desktop.github.com/

![Screenshot_GitHub_3 4 1](https://github.com/desktop/desktop/assets/126275041/1fd7f797-6d31-4c49-b313-e0a6b988d199)

**Comment by Piogre** [comment]
Still an issue in 2025.  Absolutely infuriating that an update starts without asking when I launch the program, takes seemingly forever with no progress indicator, and says it will break the installation if I close the program before its done.  Even more infuriating that this issue was closed because the initial reporter happened to not respond, and remains closed despite numerous people indicating it's still an issue.

**Comment by hgs-sellis** [comment]
This issue should be re-opened. It is happening to me now and apparently to a lot of other people too.

**Comment by hgs-sellis** [comment]
I thought this issue was happening to me. I waited a LONG time and it finally finished. I have a  very fast internet connection so it should not take so long. Seems like there is a performance bug here.

**Comment by prmntr** [comment]
How is this still happening in 2025??? I've been waiting for almost 2 hours for this to update while the program sits in my task manager eating up all my CPU usage.

**Comment by Amesh321** [comment]
I ran into this in 3.4.16 
I also noticed antimalware service becomes super busy at the same time and chills out after you close github desktop in task manager. (windows 11)

**Comment by stolarchukboris** [comment]
~3.5.0 still a thing (havent used github desktop in a while hence the version)~
disregard, updated in like 5 minutes
