### ISSUE TITLE
I am not able to pull origin repository using gitdesktop

### ISSUE THREAD

**Issue by jai-dewani** [desktop/desktop#4012]
### Description
When ever I try to create a pull request or even try to update my repository, it show this error:
**_**fatal: unable to access 'https://github.com/SimpleMobileTools/Simple-Calendar.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.**_**
[Description of the issue]

### Version

Version 1.0.13
**GitHub Desktop version:** [version here]

Windows 10
**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

This issue seems related to #3326

Could you run the following command and paste its output?
`git config http.sslBackend`

**Comment by shiftkey** [comment]
Closing this out as inactive, and we're pretty sure [these instructions](https://github.com/desktop/desktop/blob/master/docs/known-issues.md#certificate-revocation-check-fails---3326) workaround the issue.
