### ISSUE TITLE
I can't connect to my own repository. Push origin

### ISSUE THREAD

**Issue by EugeneAndrievsky** [desktop/desktop#4013]
Hello, I have the same problem as https://github.com/desktop/desktop/issues/2453
I can't connect to my own repository
I think the problem is because of shh keys.

When I first time installed git in 2016 I  just launched github.desktop once. Was created key github_rsa.
In 2017 I started work with git console and created a new key id_rsa and added it to the github account. it still working for now by the console.

But github desktop, i think, is trying to use my github_rsa which invalid:
"Key is invalid. It must begin with 'ssh-ed25519', 'ssh-rsa', 'ssh-dss', 'ecdsa-sha2-nistp256', 'ecdsa-sha2-nistp384', or 'ecdsa-sha2-nistp521'. Check that you're copying the public half of the key " 
and i can't add it to github profile.

Github.Desktop use password from github.com but console use another one. I think it is because of different ssh keys.
How to "meet" working key with github desktop?

**GitHub Desktop version:** [1.0.13]

**OS version:** [Microsoft Windows 7 version 6.1.7601]

### Steps to Reproduce

I have local repository (with .git folder)
1. [push origin]
2. [Error : "Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository."]

**Reproduces how often:** [100%]

### Logs

Developer's tools console log: 
"Executing fetch: git -c credential.helper= fetch --progress --prune origin "
and below:
install.ts:23 `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
(The error was parsed as 2: Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.)

`%APPDATA%\GitHub Desktop\logs\*.desktop.production.log`
I have not this log/ folder

#### Additional Information

git remote -v
origin  git@github.com:EugeneAndrievsky/repositoryName.git (fetch)
origin  git@github.com:EugeneAndrievsky/repositoryName.git (push)

**Comment by iAmWillShepherd** [comment]
@EugeneAndrievsky did you clone your repository using SSH? If so, could you try cloning using HTTPS to see if the problem persists?

**Comment by EugeneAndrievsky** [comment]
@iAmWillShepherd 

1. Using Github Desktop:
* Clone repository (Ctrl + Shift + O)
* Tab "URL" > https://github.com/.../.git
* Clone
* Make a commit
* Push origin
* It's work!

2. Using Github Desktop:
* Add a local repository... (ctrl + o) (cloned earlier by console using SSH)
* Make a commit
* Push origin
* Error: "Authentication failed. You may not have permission to access the repository..."

3. Using console:
* git clone https://github.com/.../.git
* Add in Github Desktop as local repository
* Make a commit
* Push origin
* It's work!

So, the problem was caused by using SSH.
Thank you very much for your help and for such a quick response.

**Comment by iAmWillShepherd** [comment]
I'm glad you were able to work around the problem. At the moment, GitHub Desktop doesn't support repos cloned using SSH very well, but it's something we are looking to improve (see #2579). For now, just be sure to clone all repos using HTTPS for Desktop to work without the 🤕

**Comment by giuseppephp** [comment]
Signing out and signing back in worked for me.

**Comment by EvoDoro** [comment]
Signing out and back in also worked for me. I was so confused because I was using HTTPS!

**Comment by IamCathal** [comment]
Can say signing in and out fixed the problem for me if anyone needed some more encouragement to do it. Thank you for the fix

**Comment by RedaBenh** [comment]
I get the same error. i change the git remote url from ssh to https : 

1. Go to menu > Repository Settings 
2. Change primary remote repository (Origin) from "git@github.com:<USERNAME>/<REPO_NAME>.git" to "https://github.com/<USERNAME>/<REPO_NAME>.git"

**Comment by MohammedMohammedBayomy** [comment]
For The access Denied Issues And git username , password

I had this problem too but managed to solve it, the error is that ur computer has saved a git username and password so if you shift to another account the error 403 will appear. Below is the solution
For Windows you can find the keys here:

control panel > user accounts > credential manager > Windows credentials > Generic credentials

Next remove the Github keys.

**Comment by arpan13579** [comment]
git push origin master
fatal: unable to access 'https://github.com/arpan13579/docker-app.git/': Failed to connect to 172.22.218.218 port 8085: Timed out



I'm getting the above error

**Comment by shahnawazm786** [comment]
> git push origin master fatal: unable to access 'https://github.com/arpan13579/docker-app.git/': Failed to connect to 172.22.218.218 port 8085: Timed out
> 
> I'm getting the above error

Check the your credential which you are using to login. 
or use git bash, you will had better error description. 



Thanks

**Comment by shahnawazm786** [comment]
git status 

git add --all

git commit -m "message here"

git push -u origin --all
