### ISSUE TITLE
Double tapping a file should open with the default program

### ISSUE THREAD

**Issue by danielgalasko** [desktop/desktop#4019]
### Description

<img width="473" alt="screen shot 2018-02-15 at 11 25 31 am" src="https://user-images.githubusercontent.com/4479146/36249329-f84fd92c-1242-11e8-88a9-57445942a002.png">

When I am viewing files, I have to right click and select "Open with default program" to open a file. It would be awesome if this could be done by double clicking.

### Version

**GitHub Desktop version:** [1.0.13]

**OS version:** [10.12.6]

### Steps to Reproduce

1. Make changes to a source file
2. Observe the file in the Files Changed view
3. Double tap any file in the list

**Expected behavior:** [The file opens in my default program]

**Actual behavior:** [Nothing happens]

**Reproduces how often:** [All the time]

**Comment by shiftkey** [comment]
@danielgalasko thanks for the feedback. We're tracking this in #2620, so please follow along with that.
