### ISSUE TITLE
Do Better at Sharing New Features

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#4021]
I was reading through the docs and noticed that we didn't follow through on `preview-features.md`. I did update it, but it was too little and too late, so I removed that doc in #4016. It is rather unfortunate that we let this slip, but maybe there is a better way to surface this information? 

Let use this issue to figure out a better way to communicate features released behind a feature flag.

**Comment by j-f1** [comment]
Maybe a `chrome://flags`-style interface?

**Comment by shiftkey** [comment]
> Let use this issue to figure out a better way to communicate features released behind a feature flag.

A couple of initial thoughts:

 - I'd rather us focus on communicating stuff that's in the beta channel before promoting features that are less further along.
 - I also look at things like https://desktop.github.com/features/co-authors/ and wonder if that's a better way to quickly summarize features (both in words and visually)

**Comment by iAmWillShepherd** [comment]
> I also look at things like https://desktop.github.com/features/co-authors/ and wonder if that's a better way to quickly summarize features (both in words and visually) 
☝️ 💯 

I agree with that. 

How would this look like? I could imagine having a permanent beta page that contains the current features we've released to the beta channel or preview features. It would definitely be better for users. I'm not sure if most people go to the repository for information about products.

**Comment by shiftkey** [comment]
What about something like `https://desktop.github.com/features/upcoming/`? We can avoid it being channel-specific, and I think a similar marketing-esque layout to the `co-authors` page would be a good starting point.

**Comment by iAmWillShepherd** [comment]
Should I go ahead and get that started? Also would we have gifs and images for all *major* features at `https://desktop.github.com/features`? I think that would be awesome since we don't really show off all the little cool things Desktop does.

**Comment by shiftkey** [comment]
> Should we go ahead and get that started?

How about we hold off on this until we have some 1.2 features in beta? Then we'll have some cool things to show off on this new page.

> Also would we have gifs and images for all major features at `https://desktop.github.com/features`?

@donokuda is this something on your radar? Want to chime in?

**Comment by j-f1** [comment]
> Also would we have gifs and images for all *major* features at `https://desktop.github.com/features`?

How about showing the first frame of the GIF for each feature, then swapping it with the GIF on hover?

**Comment by nerdneha** [comment]
would definitely love @donokuda's 2 cents on this. 

@donokuda and i talked about expanding the [co-authoring features page mentioned above](https://desktop.github.com/features/co-authors/) to include pull requests so we start to have a feed of all major features as they're released. @iAmWillShepherd i like you're idea of having past major features on there, too! i'm warming up to an upcoming section (pro: great way to point people to and get them excited, con: more work). maybe we can adapt our upcoming post about roadmap into this

**Comment by donokuda** [comment]
> i'm warming up to an upcoming section (pro: great way to point people to and get them excited, con: more work).

![image](https://user-images.githubusercontent.com/1174461/36331089-8900d3f4-1310-11e8-9a49-67898380080a.png)

I'm all for a main features and a "future features" section that follows afterwards. This can be done in parallel with some of the images for the upcoming post.

**Comment by DevAndArtist** [comment]
A roadmap of new features would be great. I'm really interested when the native desktop app will support **GitHub Projects**.

**Comment by DevAndArtist** [comment]
@j-f1 I didn't know, thx. No mention of GitHub projects for this year I guess. Do you think that feature will be ever included into this application or is it more an app of it's own?

**Comment by steveward** [comment]
@DevAndArtist Thanks for letting us know you would like to see support for GitHub Projects! That is something we may look into in the future. There is an [open issue](https://github.com/desktop/desktop/issues/1867) you can track to get updates about adding this feature -- please feel free to add any feedback you have there.

**Comment by donokuda** [comment]
> The marketing site for the transition from the old to the new desktop app is really well done and I can definitely see it as the main homepage for the product. Is it something that you consider doing?

Yup! Moving the content over to the main page is something I'm considering doing, but I don't have an ETA on when that'll happen.

**Comment by donokuda** [comment]
> Yup! Moving the content over to the main page is something I'm considering doing, but I don't have an ETA on when that'll happen.

I opened up a pull request that does this, so expect an update to the marketing page sooooon!

**Comment by agisilaos** [comment]
That's great! Thank you @donokuda!

**Comment by steveward** [comment]
I'm going to close this out as we now do a better job of advertising our beta channel where users can help us test out new features.
