### ISSUE TITLE
Clean up PR integration feature flag uses

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#4025]
In order to launch 1.1, we switched our feature flag for `enablePRIntegration()` on in #4108. We left it this way after launching 1.1 until things stabilized. Now that things are stable, we're all set to remove any traces of the `enablePRIntegration` flag.

**Task:** Clean up any code paths/mentions around `enablePRIntegration` to officially remove the flag. It is defaulted to `true` so removing it should not affect anything.

--

Some helpful tips for completing a PR:
* If you want to take this issue, comment here so people have a heads up
* Include `Fixes #4025` at the top of the description for your PR
* read our [PR process doc](https://github.com/desktop/desktop/blob/master/docs/process/reviews.md) to understand how we do PRs in this repo and what code review looks like
* When you finish the PR, let us know with a comment that says you're done
* Make sure to test on both Windows and MacOS

**Comment by nerdneha** [comment]
bumping this with an updated description! this is ready to be worked on

**Comment by agisilaos** [comment]
@nerdneha Just opened a PR 😊
