### ISSUE TITLE
Feature request: allow opening file in plain old text editor

### ISSUE THREAD

**Issue by fluffynuts** [desktop/desktop#4028]
### Description

Currently, Github Desktop allows, via context menu, to "open with default program", which is all fine and well, but when one is trying to resolve a merge conflict on a `.csproj` file, that's just going to end in tears for everyone. It would be nice if one could simply open any file with a configured text editor of the user's choice, as another option below "open with default program".

### Version
**GitHub Desktop version:** 1.0.13
**OS version:** windows 10 version 1709

**Comment by fluffynuts** [comment]
Not sure if I should report here or start a new issue, but this feature in 1.1.1 on Windows isn't working quite right -- selecting "Open in Visual Studio Code" seems to get the path to the file wrong -- instead of opening from the base folder of the repository, it opens from the `GitHubDesktop\app-1.1.1` folder, ie:

In my repo, I have a modified file `Test/packages.config`, so it shows up in the Changes pane in GitHubDesktop. Let's pretend my repo is found at `C:\code\my-project` -- I would expect to open the file `C:\code\my-project\Test\packages.config`. Instead, vscode is invoked with the path `%LOCALAPPDATA%\GitHubDesktop\app-1.1.1\Test\packages.config` -- which, naturally, doesn't exist.

**Comment by shiftkey** [comment]
@fluffynuts I encountered the same thing, and I think #4381 is the right fix (should go out in the next update)
