### ISSUE TITLE
select default GIT repo folder

### ISSUE THREAD

**Issue by mancoast** [desktop/desktop#4031]
Greetings,

I am unable to find the option to modify the default GIT repo directory.
REF: 
![image](https://user-images.githubusercontent.com/7040493/36322403-1da20e2e-131b-11e8-9ed3-bd38bdb90529.png)

Thanks,
coast

**Comment by steveward** [comment]
👋 @mancoast 

When you go to `File` > `Clone a repository` or `File` > `New repository` you will see a `Local path` text box that allows you to choose a path where you would like to clone or create your repository. The location you choose there will stick as the default for the next time you clone or create a repository.

Hope that helps!

**Comment by mancoast** [comment]
thanks!
