### ISSUE TITLE
add warning when renaming branch that the remote branch is not updated

### ISSUE THREAD

**Issue by Kubrix** [desktop/desktop#4035]
### Description

Branch renaming in GitHub Desktop does not change branch name in site repository

### Version
**GitHub Desktop version:** 1.0.13

**OS version:** Microsoft Windows [Version 6.1.7601]

### Steps to Reproduce

1. Rename the branch in GitHub Desktop. Make no source code changes.
2. Visit the branches section of your repository on  site
3. Branch in not renamed.

**Expected behavior:** Branch is renamed on this site.

**Actual behavior:** Branch is not renamed on this site

**Reproduces how often:** On each renaming

#### Additional Information
It may not be a bug as updating site information is hard. But how can I update the branch name on the site? Since site name is not updated, all my other PC are showing old branch name.

**Comment by shiftkey** [comment]
I'm somewhat 👎on renaming branches on the remote, because of the flow-on effects and potential to break your collaborators.

@desktop/core any additional feels on this?

**Comment by lee-dohm** [comment]
I tend to agree with you @shiftkey for the reasons you stated above. Renaming on the remote is perhaps fine if you're the only one working in that repo, but since Desktop has no way of knowing we should take the safe route.

**Comment by nerdneha** [comment]
👍 agreed

**Comment by Kubrix** [comment]
@shiftkey, @lee-dohm 

I have renamed the branch ContactIsLayout to ContactIsLayout2 via Git, made changes in the source code,  made a commit to local repository and pushed changes to site repository.

Branch: https://github.com/kalistrat/WebSolidSvn/tree/ContactIsLayout

Link to commit with a new name: https://github.com/kalistrat/WebSolidSvn/commit/95cca01e7c955d86d0c1f114e32d4d6f123da529.

How do I change the branch name on the site?

**Comment by shiftkey** [comment]
> How do I change the branch name on the site?

This is not currently supported on GitHub The Website

**Comment by Kubrix** [comment]
On a related note - branch renaming does not update the "main repository".

I have renamed a branch on one PC and commited that changes to repository.
When I cloned that project on another PC it had old branch name.

Branch renaming on site is not supported. 
But I suppose that site is just a visual representation for the repository.
And the repository itself is not updated by the GitHub branch renaming command.

Maybe you should disable the "Rename branch" menu option?

**Comment by shiftkey** [comment]
@Kubrix 

> On a related note - branch renaming does not update the "main repository".

The main repository is the one with the remote branch, which as we've discussed earlier has a number of side-effects. Clones of the remote repository will continue to have the old name currently.

> Maybe you should disable the "Rename branch" menu option?

If you rename a branch in Git like this, it's also only applied locally:

```
git branch -m old-branch new-branch
```

This is how Desktop is currently behaving, and I think we should make this explicit in the dialog to avoid some confusion. I suggest a message like this:

> This branch is currently tracking `origin/branch-name`, but renaming this branch will only update your local repository.

**Comment by Kubrix** [comment]
@shiftkey 

>  I think we should make this explicit in the dialog to avoid some confusion. I suggest a message like this:
Yes, that would be good.

**Comment by shiftkey** [comment]
@Kubrix I'll update the issue title to reflect the current state of the discussion

**Comment by shiftkey** [comment]
Here's a rough patch to illustrate how we might add this message to the Rename branch dialog:

```
diff --git a/app/src/ui/lib/branch-name-warnings.tsx b/app/src/ui/lib/branch-name-warnings.tsx
index f5d37c462..220715ad3 100644
--- a/app/src/ui/lib/branch-name-warnings.tsx
+++ b/app/src/ui/lib/branch-name-warnings.tsx
@@ -1,5 +1,6 @@
 import * as React from 'react'
 
+import { Branch } from '../../models/branch'
 import { Row } from './row'
 import { Octicon, OcticonSymbol } from '../octicons'
 import { Ref } from './ref'
@@ -30,3 +31,19 @@ export function renderBranchNameWarning(
     return null
   }
 }
+
+export function renderBranchHasRemoteWarning(branch: Branch) {
+  if (branch.upstream != null) {
+    return (
+      <Row className="warning-helper-text">
+        <Octicon symbol={OcticonSymbol.alert} />
+        <p>
+          This branch is tracking <Ref>{branch.upstream}</Ref> and renaming this
+          branch will not change the branch name on the remote.
+        </p>
+      </Row>
+    )
+  } else {
+    return null
+  }
+}
diff --git a/app/src/ui/rename-branch/rename-branch-dialog.tsx b/app/src/ui/rename-branch/rename-branch-dialog.tsx
index 30deb34b0..036558085 100644
--- a/app/src/ui/rename-branch/rename-branch-dialog.tsx
+++ b/app/src/ui/rename-branch/rename-branch-dialog.tsx
@@ -9,7 +9,10 @@ import { Row } from '../lib/row'
 import { Button } from '../lib/button'
 import { ButtonGroup } from '../lib/button-group'
 import { Dialog, DialogContent, DialogFooter } from '../dialog'
-import { renderBranchNameWarning } from '../lib/branch-name-warnings'
+import {
+  renderBranchNameWarning,
+  renderBranchHasRemoteWarning,
+} from '../lib/branch-name-warnings'
 
 interface IRenameBranchProps {
   readonly dispatcher: Dispatcher
@@ -54,6 +57,7 @@ export class RenameBranch extends React.Component<
             this.state.newName,
             sanitizedBranchName(this.state.newName)
           )}
+          {renderBranchHasRemoteWarning(this.props.branch)}
         </DialogContent>
 
         <DialogFooter>
```

And this is how it looks in action:

<img width="621" src="https://user-images.githubusercontent.com/359239/37882084-b0d66026-30eb-11e8-81ce-d41cdc37bb2b.png">

We already have the ability to display a warning message here, so I'm not sure how to stack these so the dialog doesn't become overwhelming (put it above the form?):

<img width="627" alt="screen shot 2018-03-26 at 11 48 25 am" src="https://user-images.githubusercontent.com/359239/37882248-3696ddde-30ed-11e8-9d18-eb60ab1e2596.png">

There's also the squished icon because of the very wordy message to figure out.

**Comment by JordanMussi** [comment]
How about simply changing the title of the dialogue to `Rename Local Branch`? This informs the user what action will be performed without undue attention using a warning.

**Comment by lee-dohm** [comment]
@JordanMussi It would be nice if we could depend on people to see that and understand that's what that means. I feel that the warning that @shiftkey suggested is much more clear and noticeable.

**Comment by JordanMussi** [comment]
Personally a warning is a bit strong for this hence the idea of changing the title. I think a concept of a "note" would fit much better since using a warning just under the input implies it's to do with what the user has entered.
