### ISSUE TITLE
Window remains in unreachable Area of Monitor

### ISSUE THREAD

**Issue by stawi** [desktop/desktop#4038]
### Description

Github Desktop is not able to be displayed after disconnecting a 4K Monitor.
After disconnecting, Github Desktop will be left in a undisplayable Area of the Screen. The only posibility to view it is to change to full-screen via F11. After that it remains unscalable and undragable.

Note: Windowskey + Left/Right/Up/Down doesn't work

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** Microsoft Windows [Version 10.0.16299.248]

### Steps to Reproduce

1. Connect a 4K Monitor to your Laptop
2. Drag Github Desktop to the 4k Monitor
3. Disconnect the Monitor

**Expected behavior:** Github should have been moved to a displayable area of the Monitor

**Actual behavior:** Github remains in the area of the 4K Monitor and so won't be able to be displayed without a 4K Monitor

**Reproduces how often:**  Every Time
#### Additional Information

The setup was an internal 1080p Monitor + 4k over HDMI
The setup is now: internal 1080p Monitor + 1x 1080p over HDMI + 786x1366 over VGA

**Comment by shiftkey** [comment]
@stawi thanks for the report! We're tracking this issue in #2107, so please follow along with that issue.
