### ISSUE TITLE
Not sure 

### ISSUE THREAD

**Issue by steventam312** [desktop/desktop#4040]
### Description

[Description of the issue]

### Version

Rewrite**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by nori0990** [comment]
D
