### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by say25** [desktop/desktop#4048]
Not to bring up another Holy War or anything but now that the app has matured more is it possible to consider adding dark mode back in? Its been a couple releases and months since the last issue was closed.

**Comment by crea7or** [comment]
Really good thing. Almost every dev tool have dark theme, most of them by default:
(visual studio/sublime/gitkraken/vs code)
![dark](https://user-images.githubusercontent.com/467357/36430302-ec790142-1665-11e8-90be-1af78fbca0b8.PNG)

**Comment by shiftkey** [comment]
@say25 @crea7or we're tracking this in #1515. Please follow along with that issue.

**Comment by say25** [comment]
^ that issue is closed no?

**Comment by shiftkey** [comment]
@say25 no, see this comment for where we're current at https://github.com/desktop/desktop/issues/1515#issuecomment-336532891
