### ISSUE TITLE
provide a loading gif when unpacking on Windows

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#405]
When running the Squirrel installer it currently has a "typing"-esque GIF when unpacking:

<img width="294" src="https://cloud.githubusercontent.com/assets/359239/18858098/f8f82ff2-84ac-11e6-8281-c1f4a0853fba.png">

It'd be cool to show something nice. It also lacks Branding™. Here's the Atom one, for example:

![](https://github.com/atom/atom/blob/master/resources/win/loading.gif?raw=true)

cc @donokuda @niik for ideas

**Comment by Edgarruiz856** [comment]
[**`by: Edgarruiz856`**](https://github.com/desktop/desktop/issues/405#issue-179382551)
