### ISSUE TITLE
Changing repository settings does absolutely nothing

### ISSUE THREAD

**Issue by nh2d** [desktop/desktop#4060]
### Description

I am trying to switch between repositories but i am unable to even though I change Repository->Repository Settings...

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** High Sierra 10.13.3

### Steps to Reproduce

1. Loaded one repository
1. Changed repository settings
1. Nothing changes

**Expected behavior:** The repository switches

**Actual behavior:** Still somehow bound to previous repository

**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
@nh2d thanks for the feedback! The way to change repositories is to use the repository switcher in the top-left of the app:

<img width="358" src="https://user-images.githubusercontent.com/359239/36459991-4f117b22-1706-11e8-8528-fb370f4fd36a.png">

If you click this, it will expand to show the list of repositories currently tracked in the app:

<img width="367" src="https://user-images.githubusercontent.com/359239/36460007-69272cbe-1706-11e8-9a75-586db99bae3c.png">

To add more repositories to this list, use the **File** | **Add Local Repository** menu to add them, or just drag-and-drop the folders from Finder into the app.

I'm going to close this out, but if you have any other questions or feedback I'm happy to follow up!
