### ISSUE TITLE
"Authentication failed" when trying to publish a branch

### ISSUE THREAD

**Issue by mikez302** [desktop/desktop#4065]
I am using GitHub Desktop Version 1.0.13 on OS X 10.12.6. I am working on Mypy, trying to make a change to the documentation. I created a branch and made my change. I'm trying to create a pull request. I clicked the "Publish branch" button in GitHub Desktop and saw the following error message:

> Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open preferences and verify that you're signed in with an account that has permission to access this repository.

I opened the preferences dialog and verified that I am signed in as myself. Am I doing something wrong? Am I supposed to create a fork and not just a branch? Or is this a bug in GitHub Desktop?

**Comment by shiftkey** [comment]
@mikez302 if you've cloned the https://github.com/python/mypy repository to your local machine and don't have permissions to push to it, that's likely the issue.

The "Fork and Publish" workflow to reduce this friction is something we're tracking in #3918, and as a workaround you can [fork the repository](https://help.github.com/articles/fork-a-repo/) through the website to your account, and then clone that one to your local machine. You should then be able to push branches to your fork and create the pull request in the app.

Let me know if you have any other questions or issues about this.

**Comment by mikez302** [comment]
I tried what you suggested and it worked. Thanks. I wish you the best of
luck with the workflow project.

**Comment by HedvigS** [comment]
I'm having the same problem, and I don't want to fork and clone. I want to keep branching and making PRs. Should I make a new issue thread, or is there another one I should be following?

**Comment by tierninho** [comment]
> Should I make a new issue thread, or is there another one I should be following?

@HedvigS Please open a new issue. Thank you.
