### ISSUE TITLE
file too large, but can't remove it

### ISSUE THREAD

**Issue by ryan-jonesford** [desktop/desktop#4066]
### Description

Uploaded a file that exceeds size of a file I can upload. But I can't remove it from the history when it asks me to, so whenever I try to push it tells me that I am trying to push a file that is too large and none of my files get pushed.

### Version

1.0.13

Windows 10

### Steps to Reproduce

1. Add a file that is over 100mb
2. Commit and push

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by shiftkey** [comment]
@ryan-jonesford sorry to hear you've encountered this problem. This is a [hard limit](https://help.github.com/articles/conditions-for-large-files/#100-mb-push-limit) for GitHub to ensure our Git servers aren't overloaded.

We're tracking #997 as a way to warn people about this issue, when you're working with a GitHub repository, so please follow along with that issue.

> But I can't remove it from the history when it asks me to,

@steveward any pointers or resources for helping remove this from history?

**Comment by j-f1** [comment]
I’m not @steveward, but I took a look at the [`git lfs migrate` docs](https://github.com/git-lfs/git-lfs/blob/6f503b2b8e26e4cd9bcb826712be2537927cf97c/docs/man/git-lfs-migrate.1.ronn), and they have [an example](https://github.com/git-lfs/git-lfs/blob/6f503b2b8e26e4cd9bcb826712be2537927cf97c/docs/man/git-lfs-migrate.1.ronn#L132-L162) that shows how to convert large files in unpushed commits to LFS objects.

**Comment by shiftkey** [comment]
@j-f1 thanks for that. I was also thinking about rewriting history to remove the file without enabling LFS, but that's really Danger Zone™ because you're rewriting history...

**Comment by steveward** [comment]
@ryan-jonesford we have a [help article](https://help.github.com/articles/removing-files-from-a-repository-s-history/) that walks through how to remove a large file from your repository's history. If you have any questions about these steps please feel free to reach out to support@github.com and we can assist you further.

**Comment by number435398** [comment]
The issue is that this can't be fixed within "Github Desktop".  Not that there aren't other options.  Though, I installed Git and when I try to "Open in Command Prompt", it still states I don't have it.  I'm not finding the proposed solution to be easy at all.

**Comment by laredoza** [comment]
This worked for me:

A simple solution I used: 

1. Do `git reset HEAD^` for as many commits you want to undo, it will keep your changes and your actual state of your files, just flushing the commits of them. 

2. Once the commits are undone, you can think about how to commit your files in a better way, e.g.: removing/ignoring the huge files and then adding what you want and then committing again. Or use Git LFS to track those huge files.

https://stackoverflow.com/questions/20002557/how-to-remove-a-too-large-file-in-a-commit-when-my-branch-is-ahead-of-master-by

**Comment by samsato** [comment]
The solution that worked for me was to delete the entire local modified repository. Re-clone the Github repository. Restore my changes and then perform the commit and push.

**Comment by steveward** [comment]
@samsato we'll be [shipping a feature](https://github.com/desktop/desktop/pull/6013) in an upcoming release that will automatically detect when you attempt to push large files. It's currently available in the [beta channel](https://github.com/desktop/desktop#beta-channel) of GitHub Desktop if you are interested in checking it out. Hope that is helpful!

**Comment by ppoh71** [comment]
> The solution that worked for me was to delete the entire local modified repository. Re-clone the Github repository. Restore my changes and then perform the commit and push.

That was also the only solution for me....

**Comment by RowdyWabbid** [comment]
> This worked for me:
> 
> A simple solution I used:
> 
> 1. Do `git reset HEAD^` for as many commits you want to undo, it will keep your changes and your actual state of your files, just flushing the commits of them.
> 2. Once the commits are undone, you can think about how to commit your files in a better way, e.g.: removing/ignoring the huge files and then adding what you want and then committing again. Or use Git LFS to track those huge files.
> 
> https://stackoverflow.com/questions/20002557/how-to-remove-a-too-large-file-in-a-commit-when-my-branch-is-ahead-of-master-by

This should be a button on Github desktop. Life Saver!

**Comment by fcatapano** [comment]
> This worked for me:
> 
> A simple solution I used:
> 
> 1. Do `git reset HEAD^` for as many commits you want to undo, it will keep your changes and your actual state of your files, just flushing the commits of them.
> 2. Once the commits are undone, you can think about how to commit your files in a better way, e.g.: removing/ignoring the huge files and then adding what you want and then committing again. Or use Git LFS to track those huge files.
> 
> https://stackoverflow.com/questions/20002557/how-to-remove-a-too-large-file-in-a-commit-when-my-branch-is-ahead-of-master-by

This worked for me

**Comment by JonathanHelvey** [comment]
https://stackoverflow.com/questions/9529078/how-do-i-use-git-reset-hard-head-to-revert-to-a-previous-commit#targetText=HEAD%20points%20to%20your%20current,log%20or%20any%20history%20browser.)

git reset --hard <SOME-COMMIT>

This worked for me!
