### ISSUE TITLE
optimization: avoid a fetch when checkout out a pull request

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#4068]
In #4057 @niik mentions an opportunity to avoid a `fetch` if we know the branch exists:

```ts
      // TODO: I think we could skip this fetch if we know that we have the branch locally
      // already. That way we'd match the behavior of checking out a branch.
      if (defaultRemote) {
        await this._fetchRemote(
          repository,
          defaultRemote,
          FetchType.UserInitiatedTask
        )
      }
```

I'll let @niik add any additional thoughts on the best approach here.

**Comment by agisilaos** [comment]
Would be more than happy to pick this up @shiftkey 💯

**Comment by agisilaos** [comment]
@shiftkey Is it possible to report the comment above as spam? because I don't have this option available.
![screen shot 2018-02-24 at 18 41 14](https://user-images.githubusercontent.com/10944108/36632707-5850da78-1992-11e8-94b3-84ceb06fd098.png)

**Comment by iAmWillShepherd** [comment]
@agisilaos. Go for it! I'll add it to our project board for tracking issues our community have claimed.

**Comment by agisilaos** [comment]
@niik Before I start working on this, I would love to know your additional thoughts or any other info that may help me during the process.

**Comment by iAmWillShepherd** [comment]
@agisilaos , when you open your PR, can you be sure to include `Fixes #4068` at the top of the PR body?

**Comment by agisilaos** [comment]
Of course 🌮

**Comment by niik** [comment]
> Before I start working on this, I would love to know your additional thoughts or any other info that may help me during the process.

I believe I was referring to using the same logic that already exists in the forked-case: https://github.com/desktop/desktop/blob/321c3de0f143e29cfaab702dbc6e5766f8d91fda/app/src/lib/stores/app-store.ts#L3323-L3333

So I'd say the work consists of extracting that logic into something reusable and then verifying that my assumption was correct in the first place.

**Comment by agisilaos** [comment]
Just finished working on this one. Will create a PR soon @niik!

**Comment by agisilaos** [comment]
PR #4240 is up! 💯
