### ISSUE TITLE
SmartScreen blocking, Why ?

### ISSUE THREAD

**Issue by JiranKurian** [desktop/desktop#4073]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by jamescriscoe** [comment]
hi

**Comment by crea7or** [comment]
Regular (not EV) sha1 signature require some time to collect reputation in Windows SmartScreen.

**Comment by crea7or** [comment]
1) GitHub should add Sha256 signature to existing Sha1 signature
2) Get EV certificate or register regular one at [sysdev](https://sysdev.microsoft.com/en-US/hardware/signup/) (register company and submit signed file - it will give instant reputation in SmartScreen later for this certificate).

**Comment by shiftkey** [comment]
@JiranKurian thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by shiftkey** [comment]
@crea7or Desktop Classic got caught when Smartscreen started blocking SHA1 certificates [back in 2016](https://www.globalsign.com/en/blog/microsoft-announces-updates-sha-1-code-signing-policy/), so we should be using a combined SHA1-SHA256 certificate these days (for compatibility reasons), and our installer and main executable are both signed with this certificate (ignore what the first dialog says):

<img width="887" src="https://user-images.githubusercontent.com/359239/36534391-56702aa6-1816-11e8-8454-89f966c9b1d0.png">

<img width="880" src="https://user-images.githubusercontent.com/359239/36534392-56b78522-1816-11e8-8f8a-3ed2d6b155bf.png">

I'd love more concrete feedback if we're encountering a new Smartscreen issue.

**Comment by crea7or** [comment]
@shiftkey The second dialog shows the signature of the certificate. Correct signatures will be available at the first screen:
![image](https://user-images.githubusercontent.com/467357/36539261-3e712786-17e7-11e8-84c2-058789f95b42.png)

There is a special command that append the second signature to .exe file without removing the first one.
```
signtool.exe sign /a /s MY /n "Your Common Name" /fd sha1 /t http://timestamp.comodoca.com /v filetosign.exe
signtool.exe sign /as /a /s MY /n "Your Common Name" /fd sha256 /tr http://timestamp.comodoca.com/?td=sha256 /v filetosign.exe
```

**Comment by JiranKurian** [comment]
![github](https://user-images.githubusercontent.com/22431166/36543897-1cb342d6-180b-11e8-9a49-6930c46b8bdb.PNG)

**Comment by shiftkey** [comment]
@JiranKurian "SmartScreen can't be reached right now" is a network connectivity issue, and is beyond the control of Desktop.

Closing as an external issue.
