### ISSUE TITLE
Allow for issues to be manually refreshed

### ISSUE THREAD

**Issue by AmirSavand** [desktop/desktop#4076]
### Description

When creating issues on GitHub while GitHub Desktop is open, they won't show up when referencing them in commit field (#`issue-number`).

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** Microsoft Windows [Version 10.0.16299.248]

### Steps to Reproduce

1. Open GitHub Desktop
1. Create an issue on GitHub
1. GitHub Desktop fails to show it when referencing the issue in commit field.

**Expected behavior:** Being able to select the issue that was recently created.

**Actual behavior:** Fails to show the issue.

**Reproduces how often:** 100%

#### Additional Information

No additional information 😜

**Comment by tierninho** [comment]
@AmirSavand Are you referring the referencing of `#`-issues to the commit fields? Please fill out the template so we can get more details.

**Comment by AmirSavand** [comment]
@tierninho yes I am.

Currently I'm super busy, will update the issue once I have some free time.
I had to post this issue since it's annoying, I didn't have this problem with old GitHub Desktop.
I installed this yesterday.

**Comment by shiftkey** [comment]
Dropping `needs-reproduction` until we have more information to understand the problem.

**Comment by AmirSavand** [comment]
Ok, I think I know how this goes, if the app is open and I create new issues, they won't come up in app when referencing via # in commit field.

**Comment by AmirSavand** [comment]
Updated issue description.

**Comment by AmirSavand** [comment]
I checked back after like 10 minutes and the issue was there, so it seems like it takes time to pull the issues... so I think that's just it, it's not instant.

**Comment by tierninho** [comment]
Thanks for clarifying, closing this issue.

**Comment by j-f1** [comment]
I think we should keep this open to track updating the issues when the user manually clicks “Fetch.”

**Comment by AmirSavand** [comment]
I think it would be good if someone updated the issue title, since the exact cause was found after the issue was created.

**Comment by shiftkey** [comment]
> any points against changing performFetch so that it also updates issues?

I think doing this inside the `finally` block (like we're doing with pull requests) is a reasonable compromise. I was going to leave this open but my exploration of this has yielded #4311 so we might as well just go straight to the PR for the change.
