### ISSUE TITLE
Autocomplete list not working properly in commit description

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#4084]
When opening an `#`issue menu in the commit description field, I noticed the results were placed behind the co-author feature, making the content hard to read. 

Expected result: results should be on top of the co-author feature

<img width="503" alt="screen shot 2018-02-22 at 2 14 36 pm" src="https://user-images.githubusercontent.com/14828183/36567384-1ca3ce3a-17db-11e8-9eae-af141274d551.png">

We should also reposition the autocomplete popup so it doesn't appear to be cut off when it is near the edge of the app.

![51198824-2d98b400-18aa-11e9-824a-887931943015](https://user-images.githubusercontent.com/14828183/54955803-6f6d5880-4ef2-11e9-872b-e812608daf26.png)

**Comment by shiftkey** [comment]
Nice find @tierninho 💖

**Comment by shiftkey** [comment]
Tentatively pulling this into 1.1.x, hopefully it doesn't require CodeMirror Hacks™

**Comment by shiftkey** [comment]
Dropping this from `1.1.x` as I think there's more urgent bugs to address.

**Comment by tierninho** [comment]
For anyone who works on this, a good place to start is:

https://github.com/desktop/desktop/blob/1de8d45fc6dc3da6b7099c68f0d4a97c311bf972/app/src/ui/diff/code-mirror-host.tsx
https://github.com/desktop/desktop/blob/1de8d45fc6dc3da6b7099c68f0d4a97c311bf972/app/styles/ui/_autocompletion.scss
https://github.com/desktop/desktop/blob/e69467d1239c1b2cb0e290b61f8f703aaa9deeea/app/src/ui/lib/author-input.tsx
https://github.com/desktop/desktop/blob/1de8d45fc6dc3da6b7099c68f0d4a97c311bf972/app/styles/ui/_author-input.scss

The `autocompletion-popup` currently renders behind the `author-input-component`.

**Comment by tierninho** [comment]
Adding #6633 to this issue as the touch the same code area.

We should reposition the autocomplete popup so it doesn't appear to be cut off when it is near the edge of the app.

![51198824-2d98b400-18aa-11e9-824a-887931943015](https://user-images.githubusercontent.com/14828183/54955803-6f6d5880-4ef2-11e9-872b-e812608daf26.png)

v1.6.0-beta2, mac

**Comment by billygriffin** [comment]
Removing `help wanted` here since we've decided to pick this one up for the 2.3 release.
