### ISSUE TITLE
Github Desktop Catastrophic Failure

### ISSUE THREAD

**Issue by rhodso** [desktop/desktop#4086]
### Description

Error: write EOF
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite (net.js:813:14)

Version: 1.0.13
OS: Windows 6.1.7601

### Version
**OS version:** Microsoft Windows [Version 6.1.7601]

### Steps to Reproduce
1. Create local project
2. Try to upload to GitHub in a new repository
3. Fail

**Expected behavior:** Create new repository

**Actual behavior:** Catastrophic failure 

**Reproduces how often:** So far 3 for 3

### Logs

https://pastebin.com/WLrEcCL0

**Comment by shiftkey** [comment]
@rhodso thanks for the report. It looks like you're trying to commit some changes when the error occurs, and I'd love to understand more about it.

```
2018-02-22T22:36:46.587Z - error: [ui] `git update-index --add --remove --replace -z --stdin` exited with an unexpected code: 128.
warning: LF will be replaced by CRLF in .gitattributes.
The file will have its original line endings in your working directory.
error: open(".vs/ChatBot/v15/Server/sqlite3/db.lock"): Permission denied
fatal: Unable to process path .vs/ChatBot/v15/Server/sqlite3/db.lock
 
2018-02-22T22:36:46.933Z - info: [main] Error report submitted
```

This error suggests a different program (Visual Studio?) has this file open while Desktop is trying to commit it.

But it's this error that's the real problem:

```
2018-02-22T22:36:46.587Z - error: [main] Error: write EOF
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite (net.js:813:14)
```

We've made some changes to our embedded Git to handle this error, and it's currently on the [beta channel](https://github.com/desktop/desktop#beta-channel) - are you able to install that version and see if it behaves differently? If it still errors, an updated log file would be great!

**Comment by rhodso** [comment]
It appears to have worked, thanks very much for the quick response and fix!

**Comment by shiftkey** [comment]
@rhodso that's great to hear! cc @niik

**Comment by shiftkey** [comment]
Closing this out as #4058 seems to address this - we'll push 1.1 to the stable channel on Monday.
