### ISSUE TITLE
GitHub wiki repositories are recognized as "Other" instead of "GitHub.com"

### ISSUE THREAD

**Issue by caioproiete** [desktop/desktop#4092]
Hello! This might be by design, but reporting just in case:

I've added 2 repositories cloned from GitHub, to `GitHub Desktop`, by dragging them from the disk. One "regular" repository, and one "wiki" repository, which is the wiki that belongs to the "regular" repository.

![image](https://user-images.githubusercontent.com/177608/36598887-ffbd628c-1883-11e8-8326-b62f1ab61530.png)

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** Windows 7

1. Clone the repository https://github.com/xlget/xlget-docs.git by using Git Bash
2. Clone the repository https://github.com/xlget/xlget-docs.wiki.git by using Git Bash
3. Add both repositories to `GitHub Desktop` by dragging the two folders into `GitHub Desktop`
4. Notice that the first repository appears under "GitHub.com", but the second repository appears under "Other"

**Expected behavior:** Both repositories to appear under "GitHub.com"

**Actual behavior:** One repository (docs) appears under "GitHub.com" and the other (docs.wiki) appears under "Other"

**Reproduces how often:** 100% of the time

**Comment by tierninho** [comment]
@caioproiete Thanks for reaching out. We still have a pending bug where wikis are not part of the API, which may be the reason for such repos being recognized as "other". 

You can follow along here: https://github.com/desktop/desktop/issues/2061

**Comment by shiftkey** [comment]
I'm going to fold this up into the #2061 issue
