### ISSUE TITLE
Branch list-related features request

### ISSUE THREAD

**Issue by Kubrix** [desktop/desktop#4099]
Request 1: Option to do not divide the branches list into "Recent" and "Other" branches - since the "recent" branch is not necessarily the branch you have been working on recently. I can select and view all my branches one-by-one and the previous of recent branch will be shown as "Other". Note that I did not do any changes to the branches.

Request2: Option not to change the position of the branch in the list after I selected it. When I choose a branch it is lifted up to the first place under the "Recent branches" list. This prevents me from going through the full list of branches from top the bottom so I can check of them. Since every branch is lifted to the top am I not sure what branches I have already checked and which not. It would be nice if the active branch is just marked by [v] and stayed at it`s place in the list.

**Comment by shiftkey** [comment]
@Kubrix thanks for the feedback. 

We compute the "Recent Branches" list by scanning the reflog of the repository for branches you've checked out in your local repository. It's a bit primitive, but is relatively inexpensive compared to scanning all refs for commits.

> since the "recent" branch is not necessarily the branch you have been working on recently. ... Note that I did not do any changes to the branches.

I'm curious about this statement - could you elaborate on it further? I'm not sure I understand it clearly.

> This prevents me from going through the full list of branches from top the bottom so I can check of them. 

Can you tell me about this workflow here? What tasks are you doing that you need to walk through all the refs from top-to-bottom that the "Recent Branches" view interferes with?

**Comment by Kubrix** [comment]
@shiftkey 
> I'm curious about this statement - could you elaborate on it further? I'm not sure I understand it clearly.

What branches are counted as "Recent" by GitHub Desktop?
This is what I see when I open Github after cloning the repository to a new PC:
![branchlist1](https://user-images.githubusercontent.com/33233100/36665240-f5d4f4ee-1ade-11e8-8cc0-c81e631d70b4.PNG)

No recent branches.
Now I click one of the branches from the list. This leads to GitHub switching to that branch and updating the changes list. Now when I open the branch list I see this:
![branchlist2](https://user-images.githubusercontent.com/33233100/36665394-59ebc278-1adf-11e8-8b60-af59d3c1dfca.PNG)

Selected branch in now shown as Recent. Based on this picture I suppose that "Recent" by GitHub`s definition is the "Recently opened branch" and not the "Branch with the recent commits" as no changes is made till now.

So my question is - what is the purpose of dividing the branches into "Recent" and "Other"?

>Can you tell me about this workflow here? What tasks are you doing that you need to walk through all the refs from top-to-bottom that the "Recent Branches" view interferes with?

My application is working with database and I have several independent branches. I want to update my branches - do a commit with a new database dump file. The easiest way to do it is go through the list of branches in some order - for example from top to bottom of branch list. But the problem is - when I select a branch is lifted to the top. After the second branch update I can get confused - which branches are updated and which not. How do I go through the list of not updated branches without selecting all of them?

It would be possible if the branch position in the list would not be changed by selecting it - I know that I started from the top. I can continue from the bottom.

**Comment by shiftkey** [comment]
> The easiest way to do it is go through the list of branches in some order - for example from top to bottom of branch list. But the problem is - when I select a branch is lifted to the top. After the second branch update I can get confused - which branches are updated and which not. How do I go through the list of not updated branches without selecting all of them?

I don't have a good answer for this - in addition to using the "Recent Branches" list we'll remove these branches from the "Other" list to prevent duplication and potential confusion, which is clashing with your workflow.

cc @desktop/core @desktop/comrades for :eyes: and additional feels

**Comment by shiftkey** [comment]
This has sat for a while, and I guess the big question here from @desktop/core that I'm curious about is whether we want to revisit our thinking about the "Recent Branches" area.

Some thoughts:

 - our separation of "recent" branches from "other" might be a source of confusion when users don't care about when a branch was last checked out locally
 - it relies on the assumption that you only care about local branches, and not branches that other users have updated recently on the remote

Personally, I'm fine with leaving it as-is until we have more insights about usage. Anything else to add?

**Comment by nerdneha** [comment]
> our separation of "recent" branches from "other" might be a source of confusion when users don't care about when a branch was last checked out locally

could we at least make the intention of the functionality more obvious by changing copy to `Recently accessed branches`" that way people will know what it is at least

other than that, i'm okay with leaving as-is until we have more thoughts around this.

**Comment by iAmWillShepherd** [comment]
I understand how having a list that is always reorganizing itself can be confusing. I think we should not try to group branches by access date unless we provide alternative grouping options so that people can choose what works best for them. If we stick with trying to group branches in some way I think having them grouped into Default (should just be one branch) and Local/Remote is good enough.

**Comment by j-f1** [comment]
How about headings like:

* Default
  (`master`, `origin/master`, `upstream/master`)
* [🌎](https://octicons.github.com/icon/globe/) `origin`
  (`origin/master`, `origin/foo`, `origin/bar`)
* [🌎](https://octicons.github.com/icon/globe/) `upstream`
  (`upstream/master`, `upstream/foo`, `upstream/bar`)

Could also use ☁️, but there isn’t a plain octicon-cloud.

**Comment by shiftkey** [comment]
I'm going to move the discussion about grouping ideas over to #4327 as a way to reset this discussion.
