### ISSUE TITLE
I can't push because it says that I am not allowed to make changes to my own repository

### ISSUE THREAD

**Issue by rjthalman** [desktop/desktop#4100]
### Description

I can't push request. It says I don't have access and to sign in again.  Then I do and same thing. some how I locked myself out?

### Version

**GitHub Desktop version:** 1.0.12

**OS version:** 10.13.2

### Steps to Reproduce

1. open desktop
1. select files to push
1. push, then error message
<img width="1160" alt="screenshot 2018-02-26 10 22 43" src="https://user-images.githubusercontent.com/35240483/36688037-2079243a-1ae0-11e8-8e1a-f83d22237e10.png">

**Expected behavior:** the push to update my web page

**Actual behavior:** error message and a headache

**Reproduces how often:** every time since satruday

**Comment by shiftkey** [comment]
@rjthalman thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by rjthalman** [comment]
I updated it. sorry I only had a bit of time saturday to report the issue. thanks

**Comment by rjthalman** [comment]
[2018-02-24.desktop.production.log](https://github.com/desktop/desktop/files/1764085/2018-02-24.desktop.production.log)

**Comment by rjthalman** [comment]
please help I am using this per my CIT college course. I have dead lines. thanks

**Comment by shiftkey** [comment]
@rjthalman two things:

> 2018-02-26T22:22:00.052Z - error: [ui] Error checking for updates
Error: Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. See https://github.com/Squirrel/Squirrel.Mac/issues/182 for more information.

This is related to updating the application, and it's being reported that you need to move the app into the `/Applications` directory.

> 2018-02-24T22:31:00.533Z - error: [ui] Error adding account 'rjthalman'
Error: The user name or passphrase you entered is not correct.

This is occurring during sign-in, and seem to be related to a known issue with the keychain explained [here](https://github.com/desktop/desktop/blob/master/docs/known-issues.md#the-username-or-passphrase-you-entered-is-not-correct-error-after-signing-into-account---3263) in more detail.

Apply the workaround and try signing into the app again.

**Comment by shiftkey** [comment]
@rjthalman I'm going to close this out as known existing issues, but please reach out if you're still having issues.
