### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by gauravinstasafe** [desktop/desktop#4101]
Extracted from issue title:

> Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.

### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by shiftkey** [comment]
@gauravinstasafe thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Could you also the full log files? The **Help** | **Show Logs in Explorer/Finder** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

Thanks for understanding and meeting us half way 😀

**Comment by bretticus** [comment]
It's a shame actually. Wish I wouldn't have upgraded. I still like the simplicity of this app to just  see what changes are staged. It used to do other things that I really liked though: Automatic stashiing when switching branches or being able to authenticate using SSH settings. I prefer to use SSH over HTTPS so with my existing local repo configured like (this for ages now,) I get the Authentication failed error when I try any operation that hits github. Now I just use the command line and native git to do remote operations. 😦

**Comment by 1andee** [comment]
Experiencing a similar issue on macOS Sierra 10.12.6.
Reinstalled GitHub Desktop (v1.1.0) with nil change.

No problem accessing or contributing to this repo via CLI.

```
018-03-01T18:32:19.235Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.118s)
2018-03-01T18:39:15.255Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
(node:39986) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: The user name or passphrase you entered is not correct.
(node:39986) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/redacted/redacted.git/'

(The error was parsed as 3: Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open preferences and verify that you're signed in with an account that has permission to access this repository.)
```

**Comment by shiftkey** [comment]
@bretticus would you mind opening a new issue to report your SSH setup now not working? If you've got a working `ssh-agent` setup then Desktop should just kick out to that - we shouldn't be interfering with that.

**Comment by shiftkey** [comment]
Closing as inactive. @gauravinstasafe if you are able to provide the log files we're happy to troubleshoot further.
