### ISSUE TITLE
When uploading to Git LFS (Git Large Files) progress bar flickers with random data

### ISSUE THREAD

**Issue by Muchaszewski** [desktop/desktop#4102]
### Description

> Gif recorded in 144fps so it might not look all that bad!

![wierd](https://user-images.githubusercontent.com/5092066/36646144-13d43cf4-1a74-11e8-9890-3c30fc09889e.gif)

When uploading to Git LFS progress bar is not readable as values run up and down for both files to upload and amount of bytes left to upload.

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** Microsoft Windows [Version 10.0.16299.248]

### Steps to Reproduce

1. Add LFS to your existing project
1. Add multiple files to track using LFS (in my case it was 205 around 20-50mb each)
1. Push

**Expected behavior:** Consistent progress bar where values only go up. (At least for files left to upload). Consider change to percentage values, instead of current file display

**Actual behavior:** Probably multiple files are being sent at once and display cannot decide which to display. So it looks like on gif above.

**Reproduces how often:** 100%

**Comment by shiftkey** [comment]
@Muchaszewski thanks for the feedback! We're already tracking this in #3171 and there's some extra context there around the underlying problem. Please follow along with that issue...
