### ISSUE TITLE
Error for Commit to Master

### ISSUE THREAD

**Issue by cheahengsoon** [desktop/desktop#4103]
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

#### Additional Information

Error: write EOF
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite (net.js:813:14)

Version: 1.0.13
OS: Windows 10.0.16299

**Comment by shiftkey** [comment]
@cheahengsoon thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by shiftkey** [comment]
Closing as inactive. @cheahengsoon I _think_ this was fixed by #4058 which is in 1.1.0, but if you encounter the issue in a later version and are able to provide fresh logs we're happy to revisit it.
