### ISSUE TITLE
The user name or passpharse you entered is not correct

### ISSUE THREAD

**Issue by mzdhr** [desktop/desktop#4104]
### Description

I can't log in to github in the desktop app.

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** macOS High Sierra verson 10.13.3

### Steps to Reproduce

1. [First step]
Open Github Desktop app.
1. [Second step]
Try to log in using Github email and pass.
1. [and so on]
Even Sign in using your browser option in not working.

**Expected behavior:** to log in

**Actual behavior:** password in not correct

**Reproduces how often:** all the time

### Logs

Attached

#### Additional Information
I can log in fine on Github website. But can't in Desktop App.

[2018-02-26.desktop.production.log](https://github.com/desktop/desktop/files/1757757/2018-02-26.desktop.production.log)

**Comment by shiftkey** [comment]
@mzdhr I think this is related to the keychain being locked. There are instructions to try and unlock the keychain [here](https://github.com/desktop/desktop/blob/known-issues-doc/docs/known-issues.md#macos) - could you try those out and see if it fixes your problem?

**Comment by mzdhr** [comment]
Thanks @shiftkey that solve my problem.
