### ISSUE TITLE
failed: SEC_E_UNSUPPORTED_FUNCTION (0x80090302)

### ISSUE THREAD

**Issue by mohamedkhairy** [desktop/desktop#4108]
when I try to publish my project on github form git bash or github desktop version this message pop up

![capture](https://user-images.githubusercontent.com/8893078/36680069-7acc51cc-1b1d-11e8-8536-a092cc9f2af9.PNG)

**Comment by tierninho** [comment]
@mohamedkhairy please fill out the template details so we have some more info. thanks!

**Comment by iAmWillShepherd** [comment]
This may be a TLS or SSL related issue. @shiftkey is this a symptom of either of those two things changing on Windows?

**Comment by j-f1** [comment]
It’s probably got something to do with https://github.com/blog/2507-weak-cryptographic-standards-removed.

**Comment by shiftkey** [comment]
@iAmWillShepherd @j-f1 I think the original issue is around SChannel in Desktop again. There's more details here as well as a workaround: https://github.com/desktop/desktop/blob/eb4e56637f816a99ac2f32cf699f61be763892fb/docs/known-issues.md#certificate-revocation-check-fails---3326

@mohamedkhairy can you run this command in your Git Bash for me - you might need to update Git for Windows as well as apply that workaround:

```
$ git version
```

**Comment by mohamedkhairy** [comment]
@shiftkey it give me this
git version 2.16.2.windows.1

**Comment by shiftkey** [comment]
@mohamedkhairy for your issue with the Git command line, I'd recommend reading over this upstream issue https://github.com/git-for-windows/git/issues/1522 as it's separate to Desktop and feels very similar to what you're dealing with.

For the issue inside GitHub Desktop, the workaround for [this known issue](https://github.com/desktop/desktop/blob/eb4e56637f816a99ac2f32cf699f61be763892fb/docs/known-issues.md#certificate-revocation-check-fails---3326) should resolve it.

**Comment by mohamedkhairy** [comment]
it is fine when I delete this line -> sslVersion = tlsv1.0  from the .gitconfig file

**Comment by j-f1** [comment]
Should GitHub Desktop do that automatically for GitHub repositories?

**Comment by shiftkey** [comment]
@j-f1 we had Strong™ Opinions™ about your global configuration in Desktop Classic about things like this, but we haven't had a need to revisit that with Desktop Electron - things have changed a lot since then, and most people don't specify `sslVersion` manually these days...
