### ISSUE TITLE
Move "forgot password" link below/after password input

### ISSUE THREAD

**Issue by francisrath** [desktop/desktop#4109]
### Description

When logging in with your GitHub account, the next tab stop after username is "Have you forgotten your password" or similar wording. It should probably be the password input instead.

~~Also, if you have 2FA enabled it would be nice if the code input was focused.~~ Moved to #4132

### Version

**GitHub Desktop version:** 1.0.13
**OS version:** Microsoft Windows [Version 10.0.16299.248]

### Steps to Reproduce

1. Open GitHub Desktop
2. File -> Options
3. Sign in (only tested github.com, not enterprise)

**Comment by tierninho** [comment]
No focus for the 2FA code on OSX either. 

![screen shot 2018-02-26 at 11 18 37 am](https://user-images.githubusercontent.com/14828183/36690353-e88978e8-1ae6-11e8-9fe3-8678188eb25e.png)
![screen shot 2018-02-26 at 11 19 04 am](https://user-images.githubusercontent.com/14828183/36690352-e86b1114-1ae6-11e8-84a7-972559e0a38b.png)

**Comment by shiftkey** [comment]
@francisrath thanks for the feedback!

We had a discussion about this ages ago in https://github.com/desktop/desktop/pull/1513#issuecomment-305205528, which I'll cross-reference here.

> We talked this over internally. The problem with changing the `tabIndex` is that it makes the view less accessible by making the onscreen order and tab index different. **The solution we'd prefer is reordering the actual onscreen elements.**

I'm not sure if we're into doing the reordering of the onscreen elements, so I'll ask @desktop/design to chime in here and clarify where we currently stand.

@tierninho could you open a fresh issue for the focus issue? I think adding `autoFocus={true}` to the right textbox should be easy enough to address that.

**Comment by francisrath** [comment]
@shiftkey I see your point about tab order matching the visual layout, but I am guessing 95%+ of the use cases will be logging in with a known password. Maybe consider moving the "Forgot password?" link below the password input to match the tab order?

Looks like the suggestion already came up in #1513 but still think it's a good idea to make the most common actions the easiest to perform :)

**Comment by nerdneha** [comment]
> Maybe consider moving the "Forgot password?" link below the password input to match the tab order?

right on, @francisrath! we invite you or anyone in the company to take a stab at this and open a PR! (You can refer to #2263 for an example of a similar PR in the past). 

Here are some factors to consider when starting this PR:

1. *What does it look like with longer copy?*
  The copy (text) is currently `Forgot password?` and @francisrath suggested `Have you forgotten your password?`. Should we a) keep it as original, b) change it to their suggestion or c) make it a fuller sentence? Ideally, we opt for something intuitive and visually pleasing (we want it to look properly balanced next to the text inputs)

2. *How does it affect the custom divider that we have there?*
  Before the copy was on the same line as `Password` but if we move it below, it'll be on its own. Should we provide extra spacing? What might that look like so it feels like it belongs to the "password" section?

3. *Should we try to cram it in the dialog footer instead?*

--

Some helpful tips for completing a PR:
* If you want to take this issue, assign yourself to it
* Include `Fixes #4109` at the top of the description for your PR and a checklist as you progress through (helpful for you and us!)
* read our [PR process doc](https://github.com/desktop/desktop/blob/master/docs/process/reviews.md) to understand how we do PRs in this repo and what code review looks like
* When you finish the PR, add the `ready-for-review` label, include before/after screenshots in the description, and describe any major changes
* Make sure to test on both Windows and MacOS
* cc @desktop/design in your PR

**Comment by j-f1** [comment]
> When you finish the PR, add the `ready-for-review` label

You have to have write access to do that.

**Comment by nerdneha** [comment]
@j-f1 good catch! i updated my comment so it's clearer earlier on. (so if others are viewing, you won't see the original text @j-f1 corrected)

**Comment by iamnapo** [comment]
Hello 😃,
I'd like to take a shot at it.
