### ISSUE TITLE
Timeout in cloning repositories

### ISSUE THREAD

**Issue by Ebeid** [desktop/desktop#4116]
### Description

I'm unable to clone any repository. This is a brand new machine. I installed GitHub desktop on it and tries to clone repositories but always give me the flowing error after a while

Cloning into 'C:\..\..\'...
fatal: unable to access 'https://github.com/././': Failed to connect to github.com port 443: Timed out

### Version

**GitHub Desktop version:** [1.1.0]

**Comment by iAmWillShepherd** [comment]
Thanks for reaching out!

We require the template to be filled out with all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀

**Comment by shiftkey** [comment]
@Ebeid is there something interesting about the repository or your internet connection that might help explain the issue? The "timed out" message suggests a connectivity issue when cloning down the repository, and I'm not sure how much we can do about this in Desktop.

**Comment by Ebeid** [comment]
It was the firewall that is not working as expected. Although port 430 was open, the request was blocked. Switched to another network for the moment and everything works. Sorry for the interruptions

**Comment by maburns2** [comment]
I have the same problem.

**Comment by j-f1** [comment]
@maburns2 Please open a new issue & fill out the issue template.

**Comment by shadab97** [comment]
i faced the same issue due to proxy servers i use then i stopped the server clone it restart the server

**Comment by steveward** [comment]
@shadab97 I'm not sure I understand the issue you are having. If you are continuing to run into a specific problem with GitHub Desktop please open a new issue and fill out the template. Thanks!

**Comment by Hydsiun** [comment]
克隆时不能用代理服务器吗？那太不方便了

**Comment by TouficWehbeMeg** [comment]
> 克隆时不能用代理服务器吗？那太不方便了

尝试让我们知道
