### ISSUE TITLE
 fatal: unable to access 'H://.gitconfig': Invalid argument

### ISSUE THREAD

**Issue by joerg1985** [desktop/desktop#4119]
### Description

After the application is started an error dialog is shown 'fatal: unable to access 'X://.gitconfig': Invalid argument'. It is not possible to use github desktop anymore,

### Version

since 1.1.0, last working version 1.0.13

**GitHub Desktop version:** 1.1.0

**OS version:** Microsoft Windows [Version 6.1.7601]

### Steps to Reproduce

1. run GitHub Desktop

**Expected behavior:** no error message

**Actual behavior:** error message

**Reproduces how often:** allways / no workaround

### Logs

2018-02-27T10:15:16.948Z - error: [ui] `git status --untracked-files=all --branch --porcelain=2 -z` exited with an unexpected code: 128.
fatal: unable to access 'X://.gitconfig': Invalid argument

2018-02-27T10:15:17.025Z - error: [ui] `git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(committer)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%(trailers:unfold,only)%00%1F refs/heads refs/remotes` exited with an unexpected code: 128.
fatal: unable to access 'X://.gitconfig': Invalid argument

2018-02-27T10:15:17.057Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
fatal: unable to access 'X://.gitconfig': Invalid argument

#### Additional Information

The home drive (X:) is hidden to the user and mapped to a network share.

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

This issue feels pretty close to [this known issue](https://github.com/desktop/desktop/blob/master/docs/known-issues.md#using-a-repository-configured-with-folder-redirection---2972)

**Comment by shiftkey** [comment]
@iAmWillShepherd I wouldn't be so sure:

> since 1.1.0, last working version 1.0.13

@joerg1985 this error looks like it might be related to our version of Git - do you have a command line version of Git installed? Are you able to run these commands against the repository and tell me what they return:

```
$ git status
$ git version
```

**Comment by nerdneha** [comment]
Hi there, I'm going to close this out due to inactivity but if you can provide more details about the issue, we're happy to re-open and help!

**Comment by BvdVen** [comment]
I was able to solve it by adding HOME to the enviroment variables and directing it to the folder with al my repositories.

**Comment by Satyajeet-Kumar** [comment]
I got this error today. 
I found that there is file on my H drive H:\.gitconfig, which is also a network drive(home drive from office).
I saw that this file was an empty file and It was not changed for a week but it worked fine last friday. 

I had a backup at the same location I copied the content in the file and it worked.
Content of the file:
[winUpdater]
	recentlySeenVersion = 2.21.0.windows.1
[http]
	sslVerify = false
[merge]
	tool = kdiff3
[diff]
	guitool = kdiff3
[core]
	editor = \"C:/appl/GitExtensions/GitExtensions.exe\" fileeditor

**Comment by KorayKinik** [comment]
Satyajeet, et al., thanks! 
I found the .gitignore file and added your content and my SourceTree is back.
(But I simply don't understand why/how this happened in the first place..)

**Comment by turbolego** [comment]
Thanks @Satyajeet-Kumar this copying the contents of the file ".gitconfig.backup" to the file ".gitconfig" (that was empty) worked for me.

After the copypaste i restarted my machine and ran Sourcetree, and now the .gitconfig file has more content than it had in the .gitconfig.backup file.

**.gitconfig.backup:**

`[merge]
	tool = kdiff3
[diff]
	guitool = kdiff3
[core]
	editor = \"C:/Program Files (x86)/GitExtensions/GitExtensions.exe\" fileeditor
[mergetool "kdiff3"]
	path = C:/Program Files/KDiff3/kdiff3.exe
[difftool "kdiff3"]
	path = C:/Program Files/KDiff3/kdiff3.exe
`

**.gitconfig after copypaste and restart:**

`[merge]
	tool = kdiff3
[diff]
	guitool = kdiff3
[core]
	editor = \"C:/Program Files (x86)/GitExtensions/GitExtensions.exe\" fileeditor
[mergetool "kdiff3"]
	path = C:/Program Files/KDiff3/kdiff3.exe
[difftool "kdiff3"]
	path = C:/Program Files/KDiff3/kdiff3.exe
[difftool "sourcetree"]
	cmd = '' \"$LOCAL\" \"$REMOTE\"
[mergetool "sourcetree"]
	cmd = "'' "
	trustExitCode = true
`

**Comment by sankalp44052** [comment]
I Also faced this issue , i tried many things but did not work.
Finally , I checked the file property of .gitconfig and saw it was marked as "archive"  , I removed and created fresh new blank file.  in Parallel  in reinstalled source tree. 
It worked ...

**Comment by MuhammedGenco94** [comment]
This command has solved my problem: 
`net use H: /delete`

**Comment by nklsla** [comment]
> This command has solved my problem: `net use H: /delete`

Thanks, this solved it for me!
