### ISSUE TITLE
When creating a new branch, default the branch from to the branch that is currently checked out

### ISSUE THREAD

**Issue by curranlipsett** [desktop/desktop#4121]
### Description

When I want to create a new branch, master is always selected as the branch to create the new branch from. I'd like Github Desktop to either default to my currently checked out branch, or give me the option to define which branch I'd like selected by default.

### Version

**GitHub Desktop version:** 1.1.0

**OS version:** Microsoft Windows [Version 10.0.16299.248]

#### Additional Information

I'd be able to look into making this fix if that's something that would be helpful. Just let me know!

**Comment by niik** [comment]
Hey @curranlipsett, thanks for opening this. I'm going to refer you to https://github.com/desktop/desktop/issues/2322 and the discussion in https://github.com/desktop/desktop/pull/2330, feel free to add to that discussion.

I'll close this issue out since there's been prior discussion elsewhere.

**Comment by curranlipsett** [comment]
Sounds good, thanks @niik
