### ISSUE TITLE
Merged pull request still shown in Desktop several hours after merging/closing

### ISSUE THREAD

**Issue by OllyMcBrideOB** [desktop/desktop#4122]
### Description

When a pull request is created, it is shown in the 'Pull requests' tab in the 'Current branch' menu. I then navigate to GitHub.com and merge the commit, but the pull request is still shown in GitHub desktop 'Pull requests' tab. 

If I continue to commit to this branch and then try and 'Create a pull request', the menu option has changed to 'Show pull request' and does not allow me to create a pull request (even though the previous pull request has already been merged).

### Version

**GitHub Desktop version:** 1.1.0

**OS version:** Windows 10

### Steps to Reproduce

1. Create branch and perform a commit
1. Create and approve a pull request
1. Perform another commit on the same branch
1. Try and create another pull request

**Expected behavior:** I should be able to create another pull request after the previous one has been merged

**Actual behavior:** IThe menu item has changed, only allowing me to show the previous pull request

**Reproduces how often:** Every time

#### Additional Information

This has only happened since GitHub Desktop v1.1.0

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

This is expected behavior. We check for updates at a specific interval so desktop will always lag behind dotcom a bit.

**Comment by OllyMcBrideOB** [comment]
It's been 2 hours and the pull request has not been updated from dotcom.

**Comment by iAmWillShepherd** [comment]
> It's been >2 hours and the pull request has not been updated from dotcom

That's an important detail that was missing. Have you tried manually fetching changes?
![2018-02-27_11-31-33](https://user-images.githubusercontent.com/1715082/36744254-f1a85e64-1bb1-11e8-83b3-c478872b6925.png)

**Comment by OllyMcBrideOB** [comment]
My apologies.

I have tried manually fetching changes and this has not fixed the issue.

I have also tried closing and re-opening desktop, but that has also not changed things.

**Comment by iAmWillShepherd** [comment]
That green check is a commit status (in my case CI). You will only see it if you are using GitHub integrations in your repo. Is the repo you are having trouble with public? If so, I can try to reproduce with your repo.

**Comment by tierninho** [comment]
@OllyMcBrideOB 

I tried to reproduce, here is what I am seeing: 

1. Create branch and perform a commit in Desktop
2. Create pull request on GitHub.com <Desktop menu now says "Show Pull Request">
3. Merge pull request on GitHub.com <Desktop menu now says "Create Pull Request">
4. Perform another commit in Desktop on the same branch  <Desktop menu now says "Create Pull Request">
5. Try and create another pull request  <Desktop menu now says "Show Pull Request">

Sounds right?

**Comment by rag4214** [comment]
I'm having the same issue, my pull request is still there 15 hours later after closing it.

**Comment by shiftkey** [comment]
I've been able to reproduce this, and it's related to the merged PR being the **last** PR in the repository. This is unrelated to the whole "open a new branch to create a new PR" discussion.

See #4148 for the fix.

**Comment by SASFMONTOYA** [comment]
This issue continue... My issue is #4241

**Comment by jlurena** [comment]
Same issue here, but on web not desktop

**Comment by shiftkey** [comment]
@jlurena please contact [GitHub Support](https://github.com/contact) if you'd like someone to investigate the behaviour on the GitHub website.

**Comment by sunefischer** [comment]
Any solution to this? 
I current have two PR which remains open even after they are merged and branches are deleted, it's been 9 days now. I remember getting an error message as they got merged but they did in fact merge. Somehow this has messed up the state on the PR so it now remains in open state and I don't see a manual override to close or delete it.

**Comment by Nosferican** [comment]
I am having the same issue on Mac Catalina,
<img width="962" alt="Screen Shot 2019-10-15 at 15 33 51" src="https://user-images.githubusercontent.com/2529329/66863540-3580a400-ef61-11e9-818a-40c315cd5ba0.png">
https://github.com/Nosferican/EconJobMarket.jl
There was a previous repo there...

**Comment by atulpatill** [comment]
Same issue in 2021 Nov

**Comment by ojvribeiro** [comment]
Same issue today (Feb 2023). The PR was merged on the last Friday, but still shows as open on Desktop even if I click on the Fetch or the Refresh button.

![image](https://user-images.githubusercontent.com/8026741/220725816-9352fa0d-aa81-4b1f-971d-caddc3de9b49.png)

![image](https://user-images.githubusercontent.com/8026741/220726261-4e7f47a3-9ac2-4fac-b7d3-5f086e39bcb0.png)

**Comment by dillontrembath** [comment]
Same issue in 2025. Anyone figured this out?
