### ISSUE TITLE
Yoast SEO Pinterest Product Rich Pins data not showing

### ISSUE THREAD

**Issue by 2ccontacts** [desktop/desktop#4123]
Hi - first time user, my apologies for any mistakes made or missing info.

I own basketcasegifts.shop - my rich pins for Pinterest are not showing the price, currency, and availability in the product pin because the meta tags are not entered right. I've pasted my findings below from the page source of one product. (view-source:https://basketcasegifts.shop/shop/subscription-boxes/spoil-her-lots-more-box-general-holidays/)

<meta property="og:image:height" content="700" />
--
  | <meta property="product:price:amount" content="55"/>
  | <meta property="product:price:currency" content="CAD"/>
  | <meta property="product:availability" content="instock"/>
  | <meta name="twitter:card" content="summary" />

As you can see the middle three are missing the required space between the closing quotation mark and the forward slash.  

My question is what file do I go to in order to fix this so that my rich pins display properly?

Thank you

**Comment by tsarovaT** [comment]
Maybe you are not avtorizathion in system

**Comment by shiftkey** [comment]
@2ccontacts this repository is related to the GitHub Desktop client. I closed this out as spam because this is not the place to be asking support questions for Wordpress/Woocommerce projects.
