### ISSUE TITLE
branch list containing many forks and refs is hard to navigate

### ISSUE THREAD

**Issue by thinkyhead** [desktop/desktop#4127]
**Background:** I work with a dozen remotes —forks of my project— at any given time, as I need to edit and rebase submitted PRs and push changes back to those remotes. Since "git remote add" brings in all their branches there are >100 branches listed in the Branches dropdown list.

**Request:** I'd like to be able to collapse the remotes in the list to reduce the number of top-level items and reduce visual noise.

**Comment by shiftkey** [comment]
@thinkyhead thanks for the feedback! We have [code](https://github.com/desktop/desktop/blob/67eb592cc0c5b7c396206b2b5ba30293c0c85c9a/app/src/lib/stores/pull-request-store.ts#L208-L230) for tidying up remotes that aren't associated with any open PRs, so hopefully that tidies up the unnecessary remotes over time.

@desktop/core I found this feedback in reply to our tweet announcing 1.1, and wanted to hear your we might balance the new PR experience (of adding remotes for forks) with the branch list in it's current form. 

A quick win might be to make the branch list hide these `github-desktop-*` refs. Thoughts?

**Comment by thinkyhead** [comment]
I do most of my work, such as [cloning dev branches](https://github.com/MarlinFirmware/Marlin/blob/bugfix-1.1.x/buildroot/share/git/mfnew), cleaning up [merged and deleted](https://github.com/MarlinFirmware/Marlin/blob/bugfix-1.1.x/buildroot/share/git/mfclean) branches, [opening PRs](https://github.com/MarlinFirmware/Marlin/blob/bugfix-1.1.x/buildroot/share/git/mfpr), [rebasing](https://github.com/MarlinFirmware/Marlin/blob/bugfix-1.1.x/buildroot/share/git/mfrb) (always rebase, never merge), etc. using small [helper scripts](https://github.com/MarlinFirmware/Marlin/tree/bugfix-1.1.x/buildroot/share/git) tailored to our development branches, but I find GitHub Desktop invaluable for many things.

I assume that it requires a Github API call (?) to find out whether a branch is associated with a PR. So being able to clean up remotes not associated with a PR would be a very handy addition, and would definitely solve my main issue, which is having a lot of irrelevant branch refs hanging around.

**Comment by shiftkey** [comment]
> I assume that it requires a Github API call (?) to find out whether a branch is associated with a PR. 

We work backwards from the list of open PRs to find the remotes that we no longer need to track, and the open PRs list is refreshed every 10 minutes.

**Comment by shiftkey** [comment]
I'm going to move this tweak into `1.1.x` subject to feedback from others:

> A quick win might be to make the branch list hide these `github-desktop-*` refs. Thoughts?

**Comment by shiftkey** [comment]
I've opened #4150 with my proposed solution to this - please sound off there!
