### ISSUE TITLE
Feature Request: Commit Message History

### ISSUE THREAD

**Issue by fivesoftware** [desktop/desktop#4129]
### Description

I normally use a ticket reference in the Summary field when committing changes. Then add any commit specific information in the description field. It would be a helpful feature to allow re-using of previously entered Summary messages. This is a feature I used regularly in TortoiseGit until recently trying GitHub Desktop. TortoiseGit stores recent commit log messages that you enter. These are stored per repository.

![image](https://user-images.githubusercontent.com/785827/36787302-9b14ece0-1c81-11e8-81bc-173d8caf3d44.png)

### Version
**GitHub Desktop version:** 1.0.13
**OS version:** Windows 10 Enterprise

**Comment by Kubrix** [comment]
This might be useful but this should be an option like "Show recent commit messages". GitHub might collect those messages but it should show the history only when the option is active.

**Comment by shiftkey** [comment]
@fivesoftware thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by fivesoftware** [comment]
@shiftkey thanks!

**Comment by billygriffin** [comment]
@fivesoftware Thanks for the suggestion. We haven't heard that many others suffer from this problem of needing to reuse commit messages, and commit messages became quite a bit easier when we landed a recent PR for default commit messages (like Update README.md), so hopefully that helps speed up your workflow. I'm going to remove the `future-proposal` label to indicate that we don't intend to support this. We're always open to revisiting if we continue to hear that the current commit message flow isn't working for folks. Thanks again!

**Comment by doron-matific** [comment]
How was this closed? This is a feature in every other tool out there...

**Comment by yathu-arulnanthy-gtg** [comment]
Many other git tool has this feature and it would make the workflow of many easier, can you please support it.
