### ISSUE TITLE
Authentication failing

### ISSUE THREAD

**Issue by Kizmar** [desktop/desktop#4131]
### Description
I've been using this with VSO projects for a while now, and all the sudden this morning authentication isn't working when I try to pull. This app keeps saying authentication failed and popping up the login dialog.

I can do a `git pull` in command line just fine. I tried SourceTree to do the same thing and it also worked fine.

Looking at the debug console, there are no errors, and it doesn't look like it's even making a network call.

### Version
**GitHub Desktop version:** 1.1.0
**OS version:** Windows 10

### Steps to Reproduce

1. Have existing VSO repo added 
2. Try to pull update from origin

**Expected behavior:** Pulls with successful authentication

**Actual behavior:** Authentication fails repeatedly

**Reproduces how often:** Any time I try to access the VSO repos

### Logs
This is the log file from me opening the app, trying to log in, getting the authentication failed message, then cancelling.
> 2018-02-28T13:08:09.747Z - info: [ui] [AppStore] loading 16 repositories from store
> 2018-02-28T13:08:09.747Z - info: [ui] [AppStore] found account: OMITTED
> 2018-02-28T13:08:10.183Z - info: [ui] launching: 1.1.0 (Windows 10.0.16299)
> 2018-02-28T13:08:10.183Z - info: [ui] execPath: 'C:\OMITTED\AppData\Local\GitHubDesktop\app-1.1.0\GitHubDesktop.exe'
> 2018-02-28T13:08:22.391Z - info: [ui] Executing pull: git -c credential.helper= pull --no-rebase --progress origin (took 1.580s)
> 2018-02-28T13:08:30.938Z - info: [ui] storing generic credentials for 'OMITTED' and 'OMITTED'
> 2018-02-28T13:08:32.380Z - info: [ui] Executing pull: git -c credential.helper= pull --no-rebase --progress origin (took 1.248s)

**Comment by ericdrobinson** [comment]
I'm experiencing something similar (VSO is now [VSTS](https://www.visualstudio.com/vso/) [Visual Studio Team Services]).

**Pushing** to VSTS repositories currently doesn't work for me. That said, this _also_ affects Visual Studio Code and the git command line utility so I assume that something is broken on Microsoft's end(?).

I haven't tried this yet myself, but perhaps using a [Personal Access Token](https://stackoverflow.com/a/34010174/5285364) (rather than username+password combo) will work...?

**Comment by ericdrobinson** [comment]
@Kizmar I just tried again and succeeded. It appears that Microsoft may have resolved the issue on their end. Perhaps test again?

**Comment by shiftkey** [comment]
@ericdrobinson thanks for confirming it's now resolved.

@Kizmar please confirm this was an intermittent issue.

**Comment by Kizmar** [comment]
@shiftkey Yeah it's working again this morning.
