### ISSUE TITLE
When renaming/moving a file unable to view old path.

### ISSUE THREAD

**Issue by blanchg** [desktop/desktop#4146]
### Description

When renaming a file with even a moderately long path the history tab correctly shows it as a move but both names are truncated in the middle with ...  There is a tooltip that shows the new name in full but there is no tooltip that shows the old name in full.

### Version

**GitHub Desktop version:** 1.1.0

**OS version:** macOS 10.13.3

### Steps to Reproduce

1. Rename or move a file that has a long path or filename
1. Commit the change so it is visible in the history
1. Try to view the old filename/location

**Expected behavior:** Either a tooltip to show the full path before and after or be able to resize the file listing box larger to see it (preferably both)

**Actual behavior:** Tooltip only shows the destination filename and the file listing can't be resized beyond a certain amount
![image](https://user-images.githubusercontent.com/86495/36870092-a0692b2a-1de9-11e8-8e27-4432eb38a72c.png)

**Reproduces how often:** Every time

**Comment by shiftkey** [comment]
@blanchg the tooltip is related to the file path you are looking at - so hovering over the old path should show the tooltip containing the full old path:

<img width="321" src="https://user-images.githubusercontent.com/359239/36872758-6f8e48d0-1dfa-11e8-8fc9-0baad45c84c8.png">

Or hovering over the new path should show the full new path:

<img width="458" src="https://user-images.githubusercontent.com/359239/36872759-6fc1c61a-1dfa-11e8-84bb-71f1ea127ff3.png">

The changes list can also be expanded a bit to provide a bit more room. Does that help clarify things?

**Comment by blanchg** [comment]
Yes you are right, my apologies, it would be nice if the list could be
expanded more than it does though especially for renames trying to see
multiple when the contents of the massive right hand pane is "The file was
renamed but not changed".

It is quite painful still to see where multiple files were moved from -> to.

Thanks

Glen.

**Comment by shiftkey** [comment]
@blanchg please follow along with the discussion in #2745 about that constraint and particularly this comment: https://github.com/desktop/desktop/issues/1588#issuecomment-329405096
