### ISSUE TITLE
I don't know how to view all my repositories

### ISSUE THREAD

**Issue by thec0deguru** [desktop/desktop#4151]
### Description

[I am new to Github and I have forked some repositories to get started, but I can't seem to be able to view them. I am only able to view the first repository I created. How can I view other repositories? Thanks.]

### Version

**GitHub Desktop version:** [1.1.0]

**OS version:** [Microsoft Windows [Version 10.0.16299.125]]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by j-f1** [comment]
You have to go to File → Clone repository…, then select your fork to download it.

**Comment by WorkShop-Office** [comment]
Ok

**Comment by shiftkey** [comment]
I think we're good here - thanks @j-f1 for the fast reply.

@thec0deguru please reply if you have any other questions!
