### ISSUE TITLE
Add hooks so that the Developer Tools Console can be used to debug the running app

### ISSUE THREAD

**Issue by lee-dohm** [desktop/desktop#4152]
### Description

In working on the PR for #3720, I found myself missing something that is very helpful in testing out new code or ideas in Atom. In Atom, there is the `atom` global that is the gateway into the entire [Atom public API](https://atom.io/docs/api/latest), which can be accessed directly from the Developer Tools Console in any Atom window. This is very helpful for new community developers to learn how Atom works under the covers without having to write a full package to test their theories.

It might be useful for there to be a `desktop` global with hooks to various key state stores that could be probed for information or even the state altered in specific ways. This would be helpful for community developers to learn how Desktop works interactively.

### Version

**GitHub Desktop version:** v1.1.1-beta1

**OS version:** Mac OS X 10.13.3

### Steps to Reproduce

1. Launch GitHub Desktop
1. Press <kbd>Shift+Cmd+I</kbd> to open the developer tools
1. Click the Console tab
1. Type `desktop.appStore.getRepositoryState()`

**Expected behavior:** Get an object describing the repository's state

**Actual behavior:** `Uncaught ReferenceError: desktop is not defined`

**Comment by shiftkey** [comment]
@lee-dohm 

![](https://media.giphy.com/media/KQm5O05y9rzQA/giphy.gif)

**Comment by j-f1** [comment]
It would also be useful to have an API that lets you paste in a stack trace and get the source-mapped version.

**Comment by shiftkey** [comment]
I'm going to mark this as `help wanted` as I think it's ideal for someone external who wants to poke at the codebase a bit more - otherwise it might be a neat Hack Week™ project for someone to grab.

**Comment by MagicMarvMan** [comment]
I would like to work on that issue. I will open a PR in a few days. :octocat: :+1:

**Comment by Nonameinfo** [comment]
> ### Description
> In working on the PR for #3720, I found myself missing something that is very helpful in testing out new code or ideas in Atom. In Atom, there is the `atom` global that is the gateway into the entire [Atom public API](https://atom.io/docs/api/latest), which can be accessed directly from the Developer Tools Console in any Atom window. This is very helpful for new community developers to learn how Atom works under the covers without having to write a full package to test their theories.
> 
> It might be useful for there to be a `desktop` global with hooks to various key state stores that could be probed for information or even the state altered in specific ways. This would be helpful for community developers to learn how Desktop works interactively.
> 
> ### Version
> **GitHub Desktop version:** v1.1.1-beta1
> 
> **OS version:** Mac OS X 10.13.3
> 
> ### Steps to Reproduce
> 1. Launch GitHub Desktop
> 2. Press Shift+Cmd+I to open the developer tools
> 3. Click the Console tab
> 4. Type `desktop.appStore.getRepositoryState()`
> 
> **Expected behavior:** Get an object describing the repository's state
> 
> **Actual behavior:** `Uncaught ReferenceError: desktop is not defined`

**Comment by Mellbabe** [comment]
> ### Description
> In working on the PR for #3720, I found myself missing something that is very helpful in testing out new code or ideas in Atom. In Atom, there is the `atom` global that is the gateway into the entire [Atom public API](https://atom.io/docs/api/latest), which can be accessed directly from the Developer Tools Console in any Atom window. This is very helpful for new community developers to learn how Atom works under the covers without having to write a full package to test their theories.
> 
> It might be useful for there to be a `desktop` global with hooks to various key state stores that could be probed for information or even the state altered in specific ways. This would be helpful for community developers to learn how Desktop works interactively.
> 
> ### Version
> **GitHub Desktop version:** v1.1.1-beta1
> 
> **OS version:** Mac OS X 10.13.3
> 
> ### Steps to Reproduce
> 1. Launch GitHub Desktop
> 2. Press Shift+Cmd+I to open the developer tools
> 3. Click the Console tab
> 4. Type `desktop.appStore.getRepositoryState()`
> 
> **Expected behavior:** Get an object describing the repository's state
> 
> **Actual behavior:** `Uncaught ReferenceError: desktop is not defined`

**Comment by Andrewjlucas1** [comment]
#readme.md

**Comment by Andrewjlucas1** [comment]
#11283

**Comment by niik** [comment]
Going to close this old issue out. When running the app in development mode you can access the React tools in the developer tools window to get access to props and state for all components

<img width="880" alt="Screenshot showing the developer tools window with the React components tab selected" src="https://user-images.githubusercontent.com/634063/234207609-8629ce41-f822-4d1e-a39f-ad7db08c61cb.png">
