### ISSUE TITLE
Cloning gitlab URL results in GitHub repository being cloned.

### ISSUE THREAD

**Issue by grokys** [desktop/desktop#4154]
### Description

If I try to clone a gitlab.com URL that also exists on github.com, the github.com URL will be cloned instead.

### Version

**GitHub Desktop version:** 1.1.1-beta1
**OS version:** win10

### Steps to Reproduce

1. Go to File -> Clone Repository
2. select the URL tab
3. paste in https://gitlab.com/inkscape/inkscape.git 
4. Click Clone

**Expected behavior:** https://gitlab.com/inkscape/inkscape.git  is cloned

**Actual behavior:** https://github.com/inkscape/inkscape.git is cloned

**Reproduces how often:** Every time afaics

### Logs

```
2018-03-02T08:31:40.671Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.099s)
2018-03-02T08:33:18.028Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/inkscape/inkscape.git - grokys (has token)
2018-03-02T08:35:03.033Z - info: [ui] Executing clone: git -c credential.helper= clone --recursive --progress -- https://github.com/inkscape/inkscape.git D:\projects\inkscape 
```

**Comment by shiftkey** [comment]
@grokys I wish I could say this was a elaborate joke but the actual issues is a bit more mundane.

In [here](https://github.com/desktop/desktop/blob/605e35d492668f7fae4078e40934b88a897ce276/app/src/lib/find-account.ts#L95-L104) can you spot the missing context?

Here's a hint:

```ts
  // extract a repository identifier
  const repositoryIdentifier = parseRepositoryIdentifier(urlOrRepositoryAlias)
  if (repositoryIdentifier) { 
    // wait, this doesn't contain the hostname!
    const { owner, name } = repositoryIdentifier
    // and inkscape/inkscape is a public repository on GitHub, oh no!
    const account = await findRepositoryAccount(allAccounts, owner, name)
    if (account) {
      // so you can go and clone this down anonymously if you're not signed in
      return account
    }
  }

  return null
```
