### ISSUE TITLE
Can't download GitHub app from website - error 500 and 504

### ISSUE THREAD

**Issue by teinett** [desktop/desktop#4155]
Website https://desktop.github.com/ has a link "Download for MacOS" - https://central.github.com/deployments/desktop/desktop/latest/darwin.

Now (March 2, 2018) on the page https://central.github.com/deployments/desktop/desktop/latest/darwin I have an error 500 or 504, and I can't download the app.

Screenshot is attached.

<img width="1397" alt="github-500" src="https://user-images.githubusercontent.com/1038168/36904673-6233f41c-1e42-11e8-9475-bc602bb6bace.png">

Status page https://status.github.com/messages says everything is OK.

**Comment by beatrizfagundes** [comment]
Having this same problem here!

**Comment by joshaber** [comment]
Thanks @teinett, @beatrizfagundes, it looks like AWS is struggling which is having some knock on effects. We're looking into it.

**Comment by joshaber** [comment]
In the mean time, you should be able to download the latest macOS release from https://s3.amazonaws.com/github-desktop/releases/1.1.0-cfbf44c8/GitHubDesktop.zip and Windows from https://s3.amazonaws.com/github-desktop/releases/1.1.0-cfbf44c8/GitHubDesktopSetup.exe.

**Comment by joshaber** [comment]
The download links should be working again. Please let us know if you see any more problems. Thanks!
