### ISSUE TITLE
Can't Sign in to Enterprise Github account via Github Desktop

### ISSUE THREAD

**Issue by brtrx** [desktop/desktop#4159]
### Description

I can access repositories hosted on our enterprise github account via the web interface.
But trying to sign in to the native client just opens an empty chrome instance, whether or not I am already logged in on the web.

### Version

**GitHub Desktop version:** 1.1.0

**OS version:** macOS 10.13.3

### Steps to Reproduce

1. Open Github Desktop
2. Open Preferences and click Enterprise Account Sign In button
3. Enter Enterprise server address https://git.soma.salesforce.com and click Continue
4. See message to sign in via browser, click Continue With Browser

**Expected behavior:** Google chrome window to open with a login screen, or simply to confirm I am logged in 

**Actual behavior:** Empty chrome window launches

**Reproduces how often:** Constant

### Logs

2018-03-02T20:39:34.816Z - info: [ui] [SignInStore] initializing OAuth flow
2018-03-02T20:39:34.894Z - info: [main] opening in browser: https://git.soma.salesforce.com/login/oauth/authorize?client_id=XXX&scope=repo%20user&state=XXX

**Comment by shiftkey** [comment]
@brtrx thanks for the report. Do you know the version of GitHub Enterprise you are trying to connect to? I think we require 2.8 as a minimum.

**Comment by brtrx** [comment]
I'm afraid I don't, but I know it's a recent transition.
Also, I've just discovered that, even on my personal account, attempting to open a pull request from the Desktop app (which also should open in a new browser window) just opens an empty window.

**Comment by shiftkey** [comment]
@brtrx lots of the features of Desktop use the URL that you first enter when trying to "discover" your GitHub Enterprise instance, but it seems like that URL is being reported as valid (but requiring browser authentication).

Is there a different URL that you use to access the GitHub Enterprise instance through the browser?

**Comment by brtrx** [comment]
No, I use https://git.soma.salesforce.com/ to access through a browser
and it logs me in via SSO, no problem.

**Comment by brtrx** [comment]
But trying to start a pull request from my personal account should just be hitting https://github.com/ shouldn't it.
Seems like the problem is with Desktop passing the URL to chrome.
Any idea what could cause that?

**Comment by mwascak** [comment]
I am getting the same error. Running 2.13

**Comment by shiftkey** [comment]
@mwascak it's not clear to me what "2.13" relates to - that sounds like a Git version rather than Desktop. Also, it's not clear which OS you are running. Could you open a fresh bug report and fill out the template so we can troubleshoot better?

**Comment by tierninho** [comment]
@shiftkey I believe @mwascak was referring to Enterprise 2.13: https://blog.github.com/2018-03-27-github-enterprise-release-2-13/ if it matters.

@brtrx the version of Enterprise you are running can be found at the footer of the web interface. Are you still having this same issue? Have you tried a different browser? On a mac, it's under 🍎 > Sys Prefs > General

**Comment by billygriffin** [comment]
@desktop/support Any chance you'd mind following up on this one?

**Comment by steveward** [comment]
@brtrx and @mwascak -- are you still experiencing this issue when authenticating to your GitHub Enterprise instance? Have you tried using a different default browser to see if that makes a difference?

**Comment by FooFoundry** [comment]
I'm unable to sign into github with the desktop application. I'm on a mac. I'm able to log in via Chrome. I had to recently change my password which broke the desktop app authentication. How Do I fix?

**Comment by tierninho** [comment]
@FooFoundry Please fill out this issue template https://github.com/desktop/desktop/issues/new?template=bug_report.md so we have enough info to address your issue. Thank you!
