### ISSUE TITLE
webp image support

### ISSUE THREAD

**Issue by pforhan** [desktop/desktop#4160]
### Description

Support .webp files at the same level of .png

.png files are shown in the detail pane as images, and if they are changed you can see the old and new versions.  Support the same for .webp

For details on the webp format, see https://developers.google.com/speed/webp/

**Comment by shiftkey** [comment]
@pforhan if this is natively supported in Chromium, I can't see why this isn't possible.

I think there's three parts to testing this works:

 - a public repository containing webp files for testing
 - making a change here to look for the `.webp` extension

https://github.com/desktop/desktop/blob/6ff3112dc2acdf43ba6517ff40cd3411d9c3269f/app/src/lib/git/diff.ts#L78

 - update `getMediaType` to return whatever media type `.webp` files

https://github.com/desktop/desktop/blob/6ff3112dc2acdf43ba6517ff40cd3411d9c3269f/app/src/lib/git/diff.ts#L304-L320

I'll mark this as `help-wanted` and `good-first-issue` as I'm _pretty sure_ that's all the changes needed, and I'm happy to help review a contribution around this.

**Comment by pforhan** [comment]
Nice, thanks.
