### ISSUE TITLE
Github Desktop crashes on exit..

### ISSUE THREAD

**Issue by onwhim** [desktop/desktop#4163]
### Description

Open GD -> Exit GD -> Crash notification occurs

### Version

**GitHub Desktop version:** 1.1.0

**OS version:** Widows 7 Professional - Version 6.1 (Build 7601: Service Pack 1)

### Steps to Reproduce

1. Open GD
2. Exit GD
3. Crash Occurs

**Expected behavior:** App Closes without errors.

**Actual behavior:** App crashes on exit.

**Reproduces how often:** All the time.

### Logs
GD Log: https://drive.google.com/uc?authuser=0&id=1hXRq-RPDPqEG_FRl2UuHu54nPsaVYdmY&export=download

## Problem details from Windows: 
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	GitHubDesktop.exe
  Application Version:	1.1.0.0
  Application Timestamp:	5a665abd
  Fault Module Name:	GitHubDesktop.exe
  Fault Module Version:	1.1.0.0
  Fault Module Timestamp:	5a665abd
  Exception Code:	80000003
  Exception Offset:	0000000000412f99
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	c3c4
  Additional Information 2:	c3c49eaf39279c16e1ebd40aa0ab5cb0
  Additional Information 3:	1d71
  Additional Information 4:	1d710c6401b141fdce236c2b04604f52

**Relevant Files**
## Video of error: https://drive.google.com/uc?authuser=0&id=1B1di0TxsYextsbb8cgUeLgWPOQ99xdGJ&export=download

**Comment by onwhim** [comment]
I have not used GD regularly in a while so I can't verify the status enough. But I have checked today and can't reproduce the bug anymore.

**Comment by onwhim** [comment]
@billygriffin I have not used GD regularly in a while so I can't verify the status enough. But I have checked today on version 1.4 and can't reproduce the bug anymore.

**Comment by billygriffin** [comment]
Thanks @onwhim, we've had a few that have been cleared up in the past couple releases, so I'm going to close this out for now. Please feel free to open another issue if you're running into additional problems. And thanks again!
