### ISSUE TITLE
Update one file in all branches - is it possible?

### ISSUE THREAD

**Issue by Kubrix** [desktop/desktop#4166]
I have a file named SmartTextField.java in all my branches including [SmartTextField Branch](https://github.com/kalistrat/WebSolidSvn/tree/SmartTextFieldBranch) which was cloned from master branch for testing purpose. 

Now the file SmartTextField.java in SmartTextFieldBranch is ready and I need to update the file for all branches. Is there a way to update the file for a several branches at once? Or do I need to update each branch separately?

**Comment by shiftkey** [comment]
@Kubrix this is not possible in Desktop, but I'd have a look at [this StackOverflow](https://stackoverflow.com/questions/11940977/how-to-update-a-file-across-all-branches-in-a-git-repository) question which is relevant to what you're looking for.
