### ISSUE TITLE
cannot fetch existing repositories on github

### ISSUE THREAD

**Issue by Ankesh11** [desktop/desktop#4173]
### Description
Just installed github desktop but unable to fetch existing repositories from github.

### Version

**GitHub Desktop version:** [1.1.0]

**OS version:** [Windows 10 HOME]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [After login my repositories should be automatically fetched.]

**Actual behavior:** [Not expected]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by HeavenlyEntity** [comment]
I get the same thing. Can't seem to find a way to fix it. @Ankesh11 have you found a way.
![2018-12-15_17-29-48](https://user-images.githubusercontent.com/39228141/50048664-71bc4d00-008f-11e9-8676-5a0b5fb4ae34.gif)
