### ISSUE TITLE
Discard changes (for a single change) is very slow

### ISSUE THREAD

**Issue by kmscode** [desktop/desktop#4180]
## Version

* GitHub Desktop: 1.1.0

* Operating system: Windows 10 Pro 1709

### Expected Behavior
Change should be discarded without delay.

### Actual Behavior
Change is discarded, but it takes about 3 seconds for the popup to go away. This makes the UI feel very sluggish. 

## Additional Information

Not sure if this is just a UI issue where the popup needs to be destroyed, or if this is related to the backend / electron APIs for sending the file to the recycle bin as noted in #2629

Desktop Client system hardware specs:
Dell Precision 7510
[Core i7-6920HQ](https://ark.intel.com/products/88972/Intel-Core-i7-6920HQ-Processor-8M-Cache-up-to-3_80-GHz)
32 Gigs of RAM
512 Gig SSD

Repo in that I've been using most recently is GitHub Enterprise. Server has 2 ms ping times and is 4 hops away on a very fast wired/gigabit corporate network:
```
> ping [REPO HOSTNAME]

Pinging [REPO HOSTNAME] [[REPO IP]] with 32 bytes of data:
Reply from [REPO IP]: bytes=32 time=2ms TTL=61
Reply from [REPO IP]: bytes=32 time=2ms TTL=61
Reply from [REPO IP]: bytes=32 time=2ms TTL=61
Reply from [REPO IP]: bytes=32 time=2ms TTL=61

Ping statistics for [REPO IP]:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 2ms, Maximum = 2ms, Average = 2ms
> tracert [REPO HOSTNAME]

Tracing route to [REPO HOSTNAME] [REPO IP]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  [HOP1] [HOP1 IP]
  2     2 ms     3 ms     1 ms  [HOP2] [HOP2 IP]
  3    <1 ms    <1 ms    <1 ms  [HOP3] [HOP3 IP]
  4     2 ms     2 ms     2 ms  [REPO HOSTNAME] [REPO IP]
```

<sub><sup>Running some tests for some build scripts that will ultimately change some files and check them in. For now as I'm tweaking I need to discard the changed and it's super annoying how slow it is...</sup></sub>

### Logs

[2018-03-05.desktop.production.log](https://github.com/desktop/desktop/files/1782229/2018-03-05.desktop.production.log)

**Comment by shiftkey** [comment]
@kmscode I think this is related to a change to discard changes when a repository has submodules: #3728

We need to check if any submodules have changed, to ensure that we don't move the submodule to the trash, and we do this by invoking `git submodule status`.

On your machine and this repository this seems to take ~2sec:

```
2018-03-05T18:47:53.959Z - info: [ui] Executing listSubmodules: git submodule status -- (took 2.381s)
2018-03-05T18:48:08.740Z - info: [ui] Executing listSubmodules: git submodule status -- (took 1.946s)
2018-03-05T18:50:46.122Z - info: [ui] Executing listSubmodules: git submodule status -- (took 1.634s)
...
2018-03-05T18:53:46.166Z - info: [ui] Executing listSubmodules: git submodule status -- (took 1.627s)
2018-03-05T18:54:54.194Z - info: [ui] Executing listSubmodules: git submodule status -- (took 2.076s)
2018-03-05T18:55:11.270Z - info: [ui] Executing listSubmodules: git submodule status -- (took 2.165s)
```

How many submodules do you have in this repository?

**Comment by kmscode** [comment]
@shiftkey 

There are no submodules. 

.gitmodules doesn't even exist in this repo.

**Comment by shiftkey** [comment]
@kmscode that's interesting. Are you able to run these two commands in a shell and attach the output?

```
$ git submodule status
$ ls .git/modules/
```

**Comment by kmscode** [comment]
@shiftkey 

```
$ time git submodule status

real    0m1.907s
user    0m0.000s
sys     0m0.015s

$ ls .git/modules/
ls: cannot access '.git/modules/': No such file or directory

$ ls .git
COMMIT_EDITMSG  description  HEAD    index  lfs/   objects/   packed-refs
config          FETCH_HEAD   hooks/  info/  logs/  ORIG_HEAD  refs/
```
~2 seconds seems to be the average for the `git submodule status` command. I've seen it go as high as ~2.5 seconds though.


Just a thought...

In [submodule.ts](https://github.com/desktop/desktop/blob/16e2e6b06d3013578b75bd787590b0dc458c75c6/app/src/lib/git/submodule.ts#L8). Why not check for the existance of the file and/or dir before attempting to get submodule status?

I wasn't able to quickly find enough build info on this project to test and/or submit a PR - but if you could point me in the right dir, I most certainly will... This is assuming my thought and code aren't utter garbage.

```
const modFile = Path.join(repository.path, '.gitmodules');
fs.stat(modFile, (e) => {
  if(e == null) {
    // file exists	
  } else if(e.err == 'ENOENT') {
    return [];
  }
}

const modDir = Path.join(repository.path, '.git', 'modules');
fs.stat(modDir, (e) => {
  if(e == null) {
    // dir exists
  } else if(e.err == 'ENOENT') {
    return [];
  }
}

// continue to git submodule status
```

**Comment by shiftkey** [comment]
> Why not check for the existance of the file and/or dir before attempting to get submodule status?

It looks like on Windows the git command has significant overhead. On a blank repository it takes ~1s, so I think an escape hatch is a good idea if we **know** there are no submodules:

```
$ git init hello-world && cd hello-world

$ time git submodule status

real    0m1.087s
user    0m0.000s
sys     0m0.000s
```

> I wasn't able to quickly find enough build info on this project to test and/or submit a PR - but if you could point me in the right dir, I most certainly will..

Have a look at [`Building Desktop`](https://github.com/desktop/desktop/blob/master/docs/contributing/setup.md#building-desktop) in the Setup Guide

**Comment by kmscode** [comment]
@shiftkey Thanks for the link to the setup guide. Not sure why I couldn't locate this. But there was the documentation link, right next to the CONTRIBUTING.md link within the readme... Maybe I jumped straight to CONTRIBUTING.md?

Anyways, as you saw already, PR has been submitted and all checks are currently passing. This does make the discard changes (for single changes at least) feel a lot smoother.

Sample log messages during some various tests:
```
2018-03-06T19:00:10.493Z - info: [ui] No submodules found. Skipping "git submodule status"
2018-03-06T19:08:06.963Z - info: [ui] Executing listSubmodules: git submodule status -- (took 1.476s)
2018-03-06T19:10:56.710Z - info: [ui] Executing listSubmodules: git submodule status -- (took 1.338s)
2018-03-06T19:11:43.836Z - info: [ui] Executing listSubmodules: git submodule status -- (took 1.374s)
2018-03-06T19:12:28.128Z - info: [ui] No submodules found. Skipping "git submodule status"
...
...
2018-03-06T20:28:08.947Z - info: [ui] Executing listSubmodules: git submodule status -- (took 1.770s)
```

These first few messages were "artificial" submodules as I didn't have any repos with submodules available that I was comfortable testing with initially. The last message is on the GH desktop repo which does have some submodules. In this scenario the discard will still delay by ~1-2 seconds. Also as you can see there are some differences between a repo with no submodules (1.3-1.4 seconds) to a repo with a few submodules (pretty consistent at about 1.7-1.8 seconds).

Hope this helps!

**Comment by BasmanovDaniil** [comment]
Same issue on my machine in all repos, even the simplest ones. The old GitHub for Windows does not have this problem and discards changes instantly.

**Comment by shiftkey** [comment]
This was fixed in #4186 which will go out in 1.1.1

**Comment by anaibol** [comment]
It's still very slow on Linux at least, using v `2.1.0-linux1`.

**Comment by outofambit** [comment]
hey @anaibol please file linux issues over in https://github.com/shiftkey/desktop. thank you!
