### ISSUE TITLE
Repositories sorted incorrectly when filtering

### ISSUE THREAD

**Issue by adamreisnz** [desktop/desktop#4184]
## Description
The order in which repositories are sorted is incorrect when filtering:

![image](https://user-images.githubusercontent.com/490562/37018386-09437118-2179-11e8-80b7-8f23b7213c4e.png)

vs.

![image](https://user-images.githubusercontent.com/490562/37018346-eb3eebf2-2178-11e8-91b7-b5242a667bf9.png)

## Version
* GitHub Desktop: 1.1.0
* Operating system: OS X 10.11.6

## Steps to Reproduce
See screenshot

### Expected Behavior
For the sort order to be the same as when not filtering (e.g. alphabetically)

### Actual Behavior
Repositories sort order out of whack.

## Additional Information
This seems to be a regression that happened in the latest version, I did not observe this in previous versions.

**Comment by niik** [comment]
This seems to be a side-effect of the work done in #3873 to add fuzzy filtering. The filtering is no longer a simple substring match and the scoring algorithm within fuzzaldrin now determines the sorting order.

I'd be happy to consider alternative (fuzzy) scoring algorithms that attempt to preserve the original order but the overall behavior is what we want. Fuzzy search allows for quick filtering where you can use muscle-memory shortcuts to get to the repository you want quickly with less typing.

<img width="251" alt="screen shot 2018-03-06 at 15 18 45" src="https://user-images.githubusercontent.com/634063/37037165-ff1d2084-2151-11e8-9f21-384a0adcd242.png">

If you have a suggestion for an alternative algorithm we'd love to hear about it!

**Comment by j-f1** [comment]
I think this happened because we now use a fuzzy-searching algorithm, and it ranks better matches first.

**Comment by adamreisnz** [comment]
I personally don't think this is very beneficial to something which generally doesn't have that many items in the list. Even if you have 100+ repo's, you tend to know how they are called and which one you're after, so you'll know what to type in the filter.

So I'm not too sure what problem this change was trying to solve.

For me, this new search mechanism really works counter productive, because I use it primarily to filter out grouped repositories (as in my example) so that I can keep them visible throughout the day if I'm working on a particular project. This was the whole [reason I asked for the filter to be preserved](https://github.com/desktop/desktop/issues/2451).

Not having these results sorted alphabetically makes it once again harder for me to find the one I want because they appear scattered in a completely random order.

Any chance of turning this into a setting so that we can choose which filtering algorithm we want to use? 

Or at least improving the fuzzy search so it sorts a bit better when there are multiple results? From my example above I really can't tell why it would sort in the way it does, as there are no character matches beyond the first "hello", so it should score all the results equally and show them in alphabetical order when that's the case.

**Comment by billygriffin** [comment]
Hi @adamreisnz, just stumbled upon this issue (wow, there are so many in the realm of the repo list! 😄). This isn't something I've heard from others and generally the feedback has been really positive about the fuzzy filter, and based largely on your feedback it will now filter on the org as well. I'm going to close this so we're looking at all of these problems holistically. I'm honestly not sure this one will rise to the threshold of changing our fuzzy filter methodology to accommodate it to be honest unless we see it from others as a pain point, but @outofambit and I will discuss in our next meeting about the repo organization work overall. Thanks again for all your feedback, it's been really useful!

**Comment by adamreisnz** [comment]
@billygriffin yeah tell me about it haha :)

Well, I'd just like to suggest that the search filter is used in two ways (which you have been helpful to accommodate).

1) To find a random repo you're looking for. In this case, having prioritised matches in the fuzzy results is a great thing to have.

2) To limit the number of repo's in the list (for example search by project name/org name), and then select repo's from the list.

In the case of 2, which is what we mostly use it for, it would be great if the repo's were sorted alphabetically instead of fuzzy (e.g. randomly). This will just make it much easier to find them:

![image](https://user-images.githubusercontent.com/490562/54471200-1fb7ce80-481a-11e9-8ae9-1d595eb541b6.png)

Furthermore, I don't really see the logic in this order. For example, why does "site" score higher than "client"? And higher than "he900-test" even?
