### ISSUE TITLE
Authentication Failed Error - Repos still downloads - Can open but not push or commit

### ISSUE THREAD

**Issue by sethmccombs** [desktop/desktop#4191]
## Description

I have a GHE server in use, I am able to clone and commit/push to repos but not an org repo. When I clone the repository from the web page, the progress bar gets to 100% then I receive a "Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open preferences and verify that you're signed in with an account that has permission to access this repository." error message. The repository still clones locally and I can open it in the app, but cannot push to it 

## Version

* GitHub Desktop: 1.1.0

* Operating system: MacOS High Sierra 10.13.3 (17D102)

## Steps to Reproduce

1. Open repo page in Google Chrome
2. Click "Clone or Download" then "Open in Desktop" 
3. GitHub app opens and progress bar starts moving, at ~100% - the error  appears. 
4. Open repo from within github by pointing to directory, when trying to commit code - "Commit failed - exit code 1 received"

### Expected Behavior

Repo clones successfully, code can be commited

### Actual Behavior

"Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open preferences and verify that you're signed in with an account that has permission to access this repository."
"Commit failed - exit code 1 received"

### Logs

Cleared logs when reinstalling, no logs yet

**Comment by shiftkey** [comment]
@sethmccombs thanks for the report!

A log file with the underlying errors would be fantastic to help understand the underlying issue you're seeing. Can you also confirm you're signed into GitHub Enterprise under the **Preferences** menu?

**Comment by sethmccombs** [comment]
@shiftkey I have one, trying to pull out any private information that I can't publish. 

The error is 

`2018-03-06T22:42:53.224Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://<repo-name>.git /Users/<local-path>` exited with an unexpected code: 1.`

**Comment by shiftkey** [comment]
> It has something to do with a Submodule, trying to look into my repo a bit more

Have a read of #3242 - this might be related

**Comment by sethmccombs** [comment]
That was the issue! Thanks @shiftkey - I have to switch away from Desktop because I can't gpg sign, :( back to CLI for me.

**Comment by shiftkey** [comment]
> I have to switch away from Desktop because I can't gpg sign,

That's #78
