### ISSUE TITLE
Discard All Changes isn't discoverable

### ISSUE THREAD

**Issue by mdiep** [desktop/desktop#4197]
## Description
One of the things I miss most from Classic Desktop (apart from my beloved comparison graph) is the ability to discard all changes. I've used this pretty frequently after commiting the subset of the changes that I care about. I'd love to have this option back.

The alternatives, discarding the files one-by-one or resorting to the terminal (🙀), take quite a bit more time.

❤️

**Comment by donokuda** [comment]
Hi @mdiep!

If I understand correctly, you can discard all changes by right clicking in the `X Changed Files` header:

<img src="https://user-images.githubusercontent.com/1174461/37114275-b4968720-21fc-11e8-911f-e5e09927a448.png" width="400" />

**Comment by mdiep** [comment]
Wow. That is… not discoverable.

In that case, I'd like to see a menu item for this. ☺️

**Comment by mdiep** [comment]
Classic Desktop also had this as an option in the context menu on the individual files. It might not be a bad idea to add it back there too.

Also, discarding an individual file isn't in the main menu either.

**Comment by donokuda** [comment]
> Wow. That is… not discoverable.

I totally agree 😄 

> Classic Desktop also had this as an option in the context menu on the individual files. It might not be a bad idea to add it back there too.

👍I'm for this since it's more discoverable than the header.

**Comment by donokuda** [comment]
If anyone wanted to tackle this, I think this will make a good first issue for someone to pick up! 😄 

For the UI, we'll want to implement the right click menu item:

<img src="https://user-images.githubusercontent.com/1174461/37236597-2900b26c-23be-11e8-920a-e13be5457603.png" width="450" />

The relevant lines of code to add the menu item can be found here:

https://github.com/desktop/desktop/blob/d328cf729a9540b7db84632f00e77e2c12923037/app/src/ui/changes/changed-file.tsx#L103-L114

You'll want to add similar to how the "Discard All Changes" item is implemented in the changes list:

https://github.com/desktop/desktop/blob/d328cf729a9540b7db84632f00e77e2c12923037/app/src/ui/changes/changes-list.tsx#L152-L156

@desktop/core + @desktop/comrades Am I missing anything for this one?

**Comment by xamm** [comment]
Hi,
I would really like to take on this issue.

**Comment by nerdneha** [comment]
@xamm go for it!

Some helpful tips for completing a PR:
* Open up a PR when you have your first commit
* Include `Fixes #4197` at the top of the description for your PR and a checklist as you progress through (helpful for you and us!)
* Read our [PR process doc](https://github.com/desktop/desktop/blob/master/docs/process/reviews.md) to understand how we do PRs in this repo and what code review looks like
* When you finish the PR, add a comment saying it's ready for review, include before/after screenshots in the description, and describe any major changes
* Make sure to test on both Windows and MacOS
* cc @desktop/design in your PR

**Comment by xamm** [comment]
I created the first pull request (hoping I did it right).
But i have a question regarding automated tests. Are there any unit or integration tests for this component?

**Comment by tierninho** [comment]
@xamm That's a great question! We plan to add automated end-to-end coverage in the future for some general use cases, in fact this is something we're actively working on. We have a few unit test files in `app/test/unit` but I don't think we have coverage for this file right now. Thanks for asking!

PS. No need to add test coverage with your pull request.
