### ISSUE TITLE
Please add the function of setting the comment name

### ISSUE THREAD

**Issue by shankesgk2** [desktop/desktop#4199]
Please🙏
![wx20180308-110518](https://user-images.githubusercontent.com/8123290/37130947-e9ffbf2a-22c0-11e8-8515-68ac619d87ef.png)

**Comment by shiftkey** [comment]
@shankesgk2 

> Please add the function of setting the comment name

Could you elaborate on what you would like to happen here?

Currently we differentiate when repositories in the same grouping have a matching name:

<img width="362" src="https://user-images.githubusercontent.com/359239/37259858-287ab310-2549-11e8-89fa-122dab3882df.png">

Repositories **across** groups do not differentiate in the same way.

**Comment by niik** [comment]
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.
