### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by lgqfhwy** [desktop/desktop#4200]
<img width="964" alt="screen shot 2018-03-08 at 16 59 34" src="https://user-images.githubusercontent.com/16728136/37142159-3afa65a2-22f2-11e8-8ec4-a7aa3d9bbb59.png">
I am using Mac, Sierra 10.12.6, I don't know how to fix it, please help me

**Comment by shiftkey** [comment]
@lgqfhwy are you working behind a proxy server? That IP address and port seem to suggest that some sort of setup needs to occur to be able to reach GitHub.

**Comment by niik** [comment]
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.
