### ISSUE TITLE
Lua files not displaying as plain text

### ISSUE THREAD

**Issue by Krelsis** [desktop/desktop#4205]
## Description
Not entirely sure if this is an issue, but it is something I've searched around looking for a solution and came up empty, on a previous version of github desktop, when it used to be called GitHub For Windows, Lua files were working perfectly for me, and I could see the text within, now however, even though *.lua       diff=astextplain          is set in the gitattributes, it states that no file has been selected.

## Version

* GitHub Desktop:
1.1.0
* Operating system:
Windows 7 64bit ( Microsoft Windows [Version 6.1.7601])

## Steps to Reproduce
1. Ensure *.lua         diff=astextplain        is included in .gitattributes
2. Create a new lua file with something inside print("Hello")
3. Commit the new file.
4. Change the file, add new line print("Bye")

### Expected Behavior
The git browser should now let me select the file and see whats changed, in this case, it should highlight the second line which is print("Bye")

### Actual Behavior
For me, It says no file has been selected, even If I have multiple files with different changes.

## Additional Information
My specific issue is occuring on a repository I cloned.

**Comment by shiftkey** [comment]
@Krelsis thanks for the report.

I haven't had a chance to walk through the steps but I'm 99% sure it's down to the `asplaintext` script not part of Git core, or the embedded Git we use in Desktop.

It's an extra package in [Git for Windows](https://github.com/git-for-windows/build-extra/blob/master/git-extra/astextplain) and if it's missing that would explain the strange behaviour.

Is there a reason why you are enabling this in `.gitattributes`? I had a quick look at some of the notable Lua projects like [Neovim](https://github.com/neovim/neovim) and it doesn't seem to create a `.gitattributes` file.

**Comment by Krelsis** [comment]
I was adding it so that it would show the changes as in the old version I do not believe that the app showed any text without it. As being able to see exactly which line I changed in previous change is a must have. In the previous version text did not show, a friend suggested to so this and the text started to show.

**Comment by shiftkey** [comment]
@Krelsis you might be encountering Git's binary detection, which [scans the blob content](https://github.com/git/git/blob/c2ece9dc4de60ead431f7902c273be32c880eede/xdiff-interface.c#L201-L206) for a `\0` in the first 8000 characters - so some files may be fine despite having a `.lua` extension. This can often occur when using Unicode or other 16-bit characters in a file.

You're on the right track with using `.gitattributes` to provide hints to Git: would doing `*.lua diff` in the `.gitattributes` (which is supported in Git core) address the issue, or does it too show the same problem as not having the rule defined?

**Comment by Krelsis** [comment]
Removing `*.lua	 diff=astextplain`      and inserting `*.lua		diff` actually solved the issue and now text is appearing correctly on the right side of the app, thank you for your assistance.
