### ISSUE TITLE
Need to use MacOS system proxy configuration

### ISSUE THREAD

**Issue by cjnewman** [desktop/desktop#4206]
When I try to clone a repository on my corporate network, I get the following error:

Cloning into '/Users/cjnewman/Documents/GitHub/robotframework-cassandracqllibrary'...
fatal: unable to access 'https://github.com/peterservice-rnd/robotframework-cassandracqllibrary.git/': Failed to connect to github.com port 443: Network is unreachable

Mac GUI software should use the OS proxy settings and connect via the properly configured proxy (this works on all mature MacOS applications). A poor-man's alternative would be to provide a way to manually set the proxy in the preferences.

Simply failing makes the application look primitive and incomplete.

**Comment by shiftkey** [comment]
@cjnewman thanks for the feedback. Git itself doesn't automagically probe for proxy settings, and these need to be provided via config:

```
git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080
```

We're tracking making this experience better in the app over in #3294, if you want to follow along with that.

**Comment by cjnewman** [comment]
Since I use my laptop both on and off the corporate network (and switch OS Network locations), a global setting doesn't work. I'll just avoid using github desktop until it works like a real application.
