### ISSUE TITLE
Request feature : being able to select severall files and discard all of them

### ISSUE THREAD

**Issue by cavo789** [desktop/desktop#4209]
Hello

A small request if possible : would be usefull to be able to select several files (under Windows Clic-select-Shift-Clic) then discard them or ignore or ...

![2018-03-09_15h21_28](https://user-images.githubusercontent.com/355999/37211830-8b0fcefe-23ad-11e8-83e8-d39cfb45035b.png)

Thanks a lot !

**Comment by niik** [comment]
Hi @cavo789, this is currently being worked on in #4188, so please subscribe to that pull request to follow along.
