### ISSUE TITLE
Unable to build master since d328cf7

### ISSUE THREAD

**Issue by icosamuel** [desktop/desktop#4210]
## Description

I am unable to build master since commit [d328cf7](https://github.com/desktop/desktop/commit/d328cf729a9540b7db84632f00e77e2c12923037)

```[at-loader] Checking finished with 1 errors
(node:21860) Warning: a promise was rejected with a non-error: [object Object]
[WEBPACK] Build failed after 26.254 seconds
(node:21860) Warning: a promise was rejected with a non-error: [object Object]
(node:21860) Warning: a promise was rejected with a non-error: [object Object]
[WEBPACK] Errors building ask-pass.js
[at-loader] ./app/src/ui/lib/author-input.tsx:799:12 
    TS2339: Property 'execCommand' does not exist on type 'Editor'.
```

## Version
master/d328cf729a9540b7db84632f00e77e2c12923037
* Operating system:
arch-linux

## Steps to Reproduce
1 - `git clone git@github.com:desktop/desktop.git`
2 - `git checkout d328cf729a9540b7db84632f00e77e2c12923037`
3 - `yarn build:dev`

**Comment by shiftkey** [comment]
@icosamuel that line suggests the `@types/codemirror` package is out of date on your local machine. Can you do a `yarn` before doing `yarn build:dev` to ensure your `node_modules` are up to date?

**Comment by icosamuel** [comment]
That was it. I'm still unfamiliar with yarn. 
Thanks!
