### ISSUE TITLE
Trim whitespace from start and end of URLs pasted into "Clone repository"

### ISSUE THREAD

**Issue by rock-hopper** [desktop/desktop#4213]
## Description

Please trim whitespace from start and end of URLs pasted into "Clone repository" under the "URL" tab. When copying and pasting a URL it is easy to copy extra whitespace by mistake and GitHub desktop gives the following error:

fatal: I don't handle protocol ' http'

## Version

* GitHub Desktop: 1.1.0

* Operating system: Windows 10 / Windows 7

## Steps to Reproduce

1. Copy URL for a git repository with some whitespace before the "http"
2. Paste URL into "Clone repository" / "URL"
3. Click "Clone" button

### Expected Behavior

GitHub desktop should trim whitespace from start and end of URL before attempting to clone repo
### Actual Behavior

Error message is displayed:

fatal: I don't handle protocol ' http'

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇
