### ISSUE TITLE
Add me to desktop GitHub Org

### ISSUE THREAD

**Issue by YoginthS** [desktop/desktop#4218]
Hey,

I am really excited about the active development and wanted to be a part of the **desktop** organization on GitHub. In this regard, how can I become a member and would love if somebody would add me to it?

My GitHub username is YoginthS

Thanks, Yoginth

**Comment by Kubrix** [comment]
@YoginthS 
This is an issue-tracker and not the GitHub HR department blog. Please try contacting via 
https://github.com/contact

**Comment by j-f1** [comment]
@YoginthS The best way to become a member of an organization — any organization — is to contribute actively, [i](https://github.com/ansible/community/issues/299)[n](https://github.com/Shopify/bootsnap/issues/140)[s](https://github.com/guardian/frontend/issues/19311)[t](https://github.com/laravel/framework/issues/23491)[e](https://github.com/bitcoin/bitcoin/issues/12667)[a](https://github.com/nuxt/docs/issues/522)[d](https://github.com/gitlabhq/gitlabhq/issues/10481)[ ](https://github.com/octokit/discussions/issues/20)[o](https://github.com/nuxt-community/nuxt7/issues/31)[f](https://github.com/probot/probot.github.io/issues/140)[ ](https://github.com/atom/atom/issues/16929)[o](https://github.com/kubernetes/community/issues/1918)[p](https://github.com/Microsoft/vscode/issues/45498)[e](https://github.com/bower/bower/issues/2503)[n](https://github.com/babel/babel/issues/7546)[i](https://github.com/tastejs/todomvc/issues/1859)[n](https://github.com/yeoman/yeoman.github.io/issues/758)[g](https://github.com/gruntjs/grunt/issues/1630)[ ](https://github.com/h5bp/html5boilerplate.com/issues/174)[s](https://github.com/git/git-scm.com/issues/1180)[e](https://github.com/flutter/flutter/issues/15395)[v](https://github.com/gogits/gogs/issues/5091)[e](https://github.com/GoogleCloudPlatform/community/issues/383)[r](https://github.com/Azure/azure.github.io/issues/56)[a](https://github.com/coala/community/issues/88)[l](https://github.com/fossasia/fossasia-communities/issues/108) issues asking for membership in organizations you haven’t contributed to.
