### ISSUE TITLE
Ability to confirm the discard for several files at once

### ISSUE THREAD

**Issue by Kubrix** [desktop/desktop#4221]
GitHub 1.1.0

I made changes to the project and closed IDEA. Github showed that some files are changes. I tried to change the branch without making the commit and got the Error "Please commit your changes or stash them before you switch branches.".

I don`t want to make a commit or stash and I want to discard changes. I have 10 changed files and need to confirm 10 discards one-by-one. 

It is possible to make GitHub desktop able to select all changed files and confirm one discard for all changes?

**Comment by j-f1** [comment]
You can right-click the “x files changed” header to get an option to discard all of the changes.

**Comment by Kubrix** [comment]
Thanks, @j-f1.
