### ISSUE TITLE
ELIAS

### ISSUE THREAD

**Issue by 15158659** [desktop/desktop#4223]
## Version

* GitHub Desktop:

* Operating system:

**Comment by Kubrix** [comment]
What is your problem? Do you want to be banned for spamming?

**Comment by lee-dohm** [comment]
@Kubrix your comment was deleted as a violation of the [Desktop Code of Conduct](https://github.com/desktop/desktop/blob/master/CODE_OF_CONDUCT.md) as it was insulting or derogatory.

**Comment by ja1977ja** [comment]
please tell me what i did wrong and what is it to help me fixed thank you

**Comment by lee-dohm** [comment]
@ja1977ja If you are really @Kubrix in disguise and you're sincere in wanting to discuss what you did wrong, you can reach me at opensource@github.com.

**Comment by ja1977ja** [comment]
not i not  @Kubrix 
i new one and lots thinks do not understand
