### ISSUE TITLE
When I try to publish, I get the comment that it required authentication. But I am unable to get a location to authenticate.

### ISSUE THREAD

**Issue by githubdarvin** [desktop/desktop#4224]
## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@githubdarvin thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by githubdarvin** [comment]
Which template? I did not get any template link or file. I just don't understand how to authenticate on github desktop. Is it an issue if I used a different folder

**Comment by shiftkey** [comment]
@githubdarvin if you edit the issue body, you'll see a number of HTML comment tags in the text:

<img width="781" src="https://user-images.githubusercontent.com/359239/37259000-8b50e466-253d-11e8-8f9f-2164e5e04be4.png">

Please fill out those details to help us understand things like:

 - whether you are using GitHub Desktop on macOS or Windows (and the versions)
 - whether you've signed into a GitHub account
 - how you added the repository into GitHub Desktop
 - what you were doing to trigger the issue

There are also log files that can be found in the **Help** | **Show Logs in Explorer** menu, which will help with troubleshooting

**Comment by niik** [comment]
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.

**Comment by satvikkaul** [comment]
I have the same issue (Windows 10, using GitHub desktop) when I am trying to publish my repository locally from GitHub desktop it says requires authentication but I don't understand where to authenticate from.

**Comment by steveward** [comment]
@satvikkaul you can log in to your GitHub account by going to the menu in GitHub Desktop and selecting `File` > `Options` > `Accounts`. Let us know if you have any issues.

**Comment by satvikkaul** [comment]
@steveward thank you, I was able to fix it myself, just had log out and back in.

**Comment by kamil-tekiela** [comment]
It happened to me, because I have changed my username in the meantime and I was still logged in with my old one. Once I logged out and logged in with the new username it worked.

**Comment by haywhyze** [comment]
Signing out and signing in works for me too.

**Comment by spockoyno** [comment]
On Mac it's currently  GitHub Desktop -> Preferences -> Accounts. You may need to sign out and sign in again.

**Comment by Generalisk** [comment]
Go To `File` > `Options` > `Accounts` And Sign Out & Sign In Should Do The Trick!
