### ISSUE TITLE
Unable to display desktop applications.

### ISSUE THREAD

**Issue by mozziechu** [desktop/desktop#4225]
Yesterday, when I was doing screen expansion on my Windows computer, I copied GitHub Desktop to another screen, and after the screen expanded, I could only see the GitHub Desktop icon in the taskbar.

When I expanded the screen again, I found it on the replicated screen.
At first I thought I was bad for GitHub desktop.

**Comment by nerdneha** [comment]
@mozziechu thanks for filing this issue! This sounds pretty similar to an open issue we have in #2107. Please follow along there as it contains the latest progress which is that we are hoping to address it
