### ISSUE TITLE
Add filtering of Pull Requests by pull request number and author

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#4229]
Currently, the Pull Request tab (Current Branch > Pull Requests) has fuzzy search functionality that allows you to search a string and filters the results by finding matches to the PR titles. This is great if you know the title you are searching for or approximate keywords but does not allow you to search by pull request number or by author handle.
For example, if you wanted to find PR #4227, `Bump toolbar contrast`, you could find it by searching "contrast" or "btcrst", etc. but you can't find it by searching "4227" or "niik"....yet 👇 

✏️ 🗒 **Task**: **Index the pull request numbers and authors and allow filtering of results by the PR number and author.**

Suggested Functionality (let's pretend the user is Paula) :
- **match all number occurrences**: if Paula types `2` in the filter (without `#` sign), they will see all the issues with a `2` in it, like: `#21`, `#2`, `#294`, `#321`, `#52`,  and a PR with the title `when 2 becomes 1` (new)
- **filter by `#` sign**: if Paula types `#23` (with `#` sign), they will see all issues *beginning* with `23`, like `#23` and `#232` but not `#123` (new)
- **match all author occurrences**: if Paula types `n` in the filter, they will see all issues with an `n` in it like a PR with the title `Add context menu to...` and all authors with an `n` in it like `nerdneha` and `niik` (new)
- **highlight matching characters**: while Paula types, text matching the filter will continue to be highlighted (existing functionality)
-  **preserve existing fuzzy searching**: when Paula types a string with mixed characters, they will see results that match existing fuzzy search results, like `3I` will show `Drop back to v3 API to retrieve...` Not sure of the expectation when we type "32" though... (existing functionality)

![screen shot 2018-03-12 at 11 20 23 am](https://user-images.githubusercontent.com/14828183/37302081-c07145aa-25e7-11e8-8e1c-9b1682a37099.png)

**Comment by tierninho** [comment]
cc @desktop/design ⬆️

**Comment by donokuda** [comment]
I'm 👍for this. I ran into a situation today where I wanted to search by the pull request number.

> Current fuzzy searching will search for characters separately, ex: "3I" will show `Drop back to v3 API to retrieve...` Not sure of the expectation when we type "32" though...

I'm fine with punting a decision on consecutive numbers until after a first pass at this and getting a feel of it using real information. Basically, let's see what we get by default and go from there.

**Comment by nerdneha** [comment]
note: updated description to include context, explicit task, use cases with persona `Paula`, and added author filtering as part of desired functionality.

**Comment by mats23177** [comment]
merge with webhook https://github.com/mats23177/desktop/settings/hooks/24563236

**Comment by say25** [comment]
I believe this can be closed.

**Comment by shiftkey** [comment]
Thanks for the reminder @say25!
