### ISSUE TITLE
Github Desktop not asking for self-signed certificate password

### ISSUE THREAD

**Issue by asegursa** [desktop/desktop#4233]
## Description
I have a git server with existing repositories on it and SSL verification with self-signed certificates. I can clone those repositories through git command line, but I'm unable to do the same from Github Desktop, as it gets stuck on an infinite loop cloning whatever repository I specify. I've been through all the issues related to this problem which I've been able to find searching, but none of them has helped me so far. Maybe there's an issue saying password protected self-signed certificates are not yet supported, but I haven't found anything related to it. If it is currently supported, it's something strange that I can clone from cmd git but not from Github Desktop, isn't it?

## Version
* GitHub Desktop: 1.1.0
* Operating system: Windows 10

## Steps to Reproduce
I don't have steps to reproduce it. From cmd git I can use my server but not from Github Desktop.

### Expected Behavior
From cmd git I can clone and manage all repositories without any kind of problem. I expected to do the same with Github Desktop.

### Actual Behavior
Github Desktop gets stuck in an infinite loop saying it is cloning the desired repository, but nothing happens. It just creats the root folder for the git repository but does not download any repository files. It also does not prompt asking for user and password credentials as cmd git does.

## Additional Information
This is my .gitconfig file (I've edited my personal information to publish this lines):
```
[credential]
	helper = manager
[user]
	name = My Name
	email = my.name@mycompany.com
[filter "lfs"]
	required = true
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
[http]
	sslVerify = true
	sslBackend = openssl
	sslCAInfo = C:\\Certificates\\ca_chain.pem
	sslPath = C:\\Certificates\\
	sslCert = C:\\Certificates\\my.name.pem
```

### Logs
```
2018-03-13T15:21:37.421Z - info: [ui] [AppStore] loading 0 repositories from store
2018-03-13T15:21:37.646Z - info: [ui] launching: 1.1.0 (Windows 10.0.16299)
2018-03-13T15:21:37.647Z - info: [ui] execPath: 'C:\Users\User\AppData\Local\GitHubDesktop\app-1.1.0\GitHubDesktop.exe'
2018-03-13T15:22:06.378Z - warn: [ui] fetchRepository: 'my.name/OpenLDAP' returned a 404
2018-03-13T15:22:06.380Z - info: [ui] [AppStore.getAccountForRemoteURL] found generic credentials for 'git' and 'my.name'
```

**Comment by shiftkey** [comment]
> Maybe there's an issue saying password protected self-signed certificates are not yet supported, but I haven't found anything related to it.

Can you share the output of when you're cloning from the command line? If it's asking you to prompt for a password during the clone, that's a scenario that Desktop's clone experience doesn't currently support (we set `GIT_TERMINAL_PROMPT=0` so that prompts for username and password don't block the operation).

**Comment by asegursa** [comment]
This is the output when cloning from the command line:
```
C:\Users\User\Documents\GitHub>git clone https://git/my.name/OpenLDAP.git
Cloning into 'OpenLDAP'...
```
**HERE IT ASKS FOR MY PRIVATE CERTIFICATE PASSWORD**
```
Enter PEM pass phrase:
remote: Counting objects: 28, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 28 (delta 7), reused 0 (delta 0)
Unpacking objects: 100% (28/28), done.
```
Sorry to hear that prompts for username and password are not yet supported.

**Comment by shiftkey** [comment]
> Sorry to hear that prompts for username and password are not yet supported.

We do this because Desktop acts as the credential provider, and if that fails we don't want the clone to block on prompting for basic authentication. Prompting for the passphrase to unlock a custom certificate file isn't a scenario we considered at the time.

**Comment by shiftkey** [comment]
This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by billygriffin** [comment]
@asegursa Thanks so much for the issue and explaining your setup. We haven't heard from very many others that supporting something like this would be useful and your configuration seems to be relatively rare. I'm going to remove the `future-proposal` label to indicate that we don't intend to support this, but we're always open to revisiting if we hear from others that support for custom certificates with passphrases would be more broadly beneficial. Thanks again!

**Comment by kelirkenan** [comment]
### Updating information on this issue as now I can use Github Desktop with a slight change in .gitconfig:

I have changed these lines in .gitconfig:
```
[http]
	sslVerify = true
	sslBackend = openssl
	sslCAInfo = C:\\Certificates\\ca_chain.pem
	sslPath = C:\\Certificates\\
	sslCert = C:\\Certificates\\my.name.pem
```

to these lines:

```
[http]
	sslVerify = true
	sslBackend = schannel
```

This just tells Git to use the Windows Certificate Store. After this change I've been able to clone, pull, push without any issues. Hope this helps anyone with the same or similar setup 😄
