### ISSUE TITLE
Cut A New Beta?

### ISSUE THREAD

**Issue by say25** [desktop/desktop#4235]
There have been a lot of improvements both small and large since 1.1.1-beta1. Time to make a new beta? ✂️

**Comment by shiftkey** [comment]
Once I get a :thumbsup: on some release notes in https://github.com/desktop/desktop/pull/4234 and do some more QA on `master` I think I'll be happy to cut a release, but I'll let the other @desktop/core and @desktop/comrades chime in on this.

**Comment by shiftkey** [comment]
`1.1.1-beta3` has just been published to beta, which contains all the latest work merged to `master`. 

We're aiming to ship this to the production channel next week, so any additional testing and reports is greatly appreciated. Installer links are [here](https://github.com/desktop/desktop#beta-channel), if you want to switch and assist.
