### ISSUE TITLE
adb over wifi connection problem

### ISSUE THREAD

**Issue by mohamedkhairy** [desktop/desktop#4237]
I'm using wifi adb app on my mobile which is galaxy s3 mini 
when I type this command

    adb connect 192.168.11.22:5523

it's connected fine, when I run the app over the android studio 
this message pop-up "session app Error installing APK"
and mobile disconnected and trying to connect it but it gives me this on CMD

    unable to connec 192.168.11.22:5523

**Comment by steveward** [comment]
:wave: @mohamedkhairy 

This issue tracker is for GitHub Desktop -- it looks like your question is about the Android Debug Bridge (ADB). I'd recommend posting a question on https://stackoverflow.com if you are having issues with ADB.

**Comment by mohamedkhairy** [comment]
@steveward 
I see this, but when I ask  a question on Stackoverflow it gets ignored and try it here I get more benefit
