### ISSUE TITLE
Error message does not go away

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#4242]
## Description

@nerdneha pointed this out in her [comment](https://github.com/desktop/desktop/pull/4216) over in #4216.

> FYI, right now, if i put in a bunch of spaces into the input so that the input is all white space, the error message is The destination already exists which is weird to me. Removing the white spaces does not remove the error, the error persists until i type something that could theoretically exist

## Version

* GitHub Desktop: 1.1.0

* Operating system: macOS and Windows

## Steps to Reproduce

1. Open the Clone Repository dialog
1. Select the URL tab
1. Press <kbd>space</kbd>
1. Note the error message displayed
1. Delete the blank space added
1. Note the error message is still displayed

### Expected Behavior

The error message to go away when the input is empty.

### Actual Behavior

The error message is never cleared.

## Additional Information

I addressed the issue not clearing issue in [94bb0d9](https://github.com/desktop/desktop/pull/4216/commits/94bb0d971724451265935dd4bfe53a17c4ae39d8).

![clone-repo-whitespace](https://user-images.githubusercontent.com/1834387/37303190-fc7032aa-262d-11e8-8a51-73fd51a3e10a.gif)

**Comment by Daniel-McCarthy** [comment]
This issue appears to be resolved as of #6357.
I have tested it in the URL tab and I can no longer reproduce this.

**Comment by billygriffin** [comment]
+1, thanks @Daniel-McCarthy!
