### ISSUE TITLE
Launching the external editor is not working on windows 10.

### ISSUE THREAD

**Issue by Yash-Pal** [desktop/desktop#4246]
## Description

**I just installed the github desktop on my windows 10 PC. I have installed both editor "Atom" and "Microsoft Visual Studio Code" and selected one is VS Code. Now when I tried to open repository with the editor with shortcut Ctrl+Shift+A it doesn't do anything. I have changed my default editor to "Atom" but still not working.**

## Version

* GitHub Desktop: 1.1.0

* Operating system: Windows 10

### Expected Behavior
Selected Editor should be open when I press **Ctrl+Shift+A** or by opening it from **Repository -> Open in <Selected Editor>**

### Actual Behavior
Nothing happening.

**Comment by shiftkey** [comment]
@Yash-Pal thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by shiftkey** [comment]
> Now when I tried to open repository with the editor with shortcut Ctrl+Shift+A it doesn't do anything.

Does manually launching the external editor with the menu item work?

**Comment by Yash-Pal** [comment]
Manually launching the external editor with the menu item is not working. And where do I find the log file?

Thanks!

**Comment by shiftkey** [comment]
@Yash-Pal apologies, I had a look over [the implementation](https://github.com/desktop/desktop/blob/release-1.1.0/app/src/lib/editors/win32.ts) of this and it's logging things at the `debug` level, which doesn't end up in these logs.

Could you open the **View** | **Toggle Developer Tools** menu item, run through the steps to trigger the issue, and check the **Console** for any interesting messages that might explain what's failing?

**Comment by Yash-Pal** [comment]
I toggled the Developer tool and tried to open editor with available methods manually and with shortcut too. But console doesn't show any errors warnings etc. And one more thing I want to tell you that I am using windows 10 64 bit operating system.
Device Configuration Info:
![device specification](https://user-images.githubusercontent.com/19922707/37500174-fea8eeb4-28ed-11e8-9e7f-d181b2983d74.png)


Developer Tools screenshot: 
![console](https://user-images.githubusercontent.com/19922707/37500109-a521a0ac-28ed-11e8-8b3e-1939e6820a6a.png)

Thanks!

**Comment by shiftkey** [comment]
@Yash-Pal oops, could you toggle the verbosity from "Info" to "Verbose"? (yay defaults)

**Comment by Yash-Pal** [comment]
Yeah sure,

I have launched the application and opened up the developer tool then went to console tab then filtered *Verbose*

After Launch application
![verbose-1](https://user-images.githubusercontent.com/19922707/37512459-417c026e-2928-11e8-8477-a48fe4173d3f.png)

Cleaned all *Verbose* and pressed shortcut key and then tried to open up by going through manually
![verbose-2](https://user-images.githubusercontent.com/19922707/37512546-79bbf684-2928-11e8-9ae6-8d4173ddb53e.png)

Another screensot
![verbose-3](https://user-images.githubusercontent.com/19922707/37512572-8ad362fe-2928-11e8-90eb-4fbf363e67d2.png)

**Comment by shiftkey** [comment]
I've not been able to reproduce this problem on my setup:

 - Windows ` 10.0.16299.248`
 - GitHub Desktop 1.1.0
 - Visual Studio Code 1.21.1 (installed with defaults)
 - Atom 1.25.0 (installed with defaults)

The fact that the app is able to detect VS Code or Atom suggests that our _detection_ logic is fine, and we're able to find a valid registry entry at one of these locations:

https://github.com/desktop/desktop/blob/76216ec81d638eb7c0333e5934dec03ea9de5469/app/src/lib/editors/win32.ts#L63-L77

We then look at the keys at this registry path for the install location:

https://github.com/desktop/desktop/blob/76216ec81d638eb7c0333e5934dec03ea9de5469/app/src/lib/editors/win32.ts#L213-L221

If something is different about your setup, it might explain why we're not able to launch it. Any ideas how your setup differs to mine?

**Comment by Yash-Pal** [comment]
Yes detecting editors on system is working perfect. I don't have any idea where I can find win32.ts can you please let me know where I can find this file.
While working in office the issue is same in my PC having windows OS with same configurations.  I noticed while working launching editor with shortcut key or with manual launching is working on some repositories. Suppose I have setup 10 repositories and there is only one or two repositories which is perfectly working with quick launching but rest are behaving the same. Is there any conflication if repositories  or something else ?

Thanks!

**Comment by shiftkey** [comment]
> I don't have any idea where I can find win32.ts can you please let me know where I can find this file.

This is the Typescript source file, which is transpiled and minified into the compiled app - you won't be able to find it locally, but there are source maps which help for debugging inthe app.

> Suppose I have setup 10 repositories and there is only one or two repositories which is perfectly working with quick launching but rest are behaving the same. Is there any conflication if repositories or something else ?

Not that I'm aware of. This is the work we do when launching, and we only pass in the path to the repository root:

https://github.com/desktop/desktop/blob/d94c03789d5be85184d5ec508c86c1872ce131ce/app/src/lib/editors/launch.ts#L11-L28

**Comment by Yash-Pal** [comment]
Here is win32.ts you might see this:

[win32.txt](https://github.com/desktop/desktop/files/1828553/win32.txt)

**Comment by manwithgills** [comment]
Hi Gents. I am running into the same issue. I am using a Windows 7 Pro 64bit machine. I have Git, Atom, and Github desktop installed. While reading through this thread I ran my developer tools console and have come across the error when I try to launch an external editor: 

Command line interface for Atom not found at 'C:\Users\daltonc\AppData\Local\atom\bin\atom.cmd'

When I try to open in command prompt it informs me that I do not get Git installed.

**Comment by shiftkey** [comment]
@manwithgills this is a separate issue to the one currently discussed:

> While reading through this thread I ran my developer tools console and have come across the error when I try to launch an external editor:
> > Command line interface for Atom not found at 'C:\Users\daltonc\AppData\Local\atom\bin\atom.cmd'

This is a known problem with Atom not installing the command line shortcut that Desktop requires - please read this comment for more details: https://github.com/desktop/desktop/issues/2585#issuecomment-326901330

> When I try to open in command prompt it informs me that I do not get Git installed.

This is a warning that you don't have a standalone version of Git installed. The previous Classic Desktop application contained a "Git Shell" experience, but that's been deprecated in our Electron build in favour of installing [Git for Windows](https://gitforwindows.org/).

**Comment by Yash-Pal** [comment]
@shiftkey you can close the issue now. I don't have any more issues with Github Desktop as it is working perfectly since l last commented on this issue.

Thank you very much for your valuable support.

**Comment by Haacked** [comment]
> Hi Gents.

Hi @manwithgills, I appreciate the friendliness in tone with this salutation and I assume no ill intent. I did want to suggest a more inclusive greeting might look like "Hey y'all" or "Hey folks" or "Hello comrades" or "Hello fellow human beings (and potential sentient AIs)."

As a gentle friendly reminder, when you address an issue thread, you not only address the folks currently in the thread, but all the people watching and those who will read the thread later. Many of whom are definitely not gents. We want everyone to feel included in the conversation. Thanks!

**Comment by TheMedina** [comment]
I seem to  be having the same issue here. I can't get any editors to open from GitHub Desktop. Any thoughts on what caused this to happen?

**Comment by shiftkey** [comment]
@TheMedina please open a new issue and fill out the template so we can investigate

**Comment by j-f1** [comment]
@shiftkey Over in prettier/prettier, we had some success with adding the [`lock`](https://github.com/apps/lock) bot (https://github.com/prettier/prettier/pull/4802). We configured it to lock after 90 days of inactivity, and we had it add a label instead of commenting so collaborators wouldn’t get [2k](https://github.com/prettier/prettier/issues?q=label%3Alocked-due-to-inactivity+is%3Aclosed+sort%3Aupdated-desc) notifications. GitHub’s label description feature lets us give some brief instructions:

<img alt="Label description says to “Please open a new issue and fill out the template instead of commenting.”" src="https://user-images.githubusercontent.com/25517624/42833129-4b40a97c-89c1-11e8-8af8-2124e59cd940.png">

**Comment by shiftkey** [comment]
@j-f1 I like this idea. I'll get it setup.

**Comment by HunterDG** [comment]
Same issue here!

**Comment by shiftkey** [comment]
@HunterDG please open a new issue and fill out the template so we can investigate

**Comment by AfnanAlnajar030** [comment]
I had the same problem, and I don't know if it'll work on any one of your computers. But, I opened my editor that I wanted it to recognize, quit the gitHub Desktop app (I am on mac) and then tried it again and it worked. Probably just luck, but maybe try this out. 

Also completely unrelated, I feel like 'Hi Gents' was a OK greeting (I am a woman).

**Comment by flybyray** [comment]
> * Visual Studio Code 1.21.1 (installed with defaults)
> ...
> The fact that the app is able to detect VS Code or Atom suggests that our _detection_ logic is fine, and we're able to find a valid registry entry at one of these locations:

I am completely unhappy with this "fine" detection logic.
At least when there is no possibility to override it.

The default/"fine logic" should be the simplest assumption - `code` is on the path!

As an example use a package manager which installs applications in a fashion like many package managers do. It is more portable way for instance https://scoop.sh/
