### ISSUE TITLE
Allow repo list to be pinned open so I can use cursor keys to select them one by one

### ISSUE THREAD

**Issue by gingerbeardman** [desktop/desktop#4250]
## Description

Allow repo list to be pinned open

## Version

* GitHub Desktop: 1.1.0 electron

* Operating system: 10.13.3

## Steps to Reproduce
1. Open repo list
2. Try to move down them one at a time to find repo’s that are no longer on disk

### Expected Behavior

able to use cursor keys to move down repo list

### Actual Behavior

repo list closes

**Comment by gingerbeardman** [comment]
Ah, I can Tab to them and the cursor works.

**Comment by shiftkey** [comment]
> Ah, I can Tab to them and the cursor works.

Yes, keyboard navigation should work there - and we lazily refresh the repositories so that should be a way to trick the app into checking the repository exists on disk.

**Comment by gingerbeardman** [comment]
I ended up having to go into each repo
