### ISSUE TITLE
Ability to quickly remove all invalid (deleted on disk) repos from repo list

### ISSUE THREAD

**Issue by gingerbeardman** [desktop/desktop#4251]
## Description

Ability to quickly remove all invalid (deleted on disk) repos from repo list

## Version

* GitHub Desktop: 1.1.0

* Operating system: 10.13.3

## Steps to Reproduce

1. remove some repos from disk 
2. Try to remove them all from GHD

### Expected Behavior

Should be able to remove all invalid repos easily

### Actual Behavior

Cannot easily remove invalid repos

## Additional Information

Should be able to remove all invalid repos easily

Also not possible to see which repos are “missing” https://github.com/desktop/desktop/issues/4254

**Comment by shiftkey** [comment]
@gingerbeardman thanks for the suggestion!

We're already tracking this in #2375, so please follow along with that issue.

**Comment by gingerbeardman** [comment]
Would you accept a PR?

**Comment by shiftkey** [comment]
@gingerbeardman not for this approach, but let's talk about #2375 over there.
