### ISSUE TITLE
Ability to "Remove and Move to Trash” a repo

### ISSUE THREAD

**Issue by gingerbeardman** [desktop/desktop#4252]
## Description

Whenever I am done with a repo I have to do two things:
1. remove repo from GHD
2. delete repo from disk

it would be good if I could do both in GHD

## Version

* GitHub Desktop: 1.1.0

* Operating system: macOS 10.13.3

## Steps to Reproduce

Try to delete a repo from your disk using only the GHD interface
 
### Expected Behavior

Should be a “Remove and Move to Trash” option for a repo

### Actual Behavior

No way to delete repo on disk

## Additional Information

![screen shot 2018-03-15 at 17 23 40](https://user-images.githubusercontent.com/49612/37479885-a9df761e-2875-11e8-890a-a977f61c09ab.png)
    Remove and Move to Trash

**Comment by shiftkey** [comment]
@gingerbeardman thanks for the suggestion.

Historically, Desktop hasn't been in the disk management "game", and "Remove" would only remove the repository from being tracked in Desktop, leaving the repository on disk just in case you were using it elsewhere. 

A suggestion to move this to configuration is being tracked in #2108, which I think is better aligned with the Desktop philosophy. Please add your thoughts to that issue.
