### ISSUE TITLE
Unnecessary modal dialog when repository is missing on disk

### ISSUE THREAD

**Issue by gingerbeardman** [desktop/desktop#4253]
## Description

An unnecessary dialog is shown when the repository is missing from disk.

## Version

* GitHub Desktop: 1.1.0
* Operating system: macOS 10.13.3

## Steps to Reproduce

1. open repo list
2. go to a repo that has been deleted on disk and can no longer be found

### Expected Behavior

Skip the error dialog, as the information below says more and is more useful

![screen shot 2018-03-15 at 17 34 38](https://user-images.githubusercontent.com/49612/37480450-2e5400bc-2877-11e8-994a-9a4f700f2008.png)

### Actual Behavior

You get a modal error dialog

![screen shot 2018-03-15 at 17 34 35](https://user-images.githubusercontent.com/49612/37480444-2ca4a370-2877-11e8-84ae-02680e1cde3b.png)

**Comment by shiftkey** [comment]
@gingerbeardman as these are two separate parts of the app, I split out the first issue into #4256 and will use this issue to focus on the second set of steps

**Comment by gingerbeardman** [comment]
These were just to examples, I think the app should be reviewed for all instances where it shows these error dialogs. They appear very slowly due to their animation, so when they’re essentially “nags” with only one option, they’re a real usability issue.

**Comment by justalemon** [comment]
I can confirm this issue, but randomly occurs when removing 2 or more repos and selecting them.

And it shows both the "Unable to find path to repository on disk." dialog and "Can't find REPO_NAME" message:

![Captura](https://user-images.githubusercontent.com/11861253/37564065-0df62488-2a6d-11e8-88fe-d73e57748953.PNG)

* GitHub Desktop: 1.1.0
* Operating system: Windows 10 v1709 c16299.309

**Comment by steveward** [comment]
Closing this out as we no longer show that modal dialog.
