### ISSUE TITLE
Pull Request display

### ISSUE THREAD

**Issue by jasondenney** [desktop/desktop#4257]
GitHubDesktop v1.1.0 
macOS 10.13.3

Upon pull request being created I would see the pull request in the branch dropdown within the application.  Upon that pull request being merged and marked as closed the pull request number still appears on the branch.

## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@jasondenney thanks for the report!

> Upon that pull request being merged and marked as closed the pull request number still appears on the branch.

We were made aware of this in #4122 and has been fixed in #4148, which should go out as an update next week - we've got [a few fixes](https://github.com/desktop/desktop/pull/4234) that we're currently QAing.
