### ISSUE TITLE
Open/add local repo from command line should not prompt for approval

### ISSUE THREAD

**Issue by gingerbeardman** [desktop/desktop#4259]
## Description

If I’m adding a repo from the command line, the path is most likely correct and I have already made my decision to add it. I do not want to have to confirm a dialog box.

This would also help with automation

## Version

* GitHub Desktop: 1.1.0

* Operating system: macOS 10.13.3

## Steps to Reproduce

`github open “/users/matt/projects/test”`

### Expected Behavior

Should just add it if it’s a valid local repo

### Actual Behavior

I have to confirm a dialog accepting the values I know are correct because i passed them to the app

![screen shot 2018-03-15 at 23 18 43](https://user-images.githubusercontent.com/49612/37495844-3c087f6e-28a7-11e8-97e4-39bb1c2c4cd8.png)

Alternatively, an `add` command could be added to the github command line app.

**Comment by shiftkey** [comment]
As part of this workflow we already check if this path is associated with a tracked repository, and select that to avoid confusion:

https://github.com/desktop/desktop/blob/1b96ce51c752cc077b53a4ad01052f16ce1905b2/app/src/lib/dispatcher/dispatcher.ts#L841-L848

I think I'd be :thumbsup:  to adding the repository if:

 - it comes from the `open-repository-from-path` code path (i.e. the user initiated this from the CLI)
 - is a valid Git repository

Otherwise we should end up on this path, with details about why we need user input.

cc @desktop/core @desktop/comrades for feels

**Comment by j-f1** [comment]
One case to think about is that other apps might use the URL scheme to open Desktop.

**Comment by shiftkey** [comment]
> One case to think about is that other apps might use the URL scheme to open Desktop.

I think we handle that through a different code path

**Comment by shiftkey** [comment]
I'm going to set this as `help wanted` because it's a relatively isolated change, and while there might be some tricks to testing this I think it's a relatively easy task to review.

**Comment by j-f1** [comment]
> I think we handle that through a different code path

Nope, we [literally `open`/`cmd /c start` the URL](https://github.com/desktop/desktop/blob/289ae93745aa69c1142870af4e1db8d09e0881ab/app/src/cli/open-desktop.ts).

**Comment by shiftkey** [comment]
@j-f1 `github open [path]` prefixes `openLocalRepo` to whatever argument it gets:

https://github.com/desktop/desktop/blob/ffec2323d6663379aca834f129df2718af6ee51c/app/src/cli/commands/open.ts#L28-L30

This is handled in the main process to transform it into an `open-repository-from-path` action:

https://github.com/desktop/desktop/blob/289ae93745aa69c1142870af4e1db8d09e0881ab/app/src/lib/parse-app-url.ts#L106-L111

And this is propagated to the renderer process - so it's already something that we don't support through the CLI.

**Comment by j-f1** [comment]
I meant that another app/website could make a similar URL, and if we bypassed user approval when the URL is called, arbitrary code could be downloaded onto the user’s computer.

**Comment by shiftkey** [comment]
> I meant that another app/website could make a similar URL, and if we bypassed user approval when the URL is called, arbitrary code could be downloaded onto the user’s computer.

This is what currently happens in Desktop when you provide a URL rather than a path:

<img width="515" src="https://user-images.githubusercontent.com/359239/38068969-9424d752-335f-11e8-8d48-a8f398d448d7.png">

I don't think the proposed change here to **add the valid repository that exists on disk** changes this behaviour (which isn't ideal).

**Comment by WKKSD123** [comment]
![dmr_120_000](https://user-images.githubusercontent.com/35544702/39010518-bd13b614-43c3-11e8-92fb-8222cf28ced8.jpg)
[Desktop.docx](https://github.com/desktop/desktop/files/1929289/Desktop.docx)
![dmr_120_000](https://user-images.githubusercontent.com/35544702/39018253-639b25f6-43da-11e8-8bfc-0f92139fd0c9.jpg)
# ##

**Comment by WKKSD123** [comment]
#

**Comment by shiftkey** [comment]
Retesting the flows based on what's currently in #4513.

> What if the user mistypes the name?

You end up in the original dialog with a warning that there's no repository there. This seems fine:

<img width="431" src="https://user-images.githubusercontent.com/359239/39900221-ad828e40-5503-11e8-816d-25267659b2ce.png">

> Can we keep the open via URL topic out of scope here and move to some other ticket where could be clarified first?

:thumbsup: I'll port that to a fresh issue so we can close this out.

**Comment by shiftkey** [comment]
I've opened #4658 to track the URL handling through `github open`, and I think everything else is taken care of.
