### ISSUE TITLE
Error on git commit using visual studio 2017

### ISSUE THREAD

**Issue by Mugesh-Rajaram** [desktop/desktop#4261]
Hi Team,

   Am getting error while committing the code using Visual Studio 2017 can anyone help me out.

![image](https://user-images.githubusercontent.com/16976667/37507526-f1a44412-2914-11e8-8f35-e24065420f1a.png)

**Comment by shiftkey** [comment]
@Mugesh-Rajaram this is the repository for GitHub Desktop, and we are unable to help out with this specific problem.

Please ensure you are up to date with Visual Studio and [check the support forums](https://developercommunity.visualstudio.com/spaces/8/index.html) to see if your issue has been reported - [this one](https://developercommunity.visualstudio.com/content/problem/64028/git-failed-with-a-fatal-error-fatal-aggregateexcep.html) looks similar but didn't seem to be resolved.
