### ISSUE TITLE
'lfs' is not a git command bug in Windows 10 180309 New build

### ISSUE THREAD

**Issue by Synaxis** [desktop/desktop#4263]
Hello ! , i'm having this issue while using windows 10 latest update
[
![capture](https://user-images.githubusercontent.com/29115371/37509565-8ef5327e-28d6-11e8-9d46-fbe4c1d00fef.PNG)
](url)

**Comment by shiftkey** [comment]
@Synaxis which insiders channel is this coming from?

**Comment by Synaxis** [comment]
Hi , It is the build 1803 , windows 10.
But the issue seems to go away after rebooting the pc
