### ISSUE TITLE
mac, blue buttons should get executed when pressing the return key

### ISSUE THREAD

**Issue by bj97301** [desktop/desktop#4270]
## Description

Example:
![screen shot 2018-03-16 at friday march 16 2018 10 53 am](https://user-images.githubusercontent.com/1450431/37536630-5ff5ac1a-2908-11e8-8a7e-54eea2271c33.png)

When pressing return it does nothing. 

## Version

1.1.0
* GitHub Desktop:

* Operating system:
10.13.3

## Steps to Reproduce

press command+o to add a repo
find the repo
press enter

### Expected Behavior

Pressing enter should do the action that is associated with the blue button.
### Actual Behavior

nothing

## Additional Information

This is a pretty standard thing within the OS and it would be a good idea to adopt it.  I am sure there are other blue buttons elsewhere.  Let me know if I can help track them all down.

**Comment by tierninho** [comment]
@bj97301 Thank Bryan for filing. 

For me, hitting `enter` re-engages the `Choose` button, as the focus is not moved to the `Add Repository` button. 

![screen shot 2018-03-16 at 1 41 36 pm](https://user-images.githubusercontent.com/14828183/37543731-c4953732-291f-11e8-86e1-ad4fadef5c83.png)

**Comment by bj97301** [comment]
@tierninho good point.  I guess it depends on where the focus is at.  If the focus is at the local path text field then it does nothing. 

Another one would be the commit to master button: 
![screen shot 2018-03-16 at friday march 16 2018 4 13 pm](https://user-images.githubusercontent.com/1450431/37548426-0a1841a4-2935-11e8-8bc0-15df369e5157.png)

The clone repo dialog(s):
![screen shot 2018-03-16 at friday march 16 2018 4 15 pm](https://user-images.githubusercontent.com/1450431/37548451-3c521b40-2935-11e8-88c9-0fbb9de96f72.png)
![screen shot 2018-03-16 at friday march 16 2018 4 15 pm 1](https://user-images.githubusercontent.com/1450431/37548455-47932d3c-2935-11e8-821c-6737ca2fee4e.png)
The url tab seems to work. 

The cancel dialog for delete branch:
![screen shot 2018-03-16 at friday march 16 2018 4 21 pm](https://user-images.githubusercontent.com/1450431/37548575-290685ac-2936-11e8-8f59-8e88a7564627.png)

Sign in button in prefs:
![screen shot 2018-03-16 at friday march 16 2018 4 23 pm](https://user-images.githubusercontent.com/1450431/37548601-5a17d59c-2936-11e8-9256-6b5053b9e420.png)

The save button in the advanced tab in prefs:
![screen shot 2018-03-16 at friday march 16 2018 4 23 pm 1](https://user-images.githubusercontent.com/1450431/37548620-74fdba7a-2936-11e8-97ae-02fce497efcf.png)


I think thats it. Hope that helps.  Let me know if you need any help.

**Comment by niik** [comment]
Removed the good-first-issue and help-wanted labels as it's not clear to me exactly what the task consists of. For good-first-issue we should have very clearly defined goals.

This issue also feels similar to #3629 so I'm going to close this one out but please let me know if they differ and we can reopen this.

**Comment by bj97301** [comment]
Looks like its the same.  Thank you @niik
