### ISSUE TITLE
Hanging on filtering during git clone...

### ISSUE THREAD

**Issue by adrianefresh** [desktop/desktop#4271]
Trying to clone a repo from github (using github desktop) and keeps hanging on filtering (at about 55%, though exact point keeps changing...). 

![screen shot 2018-03-16 at 1 45 06 pm](https://user-images.githubusercontent.com/19844841/37543881-0e00bb9c-2931-11e8-9313-b8e4c56ea91b.png)

Software:

```
git version 2.16.2
git-lfs/2.4.0 (GitHub; darwin amd64; go 1.10)

OSX 10.11.6

Github desktop 1.1.0
```

**Comment by adrianefresh** [comment]
Aaaand... suddenly on the ~7th attempt it worked. My guess is a github LFS server issue.

**Comment by onekid1469** [comment]
I am staring into the sun I can’t even see the screen

**Comment by onekid1469** [comment]
All the work spaces are taken here in the shop

**Comment by shiftkey** [comment]
@adrianefresh there are some log files available from the **Help** | **Show Logs in Finder** menu item which might contain details about the failed clones - happy to help troubleshoot if you see anything interesting in there.
