### ISSUE TITLE
simplify constructors in models folder by using parameter properties

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#4272]
See https://github.com/desktop/desktop/pull/4243 for initial discussion.

[TL;DR](https://en.wikipedia.org/wiki/Wikipedia:Too_long;_didn%27t_read):

 - we're mostly :thumbsup: on this idea, with some concerns about readability
 - this is tentatively in-scope for 1.3 (we want to get some of the features in 1.2 out first)
 - this is probably something that an external contributor can help with, but we've got plenty of contributions to work through currently

We'll update this issue when this is ready to be started.

**Comment by shiftkey** [comment]
I'm going to drop this from a given milestone, but mark it open for people who want to dive into a bit of TS refactoring work.

I suggest porting one file at a time, at least initially, as this will help with us reviewing and catching potential errors.

**Comment by Daniel-McCarthy** [comment]
I have continued looking into the other `models` and found one that seems to generate a bit of an issue (small albeit).

With `models/pull-request.ts` is a property called `number`. In the constructor the argument that is used to initialize `number` is called `number_`. When this constructor is switched to use parameter properties, however, a linting issue appears to result due to the name being the same as the type.

This does not seem to be a major issue, but one worth noting for these changes as it may occur elsewhere. In this situation, it would likely be sufficient to specify the name as `requestNumber`.

**Comment by shiftkey** [comment]
I'm not a fan of the `number_` pattern to get around this constraint that [tslint is enforcing](https://palantir.github.io/tslint/rules/variable-name/), but it's also pretty pragmatic. We likely stumbled into that because the Pull Request API returns a field named `number` and we want to avoid confusion.

What if we used `pullRequestNumber` instead, which was used previously in that file?

**Comment by Daniel-McCarthy** [comment]
Sounds great. I will switch it to `pullRequestNumber` and get it ready to make a pull request for that file.

**Comment by Daniel-McCarthy** [comment]
As an update to this, I am getting close to done with this.
- Except for one file that additionally requires a rename, I have all of the files in the `models/` folder complete and ready for a pull request. (I have not done so for all of them yet, but I was planning on doing them in chunks to keep it manageable).
- I am currently working on the `models/diff` folder.

I did find one circumstance that seems to be unique from the previous ones. `diff/diff-selection` has a constructor that sets the properties normally, but with a ` || null`. I am not sure if I can duplicate this behavior while using parameter properties. I suspect this constructor would need to be left alone in this case, unless there is a way to do this that I am not aware of.

**Comment by j-f1** [comment]
How about e.g. `public divergingLines: Set<number> | null = null`? Would that work?

**Comment by Daniel-McCarthy** [comment]
Ah, that's great! Thank you @j-f1 , that works perfectly.

**Comment by say25** [comment]
@Daniel-McCarthy are all of these done now?

**Comment by Daniel-McCarthy** [comment]
@say25 There's still `models/diff/diff-selection` and `models/diff/raw-diff` which I will create a pull request for very soon. So very close. I had previously accidentally left `raw-diff` out of this list until I caught it yesterday.

**Comment by shiftkey** [comment]
I'm going to close this out as I believe everything has been covered, but feel free to submit fresh cleanup PRs if you spot additional work in the wild. Thanks again @Daniel-McCarthy for all your hard work here!
