### ISSUE TITLE
Selecting repository does not clear the filter text

### ISSUE THREAD

**Issue by saschanaz** [desktop/desktop#4273]
## Description

1. Click 'Current repository' button and type some filter text
  ![image](https://user-images.githubusercontent.com/3396686/37555086-6a436608-2a25-11e8-82f1-86dbcd006e85.png)
2. Select the repository
3. Click 'Current repository' again

## Version

* GitHub Desktop: 1.1.0

* Operating system: Windows 10 RS3

### Expected Behavior

The filter text should disappear, as it did in 0.5.3

### Actual Behavior

The filter text still exists, I have to delete it to select another repo

**Comment by justalemon** [comment]
I can confirm that.

![repro](https://user-images.githubusercontent.com/11861253/37563992-e5d26e9a-2a6b-11e8-811b-74f9e0128f21.gif)

## Version

* GitHub Desktop: 1.1.0
* Operating system: Windows 10 v1709 c16299.309

**Comment by shiftkey** [comment]
@saschanaz @justalemon thanks for the feedback. This is a change we made in https://github.com/desktop/desktop/pull/2571 and this case was mentioned:

> Speaking entirely for myself, when I cmd-T, it's to switch repositories. Keeping the filtered text is kinda the opposite of what I want.

And we settled on a compromise 

> Or how about after CMD-T the focus is put on the filter text and the current text is selected? That won't slow you down if you want to type something else, yet will make it easier for me by having the current filter persisted.

**Comment by saschanaz** [comment]
Hmm, how about creating a separate tab for that purpose? "all repositories" and "search"?

1. A user searches by a filter text. "search" tab is then automatically selected
2. The user selects a repo
3. The search flyout closes
4. "all repositories" tab opens when the user clicks "Current repository" again, and the user can manually select "search" tab to access previous search

**Comment by justalemon** [comment]
Or maybe adding a configuration option like "Save the repository search after choosing a repository".

**Comment by donokuda** [comment]
I'm 👎on adding a setting for this behavior. I think the compromise we came up with is still valid, and I don't consider hitting backspace to clear the field disruptive to workflows.

**Comment by saschanaz** [comment]
A compromise is a compromise, I hate when I click "Current repository" with my mouse and then it forces me to tap my keyboard button. My local repositories have their unique names, no need to keep search results.

**Comment by lee-dohm** [comment]
I agree with @saschanaz from the perspective that the current experience is optimized for those that navigate this flow via the keyboard at the expense of the person using the mouse. If I have previously filtered my repositories and successfully found the repo I wanted and want to find another one but don't remember the name of it, I have to click the tiny target of the ❌ to clear the filter before continuing. This is a much more cumbersome flow than it is in the keyboard scenario.

**Comment by billygriffin** [comment]
We're looking at this whole area in the context of #6460, so I'm going to close this in favor of that issue. Based on our research thus far, it seems reasonably likely that we'll leave the existing compromise in place as it seems to work reasonably well for most folks. But I wanted us to have context on this issue as we look at that one. Thanks everyone for weighing in!
