### ISSUE TITLE
Open in Visual Studio Code never works for me.

### ISSUE THREAD

**Issue by deep5050** [desktop/desktop#4277]
Neither the CTRL+SHIFT+A nor clicking "open in visual studio code" work for me.
![vs](https://user-images.githubusercontent.com/27947066/37567864-04d574c2-2af3-11e8-92ae-deffcd22a9e8.gif)

**Comment by shiftkey** [comment]
What version of VSCode do you have installed? And which build of GitHub Desktop and Windows?

I'm also looking at #4246 which might be related to this issue.

**Comment by shiftkey** [comment]
Actually, I'm going to close this out as a duplicate of whatever is happening in #4246, please follow along with that issue.
