### ISSUE TITLE
Installer should transfer settings and uninstall the classic app

### ISSUE THREAD

**Issue by Pr0methean** [desktop/desktop#4279]
## Description

When I installed the new GitHub Desktop app on my machine that already had the old GitHub app (with the blue-on-white icon), the old app remained installed and there was no prompt to uninstall it. I also had to log in again and drag-and-drop all my cloned repositories.

## Version
* GitHub Desktop: 1.1.0 (exe installer)
* Operating system: Windows 10 Pro 64-bit

## Steps to Reproduce
1. Install the old GitHub app.
2. Log into GitHub.
3. Clone some repos.
4. Download and run the exe installer for the new app.

### Expected Behavior
My login and repo locations are transferred over. The old app is uninstalled (or at least, I'm prompted to do so, with the default answer being yes). This is what typically happens when installers detect an older version of the app they're installing.

### Actual Behavior
The old app remains installed. The new app isn't initially logged in or aware of any repos.

**Comment by TaylorDale** [comment]
Perhaps import old data but definately do not uninstall old Github desktop without the user permission - they are different products.

**Comment by niik** [comment]
Hey @Pr0methean. The discussion about importing data from the old clients is over at https://github.com/desktop/desktop/issues/186 so please subscribe to that issue to follow along. As for automatically uninstalling the classic app we prefer leaving that choice up to the user.
