### ISSUE TITLE
Cannot run multiple instances of the program

### ISSUE THREAD

**Issue by TaylorDale** [desktop/desktop#4280]
## Description
In the old Github Desktop you could have multiple instances of the application open - this was great for multi-desktop work on different repos. This does not look like the case anymore.

## Version
* GitHub Desktop: 1.1.0
* Operating system: Windows 10

## Steps to Reproduce
1. Right-Click Github desktop icon
2. Click on Github Desktop
3. Should open a new instance

### Actual Behavior

It doesn't

**Comment by shiftkey** [comment]
@TaylorDale thanks for the feedback. This is something we're already tracking in #3606, and you can see some of the context around this change there - and what would be affected by disabling the "single instance mode" that Electron supports. Please follow along with that issue.
