### ISSUE TITLE
New branch's parent is fork-default instead of origin-default

### ISSUE THREAD

**Issue by Pr0methean** [desktop/desktop#4281]
## Description
When I check out a branch from the origin repository rather than from my fork of it, I get a detached HEAD. When I try to create a branch so that I can directly push changes to the origin (I have that permission), the branch's parent becomes my *fork's* default branch.

I managed to work around this by choosing "Git Shell" from the Start menu and rebasing the fork's default to the origin's default. However, clicking "Git Shell" had the side effect of reinstalling the old GitHub app alongside the new one.

## Version
* GitHub Desktop: 1.1.0
* Operating system:
Microsoft Windows [Version 10.0.16299.309]
(c) 2017 Microsoft Corporation. All rights reserved.

## Steps to Reproduce
1. Fork an organization repo where you have permission to push to the default branch.
2. Clone it in GitHub Desktop.
3. Check out the default branch from the origin.
4. Press Ctrl-Shift-N and choose a name for the new branch.

### Expected Behavior
The parent of the new branch is the *origin's* default branch.

### Actual Behavior
The parent of the new branch is the *fork's* default branch.

**Comment by shiftkey** [comment]
@Pr0methean thanks for the feedback!

We're using the `default_branch` returned by the repository API here, so it does make sense that a fork's default branch would come from it's repository API value. 

I could go one of two ways here:

 - stick with the fork repository API value - maybe it's been changed for a good reason?
 - choose the upstream repository API value - to help reduce friction when opening a PR against the upstream repository?

cc @desktop/core @desktop/comrades for feels

> Fork an organization repo where you have permission to push to the default branch.

@Pr0methean I'm curious why, after forking, the fork doesn't initially have the same default branch to the upstream repository. Has the upstream repository chosen a different default to `master`? Any extra information here will help with reproducing the behaviour you're seeing...

**Comment by Pr0methean** [comment]
In this case, my fork's default branch had diverged from that of the origin. I've since managed to rebase it (since merging conventionally would create spurious empty merge commits the next time I pushed back).

**Comment by Pr0methean** [comment]
In any case, my main point is that when a detached head becomes a branch, its parent should stay the same. The detached head's parent was `heads/GlowstoneMC/dev`, so when I converted the detached head to a branch, the branch's parent should also have been `heads/GlowstoneMC/dev`.

**Comment by iAmWillShepherd** [comment]
@Pr0methean 

Could you provide a bit of clarification on what's necessary to successfully reproduce this issue?

Here are the steps I've done to try to reproduce this issue:
1. Clone a forked repo I have push access to
1. Check out `origin/master` (iamwillshepherd/desktop)
1. Create new branch, `test-a` 

After checking the state of the repo, I see that the _parent_ of `test-a` is `master`
```
╭─iamwillshepherd ~/Desktop/desktop-fork  ‹test-a› 
╰─$ cat .git/refs/heads/master 
d1324f56d02dd9afca5d2e9da545905a7d41d671
```

```
╭─iamwillshepherd ~/Desktop/desktop-fork  ‹test-a› 
╰─$ git rev-list --format=raw test-a...master
commit b8945b015c5dd3bfb35d161a9d65661108c5013b
tree 1d3ce8ba7ed7e7996a91820765c5847adabc8ee3
parent d1324f56d02dd9afca5d2e9da545905a7d41d671
author William Shepherd <williamrshepherd@gmail.com> 1531171161 -0500
committer William Shepherd <williamrshepherd@gmail.com> 1531171161 -0500

    Here you go

```

I also did these steps just in case you meant the upstream remote of the fork:
1. Check out `upstream/master` (desktop/desktop)
```
╭─iamwillshepherd ~/Desktop/desktop-fork  ‹master› 
╰─$ git checkout upstream/master 
M	app/static/common/choosealicense.com
M	app/static/common/gitignore
Note: checking out 'upstream/master'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 1cd48a0e2... Merge pull request #4770 from desktop/more-repo-info
```
As you can see, the commit pointed to by `upstream/master` is _1cd48a0e2_

2. Create new branch, `test-b` 

```
╭─iamwillshepherd ~/Desktop/desktop-fork  ‹test-b› 
╰─$ git rev-list --format=raw test-b...master    
commit e81d7d4dc397abb065228acf48ac698076b142de
tree 346ae6d428de71685d1ca3c75e4fbfb00443fc6a
parent d1324f56d02dd9afca5d2e9da545905a7d41d671
author William Shepherd <williamrshepherd@gmail.com> 1531172036 -0500
committer William Shepherd <williamrshepherd@gmail.com> 1531172036 -0500

    Another commit

```

The commit is still reachable from `master` (d1324f56d02dd9afca5d2e9da545905a7d41d671).

**Comment by Pr0methean** [comment]
I think this only affects branches that start as detached heads.

**Comment by billygriffin** [comment]
@Pr0methean Thanks for the report here. We haven't seen this from others, and it feels like only a very niche configuration that could get folks into this place, so I'm going to close this for now.
