### ISSUE TITLE
Commit failed - exit code 128 received, with output: '*** Please tell me who you are.

### ISSUE THREAD

**Issue by samcodingmaster** [desktop/desktop#4282]
## Description
it doesn't let me creat a commit

## Version

* GitHub Desktop:
1.1.0
* Operating system:
windows 7

### Expected Behavior
commit to master

### Actual Behavior
error:
Commit failed - exit code 128 received, with output: '*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'win 7@f-PC.(none)')'

**Comment by shiftkey** [comment]
@samcodingmaster thanks for the report.

It looks like you bypassed a step in the Welcome Wizard which asks you to enter your Git user name and email details, which Git requires for creating commits.

You can find these details by: 

 - open the **File** | **Options** menu item
 - selecting the **Git** tab from the dialog
 - enter the name and email address that you want to associate with Git commits
 - save the changes and try again

Let me know if you have any other issues with this setup.

**Comment by weichangying** [comment]
thank you for helping
