### ISSUE TITLE
[UNTNG] Upgrade nudge from macOS to Desktop Electron

### ISSUE THREAD

**Issue by nerdneha** [desktop/desktop#4286]
This is part of #4285 and is for the work done on the macOS Desktop Classic application

**Changes:**
- [ ] create a `popup` on app launch with `read more` and `remind me later` button 
   - `read more` button opens the url: `desktop.github.com/upgrade/classic/` AND reminds the user in 30 days
   - `remind me later` removes the popup and reminds the user in 30 days
   - clicking on the red traffic light `x` button removes the popup and reminds the user in 30 days
- [ ] final image/copy (see last section in description) 
- [ ] update copy on `About` info that no longer says the app is up to date
- [ ] provide some steps in the PR on how we can test the reminder popping up in `30 days` in code review, given the fact that you are aware of the implementation details

**User Flow functionalities to check:**
(let's pretend the user is `Tracy`)
- If `Tracy` opens the app and somehow quits the app without engaging in the popup (ex: killing the process), they will see the popup appears on the next app launch
- If `Tracy` resizes the app or connects to an external monitor, the popup appears in the center with a fixed size (500px x 255px) no matter what
- `Tracy` sees copy that matches macOS casing
- `Tracy` sees a popup appears after 30 days if they 1) close the popup by `x`-ing out, 2) clicking on `read more`, or 3) clicking on `remind me later`
- If `Tracy` clicks on `read more`, it'll open `desktop.github.com/upgrade/classic/` in whatever default browser they have

**Other pieces**:
- Windows work - #4287 
- analytics

**Notes:**
* img size is 500px x 255px
* you are awesome and thank you

#### Before
[Before] For `popup`:
Before, `Tracy` sees Desktop Classic for macOS on app launch

[Before] For `about`:
![image 2](https://user-images.githubusercontent.com/1834387/37617982-eee1b7b2-2bb4-11e8-81a7-7d4cd9ff0903.png)

#### After
[After] For `popup`:
![upgrade dialog macos](https://user-images.githubusercontent.com/1834387/37618058-23932892-2bb5-11e8-8099-f211c15c99a6.png)

[After] For `about`:
![about dialog macos](https://user-images.githubusercontent.com/1834387/37618064-2b932d1c-2bb5-11e8-99c9-a81d30ec7d9d.png)

#### Image for popup modal
![upgrade-nudge-image-mac](https://user-images.githubusercontent.com/1834387/37978395-c8387056-319a-11e8-99eb-34f6d95450c6.png)

**Comment by joshaber** [comment]
![giphy-12](https://user-images.githubusercontent.com/13760/37660282-6d51cda8-2c28-11e8-9286-9b6bba7f7d73.gif)

**Comment by agisilaos** [comment]
@joshaber Welcome back ❤️

**Comment by shiftkey** [comment]
![](https://media.giphy.com/media/B3nATT4FPkb3G/giphy.gif)

**Comment by joshaber** [comment]
Should the window be modal?

**Comment by niik** [comment]
Yes, at least that’s what I envisioned. If that goes against everything
you’ve ever stood for I’m open to changing my mind.

**Comment by nerdneha** [comment]
![upgrade-nudge-image-mac](https://user-images.githubusercontent.com/1834387/37977809-661a5b10-3199-11e8-9e59-fafbdd58746b.png)

**Comment by j-f1** [comment]
What do you think about changing “Appease linter” to something more positive? (maybe “Make sure to check for esc if list is empty” from earlier in the PR)

**Comment by nerdneha** [comment]
FYI the description is updated to reflect:
* final image to be used in popup
* final link for `read more` button (desktop.github.com/upgrade/classic/)
* copy being finalized (whatever is in the mockups; nothing has changed)
