### ISSUE TITLE
[UNTNG] Upgrade nudge from Windows to Desktop Electron

### ISSUE THREAD

**Issue by nerdneha** [desktop/desktop#4287]
This is part of #4285 and is for the work done on the Windows Desktop Classic application

**Changes:**
- [ ] create a `popup` on app launch with `read more` and `remind me later` button 
   - `read more` button opens the url: `desktop.github.com/upgrade/classic/` AND reminds the user in 30 days
   - `remind me later` removes the popup and reminds the user in 30 days
   - clicking on the back `<` button removes the popup and reminds the user in 30 days
- [ ] final image/copy (see last section in description) 
- [ ] update copy on `About` info that no longer says the app is up to date
- [ ] provide some steps in the PR on how we can test the reminder popping up in `30 days` in code review, given the fact that you are aware of the implementation details

**User Flow functionalities to check:**
(let's pretend the user is `Tracy`)
- If `Tracy` opens the app and somehow quits the app without engaging in the popup (ex: killing the process or using window controls), they will see the popup appear on the next app launch
- If `Tracy` resizes the app or connects to an external monitor, the popup appears in the center with a fixed size (500px x 255px) no matter what
- `Tracy` sees copy that matches Window casing
- `Tracy` sees a popup appears after 30 days if they 1) close the popup by `<`-ing out, 2) click on `read more`, or 3) click on `remind me later`
- If `Tracy` clicks on `read more`, it'll open `desktop.github.com/upgrade/classic/` in whatever default browser they have

**Other pieces**:
- macOS work - #4286
- analytics

**Notes:**
* img size is 500px x 255px
* you are awesome and thank you

**Before:** 
[Before] For `popup`:
Before, `Tracy` sees Desktop Classic for macOS on app launch

[Before] For `about`:
![original about view](https://user-images.githubusercontent.com/1834387/37618271-0ac84292-2bb6-11e8-8c59-f8c67f465ea4.png)

**After:**
[After] For `popup`:
![upgrade nudge windows](https://user-images.githubusercontent.com/1834387/37618294-23e51124-2bb6-11e8-87df-d94c90511f4f.png)

[After] For `about`:
![about dialog windows](https://user-images.githubusercontent.com/1834387/37618307-2898dad4-2bb6-11e8-81c1-3b2d5aa8a867.png)

#### Image for popup modal
![upgrade-nudge-windows](https://user-images.githubusercontent.com/1834387/37978411-d266463e-319a-11e8-93e1-32e16d98e6ac.png)

**Comment by shiftkey** [comment]
![](https://user-images.githubusercontent.com/359239/37938728-09b925d8-31ab-11e8-8451-849499092c20.gif)

**Comment by nerdneha** [comment]
![upgrade-nudge-windows](https://user-images.githubusercontent.com/1834387/37977851-7d09c522-3199-11e8-9408-30daa85bacef.png)

**Comment by j-f1** [comment]
Same comment as https://github.com/desktop/desktop/issues/4286#issuecomment-376570718.

**Comment by nerdneha** [comment]
FYI the description is updated to reflect:
* final image to be used in popup
* final link for `read more` button (desktop.github.com/upgrade/classic/)
* copy being finalized (whatever is in the mockups; nothing has changed)
