### ISSUE TITLE
'SSL certificate problem: unable to get local issuer certificate' when trying to clone repos

### ISSUE THREAD

**Issue by calioto** [desktop/desktop#4291]
## Description
Cannot clone repositories

## Version

* GitHub Desktop: N/A - Company won't allow desktop installed. Running git version 2.14.1.windows.1

* Operating system: Microsoft Windows [Version 6.1.7601]

## Steps to Reproduce
1) Trying to clone any repository via command line (e.g. git clone https://github.com/planetoftheweb/learnangular5.git)

### Expected Behavior
Repository cloned

### Actual Behavior
Error given:
fatal: unable to access 'https://github.com/planetoftheweb/learnangular5.git/': SSL certificate problem: unable to get local issuer certificate

## Additional Information
Here's the output of my git config -l --show-origin command:
file:"C:\\ProgramData/Git/config"	core.symlinks=false
file:"C:\\ProgramData/Git/config"	core.autocrlf=true
file:"C:\\ProgramData/Git/config"	core.fscache=true
file:"C:\\ProgramData/Git/config"	color.diff=auto
file:"C:\\ProgramData/Git/config"	color.status=auto
file:"C:\\ProgramData/Git/config"	color.branch=auto
file:"C:\\ProgramData/Git/config"	color.interactive=true
file:"C:\\ProgramData/Git/config"	help.format=html
file:"C:\\ProgramData/Git/config"	rebase.autosquash=true
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"	http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"	http.sslbackend=openssl
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"	diff.astextplain.textconv=astextplain
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"	filter.lfs.clean=git-lfs clean -- %f
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"	filter.lfs.smudge=git-lfs smudge -- %f
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"	filter.lfs.required=true
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"	filter.lfs.process=git-lfs filter-process
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"	credential.helper=manager
file:H://.gitconfig	https.proxy=http://webproxy.bankofamerica.com:8080
file:H://.gitconfig	http.proxy=http://webproxy.bankofamerica.com:8080
file:.git/config	core.repositoryformatversion=0
file:.git/config	core.filemode=false
file:.git/config	core.bare=false
file:.git/config	core.logallrefupdates=true
file:.git/config	core.symlinks=false
file:.git/config	core.ignorecase=true

**Comment by tierninho** [comment]
@calioto Thanks for filing. This looks similar to another issue, now resolved: https://github.com/desktop/desktop/issues/3684

Let us know if this resolves your issue.

**Comment by calioto** [comment]
@tierninho If I read the issue you mentioned correctly, I think I have my config setup correctly. I have http.sslbackend set to openssl and http.sslcainfo also set. The user in the mentioned issue had two different values for http.sslbackend while I only have one. I am not reading the solution correctly? Thanks.

**Comment by shiftkey** [comment]
> GitHub Desktop: N/A - Company won't allow desktop installed. Running git version 2.14.1.windows.1

Please report this issue to the [Git for Windows](https://github.com/git-for-windows/git) project, as we can only help you address issues with GitHub Desktop and it's embedded Git (which is a later version than the one you are currently running).

**Comment by azatadilov** [comment]
SSL certificate problem: unable to get local issuer certificate

I have got the same problem, I cant understand what to do for 3 days

**Comment by shiftkey** [comment]
@azatadilov please open a new [bug report](https://github.com/desktop/desktop/issues/new?template=bug_report.md) and fill out the template if you believe this is something related to GitHub Desktop...
