### ISSUE TITLE
When files are moved, it can be impossible to see the full filename/path

### ISSUE THREAD

**Issue by snoblenet** [desktop/desktop#4298]
## Description

When files are moved, it can be impossible to see the full filename/path. See example screenshot:

![image](https://user-images.githubusercontent.com/62277/37744645-6e8bebde-2dc4-11e8-98a1-12790b99b376.png)

## Version
* GitHub Desktop: 1.1.0
* Operating system: Mac OS X 10.13.3

## Steps to Reproduce
1. Move a file
2. Examine in Github Desktop

### Expected Behavior
The full filename/path, both before and after the move, is visible.

### Actual Behavior
The full filename/path, both before and after the move, is *not* visible.

## Additional Information
I'd appreciate one of the following possible solutions:

1. File list column automatically expands to show all information
2. File list column can be manually resized to show more or less information
3. File listings show the full filename/path (before and after move) in a pop-up on hover
4. The full filename/path (before and after move) for the currently selected file is shown near the heading

**Comment by snoblenet** [comment]
Thanks @niik. I think you're comments hold for the History view but not the Changes view?

**Comment by ramirocantu** [comment]
I feel that a on hover pop-up would be the appropriate way to deal with this.

**Comment by steveward** [comment]
Column widths are no longer limited thanks to https://github.com/desktop/desktop/pull/13439, so I'm going to close this out.
