### ISSUE TITLE
Failure to create the LFS progress tracking file should not abort a clone

### ISSUE THREAD

**Issue by niik** [desktop/desktop#4307]
#4304 describes a scenario where the clone operation fails because we're unable to create a temporary file for Git LFS to write its progress output to. I think we should be much more lenient and default to logging the error and not tracking LFS progress in the rare case where we're unable to create that file.

The function which creates the file is `createLFSProgressFile`: https://github.com/desktop/desktop/blob/acda0e0b95a0cee29c7de4808e1023c038fb49e9/app/src/lib/progress/lfs.ts#L6-L17

It's used from `executionOptionsWithProgress` https://github.com/desktop/desktop/blob/acda0e0b95a0cee29c7de4808e1023c038fb49e9/app/src/lib/progress/from-process.ts#L18-L38

We should catch any errors from `createLFSProgressFile` inside of `executionOptionsWithProgress` and continue on without LFS progress tracking.

**Comment by MagicMarvMan** [comment]
I developed a solution. I open a PR soon.
