### ISSUE TITLE
Loading ahead/behind info for each branch is slow

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#4318]
This issue fell out of #4182. Scrolling through the list of branches is a bad experience. The rendering is taking a long time because shelling out to Git actually has a bit of overhead. I initially tried caching `ICompareResults` in the `GitStore`, but cache invalidation is still a thing. 

![2018-03-23 17 21 49](https://user-images.githubusercontent.com/1715082/37855729-b6d6ba68-2ebe-11e8-8e9b-f8ecb8df2404.gif)

**Comment by j-f1** [comment]
Would it be possible to render just the branch name and add the ahead/behind info later?

**Comment by shiftkey** [comment]
> Would it be possible to render just the branch name and add the ahead/behind info later?

This is basically the work I've done in #4399. I'll mention this issue in that PR.
