### ISSUE TITLE
Error trying to manually set email adress

### ISSUE THREAD

**Issue by CooleKakkerlak** [desktop/desktop#4322]
## Description

I was trying out some things to get a unity game to run on my mobile device, including downloading other versions of Java and setting environment variables. I was just trying different things, and eventually it worked. However, when I got back to a different unity project and tried to commit some changes using github desktop, it threw an error and said 'please tell me who you are', and asked me to set my email address, which it had never done before.

The error message told me to type in this command: `git config --global user.email "youremail@gmail.com"`
This doesn't work for me, and it throws the following error: `error: could not lock config file C:/Program Files (x86)/Java/jdk1.8.0_161/.gitconfig: No such file or directory` If I omit the `--global` it does work, but then I have to do that in all my repositories. 

The Java version that the error message is referring to does not exist on my computer. I do have a 'jdk/1.8.0_162', which I guess is just a newer version, but that does not contain a .gitconfig file either. This issue does not have a very high priority for me, because I can commit and push changes by adding my email in every seperate repository, but it does mean there is something wrong which I would like to fix. Any help would be appreciated, and I'm not very smart with computers sometimes so it might just be a dumb msitake :)

## Version

* GitHub Desktop: Version 1.1.0

* Operating system: Microsoft Windows [Version 10.0.16299.309]

## Steps to Reproduce

I'm not quite sure how to reproduce my problem. I think it has to do with installing and deinstalling different versions of Java, but that's just a guess.
### Expected Behavior

I expected to be able to commit changes in any repository in github desktop, without having to enter my email address every time.
### Actual Behavior

It gives an error when I commit changes, telling me to enter my email address.

**Comment by shiftkey** [comment]
@CooleKakkerlak thanks for the report:

> The error message told me to type in this command: `git config --global user.email "youremail@gmail.com"`
This doesn't work for me, and it throws the following error: error: could not lock config file `C:/Program Files (x86)/Java/jdk1.8.0_161/.gitconfig: No such file or directory` If I omit the `--global` it does work, but then I have to do that in all my repositories.

This looks like a different version of Git is being used here in your shell (does the JDK come with Git?), but we can workaround this for Desktop. The default location for your global `.gitconfig` is under your `$HOME` directory - so `C:\Users\{account}\.gitconfig` - and this is what Desktop should be looking at.

If you add this section to this global config file:

```
[user]
	name = {your name}
	email = youremail@gmail.com
``` 

That should be applied to all your repositories when used in Desktop.

**Comment by shiftkey** [comment]
I'm going to close this out as resolved with a workaround. @CooleKakkerlak please let us know if you have any other issues committing in Desktop.

**Comment by CooleKakkerlak** [comment]
@shiftkey, thanks a lot for your answer, I'm very sorry I didn't answer earlier, I did not read the notification email. 
In my C:\Users\account folder, there is no .gitconfig file. I have been searching around a bit, and if I type `echo %HOME%` in CMD, it says `C:\Program` Files\jkd-10` (although there is no .gitconfig file in there either). Side note, I do have invisible files turned on. 

I think I have set this home myself when I was setting up my laptop to run an application on my phone, as I have been setting system environment variables. 

So now I think I want to know this: how to find the $HOME folder, or how to set it properly? Or maybe there is a whole different fix altogether?

**Comment by shiftkey** [comment]
> So now I think I want to know this: how to find the $HOME folder, or how to set it properly? 

To see what environment variables are set, this guide can help: https://www.computerhope.com/issues/ch000549.htm

Git on Windows looks for `HOME` to represent it's home directory, which sounds like the problem you're encountering. Windows itself doesn't have this set by default, and there's some more details about this behaviour here: https://github.com/git-for-windows/git/pull/1548/files#diff-b9d078f9ff198fc54e599a6f15a81df3R366
