### ISSUE TITLE
github application not fetching origin can only publish branch

### ISSUE THREAD

**Issue by alenart91** [desktop/desktop#4325]
## Description

When opening the github desktop application it no longer fetches origin for one of my repository's. Under the history tab none of the changes are updating, I have to view the repository on the github website to see if there has been any updates.

## Version

* GitHub Desktop: 1.1.0

* Operating system: Microsoft Windows version 10.0.16299.309

## Steps to Reproduce

1. open github desktop application
2. select repository 

### Expected Behavior

Able to fetch updates from repository

### Actual Behavior

can only "publish branch" and can't see any updates

## Additional Information

This is only happening on one of my repository's

**Comment by shiftkey** [comment]
@alenart91 thanks for the report! 

> can only "publish branch" and can't see any updates

The "Publish branch" button appears when the current branch is local and hasn't been published to GitHub. If there's an existing branch on GitHub that you think the application should be tracking, I can help to wire this up (it should do this if you checkout the branch from the app).

Can you share a screenshot of the app when the problem branch is in use, as well as attaching the output of this command?

```
git remote -vv
```

This will help me confirm the next steps.

**Comment by alenart91** [comment]
Hi, thanks for the reply. Here is a screenshot
![ss](https://user-images.githubusercontent.com/25220883/37968873-f388ddb4-3194-11e8-9e2e-a04b32314aa3.jpg)


As you can see the current branch has been published to github for awhile now, no idea why it just stopped fetching the updates. There's only one branch for this repository. If I publish the branch now will that cause any problems? There has been tons of updates since than. I'm not sure what to do with that command you posted.

**Comment by alenart91** [comment]
When I try to publish the branch it tells me there have been changes made and to pull it. It then displays this error

![ss2](https://user-images.githubusercontent.com/25220883/37971863-a17a97da-319c-11e8-804c-2d35b23b21ba.jpg)


when I try to pull nothing happens

**Comment by steveward** [comment]
👋 @alenart91 

It looks like one of your references pointing to the `master` branch is broken. This is easy to fix, but you will need to drop into the command line. Here's how to do that:

1. Open the repository in GitHub Desktop
2. Go to the file menu and select `Repository` > `Open in Command Prompt`
3. Run the command `rm .git/refs/remotes/origin/master` to delete the broken ref
4. Run the command `git fetch origin` to grab a new copy of the ref
5. Run the command `git branch -u origin/master` to have your local `master` branch track the `origin/master` branch

That should get things working for you. Let me know if you run into any issues.
