### ISSUE TITLE
Support multiple open windows

### ISSUE THREAD

**Issue by walaura** [desktop/desktop#4340]
## Description
Working across multiple repos at once can be a but of a pain point at the moment as there's no 1 click way to switch them or just have an overview of what's going on in number of them (This has a level of overlap with #1593 )

I feel a quick fix for this would simply be to enable multiple windows of the app being open at the same time, that way if you want to work on two different repos you can just whip up a second  window. Everything else being the same. _Maybe a right click item on the repo list to open a repo in a new window_.

This is one of those things that sounds easier said than done but it would be a huge help for complex workflows.

## Version
* GitHub Desktop: 1.1.1
* Operating system: MacOS 10.11.6

## Additional Information

**Comment by shiftkey** [comment]
@walaura thanks for the feedback. This is something we're already tracking in #3606, and you can see some of the context around this change there - and what would be affected by disabling the "single instance mode" that Electron supports. Please follow along with that issue.

**Comment by xgdgsc** [comment]
I find it weird that you expect to track future proposal in a closed issue :sweat_smile:

**Comment by j-f1** [comment]
@xgdgsc We keep those issues closed because we reserve the open issues list for issues that need triage, a response from the OP, or things we plan to fix/add according to the roadmap. The team goes through all the issues labeled `future-proposal` every six months and adds some of them to the roadmap.
