### ISSUE TITLE
Windows shortcut for opening PowerShell shows a backtick but requires an apostrophe

### ISSUE THREAD

**Issue by DanTup** [desktop/desktop#4342]
On macOS, Ctrl+Backtick opens the terminal. On Windows it's Ctrl+Apostrophe, but the text on the menu still shows a backtick.

**Comment by DanTup** [comment]
It's a UK layout. It looks the same as your screenshot, backtick is top left. To open PoSh I have to press apostrophe which is over on the right next to the enter key :(

**Comment by shiftkey** [comment]
@DanTup thanks for the extra details. I can flip my layout over to UK, like this:

<img width="309" src="https://user-images.githubusercontent.com/359239/37993713-38de7b96-325b-11e8-9ba2-ce6f4df301b1.png">

Which does change the keys somewhat, and it behaves like you were reporting:

<img width="833" src="https://user-images.githubusercontent.com/359239/37993807-700fe5dc-325b-11e8-90e0-1859382bd92f.png">

This probably needs some learnings about how Electron is managing these keyboard shortcuts on different layouts, as well as getting some facetime with the Atom team about how they've tackled this problem...

**Comment by DanTup** [comment]
Aha, cool :-)

FWIW it's fine on UK Macs, but their British keyboard layout is a bit weird; it's somewhere between a UK/US PC keyboard (some things, like @ and " are the same as US, but other bits - like the tall return key - are same as UK!).

**Comment by shiftkey** [comment]
Yeah, have a look at [the different layouts Windows supports](https://docs.microsoft.com/en-us/globalization/windows-keyboard-layouts) and laugh:

![l](https://user-images.githubusercontent.com/359239/37994658-f6d07990-325d-11e8-94c6-ac73341706c2.gif)

**Comment by DanTup** [comment]
Nice :(

Is there no way to get at the character the key would type rather than the key? It seems like it should be a trivial problem (after all, typing into a text box does the right thing), but since I've had similar comments about keyboard layouts when I raised a bug in VS Code's key bindings I'm guessing it is not! ;-(

**Comment by shiftkey** [comment]
> Is there no way to get at the character the key would type rather than the key?

We tell Electron the characters and modifiers we want to associate with the shortcut, like this:

https://github.com/desktop/desktop/blob/f49ee7a2714b49c3c4008b9623c08c75ca3e0303/app/src/main-process/menu/build-default-menu.ts#L231-L236

Clearly that approach isn't working for layouts that move the characters to different keys. I need to wrap my head around what happens after that, and how keyboard layouts affect that, and I fear this involves going deep into the Chromium source which requires time and courage...

**Comment by shiftkey** [comment]
I'm going to fold this up into #3240 as that issue is tracking the same bug but affecting a different keyboard layout. Please follow along with that issue while we figure out how to better handle shortcuts in the app.
