### ISSUE TITLE
Follow Windows conventions for installation

### ISSUE THREAD

**Issue by mhouston100** [desktop/desktop#4345]
## Description

Attempting to install GitHub desktop with Applocker enabled is a nightmare. The MSI and EXE's contained in there are all signed using different publisher certificates and some are not signed at all. This is a very inconsistent experience.

The installer essentially acts as malware, obfuscating several EXE's and DLL's inside multiple compressed files, installing directly to the user profile, attempting to run automatically for users when they log in...

The application installer should just follow normal Windows software conventions and locations. Install executable's to 'Program Files', save user data to 'AppData', save shared data to 'ProgramData'.

There is no reason for the EXE to have to run from the users profile on a Windows machine.

## Version
* GitHub Desktop: 1.1.0
* Operating system: Windows 10 1709

## Steps to Reproduce
Attempt to install GitHub Desktop with AppLocker enabled.

### Expected Behavior
Passable: All EXE's, MSI's and DLL's signed successfully with the same publisher certificate.

Perfect: Follow normal Windows conventions for application installs.

**Comment by shiftkey** [comment]
@mhouston100 thanks for the feedback! 

We're tracking the machine-wide install experience in #1086, which I think will address most of your concerns about the installer behaviour, but it's not currently on our roadmap.

The publisher certificate issue however is separate to that. I'm aware that Git for Windows and Git LFS should be signing their executables, which we bundle into Desktop, and we should be signing Desktop's executables on top of that, but if you are finding _executables_ that aren't signed please let me know. Signed DLL files is less of a priority for me, as it requires me to go and pester upstream projects that have limited bandwidth.

**Comment by mhouston100** [comment]
Thanks for the quick response!

I guess this can be marked as a duplicate and I'll follow the other thread as it progresses.

I might have jumped the gun on saying the executable are not signed, apologies.  It looks like (potentially) AppLocker can't create exceptions automatically due to some metadata being incorrect in some of the files (e.g the Product Name or Version is missing). Creating a publisher rule manually through Applocker appears to work and the certificates are valid, you just need to use '*' for some ofthe values, which is not ideal for compliance.

Not sure this metadata is 'issue worthy' or not, but I'll test further to ensure that is the answer regardless.

DLL is a secondary issue as it's a separate feature in AppLocker, often not even enabled.

**Comment by shiftkey** [comment]
> It looks like (potentially) AppLocker can't create exceptions automatically due to some metadata being incorrect in some of the files (e.g the Product Name or Version is missing).

If you can provide details of which files are missing this metadata I can probably help figure out how easy it is to address this (again, requires pestering upstream). But let's take it to #1086.
