### ISSUE TITLE
Requesting grading (GitHub Classroom) support - bulk clone

### ISSUE THREAD

**Issue by BU-AWolfe** [desktop/desktop#4346]
## Description
In order to support my work with GitHub Classroom - that is, grading my students - I would like to request that the File menu have a new command "Bulk Clone..." or "Clone multiple..."

When the user selects it, GitHub Desktop would present a list of all available repositories with checkboxes the user can turn on for cloning.

The user would navigate to a common parent directory in which all of the clones would be created.

## Version

* GitHub Desktop: 1.1.1
* Operating system: MacOS 10.13.3 (17D102)

## Steps to Reproduce
Enhancement request, not a bug

### Expected Behavior
Requested behavior presented in description

### Actual Behavior
Enhancement request, not a bug

## Additional Information
Enhancement request, not a bug

### Logs

**Comment by shiftkey** [comment]
@BU-AWolfe thanks for the feedback!

This feels very similar to #3849, so please follow along with that issue.

**Comment by BU-AWolfe** [comment]
But I wrote mine better! ;)

[X]
Metropolitan College
Andrew D Wolfe, Jr.
Lecturer
awolfe@bu.edu<mailto:awolfe@bu.edu?subject=Contact+Andrew+Wolfe+at+BU>
http://www.schemaczar.com
+1 617-358-1984

On Mar 27, 2018, at 8:25 PM, Brendan Forster <notifications@github.com<mailto:notifications@github.com>> wrote:


@BU-AWolfe<https://github.com/BU-AWolfe> thanks for the feedback!

This feels very similar to #3849<https://github.com/desktop/desktop/issues/3849>, so please follow along with that issue.
