### ISSUE TITLE
Text search commit history

### ISSUE THREAD

**Issue by shravan2x** [desktop/desktop#4347]
## Description

A text search box for the commit history pane would be useful to quickly pull commits from long ago. Something like:

![image](https://user-images.githubusercontent.com/4096676/38006556-20611a1a-320b-11e8-906e-8c4aeca91be1.png)

## Version

* GitHub Desktop:  1.1.1

* Operating system: Windows 10 Home

**Comment by shiftkey** [comment]
@shravan2x thanks for the feedback!

I'm going to close this in favour of an earlier discussion about this idea: #1543. Please follow along with that issue.
