### ISSUE TITLE
Branch name characters do not retain their capitalisation when created on Desktop and a pull request is opened

### ISSUE THREAD

**Issue by OllyMcBrideOB** [desktop/desktop#4349]
## Description

If a branch is created using Desktop and the branch name uses uppercase characters, when a pull-request is opened (and viewed on .com) the capitalisation has disappeared. 

## Version

* GitHub Desktop:
Version 1.1.1

* Operating system:
Windows 10

## Steps to Reproduce

1. Create a new branch on Desktop
2. Name the branch OB-554_Branch_name
3. Create a pull request (you are taken to .com)
4. The pull request title is now Ob 554 branch name

### Expected Behavior

I would expect the uppercase characters to remain.

### Actual Behavior

The only character that remains uppercase is the first char.

## Additional Information

We use [Jira Smart Commits](https://confluence.atlassian.com/fisheye/using-smart-commits-298976812.html) which looks for the issue key OB-### (where # is the issue number) in various commits and branches. This issue key on GitHub has to match the case of that on Jira in order to be recognised.

I currently have to manually re-type the issue key in every pull-request title, which gets tedious, as I've already entered it correctly when naming the branch.

**Comment by shiftkey** [comment]
@OllyMcBrideOB thanks for the report!

> 3. Create a pull request (you are taken to .com)
> 4. The pull request title is now Ob 554 branch name

This behaviour is external to Desktop, and it's GitHub The Website trying to be clever about the initial pull request title:

 - if a branch has a single commit, it uses the commit summary
 - if the branch has multiple commits, it takes the branch name and tries to turn it into a human-friendly sentence, by removing non-alphabet characters and sentence casing it

Having a pull request experience in the app is being tracked in #295, but that's not currently on our roadmap.

If this is something you're not a fan of, I'd recommend passing feedback on to [GitHub Support](https://github.com/c).

**Comment by shiftkey** [comment]
I'm going to close this out as external to Desktop. @OllyMcBrideOB feel free to reply if you have any other questions!
