### ISSUE TITLE
"Open in external editor" uses absolute path and thus doesn't work

### ISSUE THREAD

**Issue by koenpunt** [desktop/desktop#4350]
## Description

Since the last update the context menu "Open in [External Editor]" doesn't work. At least not for TextMate and Atom. It seems it tries to use the repo path as absolute root, what obviously won't work (except if one would keep their repositories at root (`/`))

## Version

* GitHub Desktop: 1.1.1
* Operating system: macOS 10.13.3 (17D102)

### Logs

_nothing relevant_

**Comment by shiftkey** [comment]
> It seems it tries to use the repo path as absolute root, what obviously won't work (except if one would keep their repositories at root (`/`))

I'm not sure I understand these details here -  where is your repository located on disk, if not under `/`?

I set a breakpoint in `/app/src/lib/editors/launch.ts` with my Atom dev build installed and poked at the values returned for my repository under `/`, and Atom was able to launch it fine - what's different about your setup that I've overlooked here?

<img width="1298" src="https://user-images.githubusercontent.com/359239/38022763-1df1f9ae-32cc-11e8-9709-9104dafb3060.png">

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @koenpunt if you're able to answer the questions above we're happy to revisit this issue.
