### ISSUE TITLE
Can't select and commit individual lines

### ISSUE THREAD

**Issue by oliverodaa** [desktop/desktop#4351]
When using the GitHub Desktop app on Mac (version 1.1.1), I can't select and commit individual lines from a file. Attempting to do it causes the whole file to be committed, not just the lines I had selected.

![ezgif-3-8b1f8291ae](https://user-images.githubusercontent.com/5886107/38047640-c601280c-3288-11e8-81b1-62648a78397a.gif)

**Comment by j-f1** [comment]
Looks like this might be because the file has just been created. Do you encounter this issue with a file that already exists?

**Comment by oliverodaa** [comment]
@j-f1 Thank you for the quick response!

Yes, I also encounter the issue with a file that already exists.

Extra info: I only created `fakeFile.js` because I do not want to share private code from the company I work for.

**Comment by oliverodaa** [comment]
> could you attach your log file

Sure! I was able to recreate the problem and here is the only line in the logs that was generated:
```
2018-03-28T19:24:42.486Z - info: [ui] Executing createCommit: git commit -F - (took 13.708s)
```

> looks like commit took super long and i'm curios if that's due to git hooks

You're quite right! It's a very big project and we run `eslint` and `prettier` on each commit. I double-checked with my coworker and those are the only ones.

**Comment by iAmWillShepherd** [comment]
Do any of the hooks being executed modify the staging area for your repo?

**Comment by oliverodaa** [comment]
They definitely do not.

**Comment by oliverodaa** [comment]
So, Prettier might do that. If you have JavaScript code that is badly formatted then it will update that file to have better formatting.

I will try disabling Prettier to see if it resolves the issue.

**Comment by oliverodaa** [comment]
Disabling Prettier allows me to commit specific lines. Great result. Thank you!

**Comment by iAmWillShepherd** [comment]
Hmm, you may be able to keep it enabled for pushing so you wont have to completely disable it.

Closing since we have no control of what git hooks do to the state of your repo.

**Comment by j-f1** [comment]
@oliverodaa You might be interested in [`pretty-quick --staged`](https://github.com/azz/pretty-quick), which only formats staged (selected in Desktop) lines before committing.

**Comment by shiftkey** [comment]
For reference, we're aware about some tools that run as pre-commit hooks affecting Desktop when trying to partially commit files, like https://github.com/desktop/desktop/issues/1831. It seems to be related to these hooks doing a subsequent `git add`, which is overriding the chosen staged lines.
