### ISSUE TITLE
Commit button disabled for unclear reasons

### ISSUE THREAD

**Issue by skalnik** [desktop/desktop#4354]
## Description

When using GitHub Desktop, the commit button is disabled until a commit summary is typed in. However, for users who are new to Git & GitHub, its not entirely clear why the button is disabled.

## Version
* GitHub Desktop: 1.1.1
* Operating system: MacOS 10.13.3

## Steps to Reproduce
1. Make some changes to a git repo
2. See that the commit button is disabled and there is no indication of why

### Expected Behavior
The Commit Summary field is highlighted in red or indicated as required in some manner

### Actual Behavior
No indication is given.

**Comment by shiftkey** [comment]
:thumbsup: - the current tooltip is just there to ensure the whole branch name can be seen

<img width="446" alt="screen shot 2018-03-29 at 9 31 55 am" src="https://user-images.githubusercontent.com/359239/38059917-280a08a6-3334-11e8-8e72-6549bd7fa1d7.png">

I'm not sure how I feel about the suggestion for highlighting missing fields in red, but this feels like form validation which I'm sure @desktop/design has some input about.

**Comment by skalnik** [comment]
> I'm not sure how I feel about the suggestion for highlighting missing fields in red, but this feels like form validation which I'm sure @desktop/design has some input about.

Yeah, that was just a suggestion. I think any kind of indication that there are required fields missing and what they are would be an improvement here 😸

**Comment by MagicMarvMan** [comment]
I would like to work on it, unless anyone else is already working on it?!

**Comment by shiftkey** [comment]
> I would like to work on it, unless anyone else is already working on it?!

@MagicMarvMan let's hold off for a bit to think about what we want to do to address the issue. Once we've figured that out, we'll label issues that can be worked on by external contributors with `help wanted` - so keep an eye on that label in the meantime!

**Comment by MagicMarvMan** [comment]
Ok. Thank you!

**Comment by donokuda** [comment]
I think the quickest solution here is to update the placeholder to mention that it's required:

<img src="https://user-images.githubusercontent.com/1174461/38512140-448ca098-3bdf-11e8-9def-69f1694116c6.png" width="250" />

We should also add `aria-required="true"` to that specific field.

**Comment by verny2verny** [comment]
OMG, this totally needs fixing. As a relatively new user to GIT, I just spent the last two hours trying to setup a fresh repository and be able to commit my work. This process involved remaking everything from scratch at least a dozen times before I finally stumbled upon this.  Even if this was mentioned somewhere in the quickstart guide, or other manuals for the GitHub extension. 

Vern

**Comment by outofambit** [comment]
hi @verny2verny can you share what version of desktop you're hitting this on? i'm sorry this was so frustrating. i would expect #4429 to help prevent at least some of this pain and it would be really helpful to know more about your experience.

**Comment by verny2verny** [comment]
I am currently using version 1.4.0, GitHub for Unity, downloaded via the asset store. Unity version 2019.1.12f1 on a Windows10pr PC

With this version, at least, there is no indicator saying that a summary is needed in order to make a commit. 

My experience was following the GitHub QuickGuide (pdf) that comes with the package.

Nowhere in this guide, nor in the plugin is it mentioned that a summary is required in order to commit. Without anything entered in the summary field, the commit button remains grayed out (with no indication as to why).

From the looks of 4429, this may already be addressed in latest version? Or at least, it does look like it is being looked into.

Vern

**Comment by outofambit** [comment]
ah thanks @verny2verny for the extra info! GitHub for Unity is a different project than GitHub Desktop. You can find the proper repo here: https://github.com/github-for-unity/Unity. thanks!

**Comment by outofambit** [comment]
closing this issue since we haven't had any further reports of this problem since #4429. thanks all!

**Comment by mr5z** [comment]
Ugh, I'm not new to git and just tried GitHub for Desktop today and it took me almost an hour to figure out what I'm missing. Turns out the commit message I'm filling was the description field the the actual commit message was above it.

I think the button shouldn't be disabled, instead prompt a useful error message that would lead the user to correct their mistakes.

**Comment by KhanA-Ahad** [comment]
commit to master button disable.Any one help?

**Comment by steveward** [comment]
@KhanA-Ahad have you entered a commit message in the `Summary (required)` field? Do you have uncommitted changes in your repository?

**Comment by DClyde** [comment]
For what it is worth I did the exact same thing as @mr5z. I treated the "Summary (Required)" as the title bar for the Description box and after typing into the description box and fumbling around for a couple of minutes flabbergasted as to the issue did I figure it out upon searching the internet and finding this issue.

Not my first time using GitHub for Desktop, but definitely not often enough that I was like "oh right"

**Comment by LucianoCalsolari** [comment]
It is easy ,I don't know why but if you delete a GitHub folder and try again,it works.

**Comment by dbperry17** [comment]
I had the same issue as @mr5z. My laptop screen on my desk turned out to be angled _just right_ to make the actual summary box blend in to the background behind it so that the description box looked like it was where I was meant to put the required summary. It would be really nice if maybe the box was highlighted in red or something if you tried to click commit without it filled in.

**Comment by sonammeena** [comment]
After writing something on the summary (required) portion. I'm continually getting this
![IMG20210303095129](https://user-images.githubusercontent.com/78652990/109752414-61f49900-7c06-11eb-8489-a5b0d1a86747.jpg).

I don't know what is this. please help me to figure out this.

**Comment by tidy-dev** [comment]
@sonammeena  It would appear that your git config email is not able to detect it as an email address. Do you have an email address you can update your git config with? (If you have a github.com account, preferably use the email associated with it) 

If you are not familiar with the command line as shown in the error,
You can update it inside the Desktop by going to:
Windows: File > Options 
or 
Mac: File > Preferences

Then, navigate to Git menu item (left hand menu pane)

Then fill in the Name and Email fields and hit Save.

**Comment by devasia2112** [comment]
The issue was open in 2018, we are in 2021 and the problem persist, not only in the Desktop but also in the web interface, the button "commit changes" is disabled in all my repositories, I do not know if deserve the time to dig into this thing, feels like time wasted. 
Why nobody cares about a simple problem like that? 
Just saying, there is quite a few good option to github/microsoft. I may pick one soon.

**Comment by finnbear** [comment]
A workaround I found was to make the commit manually, outside of Atom, such as with `git commit -m "..."` and `git push` it manually. This got Atom's commit button un-stuck for me.

**Comment by ShawnLi1102** [comment]
Don't do batch commit by selecting all files. If you select more than one file, the commit button is grayed out. This caught me in surprise and it's kind of stupid. Just select one file at a time and commit button will be enabled.

**Comment by Cantersoft** [comment]
I also got hung up on this. I didn't even see the summary field until I found this page.

**Comment by ghost** [comment]
I get commit field unhighlighted when making a change using the website interface. I make a change, but cannot click commit button.

**Comment by steveward** [comment]
@thisisawesome1994 see [this guide](https://docs.github.com/en/github/managing-files-in-a-repository/managing-files-on-github/editing-files-in-your-repository) for information about how to edit/commit files directly on GitHub. This issue tracker is for GitHub Desktop.

**Comment by NotQuiteCosmic** [comment]
As someone who is relatively new to Git and GitHub Desktop, I too hit this summary-field stumbling block. Looking back, a little bit of reading would have revealed the issue (the required is fairly obvious) but the fact of the matter is that it took me the better part of an hour to figure out. While most people wouldn't be caught up by this, I think a relatively simple and very helpful tool would be the following: if someone clicks on the commit button without any summary entered, the Summary box becomes selected, clearly outlined by blue and with typing enabled (much like many login pages do when a username/password isn't entered). This could help mitigate this frustrating barrier to entry.

**Comment by vkenn** [comment]
Who managed to solve this problem ,I added summary but still nothing works 
![image](https://user-images.githubusercontent.com/40527021/157032193-7d9406d0-a93f-4382-a77f-cfe79b1324bd.png)

**Comment by steveward** [comment]
@vkenn it looks like you're committing on github.com, not in GitHub Desktop. I'd recommend reaching out to [GitHub Support](https://support.github.com/) if you are having issues committing on github.com. I believe there have been browser issues with committing in the past, so it may be worth trying a different browser to see if that helps.

**Comment by jaszczykj** [comment]
> Who managed to solve this problem ,I added summary but still nothing works ![image](https://user-images.githubusercontent.com/40527021/157032193-7d9406d0-a93f-4382-a77f-cfe79b1324bd.png)

just like you,

**Comment by jaszczykj** [comment]
> Who managed to solve this problem ,I added summary but still nothing works ![image](https://user-images.githubusercontent.com/40527021/157032193-7d9406d0-a93f-4382-a77f-cfe79b1324bd.png)

just disable adblock and hard refresh

**Comment by vkenn** [comment]
Thank you @jaszczykj it solved it .Have been banging my head for a whole weekend .

**Comment by xbdh** [comment]
disable Ghostery chorme extension may solve

**Comment by madCakes** [comment]
@xbdh do you know why ghostery causes this issue?

**Comment by ReneeDeLuca** [comment]
> just disable adblock and hard refresh

Thank you @jaszczykj! Disabled adblock and ghostery and now it's working.
