### ISSUE TITLE
Remote disconnected on Cloning 

### ISSUE THREAD

**Issue by SteffenHaeuser** [desktop/desktop#4356]
[2018-03-29.desktop.production.log](https://github.com/desktop/desktop/files/1858795/2018-03-29.desktop.production.log)

I tried to Clone a Project I had recently created, but after it started to clone (happened with starting the Desktop through either Google Chrome or the Microsoft Windows 10 Browser) it aborted with "Remote disconnected". I am on a very stable Internet Connection. In both cases it aborted a few seconds after starting.

## Version

Version 1.1.1
* GitHub Desktop:

Microsoft Windows [Version 10.0.16299.309]
* Operating system:
Windows 10

## Steps to Reproduce

Just try to clone the Project. I used a different Directory than suggested.

### Expected Behavior

That the Project is cloned.

### Actual Behavior

It Aborts.

**Comment by shiftkey** [comment]
@SteffenHaeuser thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by SteffenHaeuser** [comment]
Hmmm, if you look at the issue, you can see that the logs are already there. I had attached them when I created the issue. See above. First line of the issue.

The problem seems to be here:

Receiving objects:   0% (1/3959)   
Receiving objects:   1% (40/3959)   
Receiving objects:   2% (80/3959)   
Receiving objects:   3% (119/3959)   
Receiving objects:   4% (159/3959)   
Receiving objects:   5% (198/3959)   
Receiving objects:   6% (238/3959)   
Receiving objects:   7% (278/3959)   
Receiving objects:   7% (310/3959), 284.00 KiB | 438.00 KiB/s   
fatal: early EOF
fatal: The remote end hung up unexpectedly
fatal: index-pack failed
error: RPC failed; curl 56 Failure when receiving data from the peer

(The error was parsed as 4: The remote disconnected. Check your Internet connection and try again.)

**Comment by shiftkey** [comment]
@SteffenHaeuser apologies, I glossed over that and assumed it was missing when I got to the "Logs" section at the end of the template:

This is the detail I was looking for:

```
fatal: early EOF
fatal: The remote end hung up unexpectedly
fatal: index-pack failed
error: RPC failed; curl 56 Failure when receiving data from the peer
```

We had a similar report to this in https://github.com/desktop/desktop/issues/3695, which we traced to a firewall interfering with the clone operation for a specific repository, which I think is what's happening here.

**Comment by SteffenHaeuser** [comment]
Hi!

Thanks a lot, I temporarily disabled the firewall and now it works. Still strange that the Windows Firewall (it was no 3rd party one, just the default Firewall settings of Windows 10) does this, but well, I have a workaround then.

Thanks for your fast help.
