### ISSUE TITLE
Enable React 16.3’s strict mode to catch bad practices

### ISSUE THREAD

**Issue by j-f1** [desktop/desktop#4369]
React 16.3 introduces a new [strict mode](https://reactjs.org/docs/strict-mode.html), which is enabled by wrapping all or a portion of your components with the `<React.StrictMode>` component.

According to the docs, it:

- identifies usages of lifecycle methods that will be deprecated in React 17 (`componentWillMount`, `componentWillReceiveProps`, and `componentWillUpdate`; [migration docs are here](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html))
- warns about using `ref="string"` (there’s a new `React.createRef()` type now that we could use instead of ref functions)
- and runs `constructor`, `render`, the new `getDerivedStateFromProps`, and the first argument to `setState` (if it’s a function) twice to ensure that they’re idempotent

All of these changes only occur when running in dev mode, so behavior in production shouldn’t change.

What do you think about enabling this @desktop/core? (I can’t ping you since the team is private)

**Comment by shiftkey** [comment]
Revisiting this thread, there's a couple of issues I'd like to address before enabling this for development mode:

 - a lot of components are using these old lifecycle functions, so it'll generate a lot of noise in the console until we migrate them to the new API
 - these components aren't really covered by any tests beyond the integration test which isn't satisfactory to catch subtle changes - it'd be nice to use something lean like [`react-testing-library`](https://github.com/kentcdodds/react-testing-library) to capture the "before" behaviour of each component before we open it up to migrating

It's easy to find all mentions of `componentWillMount`, `componentWillReceiveProps` and `componentWillUpdate` in the codebase, but I'd like to craft up a list of refactoring issues that others can help out with so we can track this migration work - on top of everything else we need to worry about currently.

**Comment by shiftkey** [comment]
I've opened #5092 to get `react-virtualized` up to date, and #5093 to track upgrading `react-transition-group`. Once those are in we can look at components in the codebase and figure out that migration strategy.

**Comment by say25** [comment]
I sorta believe this can be closed as its superseded by https://github.com/desktop/desktop/issues/9875 which is 2 years newer
