### ISSUE TITLE
Everything deleted

### ISSUE THREAD

**Issue by LukeTomalty** [desktop/desktop#4370]
Everything I did was not committed and deleted after spending weeks on a project. No idea why this happened, just one day it was all gone.

**Comment by shiftkey** [comment]
@LukeTomalty sorry to hear you're having problems!

It's hard to say what's happened without more information, these things in particular are helpful:

 - a screenshot of the application with the problem repository, with the **History** tab selected
 - log files - the **Help** | **Show Logs in Explorer/Finder** menu items should open the logs folder, and inside those are the log files generated by day.

This will provide some more information to help troubleshoot what the application has been doing.

**Comment by shiftkey** [comment]
Closing this out as inactive. @LukeTomalty if you're able to answer the questions above we're happy to revisit this.
