### ISSUE TITLE
Unable to set install directory

### ISSUE THREAD

**Issue by JamesYeoman** [desktop/desktop#4371]
## Description
I have multiple partitions on my HDD and one of them is a "Programs" partition so that I don't fill the C drive with all the programs (and also so that I can avoid UAC issues with programs). Having a dedicated Programs partition also makes it easier to identify the folder that a program is in (rather than having to sift through AppData and/or Program Files( (x86)).

When installing Git For Desktop (mainly so I don't have to faff around with credentials and/or ssh keys when using bash), it didn't even give me the option to choose the install directory. This seems like a 'must have' for installers so the fact that it doesn't even have an install directory option is rather peculiar.

## Version

* GitHub Desktop: 1.1.1

* Operating system: Windows 8.1

### Expected Behavior

The installer lets me choose the Installation Directory
### Actual Behavior

The installer forces the Installation Directory to be `%APPDATA%\Local\GitHubDesktop`

### Latest
I said the install directory was "%APPDATA%\Roaming\Github Desktop" but infact it is "%APPDATA%\Local\GitHubDesktop

**Comment by shiftkey** [comment]
@JamesYeoman thanks for the feedback!

This is something that we're looking at as part of #1086 so please follow along with that issue.

**Comment by SimranKnight** [comment]
i double click on the github.exe   ... it takes a 30 seconds and gets installed somewhere in the computer... without giving any clue... and when i try to run any git command.... its says not recoganised

**Comment by Ragolution** [comment]
This is still a pressing issue for people with SSDs as their OS drive and an annoying issue for anyone else. On Windows 7, the program installs without any input whatsoever from the user, so it seems this issue is still not resolved.

**Comment by Megalomaniak** [comment]
I have recently adopted to using an SSD for my system drive as well however I have always kept a separate partition or drive for programs. Even before switching to the SSD for system drive. As for installing software into user space, whats up with that abomination?

**Comment by KulaGGin** [comment]
Same here, GitHub Desktop installed itself into `%localappdata%\GitHubDesktop\` without asking me where I want to install it. I'm on SSD and have a dedicated logical drive and a folder for programs `D:\Programs\` where I install all my programs.

**Comment by animanoir** [comment]
This fad of installing software without asking where to should disappear.

**Comment by kylegnally** [comment]
> This fad of installing software without asking where to should disappear.

This fad of closing issues without actually addressing them should also disappear. I can't tell you how many times I've seen it involving how many projects and it reeks of arrogance and dismissal every time.

**Comment by Megalomaniak** [comment]
Sure, but it's also hard to work with an issue tracker full of 5000+ open issues. Inevitably issues have to be closed based on whether why are likely to be handled sometime soon or not. In other words even a valid issue might get closed simply because there is no-one to work on it.

**Comment by alefred** [comment]
Someone found a workaround for solve this problem?, I try to install github desktop in another directy

**Comment by fffnite** [comment]
This is a very needed feature. When deploying this software to over 100 devices with dozens of different users logging in every day per device with non-persistent user profiles, this makes having an installer that installs a 90MB application each time madness.

Please consider enterprise use cases, roaming/persistent profiles do not always make sense. $env:ProgramFiles should be a respected option. 

For anyone else using this. Much like Microsoft teams and no doubt other electron (hell) apps. You can usually get the self contained application extracted using 7zip. Copy the contents of the net45 to your desired location.

`GitHub Desktop Installer\GitHubDesktop.exe\GitHubDesktop-2.5.3-full.nupkg\lib\net45`

**Comment by xinxilas** [comment]
Important for me also...

**Comment by animanoir** [comment]
> This is a very needed feature. When deploying this software to over 100 devices with dozens of different users logging in every day per device with non-persistent user profiles, this makes having an installer that installs a 90MB application each time madness.
> 
> Please consider enterprise use cases, roaming/persistent profiles do not always make sense. $env:ProgramFiles should be a respected option.
> 
> For anyone else using this. Much like Microsoft teams and no doubt other electron (hell) apps. You can usually get the self contained application extracted using 7zip. on the .msi Copy the contents of the net45 to your desired location.
> 
> `GitHubDesktopSetup.msi\GitHubDesktop.exe\GitHubDesktop-2.5.3-full.nupkg\lib\net45`

Nah, consumerism is what ruins things.

**Comment by faridhuseynov** [comment]
was this issue somehow solved?

**Comment by animanoir** [comment]
@faridhuseynov  No. Corporations still ruin everything.

**Comment by Balkoth** [comment]
Try running the installer (msi or exe does not matter) in an environment where AppLocker is active. You just can't get it installed even with admin rights on the target machine, as it extracts the contents to some weird folder in appdata where it runs "update.exe" with normal rights. This is just stupid.
