### ISSUE TITLE
Why doesn't desktop use Linguist?

### ISSUE THREAD

**Issue by decision** [desktop/desktop#4372]
Completely uninformed and non-technical question, but I'm curious why desktop is not using GitHub's own [Linguist](https://github.com/github/linguist) library (or at least the grammars that power it)?

I really like the current implementation, syntax highlighted diffs are super helpful and liven up the app. However, CodeMirror _only_ supports ~100 languages according to their site, which is dwarfed by Linguist's 471? (not sure if that's correct, just going off the `language_id` keys).

CodeMirror is awesome for all of your mainstream needs but it seems the GitHub community has contributed support for a lot of _niche_ languages to Linguist that will never make their way into CodeMirror's collection.

**Comment by shiftkey** [comment]
@decision Linguist is about language detection, and doesn't have any support for syntax highlighting.

**Comment by shiftkey** [comment]
@decision some other things that don't work in Linguist's favour:

 - it's bundled as a Rubygem, so we'd either need to bundle a Ruby runtime with the app or figure out a way to port the functionality (as well as it's dependencies) to run with Node
 - Textmate grammars need to be ported to Codemirror to be consumed in the app - I stumbled upon [this project](https://github.com/dignifiedquire/tmthemeConverter) but it hasn't been updated in over 4 years, so I'm not sure how well-supported that is.

Codemirror no longer supports new languages in-the-box, but has an extensibility story that we're able to add new languages fairly easily (see #3774 for what that looks like), and by keeping this syntax highlighting to a known set of languages we avoid the overhead of doing detection at runtime.

**Comment by decision** [comment]
@shiftkey thanks for your responses, are you sure Linguist isn't used for both the detection and highlighting? [This comment](https://github.com/github/linguist/issues/3156#issuecomment-348805833) implies the TextMate grammars are shipped as-is with Linguist and used to determine how to highlight a language once it's detected by the samples (and heuristics if present).

I checked out #3774 and that's great that new languages can be added (I had no idea CodeMirror wasn't accepting new modes). However, I noticed in [`app/src/highlighter/index.ts`](https://github.com/desktop/desktop/blob/4405c3bb22d33b92ed4682072e7e205420c88ef9/app/src/highlighter/index.ts#L14-L113) the use of `extensionMIMEMap.set` suggests the current implementation can't support two languages sharing an extension?

**Comment by shiftkey** [comment]
> This comment implies the TextMate grammars are shipped as-is with Linguist and used to determine how to highlight a language once it's detected by the samples (and heuristics if present).

I went looking for good samples in Linguist about how to use it for generating the syntax highlighting and couldn't really wrap my head around it. If it requires scanning the whole folder for language stats to _then_ do syntax highlighting, then it's a very different approach to what we currently have. This also still requires us to ship a Ruby runtime to emulate this behaviour, which I'd rather avoid.

> the current implementation can't support two languages sharing an extension?

This is correct. Have you got an example of this that others might encounter within the context of Desktop?

**Comment by decision** [comment]
@shiftkey 
> I went looking for good samples in Linguist about how to use it for generating the syntax highlighting and couldn't really wrap my head around it.

I don't have an understanding of how Linguist works. However, they do make it clear that [.com uses the grammars](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#fixing-syntax-highlighting) for highlighting and there's a small mention of how .com handles it all but it seems vague. Maybe someone from their team could provide some insight.
>Have you got an example of this that others might encounter within the context of Desktop?

There are many languages that share extensions in Linguist, some are syntactically different enough that the samples are enough to differentiate them but ~50 extensions have separate heuristics for determining which language they are.

I don't feel I'm clued up enough to say which languages are _"important"_ enough to warrant being implemented even though it seems CodeMirror has decided that themselves. Some notable ones from a quick look would be `.h`, `.inc`, `.sc`, `.ts` & `.tsx` but there's many more that can be found [here](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) & [here](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.rb), some of these are already included in desktop of course and some others are for _popular_ languages.

**Comment by nerdneha** [comment]
@decision Based on this conversation, it looks like Linguist _could_ provide value. However, as we listed above, especially with needing to bundle a Ruby runtime with the app, this isn't something we'll be working on. 

If anyone is interested in porting a ruby library and its native dependencies to node and incorporate Linguist, we're happy to provide guidance on such a PR.

I'm going to close this for now. If there are any changes that makes Linguist easier to incorporate, let's open this issue again and revisit our options. Thanks!
