### ISSUE TITLE
Distinguish between repositories with identical names

### ISSUE THREAD

**Issue by ralish** [desktop/desktop#4374]
## Description

If multiple repositories with the same name are opened it's impossible to distinguish between them in the drop-down menu opened via the "*Current repository*" button.

## Version

* GitHub Desktop: 1.1.1

* Operating system: Microsoft Windows [Version 10.0.16299.309]

## Steps to Reproduce

1. Open two or more repositories with the same name (see screenshot below)
2. Open the recent repositories list and note they cannot be uniquely identified

### Expected Behavior

There's multiple ways to solve this, but a relatively simple method I'd suggest would be to prefix the parent directory to identically named repositories. This could be done repeatedly until the names are unique.

### Actual Behavior

The recent repositories list shows identically named entries. Finding the desired repository requires opening each identically named repository until you stumble upon the right one.

## Additional Information

This is admittedly a bit of an edge case, but it's still a sub-optimal UX scenario that has I think a relatively simple fix if using the approach I suggested above. In my case, this issue occurs relatively frequently due to working with several organisations that share codebases but maintain their own downstream forks. Renaming affected repositories on my local system to be unique after cloning is of course a workaround, but it's an extra step that ideally shouldn't be necessary, and hasn't been to date when using CLI tools.
<img width="251" alt="current repository" src="https://user-images.githubusercontent.com/3214803/38182982-65cb3c06-3680-11e8-8d88-14b9e29f124f.png">

**Comment by shiftkey** [comment]
@ralish thanks for the feedback! We do differentiate GitHub repositories by showing the owner - see #2027 for that change - but **Other** repositories don't get caught by this (because we don't have the same context).

We're tracking a very similar request for this in #1929, so please follow along with that issue.

**Comment by ralish** [comment]
@shiftkey Thanks for above. I did do a search first but clearly my search-fu needs some work. Cheers!
