### ISSUE TITLE
I cannot open rstudio using internet explorer

### ISSUE THREAD

**Issue by inatigmonrstudio** [desktop/desktop#4377]
## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@inatigmonrstudio thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by inatigmonrstudio** [comment]
Since I am not familier with GitHub site, when I first watched your download page, I was confused which button, laptop download or zip code, to select. So, first , I selected zip code button but this was not the button I should select because this was just a programe and the icon did not appear on my desktop. My laptop is made by Dell with Windows, the latest version. Second, I selected the laptop download and succeeded in downloading the RStudio. Then following your instruction, I selected internet explore as an editor. However, although the popup window with i-explore appeared, it was not activated.
In my opinion, during the download process, I might miss some important procedures. I think I should try the download newly. I would like to select Word as an editor.
If you need more information, please do not hasitate to send your email.

Best regards,
Yasushi Makino

**Comment by j-f1** [comment]
You probably want to download R Studio from [their website](https://www.rstudio.com/products/rstudio/download/#download) instead of from GitHub.

**Comment by inatigmonrstudio** [comment]
Following your suggestion, I downloaded RStudio 1.1.442-Windows Vista/7/8/10 from https://www.rstudio.com. Since I already installed R i386 3.4.4 and R x64 3.4.4, I would be able to use RStudio. However, I could not find RStudio icon on my desktop and I tried to activate RStudio through R but I could not. No change in R. Please tell me how I can use RStudio.

**Comment by shiftkey** [comment]
@inatigmonrstudio this repository is for support for the [GitHub Desktop](https://desktop.github.com/) application.

For support with the GitHub website, please contact [GitHub Support](https://github.com/contact).
