### ISSUE TITLE
upgrade emoji support to align with GitHub The Website

### ISSUE THREAD

**Issue by CarlRosell** [desktop/desktop#4385]
## Description
Some newer emojis are missing. Found this when I was trying to use the `:clown_face:`-🤡 emoji. It is available here on Github.com. Both seem to rely on https://github.com/github/gemoji and the clown_face is available in `master` but not in the commit of the submodule here.

## Version
* GitHub Desktop: 1.1.1
* Operating system: Mac, 10.13.3

## Steps to Reproduce
1. Typing `:clown_face:` in the commit message.

### Expected Behavior
Display the emoji in the auto-complete and in the commit history

### Actual Behavior
Displays `:clown_face:` as a string

**Comment by shiftkey** [comment]
The problem with upgrading the submodule is that this commit no longer bundles the images that Desktop was using: https://github.com/github/gemoji/commit/16c7e21e5e2ff049c1e5affa956b120eb41fc412

The work to translate a character to the on-disk URL is being done here: 

https://github.com/desktop/desktop/blob/68e4dfbe90df4951ba2aca9a1e18b2d39e3c7f86/app/src/lib/stores/emoji-store.ts#L55-L80

We need to figure out some way to workaround this if we're going to catch up with whatever GitHub The Website is doing.

**Comment by shiftkey** [comment]
For reference, I think we need to switch over to native emoji (printing the actual unicode characters instead of an image) and fallback to https://github.com/googlei18n/noto-emoji/ for platforms that don't support native emoji (Win 7, Win 8, Win 8.1 and Linux).
