### ISSUE TITLE
Error fetching and committing 

### ISSUE THREAD

**Issue by henriquefernandes95** [desktop/desktop#4391]
## Version

* GitHub Desktop:

* Operating system:

## Steps to Reproduce

Successfully fetched. 

### Actual Behavior

fatal: unable to access 'https://github.com/henriquefernandes95/java.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - A fun��o de revoga��o n�o p�de verificar a revoga��o do certificado.

**Comment by steveward** [comment]
:wave: @henriquefernandes95 

We have a workaround for the schannel error you are encountering here:

https://github.com/desktop/desktop/blob/master/docs/known-issues.md#certificate-revocation-check-fails---3326

If you run into any problems with that, please let us know!
