### ISSUE TITLE
Fetching Origin - Hang on... doesn't end

### ISSUE THREAD

**Issue by ncwarren96** [desktop/desktop#4397]
## Description

When opening GitHub Desktop the "Fetching Origin" box is continually loading/spinning. After a couple seconds, Windows Explorer opens with no context. I can close Explorer and the GitHub Desktop will still be loading. This is preventing me from pulling anything to my repo. It doesn't matter if I switch branches. I can only get Explorer to open again if I close the application and open it again.

## Version

* GitHub Desktop:
v 1.1.1

* Operating system:
Windows 10.0.16299

### Expected Behavior
Fetch origin and update repo

### Actual Behavior
Nothing

**Comment by shiftkey** [comment]
@ncwarren96 thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by shiftkey** [comment]
> After a couple seconds, Windows Explorer opens with no context. I can close Explorer and the GitHub Desktop will still be loading.

Oh gosh, I think I've see this before (or at least a variant of it): #3604

That example was traced to what looked like a normal executable which actually contained bitcoin mining malware. This bit of information is probably helpful: https://github.com/desktop/desktop/issues/3604#issuecomment-352192406

>  The malware tried to run the mining code each time `cmd` was started.

Look for any strange process spawning in Process Explorer when you try and perform the fetch.

**Comment by ncwarren96** [comment]
wow! It looks like it was the exact same thing as #3604.
It all works now after removing it.

Thanks!

**Comment by adarsh-bankopen** [comment]
I am having this issue in Mac OS (Version: 12.7). Any idea how to rectify this?

<img width="247" alt="image" src="https://user-images.githubusercontent.com/79446266/200988830-27477b80-52ad-4bb9-ab9f-81bcee29860c.png">

**Comment by varjmes** [comment]
> I am having this issue in Mac OS (Version: 12.7). Any idea how to rectify this?
> 
> <img alt="image" width="247" src="https://user-images.githubusercontent.com/79446266/200988830-27477b80-52ad-4bb9-ab9f-81bcee29860c.png">

I found I had this issue when Github Desktop needed the password I set for my SSH key. I need to set it so my computer provides the password without being asked

**Comment by steveward** [comment]
@varjmes GitHub Desktop should prompt you for your passphrase:

<img width="522" alt="Screenshot 2022-12-01 at 1 47 32 PM" src="https://user-images.githubusercontent.com/721500/205135193-ffa9423d-3082-434c-965c-456fe89ec177.png">

Does the log file confirm that this is an SSH issue?  To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. I'd be happy to take a look as the log to see if there's an issue here.

You can also set things up to automatically start ssh-agent and store your keys, see [this article](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent).

**Comment by galeamark7** [comment]
I am having the same issue. I moved the repo folder to a different PC with a new ssh key. I can pull and push in Git Bash but Github Desktup is stuck on hang On and never prompts for passphrase of new ssh key.

If I turn off "Use system OpenSSH" everything works and I am prompted for the passphrase

**Comment by bavanim** [comment]
Thank you for the update. Its saved my time.. Its worked for me.. turn off "Use system OpenSSH" in GitHub Desktop

**Comment by OlegParfenov** [comment]
> I am having the same issue. I moved the repo folder to a different PC with a new ssh key. I can pull and push in Git Bash but Github Desktup is stuck on hang On and never prompts for passphrase of new ssh key.
> 
> If I turn off "Use system OpenSSH" everything works and I am prompted for the passphrase

Thanks, it works
