### ISSUE TITLE
"Open in Atom" always opens new window instead of using existing window

### ISSUE THREAD

**Issue by jaredmoody** [desktop/desktop#4401]
## Description

When clicking "Open in Atom", the file is always opened in a new atom window even if a window containing the file is already open. When clicking "Open with Default Program" when the default program is Atom, then the file is correctly opened in the existing window.

## Version

* GitHub Desktop: 1.1.1

* Operating system: macOS 10.13.4

## Steps to Reproduce
1. Open a project in Atom
2. Modify that file
3. Find the file in the Changes tab of Github Desktop
4. Right click on that file and select "Open in Atom"

### Expected Behavior
The file is opened in the existing Atom window

### Actual Behavior
A new atom window is opened with the file

**Comment by shiftkey** [comment]
@jaredmoody I think you've encountered the same problem I found and fixed in #4381. I tested yours steps against the latest `master` using macOS and Atom and it seems to be working as expected, so this will be available with the next update.
