### ISSUE TITLE
when I try do push from local GitHub to online GitHub, GitHub try publish a new repository 

### ISSUE THREAD

**Issue by RubenK01** [desktop/desktop#4406]
## Description
when I try do push from Desktop GitHub to online GitHub, GitHub try publish a new repository and not do push

## Version

* GitHub Desktop: 1.1.1

* Operating system: Windows 10

**Comment by shiftkey** [comment]
Thanks for reaching out!

It sounds like GitHub Desktop can't find any remotes in your repository, so it's suggesting to publish the repository.

Does your repository have any remotes defined? If you have Git available on the command line, you can run this command inside the repository: `git remote -vv`

If you don't have Git available, you can look at the `.git/config` file inside the repository for entries like this:

```
[remote "origin"]
        url = https://github.com/desktop/desktop
        fetch = +refs/heads/*:refs/remotes/origin/*
```

Let me know what you have, maybe our remote detection has missed something.

**Comment by RubenK01** [comment]
Thanks for your answer.

I have the remote repository defined but, the problem i think is in the api desktop, when I do 'push', desktop GitHub does 'publish repository'. 
When I do 'push' in cmd "git push origin master" and GitHub does push all right.

**Comment by jalovatt** [comment]
I've just run into this issue as well. However, it's only affecting my project **wiki** - the project itself still lets me push just fine.

- The push/fetch/publish button shows "Push origin, last fetched a day ago"
- Clicking it, or selecting Push in the menu, brings up "Publish repository" instead.
- I've doublechecked the address for my repo in Repository Settings; nothing funny there.
- Attempting to pull the repository via the menu does... nothing at all.

.gif of the issue [here](https://www.dropbox.com/s/yd97o7jazs4q92j/desktop%20push%20publish.gif?dl=0).

Cheers.

**Comment by shiftkey** [comment]
@jalovatt yeah, let's focus on the wiki-specific issue over in #3839

**Comment by shiftkey** [comment]
I'm going to close this out due to inactivity.

@RubenK01 if you're able to answer the questions and follow the context in my previous reply I'm happy to revisit this issue.
