### ISSUE TITLE
Can't login into github account throught github-desktop in a gnome-free system

### ISSUE THREAD

**Issue by sl1pkn07** [desktop/desktop#4407]
## Description
can't login to my github account througth github-desktop in my linux gnome-free desktop due a failed about gnome-keyring requeriment

## Version
* GitHub Desktop: 176a5f1bdf874915e4db894b048f66ce32764adf

* Operating system: archlinux

## Steps to Reproduce
1. build and install electron 1.8.4 (official package in archlinux) from sources without gnome-keyring support 
(add 'use_gnome_keyring = false' 'use_gio = false' in chromiumcontent/args/{shared,static}_library.gn and add  'use_gnome_keyring=false use_gio=false' in 'bootstrap.py --gn-gen-args' command
2. build github-desktop with 'yarn install', 
remove the contents of desktop/node_modules/electron/dist/ and copy the content of the craftered electron builded before
run: 'yarn build:prod'
3. install github-desktop
4. launch github-desktop and try to login in the github account throught github-desktop

### Expected Behavior
login without problems

### Actual Behavior
failed due:
** Message: 23:09:47.093: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
error: [ui] Error adding account 'sl1pkn07'
Error: The name org.freedesktop.secrets was not provided by any .service files

## Additional Information
pkgbuild used for build electron and build github-desktop:

https://gist.github.com/sl1pkn07/e6a613916148a6df148efe5d9339bb5c

the rest of the files (patches) in here: https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/electron

**Comment by shiftkey** [comment]
@sl1pkn07 thanks for the report! 

This is being tracked over in https://github.com/shiftkey/desktop/issues/7 and is related to needing `gnome-keyring` support for one of Desktop's dependencies.

**Comment by StStephensChester** [comment]
I have the same issue.

**Comment by andrewsheridan** [comment]
Same issue here.
