### ISSUE TITLE
Ignored file is still shown in the change list

### ISSUE THREAD

**Issue by garylavayou** [desktop/desktop#4410]
## Description

Right click to ignore a file in the changes list, but no effect at all.
The `.gitignore` file has been modified.
Moreover, mutilple ignore operations to the same file will append duplicate entries in the `.gitignore` file.

## Version

* GitHub Desktop: 1.1.1

* Operating system: Windows 10 1803 17133.1

## Steps to Reproduce

1. `step 1`: right click on a file in the changes list;
2. `step 2`: choose to ignore the file; if the operation takes no effect, try multiple times;
3. `step 3`: open the `.gitignore` file, you can see multiple duplicate entries.

**Comment by shiftkey** [comment]
@garylavayou thanks for the report. This is already tracked in #2537 and has some more details about the underlying problem - please follow along with that issue.
