### ISSUE TITLE
the new dangerous 'Discard All Changes' option

### ISSUE THREAD

**Issue by aliakseiherman** [desktop/desktop#4423]
## Description

'Discard All Changes' option is **not safe** at the moment, because of the following:

1. It is very easy to click it instead of 'Discard Changes' (single file)

2. No confirmation dialog appears when we click 'Discard All Changes' (provided that we've chosen to avoid these confirmation dialogs)

## Version

* GitHub Desktop: version 1.1.1

* Operating system: Windows 10 64 bit

## Steps to Reproduce

1. when you have uncommitted changes - click on 'Changes' tab on the left
2. right click on any file
3. you can see the standard 'Discard Changes' option
4. you can also see the dangerous 'Discard All Changes' option which is located extremely close to the previous one.
5. discard single file by clicking 'Discard Changes' option
6. confirmation dialog appears - you can see 'Do Not Show This Message Again' checkbox
7. tick the checkbox and click on 'Discard Changes' button
8. try discarding all files by clicking 'Discard All Changes' option
9. result - you've lost all your changes (perhaps even the important ones) which could be easily avoided if confirmation dialog was **mandatory** when discarding all changes.

### Expected Behavior

Even if we've chosen to avoid confirmation dialog when **reverting single file** ('Discard Changes' option), the 'Discard All Changes' one **is supposed to cause the confirmation dialog to appear anyway**, because we risk losing all uncommitted  changes.

Secondly, the 'Discard All Changes' option should be located a few menu items away from the 'Discard Changes' one.

### Actual Behavior

If we've chosen to avoid the confirmation dialog, when reverting single file - the dialog also does not appear when reverting all changes, thus the new functionality **is kind of a trap** both for novice and experienced GitHub Desktop users.

## Additional Information

The 'Discard All Changes' option is **absolutely necessary**, so please do not remove it.

Thanks in advance!

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇

**Comment by iAmWillShepherd** [comment]
@desktop/design How do you all feel about forcing the confirmation dialog to appear, irrespective of the preference being set to not show them, when discarding **all** changes?

**Comment by niik** [comment]
> @desktop/design How do you all feel about forcing the confirmation dialog to appear, irrespective of the preference being set to not show them, when discarding all changes?

👍 💯

**Comment by ideaguy3d** [comment]
how to we undo this? I accidentally discarded all changed and need to undo that. 
Is there a way to undo (ctrl-z) ?

**Comment by j-f1** [comment]
@ideaguy3d The changed files should be in the Trash/Recycle Bin.
