### ISSUE TITLE
"Open in Sublime Text" menu option not working

### ISSUE THREAD

**Issue by mikez302** [desktop/desktop#4428]
I am using GitHub Desktop version 1.1.1 on macOS 10.13.4, running Sublime Text 3.0.

## Description

I have a repo, with some files that have been modified from the working copy. The "Changes" tab shows the modified files, as I would expect. But if I right click on one of the files and then click on "Open in Sublime Text", it doesn't work. A blank tab in Sublime Text shows up, and it has a funny filename. My repo is in a directory like `/Users/Elias/project` and the file is at a path like `/Users/Elias/project/components/whatever.jsx`. It seems like GitHub Desktop is trying to open a file at `//components/whatever.jsx`, like it is coming up with a relative path from the repo root, and turning it into a relative path from the file system root.

If I click "Open with Default Program", then it loads fine.

## Version

* GitHub Desktop: 1.1.1

* Operating system: macOS 10.13.4

## Additional Information

I am using Sublime Text 3.0.

### Logs

The log files didn't seem to have any hints related to this issue. I would attach them, but I'm not sure if my company's privacy policy would allow it.

**Comment by pacav69** [comment]
i tried it and the result is 
    
    //README.md

seems like it is not using the path of the file.

**Comment by j-f1** [comment]
This was fixed in https://github.com/desktop/desktop/pull/4381, which should be released in the next update.

**Comment by shiftkey** [comment]
> This was fixed in #4381, which should be released in the next update.

Yep, I'm aiming to publish a build to the beta channel in a day or so.
