### ISSUE TITLE
I need GitHub notifications management tool

### ISSUE THREAD

**Issue by natsumesou** [desktop/desktop#4434]
## Description

I can get repository events emails (or some integrations like slack).
But I receive so many(but necessary) notifications.
It's hard to read notifications.
And I always forget which issues(or pull requests) of repositories should I check.
So I need GitHub notification management tool in desktop app(or other solution).

Does anyone have same issue?

**Comment by shiftkey** [comment]
@natsumesou thanks for the feedback!

We don't have anything particular in Desktop about notifications today, but we're tracking a proposal about notifications in #2825 which has some initial thoughts - please add your thoughts to that issue.

**Comment by natsumesou** [comment]
@shiftkey thank you for your information.
I read desktop roadmap, but it's far from the solution of my problem.

I mean I need repositories task management tool(include notification).
I have many repositories to watch and resopnse in my business account.
So I need to know which issues or pull requests of repositories do I have to check.
But it's difficult to management by email or other notification.
It just notify, but I need management tool!

Please consider to solve this problem!
