### ISSUE TITLE
After Open in External, Title is "index.html"

### ISSUE THREAD

**Issue by MikeDombo** [desktop/desktop#4446]
## Description
After opening a file in an external program, the window title of GitHub Desktop is changed to "index.html". 

## Version
* GitHub Desktop: 1.1.1
* Operating system: Microsoft Windows [Version 10.0.17643.1000]

## Steps to Reproduce
1. Look at repository history
2. Find a binary file that was changed and click "Open file in external program."

### Expected Behavior
File opens in an external viewer.

### Actual Behavior
File opens in an external viewer such as Adobe Acrobat and the title of the GitHub Desktop window changes to "index.html".

## Additional Information
![image](https://user-images.githubusercontent.com/3926405/38784584-fd1e3c50-40e1-11e8-9435-c46792c8e1fd.png)

### Logs
[2018-04-15.desktop.production.log](https://github.com/desktop/desktop/files/1913498/2018-04-15.desktop.production.log)

**Comment by shiftkey** [comment]
@MikeDombo what extension was the file you were trying to open?

**Comment by MikeDombo** [comment]
I opened a PDF file and it opened in Acrobat DC.
