### ISSUE TITLE
Authentication failed to clone private repository

### ISSUE THREAD

**Issue by monroews** [desktop/desktop#4451]
## Authentication failed

I'm cloning my private repository using github desktop. I select "clone or download" and "open desktop" at github.com. Github desktop opens and appears to begin the download and then a dialog box opens
Authentication failed
We were unable to authenticate with github.com. Please enter your username and password to try again. 

I enter my username and password and the same dialog box repeatedly appears.

## Version

* GitHub Desktop: Version 1.1.1

* Operating system:
Windows 10

## Steps to Reproduce

I'm cloning my private repository using github desktop. 
1. I select "clone or download" and "open desktop" at github.com. Github desktop opens and appears to begin the download and then a dialog box opens
Authentication failed
We were unable to authenticate with github.com. Please enter your username and password to try again. 
2. I enter my username and password and the same dialog box repeatedly appears.
### Expected Behavior

I expected the repo to be cloned to my computer
### Actual Behavior

No clone!

### Logs

[2018-04-16.desktop.production.log](https://github.com/desktop/desktop/files/1915723/2018-04-16.desktop.production.log)

**Comment by iAmWillShepherd** [comment]
> remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/monroews/CEE4530TA.git/'

This line seems to suggest the username and password are incorrect. If you are using a personal access token, maybe it expired? Try singing out out GitHub Desktop and signing in again.

**Comment by monroews** [comment]
I signed out of github desktop and signed in again and it solved the problem.

Thank you!

**Comment by aakashsinghbais** [comment]
It probably happens due to a password change, not sure. happened to me too. Sign out --> Sign-in helped.
