### ISSUE TITLE
Default clone path option and import of existing repos

### ISSUE THREAD

**Issue by tonysamperi** [desktop/desktop#4452]
## Description

I couldn't find an option to set default checkout path and to scan for existing local repos

## Version

* GitHub Desktop: **v 1.1.1**

* Operating system:
Windows 10 1709

## Steps to Reproduce

1. Open Github Desktop
2. Click **File** > Options
3. Check all the tabs in the options window.

### Expected Behavior

Like the faithful 3.3.4, I'd expect to see the **Clone path** option
and the **Scan for repositories** function
### Actual Behavior

None of the above

### Logs

![github](https://user-images.githubusercontent.com/5957244/38816345-2c4bd35c-4196-11e8-9b5f-a07994587b14.PNG)

**Comment by iAmWillShepherd** [comment]
For the new version of desktop, we do not provide a way to explicitly set a default clone path; however, we remember the last location you cloned to. This way, there is no need to set a default clone path. We also do not provide a way to scan your computer for repositories. Instead, you can select each of your repos and drag-and-drop your them into GitHub Desktop.

**Comment by tonysamperi** [comment]
ooops. Didn't know that!
Closing immediately :D
