### ISSUE TITLE
[Feature request] How about providing "Rebase and Push"?

### ISSUE THREAD

**Issue by drakeet** [desktop/desktop#4456]
Thank you very much for sharing this application. It's great. 

I am using version 1.1.1. If the GitHub Desktop can provide _**Rebase and Push**_ action in the future, that would be more great. It can be like the IntelliJ Idea's Git plugin:

![image](https://user-images.githubusercontent.com/5214214/38848297-faaf52e4-4238-11e8-8639-3fc7ccf1ea99.png)

Thanks!

**Comment by steveward** [comment]
Thanks for opening this @drakeet! 

This is similar to https://github.com/desktop/desktop/issues/1652 and https://github.com/desktop/desktop/issues/3422, so I am going close this issue out. Please subscribe to those issues for updates about rebasing in GitHub Desktop.

**Comment by billygriffin** [comment]
Removing the labels on this so we can streamline the tracking of rebasing in #3422.
