### ISSUE TITLE
"Discard Changes" doesn't work

### ISSUE THREAD

**Issue by Mlocik97-issues** [desktop/desktop#4461]
## Description

"Discard Changes" doesn't work (nothing happend)

## Version

* GitHub Desktop: 1.1.1

* Operating system: Windows 10

## Steps to Reproduce

Try Discard Changes by right click on file and select "Discard Changes"

### Expected Behavior

Discard Changes
### Actual Behavior

Nothing Happen

**Comment by shiftkey** [comment]
We're also tracking #4194 which might be related, but doesn't have a clear set of repro steps...

**Comment by steveward** [comment]
Based on the 👍 I'm going to assume that @Mlocik97-issues is running into the same issue as https://github.com/desktop/desktop/issues/4194, so I'm going to close this one out.

**Comment by HedvigS** [comment]
(I'm also having this issue, Github desktop: 2.5.3 Mac OS Catalina.)

**Comment by cmlibra71** [comment]
I'm having a problem when i try to discard all changes.  It essentially sits on the "Confirm discard all changes" dialogue prompt, never completing the "Discard all changes" operation.

**Comment by steveward** [comment]
@cmlibra71 thanks for the report -- would you mind opening up a new issue, filling out the template, and uploading your log file? That should give some more information for us to investigate.
