### ISSUE TITLE
Highlights are Case Sensitive

### ISSUE THREAD

**Issue by say25** [desktop/desktop#4462]
## Description
Code syntax highlights are Case Sensitive

## Version
* GitHub Desktop: 1.1.2-beta2
* Operating system: MacOS Sierra - 10.12.6 (16G1314)

## Steps to Reproduce
1. Make a .MD file
1. See that highlights are **not** there
1. Make a .md file
1. See that highlights are there

### Expected Behavior
1. Highlights work even when I case files differently.... I'm weird ok..... 

### Actual Behavior
1. Highlights disappear.

## Additional Information
Changing from a valid extension or to a valid extension makes the highlights show up...

<img width="962" alt="screen shot 2018-04-17 at 7 08 28 pm" src="https://user-images.githubusercontent.com/7467062/38904909-bc43bdbc-4272-11e8-821f-0e7f9507c257.png">

**Comment by steveward** [comment]
Thanks for opening this and submitting a pull request to fix it @say25! ✨
