### ISSUE TITLE
Upper case extension format is not recognized 

### ISSUE THREAD

**Issue by zhaobenx** [desktop/desktop#4466]
## Description

Desktop cannot recognize upper case extension on windows, that if one file's extension is ".JPG", it shows that it is a binary file, while if the extension is ".jpg", it will be shown as image.

![image](https://user-images.githubusercontent.com/23143530/38918247-b7f30206-431f-11e8-8828-c0cea652813b.png)
![image](https://user-images.githubusercontent.com/23143530/38918253-bc90d25c-431f-11e8-8539-f91021cb2aa8.png)
This two pictures are actually one same image while with different file name.

## Version

* GitHub Desktop:1.1.1

* Operating system: Microsoft Windows [Version 10.0.16299.371]

### Expected Behavior

File name ended with ".JPG" should also be recognized as image file.
### Actual Behavior

Detected as binary file.

**Comment by shiftkey** [comment]
@zhaobenx thanks for the report! This has been fixed in https://github.com/desktop/desktop/pull/4348 - relevant change [here](https://github.com/desktop/desktop/pull/4348#discussion_r178704098) and will be available in the next update.
