### ISSUE TITLE
Add syntax highlighting for JSP files

### ISSUE THREAD

**Issue by Kyhel** [desktop/desktop#4470]
## Description

The JSP (Java Server Pages) files are not highlighted in the diffs.
By reading the file https://github.com/desktop/desktop/blob/master/docs/technical/syntax-highlighting.md I've seen it's not in the supported language list, but since it says that if it's in the CodeMirror's supported language list (https://codemirror.net/mode/htmlembedded/index.html) I just need to open an issue to have it covered, there it is.

## Version

* GitHub Desktop: 1.1.2-beta3

* Operating system: Windows 7 Pro

## Steps to Reproduce

1. Commit a file ending with the JSP extension (.jsp)

### Expected Behavior

The file's syntax is highlighted.
### Actual Behavior

The file's synatx is not highlighted.

## Additional Information

I don't think any more information is needed since this is pretty straightforward, but just in case, here is a sample file from my project. (Which also shows here what kind of highlighting could be expected)

```jsp

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<%@ page language="java" contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="template" uri="http://www.jahia.org/tags/templateLib" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="jcr" uri="http://www.jahia.org/tags/jcr" %>
<%--@elvariable id="currentNode" type="org.jahia.services.content.JCRNodeWrapper"--%>
<%--@elvariable id="out" type="java.io.PrintWriter"--%>
<%--@elvariable id="script" type="org.jahia.services.render.scripting.Script"--%>
<%--@elvariable id="scriptInfo" type="java.lang.String"--%>
<%--@elvariable id="workspace" type="java.lang.String"--%>
<%--@elvariable id="renderContext" type="org.jahia.services.render.RenderContext"--%>
<%--@elvariable id="currentResource" type="org.jahia.services.render.Resource"--%>
<%--@elvariable id="url" type="org.jahia.services.render.URLGenerator"--%>


<html lang="fr">
  <head>
    
    <template:include view="hidden.head" />
    
  </head>
  
  <body>
    <div id="page-wrapper">
      
      <template:include view="hidden.header" />
      
      <div class="content" id="top">
      
        <template:area path="zone-profiling-guard" nodeTypes="awebnt:profilingGuard" listLimit="1" />

        <template:area path="document" moduleType="absoluteArea" level="1" nodeTypes="awebnt:listedocs" listLimit="1" limitedAbsoluteAreaEdit="false" />
        
        <div class="wrapper sm border-bottom t16">
          <template:area path="pagecontent"/>
        </div>
      </div>
    
      <template:include view="hidden.footer" />

    </div>

    <script src="${url.context}${url.currentModule}/javascript/jquery/jquery.follow-me.js"></script>
    <script type="text/javascript" src="${url.context}${url.currentModule}/javascript/app.js"></script>
    
  </body>
</html>
```

**Comment by Kyhel** [comment]
Is the way to add the highlighting for this language as simple as for this PR https://github.com/desktop/desktop/pull/4445 ?
If so, I may be able to do it myself. 
Also, if it's that simple, maybe I could consider adding other languages that are present in CodeMirror but not here, should I make a different PR for each, or could I do several of them in the same PR ?

**Comment by steveward** [comment]
Thanks for opening this @Kyhel! It looks like you've already had a look through our documentation about adding a language for syntax highlighting. If you are interested you could make the change and submit a pull request to add support for JSP files. Here is a [similar pull request](https://github.com/desktop/desktop/pull/3420) that added support for .hpp files.
