### ISSUE TITLE
github desktop not obeying gitignore_global

### ISSUE THREAD

**Issue by thehesiod** [desktop/desktop#4476]
## Description
Both GitHub Desktop and GitHub Desktop Beta are not obeying the exclusions from .gitignore_global

## Version
* GitHub Desktop: 223
* GitHub Desktop Beta: 1.1.1
* Operating system: OSX 10.13.4

## Steps to Reproduce
If you create this file and associate it via `git config --global core.excludesfile ~/.gitignore_global`, then add exclusions, and check to see if exclusions are obeyed, they are not.

### Expected Behavior
Exclusions from global file should be obeyed

### Actual Behavior
They are not

## Additional Information
I made sure both my system git and git in the Application resource were configured.

**Comment by shiftkey** [comment]
@thehesiod thanks for the report. I think there's enough in here to see if we can reproduce the behaviour on our end.

**Comment by thehesiod** [comment]
in my case I had `virtualenv/bin/` in my global, and all those files were listed in the UI, if I added it the `.gitignore` in the parent folder they were removed

**Comment by shiftkey** [comment]
@thehesiod I've not been able to reproduce this in a test harness in macOS:

```
    it('respects core.excludesfile entries', async () => {
      // create a temporary global ignore file on disk to hide .txt files
      const rootDirectory = setupEmptyDirectory()
      const excludesFilePath = path.join(rootDirectory, '.gitignore_global')
      fs.writeFileSync(excludesFilePath, '*.txt')

      // create a new repository with a number of untracked files
      const repo = await setupEmptyRepository()
      const firstTextFile = path.join(repo.path, 'first.txt')
      const secondTextFile = path.join(repo.path, 'second.txt')
      const firstMarkdownFile = path.join(repo.path, 'first.md')
      const secondMarkdownFile = path.join(repo.path, 'second.md')
      fs.ensureFileSync(firstTextFile)
      fs.ensureFileSync(secondTextFile)
      fs.ensureFileSync(firstMarkdownFile)
      fs.ensureFileSync(secondMarkdownFile)

      // set the excludes file to the .gitignore_global file
      await GitProcess.exec(
        ['config', 'core.excludesfile', excludesFilePath],
        repo.path
      )

      // confirm only .md files are listed
      const status = await getStatus(repo)
      const files = status.workingDirectory.files
      expect(files.length).to.equal(2)
      expect(files.every(v => v.path.endsWith('.md'))).is.true
    })
```

Are you able to provide more detailed steps to reproducing your issue?

**Comment by thehesiod** [comment]
looks like it needs to be at least one directory down, here's how I just reproduced:

`~/.gitignore_global`
```
virtualenv/bin/
virtualenv/lib/
virtualenv/include/
```

then
```
cd ~/
amohr@amohr-macpro:~$ mkdir -p deleteme/foo/virtualenv/bin
amohr@amohr-macpro:~$ cd deleteme
amohr@amohr-macpro:~/deleteme$ git init .
amohr@amohr-macpro:~/deleteme$ touch foo/virtualenv/bin/foo.bar
amohr@amohr-macpro:~/deleteme$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	foo/

nothing added to commit but untracked files present (use "git add" to track)
```

when I now load this into github desktop it incorrectly lists foo.bar as a change, whereas other tools will not list this file"

**Comment by shiftkey** [comment]
> when I now load this into github desktop it incorrectly lists foo.bar as a change, whereas other tools will not list this file"

I'm curious about which other tools are behaving as you expect, because I can reproduce this with Git 2.17.0 (Desktop is on 2.16.something, so it's not far behind). There's a command `git check-ignore` that lets you troubleshoot whether paths are ignored in a repository, and I don't see `foo/` being excluded. Here's my tweak repro of yours:

```shellsession
$ git --version
git version 2.17.0
$ cd ~src/test/
$ mkdir -p deleteme/foo/virtualenv/bin
$ cd deleteme
$ git init .
Initialized empty Git repository in /Users/shiftkey/src/test/deleteme/.git/

$ touch foo/virtualenv/bin/foo.bar

$ echo "virtualenv/bin/" >> ../.gitignore_global
$ cat ~/src/test/.gitignore_global
virtualenv/bin/
$ git config core.excludesfile ~/src/test/.gitignore_global
$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	foo/

nothing added to commit but untracked files present (use "git add" to track)
$ git check-ignore --verbose foo/virtualenv/bin/foo.bar
$ git check-ignore --verbose virtualenv/bin/foo.bar
/Users/shiftkey/src/test/.gitignore_global:1:virtualenv/bin/	virtualenv/bin/foo.bar
```

Note that the rule only lights up when the path _starts_ with a matching rule - this isn't caught when it's at an arbitrary location within the repository. I generally avoid using `core.excludesfile`, so I'm a bit hazy on what's going on in here.

**Comment by thehesiod** [comment]
> the rule only lights up when the path starts with a matching rule

ahh, that explains it, totally my fault then, sorry for the waste of time.  I think I was confused because pycharm lists it separately in untracked files so I was ignoring them.

yay, this helps me alot as those folders for me had tons of files :)

**Comment by OiYouYeahYou** [comment]
```
# General
.DS_Store
.AppleDouble
.LSOverride

# Icon must end with two \r
Icon


# Thumbnails
._*

# Files that might appear in the root of a volume
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent

# Directories potentially created on remote AFP share
.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk

# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# nyc test coverage
.nyc_output

# Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript v1 declaration files
typings/

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env

# next.js build output
.next

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless

graph.svg
```

**Comment by shiftkey** [comment]
@OiYouYeahYou oh, and one more thing to clarify with the repro - where is your `core.excludesfile` set?

```
$ git config -l --show-origin | grep "core.excludesfile"
```

**Comment by OiYouYeahYou** [comment]
file:/usr/local/git/etc/gitconfig	core.excludesfile=~/.gitignore

**Comment by shiftkey** [comment]
Aha, so this is the issue:

 - `/usr/local/git/etc/gitconfig` is the system configuration for your Git command line installation (mine is at `/usr/local/etc/gitconfig`, to show this can change between installations)
 - System configs should only contain things tied that the Git installation needs (because you can actually compile Git in a lot of different ways)
 - the embedded Git that ships in Desktop has it's own system config (but we only need to ship any changes for Windows currently)

To get Desktop to use this config value, move it into your global config at `~/.gitconfig` as global configs are respected by all Git installations and will override whatever is set in it's system config

**Comment by OiYouYeahYou** [comment]
Aha, I was wondering what the difference between system and global was. And because of the difference, I doubt there is a solution nor any point in documenting this edge case.

Thank you, for helping

**Comment by aheckler** [comment]
I am seeing this same issue. My global gitignore is at `~/.gitignore_global` and it includes this file here:

https://github.com/github/gitignore/blob/master/Global/macOS.gitignore

So git should be ignoring all `.DS_Store` files, but GitHub Desktop shows them:

![Markup on 2020-11-24 at 16:35:59](https://user-images.githubusercontent.com/5512652/100154157-27df6280-2e73-11eb-8c08-85504fdeac2b.png)

```
~ % git config -l --show-origin | grep "core.excludesfile"
file:/Users/Adam/.gitconfig	core.excludesfile=/Users/Adam/.gitignore_global
```

Not sure what's going on here...

**Comment by gaviral** [comment]
I am facing the same issue. I have `.DS_Store` in my .gitignore, but it still appears in the change list.

**Comment by steveward** [comment]
@gaviral if the `.DS_Store` file has been previously committed to your repository you will need to run `git rm --cached .DS_Store` to ignore it properly.
