### ISSUE TITLE
There is no Dark theme in latest version for Windows

### ISSUE THREAD

**Issue by bmaximus** [desktop/desktop#4480]
## Version

* GitHub Desktop:  1.1.1

* Operating system: Windows 10 Pro

## Steps to Reproduce

There is no Dark Theme and this is very important since all dev apps include this feature. 
This would save lifes.

**Comment by j-f1** [comment]
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #1515. Please follow that issue for further updates.
