### ISSUE TITLE
Allow commit by hitting enter key in summary field

### ISSUE THREAD

**Issue by omzy83** [desktop/desktop#4481]
## Description

In the older version of Github Desktop, you could hit the enter key in the "summary" field and it would perform the commit. In the latest version, this behaviour is no longer present. You have to either manually click the commit button, or tab to it and press enter.

It would be great if we could commit by hitting enter in the summary field.

## Version

* GitHub Desktop: 1.1.1

* Operating system: Windows 10 Pro

**Comment by steveward** [comment]
Thanks for opening this @omzy83. The shortcut to perform a commit is `Control-Enter` (Windows) or `Command-Enter` (macOS). Hope that helps!

**Comment by shiftkey** [comment]
Also, this was an inconsistency between the classic apps (the macOS version used Command-Enter to submit but the Windows version did not use Control-Enter).

We've talked about this in an earlier issue: https://github.com/desktop/desktop/issues/1594.

**Comment by omzy83** [comment]
Fair enough. However if you think about how forms work on webapps, pressing enter in an input field will normally submit the form.

Could we at least have an option?

**Comment by steveward** [comment]
Thanks for the feedback @omzy83. I've added the `enhancement` label, and have copied your reply into the issue that @shiftkey linked to group it with the other feedback we've heard about this.
