### ISSUE TITLE
Better experience around protected branches and pr permissions

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#4482]
We should provide a friendlier experience when collaborating with others on a single repository

![2018-04-19_23-42-51 994](https://user-images.githubusercontent.com/1715082/39059547-76bbff02-4484-11e8-947f-c95d928c06e4.png)

The reason why this failed is in the error message, but it's not presented in a user friendly way. In the case of :point_up:, the publish button should have been disabled. We can get these permissions from the [repositories endpoint](https://developer.github.com/v3/repos/#response), so it should be possible to prevent this state from occuring. 

**tl;dr**
1. Desktop should preempt this
1. It's possible to push to a protected branch
1. Scary error messages

Interestingly, this repo requires signed commits and I did not sign the commits made by my evil-handle, yet that was not the reason why the push failed. **Shouldn't unsigned commits take precedence?**

## Reproduction steps
_Assume steps not listed explicitly are things **not** to do (where it makes sense :man_shrugging:)_

### Main handle - performed on dotcom
* Create a repo
* Protect `master`
  * Require pr reviews
  * Require signed commits
* Add a @iamnotwillshepherd as collaborator

### Evil handle - performed in desktop
* Re-sign in as @iamnotwillshepherd
  * Update git information from `iAmWillShepherd` and `iamwillshepherd@github.com` :arrow_right:: `iAmNotWillShepherd` and `iAmNotWillShepherd@github.com` (remember to change back)
  
_Noticed that git information didn't automatically update as I was documenting :point_up: (is this a bug?)_

* Clone the repo
* Make some commits to `master`
* Push

## Separate maintainers problem
This is a related issue

Maintainers should be able to push to their contributors' PRs since we can get this info from the `maintainer_can_modify` property returned from the [pull requests endpoint](https://developer.github.com/v3/pulls/#response-1). If we store this data, desktop could allow this.

**Comment by shiftkey** [comment]
> Maintainers should be able to push to their contributors' PRs since we can get this info from the `maintainer_can_modify` property returned from the pull requests endpoint. If we store this data, desktop could allow this.

I think Desktop also needs to track the `permissions` hash for [the repository](https://developer.github.com/v3/repos/#list-your-repositories) from the API along with this field. From [the docs](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/), it's constrained to everyone with `push` permissions:

> For greater collaboration, you can allow commits on branches you've created from forks. **Permission to commit to your forked branches is limited to those with push access to the upstream repository of the fork.**

**Comment by niik** [comment]
This has largely been covered by https://github.com/desktop/desktop/pull/8889 and https://github.com/desktop/desktop/pull/7826. Going to consider it closed
