### ISSUE TITLE
Need to do search in the diff-ed change files

### ISSUE THREAD

**Issue by ivolazy** [desktop/desktop#4484]
## Description

When reviewing changes before checking them in, I'd like to be able to search into the diff-ed file for specific term in the code

## Version

* GitHub Desktop:

* Operating system: MacOS

## Steps to Reproduce

1. `step 1` - Open a repo that has changes
2. `step 2` - Click on Changes to see the changed files and click on one of the changed files
3. `step 3` - This is where I'd like to be able to do a search in the right panel for a term so that I can decide whether to include or not in the current commit.

### Expected Behavior

I'd like to be able to do a search in the right panel for a term so that I can decide whether to include or not in the current commit.

### Actual Behavior

No search capability

**Comment by shiftkey** [comment]
This feels very similar to #2306 but as yours is more detailed I'm going to refer to this issue instead.

**Comment by shiftkey** [comment]
This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by pforhan** [comment]
I'm sad that this and related issues are all closed.  One of the last things I like to do is check that I'm not merging a TODO I meant to do, for example.

**Comment by billygriffin** [comment]
We have this now as an open issue in #7538, so I'm going to remove `future proposal` here. We're discussing the priority of this now, but no promises on when it will land. Thanks for the idea!
