### ISSUE TITLE
PowerShell modules aren't loading when launched from GitHub Desktop

### ISSUE THREAD

**Issue by xt0rted** [desktop/desktop#4485]
## Description
When opening PowerShell from GitHub Desktop my installed modules (only posh-git at the moment) no longer load, but they do load when opening PowerShell directly.

## Version
* GitHub Desktop: 1.1.2-beta3
* Operating system: Win10
* PowerShell: 5.1.16299.251
* posh-git: 0.7.1 & 0.7.3

## Steps to Reproduce
1. Install posh-git via `PowerShellGet\Install-Module posh-git -Scope CurrentUser`
2. Open PowerShell manually - should load without any errors
3. Open PowerShell via <kbd>ctrl</kbd>+<kbd>`</kbd> - should load with an error

### Expected Behavior
PowerShell modules to load as they normally did.

### Actual Behavior
PowerShell loads, but with the following error
```ps
Import-Module : The specified module 'posh-git' was not loaded because no valid module file was found in any module
directory.
At C:\Users\brian\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:2 char:1
+ Import-Module posh-git
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (posh-git:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

## Additional Information
This started happening after the `1.1.2-beta3` update earlier today. Nothing else on my machine has changed or been updated.

**Comment by shiftkey** [comment]
@xt0rted thanks for the report. I'm not aware of any changes with the PowerShell support in the latest beta, and the previous beta update shipped PowerShell Core support for Windows but I think that's an additive change.

**Comment by xt0rted** [comment]
@shiftkey is there a way to switch between the stable and beta releases? Or a way to install them side by side?

**Comment by shiftkey** [comment]
@xt0rted not currently

**Comment by xt0rted** [comment]
@shiftkey turns out I had a pending reboot from my preview install of VS 2017 updating, once rebooted this issue went away. I guess that's what I get for not rebooting right after an update. Sorry for the bogus error report.
