### ISSUE TITLE
Advance Merging Pulling Pushing 

### ISSUE THREAD

**Issue by mohammadayoub96** [desktop/desktop#4496]
## Description
Advance Merging Pulling Pushing as we do not need to purchase an external unofficial app for github desktop
 also create issues from desktop app, merge issues close issue.

## Version
1.11
* GitHub Desktop:
Yes
* Operating system:
Win 10 Pro 64bit

**Comment by shiftkey** [comment]
> Advance Merging Pulling Pushing as we do not need to purchase an external unofficial app for github desktop

Please have a look at our **Compare to Branch** experience, which is under review in https://github.com/desktop/desktop/pull/4182 and slated to go out with the next update.

> also create issues from desktop app, merge issues close issue.

Please add your feedback to the existing issue discussing this area: #2378
