### ISSUE TITLE
 authentication failures with the desktop app 

### ISSUE THREAD

**Issue by alex-miro** [desktop/desktop#4497]
## Description

New user of the Desktop app
Using Desktop app (both Mac and Windows) to clone existing **private** repos.  Some of the repos are cloned just fine, others clone all the contents but at the very end reports an authentication failure.
The repo on disk locally is fine and complete I can add it as a local repo to the app and it works fine including pushing commits etc.
There is no issue with credentials obviously, I have been using them with the `git` command and all the repos are private, open only to collaborators even for read access. 
The problem exists for all authorized collaborators including the repo owner (myself). 

After some brief investigation I found out that the problem shows up ONLY with repos which have `deploy keys` installed (used by a jenkins integration server). 

It does smell like a bug.

**Comment by vanfumin08** [comment]
Master

**Comment by shiftkey** [comment]
> Some of the repos are cloned just fine, others clone all the contents but at the very end reports an authentication failure.
> The repo on disk locally is fine and complete I can add it as a local repo to the app and it works fine including pushing commits etc.

It's not clear to me what these authentication errors are, especially if you can also push commits. [Logs here would be great to assist with troubleshooting](https://github.com/desktop/desktop/blob/master/docs/installation.md#log-files).

> There is no issue with credentials obviously, I have been using them with the `git` command and all the repos are private, open only to collaborators even for read access.

Desktop doesn't share the authorization token with the command line Git you have installed. These are the scopes we request when you sign into the app:

https://github.com/desktop/desktop/blob/75f66b782d7142fe5e289034426b046d6ae9a359/app/src/lib/api.ts#L28

This should cover private repositories too.

> After some brief investigation I found out that the problem shows up ONLY with repos which have `deploy keys` installed (used by a jenkins integration server).

Are you referring to [Deploy Keys](https://developer.github.com/v3/guides/managing-deploy-keys/) from the GitHub API? I'm not sure how this would affect that, but more details would be great to understand how you came to this conclusion.

**Comment by shiftkey** [comment]
> Some of the repos are cloned just fine, others clone all the contents but at the very end reports an authentication failure.

Closing this out because details to help troubleshoot the issue about why the clone fails - log files are ideal - are necessary. @alex-miro if you're able to find those logs we're happy to revisit this issue.
