### ISSUE TITLE
Report issue ... Link at step 1 is broken

### ISSUE THREAD

**Issue by ewerybody** [desktop/desktop#4499]
## Description
So in Github Desktop, when I want to file a bug I end up on the github website in `.../issues/new`. I read the description there and try to open the link provided at step 1.: its broken :/

## Steps to Reproduce
1. goto the new issue form by:
  * click on the <kbd>Report issue ...</kbd> action in Github Desktops Help menu or
  * on the project page in [issues](https://github.com/desktop/desktop/issues) I click <kbd>New Issue</kbd> or
  * just browse to the new issue page directly: https://github.com/desktop/desktop/issues/new
2. start reading the instructions
3. on step 1 try opening the provided link: https://github.com/desktop/desktop/blob/master/CONTRIBUTING.md#contributing-to-github-desktop

### Expected Behavior
Its opening up the **Contributing to GitHub Desktop**-help page. Probably [this one](https://github.com/desktop/desktop/blob/master/.github/CONTRIBUTING.md#contributing-to-github-desktop).

### Actual Behavior
404

**Comment by shiftkey** [comment]
@ewerybody thanks for the report. Looks like this was just missed as part of tidying up in #4089 - over time we've centralised the docs that back GitHub-specific features into the `.github` folder.

**Comment by shiftkey** [comment]
Fixed in #4500
