### ISSUE TITLE
Grouping repositories

### ISSUE THREAD

**Issue by Pekshev** [desktop/desktop#4505]
I tried a lot of clients, but still no one could guess the ability to group repositories in the client window. I mean a conditional grouping that does not affect the repository itself, but only conveniently displayed all of my local repositories. Can you decide to do this?

**Comment by shiftkey** [comment]
@Pekshev thanks for the suggestion!

We have a few existing issues about different grouping proposals - please add your feedback to any that grab your interest: #1533 #1598 #2037
