### ISSUE TITLE
Trying to made first open source contribution

### ISSUE THREAD

**Issue by juliehudspeth** [desktop/desktop#4518]
## Description
  I forked repository, created new branch, made commit, but when I try to publish branch - it says "bad credentials"....?

## Version

* GitHub Desktop:  Version 1.1.1

* Operating system:

### Expected Behavior
  create push request, trying to add my name to contributors

### Actual Behavior
 says bad credentials

**Comment by shiftkey** [comment]
@juliehudspeth thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

I'd like to confirm that you've signed into your GitHub account, and that we're providing a token when you publish the branch.

**Comment by iAmWillShepherd** [comment]
@juliehudspeth, glad you figured out the issue. I'm going to close this out now.
