### ISSUE TITLE
Add MacVim as a supported external editor for macOS

### ISSUE THREAD

**Issue by johnelliott** [desktop/desktop#4530]
## Description
I want to be able to select the system default editor, or specify any program to open a file. Why limit the user to three choices?!

## Version

* GitHub Desktop: 
1.1.1 downloaded from web

macOS sierra
* Operating system:

## Steps to Reproduce

Go here: 
![image](https://user-images.githubusercontent.com/5633265/39269510-0581bedc-48a1-11e8-9c2d-f6772b651c63.png)

### Expected Behavior
User is presented a sheet to choose a program.

### Actual Behavior
Only three options.

**Comment by agisilaos** [comment]
Hello @johnelliott johnelliott, for now, Github Desktop for Mac support 7 editors.

What's the editor that you use and it's not currently supported? There is a [doc](https://github.com/desktop/desktop/blob/master/docs/technical/editor-integration.md) that explains how an external contributor can add support for an editor, so feel free to make a contribution if you want to.

The core team can help you with your PR, so feel free to ask any questions.

**Comment by iAmWillShepherd** [comment]
Closing this issue since Desktop supports more than 3 editors. If you would like support to be added for another editor, please read the [editor integration](https://github.com/desktop/desktop/blob/master/docs/technical/editor-integration.md) doc as @agisilaos mentioned and open a new issue for the editor you'd like support for. From there, we will leave it to you or another member of the community to implement it.

**Comment by johnelliott** [comment]
OK, thanks for pointing me to this doc @iAmWillShepherd. I was just reading through the code otherwise :)

@agisilaos I want add MacVim. I've got a way of using Atom more or less as a github/tree browser by using a plugin for opening things in macvim.

MacVim may be problematic because of point three here: https://github.com/desktop/desktop/blob/master/docs/technical/editor-integration.md#my-favourite-editor-xyz-isnt-supported, but I wonder if the common `gvim` command or the macOS `open` command can help out there.

Contributing to this part of the code doesn't seem to bad so I may give it a shot. I've never worked with a TS project before.

**Comment by iAmWillShepherd** [comment]
> Contributing to this part of the code doesn't seem to bad so I may give it a shot. I've never worked with a TS project before.

@johnelliott that's great to hear. Could you update this issue to reflect the editor you want? I'm going to reopen this issue and tag it as help-wanted and put it in our community project. 👍

**Comment by johnelliott** [comment]
Thanks all, I have started the PR here: https://github.com/desktop/desktop/pull/4532

**Comment by omnipitous** [comment]
I can create a new issue but this seems like a cross-platform request so pinging here first: I have the exact same issue only for the Windows platform. Unlike Mac tho we have exactly one available editor option and that is Atom. Nothing else seems to be identified or supported. Similar to OP I would like to use Vim (GVim in the Windows world) but allowing any editor shouldn't require so much editor-specific code.. this should be generifiable to any available editor without having to add each one specifically.

**Comment by agisilaos** [comment]
> I have the exact same issue only for the Windows platform. Unlike Mac tho, we have exactly one available editor option and that is Atom. 

Hello @omnipitous, on Windows, 4 editors are currently supported: 

- Atom
- Visual Studio Code - both stable and Insiders channel
- Sublime Text
- ColdFusion Builder

> Similar to OP I would like to use Vim (GVim in the Windows world) but allowing any editor shouldn't require so much editor-specific code.

Currently, the way that we support new editors is presented on this [doc](https://github.com/desktop/desktop/blob/master/docs/technical/editor-integration.md), For the reason why maybe @iAmWillShepherd can chime in and explain it a bit more.

**Comment by shiftkey** [comment]
> Similar to OP I would like to use Vim (GVim in the Windows world) but allowing any editor shouldn't require so much editor-specific code.

The big reason why I still continue to nudge people to help contribute the work to add support for their editor is that, once we figure out the right code to use, it's available to everyone.

I'm also happy to help with reviewing and pointers about how things work - this approach has been a great timesaver personally!

**Comment by johnelliott** [comment]
Oops, I must have accidentally clicked as I was reading.
