### ISSUE TITLE
unable to spawn Git due to "resource temporarily unavailable" error

### ISSUE THREAD

**Issue by huashengwang1989** [desktop/desktop#4535]
## Description

When launching GitHub Desktop on Mac, it keeps prompt the following error message:

> Cannot read property 'on' of undefined

Once the popup is closed, this message appears almost immediately again and again. Switching among the repos (including both public and private ones) within the short blink of time does not help. After a few "undefined" popups, an error message shows:

> Error: spawn /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git EAGAIN
>     at exports._errnoException (util.js:1024:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
>     at onErrorNT (internal/child_process.js:374:16)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)

2nd time error message (see Steps to Reproduce):

> Error: Failed to call git rev-parse --git-dir --show-toplevel: ""
> Error reading git config: fork/exec /Applications/GitHub Desktop.app/Contents/Resources/app/git/libexec/git-core/git: resource temporarily unavailable
> Error getting git version: fork/exec /Applications/GitHub Desktop.app/Contents/Resources/app/git/libexec/git-core/git: resource temporarily unavailable

After quitting GitHub Desktop (Including force quit from Mac's Activity Monitor), GitHub Desktop is launched with no window. Selecting any menu item that supposes to popup some window such as "Preference", "About GitHub" etc. will end up in a blank window.

## Version
* GitHub Desktop: Version: 1.1.1

* Operating system:
OS: Mac OS 10.13.4

## Steps to Reproduce
I am unable to find out the exact steps needed to reproduce this problem as it is like that once is launched; however, the problem is somehow automatically resolved and everything works normally. I triggered this problem again without knowing why and resulted in the 2nd error message above. And it repeated for the 3rd time, and I still cannot figure out how to reproduce this...

### Expected Behavior
Launch the app properly.

### Actual Behavior
Fail to launch the app with a proper window and without constant error message.

## Additional Information
NIL

### Logs
[2018-04-26.desktop.production.log](https://github.com/desktop/desktop/files/1951033/2018-04-26.desktop.production.log)

For every failed launch, this is the Mac console output:

> 19:55:58.055561 +0800	GitHub Desktop	LSExceptions shared instance invalidated for timeout.
> 19:56:41.626364 +0800	launchservicesd	CHECKIN:0x0-0x1aedaec 74001 com.github.GitHubClient
> 19:56:41.719571 +0800	GitHub Desktop	        AEGetDescData of non-desc type 'reco' not a good idea
> 19:56:41.730092 +0800	GitHub Desktop	*** WARNING: Textured window <AtomNSWindow: 0x7fdc15c2c670> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇

**Comment by shiftkey** [comment]
@huashengwang1989 thanks for the report. This looks like Git is unable to spawn because of a resource constraint enforced by the OS:

```
Error getting git version: fork/exec /Applications/GitHub Desktop.app/Contents/Resources/app/git/libexec/git-core/git: resource temporarily unavailable
```

If you open a shell and run `ulimit`, what does it return? On my machine it returns this:

```
$ ulimit
unlimited
```

**Comment by huashengwang1989** [comment]
I'm sorry for the late reply. Currently it is working (which I have no idea why it suddenly works and suddenly not working), and `$ ulimit` returns `unlimited`. I will take note of this and will try again if is not working another time...

**Comment by shiftkey** [comment]
@huashengwang1989 I'm going to close this out, but feel free to comment in here if you encounter it again and we can try troubleshooting again.

**Comment by finssao** [comment]
hello I meet errors while wanting to add a package on my Github repo can you help me please? thank you : serveur-finssao:repo cyrillefiliatre$ ./packit.sh
./packit.sh: fork: Resource temporarily unavailable
serveur-finssao:repo cyrillefiliatre$ ./push.sh
./push.sh: fork: Resource temporarily unavailable
serveur-finssao:repo cyrillefiliatre$
