### ISSUE TITLE
Please please please, move "Discard All Changes" or add a confirmation

### ISSUE THREAD

**Issue by jacwright** [desktop/desktop#4537]
I have lost so much work because I want to discard the changes to a single file and end up discarding ALL the changes. The two items are right next to each other in the right click menu. This makes sense from a functionality perspective, but one mis-click and everything is gone with no way to undo or recover.

Could we separate these two menu options, or put a confirmation dialog on the one asking "Are you sure you want to discard ALL changes?" Having the "Discard All Changes..." doesn't really make sense on the context menu for a single file anyway. It should be in a context menu when right-clicking on the Changes tab at the top.

Please save me from myself! Thank you!

![screen shot 2018-04-26 at 10 01 11 am](https://user-images.githubusercontent.com/120294/39317593-366d49ce-4939-11e8-80c9-4ddc782fa971.png)

**Comment by j-f1** [comment]
We have a PR over in #4426 that always displays the confirmation dialog before discarding everything. It should go out in the next update.

**Comment by jacwright** [comment]
I found in the Advanced settings this checkbox which I had unchecked so I could more quickly discard changes for single files. I had forgotten about it. I am checking it again until that ☝️ PR goes out. Thank you! ❤️ 

![screen shot 2018-04-26 at 10 13 24 am](https://user-images.githubusercontent.com/120294/39318148-963059ae-493a-11e8-88f1-e568d5c95a30.png)

**Comment by iAmWillShepherd** [comment]
I'm re-opening this because there is still an outstanding PR that fixes this issue.

**Comment by Muchiachio** [comment]
I think discard all changes should only be available at the top and not on the single file.

**Comment by j-f1** [comment]
@Muchiachio We decided to add it to each file item because lots of people were having trouble finding the menu item.

**Comment by niik** [comment]
> I'm re-opening this because there is still an outstanding PR that fixes this issue.

@iAmWillShepherd I'm assuming the PR you were referring to was https://github.com/desktop/desktop/pull/4459? I can't see any currently open PRs targeting this feature so I'm going to close this out. Please reopen if I'm mistaken.
