### ISSUE TITLE
Double clicking a file to open in default editor

### ISSUE THREAD

**Issue by HeroProtagonist** [desktop/desktop#4539]
## Description

The previous version of github desktop allowed for double clicking a file in the sidebar and then it would open in the default editor. The new one lacks this feature. I added this to my fork https://github.com/HeroProtagonist/desktop/tree/feature/open-files-sidebar. I have tested and it works on Mac Sierra and Windows 10. If this feature would be wanted in the project I would be happy to open a pull request. 

## Version

* GitHub Desktop: 1.1.1 (But all since the logo changed)

* Operating system: All

### Expected Behavior

Double click file name, open it in default editor

### Actual Behavior

Nothing

## Additional Information

I did not see this mentioned in other issues. Apologies if it has been addressed elsewhere.

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇

**Comment by HeroProtagonist** [comment]
@iAmWillShepherd I opened a PR from my branch

**Comment by niik** [comment]
Hey @HeroProtagonist. I'm closing this in favor of #2620, let's continue the discussion over there!

**Comment by 1083** [comment]
@niik That issue was closed. It looks like there is clearly demand for fixing this bug.
