### ISSUE TITLE
Consider reducing the minimum window size constraints

### ISSUE THREAD

**Issue by samkusnetz** [desktop/desktop#4547]
## Description

When using GitHub Desktop on a laptop, the minimum window size is rather large; about 60% of both the width and height of my MacBook Pro 15" screen. Since I often use GitHub Desktop without needing to read all that much (only need to see the last few items of history, etc.) it would be great to be able to shrink the window down smaller to, say, 25%.

## Version

* GitHub Desktop: 1.1.1

* Operating system: macOS 10.12.6

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue. 🙇 

The minimum size is the smallest size our window can be while retaining the correct layout for the UI. Given this constraint, we are unlikely to reduce the minimum size of the window.
