### ISSUE TITLE
Purpose of the debug script and differences with the start script

### ISSUE THREAD

**Issue by streeter** [desktop/desktop#4548]
## Description
I was trying to run the local, debug version of GitHub Desktop, and found the `yarn debug` command. At first it doesn't work, and I noticed that it needs a bit of fixing (which has been done in https://github.com/desktop/desktop/pull/3675/files#diff-165034287d03bd2dd5ecb9b849bcad3d). However, I'm not sure what it does. If I want to run the Desktop locally, can I do that with other commands? Can I do `yarn build:dev && yarn start`? What does `yarn debug` do that the other ones don't?

## Version
* GitHub Desktop: `master`
* Operating system: `Mac OS 10.13.4`

## Steps to Reproduce

1. `yarn install`
2. `yarn debug` (which fails)
3. `yarn build:dev`
4. `yarn start`

### Expected Behavior
Not sure. I don't know what `script/debug` does that the `script/start` script does not.

### Actual Behavior
Again, the `yarn debug` issue in the script seems to be have fixed in an upcoming PR. But I'm afraid that using `yarn start` does not give the dev middleware, or the hot middleware.

**Comment by iAmWillShepherd** [comment]
We have a [guide](https://github.com/desktop/desktop/blob/master/docs/contributing/setup.md) on building Desktop. Please check there for details. 

I'm going to close this issue since there doesn't seem to be a problem with the application.

**Comment by streeter** [comment]
Ok, thanks @iAmWillShepherd. I'd seen that doc, but it doesn't mention the `debug` script. So I wasn't sure if that script was even needed, or if it provided additional debug functionality. I noticed an issue on the doc, so I'll make a PR for that.

**Comment by iAmWillShepherd** [comment]
@streeter, we've also updated the docs to remove the `yarn debug` stuff that was giving you problems. Thanks for opening this issue and submitting your PR.

**Comment by streeter** [comment]
Awesome! Thanks!
