### ISSUE TITLE
Github Noob - Need help!

### ISSUE THREAD

**Issue by Fiddy187** [desktop/desktop#4557]
Hi all,

Trying my best to figure out how to get this working and I'm at a complete lose!!
I've tried my to follow the steps, but as someone who is very new to Github, I just can't get it working. 
Is there a video or something I could follow along with?
Many Thanks,
Stuart

**Comment by niik** [comment]
Hey @Fiddy187, if you're talking about GitHub Desktop specifically please have a look at our user guides over at https://help.github.com/desktop/guides/

For more general information about Git and GitHub we have a ton of resources at https://guides.github.com and https://help.github.com. 

I hope that'll help get you started!
