### ISSUE TITLE
Show message when no branches to compare

### ISSUE THREAD

**Issue by meaghanlewis** [desktop/desktop#4559]
## Description
A suggestion for an enhancement. When there are no branches other than master and going to compare and select a branch from the list the pane shows "Sorry, I can't find that branch" when really there are just no other branches to select.

## Version
* GitHub Desktop: 1.1.2-beta4
* Operating system: Mac and Windows

## Steps to Reproduce
1. Use a repository that only has master branch
2. Go to `Compare` tab
3. Click in `Select branch to compare...`

### Expected Behavior
See a message like "There are no branches to compare"

### Actual Behavior
The current message says: "Sorry, I can't find that branch"

![no other branches exist](https://user-images.githubusercontent.com/10103121/39440068-99209170-4c5e-11e8-987a-fdceb5b5b317.png)

**Comment by shiftkey** [comment]
Nice spot @meaghanlewis. Tentatively putting this into 1.2.0 but I'll let @desktop/core add their feels about whether this is a ship-blocker.

**Comment by iAmWillShepherd** [comment]
This has the potential to be a quick fix, but I wonder if we should even show the text box if the repo doesn't have more than one branch. Thoughts?

**Comment by donokuda** [comment]
> This has the potential to be a quick fix, but I wonder if we should even show the text box if the repo doesn't have more than one branch. Thoughts?

I'm 👍for not showing the text box, except that hiding it would make the title of the tab ("Compare") confusing...

This might be too much, but would it make sense to hide the text box and change "Compare" to "History" if there aren't any branches to compare it to?

We could also consider disabling the text box, but then it's not necessarily clear as to why it would be disabled in the first place.
