### ISSUE TITLE
Allow Branches button to take up full middle of toolbar because get truncated pretty early

### ISSUE THREAD

**Issue by jglovier** [desktop/desktop#4569]
## Description

The team I working with has a convention of using branch names that follow this format: `[gh-username]/[project-name]/[feature-or-fix-title]`, which can make for pretty long branch names. 

This is especially convenient when scanning a list of branches for your current feature branch, such as in this branches tab of the GitHub.com repository with a search param for our team or project name.

The Desktop experience of working with these longer branches is a little less helpful, however – . specifically when glancing to see which branch I'm currently on, something I do frequently when I have several different feature branches in progress:

![image](https://user-images.githubusercontent.com/1319791/39463344-7575bd54-4ce5-11e8-81d0-d89b6295d0c7.png)

The truncation kicks in pretty early, so given our convention, I typically don't even get to see my feature name part of the branch.

### Suggestion: a floated Fetch origin button

The solution I'd like to propose is a floated (visual description, not technical implementation advice :wink:) `Fetch origin` button that allows for the branch button (and menu dropdown) to occupy the entire full width of the toolbar. E.g.:

![image](https://user-images.githubusercontent.com/1319791/39463368-95f92eb2-4ce5-11e8-96a9-94063676ab62.png)

This would:
- allow the full branch name to be displayed for most branches, even longer ones
- put the Fetch button (which I would assume is the button most frequently clicked in the navbar) in a very familiar primary call to action location
- open up some extra breathing room in the dropdown to display full branch names there too

There may be some glaring downsides that I'm not considering, too. What might those be?

Not sure how many developers or teams of developers on GH follow a similar pattern of branch naming that produces relatively longer names. Do we have any existing data around average branch name length that might help inform us here?

cc @donokuda @nerdneha 

## Version

* GitHub Desktop: Version 1.1.1
* Operating system: MacOS 10.13.4

## Steps to Reproduce
1. Create a branch with a very long name, for example `myusername/myproject/my-new-feature-1`
2. Observe that truncation in the branch button cuts off the branch name after a relatively few amount of characters.

### Expected Behavior

I would expect to be able to see the entire branch name.

### Actual Behavior

I cannot see the full branch name.

## Additional Information

Not applicable.

### Logs

Not applicable.

**Comment by iAmWillShepherd** [comment]
> Do we have any existing data around average branch name length that might help inform us here?

We don't collect this information in Desktop, but I believe dotcom has this info.

**Comment by dbchristopher** [comment]
Just wanted to add my support for this feature enhancement. I have to switch to command line every time I want to double check what branch I'm currently on, which is really annoying. Seems like an easy fix to remove a common pain point

**Comment by tierninho** [comment]
@dbchristopher I agree that surfacing the entire branch name would be useful, however you can always just hover over the branch to see the entire name in the tooltip. 

<img width="472" alt="screen shot 2018-10-04 at 10 07 39 am" src="https://user-images.githubusercontent.com/14828183/46490738-a40f1b80-c7bd-11e8-9f1c-db5f6a2fbe8f.png">

**Comment by dbchristopher** [comment]
Cool, thanks @tierninho! That's helpful. I guess now that I think about it the bigger annoyance is actually having to select a branch from the dropdown which is also far too narrow to show the complete branch name. I hope that will also be expanded to match the wider button

**Comment by tierninho** [comment]
Glad it helps! Same workaround for the branch list, just hover:

<img width="400" alt="screen shot 2018-10-04 at 11 06 28 am" src="https://user-images.githubusercontent.com/14828183/46493588-9eb5cf00-c7c5-11e8-8afd-d93286c3d7bc.png">

**Comment by cocco3** [comment]
This is still a poor user experience to have to hover over everything in a list to find what you're looking for instead of just being able to quickly scan it.

**Comment by j-f1** [comment]
I think the dropdowns should be allowed to expand as much as is needed, like regular menus do on macOS.

**Comment by tierninho** [comment]
Although this comment applies to a neighboring button, it is inline with the original request, i.e. expand the buttons to expose relevant content.

We are showing an "unknown" metric on the push/pull/fetch button when uploading large files:

<img width="248" alt="screen shot 2018-10-29 at 12 07 01 pm" src="https://user-images.githubusercontent.com/14828183/47674250-1af8c380-db74-11e8-8083-71482d0ad088.png">

I suppose it's a timer, but expanding the button would give the user the relevant information.

**Comment by dbchristopher** [comment]
@billygriffin it's a bit of an improvement, but still seems like there's no reason to limit the size of the dropdown header or content. 

I've never coded an electron app so I'm not sure if there are some extra limitations on css rendering. But would it be very much more difficult to just have that branch dropdown button and menu content expand to fill the available window space? Or if it needs to be static, at least bump the width up another 50% from where it's set now?

**Comment by dbchristopher** [comment]
Just to be clear -- this is what I mean by "button":

<img width="1065" alt="pasted_image_11_19_18__5_20_pm" src="https://user-images.githubusercontent.com/238293/48745206-62c4b500-ec1f-11e8-9c5f-06f3bce5a43b.png">

It would be nice if that button had a fluid width. 

And this is what I mean by "menu content" 

<img width="1161" alt="pasted_image_11_19_18__5_21_pm" src="https://user-images.githubusercontent.com/238293/48745257-8f78cc80-ec1f-11e8-9e97-81dc3e5479d6.png">

It would be nice if that also expanded a bit more, or had some fluid layout settings as well

**Comment by cocco3** [comment]
Most of my branch names are still truncated, so I didn't even notice the menu was widened in the latest release :)

So is there a specific reason to not allow the button and menu taking up available space?

The code below worked great for me. I also resized the app and everything looked ok. (The commented out properties are things that would have to be removed.)

```css
#desktop-app-toolbar .toolbar-dropdown.branch-button {
    /* width: 230px; */
    flex: 1;
}

.branches-container {
    /* width: 350px; */
}

.branches-container .branches-list {
    /* width: 350px; */
}
```

<img width="1393" alt="screen shot 2018-11-19 at 5 47 13 pm" src="https://user-images.githubusercontent.com/1775017/48746272-a02b4180-ec23-11e8-8847-bbcf8ee8f34f.png">

**Comment by dbchristopher** [comment]
@cocco3 💯

**Comment by cocco3** [comment]
Been nearly a year since the ticket was first opened. Has sufficient data been collected yet? Is there any concern with allowing the button to take up available space? I'd be happy to submit a PR to get this conversation back up.

**Comment by billygriffin** [comment]
Hi @cocco3, thanks for the friendly nudge. To be honest, while I totally agree that this can be improved, we haven’t heard it enough to prioritize work around it yet. We are discussing it internally and what pitfalls may exist, and I appreciate you following up on it as it helps keep it top of mind with hundreds of things we (or the community) could work on at any point in time. I’ll make sure we get somewhere on how we’d like to go forward here, but there are several other things we’re working on at the moment that we’ve received orders of magnitude more user feedback about, so I can’t promise a timeline. Thanks again!

**Comment by martinzugec-ctx** [comment]
+1 for this issue. I am dealing with many new contributors to GitHub (people that are not familiar with versioning systems) and we are using automatic branch names that are longer than usual. 

This has been extremely confusing to most contributors and I keep hearing this complain almost on a daily basis.

**Comment by fabtjar** [comment]
> We are discussing it internally and what pitfalls may exist

@billygriffin What pitfalls could exist with making the dropdown wider? There's a lot space not being used already isn't there?

**Comment by SebastienPoncelet** [comment]
+1 for this issue. I can understand that this is not a priority for the team right now, however even a dirty quick fix like this one makes it much more comfortable to use. Same goes to see the branches names list.

Hope something will be done about it, even if quick fix would make the experience way nicer and user friendly.

<img width="1165" alt="Screenshot 2021-06-29 at 3 32 08 PM" src="https://user-images.githubusercontent.com/40748222/123756383-72d0c500-d8ef-11eb-817e-295b4f0bce87.png">

**Comment by cschreib** [comment]
I would like to add that the situation is made much worse when the branch has a PR against it, as the PR number is now taking almost half of this already small space:
![Screenshot from 2021-09-03 13-18-06](https://user-images.githubusercontent.com/2236577/132003943-e65c70ac-77b5-4a65-adea-dcd8576c8dfd.png)

In the example above, I'm getting 3 useful characters (we use the [author]-[branch-name] convention at work). 

What about making it user-adjustable, like the left panel with the list of files/commits?

**Comment by Jeffrey-R** [comment]
> Most of my branch names are still truncated, so I didn't even notice the menu was widened in the latest release :)
> 
> So is there a specific reason to not allow the button and menu taking up available space?
> 
> The code below worked great for me. I also resized the app and everything looked ok. (The commented out properties are things that would have to be removed.)
> 
> ```css
> #desktop-app-toolbar .toolbar-dropdown.branch-button {
>     /* width: 230px; */
>     flex: 1;
> }
> 
> .branches-container {
>     /* width: 350px; */
> }
> 
> .branches-container .branches-list {
>     /* width: 350px; */
> }
> ```
Using View > Toggle Developer Tools I was able to find the file: `/Applications/GitHub Desktop.app/Contents/Resources/app/renderer.css` where these changes are made. Thanks @cocco3 for the great tip!

**Comment by steveward** [comment]
Requested in https://github.com/desktop/desktop/issues/16099.

**Comment by jgallantgs** [comment]
> > Most of my branch names are still truncated, so I didn't even notice the menu was widened in the latest release :)
> > So is there a specific reason to not allow the button and menu taking up available space?
> > The code below worked great for me. I also resized the app and everything looked ok. (The commented out properties are things that would have to be removed.)
> > ```css
> > #desktop-app-toolbar .toolbar-dropdown.branch-button {
> >     /* width: 230px; */
> >     flex: 1;
> > }
> > 
> > .branches-container {
> >     /* width: 350px; */
> > }
> > 
> > .branches-container .branches-list {
> >     /* width: 350px; */
> > }
> > ```
> 
> Using View > Toggle Developer Tools I was able to find the file: `/Applications/GitHub Desktop.app/Contents/Resources/app/renderer.css` where these changes are made. Thanks @cocco3 for the great tip!

Hi I just wanted to +1 this feature and post this for anyone else, as I too use large branch names. I've found this works for me as of today, the 350px is just too small. Thank you @cocco3 and @Jeffrey-R  🥇 Legends!
```
#desktop-app-toolbar .toolbar-button.branch-toolbar-button {
  min-width: 450px;
}

.branches-container {
  min-width: 450px;
}

.branches-container .branches-list {
  width: 100%;
}
```

**Comment by Jay-o-Way** [comment]
LOL almost 5 years later...

**Comment by frankhli843** [comment]
Hi I wanted to chime in here as well. This CSS change would be much appreciated.

**Comment by ihasdapie** [comment]
+1 to be able to widen the branch name selector to fit long branch names on github web and github desktop.  This is particularly aggravating when using github on any sufficently large team with branching conventions. In particular the web interface doesn't even support having a tooltip that displays the full branch name and the user has to rely on the browser's link preview.

**Comment by jpedroso** [comment]
This branch in my fork [makes the branch dropdown button resizable](https://github.com/desktop/desktop/compare/development...jpedroso:github-desktop:resizable-branch-dropdown-button?expand=1), in the same way the sidebar is. The branches list also reflects the size of the resizable button and extends to fill its width when opened.

Here’s a demo showing how it behaves with the minimum window size and different zoom values:

https://github.com/desktop/desktop/assets/3560/e978d120-ad57-4f59-b17a-890750dec598

As for implementation details, the branch toolbar dropdown is wrapped in a `Resizable` with a maximum width of `600`. Default size remains `230` and it conforms to `IConstrainedValue`. Like other resizables, double-click resets to default width as seen in video.

@tidy-dev what do you think? This might not be too far from your [preferred solution](https://github.com/desktop/desktop/issues/17388#issuecomment-1723732170) in #17388. Let me know if you’d consider opening this issue to contribution.

**Comment by jpedroso** [comment]
I made a few tweaks in `updateResizableConstraints()` such that [the max width of the branch dropdown button is the available space in the toolbar](https://github.com/desktop/desktop/compare/development...jpedroso:github-desktop:resizable-branch-dropdown-button?expand=1#diff-b238c18a99c08ab800e422715cc02105067f5f1394027f489e52d7fb15d6ca74R2252-R2260) after taking the sidebar width and the push/fetch button fixed width (`230`). This prevents the resizable from squeezing the pull/fetch button like shown in previous post. 

https://github.com/desktop/desktop/assets/3560/d8f93788-daa4-415e-ae83-2660e7fdf000

**Comment by Jay-o-Way** [comment]
Question:
 why is the left-most ("repo") button width connected to the side-bar in the first place? This should be independent. The button is not a part of the sidebar.

**Comment by tidy-dev** [comment]
@jpedroso Thank you for doing this exploration. I responded to your request in https://github.com/desktop/desktop/issues/17388#issuecomment-1770801890 . 

@Jay-o-Way There has been some discussion about refactoring  to make it independent. [This comment ](https://github.com/desktop/desktop/issues/4195#issuecomment-374204924)has links where you can read up on that, but is not something we are looking to work on as part of the branches and pull/push/fetch toolbar button work.

**Comment by Jeffrey-R** [comment]
Thanks for doing this exploration! I would not limit the width of the
branch section whatsoever. Let the minimum sizes of the other elements
dictate what max size is possible. Very long branch names are easy to
encounter when you use a folder structure and make sure you are clear. As
long as the other elements are not squeezed I see no reason to not maximize
the branch name section. I do that for each new build like this:
[image: image.png]
It makes the Fetch/Push button stay in the same place which is a nice side
effect.

**Comment by chronvas** [comment]
> I made a few tweaks in `updateResizableConstraints()` such that [the max width of the branch dropdown button is the available space in the toolbar](https://github.com/desktop/desktop/compare/development...jpedroso:github-desktop:resizable-branch-dropdown-button?expand=1#diff-b238c18a99c08ab800e422715cc02105067f5f1394027f489e52d7fb15d6ca74R2252-R2260) after taking the sidebar width and the push/fetch button fixed width (`230`). This prevents the resizable from squeezing the pull/fetch button like shown in previous post.
> 2023-10-18-001844.mp4

This looks much better from the current implementation 👍  
Can I please ask why isn't this an open PR?

**Comment by Jay-o-Way** [comment]
Come on, after six years... 😮‍💨

**Comment by Jeffrey-R** [comment]
I make this change/workaround everytime there is a new release. I even have
shared it w/ all my coworkers so they can make it too XP

**Comment by jpedroso** [comment]
pr #18095 submitted for this

**Comment by steveward** [comment]
Requested in https://github.com/desktop/desktop/issues/19191.
