### ISSUE TITLE
Metrics tracking for pushes

### ISSUE THREAD

**Issue by telliott27** [desktop/desktop#4570]
We don't currently have metrics tracking for pushing to remotes within GitHub Desktop. It would be great to add this to our metrics.

**Comment by iAmWillShepherd** [comment]
Would this be to gain insight into how many people use the PR List feature? That's the only place I can see this making sense since Desktop doesn't really support pushing to arbitrary remotes.

**Comment by telliott27** [comment]
More for seeing how many Desktop users are pushing code to GitHub versus just using it to manage local repositories.

**Comment by telliott27** [comment]
Yep! that would be perfect

**Comment by iAmWillShepherd** [comment]
We may need a `numberOfPushesToGithub` measure as well to distinguish between pushing to repos hosted on other platforms.

**Comment by j-f1** [comment]
How about counting the number of commits pushed to avoid getting large numbers from people who push every commit individually and small numbers from people who push rarely?

**Comment by iAmWillShepherd** [comment]
We currently do that, but we only receive anonymized aggregate data. That means that even if we did what you suggested at the app level, we'd still only get the aggregated data.

**Comment by iAmWillShepherd** [comment]
@j-f1 , just in case you didn't know about this: https://desktop.github.com/samples/

**Comment by j-f1** [comment]
I see an entry for the number of commits created on that page, but not one for the number of commits pushed. Am I missing something?

**Comment by iAmWillShepherd** [comment]
No, you're right. We don't track the number of commits pushed. We haven't asked any questions that require that data. Even if we did, we'd only be able to get an average per installation (which means we'd need to calculate the standard deviation for it to be useful). I can't think of anything we'd gain at the moment by doing this. 

 @telliott27, thoughts?

**Comment by telliott27** [comment]
Yeah, I don't think we need average commits per push - I don't think that tells us enough to justify the additional logging.

**Comment by iAmWillShepherd** [comment]
@telliott27 I just want to confirm that we want to add the following measures:
* `numberOfPushesToGithub`
* `numberOfPushes`

Are there any other metrics related to pushing that you can think of? I plan to get this change in place tomorrow.

**Comment by shiftkey** [comment]
@iAmWillShepherd @telliott27 are we going to differentiate between GitHub The Website and GitHub Enterprise with the `numberOfPushesToGithub` metric?

**Comment by telliott27** [comment]
@shiftkey I think differentiating between Enterprise and Dotcom is a good idea. Can we add a third measure:

- `numberOfPushesToEnterprise`

Thanks for working on this @iAmWillShepherd! This will be awesome to add to our tracking.

**Comment by iAmWillShepherd** [comment]
@telliott27 @shiftkey , I agree that we should track pushes to enterprise as well, so I'm going to create the following measures:
* dotcomPushCount
* enterprisePushCount
* externalPushCount

Is  this sufficient?

**Comment by telliott27** [comment]
Just so I understand correctly: The sum of those would the total number of pushes the user did that day?

**Comment by iAmWillShepherd** [comment]
> Just so I understand correctly: The sum of those would the total number of pushes the user did that day?

Yes

**Comment by telliott27** [comment]
Just to follow up on this: I am interested in whether people are using Desktop to make commits to a repo but don't push those commits to a remote. In other words, how many people are using Desktop to only manage local repos?

**Comment by billygriffin** [comment]
Thanks @telliott27! A couple clarifying questions: Would we only have insight into GitHub remotes? For instance, would this make someone using Desktop with Bitbucket or Gitlab look like someone who was just using it locally, or are those distinguishable?

@niik had the question during our meeting today of why we care about this, and what hypothesis do we have that getting this information will help inform?
