### ISSUE TITLE
Option to only use absolute dates in history screen

### ISSUE THREAD

**Issue by dixonte** [desktop/desktop#4573]
## Description
Currently the History tab displays the commit timestamp in relative terms if the commit was recent enough. I would like an option to always display the absolute date (and possibly time).

## Version
* GitHub Desktop: 1.1.1
* Operating system: Windows 10

## Steps to Reproduce
1. Open a recently updated repository.
2. Go to the History tab.

### Expected Behavior
If the 'Use absolute dates' option is enabled: Commit is listed with description, contributor name, and date in locale-aware format (optionally also time).

### Actual Behavior
If the commit is within the last 7 days, the commit date is listed relative to the current date: e.g. '5 days ago', or '5 hours ago' if within the last 24 hours.

## Additional Information
N/A

### Logs
N/A

**Comment by shiftkey** [comment]
This came up earlier in #3999 and I'll defer to @niik's comment here about why we've chosen relative timestamps: https://github.com/desktop/desktop/issues/3999#issuecomment-366213166

> Commit is listed with description, contributor name, and date in **locale-aware format** (optionally also time).

There's a limitation about detecting the right locale from the user's OS that we currently cannot workaround https://github.com/desktop/desktop/pull/1257#issuecomment-296147325 and we're tracking some outstanding Chromium issues about this https://github.com/desktop/desktop/pull/1257#issuecomment-296200080.

If those get resolved, we can revisit this area of the UI.

**Comment by rasenplanscher** [comment]
I don't see how the locale issue prevents this feature request. Absolute dates are displayed anyway if the commit is old enough. All this Feature needs is a setting to always use that output. If it's sub-optimal, that's an issue that has to be addressed in any case.

That said, I would really love this option because I find anything beyond "today" and "yesterday" to be a hassle. Ok, it may look nice, but it's impractical. Additionally, the existing tooltip may be useful to know when a given commit was made, but finding a commit by date and time is still rather a chore.

Please re-open this.

**Comment by miriamoc99** [comment]
Please reopen this issue. Relative dates are very frustrating - I have to look at my calendar and count back to find the actual date that something happened.

**Comment by tierninho** [comment]
@miriamoc99 Apologies for the added frustration. You can hover over the relative date and it will show you the absolute date, like so:

![Screen Shot 2020-07-06 at 7 53 53 AM](https://user-images.githubusercontent.com/14828183/86623863-fc101e80-bf5d-11ea-9bf5-7511110333ad.png)

**Comment by miriamoc99** [comment]
Thanks  Tiernan - I wasn't aware of that feature.

**Comment by awulkan** [comment]
> @miriamoc99 Apologies for the added frustration. You can hover over the relative date and it will show you the absolute date, like so:
> 
> ![Screen Shot 2020-07-06 at 7 53 53 AM](https://user-images.githubusercontent.com/14828183/86623863-fc101e80-bf5d-11ea-9bf5-7511110333ad.png)

I don't think this is a good solution. It's both hidden from the user, and it doesn't work in mobile browsers. It's impossible to see when actions were done. Just saying "a month ago" is extremely unspecific for a technical website like this.

**Comment by timothy-humphrey** [comment]
It would be great to add a toggle to the user Settings -> Appearance panel, so the user could switch between their preference of relative or absolute dates.

**Comment by bmulling** [comment]
+1 to this issue. 

Auditors need to see specific dates, and this broken presentation functionality is forcing me to install risky Chrome plugins as a workaround. In MacOS the tooltip mentioned above disappears when you hit the screenshot key combination, so that doesn't work.

**Comment by MadsSaustrupFox** [comment]
+1 to this issue

Need this to create easy documentation of validated software. Else we need to use another system and have a parallel processed less attached to the source code

**Comment by jamesgeddes** [comment]
I have already +1ed but just want to emphasise how irritating relative dates are. I have to spend brain power working out when something occurred, rather than the system just telling me. Someone has had to put effort into creating the relative date functionality, so why not just let us use the normal datetime too?

**Comment by jamesgeddes** [comment]
As a workaround, the [Github Absolute Dates chrome extension](https://chrome.google.com/webstore/detail/github-absolute-dates/iepecohjelcmdnahbddleblfphbaheno/related?hl=en) does append the actual datetime to the relative one.

**Comment by maddes-b** [comment]
+1 for making this an option. "1h ago" is not precise (can be anything from 60 to 119 minutes ago), just give coders/admins all detail information so they can work without hassle. (UTC as default would be fine for those, and newbies can easily learn what's the delta to UTC via Wikipedia or [www.timeanddate.com](https://www.timeanddate.com/))

**Comment by matt-palermo-optum** [comment]
This is a MUCH needed option.  It even looks like that what's already there by default.  If the page loads slowly, you see actual dates until the page fully loads and switches to relative dates!

When someone says "There was a blip in production at 3:30 on March 3rd", it would take only seconds to find if ther was a build around that time.  The way it is now is hovering over 3 pages of "5 days ago" strings looking for dates/times...  That is just crazy.

**Comment by tim1mw** [comment]
Ditto. This option is essential. I can't understand why it wasn't done years ago, it's so obvious.

Also surely the locale issue which is the stated reason for not doing this would also affect the relative date once you start counting "days ago"? So I can only assume that is wrong. I'd rather have the date in UTC if all else fails and work out the time correction myself.

**Comment by jonasflynn** [comment]
WELL DISORGANIZATION IS A CURDE AND TIME IS NOTHING BUT ESSENCE.....VAPOR
BEING OUR MOST BASIC FORM HERE ON THIS PLANET.....MUCH LOVE MY BROTHER,
GIVE THE FAMILY LOVE FROM ME    <3 <3 3  8008135

**Comment by NickThorne123** [comment]
+1

**Comment by sterlingcrispin** [comment]
this is still an issue and seems like an easy fix plz @niik 
```
3 days ago
6 days ago
7 days ago
```
I just always want to see the date and maybe even the time

**Comment by maddes-b** [comment]
I installed [Tampermonkey](https://www.tampermonkey.net/) (a Greasemonkey alternative) on Firefox for UserScripts and then the UserScript [GitHub-static-time](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-static-time). That works well.
I am using the following format `Y-MM-DD HH:mm:ss z` (see [moment.js formats)](https://momentjs.com/docs/#/displaying/format/), [no UTC yet.](https://github.com/Mottie/GitHub-userscripts/issues/177) Thanks to [refined-github](https://github.com/refined-github/refined-github/issues/6143) for hinting me to this.

Still the option to show absolute dates should be a GitHub standard feature.

**Comment by ryancampfire** [comment]
Fun wrinkle is the hover for the real date stops working on some pages if the window is half-width.

But the time when I really wish this listed real dates is when I'm cross-referencing with something else, which is the same situation I'm going to put two half-width windows side-by-side.

**Comment by diligent176** [comment]
Relative dates are **awful**.  Please make this a setting I can change!
There are 0 use-cases where I want relative dates.  Only show real date & time - please!!

**Comment by gabor-akeero** [comment]
If it were just commit history, I wouldn't care, we still have command line, we still have `git log`.

But Actions' workflow run history also shows only "12 days ago", which is sort of annoying, when I'm looking for the logs of an Action execution whose timestamp I happen to know. And the hover trick doesn't work here either.

Couldn't we just have a checkbox for this, like at Profile / Appearance, right next to the "default emoji skin tone", the "tab size preference" and the "use / don't use monospace font in markdown editing" ?

**Comment by niik** [comment]
Hey folks, first of all this is it repository for GitHub Desktop, the official, open source, GitHub client and we don't control how GitHub.com chooses to format date and time. Several of the most recent comments seem to have us confused with GitHub the website. To provide feedback around GitHub.com behavior I would suggest visiting the [GitHub Community Discussions](https://github.com/orgs/community/discussions/).

Secondly, the best way to show your support for this feature is by adding a 👍 reaction to the top of this issue. "+1" and "me too"-type comments are not helpful and could lead to us having to restrict commenting on this issue.

**Comment by matt-palermo-optum** [comment]
I found _two_ open issues for absolute dates

Replace "Friendly Date" format in favor of Date/TimeStamp #16550
https://github.com/orgs/community/discussions/16550

Option to show absolute dates #5972
https://github.com/orgs/community/discussions/5972

I don't see any posts associating a PR with either, so it looks like the requests are being ignored(??)

**Comment by MichaelArnoldOwens** [comment]
would be cool to just do away with the `...days ago` altogether and use something like `Month Date, Year`

**Comment by sonnyleman-bib** [comment]
I have no idea who thought that showing date like 'a day ago' is more useful than absolute date.
If we have concern about locale format and timezone, we can enforce it to the GMT, and use YYYY-MM-DD HH:mm:ss format, which is more meaningful.

**Comment by RobertKrawitz** [comment]
> As a workaround, the [Github Absolute Dates chrome extension](https://chrome.google.com/webstore/detail/github-absolute-dates/iepecohjelcmdnahbddleblfphbaheno/related?hl=en) does append the actual datetime to the relative one.

That's not useful with other browsers.

**Comment by RobertKrawitz** [comment]
> I have no idea who thought that showing date like 'a day ago' is more useful than absolute date. If we have concern about locale format and timezone, we can enforce it to the GMT, and use YYYY-MM-DD HH:mm:ss format, which is more meaningful.

Yes.  That's unambiguous across timezones.

I may colloquially say "I commented on this last week", but for written communication, I need precision.

**Comment by the0ffh** [comment]
How about simply displaying `in the past` instead of `...ago`?
...in order to follow the 'something happened' fashion
![image](https://user-images.githubusercontent.com/26150100/221929136-e7cd01dc-2b1a-4eb0-9b77-b1b1dc345728.png)

**Comment by elenadimitrova** [comment]
+1 Adding my vote to reopen this. Thanks to @tierninho who showed us where to look, this could be as easy as replacing the annoying relatives with the date from the tooltip.

**Comment by timk2112** [comment]
This is really frustrating. "12 days ago" is a useless time indicator. Especially since there's a mouseover for the actual time. Just use the actual time! If you can't figure out the local time from the browser, just use GMT and label it as such. "May 12, 18:30 GMT." Why is this even a problem?

**Comment by massimilianokraus-kappas** [comment]
People have been asking this feature for 5 years now...
I see that GitHub Desktop is frequently released with updates, so why wasn't this fix included in any of the updates? Even if the absolute date is shown in the tooltip (so its calculation is not an issue)?
Is there a specific reason?
I can't think of a single developer that finds the relative date useful in any way.

**Comment by AndyE0** [comment]
This is ludicrous. I'm currently trying to track down an update that's causing performance issues that happened between the 14th and 15th Jan - "last month" is no damn use to anyone and hovering over the timestamp to get a tooltip showing what I need is not a solution. Now using Tortoise Git to actually show the info required.

**Comment by sterlingcrispin** [comment]
@shiftkey please consider re-opening this issue its a long standing user request and seems like it should be a relatively easy fix to implement, we are dying

**Comment by shiftkey** [comment]
@sterlingcrispin I am no longer an active contributor to GitHub Desktop

**Comment by sterlingcrispin** [comment]
@steveward  help we are dying

**Comment by RobertKrawitz** [comment]
> @miriamoc99 Apologies for the added frustration. You can hover over the relative date and it will show you the absolute date, like so:
> 
> ![Screen Shot 2020-07-06 at 7 53 53 AM](https://user-images.githubusercontent.com/14828183/86623863-fc101e80-bf5d-11ea-9bf5-7511110333ad.png)

Hover really isn't useful if you want to see the timestamps of a lot of files, and it's not useful on a mobile device.

If localization is a real problem I'd be fine with just displaying UTC, but if the hover is able to display relative dates, it's clearly possible.

Precision and accuracy are more important to me than "friendliness".

**Comment by rockingdice** [comment]
just come by and +1 for this issue, it's like this git client is not designed for engineers - it's for artists and designers who don't care much about preciseness but feelings/intuitions.
