### ISSUE TITLE
[enhancement] Support renaming repositories 

### ISSUE THREAD

**Issue by jerguslejko** [desktop/desktop#4576]
## Description
It'd be great, if there was a way to rename a repository.

Example:
I have a project that is split into two repos: `project/client` and `project/server`. The app shows `client` and `server` only.

I suppose, it could take `.git/description` file into the account. This file is used in `GitWeb` for example.

## Version

* GitHub Desktop: 1.1.1

* Operating system: macOS 10.13.4

**Comment by steveward** [comment]
Thanks for opening this @jerguslejko! I'm going to drop this feedback into https://github.com/desktop/desktop/issues/4576, where we are tracking feedback about repository renames/labels. You can follow along there for updates.

**Comment by billygriffin** [comment]
Since we're tracking this in the issue linked above, I'm going to remove the labels here.
