### ISSUE TITLE
Black screen if launched while charging laptop

### ISSUE THREAD

**Issue by itggot-emil-sonksen** [desktop/desktop#4577]
## Description

Window turns black if launched while laptop connected to charger. Launches like normal while not charging.

## Version

* GitHub Desktop: 1.1.1

* Operating system: Microsoft Windows [Version 10.0.16299.248]

## Steps to Reproduce

1. Plug in charger.
2. Launch application

### Expected Behavior

Normal window
### Actual Behavior

Black window

## Additional Information

[Video](https://youtu.be/AWm3puuZvnw)

### Logs

[2018-05-02.desktop.production.log](https://github.com/desktop/desktop/files/1967091/2018-05-02.desktop.production.log)

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

Does your laptop happen to have a discrete GPU in addition to an integrated one? If so, it's likely windows is switching to the discreet GPU when you plugin. 

Assuming your machine does have a discrete GPU, check out our [known-issues](https://github.com/desktop/desktop/blob/master/docs/known-issues.md#i-get-a-black-screen-when-launching-desktop) doc for a workaround.

**Comment by shiftkey** [comment]
Closing this out because we've had similar reports that seem to have been addressed by the workaround in the Known Issues doc linked in the previous comment.

**Comment by Asimov500** [comment]
Can I re-open this as the known issues link leads nowhere, and I am having the same problem on a lenovo laptop

**Comment by tierninho** [comment]
@Asimov500 Fixed the link. Please open a new issue if you are still having issues. Thanks!
