### ISSUE TITLE
Authentication Failed (with valid credentials, CLI is working fine)

### ISSUE THREAD

**Issue by manoadamro** [desktop/desktop#4578]
## Description
I can use the app for about a month or so, then suddenly (seemingly randomly) it will refuse to authenticate, even if i provide valid credentials.
I can still use git on the command line with no issues

Usually I solve this by deleting all of my ssh keys, both locally and on github, regenerating and re-adding them, this is a annoying but necessary. If there was a more 'proper' way of solving this, i would really like to hear it.

For now i can make do with the command line, but this was a really useful tool and would love to see it working again.

## Version
1.1.1

* GitHub Desktop:

* Operating system:
OSX 10.12.6

## Steps to Reproduce
Use github desktop for a few months

### Expected Behavior
make commits, push, pull etc, normal git stuff

### Actual Behavior
Log in box pops up and refuses to accept any credentials i give it

### Logs

```~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log```  does not exist
have done a full search for anything containing ```.desktop.production.log``` but no luck

**Comment by steveward** [comment]
Thanks for opening this @manoadamro. 

>Usually I solve this by deleting all of my ssh keys, both locally and on github, regenerating and re-adding them, this is a annoying but necessary. If there was a more 'proper' way of solving this, i would really like to hear it.

Are you using SSH with all of your repositories in GitHub Desktop? GitHub Desktop defaults to HTTPS, so any repositories that you cloned in-app should be using HTTPS remotes (hence why you are seeing the credential error popup).

> Log in box pops up and refuses to accept any credentials i give it

Can you try going into `Keychain Access.app` and deleting the `GitHub - https://api.github.com` entry located there? Then try logging in again to GitHub Desktop. That should hopefully fix this issue.

**Comment by manoadamro** [comment]
No luck unfortunately,
I have encountered this problem before, but not in the last few months. I was using it fine all morning then suddenly between 2 commits this started again. 
I'm not sure it would be a problem with remotes (unless the remotes changed themselves or i have somehow been bypassing the https for the last few months without realising)

Thank you for your response, but i will probably just make do with the command line until i have some more time to dedicate to this.

**Comment by omnipitous** [comment]
I'm having this same problem... *just started happening with the latest update (I'm now on "End of an Era (3.3.5.1) 1173c88" )  This has been working fine for me for years.. this update broke something.  Whenever I connect to the app or try to sync a repo it pops up the box and won't accept any flavor of my authentication (username/password, email/password, username/key, email/key). If I go into the settings and "logout" then re-login it only accepts my username/password OR email/password but Not username/key or email/key *and then it asks and accepts my 2-factor authentication.  This seems "successful" only in that it doesn't show me an error and shows my account details so clearly it connected BUT when it returns me to the repo view and I try to do anything I still get the broken auth popup so I'm not really "logged in" successfully. 

FYI at the command line I'm using Cygwin's git and have my credentials successfully stored in the "store".  Is there any way to "downgrade"  until this is fixed the app is completely useless to me.. the last version worked just fine.

**Comment by j-f1** [comment]
@omnipitous This repository is for issues with the redesigned app, not the old native ones.

**Comment by manoadamro** [comment]
@steveward It seems this issue goes beyond the desktop app. 
Pretty much as soon as I posted, the command line stopped working too. After deleting my ssh keys, all my repos from local, internet history and everything else i could think of, then re adding them, I can now use the desktop app but not the command line.
I am having to do this at least twice a day at the moment, so this may not be an issue for you guys after all. It seems like a deeper issue in GitHub.

**Comment by shiftkey** [comment]
> Pretty much as soon as I posted, the command line stopped working too. 

@manoadamro the next time you see this occur, could you try running `ssh -Tv git@github.com` to see _why_ it might be failing?

**Comment by guardrex** [comment]
Just wanted to add ... same here. I was using the old GH Desktop for several years without problem. It seems to have reached a point where it forced me to upgrade.

Current behavior is that GH Desktop (the app) authenticates and works as expected. The CLI tho doesn't ... It asks me for credentials in a pop-up panel first ... and then flips over to the command line asking for credentials. It won't authenticate. For something like a force push, I can't use the UI, so I'm pretty much broken at the moment.

![capture](https://user-images.githubusercontent.com/1622880/39786467-56813534-52e6-11e8-89ee-21323deefe54.PNG)

![capture1](https://user-images.githubusercontent.com/1622880/39786471-59ee79ca-52e6-11e8-83c4-b03cc2f7c1c1.PNG)

I've put in a support request with GH to see if they can help.

**Comment by guardrex** [comment]
I've chatted with GH Support. The problem in my case seems to be that with 2FA activated my GH password won't work in either in the login panel or in the CLI ... **a personal access token has to be created and used** ...

https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/

Further, the CLI won't remember the token session-to-session, so I need to follow the instructions to cache a token (which I haven't done yet, but will to later today) ...

https://help.github.com/articles/caching-your-github-password-in-git/

**NOTE TO OWNERS** Someone really dropped the ball here on surfacing migration info during the GH Desktop installation process. IIRC, I didn't need to go thru these steps with the prior GH Desktop, perhaps because I activated 2FA at some point later. However, these probs should've been foreseen, and you should've taken steps to surface these migration details **during the install process using screens that the installer shows**. Throwing auth error messages at the user when they're providing correct login credentials **is a horrible user experience**. It's a waste of my time and the time of the GH Support cats.

**Comment by manoadamro** [comment]
@guardrex 
That seems likely however it is a little worrying that it still works on and off. 
Seems like a pretty flakey feature to me

**Comment by shiftkey** [comment]
@guardrex sorry to hear you're having problems. The `HttpRequestException` error is coming from the [Git Credential Manager for Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows) - that slipped into the latest update but isn't meant to be used.

I pushed out a fix for this as soon as I heard about it last week. Can you confirm you're on `3.3.6.1` and that your `credential.helper` config value is accurate?

```
$ git config credential.helper
```

It should be `!github --credentials`, and not `manager`.

**Comment by guardrex** [comment]
GH Support had me follow the advice in https://help.github.com/articles/caching-your-github-password-in-git/ 

When I run the command you posted, it comes back ...

```
wincred
```

**Comment by shiftkey** [comment]
`wincred` doesn't support 2FA dialogs, which is why you have to fall back to using personal access tokens.

If you want to get back to using the Desktop credentials from the CLI, open this file `%LOCALAPPDATA%\GitHub\PortableGit_69bd5e6f85e4842f07db71c9618a621154c52254\mingw32\etc\gitconfig`, find this section and update it to look like this:

```
[credential]
	helper = !github --credentials
```

Then cleanup whatever is in your `~/.gitconfig` and launch a fresh shell to see if it's been fixed.

**Comment by guardrex** [comment]
@shiftkey Update made. I'll test it tomorrow.

Thanks for your help!

**Comment by shiftkey** [comment]
Closing this out due to inactivity and the recent discussion being about the classic Desktop apps.

If you're still encountering authentication issues with the Desktop Electron app, please open a fresh issue so we can investigate.

**Comment by vinaysk95** [comment]
Hi, I downloaded GitHub Desktop recently and I am facing this issue currently. GitHub Desktop version is 1.4.3.
Should I open new issue? or continue in this thread?

**Comment by tierninho** [comment]
@vinaysk95 Please open a new issue. Thanks!

**Comment by G14NC4RL0** [comment]
> I've chatted with GH Support. The problem in my case seems to be that with 2FA activated my GH password won't work in either in the login panel or in the CLI ... **a personal access token has to be created and used** ...
> 
> https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/
> 
> Further, the CLI won't remember the token session-to-session, so I need to follow the instructions to cache a token (which I haven't done yet, but will to later today) ...
> 
> https://help.github.com/articles/caching-your-github-password-in-git/
> 
> **NOTE TO OWNERS** Someone really dropped the ball here on surfacing migration info during the GH Desktop installation process. IIRC, I didn't need to go thru these steps with the prior GH Desktop, perhaps because I activated 2FA at some point later. However, these probs should've been foreseen, and you should've taken steps to surface these migration details **during the install process using screens that the installer shows**. Throwing auth error messages at the user when they're providing correct login credentials **is a horrible user experience**. It's a waste of my time and the time of the GH Support cats.

Thanks a lot @guardrex , this solved my issue.

**Comment by AkashicSeer** [comment]
Looks like this problem has returned is there any solution other than using Gitlab instead? I use valid credentials it fails.  I reset my gitlab password and it lets me push to my repo for 1 day, next day it fails to authenticate again so I have to repeat the process. It really sucks that in order to use my repo I have to google "reset github password" then click the link then login to gmail then follow the link to reset my password, just to be able to push my code to my PUBLIC repo. What am I missing here?

**Comment by AkashicSeer** [comment]
If the answer is the last response then I am done with github

**Comment by tierninho** [comment]
@AkashicSeer Please file a new issue so we may assist you individually. You might want to check your Desktop version, as we fixed a bug for cloning non-GitHub repos recently https://github.com/desktop/desktop/issues/9843 Thanks.
