### ISSUE TITLE
Switching branches does not update submodules

### ISSUE THREAD

**Issue by jessetan** [desktop/desktop#4579]
## Description
When switching between branches of a repo, submodules are not updated

## Version
* GitHub Desktop: 1.1.1
* Operating system: macOS 10.13.4

## Steps to Reproduce

1. In a repo called `repo`, with branches `foo` and `bar`, add a submodule `sub`, with branches `subfoo` and `subbar`.
2. In branch `bar` checkout `subbar` in the submodule and commit
3. In branch `foo` checkout `subfoo` in the submodule and commit
4. In GitHub Desktop, switch between the `foo` and `bar` branches

### Expected Behavior
GitHub Desktop runs `git submodule update` on every branch switch, so that branch `foo` always uses branch `subfoo` of the submodule and branch `bar` always uses branch `subbar` of the submodule.

### Actual Behavior
The submodule is not updated during branch switches. GitHub Desktop will mark the submodule as changed.

**Comment by shiftkey** [comment]
@jessetan thanks for the feedback.

For the moment, this is following what `git checkout` does when switching branches, but this is definitely an opportunity for Desktop to help with the friction of managing submodules.

**Comment by jessetan** [comment]
@shiftkey depending on the version of git used, this may actually be as simple as adding `--recurse-submodules` to git checkout (and pull and fetch), see https://www.mail-archive.com/git@vger.kernel.org/msg120829.html
Since submodules are already cloned during the initial clone, the process of fetching/pulling and checking out a submodule commit should be fast.

**Comment by MichaelVoelkel** [comment]
But... why is this not automatic?

Having a checkout without submodules being pointed to what the CHECKOUT says makes little sense, no?

At least I would have expected from "switch". Plus, why is there no shortcut version of --recurse-submodules? It's too long
