### ISSUE TITLE
Octicon color does not match when textbox is disabled

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#4580]
This issue was introduced as a result of PR #4563 and was pointed out by @j-f1.

> Also, can you make the area behind the Octicon gray instead of white?

![](https://user-images.githubusercontent.com/1715082/39452956-c8a00c4c-4c99-11e8-93a6-e1e3e8038888.png)

Notice that the Octicon background next to the textbox is white, but the background of the textbox is gray.

**Comment by shiftkey** [comment]
Fixed in #4583
