### ISSUE TITLE
Do not navigate to bottom of history list on press of up arrow key from top of history.

### ISSUE THREAD

**Issue by mikeperrotta** [desktop/desktop#4582]
## Description

Enhancement: when viewing a repository's history, do not jump to the last item when using the arrow keys to navigate upwards from the topmost item. This is particularly annoying because after jumping to the bottom of the history, the next section of history is loaded and navigating downwards using the arrow keys does not return you to the top. Since it is impossible to use the down key to move to the top (unless you are at the end of the history), using the up key should not move to the bottom of the currently loaded history (possibly it could move to the very very bottom of the history, but then you would either need to load all history or have a non-continuous list of past commits). 

## Version

* GitHub Desktop: 1.1.1

* Operating system: macOS 10.13.3

## Steps to Reproduce

In the history view, select the topmost item and press the up arrow key.

### Expected Behavior

Do not move.

### Actual Behavior

Moves to the bottom of the currently loaded history list, then loads more history items.

**Comment by shiftkey** [comment]
@mikeperrotta thanks for the report!

We've had a couple of these come through in the past (#2763, #2479 and #3093) and I think this is worth revisiting to see if we can control the `List` keyboard navigation to prevent it from looping like this. We had a shot at it in #2539 but couldn't get a satisfactory fix together.

I'm going to mark this as `enhancement` and see if I can write up some more details about what needs to change.

**Comment by mikeperrotta** [comment]
Thanks! Really did try to look for duplicates, but guess I wasn't searching for the right thing. Thanks for the comment though!

**Comment by billygriffin** [comment]
Closing in favor of #7679 because there's a bit more detail there.
