### ISSUE TITLE
New Look - Too Bright

### ISSUE THREAD

**Issue by Kherae** [desktop/desktop#4589]
So, new client is out, and I already have a major problem with it: the lack of a Dark Mode. Previous client was dark enough I could use it without straining my eyes. Now? Painful. Just like the website, which I've avoided using for the most part. I would greatly appreciate it if there were some form of dark theme to activate for the client. I expect others would as well.

**Comment by shiftkey** [comment]
@Kherae thanks for the feedback!

We're tracking this in https://github.com/desktop/desktop/issues/1515, so please follow along with that issue.
