### ISSUE TITLE
Staging not used

### ISSUE THREAD

**Issue by beruic** [desktop/desktop#4591]
## Description
This might be a linux issue, as I have only tried GD on Ubuntu.
I often use my graphical GIT client in conjunction with the command line client. Therefore I use the staging area between them, but it doesn't seem like GitHub Desktop uses the staging area.

## Version
* GitHub Desktop: GitHubDesktop-linux-amd64-1.1.1
* Operating system: Ubuntu 16.04

## Steps to Reproduce
1. Open GitHub Desktop
2. Make sure something is selected for commit
3. Check that it it staged with another git client (e.g. `git status` from command line)

### Expected Behavior
Changes selected in GitHub Desktop show up as selected for commit in alternative client.

### Actual Behavior
Selected changes in GitHub Desktop does not sync with staging.

### Logs
[2018-05-03.desktop.production.log](https://github.com/desktop/desktop/files/1971016/2018-05-03.desktop.production.log)

**Comment by JordanMussi** [comment]
It’s the same across all platforms by design, see the replies to #4475. 🙂

**Comment by shiftkey** [comment]
@beruic Yep, basically what @JordanMussi said. We want to ensure we interop nicely with other tools, but keeping the checkbox state in sync with the git index is really tricky in some areas like partial commits, which is an important part of Desktop.

**Comment by beruic** [comment]
I find that odd since SourceTree and GitKraken both do this. I'd suspect they parse the output of `git diff --cached` and emulate `git add -p`.

Will you at least make Desktop remember the state when it is shut down, so you can shut it down and continue working on a commit after opening it up again?
