### ISSUE TITLE
Upgraded to new desktop app, now required to add all my repos from scratch

### ISSUE THREAD

**Issue by ishepherd** [desktop/desktop#4600]
## Description

The desktop app installer should look for a previous version and migrate in the repos required. I have +30 now to add manually.

## Version

* GitHub Desktop: 1.1.1

* Operating system: Windows 7 (Microsoft Windows Version 6.1.7601)

## Steps to Reproduce

1. Install Github Desktop 3.3.6
2. Add a bunch of repos
3. Install Github Desktop 1.1.1

**Comment by j-f1** [comment]
You should be able to drag and drop them onto the app’s window to add them.

**Comment by steveward** [comment]
Thanks for opening this @ishepherd. You can find the original discussion about importing repositories from the classic version of GitHub Desktop in https://github.com/desktop/desktop/issues/186. As @j-f1 mentioned, the quickest way to add multiple repositories is to bulk select them and then drag-and-drop.
