### ISSUE TITLE
Authentication fails while trying to push the changes of repository to GitHub.com

### ISSUE THREAD

**Issue by stavrossk** [desktop/desktop#4607]
When I have more than 25 changed files in my local repository to upload to GitHub.com, and I try to push them, I get an "Authentication Failed" error. The exact error is:

"Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository."

In the Github Desktop app I have to logout from Github and re-login in order for the push to work.

**Comment by Dinhvamtramg** [comment]
: 1M1eTENm49wR3U3xQ9qZ6TZwqcVkJ7Hpvz

2018-05-05 20:04 GMT+07:00, Stavros Skamagkis <notifications@github.com>:

**Comment by shiftkey** [comment]
@stavrossk thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by stavrossk** [comment]
@shiftkey Here you go: 
[2018-05-05.desktop.production.log](https://github.com/desktop/desktop/files/1977297/2018-05-05.desktop.production.log)

**Comment by shiftkey** [comment]
@stavrossk thanks for the details - it looks like the application isn't able to find a token for the user in the Windows Credential Manager:

```
2018-05-05T12:57:23.031Z - info: [ui] [AppStore] found account: stavrossk (Stavros Skamagkis)
2018-05-05T12:57:23.964Z - warn: [ui] Error refreshing account 'stavrossk'
Error: Cannot update an account which doesn't have a token: [object Object]
    at Object.n [as fatalError]
...
2018-05-05T12:59:08.132Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: MeediFier_for_MeediOS - stavrossk (empty token)
```

Could you try signing out and in again for your account to see if it stores a token? You'll see this by opening **Credential Manager**, selecting **Windows Credentials** and then looking for an entry named **GitHub - https://api.github.com/stavrossk**.

Here's what it looks like on my development machine, for example:

<img width="820" src="https://user-images.githubusercontent.com/359239/39670057-8f31ddbe-513f-11e8-9b75-42920f255675.png">

**Comment by stavrossk** [comment]
@shiftkey Thanks for the reply, the Crecendtial Manager has the entry you asked for, but the username is empty. (password field is not empty). Also it says that it was modified yesterday. It seems logical, since yesterday I performed a logout and logged in back again.

**Comment by shiftkey** [comment]
@stavrossk apologies for the delay in replying, but I'm trying to think of other ways that this might still be failing. Are you still encountering authentication issues? From that last log it looks like there weren't any other errors when push/pulling.

**Comment by stavrossk** [comment]
@shiftkey No, I haven't encountered any authentication errors since I updated to the latest GitHub Desktop version. Thanks for your interest.

**Comment by shiftkey** [comment]
@stavrossk that's great to hear. I'm going to close it out, but please let us know if it returns.
