### ISSUE TITLE
GitHub Desktop was unable to store the account token in the keychain

### ISSUE THREAD

**Issue by adebeo** [desktop/desktop#4614]
## Description
I'm on Macbookpro with MacOs 10.11.6
I use "Github desktop - Tasty Things Done Tastily (224) " on this machine since 3 year on this machine without any problem. With public and private repo
This morning , I try to push a commit github
-> the MacOs ask "if I give the acces to key to a githubxxxxx ( I don't remember) I say yes
-> the commit didn't work
-> A message show that a new "github desktop" is available
-> I accept to donwload it and install it into the application folder ( The withe one is the old one , the purple is the new application github desktop 1.1.1)
<img width="283" alt="capture d ecran 2018-05-06 a 19 27 13" src="https://user-images.githubusercontent.com/3003088/39676023-847cff2e-5163-11e8-8dbe-995480ee065c.png">

-> I try a lot to log several into github with this new application but I get this message

<img width="605" alt="capture d ecran 2018-05-06 a 19 26 18" src="https://user-images.githubusercontent.com/3003088/39676016-5f669592-5163-11e8-9c86-325d852c2801.png">

-> I try to use the previous application to push my commit. but I didn't achieve to do it. Application ask me to log in endlessly
<img width="423" alt="capture d ecran 2018-05-06 a 19 29 48" src="https://user-images.githubusercontent.com/3003088/39676045-dbd452d6-5163-11e8-97c0-08c89ba83546.png">

-> I decide to push the code with command line git push origin master,after login password its work !

-> when I come back to the new and the old application commit appear but with another avatar ( even if I use the same login)

<img width="245" alt="capture d ecran 2018-05-06 a 19 32 04" src="https://user-images.githubusercontent.com/3003088/39676060-2e3a2a8c-5164-11e8-81c9-0f95215ea340.png">

I don't know how to use github desktop any more.
Please help

## Version

* GitHub Desktop:
Tasty Things Done Tastily (224) and 1.1.1
* Operating system:
MacOs 10.11.6

**Comment by shiftkey** [comment]
@adebeo with respect to this message:

![](https://user-images.githubusercontent.com/3003088/39676016-5f669592-5163-11e8-9c86-325d852c2801.png)

Could you try the steps listed in [this workaround](https://github.com/desktop/desktop/blob/master/docs/known-issues.md#the-username-or-passphrase-you-entered-is-not-correct-error-after-signing-into-account---3263) to see if it addresses the issue? I can see you're not running High Sierra (where we've mostly seen this occur) but the details all match up.

> -> when I come back to the new and the old application commit appear but with another avatar ( even if I use the same login)

Check the `user.name` and `user.email` settings in your ~/.gitconfig - these are what Desktop is using to make the commits, and I guess a different email address is currently set there.

**Comment by adebeo** [comment]
Wahoo !
Lock and unlock wok fine for me ! Thank you Shifkey ! I couldn't find it by myself

**Comment by 2tackle** [comment]
@shiftkey Thanks so much! You helped much with my problem.
“how to GitHub Desktop was unable to store the account token in the keychain. Please check you have unlocked access to the 'login' keychain.” this popped up while I was trying to log into my account on Github desktop and your solution works. Do hope my comment could help with later users who have similar problems

**Comment by AimeeD90** [comment]
Thank you so much! It helps a lot!

**Comment by godrose** [comment]
Thank you @shiftkey 
It's really disappointing to see this kind of regression in this tool.

**Comment by ashleyriah** [comment]
@shiftkey Fixed my login issue as well, thank you!!

**Comment by FrizzleFur** [comment]
Yeah, Thanks!   

My issue was "GitHub Desktop was unable to store the account token in the keychain. Please check you have unlocked access to the 'login' keychain."
I just follow the Lock and unlock, worked, I think it maybe the right to access to the  'login' keychain.
![](http://oc98nass3.bkt.clouddn.com/15303369966352.jpg)

**Comment by tlouth19** [comment]
@shiftkey thanks 👍

**Comment by makbas86** [comment]
@shiftkey  Thanks . it worked for me :)

**Comment by shiftkey** [comment]
While it's great to hear that people appreciate this workaround helps them, I'm going to lock this so I don't keep getting notifications for each mention.
