### ISSUE TITLE
Github for windows colors and layout

### ISSUE THREAD

**Issue by rafaelcastrocouto** [desktop/desktop#4624]
## Can you add an option to reproduce the former "older" Github for Windows layout/colors?

The old layout was really good and this "new version" breaks it apart.
Can we have a "old Github desktop" layout/colors option in the settings?

Screenshot from the "old Github" attached

![untitled](https://user-images.githubusercontent.com/422159/39708858-b109415c-51ee-11e8-8736-777a0bedc6aa.png)

**Comment by j-f1** [comment]
See #1515 for our issue tracking the dark theme.

**Comment by niik** [comment]
Hey @rafaelcastrocouto, thanks for taking the time to contribute!

This issue is being tracked over in https://github.com/desktop/desktop/issues/1515 so please subscribe to that issue to follow along.
