### ISSUE TITLE
DESKTOP_OAUTH_CLIENT_ID for OAuth

### ISSUE THREAD

**Issue by wanjizheng** [desktop/desktop#4625]
A quick question, how could I define the DESKTOP_OAUTH_CLIENT_ID mentioned in https://github.com/desktop/desktop/blob/master/docs/technical/oauth.md   ?

**Comment by j-f1** [comment]
You can [create your own app](https://github.com/settings/applications/new) and copy the data from there, but the default values should work fine.

**Comment by niik** [comment]
Hey @wanjizheng, as @j-f1 said, the development build already ships with a test auth client id and secret that you can use while developing. If you want to ship your version to others you need to [create an OAuth application](https://developer.github.com/apps/building-oauth-apps/creating-an-oauth-app/) and use its client id and secret. I'm closing this issue but feel free to add more comments if there's anything else we can do to help
