### ISSUE TITLE
Feature Request: Missing Setting for Default Clone Folder in "Options"

### ISSUE THREAD

**Issue by omnipitous** [desktop/desktop#4626]
## Description
This seems to be a basic feature that is missing from the new tool. Need a way to specify the default folder to clone into instead of having to browse on each clone.

## Version
* GitHub Desktop:
Version 1.1.1
* Operating system:
Microsoft Windows [Version 10.0.17134.1]

## Steps to Reproduce
Open the Options...
Fail to see an option for default Clone path.

### Expected Behavior
See the option...

### Actual Behavior
Don't see the option...

## Additional Information
This feature was available in the old Desktop.

### Logs
Not pertinent for feature request.

**Comment by j-f1** [comment]
Once you select a folder to clone into, we’ll suggest that folder as the default the next time you clone something.

**Comment by shiftkey** [comment]
What @j-f1 said - we default to `~/Documents/GitHub` on a fresh install, will display this in the dialog when you clone a repository for the first time, and we'll update this if you choose a different path at that point.

**Comment by JordanMussi** [comment]
@shiftkey if the app remembers the directory from the first clone it could be frustrating for users who clone to an uncommon place the first time. Since there is a place where the directory is stored I agree with @omnipitous that there should be a option to change it. Perhaps this could be marked as a future proposal/help wanted?

**Comment by omnipitous** [comment]
I do appreciate the "remember last" feature but similar to what Jordan said I have a use-case at my current job that emphasizes this: All of our "internal/private" repos get cloned to a certain place on my machine and all 3rd-party repos get cloned elsewhere. In the old app I have our "Internal" location as the default.. when I want to clone a 3rd-party it's nice to not have the default change for that rarer occasion.

It's not an end-of-the-world miss but having a fixed default is definitely a nice-to-have feature.
