### ISSUE TITLE
Feature Request: Need more flexibility for Git Shell

### ISSUE THREAD

**Issue by omnipitous** [desktop/desktop#4627]
## Description
Would like more flexibility or at least options for Git Shell on Windows. The old Desktop app respected the default %SHELL% / $shell on the host and was able to open my Cygwin bash no problem. Modern Windows has its own bash as well. Execing any available shell should be capable without special code.

## Version
* GitHub Desktop:
Version 1.1.1
* Operating system:
Microsoft Windows [Version 10.0.17134.1]

## Steps to Reproduce
Open the Options... -> Advanced tab
Shell options only include "Command Prompt" and "Power Shell"

### Expected Behavior
See options for Known Shells (like above) OR select shell for any.

### Actual Behavior
Shell options only include "Command Prompt" and "Power Shell"

## Additional Information
This feature was more flexible in Old Desktop.

### Logs
Not pertinent for feature request.

**Comment by omnipitous** [comment]
As I recall I didn't have to configure it in the old app although it might just have been long enough ago I forgot.. When I click the "Open Git Shell" button it just always brought me to Cygwin Bash.. by far not the "standard" shell on my Windows machine so.. I did have %SHELL% set so I guess that was a presumption.

Windows 10 has bash built in and a lot of devs use Cygwin SO having one or the other available would be great. Not having either is not a huge hurt either but more of a nice-to-have.. my environment works in any of these shells bash is just more friendly.

**Comment by shiftkey** [comment]
I'm going to close this out as I think the outstanding questions have been addressed:

 - launching arbitrary shells was a Windows-specific feature, and I'm still hesitant to bring that across
 - support for additional shells can be done by contributors based on demand, and this approach means everyone can benefit from it

@omnipitous feel free to refer to #4267 as an example of adding a new shell for Windows, and #4641 for detailing WSL Bash support - if you'd like to see Cygwin Bash supported that's the approach we're currently supporting.
