### ISSUE TITLE
App menu foldout list items do not change on focus

### ISSUE THREAD

**Issue by JordanMussi** [desktop/desktop#4636]
## Description

The styling for this was removed by #4188 in https://github.com/desktop/desktop/commit/e0d7d9f4aefead97c3792eff6e1fb14ab75a18fe#diff-cad62e98a2e7c4bc492c0a912c3eb447L87.

## Version

* GitHub Desktop: 1.1.2-beta5

* Operating system: Windows 10

## Steps to Reproduce

1. Hover over any of the main app menu items to open its foldout
2. Move the mouse down to over over one of the list items

### Expected Behavior

The list item should behave as in 1.1.1 where the background is blue with white text on hover.

### Actual Behavior

No change on hover.

**Comment by iAmWillShepherd** [comment]
@JordanMussi Would you mind posting a GIF of this behavior?

**Comment by JordanMussi** [comment]
`1.1.1` | `1.1.2-beta5`
-- | --
![4636-1 1 1](https://user-images.githubusercontent.com/2552068/39773451-11afea7c-52f0-11e8-948b-93de557f6da8.gif) | ![4636-1 1 2-beta5](https://user-images.githubusercontent.com/2552068/39773452-14044c6e-52f0-11e8-8e71-9a58468c5886.gif)
