### ISSUE TITLE
ERRO-SHAREX

### ISSUE THREAD

**Issue by cradino** [desktop/desktop#4637]
When uploading one video *.mp4  ShareX - Erro  Message:  O servidor remoto retornou um erro:  (409) Conflito.  ShareX 
[https://i.imgur.com/HPT81gX.png](url)

**Comment by shiftkey** [comment]
@cradino this is the repository for GitHub Desktop. I think you need to reach out to [ShareX](https://getsharex.com/) and their support channels.
