### ISSUE TITLE
History tab not highlighting unsynced commits

### ISSUE THREAD

**Issue by r-pascal** [desktop/desktop#4645]
## Description

The history tab does not show the sync status of commits. Compared to the old client, there used to be a circle symbol next to commits that had not been pushed to the remote repository. Not sure if this is a bug or intended behaviour?!

![git-old-new-client](https://user-images.githubusercontent.com/4028417/39815957-08138640-539a-11e8-8196-9cb36daeb809.jpg)

## Version

* GitHub Desktop: 1.1.1

* Operating system: MAC OSX 10.11.6

**Comment by shiftkey** [comment]
@r-pascal apologies for not replying to this issue.

Please follow along with #5873, which has had some discussion about the area.
