### ISSUE TITLE
Please remove the "Discard all changes" option

### ISSUE THREAD

**Issue by krusek** [desktop/desktop#4651]
I've accidentally tapped it more than once when trying to discard changes on individual files. I've never done it on purpose.

**Comment by j-f1** [comment]
We’ll be making that option prompt for confirmation in the next update.

**Comment by shiftkey** [comment]
As discussed in #4423 and #4426, the next update will always ask you to confirm before discarding all changes:

![](https://user-images.githubusercontent.com/1715082/38574290-18cd1eee-3cbe-11e8-976d-8e67176e9770.gif)

Aiming to get this out mid-next week.

**Comment by cheshire137** [comment]
Related: #4781. Now that "Discard all changes" prompts me if I'm sure, despite me setting a preference saying to never prompt me, I thought it was a bug.
