### ISSUE TITLE
support for creating orphan branches

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#4654]
**Is your feature request related to a problem? Please describe.**
To not make too much repostories i would sometimes make a branch but it automatically bases it off master. I don't want it based off master because it for insance maybe a version writen in a completely diffrent language.

**Describe the solution you'd like**
I would like to have an option to make it a blank branch in this menu:
![przechwytywanie](https://user-images.githubusercontent.com/36047212/39870854-19e6d7e0-5463-11e8-874d-29b8b86c30bc.PNG)

**Describe alternatives you've considered**
An option named "New blank branch" in this menu:
![przechwytywanie2](https://user-images.githubusercontent.com/36047212/39871057-ef39bc78-5463-11e8-8ea7-d0fe330ab6bb.PNG)

**Teachability, Documentation, Adoption, Migration Strategy**
This feature will create a branch without any files or commits.
![mockup1](https://user-images.githubusercontent.com/36047212/39871534-77955b26-5465-11e8-9e1c-140a68e65193.png)
![mockup2](https://user-images.githubusercontent.com/36047212/39871540-7c127b52-5465-11e8-808f-2194aa050085.png)

**Comment by shiftkey** [comment]
@MAX0342 thanks for the feedback. In Git terminology this is called an `orphan` branch, because the first commit on this branch will have no parent commits.

I'm not sure how common or popular this request will be, but I'm happy to hear from others about it.

**Comment by MAX0342** [comment]
@shiftkey well I'm not good with git so I didn't know

**Comment by billygriffin** [comment]
Given that this user no longer exists and we haven't heard this elsewhere as a common problem, I'm going to remove the labels here.
