### ISSUE TITLE
"Open in explorer" does not work when repository is in OneDrive with "Files On-Demand" enabled

### ISSUE THREAD

**Issue by kelvinwop** [desktop/desktop#4662]
## Description

When you click 
![image](https://user-images.githubusercontent.com/30770221/39935673-6af1385e-550f-11e8-98d2-136f6ba38329.png)
Or
Repository>Show in explorer

nothing happens

Possibly related to: #2798

## Version

* GitHub Desktop: version 1.1.1

* Operating system:![image](https://user-images.githubusercontent.com/30770221/39935737-9bbd56e8-550f-11e8-9089-668e1f70fae6.png)

## Steps to Reproduce

1. have repo
2. open in explorer button (Repository>Open in explorer) or ![image](https://user-images.githubusercontent.com/30770221/39935673-6af1385e-550f-11e8-98d2-136f6ba38329.png)

### Expected Behavior

explorer opens the directory to the repository

### Actual Behavior

nothing at all

### Logs
[2018-05-11.desktop.production.log](https://github.com/desktop/desktop/files/1996135/2018-05-11.desktop.production.log)

I would imagine that this line:
`2018-05-11T16:38:26.636Z - error: [main] Unable to find file at 'C:\Users\kelvi\OneDrive\Documents\GitHub\autolist-webserver'
Error: EINVAL: invalid argument, stat 'C:\Users\kelvi\OneDrive\Documents\GitHub\autolist-webserver'`

shows the issue perfectly
In fact, if we copy that exact address
`C:\Users\kelvi\OneDrive\Documents\GitHub\autolist-webserver` into explorer bar
![image](https://user-images.githubusercontent.com/30770221/39935957-8abb2018-5510-11e8-8e3f-2323eab78a5c.png)

I get exactly where I want to go.

¯\\\_(ツ)\_/¯

Fun Fact: Show logs in explorer works perfectly as well

**Comment by shiftkey** [comment]
@kelvinwop thanks for the log. Are you able to navigate to the folder in Command Prompt? I wonder if the fact it's a OneDrive path is important to the issue.

**Comment by shiftkey** [comment]
It looks like VSCode has encountered the same issue, and this workaround might help: https://github.com/Microsoft/vscode/issues/27285#issuecomment-309270189

**Comment by kelvinwop** [comment]
The workaround works... kinda weird though

Not sure how navigating via explorer does it, but the shell method you guys use doesn't. Windows will be windows, I guess.

**Comment by kelvinwop** [comment]
oh dang that's fancy

**Comment by shiftkey** [comment]
Marking this one down to revisit as part of upgrading Desktop to use Electron 2.0.x.

**Comment by shiftkey** [comment]
I believe this has been fixed in Electron `2.0.x` which has been published to beta as Desktop `1.3.0-beta2`.

@kelvinwop I'm going to close this out as resolved, but please get back to us if you're still seeing this after we get `1.3.0` out to everyone at the end of the month.
