### ISSUE TITLE
Old node.js version

### ISSUE THREAD

**Issue by eKristensen** [desktop/desktop#4664]
Dear Github Desktop team.

According to Kasperskey you use an old version of node.js: https://threats.kaspersky.com/en/vulnerability/KLA11231/

The file is in the path: C:\Users\\%USERNAME%\AppData\Local\gitHubDesktop\app-1.1.1\node.dll

The metadata suggest you use version 8.2.1, whereas according to Kasperskey you have to updates to version 8.11 or newer for this issue to be fixed.

It came up when i scanned my computer for "Vulnerable applications".

I use Github Desktop Version 1.1.1 on Windows 10 version 1803

**Comment by shiftkey** [comment]
@eKristensen thanks for the report.

Unfortunately the version of Node we use currently (8.2.1) is dictated by Electron itself as Electron needs a specific Node version to ensure it interoperates with V8 and Chromium. As downstream users we can't change this arbitrarily without potentially breaking the app.

That said, we work closely with the Electron team when it comes to security, and have been keeping up with security fixes as they land, like:

 - [1.8.2](https://github.com/electron/electron/releases/tag/v1.8.2) - fix for command line argument parsing
 - [1.8.3](https://github.com/electron/electron/releases/tag/v1.8.3) - other security fixes not impacting Desktop

Other minor fixes waiting for us are not crucial:

 - [1.8.4](https://github.com/electron/electron/releases/tag/v1.8.4) - contains security fix that doesn't affect Desktop
 - [1.8.5](https://github.com/electron/electron/releases/tag/v1.8.5) - only contains minor fixes
 - [1.8.6](https://github.com/electron/electron/releases/tag/v1.8.6) - unrelated minor fix

When we have some bandwidth we're going to look at upgrading to Electron [2.0](https://github.com/electron/electron/releases/tag/v2.0.0), which will upgrade us to NodeJS 8.9.3. This however has some breaking changes, so we need to thoroughly test things as part of the upgrade.

**Comment by eKristensen** [comment]
Kinda sad, but that just how it is I guess.
