### ISSUE TITLE
Submodules and new git repositories show with repeated first letter

### ISSUE THREAD

**Issue by ujLion** [desktop/desktop#4670]
1. Place git repo within subfolder of the main repository working directory as A:\B
2. Shows as A:\BB in the file list tree pane

**Comment by shiftkey** [comment]
@UjLion are you on macOS or Windows?

This reminds me of an issue I saw ages ago which I'm trying to find because I don't know where it ended up.

**Comment by UjLion** [comment]
Windows 10 x64 (1709)

**Comment by shiftkey** [comment]
@BruceEckel also pointed out in #5512 that trying to commit this new submodule produces a vague error:

![](https://user-images.githubusercontent.com/1001900/44821247-e5564f00-abb1-11e8-8144-62ac2afa4bb0.png)

**Comment by rgougelet** [comment]
one workaround seems to be to add the submodule repo to .gitignore in the parent repo after using "git submodule add", this won't work with the submodule in .gitignore first. at least the phantom file doesn't show up in the gui anymore for me.

**Comment by d-Rickyy-b** [comment]
I experience the same issue.

![grafik](https://user-images.githubusercontent.com/5798157/129488312-41cb234d-4ab3-4b38-879d-91d58aea1291.png)

Is there any way to help debug this issue? I mean this is open since ~3 years.
___
Version 2.9.0 (x64)
Windows 10 Version 20H2 (Build 19042.1165)

**Comment by steveward** [comment]
Thanks for the bump @d-Rickyy-b, I'm going to close this in favor of the more recent issue https://github.com/desktop/desktop/issues/12314. I'd recommend following along there for updates.
