### ISSUE TITLE
preview what is different between the current branch and it's tracking branch

### ISSUE THREAD

**Issue by olegburov** [desktop/desktop#4671]
The desktop app (`v1.1.1`) doesn't have a feature to peek new commits from the origin before pulling them to a local repository. I can only blindly pull all commits in one go.

![github-desktop](https://user-images.githubusercontent.com/2487951/39971117-f4bd6106-56aa-11e8-93f5-200b0bc9a812.png)

Please add a new feature to see those changes in the app.

Additionally, it would be handy to choose specific changes that I what to pull to a local repository. For example, there are four new commits in the origin, but I need only one to pull out to a local repository.

If I will be able to see those changes, then I want to have a check list where I can pick which of them I want to pull now and leave the rest for later.

**Comment by olegburov** [comment]
@shiftkey not exactly. I was thinking about a scenario, where there were commit 1, 2 and 3, where commit 3 is the latest. GitHub Desktop allows me to pull out all three commits at once, like it does today. Or pull out commit 1 or 1 and 2, and later commit 3.

Let's say my local repository is 20 commits behind the origin, and I want to pull out only first two from these 20.

**Comment by shiftkey** [comment]
> I was thinking about a scenario, where there were commit 1, 2 and 3, where commit 3 is the latest. GitHub Desktop allows me to pull out all three commits at once, like it does today. Or pull out commit 1 or 1 and 2, and later commit 3.

That's different to what was originally requested.

Like @j-f1, I'd love to understand more about your workflow and what you're trying to achieve here.

**Comment by olegburov** [comment]
@shiftkey @j-f1 You're right. This issue is about to have an option just to see/peek what I'm pulling out from the origin. Let's focus on this, and I will open a new one for the second part where I said: 

> If I will be able to see those changes, then I want to have a check list where I can pick which of them I want to pull now and leave the rest for later.

**Comment by billygriffin** [comment]
Since this hasn't been something that has come up and since any potential solution we'd be looking at seems quite involved, I'm going to close this for now. We have been discussing things around seeing the diff of one entire branch to another in the context of PRs, and this is potentially relevant as we explore that, but I don't think we're going to focus on this as stated in the issue. Thanks for explaining!
