### ISSUE TITLE
'Not Responding' After Sleep? Windows 10

### ISSUE THREAD

**Issue by Templarian** [desktop/desktop#4672]
## Description

This rarely has happened, but I have seen it happen 3 times in the last month. Where coming out of sleep the GitHub Desktop app is in a sort of Frozen Not Responding state.

Clicking end process doesn't do anything, it seems to be stuck in a loop trying to close the process and/or child processes. The only solution is to restart my machine.

## Version

* GitHub Desktop: 1.1.1 (Says Latest)
* Operating system: Windows 10 1803 (aka April 2018 Update)

## Steps to Reproduce

1. Start GitHub Desktop
2. Leave Machine running for a while doing stuff.
3. Sleep Machine
4. Wake Machine
5. Select from taskbar. I'm not sure what causes it. The machine has 16gb of ram and I'm only using 10gb, so I don't think it's ram related.

### Expected Behavior

The application should resume where it was left off.

### Actual Behavior

It displays a black box, clicking the black window causes the "Not Responding" dialog. This dialog does not actually end the process.

## Additional Information

![image](https://user-images.githubusercontent.com/338885/39972882-ff10a640-56dc-11e8-94c9-e3b256b03189.png)

### Logs

[2018-05-13.desktop.production.zip](https://github.com/desktop/desktop/files/1999048/2018-05-13.desktop.production.zip)

**Comment by shiftkey** [comment]
@Templarian thanks for the report! 

The blank screen made me wonder if this was a general Electron issue with sleep/wake, but a quick skim of the Electron repository didn't show up anything interesting...

**Comment by Templarian** [comment]
One more note... it's happen twice on my Surface Pro 2017 and once on my Surface Laptop (work). So I don't think it's just this device is why I filed the bug. I never close the app and usually have it started right when my machine is powered on (so it was probably running for ~20 hours total across ~dozen sleeps.

It's so random and rare, that I have no idea if it's not in that log file. 🤷‍♂️  I'll try and reproduce it happens again.

**Comment by shiftkey** [comment]
> It's so random and rare, that I have no idea if it's not in that log file. 

I don't think it'll be something that's captured in the log file - there's a hook in Electron we don't listen to that reports when the renderer process (i.e. that window) [has crashed](https://electronjs.org/docs/api/web-contents#event-crashed), but it's not really informative - and looking at the screenshot it might not be that it's just unresponsive (needing to poke at a memory dump to figure it out).

**Comment by Templarian** [comment]
Small update: I have the latest version installed. It's happened a couple more times. Still no idea how to reproduce it. It renders really tiny and locks up.

![image](https://user-images.githubusercontent.com/338885/44998727-7300b880-af7d-11e8-9167-eb90f3a29b3d.png)

Sorry I can't add any other help. Not annoying enough to stop using it, just wanted to update it's still happens from time to time.

**Comment by endrawes0** [comment]
I can report this is still an issue. I see it regularly

**Comment by tierninho** [comment]
As this has not been reported in over a year, going to close this issue for now. Happy to reopen if needed.

**Comment by Inumedia** [comment]
@tierninho I'm still seeing this issue almost weekly

![image](https://user-images.githubusercontent.com/856822/60284564-daf00900-98d9-11e9-9adc-40c02890f00d.png)

**Comment by tierninho** [comment]
@Inumedia Please fill out a [new issue](https://github.com/desktop/desktop/issues/new?template=bug_report.md) so we can investigate.
