### ISSUE TITLE
starting in dev mode doesn't respect PORT value

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#4675]
Stumbled upon this as part of #3675 but it's actually an issue that's been around forever.

In theory, you can override a different port when launching the app in dev mode:

```
$ PORT=3001 yarn start
```

If you don't specify this environment variable, `3000` is used. That's this value:

https://github.com/desktop/desktop/blob/f7297021482886ceec53dfc414b8235525adc223/script/start#L33

However we also hard-code this value in [`webpack.development.js`](https://github.com/desktop/desktop/blob/master/app/webpack.development.js):

https://github.com/desktop/desktop/blob/f7297021482886ceec53dfc414b8235525adc223/app/webpack.development.js#L17-L26

Here's a rough patch to update this value, to get things started:

```diff
diff --git a/app/webpack.development.js b/app/webpack.development.js
index aab57ac31..1bd701afd 100644
--- a/app/webpack.development.js
+++ b/app/webpack.development.js
@@ -14,15 +14,29 @@ const askPassConfig = merge({}, common.askPass, config)
 const cliConfig = merge({}, common.cli, config)
 const highlighterConfig = merge({}, common.highlighter, config)
 
+function getPortOrDefault() {
+  const port = process.env.PORT
+  if (port != null) {
+    const result = parseInt(port)
+    if (isNaN(result)) {
+      throw new Error(`Unable to parse '${port}' into valid number`)
+    }
+    return result
+  }
+
+  return 3000
+}
+
+const port = getPortOrDefault()
+const rendererEntryPoint = `webpack-hot-middleware/client?path=http://localhost:${port}/__webpack_hmr`
+const publicPath = `http://localhost:${port}/build/`
+
 const rendererConfig = merge({}, common.renderer, config, {
   entry: {
-    renderer: [
-      'webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr',
-      common.renderer.entry.renderer,
-    ],
+    renderer: [rendererEntryPoint, common.renderer.entry.renderer],
   },
   output: {
-    publicPath: 'http://localhost:3000/build/',
+    publicPath,
   },
   module: {
     rules: [
```

There's two things in here for a contributor to help improve the development experience:

First, confirm the fix above addresses the issue - these steps should launch the app:

```shellsession
$ PORT=3001 yarn build:dev
$ PORT=3001 yarn start
```

Second, choosing a different port when `yarn start` should also work:

```shellsession
$ PORT=3001 yarn build:dev
$ PORT=3002 yarn start
```

Currently this just shows the developer tools without launching the Desktop UI - this might need some familiarity with how we're using `webpack-dev-middleware` here to ensure we're correctly building the renderer config:

https://github.com/desktop/desktop/blob/f7297021482886ceec53dfc414b8235525adc223/script/start#L35-L40

**Comment by sr98bj** [comment]
For Windows, the documentation should be updated to use the commands this way:
$ yarn build:dev PORT=3001
$ yarn start PORT=3001

and respectively

$ yarn build:dev PORT=3001 
$ yarn start PORT=3002

**Comment by sr98bj** [comment]
I WAS WRONG, shiftkey was correct, his version of the commands are golden and correct!

$ PORT=3001 yarn build:dev
$ PORT=3001 yarn start
Second, choosing a different port when yarn start should also work:

$ PORT=3001 yarn build:dev
$ PORT=3002 yarn start
