### ISSUE TITLE
External editor is not detected. And no option to search or browse for it

### ISSUE THREAD

**Issue by pavel-a** [desktop/desktop#4681]
## Description
On Windows: External editor is not detected. And no option to search or browse for it

## Version

* GitHub Desktop: 1.1.1

* Operating system: Win10 1803 (RS4 release), x64

## Steps to Reproduce

Installed the app, opened Options/advanced. That's it.

### Expected Behavior

It finds my existing editor ( I have Notepad++) or lets browse and point.

### Actual Behavior

It offers to install Atom

**Comment by iAmWillShepherd** [comment]
We have a list of supported editors in our [docs](https://github.com/desktop/desktop/blob/master/docs/technical/editor-integration.md#windows) for editor integration.

**Comment by shiftkey** [comment]
Please also note that there is a known limitation with Notepad++ that we uncovered in an earlier PR to add support: https://github.com/desktop/desktop/pull/4120#issuecomment-369901927
