### ISSUE TITLE
Rename menu items

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#4685]
Having a verb after a verb is weird i.e., View -> Show Branches List could just be View -> Branch List

![2018-05-14_20-16-23 239](https://user-images.githubusercontent.com/1715082/40031100-b13f3616-57b3-11e8-9c09-cd71d037e6f7.png)

**Comment by shiftkey** [comment]
FYI : the `Show` here is apparently a macOS convention https://github.com/desktop/desktop/pull/1063#discussion_r108217531

**Comment by shiftkey** [comment]
Also, I'll call out [this comment](https://github.com/desktop/desktop/pull/1063#discussion_r108212311):

> I think because most of our menu items are verb-oriented where these are noun-oriented.

We should ensure we're consistent here, and avoid going back to noun-oriented menu labels unless it's essential.

**Comment by nerdneha** [comment]
Hmmm if it's a macOS convention, maybe we keep it? Are we doing the right thing for Windows?

**Comment by shiftkey** [comment]
I think Windows is fine too

**Comment by shiftkey** [comment]
@niik I think you were involved in the last bit of renaming here - any thoughts to add here?

**Comment by agisilaos** [comment]
After testing a bunch of other apps, Show is a "must" when it comes to showing another view etc. Kinda makes sense. `Repository List` without `Show` feels really broad. 💭

**Comment by iAmWillShepherd** [comment]
Going to close this out since @shiftkey and @agisilaos are right, this is a macOS convention. Also, we are doing the correct things on Windows as well.
