### ISSUE TITLE
[Compare Branches] add a bit more context to the merge call-to-action

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#4689]
There's a bit of confusion here about the result of this merge:

<img width="430"  src="https://user-images.githubusercontent.com/359239/40032111-0c1b395e-5836-11e8-88f3-3c6d561c5155.png">

It's been recommended to mention the target of the merge here too:

<img width="422"   src="https://user-images.githubusercontent.com/359239/40032109-0bed84c8-5836-11e8-82e1-730768e5af0d.png">

**Comment by gdub1018** [comment]
1.
