### ISSUE TITLE
Compare branches - Cannot select another branch if branch field is already filled

### ISSUE THREAD

**Issue by emilianopenedo** [desktop/desktop#4696]
Occurs in Version 1.1.2-beta5 (Windows 10)
Steps to reproduce:
1) Compare a branch typing in the branch field and select one from the list.
2) Type in the field without pressing (X) to clear the field.
3) Pick a different branch than the previous one from the list.
Result: Selection not applied and comparison stays in the previous branch.

PS: If you clear the field pressing the (X) everything goes right.

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

We are actually tweaking this feature this week, I'm going to assign this issue to our milestone so that we can verify this has been fixed.

**Comment by shiftkey** [comment]
@emilianopenedo I've not been able to reproduce this on `master` e.g 7f02d93f4624aee8a9e46286e5a6525ea341b6bb with either keyboard or mouse.

Are you able to clarify the interactions in your repro steps so I can confirm this has been sorted once a couple of other PRs have been merged?

**Comment by iAmWillShepherd** [comment]
@emilianopenedo, is this the behavior you are experiencing? 

![2018-05-18 00 26 20](https://user-images.githubusercontent.com/1715082/40217388-22af7984-5a32-11e8-8d0a-dfd346264154.gif)

Here's what I did to get to that state:
1. Initiate compare by typing _no-more_dexie_
1. Use arrow-key to select row
1. Press <kbd>return</kbd>
1. Initiate another compare by typing _master_
1. Use arrow-key to select row*
1. Press <kbd>return</kbd>

*Notice that the text changes from _master_ back to _no-more-dexie_

**Comment by emilianopenedo** [comment]
@iAmWillShepherd that's exactly the behavior
