### ISSUE TITLE
Github Desktop detects changes to image files immediately after pulling from origin and doesn't allow you to discard these changes.

### ISSUE THREAD

**Issue by enochrod** [desktop/desktop#4699]
## Description

I am having a problem with Github detecting changes to my image files, after pulling from origin.  I am also unable to discard changes in order to remove these changes files from the list.

This is a relatively new problem that has only cropped up in the last couple of weeks.

## Version

* GitHub Desktop: Version 1.1.1

* Operating system: Microsoft Windows [Version 10.0.16299.431]

## Steps to Reproduce

1. Switch to Master branch. (At this moment, the Master branch did not have any stages or unstaged changes)
2. Click pull origin to bring in new changes from origin master.
3. After pull is done, Github Desktop shows 3 image files that have been changed.
4. Try to discard files.
5. Right click the text that says "3 changes files", left click  "Discard all changes..."

### Expected Behavior
I should not see any changed files, immediately after pulling changes from the origin.

Discarding all changes files should restore the files back to their original state and remove them from the list.

### Actual Behavior

Immediately  after pulling from origin, Github Desktop shows changes files

Discarding files does nothing, Changed files still appear in the list.

**Comment by enochrod** [comment]
Looks like this problem was caused by `* text eol=lf` in my `.gitattributes` file which was affecting binary files as well.

**Comment by iAmWillShepherd** [comment]
Glad you were able to resolve this one, I had this on my todo list to try and reproduce.
