### ISSUE TITLE
Can't Connect Because Of Firewall Issues

### ISSUE THREAD

**Issue by randomblink** [desktop/desktop#4700]
My company just recently added a new level of security through firewall settings. We have self-signed certificates. Where can I point to a PEM file, like I do with NPM, so I can continue using this app?

**Comment by iAmWillShepherd** [comment]
@randomblink , did adding your certificate to the certificate store solve your issue?

**Comment by iAmWillShepherd** [comment]
@ipat8, that error you posted looks very similar to an issue in our [known issues doc](https://github.com/desktop/desktop/blob/master/docs/known-issues.md#certificate-revocation-check-fails---3326). Would you mind trying the workaround and getting back to me on whether or not that fixes the issue?

**Comment by shiftkey** [comment]
Closing this out as we have an existing resource for people who want to point Git at their own certificate bundle.
