### ISSUE TITLE
Windows 10 April 2018 Update messed up Github

### ISSUE THREAD

**Issue by tekbird** [desktop/desktop#4706]
I updated my windows 10 to the latest which is (April 2018 update). After that, when I try to fetch from remote, I get the following error:

fatal: unable to access 'https://github.com/xxxxxx/xxxxx.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

**Comment by iAmWillShepherd** [comment]
Please follow the work-around detailed in our [known issues](https://github.com/desktop/desktop/pull/4693) document.
