### ISSUE TITLE
Not able to Clone and cannot find .gitconfig file in system

### ISSUE THREAD

**Issue by sharmr1z** [desktop/desktop#4715]
## Version

* GitHub Desktop:

* Operating system:

**Comment by sharmr1z** [comment]
which template

**Comment by shiftkey** [comment]
@sharmr1z I've updated the original comment with the issue template

**Comment by shiftkey** [comment]
Closing this out as inactive. @sharmr1z if you're able to fill out the template to help us troubleshoot we're happy to revisit.
