### ISSUE TITLE
Update from Default Branch - Question

### ISSUE THREAD

**Issue by Cervenka** [desktop/desktop#4717]
Hi,
what is the actual git command (and options) issued when I use the desktop client's feature "Update from Default Branch"? 

Thank you!

**Comment by shiftkey** [comment]
@Cervenka this menu item emits the `'update-branch'` message to the main window (what we call the renderer in Electron terminology):

https://github.com/desktop/desktop/blob/1ca123e03c8983d768154a716d089fb1c8288b85/app/src/main-process/menu/build-default-menu.ts#L283-L290

Back in the main application code, we run the `updateBranch` method which looks for your default branch (typically `master`):

https://github.com/desktop/desktop/blob/1ca123e03c8983d768154a716d089fb1c8288b85/app/src/ui/app.tsx#L362-L374

This flows through the `AppStore` (for managing application state) and `GitStore` (which tracks Git data for each repository) and ends up here:

https://github.com/desktop/desktop/blob/1ca123e03c8983d768154a716d089fb1c8288b85/app/src/lib/git/merge.ts#L5-L10

Our Git operations in the app use the Git command line, so what we're doing in the app is just a `git merge master` into your current branch.

Let me know if you have any other questions about this!

**Comment by Cervenka** [comment]
Thank you for the detailed explanation. I appreciate it!
