### ISSUE TITLE
Allow one click commit then push button

### ISSUE THREAD

**Issue by xgdgsc** [desktop/desktop#4719]
**Is your feature request related to a problem? Please describe.**
When using the commit UI, I only have one option to commit. 

**Describe the solution you'd like**
I' d like an option to commit and then push at the same time.
 
**Teachability, Documentation, Adoption, Migration Strategy**
Sourcetree provides a checkbox when commiting.

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

Could you share some more details on your workflow to help us understand the use-cases for pushing on commit? 

For context, GitHub Desktop follows the [GitHub Flow](https://guides.github.com/introduction/flow/).

**Comment by shiftkey** [comment]
@xgdgsc Thanks for the feedback. We're already tracking this in #2191 as this feature was implemented originally in the Classic Desktop app for macOS - but not Windows, so we haven't ported it across yet.

Please add your feedback and details about your workflow to #2191.

**Comment by xgdgsc** [comment]
Thanks. For example for projects with one person or just a few people. It would be useful to push on commit for backup purposes. 

I think your habit of tracking future proposals as closed issues would generate more duplicate feature requests as github users usually would only see the search results in open issues. And I didn' t see those duplicate search results although I intentionally looked through the long list of closed issues.

**Comment by shiftkey** [comment]
> I think your habit of tracking future proposals as closed issues would generate more duplicate feature requests as github users usually would only see the search results in open issues

This is something we've been doing to keep our backlog under control, but it's something we're thinking about revisiting when we have some bandwidth.
