### ISSUE TITLE
Menu item label is cut off on Windows

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#4721]
I noticed this while testing a PR on Windows.

<img width="272" alt="screen shot 2018-05-17 at 11 04 27 am" src="https://user-images.githubusercontent.com/1715082/40189559-5e31bb68-59c2-11e8-9e86-b2e29df03a49.png">

Notice that _Clone Repository..._ has the letter _y_ missing. This is likely due to the keyboard shortcut taking up a ton of space. I'm not sure what the path forward is, but we could start using _repo_ instead of _repository_.

**Comment by shiftkey** [comment]
> This is likely due to the keyboard shortcut taking up a ton of space.

Also note that the `...` is required for this menu shortcut, because the menu item here is supposed to open a new dialog.

> I'm not sure what the path forward is, but we could start using repo instead of repository.

I'm 👎 on this for historical reasons (I think we've made this same mistake before) and being consistent with the rest of the GitHub ecosystem.

**Comment by iAmWillShepherd** [comment]
> Also note that the ... is required for this menu shortcut, because the menu item here is supposed to open a new dialog.

I should have been more clear. I was not advocating we remove the ellipsis. But I still feel like we should show the entire word.

Citing consistency, there menu item above has the entire word, so maybe this one should too?

**Comment by shiftkey** [comment]
Moving this `enhancement` as something for someone with a Windows setup to dig into.

**Comment by j-f1** [comment]
@shiftkey it should also be possible for someone on another platform to lie to Desktop — I did it before with my PR for the tooltip on the minimize button and it worked fairly well.

**Comment by shiftkey** [comment]
@j-f1 can you share how you hacked around it? It'd be neat to figure out how easy that would be to switch between OSes, but I worry about not quite testing the right setup using shortcuts like this (like you can't run the macOS menu on Windows, and might actually :boom: the app I suspect)

**Comment by iAmWillShepherd** [comment]
Fixed in #5348
