### ISSUE TITLE
Merge into current branch menu item is not disabled at the right times

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#4725]
This menu item should be disabled if there are no branches to merge.

<img width="544" alt="screen shot 2018-05-17 at 3 13 36 pm" src="https://user-images.githubusercontent.com/1715082/40201564-057f95f8-59e5-11e8-94cb-79451fd08351.png">

**Comment by shiftkey** [comment]
@iAmWillShepherd this came up earlier in #2637:

> Should we be displaying the Branch > Merge into Current Branch.. option if `master` is the only branch.

And this was where that discussion ended up:

> My gut feeling concurs, we shouldn't disable the menu item. That said the merge branch dialog with no other branches than the current isn't great either. I think we could add some UX around that case to make it ✨ but unfortunately that'll have to be fairly low down on our list of priorities right now.
