### ISSUE TITLE
Can't double-click changed file to open

### ISSUE THREAD

**Issue by maryfries** [desktop/desktop#4727]
You used to be able to double-click a changed file that was not yet committed and it would open the file in your default application, but you can't do that any more. It was convenient. Can you bring that feature back? Thanks!

**Comment by shiftkey** [comment]
@maryfries thanks for the report. We're already tracking this in https://github.com/desktop/desktop/issues/2620, so please follow along with that issue.

**Comment by 1083** [comment]
@shiftkey That issue is now closed.
