### ISSUE TITLE
GitHub Desktop is showing changes but I havent made changes and up to date with master

### ISSUE THREAD

**Issue by rpilman** [desktop/desktop#4728]
## Description
 
From time to time when I open GitHub Desktop program it will show changes even when I didn't make any changes to the file locally and I'm up to date with master branch.

## Version

* GitHub Desktop: 
Ver. 1.1.1

* Operating system: 
Windows 10 Pro Native - [Version 10.0.17134.48]

## Steps to Reproduce

1. Open GitHub Desktop 
2. Verify you're on master & click Pull
3. A file or change another co-worker did shows under changes
   * But, I did pull and expect to see any new changes or file.  The problem I'm having is it's showing changes but I didn't make any changes locally please help.

### Expected Behavior

Would expect after opening GitHub desktop and pulling and syncing with master that no changes should be showing because I havent made any local changes. 

### Actual Behavior

 The problem I'm having is it's showing changes but I didn't make any changes locally please help.

## Additional Information

![2018-05-17_16-40-08](https://user-images.githubusercontent.com/2511721/40205774-04180e4e-59f3-11e8-926f-778b8d006ca9.jpg)

### Logs

[2018-05-17.desktop.production.log](https://github.com/desktop/desktop/files/2014849/2018-05-17.desktop.production.log)

**Comment by rpilman** [comment]
@iAmWillShepherd -  In Git CMD desktop, I run `git config core.eol` and it doesn't show anything. 

![image](https://user-images.githubusercontent.com/2511721/40208699-99f3ffa6-5a00-11e8-82d2-40663a7f6d1f.png)

**Comment by rpilman** [comment]
I just closed GitHub Desktop and re-opened it and it's still showing 1 file under changes.  Any way I can resolve this with some git commands using Git CMD?

**Comment by shiftkey** [comment]
@rpilman could you run these commands from Git CMD and share the output? They might help with troubleshooting what's happening:

```
$ git status
$ git diff [path to file]
$ git config -l --show-origin
```

**Comment by rpilman** [comment]
@shiftkey 

Here's a screen shot:
![image](https://user-images.githubusercontent.com/2511721/40244710-3248966c-5a89-11e8-91cf-f6839a835c58.png)

**Comment by rpilman** [comment]
So this morning I opened Github desktop and getting this error now 

![image](https://user-images.githubusercontent.com/2511721/40249805-c961298c-5a99-11e8-9f80-77dd32e4f551.png)

**Comment by shiftkey** [comment]
@rpilman that last command should be a lower-case `L`, not a `1`.

Also, it's really hard to say _why_ Git is reporting the file as modified without a bit of detail about the file itself:

 - Is the file actually a binary format? The file extension keeps getting obfuscated in screenshots, which isn't helping to reproduce or understand the problem.
 - Git's binary detection is based on the file contents, and it essentially is scanning the file for a `NUL` character (`\0`) in the first 8000 bytes. Are you expecting to be able to diff the file?

**Comment by shiftkey** [comment]
Closing this out as inactive. @rpilman if you're able to send through an updated `git config -l --show-origin` and answer the questions from the previous comment we're happy to revisit this.

**Comment by vanvught** [comment]
This is still a bug. I have 1600+ changed files which are not changed. And all telling : "no content changes found".

**Comment by ryanagler** [comment]
I have the same issue.  In my instance the project is on a mounted folder on a linux machine, not sure if that has anything to do with it.

**Comment by steveward** [comment]
@ryanagler are you working on a Windows machine? It's likely you are running into file mode changes if you are working across different operating systems.

**Comment by ryanagler** [comment]
> @ryanagler are you working on a Windows machine? It's likely you are running into file mode changes if you are working across different operating systems.
Yes, using Github Desktop on Windows, with a mounted drive that is on a Linux machine.  Is there a way to resolve this?

**Comment by ryanagler** [comment]
@steveward I have been playing with it more, and if "Hide Whitespace" is checked, the message when I click on any of the files changes to "Only whitespace changes found" instead of "No content changes found".  

But no matter what I do, I can't get it to stop listing all files under "changed files".  I have tried putting the following into a .gitattributes:

* text=auto
* text eol=lf

But it didn't seem to do much.

**Comment by steveward** [comment]
@ryanagler you can try running `git config core.filemode false` to ignore file mode changes for the specific repository you are working with. If you would like to set that option globally you can use the `--global` flag to set it in the global `.gitconfig`.

**Comment by avencherus** [comment]
Having the same issue from time to time from the Windows client.  Going into command line and typing git add -A will clear them.  It usually has a message of carriage returns.

My config is also core.filemode false, and this doesn't affect it.

Is this still the best place to report this, or has it moved onto another issue thread?

**Comment by steveward** [comment]
@avencherus the carriage return issue is related to line endings, not file modes, which is why setting `core.filemode` to false has no affect on those files. For line endings you would want to use `core.autocrlf`. I'd recommend taking a look at [GitHub's line endings guide](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings) for further information.

**Comment by avencherus** [comment]
@steveward Thanks.  I did try that out on our Windows PC.  There was a file that kept popping up in the GitHub desktop entries, and a warning of LF to CRLF.  I tried `autocrfl` option globally, no effect, it kept popping up.  I also tried added this to the .gitattributes file `*.import text eol=crfl`.  Also still seeing these appear.

I'm working with a cross platform app that is likely generating the LF on certain project files, since the core developers of it work in Linux.

**Comment by Maheima** [comment]
> @avencherus the carriage return issue is related to line endings, not file modes, which is why setting `core.filemode` to false has no affect on those files. For line endings you would want to use `core.autocrlf`. I'd recommend taking a look at [GitHub's line endings guide](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings) for further information.

this was very helpful! Thanks.

**Comment by fzhangj2ee** [comment]
> @ryanagler you can try running `git config core.filemode false` to ignore file mode changes for the specific repository you are working with. If you would like to set that option globally you can use the `--global` flag to set it in the global `.gitconfig`.

I followed this, also set core.autocrlf true, however, it did not work right away. I restarted computer, then created a different branch, going through the stash etc. suddenly everything worked!

**Comment by chrisdenton-ct** [comment]
I get this problem quite often. Today, for example I made a fresh clone of my repo, and then 10 minutes later GitHub Desktop thinks I have made 505 local changes, when in fact I've made none.

**Comment by 15kstudios** [comment]
Same issue here.

**Comment by cdiservices** [comment]
![Screenshot 2024-09-10 at 12 00 15 PM](https://github.com/user-attachments/assets/01b9aedf-7300-43a9-9214-a8517e5edc98)

My GitHub Desktop shows that all my code files are modified, even though no actual changes were made to the code. I just copied, pasted, and unpacked the files, but now everything appears as modified. What could be causing this?

**Comment by elite-mob** [comment]
![Screenshot 2024-09-10 at 12 00 15 PM](https://github.com/user-attachments/assets/7723e036-ea63-4fe0-baa2-96e90181b8c1)

My GitHub Desktop shows that all my code files are modified, even though no actual changes were made to the code. I just copied, pasted, and unpacked the files, but now everything appears as modified. What could be causing this?

**Comment by EzgiAltun** [comment]
I have the same problem. I can not understand why, I did 0 changes, but github shows many changes made....

**Comment by 15kstudios** [comment]
Line endings (CRLF vs LF) can cause Git to falsely report large modifications, some editors auto-format files leading to unintended changes, and Git tracks file permission (chmod) changes, treating them as modifications.
