### ISSUE TITLE
add context menu to current repository screen region

### ISSUE THREAD

**Issue by santiagoprieto** [desktop/desktop#4737]
First off, I want to say that the new version of the Desktop App is awesome!

**Is your feature request related to a problem? Please describe.**
Hi, in the old version of the desktop app, it used to be less clicks to open a repository either in terminal, atom, or in the finder. I used to find it super helpful, but now have to open the drop down menu of all repositories to do this.
<img width="446" alt="screen shot 2018-05-19 at 12 20 10 pm" src="https://user-images.githubusercontent.com/8649137/40272219-00256a30-5b5f-11e8-8ccd-6b6748b4e084.png">

**Describe the solution you'd like**
It would be amazing to have this same modal appear on the top menu as such when you use the double finger click on a mac: 
(sorry for the shitty photoshop)
![screen shot 2018-05-19 at 12 22 22 pm](https://user-images.githubusercontent.com/8649137/40272280-b432c090-5b5f-11e8-96a0-f7138bce46f1.jpg)

**Describe alternatives you've considered**
The alternative is always having to open and reopen the dropdown, which gets annoying when doing this many times per day.

**Teachability, Documentation, Adoption, Migration Strategy**
It's just easier and more natural navigation.

**Comment by j-f1** [comment]
You should be able to perform all of these actions from the Repository menu.

**Comment by santiagoprieto** [comment]
Thanks for letting me know! 👍 I guess I never use the `apple menu`... I'm always looking directly in the app screen itself. I think it _still_ would be useful to add to the main nav, but maybe it's just me.This feature is a total random improvement suggestion from a lone user, so feel free to use or discard the idea as you see fit.

**Comment by agisilaos** [comment]
Hey @santiagoprieto thank you for the suggestion. In the meantime if you don't want to use the apple Tab Menu, you can use these shortcuts:
- Open in Terminal -> ctrl + `
- Show In Finder -> `Shift + CMD + F`
- Show In Atom -> `Shift + CMD + A`

**Comment by santiagoprieto** [comment]
@agisilaos thanks for the suggestion! I will surely use these many times per day.

**Comment by agisilaos** [comment]
Anytime. 🎉

**Comment by shiftkey** [comment]
Thanks @j-f1 and @j-f1 for jumping in with the suggestions.

@santiagoprieto for the moment we're encouraging people to use the keyboard shortcuts to speed things up. I've tweaked the title to focus this issue on this request:

> It would be amazing to have this same modal appear on the top menu as such when you use the double finger click on a mac

For reference, we have a similar discussion over in #4114 for a different area of the app (being able to quickly get to the pull request associated with the current branch) that is also already covered by a keyboard shortcut.

**Comment by billygriffin** [comment]
Thanks for the suggestion @santiagoprieto and for the discussion about how it's an issue for you! Because this hasn't been a thing we've heard broadly and the fact that there are shortcuts from the `Repository` menu and associated keyboard shortcuts, I'm going to close this. We're also looking at repo organization more and this area of the app more generally in the context of #6460, so I'd definitely encourage you to check out the work happening there. Thanks again, and hope you're continuing to find the app useful overall!
