### ISSUE TITLE
Error when publishing branch: "The remote disconnected. Check your Internet connection and try again."

### ISSUE THREAD

**Issue by AidanCooper** [desktop/desktop#4746]
## Description

When I try to publish my branch to Github from Github Desktop, it stalls on ["Pushing to origin" ](http://prntscr.com/jktdtv) before showing the following error:
["The remote disconnected. Check your Internet connection and try again."](http://prntscr.com/jktf1x)

I've also tried pushing through Command Prompt but again see a fatal error ([screenshot](http://prntscr.com/jktfs6)).

## Version

* GitHub Desktop: Version 1.1.1
* Git: 2.17.0

* Operating system: Windows 10 Home

## Steps to Reproduce

1. Create a new repository on github.com and open in GitHub desktop.
2. Create a new branch via GitHub desktop.
3. Add some files and commit to the new branch.
4. Try to publish the branch to GitHub.

### Expected Behavior

Branch should be published to GitHub website.

### Actual Behavior

Fatal error prevents branch from being published.

## Additional Information

I have seen other bug reports for this issue, but none of the suggested fixes have worked for me.

My network connection is good and stable. I'm not behind a firewall.

The repository contains two files, one of which being a large CSV (146MB). I have tried "git config --global http.postBuffer 157286400" without success.

### Logs

[2018-05-21.desktop.production.log](https://github.com/desktop/desktop/files/2023827/2018-05-21.desktop.production.log)

**Comment by steveward** [comment]
Thanks for opening this @AidanCooper. The 401 error indicates a credential issue -- could you try logging out and then logging back in to GitHub Desktop to see if you still encounter this issue?

> The repository contains two files, one of which being a large CSV (146MB)

That file is going to prevent the push from succeeding since [GitHub limits file size to 100MB](https://help.github.com/articles/conditions-for-large-files/).

I would recommend looking into using [Git LFS](https://help.github.com/articles/versioning-large-files/) if you are wanting to push a large file up to GitHub. If you have any questions about using Git LFS with GitHub Desktop please let us know!

**Comment by AidanCooper** [comment]
Hi @steveward - thank you for your suggestions.

I still had the same issue after logging out and back in to GitHub Desktop.

I installed Git LFS and tracked the appropriate file, as instructed. When I first attempted to publish the branch I could see the large file being uploaded successfully, but again it subsequently stalled at the same stage as before and returned the same error shortly afterwards. If I try to publish the branch again, the upload stage is skipped but I still run into the same error.

Same problem when I try to push from the command line, also.

Here's an updated log file:
[2018-05-21.desktop.production.log](https://github.com/desktop/desktop/files/2024038/2018-05-21.desktop.production.log)

**Comment by shiftkey** [comment]
@AidanCooper looking at the the Git LFS output, it seems to have skipped that file, which would explain why it's encountering the same problem:

```
2018-05-21T20:39:51.558Z - error: [ui] `git -c credential.helper= push origin data-preparation --set-upstream --progress` exited with an unexpected code: 1.

Git LFS: (0 of 0 files, 1 skipped) 0 B / 0 B, 142.55 MB skipped                
Git LFS: (0 of 0 files, 1 skipped) 0 B / 0 B, 142.55 MB skipped   
...
```

I think, if you can figure out why the file is being skipped, you should be able to get this working in Desktop.

**Comment by AidanCooper** [comment]
@shiftkey - I reset my local commits and started over with Git LFS implemented, and everything seems to be working now. Thanks for the help!

**Comment by klamomd** [comment]
Note to any others experiencing this problem: for me it stemmed from my project folder being saved onto another internal hard drive (M:) instead of my main drive (C:). Creating the repository on my desktop and copying everything over fixed the issue for me.

**Comment by steveward** [comment]
@klamomd thanks for sharing your workaround!

**Comment by fathah** [comment]
Try this command. It might be an issue with your post buffer
```
git config --global http.postBuffer 157286400
```

**Comment by LindholmDK** [comment]
> Try this command. It might be an issue with your post buffer
> 
> ```
> git config --global http.postBuffer 157286400
> ```

Where do i put this command?

**Comment by englianhu** [comment]
- https://github.com/desktop/desktop/issues/4746#issuecomment-1204295607
- https://github.com/desktop/desktop/issues/16405#issuecomment-1487338064
- https://github.com/desktop/desktop/issues/14936#issuecomment-1204295156
