### ISSUE TITLE
bad netrc file

### ISSUE THREAD

**Issue by zeke** [desktop/desktop#4752]
Seeing this dialog in Desktop:

> bad netrc file /Users/z/.netrc: line 7: keyword expected; got method

<img width="671" alt="screen shot 2018-05-21 at 8 40 48 pm" src="https://user-images.githubusercontent.com/2289/40341026-860e0eca-5d37-11e8-9b6c-c67c3fd3b5de.png">

I think this is caused by something in the latest Heroku CLI: https://github.com/heroku/cli/issues/539

cc @jdxcode

**Comment by shiftkey** [comment]
@zeke already tracking this in #4745, but thanks for the reference to the upstream issue ❤️

**Comment by zeke** [comment]
dang thought I was quick. should have searched first! 🙈
