### ISSUE TITLE
"No Branches to Compare" shown when there are 2 branches

### ISSUE THREAD

**Issue by meaghanlewis** [desktop/desktop#4755]
## Description
After adding a second branch to a new repository, I expected to be able to compare that branch with master.

## Version

* GitHub Desktop: 1.1.2-beta7
* Operating system: Mac

## Steps to Reproduce
1. Start by creating a new repo or use a repo with only one branch
2. Add a second branch
3. Try to compare branches by: `Branch -> Compare to Branch`,look under the `History` tab, or use the kebab option from the branch list to select `Compare to this branch` for a specific branch

### Expected Behavior
I should be able to compare `branch1` to `master`. Even after adding changes and committing changes on `branch1` I'm unable to do so. 

### Actual Behavior

![screen shot 2018-05-22 at 10 38 27 am](https://user-images.githubusercontent.com/10103121/40380619-78013ef2-5dae-11e8-99f4-69253a7e3cc4.png)

![screen shot 2018-05-22 at 10 36 32 am](https://user-images.githubusercontent.com/10103121/40380630-7fd919ba-5dae-11e8-8c33-a169c8aaf892.png)

![screen shot 2018-05-22 at 10 34 08 am](https://user-images.githubusercontent.com/10103121/40380637-847e63b2-5dae-11e8-9044-85a109c25139.png)

After adding another branch this works as expected.

**Comment by shiftkey** [comment]
I think this is the same report as #4947 which was fixed in #4948 and will be available in `1.2.4`.
