### ISSUE TITLE
Unable to use SSH key's with passphrases

### ISSUE THREAD

**Issue by rocktavious** [desktop/desktop#4756]
Following the Github Documentation for setting up an SSH key and then configuring Github Desktop for Windows - leads you into a state where your SSH key has a passphrase but when setting the remote to use an SSH clone URL leads to all git remote actions to fail because Github Desktop does not prompt you to enter your SSH key's passphrase.

**Comment by steveward** [comment]
Thanks for opening this @rocktavious. You can find some of the known SSH issues we would like to address in the future in https://github.com/desktop/desktop/issues/2579. 

Working with SSH keys with passphrases should work if the [key has been added to `ssh-agent`](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#adding-your-ssh-key-to-the-ssh-agent). Can you verify that this is the case on your machine?

**Comment by rocktavious** [comment]
@steveward It looks like after reading through #2579 i probably didn't run `eval $(ssh-agent -s)` prior to launching the desktop app (it was already open prior to setting up the SSH key) - i look forward to all the improvements discussed in #2579 though.
