### ISSUE TITLE
Deleting text in compare branch selector causes branch selector to lose focus

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#4758]
Noticed that the branch list is too eager to blur the branch list while testing #4743

There are two scenarios where this issue occurs:
1. Deleting the entire value in the branch selector in 1 go
2. Deleting the value in the branch selector 1 character at a time

**Reproduction steps (scenario 1):**
1. Select a branch to compare to
2. Click branch selector
3. Press <kbd>Delete</kbd> key

**Reproduction steps (scenario 2):**
1. Select a branch to compare to
2. Click branch selector
3. Place cursor at end of selection
4. Delete 1 character at a time

I expected the branch list to show the placeholder _Select  Branch to Compare…_ and that the branch list would remain focused until I pressed <kbd>Delete</kbd> again, <kbd>Escape</kbd> or the little _X_ in the top-right corner of the input.

What actually happens is the branch list is blurred before I'm done with it.

The GIF shows both cases:
![2018-05-22 14 27 29](https://user-images.githubusercontent.com/1715082/40386382-2ee43eb0-5dcf-11e8-91b4-0c4c61ff9682.gif)

**Comment by shiftkey** [comment]
This was fixed in #4751
