### ISSUE TITLE
Change notification dot on Changes tab to a badge

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#4772]
## Goal

Prevent confusion that could be caused by using the same UI element to notify users of two separate updates: new changes vs. new commits.

**Background**

This task was pulled from #4646.

## Solution

* Replace notification dot with a badge
* The badge's content will be the number of files that have changed
* Remove badge when there are no changes to be committed

### Mockup

**Before**
![before](https://user-images.githubusercontent.com/1715082/40588464-16502972-61a3-11e8-9172-9310ef463d64.png)

**After**
![screen shot 2018-05-23 at 3 01 37 pm](https://user-images.githubusercontent.com/1715082/40588446-f3283188-61a2-11e8-86a9-b1de162e6cf3.png)

## Help Wanted

If you're interested in taking on this task, please @mention me in a comment and I'll move this issue to _taken_ and serve as your point of contact for getting it delivered.

### What are we are looking?

* Build a component, `FilesChangedBadge`, that
* Accepts 1 prop, `numFilesChanged`, for the number that will be displayed
* Replace the blue notification dot with `FilesChangedBadge`

### Nice to haves ✨ 

* Handle large numbers in the following way, to ensure we don't have to fiddle with formatting too much:

| Condition | What to render |
|:--|:--|
| `x === 0` | Nothing |
| `x > 0 && x < 300` | Badge with `x` |
| `x >= 300` | Badge with `300+` |
* Styles to make the component look like the mockup

### Where to start

The notification dot is located here (note that it is not a component):
https://github.com/desktop/desktop/blob/c64e55527b1df9a20a2c5c896e82ecd3e9207447/app/src/ui/repository.tsx#L85-L98

**Comment by j-f1** [comment]
How about making it white text on a blue bubble and putting a similar label on the history with “⬆️ X ⬇️ Y”?

**Comment by iAmWillShepherd** [comment]
@j-f1 we already have a design for this. See the mockup ☝️ .

**Comment by iAmWillShepherd** [comment]
Also, checkout the issue I pulled this out of. There you will see what the notification will look like.

**Comment by yongdamsh** [comment]
Can I work on this?

**Comment by iAmWillShepherd** [comment]
@yongdamsh sure thing 👍
