### ISSUE TITLE
add support for --reference when cloning (to reduce network and storage costs)

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [desktop/desktop#4775]
**Is your feature request related to a problem? Please describe.**
I want to clone a really big repository, which is a fork of another.

**Describe the solution you'd like**
I'd like an UI for `--reference`, like using an already imported repository and a file chooser.

**Describe alternatives you've considered**
It's also possible to automatically use it for forks, but if the fork base is deleted locally, a problem is likely to happen.

**Teachability, Documentation, Adoption, Migration Strategy**
First, they should clone the fork base, and then the fork with the `--reference` parameter pointing to the base.

**Comment by shiftkey** [comment]
@kaeptmblaubaer1000 I have a few questions:

> I want to clone a really big repository, which is a fork of another.

How often do you need to do this operation? And it's not clear to me which of these repositories are available locally - are either of them? 

> I'd like an UI for --repository, like using an already imported repository and a file chooser.

I'm not familiar with this `--repository` flag - the [Git SCM docs for `git clone`](https://git-scm.com/docs/git-clone) don't mention this either. Can you clarify what this parameter is supposed to represent?

If you're using a GitHub fork we'll ask you if you want to track the upstream repository, and we infer that information from the API details about the repository. Outside of that scenario, I'd like to understand more about the actual workflow that might help out here.

**Comment by kaeptmblaubaer1000** [comment]
@shiftkey my mistake, it's called `--reference`, not `--repository`.
The upstream repository is available locally, and both repositories are on GitHub.

**Comment by shiftkey** [comment]
@kaeptmblaubaer1000 thanks for clarifying.

We're using an up-to-date Git, so as a workaround I think if you clone with `--reference` and add the repository to the app we should respect that behaviour. 

We don't really have a good story about "cloning from a local repository" yet in terms of an interface, so I think we're a fair way off from looking into this deeper. I'm going to label this as `future-proposal` so we can track it, and close it out as a way to keep our issue tracker under control.

**Comment by billygriffin** [comment]
@kaeptmblaubaer1000 Thanks so much for the issue and request. Up to now we haven't heard very much feedback that this would be helpful for others, so I'm going to remove the `future-proposal` label to indicate that we don't intend to support this at present. However, we are always open to revisiting things like this if we start to hear from other users that they're also facing problems that would be solved with something like you suggest. Thanks again!
