### ISSUE TITLE
Losing all my repos

### ISSUE THREAD

**Issue by maximekl** [desktop/desktop#4777]
## Description

My local repository and one created on my GitHub folder are not listed on desktop app.
I have no more information, after some days when i re-open desktop app all my repo are lost.

## Version
I had 1.1.1, but bug was still here (i re-added all my repos), just updated to 1.2.0 but not in fixed issues.

## Steps to Reproduce
Dont have more to said.

### Expected Behavior
Not loosing my repos

### Actual Behavior
Lossing repos

## Additional Information
OS X El Capitan 10.11.5
Sometime i am low in ram and space.
and sometime my mac turn off (no more batterie).

### Logs
I added the last 3 logs, maybe it can help.
[2018-05-24.desktop.production.log](https://github.com/desktop/desktop/files/2034558/2018-05-24.desktop.production.log)
[2018-05-23.desktop.production.log](https://github.com/desktop/desktop/files/2034559/2018-05-23.desktop.production.log)
[2018-05-22.desktop.production.log](https://github.com/desktop/desktop/files/2034560/2018-05-22.desktop.production.log)

**Comment by steveward** [comment]
Thanks for opening this @maximekl. I have not seen any other reports of this, so my guess is that it may be due to the local cache becoming corrupt. 

In the log from 5-22 I can see that one repository was loaded:

`2018-05-22T08:25:30.033Z - info: [ui] [AppStore] loading 1 repositories from store`

In the log file from 5-24 I can see that no repositories were loaded:

`2018-05-24T08:51:24.267Z - info: [ui] [AppStore] loading 0 repositories from store`

Does that line up with the timing of when you were unable to see your repositories in GitHub Desktop?

**Comment by maximekl** [comment]
Hi @steveward,
Yep and the log is quite straightforward.

**Comment by maximekl** [comment]
Hi @steveward,
This morning i lost all my repo again, what happened :
- I laked HDD space yesteday (128GB and hdd memory cache took a lot)
- No more batterie, my computer shutdown last night
- This morning my computer rebooted, a weird bug with AVG happend on this case, he invalidate all  SSL certificate.
- I restarted my computer, everything works now, but i loosed all my repo :(

Here are the 2 logs from yesteday and today

[2018-06-06.desktop.production.log](https://github.com/desktop/desktop/files/2079779/2018-06-06.desktop.production.log)
[2018-06-07.desktop.production.log](https://github.com/desktop/desktop/files/2079780/2018-06-07.desktop.production.log)

**Comment by steveward** [comment]
@maximekl I'm sorry to hear this happened again. I can see the issue in the log file where you ran out of space on your machine like you mentioned:

```
2018-06-06T20:25:41.690Z - error: [ui] Error writing LFS progress file
Error: ENOSPC: no space left on device, mkdtemp '/var/folders/72/6q_4_pxj79z_5527g_0h7kkh0000gn/T/GitHubDesktop-lfs-progress-bMWhg2'
```

If your repositories are lost again, I would like for you to follow these steps and let me know what you see:

1. Open GitHub Desktop
2. Go to the file menu and select `View` > `Toggle Developer Tools`
3. Go to the `Application` tab
4. Under `Storage` in the side pane select `IndexedDB` > `Database` > `Repositories` > `path`

This will allow you to view the repositories that are cached in the database -- let us know if you see anything there after your repositories have been removed.

**Comment by maximekl** [comment]
Hi @steveward, 
this morning it happened again, and the database is empty (with the update as well):
<img width="1120" alt="screen shot 2018-06-11 at 10 45 24" src="https://user-images.githubusercontent.com/11152214/41221561-c0d11b28-6d64-11e8-91e7-94f027869960.png">

**Comment by platon9000** [comment]
Fuck it speed!!!


Le 11 juin 2018 4:47 AM, MaximeK <notifications@github.com> a écrit :

Hi @steveward<https://github.com/steveward>,
this morning it happened again, and the database is empty (with the update as well):
[screen shot 2018-06-11 at 10 45 24]<https://user-images.githubusercontent.com/11152214/41221561-c0d11b28-6d64-11e8-91e7-94f027869960.png>

**Comment by Ericvulpi** [comment]
I also lost all my repositories when switching to the new version.
But I have no cache or HDD space issue (more than 50% free for both)
I can't even see my github account repositories ...

**Comment by j-f1** [comment]
@Ericvulpi That’s not a bug — we don’t transfer repositories over from the old app You should be able to select your repository clones in your file manager, then drag-and-drop them onto the new app to add them.

**Comment by maximekl** [comment]
@j-f1 For info, that already happened without updating my app.

**Comment by shiftkey** [comment]
@maximekl @steveward this feels like some important context for #4414:

```
2018-06-06T20:25:41.690Z - error: [ui] Error writing LFS progress file
Error: ENOSPC: no space left on device, mkdtemp '/var/folders/72/6q_4_pxj79z_5527g_0h7kkh0000gn/T/GitHubDesktop-lfs-progress-bMWhg2'
```

I left it open as a chance for someone to contribute as it seemed like a minor issue, but if it's causing Desktop to lose data like this I'm happy to expedite the fix and ensure we're cleaning up after ourselves.

**Comment by maximekl** [comment]
@shiftkey I would love to test a release with this patch :)

**Comment by shiftkey** [comment]
@maximekl out of curiosity, can you look into your `TEMP` directory and see if there are lots of these LFS pointer directories leftover?

In command prompt you can run this command to see what's listed:

```
> dir %TEMP%\GitHubDesktop*

 Volume in drive C has no label.
 Volume Serial Number is 1A14-4865

 Directory of C:\Users\shiftkey\AppData\Local\Temp

15/06/2018  08:05    <DIR>          GitHubDesktop-lfs-progress-4ipWrU
18/06/2018  09:07    <DIR>          GitHubDesktop-lfs-progress-dgRRAu
18/06/2018  09:07    <DIR>          GitHubDesktop-lfs-progress-f4RCd1
15/06/2018  08:04    <DIR>          GitHubDesktop-lfs-progress-FA3fB5
15/06/2018  08:05    <DIR>          GitHubDesktop-lfs-progress-fLwVWm
15/06/2018  08:05    <DIR>          GitHubDesktop-lfs-progress-JWd15A
18/06/2018  09:17    <DIR>          GitHubDesktop-lfs-progress-kAnKDQ
18/06/2018  09:46    <DIR>          GitHubDesktop-lfs-progress-MYM4RH
15/06/2018  08:04    <DIR>          GitHubDesktop-lfs-progress-qP6mvR
18/06/2018  09:28    <DIR>          GitHubDesktop-lfs-progress-qSZC30
18/06/2018  09:40    <DIR>          GitHubDesktop-lfs-progress-R2JNAi
18/06/2018  09:11    <DIR>          GitHubDesktop-lfs-progress-Rcj85x
10/06/2018  19:46    <DIR>          GitHubDesktop-lfs-progress-SdR4c3
18/06/2018  09:57    <DIR>          GitHubDesktop-lfs-progress-sf0l6K
18/06/2018  09:22    <DIR>          GitHubDesktop-lfs-progress-TsuKig
15/06/2018  08:04    <DIR>          GitHubDesktop-lfs-progress-wMP5oW
18/06/2018  09:35    <DIR>          GitHubDesktop-lfs-progress-xnItVS
18/06/2018  09:11    <DIR>          GitHubDesktop-lfs-progress-xNWMAb
18/06/2018  09:51    <DIR>          GitHubDesktop-lfs-progress-ZOX0KC
               0 File(s)              0 bytes
              19 Dir(s)  231,429,468,160 bytes free
```

Desktop is already removing the file inside the directory, but I wonder if we need to also remove the directory while we're here.

**Comment by maximekl** [comment]
Here what is in my temp folder (/var/folders/):
![screen shot 2018-06-18 at 15 29 27](https://user-images.githubusercontent.com/11152214/41538907-a7099d2a-730c-11e8-933f-52fcdfaeb48c.png)

**Comment by maximekl** [comment]
Hi @shiftkey, thanks for your time.
I still have this issue:
<img width="903" alt="screen shot 2018-07-17 at 16 03 43" src="https://user-images.githubusercontent.com/11152214/42822324-117f82d4-89db-11e8-9b76-40c76864a47f.png">

Here the logs related:
[2018-07-16.desktop.production.log](https://github.com/desktop/desktop/files/2201973/2018-07-16.desktop.production.log)
[2018-07-17.desktop.production.log](https://github.com/desktop/desktop/files/2201974/2018-07-17.desktop.production.log)

Now a `ls GitHubDesktop-* | wc -l` in $TMPDIR give me 1891, an increase of 348 from 29 days ago (Did you add a script for clearing the $TMPDIR ?)

**Comment by shiftkey** [comment]
@maximekl 

> (Did you add a script for clearing the $TMPDIR ?)

No, we should only be clearing out new entries.

It's not clear to me from the logs when you updated, but this command will help show when the directories were created:

```
$ ls -l $TMPDIR | grep GitHubDesktop-
```

If the folders are not recent, I think at least that issue has been fixed.

**Comment by maximekl** [comment]
`$ ls -l $TMPDIR | grep GitHubDesktop-`

give me no result, no more temp files huhu 👍

**Comment by shakyjake** [comment]
> @Ericvulpi That’s not a bug — we don’t transfer repositories over from the old app

So you're intentionally disincentivising updating?

**Comment by tierninho** [comment]
I think this issue can be closed at this point. Happy to re-open if further investigation needed.
