### ISSUE TITLE
Feature request: 'Discard selected changes' in the context menu 

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [desktop/desktop#4778]
1. **Is your feature request related to a problem? Please describe.**
If you have multiple modified files, but for some reason you want to discard changes on a subset of these files, you have no option. Context menu provides either *Discard changes*, which discards changes in the file you right-clicked, or *Discard all changes*, which discards **all** currently discovered changes.
Both options ignore your selections made by checking check-boxes.

2. **Describe the solution you'd like**
    - Add a context menu item *Discard selected changes* (or any other appropriate clear name), which performs **discard** operations on **selected** (using check-boxes) files. Add a **confirmation** dialog that cannot be disabled (as operation is performed on, possibly, a large amount of files at the same time).
     **-OR-**
     - Change functionality of *Discard all changes* to *Discard all selected changes* and use check-box selections. This way current *Discard all changes* operation can be performed by first, selecting all files and second, clicking appropriate menu item. 

3. **Describe alternatives you've considered**
    - Manually discarding files one by one. Works if you have a few files in your *Changes* and you want to discard changes only in part of those files
    - `git checkout -- <pattern>`

4. **Teachability, Documentation, Adoption, Migration Strategy**
![capture](https://user-images.githubusercontent.com/8782986/40489002-be30873e-5f70-11e8-9d4c-4205a3908294.PNG)

**Comment by niik** [comment]
Hi @Ilia-Kosenkov, thanks for opening this.

You should be able to select more than one file by Shift/Control clicking on them and then right clicking and selecting 'Discard selected changes'.

![screen shot 2018-05-24 at 16 23 53](https://user-images.githubusercontent.com/634063/40491710-152b0264-5f6f-11e8-85cd-f2b33476c58a.png)

This change shipped in the latest release (1.2) so make sure you're up to date by going to the Help menu and selecting 'About GitHub Desktop'.

Please let me know if that doesn't work or if there's a reason you aren't able to use that feature.

**Comment by amoyano** [comment]
> I am sorry I apparently did not carefully read the change log and got confused by **two** types of selection - the usual one with shift and the one using check boxes. The latest `1.2.0` does have this feature and works fine, thank you for the explanation.

how do you do it using check box? I don't find the option... thanks...

**Comment by amoyano** [comment]
> Hi @Ilia-Kosenkov, thanks for opening this.
> 
> You should be able to select more than one file by Shift/Control clicking on them and then right clicking and selecting 'Discard selected changes'.
> 
> ![screen shot 2018-05-24 at 16 23 53](https://user-images.githubusercontent.com/634063/40491710-152b0264-5f6f-11e8-85cd-f2b33476c58a.png)
> 
> This change shipped in the latest release (1.2) so make sure you're up to date by going to the Help menu and selecting 'About GitHub Desktop'.
> 
> Please let me know if that doesn't work or if there's a reason you aren't able to use that feature.

how do you do it using check boxes?

**Comment by tidy-dev** [comment]
@amoyano Sorry for the confusion. The check boxes are not for deleting. The check boxes represent which files are staged for commit or not. You can delete as you show in your screenshot.

Example of checkbox use. Modify 3 files, but only want to commit 2 of those changes. You simply uncheck the file you don't want to commit. Type your summary/description and commit. The unchecked file will remain in your changes list.
