### ISSUE TITLE
Missing Features from previous version

### ISSUE THREAD

**Issue by glennreid** [desktop/desktop#4789]
Trying hard to like the new Desktop client (Mac) but the old one had more sophisticated features that would be valuable additions.

Requests:

-  Most noticeable is the lack of the old "Automatically Sync After Committing" option.  It is almost never useful to just have a local repo commit -- and it's really easy to overlook a Push.
- Also liked the word "Sync" better than "Push".  I always hit the Sync button before doing anything.
- The pale blue highlight color in Diffs (for adds) is barely visible and not nearly as good as the green highlight in previous version.
- The column width resize for the Changes/History column is constrained to a max value that is too short.  With long filenames, it's useful to be able to resize this much wide.  I have a 4k monitor and plenty of real estate -- why limit it at all?

Thanks for listening!

**Comment by j-f1** [comment]
> The pale blue highlight color in Diffs … is barely visible

It should still be green. Can you upload a screenshot so we can see what’s going on?

**Comment by shiftkey** [comment]
@glennreid thanks for the feedback.

We're tracking some of these things in other places already:

> Most noticeable is the lack of the old "Automatically Sync After Committing" option. It is almost never useful to just have a local repo commit -- and it's really easy to overlook a Push.

This is being discussed in #2191

> Also liked the word "Sync" better than "Push". I always hit the Sync button before doing anything.

We've talked a bit about this in #1565

> The column width resize for the Changes/History column is constrained to a max value that is too short. 

This is captured in #2745

**Comment by glennreid** [comment]
@j-f1 , thanks for your note.  here are screen shots:

![github desktop v224](https://user-images.githubusercontent.com/1266643/40579079-e4c81474-60d4-11e8-9d92-e8ea446795c0.png)
![github desktop v1 2 0](https://user-images.githubusercontent.com/1266643/40579080-e85aadae-60d4-11e8-89c2-d96a844a762c.png)

I saved the old app so I've uploaded a screen shot from before and after.

**Comment by glennreid** [comment]
In case it matters, I have changed my OS X system-wide preference (under General) so my Highlight color is a ghastly orangish, which makes it much easier to see selected text.  It's possible that has something to do with this.  The highlight color on the "before" screen shot in the line number column shows that highlight color.

**Comment by shiftkey** [comment]
@glennreid thanks for the screenshot. This feels like the ongoing discussion in #1688 about making the "staged lines" clearer.

**Comment by shiftkey** [comment]
@glennreid I think we've been able to cross-reference this issue in existing issues, so I'm going to close this out. Feel free to open fresh issues to provide further feedback about other parts of the app.

**Comment by glennreid** [comment]
Okay, #1688 is certainly related.  Just make it better and we'll all be happy!
