### ISSUE TITLE
Support for manual stashing

### ISSUE THREAD

**Issue by shacker** [desktop/desktop#4793]
#1633 is a feature request to support "automagic" stashing. I'm not so interested in the magic aspect, but would very much like to see support for manual stashing, as I consider it a part of essential workflow. This would help Github Desktop gain parity with tools like Atlassian SourceTree, which do support manual stashing.

**Comment by adamreisnz** [comment]
I am also in favour of this feature. Stashing is a very frequent operation, and it is currently one of the few commands I still have to leave Github desktop and go into the command line for. It'd be great to have a simple, intuitive GUI for simple stash/unstash operations.

**Comment by shiftkey** [comment]
@shacker thanks for the suggestion. We've got an earlier discussion about this in #2304 - please add your thoughts to that issue.

**Comment by adamreisnz** [comment]
Funny @shiftkey, @iAmWillShepherd asked @shacker to create a new issue for it ;)
