### ISSUE TITLE
Keyboard shortcuts broken for non english keyboard layouts

### ISSUE THREAD

**Issue by johanwikstrom** [desktop/desktop#4796]
## Description

When having a non English keyboard with characters that needs a "shift" combination to get to this character this breaks. 

## Version

* GitHub Desktop:

1.2.0
* Operating system:
Windows 10

## Steps to Reproduce

Lets take open in git bash for example. It set to ctrl+`  but this character  is made by doing shift+´ on my local keyboard (swedish). 

![image](https://user-images.githubusercontent.com/664718/40605067-65b367f4-6261-11e8-9e18-f6d317c78eca.png)

Going against key above tab as in english do not work either. (does work if changing the keyboard layout to english).

I would suggest either to handle this case in some way, or allow us to manually override the keyboard shortcuts.

**Comment by shiftkey** [comment]
@johanwikstrom thanks for the report! I'm going to add your details to #3240 where we're tracking this issue, and provides more details about what needs to change.
