### ISSUE TITLE
Authentication Failed - web account working but app is not 

### ISSUE THREAD

**Issue by usmankhanisb** [desktop/desktop#4797]
Hi,
I am trying to clone Google code here via Github Desktop account, I clicked Clone repository option and than clicked URL option from file menu. 
https://github.com/GoogleCloudPlatform/cloudml-samples/tree/master/census
but it says that authentication failed add user name password. I added the exact username password as I have on Github web account. It is not working. 

Am I missing something here ?

**Comment by shiftkey** [comment]
@usmankhanisb did this get resolved? I've added the issue template to the comment - if you can fill that out and attach the logs we might be able to help troubleshoot further.
