### ISSUE TITLE
Rewrite our build scripts in TypeScript

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#48]
Because T Y P E S

For some reason I was thinking we'd need to setup a whole compilation step for them. But we can use [ts-node](https://www.npmjs.com/package/ts-node) to run them and it _should_ Just Work®.

**Comment by j-f1** [comment]
List of scripts:

- [x] [`build.ts`](https://github.com/desktop/desktop/blob/master/script/build.ts)
- [ ] [`debug`](https://github.com/desktop/desktop/blob/master/script/debug) (imports [`express`](https://www.npmjs.com/package/@types/express), [`webpack`](https://www.npmjs.com/package/@types/webpack), [`webpack-dev-middleware`](https://www.npmjs.com/package/@types/webpack-dev-middleware), and [`webpack-hot-middleware`](https://www.npmjs.com/package/@types/webpack-hot-middleware)) (maybe merge with `start`?)
- [ ] [`dist-info.js`](https://github.com/desktop/desktop/blob/master/script/dist-info.js) (depended upon by [`package`](https://github.com/desktop/desktop/blob/master/script/package), [`publish`](https://github.com/desktop/desktop/blob/master/script/publish), [`review-logs.ts`](https://github.com/desktop/desktop/blob/master/script/review-logs.ts), [`run.js`](https://github.com/desktop/desktop/blob/master/script/run.js), and [`test-setup.ts`](https://github.com/desktop/desktop/blob/master/script/test-setup.ts))
- [ ] [`generate-octicons`](https://github.com/desktop/desktop/blob/master/script/generate-octicons) (imports `process` (?!), [`xml2js`](https://www.npmjs.com/package/@types/xml2js), and `to-camel-case`)
- [ ] [`is-it-pretty.js`](https://github.com/desktop/desktop/blob/master/script/is-it-pretty.js) (🔥 in #2405)
- [ ] [`license-overrides.js`](https://github.com/desktop/desktop/blob/master/script/license-overrides.js) (depended upon by `build.ts`)
- [ ] [`package`](https://github.com/desktop/desktop/blob/master/script/package) (imports [`fs-extra`](https://www.npmjs.com/package/@types/fs-extra) and `electron-winstaller`)
- [ ] [`publish`](https://github.com/desktop/desktop/blob/master/script/publish) (imports [`aws-sdk`](https://www.npmjs.com/package/aws-sdk) and [`request`](https://www.npmjs.com/package/@types/request))
- [x] [`review-logs.ts`](https://github.com/desktop/desktop/blob/master/script/review-logs.ts)
- [ ] [`run.js`](https://github.com/desktop/desktop/blob/master/script/run.js) (depended upon by [`start`](https://github.com/desktop/desktop/blob/master/script/start))
- [ ] [`start`](https://github.com/desktop/desktop/blob/master/script/start) (imports [`express`](https://www.npmjs.com/package/@types/express), [`webpack`](https://www.npmjs.com/package/@types/webpack), [`webpack-dev-middleware`](https://www.npmjs.com/package/@types/webpack-dev-middleware), and [`webpack-hot-middleware`](https://www.npmjs.com/package/@types/webpack-hot-middleware))
- [x] [`test-review.ts`](https://github.com/desktop/desktop/blob/master/script/test-review.ts)
- [x] [`test-setup.ts`](https://github.com/desktop/desktop/blob/master/script/test-setup.ts)

**Comment by shiftkey** [comment]
Just a heads-up:

 - `dist-info.js` is also `require`'d in the webpack configurations, which we don't currently have plans to port to TS
 -  "imports process (?!)" - the only usage i could find is for `process.exit(1)` which should work globally

**Comment by shiftkey** [comment]
Adding `@types/electron-winstaller` is underway here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19814
