### ISSUE TITLE
fatal: unable to access 'https://github.com/tensorflow/tensorflow.git/': Could not resolve host: github.com

### ISSUE THREAD

**Issue by Nagarjunasagar** [desktop/desktop#4800]
## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
Closing this out as inactive. @Nagarjunasagar if you're able to fill out the template we're happy to revisit this.

**Comment by bopoh13** [comment]
For Windows 7 32-bit I had a [similar](https://github.com/desktop/desktop/issues/5180) problem.
