### ISSUE TITLE
Unable to set up

### ISSUE THREAD

**Issue by bsoyka** [desktop/desktop#4803]
## Description

Whenever I try to install GitHub Desktop on my device, I get an error with a link to the file attached.

## Version

* GitHub Desktop: N/A

* Operating system: Microsoft Windows [Version 10.0.16299.431]

## Steps to Reproduce

1. Click on regular, machine-wide, or beta installation link.
2. Run downloaded file.
3. Wait for error to show during setup.

### Expected Behavior

I expected to get GitHub Desktop installed.

### Actual Behavior

I receive an error every time.

## Additional Information

I don't have any other information to share, but please ask me if there is something I'm forgetting.

### Logs

[SquirrelSetup.log](https://github.com/desktop/desktop/files/2046487/SquirrelSetup.log)

**Comment by shiftkey** [comment]
@bsoyka thanks for the report. The error is occurring because you're trying to install the application onto a 32-bit version of Windows:

```
---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
```

For more information about this, and why we haven't supported 32-bit yet, see #1214.

**Comment by bsoyka** [comment]
I guess that’s okay.  I can just keep using the command prompt.
