### ISSUE TITLE
"Merge Conflicts Found" dialog should be aware of which tab you're currently on

### ISSUE THREAD

**Issue by adamreisnz** [desktop/desktop#4806]
## Description
Not sure if this button is meant to do something yet, or if it's part of future work on dealing with merge conflicts:

![image](https://user-images.githubusercontent.com/490562/40639656-294c705c-6366-11e8-950e-6da3dd0c8315.png)

For me, clicking either Close or View conflicts does exactly the same thing -- nothing (except for closing the modal).

Should View conflicts do something else?

## Version
* GitHub Desktop: 1.2.0
* Operating system: OS X 10.12.6

## Steps to Reproduce
1. Merge a branch which will generate some conflicts
2. Observe modal opens up
3. Click View conflicts
4. Observe nothing happens

### Expected Behavior
Not sure?

### Actual Behavior
Nothing

**Comment by shiftkey** [comment]
@adamreisnz this was implemented in https://github.com/desktop/desktop/pull/4694 and the goal was to ensure that you were focused on the Changes tab after you encounter a merge conflict.

With the new Compare and Merge flow you'd be on the other tab and the generic error dialog wouldn't move you, which was confusing to some users. The classic Merge Branch dialog can be initiated from either tab, so you might already be there.

Got any ideas about improving this flow?

**Comment by adamreisnz** [comment]
I see, in that case the solution seems simple -- if you're already on that tab, hide the View Conflicts button?

This should avoid confusion when you click it and nothing happens 👍

**Comment by shiftkey** [comment]
@adamreisnz interesting idea - we could show a different message here to indicate that you're already on the right tab. cc @desktop/core @desktop/comrades for feels

**Comment by iAmWillShepherd** [comment]
I'm 👍 on providing a message in addition to removing the button if it won't do any meaningful.

**Comment by fungjj92** [comment]
Taking a look

**Comment by tierninho** [comment]
Closing this issue as it is no longer relevant given the recent feature work around merge conflicts.
