### ISSUE TITLE
Github-desktop - Branch list is not getting refreshed automatically, when remote branch is deleted

### ISSUE THREAD

**Issue by pawan-idrive** [desktop/desktop#4807]
## Description

What, I have noticed, branches list is not getting refreshed automatically in case if remote branch is deleted, whereas, it works in case of pull requests.

## Version

Github deskop v1.2 
* GitHub Desktop:

* Operating system:
windows 10 OS

## Steps to Reproduce

1.  `Create a remote branch` , it should be shown in Github desktop application
2. `Delete that branch from Remote'

### Expected Behavior

Expectation is, that deleted branch should be removed from Github desktop as well
### Actual Behavior

That branch remains there until deleted manually

**Comment by tian-heng** [comment]
Have the same problem on the Mac system.  hope someone can fix it

**Comment by shiftkey** [comment]
@pawan-idrive @tian-heng can you confirm that the branches are checked out locally?

For branches that are never checked out locally, they should be removed on the next fetch - either background or a manual fetch (we do a `--prune` when fetching from a remote to cleanup the remote refs).

Once you've checked out the remote branch locally, we're don't clean those up currently because you might still want to work on them. We've talked about pruned merged branches in #750 (such as those from pull requests) but that's not currently on our roadmap.

**Comment by tian-heng** [comment]
@shiftkey Yes, I'm sure. On the Mac system, speak accurately, when I checked out the remote branch locally, and delete delete the local branch in the folder, branch list is not getting refreshed automatically.As the local branch grows, many invalid branch lists in the Github-desktop, I have to remove it one by one..so, I hope the branch list is getting refreshed automatically or delete multiple at a time.Thank you!

**Comment by pawan-idrive** [comment]
@shiftkey  I am not creating local branches, as Github Desktop lists my remote branch and I commit followed by push my changes directly into remote branch.

**Comment by pawan-idrive** [comment]
Okay, I understood it now, Github desktop is creating local branch for me automatically and that is why as @shiftkey mentioned, once remote branch is deleted, local branch doesn't get deleted automatically as of now. I noticed, If I try to delete a local branch, i get a prompt to delete remote branch as well ( if there is a reference available to it ). As per me, we could close this issue as not an issue :). Thanks @shiftkey  and @tian-heng

**Comment by shiftkey** [comment]
@pawan-idrive yep, that's the current behaviour. @tian-heng are we fine to close this out and use #750 to track pruning local branches that have been merged?

**Comment by shiftkey** [comment]
I'm going to close this out as I believe this is behaviour already we're tracking in #750. Let me know if there's any other questions about this area.

**Comment by orvindemsy** [comment]
Hello, it's Oct 29th, 2019, currently dealing with this thing, and apparently manually delete the branch on Github Desktop is the only way?

**Comment by tierninho** [comment]
@orvindemsy Please see this [pull request](https://github.com/desktop/desktop/pull/6544) for the logic behind branch pruning. Otherwise, you will have to remove the branch manually. Thanks for reaching out.
