### ISSUE TITLE
After restarting my client following a desktop client update prompt, I can no longer Fetch Origin

### ISSUE THREAD

**Issue by michellepurcell** [desktop/desktop#4817]
## Description

![image](https://user-images.githubusercontent.com/19187948/40717496-70f6ccba-6404-11e8-93f0-6268f1d02dbd.png)

## Version

* GitHub Desktop:

![image](https://user-images.githubusercontent.com/19187948/40717524-8f17ef6c-6404-11e8-96c3-72ac08d83884.png)

* Operating system:

Windows 7 professional.

## Steps to Reproduce

1. I restarted the GH desktop client after noticing a prompt that there was a new update.
2. I made a change to content in a repo.
3. Now when I click fetch Origin I get the error above. I have not touched my properties, my password or anything.

### Expected Behavior

Fetch original to work as normal.

### Logs

[2018-05-30.desktop.production.log](https://github.com/desktop/desktop/files/2053675/2018-05-30.desktop.production.log)

**Comment by shiftkey** [comment]
@michellepurcell thanks for the report. We published an update a couple of hours ago to address a Git security issue, and I'd received a report about a potential SChannel issue, but I couldn't reproduce it myself.

Could you do me a huge favour and open a shell and run this command? This will help with troubleshooting and reporting this upstream:

```
$ git config --show-origin -l
```

**Comment by michellepurcell** [comment]
![image](https://user-images.githubusercontent.com/19187948/40718246-45c0d218-6407-11e8-875b-f5528b46d472.png)

**Comment by shiftkey** [comment]
@dscho I'm going to put together a test release now to downgrade to 2.17.0 and confirm this is specific to the latest build - is there any diagnostics or tracing here you'd like to gather to help get to the root cause of this?

**Comment by fschutt** [comment]
Is there any way to downgrade right now? I am getting a similar (but not the same error) when I try to push to origin:

![image](https://user-images.githubusercontent.com/12084016/40719504-193405b4-6414-11e8-8f3b-ffc79a90425e.png)

The file it's complaining about, exists, however:

![image](https://user-images.githubusercontent.com/12084016/40719624-72a64e5e-6414-11e8-95d0-4b160b18ec7d.png)

Maybe I should note that I installed git with the MinGW shell? This never happened before the update, however. Here is my git config:

```
file:"C:\\ProgramData/Git/config"       core.symlinks=false
file:"C:\\ProgramData/Git/config"       core.autocrlf=true
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    http.sslbackend=openssl
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    diff.astextplain.textconv=astextplain
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.clean=git-lfs clean -- %f
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.smudge=git-lfs smudge -- %f
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.process=git-lfs filter-process
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.required=true
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    credential.helper=manager
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    core.editor=nano.exe
file:"C:/Users/Felix Sch\303\274tt/.gitconfig"  user.email=felix.schuett@maps4print.com
file:"C:/Users/Felix Sch\303\274tt/.gitconfig"  user.name=Felix Schütt
file:"C:/Users/Felix Sch\303\274tt/.gitconfig"  filter.lfs.clean=git-lfs clean -- %f
file:"C:/Users/Felix Sch\303\274tt/.gitconfig"  filter.lfs.smudge=git-lfs smudge -- %f
file:"C:/Users/Felix Sch\303\274tt/.gitconfig"  filter.lfs.process=git-lfs filter-process
file:"C:/Users/Felix Sch\303\274tt/.gitconfig"  filter.lfs.required=true
file:"C:/Users/Felix Sch\303\274tt/.gitconfig"  core.autocrlf=false
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.symlinks=false
file:.git/config        core.ignorecase=true
file:.git/config        remote.origin.url=https://github.com/maps4print/azul.git
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.master.remote=origin
file:.git/config        branch.master.merge=refs/heads/master
```

Well, since the main purpose of the app is broken now, I have no other choice than to use the command line, sorry.

**Comment by fschutt** [comment]
@shiftkey yep, that seems to fix it, thanks.

**Comment by michellepurcell** [comment]
@shiftkey - Thanks Brendan. I get errors doing that:

![image](https://user-images.githubusercontent.com/19187948/40721518-91d38632-6411-11e8-8a76-b4ee3b166432.png)

**Comment by niik** [comment]
hey @michellepurcell, you'll need to `CD` into the directory of the repository you were having problems with first. As a shortcut you can click on the `Repository` menu in GitHub Desktop and then `Open in Command Line` and that should open a command line with the correct directory preselected.

**Comment by niik** [comment]
@Reahreic is also experiencing this (see #4821) and they're on Windows 10 so this problem is not constrained to a particular version of Windows.

**Comment by niik** [comment]
Just a quick update here. We're still investigating the best way to address this but preliminary findings indicate that this is a side-effect of https://github.com/curl/curl/commit/899630021153b2a26a43008cccc6620b6c3f9bbf (https://github.com/curl/curl/pull/1325) wherein support is added to curl's schannel interface (Win32 SSL) that allows it to parse a "traditional" certificate bundle file.

This allows curl to operate the same way on Windows as it does on macOS and Linux while leveraging the native Windows APIs for SSL/TLS support.

Prior to this update the only way you could use a CA bundle file was to switch back to the openssl backend.

Unfortunately this means that as long as either the Git config variable `http.sslCAInfo` or the environment variable `GIT_SSL_CAINFO` is set (*even if set to an empty string*) curl will bypass the normal Windows certificate chain validation and solely use the information in the ca bundle file.

GitHub Desktop ships with a stock CA bundle file in order for the openssl backend to work properly but that also means that the schannel backend will always use the bundle file and never look at the Certificate Store.

While we search for an optimal solution that will work for both backends I believe I have workaround for any users currently stuck and unable to push/pull/fetch from their enterprise instances.

1. Open a command line prompt (click on the Repository menu in GitHub Desktop and then Open in Command Line).
1. Copy and paste the following commands (and hit <kbd>Enter</kbd> after pasting to run them)
  * `"%LocalAppData%\GitHubDesktop\app-1.2.1\resources\app\git\cmd\git" config --unset --system http.sslCAInfo`
  * `"%LocalAppData%\GitHubDesktop\app-1.2.1\resources\app\git\cmd\git" config --unset --global http.sslCAInfo`
  * `"%LocalAppData%\GitHubDesktop\app-1.2.1\resources\app\git\cmd\git" config --global http.sslBackend schannel`

This workaround will be reset the next time we ship an update but hopefully by then we will have solved it properly. Note that if you're using a beta version of GitHub Desktop you'll need to substitute the `app-1.2.1` part in the paths with your version i.e. `app-1.2.1-beta1`.

**Comment by Reahreic** [comment]
@niik The workaround you posted is allowing me to sync and push again. (At lease for now) Thank you.

**Comment by nerdneha** [comment]
Hi @michellepurcell @fschutt, we just released 1.2.2 to address your and others' issues without requiring a workaround. Do you mind confirming that 1.2.2 addresses your issue?

**Comment by akrock** [comment]
Just did a fresh install of 1.2.2 and seeing:
```
fatal: unable to access 'https://github.com/XXX/': schannel: failed to open CA file 'C:/Users/Andrew/AppData/Local/GitHubDesktop/app-1.2.2/resources/app/git/mingw64/bin/curl-ca-bundle.crt': No such file or directory
```

referenced curl-ca-bundle.crt does not exist at the path specified on disk,

**Comment by shiftkey** [comment]
@akrock  thanks for the report. Could you open a shell, run this command and attach the output?

```
$ git config -l --show-origin
```

I'd like to confirm whether or not you still have a `http.sslCAInfo` entry defined at the global or system level that is unnecessary when using SChannel.

**Comment by michellepurcell** [comment]
@shiftkey & @nerdneha 

1.2.2 does not fix the problem. Same error occurs.
Thanks

**Comment by michellepurcell** [comment]
@niik - Thanks for your update and workaround. I tried this also but get the same error.

**Comment by shiftkey** [comment]
> Manually adding the curl-ca-bundle.crt at this path does indeed fix the issue, but it was not installed/distributed with the 1.2.2 release.

@akrock this configuration file wasn't included by Desktop - it probably lived at `C:\ProgramData\Git\config` and was related to an old Git installation.

**Comment by shiftkey** [comment]
@michellepurcell could you share a fresh log file? I'd like to confirm the error you're now seeing.

**Comment by michellepurcell** [comment]
[2018-05-31.desktop.production.log](https://github.com/desktop/desktop/files/2057609/2018-05-31.desktop.production.log)

**Comment by qq15870939565** [comment]
Configure it under the corresponding project

**Comment by qq15870939565** [comment]
@michellepurcell There is no setting at all：rebase.autosquash=true
http.sslcainfo

**Comment by qq15870939565** [comment]
C:\Users\Administrator>git config --list
core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
http.sslcainfo=d:/Program Files (x86)/Git/mingw32/ssl/certs/ca-bundle.crt
diff.astextplain.textconv=astextplain
rebase.autosquash=true
http.sslcainfo=d:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
user.name=
user.email=
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f

**Comment by michellepurcell** [comment]
qq15870939565 - Thanks but can you please clarify the name and path of the config file that I need to manually edit?

**Comment by shiftkey** [comment]
@michellepurcell the file I'm interested in, and I think @qq15870939565 is too, should be located at `C:\ProgramData\Git\config`. What's in there currently?

**Comment by michellepurcell** [comment]
@shiftkey & @qq15870939565 - Here you go... Thanks!

[core]
	symlinks = false
	autocrlf = true
	fscache = true
[color]
	diff = auto
	status = auto
	branch = auto
	interactive = true
[pack]
[help]
	format = html
[http]
	sslCAInfo = C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
[diff "astextplain"]
	textconv = astextplain
[rebase]
	autosquash = true

**Comment by shiftkey** [comment]
@michellepurcell this is the problem entry:

```
[http]
sslCAInfo = C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
```

If you delete those two lines, Desktop should be back to a happy place. I'm also curious if there's another tool which is adding these lines back in - are there any other tools you have installed that have Git integration?

**Comment by michellepurcell** [comment]
@shiftkey - Thank you Brendan. I am now back in business and working again!

**Comment by michellepurcell** [comment]
@shiftkey - Git command line, npm, Atom, markdown cli? Other than that, I don't recall installing any other tools relating to Git.

**Comment by shiftkey** [comment]
@michellepurcell those all seem fine. Please report back if you see that value return and affecting Desktop again.

**Comment by shiftkey** [comment]
@jpkessle are you able to open a shell and run this command too?

```
$ git config -l --show-origin
```

I think that value is what Desktop is providing, and on the next update it'll be added back again. It would be nice to confirm the root cause of your issue is the same as the others.

**Comment by jpkessle** [comment]
@shiftkey - Here is my output:
```
C:\>git config -l --show-origin
file:"C:\\ProgramData/Git/config"       core.symlinks=false
file:"C:\\ProgramData/Git/config"       core.autocrlf=true
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       http.sslcainfo=C:/Program Files/Git/ming
w64/ssl/certs/ca-bundle.crt
file:"C:\\ProgramData/Git/config"       diff.astextplain.textconv=astextplain
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    credential.helper=manage
r
file:C:/Users/username/.gitconfig      filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/username/.gitconfig      filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/username/.gitconfig      filter.lfs.process=git-lfs filter-proces
s
file:C:/Users/username/.gitconfig      filter.lfs.required=true
file:C:/Users/username/.gitconfig      user.name=Josh Kessler
file:C:/Users/username/.gitconfig      user.email=testuser@domain.com
```

**Comment by shiftkey** [comment]
@jpkessle thanks for the details - this is the problem entry that you need to remove from `C:\ProgramData\Git\config`:

```
file:"C:\\ProgramData/Git/config"       http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
```

You should restore that `schannel` config value that GitHub Desktop expects by ensuring this entry exists at "%LocalAppData%\GitHubDesktop\app-1.2.2\resources\app\git\mingw64\etc\gitconfig":

```
[http]
	sslBackend = schannel
```

**Comment by salihyalcin** [comment]
@shiftkey Hi Brendan, I'm facing this issue while upgrading to  1.2.2 version. When I want to clone one repository, I encountered with this message;

```
Cloning into 'D:\PersonelProjects\app-android-new'...
fatal: unable to access 'https://github.com/repoName/repoName-app-android-new.git/': schannel: failed to open CA file 'D:/Users/salih.yalcin/AppData/Local/GitHubDesktop/app-1.2.2/resources/app/git/mingw64/bin/curl-ca-bundle.crt': No such file or directory
```

Here is my `git $ git config -l --show-origin` result

```
file:"C:\\ProgramData/Git/config"       core.symlinks=false
file:"C:\\ProgramData/Git/config"       core.autocrlf=true
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       http.sslcainfo=/bin/curl-ca-bundle.crt
file:"C:\\ProgramData/Git/config"       sendemail.smtpserver=/bin/msmtp.exe
file:"C:\\ProgramData/Git/config"       diff.astextplain.textconv=astextplain
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:C:/Program Files/Git/mingw64/etc/gitconfig sslbackend=openssl
file:C:/Program Files/Git/mingw64/etc/gitconfig diff.astextplain.textconv=astext                                 plain
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.clean=git-lfs clean -                                 - %f
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.smudge=git-lfs smudge                                  -- %f
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.process=git-lfs filte                                 r-process
:...skipping...
file:"C:\\ProgramData/Git/config"       core.symlinks=false
file:"C:\\ProgramData/Git/config"       core.autocrlf=true
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       http.sslcainfo=/bin/curl-ca-bundle.crt
file:"C:\\ProgramData/Git/config"       sendemail.smtpserver=/bin/msmtp.exe
file:"C:\\ProgramData/Git/config"       diff.astextplain.textconv=astextplain
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:C:/Program Files/Git/mingw64/etc/gitconfig sslbackend=openssl
file:C:/Program Files/Git/mingw64/etc/gitconfig diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.required=true
file:C:/Program Files/Git/mingw64/etc/gitconfig credential.helper=manager
file:D:/Users/salih.yalcin/.gitconfig   core.autocrlf=true
file:D:/Users/salih.yalcin/.gitconfig   core.excludesfile=C:\Users\salih.yalcin\Documents\gitignore_global.txt
file:D:/Users/salih.yalcin/.gitconfig   filter.lfs.clean=git-lfs clean -- %f
file:D:/Users/salih.yalcin/.gitconfig   filter.lfs.smudge=git-lfs smudge -- %f
file:D:/Users/salih.yalcin/.gitconfig   filter.lfs.process=git-lfs filter-process
file:D:/Users/salih.yalcin/.gitconfig   filter.lfs.required=true
~
~
~
~
~
~
~
~
~
(END)
```

**Comment by shiftkey** [comment]
@salihyalcin thanks for the details - this is the problem entry that you need to remove from `C:\ProgramData\Git\config`:

```
file:"C:\\ProgramData/Git/config"       http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
```

**Comment by salihyalcin** [comment]
Thanks @shiftkey, here is my config file that you mentioned it. I also removed http.sscainfo line but problem not solved. 

```
[core]
	symlinks = false
	autocrlf = true
	fscache = true
[color]
	diff = auto
	status = auto
	branch = auto
	interactive = true
[pack]
[help]
	format = html
[http]
	sslCAinfo = /bin/curl-ca-bundle.crt
[sendemail]
	smtpserver = /bin/msmtp.exe

[diff "astextplain"]
	textconv = astextplain
[rebase]
	autosquash = true

```

**Comment by salihyalcin** [comment]
Okey I just remove lines below and everything works like a hero. 👍  Thanks 
 ```
[http]
	sslCAinfo = /bin/curl-ca-bundle.crt
```

**Comment by SidVal** [comment]
This "fatal error" still happening ...

I just installed new version 64 bits, and fatal error shows up :-1:

**Comment by shiftkey** [comment]
@SidVal have you had a chance to look at the output of this command on your machine?

```
$ git config -l --show-origin
```

It's hard to say more without knowing what error you're seeing is and what your current configuration is, but I think it's related to this configuration value being present:

```
file:"C:\ProgramData/Git/config" http.sslcainfo=/bin/curl-ca-bundle.crt
```

And removing these lines from `C:\ProgramData\Git\config` should do the trick:

```
[http]
   sslCAinfo = /bin/curl-ca-bundle.crt
```

**Comment by chutkoy** [comment]
fatal: unable to access 'https://github.com/lincolnvirus/lincolnvirus.github.io.git/': schannel: failed to open CA file 'C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt': No such process
данная проблема не решается. что происходит?

**Comment by chutkoy** [comment]
Found a simple solution to this problem: disable the antivirus. On my computer all the work spoils "Kaspersky". I will delete it.

**Comment by SidVal** [comment]
Yes @shiftkey I removed the line that @salihyalcin said [here](https://github.com/desktop/desktop/issues/4817#issuecomment-393796192), I just said that the error still showing up. I don't understand why this issue is closed 😐  (or there is some open issue about this problem?)

**Comment by shiftkey** [comment]
@SidVal if you don't believe this has been resolved please open a fresh issue and provide details about your setup, details about the errors you are seeing, and the diagnostic information I asked for above.

**Comment by ygor-lima** [comment]
I removed the line @shiftkey point, and it worked

[http]
	sslCAInfo = C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt

**Comment by alvaromon** [comment]
@shiftkey im experience this same issue but C:/ProgramData/Git/config doesnt have the [http] line everyone is saying they removed for it to work

**Comment by Ribhasingh** [comment]
ok

**Comment by Ribhasingh** [comment]
ok

**Comment by Ribhasingh** [comment]
add account

**Comment by shiftkey** [comment]
@alvaromon please open a fresh issue and provide details about your setup, details about the errors you are seeing, and the diagnostic information I asked for above - it might not be the exact same issue.

**Comment by subsoap** [comment]
Just posting to say I had the same issue after updating GitHub Desktop
```
github fatal: unable to access schannel: failed to open CA file No such file or directory
```

Deleting these lines in C:\ProgramData\Git\config as instructed seems to have solved it
```
[http]
   sslCAinfo = /bin/curl-ca-bundle.crt
```

**Comment by dhimant1** [comment]
On my Windows 10 Surface book, I had to remove the following line from the config file... 
	sslCAInfo = C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt

**Comment by BelarminoVicenzo** [comment]
I had the same error today when I download GHDesktop
there is not file or folder C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt

So I did what @shiftkey said, I delete those two lines.

[http]
sslCAInfo = C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt

**Comment by JACK-ZHANG-coming** [comment]
请问现在github destop最新版本对于这个问题已经解决了吗，我昨天下载了一个老版本的github destop也提示此问题，然后今天更新了一下，就没有出现了，其他的我也没做任何操作。

May I ask if this problem has been solved in the latest version of GitHub destop? I downloaded an old version of GitHub destop yesterday, which also suggested this problem, and then updated it today, but it did not appear, and I did nothin
