### ISSUE TITLE
Text select stopped working with 1.2.1-beta1 update

### ISSUE THREAD

**Issue by gemal** [desktop/desktop#4818]
I cant select any text in the diff window anymore.
Using 1.2.1-beta1 on Windows

**Comment by shiftkey** [comment]
@niik can you look into this? I can trigger this on macOS, and maybe we overlooked something in #4780...

**Comment by niik** [comment]
Seems like setting an explicit background color on the codemirror diff view prevents the text selection layer from rendering. The text will still get selected but you won't be able to see exactly what you select.

**Comment by niik** [comment]
Fixed in https://github.com/desktop/desktop/commit/e52dd0e9928a77c7abab74f6cf9d0a94d13fa51e, will land as part of #4810. Thanks for reporting this @gemal

**Comment by nerdneha** [comment]
Hi @gemal, we just released 1.2.2 and 1.2.2-beta1 to address your and others' issues. Do you mind confirming that one of those works with regards to syntax highlighted diffs for you?

**Comment by gemal** [comment]
Yes it works perfect. Thank you for a quick response and fix
