### ISSUE TITLE
Add support for other terminal apps

### ISSUE THREAD

**Issue by xgdgsc** [desktop/desktop#4820]
**Is your feature request related to a problem? Please describe.**
Currently on linux there is only an option to open the repo in gnome terminal.

**Describe the solution you'd like**
Support for other desktop terminal apps should be added, such as Konsole. An option to define the command would be more useful.

**Comment by shiftkey** [comment]
@xgdgsc thanks for the feedback. Konsole should be one of the supported shells - have you looked at the **File** | **Options...** menu and then the **Advanced** tab?

<img width="490" src="https://user-images.githubusercontent.com/359239/40760440-2e8d53e0-64da-11e8-81d4-394da5042ad8.png">

GNOME is the one that we default to, but there should be others supported if you have them installed:

<img width="435" src="https://user-images.githubusercontent.com/359239/40760467-48d181b8-64da-11e8-9d70-004fec2b58aa.png">

You can see the current list of these in our technical documentation: https://github.com/desktop/desktop/blob/master/docs/technical/shell-integration.md#linux

**Comment by xgdgsc** [comment]
Thanks. Konsole is in the option. But I have to switch to xterm and switch back to konsole and save to make it work. Before that there is only "open in gnome terminal" . Maybe it could be made more automatic.

**Comment by shiftkey** [comment]
@xgdgsc we should be defaulting to the first available shell (so the order they're declared), and I'm not sure what "more automatic" might mean here.

**Comment by xgdgsc** [comment]
I mean it should just show "open in konsole". Now I have to open the option and select xterm and select back to make it show konsole. Before that it shows gnome terminal.

**Comment by shiftkey** [comment]
@xgdgsc are you able to log this over in [my fork](https://github.com/shiftkey/desktop) so we can track this separately - I'm not aware of the other OSes doing this, and it'd be nice to dig into whether others are noticing this.

**Comment by xgdgsc** [comment]
https://github.com/shiftkey/desktop/issues/48 this seems to be the same issue.

**Comment by shiftkey** [comment]
@xgdgsc excellent - I'll close this out to avoid the duplication.
