### ISSUE TITLE
Add Xcode to list of supported 'open in' editors

### ISSUE THREAD

**Issue by stevemoser** [desktop/desktop#4825]
**Is your feature request related to a problem? Please describe.**
It takes too many clicks to open a project in Xcode after cloning it in GitHub Desktop

**Describe the solution you'd like**
Right click a repo to see an option to open in Xcode

**Describe alternatives you've considered**
Open in finder then open the project file.

**Teachability, Documentation, Adoption, Migration Strategy**
Just like they use the option to open a repo in vs code or atom.

It seems that there might be a current limitation in that Xcode requires a project file to open and current editor options will open any folder.

Related: https://github.com/desktop/desktop/pull/2039

**Comment by shiftkey** [comment]
> It seems that there might be a current limitation in that Xcode requires a project file to open and current editor options will open any folder.

The supported editors all use the command line interfaces provided to launch them by passing the path to the current repository. if XCode does have support for working in this way, it sounds like an ideal contribution to sit alongside the other editors.

Is this something you're able to investigate?

**Comment by stevemoser** [comment]
I'm not sure how to handle the logic of looking for the right project file to open. The simplest answer is `open *.xcodeproj` but it doesn't cover every case of course.

**Comment by shiftkey** [comment]
> I'm not sure how to handle the logic of looking for the right project file to open. The simplest answer is open *.xcodeproj but it doesn't cover every case of course.

Being able to open a specific file in a given editor (because it acts as an entry point to organize the source code) is beyond the scope of what's currently supported in Desktop. Visual Studio has a similar constraint, using `.sln` files to manage a repository containing multiple project files.

**Comment by stevemoser** [comment]
Looks like `xed .` or `open -a Xcode .` is the ticket.

https://twitter.com/_inside/status/1014186936049766400

**Comment by msztech** [comment]
@shiftkey Mind if I work on this?

**Comment by shiftkey** [comment]
@msztech not at all. Feel free to ask questions in here if things are unclear or if you encounter interesting issues.

**Comment by msztech** [comment]
Sounds great! Thanks! Will PR soon! @shiftkey

**Comment by msztech** [comment]
Xcode shows an error message if the path doesn't contain a Xcode project, and will show up the error message

> Could not open file (/path)

Should I check if the folder contains a Xcode project when rendering UI? (So hide the option to open in Xcode if there's no project files) Or maybe I can search for commands that capture that error or check if a specific application can open a path.

@shiftkey

**Comment by msztech** [comment]
@shiftkey Pull requested ;)

**Comment by msztech** [comment]
Revised version pull requested.

**Comment by msztech** [comment]
Will submit a new PR this week with ideas described in [this PR thread](https://github.com/desktop/desktop/pull/7369)

**Comment by sportshead** [comment]
@shiftkey This issue should be closed

**Comment by Calorion** [comment]
> I have already completed the implementation of this feature, but have encountered a small issue.
> 
> Xcode shows an error message if the path doesn't contain a Xcode project, and will show up the error message
> 
> > Could not open file (/path)
> 
> Should I check if the folder contains a Xcode project when rendering UI? (So hide the option to open in Xcode if there's no project files) Or maybe I can search for commands that capture that error or check if a specific application can open a path so we can try to present a customized dialog.

Ideally it would offer to create an Xcode project. If that's not possible, checking to see if the path includes an Xcode project and throwing an error if it doesn't would be better than the current behavior, which is somewhat confusing.
