### ISSUE TITLE
Can't clone repository after latest update

### ISSUE THREAD

**Issue by SprtanLuis** [desktop/desktop#4826]
## Version

* GitHub Desktop:

* Operating system:

**Comment by niik** [comment]
Hey @SprtanLuis, sorry about that! We're tracking the issue over in #4817 and we're getting ready to push an update that will hopefully address it. Please subscribe to #4817 to follow along.

If you need to push right now there's a workaround that you can try in https://github.com/desktop/desktop/issues/4817#issuecomment-393241303

**Comment by SprtanLuis** [comment]
Thank you! it works
