### ISSUE TITLE
Fatal: Unable to access 'https://github.cerner.com'

### ISSUE THREAD

**Issue by anessap** [desktop/desktop#4828]
Hello, 
I am trying to Push into Github using GitDesktop but keep getting a fatal error. I have been able to push for the past few months up until now. Any advice would be greatly appreciated. 
![error](https://user-images.githubusercontent.com/33668379/40745713-c02e7902-6447-11e8-973b-09bdfadef364.png)

**Comment by niik** [comment]
Hey @anessap, sorry about that! We're tracking the issue over in #4817 and we're getting ready to push an update that will hopefully address it. Please subscribe to #4817 to follow along.

If you desperately need to push right now there's a workaround that you can try in https://github.com/desktop/desktop/issues/4817#issuecomment-393241303

**Comment by anessap** [comment]
Ok thanks for the response!
