### ISSUE TITLE
Installing 1.2.2 causes this error: curl-ca-bundle.crt': No such file or directory

### ISSUE THREAD

**Issue by DanDixon** [desktop/desktop#4832]
## Description
Updating to 1.2.2 causes this error:

```fatal: unable to access 'https://github.com/GiantArmy/US.git/': schannel: failed to open CA file 'C:/Users/Dan/AppData/Local/GitHubDesktop/app-1.2.2/resources/app/git/mingw64/bin/curl-ca-bundle.crt': No such file or directory```

Reverting to 1.0.10 (an old copy I had on my computer) makes everything work again.

## Version

* GitHub Desktop: 1.2.2

* Operating system: Windows 10

## Additional Information
- Uninstalling and reinstalling didn't fix it.
- Error comes back if I let the 1.0.10 version update to 1.2.2.
- Deleting the whole folder (C:\Users\Dan\AppData\Local\GitHubDesktop) and reinstalling didn't fix it either.
- I also tried to just re-Clone the repository, that didn't work either. Same error right away.
- Currently having to reinstall 1.0.10 everytime I need to use it as it auto updates to 1.2.2.

![2018-05-30 19_29_23-start](https://user-images.githubusercontent.com/10511776/40759237-00c1366e-6446-11e8-9b89-74d2749ebd91.png)

**Comment by shiftkey** [comment]
@DanDixon thanks for the report. Could you open a shell, run this command and attach the output?

```
$ git config -l --show-origin
```

I'd like to confirm whether or not you still have a `http.sslCAInfo` entry defined globally that is unnecessary when using SChannel.

**Comment by DanDixon** [comment]
I think this is what you wanted:

file:"C:\\ProgramData/Git/config"       core.symlinks=false
file:"C:\\ProgramData/Git/config"       core.autocrlf=false
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       http.sslcainfo=/bin/curl-ca-bundle.crt
file:"C:\\ProgramData/Git/config"       sendemail.smtpserver=/bin/msmtp.exe
file:"C:\\ProgramData/Git/config"       diff.astextplain.textconv=astextplain
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      alias.c=commit
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      alias.co=checkout
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      alias.dt=difftool
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      alias.mt=mergetool
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      alias.praise=blame
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      alias.ff=merge --ff-only
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      alias.st=status
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      alias.sync=!git pull && git push
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      apply.whitespace=nowarn
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      core.symlinks=false
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      core.autocrlf=true
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      core.editor=gitpad
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      core.preloadindex=true
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      core.fscache=true
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      color.diff=auto
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      color.status=auto
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      color.branch=auto
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      color.interactive=true
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      color.ui=true
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      pack.packsizelimit=2g
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      help.format=html
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      http.sslcainfo=/ssl/certs/ca-bundle-ghfw.crt
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      diff.astextplain.textconv=astextplain
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      rebase.autosquash=true
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      credential.helper=!github --credentials
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      filter.ghcleansmudge.clean=cat
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      filter.ghcleansmudge.smudge=cat
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      push.default=upstream
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      diff.tool=vs2013
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      diff.algorithm=histogram
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      difftool.prompt=false
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      difftool.bc4.cmd="c:/program files (x86)/beyond compare 3/bcomp.exe" "$LOCAL" "$REMOTE"
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      difftool.p4.cmd="c:/program files/Perforce/p4merge.exe" "$LOCAL" "$REMOTE"
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      difftool.vs2012.cmd="c:/program files (x86)/microsoft visual studio 11.0/common7/ide/devenv.exe" '//diff' "$LOCAL" "$REMOTE"
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      difftool.vs2013.cmd="c:/program files (x86)/microsoft visual studio 12.0/common7/ide/devenv.exe" '//diff' "$LOCAL" "$REMOTE"
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      merge.tool=bc3
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      mergetool.prompt=false
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      mergetool.keepbackup=false
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      mergetool.bc3.cmd="c:/program files (x86)/beyond compare 3/bcomp.exe" "$LOCAL" "$REMOTE" "$BASE" "$MERGED"
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      mergetool.bc3.trustexitcode=true
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      mergetool.p4.cmd="c:/program files/Perforce/p4merge.exe" "$BASE" "$LOCAL" "$REMOTE" "$MERGED"
file:"C:\\Users\\Dan\\AppData\\Local\\GitHub\\PortableGit_f02737a78695063deace08e96d5042710d3e32db\\mingw32/etc/gitconfig"      mergetool.p4.trustexitcode=false
file:C:/Users/Dan/.gitconfig    user.name=dan
file:C:/Users/Dan/.gitconfig    user.email=dan@universesandbox.com
file:C:/Users/Dan/.gitconfig    core.autocrlf=true
file:C:/Users/Dan/.gitconfig    core.excludesfile=C:/Users/Dan/.gitignore
file:C:/Users/Dan/.gitconfig    filter.hawser.clean=git hawser clean %f
file:C:/Users/Dan/.gitconfig    filter.hawser.smudge=git hawser smudge %f
file:C:/Users/Dan/.gitconfig    filter.hawser.required=true
file:C:/Users/Dan/.gitconfig    filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/Dan/.gitconfig    filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/Dan/.gitconfig    filter.lfs.process=git-lfs filter-process
file:C:/Users/Dan/.gitconfig    filter.lfs.required=true
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.symlinks=false
file:.git/config        core.ignorecase=true
file:.git/config        remote.origin.url=https://github.com/GiantArmy/US.git
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.develop.remote=origin
file:.git/config        branch.develop.merge=refs/heads/develop
file:.git/config        branch.a20-StellarEvo.remote=origin
file:.git/config        branch.a20-StellarEvo.merge=refs/heads/a20-StellarEvo
file:.git/config        branch.a20-ECS.remote=origin
file:.git/config        branch.a20-ECS.merge=refs/heads/a20-ECS
file:.git/config        branch.planet-grid-ecs.remote=origin
file:.git/config        branch.planet-grid-ecs.merge=refs/heads/planet-grid-ecs
file:.git/config        branch.accuracy-ui.remote=origin
file:.git/config        branch.accuracy-ui.merge=refs/heads/accuracy-ui
file:.git/config        branch.release.remote=origin
file:.git/config        branch.release.merge=refs/heads/release
file:.git/config        branch.release-buildtools-changes.remote=origin
file:.git/config        branch.release-buildtools-changes.merge=refs/heads/release-buildtools-changes
file:.git/config        branch.NativeRewrite.remote=origin
file:.git/config        branch.NativeRewrite.merge=refs/heads/NativeRewrite
file:.git/config        branch.localization.remote=origin
file:.git/config        branch.localization.merge=refs/heads/localization
file:.git/config        branch.dev2017.remote=origin
file:.git/config        branch.dev2017.merge=refs/heads/dev2017
file:.git/config        branch.vr-virtualhands.remote=origin
file:.git/config        branch.vr-virtualhands.merge=refs/heads/vr-virtualhands
file:.git/config        branch.l10n_localization.remote=origin
file:.git/config        branch.l10n_localization.merge=refs/heads/l10n_localization
file:.git/config        branch.SimInfoPanel.remote=origin
file:.git/config        branch.SimInfoPanel.merge=refs/heads/SimInfoPanel
file:.git/config        branch.planet-grids-ecs-melting.remote=origin
file:.git/config        branch.planet-grids-ecs-melting.merge=refs/heads/planet-grids-ecs-melting
file:.git/config        branch.propertiesRevision.remote=origin
file:.git/config        branch.propertiesRevision.merge=refs/heads/propertiesRevision
file:.git/config        branch.sound_experiments.remote=origin
file:.git/config        branch.sound_experiments.merge=refs/heads/sound_experiments
file:.git/config        branch.change-resolution.remote=origin
file:.git/config        branch.change-resolution.merge=refs/heads/change-resolution

**Comment by shiftkey** [comment]
```
file:"C:\ProgramData/Git/config" http.sslcainfo=/bin/curl-ca-bundle.crt
```

@DanDixon can you remove this entry from the `C:\ProgramData\Git\config` file? I don't believe this is necessary any more, and should address the issue.

**Comment by DanDixon** [comment]
Yes... that fixed it (just renamed/deleted the whole file). Thank you very much @shiftkey

**Comment by vmiis** [comment]
I had same problem. What I did is copy the file   
C:\Users\xxx\AppData\Local\GitHubDesktop\app-1.2.2\resources\app\git\mingw64\ssl\certs\ca-bundle.crt to the directory
C:\Users\xxx\AppData\Local\GitHubDesktop\app-1.2.2\resources\app\git\mingw64\bin
and rename the ca-bundle.crt to curl-ca-bundle.crt
Hope this can help.

**Comment by ofek** [comment]
Yes this happened to me too just now. Perhaps we should document the fix.

**Comment by myfj** [comment]
this is what I am getting

file:"C:\\ProgramData/Git/config"       core.symlinks=false
file:"C:\\ProgramData/Git/config"       core.autocrlf=true
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       http.sslcainfo=G:/Git/mingw32/ssl/certs/                                                                                                                ca-bundle.crt
file:"C:\\ProgramData/Git/config"       diff.astextplain.textconv=astextplain
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:C:/Program Files/Git/mingw64/etc/gitconfig http.sslcainfo=C:/Program Files/                                                                                                                Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/mingw64/etc/gitconfig http.sslbackend=openssl
file:C:/Program Files/Git/mingw64/etc/gitconfig diff.astextplain.textconv=astext                                                                                                                plain
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.clean=git-lfs clean -                                                                                                                - %f
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.smudge=git-lfs smudge                                                                                                                 -- %f
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.process=git-lfs filte                                                                                                                r-process
:

**Comment by TheRealCatherine** [comment]
Ok I was dying trying to figure this out removing that line from the config file fixed it. Maybe the program should give a better warning message or offer to resolve it by editing the file automatically?

**Comment by shiftkey** [comment]
> Maybe the program should give a better warning message or offer to resolve it by editing the file automatically?

@TheRealCatherine we're discussing this behaviour with the upstream Git for Windows project and ways to improve things as part of a future update here https://github.com/git-for-windows/git/issues/1698

**Comment by erros84** [comment]
I'm getting this on Github Desktop 1.2.3. 

I removed: 
> [http]
> 	sslCAInfo = C:/Program Files (x86)/Git/mingw32/ssl/certs/ca-bundle.crt

From the config file and all works well now. I'm glad I found this thread.

**Comment by growthat** [comment]
I'm REALLY new to this, but having this issue. How do you remove/delete the file? Using the command line? Many thanks!!

**Comment by RuloAlpe** [comment]
I fixed it just comment on file:"C:\ProgramData/Git/config" this lines with #:

[http]
   sslCAinfo = /bin/curl-ca-bundle.crt
