### ISSUE TITLE
make "Select All" checkbox cleared by default on launch

### ISSUE THREAD

**Issue by xgdgsc** [desktop/desktop#4835]
**Is your feature request related to a problem? Please describe.**
Currently whenever I restart github desktop, it would be started in a status of checking all of the untracked files in that repo.

**Describe the solution you'd like**
The default should be not checking any file or remember the previous state. Because usually when you don' t have a complete gitignore file (and don' t bother to add in many cases) , you would get a lot of untracked files, and when I want to commit some file, I now have to uncheck all and then select the files I need after every restart. The default behavior for most git GUIs I used is checking no file.

**Comment by shiftkey** [comment]
@xgdgsc thanks for the feedback! I thought we had a discussion about this elsewhere, but I can't dig it up.

I'm going to tweak the title to indicate this is about the initial state of the "Select All" checkbox in the header of the Changes tab:

<img width="411" src="https://user-images.githubusercontent.com/359239/40811232-bff4b668-6573-11e8-91b7-8704836ad48e.png">

Some additional context:

 - this isn't related to untracked changes specifically - if you have any changes in the repository, they default being checked
 - it's still one-click to de-select all these changes
 - this isn't a value that's remembered across sessions - Desktop just defaults to `true` on launch

I don't have any strong opinions on this, but I'm open to hearing from others about their feels.

> The default behavior for most git GUIs I used is checking no file.

Can you share an example of this behaviour you've seen elsewhere, for reference?

**Comment by xgdgsc** [comment]
For example, sourcetree, gitkraken and smartgit doesn' t have that "checkbox" and when I want to commit I only have to launch the app,  select those changed files and do the commit, while I have to first uncheck all when using github desktop. They show the staging status more clearly, which is replaced by the checkbox here.

**Comment by shiftkey** [comment]
We're already tracking this in #1788 so I'll cross-reference these comments here. Please follow along with that issue.
