### ISSUE TITLE
fatal: unable to access curl-ca-bundle.crt

### ISSUE THREAD

**Issue by photonstorm** [desktop/desktop#4836]
## Description

GitHub Desktop updated itself today to 1.2.2. Since then any time I try to push, to any repo, I get a fatal warning error dialog appear saying: "fatal: unable to access (github repo url): schannel: failed to open CA file (AppData path to 1.2.2/resources/app/git/mingw64/bin/curl-ca-bundle.crt`: No such file or directory."

I checked and the file doesn't exist in that folder, or in any previous version folder (i.e. 1.2.1, 1.2.0).

## Version

* GitHub Desktop: 1.2.2
* Operating system: Microsoft Windows [Version 10.0.17134.48]

## Steps to Reproduce

Push to any GitHub hosted repo, public or private.

### Expected Behavior

It should push without erroring.

### Actual Behavior

fatal error dialog appears.

## Additional Information

No updates to Windows have taken place. Was working fine earlier today before it updated to 1.2.2.

**Comment by wieslawsoltes** [comment]
Have same issue:
```
2018-05-31T18:16:18.397Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
fatal: unable to access 'https://github.com/wieslawsoltes/Dock.git/': schannel: failed to open CA file 'C:/Users/Wiesiek/AppData/Local/GitHubDesktop/app-1.2.2/resources/app/git/mingw64/bin/curl-ca-bundle.crt': No such file or directory
```

**Comment by shiftkey** [comment]
@photonstorm @wieslawsoltes can you open a shell, run this command and attach the output?

```
$ git config -l --show-origin
```

I believe your issues is the same as https://github.com/desktop/desktop/issues/4832, because of an entry that looks like this:

```
file:"C:\ProgramData/Git/config" http.sslcainfo=/bin/curl-ca-bundle.crt
```

This entry is no longer valid (Git installations should not be adding this entry to this file) and removing it should address the issue for Desktop.

**Comment by wieslawsoltes** [comment]
@shiftkey Thanks it helped:
Removed:
```
[http]
	sslCAinfo = /bin/curl-ca-bundle.crt
```
from:
```
C:\ProgramData\Git\config
```

**Comment by duxingzhe** [comment]
Thanks, it works.

**Comment by shiftkey** [comment]
I'm going to close this out as a known issue with a workaround. Thanks for confirming this puts Desktop back in a good place!

**Comment by probeman** [comment]
Thank-you for the rapid response.  My config file had slightly different text on that line , but I deleted it anyway and after re-installing GHD, that fixed it!  Thanks much.

You people provide excellent service and a great app.

**Comment by Hu-Hongyan** [comment]
Thanks very much.  I got the same problem not only in GitHub Desktop but also in the git module with Atom. And both of them are resolved after remove the "sslCAinfo" from C:\ProgramData\Git\config file(may be need administrators authority).

**Comment by Der-Flip** [comment]
so deleting the [http]section in the config file didn't do it for me, i got a message derivig from windows that some server to check something was offline.

Anyways, long story short: I found a ca-bundle.crt in my lightroom directory. I copied that, created the path (program files/git/mingw64/ssl/certs) and pasted the lightroom ca-bundle.crt into this directory. Works a charm.

**Comment by zhaoM0** [comment]
ojbk

**Comment by geekcz** [comment]
@wieslawsoltes thanks!

**Comment by BhavishaVegada** [comment]
in my system C:\ProgramData\Git this folder not display, so what can i do
