### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by IvanS95** [desktop/desktop#4837]
GitHub Desktop says I may not have permission to push to a repository, that it may be archived or I'm not using the right account.

Thing is the repository is not archived and I'm using the right account. I was able to clone all the repositories from my organization and I can definitely commit and push from my terminal, but GitHub Desktop will not allow me to push at all.

![captura](https://user-images.githubusercontent.com/34747382/40791301-cf96505c-64bc-11e8-8199-6c631dd5d81c.PNG)

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

Does signing out and signing in again help?

**Comment by IvanS95** [comment]
Fixed it, it was my bad! I hadn't generated ssh keys for my Windows computer 😀 😆

**Comment by shiftkey** [comment]
@IvanS95 I'm glad you were able to resolve this!
