### ISSUE TITLE
Unhide files when discarding

### ISSUE THREAD

**Issue by browner12** [desktop/desktop#4839]
**Is your feature request related to a problem? Please describe.**

I recently discarded a hidden file (`.env.backup`) and later realized I needed it. I expected it to be in the trash, but when I looked in Finder, it was not shown.  After a little panic and digging, I realized it was still in the trash, but just not visible. I was able to go into the terminal and recover it.

**Describe the solution you'd like**

I would like Github Desktop to rename hidden files when moving them to the trash, so they are not hidden. On a Unix system this would be as simple as removing the leading `.`. I'm not sure what the procedure would be for Windows.

One drawback would be if you "recovered" the file from your trash you would need to remember to rename it and make it hidden again for your application to behave properly.

Another drawback could be naming collisions, although I believe the trash will rename files that are named the same as an existing file in the trash.

**Describe alternatives you've considered**

Alternative could be to add documentation, so it is apparent to people how to recover hidden files.

**Teachability, Documentation, Adoption, Migration Strategy**

The UI / behavior of Github Desktop would not change from an end user perspective.  We would simply update the scripts to rename hidden files prior to discarding them.

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

I don't think this is something we'd want to do mainly for the following reasons:
1. > One drawback would be if you "recovered" the file from your trash you would need to remember to rename it and make it hidden again for your application to behave properly.
2. The OS provides a way around this by giving you the option to show hidden files.

Now, there may be some edge case I've not thought about. If so, please share and we can work together to come up with a solution that does not require users to remember to re-rename things.

**Comment by shiftkey** [comment]
I'm in agreement with what @iAmWillShepherd is saying - Windows Explorer has the same behaviour to show/hide these "hidden" files:

- To find the menu:

<img width="1195" alt="screen shot 2018-06-01 at 7 12 58 am" src="https://user-images.githubusercontent.com/359239/40808775-8b2167cc-656b-11e8-82b4-132d691667aa.png">

 - The setting itself:

<img width="397" alt="screen shot 2018-06-01 at 7 11 14 am" src="https://user-images.githubusercontent.com/359239/40808788-984718b6-656b-11e8-87d0-b3e5a0aee0d3.png">

The drawbacks from the proposed approach are enough to be concerned about trying to be too clever when discarding changes in the app. 

> Alternative could be to add documentation, so it is apparent to people how to recover hidden files.

As a starting point I think some technical details about how our Discard Changes works would be good, to point people to. Some approximate topics to cover:

 - Where you can find this in the UI
 - How this works under the hood
 - How you can restore changes
 - A note about hidden files and how to enable this for your OS

This might be able to graduate to documentation on the website so it's more prominent, but that needs me to float this idea with another team to get them on board.

**Comment by shiftkey** [comment]
And here's how to show hidden files on macOS (you have a few options): https://ianlunn.co.uk/articles/quickly-showhide-hidden-files-mac-os-x-mavericks/

**Comment by browner12** [comment]
Thanks for taking a look at this guys.

Up until MacOS Sierra, showing and hiding hidden files in Finder on a Mac was clunky.  It's definitely much easier to toggle now.

My only concern is I would guess it's very uncommon to have hidden files shown in either Finder on the Mac or Explorer on Windows all the time, which means it is not readily apparent the hidden file you discarded **is** actually in your trash.

I think some technical documentation of how the Discard Changes works is a good idea.  This is definitely an edge case, but anything we can do to help people recover their files is good.

**Comment by vintagesucks** [comment]
@shiftkey FYI, you can just activate 4 to show hidden files.

![grafik](https://user-images.githubusercontent.com/13335308/40985702-f488f546-68e4-11e8-869f-218040be051c.png)

**Comment by shiftkey** [comment]
@vintagesucks cool, I just went to the classic way as I know that's where the setting is hiding for all Windows going back to at least Win7.
