### ISSUE TITLE
Support WebStorm as an external editor on Mac

### ISSUE THREAD

**Issue by kadishmal** [desktop/desktop#4841]
Creating a separate issue as instructed in https://github.com/desktop/desktop/issues/2487.

WebStorm:

- provides a command line shortcut (at least on macOS)
- allows to install the command line shortcut via `Tools -> Create Command Line Launcher...` [SO](https://stackoverflow.com/questions/26879172/how-to-open-webstorm-from-terminal).
- supports opening both file and directory from the command line

A PR for Brackets editor support can serve as a starting point https://github.com/desktop/desktop/pull/4608.

**Comment by iAmWillShepherd** [comment]
For anyone interested in tackling this, please see the [docs](https://github.com/desktop/desktop/blob/master/docs/technical/editor-integration.md) on editor integration.
