### ISSUE TITLE
Accepted lines shift upon document edited

### ISSUE THREAD

**Issue by patricktokeeffe** [desktop/desktop#4843]
## Description

Inclusion-selection mechanism gets tripped up by document editing. This is a hard one to describe.. after adding or removing a line to the document, the block *following* that edit will be modified wrt which lines are selected for inclusion in the next commit.

Original document with single line identified for inclusion in this commit:
![2018_05_31_16_09_06_github_desktop](https://user-images.githubusercontent.com/1348834/40813194-52f02884-64ee-11e8-86c1-7c86e797d0e1.png)

And after adding a single line, lines in the following 'block' are modified w.r.t whether they are included or not in this commit (ignore screenshot comment, only affects *next* block not all following):
![2018_05_31_16_09_36_github_desktop](https://user-images.githubusercontent.com/1348834/40813207-6cd57eca-64ee-11e8-863b-9ffda9eb866a.png)

:man_shrugging:  Doesn't seem to impact blocks beyond the first encountered after position of a change. Here we work in reverse.. (see our selection?):
![2018_05_31_16_28_09_github_desktop](https://user-images.githubusercontent.com/1348834/40813465-e01c236a-64ef-11e8-9300-0b438e31e4a1.png)

And after deleting that line, lines selected for inclusion change but only in the block immediately following that edit:
![2018_05_31_16_28_27_github_desktop](https://user-images.githubusercontent.com/1348834/40813476-f307d474-64ef-11e8-81c3-de3861612911.png)

Lines selected for inclusion on a particular commit should remain selected despite the addition or removal of lines elsewhere in the file. 

## Version

* GitHub Desktop: 1.2.2

* Operating system: Windows 7 Pro SP1 x64

### Expected Behavior

Line commit selections are only mutable by user

### Actual Behavior

Editing document mutates line commit selections

## Additional Information

Please see description

### Logs

None generated

**Comment by shiftkey** [comment]
@patricktokeeffe this feels very similar to #4720 - can you confirm?

**Comment by shiftkey** [comment]
@patricktokeeffe thanks, I'll add that context to #4720 so we can keep this discussion to one issue
