### ISSUE TITLE
"Clone repository" shortcuts does not fire (others seem to work fine)

### ISSUE THREAD

**Issue by rkmarks** [desktop/desktop#4845]
## Description

On windows in the client using the keyboard shortcut to open dialog box to clone a repo does not work. `ctrl+o` does work however adding shift does not work.  

## Version

* GitHub Desktop: 1.2.2

* Operating system: Windows 10

## Steps to Reproduce

1. Open Github desktop
2. Use `ctrl+shift+O` to attempt to open dialog to clone a repo

### Expected Behavior

Expect dialog box to open

### Actual Behavior

The dialog box does not open at all

### Logs

[2018-05-31.desktop.production.log](https://github.com/desktop/desktop/files/2060623/2018-05-31.desktop.production.log)

**Comment by shiftkey** [comment]
@rkmarks thanks for the report. Are you using a keyboard layout other than US English?

**Comment by rkmarks** [comment]
@shiftkey Nope using US English

**Comment by shiftkey** [comment]
@rkmarks strange. I had a few attempts at reproducing this but every time I was able to see the dialog.

Here's a demo using the On-Screen Keyboard:

![](https://user-images.githubusercontent.com/359239/40815821-7d9b7ebe-658c-11e8-8cc3-3657aa7457fc.gif)

What might I be missing to (not) trigger this?

**Comment by rkmarks** [comment]
Huh that is really weird. Perhaps my install is corrupt? I'll attempt a reinstall. Thanks for looking into it though @shiftkey

**Comment by shiftkey** [comment]
@rkmarks can you confirm after reinstall if all keyboard shortcuts are affected, or just the **File** | **Clone repository...** shortcut

**Comment by rkmarks** [comment]
@shiftkey just reinstalled and tried it again. only that keyboard shortcut fails. All others are working as intended

**Comment by rkmarks** [comment]
I would be happy to debug in dev tools. can you point me to the file where it picks up on the key events? @shiftkey

**Comment by j-f1** [comment]
@shiftkey could it have anything to do with the fact that we render the app menu ourselves?

**Comment by rkmarks** [comment]
@shiftkey I'm not entirely sure what happened but my shortcut to clone repository is now working 🤷‍♂️
