### ISSUE TITLE
Unable to set Co-Author in 1.2.2

### ISSUE THREAD

**Issue by thinkyhead** [desktop/desktop#4847]
## Description
The Co-Author field no longer searches Github or allows setting a Co-Author.

## Version

* GitHub Desktop:
1.2.2
* Operating system:
macOS 10.13.4

## Steps to Reproduce
1. Click Add Co-Authors to show the Co-Authors field
2. Enter the name of a GitHub account
3. Press return

### Expected Behavior
The account should be validated and accepted

### Actual Behavior
There is no response. The account is not validated, and no Co-Author is added.

## Additional Information
n/a

### Logs
n/a

**Comment by thinkyhead** [comment]
Yes, indeed, I do!

**Comment by shiftkey** [comment]
Looks like the Webpack 4 migration is generating some interesting markup around the `onAutocompleteUser` callback that Codemirror invokes when bundling:

```js
            this.onAutocompleteUser = (async(e,t,n)=>{
                const r = e.getDoc()
                  , i = r.getCursor()
                  , {from:o,to:s} = {
                    from: g(r = r, i = i, f, d),
                    to: g(r, i, f, p)
                }
```

Looks like the `const r = e.getDoc()` and subsequent `from: g(r = r, i = i, f, d)` is causing Chrome to (correctly) warn about reassigning `r`.

**Comment by johnhobbs72** [comment]
#4817
