### ISSUE TITLE
Github Desktop does not stay on top after selecting in Mission Control

### ISSUE THREAD

**Issue by mikew** [desktop/desktop#4850]
## Version

* GitHub Desktop: 1.2.2

* Operating system: 10.13.4

## Steps to Reproduce

1. Open Github Desktop and another application
2. Focus other application
3. Launch Mission Control
4. Select Github Desktop

### Expected Behavior

Github Desktop be on top of other windows

### Actual Behavior

Github desktop appears on top for a split second then loses focus

## Additional Information
https://gfycat.com/MisguidedGrayJackrabbit

**Comment by shiftkey** [comment]
@mikew I've not been able to reproduce this with the same version of macOS - my Mission Control layout is different to yours, could there be some setting I've not got right?

**Comment by nerdneha** [comment]
Hi @mikew, I'm going to close this out due to inactivity but if you can provide more details about the issue, we're happy to re-open and help!

**Comment by mikew** [comment]
Ah-ha, it's when "Assign To: All Desktops" is enabled.
