### ISSUE TITLE
Press Enter to automatically commit after setting a commit message

### ISSUE THREAD

**Issue by kenma9123** [desktop/desktop#4853]
**Is your feature request related to a problem? Please describe.**
The old github desktop app allows you to press the enter key right away after a commit message has been set. This will automatically commit the changes without having to click the "Commit" button. This new app does not do it. But there should be at least an option to do so.

**Describe the solution you'd like**
Make it react to the enter key to automatically commit when focused on the commit message input. 

**Describe alternatives you've considered**
If the above is not possible for general users. Have an option to enable/disable this feature from the settings.

**Teachability, Documentation, Adoption, Migration Strategy**
I think having option on interacting the UI is good. For me I like the way I can commit right away after typing the commit message without touching my mouse button to commit it. Consider it just like a normal online form :)

**Comment by j-f1** [comment]
Right now you can commit with (Cmd/Ctrl)+Enter.

**Comment by kenma9123** [comment]
I guess I didn't explored much. Thanks for that. Maybe this feature can be ignored then.
