### ISSUE TITLE
Latest update killed Fetch

### ISSUE THREAD

**Issue by probeman** [desktop/desktop#4857]
Github desktop warned me it would update on next restart.  When I relaunched it, the commit went well, but the fetch fails with:

fatal: unable to access 'https://probeman@bitbucket.org/probeman/probe-software-probe-for-epma.git/': schannel: failed to open CA file 'C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt': No such process

I tried uninstalling and re-installing Github Desktop, but the error is the same.

Interestingly the older Github for Windows still works fine.

Help!

**Comment by shiftkey** [comment]
@probeman please have a look at https://github.com/desktop/desktop/issues/4836#issuecomment-393662988 as I believe your setup is the same.
