### ISSUE TITLE
issue while publishing the repo

### ISSUE THREAD

**Issue by ramanichandran** [desktop/desktop#4865]
## Description

while publishing it is asking please upgrade your plan to create a new repository

## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@ramanichandran could it be because you have this checkbox checked?

<img width="518" src="https://user-images.githubusercontent.com/359239/40899200-ec625154-6804-11e8-8ade-ff9aff78451b.png">

**Comment by AngelLopezfundraiser** [comment]
Thanks

**Comment by AngelLopezfundraiser** [comment]
I really wish somebody could try to help me with this fundraiser cuz I'm not having no good luck

**Comment by shiftkey** [comment]
Closing this out as inactive. @ramanichandran if you're able to fill out the template to help us to troubleshoot the issue we're happy to revisit it.

**Comment by ramanichandran** [comment]
yes sorry for late.the issue has been resolved.kindly close the same.
