### ISSUE TITLE
Getting a Fatal Error when attempting to upload changes

### ISSUE THREAD

**Issue by rich-fts** [desktop/desktop#4868]
I am getting a fatal error when I attempt to update my repository as follows:

![image](https://user-images.githubusercontent.com/17622434/40935337-c49f6430-6805-11e8-8ff1-8ccf776f6e99.png)

I have tried uninstalling and re-installing the application, but I still get the error.  Help please.

**Comment by shiftkey** [comment]
@rich-fts thanks for the report - there's more details and a workaround in https://github.com/desktop/desktop/issues/4836#issuecomment-393662988 that should put you back to a good place!

**Comment by rich-fts** [comment]
Your solution worked.  Thank you very much
