### ISSUE TITLE
Forced to reload all repos into new GUI (this is crappy service !)

### ISSUE THREAD

**Issue by RustyButStillUseful** [desktop/desktop#4869]
Not impressed. 
You are shoving the new tool down our throats, but have not provide even a basic migration offering of having the new  tool pick up the existing repos.   Because YOU want me to use your new tool you are forcing me to take time out of my day to reverse engineer your product and figure out how to migrate all my repos.  
What is even worse I don't think it offers any improvement.  It is just clumsy and unhelpful, hiding all the functions that I found useful and giving nothing useful in exchange.

Seriously disappointed. 
This is exactly the sort of crap service I would expect from Microsoft not from a dev based service like GitHub.

Sloppy and anti-service is how I would describe this.
Unimpressed.

**Comment by shamrock77** [comment]
Right first of all who the hell is this and who do you think you are coming onto my site and using bad language about me when I don't know who you are so who the hell is this.

Get Outlook for Android

________________________________

**Comment by j-f1** [comment]
You can drag-and-drop repository folders onto the app to add them. (We tell you this at the bottom of the page you’re sent to from the old GitHub Desktop, and even have a ⚠️ icon so you notice it)
Also, when you first open the app,  we make it pretty easy to add a repository.

**Comment by lee-dohm** [comment]
Thank you for the feedback @RustyButStillUseful.

I can understand your frustration at being encouraged to upgrade to a product that doesn't cover your workflows as well. Additionally, with regard to migration, you should be able to drag and drop them onto the app's window to add them as described in https://github.com/desktop/desktop/issues/4600. If you'd like to work with us to make the new Desktop better, we'd definitely be interested in hearing [more constructive feedback.](https://github.community/t5/Studies-in-Community/Being-toxic-is-not-constructive-criticism/ba-p/8029)

-----

While I can understand your frustration, your comment is considered a violation of the [Desktop Code of Conduct](https://github.com/desktop/desktop/blob/master/CODE_OF_CONDUCT.md) as it was unprofessional. You may consider this an official warning.

**Comment by RustyButStillUseful** [comment]
j-f1 I have looked at the bottom of both the old and new tools and cannot find the reference that you mentions.  I looked on your help site and it all for the old tool, and I googled it and could not find any method other that moving the folders in the file system and that is not an option 
I will keep looking for the function. you refer to,

I am at a loss

**Comment by j-f1** [comment]
@RustyButStillUseful It’s at the bottom of [this page](https://desktop.github.com/upgrade/classic/).

**Comment by shamrock77** [comment]
You ever talk to me again like that you better hide you fucking twat

Get Outlook for Android

________________________________

**Comment by RustyButStillUseful** [comment]
Thank @j-f1 ,
   I was trying to find it in the on-line doco.  But din't find anything.

Thank you for the link 
I will try that to move the rest of the repos.

Off hand is there any reason that the migration was not built in to the install instead of making the customer jump through hoops.

**Comment by RustyButStillUseful** [comment]
Hi @lee-dohm ,
  Point taken.   I edited the title down.

Yes, I am super frustrated with the new UI and having to take time away from my work to deal with this what I see as unnecessary busy work.

**Comment by j-f1** [comment]
@RustyButStillUseful https://github.com/desktop/desktop/issues/186#issuecomment-389055403 has some details about why migration isn’t a feature right now.

**Comment by lee-dohm** [comment]
Thanks @RustyButStillUseful ... I'm on that one too :grinning:

**Comment by RustyButStillUseful** [comment]
@j-f1 
ok.   That explains a lot. =
Thank you
Keep well
