### ISSUE TITLE
Respect the "Options > All Desktops" flag in OSX

### ISSUE THREAD

**Issue by heliodor** [desktop/desktop#4870]
**Is your feature request related to a problem? Please describe.**
New version of the app (Electron) does not show up on all desktops/spaces in OSX. The native app used to do so properly. When using multiple desktops, right click the app icon in the dock and click on Options > All Desktops.

Instead of showing the app on the current desktop when I click the app icon in the dock, I get taken to the desktop on which the app is, which would be the default behavior when All Desktops is unchecked.

**Describe the solution you'd like**
I'd like this operating system feature to be handled by the app.

**Describe alternatives you've considered**
Not applicable

**Teachability, Documentation, Adoption, Migration Strategy**
Not applicable

**Comment by shiftkey** [comment]
I think this needs to be submitted to the Electron repository.

@desktop/electron I couldn't find an open issue, can you confirm?

**Comment by shiftkey** [comment]
@heliodor

> New version of the app (Electron) does not show up on all desktops/spaces in OSX. The native app used to do so properly. When using multiple desktops, right click the app icon in the dock and click on Options > All Desktops.

I was able to confirm this option works fine with the [Electron Quick Start](https://github.com/electron/electron-quick-start) project, so I tested this with Desktop and it seems to be set. Here's a quick GIF of it in action (note that I have already set this option):

![](https://user-images.githubusercontent.com/359239/41497924-3c283ade-7136-11e8-89e1-034b1afea7e0.gif)

> Instead of showing the app on the current desktop when I click the app icon in the dock, I get taken to the desktop on which the app is, which would be the default behavior when All Desktops is unchecked.

This is the part that I'm not clear on - if `All Desktops` is checked then you should see either the current GitHub Desktop window appear (if the app is already active) or a new GitHub Desktop window should appear on the current desktop (if the app is not active). And that's the behaviour I saw 

Are you able to provide a more detailed set of repro steps so I can see the same behaviour you're seeing here? Also, can you confirm which version of macOS you're currently running?

**Comment by heliodor** [comment]
Seems that my OS ended up in a bad state. I rebooted the laptop after the battery meter icon stopped working/updating. Now that I checked again, the Github app has no problem with the "All Desktops" setting, so I'm going to close this issue as nonreproducible.
