### ISSUE TITLE
Could not resolve host: github.com

### ISSUE THREAD

**Issue by shiv1490** [desktop/desktop#4872]
## Description

I create a new repository in my local and complete the changes . After that I opened my github desktop to push the changes to my GitHub repo. As soon as i click the publish button it gave me this error

## Version

* GitHub Desktop:1.22

* Operating system: windows 10 64 bit

### Expected Behavior
Should publish new repository

### Actual Behavior
gave this error -  fatal: unable to access 'https://github.com/shiv1490/Burger-Builder.git/': Could not resolve host: github.com

**Comment by niik** [comment]
Hey @shiv1490. This error message seems to indicate a connectivity problem. Do you currently have any antivirus software installed other than the default antivirus that ships with Windows?

Additionally, are you using a proxy server to access the internet? Git requires special configuration to work behind proxy servers, see https://github.com/desktop/desktop/issues/1998, #2789

**Comment by shiv1490** [comment]
Hi All,
Issue is resolved now. This was happening because I was behind a corporate proxy. I used below commnad to resolve the issue

git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080 

Thanks

**Comment by JawharMbarek** [comment]
@shiv1490  :+1:
the command worked with me.
git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080

**Comment by SethuSP** [comment]
> Tried the following
> **git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080** and
> **git config --global --unset http.proxy**
> **git config --global --unset https.proxy**
> but none seems to work for me; could it be a possible internet strength isssue?

I too tried the same. It does not work for me as well and i do not think it is related to internet strength. Not sure why.

**Comment by JCDigital27** [comment]
This method works for me!
reboot>
then establish connection to internet...
then>
#git config --global --unset http.proxy
#git config --global --unset https.proxy
then>
#git clone https://(.........................................).git

**Comment by davidbeery** [comment]
Why does this fix work?
What is it about the http/s.proxy global config that interferes with the internet connection?

**Comment by steveward** [comment]
@davidbeery The `--unset` flag can fix the issue where Git will attempt to establish a connection through an invalid proxy configuration (i.e. the user is actually not behind a proxy), which causes Git operations to error out. If you are using a proxy then you will want to keep that proxy configuration line in order to ensure Git operations work successfully.

**Comment by RoderickKennedy** [comment]
@JCDigital27 i have the same problem, whe i use the solution,  but it not work?
when i use curl -I https://github.com, it show the error.
curl: (6) Could not resolve host: github.com; Unknown error

**Comment by manishak-kumari** [comment]
> @shiv1490 👍
> the command worked with me.
> git config --global http.proxy http://proxyuser:proxypwd@proxy.servers
should i copy and paste the same line given by you above or i need to do some change?

**Comment by sadkisoft** [comment]
Please i need a help
My code is : 
$UserID="sadkisoft@gmail.com";
$Signature="253c69d31f785f88973b5d6d418831a3ef934d29";
$Action="GetProducts";
$Format="JSON";
$VersionAPI="V2.7.11";
$url="https://api.sellercenter.net/?Action=GetProducts&UserID=***&Signature=***&Format=JSON";
		$ch = curl_init($url);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($ch, CURLOPT_URL, $url); 
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0); 
		curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
		curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);
		curl_setopt($ch, CURLOPT_TIMEOUT, 5);
		curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
		curl_setopt($ch, CURLOPT_MAXREDIRS, 3);
		curl_setopt($ch, CURLOPT_HTTPHEADER, array('Accept: application/json'));
		
		$parsee = curl_exec($ch);
		$result=json_decode($parsee,false); 
		$errno = curl_errno($ch);
		$errmsg = curl_error($ch);
		$httpcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
		curl_close($ch);
		var_dump($errno, $errmsg, $httpcode, $parsee);
the result is :+1: 
int 6
string 'Could not resolve host: api.sellercenter.net; Host not found' (length=60)
int 0
boolean false

**Comment by steveward** [comment]
@sadkisoft this issue tracker is for GitHub Desktop -- if you have specific programming questions I'd recommend our [Community Forum](https://github.community/t5/Programming-Help-and-Discussion/bd-p/programming) or StackOverflow.

**Comment by keshri1** [comment]
> Check [this](https://github.com/Homebrew/brew/issues/1414) out as well. it helped me.
> 
> ```
> git config --global --unset http.proxy 
> git config --global --unset https.proxy
> ```
This helped buddy

**Comment by Preethi-Sanga** [comment]
git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080
its not worked for me

**Comment by pdkproitf** [comment]
> Check [this](https://github.com/Homebrew/brew/issues/1414) out as well. it helped me.
> 
> ```
> git config --global --unset http.proxy 
> git config --global --unset https.proxy
> ```
Thank @imsrgadich. it worked for me.

**Comment by Vadimkin448** [comment]
> Check [this](https://github.com/Homebrew/brew/issues/1414) out as well. it helped me.
> 
> ```
> git config --global --unset http.proxy 
> git config --global --unset https.pro

**Comment by jlcalderon** [comment]
Hi everybody! 

I had the same problem and I solved differently. First, I was getting the error, because I created the Local repo and initialized before I had an online instance of the repo. Then manually, online in my git hub account created the repo to push my local files on it. When I tried to push the local repo into the online I got the error.

Solution:
1. Remove the origin to clear out the initialization by:
git remote rm origin

2. Then try again the command lines: 
git remote add "your link to the repo".git
git push -u origin master

Hope this help somebody.

**Comment by Harshada-github** [comment]
> @shiv1490 
> the command worked with me.
> git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080

Did it work for Ubuntu

**Comment by steveward** [comment]
@Harshada-github the proxy configuration command will work for Ubuntu.

**Comment by emmanuellekamwa** [comment]
All the solutions you proposed did not work for me. Anything else to propose?

**Comment by steveward** [comment]
@emmanuellekamwa are you encountering the `could not resolve host` error? Are you behind a firewall or proxy server? It would also be helpful to know the specific actions you have already taken to try and resolve the issue.

**Comment by emmanuellekamwa** [comment]
@steveward Yes I have that error and I am behind a firewall

**Comment by ayushshaz** [comment]
It worked for me when I used "service apache2 stop" ;-)

**Comment by teratron-git** [comment]
Hi!

I have the same problem with corporate proxy 'Could not resolve host: github.com'.
The main problem in my case is that my proxy adjusted via script automatically like that:
`http://pacproxy.com/proxy.pac`
In that case i don't have any login/pass for proxy autorization.

How can I adjust that?
Any info appreciated.

**Comment by Djotchuang** [comment]
> git config --global --unset http.proxy

Thanks. This worked for me.

**Comment by casualhuman** [comment]
May be totally unrelated tho, but if someone comes across this issue and is trying to push in WSL try installing git base and do it from there works for me

**Comment by Nuevoprogramador** [comment]
> May be totally unrelated tho, but if someone comes across this issue and is trying to push in WSL try installing git base and do it from there works for me

Hi I am trying to resolve this issue WSL2  ubuntu 18.04  and nothing  seems to work in order to be able to commit  or comunicate with github.com    now the fatal message is  Could not resolve proxy : proxy.server.com   ...  Can you please tell me what you did ... thanks in advance

**Comment by MiChaelinzo** [comment]
It does work well for me after restarting the app

**Comment by cheseren** [comment]
> git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080

This worked for me.

**Comment by Nuevoprogramador** [comment]
Thank you

**Comment by abhishek21nair** [comment]
Hi All facing the same issue, tried all of the above solutions, did not work for me.

below is my JSON file.

{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=7.4.0",
        "laravel/framework": "^7.24",
        "laravel/tinker": "~2.0",
        "laravelcollective/html": "~6.1",
        "milon/barcode": "^7.0",
        "maatwebsite/excel": "~3.1.21",
        "fideloper/proxy": "^4.2",
        "laravel/ui":"^2.0",        
        "fruitcake/laravel-cors": "^2.0"
    },
    "require-dev": {
        "composer/composer": "^1.10",
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "^1.9",
        "mockery/mockery": "^1.0",
        "phpunit/phpunit": "^8.5"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}

I have tried disabling antivirus also as well ass tried proxy command which is given above.

error:

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

J:\wamp64\www\Upgrade>composer diagnose

Deprecated: Directive 'track_errors' is deprecated in Unknown on line 0
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: FAIL
[Composer\Downloader\TransportException] Could not resolve host: api.github.com
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: (available)
Dev Public Key Fingerprint: (available)
OK
Checking composer version: OK
Composer version: 2.0.0-alpha3
PHP version: 7.4.9
PHP binary path: J:\wamp64\bin\php\php7.4.9\php.exe
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020

J:\wamp64\www\Upgrade>

Any help will be appreciated, Thanks in Advance.

**Comment by Rhmd03** [comment]
What
Im from indonesia

Pada tanggal 28 Agt 2020 14:44, "abhishek21nair" <notifications@github.com>
menulis:

Hi All facing the same issue, tried all of the above solutions, did not
work for me.

below is my JSON file.

{
"name": "laravel/laravel",
"description": "The Laravel Framework.",
"keywords": [
"framework",
"laravel"
],
"license": "MIT",
"type": "project",
"require": {
"php": ">=7.4.0",
"laravel/framework": "^7.24",
"laravel/tinker": "~2.0",
"laravelcollective/html": "~6.1",
"milon/barcode": "^7.0",
"maatwebsite/excel": "~3.1.21",
"fideloper/proxy": "^4.2",
"laravel/ui":"^2.0",
"fruitcake/laravel-cors": "^2.0"
},
"require-dev": {
"composer/composer": "^1.10",
"filp/whoops": "~2.0",
"fzaninotto/faker": "^1.9",
"mockery/mockery": "^1.0",
"phpunit/phpunit": "^8.5"
},
"autoload": {
"classmap": [
"database"
],
"psr-4": {
"App\": "app/"
}
},
"autoload-dev": {
"psr-4": {
"Tests\": "tests/"
}
},
"scripts": {
"post-root-package-install": [
"php -r "file_exists('.env') || copy('.env.example', '.env');""
],
"post-create-project-cmd": [
"php artisan key:generate"
],
"post-install-cmd": [
"Illuminate\Foundation\ComposerScripts::postInstall"
],
"post-update-cmd": [
"Illuminate\Foundation\ComposerScripts::postUpdate"
],
"post-autoload-dump": [
"Illuminate\Foundation\ComposerScripts::postAutoloadDump",
"@php <https://github.com/php> artisan package:discover"
]
},
"config": {
"preferred-install": "dist",
"sort-packages": true,
"optimize-autoloader": true
}
}

I have tried disabling antivirus also as well ass tried proxy command which
is given above.

error:

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

J:\wamp64\www\Upgrade>composer diagnose

Deprecated: Directive 'track_errors' is deprecated in Unknown on line 0
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: FAIL
[Composer\Downloader\TransportException] Could not resolve host:
api.github.com
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: (available)
Dev Public Key Fingerprint: (available)
OK
Checking composer version: OK
Composer version: 2.0.0-alpha3
PHP version: 7.4.9
PHP binary path: J:\wamp64\bin\php\php7.4.9\php.exe
OpenSSL version: OpenSSL 1.1.1g 21 Apr 2020

J:\wamp64\www\Upgrade>

Any help will be appreciated, Thanks in Advance.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/desktop/desktop/issues/4872#issuecomment-682379853>, or
unsubscribe

**Comment by ishoomsky** [comment]
Make sure Wi-Fi is on.

**Comment by lucianoschirmer** [comment]
> Oi pessoal!
> 
> Eu tive o mesmo problema e resolvi de forma diferente. Primeiro, estava recebendo o erro, porque criei o repositório local e inicializei antes de ter uma instância online do repo. Em seguida, manualmente, online em minha conta git hub criei o repo para enviar meus arquivos locais nele. Quando tentei enviar o repositório local para o online, recebi o erro.
> 
> Solução:
> 
> 1. Remova a origem para limpar a inicialização por: 
>    git remote rm origin
> 2. Em seguida, tente novamente as linhas de comando: 
>    git remote add "seu link para o repo" .git 
>    git push -u origin master
> 
> Espero que isso ajude alguém.

Tks!

**Comment by mariuspet89** [comment]
> Hi All,
> Issue is resolved now. This was happening because I was behind a corporate proxy. I used below commnad to resolve the issue
> 
> git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080
> 
> Thanks

Thank you. This answer worked for me as well!! Thaks a LOT !

**Comment by yuliannybetancourt** [comment]
> git config --global --unset https.proxy

funciona.

**Comment by Nakilon** [comment]
The issue fixed for me by upgrading Docker from version 2 to 3.

**Comment by pchiluveru** [comment]
The same issue i also faced while cloning the repo. i just tried out with below cmds and its worked for me 
    git credential-manager uninstall
    git credential-manager install

**Comment by faizaslam11** [comment]
### I solved this error by using below command

`git config --global --unset http.proxy` 👍

**Comment by Anindita2611** [comment]
Ok it helped

**Comment by sanim35** [comment]
I tried this but doesn't work.

──(sanim㉿kali)-[~]
└─$ git clone https://github.com/ZerBea/hcxdumptool.git                   130 ⨯

Cloning into 'hcxdumptool'...
fatal: unable to access 'https://github.com/ZerBea/hcxdumptool.git/': Could not resolve host: github.com
                                                                                
┌──(sanim㉿kali)-[~]
└─$ git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080
                                                                                
┌──(sanim㉿kali)-[~]
└─$ git clone https://github.com/ZerBea/hcxdumptool.git
Cloning into 'hcxdumptool'...
fatal: unable to access 'https://github.com/ZerBea/hcxdumptool.git/': Could not resolve proxy: proxy.server.com
                                                                                
┌──(sanim㉿kali)-[~]
└─$ git config --global --unset http.proxy                                128 ⨯
                                                                                
┌──(sanim㉿kali)-[~]
└─$ git clone https://github.com/ZerBea/hcxdumptool.git
Cloning into 'hcxdumptool'...
fatal: unable to access 'https://github.com/ZerBea/hcxdumptool.git/': Could not resolve host: github.com
                                                                                
┌──(sanim㉿kali)-[~]
└─$ git config --global --unset https.proxy                               128 ⨯
                                                                                
┌──(sanim㉿kali)-[~]
└─$ git clone https://github.com/ZerBea/hcxdumptool.git                     5 ⨯
Cloning into 'hcxdumptool'...
fatal: unable to access 'https://github.com/ZerBea/hcxdumptool.git/': Could not resolve host: github.com
                                                                                
┌──(sanim㉿kali)-[~]
└─$ git config --global --unset http.proxy                                128 ⨯
                                                                                
┌──(sanim㉿kali)-[~]
└─$ git clone https://github.com/ZerBea/hcxdumptool.git                     5 ⨯
Cloning into 'hcxdumptool'...
fatal: unable to access 'https://github.com/ZerBea/hcxdumptool.git/': Could not resolve host: github.com

**Comment by faizaslam11** [comment]
> 
> I tried this but doesn't work.
> 
> ──(sanim㉿kali)-[~]
> └─$ git clone https://github.com/ZerBea/hcxdumptool.git                   130 ⨯
> 
> Cloning into 'hcxdumptool'...
> fatal: unable to access 'https://github.com/ZerBea/hcxdumptool.git/': Could not resolve host: github.com
>                                                                                 
> ┌──(sanim㉿kali)-[~]
> └─$ git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080
>                                                                                 
> ┌──(sanim㉿kali)-[~]
> └─$ git clone https://github.com/ZerBea/hcxdumptool.git
> Cloning into 'hcxdumptool'...
> fatal: unable to access 'https://github.com/ZerBea/hcxdumptool.git/': Could not resolve proxy: proxy.server.com
>                                                                                 
> ┌──(sanim㉿kali)-[~]
> └─$ git config --global --unset http.proxy                                128 ⨯
>                                                                                 
> ┌──(sanim㉿kali)-[~]
> └─$ git clone https://github.com/ZerBea/hcxdumptool.git
> Cloning into 'hcxdumptool'...
> fatal: unable to access 'https://github.com/ZerBea/hcxdumptool.git/': Could not resolve host: github.com
>                                                                                 
> ┌──(sanim㉿kali)-[~]
> └─$ git config --global --unset https.proxy                               128 ⨯
>                                                                                 
> ┌──(sanim㉿kali)-[~]
> └─$ git clone https://github.com/ZerBea/hcxdumptool.git                     5 ⨯
> Cloning into 'hcxdumptool'...
> fatal: unable to access 'https://github.com/ZerBea/hcxdumptool.git/': Could not resolve host: github.com
>                                                                                 
> ┌──(sanim㉿kali)-[~]
> └─$ git config --global --unset http.proxy                                128 ⨯
>                                                                                 
> ┌──(sanim㉿kali)-[~]
> └─$ git clone https://github.com/ZerBea/hcxdumptool.git                     5 ⨯
> Cloning into 'hcxdumptool'...
> fatal: unable to access 'https://github.com/ZerBea/hcxdumptool.git/': Could not resolve host: github.com
> 

https://stackoverflow.com/questions/20370294/git-could-not-resolve-host-github-com-error-while-cloning-remote-repository-in 
Check this link!

**Comment by MargelGC** [comment]
> Probé la siguiente
> **configuración de git --global http.proxy [http: // proxyuser: proxypwd@proxy.server.com: 8080](http://proxyuser:proxypwd@proxy.server.com:8080)** y
> **git config --global --unset http.proxy **
> **git config --global --unset https.proxy**
> pero ninguno parece funcionar para mí; ¿Podría ser un posible problema de fortaleza de Internet?

Me funciono al 100% tenia horas buscandole solución. GRACIAS

**Comment by MANOJ-M-01** [comment]
`git config --global --unset http.proxy`

make sure to quit and restart terminal.

**Comment by MargelGC** [comment]
Gracias bro

**Comment by darthnithin** [comment]
This happened for me when I tried to `git clone` while i was in wsl. I exited and it fixed it.

**Comment by itsanji** [comment]
I have no idea why but restart helped me (?)

**Comment by 4sskick** [comment]
I've tried many tips on here. But nothing worked. I'm not using proxy company, just regular internet connection. I give up. Using git bash or git gui helped me.

**Comment by Milan-rawat** [comment]
> Check [this](https://github.com/Homebrew/brew/issues/1414) out as well. it helped me.
> 
> ```
> git config --global --unset http.proxy 
> git config --global --unset https.proxy
> ```

Thanks @imsrgadich  It also worked for me

**Comment by zacraoui** [comment]
Hii !

 I tried all but doesn't work. 
this method resolve my issue https://reactgo.com/github-password-authentication-removed/

Hope this help somebody.

**Comment by AnghelAndrei28** [comment]
None of the solutions above worked for me, but a full restart of the PC solved everything.

**Comment by AbdullahAljojo** [comment]
> All the solutions you proposed did not work for me. Anything else to propose?

Me Too

**Comment by kdsinghapp** [comment]
I did this:
first I ran this command as it is(Here, I did not changed usename and password and used it as it is): 
```
git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080
```
then I ran these two commands:
```
git config --global --unset http.proxy 
git config --global --unset https.proxy
```

**Comment by mufaddalhamidofficial** [comment]
I did this: 
first I ran this command as it is(Here, I did not changed usename and password and used it as it is): 
```
git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080 
```
then I ran these two commands: 
```
git config --global --unset http.proxy 
git config --global --unset https.proxy
```

**Comment by naeeshopofficial** [comment]
![image](https://user-images.githubusercontent.com/91562386/138440622-81bd4c98-5ccf-4190-9ca7-17ca78367364.png)
I'm stiill getting this error
after running all the command

**Comment by steveward** [comment]
@naeeshopofficial are you actually behind a proxy, or are you wanting to remove your proxy settings? It looks like there is an issue with your `.gitconfig`. I would run `git config --global --edit` and remove the `http.proxy` sections, and then try re-adding your proxy again. Make sure you enter your proxy username and password if needed.

**Comment by Crazyokd** [comment]
The problem no longer occurs after restart

**Comment by nbrucepro** [comment]
Restart will remove a problem

**Comment by Ana12-hub** [comment]
> Hi All, Issue is resolved now. This was happening because I was behind a corporate proxy. I used below commnad to resolve the issue
> 
> git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080
> 
> Thanks

**Comment by Ana12-hub** [comment]
It does not work to me. May anyone help?

Error:
Could not resolve proxy: proxy.server.com

**Comment by steveward** [comment]
@Ana12-hub If you are behind a proxy you need to replace the `proxyuser`, `proxypwd`, and `proxy.server` values in the config command with the correct values for your proxy server. You can rerun the command again to configure it. Let me know if you have any questions.

**Comment by Ana12-hub** [comment]
Thank you Steve. However, it still unresolved.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by steveward** [comment]
@Ana12-hub can you confirm that you are behind a proxy? The `could not resolve host` error can be caused by a number of things, including antivirus software or a restrictive firewall. Could either of those be a possible cause?

**Comment by sarimmehdi** [comment]
None of these solutions work on Ubuntu 20.04, if anyone finds a solution to these for that OS, then please post here

**Comment by alicezou-ventures** [comment]
Disconnect the VPN and Reconnect the VPN resolved the connection issue for me.

**Comment by chicacode** [comment]
> I have no idea why but restart helped me (?)

Me too

**Comment by mikekosulin** [comment]
In case you get this error even on `curl -I https://github.com` – it's all about DNS. 
You can clear your DNS cache to resolve this issue

linux:
`sudo systemd-resolve --flush-caches`
mac:
`sudo killall -HUP mDNSResponder`

**Comment by miguelgargallo** [comment]
> This method works for me! reboot> then establish connection to internet... then> #git config --global --unset http.proxy #git config --global --unset https.proxy then> #git clone https://(.........................................).git

Thanks

**Comment by nxuanthanh** [comment]
> Disconnect the VPN and Reconnect the VPN resolved the connection issue for me.

thank you i fixed my problem

**Comment by gcizman** [comment]
> Hi everybody!
> 
> I had the same problem and I solved differently. First, I was getting the error, because I created the Local repo and initialized before I had an online instance of the repo. Then manually, online in my git hub account created the repo to push my local files on it. When I tried to push the local repo into the online I got the error.
> 
> Solution:
> 
> 1. Remove the origin to clear out the initialization by:
>    git remote rm origin
> 2. Then try again the command lines:
>    git remote add "your link to the repo".git
>    git push -u origin master
> 
> Hope this help somebody.

I applied this solution and works fine, you are star man. thanks although tried all the above, eventually this one was my main killer solution after so many different attempts and hours

**Comment by DTechBloKe** [comment]
![Uploading git error .png…]()
Please anyone can help me out? I've tried all the solutions here non of them worked😢

**Comment by DTechBloKe** [comment]
![Uploading git error .png…]()
Please anyone can help me out? I've tried all the solutions here non of them worked😢

**Comment by DTechBloKe** [comment]
Please anyone can help me out? I've tried all the solutions here non of them worked😢

**Comment by DTechBloKe** [comment]
Please anyone can help me out? I've tried all the solutions here non of them worked😢
![Uploading git error .png…]()

**Comment by DTechBloKe** [comment]
Please anyone can help me out? I've tried all the solutions here non of them worked😢
![Uploading git error .png…]()

**Comment by steveward** [comment]
@DTechBloKe if you can upload your log file in a comment on this issue that should give some more information about the error you are experiencing.

**Comment by BlaCBunJEE** [comment]
> 

worked for me

**Comment by manojkumar1919** [comment]
not worked for me

**Comment by emmaudeji** [comment]
> Tried the following **git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080** and **git config --global --unset http.proxy** **git config --global --unset https.proxy** but none seems to work for me; could it be a possible internet strength isssue?

Check again. This worked for me 

git config --global --unset http.proxy

**Comment by untilhamza** [comment]
Tried everything here and it failed.

This helped me.
git config --local credential.helper

https://www.edureka.co/community/66457/fatal-unable-to-access-could-not-resolve-host-github#:~:text=git%20config%20%2D%2Dlocal%20credential.helper%20%22%22

**Comment by arex123** [comment]
simply try reconnecting to your wifi,
 It worked for me,

source:
https://stackoverflow.com/a/34777941/16687503

**Comment by KendiJ** [comment]
> Check [this](https://github.com/Homebrew/brew/issues/1414) out as well. it helped me.
> 
> ```
> git config --global --unset http.proxy 
> git config --global --unset https.proxy
> ```

Thanks, this worked well on my M2

**Comment by Kellynjenga** [comment]
How can i solve this fatal: unable to access 'https://github.com/ultrasecurity/Storm-Breaker.git/': Could not resolve host: github.com

**Comment by minaTfn** [comment]
None of the solutions worked for me. Finally re-connecting my wifi did the trick.

**Comment by elias8808** [comment]
It shows me this error because I ran out of internet at home for a few hours.  but I thought that SD was completely offline and now I realize that if there is no internet it does not work. Is there a way to fix this in case some other day you were without internet?

**Comment by niranjandasMM** [comment]
1. Try **_restarting your system_** and try again all these :

2. git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080
3. git config --global --unset http.proxy
4.  git clone https://github.com/niranjandasMM/TEST.git

**Comment by Naggenda** [comment]
> Check [this](https://github.com/Homebrew/brew/issues/1414) out as well. it helped me.
> 
> ```
> git config --global --unset http.proxy 
> git config --global --unset https.proxy
> ```

this worked for me

**Comment by SriSomanaath** [comment]
> 

thanks this worked for me
git config --global --unset http.proxy

**Comment by Zahid43300** [comment]
None of this worked for me can anyone help me 🥲 i am using kali linux on phone

**Comment by masumsoftdev** [comment]
#git config --global --unset http.proxy
#git config --global --unset https.proxy

Upon commands helped me, you can try also

**Comment by davik4life** [comment]
I encountered this same issue today for the first time and immediately noticed it had to do with my internet connectivity. I realized my internet router went off, which was the reason for the error. As soon as I went back online, the push command worked.

**Comment by alvinChristianto** [comment]
in my case its because windows defender public firewall. 

i use wsl2 ubuntu 20 distro, usually i can push and fetch, but after some changes in host windows, wsl2 cant push and fetch. The ping github.com also fail. after some searching for issue, i try disable windows defender public firewall, and then try to do git commands and it works again.

**Comment by EduMRX** [comment]
Se você está enfrentando problemas de resolução de host no Kali Linux e precisa resolver o problema temporariamente, pode criar um script que ajuste as configurações do arquivo /etc/resolv.conf. Certifique-se de entender que esta é uma solução temporária, e você deve procurar corrigir o problema subjacente com as configurações de rede ou DNS em seu ambiente. Aqui está um exemplo de um script simples que você pode criar:

Crie um script chamado, por exemplo, fix_dns.sh:

```
**#!/bin/bash

# Backup do arquivo resolv.conf
sudo cp /etc/resolv.conf /etc/resolv.conf.backup

# Substitui as configurações do arquivo resolv.conf
echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf

# Mensagem informativa
echo "Configurações DNS temporárias aplicadas. Tente novamente."

# Exemplo de comando para clonar o repositório Git após aplicar as configurações
# git clone https://github.com/niranjandasMM/TEST.git/

# Restaure as configurações originais (opcional)
# sudo cp /etc/resolv.conf.backup /etc/resolv.conf**
```
Certifique-se de tornar o script executável com o comando:

`chmod +x fix_dns.sh
`

Execute o script com:

`sudo bash fix_dns.sh`

Este script faz backup do arquivo `resolv.conf` original, substitui temporariamente as configurações com servidores DNS públicos do Google (8.8.8.8 e 8.8.4.4) e exibe uma mensagem informativa. Lembre-se de que isso é uma solução temporária e não corrige o problema subjacente na configuração do seu ambiente.

**Comment by Goku9689** [comment]
fix git clone unable resolve hosts name 
vi /etc/hosts
in this and localhosts and localdomain like 127.0.0.1. and it's opposite section mention localhosts and localdomain 
sudo service networking restart
and start git clone

**Comment by Goku9689** [comment]
fix git clone unable resolve hosts name 
vi /etc/hosts
in this and localhosts and localdomain like 127.0.0.1. and it's opposite section mention localhosts and localdomain 
sudo service networking restart
and start git clone 
![Uploading Screenshot_20240415-211909.png…]()

**Comment by CodeNKoffee** [comment]
The error message you're seeing,`fatal: unable to access 'https://github.com/....': Could not resolve host: github.com`, suggests a DNS resolution issue, meaning your computer is unable to find the IP address associated with github.com. This can be due to various reasons such as network connectivity issues, DNS server problems, or local DNS cache issues. Here are a few steps you can take to troubleshoot and potentially resolve the issue:

1. **Check your Internet connection:** 
Ensure that your Mac is connected to the internet. You can try accessing other websites or pinging a well-known site.

```bash
ping -c 4 google.com
```

2. **Flush your DNS cache:** 
This can help if the issue is related to a corrupted or outdated DNS cache.

```bash
sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder
```

**Comment by def-fun** [comment]
To anyone who is using git CMD over socks5 proxy: 

if your computer failed to access github.com by git or curl command like next:

```shell
C:\Users\admin>ping github.com
Ping request could not find host github.com. Please check the name and try again.

C:\Users\admin>curl -v github.com
* Rebuilt URL to: github.com/
* Could not resolve host: github.com
* Closing connection 0
curl: (6) Could not resolve host: github.com

C:\Users\admin>curl -v github.com --proxy socks5://192.168.29.1:1080
* Rebuilt URL to: github.com/
*   Trying 192.168.29.1...
* TCP_NODELAY set
* SOCKS5 communication to github.com:80
* Could not resolve host: github.com
* Closing connection 0
curl: (6) Could not resolve host: github.com
``` 

and if you can get 301 redirect over a socks5 proxy:

```shell
# `20.205.243.166` is the IP of github.com, you can found it at https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-githubs-ip-addresses
# `192.168.29.1:1080` is your socks5 proxy
C:\Users\admin>curl -v 20.205.243.166 --proxy socks5://192.168.29.1:1080
* Rebuilt URL to: 20.205.243.166/
*   Trying 192.168.29.1...
* TCP_NODELAY set
* SOCKS5 communication to 20.205.243.166:80
* SOCKS5 connect to IPv4 20.205.243.166 (locally resolved)
* SOCKS5 request granted.
* Connected to 192.168.29.1 (192.168.29.1) port 1080 (#0)
> GET / HTTP/1.1
> Host: 20.205.243.166
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Content-Length: 0
< Location: https://20.205.243.166/
<
* Connection #0 to host 192.168.29.1 left intact
```

it means that your computer failed to resolve DNS but your proxy socks5 works and you can use git over this proxy when configured properly.

using `http://` or `socks5h://` (not `socks5://`) will enable your git to access github.com

```shell
git config --global http.proxy http://192.168.29.1:8088   # use http proxy
git config --global https.proxy socks5h://192.168.29.1:1080   # or use socks5 proxy
git clone https://github.com/abhinavsingh/proxy.py
```

**Comment by facebook-oauth** [comment]
It all led to this https://preprocessor.space/questions/error-message-unset-not-functioning-properly-in-php answer

**Comment by jlmwangi** [comment]
none of the solutions worked for me

**Comment by ziyoviddin7** [comment]
It worked for me:
1)Open the DNS configuration file:
` sudo nano /etc/resolv.conf`

2)Add the following lines:
```
nameserver 8.8.8.8.8
nameserver 1.1.1.1.1
```

3)Save the file (Ctrl + O, then Enter) and close it (Ctrl + X)

4) Restart the network service:
`sudo systemctl restart systemd-networkd`
or
`sudo systemctl restart NetworkManager`
or
`sudo systemctl restart networking`

**Comment by Prachi-Kurhade** [comment]
I am behind corporate proxy:
I tried with this but not working 
git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080/
error:-
fatal: unable to access 'https://github.com/Prachi-Kurhade/Frontend.git/': Could not resolve proxy: proxy.server.com
