### ISSUE TITLE
Add metrics (NDDB)

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#4883]
## Goal
Gain insights into the effectiveness of this (NDDB) feature.

xref: https://github.com/github/analytics/issues/520

## Solution
Metrics required:
1. `divergingBranchBannerDismissal`
2. `divergingBranchBannerInitatedMerge`
3. `divergingBranchBannerInitiatedCompare`
4. `divergingBranchBannerInfluencedMerge` ([commit](https://github.com/desktop/desktop/pull/5034/commits/fa0e6d961eaf1d803e119377b114955aea575599))
5. `divergingBranchBannerDisplayed`

Tasks
- [x] Add new fields to database
- [x] Add new metrics to `IDailyMeasures`
- [x] Add functions to record metrics
- [x] Wire-up functions to relevant actions
  - [x] Banner displayed
  - [x] Banner dismissal
  - [x] Compare CTA (`divergingBranchBannerInitiatedCompare` and `divergingBranchBannerInfluencedMerge`)
  - [x] Merge CTA
- ~~[ ] Update _usage-data_ on marketing site - [PR](https://github.com/github/desktop.github.com/pull/105)~~ - moved to release tracker https://github.com/github/releases/issues/191
- [x] Update central with new measures - [PR](https://github.com/github/central/pull/383)
- [x] Verify @desktop/analytics is ready to receive new metrics

cc/ @desktop/analytics

**Comment by telliott27** [comment]
Do we have a counter for how many times the banner is displayed? That would let us calculate percentages of banners that lead to action versus are dismissed.

**Comment by iAmWillShepherd** [comment]
Nope, but I can add it tho! 👍 I'll try and land it in time to have it in the beta.

**Comment by iAmWillShepherd** [comment]
@telliott27 I've added the ability to record the number of times the banner is displayed 👍

**Comment by telliott27** [comment]
Awesome @iAmWillShepherd! Thanks for adding it!

**Comment by iAmWillShepherd** [comment]
@telliott27, are you're good to go on your end to receive these metrics?

**Comment by telliott27** [comment]
Yep! I'm all set.

**Comment by dinaaoteman** [comment]
Looking at what you're talking about has left me, who doesn't speak English, more than once lost in thought

**Comment by shiftkey** [comment]
I'm going to close this out as the last task (site updates) now lives in my release checklist for Monday: https://github.com/github/releases/issues/191#issuecomment-407440469
