### ISSUE TITLE
Offering to 'restart GitHub now' instead of offering to 'restart now' when updates are available, can be confusing.

### ISSUE THREAD

**Issue by Raymo111** [desktop/desktop#4891]
Offering to restart now discourages people who misinterpret restarting as restarting their computer to update GitHub (the desktop app) as they are in the middle of doing something. But offering instead to 'restart GitHub now', encourages those (most people) who are not using GiHub but still using their computer to restart GitHub to receive the new update.

**Comment by shiftkey** [comment]
@Raymo111 I'm not sure how I feel about adding more to the message, but here's the source if someone wants to have a go:

https://github.com/desktop/desktop/blob/3fc22b4d48e4dacab698e5b5e3f2f9022d0c71ab/app/src/ui/updates/update-available.tsx#L24-L29

cc @desktop/core for feels

**Comment by iAmWillShepherd** [comment]
I actually agree that we should be specific. We have users of all levels, so our messaging to be clear to as many people as possible. I do think this is a nice issue for a first PR, so going to add it to our project board for the community.

**Comment by AB1908** [comment]
Well not be pedantic, but could it be `Restart GitHub Desktop Now` instead? I feel that that's both accurate and clear.
