### ISSUE TITLE
Error when trying to clone repo

### ISSUE THREAD

**Issue by sroudnitsky** [desktop/desktop#4892]
When i try to clone a repo, i get this error:
`Cloning into 'C:\Users\Sean\Documents\asd\Treeio-O-s'...
fatal: unable to access 'https://github.com/alanwang67/Treeio-O-s.git/': schannel: failed to open CA file 'C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt': No such process`

**Comment by shiftkey** [comment]
@sroudnitsky thanks for the report!

I believe this is the same as #4836, and this workaround should address the issue https://github.com/desktop/desktop/issues/4836#issuecomment-393666595:

> Removed:
> ```
>[http]
>	sslCAinfo = /bin/curl-ca-bundle.crt
>```
>from:
>```
>C:\ProgramData\Git\config
>```

**Comment by sroudnitsky** [comment]
@shiftkey i don't have a ProgramData folder

**Comment by shiftkey** [comment]
@sroudnitsky it might be hidden by default in Explorer
