### ISSUE TITLE
show details of repository

### ISSUE THREAD

**Issue by NickZengXL** [desktop/desktop#4894]
![default](https://user-images.githubusercontent.com/24708598/41137152-37fc1672-6b0c-11e8-84b1-0ff8e1eeecc1.png)

It's will be more helpful to show more details in repository list.  
For example, path of local repository.

Especially, when there are several repository with same name

**Comment by steveward** [comment]
Thanks for contributing @NickZengXL!

> For example, path of local repository.

For reference, if you hover over the repository in the list it will show you the full path, but I can see how having a quick way to differentiate between repositories with the same name would be helpful. 

I'm going to close this in favor of https://github.com/desktop/desktop/issues/1929, which is where we are tracking adding the option to set a custom label for a repository. I think that would be a viable solution for your use case -- please feel free to add any additional feedback in that issue as well.

We are also tracking adding various improvements to the repository list in https://github.com/desktop/desktop/issues/2259, which is on the roadmap for v1.3.
