### ISSUE TITLE
Clone and push problem ? 

### ISSUE THREAD

**Issue by kuldip-benzatine** [desktop/desktop#4897]
## Description
I will clone my project but i have some certificate and other problem but i can't understand it please help what is problem and how to solve it.

## Version
1.2.3

* Operating system:
windows 8.1

* other 
- i am attach my screen shot please see and if you know give me some ideas.

![screenshot 22](https://user-images.githubusercontent.com/19344731/41149474-486d3280-6b29-11e8-98bd-5a5f7187b5f3.png)

Thanks

**Comment by niik** [comment]
Hi @kuldip-benzatine,

Assuming this is a similar issue to https://github.com/desktop/desktop/issues/4836 there seems to be some remnants from an old installation of Git that's causing problems for you.

See if you have a file in `C:\ProgramData\Git\config` and check if that file contains a section similar to this

```
[http]
	sslCAinfo = /bin/curl-ca-bundle.crt
```

If it does, try removing the sslCAInfo line, save the file, and try cloning again from GitHub Desktop

**Comment by shiftkey** [comment]
I see that @kuldip-benzatine left a couple of reactions on that last comment, so I'm going to close this out as resolved.
