### ISSUE TITLE
Need graphic view for branch

### ISSUE THREAD

**Issue by pluwen** [desktop/desktop#4905]
![image](https://user-images.githubusercontent.com/555720/41194029-ffd5524e-6c47-11e8-9f66-8f54c9e75b00.png)

Just like SourceTree or other git client.

**Comment by jaketyo** [comment]
This would be a huge improvement.

I'm waiting for this to be implemented so I can switch away from GitKraken.

**Comment by nerdneha** [comment]
hi @pluwen and @jaketyo, thanks for the feedback and taking the time to contribute!

We noticed that this is a duplicate of #1634. Please follow that issue for further updates.
