### ISSUE TITLE
Files in a .gitignore'd folder still get picked up

### ISSUE THREAD

**Issue by Pr0methean** [desktop/desktop#4907]
In https://github.com/pr0methean/BetterRandom the .gitignore file includes `.idea/`. But when I run commands such as `git rm --cached --force ".idea/encodings.xml"` on a Linux machine to untrack pre-existing files, commit, and then pull into GitHub Desktop on my Windows PC, the files are deleted (which doesn't happen on the Linux machine). When I run `git checkout HEAD~1 .idea` to restore them, GitHub Desktop picks them up as added files. Even selecting them and choosing "Ignore" from the right-click menu, which creates redundant .gitignore entries, doesn't remove them from the list of changed files! How do I get GitHub Desktop to respect .gitignore?

**Comment by Pr0methean** [comment]
A workaround seems to be to copy the .idea folder outside the repo, discard changes, close GitHub Desktop and copy it back.

**Comment by shiftkey** [comment]
> Even selecting them and choosing "Ignore" from the right-click menu, which creates redundant .gitignore entries, doesn't remove them from the list of changed files! How do I get GitHub Desktop to respect .gitignore?

This feels a lot like #2537, and we've gone back and forth on this a bit - https://github.com/desktop/desktop/pull/3164#issuecomment-339789343 is important context here.

**Comment by nerdneha** [comment]
Hi @Pr0methean, I'm going to go ahead and close this out as this is a known issue but if there's any other context you'd like to provide here, feel free to provide it! Thanks for bringing it up!
