### ISSUE TITLE
split some function to individual package like get available editors.

### ISSUE THREAD

**Issue by gengjiawen** [desktop/desktop#4909]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Current we have some function like get available editor and open in terminal that should be in a individual package than coupled into the main repo. So I am thinking maybe extract those function to lerna package with there own test. With this, it will be much easy to debug and reusable by community.

**Describe alternatives you've considered**

**Teachability, Documentation, Adoption, Migration Strategy**

**Comment by gengjiawen** [comment]
> Are you able to illustrate with a code snippet or API example what one of these packages would look like, from a consuming perspective?

My thought is that it looks like just normal projects managed by [lerna](https://github.com/lerna/lerna), take react for example https://github.com/facebook/react/tree/master/packages.
> What dependencies and tooling related to Lerna JS would we need to adopt? Got a good example project for us to look at and learn from?

I believe lerna is the only manage tool needed. Besides react, [apollo](https://github.com/apollographql/apollo-server) is ts project also managed by lerna.
> We've had success already by splitting out dugite and registry-jsinto standalone repositories that now get external contributions - is there a reason why you prefer Lerna over that approach?

Split it out also works fine. Because in the end they are published to npm. But stay in this repo will be easy to manage. Maybe one package became very popular in js community, then we can move it out.

> Can you point to details about how things aren't easy to debug or reusable currently? I'd like to ensure we've considered alternatives before going to down this path.

For `easy to debug`, take the get external editor part. If I want to debug is vs code installed in my computer or I have find a bug, I don't have to look the related code in app directory. It's became more clear it stays in a small package. And test case are easy to find too.

For `reusable`, I have some idea may need a npm lib just like `open-in-terminal` or `open in vs-code`, with split it out I don't have to write one myself.

**Comment by shiftkey** [comment]
@gengjiawen 

> My thought is that it looks like just normal projects managed by lerna, take react for example https://github.com/facebook/react/tree/master/packages.

We're not currently set up for publishing NPM packages, so this is additional work to bring into the core, and I'm not sure how Lerna works with things that aren't published to npm (like our Desktop app). 

I think following the precedence of modules in separate repositories is preferred at this stage.

> For `reusable`, I have some idea may need a npm lib just like `open-in-terminal` or `open in vs-code`, with it split it out I don't have to write one myself.

I'd love to see a full snippet or scenario of how you'd use this hypothetical library - this will help me understand the impact to extracting the work from Desktop, which is what we've done in the past with these other modules.

**Comment by shiftkey** [comment]
Closing this out to keep our backlog under control, but this is still my current thinking:

> I think following the precedence of modules in separate repositories is preferred at this stage.

And again, I'm more than happy to help talk about specific API proposals and how we can adapt Desktop to support new scenarios - you can find my email around the place, or you can `@`-me on issues or PRs anywhere on this site - but I don't have the bandwidth to drive this myself so it'll be up to others to take charge of this and [scratch their own itch](https://geekfeminism.org/2013/04/28/from-sit-still-to-scratch-your-own-itch/).
