### ISSUE TITLE
Windows user whose name contains special spaces cannot push.

### ISSUE THREAD

**Issue by taroyabuki** [desktop/desktop#4910]
## Description

Windows user whose name contains special spaces such as U+00A0 (NO-BREAK SPACE) or U+3000 (IDEOGRAPHIC SPACE) cannot push.

Examples:

* `John*Smith` (replace `*` with U+00A0)
* `Jane*Smith` (replace `*` with U+3000)

## Version

* GitHub Desktop: 1.2.3

* Operating system: Windows 10 Education 1709

## Steps to Reproduce

1. Create a Windows user whose name contains U+00A0 such as `John*Smith`. (Replace `*` with U+00A0.)
1. Login as the new user.
1. Clone a repository.
1. Create a new file and commit, push.

### Expected Behavior

Push succeeds.

### Actual Behavior

An error occurs and the push fails.

## Additional Information

![error](https://user-images.githubusercontent.com/2989114/41198772-7800057a-6cc0-11e8-9305-1889c572502a.png)

### Logs

[2018-06-10.desktop.production.log](https://github.com/desktop/desktop/files/2087586/2018-06-10.desktop.production.log)

**Comment by Orion12fugood** [comment]
@taroyabuki 

_Sent from my Galaxy J7 Pop using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Orion12fugood** [comment]
- - 

_Sent from my Galaxy J7 Pop using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tierninho** [comment]
Sorry, but I could not reproduce this.  Perhaps the dev team has some insight.

**Comment by taroyabuki** [comment]
With the new version 1.4, this problem was not reproduced.
