### ISSUE TITLE
New desktop's color is not color blindness friendly

### ISSUE THREAD

**Issue by Asoul** [desktop/desktop#4913]
**Is your feature request related to a problem? Please describe.**
I'm a red/green color blindness. It's hard for me to distinguish the - and the + lines

**Describe the solution you'd like**
I think the red and green color in diff mode can be brightness differently more.

**Describe alternatives you've considered**
User may customized their color theme, or download third party themes.

I think it's better to make GitHub desktop more friendly to more people. Thank you!

**Comment by niik** [comment]
Hi @Asoul, thank you so much for opening this issue, feedback like this is very valuable to us. We had two similar issues a while back https://github.com/desktop/desktop/issues/2586 and https://github.com/desktop/desktop/issues/2974 and as a result of that we changed the colors to match that of GitHub.com (https://github.com/desktop/desktop/pull/3000).

I'm curious to know if you find the colors on the website easier or harder to differentiate, it's possible that there's other factors involved such as syntax highlighting that makes it harder.

We're also working on a dark theme in #4849 and even if you don't fancy a dark appearance in general it would be helpful to get your feedback on red/greens in that theme once we ship it.

**Comment by shiftkey** [comment]
@Asoul have you had a chance to look at how GitHub diffs (and our dark theme diffs in 1.2.4) look? It'd be nice to get some guidance about how those feel versus what is currently in the light theme...

**Comment by JosephTLyons** [comment]
[Just inserting this for reference ](https://github.com/desktop/desktop/issues/5027)

**Comment by lenis2000** [comment]
The red/green commit colors in the new dark theme are not friendly for me having partial color blindness. I just see them all as equally dark. I'm working on MacBook Pro mid 2014 Retina with standard monitor settings (no night shift).

**Comment by shiftkey** [comment]
This has sat quiet for a while, and we'd really like some input on this particular question about the diffs in Desktop versus the diffs on GitHub The Website:

> I'm curious to know if you find the colors on the website easier or harder to differentiate, it's possible that there's other factors involved such as syntax highlighting that makes it harder.

We'd like this input to help us make more informed choices like #5094

**Comment by sybrew** [comment]
I have perfect vision (yay), and I'm also finding issues with this. 
This issue is mostly present with the dark theme on a TN panel, where I can hardly discern dark green from dark grey.

On a (factory calibrated) IPS panel it's doing somewhat fine; however, don't expect everyone to have this luxury.

**Comment by Asoul** [comment]
Sorry for the delay input. I found out that the color isn't bad, but the highlight syntax is sometimes wrong, it makes the color not highlight in specific lines/variables and make it hard to read. I didn't remember how I reinstall or update the Github Desktop, and someday it just not hard to read. 
Thank you! Now I use the Github Desktop smoothly.

**Comment by shiftkey** [comment]
Thanks for the follow-up @Asoul!
