### ISSUE TITLE
Github Desktop change filenames case by itself

### ISSUE THREAD

**Issue by viviengarcia** [desktop/desktop#4916]
## Description

Github Desktop renames by itself files in my project. When I make changes on some files, they appear renamed in lowercase in the "Changes" tab in the app. Problem is, when I commit, files are actually renamed in my project. File content is not impacted, only filenames.

## Version

* GitHub Desktop: 1.2.3

* Operating system: OS X 10.11.6

## Steps to Reproduce

1. Edit 2 file: "Pub**Lite**.sublime-project" and "**AbOut**.md"

### Expected Behavior

Github Desktop doesn't change my filenames

### Actual Behavior

1. Github desktop show them in the "Changes" tab as "Pub**lite**.sublime-project" and "**about**.md", which isn't even consistent in the renaming
2. Once commited, files are renamed

### Logs

[2018-06-11.desktop.production.log](https://github.com/desktop/desktop/files/2090142/2018-06-11.desktop.production.log)

**Comment by shiftkey** [comment]
@viviengarcia thanks for the report!

Windows and macOS are not case-sensitive filesystems, so Git itself has to workaround this by probing the underlying setup. I wrote up a bit about this over in https://github.com/desktop/desktop/issues/2672#issuecomment-329011490 but I'll call out [this part of the Git docs](https://git-scm.com/docs/git-config#git-config-coreignoreCase):

> **`core.ignoreCase`**
>
> If true, this option enables various workarounds to enable Git to work better on filesystems that are not case sensitive, like FAT. For example, if a directory listing finds "makefile" when Git expects "Makefile", Git will assume it is really the same file, and continue to remember it as "Makefile".
>
> The default is false, except `git-clone` or `git-init` will probe and set core.ignoreCase true if appropriate when the repository is created.

If you want to do a rename that changes the casing of a file and have this reflected correctly in Git you'll need to use `git mv`.

**Comment by nerdneha** [comment]
Hi @viviengarcia, @shiftkey did a great job explaining why changed filenames don't show up as changes in git but what I'm understanding is that you're noticing that the GitHub Desktop app proactively renames your files. 

I tried to reproduce your experience of having GitHub Desktop change the casing of your filenames but I couldn't successfully do so. Is there any chance you can upload a gif of this happening?

**Comment by viviengarcia** [comment]
Hi @nerdneha , @shiftkey. Sorry for the late answer, didn't realize so much time had passed. @shiftkey  did effectively a great job answering my question. It made me realize I has probably renamed my file PubLite.sublime-project _after_ it was created in the git repo. The other one (AbOut.md) was purposely renamed for testing purpose. 

So I renamed my file using `git mv` and since this I don't have anymore wild renaming problems. This seems consistent with what @shiftkey  said me so far, in particular the renaming scheme that wasn't the same for each file. It makes sense if the renaming just tried to rename the files like they where registered first.

I suppose  this isn't a bug at all but my lack of comprehension of git at work. Thank you both for your help and your time. @nerdneha if you want to reproduce this behavior, I think by renaming a file after adding it to the repo it should happens. Unfortunately I'm a little short of time now but I can try to do it later if you want. Have a nice day, both.

**Comment by shiftkey** [comment]
@viviengarcia thanks for following up.

I'm happy to close this out as it's a known limitation with the environment that Git needs to work in.
