### ISSUE TITLE
Build for linux

### ISSUE THREAD

**Issue by Rovel** [desktop/desktop#4920]
Is ok to build from source to use it on linux?

most of the electron apps have a debian dist ex: slack.

Any chance to have it on linux in future roadmaps??

**Comment by steveward** [comment]
👋 @Rovel 

We have [written documentation](https://github.com/desktop/desktop/blob/master/docs/contributing/linux-testing-and-you.md) for getting started with using GitHub Desktop on Linux. Hope that helps!

**Comment by Rovel** [comment]
thanks! :tada:

**Comment by Rovel** [comment]
[GitHubDesktop-linux-amd64-1.2.3.deb](https://github.com/shiftkey/desktop/releases/download/release-1.2.3/GitHubDesktop-linux-amd64-1.2.3.deb) successfully installed on **4.15.0-kali3-amd64**
