### ISSUE TITLE
How is this feature activated?

### ISSUE THREAD

**Issue by JosephTLyons** [desktop/desktop#4929]
When checking the github desktop website, I noticed this little box in the branch window.  I don't see this on my version of Desktop and can't seem to find a setting to show it.  How is this feature activated?  Also, what exactly is this number referring to? A commit number?

<img width="989" alt="screen shot 2018-06-13 at 3 14 48 am" src="https://user-images.githubusercontent.com/19867440/41335840-329e942a-6eb8-11e8-937f-eaec3fa617e8.png">

**Comment by agisilaos** [comment]
Hello @JosephTLyons, this number refers to a PR that the current branch (e.g `esc-pr`) is associated with. You don't have to do anything to activate this feature, because it's on automatically. 

When you open a PR from a branch that you're working on this box with the number of the PR will automatically appear as you see it in the screenshot.

**Comment by shiftkey** [comment]
@JosephTLyons yep, what @agisilaos said.

I'll also mention that you need to be signed into your GitHub or GitHub Enterprise account, and be using a GitHub repository so we can leverage the GitHub API to add this extra context.

**Comment by shiftkey** [comment]
@JosephTLyons I'm going to close this out as I don't believe there is any additional work to do here, but feel free to follow up with any extra questions you might have about this area.

**Comment by JosephTLyons** [comment]
Thank you very much, and yes, I actually meant to close it when I posted, as it wasn’t an actual issue, but an inquiry - I simply forgot to do so.  Thank you for the information.

**Comment by JosephTLyons** [comment]
I suppose this thread would probably be a bad place to request the feature of having the commit number shown in-app.  I think others have mentioned this in the  past, including myself, but just wanted to re-emphasize how great that would be.

**Comment by agisilaos** [comment]
@JosephTLyons  
> I suppose this thread would probably be a bad place to request the feature of having the commit number shown in-app. 

You can find the commit number here: 
<img width="719" alt="41335840-329e942a-6eb8-11e8-937f-eaec3fa617e8" src="https://user-images.githubusercontent.com/10944108/41379555-f0bb58be-6f6a-11e8-99bb-b2f6966023e8.png">

**Comment by JosephTLyons** [comment]
My apologies, my wording wasn’t that great, I meant the commit count number.
