### ISSUE TITLE
Authentication fails on macOS 10.14

### ISSUE THREAD

**Issue by hallee** [desktop/desktop#4931]
## Description

On macOS 10.14 beta (Mojave), anything requiring authentication gives the error: 
`Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open preferences and verify that you're signed in with an account that has permission to access this repository.`

## Version

* GitHub Desktop: 1.2.3

* Operating system: macOS 10.14 Beta

## Steps to Reproduce

Log in to a GitHub account and attempt to pull or push to a private repository while running the 10.14 beta.

### Logs

[2018-06-13.desktop.production.log](https://github.com/desktop/desktop/files/2098223/2018-06-13.desktop.production.log)

**Comment by steveward** [comment]
Thanks for opening this @hallee. This error seems to be the culprit:

```
ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

Are you able to successfully perform a `git push/pull` using the Terminal? 

I found a [similar issue](https://github.com/Microsoft/vscode/issues/32097) that popped up in VSCode, which seemed to happen when users upgraded to macOS Sierra last year. There are some workarounds in that issue thread that may be helpful, but the first one I would try would be to run `ssh-add ~/.ssh/id_rsa` from the Terminal and then restart GitHub Desktop to see if that gets things working.

**Comment by hallee** [comment]
I am able to `git push`/`pull`.

As it turns out, `id_rsa` was the name of my ssh key, and `ssh-add`'ing that has fixed Github Desktop. I'm still curious why the system update would break this (everything worked fine pre-update), but things are working now!

**Comment by steveward** [comment]
I'm glad to hear that got things working! Let us know if you run into any other issues using macOS 10.14.

**Comment by distinctdan** [comment]
I just had this same issue happen to me after rebooting my mac running High Sierra 10.13.6. However, redoing ssh-add seems to have fixed it.

**Comment by ScGPS** [comment]
Hi, I encount this issue with Jenkins Node, in plist mode.
```
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@xxx.com:one/app_mac.git # timeout=10
Fetching upstream changes from git@xxx.com:one/app_mac.git
 > git --version # timeout=10
using GIT_SSH to set credentials username: jenkins come from Jenkins Agent deployed user in OS. IP: .(One Project,MacOS Mini)
 > git fetch --tags --progress git@xxx.com:one/app_mac.git +refs/heads/*:refs/remotes/origin/*
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git@xxx.com:one/app_mac.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:817)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1084)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1115)
	at hudson.scm.SCM.checkout(SCM.java:495)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1276)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:560)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:485)
	at hudson.model.Run.execute(Run.java:1735)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress git@xxx.com:one/app_mac.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: jenkins@xxx.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```
I also use '$ ssh-agent -s  $ ssh-add ~/.ssh/id_rsa ', but it not work.
Please help.

**Comment by ScGPS** [comment]
I found the worked way:
change 
git@xxx.com:one/app_mac.git
to 
https://xxx.com/one/app_mac.git

don't use git ssh to visit, but https to visit
That's to say, use password to visit, not ssh to visit.

**Comment by tillt** [comment]
You might want to try the following on your Mac build slave; login onto that machine and set
```
git config --global --add core.sshCommand "ssh"
```

With that set, public key authentication might work for you - it did for me and was the only way to make sure the Jenkins key handover would properly work.

I have yet to find out why.

**Comment by tillt** [comment]
Try 
```
git config --global --add core.sshCommand "ssh"
```

**Comment by ScGPS** [comment]
@tillt Thanks again! I will try it.

**Comment by LunaGao** [comment]
@tillt You save my day!

**Comment by rmsys** [comment]
@tillt You save my day!
