### ISSUE TITLE
Ability to Add Keyword

### ISSUE THREAD

**Issue by oleteacher** [desktop/desktop#4940]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Having the ability to add a keyword(s) to each repository would be really helpful. Many repositories have names that are not associated with what they actually do.

**Describe alternatives you've considered**
N/A

**Teachability, Documentation, Adoption, Migration Strategy**
The current search filter form could be used. Maybe place a checkbox to filter by user inputted keyword

**Comment by steveward** [comment]
Thanks for opening this @oleteacher! This is similar to https://github.com/desktop/desktop/issues/2324, so I am going to drop your feedback in there so that we can have it accessible in one location. Please follow along there for updates!

**Comment by billygriffin** [comment]
Thanks for the idea! I'm removing `future proposal` in favor of #6460 which tries to capture *all the things*™️ in a more unified way since there have been so many different implementation ideas suggested.
