### ISSUE TITLE
Repo Categorization

### ISSUE THREAD

**Issue by PseudoCoding** [desktop/desktop#4945]
**Is your feature request related to a problem? Please describe.**
When using GH desktop on a wide variety of projects, it can become difficult to find repos in the repo list. 

**Describe the solution you'd like**
Currently search is a great feature, however it would be great it repositories could be categorized or grouped together for easy navigation without searching.

**Describe alternatives you've considered**
Using search more often.

**Teachability, Documentation, Adoption, Migration Strategy**
When cloning/creating a new repository the user should be able to select or create a category in an additional optional field. Post creation/clone the user should be able to right click on a repo to change the category. Repos can only be in one category at a time. The categories should be sub categories of the existing Enterprise, Other, etc categories, but should also be expandable or shrinkable for a better viewing experience.

**Comment by steveward** [comment]
Thanks for opening this @PseudoCoding!

Here are a few of the previous discussions we've had around ways to enhance the repository list:

 - #2038 - pin repositories so they appear at the top
 - #2037 - grouping repositories by organization
 - #1598 - custom folders for repositories
 - #1929 - support changing description to distinguish between local clones of the same repository

Hopefully some of those issues align with what you are looking for. Please feel free to add any further feedback there. I'm going to close out this issue with the `future-proposal` and `enhancement` labels.

**Comment by PseudoCoding** [comment]
@steveward From what you linked there this is a pretty frequent request, but from reading them it appears all the issues are closed and it is not on the roadmap or am I missing something here?

**Comment by steveward** [comment]
@PseudoCoding we close out issues to keep the issue backlog from becoming too large, but we do periodically revisit issues for future feature planning. There are already some improvements in the works for the repository list (see https://github.com/desktop/desktop/pull/4770 for an example), so this is definitely something we are thinking about!

**Comment by PseudoCoding** [comment]
@steveward. Just wanted to make sure it wasn't just getting dismissed. Everyone runs their repos/orgs differently. Thank you. 👍

**Comment by billygriffin** [comment]
Thanks for the idea! I'm removing `future proposal` in favor of #6460 which tries to capture *all the things*™️ in a more unified way since there have been so many different implementation ideas suggested.
