### ISSUE TITLE
cloning repository uses incorrect URL for source

### ISSUE THREAD

**Issue by doriclaudino** [desktop/desktop#4952]
## Description

I have two repositories:
ALGO: https://github.com/doriclaudino/algorithm-lessons
BOILERPLATE: https://github.com/doriclaudino/boilerplate-es6-mocha

When cloning the BOILERPLATE, it coming with algorithm-lessons name.
When cloning the ALGO, it coming with algorithm-lessons name [that's ok].

I tried to recreate the BOILERPLATE, still not working.

## Version

* GitHub Desktop: 1.2.3

* Operating system:
Windows 10 64bits.

## Steps to Reproduce

CTRL+SHIFT+O
![image](https://user-images.githubusercontent.com/3863501/41538156-91090b16-72d8-11e8-93e2-c9ca0216f20b.png)

![image](https://user-images.githubusercontent.com/3863501/41538277-f26f4abe-72d8-11e8-97e9-e709ffa06a51.png)

### Expected Behavior

Cloned repositories must still the same name from web to desktop github.

### Actual Behavior

![image](https://user-images.githubusercontent.com/3863501/41538582-afd5513e-72d9-11e8-84e3-5bd902e635ca.png)

### Logs

2018-06-18T13:12:51.855Z - info: [ui] [AppStore] loading 0 repositories from store
2018-06-18T13:12:51.857Z - info: [ui] [AppStore] found account: doriclaudino (dori)
2018-06-18T13:12:52.024Z - info: [ui] launching: 1.2.3 (Windows 10.0.17134)
2018-06-18T13:12:52.031Z - info: [ui] execPath: 'C:\Users\dori\AppData\Local\GitHubDesktop\app-1.2.3\GitHubDesktop.exe'
2018-06-18T13:13:02.345Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/doriclaudino/algorithm-lessons.git - doriclaudino (has token)
2018-06-18T13:13:07.140Z - info: [ui] Executing clone: git -c credential.helper= clone --recursive --progress -- https://github.com/doriclaudino/algorithm-lessons.git C:\github\boilerplate-es6-mocha (took 4.752s)
2018-06-18T13:13:07.203Z - info: [ui] [AppStore] adding repository at C:\github\boilerplate-es6-mocha to store
2018-06-18T13:14:02.739Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/doriclaudino/algorithm-lessons.git - doriclaudino (has token)
2018-06-18T13:14:06.584Z - info: [ui] Executing clone: git -c credential.helper= clone --recursive --progress -- https://github.com/doriclaudino/algorithm-lessons.git C:\github\algorithm-lessons (took 3.836s)
2018-06-18T13:14:06.681Z - info: [ui] [AppStore] adding repository at C:\github\algorithm-lessons to store

**Comment by shiftkey** [comment]
@doriclaudino thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Also, could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

Thanks for understanding and meeting us half way 😀

**Comment by doriclaudino** [comment]
@shiftkey I just update the issue. thanks!
Look at time from log: **2018-06-18T13:13:07.140Z**, It seems some cache or old refs bug, because I clone two different repositories.

**Comment by shiftkey** [comment]
@doriclaudino that log file helps - thanks for the details. It looks like the first clone was done with the correct URL but it chose to use a different local path:

```
2018-06-18T13:13:07.140Z - info: [ui] Executing clone: git -c credential.helper= clone --recursive --progress -- https://github.com/doriclaudino/algorithm-lessons.git C:\github\boilerplate-es6-mocha (took 4.752s)
```

The local path should be inherited from the repository you've selected, but I couldn't trigger this while testing on Windows just now:

<img width="522" src="https://user-images.githubusercontent.com/359239/41540021-8d963fdc-72e5-11e8-9026-de627863cf9d.png">
 
Could you have been switching quickly between the `algorithm-lessons` and `boilerplate-es6-mocha` repositories in the clone tab - which should update the local path - and created some state where `algorithm-lessons` was the selected repository but the local path was using `boilerplate-es6-mocha`? That's my best guess as to how it got into that state.

**Comment by doriclaudino** [comment]
@shiftkey but I'm not cloning: https://github.com/doriclaudino/algorithm-lessons.git on the first click.
I clicked to clone the https://github.com/doriclaudino/boilerplate-es6-mocha.git.

DETAIL:
If I rename the repository on github.com https://github.com/doriclaudino/boilerplate-es6-mocha.git to https://github.com/doriclaudino/boilerplate-es6-mochaNEWNAME.git **(just a different name)** it will display OK.

The image bellow must be:
doriclaudino/algorithm-lessons
doriclaudino/**boilerplate-es6-mocha**
![image](https://user-images.githubusercontent.com/3863501/41541190-de88b6be-72df-11e8-8425-e2e0127f679b.png)

**Comment by shiftkey** [comment]
@doriclaudino the repositories in the list will show their GitHub name (and differentiated by owner if they have the same name) so that behaviour seems to be correct. We only fallback to folder names for non-GitHub repositories.

I'd like to understand the steps you went on to clone the repository down - is this repeatable? Can you put together a GIF showing the steps that are leading to this confusion?

**Comment by doriclaudino** [comment]
@shiftkey, OK, like I said by the log shows I'm cloning 2 times the same repository (the lessons), but is not true. I'll make a .gif to show my problem. and I'll clean the folder to be easy.

**Comment by doriclaudino** [comment]
![github-bug](https://user-images.githubusercontent.com/3863501/41547387-0ed2a376-72ee-11e8-8147-a8d0c8d379cb.gif)

**Comment by shiftkey** [comment]
@doriclaudino thanks for the details and the GIF. I'm puzzled why it doesn't seem to be using the URL, but those steps are a great help to reproduce it on my end!

**Comment by billygriffin** [comment]
@desktop/support Mind taking a look at this one?

**Comment by steveward** [comment]
@doriclaudino I have attempted to reproduce this but have so far been unsuccessful. Is this something that you are able to still consistently reproduce in GitHub Desktop?
