### ISSUE TITLE
Unchanged files marked as changed after clone

### ISSUE THREAD

**Issue by hoof** [desktop/desktop#4953]
## Description

After cloning my repository from Github more or less all files are marked as "changed". I suspect it has to do with line endings since no changes are visible in the Desktop application. The weird thing is "git status" reports no changes - and I would expect this to be the source of truth. 
I have tried setting core.autocrlf to true|false|input and clone the repository again - same result with either setting.
It's worht mentioning that binary files are marked as changed as well - for instance `gradle-wrapper.jar`.
This issue sadly renders the Desktop app completely unusable for me.

## Version

* GitHub Desktop: 1.2.3

* Operating system:
Windows 10 64bit

## Steps to Reproduce

Unfortunately my repo is within a closed organizational account so I can't provide access to the exact repo. The steps to reproduce however are:
1. Clone repo
2. Check status of "git status" and verify that all files are up-to-date
3. Open Github desktop and add the newly cloned repo
4. Verify that almost all files are reported as changed without and diff

### Expected Behavior

Github Desktop should report the same as "git status"
### Actual Behavior

Unchanged files are marked as changed in Github  Desktop even though "git status" reports no changed files

## Additional Information

As noted above I expect this to be related to line endings. There are many contributors to this repository and I cannot know which core.autoclrf setting they are using. They are all working from Windows based machines.
Here is a screen shot from Github Desktop illustrating the problem along with a commandline status:
![image](https://user-images.githubusercontent.com/427736/41525623-e8b65842-72e1-11e8-910a-66f49850b176.png)

### Logs

[2018-06-18.desktop.production.log](https://github.com/desktop/desktop/files/2110504/2018-06-18.desktop.production.log)

**Comment by j-f1** [comment]
What does `git status --untracked-files=all --branch --porcelain=2` report?

**Comment by hoof** [comment]
Dear @j-f1 
Please find output below :)

```
xxx@localhost: ~/workspaces/my-repo $ (master) git status --untracked-files=all --branch --porcelain=2
# branch.oid cf88511f9324d9f3401a897704209c9e93bacad1
# branch.head master
# branch.upstream origin/master
# branch.ab +0 -0
xxx@localhost: ~/workspaces/my-repo $ (master)
```

**Comment by j-f1** [comment]
Looks like Desktop’s instance of Git is interpreting things differently for some strange reason.

**Comment by hoof** [comment]
Anything I can do to provide further help to figure out the issue? Does my local Git installation in any way affect the behavior of the desktop application? (It's version 2.16.2 btw. - I know, I havent updated for a while).

**Comment by shiftkey** [comment]
@hoof is there a ⚠️icon in the diff details for any of these files? My best guess at this point is that some line endings change has occurred when porting a repository from non-Windows to Windows.

**Comment by hoof** [comment]
Hi @shiftkey 

No, there is not. The repository has not been ported. It started out on Github and there has only been Windows machines committing to the repository.

**Comment by shiftkey** [comment]
@hoof actually, there's a detail that I overlooked from the repro steps:

> 2. Check status of "git status" and verify that all files are up-to-date

The embedded Git in Desktop has it's own system configuration that might differ from what you have installed with Git for Windows. Are you able to run `git config -l --show-origin` from your CLI and share what's set there?

That should be the "known good" configuration and we can then identify what's different from the config in Desktop itself to potentially reproduce this issue, or identify a workaround to "teach" Desktop that those files are fine.

**Comment by hoof** [comment]
Dear @shiftkey 

Please find output below:

```
xxx@localhost: ~/workspaces/my-project $ (master) git config -l --show-origin
file:/cygdrive/c/Users/rph/.gitconfig   user.name=Rasmus Hovendal
file:/cygdrive/c/Users/rph/.gitconfig   user.email=hovendal@gmail.com
file:/cygdrive/c/Users/rph/.gitconfig   alias.co=checkout
file:/cygdrive/c/Users/rph/.gitconfig   alias.cm=commit -m
file:/cygdrive/c/Users/rph/.gitconfig   alias.s=status
file:/cygdrive/c/Users/rph/.gitconfig   alias.aa=add .
file:/cygdrive/c/Users/rph/.gitconfig   alias.b=branch
file:/cygdrive/c/Users/rph/.gitconfig   filter.lfs.smudge=git-lfs smudge -- %f
file:/cygdrive/c/Users/rph/.gitconfig   filter.lfs.process=git-lfs filter-process
file:/cygdrive/c/Users/rph/.gitconfig   filter.lfs.required=true
file:/cygdrive/c/Users/rph/.gitconfig   filter.lfs.clean=git-lfs clean -- %f
file:/cygdrive/c/Users/rph/.gitconfig   core.autocrlf=false
file:/cygdrive/c/Users/rph/.gitconfig   winupdater.recentlyseenversion=2.17.1.windows.2
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=true
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.ignorecase=true
file:.git/config        remote.origin.url=git@github.com:myorg/my-project.git
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.master.remote=origin
file:.git/config        branch.master.merge=refs/heads/master
file:.git/config        branch.development.remote=origin
file:.git/config        branch.development.merge=refs/heads/development
```

**Comment by chrstphrchvz** [comment]
I think `core.filemode=true` might be the culprit here. (i.e. try running `git config core.filemode false`). I don't know how that gets set by default, but looking online it seems to often be a problem Cygwin git users.

**Comment by steveward** [comment]
@chrstphrchvz setting `core.filemode` to `false` will force Git to ignore file mode changes. The default setting is `true` when `core.filemode` is not specified in the config file.

Did setting this value to false fix the issue for you?
