### ISSUE TITLE
UI Update: Expanded branch list dropdown view

### ISSUE THREAD

**Issue by dbchristopher** [desktop/desktop#4957]
**Is your feature request related to a problem? Please describe.**
There is a small but annoying issues caused by how narrow the branch list dropdown pane is. We format our branches with `username/feature-branch`, so the names can get fairly long. Due to that I often can't tell the difference between similar branches because the names gets cut off with an ellipsis:

<img width="338" alt="screen shot 2018-06-18 at 9 52 44 am" src="https://user-images.githubusercontent.com/238293/41550492-c6b14f3a-72dd-11e8-82a5-354ca93551d7.png">

**Describe the solution you'd like**
I'd love to see the dropdown expanded to be at least 50% wider to provide room for longer branch names.

**Comment by joshuapage2017** [comment]
New UI

**Comment by shiftkey** [comment]
@dbchristopher thanks for the feedback. For reference, which OS are you running on?

**Comment by dbchristopher** [comment]
@shiftkey MacOS. Thanks for following up!

**Comment by dbchristopher** [comment]
And also related to this issue, expanding the closed Branch tab would be nice. All I can see for my current selected branch is my own username:

<img width="362" alt="screen shot 2018-06-19 at 2 30 57 pm" src="https://user-images.githubusercontent.com/238293/41625392-8e63885a-73cd-11e8-8af0-5cc560c7b79c.png">

**Comment by tierninho** [comment]
Closing this issue as it will addressed in pull release: https://github.com/desktop/desktop/pull/6112
