### ISSUE TITLE
Filter Repositories by Topic

### ISSUE THREAD

**Issue by sbonami** [desktop/desktop#4958]
**Describe the solution you'd like**

As an organization with a broad range of repositories, it would be great to filter our repository list by [topic](https://blog.github.com/2017-01-31-introducing-topics/).

This also requires:
- Topics be pulled into the application
- Viewing topics for each repository within the repo list, highlighting matches like the branch dropdown's search feature
- Possibly also editing topics for a repository

Topics would provide a tremendous benefit in filtering by:
- Internal project names
- Type: library vs toolkit vs application
- Language
- Library (react, redux, rails)

**Describe alternatives you've considered**

Due to our namespacing within repository names, the Topics aren't the highes of a priorities for us. One can search simply by name and get an acceptable result.

**Teachability, Documentation, Adoption, Migration Strategy**

Similar to [the organization filtering feature request](https://github.com/desktop/desktop/issues/1533), the ability to filter large lists of repositories is a must. Organizations with a large number of projects (or sub-divisions of projects), multivariate project focuses, and/or a breadth of unique projects would benefit from this the greatest.

**Comment by shiftkey** [comment]
@sbonami Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

The `future-proposal` label has been added to this issue, and I'll close this so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Comment by billygriffin** [comment]
Thanks for the idea! I'm removing `future proposal` in favor of #6460 which tries to capture *all the things*™️ in a more unified way since there have been so many different implementation ideas suggested.
