### ISSUE TITLE
Add pending changes marker on Current Repository dropdown

### ISSUE THREAD

**Issue by StickNitro** [desktop/desktop#4960]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

When opening up the Current Repository dropdown there is no indication whether there are any pending changes in any of the available repositories prompting you to load each repository in turn to check and commit as required.

Would it be possible to add a marker alongside each repository name to indicate the following
* The number of files pending
* number of pushes pending (count of commits)
* and changes on the server that need to be pulled (a count of commits)

**Describe alternatives you've considered**
None

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this. This will help the core team understand how the feature would work, and assist with future work like documentation.
Screenshots or mockups here are a great help!

Users when working across multiple repositories will be able to see at a glance which repositories have changes to commit, equally where multiple users are working on a given repository the user will be able to see if there are any changes on the server without needing to switch to that repository

**Comment by shiftkey** [comment]
> When opening up the Current Repository dropdown there is no indication whether there are any pending changes in any of the available repositories prompting you to load each repository in turn to check and commit as required.

There's work underway to implement this in #4770 - please follow along with that PR and in particular this comment https://github.com/desktop/desktop/pull/4770#issuecomment-392071080 which has the latest screenshots.
