### ISSUE TITLE
History list shows only ~100 items, expecting to see more

### ISSUE THREAD

**Issue by NiklasBr** [desktop/desktop#4964]
## Description
The history list is only showing the latest 100 items or so, previous versions of the app could scroll back to the initial commit.

## Version
* GitHub Desktop: 1.2.3
* Operating system: macOS 10.12.6 (16G1408)

## Steps to Reproduce
1. Open the History pane.
2. Scroll down.

### Expected Behaviour
I expect earlier commits to show up in the list. I think they were loaded dynamically as scrolling happened before.

### Actual Behavior
No older commits are showing.

## Additional Information
n/a

### Logs
[2018-06-19.desktop.production.log](https://github.com/desktop/desktop/files/2114252/2018-06-19.desktop.production.log)

**Comment by shiftkey** [comment]
@NiklasBr thanks for the report!

> I think they were loaded dynamically as scrolling happened before.

Yes, this should have been happening. Let me see if I can reproduce this, as it feels like a recent regression.

**Comment by shiftkey** [comment]
Yep, I can reproduce this on 1.2.3 on macOS and Windows. Figuring out how this was introduced.
