### ISSUE TITLE
Allow wider range of zoom levels / mouse-wheel zoom.

### ISSUE THREAD

**Issue by kbauer** [desktop/desktop#4967]
As of version 1.2.3, the zoom levels are locked to the range from 100% to 200%. Please relax this limitation.

When commiting verbose changes (e.g. LyX files, or having a lot of new code lines) it can be useful to have a birds view of the changes, rather than a good visiblity of individual code lines. Currently, at 100% zoom, the font size is too large for this.

Additionally, I have come to expect "<kbd>Ctrl</kbd>+Mousewheel" to zoom. Popularized by browsers, this keybinding is found in a lot of applications these days. Given the mouse-focus of Github Desktop's UI, it would be quite preferable to <kbd>Ctrl</kbd>+<kbd>+</kbd> and <kbd>Ctrl</kbd>+<kbd>-</kbd> (German layout).

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇

**Comment by kbauer** [comment]
> To clarify, are you saying you'd like to go below 100% here?

Yes. Less than 100%, temporarily, is quite useful for getting a birds-eye view of changes. A similar effect could be achieved though, by making the font size of the diff pane configurable, but zooming is typically more flexible.

> Are you running Windows? I think this is related to #3240 as we don't handle different keyboard layouts well, which affects some existing shortcuts.
> I will however call out that Ctrl+= is the correct shortcut here because we don't need the user to also press Shift here to force a +.

Actually, <kbd>Ctrl</kbd>+<kbd>+</kbd> is quite preferable on the German layout, which has <kbd>+</kbd> and <kbd>-</kbd> keys, but no <kbd>=</kbd> key. `=` is <kbd>Shift</kbd>+<kbd>0</kbd> here. The menu bar still claims the shortcut were <kbd>Ctrl</kbd>+<kbd>=</kbd> though.

I'm not sure about the Electron framework, but in other programs that bind a function to <kbd>Ctrl</kbd>+<kbd>=</kbd> regardless of keyboard layout, I've experienced the hotkey not to work at all, as <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>0</kbd> would not register as equivalent to <kbd>Ctrl</kbd>+<kbd>=</kbd>

**Comment by shiftkey** [comment]
@kbauer thanks for the context. #3240 is the issue to keep an eye on about us being able to support non-US English layouts for these shortcuts ([this is how we register shortcuts with Electron](https://github.com/desktop/desktop/blob/master/app/src/main-process/menu/build-default-menu.ts)). Once we are able to support that, tweaking shortcuts based on what's natural should be fairly easy to do.

**Comment by xQsme** [comment]
I would like to be able to zoom below 100% due to my scaling options, I run all my electron apps at 80% (when possible)

**Comment by silvanet** [comment]
I use a Logitech standard English keyboard and I can't zoom at all on GitHub Desktop. I can't resize the window either. There's maximized and that's it. On some dialogs I can't see the entire dialog because it goes off the screen at the bottom. For example, on File, Options, Advanced. I can't move the dialogs. The font size is too large, and can't be adjusted. I forget at which version update this started happening, but it is extremely frustrating.

**Comment by tidy-dev** [comment]
Requested in https://github.com/desktop/desktop/issues/15380 -> allow zoom below 100%.
