### ISSUE TITLE
Desktop Remote Window Position

### ISSUE THREAD

**Issue by me89** [desktop/desktop#4970]
## Description
I have a Windows 10 with three displays. If GitHub Desktop was used and hasn't been closed at the primary monitor (with physically setup), I can't reach the GitHub window in a remote session anymore. Even if I have the same count of displays for the remote session.

## Version
* GitHub Desktop: Version 1.2.3
* Operating system: Windows 10.0.17134.112

## Steps to Reproduce
1. Use Multi-Display Setup
2. Open GitHub Desktop and move windows to a not primary display
3. Close GitHub Window (It stores there last active position)
4. Connect with Remote -> Not able to access GitHub Desktop, even with close/restart etc.

### Expected Behavior
It should delete the last active position, if the display setup has been changend. 

### Actual Behavior
If the window has not been closed it is possible to access, or if I move it before I leave the phyiscally environment, I need to move the window to the primary display.

## Additional Information
Remote from Mac 10.13.5
with Microsoft Remote Desktop 8.0.43 (Build 27325)

### Logs
No Logfiles needed

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

Could you verify if performing [these](https://github.com/desktop/desktop/blob/master/docs/known-issues.md#window-is-hidden-after-detaching-secondary-monitor---2107) steps resolves the issue? This is mostly for my curiosity because I think this is the first report where the app is lost due to a multi-monitor remote session.

**Comment by me89** [comment]
@iAmWillShepherd Yes, I tried it more often, especially to reduce this issue to its problem.

**Comment by me89** [comment]
@iAmWillShepherd, if I delete the "window-state.json", the window is resets and appears normaly again. The linked issue #2107 describes nearly the same issue. The only difference is, that I'm using a remote session, which should not make a difference. Its caused from the changed Windows-Display environment.

**Comment by iAmWillShepherd** [comment]
Yes, the workaround linked came from that issue. Since this is a known-issue with a workaround that seems to work for you, I'm going to close this issue out. Please use #2107 for any additional details.

**Comment by me89** [comment]
refering to: #2107
