### ISSUE TITLE
"Remove" default menu item needs to be aware of user preference

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#4976]
Following on from #4975, the top-level **Repository** | **Remove** menu item needs to be aware of whether the user has this set:

<img width="336" alt="screen shot 2018-06-20 at 11 19 07 am" src="https://user-images.githubusercontent.com/359239/41664586-716b84c8-747c-11e8-98df-a357d99cbbba.png">

<img width="601" src="https://user-images.githubusercontent.com/359239/41664325-ddfb219e-747b-11e8-8ba3-53e6bb7940f6.png">

I wasn't able to fix this in #4975 because we don't have an easy way to get access to this setting (which is managed by the renderer) when generating the menu entries (which is managed by the main process).

[`build-default-menu.ts`](https://github.com/desktop/desktop/blob/061fc8e21caf5640363ae8cdb4f3f9c5c09f6b5e/app/src/main-process/menu/build-default-menu.ts#L21-L25) is the place to make this change, as well as the [related IPC call](https://github.com/desktop/desktop/blob/061fc8e21caf5640363ae8cdb4f3f9c5c09f6b5e/app/src/lib/stores/app-store.ts#L1350-L1364) from the renderer, but this is a potential opportunity to think about how to rethink this area rather than adding another parameter.

**Comment by iAmWillShepherd** [comment]
We have an event handler in `main.ts` which may be a good starting point.

https://github.com/desktop/desktop/blob/061fc8e21caf5640363ae8cdb4f3f9c5c09f6b5e/app/src/main-process/main.ts#L207-L223

The function that you can call to update the menu items is in `app-store.ts`.

https://github.com/desktop/desktop/blob/061fc8e21caf5640363ae8cdb4f3f9c5c09f6b5e/app/src/lib/stores/app-store.ts#L1350-L1364

`localStorage.getItem(confirmDiscardChangesKey)` should be enough to get the value of the setting.

**Comment by Daniel-McCarthy** [comment]
I am interested in this issue as I would like to learn some more about Electron and how the core of the program is set up. This issue deals with the communication between main and renderer, which is great.

I would be more than happy to submit a pull request to add a parameter for the `Remove` label to be passed to main, however, this issue proposes rethinking this area.

Is this something there is still interest in? Are there goals in mind for what some kind of shake up to this area would help address?

**Comment by shiftkey** [comment]
@Daniel-McCarthy I think this is an interesting issue because of all the stuff that Electron touches. Feel free to dive into it when you've got time, I'd be happy to help with reviewing stuff...

**Comment by Daniel-McCarthy** [comment]
Excellent, I will submit a pull request soon regarding this Issue.

**Comment by shiftkey** [comment]
We had a go at getting this working in #6489 but it uncovered a race condition with the tests that needs to be addressed. https://github.com/desktop/desktop/pull/6489#issuecomment-452371517 contains the gory details, and for the moment this is blocked on figuring that out.
