### ISSUE TITLE
switching repositories sometimes shows old repository as selected momentarily

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#4981]
## Description

In some cases when switching repositories you'll notice a momentary "flicker" where selection switches to the previous repository.

Here's a GIF, slowed down to 15% of actual speed, of this in action:

![](https://user-images.githubusercontent.com/359239/41681047-d7bfa844-74a9-11e8-890e-e73f74a4dee8.gif)

## Version

* GitHub Desktop: 1.2.3 (also seen in recent betas)

* Operating system: Windows 10

## Steps to Reproduce

1. Add a bunch of repositories to the list (not sure if important)
2. Switch between them 

### Expected Behavior

New repository should remain selected until repository switcher is hidden

### Actual Behavior

A small percentage of the time (20%? hard to say) the selection will revert to the previous repository momentarily

**Comment by tierninho** [comment]
Tried to reproduce this and it appears to be fixed.
