### ISSUE TITLE
Use consistent sentence structure and adjust wording in CONTRIBUTING.md

### ISSUE THREAD

**Issue by JonahMoses** [desktop/desktop#4991]
In `CONTRIBUTING.md` we could possibly be more consistent around sentence structure and bullet points by not having bullet points and non complete sentences end in `.` (periods). 

Separately under the `Issue and Pull Request Labels` section, the description for `reviewer-needs-to-reproduce` currently reads: `Likely bugs, but haven't been reliably reproduced by a reviewer.`.

I'm suggesting changing the description to `Possible bugs, that haven't been reliably reproduced by a reviewer, yet` or `Possible bugs, that haven't yet been reliably reproduced by a reviewer` (thoughts/suggestions welcomed). This change helps convey the message that while a reviewer has not been able to reproduce it at this time, it is still on the radar. Plus I believe it reads a little easier.

PR Incoming, please do what you wish with it :)

**Comment by iAmWillShepherd** [comment]
Thanks for the report and the incoming PR!
