### ISSUE TITLE
Fail to start from WSL

### ISSUE THREAD

**Issue by minvedacat** [desktop/desktop#4998]
## Description

In a [WSL(Windows Subsystem for Linux)](https://docs.microsoft.com/en-us/windows/wsl/about) exclusively available on Windows 10, running `github` CLI command fail to start Github Desktop. 

## Version

* GitHub Desktop: 
Version 1.2.3

* Operating system: 
Microsoft Windows [Version 10.0.17134.112]
WSL enabled with Ubuntu 18.04

## Steps to Reproduce

1. Install WSL on a Windows 10 system by following [Microsoft's Guide](https://docs.microsoft.com/en-us/windows/wsl/install-win10), Ubuntu 18.04 is installed for example.
2. Install Github Desktop.
2. Start `bash`, `wsl` from Start Menu, or start from your installed Linux distro app `ubuntu`
3. Run `github` and you can observe the error message

### Expected Behavior

By running `github` in WSL should the application start as expected as it does in cmd, PowerShell and Git bash on Windows 10.

### Actual Behavior

The application won't start and a script error is printed.
```
sh: 0: Can't open /mnt/d/bob/AppData/Local/GitHubDesktop/bin/..\app-1.2.3\resources\app\static\github.sh
```

## Additional Information

As @shiftkey suggested, [this script](https://github.com/desktop/desktop/blob/master/app/static/win32/github.sh) which do start the application properly in Git Bash, cmd and PowerShell on Windows 10, should be modified to cover WSL.

If it is caused by unexpected behavior from WSL, we might need to check [WSL Github](https://github.com/Microsoft/WSL).

Since WSL keeps adding [more Linux distro](https://aka.ms/wslstore), they should be considered as well.

And regarding to #4641, WSL will be added to supported shell options, so this issue should be fixed by then so Github Desktop can start and be started from WSL.

**Comment by minvedacat** [comment]
I've some time to look into this 😃 

1. Since the script error says:
```
min@MMM:/mnt/d/joe5y$ github
sh: 0: Can't open /mnt/d/joe5y/AppData/Local/GitHubDesktop/bin/..\app-1.2.3\resources\app\static\github.sh
```
And the real path to `github.sh is:
```
min@MMM:/mnt/d/joe5y$ sh '/mnt/d/joe5y/AppData/Local/GitHubDesktop/app-1.2.3/resources/app/static/github.sh'
```
which successfully start the app, so actually earlier `/mnt/d/joe5y/AppData/Local/GitHubDesktop/bin/github` which compose the path here
```
#!/usr/bin/env bash
  DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  sh "$DIR/..\app-1.2.3\resources\app\static\github.sh" "$@"
```
that offered a wrong folder path(`echo $DIR`):
```
min@MMM:/mnt/d/joe5y/AppData/Local/GitHubDesktop/bin$ github
/mnt/d/joe5y/AppData/Local/GitHubDesktop/bin
sh: 0: Can't open /mnt/d/joe5y/AppData/Local/GitHubDesktop/bin/..\app-1.2.3\resources\app\static\github.sh
```

2. Also WSL doesn't understand the file path
``` 
min@MMM:/mnt/d/joe5y$ sh '/mnt/d/joe5y/AppData/Local/GitHubDesktop/..\app-1.2.3\resources\app\static\github.sh'
sh: 0: Can't open /mnt/d/joe5y/AppData/Local/GitHubDesktop/..\app-1.2.3\resources\app\static\github.sh
```

@shiftkey If I
m right, the code to generate `/mnt/d/joe5y/AppData/Local/GitHubDesktop/bin/github` need minor update.

**Comment by shiftkey** [comment]
@minvedacat probably - I had a look at the [VSCode script](https://github.com/Microsoft/vscode/blob/master/resources/win32/bin/code.sh) and it seems to do some WSL-specific checks. We should do the same.

**Comment by shiftkey** [comment]
Switching this back to `help-wanted` because I don't have the bandwidth currently to do this - you can see what I did in #5111 which I think was on the right track, if someone with WSL experience wants to help wrap it up.

**Comment by shawnfunke** [comment]
I will take a look at this.

**Comment by shawnfunke** [comment]
I will take a look at this
