### ISSUE TITLE
Clone Repos with SSH Instead of HTTPS

### ISSUE THREAD

**Issue by say25** [desktop/desktop#4999]
**Is your feature request related to a problem? Please describe.**
As part of my workflow, I prefer to clone repos with SSH over HTTPS.  I use an SSH key to execute git commands in GitBash (Windows) and VSCode as my GHE password is tied to an okta login.

**Describe the solution you'd like**
A way to clone a repo with SSH rather than HTTPS.

**Describe alternatives you've considered**
Maybe this is a user setting? Or if SSH key is present try cloning with that first?

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to contribute!

We are tracking this in #2579, so I'm going to close this issue out.
