### ISSUE TITLE
Group repositories

### ISSUE THREAD

**Issue by lambidu** [desktop/desktop#5000]
Please, add a way to create named groups of repositories.

Something like
![image](https://user-images.githubusercontent.com/2502621/41761509-3e4d4fd8-7600-11e8-9a0b-7aaf9469af49.png)

For now, there are two groups: "GitHub.com" and "Other". 
Let us give to give them a meaningful name, and create other groups too.

**Comment by bwleon** [comment]
This would be helpful too if you have repos in development and production servers with the same name.

**Comment by iAmWillShepherd** [comment]
We have an issue tracking something similar,  #1533. I'm going to close this one out in favor of that one. I encourage you to chime in on the conversation there.
