### ISSUE TITLE
Typing "Enter" While Cursor is in Commit Summary Field No Longer Triggers Commit

### ISSUE THREAD

**Issue by Kelderic** [desktop/desktop#5004]
## Description

I just upgraded from the old version of GitHub Desktop to the current Electron-based version. I have noticed a regression. After I select which changes I want to commit, and type in a summary, I hit "enter", but the commit no longer happens.

## Version

* GitHub Desktop: v1.2.3

* Operating system: Windows 10 (1803)

## Steps to Reproduce

1. Open GitHub Desktop
2. Make a change to the selected repo.
3. Enter text in the "Summary (required)" field.
4. Hit "enter" key.

### Expected Behavior

The changes should be commited.

### Actual Behavior

Nothing happens. (I have to go down and click on the "Commit to [BRANCH]" button.

**Comment by shiftkey** [comment]
@Kelderic thanks for the report.

This was an inconsistency between the classic macOS and Windows versions that we decided to finally unify behind <kbd>Command</kbd> + <kbd>Enter</kbd> on macOS and <kbd>Ctrl</kbd> + <kbd>Enter</kbd> on Windows and Linux.

#1594 has some more details about the discussion.

**Comment by zekrom-vale** [comment]
I still would prefer an option for it to work in the summary field as "Enter" has no purpose.
