### ISSUE TITLE
black screen is coming while opening github desktop 

### ISSUE THREAD

**Issue by arunph** [desktop/desktop#5007]
## Version

* GitHub Desktop:1.2.3

* Operating system:windows 8.1

### Expected Behavior

it should show the UI of application program
### Actual Behavior

showing black screen in place of actual UI of application

**Comment by shiftkey** [comment]
@arunph thanks for the report!

Are you running Windows? This might be a known issue with some graphics card drivers and hardware acceleration. There's [a workaround](https://github.com/desktop/desktop/blob/master/docs/known-issues.md#i-get-a-black-screen-when-launching-desktop) in our Known Issues doc that might work for you!

**Comment by arunph** [comment]
yaa i'm running in windows.

**Comment by shiftkey** [comment]
@arunph can you confirm the workaround addresses the issue for you?

**Comment by arunph** [comment]
it had got fixed.since i run the github desktop via external graphics
