### ISSUE TITLE
Add support for previewing PDF files

### ISSUE THREAD

**Issue by dtabell** [desktop/desktop#5009]
**Is your feature request related to a problem? Please describe.**
In the previous version of GitHub Desktop, before committing, for example, a pdf image to my repo, I would see a preview of that image. Now I just see "This binary file has changed." together with a link that allows me to "Open file in external program."

**Describe the solution you'd like**
Please restore the ability to preview images being committed.

**Describe alternatives you've considered**
None. This is a request to restore a deleted feature.

**Comment by shiftkey** [comment]
> In the previous version of GitHub Desktop, before committing, for example, a pdf image to my repo, I would see a preview of that image. 

What's the image file extension you are working with, and which OS are you using?

**Comment by dtabell** [comment]
I noticed this specifically for .pdf files.
On Mac OS X. Version 10.13.5.

Thanks,
Dan

**Comment by shiftkey** [comment]
Classic Desktop on macOS did support rendering PDFs natively, but Desktop Electron only has support for image-based formats currently. The equivalent work wasn't done for Windows, so this work was deferred.

This PR https://github.com/electron/electron/pull/8435 shows that Electron supports rendering PDFs, but that looks like a full-window experience - that might not be suitable for doing diffs without a bunch of additional work.

Marking this as `help wanted` for someone to explore what's possible currently and how to fit it into our existing diff experience.

**Comment by dtabell** [comment]
Dear Brendan,

Thanks for you very quick response.

Okay ... I'm puzzled, because here's a screenshot of what I see
in the previous version of GitHub Desktop:



So when you say, “Classic Desktop on macOS did not support
rendering PDFs natively”, I don't understand. If I click on the
.jpg, then I can see the corresponding photograph there in my
GitHub Desktop. Here's another screenshot:



That is a multi-page pdf, and I cannot see beyond the first page,
so perhaps that is what you mean by “natively”. But I could at
at least see the cover—helpful for knowing whether I want to
commit that file now or later. The corresponding image from the
new GitHub Desktop is the following screenshot:



Not what I was hoping for.

When you say "Desktop Electron", are you referring to the new
(v.1.2.3) GitHub Desktop I downloaded earlier today, or to the
GitHub Desktop app with some additional plugin?

Thanks again,
Dan

**Comment by shiftkey** [comment]
@dtabell the images did not come through in your reply. Are you able to add them again on the website?

**Comment by dtabell** [comment]
Sure
Will do that momentarily.
Dan

**Comment by dtabell** [comment]
Okay ... I'm puzzled, because here's a screenshot of what I see in the previous version of GitHub Desktop: 

<img width="512" alt="image" src="https://user-images.githubusercontent.com/11483676/41795208-31657c40-761f-11e8-9cd6-37b0f635dd2f.png">

**Comment by dtabell** [comment]
<img width="1282" alt="gd" src="https://user-images.githubusercontent.com/11483676/41795244-4e777dd8-761f-11e8-84e4-5b78f29cb8fe.png">

**Comment by dtabell** [comment]
So when you say, “Classic Desktop on macOS did not support rendering PDFs natively”, I don't understand. If I click on the .jpg, then I can see the corresponding photograph there in my GitHub Desktop. Here's another screenshot: 
<img width="1282" alt="gd2" src="https://user-images.githubusercontent.com/11483676/41795292-788d3e00-761f-11e8-89f2-d9b08259e358.png">

**Comment by dtabell** [comment]
That is a multi-page pdf, and I cannot see beyond the first page, so perhaps that is what you mean by “natively”. But I could at at least see the cover—helpful for knowing whether I want to commit that file now or later. The corresponding image from the new GitHub Desktop is the following screenshot: 
![gd3](https://user-images.githubusercontent.com/11483676/41795333-93891008-761f-11e8-8e66-b5a8d0eeb715.png)
Not what I was hoping for.

**Comment by shiftkey** [comment]
@dtabell 

> So when you say, “Classic Desktop on macOS did not support rendering PDFs natively”, I don't understand. 

[I didn't say that.](https://github.com/desktop/desktop/issues/5009#issuecomment-399532199)

> That is a multi-page pdf, and I cannot see beyond the first page, so perhaps that is what you mean by “natively”.

We don't treat PDFs in any special way with the Electron Desktop app. That's work that needs to be investigated and scoped.

**Comment by dtabell** [comment]
Sorry: my brain put a "not" in there. All on it's own. :-/

**Comment by billygriffin** [comment]
Thanks for the issue @dtabell! Since we haven't seen much further interest in this, I'm going to close it for now. However, we're more than happy to reopen if we see increased interest in PDF support and/or someone is able to weigh in here with how the implementation might work on Electron. Thanks again!

**Comment by JoseMath** [comment]
Hi, I am having the same issue @dtabell described. 
Was a fix or workaround provided for this?
Thank you
