### ISSUE TITLE
Toggle to enable hitting 'enter' for committing when only summary has been filled out

### ISSUE THREAD

**Issue by x775** [desktop/desktop#5014]
**Is your feature request related to a problem? Please describe.**
My feature request is not related to a problem.

**Describe the solution you'd like**
Sometimes I do not always need to add a description to what has been changed, and would thus like to go directly from writing a summary to committing the changes by simply hitting _enter_. I am explicitly suggesting making it a toggle as some users might not be interested in having this feature.

**Describe alternatives you've considered**
None. This would simply be an alternative to clicking with the mouse.

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

This is currently already something you can accomplish by using the shortcut, <kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>Enter</kbd>.
