### ISSUE TITLE
Keyboard Shortcut for Delete Branch

### ISSUE THREAD

**Issue by 1pete** [desktop/desktop#5018]
**Is your feature request related to a problem? Please describe.**
Currently the instructions to delete branch are to open menu in menu bar, which require mouse movement and a few clicks. In large monitor menu bar is also quite far from application window 😛 

**Describe the solution you'd like**
Add keyboard shortcut e.g. `cmd+shift+D`, after pressing them, the delete branch popup will appear, just like normal flow when you select menu item from menu bar.

Thanks

**Comment by tongovan** [comment]
@398¢$DDDJJ
