### ISSUE TITLE
when clicking on the hash id for a commit, it could open the commit inside a browser on github.com 

### ISSUE THREAD

**Issue by Chris1904** [desktop/desktop#5021]
**Describe alternatives you've considered**
It would be great if you could click on this commit hash

<img width="740" alt="screen shot 2018-06-25 at 7 39 06 am" src="https://user-images.githubusercontent.com/6228425/41857750-15f2bc90-784d-11e8-99f6-cea13a241a96.png">

it would open GitHub's commmit history for that specific commit.

**Teachability, Documentation, Adoption, Migration Strategy**
I think this is a great feature as I used this a lot in a earlier GitHub Mac version. When I switched to the Electron version, this feature was removed.

Thanks for considering!

**Comment by shiftkey** [comment]
@Chris1904 thanks for the suggestion!

We originally had it this way, but we were wrestling with the inconsistent UX between clickable links, a "more actions" menu (like the classic Mac app) and the context menu in the commit history.  This comment is a pretty good summary of the situation: https://github.com/desktop/desktop/pull/2045#issuecomment-319469090

We eventually settled on unifying behind the context menu, which is where this action now lives:

<img width="361" src="https://user-images.githubusercontent.com/359239/41858817-240445be-7871-11e8-82e8-6352902c1bbb.png">

For the moment, we're going to stick to that approach to be consistent with where to place commit-related actions.
