### ISSUE TITLE
Dark Theme Beta Diff Colors Are Not Ideal

### ISSUE THREAD

**Issue by JosephTLyons** [desktop/desktop#5027]
I'm testing the new beta version of the new dark theme and the only issue I'm having is that the green and red colors used to represent added lines and deleted lines are too dark (the green for sure it seems).  You can still see where the colors start and stop in the lines of code, but they do not jump out at you like they do in the normal theme (which is expected, but not to this degree).  I think having brighter colors here would help out a bit for those with eyes that are not entirely great.

<img width="813" alt="screen shot 2018-06-25 at 2 53 58 pm" src="https://user-images.githubusercontent.com/19867440/41869688-bd5a3dac-7887-11e8-8299-e31ad53e88ee.png">

**Comment by JosephTLyons** [comment]
The Git diff colors used in Atom, when using a darker theme, seem to be more appropriate:

<img width="964" alt="screen shot 2018-06-25 at 3 20 17 pm" src="https://user-images.githubusercontent.com/19867440/41870945-7bd4a382-788b-11e8-9f4c-b372ccb8d385.png">

**Comment by lenis2000** [comment]
Could not agree more. I have partial color blindness and cannot even distinguish these colors. I would like to see this changed.

**Comment by shiftkey** [comment]
@JosephTLyons thanks for the info. For reference, I think these are the relevant colours to compare:

 - **Diff context**
   - Background: `#282c34`
   - Font color: `rgba(157, 165, 180, 0.6)`
 - **Added line:**
   - Background: `#1e4839`
   - Text color: `#b9e0d3`
 - **Removed line:**
   - Background: `#4c232d`
   - Text color: `#e8b9b8`

**Comment by shiftkey** [comment]
@lenis2000 we've asked for details about the existing color selection on Desktop and GitHub The Website in #4913 from people who are affected by color blindness - could you add to that discussion? 

We're not opposed to changing these values, we'd just like to ensure we make the right choice - and that requires your insights.

**Comment by JosephTLyons** [comment]
While I'm generally opposed to having a slew of options thrown at the user, causing ["Option Paralysis"](https://www.urbandictionary.com/define.php?term=option%20paralysis), I think it might be smart to provide the user with maybe 2-3 diff color presets that vary the brightness.  This would avoid trying to picking a definitive set that tries to please everyone, but avoids slinging a nasty color palette for people to muck around with.

**Comment by JosephTLyons** [comment]
While I'm generally opposed to having a slew of options thrown at the user, causing ["Option Paralysis,"](https://www.urbandictionary.com/define.php?term=option%20paralysis) I think it might be smart to provide the user with maybe 2-3 diff color presets that vary the brightness.  This would avoid trying to picking a definitive set that tries to please everyone, but avoids slinging a nasty color palette for people to muck around with.

Of course, if this is something GH would prefer to avoid, finding an optimum set of colors that best suits the majority is the next best thing.

**Comment by greg-grondecki-infotrack** [comment]
I'm not colorblind, but I think the green is way too dark. With flux enabled, it looks more black than the background. It would be much better in a brighter color, the one in @JosephTLyons 's screenshot looks great. Also, how about simply adding a separate set of colors for colorblind users?

**Comment by j-f1** [comment]
I’ve also seen some apps (such as Trello) have an option for colorblind people fragrance adds a pattern to things differing only by color, but I don’t know how well that would work here.

**Comment by jtlowe** [comment]
I'm very excited about this theme! Any reason to keep a very dark green, such as compatibility with a particular syntax highlighting? Here's my thought on a green color.

![github-desktop-dark-diff-colors](https://user-images.githubusercontent.com/766226/42046602-d4de4746-7ac3-11e8-8c16-91f95d7cce86.png)

* Added line:
  * background:  #0c4532
* Added inner:
  * background: #188a64
  * color: #e5e9ee

**Comment by JosephTLyons** [comment]
@jtlowe , that definitely seems to be a big improvement for sure.

**Comment by ampinsk** [comment]
Hey everyone, thanks for all your input! I started a PR to address this, I'd love to hear your thoughts in #5094 😄

**Comment by JosephTLyons** [comment]
Diff colors are much better in v1.3.0.  Thanks!
