### ISSUE TITLE
visual indicators when hovering would help emphasize interactive parts of the app

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#5030]
Extracted from #4989 

@jsunsawyer called out some feedback about our current visual theme: 

> There are several instances where a visual indicator (background change or darkened text) on hover would help users be sure that they're in the right spot before they click. Right now, you just have to click and hope that your mouse was in the right spot. It just slows you down a bit.
> 
> Places where hover states would help:
> 
> - Switching repositories
> - Switching tabs (Changes vs History and Branches vs Pull Requests)
> - Selecting a file to view in the Changes or History views
> - Selecting a branch to compare
> - Selecting a previous commit in the History view
> - Selecting a different branch or pull request
>
> At the very least, the cursor should change from an arrow to a pointer when you hover over an interactive element.

**Comment by xt0rted** [comment]
Another spot that lacks a hover indicator is the files list for a commit

**Comment by j-f1** [comment]
I’m wondering if this is a good idea. While many web apps do this sort of thing, I feel like most native apps don’t, and that’s one of the factors that makes them feel native.

**Comment by shiftkey** [comment]
I'm going to drop `themes` from this while we experiment with figuring out how to address this.

**Comment by billygriffin** [comment]
Added the new `user-research` label to convey that this would benefit from validation with external users.

Generally, however, I agree with the idea that giving users an indication that something is clickable is a good practice and that visual feedback can be very helpful. We do this in a few other instances in Desktop, just not everywhere. For example, the tabs "Current Repository", "Current Branch," and Push/Pull/Fetch all have a lighter hover state. 

I'd love thoughts from @donokuda and/or @ampinsk too.

With a bit more scoping and validation, could this also be something appropriate for a contributor from the community?
