### ISSUE TITLE
In-app pull request

### ISSUE THREAD

**Issue by Boundarybreaker** [desktop/desktop#5032]
Github Desktop Electron does not have an efficient PR system.

In Github Desktop Classic, you could create and submit a pull request to the head without having to use a web browser. In the new Electron version, however, that's not possible. There's no "make a PR" button in the gui, and hitting the ctrl-R (or ⌘-R on mac) command for opening a PR just opens the compare page in the default browser. The one-click method of Classic is gone, which slows down the process to make a PR massively.

Optimally, a one-click PR in Electron would work similarly to the Classic system:
![](https://dsc.cloud/b0undarybreaker/Capto_Capture-2018-06-25_05-42-16_PM.png)
You can just click the PR button, choose the head, write a description, and send the PR in. No need to launch a browser, click through the comparison tab, then write the PR.

**Comment by shiftkey** [comment]
@Boundarybreaker thanks for the feedback! We're tracking this in #295, so please follow along with that discussion.
