### ISSUE TITLE
Failed to locate pre-commit hook

### ISSUE THREAD

**Issue by JoeyLi-1** [desktop/desktop#5036]
## Description
The latest version popup error when I try to commit code.
![image](https://user-images.githubusercontent.com/20162464/41900909-4b8dae62-7962-11e8-82c3-2db6e02853fd.png)

This works fine before I upgraded to the latest version.

## Version
* GitHub Desktop:
1.2.6
* Operating system:
Win10

## Steps to Reproduce
Install precommit (https://github.com/observing/pre-commit)
Add 

> "precommit": {
        "run": "tslint"
    },

to package.json

And commit anything, you will see that error.

## Additional Information
I found this issue in dugite https://github.com/desktop/dugite/issues/96
And the latest version of Githubdesktop use ASAR file as well, so there might have some connection. 
Hope this could help somehow.

### Logs

> 2018-06-26T08:55:27.234Z - info: [ui] [AppStore] loading 2 repositories from store
2018-06-26T08:55:27.235Z - info: [ui] [AppStore] found account: JoeyLi-1 (Joey Li)
2018-06-26T08:55:27.721Z - info: [ui] launching: 1.2.6 (Windows 10.0.17134)
2018-06-26T08:55:27.721Z - info: [ui] execPath: 'C:\Users\joey\AppData\Local\GitHubDesktop\app-1.2.6\GitHubDesktop.exe'
2018-06-26T08:55:28.739Z - warn: [ui] fetchRepository: 'clarifyhealth/carepilot-web' returned a 404
2018-06-26T08:55:35.034Z - error: [ui] `git commit -F -` exited with an unexpected code: 1.
error: cannot spawn .git/hooks/pre-commit: No such file or directory

Please review this issue. Thank you!

**Comment by shiftkey** [comment]
@JoeyLi-1 thanks for the report. I haven't been able to reproduce the issue using those steps provided.

Here's my `package.json` file after installing `precommit-hook`:

```json
{
  "name": "pre-commit-hook",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "lint": "jshint .",
    "validate": "npm ls"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "precommit": {
    "run": "tslint"
  },
  "pre-commit": [
    "lint",
    "validate",
    "test"
  ],
  "devDependencies": {
    "precommit-hook": "^3.0.0"
  }
}
```

It seems to be configured to run all three scripts as part of the pre-commit, so I skipped over step 2 in your steps.

What I was expecting to happen when I made a commit that it'd fail (because I don't have `jshint` installed) but committing anything would succeed.

I also checked the `.git/hooks` folder and none of the commit hooks were enabled:

```sh
$ ls .git/hooks
applypatch-msg.sample*      pre-applypatch.sample*      pre-rebase.sample*
commit-msg.sample*          pre-commit.sample*          pre-receive.sample*
fsmonitor-watchman.sample*  prepare-commit-msg.sample*  update.sample*
post-update.sample*         pre-push.sample*
```

What am I missing?

**Comment by JoeyLi-1** [comment]
@shiftkey My bad! I attached wrong package link. It should be https://github.com/observing/pre-commit

There will be precommit hook enabled in the .git/hooks folder.

Really sorry about that!!!

**Comment by shiftkey** [comment]
@JoeyLi-1 I updated my `package.json` script to this:

```js
{
  "name": "pre-commit-hook",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "lint": "jshint .",
    "validate": "npm ls"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "precommit": {
    "run": "tslint"
  },
  "devDependencies": {
    "pre-commit": "^1.2.2"
  }
}
```

And then ensured I was working from a clean slate:

```sh
$ git clean -xdf
$ rm -rf .git/hooks/*
$ npm i
```

This then populates the pre-commit hook as expected:

```sh
$ cat .git/hooks/pre-commit
#!/bin/bash
./node_modules/pre-commit/hook
RESULT=$?
[ $RESULT -ne 0 ] && exit 1
exit 0
```

I'll call out here that `/bin/bash` is not guaranteed to be available with Git for Windows - I worked with the Husky project to ensure they only needed `/bin/sh` for their scripting needs over in https://github.com/typicode/husky/issues/228#issuecomment-362394984 so I think that is something that needs to be addressed upstream.

Putting that aside, I tried to make a commit in Desktop and got this error:

```
Commit failed - exit code 1 received, with output: '.git/hooks/pre-commit: line 2: ./node_modules/pre-commit/hook
: No such file or directory
.git/hooks/pre-commit: line 4: [: 127
: integer expression expected
.git/hooks/pre-commit: line 5: exit: 0
: numeric argument required'
```

This feels like the Git embedded in Desktop isn't able to work with the bash syntax provided. That's fine. On the command line (where the full `bash` environment is available), the commit fails because `tslint` can't be found:

```sh
$ git commit -m "whatever"
pre-commit:
pre-commit: We've failed to pass the specified git pre-commit hooks as the `tslint`
pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit:
pre-commit:   git commit -n (or --no-verify)
pre-commit:
pre-commit: This is ill-advised since the commit is broken.
pre-commit:
```

So I'm still not sure how my setup is still different to yours to show the original issue - I was seeing that `npm install` is only run as part of the `install` hook in Node:

```sh
$ npm i

> pre-commit@1.2.2 install C:\Users\shiftkey\src\test\pre-commit-hook\node_modules\pre-commit
> node install.js

pre-commit:
pre-commit: Detected an existing git pre-commit hook
pre-commit: Old pre-commit hook backuped to pre-commit.old
pre-commit:
```

That might explain why the `.git/hooks/pre-commit` file isn't existing in the repository, but it's not the whole solution to the problem.

**Comment by JoeyLi-1** [comment]
@shiftkey I had created a demo repo. https://github.com/JoeyLi-1/angular2-force
Please clone this repo and change anything and then commit. You will see the error notification.

**Comment by shiftkey** [comment]
@JoeyLi-1 same thing

<img width="991" src="https://user-images.githubusercontent.com/359239/41935648-c907ade0-7960-11e8-8021-2c6495c62302.png">

**Comment by JoeyLi-1** [comment]
@shiftkey  That is wired.
Here is what I did:
* a clean folder -> clone angular2-force
* change some file and commit
![image](https://user-images.githubusercontent.com/20162464/41948220-48d06476-79ee-11e8-9128-7b15560e6356.png)
My system: Win10 pro / home (able to reproduce on both of them)
git / node / npm versions:
![image](https://user-images.githubusercontent.com/20162464/41948213-4196d97e-79ee-11e8-8b25-b1f8bf0970cc.png)
git desktop version:
![image](https://user-images.githubusercontent.com/20162464/41948334-c80e91cc-79ee-11e8-91b4-925a61ba3795.png)

package.json:

> {
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "description": "QuickStart package.json from the documentation, supplemented with testing support",
  "scripts": {
    "start": "tsc && concurrently \"tsc -w\" \"lite-server\" ",
    "docker-build": "docker build -t ng2-quickstart .",
    "docker": "npm run docker-build && docker run -it --rm -p 3000:3000 -p 3001:3001 ng2-quickstart",
    "e2e": "tsc && concurrently \"http-server\" \"protractor protractor.config.js\"",
    "lint": "tslint ./app/**/*.ts -t verbose",
    "lite": "lite-server",
    "postinstall": "typings install",
    "test": "tsc && concurrently \"tsc -w\" \"karma start karma.conf.js\"",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings",
    "webdriver:update": "webdriver-manager update"
  },
  "precommit": {
    "run": "lint"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.1",
    "@angular/upgrade": "2.0.0-rc.1",
    "systemjs": "0.19.27",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.12",
    "angular2-in-memory-web-api": "0.0.7",
    "bootstrap": "^3.3.6"
  },
  "devDependencies": {
    "canonical-path": "0.0.2",
    "concurrently": "^2.0.0",
    "http-server": "^0.9.0",
    "jasmine-core": "~2.4.1",
    "karma": "^0.13.22",
    "karma-chrome-launcher": "^0.2.3",
    "karma-cli": "^0.1.2",
    "karma-htmlfile-reporter": "^0.2.2",
    "karma-jasmine": "^0.3.8",
    "lite-server": "^2.2.0",
    "lodash": "^4.11.1",
    "pre-commit": "^1.2.2",
    "protractor": "^3.3.0",
    "rimraf": "^2.5.2",
    "tslint": "^3.7.4",
    "typescript": "^1.8.10",
    "typings": "^0.8.1"
  },
  "repository": {}
}


What else information do you need to reproduce this issue? Thank you!

**Comment by JoeyLi-1** [comment]
BTW, it works fine in window cmd.
![image](https://user-images.githubusercontent.com/20162464/41948519-c0dacb22-79ef-11e8-8c8b-81441c72e1b6.png)

**Comment by JoeyLi-1** [comment]
> #!/bin/bash
./node_modules/pre-commit/hook
RESULT=$?
[ $RESULT -ne 0 ] && exit 1
exit 0

My pre-commit

**Comment by JoeyLi-1** [comment]
Environment: Path
![image](https://user-images.githubusercontent.com/20162464/41954891-48ce2a54-7a10-11e8-9ed2-9b95c8056028.png)
![image](https://user-images.githubusercontent.com/20162464/41954893-4ceee920-7a10-11e8-951b-43b5d376af73.png)

**Comment by shiftkey** [comment]
@JoeyLi-1 the part that I'm not able to understand is this error message:

![](https://user-images.githubusercontent.com/20162464/41948220-48d06476-79ee-11e8-9128-7b15560e6356.png)

There's two parts to this error message - Git tries to make the commit and fails (the `commit failed: exit code 1` part) and the source of this error. The `error: cannot spawn` part of the message really looks like Git trying to [run a command](https://github.com/git/git/blob/f15a486ca1dd67757cb6a3c0545dc2c6ef992bc3/run-command.c#L897-L898):

```c
	if (cmd->pid < 0 && (!cmd->silent_exec_failure || errno != ENOENT))
		error_errno("cannot spawn %s", cmd->argv[0])
```

But you say that the `pre-commit` file exists at the right location? I'm not sure how else to debug this, and my gut feeling is you're going to encounter this error once you figure it out:

![](https://user-images.githubusercontent.com/359239/41935648-c907ade0-7960-11e8-8021-2c6495c62302.png)

**Comment by JoeyLi-1** [comment]
@shiftkey Finally, I found out the reason. After I added "C:\Program Files\Git\bin" to the system environment "path", it works. the git/bin contains the bash which is required by my pre-commit hook.

Not sure why the old githubdesktop application worked fine without this environment path......

However, it works. Thank you for your help! :)

**Comment by TNT-Likely** [comment]
@JoeyLi-1 it works fine for me ,thank you

**Comment by MaAnShanGuider** [comment]
thanks a lot.

**Comment by nemostudent** [comment]
![image](https://user-images.githubusercontent.com/53701833/89759858-c1b51680-daf3-11ea-81b9-df652104b43f.png)
After I added \Git\bin in path
