### ISSUE TITLE
Add option to disable "commits behind" notification (NDDB)

### ISSUE THREAD

**Issue by thinkyhead** [desktop/desktop#5042]
**Is your feature request related to a problem? Please describe.**

Not all project branches bear a direct relationship to my default branch. Yet, every branch I open or create bears this notification, which simply clutters the interface.

![image](https://user-images.githubusercontent.com/698003/41936152-e5818040-7951-11e8-9d1f-87ec9280c8e8.png)

**Describe the solution you'd like**

I would prefer that these notifications didn't appear at all. I would like to be able to simply turn them off.

**Describe alternatives you've considered**

I maintain a lot of short-lived feature branches and branches pulled from contributor repositories, so it would be unwieldy to have to inform GitHub Desktop about which should show me a warning and which should not.

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

What version of Desktop are you running? This is feature is still in the works and was shipped too soon due to a feature flag issue. No matter your response, this is really good feedback 🙇 . 

Would adding a preference that allows you to opt-in to this feature be a good first step to solving your immediate problem?

cc @desktop/design

**Comment by thinkyhead** [comment]
The issue is currently gone, I assume because it was removed in the most recent update.

A preference option would be good. And/or a little deeper digging by the app so that it compares to the branch's own upstream remote and notifies about any disparities compared to that. It would then also be able to target PRs to the appropriate upstream remote branch, or allow direct commits to the upstream remote in those cases where (for example) a maintainer has write access because the branch has an associated PR already.

**Comment by iAmWillShepherd** [comment]
> The issue is currently gone, I assume because it was removed in the most recent update.

Yes, that feature was mistakenly enabled in the last release. Regarding the second part of your comment,

> And/or a little deeper digging by the app so that it compares to the branch's own upstream remote and notifies about any disparities compared to that. 

We are currently doing something like that. Check out #4766 for more details in how we determine what branch to use.

**Comment by iAmWillShepherd** [comment]
I'm going to close out this issue since the WIP feature is no longer enabled, but we can continue having this conversation if you'd like 👍

**Comment by thinkyhead** [comment]
Thanks for the followup. Looks like you're on top of it with 4766!

**Comment by iAmWillShepherd** [comment]
Reopening this issue since @desktop/core agreed that having the option to disable notification is a good thing.

**Comment by shiftkey** [comment]
@iAmWillShepherd is this in scope for 1.3.0, or are you fine with following up in a bugfix update?

**Comment by iAmWillShepherd** [comment]
I answered this in Slack, short story is I moved this issue to milestone 1.3.x

**Comment by billygriffin** [comment]
@thinkyhead Thanks for this issue. As we haven't heard this more broadly as a pain point and this has been released for several months now, I'm going to close this. However, if we continue to hear things that indicate that we ought to allow this to be disabled and/or iterate on the concept, we'll be happy to revisit.
