### ISSUE TITLE
Text selection doesn't work on wrapped lines in the diff

### ISSUE THREAD

**Issue by greg-grondecki-infotrack** [desktop/desktop#5045]
## Description

When a line in the diff is long enough to wrap into the next line, it's impossible to select and copy text correctly. Selection is displayed as a rectangle covering both lines, as pictured in the screenshot below. When you try to copy the selection, only the content from the first line is copied, regardless of how you selected it.

## Version

* GitHub Desktop: 1.2.6

* Operating system: Microsoft Windows [Version 10.0.14393]

## Steps to Reproduce

1. Modify a file with long lines to cause the wrap to happen
2. Try to select the text in the wrapped line.

### Expected Behavior

I would expect it to work normally, i.e. the selection should allow you to select a fragment of the text taking into account the wrap.
### Actual Behavior

Displays a 2-line high rectangle and only allows to copy text from the first line.

## Additional Information

Picture of the behavior:
![image](https://user-images.githubusercontent.com/25468183/41952287-8b05293e-7a12-11e8-9694-53b4600422b7.png)

### Logs

I don't think the logs apply to this issue in any way.

**Comment by shiftkey** [comment]
@greg-grondecki-infotrack thanks for the report. This is already being tracked in #1551, so please follow along with that issue.
