### ISSUE TITLE
GithubDesktopSetup.exe detected as trojan. (27.06.2018)

### ISSUE THREAD

**Issue by MrDarker201** [desktop/desktop#5047]
Hello,
Today, I wanted to download Github Desktop
(From **https://desktop.github.com** This is the direct download link; **https://desktop.githubusercontent.com/releases/1.2.6-908a2695/GitHubDesktopSetup.exe**). 
To do the quick setup of a project.
After download, I uploaded the file to Virustotal and one antivirus detects it as a trojan.
I know there is already issue topic, but that was 1 year ago.
So, is this a false detection or not?
Below, I provide a screenshot.
![screenshot-2018-6-27 
virustotal](https://user-images.githubusercontent.com/34425939/41982258-41c4970a-7a2b-11e8-8558-875087046060.png)

**Comment by shiftkey** [comment]
@MrDarker201 I tried the same file and got no issues: https://www.virustotal.com/#/url/e9e8b2ab008cb3aa33f22c56fa0a8825ad671657219c83024fdb3695c08f622b/detection 

Jiangmin wasn't in the list of AV products tested for me, but I suspect this is just a false detection.

**Comment by MrDarker201** [comment]
Ok, Thanks for replay.
