### ISSUE TITLE
Spring Load Mac Dock Icon

### ISSUE THREAD

**Issue by stevemoser** [desktop/desktop#5048]
**Is your feature request related to a problem? Please describe.**
I have project/repo/folder open in finder and I want to quickly open that repo in GitHub Desktop

**Describe the solution you'd like**
I want to be able to drag a folder to the GitHub Desktop dock icon which will open the corresponding repo in GitHub Desktop or offer to create it in GitHub Desktop if it doesn't already exist.

**Describe alternatives you've considered**
:|

**Teachability, Documentation, Adoption, Migration Strategy**
Many apps like VScode support this workflow.

**Comment by shiftkey** [comment]
@stevemoser I'm not opposed to seeing this supported. I had a quick look but couldn't figure out how to enable folder dropping onto the tray from the Electron APIs, but if someone knows about how to enable it they can add some more context here and we can figure out the rest of the work.

**Comment by stevemoser** [comment]
Looks like `ted .` is the ticket.

https://twitter.com/_inside/status/1014186936049766400

**Comment by shiftkey** [comment]
For anyone else looking for alternatives to this feature - you can drag-and-drop the folder _onto the Desktop window itself_ to add it. This works on all platforms.
