### ISSUE TITLE
see remote hocks results/outputs somewhere in application

### ISSUE THREAD

**Issue by MetaiR** [desktop/desktop#5054]
do you see MS visual studio code?

it has a terminal in the bottom of its page which you can appear and disappear it whenever you want, here a picture of it:

![image](https://user-images.githubusercontent.com/7807264/42014853-c8df28de-7ab9-11e8-95be-a8a3d9d8e727.png)

I think it will be awesome if there is such thing **or** something that shows remote outputs when we push commits because sometimes the hocks will be failed and this way we can see and solve it.

**Comment by shiftkey** [comment]
@MetaiR we're already tracking this suggestion in #1570 - please follow along with that issue as that adds context for why we haven't really explored that area.
