### ISSUE TITLE
cloning renamed repository uses old name and remote URL

### ISSUE THREAD

**Issue by dano-ai** [desktop/desktop#5055]
## Description

I cloned one of my own repository (dano-ai.github.io) using importer and changed the name to www-dano-ai.github.io

Desktop displays the name of repo correctly in the clone repository view but after cloning, there are 2 repos with the same name in the list of my repository (dano-ai.github.io) in Desktop. Also the newly created repo has been created in my local directory with the new name (www-dano-ai.github.io) but the remote origin in the repository setting of the new repo is still the old one.

## Version

* GitHub Desktop:
1.2.6

* Operating system:
Mac OS 10.13.4

## Steps to Reproduce
1. Import one's own repo using 'import repository' feature
2. clone the newly created repo using Desktop

### Expected Behavior
The name and the remote origin of the repo should be ones of the newly created repo

### Actual Behavior
The name and the remote origin of the repo are ones of the original repo

**Comment by shiftkey** [comment]
@dano-ai I'm trying to parse the steps here and understand the issue but some things aren't clear.

> I cloned one of my own repository (dano-ai.github.io) using importer and changed the name to www-dano-ai.github.io

What is this "importer" referred to here? Desktop supports **File** | **Add Local Repository** - are you referring to that?

Also, could you attach the full log files? The **Help** | **Show Logs in Finder** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @dano-ai if you're able to answer the questions from the previous comment we're happy to revisit this.
