### ISSUE TITLE
Issues while code uploading

### ISSUE THREAD

**Issue by varunsundraeshkovakkat** [desktop/desktop#5056]
Hello!

I am trying to upload code into a new branch.
My code contains Japanese characters encoded in SHIFT-JIS. But while uploading, these Japanese  characters become junk, which is not expected.
Could you please let us know how we can upload without these characters becoming junk.

Thank you!

**Comment by shiftkey** [comment]
@varunsundraeshkovakkat are you referring to the characters in the diff when viewing in Desktop? 

We're tracking https://github.com/desktop/desktop/issues/3923 which is a limitation around viewing non-UTF-8 diffs, but the contents of the file are preserved by Git and should look fine when publishing to GitHub.

**Comment by varunsundraeshkovakkat** [comment]
@shiftkey Yes that is right. It is the characters in diff when viewing in the Desktop.
We have tried to publish it on GitHub as it is. But, when we try to download the published file we get junk characters.

**Comment by shiftkey** [comment]
@varunsundraeshkovakkat it's hard to say without being able to work with a real repository - are you able to share some repro steps to illustrate the problem, as well as a sample file I can work with on my end to recreate the problem myself?

**Comment by varunsundraeshkovakkat** [comment]
@shiftkey please see the steps which were followed.
1. Cloned repository from the Desktop.
2. Created a new branch.
3. In that branch we uploaded the file which was modified.
4. Committed to the branch and checked the difference in Desktop. (Japanese characters appeared as junk). Screenshot of this is attached too.
![github_desktop](https://user-images.githubusercontent.com/22141365/42301869-4e0cfa2e-8035-11e8-8413-9ff779d8a198.PNG)

5. But after your advice, I tried to publish the branch on GitHub, but still Japanese characters appeared as junk.

Also, attached is the sample file which you can work with.
[UploadBLL_2.zip](https://github.com/desktop/desktop/files/2164859/UploadBLL_2.zip)

**Comment by shiftkey** [comment]
@varunsundraeshkovakkat thanks for the details and screenshots - it looks like the diff is at least showing some of the valid characters.

Is there also a particular editor you using alongside Desktop when making these changes? I want to confirm that it's not something external that is malforming the bytes on disk when saving changes, that Desktop is then committing.

**Comment by varunsundraeshkovakkat** [comment]
@shiftkey we have used Visual Studio. 
But, previously also we have used it and that time there was no such issue. Observing this issue lately.

**Comment by billygriffin** [comment]
This looks similar to https://github.com/desktop/desktop/issues/3923 in handling of non-UTF8 chars, so we're going to close this in favor of that one.
