### ISSUE TITLE
publish branch not using proxy for https

### ISSUE THREAD

**Issue by grandinj** [desktop/desktop#5058]
## Description

Not using proxy when attempting to push branch to github. Note that I have this with Microsoft Message Analyzer (i.e. microsoft's version of WireShark)

## Version

* GitHub Desktop:
    1.2.6, this used to work in versions before this, I updated fairly frequently
* Operating system:
  Windows 10

## Steps to Reproduce

Click publish branch.

### Expected Behavior

Should use the proxy I have configured in my Internet Proxy settings.

### Actual Behavior

It tries to establish a direct connection, instead of using the proxy.

### Logs

[2018-06-28.desktop.production.log](https://github.com/desktop/desktop/files/2145101/2018-06-28.desktop.production.log)

**Comment by shiftkey** [comment]
@grandinj thanks for the report.

Do you have a `http.proxy` setting in your global configuration?

```
git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080
```

That's what Git looks for when making any network calls. I don't believe it supports the Internet Proxy settings that ship with Windows.

**Comment by grandinj** [comment]
> I don't believe it supports the Internet Proxy settings that ship with Windows.

Aah, that is a great pity.

Thanks, your suggestion works. 

Open source software is pretty useless in general when it comes to proxies, nothing seems to read the system settings.

**Comment by burningTyger** [comment]
@shiftkey This is what dugite looks for, right? This is not about the HTTP_PROXY and HTTPS_PROXY env vars which are described in the dugite docs? They are used for running the dugite installer iirc. I'm finding the proxy situation quite frustrating too. Is there some way to avoid writing username and password into an unencrypted file?

**Comment by shiftkey** [comment]
@burningTyger `dugite` is just the NodeJS API for interacting with Git repositories - under the hood it's the same Git experience as the command line.

> Is there some way to avoid writing username and password into an unencrypted file?

Git also supports environment variables for this situation - if you set `HTTP_PROXY` to the value and remove the `http.proxy` config value it should achieve the same result.

**Comment by burningTyger** [comment]
@shiftkey thank you very much for the clarification
