### ISSUE TITLE
Jumping in commit history on out of focus

### ISSUE THREAD

**Issue by killerwife** [desktop/desktop#5059]
## Description

When Github Desktop goes out of focus, and the user is deep in commit history, more than one complete scrolldown (after the short mini loading), and the user alt tabs to any other application, on coming back into focus, Github Desktop jumps to last item in first complete scrolldown.

## Version

* GitHub Desktop: 1.2.6

* Operating system: Windows 10

## Steps to Reproduce

1. Have a repository with a lot of commits.
2. Scroll down at least 100 commits
3. Alt tab to any other application
4. Alt tab back to Github Desktop
### Expected Behavior

The commit viewer stays on the same commit as it was on before coming into focus.
### Actual Behavior

The commit viewer jumps to last commit in the first complete scrolldown inside Github Desktop.

## Additional Information

This is the video illustrating the issue. Small problem is that you cant see the other application I alt tab to.
Nonetheless, it does illustrate the annoying issue.
https://youtu.be/tuH_7cdHkz4
### Logs

Logs have no entries for this issue.

**Comment by shiftkey** [comment]
@killerwife thanks for the report. This feels similar to #4985 but with different repro steps. This requires some cleanup of components to ensure we're tracking the right state, and I'll keep an eye on these repro steps while I'm in here.
