### ISSUE TITLE
Extremely slow application

### ISSUE THREAD

**Issue by OakyElkoy** [desktop/desktop#5060]
Hello. I'm using Github Desktop (latest version, 1.2.6) and since a few weeks ago it has been incredibly slow to use. When I click something it feels like the entire application freezes for like 5 seconds.  Clicking a changed file in the "History" tab for example (to view the changes before commiting it) takes like 10 minutes for it to load the changes.. Please sort it, I dont want to start using sourcetree again...

**Comment by shiftkey** [comment]
@OakyElkoy thanks for the report.

There's [instructions here](https://github.com/desktop/desktop/blob/263a1ca60ba2eddb3e20b8f4da599778e76d9d55/docs/contributing/timeline-profile.md) to help grab profiling information from the running app to assist with troubleshooting - this will help greatly with understanding where the bottlenecks are for your setup.

**Comment by OakyElkoy** [comment]
@shiftkey I used CCleaner to uninstall Github desktop and also clean the registry, then re-installed the application. It seems to be fixed now, doesn't freeze at all anymore.

**Comment by shiftkey** [comment]
@OakyElkoy thanks for the update. If you notice anything out of the ordinary, grab that profiling information and we can try and troubleshoot things further!
