### ISSUE TITLE
Automatically update doesn't work

### ISSUE THREAD

**Issue by IsaiahJTurner** [desktop/desktop#5061]
## Description

I see a banner "An updated version of GitHub is available..." with a button "restart GitHub Desktop" but when I click the button, GitHub closes but never reopens. When I open it manually, it returns to version 1.2.5 and asks me to update again.

## Version

* GitHub Desktop: 1.2.5

* Operating system: OS X High Sierra 10.13.5 (17F77)

### Logs

> 2018-06-28T16:43:22.854Z - info: [ui] skipping fast-forward for all branches as there are 48 local branches - this will run again when there are less than 20 local branches tracking remotes
> 2018-06-28T16:46:20.548Z - info: [ui] [AppStore] loading 11 repositories from store
> 2018-06-28T16:46:20.550Z - info: [ui] [AppStore] found account: IsaiahJTurner (Isaiah J Turner)
> 2018-06-28T16:46:21.017Z - info: [ui] launching: 1.2.5 (Mac OS 10.13.5)
> 2018-06-28T16:46:21.017Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper.app/Contents/MacOS/GitHub Desktop Helper'
>

**Comment by shiftkey** [comment]
@IsaiahJTurner thanks for the report!

These two log files might help - can you find anything interesting at the end of these files that might tell us _which_ folder the updater is trying to create?

 - `~/Library/Caches/com.github.GitHubClient.ShipIt/ShipIt_stderr.log`
 - `~/Library/Caches/com.github.GitHubClient.ShipIt/ShipIt_stdout.log` (this was empty on my machine)

**Comment by IsaiahJTurner** [comment]
@shiftkey 
`ShipIt_stdout.log` is empty and `ShipIt_stderr.log` doesn't have any logs from the failed installations. The file has contents and it looks like these were the logs from the last time auto update worked. I think this is from when it updated to 1.2.5.
> 2018-06-25 13:47:13.037 ShipIt[8286:177174] Beginning installation
> 2018-06-25 13:47:13.865 ShipIt[8286:177289] Moved bundle from file:///Applications/GitHub%20Desktop.app/ to file:///var/folders/XX/randomstringXXXXXXXXXX/X/com.github.GitHubClient.ShipIt.XXXXXXX/GitHub%20Desktop.app
> 2018-06-25 13:47:13.866 ShipIt[8286:177289] Moved bundle from file:///var/folders/XX/randomstringXXXXXXXXXX/X/com.github.GitHubClient.ShipIt.YYYYYYY/GitHub%20Desktop.app to file:///Applications/GitHub%20Desktop.app/
> 2018-06-25 13:47:14.053 ShipIt[8286:177289] Couldn't remove owned bundle at location file:///var/folders/XX/randomstringXXXXXXXXXX/X/com.github.GitHubClient.ShipIt.YYYYYYY/GitHub%20Desktop.app, error NSError { domain: NSCocoaErrorDomain, code: 4, description: "“GitHub Desktop.app” couldn’t be removed.", failureReason: "The file doesn’t exist.", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: "The operation couldn’t be completed. No such file or directory" }, userInfo: {
>     NSFilePath = "/var/folders/XX/randomstringXXXXXXXXXX/X/com.github.GitHubClient.ShipIt.YYYYYYY/GitHub Desktop.app";
>     NSUserStringVariant =     (
>         Remove
>     );
> } }
> 2018-06-25 13:47:16.063 ShipIt[8286:177289] Installation completed successfully
> 2018-06-25 13:47:16.095 ShipIt[8286:177303] Application launched at file:///Applications/GitHub%20Desktop.app/
> 2018-06-25 13:47:16.095 ShipIt[8286:177303] ShipIt quitting
>

**Comment by shiftkey** [comment]
@IsaiahJTurner thanks for the log - this error suggests that it wasn't able to remove the old app (because it didn't exist at the time??!?!).

Are you able to remove those files and try updating again, to see if it succeeds or has a similar error?

```
018-06-25 13:47:14.053 ShipIt[8286:177289] Couldn't remove owned bundle at location file:///var/folders/XX/randomstringXXXXXXXXXX/X/com.github.GitHubClient.ShipIt.YYYYYYY/GitHub%20Desktop.app, error NSError { domain: NSCocoaErrorDomain, code: 4, description: "“GitHub Desktop.app” couldn’t be removed.", failureReason: "The file doesn’t exist.", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: "The operation couldn’t be completed. No such file or directory" }, userInfo: {
NSFilePath = "/var/folders/XX/randomstringXXXXXXXXXX/X/com.github.GitHubClient.ShipIt.YYYYYYY/GitHub Desktop.app";
NSUserStringVariant = (
Remove
);
} }
```

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @IsaiahJTurner please let us know if you're still having issues upgrading after trying this:

> Are you able to remove those (log) files and try updating again, to see if it succeeds or has a similar error?
