### ISSUE TITLE
Problems with full-screen mode

### ISSUE THREAD

**Issue by Specialist001** [desktop/desktop#5064]
When I run the program, it starts on full-screen mode. And without a menu tab

## Version

* GitHub Desktop: 1.2.6

* Operating system: Windows 7 x64

## Steps to Reproduce

![git](https://user-images.githubusercontent.com/31097426/42053577-52e49bce-7b2b-11e8-9cd7-02c36ce27f9a.jpg)

**Comment by Specialist001** [comment]
I'm sorry (( .   Found. It's button F11

**Comment by steveward** [comment]
@Specialist001 glad to hear you were able to get things working. Let us know if we can help with anything else!
