### ISSUE TITLE
No repos shown

### ISSUE THREAD

**Issue by rtm** [desktop/desktop#5066]
## Description

Even though I have lots of repos, the desktop shows none.

## Version

* GitHub Desktop: 1.2.6

* Operating system: W10

## Steps to Reproduce

1. Log in to personal account.
2. View repos.
3. No repos are shown.

**Comment by shiftkey** [comment]
@rtm thanks for the feedback!

The list of repositories in your app represents _local_ Git repositories, and on first start this is not populated. To clone repositories down from your GitHub account, choose **File** | **Clone repository...** to access these.

**Comment by shiftkey** [comment]
@rtm I'm going to close this out as "by design" but let me know if you have any other questions about this area of the app.
