### ISSUE TITLE
Error accessing GitHubDesktop.exe

### ISSUE THREAD

**Issue by Akashdave99** [desktop/desktop#5067]
## Description

**When I double click the 'GitHubDesktop.exe' file where it is installed it just crashes and show me a crash report.**

## Version

* GitHub Desktop: 1.2.6.0

* Operating system: Windows 8.1 32 bit

### Expected Behavior

It should open a window for Git GUI 
### Actual Behavior

Showing a crash report and opting to close

### Logs

![adfadf](https://user-images.githubusercontent.com/20316462/42079448-65b6d8a8-7b9d-11e8-8836-3a96a9264f0f.PNG)
[SquirrelSetup.log](https://github.com/desktop/desktop/files/2148221/SquirrelSetup.log)

**Comment by shiftkey** [comment]
@Akashdave99 thanks for the report!

Unfortunately GitHub Desktop doesn't have 32-bit support, so the error you are seeing is the expected behaviour. There's more details about this from an earlier discussion over in #1214, and we don't have plans to support 32-bit Windows on our roadmap.
