### ISSUE TITLE
Selected commit in Compare branch view gets replaced with latest when window regains focus

### ISSUE THREAD

**Issue by JonasAmrich** [desktop/desktop#5069]
## Description

When you select a commit in the Compare to Branch view, it's diff is presented in the right part of window. However when the window gets out of focus and then is focused again, this diff is replaced with latest commit's diff. Previously selected commit still looks selected and clicking on it doesn't refresh the diff. One has to select different commit to change presented diff. The issue is only present when a commit from "Behind" list is selected.

## Version

* GitHub Desktop: 1.2.6

* Operating system: macOS 10.13.4

## Steps to Reproduce

1. Go to "Compare to Branch" view
2. Select some branch
3. Select some commit from "Behind" list
4. Get the window out of focus / open different application
5. Refocus the window

### Expected Behavior

The diff should remain same

### Actual Behavior

The diff from the first commit on the branch is presented

**Comment by shiftkey** [comment]
@JonasAmrich thanks for the report! This feels very similar to #4985, which I'm looking into over in #5062. Can you confirm that's the same behaviour you're seeing?

**Comment by shiftkey** [comment]
I've done some testing and confirmed this will be resolved by #5062
