### ISSUE TITLE
address unmounted component issue in CommitMessage

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#5071]
Found this error in the React Dev Tools while investigating #5040 and wanted to ensure it was captured and addressed:

```
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in CommitMessage (created by ChangesList)
    in div (created by ChangesList)
    in ChangesList (created by ChangesSidebar)
    in div (created by ChangesSidebar)
    in ChangesSidebar (created by RepositoryView)
```

As the warning suggests, I think we need to detect when the `CommitMessage` component has been unmounted and avoid calling `setState` - we do this in a few places in `receiveProps`, which I think is the most likely culprit:

https://github.com/desktop/desktop/blob/1c443bcf02c59dbf0833975211c9cffaaaa489ea/app/src/ui/changes/commit-message.tsx#L125-L133

**Comment by ADustyOldMuffin** [comment]
I'd like to work on this if it's available still (I know it's been a hot second).

**Comment by shiftkey** [comment]
@ADustyOldMuffin go for it 🎉

**Comment by shiftkey** [comment]
Not able to reproduce this, so I gather it's been inadvertently fixed somehow...
