### ISSUE TITLE
List what files are over 100mb when reporting files are over 100mb.

### ISSUE THREAD

**Issue by owlboy** [desktop/desktop#5079]
**Is your feature request related to a problem? Please describe.**
When you have a file that is over 100mb in your repo and you push, it does the whole process and then tells you there is a file that is over 100mb. It does not tell you _what_ file(s).

**Describe the solution you'd like**
List the files that are too big. The old macOS app did this (As far as I can remember).

**Comment by shiftkey** [comment]
@owlboy this feels similar to #997, but that issue is focused on warning _before_ committing.

> The old macOS app did this (As far as I can remember).

Can you describe how you remember this feature working there? I'm not sure I stumbled upon that, and it might save time digging into the archives of history to wrap my head around that area.

**Comment by shiftkey** [comment]
@owlboy I'm going to close this in favour of #997 but feel free to add further to that issue if you can share what you remember the classic macOS app doing.

**Comment by owlboy** [comment]
@shiftkey Sorry it took me so long to get you a screenshot of what the old macOS app did:

<img width="534" alt="screen shot 2018-07-27 at 10 40 05 am" src="https://user-images.githubusercontent.com/237349/43330658-7d54213a-9189-11e8-89c0-a1249e3f3377.png">

<img width="529" alt="screen shot 2018-07-27 at 10 40 10 am" src="https://user-images.githubusercontent.com/237349/43330664-7f90e50a-9189-11e8-8691-88989e53fef1.png">

**Comment by hoverbird** [comment]
Please, yes, it's maddening to be told a file is blocking our push... with absolutely no further info. In some cases the file in question may have been committed ages ago before its type was tracked by LFS, leaving us no clear way to track down the issue.
