### ISSUE TITLE
GIT_ASKPASS error from clone after signing into GHE installation

### ISSUE THREAD

**Issue by irdw** [desktop/desktop#5082]
## Description
Unable to use Windows GitHub Desktop client 1.2.3 on a SSO GitHub Enterprise environment.

## Past behavior
When choosing the GitHub enterprise login option, it had the option to enter username and password (access token). Now the enterprise login is an SSO prompt which can get the user signed in but cannot perform any actions (clone,push,etc). There is no place to use access token as it redirects to the browser SSO login.

## Version
* GitHub Desktop: 1.2.3
* GitHub Enterprise: 2.12.11
* Operating system: Windows 10, Windows Server 2016 (Latest as of June 12th 2018)

## Steps to Reproduce
1. Perform a new installation of GitHub Desktop ( to make sure access token credentials aren't present)
2. Clone a repository from Enterprise GitHub (with SSO) using command line (https clone)
3. Open the GD client and sign in using SSO prompt (Note that there is no way to enter access tokens). The user is logged in and able to list repositories
4. Add the already cloned repository into the client and perform an operation such as fetch, pull, push using the GUI
5. Operation fails with an error: terminal prompts disabled

### Expected Behavior
The action should have been performed.

### Actual Behavior
All actions fail with error: terminal prompts disabled

## Additional Information
1. Mac client works correctly ( Although didn't test a clean install )
2. Git scm works correctly

### Logs
![1](https://user-images.githubusercontent.com/40781000/42195774-a3eda996-7e48-11e8-969c-04046ff969a6.png)
![2](https://user-images.githubusercontent.com/40781000/42195775-a415f022-7e48-11e8-8cfe-b4527e630d58.png)

**Comment by shiftkey** [comment]
@irdw thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by irdw** [comment]
@shiftkey thanks for the response. 

Here are two days of cleared full logs. Let me know if more are needed:

[2017-06-29.desktop.production.log](https://github.com/desktop/desktop/files/2164209/2017-06-29.desktop.production.log)
[2018-07-04.desktop.production.log](https://github.com/desktop/desktop/files/2164210/2018-07-04.desktop.production.log)

**Comment by shiftkey** [comment]
@irdw thanks for the details.

I can see that we're able to complete the sign in flow and store a token for the user:

```
2018-07-04T19:28:44.316Z - info: [main] opening in browser: https://github.<My_Company>.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user&state=28a3a8b6-f730-4000-914e-92c17da3406e
2018-07-04T19:29:09.813Z - info: [main] Received possible protocol arguments: 4
2018-07-04T19:29:09.813Z - info: [main] Processing protocol url
2018-07-04T19:29:09.815Z - info: [ui] [Dispatcher] requesting authenticated user
... 
2018-07-04T19:29:11.781Z - info: [ui] [SignInStore] account resolved
2018-07-04T19:29:11.781Z - info: [ui] [AppStore] adding account <My_Username> (<My_Name>) to store
```

And it looks like we're able to get this token later:

```
2018-07-04T19:30:22.773Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.<My_Company>.com/<My_Organization>/<My_Repository>.git - <My_Username> (has token)
```

Further down, this error around launching out `GIT_ASKPASS` script is the actual problem:

```
2018-07-04T19:30:26.700Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://github.<My_Company>.com/<My_Organization>/<My_Repository>.git C:\projects\GitHubToo\<My_Repository>` exited with an unexpected code: 128.
Cloning into 'C:\projects\GitHubToo\<My_Repository>'...
error: cannot spawn C:\Users<My_User>AppData\Local\GitHubDesktop\app-1.2.3\resources\app\static\ask-pass-trampoline.bat: No error
fatal: could not read Username for 'https://github.<My_Company>.com': terminal prompts disabled
```

That last error suggests we're not passing the right username here when Git prompts for credentials:

https://github.com/desktop/desktop/blob/03873557b5e831fa3c0368fa782e2421e04b6c3d/app/src/ask-pass/ask-pass.ts#L5-L14

A couple of general questions: 

 - we're using the `DESKTOP_USERNAME` environment variable here - does that already exist on your machine? 
 - is this occurring for all network operations, or just when trying to clone down this repository? I can only see this clone action in the list, so maybe it's impacting everything...

**Comment by irdw** [comment]
@shiftkey Thanks for a detailed explanation. 💯 

> we're using the DESKTOP_USERNAME environment variable here - does that already exist on your machine?
I checked the Windows environment variables and on the PS prompt. It doesn't seem to be in use. Is there some other mechanism to check?

>is this occurring for all network operations, or just when trying to clone down this repository? I can only see this clone action in the list, so maybe it's impacting everything...
You are correct, it is happening with everything. For that particular instance, I used clone but it will happen for publish, push, etc. However, logging in and listing enterprise repositories works.

Seems to me that GitHub Enterprise for whatever reason, expects us to do a SSO login at every action or the credentials received on login are not valid for operations.  Note that in earlier versions of GitHub Desktop/Enterprise, it would use username/password and on later version username/access token, both of which could be reused.

**Comment by bailz** [comment]
This was a permissions issue in Windows 10 for me.  Running GitHub Desktop as administrator solved it for me. Understand this is not always possible on corporate builds of Windows 10 locked down by group policy.

I can replicate this 100% of the time when running as non-admin (normal user). Let me know if you need logs.

**Comment by steveward** [comment]
@bailz it would be helpful if you could reproduce this issue and then upload a log file. I've seen a few other causes of this error but the non-admin issue isn't one that I've seen before. Thanks for your help!

**Comment by bailz** [comment]
@steveward Please see logs attached
[2019-04-21.desktop.production.NotWorkingAsWin10User.log](https://github.com/desktop/desktop/files/3100837/2019-04-21.desktop.production.NotWorkingAsWin10User.log)
[2019-04-21.desktop.production.WorkingAsWin10Admin.log](https://github.com/desktop/desktop/files/3100838/2019-04-21.desktop.production.WorkingAsWin10Admin.log)

**Comment by steveward** [comment]
@irdw I was going through some old issues and wanted to follow up to see if you are still encountering this error in GitHub Desktop when using your GitHub Enterprise account. Let us know if it's still a problem.
