### ISSUE TITLE
Option to view the used commands while using the desktop application

### ISSUE THREAD

**Issue by JanderHungrige** [desktop/desktop#5084]
As a new user of Git, I love the simple use of Git-desktop. Nevertheless, whenever I switch using Git commands directly, I still have to look them up constantly (in fear of overwriting my actual files). To increase the learning rate, an option to view the executed commands related to action in Git-desktop could help tremendously. Maybe in a separate window or tab. 

Thanks for considering.
Keep up the great work,
Jan

**Comment by shiftkey** [comment]
@JanderHungrige thanks for the feedback.

We have an existing suggestion about this in https://github.com/desktop/desktop/issues/1570 and there's some additional discussion about it, so please follow along with that issue.
