### ISSUE TITLE
Error message when attempting to clone repository: "failed to open CA file"

### ISSUE THREAD

**Issue by PapaCapricorn** [desktop/desktop#5089]
## Description

Error message when attempting to clone repository: "fatal: unable to access 'https://github.com/shiftstoned/shiftstoned.github.io.git/': schannel: failed to open CA file 'C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt': No such process 

![image](https://user-images.githubusercontent.com/39966530/42240237-aac94a9a-7ed4-11e8-9427-d59bc0cb9436.png)

## Version

* GitHub Desktop: Version 1.2.6

* Operating system: Windows [Version 6.3.9600]

## Steps to Reproduce

1. Open Github Desktop
2. Choose File | Clone repository
3. Select repository from Github.com
4. Receive error message

### Expected Behavior

Ability to clone repository - this was working as expected previously

### Actual Behavior

Receive error message seen above, unable to clone repository. I received a similar message when attempting to push files.

**Comment by shiftkey** [comment]
@PapaCapricorn thanks for the report. I believe your issues is the same as https://github.com/desktop/desktop/issues/4832, because of an entry that looks like this:

```
file:"C:\ProgramData/Git/config" http.sslcainfo=/bin/curl-ca-bundle.crt
```

This entry is no longer valid (Git installations should not be adding this entry to this file) and removing this entry

```
[http]
  sslCAinfo = /bin/curl-ca-bundle.crt
```

from `C:\ProgramData\Git\config` should address the issue for Desktop.

**Comment by PapaCapricorn** [comment]
@shiftkey Thanks for the swift response. I did try what you suggested, but I am still receiving the error message. Screenshot below shows contents of C:\ProgramData\Git\config...please advise.

![image](https://user-images.githubusercontent.com/39966530/42241495-c66af8c6-7ed8-11e8-8584-27e7fe5bb00d.png)

**Comment by shiftkey** [comment]
@PapaCapricorn could you open a shell and run this command? 

```
git config -l --show-origin
```

That should show where the source of that config entry can be found.

**Comment by PapaCapricorn** [comment]
Sure...
![image](https://user-images.githubusercontent.com/39966530/42241769-b230f7ba-7ed9-11e8-9338-41b7cbcab696.png)

**Comment by shiftkey** [comment]
Well that's interesting: Git is saying the config entry is still there - did you save the changes to that file?

![](https://user-images.githubusercontent.com/359239/42242025-f588dcb8-7ee2-11e8-89af-8a8e069e874e.png)

**Comment by PapaCapricorn** [comment]
Ah, looks like there was a write permission issue with the user profile I was using - it is resolved now. 

Thanks for your help!

**Comment by levanlong240895** [comment]
I see a error when i try clone "Cloning into 'master'...
fatal: unable to access 'https://git.rikkei.org/d5/18187d5_xtheta/tree/master/': error setting certificate verify locations:
  CAfile: C:/Program Files/Git/mingw64/libexec/ssl/certs/ca-bundle.crt
  CApath: none
"
