### ISSUE TITLE
GitHub GUI App: When file exceeds 100MB, say which file is the problem so we can delete it.

### ISSUE THREAD

**Issue by yepthatsjason** [desktop/desktop#5097]
**Is your feature request related to a problem? Please describe.**
The GitHub GUI app throws up an error message when a file exceeds 100MB in size. Please tell us exactly which file is the problem so we don't have to hunt for it.

**Describe the solution you'd like**
Please list the exact files that exceed 100MB.

**Comment by j-f1** [comment]
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #5079. Please follow that issue for further updates.

**Comment by shiftkey** [comment]
Even better, let's talk about this in https://github.com/desktop/desktop/issues/997 because it'd be nice to warn you _before_ committing.
