### ISSUE TITLE
Cannot correctly highlight wrapped lines in diff viewer

### ISSUE THREAD

**Issue by csuhta** [desktop/desktop#5099]
## Description
When highlighting wrapped lines in the diff views, the highlighting grabs strange block-shaped areas of the text, and does not copy what you have highlighted to the pasteboard if you copy that text.

## Version
* GitHub Desktop: 1.2.6
* Operating system: macOS 10.13.5

## Steps to Reproduce
1. Change a file with a long line
2. Look at the diff in GitHub Desktop
3. Try to highlight or copy a wrapped line. 

### Expected Behavior
You can start any any point in the wrapped line and highlight it as a single line, like in Safari and other apps that show wrapped text.

Expected behavior from other apps: https://s.csuhta.com/2nTMPY10Hf.mp4

### Actual Behavior
the highlighting grabs strange block-shaped areas of the text, and does not copy what you have highlighted to the pasteboard if you copy that text.

See video here for block behavior: https://s.csuhta.com/XSo3UNcEyY.mp4

**Comment by niik** [comment]
Hey @csuhta, thanks for the detailed report and thank you especially for taking the time to provide video. We're tracking this issue over in https://github.com/desktop/desktop/issues/1551 so please subscribe to that issue to follow along.
