### ISSUE TITLE
No context menu available for highlighted text in diff view

### ISSUE THREAD

**Issue by csuhta** [desktop/desktop#5100]
## Description
When highlighting lines in the diff views, there is no context-click menu available to work with the selected text, even though you can actually highlight text and Command+C with your keyboard to copy it.

## Version
* GitHub Desktop: 1.2.6
* Operating system: macOS 10.13.5

## Steps to Reproduce
1. Change a file in your project
2. Look at the diff in GitHub Desktop
3. Highlight some text
4. Context-click on that text

### Expected Behavior
A context menu opens, with options for at least "Copy"

### Actual Behavior
Nothing happens

**Comment by shiftkey** [comment]
@csuhta thanks for the suggestion - I thought we might have already been tracking this but I guess not.

I took a quick look at what it would take to do _something_ here, and here's a patch that shows a context menu when codemirror sends an event:

```diff
diff --git a/app/src/ui/diff/code-mirror-host.tsx b/app/src/ui/diff/code-mirror-host.tsx
index 05a2574cf..fce73a592 100644
--- a/app/src/ui/diff/code-mirror-host.tsx
+++ b/app/src/ui/diff/code-mirror-host.tsx
@@ -6,6 +6,7 @@ import 'codemirror/addon/selection/mark-selection'
 
 // Autocompletion plugin
 import 'codemirror/addon/hint/show-hint'
+import { showContextualMenu } from '../main-process-proxy'
 
 if (__DARWIN__) {
   // This has to be required to support the `simple` scrollbar style.
@@ -74,9 +75,34 @@ export class CodeMirrorHost extends React.Component<ICodeMirrorHostProps, {}> {
     // See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18824.
     this.codeMirror.on('copy', this.onCopy as any)
 
+    this.codeMirror.on('contextmenu', this.onContextMenu)
+
     this.codeMirror.setValue(this.props.value)
   }
 
+  private onContextMenu = (instance: CodeMirror.Editor, event: Event) => {
+    // TODO: how to detect that text is selected in the editor?
+    const isTextSelected = false
+
+    const action = () => {
+      if (this.props.onCopy != null) {
+        this.props.onCopy(instance, event)
+      } else {
+        log.warn('[CodeMirrorHost] attempting to copy when no prop defined')
+      }
+    }
+
+    const items = [
+      {
+        label: 'Copy',
+        action,
+        enabled: this.props.onCopy && isTextSelected,
+      },
+    ]
+
+    showContextualMenu(items)
+  }
+
   private onCopy = (instance: CodeMirror.Editor, event: Event) => {
     if (this.props.onCopy) {
       this.props.onCopy(instance, event)
```

The last part of this would be to detect when text has been selected, and enable the menu item. I think we can adapt this example from when we're doing the actual copying and confirm there are selections:

https://github.com/desktop/desktop/blob/4a5f2cc8246627f7ea9f2bce467cad216931bcdc/app/src/ui/diff/text-diff.tsx#L548-L550

I'm going to leave this open as a chance for someone to contribute this.

**Comment by MagicMarvMan** [comment]
Hello, I would like to work on this, if this issue is still available. Thank you!

**Comment by shiftkey** [comment]
@MagicMarvMan go for it!
