### ISSUE TITLE
Set Up In Desktop button won't send me to Github Desktop app

### ISSUE THREAD

**Issue by chayabelle** [desktop/desktop#5102]
## Description
1. On github.com, when I click Quick Setups's "Set Up in Desktop" it repeatedly sends me to desktop.github.com. I need it to send it to send me to the actual GitHub Desktop application which I have downloaded. Anyone know why the Set Up in Desktop wont link out to the application on my computer?
2. Also, when I open Github Desktop, it brings me to a screen that says "current repository" in the top left corner but doesn't tell me how to upload my project! How do I upload my project/folders? 

Thx in advance for your help--Chayabelle

## Version

* GitHub Desktop: Newest version (downloaded today).
* Operating system: macOS high sierra 10.13.4

### Expected Behavior
The Set Up in Desktop button would bring me to my Github Desktop application on my computer.

### Actual Behavior
Just brings me to desktop.github.com (even though I already have the app downloaded!)

## Additional Information
How do I open my project/folders from here?
![screen shot 2018-07-05 at 1 49 58 pm](https://user-images.githubusercontent.com/40867931/42339219-600d69a0-805a-11e8-9b85-403277141b41.png)

**Comment by shiftkey** [comment]
@chayabelle have you signed into GitHub Desktop yet? When you sign in from Desktop we're able to set a flag for the user that they have Desktop installed, and so we can probably launch them rather than prompt you to install.

**Comment by chayabelle** [comment]
Hi Brendan, thanks for getting back to me. Yes, I believe I'm signed in. I re-installed Desktop and it didn't ask me to sign in and it automatically said my username "chayabelle" under Current Repsository in the top lefthand corner. And yes, I want it to launch, not prompt to install.

**Comment by chayabelle** [comment]
Sign in & out instead of just uninstalling seemed to work! Thanks, guys! @j-f1

**Comment by LindsayFowler** [comment]
Whenever I have tried to use github in classes I teach, this issue was a problem for around 30% of the kids in the class. 
This may help:
Github.com always directs you to the app download page if you are not signed in in the web page. 
1) Ensure that you are signed in to github.com on the web browser window you are cloning from.
2) Sign in in the GitHub Desktop App as well.
