### ISSUE TITLE
Closing windows should minimize it to the system tray (Windows 10)

### ISSUE THREAD

**Issue by Mored1984** [desktop/desktop#5105]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

**Describe alternatives you've considered**

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this. This will help the core team understand how the feature would work, and assist with future work like documentation.
Screenshots or mockups here are a great help!

**Comment by shiftkey** [comment]
@Mored1984 thanks for the suggestion! 

We talked a bit about this in #4098 and we're not clear on the use case for this - the system tray should be used for notifications and features without desktop presence, and we don't really do any of this in the current version of Desktop.

Are you able to elaborate on the benefits of supporting this?

**Comment by shiftkey** [comment]
Closing this out as inactive. @Mored1984 if you're able to answer the question in the previous comment we can revisit this.

**Comment by allan-navarro** [comment]
what happens if I'm pushing a commit? If I close the program it stops the upload, maybe this could be a use case?
