### ISSUE TITLE
Repositories with identical names should be disambiguated

### ISSUE THREAD

**Issue by varkor** [desktop/desktop#5106]
I often have multiple local copies of a repository for development, but they're displayed identically in the repository list in the Desktop app. Only by hovering over them am I able to see the folder they're in, which is the best way to disambiguate them.

It'd be helpful if some of the local path was also displayed (possibly solely for ambiguous repositories) in the list, so that it is possible to tell which is which more easily. Possibly as right-aligned text next to the repository names?

**Comment by shiftkey** [comment]
@varkor thanks for the feedback!

We have a couple of open issues that overlap with this:

 - #1598 - custom folders for repositories
 - #1929 - support changing description to distinguish between local clones of the same repository

Please follow along with those discussions.

**Comment by omzy83** [comment]
@shiftkey those issues are no longer open. What exactly is happening with this?

**Comment by shiftkey** [comment]
>  those issues are no longer open. What exactly is happening with this?

Apologies, I use the term "open" here to indicate it's marked with a `future-proposal` label to label it as under consideration. We close these issues out in the literal sense to try and keep our backlog under control.
