### ISSUE TITLE
UI: Arrow is too close to text.

### ISSUE THREAD

**Issue by agisilaos** [desktop/desktop#5114]
## Description
Let's say that we change the path of a file inside a repo. When such thing happens, the arrow that indicates that we changed the path is super close to the labels.

## Version
* GitHub Desktop: version 1.2.7-beta0
* Operating system: macOS, High Sierra - version 10.13.5

## Steps to Reproduce
- Change the path of a file inside a repo
- Pay attention to this part of the app:

![screen shot 2018-07-04 at 15 20 51](https://user-images.githubusercontent.com/10944108/42410911-aa4a1c56-81fa-11e8-9c40-6129af2d5ea7.png)

### Expected Behavior
- The arrow shouldn't be that close to both of the labels. One indicating the previous path and one indicating the new path.

### Actual Behavior
- The arrow is too close to both labels.

**Comment by RobertJGabriel** [comment]
Going to give this a try now :)

**Comment by RobertJGabriel** [comment]
Have this sorted now. Sorry for the delay. Going to push in an hour or two :D

**Comment by iAmWillShepherd** [comment]
@RobertJGabriel,

Can you make sure to cc @desktop/core abd @desktop/comrades on your PR?

**Comment by RobertJGabriel** [comment]
@iAmWillShepherd I will of course.

**Comment by j-f1** [comment]
@iAmWillShepherd That won’t work quite right unfortunately — [you have to be an org member to mention a team](https://help.github.com/articles/about-teams/#team-visibility) and you have to be an org owner or @desktop/core member to mention it since it’s secret.

**Comment by iAmWillShepherd** [comment]
😞 I see. Perhaps he can mention one of us since we're already a part of this issue.

**Comment by billygriffin** [comment]
@RobertJGabriel Did you happen to take a shot at this? 😄 Just want to make sure we make clear that it's available if you're not planning to continue to work on it. Thanks!

**Comment by koralcem** [comment]
Is this issue still applicable? It looks like https://github.com/desktop/desktop/commit/cf1e7f0cec90cf0a567554e966421a480e3bdc50 accounted for some padding on either side of the arrow in the case of a renamed or copied file. And trying it out locally, even when I do my best to squish the file paths, I just get the file paths truncated but the arrow still looks decently padded:
<img width="315" alt="arrow" src="https://user-images.githubusercontent.com/3772093/50503127-4df6f080-0a19-11e9-99da-c23bcae0d591.png">

**Comment by j-f1** [comment]
@koralcem the issue was with the header above the diff. Does that have the proper padding now?

**Comment by koralcem** [comment]
Good call @j-f1; the header above the file diff does _not_ have the proper padding:
<img width="449" alt="nopad" src="https://user-images.githubusercontent.com/3772093/50522166-60efdc00-0a7e-11e9-9128-1631ce744800.png">

I will try my hand at this.

**Comment by j-f1** [comment]
👍 on giving both arrows a fixed margin.
