### ISSUE TITLE
Support remote repos

### ISSUE THREAD

**Issue by northamerican** [desktop/desktop#5115]
I have a repo with `origin` remote and `production` remote. When pushing, my new commits are synced with `origin` but there is no clear way, if any, to push my master branch to my `production` remote. 
In the terminal my command is pretty basic. `git push production master`. I am prompted for a password and that's it. 

Currently, desktop treats `production/master` as just another branch and presents the error "A branch with that name already exists." when switching to it. 

I'd like help with how to do this without the terminal or the added ability to push to other remote branches. thanks

**Comment by steveward** [comment]
Thanks for opening this @northamerican. Currently GitHub Desktop does not support multiple remotes unless you are working with a fork that has an `upstream` remote. 

Supporting multiple remotes is not currently on our [roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md), but you can follow along in #1442 for updates. I am going to close this out and add the `future-proposal` label.

**Comment by billygriffin** [comment]
Really appreciate this request @northamerican. I'm removing the `future-proposal` label on this one as we're trying to minimize duplicates on those as we revisit our priorities going forward. Feel free to follow along in the issue @steveward mentioned above.
