### ISSUE TITLE
Remove summary

### ISSUE THREAD

**Issue by n13** [desktop/desktop#5121]
**Is your feature request related to a problem? Please describe.**

I don't understand why there's a "summary" as well as a detail field.

I just want to commit to git.

With a message. 

I always end up writing something in the "description" field, then try to commit, and it doesn't work because I need to provide a summary.

I don't know what the summary is supposed to be for - that's not how git works, and it's not how I use git. 

**Describe the solution you'd like**

Remove the "summary" field altogether

Alternatively, remove the requirement to have a summary before hitting "commit" - allow me to commit with no summary, and just use the description as the git commit message. 

Alternatively have a setting for this

**Describe alternatives you've considered**

See above

**Teachability, Documentation, Adoption, Migration Strategy**

I know it's supposed to enforce good practices, but in my case, it's mostly just in the way. Please remove this requirement.

**Comment by j-f1** [comment]
The “summary” field is where you’re supposed to write the first line of your commit message. The app will insert a blank line in the commit message between what you write in the summary field and what you write in the description field.

**Comment by j-f1** [comment]
If you commit from the command line, the first `-m` you pass goes in the summary field. Can you give an example of a commit message without a summary?

**Comment by n13** [comment]
That is incorrect (I had to look it up though ;) ). 

Git commit -m uses the given message as commit message. See below from the official documentation.

Git does not know anything about a "summary" - it only has a commit message. Although - and I did not know this - multiple -m messages are concatenated in paragraphs.

Pretty much every single one of my commits doesn't have a summary. I just describe what I changed, without summarizing this change, and commit it. 

Recent example: "remove debug printout"

I don't know what I should summarize there? I like to make small incremental changes, so everything gets committed. 

All I am asking is that Github desktop allows me to just commit things with a message. I know I could put my commit message in that tiny summary field and it would work. But this field is called summary, which is weird, and it's very small, so it looks like it should be a title. 

I realize this enhancement request is merely a user interface / usability issue. But I find it strange that it would behave different from command line git, and it's strange I am asked to provide a summary when there is none.

Like I said a very easy fix for this would be to just allow me to commit without summary filled in?! At least make that an option?

https://git-scm.com/docs/git-commit

```
-m <msg>
--message=<msg>
Use the given <msg> as the commit message. If multiple -m options are given, their values are concatenated as separate paragraphs.

The -m option is mutually exclusive with -c, -C, and -F.
```

**Comment by j-f1** [comment]
For your example commit message, all you have to do is type “remove debug printout” in the summary field and commit. The description field is not required.

**Comment by shiftkey** [comment]
@n13 thanks for the suggestion.

This form is intended to mimic this part of committing with Git, which is why we've made the summary mandatory and the description optional (from the Git SCM docs):

> The text up to the first blank line in a commit message is treated as the commit title, and that title is used throughout Git.

I'm curious about your workflow and why you skip the summary and just use the description - can you share an example of the type of commit you're making and the sort of friction that's occurring because of the current form layout?

**Comment by n13** [comment]
It's because the word summary implies I need to provide a summary of what I am doing, pretty simple.

All I did is "remove debug printouts" - clearly that does not need a summary.

In the english language, having a summary implies there is something to be summarized. 

So if I just put "remove debug printouts" in the summary, I feel like I am asked to give a more complete description of this summary in the field below. 

Note that in the git specifications, a summary is **not** mandatory. 

Clearly we can do whatever we want in the desktop implementation - all I am saying is that the current setup does not work for 95% of my checkins. The previous version of GHD simply had a field for the commit comment, and that was good. 

To ask an alternative question: Why is the summary mandatory? What is the new, more strict system, improving?

**Comment by shiftkey** [comment]
@n13 thanks for the extra context

> So if I just put "remove debug printouts" in the summary, I feel like I am asked to give a more complete description of this summary in the field below.
> ...
> To ask an alternative question: Why is the summary mandatory? What is the new, more strict system, improving?

We've made the summary mandatory and description optional here so we have _something_ to pass to Git. If you've specified both fields, we'll stitch this together in the format that Git wants (summary as the first line, description below). If you only specify a summary, that becomes the commit title when committed.

>  The previous version of GHD simply had a field for the commit comment, and that was good.

Both of the classic macOS and Windows apps had this setup (note the use of summary and description in the labels):

<img width="1035" src="https://user-images.githubusercontent.com/359239/42450777-a9877158-835b-11e8-943c-e34cea08f935.png">
<img width="1240" src="https://user-images.githubusercontent.com/359239/42450778-a99d51f8-835b-11e8-915a-13373bc61f9a.png">

I think you might be stumbling upon the classic macOS behaviour here. This is the error message you get when nothing is filled out, and it's a hint that you can fill out either field.

<img width="501" src="https://user-images.githubusercontent.com/359239/42451236-febc5ebc-835c-11e8-9476-17c04d120bb6.png">

We didn't follow this pattern with the Windows app, and I think when we revisited this area we wanted to be consistent.

**Comment by shiftkey** [comment]
@n13 I'm going to close this out because this is a layout we've had in the Desktop apps for a while, but let me know if you have any further questions about how this area works under the hood.

**Comment by amazedevil** [comment]
This issue (summary/description split optionality) is still relevant for me, cause it kinda breaks my workflow: I used to write commit message in mulitple lines, without breaks, and with GD, I just can't do that - summary doesn't allow muliple lines, and description isn't allowed to be on it's own, so I just can't use git as I used to with GD, that's sad

**Comment by n13** [comment]
It’s still stupid. I’ve gotten used to it now by mostly just only writing a summary. I still dislike it. 

The problem with this feature is that it is not matching the functionality of git.

It’s a poor mapping to the actual git features. 

It’s just somebody’s idea on how to make it fit their workflow but it impedes others workflow. It’s a poor UX. Only thing we can do is use other git clients. 

That’s it.

**Comment by Graywoolfie** [comment]
Summary should be optional as it is with default git.  Wished Github Desktop can at least make this configurable.

**Comment by MrFunEGUY** [comment]
Still relevant. Having to put a summary for every commit is pointless when I'm just changing small things. I truly don't care about what is "proper," as this is for my personal use. I just wind up putting a random letter or dash when I do a small commit that doesn't need a summary.

Why, then, should Github require me to put in a pointless character? The fact that this is a required field is, honestly, infantilizing. I'm an adult, I think I can decide for myself whether or not a summary of my commit is required.

**Comment by philip-nicholls** [comment]
I completely agree with @n13.  Just installed GitHub Desktop, and I can't set my commit message properly.  I am forced to write a summary first on the top line.  This is a non standard and optional convention which somebody has just cooked up out of thin air, possibly for good reasons, however I am not happy about adhering to some non standard convention just because somebody thought it was a good idea.

A git commit message is an optional string, not multiple strings, not 1 optional and 1 mandatory, not anything more than just an optional string.  You can check with Linus if you like.
