### ISSUE TITLE
Operation confirmation button colors

### ISSUE THREAD

**Issue by AlFasGD** [desktop/desktop#5125]
When it comes to deleting, removing, etc. I think it would be best to use red colors for the confirmation button instead of the blue. It's really easy to mix them up without actually reading the text of the buttons, therefore some dangerous actions may be taken recklessly.

**Comment by niik** [comment]
Hi @AlFasGD, thanks for opening this issue. While the thought is interesting I believe that following platform conventions should take precedence here. Both macOS and Windows use a standard style for confirmation actions regardless of their impact or recoverability. Another commonly accepted convention is the use of iconography to indicate "dangerous" or irrevocable actions.

![screen shot 2018-07-09 at 11 36 21](https://user-images.githubusercontent.com/634063/42443104-da1102ec-836c-11e8-8cef-1d91d92e7df7.png)

Using symbols over colors is also more accessible to people with vision deficiencies such as color blindness.

macOS does have one convention that we're not following at the moment that I'd love to see implemented which is to place destructive actions farther apart from the other actions: https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/dialogs/

I could have sworn we had an issue about that but I can't find it right now.

So while I really appreciate you taking the time to open an issue I don't believe that changing the colors of the primary action is the way to go.

cc @desktop/design
