### ISSUE TITLE
git clone failed especially at night times

### ISSUE THREAD

**Issue by srikanth-ip** [desktop/desktop#5127]
git clone failing some times(at night times) 
I set httpPostBuffer to 1048576000
and my network is good
I created my gerrit server in cloud instance(linux)
I unable to solve this issue 

help me in this issue

ThankYou in advance

**Comment by niik** [comment]
Hi @srikanth-ip. This sounds like a network connectivity issue either on your end or somewhere between you and your server. GitHub Desktop itself doesn't do anything magical when it comes to cloning, it merely invokes `git clone --recursive --progress [URL]`. I would suggest you try to clone without using GitHub Desktop and let us know if that works better. If you encounter the same issue with a regular Git clone as I suspect you will the problem will most likely be related to network or server issues.

**Comment by srikanth-ip** [comment]
I am getting this error in jenkins (installed in cloud instance)
this is the screenshot regarding the issue

![git-clone-fail](https://user-images.githubusercontent.com/33771695/42615133-a55321dc-855d-11e8-8d1e-0ce9bd8a1d3e.png)

**Comment by niik** [comment]
Hi @srikanth-ip, seeing as you're getting the same error on a jenkins instance which is using Git through other means than GitHub Desktop I don't believe there's much we (as in GitHub Desktop) can do here. As I said earlier this looks like a problem with the server (in this particular instance the server is explicitly returning an error code).

As this repository deals only with problem related to the GitHub Desktop client I'm going to close this issue. Perhaps you'll have better luck by asking your question on sites such as ServerFault.

**Comment by 4194sunny** [comment]
1
Sent from Yahoo Mail on Android 
 
  On Thu, 12 Jul 2018 at 4:44 pm, Markus Olsson<notifications@github.com> wrote:   

Closed #5127.
