### ISSUE TITLE
Markdown headers in dark theme have poor contrast

### ISSUE THREAD

**Issue by bonimy** [desktop/desktop#5133]
## Issue
I am using the beta dark theme for GitHub desktop (version 1.2.6) and the syntax coloring for headers/titles in markdown files has a poor contrast to the page background.

![screen shot 2018-07-09 at 12 05 30 pm](https://user-images.githubusercontent.com/12055044/42470890-bb2aae4c-8370-11e8-93b3-720760e088ef.png)

Taken on MacOS High Sierra 10.13.5 

## Preferred solution
Increase the brightness of the markdown header color to be easier on the eyes when using dark theme.

## Alternative solutions
* Let users create custom syntax coloring, editable either as a .json file or more ambitiously in the app itself.

**Comment by shiftkey** [comment]
@bonimy thanks for the report. The blue that is coming through is from the default Codemirror CSS, and thankfully we have the ability to style these diffs however we want if we know the right selector to use. I'm going to leave this open as a chance for someone to contribute a fix to it and figure out what colour works here, but here's a patch I used to help as a starting point:

```diff
diff --git a/app/styles/_variables.scss b/app/styles/_variables.scss
index f9e564a68..dab2d056a 100644
--- a/app/styles/_variables.scss
+++ b/app/styles/_variables.scss
@@ -343,6 +343,7 @@ $overlay-background-color: rgba(0, 0, 0, 0.4);
   --syntax-tag-color: #22863a;
   --syntax-attribute-color: #6f42c1;
   --syntax-link-color: #032f62;
+  --syntax-header-color: #032f62;
 
   // Note that this duration *must* match the `UndoCommitAnimationTimeout`
   // specified in `changes/index.tsx`.
diff --git a/app/styles/themes/_dark.scss b/app/styles/themes/_dark.scss
index d95d687e5..589b04878 100644
--- a/app/styles/themes/_dark.scss
+++ b/app/styles/themes/_dark.scss
@@ -265,6 +265,7 @@ body.theme-dark {
   --syntax-tag-color: $green-400;
   --syntax-attribute-color: $purple-300;
   --syntax-link-color: $blue-300;
+  --syntax-header-color: $red-300;
 
   // Colors for form errors
   --error-color: $red;
diff --git a/app/styles/ui/_diff.scss b/app/styles/ui/_diff.scss
index 8b9383b26..21b46d03b 100644
--- a/app/styles/ui/_diff.scss
+++ b/app/styles/ui/_diff.scss
@@ -521,6 +521,9 @@
     text-decoration: underline;
     color: var(--syntax-link-color);
   }
+  .cm-header {
+    color: var(--syntax-header-color);
+  }
 
   // Intra line markings takes precedence over syntax highlighting.
   .cm-diff-delete-inner {
```

**Comment by daedaesplayground1911** [comment]
Im trying to solve as many issues in a short amount of time as i possibly can.
