### ISSUE TITLE
Integrate Discord Rich Presence 

### ISSUE THREAD

**Issue by KennethSweezy** [desktop/desktop#5135]
**Is your feature request related to a problem? Please describe.**
No, just think that it would be nice to have a custom "Playing" message for GitHub Desktop

**Describe the solution you'd like**
Discord Rich Presence could be used to show what repository is open (Only Public), and how many commits haven't been pushed.

**Describe alternatives you've considered**
N/A

**Teachability, Documentation, Adoption, Migration Strategy**
Official Documentation on how to implement this is located [here](https://discordapp.com/developers/docs/rich-presence/how-to).
Example of How It Could Look:
![Concept](https://image.ibb.co/jdEKro/Screenshot_2018_07_10_at_12_35_53_AM.png)
(Excuse Bad Editing)

**Comment by niik** [comment]
Hi @KennethSweezy, thanks for opening this, I really like the sentiment and agree that it would be a cool little integration.

I took a quick glance at the documentation and I'm afraid that implementing something like this is going to fall out of the scope of GitHub Desktop. Had the effort been minuscule and the risk very low I think this is something that could have been a fun extra feature but we're not willing to accept the overhead and risk involved in using the Discord SDK at this point.

Perhaps it would be possible to write a small utility application that could be developed, and run, separately from GitHub Desktop which could communicate with Discord?
