### ISSUE TITLE
Can not delete one part of repo

### ISSUE THREAD

**Issue by cosmos-factory** [desktop/desktop#5139]
>Hi, My repository
>  cosmos-factory/cosmos-factory.github.io
 >consists of several sites.  
![screenshot_2018-07-10 cosmos-factory cosmos-factory github io](https://user-images.githubusercontent.com/17174135/42527283-a0ecd272-8491-11e8-9a8c-3943243bf387.png)
I needed delete last one: testblog/public
But that's impossible because I can't delete only one part but only whole repo. So I deleted it from my local repository. And now I can't do any commite from my desktop Github. I reinstalled Github desktop but problem is same:  
>fatal: unable to access 'https://github.com/cosmos-factory/cosmos-factory.github.io.git/': schannel: failed to open CA file 'C:/Users/Konstantin/AppData/Local/GitHubDesktop/app-1.2.6/resources/app/git/mingw64/bin/curl-ca-bundle.crt': No such file or directory
>Although there is all files on local directory.

     

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

**Describe alternatives you've considered**

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this. This will help the core team understand how the feature would work, and assist with future work like documentation.
Screenshots or mockups here are a great help!

**Comment by shiftkey** [comment]
@cosmos-factory thanks for the report!

This error looks like #4836 and it's related to a global config entry from a previous Git for Windows installation.

From the command line, if you run this command:

```
$ git config -l --show-origin
```

You should see an entry like this:

```
file:"C:\ProgramData/Git/config" http.sslcainfo=/bin/curl-ca-bundle.crt
```

This entry is no longer valid (Git installations should not be adding this entry to this file) and removing these lines

```
[http]
  sslCAinfo = /bin/curl-ca-bundle.crt
```

from `C:\ProgramData\Git\config` should address the issue for Desktop. 

Once you've done that, you should be able to push your changes again.

**Comment by cosmos-factory** [comment]
Thank you Brendan, I did it. But how can I delete my directory?

> testblog/public
