### ISSUE TITLE
counter for total number of commits per repository

### ISSUE THREAD

**Issue by ipkpjersi** [desktop/desktop#5146]
**Is your feature request related to a problem? Please describe.**
I think it would be nice to have a total number of commits per repository. Right now there is no way to keep track of the current number of commits you have made in a repository - either in a GitHub repository, or even a local Git repository.

**Describe the solution you'd like**
I think there should be a way to view the number of commits you have made for each of your repositories. This could be just a simple label with the number of commits. Maybe there could even be two labels, one for local commits and one for remote/GitHub commits if there is a remote repository.

**Teachability, Documentation, Adoption, Migration Strategy**
For example, you could have it beside pull origin as there is some room there: 
![](https://i.imgur.com/2mA225a.png)

Or, maybe you could have it on the current repository itself: 
![](https://i.imgur.com/eVZC2QB.png)

**Comment by shiftkey** [comment]
@ipkpjersi thanks for the suggestion!

 I'm not sure of the overall value of displaying your commit count for each repository in the app (taking screen real estate away from other things), but I'm going to mark this as `user-research` for us to think about a bit more.

**Comment by ipkpjersi** [comment]
I think if it can be done in an unobtrusive way it can be a nice feature to have that hopefully shouldn't be too difficult to implement.

It may not be super useful for GitHub repos since you can see the number of commits online, but for repos without a remote I think it would be quite handy to have.

**Comment by billygriffin** [comment]
@ipkpjersi Thanks for this suggestion. I'm curious what problem you're having where it would be helpful to you to see the number of commits locally? Echoing @shiftkey, this isn't something we've heard from other users and I'm unclear on the value, but if there's a problem it's solving that I'm not thinking about, I'm open to investigating further with other users.

**Comment by ipkpjersi** [comment]
It's not really a problem, it's just something I thought of that could be a nice little quality of life thing that shouldn't take too many developer hours to do yet could be nice as long as it's done in a clean, concise manner.

It's not like "oh my god, we must absolutely have this feature immediately at all costs", it's more of a "why not, might as well, could be cool to see"

I just think it'd be closer to feature parity with the GitHub website, if that makes sense.

**Comment by JosephTLyons** [comment]
No, definitely not crazy for wanting it.  I've wanted this for some time now.

And just for dramatic effect, here's a screenshot with a huge red arrow pointing to where the count exists directly on a Github.com repo, although I'm sure everyone knows this.
![screen shot 2018-07-17 at 9 52 55 pm](https://user-images.githubusercontent.com/19867440/42854883-00754bdc-8a0c-11e8-830e-890892c63997.png)

**Comment by JosephTLyons** [comment]
Using the command `git rev-list --count HEAD` shows the git count in a terminal, so I'm sure this wouldn't be too hard to implement.

**Comment by billygriffin** [comment]
Thanks for the feedback folks, really appreciate your thoughts. After giving this more consideration, it doesn't seem that the absence of the commit numbers negatively impacts people's workflow. If that assumption is incorrect, we're happy to revisit. On GitHub.com, the intent is to provide an contextual overview of the repo as a whole, whereas GitHub Desktop is intended as more of a workflow tool to enable you to get your work done more efficiently and intuitively. Given that there's no obvious problem this is solving in that context, I'm going to close this out.

**Comment by ipkpjersi** [comment]
I know you guys closed this and I am very sad you did, but you could easily put the commits count in the history tab like it is in the changes tab and it wouldn't even interfere with the UI at all or clutter it up. It would still look just as clean. At work we don't use GitHub but we do use local git repostiories, so being able to see the number of commits would improve my workflow by reminding me to commit more frequently because I will subconsciously want to increase the commits number. I can't imagine that this would take too long to implement, I am sure someone could even do a PR so you guys wouldn't even need to allocate any core dev time to this. Can you guys please re-consider this?
 
![repo_history_commits_example](https://user-images.githubusercontent.com/33754783/43619843-b9f06162-969d-11e8-9c06-6399979ccc2c.PNG)

CC: @billygriffin 
CC: @shiftkey 
CC: @JosephTLyons

**Comment by billygriffin** [comment]
@ipkpjersi I really appreciate the added context here on why you’d like to see it. We’re doing our best to ensure our focus is on things that add demonstrable value, and while I appreciate where you’re coming from, we just haven’t heard this as something that is slowing people down or causing problems in any material way. It’s often really helpful to have these issues stick around for posterity so if a similar item comes up from lots of different users, we can revisit our assumption (because it’s possible we’re wrong). We always have to make tradeoffs in building products, and each addition also adds cognitive overhead for users, so we want to make sure the things we are doing have clear and obvious benefit. Reasonable people can disagree on where that line is, so thanks again for your perspective.

**Comment by ipkpjersi** [comment]
I just find it odd for it to be like a straight-up no when because this is open-source, it does not even have to be the core development team. No development or testing time has to be taken away from the core team, it can all be accomplished by the community. This would definitely be nice to have for me and others, and this is something I would really like to see.

I really hope you guys do re-consider this decision.

**Comment by billygriffin** [comment]
@ipkpjersi People could open up PRs for hundreds of different features that they each wanted to see, and that would make for a very bloated and confusing user experience for the rest of Desktop users, even if it wasn't using core team resources. I realize this change feels small and non-obtrusive, but we have to make product decisions based on what we think is best for all of our users. Again, I'm open to being wrong if we continue to hear this type of request, but I'm not convinced it's solving a real problem and therefore at present we're not going to build it. Thanks again for your thoughts.

**Comment by ipkpjersi** [comment]
I guess I'm just not seeing how this could possibly ever make for a very bloated and confusing user experience. You already have an "advanced" tab presumably for advanced users only in the options menu, and you could easily have a toggle there for this - although, this is honestly really so unobtrusive, having a toggle for this in the first place would end up adding more "bloat" than simply having a number display on the history tab. If you were worried about what to display for "too many" commits, you could have it exactly like the changes tab where I believe it shows more than 800 just as 800+. I mean, it's good enough for the history tab so why not have it on the changes tab too? I dunno, that's just how I see it. Plus, I am willing to bet the average developer is less likely to be "confused" by more features, and might even encourage it.

Oh well. I am not going to win this, I know when I've been defeated.

**Comment by JosephTLyons** [comment]
Been working in a massive group coding project where were all using GitHub Desktop.  Not everyone is great at creating very uniquely identifying commit messages (an issue itself) and I think the commit number would be useful here.  When were doing voice chats, instead of saying "hey, look at my commit with text "not unique commit message," we could just say "check out commit number 435.  I realize that this has mostly been shut down and decided upon, but I figured I would voice a reasonably good situation where it would be useful.  I think the lower-right hand corner of every commit message box in the history could have a number for it and it wouldn't take up much space.
<img width="354" alt="screen shot 2019-03-06 at 4 15 50 am" src="https://user-images.githubusercontent.com/19867440/53869731-c56f7000-3fc6-11e9-8d60-cdec6c3b0a03.png">

**Comment by ipkpjersi** [comment]
I'd love to see that, that would be very useful, but sadly it's not going to be happening either. I think instead of commit number it could possibly be the hash of the commit but I'm not expecting to see that feature any time ever, really.

**Comment by billygriffin** [comment]
@JosephTLyons Would you mind opening a fresh issue describing the problem so we can think about it a bit more? The proposed solution is potentially interesting, but it seems like that's more in line with commit searchability and navigation as opposed to this issue, which is about the total number of commits. I'm interested in exploring the problem further and examining whether other people feel this pain as well. I thought we may have an issue somewhere that relates to this idea of quickly finding a particular commit, but I just looked for the past few minutes and wasn't able to find it.

**Comment by JosephTLyons** [comment]
Absolutely.  I'll have it up by tonight.

**Comment by JosephTLyons** [comment]
@billygriffin 

https://github.com/desktop/desktop/issues/7022
