### ISSUE TITLE
Does not delete old versions when upgrading.

### ISSUE THREAD

**Issue by felipedrumond** [desktop/desktop#5147]
I found three versions of Github Desktop at C:\Users\user_name\AppData\Local\GitHubDesktop of the size of 180MB each. I think it shoud delete previous versions when upgrading.

**Comment by shiftkey** [comment]
@felipedrumond the update framework we use is careful to ensure that it doesn't remove the previous version (in case it's still running).

There should be a log file at `%LOCALAPPDATA%\GitHubDesktop\SquirrrelSetup.log` that should have details about what's happening (look for the message `cleanDeadVersions: for version {XYZ}`). Is there anything interesting in there that might explain why it can't remove the oldest version?

You can also look at [the source](https://github.com/Squirrel/Squirrel.Windows/blob/b25c9fa1e4d60f8969137532a95bd53bb5a8de1f/src/Squirrel/UpdateManager.ApplyReleases.cs#L539) for this function to see all the caveats and tricks that Squirrel does to try and tidy up, but sometimes it needs a restart from the OS to fully clean up.

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @felipedrumond if you're able to answer this question I'm happy to investigate further:

> Is there anything interesting in (the log files) that might explain why it can't remove the oldest version?
