### ISSUE TITLE
Devops release failed 

### ISSUE THREAD

**Issue by frederickfdo** [desktop/desktop#5148]
## Description

`C:\Program Files\Git\mingw64\bin\curl.exe failed   with return code: 21`

I got the above error while uploading jar Artificate in one environment, please help on this 

## Version

* GitHub Desktop:

* Operating system:

**Comment by frederickfdo** [comment]
![error](https://user-images.githubusercontent.com/20641018/42617267-bfdd95de-85ce-11e8-8342-9cd139109cdb.PNG)

**Comment by shiftkey** [comment]
@frederickfdo Thanks for reaching out!

It's not clear to me that this is related to GitHub Desktop, but if you believe it is can you fill out the template and provide details for reproducing the issue on our end?

**Comment by shiftkey** [comment]
Closing this out as inactive. I believe this is an issue unrelated to GitHub Desktop.
