### ISSUE TITLE
Open in Visual Studio Code

### ISSUE THREAD

**Issue by artivilla** [desktop/desktop#5156]
## Description
Open the file in `Visual Studio Code` for application when you right click and open the context menu.

## Version
* GitHub Desktop:
1.2.6
* Operating system:
10.12.6

## Steps to Reproduce
1. Click on `History` tab in the desktop client.
2. Select individual file from one of the commits.
3. Right Click and pick `Open in Visual Studio Code`.

### Expected Behavior
Should open VS Code.

### Actual Behavior

Error recieved.
View error. Worked the first time only however opened another session of the client. Following times I got the following error. Other options worked well.

<img width="597" alt="screen shot 2018-07-13 at 10 38 12 am" src="https://user-images.githubusercontent.com/2120159/42697842-3d1bf552-868a-11e8-9d64-88366e27e595.png">

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by artivilla** [comment]
Hi,

Unfortunately, I opened the issue and didn't add all the details. Was filling in the description, and in the meantime, the issue got closed. That was way to quick of a response I wasn't expecting.

**Comment by niik** [comment]
> Unfortunately, I opened the issue and didn't add all the details. Was filling in the description, and in the meantime, the issue got closed. That was way to quick of a response I wasn't expecting.

Hi @artivilla! Sorry about that. We get a bunch of issues opened without any details and no response so we usually close them out fairly quickly but not to fret, we can just as easily reopen them 😄

**Comment by shiftkey** [comment]
@artivilla that's weird - we're using macOS APIs to find where this app is listed, and the fact that it's returning `~/Library/Caches` suggests an update is in flight.

What happens if you run this command from the shell? 

```sh
$ mdfind kMDItemCFBundleIdentifier = "com.microsoft.VSCode"
```

On my machine it looks like this:

```sh
$ mdfind kMDItemCFBundleIdentifier = "com.microsoft.VSCode"

/Applications/Visual Studio Code.app
```

**Comment by artivilla** [comment]
The path is the same. I tried it again and it works now. ¯\_(ツ)_/¯

**Comment by douglasdd** [comment]
For the benefit of future victims, some additional info...

Unrelated to GitHub desktop, I had the same issue on Mac 10.14.6 where `mdfind kMDItemCFBundleIdentifier = "com.microsoft.VSCode"` could not find "Visual Studio Code.app" after I'd dragged it to my `/Applications` folder.

(So at the time I shrugged and hardcoded the path to `/Applications/V*Code.app/Contents/Resources/app/bin/code` in my aliases.)

But a few days later, I found the same `mdfind` command worked and returned the correct path!

My conclusion:
* VSCode probably does some Mac-y "housekeeping" at the time of it's first run to properly register itself(?)
* Other apps using the Electron framework *might* behave similarly(?)

**Comment by xgqfrms** [comment]
# same problem, after update reinstall the vscode editor

> old path

![image](https://user-images.githubusercontent.com/7291672/121454929-3e47a880-c9d6-11eb-96a7-80d2e8ea7314.png)

> new path

![image](https://user-images.githubusercontent.com/7291672/121454829-15bfae80-c9d6-11eb-8596-f846956b82d9.png)


@shiftkey I think this a path match problem, so how can I change the path setting of github desktop?

```sh
$  mdfind kMDItemCFBundleIdentifier = "com.microsoft.VSCode"
/Applications/Visual Studio Code.app

```
