### ISSUE TITLE
New repositories won't appear on Repositories list

### ISSUE THREAD

**Issue by zSucrilhos** [desktop/desktop#5161]
## Description

I have created a new repository on github's site but the desktop version doesn't have updated and it is showing that i have no repositories even tough i created one. I also tried do close and open the app again, it did not helped.

## Version

* GitHub Desktop: Version 1.26

* Operating system: Microsoft Windows 10 [Version 10.0.16299.309]

## Steps to Reproduce

step 1 = Create a new repository on the github website;
step 2 = Do some changes on the new repository, just some random text;
step 3 = Check the github app for your new repository you just created on the site.

### Expected Behavior

I expected to see my new repository listed on the Repository list (CTRL+T) on the desktop version.
### Actual Behavior

It doesn't show my new repository in the Repository list (CTRL+T), instead, it continues to show as if i had no repositories even after i closed and re-opened the desktop app.

## Additional Information

There is no additional info.

If you have screen shots or gifs that demonstrate the issue, please include them.
![image](https://user-images.githubusercontent.com/37763819/42720585-cab26dcc-86ff-11e8-9da0-331d123e69b0.png) = desktop version
![image](https://user-images.githubusercontent.com/37763819/42720591-d813e306-86ff-11e8-82fa-04e2f5ac4b15.png) = site

If the issue involves a specific public repository, including the information about it will make it easier to recreate the issue.

If you are dealing with a performance issue or regression, attaching a Timeline profile of the task will help the developers understand the runtime behavior of the application on your machine.
https://github.com/desktop/desktop/blob/master/docs/contributing/timeline-profile.md
-->

### Logs

[2018-07-14.desktop.production.log](https://github.com/desktop/desktop/files/2194634/2018-07-14.desktop.production.log)

**Comment by j-f1** [comment]
GitHub Desktop doesn’t automatically download your repositories. You need to go to File → Clone repository… to clone your repository to your computer.

**Comment by shiftkey** [comment]
@zSucrilhos yep, what @j-f1 said.

We want it to be easy for you to clone your repositories to your local machine, but we don't want to clone them all down automagically.

**Comment by zSucrilhos** [comment]
Got it, tnx

**Comment by zSucrilhos** [comment]
Oh, got it. Thanks for the support :)

**Comment by ghost** [comment]
[time.txt](https://github.com/user-attachments/files/17305838/time.txt)
