### ISSUE TITLE
Include kitty in the list of terminals to use

### ISSUE THREAD

**Issue by baremetalfreak** [desktop/desktop#5162]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Include [_kitty_](https://github.com/kovidgoyal/kitty) in the list of terminals to choose from under Preferences/Advanced/Shell, when _kitty_ is installed

**Describe alternatives you've considered**
I can use Terminal, Hyper or iTerm2. But kitty is the best terminal emulator I have seen so far. It would be nice if I could set it as my default terminal for Github Desktop.

**Teachability, Documentation, Adoption, Migration Strategy**
Show _kitty_ in the list under Preferences/Advanced/Shell when it is installed. Launch it like any other terminal emulator app when requested.

**Comment by agisilaos** [comment]
Hello, @baremetalfreak thank you for the feedback. We have a [document](https://github.com/desktop/desktop/blob/master/docs/technical/shell-integration.md) that describes how to integrate a new terminal into Github Desktop. If you're interested, feel free to open a PR with that integration. The team would be more than happy to help you with your PR, provide feedback etc. Let me know if you have any questions.

**Comment by MagicMarvMan** [comment]
Hello, if this issue is still available, I would like to take it. I will open a PR as soon as I am done. Thank you!
