### ISSUE TITLE
github desktop auto refresh is disruptive

### ISSUE THREAD

**Issue by underdarkskies** [desktop/desktop#5164]
## Description

when browsing the commit history of a repo in github desktop, the view will refresh automatically at an interval, or when application focus resumes. when this occurs the history list is rolled up to the top, losing your place in the history list. VERY inconvenient for browsing previous commits as the app is basically fighting you to keep your place. ive never scrolled harder in my life. please add an option to disable directory refresh!!!!!

## Version

* GitHub Desktop:

* Operating system:

**Comment by billygriffin** [comment]
Thanks for reaching out! I was unable to reproduce the issue, so we need more information. Would you mind filling out the issue template so we have enough information to dig into this?

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @underdarkskies if you're able to fill out the template and provide more information for us to troubleshoot the issue we're happy to revisit it.

**Comment by deanius** [comment]
This is a non-issue IMHO. Reflecting reality is what the GUI should do. The scroll position - in a list of commits you've caused to no longer exist - simply cannot be maintained if you are no longer browsing those commits. At best - a scroll position per branch could be maintained.

**Comment by underdarkskies** [comment]
I really don’t understand why you are commenting on a closed issue a year plus later. Furthermore you misinterpret completely the original issue making an assumption that I was scrolling through ?!-A list ofcommits I’ve caused to no longer exists-?!

Look the issue was simple. Github desktop on windows 10 while scrolling through the commit history of a repo with a LARGE number of commits(bitcoin) would arbitrarily reset your scroll position back to the most recent commit. I don’t know why billy couldn’t replicate this as it’s pretty straightforward and is still how the app behaves a year later.
