### ISSUE TITLE
unable to login with my credentials

### ISSUE THREAD

**Issue by spkavyashree** [desktop/desktop#5167]
## Version

* GitHub Desktop:

* Operating system:

**Comment by Koklin** [comment]
@

**Comment by Koklin** [comment]
Why do morons like @spkavyashree  add uselss and empty issues? Can we ban this idiots?

**Comment by Koklin** [comment]
kkkkkkkkkk

**Comment by Koklin** [comment]
Morons keep adding empty issues.
@spkavyashree  get lost noob!!!!!!!!!!!!!!!!

**Comment by Koklin** [comment]
Morons keep adding empty issues.
@spkavyashree get lost noob!!!!!!!!!!!!!!!!

**Comment by jhildreth1028** [comment]
I am also having this issue. My login was working fine until last Thursday. I went to pull from Visual Studio Team Services (VSTS) (which I have been doing for months) and Desktop said "Authentication Failure" I checked the password and username and resubmitted but I keep getting the same error. I had another person who uses Desktop try to connect and they are receiving the same error. I tested connecting with sourcetree and that allowed me to connect to VSTS. Let me know if I can provide any additional information that can help resolve this.

**Comment by shiftkey** [comment]
@jhildreth1028 please open a fresh issue and fill out the template as there are a lot of variables at play here. There's also [a guide](https://github.com/desktop/desktop/blob/master/docs/integrations/vsts.md) to help connect Desktop to VSTS - I'm not sure if you've used that initially or something else.

**Comment by shiftkey** [comment]
Closing this out as inactive.

@spkavyashree if you're able to fill out the template to provide more details we can revisit this issue.
