### ISSUE TITLE
Authentication Error When connecting to Visual Studio Team Services

### ISSUE THREAD

**Issue by jhildreth1028** [desktop/desktop#5171]
## Description

When pulling from a repository on VSTS I received an authentication failure. I had been connecting to this repository for a few months without problems. I tried to troubleshoot this by deleting the repository on my windows machine and cloning the repository from scratch. This caused the same issue saying authentication failed.

## Version

* GitHub Desktop: 1.2.6

* Operating system: Microsoft Windows [6.1.7601]

## Steps to Reproduce

1. Launch Desktop
2. Clone Repository
3. enter VSTS url and local path
4. Enter Alternate authentication credentials for VSTS
### Expected Behavior

Connect to VSTS Repository
### Actual Behavior

Authentication Failure

**Comment by shiftkey** [comment]
@jhildreth1028 thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by jhildreth1028** [comment]
This issue resolved it self in the last hour. I don't know what happened. It could have been on the server side.

**Comment by shiftkey** [comment]
@jhildreth1028 I'm glad it resolved itself

**Comment by jhildreth1028** [comment]
Thanks for your help and quick responses. I really like Github Desktop due to the simple UI and ease of use!
