### ISSUE TITLE
Add option to show repo path below name

### ISSUE THREAD

**Issue by sammahoney** [desktop/desktop#5175]
The company I work for uses a specific setup for all their sites, and the repo name is always "theme". This means that under the repo list I just have a bunch of "themes" and need to hover over them to see the local path to determine which is which.

![theme](https://user-images.githubusercontent.com/3868359/42819608-5c4294e8-89d4-11e8-8425-28292ac23974.jpg)

Would be nice if there was an option in preferences to display the path underneath the name in the list without needing to hover (and also under the current repo's name too).

Noticed someone else with a similar issue here, which I presume this would also fix: https://stackoverflow.com/questions/37635517/how-do-i-rename-a-local-only-repository-on-github-desktop-without-renaming-r

**Comment by steveward** [comment]
Thanks for opening this @sammahoney! Would supporting custom labels for the repository list be a solution for this issue? We are tracking feedback for that in https://github.com/desktop/desktop/issues/1929 -- let me know if that seems to align with what you are looking for.

**Comment by sammahoney** [comment]
Yeah, that would actually be my preferred way of dealing with this, just figured it might be easier to simply make the paths visible seeing as they're already there on hover.

**Comment by steveward** [comment]
Thanks for the feedback @sammahoney. I'm going to close this issue out -- you can follow along in #1929 for updates.
