### ISSUE TITLE
scroll position not remembered when switching tabs

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#5177]
## Description

When switching between the changes and history tabs, the scroll position is not remembered, which leads to the lists being reset to the top even if the selected item is remembered.

This relates to #5059 but is a different set of repro steps.

## Version
* GitHub Desktop: `1.1.1` (at least) through to `1.3.0-beta2`
* Operating system: macOS 10.13.6 (probably affects all platforms)

## Steps to Reproduce

1. Create enough changes and history in a repository so that each list can be scrolled
1. Scroll down and select a changed file beyond the first page
1. Switch to the History tab
1. Scroll down and select a commit beyond the first page
1. Switch back to the Changes tab, then switch back to the History tab

### Expected Behavior

Scroll position is remembered, and the selected item remains in focus for both Changes and History

### Actual Behavior

Scroll position resets to zero, but selection is remembered

## Additional Information

Here's a really long GIF of this in action (working against `master`)

![](https://user-images.githubusercontent.com/359239/42843448-860df0f8-89e6-11e8-9bc6-5586e74f49fd.gif)

### Logs

N/A

**Comment by tierninho** [comment]
Can reproduce this. The `enhancement` label was added.

**Comment by Daniel-McCarthy** [comment]
This is a great suggestion that I think should really help with productivity and reduce some potential frustrations in working with GitHub desktop.

I have attempted to add this functionality and have a basic solution I think we can iterate on as needed.
A pull request will be submitted quite soon to address this Issue and Issue #5059.
