### ISSUE TITLE
Unable to resolve host

### ISSUE THREAD

**Issue by AceSyntax** [desktop/desktop#5180]
I'm getting an error when trying to clone a repo of mine.

Unable to resolve host 
'https://github.com/AceSyntax/DemoApp.git/

I'm guessing this is a proxy issue as I can see this in my browser.

I don't see any settings in the allow me to specify a proxy.

Maybe this is a some other issue though?

**Comment by steveward** [comment]
👋 @AceSyntax 

If you are behind a proxy that requires credentials there are some steps you can take to configure it:

1. Go to the file menu and select `Repository` > `Open in Terminal` (macOS) or `Open in <default_command_line_application>` (Windows)
2. Run the following command:

`git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`

Replace `proxyuser` with your proxy username and `proxypwd` with your proxy password. Also, `proxy.server.com:8080` needs to point to the URL of your proxy server.

Let me know if that doesn't get things working for you!

**Comment by bopoh13** [comment]
@steveward, why should I specify proxy settings if I do not have a proxy? Or give the working settings of your proxy so that I can check the connection. 2 months ago everything worked.

#### GitHub Desktop 3.3.6.1:
``` nix
Failed to sync this branch
You might need to open shell and debug the state of this repo.
```
#### Git Bash 2.14.1.windows.1:
```
$ git config --global http.proxy
[empty]

$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean

$ git pull
fatal: unable to access 'https://github.com/bopoh13/docs.git/': Could not resolve host: github.com
```

**Comment by bopoh13** [comment]
Hi All!

I use the **mintty 2.7.7** for MSYS (supplied in the GitHub Desktop). Can I somehow change the port of work from 443 to 80? There is [no proxy](https://superuser.com/questions/346372) on the computer, but a corporate firewall is installed.
#### Git Bash 2.14.1.windows.1:
```
/usr/bin/bash --login -i

$ GIT_CURL_VERBOSE=1 git pull
* Couldn't find host github.com in the _netrc file; using defaults
* Could not resolve host: github.com
* Closing connection 0
fatal: unable to access 'https://github.com/bopoh13/docs.git/': Could not resolve host: github.com
```
#### GitHub Desktop 3.3.6.1:
``` nix
Failed to sync this branch
You might need to open shell and debug the state of this repo.
```

**Comment by iAmWillShepherd** [comment]
@bopoh13 this repository is for the new version of [GitHub Desktop](https://desktop.github.com/). GitHub Desktop (Windows edition) and (Mac edition) have been discontinued and are no longer supported.

**Comment by bopoh13** [comment]
@iAmWillShepherd I konw, but I can't use 64-bit on all PC. The administrator said that he did not block the ports. Perhaps a coincidence, but the connection was restored after the launch [TCPView](https://docs.microsoft.com/en-us/sysinternals/downloads/tcpview).

**Comment by bopoh13** [comment]
@iAmWillShepherd I know, but I can't use 64-bit on all PC. The administrator said that he did not block the ports. Perhaps a coincidence, but the connection was restored after the launch [TCPView](https://docs.microsoft.com/en-us/sysinternals/downloads/tcpview).
