### ISSUE TITLE
Avatar Stopped Displaying After GitKraken Install

### ISSUE THREAD

**Issue by JosephTLyons** [desktop/desktop#5184]
## Description
I'm not entirely sure if its related, but I installed [GitKraken](https://www.gitkraken.com) today out of curiosity and within the same day, my Avatar in GitHub Desktop stopped displaying, even after completely removing GitKraken from my Mac system.

## Version
* GitHub Desktop: 1.2.6
* Operating system: macOS 10.13.6

## Steps to Reproduce
I'm not sure, but it seems like installing GitKraken might be it (although I can't be sure the events are related).

### Expected Behavior
Expect to see my Github avatar for each commit

### Actual Behavior
I'm seeing a default avatar

## Additional Information
![screen shot 2018-07-18 at 6 55 10 am](https://user-images.githubusercontent.com/19867440/42877443-a4379dba-8a57-11e8-8224-a2321b8e5d58.png)

Even the commit section shows a default avatar, like it just can't obtain the one from Github.com:

![screen shot 2018-07-18 at 7 04 43 am](https://user-images.githubusercontent.com/19867440/42877860-0da772ce-8a59-11e8-97f0-1822ba251af9.png)

Note, I tried changing my Avatar on Github.com, to see if it would somehow reset on Desktop, but this did not work.

**Comment by shiftkey** [comment]
@JosephTLyons Did GitKraken change your email address in the `~/.gitconfig`? If it's a new email address on those two commits it might not be associated with your GitHub account.

You should be able to just [add it](https://github.com/settings/emails) to your account and that should be picked up on next launch.

**Comment by JosephTLyons** [comment]
Yep.  The email in my `.gitconfig` was displaying one of my emails that is not on my account on GitHub.com.  Adding the email to the account fixed it and my avatar now shows on all commits.   Thank you very much for your quick help.

**Comment by billygriffin** [comment]
@JosephTLyons Awesome, thanks for the detailed description!
