### ISSUE TITLE
Dragging folders onto dock icon

### ISSUE THREAD

**Issue by adactio** [desktop/desktop#5194]
I have an issue where trying to drag the folder of a repo onto the icon for GitHub Desktop doesn't do anything. In the previous versions of the app, this action would open the repo in that folder.

I'd like to see the behaviour revert to that of the previous versions: dragging a folder on to the icon for Github Desktop opens the app with that repo selected (or if the app is already open, switches to that repo).

For now, I can open the app first and type the name of the folder/repo, but this takes a bit longer than dragging and dropping (especially if I already have Finder open).

I realise this isn't high priority and it's a relatively minor regression from previous versions of the app, but having lived with the new version for a while now, I find myself still missing this little feature.

**Comment by shiftkey** [comment]
@adactio I think we've already captured this in #5048 - can you confirm that it's talking about the same part of macOS?

**Comment by shiftkey** [comment]
@adactio I'm going to close this in favour of #5048, but let me know if I'm missing any context

**Comment by adactio** [comment]
Oh, yes! Apologies for the duplication.
