### ISSUE TITLE
update electron-winstaller to help app clean up after itself

### ISSUE THREAD

**Issue by zero77** [desktop/desktop#5197]
## Description
The Squirrel dependency is out of date by a few versions also, it should automatically update itself alongside Git Desktop.

https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/getting-started/1-integrating.md#basic-squirrelwindows-update-code

## Version
1.2.6 on windows 8

**Comment by shiftkey** [comment]
@zero77 Thanks for the feedback!

This is a dependency managed by [`electron-winstaller`](https://github.com/electron/windows-installer), and the latest published version contains Squirrel.Windows `1.7.9`. We're on `1.5.2` currently.

Is there anything in particular we should be interested in from recent updates to `Squirrel.Windows`? Breaking the updater is the stuff of my eternal nightmares, so I want to ensure upgrading `electron-winstaller` gets a thorough set of testing before it goes out to everyone.

**Comment by shiftkey** [comment]
Just updated the title on this to indicate the actionable work, but I'd still love to hear from @zero77 about Squirrel-specific improvements that might help out Desktop.

**Comment by zero77** [comment]
Sorry for the very late reply, there’s been a few changes from 1.5.2 to 1.7.9. so, from memory I can only suggest one change currently.

The newer version cleans logs and cleans up after old versions that are left behind in AppData\Local\GitHubDesktop, because, this can quickly become filled up will unnecessary leftover files that take up disk space over time.

I can also look over the change log to find some of the major changes.

**Comment by shiftkey** [comment]
#6486 is an interesting error about the upgraded app being in an invalid state on-disk that might be related to some `Squirrel.Windows` work that we should look at while upgrading this dependency.

**Comment by shiftkey** [comment]
#7084 is an interesting problem about the start menu shortcut going missing between updates. We should investigate after the upgrade whether this can still be reproduced.

**Comment by steveward** [comment]
#8204 was another request for updating Squirrel to help reduce leftover files after updates occur.
