### ISSUE TITLE
Please make it possible to select/deselect ranges of checkboxes as a single operation

### ISSUE THREAD

**Issue by axefrog** [desktop/desktop#5210]
Very simple request: If I click a checkbox, then shift+click another checkbox, I'd like all the checkboxes in-between to also become checked (or unchecked). When you have changes across 50+ files, having to manually check or uncheck large groups of them is extremely tedious.

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

I've included this GIF to stand in for reproduction steps. 
![2018-07-23 15 07 14](https://user-images.githubusercontent.com/1715082/43100197-354aa41a-8e8a-11e8-9c05-0ba6551ba756.gif)

**Comment by axefrog** [comment]
Yeah  select/deselect all is better than nothing, but being able to check/uncheck partial ranges is what is really needed, because there are often groups of changes to include in a commit, and groups to exclude at the same time.

**Comment by tierninho** [comment]
For any open-source contributor looking to help, here is a good place to start:

https://github.com/desktop/desktop/blob/master/app/src/ui/lib/checkbox.tsx
https://github.com/desktop/desktop/blob/master/app/styles/ui/_checkbox.scss
https://github.com/desktop/desktop/blob/master/app/styles/ui/_file-list.scss
https://github.com/desktop/desktop/blob/master/app/styles/ui/changes/_changes-list.scss

Reach out to the team if you need guidance. Thank you!

**Comment by binaryfunt** [comment]
A feature heavily related to this would be pressing alt + clicking on a checkbox resulting in unchecking all other checkboxes. While not exactly standard behaviour for checkboxes across apps, it is implemented in Photoshop for viewing/hiding layers.

**Comment by shacharoz** [comment]
this is one of the critical features github desktop is missing.
please please fix this!

**Comment by shacharoz** [comment]
Hi Shachar,

Thanks for writing in. You can use **shift and ctrl to select multiple files** in the changes list and then click **Enter to select the highlighted files**. 

There was some discussion around improving this here:
https://github.com/desktop/desktop/issues/7790

Best,
Steve

**Comment by billygriffin** [comment]
I'm going to close this issue because I think the same concept it captured in #7790 and we further fleshed out the user problem there. I don't think this is something we're likely to work on very soon, especially since there's a way to achieve this goal (albeit not super discoverable), but didn't want you to think it's lost.

**Comment by shacharoz** [comment]
Thanks. It is actually solved already.
There is no documentation for it as well as no instructions, but it can be
done by clicking Enter key after selecting few items. . this toggles that
group.

**Comment by shagunMathur** [comment]
There should be a search dialog box too so that user can search a particular file to check/uncheck from a number of files. This will help to a great extent.
