### ISSUE TITLE
Black Screen when GitHub desktop is opened 

### ISSUE THREAD

**Issue by SHADOWELITE7** [desktop/desktop#5212]
## Description
When I opened Github desktop, it showed this, I am currently using dark theme
![image](https://user-images.githubusercontent.com/33847580/43035711-9545fb04-8cc2-11e8-9823-cfb56c125318.png)

## Version

* GitHub Desktop: 1.2.6
* Operating system: Microsoft Windows [Version 6.1.7601]

### Expected Behavior
clicks Github Desktop, pulls up, shows the menue
### Actual Behavior
clicks Github Desktop, pulls up, shows black screen

**Comment by SHADOWELITE7** [comment]
Hi @shiftkey ,

I am on a desktop. My graphics card is an Nvidia Geforce 9500gt, I am using the GeForce experience to update the driver, its current version: ``21.21.13.4201``. I will also look into the Do page.

**Comment by SHADOWELITE7** [comment]
It's working right now, I guess I had to restart my Desktop

**Comment by alexandrubetea** [comment]
Hello,
i still have this problem and i don't know how to fix it, any ideas?
Thanks

**Comment by tierninho** [comment]
@alexandrubetea Please see our help doc with the solution here: https://github.com/desktop/desktop/blob/development/docs/known-issues.md#i-get-a-black-screen-when-launching-desktop

**Comment by sreekanth-karini** [comment]
https://www.youtube.com/watch?v=2835_ZJGCQA

The above solution in the video worked for me.

**Comment by sreekanth-karini** [comment]
@alexandrubetea 
try this just add **--disbale-gpu**  in properties
goto github properties(right click on it)>target path>paste this **--disbale-gpu** at last>click apply>ok>relaunch app
below example for visual studio app
https://www.youtube.com/watch?v=2835_ZJGCQA

**Comment by shurvir49** [comment]
Thanks... this works for me

**Comment by AirChandler** [comment]
> > [@alexandrubetea](https://github.com/alexandrubetea)
> > try this just add **--disbale-gpu** in properties
> > goto github properties(right click on it)>target path>paste this **--disbale-gpu** at last>click apply>ok>relaunch app
> > below example for visual studio app
> > https://www.youtube.com/watch?v=2835_ZJGCQA
> 
> This works, but , there is spelling mistake in yours... please edit with **--disable-gpu** But Thanks... this works for me

I'm having this issue with the unofficial linux port with WSL, can confirm this worked for me as well.
