### ISSUE TITLE
Big image preview overlaps the nav bar

### ISSUE THREAD

**Issue by klenium** [desktop/desktop#5215]
## Description
I added an image to my repository, it's size was 2600x3100 pixels. I previewed it before commiting changes. The 2-up view were selected. The image hided some of the navbar's components, like a layer whichs z-index is incorrect.

## Version
* GitHub Desktop: 1.2.6
* Operating system: Windows [Version 10.0.17134.165]

## Steps to Reproduce
1. Add a tall image to a reposity.
2. Before commiting, in the changes tab, select that image, and see the preview.

### Expected Behavior
[Scrollbars](https://github.com/desktop/desktop/issues/4925), or resized image to fit the available space, maybe zooming. Tabs to see old and new images.

### Actual Behavior
(The cursor is over the Fetch origin button)
![a](https://user-images.githubusercontent.com/4959489/43044820-dd9b8914-8dad-11e8-9a2c-4a32ab82544b.PNG)

**Comment by shiftkey** [comment]
@klenium thanks for the report. This feels like it's the same issue as #2480, so I'm going to add a comment there and close this out to avoid confusion. Please follow along with #2480!

**Comment by klenium** [comment]
Yeah, it is. Sorry, I didn't find it by searching for keywords. :(
