### ISSUE TITLE
unable to push More than 100MB data

### ISSUE THREAD

**Issue by dasumenaria** [desktop/desktop#5217]
## Version

* GitHub Desktop:

* Operating system:

**Comment by dasumenaria** [comment]
![image](https://user-images.githubusercontent.com/13076429/43058695-86eb115c-8e66-11e8-9c97-717c2c32086b.png)

**Comment by shiftkey** [comment]
@dasumenaria unfortunately this is a restriction enforced by the GitHub server.

If the commits are still unpublished, you should be able to undo them (using the button below the commit form) to bring back that file which exceeds this limit into your working directory. If you avoid committing it again, you should be able to push the other changes fine.

If you still want to have this large file in version control, Desktop supports Git LFS - [here's how to configure it for your repository](https://git-lfs.github.com/). Once your repository is Git LFS-enabled, Desktop will use that when pushing in the future.

Please also follow along with #997 which is our exploration of warning the user before committing a file that will trigger this warning.

**Comment by dasumenaria** [comment]
Thanks sir
