### ISSUE TITLE
Fetch & pull does not update submodules.

### ISSUE THREAD

**Issue by martinrode** [desktop/desktop#5220]
## Description

My top level repo includes an updated submodule. If I use "fetch & pull" the submodule gets not updated to the new reference. Github Desktop reports a changed file (with the old reference from the submodule), which is unusable for people not really familiar with git commands.

## Version

* GitHub Desktop:  1.2.6.

* Operating system: Windows 10

## Steps to Reproduce

1. Use a repo with a submodule
1. Update the submodule somewhere else, link the new reference into your repo
1. Use Github Desktop to Fetch & Pull

### Expected Behavior

The submodule should get pulled and updated.

### Actual Behavior

GitHub Desktop reports a file change (with the old submodule reference).

**Comment by shiftkey** [comment]
@martinrode thanks for the report.

We're already tracking this in #4579 and we've got #5154 open to address it - please follow along with those discussions!
