### ISSUE TITLE
Windows Firewall Outgoing Rules ignored

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#5223]
## Description
If you set Windows Firewall to deny outgoing connections unless a rule specifies, despite setting a rule to allow the Github Desktop executable(s) (including all app executables and squirrel executables), github desktop will still fail to establish any outgoing connections. 

## Version
* GitHub Desktop: 1.2.6
* Operating system: Windows 10

## Steps to Reproduce
1. Open Windows Defender Firewall
2. Open Windows Defender Firewall advanced options (this shows the rule window)
3. Open Windows Defender Firewall Properties (in the overview section)
4. Go to the profile tab that is associated with your network connection, and set Outbound Connections to Block.
5. Go to outbound connections and create a new rule, allowing connections for squirrel.exe, GithubDesktop.exe, and the squirrel.exe and GithubDesktop.exe within the app folder with the latest version, e.g. %USERPROFILE%\AppData\Local\GitHubDesktop\GitHubDesktop.exe
6. Open Github Desktop

### Expected Behavior
Github Desktop should be able to connect, since the executable is allowed through the firewall.

### Actual Behavior
Github Desktop fails to connect.

## Additional Information
The same type of problem exists when you try to block Github Desktop with a rule, the rule will be ignored.

### Logs
[2018-07-23.desktop.production.log](https://github.com/desktop/desktop/files/2220960/2018-07-23.desktop.production.log)

**Comment by iAmWillShepherd** [comment]
@PaperSlips could you verify that you also have a rule for `git.exe`?

**Comment by PaperSlips** [comment]
Yes, I have every executable within the %USERPROFILE%\AppData\Local\GitHubDesktop\ folder added and the problem still persists. 
![screenshot 2018-07-24 15 51 00](https://user-images.githubusercontent.com/36243094/43174623-bf1c7eec-8f80-11e8-8446-c2f78550f70d.png)
etc.

**Comment by iAmWillShepherd** [comment]
I may be missing something... I don't see a rule listed for git in your screenshot.

**Comment by Mehmet2209** [comment]
iOS için Outlook<https://aka.ms/o0ukef> uygulamasını edinin
________________________________

**Comment by PaperSlips** [comment]
ghd-git-2: %USERPROFILE%\AppData\Local\GitHubDesktop\app-1.2.6\resources\app\git\mingw64\bin\git.exe

ghd-git-cmd: %USERPROFILE%\AppData\Local\GitHubDesktop\app-1.2.6\resources\app\git\cmd\git.exe

@iAmWillShepherd

**Comment by shiftkey** [comment]
We didn't quite get around to following up on this in a timely manner, but I'll call out from the logs that the Git operations (performed by `git.exe`) don't seem to be affected on the last run:

```
2018-07-23T20:23:53.988Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: GraphicsImplementation - PaperSlips (has token)
2018-07-23T20:23:55.519Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.494s)
2018-07-23T20:24:21.557Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: GraphicsImplementation - PaperSlips (has token)
2018-07-23T20:24:41.571Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: GraphicsImplementation - PaperSlips (has token)
2018-07-23T20:24:42.741Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.149s)
```

And I don't see any failing API operations in the last launch of the app either.

Sadly the user is no longer contactable, so we are unable to follow up and confirm this is still occurring.

**Comment by ddesmond** [comment]
Have same issue. after each githubdesktop update, my firewall denies github zo network. and then i spend hours debuging why and what rule has been changed. ive added all from 1.60 and nothing helps.
What request should i write for this to work on your next update?
Its not that my machine is changing but the exe of GHD is changing place. I understand that you develop more features and make it secure and what not, but this is a bit akward situation.

**Comment by steveward** [comment]
@ddesmond are you able to view the firewall logs to see specifically what is being blocked?

> ive added all from 1.60 and nothing helps.

Can you clarify the exact steps you took here? Did you whitelist the `%LocalAppData%\GitHubDesktop\app-1.6.0` directory?

**Comment by haXs** [comment]
Just stumbled across this on an unrelated search but I think I can add some value to this, if not for this issue but in the future,  Windows firewall does not run under the user context so it has no concept of local variables such as %USERPROFILE% or %localappdata% , if you go to the Windows Defender Firewall console > Monitoring > Firewall and look at the rules as they have applied,  you will likely see all the rules evaluated to a path like c:\windows\ServiceProfiles\LocalService rather then your profile

**Comment by zaheer-s** [comment]
For HTTPS sync this is the path C:\users\<username>\appdata\local\githubdesktop\app-2.2.4\resources\app\git\mingw64\bin\git-remote-https.exe

Can use my answer here to troubleshoot https://serverfault.com/questions/316428/does-windows-firewall-have-the-ability-to-log-which-exe-is-blocked/841940#841940

**Comment by nanabananab** [comment]
> Just stumbled across this on an unrelated search but I think I can add some value to this, if not for this issue but in the future, Windows firewall does not run under the user context, It runs under LocalService, so the variables like %USERPROIFLE% resolve to that service account rather then your profile. If you go to the Windows Defender Firewall console > Monitoring > Firewall and look at the rules as they have applied, you will likely see all the rules evaluated to a path like c:\windows\ServiceProfiles\LocalService rather then your profile

Solved: just use the plain resolved path instead of %USERPROFILE%. Specifically need this one rule:
C:\Users\me\AppData\Local\GitHubDesktop\app-2.2.4\resources\app\git\mingw64\bin\git-remote-https.exe
