### ISSUE TITLE
site.min.css keeps being added even if ignored

### ISSUE THREAD

**Issue by JeanCollas** [desktop/desktop#5229]
We have deleted the site.min.css from our repository, added it many times to the gitignore file, but the file keeps showing up in github desktop. 

It is located in /Project/wwwroot/css/site.min.css, and when we click on it, do "ignore file", it adds a line to gitignore "/Project/wwwroot/css/site.min.css", but the file remains in the list of modified files.

We don't understand why and find it quite annoying. 
Any way to fix this?

**Comment by shiftkey** [comment]
@JeanCollas thanks for the report. We're already tracking this in #2537 and that has details about what is happening:

> This behaviour occurs due to the fact that Git will only apply gitignore rules to untracked files - once a file is tracked it doesn't care about your .gitignore file contents.

And why we haven't settled on a resolution for it yet: https://github.com/desktop/desktop/pull/3164#issuecomment-339789343

Please follow along with #2537
