### ISSUE TITLE
Branches/Commits timeline

### ISSUE THREAD

**Issue by JeanCollas** [desktop/desktop#5231]
In previous (beta?) version of Github Desktop, there used to be at the top a timeline showing branches, and commits as dots. It was quite convenient to understand the past commits. 

I can't find any way to get it back in the new versions, I guess this version is a rewrite of the older one, but is there any plan to see it coming in a future version?

I am talking about this one (pic found on stackoverflow):
![image](https://user-images.githubusercontent.com/3519393/43136423-f45d1e28-8f48-11e8-93d8-82927413aac8.png)

**Comment by shiftkey** [comment]
@JeanCollas thanks for the report. 

We made a decision as part of the Electron transition to not bring the old Comparison Graph across. We're talking about this in #1634 but for the moment we're rethinking that feature, so we're not ready to actually implement it or something in that vein: https://github.com/desktop/desktop/issues/1634#issuecomment-400461989

Please follow along with #1634 in the meantime.

**Comment by dumitrule** [comment]
Thank you!

**Comment by JeanCollas** [comment]
@shiftkey I do not approve your decision, but I understand that it is not my project and I am just a user among others. 
Thanks for taking time to reply.
I hope to see this top feature back soon.

**Comment by bsherwoodofdaptiv** [comment]
I'll agree with the 'don't approve' group. It really was a great way to see when a branch had been committed, or synced in other branches. this is specifically why I prefer the old version. I made the move to the new 'desktop' app and it has not been enjoyed. It also helped to rapidly determine how long of a gap in time the branch has sat between new commits (relatively speaking).

Sure, it was a design decision.  (ie: we don't feel like it, not really important, people can 'just deal with it' ). But it was one of the best adoption features that made my first transition into github worth it. Now, not so much.
