### ISSUE TITLE
NOT WORKING CORRECTLY

### ISSUE THREAD

**Issue by tyetech** [desktop/desktop#5232]
[adxregistrator.log](https://github.com/desktop/desktop/files/2223511/adxregistrator.log)

## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@tyetech This log file isn't for GitHub Desktop, and I can't really tell you where it's from.

```
Add-in Express Registrator Log File: 05/13/2018 20:25:48

...
```

I recommend contacting the vendor to see if they have any support channels available.
