### ISSUE TITLE
History missing latest commit

### ISSUE THREAD

**Issue by Cherry** [desktop/desktop#5243]
## Description
As of the latest beta, the "History" tab doesn't show the most recent commit and is always one commit behind. This affects all repos.

## Version
* GitHub Desktop: 1.3.0-beta4
* Operating system: Microsoft Windows [Version 10.0.17134.165]

## UI
![](https://up.jross.me/t02ci)

## Actual
![](https://up.jross.me/9674q)

Let me know if you need any further info. I believe the steps to replicate should be pretty self-explanatory.

**Comment by shiftkey** [comment]
@Cherry thanks for the report! Is this available with a public repository, so that I can test the same behaviour you're seeing?

**Comment by shiftkey** [comment]
@Cherry thanks for the extra example - I just wanted to confirm that I didn't only fix the repository I was looking at. Hopefully we can get #5244 into the next release!
