### ISSUE TITLE
Cannot login on windows 10 desktop app

### ISSUE THREAD

**Issue by pnewman-cti** [desktop/desktop#5248]
## Description

I cannot login via the desktop app. It just hangs and spins.  password works fine on web

## Version

* GitHub Desktop:

* Operating system:
Microsoft Windows [Version 10.0.17134.165]

## Steps to Reproduce

step 1 try to login
### Expected Behavior

log me into my github account
### Actual Behavior

hangs/spins

**Comment by shiftkey** [comment]
@pnewman-cti thanks for the report!

The steps to reproduce the issue are not clear, and don't cover details like:

 - are you signing in via the browser or with your username/password combination?
 - do you have 2FA enabled on your account?
 - what do you mean by "hangs/spins"? Can you elaborate?

Also, could you attach the full log files generated by the app? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @pnewman-cti if you're able to answer the questions above we'd be happy to revisit this issue.
