### ISSUE TITLE
Add 'Open in Git Bash'

### ISSUE THREAD

**Issue by UgurAldanmaz** [desktop/desktop#5250]
I frequently use GitHub Desktop but sometimes I need to use Git Bash. Opening the repository folder then right clicking then selecting the 'Git Bash Here' is boring.

There is a menu item to open the repository in Command Prompt. A menu item to open the repository in Git Bash would be nice. Also keyboard shortcut would be helpful.

![image](https://user-images.githubusercontent.com/5686267/43220667-449b1d62-9053-11e8-8461-a9c330d7a5d3.png)

**Comment by shiftkey** [comment]
@UgurAldanmaz if you select **File** | **Options** and then navigate to the **Advanced** tab you'll be able to select from a number of shells installed on your machine:

<img width="507"  src="https://user-images.githubusercontent.com/359239/43221221-a0c8d0b0-9022-11e8-9545-1b2656521325.png">

If you already have Git for Windows installed, Git Bash will be available in the list.

**Comment by UgurAldanmaz** [comment]
Thank you very much. How can I change the keyboard shortcut?

**Comment by vldcom** [comment]
Hello. I can't find Git Bash in that list, I only have powershell and command promp.

**Comment by tidy-dev** [comment]
@vldcom Make sure Git Bash is installed on your machine. If it is, I would recommend uninstalling and reinstalling it.

**Comment by khaideethailand** [comment]
ฉันกำลังตรวจสอบ
