### ISSUE TITLE
Customizable keyboard shortcut support

### ISSUE THREAD

**Issue by UgurAldanmaz** [desktop/desktop#5253]
My keyboard language does not support some of the keyboard shortcuts. For example, I cannot press `'` without `Shift` key. So I cannot use `Ctrl+'` shortcut.

This problem can be solved by allowing to change keyboard shortcuts.

**Comment by iAmWillShepherd** [comment]
@UgurAldanmaz would you mind sharing the type of keyboard layout you are having this issue with?

**Comment by shiftkey** [comment]
I'm inclined to fold this into #3240 because I think we need to teach Desktop to be aware of keyboard locale when choosing it's default shortcuts. Opening it up to changing shortcuts to arbitrary things requires much more work, and we've not gotten much interest in that.

**Comment by UgurAldanmaz** [comment]
@iAmWillShepherd I'm using the Turkish Q keyboard layout.

![here](https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/KB_Turkey.svg/2000px-KB_Turkey.svg.png)

> I think we need to teach Desktop to be aware of keyboard locale when choosing it's default shortcuts

@shiftkey You are absolutely right. This is the better solution.

Thanks for your interest.

**Comment by shiftkey** [comment]
> You are absolutely right. This is the better solution.

I'll add your setup to #3240 so we include it with our testing. Thanks for the extra info.
