### ISSUE TITLE
Can't View History After Deleting Branch While in "Behind" / "Ahead" View

### ISSUE THREAD

**Issue by JosephTLyons** [desktop/desktop#5256]
## Description
If you are in the comparison view between branches ("Behind" / "Ahead") and you delete the last branch besides the master, you will be stuck in "Behind" / "Ahead" view.  You can't get back to the history of master unless you go to the menu option `View > Show History`.  Clicking the history button will not bring it back.

## Version
* GitHub Desktop: v1.2.6
* Operating system: macOS 10.13.6

## Steps to Reproduce
1. Use a repo that has only a master branch
2.  Create new branch and make sure you are currently in that branch
3. Change to the history tab, select `select branch to compare`, and pick the `master`
4. Delete new branch and find yourself stuck in that view.  You will notice that the branch name inside the compare field is still stuck on `master` and that it is greyed out.   You are not able to see the commit history until you use the menu option `View > Show History`.

### Expected Behavior
I expected the history button to bring me back to the history or for it to show up automatically after the branch was deleted, since there was no branch to compare to now that the new one was deleted.

### Actual Behavior
I am stuck in the "Behind" / "Ahead" view

![history bug](https://user-images.githubusercontent.com/19867440/43242632-38077074-9070-11e8-8441-a4567eb52414.gif)

**Comment by shiftkey** [comment]
@JosephTLyons thanks for the report and the detailed writeup.

@iAmWillShepherd anything else we need to confirm and prioritize this? I'm fine with leave it for a `1.3.x` bugfix release given the setup required.

**Comment by iAmWillShepherd** [comment]
> anything else we need to confirm and prioritize this?

Nope and I'm also fine with tagging this to milestone 1.3.x.
