### ISSUE TITLE
cannot fetch from https remotes

### ISSUE THREAD

**Issue by bmcdonnell-ionx** [desktop/desktop#5258]
## Description

I cannot fetch from `https` remotes with GitHub Desktop.

## Version

* GitHub Desktop:
1.2.6

* Operating system:
Microsoft Windows [Version 10.0.14393]
64-bit

## Steps to Reproduce

1. Install GitHub Desktop
2. File menu &rarr; Add local repository...
3. Browse to a local repo which already has an `https` remote set as its `origin`
4. Click `Fetch origin`

### Expected Behavior

Successful fetch.

### Actual Behavior

`fatal: unable to access 'https://git.xiph.org/flac.git/': schannel: failed to open CA file 'C:/Program Files (x86)/Git/mingw32/ssl/certs/ca-bundle.crt': No such process`

## Additional Information

I do not have a `C:/Program Files (x86)/Git` folder (let alone `C:/Program Files (x86)/Git/mingw32/ssl/certs/ca-bundle.crt`).

![2018-07-26 - github desktop https fetch error](https://user-images.githubusercontent.com/34172339/43267845-0b155304-90bd-11e8-8f5b-95a3fad864a9.png)

### Logs

[2018-07-26.desktop.production-redacted.log](https://github.com/desktop/desktop/files/2232373/2018-07-26.desktop.production-redacted.log)

**Comment by shiftkey** [comment]
@bmcdonnell-ionx thanks for the report.

I believe your issues is the same as https://github.com/desktop/desktop/issues/4832, because of system config entry that looks like this:

```
file:"C:\ProgramData/Git/config" http.sslcainfo=/bin/curl-ca-bundle.crt
```

You should be able to see this entry by running this command:

```
$ git config -l --show-origin
```

This entry is no longer valid (Git installations should not be adding this entry to this file) and removing this entry:

```
[http]
  sslCAinfo = /bin/curl-ca-bundle.crt
```

from `C:\ProgramData\Git\config` should address the issue for Desktop.

**Comment by bmcdonnell-ionx** [comment]
Yes, removing those lines from the `config` file now allows me to fetch from `https` sources.

So now we have a work-around. I'd say the solution is to prevent the issue, such as suggested [here](https://github.com/desktop/desktop/issues/4832#issuecomment-397560524).

Why did this happen? Any progress on properly resolving it?

**Comment by shiftkey** [comment]
@bmcdonnell-ionx this was an upstream change in Git for Windows around new curl behaviour that coincided with a security update. I reported it in https://github.com/git-for-windows/git/issues/1698 and the next update will include a config flag for us to control SChannel behaviour better.
