### ISSUE TITLE
pare down runtime errors generated by logging infrastructure

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#5265]
We use `winston` which should generate daily logs and keep around the most recent 14, but there's some scenarios which generate errors that are unseen by the user that still end up in our error reporting service. 

These are the groups of errors that I think we can ignore, because there's nothing we can really do:

 - a filesystem error suggesting there is no available space on the drive  (macOS)

`ENOSPC: no space left on device, open '/Users/[account]/Library/Application Support/GitHub Desktop/logs/2018-07-27.desktop.production.log'`

 - a filesystem error because the remote share was not available (Windows)

`ECONNRESET: connection reset by peer, stat '\\[server]\users\[account]\AppData\Roaming\GitHub Desktop\logs\2018-07-26.desktop.production.log'`

 - a generic permissions error accessing the log directory (Linux)

`EACCES: permission denied, open '/home/[account]/.config/GitHub Desktop/logs/2018-07-26.desktop.production.log'`

 - unable to stat the log file (Windows)

`EINVAL: invalid argument, stat 'C:\Users\[account]\AppData\Roaming\GitHub Desktop\logs\2018-07-25.desktop.production.log'`

There's probably some others, but these are an interesting group to start with.

The source for this logging is [here](https://github.com/desktop/desktop/blob/master/app/src/main-process/log.ts), and you'll see that we're just rethrowing errors reported in here.

If someone wants to look into this I think the steps to address this are:

 - inspect the raised errors for error codes (see what we did with dugite https://github.com/desktop/dugite/pull/164)
 - compare the found error codes to a list that we know we can't handle
 - mute those errors we know we can't do anything about

**Comment by shiftkey** [comment]
Switching this over to `meta` because this likely needs a fresh round of :eyes: to understand what's noisy and what should be looked at. Once this is done, we can extract more granular tasks and close it out.

**Comment by outofambit** [comment]
closing this until we're ready to look at it more closely, this filtering could also be done server side in our exception report handling infrastructure.
