### ISSUE TITLE
Odd UI performance issues when committing

### ISSUE THREAD

**Issue by VizuaaLOG** [desktop/desktop#5274]
## Description
I've seen a few issues relating to performance although not seeing anything similar to what I am having. Generally, the app seems to be performing great, I can switch branches etc. fine, preview/stage changed files etc.

However, when committing changes that's when I get some odd behaviour. Typing the message etc. is fine no issues there. However, when I commit the message the commit happens generally straight away. However, the UI seems to take a couple seconds longer to update, my comments etc remain filled out then eventually clear once 2 - 3 seconds have passed.

I don't have any hooks associated with my repo, it's a public Github repository. Pushing changes is also fine no performance issues there.

I've included a performance profile below, not sure if this includes screenshots (not really used exported a profile) as the screenshots clearly show the UI lag that exists. I've also included a gif that shows the issue.

I'm also getting a similar issue, with different non-public (and different repo host) repositories on my work machine, which is also High Sierra.

**Edit: I don't seem to have the long wait times when doing it via git directly in terminal.**

## Version

* GitHub Desktop: 1.2.6

* Operating system: macOS High Sierra 10.13.6

## Steps to Reproduce

1. Open a repo in Github Desktop (as this is an open source project you could try using the same repo, see if that helps reproduct. repo is BulmaJS)
2. Make some changes
3. Stage and write a commit message
4. Commit the changes - either by clicking the button or pressing command+enter
5. Commit seems to happen fairly quick, but the UI take a little time to update

### Expected Behavior
I expect the commit messages to dissapear at the same time the commit is made. This is normal and used to be the case.

### Actual Behavior
The commit is made (shown by the small section below the commits popping up) but the messages remain in the boxes for a couple or more seconds.

## Additional Information

[Profile-20180727T213817.json.zip](https://github.com/desktop/desktop/files/2237195/Profile-20180727T213817.json.zip)

![jul-27-2018 21-52-31](https://user-images.githubusercontent.com/4404472/43345996-79b0ccdc-91e7-11e8-9eeb-bb245c4da231.gif)

### Logs

[2018-07-27.desktop.production.log](https://github.com/desktop/desktop/files/2237207/2018-07-27.desktop.production.log)

Ignore the errors relating to the lock file, this was me being impatient lol.

**Comment by shiftkey** [comment]
@VizuaaLOG thanks for the details and the profile. 

At first glance based on that GIF:

 - We usually show a spinner in the `Commit to [branch]` while a commit is in progress, but as I can't see that I guess the commit takes very little time
 - My gut feeling is some background work _after_ the commit is done might be blocking the commit form from updating to clear itself

**Comment by billygriffin** [comment]
I tried to reproduce this with the same repo on multiple machines and was unable to do so. Are you still having this issue @VizuaaLOG?

**Comment by iAmWillShepherd** [comment]
I just looked over the performance logs and am not seeing any performance issues, so I'm inclined to agree with what @shiftkey said. It's likely the case the component isn't being updated correctly.

**Comment by billygriffin** [comment]
@VizuaaLOG Thanks! I'm not positive we're going to be able to dig into this, but at least understanding whether it's still a problem would be great. Have you seen it occur on other projects while you're using Desktop?

**Comment by VizuaaLOG** [comment]
@billygriffin no haven't experienced it at work recently. And don't remember having it with other projects either. If I still have it I'll try re-cloning the repo. Just in case something odd is happening there.

**Comment by VizuaaLOG** [comment]
@billygriffin Just tested again with the latest update (1.4.0) and seems to be super snappy when committing. Not sure if the update has performance updates or if the test commit doesn't trigger whatever causes the issue.

If I have it again when I start properly continuing the project, when life stops taking over haha, then I'll try recloning the repo, as I said above I'm not getting this issue at work anymore so seems more like a repo-specific thing now.

Thanks to all who were helping with this issue.

**Comment by billygriffin** [comment]
Thanks for the update, really appreciate it!
