### ISSUE TITLE
Adding ability to view Jupyter Notebooks in Desktop app

### ISSUE THREAD

**Issue by Nikronic** [desktop/desktop#5279]
It makes too much time to every time upload notebook to Jupyter and view its content after any pull or commit. Just view Jupyter notebook like Github webpage.

current:
![image](https://user-images.githubusercontent.com/32401852/43388144-9cdc2be4-93fd-11e8-9e5d-1f4c299fac24.png)

expected:
![image](https://user-images.githubusercontent.com/32401852/43388216-caf21a2a-93fd-11e8-882e-7e78825e007f.png)

Best regards

**Comment by shiftkey** [comment]
@billygriffin technical issues aside, I'd love to put this in front of you:

> It makes too much time to every time upload notebook to Jupyter and view its content after any pull or commit. 

This is an interesting point about the feedback loop when working with things locally, and users may be hesitant to push changes if they can't verify them locally.

**Comment by steveward** [comment]
Requested in https://github.com/desktop/desktop/issues/12121.

**Comment by alexlenail** [comment]
I'd like to see this as well.
