### ISSUE TITLE
Repo search operators OR |

### ISSUE THREAD

**Issue by penCsharpener** [desktop/desktop#5280]
**Describe the solution you'd like**
enable OR operator in repository seach

**Teachability, Documentation, Adoption, Migration Strategy**
users with lots of repos in their repo list would benefit from concatenating parts of the repo names together with a pipe character `|` so that related repos (dependencies) can show up in a single search. 

![mockup](https://user-images.githubusercontent.com/26190934/43393774-8bf99fd2-93f8-11e8-9612-6be695749c18.png)

Additionally Desktop could save recent searches for easy selection.

**Comment by shiftkey** [comment]
@penCsharpener thanks for the suggestion.

We're using  [`fuzz-aldrin-plus`](https://github.com/jeancroy/fuzz-aldrin-plus) in the app to do this fuzzy-find lookup, and if there's a way for us to support this syntax it might live in here. But I'm not familiar with how that might work.

> Additionally Desktop could save recent searches for easy selection.

Could you open a fresh issue for this and provide some context, so it doesn't get lost in the main discussion?

**Comment by iAmWillShepherd** [comment]
@penCsharpener could you provide some examples of when having the ability to filter using an `OR` operator would have improved your workflow? I'm also interested in how you've been getting along without the ability to filter on unions. Do you find yourself having to work harder to get around the current limitation?

**Comment by penCsharpener** [comment]
In my case I have around 30 `C#/.NET` repos in `Desktop` and it's getting longer over time. 

I keep all the repos in the list in case I need to fix bugs in projects that I'm mostly done with. Most of the time though I work on one solution in Visual Studio. It consists of different projects - most of the projects are separate git repos. 

With the OR search I could reduce the list to exactly those project in my solution which are separate repos. 

So far I either make the window of `Desktop` really large to fit all repos in the list which is not my preferred option. Or I redo the search by hitting `Ctrl + T`.

I definitely find it a limitation, not being able to filter the list more precisely. I end up committing regularly to the main repo of the solution but not so much to the projects which are dependencies/class libraries. Those class libraries are also used in different solutions by different people. Small commits are of the essence.

Hopefully this helps to colour in the picture.

Alternatively it would help to be able to run multiple instances of `Desktop` each showing a different repo which is part of my solution.

**Comment by penCsharpener** [comment]
@shiftkey Creating another issue about saving searches only makes sense if more complex searches are possible. For example I use HeidiSQL at lot on Windows. It has a search box for tables which supports regex and it saves recent searches. I do there exactly what I'm suggesting here: `task|proj|noti|user` would be an example which would result in showing all tables that (in HeidiSQL's case) start with those characters giving me a nice selection of all the tables related to what I'm working on. And often I would then pull this search out again from the saved history.

I really think this improved the workflow.

**Comment by shiftkey** [comment]
Moving this into the `user-research` bucket to better understand the flows around filtering repositories.

**Comment by billygriffin** [comment]
Hi @penCsharpener, sorry I missed this. I'm going to roll this into #6460 because we're actively looking at similar things there. Thanks so much for the feedback, and please follow along there!
