### ISSUE TITLE
add support for detecting new User Install of VS Code Insiders

### ISSUE THREAD

**Issue by CharlesStover** [desktop/desktop#5281]
File -> Options -> Advanced -> External editor
![image](https://user-images.githubusercontent.com/343837/43398398-980d4128-93cd-11e8-901c-b3fdecd80fcf.png)

**Describe the solution you'd like**
I believe VS Code Insiders is supported, however Microsoft has recently released a new version of VS Code that installs to the user directory instead of Program Files, to prevent the requirement of running as administrator in order to get automatic updates.
I recently changed to this version of VS Code, and GitHub Desktop is no longer acknowledging my editors installation.

**Comment by shiftkey** [comment]
@CharlesStover thanks for the report. It's been a while since I last looked at how we detect VSCode, and it was just around the time 64-bit support was rolling out. The relevant things we look for are:

 - a registry entry for the app telling us about where it's located (these are all HKLM, so perhaps there is a new location under HKCU that these list themselves in)

https://github.com/desktop/desktop/blob/bdf212301b11c2cdbf5123e1c69bace89bfe36b5/app/src/lib/editors/win32.ts#L78-L92

- details about the publisher (these should be the same, maybe?) 

https://github.com/desktop/desktop/blob/bdf212301b11c2cdbf5123e1c69bace89bfe36b5/app/src/lib/editors/win32.ts#L168-L172

- the location of the command line shim to run (shouldn't need changing)

https://github.com/desktop/desktop/blob/bdf212301b11c2cdbf5123e1c69bace89bfe36b5/app/src/lib/editors/win32.ts#L137-L138

Let me know how your new installation is different, it shouldn't be too hard to add support in if the installer works similarly to the previous versions.

**Comment by shiftkey** [comment]
This issue has been marked as `help wanted`, which means:

  - we're interested in seeing this resolved, but haven't prioritized it yet on our roadmap
  - we think this is small enough that someone with a bit of experience with TypeScript and React can dive into it
  - we think it can be worked on in isolation, so someone can work on it at their own pace

If you're interested in this, reply to this to let everyone know. Also feel free to comment here if you have any questions about the task.

If you have something working and it's ready to review, please [open a pull request]() and ensure it contains "Fixes #5281", so we can associate it with this issue.

**Comment by CharlesStover** [comment]
Would have never found this bad boy if search wasn't available, but it appears to be under:
key: `HKEY.HKEY_LOCAL_MACHINE`
subkey: `SOFTWARE\WOW6432Node\Tanium\Tanium Client\Sensor Data\Applications\Code - Insiders` (Path)

The publisher, display name, and command line shim are the same.
Unless you just want to give it a different display name in case they have multiple installations of VS Code. I had two for a while. Since this one doesn't use Program Files, they don't conflict on installation.

**Comment by shiftkey** [comment]
```
key: HKEY.HKEY_LOCAL_MACHINE
subkey: SOFTWARE\WOW6432Node\Tanium\Tanium Client\Sensor Data\Applications\Code - Insiders
```

This is still under HKLM, which requires elevation to write to, and I'm not sure where those intermediate `Tanium\Tanium Client\Sensor Data\` subkeys are coming from. A cursory google search shows Tanium is a company specializing in "endpoint security and systems management" so maybe they're injecting themselves into the process 🤷‍♂️ 

I grabbed the latest version of VSCode Insiders (1.26.0, 64-bit) which:

 - triggered a UAC prompt
 - defaulted to `C:\Program Files\Microsoft VS Code Insiders` (you can change this of course)
 - installed to `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{1287CAD5-7C8D-410D-88B9-0D1EE4A83FF2}_is1`

I'm not sure where your installer came from, but my gut feeling here is that this "find the registry entry at some other location" isn't currently supported in Desktop.

**Comment by shiftkey** [comment]
For reference, the Atom installer doesn't require elevation and it installs itself to `HKEY_CURRENT_USER\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\atom`, which is the behaviour I'd expect from VSCode if this was a supported scenario.

**Comment by CharlesStover** [comment]
The Users installer is not what you get from the big Download button on the VS Code Insiders website. You can find the install link [in their documentation](https://code.visualstudio.com/updates/v1_25#_user-setup-for-windows). The non-Users installation also prompts you to download the Users installer from inside the editor, which makes it a little odd that the Users installation isn't the default link.

**Comment by shiftkey** [comment]
@CharlesStover thanks for the installer link. This shows that it installs to `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\{217B4C08-948D-4276-BFBB-BEE930AE5A2C}_is1` which is more like what I was expecting.

I think if we add that lookup location to the VSCode Insider registry path that should look for this new location.

**Comment by Cologler** [comment]
@shiftkey vscode user setup (x64):

`\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\{771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1`

![snipaste_2018-08-16_14-11-15](https://user-images.githubusercontent.com/10906962/44191491-4582d500-a15e-11e8-829b-2fdc99f5af65.png)

**Comment by Elderry** [comment]
According to the [update page](https://code.visualstudio.com/updates/v1_26#_user-setup-for-windows) of vscode:
> The user setup package for Windows is now available on stable.
I think more people will need this feature now.

**Comment by shiftkey** [comment]
> I think more people will need this feature now.

The details on what needs to change are listed [here](https://github.com/desktop/desktop/issues/5281#issuecomment-408854865) but I suspect it's just adding the new registry paths to [`app/src/lib/editors/win32.ts`](https://github.com/desktop/desktop/blob/master/app/src/lib/editors/win32.ts)

**Comment by shiftkey** [comment]
Just letting everyone know that `1.3.4` has been published and should support the new User scope install.
