### ISSUE TITLE
Connection to Github.com is not established

### ISSUE THREAD

**Issue by Narendra-Majhi** [desktop/desktop#5283]
Hello,
I am using the GitHub desktop to manage my files locally. But whenever I try to publish any branch to the website. In this case, Circle-and-Line.ipynb . It always returns a fatal error, with a message "fatal: unable to access 'https://github.com/Narendra-Majhi/Circle-and-Line.git/': Could not resolve host: github.com".

It will be helpful if this matter is resolved quickly. In case of any further assistance, drop a mail back.

**Comment by billygriffin** [comment]
👋 @Narendra-Majhi! Thanks for creating an issue. It looks like your issue may be similar to this one, which could be related to connectivity and/or using a proxy: https://github.com/desktop/desktop/issues/4872

Are any of those conditions in place?

**Comment by Narendra-Majhi** [comment]
@billygriffin  The issue seems to be resolved. Now my system works fine and can sync with the website.
Thank you Billy.

**Comment by billygriffin** [comment]
Great to hear!
