### ISSUE TITLE
Can't find Git following upgrade from 1.2.6 -> 1.3.0

### ISSUE THREAD

**Issue by gedrick** [desktop/desktop#5285]
## Description

Github Desktop is unable to locate Git, although committing, pushing, pulling, ie. business as usual Git operations work correctly. Between 2-6 popups indicating the inability to find Git sporadically show up now. Typically this happens on app launch, and then sporadically afterwards.

## Version

* GitHub Desktop: 1.3.0

* Operating system: Mac OSX High Sierra

## Steps to Reproduce

1. Upgrade from 1.2.6 to 1.3.0

### Expected Behavior

1. Github Desktop should not repeatedly show popups for losing Git.
### Actual Behavior

1. It shows a pile of popups indicating that it can't find Git.

## Additional Information

![screen shot 2018-07-30 at 4 46 08 pm](https://user-images.githubusercontent.com/647379/43422581-225bd0fc-9418-11e8-8410-5440e9000aff.png)

### Logs

> 2018-07-30T20:48:43.885Z - info: [ui] [AppStore] loading 8 repositories from store
> 2018-07-30T20:48:43.885Z - info: [ui] [AppStore] found account: gedrick (Christopher "Geddy" Lee)
> 2018-07-30T20:48:43.920Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: **HIDDEN** - gedrick (has token)
> 2018-07-30T20:48:43.920Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: **HIDDEN** - gedrick (has token)
> 2018-07-30T20:48:43.920Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: **HIDDEN** - gedrick (has token)
> 2018-07-30T20:48:43.920Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: **HIDDEN** - gedrick (has token)
> 2018-07-30T20:48:43.920Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: **HIDDEN** - gedrick (has token)
> 2018-07-30T20:48:43.920Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: **HIDDEN** - gedrick (has token)
> 2018-07-30T20:48:43.921Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: **HIDDEN** - gedrick (has token)
> 2018-07-30T20:48:43.921Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: **HIDDEN** - gedrick (has token)
> 2018-07-30T20:48:44.425Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: **HIDDEN** - gedrick (has token)
> 2018-07-30T20:48:44.441Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: **HIDDEN** - gedrick (has token)
> 2018-07-30T20:48:44.599Z - info: [ui] launching: 1.3.0 (Mac OS 10.13.6)
> 2018-07-30T20:48:44.599Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper.app/Contents/MacOS/GitHub Desktop Helper'

**Comment by shiftkey** [comment]
@gedrick thanks for the report - please follow along with #5282 as there is some more context here https://github.com/desktop/desktop/issues/5282#issuecomment-408979834 and a fix is underway

**Comment by gedrick** [comment]
Thanks @shiftkey  - just came back here to link your comment on there. I had a missing repository and that was causing the error. 👍 

Fix here - https://github.com/desktop/desktop/issues/5282#issuecomment-408979834
