### ISSUE TITLE
After upgrade & startup get error "spawn C:\Users\xxx\AppData\Local\GitHubDesktop\app-1.3.0\resources\app\git\cmd\git.exe ENOENT"

### ISSUE THREAD

**Issue by jvopalensky** [desktop/desktop#5286]
## Description

I get this error (twice) in a pop-up dialog right after updating and every time I restart the app. Once I hit 'close' all seems fine.

## Version

* GitHub Desktop:
1.3.0

* Operating system:
Windows 10, build 17134.167

## Steps to Reproduce

Just did update by restarting the app

### Expected Behavior

No error

### Actual Behavior

Error in popup dialog

**Comment by shiftkey** [comment]
@jvopalensky thanks for the report - please follow along with #5282 as there is some more context here #5282 (comment) and a fix is underway.

**Comment by JosephTLyons** [comment]
Yep, same here.
