### ISSUE TITLE
After github desktop update, getting `spawn /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git ENOENT` error

### ISSUE THREAD

**Issue by nickeubank** [desktop/desktop#5290]
## Description

Keep getting `spawn /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git ENOENT` error since updating today to 1.3.0. 

Possibly #5289 , but not sure -- made no changes, just updated software and started getting constantly. 
## Version

* GitHub Desktop: 1.3.0

* Operating system: MacOS 10.13.6

### Logs

[2018-07-30.desktop.production.log](https://github.com/desktop/desktop/files/2243013/2018-07-30.desktop.production.log)

**Comment by billygriffin** [comment]
Hi @nickeubank, thanks for the report! Sorry about that, it does look to be the same as #5289. It seems to be related to repositories that you're tracking in GitHub Desktop that have been deleted or moved on your local file system.

We're working on a hotfix now which should make it usable again. Please follow along there, and hopefully we'll have something out shortly.

**Comment by nickeubank** [comment]
Thanks! @billygriffin That's actually helpful info -- I'll try and remove all the repos from github desktop I'm not actively using anymore. Hopefully that'll fix.

**Comment by billygriffin** [comment]
@nickeubank We released 1.3.1 yesterday evening, so hopefully it should be working for you now!

**Comment by nickeubank** [comment]
Thanks!
