### ISSUE TITLE
Getting error (Git returned an unexpected exit code '128') after updating to v1.3.1

### ISSUE THREAD

**Issue by gencer** [desktop/desktop#5291]
## Description
Few minutes ago I've updated to v1.3.1 and after opening GitHub Desktop (everytime) I get this error pops up.

## Version
* GitHub Desktop: 1.3.1
* Operating system: Windows 10 x64

## Steps to Reproduce
1. Update to v1.3.1
2. Open Desktop. You get error.
3. Close and re-open Desktop.
4. You will get this error again.

You will also get this error if you keep GitHub Desktop open. Probably a background task.

### Expected Behavior
No error should raised.

### Actual Behavior
`Git returned an unexpected exit code '128' which should be handled by the caller.'`

## Additional Information
No additional info

### Logs
I could attach log here but I investigated it and no error or similar messages but infos available. I avoid uploading all logs here due to some details about my private repositories in it.

**Update:** This evening I keep GitHub Desktop open in the background. After 5-6 hours, when I maximize it, I see error message already displayed. I just clicked `Close` however, another one pops up. I tried nearly hundred times and it seems GitHub Desktop does this in a loop in the background, so I got probably a thousand of errors. I had to close manually from task manager. Anyway, I just watch my GitHub Desktop today and it's indeed this error pops up every few minutes.

**Comment by manogi** [comment]
I have exactly the same issue on Mac OSX 10.13.6.
I also only see the expected log entries - only infos, some warnings, no errors and nothing that seems related to this.

**Comment by manogi** [comment]
As I read on the other issue today, this might only happen when updating - not when installing fresh? But I'm not sure how I uninstall and reinstall github desktop without having to add all my repos (quite a few) manually again...

**Comment by shiftkey** [comment]
@manogi don't worry about reinstalling - I think this is a corner case we've uncovered as part of the new background fetching. Given you have a lot of repositories in the list, I suspect one of them is failing for a `git status` (which Git returns 128 as a generic exit code) because the `.git` folder is now missing.

**Comment by shiftkey** [comment]
I've been able to reproduce this by:

 - add a repository to Desktop
 - outside Desktop, rename the `.git` directory to `.got`
 - switch back to Desktop so the repository is refreshed
 - :boom:

**Comment by manogi** [comment]
OK - I'll look throught the folders - the folder must be obsolete then if there is no .git in there... Thanks!

**Comment by KurtE** [comment]
I am running into this as well.  I have a lot of projects in the list, not sure which ones it is complaining about, it gives me two of these error messages each time.

**Comment by shiftkey** [comment]
@KurtE thanks for the information. We're aiming to put a fix together for this today - just gotta go through the appropriate review and QA process. Stay tuned!

**Comment by shiftkey** [comment]
Just a heads up for people who are arriving to this issue - the PR #5297 has been merged, but we're just looking to wrap up #5300 and aiming to publish a release tomorrow. Stay tuned.

**Comment by depsimon** [comment]
I had this issue too. I browsed all my repos in the interface and one of them was throwing this error. The repo in question was a specific private git repo and I removed it from the interface. 

It seems to have resolved the issue.

**Comment by lukexperias** [comment]
> I had this issue too. I browsed all my repos in the interface and one of them was throwing this error. The repo in question was a specific private git repo and I removed it from the interface.
> 
> It seems to have resolved the issue.

Hi, can you please explain me how to do this? 

I have the same error "Can't update https://github.com/hassio-addons/repository repo: Cmd('git') failed due to: exit code(128)"
Thanks in advance

**Comment by tierninho** [comment]
@lukexperias If you wish to remove a repository, open the repo list in Desktop and right-click to select the `Remove` option. 

If you would like to triage an issue you are facing, please open a [new issue](https://github.com/desktop/desktop/issues/new/choose). Thank you.
