### ISSUE TITLE
Deleting a Folder That Contains a Repo Outside of Desktop Triggers spawn Error

### ISSUE THREAD

**Issue by JosephTLyons** [desktop/desktop#5294]
## Description
If I leave GitHub Desktop set on a specific project, then delete that project on my comp, then switch back to GitHub Desktop, I get the error:

<img width="600" alt="screen shot 2018-07-31 at 12 40 32 am" src="https://user-images.githubusercontent.com/19867440/43438137-adfdf378-945a-11e8-94bf-b2842c79515b.png">

Dismissing it brings me back to the normal message of "Can't Find ProjectName:"

<img width="449" alt="screen shot 2018-07-31 at 12 43 25 am" src="https://user-images.githubusercontent.com/19867440/43438160-c8acd69e-945a-11e8-95dd-7f389325c1f7.png">

I don't think this used to happen, I think it used to just show the "Can't Find ProjectName" window.

## Version
* GitHub Desktop: v1.3.1
* Operating system: macOS 10.13.6

## Steps to Reproduce
1.  Leave project open in Desktop
2. Delete project outside of Desktop
3. Switch back to Desktop and see error message

### Expected Behavior
I expect to just see the "Can't Find ProjectName" window

### Actual Behavior
I see the spawn error message

**Comment by shiftkey** [comment]
@JosephTLyons thanks for the report.

This was uncovered while we were implementing the `1.3.1` hotfix yesterday. I opened #5289 to track fixing that, and hopefully this will go out with the next update, so please follow along with that.
