### ISSUE TITLE
Error pops up on cloning repositories on Github desktop, git hub desktop does not take the name and email of git

### ISSUE THREAD

**Issue by shubhof7** [desktop/desktop#5308]
## Description

I am using Github Desktop but everytime i try to clone a repository a message pops up of Meaningless REX Prefix 

## Version

* GitHub Desktop: 1.1.1

* Operating system: Windows 10

### Expected Behavior

The repository should be cloned 
### Actual Behavior

Error pops up 

### Logs

git version >= 1.8.2 is required for Git LFS, your version: [0x7FFD8AC43C40] ANOMALY: meaningless REX prefix used
[0x7FFD8AC5DA20] ANOMALY: meaningless REX prefix used
[0x7FFD8CA9D730] ANOMALY: use of REX.w is meaningless (default operand size is 64)
[0x7FFD8CAB5DD0] ANOMALY: use of REX.w is meaningless (default operand size is 64)
[0x7FFD8E36A650] ANOMALY: meaningless REX prefix used
git version 2.16.1.windows.1

**Comment by shiftkey** [comment]
@shubhof7 thanks for the report! This feels related to #5247 in that a different program is being run rather than our version of Git - but I can see some version of Git is being emitted in there.

What does your current PATH look like?

**Comment by shubhof7** [comment]
git version 2.18.0.windows.1

PATH=C:\Users\Dell\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Dell\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Microsoft\Web Platform Installer;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files (x86)\Brackets\command;C:\xampp\php;C:\composer;C:\Program Files\dotnet;C:\Program Files\nodejs;C:\WINDOWS\System32\OpenSSH;C:\Users\Dell\AppData\Local\Programs\Python\Python36-32\Scripts;C:\Users\Dell\AppData\Local\Programs\Python\Python36-32;C:\Program Files\Java\jdk1.8.0_66\bin;C:\Users\Dell\AppData\Local\Microsoft\WindowsApps;C:\Users\Dell\AppData\Roaming\Composer\vendor\bin;C:\Users\Dell\AppData\Local\atom\bin;C:\Users\Dell\AppData\Roaming\npm;C:\Users\Dell\AppData\Local\Microsoft\WindowsApps;C:\Users\Dell\AppData\Local\GitHubDesktop\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl

**Comment by shubhof7** [comment]
where git
C:\Program Files\Git\mingw64\bin\git.exe

**Comment by shiftkey** [comment]
@shubhof7 thanks for the details. I think this might be related to some [external software](https://social.technet.microsoft.com/Forums/ie/en-US/efd83b6a-dc86-4854-b05f-f484e1ed5596/anomaly-meaningless-rex-prefix-used?forum=winserverGP) that meddles with the environment:

> I looked at your screenshot, and my guess is that some non-Microsoft component (driver, software, utility) is installed and has "extended" the command processing environment with a REXX interpreter.
>
> A quick web search reveals that some people have found either AVG Antivirus software or NVidia display software might be the cause, and that uninstalling those could solve the issue.

[This thread](https://stackoverflow.com/questions/29063306/javafx-error-anomaly-meaningless-rex-prefix-used) also refers to graphics driver software - could an update to something video card related introduced this?

**Comment by shubhof7** [comment]
I tried uninstalling all software that could cause this like Java and others but the problem still exists.

**Comment by shiftkey** [comment]
@shubhof7 what anti-virus are you running? I've found some threads about TrendMicro needing an update for Windows 10 Anniversary Edition, [like this](https://success.trendmicro.com/solution/1115554-ping-command-results-show-an-anomaly-message-on-windows-10-anniversary-update-with-an-osce-11-0-sp1). 

Also, we upgraded Git LFS in version `1.2.4` - are you able to update Desktop and see if this behaviour persists?

**Comment by billygriffin** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in the previous comment. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
