### ISSUE TITLE
Zoom level is not retained after updating

### ISSUE THREAD

**Issue by ChiriVulpes** [desktop/desktop#5315]
I use 125% zoom, and so far every time I've updated the software (with the "restart to update" feature), the zoom level resets, and I have to zoom back in to 125% manually again. It's not a huge deal, just a minor annoyance. (Especially when there are a lot of minor updates after a release)

**Comment by steveward** [comment]
Thanks for opening this @Yuudaari. What operating system are you running on this machine? I just tested this out on macOS and was unable to reproduce this behavior after restarting to install an update.

**Comment by aryyya** [comment]
I also encounter this issue on Windows 10.

**Comment by aryyya** [comment]
I'm interested in helping fix this problem.

My initial thoughts are that the configuration file that stores user settings is being overwritten, or the field that stores the zoom level is not being retained in the new version after an update.

I cannot test out my theory however as I'm having trouble finding this configuration file in the first place. 😐

**Comment by Yuudaari** [comment]
It's `%AppData%/Roaming/GitHub Desktop/Preferences`
The relevant JSON path is: `partition.per_host_zoom_levels.<some long number>.<the path to the index.html file of the version of github desktop you're using>`

If I remove the line for app-1.3.4 (which is currently set to `1.2239010857415449` (which definitely is not 125%, lol), and relaunch the app, it displays at 100% zoom. Re-adding it and relaunching it puts it back at 125%

**Comment by aryyya** [comment]
@Yuudaari 

Ahhh ok. I see that now. I'd initially set my zoom level to 200% to look for something resembling `2.0` in a configuration file, and that `per_host_zoom_levels` entry showed `3.8017840169239308`, so it didn't really click that they were related in my head.

**Comment by outofambit** [comment]
Hi @Yuudaari @aryyya thanks for your research into this! I think the next step is to figure out which of the following is the cause:

> My initial thoughts are that the configuration file that stores user settings is being overwritten, or the field that stores the zoom level is not being retained in the new version after an update.

These are also my first suspicions. Are any other settings in that file being over by an upgrade? If so, I think we can say that it is an update process problem (aka the file is getting overwritten), otherwise I think the GitHub Desktop is failing to read it in and then overwriting it later (probably when you adjust the zoom again).

**Comment by Yuudaari** [comment]
@outofambit I have an identical line for every version of github desktop I've ever installed, so I would guess it's the latter.

```json
{"per_host_zoom_levels":{"16424181881929237404":{
	"file:///C:/Users/Mackenzie/AppData/Local/GitHubDesktop/app-1.0.13/resources/app/index.html":1.2239010857415449,
	"file:///C:/Users/Mackenzie/AppData/Local/GitHubDesktop/app-1.1.0/resources/app/index.html":1.2239010857415449,
	"file:///C:/Users/Mackenzie/AppData/Local/GitHubDesktop/app-1.1.1/resources/app/index.html":1.2239010857415449,
	"file:///C:/Users/Mackenzie/AppData/Local/GitHubDesktop/app-1.2.0/resources/app/index.html":1.2239010857415449,
	"file:///C:/Users/Mackenzie/AppData/Local/GitHubDesktop/app-1.2.2/resources/app/index.html":1.2239010857415449,
	"file:///C:/Users/Mackenzie/AppData/Local/GitHubDesktop/app-1.2.3/resources/app/index.html":1.2239010857415449,
	"file:///C:/Users/Mackenzie/AppData/Local/GitHubDesktop/app-1.2.6/resources/app/index.html":1.2239010857415449,
	"file:///C:/Users/Mackenzie/AppData/Local/GitHubDesktop/app-1.3.0/resources/app/index.html":1.2239010857415449,
	"file:///C:/Users/Mackenzie/AppData/Local/GitHubDesktop/app-1.3.1/resources/app/index.html":1.2239010857415449,
	"file:///C:/Users/Mackenzie/AppData/Local/GitHubDesktop/app-1.3.2/resources/app/index.html":1.2239010857415449,
	"file:///C:/Users/Mackenzie/AppData/Local/GitHubDesktop/app-1.3.3/resources/app/index.html":1.2239010857415449,
	"file:///C:/Users/Mackenzie/AppData/Local/GitHubDesktop/app-1.3.4/resources/app/index.html":1.2239010857415449
}}}
```

**Comment by aryyya** [comment]
I'm trying to trace the location where `desktop` interacts with the `%AppData%\...\Preferences` file, but I cannot. Searching for the string "per_host_zoom_levels" results in a line from `electron` in `electron\brightray\browser\zoom_level_delegate.cc`.

I had a hunch that the package `electron-window-state` is where the interaction happens, but that package appears to concern the `window-state.json` instead.

**Comment by Yuudaari** [comment]
Actually, the entire Preferences file is part of chromium, you can find it in your chrome user data folders, with the same data that github desktop has

**Comment by Yuudaari** [comment]
I assume this is actually managed by the chromium core and isn't even touched at all by Github Desktop. The fix that I expect is needed is changing the name that it recognises Github Desktop by, so that it doesn't use the path to the executable for the host name in "per_host_zoom_levels". I would have no idea where this name would be provided, but theoretically if you were able to change it from the executable path to "Github Desktop", future versions would all reference the same property of the "per_host_zoom_levels"

**Comment by Yuudaari** [comment]
I would be interested to know what the Preferences file looks like on other operating systems. There could be a clue as to where the name is provided there, if it exists.

**Comment by Shakil-Shahadat** [comment]
Please fix this.

**Comment by pfthroaway** [comment]
I'm still having this issue as of release 2.4.3 on Windows 10 1909 Pro x64. Every time the application updates, I lose my zoom level. I can't read the tiny default font on my 1080p monitor. Please fix this issue.
