### ISSUE TITLE
Open in Desktop launches GitHub Desktop but doesn't start clone process

### ISSUE THREAD

**Issue by ericmschmidt** [desktop/desktop#5324]
Using Firefox, I've tried multiple times to use the "Open in Desktop" option when trying to clone a repository. At first, GitHub Desktop wasn't an option to download. After adding it to the list of options to open the link with, GitHub Desktop opens but it doesn't start prompting to complete the clone process. I've tried uninstalling and removing the GitHub Desktop user preferences that I could find, as well as trying from other browsers but I still experience the same behavior.

**Comment by oktonion** [comment]
Same issue. 
In any repo:
Clone or download -> Open In Desktop -> *GitHub Desktop shows* -> nothing happens

OS: Windows 7
GitHub Desktop 1.3.2
Browser: Mozilla Firefox 61.0.1 (if it matters)

Developer console and production log is clear about anything related to cloning new repo. Looks like ordinary launch of application.

**Comment by shiftkey** [comment]
@ericmschmidt @oktonion I went through the steps to reproduce this and I got stuck at this point:

<img width="385" src="https://user-images.githubusercontent.com/359239/43909959-ec705514-9bd1-11e8-9582-e33e1265637b.png">

Can you clarify how you've setup Firefox to launch Desktop - which program you've chosen in particular - as this will ensure I'm testing the right reproduction steps.

**Comment by oktonion** [comment]
![ghbug](https://user-images.githubusercontent.com/27406278/43915525-a8f25bec-9c13-11e8-8805-6b424bc0f278.jpg)

**Comment by shiftkey** [comment]
So I've traced the difference here to how the arguments are passed to Desktop.

In Chrome, these are the arguments that are received:

```
info: [main] Received possible protocol arguments: ["C:\\Users\\shiftkey\\src\\desktop\\dist\\GitHubDesktop-dev-win32-x64\\GitHubDesktop-dev.exe","--protocol-launcher","--","x-github-client://openRepo/https://github.com/desktop/dugite"]
```

This is what Firefox sends to Desktop:

```
info: [main] Received possible protocol arguments: ["C:\\Users\\shiftkey\\src\\desktop\\dist\\GitHubDesktop-dev-win32-x64\\GitHubDesktop-dev.exe","x-github-client://openRepo/https://github.com/desktop/dugite"]
```

I believe this is related to this change we introduced several months ago, as mitigation for the reported security vulnerability around protocol handlers: https://electronjs.org/blog/protocol-handler-fix

https://github.com/desktop/desktop/blob/7e9f40403be55d89b18a430f5bd3407eeafc8b54/app/src/main-process/main.ts#L139-L151

You'll also note further down that we defensively set these arguments as part of the registration of the protocol handler:

https://github.com/desktop/desktop/blob/7e9f40403be55d89b18a430f5bd3407eeafc8b54/app/src/main-process/main.ts#L163-L167

I'm really not sure why Firefox is omitting these arguments, and I'm not keen to roll those back (the `--` is especially important here because it's signals to the program being launched the separation between trusted and untrusted input.

**Comment by shiftkey** [comment]
I'm on the fence about marking this as a bug, because the app is setup to expect a certain format for the arguments (for defensive reasons) and I'm not sure how to teach Firefox to do that.

**Comment by oktonion** [comment]
I made a [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1482225) to Mozilla. Hope they can clarify the situation.

**Comment by billygriffin** [comment]
What do we think about closing this as an OS-browser combination that we can't really control?

**Comment by shiftkey** [comment]
Currently I can't even follow along with the bug report:

<img width="433" src="https://user-images.githubusercontent.com/359239/43968623-192cf18a-9c9e-11e8-9509-a97b2f42abce.png">

@oktonion please report back if you hear anything about the issue that Desktop can do to make this experience better. As @billygriffin, we don't have much control over how to configure Firefox to send the arguments in the appropriate order, which was done for defensive reasons, so we'll close this out for the moment until we hear back from Mozilla.

**Comment by oktonion** [comment]
@shiftkey It's the closed one because of security reasons. I will update this issue with info from mozilla team.

**Comment by oktonion** [comment]
So the mozilla team suggest that:

> there's no way for users to specify additional parameters to pass to the app handling the protocol when adding it manually

> For custom protocol handler applications added manually, the only interface we support consists in passing the URI as the only argument on the command line. This means the GitHub Desktop executable is not compatible with this interface anymore.

> In general, we're also moving towards dropping support for custom applications and only supporting system default applications. This is far away in the future, but I don't see us adding more features in this area. The workaround here if nothing else works may be to create a ".bat" file that wraps the GitHub Desktop executable and adds the other arguments.

> The best thing in this specific case, though, is to reinstall GitHub Desktop and ensure it is registered as the default application in the system and selected in Firefox. In the Firefox options, under "General > Applications", the default application should say "(default)" in parentheses after the application name. This works for me on Windows 10 with the latest version of GitHub Desktop.

**Comment by shiftkey** [comment]
> The best thing in this specific case, though, is to reinstall GitHub Desktop and ensure it is registered as the default application in the system and selected in Firefox. In the Firefox options, under "General > Applications", the default application should say "(default)" in parentheses after the application name. **This works for me on Windows 10 with the latest version of GitHub Desktop.**

Are you able to try reinstalling Desktop so that Firefox does detect it as the default? I'm not sure what else we can do here.

**Comment by oktonion** [comment]
Considering this I can not quite understand how to remove all registered GitHubDesktops as x-github-client handlers (I have two actually now) and reset it to default.
Also does GihubDesktop itself registering as handler of this protocol or not after install?

**Comment by oktonion** [comment]
This have not work however event when 'use GithubDesktop.exe (default)' option was set so the uninstalling part is necessary to make it work again.

**Comment by aminya** [comment]
I have the same problem. How did this get solved?

**Comment by oktonion** [comment]
> I have the same problem. How did this get solved?

https://github.com/desktop/desktop/issues/5792#issuecomment-427744894

**Comment by aminya** [comment]
If it is not solved why the issues are closed?!

**Comment by oktonion** [comment]
> If it is not solved why the issues are closed?!

It's external bug. Nothing can be done there.
