### ISSUE TITLE
Pre-commit hook failure output should use a fixed-width font

### ISSUE THREAD

**Issue by baddox** [desktop/desktop#5325]
**Please describe the problem you think should be solved**
I use git pre-commit hooks to run linters on my code. Any errors in the pre-commit hook will block the commit, and GitHub Desktop will show the shell output in a popup window. That output would be a lot easier to read if GitHub Desktop displayed it using a fixed-width font, because many linters use whitespace to align parts of the output for human readability.

**Comment by shiftkey** [comment]
@baddox can you add a screenshot of the example pre-commit hook error, for reference?

**Comment by baddox** [comment]
An example of Jest test failure output in GitHub Desktop:

![github desktop 2018-08-02 13-58-43](https://user-images.githubusercontent.com/307393/43610885-50a6c426-965c-11e8-8199-d1809be56f9c.png)

The same example in my terminal:

![1 shaddox thomass-macbook-pro work web zsh 2018-08-02 13-59-10](https://user-images.githubusercontent.com/307393/43610891-5631d20a-965c-11e8-9f0b-3f364d60418e.png)

Of course, full terminal features (like colors) would be nice too, but I suspect that using a fixed-width font would be much simpler and would go a long way to making the output easier to read.

**Comment by shiftkey** [comment]
Closing this out in favour of #6403 where we're digging into the changes required to support it
