### ISSUE TITLE
`unable to update local ref` error on first Pull for every repo

### ISSUE THREAD

**Issue by photonstorm** [desktop/desktop#5328]
## Description

When I open GitHub Desktop I start by pulling down several repos (all hosted on GitHub). Since update 1.3.2 I now consistently get an error window pop-up with the following content (obviously the repo and delta count varies each time, but the end result is always the same)

```
remote: Counting objects: 117, done.        
remote: Compressing objects:   3% (1/26)           
[snipped for brevity]
remote: Compressing objects: 100% (26/26), done.        
Receiving objects:   0% (1/117)   
Receiving objects:   1% (2/117)   
Receiving objects:  45% (53/117)   
remote: Total 117 (delta 98), reused 110 (delta 91), pack-reused 0        
Receiving objects:  46% (54/117)   
[snipped for brevity]
Receiving objects: 100% (117/117), 22.94 KiB | 7.65 MiB/s, done.
Resolving deltas:   0% (0/98)   
[snipped for brevity]
Resolving deltas:  94% (93/98)   
Resolving deltas: 100% (98/98), completed with 30 local objects.
error: cannot lock ref 'refs/remotes/origin/master': is at fc0dc1393039da99c24b165a868444429a591cf6 but expected 0967bfcab4d5f8671783696c67065431fb5d35ba
From https://github.com/photonstorm/phaser
 ! 0967bfcab..fc0dc1393  master     -> origin/master  (unable to update local ref)
```

This only happens once, the first time I try to pull. If I dismiss the error, then click Pull again, it works.

## Version

* GitHub Desktop: 1.3.2
* Operating system: Windows 10

## Steps to Reproduce

Launch GitHub Desktop. Click 'Pull' on any repo.

### Expected Behavior

For it to pull down without an error window.

### Actual Behavior

See above.

## Additional Information

It's not too much of a problem because I can just click Pull a second time and it'll work fine. It happens whenever I launch GitHub Desktop. So if I close it down, make a commit from the command line, open Desktop and try to pull, the first one will error.

It has only started happening with 1.3.2 or the previous version, but definitely not before.

**Comment by natros** [comment]
same problem here with macos
$ git --version
git version 2.18.0

**Comment by bschaeublin** [comment]
Same Problem on Windows 10, with Github Desktop version 1.3.2. It's irritating and suggests that something is wrong with the repository.

**Comment by shiftkey** [comment]
I'm going to mark this as resolved for 1.3.3 and add it to the QA process to confirm for when we publish the beta on Monday.

**Comment by JustinK1973** [comment]
Hi, I still get this issue with 1.3.3 update about 50% of the time.

**Comment by mattacosta** [comment]
I saw this error again too. Only once though, and it was after pulling from a non-github repo.

**Comment by shiftkey** [comment]
Reopening this because I believe that #6141 is the proper solution

**Comment by Rohit221990** [comment]
There is only one solution for this issue.

Go to .git directory of your solution and follow below steps:

1. .git/FETCH_HEAD  :- find out you branch and replace the latest ref id of your branch.

**Comment by sanjaygupta1011** [comment]
You need to update the reference using following Git command on Git bash:
$ git update-ref -d refs/remotes/origin/[locked branch name]
then pull using $git pull

[locked branch name] is the name of the branch that the error is happening because of mismatch of commit Ids.
