### ISSUE TITLE
Error while publishing branch 

### ISSUE THREAD

**Issue by kastouni** [desktop/desktop#5329]
Hi, 
When I run into publish branch , I receive the below error message :+1: 

fatal: unable to access 'https://github.com/kastouni/Git.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - La fonction de r�vocation n�a pas pu v�rifier la r�vocation du certificat.

Regards

**Comment by j-f1** [comment]
Does the information in [this known issue page](https://github.com/desktop/desktop/blob/master/docs/known-issues.md#certificate-revocation-check-fails---3326) help you?

**Comment by kastouni** [comment]
Yes , thanks

2018-08-03 11:05 GMT+01:00 Jed Fox <notifications@github.com>:

**Comment by shiftkey** [comment]
I'm going to close this out as it's a known issue with a workaround, and we're waiting on some upstream changes to Git before we can improve the in-app experience - please follow along with #3326.
