### ISSUE TITLE
incorrect commit files deleting from index

### ISSUE THREAD

**Issue by ixamilion** [desktop/desktop#5334]
I tried to delete some files from index

I added <folder_with_files> to .gitignore
I use bash command "git rm --cached '<folder_with_files>' -r"
then I made a commit with GitHub Desctop but files still in index
In  GitHub Desctop history those files marked as changed

If I made a commit with bash command "git commit -m "delete_some_file"" it work correct
In  GitHub Desctop history those files marked as deleted

**Comment by shiftkey** [comment]
@ixamilion thanks for the report! We have an earlier report of this in #4133 so I'm going to close this out as a duplicate. We also have a fix for this under review at #4147 so please follow along with that.
