### ISSUE TITLE
Support custom actions (essentially command-line calls with placeholders)

### ISSUE THREAD

**Issue by zaus** [desktop/desktop#5336]
I've aliased several git commands I use often on the command line.  I also like git-flow.  Neither of which are easily possible (other than "Open in Command Prompt" which forces me out of the program).  I would like:

1. Menu support for my commands
2. Hotkey support for my commands

[Sourcetree has this feature](https://blog.sourcetreeapp.com/2012/02/08/custom-actions-more-power-to-you/) as a reference example.

This would also bring back/support #2487 and #5083, which would be great as I'd also like to add my own editor (i.e. 'quick edit' to just make a small tweak vs. open in my default editor).  I strongly disagree with [the objections in this comment](https://github.com/desktop/desktop/issues/2487#issuecomment-347375512) regarding user-customization -- it should not be hard to support a vast majority of use cases with a couple placeholders, and please don't decide my workflow or I'll be inclined to find a different product :)

**Comment by zaus** [comment]
And it would address #1644 so we can hotkey amended commits

**Comment by shiftkey** [comment]
@zaus thanks for the feedback! Before I revisit this discussion, I have some questions that will help me understand more about your setup:

> I've aliased several git commands I use often on the command line.

Can you share some examples of what these Git commands do? This will help me understand the workflows you've built up over time, and how these differ from what's currently supported in Desktop.

>   I'd also like to add my own editor (i.e. 'quick edit' to just make a small tweak vs. open in my default editor)

What are you making a "quick edit" to here?

> it should not be hard to support a vast majority of use cases with a couple placeholders

What placeholders do you imagine needing?

**Comment by niik** [comment]
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.

**Comment by zaus** [comment]
Apologies for not replying, went straight to my spam folder.  The following was written without an argumentative intent, so hopefully it comes across appropriately neutral.

1. I don't think knowing my particular git aliases matters; basically my aliases are either normal git commands with specific options, or combinations of git commands.  The point is that it would be a very convenient customization not specific to a particular workflow, but will accommodate anyone's workflow (even Gitflow) so you don't have to promote or guide users to one particular way to use git.  @shiftkey's 3rd point about broad community support (meaning, eventually you might fold in Editor A etc) is unaffected -- until you have a chance to support whatever enough users are asking for, those users can enjoy their feature.  And if their feature never makes it into Desktop -- then those users can still enjoy their feature.
2. Making a quick edit to a file.  My current choices are to use either: the editor you think I should (VS Code) or the editor my computer thinks I should (default program), but maybe sometimes I just want to open a `.cs` file in Notepad2 rather than wait for Visual Studio Professional to open.  Or hypothetically I have a really particular scenario where for this one kind of file I've made my own custom app to do something, and it would be subjectively important if I didn't have to take three clicks and a wrist shake to open it.  Or not-so-hypothetically my editor is never going to be [cross-platform or CLI compliant](https://github.com/desktop/desktop/issues/2487#issuecomment-323215832).
3. Since there's not really much to interact with other than files (in the Changes tab) or commits (in the History tab), I don't think you'd need more than one or two placeholders.  As I mentioned earlier, the placeholders [SourceTree provides](https://blog.sourcetreeapp.com/2012/02/08/custom-actions-more-power-to-you/) are either:
    * the path of the selected file(s)
    * the hash of the selected commit(s)
    
    Maybe another placeholder to prompt for user input (just a simple message box with textarea) would support adding one-off flags for scenario-specific uses of the command (like line numbers or whatever).

So a custom command setup would look like:

    | Label     | Hotkey         | Command                                           |
    +-----------+----------------+---------------------------------------------------+
    | My Editor | CTRL+E         | ../path/to/myeditor.exe {target} -whatever -flags | <-- where {target} is the selected files when in "changes" tab
    | Revert    | CTRL+R, CTRL+Z | git myaliasfordarkmagic {target} {userinput}      | <-- where {target} is the commit hash from the "history" tab and {userinput} lets me tack on whatever is appropriate when necessary
