### ISSUE TITLE
Support for .dds image file preview

### ISSUE THREAD

**Issue by stuffi3000** [desktop/desktop#5337]
Hello,
I'd like to suggest the addition of .dds image preview in Github Desktop.

To get a preview here:
![image](https://user-images.githubusercontent.com/11315157/43652446-88f71120-9745-11e8-9eed-c6249f4a589b.PNG)

**Comment by shiftkey** [comment]
@stuffi3000 what options are there currently for previewing these files? I'm not familiar with the format, and would like to understand whether there's a library or framework out there that lets us support embedding this with HTML/JS/CSS.

**Comment by stuffi3000** [comment]
@shiftkey 
Its a format used in the gaming industry for adding textures to 3d models for example but also just for images. 
This explains its benefits very well:
_The advantage of using DDS textures for your materials is that this file type makes it possible to reduce the amount of memory that textures use by reducing the quality a little. This is useful if you're trying to cram as many textures as possible into a limited amount of graphics card and system memory, and is especially suitable for organic/nature textures where precision isn't paramount.

As an example, a 16-bit 1024x1024 JPG image requires 2.4 MB of graphics card memory. The same image stored in DDS format using DXT1 compression would require only 630 KB. So you could use almost 4 x 1024x1024 DDS textures for the 'price' of 1 JPG, so to speak._ 


Nvidia created a small tool for .dds file viewing, it is available here, together with links to other tools around .dds which could be useful as a source of information: http://www.nvidia.de/object/windows_texture_viewer.html

I'm not sure if there currently is any html/js/css framework for previewing these files, as browsers usually don't support this file type

**Comment by shiftkey** [comment]
@stuffi3000 thanks for the extra details. 

> I'm not sure if there currently is any html/js/css framework for previewing these files, as browsers usually don't support this file type

Electron uses Chromium under the hood for rendering, so modern web technologies might be able to help here. I also stumbled upon https://github.com/Jam3/parse-dds which might help with parsing these files within an Electron app (it mentions WebGL support, which is supported across most browsers these days).

For the moment I'm going to mark this as `help wanted` as I'd love some help to help explore this further.

Here's what I'd like to seen happen:

 - someone provide a repository containing `.dds` files so we have sample images to work with
 - someone take [this demo script](https://github.com/Jam3/parse-dds/blob/master/demo/index.js) and get it working with the example images in the repository, so we can "view" these images with a browser.

**Comment by stuffi3000** [comment]
@shiftkey
Here's a repository I am working on. It's about a mod for the strategy game "Hearts Of Iron IV".
There are loads of .dds files in the subfolders of ./gfx.
Here's the link to it:
https://github.com/generalisofficial/the-information-age

**Comment by stuffi3000** [comment]
@shiftkey 
Any news on this?

**Comment by billygriffin** [comment]
@stuffi3000 Because yours is the only request we've ever received for this, we're unable to devote time from our internal team to support it. If there's interest from the community, @shiftkey laid out a proposed path (https://github.com/desktop/desktop/issues/5337#issuecomment-411052876) for what we need to see from someone in the community to move this forward, so until that happens (which should be reflected in this issue), there won't be any movement. If there's no further interest in the next several months, we'll likely close this to keep our backlog manageable. Thanks!

**Comment by theolaa** [comment]
I'd definitely also like this feature. There's a fairly large community of modders for Paradox Interactive games (which use a lot of dds and tga files) who use GitHub for version control, and dds support would definitely be a welcome feature, even if we haven't been particularly vocal.

**Comment by sumghai** [comment]
Hi @shiftkey and @billygriffin, at least one of my repositories make use of DDS image files, and I would definitely appreciate being able to preview them in GitHub Desktop:

https://github.com/sumghai/SDHI_ServiceModuleSystem

(the actual DDS files are scattered across several folders in the repo, due to special requirements for modding a particular game)

I'll try running the script mentioned in https://github.com/desktop/desktop/issues/5337#issuecomment-411052876 later tonight.

**Comment by mido1966** [comment]
Pls No Email mor pls Tank you



Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: Robin Chang <notifications@github.com>
Datum: 22.05.19 06:58 (GMT+01:00)
An: desktop/desktop <desktop@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [desktop/desktop] Support for .dds image file preview (#5337)


Hi @shiftkey<https://github.com/shiftkey> and @billygriffin<https://github.com/billygriffin>, at least one of my repositories make use of DDS image files, and I would definitely appreciate being able to preview them in GitHub Desktop:

https://github.com/sumghai/SDHI_ServiceModuleSystem

(the actual DDS files are scattered across several folders in the repo, due to special requirements for modding a particular game)

I'll try running the script mentioned in #5337 (comment)<https://github.com/desktop/desktop/issues/5337#issuecomment-411052876> later tonight.

**Comment by theolaa** [comment]
You need to unsubscribe from this thread if you don't want to get email notifications anymore.

**Comment by stuffi3000** [comment]
I've recently tested a .dds file preview mechanism I found in another Github repo, which made it possible to show .dds files in the browser. The only issue was that the files had to be a-power-of-two to work. I'll search the link and send it in here

**Comment by stuffi3000** [comment]
Here it is:
https://github.com/toji/texture-tester

**Comment by stuffi3000** [comment]
@sumghai 
Any luck running the script?

**Comment by stuffi3000** [comment]
Any news on this? :)

**Comment by generalisofficial** [comment]
It would be VERY useful for many communities

**Comment by DillanV** [comment]
Same. We need this!

**Comment by yooksi** [comment]
I support this request :+1:

**Comment by chardynamics** [comment]
Need it we must

**Comment by biel-correa** [comment]
Guys I found these packages that may help solving the problem
https://www.npmjs.com/package/parse-dds
https://threejs.org/docs/index.html?q=Texture#api/en/loaders/CompressedTextureLoader
What do you think?

**Comment by stuffi3000** [comment]
> Guys I found these packages that may help solving the problem https://www.npmjs.com/package/parse-dds https://threejs.org/docs/index.html?q=Texture#api/en/loaders/CompressedTextureLoader What do you think?

The "Parse DDS" you found was already mentionned in one of the first commentaries to this issue, your link just sends us to the NPM link, which explicitly refers back to the Github link.
The second link is however more interesting. But since I have no knowledge about how it could be implemented into Github Desktop, I can sadly take no further action.

**Comment by tombricks** [comment]
This would benefit many communities that use DDS graphics files to store images.

**Comment by a2937** [comment]
Omg I just realized this was written in ElectronJS probably and uses the parse library. https://github.com/Jam3/preview-dds

**Comment by a2937** [comment]
This feature would probably require changing the image element to a canvas one at the very least. And I don't exactly know how it determines if the binary file is an image. Grabbing the canvas element afterwards and drawing the image directly on it would then probably show the image. Though in every example I see the canvas from the GL context gets directly appended onto the page.

**Comment by mkafrin** [comment]
@shiftkey Would y'all be okay with me picking this up? I wrote up a codesandbox (loosely using the code you asked someone above to get working) to demonstrate rendering in the browser with canvas (webgl2) with multiple dds files of different types  (https://codesandbox.io/s/angry-rubin-zf4cpq).

The sandbox also has the `RENDER_TO_IMG_ELEMENT` variable at the top which shows off two ways we can display these images. The first is to render them natively with the canvas element (would require changing how desktop shows image previews/diffs), and the second is to use `toDataURL` to convert the canvas image into a data url of any supported type (such as png in this case) and use that instead.

**Comment by shiftkey** [comment]
@mkafrin I'm no longer an active contributor to the project so you'd have to defer to the current team members to gauge their interest here...

**Comment by mkafrin** [comment]
> @mkafrin I'm no longer an active contributor to the project so you'd have to defer to the current team members to gauge their interest here...

Ah gotcha, will do.

**Comment by mkafrin** [comment]
@tidy-dev @sergiou87 Apologies if there's a better way to do this, but y'all seem to be the current team members here from what I can tell. Any thoughts on my above comment https://github.com/desktop/desktop/issues/5337#issuecomment-1648038024?

**Comment by stuffi3000** [comment]
@mkafrin
Wow, I didn't expect this to ever see the light of day. Thank you so much for focusing on this!

**Comment by theolaa** [comment]
Yeah, I've been keeping my eye on this too. Glad to see some activity!

**Comment by sergiou87** [comment]
Hey @mkafrin !

No worries, I will take this to the team in our next meeting to discuss it if we have time 😄

I can't promise anything, though! We are a small team, and right now focusing on accessibility improvements 😅

**Comment by mkafrin** [comment]
Fully understand, appreciate it!

**Comment by sergiou87** [comment]
Hey @mkafrin ! We talked about this and we'll be happy to see your PR. However, I want to warn you we're a small team so we can't say when exactly we'll be able to review it 😓 

In any case, thank you very much!!

**Comment by mkafrin** [comment]
Hey @sergiou87, no rush (as you discussed about y'alls limited resources), but just wanted to make sure you were aware a PR for this is up! Thanks again to the team for allowing me to tackle it.

**Comment by sergiou87** [comment]
Yes! We haven't had time to review it yet, but we're aware of it, thank you!

**Comment by 0xdevalias** [comment]
See also:

- https://github.com/desktop/desktop/issues/2981
  - https://github.com/desktop/desktop/pull/17686
- https://github.com/desktop/desktop/issues/6535

**Comment by ones-app** [comment]
It's weird, but in my case DDS files still don't show up. Can anyone confirm if this is still supported?
<img width="1734" height="955" alt="Image" src="https://github.com/user-attachments/assets/1b09fdb5-35a4-4a5d-bd44-4cf0b47f008b" />

**Comment by mkafrin** [comment]
@SaprIvan This is still only on the beta build to my knowledge. Try https://desktop.github.com/beta/
