### ISSUE TITLE
UX around Discard Changes is unclear

### ISSUE THREAD

**Issue by 5acres** [desktop/desktop#5342]
It is possible in 1.3.2 to Discard a single change (right-clicking on it), or "Discard All Changes...", but there is no way to discard only the changes that are selected (checkboxes).

The old version had this.  It is almost a necessary feature.  If you want to discard "all but one" from a long list, for example, you have to discard them one by one.

![screen shot 2018-08-04 at 12 06 50 pm](https://user-images.githubusercontent.com/40286055/43679699-f0b958ce-97de-11e8-9b1c-a64e6b08f568.png)

**Comment by MichaelHillcox** [comment]
Hi @5acres I'd say this is more of a usability issue if you want to call it an issue but what you've described is more than possible but you have to do it slighly differently.

Instead of using the checkboxes use ctr / command ( mac ) and click on the item's you'd like to discard. Once you have selected the ones you no longer want you can right click on any selected item and discard the changes. This will affect all highlighed items.

Hopefully it should look like this 
![](https://i.imgur.com/BSzGFok.png)

**Comment by 5acres** [comment]
Interesting, so there are two competing selection models.  How would one know about the Cmd-click selection model, and why not just use the check boxes, which are already a form of selection?  That's what the previous Mac desktop client did.

It's worth noting that all of these are hidden under right-click and command key modifiers, so they are not "discoverable" in the general sense of the word.

But ... thanks for the workaround!

**Comment by MichaelHillcox** [comment]
So, I understand your confusion but I'd also have to argue that Cmd+click is pretty native when being given a list of items like you are presented with within the client. 

The confusing part is when you don't know that the checkboxes are for staging and unstanging changes and nothing to do with the actual act of selecting an item to perform an action.

**Comment by 5acres** [comment]
It's bad design.  Conflicting selection paradigms.

You say the checkboxes are "for staging and upstaging changes" and "nothing to do with selecting an item to perform an action..." and yet they select items to perform the Commit action.

Obviously the checkboxes are selection.  Just like Gmail, as an example.  That you decided you needed a second, different selection paradigm for a different set of operations makes no sense.

I've been building software for 30 years and I can't think of another example of two orthogonal selection paradigms for different sets of operations, with the possible exception of the marquee selection vs. masks in Photoshop, but that's pretty esoteric.  Can you think of another example where that's been done, or is actually necessary?

Anyway, thanks for responding quickly.

**Comment by MichaelHillcox** [comment]
Unfortuantly I havent put any time into this application myself but there are many put falls, I might suggest using gitKracken for a much nicer interface but unfortuantly I think you'll find yourself in the same situation with the selection issue. ( To be clear, I completely agree its not great. )

I think it's the best way of doing so far unless someone much better at UX comes along and figures something out. VS code kind of has the same issue, To perform an action on it you have to either use the things that show up at the side or use Ctr + Click to select multiple then rightclick. It's more of a flaw of having it all in the same list. I'm pretty sure google find themselves falling into this issue all the time, google drive in the browser comes to mind.

If you think you can offer a better solution then I urge you to submit PR / Issue with a proposal for a better system. 

Either way, Hope this is the only issue you find.

**Comment by shiftkey** [comment]
@5acres @MichaelHillcox thanks for the feedback on this area of the app.

I'll confirm the two different flows here to ensure we're talking about the right thing:

 - the checkbox state indicates which items are to be included in the commit - I don't believe this affects the context menu items
 - selecting rows (using <kbd>Shift</kbd> to select a range of files, or <kbd>Ctrl</kbd>/<kbd>Cmd</kbd> to select single rows) is used to apply context menu actions to multiple items.

> The old version had this.

Can you clarify which version you are referring to here? I pulled down the old macOS app to compare and it:

 - had no ability to select multiple rows in the list
 - "Discard Changes" only applied to the selected row, even when all entries were checked

> If you want to discard "all but one" from a long list, for example, you have to discard them one by one.

#4509 added support to do "Select All" when the changes list has focus, and you can then unselect the row(s) you want to include before right-clicking to discard changes. That's the quickest way I can think of to achieve that today.
 
Happy to discuss this further if there's ways to improve this flow, but using the checkboxes to represent the _commit_ state is still something I consider to be very important to Desktop.

**Comment by MichaelHillcox** [comment]
Hi @shiftkey 

From what I could understand and what I have found to be the case myself, it would appear that @5acres is having and issue dealing with the two different ways of selecting files: 

- Check boxes for staging
- And actual item selection.

It adds this layer of complexity to the application some users may find hard to deal with if they haven't been presented with this kind of UX before. I'd some to provide the magic solution but everything I can think of would add more complexity than is already present.

**Comment by 5acres** [comment]
In version "Tasty Things Done Tastily (224)", which is the last update of the "old" version (I still have it on my machine during the transition)....

It's in the Repository Menu, rather than under right-click.  The menu item is "Discard Changes to Selected Files..." and it works exactly like that, and uses the checkboxes for selection.

It's hard to make the argument for the current implementation as the only one possible, when the previous version of your own app did exactly what I describe (and was intuitive and worked fine).

![screen shot 2018-08-08 at 12 45 26 pm](https://user-images.githubusercontent.com/40286055/43860567-f617b6e4-9b08-11e8-97cf-fa0bcaa134b8.png)

![screen shot 2018-08-08 at 12 41 48 pm](https://user-images.githubusercontent.com/40286055/43860573-fafb8ae6-9b08-11e8-89bd-9236692dc502.png)

**Comment by billygriffin** [comment]
@5acres Thanks for the detailed screenshots and description. I think going back to the previous implementation would also be confusing because it would be unclear to people whether "Discard Changes to Selected Files" meant the file you have highlighted (third file down) or the two files with the checkboxes checked. The difference between the active state and the checkboxes exists either way. I think this is something we'll explore further in our usability testing to find out if it's unintuitive for others as well, and thanks for pointing it out.

**Comment by steveward** [comment]
Feedback from @graemeworthy in https://github.com/desktop/desktop/issues/5690:

> This has happened a few times, and the dialog doesn't seem to stop it from happening.
> 
> It seems like the context dropdown is the wrong place for this item.
> 
> Right clicking a file is for actions related to that file
> Lets look at the rest of the items in that list 
> 
> |Action| Context|
> |---|----|
> |Discard Changes...| This file... destructive|
> |Discard All Changes...| All Files... destructive|
> |Ignore File| This file|
> |Ignore All .js files | Project wide, using this file as an example|
> |Reveal in finder | This file|
> |Open in Atom| This file|
> |Open with Default Program| This File|
> 
> 
>

**Comment by wduquette** [comment]
Got to say, I selected Discard All Changes by accident this morning and lost the morning's work.  The dialog is no help at all; visually, if you're working quickly, it looks pretty much the same as the Discard Changes dialog.  It was a bonehead thing to do.  I'd move Discard All Changes somewhere else (I want to have it available, but not where it is).

**Comment by billygriffin** [comment]
Thanks folks for weighing in on this. We discussed it internally, and based on the feedback we've seen from users, we're inclined to agree that the conflation of "Discard one" and "Discard all" is confusing and makes for a pretty dangerous situation, as @wduquette described above (thanks for explaining how it happened!).

This came about from this issue (https://github.com/desktop/desktop/issues/4197), and we didn't fully appreciate how it might fall down as a result while improving discoverability. Our biggest question now is whether just removing "Discard all files" from the context menu will just reintroduce the discoverability problem for people who want to discard everything, or if multi-select for files will solve the problem (along with the relatively undiscoverable existing context menu item for "Discard all changes" from the header area).

@desktop/design When you have a chance, would you mind weighing in on this given that there is a previous issue around discoverability?

**Comment by wduquette** [comment]
"the relatively undiscoverable existing context menu item for "Discard all changes" from the header area": I certainly didn't know that that was there, and it wouldn't have occurred to me to look for such a thing there.  Now that I know it's there, I like it; that's the right place for it, much better than on the context menu for a single file.

Maybe add a "cog" icon to the header, as an indicator that there's a menu?  Or a downward pointing triangle icon?  You don't need that on the files, because they are items in a list; context menus are expected.  But the header isn't an item in the list, and needs a little extra help.

**Comment by billygriffin** [comment]
Thanks @ampinsk! 

I'm going to go ahead and add `help wanted` here since it's clear what the initial three steps are, but please let us know if you have questions. Agreed that we hold off on (4) unless it becomes more clearly needed, and I think with the first three we can close this issue.

Please let us know if you're interested in picking this one up!

**Comment by shiftkey** [comment]
@bamwu opened #7356 to propose removing this menu item, which is what we settled based on the recent comments in this discussion.

**Comment by shiftkey** [comment]
This issue has sat for a while without being acted upon, and I believe it's down to the discoverability of the task list. I've extracted this out to #7394, and to prevent further confusion now we know what changes we want to make I'm going to close this out.

**Comment by billygriffin** [comment]
Hi folks! @ampinsk's proposed changes 1-3 have now been merged and shipped to beta in https://github.com/desktop/desktop/pull/7415 (thanks @ahuth!), and should go out to production in one of the next two releases. Really appreciate the feedback here, and we'll continue to look at ways to improve it.
