### ISSUE TITLE
keyboard navigation and enter will execute menu item twice

### ISSUE THREAD

**Issue by UgurAldanmaz** [desktop/desktop#5344]
## Description
When I use the keyboard to open menu and select 'Open in Git Bash', two instances of Git Bash is opened.

## Version

* GitHub Desktop:
1.3.2

* Operating system:
Microsoft Windows [Version 10.0.17134.167]

## Steps to Reproduce
1. Press `Alt`
2. Press `R`
2.1. Opens the Repository menu
3. Use arrow down to select 'Open in Git Bash'
4. Press `Enter`

### Expected Behavior
One Git Bash instance should be opened.

### Actual Behavior
Two instances of Git Bash is opened.

## Additional Information

I've added notes to the following screenshot gif files.

Here is the reproduce gif.

![spawn-issue](https://user-images.githubusercontent.com/5686267/43690174-3c00e7a4-990e-11e8-8ca8-5afc6f5b783c.gif)

Here is the expected behavior when I use the mouse.

![spawn-issue-mouse](https://user-images.githubusercontent.com/5686267/43690175-4b2ba688-990e-11e8-97e7-82a674ec138c.gif)

**Comment by steveward** [comment]
Thanks for the report @UgurAldanmaz. I was able to reproduce this issue on my machine, so I'm going to label this as a bug for the team to look into.

**Comment by UgurAldanmaz** [comment]
Thanks for the answer @steveward. I took a look at the source code and I think that I can fix this bug.

If there is no hurry, I would like to work on it.

**Comment by steveward** [comment]
@UgurAldanmaz that would be ✨!

**Comment by shiftkey** [comment]
@steveward @UgurAldanmaz what version of Git for Windows do you have installed?

**Comment by steveward** [comment]
@shiftkey I'm on v2.18.

**Comment by UgurAldanmaz** [comment]
@shiftkey 2.18.0.windows.1

**Comment by shiftkey** [comment]
Weird - I haven't been able to reproduce this myself on a Windows `10.0.17134.191` VM with the same version of Git and `1.3.2`.

Anyway, let me know if I'm missing something with the repro steps or if I can help with the shell internals in Desktop.

**Comment by shiftkey** [comment]
> I have to use the keyboard shortcuts to get it to happen, using a mouse will not trigger the bug.

Oh, this is a very interesting clue - thanks @dlloyd123!  I stumbled upon something similar over here where the behaviour differed between keyboard and mouse: #5368

**Comment by dlloyd123** [comment]
I've been investigating the bug locally for an hour or so, and yes its firing the 'enter' key press, then firing it again. I was wondering if it was an async/promise thing, but i think thats probably incorrect. Its hitting this twice in app-menu.tsx (onItemClicked): this.props.dispatcher.executeMenuItem(item) - i think using a similar fix as mentioned in #5368 would probably suffice in this method. It would be interesting to understand why its doing it twice though - just in case suppressing it is merely hiding something deeper.

**Comment by dlloyd123** [comment]
Looks like in executeDispatchesInOrder in react-dom.development.js it's looping over some dispatch listeners and it executes the first listener and does the first 'click' and it checks if  event.isPropagationStopped()) if it is it breaks out of the loop - in this case it does another loop and hits the 'click' again. Do we have a rogue extra 'listener' hanging around somewhere which shouldn't be listening?

**Comment by dlloyd123** [comment]
Yea ha i was just going to comment i found that i can fix it in either list-row.tsx or focus-container.tsx by using a similar fix in onKeyDown. Nice find.

**Comment by shiftkey** [comment]
I've bumped this up to `priority-2` because you can trigger this with any sort of keyboard navigation that triggers an event (Open on GitHub, Toggle Fullscreen, etc) and I keep encountering it as someone who likes keyboard navigation.
