### ISSUE TITLE
Desktop client opens when using Git from PHPStorm

### ISSUE THREAD

**Issue by KrissKulins** [desktop/desktop#5345]
## Description

I'm using PHPStorm V2018.2, and have installed Github Desktop client. Had this combo for quite a while, but recently, when updating to a newer version of Github Desktop, every time I pull or push or even just fetch from within PHPStorm, the application just pops up even though it isn't open. 

In PHPStorm I've set my git executable path to the following:
C:\Users\[username]\AppData\Local\GitHub\PortableGit_69bd5e6f85e4842f07db71c9618a621154c52254\cmd\git.exe

## Version

* GitHub Desktop:
1.3.2

* Operating system:
Windows 10

## Steps to Reproduce

1. Install php storm
2. set it's git executable path to:
C:\Users\[username]\AppData\Local\GitHub\PortableGit_69bd5e6f85e4842f07db71c9618a621154c52254\cmd\git.exe
3. Pull from any branch.

### Expected Behavior

Pulls from that branch.
### Actual Behavior

Pulls from that branch and opens Github Desktop application.

## Additional Information

https://www.dropbox.com/s/81gkcr9ilzguoqx/github.gif?dl=0

### Logs

Couldn't find them, sorry.

**Comment by KrissKulins** [comment]
@steveward thank you for your response.
Will installing git not cause problems with the Git Shell CLI? Because that's what I'm using primarily, because of it's added SSH functionality over the normal Powershell.

**Comment by steveward** [comment]
@KrissKulins Installing Git for Windows will not interfere with the Git Shell -- I have both installed on my Windows 10 machine.

If you want to eventually move off of using the Git Shell to using Git Bash or Git in PowerShell you will need to configure your SSH key manually. We have a [guide](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/) for how to do that -- let me know if you have any questions.

If you want to get PowerShell to look like the Git Shell had you can download [posh-Git](https://github.com/dahlbyk/posh-git) to add in the Git status information. Hope that helps!

**Comment by KrissKulins** [comment]
@steveward thank you for your help. Just installed Git for Storm only, popup went away.
Gonna close this then.

**Comment by steveward** [comment]
@KrissKulins glad to hear that got things working!
