### ISSUE TITLE
"No suitable editors installed for Github Desktop to launch."

### ISSUE THREAD

**Issue by EmiLithium** [desktop/desktop#5349]
## Description

I have seen this issue on the forums in closed threads, and someone in one of those threads said to open a new issue if the thread closed due to inactivity. Since they seemed unsolved and the threads were closed, I have decided to open a new thread.

Issue: When trying to open a repository in Atom through GitHub Desktop, this error message pops up, "No suitable editors installed for Github Desktop to launch. Install Atom for your platform and restart GitHub Desktop to try again." I have located Atom in `C:\Users\[name]\AppData\Local\atom` and tried re-installing it, and I have restarted GitHub Desktop since installing Atom, but GitHub Desktop still won't recognize that I already have Atom installed.

## Version

* GitHub Desktop: 1.3.2 for Windows 64 bit

* Operating system: Microsoft Windows [Version 10.0.14393]
* Atom: 1.29.0 for Windows 64 bit

## Steps to Reproduce

1. Install and open GitHub Desktop.
1. Install and open Atom.
1. Close Atom.
1. Restart GitHub Desktop.
1. Open the Repository dropdown menu in GitHub Desktop.
1. Click "Open in external editor."
1. Result in error "No suitable editors installed for Github Desktop to launch. Install Atom for your platform and restart GitHub Desktop to try again."

### Expected Behavior

Repository should open in Atom, which is already installed.

### Actual Behavior

Atom does not launch. GitHub Desktop seems unable to locate Atom on my machine, even though Atom is in `C:\Users\[name]\AppData\Local\atom`.

## Additional Information

![unabletoopenatom](https://user-images.githubusercontent.com/41804177/43780405-86db6220-9a28-11e8-9393-4f4669910740.PNG)

### Logs

[2018-08-07.desktop.production.log](https://github.com/desktop/desktop/files/2266603/2018-08-07.desktop.production.log)
[2018-08-03.desktop.production.log](https://github.com/desktop/desktop/files/2266617/2018-08-03.desktop.production.log)

**Comment by shiftkey** [comment]
@EmiLithium thanks for the report!

 It looks like Atom hasn't installed the `%LOCALAPPDATA%\Atom\bin\atom.cmd` shortcut that Desktop needs to be able to launch it correctly. Are you able to open CMD and run these commands to force it to create those?

```
> cd %LOCALAPPDATA%\Atom\
> atom --squirrel-updated
```

This should restore your `bin` shortcuts and Desktop should then be able to launch Atom fine.

**Comment by EmiLithium** [comment]
Thanks! The `bin` folder is there now and opening Atom from GitHub works now. Glad it was such a simple fix, thanks very much @shiftkey for catching that.

**Comment by coyotepod** [comment]
I had a similar issue. On Win 10, used Powershell with the above commands in the "\AppData\Local\atom\" folder. Powershell did tell me to use ".\atom" rather "atom" to allow commands to run in that folder. Thanks for the solution :-)

**Comment by vaishali-tanwar** [comment]
I had the similar issue with Atom and it is working now in GitHub Desktop with the help of above mentioned commands. Thanks for the solution . :)

**Comment by xfqwdsj** [comment]
> @EmiLithium thanks for the report!
> 
> It looks like Atom hasn't installed the `%LOCALAPPDATA%\Atom\bin\atom.cmd` shortcut that Desktop needs to be able to launch it correctly. Are you able to open CMD and run these commands to force it to create those?
> 
> ```
> > cd %LOCALAPPDATA%\Atom\
> > atom --squirrel-updated
> ```
> 
> This should restore your `bin` shortcuts and Desktop should then be able to launch Atom fine.

![error](https://user-images.githubusercontent.com/37076189/75516446-79b7a100-5a37-11ea-89c8-12a9974611fa.png)
hello! what should i do?

**Comment by tierninho** [comment]
@xfqwdsj Please open a new issue. Thanks.

**Comment by xfqwdsj** [comment]
> @xfqwdsj Please open a new issue. Thanks.

OK! I report it in Atom

**Comment by hanna73** [comment]
> @EmiLithium thanks for the report!
> 
> It looks like Atom hasn't installed the `%LOCALAPPDATA%\Atom\bin\atom.cmd` shortcut that Desktop needs to be able to launch it correctly. Are you able to open CMD and run these commands to force it to create those?
> 
> ```
> > cd %LOCALAPPDATA%\Atom\
> > atom --squirrel-updated
> ```
> 
> This should restore your `bin` shortcuts and Desktop should then be able to launch Atom fine.

Thank you very much
