### ISSUE TITLE
Add a keyboard shortcut for switching repos or branches like command/ctrl+k in slack

### ISSUE THREAD

**Issue by bj97301** [desktop/desktop#5353]
**Please describe the problem you think should be solved**
Add a keyboard shortcut for switching between repos or branches.  

**Do you have any potential solutions in mind?**
I like slack's command/ctrl+k or vscode's command/ctrl+p:
![screen shot 2018-08-07 at tuesday august 7 2018 11 04 am](https://user-images.githubusercontent.com/1450431/43793916-b52c28b8-9a31-11e8-9019-7c39118bcc85.png)
![screen shot 2018-08-07 at tuesday august 7 2018 11 06 am](https://user-images.githubusercontent.com/1450431/43794007-f555dcb8-9a31-11e8-9830-b22db80918cf.png)

**Comment by j-f1** [comment]
We have Cmd/Ctrl+T and Cmd/Ctrl+B (IIRC) to activate the proper switcher already. If this isn’t what you were asking about, could you clarify please?

**Comment by bj97301** [comment]
Didnt know about cmd+t and cmd+b.  That totally works.  Where can I find docs on the keybindings?

**Comment by shiftkey** [comment]
@bj97301 we don't have docs for keybindings currently (probably on hold until we address #4796) but every menu item should also show a keyboard shortcuts where they are defined:

<img width="275"  src="https://user-images.githubusercontent.com/359239/43797980-866c449e-9a5f-11e8-8e4c-1301c0b5dc15.png">

**Comment by bj97301** [comment]
Oh I see.  Well thats pretty intuitive.  You win this time @shiftkey ;)

**Comment by bj97301** [comment]
Thanks again for the help and quick replys @j-f1 and @shiftkey
