### ISSUE TITLE
Tune out : Auto sync after commit 

### ISSUE THREAD

**Issue by anilshar** [desktop/desktop#5357]
There should be some config/setting to tune out this feature. It can be disastrous in some cases.

**Comment by shiftkey** [comment]
@anilshar which version of the app are you running? This hasn't been ported to the Electron version of Desktop (see #2191 for that request) and the classic Mac app (I believe the only place where this has been implemented) has this config setting to control the behaviour:

<img width="318" alt="screen shot 2018-08-08 at 2 26 58 pm" src="https://user-images.githubusercontent.com/359239/43853679-3657e2de-9b17-11e8-9bde-b4691eee7785.png">

**Comment by billygriffin** [comment]
Since this isn't the case in the current version of GitHub Desktop, I'm going to close this out. Thanks for the report, and glad the current version doesn't introduce this problem for you.
