### ISSUE TITLE
When comparing two branches, after about 20 seconds the view resets

### ISSUE THREAD

**Issue by BacchusPlateau** [desktop/desktop#5360]
## Description

When comparing two branches with numerous commits, every 20 seconds or so the view refreshes and you lose your place - the view resets to the topmost commit.   

## Version

* GitHub Desktop: 1.2.6

* Operating system: Windows 10

## Steps to Reproduce

1. Choose "Branch" and then "Compare to Branch" from main menu
2. Select Master and another branch with numerous commits ahead of Master
3. Select any merge on the left nav that is not the topmost merge
4. Select a commit on the second column of commits for the merge selected in 3
5. Study the delta on the rightmost column / pane 
6. After about 20 seconds, the entire view refreshes and you're looking at the topmost merge and topmost commit, losing your place reviewing the code.   UGH!

### Expected Behavior

Refreshing the view is find, but don't reset the selected merge and commit

### Logs

[2018-08-08.desktop.production.log](https://github.com/desktop/desktop/files/2271871/2018-08-08.desktop.production.log)

**Comment by shiftkey** [comment]
@BacchusPlateau thanks for this report!

I believe this has been fixed by #5062 which was published as part of `1.3.0`. Are you able to update Desktop and confirm this is still occurring?

**Comment by shiftkey** [comment]
@BacchusPlateau thanks for confirming this is no longer an issue!
