### ISSUE TITLE
show current branch of repo in the repos list

### ISSUE THREAD

**Issue by VitaliyKim** [desktop/desktop#5365]
Hello dears,

The feature would save some time to ones with multiple repos containing interconnected projects.

Thank you.

**Comment by billygriffin** [comment]
Hi @VitaliyKim, thanks for reaching out. What problem would be solved by showing the branch in addition to the repo name in the list? You know immediately what branch you're on when you switch to a given repo, and the decision of whether to switch to a repo isn't likely going to be made based on which branch you're on, right? It's possible I'm missing something here, so please let me know if so. Thanks!

**Comment by billygriffin** [comment]
Thanks again for leaving an issue.

We haven't gotten a response to our questions in our questions above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by mirai-zoom** [comment]
ビリー・グリフィン　さま
よろしく　おねがいします。
奥が深いですね（専門的）です
期待と不安？期待のほうが大きいいです。
よろしく　どうぞ

**Comment by VitaliyKim** [comment]
Hi @billygriffin,
Thank you and sorry for late reply.

As stated in first comment it would save time switching repos.

As an example: 
- We work on several projects that are communicating to each other and are placed in different repos. 
- Different branches contain different implementations/fixes.
- And while working on one (say first) of the projects we need to be sure that another (say second) interconnected project is currently switched to a branch with needed implementation.

Currently to ensure needed branch we have to switch to the second repo then switch back to the first one we work on.

Thank you :)

**Comment by billygriffin** [comment]
@VitaliyKim Thanks for the context! I’ve not heard that use case previously, so thanks for walking through how you’re using it. There have been several issues asking about things related to what additional context we show or don’t show in the repo list, so we’ll be evaluating all of those and figuring out what things are most critical. My gut right now is that the way you’re using it may be pretty rare, so I’m wondering if something like adding the branch to the tooltip for each repo would be helpful or something else that doesn’t clutter up the normal interface. Thoughts?

**Comment by ac05219** [comment]
@billygriffin 

> You know immediately what branch you're on when you switch to a given repo, and the decision of whether to switch to a repo isn't likely going to be made based on which branch you're on, right?

This is not true. I have several features branches that I and my team are working on. Since I am not single tasked, I have multiple branches and I choose which repo I am going to work on/review today by the branch. It's easier than constantly switching and having to download all the changed code every time I want to take a quick look at something.

**Comment by steveward** [comment]
Closing in favor of https://github.com/desktop/desktop/issues/8158 where we are collecting feedback about this.
