### ISSUE TITLE
Can't clone a repository "cygheap base mismatch detected".

### ISSUE THREAD

**Issue by mpp-oliverh** [desktop/desktop#5366]
## Description
I installed the latest Github Desktop for Windows and tried to clone a repository, the files are created but I get a whole page of error message and the repository doesn't appear in the UI.

I've uninstalled and rebooted but it didn't fix it.

I've seen the same problem reported before but the issue is marked closed and locked so I think it's come back.

## Version
* GitHub Desktop: 1.3.2
* Operating system: Microsoft Windows [Version 10.0.17134.165]

## Steps to Reproduce
1. install the Desktop client.
2. clone a repository

### Expected Behavior
The repository is cloned and appears in the UI.

### Actual Behavior
The files are downloaded to disk but the client UI is broken and I get an error message, shown below.

## Additional Information
Cloning into 'C:\Users\Oliver\Documents\GitHub\developer-guide'...
remote: Counting objects: 2528, done.        
..removed progress
Resolving deltas: 100% (1565/1565), done.
      2 [main] sh (16164) C:\Users\Oliver\AppData\Local\GitHubDesktop\app-1.3.2\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0xEE8410/0xDA8410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      1 [main] sh 17708 fork: child -1 - forked process 16164 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Oliver\AppData\Local\GitHubDesktop\app-1.3.2\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      2 [main] sh (19724) C:\Users\Oliver\AppData\Local\GitHubDesktop\app-1.3.2\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0xEE8410/0xDA8410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
1063993 [main] sh 17708 fork: child -1 - forked process 19724 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Oliver\AppData\Local\GitHubDesktop\app-1.3.2\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      3 [main] sh (15628) C:\Users\Oliver\AppData\Local\GitHubDesktop\app-1.3.2\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0xEE8410/0xF98410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
3119447 [main] sh 17708 fork: child -1 - forked process 15628 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Oliver\AppData\Local\GitHubDesktop\app-1.3.2\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      5 [main] sh (20996) C:\Users\Oliver\AppData\Local\GitHubDesktop\app-1.3.2\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0xEE8410/0xE88410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
7192140 [main] sh 17708 fork: child -1 - forked process 20996 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Oliver\AppData\Local\GitHubDesktop\app-1.3.2\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      4 [main] sh (9048) C:\Users\Oliver\AppData\Local\GitHubDesktop\app-1.3.2\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0xEE8410/0xF18410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
15253839 [main] sh 17708 fork: child -1 - forked process 9048 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Oliver\AppData\Local\GitHubDesktop\app-1.3.2\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: Resource temporarily unavailable

**Comment by shiftkey** [comment]
@mpp-oliverh thanks for the report. 

We had a report of this being introduced by Windows 10 Fall Edition introducing some new enhancements to the Windows [EMET](https://support.microsoft.com/en-ca/help/2458544/the-enhanced-mitigation-experience-toolkit) and in particular the option to "Force Randomization of Images (Mandatory ASLR)". More details about that can be found here: https://github.com/desktop/desktop/issues/3096#issuecomment-339402431

Can you confirm you also have this setting enabled?

**Comment by mpp-oliverh** [comment]
The mandatory ASLR is enabled yes. 
I fixed it with some god-awful powershell script to add a load of exceptions.

**Comment by shiftkey** [comment]
@mpp-oliverh I'm glad you were able to workaround it. For the moment we're stuck dealing with upstream limitations https://github.com/desktop/desktop/issues/3096#issuecomment-339498661, so I'm going to close this out because it's outside the control of Desktop to address.
