### ISSUE TITLE
Use checkboxes in Changes tab for "discard N selected changes"

### ISSUE THREAD

**Issue by mikew** [desktop/desktop#5369]
**Please describe the problem you think should be solved**
When selecting multiple files to discard it's impossible to see a preview of what you're selecting without losing said selection. I think this is a UX regression from older versions of the Desktop app.

**[Optional] Do you have any potential solutions in mind?**
There are already check boxes next to the files. I think this is what drove this feature in previous versions of the app. Now the feature is kind of hidden, less accessible (needs KB + M if you want to not select a file between two others), and as mentioned above just not as nice to use when you've got some files selected and want to preview another file to potentially add to the selection.

**Comment by shiftkey** [comment]
@mikew thanks for the feedback! 

We are already tracking this discussion in #5342, so please follow along with that.

**Comment by mikew** [comment]
Oh wow, must be that time of year, apologies!
