### ISSUE TITLE
Defaut Folder 

### ISSUE THREAD

**Issue by daniellealfreitas** [desktop/desktop#5377]
Hi. 

Its possible to change the defaut page where its saved my files on local ?

current the defaut folder its in /documents/github/  

i want to change to d:/wamp/www/foldername coz in that way i can see the changes on my localhost.

**Comment by j-f1** [comment]
If you change the folder the repository is cloned/created in, Desktop will remember that choice and provide it as the default the next time.

**Comment by shiftkey** [comment]
@daniellealfreitas seconding what @j-f1 said - any time you create or clone a repository the directory you choose will become the new default. 

Otherwise, if you want to add an existing repository to Desktop just drag-and-drop the folder into the app to work with it there.

**Comment by limeb** [comment]
I would prefer an actual setting for a default folder.
