### ISSUE TITLE
Allow for copying file path in file list views

### ISSUE THREAD

**Issue by sbonami** [desktop/desktop#5382]
**Please describe the problem you think should be solved**

As a user that bounces between the GUI and the terminal for various git operations, it would be helpful to copy the file path for files in both the "change" view and the commit history's file list.

**[Optional] Do you have any potential solutions in mind?**

I could see this taking shape in several ways:

1) Enable copy/paste support through keyboard shortcuts when a file is selected
2) Context-menu buttons for copying the file path of the focused file
3) Enable the copy/paste actions from the OS menu bar

The file path could be relative to the repository root or as an absolute path, however I'm not sure which use-case would be more preferred.

**Comment by shiftkey** [comment]
@sbonami thanks for the suggestion. We have #2944 open which is tracking the History view changes and adds some more context there, but I don't think we have an equivalent issue for the Changes tab which you also suggested.

**Comment by shiftkey** [comment]
@sbonami actually, I'm going to fold this into that issue because there's significant overlap and ensure it covers both Changes and History - please follow along with that discussion!

**Comment by sbonami** [comment]
Thanks for catching this; apologies for not doing a thorough-enough search!
