### ISSUE TITLE
Feature Request: Repo Nickname

### ISSUE THREAD

**Issue by AdrianB93** [desktop/desktop#5383]
**Feature Request:**

I would like to rename/nickname my repos in GitHub Desktop.

**My Problem:**

In self-hosted Bitbucket, we have our repositories as `[project]/[repo]`. Each project has similarly names repos, for example:

* `product-a/webapp`
* `product-b/webapp`
* etc.

In Github Desktop, they all appear with the name "webapp". I have no idea which repo belongs to which project. I need to be able to tell tham apart.

**Comment by say25** [comment]
Something like this could solve the problem of multiple checkouts of repos as well

**Comment by steveward** [comment]
Thanks for opening this @AdrianB93! I'm going to close this issue out as a duplicate of https://github.com/desktop/desktop/issues/1929. Please follow along in that issue for updates about this feature.
