### ISSUE TITLE
Not able to push any files to github due to "Chain.pem': No such process"

### ISSUE THREAD

**Issue by dinocherian** [desktop/desktop#5385]
**Please describe the problem you think should be solved**
When I push some files using GitHub Desktop App, I am getting below error
fatal: unable to access 'https://github.com/PQR/ABC.git/': schannel: failed to open CA file 'C:/Users/XYZ/AppData/Local/GitHubDesktop/app-**1.3.2**/resources/app/git/mingw64/C/Users/XYZ/EMCSSLCA-Chain.pem': No such process

This is happening in latest Desktop App version 1.3.2 

I was using version 1.0.9
Please resolve this ASAP or tell me how to stop auto-update

Thanks,
Dino

**Comment by shiftkey** [comment]
@dinocherian thanks for the report.

There was an upgrade in Git 1.2.1 to a newer version of curl, which changed the behaviour with respect to certificate bundles. Previously, using SChannel like we do in GitHub Desktop would ignore any `http.sslCAInfo` config value and use the OS certificate store when validating certificates. After this update, it would try and use this value, which is potentially invalid.

Can you share the output of this command so I can see what your `http.sslCAInfo` bundle is configured to?

```
> git config -l --show-origin
```

**Comment by dinocherian** [comment]
Hi Forster,
Please find the command output below.

file:"C:\\ProgramData/Git/config"       core.symlinks=false
file:"C:\\ProgramData/Git/config"       core.autocrlf=true
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    http.sslbackend=openssl
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    diff.astextplain.textconv=astextplain
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.clean=git-lfs clean -- %f
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.smudge=git-lfs smudge -- %f
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.process=git-lfs filter-process
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.required=true
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    credential.helper=manager
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    core.longpaths=true
file:C:/Users/xyz/.gitconfig filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/xyz/.gitconfig filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/xyz/.gitconfig filter.lfs.process=git-lfs filter-process
file:C:/Users/xyz/.gitconfig filter.lfs.required=true
file:C:/Users/xyz/.gitconfig user.name=Dino Cherian
file:C:/Users/xyz/.gitconfig user.email=Dino.Cherian@rsa.com
file:C:/Users/xyz/.gitconfig http.sslcainfo=/C/Users/xyz/EMCSSLCA-Chain.pem
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
:...skipping...
file:"C:\\ProgramData/Git/config"       core.symlinks=false
file:"C:\\ProgramData/Git/config"       core.autocrlf=true
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    http.sslbackend=openssl
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    diff.astextplain.textconv=astextplain
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.clean=git-lfs clean -- %f
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.smudge=git-lfs smudge -- %f
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.process=git-lfs filter-process
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.required=true
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    credential.helper=manager
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    core.longpaths=true
file:C:/Users/xyz/.gitconfig filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/xyz/.gitconfig filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/xyz/.gitconfig filter.lfs.process=git-lfs filter-process
file:C:/Users/xyz/.gitconfig filter.lfs.required=true
file:C:/Users/xyz/.gitconfig user.name=Dino Cherian
file:C:/Users/xyz/.gitconfig user.email=Dino.Cherian@rsa.com
file:C:/Users/xyz/.gitconfig http.sslcainfo=/C/Users/xyz/EMCSSLCA-Chain.pem
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.symlinks=false
file:.git/config        core.ignorecase=true
file:.git/config        submodule.active=.
file:.git/config        remote.origin.url=https://github.com/netwitness/nw-logparsers.git
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.master.remote=origin
file:.git/config        branch.master.merge=refs/heads/master
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
(END)

Regards,
Dino Cherian

**Comment by shiftkey** [comment]
@dinocherian I believe this is the problem value:

```
file:C:/Users/xyz/.gitconfig http.sslcainfo=/C/Users/xyz/EMCSSLCA-Chain.pem
```

Are you able to change this value to look like an absolute Windows path:

```
C:/Users/xyz/EMCSSLCA-Chain.pem
```

I think that will address your problem, as Git is considering it a relative path and unable to resolve it on disk.

**Comment by dinocherian** [comment]
@shiftkey ,
Thanks for the suggestion,
Are you able to change this value to look like an absolute Windows path:

C:/Users/xyz/EMCSSLCA-Chain.pem

**Where or which file do I need to change this path?**

Thanks,
Dino Cherian

**Comment by shiftkey** [comment]
> Where or which file do I need to change this path?

Apologies for not being clear. The `.gitconfig` in your home directory, `C:/Users/xyz/.gitconfig`, has this config value which should be changed.

**Comment by shiftkey** [comment]
@dinocherian if that file doesn't exist, and you don't need it for handling Git operations with custom certificates (some enterprise networks need this) then you can probably remove the config entry.

**Comment by dinocherian** [comment]
@shiftkey 
Thanks for the suggestion.
It is working for me.

Regards,
Dino
