### ISSUE TITLE
Partial selection no longer working

### ISSUE THREAD

**Issue by jjenzz** [desktop/desktop#5386]
## Description

Deselecting lines does not exclude them from commit.

## Version

* GitHub Desktop: 1.3.2
* Operating system: High Sierra 10.13.1

## Steps to Reproduce

1. Deselect a line from many changes 
2. Add commit message
3. Commit 

### Expected Behavior
The deselected line should still be available to commit separately.

### Actual Behavior
Deselected lines are committed with selected lines.

## Additional Information

![github-desktop](https://user-images.githubusercontent.com/175330/44022903-e4ba9908-9ee0-11e8-8033-13de21717c06.gif)

**Comment by shiftkey** [comment]
@jjenzz I've not been able to reproduce this as-is. Can you tell me if you have any Git hooks in the repository that run as a `pre-commit` step that might be involved here?

**Comment by jjenzz** [comment]
Oh @shiftkey, how did I not think of that? 🙈 haha. Yes, I have prettier running on `pre-commit` using `lint-staged`. There seems to be [an issue over on their repo](https://github.com/okonet/lint-staged/issues/62) tracking this. Apologies. Feel free to close 🙂

**Comment by shiftkey** [comment]
@jjenzz thanks for confirming the root cause!
