### ISSUE TITLE
Add UI support for common rebase actions (reorder, delete, rename, squash)

### ISSUE THREAD

**Issue by cdmihai** [desktop/desktop#5391]
I often (several times per day) reorder, delete, and squash commits via interactive rebase. It would be nice to implement these commands from the UI client from the History tab by dragging and dropping commits (for reorder and squash) and right click context menu (for delete and rename).

**Comment by billygriffin** [comment]
Hi @cdmihai. We're tracking this in #3422 and is likely something we'll be digging into in a bit more depth in the next few months, so please follow along there. I copied your request there to add continued context as we research possible approaches.
