### ISSUE TITLE
show the full date and time of commits

### ISSUE THREAD

**Issue by ggedde** [desktop/desktop#5395]
Currently, the full date and time of a commit is not shown anywhere.  Maybe I am missing it.
There is the relative time shown ex (6 days ago) and if the date is old enough it will then show (Aug 6th, 2018)

This is fine for a quick glance, but I really don't want to be doing the math all the time trying to figure out wha the date was 6 days ago if today is the 3rd, etc

It is nice having the quick reference in the History column, but I think when clicking on the commit it should include the full date and time in the commit window next to the commit number, changed files, etc.  Also the ability to copy the date and time text would be appreciated.

This might raise additional concerns with some wanting different formatting options, 24 hours support, etc, but I would prefer a generic 12hour format.  I would use this would wanting to copy the date and commit message to relay to a client or Project Manager, etc.  So making it easy for them to read would be best.

**Comment by ggedde** [comment]
This works, Thanks!
Although I cannot copy it due to it being a tooltip, but that is not a big deal.

**Comment by shiftkey** [comment]
> Although I cannot copy it due to it being a tooltip, but that is not a big deal.

For the moment we have some issues like https://github.com/desktop/desktop/issues/2944 around being able to copy details from in the app to use elsewhere, but if we get more interest in being able to copy the timestamp we'll revisit this.

**Comment by shiftkey** [comment]
I'm going to close this out as we have a read-only way to find the timestamp associated with a commit.

**Comment by ggedde** [comment]
@shiftkey After a few weeks using the tooltip I now find it sort of a pane.  Sometimes the tooltip does show so I have to move my mouse around and come back to it and wait.  I still think it would be nice to show the date next to the commit message when selecting the commit in the history log.  Currently there is a bunch of empty space and could support it.

![github-desktop-dates](https://user-images.githubusercontent.com/3236909/47752886-02aba600-dc53-11e8-87a7-c389c118159e.png)

Thanks

**Comment by YoungjaeKim** [comment]
Hi @shiftkey , could you consider to reopen this issue? My wish is exactly same as what @ggedde depicted above.

**Comment by chrisdlee1** [comment]
It would be much better to just show the date, and time, of each commit, all the time, where the '9 days ago' is now, and not need to hover. Point is, I like to look for a specific commit by time, and quickly scan through them, not have to hover over each individually and memorize. 
Or at least have that option.

**Comment by mehlbmth** [comment]
I wonder why there are timestamps shown here, instead of "quite long ago" or "pretty recently" - this is inconsistent. 
Honestly, this should be configurable.

**Comment by HughWarrington** [comment]
People who commented about always displaying the full date/time: I have proposed a feature to address this in #17702. Give that a thumbs up if you would like to see it implemented.
