### ISSUE TITLE
Merge conflicts cause confusion and aren't handled well

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#5400]
**Please describe the problem you think should be solved**

When people run into a merge conflict, it's often a confusing and overwhelming experience. GitHub Desktop provides a few ways to merge code from one branch into another (or when pulling from your upstream remote), but when a merge conflict occurs, there isn't a particularly elegant way of handling it, and the app just sort of leaves people on their own to resolve it, usually in the browser, with their editor, or on the command line + an in-terminal editor.

Example:

This recent issue clearly captures an example where this can fall down: https://github.com/desktop/desktop/issues/5264

**Next steps**

- [x] Conduct interviews with non-GitHub people about their experiences with merge conflicts
- [x] Synthesize the notes and identify particular problem areas
- [x] Evaluate GitHub Desktop's existing handling of those problem areas
- [x] Prototype one or more possible solutions and get them in front of users
- [ ] Build and release first iteration in Desktop

We'll be using this issue to update the progress on each of these and we'll likely update it with additional references of others who have run into problems in this realm.

**Comment by billygriffin** [comment]
Via @niik in #2640 for solving the problem of differentiating between conflicted files and those without conflicts: We talked about this and we think that a good first step is, as has been previously suggested, to sort them ahead of other changed files. Individually they'll still be sorted alphabetically but they'll be visually grouped together. We think that'll make a big difference.

**Comment by ampinsk** [comment]
# Designs

After some sketching, and a quick round of usability testing, we have a direction that we're going to move forward with building.

✨ [**Clickable prototype**](https://projects.invisionapp.com/share/VRODZ3VGW89#/323477467_Start) ✨ 

### Encountering merge conflicts

This experience would begin by clicking the `Merge into...` button when comparing branches, or from the Merge options in the Branch menu.

<img width="1440" alt="start 2x" src="https://user-images.githubusercontent.com/10404068/46443449-7de86d80-c722-11e8-873a-24390579dd0f.png">


If you run into conflicts, we will show you this modal, which lists the conflicted files, and sends you to your editor of choice. You can abort your merge at any time in the process.

<img width="1440" alt="no resolved conflicts 2x" src="https://user-images.githubusercontent.com/10404068/46768777-5c493200-cc9e-11e8-8fc9-ec3434a4de88.png">


If you abort while you have some resolved changes, we’ll show you a confirmation modal.

<img width="1440" alt="abort-merge-confirm" src="https://user-images.githubusercontent.com/10404068/46768811-7aaf2d80-cc9e-11e8-80e6-adf80e91ac9a.png">


### Resolving merge conflicts

Using Atom as an example, you would resolve conflicts in your editor or merge tool of choice:

<img width="1440" alt="animals_ unresolved 2x" src="https://user-images.githubusercontent.com/10404068/46443448-7de86d80-c722-11e8-9abd-202b78efb0ba.png">
<img width="1440" alt="animals_ resolved 2x" src="https://user-images.githubusercontent.com/10404068/46443447-7de86d80-c722-11e8-87cd-258bb021a65e.png">

When you come back to Desktop, these changes are reflected:

<img width="1440" alt="animals resolved objects conflicted 2x" src="https://user-images.githubusercontent.com/10404068/46768827-8995e000-cc9e-11e8-8b99-00ce663a0604.png">


As you continue to resolve the conflicts, the modal continues to update. The number of merge conflicts per file will update as you resolve the conflicts in each file:

<img width="1440" alt="objects_ no resolved 2x" src="https://user-images.githubusercontent.com/10404068/46443446-7de86d80-c722-11e8-9017-ac8b4d88267d.png">

<img width="1440" alt="objects_ some resolved 2x" src="https://user-images.githubusercontent.com/10404068/46443443-7d4fd700-c722-11e8-9e26-be4e0f8a41ad.png">

<img width="1440" alt="objects partially resolved 2x" src="https://user-images.githubusercontent.com/10404068/46769378-6ff59800-cca0-11e8-876e-c6641fc0c24c.png">


<img width="1440" alt="objects_ resolved 2x" src="https://user-images.githubusercontent.com/10404068/46443442-7d4fd700-c722-11e8-9a7f-ede72ef2a6e4.png">

### Committing your merge

Once all conflicts are resolved, you can commit the merge from the modal, and we’ll take you to the Changes view with your merge commit ready to be undone if needed.

<img width="1440" alt="all resolved 2x" src="https://user-images.githubusercontent.com/10404068/46443437-7d4fd700-c722-11e8-8890-68c89a14ac2f.png">

<img width="1440" alt="done 2x" src="https://user-images.githubusercontent.com/10404068/46769821-d7f8ae00-cca1-11e8-82cd-1ba777122eda.png">



## Some questions we're still looking to investigate:
1. Are users comfortable not seeing a diff inside GHD?
2. What do users expect to happen and be able to accomplish when they go to the command line during the process?
3. Where should users be taken after they commit the merge from the modal?
4. How does this respond to terminal actions? For example, what if I merge in terminal and then go to GHD?
5. Do users stash files in the middle of a conflict and why?
6. How do users expect to handle binary files?


cc @billygriffin @donokuda @outofambit

**Comment by hdsantos89** [comment]
I don't have a great deal of time to answer here but I definitely want to answer this question.
**1. Are users comfortable not seeing a diff inside GHD?**
Yes, I, personally, am. However,  I would much prefer to see a diff happening within GHD. Also would love to see the ability to change between two views (up-down in same file comparison and side by side comparison). I probably am just a bigger fan of side by side with coinciding lines.

**Comment by mcmz** [comment]
In my opinion users expect to see a simple side by side diff view. With some simple black arrows to merge the diff from ltr and rtl.

**Comment by billygriffin** [comment]
@mcmz Please keep discussion in this issue to merge conflicts. #172 is where we're tracking side-by-side diffs. Thank you!

**Comment by Tsarfolk** [comment]
I wanted to write that I don't like the changes, cause the default editor is Atom (...nasty tabs...) and I can't really change it... But then, I took a look at settings and found there Sublime 🙌 

So, I'm ok with new feature. Can't say that wow it's a breakthrough, but it's good for sure
About editors, for person, who doesn't like sublime / webstorm or Atom (I found it as options of default editor which I can choose on my machine) it can be annoying. Since he or she really can't change the editor to the favourite one if it's not in the list
For example, Xcode is not supported as a default editor. But I can open *.swift file by clicking "Open with Default Program" and at the same time, I can't do it while merge conflicts in the new version

I personally use GHD only for merge conflicts and to watch current (some commit) diff
for checkout, pull, push, reset and etc CLI is more preferable for me

**Comment by billygriffin** [comment]
Thanks @Tsarfolk! There are a lot of editors available to work with Desktop ([documentation here](https://github.com/desktop/desktop/blob/master/docs/technical/editor-integration.md) with available editors), and for the example you gave, XCode, we have an open issue if someone wants to configure it: https://github.com/desktop/desktop/issues/4825.

You're also able to always update your preferred editor in preferences.

<img width="512" alt="screen shot 2018-11-19 at 8 41 11 am" src="https://user-images.githubusercontent.com/5091167/48717568-eefeba00-ebd6-11e8-832d-9c79c2e0ee71.png">

Hope that's helpful! Our primary goal with the feature was to lower the level of intimidation of merge conflicts and make them more approachable for newer developers, while also not making them too burdensome for more experienced developers.

**Comment by everhardt** [comment]
When merging, I don't always only review conflicts: I sometimes want to review other changes as well. 

Until now, I was able to glance through them by going through each file in the "changed files" list in GH. Wit this modal, I can't do that anymore. If it's a long list of files, I can't even see in GH which files are changed, as I can't scroll with the modal in place.

Therefore, I'd like to have a third button in the modal: "Resolve manually", where the modal closes and the changes are still in the staging area/ working directory.

**Comment by billygriffin** [comment]
Thanks @everhardt! That's really helpful feedback. We're looking at this in #6213. Your problem statement is slightly different from the person's from that issue but I think @ampinsk's initial thinking on it would also solve your problem in a similar manner that you proposed. We're still discussing this internally and trying to gather more data about how it's working for folks and how it's falling down, so I really appreciate you weighing in.

**Comment by jbrennan** [comment]
Seconding these things mentioned by @Tsarfolk and @everhardt as they line up with my experiences as well:

> For example, Xcode is not supported as a default editor. But I can open *.swift file by clicking "Open with Default Program" and at the same time, I can't do it while merge conflicts in the new version

and 

> Until now, I was able to glance through them by going through each file in the "changed files" list in GH. Wit this modal, I can't do that anymore. If it's a long list of files, I can't even see in GH which files are changed, as I can't scroll with the modal in place.
> 
> Therefore, I'd like to have a third button in the modal: "Resolve manually", where the modal closes and the changes are still in the staging area/ working directory.

My workflow in GHD up until the new merge modal has been:

- merge in the branch in GHD
- if there are conflicts, open each conflicted file in Xcode via right click -> open with default program
- fix the merges in Xcode

Now, I don’t have that option. And since Xcode is not yet recognized as one of the valid GHD editors, I actually can’t perform a conflicted merge in GHD now.

Just wanted to give some +1s on this thread, thanks!

**Comment by billygriffin** [comment]
Thanks @jbrennan, especially for explaining your workflow! I think you should be able to do something very similar to your previous workflow when we ship the next iteration (that we're tracking in #6213), and also have available which conflicted files have all the conflicts resolved and which are still conflicted. Sorry for the inconvenience in the mean time. We're hoping this new path will be more useful for both people who prefer a bit more of a guided editor-centric workflow and people like you and the others who have offered feedback.

Quick question for you though, if XCode did show up as a supported editor in the guided flow, do you think you'd still prefer to resolve it in the old way, or would you like to use the guided flow?

**Comment by jbrennan** [comment]
> I think you should be able to do something very similar to your previous workflow when we ship the next iteration (that we're tracking in #6213)

Excellent, looking forward to this!

> if XCode did show up as a supported editor in the guided flow, do you think you'd still prefer to resolve it in the old way, or would you like to use the guided flow?

Hard to say for sure since I currently haven’t been able to use the flow, but probably yes. What I care about most during merge conflicts are seeing which files are conflicted + opening them in my editor to resolve them. Seems like supporting Xcode as an editor should handle that OK in the current workflow :)

**Comment by timor-raiman** [comment]
This is good news.
However, we are missing:
1.  an option to accept one of the versions (--ours or --theirs) without merging through a merge tool
2.  being able to configure a merge tool other than an editor (like winmerge)

For (1), right now, we drop to cli and do "git checkout --ours/theirs -- path/to/file; git add path/to/file" for each file we don't care to merge

**Comment by thientm** [comment]
> Thanks @Tsarfolk! There are a lot of editors available to work with Desktop ([documentation here](https://github.com/desktop/desktop/blob/master/docs/technical/editor-integration.md) with available editors), and for the example you gave, XCode, we have an open issue if someone wants to configure it: #4825.
> 
> You're also able to always update your preferred editor in preferences.
> 
> <img alt="screen shot 2018-11-19 at 8 41 11 am" width="512" src="https://user-images.githubusercontent.com/5091167/48717568-eefeba00-ebd6-11e8-832d-9c79c2e0ee71.png">
> 
> Hope that's helpful! Our primary goal with the feature was to lower the level of intimidation of merge conflicts and make them more approachable for newer developers, while also not making them too burdensome for more experienced developers. We're discussing whether we can improve on the latter portion in #6213.

hope this have a optiosn for KDiff3
