### ISSUE TITLE
Thanks Github

### ISSUE THREAD

**Issue by kateeliza24** [desktop/desktop#5402]
## Version

* GitHub Desktop:

* Operating system:

**Comment by billygriffin** [comment]
@kateeliza24 Thanks for opening an issue! We ask that people fill out the issue template to make sure the maintainers are spending their time effectively.

Thanks for meeting us halfway!

**Comment by billygriffin** [comment]
@kateeliza24 If this was just to say thanks, then you're very welcome. 😄 And if there's something going on with Desktop that you need assistance with, please just let us know. I'll go ahead and close this for now.

**Comment by mirai-zoom** [comment]
どうも　ありがとう　ございます。
よろしく　どうぞ
