### ISSUE TITLE
The github desktop by windows 7 can't sign in

### ISSUE THREAD

**Issue by billhorry** [desktop/desktop#5404]
## Description
The log described below:
Error: Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.

## Version

* GitHub Desktop:

* Operating system:

**Comment by billygriffin** [comment]
@billhorry Thanks for opening an issue! We ask that people fill out the full issue template to make sure the maintainers are spending their time effectively and have enough information to diagnose the problem.

Thanks for understanding and meeting us halfway!

**Comment by billhorry** [comment]
@billygriffin When can you give me a solution to this problem?

**Comment by shiftkey** [comment]
I've just added the issue template to this issue to prevent further confusion

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @billhorry if you're able to fill out the issue template to provide more details about the issue we're happy to revisit this.
