### ISSUE TITLE
open . -a "/Applications/GitHub Desktop.app" doesn't work

### ISSUE THREAD

**Issue by kawanet** [desktop/desktop#5405]
The previous version of GitHub Desktop for Mac has allowed for `open` command to launch the app with the current directory as below:

```sh
open . -a "/Applications/GitHub Desktop.app"
```

The current version 1.3.2 doesn't work on the other hand.

Thank you for providing the great app anyway. 😃

**Comment by j-f1** [comment]
You can run `github .` from the command line to open GitHub Desktop and prompt to add the current directory.

**Comment by shiftkey** [comment]
Just don't forget to install the command line shortcut first:

<img width="287" src="https://user-images.githubusercontent.com/359239/44146299-5e9b2f1e-a065-11e8-8191-a1404f5568db.png">

<img width="435" src="https://user-images.githubusercontent.com/359239/44146329-75d26332-a065-11e8-9306-c74a9fd83005.png">

**Comment by kawanet** [comment]
Thanks! It works! 😀 

https://help.github.com/desktop/guides/getting-started-with-github-desktop/launching-github-desktop-from-the-command-line/
