### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by jthalliley** [desktop/desktop#5414]
## Description
GitHub Desktop does not support a corporate NTLM proxy?

## Version

1.3.2
* GitHub Desktop:

* Operating system:
Windows 7

## Steps to Reproduce

1. Set up a github.com account from the File-->Options dialog.
2. Attempt to clone a repository from same.

### Expected Behavior

I'd expect that I'd be prompted for proxy credentials, or that github desktop would use the IE settings on Windoze. (Strangely enough, github desktop does list the repos to clone from github.com)

### Actual Behavior

Dialog with:  fatal: unable to access 'https://github.com/jthalliley/vf-todo-list.git/': Received HTTP code 407 from proxy after CONNECT

## Additional Information

Seems to also fail when a github enterprise installation inside our firewall. Then I get a dialog with this message:

Cloning into 'C:\Users\jhalliley\work\ancillary-service'...
fatal: unable to access 'http://github.cac.com/CAC-caps/ancillary-service.git/': Recv failure: Connection was aborted

**Comment by steveward** [comment]
Thanks for opening this @jthalliley. 

If you are using NTLM you will need to use something like [CNTLM](https://sourceforge.net/projects/cntlm/) or [PX](https://github.com/genotrance/px) to act as a layer between GitHub Desktop and your proxy.

Once you have set that up you just need to point Git to use that proxy by running the following command:

`git config --global http.proxy http://localhost:3128`

Replace the localhost and port to point to wherever your local CNTLM/Px server is running. Let me know if that doesn't get things working for you. You can check out [this guide](http://www.lmxm.net/git/2012/05/21/github-behind-isa-proxy.html) for reference as well.

**Comment by steveward** [comment]
@jthalliley I'm going to close this out, but please follow along in https://github.com/desktop/desktop/issues/2789 for updates about better proxy support in GitHub Desktop.

**Comment by jthalliley** [comment]
FYI:  I do use cntlm and I have configured the global proxy for git, but it still fails.
