### ISSUE TITLE
GitHub Desktop failed to launch

### ISSUE THREAD

**Issue by deanq** [desktop/desktop#5416]
## Description
I have changed nothing. It's been running fine for a while, and then this keeps coming up and crashing...

## Version
* GitHub Desktop: 1.3.2
* Operating system: Mac OS 10.13.6

## Steps to Reproduce
1. Do nothing
2. Wait for it to crash over nothing
3. Press Quit and Restart
4. Wait for it to crash again (maybe wait for a few hours)

### Expected Behavior
Not crash

### Actual Behavior
Crashing randomly

### Logs
```
Error: spawn /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git EAGAIN
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by deanq** [comment]
Great. Now the app just keeps relaunching with nothing to show. I force kill GitHub Desktop Helper and GitHub Desktop, but they just quit and relaunch over and over again. Zombies.

**Comment by niik** [comment]
This bears some resemblance to https://github.com/desktop/desktop/issues/4535.

Could you open the Console app in macOS and see if there's anything interesting being written to the system logs when the application crashes?

The previous issue seemed to hint at resource limits, have you tried rebooting your machine recently?

**Comment by deanq** [comment]
I restarted my Mac and it seemed to go away. I'll update here what I can find in my system logs.

**Comment by shiftkey** [comment]
@deanq I'm going to close this out because it's unclear how to proceed currently. Please follow up if you spot anything unexpected and we can reopen the issue if there's something to investigate.
