### ISSUE TITLE
How to push current branch to remote's other branch?

### ISSUE THREAD

**Issue by myu** [desktop/desktop#5428]
> “When I push current branch to remote, just one origin branch could be choosed. But when I want to push to another remote branch,  just like named 'dev' branch, I can't shift it as a shortcut, I have to code in the command line”

**Comment by steveward** [comment]
Thanks for opening this @myu. GitHub Desktop does not currently support working with remotes other than `origin` (unless you are specifically working with a fork of another repository). This is something that we are tracking in #1442 -- please follow along in that issue for updates about this feature.

**Comment by steveward** [comment]
@myu please let me know if I misunderstood your feature request -- reading it over again I realized I may not have fully understood the workflow you are trying to achieve.
