### ISSUE TITLE
I want to be able to search name of files to be commited/staged.

### ISSUE THREAD

**Issue by prasadsunny1** [desktop/desktop#5430]
I have used source tree.but have moved to GitHub desktop. and I miss the feature that allows me to search files which are in the changes section.

It is helpful to find and stage files I want to commit.
Thanks for the GitHub desktop.

**Comment by billygriffin** [comment]
Hi @prasadsunny1, thanks for opening an issue. Is the problem that you have changes in too many files, and you can't easily sort through them so you're searching for the name of the file to get to it easier? Or are you searching within files? I'm just trying to figure out what problem you're trying to solve with this search.

**Comment by billygriffin** [comment]
Thank you for your issue @prasadsunny1.

We haven't gotten a response to our questions above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
