### ISSUE TITLE
[Metrics] Add default editor and default shell to reported metrics

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#5431]
Context: https://github.com/desktop/desktop/pull/5362/files#r208794338

cc @desktop/analytics for thoughts on whether this is of interest

**Comment by telliott27** [comment]
Just to clarify, would this add a dimension labeled, perhaps, `editor` with the preferred editor (e.g. `atom`, `vscode`, etc) as its value? And then same with `shell`?

**Comment by billygriffin** [comment]
Reference https://github.com/desktop/desktop/issues/6060 for an example of how this information would be useful.
