### ISSUE TITLE
getting error when im commiting

### ISSUE THREAD

**Issue by BROjohnny** [desktop/desktop#5433]
![image](https://user-images.githubusercontent.com/36418402/44298910-e5c92d00-a309-11e8-998c-3f9b90b65ec5.png)
when im commit to my repository getting this error

**Comment by Jobayer12345** [comment]
yes

**Comment by j-f1** [comment]
It looks like you bypassed a step in the Welcome Wizard which asks you to enter your Git user name and email details, which Git requires for creating commits.

Here’s how you can input this information:

* open the **File → Options** menu item
* select the **Git** tab from the dialog
* enter the name and email address that you want to associate with Git commits
* save the changes and try again

Let me know if you have any other issues with this setup.

**Comment by shiftkey** [comment]
Closing this out because I believe this is a setup issue, and @j-f1 has indicated how to configure your Git commit details.
