### ISSUE TITLE
Github Desktop 1.3.3 does not recognize Visual Studio Code 1.26.1

### ISSUE THREAD

**Issue by wildapt01** [desktop/desktop#5437]
**Adding VSCode 1.26.1 User setup to recognized editors**
config: 
Windows 10 x64
VSCode 1.26.1 User setup
Github Desktop 1.3.3
WSL with Ubuntu 18.04

While VSC is associated with the proper file types, and installed as my only editor, GitHub Desktop does not recognize VSCode as an editor.

After a fresh complete re-install of GDesktop, the issue persists. 

It seems only the system-wide install of VSCode is recognized. On the other hand, VSCode team recommends installing the User set-up from now on. Is there any info on this?

**Comment by shiftkey** [comment]
> Is there any info on this?

#5420 is the necessary changes to support the new User install, which will go out with the next update.

**Comment by wildapt01** [comment]
Thanks!

**Comment by shiftkey** [comment]
@wildapt01 just to let you know that `1.3.4` has been published and should support the new User scope install.
