### ISSUE TITLE
error: cannot lock ref 'refs/remotes/origin/

### ISSUE THREAD

**Issue by natros** [desktop/desktop#5438]
It only happens a few times

```
error: cannot lock ref 'refs/remotes/origin/jetty-9.4.x': is at d8e0f8df1206536612c938b63ae677d2352de14b but expected ddd80deeb96eed136029b944258b36b285af79c6
From github.com:eclipse/jetty.project
 ! ddd80deeb9..d8e0f8df12  jetty-9.4.x -> origin/jetty-9.4.x  (unable to update local ref)
 * [new branch]            jetty-9.4.x-2828-http2_connection_listener_contention -> origin/jetty-9.4.x-2828-http2_connection_listener_contention
```

![image](https://user-images.githubusercontent.com/4996289/44312340-66f9f000-a3ee-11e8-9dc0-7b4f54921409.png)

Version 1.3.3
$ git --version
git version 2.18.0
macOS 10.13.6

**Comment by zhzoo** [comment]
On windows, happens to me nearly every time.
Same exact error as you:
error: cannot lock 'ref/remotes/origin/blahblahblah': is at something but expected somethingelse

Hacky workaround I've been doing is a combination of:
running: git gc --prune=now
and deleteing .git/refs/remote/origin

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

This error is often a symptom of more than one process trying to act on the same repository at the same time.

@natros could you verify if you are using other tools to manage your repository while Desktop is open (some IDEs and text editors have git plugins that may access your repository)? 

cc @desktop/support

**Comment by natros** [comment]
hi,

i'm not using other tools, just using this to keep up to date with last changes from a few repositories. the one that most often is causing me problems is this repo:

```
(jetty-9.4.x) git remote -v
origin	git@github.com:eclipse/jetty.project.git (fetch)
origin	git@github.com:eclipse/jetty.project.git (push)
```

and this happens right now
```
error: cannot lock ref 'refs/remotes/origin/jetty-9.4.x': is at 5b5f2fcf5f8241dd9edb998b97ad5e6cd45130a8 but expected 33a1367325530ec38254a279abb30946505af485
From github.com:eclipse/jetty.project
 ! 33a1367325..5b5f2fcf5f  jetty-9.4.x -> origin/jetty-9.4.x  (unable to update local ref)
error: cannot lock ref 'refs/remotes/origin/jetty-9.3.x': is at 29d466e7046bfd2c67d50194a606ed5276a6c8f9 but expected bd143a674ba7fbb3c7e7e450c8102e9a4bd95172
 ! bd143a674b..29d466e704  jetty-9.3.x -> origin/jetty-9.3.x  (unable to update local ref)
error: cannot lock ref 'refs/remotes/origin/jetty-9.4.x-2711-tls_13_compliance': is at eadb7469ea009042a4bc23f1c16173c06c9d68a7 but expected f51c205c6fcdfee412f13a428a81dc2fd148e2ae
 ! f51c205c6f..eadb7469ea  jetty-9.4.x-2711-tls_13_compliance -> origin/jetty-9.4.x-2711-tls_13_compliance  (unable to update local ref)
```

github desktop 1.3.4
$ git --version
git version 2.18.0
macOS 10.13.6

i'm going to remove the repo and start a new clone to see if what happens in a frew days.

**Comment by natros** [comment]
and btw, this is what i have in my config

```
$ cat jetty/.git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = git@github.com:eclipse/jetty.project.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[branch "jetty-9.4.x"]
	remote = origin
	merge = refs/heads/jetty-9.4.x
[branch "jetty-10.0.x"]
	remote = origin
	merge = refs/heads/jetty-10.0.x
```

**Comment by zhzoo** [comment]
Least for me, the latest update fixed the issue.
But previously, I had tried restarting my computer, killing all relevant processes, etc...

**Comment by natros** [comment]
and it's happening again but this time i'm posting the log from developer tools:

```
launching: 1.3.4 (Mac OS 10.13.6)
install.ts:31 execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper.app/Contents/MacOS/GitHub Desktop Helper'
3install.ts:31 [AppStore.withAuthenticatingUser] account found for repository: jetty.project - natros (has token)
install.ts:31 Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.691s)
install.ts:23 `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 1.
From https://github.com/eclipse/jetty.project
 - [deleted]               (none)     -> origin/jetty-9.4.x-2711-tls_13_compliance
 - [deleted]               (none)     -> origin/jetty-9.4.x-2844-clean-up-DefaultServlet-doc-and-webdefault
remote: Counting objects: 221, done.        
remote: Compressing objects:   1% (1/56)           
remote: Compressing objects:   3% (2/56)           
remote: Compressing objects:   5% (3/56)           
remote: Compressing objects:   7% (4/56)           
remote: Compressing objects:   8% (5/56)           
remote: Compressing objects:  10% (6/56)           
remote: Compressing objects:  12% (7/56)           
remote: Compressing objects:  14% (8/56)           
remote: Compressing objects:  16% (9/56)           
remote: Compressing objects:  17% (10/56)           
remote: Compressing objects:  19% (11/56)           
remote: Compressing objects:  21% (12/56)           
remote: Compressing objects:  23% (13/56)           
remote: Compressing objects:  25% (14/56)           
remote: Compressing objects:  26% (15/56)           
remote: Compressing objects:  28% (16/56)           
remote: Compressing objects:  30% (17/56)           
remote: Compressing objects:  32% (18/56)           
remote: Compressing objects:  33% (19/56)           
remote: Compressing objects:  35% (20/56)           
remote: Compressing objects:  37% (21/56)           
remote: Compressing objects:  39% (22/56)           
remote: Compressing objects:  41% (23/56)           
remote: Compressing objects:  42% (24/56)           
remote: Compressing objects:  44% (25/56)           
remote: Compressing objects:  46% (26/56)           
remote: Compressing objects:  48% (27/56)           
remote: Compressing objects:  50% (28/56)           
remote: Compressing objects:  51% (29/56)           
remote: Compressing objects:  53% (30/56)           
remote: Compressing objects:  55% (31/56)           
remote: Compressing objects:  57% (32/56)           
remote: Compressing objects:  58% (33/56)           
remote: Compressing objects:  60% (34/56)           
remote: Compressing objects:  62% (35/56)           
remote: Compressing objects:  64% (36/56)           
remote: Compressing objects:  66% (37/56)           
remote: Compressing objects:  67% (38/56)           
remote: Compressing objects:  69% (39/56)           
remote: Compressing objects:  71% (40/56)           
remote: Compressing objects:  73% (41/56)           
remote: Compressing objects:  75% (42/56)           
remote: Compressing objects:  76% (43/56)           
remote: Compressing objects:  78% (44/56)           
remote: Compressing objects:  80% (45/56)           
remote: Compressing objects:  82% (46/56)           
remote: Compressing objects:  83% (47/56)           
remote: Compressing objects:  85% (48/56)           
remote: Compressing objects:  87% (49/56)           
remote: Compressing objects:  89% (50/56)           
remote: Compressing objects:  91% (51/56)           
remote: Compressing objects:  92% (52/56)           
remote: Compressing objects:  94% (53/56)           
remote: Compressing objects:  96% (54/56)           
remote: Compressing objects:  98% (55/56)           
remote: Compressing objects: 100% (56/56)           
remote: Compressing objects: 100% (56/56), done.        
remote: Total 221 (delta 64), reused 144 (delta 63), pack-reused 60        
Receiving objects:   0% (1/221)   
Receiving objects:   1% (3/221)   
Receiving objects:   2% (5/221)   
Receiving objects:   3% (7/221)   
Receiving objects:   4% (9/221)   
Receiving objects:   5% (12/221)   
Receiving objects:   6% (14/221)   
Receiving objects:   7% (16/221)   
Receiving objects:   8% (18/221)   
Receiving objects:   9% (20/221)   
Receiving objects:  10% (23/221)   
Receiving objects:  11% (25/221)   
Receiving objects:  12% (27/221)   
Receiving objects:  13% (29/221)   
Receiving objects:  14% (31/221)   
Receiving objects:  15% (34/221)   
Receiving objects:  16% (36/221)   
Receiving objects:  17% (38/221)   
Receiving objects:  18% (40/221)   
Receiving objects:  19% (42/221)   
Receiving objects:  20% (45/221)   
Receiving objects:  21% (47/221)   
Receiving objects:  22% (49/221)   
Receiving objects:  23% (51/221)   
Receiving objects:  24% (54/221)   
Receiving objects:  25% (56/221)   
Receiving objects:  26% (58/221)   
Receiving objects:  27% (60/221)   
Receiving objects:  28% (62/221)   
Receiving objects:  29% (65/221)   
Receiving objects:  30% (67/221)   
Receiving objects:  31% (69/221)   
Receiving objects:  32% (71/221)   
Receiving objects:  33% (73/221)   
Receiving objects:  34% (76/221)   
Receiving objects:  35% (78/221)   
Receiving objects:  36% (80/221)   
Receiving objects:  37% (82/221)   
Receiving objects:  38% (84/221)   
Receiving objects:  39% (87/221)   
Receiving objects:  40% (89/221)   
Receiving objects:  41% (91/221)   
Receiving objects:  42% (93/221)   
Receiving objects:  43% (96/221)   
Receiving objects:  44% (98/221)   
Receiving objects:  45% (100/221)   
Receiving objects:  46% (102/221)   
Receiving objects:  47% (104/221)   
Receiving objects:  48% (107/221)   
Receiving objects:  49% (109/221)   
Receiving objects:  50% (111/221)   
Receiving objects:  51% (113/221)   
Receiving objects:  52% (115/221)   
Receiving objects:  53% (118/221)   
Receiving objects:  54% (120/221)   
Receiving objects:  55% (122/221)   
Receiving objects:  56% (124/221)   
Receiving objects:  57% (126/221)   
Receiving objects:  58% (129/221)   
Receiving objects:  59% (131/221)   
Receiving objects:  60% (133/221)   
Receiving objects:  61% (135/221)   
Receiving objects:  62% (138/221)   
Receiving objects:  63% (140/221)   
Receiving objects:  64% (142/221)   
Receiving objects:  65% (144/221)   
Receiving objects:  66% (146/221)   
Receiving objects:  67% (149/221)   
Receiving objects:  68% (151/221)   
Receiving objects:  69% (153/221)   
Receiving objects:  70% (155/221)   
Receiving objects:  71% (157/221)   
Receiving objects:  72% (160/221)   
Receiving objects:  73% (162/221)   
Receiving objects:  74% (164/221)   
Receiving objects:  75% (166/221)   
Receiving objects:  76% (168/221)   
Receiving objects:  77% (171/221)   
Receiving objects:  78% (173/221)   
Receiving objects:  79% (175/221)   
Receiving objects:  80% (177/221)   
Receiving objects:  81% (180/221)   
Receiving objects:  82% (182/221)   
Receiving objects:  83% (184/221)   
Receiving objects:  84% (186/221)   
Receiving objects:  85% (188/221)   
Receiving objects:  86% (191/221)   
Receiving objects:  87% (193/221)   
Receiving objects:  88% (195/221)   
Receiving objects:  89% (197/221)   
Receiving objects:  90% (199/221)   
Receiving objects:  91% (202/221)   
Receiving objects:  92% (204/221)   
Receiving objects:  93% (206/221)   
Receiving objects:  94% (208/221)   
Receiving objects:  95% (210/221)   
Receiving objects:  96% (213/221)   
Receiving objects:  97% (215/221)   
Receiving objects:  98% (217/221)   
Receiving objects:  99% (219/221)   
Receiving objects: 100% (221/221)   
Receiving objects: 100% (221/221), 44.07 KiB | 8.81 MiB/s, done.
Resolving deltas:   0% (0/64)   
Resolving deltas:   4% (3/64)   
Resolving deltas:   6% (4/64)   
Resolving deltas:   7% (5/64)   
Resolving deltas:   9% (6/64)   
Resolving deltas:  10% (7/64)   
Resolving deltas:  14% (9/64)   
Resolving deltas:  15% (10/64)   
Resolving deltas:  18% (12/64)   
Resolving deltas:  21% (14/64)   
Resolving deltas:  25% (16/64)   
Resolving deltas:  26% (17/64)   
Resolving deltas:  28% (18/64)   
Resolving deltas:  29% (19/64)   
Resolving deltas:  31% (20/64)   
Resolving deltas:  32% (21/64)   
Resolving deltas:  34% (22/64)   
Resolving deltas:  35% (23/64)   
Resolving deltas:  37% (24/64)   
Resolving deltas:  39% (25/64)   
Resolving deltas:  40% (26/64)   
Resolving deltas:  43% (28/64)   
Resolving deltas:  45% (29/64)   
Resolving deltas:  46% (30/64)   
Resolving deltas:  48% (31/64)   
Resolving deltas:  50% (32/64)   
Resolving deltas:  53% (34/64)   
Resolving deltas:  54% (35/64)   
Resolving deltas:  56% (36/64)   
Resolving deltas:  57% (37/64)   
Resolving deltas:  59% (38/64)   
Resolving deltas:  60% (39/64)   
Resolving deltas:  62% (40/64)   
Resolving deltas:  64% (41/64)   
Resolving deltas:  65% (42/64)   
Resolving deltas:  67% (43/64)   
Resolving deltas:  68% (44/64)   
Resolving deltas:  70% (45/64)   
Resolving deltas:  71% (46/64)   
Resolving deltas:  73% (47/64)   
Resolving deltas:  75% (48/64)   
Resolving deltas:  76% (49/64)   
Resolving deltas:  78% (50/64)   
Resolving deltas:  79% (51/64)   
Resolving deltas:  81% (52/64)   
Resolving deltas:  82% (53/64)   
Resolving deltas:  84% (54/64)   
Resolving deltas:  85% (55/64)   
Resolving deltas:  87% (56/64)   
Resolving deltas:  89% (57/64)   
Resolving deltas:  90% (58/64)   
Resolving deltas:  92% (59/64)   
Resolving deltas:  93% (60/64)   
Resolving deltas:  95% (61/64)   
Resolving deltas:  96% (62/64)   
Resolving deltas:  98% (63/64)   
Resolving deltas: 100% (64/64)   
Resolving deltas: 100% (64/64), completed with 55 local objects.
error: cannot lock ref 'refs/remotes/origin/jetty-9.4.x': is at 7cf027b98f27dd459dd9c1c1f30ffe8dc18745d2 but expected 5b5f2fcf5f8241dd9edb998b97ad5e6cd45130a8
 ! 5b5f2fcf5f..7cf027b98f  jetty-9.4.x           -> origin/jetty-9.4.x  (unable to update local ref)
 * [new branch]            feature/ldap_unit_test_2846 -> origin/feature/ldap_unit_test_2846
error: cannot lock ref 'refs/remotes/origin/jetty-10.0.x': is at 90f15f278b2138834d37ddb963b18b5c43924550 but expected 5afe2e215f93f366d3d7e9c9f4378fb90509a9e5
 ! 5afe2e215f..90f15f278b  jetty-10.0.x          -> origin/jetty-10.0.x  (unable to update local ref)
 * [new branch]            jetty-9.4.x-2191-jpms -> origin/jetty-9.4.x-2191-jpms
error: cannot lock ref 'refs/remotes/origin/jetty-9.4/troubleshooting-guide': is at 29934debd9a90c1f7b4c84b1d3877ccfbca7c9a2 but expected 1be776cb75d174bc83a3fdab3c7e054838446da7
 ! 1be776cb75..29934debd9  jetty-9.4/troubleshooting-guide -> origin/jetty-9.4/troubleshooting-guide  (unable to update local ref)

error @ install.ts:23
install.ts:31 Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.683s)
install.ts:31 Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.026s)
install.ts:23 `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 1.
error: cannot lock ref 'refs/remotes/origin/jetty-9.4.x': is at 7cf027b98f27dd459dd9c1c1f30ffe8dc18745d2 but expected 5b5f2fcf5f8241dd9edb998b97ad5e6cd45130a8
From https://github.com/eclipse/jetty.project
 ! 5b5f2fcf5f..7cf027b98f  jetty-9.4.x           -> origin/jetty-9.4.x  (unable to update local ref)
 * [new branch]            feature/ldap_unit_test_2846 -> origin/feature/ldap_unit_test_2846
error: cannot lock ref 'refs/remotes/origin/jetty-10.0.x': is at 90f15f278b2138834d37ddb963b18b5c43924550 but expected 5afe2e215f93f366d3d7e9c9f4378fb90509a9e5
 ! 5afe2e215f..90f15f278b  jetty-10.0.x          -> origin/jetty-10.0.x  (unable to update local ref)
 * [new branch]            jetty-9.4.x-2191-jpms -> origin/jetty-9.4.x-2191-jpms
error: cannot lock ref 'refs/remotes/origin/jetty-9.4/troubleshooting-guide': is at 29934debd9a90c1f7b4c84b1d3877ccfbca7c9a2 but expected 1be776cb75d174bc83a3fdab3c7e054838446da7
 ! 1be776cb75..29934debd9  jetty-9.4/troubleshooting-guide -> origin/jetty-9.4/troubleshooting-guide  (unable to update local ref)

error @ install.ts:23
install.ts:31 [AppStore.withAuthenticatingUser] account found for repository: Resteasy - natros (has token)
install.ts:31 Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.145s)
install.ts:31 [AppStore.withAuthenticatingUser] account found for repository: maven - natros (has token)
install.ts:31 Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.535s)
install.ts:31 Background fetch for 27 repositories took 9.797sec

```

**Comment by iAmWillShepherd** [comment]
I suspect this issue is caused by how we get the status of a repo. https://github.com/desktop/desktop/pull/5376 should fix this if your issue is indeed caused by us writing status to disk.

**Comment by cacho** [comment]
Happen from time to time to me too.
I'm using VSCode an iTerm2 with agnoster theme to see the branch currently active.

![screen shot 2018-08-30 at 12 50 01 pm](https://user-images.githubusercontent.com/586721/44869459-45510200-ac53-11e8-95f3-7c0633708084.png)
<img width="1398" alt="screen shot 2018-08-30 at 12 50 45 pm" src="https://user-images.githubusercontent.com/586721/44869572-8ba66100-ac53-11e8-8cd3-89e914dad415.png">

**Comment by marek-benes** [comment]
I have the same problem on the latest version of  MacOS.

**Comment by jsimmonds2** [comment]
GitHub Desktop Version 1.4.0 on Windows 10  maybe similar bug.
I have no other tools/processes contacting my GitHub repo.

![ghdesktop-1 4 0](https://user-images.githubusercontent.com/1224439/46009646-8c6fcd00-c103-11e8-9e74-ea9d933aadad.jpg)

**Comment by Comply-it** [comment]
I'm experiencing this issue also. Github Desktop 1.40

**Comment by FernandoHurtado** [comment]
Same issue on Arch linux

**Comment by damaimrs** [comment]
anyone solved this issue? i face this problem too..

**Comment by vishalyadavCB** [comment]
I am also facing this issue on git version 2.19.0.windows.1

**Comment by jsimmonds2** [comment]
@vishalyadavCB  . .  what is the version of your Windows app ?   (1.5.0 seems latest prod release)

**Comment by vishalyadavCB** [comment]
I am not sure about Windows App.
I have figured out this issue by cloning repo again. For this, I have deleted previous code first by taking my code changes in back up.

**Comment by mtonkins** [comment]
I am having the same issue with version 1.6.1.

**Comment by Rohit221990** [comment]
Compare FETCH_HEAD and packed-ref with the latest commit ID and replace Id on the perticular branch

**Comment by shiftkey** [comment]
@mtonkins the fix in #6141 is planned to go out with the next update (`1.6.2`) and is available on the [beta channel](https://github.com/desktop/desktop#beta-channel) currently.

**Comment by harishnarayanan** [comment]
Hi, This is the fix, please delete all the files present in the folder c:\{yourrepo}\.git\refs\remotes\origin\ and do the git fetch..

**Comment by zahidrafiq** [comment]
@harishnarayanan thanks. This solution works.
Mostly this problem arises when we make some commit on pull request remotely.

**Comment by GutierrezDev** [comment]
> Hi, This is the fix, please delete all the files present in the folder c:[yourrepo].git\refs\remotes\origin\ and do the git fetch..

This worked for me. Thanks.

**Comment by psk2** [comment]
> Hi, This is the fix, please delete all the files present in the folder c:[yourrepo].git\refs\remotes\origin\ and do the git fetch..

This worked for me too, thanks :)

**Comment by mido1966** [comment]
Pls No Email mor pls



Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: saikrishna PSK <notifications@github.com>
Datum: 22.05.19 15:51 (GMT+01:00)
An: desktop/desktop <desktop@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [desktop/desktop] error: cannot lock ref 'refs/remotes/origin/ (#5438)


Hi, This is the fix, please delete all the files present in the folder c:[yourrepo].git\refs\remotes\origin\ and do the git fetch..

This worked for me too, thanks :)

**Comment by keesdejong** [comment]
Hi, This is the fix, please delete all the files present in the folder c:[yourrepo].git\refs\remotes\origin\ and do the git fetch..

Worked for me

**Comment by arpitgupta19** [comment]
This worked for me :
**git remote prune origin**

**Comment by Outworldz** [comment]
I am on Windows, which has up/lc issues.  This happened to me when I deleted v2 on one machine, yet the remote had V2 which was what I wanted.  I copied the V2 folder from c:[yourrepo].git\refs\remotes\origin\ to the machine what gave the error. A git pull then merged the changes in normally.

**Comment by maxrikotero** [comment]
i faced with the same issue i could figure out why it happened but the solution of @arpitgupta19 this worked for me.Thanks.

**Comment by acrane1** [comment]
I am facing this issue regularly too. I'm on SuSe linux running git version 2.12.3

**Comment by commando24** [comment]
Neither of solution is working for me on mac.

**Comment by ejagankumar** [comment]
**Delete the Entire Folder .git/refs/remote/origin** ,
and try Git pull or push .
It works for me

**Comment by cemerturk** [comment]
Deleting  just the branch mentioned on the error worked for me (again on Windows).

For the following error I removed the file named MDS-22178 under .git\refs\remotes\origin\features.
_error:_ cannot lock ref 'refs/remotes/origin/Features/MDS-22178': is at 9db2b2d57b2c95467a9376de7f5ee9a4feed2efa but expected 4d503fd3d893474e537a0ec7416e8c2395d5c5da_

When I pulled it again it worked and I had a new file named MDS-22178.

> **Delete the Entire Folder .git/refs/remote/origin** ,
> and try Git pull or push .
> It works for me [Windows]

**Comment by gabrielp16** [comment]
> **Delete the Entire Folder .git/refs/remote/origin** ,
> and try Git pull or push .
> It works for me [Windows]

Esta solución es directa.

**Comment by diepes** [comment]
i just run git pull twice to get around it.

**Comment by rpotter12** [comment]
Hi
I'm having repository https://github.com/rpotter12/whatsapp-play. In this CircleCI build fails with the same reason. Logs are in: https://circleci.com/gh/rpotter12/whatsapp-play/571.
please guide me why it is failing and how to resolve it. :)

**Comment by mohitsehgal** [comment]
> Hi, This is the fix, please delete all the files present in the folder c:[yourrepo].git\refs\remotes\origin\ and do the git fetch..

This works

**Comment by dev-sareno** [comment]
I got the same problem but this one didn't work

> **Delete the Entire Folder .git/refs/remote/origin** ,
> and try Git pull or push .
> It works for me [Windows]


What happened in my case is that I tried to push to a new branch i.e.
```sh
$ git push origin refactor/contacts-page
```
and my remote repository has an existing branch named `refactor`.

I solved it by creating and pushing to a new branch that name didn't start with `refactor/`.
```sh
$ git checkout -b refactor-contacts-page
$ git push origin refactor-contacts-page
```

**Comment by krnm1023** [comment]
I solved it by doing
$ git fetch --prune

**Comment by nastari** [comment]
is giving this error, but the push is being carried out. so fuck it. Git is a limbo at times...

**Comment by ShangxuanWu** [comment]
> This worked for me :
> **git remote prune origin**

This actually works for me!

**Comment by Kejia** [comment]
my solution:
```shell
$ git update-ref -d refs/remotes/origin/f/theheckthing
```

**Comment by jorgeorpinel** [comment]
https://github.com/desktop/desktop/issues/5438#issuecomment-499407043 worked for me, on Windows. The remote had some overlapping refs like `refs/remote/origin/a` and `refs/remote/origin/a/b` which seems to have cause a problem. Who knows...

**Comment by Dd0305** [comment]
git remote add origin <git@site.git>
git push -u origin master

**Comment by myspyhobbymom** [comment]
Get the fuck off my laptop. I got your ip address. Were you are what
controller your using a fkn Mac book. Your know the dodge youtuber he's
coming for you

**Comment by afonsoalbrecht** [comment]
> 
> 
> Hi, This is the fix, please delete all the files present in the folder c:[yourrepo].git\refs\remotes\origin\ and do the git fetch..

that worked!!!

**Comment by rohitattaluri552** [comment]
https://github.com/desktop/desktop/issues/5438#issuecomment-640714563

either this or the other fixes worked for me. Please someone bring me out of this issue.

I'm using MacOs with the below configuration.

<img width="647" alt="Screenshot 2022-02-25 at 12 15 25 PM" src="https://user-images.githubusercontent.com/61145279/155667768-dd0698be-65d4-4950-bfd7-6166d5dad28d.png">

Github desktop with the below Version
<img width="647" alt="Screenshot 2022-02-25 at 12 16 00 PM" src="https://user-images.githubusercontent.com/61145279/155667830-6f078661-0558-4628-a39b-2e3b39e0a4b6.png">

**Comment by PWaksman** [comment]
Damm, I really don't see how this is closed, it still happening when you get some branch deleted or moved/renamed, when the "this fix" is deleting the files.... It works, but its far from being a solution..

one is trying to pull or fetch, but some where lost in the files there is a branch, that is not even pulled from the server, but it is there in the files, and if the actual branch get moved from the server, now, you, that has nothing to do with that branch, didn't made any pull from it, get those errors...

Just ignore it on the freaking pull/fetch command, would make sense if one is trying to pull from the deleted branch, but not from everything else

**Comment by shiennymendeline** [comment]
> Hi, This is the fix, please delete all the files present in the folder c:[yourrepo].git\refs\remotes\origin\ and do the git fetch..

Thank you, it works for me. However, instead of deleting everything in that folder, I prefer deleting the <branch_name> file which is causing this error

**Comment by bawantha** [comment]
Nothing worked for me

**Comment by abhijeet1033** [comment]
![image](https://github.com/desktop/desktop/assets/66121235/d5e3dbca-2f37-4ee9-ac4d-e55cd3714207)

not able to fetch master changes.

**Comment by trickyearlobe** [comment]
This happens for me occasionally with the git commandline too, but it's only transient. A retry is usually successful.

I believe (as @iAmWillShepherd  suggested earlier) that one thing that can cause this is some kind of locking issue. My VSCode has a git plugin which periodically checks remote branch status to tell me how far behind my local branch is. If I remove said plugin I no longer get the issue.

**Comment by h-elbeheiry** [comment]
never had this issue except 4 days ago, started happening with every commit/pull I have to do, Xcode 15.0, MacOS 14.0, GitHub Desktop Version 3.3.4 (arm64)

**Comment by fernandowolff** [comment]
For me, on Windows at least, the only fix was to update the commit code of the branch it complains about directly on the .git/packed-refs file. This file contains all remote branches alongside their head commit codes. In this scenario, the code on this file for this branch was out-dated for some reason. So if you take the correct/latest commit code this branch should have and replace the code on that file with this new one, save it, it should work.

**Comment by ShaliniSekar22** [comment]
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0        error: cannot lock ref 'refs/remotes/origin/sha/task': 'refs/remotes/origin/sha' exists; cannot create 'refs/remotes/origin/sha/task'
From https://github.com/Rubix-StyleSpot-NopCommerce/Uzhavar-Nanban ! [new branch]      sha/task           -> origin/sha/task  (unable to update local ref)
   c487e0f..9e99de8  uzhavar-dev-deploy -> origin/uzhavar-dev-deploy
error: some local refs could not be updated; try running
'git remote prune [https://github.com/Rubix-StyleSpot-NopCommerce/Uzhavar-Nanban.git'](https://github.com/Rubix-StyleSpot-NopCommerce/Uzhavar-Nanban.git%27) to remove any old, conflicting branches


I have this error How can I resolved it.

**Comment by moro256** [comment]
if anyone still getting this you can try:
`git config remote.origin.prune true`

**Comment by na-zi-ya** [comment]
> Nothing worked for me

same here..

**Comment by na-zi-ya** [comment]
> git config remote.origin.prune true

 No solution has worked for me.... Can anyone help resolve this issue...?

**Comment by JohnScalesTR** [comment]
7... years... later... still seeing the issue. Tried deleting the origin folder and pruning but nothing works.

**Comment by frankspies** [comment]
i just had the same error message and in my case it was because i had created the local branch as:
git checkout -b origin/dev__xyz
instead of
git checkout -b dev__xyz
maybe this is your case too ?

**Comment by cryo** [comment]
If you are using a Mac, the filesystem that you are using is CASE-INSENSITIVE, which means branches named ROY and roy will collide.

```[1827][cryo@morbo:~/Desktop/Github/src]$ git pull
error: cannot lock ref 'refs/remotes/origin/roy': is at e384be3f30cac223ac5701ee8409abfdc2ebc371 but expected 229e8bd36b91ce41904348c5f9a2a72d6c8cba1e
From https://github.com/NetBSD/src
 ! 229e8bd36b91..f1b9b4a621fa  roy        -> origin/roy  (unable to update local ref)
```
This will probably break your brain:

```
1830][cryo@morbo:~/Desktop/Github/src]$ ls -l .git/refs/remotes/origin/roy
-rw-r--r--  1 cryo  staff  41 Feb 13 18:25 .git/refs/remotes/origin/roy
[1831][cryo@morbo:~/Desktop/Github/src]$ ls -l .git/refs/remotes/origin/ROY
-rw-r--r--  1 cryo  staff  41 Feb 13 18:25 .git/refs/remotes/origin/ROY
[1831][cryo@morbo:~/Desktop/Github/src]$ ls -l .git/refs/remotes/origin/RoY
-rw-r--r--  1 cryo  staff  41 Feb 13 18:25 .git/refs/remotes/origin/RoY
```

So my theory is that the hash changes based on what the committed put into the tree ... there may be two branches, called ROY and roy, but the filesystem will see them as the same and git will burp.

**Comment by iainheng** [comment]
I am experiencing this issue only when my Cursor IDE is opened. Close the Cursor IDE and it works again.

**Comment by gabri-melis** [comment]
None of the solutions proposed has worked for me. I had to delete the local copy of the repo and clone it again. Working on a pretty powerful but old Windows laptop.

**Comment by agrawalmanu16** [comment]
Below command works best in resolving the issues. 
`git update-ref -d refs/remotes/origin/BRANCH NAME WITH REF ISSUE`
