### ISSUE TITLE
Ability to show diff between two revisions

### ISSUE THREAD

**Issue by elias6** [desktop/desktop#5443]
I really like GitHub Desktop, but there is one feature I have been wishing for: the ability to see a diff between any two revisions.

I know there are other ways of doing this, but they all seem inadequate.`git diff` can do it, but the output is kind of ugly and hard to make sense of, and it doesn't show binary files like images. The GitHub website has its (hidden) "compare" feature, which shows a nice-looking diff, but it only works on remote branches, not local ones. GitHub Desktop recently introduced its "Compare" feature, which can show the commits made between one branch and another, but it does not show all of the differences in one diff.

This would be useful to me. Sometimes I am working on a feature, and I want to see what changes will be made after it is merged and squashed into master. Or sometimes I see someone else's branch, but to know what changes it makes, I have to diff it against master (or whatever other branch it is intended to be merged into).

To me, it seems like most of the tricky work required to implement this feature has already been done. The "Changes" tab in GitHub Desktop already can already show nice-looking diffs between a revision and the revision that came before it. It is already possible (but awkward) in GitHub Desktop to show a nice diff between two revisions by checking out one, squash-merging the other (using the command line), and looking at the latest diff (within GitHub Desktop). This feature would just do this in a simpler and more straightforward way, without making any commits.

The hardest part (to my limited knowledge) would be putting a nice UI on it. Maybe a third tab saying "Diff" can be added next to the "Behind" and "Ahead" tabs in the history section, and clicking that would show the diff.

**Comment by billygriffin** [comment]
Goodness, sorry for the lack of response here @elias6, that's totally my mistake. I was searching for similar issues to https://github.com/desktop/desktop/issues/6757 and stumbled upon this one. This is definitely something that's interesting. As @shiftkey suspected, I think we ought to do some user research to frame the problem(s) that others might have that are similar to this one. I'm going to roll this into #5443 and update that one so we can look at this holistically. Again, I apologize for the lack of a timely response here and really appreciate you explaining the struggle you're having.
