### ISSUE TITLE
Visual Studio Code User version not detected as external editor.

### ISSUE THREAD

**Issue by billw2012** [desktop/desktop#5445]
## Description

New Visual Studio Code User install doesn't get picked up by GitHub desktop as an external editor.

## Version

* GitHub Desktop: 1.3.3

* Operating system: Microsoft Windows [Version 10.0.16299.611]

## Steps to Reproduce

1. Have Visual Studio Code NON User version installed.
2. Install GitHub
3. Install Visual Studio Code User
4. Uninstall Visual Studio Code NON User version.

### Expected Behavior

Visual Studio Code should be usable as an external editor.

### Actual Behavior

"Unable to open external editor" dialog pops up when attempting to use Open in Visual Studio Code menu option.

**Comment by shiftkey** [comment]
@billw2012 thanks for the report. We merged #5420 which will detect the new User install, and this will be available in the next update.

**Comment by shiftkey** [comment]
@billw2012 just to let you know that `1.3.4` has been published and should support the new User scope install.

**Comment by n4ks** [comment]
last vscode version don't work

**Comment by Old-Trekee** [comment]
I'm having the same problem. I've re-installed GitHub Desktop and VScode.
