### ISSUE TITLE
Slow cleaning of Summary and Description

### ISSUE THREAD

**Issue by ShoshinNikita** [desktop/desktop#5452]
## Description

Text from Summary and Description is cleared slowly. So, it can sometimes stay not deleted.

## Version

* GitHub Desktop: 1.3.3

* Operating system: Windows 10

## Steps to Reproduce

1. Enter text into summary and description filelds
2. Press **Commit** button
3. Switch to **History** tab quickly
4. Return to **Changes** tab
5. Fields weren't cleared

### Expected Behavior

Text from Summary and Description is cleared right after committing.

## Additional Information

![ezgif-2-f5a1a4f8bb](https://user-images.githubusercontent.com/30220965/44496715-65465b80-a67e-11e8-9b09-2b624637ad0a.gif)

**Comment by shiftkey** [comment]
@ShoshinNikita thanks for reporting this! 

We're already tracking this issue in #4046, and I think this comment is the same steps as you are performing to reproduce this https://github.com/desktop/desktop/issues/4046#issuecomment-406566833 so please follow along with that issue.
