### ISSUE TITLE
What is 1.3.4-beta1

### ISSUE THREAD

**Issue by say25** [desktop/desktop#5456]
**Please describe the problem you think should be solved**
I'm unsure what is included in 1.3.4-beta1. The release notes haven't been updated (I can't seem to find an open PR with a proposed release note change either).

**[Optional] Do you have any potential solutions in mind?**
Add release notes/

**Comment by immackay** [comment]
`[Improved] Cloning message uses remote repo name not file destination - #5413. Thanks @lisavogtsf!`
`[Improved] Support VSCode user scope installation - #5281. Thanks @saschanaz!`

See desktop/changelog.json.

**Comment by shiftkey** [comment]
@say25 yeah, we didn't go the normal route for release notes review with this update because we're currently onsite at a team mini-summit.

For the moment stay tuned for us showing the beta release notes on the website in #3385, but #3601 is more important and planned for the next feature release.
