### ISSUE TITLE
"fatal" error when viewing a repo with log.showsignature enabled

### ISSUE THREAD

**Issue by demonbane** [desktop/desktop#5466]
## Description
Opening a repo that includes gpg-signed commits while `log.showsignature=true` is set displays a fatal error informing me that... the signature is valid.

## Version

* GitHub Desktop: 1.3.4

* Operating system: 10.14 Beta (18A371a)

## Steps to Reproduce
Open a repo that includes gpg-signed commits while `log.showsignature=true` is set in your gitconfig. (`--global` in my case, but I'm assuming desktop would honor `--system` and `--local` as well)

### Expected Behavior
For the repo to open normally

### Actual Behavior
The repo opens normally **after** displaying a ⚠️**fatal: bad revision** ⚠️warning.

## Additional Information
Everything else appears to work fine after closing the error, and viewing the repo directly from the command line doesn't show any issues.
![image](https://user-images.githubusercontent.com/7385/44605337-c44ec200-a79d-11e8-8006-4b12bbb6b56f.png)

### Logs
```
2018-08-24T19:56:19.911Z - info: [ui] launching: 1.3.4 (Mac OS 10.14.0)
2018-08-24T19:56:19.912Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper.app/Contents/MacOS/GitHub Desktop Helper'
2018-08-24T19:56:20.091Z - info: [ui] Stats reported.
2018-08-24T19:56:25.571Z - error: [ui] `git log gpg: Signature made Thu Jun 28 22:55:54 2018 PDT
gpg:                using RSA key 9AF7E18D91038097BF9D6749F3327D1AA93CF5F0
gpg: Good signature from "Alex Malinovich <alexmalinovich@gmail.com>" [ultimate]
4821ed7e8d9b0ae9a84390f79fe8dca9e0809e9d -C -M -m -1 --first-parent --name-status --format=format: -z --` exited with an unexpected code: 128.
fatal: bad revision 'gpg: Signature made Thu Jun 28 22:55:54 2018 PDT
gpg:                using RSA key 9AF7E18D91038097BF9D6749F3327D1AA93CF5F0
gpg: Good signature from "Alex Malinovich <alexmalinovich@gmail.com>" [ultimate]
4821ed7e8d9b0ae9a84390f79fe8dca9e0809e9d'

2018-08-24T19:58:20.846Z - info: [ui] Background fetch for 6 repositories took 1.709sec
```

**Comment by j-f1** [comment]
This can be overridden by passing the (apparently undocumented) `--no-show-signature` [option](https://github.com/git/git/blob/7e8bfb0412581daf8f3c89909f1d37844e8610dd/revision.c#L2010) to Git.

**Comment by shiftkey** [comment]
@j-f1 thanks for the spot. My guess is that here is where we need to add it (but that might uncover others):

https://github.com/desktop/desktop/blob/513ffaa90ac4396bcbdeea060e53afd78d930638/app/src/lib/git/log.ts#L150-L162
