### ISSUE TITLE
Bring back the "Tree" to show history branches

### ISSUE THREAD

**Issue by BettyBei** [desktop/desktop#5468]
Please bring the "Tree view" back, like the following picture in the previous version.
![tree](https://user-images.githubusercontent.com/10226359/44612061-bed09680-a7f4-11e8-878c-af69cc9ae7b1.png)

**Comment by billygriffin** [comment]
Thanks for the request @BettyBei. This is a duplicate of https://github.com/desktop/desktop/issues/1634, and this is how we're thinking about improving our product-level communication going forward: https://github.com/desktop/desktop/issues/5398

Please follow along in #1634, and thanks again.

**Comment by WencaiZheng** [comment]
Now what?

**Comment by Bilalmirza** [comment]
Bring the tree back please!

**Comment by WencaiZheng** [comment]
GitKaren does that but charge

**Comment by HongJheLi** [comment]
> GitKaren does that but charge

GitKraken？

I just move to [fork ](https://git-fork.com/)since GitKraken did not work with self-hosted repositories for free acount.

**Comment by WencaiZheng** [comment]
yes charge ~$30/user/year I find it's fine.

**Comment by WencaiZheng** [comment]
Maybe gitk will split the money with github who knows

**Comment by FelipeSchneider** [comment]
I also would like to have this back... I've been using SourceTree for a while, but with the recent changes in Github security policies it became pretty hard to work with external apps

**Comment by cj-marius-duna** [comment]
We need this back

**Comment by JGroxz** [comment]
Would be very useful

**Comment by hostfully** [comment]
still a very much needed feature, 4 years later.

**Comment by unikoca** [comment]
looks like a small feature but it's very useful... come on MIcrosoft, give us or tree back!

**Comment by DinhHaoIT** [comment]
I would like it back

**Comment by anasahmed142** [comment]
for the tree view i have to use atlassian bitbucket

**Comment by the-nemz** [comment]
Is this in the plan? I'd really love to have a tree view on an official GitHub client. Ideally something like what SourceTree has. I don't enjoy SourceTree very much but I'm forced to use it for the simple purpose of viewing different branches in a GUI. I just installed GH Desktop on a new computer assuming this had been added, but alas.

**Comment by alockwood05** [comment]
PLEASE!
