### ISSUE TITLE
Please bring back pull request creation from within the app

### ISSUE THREAD

**Issue by louman** [desktop/desktop#5480]
I'm not sure why it got removed but please bring back the PR creation from within the app. No only the section is gone but now when you press cmd+r, it takes you to github. Please let me create a PR without having to open the browser.

**Comment by shiftkey** [comment]
@louman thanks for the feedback! 

We're tracking this in #295, and our thinking when we revisited this was that there were a couple of things that we couldn't do within the app that were important for PRs - like being able to add images. 

Please follow along with #295 in the meantime.
