### ISSUE TITLE
Window spawns off screen after display rearrangement

### ISSUE THREAD

**Issue by butler1233** [desktop/desktop#5483]
After making a change to my display arrangement this week, I noticed that the application has spawned in the same place it was last time it was open (makes sense) except that location is no longer on any screen.  On most applications, this issue can be resolved by using Win+Left or Win+Right, which will snap it to the edge of the screen, and keeping doing that will then snap it onto a screen that exists. Alternatively, Right clicking the window in the taskbar and selecting "Move", then moving the window around with arrow keys works. 

I understand this problem probably doesn't come up much, but I have noticed it. In applications I've developed, I've been able to work around this by, when placing the window in the place it was when closed last, ensure that that area is actually partially on a screen. 

Attached is a rough diagram of what my old and new setups were like, and Desktop's location in both
![github offscreen](https://user-images.githubusercontent.com/15906013/44655402-e0946e00-a9ec-11e8-8b99-69f36d5a91c9.png)

**Comment by shiftkey** [comment]
@butler1233 thanks for the report, and the detailed feedback. 

We're tracking this in #2107 and there's a workaround mentioned in there to restore the default behaviour, so please follow along with that.
