### ISSUE TITLE
enable git's copied and renamed files detection by default?

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#5489]
**Please describe the problem you think should be solved**

Git can automatically detect when files are renamed or copied if you configure it to. By default GitHub Desktop does not turn this on by default, but should it be? 

**[Optional] Do you have any potential solutions in mind?**
Implementation would be a couple lines of config setting, but UI might need some consideration.

**Comment by billygriffin** [comment]
Thanks @outofambit! I'm not sure I understand the problem this is intended to solve. In other words, by not defaulting these to detect copied or renamed files out of the box, what problems are we introducing? Going to remove `needs-design-input` until we have a clarified problem statement, hope that's ok!

**Comment by outofambit** [comment]
ah! @billygriffin that makes sense :) i think i'm gonna close this issue until i have a clearer value proposition to share. 💜 

and just to clarify, i don't think this is high priority or anything, just wanted to have a place to track the idea/question. :)

**Comment by shiftkey** [comment]
> Git can automatically detect when files are renamed or copied if you configure it to. 

Some extra context:

 - for working directory changes, both files need to be staged for detection to kick in
 - for committed changes, this Should Just Work™ (we have a test for `diff.renames` displaying copied files)
 - this can be set in two places in config - `diff.renames` and `status.renames` (if `status.renames` not set, defaults to `diff.renames`)

I'll also point out https://github.com/desktop/dugite-native/issues/72 which was a suggestion about shipping a system config change where a user undid some Desktop functionality, but I haven't quite figured out how to build Git from source so you can use an arbitrary config file for the system config (Git for Windows supports this OOTB already).
