### ISSUE TITLE
No changes reported for an RTF file

### ISSUE THREAD

**Issue by Shadowtail117** [desktop/desktop#5501]
## Description

When saving an RTF file, Desktop recognizes that changes were made but does not find any content changes. Running `git diff` from the command line shows the changes just fine and pushing to the origin uploads the changes as well, but the UI does not report any changes.

## Version

* GitHub Desktop: 1.3.4 de41db3a23ca826b50f8aeda6e792805608250dd

* Operating system: Windows 10 [Version 10.0.17134.228]

## Steps to Reproduce

1. Edit/create an RTF file in a repository (I used WordPad)
2. Open Github Desktop
3. Despite changes having been made, it reports nothing

### Expected Behavior
Desktop would report the changes similar to how the website would.
### Actual Behavior
Desktop reports there being no changes to the file (but still uploads the changes if you push).

## Additional Information
![github desktop](https://user-images.githubusercontent.com/25853190/44760998-4d475f80-aaf6-11e8-9ca0-99025d55499b.png)
(Desktop does not show any changes)
![cmd](https://user-images.githubusercontent.com/25853190/44761004-5cc6a880-aaf6-11e8-87b6-c98136992b67.png)
(Running `git diff` does show changes)
![website diff](https://user-images.githubusercontent.com/25853190/44761028-77008680-aaf6-11e8-98bb-f41b1a6a5cad.png)
(Pushing to the origin will upload the changes despite the app not showing any)

### Logs
[2018-08-29.desktop.production.log](https://github.com/desktop/desktop/files/2330445/2018-08-29.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @Shadowtail117. I quickly tested out a sample RTF file in GitHub Desktop on macOS and was able to view the diff of that file, so I am guessing this may be a specific configuration issue with your repository or machine (I need to test this on Windows as well).

A couple of questions for you:

1. Is there a specific file or repository where you are having this issue that I could take a look at? 
2. Do you have a custom .gitattributes file set for this repository? If not, I would recommend [creating a .gitattributes file](https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes) and adding the following two lines:

```
*.rtf	diff=astextplain
*.RTF	diff=astextplain
```

Those lines will force Git to convert RTF files to a text format before generating the diff, and should hopefully fix this issue for you.

**Comment by Shadowtail117** [comment]
Making a .gitattributes with those lines (in the .git folder; putting it in the root had no effect) fixed the issue and now the app shows the diffs just fine. If you still want the file, it's `synopsis.rtf` in https://github.com/Shadowtail117/Shadows-Parallel/tree/synopsis/chapter-4. 
Thanks for your help!

**Comment by ElectricS01** [comment]
@Shadowtail117 that repo was deleted, do you have a copy of the file that fixes this issue?
