### ISSUE TITLE
Blank Screen on Mac OS Mojave 10.14 

### ISSUE THREAD

**Issue by koconder** [desktop/desktop#5502]
## Description

Github window showing blank/white, but all menu's still working. This is after updating to Mojave public beta (latest build). Tried to reinstall app from latest version on site.

## Version

* GitHub Desktop:

* Operating system: MAC OS Mojave (18A377a)

### Expected Behavior

Show my Github window

### Actual Behavior

Window loads white

<img width="1672" alt="screenshot 2018-08-29 16 12 51" src="https://user-images.githubusercontent.com/25068/44768958-6871a800-aba6-11e8-854a-39d122ae33f1.png">

### Logs

[2018-08-29.desktop.production.log](https://github.com/desktop/desktop/files/2330920/2018-08-29.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @koconder. There have been similar issues reported in https://github.com/desktop/desktop/issues/4054 and https://github.com/desktop/desktop/issues/5387.

Could you try following these steps to see if it gets things working?

1. Close GitHub Desktop
2. Delete the `~/Library/Application Support/Github Desktop` directory
3. Relaunch GitHub Desktop

If that does not work, please let us know if you are possibly running external displays using a DisplayLink adapter. There was [a report](https://github.com/desktop/desktop/issues/5387#issuecomment-412514795) of this causing similar behavior.

**Comment by koconder** [comment]
Issue resolves once you delete the application support and do a hard-restart

**Comment by kod3000** [comment]
Following the instructions listed above did not work on a fresh Install of Mojave 10.14.3 :
 
- Deleting Folder `~/Library/Application Support/Github Desktop`
- Next doing a hard-restart && Relaunching the Application 

Unfortunately, Github Desktop would behave in the same manner by displaying a white screen with no ui/ux inside of it. As mentioned above the top menu does show all the items but most items are disabled cause the program does not load in completely.

However, **the problem does seem to lie in the Application Support directory for Github Desktop**. **I was able to resolve the problem by quitting the application. Going to another machine and copying over the "Application Support" directory for "Github Desktop" onto the fresh install of Mojave.** After the folder is in place, this allows the application to no longer have a blank white screen and perform as expected. 


_Note* I've done fresh installs of Mojave 10.14.3 on 5 machines back to back and all have had the same issue with Github Desktop._
