### ISSUE TITLE
Option for viewing diffs ignoring case changes?

### ISSUE THREAD

**Issue by sharunkumar** [desktop/desktop#5503]
Been working on a VB6 project and the IDE keeps changing the case of the variables whenever I edit a file from within it. So what I used to do before committing was to check the diff with tortoise git and only move my changes, ignoring the case change diffs, like MyVariable being changed to myvariable (which were a lot).
So I was wondering if there was a way to show only the "clean" changes, ignoring all the case sensitive changes in diff so I could just select my changes and commit it. I could later just revert the remaining case changes after the commit. Any thoughts?

This is an example of the changes I would like to ignore in the viewer:
![case-change-diffs](https://user-images.githubusercontent.com/715417/44773529-73b8d980-ab8e-11e8-953d-d48888f29d79.PNG)

EDIT: added screenshot

**Comment by shiftkey** [comment]
> So I was wondering if there was a way to show only the "clean" changes, ignoring all the case sensitive changes in diff so I could just select my changes and commit it.

This is not currently supported in Git without some customization of your Git environment.

Here is an example of how to configure a `difftool` command https://stackoverflow.com/questions/17380029/how-to-perform-case-insensitive-diff-in-git/17380104#17380104 (I've not tested this on Windows)

**Comment by shiftkey** [comment]
@billygriffin yes, this is something I consider to be out of scope for Desktop with a known workaround in Git itself

**Comment by billygriffin** [comment]
Thanks @shiftkey. Sorry this isn't super straight-forward @sharunkumar, but hopefully the example @shiftkey offered is helpful. Going to close this.
