### ISSUE TITLE
Merge branch 'master' from 'master'???

### ISSUE THREAD

**Issue by HeatMint** [desktop/desktop#5504]
When using github desktop, if I am currently in branch "master", and I do commit twice before push, it will have a merge 'master' to branch 'master'. See as two examples below.
![image](https://user-images.githubusercontent.com/24670423/44796514-ab03a680-abdf-11e8-9818-7f4dd162e618.png)
In this time, I commit the same message "add support to npm" twice, and then I push my code.
![image](https://user-images.githubusercontent.com/24670423/44796588-dbe3db80-abdf-11e8-84db-a6763410e992.png)
In this situation, he commit "adding font..." and he undo the "adding font...", then, he commit the "changing button...", and he push his code up, after that, in commit history, it happens that "merge branch 'master'".

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

I want to clarify the issue you're having to make sure we're on the same page. From my understanding:
1. You commit a Change
2. then push it to GitHub
3. and afterwards, you see a merge commit in your history

And in the second instance, your colleague encounters the same issue.

Is this an accurate summary of what you're encountering?

Also, are you merging any PRs? If so, that may be the reason why you're seeing those merge commits.

**Comment by HeatMint** [comment]
Not exactly, my situation is:

1. I commit a Change
2. I commit another Change
3. I push my code

In these process, I never handle any PR, but a merge commit automatically generated.

**Comment by HeatMint** [comment]
I'll close this issue because after several minutes research I found out my problem, but I'm Chinese so I researched in Chinese.
Here's that Chinese article link explain this situation
https://www.cnblogs.com/Sinte-Beuve/p/9195018.html
