### ISSUE TITLE
show border when commit description is expanded

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#5506]
On current `master` we merged #5471 which expands a long commit message to only the space that's needed (rather than filling the whole space). 

On macOS (I'm sure this is the same on other OSes) when the commit is collapsed, there's a 1px grey border separating the commit description from the file list:

<img width="722" src="https://user-images.githubusercontent.com/359239/44803917-2e98a580-ab96-11e8-9556-21a317e09e12.png">

When this is expanded, the border is no longer displayed:

<img width="742" src="https://user-images.githubusercontent.com/359239/44803899-28a2c480-ab96-11e8-9928-d9ef1c388044.png">

This wasn't an issue before because the expanded commit description would take up the whole panel.

Repro steps:

 - create a new repository
 - add some changes so you can commit
 - make a long commit description so that you trigger the expander
 - switch to the history list, select the new commit
 - expand the commit description

**Comment by aryyya** [comment]
@shiftkey 

This was an oversight on my part! It's a quick fix, but I need to determine the best way to hide the border once more if the expanded message is large enough to fill the entire pane.

**Comment by shiftkey** [comment]
@aryyya no problem - feel free to follow up with a fix if you can figure it out!
