### ISSUE TITLE
migrate to yarn for all our packaging needs

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#551]
`yarn@0.16.0` now seems to work for this repository (https://github.com/yarnpkg/yarn/issues/721 was a blocker), and claims to be much faster than vanilla npm.

So let's test this out:
- measure `npm install` improvements on macOS
- measure `npm install` improvements on Windows
- update CI scripts to `npm install -g yarn` - do we get gains there too?
- investigate how `yarn.lock` (needs to be in source control) replaces our usage of `npm-shrinkwrap.json` (I don't think we need to do anything explicit here)
- verify `npm run package` works locally
- verify package works as expected on Windows and macOS

**Comment by albinekb** [comment]
Npm is so slow 😭
