### ISSUE TITLE
First letter of directory name duplicated

### ISSUE THREAD

**Issue by BruceEckel** [desktop/desktop#5512]
## Description

The first letter of a directory name is duplicated in github desktop, which then claims the directory is empty.

The directory:
![image](https://user-images.githubusercontent.com/1001900/44820908-45e48c80-abb0-11e8-9bca-5fcda92596e1.png)

What it looks like in Github desktop:
![image](https://user-images.githubusercontent.com/1001900/44820944-644a8800-abb0-11e8-8909-79bb56fe4ca8.png)

I've tried changing the directory name and it does the same thing.

## Version

* GitHub Desktop: 1.3.4

* Operating system: Microsoft Windows [Version 10.0.17134.228]

## Steps to Reproduce

Described above

### Expected Behavior

Normal directory name
### Actual Behavior

Directory name with first letter duplicated.

**Comment by BruceEckel** [comment]
Also, when I try to check it in, I get this:
![image](https://user-images.githubusercontent.com/1001900/44821247-e5564f00-abb1-11e8-8144-62ac2afa4bb0.png)

**Comment by shiftkey** [comment]
@BruceEckel thanks for the report!

I believe this is the same issue as #4670, and is occurring because Desktop doesn't initialize the folder as a submodule correctly. Please follow along with #4670.

**Comment by BruceEckel** [comment]
I discovered later that this happened because I had *cloned* the hugo-nuo subdirectory into the project. Using the command-line git produced an illuminating error message.

**Comment by ishara28** [comment]
Check whether there is a git folder inside that added folder. I deleted that one. That solved for me!
