### ISSUE TITLE
unable to create desktop icon in win7

### ISSUE THREAD

**Issue by Panchalkishan** [desktop/desktop#5517]
there is problem to create desktop icon for desktop github application, for desktop windows operating system, in win7

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

@kp-clash without more information, there is not much I can do.

Can you provide details on your inability to create an icon?
1. What version of Desktop are you using?
1. What version of Windows 7 are you using?
1. Are there any error messages or any other forms of feedback? 
1. What steps have you taken to create the icon? 
1. How long has this been an issue?

**Comment by steveward** [comment]
@kp-clash for reference here are some steps you can take to generate a new shortcut to GitHub Desktop:

1. Open up File Explorer and navigate to `%LocalAppData%\GitHubDesktop`
2. Right-click on the `GitHubDesktop.exe` file 
3. Select `Send to` > `Desktop (create shortcut)` to generate a new shortcut on your desktop

**Comment by thanibharathi** [comment]
First use a original version of windows its easily possible.Otherwise there is a icon Size or pixel or unsupportable format picture you use.Just you restart the windows and left click  and choose personalize and change.

**Comment by shiftkey** [comment]
Closing this out as I believe the comment from @steveward will help resolve the issue.
