### ISSUE TITLE
LF on windows give a warning

### ISSUE THREAD

**Issue by TheBegining** [desktop/desktop#5525]
**Please describe the problem you think should be solved**
> I was working on windows ,i create test.1.html with LF & test.2.html with CRLF
But,github desktop warning me on test.1.html line endings have changed from lf to crlf.
what does it happend?It is LF now. Does It means it auto transform LF to CRLF？
![image](https://user-images.githubusercontent.com/17702287/44917041-dc0fe280-ad69-11e8-853f-f0f7e05489dd.png)
![image](https://user-images.githubusercontent.com/17702287/44917042-dc0fe280-ad69-11e8-9316-9825a6400a1e.png)
![image](https://user-images.githubusercontent.com/17702287/44917057-e9c56800-ad69-11e8-84d7-765c8d0e1b3a.png)
![image](https://user-images.githubusercontent.com/17702287/44917062-edf18580-ad69-11e8-8321-e2acd722bd7c.png)

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

The behavior of changing LF to CRLF is defined in git's configuration. Desktop does not automatically change your line endings. Have a look at these [docs] for more info on changing how git handles line endings.

**Comment by TheBegining** [comment]
Thanks，it really troubled me for a long time
