### ISSUE TITLE
Appveyor builds are failing silently

### ISSUE THREAD

**Issue by streeter** [desktop/desktop#5527]
I noticed that Appveyor builds seem like they are broken, even though they are reported as passing. Check out the build for a recent master commit (9c96a9f0cac29f1276d8f1174dd78c318b96201a): https://ci.appveyor.com/project/github-windows/desktop/build/10374#L797

But the status is reported as passing.

I'm not sure if the problem was related to moving to jest (see https://github.com/desktop/desktop/pull/5427)

**Comment by outofambit** [comment]
hey @streeter thanks so much for catching this! looking into it now. investigating over at #5528

**Comment by outofambit** [comment]
may be similar to https://github.com/facebook/jest/issues/5841?

**Comment by outofambit** [comment]
actually it is more likely something like this: https://help.appveyor.com/discussions/problems/6413-unit-test-fails-but-build-is-green#comment_42289770

**Comment by shiftkey** [comment]
Some AppVeyor context:

 - tests are run slightly differently there compared to the others CI platforms

https://github.com/desktop/desktop/blob/e3ba4847f3983e2c0a099ca37137b1a68c53b42d/appveyor.yml#L35-L37

 - `test-appveyor.bat` is assigning the `%ERRORLEVEL%` from the previous command to a special environment variable

https://github.com/desktop/desktop/blob/e3ba4847f3983e2c0a099ca37137b1a68c53b42d/script/test-appveyor.bat#L1-L2

This is not for AppVeyor-specific features, but a way for us to pass state around between steps in the build so we can identify when a test run failed and read the log files out from the CI build

> may be similar to https://github.com/facebook/jest/issues/5841?

This is my gut feeling too, based on skimming that issue.

**Comment by outofambit** [comment]
#5528 is now a fix for this issue 🌈
