### ISSUE TITLE
unable to store the account token in the keychain .... after update ?...

### ISSUE THREAD

**Issue by jipexu** [desktop/desktop#5530]
i have now this error and can not connect ...

GitHub Desktop was unable to store the account token in the keychain. Please check you have unlocked access to the 'login' keychain.

in dev console i get this
Error adding account 'jipexu'
Error: The user name or passphrase you entered is not correct.

and i am sure that the account and pass are correct .....

version 1.3.4
mac os 10.13.6

**Comment by shiftkey** [comment]
@jipexu 

> and i am sure that the account and pass are correct .....

This is related to the keychain access, not your GitHub account details. Please read the details in this known issue: https://github.com/desktop/desktop/blob/master/docs/known-issues.md#the-username-or-passphrase-you-entered-is-not-correct-error-after-signing-into-account---3263

**Comment by jipexu** [comment]
ok thanks for the answer

**Comment by Jasperav** [comment]
Link is dead

**Comment by tierninho** [comment]
Fixed the link 😄

**Comment by Jasperav** [comment]
Thx, that fix actually worked, didn't expect that

**Comment by heshamelmasry77** [comment]
i really hate github desktop piece  of shxx

**Comment by lee-dohm** [comment]
@heshamelmasry77 your comment was deleted as a violation of the [Desktop Code of Conduct](https://github.com/desktop/desktop/blob/master/CODE_OF_CONDUCT.md) as it was insulting or derogatory. You may consider this an official warning.

**Comment by IanIsMyUsername** [comment]
it works for me! Thx

**Comment by Chaitanya-Varanasi** [comment]
Thank u so much, such a saviour :)

**Comment by DevelopCarlosMD** [comment]
thank you, It saved me time =)

**Comment by SomeEarth86** [comment]
Yes, It worked for me.
