### ISSUE TITLE
Entire repo gone after stash

### ISSUE THREAD

**Issue by kmcaloon** [desktop/desktop#5539]
**Version: Tasty Things Done Tastily (224)**

Ran into a pretty big issue and really hoping for some help with this one.  After doing some work locally I realized I was on the wrong branch of my repo.  To correct the issue, within the terminal I ran `git stash` to stash the changes, `git checkout development` to switch to the correct branch, then `git stash apply` to apply the changes to the correct branch.  Then using the GUI, I made sure that everything was appearing as it should, committed the changes, and then synced with my remote repo. Everything seemed to go smooth.

Then when attempting to interact to the GUI it crashed.  When I reopened I noticed that everything in my repo was completely gone except for the directory and file related to the latest commit.  This wouldn't be a big deal except I had a large amount of work committed locally that I had not yet synced with remote and now it's gone.  Attached is a screenshot of what I did within the terminal.

<img width="711" alt="screen shot 2018-09-04 at 10 55 53 am" src="https://user-images.githubusercontent.com/10777353/45039374-82413e00-b031-11e8-89b2-65831fe489d7.png">

Is this salvageable??

PS I realize I am using an older version of the GUI. The reason for this is that the new version does not include the graph history view.

**Comment by j-f1** [comment]
Does the `.git` repository still exist?

**Comment by kmcaloon** [comment]
Unfortunately not, which is why I'm assuming this is an irreversible error.

**Comment by j-f1** [comment]
cc @desktop/support — do you have any suggestions?

**Comment by outofambit** [comment]
Hi @kmcaloon, that sounds incredibly frustrating, and I'm so sorry you've lost so much work. We talked about some possibilities internally and there's no obvious solutions. Unfortunately we no longer support the older versions of GitHub Desktop, so I don't have a great answer for you. Best of luck and apologies again that you had this experience.
