### ISSUE TITLE
add support for Typora

### ISSUE THREAD

**Issue by seamusdemora** [desktop/desktop#5558]
There are currently two choices for an external editor in a local repo on my Mac OS machine: `Sublime Text` and `BBEdit`. These are likely popular choices, but they're certainly not the only good choices. 

I think the best solution long-term is to allow users to add any app they wish. If that's impractical, I'd like to see at least the following two apps added to Mac OS: 
1. Typora 
2. Text Edit

**Comment by aryyya** [comment]
There is documentation concerning editor integration [here](https://github.com/desktop/desktop/blob/1de8d45fc6dc3da6b7099c68f0d4a97c311bf972/docs/technical/editor-integration.md).
