### ISSUE TITLE
Error while pulling from rep

### ISSUE THREAD

**Issue by RedRockStudio** [desktop/desktop#5559]
why this happening? It was good. but when I tried to pull from rep at home. 
![index](https://user-images.githubusercontent.com/42136400/45202311-8b414200-b2b3-11e8-8785-7f56f59dbcb4.jpg)
How I can fix this?

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @RedRockStudio if you're able to provide the logs (which contain the actual exception) we're happy to revisit this.
