### ISSUE TITLE
show something when repository filter returns no matches

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#5566]
I noticed we surface actions to engage the user to either 'create a new branch' or 'create a new PR' when a filter shows no results. However, the same cannot be said for the results of a Repo, when they are null. 

We just offer up a bunch of white space. We should take advantage of that space to engage the user with buttons for New Repository, Add Local Repo, Clone Repo options (similar to how our landing page looks).

Repo space:
<img width="245" alt="screen shot 2018-09-07 at 10 52 37 am" src="https://user-images.githubusercontent.com/14828183/45235153-d562fd00-b28c-11e8-9c8a-fb82ed4ce87d.png">

Branch/PR suggestions:
<img width="305" alt="screen shot 2018-09-07 at 10 52 52 am" src="https://user-images.githubusercontent.com/14828183/45235161-dbf17480-b28c-11e8-8e94-1c4f60f8432f.png">
<img width="298" alt="screen shot 2018-09-07 at 10 52 59 am" src="https://user-images.githubusercontent.com/14828183/45235162-dbf17480-b28c-11e8-92ba-4af1b4d5d162.png">

cc @desktop/design

**Comment by ampinsk** [comment]
Thanks for pointing this out @tierninho! I think it's definitely space that we should be at least showing an empty state and a good opportunity to point users to a next step. I think my question is more should we: 

1. Surface all three options (New Repository, Add Local Repo, Clone Repo)?
2. Choose one based on some criteria (most frequently used, what users are most likely looking for in this context)? 

I'd lean towards choosing one action based on what's most frequently used of the three. 👍 

@desktop/analytics do we have metrics on these actions?

This is also a side point, but I just realized we speak from the first person here, do we do that anywhere else? I'd expect us to speak more from the third person. 🤔
