### ISSUE TITLE
what should we show if there's an empty changelog?

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#5569]
We've been pretty diligent with our [changelog](https://github.com/desktop/desktop/blob/master/changelog.json) to ensure that every entry has something in it, but sometimes we leave this empty for beta updates, like this:

```json
{
  "releases: {
    "1.4.0-beta0": [
    ],
    ... 
  }
}
```

This is empty because all of the changes from the last production release were on beta before, so this update is just bumping the version to put `beta` ahead of `production` again. So what should we show users in this situation?

**Comment by outofambit** [comment]
we could have a default message that says something like "No changes in this update" as a placeholder but I'm not super concerned about this as its really only something we'll see in beta.

**Comment by billygriffin** [comment]
Since this hasn't been a major problem and as @outofambit noted it's only ever present in beta, I'm going to close this issue. Thanks!
