### ISSUE TITLE
NDDB prompt is shown for branches already being compared

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#5573]
From my understanding, the NDDB prompt is used a notification to alert the user that the default branch is behind another branch. These prompts do not correspond to the two branches currently being compared. 

Having said that, should we show the NDDB prompt under the following scenarios:

- User is currently comparing Branch A to B. Surfacing the prompt that says the same thing is repetitive. For example, note the prompt and two branches being compared... they are the same:

<img width="476" alt="screen shot 2018-09-07 at 3 59 41 pm" src="https://user-images.githubusercontent.com/14828183/45246802-3653fa80-b2b8-11e8-99e2-25aba6064049.png">

- Also, if the user already clicked `View Commits` or `Merge...` in the prompt, should we show the prompt again? Currently we do.

More thoughts:
- should we change the prompt messaging when there are merge conflicts? Instead of seeing potential merge conflicts after clicking `Merge...`, why not just say something like "We noticed you branch has merge conflicts with X". The two buttons might be different in this scenario.

**Comment by billygriffin** [comment]
Closing in favor of #6875.
