### ISSUE TITLE
No way to open a new window

### ISSUE THREAD

**Issue by manelclos** [desktop/desktop#5578]
## Description
File -> New window is missing (it is there for the old Mac GitHub Desktop), and there is no "new window" keyboard shortcut.

## Version
* GitHub Desktop: 1.3.5

* Operating system: macOS High Sierra 10.13.6

### Expected Behavior
Being able to open multiple windows of GitHub Desktop

### Actual Behavior
Just one window open at a time

## Additional Information
Regression compared to "old" MacOS GitHub version

**Comment by shiftkey** [comment]
@manelclos thanks for the feedback! We're already tracking this in https://github.com/desktop/desktop/issues/3606 and there's some extra context there, so please follow along with that issue.
