### ISSUE TITLE
Can't login to GitHub using the snap version of GitHub Desktop

### ISSUE THREAD

**Issue by NatoBoram** [desktop/desktop#5606]
## Description

Can't login to GitHub using the snap version of GitHub Desktop.

![github desktop bug](https://user-images.githubusercontent.com/10495562/45384452-17b57280-b5dc-11e8-9e56-d44170c303c0.png)

## Version

```bash
$ snap info github-desktop 
name:      github-desktop
summary:   Extend your GitHub workflow beyond your browser with GitHub Desktop
publisher: Snapcrafters
contact:   https://github.com/snapcrafters/github-desktop/issues
license:   unset
description: |
  Extend your GitHub workflow beyond your browser with our Desktop,
  completely redesigned with Electron. Get a unified cross-platform
  experience that's completely open source and ready to customize.
commands:
  - github-desktop
snap-id:      vxuDrMy9vuqIU5Abf2MQOowf2e09tcm9
tracking:     edge
refresh-date: today at 15:50 EDT
channels:                     
  stable:    –                
  candidate: –                
  beta:      –                
  edge:      1.3.4 (31) 140MB -
installed:   1.3.4 (31) 140MB -
```

* Operating system:

```bash
$ neofetch --off
nato@HelionUbuntu 
----------------- 
OS: Ubuntu 18.04.1 LTS x86_64 
Kernel: 4.15.0-34-generic 
Uptime: 4 hours, 44 mins 
Packages: 2148 
Shell: bash 4.4.19 
Resolution: 1920x1080 
DE: GNOME 3.28.3 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Ubuntu-mono-dark [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-3570K (4) @ 4.100GHz 
GPU: NVIDIA GeForce GTX 660 Ti 
Memory: 6003MiB / 7922MiB 
```

## Steps to Reproduce

1. `sudo snap install github-desktop --edge`
2. Open GitHub Desktop. It takes a while the first time.
3. Login

### Expected Behavior

The login completes successfully.

### Actual Behavior

The login fails with the following message : `An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.291" (uid=1000 pid=22162 comm="/snap/github-desktop/31/opt/GitHubDesktop/desktop " label="snap.github-desktop.github-desktop (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.20" (uid=1000 pid=1732 comm="/usr/bin/gnome-keyring-daemon --daemonize --login " label="unconfined")`.

## Additional Information

I believe it's because of an undeclared capability in the app. It should be as simple as modifying the `package.json` file by adding an [interface](https://docs.snapcraft.io/core/interfaces).

### Logs

... and I noticed I reported at the wrong place. There's already https://github.com/snapcrafters/github-desktop/issues/9.

**Comment by shiftkey** [comment]
Currently our Linux builds are in preview mode (see [this documentation](https://github.com/desktop/desktop/blob/master/docs/contributing/linux-testing-and-you.md) for more details), and we're tracking Linux-specific issues over in [my fork](https://github.com/shiftkey/desktop) so I'm going to close this out for the moment to keep this separate from the main project.

Please submit this issue there, but keep in mind our Snap image isn't quite ready yet, and being discussed in https://github.com/shiftkey/desktop/pull/58

**Comment by brunomgalvao** [comment]
I am going through the same problem. Unfortunately the new version does not start on my ubuntu 16.04
