### ISSUE TITLE
Reflect resolved conflicts in commit view

### ISSUE THREAD

**Issue by ampinsk** [desktop/desktop#5609]
**Please describe the problem you think should be solved**
When I hit a merge conflict, GitHub Desktop shows what files are conflicted in the commit view, but doesn't reflect that they've been resolved after I've resolved them in my text editor.

Here's the current flow: 

![screen shot 2018-09-11 at 2 57 22 pm](https://user-images.githubusercontent.com/10404068/45390236-57c42780-b5d3-11e8-8374-bfe964e64504.png)
![screen shot 2018-09-11 at 2 57 40 pm](https://user-images.githubusercontent.com/10404068/45390237-57c42780-b5d3-11e8-86c1-bdc79dcb2b65.png)
![screen shot 2018-09-11 at 2 59 04 pm](https://user-images.githubusercontent.com/10404068/45390238-57c42780-b5d3-11e8-9821-fb5cb6cd07bb.png)

I'll follow up back here with some ideas for solutions! 

cc @outofambit

**Comment by shiftkey** [comment]
You can query Git for unresolved conflicts in working directory changes (like when you're stuck in a merge conflict) like this:

```
$ git diff --check
```

This will list all the places where conflict markers can be found currently:

```
app/src/lib/app-state.ts:295: leftover conflict marker
app/src/lib/app-state.ts:314: leftover conflict marker
app/src/lib/app-state.ts:316: leftover conflict marker
app/src/lib/stores/app-store.ts:3372: leftover conflict marker
app/src/lib/stores/app-store.ts:3374: leftover conflict marker
app/src/lib/stores/app-store.ts:3377: leftover conflict marker
app/src/lib/stores/app-store.ts:3411: leftover conflict marker
app/src/lib/stores/app-store.ts:3423: leftover conflict marker
app/src/lib/stores/app-store.ts:3445: leftover conflict marker
app/src/ui/app.tsx:76: leftover conflict marker
app/src/ui/app.tsx:78: leftover conflict marker
app/src/ui/app.tsx:82: leftover conflict marker
app/src/ui/app.tsx:1261: leftover conflict marker
app/src/ui/app.tsx:1308: leftover conflict marker
app/src/ui/app.tsx:1312: leftover conflict marker
```

The issue here is that `git status` will continue to consider these files as conflicted until they're staged in the index, which we don't do for Desktop (we only stage when you commit). But we could leverage that and combine it with new information from `git diff --check` to indicate that a conflicted file is now considered resolved and safe to commit.

**Comment by ampinsk** [comment]
Initially, I was thinking once we detect a conflict has been resolved, we could show a check: 

![desktop](https://user-images.githubusercontent.com/10404068/45457541-41d26780-b6a4-11e8-87e0-e84e2b7f2ed9.png)

This style itself might be confused with the CI passing icon, but something along these lines.

But after chatting with @nerdneha, I'm actually leaning more towards just removing the conflicted sign and showing the usual `Modified`, `New`, or `Deleted` icons.

![desktop-1](https://user-images.githubusercontent.com/10404068/45457646-d937ba80-b6a4-11e8-9237-e0fc602aada8.png)

Anyone have any thoughts? 

cc @donokuda

**Comment by donokuda** [comment]
> Initially, I was thinking once we detect a conflict has been resolved, we could show a check:
> 
> This style itself might be confused with the CI passing icon, but something along these lines.
> 
> But after chatting with @nerdneha, I'm actually leaning more towards just removing the conflicted sign and showing the usual Modified, New, or Deleted icons.

Coincidentally, I was also thinking that resolved conflicts could be represented with a green check since I thought it would be easier to keep track of files that previously had conflicts.

Out of curiosity, are there specific reasons for using the modified/new/deleted icons as opposed to a check?

**Comment by donokuda** [comment]
Thanks everyone! That all makes sense and I'm onboard with using the modified/new/deleted iconography instead of a check. 😄 

> I was also thinking that resolved conflicts could be represented with a green check since I thought it would be easier to keep track of files that previously had conflicts.

☝️ I'm not concerned of my above thoughts anymore, and if keeping track of previously conflicted files become an issue, I'm sure there are other ways to solve that (grouping being one example that comes to mind.)

**Comment by ampinsk** [comment]
I was looking at this again, and looking at how the GitHub package in Atom handles this, and I was thinking with how git works it could make sense to do something like this, at least as a first step before we look at this flow holistically:

![2-icons](https://user-images.githubusercontent.com/10404068/45575263-c00b4700-b827-11e8-9a36-f41ed37d14f7.png)

Here you see that this file was conflicted, but the check means "ready to merge," aka we detected that there are no more conflicts in the file.

I'm nervous that with just removing the conflict icon you might lose a sense of what you've done, and it might feel strange with existing mental models of git. Anyone have thoughts?

**Comment by outofambit** [comment]
or maybe it could be different states of the yield sign? like conflicted is orange yield sign and and resolved is green or grey yield sign?

**Comment by ampinsk** [comment]
> maybe it could be different states of the yield sign? like conflicted is orange yield sign and and resolved is green or grey yield sign? or maybe that's not readily understood from a first glance?

@outofambit I was thinking about that, and I was nervous that it might be conflating two different slightly concepts ("git says this file is conflicted" vs "we detected that all of the merge markers are gone"). But I also don't love showing the user multiple icons if we don't have to.


Showing a green warning sign feels a little odd to me, and I don't love communicating with color alone for accessibility reasons:
![desktop-2](https://user-images.githubusercontent.com/10404068/45577744-5e9ca580-b832-11e8-84da-46547b120f03.png)


I like the idea of graying it out better since that's also introducing the contrast change, but I might not read this as "resolved" or "ready to merge"
![desktop-1](https://user-images.githubusercontent.com/10404068/45577745-62302c80-b832-11e8-978c-c522e6cbd617.png)


Or we could replace the yield icon with a check and end up back where we started 😆 
![desktop](https://user-images.githubusercontent.com/10404068/45577750-68260d80-b832-11e8-9dc1-a9177248d8a6.png)

**Comment by ampinsk** [comment]
@outofambit and I chatted this through in Slack! We're gonna build the "remove the yield sign" idea to start. We'll see if it feels confusing to come back and not see an indicating that a file _was_ conflicted. If it does, then we'll explore what we should be showing to ease that confusion (a check, a grayed out yield sign, something we haven't thought of yet, etc)

FWIW we're _pretty_ sure it's going to feel confusing, but this gives us an opportunity to validate that hypothesis in a relatively lightweight way!
