### ISSUE TITLE
Delete all local branches not on remote

### ISSUE THREAD

**Issue by jpike88** [desktop/desktop#5611]
I accumulate a lot of local branches that are deleted throughout the week. I have to run this each semi-often:

`git fetch -p && git branch -vv | awk '/: gone]/{print $1}' | xargs git branch -D`

A simple button saying 'delete all local branches not on remote', with a warning to proceed can make this easier.

**Comment by shiftkey** [comment]
@jpike88 thanks for the feedback! We're already tracking this in #750, so please follow along with that issue.

**Comment by kuaminika** [comment]
is there a way to  do this on github?

**Comment by dhengGhuring** [comment]
@jpike88 Thanks that work
