### ISSUE TITLE
NDDB prompt appears after merge initiated

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#5617]
The NDDB appeared after I clicked the `Merge` button at the bottom of the History tab (while comparing my branch with the default branch). 

As you can see the merge was already initiated and a Push is awaiting, yet the prompt appeared seconds after.

<img width="746" alt="screen shot 2018-09-12 at 9 14 58 am" src="https://user-images.githubusercontent.com/14828183/45438748-c7d2bc00-b66c-11e8-8a24-b16e13f37a45.png">

So, after clicking the `Merge` button in the prompt, the `Merge Branch` modal was displayed and it correctly showed that there was no commits to be merged.

<img width="811" alt="screen shot 2018-09-12 at 9 15 14 am" src="https://user-images.githubusercontent.com/14828183/45438999-8c84bd00-b66d-11e8-8112-86c6aaae9d33.png">

I think we need to adjust the timing of the NDDB prompt. I assume there is a slight lag before it is displayed.

tested in v1.4.0, mac

**Comment by billygriffin** [comment]
Closing in favor of #6875
