### ISSUE TITLE
Update the GitHub logo on the About GitHub Desktop page

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#5619]
I wanted to start the conversation on possibly updating the black GitHub logo we use on the About GitHub Desktop to the purple logo in order to match the current Dock icon. 

<img width="458" alt="screen shot 2018-09-12 at 10 30 58 am" src="https://user-images.githubusercontent.com/14828183/45445706-d080bd80-b67f-11e8-9581-3cb6c6a4335c.png">

@desktop/design for feels

cc @nerdneha

**Comment by billygriffin** [comment]
Adding help wanted here as it's not a big thing but nice for consistency and scoped sufficiently for a newer contributor. 😄

**Comment by tierninho** [comment]
## Summary

This issue is to swap the black existing Desktop logo for the purple logo, to stay inline with branding.

## Reproduction steps

To see the logo, go to the top navigation and select the GitHub Desktop menu option, then choose "About GitHub" in Mac. For Windows, see the Help menu. The modal popup will display the logo.

## What happens

Once the logo is replaced, we should see the purple GitHub logo in the place of the black version -- of equal size (64x64px).

<img width="458" alt="screen shot 2018-09-12 at 10 30 58 am" src="https://user-images.githubusercontent.com/14828183/45445706-d080bd80-b67f-11e8-9581-3cb6c6a4335c.png">

## Relevant areas of the source

A good place to start:
https://github.com/desktop/desktop/blob/development/app/src/ui/about/about.tsx
https://github.com/desktop/desktop/tree/development/app/src/ui/octicons

![image](https://user-images.githubusercontent.com/14828183/52807794-9a7da600-3030-11e9-8a75-d662291535be.png)

## Resources

These links will help you get familiar with the project and get started with contributing:

 - [Developer Environment Setup guide](https://github.com/desktop/desktop/blob/development/docs/contributing/setup.md)
 - [Code of Conduct](https://github.com/desktop/desktop/blob/development/CODE_OF_CONDUCT.md)
 - [CONTRIBUTING.md](https://github.com/desktop/desktop/blob/development/.github/CONTRIBUTING.md)

**Comment by tierninho** [comment]
cc @desktop/design does a 64x64px purple logo asset need to be referenced here or do you have one already in the `/src/ui/octicons`?

**Comment by donokuda** [comment]
> cc @desktop/design does a 64x64px purple logo asset need to be referenced here or do you have one already in the `/src/ui/octicons`?

I don't think I exported a logo in 64x64 pixels to be used in the app (png files for the app logo exist in the [app/static/logos](https://github.com/desktop/desktop/tree/development/app/static/logos) folder for what it's worth.)

However, doing a little bit of digging around, I _think_ [`app/static/common`](https://github.com/desktop/desktop/tree/development/app/static/common) is a more appropriate place to put this logo, but please correct me if I'm mistaken 😄  

I went ahead and exported a [64x64 logo](https://user-images.githubusercontent.com/1174461/53454752-0ff85780-39dd-11e9-88a1-b025999bd7bd.png) (at 2x) for whoever wants to pick this up.

**Comment by tierninho** [comment]
@donokuda Thanks!!

This issue is ready to be picked up by any open source contributor. ❇️
