### ISSUE TITLE
Enter button should commit in the commit message box

### ISSUE THREAD

**Issue by cyberpwnn** [desktop/desktop#5621]
There are many times where I will instinctively press enter when finishing my commit message, realizing my mistake and clicking the commit button.

I feel like this is a very simple change but would make a significant difference to those who abuse a keyboard 8 hours a day. If for some reason I am not being clear enough, here is a screenshot: 

<img width="292" alt="screen shot 2018-09-12 at 4 20 25 pm" src="https://user-images.githubusercontent.com/10619135/45451161-3da84900-b6a8-11e8-9165-1444cc9348cf.png">

**Comment by outofambit** [comment]
thanks for writing this up @cyberpwnn! this makes a lot of sense to me. Would you agree that pressing enter in the description field should _not_ commit?

**Comment by shiftkey** [comment]
@cyberpwnn thanks for the feedback. We talked about this ages ago in https://github.com/desktop/desktop/issues/1594 and these two comments essentially match my current thinking:

> Having <kbd>Ctrl</kbd> + <kbd>Enter</kbd> as an explicit submit command prevents any confusion of what hitting <kbd>Enter</kbd> (and <kbd>Shift</kbd> + <kbd>Enter</kbd>) does with other fields (such as the description.)

> this was an inconsistency between the platforms and while unlearning muscle memory is hard we do believe that this is the better of the two routes

**Comment by outofambit** [comment]
hmmm, looks like there's more information to consider here. @cyberpwnn what do you think?

**Comment by shiftkey** [comment]
I'm going to close this out because this was a scenario where the classic apps behaved differently, and we settled on the current behaviour to avoid such confusion. @cyberpwnn let us know if you have any other questions about it.
