### ISSUE TITLE
Add the ability to utilise certificates

### ISSUE THREAD

**Issue by jackr579** [desktop/desktop#5627]
I would like to be able to use github desktop at school for a team-based task, but i cannot publish branches. This is because the school uses a special web-certificate that must be setup in things like web-browsers. Github Desktop, however, doesn't appear to have this feature. Maybe also add support for Proxies?

**Comment by shiftkey** [comment]
@jackr579 thanks for the suggestion!

> This is because the school uses a special web-certificate that must be setup in things like web-browsers. 

It's not quite clear to me what's involved here. Are you able to provide more details, and also share an example of the error you're seeing?

Also, Git does support using proxies for it's Git operations, via config:

```
git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080
```

**Comment by shiftkey** [comment]
Closing this out due to lack of information. @jackr579 if you're able to provide more details about your setup and the issues you're seeing, we're happy to revisit this.
