### ISSUE TITLE
pre-commit hook doesn't work when using #!/bin/bash on windows

### ISSUE THREAD

**Issue by Jamesernator** [desktop/desktop#5628]
## Description
Basically if a pre-commit hook uses `#!/bin/bash` rather than `#!/bin/sh` then it works on the command line (in all of `cmd`, git `bash` and `powershell`) but causes this error in the github app:

```
Commit failed - exit code 1 received, with output: 'error: cannot spawn
C:/Users/Public/github-desktop-issue/githooks/pre-commit: No such file or directory'
```
## Version
* GitHub Desktop: 1.4.0
* Operating system: Microsoft Windows [Version 10.0.17134.285]

## Steps to Reproduce

1. Clone this repository: https://bitbucket.org/Jamesernator/github-desktop-issue
2. Change the githooks directory using `git config core.gitHooks githooks` while in the repo directory
3. Change the example file somehow
4. Try to commit in Github Desktop
5. Error occurs because of #!/bin/bash
6. EXTRA: Try committing in a regular shell, this works per normal

### Expected Behavior
I expected the git hook to work like it did in all three regular shells.

### Actual Behavior
The error mentioned in the top of the post occurs.

## Additional Information
![capture](https://user-images.githubusercontent.com/8518303/45460414-76e8c380-b751-11e8-9e06-016e3a80707b.PNG)

### Logs
[2018-09-12.desktop.production.log](https://github.com/desktop/desktop/files/2377298/2018-09-12.desktop.production.log)

## Non-Solutions Tried:

Although `#!/bin/sh` works on windows (as it uses `bash`) it's a non-solution for user's on other operating systems as `#!/bin/sh` does not in general point to `#!/bin/bash`.

Creating a trivial `#!/bin/sh` file that uses `bash ./pre-commit.bash` doesn't work Windows as `bash` isn't found when run in the github app pre-commit hook.

**Comment by Jamesernator** [comment]
Do you have a suggestion as to how to check if the environment is windows inside a `sh` script that would be compatible with what is implemented in the desktop app?

```bash
if [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
  // Do windows specific logic  
else
 // Do mac/linux logic
fi
```

**Comment by shiftkey** [comment]
This script worked for me on Windows 10 without a Git for Windows installation on the path:

```sh
#!/bin/sh
#!/bin/sh
if [ "$(expr match $(uname -s) 'MINGW64_NT*')" == "10" ]; then
  echo "You may commit on Windows"
  exit 2
else
  echo "You cannot commit on this non-Windows OS"
  exit 3
fi
```

Setting `.git/hooks/precommit` to this script and making a commit would error (as intended) but with the expected message:

<img width="550" src="https://user-images.githubusercontent.com/359239/45824161-b705f400-bcc5-11e8-9091-a96a98de4dd0.png">

I think `uname -s` is a fine enough approach here, but maybe older versions of Windows report the numbers differently:

<img width="267" alt="screen shot 2018-09-20 at 11 11 36 am" src="https://user-images.githubusercontent.com/359239/45824268-faf8f900-bcc5-11e8-95ec-67e7fa7231ca.png">

**Comment by maystar** [comment]
@shiftkey Could you please describe in detail how to fix this issue with the PATH variable? I've still have this problem with such a variable definition: 
![image](https://user-images.githubusercontent.com/3787110/116217047-92117180-a749-11eb-9886-1cc0d636d249.png)

I'm not willing to make the hook scripts more complicated just because of a non-standard behaviour of a specific git client just a few team members are using. 

It would be great if github desktop would give me an option to use an external git installation.

**Comment by Kurt-von-Laven** [comment]
@maystar, add `%LOCALAPPDATA%\Programs\Git\bin` to your user's path via `Settings (Win + I) > Edit environment variables for your account > User variables for … > Path > Edit…`. `%LOCALAPPDATA%` expands to `C:\Users\<user>\AppData\Local\`.
