### ISSUE TITLE
White box in the bottom right corner of "Terms and Conditions" and "License and Open Source Notices" dialogs

### ISSUE THREAD

**Issue by Yuudaari** [desktop/desktop#5629]
## Description
In #5598 a bug was fixed that caused a white box to appear in the bottom right of the release notes. This bug is also present in the "Terms and Conditions" and "License and Open Source Notices" dialogs.

## Version
* GitHub Desktop: 1.4.0
* Operating system: Microsoft Windows [Version 10.0.17134.228]

## Steps to Reproduce
1. Use windows
2. View "Terms and Conditions" or "License and Open Source Notices"

### Expected Behavior
No white box in the corner.

### Actual Behavior
There's a white box in the corner.

## Additional Information

![image](https://user-images.githubusercontent.com/6081834/45461032-51fb3e80-b6c6-11e8-8d0b-97e06beb9abe.png)

PS: How do I open the release notes in the app? Is that something that you can only see when you have a pending update? I had assumed the "release notes" link in "About GitHub Desktop" would have been changed to show that.

**Comment by shiftkey** [comment]
@Yuudaari thanks for the report. I think I stumbled upon the fix for these in #5598 - I'll leave this as `help-wanted` for someone who wants to find the relevant places where we're doing `overflow: scroll` and verify that `overflow: auto` is the right change.

Relevant areas to change:

https://github.com/desktop/desktop/blob/741a5534bcaed63a5b6c5637feb59bd64bdc27c3/app/styles/ui/_terms-and-conditions.scss#L1-L6

https://github.com/desktop/desktop/blob/741a5534bcaed63a5b6c5637feb59bd64bdc27c3/app/styles/ui/_acknowledgements.scss#L1-L6

**Comment by shiftkey** [comment]
> PS: How do I open the release notes in the app? Is that something that you can only see when you have a pending update? 

Yes, we settled on only displaying that dialog to show changes for the pending update.

> I had assumed the "release notes" link in "About GitHub Desktop" would have been changed to show that.

That's some interesting feedback. We wanted to avoid the potentially overwhelming situation of showing every release in such a small space. cc @desktop/design @desktop/core for :eyes:

**Comment by Yuudaari** [comment]
> That's some interesting feedback. We wanted to avoid the potentially overwhelming situation of showing every release in such a small space. 

Are you referring to making the dialog show the entire list of releases like the web page does? I  would have just expected a link to the release notes web page somewhere in the dialog.

**Comment by shiftkey** [comment]
> Are you referring to making the dialog show the entire list of releases like the web page does?

That's what we tried to avoid with this first iteration on it

>  I would have just expected a link to the release notes web page somewhere in the dialog.

See #5605 for that proposal

**Comment by cwongmath** [comment]
With overflow: auto, the white box disappears, but some space between the display of the text and the footer is removed: 
![image](https://user-images.githubusercontent.com/32407067/45591258-35077b00-b913-11e8-888e-48f56d4a30a1.png)

**Comment by shiftkey** [comment]
@cwongmath I think that's fine - and probably the root cause of the styling issue! If you're keen to open a PR with the current fixes we can loop in @desktop/design and figure out if there's anything extra we should do here.

**Comment by cwongmath** [comment]
![image](https://user-images.githubusercontent.com/32407067/45599221-32596400-b9ad-11e8-9fa5-b91c83d7dcae.png)
this is the result of overflow: scroll. that space at the bottom is a horizontal scrollbar that's unused.
