### ISSUE TITLE
Error while pushing: "The remote disconnected. Check your Internet connection and try again."

### ISSUE THREAD

**Issue by DavideTomasella** [desktop/desktop#5630]
I rebuilded a project realized with esp-idf library and, when I tried to push the new files to the repository, Github desktop showed me this error: "The remote disconnected. Check your Internet connection and try again."

Here there is the log file:

2018-09-13T08:21:50.176Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.759s)
2018-09-13T08:21:54.088Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.130s)
2018-09-13T08:23:08.435Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.311s)
2018-09-13T08:23:10.136Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.782s)
2018-09-13T08:23:18.068Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.107s)
2018-09-13T08:23:19.240Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.270s)
2018-09-13T08:24:30.118Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.163s)
2018-09-13T08:24:30.215Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: AQUARIUM-ESP32-ESPIDF-VSCODE - DavideTomasella (has token)
2018-09-13T08:24:35.490Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 5.242s)
2018-09-13T08:24:35.490Z - error: [ui] `git -c credential.helper= push origin master:master --progress` exited with an unexpected code: 1.
Enumerating objects: 2499, done.
Counting objects:   0% (1/2497)   
Counting objects:   1% (25/2497)   
Counting objects:   2% (50/2497)   
Counting objects:   3% (75/2497)   
Counting objects:   4% (100/2497)   
Counting objects:   5% (125/2497)   
Counting objects:   6% (150/2497)   
Counting objects:   7% (175/2497)   
Counting objects:   8% (200/2497)   
Counting objects:   9% (225/2497)   
Counting objects:  10% (250/2497)   
Counting objects:  11% (275/2497)   
Counting objects:  12% (300/2497)   
Counting objects:  13% (325/2497)   
Counting objects:  14% (350/2497)   
Counting objects:  15% (375/2497)   
Counting objects:  16% (400/2497)   
Counting objects:  17% (425/2497)   
Counting objects:  18% (450/2497)   
Counting objects:  19% (475/2497)   
Counting objects:  20% (500/2497)   
Counting objects:  21% (525/2497)   
Counting objects:  22% (550/2497)   
Counting objects:  23% (575/2497)   
Counting objects:  24% (600/2497)   
Counting objects:  25% (625/2497)   
Counting objects:  26% (650/2497)   
Counting objects:  27% (675/2497)   
Counting objects:  28% (700/2497)   
Counting objects:  29% (725/2497)   
Counting objects:  30% (750/2497)   
Counting objects:  31% (775/2497)   
Counting objects:  32% (800/2497)   
Counting objects:  33% (825/2497)   
Counting objects:  34% (849/2497)   
Counting objects:  35% (874/2497)   
Counting objects:  36% (899/2497)   
Counting objects:  37% (924/2497)   
Counting objects:  38% (949/2497)   
Counting objects:  39% (974/2497)   
Counting objects:  40% (999/2497)   
Counting objects:  41% (1024/2497)   
Counting objects:  42% (1049/2497)   
Counting objects:  43% (1074/2497)   
Counting objects:  44% (1099/2497)   
Counting objects:  45% (1124/2497)   
Counting objects:  46% (1149/2497)   
Counting objects:  47% (1174/2497)   
Counting objects:  48% (1199/2497)   
Counting objects:  49% (1224/2497)   
Counting objects:  50% (1249/2497)   
Counting objects:  51% (1274/2497)   
Counting objects:  52% (1299/2497)   
Counting objects:  53% (1324/2497)   
Counting objects:  54% (1349/2497)   
Counting objects:  55% (1374/2497)   
Counting objects:  56% (1399/2497)   
Counting objects:  57% (1424/2497)   
Counting objects:  58% (1449/2497)   
Counting objects:  59% (1474/2497)   
Counting objects:  60% (1499/2497)   
Counting objects:  61% (1524/2497)   
Counting objects:  62% (1549/2497)   
Counting objects:  63% (1574/2497)   
Counting objects:  64% (1599/2497)   
Counting objects:  65% (1624/2497)   
Counting objects:  66% (1649/2497)   
Counting objects:  67% (1673/2497)   
Counting objects:  68% (1698/2497)   
Counting objects:  69% (1723/2497)   
Counting objects:  70% (1748/2497)   
Counting objects:  71% (1773/2497)   
Counting objects:  72% (1798/2497)   
Counting objects:  73% (1823/2497)   
Counting objects:  74% (1848/2497)   
Counting objects:  75% (1873/2497)   
Counting objects:  76% (1898/2497)   
Counting objects:  77% (1923/2497)   
Counting objects:  78% (1948/2497)   
Counting objects:  79% (1973/2497)   
Counting objects:  80% (1998/2497)   
Counting objects:  81% (2023/2497)   
Counting objects:  82% (2048/2497)   
Counting objects:  83% (2073/2497)   
Counting objects:  84% (2098/2497)   
Counting objects:  85% (2123/2497)   
Counting objects:  86% (2148/2497)   
Counting objects:  87% (2173/2497)   
Counting objects:  88% (2198/2497)   
Counting objects:  89% (2223/2497)   
Counting objects:  90% (2248/2497)   
Counting objects:  91% (2273/2497)   
Counting objects:  92% (2298/2497)   
Counting objects:  93% (2323/2497)   
Counting objects:  94% (2348/2497)   
Counting objects:  95% (2373/2497)   
Counting objects:  96% (2398/2497)   
Counting objects:  97% (2423/2497)   
Counting objects:  98% (2448/2497)   
Counting objects:  99% (2473/2497)   
Counting objects: 100% (2497/2497)   
Counting objects: 100% (2497/2497), done.
Delta compression using up to 8 threads.
Compressing objects:   0% (1/1509)   
Compressing objects:   1% (16/1509)   
Compressing objects:   2% (31/1509)   
Compressing objects:   3% (46/1509)   
Compressing objects:   4% (61/1509)   
Compressing objects:   5% (76/1509)   
Compressing objects:   6% (91/1509)   
Compressing objects:   7% (106/1509)   
Compressing objects:   8% (121/1509)   
Compressing objects:   9% (136/1509)   
Compressing objects:  10% (151/1509)   
Compressing objects:  11% (166/1509)   
Compressing objects:  12% (182/1509)   
Compressing objects:  13% (197/1509)   
Compressing objects:  14% (212/1509)   
Compressing objects:  15% (227/1509)   
Compressing objects:  16% (242/1509)   
Compressing objects:  17% (257/1509)   
Compressing objects:  18% (272/1509)   
Compressing objects:  19% (287/1509)   
Compressing objects:  20% (302/1509)   
Compressing objects:  21% (317/1509)   
Compressing objects:  22% (332/1509)   
Compressing objects:  23% (348/1509)   
Compressing objects:  24% (363/1509)   
Compressing objects:  25% (378/1509)   
Compressing objects:  26% (393/1509)   
Compressing objects:  27% (408/1509)   
Compressing objects:  28% (423/1509)   
Compressing objects:  29% (438/1509)   
Compressing objects:  30% (453/1509)   
Compressing objects:  31% (468/1509)   
Compressing objects:  32% (483/1509)   
Compressing objects:  33% (498/1509)   
Compressing objects:  34% (514/1509)   
Compressing objects:  35% (529/1509)   
Compressing objects:  36% (544/1509)   
Compressing objects:  37% (559/1509)   
Compressing objects:  38% (574/1509)   
Compressing objects:  39% (589/1509)   
Compressing objects:  40% (604/1509)   
Compressing objects:  41% (619/1509)   
Compressing objects:  42% (634/1509)   
Compressing objects:  43% (649/1509)   
Compressing objects:  44% (664/1509)   
Compressing objects:  45% (680/1509)   
Compressing objects:  46% (695/1509)   
Compressing objects:  47% (710/1509)   
Compressing objects:  48% (725/1509)   
Compressing objects:  49% (740/1509)   
Compressing objects:  50% (755/1509)   
Compressing objects:  51% (770/1509)   
Compressing objects:  52% (785/1509)   
Compressing objects:  53% (800/1509)   
Compressing objects:  54% (815/1509)   
Compressing objects:  55% (830/1509)   
Compressing objects:  56% (846/1509)   
Compressing objects:  57% (861/1509)   
Compressing objects:  58% (876/1509)   
Compressing objects:  59% (891/1509)   
Compressing objects:  60% (906/1509)   
Compressing objects:  61% (921/1509)   
Compressing objects:  62% (936/1509)   
Compressing objects:  63% (951/1509)   
Compressing objects:  64% (966/1509)   
Compressing objects:  65% (981/1509)   
Compressing objects:  66% (996/1509)   
Compressing objects:  67% (1012/1509)   
Compressing objects:  68% (1027/1509)   
Compressing objects:  69% (1042/1509)   
Compressing objects:  70% (1057/1509)   
Compressing objects:  71% (1072/1509)   
Compressing objects:  72% (1087/1509)   
Compressing objects:  73% (1102/1509)   
Compressing objects:  74% (1117/1509)   
Compressing objects:  75% (1132/1509)   
Compressing objects:  76% (1147/1509)   
Compressing objects:  77% (1162/1509)   
Compressing objects:  78% (1178/1509)   
Compressing objects:  79% (1193/1509)   
Compressing objects:  80% (1208/1509)   
error: corrupt loose object '792489a3d568dd0454eb6f94d552fdda0c876935'
fatal: loose object 792489a3d568dd0454eb6f94d552fdda0c876935 (stored in .git/objects/79/2489a3d568dd0454eb6f94d552fdda0c876935) is corrupt
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
error: failed to push some refs to 'https://github.com/DavideTomasella/AQUARIUM-ESP32-ESPIDF-VSCODE.git'

(The error was parsed as 4: The remote disconnected. Check your Internet connection and try again.)

How can I resolve it?

**Comment by shiftkey** [comment]
@DavideTomasella  thanks for the report! Looks like there's some local repository corruption:

```
error: corrupt loose object '792489a3d568dd0454eb6f94d552fdda0c876935'
fatal: loose object 792489a3d568dd0454eb6f94d552fdda0c876935 (stored in .git/objects/79/2489a3d568dd0454eb6f94d552fdda0c876935) is corrupt
```

@steveward any quick suggestions for getting this sorted?

**Comment by steveward** [comment]
@DavideTomasella GitHub will not allow the repository to be pushed up until the corrupt object is removed. There are a couple of options you can consider to resolve this:

1. Clone a fresh copy of the repository and commit any changes that you had made from the now corrupt repository into the fresh repository. This is likely the quickest solution if you have not yet made a large number of commits in the corrupt local repository.

2. Attempt to fix the corrupt local repository. The first step to take for this would be to open the repository in the command line and run `git fsck` to perform a full check of the local repository. That should give some more information about the level of corruption you are dealing with. After gathering those details you can attempt to resolve the corruption. Resolving repository corruption involves using some specific Git plumbing commands -- there are a few guides for this I have saved that I can share with you, and I can also assist with any specific questions you have.

Let me know how you would like to proceed.

**Comment by DavideTomasella** [comment]
I followed the option 1: I deleted the local repository, cloned a new one from github, modify the necessary files and rebuild the project with the latest version of the esp-idf library.
Now it seems to work.
I'll consider the second option if I find other problems. 

Thanks for your help

**Comment by steveward** [comment]
@DavideTomasella I'm glad to hear you were able to get things up and running again. I'm going to close this issue out.

**Comment by mcNuggets1** [comment]
This happens to me for uploading to much files at once.
Just stops some time and completely messes up the entire upload
Same error message.
Consistently happening also for my friends.

**Comment by rvbatista** [comment]
Had the same problem, but just commited something and it works.
