### ISSUE TITLE
schannel: failed to receive handshake, SSL/TLS connection failed

### ISSUE THREAD

**Issue by pelc13** [desktop/desktop#5632]
## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @pelc13 if you're able to fill out the template to provide more information we're happy to revisit it.

**Comment by VijayalakshmiNatarajan** [comment]
Error: Failed to install 'unknown package' from GitHub:
  schannel: failed to receive handshake, SSL/TLS connection failed
