### ISSUE TITLE
Add positive response if no search results in Clone Repo filter 

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#5637]
When searching for cloned repos in GitHub and Enterprise under File > Clone Repository... there is no positive result when the search turns up 0 results. 

We almost always show a positive result throughout the whole app, such as:
<img width="259" alt="screen shot 2018-09-13 at 10 10 36 am" src="https://user-images.githubusercontent.com/14828183/45504305-506d5d00-b73e-11e8-8c5c-db5830ee305b.png">

Something simple should be shown here (and Enterprise) if no results:
<img width="460" alt="screen shot 2018-09-13 at 10 11 39 am" src="https://user-images.githubusercontent.com/14828183/45504062-adb4de80-b73d-11e8-9aea-c0c391da375e.png">

Suggestion: "Sorry, I can't find that repository"

tested in 1.4.1-beta0, mac.

**Comment by DanielHix** [comment]
Hello, I'd like to get into contributing to Github-Desktop and this seems like a simple thing to start with if you don't mind. If not I'll see if I can't find something else.

**Comment by DanielHix** [comment]
I actually believe I've already finished this! I just need permission to push to the repository so I can push my branch.

**Comment by tierninho** [comment]
@DanielHix Please feel free to begin. Thanks for the help and reach out if ya need anything!

**Comment by DanielHix** [comment]
@tierninho Thanks! I have a Pull Request open which should fix this issue just waiting for a review 👍
