### ISSUE TITLE
I can't push my commits to my private repository.

### ISSUE THREAD

**Issue by Yeadh** [desktop/desktop#5639]
When I am trying to push my commit it is showing an error message every time.It says 
"cannot push these commits as they contain an email address marked as private on GitHub"
![screenshot_3](https://user-images.githubusercontent.com/8848247/45509460-7421b900-b7b9-11e8-8697-cdc9b8c31ff0.png)

Please help me how can I solve this problem?

**Comment by DanielHix** [comment]
You're likely pushing a commit that is signed using your email address, and in your settings on Github. You can change this behavior by either going to github -> settings -> email and unchecking the box that says Block command line pushes that expose my email, make your email not private (right above that option), or sign your commits with a public email.

**Comment by Yeadh** [comment]
@DanielHix I have unchecked the box that says Block command line pushes that expose my email and also made my email not private by unchecked the box and now I have the same problem.

Also, I sign in with a public email but still not working.

**Comment by DanielHix** [comment]
Can you give steps that you do when this problem occurs? Such as, are you creating a new repo and this happens or is to any repo?

**Comment by Yeadh** [comment]
This problem occurs when I create a new repo and in my old repo when I push, it says "last fetched just now" but into the repo, it shows nothing update.
![screenshot_4](https://user-images.githubusercontent.com/8848247/45532259-36527e00-b815-11e8-88fc-2ba5037bbb90.png)

**Comment by shiftkey** [comment]
@Yeadh thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide more information to help troubleshoot.

**Comment by Yeadh** [comment]
It is working now.

**Comment by wasteproduct** [comment]
@DanielHix Which github do you mean by "going to github -> settings ?" I can't find the email part.

**Comment by assidiwassim** [comment]
![image](https://user-images.githubusercontent.com/29416254/66218168-ee74f200-e6c8-11e9-91a7-57810b2a48c7.png)

going to github -> settings -> email and unchecking this box.
view more https://help.github.com/en/articles/setting-your-commit-email-address

**Comment by Saleca** [comment]
> You're likely pushing a commit that is signed using your email address, and in your settings on Github. You can change this behavior by either going to github -> settings -> email and unchecking the box that says Block command line pushes that expose my email, make your email not private (right above that option), or sign your commits with a public email.

Worked for me to just Copy the email from settings here on the website and paste in the options on the desktop. even thou there was a very similar email(if not the same) .
