### ISSUE TITLE
Old version of GitHub Desktop

### ISSUE THREAD

**Issue by Yoti** [desktop/desktop#5642]
Just checked all of releases and not found link to the GitHub Desktop Unnecessary Sequel (3.3.6.1) 56edc3f. I need full offline installer for Windows OS.

**Comment by shiftkey** [comment]
@Yoti the classic Windows app was not a "full" offline installer, but the new Electron app (available from https://desktop.github.com/) does install offline just fine.

**Comment by rio-rattenrudel** [comment]
> 
> 
> Just checked all of releases and not found link to the GitHub Desktop Unnecessary Sequel (3.3.6.1) 56edc3f. I need full offline installer for Windows OS.

You could do it yourself. All you have to do is:

1. Install windows github desktop once via the online installer: https://github-windows.s3.amazonaws.com/GitHubSetup.exe
2. Install a portable version of portableApps Manager: https://portableapps.com/
3. Migrate the copy of ..\AppData\Local\Apps\2.0 into PortableApps.com Platform like described here:
https://superuser.com/questions/842102/how-to-make-shortcut-to-external-apps-in-portableapps-com-platform

**Comment by rio-rattenrudel** [comment]
> 
> 
> Just checked all of releases and not found link to the GitHub Desktop Unnecessary Sequel (3.3.6.1) 56edc3f. I need full offline installer for Windows OS.

You could do it yourself - at least a portable variant. All you have to do is:

1. Install Windows Github Desktop Classic (3.3.6.1) once via the online installer: https://github-windows.s3.amazonaws.com/GitHubSetup.exe
2. Install a portable version of portableApps Manager: https://portableapps.com/
3. Then you could migrate a copy of your Github Desktop Classic Installation from ..\AppData\Local\Apps\2.0 into PortableApps.com Platform like described here: https://superuser.com/questions/842102/how-to-make-shortcut-to-external-apps-in-portableapps-com-platform
