### ISSUE TITLE
Fails to checkout specific PRs repeatedly

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#5650]
## Description

repeated failure to checkout a PR

## Version

* GitHub Desktop: 1.4.0

* Operating system: MacOS 10.13.6

## Steps to Reproduce

1. open branch dropdown
2. click pr tab
3. choose a PR

### Expected Behavior

corresponding branch is checked out
### Actual Behavior

Error popup "A lock file already exists in the repository, which blocks this operation from completing."

## Additional Information

Error popup:
<img width="604" alt="screen shot 2018-09-14 at 1 03 18 pm" src="https://user-images.githubusercontent.com/964912/45572616-9b5ea180-b81e-11e8-8324-62682a780bdb.png">

- seems to only happen on certain branches, but repeatedly
- restarting desktop does not resolve the problem
- choosing the corresponding branch in the branches tab doesn't exhibit this error. it works as expected

### Logs
[2018-09-14.desktop.production.log](https://github.com/desktop/desktop/files/2384718/2018-09-14.desktop.production.log)

**Comment by steveward** [comment]
Closing this out as it was resolved by https://github.com/desktop/desktop/pull/5952 and I haven't seen any further reports.
