### ISSUE TITLE
Feature Request : Script Automation

### ISSUE THREAD

**Issue by MarkPuchalaII** [desktop/desktop#5651]
This is my first time making a feature request, so please let me know if I'm not doing it right.

I use the GithubDarkMode for my Desktop app, but every time the app gets an update, I have to reopen the files for GithubDarkMode to run the script again & get all of its settings reapplied.

What if there was just a place to store custom scripts that automatically run after you press that "wanna update your Github Desktop?" button when it shows up?

**Comment by shiftkey** [comment]
@MarkPuchalaII thanks for the suggestion!

For the moment we don't have plans to support arbitrary scripts manipulating the Desktop user interface, but we did ship a dark theme recently (available under **File** | **Preferences**/**Options**) which is supported:

<img width="487" src="https://user-images.githubusercontent.com/359239/45586379-f8189580-b8cc-11e8-819a-a32fc894d7c6.png">

Please try that out and provide feedback if there are ways we can improve it!
