### ISSUE TITLE
unable to open editors when user account has space in it

### ISSUE THREAD

**Issue by LordOfTheThunder** [desktop/desktop#5655]
**details about your environment - which build, which operating system**
Git Desktop Version 1.4.0
Operating System - Windows 10 Education
Visual Studio Code Version 1.27.2

**details about reproducing the issue - what steps to take, what happens, how often it happens**
I installed Visual Studio Code but the "Open in Visual Studio Code" option doesn't react and nothing happens. When I open the folder manually through Visual Studio Code everything works well.

**Comment by shen5d** [comment]
哦？搜噶~

**Comment by shiftkey** [comment]
@LordOfTheThunder thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by LordOfTheThunder** [comment]
@shiftkey I've made a little investigation and found out that the reason for this problem is, again, because the path of both my sandbox and my visual studio code are has a folder that contains a space.
The issue happens inside launch.ts inside the proc launchExternalEditor
This hardcoded fix makes it run:

```typescript
export async function launchExternalEditor(
  fullPath: string,
  editor: FoundEditor
): Promise<void> {
  var editorPath = editor.path

  const exists = await pathExists(editorPath)
  if (!exists) {
    const label = __DARWIN__ ? 'Preferences' : 'Options'
    throw new ExternalEditorError(
      `Could not find executable for '${editor.editor}' at path '${
        editor.path
      }'.  Please open ${label} and select an available editor.`,
      { openPreferences: true }
    )
  }
  //spawn(editorPath, [fullPath])
  spawn('C:\\Users\\Max Kolchinsky\\AppData\\Local\\atom\\atom.exe', [
    'C:\\Users\\Max Kolchinsky\\Documents\\max_sbox\\desktop',
  ])
}
```

Unfortunately the editorPath contains atom.cmd which is inside bin dir instaed of atom.exe which I used here. I tried multiple options to manipulate both editorPath and fullPath but everything failed.

**Comment by shiftkey** [comment]
@LordOfTheThunder I think we need to encode this argument, like this:

```diff
diff --git a/app/src/lib/editors/launch.ts b/app/src/lib/editors/launch.ts
index 14fcc4b0e..f77e81a9c 100644
--- a/app/src/lib/editors/launch.ts
+++ b/app/src/lib/editors/launch.ts
@@ -12,7 +12,7 @@ export async function launchExternalEditor(
   fullPath: string,
   editor: FoundEditor
 ): Promise<void> {
-  const editorPath = editor.path
+  const editorPath = `"${editor.path}"`
   const exists = await pathExists(editorPath)
   if (!exists) {
     const label = __DARWIN__ ? 'Preferences' : 'Options'
```

Could you test that out and indicate that addresses the issue on your end? We've done this for a couple of shells that can be located under `%APPDATA%` and I'm surprised we haven't had others encounter this previously...

**Comment by LordOfTheThunder** [comment]
I tried this previously and here's the result
![image](https://user-images.githubusercontent.com/43252111/45706915-24ab0680-bb86-11e8-8715-5bac34f15761.png)
I checked manually and the path to this file does exist. The function pathExists on the next line failed to find it. After I tried this I tried moving this line down to make the code look like this
```diff
export async function launchExternalEditor(
  fullPath: string,
  editor: FoundEditor
): Promise<void> {
  var editorPath = editor.path

  const exists = await pathExists(editorPath)
  if (!exists) {
    const label = __DARWIN__ ? 'Preferences' : 'Options'
    throw new ExternalEditorError(
      `Could not find executable for '${editor.editor}' at path '${
        editor.path
      }'.  Please open ${label} and select an available editor.`,
      { openPreferences: true }
    )
  }

+  editorPath = `"${editorPath}"`
  spawn(editorPath, [fullPath])
}
```

And the result was:
![image](https://user-images.githubusercontent.com/43252111/45707397-66887c80-bb87-11e8-88eb-7d66983c3cd5.png)

Even though, again, the path exists.

**Comment by shiftkey** [comment]
`pathExists` is part of `fs-extra` which is just supposed to wrap the core `fs` module, and the seeing that it can't resolve the path - and that ignoring it to call `spawn` still raises `ENOENT` - suggests something is awry.

Are you able to test this in a plain NodeJS project using `fs`? 

```js
const fs = require('fs')
const path = "your-path-here"

fs.stat(path, (err, stats) => {
   if (err) {
      throw err;
      return;
   }

   const isFile = stats.isFile();
   console.log(`file at path '${path}' ${isFile ? 'is' : 'is not'} a file`);

   // TODO: try spawn if successful
});
```

Also, is this only tied to VSCode? Or do Atom and other shells also exhibit the same issue?

**Comment by LordOfTheThunder** [comment]
Using fs worked.
I ran the script with the path:
const path =
  'C:\\Users\\Max Kolchinsky\\Documents\\max_sbox\\desktop\\.github\\CONTRIBUTING.md'
and the output was:
file at path 'C:\Users\Max Kolchinsky\Documents\max_sbox\desktop\.github\CONTRIBUTING.md' is a file

No, this is not only tied to VSCode. I also tested this with atom and got the same problem. This is most likely a global problem with folders that contain spaces.

**Comment by shiftkey** [comment]
@LordOfTheThunder and can you confirm which version of Node you're running that standalone script with, for completeness?

**Comment by LordOfTheThunder** [comment]
v8.11.3
