### ISSUE TITLE
Desktop doesn't recognize a GitHub repository and won't push

### ISSUE THREAD

**Issue by starkat99** [desktop/desktop#5659]
## Description

GitHub Desktop doesn't recognize one of my repositories as being from GitHub and fails to push. Other repositories work fine, just this one single repo has issues.

My repository is hosted at https://github.com/starkat99/ink-rs and is public. Yet when I clone the repo using Desktop, it places in the "Other" section of the repositories list, not the GitHub.com section. This wouldn't be a problem, but somehow Desktop doesn't recognize the remote when I try to push. Whenever I have local changes to push, if I try to use Desktop it brings up a dialog prompt as if I'm pushing a brand new repository to GitHub, asking for name, etc. Using the same name fails with an errors saying it already exists. Again, this was cloned with Desktop.

If I try to push using command line, it works. Just Desktop is failing. Since I use two-factor auth, it's easier to use Desktop than hunt for a personal access token for command line, so I usually just use Desktop for other repositories.

## Version

* GitHub Desktop: 1.14.0

* Operating system: Microsoft Windows [Version 10.0.17134.285]

## Steps to Reproduce

1. Clone https://github.com/starkat99/ink-rs using Desktop
2. Observe ink-rs repo is placed in "Other" section of repository list, not GitHub.com section.
3. Make a local commit.
4. Push local changes using Desktop.
5. Observe Desktop fails to push and shows a dialog for creating a new GitHub.com repo instead.

### Expected Behavior

Push should work as expected on this repo.

### Actual Behavior

Push will instead show a dialog to create a new GitHub.com repository instead of pushing to existing remote origin.

### Logs

[2018-09-16.desktop.production.log](https://github.com/desktop/desktop/files/2386346/2018-09-16.desktop.production.log)

**Comment by shiftkey** [comment]
@starkat99 thanks for the report and the log files. I see a lot of these warnings about the new repository:

```
2018-09-16T01:33:17.546Z - warn: [ui] fetchRepository: 'starkat99/ink-rs' returned a 404
```

This suggests that we're not able to get details about the repository from the GitHub API, which might explain why we mark it as "Other" and try to publish it. Was the repository renamed recently? We've had a couple of reports like this but haven't been able to track down anything conclusive.

I tried cloning down the repository and found it was grouped under GitHub as expected. Could you try removing (right-click on the repository) and re-adding the repository (you can drag-and-drop the folder onto Desktop to save clicks) and see if the behaviour is repeatable?

<img width="280" src="https://user-images.githubusercontent.com/359239/45599348-54a8ad00-b9c0-11e8-9368-051f225af19d.png">

**Comment by starkat99** [comment]
Yup, I've removed and readded multiple times

**Comment by steveward** [comment]
@starkat99 you can try resetting GitHub Desktop by following these steps:

1. Close GitHub Desktop
2. Remove all of the files and folders in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop (you will need to log in and add your repositories again)

Let me know if that does not help either.

**Comment by starkat99** [comment]
Nope, still no luck

**Comment by starkat99** [comment]
Wait, scratch that. It didn't work at first, but after I restarted GitHub Desktop after adding the repository, it recognized it as a GitHub repository and worked

**Comment by steveward** [comment]
@starkat99 I'm glad to hear that got things working. I'm going to close this issue out, but let us know if you run into any further issues.

**Comment by barny** [comment]
This fixed a problem for me where desktop/enterprise had messed up after it let me (unintentionally) try to add a >100Mb file - I can't express how intensely irritating it is that desktop doesn't know about this limit on Enterprise! - and after being unable to decode discovered manual commandline instructions to recover from this I did manual config management by zipping everything up, deleting the repo, deleting my local repo and completely recreating (without the history :-( - the result being that I could clone/commit/push as long as I kept desktop running but after a restart it always wouldn't push origin it always wanted to create a new repo and it already existed. Anyway, deleting the %Appdata/github desktop folder and re-adding the local repos it now works. Phew. Please fix the absence of warning of impending doom on the 100M file limit.

**Comment by ryryqtpi** [comment]
> @starkat99 you can try resetting GitHub Desktop by following these steps:
> 
> 1. Close GitHub Desktop
> 2. Remove all of the files and folders in `%APPDATA%\GitHub Desktop\`
> 3. Restart GitHub Desktop (you will need to log in and add your repositories again)
> 
> Let me know if that does not help either.

That worked for me! Thank you.

**Comment by selieshjks** [comment]
I have deleted the %APPDATA%\GitHub Desktop\ and then reinstalled the github desktop. Now it works for me

**Comment by Leavoh** [comment]
Thank you so much @seliesh20 that fixed my issue!

**Comment by AtillaYasar** [comment]
> @starkat99 you can try resetting GitHub Desktop by following these steps:
> 
> 1. Close GitHub Desktop
> 2. Remove all of the files and folders in `%APPDATA%\GitHub Desktop\`
> 3. Restart GitHub Desktop (you will need to log in and add your repositories again)
> 
> Let me know if that does not help either.

Thanks, that worked.
