### ISSUE TITLE
Cleanup/delete all merged branches from local

### ISSUE THREAD

**Issue by longzheng** [desktop/desktop#5665]
**Please describe the problem you think should be solved**
It is common to have lots of local branches that have already been merged into master. The long list of local branches makes the "branches" list hard to navigate and filter.

There are various terminal commands that can be used to clean up branches by deleting those that have already been merged into master. For example: https://stackoverflow.com/questions/6127328/how-can-i-delete-all-git-branches-which-have-been-merged

**[Optional] Do you have any potential solutions in mind?**
There should be a menu option, under "Branch" perhaps, that allows you to "Clean up all merged branches" that runs the terminal commands automatically behind the scenes.

**Comment by shiftkey** [comment]
@longzheng thanks for the report! We're tracking this in #750 which talks about doing it automagically rather than with a menu item, so please follow along with that issue.
