### ISSUE TITLE
Gui is transparent after build

### ISSUE THREAD

**Issue by LordOfTheThunder** [desktop/desktop#5672]
**Description:**
This might've happened when I tried to install/uninstall ts-node or typescript but around that time, every time I built desktop this is how my window looked:
![image](https://user-images.githubusercontent.com/43252111/45685337-b8aeab00-bb51-11e8-9b49-68d7f737ffe9.png)

my yarn, nodejs and python versions are all correct and build succeeds without issues.
Thanks in advance

**Comment by shiftkey** [comment]
@LordOfTheThunder this feels like what I hope to fix in #5644 - are you running Node 10?

**Comment by LordOfTheThunder** [comment]
No. My node version is 8.11.3.

**Comment by shiftkey** [comment]
Can you ensure you do a `git clean -xdf node_modules` before doing a `yarn` to update packages? That feels like a newer version of `node-sass` (that's incompatible with our current way of styling the app) is still being used.

**Comment by LordOfTheThunder** [comment]
Excellent! This solved the issue! Thank you very much @shiftkey

**Comment by shiftkey** [comment]
@LordOfTheThunder you're welcome!
