### ISSUE TITLE
[Draft] Decoupling stores from databases and other stores

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#5675]
## Problem

Debugging issues that deal with app state is difficult because it's not clear, in all cases, which store is responsible for specific pieces of app state, stores can call into other stores that mutate state, awaiting promises within a transaction is a challenge and not [explicitly compatible](http://dexie.org/docs/Dexie/Dexie.transaction()#transaction-scope) with Node promises (it state's Window.Promise, so maybe that's the reason our transaction don't complete sometime?)

**Mixture of database logic with store logic**

Adding a new store function requires knowing where and how data is stored **and** that we use Dexie.

https://github.com/desktop/desktop/blob/e3bde86f16ecd6820d16d28edb15e611f6ba78be/app/src/lib/stores/pull-request-store.ts#L113-L132

**Stores depend on other stores**

Why does `PullRequestStore` depend on `RepositoriesStore`? Maybe this is a signal that they should not be separated?

https://github.com/desktop/desktop/blob/e3bde86f16ecd6820d16d28edb15e611f6ba78be/app/src/lib/stores/pull-request-store.ts#L30-L38

 We currently use this store to do two things: finding a `GitHubRepository` by its primary key and creating/updating a `GitHubRepository`.

https://github.com/desktop/desktop/blob/e3bde86f16ecd6820d16d28edb15e611f6ba78be/app/src/lib/stores/pull-request-store.ts#L137-L141

https://github.com/desktop/desktop/blob/e3bde86f16ecd6820d16d28edb15e611f6ba78be/app/src/lib/stores/pull-request-store.ts#L336-L348

The second snippet calls directly into another store which mutates another object store before updating app state.

**Comment by niik** [comment]
Closing as it's not a planned work item
