### ISSUE TITLE
Can't authenticate to GitHub

### ISSUE THREAD

**Issue by jeffdgr8** [desktop/desktop#5678]
## UPDATE Resolved:
On Linux for Chrome OS, run `sudo apt install gnome-keyring` in order to store account credentials in the GitHub Desktop app.

## Description
Attempting to sign in to GitHub, after entering my credentials, including two-factor authentication code, I get an error dialog "Unknown or unsupported transport 'disabled' for address 'disabled:'".

If I use the link "Sign in using your browser" I get the error: "Google Chrome OS can't open this page" when the link opens in Chrome.

## Version
* GitHub Desktop: 1.4.0-linux2
* Operating system: Chrome OS 69.0.3497.95 / Debian GNU/Linux 9 (stretch)

## Steps to Reproduce

1. File -> Options... -> GitHub.com Sign in
2. Enter username or email address and password
3. Enter two-factor authentication code
4. Sign in

### Expected Behavior
Be authenticated to GitHub.com

### Actual Behavior
Receive an Error dialog: "Unknown or unsupported transport 'disabled' for address 'disabled:'"

## Additional Information
I installed with the .deb package file.

I get the same error if I attempt to add a repository with its URL and authenticate afterwards.

### Logs
[2018-09-19.desktop.production.log](https://github.com/desktop/desktop/files/2395458/2018-09-19.desktop.production.log)

**Comment by j-f1** [comment]
Are you running crouton or something else?

**Comment by shiftkey** [comment]
```
2018-09-19T04:09:07.623Z - error: [ui] Error adding account 'jeffdgr8'
Error: Unknown or unsupported transport 'disabled' for address 'disabled:'
```

This looks like it's failing when trying to add the token to the GNOME keyring. I haven't had a chance to test out ChromeOS support to see if some dependency is missing, but that's my best guess currently.

**Comment by jeffdgr8** [comment]
I'm running the native Debian Linux container available in Chrome OS 69.

Thanks for the info that it's using GNOME keyring to store the credentials. After running `sudo apt install gnome-keyring`, GitHub Desktop now succeeds in adding my GitHub account.

**Comment by shiftkey** [comment]
@jeffdgr8 thanks, I'll add that to the dependencies for the next update to make that super-clear.

If you find anything else, could you log it over on my fork where I'm handling the Linux packaging currently: https://github.com/shiftkey/desktop

**Comment by jeffdgr8** [comment]
@shiftkey perfect. I actually meant to post this to your fork. Somehow I ended up on the wrong page.

**Comment by Andynopol** [comment]
Hi! I am new to this Chrome OS scene and I was wondering if the problem has been solved. And if not, how can I use the GNOME keyring? Just typing the command sudo `apt install gnome-keyring` in the console didn't cut it for me. I still get the error listed above.

Thank you for your time! I am waiting for your response.

This is the message from the console: 
`Reading package lists... Done`
`Building dependency tree  `     
`Reading state information... Done`
`gnome-keyring is already the newest version (3.28.2-5).`
`0 upgraded, 0 newly installed, 0 to remove and 59 not upgraded.`

**Comment by jeffdgr8** [comment]
@Andynopol this should be resolved in @shiftkey's [latest Linux builds](https://github.com/shiftkey/desktop/releases). What's the error you're getting? Looks like `gnome-keyring` is installed, so should be working.
