### ISSUE TITLE
Improve initial onboarding experience

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#5686]
Based on feedback from new users and user interviews, we think there's an opportunity to improve the onboarding experience in GitHub Desktop and reduce the time between when people download and when they can be more productive using the app. 

We're working on getting baseline metrics in place in #5549, and this issue is intended to capture the work that follows from that.

Specifically, we'd like to reduce the amount of time to each action captured in #5549 and increase the percentage of new users who get to those actions.

**Actions are:**

- Adding repo, cloning repo, creating repo
- Committing
- Being on a non-default branch
- Pushing to GitHub

**The things we want to move the needle on:**

1. Time from first launch of GitHub Desktop to [action] - we want these to go down
2. Percent of installs that reach each action - we want these % to go up

**Problem statements to focus on for our initial iteration:**

1. As a new user to GitHub Desktop, after I've gone through the initial sign up flow and added a repository, it's not clear to me what value GitHub Desktop offers me or what I should do next.

2. As a new user to GitHub Desktop, after I've gone through the initial setup, I'm landed on a page that gives me three buttons to add a repository, but doesn't help me through that process - which should I choose, what do they mean, is there one that I should likely be using?

Steps:

- [x] Initial design exploration
- [x] Implementation
- [x] Usability testing with small group of beginner users
- [x] Iterate
- [x] Release

**Comment by billygriffin** [comment]
This comment (https://github.com/desktop/desktop/issues/1688#issuecomment-303386625) stemming from this issue #5738 is likely worth examination. Thanks @cheshire137! 😄

**Comment by tierninho** [comment]
@niik Possible to post the mocks for this when ready? Thanks!

**Comment by niik** [comment]
> @niik Possible to post the mocks for this when ready? Thanks!

Sorry @tierninho, I didn't see this until now 🤦‍♂️. There are some screenshots over in #6365 and, you know, the real thing.

**Comment by shiftkey** [comment]
@billygriffin I've updated the checklist of issues now that #6445 has been merged, and I plan to put together a beta release with the last of our changes in there. Let me know if there's anything else that needs to be done as part of 1.6 for this, otherwise I'd like to close it out before the 🚢.

**Comment by shiftkey** [comment]
I'll defer to @niik on when it's good to close this out, given the last part of this feature just landed on `beta` today.

**Comment by billygriffin** [comment]
Since this is all merged into the release branch and ready to 🚢 tomorrow, gonna close it out!
