### ISSUE TITLE
Confusion between "Discard all changes" and "Discard changes" leading to unintentionally discarding all

### ISSUE THREAD

**Issue by bill1234567890abc** [desktop/desktop#5690]
Just now I wanted to discard one local file change. I opened the right mouse click and chose discard changes. Unfortunately I chose "discard all" because "discard one" is close to "discard all". I didn't have a careful look at confirmation dialog and confirmed the action. Then all work I have done today was discarded.

Thanks God. I restored them from recycle bin on windows. I guess I'm not the first that discard changes wrongly. 

My complain is that the two discard changes are too close and easily choose by mistake.

My idea is to separate them within an apparent distance.

Thanks,
Bill

**Comment by steveward** [comment]
Thanks for the feedback about this @bill1234567890abc. When you select `Discard all changes` a confirmation dialog appears that explicitly states the number of files that will have discarded changes, which should help reduce cases where all changes are accidentally discarded. However I can understand how this could be missed if you are assuming you clicked the correct option.

Would changing the title of the `Discard Changes` confirmation button to `Discard All Changes` be helpful in this scenario?

**Comment by Daniel-McCarthy** [comment]
I can certainly see the potential confusion here. I definitely see where changing the dialog title and/or button text can be useful.

Here are two possible iterations.

- Change dialog title & confirm button text.
![image](https://user-images.githubusercontent.com/4957200/46044338-1c9c1b00-c0e0-11e8-841b-1b1e321ff4a4.png)

- Change dialog title solely.
![image](https://user-images.githubusercontent.com/4957200/46044408-4b19f600-c0e0-11e8-81b1-75dcd9668cf9.png)

I think that at a bare minimum the dialog title should be changed as it is the largest and most apparent change. However, the button gives the user a final chance to notice.

**Comment by graemeworthy** [comment]
This has happened a few times, and the dialog doesn't seem to stop it from happening.

It seems like the context dropdown is the wrong place for this item.

Right clicking a file is for actions related to that file
Lets look at the rest of the items in that list 

|Action| Context|
|---|----|
|Discard Changes...| This file... destructive|
|Discard All Changes...| All Files... destructive|
|Ignore File| This file|
|Ignore All .js files | Project wide, using this file as an example|
|Reveal in finder | This file|
|Open in Atom| This file|
|Open with Default Program| This File|

**Comment by steveward** [comment]
Thanks for the feedback @graemeworthy. There is an discussion about improving the UX around the `Discard` functionality in https://github.com/desktop/desktop/issues/5342. I'm going to drop your feedback in there. I'm going to close this issue out since #5432 is discussing this further, and @Daniel-McCarthy shipped an improvement that helped assuage some of the confusion around this.

**Comment by billygriffin** [comment]
Thanks for dropping that in @steveward, I'm going to close this issue in favor of looking at it holistically in #5342.
