### ISSUE TITLE
improve handling merges with uncommitted changes in the working directory

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#5691]
**Please describe the problem you think should be solved**

This came up from a chat with @tierninho today and I wanted to use a similar, but different example.

I'm working on a feature branch and I want to pull in my `master` changes:

<img width="533" alt="screen shot 2018-09-20 at 11 38 13 am" src="https://user-images.githubusercontent.com/359239/45825977-def75680-bcc9-11e8-8fec-2e8fe59c7f44.png">

Do you think this will work?

<img width="616" src="https://user-images.githubusercontent.com/359239/45826000-e74f9180-bcc9-11e8-87a0-9388619ccd7e.png">

Oops, turns out I have some uncommitted changes already, and that clashes with other changes:

<img width="325" src="https://user-images.githubusercontent.com/359239/45826049-02220600-bcca-11e8-87f6-d0b42fbe834b.png">

Currently Git will stop the merge because it's trying to merge changes with these uncommitted changes, but other scenarios with working directory changes will work where the files changed don't clash with changes in the branch being merged in.

**Do you have any potential solutions in mind?**

Two initial ideas:

 - Blocking merges while there are uncommitted changes feels heavy-handed, but maybe that's an option?
 - For successful `git merge-tree` results we do get a list of files that are affected - if we find an entry that currently has uncommitted changes we could update the merge hint to block you from merging until you've committed that change. But that's extra work to replace what Git currently does when it performs (and fails) the merge.

**Comment by j-f1** [comment]
We could also do a stash.

**Comment by shiftkey** [comment]
We encounter this in #6075 while testing the new conflict resolution flow. Not sure whether we want to think about doing more here than What Git Does™.

**Comment by shiftkey** [comment]
Tagging this as `user-research` because I think it needs some fresh eyes and thoughts, rather than moving it straight to `enhancement`

**Comment by steveward** [comment]
We now stash when switching branches (when it's selected instead of bringing the changes), so this is no longer an issue. ✨
