### ISSUE TITLE
Prevent user from comparing branch A against branch A

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#5692]
This is normally prevented but there is an edge case scenario where you can compare branch A with branch A. 

Prerequisite: you must have an error message (eg. merge conflict) waiting to be triggered after step 3 is initiated. This can also be a NDDB prompt. Really just something that "disrupts" the logic.

Repro:
1. Select any branch from the branch tab
1. Select branch A from the compare list under History
1. Select branch A from the branch tab 

<img width="511" alt="screen shot 2018-09-20 at 8 29 50 am" src="https://user-images.githubusercontent.com/14828183/45830993-11e22000-bcb3-11e8-9d03-fb6ab19f9a49.png">

Note, this is more of a UI issue as there is not a real comparison of the two branches. When you click into the compare branch filter, it shows this correct response:

<img width="253" alt="screen shot 2018-09-20 at 8 57 01 am" src="https://user-images.githubusercontent.com/14828183/45831025-28887700-bcb3-11e8-99f5-4db381594caf.png">

1.4.1-beta0, mac

**Comment by iAmWillShepherd** [comment]
For anyone looking to take on this piece, start with the `BranchList` components. It may be easiest to add a new prop to `BranchList` or one of it's parent components that allows us to optionally pass a selected comparison branch that we can filter out of the branch list (or just disable it from being selected). The prop would have to be passed through from `App`, you can access the currently selected comparison branch by inspecting `ICompareState` in app state.

Also have a look at `CompareSidebar`->`componentDidUpdated` to see how `ICompareState` is used and how we keep track of the selected comparison branch.

**Comment by tierninho** [comment]
Too much of an edge case so closing for now.
