### ISSUE TITLE
Update stats reporting data structure

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#5695]
The current stats we submit are aggregated **before** being submitted to us. If  we want to answer more interesting questions, we need to increase the granularity of or metrics. 

## Current Stats
**Measures: Timers**
https://github.com/desktop/desktop/blob/e4754a27dc6f0a3a3a1e19ba8329f14784434dc4/app/src/lib/stats/stats-database.ts#L7-L25

**Measures: Counters**
https://github.com/desktop/desktop/blob/e4754a27dc6f0a3a3a1e19ba8329f14784434dc4/app/src/lib/stats/stats-database.ts#L28-L111

**Dimensions**
https://github.com/desktop/desktop/blob/e4754a27dc6f0a3a3a1e19ba8329f14784434dc4/app/src/lib/stats/stats-store.ts#L59-L91

These are composed to build the `DailyStats` type https://github.com/desktop/desktop/blob/e4754a27dc6f0a3a3a1e19ba8329f14784434dc4/app/src/lib/stats/stats-store.ts#L93

## Proposed Stats format
```json
[
    {
        "dimension": {
            "user_guid": "",
            "installation_guid": "",
            "event_type": "commit"
        },
        "measure": {
            "network_time": -1,
            "memory_usage": 8e+8
        }
    }
]
```

**Comment by billygriffin** [comment]
@desktop/analytics do you have any thoughts about this?

**Comment by telliott27** [comment]
To clarify, this is proposing moving from a daily aggregate metrics reporting to an event-based one, right? So we would generate a metrics package for each action we are tracking, with data about the action, and other context, and send that off to central?

I think ultimately this would be a good direction to go. It would make it easier to answer some of the questions we want to ask, and we can calculate better aggregate metrics, like the average spread per user of load times, commits per day, etc.

**Comment by iAmWillShepherd** [comment]
> To clarify, this is proposing moving from a daily aggregate metrics reporting to an event-based one, right?

Correct.

> So we would generate a metrics package for each action we are tracking, with data about the action, and other context, and send that off to central?

This is the goal. Right now, it seems like it will work, but we'll know for sure once it starts getting implemented.

**Comment by outofambit** [comment]
closing this until we're ready to come back to it
