### ISSUE TITLE
Discarding changes doesn't abort merge

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#5699]
## Description

If you discard all changes in the middle of a conflicted merge, the changes are discarded but the merge is not aborted.

## Version

* GitHub Desktop: 1.4.0

* Operating system: MacOS 10.13.6

## Steps to Reproduce

![merge-abort](https://user-images.githubusercontent.com/964912/45848642-18d55680-bce4-11e8-8d2b-e41b13cef0ef.gif)

### Expected Behavior

git status is normal
### Actual Behavior

git status says still merging
<img width="724" alt="screen shot 2018-09-20 at 2 41 36 pm" src="https://user-images.githubusercontent.com/964912/45848651-24c11880-bce4-11e8-870d-f4ca8fbaf955.png">

**Comment by iAmWillShepherd** [comment]
I think this is normal behavior of Git. I agree we should give the user the option to back out of a merge, but I don't think discarding files should cancel a merge implicitly. Maybe we could add a context-button for cancelling a merge due to conflict?

cc @desktop/product @desktop/core

**Comment by outofambit** [comment]
don't forget @desktop/design :)

**Comment by billygriffin** [comment]
@ampinsk is looking at this as part of the merge conflicts flow, so let's hold off on `help-wanted` for the moment. Definitely seems to me like this shouldn't be overlooked as part of that effort.

**Comment by ampinsk** [comment]
I do feel like I've run into the confusion of discarding my changes during a merge conflict and the app gives you errors with no way of aborting the merge. I'm looking at other ways to do this (signal that you're in the middle of resolving conflicts, giving you a way to get out of it) but we could address this in the meantime, just depends on timelines 😄

**Comment by outofambit** [comment]
fwiw this would develop some functionality we could reuse for the future abort merge flow
