### ISSUE TITLE
Increase height of the Commit Summary area to avoid the use of the Expand button

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#5700]
So the height of the `commit-summary-description-container` is not optimal. Although we created the shadow to let the user know there is more info below (see here 👇) 

https://github.com/desktop/desktop/blob/3756c147716a2f26729dd790a9cba6a4033fe232/app/styles/ui/history/_commit-summary.scss#L47

I think we ought to increase the height of this area by a few pixels to avoid the following scenario.)

Before user clicks expand:
<img width="1045" alt="screen shot 2018-09-20 at 3 42 20 pm" src="https://user-images.githubusercontent.com/14828183/45850941-27743b80-bced-11e8-8354-b3d663ded2ae.png">

After user clicks expand:
<img width="1047" alt="screen shot 2018-09-20 at 3 42 33 pm" src="https://user-images.githubusercontent.com/14828183/45850946-2d6a1c80-bced-11e8-81ca-75ff4047a575.png">

Literally, I clicked the `Expand` button to remove the shadow from the sentence. The latter pic seems like a reasonable minimal height... and if there is any text below then we should show the shadow. 

cc @desktop/design 

1.4.1-beta0, mac

**Comment by billygriffin** [comment]
@tierninho Thanks! It doesn't avoid the scenario altogether, it just avoids the scenario in the case of when there are exactly three lines, like your example and this one below:

<img width="875" alt="screen shot 2018-09-21 at 8 41 06 am" src="https://user-images.githubusercontent.com/5091167/45887963-23dac600-bd7a-11e8-894b-4f9819f1c85e.png">

However, when there are more than three lines or less than three, it works I think as people would expect. No matter what we choose to do here, there's going to be *a number of lines* where it starts being cut off. Is there something special about 3 that you think we should accommodate that?

For example, just having a summary and a co-author works just fine in the space allotted.

<img width="876" alt="screen shot 2018-09-21 at 8 44 21 am" src="https://user-images.githubusercontent.com/5091167/45888146-9ba8f080-bd7a-11e8-81a9-90ee8a220e36.png">

**Comment by tierninho** [comment]
@billygriffin thanks for the clarification

> No matter what we choose to do here, there's going to be a number of lines where it starts being cut off.

Good point. however 3 lines does seem like a better choice as it encompasses 'one line' descriptions and 'one line' worth of co-authors, which is important enough to be shown at first glance. Anything else, and we should use the expand button.

**Comment by billygriffin** [comment]
To make the "Expand" as obvious as it is at present, I'm not sure we could just expand the max-height by 3-4 pixels, but rather might have to expand it by another full line (or two?) to make it obvious to people that there is additional content and they can actually expand. I think that works quite well now at the third line without taking too much vertical space.

So the question would be whether making the exactly three line scenario work nicely is worth either confusion about there being more context if it's more than three lines or adding significantly to the vertical space.

**Comment by tierninho** [comment]
> To make the "Expand" as obvious as it is at present, I'm not sure we could just expand the max-height by 3-4 pixels, but rather might have to expand it by another full line (or two?) to make it obvious to people that there is additional content and they can actually expand. I think that works quite well now at the third line without taking too much vertical space.

I am curious if we can measure the amount of people going beyond 3 lines 🤔 . I would wager most are 3 or less, meaning it would be beneficial to just show the 3 lines unencumbered. 

> So the question would be whether making the exactly three line scenario work nicely is worth either confusion about there being more context if it's more than three lines or adding significantly to the vertical space.

Yes, there could be some confusion. I will default to you. I have no strong feelings either way.

**Comment by ampinsk** [comment]
Would it be possible to show the full message with no expand if it's just 3 lines? And then if it's >3 lines, still cut off at line 3, and expand to show lines 4+?

**Comment by ampinsk** [comment]
I think when it’s only 3 lines we can just show them. Then once it hits 4 lines, we still cap it at 3, show the shadow and the expand button, and expand to see lines 4+. This way, we only show the shadow when you’re actually going to be expanding to see more lines. Do we think that's technically feasible?

**Comment by outofambit** [comment]
@ampinsk I think so. @aryyya has done some similar work for the commit summary box recently. any thoughts @aryyya?

**Comment by aryyya** [comment]
@outofambit Thanks for bringing this to my attention!

I'm in agreement with @ampinsk.

This is a simple fix.
