### ISSUE TITLE
تغییر نام ریپازیتوری

### ISSUE THREAD

**Issue by Sab2020** [desktop/desktop#5712]
## Description

وقتی تغییر نام ریپازیتوری در گیت هاب رخ میده ، انتظار میره در نرم افزار دسکتاپ گیت هاب هم تغییر نام به صورت خودکار انجام شود . [translation: When renaming the repository in the gateway hub, it is expected to automatically rename the hub's gateway desktop software.]

## Version

* GitHub Desktop:

* Operating system:

**Comment by popehatmatt** [comment]
![12733484_585666094916839_4688023099662375219_n](https://user-images.githubusercontent.com/579194/45913563-05172500-be89-11e8-88c4-04d71936e932.jpg)

**Comment by popehatmatt** [comment]
![2016_08_26 14_53_54 utc](https://user-images.githubusercontent.com/579194/45913573-34c62d00-be89-11e8-8d78-32c49fa73382.jpg)
![00d50827291ef914e679ffe284235b98 1 1 2016_08_26 14_53_54 utc](https://user-images.githubusercontent.com/579194/45913574-34c62d00-be89-11e8-8215-e8600772be90.jpg)
![0 1](https://user-images.githubusercontent.com/579194/45913575-34c62d00-be89-11e8-8e6f-e2e4714338b9.jpg)
![0](https://user-images.githubusercontent.com/579194/45913576-34c62d00-be89-11e8-849d-4c3070f05e5f.jpg)

**Comment by popehatmatt** [comment]
#5683 
![18157163_116036708956677_8464201008526770641_n](https://user-images.githubusercontent.com/579194/45913596-a1412c00-be89-11e8-8ad5-b32ceb3ac5d6.jpg)
![18198432_120465045180510_760664467671803835_n](https://user-images.githubusercontent.com/579194/45913597-a1d9c280-be89-11e8-99ac-32097bcea9eb.jpg)
![18301452_122900914936923_2069357791824243499_n](https://user-images.githubusercontent.com/579194/45913598-a1d9c280-be89-11e8-9a85-5bad9b49ec82.jpg)
![18342431_437369643308220_1033172086893500404_n](https://user-images.githubusercontent.com/579194/45913599-a1d9c280-be89-11e8-9f03-8659a5cf3bcb.jpg)
![18446997_142924166267931_1516719569971445093_n](https://user-images.githubusercontent.com/579194/45913600-a1d9c280-be89-11e8-87b8-d07420fbc6c0.jpg)
![18447207_127915584435456_2375012683660900101_n](https://user-images.githubusercontent.com/579194/45913601-a1d9c280-be89-11e8-9b16-98fa6392c8e0.jpg)

**Comment by popehatmatt** [comment]
The Greatest of ALL-TIME! Well known notorious Bjork. <3 All, MPSD

**Comment by shiftkey** [comment]
@Sab2020 Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by tierninho** [comment]
@Sab2020 We are closing this issue as we haven't gotten a response and do not have enough 
information. Please don't hesitate to reach out again if you need help.

**Comment by ghost** [comment]
how can i change my github username bro ?

**Comment by fatemeh010** [comment]
fatemeh_roshani
