### ISSUE TITLE
Suggestion: Enter key focuses summary input

### ISSUE THREAD

**Issue by justingolden21** [desktop/desktop#5714]
### Simple Suggestion

I have a simple suggestion that would save many power users time when committing. The idea is that when in Github Desktop, if the user isn't focused on an input, pressing <kbd>Enter</kbd> would then focus the "Summary (required)" input, so the user can type their summary then press <kbd>Ctrl+P</kbd> to push without having to move the mouse.

A similar feature is implemented in Discord. It would be super simple to implement, just adding a keylistener for <kbd>Enter</kbd> and a conditional if the user is focusing an input. If there is some downside to having this feature that I'm not aware of, it could always be an option in settings to have it on or off.

Thanks for listening to my input 👍

**Comment by billygriffin** [comment]
Hi @justingolden21, thanks for the suggestion! That particular implementation we could see being confusing and introducing some unexpected behavior, but let me try to reframe the problem statement.

"As a power user of GitHub Desktop, I'm not able to quickly get to the commit input area without using my mouse."

I'm not *positive* this is a problem that a lot of people experience or if there's prior art here, so I'll let others weigh in.

**Comment by billygriffin** [comment]
Hi @justingolden21, we're tracking this in #1719 and I just added `help wanted` to that issue, so if the community wants to pick it up, we think that'd be great. Thanks!
