### ISSUE TITLE
Undo doesn't undo

### ISSUE THREAD

**Issue by andybak** [desktop/desktop#5716]
## Description

I accidentally committed too much stuff (probably should submit another ticket for your confusing commit UI but that's another story)

## Version
1.4.0

* GitHub Desktop:
Windows 10.

* Operating system:

## Steps to Reproduce
1. Commit too much
2. "Undo"

### Expected Behavior
My last action should undo

### Actual Behavior
No idea. Nothing happened as far as I could tell.

## Additional Information
1. An undo that doesn't is worse than no undo.
2. Undo should tell you what it's about to undo (Unity does a fairly good job of this for reference)
3. If in doubt disable undo. It should never be ambiguous what it's about to (un)do.

### Logs
n/a

**Comment by tierninho** [comment]
@andybak Please clarify if you are referring to the "Undo" button (see pic) or "Undo" in the Edit menu.

<img width="251" alt="screen shot 2018-09-24 at 7 29 59 am" src="https://user-images.githubusercontent.com/14828183/45958202-ab6b4380-bfcb-11e8-9130-b2c5182afd60.png">

If the former, the button will reverse your last commit, and all your files will again be shown in the Changes tab.

If the latter, here is an explanation: https://github.com/desktop/desktop/issues/1541#issuecomment-302059241

**Comment by andybak** [comment]
Yikes. That's crazy. Yes - I probably did either press Ctrl+Z or use the system menu item. It would never have occurred to me that there would be two different types of undo.

> I'm going to close this out as we classify this as expected behavior.

"Confusing and unintuitive behaviour we can't easily fix" is a not quite the same as "expected behaviour" as the latter implies that everything is right with the world.

Has there been any user testing of this to gauge it's real-world implications? I can imagine it causing unsuspecting users serious problems as it nearly did with me,

(UX issues can manifest themselves as data-loss bugs in the right circumstances. I believe Therac-25 was at least partially a UX problem...)

**Comment by outofambit** [comment]
Hi @andybak, thanks for the feedback! I can imagine that improving the discoverability of the commit undo functionality would have helped this case. I've captured that in the issue above (#5725). If you have any designs you'd like to propose (and that would be awesome!) or if you have other feedback you'd like to share let's continue there.

I'm going to close this issue in favor of that one for tracking purposes. Thanks again!
