### ISSUE TITLE
Repository not being recognized as part of "GitHub.com"

### ISSUE THREAD

**Issue by MiguelRipoll23** [desktop/desktop#5717]
## Description
Cloning certain repository using the GitHub.com "Open in Desktop" button clones the repository successfuly but it isn't part of "GitHub.com", appears as "Other" and trying to push changes will trigger the "Publish repository" dialog but it's already published.

## Version
* GitHub Desktop: 1.40
* Operating system: Microsoft Windows [Version 10.0.17134.285]

## Steps to Reproduce
1. [Clone this repository.](https://github.com/MiguelRipoll23/tusestimaciones)

### Expected Behavior
Repository appears as part of "GitHub.com" on the sidebar and changes can be pushed.

### Actual Behavior
Repository appears as part of "Other" on the sidebar and changes can't be pushed because it must be (re)published.

## Additional Information
[Repository that triggers this error.](https://github.com/MiguelRipoll23/tusestimaciones)

Check end of the logs file.

### Logs
[2018-09-23.desktop.production.log](https://github.com/desktop/desktop/files/2409234/2018-09-23.desktop.production.log)

**Comment by MiguelRipoll23** [comment]
@shiftkey If this issue isn't reproducible it means that it depends on my application data, I see a lot of previously deleted repositories still stored on the IndexedDB which I found quite weird, so some steps must be done in order to have some kind of "corrupted database" that will prevent a previously deleted repository to be cloned again correctly.

Maybe deleting the data from removed repositories would fix this issue, otherwise the necessary steps to trigger this error must be found.

**Comment by njbmartin** [comment]
This is what I am currently experiencing. Here's some steps I took that may help trace the issue:

1. Published a local repo to Github. For demo purpose, repo is called "demo".
2. renamed repo on github to "demo_old".
3. Created a new local repo with previous "name", and published.
4. Both repos in Github desktop show "demo_old".
5. Delete both from Github Desktop and re-clone. **Name still shows "demo_old"**
6. Delete again, and also delete "demo_old" from Github entirely, leaving just "demo".
7. Clone again... shows up as "demo". Yay! Oh, but it's classed as "other".

For me, "Fetch" does not do the animation or show status, Github logs a 404 error, but eventually it fetches and shows a pull is required. Click on Pull, and again no animation or status, but eventually pulls.

I have about 10 other repos that work fine while this behaviour is happening.

**Comment by njbmartin** [comment]
Identified the issue!

Opened up developer tools and found there was a network request to `https://api.github.com/repos/xxx/xxx` which was returning a `301` redirect (on disk cache), with a `Location` header set to `https://api.github.com/repositories/12345`

This is what was returning 404 as the repo it relates to no longer exists.


I **disabled cache**, and did a refresh... voila!
