### ISSUE TITLE
The desktop does not display after starting the program.

### ISSUE THREAD

**Issue by Niumeng1** [desktop/desktop#5733]
HI.
The program has been minimized, but it can not be solved in many ways.
![image](https://user-images.githubusercontent.com/21193895/45987547-bf36a880-c0a4-11e8-9365-d97fec082aac.png)

Thanks.
snowflake1

**Comment by shiftkey** [comment]
@Niumeng1 thanks for the report!

Could you attach the full log files?  These are the relevant locations on disk:

 - `%APPDATA%\GitHub Desktop\logs`
 - `%LOCALAPPDATA%\GitHubDesktop\SquirrelSetup.log`

This will provide some more information to help troubleshoot.

**Comment by Niumeng1** [comment]
@shiftkey thanks for your reply.
This problem has been solved, but local repository and cloned items have been lost.

**Comment by shiftkey** [comment]
> This problem has been solved, but local repository and cloned items have been lost.

I'm glad you're back to a happy place. I'm going to close this out,  but let me know if you have more information that might help troubleshooting the root cause.
