### ISSUE TITLE
loss of service to a local repository upon computer sleep

### ISSUE THREAD

**Issue by msftrncs** [desktop/desktop#5734]
## Description
Services to a local repository that is stored on a network share is lost if the computer goes to sleep or hibernates, or possibly with other network access issues.

## Version
* GitHub Desktop: 1.4.0
* Operating system: Microsoft Windows [Version 10.0.17763.1]

## Steps to Reproduce
Leave GitHub Desktop open on a repository that is stored on a network share (Windows Server 2012 R2) and then walk away and allow the computer to sleep and eventually hibernate.
Return to the computer and wake it up.

### Expected Behavior
I expect the state of GitHub desktop should return to normal (as was previous before the sleep), if not immediately, I expect it to try again (indefinitely until the user says otherwise) to locate the repository at the path it was last seen.

### Actual Behavior
You will find GitHub Desktop reporting 'Can't Find "repository"' along with a path to where it was last seen, and some buttons, 'locate...', 'clone' and 'remove'.

I restarted GitHub desktop, but it just came back up in the same state.  I tried pressing the 'locate...' button, but it took me to some other path way too far away (local system drive) to be worth the effort to navigate to.  I know the path exists because I still had Explorer windows open to the folder, and they are working fine, immediately after the awakening.  All other repositories are fine, even the ones on the same server share, so only the one that was open at the time the machine went to sleep is a problem.

### Logs
[2018-09-25.desktop.production.log](https://github.com/desktop/desktop/files/2413481/2018-09-25.desktop.production.log)

**Comment by msftrncs** [comment]
Apparently the repository became corrupt during the sleep event, locating it is doing no good.  The issue probably happens when the computer sleeps while GitHub has some uncommitted writes to the database.  Fortunately the repository was synced.

**Comment by msftrncs** [comment]
Additional, the database and the older seem to be intact, as GIT and VS Code operated repository just fine.

**Comment by shiftkey** [comment]
@msftrncs thanks for the report.

>  I know the path exists because I still had Explorer windows open to the folder, and they are working fine, immediately after the awakening. 

Once Desktop is unable to find the repository on disk, it'll stay in that "missing" state until being resolved. Anecdotally, we mostly see this "missing" flow occur when someone renames or deletes a folder on disk without updating Desktop. We've not talked about checking the location again to see if the folder is accessible again, which might help for scenarios like repositories on network shares, but I'm not sure how many of our users are working with this sort of setup.

> I restarted GitHub desktop, but it just came back up in the same state. I tried pressing the 'locate...' button, but it took me to some other path way too far away (local system drive) to be worth the effort to navigate to.

As a workaround, you can drag-and-drop the folder onto Desktop to re-add it. But this is an interesting bit of information, as we don't seem to use the old location at all when trying to relocate the repository:

https://github.com/desktop/desktop/blob/6a0eecfec29c1b4453fd002a071d0175cc037eb2/app/src/lib/dispatcher/dispatcher.ts#L782-L791

If we try and open Explorer to the parent directory where we last saw this repository, would that help make this flow easier? I'm also not sure how it'd work if the network share itself is unaccessible, but I suspect Windows will put you _somewhere_.

**Comment by msftrncs** [comment]
Just flagging that this issue is effectively a duplicate to #4264 which is in the `Available In Community` project.

**Comment by shiftkey** [comment]
@msftrncs thanks for the heads up. I'm going to cross-reference this issue there so we avoid carrying duplicates around.
