### ISSUE TITLE
Line endings change warning phrasing is backwards

### ISSUE THREAD

**Issue by fatcerberus** [desktop/desktop#5741]
## Description

The warning that line endings for a file have changed has it backwards, saying the file's line endings have change *from* "what it is now" *to* "what it was", instead of vice versa.  See screenshot below illustrating the problem.  This confused me for a bit when it first happened.

![lf-crlf](https://user-images.githubusercontent.com/4097841/46043452-13ae4800-c0e6-11e8-8d68-b83b86e3e58a.png)

## Version

* GitHub Desktop: 1.4.0

* Operating system: Windows 10 Pro x64 [10.0.17134.285]

## Steps to Reproduce

* Change the line endings of a file
* View diff in GitHub Desktop
* Note that change described in warning text is backwards

### Expected Behavior
The warning to say "Line endings have changed from 'CRLF' to 'LF'"

### Actual Behavior
The warning actually says "Line endings have changed from 'LF' to 'CRLF'"

**Comment by outofambit** [comment]
Thanks for the excellent bug report @fatcerberus! I'm gonna mark this so one of the maintainers can reproduce it locally and spec out a fix.

**Comment by tierninho** [comment]
This is reproducible on 1.4.1-beta1, mac. The file was saved as CRLF, but the warning said it was changed to LF.

Steps:
- Add new file to commit
- Use Atom to change the line ending, save
- The warning icon will appear with error msg

Note, this is a one way warning, as Unix is LF, and I changed it to CRLF. When I change it back the warning goes away as expected.

<img width="1425" alt="screen shot 2018-09-26 at 2 37 45 pm" src="https://user-images.githubusercontent.com/14828183/46111192-ea9bbf00-c19a-11e8-9003-a9b85dc8befa.png">

Good place to start if we assign this as `help-wanted`:
https://github.com/desktop/desktop/blob/1de8d45fc6dc3da6b7099c68f0d4a97c311bf972/app/src/ui/changes/changed-file-details.tsx#L54

https://github.com/desktop/desktop/blob/1de8d45fc6dc3da6b7099c68f0d4a97c311bf972/app/src/models/diff/diff-data.ts#L24

https://github.com/desktop/desktop/blob/1de8d45fc6dc3da6b7099c68f0d4a97c311bf972/app/src/lib/git/diff.ts#L324

**Comment by fatcerberus** [comment]
Based on that third line, it seems that it's deciding how to warn based on the message from `git diff`--a message which is itself pretty confusing.  Git's warning actually means something closer to "(CRLF|CR|LF) in the working tree will be replaced with (CRLF|CR|LF) in the repo when committed".  In other words it's not necessarily telling you that the file's line endings *changed* (although in practice this is usually the case), but rather that the line endings in the working tree simply don't match what Git has been configured to commit.

**Comment by fatcerberus** [comment]
FWIW it seems to be an impedance mismatch between Desktop and Git: Git is warning “I’m going to change the line endings when I make the commit” while Desktop is misappropriating that message to mean “the line endings have changed from what they were before”—which is not (necessarily) true.

**Comment by Dimas19812** [comment]
https://github.com/manga-download/hakuneko/issues/727#issue-530297708
