### ISSUE TITLE
Lack of import from old app remains barrier to entry

### ISSUE THREAD

**Issue by bdw429s** [desktop/desktop#5743]
I've used Github for Desktop for years now and installed the new version back when it first came out but was promptly disappointed when I realised I hadn't upgraded the app but merely installed a second software which contained none of my repos.  I set it aside and figured that if I waited a while, surely a proper import would be implemented.  I have hundreds of repos spread around my computer and have no interest in setting all that up again from scratch.

I finally got a chance to check back into this and was again disappointed to see that not only does a proper import from the old version of Desktop not exist, it has been asked for several times and either met with the instructions to simply re-create the setup from scratch, or the tickets left until a bot came along and closed them!  

Here are all the existing tickets I found.  They are all closed with no resolution, thus this new ticket.

https://github.com/desktop/desktop/issues/4600
https://github.com/desktop/desktop/issues/186
https://github.com/desktop/desktop/issues/1672
https://github.com/desktop/desktop/issues/1752
https://github.com/desktop/desktop/issues/2220
https://github.com/desktop/desktop/issues/4869

I really appreciate all the use I've gotten out of this (free) app over the years but find it surprising that a proper migration was never considered seriously, and even actively rejected by some members.  I appreciate that underlying technologies have changed from your perspective, but from my perspective as a user, I really don't care :)  This is just another upgrade like any other.  Like going from Chrome 68 to Chrome 69.  I don't want the old version around and I expect all my data to be in the new version.  If you changed underlying technologies I'm more than happy for you, but don't push the baggage onto me please.

I read through the other threads including one that had researching into what it would take to perform a seamless migration.  Surely this new version didn't sneak up on everyone, though.  I assume development was ongoing for months and at some point in time, the later releases of the old architecture could have easily exposed their data in a way readable by the upgrade.  How is it this caught everyone off guard?

If an automatic-migration is not going to be considered, please be upfront and state it here, don't just keep referring to other closed tickets like what happened on all the other threads.  I'm not a huge fan of your auto-close bot, who assumes any ticket not replied to must be resolved so I aim to keep this ticket alive until an answer can be reached one way or another lest others stumble across it, auto-closed in a few months, with no discernable resolution. 

Thank you for the considerations and I'm looking forward to finally having a seamless upgrade path from the latest version of this great tool.

**Comment by j-f1** [comment]
@shiftkey summarized the current situation pretty well in https://github.com/desktop/desktop/issues/186#issuecomment-389055403. Currently, you can bulk drag-and-drop your existing repositories onto the new app to add them.

**Comment by bdw429s** [comment]
@j-f1 Thanks for the reply, but as I mentioned, I've already read the other tickets and I'm not interested in another manual setup,.  In fact, I'm pretty sure I covered that above.  I entered this ticket for a resolution, not more workarounds and links to dead issues.

**Comment by bdw429s** [comment]
@billygriffin Thank you for the reply, for addressing the lock bot (which surely was responsible for several of the duplicate tickets on this topic including this one), and for clarifying your official intentions regarding a migration feature.  

I obviously disagree with your decision, but I appreciate the definitive answer.  It's been almost a year since I initially installed the new version and the vague but persistent hope of an eventual migration path is what prevented me from ever using it.  If I am to take your reply as a definitive and official "no" then I'll call off the wait and see what I can do to start a manual migration.  

@shiftkey I may take a stab at writing a script for automation, at least in terms of Windows/SQLite.  How would I go about finding the SQLite DB that is used?  I see a series of cache databases under `~/AppData/Local/GitHub` but nothing that seems to hold the main list of repos for the app.

**Comment by shiftkey** [comment]
@bdw429s I believe it was the `~/AppData/Local/GitHub/cache.db` file that we used to store settings like the tracked repositories. We used a library named [Akavache](https://github.com/reactiveui/Akavache) to interact with it from .NET, and Akavache has it's own way of storing the .NET objects - look for the `CacheElement` table that should contain the key-value pairs representing settings.

**Comment by bdw429s** [comment]
@billygriffin Yes, of course I would share it.  Since my axe of choice is CFML, I would release it as a CommandBox CLI Module on Forgebox.io so anyone could install it and run it from the command line.  But first I'll see if it's even doable.  

@shiftkey Thanks for the reply.  I did find that `cache.db` file and I did file the `CacheElement` table inside the `main` DB but as it seemed to just be a generic key/value pair thing I figured it wasn't what I wanted.  Is there any more insight you can provide on exactly what records in that table I'd need and the format they're in.  Dumping the entire table contents seems to include a lot of random stuff including binary data.

**Comment by shiftkey** [comment]
@bdw429s I believe it's these blobs that you want to parse. Akavache handles taking arbitrary .NET objects and serializes them to JSON before converting into a byte array:

https://github.com/reactiveui/Akavache/blob/54ba92ef7e8778ee0dbb947d4acf8c7a515df12b/src/Akavache.Core/JsonSerializationMixin.cs#L317-L321

**Comment by K6TD** [comment]
I would like to add my voice and comments to the above.  Not migrating my data on a new update is just plain poor practice.  I no longer have faith that I can update without having to do a bunch of work that seems pretty unnecessary.

Noting that users have lived with it for a year probably doesn't reveal the entire story.

At a minimum, let me open both version of the app and drag repos from one to the other.

 I have over 75 repos I keep track of (I do a lot of consulting work for IoT companies, and everyone of the them has their own repo for their special sauce software).  I’m also not too sure where the repos are on my MAC.  To be honest, I’ve used the GitHub desktop tool to keep track of where they are.  When I have to go back to a project, the first thing I do it - pull up the desktop tool and find where I stored the repo.

Please accept this as a request to migrate my repo listing from version to version.

**Comment by billygriffin** [comment]
Hi @K6TD, thanks for your thoughts, and I appreciate that it's not an ideal circumstance for you to migrate. We absolutely welcome someone diving into create a solution to this, but it's not something the team is going to devote resources to for the reasons stated previously in this issue. Thanks for understanding and apologies again for the inconvenience.

**Comment by K6TD** [comment]
Perhaps on install, you can very clearly state the existing repo list isn't migrated, it's a manual operation.  Also perhaps suggest to keep around the previous version of the desktop application, as it will help you find your repos on your local machine, helping with the drag and drop import.  Giving a notification results in a lot less surprise than just wondering what happen to my repo list.

I'd also comment - you should consider the value and trust aspect that has been reduced by taking this path.  When in the future when I install and update, only to find something such as this and the reason was - too hard to take on.

Thanks for reviewing my comments.

**Comment by billygriffin** [comment]
> I'd also comment - you should consider the value and trust aspect that has been reduced by taking this path. When in the future when I install and update, only to find something such as this and the reason was - too hard to take on.

That's completely fair, and we absolutely will. Since this is a one time migration and because the vast majority of folks have already migrated, the marginal impact of this would be relatively small when compared with continuing to improve how the new application serves our users. I understand your frustration and it's something we'll be mindful of going forward.

**Comment by K6TD** [comment]
Thanks.  I've actually dug into this a lot more, for OSX.  It's a huge pain, and I now agree with your reasoning and answer.  I owe you an apology as well.  I apologize.

FWIW - I found a two step process to manually migrate a repo over - in the old app, right click, select show in finder.  In the finder window that pops up, drag the repo to the new app.  Best done on a pair of side by side monitors, to keep the src and dest sorted out.

Alas, as I started doing this, I realized a fair number of the repos were out of date, or no longer mattered, and I found a few changes that I hadn't either pushed, or done pull request for.  

The sliver lining for me is - forced me to sort out a neglected mess.

Thanks again.

KR

**Comment by billygriffin** [comment]
@K6TD Thanks for the thoughtful reply and for describing the migration strategy you found most useful so others might benefit from it. As you get up to speed using the new Desktop, we're super open to feedback so please let us know if you find anything confusing or frustrating (or particularly useful - that helps too!).

**Comment by billygriffin** [comment]
Hi folks, given the significantly diminished number of people using the old apps and the discussion above, I'm going to close this issue to indicate that we don't intend to build an automated migration tool at this point. Thanks to everyone for weighing in, and it would be great if anyone is able to figure out a path to do so as described above if you'd share it out. Thanks again.
