### ISSUE TITLE
UI is broken for Terms and Conditions &  Open Source and License Notices

### ISSUE THREAD

**Issue by agisilaos** [desktop/desktop#5756]
## Description

When you visit Terms and Condition or/and License notices panels/pop-ups the UI is broken.

## Version
* GitHub Desktop: 1.4.2-beta0
* Operating system: v10.14, macOS Mojave

## Steps to Reproduce
1. Click on the Github Desktop menu
2. Click on About Github Desktop menu 
3. Click on Terms and Conditions and/or License and Open Source Notices

### Expected Behavior
The text shouldn't be outside of the box/panel are and the content should be scrollable

### Actual Behavior
The text is outside of the box/panel area and the content isn't scrollable.

## Additional Information
<img width="1392" alt="screenshot 2018-09-26 at 23 54 41" src="https://user-images.githubusercontent.com/10944108/46109242-a9ca9700-c1e8-11e8-98a9-010d3c39fefd.png">
<img width="1392" alt="screenshot 2018-09-26 at 23 54 59" src="https://user-images.githubusercontent.com/10944108/46109243-aa632d80-c1e8-11e8-9cdb-a4aabba13277.png">

**Comment by outofambit** [comment]
thank you for filing this @agisilaos! I reproduced it on `1.4.1` too. 😞
