### ISSUE TITLE
All my information on my pc and phone are always changing and possible watched at all times . I'm pretty sure its my business partner but cant prove . I have a windows 10 and we are all on the same network at our office but all my files with passwords are always getting opened and changed , as well as my phone S9 + Android.. the pc is a intel pentium G4560t 400. GB. If anyone can help figure out how to stop or even prove who doing it please let me know thanks.

### ISSUE THREAD

**Issue by BM2830** [desktop/desktop#5759]
## Version

* GitHub Desktop:

* Operating system:

**Comment by BM2830** [comment]
I don't know much about computer's or fixing phones so I am willing to pay for someone to help.

**Comment by njbmartin** [comment]
This is definitely not an issue related to Github Desktop.

**Comment by shiftkey** [comment]
@BM2830 this issue tracker is for the GitHub Desktop application. If you need help with GitHub, please reach out to [GitHub Support](https://github.com/contact).
