### ISSUE TITLE
Zoom-State resets when updating

### ISSUE THREAD

**Issue by pkunze** [desktop/desktop#5761]
One of the things I love most about GH Desktop is the abilitiy to increase the size of fonts/elements (View &rarr; Zoom in). 

Whats great is that I do not have to zoom in everytime I (re-) open GH Desktop. Unfortunately, installing an updated version resets the zoom state to the defaults. 

Minor issue but still a little itch I always experience after installing an otherwise better version of GH Desktop ;)

**Comment by steveward** [comment]
Thanks for the report @pkunze! This was reported in https://github.com/desktop/desktop/issues/5315, so I am going to close out this issue as a duplicate. Please follow along in #5315 for updates.
