### ISSUE TITLE
Github desktop is crashed when it start up

### ISSUE THREAD

**Issue by Wzy-CC** [desktop/desktop#5763]
## Description

I cannot open GitHub desktop, and it has this question:</br>
![bug](https://user-images.githubusercontent.com/26458757/46144200-ce794a00-c28e-11e8-93bc-327da313e3aa.PNG)</br>
Before this question occur, the desktop can not located the repositories (of course I do nothing),and when I try to located repositories in my computer it will failed(no screenshot)

## Version

* GitHub Desktop:
1.4.1.0:</br>
![bug2](https://user-images.githubusercontent.com/26458757/46144608-092fb200-c290-11e8-827e-f8d4877a54ee.PNG)

* Operating system:
Microsoft Windows [版本 10.0.17134.285]
version:10.0.17134.285

## Steps to Reproduce

1.install GitHub desktop

2.do some work and spent much time on it

3.Suddenly crashed out and shocked me

4.in fact I think I just deleted a branch on GitHub classroom(I don't think it is related)

### Expected Behavior

GitHub desktop works well
### Actual Behavior

but it crashed down

## Additional Information

I AM A FRESHMAN OF GITHUB,SO IF THERE ARE SOMEWHERE I DONT UNDERSTAND OR MY ACTION IS NOT RIGHT,PLEASE FORGIVE ME AND GIVE ME SOME ADVICE(I TRY MY BEST TO EXPRESS MY VIEW ALTHOUGH IT MAY AMBIGUOUS AND VAGUE,I AM A CHINESE STUDENT NOT SKILLED FOR ENGLISH)

**Comment by steveward** [comment]
@Wzy-CC I'm glad to hear that a reinstall got things working again, and thank you for sharing the log file. I see a few errors in the log file, but nothing that appears to be directly related to the crash. I'm going to close this issue out, but please don't hesitate to reach out if you encounter any further issues.
