### ISSUE TITLE
remove --detectOpenHandles flag from jest

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#5770]
`--detectOpenHandles` gives us a 30% slowdown in node 8. 😢https://github.com/desktop/desktop/pull/5528#discussion_r215888601

need to wait for completion of facebook/jest#6950 before we can remove it safely though, (though that may not be entirely true) ping @outofambit for more info

**Comment by outofambit** [comment]
this will involve:
- update jest to version where the above PR is released
- removing the `--detectOpenHandles` flag from the test npm script in `package.json`
- running tests to ensure everything still passes (locally and on CI by opening a PR)
- profit 🤑

**Comment by shiftkey** [comment]
This looks like it'll be ready to go whenever Jest 24 is released (currently there are some alpha builds with it available).

**Comment by shiftkey** [comment]
Looks like this was landed in https://github.com/facebook/jest/pull/7074 but then reverted in https://github.com/facebook/jest/pull/7259 because of unexpected side effects. Not sure what the next steps are to this 🤷‍♂️
