### ISSUE TITLE
Potentially unclear during onboarding what version of Desktop I'm using

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#5771]
The`About GitHub Desktop` menu item is disabled when the user is onboarding. We should enable it so the user can easily see which build version they are using. 

However, the top-level menu is not present on Windows until *after* onboarding. As such, a text based approach i/o a menu change seems more practical. Thoughts, opinions, etc...?

Mac/Darwin: About is under the `GitHub Desktop` menu
Windows/WIN: About is under the `Help` menu

<img width="931" alt="screen shot 2018-09-27 at 11 08 41 am" src="https://user-images.githubusercontent.com/14828183/46165550-c517bf80-c245-11e8-8871-a9d6945ae9e0.png">
<img width="469" alt="screen shot 2018-09-27 at 10 54 21 am" src="https://user-images.githubusercontent.com/14828183/46165558-ca750a00-c245-11e8-820e-fd046d26fd0a.png">

Good place to start:
https://github.com/desktop/desktop/blob/4460c484508d8467db615f903c47f0f4c914126b/app/src/main-process/menu/build-default-menu.ts#L28

Tip: in order not to blow away your current repos in Desktop, you can access the onboarding pages by changing this to `0`:
<img width="774" alt="screen shot 2018-09-27 at 11 02 22 am" src="https://user-images.githubusercontent.com/14828183/46165222-f9d74700-c244-11e8-93f5-b1b88f4b75e7.png">

**Comment by shiftkey** [comment]
@tierninho 

> Windows/WIN: About is under the Help menu

The menu is not visible when using the Welcome Wizard on Windows

<img width="985" alt="screen shot 2018-09-27 at 3 30 58 pm" src="https://user-images.githubusercontent.com/359239/46166796-6c0e5280-c26a-11e8-9aef-0a9c48de7900.png">

Also, there are already ways to find the version installed without needing to launch the app:

<img width="822"  src="https://user-images.githubusercontent.com/359239/46166830-834d4000-c26a-11e8-989a-1131e1ce8e44.png">

<img width="278" src="https://user-images.githubusercontent.com/359239/46166854-93fdb600-c26a-11e8-890e-5a524032214a.png">

**Comment by tierninho** [comment]
@shiftkey Yes, there are ways to find out, but the novice may not know how to inherently do that. 

Also, I mentioned this, so perhaps it's an alternative if we decide to implement anything:

> However, the top-level menu is not present on Windows until after onboarding. As such, a text based approach i/o a menu change seems more practical.

**Comment by shiftkey** [comment]
Is the issue just that the version isn't visible to the user when they start the welcome wizard?

I'm trying to wrap my head around the value here, because we could do something like embed the version on that first page if it's really important. This version also gets embedded in logs, so we have plenty of place to grab this info already:

```
2018-09-27T18:30:24.500Z - info: [ui] [AppStore] loading 5 repositories from store
2018-09-27T18:30:25.034Z - info: [ui] launching: 1.4.1 (Windows 10.0.17134)
```

**Comment by tierninho** [comment]
> Is the issue just that the version isn't visible to the user when they start the welcome wizard?

yes, correct

> if it's really important...

Don't think so, just an minor enhancement. If you feel the value doesn't outweigh the effort, feel free to close the issue or we can assign to the open contributors. I'm open either way.

**Comment by shiftkey** [comment]
I'll let @desktop/maintainers and @desktop/comrades sound off on this too

**Comment by j-f1** [comment]
How about a light gray “About GitHub Desktop” link tucked away in a corner of the welcome wizard?

**Comment by billygriffin** [comment]
This feels small enough to address in context of #5686 as we look at onboarding more holistically (linked it so it'd be captured there). Does that seem reasonable?

**Comment by tierninho** [comment]
Yes, indeed. Not sure if I should close it or not...
