### ISSUE TITLE
Onboarding buttons are backwards

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#5772]
The Desktop onboarding process in the Welcome flow currently shows multiple forms, each with the primary action button (blue one) on the left, and secondary button on the right. This is opposite of the rest of the app, which has the primary action button on the right and secondary button on the left (unless it is a destructive action).

1) Github.com sign-in
2) Enterprise sign-in
3) Git sign-in
4) Stats agreement

<img width="456" alt="screen shot 2018-09-27 at 1 47 03 pm" src="https://user-images.githubusercontent.com/14828183/46173691-dd92d480-c25b-11e8-813f-70bf80f2cc82.png">
<img width="552" alt="screen shot 2018-09-27 at 1 43 42 pm" src="https://user-images.githubusercontent.com/14828183/46173692-dd92d480-c25b-11e8-8757-5b8077e557c2.png">
<img width="540" alt="screen shot 2018-09-27 at 1 43 29 pm" src="https://user-images.githubusercontent.com/14828183/46173693-dd92d480-c25b-11e8-92d9-ff09acc4b00c.png">
<img width="546" alt="screen shot 2018-09-27 at 1 43 22 pm" src="https://user-images.githubusercontent.com/14828183/46173694-dd92d480-c25b-11e8-82b7-ff128b86eedd.png">

Original convo around button order: https://github.com/desktop/desktop/issues/1311

Can a @desktop/maintainers confirm this change?

**Comment by billygriffin** [comment]
We're looking at the entire onboarding experience in https://github.com/desktop/desktop/issues/5686 so just wanted to make sure this was linked in that issue.

**Comment by tierninho** [comment]
Closing this issue for now in light of ⬆️
