### ISSUE TITLE
License terms expand past modal, un-scrollable

### ISSUE THREAD

**Issue by jimgraham** [desktop/desktop#5774]
## Description
The text in the OSS licenses and also the terms overflows the modal window

## Version
* GitHub Desktop: 1.4.1
* Operating system: mac osx 10.13.6 High Sierra

## Steps to Reproduce

1. Click "About GitHub Desktop"
2. In modal dialog, click either "License and Open Source Notices" or "Terms and Conditions'

Text overflows the modal, and is neither readable nor scrollable

![image](https://user-images.githubusercontent.com/430293/46210811-cc9b9f00-c2ff-11e8-82d0-f434979fad0f.png)

### Expected Behavior

I can read all the terms & licenses in the modal window. Text scrolls within bounds of the window.

### Actual Behavior

I can't read the bulk of the text.

**Comment by tierninho** [comment]
@jimgraham thanks for filing. We addressed this here: https://github.com/desktop/desktop/issues/5756
