### ISSUE TITLE
Suggestion: Add UI treatment to default and protective branches

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#5776]
Enhancement suggestion: As it can be unclear to the user that the current branch they are working on is the default or a protective branch, I suggest we show a `default` badge next to the respective branch name in the below pic. Alternatively, we could change the text color.

<img width="245" alt="screen shot 2018-09-28 at 9 28 46 am" src="https://user-images.githubusercontent.com/14828183/46223205-919d6980-c307-11e8-8231-dc575751d22b.png">

Also, we should have a 🔒icon or similar to respective protected branches. No UI treatment currently exists for this... instead we get a over-the-top error message [like so](https://github.com/desktop/desktop/issues/4482). (Note, this could co-exist with the `default` badge, btw.)

Why do it? To add an extra layer of communication to the state of each branch being worked on by the user.

**Comment by tierninho** [comment]
@billygriffin Thanks for the helpful feedback on this issue. 

1. A bit of an edge case in my reasoning for the default badge. The badge would be beneficial to those who have named their default branches something ambiguous. The badge would serve as a reminder that the commits are going to the default branch, and to others new to the repo. I agree, that this change doesn't have a strong business case.

2. Yes, the protected branch icon is obvious, and would be useful to reduce pain later on. I'll leave the decision to the team.

**Comment by billygriffin** [comment]
I'm going to roll this into #4482 as I think they shouldn't be considered in isolation. The primary question we want to answer is how we deal with protected branches and ensuring that Desktop users have the information they need to be successful (both in getting the right error messages and in not getting into a painful place in the first place).
