### ISSUE TITLE
"Publish branch" modal window's default button doesn't work as default

### ISSUE THREAD

**Issue by mdiep** [desktop/desktop#5777]
## Description
When you try to open a PR for an unpublished branch, a modal window is show. If you press _return_ on your keyboard, the cancel button is used instead of the publish branch (which has a default button treatment).

<img width="462" alt="publish-branch" src="https://user-images.githubusercontent.com/1302/46228293-a5f55c80-c32f-11e8-99eb-376a0ea92baf.png">

## Version
* GitHub Desktop: 1.4.1
* Operating system: macOS 10.14

## Steps to Reproduce
1. Create a new branch
2. Commit some changes
3. Press Cmd-R to open a PR
4. Press _return_

### Expected Behavior
Default button (_Publish Branch_) should be used

### Actual Behavior
_Cancel_ button is used

**Comment by outofambit** [comment]
Hi @mdiep thank you so much for the excellent bug report! We've been discussing issues like this recently. @desktop/design can you weigh in on this case?

**Comment by billygriffin** [comment]
Thanks @mdiep! @outofambit This is perfectly characterized as a bug in the description. We use "Cancel" as the default button for destructive actions, and otherwise the normal button should be used (it's also the blue button which is the visual indication).

**Comment by JKirkYuan** [comment]
**UPDATE**: So for dialogs like `create-branch-dialog` or `rename-branch-dialog`, the autofocus goes onto the input element so on `Enter` it will click on the button with `type="submit"`. For some reason, `delete-branch-dialog` and `push-branch-commit` seem to autofocus on the first button element. 

Temporarily got it working by using a `onButtonRef` pointing to the *Publish Branch* button element, let me know if that's alright to do! 🙌

**Comment by billygriffin** [comment]
@JKirkYuan I'm not sure about `push-branch-commit` but for the other three you mentioned, that sounds correct (delete is a destructive action and therefore should respect the "Cancel" button on `Enter`, regardless of the placement of it).

cc: @desktop/engineering as well as I can't speak to the implementation question

**Comment by outofambit** [comment]
@JKirkYuan this is great research. thank you!

could you open a WIP PR with the `onButtonRef` solution so I could see what that looks like? feel free to @ mention me in it so I see it right away. :)
