### ISSUE TITLE
Text selection in popup window text fields when cursor is out of popup (bug)

### ISSUE THREAD

**Issue by embick** [desktop/desktop#5786]
## Description

When text in a text field in a popup window is selected by click and drag, and the mouse pointer is dragged outside the bounds of the popup window, the selected text behaves as if the text field was positioned relative to the GitHub Desktop window instead of the popup window. **See illustration below.**

## Version

* GitHub Desktop:
Version 1.4.1

* Operating system:
Microsoft Windows [Version 10.0.17134.285]

## Steps to Reproduce

1. Open any popup window with a text field (e.g. File > New repository, Repository > Repository settings, Branch > New branch)
2. Type some text in any text field in the popup window
3. Click and drag to select some of the text, and keep holding the mouse down
4. Move the cursor outside of the bounds of the popup window
5. Keeping the cursor outside the popup window, move it toward the left edge of the GitHub Desktop window, and observe unusual text selection

### Expected Behavior

When the cursor is dragged (left|right)ward past the bounds of the popup window, either none of the text in the text field is selected, or all the text to the (left|right) of the cursor's original mark position remains selected. The latter is preferred - that is, the text selection on the text field simply shouldn't care that the cursor is outside the popup window that contains the text field, it should just keep using the cursor's position to determine what text is selected.

### Actual Behavior

When the cursor is dragged outside the bounds of the popup window, the text selection behaves as if the text field's X position was relative to the left edge of the Github Desktop window instead of the left edge of the popup window, despite not actually being there. I say this because these distances are the same:
a) from the left edge of the popup window, to the mark point in the text field where the cursor was initially clicked to start dragging
b) from the left edge of the GitHub Desktop window, to the point where the strange text selection behavior would imply the mark point actually was

## Additional Information

Illustration:
![2018-09-29_23-55-10](https://user-images.githubusercontent.com/26918079/46253196-45efda80-c443-11e8-9cb4-1139ec6be415.gif)

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue the GIF was super helpful! 🙇

**Comment by iAmWillShepherd** [comment]
I've tested this on other text fields and noticed this behavior is consistent across all of them whether it's in a dialog or the main window.

**Comment by billygriffin** [comment]
I think this is fixed in https://github.com/desktop/desktop/pull/8547 so I'm going to close this.
