### ISSUE TITLE
Dragging the mouse quickly while in word select mode causes a crash

### ISSUE THREAD

**Issue by pbfy0** [desktop/desktop#5790]
## Description

When viewing a diff, entering word select mode by double clicking and dragging on the diff, then dragging the mouse quickly between between the diff and parts of the frame around it eventually results in a crash.

This crash sometimes takes 5-10 seconds of fervent dragging to trigger. If the crash doesn't happen during that timeframe, try deselecting and starting by selecting a different word. I've been able to crash the program every time within one or two tries.
## Version

* GitHub Desktop: 1.4.1

* Operating system:
Windows 10 (10.0.17134)

## Steps to Reproduce

1. Open a diff (easiest to trigger the crash in Changes view)
2. Enter word select mode in the diff by double-clicking a word and holding
3. Rapidly drag the mouse back and forth between the diff and other UI elements outside of the diff view (I've been able to reproduce by moving between the left pane and the diff, as well as by moving between the top pane and the diff.)

### Expected Behavior

GitHub Desktop displays rapidly changing selection and does not crash
### Actual Behavior

GitHub Desktop crashes

### Logs

```
TypeError: Cannot read property 'find' of undefined
    at a (app\node_modules\codemirror\addon\selection\mark-selection.js:97:1)
    at C:\Users\Paul\AppData\Local\GitHubDesktop\app-1.4.1\webpack:\app\node_modules\codemirror\addon\selection\mark-selection.js:38:44
    at _o (app\node_modules\codemirror\lib\codemirror.js:3865:1)
    at na.operation (app\node_modules\codemirror\lib\codemirror.js:8532:28)
    at t (app\node_modules\codemirror\addon\selection\mark-selection.js:38:1)
    at Rt (app\node_modules\codemirror\lib\codemirror.js:2107:12)
    at kt (app\node_modules\codemirror\lib\codemirror.js:2116:36)
    at go (app\node_modules\codemirror\lib\codemirror.js:3738:1)
    at HTMLDocument.<anonymous> (app\node_modules\codemirror\lib\codemirror.js:3875:32)

Version: 1.4.1
OS: Windows 10.0.17134
```

**Comment by j-f1** [comment]
Norepro on macOS.

**Comment by billygriffin** [comment]
@pbfy0 Thanks so much for the report! This feels like something where someone has to do some extremely unusual behavior in order to get the app to crash. I'm going to go ahead and close it as we don't expect people to be doing this sort of intense dragging in the app.
