### ISSUE TITLE
About GitHub Desktop

### ISSUE THREAD

**Issue by luchinhsun** [desktop/desktop#5791]
I have used GitHub before, it told me to install GitHub Desktop recently, so I did, but the GitHub Desktop can't detect my all repositories which I already clone when I used GitHub before.
I think it's a problem that should be fixed, right?
or there is something I didn't do?
I think it should detect the repositories I already clone.
P.S. the path is same

**Comment by Daniel-McCarthy** [comment]
Hello there.
That is correct that the electron GitHub Desktop program does not automatically import repositories previously used in the GitHub Desktop classic program.

More information on this can be found in Issue #5743.
It may be worth noting that you can drag and drop your current repositories onto the electron program to add them. I understand this is not a perfect replacement, especially if you have repositories in several locations.

However, in the above Issue, someone is looking into an automated solution for this. Perhaps in time it will be available for users in your situation.

**Comment by billygriffin** [comment]
Thanks @luchinhsun for the issue, and thanks so much for the quick response @Daniel-McCarthy! ❤️ 

What @Daniel-McCarthy said is all correct, so I'm going to go ahead and close this issue.
