### ISSUE TITLE
Github Desktop mess with x-github-desktop protocol

### ISSUE THREAD

**Issue by oktonion** [desktop/desktop#5792]
## Description
Cloning process with 'Open In Desktop' from browser is not starting.

## Version

* GitHub Desktop:
1.4.1
* Operating system:
Windows 7 x64

## Steps to Reproduce
Launch 'Open In Desktop' for any repo
GitHub Desktop shows up
Nothing happens

### Expected Behavior
Cloning process

### Actual Behavior
Nothing happens

## Additional Information
I'm reopening the issue since #5324 was closed and there is definitely something wrong with URI for x-github-desktop protocol.

Since [electron protocol CVE](https://medium.com/0xcc/electrons-bug-shellexecute-to-blame-cacb433d0d62) was discovered and fixed with: 
https://github.com/desktop/desktop/blob/7e9f40403be55d89b18a430f5bd3407eeafc8b54/app/src/main-process/main.ts#L139-L151
GitHub desktop requires arguments to be passed as
`"GitHubDesktop.exe" --protocol-launcher -- "x-github-client://openRepo/https://github.com/blablablalala"`

To enforce that behaviour in Windows there is a [documented](https://docs.microsoft.com/en-us/windows/desktop/lwef/-search-2x-wds-ph-install-registration) way. Summary of it will be following:
```
For example, to associate alert: protocol to alert.exe, create following registry keys:

HKEY_CLASSES_ROOT
   alert
      (Default) = "URL:Alert Protocol"
      URL Protocol = ""
      DefaultIcon
         (Default) = "alert.exe,1"
      shell
         open
            command
               (Default) = "C:\Program Files\Alert\alert.exe" "%1"
```

For security reasons with electron protocol the command string should be
`(Default) = "C:\Program Files\Alert\alert.exe" --protocol-launcher -- "%1"`

So I assume there should be the same registry key in my Windows x64 workstation with additional '--protocol-launcher' and '--' there, like:
```
HKEY_CLASSES_ROOT
   x-github-client
      (Default) = "URL:x-github-client"
      URL Protocol = ""
      DefaultIcon
         (Default) = "GitHubDesktop.exe,1"
      shell
         open
            command
               (Default) = "C:\Users\User\AppData\Local\GitHubDesktop\GitHubDesktop.exe" --protocol-launcher -- "%1"
```
 But there is not! Instead what I have is following:

- HKEY_CLASSES_ROOT\x-github-client\shell\open\command\(Default) = "C:\Users\User\AppData\Local\GitHubDesktop\app-1.4.1\GitHubDesktop.exe" --protocol-launcher "%1"
- HKEY_CLASSES_ROOT\x-github-desktop-auth\shell\open\command\(Default) = "C:\Users\User\AppData\Local\GitHubDesktop\app-1.4.1\GitHubDesktop.exe" --protocol-launcher "%1"
- HKEY_CURRENT_USER\Software\Classes\x-github-client\shell\open\command\(Default) = "C:\Users\User\AppData\Local\GitHubDesktop\app-1.4.1\GitHubDesktop.exe" --protocol-launcher "%1"
- HKEY_CURRENT_USER\Software\Classes\x-github-desktop-auth\shell\open\command\(Default) = "C:\Users\User\AppData\Local\GitHubDesktop\app-1.4.1\GitHubDesktop.exe" --protocol-launcher "%1"
- HKEY_LOCAL_MACHINE\SOFTWARE\Classes\x-github-client that is empty
- HKEY_USERS\S-1-5-21-1186505040-3499372643-3030342882-1000\Software\Classes\x-github-client\shell\open\command\(Default) = "C:\Users\User\AppData\Local\GitHubDesktop\app-1.4.1\GitHubDesktop.exe" --protocol-launcher "%1"
- HKEY_USERS\S-1-5-21-1186505040-3499372643-3030342882-1000\Software\Classes\x-github-desktop-auth\shell\open\command\(Default) = "C:\Users\User\AppData\Local\GitHubDesktop\app-1.4.1\GitHubDesktop.exe" --protocol-launcher "%1"
- HKEY_USERS\S-1-5-21-1186505040-3499372643-3030342882-1000_Classes\x-github-client\shell\open\command\(Default) = "C:\Users\User\AppData\Local\GitHubDesktop\app-1.4.1\GitHubDesktop.exe" --protocol-launcher "%1"
- HKEY_USERS\S-1-5-21-1186505040-3499372643-3030342882-1000_Classes\x-github-desktop-auth\shell\open\command\(Default) = "C:\Users\User\AppData\Local\GitHubDesktop\app-1.4.1\GitHubDesktop.exe" --protocol-launcher "%1"

The reasons GitHub desktop is not working:

1. Is **not** Firefox or any other browser handling of x-github-client protocol.
2. There is definitely missed second argument '--'. It's the main reason.
3. There is hell more registry keys then it should be.
4. That keys are refreshed at every launch of GitHub Desktop so I assume the GH Desktop is rewriting it with the wrong string.
5. It seems wrong that there are multiple versions of GitHubDesktop.exe and especially that 'app-1.4.1' version is used instead of 'GitHubDesktop.exe' in root folder '...\\AppData\\Local\\GitHubDesktop\\...'

**Comment by iAmWillShepherd** [comment]
Thanks for the super detailed issue and thorough analysis of the root cause! 😃

**Comment by oktonion** [comment]
@iAmWillShepherd I had a quick look at codebase for up-to-date master and it seems now
https://github.com/desktop/desktop/blob/07f354771b42f218e3c0de2395846576952bef1d/app/src/main-process/main.ts#L139
GH Desktop has changed the cmd line arguments since issue #5324 was discussed. So I'm a bit confused with what is happening. But it still is not working with firefox and Windows 7. So n.1, n.2, n.4 are questionable and should be investigated more, my bad. 

In my understanding the root of the problem is that Firefox would pass arguments with extra parameters only if Application is registered as default handler for x-github-... protocols in Windows and GH Desktop is doing this somehow wrong from firefox stand point. 

n.3, n.5 are still relevant 100% tho.

**Comment by iAmWillShepherd** [comment]
@ oktonion,

Sorry for the delay on this, I'm not that familiar with Windows so I had to do a bit soul searching to parse this. Do the following points summarize your issue correctly? I also included a couple of questions of my own.

1. HKEY_CLASSES_ROOT: `command(Default)` should be `...GitHubDesktop.exe" --protocol-launcher -- "%1"`
1. HKEY_CURRENT_USER: `command(Default)` should be `...GitHubDesktop.exe" --protocol-launcher -- "%1"`
1. HKEY_LOCAL_MACHINE: registry key should not be empty, unsure what it should be at the moment. Would you happen to know the correct values?
1. HKEY_USERS: There is twice as many registries than there should be. I think that's wrong, but I'm not sure which registry item is right: `...\Software\Classes\[x]\...` **or** `..._Classes\[x]\...`?

I had to format your issue a bit to aid in my understanding. Posting it here so it's easier for others to get up to speed.

#### HKEY_CLASSES_ROOT

_Contains file name extension associations_

**x-github-client**

```
HKEY_CLASSES_ROOT
  x-github-client
    shell
      open
        command(Default) = "C:\Users\User\AppData\Local\GitHubDesktop\app-1.4.1\GitHubDesktop.exe" --protocol-launcher "%1"
```

**x-github-desktop-auth**

```
HKEY_CLASSES_ROOT
  x-github-desktop-auth
    shell
      open
        command(Default) = "C:\Users\User\AppData\Local\GitHubDesktop\app-1.4.1\GitHubDesktop.exe" --protocol-launcher "%1"
```

`command(Default)` should be `"C:\Users\User\AppData\Local\GitHubDesktop\app-1.4.1\GitHubDesktop.exe" --protocol-launcher -- "%1"`

#### HKEY_CURRENT_USER

_defines the preferences of the current user_

**x-github-client**

```
HKEY_CURRENT_USER
  Software
    Classes
      x-github-client
        shell
          open
            command(Default) = "C:\Users\User\AppData\Local\GitHubDesktop\app-1.4.1\GitHubDesktop.exe" --protocol-launcher "%1"
```

**x-github-desktop-auth**

```
HKEY_CURRENT_USER
  Software
    Classes
      x-github-desktop-auth
        shell
          open
            command(Default) = "C:\Users\User\AppData\Local\GitHubDesktop\app-1.4.1\GitHubDesktop.exe" --protocol-launcher "%1"
```

`command(Default)` should be `"C:\Users\User\AppData\Local\GitHubDesktop\app-1.4.1\GitHubDesktop.exe" --protocol-launcher -- "%1"`

#### HKEY_LOCAL_MACHINE

_defines the physical state of the computer_

**x-github-client**

```
HKEY_LOCAL_MACHINE
  SOFTWARE
    Classes
      x-github-client
```

Probably should not be empty

#### HKEY_USERS

_defines the default user configuration for new users on the local computer and the user configuration for the current user_

**x-github-client**

```
HKEY_USERS
  S-1-5-21-1186505040-3499372643-3030342882-1000
    Software
      Classes
        x-github-client
          shell
            open
              command(Default) = "C:\Users\User\AppData\Local\GitHubDesktop\app-1.4.1\GitHubDesktop.exe" --protocol-launcher "%1"
```

```
HKEY_USERS
  S-1-5-21-1186505040-3499372643-3030342882-1000_Classes
    x-github-client
      shell
        open
          command(Default) = "C:\Users\User\AppData\Local\GitHubDesktop\app-1.4.1\GitHubDesktop.exe" --protocol-launcher "%1"
```

Not really sure why there are two of these. The only notable difference between the two is

`...\Software\Classes\x-github-client\...`

vs.

`..._Classes\x-github-client\...`

Not sure if this is a mistake.

**x-github-desktop-auth**

```
HKEY_USERS
  S-1-5-21-1186505040-3499372643-3030342882-1000
    Software
      Classes
        x-github-desktop-auth
          shell
            open
              command(Default) = "C:\Users\User\AppData\Local\GitHubDesktop\app-1.4.1\GitHubDesktop.exe" --protocol-launcher "%1"
```

```
HKEY_USERS
  S-1-5-21-1186505040-3499372643-3030342882-1000_Classes
    x-github-desktop-auth
      shell
        open
          command(Default) = "C:\Users\User\AppData\Local\GitHubDesktop\app-1.4.1\GitHubDesktop.exe" --protocol-launcher "%1"
```

Same thing as noted above. The difference being

`...\Software\Classes\x-github-desktop-auth\...`

vs

`..._Classes\x-github-desktop-auth\...`

In both cases
`command(Default)` should be `"C:\Users\User\AppData\Local\GitHubDesktop\app-1.4.1\GitHubDesktop.exe" --protocol-launcher -- "%1"`

**Comment by iAmWillShepherd** [comment]
@oktonion,

> n.3, n.5 are still relevant 100% tho.

I'm not sure I understand what you mean by your fifth question.

**Comment by oktonion** [comment]
> 
> 
> @oktonion,
> 
> > n.3, n.5 are still relevant 100% tho.
> 
> I'm not sure I understand what you mean in your fifth question.
@iAmWillShepherd I'm talking about that:
```
C:\Users\User\AppData\Local\GitHubDesktop
    \app-1.4.0\GitHubDesktop.exe
    \app-1.4.1\GitHubDesktop.exe
    \GitHubDesktop.exe
```
I can not understand which .exe is the right one, why there are two directories with same binaries (lots of .dll, .exe, .bin).

**Comment by iAmWillShepherd** [comment]
Ahh, gotcha. Thanks for the clarification on that question. Are you able to confirm my summarized points as well?

**Comment by iAmWillShepherd** [comment]
@oktonion, regarding you point: 

```
C:\Users\User\AppData\Local\GitHubDesktop\
    \app-1.4.0\
        \GitHubDesktop.exe
        \*.dll
        \*.bin
    \app-1.4.1\
        \GitHubDesktop.exe
        \*.dll
        \*.bin
    \GitHubDesktop.exe
```

I think this may be a result squirrel updater [[point 6 in  docs](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/update-process.md)].

**Comment by oktonion** [comment]
@iAmWillShepherd so about your summary:
I can not tell what are the right numbers of registry keys for the purpose of registering URI protocol in Windows 7 although Microsoft states that key in HKEY_CLASSES_ROOT should be enough. Also I see that this issue appears to be some misunderstanding between definition of "Application registered to handle URI protocol" in firefox and in GH Desktop for Windows.

I'm summoning @shiftkey for that as he is the Sherlock Holmes of the original issue.

About extra '--' parameter:
[This](https://electronjs.org/blog/protocol-handler-fix) is what electron says about fixing this CVE.
First of all:

Electron says:

> We've published new versions of Electron which include fixes for this vulnerability: 1.8.2-beta.5, 1.7.12, and 1.6.17. We urge all Electron developers to update their apps to the latest stable version immediately.

so... if GH Desktop is using new version it should be safe (I think?) with no need for extra params. Then

Electron says:

> If for some reason you are unable to upgrade your Electron version, you can append -- as the last argument when calling app.setAsDefaultProtocolClient, which prevents **Chromium** from parsing further options. The double dash -- signifies the end of command options, after which only positional parameters are accepted.

So what about not Chromium-based browsers, dear electron developers (@zcbenz may be?) ? 

Anyway I'm not qualified to tell you how GH Desktop should be registered in Windows with all this electron-specific stuff. In my view it should have registry keys in HKEY_CLASSES_ROOT as Microsoft states and, depending on the version of electron used, have or have not extra parameters for launch.

**Comment by iAmWillShepherd** [comment]
@oktonion, he is out on vacation

**Comment by oktonion** [comment]
> 
> 
> @oktonion, regarding you point:
> 
> ```
> C:\Users\User\AppData\Local\GitHubDesktop\
>     \app-1.4.0\
>         \GitHubDesktop.exe
>         \*.dll
>         \*.bin
>     \app-1.4.1\
>         \GitHubDesktop.exe
>         \*.dll
>         \*.bin
>     \GitHubDesktop.exe
> ```
> 
> I think this may be a result squirrel updater [[point 6 in docs](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/update-process.md)].

So the version in C:\Users\User\AppData\Local\GitHubDesktop\$CURRENT_VERSION_NUMBER$\GitHubDesktop.exe is the one? Or C:\Users\User\AppData\Local\GitHubDesktop\GitHubDesktop.exe is? Anyway why there are two of a kind?

**Comment by oktonion** [comment]
> 
> 
> @oktonion, he is out on vacation

@shiftkey ? If so that's good for him. He will not be stuck in that conversation. =)

Back to the topic about firefox and electron-based GH Desktop relations:
I suggest that a developer of GH Desktop should contact firefox via bug tracker and solve the issue between firefox and electron ways of registering protocol handler in Windows. My [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1482225) was closed because I can not argue with firefox developers about internals that I have not so much info and understanding. So qualified eletron developer help and arguments are required there.

**Comment by iAmWillShepherd** [comment]
@oktonion 

I've answered all your questions below

> 1. Is not Firefox or any other browser handling of x-github-client protocol.

I created a fresh VM with Windows and installed both Desktop and Firefox on it. I clicked the _Clone or download_ button on the desktop/desktop repo to open the repo in Desktop. I was presented with this dialog on Firefox. I opened the link and Desktop opened as expected. 

![screen shot 2018-10-02 at 9 30 51 am](https://user-images.githubusercontent.com/1715082/46357091-af314280-c629-11e8-9dc2-1ebbfe871d3d.png)

> For custom protocol handler applications added manually, the only interface we support consists in passing the URI as the only argument on the command line. This means the GitHub Desktop executable is not compatible with this interface anymore.
> In general, we're also moving towards dropping support for custom applications and only supporting system default applications. This is far away in the future, but I don't see us adding more features in this area. The workaround here if nothing else works may be to create a ".bat" file that wraps the GitHub Desktop executable and adds the other arguments.
> The best thing in this specific case, though, is to reinstall GitHub Desktop and ensure it is registered as the default application in the system and selected in Firefox.

-- [Paolo Amadini's comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1482225#c6)

We will not be implementing the suggested workaround since we have a solution that works: reinstall  Desktop and Firefox will recognize it.

> 2. There is definitely missed second argument '--'. It's the main reason.

We no longer need to supply the `--` before arguments are passed from the URL as this is now handled internally by Electron.

> 3. There is hell more registry keys then it should be.

We (Desktop) is only writing a single key, `HKEY_CURRENT_USER `. The rest, except for `HKEY_LOCAL_MACHINE `,  are artifacts of the registries internal implementation (there is no problem here).

`HKEY_LOCAL_MACHINE` is likely the result of some other git client or an legacy version of Desktop writing that key. Desktop currently doesn't create or read from that key.

> 4. That keys are refreshed at every launch of GitHub Desktop so I assume the GH Desktop is rewriting it with the wrong string.

We do re-write the keys on launch, but these keys are not incorrect. We re-write the keys to ensure the protocol handler is always up to date.

https://github.com/desktop/desktop/blob/07f354771b42f218e3c0de2395846576952bef1d/app/src/main-process/main.ts#L153-L165

As you can see above, we grab the value of the process's executing path and stuff that into the registry, ensuring the latest version is used.

> 5. it seems wrong that there are multiple versions of GitHubDesktop.exe and especially that 'app-1.4.1' version is used instead of 'GitHubDesktop.exe' in root folder '...\AppData\Local\GitHubDesktop\...'

I answered this in [this comment](https://github.com/desktop/desktop/issues/5792#issuecomment-426177366)

After reviewing and discussing with the team, I've determined this to be a non-issue, so I'll be closing this out.

**Comment by oktonion** [comment]
@iAmWillShepherd Thank you for detailed answer and for your time. If it is the case that now reinstall of GitHub Desktop will solve the problem for firefox in Windows 7 I will definitely do it. That's unfortunate that such a simple solution took so complicated discussion. I will try it tomorrow.

**Comment by oktonion** [comment]
Okay, for future reference:
This is some kind of problem in firefox and it's protocol handling in general. [Bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1496024) to follow. 

P.S.:
From my experience this fix is not going to happen soon because [related bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1413819) reported at the end of 2017 is still there with low priority.

**Comment by doppelhub** [comment]
Amazing that this is a "low priority" issue... Firefox is the #2 desktop browser (far behind Chrome, which has a 70% market share).  I don't like using google products, so my inclination was to use IE (because it's already installed)... nope, that doesn't work either... basically I cannot log into Github Desktop without installing Chrome.
