### ISSUE TITLE
Electron is garbage

### ISSUE THREAD

**Issue by newguy12345** [desktop/desktop#5798]
All I want to say is that you should have used JavaFX (or my God, your app is so simple just make separate apps) instead of Electron. I've had nothing but problems.  Constant errors with "locks" that disappear a second or third time you click Pull/Fetch.   Now, the title of my last commit stays in the text box label even after something has been committed and pushed.  It's also a lot slower. I'm switching over to the regular GUI -- and deal with that complicated mess.  It's almost like you've brought the trash from the Web into the Desktop... or wait.. you did!

**Comment by billygriffin** [comment]
Thanks for the issue @newguy12345, and sorry you're having problems with the app. If you'd like to open an issue with the template to report a specific problem (maybe one of the ones you referenced), we'd be happy to look into it. If you decide to switch, hope whatever you find works great for your needs.
