### ISSUE TITLE
failure to restart after just being open

### ISSUE THREAD

**Issue by msftrncs** [desktop/desktop#5800]
## Description
After having just had Desktop open and refreshed a repository from online, I closed desktop, and a few moments later (2 or three minutes, as I moved some files around relating to the repository, I attempted to reopen desktop, and it would not open.

![image](https://user-images.githubusercontent.com/26179051/46361291-d3dde800-c632-11e8-9ee0-a762eb23a519.png)

## Version
* GitHub Desktop: ??
Unable to get it open, but it looks like I had 1.4.0, and appears as if it tried to update to 1.4.1 this morning while I had it open, basing this on folders present in `AppData\Local\GitHubDesktop`
* Operating system:
Win 10 1803.  [Version 10.0.17134.286]

### Logs
I have no logs folder, but I have the following which appears to be a setup log.
[SquirrelSetup.log](https://github.com/desktop/desktop/files/2438665/SquirrelSetup.log)
This log goes all the way back to my original install.

**Comment by steveward** [comment]
Thanks for the report @msftrncs. This looks like the same error that was reported in https://github.com/desktop/desktop/issues/5763. It does look like the update to v1.4.1 failed based on the log file you sent over.

I would recommend deleting the `%LocalAppData%\GitHubDesktop` directory and then reinstalling GitHub Desktop to see if that gets things working again for you.

**Comment by msftrncs** [comment]
FYI, I was able to get it running again (right or wrong) by using the copy stored in the folder `AppData\Local\GitHubDesktop\app-1.4.0` and use the About... Update function there, the update completed successfully this time, and now the regular icons start the app successfully.  In my case I might wonder if I shut it down while it was trying to update.  I only had it open long enough to refresh a repository from online, and that didn't take long because its very small, single file repository.  My other thought is that something was stuck from a previous update attempt yesterday, thus why the files were already in use.  The logfile is jumbled between 10-01 and 10-02 ...

**Comment by steveward** [comment]
@msftrncs I'm glad to hear things are working for you now. I'm going to close this issue out, but if we continue to see reports of this error I will plan on investigating it further.
