### ISSUE TITLE
Add context menu to branch list

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#5803]
Tagging #5555 since this issue is related to point 2 in that issue.

Starting a branch comparison is currently a bit confusing. Desktop requires that the user click on the _History_ tab then a text box to show a list of branches to compare against.

![2018-10-03 09 39 50](https://user-images.githubusercontent.com/1715082/46418562-a4da7b80-c6f1-11e8-8b11-eee2066ca714.gif)

This is problematic because the _History_ tab is about showing commits. While it's true that selecting a comparison branch will indeed produce a list of commits that are ahead/behind the current branch, the location of the action to produce that result feels out of place.

**Proposal**
As a start, we can add a context-menu to the branch list that will allow comparisons to be initiated directly from the branch list. For now, I think the we should bring over all of the items in the _Branch_ menu except for the _New Branch..._ item.

![screen shot 2018-10-03 at 9 45 27 am](https://user-images.githubusercontent.com/1715082/46418577-ad32b680-c6f1-11e8-98de-56b353865109.png)

I'm already aware that context-menus present a discoverability problem; however, this is intended to be a step taken to overhaul the relationship between branches experience. We also make use of these menus in other areas of the app, so there is precedent here. 

![2018-10-03 09 48 21](https://user-images.githubusercontent.com/1715082/46418590-b1f76a80-c6f1-11e8-9cfb-d9cd80385f40.gif)

cc @desktop/design

**Comment by tierninho** [comment]
A step in the right direction 👍 

> Starting a branch comparison is currently a bit confusing.

My two cents is to decouple the compare branch feature altogether. I use this area quite a bit in testing, and it is never intuitive and always feels out-of-place. Going back and forth from the actual commit history to the compare branch feature is never a smooth transition. 😞

**Comment by billygriffin** [comment]
I stumbled upon this https://github.com/desktop/desktop/pull/3559 which seems related, so just want to make sure we are accounting for the same issues that we were running into on that one.

**Comment by billygriffin** [comment]
From @njbmartin:
> It seems the only way to delete a branch using Github Desktop is to switch to it, and then use the menu to delete it. When you're trying to tidy up branches, they should be trivial to delete.

**Comment by billygriffin** [comment]
I'd like to reframe/downscope the problem statement here a bit. I've seen and heard an expectation that there are a couple branch-specific actions people want to be able to take without having to switch to the branch and then navigate to the menu bar.

1. I want to be able to delete a branch (as captured by @njbmartin in #6091 and copied above).
2. I want to be able to rename a branch.

Now that we'll have merging available from the branch menu in 1.5, I don't think it's necessary to include merging workflows into this context menu.

@ampinsk @iAmWillShepherd Any objection to this reframing and maybe a `help wanted` from there since you already got it started in #5817 @iAmWillShepherd?

**Comment by njbmartin** [comment]
Thanks @billygriffin. I read the problem statement for this issue before posting but didn't seem related. However as you've noted the proposal would cover #6091

**Comment by OmerJog** [comment]
When will this be added? It's much needed!
For example there is no way to delete branch now

**Comment by nunoperalta** [comment]
This would be extremely useful :)

**Comment by tidy-dev** [comment]
This appears scoped to just the branches. However, you can also Rename and Delete from the top branch menu for Pull Requests. Should this context menu be added there as well as part of a solution to this?
![image](https://user-images.githubusercontent.com/75402236/105366359-404acf80-5bcd-11eb-86e2-4c4a2d15f6e0.png)

**Comment by ampinsk** [comment]
@tidy-dev since the deletion/rename will happen on the branch itself, not the PR (for ex, you're not renaming the PR title), let's keep the context menus scoped to the branch list for now!

**Comment by tidy-dev** [comment]
Good point! Will do
