### ISSUE TITLE
Proposal: add path to "Remove repository" dialog

### ISSUE THREAD

**Issue by NickCraver** [desktop/desktop#5805]
Currently, when you right click and `Remove...` on a repository in the list, you'll get the following dialog:
![image](https://user-images.githubusercontent.com/454813/46425368-7b2d4e80-c709-11e8-9719-5f8d2f52fed5.png)

Several times, I've found I had another clone somewhere and GitHub desktop had the wrong one...not the thing I intended to edit. So time to remove that and add the right one.

Since this dialog also offers to *delete the files off disk*, I think it should include the file path it's talking about. Can we please add a link with the repo path on it? That'd remove any ambiguity from the situation, and in my case: help find that duplicate repo to boot. Something like this:

![image](https://user-images.githubusercontent.com/454813/46425589-0e668400-c70a-11e8-8f27-e7bba7d2ad75.png)

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue, this is an excellent suggestion! 🙇

**Comment by iAmWillShepherd** [comment]
cc @desktop/product and @desktop/design for their opinion on this suggestion.

**Comment by outofambit** [comment]
The place to start on this would be in: https://github.com/desktop/desktop/blob/9ada1c10559089eea46c8354ac8a1b1404f771b4/app/src/ui/remove-repository/confirm-remove-repository.tsx#L27

The `repository` prop should have the information needed (aka the path) for this new message 😃 you can see what it contains at https://github.com/desktop/desktop/blob/9ada1c10559089eea46c8354ac8a1b1404f771b4/app/src/models/repository.ts#L19

**Comment by billygriffin** [comment]
This is a great suggestion @NickCraver and thanks @outofambit for adding the community labels and offering guidance on where to start!

**Comment by NickCraver** [comment]
@outofambit Thanks for the time savers there (and thanks all for feedback!) I opened a PR with the changes in #5807.
