### ISSUE TITLE
Ref component rendering differences between macOS and Windows

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#5812]
`Ref component` or its associated CSS does not reflect the same on Windows and MacOS. Notice the font sizes are different between OS and Windows for the `ref component` in the following example:

https://github.com/desktop/desktop/pull/5807#issuecomment-427076126

Within the class, Windows the font sizes match, while Mac has two different font sizes.

tested with: Mac, 1.4.2-beta0

**Comment by shiftkey** [comment]
@tierninho It's not clear to me what we should be doing here (working from dev build 45e74638849a942d1b768ffc922d04af89f8f5cb).

>However, the Mac font size seems to show two different font sizes, `10px` and `11px` in the `description` and `ref-component`. Looks a bit odd.

The `Ref` component does not specify a `font-size` style in it's CSS:

https://github.com/desktop/desktop/blob/45e74638849a942d1b768ffc922d04af89f8f5cb/app/styles/ui/_ref.scss#L1-L9

And on MacOS I see the `font-size: 11px` being set based on this selector:

https://github.com/desktop/desktop/blob/45e74638849a942d1b768ffc922d04af89f8f5cb/app/styles/ui/_dialog.scss#L350-L357

<img width="979" src="https://user-images.githubusercontent.com/359239/46922121-dd743200-cfda-11e8-95de-ca504c2b076b.png">

I also checked the parent paragraph and it too is 11px on macOS (Chrome Dev Tools wouldn't let me select the text directly for some reason):

<img width="1024" src="https://user-images.githubusercontent.com/359239/46922186-c3871f00-cfdb-11e8-854c-5f7a50595e6d.png">

**Comment by tierninho** [comment]
@shiftkey Looks like there are two different font families, hence the size of the text is slightly different.

Notice the highlighted text is not affected from unchecking this box :
<img width="912" alt="screen shot 2018-10-15 at 2 25 11 pm" src="https://user-images.githubusercontent.com/14828183/46979522-b410e000-d086-11e8-9136-4fedd2776c71.png">

The highlighted text is from `(--font-family-monospace)`.

Probably not worth fixing unless you see a quick fix. Feel free to close 👍

**Comment by tierninho** [comment]
Closing this as it has not come up enough times to be validated as a real problem.
