### ISSUE TITLE
 Snap package support (Feature Request) 

### ISSUE THREAD

**Issue by Mikerr1111** [desktop/desktop#5832]
I was thinking the setup and install process for Ubuntu and other Linux distros could be improved by having a [Snap package](https://snapcraft.io/) version. 

[Creating a Snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

[Create snaps from your preferred programming language.](https://docs.snapcraft.io/build-snaps/languages)

[Linux distros with Snap support](https://docs.snapcraft.io/core/install)
![snap](https://user-images.githubusercontent.com/18353476/43989596-ec564800-9d01-11e8-89e6-8e0af1434f62.png)

**Comment by steveward** [comment]
Thanks for contributing @Mikerr1111. @shiftkey [maintains a fork of GitHub Desktop](https://github.com/shiftkey/deskop) where he publishes Linux releases. You can also find any related discussion in the issue tracker there.  You can check out the [releases](https://github.com/shiftkey/desktop/releases) page to find Snap package version of GitHub Desktop. 

If you run into any issues with the Linux version please feel free to open an issue there. I hope that is helpful!

**Comment by Mikerr1111** [comment]
Yes, Thank you!
