### ISSUE TITLE
Allow font size configuration

### ISSUE THREAD

**Issue by ardias** [desktop/desktop#5836]
**Please describe the problem you think should be solved**
In appearance configuration there is no way to configure fonts, especially font size.
For some files, readme.md and others, that are a bit larger it would be beneficial to be able to configure the font size, for people that may have sight problems.

**[Optional] Do you have any potential solutions in mind?**
Just allow for font configuration, if not fully, at least font size.

**Comment by kiser0606** [comment]
.

**Comment by tierninho** [comment]
@ardias Have you tried our zoom feature? See the `View` menu on Mac or Windows.

Alternatively, keyboard commands are:
```
Reset Zoom (Mac: ⌘0; Windows: Ctrl+0)
Zoom In (Mac: ⌘=; Windows: Ctrl+=)
Zoom Out (Mac: ⌘-; Windows: Ctrl+-)
```

**Comment by ardias** [comment]
@tierninho Sorry, no i didn't. Will try that. Still would be cool if we could configure it :)

**Comment by tierninho** [comment]
@ardias Great, hope the zoom feature helps.

**Comment by travellers** [comment]
> @ardias Have you tried our zoom feature? See the `View` menu on Mac or Windows.
> 
> Alternatively, keyboard commands are:
> 
> ```
> Reset Zoom (Mac: ⌘0; Windows: Ctrl+0)
> Zoom In (Mac: ⌘=; Windows: Ctrl+=)
> Zoom Out (Mac: ⌘-; Windows: Ctrl+-)
> ```

Hi tierninho,
The zoom feature is great, but If the default font size can be configured by the user, I think it is appreciated.
