### ISSUE TITLE
Automatic removal of old GitHub Desktop versions and clear display of active remote branches

### ISSUE THREAD

**Issue by Fredrik00** [desktop/desktop#5842]
Every time the application is updated, the old files remain in /appdata/local/GitHubDesktop with the old version number while a new one is added. This has two quite annoying results, one that more and more disk space is taken up unless cleaned up manually, while the other is that the path to the git executable also changes and then has to be reconfigured in PATH if it is to be used. I believe a much better approach, and a more common one, would be to not include the version number in the application folder and simply replace this folder with each update.

Another thing I would like adjusted is the listing of branches from the drop down menu to show those active on the remote. As feature branches are deleted on the remote to clean up, these are still listed in the client not being marked in any way as deleted or inactive. After a while the branch list in the client becomes very cluttered as a result. Preferably I would like the active branches appearing on the top, but a clear separation should be sufficient.

**Comment by j-f1** [comment]
> while the other is that the path to the git executable also changes and then has to be reconfigured in PATH if it is to be used.

This is intentional. We use a specially-compiled version of Git that may not have all the features a normal installation of Git has. Instead, we recommend installing [Git for Windows](https://gitforwindows.org) so you have a full copy of Git available.

**Comment by Fredrik00** [comment]
> > while the other is that the path to the git executable also changes and then has to be reconfigured in PATH if it is to be used.
> 
> This is intentional. We use a specially-compiled version of Git that may not have all the features a normal installation of Git has. Instead, we recommend installing [Git for Windows](https://gitforwindows.org) so you have a full copy of Git available.

That is a fair point, and I have installed Git for Windows additionally for this purpose. In terms of the extra disk space used the issue still applies though.

**Comment by steveward** [comment]
Thanks for sharing this feedback @Fredrik00.

>Every time the application is updated, the old files remain in /appdata/local/GitHubDesktop with the old version number while a new one is added. 

The Squirrel framework we use for updating/installing is careful to ensure that it doesn't remove the previous version (in case it's still running).

There should be a log file at %LocalAppData%\GitHubDesktop\SquirrrelSetup.log that should have details about what's happening -- look for the message `cleanDeadVersions: for version {XYZ}`. Let me know if there is anything in the log file that may indicate why Squirrel is not removing the oldest version.

>Another thing I would like adjusted is the listing of branches from the drop down menu to show those active on the remote. As feature branches are deleted on the remote to clean up, these are still listed in the client not being marked in any way as deleted or inactive. After a while the branch list in the client becomes very cluttered as a result. Preferably I would like the active branches appearing on the top, but a clear separation should be sufficient.

We are tracking pruning local branches in https://github.com/desktop/desktop/issues/750 -- we would love for someone from the community to contribute a pull request for this if you are interested!

**Comment by shiftkey** [comment]
> This has two quite annoying results, one that more and more disk space is taken up unless cleaned up manually, while the other is that the path to the git executable also changes and then has to be reconfigured in PATH if it is to be used.

Two extra things to note:

 - Squirrel will prune older versions of the app as part of the upgrade process. The log files that @steveward outlined should show that it does clean up after itself during updates.
 - the Git we embed in Desktop is designed for embedding in apps, so if you're trying to use it on the command line it doesn't have the full set of utilities that Git for Windows provides.

**Comment by Fredrik00** [comment]
> The Squirrel framework we use for updating/installing is careful to ensure that it doesn't remove the 
> There should be a log file at %LocalAppData%\GitHubDesktop\SquirrrelSetup.log that should have details about what's happening -- look for the message `cleanDeadVersions: for version {XYZ}`. Let me know if there is anything in the log file that may indicate why Squirrel is not removing the oldest version.

I looked through the log file and could only find mentions of it excluding the previous version as well as the updated one after the update. For example like this:
2018-09-13 10:05:39> ApplyReleasesImpl: cleanDeadVersions: for version 1.4.0
2018-09-13 10:05:39> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.3.5
2018-09-13 10:05:39> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.4.0

I am not sure how diligent I have been at cleaning each version manually, but I could not find any mention in cleanDeadVersions handling more than two app versions so I guess the logged behavior is as expected. I'll take a look at my desktop as well when I get the chance to see if the log there has more interesting info. 

I think it would perhaps be better to perform the cleanup after the new version is launched, unless you have some other reason as to why you would like to keep the previous version around for longer.

**Comment by shiftkey** [comment]
@Fredrik00

> I think it would perhaps be better to perform the cleanup after the new version is launched, unless you have some other reason as to why you would like to keep the previous version around for longer.

The cleanup is actually done on the first launch _after updating_, but the previous version is kept around: https://github.com/Squirrel/Squirrel.Windows/issues/589. I believe this is for safety, in case something is not working with the new version, but I can't find any docs about it currently.

**Comment by shiftkey** [comment]
In regards to your other bit of feedback:

> Another thing I would like adjusted is the listing of branches from the drop down menu to show those active on the remote. As feature branches are deleted on the remote to clean up, these are still listed in the client not being marked in any way as deleted or inactive. After a while the branch list in the client becomes very cluttered as a result. Preferably I would like the active branches appearing on the top, but a clear separation should be sufficient.

Does #750 feel like what you need here? Something to sweep up these branches which have been merged into the default branch so that they no longer appear in your branches list?

**Comment by shiftkey** [comment]
Closing this out because I believe the outstanding questions have been either resolved or are tracked in existing issues. @Fredrik00 let us know if anything above is unclear.
