### ISSUE TITLE
Shell command fails if `python` points to Python 3

### ISSUE THREAD

**Issue by munir131** [desktop/desktop#5843]
## Description
It is similar to https://github.com/Microsoft/vscode/issues/3790. `github` command line utility fails when python points to Python 3

## Version
* GitHub Desktop:
**About Github Desktop** menu option is also not working.
* Operating system: OS X

## Steps to Reproduce
`github --help`

### Expected Behavior
should show help

### Actual Behavior
![screen shot 2018-10-08 at 6 30 23 pm](https://user-images.githubusercontent.com/6319375/46650437-229efb00-cbba-11e8-8626-3102cefa66d3.png)

`File "<string>", line 1
    import os,sys; print os.path.realpath(sys.argv[1])
                          ^
SyntaxError: invalid syntax
ls: ./MacOS/: No such file or directory`

## Additional Information
I fixed this issue on my local by update script to 
`/usr/bin/python -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$0";`

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to open an issue! 🙇 

Could you explain your configuration a bit more please? I need to verify that I can reproduce this issue on my machine. At the moment, I'm assuming you don't have the version of python that shipped with macOS, so details about how you've configured Python will help me get my dev machine in the _same_ state as yours. Disclaimer, I don't use Python, so be as detailed as possible about your setup: assume I know nothing :-)

**Comment by munir131** [comment]
You can do it with these two steps:
1. `brew install python3`0
2. `export PATH=/usr/local/bin:/usr/local/sbin:$PATH`

Reference link: https://docs.python-guide.org/starting/install3/osx/
