### ISSUE TITLE
cryptic error message when Publishing

### ISSUE THREAD

**Issue by goswinr** [desktop/desktop#5846]
When trying to publish a repro that has just one .txt file I get this error message:

`fatal: unable to access 'https://github.com/goswinr/test.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
`

This is my first use of Github Desktop. I have not yet done a successful publish
could this be related to a firewall? and Certificate signing?

Version 1.4.2

![image](https://user-images.githubusercontent.com/884885/46617337-cc2faf00-cb1c-11e8-98a2-44d64779e4bb.png)

**Comment by goswinr** [comment]
@tierninho Thanks, I could install the PEM file. but  now if have this error about self signed certificates. 
I had similar errors on other apps, so this is probably related to our cooperate network. Is ther a way to by pass this?

```
Cloning into 'C:\10_Dev\50_GitHub\rhinoscriptsyntax'...
fatal: unable to access 'https://github.com/mcneel/rhinoscriptsyntax.git/': SSL certificate problem: self signed certificate in certificate chain
```

**Comment by goswinr** [comment]
It's solved. This helped me to solve it:
https://stackoverflow.com/questions/11621768/how-can-i-make-git-accept-a-self-signed-certificate
I am leaving this issue open because i think the initial error message  about certificate revocation could be improved. I think many new users of GitHub Desktop might just give up when they see such messages.

**Comment by tierninho** [comment]
@goswinr thank you for sharing the link. Closing this issue as it's a known issue and still discoverable in search. 

> I think many new users of GitHub Desktop might just give up when they see such messages.

I agree, and we are always here to help until it gets fully resolved by the team 😄

**Comment by goswinr** [comment]
Yes, your response has been very fast! Thanks
