### ISSUE TITLE
toPlatformCase component helper

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#5847]
## `toPlatformCase`

In #5744 we added `toPlatformCase`, a helper function to change this pattern:

https://github.com/desktop/desktop/blob/3feeaac7ba184aacdeb21aadc85587b29e3f36f6/app/src/ui/merge-conflicts/merge-conflicts-warning.tsx#L31

to this:

https://github.com/desktop/desktop/blob/3feeaac7ba184aacdeb21aadc85587b29e3f36f6/app/src/ui/discard-changes/discard-changes-dialog.tsx#L69

**The idea is that `toPlatformCase` will case the string properly depending on the current platform.** macOS is title case and windows is sentence case _generally_.

The original pattern appears in about 85 places in Desktop's React components, according to a quick search of the codebase. (Currently `toPlatformCase` is only used in one component.)

## Limitations

There are limitations to this approach because there are a number of edge cases that extend beyond simply title casing or sentence casing a string.

1. Prepositions (https://github.com/desktop/desktop/pull/5841#pullrequestreview-162478757), which are lower case, even in title case.
2. Platform-specific terminology (#2103), like trash or recycling bin
3. Key shortcuts (#2103), which differ on platforms

## The Question

Options:
* keep `toPlatformCase` and spread in the codebase (where applicable)
* remove `toPlatformCase` and continue using string literals in our components
* refactor `toPlatformCase` to cover more edge cases
* something else?

cc @Daniel-McCarthy @j-f1 @say25 @iAmWillShepherd

**Comment by outofambit** [comment]
### My proposal:

> * keep toPlatformCase and spread in the codebase (where applicable)

but additionally:

* make the limitations abundantly clear through code documentation
* in components where we can't use `toPlatformCase` create a helper function in that component that returns the correct wording and casing depending on platform to avoid the inline platform check syntax outlined aboe

**Comment by say25** [comment]
I am personally in favor of options 2 or 3. I think for first time contributors, it is easier to call the `toPlatformCase` function and get what one might expect.

**Comment by say25** [comment]
@j-f1 that would basically be what toPlatformCase would conditionally call correct?

**Comment by j-f1** [comment]
Yep @say25! We could even define `toPlatformCase` as:

```ts
export const toPlatformCase = __DARWIN__ ? title : (s: string) => s
```

**Comment by j-f1** [comment]
For edge cases, we could define a second parameter that’s used as-is on macOS when it’s passed instead of the title-cased version.

**Comment by shiftkey** [comment]
I'm somewhat neutral about this effort to introduce a generic platform helper component (I've seen a couple of attempts in the past and might have even had a shot at this myself). I had some notes from a chat we had in Slack a while ago, which I'll share here for everyone's benefits:

> 1. I'm still a fan of the use of ternary statements because they get optimized away at runtime for the specific platform (smaller bundles yay!)
> 2. toPlatformCase feels like it lacks nuance, and we lose the minification benefits from (1)
> 3. I'd love to nail down the underlying problem with our current approach before we go further - is it the use of these ternaries? the potential for inconsistent labels? how it supports English-only templates?
> 4. I'd love for us to work towards a solution that supports the nuance of localization, but agree to punt it for now
> 5. Keyboard shortcuts should also be out-of-scope here (they should derive from the keyboard layout or support customization by the user)

For me, I'd love to come to a consensus on this before we dive into solutions:

>  I'd love to nail down the underlying problem with our current approach before we go further - is it the use of these ternaries? the potential for inconsistent labels? how it supports English-only templates?

**Comment by say25** [comment]
@outofambit whats the conclusion here? are we going to remove `toPlatformCase`.
