### ISSUE TITLE
Commit failed - exit code 128 received, with output: '*** Please tell me who you are.  Run    git config --global user.email "you@example.com"   git config --global user.name "Your Name"  to set your account's default identity. Omit --global to set the identity only in this repository.  fatal: unable to auto-detect email address (got 'Ravi Shankar@LAPTOP-MBB3MV1Q.(none)

### ISSUE THREAD

**Issue by ravi2248** [desktop/desktop#5855]
**Please describe the problem you think should be solved**
A clear and concise description of what the problem is and who else might be impacted. Screenshots are encouraged.

Example:

> “When I run into a merge conflict, I don’t know where to go to resolve it. Anyone who works off of multiple branches will likely run into this problem at least occasionally.”

**[Optional] Do you have any potential solutions in mind?**
A clear and concise description of one or more solutions you think might solve the problem. Please include any considered drawbacks or tradeoffs, and how users might use your solution(s). Screenshots or mockups are helpful here!

**Comment by steveward** [comment]
Thanks for contributing @ravi2248. It looks like your name and email are not set correctly in your .gitconfig file. Can you go to the file menu in GitHub Desktop and select `GitHub Desktop` > `Preferences` > `Git` and enter your name and email?

That should get things working for you again. Let me know if you have any further issues.
