### ISSUE TITLE
Clone Repository not working

### ISSUE THREAD

**Issue by srajaratnam** [desktop/desktop#5857]
I have tried to use the File>Clone repository option on my Desktop. The option does not seem to work 

Environment:
GitHub Desktop version: 1.4.2
Git-GUI for windows 2.18
Windows 7 Pro (x64)

source url: "https://github.com/firebase/quickstart-android.git"
destination: D:\WorkDesk\Repos\Android\android

message: "Destination already exists" where the destination is an empty folder created for cloning.

if the destination is a non-existant folder (with immediate parent is available, eg:"D:\WorkDesk\Repos\Android\quickstart-android"), then the message changed to "Sorry, I can't find that repository".

"Open in Desktop" from chrome does not seem to identify GitHub Desktop installation either.

**Comment by steveward** [comment]
Thanks for the report @srajaratnam -- I was able to reproduce this issue as well, but I'm still working on tracking down the exact scenarios that can trigger this error. I will update this issue once I have more information about that.

There were some changes made to repository path validation in https://github.com/desktop/desktop/pull/5518 -- @Daniel-McCarthy any thoughts on this with regards to the changes you made?

>"Open in Desktop" from chrome does not seem to identify GitHub Desktop installation either.

@srajaratnam could you clarify the issue you are experiencing with the `Open in Desktop` button further?  When you click `Open in Desktop` is GitHub Desktop not being launched correctly?

**Comment by outofambit** [comment]
@billygriffin I think @Daniel-McCarthy 's analysis and recommendation here is spot on. 👍

**Comment by billygriffin** [comment]
Thanks @outofambit!

@Daniel-McCarthy Would you consider this a bug? Sort of feels that way to me but I'm not positive. If you have thoughts on a path forward, I think we'd love it if you want to take a crack at it.

**Comment by srajaratnam** [comment]
> @srajaratnam could you clarify the issue you are experiencing with the `Open in Desktop` button further? When you click `Open in Desktop` is GitHub Desktop not being launched correctly?

@steveward, At the time of reporting; When on the GitHub > Clone or download > Open in Desktop, I were being taken to the GitHub Desktop [download](https://desktop.github.com/) page, though I had GitHub Desktop installed.

As of today, on my Windows 10 Pro+Chrome, the above action pops up the message box to open in GitHub Desktop as expected. But the Windows 7+Chrome still takes me to download page.

**Comment by steveward** [comment]
@srajaratnam are you able to try a different browser on your Windows 7 machine to see if you are able to reproduce this behavior across browsers?

**Comment by Delishan1505** [comment]
Hello all, 
i'm new to GitHub and i have a question. i'm working on a project and i wasn't able to pull the latest changes made by my friends, so i removed the project form GitHub desktop, and tried to reclone, but i get this error message " This folder contains files, Git can only clone to empty folders. what should i do to be able to reclone the project?

**Comment by tidy-dev** [comment]
@Delishan1505  Welcome to GitHub! It sounds like when you removed the project from GitHub Desktop the files were not removed from your computers directory. You can do one of two things:
1. Go to the directory where the repo was cloned and delete it. Then, it should work to reclone as it was.
2. Or.. when you go to clone and see that error, change the Local Path to a new folder. (This will keep the original clone at the old directory, but allow you reclone the repo somewhere else on your computer.)
