### ISSUE TITLE
Refactor AutocompletionProvider loading and updating in Sidebar.tsx

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#5861]
We've had a few bugs (#5859, #5618) related to the logic in [Sidebar.tsx](https://github.com/desktop/desktop/blob/master/app/src/ui/changes/sidebar.tsx), specifically here:

https://github.com/desktop/desktop/blob/6ca665270e6e6e300f559ce65a993db8f8208309/app/src/ui/changes/sidebar.tsx#L77-L82

which decides when to reload the autocompletion providers. in both PRs above, we've simply patched this logic to handle more cases, but i think this will be an ongoing source of bugs without a refactor.

I think there are a number of possible solutions. Suggestions/proposals welcome!

**Comment by ADustyOldMuffin** [comment]
Are you talking about 


https://github.com/desktop/desktop/blob/9a1bc7bc2616f9d46ede6bced8eddccdc464821f/app/src/ui/changes/sidebar.tsx#L89-L98


If so are you just talking about refactoring the if statement logic?

**Comment by ADustyOldMuffin** [comment]
Guess I should probably @outofambit So are you looking to move the logic out of the if statement, or make it easier to modify?

**Comment by outofambit** [comment]
hey @ADustyOldMuffin thanks for pinging me on this! In hindsight this is a half-baked issue and I'm having trouble developing it into a fully baked one right now, so I'm going to close it. Thanks for the interest and happy bug hunting :)
