### ISSUE TITLE
Branches deleted in Remote show up in "Recent Branches"

### ISSUE THREAD

**Issue by sharunkumar** [desktop/desktop#5863]
## Description

I use GitHub Desktop to maintain a GitLab repo clone. When I delete a branch in the server, it still shows up in the "recent branches" sub-menu

## Version
* GitHub Desktop: Version 1.4.2
* Operating system: Microsoft Windows [Version 6.1.7601] (Windows 8)

## Steps to Reproduce
1. Checkout a branch from remote
2. Delete the branch in the remote server (In my case it is hosted with GitLab)
3. Switch to a different branch (perhaps master) and fetch
4. Open the branch menu

### Expected Behavior
 - Deleted branch should not appear under "Recent Branches"

### Actual Behavior
 - It is possible to switch to the deleted branch via "Recent Branches" and there is also option to publish the branch

### Logs
[logs.zip](https://github.com/desktop/desktop/files/2463382/logs.zip)

**Comment by steveward** [comment]
Thanks for opening this @sharunkumar! At this time GitHub Desktop does not prune local branches that have been deleted in the remote repository. You can follow along in https://github.com/desktop/desktop/issues/750 for updates about adding this feature.
