### ISSUE TITLE
Git Clone Error

### ISSUE THREAD

**Issue by dipen-sen** [desktop/desktop#5864]
When I am trying to clone a repository, I am getting below error
fatal: 'remote-https' appears to be a git command, but we were not
able to execute it. Maybe git-remote-https is broken?

I tried to clone same repository with Eclipse git perspective as well and same error.

I am using windows 10 and git version is 2.19.1.windows.1

But I am able to clone using Tortoise Git.

**Comment by dipen-sen** [comment]
> @dipen-sen thanks for contributing! This issue tracker is for GitHub Desktop -- are you experiencing this error within GitHub Desktop? If so, could you please update the issue body and fill out the issue template?

I guess I selected the second template i.e. "Problem to raise". Do you mean I need to raise it with bug template? I did not use bug template because I am not sure if its a bug of Github Desktop App.

>The error you are experiencing is one I have seen before, and is often caused by a broken Git installation. If you are just using Git from the command line I would recommend trying to reinstall Git for Windows to see if it gets things working for you. If you are seeing this error in GitHub Desktop, please let me know and we can continue to dive into this further.

I have reinstalled Git for windows. I am using Windows 10 Enterprise as OS, Git for windows 2.19.1-64-bit and Github Desktop v 1.4.2

**NOTE: Similar issue I am facing with Eclipse but not with Tortoise Git.**

**Comment by shiftkey** [comment]
@dipen-sen can you clarify where you are cloning the app when this occurs? Are you cloning inside GItHub Desktop, or are you cloning from the command line? I'm not too worried about Eclipse at this point, and I'm not sure offhand what TortoiseGit uses for it's Git operations.

The reason that I ask is this error:

> fatal: 'remote-https' appears to be a git command, but we were not able to execute it. 

Is related to an executable that ships in Git for Windows: `git-remote-https.exe`. We use an embedded version in GitHub Desktop, and I think we're on that same version as Git for Windows.

If that executable doesn't exist where Git expects it to be, or is throwing an error for some reason, that's going to affect cloning or anything network-related for a HTTPS remote.

Can you confirm how you're triggering this error?

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @dipen-sen if you're able to answer the questions I've provided in the previous comment I'm happy to revisit this issue.
