### ISSUE TITLE
Release notes dialog text overflown and running over the dialogs footer.

### ISSUE THREAD

**Issue by sanusart** [desktop/desktop#5868]
## Description

Release notes dialog text overflown and running over the dialogs footer.

## Version

* GitHub Desktop: 1.4.1

* Operating system: macOs 10.14 (Mojave)

## Steps to Reproduce

1. Open application version 1.4.1
2. Click on to see **what's new?** on the update notification bar on top when it appear

### Expected Behavior

Content of the dialog should have scroll to support long changelog
![image](https://user-images.githubusercontent.com/267718/46785216-c4008b00-cd39-11e8-885b-41ed29006f16.png)

### Actual Behavior

Text is bleeding over the dialogs footer and out of the dialog which makes it impossible/hard to read
![image](https://user-images.githubusercontent.com/267718/46785203-b8ad5f80-cd39-11e8-8b49-3a8685018467.png)

**Comment by billygriffin** [comment]
Thanks for the report @sanusart! This should be fixed now (https://github.com/desktop/desktop/pull/5760) and visible in the next release.
