### ISSUE TITLE
Ignore File not working as expected

### ISSUE THREAD

**Issue by tbenko73** [desktop/desktop#5871]
**Please describe the problem you think should be solved**

"Ignore File" or "Ignore All .XXX Files" is not working if files are already tracked. Lots of people run into this problem frequently.

**[Optional] Do you have any potential solutions in mind?**

It would be expected to also stop tracking a file if the user chooses "Ignore" for a file. (Not sure if this raises any conflicts)

Adding a "Stop Tracking And Ignore" option would be very straightforward and helpful option.

**Comment by steveward** [comment]
@tbenko73 thanks for opening this. We are tracking this #2537 -- please follow along there for updates.

You can also find some more context and discussion about this in https://github.com/desktop/desktop/pull/3164#issuecomment-339789343.
