### ISSUE TITLE
Realize a Commit with an Enter

### ISSUE THREAD

**Issue by ValneyFaria** [desktop/desktop#5886]
After describing the commit name, we should have the possibility to just click Enter and the Commit to be done.

**Comment by billygriffin** [comment]
Hi @ValneyFaria, thanks for the idea. Would you mind filling out the template with the problem you think this would be solving, and potentially a screenshot of how your proposed solution might work? I can imagine this type of thing might be convenient for some but also might result in unexpected or confusing behavior, especially for those that don't understand it's an option.

Thanks for understanding and meeting us halfway! 😄

**Comment by ValneyFaria** [comment]
![capture](https://user-images.githubusercontent.com/9964643/46840733-cf37d300-cd9a-11e8-9d6d-43f789a42792.PNG)
My idea is this: After completing the commit message, the developer could simply click Enter and the commit would be done, just like in a message chat.

**Comment by steveward** [comment]
@ValneyFaria Thanks for the feedback. You can use the shortcut `CMD-Enter` (macOS) or `Control-Enter` (Windows) to quickly commit your changes after entering a summary description. I hope that is helpful!
