### ISSUE TITLE
Consistent behavior for escape button

### ISSUE THREAD

**Issue by luukdv** [desktop/desktop#5889]
On macOS, when the 'Merge Into Current Branch' (`⇧⌘M`) modal is open, it cannot be closed with the <kbd>esc</kbd> button.

**Comment by shiftkey** [comment]
@luukdv I believe this is because the modal opens and focuses on the filter text box. Do you think we should be handling <kbd>ESC</kbd> and dismissing the dialog?

Once I changed the focus to something else the modal would be dismissed, so I think it's just down to that scenario.

**Comment by tierninho** [comment]
@shiftkey I found some other modals (with the filter focus intact) where we allow the `esc` key to work. Try ⌘N and ⌘O. 

Seems like a bug and good first issue, if you agree.

**Comment by Amabel** [comment]
@shiftkey I found the same problem in Clone Repository modal (⇧⌘O).

For anyone who is interested in this issue, I think using a `FilterList` in a modal will cause this problem. As for @tierninho mentioned above, actually the ⌘N and ⌘O modals are just using `TextBox` instead of `FilterList`, and that is why the `esc` key works fine.

**Comment by koralcem** [comment]
Is this issue still happening/applicable? I can currently dismiss the `Clone a repository` and `Merge into <branch>` dialogs by hitting <kbd>ESC</kbd>, even with their initial focus in a `FilterList`. I'm guessing https://github.com/desktop/desktop/pull/6236 fixed it for all `Dialog` components.

Should this issue be closed, or is it tracking something else?

**Comment by shiftkey** [comment]
@koralcem I think the `Merge into current branch` dialog was fixed in #6236 but I'm going to ask @tierninho to confirm that they can't find any more dialogs that behave like this before we close it out.

**Comment by tierninho** [comment]
Confirming that I could not find any other such dialogs with similar behavior.

**Comment by tierninho** [comment]
Actually, I think I found one:

<img width="697" alt="screen shot 2019-01-08 at 9 28 59 am" src="https://user-images.githubusercontent.com/14828183/50848011-e64d7900-1327-11e9-8ac0-b6d5988d4b0e.png">

Steps to reach this modal are:
- Branch > Merge into current branch
- Find conflicts, and then abort the conflict modal
- Attempt to commit the Changes


https://github.com/desktop/desktop/blob/development/app/src/ui/merge-conflicts/commit-conflicts-warning.tsx

**Comment by shiftkey** [comment]
Moving this one back to `more-information-needed` based on the outstanding questions in the previous comment.

**Comment by outofambit** [comment]
@shiftkey thanks for pinging me. I agree we don't want to make <kbd>ESC</kbd> active for the large file size check dialog as the user needs to make an explicit choice about cancelling the commit or continuing.

So, I think we can close this issue. @tierninho does that sound right?

**Comment by tierninho** [comment]
@outofambit sounds right to me, thanks

**Comment by outofambit** [comment]
ack sorry @shiftkey thank you! **definitely** don't want <kbd>ESC</kbd> for conflicted files dialog. (And upon further reflection, the large file check dialog is not destructive and has a clear cancel behavior.)

Closing this issue. If anyone discovers more dialogs that need their behavior modified, lets open a single issue for each. Thank you!
