### ISSUE TITLE
Support for multiple editors

### ISSUE THREAD

**Issue by judge2020** [desktop/desktop#5891]
**Please describe the problem you think should be solved**
I work in multiple editors, including VS Code, Code Insider edition, and Atom and frequently switch between them in my workflows. Currently, GH desktop only supports selecting one of those editors at a time.

**Do you have any potential solutions in mind?**
You should be able to add more than one external editor in options (perhaps a `+` button which would add a new drop-down menu) and the Repository menu should show all editors that were added to options. Concept:

![image](https://user-images.githubusercontent.com/8601934/46900676-ff06d980-ce73-11e8-91df-8decfdadc81a.png)

This stems from #5083 since adding custom editors would likely increase demand for support of this feature, in case you want to add different custom IDE's for different languages.

**Comment by Niall456** [comment]
Would love to see this 👍

**Comment by billygriffin** [comment]
Thanks @judge2020! Can you help me understand under what circumstances you're using each different editor so we can try to evaluate how common it is for people to use more than one editor on a regular basis (as opposed to just very occasionally)?

**Comment by Benjiko99** [comment]
We could keep it the way it is for setting a **primary** editor and additionally list all the editors from the dropdown menu in the Repository menu.
 So you could choose one editor that is opened via a shortcut and others are in the menu.

**Comment by adambirds** [comment]
I think the idea of @benjiko99 is a good one. I have a preferred IDE for most stuff which is VS Code, but I also use Atom, Sublime, Powershell ISE, and others on a regular basis. So I think a drop down with them all listed would be good. Which was my idea back in #3221

**Comment by nicholaswright** [comment]
When I choose an editor in Preferences it already lists my available editors: 
![Screenshot 2019-08-01 at 15 57 33](https://user-images.githubusercontent.com/5063452/62304052-29fb0200-b475-11e9-8ea3-65bd6af69656.PNG)
Couldn't this same list just be displayed in each file's contextual menu?

**Comment by tdaniely** [comment]
How about instead of trying to support 100 different scenario just add a git based integration point.
Something like a git config `ide.launch` or a file `.git/launch`.

This will allow complete customization without high maintenance. Since you're delegating the command syntax to configuration and the spawn mechanics to the shell.
And this will be a lot more generic considering cross tooling since other tools could align on the standard.

Then you can add a settings box under repository settings to configure this, and maybe add a template list.

**Comment by Peter-Schorn** [comment]
What about an option for setting a different editor for each programming language? Then, desktop could determine which editor to open a repository in based on the language that most of it's code is written in.

**Comment by ndraiman** [comment]
> What about an option for setting a different editor for each programming language? Then, desktop could determine which editor to open a repository in based on the language that most of it's code is written in.

Alternatively, allow users to set an external editor per repository.

**Comment by clarelgibson** [comment]
Any movement on this? I have some repositories using R and some using Python, so I want the ability to select RStudio for the R projects and VS Code for the Python projects.

**Comment by steveward** [comment]
I'm going to close this in favor of https://github.com/desktop/desktop/issues/12195 where we are tracking support for default editors on a per-repository basis.
