### ISSUE TITLE
Repository statistics

### ISSUE THREAD

**Issue by thohemp** [desktop/desktop#5894]
Is there any way to show general commit statistics etc about single repositories? Thanks in advance.

**Comment by billygriffin** [comment]
Hi @thohemp, can you say more about what you’re trying to accomplish with this? Do you mean how many commits are present for a given repo?

Generally we prefer to frame issues in terms of the problem they’re intended to solve, so I’d love to understand this a bit better.

**Comment by thohemp** [comment]
Thanks for your answer @billygriffin 

Yes, I mean how many commits are present, when they where commited and when.

**Comment by billygriffin** [comment]
Hi @thohemp, thanks for clarifying. In the “History” tab in Desktop (next to the changes tab) you’re able to see each of the commits and when they were committed in reverse chronological order. On GitHub.com you’re able to see the total number of commits for any given repo, but given the purpose of GitHub Desktop as a workflow tool, we decided not to add that in the app. Hope that helps! I’m going to go ahead and close this but if there’s anything I’m misunderstanding feel free to let me know and we can reopen if needed. Thanks again!

**Comment by thohemp** [comment]
Thanks for clarifying!
