### ISSUE TITLE
客户端可以断点续传吗？ 每次都要全部一起下载

### ISSUE THREAD

**Issue by linlsyf** [desktop/desktop#5896]
**Please describe the problem you think should be solved**
A clear and concise description of what the problem is and who else might be impacted. Screenshots are encouraged.

Example:

> “When I run into a merge conflict, I don’t know where to go to resolve it. Anyone who works off of multiple branches will likely run into this problem at least occasionally.”

**[Optional] Do you have any potential solutions in mind?**
A clear and concise description of one or more solutions you think might solve the problem. Please include any considered drawbacks or tradeoffs, and how users might use your solution(s). Screenshots or mockups are helpful here!

**Comment by shiftkey** [comment]
@linlsyf thanks for reaching out!

A rough translation of the title:

> Can the client resume the breakpoint? Download all together every time

I'm not sure I understand the context enough to help you further. Are you able to provide more details about what you are looking for?

**Comment by linlsyf** [comment]
gfw影响
