### ISSUE TITLE
can't publish branch authentication failed

### ISSUE THREAD

**Issue by modiract** [desktop/desktop#5905]
I am trying to push my changes but the authentication screen keeps popping up although my login is correct.

I think that the problem comes due to 2 steps phone verification.

https://imgur.com/a/9eLoxEt

This is the same problem as:

https://github.com/desktop/desktop/issues/4565
https://github.com/desktop/desktop/issues/1985

The problem is how do I push if I can't login even though my login is correct?

**Comment by shiftkey** [comment]
@modiract it's interesting that you're getting the Basic Authentication dialog here - have you signed into your GitHub account under the **Options** tab? That flow will handle any 2FA prompt, whereas our Basic Authentication is only designed for non-GitHub hosts.

Also, could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by modiract** [comment]
_"it's interesting that you're getting the Basic Authentication dialog here - "_

I thought it had to do something with the authentication but it might not be that.

This is the error log. https://ufile.io/o0q4z

**Comment by steveward** [comment]
@modiract it looks like there may be an issue your stored credentials. Can you try logging out and then logging back in to GitHub Desktop to see if that gets things working? You can do this by going to the file menu in GitHub Desktop and selecting `File` > `Options` > `Accounts`.

**Comment by modiract** [comment]
Thank you it works The problem was that if you publish/ push your changes and need to log in, you won't be able because you need a phone verification. Because of this the login isn't working and not showing any kind of way to insert your authentication code. However, if you go to file options accounts and login there, it does show the authentication code to insert.

**Comment by steveward** [comment]
Thanks for the update @modiract. The specific case of attempting to clone a private repository when a user is *not* logged should be addressed by the changes in https://github.com/desktop/desktop/pull/5816. Attempting to clone a private repository when not logged in will return a `404` status code, which will then throw the error that the repository does not exist and will mention to the user to make sure they are logged in correctly. I'm going to close this issue out, but let me know if you have any further feedback about this!

**Comment by pd1138** [comment]
Still an issue

**Comment by shiftkey** [comment]
@pd1138 if that's the case could you please open a new issue and fill out the bug report template, so we can investigate what might have changed?
