### ISSUE TITLE
Reference to “tsonfig.json” in package.json

### ISSUE THREAD

**Issue by gscscnd** [desktop/desktop#5908]
In `package.json`, line 12…

https://github.com/desktop/desktop/blob/4272bda3720a4e00b379c83643229be9565503cc/package.json#L12

…there’s a reference to `tsonfig.json`. There’s no such file, so it’s probably a typo. It was introduced in ff3c5a8c1e44c0b478dce3730bde15e6df7090e2.

**Comment by shiftkey** [comment]
@gscscnd that seems like an easy change - are you interested in making a change and submitting a PR?

**Comment by gscscnd** [comment]
Well, [there’re no docs about that `-P` argument](https://mochajs.org/#usage), so should it be simply removed? (That is, instead of fixing the typo.)

**Comment by shiftkey** [comment]
@gscscnd that seems reasonable. We have a decent CI setup that will likely catch anything if it's not the right change, so go for it!

**Comment by billygriffin** [comment]
Thanks @gscscnd! @outofambit Would you mind taking a quick look please? 😄
