### ISSUE TITLE
Changes/History do not switch with Ctrl-Tab shortcut if the focus is outside of the changes/history list or content view

### ISSUE THREAD

**Issue by a-golovanov** [desktop/desktop#5911]
## Description

Changes/History do not switch with Ctrl-Tab shortcut if the focus is outside of the changes/history list or content view.

## Version

* GitHub Desktop: 1.4.2

* Operating system:
macOS 10.14

## Steps to Reproduce

1. Click "Fetch ..." button
2. Press Ctrl-Tab -> nothing happened

Alternative steps:
1. Select any view in Changes/History tab or content view
    a. item in the changes/history list
    b. Summary or Description field in the Changes tab
    c. changed files list or diff view in the content view
2. Press Ctrl-Tab -> tabs switch (as expected)
3. Press Ctrl-Tab again -> nothing happens

### Expected Behavior

Pressing Ctrl-Tab should always switch tabs as long as tabs are present on the screen and there is no modal dialog, popup or any other obstructing view is present on the screen

### Actual Behavior

Pressing Ctrl-Tab switches tabs only when the focus is set to a view inside Changes/History tab or content view

**Comment by billygriffin** [comment]
Thanks @a-golovanov! I was able to reproduce. Just a note that you can also use the specifically defined Desktop keyboard shortcuts Cmd+1 and Cmd+2, respectively, on macOS to get to the "Changes" and "History" tabs. I'm going to classify this as a small bug and if someone from the community is able to help knock it out, that'd be great. 😄
