### ISSUE TITLE
Number formatting for commit count in push button

### ISSUE THREAD

**Issue by cheshire137** [desktop/desktop#5914]
When I have a lot of commits to push, say from switching to a very old branch and merging in the latest master, the push button could be formatted with commas (or periods, depending on locale) to make the commit count more readable:

![image](https://user-images.githubusercontent.com/82317/47041237-e1749100-d14d-11e8-866b-070f3333b5f8.png)

In the above screenshot, I'd like to see "16,236" or even just "16k".

**Comment by shiftkey** [comment]
@cheshire137 we're already discussing this in #1245
