### ISSUE TITLE
Emoji Not Being Displayed under Current Branch

### ISSUE THREAD

**Issue by n0shake** [desktop/desktop#5915]
macOS High Sierra 10.13.6
Macbook Pro 2015 Retina
Github Desktop 1.1.1

Steps to Reproduce:

1. Create a new branch under an existing repo
2. Name the branch using emojis
3. See the branch name not being reflected in the UI

<img width="1040" alt="screen shot 2018-10-16 at 3 45 43 pm" src="https://user-images.githubusercontent.com/8280282/47046406-a3ca3500-d15a-11e8-8e88-fc3e13c1e599.png">

<img width="563" alt="screen shot 2018-10-16 at 3 46 38 pm" src="https://user-images.githubusercontent.com/8280282/47046436-b3497e00-d15a-11e8-8e20-07f77a70e09a.png">

**Comment by shiftkey** [comment]
I tested this out using a different emoji with the latest `master` build:

<img width="496"  src="https://user-images.githubusercontent.com/359239/47093716-26590000-d200-11e8-950e-d783193b7a5b.png">

But then I chose the 🕷 emoji and I did see this issue (note that it's rendered fine in the branch list):

<img width="583"  src="https://user-images.githubusercontent.com/359239/47093805-543e4480-d200-11e8-8c5e-7c67290c663b.png">

I'm not quite sure why these are different, but 👍 to `help wanted` for someone to dig into.

**Comment by shiftkey** [comment]
Also, this seems to work fine on Windows 10 (use Windows Key and <kbd>,</kbd> to get to the Emoji Picker) so I'm going to mark it as macOS only for now:

<img width="563" src="https://user-images.githubusercontent.com/359239/47094037-cca50580-d200-11e8-9cf3-a4e2e9bd1929.png">

**Comment by tierninho** [comment]
Did some investigation and here is the problem: the font weight in the `toolbar` is blocking the emoji from rendering.

<img width="1113" alt="screen shot 2018-11-08 at 2 06 31 pm" src="https://user-images.githubusercontent.com/14828183/48230644-a0dcf180-e360-11e8-9cff-2b704e56c13a.png">

Start here:
https://github.com/desktop/desktop/blob/master/app/styles/ui/toolbar/_toolbar.scss

Some findings from other repos with the same problem.. which might help:
https://github.com/flutter/flutter/issues/11108
https://bugs.chromium.org/p/chromium/issues/detail?id=551843

**Comment by billygriffin** [comment]
Since we haven't seen this come up again, we're going to close it for now as something that happens to rarely to prioritize. Happy to reopen if it becomes an issue for others.
