### ISSUE TITLE
Both Github.com and Github Desktop displays incorrect diff for files containing \r

### ISSUE THREAD

**Issue by vczh** [desktop/desktop#5919]
## Description
Refer to [here](https://github.com/vczh-libraries/Document/commit/e62cd132fdcec45653ed294fc22632c289aadc96) and [here](https://github.com/vczh-libraries/Document/commit/e71bea01d5ea1c4333e1bfa7f5974089cfeaa5ce)

I made a mistake which inserted `\r` instead of `\r\n` for just a few lines in `Parser_Expr.cpp`. And then both Github.com and Github Desktop display incorrect diff for this file, by showing that the whole file is changed, not just those lines I was editing. I changed all `\r` to `\r\n` in the second change.

If Github doesn't accept that `\r` works as `\r\n`, that's fine. But in that file most of the lines ends with `\r\n`, there is no reason to show that the whole file is changed. At least it can show diff like:

**Expected Behavior**
```
1111111\r\n
<<<<
2222\r\n3333\r\n
----
2222\r3333\r\n
>>>>
4444
```

But now it is
**Actual Behavior**
```
<<<<
1111\r\n
2222\r\n
3333\r\n
4444
----
1111\r\n
2222\r3333\r\n
4444
>>>>
```

## Version
* GitHub Desktop: 1.4.2
* Operating system: Windows 10.0.17134.345

## Steps to Reproduce
Just see my links to my changes

### Expected Behavior
Described in description

### Actual Behavior
Described in description

## Additional Information
N/A

### Logs
Given that the website has the same problem I believe you are able to find the issues without my log.

**Comment by shiftkey** [comment]
> Just see my links to my changes

@vczh Can you be more specific? The diff for `Parser_Expr.cpp` in each commit is ~1400 lines and I'm not quite sure what I'm looking for exactly.

**Comment by vczh** [comment]
@shiftkey Hi, in order to get the idea you can read the second diff, which I changes just a few `\r` to `\r\n` from line 48 to 54. \r will be rendered as `^M` so it is very easy to find.

**Comment by steveward** [comment]
Closing as stale.
