### ISSUE TITLE
lib/git/commit functions could return SHA on success

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#5923]
(From https://github.com/desktop/desktop/pull/5910#discussion_r225712202)

Currently, `createCommit` and `createMergeCommit` (both in https://github.com/desktop/desktop/blob/master/app/src/lib/git/commit.ts)  return a boolean or null on success and throw an error on failures. It would be nice to have them return the SHA of the commit created on success.

This will require parsing the git output from commit to get the SHA and adding some test coverage.

**Comment by shiftkey** [comment]
>  It would be nice to have them return the SHA of the commit created on success.

Are there scenarios you have in mind where having this would be helpful?

**Comment by outofambit** [comment]
It would make testing a little easier, since you could check if the returned commit exists. perhaps there are places in the UI where we could use that too?

Mostly, @iAmWillShepherd and I were brainstorming other things to return besides `true` or `void` to indicate success and the SHA seemed slightly more informative.

**Comment by shiftkey** [comment]
@outofambit I'm into it - just wanted to tease out a bit more context about the motivation 🤘
