### ISSUE TITLE
ANSI character problem

### ISSUE THREAD

**Issue by hyagli** [desktop/desktop#5925]
## Description
When viewing the changes in an ANSI encoded file. The turkish characters are displayed as question marks.

## Version

* GitHub Desktop: 1.4.2
* Operating system: Windows 10 64 bit with Turkish locale set.

![image](https://user-images.githubusercontent.com/3749620/47096287-874ffa80-d237-11e8-85a6-c13414b09f36.png)

**Comment by billygriffin** [comment]
Thanks for the report @hyagli, and sorry about that. We're tracking non-UTF8 characters in https://github.com/desktop/desktop/issues/3923, so please follow along there.

**Comment by mlferreira151276** [comment]
i have the same problem, not resolved

**Comment by murchelon** [comment]
hi, same problem here: I have files that are in ANSI (windows-1252) and they show up with a question mark, in Github Desktop. When viewing the file with other way, it shows up correctly. Thanks a lot for this great program!
