### ISSUE TITLE
Add a button to the branch selector

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#5929]
It's not obvious how to merge one branch into another in Desktop.

:warning: See #5555 for additional context :warning: 

This issue is marked as help wanted to gives others the chance to get involved in feature iteration. Please leave a comment below if you'd like to pick this up 😄.

### Goal

We want to improve the discoverability of merging branches. At the moment, we have 2 ways of doing this. 

1. The top-level menu: **Branch -> Merge Into Current Branch**
![screen shot 2018-10-17 at 4 05 38 pm](https://user-images.githubusercontent.com/1715082/47116497-6e3f4d80-d227-11e8-9245-28abd9a62dcd.png)

1. Initiating a branch comparison
![2018-10-17 16 13 09](https://user-images.githubusercontent.com/1715082/47116556-962eb100-d227-11e8-8592-56b1d7fab815.gif)

### Proposed Solution

Adding a button to the *Branch Selector* should bring the merge action closer to where most would expect it to be. This button will behave just like the menu button and bring up the _Merge Branch_ dialog where a user can select the branch they'd like to merge.

**Mockup**
<img width="1010" alt="46970036-c120d580-d06c-11e8-9fd9-31a54974977c" src="https://user-images.githubusercontent.com/1715082/47116615-bb232400-d227-11e8-96d8-dc03ca64b112.png">

**Comment by shiftkey** [comment]
@iAmWillShepherd I'm trying to reconcile the urgency of this (milestoned for the next release) with accepting external contributions for this (that might not be picked up soon). Can you elaborate on when you think this should be worked on?

**Comment by iAmWillShepherd** [comment]
Just posting this here for context:

We decided to de-scope this from the milestone since it's really a task of a larger issue. I also removed myself from the assignee in favor of being the assigning of the tracking issue, #5555.

**Comment by bruncun** [comment]
I’d like to pick this up. 😊

**Comment by iAmWillShepherd** [comment]
That's great, @bruncun. Since this is part of feature iteration, there is a timeline we're working on. The goal is to get these changes in this week so that we can ship them in our beta release next week. If you're still able to take this, feel free to open up a PR. I recommend opening your PR sooner that way we can advise as you make progress.
