### ISSUE TITLE
It's unclear which branch is being merged into another in the merge dialog

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#5930]
The directional merge flow is not as obvious as it could be. It should be perfectly clear which branch you're merging into which branch.

:warning:  See [#5555](https://github.com/desktop/desktop/issues/5555) for additional context :warning:

This issue is marked as help wanted to gives others the chance to get involved in feature iteration.

**Current Merge Dialog**
![screen shot 2018-10-17 at 4 42 51 pm](https://user-images.githubusercontent.com/1715082/47118413-caf13700-d22c-11e8-8d9a-a58c089fed7b.png)
Note that we are merging `git-store-cache` into `master`.

### Goal

We want to make it clearer what branch will be merged into another. 

### Proposed Solution

Make two changes:

1. use the title of the dialog to state what branch is being merged and the _direction_ it's being merged
1. Move the conflicts hint above the _Merge_ button

**Mockup**
<img width="1010" alt="46981644-233e0280-d08e-11e8-9a17-c76e9dca38b5-2" src="https://user-images.githubusercontent.com/1715082/47118397-bc0a8480-d22c-11e8-99f5-c5826c482054.png">

### Risks
* Branch names can be an arbitrary length, so it's worth thinking about how to present a longer branch names in a fixed width window. 

The CSS that controls the ellipsis is located here: https://github.com/desktop/desktop/blob/19d5fdd4621c6147979c3ac3fdbc77c89d8d4d6a/app/styles/ui/_branches.scss#L204-L217 for some prior art in that area.

**Comment by JQuinnie** [comment]
Hi,
I’d like to take a stab and work on this issue, thanks!

**Comment by JQuinnie** [comment]
Hi @iAmWillShepherd ,

Love to get a sanity check before I move onto the other portion of this issue.

See current modal output below;

![image](https://user-images.githubusercontent.com/29465981/47193086-4d9df300-d30e-11e8-9460-438a6664a8b2.png)

Question:
1. I could not seem to replicate the merge conflict in your 2nd screenshot, for me it does not show a conflict and allows merging from modal, but after you click the button, it goes into a different view that brings up the merge conflict diffs... is this a feature for later as discussed in #5555 ? Just double checking...
2. Both screenshots have an icon above merge dialog (green check and orange warning), are those features to be pulled in on this issue? If so, can you point me to where I would be able to get those icons?
3. Styling in the form of a line break between dialog and button, would you like some?

**Comment by iAmWillShepherd** [comment]
> I could not seem to replicate the merge conflict in your 2nd screenshot, for me it does not show a conflict and allows merging from modal, but after you click the button, it goes into a different view that brings up the merge conflict diffs... is this a feature for later as discussed in #5555 ? Just double checking...

No need to replicate the merge conflict as this issue is about presentation. So long as this bit of code is above the `ButtonGroup` component, you should be fine. https://github.com/desktop/desktop/blob/44eb18b860cbbd5317cd647d116bf883197c83e4/app/src/ui/merge-branch/merge.tsx#L315-L317

If you're curious how to see the conflict warning, you have to try to merge a branch that would produce conflicts.

> Both screenshots have an icon above merge dialog (green check and orange warning), are those features to be pulled in on this issue? If so, can you point me to where I would be able to get those icons?

Merge info is encapsulated within the `renderNewMergeInfo` function. https://github.com/desktop/desktop/blob/44eb18b860cbbd5317cd647d116bf883197c83e4/app/src/ui/merge-branch/merge.tsx#L113-L140

Controlling which icon to render is encapsulated in the `MergeStatusHeader` component.
https://github.com/desktop/desktop/blob/44eb18b860cbbd5317cd647d116bf883197c83e4/app/src/ui/history/merge-status-header.tsx#L44-L54

As these pieces are already implemented, you don't have to worry about pulling in any new features.

> Styling in the form of a line break between dialog and button, would you like some?

I think you could use use some margin to separate the merge info from the button. 

cc @ampinsk to get her input on your third question.

**Comment by ampinsk** [comment]
@JQuinnie thanks for picking this up! Some more margin between the text and button on the bottom would be great.

**Comment by tierninho** [comment]
Maybe this issue should be addressed here too? https://github.com/desktop/desktop/issues/5970

Secondly, should we edit the merge hint text "This branch is up to date with..." with the actual branch name? It will match our other iterations. This is in regards to https://github.com/desktop/desktop/blob/aa99aa3aceba96f3b8b9e793334b9c9346dc17ec/app/src/ui/merge-branch/merge.tsx#L183

**Comment by iAmWillShepherd** [comment]
> Maybe this issue should be addressed here too? #5970

@tierninho Let's keep the PR for this issue focused. We can get that fix in as a separate PR. 

@JQuinnie, if you're interested in tackling #5970 as well, could you open a new PR for it? Since the merge flow is iteration on feature work we expect to deliver in the next beta, adding additional scope could delay getting this shipped by next week.

**Comment by iAmWillShepherd** [comment]
The final piece of this was completed in #6027.
