### ISSUE TITLE
Large files, which one?

### ISSUE THREAD

**Issue by HedvigS** [desktop/desktop#5932]
**Identify which files are too large**
When merging, sometimes I get an error message that a file is over 100 MB. Could the dialogue box please include which they are? That would be practical.

**Comment by billygriffin** [comment]
Thanks for the idea @HedvigS! We agree, and we’re tracking that in #997, so I’m going to go ahead and close this issue. If you have a desire to get involved it is labeled as help wanted, and we appreciate it regardless!

**Comment by HedvigS** [comment]
I often find myself not being able to find the file and resolve the conflict. My current method of solving these situations is rather crude, but has proven successful.

* move the folder where I have made changes to outside of the repos
* remove the clone from Github Desktop and move to trash
* re-clone the same repos
* put the folder back into re-cloned repos
* comity and push and pull again
