### ISSUE TITLE
can't push to repository in app (publish repository modal displayed)

### ISSUE THREAD

**Issue by FaithInMotion** [desktop/desktop#5936]
## Description
I updated my system from High Sierra to Mojave. Upon update, I lost the ability to publish.

When I'm looking at the Desktop app, I have the "Push" command for my branch in my repository.
<img width="494" alt="screen shot 2018-10-18 at 1 44 24 pm" src="https://user-images.githubusercontent.com/7316029/47173627-8fae4100-d2dc-11e8-9681-0b81b174a972.png">

However, when I click this: 
<img width="488" alt="screen shot 2018-10-18 at 1 49 56 pm" src="https://user-images.githubusercontent.com/7316029/47173706-c84e1a80-d2dc-11e8-8729-370bae050c2a.png">

What I have been doing to complete my work is commit here, then use the command line to 
`git push origin marketplace_product_sort`

It seems to be all branches on this repository - at least this is the second branch I've come across.

I have been going through a few issues here but they were all relegated to Windows 10 issues, and they didn't seem to quite match. If I am wrong I'll happily be pointed to a good issue to follow.

## Version

* GitHub Desktop: 1.4.2

* Operating system:
Mac OSX Mojave 10.14

## Steps to Reproduce
1. Click `Push Origin`
2. Get `Publish?` box
3. Close box without publishing, go to CLI
4. `git push origin my_branch`
5. Branch pushes correctly without errors

### Expected Behavior
Github desktop pushes normally like it used to

### Actual Behavior
Refuses to push

### Logs

[2018-10-18.desktop.production.log](https://github.com/desktop/desktop/files/2493044/2018-10-18.desktop.production.log)

**Comment by shiftkey** [comment]
@FaithInMotion thanks for the details. At first glance I'm not sure why we're showing the publish dialog despite the fact we detect you have an `origin` remote and a tracked branch.

Out of curiosity, do you see the padlock icon next the repository switcher in the top-left? That's our way of detecting that you're working with a private GitHub repository, and if it's reverting to a "computer monitor" icon then we might have messed up our GitHub association checks - which would explain why it suggests publishing.

The other bit of information I'd like is to confirm whether your `origin` remote is a HTTPS or SSH URLs, and if ends in `.git`. That will help me troubleshoot the issue further.

**Comment by FaithInMotion** [comment]
This is what I have currently:

<img width="244" alt="screen shot 2018-10-18 at 2 13 54 pm" src="https://user-images.githubusercontent.com/7316029/47174983-23354100-d2e0-11e8-84e3-1a91b9e35e46.png">

**Comment by FaithInMotion** [comment]
Is this what you are looking for? (I'm not overly new to this but sometimes I lose the terminology)

```
(marketplace_product_sort)> git remote -v
origin	git@github.com:/JVZoo/JVZoo.git (fetch)
origin	git@github.com:/JVZoo/JVZoo.git (push)
```

**Comment by shiftkey** [comment]
> This is what I have currently:

That's the current branch - what about the area to the left of that?

> Is this what you are looking for?

Cool, SSH URLs with a `.git` suffix. That helps - I think I know where this is lurking.

**Comment by FaithInMotion** [comment]
Sweet, thanks! I'm just happy it's an actual issue and not just me losing my marbles for once :P

**Comment by shiftkey** [comment]
@FaithInMotion I haven't been able to reproduce the issue as you're seeing it, but I think I know the root cause.

Seeing that your `Push origin` button matches to the `origin` remote defined in your Git config, I looked at that code to see what that is using to render itself:

https://github.com/desktop/desktop/blob/0fc2294c119d0186e2d5db75ce74174233d57924/app/src/ui/app.tsx#L1573-L1584

So it's using our `IRepositoryState` in-memory object. Cool. What about the push operation itself?

https://github.com/desktop/desktop/blob/0fc2294c119d0186e2d5db75ce74174233d57924/app/src/lib/stores/app-store.ts#L2391-L2396

This is using our `GitStore` in-memory object, and for some reason it's `null` in your case so we show the dialog.

I've opened https://github.com/desktop/desktop/pull/5948 to address the `push` issue.

**Comment by shiftkey** [comment]
As to the other issue (the icon being a generic "computer" rather than the "padlock" icon), I see this message in the log:

```
2018-10-18T17:21:16.211Z - warn: [ui] fetchRepository: '/JVZoo/JVZoo' returned a 404
2018-10-18T17:21:16.211Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: JVZoo - FaithInMotion (has token)
```

This suggests that, while Desktop has a valid OAuth token associated with your account, our API check for the repository is failing (because it's a private repository). This is relatively minor if you are using an SSH URL for the repository and have that configured correctly to push and pull, but maybe signing out and into your GitHub Account (from under the **Preferences** tab) might resolve it.

**Comment by shiftkey** [comment]
@FaithInMotion actually there's one more bit of info I think I'm missing. Could you run this command against your feature branch (so note `master`) and attach the output:

```
$ git status --porcelain=2 --branch
```

For example, on my side:

```
$ git status --porcelain=2 --branch
# branch.oid 921671d721043c2cd69f21f8e9b8b49b3573b737
# branch.head extract-ci-logic
# branch.upstream origin/extract-ci-logic
# branch.ab +0 -0
```

I want to confirm that you have a `branch.upstream` value set here (when you were pushing from the command line you specified the remote and branch name) and that might be the bit I'm missing to reproduce it in the same way as you're seeing it.

**Comment by FaithInMotion** [comment]
I will do so now. I cannot pull from the Desktop either - nothing happens when clicking the button. I am in a different branch now (all the issues are the same). Hopefully that doesn't matter! If it does let me know. This branch has ALL the problems from the last one, so nothing has changed.

```
16:39:40 ~/jvzoo/JVZoo (feature/lorie/preapproval_dashboard)> git status --porcelain=2 --branch
# branch.oid 86538de086d1f8592f47ba597732ac16c24632e4
# branch.head feature/lorie/preapproval_dashboard
# branch.upstream origin/feature/lorie/preapproval_dashboard
# branch.ab +1 -2
20:59:20 ~/jvzoo/JVZoo (feature/lorie/preapproval_dashboard)>
```

I will try logging out and back in now.

**Comment by FaithInMotion** [comment]
Signed out and back in, restarted the app. Still have the computer screen.

**Comment by j-f1** [comment]
Can you try removing the repository from the app and adding it back in?

**Comment by webchang** [comment]
I'm experiencing the same issue with GitHub v2.0.3 on macOS Mojave v10.14.5.  I have to use CLI to push my updates back to the origin, which is a "public" repository hosted by GHE.  Moreover, after I use CLI to pull updates from the origin, the text of "Fetch origin" changes though I could not use the icon to perform the task.

**Comment by shiftkey** [comment]
@webchang please follow along with #7713 which I feel is very similar to what you're seeing
