### ISSUE TITLE
Ability to submit and interact with GitHub issues via GitHub Desktop

### ISSUE THREAD

**Issue by coltenkrauter** [desktop/desktop#5944]
**Ability to submit issues via GitHub Desktop**
As a GitHub user I would like the ability to submit GitHub issues via the GitHub desktop application so that I can manage my project with the same app that I use regularly for committing code. 

**I think that adding a button to the right of the Fetch origin button would fit nicely**
An **Issues** button to the right of the **Fetch origin** button could load GitHub issues for the current selected repository with the ability to manage issues in the main pane. 

**Mock up**
![image](https://user-images.githubusercontent.com/18080897/47190811-63a0b900-d2f8-11e8-911a-07b6517c2082.png)

**Comment by billygriffin** [comment]
Thanks for the detailed description @coltenkrauter, this is useful to have when we're able to take a look at how this might add value. We're tracking this in #2376, so I'm going to close this in favor of that one - I know it looks closed, we're actively evaluating all the `future proposal` issues.

**Comment by babski123** [comment]
Is there any update on this issue?

**Comment by andreiwow2** [comment]
I am also interested in this..

**Comment by LucaColombi** [comment]
still nothing? :(

**Comment by ward0** [comment]
nothing?

**Comment by vgavinash** [comment]
@billygriffin its still not come.

**Comment by kaanchan** [comment]
I find this functionality very useful in the mobile app. Wondering why the feature is not mirrored in the desktop app.

**Comment by sirius-pro** [comment]
me too :) it would be nice to see this feature in desktop app with all featured like labels, assigns etc.

**Comment by 0xBunzy** [comment]
Still nothing?

**Comment by Matatosker** [comment]
You guys should really add this. I have to go into the app and open up the website to add an issue or just keep my phone next to me with the app open to quickly add or tick things off the list. Iv been using the issues as a checklist for the team.

Would be a valuable feature
