### ISSUE TITLE
Blank merge branch dialog doesn't disappear when press esc

### ISSUE THREAD

**Issue by bangnokia** [desktop/desktop#5946]
## Description
When merge dialog is blank and i press esc, it doesn't disappear, and it user must to use mouse to close it or press cmd + w

## Version
* GitHub Desktop: 1.4.3
* Operating system: macos mojave

## Steps to Reproduce
1. Press cmd + shift + m
2. Press esc

### Expected Behavior
When press esc, the dialog should be disappeared

### Actual Behavior
Nothing happen

**Comment by shiftkey** [comment]
@bangnokia thanks for the report!

I'm going to close this out in favour of #5889 which has some more details about the underlying issue.
