### ISSUE TITLE
"What's New" modal UI broken 

### ISSUE THREAD

**Issue by agisilaos** [desktop/desktop#5958]
## Description

When you tap "What's new" button when it appears with an update, the UI is broken.  If the release notes list is bigger than the "view" inside it, the content is not scrollable.

## Version
* GitHub Desktop: `v. 1.4.2`
* Operating system: `v. 10.14 (18A391)`

## Steps to Reproduce
1. When an update is available click on the `What's new` button
2. Observe pop-up, the release notes are not only inside the view but below it as well.

### Expected Behavior
Release notes should be in the view and the content should be scrollable

### Actual Behavior

Release notes are not placed properly inside the view and the content isn't scrollable

## Screenshot
![screenshot 2018-10-20 22 59 15](https://user-images.githubusercontent.com/10944108/47260090-49640800-d4bd-11e8-8040-5132965a5b96.png)

**Comment by dsanders11** [comment]
That was fixed by #5854, as mentioned under the bugfixes in your screenshot. :-)

**Comment by billygriffin** [comment]
Yep, this will finally be behind us going forward. Thanks @agisilaos and @dsanders11!
