### ISSUE TITLE
Code change doesn't reflect on github website after pushing

### ISSUE THREAD

**Issue by Yuhanlolo** [desktop/desktop#5960]
## Description

I have been using the GitHub desktop to manage my project for a while and everything works well. But today, I just found that the change of the code doesn't reflect on the Github website after I clicked the "push origin". I did this every day and I can see the changes I made yesterday. But none of the changes I made today reflect on the Github website (I did several "push origin" today). I tried this for my other projects and got the same results.

Btw, I didn't get any error when I click "push origin".

## Version

1.4.3

* GitHub Desktop:

* Operating system:
macOS

### Expected Behavior

After "push origin", the change of code should reflect on the GitHub website.

### Actual Behavior

After "push origin", the change of code did not reflect on the GitHub website.

**Comment by niik** [comment]
Closing in favor of #5963
