### ISSUE TITLE
Change of code doesn't reflect on Github website after pushing without an error

### ISSUE THREAD

**Issue by Yuhanlolo** [desktop/desktop#5963]
## Description

I have been using Github desktop for my project for a while and it was working well. However, today I found after I click "push origin", the change of code doesn't reflect on the Github website. I did this every day and I can see the changes every time when I went to the Github website. I changed my code and pushed origin a couple of times today but none of the changes reflect on the Github website. I didn't get any error when I "push origin". I tried it for my other projects and got the same results.

## Version

1.4.3

* GitHub Desktop:

* Operating system:
macOS

### Expected Behavior

The change of code should reflect on the Github website after pushing.

### Actual Behavior

The change of code did not reflect on the Github website after pushing.

**Comment by niik** [comment]
Hey @Yuhanlolo, GitHub had a service outage earlier today around the time you posted this which I believe was the cause of your issue. One of the symptoms of this particular outage was GitHub.com showing stale, and/or, inconsistent data.  See https://status.github.com.

If your changes aren't reflected on GitHub.com even after status.github.com reports that the outage is over please try pushing again and then comment here again and we'll have another look at it.

**Comment by Yuhanlolo** [comment]
@niik Thanks! Everything goes back to work now. Sorry for the spam. The page turned to 404 after I submit the issue so I thought I didn't submit successfully and refreshed a couple of times.

**Comment by billygriffin** [comment]
@Yuhanlolo It's totally fine, not like you did it intentionally. Thanks again and apologies for the confusion on our end. 😄
