### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by planetf1** [desktop/desktop#5968]
## Description

Dark mode has insufficient contrast

## Version

* GitHub Desktop:
1.4.3

* Operating system:
10.14.1 Beta (18B67a)

## Steps to Reproduce

Enable dark mode

### Expected Behavior

readable text

### Actual Behavior

Text is not readable

## Additional Information

When 'dark mode' is enabled the 'darker text' ie under change history the 'ABC committed 4 days ago' is a little too dull and straining to read. The directories in the path on the middle bar are similar, as are the diff lines ie
@@ -64,5 +63,13

This is also noticeable with the labels for current repository, current branch
Could we make these a little lighter 

Also making the background a little darker may help. 

If I compare with something like iTerm2 the text is not as clear due to the lower contrast

### Logs

n/a

**Comment by niik** [comment]
Hey @planetf1, thank you for opening this. Could you please attach a screenshot with the areas of the app that you feel are hard to read highlighted? That would make it a lot easier for me to understand exactly what areas we're talking about.

> If I compare with something like iTerm2 the text is not as clear due to the lower contrast

I think, to some extent, this is to be expected. The dark theme is supposed to be a bit gloomy and if I understand the issue we're talking primary about secondary text whereas iTerm gets to treat everything as primary text. That said we should certainly stay above a minimum 4.5:1 contrast ratio ( WCAG AA) for all text and if we're not we should look into that.

It would also be very helpful if you could share a little bit about your environment, what screen resolution are you using and what monitor do you have? Do you find the default theme equally hard to read?

**Comment by planetf1** [comment]
[
<img width="1317" alt="screenshot 2018-10-23 at 11 27 24" src="https://user-images.githubusercontent.com/7292002/47354447-ae368280-d6b6-11e8-8b0d-4c49e8c33230.png">
](url)

For me in this picture. From the top left

'Current repository' is borderline
'Select branch to Compare' is very very pale
'Nigel Jones committed 3 days ago' - under the second change is pale
In the middle pane the directory structure is pale - though a slightly larger font
For the main body of the file the dark green background reduces contrast significantly, and the comments are very pale (and can be quite useful!). Same with the annotations

**Comment by planetf1** [comment]
If the dark theme is gloomy maybe I just prefer brighter colours (too much for some?) so docs on customization may suffice ... 

The screen I was using was a Macbook Pro, 15", 2016 touchbar model running at default retina resolution/setup

I then moved the window to my LG 27UD88 4K IPS monitor (in sRGB picture mode) and actually I would be on the verge of retracting my comments. It is FAR more readable. The contrast is better, the green is much greener, in fact .. absolutely wouldn't have opened an issue.

So the challenge seems to be the macbook pro screen. Moving my intellij window over and it is also not as good (though due to the higher contrast it's still very readable). As I mentioned may be too extreme for some

<img width="2048" alt="screenshot 2018-10-23 at 11 35 08" src="https://user-images.githubusercontent.com/7292002/47354864-c22eb400-d6b7-11e8-8690-c520042390a9.png">

**Comment by planetf1** [comment]
The default theme for github desktop is fine. Looking at the desktop itself for the macOS default dark theme I would be inclined to raise a github issue (if apple was all open source. lol) on the same. So maybe therein lays the challenge - macos retina screen config

**Comment by planetf1** [comment]
Turning brightness to max on internal screen (it's only 50% on the LG external display)and the contrast seems fine.

So this could be a case of 'user error' / personal challenges dealing with the mix of light themed apps (browser, whatsapp) and dark themed (desktop, github desktop). With the brightness so high whatsapp white background, browser are actually far too glaring. Then found a mid point where I think I have a good balance.

Hope the comments have helped, but this may be one to consider closing. My bad.

**Comment by niik** [comment]
> Hope the comments have helped, but this may be one to consider closing.

These comments have been super helpful @planetf1, we're really thankful that you took the time to open an issue! It's hard to strike the ideal balance when designing a theme.

> 'Current repository' is borderline
> 'Nigel Jones committed 3 days ago' - under the second change is pale

Seeing as these meet the WCAG AA threshold and weighing in the importance of the distinguishing contrast for the visual hierarchy in these I'm going to say that we should leave them as.

> 'Select branch to Compare' is very very pale

It really is, and looking at its contrast ratio I calculate it to 3.51:1 which is below the WCAG AA threshold so I would like to address this one. I've opened #5978 to track this issue.

> For the main body of the file the dark green background reduces contrast significantly, and the comments are very pale (and can be quite useful!)

I'm getting 4.64:1 on the comments which is on the low end but still within the threshold. I can see us bumping this a smidge but since it's within limits I'm not going to open an issue about it.

---

Thank you again for your feedback, subscribe to #5978 to follow along on the placeholder text resolution and please let us know if there's anything else you spot that could use some improvement.
