### ISSUE TITLE
Truncate branch name in merge hint

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#5970]
A long branch name should be truncated in both locations where we show a merge hint: 

- Modal surfaced when selecting `Merge into Current Branch...` in the View menu
<img width="834" alt="screen shot 2018-10-22 at 11 54 36 am" src="https://user-images.githubusercontent.com/14828183/47313825-cc3bae80-d5f4-11e8-8df7-3c34abf59a0e.png">

- Changes tab 
<img width="511" alt="screen shot 2018-10-22 at 12 12 05 pm" src="https://user-images.githubusercontent.com/14828183/47313821-c9d95480-d5f4-11e8-83a0-272cfaa4f107.png">

Note: the modal is a fixed width and the Changes pane is flexible so I am not sure of the scalability in making the truncations adhere to the same character limit.

tested in: 1.4.4-beta0, mac

**Comment by JQuinnie** [comment]
Hi @tierninho ,
@iAmWillShepherd mentioned this in issue #5930 under **Risks**. I will pull this into a new PR that references both issues as I am currently planning to fix this.

**Comment by iAmWillShepherd** [comment]
Tagging #5977 since it also will need to handle long branch names correctly.

**Comment by tierninho** [comment]
Re-adding `help-wanted` as this is not fixed.
