### ISSUE TITLE
Case-sensitive branch names

### ISSUE THREAD

**Issue by mediocregatsby** [desktop/desktop#5971]
## Description

Github desktop client is not recognizing branch names on a case-sensitive basis. In my github corporate repo, we had a branch named 'Milestone' but one dev accidentally checked out and pushed to a branch named 'MIlestone' (not the capital 'i' in the second character). Git and github will track changes to these as different branches, but the desktop client will not. When checking out a branch using the desktop client, it will simply pick one and hide the existence of the other one.

## Version

* GitHub Desktop: 1.4.3 

* Operating system: 10.13.6 (17G65)

## Steps to Reproduce

1. Use the command line to cut and push a branch with lower case characters
2. Use the command line to cut and push a branch with the same name, but upper-case at least 1 character
3. Use the command line to push different non-conflicting changes to both branches
4. Use github desktop client to search for both distinct branches (bug causes you to see only 1)
5. Use github desktop client to pull changes for one of the branches (bug causes your branch to enter a buggy state)

### Expected Behavior

Github desktop client can recognize case-sensitive branch names to distinguish between them

### Actual Behavior

Github desktop client fails to distinguish case-sensitive branch names

**Comment by niik** [comment]
Hey @mediocregatsby, thanks for opening this. While the internals of Git are case-sensitive it's dependent on platform support to actually work. Windows and macOS file system are (by default) case-preserving but case insensitive whereas Linux is case sensitive. We recommend against use case-only differing branch name for interoperability reasons.

```
Markuss-MacBook-Pro:case-test markus$ git checkout -b Test
Switched to a new branch 'Test'
Markuss-MacBook-Pro:case-test markus$ git checkout -b test
fatal: A branch named 'test' already exists.
```

> 4\. Use github desktop client to search for both distinct branches (bug causes you to see only 1)

If you run `git branch` at this point, does it list one or two branches? I'm guessing that if it does list two you're either on a case-sensitive file system, or the second branch has been packed by Git, or the one of the branches aren't actually a local branch but a remote one.

> 5\. Use github desktop client to pull changes for one of the branches (bug causes your branch to enter a buggy state)

Could you elaborate on what "buggy state" means here?

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @mediocregatsby if you're able to answer the questions in the previous comment we're happy to dig deeper into the issue.
