### ISSUE TITLE
Content overflows out of bound inside 'What's new' window. (On update process)

### ISSUE THREAD

**Issue by phu54321** [desktop/desktop#5974]
## Description

Text overflows out of modal window.

![image](https://user-images.githubusercontent.com/775265/47357391-87516e00-d701-11e8-93fa-9f70d0974f3d.png)

Text should not.

## Version

* GitHub Desktop: 1.4.1

* Operating system: macOS Mojave (10.14)

## Steps to Reproduce

Click on 'what's new?' button when an update is queued.

![image](https://user-images.githubusercontent.com/775265/47357484-c253a180-d701-11e8-92be-783ffc680632.png)

### Expected Behavior
It should not overflow. The content should properly hidden, and there should be a scrollbar to make the hidden part visible.

### Actual Behavior
See the image.

## Additional Information

This seems like a simple CSS issue.

### Logs

I don't think I need this? If I need this I'll upload them.

**Comment by steveward** [comment]
@phu54321 thanks for contributing! This was tracked in https://github.com/desktop/desktop/issues/5854 and was fixed in https://github.com/desktop/desktop/pull/5885 so I'm going to close this out.
