### ISSUE TITLE
Improve the list of branches

### ISSUE THREAD

**Issue by danielb987** [desktop/desktop#5981]
I'm working on a fork of the [JMRI](https://github.com/JMRI/JMRI) project. The JMRI project has a lot of branches and I have several branches of my own. This results in a very hugh list of branches.

For both GitHub Desktop and the GitHub web site, I would like to be able to hide all the JMRI branches except the "upstream/master" branch. It's the only branch I'm interested in and the usage of that branch is to merge in upstream changes into my branches.

For me, the list of branches is a mess and I often need to do a search to find my own branches, which in turn requires me to remember the name I gave the branch.

**Comment by niik** [comment]
Hey @danielb987, thanks for opening this issue. I understand that having a lot of branches can be cumbersome but branches are a core piece of working with a Git repository and I don't believe hiding them is the right way to go for GitHub Desktop.

I'd like to offer some tips that can hopefully alleviate some of your issues though.

> I often need to do a search to find my own branches, which in turn requires me to remember the name I gave the branch.

The recent branches grouping in the branches list should help you out here a bit. This group lists the five most recently checked out branches, chances are that the branch you're looking for is among them.

<img width="326" alt="screen shot 2018-10-24 at 09 01 34" src="https://user-images.githubusercontent.com/634063/47412252-7c332800-d76b-11e8-9ed9-1e72379a8084.png">


Another trick that I've used on projects with larger branches is to always name your branches prefixed with your username and a slash. So if my branch name was supposed to be `feature-a` I'd name it `niik/feature-a`. The slash gives it a hierarchical grouping and now you can search for just your username and find all the branches you've created.

Finally I'd recommend opening a pull request early (you can alway prefix the title with [WIP] for work in progress to avoid premature reviews). PR titles are (in my experience) easier to remember than branch names and you can search for PRs by username in desktop (see the screenshot below listing all of @outofambit's currently open PRs

<img width="320" alt="screen shot 2018-10-24 at 08 57 52" src="https://user-images.githubusercontent.com/634063/47412081-f2835a80-d76a-11e8-928f-24b1e7548194.png">

I hope that will help you manage your branches more easily and we really appreciate the feedback which might feed into other decisions in the future to help with managing branches. I'm going to close this issue but feel free to keep adding feedback if you think something is missing.

**Comment by danielb987** [comment]
Thanks for your answer.

What is the drawback of having an option to hide branches?

> The recent branches grouping in the branches list should help you out here a bit. This group lists the five most recently checked out branches, chances are that the branch you're looking for is among them.

That works fine on the computer that checked out the branch. But I use two computers for development, one computer there I write code and one computer there I do merge from upstream/master. The reason for this is that I use the NetBeans IDE for Java development and if I change branch, NetBeans will automaticly close all open files that doesn't exists on the branch I switch to. So if I'm working on a new part of the project with a lot of new files, NetBeans will close all these files every time I switch to my master. And I want to always merge upstream/master into my master and then merge my master into my branches, which means that I need to switch to the master to do the merge. Therefore I do all the merging from upstream/master on another computer.

Yesterday, I thought I hade merged upstream/master into my latest branch, but I realized that I didn't. I hade merged the master into the latest branch on that computer, `newlogix_6`, but on the other computer I'm working on the branch `newlogix_7`.

> Finally I'd recommend opening a pull request early ...

I don't have one branch per PR. At this point I have 7 branches for one single PR. Branches are cheap and there are two major reasons for me to work this way.

First, `git merge` can go terrible wrong. It has happen to me and others. For example, I'm using Windows which doesn't care about case in filenames. If another developer working on Linux changes the case of the filename in a lot of files but only changes the case, for example changing a file name from `onefile.txt` to `oneFile.txt`, `git merge` go nuts on Windows. If I create a new branch before doing a `git merge` I can easily go back simple by switching to the old branch.

Second, if I have done a lot of work on a branch and then need to test an idea, I can create a new branch and implement that idea in the new branch. If the idea is good I continue on that branch. If it's not, I switch back to the old branch.

**Comment by billygriffin** [comment]
Thanks for the feedback and the detailed explanation of how you're using this @danielb987. Unfortunately your workflow seems pretty different from how we've observed most developers manage branches in both of the examples you laid out. We try to make Desktop as intuitive as possible, and adding additional configuration to support workflows for more advanced users adds potential for confusion for newer users. How we think about this tradeoff is outlined in this document: https://github.com/desktop/desktop/blob/master/docs/process/what-is-desktop.md

We are likely going to be thinking about how branches are organized more generally, and we'll definitely take your feedback into account when we get there. Thanks again and we're always open to revisiting this type of decision as we continue to learn more about our users and their needs.
