### ISSUE TITLE
standardize the way that hashes for objects are created

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#5988]
For context, https://github.com/desktop/desktop/pull/5947#discussion_r227863728 spurred the creation of this issue.

I'm propose that instead of using string templates to produce a value to be used for comparison, we rely on `Array##join`.

**Using `GitHubRepository` as a motivating example**

```ts
return [
      this.dbID,
      this.defaultBranch,
      this.private,
      this.cloneURL,
      this.name,
      this.htmlURL,
      this.owner.hash,
      this.parent && this.parent.hash,
    ]
      .map(s => (s == null ? `${s}` : s))
      .join('+')
```

 I think doing it this way 

1. improves the readability a bit because we remove the noise `${value}` and  `+` from the picture.

2. Gives us more control of how we handle `null` or `undefined` values. In the example above, I chose to mirror what was done before and return `null` and `undefined` as strings, but we could easily filter them if we wish.

3. Allows us to easily change the order of the values in the result string. This is only useful if we use the results for debugging purposes. For instance, the most important thing in the above example may be the `cloneURL` (just go with it as an example), so we may want to have that start the string so we don't have to search through it in a string that looks like this:

   `13+master+false+https://github.com/iAmWillShepherd/CSCI-E-34.git+CSCI-E-34+https://github.com/iAmWillShepherd/CSCI-E-34+iamwillshepherd+https://api.github.com+13+null`

4. Allows us to format the way we want without prettier interfering

   Changing `'+'` to `'\n'` in the `join` function gives us the output we intended to get before #5947 was opened.

   ```
   13
   master
   false
   https://github.com/iAmWillShepherd/CSCI-E-34.git
   CSCI-E-34
   https://github.com/iAmWillShepherd/CSCI-E-34
   iamwillshepherd+https://api.github.com+13
   null
   ```

Currently, these models allow us to get a "Hash":

- `Owner`

  https://github.com/desktop/desktop/blob/692b1439ada26f61d0fbca7f1fb79969daebcad3/app/src/models/owner.ts#L17-L19

- `CloningRepository`

  https://github.com/desktop/desktop/blob/692b1439ada26f61d0fbca7f1fb79969daebcad3/app/src/models/cloning-repository.ts#L23-L25

- `GitHubRepository`

  https://github.com/desktop/desktop/blob/692b1439ada26f61d0fbca7f1fb79969daebcad3/app/src/models/github-repository.ts#L60-L69

- `Repository`

  https://github.com/desktop/desktop/blob/be4aa950b048858aaad6924fd05c28bab352f786/app/src/models/repository.ts#L40-L47

**Comment by shiftkey** [comment]
I'm into it. I gather this part is to ensure `null` and `undefined` are encoded into the string, rather than being omitted?

```ts
s == null ? `${s}` : s
```

**Comment by niik** [comment]
I don't believe this is something we're going to be addressing in the short term so I'm gonna close it
