### ISSUE TITLE
Unable to pull/push from/to github wikis

### ISSUE THREAD

**Issue by sa501428** [desktop/desktop#5989]
## Description

After checking out a github wiki in Github Desktop using the clone url, it is not possible to pull changes or push updates to the wiki repo. Nothing happens when the button is clicked. No error is given. Regular repos seem to work fine.

## Version

* GitHub Desktop: 1.4.3

* Operating system: Mac OS High Sierra

## Steps to Reproduce

1. Open a github wiki page and copy the "clone this wiki" url
2. Open up github desktop and clone the repo using url (won't allow cloning directly through github - separate issue)
3. Once directly is cloned, change a file locally.
4. Click commit changes.
5. Click Push update (nothing happens)

--- alternatively
1. Open a github wiki page and copy the "clone this wiki" url
2. Open up github desktop and clone the repo using url (won't allow cloning directly through github - separate issue)
3. Once directly is cloned, change a file online using github website and commit changes
4. Github desktop will show that changes are available to pull
5. Click Pull/sync changes (nothing happens)

### Expected Behavior

Updates should be pulled/pushed correcly as in older versions of github desktop

### Actual Behavior

nothing - no error, no feedback, as though button has no action associated with it? (but works fine with non wiki repos)

**Comment by billygriffin** [comment]
Hi @sa501428, thanks for the report. We're tracking this in https://github.com/desktop/desktop/issues/3839, and it hasn't been a super high priority because wikis aren't very commonly used in conjunction with Desktop. You're welcome to follow along there, and thanks again for letting us know!
