### ISSUE TITLE
flags & countries

### ISSUE THREAD

**Issue by basil-g** [desktop/desktop#5992]
Currently if an institution is being added - its descriptive field in the appropriate db field called country is used to generate the flag file name: engine/images/.png
That should be done in a more elegant way if possible. @basil-g

**Comment by basil-g** [comment]
Currently if an institution is being added - its descriptive field in the appropriate db field called country is used to generate the flag file name:  engine/images/<country>.png
That should be done in a more elegant way if possible.

**Comment by shiftkey** [comment]
@basil-g this issue tracker is for the [GitHub Desktop](https://desktop.github.com/) project, and I'm not sure your suggestion relates to that.

Could you please [open a new issue](https://github.com/desktop/desktop/issues/new/choose) and choose a suitable template if you have some feedback regarding GitHub Desktop?

**Comment by basil-g** [comment]
I'm very sorry
I'm a newbie
Just kill the misplaced issue if possible
Thanks in advance
