### ISSUE TITLE
Broken styling on merge modal

### ISSUE THREAD

**Issue by ampinsk** [desktop/desktop#5998]
This isn't in production yet, but I noticed some funkiness on `master` on the merge modal header: 

<img width="452" alt="screen shot 2018-10-25 at 10 35 27 am" src="https://user-images.githubusercontent.com/10404068/47523092-179bca00-d84c-11e8-9691-78308cfdf415.png">

It should look like this: 

<img width="502" alt="screen shot 2018-10-25 at 11 53 53 am" src="https://user-images.githubusercontent.com/10404068/47523349-a9a3d280-d84c-11e8-8792-0d9cd04c3521.png">

Margin was added to `.filter-field-row` when there should be no margin, I _think_ it came from this commit: https://github.com/desktop/desktop/commit/b8a600971305c0f99ae5632de946ab883f25e05e

**Comment by JKirkYuan** [comment]
I can quickly take a look at this! 👍
