### ISSUE TITLE
Consistent text retention in Branch/PR filters

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6002]
When entering text in either the Repo or History filter, we retain the text when the user navigates elsewhere in the app. This is also partially true for the Branch filter and Pull Request filter, however these are cleared if the user navigates elsewhere in the app.

For consistent behavior and functionality, we should retain the text in the Branch filter and Pull Request filter.

<img width="354" alt="screen shot 2018-10-25 at 2 38 35 pm" src="https://user-images.githubusercontent.com/14828183/47531896-ae27b580-d863-11e8-8595-0bee752db321.png">
<img width="340" alt="screen shot 2018-10-25 at 2 38 28 pm" src="https://user-images.githubusercontent.com/14828183/47531897-aec04c00-d863-11e8-84e8-1f0b7bb5808e.png">

1.4.4-beta0, mac

**Comment by Daniel-McCarthy** [comment]
I think this is a great idea, both for functionality as a user as well as consistency within the program.
I will have a pull request for this open very soon.

**Comment by Rodion8888** [comment]
> When entering text in either the Repo or History filter, we retain the text when the user navigates elsewhere in the app. This is also partially true for the Branch filter and Pull Request filter, however these are cleared if the user navigates elsewhere in the app.
> 
> For consistent behavior and functionality, we should retain the text in the Branch filter and Pull Request filter.
> 
> <img alt="screen shot 2018-10-25 at 2 38 35 pm" width="354" src="https://user-images.githubusercontent.com/14828183/47531896-ae27b580-d863-11e8-8595-0bee752db321.png">
> 
> <img alt="screen shot 2018-10-25 at 2 38 28 pm" width="340" src="https://user-images.githubusercontent.com/14828183/47531897-aec04c00-d863-11e8-84e8-1f0b7bb5808e.png">
> 
> 1.4.4-beta0, mac
