### ISSUE TITLE
improvements to default message when single file chosen to commit

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#6017]
**Please describe the problem you think should be solved**

The changes in #5389 around showing a default message don't seem to match up with the behaviour on GitHub, and I think it's a relatively-straightforward change to address.

**[Optional] Do you have any potential solutions in mind?**

Two specific things I've noticed:

 - first, on the website the commit summary is by default "Update [filename]" rather than "Update [path-to-file]" that Desktop displays. That's this line:

https://github.com/desktop/desktop/blob/c82e0707ce4072ec4e768f8f143137eee3c0db0f/app/src/ui/changes/changes-list.tsx#L416

For reference, heres's what I see when updating a file named `Global/SlickEdit.gitignore`

<img width="413" src="https://user-images.githubusercontent.com/359239/47615785-af8af500-da92-11e8-87c8-9e50f44d6880.png">

 - second, we should differentiate between creating a new file ("Create [file]"), updating an existing file ("Update [file]") or removing a file ("Removed [file]").

An example of creating a new file:

<img width="474" src="https://user-images.githubusercontent.com/359239/47615795-009ae900-da93-11e8-8925-4e4c134f9db9.png">

An example of removing a file:

<img width="1014" src="https://user-images.githubusercontent.com/359239/47615793-f2e56380-da92-11e8-99d7-1c0613fc6e45.png">

**Comment by Daniel-McCarthy** [comment]
If I understand correctly, you would like the default summary to act like this?
![image](https://user-images.githubusercontent.com/4957200/47618384-7ce7f900-daa0-11e8-8508-0f22f16cf97b.png)
- No file path, only the name and extension
- Show Create, Delete, or Update depending on what kind of change is being made

I gave it a try and I think I seem to have it how you asked.

**Comment by shiftkey** [comment]
@Daniel-McCarthy that's exactly it - I just wanted to brain dump it today when I spotted it, but those mocks do seem to match up with what I was expecting...

**Comment by Daniel-McCarthy** [comment]
Excellent, then in that case I can make a pull request with the necessary changes for this new behavior.
I would also be happy to update it if there are more suggestions later on as well.
