### ISSUE TITLE
Add the ability to specify your repository name

### ISSUE THREAD

**Issue by kvantstudio** [desktop/desktop#6019]
When you select a repository in the www or public_html folder, it is unclear which one is currently open and in the list of recent repositories, it is also unclear what kind of repositories.

**Comment by billygriffin** [comment]
Hi @kvantstudio, thanks for the issue! I’m not super clear on what you’re referring to. Would you mind including steps to reproduce what you’re seeing and screenshots to help us understand the problem? Thanks!

**Comment by kvantstudio** [comment]
![2018-10-29_21-28-40](https://user-images.githubusercontent.com/12735787/47665067-1e1aa080-dbc2-11e8-979f-efdde0dad8e6.png)
Need name of repository when folder name equivalent

**Comment by steveward** [comment]
Thanks for the update and screenshot @kvantstudio. We are tracking the ability to add custom repository labels in https://github.com/desktop/desktop/issues/1929. I'm going to close this issue out, but please follow along there for updates about this feature.
