### ISSUE TITLE
Account sign in error - UNIX[Permission denied]

### ISSUE THREAD

**Issue by aminelmassih** [desktop/desktop#6020]
## Description

When trying to sign in to my github desktop i've got this message L
Error --- UNIX[Permission denied]

## Version

* GitHub Desktop: 1.4.3

* Operating system: maOS high Sierra version 10.13.6

**Comment by aminelmassih** [comment]
@shiftkey i downloaded github desktop, tried to sign in i've got this message. the error displayed in a popup window.
[2018-10-28.desktop.production.log](https://github.com/desktop/desktop/files/2525404/2018-10-28.desktop.production.log)

**Comment by shiftkey** [comment]
@aminelmassih thanks for the log file - this shows the error is occurring when Desktop tries to add the account to the keychain:

```
2018-10-28T19:38:08.440Z - error: [ui] Error adding account 'aminelmassih'
Error: UNIX[Permission denied]
```

Have you done anything interesting to your Keychain Access that might impact Desktop?

Also, I see this error in the logs:

```
2018-10-28T19:37:48.580Z - error: [ui] Error checking for updates
Error: Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. See https://github.com/Squirrel/Squirrel.Mac/issues/182 for more information.
```

I would recommend moving the app to `/Applications` if you'd like it to update itself in the future.

**Comment by aminelmassih** [comment]
@shiftkey Not as i remember regarding the KEYCHAIN, and i moved it to APPS folder.  Other than that still having the same error.

**Comment by shiftkey** [comment]
@aminelmassih apologies for the delay.

 I'm pretty sure this is an issue with Keychain Access that Desktop cannot resolve by itself. Are you able to check that you can access the `login` keychain, where Desktop is trying to add it's credentials? This thread talks about diagnosing the same error you're seeing: https://discussions.apple.com/thread/6355363

**Comment by billygriffin** [comment]
I'm going to close this, and fingers crossed that you were able to resolve it @aminelmassih. Let us know if you're still having issues and we can continue to work with you to try to get to the bottom of it.
