### ISSUE TITLE
GitHub Desktop Icon Missing In Windows App Switcher

### ISSUE THREAD

**Issue by say25** [desktop/desktop#6021]
## Description
GitHub Desktop Icon Missing In Windows App Switcher.

## Version
* GitHub Desktop: 1.5.0-beta1
* Operating system: Windows 10

## Steps to Reproduce
1. Open GitHub Desktop
1. Enable App Switcher

### Expected Behavior
To See GitHub Desktop Application Icon when Switching Apps

### Actual Behavior
I see a generic Windows Application Icon for GitHub Desktop when Switching Apps.

## Additional Information
As I build & run console applications on Windows its annoying to differentiate my application from Github Desktop at a glance.

**This appears to be a Windows only Issue.**

![windowsswitcher](https://user-images.githubusercontent.com/7467062/47623918-7b402480-dae4-11e8-86f6-e25b576241c9.PNG)

**Comment by shiftkey** [comment]
@say25 can you verify a couple of things for me, to help me trace how this might be broken?

 - the task manager icons are valid

<img width="441" src="https://user-images.githubusercontent.com/359239/47647188-02c57c00-db55-11e8-9761-871c1dea1180.png">

 - the icon in the taskbar is valid

<img width="364" src="https://user-images.githubusercontent.com/359239/47647087-ba0dc300-db54-11e8-8a60-11161007d2c4.png">

 - Under Apps & Features the installation looks correct

<img width="507" src="https://user-images.githubusercontent.com/359239/47647136-e32e5380-db54-11e8-87e1-664937737f78.png">

You should be able to right-click on the process in Task Manager, select **Open file location**, and end up here, which looks fine on my build:

<img width="563" src="https://user-images.githubusercontent.com/359239/47647280-428c6380-db55-11e8-9f3d-2d2b1a35c79e.png">

Also, which build of Windows are you running? I don't think it's important here, but my Command Prompt shows `10.0.17134.345` which should be up-to-date (just wanted to ensure you weren't on an insider build of Windows):

<img width="465"  src="https://user-images.githubusercontent.com/359239/47647351-7bc4d380-db55-11e8-9231-ef8ad5a72208.png">

**Comment by say25** [comment]
@shiftkey strangely enough everything else checks out as expected. Here are a few screenshotted: 
![image](https://user-images.githubusercontent.com/7467062/47656714-9602af80-db5d-11e8-96bf-8e87cf1d6280.png)

When I build and run `master` locally Github Desktop Dev is also effected.

**Comment by say25** [comment]
Also deleted my AppData folder and reinstalled GHD and it still failed to come back

**Comment by say25** [comment]
Its been a couple years, Windows updates, Electron updates etc but this issue doesn't seem to occur locally anymore closing for now.

**Comment by AlongDeveloper** [comment]
noob
