### ISSUE TITLE
Changes List Bulk Select Checkbox Doesn't Respond to Keyboard Enter Key

### ISSUE THREAD

**Issue by say25** [desktop/desktop#6022]
## Description
Changes List Bulk Select Checkbox Doesn't Respond to Keyboard Enter Key

## Version
* GitHub Desktop: 1.5.0-beta1
* Operating system: Windows 10

## Steps to Reproduce
1. Use Tab to Highlight Changes Header Checkbox
2. Hit Enter Key

### Expected Behavior
Checkbox should change state.

### Actual Behavior
Nothing

## Additional Information
![changesbox](https://user-images.githubusercontent.com/7467062/47625644-5653ad80-daf4-11e8-83d6-6ce24d767552.png)

**Comment by shiftkey** [comment]
Cool, I'm not sure that this ever worked so nice spot @say25 🤷‍♂️ .

cc @desktop/design and @niik to confirm this makes sense from a UX perspective (<kbd>Enter</kbd> does update the checkbox when you focus on an item in the list).

**Comment by donokuda** [comment]
It looks like hitting <kbd>Enter</kbd> to toggle a checkmark in the changes list is a behavior we introduced ourselves and isn't something that is native to the OS.

If we wanted to support toggling checkmarks with <kbd>Enter</kbd> here, would that mean we would have to make sure that every checkmark throughout the app behaves the same way? What does the amount of effort look like if that's the case?

**Comment by tidy-dev** [comment]
I checked in with our Accessibility team and we shouldn't be toggling checkboxes with enter.

>Users won’t (shouldn’t) expect Enter will toggle the checkbox, since that’s not how other checkboxes (neither on the web nor on macOS) are toggled.
Users could be confused if their muscle memory (press Enter to confirm and close) breaks because special handling is added.
