### ISSUE TITLE
Add Visual SlickEdit as an external editor

### ISSUE THREAD

**Issue by texasaggie97** [desktop/desktop#6029]
I use Visual SlickEdit as my programming editor. I would like to be able to use it as an external editor when needing to edit files from GitHub Desktop

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to create an issue @texasaggie97.

Have a look at our [docs](https://github.com/desktop/desktop/blob/master/docs/technical/editor-integration.md) for getting another editor integrated.

**Comment by texasaggie97** [comment]
I already created a PR for this. The only reason I opened an issue is your PR template said I was supposed to. See #6030
