### ISSUE TITLE
Character corruption

### ISSUE THREAD

**Issue by pcavalcanteoliveira** [desktop/desktop#6042]
**Please describe the problem you think should be solved**
Downloading .Rnw files by Github Desktop corrupts encoding. Special characters, specifically, are lost. 

Example:

What should be:

> "A inflação cheia medida pelo IPCA em um período"

Becomes: 

> “A infla??o cheia medida pelo IPCA em um per?odo”

**Comment by tierninho** [comment]
@pcavalcanteoliveira thanks for filing. Can you provide some more details like the logs, your version of Desktop, mac/windows OS, and some reproduction steps. Valeu.

**Comment by shiftkey** [comment]
@pcavalcanteoliveira are you able to provide a public commit or example to go with this issue? I think this is the same root cause as #3923

**Comment by billygriffin** [comment]
Since I think we have this captured in #3923, I'm going to close this out. Sorry it's a pain for you @pcavalcanteoliveira.
