### ISSUE TITLE
preserve commit messages when undoing several commits

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#6043]
**Please describe the problem you think should be solved**

After creating a lot of small commits, I sometimes want to rework the history before pushing the branch. I can do this by rebasing in the command line, but a quick way to do it while avoiding rebase flows would be to just undo all my local commits.

Currently the app will replace the commit summary/description with the details of the previous commit, which is nice if you want to just amend that commit. But if I want to undo multiple commits, the app will replace the contents with the previous commit, so I lose that context and need to poke at the reflog to see what my old history looked like.

**[Optional] Do you have any potential solutions in mind?**

One potential solution would be to append the commit summary and/or description to the current commit form. Here's an example of how this might work:

> I have three local commits - A, B and C - that I would like to undo
> C <---- my branch
> B
> A
> X <---- my default branch
>
> 1. I undo the first commit (C) and the commit form becomes:
> 
> *Summary:* C
> *Description:*
> Description related to C
> 
> 2. I undo the second commit (B) and the commit form becomes:
>
> *Summary:* B
> *Description:*
> Description related to B
> 
> C
> Description related to C
>
> 3. I undo the first commit (A) and the commit form becomes:
>
> *Summary:* A
> *Description:*
> Description related to A
>
> B
> Description related to B
> 
> C
> Description related to C

**Comment by billygriffin** [comment]
We're working on some improvements to undo now, but I don't think we've seen much evidence that this is used enough to justify the work involved with preserving the commit messages, so I'm going to close this. Thanks!
