### ISSUE TITLE
prevent background updates while popup is displayed

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#6047]
An existing issue discovered in reviewing #5809. While popups are displayed in the app, the background still updates visually. We'd like them to not update while the popup is displayed and then resume updating once the popup is closed.

![background activity](https://user-images.githubusercontent.com/964912/47748327-c4f55000-dc47-11e8-8381-bf72339d06f8.gif)

**Comment by billygriffin** [comment]
Adding `help wanted` here as I think the desired behavior is straight-forward, but it may not be the easiest to solve.
