### ISSUE TITLE
spinner while updating status in merge conflicts modal?

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#6048]
from https://github.com/desktop/desktop/pull/5809
> we don't show any indicator when we are checking the state of conflicted files, so the screen can just sit there for a while before it switches to "resolved!"

Perhaps we should show a spinner or some updating animation while this is happening in the background?

cc @desktop/design

**Comment by ampinsk** [comment]
Are we talking about this spot? 

<img width="146" alt="screen shot 2018-10-30 at 2 38 57 pm" src="https://user-images.githubusercontent.com/10404068/47752395-91b7be80-dc51-11e8-9825-12918dcfcfc2.png">


Maybe we do something like we do for the merge hint indicator? 

![screen shot 2018-10-30 at 2 02 23 pm](https://user-images.githubusercontent.com/10404068/47752426-a431f800-dc51-11e8-8f4a-050e64212ecd.png)

**Comment by shiftkey** [comment]
> Perhaps we should show a spinner or some updating animation while this is happening in the background?

The `Dialog` component has an inbuilt `loading` prop that renders a spinner next to the heading. Maybe that could help here?

<img width="833" src="https://user-images.githubusercontent.com/359239/47798404-131d5880-dd07-11e8-8bd8-b402e5674684.png">

**Comment by billygriffin** [comment]
@outofambit (or someone else if it's clear) Would you mind clarifying where and when we're talking about here? It's not super clear to me at what point in the process we're solving for.
