### ISSUE TITLE
Aborting a new merge doesn't update the changed files list

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#6052]
## Description

After aborting a merge, the status doesn't update. I continue to see all the conflicted files, etc. If I check `git status` on the command line, it reflects that I aborted the merge. If I switch away from the app and back, the changed files updates as I'd expect.

## Version

* GitHub Desktop: 1.5.0-beta2
* Operating system: macOS 10.13.6 

## Steps to Reproduce

1. Merge two branches that introduce a conflict.
1. Abort the merge using the ✨ fancy new dialog ✨ 

### Expected Behavior

1. All the changed files and conflicts are gone.

### Actual Behavior

1. I still see the changed files and conflicts.

**Comment by shiftkey** [comment]
>  If I switch away from the app and back, the changed files updates as I'd expect.

This one might be the key to the issue - could just require refreshing the changes tab after dismissing the dialog.

**Comment by shiftkey** [comment]
Yep, I've got a consistent repro now:

 1. From the changes tab, select "Merge into Current branch"
 2. Choose a branch that will cause conflicts
 3. Continue and see the merge conflicts list
 4. Abort the merge

Expected: no changes in list
Actual: files remain

**Comment by shiftkey** [comment]
Marking as `priority-2` because I believe it's a common flow, and potentially very confusing. PR incoming.
