### ISSUE TITLE
Extra space under Select Branch to Compare input

### ISSUE THREAD

**Issue by ampinsk** [desktop/desktop#6058]
Related to #5998, I think this is due to the changes in b8a6009

| Actual| Expected|
|---|---|
|<img width="260" alt="screen shot 2018-10-31 at 9 46 06 am" src="https://user-images.githubusercontent.com/10404068/47804948-579ef900-dcf3-11e8-98e9-a2a28810dbca.png">|<img width="262" alt="screen shot 2018-10-31 at 9 45 28 am" src="https://user-images.githubusercontent.com/10404068/47804951-579ef900-dcf3-11e8-8080-5ce92bb04b6f.png">|

**Comment by shiftkey** [comment]
Reproducible in `1.5.0-beta2`:

<img width="347" src="https://user-images.githubusercontent.com/359239/47806973-b11a1e80-dd19-11e8-8d17-34ce12760d7b.png">

**Comment by shiftkey** [comment]
Moving this into `1.5.0` as I consider this a regression (and should be easy to fix like #5998)
