### ISSUE TITLE
display manual conflict resolution options in app

### ISSUE THREAD

**Issue by ampinsk** [desktop/desktop#6062]
Right now, we're treating binary files as simply resolved:

<img width="531" alt="screen shot 2018-10-31 at 10 44 31 am" src="https://user-images.githubusercontent.com/10404068/47807837-473e4c80-dcfa-11e8-96c3-1f07257ada70.png">

It would probably be more clear to treat them differently to let the user know that they may need to resolve these outside of Desktop, or even better, we could resolve these using an "ours/theirs" sort of approach in the dialog itself 🤔 

I think we can probably address this after 1.5.0 but wanted to track this as a case 👍

**Comment by shiftkey** [comment]
> let the user know that they may need to resolve these outside of Desktop,

Yep, looks like we might need to tweak our detection of conflicts to handle these files.

> we could resolve these using an "ours/theirs" sort of approach in the dialog itself 🤔

I'm into this idea for the sake of simplicity, and here's a quick writeup on how to resolve this on the command line (which we can steal for any eventual solution): https://stackoverflow.com/a/2163926

```
git checkout --theirs -- path/to/conflicted-file.txt
# or
git checkout --ours -- path/to/conflicted-file.txt
```

**Comment by shiftkey** [comment]
Marking this as `priority-2` because we incorrectly consider them as resolved, and I'm pretty sure the merge won't actually complete successfully if the user tries it.

**Comment by ampinsk** [comment]
I just tried it, and it looks like we do let you successfully complete a merge in this case, at least in the UI

**Comment by shiftkey** [comment]
@ampinsk I guess we just stage whatever is currently in the working directory (which could be it's own can of worms). Gonna try and put together a repro of this to test on my end and confirm. 🤷‍♂️

**Comment by outofambit** [comment]
#6066 is the first iteration of this, while this issue will contain further refinement.

**Comment by shiftkey** [comment]
I started noodling on the UI changes for this building on top of #6066 and wanted to throw it open for feedback. With binary files the only typical options you have when merging conflicts is to choose your version of the file, or the one coming from the other branch.

I started on a dumb UI to expose these options (no messing with styles just yet):

<img width="590" src="https://user-images.githubusercontent.com/359239/47872772-3838c680-ddee-11e8-8351-b459eeb186cd.png">

Unlike merging conflicts in text files, we shouldn't immediately update the Git index with the choice you've made - because the file may disappear when you choose "ours". Instead, we should track the option in-memory and apply it before performing the merge.

I'm open to UX ideas around making this friendly and avoid the Git porcelain, I think there will be some other scenarios like "the file you modified in this branch is deleted in the other branch" which I'll update this with while I'm verifying #6066 .

**Comment by shiftkey** [comment]
Moving it along a bit further, I can now pull in more context around the decision making process:

<img width="526" alt="screen shot 2018-11-01 at 4 38 57 pm" src="https://user-images.githubusercontent.com/359239/47875200-b5ffd080-ddf4-11e8-9027-bacd6ab001ae.png">

The words themselves could be much more friendly (suggestions/improvements welcome):

> "Use the modified version from `master`"  to update to the version from the other branch
>  "Ignore the version on `master`" to prefer the change I made

I'm not a huge fan of the dual buttons, and maybe a dropdown of the options here might give us more horizontal space. When the user has chosen an option we could show a tick alongside to indicate no further work is needed.

**Comment by ampinsk** [comment]
We're trying to do this for 1.5.1, not 1.5.0 right? I can noodle on some designs for this 👍

**Comment by shiftkey** [comment]
@ampinsk correct

**Comment by ampinsk** [comment]
> I'm not a huge fan of the dual buttons, and maybe a dropdown of the options here might give us more horizontal space for wording. When the user has chosen an option we could show a tick alongside to indicate no further work is needed.

I like this idea, here's some mockups around that kind of a flow: 

We can show a `Resolve` button with a down arrow to indicate they'll get a dropdown:

![screen shot 2018-11-07 at 10 16 30 am](https://user-images.githubusercontent.com/10404068/48152105-da85fd80-e277-11e8-8d21-c371b18109ae.png)

Then when a user clicks on that, they'll get more descriptive options in the dropdown:

![screen shot 2018-11-07 at 10 16 36 am](https://user-images.githubusercontent.com/10404068/48152104-da85fd80-e277-11e8-90ed-12485003f442.png)

What are all the scenarios that could come up in this dropdown? Probably lots of ways we could go with wording here.

**Comment by shiftkey** [comment]
> What are all the scenarios that could come up in this dropdown? Probably lots of ways we could go with wording here.

I think the scenarios are just variations on added/modified/deleted and "our branch"/"their branch" so the number of permutations is rather low if we stick a format like that last screenshot.

> Do we want to let people edit this after they've selected it? 

Unless they're in a scenario where both branches have modified the file, I wouldn't worry about it. In that case either the changes merge cleanly or there's conflicts that need to be resolved, which we ask them to resolve in their editor of choice.

**Comment by shiftkey** [comment]
Just tweaked the title because this isn't an issue specific to binary files. #6133 will go out with `1.5.0` to ensure text files are rendered correctly, and next I'm fleshing out the mocks here into something functional in the app.

**Comment by ampinsk** [comment]
@shiftkey I have some updated mocks after design review yesterday! I'll post asap

**Comment by ampinsk** [comment]
## Design update

Brought this to design review yesterday, we chatted through the idea of using a select dropdown, but decided against it. Updating here with the success state, where we want to use more clear language so users know what they selected:


`Binary conflict` in orange, with the Resolve dropdown:

![screen shot 2018-11-09 at 10 36 22 am](https://user-images.githubusercontent.com/10404068/48281469-8ca1fe80-e40b-11e8-9862-4edd3dd4fd9b.png)


Same as above, reveal the options in a native dropdown: 

![screen shot 2018-11-09 at 10 36 28 am](https://user-images.githubusercontent.com/10404068/48281593-dee31f80-e40b-11e8-93c6-b13e8a40dc0a.png)


Once selected, show the option they picked in the green text. 

![screen shot 2018-11-09 at 10 44 07 am](https://user-images.githubusercontent.com/10404068/48281792-8d876000-e40c-11e8-8de6-2378efff1109.png)

---

This might be a little out of scope for this issue, but we also talked about the possibility of undoing this if users want to change their selection? Would this be possible or something we want to tackle? 

![screen shot 2018-11-09 at 10 36 41 am](https://user-images.githubusercontent.com/10404068/48281605-e3a7d380-e40b-11e8-9c7a-3c09ec61e6c1.png)

**Comment by shiftkey** [comment]
> This might be a little out of scope for this issue, but we also talked about the possibility of undoing this if users want to change their selection? Would this be possible or something we want to tackle?

We could support this if we defer staging the changes until they click "Commit merge". This means the app would just keep the selection in-memory and flush changes later on, which was the initial approach I was going to explore.

"Undo" in that case could restore the button and context menus.

**Comment by shiftkey** [comment]
Aiming to open up a PR for this tomorrow, but I figured an in-progress demo of the interactions here might help to show the direction (branch names are placeholders right now, so they don't match the actual state of the dialog):

![](https://user-images.githubusercontent.com/359239/48586763-3d763500-e907-11e8-8d00-514f0d1a8e52.gif)

**Comment by j-f1** [comment]
Looks nice! How about using a styled `<select>` instead of a button + context menu? I feel like that would make for a better UX.

**Comment by ampinsk** [comment]
@shiftkey yay this looks awesome! I couple things I noticed:

- The `Resolve` button should have a down triangle octicon 
- I was thinking where it says `Choose a version of the file` it would say `Binary conflict` but I could see that being less clear 🤔 
- And in the resolved state, I was thinking the language would say `Using ...` instead of `Use ...`


@j-f1 we played with that idea, but a `<select>` felt out of place with the room we have on this dialog. 😕 

cc @donokuda if you have 💭

**Comment by shiftkey** [comment]
> I was thinking where it says `Choose a version of the file` it would say `Binary conflict` but I could see that being less clear 🤔

Yep, we can have text files that exist in the working directory that need manual resolution.

**Comment by shiftkey** [comment]
To whoever picks up this task, I have a branch here that was a first attempt at implementing the necessary features: https://github.com/desktop/desktop/compare/c6ee81f...shiftkey/add-support-for-resolving-files-in-app?expand=1

 - surfacing the Git details about "ours" and "theirs"
 - let the user choose a version, update the UI to show a check mark, let them undo
 - when no remaining conflicts, create the merge commit

Feel free to borrow or just learn from it

**Comment by billygriffin** [comment]
Moving this into 1.6 milestone as we're planning to release 1.5.1 next week and this is more in line with the other iterations we're doing on merge conflicts.

**Comment by msftrncs** [comment]
It might be desirable to include more options in the resolve drop-down, or similar interface, as per suggestions in #6385 for other files?  In this case, maybe just 'reveal/show in finder/explorer'?    I have not yet had to work with binary file conflicts, but I might imagine that a user might need to inspect the incoming file before choosing 'ours/theirs'.

**Comment by ampinsk** [comment]
@msftrncs we've been discussing combining these dropdown options internally, thanks for bringing it up! We'll likely get to this in future iterations 😄

**Comment by timor-raiman** [comment]
Great job, exactly what we needed in https://github.com/desktop/desktop/issues/5400#issuecomment-445801777 !!

**Comment by MarkBeharrell** [comment]
Is there any way the list can be saved, shared or added to a commit?

For instance, we have a long-running branch that I regularly update from trunk. During the update we create a branch from this and send that for a PR.

Having the conflicts and resolutions in the commit would be helpful for the reviewers.

It could be a simple as making the window with the conflicts resizable and text selectable.
