### ISSUE TITLE
Cant find an option to change the default directory to clone repos to

### ISSUE THREAD

**Issue by TrentKnight** [desktop/desktop#6064]
When I try to clone a repo it clones it to C:\Users\<username>\OneDrive\Documents\GitHub but I want to change this to a different folder so my repos aren't uploaded to onedrive. I have looked through the settings but I don't see an option to change this.

**Comment by iAmWillShepherd** [comment]
There is no setting for this as Desktop remembers the last directory you cloned a repo to, so the only thing that is needed is to clone a repo and the next time, it will default to that location.
