### ISSUE TITLE
Conflicted file marked as fixed once Merge Conflict modal opened

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6065]
A file marked as merge conflict was already fixed by the time the merge conflict modal appeared. 

The merge hint said I had 1 file that needed to be resolved, yet when the merge conflict modal was surfaced, it was already "green" and the conflicted file count changed to 0.

![oct-31-2018 13-54-26](https://user-images.githubusercontent.com/14828183/47818890-28e64a00-dd16-11e8-8be8-98e5ce375199.gif)

No sure how to reproduce this issue accurately.

Logs
```
git merge HHH` exited with an unexpected code: 1.
CONFLICT (modify/delete): README.md deleted in HEAD and modified in HHH. Version HHH of README.md left in tree.
Auto-merging .gitignore
Automatic merge failed; fix conflicts and then commit the result.
(The error was parsed as 7: We found some conflicts while trying to merge. Please resolve the conflicts and commit the changes.)
```

**Comment by outofambit** [comment]
did you manually resolve the conflict? or are you saying it is being falsely marked as resolved here?

**Comment by tierninho** [comment]
I t is being falsely marked as resolved. Haven't resolved it yet in case I needed to reproduce it.

**Comment by outofambit** [comment]
was the file added or deleted by chance?

**Comment by tierninho** [comment]
It was recently added I believe, but has a checkmark instead of a plus sign:

<img width="715" alt="screen shot 2018-10-31 at 2 07 26 pm" src="https://user-images.githubusercontent.com/14828183/47819504-f3426080-dd17-11e8-9028-8a4168000982.png">

**Comment by shiftkey** [comment]
> CONFLICT (modify/delete): README.md deleted in HEAD and modified in HHH. Version HHH of README.md left in tree.

@tierninho I think this is the same issue as #6123 which is being actively worked on in #6133 - if you still have the repository around see if #6133 does correctly show it as conflicted.

**Comment by tierninho** [comment]
@shiftkey Yes, that looks to be the same issue. Not sure what repo it was anymore. 

Closing this issue as its a dupe.

**Comment by shiftkey** [comment]
@tierninho thanks for the follow-up!
