### ISSUE TITLE
Reinstall VS git.exe moves

### ISSUE THREAD

**Issue by OzBob** [desktop/desktop#6070]
## Description
uninstalled VS 2017 15.8.8 and re-installed it
 ...git.exe 1.4.??? … can not be found in expected location

## Version
* GitHub Desktop: 1.4.3
* Operating system: Microsoft Windows [Version 10.0.17134.345]

## Steps to Reproduce
1. uninstalled VS 2017 15.1(?), install v15.8.8
2. clicked url 
3. x-github-client://openRepo/https://github.com/JasonGT/NorthwindTraders
4. opened Gitforwindows and prompted for repo folder
5. clicked clone
6. popup error similar to :  ...git.exe 1.4.0 … can not be found in expected location
7. close Gitforwindows
8. open gitforwindos
9. try link again from Edge repo in GitHub.com
10. all OK.

### Expected Behavior
search for versions greater than expected one

### Actual Behavior

...git.exe 1.4.0 … can not be found in expected location

## Additional Information
I have been unable to replicate this past the original issue

**Comment by shiftkey** [comment]
@OzBob thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by OzBob** [comment]
[2018-11-02.desktop.production.log](https://github.com/desktop/desktop/files/2540677/2018-11-02.desktop.production.log)

I attached the logs, sorry didn't grab a screen shot when the error occurred, as it wasn't logged in the attached logs.

I've failed to replicate this, but at least it's been reported.

**Comment by shiftkey** [comment]
@OzBob I was hoping the logs would contain details about the Git errors, but the only thing I can spot is this:

```
2018-11-02T01:11:21.188Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.638s)
```

And that seems to have completed successfully. Were there any other days of logs that might have clues as to what the initial behaviour was?

**Comment by steveward** [comment]
@OzBob are there any other log files prior to 11/2 that you could upload? Since you opened the issue on 11/1 the log file from that date may give us some more information.

**Comment by billygriffin** [comment]
Since we haven't heard back from our last couple questions, I'm going to close this out, but we're happy to revisit if it's still an issue. Hopefully your last message saying you can no longer reproduce this means you're good to go.
