### ISSUE TITLE
cannot tab to `open in command line` url  in merge conflicts dialog

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6076]
I cannot use `tab` to select the `open in command line` url in the merge conflict dialogue.

<img width="494" alt="screen shot 2018-11-01 at 12 30 00 pm" src="https://user-images.githubusercontent.com/14828183/47874795-00238a80-ddd2-11e8-944c-7c234ebe4d77.png">

1.5.0-beta2, mac

**Comment by shiftkey** [comment]
Pulling this into `1.5.0` because the fix is easy (use `LinkButton` which is our abstraction for an anchor tag).
