### ISSUE TITLE
Add support for JetBrains Webstorm on Windows

### ISSUE THREAD

**Issue by KennethSweezy** [desktop/desktop#6077]
I use JetBrains Webstorm as my text editor, which is currently not integrated with the "Open External Editor" feature. I would like to be able to quickly open this editor from GitHub Desktop.

**Comment by tierninho** [comment]
Thanks for taking the time to create an issue @KennethSweezy 

Have a look at our [docs](https://github.com/desktop/desktop/blob/master/docs/technical/editor-integration.md) for getting another editor integrated. You can open a PR yourself or wait and see if someone from the community takes it on.

**Comment by KennethSweezy** [comment]
I will work on this, thanks for the link to the documentation!

**Comment by KennethSweezy** [comment]
I am having issues running `yarn` .
Here is the CMD output: [PasteBin](https://pastebin.com/wa5Xszvc)

**Comment by shiftkey** [comment]
@KennethSweezy it's hard to say but the best guess I've got is that your existing Visual Studio install isn't compatible (might be missing the feature that Node needs to support compiling native Node modules). Check out this section of the setup guide: https://github.com/desktop/desktop/blob/master/docs/contributing/setup.md#windows

**Comment by evromalarkey** [comment]
I think this wont work if user had installed previous versions of webstorm and autoupdate from then. I have 2018.3.3 but my subKey path in registry is `SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\WebStorm 2018.1.4`

Your subKey path is for WebStorm 2018.3, so this will also stop working if someone will install newer version in the future.

**Comment by biolauri** [comment]
For me, it's not working either. I assume, according to [win32.ts line 235](https://github.com/desktop/desktop/blob/development/app/src/lib/editors/win32.ts#L235) and compared to other, working editors, that the current implementation is 32-bit only.

The following entry should be added. But I don't know, if this will fix it already.  
```ts
// 32-bit version of WebStorm
{
  key: HKEY.HKEY_LOCAL_MACHINE,
  subKey:
    'SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\WebStorm 2018.3',
},
```

Unfortunately, I don't have the time right now to dive deeper into this. Maybe, in two or three weeks.

**Comment by otelom** [comment]
Hello guys,
WebStorm still doesn't show up as an option for me...

I'm running:
Windows 10 Home 64 bits
GitHub Desktop 1.6.5
WebStorm x64 v. 2018.3.5 Build #WS-183.5912.23 built on February 26, 2019

Does anyone has any idea why?
@KennethSweezy @shiftkey @tierninho

**Comment by shiftkey** [comment]
@otelom my guess would be that the registry location it's installed into doesn't match what we look for. We currently only detect the 32-bit version of WebStorm on Windows:

https://github.com/desktop/desktop/blob/0c24836b13d31559f577a3e9cadc0194f7d6bba5/app/src/lib/editors/win32.ts#L233-L241

If you can find another registry path that we should look at (like in the previous comment), I'd love to see a PR open to add it.

**Comment by otelom** [comment]
@shiftkey ok I think I know where's the problem.
I'll look into it and if everything checks out, I'll submit a PR.
Thanks
