### ISSUE TITLE
Easily delete local branches

### ISSUE THREAD

**Issue by njbmartin** [desktop/desktop#6091]
**Please describe the problem you think should be solved**

Looking at #3559, it looks like there used to be a context menu for the branch list which allowed you to delete a branch. It seems the only way to delete a branch using Github Desktop is to switch to it, and then use the menu to delete it. When you're trying to tidy up branches, they should be trivial to delete.

**[Optional] Do you have any potential solutions in mind?**

As mentioned, there should either be a context menu, or a bin icon similar to the Github website.

Note that I am aware of #750 but that doesn't solve the issue of manually deleting a branch easily.

**Comment by billygriffin** [comment]
Hi @njbmartin! Thanks so much for so clearly framing the problem. We're tracking this in https://github.com/desktop/desktop/issues/5803, and I'll make sure your thoughts get copied over to that issue.
