### ISSUE TITLE
consolidate conflict information in ConflictFileStatus model

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#6093]
from https://github.com/desktop/desktop/pull/6063#pullrequestreview-171370147

> I wonder if we can collapse the `ConflictFileStatus`, `AppFileStatus.Conflicted` and `AppFileStatus.Resolved` into a single field. Right now a `ConflictFileStatus` of `null` means no conflicts, but we don't know if there _were_ ever conflicts without cross-referencing `AppFileStatus`. Perhaps we could remove `AppFileStatus.Resolved` and have a third (and maybe fourth) type for `ConflictFileStatus` that effectively means "resolved", so that a `ConflictState` of `null` would coincide with unconflicted files and there would be a single field to check for conflict information.

**Comment by shiftkey** [comment]
Tentatively assigning myself to this based on #6205 but there might be further work around this after that is reviewed...
