### ISSUE TITLE
Merge button displays very little of the branch name

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#6099]
**Please describe the problem you think should be solved**
The merge button in the branch dropdown has very little room for the branch name, so it's difficult to see for sure which branch you're merging into. It looks like it's currently a 9 character max before it gets truncated, which seems low.

<img width="479" alt="screen shot 2018-11-05 at 10 16 40 am" src="https://user-images.githubusercontent.com/5091167/48014677-741ca600-e0e4-11e8-910a-adb7881a7b39.png">

**[Optional] Do you have any potential solutions in mind?**
We might consider rewording the button a bit to provide more space. We could buy a couple characters by saying "Choose branch to merge into [branch-name]" instead, or we could consider something a bit shorter overall.

cc: @desktop/design

**Comment by ampinsk** [comment]
Would "Merge into [branch]" be too confusing? It might lead people to think it'll merge something right from the button.

**Comment by billygriffin** [comment]
That's exactly my worry @ampinsk is that when we use that elsewhere it implies an immediate action. So I think "Merge into [branch-name]" isn't quite right either. 😬

**Comment by tierninho** [comment]
Should we just expand the whole width of the pane? This would resolve other issues with longer branch names...

My hack attempt at 400px i/o of today's 300px:
<img width="441" alt="screen shot 2018-11-05 at 9 48 57 am" src="https://user-images.githubusercontent.com/14828183/48016305-1d14d200-e0e0-11e8-8bdc-7be191e907aa.png">

**Comment by ampinsk** [comment]
I'm going to play with widening the branch menu to resolve this 👍

**Comment by billygriffin** [comment]
Thanks @tierninho! Might help with both of these problems by increasing the width in the dropdown @ampinsk. It wouldn't help with the current branch name width, but would allow for quickly scanning to switch to the desired branch instead of having to hover over each one if you use longer branch names.

**Comment by say25** [comment]
@desktop/design & @billygriffin. This is 1.5.0 not 1.5.1 FYI

**Comment by billygriffin** [comment]
@say25 Thanks! I think we were originally thinking it might not make it to this week's beta and therefore should be an iteration from 1.5, but thanks to @ampinsk and @outofambit's work it's already merged. Now if only you could just update that milestone directly. 😄 😢

**Comment by say25** [comment]
#GitHubPapercuts?

**Comment by say25** [comment]
@billygriffin #GithubPaperCuts 🤔
