### ISSUE TITLE
Improper commit attribution

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#610]
Problem statements:

1. If the email in my Git config doesn't match any emails on my account in GitHub.com, commits I push are not properly attributed to my GitHub account.

2. Commits in my repository history are not attributed to a GitHub account, so I don't have confidence or peace of mind about who actually made the commit.

3. As a beginner to Git and GitHub, I don't understand why they're different or why my Git info might not match my GitHub info, and why it matters. This is just confusing. (from #4002)

4. If I sign out of my account and back in with a different GitHub account on the same machine, I may see an unexpected avatar based on my underlying Git email that doesn't match the GitHub account I'm signed in with (from https://github.com/desktop/desktop/issues/6973)

5. I want to commit in some repositories with my personal email, and in other repositories with my work email (from #9218). This is a slightly different version of (4) I think.

Considerations:

- Unexpected mismatches most frequently occur when people have a work email on their GitHub account and a personal email in their Git config, or visa versa.
- This can be solved by adding additional emails to your GitHub.com account to ensure that whatever is in your Git config matches one of them.
- We don't seem to currently update any changes from the remote in how we're rendering accounts locally. See: https://github.com/desktop/desktop/issues/3066

From @niik at https://github.com/desktop/desktop/pull/574#pullrequestreview-7378302:

>I was thinking about this one above-and-beyond thing we could do in the configuration step. If a user enters an email that's not associated with their GitHub account (assuming they've signed it) we could show a friendly warning and maybe a link to either add it or suggest one of the email addresses they have associated.

**Comment by shiftkey** [comment]
#3876 was raised by @LitenUpNet as the user had switched accounts but `user.email` was an email address from the old account, which lead to some confusion. This is a separate flow to the Welcome Wizard, but it'd be nice to have a similar check at that point too.

**Comment by shiftkey** [comment]
Noodling on this idea some more, we could change the commit avatar to indicate there's a problem needing attention:

<img width="383" alt="screen shot 2018-07-25 at 10 37 10 am" src="https://user-images.githubusercontent.com/359239/43204294-df0e02b8-8ff6-11e8-9a6d-e1ceb6e460e2.png">

(Yes, I'm going to continue to abuse ⚠️ until someone arrests me or comes along with better design skills)

Clicking on this could show a dialog which then explains the situation and helps the user resolve this, e.g: "The email address you are using for this GitHub repository isn't associated with your GitHub account. Want to add it to your GitHub account now?"

This could also potentially also address:

 - #2829 - "This repository is a GitHub Enterprise repository but your global `user.email` setting is not associated with your account - would you like to override this locally to use your GitHub Enterprise email address?"
 - #1364 - "You don't have a `user.email` address set currently - want to set this using one in your GitHub account?"

**Comment by billygriffin** [comment]
This might also be relevant for #5686.

**Comment by steveward** [comment]
- https://github.com/desktop/desktop/issues/6090 was a related case where a user made a typo in their email address which caused the commit to be attributed to the wrong user

**Comment by billygriffin** [comment]
Updated the original issue here to attempt to frame the problems. @niik Are you planning on looking at this in the context of #5686? If not, maybe @ampinsk could take a look at it as a smaller design task. It's something that @steveward brought up as still one of the most frequent causes of confusion for users.

**Comment by billygriffin** [comment]
@niik and I chatted about this this morning, and his exploration of the welcome flow in #5686 will indeed take the git config into account here to hopefully warn folks when they get set up on Desktop if there is a mismatch between their Git and GitHub setup.

Additionally, we think it would be reasonable to get some metrics in around percentage of commits (and absolute number) of commits in Desktop without attribution to see how widespread a problem it is and if it's worth tackling more broadly outside of just the welcome flow. I'm going to make a separate issue for metrics on that.

**Comment by billygriffin** [comment]
From @kaster14 in #6797:

> On the github desktop app there are times where I need to make a commit from the company login. I go to file, options, then sign out, then sign in as the company account. The problem is that when I go to the changes tabon the mains screen and go to make a commit it still shows my personal account as making the commit (or at least shows my picture).

> I find I also have to go to file, options, select the "git" tab, and change the information there to the company account, hit save, and then have to restart github desktop before the changes take place.

> I would expect to be able to go to file, options, sign out, then sign in as the company profile and have commits immediately start being made from the company account without any further steps being needed.

**Comment by tierninho** [comment]
As part of an exercise I did a walk-though of setting up GitHub and Desktop as a "new" user. All was rather easy and straight-forward, expect for setting up and explanation of git. 

Although we provide a short description in onboarding, I think we can do a better job of explaining its purpose and the distinction between GitHub and git. 

There are a couple of ideas worth revisiting in https://github.com/desktop/desktop/issues/4002

It would be great to open up a dialogue again and see if any action items come out of it.

**Comment by billygriffin** [comment]
@tierninho Thanks! I *think* that's largely captured in problem statement 3 now that I've dug into it a bit more, which also references #4002.

**Comment by steveward** [comment]
Feedback from #8407:

>I use the same laptop for private and company projects with multiple email addresses. With console version of git, I don't setup global config for user name and email, which enforces me to do it for each project whenever I want to commit (which is good). That way I know I use correct user information for each repo.

>When I save any option in GitHub Desktop, global user config is also saved with default GitHub user. If I miss that, I might commit to a new repo with wrong user information.

**Comment by Ravavyr** [comment]
Hey all, I wanted to add my experience with this. 

I own both "ravstamper" and "ravavyr" on github
Years ago i set "ravstamper" as my global config user. 

After i started using "ravavyr" i noticed sometimes my commits were showing "ravstamper". I had forgotten about the global user so it was even more confusing

Currently I've found that:
- Using github desktop, logged in as "ravavyr", my commits are being added as "ravstamper". However ravstamper does not even have access to the repos i'm committing to. This should absolutely not be possible, it should error and say that user cannot commit to that repo.
- Using CLI , i enter my username and password for ravavyr and still my commits are attributed to ravstamper. Again, it should error at the least. 

I was given this link to configure separate users per repo:
https://stackoverflow.com/questions/4220416/can-i-specify-multiple-users-for-myself-in-gitconfig/4220493#4220493

But i have access to hundreds of repos as i work from home, it's nuts to have to do this when i'm literally typing my login into github desktop or via CLI each time already. 

Help? Thoughts?

**Comment by jacobwatkinsgit** [comment]
I was having this issue and came across the topic.In my case, I was seeing the commit from one user, and the merge from another. The log-in should absolutely 100% be what is used as the user who committed the change (how it is even possible to have these be separate is beyond me). I could understand having an additional contact field for some reason (separating username and email/contact), but that's not how it works. As Ravavyr mentions, even in the newest Github Desktop Application, a non-permitted user can make changes to a repository. If the Github support team was unable to assist effectively, I could see this being used to create a lot of damage or mayhem.

**Comment by steveward** [comment]
@Ravavyr @jacobwatkinsgit work is being done to provide per-repository config settings in GitHub Desktop. See https://github.com/desktop/desktop/issues/9449 for more information about that. 

It also looks like you are confusing permissions with commit attribution. Git allows you to set your email address to any known email address. I can find the email address of someone on GitHub and then impersonate them by using that email in my `.gitconfig`, but this does not mean that I have any sort of push access to their repositories. See [this help article](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user) which states the following:

>Note: If your commits are linked to another user, that does not mean the user can access your repository. A user can only access a repository you own if you add them as a collaborator or add them to a team that has access to the repository.

I hope that helps clarify things.

**Comment by steveward** [comment]
>But i have access to hundreds of repos as i work from home, it's nuts to have to do this when i'm literally typing my login into github desktop or via CLI each time already.

You can also use the [includeIf](https://git-scm.com/docs/git-config#_includes) feature of Git to use a different .gitconfig files (i.e. for personal and work repostories). Check out the [next answer](https://stackoverflow.com/a/43654115) in the thread you linked on StackOverflow.

**Comment by billygriffin** [comment]
We discussed this in our team meeting this week, and it's something we're planning to start working on.

There are two areas here where we think there's a lot of opportunity to improve.

1. Help prevent people from getting into the situation in the first place where their commits are unattributed to their GitHub account.

For this, we can use the knowledge that someone is signed into their GitHub account in GitHub Desktop to prompt them proactively to update their global Git config with their primary email address. This will ensure that any commits made from GitHub Desktop going forward will be attributed to their GitHub user account because the Git email address will match. It will also reduce the likelihood of a disconnect when committing via Desktop and committing from the CLI or another app.

We need to be careful here not to force people to use this, but we think that for the vast majority of users this will ensure that their commits are properly attributed.

2. If the person is in a state where their Git author email does not match an email on their GitHub account, and therefore will lead to their commits being unattributed, we can warn them ahead of time so they at least know about it.

This can be done in the commit flow. Since we currently have an avatar in the commit box, we think it's reasonable to visually indicate that there's something potentially wrong with the commit if we detect a mismatch between the Git email and the GitHub email. We should also give people the ability directly from here to update their Git email so their commits will be properly attributed.

cc: @niik @ampinsk

**Comment by kaster14** [comment]
> 
> 
> As part of an exercise I did a walk-though of setting up GitHub and Desktop as a "new" user. All was rather easy and straight-forward, expect for setting up and explanation of git.
> 
> Although we provide a short description in onboarding, I think we can do a better job of explaining its purpose and the distinction between GitHub and git.
> 
> There are a couple of ideas worth revisiting in #4002
> 
> It would be great to open up a dialogue again and see if any action items come out of it.

@tierninho Could you elaborate or direct me to on what the difference is between git and github and how that applies to github desktop and commit attribution?

What I'm looking for is a single login point, it doesn't make sense that I have to log in and additionally as a second step configure the "git" tab.

**Comment by steveward** [comment]
@kaster14 GitHub uses the email in your .gitconfig to associate commits with your GitHub account. Configuring your name and email in Git is not any sort of authentication -- it's just metadata about who created the commit. [This help article](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address#about-commit-email-addresses) has some more information, but let me know if you have any specific questions.

**Comment by kaster14** [comment]
Thanks @steveward for the link - I guess I don't understand the need for an email address to be used. What I am looking for is: "I sign into github desktop then when I make commits I expect to see my account name and avatar picture with the commit in the history tab (of github desktop), that name/avatar I would expect to be based off of the account I used to sign into github desktop.
If a different name or email besides the account name is desired to be used that should be a global setting that is tied to my github account and not something local to an instance of github desktop.
I share a machine with a coworker so every time one of us signs in we have to change the "account" tab and "git" tab of github desktop, I would like to have that extra step removed.

**Comment by steveward** [comment]
GitHub Desktop does automatically use your name and email when you first log in through the application. We have also put in measures to detect if you are committing with an email address that is not associated with your current account. You will see a warning in the commit summary box and there is a dropdown to select a correct email address. https://github.com/desktop/desktop/issues/11760 is also tracking the ability to change the name in this field.

Support for multiple accounts is being tracked in https://github.com/desktop/desktop/issues/3707. You can follow along for updates about that.

**Comment by Robgizzle4** [comment]
I'm sure it does that just sounds like some snitch shit get the fuck out of 
my email motherfucker

Sent with Aqua Mail for Android
https://www.mobisystems.com/aqua-mail
