### ISSUE TITLE
git merge API should return commit id

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#6110]
following on from #6089 and #5923, i think we should have our git merge api also return the resulting commit id, especially since `createMergeCommit` does.

https://github.com/desktop/desktop/blob/5ff3f0b318b99633e649574a646cd53daf9ca792/app/src/lib/git/merge.ts#L9-L12

should return `Promise<string>` instead, which will require some changes to `app-store` and/or `git-store` to handle properly.

you can (probably) use https://github.com/desktop/desktop/blob/19ced1ae19c16858b4303c2a6f9a03a077995f6c/app/src/lib/git/commit.ts#L69 to do the parsing.

**Comment by say25** [comment]
I can take this on
