### ISSUE TITLE
Allow user to manually check for installed Editors 

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6114]
If a user swaps editors (deletes current one and then adds a new one), installs an editor for the first time, or adds a new editor, there should be a manual check in the UI if Desktop fails it automatically pick it up right away.

Perhaps an icon next to the "No editors found text"? And/or a restart hint?
<img width="444" alt="screen shot 2018-11-06 at 3 02 12 pm" src="https://user-images.githubusercontent.com/14828183/48099713-4d8a6800-e1d5-11e8-8b76-00f277c32c49.png">

Info needed around:
- [ ] Metrics on the amount of users who have no editor, re https://github.com/desktop/desktop/issues/6060#issuecomment-436027468
- [ ] Metrics on the amount of users who have more than one editor

Command-line equivalent of what Desktop does to recognize an editor:
```
$ mdfind kMDItemCFBundleIdentifier = "com.github.GitHubClient"
/Users/tabbutton/src/desktop/dist/GitHub Desktop-dev-darwin-x64/GitHub Desktop-dev.app
/Applications/GitHub Desktop.app
/Users/tabbutton/Documents/GitHub/desktop-internal-review/dist/GitHub Desktop-dev-darwin-x64/GitHub Desktop-dev.app
$ mdfind kMDItemCFBundleIdentifier = "com.microsoft.VSCode"
/Applications/Visual Studio Code.app
```

Editor integration reference: https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md

tested: 1.5.0-beta3, mac

**Comment by billygriffin** [comment]
The [metrics we're looking for here](https://github.com/desktop/desktop/issues/5431) should hopefully be included in 1.5.1 if we can swing it, but I'd like to have those prior to making any decisions on our path forward here.

**Comment by shiftkey** [comment]
@gfs raised similar feedback about this area in #7024

**Comment by billygriffin** [comment]
Wanted to capture that this is also closely related to #6386, which references the conflict resolution flow specifically but basically is around providing a better story for on-ramping people with no editors. I'm going to be writing up a meta issue around this that hopefully could allow us to close the existing ones and have a better feel for the full picture.

**Comment by billygriffin** [comment]
Now that we're bringing the editor states more in sync in #8387, I think this is ok to be closed for now as it's an implementation detail. The meta-issue in #7033 is still useful, and I think we could think about how we more cleanly get people with no editor set up initially like we do in the tutorial, but that's outside the scope of this issue.
