### ISSUE TITLE
Branch panel should close after merging from merge dialog

### ISSUE THREAD

**Issue by ampinsk** [desktop/desktop#6115]
When I merge from the merge dialog, I expect the dialog and the branch panel to close and send me back to the main app state

Right now it does this: 

![kapture 2018-11-06 at 16 00 28](https://user-images.githubusercontent.com/10404068/48101858-567f3780-e1dd-11e8-8eec-0195d5f06282.gif)

**Comment by shiftkey** [comment]
Pulling this into 1.5.1 but I think it can be worked on whenever we have bandwidth.
