### ISSUE TITLE
Error: Cannot lock ref 'refs/remotes/origin/master'

### ISSUE THREAD

**Issue by arbuzzer** [desktop/desktop#6121]
I have some problem with my GitHub. I read similar questions and answers to them in many forums, but unfortunately nothing helped.

**error: cannot lock ref 'refs/remotes/origin/master': unable to resolve reference
'refs/remotes/origin/master': reference broken
From https://github.com/arbuzzer/arbuzzer.github.io
! [new branch] master -> origin/master (unable to update local ref)**

**Comment by billygriffin** [comment]
Hi @arbuzzer, thanks for the report and sorry you're having issues. 

We ask that folks fill out the template so we can better understand your setup and what's going on so we make the best use of the maintainers' time. Here's the template you need: https://github.com/desktop/desktop/issues/new?template=bug_report.md

Thanks for understanding and meeting us halfway! 😄

**Comment by steveward** [comment]
@arbuzzer It looks like there may be some underlying repository corruption that is causing this issue. Could you go to the file menu in GitHub Desktop and select `Repository` > `Open in <your_default_command_line_application>` and run the command `git fsck`? That should give some some more information about this error. Please share the full output of that command.

**Comment by arbuzzer** [comment]
> @arbuzzer It looks like there may be some underlying repository corruption that is causing this issue. Could you go to the file menu in GitHub Desktop and select `Repository` > `Open in <your_default_command_line_application>` and run the command `git fsck`? That should give some some more information about this error. Please share the full output of that command.

![image](https://user-images.githubusercontent.com/23486809/48142278-2c994400-e2b5-11e8-933d-7fa6b8023667.png)

**Comment by arbuzzer** [comment]
> Hi @arbuzzer, thanks for the report and sorry you're having issues.
> 
> We ask that folks fill out the template so we can better understand your setup and what's going on so we make the best use of the maintainers' time. Here's the template you need: https://github.com/desktop/desktop/issues/new?template=bug_report.md
> 
> Thanks for understanding and meeting us halfway! 😄

## Description
**error: cannot lock ref 'refs/remotes/origin/master': unable to resolve reference
'refs/remotes/origin/master': reference broken
From https://github.com/arbuzzer/arbuzzer.github.io
! [new branch] master -> origin/master (unable to update local ref)**

## Version
*GitHub Desktop:
![image](https://user-images.githubusercontent.com/23486809/48142800-2788c480-e2b6-11e8-874a-339436652f40.png)

*Operating system:
![image](https://user-images.githubusercontent.com/23486809/48142767-1770e500-e2b6-11e8-85cb-4da2cb9dc20c.png)

## Steps to Reproduce
1. I read the whole topic on this site and none of the proposed solutions helped me. (https://stackoverflow.com/questions/2998832/git-pull-fails-unable-to-resolve-reference-unable-to-update-local-ref)

### Expected(Blue Box) and Actual(Red Box) Behavior
1. ![image](https://user-images.githubusercontent.com/23486809/48143223-04124980-e2b7-11e8-92af-3ca402743bbf.png)
2. ![image](https://user-images.githubusercontent.com/23486809/48143321-302dca80-e2b7-11e8-800e-8279ffcec867.png)
3.![image](https://user-images.githubusercontent.com/23486809/48143422-6e2aee80-e2b7-11e8-9fab-9564e0313ea9.png)
**And so with every command that people offer.**

## Additional Information
[Profile-20181107T180828.zip](https://github.com/desktop/desktop/files/2558231/Profile-20181107T180828.zip)


### Logs
[2018-11-07.desktop.production.log](https://github.com/desktop/desktop/files/2558219/2018-11-07.desktop.production.log)
[2018-10-03.desktop.production.log](https://github.com/desktop/desktop/files/2558220/2018-10-03.desktop.production.log)
[2018-10-02.desktop.production.log](https://github.com/desktop/desktop/files/2558221/2018-10-02.desktop.production.log)
[2018-09-11.desktop.production.log](https://github.com/desktop/desktop/files/2558222/2018-09-11.desktop.production.log)
[2018-09-10.desktop.production.log](https://github.com/desktop/desktop/files/2558223/2018-09-10.desktop.production.log)
[2018-09-07.desktop.production.log](https://github.com/desktop/desktop/files/2558224/2018-09-07.desktop.production.log)
[2018-09-05.desktop.production.log](https://github.com/desktop/desktop/files/2558225/2018-09-05.desktop.production.log)
[2018-09-04.desktop.production.log](https://github.com/desktop/desktop/files/2558226/2018-09-04.desktop.production.log)
[2018-09-03.desktop.production.log](https://github.com/desktop/desktop/files/2558227/2018-09-03.desktop.production.log)
[2018-09-01.desktop.production.log](https://github.com/desktop/desktop/files/2558228/2018-09-01.desktop.production.log)

**Comment by steveward** [comment]
Thanks for sharing that information @arbuzzer. A few other questions:

- Based on the screenshot it looks like you are were running those commands in your root directory (i.e. C:\Users\Your_User) -- is that the correct location of this repository, or is it possibly in a different directory? If you are storing this repository in a different location you will need to run Git commands from within that directory that contains your repository.
- Is this a repository that you just freshly cloned to your local machine using GitHub Desktop?

It would also be helpful if you could run the following two commands within the repository directory to provide more configuration information about your local repository:

`git branch -a`
`git config -l --list`

Please let me know the output of both of those commands

**Comment by arbuzzer** [comment]
> Спасибо, что поделились этой информацией @arbuzzer . Еще несколько вопросов:
> 
> * На основе скриншота похоже, что вы выполняли эти команды в корневом каталоге (например, C: \ Users \ Your_User) - это правильное расположение этого репозитория, или это возможно в другом каталоге? Если вы храните этот репозиторий в другом месте, вам нужно будет запустить команды Git из этого каталога, содержащего ваш репозиторий.
> * Является ли это репозиторием, который вы только что недавно клонировали на локальную машину, используя GitHub Desktop?
> 
> Было бы также полезно, если бы вы могли запускать следующие две команды в каталоге репозитория, чтобы предоставить дополнительную информацию о конфигурации вашего локального репозитория:
> 
> `git branch -a`
> `git config -l --list`
> 
> Пожалуйста, дайте мне знать выход обеих этих команд.

![image](https://user-images.githubusercontent.com/23486809/48161148-8ebc6e00-e2e2-11e8-8300-2b8c7d13f329.png)
![image](https://user-images.githubusercontent.com/23486809/48161227-b57aa480-e2e2-11e8-96b1-25051048e00a.png)![image](https://user-images.githubusercontent.com/23486809/48161249-c0353980-e2e2-11e8-8d5b-eb865f8ed64f.png)

**Comment by arbuzzer** [comment]
> Thanks for sharing that information @arbuzzer. A few other questions:
> 
> * Based on the screenshot it looks like you are were running those commands in your root directory (i.e. C:\Users\Your_User) -- is that the correct location of this repository, or is it possibly in a different directory? If you are storing this repository in a different location you will need to run Git commands from within that directory that contains your repository.
> * Is this a repository that you just freshly cloned to your local machine using GitHub Desktop?
> 
> It would also be helpful if you could run the following two commands within the repository directory to provide more configuration information about your local repository:
> 
> `git branch -a`
> `git config -l --list`
> 
> Please let me know the output of both of those commands


![image](https://user-images.githubusercontent.com/23486809/48161525-6da84d00-e2e3-11e8-921c-fdc02db1e9a1.png)
![image](https://user-images.githubusercontent.com/23486809/48161471-50737e80-e2e3-11e8-92cf-7714a237f03e.png)
![image](https://user-images.githubusercontent.com/23486809/48161486-579a8c80-e2e3-11e8-9cb9-8fa081438d48.png)

**Comment by steveward** [comment]
Thanks @arbuzzer. Try running the command `git fetch --all` to grab the remote `origin/master` branch again. That should hopefully fix this issue.

**Comment by arbuzzer** [comment]
> Спасибо @arbuzzer . Попробуйте запустить команду, `git fetch --all`чтобы `origin/master`снова захватить удаленную ветку. Это, надо надеяться, исправить эту проблему.

![image](https://user-images.githubusercontent.com/23486809/48185891-1a63e800-e33f-11e8-8f8f-50db4c52b2e2.png)

**Comment by arbuzzer** [comment]
> Thanks @arbuzzer. Try running the command `git fetch --all` to grab the remote `origin/master` branch again. That should hopefully fix this issue.

Maybe it will help me to reinstall the system, or is it easier for me to create a new account? It is just important for me to use this application.

**Comment by steveward** [comment]
@arbuzzer apologies -- I think we need to clean things up before running that command. Try these steps:

`rm .git/refs/remotes/origin/master`
`git fetch`
`git branch --set-upstream-to=origin/master`

Let me know if that doesn't get things working.

**Comment by arbuzzer** [comment]
> @arbuzzer apologies -- I think we need to clean things up before running that command. Try these steps:
> 
> `rm .git/refs/remotes/origin/master`
> `git fetch`
> `git branch --set-upstream-to=origin/master`
> 
> Let me know if that doesn't get things working.

It doesn't work :(
![image](https://user-images.githubusercontent.com/23486809/48226757-356b4200-e3a9-11e8-8f8b-e3dba6713be6.png)

**Comment by steveward** [comment]
@arbuzzer sorry about that -- you will need to run `del .git/refs/remotes/origin/master` since you are using the command prompt.

>Maybe it will help me to reinstall the system, or is it easier for me to create a new account? It is just important for me to use this application.

If you would like you can also perform a fresh clone of the repository to GitHub Desktop -- a fresh clone will not have the issues you are encountering.

**Comment by shiftkey** [comment]
Repository fixes aside, I think #6141 here should prevent us from ending up in this situation again

**Comment by arbuzzer** [comment]
> @arbuzzer сожалеет об этом - вам нужно будет запускать `del .git/refs/remotes/origin/master`с тех пор, как вы используете командную строку.
> 
> > Может быть, это поможет мне переустановить систему, или мне легче создать новую учетную запись? Для меня просто важно использовать это приложение.
> 
> Если вы хотите, чтобы вы также могли использовать новый клон репозитория для GitHub Desktop - новый клон не будет иметь проблем, с которыми вы сталкиваетесь.

![image](https://user-images.githubusercontent.com/23486809/48268773-9abd4280-e43e-11e8-8116-c1c7885d0b65.png)

**Comment by steveward** [comment]
Sorry for the delay in getting back to you @arbuzzer. I'm not sure why the `refs` directory would not exist unless it was deleted. If you navigate to the `GitHub\arbuzzer.github.io\.git\refs` in File Explorer do you see anything there?

**Comment by shiftkey** [comment]
Closing this out due to inactivity.

@arbuzzer if you're able to answer @steveward's question in the previous comment we're happy to revisit it.

**Comment by Ngwind** [comment]
nice!this solved my problem

**Comment by arpitgupta19** [comment]
This worked for me :
**git remote prune origin**

**Comment by xiye518** [comment]
git remote prune origin   
This worked for me too!

**Comment by donprecious** [comment]
Try

```
$ git gc --prune=now
$ git remote prune origin
```

cleaning-up your local repository with:

**Comment by sugoireed** [comment]
After searching constantly, this is the solution that worked for me which entails unsetting/removing the Upstream

     git branch --unset-upstream

**Comment by briancalma** [comment]
> git branch --set-upstream-to=origin/master

It worked like a charm! Thanks

**Comment by richierich25** [comment]
rm .git/refs/remotes/origin/master
git fetch
git branch --set-upstream-to=origin/master

--> This worked for me magically.

**Comment by Dzone1658** [comment]
git fetch --all
 git branch --set-upstream-to=origin/master

/* This one works for me */
thanks a lot.

**Comment by rishabh-mmc** [comment]
> rm .git/refs/remotes/origin/master
> git fetch
> git branch --set-upstream-to=origin/master
> 
> --> This worked for me magically.

@richierich25 worked for me too
thanks

**Comment by BellatrixLeStranger** [comment]
I had a similar issue running VSCode on Windows 10 and trying to commit changes or push. However what solved it for me was changing my controlled folder access in Windows settings which was preventing git from creating the .lock files locally.

**Comment by mkkmail** [comment]
> @arbuzzer apologies -- I think we need to clean things up before running that command. Try these steps:
> 
> `rm .git/refs/remotes/origin/master`
> `git fetch`
> `git branch --set-upstream-to=origin/master`
> 
> Let me know if that doesn't get things working.

This worked for me. Thanks!

**Comment by PETEROLO291** [comment]
None of the previous methods worked for me, so what I did was make a copy of the folder, delete the folder, go to GitHub Desktop, clone the repository, paste the files that I had modified that I couldn't upload and that's it.

**Comment by AshutoshSajan** [comment]
> @arbuzzer apologies -- I think we need to clean things up before running that command. Try these steps:
> 
> `rm .git/refs/remotes/origin/master`
> `git fetch`
> `git branch --set-upstream-to=origin/master`
> 
> Let me know if that doesn't get things working.

thank you

**Comment by CopyBug** [comment]
> > @arbuzzer道歉——我认为我们需要在运行该命令之前清理一下。尝试以下步骤：
> > `rm .git/refs/remotes/origin/master`
> > `git fetch`
> > `git branch --set-upstream-to=origin/maste
谢谢你
