### ISSUE TITLE
GithubDesktop installed in the Debian family of Linux 

### ISSUE THREAD

**Issue by hanbing5210** [desktop/desktop#6128]
Can you come up with a tutorial to install on Linux ？

**Comment by shiftkey** [comment]
@hanbing5210 please have a read of the current documentation about our [Linux testing](https://github.com/desktop/desktop/blob/master/docs/contributing/linux-testing-and-you.md), which links off to where to find the release candidate installers.

After that, all you should need to do is something like this:

```
dpkg -i /path/to/deb/GitHubDesktop-linux-amd64-[version].deb
apt-get install -f
```

For any further issues or feedback, please open an issue over on my fork of Desktop: https://github.com/shiftkey/desktop.

**Comment by hanbing5210** [comment]
if i installed in other Linux system also fixed？ @shiftkey

**Comment by shiftkey** [comment]
@hanbing5210 please open issues for any other questions or feedback over on my fork of Desktop: https://github.com/shiftkey/desktop.
