### ISSUE TITLE
migrate OAuth flow to use external website 

### ISSUE THREAD

**Issue by marcpalm** [desktop/desktop#6130]
**Please describe the problem you think should be solved**
Why it is not a potential security problem that you ship the clientId and the secret for oauth in your app?
I am referring to `/app/info.ts`

**[Optional] Do you have any potential solutions in mind?**
Host a backend endpoint doing the authentication and forward the token 1234 via `x-github-client/token/1234` to the app? You are doing something similar already in the app.

Possible other solutions:
https://auth0.com/blog/securing-electron-applications-with-openid-connect-and-oauth-2/

**Comment by shiftkey** [comment]
@marcpalm are you referring to this one?

https://github.com/desktop/desktop/blob/85cf9dbae5055cc4f0de9fb4f7046cd32607e877/app/app-info.ts#L9-L10

We made a conscious decision to do this a while ago because it helps with developing locally, and we wrote some documentation indicating this is for development purposes only: https://github.com/desktop/desktop/blob/master/docs/technical/oauth.md#developer-oauth-app

**Comment by marcpalm** [comment]
Ok, got it. I am just trying to copy somehow what you guys are doing here in my own app. Great UX with the shell opening and logging in.

I have digged actually deeper than that and tried to understand pretty much the whole flow.
So I thing the browser redirects to x-github-client/..., which then eventually hits requestOAuthToken. This seems to be in production.

Let me demonstrate what I understood so far:

1. Click on 'login via browser'
2. OAuth Flow starts in Shell
3. Shell redirects to x-github-client/oauth
4. Handler https://github.com/desktop/desktop/blob/master/app/src/main-process/main.ts#L83 consumes the request
5. This ends up here after a few steps https://github.com/desktop/desktop/blob/master/app/src/lib/dispatcher/dispatcher.ts#L847
6. Which ends up here
https://github.com/desktop/desktop/blob/master/app/src/lib/api.ts#L867

That is why it apparently uses the clientSecret at one point.
Maybe the best way to check this is whether there are client_secrets passed to the actual app inside travis, appveyor and circleci, right?

**Comment by marcpalm** [comment]
A simpler/safer solution might be:

1. Host an express app for oauth and token access for only loggedin
2. Access this express app in a separate Browserwindow
3. Copy the token in some database (Redis or in Memory)
4. Send a rest api request to expose the token for the authenticated user
5. Browserwindow sends it to the main process and saves it in keytar
6.  Send a rest api request to delete the token for the authenticated user 
7. Browserwindow closes

That way clientSecret is server side on your hosted service only.

**Comment by marcpalm** [comment]
By the way, it depends on clientSecret for the usual authentication flow as well https://github.com/desktop/desktop/blob/e99cfa98e39fac4bd070fc359f35574c66b65dcc/app/src/lib/stores/sign-in-store.ts#L308

**Comment by shiftkey** [comment]
> That is why I think that it apparently uses the clientSecret in someway in production.

It does, and this is just a limitation of how client-side apps that do OAuth currently are configured.

> I am far from being an expert here, but a safer solution might be:
>
> ...

Yeah, I keep meaning to book in some time with @shana to chat with her about the work they did with the GitHub for VSCode extension and see if we can leverage that.

**Comment by shiftkey** [comment]
Updating the title to reflect and evaluate the work required to migrate away from having the OAuth Client ID and Secret baked into the app.

**Comment by kevincastejon** [comment]
I'm stunned to see that the client and secret id are public for the GitHubDesktop app...
I understood that there is no real way to hide these credentials into an Electron app, so I'm asking myself:
What the best hacker could do with the clientId and secretId of my app?
From what I understood, he could only build another app that would connects to GitHub as if it was mine. 
I'm currently building an open-source app, with GitHub user login, can I put my clientId and secretId into it 'safely'?

**Comment by billygriffin** [comment]
We've discussed this with our appsec team and I'm going to close this as just a byproduct of the OAuth implementation and not something we need to change.
