### ISSUE TITLE
text files which differ by added/remove should be resolved via command line

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#6132]
similar to #6066, i think we can do a first iteration on #6123, where we display a similar UI that says "Use command line to resolve this file"

![ui reference](https://user-images.githubusercontent.com/10404068/47819720-94311b80-dd18-11e8-83d9-dffd0a9268a7.png)

**Comment by shiftkey** [comment]
@outofambit does this mean we can close #6123 if this issue replaces it?

**Comment by outofambit** [comment]
ah i was thinking of this as a baby step to really addressing with a more fully baked UI, but from the words in both issues that's totally not clear :)

**Comment by shiftkey** [comment]
In my head the work we're doing with #6062 should be applicable to text files without conflict markers, and it feels like this is the functional fix for the bug I wrote up in #6123

**Comment by outofambit** [comment]
ah that makes sense, i'll close this and retarget to that bug :)
