### ISSUE TITLE
If coauthor and committer are identical, their avatar appears twice

### ISSUE THREAD

**Issue by varkor** [desktop/desktop#6135]
Say we have the following scenario:
- Person A authored a commit.
- Person B committed it.
- Person B is also listed as a co-author in the `Co-authored-by` field .

Then the icons for contributors for that commit will show Person B twice.
Example:
![image](https://user-images.githubusercontent.com/3943692/48227779-31d0be80-e39b-11e8-86eb-88bde4ef8a18.png)

The co-author and committer should be deduplicated.

**Comment by shiftkey** [comment]
@varkor thanks for the report! I think the only question I have here is: "What Does GitHub The Website Do?"

 - if it de-duplicates the author information, then that's great and Desktop should do the same
 - if it does not, we should check in with them and confirm whether the website needs to be updated too

@varkor are you able to create a public repository with an example and share it here, so we can confirm we're all working with the same commit details? The commits page for a repository is the equivalent view to what we're doing in History, and co-authored commits should be stacked like this:

<img width="430"  src="https://user-images.githubusercontent.com/359239/48269854-f079f680-e40e-11e8-9ee2-cacd10c5adc8.png">

**Comment by varkor** [comment]
@shiftkey: ah, you're right — I should have clarified this point!

GitHub does de-duplicate the author information. The commit shown in the original post is this one: https://github.com/varkor/rust/commit/15c1abee875cd4ab7ffd01d62d64c399924370f5 (or https://github.com/varkor/rust/commits/const-generics-redux-backup?after=b91f20ddf51ac94ca59d18617503bc3114fa75bb+34 for the list-like format).
(Notice also how the text is different.)

![image](https://user-images.githubusercontent.com/3943692/48277061-83cc1f80-e441-11e8-88d5-9155d01f36a7.png)

**Comment by shiftkey** [comment]
@varkor thanks for the extra context! I'm going to mark this as `help-wanted` because I think it's ideal for someone to dig into. I'd start by checking `getAvatarUsersForCommit` because that's where we build up this list, and we don't seem to do any checks there for authors and committers:

https://github.com/desktop/desktop/blob/26889a524bf0565dac498f0a8f80169e1cecc10f/app/src/models/avatar.ts#L70
