### ISSUE TITLE
T&Cs and License button focus is inconsistent

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6137]
When opening the Terms and Conditions modal the `Close` button is in focus, yet when you open the License and Open Source Notices, the `Close` button is not in focus. If you click `enter` on the latter, then it opens the first link in the text. 

Not sure which we should lean towards (in focus vs not in focus). Thoughts @billygriffin ?

<img width="451" alt="screen shot 2018-11-08 at 2 33 54 pm" src="https://user-images.githubusercontent.com/14828183/48231550-5d37b700-e363-11e8-9f3c-33c817d0f557.png">

Go to About GitHub Desktop to test this.

Good place to start for any one wanting to work on this:
https://github.com/desktop/desktop/blob/master/app/src/ui/terms-and-conditions/terms-and-conditions.tsx
https://github.com/desktop/desktop/blob/master/app/src/ui/acknowledgements/acknowledgements.tsx

tested: 1.5.0-beta4, mac

**Comment by billygriffin** [comment]
I think we should change the behavior of the License and Open Source Notices to match the behavior of the Terms & Conditions.

In other words, clicking `enter` on the License and Open Source Notices should close the modal, not bring you to the website. 😄 

This is what the new behavior should be:
1. Open "About GitHub Desktop"
2. Click on "License and Open Source Notices"
3. Click `Enter`/`Return`
4. "Close" button should be invoked and the modal should close.
