### ISSUE TITLE
Login Issue Ubuntu 18.04

### ISSUE THREAD

**Issue by yatosha** [desktop/desktop#6144]
An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.537" (uid=1000 pid=20235 comm="/snap/github-desktop/35/opt/GitHubDesktop/desktop " label="snap.github-desktop.github-desktop (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.26" (uid=1000 pid=1424 comm="/usr/bin/gnome-keyring-daemon --start --components" label="unconfined")

**Comment by shiftkey** [comment]
@yatosha thanks for the feedback, but this isn't the right place to submit an issue. From [the docs](https://github.com/desktop/desktop/blob/master/docs/contributing/linux-testing-and-you.md#providing-feedback):

> If you find an issue with running the installer or Desktop on your platform, please open an issue on [shiftkey/desktop](https://github.com/shiftkey/desktop). Do not open issues against the main repository - these issues will be closed with a note to report the issue to the right repository.
