### ISSUE TITLE
Merge into Branch not Dismissable with Escape Key Immediately After 

### ISSUE THREAD

**Issue by say25** [desktop/desktop#6154]
## Description
Merge into Branch modal not Dismissible with `Escape` Key Immediately After opening it

## Version
* GitHub Desktop: 1.5.0-beta4
* Operating system: Windows 10

## Steps to Reproduce
1. Open Modal with `Ctrl + Shift + M`
1. Try to dismiss with escape key

### Expected Behavior
It dismisses.

### Actual Behavior
Nothing

<img width="528" alt="screen shot 2018-11-09 at 2 14 41 pm" src="https://user-images.githubusercontent.com/14828183/48291038-d4378300-e429-11e8-8278-3264739ff156.png">

1.5.0-beta5

**Comment by altaf933** [comment]
Can I work on this issue ? PR is almost ready.
