### ISSUE TITLE
Renaming a branch removes it from Recent Branch category

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6155]
If a branch is renamed then it should not be removed from the Recent Branch category in the branch list.

<img width="382" alt="screen shot 2018-11-09 at 2 29 54 pm" src="https://user-images.githubusercontent.com/14828183/48291628-0518b780-e42c-11e8-826a-3d926648d2f7.png">

Repro:
- Select any branch but default, that is in the Recent branch category
- Rename it
- The branch is pushed down into the Other category, sometimes out of sight if there are a lot of branches

Expected result: branch remains in Recent Branches category with the new name

1.5.0-beta5, mac

**Comment by gnehcc** [comment]
Hi,  can I give a try to fix this issue? Cheers.

**Comment by shiftkey** [comment]
@gnehcc go for it!
