### ISSUE TITLE
Discarding changes fails in substitute drive

### ISSUE THREAD

**Issue by LAK132** [desktop/desktop#6157]
## Description

I have a [substitute drive](https://ss64.com/nt/subst.html) set up that points to my repositories folder (`subst r: "d:\repos"`). If I clone a repo under `D:\repos` everything works fine, but if I clone it under `R:` then GitHub Desktop fails to discard changes. I get the feeling this might be related to delete to recycling bin not working from substitute drives? 

## Version

* GitHub Desktop: 1.4.3

* Operating system: Microsoft Windows [Version 10.0.17134.345]

## Steps to Reproduce

1. create a substitute drive (`subst r: "c:\some\folder"`)
2. clone a repo onto the subst drive (`R:\`)
3. make changes to the repo
4. attempt to discard the changes

### Expected Behavior

Should discard changes

### Actual Behavior

Hangs for a moment, then the popup closes, does nothing

## Additional Information

https://i.gyazo.com/ac22aa7a88835de4fd18d9a3aad0a138.gif

### Logs

https://pastebin.com/d5NH8Aiw

**Comment by tierninho** [comment]
@LAK132 Thanks for filing this. 

I am not familiar with substitute drives, but based on the submodule mention in your logs, this issue looks to be similar to https://github.com/desktop/desktop/issues/4592 and https://github.com/desktop/desktop/issues/4180 as you are attempting to create a directory within an existing directory.

Perhaps one of our core members will be able to shed some further light on this. Until then, adding the `investigation-needed` needed label for now.

**Comment by LAK132** [comment]
This issue also occurs on a near empty repo with no submodules ([log](https://pastebin.com/mjz1v0zm))

**Comment by tierninho** [comment]
Looks to be an [existing problem](https://github.com/desktop/desktop/issues/4194#issuecomment-397542724) that we haven't resolved yet, based on the `No submodules found. Skipping "git submodule status"` mention in your latest logs. 

We will update the corresponding issues once resolved, so please follow along there. Until then, I will close this ticket. Thanks for letting us know.
