### ISSUE TITLE
Github cloning repository "remote end hung up unexpectedly"

### ISSUE THREAD

**Issue by FerencRozsa** [desktop/desktop#6158]
I am trying to clone a repository I made in github desktop over at university. at home I use github desktop to clone a repository, and when it gets to 65% it throws out a big error
![giterrorbottom](https://user-images.githubusercontent.com/43654758/48307123-5ca74800-e53e-11e8-8262-9d49224e4816.png)
I tried cloning the same repository in my laptop with github desktop too. and instead of throwing the error at 65% it throws it at 23%, everytime I do it on both.

Also I cannot publish a repository into github from github desktop for some reason.
why is this happening?
every repository clones fine on the university PC's

**Comment by billygriffin** [comment]
Hi @FerencRozsa, thanks for your issue! Would you mind filling out the template please? You can find it here: https://github.com/desktop/desktop/issues/new?template=bug_report.md 

We need to know a few more details about your setup to figure out what might be causing the issues you're running into. If it's a public repo that you're trying to clone, if you could link that as well we'd appreciate it.

**Comment by billygriffin** [comment]
Closing in favor of #6193
