### ISSUE TITLE
Enable Logout on Github Desktop exit

### ISSUE THREAD

**Issue by GerdTautenhahn** [desktop/desktop#6173]
Our Team works often on customer servers to develop database solution using T-SQL. Therefore we install Github Desktop on the customer Server and we clone the repositiory of the customer there. 

We realy develop on the customer server, we not only do a deployment there. The reason is, that we are not allowed to copy databases etc. to a local development machine.

This workflow works fine - there is only one security issue. Every teammember must have always in mind to explicit logout for GitHub Desktop, when closing the serverconnection. Otherwise the customer administrator could use our userprofile and could clone repositories from different customers.

We would like to have option in Github Desktop user preferences
"Automatic Logout on exit Github Desktop"
![logout](https://user-images.githubusercontent.com/15925724/48338411-e3a31000-e665-11e8-8918-7209087b1770.PNG)

If this option is activated, Github Desktop would delete the credentials of the user, when the application is closed.

**Comment by billygriffin** [comment]
Hi @GerdTautenhahn, thank you so much for the issue and suggestion. That sounds like a tricky situation to make sure everyone is appropriately logged out after use. However, based on how we've seen GitHub Desktop used, this feels like a pretty niche use case, and I'm hesitant to support an option like this if it is indeed a very rare occurrence. Generally we want GitHub Desktop to be part of users' regular workflow, so convenience of already being logged in each time you start the app is very important. I'm going to close this issue to indicate that we do not intend to support this, but if we learn that the use case is more widespread, we're happy to revisit. This document describes how we think about what GitHub Desktop is intended to be used for and how we determine what we support and don't support: https://github.com/desktop/desktop/blob/master/docs/process/what-is-desktop.md Thanks again!
