### ISSUE TITLE
I can't found the window on Windows 10

### ISSUE THREAD

**Issue by CNwh3t** [desktop/desktop#6174]
After i opened it , i can see it on the task bar.
And when the mouse hover over the task bar ,i can see thumbnail of the client,
but when i hover the mouse over the thumbnail,it doesn't diplay the window on the desktop.
![github](https://user-images.githubusercontent.com/35597683/48339340-f2f47e80-e6a2-11e8-9c5c-cdad351169fd.png)
I can't found the window ,i can't use it .

**Comment by billygriffin** [comment]
Hi @CNwh3t, sorry you're having issues viewing the application. Would you mind providing the OS version you're using? 

Also, to confirm, if you click on the tab at the bottom of the screen, GitHub Desktop does not pop up, correct? Have you also tried to quit the program and reopen it?

**Comment by j-f1** [comment]
Could this be #2107?

**Comment by shiftkey** [comment]
Seconding @j-f1's theory - this might be Desktop rendering on a second screen that's no longer connected -  @CNwh3t do you have a multiple monitor setup?

**Comment by billygriffin** [comment]
Thanks @CNwh3t, sounds like the same thing that #2107 will hopefully address. Thanks for letting us know it was resolved!
