### ISSUE TITLE
Application becomes unresponsive with Fetch Origin with Netbeans repository

### ISSUE THREAD

**Issue by lalo-mx** [desktop/desktop#6180]
**Please describe the problem you think should be solved**
Application becomes unresponsive with Fetch Origin

Steps to reproduce

1. Clone https://github.com/apache/incubator-netbeans.git
2. Wait for the clone to finish
3. Click on Fetch Origin
4. While the Fetch Origin is processing the application becomes unresponsive and using a lot of CPU(80-90%) but not so much RAM(Around 300 MB).
5. Only happens the first time you click on Fetch Origin
Environment: 
Github Desktop Version: 1.4.3
OS: Windows 10 Version 18031
RAM: 12 GB
PROCESSOR: Intel Core i5-4460 3.20 GHz

**Expected result**
The application should not become unresponsive.

[2018-11-12.desktop.production.log](https://github.com/desktop/desktop/files/2574084/2018-11-12.desktop.production.log)

**Comment by lalo-mx** [comment]
I did the same tests today and the application slowed a little bit but remain responsive. Maybe it is related with another process in my computer. Thanks for the feedback and if it happen again i will try to isolate the process and found a reproducible escenario.

**Comment by shiftkey** [comment]
@lalo-mx thanks for the update!
