### ISSUE TITLE
remove old feature flags

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#6184]
there are a number of feature flags in https://github.com/desktop/desktop/blob/development/app/src/lib/feature-flag.ts that just return `true`. let's remove these functions and all references to them in the codebase. their respective features should be always be on.

- [x] `enableNotificationOfBranchUpdates()` - #6248
- [x] `enableRepoInfoIndicators()` - #6251
- [x] `enableMergeConflictDetection()` - #6250
- [x] `enableInAppReleaseNotes()` - #6243 
- [x] `enableMergeConflictsDialog()` - #6249

**Comment by shiftkey** [comment]
To be extra clear here, I'd recommend doing **one PR per feature flag**, as some changes will be more complex than others and it'll make reviews easier.

Also, `enableStatusWithoutOptionalLocks()` has only been enabled for everyone on `1.5.0` which is going out tomorrow, so if we can leave that to last just in case that'd be :gem:

**Comment by say25** [comment]
Good to close?
