### ISSUE TITLE
Branch name missing from Merge Conflict after restarting app

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6188]
If you quit and restart Desktop in the middle of a merge conflict then the compare-branch is missing from the title of merge conflict modal.

Repro:
- Compare two branches with a conflict
- When merge conflict modal appears, quit and restart
- Notice the compare-branch is missing

Title before restart:
<img width="509" alt="screen shot 2018-11-13 at 11 01 28 am" src="https://user-images.githubusercontent.com/14828183/48437067-40b9c700-e735-11e8-87ca-229fc67198c0.png">

Title after restart:
<img width="502" alt="screen shot 2018-11-13 at 11 07 07 am" src="https://user-images.githubusercontent.com/14828183/48437068-40b9c700-e735-11e8-8c55-feef18989510.png">

No relevant logs found. Tested in 1.5.0-beta5, mac.

**Comment by shiftkey** [comment]
I suspect @outofambit has some more context about this from the work in #6067

**Comment by altaf933** [comment]
I think, this one already resolved. Not seen in current build after restart.
<img width="537" alt="screen shot 2018-11-26 at 3 20 08 pm" src="https://user-images.githubusercontent.com/5979711/49006317-d79f6e00-f18e-11e8-8653-bf08bc14fe7e.png">

**Comment by tierninho** [comment]
@altaf933 Thanks for the confirmation. Closing the issue as I just verified the fix too.
