### ISSUE TITLE
 Failed to connect to www.google.com port 80: Timed out

### ISSUE THREAD

**Issue by LLdleo** [desktop/desktop#6195]
**Please describe the problem you think should be solved**
A clear and concise description of what the problem is and who else might be impacted. Screenshots are encouraged.

Example:

> “When I run into a merge conflict, I don’t know where to go to resolve it. Anyone who works off of multiple branches will likely run into this problem at least occasionally.”

**[Optional] Do you have any potential solutions in mind?**
A clear and concise description of one or more solutions you think might solve the problem. Please include any considered drawbacks or tradeoffs, and how users might use your solution(s). Screenshots or mockups are helpful here!

**Comment by LLdleo** [comment]
Failed to connect to www.google.com port 80: Timed out

**Comment by LLdleo** [comment]
This is what the client told me.
I already used a proxy for githubdesktop.exe

**Comment by LLdleo** [comment]
Will anyone helps me?
Much thanks

**Comment by shiftkey** [comment]
@LLdleo please submit a [bug report](https://github.com/desktop/desktop/issues/new?template=bug_report.md) issue template if you need help troubleshooting a problem with GitHub Desktop, as there is not enough information here for us to work with.
