### ISSUE TITLE
Icons of expand/collapse button are flipped

### ISSUE THREAD

**Issue by HazemAM** [desktop/desktop#6196]
## Description

When a commit message is long enough to be trimmed, the expand/collapse button has its icons flipped.

## Version

* GitHub Desktop: 1.4.3

* Operating system: Windows 10 version 1803

## Steps to Reproduce

1. Open a commit with an essay as a commit message

### Expected Behavior

2. Look at expand/collapse button
3. Not suffer

### Actual Behavior

2. Look at expand/collapse button
3. Suffer

### Shots of current state
![expand-button-1](https://user-images.githubusercontent.com/3602800/48479006-a3cb5c80-e80e-11e8-86a9-7eb429eca85a.jpg) ![expand-button-2](https://user-images.githubusercontent.com/3602800/48479014-a7f77a00-e80e-11e8-8db1-f8db3195befc.jpg)

**Comment by shiftkey** [comment]
@HazemAM thanks for the report (and the fresh PR) - I'm kind of amused it's taken this long for anyone to notice!
