### ISSUE TITLE
no moving a local copy of a repository?

### ISSUE THREAD

**Issue by kaigouthro** [desktop/desktop#6201]
When i got a new hard drive and moved my data to it, there is no way to point github desktop to the new location of files on the hard drive. the only method is to delete from github desktop and to re-initialize a new connection.

this can be a major issue if people are moving updated data meant to be pushed, because the only way to reconnect is to re-clone to a new location, then have to drag and drop in the updated files on top of the downloaded files, and then you're finally able to push data. 

it'd be solved in a  jiffy if you just allowed users to "change local storage location". .. i'm very surprised i couldn't find that option anywhere.. it should be a second tier mandatory feature.

**Comment by msftrncs** [comment]
@kaigouthro, you should have received the `Can't find "repository"` message, and you should have been able to use the 'Locate...' button to locate and restore access to the repository (with its new location) without losing anything.

It also should work fine to 'Remove' the missing repository, and then add the new location ('Add local repository') back as a new repository.  All the information about the repository, its origin, etc..,, is all stored in the folder, so its all restored immediately.

(I just tested simple renaming of a repository storage folder, and had no issues restoring access via either method).

**Comment by tierninho** [comment]
@kaigouthro The steps outlined by @msftrncs are correct. You may also use the `File > Add Local Repository` menu item to re-add your repo. 

Happy to reopen this issue if the problem persists. Thank you.

**Comment by billygriffin** [comment]
Thanks @msftrncs!

**Comment by Tobias-B-Besemer** [comment]
Anyway: Any option to it would be nice! ("Hang out & hang in" of Repro or something like that...)
Now the option/setting is to google the solution... Works, but...

**Comment by gingerbeardman** [comment]
I just changed my computer and moved my projects folder breaking all local repo links.

it's surprising i have to "locate..." each one individually

**Comment by tierninho** [comment]
You can optionally just remove them all and then drag n drop the relocated directories anytime.

**Comment by gingerbeardman** [comment]
Thanks, I took the opportunity to have a clear out. 30 mins well spent, I guess.
