### ISSUE TITLE
Github Desktop v1.5.0 does not work

### ISSUE THREAD

**Issue by freWalker** [desktop/desktop#6208]
## Description
After updated to v1.5.0, it does not work any more. The window of Github Desktop is just a blank space after restarted.

## Version

* GitHub Desktop: 1.5.0
* Operating system: macOS Mojave 10.14.1

**Comment by freWalker** [comment]
It worked after I re-downloaded the Desktop app from your website. Please just delete the issue. Thanks.

**Comment by billygriffin** [comment]
Thanks, glad to hear it’s working for you now @frewalker. I’m going to close this as you requested, but would you mind providing your OS version and the Desktop version you upgrade to 1.5 from (if you can remember that) in case we see similar reports? Thanks!

**Comment by freWalker** [comment]
@billygriffin Thanks for you comment.

We just met the issue again. I suppose it's a compatibility issue with Duet Display.
The following is the detail reproduce steps:
1. Open Duet Display and set an iPad as an external display.
2. Open Github Desktop

If I did not set my iPad as an external display by Duet Display, Github Desktop app will work well.

**Logs**

default	09:12:13.176231 +0800	GitHub Desktop	*** WARNING: Textured window <AtomNSWindow: 0x7fd9cfd0d3c0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
default	09:12:13.198760 +0800	GitHub Desktop	CVCGDisplayLink::setCurrentDisplay didn't find a valid display - falling back to 60Hz
