### ISSUE TITLE
Merge Conflict Resolution Can't Handle A File Being Deleted

### ISSUE THREAD

**Issue by say25** [desktop/desktop#6219]
When I run into a merge conflict, in which I or the branch I'm merging in deletes a whole file. I have to resolve via command line.

**[Optional] Do you have any potential solutions in mind?**
Ideally, I could have an option to take mine or theirs. (Delete the whole file or preserve changes.

![image](https://user-images.githubusercontent.com/7467062/48648457-5fca8a00-e9bd-11e8-9dbe-0ab57ecc0220.png)

**Comment by shiftkey** [comment]
@say25 I think you're interested in #6062 and in particular these mocks https://github.com/desktop/desktop/issues/6062#issuecomment-436728992

I've opened #6218 which should address these

**Comment by say25** [comment]
Closing as dupe
