### ISSUE TITLE
github desktop error 

### ISSUE THREAD

**Issue by dexter700** [desktop/desktop#6229]
n AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.127" (uid=1000 pid=6812 comm="/snap/github-desktop/35/opt/GitHubDesktop/desktop " label="snap.github-desktop.github-desktop (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.12" (uid=1000 pid=1616 comm="/usr/bin/gnome-keyring-daemon --daemonize --login " label="unconfined")

i am getting this error in Github desktop app downloaded from ubuntu software centre

how can i fix that ?
i logged in with my github account.. but no repositories showing there.

**Comment by Daniel-McCarthy** [comment]
Hi @dexter700,

I would like to clarify, you mentioned that you see no repositories showing.
When one initially installs GitHub Desktop and logs in, to access their repositories and start working in them, one must first clone the repositories. With GitHub Desktop you can do this via `File -> Clone Repository` or the shortcut `Ctrl + O`.

Then from that dialog you should be able to see your repositories and clone them into a folder to work from. With that said, is this issue preventing the cloning process? Are you able to find your repositories in this dialog?

I would love to get a better idea of the issue you are dealing with.

**Comment by shiftkey** [comment]
> i am getting this error in Github desktop app downloaded from ubuntu software centre

@dexter700 I think this is the same issue as https://github.com/shiftkey/desktop/issues/59 which should be resolved by the latest version available on the [releases](https://github.com/shiftkey/desktop/releases) tab there.

For reference, we're we're tracking Linux-specific issues over in [my fork](https://github.com/shiftkey/desktop) so I'm going to close this out for the moment to keep this separate from the main project. Please submit any future Linux-specific issues there.
