### ISSUE TITLE
close conflicts dialog

### ISSUE THREAD

**Issue by huangboju** [desktop/desktop#6245]
I just want to cancel, not abort

**Comment by RCMartins** [comment]
I also find this issue as a regression in the last GitHub Desktop update (1.5.0).
If I solve the conflicts in another tool, I go to Desktop and I only have Abort or Merge, I want to be able to check if the merge was done correctly before merging...

**Comment by shiftkey** [comment]
@huangboju @RCMartins thanks for the feedback. We're tracking this in #6213 so please follow along with that discussion.
