### ISSUE TITLE
Github Desktop Permission Denied

### ISSUE THREAD

**Issue by LisaBails** [desktop/desktop#6253]
When trying to clone any Repo within my organisation I get a "Permission Denied" Error.  I've had access to all repo's before and was able to clone/push/pull without issue. Now all my repo's are gone from within the Github Desktop application. But I can see the repos on Github Web. 

I've tried using SSH keys, I've installed and uninstalled... I've checked with Infrastructure at my company and they confirmed I have all permissions for organization. I saw this question was asked before and there was a solution but it was for Windows. (I'm using mac)

The only thing that has changed recently is that I am using a different version of IDE (Intellij). Doubt that this has anything to do with it. 

At my wits end - losing a lot of time trying to figure this out 

<img width="955" alt="screen shot 2018-11-21 at 8 41 39 am" src="https://user-images.githubusercontent.com/30228830/48823536-d4a91580-ed69-11e8-8299-91d01057a64c.png">

**Comment by shiftkey** [comment]
@LisaBails thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Finder** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information about the underlying error to help troubleshoot.

**Comment by shiftkey** [comment]
@LisaBails I think what's happening here is that the OS isn't letting the app create a folder at the root of the drive. Are you able to try a different path (say `/code/talarium`) after creating the initial `/code` folder?

**Comment by tierninho** [comment]
@LisaBails As we have not heard anything back from you, we are closing this issue for now. Please reach out if you need further help and we'd be happy to reopen the issue. Thanks!

**Comment by Amirrahman19** [comment]
I'm having the same problem and I've doubled checked that I have root access for every application in my mac

**Comment by mndbl** [comment]
i'm having the same problem in ubuntu 20.04

**Comment by TheEmeraldFalcon** [comment]
A bit late to the party, I had a similar issue, and my solution was to just shut down my IDE. I doubt it would work in this exact scenario, but it might work for some of the other people here asking about it.

**Comment by cmuhirwa** [comment]
I have the same issue on mac, I completely failed to resolve it

**Comment by FishMoy** [comment]
> 参加聚会有点晚了，我遇到了类似的问题，我的解决方案是关闭我的 IDE。我怀疑它在这种确切的情况下是否有效，但它可能适用于这里的其他一些询问它的人。



> A bit late to the party, I had a similar issue, and my solution was to just shut down my IDE. I doubt it would work in this exact scenario, but it might work for some of the other people here asking about it.

Great! it play a role,thanks bro :)
I think that IDE will occupy files. When Git try to commit it to branch, there will be some wrongs. And for answer @LisaBails question,  I think sometimes OS will occupy it too just like Deepin(Linux) always do it if you set something acturlly...qwq it's okay windows willnot do it weather you do
Then take a sip, unity editor also have this problem.

**Comment by seoProductions** [comment]
Any solution?
