### ISSUE TITLE
Repository Menu (Menu Bar) too narrow, or editor names too long, or needs tooltip.

### ISSUE THREAD

**Issue by msftrncs** [desktop/desktop#6266]
## Description
The Visual Studio Code editor fails to be identifiable in the Repositories menu.  I don't remember if the stable build or the insiders build is currently selected, and I am not getting any tooltip to help.

![image](https://user-images.githubusercontent.com/26179051/48884351-c13d8f00-ede9-11e8-8a16-d7f0497a98c3.png)

Possibly remedies (assuming that there isn't some other issue going on)

- display tooltip when menu item being cut off is hovered over.
- make menu wider, maybe auto width if possible.
- shorten editor menu names.

### Note

The right click menu over a changed file, or over the repository drop down, does show the entire editor name.  It appears to auto-size like normal for a right click menu.  Turns out it was Insiders ...

## Version
* GitHub Desktop: 1.5.1-beta0
* Operating system: Win 10 1809

**Comment by shiftkey** [comment]
@msftrncs thanks for the report. I thought we had an earlier issue about this but I couldn't find it, so I'm happy to use this issue to track it.

**Comment by msftrncs** [comment]
What is preventing an automatic width selection, the right justified shortcut details?

Since this is a variable length item (several items in this menu are) its kind of disappointing that an automatic width scheme doesn't work.

So I am finally getting an idea how the app works, so I found where this is set, and could post a PR that would at least open up the width of this menu a bit.

**Comment by tierninho** [comment]
@msftrncs there was an initial comment of the resize of Changes tab here https://github.com/desktop/desktop/issues/1588#issuecomment-329405096 although it may not fully apply here.

Also, we should consider what other parts of Desktop can benefit from automatic width selection (menu and panes alike), and figure out a way which is scalable, thus opening up your potential PR to all such areas. 🤔Approaching each area one-by-one might result in a lot of different solutions.

cc @billygriffin for thoughts

**Comment by msftrncs** [comment]
@tierninho, I just was referencing the existing manual width assignments for the other menus:

https://github.com/desktop/desktop/blob/18c8fe02bff92bcb2c71cc44f31a630982eeb123/app/styles/ui/_app-menu.scss#L12-L30

So I think for now one should be also posted for the 'repository' menu.  I determined it needs to be set about 325px for 'Open in Visual Studio Code Insiders' to fit.

It would definitely be nice for an auto sizing solution. I do believe Windows apps menu's are auto-sized so the app developer doesn't have to concern themselves with it.    Maybe Electron 3 has some enhancements coming that would help this?

**Comment by billygriffin** [comment]
> Also, we should consider what other parts of Desktop can benefit from automatic width selection (menu and panes alike), and figure out a way which is scalable, thus opening up your potential PR to all such areas. 🤔Approaching each area one-by-one might result in a lot of different solutions.

I think that's right, but I'm always open to trying something in one place and seeing how it feels and if it's extensible elsewhere. But definitely good to look out for different solutions to the same problem in various parts of the app.

@desktop/design and @niik Do either of you have a view on our approach here?

**Comment by tierninho** [comment]
Confirming I see the same result in Windows 10. Perhaps the easiest solution is to change the name to "VS Code" as it's a commonly referenced name for the editor.

**Comment by billygriffin** [comment]
> Perhaps the easiest solution is to change the name to "VS Code" as it's a commonly referenced name for the editor.

If VS Code were the only editor that people use regularly that would make sense, but I'd like for our solution to be thoughtful and account for another editor (or different variable menu item) that extends in length as well.

**Comment by msftrncs** [comment]
Just to keep this in mind, the issue is that there are two 'Visual Studio Code' entries
- Visual Studio Code
- Visual Studio Code (Insiders)

and the menu gets clipped at 'Open in Visual Studio C...'

The other editors are probably not much of an issue, as they are generally unique in the first few characters.

**Comment by Rexogamer** [comment]
I’m thinking a tooltip would be sufficient.

**Comment by niik** [comment]
This should be fixed with #14930 which is currently on our beta channel ✨
