### ISSUE TITLE
Repositories not available in one machine

### ISSUE THREAD

**Issue by farheen-patel** [desktop/desktop#6273]
## Version

* GitHub Desktop:

* Operating system:

**Comment by farheen-patel** [comment]
I have configured GitHib Desktop on my laptop and desktop.
However, The GitHub Desktop I have installed on my desktop doesn't show the repositories that I have uploaded using Github web application.

**Comment by shiftkey** [comment]
@farheen-patel please fill out the original issue template to provide more details about your setup

> However, The GitHub Desktop I have installed on my desktop doesn't show the repositories that I have uploaded using Github web application.

Are you able to share some screenshots of where the differences? It's not clear to me where in the UI this is relevant to, as two places come to mind:

 - the "Clone Repository" dialog that's accessible from the File menu
    - this is repositories that you can access from your account, and may clone to your machine
 - the list that's accessible from the top-left repository switcher
    - this is only repositories that you have cloned to your current machine, or added from local folders

**Comment by bangke213** [comment]
it's clear what this data means

**Comment by tierninho** [comment]
@farheen-patel As we have not heard anything back from you, we are closing this issue for now. Please reach out if you need further help and we'd be happy to reopen the issue. Thanks!
