### ISSUE TITLE
A lock file already exists in the repository, which blocks this operation from completing.

### ISSUE THREAD

**Issue by ceu** [desktop/desktop#6274]
i have this error, in version 1.5.0

**Comment by ceu** [comment]
[2018-11-23.desktop.production.log](https://github.com/desktop/desktop/files/2609824/2018-11-23.desktop.production.log)

**Comment by ceu** [comment]
when i commit, have this error

**Comment by ceu** [comment]
i resolve this  error through delete   index.lock    /Users/boolean/Desktop/web-oa/.git/index.lock

**Comment by AmirKhan47** [comment]
index.lock in located in the directory where u have the project for me it is htdocs/.git/index.lock

**Comment by pmcommu** [comment]
> index.lock in located in the directory where u have the project for me it is htdocs/.git/index.lock

This is the simplest answer. (y)

**Comment by gonzalochief** [comment]
Just a small footnote. Close GitHub desktop before deleting the index.lock file

**Comment by JAckZ97** [comment]
have to close all Github related first then delete the index.lock. WORKS!!!

**Comment by spec-alt** [comment]
> have to close all Github related first then delete the index.lock. WORKS!!!

still worked without closing it

**Comment by superflashilandia** [comment]
> index.lock in located in the directory where u have the project for me it is htdocs/.git/index.lock

Thank you!!! Problem solved.

**Comment by emin2045** [comment]
Thank you so much, it is really works.
