### ISSUE TITLE
Github desktop not able to clone new project from azure repo

### ISSUE THREAD

**Issue by mr-sam** [desktop/desktop#6275]
Hi,
I am trying to clone new project from azure repo with github desktop app but keeps showing me authentication screen even though i am putting correct credentials when i try same steps with other cloning apps it works fine.

**Comment by billygriffin** [comment]
@mr-sam Please let us know if that solves it or doesn’t when you get a chance. 😄

**Comment by mr-sam** [comment]
@shiftkey i tried but still getting same authentication window after putting right credentials. FYI have tried with both primary and secondary username.

**Comment by billygriffin** [comment]
@mr-sam Would you mind adding the information from the [template](https://github.com/desktop/desktop/issues/new?template=bug_report.md) to your original issue above so we can understand what your environment is, what's happening, and hopefully take a look at the log files?

**Comment by mr-sam** [comment]
I can say one of the issue can be that it is not working with new azure repo accounts as i noticed.
Here is link to my repo
https://mg-demos@dev.azure.com/mg-demos/mg-azurefunctions/_git/mg-azurefunctions
I am attaching screenshot of authentication window and have underlined link it is showing to my repo which is wrong. I think that is issue if you can help me with that will be great help. Thank you


![error](https://user-images.githubusercontent.com/6789966/49079811-a9419180-f267-11e8-8922-b3df0d409711.png)

**Comment by steveward** [comment]
@mr-sam I was able to reproduce this issue in my Azure DevOps account. I'm looking into what the issue may be. I was able to successfully authenticate by generating a personal access token, which can be done from `Security` > `Personal Access Tokens` under your Azure DevOps account.

**Comment by steveward** [comment]
Microsoft now [recommends](https://docs.microsoft.com/en-us/azure/devops/repos/git/auth-overview?view=vsts) using personal access tokens instead of basic authentication. I've tested that flow  out a few times with my Azure DevOps account and confirmed it works without issue, so I'll work on getting a PR out to update our existing documentation about this.

**Comment by lgmorand** [comment]
with the right link to the documentation for people looking for the information
https://github.com/desktop/desktop/blob/development/docs/integrations/azure-devops.md

**Comment by philipesantos136** [comment]
Awesome, works for me. Thank's!

**Comment by pithakoteTata** [comment]
> 
> 
> with the right link to the documentation for people looking for the information
> https://github.com/desktop/desktop/blob/development/docs/integrations/azure-devops.md

Thanks. Exactly what  needed

**Comment by anuragbohra** [comment]
Hello
I am getting the attached error and also not allowing me to enter username and password.

![Error](https://user-images.githubusercontent.com/66743824/84406976-dd9d5880-ac27-11ea-8bd8-8ce60b0e527f.PNG)

Please advise.

Thanks

**Comment by anuragbohra** [comment]
I just replaced the username, project_name and the repository and got the aforesaid error.

https://<username>@dev.azure.com/<username>/<project_name>/_git/<repository_name>

**Comment by anuragbohra** [comment]
Hello

I am getting the attached error while trying to clone Azure DevOps repository in GitHub Desktop. 

I followed all the steps mentioned in below dcomentation https://github.com/desktop/desktop/blob/development/docs/integrations/azure-devops.md

![Error1](https://user-images.githubusercontent.com/66743824/84408386-afb91380-ac29-11ea-8f4b-1051e2cefe6d.PNG)

Please advise.

**Comment by mossywell** [comment]
Instructions are wrong:
https://<username>@dev.azure.com/<username>/<project_name>/_git/<repository_name>

Should read:
https://dev.azure.com/<organization_name>/<project_name>/_git/<repository_name>
