### ISSUE TITLE
There is no any option to clean the cached file

### ISSUE THREAD

**Issue by Krprashant94** [desktop/desktop#6280]
**There is no any option to clean the cached file i.e. in ".git" folder ?**

I am using GitHub desktop for a long time and now I have too much cache in my local folder I want to clean it but there is no any option available in GitHub desktop to clean these cached files.

> I am want to clarify my problem again the size *"myproject/.git"* folder in my local disk to 10 time more than my original project; so i need to clean this. please add a menu entry to clean these cached files.

**Comment by j-f1** [comment]
The .git directory stores the project’s history. Is that what you want to remove?

**Comment by Krprashant94** [comment]
I want to delete some of the history and "git rm -r --cached"

**Comment by shiftkey** [comment]
@Krprashant94 the `.git` directory contains the entire local history of your repository, which is why it's significantly larger than the working directory. If you tamper with the `.git` folder contents by removing contents you risk corrupting your repository.
