### ISSUE TITLE
Successful merge banner appears when a merge doesn't actually happen

### ISSUE THREAD

**Issue by agisilaos** [desktop/desktop#6282]
## Description
Successful merge banner appears when clicking Update from master and it doesn't take into account if an actual merge occurs. 

## Version
* GitHub Desktop: 1.5.1-beta0
* Operating system: 10.14.1 (18B75) - Mojave

## Steps to Reproduce
1. Find a branch that is up to date with master
2. Click `update from master` from branch menu
3. Observe that the banner appears even though a merge didn't occur

### Expected Behavior
- The banner shouldn't appear when a merge don't actually happens

### Actual Behavior
- The banner appears either way

## Additional Information
![merge_banner_appears_in_the_wrong_time](https://user-images.githubusercontent.com/10944108/48968284-e4d52500-eff5-11e8-9c81-f3693e61d313.gif)

**Comment by tierninho** [comment]
Alternatively, we could grey out the menu option if there is no update to be made...

**Comment by outofambit** [comment]
The underlying problem here is that the command `git merge` returns a success exit code even when a merge is a no-op. 😿

```shellsession
$ git s
On branch newborn
nothing to commit, working tree clean
$ git merge master
Already up to date.
$ echo $?
0 
```

I think the right best solution here is to parse the merge stdout to see if the merge was a no-op when the exit code is `0`.

**Comment by tierninho** [comment]
I noticed there is no messaging when the user selects this menu option, and a merge is *not* expected. Should we letting the user no the merge did not occur? No response keeps me guessing...

**Comment by outofambit** [comment]
hmm @tierninho that's a good point! i think we should surface some feedback that this is a no-op. a already up to date banner could work (without the green check). or perhaps we should disable the menu item for "update from defaultBranch" when you're already up to date? @billygriffin

**Comment by billygriffin** [comment]
I'm open to something conveying already up to date, but I'd love to hear from @desktop/design on how to do so if we think conveying that information is the right choice.

**Comment by ampinsk** [comment]
I think an "Already up to date" message would be nice to see!

**Comment by billygriffin** [comment]
@ampinsk Any opinion on how that should manifest? That's where I was getting a bit hung up. Is it in the same banner area and disappears like the "Success" message? Does it use some other pattern?

**Comment by ampinsk** [comment]
Ooh I was thinking in the same banner area and it would disappear. Keeping the check would possibly still make sense as well.

**Comment by billygriffin** [comment]
Moving this to 1.6.1 as it didn't make it into the beta today. I'm 👍 on @ampinsk's suggestion.

Based on what we've said, here's a proposal:

It says "This branch is already up to date with {default branch name}." It has a green check to the left of it in the same way as the success banner does.

And it dismisses in the same time period as a success banner does.

I'm going to reopen this and move to pri-3 because the main confusion has been addressed.

**Comment by niik** [comment]
> It says "This branch is already up to date with {default branch name}." It has a green check to the left of it in the same way as the success banner does.

This was fixed in https://github.com/desktop/desktop/pull/10453

**Comment by outofambit** [comment]
thanks @niik !! 💟
