### ISSUE TITLE
Trojan (most likely a false positive by Yandex)

### ISSUE THREAD

**Issue by petrovnn** [desktop/desktop#6283]
https://www.virustotal.com/#/file/bbab9098b4422288c6ce42e92fc12be85e8c79757ce5c676856b6401a24dd5b3/detection 
![image](https://user-images.githubusercontent.com/1567284/48976247-22d55600-f095-11e8-8f10-78ad93502cbc.png)

**Comment by shiftkey** [comment]
@petrovnn thanks for the report.

These occasional false positives are hard to resolve without reaching out to the anti-virus companies to get more details, and I couldn't find a support channel for Yandex after a quick skim of their support resources.
