### ISSUE TITLE
Branch Menu is disabled entirely after a Merge Action

### ISSUE THREAD

**Issue by GokulManickam** [desktop/desktop#6285]
In the latest update, though the UI has a few modifications for the good, after I complete a merge into a branch and switch branches, the Branch Menu is disabled entirely.

Due to this, I am unable to perform any action whilst being active in a particular branch once I complete a merge into another branch and move to the former.

**Comment by tierninho** [comment]
@GokulManickam Note, the branch menu will be disabled if a modal or dialogue is currently showing. 

As we haven't heard back from you, please reach out if you need further help and we will be happy to reopen the issue. Thank you!
