### ISSUE TITLE
Too many details shown in commit flow

### ISSUE THREAD

**Issue by jancborchardt** [desktop/desktop#6286]
**Problem:** Currently in the commit flow on the bottom left, all elements are shown at all times:
![commit description](https://user-images.githubusercontent.com/925062/49003983-81690580-f163-11e8-9c8b-f853369c0624.png)
Especially the "Description" field takes attention which is not proportional to its value. The essentials are the required summary field and the commit button. Often when I show git to beginners, they start typing their commit messages into the "Description" field, or don’t see the "(required)" info for the Summary as it’s just one of many things taking attention.

**Potential solution:** The detail Description field including the "Add co-authors" icon could be hidden by default. Instead a button "Add details" would be shown next to the commit button:
![github desktop commit add details button](https://user-images.githubusercontent.com/925062/49003982-81690580-f163-11e8-98b9-50c93f98e001.png)
Pressing the "Add details" button would toggle show the textarea (ideally with quick animation from below).

So that this also works for people who regularly use description and co-authors, the toggle state of "Add details" should be remembered.

**Comment by billygriffin** [comment]
Hi @jancborchardt, thanks for the suggestion! We discussed this internally, and I'm not sure I agree with your premise that it's more confusing in the current state than it would be in a new state with the description hidden. Consistency of expectation is helpful in making it discoverable (and teachable), and we want to encourage explanatory commit messages where they're helpful. Additionally, we don't want to hide co-authoring by default as that's another collaborative behavior we want to encourage. I'm super interested in continuing to look for this in our interviews and usability tests with beginners though, and really appreciate you calling it out as a potential issue to look into. For now since we don't intend to immediately change anything, I'm going to close this, but again I really appreciate you taking the time to clearly explain your observations and suggest an alternative.

**Comment by j-f1** [comment]
How about this style?
```
😀 [Summary              ] 👤+

[Description                  ]

[       Commit to master      ]
```

The description box would expand when clicked like the review reply box on GitHub.

**Comment by jancborchardt** [comment]
@billygriffin yep, I understand. :) Probably hiding it completely is too much, maybe just collapsing it to one line by default (unless clicked) like @j-f1 suggests is better?

Because right now as a result I saw a lot of people who simply left the default summary (e.g. "Updated README.md") and then put what should be the actual commit message into the description, where it's not so visible in common log tools, or on Github.com neither.

**Comment by billygriffin** [comment]
@jancborchardt Oh that's really interesting. I'm going to be doing some new user usability tests, so this is something I'll look out for specifically and reopen if we see increased confusion. Especially if we're seeing it contribute to *worse* commit messages, that's definitely not something we want. 😄 Thanks again for the feedback.

**Comment by Daniel-McCarthy** [comment]
I also agree that it would be preferable to reduce the size of the description input box until clicked than to hide it entirely until a button is pressed.

As a user who makes use of the description quite a bit, it would be potentially discouraging to my habit to regularly have to un-hide the description box. However, having it shorter and expanding once clicked (or gains focus) feels like a good compromise. It would not be an inconvenience to me while potentially having a benefit to users who are drawn in by the scale of the description box.

**Comment by j-f1** [comment]
Here’s a quick fiddle with a mockup: https://jsfiddle.net/jed_fox/xjezpmfL/

**Comment by Daniel-McCarthy** [comment]
I think that would make a lot of sense. The mockup reacts exactly how I would expect.
- [x] Expands on click
- [x] Expands on focus from tabbing to the description box
- [x] Retracts when focus is lost and no text has been entered
- [x] Does not retract when text is contained

I think this behavior would work great and hopefully it can help users note the requirement of the summary and see that the description is not the primary form.

**Comment by jancborchardt** [comment]
Good stuff @j-f1! :) Thanks a lot for putting it in a fiddle!
