### ISSUE TITLE
Not Showing My Changes And Not discarding changes 

### ISSUE THREAD

**Issue by srikanth-padmanabhuni** [desktop/desktop#6287]
## Description

In my github desktop It is not showing any changes made in the files and if all the changes are discarded manually still  it is showing that file in "Changes tab"

Moreover discard all changes is not working.

## Version

* GitHub Desktop: 1.5.0

* Operating system: 10

## Steps to Reproduce

1. Changes made in File
2. Not showing any changes that are made
3. Discarded changes manually
4. Still showing that file in "changes" Tab
5. Discard all is not working'
6. Not switching branches
### Expected Behavior

Should show  changes made and should discard changes when we click on discard all
and should switch branches
### Actual Behavior

1. No changes are showing
2. Discard all is not working
3. Not switching branches
## Additional Information

Please fix as soon as possible

**Comment by billygriffin** [comment]
Ah @srikanth-padmanabhuni, that sounds exceptionally frustrating. Sorry you're running into so many problems. May I ask when this behavior started for you? Were you able to do these things successfully in Desktop in the past, and it just recently stopped working? Did it coincide with an update? I'm just trying to get a bit more information to help us diagnose, because there seem to be a bunch of things going wrong. If you have screenshots or a gif of the behaviors you're seeing, that would be helpful too.

@desktop/support Any ideas beyond the questions I asked?

**Comment by steveward** [comment]
@srikanth-padmanabhuni it would also be helpful if you could upload a log file from GitHub Desktop so we could see if there are any underlying issues.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue.

**Comment by tierninho** [comment]
This sounds familiar to https://github.com/desktop/desktop/issues/4194 but more info needed before we can make that call.

**Comment by srikanth-padmanabhuni** [comment]
[2018-11-24.desktop.production.log](https://github.com/desktop/desktop/files/2618338/2018-11-24.desktop.production.log)
[2018-11-26.desktop.production.log](https://github.com/desktop/desktop/files/2618339/2018-11-26.desktop.production.log)


I am facing this issue from 24-11-2018...
It stopped working suddenly and  due to this i did my work twice....!!!!
Please fix it as soon as possible

![image](https://user-images.githubusercontent.com/43059655/49058773-77123e80-f22b-11e8-9fd6-03875ac99ac1.png)

You can see i am in my working branch but  not showing the file that was changed!!!!

**Comment by tierninho** [comment]
@srikanth-padmanabhuni Sorry for the continued problems, but based on the log entries:

```
2018-11-24T05:41:10.674Z - info: [ui] No submodules found. Skipping "git submodule status"
2018-11-24T05:41:18.782Z - error: [ui] `git checkout-index -f -u -q --stdin -z` exited with an unexpected code: 128.
fatal: Unable to create 'E:/MAPIT-5B0/mapit/.git/index.lock': File exists.
```

this looks to be a known bug we are tracking in #4194 and #4592. Please follow along there.

cc @shiftkey who has been investigating the two known issues

**Comment by steveward** [comment]
@srikanth-padmanabhuni Do any of the files in the `Changes` list show the diff correctly, or are all of the files showing the `file is empty` message?

Could you also try diffing that file from the command line (`Repository` > `Open in <command line application>`)? Here's the command:

`git diff mapit-code-plagiarism\target\classes\caches\CacheStat.class`

Let me know what that returns.

**Comment by srikanth-padmanabhuni** [comment]
Every file is showing the same message empty....
Command prompt too not returned anything 

![image](https://user-images.githubusercontent.com/43059655/49129221-d8521480-f2f4-11e8-8c52-d5a2f6aad576.png)

**Comment by srikanth-padmanabhuni** [comment]
You can see that application.conf is in changes tab with yellow dot

![image](https://user-images.githubusercontent.com/43059655/49129467-f9673500-f2f5-11e8-9cf2-598360a08873.png)

**Comment by steveward** [comment]
@srikanth-padmanabhuni apologies, I mistyped the diff command:

`git diff HEAD mapit-code-plagiarism\target\classes\caches\CacheStat.class`

**Comment by srikanth-padmanabhuni** [comment]
No Not showing anything. Same result Empty!!!!!

![image](https://user-images.githubusercontent.com/43059655/49199737-89bd7c80-f3bf-11e8-8065-761f424c0c97.png)

**Comment by steveward** [comment]
@srikanth-padmanabhuni thanks for the update. I believe what you are running into is related to filemode changes, similar to https://github.com/desktop/desktop/issues/4953.

Does running the command `git status --untracked-files=all --branch --porcelain=2` show any output?

You can also force Git to ignore filemode changes by running the following command:

`git config core.filemode false`

Let me know if it helps.

**Comment by srikanth-padmanabhuni** [comment]
No Not helpful

**Comment by srikanth-padmanabhuni** [comment]
No this problem is there only recently ... before that it works fine.

And I wont zip u the repository it is confidential...

**Comment by steveward** [comment]
@srikanth-padmanabhuni could you try performing a fresh clone of the repository to a different location on your machine to see if you are able to reproduce the same issues again? That would help narrow down if this is a configuration problem or something specific to your local repository.

Could you also check if the file `E:/MAPIT-5B0/mapit/.git/index.lock` exists in your repository?

**Comment by steveward** [comment]
@srikanth-padmanabhuni if a newly cloned repository is showing all of those files as changed right after you perform the initial clone then this definitely points to the problem being a file mode or line endings issue. 

Is this repository being worked on in other non-Windows operating systems? 

Here's what you can try to verify whether or not this is a file mode issue:

1. Run the command `git config --global core.filemode false` to tell Git to globally ignore filemode changes
2. Perform a fresh clone of the repository and see if you still see all of the uncommitted changes appear

**Comment by steveward** [comment]
@srikanth-padmanabhuni As we have not heard back from you about this issue we are going to close it out. If you have any more details or questions please don't hesitate to reach out -- we would be happy to help. Thanks!
