### ISSUE TITLE
I get error cannot spawn ask-pass-trampoline.bat: No error fatal: could not read Username for 'https://github.com': terminal prompts disabled

### ISSUE THREAD

**Issue by Dpremkumar** [desktop/desktop#6288]
**Please describe the problem you think should be solved**
A clear and concise description of what the problem is and who else might be impacted. Screenshots are encouraged.

Example:

> “When I run into a merge conflict, I don’t know where to go to resolve it. Anyone who works off of multiple branches will likely run into this problem at least occasionally.”

**[Optional] Do you have any potential solutions in mind?**
A clear and concise description of one or more solutions you think might solve the problem. Please include any considered drawbacks or tradeoffs, and how users might use your solution(s). Screenshots or mockups are helpful here!

**Comment by steveward** [comment]
Thanks for the report @Dpremkumar. This looks like a similar issue to https://github.com/desktop/desktop/issues/2623.

Do you happen to be behind a proxy server or firewall? Are you possibly running any antivirus software on your computer that could be flagging the binaries that GitHub Desktop ships with?

It would also be helpful if you could upload a log file from GitHub Desktop.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue.

**Comment by billygriffin** [comment]
Thank you for your issue @Dpremkumar!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by EWouters** [comment]
I have this issue as well after I enabled two-factor authentication.

**Comment by billygriffin** [comment]
@EWouters Please feel free to open a new bug report issue, as we need to have more information from the template in order to understand what might be going on. Thank you!
