### ISSUE TITLE
'revert this commit' in branch compare 'behind' list context menu

### ISSUE THREAD

**Issue by msftrncs** [desktop/desktop#6293]
## Description
The context menu item 'Revert this commit' appears for items in the 'Behind' list of commits when comparing branches.  This seems wrong, to be allowing an action against a branch that is not currently checked out, but I suppose GIT doesn't care.  Instead I think this is a perfect place for 'Cherry-pick this commit', ala #1685, or 'Merge just this commit'. (okay, getting ahead of myself)

## Version
* GitHub Desktop: 1.5.0
* Operating system:  Win 10 1809

## Steps to Reproduce
1. Check-out a branch in a repository
1. Select a branch to compare to in the repository/branch history bar, that has 'Behind' commits in relationship to the checked-out branch..
1. Insure you are looking at the list of 'Behind' commits.
1. Activate the context menu for one of the behind commits.

### Expected Behavior
I'd of expected that I would not receive a context menu item for 'Revert this commit', only because reverting a 'behind' commit would only make the current branch further behind and the changes would be affecting a different branch than the current, so this just seems like untypical work flow.

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to bring this issue to our attention, @msftrncs 👍

**Comment by iAmWillShepherd** [comment]
I think at the very least, we should remove that option from the context menu since it results in this error
<img width="1072" alt="screen shot 2018-11-27 at 11 10 39 am" src="https://user-images.githubusercontent.com/1715082/49098697-1e47a380-f235-11e8-8336-92ec1a83b1a9.png">

**Comment by msftrncs** [comment]
I got a slightly different and unexpected error message.

![image](https://user-images.githubusercontent.com/26179051/49107452-62de3980-f24b-11e8-861b-2aaf03095753.png)

(I need to use a smaller window) 'There are no changes to commit.'

**Comment by iAmWillShepherd** [comment]
Fixed in https://github.com/desktop/desktop/pull/6300
