### ISSUE TITLE
Unable to push commit then removed multiple files

### ISSUE THREAD

**Issue by Uglyuck** [desktop/desktop#6301]
## Description

So I was unable to push multiple commits for a long time then I heard I could clear out the commits without modifying the files.  (which I had TONS of work on there.) And it seemed to work when I first did it. Then somehow while Commiting in batches it didn't push all of the files. and after finishing all of my pushes and it being ready I came back to it a couple weeks later and MANY files were gone. I have a metadata of one of the files, but the actual file and files are gone. Trying to figure out what happened and how to recover. It seems all reverts seem to revert it to a much farther back prior state. 

## Version

* GitHub Desktop:

* Operating system:

**Comment by billygriffin** [comment]
Hi @Uglyuck, thanks for the report. Would you mind filling out the rest of the template to help us better understand what's going on? It's not super clear to me what happened here so a bit more information (including detailed reproduction steps with screenshots if you can reproduce) would be really helpful. The logs can sometimes also help us identify errors that might've occurred. You can find them in `Help -> Show Logs in Finder/Explorer` and include them in this issue. Thanks!

**Comment by billygriffin** [comment]
Thank you for your issue @Uglyuck!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
