### ISSUE TITLE
Merge Conflict Popup Spam

### ISSUE THREAD

**Issue by jeremywestdev** [desktop/desktop#6311]
**Please describe the problem you think should be solved**

Merge conflicts now have pop-up spam prompting me to resolve or open in git bash or editor when all I need is access to the window in order to discard changes for compiled vue.js files or see the file names that still have conflicts.

Example:

I work with Vue.js which means the compiled files in the main branch will almost always have merge conflicts, but there is never a reason to edit or address those merge conflicts. I recompile after i commit the merge so that there's a clear compile commit. With the previous version I was able to just discard the changes on the compiled files, then manually look at which files had remaining conflicts and go open them in vscode (i could never get any of the "open in editor" prompts from github desktop to work).

**There used to be** one pop-up noting there was merge conflicts and it would warn me if i tried to commit with conflicts and that was ok. I would discard changes to compiled files, then go open and resolve remaining conflicts in vscode.

**But now** the "resolve conflicts before merging" popup shows up if i click the window, if i "open in the command line to resolve" i can get it to go away so i can quickly try to discard changes but clicking the main window makes the popup return. There is a prompt to open in an external editor but honestly I dont need github desktop that hard wired into my process. 

**[Optional] Do you have any potential solutions in mind?**

An option in the Options>>Advanced tab to enable the old method of prompting giving more control back to how conflicts are resolved to the user. 

Or an "X" on the "resolve conflicts window preventing any further popups until files change.

**Comment by billygriffin** [comment]
Hi @jeremywestdev, thanks for the feedback. Please follow along in #6213 as we're iterating on the experience you describe there, and it sounds like where we're heading next is basically your second suggestion.
