### ISSUE TITLE
Choose button in Add Repository Workflow allows multiple finder windows to be opened

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#6314]
## Description
When adding a new repository, clicking the _Choose..._ button **n** times while a Finder window is open causes **n** new Finder windows to open after making a selection.

## Version
* GitHub Desktop: 1.5.1-beta0
* Operating system: macOS and reproduced on Windows 10

## Steps to Reproduce
1. Enter the _Add Local Repository..._ workflow
1. Click _Choose..._
1. Move Finder window out the way so you can click _Choose..._ **n** more times
1. Select the repo you'd like to open and click _Open_ 

### Expected Behavior
Once selection is made, no more Finder windows appear. Ideally, the button will be disabled or result in a no-op when clicked while Finder window is open.

### Actual Behavior
**n** Finder windows will appear after clicking _Open_

## Additional Information
![2018-11-29 16 53 29](https://user-images.githubusercontent.com/1715082/49257826-16d0f780-f3f9-11e8-87c2-ea4127471edb.gif)

**Comment by tierninho** [comment]
Might be a separate issue, but if you:

- Select the repo in the finder, click Open
- Go back to Desktop
- Oops, you selected the wrong repo, so you go back to the Finder and select another repo
- Click Open
- The Desktop selector modal (cmd-O) automatically closes and the repo is lost

**Comment by iAmWillShepherd** [comment]
This is no longer an issue now that https://github.com/desktop/desktop/pull/7708 has been merged.
