### ISSUE TITLE
Close merge conflicts modal

### ISSUE THREAD

**Issue by notiv-nt** [desktop/desktop#6317]
**Please describe the problem you think should be solved**
Cannot close this modal

**[Optional] Do you have any potential solutions in mind?**
This modal must be closed without merging. I have to see which files are changed.

![image](https://user-images.githubusercontent.com/10743009/49288379-a0440080-f4b1-11e8-9f73-229b572f5988.png)

**Comment by ddowling-act** [comment]
+1 Previously I could see which files had conflicts, open the file path of the project and fix them in tortoiseGit (as its merge tool seems to cope much better with whitespace changes than the built in one)
Now I cannot get to the open project folder button (or any buttons) while mid merge.
Was the intent to stop commits of incomplete merges? Maybe better to bring up this modal when you try to commit an incomplete merge, but allow the user to close it here.

**Comment by ddowling-act** [comment]
Though I think (given a bit of issue searching) this issue is being tracked here: https://github.com/desktop/desktop/issues/6213

**Comment by billygriffin** [comment]
Thanks @notiv-nt and @ddowling-act! We're tracking this in #6213 and are currently iterating on it. Really appreciate you weighing in as well. I'm going to close this so we can track this work in one place, and thanks again.
