### ISSUE TITLE
Failure to clone to an SSL server: exit code 128

### ISSUE THREAD

**Issue by lyiriyah** [desktop/desktop#6318]
OS: Windows 10 build 10240
What should happen: clones repo lyiriyah/theta
What actually happens: failure with exit code 128 with error `fatal: unable to access 'https://github.com/lyiriyah/theta.git/': Failed to connect to github.com port 443: Connection refused`.
To reciprocate steps:

1.  Clone a repo

**Comment by lyiriyah** [comment]
@tierninho any thoughts? opened a new issue instead of continuing #2838.

**Comment by billygriffin** [comment]
@lyiriyah If what @steveward suggests above doesn't solve the issue, would you mind filling out the rest of the information requested in the bug report template please so we have more information to properly diagnose? https://github.com/desktop/desktop/issues/new?template=bug_report.md

**Comment by billygriffin** [comment]
Thank you for your issue @lyiriyah!

We haven't gotten a response to our questions in our comments above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this - hopefully @steveward's guidance solves it! - but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by lyiriyah** [comment]
yes i am on an ssl server, i'll run that cmd, thanks @steveward
