### ISSUE TITLE
Auto-fill commit message

### ISSUE THREAD

**Issue by maroun-baydoun** [desktop/desktop#6319]
**Please describe the problem you think should be solved**
When making a commit, I would like to have the ability to select a previous commit to autofill the current message. 

When committing using a ticket number in the commit message, it would make it more convenient if the previous commit message can be used and then edited to keep the ticket number for example and change the description

**Comment by billygriffin** [comment]
Hi @maroun-baydoun, thanks for the idea! This is something we've heard one before in #4129, but we decided that it may not be a broad enough use case to support in the app. It's definitely interesting to have heard it once more from you so we'll keep an eye out for others who may have the same problem, and if we're seeing it as more common than we assumed, we're absolutely willing to look further into it and explore solutions. For now though, we don't intend to support this feature. Thank you so much for bringing it to our attention, and we hope you'll continue to weigh in in the repo!

**Comment by ureiss-com** [comment]
Hi, I'm a new user of Github Desktop and just searched the web for the exact feature described here. You wrote:

> and if we're seeing it as more common than we assumed, we're absolutely willing to look further into it and explore solutions.


So I would like to let you know that there are more users out there who would be interested in being able to easily copy the latest commit messages into the message field, e.g. with the arrow up button or via a selection popup. It would be very very helpful!

I have in mind the summary field, not the description.
