### ISSUE TITLE
Cloning failed- fatal: cannot create directory - Invalid argument

### ISSUE THREAD

**Issue by Diyago** [desktop/desktop#6323]
## Description
Tried to clone this repository https://github.com/Diyago/ML-DL-scripts but failed with fatal: cannot create directory - Invalid argument
Other repository successful cloned . I believe the problem related with wrong long file/folder names

## Version

* GitHub Desktop: 1.5.0 (the last version)

* Operating system: Windows 10

## Steps to Reproduce

1. Clone https://github.com/Diyago/ML-DL-scripts
2. ???
3. Get fatal: cannot create directory - Invalid argument
### Expected Behavior

To clone the repository
### Actual Behavior

fatal: cannot create directory - Invalid argument. 

### Logs

Cloning into 'C:\Users\Insaf.Ashrapov\Desktop\ml\ML-DL-scripts'...
remote: Enumerating objects: 10, done.        
remote: Counting objects:  10% (1/10)           
.... 
remote: Counting objects: 100% (10/10)           
remote: Counting objects: 100% (10/10), done.        
remote: Compressing objects:  11% (1/9)           
...  
remote: Compressing objects: 100% (9/9)           
remote: Compressing objects: 100% (9/9), done.        
Receiving objects:   0% (1/811)   
Receiving objects:   1% (9/811)   
..
Receiving objects:  15% (122/811)   
Receiving objects:  15% (125/811), 332.01 KiB | 321.00 KiB/s   
...
Receiving objects:  99% (803/811), 88.37 MiB | 6.70 MiB/s   
Receiving objects: 100% (811/811), 88.37 MiB | 6.70 MiB/s   
Receiving objects: 100% (811/811), 89.17 MiB | 5.03 MiB/s, done.
Resolving deltas:   0% (0/289)   
Resolving deltas:   5% (16/289)   
...
Resolving deltas:  98% (286/289)   
Resolving deltas: 100% (289/289)   
Resolving deltas: 100% (289/289), done.
fatal: cannot create directory at 'DEEP LEARNING/Kaggle: Avito Demand Prediction Challenge (bronze solution)': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by steveward** [comment]
Thanks for the report @Diyago.

It looks like there are parentheses in the `DEEP LEARNING/Kaggle: Avito Demand Prediction Challenge (bronze solution)` directory name, which is why the clone is failing. Parentheses are [reserved characters](
http://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions) on Windows operating systems. 

Do you have access to a Linux or macOS system where you could rename this directory? You could also install the [Linux Subsystem for Windows](https://docs.microsoft.com/en-us/windows/wsl/install-win10) to clone the repository and then rename the directory. Once you remove those parentheses from the directory name and push that change back up to GitHub you should be able to clone this repository without issue on Windows.

**Comment by Diyago** [comment]
Yep, you were right. Deleting  `/:`   fixed the problem. Poorly that it can't be done in web version

**Comment by RadicalchAngel** [comment]
Thanks for letting me know (^^)(+_+:-$

**Comment by wengm** [comment]
This happened one my environment, even the path has no colon:

fatal: cannot create directory at '**src/main/java/com/e/m/test/cat/i/helpers/con**': Invalid argument

Bruce

**Comment by shiftkey** [comment]
@wengm please open a new [bug report](https://github.com/desktop/desktop/blob/development/.github/ISSUE_TEMPLATE/bug_report.md) and fill out the issue template so that we're better able to help you.

**Comment by e-g1gor** [comment]
> This happened one my environment, even the path has no colon:
> 
> fatal: cannot create directory at '**src/main/java/com/e/m/test/cat/i/helpers/con**': Invalid argument
> 
> Bruce

There's forbidden file names in windows, [check this out](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions) 

> Do not use the following reserved names for the name of a file: CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended. For more information, see Namespaces.

**Comment by Enzodtz** [comment]
Another alternative is that you can actually download it zipped, and then rename it inside the program like winrar or 7zip...
