### ISSUE TITLE
Path issues

### ISSUE THREAD

**Issue by LiftPizzas** [desktop/desktop#6326]
Before getting GitHub Desktop, I had a project on my PC that I published to github. It was in:
C:\Users\abc\Source\Repos

If I tell GHD this exists, it will find it ok but not let me push, demanding I create a pull request first. The only way I found to get it to recognize was to clone it. This placed the whole project in a completely different location on my HDD (C:\Users\abc\Documents\GitHub)

When I opened this cloned project file in Visual Studio and worked for a while on it, it only updated the files in C:\Users\abc\Source\Repos because the pointers to those files are in the project itself. So it basically spread this stuff all over my hard drive and then GHD couldn't find the changes when I went to upload the latest build because they were in the "Source" folder and not where GHD had placed them. I had to go back and manually merge all my files back where they belong.

**Comment by msftrncs** [comment]
@LiftPizzas, can you provide some more details?  (as far as you publicly can)

- public or private repository?
- Output of `git remote -v`
- Is the message asking you to 'make a pull request' or 'pull changes first'.
- value of the repository's remote URL as shown in GHD's repository settings?  (should match one of the output's from `git remote -v`, usually 'origin')

This might help the devs figure out what is going on.

**Comment by tierninho** [comment]
@LiftPizzas As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you!
