### ISSUE TITLE
History log commit for specific file [blame]?

### ISSUE THREAD

**Issue by djmisterjon** [desktop/desktop#6327]
Hi, i can not find a way to check all commit for a specific file?
There is a way to view all the changes made for a single file?

Example here , i want see all commit log change for the file **core_players.js**

![image](https://user-images.githubusercontent.com/24865815/49341341-1f544880-f61a-11e8-9478-b8a1fdb7c494.png)

thank for help

**Comment by djmisterjon** [comment]
after more research , i search a buton or command in github desktop name `blame` ?
https://help.github.com/articles/tracking-changes-in-a-file/
How i can perform this with the software ?

**Comment by djmisterjon** [comment]
also link https://github.com/desktop/desktop/issues/2310

**Comment by billygriffin** [comment]
@djmisterjon Thanks for the issue and idea! Please reference my recent response in #2310 that you linked above: https://github.com/desktop/desktop/issues/2310#issuecomment-442611944

So I'm going to close this as well, but I'd love to hear what specifically you'd like to be able to accomplish with this. So when you're highlighting `core_Players.js` and wanting a blame, what are you using that information for and how will it be useful to you? Thanks so much! 😄
