### ISSUE TITLE
Update.exe has failed

### ISSUE THREAD

**Issue by littlekreen** [desktop/desktop#6331]
## Description

Attempting to update github desktop on existing install fails. After uninstalling git and github desktop the installation also fails after update.exe throws an error. 

Faulting application name: Update.exe_Update, version: 1.5.2.0, time stamp: 0x58893ce7
Faulting module name: KERNELBASE.dll, version: 6.1.7601.19160, time stamp: 0x56bcd5c3
Exception code: 0xc06d007e
Fault offset: 0x0000c52f
Faulting process id: 0x2008
Faulting application start time: 0x01d48ad0f326afa8
Faulting application path: C:\Users\LilKreen\AppData\Local\SquirrelTemp\Update.exe
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll

[this bug ](https://github.com/headsetapp/headset-electron/issues/129) from an app with a similar toolchain may be a similar issue. see #5197

## Version

* GitHub Desktop: not installed.

* Operating system: Windows 7

## Steps to Reproduce

1. Run installer
2. Wait for error

### Expected Behavior

Begin installation

### Actual Behavior

Installation crashes out.

## Additional Information

All existing github directories have been purged. Temp folders cleaned.

### Logs

Squirrel installation log is completely empty.

**Comment by billygriffin** [comment]
Sorry you're having issues installing @littlekreen. @desktop/support Have you seen this before, or have any ideas if not?

**Comment by steveward** [comment]
@littlekreen have you tried running `sfc /scannow` in an elevated command prompt to verify there are no issues with your installation of Windows 7? That would be the first thing I would recommend trying if you have not already attempted that. That command will scan your system files for any issues and attempt to fix them.

**Comment by tierninho** [comment]
@littlekreen As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you!
