### ISSUE TITLE
Creating a branch from a commit / detached HEAD has an unexpected recent history

### ISSUE THREAD

**Issue by donokuda** [desktop/desktop#6335]
## Description
When I create a branch from a "detached HEAD" state (such as from a commit), the branch is created with a different history (my assumption is that it's `master` or the default branch)

## Version

* GitHub Desktop: 1.5.0

* Operating system: macOS 10.13.6

## Steps to Reproduce

1. Check out a commit in terminal (I did `git checkout a813cc1` as an example) and switch to Desktop
![image](https://user-images.githubusercontent.com/1174461/49398793-467f4880-f6f4-11e8-8cba-5af9afae0611.png)
1. In Desktop, create a new branch. Desktop should warn you that the new branch will be based off of the currently checked out commit.
![image](https://user-images.githubusercontent.com/1174461/49398916-978f3c80-f6f4-11e8-93b1-4e437d90776e.png)
1. After creating a new branch, look at the history.

### Expected Behavior

I'd expect the latest commit to be the one that I checked out (I did `git reset --hard a813cc1` to simulate this in the UI):
![image](https://user-images.githubusercontent.com/1174461/49398963-c7d6db00-f6f4-11e8-959b-227f117eb604.png)

### Actual Behavior
The latest commit in the branch is more recent than the one I originally checked out:
![image](https://user-images.githubusercontent.com/1174461/49398941-b1c91a80-f6f4-11e8-9aba-0805be195729.png)

**Comment by billygriffin** [comment]
Thanks @donokuda!

> In Desktop, create a new branch. Desktop should warn you that the new branch will be based off of the currently checked out commit.

Clarifying question on step 2. Is that the actual behavior or the behavior you think should happen?

On the final "actual behavior," is the commit that was actually the most recent the one that's the latest on master? Just trying to understand specifically what's happening instead of what should happen.

**Comment by donokuda** [comment]
Oops! I was vague on purpose because I didn't want to assume what was happening. 😅 

> Clarifying question on step 2. Is that the actual behavior or the behavior you think should happen?

This is the actual behavior.

> On the final "actual behavior," is the commit that was actually the most recent the one that's the latest on master? Just trying to understand specifically what's happening instead of what should happen.

I believe that's the latest on master.

**Comment by tierninho** [comment]
So I followed the steps and my outcome was the same as your Expected result (ie, branch is 8 days old, and so is last commit). If I switched branches back to `master`, the latest commits were shown.

I did not use `git reset --hard a813cc1` as I already arrived at the Expected result.

**Comment by donokuda** [comment]
I just realized that I didn't include the initial history in the first screenshot, which probably doesn't help troubleshooting.

Here's a gif reproducing the issue that I'm running into:

![kapture 2018-12-12 at 13 29 36](https://user-images.githubusercontent.com/1174461/49900013-39f4a180-fe12-11e8-8bfc-51feb9d40d4b.gif)

**Comment by sergiou87** [comment]
Can't reproduce this anymore 🎉
