### ISSUE TITLE
All conflicts resolved but still cannot commit

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#6342]
From @msftrncs in #6213 (edited to clarify what the bug is):

## Description
I've resolved all conflicts but it still says "2 conflicted files" and won't let me commit. (NOTE: this is only on beta version. The current production version 1.5.0 does not exhibit this discrepancy.)

## Version
* GitHub Desktop: 1.5.1-beta0 (special note, Node 10)
* Operating system: Win 10 1809

## Steps to Reproduce
1. merge which produces conflicts
1. use editor to handle the conflicts, saving file when complete
1. repeat editing until all conflicted files are 'No conflicts remaining'.

### Expected Behavior
'Commit merge' button would become available.

### Actual Behavior
'Commit merge' button remains unavailable.

## Additional Information
My editor is VS Code, so in VS Code I can just 'stage changes' on the conflicted file, and then I can merge, but that workflow is not clear to me from the dialog, nor would it be available if I was using an editor without GIT integration.

This build is built on Node 10.

![image](https://user-images.githubusercontent.com/26179051/49425755-28513100-f764-11e8-8e65-e082518ad32e.png)

So the core issue would seem to be a lack of communication on the next step, or providing the tools for the next step, which is to stage the files so they are no longer marked conflicted so we can just press the 'Commit merge' button and move on.

However, Kudos to Desktop, VS Code would not let me commit with conflicted files, even though I did not want to merge the conflicted files. Desktop handled it fine.

**Comment by adamreisnz** [comment]
There's another issue related to the popup which shows conflicts. I'll report it here, but you may want to tackle it separately.

I noticed the popup told me that after a merge, I would have 10 conflicted files. However, this was incorrect. I only had 4 conflicted files, but in total there were 10 merge conflicts. So the wording needs to be updated.
