### ISSUE TITLE
Working directory changes committed unintentionally during merge conflict resolution

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#6349]
**Please describe the problem you think should be solved**

If I have changed files in my working directory prior to merging a different branch into mine (for example, updating my branch by merging in the latest from master) and I encounter merge conflicts, resolve the conflicts, and commit the merge, the files that were in my working directory will also be committed as part of the merge commit even though I likely did not intend for them to be.

This is likely confusing ("where did the stuff I was working on go?") and could be a disincentive to frequently staying up to date with the default branch, which we think is a good practice.

**Do you have any potential solutions in mind?**

My first inclination is that Desktop could ignore the working directory files during the merge and put them back after it's completed. I'm not sure what potential pitfalls exist with this.

Note: This was originally brought to my attention by @niik.

cc: @outofambit, @ampinsk, @nerdneha

**Comment by ampinsk** [comment]
I think that makes sense. Are there any workflows that would expect the working directory files to _not_ be ignored?

**Comment by billygriffin** [comment]
Moving this to 1.6.1 - #6464 should solve #6411 but doesn't get us all the way on this one.
