### ISSUE TITLE
Issue with cloning a private repository

### ISSUE THREAD

**Issue by JamesTwallin** [desktop/desktop#6362]
I have an issue with the clone a private repository:

AppData\Local\GitHubDesktop\app-1.5.0\resources\app\static\ask-pass-trampoline.bat: No error
fatal: could not read Username for 'https://github.com': terminal prompts disabled

[2018-12-07.desktop.production.log](https://github.com/desktop/desktop/files/2657086/2018-12-07.desktop.production.log)

![image](https://user-images.githubusercontent.com/44367431/49646117-14345a80-fa16-11e8-96fc-6c2ff8011a53.png)

**Comment by steveward** [comment]
Thanks for the report @JamesTwallin. We've had various reports of this issue in 
https://github.com/desktop/desktop/issues/4124.

Are you running any antivirus software that could be flagging the binaries that GitHub Desktop ships with? If you are, I would recommend trying to temporarily disable your antivirus software and then to try reinstalling GitHub Desktop again (reinstalling has also fixed this issue for other users). 

Let me know if that helps.

**Comment by JamesTwallin** [comment]
Hi Steve, 

Thanks for the reply - I tried what you mentioned but with no luck! :(

**Comment by steveward** [comment]
@JamesTwallin can you verify that the `ask-pass-trampoline.bat` file exists in that location? Are you able to share the specific antivirus/security software you are running on your machine?

**Comment by JamesTwallin** [comment]
@steveward yep it exists and the antivirus is 'Symantec Endpoint Protection'. I've tried turning off the firewall, uninstalling, reinstalling with no firewall on - no joy.

**Comment by steveward** [comment]
@JamesTwallin thanks for the update. Is the repository you are attempting to clone a GitHub Enterprise repository?

**Comment by JamesTwallin** [comment]
@steveward  - yes it is! Is this something easily fixed? Thanks, James

**Comment by steveward** [comment]
@JamesTwallin thanks -- that confirms that you are running into the same issue as https://github.com/desktop/desktop/issues/5082. We have not yet been able to reproduce this issue directly, but we are looking into it. I'm going to close this issue out in favor of #5082, but please follow along there for updates about a fix for this.
