### ISSUE TITLE
Shift + alt in summary move input-focus on mainmenu

### ISSUE THREAD

**Issue by higimo** [desktop/desktop#6366]
I suffer.

I switch keyboard layout with shift + alt

Pressing alt moves input-focus to the main menu.

When I write summary for commit, I often switch keyboard layout by shift + alt, after which input-focus moves to the main menu against my will. I write summary, but instead the screen flashes drop-down menus and something happens. Against my will. Always. This is bad. It causes suffering.

Possible solution: input-focus of the main menu via the keyboard should be made then and only then alt key was pressed. Any combination of the alt containing the input focus does not move input-focus.

**Comment by tierninho** [comment]
@higimo Thanks for filing this.

To clarify, you want `shift+alt` not to do this, as this action should be reserved only for `alt` :
<img width="330" alt="screen shot 2018-12-07 at 9 31 41 am" src="https://user-images.githubusercontent.com/14828183/49663362-3d97bb00-fa03-11e8-8fe5-7bacba5e24b3.png">

What should be the correct action if you use `shift+alt`? For example, if you cursor is in the Summary field and use `shift+alt`, what should happen?

**Comment by higimo** [comment]
> what should happen?

Anything in Github desktop. I switch keyboard layout. Just let it happen. As far as I know, `shift+alt` is not a keyboard shortcut inside Github desktop. Let nothing happen inside the program.

**Comment by tierninho** [comment]
> Let nothing happen inside the program.

Ok, we will discuss this proposal internally.

Windows:
`alt` = main menu focus (existing functionality)
`shift+alt` = take no action

**Comment by msftrncs** [comment]
A quick survey of windows apps (@higimo may not be on Windows, though ALT would limit to Windows and Linux right?) would make it appear that this could be difficult.  It seems it depends on which key was pressed first in the sequence, and then last.   If ALT is pressed first, then shift, the focus stays in the commit message input box regardless of how they are let up.  However, if SHIFT is pressed first, then ALT, ALT needs to be let up before the shift, else the ALT menu appears, moving the focus.  This happened in the main productivity apps (Explorer, Edge, Office) as well as in Desktop.

**Comment by higimo** [comment]
@msftrncs in Skype such error was reproduced earlier, and now everything is good. In Sublime Text this error is also not present. Probably, other IDE doesn't have this error either. I am sure that this mechanism can be cured.
