### ISSUE TITLE
List branch and/or path in list of repositories

### ISSUE THREAD

**Issue by jrmadsen** [desktop/desktop#6367]
On my filesystem, I commonly have 2-3 different clones of the repository. For example:

- `/home/user/myrepo-upstream` (upstream branch of fork)
- `/home/user/myrepo-master` (master branch of fork)
- `/home/user/myrepo-devel` (current developments)

I have various reasons for doing so, but the byproduct is that I commonly end up with multiple versions of "myrepo" in GitHub Desktop. The "issue" (more of an irritant) is that the drop down list of "Current Repository" provides no information about which path is being referenced, e.g.:

- `Current Repository`
    - `GitHub.com`
        - `myrepo`
        - `myrepo`
        - `myrepo`

is all that I see in the list. It seems like it would not be particularly difficult to add a "View" option that will insert the folder-name or branch name into the list, e.g.:

- `Current Repository`
    - `GitHub.com`
        - `myrepo [myrepo-upstream]`
        - `myrepo [myrepo-master]`
        - `myrepo [myrepo-devel]`

I haven't looked through the source code to gauge how difficult this might be to integrate but I suspect this would not be particularly difficult since GitHub Desktop obviously knows the path to the repository and it is just a simple string addition of the base folder name (or an iteration over of the display names checking for equality and then parsing the folder-paths for the shortest unique path)

**Comment by msftrncs** [comment]
@jrmadsen, does hovering the mouse over each entry not hint the path? 

![image](https://user-images.githubusercontent.com/26179051/49679034-13b7b600-fa4e-11e8-91a6-8b1976934d05.png)

**Comment by jrmadsen** [comment]
Ahh, excellent. I hadn't noticed that which kind of shocks me because I have been using it for a while. Not a Windows thing, I'm a mac. That works, I'll close this issue. Thanks.

**Comment by billygriffin** [comment]
@jrmadsen Thanks for the issue though! This is definitely in the realm of how users are more easily able to organize and visualize repos, so hearing this feedback is still useful. Better differentiation without a tooltip would be ideal, so hopefully we can improve toward that in the not too distant future. 😄 Thanks @msftrncs for helping get good info out as well!

**Comment by msftrncs** [comment]
Maybe a repository setting for an 'alias' or 'nick-name' could be used, if blank, would show the conventional repository name.  This seems to be something that Desktop sets, as I have seen the repository name change when I connect a local repository to a GitHub one, it switches to the GitHub name, but I didn't look in to why it did that; there might be a technical reason.  I would have preferred it to keep my original local name.

**Comment by billygriffin** [comment]
Thanks @msftrncs! There have been at least 8 different suggestions for how people want it so we're trying to look at it as holistically as possible. @adamreisnz is also looking at it here: https://github.com/desktop/desktop/issues/1533 and we're starting to discuss these internally. We don't want to just jump to something that will work well for a few folks but potentially neglect the larger problem set, so we want to take a bit more thoughtful and holistic approach on this one.

**Comment by xakiru** [comment]
> @jrmadsen, does hovering the mouse over each entry not hint the path?
> 
> ![image](https://user-images.githubusercontent.com/26179051/49679034-13b7b600-fa4e-11e8-91a6-8b1976934d05.png)
> 
> Maybe this is a Windows only thing?

Hi, I know this might be old, but is there any plans to make an option to show the repo list with either 
 - folder_name
 - repo_name[branch_name] 
 
Or is there a proper way to have this work without having to hover project and wait whenever we wanna switch working to another project ?

**Comment by ryaa** [comment]
This will be a very helpful feature. Or it would be very helpful if the user can change (rename) the displayed name to whatever he/she wants. This is how it works in Bitbucket Source Tree and I find it very useful....
