### ISSUE TITLE
Resource Usage

### ISSUE THREAD

**Issue by RDIL** [desktop/desktop#6370]
## Description
Recently, the client has become very laggy performance wise to the point it is almost unusable

## Version

* GitHub Desktop:

* Operating system:

**Comment by billygriffin** [comment]
Hi @RDIL, thanks for the report and sorry to hear that! Would you mind filling out the rest of the template. This isn't something we're hearing frequently so providing specific interactions that are particularly laggy/slow in addition to what version and OS version you're on would be helpful in allowing us to dig into it in more detail.
