### ISSUE TITLE
Can you synchronize the menu bar (File, Edit and View stuff) between GitHub Desktop and Atom?

### ISSUE THREAD

**Issue by FlipperCanoe163** [desktop/desktop#6371]
**Please describe the problem you think should be solved**
A clear and concise description of what the problem is and who else might be impacted. Screenshots are encouraged.

Example:

> “When I run into a merge conflict, I don’t know where to go to resolve it. Anyone who works off of multiple branches will likely run into this problem at least occasionally.”

**[Optional] Do you have any potential solutions in mind?**
A clear and concise description of one or more solutions you think might solve the problem. Please include any considered drawbacks or tradeoffs, and how users might use your solution(s). Screenshots or mockups are helpful here!

**Comment by billygriffin** [comment]
Hi @FlipperCanoe163, thanks for the issue. Would you mind filling out the template? I’d love to hear more about what you’re trying to accomplish and how this might benefit you. I suspect the answer will be no as Atom and GitHub Desktop are separate products used for different things, but it would be helpful to understand your situation a bit better. Thanks!

**Comment by FlipperCanoe163** [comment]
But man, just take a look at the pictures (Atom first, GitHub Desktop second) [cid:image001.png@01D48FBF.E5014C20] [cid:image002.png@01D48FC0.1F5F5060]
For Atom, the application’s logo is on a separate line, but in GitHub Desktop, the logo is on the same line as the File, Edit and View options! It kind of makes them look so discrete!

**Comment by billygriffin** [comment]
Hi @FlipperCanoe163, your images didn’t come through in the issue, and I’m still uncertain as to what problem this is causing for you? A bit more detail on why this is confusing or frustrating would be really helpful.

**Comment by FlipperCanoe163** [comment]
I am just addressing this because that it is really frustrating (to me, personally), to see 2 GitHub Incorporated products not having the same menu bar! It just makes the whole thing (again, to me) really messed up! ☹

**Comment by billygriffin** [comment]
Hi @FlipperCanoe163, thanks for the feedback. Atom and GitHub Desktop are separate products used for different purposes, so we think it's reasonable for them to have different items in their respective menu bars. Therefore I'm going to close this to indicate we don't intend to synchronize them, but if there's a specific thing you feel like you're missing in the Desktop menu bar options, please let us know what that is and how it might be beneficial to you and we'll be happy to discuss further. Thanks again!
