### ISSUE TITLE
Warn user when committing files with conflict markers

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#6381]
from designs in https://github.com/desktop/desktop/issues/6213#issuecomment-440048836

cc @desktop/design

**Comment by ampinsk** [comment]
Here's what I was thinking! Very open to thoughts on language here: 

<img width="699" alt="conflict-marker-confirm" src="https://user-images.githubusercontent.com/10404068/49760009-3200fa00-fc78-11e8-8cc9-8808db967160.png">

**Comment by billygriffin** [comment]
@outofambit @ampinsk I would reverse the two statements. The first one is informing you of what the state is and why you're receiving the warning, and the second is making sure you actually want to do the weird thing you're about to do.

I'd also consider updating "Are you sure you want to commit conflict markers?" to "If you choose to commit, you'll be committing conflict markers into your repository" or something that's more of a statement. I'm generally of the belief that if a dialog is asking a question, the buttons should be the user's answer to the question (for example: "Are you sure" with "Yes" and "Cancel" as the buttons).

**Comment by billygriffin** [comment]
Also, does the conflict dialog go away when this pops up, or does this pop over that dialog, or does this content replace the content of the merge conflicts dialog temporarily? Just trying to understand the interaction here.

**Comment by ampinsk** [comment]
@billygriffin sorry, this is after you click Commit from the "manual" mode if you try to commit with conflict markers. So the conflicts dialog would already be "minimized" if you're seeing this. 

How's this for a copy update?

<img width="699" alt="commit-conflict" src="https://user-images.githubusercontent.com/10404068/49761054-d7b56880-fc7a-11e8-9062-57a90cf5a0cd.png">

**Comment by billygriffin** [comment]
@ampinsk Ah, thank you, sorry I didn't catch that. Because you're not able to commit with conflict markers in the guided flow. 👍 Your update looks great to me!
