### ISSUE TITLE
display PRs from upstream repository in your fork

### ISSUE THREAD

**Issue by jeremyVignelles** [desktop/desktop#6383]
I am the maintainer of Zebobo5/Vlc.DotNet. I mostly work on my fork, and make PR to integrate changes to the main repository.

To avoid pushing inadvertently bad code into Zebobo5's project, I cloned my fork (which is `origin`), and added an `upstream` remote to track changes to the main project (`git pull upstream develop`)

I've always done everything from CLI, but wanted to give GitHub desktop a try, to see if it could improve my workflow. It seems that GitHub desktop doesn't understand this workflow, and doesn't let me checkout the PR from the main project.

My question is: Is there a way to checkout a specific PR from the main project while on a fork?

Ideas:
- Show PR from this project + from the original fork in a separate category
- Show PR from all remotes configured

**Comment by tierninho** [comment]
@jeremyVignelles Thanks for the issue and ideas! 

As of now, you can clone your fork and the main version of that repo separately within Desktop. That way you can review PRs in the clone of the main repo and do development in their clone of your fork. 

We are really curious how this feels to you as you use that workflow, and if there are particular things that are confusing or frustrating about it.

**Comment by jeremyVignelles** [comment]
That would be an alternative but I find it unpractical for a few reasons :
- A mistake has been made a long time ago : vlc has been checked in git, so the repo is quite heavy, I'd need to shallow clone
- Switching between repo would be a source of mistakes
- Each sample in this repo installs a copy of vlc from NuGet, which represents a lot of space (my repo folder is currently 4.06GB ), so doubling would be a waste of space.

I don't thinks this would be a viable solution for large repos like dotnet/coreclr

**Comment by shiftkey** [comment]
Marking this one as `user-research` to think about more. Most of the internals of Desktop use the `origin` remote when doing things like finding open PRs, but maybe there's value in making forked repositories consider the `upstream` remote too?

**Comment by outofambit** [comment]
from @gengjiawen on #6820 :
> Take `react-native` for example, I am the collaborator. I also forked the repo to contribute to it.
I cloned my forked to local, But I can't checkout other's pr to `facebook/react-native` (the upstream) in `Github Desktop`.

> In other words, I want here show `facebook/react-native` prs too.
> ![image](https://user-images.githubusercontent.com/3759816/52572042-ddcdee00-2e51-11e9-9b7e-51e7ec49420d.png)

**Comment by ampinsk** [comment]
Based on what we decided in #9170, we're going to default to showing the pull requests from the parent repository, but with an indicator (in the form of a list header) to make that explicit.

<img width="1010" alt="pull-request-list" src="https://user-images.githubusercontent.com/10404068/76897353-d2b57080-6850-11ea-90de-96b547d027db.png">

**Comment by jrock4eva** [comment]
> I am the maintainer of Zebobo5/Vlc.DotNet. I mostly work on my fork, and make PR to integrate changes to the main repository.
> 
> To avoid pushing inadvertently bad code into Zebobo5's project, I cloned my fork (which is `origin`), and added an `upstream` remote to track changes to the main project (`git pull upstream develop`)
> 
> I've always done everything from CLI, but wanted to give GitHub desktop a try, to see if it could improve my workflow. It seems that GitHub desktop doesn't understand this workflow, and doesn't let me checkout the PR from the main project.
> 
> My question is: Is there a way to checkout a specific PR from the main project while on a fork?
> 
> Ideas:
> 
> * Show PR from this project + from the original fork in a separate category
> * Show PR from all remotes configured

**Comment by JoniVR** [comment]
How can I check out and push changes to a forked repo PR now? I'm only seeing the PR's from the repo that was originally forked (which is dead).

I've resorted to reverting to 2.4.0 through time machine for now but it auto updates every time I relaunch (which should be something I'd like to disable too). 😕

**Comment by billygriffin** [comment]
@JoniVR Thanks for the response and sorry it's causing issues for you. 

The fork relationship doesn't seem to be adding any value for you at this point, so I'm wondering if it would make sense to detach your fork as its own project. GitHub Support is able to do this for you if you're interested by filling out a support ticket here: https://support.github.com/contact

In Desktop we're optimizing for the use case of the vast majority of people where forks are used primarily to contribute back to upstream. We're not opposed to revisiting this, but that's our current thinking. Hope that's helpful!

**Comment by JoniVR** [comment]
Hi @billygriffin,
Thanks for the quick reply!

> The fork relationship doesn't seem to be adding any value for you at this point, so I'm wondering if it would make sense to detach your fork as its own project. GitHub Support is able to do this for you if you're interested by filling out a support ticket here: support.github.com/contact

I've read about this but unfortunately I'm a collaborator in said project, not the maintainer, the maintainer hasn't been very active lately.


Perhaps a setting which allows me to change the new default behaviour would help, or even the ability to disable auto-updates so I can continue using the older version. 

Another option would be showing both at the same time, where both have the header of their respective repo:
![image](https://user-images.githubusercontent.com/7591717/79773360-a8fcd700-8331-11ea-9e0e-10ef779e412c.png)


I'd be happy to look into contributing if it's too low priority but I'm not very familiar with the current codebase.

It's just that Github Desktop suddenly became pretty much useless for me in a x.x.1 update, which is pretty unfortunate because I like it a lot and it has been an essential tool in my workflow.

Hope you have a nice day :)
