### ISSUE TITLE
Commit failed - exit code 1 received: not the result of nested .git folders

### ISSUE THREAD

**Issue by MadRoboticist** [desktop/desktop#6389]
## Version 1.5.0

* GitHub Desktop: Version 1.5.0

* Operating system: Windows 7 Ultimate x64

## Steps to Reproduce

1. Open Github desktop 
2. Create a repository
2-1: (edit) Realize that you accidentally put the project in a child folder, move git files to parent folder of same name
3. Do the initial commit and push (publish)
4. See that there are a bunch of changes
5. Try to do a commit
6. Get the error
7. See that the code is all up to date on github.com
8. Try to fetch the origin
9. See that nothing has changed
10. Google the problem, see that it may be the result of nested .git folders (which cleared this problem on the previously created repository just a few minutes prior)
11. Find no nested .git folders
10. fill out this form
### Expected Behavior

I expect all the changes to be cleared
### Actual Behavior

I get the error and none of the changes are cleared

### Logs

[2018-12-11.desktop.production.log](https://github.com/desktop/desktop/files/2665565/2018-12-11.desktop.production.log)

Thanks for your help

**Comment by MadRoboticist** [comment]
not sure why these files weren't included 
![gitchanges](https://user-images.githubusercontent.com/43861847/49771833-e7689780-fce2-11e8-9cdb-ae0dc10044ee.PNG)

![error](https://user-images.githubusercontent.com/43861847/49771841-edf70f00-fce2-11e8-8397-628d3cb60ef3.PNG)

**Comment by billygriffin** [comment]
Glad you were able to figure it out, and thanks for letting us know @MadRoboticist!
