### ISSUE TITLE
Upgrade from Electron 2.x to Electron 3

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#6391]
Currently, the latest electron version is 3.0.10, but the version desktop used is still 2.0.13. Why don't we use the latest version?

**Comment by billygriffin** [comment]
Hi @TerryChan, thanks for the issue! Upgrading to Electron 3 is on our radar and appreciate your asking. The team has been focused primarily on feature work and we’ll likely be starting the process in the next couple months. @nerdneha Please feel free to add additional thoughts. It’s something we’ve been discussing internally but I don’t think we have a public issue for it yet, so we can use this one if you’d like.

**Comment by billygriffin** [comment]
Thanks for the additional context @nerdneha! @TerryChan I'm going to go ahead and update the issue title to reflect that it's an issue to track the progress of the upgrade. Thanks again. 😄

**Comment by shiftkey** [comment]
I believe `keytar` and `runas` will need upgrades as part of migrating to Electron 3 - #5669 is the `runas` issue, and I don't have a tracking issue for `keytar` because I think the upgrade process is relatively straight-forward.

**Comment by shiftkey** [comment]
We should keep an eye on the outstanding 3.x issues to ensure that we're not impacted by some known corner cases as part of this upgrade: https://github.com/electron/electron/labels/3-0-x

For example:
 - https://github.com/electron/electron/issues/16099
 - https://github.com/electron/electron/issues/14683
