### ISSUE TITLE
Option to prefer cloneUrl?

### ISSUE THREAD

**Issue by davatron5000** [desktop/desktop#6393]
**Please describe the problem you think should be solved**

By default when cloning a repo from GitHub app, it uses the `githubRepository.htmlUrl` for the remote `origin`. This is all fine until I try to make commits from the command line. Because I have 2FA enabled, I have to use the `githubRepository.cloneUrl` (the `.git` url) over SSH. It's a tiny annoyance where I have to go to the repo and manually reconfigure as the `cloneUrl`. 

**[Optional] Do you have any potential solutions in mind?**

Is it possible to have a global setting in GitHub for Desktop to "[ ] Prefer the Clone Url"? This would make `Hit Clone Button on GitHub > Pull Repo with App` flow just a tiny bit smoother. Thanks.

**Comment by davatron5000** [comment]
Yes! That's what I'm asking. I want to say I've been able to switch the remote manually and it works, but can't remember right now. 

So feel free to merge into that issue. I'd just like to use the SSH `cloneUrl` as the `origin` remote. So it sounds like that would cover it.

**Comment by tierninho** [comment]
@davatron5000 Thanks for the update, David!
