### ISSUE TITLE
Ordering of adding respositories is inconsistent

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#6396]
**Please describe the problem you think should be solved**

In #6365 we're looking at improving the onboarding flow to get to your first repository added to Desktop. @tierninho pointed out that the ordering of ways to add a repository is inconsistent between the file menu, the "Add" button in the repo dropdown, and the new cloning flow after onboarding.

The file menu uses OS conventions around "New" being first, but there's no reason why the "Add" button in the repo dropdown shouldn't align with the new onboarding ordering.

**Do you have any potential solutions in mind?**

We'd like for "Clone, Add, Create" to be reordered to "Clone, Create, Add" in this:

<img width="300" alt="screen shot 2018-12-11 at 9 21 30 am" src="https://user-images.githubusercontent.com/5091167/49814199-5e734f80-fd26-11e8-9f38-90d0356b460c.png">

This seems like a great first issue for a community contributor to take on, and please let us know if you have questions. 😄

**Comment by vilanz** [comment]
I'd like to help. Submitted a PR

**Comment by tierninho** [comment]
@billygriffin did you want the File menu re-ordered as well? 

Create, Add, Clone ➡️Clone, Create, Add

**Comment by billygriffin** [comment]
@tierninho The file menu for Windows and Mac use OS conventions around that menu ordering, so I'd like to keep those as is, at least for now. Thanks for double-checking.

**Comment by tierninho** [comment]
Fyi: we use the terms Local and Existing in the two menus mentioned above to refer to "local" repos. New issue needed to fix this?

**Comment by billygriffin** [comment]
I wonder if it's actually most explicit and clear if "Add Existing Repository" / "Add Local Repository" (which are used interchangeably as @tierninho mentions above) became "Add Existing Local Repository." Thoughts @desktop/maintainers?

**Comment by say25** [comment]
Local makes a 🗺 of difference
