### ISSUE TITLE
Auto-scan functionality for repositories of given folder

### ISSUE THREAD

**Issue by DaanV2** [desktop/desktop#6400]
## Description
I use a folder probably like most programmers where I keep my projects on my hard drive. I tend because of organisation to shift some projects or rename them cause the desktop app to lose the repository. I would love for the Desktop app to have a functionality that you can do either/or/and that allows to add multiple repositories add once:

## 1. User select
The user can selected a folder through browsing. That folder and sub-folders will be scanned for existing repositories and added onto the app's list.

## 2. Default folder in settings
Through either a button or/and on startup, the app looks through the given folder list in its settings. And scans each of those folders and possible sub-folders for repositories.

I would love for this to become an Feature 😄 
Keep up the good work on the rest of the App 👍

**Comment by steveward** [comment]
Thanks for opening this @DaanV2! This looks like a duplicate feature request of https://github.com/desktop/desktop/issues/1574. I've dropped your feedback directly into that issue. I'm going to close this issue out, but please follow along in #1574 for any updates about this feature.
