### ISSUE TITLE
How to disable unittest?

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#6401]
I want to breakpoint debuging in vscode in Windows, but when I start debug, it will run unittest and the unittest will fail:
![image](https://user-images.githubusercontent.com/5396286/49843901-c8115d80-fdfb-11e8-961a-3f1dc18752cd.png)
Then the debug cannot start. I'm thinking if I disabled the unittest, maybe the debug can start. And the unittest will waste me a lot of time to launch debug. How to disable the unittest? I can breakpoint debuging other electron app successfully in vscode.

**Comment by tierninho** [comment]
@TerryChan thanks for filing but this is VS Code issue. Please post your issue here: https://github.com/github/VisualStudio/issues

**Comment by TerryChan** [comment]
@tierninho thanks for your reply. Do you know how to disable the unittest? I want to have a try if I disable the unittest, whether the debug can be launched successfully. Since launch.json is provided under .vscode, that means we can debug desktop in vscode directly, right?
