### ISSUE TITLE
Use monospace font for reporting errors from git hooks

### ISSUE THREAD

**Issue by amio** [desktop/desktop#6403]
Usually the error message thrown by git hooks was mean to shown on terminal with monospace font, or we will break the text layout:

![photo_2018-12-12_20-18-32](https://user-images.githubusercontent.com/215282/49869362-287bbb80-fe4b-11e8-87d3-97b18e899070.jpg)

**Comment by tierninho** [comment]
@desktop/design thoughts?

**Comment by tierninho** [comment]
@amio thank you for filing this! Going to mark this as `help-wanted` so feel free to pick it up 😄

**Comment by tierninho** [comment]
cc @desktop/engineering thoughts?

**Comment by zerefwayne** [comment]
@tierninho Is this issue still open? I would like to work on this one.

**Comment by tierninho** [comment]
@zerefwayne It is all yours. Thank you!

**Comment by outofambit** [comment]
@zerefwayne i'm happy to help if you have any questions!
