### ISSUE TITLE
Merge Conflicts cannot proceed when untracked files exist

### ISSUE THREAD

**Issue by SleepyJay** [desktop/desktop#6411]
### Reproduce:
1. Start with a branch that has 1 or more untracked files.
2. Merge another branch, like master, into branch, such that conflicts will arise (should NOT be changes that track above file(s)).
3. Merge Conflict dialog pops up.
4. Resolve merge conflicts in editor (do not remove untracked files).
5. Press "Commit Merge" button. 
6. See error: "Could not generate a patch for file foo/bar, patch empty".
7. Now you are stuck.

### Work arounds:
1. Move (temporarily) the untracked file(s). 
2. Run `git add foo/bar` outside of the app. 

Neither are particularly pleasing options. 

### Preferred Solutions:
1. Quietly skip untracked files for the merge, unless, of course, the merge adds them. Committing anything that didn't come from the merge makes no sense from the merge's perspective. (Preferred)
2. Do (1) and offer options to add or skip untracked. (Ok, but messier merge) 
3. Allow me to exit the dialog and commit when I'm ready, which is sort of how it was before the Merge Conflict dialog was added. (Ok, less messy than (2), but not great)
4. Warn me that the merge cannot be started with untracked files present, which is hardly better than doing nothing. (Meh, I'll just end up do work around 1 anyway)

**Comment by billygriffin** [comment]
Thanks @SleepyJay, this is a super detailed and helpful report. I'm trying to discern the difference between this and #6349, as they seem like similar states but that one actually commits the files as part of the merge commit, whereas in your case it errored out. We're going to look into that so we can ensure it's a more elegant solution as we totally agree the behavior you're seeing is suboptimal.

**Comment by SleepyJay** [comment]
In #6349 they are talking about changes to tracked files, while as this (#6411) is with untracked files and a dialog-deadlock sitch. My preferred solution (1) is for the same reasons #6349 was filed: the merge commit should only contain the merge, not also my local uncommitted changes. Note that this is why you (or Git) won't allow a merge when the merge will conflict with local uncommitted changes.

**Comment by SleepyJay** [comment]
@billygriffin Ya. I didn't mean to imply otherwise. :) 👍
