### ISSUE TITLE
[Metrics] Merges from branch dropdown

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#6414]
**What question are we trying to answer?**

We'd like to understand if we made merging more discoverable by including a way to merge in the branch dropdown?

**What metrics do we need to help answer that?**

- [ ] Absolute number of merges initiated via the new button in the branch dropdown.

<img width="633" alt="screen shot 2018-12-13 at 1 46 10 pm" src="https://user-images.githubusercontent.com/5091167/49966536-793bf480-fedd-11e8-8726-b96afae40f0a.png">

cc: @iAmWillShepherd @ampinsk @telliott27

**Comment by iAmWillShepherd** [comment]
> Absolute number of merges initiated via the new button in the branch dropdown.

@billygriffin could you clarify if ☝️ means merges actually completed or just initiated (aka button clicks)?

**Comment by iAmWillShepherd** [comment]
I can get you the click count pretty quickly, but it will take a bit more time to get merges completed from this button. I'd have to refactor the code a bit to better keep track of state.

**Comment by billygriffin** [comment]
Good question! My impression is that what we’re trying to capture here is intent, and therefore I think it’s “initiated.” Our goal is to make merging more discoverable by including it in a more intuitive place, so I think that aligns with initiated over completed.

**Comment by billygriffin** [comment]
I'm going to close this for now because we're thinking about a new metrics concept anyway and the current merge metrics are not particularly reliable.
