### ISSUE TITLE
Provide dev-only helper functionality to toggle the release notes popup

### ISSUE THREAD

**Issue by koralcem** [desktop/desktop#6418]
**Please describe the problem you think should be solved**

I wanted to prepare a change to address https://github.com/desktop/desktop/issues/5605. I realized very quickly that to be able to see the effects of my changes, I somehow need to show the release notes popup. There doesn't seem to be an easy way to do so. Suggestions in that issue were to use a unique build with an update pending, or temporarily hardcode some values. 

While I imagine those methods would trigger the popup just fine, they would have to be given to every other person working on that popup in the future.

**Do you have any potential solutions in mind?**

I noticed the "Help" menu already houses some dev-only functionality to aid in verification ("Crash main process...", "Crash renderer process..."). I suggest adding an entry there to trigger popups. This specific issue is written from the perspective of the release notes popup, but it could be expanded in the future to be able trigger any popup.

**Comment by tierninho** [comment]
@koralcem Many thanks for adding the associated [PR](https://github.com/desktop/desktop/pull/6419) and congrats on contributing your first PR too 💛  

As our team focused on getting next week’s release out and with the holidays approaching, we may not be able to get to a review until after the break. 

We will circle back soon, so hold tight. ⚡️

**Comment by koralcem** [comment]
That's all good; no rush. I appreciate the explanation rather than weeks of silence.
