### ISSUE TITLE
Merge conflict branches with some uncommited changes

### ISSUE THREAD

**Issue by SaitDev** [desktop/desktop#6421]
## Version

* GitHub Desktop: 1.5.0-linux5

* Operating system:
ElementaryOS 0.4 (based on Ubuntu 16.04

## Steps to Reproduce

1. Having 2 branchs A and B. Made change to some files `x.txt` and `y.txt` while still on branch A
2. Commit only file x.txt on branch A
3. Checkout branch B, merge A into B
4. Got conflict, solve conflict -> click merge

### Expected Behavior

Can merge after solving conflict

### Actual Behavior

Error message: Could not generate a patch for file `y.txt`, patch empty

**Comment by billygriffin** [comment]
Thanks for the detailed report @SaitDev! I think this is the same as #6411, so please follow along there.
