### ISSUE TITLE
check icon in changes list after resolving conflicts is not "green"

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6423]
Make the check for a resolved conflicted file green. It is currently orange in both light/dark mode.

1.5.1-beta4, mac

<img width="903" alt="screen shot 2018-12-14 at 11 14 26 am" src="https://user-images.githubusercontent.com/14828183/50022904-86ff8180-ff92-11e8-9b29-02f3ed860df9.png">

**Comment by ampinsk** [comment]
After investigating more, I think this is a logic problem, not a styling problem. The check icon is getting the class `status-conflicted` instead of `status-resolved`, which is giving it the wrong color. @outofambit and I chatted through it, and she's going to pick this up next week.

**Comment by shiftkey** [comment]
Moving this into 1.6.0 as I don't think we'll be able to get this out before the `1.5.1` release tomorrow

**Comment by shiftkey** [comment]
Actually, we've figured out the solution here (and it was a regression from what we had in 1.5.0) so we're aiming to ship this in a final `1.5.1-beta6`.
