### ISSUE TITLE
Hangs on fetching origin after waking form hibernate

### ISSUE THREAD

**Issue by Axiverse** [desktop/desktop#6425]
With GitHub desktop open, have the computer enter hibernate. On wake, GitHub desktop with show "Fetching origin, hang on..." with the refresh icon spinning. However this never goes away nor am I able to click it again to retry the fetch.

Version 1.5.0

Logs don't detail any of the current event. Last log is from a previous fetch.

Windows 10 Pro 1803, Lenovo X1 carbon gen 6.

**Comment by tierninho** [comment]
@Axiverse Thanks for the issue.

Any further details you could share would help in investigating this. Were you performing an action prior to or at the moment the computer entered hibernate?

What happens if you select menu Repository > Push (or Pull)?

A gif is helpful but not req'd.

**Comment by tierninho** [comment]
@Axiverse As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
