### ISSUE TITLE
Cloning repo using full path 

### ISSUE THREAD

**Issue by shebdim** [desktop/desktop#6430]
**repo name is not unique**
GitHub is the biggest storage. Too many repositories may have an identical name. So repo name is not enough to use as the local path name.

Example:

I want to use to a different repo

`https://github.com/mfouquet/Reselect` and `https://github.com/reselect/Reselect`

When I open it in Desktop, local path is `GitHub/Reselect` for both of them.

**Solution**
An option like "Full path for cloning". When the option is enabled, use a local path like `GitHub/mfouquet/Reselect` and `GitHub/reselect/Reselect` respectively.

**Comment by shiftkey** [comment]
@shebdim thanks for the feedback! We're talking about this in #5449 - please follow along with that discussion.
