### ISSUE TITLE
The UI is incorrect in development version

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#6432]
I built the latest code and ran the development version on Windows as [this guide](https://github.com/desktop/desktop/blob/master/docs/contributing/setup.md#building-desktop), but the UI is incorrect- there is no color background on the UI:
![image](https://user-images.githubusercontent.com/5396286/50062491-69c0f200-01e2-11e9-889a-2c9dfae38ebe.png)
I also installed GitHub Desktop which downloaded from official site, the UI is good.
I think maybe I lost some stylesheet files, does anyone know how to fix it?

OS version: windows 10 1703
node version: v10.14.1
npm version: 6.4.1

**Comment by shiftkey** [comment]
@TerryChan thanks for the report!

There's a mention about Node versions in [this document](https://github.com/desktop/desktop/blob/master/docs/contributing/setup-macos.md#nodejs), as we've found Node 10 has some issues with the version of `node-sass` used in the app (which only affects the colours displayed).

For the moment we're stuck on Node 8.x, but #5876 is our tracking issue for getting up to date. Please keep an eye on that issue.
