### ISSUE TITLE
enable VSCode debugging of the renderer process

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#6433]
I want to breakpoint debugging, but I failed in vscode. Which methods do you used to debug?

**Comment by shiftkey** [comment]
@TerryChan I'm not quite sure of the context, but we currently only support breakpoint debugging when running the tests, not the main application.

I think we're limited a bit by how we organize the codebase (we use Webpack to transpile source) and also run the app in development mode (using `webpack-dev-middleware`) but there are plenty of resources out there that might be adaptable to our setup - we just haven't explored it recently.

Is this something you're exploring for working with the Desktop project?

**Comment by tierninho** [comment]
@shiftkey Some more context here, although not sure if it will help: https://github.com/desktop/desktop/issues/6401

**Comment by shiftkey** [comment]
@tierninho thanks for that!

>  Since launch.json is provided under .vscode, that means we can debug desktop in vscode directly, right?

This isn't correct, because `launch.json` only defines a number of configurations that the debugger can be launched. We've defined two configurations currently that are focused on running tests:

 - run all unit tests in Jest
 - run a specific file containing tests in Jest

If we wanted to support debugging the app in VSCode, we'd have to define an additional configurations to support that.

**Comment by msftrncs** [comment]
I find most things are debug'able via the developer tools item, 'View - Toggle developer tools', though there have been some areas I have not been able to set break-points in.  Maybe not as friendly since you are not looking at the source code in VS Code, but its been doing the job.

**Comment by shiftkey** [comment]
I'm going to update this issue to indicate we're talking about enhancing the VSCode `launch.json` file to support debugging the app.

We currently have Chrome Dev Tools available currently (with sourcemap files so you can step into the TS source), but if someone wants to have a shot at adding VSCode support to launch and debug the app this guide is a good starting point to understanding how to hook into an Electron app https://github.com/Microsoft/vscode-recipes/blob/master/Electron/README.md

**Comment by spitWind** [comment]
GitHubDesktop --inspect 可以调试主线程~.~

**Comment by billygriffin** [comment]
I'm going to close this because it's not something we've seen requests for from others.
