### ISSUE TITLE
could not read Username for 'https://domain name': terminal prompts disabled while cloning

### ISSUE THREAD

**Issue by avinash2wards** [desktop/desktop#6434]
Cloning into 'D:\UserID\test-github-iuuse\RepoName'...
error: cannot spawn C:\Users\UserID\AppData\Local\GitHubDesktop\app-1.5.0\resources\app\static\ask-pass-trampoline.bat: No error
fatal: could not read Username for 'https://domain name': terminal prompts disabled

[Logs]
2018-12-17T11:56:15.330Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://domainname/repo/repo.git D:\userID\test-github-iuuse\repo` exited with an unexpected code: 128.

Windows 7 64 bit.
Github desktop - version 1.5.0

**Comment by shiftkey** [comment]
@avinash2wards thanks for the report! This feels like #5082 which we have some ideas about but no firm reproduction. Are you connecting to a GitHub Enterprise server?

**Comment by avinash2wards** [comment]
Hello,
Thanks for responding, yes , I am connecting to GitHub Enterprise server.


On Mon 17 Dec, 2018, 6:07 PM Brendan Forster <notifications@github.com<mailto:notifications@github.com> wrote:

@avinash2wards<https://github.com/avinash2wards> thanks for the report! This feels like #5082<https://github.com/desktop/desktop/issues/5082> which we have some ideas about but no firm reproduction. Are you connecting to a GitHub Enterprise server?

**Comment by shiftkey** [comment]
@avinash2wards cool, let's move the discussion over to that issue then
