### ISSUE TITLE
I cannot sign in (ubuntu 18.04 desktop.)

### ISSUE THREAD

**Issue by github-raiyan** [desktop/desktop#6437]
When I try to sign in this window comes.

![deepinscreenshot_select-area_20181217223605](https://user-images.githubusercontent.com/45367929/50101120-3450ee80-024c-11e9-8b80-9d5023de7d6a.png)

**Comment by shiftkey** [comment]
@github-raiyan thanks for the report.

We're tracking Linux-specific issues in [`shiftkey/desktop`](https://github.com/shiftkey/desktop/) and the relevant issue is https://github.com/shiftkey/desktop/issues/59.

**Comment by github-raiyan** [comment]
@shiftkey problem fixed. Thank you very much.
