### ISSUE TITLE
Login after password change problem

### ISSUE THREAD

**Issue by AlexeySinushkin** [desktop/desktop#6453]
![image](https://user-images.githubusercontent.com/7188665/50212009-f4594b00-03b4-11e9-9ccc-de00dea93997.png)

I can not use it after password change on website

**Comment by iAmWillShepherd** [comment]
You can sign out of the app and sign back again to resolve this.

1. GitHub Desktop -> Preferences
1. Logout of your accounts
1. Login using new username/password combination

**Comment by iAmWillShepherd** [comment]
I'm going to close this out as resolved to keep our backlog short. If the steps above do not help you resolve this issue, please re-open this issue and add your results along with the other pieces we ask for in the issue template.

**Comment by steveward** [comment]
We now provide an option to open Preferences/Options from the authentication failed dialog, so I'm going to close this out as resolved.
