### ISSUE TITLE
Feature request: Submodule&Stash&Tag

### ISSUE THREAD

**Issue by Amarterlus** [desktop/desktop#6454]
open VSC to solve conflict is awesome!
but I still need this FEATURES to uninstall SourceTree:
Submodule Management & Stash & Tag

**Comment by iAmWillShepherd** [comment]
Thanks for taking the time to contribute!

We already have issues that capture some of the features you're requesting:
* https://github.com/desktop/desktop/issues/2304 - Stashing
* https://github.com/desktop/desktop/issues/257 - Tags

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @Amarterlus if you're able to answer the questions that @iAmWillShepherd has asked in the previous comment we're happy to revisit it.
