### ISSUE TITLE
Feature Request - Add Syntax highlighting for Visual Basic

### ISSUE THREAD

**Issue by SimpleBinary** [desktop/desktop#6461]
1. Open a Visual Basic File
2. You can see that there is no Syntax Highlighting in the Dark or Light Theme

This would be helpful to Visual Basic Developers, as it would help them to quickly pick up mistakes in their code.
![image](https://user-images.githubusercontent.com/40658215/50277377-f8a66680-048f-11e9-9094-2426386917c5.png)

**Comment by shiftkey** [comment]
@SimpleBinary thanks for opening this issue. Our syntax highlighting support is based on Codemirror which I believe has support for VB included - we just haven't enabled it.

If someone would like to try it out, we have document about [syntax highlighting](https://github.com/desktop/desktop/blob/cf99e9555c0ffb646e33c16957e4f037c06ecbfb/docs/technical/syntax-highlighting.md) to understand more as well as [getting setup](https://github.com/desktop/desktop/blob/cf99e9555c0ffb646e33c16957e4f037c06ecbfb/docs/contributing/setup.md) if you want to build Desktop in development mode.

**Comment by Daniel-McCarthy** [comment]
I would be more than happy to set this up for the `.vb` extension, add a VB file for the highlighter tests, and add Visual Basic to the supported list. Perhaps that could work as an example in case more extensions are required for VB.

**Comment by shiftkey** [comment]
@Daniel-McCarthy sounds great.

@SimpleBinary do you have a sample file we can use? We'd like to identify the right file extensions and ensure the syntax highlighting is working as intended as part of enabling this feature...

**Comment by SimpleBinary** [comment]
@Daniel-McCarthy so I just add that sample file to the highlighter-tests and add Visual Basic to the Supported list [here](https://github.com/desktop/desktop/blob/cf99e9555c0ffb646e33c16957e4f037c06ecbfb/docs/technical/syntax-highlighting.md)?

**Comment by shiftkey** [comment]
@SimpleBinary you also need to wireup the logic in here: https://github.com/desktop/desktop/blob/master/app/src/highlighter/index.ts

**Comment by Daniel-McCarthy** [comment]
@SimpleBinary That depends. If you would would like to do it yourself you would also need to set up Desktop to use codemirror's VB highlighting via the file shiftkey has linked.

Otherwise, I can set up Codemirror and add Visual Basic to the supported list you linked, and you can add the sample file to [highlighter-tests](https://github.com/desktop/highlighter-tests) here.

Either way is certainly fine by me. I have an environment set up and can get the changes prepared for the Desktop side, but if you're interested in contributing yourself, by all means go ahead!

**Comment by SimpleBinary** [comment]
@Daniel-McCarthy I have done it. You don't need to worry.

**Comment by say25** [comment]
https://github.com/desktop/desktop/pull/6471 linking as I can't tweak the PR description
