### ISSUE TITLE
Inconsistent behavior for uncommitted changes indicator

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6462]
The uncommitted changes indicator 🔵in the repo list is inconsistent when there is a file waiting to committed vs merge conflict changes. 

For a file that it changed outside of a conflict, the indicator shows up and it removed as soon as the file is committed, as expected. When there is a conflict, the blue hangs around as soon as the conflict is aborted. It should be disappear. 

Fetching will remove it.

Merge conflict in progress and Change list populated:
<img width="763" alt="screen shot 2018-12-20 at 9 52 37 am" src="https://user-images.githubusercontent.com/14828183/50302160-1e0a8480-043e-11e9-9037-34dd03226075.png">

Merge conflict aborted, 🔵still present:
<img width="744" alt="screen shot 2018-12-20 at 9 53 23 am" src="https://user-images.githubusercontent.com/14828183/50302183-2cf13700-043e-11e9-8d23-cfb363d6bdcc.png">

v1.5.1, mac

**Comment by tierninho** [comment]
> I think this is worth revisiting after #6141 is merged

@shiftkey As #6141 was merged, just wanted to bring this back up. cc @outofambit in case this is worthy enough to be part of the repo grouping. 😬 

If background fetching removes the blue indicator, we can probably just close this issue as that is sufficient.

**Comment by billygriffin** [comment]
Just took a look at this again and checked with @outofambit and we're both also 👍 on closing. Thanks!

**Comment by mikeukeul** [comment]
“Il est temps que GitHub et GitHub Desktop franchissent le pas vers une interface universelle et multilingue. Les extensions de traduction ne suffisent pas : elles bricolent là où une solution native apporterait cohérence, fiabilité et inclusion. Dans un monde où l’IA traduit le sumérien, pourquoi nos outils modernes ne pourraient-ils pas traduire toutes les langues vivantes ? Arrêtons le cloisonnement des pensées et ouvrons le monde des possibles.”
