### ISSUE TITLE
Open in Finder/Explorer terminology is inconsistent

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6466]
We use different terminology when offering to open a file in Finder/Explorer. 

Should we use `Show in Finder/Explorer` or `Reveal in Finder/Explorer`, or do we use "Open in" as we do for other actions, such as `Open in Atom`? 

Before this gets labeled as `help-wanted`, some thoughts for @desktop/core first?

v1.5.1, mac

<img width="220" alt="screen shot 2018-12-20 at 11 39 36 am" src="https://user-images.githubusercontent.com/14828183/50307143-692b9400-044c-11e9-9160-1d8f3a7e21d3.png">
<img width="315" alt="screen shot 2018-12-20 at 11 39 49 am" src="https://user-images.githubusercontent.com/14828183/50307146-692b9400-044c-11e9-8930-a177303c5fc3.png">
<img width="348" alt="screen shot 2018-12-20 at 11 40 08 am" src="https://user-images.githubusercontent.com/14828183/50307147-692b9400-044c-11e9-80e7-b68c1dc6e901.png">
<img width="356" alt="screen shot 2018-12-20 at 11 40 39 am" src="https://user-images.githubusercontent.com/14828183/50307148-69c42a80-044c-11e9-9476-c85013162fdd.png">

**Comment by steveward** [comment]
Anecdotally I still have the bad habit of telling users to `Open in Finder/Explorer` since that was what we used in the classic apps. I'd prefer unified phrasing. 😃

**Comment by billygriffin** [comment]
I think I prefer "Open in Finder/Explorer" as well, and more importantly I agree that it should be consistent across the app. @desktop/design Any heartburn about this?

**Comment by shiftkey** [comment]
One bit of nuance that I'll call out:

 - `Open in X` - view the contents of a folder, or open a file in an editor
 - `Reveal in Finder/Explorer` - show the location of a folder or file in the OS file utility (not the contents)

This is coming from Electron's [`shell.showItemInFolder`](https://electronjs.org/docs/api/shell#shellshowiteminfolderfullpath) API, which we use in a few places, e.g.
 
https://github.com/desktop/desktop/blob/db53079e3d0eb0b3087f57390b108b0626f06c1e/app/src/ui/app.tsx#L1695-L1701

I'm not sure how `Show` crept in to the terminology over Reveal (which I've seen other tools like VSCode use to expose this functionality), but I still think there needs to be some distinction here.

**Comment by billygriffin** [comment]
Totally valid @shiftkey, I agree the distinction may be important and I'm also 👍 on being consistent with what other tools use if people are used to seeing a particular pattern.

In checking three different widely used programs, two use "Show in Finder/Explorer" and one uses "Reveal in Finder/Explorer." I think if we think we'd like to maintain the distinction, which seems reasonable to me, then "Show" is a bit more plain language than "Reveal," but I don't feel too strongly about it.
