### ISSUE TITLE
Order of Merge hint and merge button are inconsistent

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6467]
The order of the merge hint and merge button in the Compare Branch feature and the Merge into Current Branch modal are different. 

It is either:
`Merge button, merge status icon, merge hint`
or
`Merge status icon, merge hint, merge button`

<img width="877" alt="screen shot 2018-12-20 at 11 53 42 am" src="https://user-images.githubusercontent.com/14828183/50307875-6e89de00-044e-11e9-95a2-997fac9f0b33.png">

For consistency, we should make them the same. cc @desktop/design 

v1.5.1, mac

**Comment by shiftkey** [comment]
I'd like to hear from @desktop/design and/or @desktop/product about which layout they prefer here

**Comment by billygriffin** [comment]
Thanks @tierninho! Since @ampinsk updated the flow here (
https://github.com/desktop/desktop/issues/5555#issuecomment-429963614) I’m going to defer to her. Unless it causes things to jump around or something else that feels unexpected, seems like they both should probably just match her latest iteration linked in the comment - with merge hint first and then the button below.

**Comment by ampinsk** [comment]
Agreed they should be consistent 👍

**Comment by billygriffin** [comment]
Adding `help wanted` here since there's a nice pattern here to go from. To be perfectly clear, the merge hint should go first and then the button should go below it - but whomever looks at this, please be sure to check that it doesn't cause any weird visual issues (like the UI jumping around).

**Comment by Daniel-McCarthy** [comment]
This may potentially be a great candidate for the `good-first-issue` tag, which I think is very useful for new contributors.

**Comment by Raul6469** [comment]
Hi! 👋 I can work on this issue

**Comment by outofambit** [comment]
Awesome @Raul6469! Let us know if you have any questions! 🚀
