### ISSUE TITLE
Differentiate Untracked Files from Added Files in Status Models

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#6468]
Currently, our status models parse `Added` files and `Untracked` files as `AppFileStatusKind.New`. Unfortunately, this means we lose information in the application about which files are which.

https://github.com/desktop/desktop/blob/b556ff8f9746447b7457fdbe78796b835e1db322/app/src/lib/git/status.ts#L104-L130

This issue proposes adding an `AppFileStatusKind.Untracked` to cover this case.

required to fix #6411

**Comment by shiftkey** [comment]
One thing to keep an eye out for is the cascading effects from this, like in `mapStatus` and `iconForStatus`:

https://github.com/desktop/desktop/blob/b556ff8f9746447b7457fdbe78796b835e1db322/app/src/lib/status.ts#L17

https://github.com/desktop/desktop/blob/b556ff8f9746447b7457fdbe78796b835e1db322/app/src/ui/octicons/status.ts#L11

I think we should still map `AppFileStatusKind.Untracked` to `'New'` and `OcticonSymbol.diffAdded` in these cases.
