### ISSUE TITLE
Un-capitalization of items in the Branch menu

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6469]
Two items in the Branch menu contain capitalized letters when they should be lowercase. They are the only two outliers for our entire top-nav menu.

Change:
`Update From` ➡️ `Update from`
`Merge Into` ➡️ `Merge into`

"From" is a transitional word and "into" is an prepositions, so no caps. 💡 

A bit nit-picky, but it is a `good first issue` and it will help with consistency and putting the emphasis on the right place for each menu item.

v1.5.1, mac

<img width="223" alt="screen shot 2018-12-20 at 2 51 01 pm" src="https://user-images.githubusercontent.com/14828183/50315208-b3217380-0466-11e9-9038-4ce51335f1ea.png">

**Comment by msftrncs** [comment]
@tierninho, I have noticed that there is a function for this in  [/app/src/lib/platform-case.ts](https://github.com/desktop/desktop/blob/800bbd3eeeacab4f409cae8bcc468b6cb0c32852/app/src/lib/platform-case.ts) but that it seems to be seldom used, seems its relatively new.  I don't think it handles the cases the way you are suggesting.

**Comment by tierninho** [comment]
@say25 thanks for the link! Closing this in favor of the prior issue.

**Comment by billygriffin** [comment]
Reopening because we haven't decided on toPlatformCase usage and there's no reason to hold this up. PR imminent.
