### ISSUE TITLE
Merge count in editor isn't in-sync with Merge modal

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6472]
When opening the Merge Modal and seeing the conflict count within each file, and then comparing it against what is recorded in the editor, the two numbers do not match.

Not sure how to consistently trigger this or if it editor specific.

Tested with Mac, Atom, on v1.5.1. Maybe related to: https://github.com/desktop/desktop/issues/6101

<img width="400" alt="screen shot 2018-12-20 at 3 18 30 pm" src="https://user-images.githubusercontent.com/14828183/50317753-149b0f80-0472-11e9-97d4-16a2f6f0bdf4.png">

**Comment by shiftkey** [comment]
@tierninho do the numbers get back in sync when you focus on Desktop again?

**Comment by tierninho** [comment]
@shiftkey No they do not, but all the numbers do decrement accordingly when selecting the "Use Me" buttons and saving the changes in Atom. 

I did notice remnants of file changes in Atom *after* selecting the "Use Me" buttons and saving. Atom does not register these remnants as conflicts, but Desktop does. I think this is the problem.

<img width="1016" alt="screen shot 2018-12-21 at 10 12 21 am" src="https://user-images.githubusercontent.com/14828183/50357056-735f9800-0509-11e9-9daa-daf515f3611c.png">

**Comment by tierninho** [comment]
Ok. As this is out of our hands, will close this out. ⚡️
