### ISSUE TITLE
Global .gitignore files are being ignored

### ISSUE THREAD

**Issue by jslewis90** [desktop/desktop#6479]
## Description

Global .gitignore files are being ignored by GitHub Desktop causing the ignored files to still appear in the Changes tab.

## Version

* GitHub Desktop: 1.5.1

* Operating system: Windows 10 Home, 1809 (build 17763.195)

## Steps to Reproduce

1. Initialize a Git repository with no `.gitignore` file
2. Configure Git to globally ignore your code editor's folder (`/.vscode` for VSCode or `/.idea` for PHPStorm) - [relevant instructions](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore)
3. Open your project in the code editor. It should create the above folder in your directory.
4. Open GitHub Desktop and add your folder as an existing repository.

### Expected Behavior

When I open my repository in GitHub Desktop, the globally ignored editor folder will not be listed in the changes tab.

### Actual Behavior

The globally ignored editor folder and its content are listed in the changes tab in GitHub Desktop.

## Additional Information

[commit from laravel/laravel to update .gitignore to exclude editor folders](https://github.com/laravel/laravel/commit/bc435e7fdd8308d133a404b1daa811dd30d95fe5)

[Screenshot - Github Desktop](https://user-images.githubusercontent.com/17649602/50357430-fbeb3200-0523-11e9-8737-386f0e15ac51.jpg)
[Screenshot - git status](https://user-images.githubusercontent.com/17649602/50357418-f1309d00-0523-11e9-934a-a7db3b451a8d.jpg)

### Logs

[2018-12-21.desktop.production.log](https://github.com/desktop/desktop/files/2703804/2018-12-21.desktop.production.log)

**Comment by shiftkey** [comment]
@jslewis90 thanks for the report.

Can you run this command in the terminal to confirm you have the right global setting?

```
$ git config --global core.excludesfile
```

From the screenshot of `git status` it too doesn't seem to be detecting a global config, so maybe it's something environmental?

**Comment by jslewis90** [comment]
The output of that is `C:\Users\(my username)\.gitignore`

**Comment by jslewis90** [comment]
@shiftkey Huh. I guess the problem was that it wanted forward slashes instead of my backslashes.

**Comment by shiftkey** [comment]
@jslewis90 `gitignore` paths need to use `/` to represent directory separators because `\` is considered an escape character. Anyway, I'm glad you were able to get to the bottom of it!
