### ISSUE TITLE
publish fails with curl error "Send failure: Connection was aborted"

### ISSUE THREAD

**Issue by samhale** [desktop/desktop#6485]
## Description

As usual, you guys still are having issues.  I had hoped you had corrected most of your problems by now but I guess not.  I am trying to publish my branch and it is kicking back an error.  

Here is the error:

fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
error: RPC failed; curl 55 Send failure: Connection was aborted
Everything up-to-date

## Version
1.5.1
* GitHub Desktop:

* Operating system:
Windows 10 Pro

## Steps to Reproduce
All I had to do was publish
### Expected Behavior
Publish my project

### Actual Behavior
Error Message
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
error: RPC failed; curl 55 Send failure: Connection was aborted
Everything up-to-date

### Logs
[2018-12-23.desktop.production.log](https://github.com/desktop/desktop/files/2706063/2018-12-23.desktop.production.log)

**Comment by shiftkey** [comment]
There's a clue in here just before the error message:

```
Writing objects: 100% (6040/6040), 2.98 GiB | 893.00 KiB/s, done.
Total 6040 (delta 2491), reused 0 (delta 0)
```

It looks like Git had to send almost 3GB of data to the remote server as part of this `git push origin master`, which is likely related to the issue you're seeing.

The error itself doesn't provide much context, just that the connection was aborted:

```
RPC failed; curl 55 Send failure: Connection was aborted
```

Are you able to run the same command from the Git command line and see it fail there? If so, you could set some environment variable to potentially provides more diagnostic help about _why_ the connection is aborting.

```
# in Command Prompt
set GIT_TRACE=1
set GIT_CURL_VERBOSE=1
git [args go here]
```

My gut feeling is that a large file is unable to be sent to the remote server. Some people in this situation have had success by [tweaking the `http.postBuffer` Git config value](https://stackoverflow.com/questions/6842687/the-remote-end-hung-up-unexpectedly-while-git-cloning/27261854) but it's rather subjective so I can't say whether this will actually help your use case.

**Comment by samhale** [comment]
So basically what you are telling me is that your system can't handle a full size software project.  Is that basically what I am hearing here?

**Comment by samhale** [comment]
Do I need to just move everything back to Dropbox?  You know, I keep trying to use your system and it frustrates me and I leave and I come back hoping you have fixed your issues and every time I do I see you haven't.  This is will be my last time, we figure out away around this problem or I am gone forever.

**Comment by outofambit** [comment]
hi @samhale. it sounds like this is a problem with the server you are pushing to (or perhaps even your internet connection). are you trying to publish to github.com? or another server?

**Comment by samhale** [comment]
Github.com

 

Sammy Hale

R&D Director

AirMaint.net

**Comment by samhale** [comment]
Ok...I have now, even reduced the file size and I am still getting the same error.  I need this corrected or I want a refund and you can cancel my account.  And this time I will not be back, this is your last shot! My patients is now gone.  It is stuff like this that has made me leave your product, and every time you have no resolution.  So this will be your last shot with me.  Which I am sure, you really could care less.

**Comment by steveward** [comment]
@samhale I'm sorry for the frustration. When you say you reduced the file size -- did you delete them on disk AND delete them from the repository's history? If you only delete a file it will still remain in the repository's history unless you use a specific Git command or the BFG cleaner tool to clear the object from the history. You can read more about this in our [help article for removing large files](https://help.github.com/articles/removing-files-from-a-repository-s-history/).

It would be helpful if you could also run the commands that @shiftkey gave which will give us some more diagnostic information:

1. Go to `Repository` > `Open in command prompt` in GitHub Desktop
2. Run the following commands:

```
set GIT_TRACE=1
set GIT_CURL_VERBOSE=1
git push origin <branch>
```

Please let us know the output of those commands.

**Comment by steveward** [comment]
@samhale are you still encountering issues with pushing your repository from GitHub Desktop? Due to inactivity I am going to close this issue out in order to keep our number of open issues maintainable, but please let me know if you are continuing to have problems and we can keep investigating further.

**Comment by GillesC** [comment]
For future reference, I solved this issue by repacking:
`git repack --max-pack-size=100M -a -d`

**Comment by Gigasoft** [comment]
I had the same problem and the repack worked for me too. Thanks GillesC

**Comment by JuicyJannis** [comment]
It says that they couldn´t find the command "git"

**Comment by newcreativegamer** [comment]
You need to cd into your project folder and then run it

**Comment by Khalidmamdou7** [comment]
> For future reference, I solved this issue by repacking:
> `git repack --max-pack-size=100M -a -d`

I tried this, but it didn't work. 

I ran the commands mentioned above and here is the output 
```
17:00:38.289442 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
17:00:38.290441 git.c:418               trace: built-in: git push origin input
17:00:38.321775 run-command.c:643       trace: run_command: GIT_DIR=.git git remote-https origin https://github.com/Khalidmamdou7/Logic-Simulator-Project-PTF20---Team-22.git
17:00:38.338597 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
17:00:38.340591 git.c:675               trace: exec: git-remote-https origin https://github.com/Khalidmamdou7/Logic-Simulator-Project-PTF20---Team-22.git
17:00:38.340591 run-command.c:643       trace: run_command: git-remote-https origin https://github.com/Khalidmamdou7/Logic-Simulator-Project-PTF20---Team-22.git
17:00:38.460435 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
* Couldn't find host github.com in the _netrc file; using defaults
*   Trying 140.82.121.3...
* TCP_NODELAY set
* Connected to github.com (140.82.121.3) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=github.com
*  start date: May  5 00:00:00 2020 GMT
*  expire date: May 10 12:00:00 2022 GMT
*  subjectAltName: host "github.com" matched cert's "github.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
> GET /Khalidmamdou7/Logic-Simulator-Project-PTF20---Team-22.git/info/refs?service=git-receive-pack HTTP/1.1
Host: github.com
User-Agent: git/2.20.1.windows.1
Accept: */*
Accept-Encoding: deflate, gzip
Pragma: no-cache

* old SSL session ID is stale, removing
< HTTP/1.1 401 Authorization Required
< Server: GitHub Babel 2.0
< Content-Type: text/plain
< Content-Length: 21
< WWW-Authenticate: Basic realm="GitHub"
< X-Frame-Options: DENY
< X-GitHub-Request-Id: CB4D:7AEA:8EC65D4:CB9E691:5FEB4497
<
* Connection #0 to host github.com left intact
17:00:39.020759 run-command.c:643       trace: run_command: 'git credential-manager get'
17:00:39.158051 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
17:00:39.159063 git.c:675               trace: exec: git-credential-manager get
17:00:39.159063 run-command.c:643       trace: run_command: git-credential-manager get
* Found bundle for host github.com: 0x2ea6b50 [can pipeline]
* Could pipeline, but not asked to!
* Re-using existing connection! (#0) with host github.com
* Connected to github.com (140.82.121.3) port 443 (#0)
* Server auth using Basic with user 'Personal Access Token'
> GET /Khalidmamdou7/Logic-Simulator-Project-PTF20---Team-22.git/info/refs?service=git-receive-pack HTTP/1.1
Host: github.com
Authorization: Basic UGVyc29uYWwgQWNjZXNzIFRva2VuOmI0MDRmZTY4ZDVmNWNkYTQwZWRiMzg4ZTBlNDEyNDg3MTFhZDhlYTY=
User-Agent: git/2.20.1.windows.1
Accept: */*
Accept-Encoding: deflate, gzip
Pragma: no-cache

< HTTP/1.1 200 OK
< Server: GitHub Babel 2.0
< Content-Type: application/x-git-receive-pack-advertisement
< Transfer-Encoding: chunked
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Vary: Accept-Encoding
< X-Frame-Options: DENY
< X-GitHub-Request-Id: CB4D:7AEA:8EC66A4:CB9E6CC:5FEB4497
<
* Connection #0 to host github.com left intact
17:00:40.579031 run-command.c:643       trace: run_command: 'git credential-manager store'
17:00:40.632190 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
17:00:40.633188 git.c:675               trace: exec: git-credential-manager store
17:00:40.633188 run-command.c:643       trace: run_command: git-credential-manager store
17:00:40.890119 run-command.c:643       trace: run_command: git send-pack --stateless-rpc --helper-status --thin --progress https://github.com/Khalidmamdou7/Logic-Simulator-Project-PTF20---Team-22.git/ --stdin
17:00:40.907849 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
17:00:40.908848 git.c:418               trace: built-in: git send-pack --stateless-rpc --helper-status --thin --progress https://github.com/Khalidmamdou7/Logic-Simulator-Project-PTF20---Team-22.git/ --stdin
17:00:40.914109 run-command.c:643       trace: run_command: git pack-objects --all-progress-implied --revs --stdout --thin --delta-base-offset --progress
17:00:40.930910 exec-cmd.c:236          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
17:00:40.934905 git.c:418               trace: built-in: git pack-objects --all-progress-implied --revs --stdout --thin --delta-base-offset --progress
Enumerating objects: 71, done.
Counting objects: 100% (71/71), done.
Delta compression using up to 8 threads
Compressing objects: 100% (25/25), done.
Writing objects: 100% (39/39), 818.59 KiB | 90.95 MiB/s, done.
Total 39 (delta 21), reused 32 (delta 14)
* Found bundle for host github.com: 0x2ea6b50 [can pipeline]
* Could pipeline, but not asked to!
* Re-using existing connection! (#0) with host github.com
* Connected to github.com (140.82.121.3) port 443 (#0)
* Server auth using Basic with user 'Personal Access Token'
> POST /Khalidmamdou7/Logic-Simulator-Project-PTF20---Team-22.git/git-receive-pack HTTP/1.1
Host: github.com
Authorization: Basic UGVyc29uYWwgQWNjZXNzIFRva2VuOmI0MDRmZTY4ZDVmNWNkYTQwZWRiMzg4ZTBlNDEyNDg3MTFhZDhlYTY=
User-Agent: git/2.20.1.windows.1
Accept-Encoding: deflate, gzip
Content-Type: application/x-git-receive-pack-request
Accept: application/x-git-receive-pack-result
Content-Length: 838397

< HTTP/1.1 200 OK
< Server: GitHub Babel 2.0
< Content-Type: application/x-git-receive-pack-result
< Transfer-Encoding: chunked
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Vary: Accept-Encoding
< X-Frame-Options: DENY
< X-GitHub-Request-Id: CB4D:7AEA:8EC6738:CB9E828:5FEB4499
<
* OpenSSL SSL_write: SSL_ERROR_ZERO_RETURN, errno 10053
* Closing connection 0
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
error: RPC failed; curl 55 OpenSSL SSL_write: SSL_ERROR_ZERO_RETURN, errno 10053
Everything up-to-date
```

**Comment by munish-garg** [comment]
I am getting the same error and I am not able to resolve this by the use of any of the comments mentioned above. Kindly help me!!!

**Comment by DS-Meena** [comment]
**error: RPC failed; curl 55 Send failure: Connection was aborted
fatal: the remote end hung up unexpectedly**

me also getting same error while using github desktop. 
How we can sole this error in github desktop.

**Comment by steveward** [comment]
@28-08-2000 are you working with a large repository? Normally this error is the result of timeouts from a poor connection or from attempting to push a large repository.

**Comment by AhmadIzaz** [comment]
I am also facing this while uploading 30MB file on git. I dont know why I am facing this as 30MB should not be an issue here but stucked with this for almost a day.

**Comment by Wise-II** [comment]
same thing but with a 77MB repo

**Comment by PavelPZ** [comment]
## same error with two 1.3 MB files

I am not able to resolve this by the use of any of the comments mentioned above
