### ISSUE TITLE
Github won't install on Windows 10 Home

### ISSUE THREAD

**Issue by joshua-deason** [desktop/desktop#6487]
<h3>The squirrel thingy</h3>

[SquirrelSetup.log](https://github.com/desktop/desktop/files/2706613/SquirrelSetup.log)

<h3>The Problem</h3>
I get to the screen saying that it will open when finished but then it stops and sends me to that Squirrel Log

<h3>Side info</h3>
I am currently on RCA Cambio 10.1 using Windows 10 Home

**Comment by shiftkey** [comment]
> 2018-12-23 21:11:34> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: The specified executable is not a valid application for this OS platform.


@joshua-deason this message suggest you're on Windows 32-bit, which isn't currently supported by GitHub Desktop - see #1214 for more details. Can you confirm this is the case?

**Comment by shiftkey** [comment]
@joshua-deason thanks for confirming. We're not currently planning to support 32-bit Windows, and the details in that issue provide more context about that.
