### ISSUE TITLE
cannot complete authentication flow due to "407 Proxy Authentication Required"

### ISSUE THREAD

**Issue by scsfdev** [desktop/desktop#6488]
**Description**
Cannot log into to GitHub Desktop client.
When I type in my User ID and Password and click on "Sign in" button, not logging me in.
When I use "Sing in using your browser", it will launch my Chrome browser and will try to sign in but gave me "Unable to fetch authenticated user." error message.

**Version**
GitHub Desktop: v 1.5.1
PC OS: Windows 7 Pro 64 bit

**Steps to Reproduce (1)**
1. Open GitHub Desktop
2. Click on "Sign into GitHub.com"
3. Key in User ID and PWD
4. Sign in
5. Fail.

**Steps to Reproduce (2)**
1. Open GitHub Desktop
2. Click on "Sign into GitHub.com"
3. Click on "Sign in using your browser"
3. Open browser with "https://github.com/login/oauth/authorize?client_id=...." URL and application will try to sign in.
4. Fail.

**Additional Info**
I am behind a corporate Proxy. I already input http and https proxy info in gitconfig file (follow this guide --> https://stackoverflow.com/a/20371843).
I also set Environment variables for both HTTP and HTTPS proxy.
I can log into from browser (through Chrome) with no issue.

I have tried Ctrl + Shift + I and saw the error message saying "net::ERR_TUNNEL_CONNECTION_FAILED" and "Status 407 error" when I use Sing in from browser function. 407 means Proxy issue but my gitconfig already have the proxy, so I am bit confuse on which one is not correct.

I also checked ticket #3117 and #2769, but not able to solve my issue.
Please advise me on where did I do wrong.
Thanks.

**Comment by scsfdev** [comment]
> hi @scsfdev i'm sorry you're hitting this! Take a look at the workaround in [#2789 (comment)](https://github.com/desktop/desktop/issues/2789#issuecomment-330751117). If that doesn't help, please let us know!

Hi @outofambit , I tried and already have the info in .gitconfig file.
Below is the data from my config file.

````
[user]
    name = 
    email = 
[core]
	autocrlf = true
[filter "lfs"]
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
	clean = git-lfs clean -- %f
[http]
	proxy = http://domain\userID:pwd@IPAddress:8080
[https]
	proxy = http://domain\userID:pwd@IPAddress:8080
````

Sorry if I do not configure it correctly. This is my first time using Git and GitHub for the code repository and I still have a very long way of learning.
Thanks.

**Comment by steveward** [comment]
@scsfdev setting your proxy in the .gitconfig will only allow Git to authenticate to your proxy -- it won't help with authenticating to your GitHub account from GitHub Desktop. Have you set your system-wide proxy on your Windows machine? If you have a system-wide proxy set up correctly that should allow GitHub Desktop to authenticate.

**Comment by steveward** [comment]
@scsfdev thanks for the update. If your system-wide proxy is set correctly then you should be able to authenticate in GitHub Desktop. Is there a network administrator you can contact who may be able to provide some more information about why your proxy may still be prohibiting you from logging in to Github Desktop?

Have you also tested if cloning works via the command line?

**Comment by scsfdev** [comment]
@steveward, thanks for your support.
I tried from Git Bash and I saw 407 error too. I read around and test a few times and managed to solve it by removing Domain name from the proxy (both my system wide Environment variable proxy and .gitConfig file). I directly use user name and password. I can clone from git bash with no issue now.

But GitHub Desktop still give me the same error message of "Status 407, length '(missing)' id: '(missing)'

**Comment by gabbiano69** [comment]
sorry I can not access github desktop, because I use a proxy in the company where I work, you could download, https: //github.com/alexa/skill-sample-nodejs-audio-player/tree/mainline/single- stream with npm run npm and zip it and post it here, I'm too urgent thanks, you would do me a big favor, thanks in advance

**Comment by steveward** [comment]
@gabbiano69 you can find steps to configure your proxy in GitHub Desktop in https://github.com/desktop/desktop/issues/2789#issuecomment-330751117. Let me know if you have any issues with that.

If you just need to download that repository as a zip you can go to the repository's page and click the green `Clone or download` button and select `Download zip`.

**Comment by gabbiano69** [comment]
thanks, anyway if i download with download a zip , this file it's not good to put in lambada aws?

**Comment by steveward** [comment]
> thanks, anyway if i download with download a zip , this file it's not good to put in lambada aws?

@gabbiano69 the zip download contains all of the repository files except for the `.git` directory. If you require the repository's history you will need to perform a full clone of the repository.

**Comment by steveward** [comment]
> than what can i do? i have a proxy and i can't use nodej and git . can you please clone and run npm ad zip the files that i need to put to lambda aws for me please i nedd it. thanks in advance

@gabbiano69 you should be able to build the project if you download the zip file of that repository. If you are having specific problems with that I would recommend opening up an issue in the repository's issue tracker.

@scsfdev are you still having issues using GitHub Desktop behind your proxy?

**Comment by steveward** [comment]
@scsfdev I am going to close this issue out since it has been a while since you last replied. If you are still having problems authenticating to GitHub Desktop, please let me know! 

You can follow along in https://github.com/desktop/desktop/issues/2789 for updates about GitHub Desktop providing better support for configuring proxies.

**Comment by NotAProfessionalDeveloper** [comment]
Neither using .gitconfig nor the corresponding Git command make it use the proxy.

```
[http]
	proxy = http://user:pass@proxy.example.com:80
[https]
	proxy = http://user:pass@proxy.example.com:80
```
(Yes the last line is correct, we are using HTTP CONNECT to tunnel HTTPS across the HTTP connection)

The connection to the proxy is made but a 407 is returned because no credentials are sent. (There is no Proxy-Authorization: header at all in the request to the proxy.)
