### ISSUE TITLE
Problem Adding Xcode Project to Repo

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#6493]
## Description

GitHub Desktop is not letting me push an Xcode project to my repo.

## Version

* GitHub Desktop:

* Operating system: High Sierra 10.13.6

## Steps to Reproduce

1. Create a GitHub repo using Github Desktop
2. Add some files to it and some folders
3. Try to push an entire Xcode project

### Expected Behavior

The code is pushed to master

### Actual Behavior

See screenshot: It does not work because it is outputting "error code 1"

## Additional Information

<img width="957" alt="screen shot 2018-12-26 at 11 21 21 am" src="https://user-images.githubusercontent.com/45888860/50451170-69220d00-0900-11e9-8f64-c42727c1fe71.png">

### Logs

Could not find

**Comment by steveward** [comment]
@SafelySwift thanks for the report! Some users have [run into this error](https://github.com/desktop/desktop/issues/3701#issuecomment-375905661) due to having nested .git directories. Can you try searching your repository to see if you have multiple .git directories?

**Comment by SafelySwift** [comment]
I actually just made another repo for the app and gave a redirect in my main projects README
