### ISSUE TITLE
Add a File menu keyboard shortcut for program Exit

### ISSUE THREAD

**Issue by jsimmonds2** [desktop/desktop#6507]
I'm a keyboard-shortcuts kind-of-guy so a **File Menu** shortcut to **Exit** would be lovely (-:

At the moment, for me, it's an `<Alt>-F ; <Up-Arrow> ; <Enter>` affair.

Thanks
[GitHub Desktop 1.5.1 on Windows 10 (Intel x86_64)]

**Comment by shiftkey** [comment]
@jsimmonds2 thanks for the report! I think you'll be interested in this PR: #5378

**Comment by jsimmonds2** [comment]
Thanks for revealing that PR . . I'll remember to search over Issues **and** PRs next time.

**Comment by shiftkey** [comment]
Moving this back to `Available` because #5378 was abandoned

**Comment by AndreiMaga** [comment]
Opened a pull request for this #7508.
