### ISSUE TITLE
2-Up / Comparison of Wide Images are cut off

### ISSUE THREAD

**Issue by AndyThePie** [desktop/desktop#6514]
**The 2-up of wide images in GitHub Desktop can have the second image cut off.**

![image](https://user-images.githubusercontent.com/25379179/50553851-aa5a4a00-0c7d-11e9-9660-37108865d1e7.png)
Here, there are two images, however, due to the width of the first, the second is off-screen.

**Do you have any potential solutions in mind?**
My own thoughts: You could add a horizontal scroll bar, scale down both of the images, or possibly have them appear vertically (top to bottom) instead.

**Comment by shiftkey** [comment]
@AndyThePie thanks for the report! 

Having the horizontal scrollbar appear seems reasonable as a workaround, but I do like the "make them appear vertically" option as a more robust solution.

**Comment by shiftkey** [comment]
@AndyThePie I'm trying to reproduce the issue and I went back to my sample here https://github.com/desktop/diff-tests/commit/854ba7f0ffd7646b7b91c0197d056b5261241544

Opening this up in the latest Desktop looks like this, with the scaling being applied:

<img width="1440"  src="https://user-images.githubusercontent.com/359239/50562598-83d2f800-0ceb-11e9-8c72-e5de0efff807.png">

Are you able to put together a public commit containing the image change that's not working for you, so I can test what you're seeing?

**Comment by AndyThePie** [comment]
I'm not completely sure what you mean by "public commit," but I'll try my best:
I believe what I mean by "width" is the aspect ratio of the two images. Since the two images I used in my screenshot have wider aspect ratios (8:3 and 2:1) this causes the images to go offscreen.

Forking your repository, I recreated the result with two images with the same resolution as the ones used in the screenshot. https://github.com/AndyThePie/diff-tests/commit/215ea0ff1cc208105805cd9d07e64946159f6b53
![image](https://user-images.githubusercontent.com/25379179/50568820-a8e45c80-0d25-11e9-99a9-dde7047ece67.png)

The commit that led to the original screenshot can be found here: https://github.com/AndyThePie/pizzaRPG-repo/commit/0233f1c56771ddf2d72f71c800d3f2ac86ef18ed (logo.png)

**Comment by shiftkey** [comment]
@AndyThePie thanks for the repo which illustrates the issue. I was able to reproduce it **on Windows** - I thought the same behaviour would be there for macOS too but I guess that was the difference.

**Comment by shiftkey** [comment]
I just realised this was already captured in #2480 and I'm going to add the `windows` label to that issue as I think Windows has been the common factor in both that issue and this one.

Please follow along with the original issue @AndyThePie!
