### ISSUE TITLE
cant sign into the pc . its shut down for some reason

### ISSUE THREAD

**Issue by crazymaribell** [desktop/desktop#6527]
**Please describe the problem you think should be solved**
A clear and concise description of what the problem is and who else might be impacted. Screenshots are encouraged.

Example:

> “When I run into a merge conflict, I don’t know where to go to resolve it. Anyone who works off of multiple branches will likely run into this problem at least occasionally.”

**[Optional] Do you have any potential solutions in mind?**
A clear and concise description of one or more solutions you think might solve the problem. Please include any considered drawbacks or tradeoffs, and how users might use your solution(s). Screenshots or mockups are helpful here!

**Comment by crazymaribell** [comment]
pc i was using shut down. still wont start. lost everything. someone stealing everything

**Comment by crazymaribell** [comment]
i am not a computer person. im 50 and really dont wanna relearn life all over. i have already started to relearn everything. but 1,000,000,000,000 things at once. imposible

**Comment by steveward** [comment]
@crazymaribell this issue tracker is for GitHub Desktop -- are you specifically having problems signing into the GitHub Desktop application with your GitHub account? 

If you are having issues logging in to an account on your computer I would recommend reaching out to [Microsoft support](https://support.microsoft.com/en-us) or [Apple support](https://support.apple.com/) for assistance.

**Comment by steveward** [comment]
@crazymaribell I'm going to close this issue out due to inactivity -- this helps keep our open issues maintainable. If you are having any problems logging in to GitHub Desktop please let us know. I'd be happy to help further.

**Comment by crazymaribell** [comment]
I can't sign in. The pc I was using says albivor and won't turn on
