### ISSUE TITLE
Light theme: top bar still dark

### ISSUE THREAD

**Issue by axelvugts** [desktop/desktop#6529]
**Please describe the problem you think should be solved**
The top bar of the new (non native) Github Desktop app is dark, even though Dark Mode is not enabled.

**[Optional] Do you have any potential solutions in mind?**
Change the top bar to a lighter color when Dark Mode is not active.

**Comment by shiftkey** [comment]
@axelvugts thanks for the feedback!

We've had a couple of discussions about this area in #3189 and #2062 and I think for the moment we settled on keeping the current colour scheme - we want that top bar to stand out from the rest of the app.

**Comment by niik** [comment]
@axelvugts Thanks for opening this! As @shiftkey said the dark title- and toolbar are deliberate parts of the design of the application and for the time being we don't have any plans to redesign that aspect of the app. As such I'm going to close this issue but know that your feedback has been noted.

**Comment by bartonnen** [comment]
Closed - but anyway. 

"we want that top bar to stand out from the rest of the app." - fair enough. But, what about getting the top bar to standout from any windows behind it. If I have Visual Studio in dark theme and Github Desktop on top of it - it's _very_ difficult to spot and click on the tool bar, I often click on VS instead, and then GD just disappears behind. _(Not everyone had dual monitors)_
