### ISSUE TITLE
unable to copy path when viewing conflicted files (ellipses hide details)

### ISSUE THREAD

**Issue by zmechanic** [desktop/desktop#6537]
**GitHub Desktop merge conflicts window is useless to help find files**
GitHub Desktop merge conflicts window shows ellipsis and have no link to copy full file path. 

Example:

> I don't use Atom and don't want to install it. I want to use my own editor.

**Potential solution**
Please provide button to copy full path next to each conflict right after ellipsis.
Or, allow to configure another text editor instead of Atom. You can already open command prompt, opening another text editor (I can use my Notepad++) is as easy.

**Comment by shiftkey** [comment]
@zmechanic thanks for the feedback! Can you add a screenshot of the dialog illustrating the issue for reference?

> (I can use my Notepad++) 

I was going to ask what your editor of choice was in the hope that we'd be able to support it, but it doesn't currently support "Open Workspace" from the command line so we had to close #4120.

But this is being tracked upstream at https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4253 so if they get that working and into an update maybe we can revisit it.

**Comment by shiftkey** [comment]
Tagging `user-research` here because I don't recall any discussions about being able to copy the relative/full path of a file from the merge conflicts dialog, and I'd like to figure out the value of supporting it.

**Comment by billygriffin** [comment]
I'm going to close this since we shipped an improvement to the modal in #6666, and because we haven't heard this specific request come up again since our release nearly a year ago. Thanks for the issue!
