### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by dkowalec** [desktop/desktop#6538]
## Description

Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open preferences and verify that you're signed in with an account that has permission to access this repository.

## Version

* GitHub Desktop: 1.5.1

* Operating system: macOS High Sierra 10.13.6

## Steps to Reproduce

1. Add repository to GitHub Desktop by local patch
2. Select Fetch origin
### Expected Behavior

Fetch repo, using same credentials retrieving anothe private repo which works fine.
### Actual Behavior

Getting an authentication failed error which is stated in the description. Is this possible due to the SSH key having a passphrase? Weird as one private repo works fine but newly created repo does not. I tested through command line and no error occurs.

## Additional Information

**Click on fetch**
![image](https://user-images.githubusercontent.com/45953408/50715127-b4979200-1049-11e9-8ffa-db80bcc711e0.png)
**Error Prompt**
![image](https://user-images.githubusercontent.com/45953408/50715095-96ca2d00-1049-11e9-94ba-f17b1ade98b6.png)

**Comment by shiftkey** [comment]
@dkowalec thanks for the report!

>  Is this possible due to the SSH key having a passphrase? 

Perhaps - is this an SSH remote or a HTTPS remote? The `.git/config` for the repository should contain this information.

Also, could you attach the full log files? The **Help** | **Show Logs in Finder** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by FlameOfIgnis** [comment]
Im having the same issue so i would like to add it here.
## Version

GitHub Desktop: 1.5.1
Operating system: Windows 10 10.0.17134

## Problem 

Can't fetch/pull/push from ssh repositories with passphrases.
ssh key is added to ssh-agent, and using git commands from cmd will not ask for passphrase, and will work correctly.
Using git GUI will work as intended, popping up a passhprase dialog.
However, Github Desktop will still fail at authentication when fetching/pulling/pushing the same repository.

Adding another ssh key for same repository without passphrase works.

### Sidenotes
Private keys are under username/.ssh 
i tried:
- Just using ssh-add file
- using ssh-agent -s then using ssh-add file
- using start-ssh-agent

**Comment by billygriffin** [comment]
@desktop/support Any thoughts here?

**Comment by dkowalec** [comment]
> @dkowalec thanks for the report!
> 
> > Is this possible due to the SSH key having a passphrase?
> 
> Perhaps - is this an SSH remote or a HTTPS remote? The `.git/config` for the repository should contain this information.
> 
> Also, could you attach the full log files? The **Help** | **Show Logs in Finder** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

Yes, the git config setup with the repo using **https works** but the git repo setup to use **ssh w/ rsa w/ passphrase does not work** using GitHub Desktop. How can we fix this as we require a passphrase to be HIPPA compliant when connecting? Otherwise, I will need to continue to use SourceTree as that works just fine.

> HTTPS _(works)_
`[remote "origin"]
	url = https://github.com/organization-name/repo-name.git
	fetch = +refs/heads/*:refs/remotes/origin/*
`

> HTTPS _(does not work)_
`[remote "origin"]
	url = git@github.com:organization-name/repo-name.git
	fetch = +refs/heads/*:refs/remotes/origin/*
`

**Comment by shiftkey** [comment]
This feels very familiar to #5641, where someone wanted to use an external SSH setup but GitHub Desktop would favour it's own internal version. They could change this behaviour via the `core.sshCommand` config value: https://github.com/desktop/desktop/issues/5641#issuecomment-421801704

**Comment by yalanzhi** [comment]
Im having the same issue so i would like to add it here.

## Version

GitHub Desktop: 1.5.1
Operating system: macOS Mojave 10.14.2

## Problem

Can't fetch private repos from my account. Always pop-ups an additional authentication window, but nothing happens.

## Sidenotes

Public repos fetched without any problems. Changing repo from private to public also kinda solved this problem. Accessing any repos at website without any troubles. 

## Logs

2019-01-08T15:33:05.163Z - info: [ui] storing generic credentials for 'github.com' and '***@gmail.com'
2019-01-08T15:33:05.265Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/***/***.git - *** (has token)
2019-01-08T15:33:07.369Z - info: [ui] Executing clone: git -c credential.helper= clone --recursive --progress -- https://github.com/***/***.git /Users/***/***/*** (took 2.101s)
2019-01-08T15:33:07.369Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://github.com/***/***.git /Users/***/***/***` exited with an unexpected code: 128.
Cloning into '/Users/***/***/***'...
remote: Your account is disabled. Please see https://github.com/account/billing
fatal: unable to access 'https://github.com/***/***.git/': The requested URL returned error: 403

(The error was parsed as 3: Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open preferences and verify that you're signed in with an account that has permission to access this repository.)

**Comment by shiftkey** [comment]
@yalanzhi 

> `remote: Your account is disabled. Please see https://github.com/account/billing`

**Comment by steveward** [comment]
@yalanzhi I've gone ahead and unlocked your account. Let me know if you run into any issues.

**Comment by dkowalec** [comment]
So the issue seems to be using SSH w/ passphrases and private repositories for my case.
@desktop/support

**Comment by dkowalec** [comment]
> @dkowalec thanks for the report!
> 
> > Is this possible due to the SSH key having a passphrase?
> 
> Perhaps - is this an SSH remote or a HTTPS remote? The `.git/config` for the repository should contain this information.
> 
> Also, could you attach the full log files? The **Help** | **Show Logs in Finder** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

I think the additional information here is sufficient enough at this point don't you think?
@shiftkey

**Comment by shiftkey** [comment]
@dkowalec please see my earlier comment https://github.com/desktop/desktop/issues/6538#issuecomment-452307176

**Comment by shiftkey** [comment]
>  I never confused SourceTree it works from install. I just point to the repo and that's it.

@dkowalec do you have Sourcetree's Git pointing to it's embedded Git or to a system Git? If it's using the system Git, that would explain why it's working the same as the Git command line (it knows how to find the running `ssh-agent` process):

<img width="722" src="https://user-images.githubusercontent.com/359239/51136347-a3e9d780-1812-11e9-88c0-380146121af1.png">

> Can we assume the workaround listed for Windows also applies to Mac client version of GitHub Desktop?

I believe `core.sshCommand` works wherever Git and SSH work.

**Comment by dkowalec** [comment]
I can try the workaround but it seems SourceTree is using the Embedded Git same as yours but 2.15.1 and yours is 2.18.0
@shiftkey 
![image](https://user-images.githubusercontent.com/45953408/51137080-07bcd200-180c-11e9-944e-124119857afe.png)

**Comment by shiftkey** [comment]
@dkowalec interesting. Anything SSH-specific in your `~/.gitconfig` that we might not be aware of?

**Comment by dkowalec** [comment]
> @dkowalec interesting. Anything SSH-specific in your `~/.gitconfig` that we might not be aware of?

Doubtful. It is pretty basic, standard install; haven't messed with it. Please let me know any other data you need I am more than happy to provide
@shiftkey 
> cat ~/.gitconfig
```
[user]
	name = Daniel Kowalec
	email = myemail@mydomain.com
[core]
	excludesfile = /Users/dkowalec/.gitignore_global
	autocrlf = input
[difftool "sourcetree"]
	cmd = opendiff \"$LOCAL\" \"$REMOTE\"
	path = 
[mergetool "sourcetree"]
	cmd = /Users/dkowalec/Applications/Sourcetree.app/Contents/Resources/opendiff-w.sh \"$LOCAL\" \"$REMOTE\" -ancestor \"$BASE\" -merge \"$MERGED\"
	trustExitCode = true
[commit]
	template = /Users/dkowalec/.stCommitMsg
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
```

**Comment by sorashi** [comment]
I'm having the same issue. GitHub Desktop version 1.6.0, Windows 10.
When the repo's remote is SSH, GitHub Desktop shows the *authentication failed* message on fetch/pull/push.
I tried setting up `ssh-agent` and `ssh-add`ing my keys, but the error persists. (I do usually type my SSH password every time I use my SSH key(s) in Git Bash, because I'm quite paranoid.)

Changing the remote to HTTPS – either using the GH Desktop UI or using the `git remote set-url origin` command – fixes the issue, as GH Desktop can use the GitHub credentials to connect.

**Comment by sorashi** [comment]
> @sorashi it sounds like you may need to use the workaround that @shiftkey shared in [#5641 (comment)](https://github.com/desktop/desktop/issues/5641#issuecomment-421801704) to use the system Git for SSH. Try following those steps to see if it resolves this issue.

@steveward, thank you very much, the solution works.

**Comment by tierninho** [comment]
This issue appears to be resolved. Happy to reopen if there are any other concerns.

**Comment by jcornelius** [comment]
Maybe I've missed something in all the other discussion, but nothing here seems to address the issue for me. 

#### Environment

Mac OS Catalina 10.15.2
Github Desktop 2.2.4

Fresh upgrade from legacy version of Github Desktop where everything worked fine. The authentication issue has been the same no matter what I've tried. 

**Sequence of things I've done.**

- I first added the repo from my hard drive as that seemed the easiest way to go.
- Logged out and logged in again using username/password in the app
- Logged out and logged in using the browser
- Deleted old SSH Key from my profile on `https://github.com/settings/keys`
- Deleted local copy of repo and attempted to clone new copy from Github
- Restarted the computer
- Logged out & in again using both authentication methods
- Tried to clone both public and private repos

Nothing changes. I get this message every time.

<img width="613" alt="Screenshot 2020-01-10 13 26 22" src="https://user-images.githubusercontent.com/366136/72176641-cf16f080-33ac-11ea-8295-bafb25c66719.png">

Here's what's in the log from the last attempt. It's the same message regardless of which repo I attempt to clone.

```
2020-01-10T18:15:24.525Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/ninelabs/loopsbook.git - jcornelius (has token)
2020-01-10T18:15:25.034Z - error: [ui] `git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/ninelabs/loopsbook.git /Users/jc/Web Projects/loopsbook` exited with an unexpected code: 128.
stderr:
Cloning into '/Users/jc/Web Projects/loopsbook'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

Anyone have ideas on how to resolve this?

**Comment by AlexSchaeferBs** [comment]
Unfortunately i have the exact same behavior with my MAC version of GitHub Desktop 2.3.1. The workaround only describes solutions for WIN PCs.

I tried both ways: "Publishing" a repository from the GitHub Desktop App runs an authentification error as well as Trying to "Set Up in Desktop" from the WebApp.

BTW: Billing says, my account is fine.

**Comment by tierninho** [comment]
@AlexSchaeferBs Please fill a new issue and if possible, include your logs. Thank you!

**Comment by AlexSchaeferBs** [comment]
> Unfortunately i have the exact same behavior with my MAC version of GitHub Desktop 2.3.1. The workaround only describes solutions for WIN PCs.
> 
> I tried both ways: "Publishing" a repository from the GitHub Desktop App runs an authentification error as well as Trying to "Set Up in Desktop" from the WebApp.
> 
> BTW: Billing says, my account is fine.

Just solved: Might have been caused by me changing my GitHub user name before. I used GitHub desktop with a previous user name. After logging out, deinstalling, reinstalling an logging in. The issue was fixed.
