### ISSUE TITLE
Pushing to a forked repository fails

### ISSUE THREAD

**Issue by kwon0408** [desktop/desktop#6545]
## Description
I have forked a public repository and fetched the forked one in my account. And then I made some edits on the local files and tried to push them to my forked repository but it failed.

## Version
* GitHub Desktop: 
1.5.1
* Operating system:
Windows 10 ver. 1809 build 17763.195

## Steps to Reproduce
1. Fork a public repository
2. Clone the forked repository ("the repo") using GitHub Desktop
3. Edit some files 
4. Open GitHub Desktop, and select the repo
4. Click "Push origin"

### Expected Behavior
A successful push, just as like pushing to a repo made by myself.

### Actual Behavior
Not pushed, but just an error message dialog comes out.
> Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.

## Additional Information
The dialog looks like this: https://imgur.com/a/7KUwTWe

Original repository: https://github.com/SlimeKnights/TinkersConstruct
My fork: https://github.com/kwon0408/TinkersConstruct

### Logs
[2019-01-07.desktop.production.log](https://github.com/desktop/desktop/files/2734229/2019-01-07.desktop.production.log)
(The current time is ~6AM KST but the logs seem to be aligned in UTC so this is my most recent log)

**Comment by outofambit** [comment]
Hi @kwon0408 ! Thanks for filing this issue. I'm sorry you're having trouble with GitHub Desktop. From the logs, it looks like something is wrong with your user authentication. Are you able to push to any of your other repos from GitHub Desktop?

**Comment by kwon0408** [comment]
At first moment I tried to push to one of my repos and it failed with the same symptom. But after I signed out from the app and signed in again, it worked. And pushing the fork repo was also successful.

Now I think the problem is related to sign-in features, rather than whether the target repo is forked from others or not...

**Comment by steveward** [comment]
I'm glad to hear things are working for you now @kwon0408. I'm going to close this issue out.
