### ISSUE TITLE
ask user to resolve rebase conflicts before continuing

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#6548]
Much like the work around handling merge conflicts, this issue is about ensuring the app correctly detects the user is in a rebase (and that conflicts were found) and asks the user to resolve these before continuing.

The mocks for this can be seen in this comment: https://github.com/desktop/desktop/issues/5953#issuecomment-437527414

TODO:

- [x] when an error occurs that indicates a rebase is occurring, show the dialog
- [x] when `git status` detects that a rebase is in progress, verify the dialog is shown
- [x] show the list of files and indicate what needs to be addressed (ala merge conflicts)
- [x] let the user abort the rebase
- [x] when there are no more things to resolve, let the user continue the rebase

**Comment by tierninho** [comment]
@shiftkey I noticed when you abort a fixed conflicted file in a merge commit, there is no "are you sure" check like we have in the existing merge flow. Is this needed for rebasing?

<img width="451" alt="screen shot 2019-02-28 at 3 42 13 pm" src="https://user-images.githubusercontent.com/14828183/53610583-8331d300-3b6f-11e9-9152-c1df99cd7bb4.png">

**Comment by shiftkey** [comment]
> Is this needed for rebasing?

We didn't talk about this in the scope of 1.6.3, but there's a rebase workflow where you might want to confirm this that we could consider:

 - you plan to rebase a very old branch
 - you see that there's likely to be lots of commits and lots of conflicts to work through, but you decide to march on
 - at some point after dealing with multiple resolved conflicts you mistakenly press `Abort rebase`
 - you're put back to the state before the rebase, and you'll likely have to redo the rebase again if you want to put that branch on top of the latest changes

@billygriffin does this case motivate you to have an equivalent "Confirm abort rebase" dialog on our roadmap?

**Comment by billygriffin** [comment]
@shiftkey I think I'd generally be inclined to have a confirm on abort only if they've already resolved some subset of conflicts already (which is @tierninho's use case). In that case, by aborting you're effectively losing work, so my preference would be that this should exist.

**Comment by shiftkey** [comment]
> In that case, by aborting you're effectively losing work, so my preference would be that this should exist.

Keep in mind that you could encounter conflicts multiple times as part of a rebase flow, so the "lost work" can be more than just the scope of a single "resolve commits" step.

I've opened https://github.com/desktop/desktop/issues/6989 to track this for `1.7.0`.
