### ISSUE TITLE
Feature Request Project Board in Github Desktop

### ISSUE THREAD

**Issue by Louis-Cypher** [desktop/desktop#6564]
**Please describe the problem you think should be solved**
Github Project Page is my clear favorite for my personal Kanban. Sadly the world is much less connected then most people think ;-) which makes it unusable for people travelling as much as I do.

 Hence, I'd really appreciate to be able to use the Github (Enterprise) project Page offline in Github Desktop. Even Read Only would help a lot. 

**[Optional] Do you have any potential solutions in mind?**
Handle the Project Page like a repository and integrate a viewer/ Editor in Github- Desktop. If the Downloaded file is Human readable this would be a good workaround for me already.

**Comment by billygriffin** [comment]
Hi @Louis-Cypher, thanks for the idea and that makes total sense. We recently responded to a similar request [here](https://github.com/desktop/desktop/issues/1867#issuecomment-448791261). Your use case is interesting in that it's specifically related to being disconnected from the internet. If we continue to hear more evidence that this would be widely beneficial for folks, we're totally open to reconsidering our stance but for now it still doesn't feel like something that contributes significantly to most folks' local workflows. Thanks again for the idea and explaining how the lack of projects incorporation when offline is problematic for you, it really helps to frame the problem in that way.

**Comment by MehdiCHEBBAH** [comment]
Any updates on this feature?

**Comment by matheus-kirchesch-old** [comment]
I agree, this would be great

**Comment by alexugthub** [comment]
I was recently looking into something similar. I expect to be offline from time to time and I would like to still be able to see my issues and project notes even if disconnected.
I am thinking about using the GitHub API and create an Electron app specially for this thing

**Comment by BrendaHutchinson** [comment]
Think would be a great idea, the more we can help the world with obstacles the easier it will be for all exspacaly beginners like me

**Comment by ohlmic** [comment]
PLEASE add this feature, would be so beneficial to have the board functionality in the desktop app.

**Comment by xzyriel** [comment]
please add it. i might then consider to only move to github like others told me too

**Comment by aborsato** [comment]
+1

**Comment by getgolden** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by Maamoon-Saleh** [comment]
+1

**Comment by Alexander-Jordan** [comment]
+1

**Comment by v-Woody** [comment]
+1
