### ISSUE TITLE
Clone repo dialog does not clone selected repo when Enter key is pressed

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#6570]
## Description
Pressing enter key on a selection in the Clone Repository dialog does not start cloning.

Related issues:
* #5234

## Version
* GitHub Desktop: 1.5.2-beta0
* Operating system: macOS 10.14.2

## Steps to Reproduce

1. Open repo dropdown list
1. Add -> Clone Repository...
1. Filter repo list (I used my username to return only my personal repos)
1. Use arrow keys to select a repository
1. Press <kbd>Enter</kbd>

### Expected Behavior
I expected the repository to be cloned

### Actual Behavior
Crickets...

## Additional Information
![2019-01-09 17 39 37](https://user-images.githubusercontent.com/1715082/50937032-9bbb2200-1437-11e9-964b-09f7642b05c8.gif)
_It's not apparent here, but I am pressing <kbd>Enter</kbd> multiple times_

**Comment by Daniel-McCarthy** [comment]
I would love to give this Issue a try. I have already taken a swing at it and will try to submit a pull request for it tomorrow!

**Comment by tierninho** [comment]
@Daniel-McCarthy go for it! Thanks again for all contributions 🥇

**Comment by gingerbeardman** [comment]
This is still broken for me when cloning from website?

Reproduce
- clone new repo from website
- wait for Desktop to appear
- Press enter

As in https://github.com/desktop/desktop/issues/5234
