### ISSUE TITLE
Authentication failed: cloning a private repository — Permission denied (publickey)

### ISSUE THREAD

**Issue by morqon** [desktop/desktop#6573]
## Description

Using a new laptop, with a fresh install of GitHub Desktop, authentication fails when I try to clone my own private repository — after passing `Checking out files: 100% (1053/1053), done.` and attempting `Cloning into`.

![Screenshot of Authentication Failure dialogue](https://duaw26jehqd4r.cloudfront.net/items/073Y2833251U2P3C0x0o/Screenshot%202019-01-09%20at%2019.32.05.png)

From the logs: 

```
Cloning into '/Users/morgan/Documents/GitHub/repository'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I have cycled through the log-out-log-in routine [suggested by hequ](https://github.com/desktop/desktop/issues/4451#issuecomment-400938553) on [#4451](https://github.com/desktop/desktop/issues/4451), revoking then reinstating GitHub Desktop's OAuth permissions, but to no avail. 

I have tried initiating the clone both within GitHub Desktop, and directly from GitHub using both HTTPS and SSH, but both fail at the same point for similar authentication issues (logs attached below).

I am able to create, and push to, new private repositories on the same account using GitHub Desktop.

The repository is forked from a separate private repository I do not own, if that makes a difference (I guess it shouldn't).

The help article '[Error: Permission denied (publickey)](https://help.github.com/articles/error-permission-denied-publickey/)' seems relevant, though it is written for command line users, not GitHub Desktop users.

Do I need to [generate a new key pair](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/), and [associate them with my GitHub Account](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/)? — for HTTPS _and_ SSH?

## Version

* GitHub Desktop: 1.5.1

* Operating system: macOS 10.14.1

#### First Attempt: browser sign in

1. Sign in to github.com
2. Install GitHub Desktop
3. Use 'Sign in using your browser' to authenticate GitHub Desktop
4. Select 'Clone Repository' and choose the private repository at issue listed under 'Your Repositories', then 'Clone'
5. The clone process starts, almost completes, then authentication fails on completion

#### Second Attempt: manual sign in

As First, except:

3. Sign in using GitHub Desktop, entering my credentials manually

#### Third Attempt: HTTPS via browser

As First, except:

4. Select 'Clone or Download' from the repository on github.com —> 'Clone with HTTPS' —> 'Open in Desktop'

#### Fourth Attempt: SSH via browser

As First, except:

4. Select 'Clone or Download' from the repository on github.com —> 'Use SSH' —> 'Open in Desktop'

**Notes**
-  Between each attempt, I delete the repository folder from my local GitHub directory
- After the fourth attempt, I signed out of my account on GitHub Desktop, then revoked its OAuth permissions in the browser; I then signed out of my account in the browser and signed back in again on both, attempting the above steps again

### Expected Behavior

I expect step 5. to complete without an authentication failure: I am logged in with the correct username and password, both on GitHub Desktop and the browser, and have full ownership and access privileges for this repository. 

### Actual Behavior

**Using HTTPS**: Authentication fails after `Checking out files` has completed, on `Cloning into`.

The key line (er, pun) seems to be: 

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Using SSH**: ssh: Authentication fails after `Checking out files` has completed, on `Cloning into`.

```
ssh: connect to host github.com port 22: Operation timed out
fatal: Could not read from remote repository.
```

## Additional Information

Other possibly related things I did when setting up the new laptop for this purpose:

-  Installed Docker Desktop, built a Docker image, and ran a server locally
-  Installed the AWS CLI
-  Troubleshooting a problem with the local server led me to attempt a fresh clone of the site repository, which is how I ran into this authentication problem

I installed GitHub Desktop on a different new laptop a month ago, and had no issues. 

<p align="center">
  <img src="https://i.pinimg.com/736x/65/72/27/657227b73fd3726a1606c849a13b0df4.jpg">
</p>

### Logs

HTTPS attempt: [2019-01-10.desktop.production.log](https://github.com/desktop/desktop/files/2745608/2019-01-10.desktop.production.log)
SSH attempt: [2019-01-09.desktop.production.log](https://github.com/desktop/desktop/files/2745610/2019-01-09.desktop.production.log)

**Comment by shiftkey** [comment]
@morqon I think you're seeing the ongoing SSH failures because your submodules are configured with SSH (these are not affected by whether the initial clone is HTTP or SSH):

```
Submodule 'source/javascripts/objcjs' (git@github.com:objcio/objcjs.git) registered for path 'source/javascripts/objcjs'
Submodule 'source/stylesheets/objcss' (git@github.com:objcio/objcss.git) registered for path 'source/stylesheets/objcss'
Cloning into '/Users/morgan/Documents/GitHub/morgan-objcio-website/source/articles'...
ssh: connect to host github.com port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:objcio/articles.git' into submodule path '/Users/morgan/Documents/GitHub/morgan-objcio-website/source/articles' failed
```

**Comment by shiftkey** [comment]
If you're not able to get to port 22, you might be able to workaround it by rewriting the URLs from config.

These two entries in your `~/.gitconfig` global config should do the trick:

```
# Use https instead of git and git+ssh
[url "https://github.com/"]
  insteadOf = git://github.com/
[url "https://github.com/"]
  insteadOf = git@github.com:
```

**Comment by steveward** [comment]
@morqon based on your 👍 it sounds like you were able to get things working, so I am going to close this issue out. Please let us know if you need any further assistance!

**Comment by morqon** [comment]
Hi @steveward, sort for the delayed reply. I did get it working, by [generating a new key pair](https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent), and [associating them with my GitHub Account](https://help.github.com/en/articles/adding-a-new-ssh-key-to-your-github-account). 

I have since had the same problem moving to a new Mac, and though I know the solution, it isn't clear to me why this is needed.

**Comment by Xunie** [comment]
For you finding this through google: You are getting a `publickey` error: This means either:
* you don't have a ssh key
* the ssh key you do have is not associated with your github account

If you're inside MSYS2, remember that `~/.ssh/` refers to the folder inside MSYS2 and not `C:\Users\Username\.ssh\`, although windows tools might look for stuff there...
