### ISSUE TITLE
File viewer is unnamed for screenreaders

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#6578]
Visually there is a header with the file name, but screenreader announces only "edit multi line"

![tdna_gh_desk_win_048](https://user-images.githubusercontent.com/964912/50985913-4d029c00-14ba-11e9-960e-ce7c14da1e20.png)

**Comment by tidy-dev** [comment]
No longer reproducible. Likely resolved with a combination of deprecating code mirror and apply cell/grid semantics in recent accessibility work.
