### ISSUE TITLE
No success announcement from screenreader after creating a branch

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#6580]
Activate **Create Branch** button. Screenreader announces "unavailable" and focus jumps to the GitHub application menu bar after activating the "Create branch" button. Users would have to navigated back to the **Current branch** to see that the branch name had been visually updated. Notification message, aria-alert or focus management could address this.

**Comment by tidy-dev** [comment]
This is being tracked internally with https://github.com/github/accessibility-audits/issues/6853. Closing in favor of tracking there.
