### ISSUE TITLE
Welcome page suggestions

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6583]
Some suggestions for the Welcome page:

- Current:
"GitHub Desktop is a seamless way to contribute to projects on GitHub and GitHub Enterprise. Sign in below to get started with your existing projects."

Perhaps "contribute" could be flushed out a little? Contribute what?

- The "create your free account" and the "Sign into.." links are different shades of blue.

- "Sign into..." should be "Sign in to..." as it not only matches the description above and github.com, but it's more technically correct, and more widely [accepted](https://books.google.com/ngrams/graph?content=sign+in%2Csign+into&year_start=1800&year_end=2018&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Csign%20in%3B%2Cc0%3B.t1%3B%2Csign%20into%3B%2Cc0)

<img width="539" alt="screen shot 2019-01-10 at 9 27 54 am" src="https://user-images.githubusercontent.com/14828183/50986838-bc798b00-14bc-11e9-8f52-16677bad773a.png">

- Zooming in fully is not the best experience: 

<img width="959" alt="screen shot 2019-01-10 at 9 47 08 am" src="https://user-images.githubusercontent.com/14828183/50986832-b84d6d80-14bc-11e9-8535-e5e0c15d77c5.png">

1.6.0-beta1, mac

**Comment by billygriffin** [comment]
@tierninho Thanks for adding this. I don't really have any problems with the verbiage to be honest. Do you have any suggestions to improve it? I added #6587 to fix the "Sign into" lines.

The create your account being slightly less emphasized seems ok too, as our hypothesis is that most people will already have a GitHub account upon downloading Desktop and if they don't we put it before the other links. But open to thoughts on that.

**Comment by tierninho** [comment]
Nothing comes to mind on any possible changes and don't have strong feelings about it either. Thanks for the PR 👍

**Comment by j-f1** [comment]
> more widely accepted

When I compare “sign into” and “sign in to,” the results are [reversed](https://books.google.com/ngrams/graph?content=sign+in+to%2Csign+into&year_start=1800&year_end=2008&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Csign%20in%20to%3B%2Cc0%3B.t1%3B%2Csign%20into%3B%2Cc0).

**Comment by billygriffin** [comment]
Discussed this with @niik and we're in agreement that #6587 is a good starting place for this. If we hear from our users that zooming is an issue, we can investigate that separately but we shouldn't unnecessarily optimize for theoretical scenarios. Thanks @tierninho!

**Comment by billygriffin** [comment]
Ah, sorry @j-f1, I had this up from yesterday and didn't see your comment until after I had closed it. Thanks for the comparison! It doesn't seem like a big deal either way, but I do think the new way is a bit more technically correct so I'm fine with leaving it. Thanks again!
