### ISSUE TITLE
Repo list entries pointing to wrong directory and overriding others after clone

### ISSUE THREAD

**Issue by Max-Hollywood** [desktop/desktop#6588]
## Description

I cloned a repo with Desktop, which worked fine.  However, I had some non-existing repos still in Desktop's list, which Desktop prompted me to remove and I did.  The issue is that now the NAME of the repo I just cloned is pointing to a different repo.

So my just-cloned "Project1" is pointing to "abcRepo", instead of the repo that it just cloned (which it did clone, but didn't add to the list).

## Version

* GitHub Desktop:
It occurred on a version previous to Version 1.5.1 (it automatically installs updates when I start the program; I restarted/updated to see if that fixed the problem).

* Operating system:
Microsoft Windows [Version 6.1.7601] (Windows 7)

## Steps to Reproduce

1. Selected Clone repo from the Desktop menu
2. Pasted in the URL .git for my repo
3. Cloned into my project repo folder
4. Desktop complained about missing repo's that didn't exist, but were in the list
5. Selected "Remove" for each missing repo
6. The newly cloned repo was selected
7. The contents of the "Changes" tab seemed incorrect as nothing should have changed, and I was just working on one of the files so I could see the contents were wrong.
8. Opened in Explorer to find that it was pointing to an old repo that existed in the list (replacing the name of that repo with the newly cloned repo name)
9. My newly cloned repo is not in the list
10. I removed the buggered up list entry, and added it as a local repo, and it now works as expected

### Expected Behavior

To clone the repo and have it in the list of repos

### Actual Behavior

Newly cloned repo is not in the list, but the name is and has overridden the name of another repo in that list (but points to that other repo)

### Logs

[2019-01-11.desktop.production.log](https://github.com/desktop/desktop/files/2747748/2019-01-11.desktop.production.log)

**Comment by tierninho** [comment]
@Max-Hollywood Stumped as this was hard to reproduce. I  do see a `fatal: refusing to merge unrelated histories` in your logs, which can occur when remotely adding a git repo. 

Not sure if this is the culprit, but it looks as it is still an existing issue based on https://github.com/desktop/desktop/issues/1484 

As you appear to have resolved the issue, gonna close this for now. Happy to reopen if there is another issue that need fixing.
