### ISSUE TITLE
Connection to repository broken after installing Git

### ISSUE THREAD

**Issue by Migdalin** [desktop/desktop#6593]
## Description

Push to repository from GitHub Desktop failed to arrive at the repository, though no errors were generated, and the UI claims that the change was pushed without issue.

## Version

* GitHub Desktop:  1.5.1

* Operating system:  Windows 10

## Steps to Reproduce

1.  Install GitHub Desktop.
2. Create a repository.  
3.  Merge and push files into the repository.
4.  Pull the repository onto a second machine.
5.  On the first machine, install Git.  (You will be prompted to do this, "if you want to merge a file manually.")
6.  Now, merge changes and push to the repository from machine #1.
7.  Return to machine #2.  Fetch.  
8.  See that the changes weren't fetched.  Look at the repository online.  See that the changes don't appear.

### Expected Behavior

1.  Require that users have Git installed locally before installing GitHub Desktop.  Or, at least forcefully warn them that operations like manual merging will be unavailable.  I don't know for sure that this is what broke the connection, but requiring that Git be installed still makes sense.  Merging changes is a standard operation.  Before the desktop can claim to be installed correctly, the desktop should support merging.
2.  During installation, warn users that, while Git will let them select various editors, GitHub Desktop only supports Atom.  Same rationale as above.
3.  If the installer doesn't require that Git be installed first, handle situations where it is installed afterwards.  For sure, don't pretend that a push to the repository worked when it didn't.

### Actual Behavior

A push to the repository appeared to succeed, but the files never made it there.

## Additional Information

![github desktop screenshot](https://user-images.githubusercontent.com/6393616/51047428-71cc4180-1596-11e9-9509-2b2b1bbb1a76.png)
![github online screenshot](https://user-images.githubusercontent.com/6393616/51047429-71cc4180-1596-11e9-9d26-0edf9dae7b80.png)

### Logs

[2019-01-11.desktop.production.log](https://github.com/desktop/desktop/files/2750464/2019-01-11.desktop.production.log)

**Comment by Migdalin** [comment]
If multiple editors are supported, then improved messaging sounds like a really good idea.  I tried following the link to the full list, but it gives me "page not found."  Anyway, I installed Notepad++, because the Git installer listed it as a supported editor, but Desktop still appears to insist on Atom or nothing.

![install atom screenshot](https://user-images.githubusercontent.com/6393616/51074485-c8488700-164d-11e9-88b8-07a146c85d1f.png)

**Comment by shiftkey** [comment]
> Anyway, I installed Notepad++, because the Git installer listed it as a supported editor, but Desktop still appears to insist on Atom or nothing.

We can't support Notepad++ currently - see #4120 for more details about that issue

**Comment by steveward** [comment]
@Migdalin sorry about the broken link -- I've updated it. For reference these are the currently supported editors on Windows:

Atom
Visual Studio Code - both stable and Insiders channel
Sublime Text
ColdFusion Builder
Typora
SlickEdit
JetBrains WebStorm

Are you still having any problems using GitHub Desktop? If so, let me know how I can help.

**Comment by Migdalin** [comment]
I have Visual Studio 2017, the free version, but I guess that's not the same as Visual Studio Code.  Probably I'll get Atom the next time I need to merge.  For now, I'm making changes on one machine only, so I don't have to worry about merging.  Thanks for your help.

**Comment by steveward** [comment]
> I have Visual Studio 2017, the free version, but I guess that's not the same as Visual Studio Code.

Visual Studio Code is a text editor similar to Atom, whereas Visual Studio is a full IDE that provides a lot of other features. They do share some features like syntax highlighting, though. I would definitely recommend checking out VSCode or Atom if you are looking for a text editor to use. I'm going to close this issue out, but let us know if we can help with anything else!
