### ISSUE TITLE
No local changes shows ampersands on Windows

### ISSUE THREAD

**Issue by nycdotnet** [desktop/desktop#6596]
## Description
In the new "No local changes" screen (1.6.0-beta2 on Windows), the ampersands for keyboard shortcuts are being rendered literally rather than being enabled as keyboard shortcuts.  See screenshot.

## Version
* GitHub Desktop: 1.6.0-beta2
* Operating system: Microsoft Windows [Version 10.0.17134.523]

## Steps to Reproduce
1. Open the new "No local changes" screen.

### Expected Behavior
1. I expected working keyboard shortcuts (highlighted by underscores on the relevant letters)

### Actual Behavior
1. I see literal ampersands in the rendered text.

## Additional Information
![image](https://user-images.githubusercontent.com/3755379/51052713-7cda9e00-15a5-11e9-8b74-9dc929e5ba7c.png)

### Logs
Let me know if you need them.

**Comment by tierninho** [comment]
@nycdotnet Good catch! and thanks for the issue

**Comment by billygriffin** [comment]
Thanks for the super fast feedback @nycdotnet! Looking into this now.
