### ISSUE TITLE
Invalid string length error upon launching desktop

### ISSUE THREAD

**Issue by karthicks** [desktop/desktop#6600]
## Description
This stacktrace from the error popup says it all:
```
RangeError: Invalid string length
    at Socket.onChildStdout (child_process.js:343:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

Version: 1.5.1
OS: Mac OS 10.14.2
```

## Version
* GitHub Desktop: Version: 1.5.1
* Operating system: OS: Mac OS 10.14.2

## Steps to Reproduce
1. `Launch github desktop on a mac`
2. `Wait for a few seconds as it loads your existing repositories`

### Expected Behavior
The desktop launches properly and stays launched.

### Actual Behavior
I observe a `Github Desktop failed to launch` error popup, with an option to `Quit and Restart`. Needless to say, restarting does not help.

## Additional Information
Here's a screenshot of the error popup: 
<img width="597" alt="github-desktop-popup" src="https://user-images.githubusercontent.com/1120120/51079905-a3700600-1685-11e9-9bcb-493ee29b2e7f.png">

While I do see a number of other tickets with this stack trace,  they appear to have been closed as `cannot reproduce` or may have been logged against an older version.

**Comment by steveward** [comment]
@karthicks is this still an issue you are encountering in GitHub Desktop? I'm going to close this out since we haven't seen any reports of this error recently, but let me know if you are still seeing it.
