### ISSUE TITLE
 What's the point of "Add local repository" dialog?

### ISSUE THREAD

**Issue by xVanTuring** [desktop/desktop#6602]
**Please describe the problem you think should be solved**
Since  there are no options to tweak,it just increases 2 clicking. If someone want to cancel, they can cancel when they choose. So why not just choose folder directly

![tim 20190113114429](https://user-images.githubusercontent.com/11146248/51081372-0e264d80-1729-11e9-8e66-decf8e802bd2.png)
 Just an advice.

**Comment by billygriffin** [comment]
Hi @xVanTuring, thanks for the idea! Just so I'm clear, you're suggesting that when a user selects "Add Existing", it should just pop Explorer or Finder to get you to pick which repo you're adding.

So the steps would be as follows below, without the intermediate step of the dialog. Is that correct?

<img width="266" alt="screen shot 2019-01-14 at 7 16 59 am" src="https://user-images.githubusercontent.com/5091167/51118008-8f82ec00-17cc-11e9-8c6e-b5dfc5558242.png">

<img width="656" alt="screen shot 2019-01-14 at 7 19 14 am" src="https://user-images.githubusercontent.com/5091167/51118084-ba6d4000-17cc-11e9-9292-0afa265f0beb.png">

**Comment by tierninho** [comment]
If we simplify this feature, some things we lose are:

- validation of the repo will no longer occur inline, and 
- users can no longer enter in the path manually

![image](https://user-images.githubusercontent.com/14828183/51124800-0ec7ee00-17d4-11e9-984d-1a2e7d539d6b.png)

**Comment by xVanTuring** [comment]
@billygriffin , that's what I am thinking.

@tierninho 
> If we simplify this feature, some things we lose are:
> 
> * validation of the repo will no longer occur inline, and
> * users can no longer enter in the path manually

Well, that's a good point. (Validation step can still pop a dialog.) Since someone may copy and paste path, the dialog will be useful then.

**Comment by billygriffin** [comment]
Thanks @xVanTuring and @tierninho for the thoughtful discussion. 😄
