### ISSUE TITLE
Github desktop automatically stages files over 100mb

### ISSUE THREAD

**Issue by michaelhester07** [desktop/desktop#6603]
**Please describe the problem you think should be solved**
Github Desktop automatically stages files that are too large for github (100mb) making it possible to accidentally commit them, preventing pushes.

Example:

I use my github mainly to manage unity projects and when lighting is baked in unity it generates large files.  It is easy for me to miss these when committing.

**[Optional] Do you have any potential solutions in mind?**
As I would expect that github desktop is only used with github so adjust the auto staging to detect how big a file is and not automatically stage it when it's over the limit.  Additionally pop up a warning when a large file is in the commit, allowing the user to OK it if they're not working with github while using the desktop app.

**Comment by shiftkey** [comment]
@michaelhester07 thanks for the feedback!

This is something we've been tracking in #997, and eventually settled on a flow that we think will make this experience better: https://github.com/desktop/desktop/issues/997#issuecomment-431936406

The next release of GitHub Desktop contains this new flow - you can see the work to support it in #6013. If you'd like to try it out before then, it's available on our [beta channel](https://github.com/desktop/desktop#beta-channel) currently.

For the moment I'm going to close this out, but please reply back if you have feedback about this new flow once you've tried it out!
