### ISSUE TITLE
Unable to clone private repository over HTTPS

### ISSUE THREAD

**Issue by BernardQuek** [desktop/desktop#6604]
## Description

I am unable to clone a private repository I own into GitHub Desktop. Couldn't figure out how to debug this so here I seeking help.

## Version

* GitHub Desktop: 1.5.1

* Operating system: Windows 10

## Steps to Reproduce

1. (Re)-install GitHub Desktop.
2. Sign-in with GitHub account.
3. Attempt to clone repo (whether from File > Clone repository, or from the website link to open in Desktop).

### Expected Behavior

Repo is cloned properly.

### Actual Behavior

![image](https://user-images.githubusercontent.com/17026786/51085202-c1fefb80-1770-11e9-8c05-ef6a45f7b97b.png)

After entering my details here, the same screen pops-up again.

## Additional Information

My GitHub account has 2FA attached to it.

I have tried logging out and into my GitHub account on GitHub Desktop, both via browser log-in and user/password login (which prompts for 2FA code).

### Logs

[2019-01-13.desktop.production.log](https://github.com/desktop/desktop/files/2755656/2019-01-13.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @BernardQuek. Just to make sure I fully understand the issue -- are you able to successfully log in to your GitHub account within GitHub Desktop from `File` > `Options` > `Accounts`?

If that is the case can you open the `Credential Manager` on your Windows machine and verify that there is a `GitHub - https://api.github.com/BernardQuek` entry under `Windows Credentials` > `Generic Credentials`? It would also be helpful if you could upload the full log file from GitHub Desktop since there will be more information about the authentication process, including whether or not GitHub Desktop can find a valid token associated with your account.

**Comment by BernardQuek** [comment]
Yes, I am able to log into GitHub Desktop, and the credentials you mentioned exists.

I have edited my issue and uploaded the full logs.

**Comment by steveward** [comment]
Thanks for the update @BernardQuek. A couple of questions:

- Have Git operations requiring authentication ever worked on this machine in GitHub Desktop?
- Are you successfully able to clone using the command line?

One thing you can try would be to reset GitHub Desktop by deleting the `%AppData%\GitHubDesktop` directory, and then try signing in and cloning again. Let me know if that gets things working.

**Comment by BernardQuek** [comment]
Yes, other private repos from private organisations have worked before. I couldn't remember how I got it to work or if I faced any issues while setting it up, though. I was not the owner of any of those repos however.

Cloning succeeded on the command line, but adding the cloned repo to GitHub Desktop then trying to do a fetch on one of my branches results in the same error.

Clearing `%APPDATA%\Roaming\GitHubDesktop` and signing in again didn't work either.

**Comment by steveward** [comment]
@BernardQuek apologies for the delay. I dug through the log file a bit further and realized I had missed this error:

```
fatal: unable to look up github.com (port 9418) (Either the application has not called WSAStartup, or WSAStartup failed. )
```

Are you behind a proxy/firewall/antivirus software that could be blocking GitHub Desktop from cloning this repository? If GitHub Desktop is being blocked that would indicate why the command line is working for you.

**Comment by billygriffin** [comment]
This sounds similar to other issues we've seen where antivirus or a firewall has been the problem. If you'd like us to help look into this further, let us know @BernardQuek, but until then I'm going to close this issue.

**Comment by emedhermrsool** [comment]
I have this same exact issue on Ubuntu 18.04, The github account is an org.
