### ISSUE TITLE
git: 'remote-https' is not a git command. See 'git --help'. error when cloning a repository

### ISSUE THREAD

**Issue by OneDev99** [desktop/desktop#6605]
I experience this error whenever I try to clone a repository. The error comes regardless if the repository is private or public. As a result, I cannot clone any repository. The same error comes if I try and create a local repository and publish it to Github.

**Github Desktop Version:  1.5.1
OS: Windows 10 64 bit**

![girhub](https://user-images.githubusercontent.com/33938563/51086190-67ae6c80-1769-11e9-8de4-f8c7443dbff5.PNG)

**Comment by steveward** [comment]
Thanks for the report @OneDev99. This looks like it may be an issue with your installation of GitHub Desktop. Have you tried reinstalling GitHub Desktop again? If not, I would recommend deleting the following two directories to allow you to perform a fresh installation:

`%AppData%\GitHubDesktop`
`%LocalAppData%\GitHubDesktop`

Then install GitHub Desktop again and see if you are able to perform a clone operation successfully.

**Comment by OneDev99** [comment]
Re-installed the application a few times using the method you provided which solved the problem. Thank you so much!

**Comment by OneDev99** [comment]
I tried the above method and was able to successfully clone a repository. I closed the application and opened it again to clone another repo but it showed the same exact error.

**Comment by OneDev99** [comment]
I had the idea already and have checked my virus chest. I'm using Avast and there are no false flags. I updated my Github Desktop to the latest version released just now and was able to clone a repository and commit changes. I restarted my desktop and now when I click on publish to Github, I get the same error. I found the remote https file inside my Visual Studio folder.  (C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin). I copied the file into the same folder in %appdata% under the github folder and the error message changed to a simple line now saying, "Unknown Error". I'm currently uninstalling Visual Studio and Github Desktop. Will update if reinstalling them changes anything.

**Comment by OneDev99** [comment]
Reinstalling both Github Desktop and updating Microsoft Visual studio to version 15.9.5 has fixed the error for now. I'll close the issue after thoroughly checking if the issue still comes after some time or after restarting my pc.

**Comment by OneDev99** [comment]
The issue came again. I have to uninstall Github every time and even manually delete files from appdata and localappdata folders. And then reinstall it for the error to go away. And it reappears after closing the app once.

**Comment by steveward** [comment]
@OneDev99 do you also run into this issue when attempting to clone a repository from the command line using the `git clone` command? If not, try [downloading Git for Windows](https://git-scm.com/download/win) and running a `git clone <REPO_URL>` to see if the same issue occurs. That will help narrow down if your something on your machine is flagging that specific file.

**Comment by guptashashank31999** [comment]
what should i have too dooo i have reinstall the software but again i get same messgage
![Screenshot (51)](https://user-images.githubusercontent.com/48836089/64454539-dd0bea80-d108-11e9-873c-3f1d508ffaae.png)

**Comment by Heart-Hacker786** [comment]
uninstalling Avast fixed the problem for me
seems like avast has problem with every Good thing

**Comment by gerardreches** [comment]
I've reinstalled and it worked JUST UNTIL I rebooted my PC. In need of a permanent solution.

**Comment by tierninho** [comment]
@gerardreches Thanks for reaching out. Please fill a new issue so we may address it separately. Include the logs if possible. Cheers.

**Comment by GeorgeAlexandruS** [comment]
I have the same issue, anyone managed to solve this?

**Comment by alchaki2009** [comment]
Duplicate of #

**Comment by bkowal** [comment]
I got this error too. It turned out that in my case it was indeed Avast that was playing tricks on me.  Avast categorized remote-https as a suspicious file and quarantined it.  Please look at the list of files that Avast quarantined, check if git stuff is there and if so, add exceptions for these files.

**Comment by EricChoLiu** [comment]
In Windows 10, I secceed in using the git clone command in the Powershell.
In Ubuntu or WSL, there is no problem in terminal.

**Comment by pk185212** [comment]
I am facing same issue on Linux RHEL 6 command line. I do not have avast on my linux server, Any leads for this?
Thanks in advace.

**Comment by ghost** [comment]
This happened with me also. I install git ver. 2.32.0 on my linux machine by compiling the source. I tried installing an older version of git which supports remote-https. I install git ver. 2.30.2 which fixed my problem. I am probably sure that this method will work because i got the same error which you got

**Comment by camkon** [comment]
This happens because the "git-remote-http.exe" file and the desktop app are in different places. So, finding the said file and add it to path in system variables so the desktop app could access it from anywhere would solve the issue. The "git-remote-https.exe" file is most likely found in - 
_"C:\Users\'UserName'\AppData\Local\GitHubDesktop\app-2.9.4\resources\app\git\mingw64\bin"._ 

Find yours and set it to path. A re-install may also solve it.

**Comment by Realsantosm** [comment]
I am facing then same error, I tried different options to solve but of no use.........😢😒

Cloning into 'D:\GitHub-Online\portfolio-professional\portfolio-professional'...
git: 'remote-https' is not a git command. See 'git --help'.

Would you like to retry cloning ?

**Comment by Hamza804-latif** [comment]
I clone directly from git bash and it worked but not working from github desktop

**Comment by Hamza804-latif** [comment]
Add the path of C:\Users\yourPcName\AppData\Local\GitHubDesktop\app-2.9.4\resources\app\git\mingw64\bin  in system variables which are located in environment variables.
AppData folder is hidden so unhide folders then you will be able to see this folder.
I have done this on windows and it worked for me.

**Comment by kasia129** [comment]
I can confirm that what @Hamza804-latif  suggested worked for me as well.
