### ISSUE TITLE
Wrong Default Branch Selected Locally

### ISSUE THREAD

**Issue by hlopetz** [desktop/desktop#6608]
## Description

using **only** GitHub Desktop i created a branch named `sfdx-master` from `master` one. there i re-structured APEX files to comply with file structure requirements of SFDX way of packaging. that was experimental branch so i switched back to `master` then and tried to create another branch (i.e. `feature-x`), but GitHub Desktop showed me branch i had to create the new one from as `sfdx-master`, not `master`.

i thought it was a glitch, but i can reproduce that on that local copy again and again.

to solve the weird default branch issue i got to our GitLab repo, but the default branch there is still `master` despite i pushed to there and fetched updates from there.

in GitHub Desktop itself i do not see a setting to choose a default branch. afaik, gif also does not have the "default branch" concept. so i have no idea on how to set `master` as the default branch back.

## Version

* GitHub Desktop: 1.5.1

* Operating system: Microsoft Windows [Version 10.0.17134.472]

## Steps to Reproduce

1. switch to master
2. menu Branch > New Branch
3. look at "Create branch based on…" selector

### Expected Behavior
default branch is `master`

### Actual Behavior
default branch is `sfdx-master`

## Additional Information

![image](https://user-images.githubusercontent.com/645340/51108053-80fef980-17f9-11e9-8bcb-949c8ddc07f8.png)

**Comment by shiftkey** [comment]
@hlopetz thanks for the report. We made a change in #5073 to better support other remotes like GitLab, so I'll walk through what this involves and see if we need to revisit this.

The code is found here:

https://github.com/desktop/desktop/blob/9bf818750ad019e99922d02d0275cbe87869fcbc/app/src/lib/stores/git-store.ts#L346-L365

For a non-GitHub repository we check what the `origin/HEAD` symbolic ref points to in the repository (swap `origin` for the current remote you are using). This is a ref that remotes declare to indicate which branch should be considered the "default" branch.

Are you able to run this command on your local repository and see whether it returns `origin/master` or `origin/sfdx-master`? I'm not sure whether you have a different remote to `origin` defined, so you might need to change that:

```
$ git symbolic-ref refs/remotes/origin/HEAD
```

**Comment by hlopetz** [comment]
thanks for the details, @shiftkey.

    > git symbolic-ref refs/remotes/origin/HEAD
    refs/remotes/origin/sfdx-master

for me.

do you is there a way to re-set that to `master`? and how such issue may be prevented going forward?

**Comment by shiftkey** [comment]
In theory there's a [`git remote set-head`](https://git-scm.com/docs/git-remote#git-remote-emset-headem) command that you could use to change it, but I haven't used it so I'm not sure.

I'm also not sure if this is some sort of bug with the GitLab UI that these have now fallen out of sync.

**Comment by hlopetz** [comment]
thank you @shiftkey, `git remote set-head origin master` worked for me.
the only Q is how that could happen if i used GitHub Desktop app only.

**Comment by shiftkey** [comment]
@hlopetz it might have been that the clone existed before the rename was applied, and in typical Git `fetch/push/pull` usage the rename of the default branch wasn't updated?

Anyway, I'm glad we got to the bottom of the issue. I'm going to close this out as resolved, but let us know if you have any other questions about this.

**Comment by RishiKulshreshtha** [comment]
I'm facing a similar issue. +1

**Comment by shiftkey** [comment]
@RishiKulshreshtha please open a fresh issue and provide details about your setup if you would like us to investigate further
