### ISSUE TITLE
error while building node-sass module

### ISSUE THREAD

**Issue by kingov** [desktop/desktop#6617]
yarn

but failed

7 warnings and 1 error generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/wangzheng/code/electron/desktop-release-1.5.1/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/wangzheng/.nvm/versions/node/v10.14.1/bin/node" "/Users/wangzheng/code/electron/desktop-release-1.5.1/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/wangzheng/code/electron/desktop-release-1.5.1/node_modules/node-sass
gyp ERR! node -v v10.14.1

**Comment by shiftkey** [comment]
@kingov are you trying to build GitHub Desktop from source? Please ensure you have [your environment setup correctly](https://github.com/desktop/desktop/blob/development/docs/contributing/setup-macos.md#setting-up-development-dependencies-on-macos) to build native modules.

**Comment by kingov** [comment]
ok , thanks

**Comment by shiftkey** [comment]
@kingov I'm going to close this out unless you can share more details about your setup and what the whole error is that you're seeing (the stuff before this bit that didn't get included).

> 7 warnings and 1 error generated.
