### ISSUE TITLE
Commit failed - exit code 1 received [NO .git FILE]

### ISSUE THREAD

**Issue by SafelySwift** [desktop/desktop#6624]
## Description
GitHub will not let me upload an Xcode project.

## Version

* GitHub Desktop:
1.5.1

* Operating system:
High Sierra 

## Steps to Reproduce
1. Try to upload an Xcode project

### Expected Behavior
Upload an Xcode project

### Actual Behavior
The "Commit failed - exit code 1 received"

## Additional Information

<img width="962" alt="screen shot 2019-01-14 at 6 57 13 pm" src="https://user-images.githubusercontent.com/45888860/51149005-3e0b4900-182e-11e9-9a54-4c3de21788b9.png">

### Logs

Could not find

**Comment by shiftkey** [comment]
> ### Logs
> Could not find

@SafelySwift thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Finder** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by SafelySwift** [comment]
There is no such thing. I type in "log" and I do not see anything.

**Comment by SafelySwift** [comment]
<img width="571" alt="screen shot 2019-01-16 at 6 17 20 pm" src="https://user-images.githubusercontent.com/45888860/51284873-0aa9f500-19bb-11e9-88be-1011bde8f7fb.png">

**Comment by shiftkey** [comment]
Not related to the issue at hand, but this message is a helpful hint if you would like Desktop to check for updates and keep you on the latest version:

> 2019-01-16T04:51:40.587Z - error: [ui] Error checking for updates
Error: Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. See Squirrel/Squirrel.Mac#182 for more information.

**Comment by SafelySwift** [comment]
I saw that, and I will update. Strange however but my app is in Documents.

**Comment by shiftkey** [comment]
@SafelySwift I think that error message is just hard-coded because the majority of cases seen was launching the app from Downloads 🤷‍♂️

**Comment by SafelySwift** [comment]
Updated - no change

**Comment by billygriffin** [comment]
Any ideas on this one @desktop/support?

**Comment by SafelySwift** [comment]
Anyone there?

**Comment by SafelySwift** [comment]
[2019-01-26.desktop.production.log](https://github.com/desktop/desktop/files/2799619/2019-01-26.desktop.production.log)

**Comment by SafelySwift** [comment]
Alright, I accdiently made the source code subdirectories. Now you can't access them

**Comment by SafelySwift** [comment]
https://github.com/SafelySwift/Swizzle/tree/swizzle-1.0/Source/Code

**Comment by SafelySwift** [comment]
and https://github.com/SafelySwift/Swizzle/tree/swizzle-1.0/Source/Sneak%20Peek

**Comment by billygriffin** [comment]
Thanks @SafelySwift!

@shiftkey @steveward Before we close this issue, I wonder if there's a way to surface a better error message. Maybe not, but just wanted to check as it's unfortunate that we don't give the user any way to know what might be causing the issue in this type of case.

**Comment by shiftkey** [comment]
@billygriffin here's some of the context about the error:

```
2019-01-26T02:26:55.216Z - error: [ui] `git commit -F -` exited with an unexpected code: 1.
On branch swizzle-1.0
Your branch is up to date with 'origin/swizzle-1.0'.

Untracked files:
	Source/Code/
	Source/Sneak Peek/

nothing added to commit but untracked files present
```

Note the specific output here -  these are directories when `git status` runs but they likely have a `.git` directory inside (so Git wants to handle them as submodules) and it won't let the user commit them (even if they have checked them in the app).

#1870 seems to be the best issue to bump with the information listed here, rather than track a separate issue.

**Comment by billygriffin** [comment]
Thanks @shiftkey, closing in favor of #1870.
