### ISSUE TITLE
pull description inside new "no local changes" view

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#6628]
When your current branch is both ahead and behind, this is what the button shows:

<img width="579" src="https://user-images.githubusercontent.com/359239/51181777-7187bb00-18a2-11e9-9dbf-8d9ebe8dfad0.png">

I had a peek at the message that was being generated and it looks like the description always shows `commits`:

https://github.com/desktop/desktop/blob/cd783fa43845c4d26d81ef18d38021a59c172ba5/app/src/ui/changes/no-changes.tsx#L478-L483

For reference, for the **Push** action we do pluralize inside the description:

https://github.com/desktop/desktop/blob/cd783fa43845c4d26d81ef18d38021a59c172ba5/app/src/ui/changes/no-changes.tsx#L527-L533

While we're in here the "doesn't" in "that doesn’t exist on your machine" jumped out at me as being grammatically off (if you expand the abbreviation to "that does not exist" it stands out) and I was wondering if we had feels about tweaking it, particularly to avoid using abbreviations in messages like this.

Suggested alternatives:

> The current branch that has commits on GitHub _that do not_ exist on your machine.
> The current branch that has commits on GitHub _which do not_ exist on your machine.

**Comment by SJT1988** [comment]
All I want to know is if I Pull when I see this message, will all of my local changes be undone and the last week of my life be for nothing?
