### ISSUE TITLE
Small tweaks to onboarding language

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6638]
For the new onboarding, I am suggesting a few small edits to some the existing language, as such:

- Swap "Configure which editor you wish to use in preferences" ... to ... "Select your editor in Preferences" as there is really nothing to configure and Preferences should be capitalized
- "View the files in your repository in Finder"... perhaps to "View the files of your repository in Finder" or "View your repository's files in Finder"? 🤔 
👇 
<img width="684" alt="screen shot 2019-01-15 at 2 58 35 pm" src="https://user-images.githubusercontent.com/14828183/51215622-59ca2a00-18d6-11e9-92e0-8791e7e4b2a4.png">

- Do not capitalize "your" in the two boxes.
👇 
<img width="676" alt="screen shot 2019-01-15 at 2 58 45 pm" src="https://user-images.githubusercontent.com/14828183/51215623-59ca2a00-18d6-11e9-9b97-d65aa88e77f9.png">

Feel free to disagree or make edits.

**Comment by shiftkey** [comment]
I'm into this 👍 

One thing to add:

> "View the files in your repository in Finder"... perhaps to "View the files of your repository in Finder" or "View your repository's files in Finder"? 

I prefer "View the files of your repository in Finder"  over the other one

**Comment by shiftkey** [comment]
Moving this to `help-wanted` as I think this is something ideal for an external contributor to help out with. The relevant areas to update:

https://github.com/desktop/desktop/blob/96eb4a8894f048cb997d86ae413f3d0bfc33be38/app/src/ui/changes/no-changes.tsx#L281-L287

https://github.com/desktop/desktop/blob/96eb4a8894f048cb997d86ae413f3d0bfc33be38/app/src/ui/changes/no-changes.tsx#L236-L239

**Comment by msztech** [comment]
I can work on this @shiftkey 😃

**Comment by shiftkey** [comment]
Moving this back to "Available" because we haven't heard anything from the interested contributor.

**Comment by jamesgeorge007** [comment]
@shiftkey I shall take this up :clap:

**Comment by jamesgeorge007** [comment]
@shiftkey Kindly have a look at #7152

**Comment by shiftkey** [comment]
@jamesgeorge007 thanks for the quick turnaround. I'm actually going to ask someone else to review it, because I'm feeling very spread thin right now across a bunch of areas...
