### ISSUE TITLE
use GitHub repository name as alias, instead of folder name

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#664]
Repro:

 - clone a GitHub repository using the command line
 - append `-test` to the folder name on disk
 - drag and drop the folder into the app

Expected: new repository selected, but GitHub repository name used
Actual: folder name on disk is displayed

<img width="280" src="https://cloud.githubusercontent.com/assets/359239/20405806/c6a09626-acd8-11e6-925a-266cc7407410.png">

**Comment by joshaber** [comment]
Reopening this in response to #1701.
