### ISSUE TITLE
cleanup unused mocha/chai packages

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#6645]
After #6518 is reviewed and merged, we'll officially have no need to keep `mocha` and `chai` around. This means we should be able to remove these packages from the project:

 - `@types/chai`
 - `@types/chai-datetime`
 -  `chai`
 - `chai-as-promised`
 - `chai-datetime`
 - `mocha`
 - `mocha-junit-reporter`
 - `mocha-multi-reporters`

As well as this test setup:

https://github.com/desktop/desktop/blob/933efd9761c1a5bf99697c3b478a7d73fae14d55/app/test/globals.ts#L1-L2

We can then drop this bit of documentation: 

https://github.com/desktop/desktop/blob/933efd9761c1a5bf99697c3b478a7d73fae14d55/docs/technical/adding-tests.md#transitioning-to-jest

After doing that, you can check there are no outstanding issues by running these commands and ensuring the tests continue to pass:

```shellsession
$ yarn
$ yarn build:prod
$ yarn test
```

**Comment by shiftkey** [comment]
Dropping `help wanted` until this is ready to be worked on

**Comment by shiftkey** [comment]
#6518 has been merged, so this is available to be worked on

**Comment by Daniel-McCarthy** [comment]
I would like to take on this Issue. I'll be happy to make a pull request once completed.
