### ISSUE TITLE
UI: The `Add` repo button is cutoff when pane is adjusted

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6646]
The new `Add` repo button in the repository list section can be cutoff if the user adjust the pane to a certain width. 

Try setting the Changes/History tab to width 211px, then opening the Repo list. Use dev tools to verify width.

I suggest we have two states: `Add v` and `...`

![image](https://user-images.githubusercontent.com/14828183/51271582-c7c92c80-197c-11e9-81c5-436837179e0d.png)

`...` should really be `+`.

1.6.0-beta3, mac

**Comment by shiftkey** [comment]
> I suggest we have two states: `Add v` and `...`

This feels like a case where the Filter textbox should not steal space the button needs to show it's label. Maybe we can tweak the Flexbox CSS in here so that we never shrink the button, but I'd need to check how it looks at the minimum width.

**Comment by xt0rted** [comment]
Was just about to report this. This is what it looks like for me on Win10 @ 4k with 150% OS scaling.

![image](https://user-images.githubusercontent.com/831974/52862605-a1c1b400-3103-11e9-8be9-350a60686faf.png)

**Comment by tierninho** [comment]
If we change the filter to ~110px width, the `Add` button will always show. 

@desktop/design and @shiftkey any thoughts?

**Comment by niik** [comment]
> @desktop/design and @shiftkey any thoughts?

I concur with @shiftkey's assessment in https://github.com/desktop/desktop/issues/6646#issuecomment-454898060. This is about ensuring that the textbox always yields its space to the button and doesn't flex. I've opened https://github.com/desktop/desktop/pull/7162 to address this.
