### ISSUE TITLE
Support "Create Release" from GitHub Desktop app

### ISSUE THREAD

**Issue by leecookson** [desktop/desktop#6648]
I would like a way to do a "release" from the GitHub Desktop app

Minimum: a link to the "release" page for the current branch of the current repo

Optimal: A dialog that lets you supply release tag name, title, description, pre-release option from the app itself.

**Comment by outofambit** [comment]
Hi @leecookson thanks for filing this proposal. I'm going to label it as an enhancement. Could you provide a bit more information about your workflow? Do you usually want to release from desktop right after you commit and push on a branch? What do you usually do afterwards? Thanks again!

cc @desktop/product

**Comment by billygriffin** [comment]
Thanks @leecookson! Echoing @outofambit, I'd love to hear a bit more about your workflow specifically to help us understand this a bit better. We have https://github.com/desktop/desktop/issues/4829 which is tracking tag support in Desktop, and most folks there have communicated that they use tags to create releases and that's why they'd like support for them in the app. Is this the same thing? Thanks!

**Comment by leecookson** [comment]
The workflow is a repo of static assets (images, JS, web pages) that we sync to S3 via a webhook.  The "push" action triggers sync to a staging location, for testing.  When tests are verified, we do a "release" from the main code page, supply a tag and title, and the webhook triggers a full sync of the repo to the production environment.

Since the "push" can be done w/o visiting the repo's web page, it would be nice to complete the workflow also w/o needing to visit the repo web page.  We do both "push" and "release" webhook triggers only for master branch changes.

**Comment by leecookson** [comment]
if it triggers a webhook with action="release", that would be good

**Comment by outofambit** [comment]
@leecookson thank you for the extra information! this is very helpful. we're going to merge this discussion with the git tags discussion in #4829 as they would most likely be part of the same workflow. Thanks again for this input and let us know if you have any more feedback or suggestions!

**Comment by ocnader** [comment]
It seems like this request got lost in the discussion of #4829 . This was specifically about creating a "Release" from Github Desktop. Should this issue be reopened?

**Comment by ahmed-adly-khalil** [comment]
same here, since we already can create a tag: https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/managing-tags we should be able to create a release i guess

**Comment by MaxUint** [comment]
Has this feature been released yet? Can't seem to find it and don't know if I'm just being dumb or not

**Comment by steveward** [comment]
@frogbean we have not implemented a releases feature into GItHub Desktop yet.

**Comment by gitmachtl** [comment]
push

**Comment by vault-thirteen** [comment]
When will this functionality be added into GitHub Desktop client ?

**Comment by cashiecoder** [comment]
Is there a plan to add this anytime soon? It would be useful for me as well.

**Comment by thomascenni** [comment]
Is there a plan to add this feauture ?

**Comment by vinceingithub** [comment]
Any updates on this?

**Comment by vgzclk** [comment]
one year later still waiting.

**Comment by ghost** [comment]
Another vote for this feature.

**Comment by adferns** [comment]
+1

**Comment by Bandeco03** [comment]
+1

**Comment by mippi-the-dork** [comment]
+1
