### ISSUE TITLE
Simplify the Auth Failure modal

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6649]
When trying to perform an action any repo when you are not logged in, an auth modal is surfaced to gather credentials. These modals are the same for GitHub and Enterprise, but they should match the normal login modal which differentiates between GitHub and Enterprise.

Suggestion: we nix the Authentication modal and just apply the error messaging inline the current login modal. See mock ups below.

### Auth failure modal (current for both .com and Enterprise):
![image](https://user-images.githubusercontent.com/14828183/51281509-75493980-1997-11e9-8033-f086f4c7ff5c.png)

### Normal login modals (current):
![image](https://user-images.githubusercontent.com/14828183/51281511-77ab9380-1997-11e9-989c-57059a551615.png)
![image](https://user-images.githubusercontent.com/14828183/51281912-9eb69500-1998-11e9-9d9f-726fe0a70889.png)

### Suggested mock ups (future):
![image](https://user-images.githubusercontent.com/14828183/51281968-c60d6200-1998-11e9-9c36-881d49519f61.png)
![image](https://user-images.githubusercontent.com/14828183/51281837-6616bb80-1998-11e9-837c-498f7b96ce8a.png)

1.6.0-beta3, mac

**Comment by billygriffin** [comment]
Thanks @tierninho! I'm not super clear from your screenshots which is current state and which is suggested future state and how you get from Enterprise to Normal and visa versa.

**Comment by tierninho** [comment]
@billygriffin Added some current/future labels to above. 

The auth failure models surface if you are logged out and attempt an action like Fetch. These modals are different the the normal sign-in modals we see under Prefs. 

My suggestion is to just use the existing error messaging in the normal sign-in modals to alert the user, and therefore nix the auth failure models altogether. 

Existing use case:
- User is logged out and attempts a fetch
- Auth modal appears, user logs in
- (Why are we gathering credentials for Enterprise?)

Suggested use case:
- User is logged out and attempts a fetch
- Normal sign-in modals appear with specific error message embedded

**Comment by tierninho** [comment]
@desktop/core I suggest bumping this up to "needs fixing" as the amount of auth/login issues continues and have a modal that isn't entirely supported isn't helping in triaging the issues.

There should not be a full login (username & password) for Enterprise.

Thoughts?

**Comment by tierninho** [comment]
As part of the update, I think we ought to consider implementing a dynamic list of suggestions dependent on the origin of the repository, ie. GitHub v Enterprise.

The list below may apply across both areas but as Enterprise has a different login method, the suggestions should be tailored to such.

![Screen Shot 2019-07-18 at 3 35 45 PM](https://user-images.githubusercontent.com/14828183/61503114-3742c780-a972-11e9-88f4-81310b56f433.png)

**Comment by steveward** [comment]
Closing this out since the authentication flow has changed, and we provide a redirect to `Accounts` for the auth failure modal.
