### ISSUE TITLE
Cannot Add Project from GitLab

### ISSUE THREAD

**Issue by sararoy** [desktop/desktop#6650]
Hello, 
I have a serious issue with GitHub Desktop after the latest update. 
I can't clone my project. I have this error message : 

Cloning into '/Users/Sara/Documents/GitHub/SaladeTomatesOignons'...
error: /private/var/folders/_t/z29zg_654kn95w9vhnl1z2hw0000gp/T/AppTranslocation/F4A40CDD-5D65-41E7-B83E-E353D716DF9B/d/GitHub Desktop.app/Contents/Resources/app/static/ask-pass-trampoline.sh died of signal 10
error: unable to read askpass response from '/private/var/folders/_t/z29zg_654kn95w9vhnl1z2hw0000gp/T/AppTranslocation/F4A40CDD-5D65-41E7-B83E-E353D716DF9B/d/GitHub Desktop.app/Contents/Resources/app/static/ask-pass-trampoline.sh'
fatal: could not read Username for 'https://gitlab.insa-cvl.fr': terminal prompts disabled

Can someone help me please ?
Thank you

**Comment by steveward** [comment]
Thanks for the report @sararoy.  It looks like you are running into a similar issue that was reported in https://github.com/desktop/desktop/issues/6362. 

Are you running any antivirus software or behind any other security software that could be flagging the binaries that GitHub Desktop ships with? 

The first things I would recommend trying would be to reinstall GitHub Desktop again (reinstalling has also fixed this issue for other users). Let me know if that helps at all.

**Comment by billygriffin** [comment]
Hope you were able to get over the hump @sararoy! Since we haven't heard back, I'm going to close this out but happy to reopen if you're still having issues.
