### ISSUE TITLE
GitHub Desktop failed to launch - RangeError: "size" argument must not be larger than 2147483647

### ISSUE THREAD

**Issue by paberglund** [desktop/desktop#6655]
## Description
RangeError: "size" argument must not be larger than 2147483647
    at Function.Buffer.allocUnsafe (buffer.js:253:3)
    at Function.Buffer.concat (buffer.js:441:23)
    at ChildProcess.s.on (app\src\lib\git\spawn.ts:72:13)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

## Version
* GitHub Desktop:
Version: 1.6.0

* Operating system:
OS: Windows 6.1.7601

### Expected Behavior
It should change to the new branch without throwing an erro

### Actual Behavior
GitHub Desktop failed to launch
Only option is to Exit and restart

**Comment by steveward** [comment]
Thanks for the report @paberglund. Would you mind uploading the full log file as an attachment? I'd like to take a look and see if there's anything else in the log that may help us track down what is causing this.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. 

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by billygriffin** [comment]
Hi @paberglund, this seems really frustrating and thanks for the report. Without having a bit more information from what @steveward asked above, there's not a whole lot we can do here, so I'm going to close this issue for now, but please let us know if you're able to provide logs for when this occurred and we'd be happy to look into it further.
