### ISSUE TITLE
docs for SPACE key to toggle multiple file changes to commit

### ISSUE THREAD

**Issue by StefanoCecere** [desktop/desktop#6657]
it was really, really hard to find out that if i press the SPACE key i can toggle the selected file changes to commit

i discovered it by searching hard in this issues repository for that problem, and it was in this page https://github.com/desktop/desktop/pull/4188

should we add this feature to https://help.github.com/desktop/guides/contributing-to-projects/committing-and-reviewing-changes-to-your-project/ ?

**Comment by shiftkey** [comment]
cc @desktop/support

**Comment by billygriffin** [comment]
Thanks @StefanoCecere! This is now updated in the [docs](https://help.github.com/desktop/guides/contributing-to-projects/committing-and-reviewing-changes-to-your-project/), as shown below.

<img width="750" alt="Screen Shot 2019-03-21 at 4 40 44 PM" src="https://user-images.githubusercontent.com/5091167/54789477-308c8980-4bf8-11e9-8585-ae70424a6d27.png">
