### ISSUE TITLE
"No local changes" window flashes every time when switching between changed files

### ISSUE THREAD

**Issue by vanyakosmos** [desktop/desktop#6658]
## Version

* GitHub Desktop: 1.6.0

* Operating system: osx 10.14

## Steps to Reproduce

1. click on changed file
2. click on another changed file

### Expected Behavior

smooth change of displayed file in patch subwindow

### Actual Behavior

"No local changes" window opens and disappear before every file change.

## Additional Information

![demo](https://user-images.githubusercontent.com/16745500/51359677-7bdbcc00-1ad1-11e9-9c75-2cb4c368735a.gif)

**Comment by ysoftware** [comment]
This makes the app painful to work in.

**Comment by outofambit** [comment]
Hi @vanyakosmos! Thanks so much for filing this issue and I'm sorry you're seeing this. I was able to reproduce this locally, so I'll mark this a bug and will update this issue soon with a timeline for a fix.

**Comment by billygriffin** [comment]
Hi folks, this shipped today! Thanks for your patience - I'm curious to hear about your experience using the new feature now that it's not flashing between viewing file diffs! 😄
