### ISSUE TITLE
FATALE: Unable To Access...

### ISSUE THREAD

**Issue by ericsotelowebdesigns** [desktop/desktop#6659]
I keep getting this error when I try to "git push --set-upstream origin stepA" which is my branch I am trying to upload using GIT BASH

This is the error I continue getting: 

fatal: unable to access 'https://ericsotelowebdesigns/udemy.git/': Could not resolve host: erics otelowebdesigns
--

I'm scratching my head on this one. I am fairly new to this GITHUB thing. Can you think of anything and why your system keeps blocking the push? 

Thanks.

**Comment by outofambit** [comment]
Hi @ericsotelowebdesigns! Thanks for reaching out! Does pushing and pulling branches work from within GitHub Desktop via the UI? From that error, it sounds like there's either a network problem, but it could also be some sort of proxy/authentication issue. cc @desktop/support

**Comment by KennethSweezy** [comment]
Not sure if this is the issue, but there isn't a domain extension (.com, .org, etc) on the link you provided. This will cause it to not resolve.

**Comment by steveward** [comment]
@ericsotelowebdesigns like @KennethSweezy mentioned it looks like your remote `origin` URL is incorrect. Here's the command you can run to fix that:

`git remote set-url origin https://github.com/ericsotelowebdesigns/udemy.git`

Or if you are using GitHub Desktop to work with this repository you can go to the file menu and select `Repository` > `Repository Settings..` > `Remote` and edit the `origin` URL there. 

I'm going to close this issue out, but let us know if you have any further issues!

**Comment by ericsotelowebdesigns** [comment]
Kenneth, 


Thank you for your response. I appreciate it. Have a great weekend.

Eric Sotelo
