### ISSUE TITLE
Truncate file names more in conflict resolution modal

### ISSUE THREAD

**Issue by ampinsk** [desktop/desktop#6666]
![image_720](https://user-images.githubusercontent.com/10404068/51416658-4f569d00-1b2f-11e9-8592-3dac0f5498c3.png)

When there are long paths these file names can get a little hairy. It would be nice to follow similar truncation patterns we have elsewhere if we aren't already, such as: 

![screen shot 2019-01-18 at 2 43 52 pm](https://user-images.githubusercontent.com/10404068/51416710-84fb8600-1b2f-11e9-8d46-39f797446912.png)

cc @outofambit

**Comment by SolanPy** [comment]
It would also be nice to display a hint with the full path to the file.

**Comment by xt0rted** [comment]
The two issues I have with this dialog are the file paths are truncated way too soon for my resolution (4k and 150% scaling in win10), and there's no tool tip displaying the full value.

![image](https://user-images.githubusercontent.com/831974/63688774-42d9a780-c7d6-11e9-923a-43b7d9cf9605.png)
