### ISSUE TITLE
App Menu not hidden/disabled when viewing "Let's get started" options

### ISSUE THREAD

**Issue by cata0309** [desktop/desktop#6669]
## Description

Installed the new Github desktop app and the visual bug appears if you hover the top part of the select repository window

## Version

* GitHub Desktop:

* Operating system:
Windows 10 Pro 64x latest version

### Expected Behavior

See blank white space
### Actual Behavior

I see a menu that does nothing

**Comment by freitasbde** [comment]
![image](https://user-images.githubusercontent.com/11089795/51439561-3a574680-1cb4-11e9-9ce5-951c7dea426e.png)

**Comment by shiftkey** [comment]
I've been able to reproduce this, and with the dark theme enabled it's even more obvious:

<img width="1026" src="https://user-images.githubusercontent.com/359239/51442097-89e74380-1caf-11e9-91f0-8f4758620a7c.png">
