### ISSUE TITLE
Github enterprise log in page not loading from outside network 

### ISSUE THREAD

**Issue by nagendrapujari** [desktop/desktop#6672]
we have installed and configure Github Enterprise on debain (Ubuntu UI), we can able to access the management console (https://git.intra.com) from the ubuntu.But, we cannot access the console from outside (windows server). The github enterprise server (10.132.194.15  git.intra.com) is pinging from windows server.

Our developers are trying to access the console (https://git.intra.com) from their machine but the page was not loading. when they tried with IP and port (https://10.132.194.15:8443) the page is redirecting to management setup page. 

which files / settings do I need to change, so that our developers can able to load the actual page https://git.intra.com ? 

(we are using LDAP as sso)

**Comment by steveward** [comment]
👋 @nagendrapujari this issue tracker is for GitHub Desktop. If you need assistance with GitHub Enterprise you can contact the Enterprise support team directly through the following contact page:

https://enterprise.github.com/support

They will be able to assist you with any questions you have. I'm going to close this issue out -- let us know if we can help with anything related to GitHub Desktop!
