### ISSUE TITLE
Incorporate PR creation into "no local changes" as top level suggestion

### ISSUE THREAD

**Issue by j-f1** [desktop/desktop#6673]
**Please describe the problem you think should be solved**
When I make a commit to a repository on GitHub, I often want to create a PR from it. However, the prompt in the “No local changes” view only gives me the option to push, meaning that I have to use the menu or a keyboard shortcut to open the PR.

**[Optional] Do you have any potential solutions in mind?**

I have two ideas:

1. Add a second button to the “push changes” suggestion when the remote is a GitHub repo that allows one click to push & switch to the open PR page
1. Add another prompt for non-default branches which have been fully pushed with a button to open the PR page.

In fact, both changes could complement each other.

**Comment by shiftkey** [comment]
@j-f1 thanks for the feedback! This is something that we do want to support, but it was held back in `1.6.0` because of some inconsistencies with how we detect pull requests. #6641 has some more context:

> After using it for a while it has become evident that the underlying data source is not suitable for determining whether or not the current branch has a PR associated with it or not and we'll need to take a step back and look at ways to improve that.

I'll assign this to @niik for the moment as he was investigation the work related to this issue.

**Comment by j-f1** [comment]
Ha, read that PR description but it didn’t connect when I opened this issue.

**Comment by billygriffin** [comment]
Moving the milestone out since the surface area is a bit bigger than we thought and @niik is still working through it.
