### ISSUE TITLE
Add option - [show in git shell]

### ISSUE THREAD

**Issue by AlanCPSC** [desktop/desktop#6674]
In the latest update, I noticed GitHub Desktop now has a variety of convenience buttons. I have found myself frequently using the [show in explorer] function. I was wondering if it is possible to add a similar button [show in git shell] that opens a command prompt in the directory of the repository.

![suggestion](https://user-images.githubusercontent.com/22120384/51434743-b9993b80-1c1c-11e9-80a2-c2cff9fcbefe.png)

**Comment by shiftkey** [comment]
Marking this one as `user-research` because I'm sure there was some thinking around this and why `Open in Shell` might not have made the cut for this first iteration of the UI.

cc @desktop/product

**Comment by billygriffin** [comment]
Thanks for the idea! I would love @niik’s perspective on this as well before we make a call one way or the other. I don’t want this blank slate to be a catch all for anything and everything, but rather to thoughtfully enable workflows that make people more productive.

@alanCPSC and anyone else who is interested in this - Out of curiosity, do you frequently use the existing keyboard shortcut for this in the Repository menu? And at what times?

**Comment by say25** [comment]
I personally feel like encouraging “opening in shell” from the empty state has value. Currently doing so supports rebasing, tagging and some other workflows we currently don’t support. I also find that people that use Desktop aren’t aware of this shortcut. I’m a large proponent of this tool at work and whenever I’m pairing with someone and I open the shell with the shortcut I get a “how did you do that”

**Comment by billygriffin** [comment]
Thanks for the input y'all. We're going to regroup on this a bit more internally before deciding which way to go on this one. Generally, we want to be very intentional about how we use the "No local changes" area to ensure that it best enables the things we think make people most productive. One thing we're doing to validate that is to measure usage of the existing items (that's TBD for me to make issues for, but should happen hopefully today). And then potentially if one of them is not getting much usage at all, we might consider a swap as opposed to an addition.

**Comment by billygriffin** [comment]
Thanks for the issue @AlanCPSC and for sharing your follow up thoughts. Just to add a bit more color, it's not about minimalist design, but rather the idea that everything added is diminishing the importance of everything that was already there. So generally we prefer to be very deliberate in assessing the value proposition of something prior to implementing it. For "open in explorer/finder," the value proposition has been super clear from many of our user interviews that it's often something people are confused about and want an easier way to know how to easily get there.

In this case, there is a keyboard shortcut and menu item to do open in shell, so the question is around discoverability. We're going to be assessing the usage of the things we chose to include initially first (https://github.com/desktop/desktop/issues/6714), and we'll consider anything additional in that context. So for now at least, I'm going to close this to indicate we don't intend to support it in the near term. Thanks again for the idea and hope you'll continue to share others.

**Comment by klo1991qa** [comment]
謝謝

**Comment by feinbd** [comment]
I never use the open in explorer option.  i always use the open in shell option to run git command line things.
