### ISSUE TITLE
Line committing not work anymore

### ISSUE THREAD

**Issue by mnsrv** [desktop/desktop#6683]
## Description

I want to commit a single line, not all diff. But instead, whole file added to commit.

## Version

* GitHub Desktop: 1.6.0

* Operating system: macOS Mojave 10.14.1

## Steps to Reproduce

1. make changes in multiple lines in file
2. select a few lines, not all diff
3. press commit

### Expected Behavior

Selected lines being added to commit, rest not staged
### Actual Behavior

File with all diffs commits

## Additional Information

This worked before update.

### Logs

[2019-01-21.desktop.production.log](https://github.com/desktop/desktop/files/2779215/2019-01-21.desktop.production.log)

**Comment by shiftkey** [comment]
@mnsrv thanks for the report! Can you tell me whether the file you were changing was a new file or an existing file that is already tracked in the repository?

**Comment by outofambit** [comment]
I tried to reproduce this with both an untracked and tracked file and was not able to. 😕 @mnsrv can you share the repo and files involved? Sorry you're hitting this problem.

**Comment by mnsrv** [comment]
Sorry, my bad! Colleague added to pre-commit hook Prettier and git add. Now all works like a charm.

@shiftkey @outofambit Thank you for such a quick response 👍
