### ISSUE TITLE
deprecate React Perf extension for React Profiler 

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#6685]
Over in https://github.com/desktop/desktop/pull/6442#issuecomment-455675571 we noticed an issue with committing in development mode triggering an error that brought down the app:

```
error: [main] TypeError: Cannot read property 'stop' of undefined
    at a (chrome-extension://react-perf/page.bundle.js:1:2004)
debug: [main] Starting crash process
debug: [main] Crash process in startup
debug: [main] Crash process is ready
debug: [main] Crash process started
debug: [main] Showing crash process window
debug: [main] Got quit signal from crash process
```

To me, this reads as the React-Perf extension encountering some weird state. This is only installed when running the app in development mode:

https://github.com/desktop/desktop/blob/52ab4b91016f3e82e13361161e89cc1bffece2c5/app/src/main-process/main.ts#L503-L524

I'm not sure this is currently working, or whether it ever did, so instead I'm opening this issue to do two things:

 - remove the work that installs the `REACT_PERF` dev tools when launching the app in dev mode
 - investigate how to use the new React Profiler (requires upgrading to `react-dom` 16.5+)

Start with [this link](https://reactjs.org/docs/optimizing-performance.html#profiling-components-with-the-devtools-profiler) and then [this blog post](https://reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html) and see if this feels like something we can use in the app at development time.

**Comment by ADustyOldMuffin** [comment]
Hello @shiftkey I'd like to take a look at this if it's still open for grabs.

**Comment by say25** [comment]
@ADustyOldMuffin I assigned you
