### ISSUE TITLE
"Ignore file" uses confusing verbiage

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#6689]
**Please describe the problem you think should be solved**

When right-clicking a changed file, a context menu shows up with several options, two of which are "Ignore file" and "Ignore all files". It's not readily apparent what's actually going to happen when you click either of those. Is it going to just ignore them in Desktop? Does it add the files to your .gitignore? It's only apparent that it's the latter after you've clicked them.

<img width="226" alt="screen shot 2019-01-22 at 1 53 20 pm" src="https://user-images.githubusercontent.com/5091167/51564654-18dd9280-1e4d-11e9-9b3d-110a05acd711.png">

**[Optional] Do you have any potential solutions in mind?**

We discussed this internally and threw out a few options that attempt to more explicitly describe what's happening for both beginners and more advanced Git users.

1. "Ignore file with .gitignore" / "Ignore all .gradle files with .gitignore"
2. "Ignore file (add to .gitignore)" / "Ignore all .gradle files (add to .gitignore)"
3. "Ignore file in Git" / "Ignore all .gradle files in Git"

I think all of them are improvements over what we have today, but I'm curious if there are any other thoughts or considerations. The length of the "Ignore all..." for (1) and (2) above doesn't feel great, but maybe ok?

When we settle on something, this feels like something that could be a `good-first-issue`.

**Comment by PaulViola** [comment]
I'd like to take a stab at this issue, thank you!

**Comment by billygriffin** [comment]
Hey @PaulViola, thanks for your interest and enthusiasm - I love it! 🎉 

Would you mind weighing in on the question of what verbiage you think we should use and why? I'd love to hear a few perspectives first before we implement any one of them. 😄

**Comment by billygriffin** [comment]
@PaulViola Thanks! If you're game, I think it might be helpful to see a screenshot of what the context menu might look like if updated to those options to get a feel for the length and whether it makes it feel super clunky. Would you mind posting a couple here for people to react to?

**Comment by PaulViola** [comment]
I'm happy to help! Here are the screenshots.

> "Ignore file with .gitignore" / "Ignore all .gradle files with .gitignore"
<img width="292" alt="image" src="https://user-images.githubusercontent.com/22381339/51572832-80efa100-1e6c-11e9-8fab-55acf3f37e6b.png">

---

> "Ignore file (add to .gitignore)" / "Ignore all .gradle files (add to .gitignore)"
<img width="315" alt="option_2" src="https://user-images.githubusercontent.com/22381339/51572861-a11f6000-1e6c-11e9-8b5a-4efb0275237b.png">

---

> "Ignore file in Git" / "Ignore all .gradle files in Git"
<img width="253" alt="option_3" src="https://user-images.githubusercontent.com/22381339/51572894-b8f6e400-1e6c-11e9-9513-fc7423ccb8b1.png">

**Comment by Peter92** [comment]
I'm also liking 2, however perhaps if you don't like the length of "ignore all," instead it could be shortened to this while keeping the same meaning:

> "Ignore file (add to .gitignore)" / "Ignore .gradle files (add to .gitignore)"

**Comment by billygriffin** [comment]
@PaulViola As long as you're ok with folks potentially pushing back in the PR, feel free to go forth with option 2 since it seems like folks generally think that's a good idea. It doesn't strike me as wildly long to where it's problematic visually. Thanks for showing us the options!
