### ISSUE TITLE
binary file merge conflicts detection broken

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#6693]
version: Desktop `1.6.0`, `1.5.1`

## Steps to reproduce:

1. create a `bothModified` conflict for an image file
(create image in base branch, then edit in a feature branch and base branch, merge)
2. take no action to resolve conflicts

## Current Result:

<img width="537" alt="screen shot 2019-01-23 at 7 07 46 am" src="https://user-images.githubusercontent.com/964912/51615872-c00a0a80-1edd-11e9-8e2f-c7ade182ee86.png">

## Desired Result:

Detect that this is a binary conflict and offer command line resolutions (or #6062)

## Notes

blocks #6062

**Comment by hfsam** [comment]
对不起，我不明白!
