### ISSUE TITLE
Add Lua and Fortran syntax highlighting.

### ISSUE THREAD

**Issue by SimpleBinary** [desktop/desktop#6700]
# Add Lua and Fortran 

1. Open a Lua and Fortran file and find that there is no syntax highlighting.

 I have wired up VB syntax highlighting, so I know how to do it and Lua and Fortran are included in codemirror. 

I have opened up this discussion to make sure I can add it.

**Comment by SimpleBinary** [comment]
If discussion is started, I will
1. Add the files to highlighter-tests
2. Add the languages to the list in `/docs/technical/syntax-highlighting.md`
3. Wireup logic in `/app/src/highlighter/index.ts`

I'm just checking that is everything.

**Comment by billygriffin** [comment]
@SimpleBinary Thanks for the issue! Just so I'm understanding correctly, you're saying you'd like to add syntax highlighting in Desktop for Lua and Fortran, and that the capability exists in CodeMirror - and you're opening the issue to start a conversation and make sure we're 👍 on it before submitting a PR? 

If so, I don't see any reason why we can't support this, but I'd love someone from @desktop/engineering to weigh in to be sure.

**Comment by SimpleBinary** [comment]
@billygriffin Exactly, I'm just making sure you're 👍 before submitting a PR. Ok, I'll wait for someone from @desktop/engineering to be sure.

**Comment by shiftkey** [comment]
@SimpleBinary @billygriffin sounds good to me!
