### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by CreativeRobotics** [desktop/desktop#6705]
## Description

Github desktop stopped working on my Windows 10 laptop yesterday. It would refuse to launch at all when you try the first time, then try a second time and it will produce a blank white window. Killing the app returns to the state where it won't launch at all until the second attempt where it produces a blank window again.

I uninstalled everything and reinstalled - NO CHANGE.

## Version
* GitHub Desktop:
File version 1.6.1.0

* Operating system:
WIndows 10 Microsoft Windows [Version 10.0.17134.523]

## Steps to Reproduce
Install github desktop
Launch github desktop
### Expected Behavior
The app will launch
### Actual Behavior
1 App fails to launch on first attempt
2 App creates a blank white window on second attempt
3 Killing the app returns us to 1
### Logs
2019-01-24T09:47:22.635Z - info: [main] Received possible protocol arguments: 1
2019-01-24T09:50:09.555Z - info: [main] Received possible protocol arguments: 3
2019-01-24T09:50:09.557Z - info: [main] Processing protocol url
2019-01-24T10:14:58.398Z - info: [main] Received possible protocol arguments: 2
2019-01-24T10:16:08.043Z - info: [main] Received possible protocol arguments: 1
2019-01-24T10:16:47.702Z - info: [main] Received possible protocol arguments: 2

**Comment by CreativeRobotics** [comment]
Ok, I got it working by uninstalling and then manually deleting all github related directorues in the roaming and local directories, then reinstalling the app.

**Comment by steveward** [comment]
Thanks for the report @CreativeRobotics. It sounds like you ran into https://github.com/desktop/desktop/issues/4054. I'm going to close this issue out, but please feel free to follow along in that issue for updates about this bug.

**Comment by CreativeRobotics** [comment]
So after using it twice the issue cropped up again - at this point if this continues I would regard the application as totally unuseable on windows 10.

**Comment by steveward** [comment]
@CreativeRobotics I'm sorry for the trouble. Unfortunately this specific issue has been difficult for us to reproduce directly, but we are tracking it in #4054. You can follow [these specific steps](https://github.com/desktop/desktop/issues/4054#issuecomment-367567297) to get things working without needing to fully uninstall GitHub Desktop.
