### ISSUE TITLE
github went crazy

### ISSUE THREAD

**Issue by karinz1993** [desktop/desktop#6708]
watch the vidoe please
https://streamable.com/l445w

I tried to do restart the computer, delete the software and re-install, sign out the account and sign in...
nothing helps...

**please help me :(**

**Comment by steveward** [comment]
@karinz1993 can you try to reset GitHub Desktop by following these steps?

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop

Let us know if that gets things working.

**Comment by tierninho** [comment]
@karinz1993 As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. 

Please follow along in https://github.com/desktop/desktop/issues/6670 as it appears to be the same issue. Thank you.
