### ISSUE TITLE
Main Menu has become inaccessible on Windows 8.1

### ISSUE THREAD

**Issue by 0xfeeddeadbeef** [desktop/desktop#6709]
## Description

After the latest GitHub Desktop update, the main menu has become inaccessible. Neither mouse nor keyboard works anymore.

## Version

* GitHub Desktop: 1.6.1   (Funny thing is, 'About GitHub Desktop' menu item is not accessible)

* Operating system: Microsoft Windows [Version 6.3.9600]

## Steps to Reproduce

1. Launch GitHub Desktop
2. Try to click on any main menu items using mouse or keyboard accelerators.

### Expected Behavior

Menus should 'drop down'.

### Actual Behavior

Look at this screen recording where I am clicking on menu items but menus do not appear:

![mijcvl89kh](https://user-images.githubusercontent.com/732366/51708182-a6cba000-203c-11e9-87bf-dfabcc8c4d1e.gif)

### Logs

I don't see anything useful in logs.
[2019-01-24.desktop.production.log](https://github.com/desktop/desktop/files/2793605/2019-01-24.desktop.production.log)

**Comment by 0xfeeddeadbeef** [comment]
Apparently, this is just new UX: menus will activate after opening a repository.

**Comment by shiftkey** [comment]
@0xfeeddeadbeef there was an earlier report of this in #6669, and we talked about how this wasn't the intended behaviour. The next update will contain #6687 which hides the menu completely.

**Comment by 0xfeeddeadbeef** [comment]
> @0xfeeddeadbeef there was an earlier report of this in #6669, and we talked about how this wasn't the intended behaviour. The next update will contain #6687 which hides the menu completely.

Oh, nice. Looking forward to it.

I've searched for any similar issues before posting this — did not know it was called 'App Menu'.

**Comment by larskuerten** [comment]
So? february 13 and still not working (windows 10 64)

**Comment by shiftkey** [comment]
@larskuerten we're on track to release this morning PST (yay timezones)
