### ISSUE TITLE
Enterprise self-signed/untrusted certificate support

### ISSUE THREAD

**Issue by niik** [desktop/desktop#671]
Refs #667 

It's not uncommon for GitHub Enterprise instances to run with a self-signed certificate or certificate signed by a non-authorative CA. There's several reasons why that might be true. These include:

 * a freshly launched GHE instance like a trial
 * of our AWS/Azure templates which generate a self-signed certificate on launch
 * GHE instances which run on non TLD domains (like ghe.lan) for which no CA will give out a certificate

We need to make sure that our enterprise sign in flow can handle an untrusted certificate and present enough information that the user can make an informed decision about whether to trust it permanently. I don't know how this works on Mac, maybe it's already taken care by the system, but on Windows we're going to have to do a bit of work for this to work nicely.

First, we need a way of installing a certificate into the appropriate certificate store. Second, we need a way of keeping the curl ca-bundle file in sync with the certificate store. This all works in the current version on Desktop on Windows. The implementation for the order of certificates in the ca-bundle is rather finicky but luckily we have a reference implementation in [MsysGitCertificateInstaller.cs](https://github.com/github/Windows/blob/master/GitHub/Helpers/MsysGitCertificateInstaller.cs) as well as a starting point for installing certificates in the store ([SystemCertificateInstaller.cs](https://github.com/github/Windows/blob/master/GitHub/Helpers/SystemCertificateInstaller.cs)). I'm assuming this will require us to write some native helpers on Windows.

This is the current flow on Windows

![](https://i.github-camo.com/bcefd88394c17e1cb26c6f179cdb477277552cf4/68747470733a2f2f636c6f75642e67697468756275736572636f6e74656e742e636f6d2f6173736574732f3633343036332f343938323434342f64393164636235342d363931322d313165342d383463632d3339326633323731653232352e676966)

**Comment by sgredell** [comment]
I'm encountering a self-signed cert error when attempting to clone from Github Enterprise in 0.8.0

**GitHub Desktop version:** 0.8.0

**OS version:** Windows 10

I am now able to login, but unable to clone a repository.

```
Cloning into 'C:\Users\steve.gredell\Documents\GitHub\analytics-pipeline'...
fatal: unable to access 'https://<enterprise-server>/<org>/<repo-name>.git/': SSL certificate problem: self signed certificate in certificate chain
```

I haven't been keeping up with the Beta version, but a coworker informed me that last week he was able to login and clone from our enterprise server with no issues.  Is there a way to get at older (windows) versions of Desktop Beta to test this?  

Also let me know if you'd rather I make a new issue.

**Comment by w60001** [comment]
I'm also seeing a regression on this in 0.8.0, which just started popping up after an auto-update to the latest GitHub Desktop version this morning.

**Comment by shiftkey** [comment]
@sgredell @w60001 it looks like someone opened #2514 to track this - please add your notes there.
