### ISSUE TITLE
GitHub Desktop Using Old Profile Picture Even After Removing Picture

### ISSUE THREAD

**Issue by Doppp** [desktop/desktop#6725]
## Description
I removed my old profile picture from GitHub and on my web profile it shows the identicon. However, my desktop app is not updated to reflect that. It still shows my previous picture from Gravatar. Signing in and out of the app doesn't change the picture.

## Version
* GitHub Desktop: 1.6.1
* Operating system: Microsoft Windows 10 Version 10.0.17134.523

### Expected Behavior
The profile picture in my desktop app should be showing an identicon and not my old profile picture.

### Actual Behavior
See the red box on the bottom left of the attached screenshot:

![bug333](https://user-images.githubusercontent.com/627410/51784629-d71f5580-2186-11e9-9422-b80c05dcdedf.png)

This should be updated with my current identicon since I removed the old profile picture.

**Comment by steveward** [comment]
Thanks for the report @Doppp. This is likely due to your old avatar being cached -- you should be able to fix this by manually deleting the `GitHubUserDatabase` in Developer Tools. Here's how to do that:

1. Go to the menu in GitHub Desktop and select `View` > `Toggle Developer Tools`
2. Go to `Storage` > `IndexedDB` > `GitHubUserDatabase`
3. Select `Delete database`
4. Close and restart GitHub Desktop

That should hopefully update your avatar -- let me know if it doesn't help.

**Comment by Doppp** [comment]
Apologies @steveward, I can't find `Storage` > `IndexDB` > `GitHubUserDatabase`.

After selective `View` > `Toggle Developer Tools`, I get the following:

![dev](https://user-images.githubusercontent.com/627410/51878722-9b190a00-23ab-11e9-9bc2-4bb4396173f0.png)

**Comment by KennethSweezy** [comment]
Hmm, I am unsure about why it didn't update... Maybe it is cached somewhere else?

**Comment by tierninho** [comment]
@Doppp It still appears to be a caching issue on your computer, as I can see your new identicon.

<img width="193" alt="screen shot 2019-01-29 at 11 18 10 am" src="https://user-images.githubusercontent.com/14828183/51934368-4203a300-23b8-11e9-9a40-1ee4f2e7882d.png">

Have you tried signing out then back in to your account on Desktop? I'd also suggest switching to a new repo. See the Options menu item to sign in/out.

**Comment by Doppp** [comment]
Yeah I also signed in and out and switched repos. Very odd. Not sure where else it's cached on my computer.

**Comment by Doppp** [comment]
Note: Uninstalling and reinstalling the app also doesn't solve this issue.

**Comment by Doppp** [comment]
I managed to solve this by deleting the app, deleting everything in `C:\Users\<username>\AppData\Local\GitHubDesktop` and `C:\Users\<username>\AppData\Roaming\GitHub Desktop` and then doing a clean install of the app. Thanks all!

**Comment by stefanjohncollier** [comment]
> Thanks for the report @Doppp. This is likely due to your old avatar being cached -- you should be able to fix this by manually deleting the `GitHubUserDatabase` in Developer Tools. Here's how to do that:
> 
> 1. Go to the menu in GitHub Desktop and select `View` > `Toggle Developer Tools`
> 2. Go to `Storage` > `IndexedDB` > `GitHubUserDatabase`
> 3. Select `Delete database`
> 4. Close and restart GitHub Desktop
> 
> That should hopefully update your avatar -- let me know if it doesn't help.

I had the same issue however these instructions worked for me. Thanks!

GitHub Desktop version: 2.1.0
System Version: macOS 10.14.5

**Comment by FengTianShi** [comment]
@steveward 
Greate job!

**Comment by clubby789** [comment]
> 2. Go to `Storage` > `IndexedDB` > `GitHubUserDatabase`

It was in `Application` > `IndexedDB` > `GitHubUserDatabase` for me, so try looking there as well

**Comment by xluludaci** [comment]
I found out the only thing making the suggested deletion not work is that the email address linking to web-based Git operations is wrong! You'd better check at `Emails Settings` and write it correctly in Github Desktop. 

The email address could be changed if you modify your username as I did, and the system might automatically (but unexpectedly) add some numbers and symbols in front of your username to make the new default email address e.g. 32718+[your_user_name]@users.noreply.github.com. If you instead fill [your_user_name]@users.noreply.github.com, then you won't see the deletion working.

**Comment by xluludaci** [comment]
I found out the only thing making the suggested deletion not work is that the email address linking to web-based Git operations is wrong! You'd better check at [Email settings](https://github.com/settings/emails) and write it correctly in Github Desktop.

The email address could be changed if you modify your username as I did, and the system might automatically (but unexpectedly) add some numbers and symbols in front of your username to make the new default email address e.g. 32718+[your_user_name]@users.noreply.github.com. If you instead fill [your_user_name]@users.noreply.github.com, then you won't see the deletion working.

**Comment by marcinbogiel** [comment]
I run Github Desktop 2.1.3 on macOS Mojave (10.14.6). What I did to fix the issue:

1) Make sure that you pushed all your commits to remote repository (just in case)
2) Open`View` > `Toggle Developer Tools` 
3) In new window in 'Application' section pick 'Clear storage' > 'Clear site data'
4) Close Github Desktop 
5) Check your email address available on your github profile
6) Open Github Desktop
7) Log to your Github account and make sure you put correct email address
8) Find your repository and open it

That worked for me. I think that my problem was putting different email address than the one available on my github profile.

**Comment by justinputney** [comment]
It finally worked for me to "Clear Storage" but that removed all 15 or so of my repos and I had to re-add them one-at-a-time.

**Comment by steveward** [comment]
@justinputney glad to hear that got things working. For reference you can drag-and-drop multiple selected repositories into GitHub Desktop to add them.

**Comment by justinputney** [comment]
@steveward Good to know. I didn't have much luck trying to select multiple items, but I'll keep it in mind for the future.

**Comment by mahrcheen** [comment]
I had some random identicon after changing login and email - deleting \AppData\Roaming\GitHub Desktop helped me as @Doppp said
