### ISSUE TITLE
Diff highlighting in split view

### ISSUE THREAD

**Issue by rmsmani** [desktop/desktop#6726]
Currently GitHub shows the diff in the united view.  As a developer it's good to have the different in the split view (ie display the changes side-by-side)

**Comment by shiftkey** [comment]
@rmsmani thanks for the feedback. We're tracking this over in #172 (you might not have seen it because it's closed, but it's marked `future-proposal` so we can track it), so please follow along with that issue.

**Comment by rmsmani** [comment]
@shiftkey
Thanks for the consideration
