### ISSUE TITLE
Git clone fails with timeout

### ISSUE THREAD

**Issue by kkadane** [desktop/desktop#6729]
## Description

I'm not able to clone code using Github Desktop. Cloning fails with "Failed to connect to 172.30.0.7 port 3128: Timed out"

## Version

* GitHub Desktop:

* Operating system:

**Comment by kkadane** [comment]
I do not use any proxy settings on my windows laptop

**Comment by shiftkey** [comment]
@kkadane thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.
