### ISSUE TITLE
Diff font selection

### ISSUE THREAD

**Issue by damieng** [desktop/desktop#673]
Many developers have a very specific font they like to use for their code.

Can we get an option to allow users to specify their own for the diff view?

**Comment by damieng** [comment]
Closing now the new desktop is out.

**Comment by karuppasamy** [comment]
would like to reopen this, as I don't see the option to choose/use system fonts for the code display. 

@niik @joshaber

**Comment by j-f1** [comment]
I really like [Fira Code](https://GitHub.com/tonsky/FiraCode). If we can’t add a setting, could Fira Code be prepended to the list so anyone with it installed will use it?

**Comment by markm77** [comment]
Agree would be great to be able to configure diff font type and size. I happen to like Fira Code with ligatures.
