### ISSUE TITLE
Auto start Github desktop when system starts

### ISSUE THREAD

**Issue by ELO1SA** [desktop/desktop#6731]
I suggest the Github Desktop app to include auto startup feature. I understand that this could be manually solved by adding a shortcut into the startup folder. However, I do think it would be much nicer to have this function available in one-click in settings since probably a lot of users using this app are going to need it almost everytime that they start their computer(myself included). 

On the other hand, such feature could always be disabled by any user who doesn't like/need such functionality.

**Comment by shiftkey** [comment]
@ELO1SA thanks for the suggestion! We don't currently have plans to support this, and it's not clear to us how much interest there is in the feature.

As a workaround I'll point to [this guide](https://lifehacker.com/how-to-start-a-program-automatically-when-your-computer-5829375) for macOS and Windows. On Windows you can point to the executable at `C:\Users\[account]\AppData\Local\GitHubDesktop\GitHubDesktop.exe` (which should launch the latest version of the app).
