### ISSUE TITLE
[Layout Error] The button is hidden when the repository list too narrow

### ISSUE THREAD

**Issue by dacapoday** [desktop/desktop#6732]
## Description
When setting the left panel to the minimum width, and click the "Current repository". I found that the "Add" button could not be fully displayed. this also happens in dark theme.

![image](https://user-images.githubusercontent.com/9378047/51819596-f4326080-230d-11e9-9b10-c56182b6252f.png)

## Version
* GitHub Desktop: 1.6.1 
* Operating system: Windows 10

**Comment by shiftkey** [comment]
@dacapoday thanks for the report!

This feels very similar to #6646, so I'm going to cross-reference that there rather than track this as a separate issue.
