### ISSUE TITLE
Repo titles changing and syncing with other repos on github desktop

### ISSUE THREAD

**Issue by legoman8304** [desktop/desktop#6734]
I’m having a continuous problem with my GitHub desktop (windows 10, GitHub desktop build 1.6.1). This is much like error #5055 but the steps used there do not work for me. I have a repo (let’s call it repo A) that I have made a website by hand on. Uploading all the files and changes. I also have another repo (repo B) which I am trying to use with GitHub pages to host my site temporarily. Now when I try to clone repo B (currently empty) onto my desktop it instantly changes the name of repo B to the name of repo A and syncing the files between them, hence rendering it useless for GitHub pages as repo B must be named “_username_.github.io” to host. Why is this happening and how do I fix it. Thanks!

**Comment by steveward** [comment]
Thanks for the report @legoman8304. The local repository name should reflect the remote repository name when cloning a repository from GitHub, but a repository can point to a repository `origin` URL that has a different name than the local repository. 

A few questions:
- Have you tried cloning the repository to a different directory to see if you you can reproduce this issue?
- Can you share the specific directory structure of where you are trying to clone this repository?
- If you go to the menu in GitHub Desktop and select `Repository` > `Repository Settings` > `Remote` is the URL there pointing to the correct remote repository on GitHub?

**Comment by steveward** [comment]
@legoman8304 it would also be helpful if you could upload the log file from GitHub Desktop.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. 

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by steveward** [comment]
Thanks for sending over the logs @legoman8304. Here's what I'm seeing in the log:

```

2019-01-29T13:17:06.951Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/legoman8304/Farm-Bureau-Site.git - legoman8304 (has token)
2019-01-29T13:17:19.389Z - info: [ui] Executing clone: git -c credential.helper= clone --recursive --progress -- https://github.com/legoman8304/Farm-Bureau-Site.git C:\Users\nultonw1\Desktop\Coding\GHUB\legoman8304.github.io 
```

It looks like you are cloning the `Farm-Bureau-Site` into the `legoman8304.github.io` directory -- are you expecting `legoman8304.github.io` to be the local repository name? 

For reference, if you are trying to use GitHub Pages you can either do a project page or a user page:

https://help.github.com/articles/user-organization-and-project-pages/

The GitHub Pages user page requires the `<username>.github.io` naming convention, but a project page does not.

**Comment by steveward** [comment]
Apologies for the delay @legoman8304. Can you share the config information of that repository? 

1. Open the repository in the command line (Menu > `Repository` > `Open in command prompt`)
2. Run the command `git config --local --list`
3. Share the output of that command in a reply 

To try and get things working again you can clear the cached data that GitHub Desktop stores. Here's how to do that:

1. Close GitHub Desktop
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop -- you will need to log in and add your repositories again.
4. Try cloning the repository to your local machine

Let me know if that fixes this issue.

**Comment by legoman8304** [comment]
Here is the output of `git config --local --list`
```
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
submodule.active=.
remote.origin.url=https://github.com/legoman8304/Farm-Bureau-Site.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
branch.dev.remote=origin
branch.dev.merge=refs/heads/dev
branch.PR-test-branch.remote=origin
branch.PR-test-branch.merge=refs/heads/PR-test-branch
atomgithub.historysha=983bffda6cf5dd4dd3263f50080b7a83097963ce
```

and as for your second solution, should this be the folder I'm deleting the files from, I don't want to screw something up. 
![](https://user-images.githubusercontent.com/43346988/52379037-4e7ea000-2a37-11e9-858f-2494247b94f6.PNG)

**Comment by legoman8304** [comment]
Hello? I understand you all could be busy, but I've been waiting for 9 days now with no answer. I know someone has viewed it too, the label support was added 4 days ago, so please get back to me as soon as possible

**Comment by steveward** [comment]
@legoman8304 that is the correct directory -- you can delete all of the files there. You will need to add your log in to GitHub Desktop again and add your repositories back, but it should get things working correctly.

**Comment by legoman8304** [comment]
That seemed to do the trick!! That you for your help.

**Comment by billygriffin** [comment]
Thanks @legoman8304, and sorry for the delay! We were in the midst of a release last week and things got hectic, so really appreciate your patience and the gentle nudge. Glad you got things resolved!
