### ISSUE TITLE
Error upon publishing or cloning repository

### ISSUE THREAD

**Issue by JensLodberg** [desktop/desktop#6736]
## Version

* GitHub Desktop: 1.6.1

* Operating system: Windows 10 Home version 1803

### Expected Behavior

Cloning or publishing said repository
### Actual Behavior

Error window pops up with following text:
find: '/I': No such file or directory
find: '/N': No such file or directory
find: 'SoundMixer.exe': No such file or directory
find: '/I': No such file or directory
find: '/N': No such file or directory
find: 'explorer.exe': No such file or directory
error: unable to read askpass response from 'C:\Users\Jens\AppData\Local\GitHubDesktop\app-1.6.1\resources\app\static\ask-pass-trampoline.bat'
fatal: could not read Username for 'https://github.com': terminal prompts disabled

After this pops up, a new file explorer window will pop up about every second until i close Github Desktop.

## Additional Information

![Error](https://user-images.githubusercontent.com/43644006/51857901-b6483300-2333-11e9-8637-b5fc00a90411.png)
### Logs

[2019-01-28.desktop.production.log](https://github.com/desktop/desktop/files/2804345/2019-01-28.desktop.production.log)

**Comment by shiftkey** [comment]
@JensLodberg thanks for the report! This feels like an old issue related to mining malware: https://github.com/desktop/desktop/issues/3604#issuecomment-352192406

Let us know if [this link](https://social.technet.microsoft.com/Forums/windows/en-US/9fb738ab-2f3d-4a07-ac8a-173d63a47f87/cmd-not-working-due-to-an-error-the-error-occurs-on-practically-everything?forum=win10itprogeneral) helps to resolve the issue.

**Comment by JensLodberg** [comment]
Yes! this was perfect, thanks so much.

**Comment by alik604** [comment]
[I used this post to remove it](https://www.reddit.com/r/Malware/comments/6y2oob/got_infected_with_some_torrent_miner_undetected/)

Note: 
1: A soundmixer.exe infected 
2: You need to change 2 Reg keys/values

**Comment by alik604** [comment]
Hey devs, would be cool to notify the user they might have a virus. 

I was too busy with life, and let the miner go uncheck and running-rampant for a few weeks.
