### ISSUE TITLE
App barely responds

### ISSUE THREAD

**Issue by ericwilliamsneu** [desktop/desktop#6738]
## Description

After a long time away from the Desktop app, I've attempted to open it up with the intent of cloning some additional repositories. After waiting about 30 minutes for the app to become responsive, I killed the task and launched it again to the same results. Uninstalled and reinstalled, which took about an hour, only to find the same behavior. When the GUI finally loads, it's stuck spinning on "Refreshing repository..."

Basic functionality like Windows minimize, maximize, and close do not respond to mouse-over events, and then I do click it takes about 5 minutes to respond.

All other software on the machine is running normally.

## Version

* GitHub Desktop: Can't access 

* Operating system: Windows 10 Version 1809

## Steps to Reproduce

1. `Open GitHub Desktop App`
2. `Interact with the software`
### Expected Behavior

It responds.
### Actual Behavior

It doesn't respond.

**Comment by steveward** [comment]
Thanks for the report @ericwilliamsneu. Could you upload a log file from the day you launched GitHub Desktop? That should give us some more information about what may be causing this slowdown.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. 

The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue.

**Comment by tierninho** [comment]
@ericwilliamsneu As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
