### ISSUE TITLE
Version error

### ISSUE THREAD

**Issue by mbenlarb** [desktop/desktop#6748]
Github desktop keeps on showing this error when fetching : "Version error : the requested version (30) is less then the existing version (40)"

**Comment by billygriffin** [comment]
Hi @mbenlarb! Would you mind filling out the template included when you make a new issue to help us troubleshoot? We ask for this so we our maintainers have enough information to properly diagnose and hopefully fix problems when they occur. You can find the template [here](https://github.com/desktop/desktop/issues/new?template=bug_report.md) and respond to this issue with those extra details. Thanks for understanding and meeting us halfway! 😄
