### ISSUE TITLE
GitHub Desktop on my windows 7 laptop can not be installed,no error can be seen

### ISSUE THREAD

**Issue by xieyong8410** [desktop/desktop#6759]
I  have a  problem, how can I solve it?
Description

I'm trying to install and run GitHub Desktop on my windows 7 laptop. I spent two hours trying to just install the software, the process goes as follows:

Launch the GitHubDesktopSetup.exe file (latest one available from the website).
The installer frame pops up that says "GitHub Desktop is installing and will launch when it's finished."
The installer frame disappears and nothing happens.

**Comment by steveward** [comment]
Thanks for the report @xieyong8410. To get some more information about why the installation is failing it would be helpful if you could send over the log file that the Squirrel installer generates.

You should be able to find the log file here:

`%LocalAppData%\GitHubDesktop\SquirrelSetup.log`

If no log file is being generated there you should be able to find one in the `SquirrelTemp` directory:

`%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

Please upload that file as an attachment.

**Comment by xieyong8410** [comment]
Here are the log file is being generated there you should be able to find one in the SquirrelTemp directory:

%LocalAppData%\SquirrelTemp\SquirrelSetup.log

 Thank you so much!
[SquirrelSetup.log](https://github.com/desktop/desktop/files/2823976/SquirrelSetup.log)

**Comment by steveward** [comment]
@xieyong8410 apologies for the delay. Are you possibly running a 32-bit version of Windows 7? At this time GitHub Desktop only supports 64-bit versions of Windows, so if you are on a 32-bit version that could be the reason the installation is failing. Let me know if that is the case.

**Comment by xieyong8410** [comment]
Thank you so much for your reply. I am using the 64-bit version of Windows.

**Comment by steveward** [comment]
@xieyong8410 apologies for the delay. Are you running any antivirus or other security software that could be preventing GitHub Desktop from installing correctly on this machine?

Could you also open File Explorer and go to `%LocalAppData%` to see if there is a `GitHubDesktop` directory? If there is, open that directory to see if there are files/folders in there. That would help narrow down if the installation process is failing to even start at all.

**Comment by niik** [comment]
Hi @xieyong8410, we haven't heard back from you in a while so I'm going to close this issue for now. Feel free to add a comment if your issue hasn't been resolved and we'll revisit it.

**Comment by benhichem** [comment]
im having the same problem tbh 
im running a windows 7-64bits  ,(
so please anyone that can help

**Comment by benhichem** [comment]
im having the same problem tbh 
im running a windows 7-64bits  ,(
so please anyone that can help

**Comment by steveward** [comment]
@benhichem please open a new issue and share the installation log file that is generated when the installation fails. Thanks!

**Comment by TheAce74** [comment]
I've been trying to install github desktop on my computer but this error code always shows and halts the installation
![error](https://user-images.githubusercontent.com/101275024/163999647-ffdef72f-c945-4488-8134-deab40e03ba6.jpg)
Please help me

**Comment by TheAce74** [comment]
![image](https://user-images.githubusercontent.com/101275024/164000159-5644bf75-b003-4e04-a7ed-2c9550ad0bad.png)
I'm operating a 64-bit windows 7 system

**Comment by steveward** [comment]
@TheAce74 you likely need some specific updates. Based on a quick search you should be able to install https://www.catalog.update.microsoft.com/Search.aspx?q=KB4457144. Please note that Microsoft no longer provides support for Windows 7.

**Comment by TheAce74** [comment]
Thanks @steveward I'll try that

**Comment by pallarajasekhar** [comment]
same probleam any solution plz  tell me ... windows 7 not installed   u have ay solution share the tips

**Comment by steveward** [comment]
@pallarajasekhar if you are having issues installing GitHub Desktop please open a new issue and fill out the template. Thanks!

**Comment by pallarajasekhar** [comment]
see the pic sir  sir iam  .net installing
 but not support my window7 sir 
![WhatsApp Image 2022-07-19 at 6 36 24 PM](https://user-images.githubusercontent.com/109082073/179757734-964b36db-4bd4-4f0c-9aa8-b8561ebe4800.jpeg)

**Comment by pallarajasekhar** [comment]
@steveward sir github also not supporting sir 64 bit not supporting window 7 sir plz any sloution plz share me sir

**Comment by steveward** [comment]
@pallarajasekhar unfortunately Windows 7 is no longer officially supported. I'm sorry that I don't have better news.

**Comment by Ob22** [comment]
> @xieyong8410 apologies for the delay. Are you possibly running a 32-bit version of Windows 7? At this time GitHub Desktop only supports 64-bit versions of Windows, so if you are on a 32-bit version that could be the reason the installation is failing. Let me know if that is the case.

Im running32 bit is there a way i download
