### ISSUE TITLE
Cant sign into git hub account

### ISSUE THREAD

**Issue by premkumarsekaran** [desktop/desktop#6761]
## Description

Cloning repo in GitHub would keep asking for authentication.

## Version

* GitHub Desktop: 1.6.1

* Operating system:

**Comment by billygriffin** [comment]
@premkumarsekaran Thanks for the issue and sorry you're having problems signing in - since we haven't heard back from you, I'm going to close this issue for now, but we're happy to reopen and investigate if you're able to fill out the rest of the template and respond here so we know it's updated.
