### ISSUE TITLE
upgrade to latest stable React

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#6763]
We are currently on `16.3` in Desktop and `16.7` is the latest stable version, but it would be nice to time the upgrade with a feature that would benefit from upgrading.

We identified some friction with the upgrade in https://github.com/desktop/desktop/issues/6226#issuecomment-447849048, which shows a working commit to upgrade to `16.4` - adding an explicit `@types/prop-types` devDependency might also be needed.

**Comment by outofambit** [comment]
> You could wait until 16.8 is released with hooks, which should be Real Soon Now™.

It's out! :D

**Comment by steveward** [comment]
Closing this out since https://github.com/desktop/desktop/pull/7050 happened.
