### ISSUE TITLE
'Publish your branch' message erroneously reports that branch has not been published

### ISSUE THREAD

**Issue by zeke** [desktop/desktop#6765]
## Description

I'm seeing a 'Publish your branch' suggestion that says my current branch hasn't been published to the remote yet, but the branch has been published (over a day ago).

<img width="667" alt="screen shot 2019-02-03 at 10 15 18 pm" src="https://user-images.githubusercontent.com/2289/52193086-32de8400-2802-11e9-9e19-8c008818ed97.png">

Evidence of the branch's existence on the remote:

<img width="856" alt="screen shot 2019-02-03 at 10 15 27 pm" src="https://user-images.githubusercontent.com/2289/52193060-0f1b3e00-2802-11e9-8b1c-8623921ba3e9.png">

## Version

* GitHub Desktop: 1.6.1
* Operating system: macOS 10.12.6

**Comment by zeke** [comment]
Maybe this is causing it:

<img width="663" alt="screen shot 2019-02-03 at 10 28 42 pm" src="https://user-images.githubusercontent.com/2289/52193278-4c340000-2803-11e9-86e7-6b73164495e6.png">

But I'm signed in:

<img width="561" alt="screen shot 2019-02-03 at 10 30 37 pm" src="https://user-images.githubusercontent.com/2289/52193293-640b8400-2803-11e9-88d2-83a07a25a46c.png">

And I have admin access to this repo:

<img width="567" alt="screen shot 2019-02-03 at 10 29 59 pm" src="https://user-images.githubusercontent.com/2289/52193304-6e2d8280-2803-11e9-8514-786ce77b2cad.png">

**Comment by shiftkey** [comment]
@zeke thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Finder** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

Another thing to check is whether the branch is configured to track a remote:

```
$ git status --porcelain=2 --branch
# branch.oid 96eb4a8894f048cb997d86ae413f3d0bfc33be38
# branch.head development
# branch.upstream origin/development
# branch.ab +0 -0
```

Could you run that command against the problem repository and share what it returns?

**Comment by zeke** [comment]
```
$ git status --porcelain=2 --branch
# branch.oid 3b5b6c2aab22526e83404bdb2fb1f1b818698f3a
# branch.head fix-raw-liquid-tags
```

I see no `upstream`! Is that the issue?

**Comment by shiftkey** [comment]
@zeke 

> I see no `upstream`! Is that the issue?

That's precisely the issue. My psychic debugger thinks that the branch was pushed from outside Desktop, and the `-u` was omitted.

Two ways to address this:

1. set the tracking branch manually from Git

```
$ git branch -u origin/fix-raw-liquid-tags
```

2. Publish the branch in Desktop (which should no-op if the remote and local branch are named the same) which also sets the upstream.

**Comment by shiftkey** [comment]
Are you signed into Desktop? The log file has a bunch of errors about `fetch` not working for private repositories:

```
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/{owner}/{repo}/'
```

I also see this warning from the GitHub API:

```
2019-02-05T00:44:00.548Z - warn: [ui] fetchRepository: an error occurred for 'words/ologies'
Error: API rate limit exceeded for 174.214.19.43. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:161:4)
    at <anonymous>
```

**Comment by zeke** [comment]
That worked! Thanks for your perseverance. ⭐️
