### ISSUE TITLE
Push/Pull button

### ISSUE THREAD

**Issue by timtribers** [desktop/desktop#6767]
Previously reported as #2431, but closed there for some reason.

When I have made a commit, the big ribbon button changes to "Push origin" (or some such).  I click it and get an error popup saying that the Origin has changed and I need to Pull first.  Fair enough.  But the ribbon button stays saying Push, and unless I know that Pulling is an option under the Repository menu item, then I am stuck.  Couldn't the main ribbon button change to Pull under these circumstances?

(Using v1.6.1 on Windows)

Anyway, thanks for great software.

**Comment by shiftkey** [comment]
@timtribers please have a read of #2738 (which I believe is the same issue as what you are seeing) and the details I uncovered in #6610 about why I think it isn't working in some situations.

**Comment by timtribers** [comment]
Many thanks @shiftkey
