### ISSUE TITLE
Error: fatal: bad revision '^'

### ISSUE THREAD

**Issue by aenagy** [desktop/desktop#6768]
## Description

I have added a remote repository (enterprise BitBucket, using Active Directory credentials for access) and "Remote > Fetch from > origin" does not generate errors. Next I try "Merge > Local Merge" which results in an error window:

  Title: Application Error
  Body: Error: fatal: bad revision '^'
  [OK]  [Skip Messages]  [Details>>]

Details:
fatal: bad revision '^'
fatal: bad revision '^'
    while executing
"close $fr_fd"
    (procedure "_new" line 114)
    invoked from within
"_new $path 1 $title"
    (procedure "::choose_rev::new_unmerged" line 2)
    invoked from within
"::choose_rev::new_unmerged $w.rev [mc "Revision To Merge"]"
    (procedure "merge::dialog" line 30)
    invoked from within
"merge::dialog"
    (menu invoke)

While filling out this form I tried "Verify Database" and got this:

dangling tree <long hex string>
notice: HEAD points to an unborn branch (master)

## Version

* GitHub Desktop: 0.21.GITGUI

* Operating system: Windows 10 version 1709 build 16299.904

### Expected Behavior

Local copy of repository populated with files from remote repository.

I am not looking to repair my local repository. I just need to start over with a fresh copy of the remote repository. This was working before.

### Actual Behavior

See Description.

## Additional Information

This may, or may not, be related to a problem previously with the same repository's local copy not showing files in the remote repository and "Verify Database" complaining about a number of problems -- didn't save the results. Rather than spending time trying to figure out how to fix this I deleted the entire local Git repository including hidden files and folders to start over.

### Logs

There are no Git* folders in "%APPDATA%".

**Comment by shiftkey** [comment]
@aenagy thanks for the report!

```
GitHub Desktop: 0.21.GITGUI
```

This doesn't look like a version of GitHub Desktop, but is instead a version of Git GUI that comes with [Git for Windows](https://gitforwindows.org/) and can be run from the command line using `git gui`. 

Please submit an issue to their [issue tracker](https://github.com/git-for-windows/git/issues) so they can investigate it.

**Comment by aenagy** [comment]
@shiftkey 

OK, will do.

So what is the difference between GitHub Desktop and Git GUI?

**Comment by shiftkey** [comment]
@aenagy 

<img width="893" src="https://user-images.githubusercontent.com/359239/52213683-2a1f9980-2866-11e9-8196-14ff6f306956.png">

Git GUI is an inbuilt tool that ships with Git for Windows, but is part of the main Git project so it's also available on other platforms.

<img width="967" src="https://user-images.githubusercontent.com/359239/52213693-30157a80-2866-11e9-8e0b-fec42a7edd22.png">

GitHub Desktop is an Electron-based GUI tool for working with Git and GitHub repositories, and is maintained and distributed by GitHub.
