### ISSUE TITLE
stop requiring the I prefix on interfaces

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#6773]
We currently have an ESLint rule that requires every interface to be prefixed with an `I`:

https://github.com/desktop/desktop/blob/6400fd767654d62a23c79f01bbdb67214c16c0bc/.eslintrc.yml#L23-L25

This feels very .NET-ish, and I've pushed back on this often when working with TS because it felt unnecessarily ceremonial and added noise to the types we define in the codebase.

@j-f1 proposed dropping this rule in https://github.com/desktop/desktop/pull/6771#discussion_r253868470, and I'm in agreement with that, but before doing that I wanted to use this issue to:

 - hear from others about their feels
 - use this issue to clarify when we should use interfaces over regular types, using examples from the codebase

If we're in consensus, we can then figure out a plan to update these affected interfaces and then drop the rule from our ESLint configuration.

**Comment by j-f1** [comment]
That rule has an option to disallow the prefix. I’d be willing to open a PR to switch the option and update the code to match.

**Comment by shiftkey** [comment]
> It feels to me like this is purely stylistic,

This is specific to how we use TS, but there are also downstream benefits to thinking about how we shape our code. One example of a downstream benefit is the emitted JS from the TS compiler (before minimising with webpack).

Here's a trivial example comparing using interfaces compared to types:

```ts
// with interfaces and implementation - the "OO" way
interface ISomething {
    doSomething: () => void
}

class SomethingImpl implements ISomething {
    public doSomething() {
        console.log('hello world')
    }
}

// without interfaces - something closer to JS?
type Something = {
    doSomething: () => void
}

const AThing: Something = {
    doSomething: () => {
         console.log('hello world')
    }
}
```

The emitted JS for both of these approaches:

```
// with interfaces and implementation - the "OO" way
var SomethingImpl = /** @class */ (function () {
    function SomethingImpl() {
    }
    SomethingImpl.prototype.doSomething = function () {
        console.log('hello world');
    };
    return SomethingImpl;
}());
// without interfaces - something closer to JS?
var AThing = {
    doSomething: function () {
        console.log('hello world');
    }
};
```

I wanted to use this discussion to help create some guidance about "when should we use interfaces" versus "when should we avoid them" based on what we've learned, and elaborate more on the benefits here beyond aesthetics, but priorities gonna priority.
