### ISSUE TITLE
GitHub Desktop Background Color is White and unresponsive

### ISSUE THREAD

**Issue by SyedYahyaMohdSalleh** [desktop/desktop#6778]
## Description

I installed the latest version of GitHub Desktop on my development machine, Windows Server 2012 (x64 Standard). It was working fine until after I closed it. On opening it again, the background of the GitHub Desktop becomes white. None of the menu items at the top of the GitHub Desktop seems to work. I have not fully exhaustively tested it (this is my first time using it), but the rest of the functionalities seems to be working.

With the white background, I have difficulty to see what is being displayed.

I have searched through the bug report for solutions and nothing seems to work.

Some assistance is much appreciated and thank you.

## Version

* GitHub Desktop: I have no idea what version it is because the menu buttons does not work. I downloaded from the Internet today. I believe it is the latest version.

* Operating system: Windows 2012 x64 (Standard). MS WIndows Version 6.2.9200
![image](https://user-images.githubusercontent.com/20148335/52334524-de721900-2a3a-11e9-975f-21d641e56f67.png)

## Steps to Reproduce

List the steps to reproduce your issue **below** this comment
ex,
1. Launch GitHub Desktop
2. (It is displayed in white background and the menus are not functioning)

### Expected Behavior

 It is supposed to display a dark background

### Actual Behavior

A white background is displayed

## Additional Information

![image](https://user-images.githubusercontent.com/20148335/52334934-06ae4780-2a3c-11e9-89f0-d7b215ebc2ba.png)

**Comment by shiftkey** [comment]
@SyedYahyaMohdSalleh thanks for the report!

> 2\. (It is displayed in white background and the menus are not functioning)

Are you referring to #6669? If so, we have a fix in #6687 which will be available as part of the next update.

**Comment by shiftkey** [comment]
Although I'm not clear on this part:

>  It is supposed to display a dark background

Are you saying that you've been using the dark theme but on this launch it has reverted to the light theme? 

I can also see that the screen you are on - the "Let's get started" view - is the one we show when you do not have any tracked repositories. Were you expecting to have tracked repositories from a previous session?

**Comment by SyedYahyaMohdSalleh** [comment]
I have read #6669 and also #6687. My issue is similar to #6687.
So,  in that case I will wait for the next update.
Thanks for your assistance and have a great day/night.
