### ISSUE TITLE
Proble,s running aplication

### ISSUE THREAD

**Issue by mariokas** [desktop/desktop#6781]
I am obtaining this error repetedley. Can you help me how to fix it?

Application.QueueAsyncCall(@PressVirtKey, VK_BACK)

**Comment by steveward** [comment]
Thanks for contributing @mariokas. It looks like this error is related to the Lazarus Component Library, not GitHub Desktop. If you are having issues with a specific project that is hosted on GitHub I would recommend opening an issue directly in that project's issue tracker. 

If you have any questions about how to use GitHub Desktop, please let us know!

**Comment by mariokas** [comment]
Thanks for your response
