### ISSUE TITLE
Git hub Desktop: Clone failed because of "Couldnt find any repository for the account

### ISSUE THREAD

**Issue by rashhs** [desktop/desktop#6783]
## Version

* GitHub Desktop:

* Operating system:

### Actual Behavior
Clone is happening in one computer but not in other computer

**Comment by billygriffin** [comment]
Hi @rashhs, thanks for the issue. Would you mind filling out the rest of the template and responding when you do? Without that additional information, it's impossible for us to properly diagnose what might be going on. Attaching logs from a day where this occurred would be particularly helpful - they're available in the `Help` menu item in GitHub Desktop. Thanks for understanding!

**Comment by tierninho** [comment]
@rashhs As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by rashhs** [comment]
The issue still exist. Where I can find log file for this.

________________________________

**Comment by tierninho** [comment]
@rashhs Please see the Help menu in Desktop for the log files. Re-opening this issue.
