### ISSUE TITLE
Menu items not visible and unresponsive

### ISSUE THREAD

**Issue by brandonheck** [desktop/desktop#6788]
OS: Windows 10 Enterprise, version 1809, build 17763.253

Description: On "Let's Get Started!" screen, the menu bar is not readily displayed; it appears to be white on white. Mouseover reveals menu items as white text on black, but clicking items does not open the menu, only changes the rendering to white text on black (and changes back once the menu item is "deselected").

Accessing menu items via keyboard shortcuts (e.g. Alt+F to open the File menu) similarly only changes the rendering of the menu item and does not open the menu.

**Comment by brandonheck** [comment]
Screenshots for reference at https://github.com/brandonheck/GitHub-Desktop-Issue

**Comment by shiftkey** [comment]
@brandonheck thanks for the report!

This feels like it's the same issue we noticed in #6669. We've merged a fix in #6687 which will be available as part of the [`1.6.2` update](https://github.com/desktop/desktop/milestone/31) (which should be out next week) and is available on our beta channel currently.

**Comment by brandonheck** [comment]
👍 Thanks, I didn't see that one when searching the existing issues.

**Comment by BoopalanARS** [comment]
I see, still the same issue of Menu Bar is not displayed...

**Comment by steveward** [comment]
@BoopalanARS the menu will not display on the "Let's Get Started!" screen -- you will need to create/clone/add a repository to get the menu to appear. Hope that helps!

**Comment by BoopalanARS** [comment]
> @BoopalanARS the menu will not display on the "Let's Get Started!" screen -- you will need to create/clone/add a repository to get the menu to appear. Hope that helps!

Thanks Steve. It does work on clone repository.  But I have to delete my previous clone repository from desktop.
But everyday, when I open the Github Desktop session is opens blank white screen and I have to cleanup %appdata% and sign in to get started.. is there a way to fix this

**Comment by steveward** [comment]
@BoopalanARS that sounds like https://github.com/desktop/desktop/issues/4054, but I haven't seen cases where this happens after each relaunch of the app. Normally it resolves itself after deleting `%AppData%\GitHubDesktop`. Would you mind sharing this in #4054 so that we can track these cases there?
