### ISSUE TITLE
Can no longer push or pull to repository

### ISSUE THREAD

**Issue by CalanceHao** [desktop/desktop#6794]
## Description

Cannot push to origin
>Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open preferences and verify that you're signed in with an account that has permission to access this repository.

Re sign in and issue is disappear.

## Version

* GitHub Desktop: 1.6.1

* Operating system:
Mac 10.13.6

**Comment by steveward** [comment]
Thanks for the report @CalanceHao. Could you upload a log file from GitHub Desktop -- that should give us some more information about this error.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. 

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by tierninho** [comment]
@CalanceHao As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
