### ISSUE TITLE
error cloning a public repository

### ISSUE THREAD

**Issue by otuoche** [desktop/desktop#6796]
## Description

when starting to clone it will be progressing then it reaches a point where it starts
failed to clone zlux example server
failed to clone tn3760ng and so on
then it says authentication error you might have permission to clone this repository or it may have been archived check options to see whether you used the right email

## Version
1.6.1
* GitHub Desktop:
6.2.9200
* Operating system:

**Comment by steveward** [comment]
Thanks for the report @otuoche. Could you upload a log file from GitHub Desktop -- that should give us some more information about this error.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. 

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by tierninho** [comment]
@otuoche As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
