### ISSUE TITLE
The Menu is white and Not working

### ISSUE THREAD

**Issue by Wide161** [desktop/desktop#6801]
After installing GITHUB desktop and I opened it but its not working properly.The background is white and i cant see the menu and its not working also
![image](https://user-images.githubusercontent.com/19819005/52502196-0ba8fd80-2bda-11e9-8e85-44e046519415.png)

**Comment by shiftkey** [comment]
@Wide161 thanks for the report. This has been fixed in #6687 and will be available with the `1.6.2` update we're aiming to ship next week.
