### ISSUE TITLE
Add copy to clipboard icon - Request for FastTrack Binary Content Management site

### ISSUE THREAD

**Issue by v-joym** [desktop/desktop#6804]
Click an item/file in the list, Click the Properties button. In the Edit Details page, beside the URL box, can you please add an icon that one can push to copy the URL to the clipboard to make it easier to copy the URL so you can paste into the browser.

**Comment by billygriffin** [comment]
Hi @v-joym! I think you might not be in the right repository with these requests. I'm going to close this out but happy to reopen if it's in reference to GitHub Desktop. Maybe you're looking for https://github.com/Microsoft/FastTrack? Thanks!

**Comment by v-joym** [comment]
Jeff Wilkes and Jayme told me to submit both of these requests to the GitHub issues form. It’s in reference to the FastTrack Binary Content Management site - https://ftdocs-bcm-app.azurewebsites.net/

**Comment by j-f1** [comment]
Maybe they wanted you to open an issue on [the FastTrack repo](https://github.com/Microsoft/FastTrack) instead?

**Comment by v-joym** [comment]
Yes. That’s right. Thanks Jed.
