### ISSUE TITLE
Add FTOP to Workload list - Request FastTrack Binary Content Management - 2

### ISSUE THREAD

**Issue by v-joym** [desktop/desktop#6805]
Can you please add FTOP to the list of apps in the Workload box.

**Comment by billygriffin** [comment]
Hi @v-joym! I think this one may also be in the wrong repository, so I'm going to close it out, but happy to revisit if I misinterpreted. Thanks and have a great weekend!

**Comment by v-joym** [comment]
Jeff Wilkes and Jayme told me to submit both of these requests to the GitHub issues form. It’s in reference to the FastTrack Binary Content Management site - https://ftdocs-bcm-app.azurewebsites.net/

**Comment by v-joym** [comment]
The correct repo is Microsoft/fasttrack-docs<https://github.com/Microsoft/fasttrack-docs>.

Regards,
Jayme

From: Joy Miller (Experis) <Joy.Miller@microsoft.com>
Sent: Friday, February 8, 2019 5:35 PM
To: desktop/desktop <reply@reply.github.com>; desktop/desktop <desktop@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Jayme Bowers <jaymeb@microsoft.com>; Jeff Wilkes <Jeff.Wilkes@microsoft.com>
Subject: RE: [desktop/desktop] Add FTOP to Workload list - Request FastTrack Binary Content Management - 2 (#6805)

Jeff Wilkes and Jayme told me to submit both of these requests to the GitHub issues form. It's in reference to the FastTrack Binary Content Management site - https://ftdocs-bcm-app.azurewebsites.net/<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fftdocs-bcm-app.azurewebsites.net%2F&data=04%7C01%7Cjaymeb%40microsoft.com%7Cce1fd31b0bf24fc55d1a08d68e15b2d8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636852621184922916%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=7Ns2tC%2FPGSEr4nnGQKhORuLAEG3UIV8RX%2FTQBTIHn7g%3D&reserved=0>

**Comment by v-joym** [comment]
Thanks. I submitted to the correct site.

From: Jayme Bowers <jaymeb@microsoft.com>
Sent: Friday, February 8, 2019 3:53 PM
To: Joy Miller (Experis) <Joy.Miller@microsoft.com>; desktop/desktop <reply@reply.github.com>; desktop/desktop <desktop@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Jeff Wilkes <Jeff.Wilkes@microsoft.com>
Subject: RE: [desktop/desktop] Add FTOP to Workload list - Request FastTrack Binary Content Management - 2 (#6805)

The correct repo is Microsoft/fasttrack-docs<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2Ffasttrack-docs&data=02%7C01%7CJoy.Miller%40microsoft.com%7C3e3d18b04ec248fb4e6408d68e208c90%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636852667789509681&sdata=RAMuevpV86Vl5cQtmv4vWKI5ttcDFonGGM482JdKKYo%3D&reserved=0>.

Regards,
Jayme

From: Joy Miller (Experis) <Joy.Miller@microsoft.com<mailto:Joy.Miller@microsoft.com>>
Sent: Friday, February 8, 2019 5:35 PM
To: desktop/desktop <reply@reply.github.com>; desktop/desktop <desktop@noreply.github.com<mailto:desktop@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>; Jayme Bowers <jaymeb@microsoft.com<mailto:jaymeb@microsoft.com>>; Jeff Wilkes <Jeff.Wilkes@microsoft.com<mailto:Jeff.Wilkes@microsoft.com>>
Subject: RE: [desktop/desktop] Add FTOP to Workload list - Request FastTrack Binary Content Management - 2 (#6805)

Jeff Wilkes and Jayme told me to submit both of these requests to the GitHub issues form. It's in reference to the FastTrack Binary Content Management site - https://ftdocs-bcm-app.azurewebsites.net/<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fftdocs-bcm-app.azurewebsites.net%2F&data=02%7C01%7CJoy.Miller%40microsoft.com%7C3e3d18b04ec248fb4e6408d68e208c90%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636852667789519679&sdata=obtfID1l7Xo8%2BjKF4YQ8vpYzinLsc4s1%2BnsRpg99cwI%3D&reserved=0>
