### ISSUE TITLE
problem1

### ISSUE THREAD

**Issue by coder101java** [desktop/desktop#6810]
where is the command-line in github desktop?

**Comment by billygriffin** [comment]
Hi @coder101java, thanks for the issue! There's no built in command line, but you can use any shell on Windows or macOS in conjunction with the app, and GitHub Desktop will pick up the current state of your repo. There's also a menu item for opening the current repo in shell in the `Repository` menu, and you can configure your shell in `Preferences`. I'm going to close this issue, and hope that's helpful!
