### ISSUE TITLE
Add "Open in Terminal" as command in "No local changes" display

### ISSUE THREAD

**Issue by rhwood** [desktop/desktop#6814]
I like the new _No local changes_ display, especially right after I have forked a repo and opened it in Desktop:

<img width="639" alt="screen shot 2019-02-09 at 19 38 57" src="https://user-images.githubusercontent.com/297232/52528098-21362a00-2ca3-11e9-82d5-b13537fa038a.png">

However, I often find that the first thing I want to do after doing this is open a Terminal window and run the project's bootstrapping command (`npm install`, `mvn initialize`, or the like) before opening the editor (most often Visual Studio Code).

Can a command "Open in Terminal" (or some such language) be added where the red arrow is?

**Comment by shiftkey** [comment]
@rhwood thanks for the suggestion. We've had some earlier discussions about thins in #6674 and #6786. For the moment, we're not planning to add this without more insight:

> The concept of opening in shell being included is something we considered but decided to leave out of the first version. We're planning to instrument metrics for the usage of each of the actions in an upcoming release, and at that point we'll decide whether we think it's a good idea to add this as well (or as a replacement for something else)
