### ISSUE TITLE
[Suggestion] Quick select multiple changes

### ISSUE THREAD

**Issue by brownsugar** [desktop/desktop#6816]
Currently we can quick select continuous changed items, but not check them, I think it will be more convenient by adding these features:
## Bulk check continuous checkbox
1. Check the first item.
![image](https://user-images.githubusercontent.com/2935980/52586255-fcdc7800-2e71-11e9-8ac9-4a21044362ba.png)

2. Holds SHIFT key while checking another item, will auto check all items between them.
![image](https://user-images.githubusercontent.com/2935980/52586326-31e8ca80-2e72-11e9-84ad-4c0a04a3bbea.png)

Which will work like this:
![demo](https://user-images.githubusercontent.com/2935980/52586556-c0f5e280-2e72-11e9-955b-3a232d504d06.gif)

## Item quick select
In the context menu, add a item "Check N selected changes...".
![image](https://user-images.githubusercontent.com/2935980/52586792-5a24f900-2e73-11e9-8242-469e40fdabcc.png)

Click the item to quick select multiple items.
![image](https://user-images.githubusercontent.com/2935980/52586654-ff8b9d00-2e72-11e9-8640-c15979fc78dd.png)

**Comment by billygriffin** [comment]
Hi @brownsugar, thanks for the issue. Would you mind describing the problem and what you're trying to do when you run into it? I'm not sure I understand what this suggestion would enable for you or help improve your workflow, so it'd be really helpful to understand some more details about what you're trying to do when this would be useful. Thanks!

**Comment by brownsugar** [comment]
@billygriffin Hi, I've updated the details about the suggestion.

**Comment by billygriffin** [comment]
Thanks @brownsugar, that's much more clear in terms of what you're suggesting, really appreciate the screenshots! Would you mind helping us understand when you might need this and how it causes frustration in its current state?

**Comment by brownsugar** [comment]
Sometimes there are lots of changes, but I only want to select some of them, maybe files under the same directory, or just several specific files, if implement these features instead of picking one by one, it would save a lot of time.

**Comment by billygriffin** [comment]
@brownsugar Thanks for the added context. We're not opposed to considering something like this, but we haven't heard it from others as a pain point and there's some risk in additional confusion around the selection vs. checked/unchecked and which thing you're multi-selecting. Definitely open to revisiting this if we see it in usability tests and hear from other users, but for now we're going to close the issue. I know it's disappointing to be stuck with something suboptimal for your workflow, so I apologize for that.
