### ISSUE TITLE
show deployment status of branch within the app

### ISSUE THREAD

**Issue by legowerewolf** [desktop/desktop#6819]
**Please describe the problem you think should be solved**
It would be great if you could view deployment information associated with GitHub repos on desktop. 

Example:

> “What's the status of my Travis checks/deployments?"

> "Has Now finished deploying my website?"

There may also be commit statuses which might also need to be shown as part of the deployment process.

**[Optional] Do you have any potential solutions in mind?**

* There's plenty of open space on the "No local changes" view
* In the top bar with the current repository/branch/status, there's an open space on the right (when not showing a PR badge).

**Comment by billygriffin** [comment]
Hi @legowerewolf, thanks for the issue. I'm curious what your workflow looks like. For example, we do show CI for pull requests in Desktop. As a general rule, we try to be extremely rigorous for anything added as we think it takes prominence and discoverability from things already in place. So I'd love to understand how you're working and how this would be useful to you outside of the context of a pull request. Thanks!

**Comment by legowerewolf** [comment]
Mainly I'm concerned about my CI deployments. I use Now to host a couple of
different websites, and I want to just look at GitHub Desktop and see if
they've deployed well. I also use a Travis build step to push to Balena,
and again I want to see the deployment status (from Travis) directly from
GitHub Desktop.

**Comment by billygriffin** [comment]
Thanks @legowerewolf. Apologies, but I'm still a bit unclear on what exactly you're trying to achieve here. Is it that you'd like to see a higher level of granularity on the checks as opposed to an overall status of pass/fail for the branch as shown in the PR view from my last comment? I'm curious how that works for you or doesn't. Thanks!

**Comment by legowerewolf** [comment]
I'd like to see my deployment status for the master branch.

**Comment by shiftkey** [comment]
> I'd like to see my deployment status for the master branch.

Are you referring to [Deployments](https://developer.github.com/v3/repos/deployments/) that are surfaced from the GitHub API?

**Comment by legowerewolf** [comment]
I think so, yes.

**Comment by shiftkey** [comment]
@legowerewolf ok cool, then I think we're talking about a different thing to [Statuses](https://developer.github.com/v3/repos/statuses/) which is what the application is showing with each pull request. I'm going to update the issue title and body to make this clearer.

**Comment by shiftkey** [comment]
Tentatively moving this to `user-research` so @desktop/product can identify what questions they would like to ask to understand the problems this would address. Feel free to move this back to `more-information-needed` with more context if things are not clear currently.

**Comment by billygriffin** [comment]
Hi @legowerewolf - we're going to be doing a bit more research into how folks manage deploys on GitHub more broadly and how the interplay works with their local environment. Because this is such a specific request and we don't intend to do exactly what's being asked here, I'm going to close this issue. However, I would love to understand your workflow better, and how you're deploying currently between GitHub.com and your local dev environment. Anything you'd be willing to provide would be really helpful. Thanks!
