### ISSUE TITLE
[Feature request] show upstream pull request

### ISSUE THREAD

**Issue by gengjiawen** [desktop/desktop#6820]
This will be very convenient if I am collaborator to some project to review code.

**Comment by outofambit** [comment]
Hi @gengjiawen, thanks for filing this issue. To make sure I'm understanding properly, i'll rephrase:

"As a repo collaborator, I would like to see and check out upstream pull requests in GitHub Desktop so I can review other collaborators' pull requests (and provide feedback on github dot com)."

Does that sound right? If you can share more about your ideal workflow, that would be great context for us to have. After you look at a pull request locally, what do you do next? Thank you!

**Comment by gengjiawen** [comment]
Take `react-native` for example, I am the collaborator. I also forked the repo to contribute to it.
I cloned my forked to local, But I can't checkout other's pr to `facebook/react-native` (the upstream) in `Github Desktop`.

**Comment by gengjiawen** [comment]
In other words, I want here show `facebook/react-native` prs too.
![image](https://user-images.githubusercontent.com/3759816/52572042-ddcdee00-2e51-11e9-9b7e-51e7ec49420d.png)

**Comment by outofambit** [comment]
Thanks for the extra information @gengjiawen! That makes sense. I think this would fall under the discussion over at #6383. I'm going to close this issue and add some of our discussion to that issue. Feel free to comment there more. Thank you!

**Comment by gengjiawen** [comment]
Thanks you too.
