### ISSUE TITLE
Co-authors missing from Windows

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6828]
The co-author section is missing from Windows which could be related to recent changes to the area via PR: https://github.com/desktop/desktop/pull/6764 

![image](https://user-images.githubusercontent.com/14828183/52605904-bdcc0980-2e14-11e9-8a65-5d5e54d6bed2.png)

tested in 1.6.2-beta2, windows 10

**Comment by shiftkey** [comment]
@tierninho what was the context behind closing this out?

**Comment by tierninho** [comment]
Repo wasn't published 🤦‍♂️
