### ISSUE TITLE
Publish repository modal showing up when repo is already published

### ISSUE THREAD

**Issue by sungdzda** [desktop/desktop#6829]
Hello,

This is a known issue and I have it in the latest version 1.6.1. Monitor icon appears on the top left corner.
If I had to guess, the bug may be related to client's internet quality. My workaround was to relocate local files and clone the remote.

I am opening this issue because I thought you'd like to know. Unfortunately I cannot provide any additional info at this point.

Please refer to #5719 #5936

**Comment by outofambit** [comment]
Hi @sungdzda! Thanks for letting us know! We'll keep an eye out for this.

There's not much else we can do at the moment without more information, so I'm going to close this issue. If at some point you can provide more information, I'd be curious to know if this is a GitHub repo? and what the remote URL is for the `origin` remote. Please reopen this issue and comment if/when you can.

Thank you!

**Comment by sungdzda** [comment]
Hello outo,

If it helps, yes it was a Github repo and I believe the URL was rather simple (all alpha and no space, etc.) I found the problematic behaviour to be exactly the same as those of the issues I referenced.

**Comment by outofambit** [comment]
@desktop/quality-assurance would you mind taking a look at this to see if you can reproduce?

**Comment by tierninho** [comment]
@outofambit Tried repoing this but no luck. We may not be accounting for an edge case when checking to see if a remote is null https://github.com/desktop/desktop/pull/5948/files#diff-d6b76b602a5c48740d6d10deda6f71ebR2378

That PR address some of the underlying behavior but the exact issue was never pinpointed.

**Comment by vertesy** [comment]
I have the same issue on OS X 10.14.6 (Mojave) using Github desktop Version 2.2.3 (this issue has been raised many times: #5936, #3723, #5719)

After sometimes, when clicking on the top bar, I got 
<img width="590" alt="Newer commits on remote" src="https://user-images.githubusercontent.com/5101911/68839070-39b6f300-06c0-11ea-9c12-9535325ae173.png">

Fetch did not do anything until trying 5 times, finally it worked, but every step required trying / restarting many times.

**Comment by steveward** [comment]
Closing this as stale.
