### ISSUE TITLE
Private repository creation is not possible 

### ISSUE THREAD

**Issue by maifeeulasad** [desktop/desktop#6833]
GitHub has introduced private repositories for all users , but GitHub Desktop has **no option for private repository creation .**

![screenshot 283](https://user-images.githubusercontent.com/29339330/52661660-b4ce5b80-2f2c-11e9-8247-c4f45a92d1d4.png)

**Comment by tierninho** [comment]
@maifeeulasad After you fill out that form, and then click the `Publish` button, you will see an option for private repos like so:

<img width="482" alt="screen shot 2019-02-12 at 9 18 36 am" src="https://user-images.githubusercontent.com/14828183/52661961-4d21fd00-2ea7-11e9-9c95-951e36799263.png">

Hope this helps! 😄

**Comment by maifeeulasad** [comment]
Thanks .
