### ISSUE TITLE
no scrolling or page up/down on file list

### ISSUE THREAD

**Issue by guitar-freq** [desktop/desktop#6841]
## Description

C'mon guys ... great product but no scroll bar when I have 7000 files and trying to find 3 boxes that are unchecked is well an oversight. To boot, when I select a file - thinking I'll just use page up & page keys - page up/down only works once. Not nice ;)

## Version

* GitHub Desktop:

* Operating system:

**Comment by outofambit** [comment]
Hi @guitar-freq, thanks for the issue. Would you mind filling out the template and responding when you do? Without that additional information, it's really hard for us to diagnose what might be going on.

Are you able to scroll with a scroll wheel or some other mouse gesture?
