### ISSUE TITLE
Desktop on Mojave (Electron 3) should not advertise itself as having a tab bar

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#6842]
<img width="303"  src="https://user-images.githubusercontent.com/359239/52735364-dc114100-2f9d-11e9-8b1c-a3ec02304faf.png">

This doesn't make sense for two reasons:

 - Desktop doesn't support a tabbed interface, so this is probably always disabled for us
  - as this is rendered before the menu items in `build-default-menu.ts` I suspect these are some new defaults added in Mojave

The relevant area for our Desktop settings is here:

https://github.com/desktop/desktop/blob/37b420abfd08f82bf419dcbc1a5b6434a8f61a11/app/src/main-process/menu/build-default-menu.ts#L145-L153

Opening this up for someone who knows more about macOS to dive into what the app should do and what Electron apps should do to advertise they don't support a tabbed interface.

**Comment by agisilaos** [comment]
@shiftkey I'm running the latest macOS Mojave & latest Github Desktop Beta and I don't have these 2 options in my menu. 
![screenshot 2019-02-13 21 03 30](https://user-images.githubusercontent.com/10944108/52736610-e994ee00-2fd2-11e9-833f-2c8d66e65cb8.png)

**Comment by shiftkey** [comment]
@agisilaos I believe you'll need to run #6713 (which contains the upgrade) to see this change yourself. It hasn't made it to beta yet.

**Comment by SensehacK** [comment]
@shiftkey I tried switching to #6713 PR branch & ran yarn commands to run the app. Yet I couldn't find "Show Tab Bar" option in the menu item.

Also, I'm new to Electron + Typescript, So maybe I'm missing something.

**Comment by shiftkey** [comment]
@SensehacK that's strange. We're planning to publish a beta with Electron 3 support real soon - I'll update this issue then to see if I can get additional testers to reproduce this behaviour rather than run things from source.

If it's something specific to my setup that others can't see then it's a low-priority task and could potentially be closed.

**Comment by SensehacK** [comment]
@shiftkey Sure thing.
My current setup would be 
MBP Early '15 8GB RAM
Mac OS 10.14 Mojave
13'' inch Display.

Aside from this, I haven't set up any graphical behavior overrides via any tools.

**Comment by shiftkey** [comment]
I've just released `1.6.3-beta1` on the [beta channel](https://github.com/desktop/desktop#beta-channel) on macOS `10.14.3` and after installing that build locally I don't see the problem 🤦‍♂️:

<img width="853" alt="screen shot 2019-02-15 at 12 58 39 pm" src="https://user-images.githubusercontent.com/359239/52871878-71890e00-3121-11e9-96e9-bc75d32aa9e9.png">

Closing this out as unable to reproduce, but if anyone else is able to spot this please comment here and we can try and dig into it further.
