### ISSUE TITLE
"Sign in using your browser" does not work with Firefox on Windows

### ISSUE THREAD

**Issue by ANogin** [desktop/desktop#6843]
When choosing to "Sign in using your browser" in GitHub Desktop 1.6.2 on Windows 7 Pro where the default browser is Firefox 64.0.2 (64-bit), I get to a `https://github.com/login/oauth/authorize?client_id=...` URL and get a "Launch Application" popup that asks me to select an application for `x-github-client` links. Selecting `GitHubDesktop.exe` does not work. Pasting the same `https://github.com/login/oauth/authorize?client_id=...` URL into Chrome does work correctly. When logging into Github Enterprise, it's the same issue.

**Comment by outofambit** [comment]
Hi @ANogin, thank you for filing this issue! I'm sorry you're running into this. Could you share a screenshot of the "Launch Application" popup? I'm curious what the other options available are. I'm guessing that you're already logged into github on firefox, so it's trying to redirect you back to GitHub Desktop (and that's the part that's failing).

As an additional diagnostic, if you click on the "Open in Desktop" link in a repo on GitHub.com from firefox, does that also trigger the "Launch Application" popup?

<img width="558" alt="screen shot 2019-02-13 at 4 40 56 pm" src="https://user-images.githubusercontent.com/964912/52754140-52b63a80-2fae-11e9-9d3f-23db68c97fd1.png">

**Comment by ANogin** [comment]
Yes, "Open in Desktop" results in an identical popup.
![popup](https://user-images.githubusercontent.com/1147370/52754438-601ff480-2faf-11e9-84d6-c7d3738916ce.png)

**Comment by ANogin** [comment]
P.S. However, using Chrome on the same machine, "Open in Desktop" works correctly.

**Comment by outofambit** [comment]
Thank you for this extra information @ANogin! This is really helpful. It sounds like the protocol handler for GitHub Desktop is not working for Firefox (on Windows). I'm going see if I can reproduce on my machine and do some more diagnosing.

**Comment by shiftkey** [comment]
For reference, we had an earlier discussion about this behaviour with Firefox in #5792 and this comment pointed out some known Firefox bugs that might be involved: https://github.com/desktop/desktop/issues/5792#issuecomment-427744894

It was suggested that a reinstall of Desktop might address the issue, but I'm not sure if that worked for the initial reporter.

**Comment by outofambit** [comment]
@ANogin I wasn't able to reproduce this on my windows machine. I would try reinstalling github desktop as a next step, as @shiftkey. If that doesn't work, let us know and we'll see if @desktop/support can help us! Thanks!

**Comment by sin2akshay** [comment]
Have the same issue. Just installed Github Desktop and tried logging in to my Enterprise.

**Comment by JannaLorette** [comment]
Thank you for your response

**Comment by shiftkey** [comment]
@sin2akshay please read the related issue which links to some known Firefox issues https://github.com/desktop/desktop/issues/5792#issuecomment-427744894. If you believe your issue is different to ours, please open a [new bug report](https://github.com/desktop/desktop/issues/new?template=bug_report.md) and fill out the template so we can investigate.

**Comment by JannaLorette** [comment]
Chrysalis abut to open knit seems like got Psy key valid dictorian. Omni
translucien

**Comment by sin2akshay** [comment]
@shiftkey It is the same. Sorry to bother but is there no workaround for now? It suggested re-install GH but I just installed a fresh copy of Github Desktop before trying this.

**Comment by shiftkey** [comment]
@sin2akshay I'm not aware of any other tricks currently to get Firefox to correctly detect the Desktop install

**Comment by steveward** [comment]
@sin2akshay are you able to temporarily change the default browser on your Windows 7 machine to a different browser other than Firefox? If you change to something like a recent version of Internet Explorer then you should be able to at least authenticate to your GitHub Enterprise instance. You can then switch back to using Firefox. This has worked for some other users who have encountered the same issue -- let me know if that helps.

**Comment by tierninho** [comment]
Successfully logged in with Desktop 1.7.0beta6 and Firefox 66.0.4 o Windows 10. Going to close this issue for now. Please add details if the issue persists after upgrading.

**Comment by valentinoPereira** [comment]
It may be your browser issue.. I had chrome selected and it wouldn't open. I went and changed my default browser to edge, then it worked
