### ISSUE TITLE
Support for multiple remotes

### ISSUE THREAD

**Issue by sorencoder** [desktop/desktop#6844]
Currently github desktop only works with one remote (origin) and there's no way to push to secondary remote. I'd be awesome if you add support for that. 

Thanks.

**Comment by steveward** [comment]
Thanks for opening this @sorencoder. This feature is being tracked in https://github.com/desktop/desktop/issues/1442, so in the interest of keeping our issue list maintainable I am going to close this issue out. Please follow along in #1442 for updates.

**Comment by billygriffin** [comment]
@sorencoder Additionally, if you wouldn't mind responding in #1442 about what other remotes you'd like to use, and what your workflow looks like, that would be really helpful for us as we consider whether or not to support that going forward. Thanks!

**Comment by ReessKennedy** [comment]
+1 ... we just started a workflow with two remotes because we write our knowledge to markdown that then lives in different places depending on the team and we use two remotes to achieve this.
