### ISSUE TITLE
[Suggestion] Repository Alias feature like SourceTree

### ISSUE THREAD

**Issue by benjamin-prnd** [desktop/desktop#6847]
# Feature
- Repository Alias feature(no Rename)

# UseCase
- if used same Repository in Submodule project, It is the same remote repository, but is managed differently locally.

# Problem
- In this usecase , Github Desktop is showing same name at Repository list. it can be confuse.

I hope that this feature will be reflected. 

Thanks.

**Comment by billygriffin** [comment]
Hi @benjamin-prnd, thanks for the issue! We're looking at this in #6460, so I'm going to close this but if your experience isn't sufficiently captured there, please feel free to weigh in on that issue. Thanks!
