### ISSUE TITLE
Unable to clone on GitHub Desktop

### ISSUE THREAD

**Issue by ihebboubakri** [desktop/desktop#6850]
Cloning into 'C:\Users\iheb\Documents\GitHub\PI-Dev'... fatal: unable to access 'https://github.com/chaymaBN/PI-Dev.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - La fonction de révocation n'a pas pu vérifier la révocation car le serveur de révocation était déconnecté.

**Comment by shiftkey** [comment]
@ihebboubakri thanks for the report!

This feels like #3326:

> GitHub Desktop by default uses the Windows Secure Channel (SChannel) APIs to validate the certificate received from a server. Some networks will block the attempts by Windows to check the revocation status of a certificate, which then causes the whole operation to error.

We have some [guidance](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#certificate-revocation-check-fails---3326) to workaround:

> To use the classic OpenSSL behavior in Git, you'll need a PEM file containing certificates that are considered trusted. The [public list](https://curl.haxx.se/docs/caextract.html) provided by the curl project can be used if you are not connecting to a GitHub Enterprise instance which has it's own distinct certificates.
>
>Once you've downloaded that PEM file somewhere, open a shell with Git and run these commands:
>
>```shellsession
> $ git config --global http.sslBackend "openssl"
> $ git config --global http.sslCAInfo "C:/path with spaces/to/directory/cacert.pem"
> ```
>
> Ensure you use forward slashes for the path when setting the `sslCAInfo` value.

**Comment by billygriffin** [comment]
Since this is similar to what we've seen previously, I'm going to close this issue for now, but we're happy to reopen it @ihebboubakri if the guidance @shiftkey linked above doesn't resolve your issue. Thanks!

**Comment by P3012852** [comment]
@billygriffin  I have followed the same steps as you mentioned above but unfortunately i'm still getting the below error. Please help me with the same.
![image](https://user-images.githubusercontent.com/19977087/55171254-e9f6dc00-516f-11e9-8dd6-22023519f453.png)

**Comment by shiftkey** [comment]
@P3012852 we have some more up-to-date advice for this `InitializeSecurityContext` error. Please try out this workaround here and see if it addresses the issue for you: https://github.com/desktop/desktop/blob/development/docs/known-issues.md#certificate-revocation-check-fails---3326

**Comment by P3012852** [comment]
@shiftkey Thanks for the quick turn around. It is working now. thanks for your help.
