### ISSUE TITLE
Repository branch (unknown) and all file changes uncommited

### ISSUE THREAD

**Issue by SpyceTewan** [desktop/desktop#6856]
## Description

I started GitHub desktop. Everything worked fine a couple of hours ago, now, suddenly my repository seems it couldn't be properly loaded. My branches are still there, but I can't switch to them and the last commit date on the branches is wrong. 

## Version

* GitHub Desktop: 1.6.2

* Operating system: Microsoft Windows [Version 10.0.17134.590]

## Steps to Reproduce

I don't know how to reproduct this because I didn't change anything. After I commited my changes and closed my laptop, after reopening, this issue happened

### Expected Behavior

My branches should work normally

### Actual Behavior

Branches seem to not get loaded properly

### Logs

[2019-02-14.desktop.production.log](https://github.com/desktop/desktop/files/2866982/2019-02-14.desktop.production.log)

**Comment by tierninho** [comment]
@SpyceTewan Thanks for filing. Every time you attempt to switch branches you see something like so?

<img width="558" alt="screen shot 2019-02-14 at 1 47 33 pm" src="https://user-images.githubusercontent.com/14828183/52824991-227aa480-305f-11e9-86e9-d28f88064dd0.png">

If yes, you have to resolve the current changes by stashing them or committing before you are able to switch branches. 

- To commit, just check the boxes, enter a summary, and click the `commit` button. 
- To stash (save for later), go to Repository menu > Open in Command Prompt > type `git stash`

The remainder of the files, if any, need to be moved or removed but based on your logs the above two options are sufficient.

**Comment by SpyceTewan** [comment]
Thanks for the explaination. What I'm concerned of, is that when I stash or commit my changes, do the other branches remain untouched? I don't want to risk losing progress.

**Comment by steveward** [comment]
@SpyceTewan committing those changes will only commit them to your current branch. Stashing the changes will store them in the stash list and not affect any other branches. You can run the `git stash` command that @tierninho mentioned, and then switch branches to work on a different branch. When you are ready to restore your stashed changes you can use the `git stash pop` command -- this will restore the most recent set of stashed changes to your current branch. 

You can read more about stashing in this [section from the Pro Git book](https://git-scm.com/book/en/v1/Git-Tools-Stashing). We're discussing implementing stashing in #6107 if you are interested in following along there.

If you run into any issues getting your repository back into its correct state, please let me know.
