### ISSUE TITLE
Default branch to is always set to "master"

### ISSUE THREAD

**Issue by Eyesonly88** [desktop/desktop#6857]
## Description

When making a new branch, the default selected branch is always `master` even if the default branch is set to `develop` or `feature` on Github.

## Version

* GitHub Desktop:

1.6.2

* Operating system:

Mac OS 10.14.2

## Steps to Reproduce

1. create a new branch from github desktop
2. the default selected branch is always master

### Expected Behavior

Uses the default branch setting from the Github settings for the repo.

### Actual Behavior

It's always using `master` as the default branch to create branches off instead of the actual default branch setting from Github.

**Comment by steveward** [comment]
Thanks for contributing @Eyesonly88! This bug was previously reported in https://github.com/desktop/desktop/issues/5709. I'm going to close this issue out as a duplicate, but please follow along in #5709 for updates about this.

**Comment by steveward** [comment]
@Eyesonly88 as a workaround you can clone a fresh copy of the repository, which should cause the correct default branch to be recognized (I just tested this behavior). Let me know if that doesn't work for you.

**Comment by Eyesonly88** [comment]
@stevecat Oh I didn't know that, ok I'll try it, thanks 👍

**Comment by gojanpaolo** [comment]
cloning a fresh copy of the repo did the trick for TFS 2015 :)

**Comment by francoios** [comment]
Hello guys, it seems for me that the solutions above are not working the only solution i found to corect it was to re-clone the repo. so the issue remain Open

and yes i tried all the mentionned solution even reloading the repo
