### ISSUE TITLE
github desktop authentication failed

### ISSUE THREAD

**Issue by Pixellore** [desktop/desktop#6859]
## Description

github desktop fails to clone a private repository giving authentication failed error. Authentication information is correct but it keeps failing. Tried to clear the credential information from windows control panel. When I start github desktop app, it already logs into my account but it finds no repositories. Can't log out from my account in the desktop app because there is no File menu or any other menu appearing in the app. Just option to add repository or refresh list.

## Version

I have installed the latest one from the web, but I can't check the version number because there is not a single menu item I can click. There is no About Github Desktop menu item. There is no File menu, nothing.

* GitHub Desktop:

* Operating system:
Windows 10

## Steps to Reproduce

1. Fork the project to clone.
2. Clone using desktop app, (https, but ssh also not working)
3. desktop app installs, and attempts to clone, but fails. At the point, I am already automatically logged into my account inside desktop app.

### Expected Behavior

Expect to be able to clone using my credential.

### Actual Behavior

Fails with authentication error.

## Additional Information

I may have used github long time ago in the same pc with some other credentials (password may have been changed?) but not 100% sure.
[2019-02-15.desktop.production.log](https://github.com/desktop/desktop/files/2868589/2019-02-15.desktop.production.log)

**Comment by Pixellore** [comment]
I am going to try on the different PC to see if this only happens for the specific PC

**Comment by Pixellore** [comment]
Tried on a different PC and everything works perfectly.. so it's the other pc's problem somehow... some thing must have been left over from last usage of git on that pc that screws up on it.

**Comment by steveward** [comment]
Thanks for the report @Pixellore. It does look like there is an issue with the token that GitHub Desktop stores:

```
Error: Cannot update an account which doesn't have a token: Pixellore
```

Can you try logging out and then logging back in to see if that gets things working for you? You can do this by going to `File` > `Options` > `Accounts`. 

Let me know if that does not get things working for you!

**Comment by Pixellore** [comment]
I dont think you have read my description carefully.. i have already stated many times that i can not log out and log back in from desktop app. because i cant access the menues! i know what menu you are talking about because i can see them in the other computer. but for some reason there are no menues at all in the problomatic pc. the app fails to display the menues to start with !

**Comment by Pixellore** [comment]
![image](https://user-images.githubusercontent.com/10590995/52925635-937ace80-3375-11e9-8ab7-39b3fb003f27.png)

This is all I get from desktop app. As you can see there are no menus..

Refresh the list button does nothing. I can't clone any repository using my credential on this PC. The exact same credential works on other PC

**Comment by shiftkey** [comment]
@Pixellore the view you are currently seeing is intended to help onboard new users rather than leaving them with an empty view. Are you able to create a blank repository locally so that you'll proceed from that view into the main app? That will let you access the Preferences view and sign into your account again.

**Comment by Pixellore** [comment]
Great. I was able to do just that! Not sure why I have never thought of doing it. Thanks for the help. Still not sure what the exact problem was, but if it is fixed, I am happy.

**Comment by megaromb** [comment]
@steveward thanks, your advice (sign out / sign in) helped me fixed the same issue.

**Comment by orionismud** [comment]
I was having the same issue, and this fixed it for me as well!

**Comment by dastrix80** [comment]
same issue, signing out/in doesnt fix the issue.

**Comment by tierninho** [comment]
@dastrix80 Please create a new issue if you'd like us to help out. Thanks!

**Comment by zgw930112** [comment]
![1](https://user-images.githubusercontent.com/10862824/61602569-b84cd800-ac6c-11e9-92ce-5e7c0e71460d.png)
I am experiencing the same problem!

**Comment by tierninho** [comment]
For anyone experiencing the same issue, please file a new issue. Thanks!
