### ISSUE TITLE
I can no longer push my latest commit after the February 13, 2019 update.

### ISSUE THREAD

**Issue by rajzerm** [desktop/desktop#6861]
## Description
 When I click the button to push origin, I get a fatal error that says "fault: unable to access 'repo name': schannel" next InitializeSecurityContext failed: Uknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.". I do not have any corporate proxy settings enabled and disabling my firewall and other antivirus protections didn't solve this issue, which is what others with this issue suggested.

## Version

* GitHub Desktop: 1.6.2

* Operating system: Windows 8.1 Pro

## Steps to Reproduce
 Step 1: Click "push origin".

### Expected Behavior
 I expected the push to work successfully.

### Actual Behavior
 Can't push changes.

### Logs
2019-02-15T16:20:49.516Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
fatal: unable to access 'Repo name': schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.

**Comment by shiftkey** [comment]
@rajzerm thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by rajzerm** [comment]
I updated the template. Is there any more information I still need to provide?

**Comment by shiftkey** [comment]
@rajzerm thanks for filling that out - I can understand more about what's happening.

This feels like #3326:

> GitHub Desktop by default uses the Windows Secure Channel (SChannel) APIs to validate the certificate received from a server. Some networks will block the attempts by Windows to check the revocation status of a certificate, which then causes the whole operation to error.

We have some [guidance](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#certificate-revocation-check-fails---3326) to workaround the problem:

> To use the classic OpenSSL behavior in Git, you'll need a PEM file containing certificates that are considered trusted. The [public list](https://curl.haxx.se/docs/caextract.html) provided by the curl project can be used if you are not connecting to a GitHub Enterprise instance which has it's own distinct certificates.
>
>Once you've downloaded that PEM file somewhere, open a shell with Git and run these commands:
>
>```shellsession
> $ git config --global http.sslBackend "openssl"
> $ git config --global http.sslCAInfo "C:/path with spaces/to/directory/cacert.pem"
> ```
>
> Ensure you use forward slashes for the path when setting the `sslCAInfo` value.

**Comment by shiftkey** [comment]
@desktop/support if the new workaround I've suggested works, we should update the [known issues](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#certificate-revocation-check-fails---3326) entry to propose this.

**Comment by rajzerm** [comment]
@shiftkey Where do I enter the global config value?

**Comment by steveward** [comment]
@rajzerm you can run the command @shiftkey provided from the command line, which you can launch by going to the menu and selecting `Repository` > `Open in <your_default_command_line_application>`. If you do not currently have Git for Windows installed you will need to grab it [here](https://git-scm.com/download/win) and run through the install process.

**Comment by rajzerm** [comment]
@steveward OK thanks for clarifying. I tried running the command that @shiftkey provided in the command line but it didn't resolve my issue. What should I try next?

**Comment by steveward** [comment]
@rajzerm can you confirm that you are still seeing the same error you were previously seeing? Can you also share the output of this command from the command line?

`git config --list --show-origin`

I'd like to verify everything is configured correctly to ensure we aren't missing anything.

**Comment by rajzerm** [comment]
@steveward Yes, I am still receiving the same error message as before. 

C:\Users\hf5516\Documents\Software\xxxx>git config --list --show-origin
file:"C:\\ProgramData/Git/config"       core.symlinks=false
file:"C:\\ProgramData/Git/config"       core.autocrlf=input
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       diff.astextplain.textconv=astextplain
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    http.sslcainfo=C:/Progra
m Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    http.sslbackend=openssl
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    diff.astextplain.textcon
v=astextplain
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.clean=git-lfs
 clean -- %f
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.smudge=git-lf
s smudge -- %f
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.process=git-l
fs filter-process
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.required=true

file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    credential.helper=manage
r
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    core.editor='C:\Program
Files (x86)\Notepad++\notepad++.exe' -multiInst -notabbar -nosession -noPlugin
file:C:/Users/hf5516/.gitconfig user.name=xxxx
file:C:/Users/hf5516/.gitconfig user.email=xxxx
file:C:/Users/hf5516/.gitconfig filter.lfs.process=git-lfs filter-process
file:C:/Users/hf5516/.gitconfig filter.lfs.required=true
file:C:/Users/hf5516/.gitconfig filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/hf5516/.gitconfig filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/hf5516/.gitconfig http.schannelcheckrevote=false
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.symlinks=false
file:.git/config        core.ignorecase=true
file:.git/config        remote.origin.url=https://github.com/xxxx/xxxx.git

file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.master.remote=origin
file:.git/config        branch.master.merge=refs/heads/master

C:\Users\hf5516\Documents\Software\xxxx>

**Comment by shiftkey** [comment]
@rajzerm there's a typo - it should be `http.schannelcheckrevoke` (with a `k`) and not  `http.schannelcheckrevote` (with a `t`).

**Comment by rajzerm** [comment]
@shiftkey I modified my .gitconfig file by changing http.schannelcheckrevote to http.schannelcheckrevoke and now my problem has been resolved. I'm not sure how this typo was made since I've never opened that file before. Thank you @shiftkey and @steveward for your help with resolving this!

**Comment by shiftkey** [comment]
@rajzerm I'm glad you were able to resolve this, and thanks for confirming the new workaround works for you.

I'm going to leave this open and update our known issues doc to explain this new flag and recommend this workaround.
