### ISSUE TITLE
Prevent multiple opens of editor via onboarding page

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6864]
The `Open in Editor` button can be clicked multiple times in a row causing the editor application to open multiple instances in a row, which can result in the crashing of the editor.

We should disable the action until something is done (process closes signaling it's completed launching atom).

When we're launching Atom we're passing it a specific path to open, and it should be using the same session for subsequent launches of the same path (essentially refocusing the window). 

![image](https://user-images.githubusercontent.com/14828183/52880131-35e04b00-3105-11e9-8b0d-b8c24a596409.png)

1.6.3-beta1, mac

**Comment by tierninho** [comment]
Closing this as it has not come up enough times to be validated as a real problem.

**Comment by steveward** [comment]
Received a report of this via Zendesk.

**Comment by tierninho** [comment]
@steveward Any errors associated with the report? Or was the user just pointing it out?

I coincidentally was testing this a few days ago. I opened like 30 windows with Atom, and  they slowly closed one-by-one until only a single instance was left. Can't speak for other editors.

Not sure if we will fix it any time soon. 🤷‍♂

**Comment by lucastonelli** [comment]
Hey, I just solved the problem for you I think. Just remember to give me credit for it hahaha

Open Sublime Text Preferences, go to Settings, write: 

`"hot_exit": false,`
`"remember_open_files": false,`

![Print](https://user-images.githubusercontent.com/52139329/61756210-589c1d00-ad91-11e9-98d1-08ae007df199.png)


Then solved!

Best regards.

**Comment by tierninho** [comment]
@lucastonelli Thanks for the tip! Now we need to solve for the other editors 🏎

**Comment by lucastonelli** [comment]
@tierninho One at a time :laughing:

**Comment by Eugene8571** [comment]
with 'hot_exit": false, and "remember_open_files": false, it no more double window and no previous file, if i run Sublime separately.
i get 1 window from git and prev file if run Sublime with  "remember_open_files": false. which is strange.

**Comment by iLPdev** [comment]
> with 'hot_exit": false, and "remember_open_files": false, it no more double window and no previous file, if i run Sublime separately.
> i get 1 window from git and prev file if run Sublime with "remember_open_files": false. which is strange.

Confirmed #8584 with clean installs. Also reproduced above by @Eugene8571
