### ISSUE TITLE
Lock file already exists and no index.lock file exists

### ISSUE THREAD

**Issue by talithachin** [desktop/desktop#6871]
I'm able to get the changes made in the pull request on github desktop. 
However, I am unable to. Instead, I get this error" A lock file already exists in the repository, which blocks this operation from completing.". I've tried deleting the index.lock file as recommended in many forums, e.g. https://github.com/desktop/desktop/issues/5475 . But when i look into the folder of the repo, the index.lock file does not exist. 

<img width="1311" alt="screenshot 2019-02-19 at 5 36 44 pm" src="https://user-images.githubusercontent.com/42484009/53004973-34988080-346d-11e9-9497-33021f56cff1.png">

**Comment by niik** [comment]
Hi @talithachin. The `index.lock` file is located in the `.git` folder inside of your repository. It's possible that this folder his hidden from view in Explorer in which case you might need to turn on [Show hidden files](https://support.microsoft.com/en-us/help/14201/windows-show-hidden-files).

Once you locate the `.git` folder you should see the `index.lock` file and be able to delete it.

Hope that helps, I'm going to close this issue out but feel free to reply if that doesn't work and we'll reopen.

**Comment by yuraporitskii** [comment]
talithachin how did you solve that , i have same problem , it just doesnt exist
