### ISSUE TITLE
[Feature Request] Vue, Edit and Comment on Issues and PRs

### ISSUE THREAD

**Issue by zero77** [desktop/desktop#6876]
Can you please add support to vue, edit and comment on Issues and PRs, like you can in the web browser.
Thanks

**Comment by billygriffin** [comment]
Hi @zero77, thanks for the suggestion - we have individual issues we're evaluating with respect to issue and PR creation (example: https://github.com/desktop/desktop/issues/295). Up to now, we've decided not to incorporate PRs and issues directly into Desktop, but we're continuously evaluating whether that makes sense compared to our other priorities. Notably, our goal is not to just match the functionality of GitHub.com, but rather to complement it and give people the tools to get their work done locally as easily as possible. Thanks for the suggestion - I'm going to close this issue for now to indicate that we don't intend to support it in the near term.
