### ISSUE TITLE
Cannot do anything that regards GH desktop connecting to GH.com

### ISSUE THREAD

**Issue by Fedefreez** [desktop/desktop#6879]
Hi everyone.

### Description
I literally can't do anything related to online repos.
When I originally installed GitHub desktop I wasn't able to clone a repo so I skipped the step.
Now I'm only able to commit and create local repos. None of these operations work:
-Fetch
-Push
-Pull
-Merge (pretty almost everything that regards changes on my online repo)

### Version
1.6.2

### Operating system:
Windows 10 pro

### Steps to Reproduce
Create local repo since I can't clone a new one,
Fetch/push/pull/merge anything.

### Expected Behavior
changes in online repo happen/ repo is cloned/ repo is created/ merge request is accepted/GH fetches updates.

### Actual Behavior
error: unable to read askpass response from 'C:\Users\fedeb\AppData\Local\GitHubDesktop\app-1.6.2\resources\app\static\ask-pass-trampoline.bat'
fatal: could not read Username for 'https://github.com': terminal prompts disabled

### Additional Information
- I know it's really really similar to other open issues, but it's slightly different the response given by the task pass trampoline operation.
- I have 2 disks on my pc, I have also 2 other pc with only  1 disk, win 10 pro and there GH desktop works!
- I don't have 2-factor auth enabled.
- This happens with every repo I try: collab ones, the one I own, the ones I previously created online etc...

I already tried:
- Uninstall GH desktop (also from Roaming, localappdata and prefetch).
- Sign out and in.
- Execute the commands GH desktop executes in the log manually (Git bash) and I get different errors (listed in the 2nd log)
- I only use windows defender and firewall, no extra security software:
- I also tried disabling them, no solution.
- My NAT type is 2
- Getting another pc, connecting it to the eth cable this pc uses and use GH desktop: it works.

### Logs
-----------------1st log-------------
```
2019-02-19T17:48:28.757Z - info: [ui] [AppStore] loading 1 repositories from store
2019-02-19T17:48:28.758Z - info: [ui] [AppStore] found account: Fedefreez (Fede)
2019-02-19T17:48:29.267Z - info: [ui] launching: 1.6.2 (Windows 10.0.17763)
2019-02-19T17:48:29.267Z - info: [ui] execPath: 'C:\Users\fedeb\AppData\Local\GitHubDesktop\app-1.6.2\GitHubDesktop.exe'
2019-02-19T17:48:30.207Z - info: [ui] Stats reported.
2019-02-19T17:48:54.638Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.085s)
2019-02-19T17:48:54.639Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
error: unable to read askpass response from 'C:\Users\fedeb\AppData\Local\GitHubDesktop\app-1.6.2\resources\app\static\ask-pass-trampoline.bat'
fatal: could not read Username for 'https://github.com': terminal prompts disabled
2019-02-19T17:50:30.931Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Lezioni - Fedefreez (has token)
2019-02-19T17:50:31.839Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
error: unable to read askpass response from 'C:\Users\fedeb\AppData\Local\GitHubDesktop\app-1.6.2\resources\app\static\ask-pass-trampoline.bat'
fatal: could not read Username for 'https://github.com': terminal prompts disabled
2019-02-19T17:50:34.793Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Lezioni - Fedefreez (has token)
2019-02-19T17:50:35.768Z - error: [ui] `git -c credential.helper= push origin master --set-upstream --progress` exited with an unexpected code: 128.
error: unable to read askpass response from 'C:\Users\fedeb\AppData\Local\GitHubDesktop\app-1.6.2\resources\app\static\ask-pass-trampoline.bat'
fatal: could not read Username for 'https://github.com': terminal prompts disabled
2019-02-19T17:54:20.948Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
error: unable to read askpass response from 'C:\Users\fedeb\AppData\Local\GitHubDesktop\app-1.6.2\resources\app\static\ask-pass-trampoline.bat'
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

### 2nd log:
I'm not familiar with git bash so I might have committed some mistakes.
[git bash.txt](https://github.com/desktop/desktop/files/2881394/git.bash.txt)

**Comment by billygriffin** [comment]
Hi @Fedefreez, sorry for missing this. Are you still experiencing this issue?

**Comment by Fedefreez** [comment]
Unfortunately yes.

**Comment by aronquiray** [comment]
same here. can't fetch/pull/push

**Comment by Fedefreez** [comment]
@aronquiray do you get the same error as me?

**Comment by aronquiray** [comment]
yep. ask-pass-trampoline.bat error. 

signout + uninstall + deleted residue files + redownload + patched (1.6.3). still gettings same error.. 
![screenshot_999](https://user-images.githubusercontent.com/13714092/53913093-76dcd700-4095-11e9-9b8d-cca672d3265b.png)

**Comment by Fedefreez** [comment]
Try to copy the path of the ask pass trampoline and use it on explorer. Tell me if you can see the file in there.

**Comment by billygriffin** [comment]
@desktop/support Do you mind taking a look at this? Feels like we've seen this "ask-pass-trampoline" issue pop up before, but I'm not sure why it's happening.

**Comment by aronquiray** [comment]
hey! @Fedefreez  sorry just replied (was sleeping)
here are the contents of it.
![screenshot_1000](https://user-images.githubusercontent.com/13714092/53929794-d9e86100-40c9-11e9-8853-0296ac42b946.png)

**Comment by Fedefreez** [comment]
Click on ask-pass-trampoline.bat , go on the explorer menu and select copy path. Paste its path here.

**Comment by aronquiray** [comment]
"C:\Users\MyUser\AppData\Local\GitHubDesktop\app-1.6.3\resources\app\static\ask-pass-trampoline.bat"

**Comment by Fedefreez** [comment]
Hey that's why it happens for you

**Comment by Fedefreez** [comment]
gh desktop path is 1.6.2 but the real is 1.6.3

**Comment by aronquiray** [comment]
@Fedefreez nope, they're not. when GH is updated. I think it also reproduces a copy of the ask-pass-trampoline.bat 
and still, same error occurred. 
![screenshot_1011](https://user-images.githubusercontent.com/13714092/54029409-3f7c4080-41e3-11e9-91d6-033fc4770083.png)

**Comment by Fedefreez** [comment]
@aronquiray check the error that gh gives where the path is /app-1.6.2/ and the one that contains the ask pass trampoline /app-1.6.3/ it's obvious that if gh tries to go in the 1.6.2 folder the error pops out.

**Comment by aronquiray** [comment]
@Fedefreez still nope. I found my answer. 
I've recently updated this (and I was doing it wrong) 
so, I've corrected it to this and now my GH works again :D
I think it was the wrong start of command prompt that's why.
![screenshot_1013](https://user-images.githubusercontent.com/13714092/54050099-50e03f80-4219-11e9-8df0-4e4a7e407caa.png)

**Comment by Fedefreez** [comment]
Nice, I have my cmd start modified too. Let's see.

**Comment by Fedefreez** [comment]
Yesss thank you so much @aronquiray I didn't think about that!!
I can finally use GitHub desktop on my pc.

**Comment by steveward** [comment]
@Fedefreez and @aronquiray thanks for sharing those details about how modifying the AutoRun setting can cause this error. It was very helpful! I'm going to make a note of this in our [known issues](https://github.com/desktop/desktop/blob/development/docs/known-issues.md) document for other users to reference.

**Comment by aronquiray** [comment]
sure @steveward , what I did was an unintentional magic fix LOL!

**Comment by Fedefreez** [comment]
No problem @steveward and thanks again @aronquiray

**Comment by KevinLHansen** [comment]
Hello

I have this exact issue. When I go examine my registry, there is no AutoRun entry - could this cause the issue? I've created an AutoRun entry of the same type as shown in your screenshot, but I'm not sure what to set the value as. Please help, thanks!

**Comment by Fedefreez** [comment]
Can you post a screenshot of the log and the error?
Did you try <a href="https://github.com/desktop/desktop/blob/development/docs/known-issues.md">this</a>?

**Comment by Alexikik** [comment]
> @Fedefreez still nope. I found my answer.
> I've recently updated this (and I was doing it wrong)
> so, I've corrected it to this and now my GH works again :D
> I think it was the wrong start of command prompt that's why.
> ![screenshot_1013](https://user-images.githubusercontent.com/13714092/54050099-50e03f80-4219-11e9-8df0-4e4a7e407caa.png)

That really fucked up my computer. My desktop won't load anymore... I could however press ctrl+alt+delete, open the task manager, open file location on something random. Then find the launcher for chrome... Sooo anyone having the file path for the registry so I can change it back?

**Comment by Alexikik** [comment]
I found the registry path, so I'm back to normal. But that certainly didn't work

**Comment by ursusg** [comment]
Hi everyone I'm having the same issue with my desktop. I'm able to clone other repositories except for a shared one with my friends, any idea why? Here's my error.

Cloning into 'G:\Unity Projects (Github)\bonesquirrel'...
error: cannot spawn C:\Users\Ursus\AppData\Local\GitHubDesktop\app-2.4.0\resources\app\static\ask-pass-trampoline.bat: No error
fatal: could not read Username for 'https://github.com': terminal prompts disabled

**Comment by Fylls** [comment]
same error here, GitHub works fine on chrome but its desktop version gives me an error every operation I execute

here I am pushing a local repo from master to orgin, here's the error:

error: unable to read askpass response from 'C:\Users\serge\AppData\Local\GitHubDesktop\app-2.4.3\resources\app\static\ask-pass-trampoline.bat'
fatal: could not read Username for 'https://github.com': terminal prompts disabled

**Comment by billygriffin** [comment]
Hi @ursusg and @Fylls, sorry about that. Please check out the [known issues](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789) document that discusses possible causes and ways to resolve this.
