### ISSUE TITLE
user not recognized unable to access ask pass trampoline

### ISSUE THREAD

**Issue by Flipfriend** [desktop/desktop#6881]
## Version

* GitHub Desktop:

* Operating system:

**Comment by tierninho** [comment]
@Flipfriend please fill out the above template so we have enough information to better assist you. Thank you for meeting us half way! 😄

**Comment by billygriffin** [comment]
#6882 is where this lives now, so closing this issue. Thanks for updating @Flipfriend!

**Comment by aronquiray** [comment]
https://github.com/desktop/desktop/issues/6879#issuecomment-471042891 
solved this issue for us..
