### ISSUE TITLE
Error message pops up when I try to push to origin.

### ISSUE THREAD

**Issue by Flipfriend** [desktop/desktop#6882]
## Version
 
* GitHub Desktop:1.6.2.0

* Operating system: Microsoft Windows version 6.1.7601

### Expected Behavior

Expected it to push to origin to github url

### Actual Behavior

error message pops up

"'C:\Users\Andrew' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
error: unable to read askpass response from 'C:\Users\Andrew&Sadie\AppData\Local\GitHubDesktop\app-1.6.2\resources\app\static\ask-pass-trampoline.bat'
fatal: could not read Username for 'https://github.com': terminal prompts disabled"

## Additional Information

'C:\Users\Andrew' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
error: unable to read askpass response from 'C:\Users\Andrew&Sadie\AppData\Local\GitHubDesktop\app-1.6.2\resources\app\static\ask-pass-trampoline.bat'
fatal: could not read Username for 'https://github.com': terminal prompts disabled

**Comment by tierninho** [comment]
@Flipfriend please fill out the above template so we have enough information to better assist you. Thank you for meeting us half way! 😄

**Comment by tierninho** [comment]
@Flipfriend Thanks for refilling with the details. We have had some reports of the `askpass` issue creep up in recent weeks, but unfortunately no clear resolution. 

Some workarounds can be found here:
* https://github.com/desktop/desktop/issues/2623
* https://github.com/desktop/desktop/issues/4124#issuecomment-429578543
* https://github.com/desktop/desktop/issues/1916#issuecomment-307607878
* https://github.com/desktop/desktop/issues/2496#issuecomment-323492222
* https://github.com/desktop/desktop/issues/2623#issuecomment-334305916
* https://github.com/desktop/desktop/pull/508

Based on the links, does anything stand out in regards to your setup? Like, are you using Visual Studio, are your credentials in your Credential Manager, do you see your proper avatar in Desktop? Etc...

**Comment by tierninho** [comment]
@Flipfriend  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by aronquiray** [comment]
@tierninho 

got the same problem. 
![screenshot_999](https://user-images.githubusercontent.com/13714092/53900829-5fdbbc00-4078-11e9-92d3-34ac31de6c49.png)

**Comment by aronquiray** [comment]
https://github.com/desktop/desktop/issues/6879#issuecomment-471042891

**Comment by Sameedahmad** [comment]
> @tierninho
> 
> got the same problem.
> ![screenshot_999](https://user-images.githubusercontent.com/13714092/53900829-5fdbbc00-4078-11e9-92d3-34ac31de6c49.png)

ME too

**Comment by tierninho** [comment]
@Sameedahmad Please fill a new issue if the workarounds in https://github.com/desktop/desktop/issues/6882#issuecomment-466600250 are not helping. Thank you.
