### ISSUE TITLE
macOS: Comparing branches with 'Select Branch to Compare...' field does not update commit list(s) immediately

### ISSUE THREAD

**Issue by smittytone** [desktop/desktop#6886]
## Description

Entering a branch name into the left-hand 'Select Branch to Compare...' text field generates the correct display of behind and ahead commit numbers, but clicking on either of these numbers does not display the **Behind X** and **Ahead Y** buttons. These buttons only appear after backgrounding and then foregrounding the app.

## Version

* GitHub Desktop: Version: 1.6.2
* Operating system:  macOS 10.14.3 / dark mode

## Steps to Reproduce
1. Select a current repository with multiple branches.
2. Select a branch in the **Current Branch** dropdown.
3. Click on the **History** tab in the left-hand column.
4. Enter a branch name in the **Select Branch to Compare...** field (or just click on it to compare to master)
5. Click on either of the up/down arrow + numeric value items to the right of the branch name below the **Select Branch to Compare...** field.
6. Observe there are no **Behind X** and **Ahead Y** buttons.
7. Switch to another open app (eg. via the macOS dock).
8. Switch back to GitHub Desktop.
9.  Observe there are now **Behind X** and **Ahead Y** buttons which can be selected to display a list of commits.

### Expected Behavior

Step 9, above, should be Step 6, and subsequent steps be unnecessary.

### Actual Behavior

See [steps to reproduce](#steps-to-reproduce)

## Additional Information

GitHub Desktop used in Dark Mode (OS and app)

**Update** In attempting to make a screen recording of the problem, I did *not* experience it. This suggests the issue relates to the updating of the app's window contents (ie. the missing buttons, etc. are there, but the window image hasn't refreshed to show them).

### Logs

[2019-02-20.desktop.production.log](https://github.com/desktop/desktop/files/2883846/2019-02-20.desktop.production.log)

**Comment by tierninho** [comment]
@smittytone Thanks for filing. Tried to reproduce but could not. I suspect it was just a temporary lag as Desktop loaded the data. 

Any luck reproducing this again? Screenshots or video would help.

**Comment by tierninho** [comment]
@smittytone As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
