### ISSUE TITLE
Projects view is virtually unusable

### ISSUE THREAD

**Issue by msmith046** [desktop/desktop#6887]
When I want to 
create an issue from a project board the + button creates a note - more clicks needed to create an issue
nest issues so I can create a container and decompose I cannot
add an size to an item I cant apart from labels
add up sizes labels cannot be summed
edit an item from the board I have to open the issue
edit a description I cant - everything is a comment
add an item to a milestone I can, but this cannot be done from the project board
see a milestone on a card I cant as I cant edit what is visible
change the states inside a ticket I can but this has no relationship between the state and board column
etc etc

A complete redesign of the project concept is in order to ensure that everything can be done from the project view

**Comment by niik** [comment]
Hi @msmith046, this is the repository for GitHub's open source Desktop client (https://desktop.github.com) so we're unfortunately not able to help you with issues related to projects. I suggest you contact GitHub Support with your concerns instead (https://github.com/contact).
