### ISSUE TITLE
upgrade app to use Electron 5

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#6888]
This should be a smoother upgrade than the Electron 3 process because they use the same version of Node, but #6883 is a known blocker that needs to happen too.

The other issue I'm tracking is https://github.com/electron/spectron/issues/346 which is about using Spectron with Electron 4 - there's a workaround in the issue to get it working with pre-release versions, which is unsatisfying. I'm trying to chase what the status is of this issue.

Given how subtle #6883 was, I'd recommend whoever looks at this issue should try upgrading locally to see if there's any other breakage.

**Comment by shiftkey** [comment]
I think `electron-packager` needs to be updated to address this issue when I try and `yarn build:dev` with Electron 4.0.5:

```
Packaging app for platform darwin x64 using electron v4.0.5
{ Error: ENOENT: no such file or directory, open '/Users/shiftkey/src/desktop/dist/GitHub Desktop-dev-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper EH.app/Contents/Info.plist'
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at packagerPromise (/Users/shiftkey/src/desktop/node_modules/electron-packager/index.js:163:6)
    at packager (/Users/shiftkey/src/desktop/node_modules/electron-packager/index.js:184:18)
    at packageApp (/Users/shiftkey/src/desktop/script/build.ts:198:10)
    at validate_all_1.verifyInjectedSassVariables.catch.then.then (/Users/shiftkey/src/desktop/script/build.ts:100:12)
    at <anonymous>
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/shiftkey/src/desktop/dist/GitHub Desktop-dev-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper EH.app/Contents/Info.plist' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'd recommend doing this in advance, because it seems there's been some recent improvements to `electron-packager` for Mojave support, based on the [latest releases](https://github.com/electron-userland/electron-packager/releases).

**Comment by shiftkey** [comment]
Spectron [4.0.0](https://www.npmjs.com/package/spectron/v/4.0.0) has been published to NPM, and should be upgraded in-step with Electron (because they need to share the same major version of `chromedriver`).

**Comment by HashimotoYT** [comment]
Spectron 4.0.0 !== Electron 4.0.0. Spectron 4.0.0 supports Electron ^2.0.0. See [Spectron version map](https://github.com/electron/spectron#version-map)

**Comment by shiftkey** [comment]
@HashimotoYT oops, yes, I meant to refer to the `v4.0.0` of `electron-chromedriver` that just got an update: https://www.npmjs.com/package/electron-chromedriver/v/4.0.0

Spectron itself still needs an upgrade, based on the issue I linked to in the issue body above.

**Comment by shiftkey** [comment]
We had a report in #7233 of a Windows-specific issue with external monitors, which should be resolved by this upgrade. cc @KyleNanakdewa for awareness.

**Comment by shiftkey** [comment]
For reference, this document will also help with updating to later versions of Electron https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md#planned-breaking-api-changes-50
