### ISSUE TITLE
port custom tslint-rules in codebase to use eslint

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#6889]
The writing is on the wall for the `tslint` ecosystem - the TypeScript team are [planning to focus](https://github.com/Microsoft/TypeScript/issues/29288) on how to make `eslint` work nicely with TypeScript projects in the first half of 2019, and the maintainers of `tslint` [announced their roadmap](https://medium.com/palantir/tslint-in-2019-1a144c2317a9) for deprecating things to transition to using `eslint`.

This affects us in a couple of ways, but something we can do today is investigate porting these custom rules to use `eslint`, so we can lessen our dependency on `tslint` while upstream tooling is doing it's thing.

These rules are very Desktop specific, and are not likely to have external replacements we could churn away to:

 - `tslint-rules/buttonGroupOrderRule.ts`
 - `tslint-rules/reactNoUnboundDispatcherPropsRule.ts`
 - `tslint-rules/reactReadonlyPropsAndStateRule.ts`

This rule could be something we could churn away to, if there's a more complete implementation out there:

 - `tslint-rules/reactProperLifecycleMethodsRule.ts`

cc @j-f1 for thoughts and advice

**Comment by j-f1** [comment]
Looking into this.

**Comment by j-f1** [comment]
Depends on #6771 for some type info.

**Comment by j-f1** [comment]
cc @niik since you originally created the `react-proper-lifecycle-methods` rule

Is it still needed?

**Comment by niik** [comment]
> cc @niik since you originally created the `react-proper-lifecycle-methods` rule
> 
> Is it still needed?

To flip the question around, is there a compelling reason not to utilize it any more? I don't see it as a the most important rule we've got but if we are to remove any static analysis that's currently in place and working I think we should clearly define the advantages of doing so.

**Comment by j-f1** [comment]
How about removing the check on the parameters? That should be covered by TS now.

**Comment by shiftkey** [comment]
@j-f1 

> How about removing the check on the parameters? That should be covered by TS now. 

I gather you're referring to the `@types/react` declarations here, rather than anything included by default with `tsc`?

> I agree the ban on typos is still valid and it makes sense to keep it.

I'm still a big fan of how this rule ensure the parameters are named consistently (matching the React docs), and would advocate for keeping that around...
