### ISSUE TITLE
commit form should provide better context when dealing with rebase conflicts

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#6890]
As part of #6698 the user can dismiss the dialog and end up in this state:

<img width="995" alt="screen shot 2019-02-20 at 11 43 44 am" src="https://user-images.githubusercontent.com/359239/53104022-023a6200-3505-11e9-9d41-c6228badcbd5.png">

If you "Commit to master", you'll trigger the warning about committing files with conflicts - this is fine:

<img width="643" alt="screen shot 2019-02-20 at 11 45 52 am" src="https://user-images.githubusercontent.com/359239/53104109-272ed500-3505-11e9-9061-987454d103e1.png">

And then the rebase trigger kicks in and says "we're good to continue" - this is also fine:

<img width="541" alt="screen shot 2019-02-20 at 11 46 35 am" src="https://user-images.githubusercontent.com/359239/53104172-4299e000-3505-11e9-9668-b837dc10d1ec.png">

But I'd like to change the commit form to do two things:

 - disable the summary and description inputs - being able to specify these details in the commit will clash with the previous history when the rebase was started, which could lead to more confusion
 - change the commit button text to "Continue rebase" to indicate this is not the normal commit flow

I'm also open to other ideas here about this flow, if you've got them.

**Comment by ampinsk** [comment]
> But I'd like to change the commit form to do two things:
>
> * disable the summary and description inputs - being able to specify these details in the commit will clash with the previous history when the rebase was started, which could lead to more confusion
> * change the commit button text to "Continue rebase" to indicate this is not the normal commit flow


This makes sense to me! I could see either this solution or even not showing the commit field, and just showing the button. 

<img width="302" alt="screen shot 2019-02-20 at 9 28 31 am" src="https://user-images.githubusercontent.com/10404068/53111451-eb3e4480-34f1-11e9-822a-aa982cbc6e08.png">

Not sure if this or disabled commit fields would be more frustrating/confusing. I think I prefer this but open to push back!

**Comment by billygriffin** [comment]
I agree with @ampinsk - I think having the fields disabled, but still visible, could potentially distract from the intent of the next action. +1 on not showing the commit fields but just the button in this state.

**Comment by shiftkey** [comment]
> +1 on not showing the commit fields but just the button in this state.

I'm gonna noodle on getting this working next - thanks for the feedback!
