### ISSUE TITLE
branch switcher does not indicate rebase context

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#6891]
When you are in the middle of rebase conflicts in #6698,  you can dismiss the dialog and see this context in the header:

<img width="980" src="https://user-images.githubusercontent.com/359239/53104831-76c1d080-3506-11e9-9a61-e64389cd3cf9.png">

We don't have this problem with merge conflicts because you merge another branch into your current branch (so Git doesn't end up with a detached HEAD), and I'd like to change the text here to something more friendly ("rebasing", with the target branch name and some sort of progress summary to see how far through?).

There's no Octicon available to represent `rebase` but maybe something visual here might help to differentiate it from detached HEAD.

**Comment by ampinsk** [comment]
I'm pretty sure I would expect to see this. I don't think I'd expect to see progress in that area, it should just reflect the branch information. 

<img width="539" alt="rebase-branch-info" src="https://user-images.githubusercontent.com/10404068/53112035-3b69d680-34f3-11e9-9a75-b2aad0ffc2f3.png">

Seems like it'd be possible or potentially more technically correct to do something like this? But I think I find this more confusing. 🤔

<img width="539" alt="rebase-commit-info" src="https://user-images.githubusercontent.com/10404068/53112134-71a75600-34f3-11e9-8710-387e225abc71.png">

**Comment by billygriffin** [comment]
Agreed with @ampinsk - I don't think the commit you're on adds much value to the context, and the "Rebasing branch {branch_name}" is a great thing to put in that area.

One related question though for @ampinsk and @shiftkey: If you're in the middle of a rebase, should you see the dropdown in that branch tab as normal (the dropdown arrow)? I would imagine it becomes more of a status at that point, and not something someone should click. It could match the greyed out state of the "Push/Pull" tab next to it?

**Comment by shiftkey** [comment]
@billygriffin 

> If you're in the middle of a rebase, should you see the dropdown in that branch tab as normal (the dropdown arrow)?

My gut feeling on this is you shouldn't be able to view or checkout a different branch when you're in the middle of a rebase.

> I would imagine it becomes more of a status at that point, and not something someone should click. It could match the greyed out state of the "Push/Pull" tab next to it?

I like this idea, and I think we have existing styles and logic to support this.

**Comment by billygriffin** [comment]
Sounds good to me!

**Comment by ampinsk** [comment]
All makes sense to me!
