### ISSUE TITLE
Missing blankslate image on compare page

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6894]
I am seeing a missing blankslate image on the compare tab if the behind/ahead = 0.

![image](https://user-images.githubusercontent.com/14828183/53112620-bdea9a00-34e3-11e9-8769-9853aaac7fe0.png)

1.6.3-beta1, mac

**Comment by niik** [comment]
Good catch @tierninho. This is my bad, I thought I had removed the last instance of that illustration when I redesigned the no-changes blank slate, see (https://github.com/desktop/desktop/commit/079a8ee32f236554e32fae3df82952936cbf47de). I'll make sure it's brought back.
