### ISSUE TITLE
"Rename Branch" and "Delete Branch" always disabled

### ISSUE THREAD

**Issue by thinkyhead** [desktop/desktop#6899]
Not much detail to report here. I'm using the latest GitHub Desktop on macOS. For the last few versions the "Rename Branch" and "Delete Branch" menu items are always grayed-out… for every branch selected. These same branches can be renamed or deleted from the console without issue.

**Comment by shiftkey** [comment]
@thinkyhead I'm not able to reproduce this behaviour on `1.6.3-beta1`.

For the default branch on a GitHub repository, I see both menu items as disabled:

<img width="686" src="https://user-images.githubusercontent.com/359239/53121778-66701c80-352b-11e9-996c-b77cd9efd487.png">

For any other branch, I see them as enabled:

<img width="671" src="https://user-images.githubusercontent.com/359239/53121802-72f47500-352b-11e9-8825-b2ea597942d5.png">

Here's the rules we use to control these menu items:

https://github.com/desktop/desktop/blob/3223b072978890b0be9fc043a9101b0ae1b63713/app/src/lib/menu-update.ts#L218-L225

Any clues from your setup what might be different about your setup versus mine?

**Comment by shiftkey** [comment]
Closing this out due to inactivity.

@thinkyhead if you're able to provide more details about triggering the issue we can revisit.

**Comment by thinkyhead** [comment]
This is not my default branch:
![image](https://user-images.githubusercontent.com/698003/53690860-30efde00-3d38-11e9-8cab-f4cfa0eba9d9.png)

But it is a branch that I checked out from a different remote than `origin` or `upstream`.

On the other hand, this branch's remote is `origin` so it should be delete-able:
![image](https://user-images.githubusercontent.com/698003/53690876-6dbbd500-3d38-11e9-9823-4b1b4f53c16c.png)

**Comment by thinkyhead** [comment]
Some of my repos behave normally:
![image](https://user-images.githubusercontent.com/698003/53690900-c8edc780-3d38-11e9-8dcf-8d281791e87e.png)

**Comment by shiftkey** [comment]
@thinkyhead for the ones that are not behaving as expected, are they associated with a GitHub remote? What remotes do they have set?

**Comment by thinkyhead** [comment]
I tend to keep about 20 remotes hanging around in this repo. Almost all my branches are created as copies of `upstream/the-dev-branch` and not from my `origin` repo.

**Comment by shiftkey** [comment]
@thinkyhead thanks for that extra clue. I'm going to reopen this up to see if we can figure out how/why that might affect the rename/delete branch menu state.

**Comment by thinkyhead** [comment]
This seems to be resolved by last week's update. Thanks!
