### ISSUE TITLE
Configure tracked LFS files

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#69]
Manage the gitattributes file.

<img width="543" alt="screen shot 2017-06-29 at 3 22 42 pm" src="https://user-images.githubusercontent.com/13760/27713097-d588046a-5cde-11e7-95d0-b3996a373ef9.png">

**Comment by shiftkey** [comment]
Pulling this into 1.0 as it's a missing feature from the classic apps. Let me know if there's any context I've missed as to why we wouldn't.

**Comment by joshaber** [comment]
We decided not to address this when we talked through scope at the mini summit, so I'm gonna 👢 it again 😁

**Comment by joshaber** [comment]
(Unless, that is, we wanna rethink our 1.0 scope.)

**Comment by s-schiegl** [comment]
Any updates on this feature? It would be really helpful for us because we are planning to onboard several users without any Git experience. Having a dialog to manage the LFS tracked files would make things a lot easier for them.

**Comment by nickeubank** [comment]
I just tried to teach some folks as well and ran into same problem as @s-schiegl . Would love to see LFS management in the new desktop!

**Comment by tierninho** [comment]
We be great as part of this to have some visual indicator for LFS files. 

Perhaps where the place marker is here:
<img width="259" alt="Screen Shot 2019-03-29 at 9 01 57 AM" src="https://user-images.githubusercontent.com/14828183/55256574-6ab1e880-5201-11e9-837e-85f45ebb5b57.png">
