### ISSUE TITLE
Can't login to Github desktop

### ISSUE THREAD

**Issue by rmargolis** [desktop/desktop#6900]
## Description
I have multiple computers on a proxy server and I can't seem to login to GitHub desktop. It for some reason allows me to still see the repositories and push/pull branches as if I was signed in, but they are not the most up to date versions. I've added the proxy server that I've read online to the .gitconfig file, however still have no luck.

## Version
Latest version. Reinstalled it today to try and see if that worked but issue still there.
* GitHub Desktop:

* Operating system: Windows 10

## Steps to Reproduce
1. Open the app. However, it automatically loads with my repositories and the current branch I was working on.
2. Sign in
3. It comes up with an error saying "Failed to fetch"

### Expected Behavior

Expect to be able to login
### Actual Behavior

Unable to login, however I can still make pushes/pulls although it's not using my current version of my branch.

### Logs

2019-02-20T00:14:14.219Z - warn: [ui] fetchRepository: an error occurred for 'picotech/picosdk-python-wrappers'
TypeError: Failed to fetch
2019-02-20T00:14:14.464Z - warn: [ui] fetchRepository: an error occurred for 'picotech/picosdk-python-wrappers'
TypeError: Failed to fetch
2019-02-20T00:14:56.263Z - warn: [ui] fetchRepository: an error occurred for 'ProteusMRIgHIFU/Proteus'
TypeError: Failed to fetch
2019-02-20T00:14:56.264Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Proteus - rmargolis (has token)
2019-02-20T00:14:57.341Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.069s)
2019-02-20T00:14:57.691Z - info: [ui] Background fetch for 2 repositories took 85.691sec
2019-02-20T00:29:14.284Z - warn: [ui] fetchRepository: an error occurred for 'picotech/picosdk-python-wrappers'
TypeError: Failed to fetch
2019-02-20T00:29:14.580Z - warn: [ui] fetchRepository: an error occurred for 'picotech/picosdk-python-wrappers'
TypeError: Failed to fetch
2019-02-20T00:29:56.378Z - warn: [ui] fetchRepository: an error occurred for 'ProteusMRIgHIFU/Proteus'
TypeError: Failed to fetch
2019-02-20T00:29:56.378Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Proteus - rmargolis (has token)
2019-02-20T00:29:57.424Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.051s)
2019-02-20T00:29:57.773Z - info: [ui] Background fetch for 2 repositories took 85.768sec
2019-02-20T00:40:06.130Z - warn: [ui] getFetchPollInterval: failed for ProteusMRIgHIFU/Proteus
TypeError: Failed to fetch
2019-02-20T00:40:06.208Z - error: [ui] Error reporting stats:
TypeError: Failed to fetch

**Comment by niik** [comment]
Hi @rmargolis, I'm sorry to hear that you're having issues using GitHub Desktop. It seems to me like there are two problems, one is GitHub Desktop not being able to connect to GitHub.com and one being that your fetches, pushes, and pulls through Git itself is unable to establish a connection to GitHub.com. Both of which are likely related to your use of a proxy.

The first issue surprises me a little because we rarely see Desktop itself having problems connecting through a proxy. Is the machine you're using configured to use the proxy for all applications or are you usually entering the proxy address manually into applications?

It also seems evident that you've been able to connect previously given that the application has your login details and have previously been able to retrieve repository information. Are you aware of any changes to your network recently that might have caused this?

Any information you could provide around the specifics of your proxy setup would be helpful in troubleshooting this.

I'll see if @steveward has any tricks up his sleeve here as well.

**Comment by rmargolis** [comment]
@niik I've had to manually enter the proxy address for everything. It was working fine without any issues up until a few days ago. I've reached out to my IT department to see if anything has changed.

In terms of setting up the proxy for GitHub desktop, I went into the .gitconfig file and added the following line:

[http]
     proxy = http://username:password@proxy.swmed.edu:3128

What confuses me though is that I am able to sign in fine with no issues through the web browser, but then when I click "Sign in through browser" it also says its unable to fetch. Let me know if you need any other information.

**Comment by niik** [comment]
Hey @rmargolis, GitHub Desktop only supports system-wide proxy configuration, in other words the proxy needs to be configured either automatically or explicitly through the system dialog (see below)

<img width="874" alt="image" src="https://user-images.githubusercontent.com/634063/53175250-d9d96300-35eb-11e9-8295-f68cbee774ed.png">

As long as you, or your IT-department is able to get Windows configured with your proxy that should enable GitHub Desktop to work.

Git itself, however, requires explicit proxy setup just like you've already done so hopefully once the system is configured to understand the proxy we should be able to see whether that's configured correctly or not.

**Comment by rmargolis** [comment]
@niik, actually looking back through my settings I already have that configured. I've also entered in the proxy manually as well.

![annotation 2019-02-21 083344](https://user-images.githubusercontent.com/34410340/53176319-703d6280-35b3-11e9-9418-410579733c6c.jpg)

I'm assuming then this would link the problem directly to possibly an incorrect proxy address?

Thanks for your help!

**Comment by niik** [comment]
@rmargolis Ideally your IT-department should make sure that the proxy settings are picked up automatically but entering it manually may work assuming that it's not an authenticating proxy which requires a username and password to connect to (I don't believe Windows supports that out-of-the-box). I'd suggest having a chat with your IT-department and see if they have a good way of configuring the proxy system-wide.

**Comment by rmargolis** [comment]
@niik alright, thanks for your help! I'll let you know one way or the other about the proxy issue after IT comes tomorrow.

**Comment by rmargolis** [comment]
@niik so it appears that IT was no help and couldn't figure out what was going on. Any suggestions for things to try?

**Comment by steveward** [comment]
@rmargolis apologies for the delay here. Do other applications work without issue behind the proxy you have configured?

**Comment by rmargolis** [comment]
@steveward Yes, everything else works behind the proxy. I'm still able to use other applications and I'm connected to the internet which is all connected through the proxy. I can use GitHub to still go in and edit things, but GitHub desktop just fails to connect.

**Comment by rmargolis** [comment]
@steveward @niik Just wanted to update you guys, not sure why all of a sudden it started working, but reinstalling GitHub worked now, although when I tried that 2 weeks ago it didn't do anything so I have no idea why it's working now, I just know that it is working now. Thanks for your help!

**Comment by steveward** [comment]
@rmargolis that's great to hear. I'm going to close this issue out.
