### ISSUE TITLE
Making "Undo" button highlight and click animation more visible

### ISSUE THREAD

**Issue by Frank4Real** [desktop/desktop#6901]
**Please describe the problem you think should be solved**
The buttons in the UI when the mouse is hovering over have a very unnoticeable shadow in the surrounding rectangle, which I didn't notice until I am about to create this issue. My original intend was to say this is no highlight but that is not the case. The other issue here is that there is no indication of whether a button has been successfully clicked.

Example:
A lot of the buttons suffer from these issues. For example, the undo button when changes are ready to be pushed to GitHub.
![image](https://user-images.githubusercontent.com/47638137/53134650-3af22f80-3535-11e9-8ff1-2458707690a9.png)
After being clicked (thanks to the lag I can get a screen shot). It is also what it looks like when mouse is hovering over.
![image](https://user-images.githubusercontent.com/47638137/53134721-7d1b7100-3535-11e9-8037-200062bc3472.png)

The Discard button when not selected
![image](https://user-images.githubusercontent.com/47638137/53134612-19914380-3535-11e9-9085-5c011e11370d.png)
The Discard button after being clicked 
![image](https://user-images.githubusercontent.com/47638137/53134791-cc61a180-3535-11e9-8a74-7bda76da4f14.png)
As you can see there is hardly any noticeable effect that indicates whether the button is highlighted or being clicked.

**[Optional] Do you have any potential solutions in mind?**
A more noticeable highlight effect and click animation.

**Comment by tierninho** [comment]
cc @desktop/design

**Comment by niik** [comment]
Hey @Frank4Real, thanks for opening this! I understand the issue you're describing but it would be very helpful for me if you could elaborate a little bit on how you rely on button hover states and why they are important to you.

Also, I'm assuming you're on Windows, is that right? Are there any particular application (built in or otherwise) that you think does button highlighting especially well?

**Comment by Frank4Real** [comment]
> Hey @Frank4Real, thanks for opening this! I understand the issue you're describing but it would be very helpful for me if you could elaborate a little bit on how you rely on button hover states and why they are important to you.
> 
> Also, I'm assuming you're on Windows, is that right? Are there any particular application (built in or otherwise) that you think does button highlighting especially well?

Hi @niik thanks for getting back to me. I would say this is important in general for any UI so that the user knows something is being selected/highlighted/clicked. The application already does that but it is just that it is so minimal and unnoticeable it feels like it doesn't do that. 

Yes I am using it on Windows 7 Enterprise with version 1.6.2.

Not many applications make me feel that way so I guess all of the other well known Microsoft applications will do. For example Outlook, when a button is selected/clicked the whole button has a different color. For the default theme it is a light blue color when selected and a darker blue when clicked. Atom for another which you guys made, does it differently but well, as it brightens the text when a button is selected, and show a blue outline when it is clicked (look at the Check for Updates in Setting for example).

Hope this helps.

**Comment by shiftkey** [comment]
Bumping this issue because we talked about this in #7180

**Comment by billygriffin** [comment]
We're working on improvements to the "Undo," but I don't think we're planning to change the design here since it's not something we've heard enough of yet. We may continue to iterate more generally as we learn how people want to use undo vs. amend.
