### ISSUE TITLE
Wrong label on optical device

### ISSUE THREAD

**Issue by SusanM1** [desktop/desktop#6906]
** Optical device \ camera ** the shutter button has been labeled wrong and I believe it will affect anyone that had to interact or use the camera. The screen shots are not lining up. I have attached a screen pic to 

(https://drive.google.com/open?id=1RQSz3s4Nx44ad6Ourp1e6Mycw71dxdD5&disco=AAAACijpoWs)

**Please describe the problem you think should be solved**
A clear and concise description of what the problem is and who else might be impacted. Screenshots are encouraged.

I am almost positive a change in coding specifically naming will fix the issue. Then again i may be surprised . 

- Here are a few steps I think will correct the problem. Ill be over at my office by 
 (https://www.github.com/) down the hall from 
 -[X]@DanielHix . Using #refs, and work  **formatting**  software, and <del>tags</del> supported
- [x] list syntax required (not in this order)
- [ ] this is an incomplete item

The one thing that has me a tad concerned is messing with the coding.

**Comment by niik** [comment]
Hi @SusanM1, this is the repository for GitHub's open source Desktop client (https://desktop.github.com) and to my knowledge we don't have any camera/shutter button in the app so we're unfortunately not able to help you with this issue. If you have any questions about the Desktop application please feel free to open a new issue.

**Comment by SusanM1** [comment]
this is Github... who are you?

**Comment by SusanM1** [comment]
crap,,,,, i need to sleep... ngrrr

**Comment by SusanM1** [comment]
i feel like an idiot.. i studied the durn word button on this file so long and the fact Ive been up all night... well heres your pic and the file name... Ill start over after ive hopefully had a nap...


.desktop/app/src/ui/dialog/header.tsx

(Screenshot 2019-02-21 at 8.55.40 AM)
