### ISSUE TITLE
Certain TypeScript language features break syntax detection in code preview

### ISSUE THREAD

**Issue by enioluwa23** [desktop/desktop#6908]
## Description
Kept the title generic as there might be more examples of typescript features that do the same, but as far as I know there is only one: 

Using a constructor type signature to pass a class as a function parameter breaks the syntax in code preview. For example the following draft of code is adapted from a project I am working on, to make it simpler to understand why I used this feature:

```typescript

// Other color classes look like this
export class Red {
  public readonly id: number;
  private readonly store: ColorStore;
  private description: string;

  constructor(id: number, store: ColorStore, description: string) {
    this.store = store;
    this.description = description;
  }
}

export type AnyColor = Red | Blue | Yellow | Green | Purple | Orange;

export class ColorStore  {
  private _colors: AnyColor[];

  private createColor<T extends AnyColor>(type: (new (store: ColorStore, id: number, description: string) => T), id: number, description: string): T {
    const item = new type(this, id, description);
    this.addItem(item);
    return item;
  }

  public addItem<T extends AnyColor>(v: T): void {
    if (this._colors.find((x) => x.id === v.id))
      throw new Error(`The color with id ${v.id} already exists`);
    this._colors.push(v);
  }

  public getItem<T extends AnyColor>(id: number): T | undefined {
    return this._colors.find((x) => x.id === id);
  }

  public deleteItem<T extends AnyColor>(id: number): void {
    const index = this._colors.findIndex((x) => x.id === id);
    if (index < 0) return;
    this._colors.splice(index, 1);
  }
}

```

ColorStore is supposed to be an instantiable class, just imagine it with constructors. The method `createColor` uses the constructor signature from `Red` which would be the same for other colors defined in `AnyColor`. With this method the store can instantiate a new color with its specific class type and store it, all without type info loss/issues.

` private createColor<T extends AnyColor>(type: (new (store: ColorStore, id: number, description: string) => T), id: number, description: string)`

The problem is using this type of signature breaks the rest of the file in code preview. Here is a screenshot: 

![Screenshot of Code Preview](https://i.imgur.com/FZlGGiV.png) 

As you can see the syntax confusion becomes even more apparent when trying to use a variable in a string literal, which ends up displaying the rest of file as part of one. This makes comparing changes harder as it basically feels like viewing a text file.

## Version

* GitHub Desktop: 1.6.2

* Operating system: Microsoft Windows [Version 10.0.16299.904]

## Steps to Reproduce

1. Drop the code from the description into a new file in any repo.
2. View it in code preview.

### Expected Behavior

Proper typescript syntax detection.

### Actual Behavior

Improper detection after using a nifty language feature.

**Comment by shiftkey** [comment]
@enioluwa23 thanks for the report! We leverage Codemirror for the syntax highlighting, rather than something custom to Desktop:

https://github.com/desktop/desktop/blob/ea85ed0f69eaa63d66a164805f4f81a11388391c/app/src/highlighter/index.ts#L45-L50

We're a few versions behind the one we use in Desktop - `5.33.0`, latest is `5.44.0` so I wonder if upgrading the dependency here will help resolve this issue.

If that doesn't fix the issue, I think someone needs to open an issue on https://github.com/codemirror/CodeMirror to bring it to their attention.

Marking this one as `help-wanted` because I think we have enough details here for someone to:
 
 - confirm the sample works as expected after upgrading `codemirror`
 - raise an issue upstream

**Comment by enioluwa23** [comment]
Thanks for the quick response! I will watch and refer this to codemirror if someone confirms it is an outdated dependency issue.
