### ISSUE TITLE
Pre-populate commit summaries

### ISSUE THREAD

**Issue by lukehefson** [desktop/desktop#692]
Maybe because I'm lazy, or maybe because I like to be succinct (not sure which) and because I often work with docs – I often find myself doing very basic commit summaries and providing more granular info in the description. 

For this reason I really enjoy the way that the web UI creates placeholder commit summaries:
<img width="263" alt="screen shot 2016-11-28 at 10 34 34" src="https://cloud.githubusercontent.com/assets/1469659/20665129/4a7fb4ba-b556-11e6-87df-099e40173a5b.png">

I'd really love this functionality for the Desktop app too.

At first I thought, rather that implementing this in the same way as the web UI, with greyed-out placeholders that disappear when you start typing, it would be nicer to pre-fill the actual text so that it can be edited (and also provide an option to clear it!). This also might have the added benefit of drawing attention to the summary as `oh hai this is the next place you need to do something!` as I know that new users can sometimes be confused with the flow.
![test_720](https://cloud.githubusercontent.com/assets/1469659/20665217/9d4fbaaa-b556-11e6-8ee1-fa3b25d814b8.png)

But then I started thinking "maybe clearing text all the time would be super annoying". So I'm not quite sure _what_ might feel better 🤔.

---

Here are the current interactions I can think of:

- Update filename
    - (any change that isn't a delete, remove or rename/move)
- Delete [or 'Remove'] filename
- Rename filename to new-filename

We currently treat moves in the web UI as `Rename old-directory-name/filename to new-directory-name/filename` but `Move filename to new-directory-name/filename` might be nicer.

One potential problem I can think of is that I presume the app will include the 'you might wanna make this summary shorter' feature. And this might be triggered if we pre-populate a summary with a long filename. The web UI just doesn't trigger the warning in these cases.

cc/ @niik as we discussed this a little in Slack.

**Comment by shiftkey** [comment]
@lukehefson thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.
