### ISSUE TITLE
Ignore system bug

### ISSUE THREAD

**Issue by HemulGM** [desktop/desktop#6928]
Пробую игнорировать выбранный файл (*.ini)
Добавляю через контекстное меню, и в файл игнорирования он добавляется, однако даже если отбросить изменения в нём, после последующих изменений он снова не игнорируется. При повторном добавлении файла, файл игнорирования снова пополняется, но без какого-либо эффекта.
![image](https://user-images.githubusercontent.com/22197242/53296295-0df89200-383f-11e9-9049-549438ad20e0.png)

**Comment by shiftkey** [comment]
@HemulGM thanks for the report.

Looking at that screenshot, the diff looks like it's a change to a modified file - which means it's already tracked by Git. The `.gitignore` file is only used for **untracked** files, and once a file is committed to the Git repository it is considered tracked.

You will need to delete the file from the repository, and commit the change, for the `.gitignore` to have any effect on this file.

We are tracking improving this experience in #2537 - please follow along with that discussion.
