### ISSUE TITLE
metrics for rebase features in 1.7.0 

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#6935]
Extracting this from #6550 as the force push work in #6913 is not in scope for `1.6.3`:

> 3\. Number of times a user force pushes (potentially as a % of regular pushes if that's possible?)

**Comment by shiftkey** [comment]
@scottypate @billygriffin just a heads up - we currently split the `push` stats into three measures based on the remote:

 - `dotcomPushCount`
 - `enterprisePushCount`
 - `externalPushCount`

https://github.com/desktop/desktop/blob/5ecf2e2faf84b763c86028f359623de9128c097f/app/src/lib/stores/app-store.ts#L2747-L2755

Are we fine with just having additional `ForcePush` measures, e.g. `dotcomForcePushCount`, `enterpriseForcePushCount`, `externalPushCount`?

**Comment by billygriffin** [comment]
@shiftkey That's fine from my perspective but interested in @scottypate's view.

**Comment by scottypate** [comment]
This is good for me as well. I was thinking it would be interesting to know if the force pushes are preceded by a push error. I think the best place to instrument push fails is on the .com side's push data.
