### ISSUE TITLE
Line numbers disappear

### ISSUE THREAD

**Issue by cheshire137** [desktop/desktop#6938]
I'm in version 1.6.3-beta2 and line numbers disappear from the diff sometimes. I viewed a changed file in Desktop, then switched to my editor and modified one of the changed lines, and when I switched back to Desktop, the diff updated to show my latest change but at the same time the line numbers went away.

![image](https://user-images.githubusercontent.com/82317/53363488-385f5380-3902-11e9-8ea2-26b12b77c1e6.png)

**Comment by cheshire137** [comment]
Possibly related? #6707

**Comment by tierninho** [comment]
Reproducible: yes

Steps: Look at the diff in Desktop, switch to the editor, change one of the already changed lines and then switch back to desktop. Note, it cannot be a file that scrolls.

The lines will comes back if you switch files and return.

**Comment by billygriffin** [comment]
@tierninho Is this reproducible on both prod and beta, or just on beta?

**Comment by tierninho** [comment]
@billygriffin Only on beta.
