### ISSUE TITLE
Search when there are multiple hundreds of files being tracked

### ISSUE THREAD

**Issue by Kool-Koder** [desktop/desktop#6941]
Is it possible to search for files that are being uploaded to github, those that are being tracked with changes. Sometimes, you want to upload a project to github and there are hundreds of files and you may want to search if a file actually exists or something along the lines. What we have to do now is manually scroll through hundreds of files.

Maybe there is a way to add in a search bar at the top right side of the changed files? Thank you. Really hope this can be implemented :)

**Comment by shiftkey** [comment]
@Kool-Koder thanks for the feedback. We have a similar request to this in #6407, which I'll add your comment to. Please follow along with that discussion.
