### ISSUE TITLE
Push status is truncated

### ISSUE THREAD

**Issue by gingerbeardman** [desktop/desktop#6956]
**Please describe the problem you think should be solved**

Push status is truncated in the narrow "tab" element:
<img width="270" alt="screen shot 2019-02-27 at 10 38 13" src="https://user-images.githubusercontent.com/49612/53493429-38db2400-3a93-11e9-9134-f12f799d9be7.png">

There is lots of room in the window, the size of this tab seems artificially limited.

Workaround: mouse over to see tooltip. Not a great solution.

**[Optional] Do you have any potential solutions in mind?**

The "tab" should take up the whole available width.

**Comment by shiftkey** [comment]
@gingerbeardman thanks for the feedback! I'll also cross-reference #4569 which talks about making the branch switcher expand to fill the available space.

**Comment by tierninho** [comment]
Given that rebasing is on the [roadmap](https://github.com/desktop/desktop/blob/development/docs/process/roadmap.md), it seems reasonable to re-examine this again as this is not ideal. 

The end user should be provided with complete context upon first glance. 

<img width="268" alt="screen shot 2019-02-28 at 10 02 50 am" src="https://user-images.githubusercontent.com/14828183/53595061-5dd9a080-3b40-11e9-8572-72cf08aa9cfa.png">

**Comment by milholen** [comment]
I was going to submit the same issue, good to see that I'm not the only one who noticed this. IMO it would be best to handle the Branch and Fetch/Push/Pull as dynamic columns that are each 50% of the available width.

Mac Desktop screenshot:

<img width="1126" alt="space" src="https://user-images.githubusercontent.com/134360/54933084-35438d00-4ed9-11e9-9e56-b35165918671.png">

**Comment by steveward** [comment]
Closing in favor of https://github.com/desktop/desktop/issues/17388 and https://github.com/desktop/desktop/pull/18095 is also open to address this.

**Comment by gingerbeardman** [comment]
@steveward I'm glad the problem has got some attention after 10,000 issues and 4+ years
