### ISSUE TITLE
Extremely slow cloning repos

### ISSUE THREAD

**Issue by Sibz** [desktop/desktop#6957]
## Description

When I clone a large repository it is downloading very slowly. My connection is 100mbps and tests ok, it's just github that is slow. varying between 50 to 200 kbps. It never used to be so slow.

## Version

* GitHub Desktop: 1.6.2

* Operating system: Microsoft Windows [Version 10.0.17134.590]

## Steps to Reproduce

Install Github desktop if not already installed.
Sign into account.
Clone a large repository (In my case its 1gb)

### Expected Behavior

Download within a decent timeframe

### Actual Behavior

Takes about an hour to close

## Additional Information

I have checked my network connection and have no issues with national or international bandwidth. 
I am located in Australia.

![githubreport](https://user-images.githubusercontent.com/12050358/53532963-10176500-3b4d-11e9-9fcf-f8324bdb896f.png)

### Logs

[2019-02-28.desktop.production.log](https://github.com/desktop/desktop/files/2913130/2019-02-28.desktop.production.log)

**Comment by shiftkey** [comment]
@Sibz thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Could you also attach the full log files? The **Help** | **Show Logs in Explorer/Finder** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

Thanks for understanding and meeting us half way 😀

**Comment by Sibz** [comment]
Sorry didn't scroll down the template enough I guess.
I just Factory Reset the computer I experienced this on so are currently reproducing on my desktop. It'll take an hour or so to clone. I'll then attach the logs. Updated original post with more info.

**Comment by maxbed** [comment]
Mr. MaxBed вам је послао/ла имејл у Gmail поверљивом режиму:Re: [desktop/desktop] Extremly slow cloning repos (#6957)Ова порука је послата 27.02.2019. у 16.35.14 PSTМожете да је отворите кликом на линк испод. Овај линк функционише само за reply@reply.github.com.Прикажи имејлGmail поверљив режим вам даје већу контролу над порукама које шаљете. Подесите датум истека, онемогућите штампање или прослеђивање поруке и још много тога. Сазнајте вишеGmail: Google-ов имејлКоришћење подлеже Google политици приватностиGoogle LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USAПримили сте ову поруку зато што вам је неко послао имејл у Gmail поверљивом режиму.

**Comment by shiftkey** [comment]
@Sibz thanks for the details. I can see from the logs that the clone takes ~26 minutes to complete

```
2019-02-28T00:54:23.245Z - info: [ui] Executing clone: git -c credential.helper= clone --recursive --progress -- https://github.com/Sibz/TD-Trains.git O:\UnityProjects\TD-Trains (took 1565.086s)
```

**Comment by Sibz** [comment]
A significant improvement from the previous effort. Average speed ~650KBps. Much better. I repeated the clone today and noticed the speed has improved, when it gets to cloning the large files, it stays around 330KB/s instead of the previous varying between 50-200KB/s. It's just the large files that seem to slow things down. 

Today's clone log:
`2019-03-01T03:50:14.678Z - info: [ui] Executing clone: git -c credential.helper= clone --recursive --progress -- https://github.com/Sibz/TD-Trains.git O:\UnityProjects\TD-Trains (took 957.106s)`
So things have got a bit faster.

**Comment by shiftkey** [comment]
@Sibz I'm not sure how much control Desktop itself has over this, but you can try cloning from the command line (which is the same behaviour as Desktop) and see how much it differs.

From Git Bash, here's how I'd measure it:

```
$ time git clone [url] some-clone-path
Cloning into 'some-clone-path'...
remote: Enumerating objects: 227, done.
remote: Counting objects: 100% (227/227), done.
remote: Compressing objects: 100% (135/135), done.
remote: Total 143409 (delta 140), reused 146 (delta 92), pack-reused 143182
Receiving objects: 100% (143409/143409), 42.21 MiB | 12.04 MiB/s, done.
Resolving deltas: 100% (114810/114810), done.
Checking out files: 100% (2024/2024), done.

real    0m8.704s
user    0m0.000s
sys     0m0.015s
```

From PowerShell:

```
> Measure-Command { git clone [url] some-clone-path }
Cloning into 'some-clone-path'...
remote: Enumerating objects: 227, done.
remote: Counting objects: 100% (227/227), done.
remote: Compressing objects: 100% (135/135), done.
remote: Total 143409 (delta 140), reused 146 (delta 92), pack-reused 143182 eceiving objects: 100% (143409/143409), 37.7Receiving objects: 100% (143409/143409), 42.21 MiB | 7.56 MiB/s, done.

Resolving deltas: 100% (114810/114810), done.
Checking out files: 100% (2024/2024), done.


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 12
Milliseconds      : 101
Ticks             : 121016816
TotalDays         : 0.000140065759259259
TotalHours        : 0.00336157822222222
TotalMinutes      : 0.201694693333333
TotalSeconds      : 12.1016816
TotalMilliseconds : 12101.6816
```

If a command line clone is in the same neighbourhood then I think we're limited by what GitHub's infrastructure can serve up to 🇦🇺 users currently...

**Comment by Sibz** [comment]
Results:

> Cloning into 'tdtrains'...
> Username for 'https://github.com': steven@entityzero.com
> Password for 'https://steven@entityzero.com@github.com':
> remote: Enumerating objects: 1054, done.
> remote: Counting objects: 100% (1054/1054), done.
> remote: Compressing objects: 100% (328/328), done.
> remote: Total 1054 (delta 718), reused 1052 (delta 716), pack-reused 0 eceiving objects:  88% (928/1054), 304.57 MiB | 170.00 KiB/s
> Receiving objects: 100% (1054/1054), 304.58 MiB | 176.00 KiB/s, done.
> Resolving deltas: 100% (718/718), done.
> Checking out files: 100% (170/170), done.
> 
> 
> Days              : 0
> Hours             : 0
> Minutes           : 29
> Seconds           : 50
> Milliseconds      : 564
> Ticks             : 17905646836
> TotalDays         : 0.0207241282824074
> TotalHours        : 0.497379078777778
> TotalMinutes      : 29.8427447266667
> TotalSeconds      : 1790.5646836
> TotalMilliseconds : 1790564.6836

A little slow today, but obviously the GitHub network slowing us down.

**Comment by billygriffin** [comment]
Hi @Sibz, sorry to hear the issue is still sometimes persisting. Since it's happening as well on the command line, there's nothing our team can do on this. If you continue to have issues, I'd recommend sending a note to support@github.com. Thank you!

**Comment by justingolden21** [comment]
I've been getting 1-7KiB/s for about a half hour now, and our internet is awful, but not that awful. I've tried stopping the clone and restarting the application, and it still gets hung in the same place.

**Comment by codingedward** [comment]
Same here, getting 1-2KiB/s using `git clone` on command line.

**Comment by Con-Artist-1** [comment]
I had the same issue but fixed it using Cloudfare DNS instead of the default google.
