### ISSUE TITLE
Command line tool

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#696]
Desktop Classic for Mac includes a little command line tool you can install that lets you do things like `github .` to open the current directory in Desktop.

Should we do that in TNG as well? Does Windows do something similar?

**Comment by feross** [comment]
Just wanted to chime in and say that I use the `github` shortcut all the time!

```bash
alias gh='github'
```

Great work, and excellent launch. Congrats!

**Comment by zeke** [comment]
This is what I'm using to open repos from the command line:

```sh
gd() {
  local dir=${1:-.}
  local repo=$(cd $dir && git config remote.origin.url)
  open x-github-client://openRepo/${repo}
}
```

Caveat: the repo has to have already been set up in the Desktop app.

**Comment by Haacked** [comment]
Similar to @zeke, I have a git alias for the new Desktop.

```
[alias]
    open = "!f() { REPO_URL=$(git config remote.origin.url); explorer x-github-client://openRepo/${REPO_URL%%.git}; }; f"
```

> Caveat: the repo has to have already been set up in the Desktop app.

If you run that command from a repository that is not already set up in Desktop, you'll see a clone dialog with the current path. If you click OK to clone, it won't clone again but realize it's already up to date and set it up in Desktop.

Not as nice as the old `github .` command. But it's a stop gap until this gets implemented.

**Comment by rlabrecque** [comment]
If this is something that you guys want still it could go well with: https://github.com/desktop/desktop/issues/1586

Running "Github Desktop.exe" -c "command" or something would be pretty awesome. Lots of code share there.

**Comment by clinejj** [comment]
Chiming in here, but this also breaks on OSX for repos with certain hooks (specifically my team is using [overcommit](https://github.com/brigade/overcommit) on a rails project that throws an error every time I do anything with the repo, since when launched from Finder it isn't configured with the appropriate environment variables. 

However, the command line launch fixed this issue in previous versions.

**Comment by joshaber** [comment]
Thanks @clinejj! That's also related to #1391 in that they would both be fixed by the app inheriting the shell's environment regardless of how it's launched.

**Comment by brennanMKE** [comment]
I just updated to use the React Native version of this app. Since it did not retain all of the repos I had added in the Mac version I had to add many manually. I did not take the time to add all of the ones which were in there before. Since I could not use `github .` I had to use the multiple step process for many repos. And once I did get them added I found that I could no longer copy the hash from the currently selected commit. That completely breaks my workflow so I will have to use another tool like GitUp which does work with my command-line and allows me to copy the commit hash. I feel these are important features to really making this React Native version as functional of the native Mac version.

GitUp is also Open Source. I've even set up this alias which allows for quickly opening a repo from the Terminal.

`alias gu='open $@ -a "GitUp"'`

https://github.com/git-up/GitUp

There is a command-line tool available with GitUp. Perhaps it could be helpful in building one out for GD.

**Comment by brennanMKE** [comment]
I've created a feature request for copying the hash. #1774

**Comment by feross** [comment]
Sadly, I will have to switch back to the non-Electron version of the app until this feature is implemented. It's just too important to my workflow. Again, love the app – great work!

**Comment by scanny** [comment]
+1 for `github` command-line launcher for Mac / OS X terminal. I'm always at the terminal when I need it and it's very convenient that it opens it in the right place. Small tool but big workflow lubrication :)

**Comment by mikeabiezzi** [comment]
+1 to be able to open GitHub desktop from a repo in the command line. It's invaluable in my gig work flow.

**Comment by joewiz** [comment]
+1 for `github` command-line launcher for macOS. I use in a script to help my colleagues pre-populate their GitHub Desktop app with all of the repositories that we use.

**Comment by scanny** [comment]
Just installed from the new release, works a treat! Thanks so much for this guys :) :1st_place_medal:

**Comment by elfxiong** [comment]
Is the "github" command line tool not available for Windows yet? The release note for version 0.7.0 doesn't say this feature is for Mac/Linux only, but I just tried and it doesn't work on Windows. Am I missing anything?

**Comment by mikeabiezzi** [comment]
Thank you!!!!

**Comment by joshaber** [comment]
@elfxiong In what way does it not work? Can you check what your `Path` is?

**Comment by elfxiong** [comment]
@joshaber Command not found, so it is not in my `Path`. I don't seem to find any instruction anywhere on which path to put in `Path`, nor is there a command in menu bar like "enable command line tool" (adding something to `Path`).

I used Everything to search for any file named similar to "github.exe", and have only found "Github Desktop.exe" in "C:Users\MyUserName\AppData\Local\GitHubDesktop".

**Comment by joshaber** [comment]
Right, it _should_ update your `Path` automatically. Could you copy and paste your `Path` in here?

**Comment by elfxiong** [comment]
Here is my `Path`:
```C:\Program Files\Docker\Docker\Resources\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Git\cmd;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\Users\elfxiong\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\elfxiong\AppData\Local\Programs\Python\Python36\;C:\Users\elfxiong\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\Binary;C:\Users\elfxiong\AppData\Local\atom\bin;C:\Program Files\Heroku\bin;C:\Users\elfxiong\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\171.4424.42\bin\;C:\Users\elfxiong\AppData\Roaming\npm```

**Comment by joshaber** [comment]
Thanks @elfxiong! What files and directories are in `%LocalAppData\GitHubDesktop`?

**Comment by awwwis** [comment]
i have the exact same case as @elfxiong , the contents of the requested directory is:
```
MINGW32 ~/AppData/Local/GitHubDesktop
$ ls
 app.ico      app-0.7.0/             packages/           Update.exe*
 app-0.6.2/  'GitHub Desktop.exe'*   SquirrelSetup.log
```

**Comment by joshaber** [comment]
@elfxiong @awwwis would you mind checking to see if you have any logs at `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`?

**Comment by awwwis** [comment]
yup I got a bunch of logs, anything particular I need to look for?

**Comment by joshaber** [comment]
Could you upload the most recent ones for me to check out?

**Comment by awwwis** [comment]
[2017-07-21.desktop.production.log.txt](https://github.com/desktop/desktop/files/1166545/2017-07-21.desktop.production.log.txt)

**Comment by joshaber** [comment]
Hmm, that doesn't have anything helpful 😞 

Let's try setting it up manually. In a command prompt, try running:

```
%LocalAppData%\GitHubDesktop\app-0.7.0\GitHub Desktop.exe --squirrel-updated
```

And then try again. If that still doesn't work, could you again list the contents of `%LocalAppData%\GitHubDesktop`?

**Comment by elfxiong** [comment]
Thank you, @joshaber. Manual setup works!

After running (I need to add the quotes because of the space in the file name)
```
"%LocalAppData%\GitHubDesktop\app-0.7.0\GitHub Desktop.exe" --squirrel-updated
```
`bin\github.bat` shows up in `%LocalAppData%\GitHubDesktop` directory. The `bin` directory has been added to `Path` by the above command. The `github` (and `github .` etc.) command works now.

**Comment by shiftkey** [comment]
I've opened #2312 to track investigating the Windows-specific reports about it not being available on `PATH` after updating. Please comment there if you still have issues after updating to `0.7.0`.

**Comment by Baneeishaque** [comment]
I have to run `C:\Users\Admin\AppData\Local\GitHubDesktop\app-2.4.0\GitHubDesktop.exe  --squirrel-updated` - still, windows specific issue not fixed? - And in another machine bin folder appeared with the installation & no more additional steps. both machines running win 7 64bit.
