### ISSUE TITLE
Warn if there will be conflicts prior to starting a rebase

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#6960]
Extracted from #6551

Similar to what we show in the Merge Branch dialog:

<img width="307" src="https://user-images.githubusercontent.com/359239/53506317-1db8e600-3a8c-11e9-880d-48758bc99a0c.png">

**Comment by outofambit** [comment]
@billygriffin and I discussed this last week and we've agreed that this is not a high impact enough feature to invest more time and energy on. The signal to noise ratio of this is lower than the merge conflict warning UI, and is more likely only to be seen by user's who don't need to know if there will be conflicts or not before they start a rebase. Closing.
