### ISSUE TITLE
test CI providers on Node 10

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#6965]
**Please describe the problem you think should be solved**

Our CI providers spent time installing a specific version of Node 8 because that's the version we settled on ages ago. I think we can leverage a later version of Node, and potentially see some improvements in the time to build and test the app.

**[Optional] Do you have any potential solutions in mind?**

These are the relevant build configs that need updating:

 - [`.circleci/config.yml`](https://github.com/desktop/desktop/blob/development/.circleci/config.yml)
 - [`.travis.yml`](https://github.com/desktop/desktop/blob/development/.travis.yml)
 - [`appveyor.yml`](https://github.com/desktop/desktop/blob/development/appveyor.yml)
 - [`azure-pipelines.yml`](https://github.com/desktop/desktop/blob/development/azure-pipelines.yml)

**Comment by shiftkey** [comment]
Dropping `help wanted` here because I don't think PRs will be able to change build configs (as a security measure) so this isn't ideal for external contributors to pick up.

**Comment by shiftkey** [comment]
As part of reviewing #7381 I noticed that Travis is inheriting it's configured version instead of what's in `.nvmrc`. Whoever gets to this work should confirm we can remove this config value so we have one fewer config value to update:

https://github.com/desktop/desktop/blob/4484f85735afd4afa2a396548cafa522663dc308/.travis.yml#L29-L30

**Comment by shiftkey** [comment]
Tweaking the issue title and body to focus on Node 10 (which is still LTS and will be the [active LTS until April 2020](https://nodejs.org/en/about/releases/))

**Comment by Rexogamer** [comment]
The CircleCI config doesn’t seem to mention Node, and all the others have been updated , so should this be closed?

**Comment by shiftkey** [comment]
@Rexogamer we addressed the CircleCI issue in #7836 as well as #7507 and #7900 so I think this is good to close out.
