### ISSUE TITLE
Timestamp in history

### ISSUE THREAD

**Issue by obendev** [desktop/desktop#6975]
It would be super cool a have a timestamp in the commit info.

![Timestamp idea](https://i.imgur.com/1H17CYW.png)

Currently there are only rough times in the history list, but it would be cool to have a more detailed info about when the changes were made.

**Comment by j-f1** [comment]
If you hover over the date, you’ll get a popup with the actual date.

**Comment by shiftkey** [comment]
@obendev thanks for the feedback!

As @j-f1 pointed out, we should display a tooltip for the absolute time whenever you see a relative time entry in the app:

<img width="428" src="https://user-images.githubusercontent.com/359239/53566957-249b3380-3b34-11e9-81bf-d24fa7c54baa.png">

Are you able to elaborate more on why you something should also exist in the commit details header?

**Comment by obendev** [comment]
Thanks you both for the hint and quick response.

I did know this feature, however I think that the timestamp is a useful information/detail which you should be able to access in the detailed view in terms of UX. Since we have enough space in the detailed view I think that would be a good trade.

**Comment by billygriffin** [comment]
Hi @obendev, thanks for the thought! Would you mind sharing a few instances where the timestamp would be beneficial to you over and above what you get from the existing pattern? A general principle I hold is that anything added necessarily takes away from everything else, so while I totally appreciate the idea that there's sufficient space, we want to focus people's attention on things that are adding clear and obvious value. Any thoughts you have would be really helpful!

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @obendev if you're able to answer the questions in the previous comment to help us understand the suggestion better we're happy to discuss further.
