### ISSUE TITLE
FR: history of specific file 

### ISSUE THREAD

**Issue by ggrrll** [desktop/desktop#6976]
Hi,

I was thinking that would be nice to have 'in one click' the history of a specific file, pretty much like what happens for instance with `log selected` (context menu) in SourceTree  (and maybe also  the possibility to create a branch from that point in history, to browse the whole repository at that point in time, etc...)

Thanks

**Comment by shiftkey** [comment]
@ggrrll thanks for the feedback! Please follow along with our earlier discussion about this: #3754
