### ISSUE TITLE
openLocalRepo and openRepo with branch parameter

### ISSUE THREAD

**Issue by pinguin999** [desktop/desktop#6977]
To change the local branch from the browser the URLs openLocalRepo and openRepo need a extra parameter branch. With this option I can jump into a branch with one click from the web ui.

Example:

`x-github-client://openRepo/https://github.com/desktop/desktop?branch=master`

`x-github-client://openLocalRepo/C:/x/y/z?branch=master`

In app\src\cli\commands\clone.ts is already code for that. Maybe we only need tests and docs for this.

**Comment by shiftkey** [comment]
@pinguin999 thanks for the feedback!

> With this option I can jump into a branch with one click from the web ui.

This is a feature that is managed by a different part of GitHub, and I'm not sure of the overall impact of changing this. I worry this might be confusing to users who just wanted to clone the repository down but find themselves on an unexpected branch.

> In `app\src\cli\commands\clone.ts` is already code for that.

This detection is for opening a pull request from the GitHub website (when the source is a local branch), or when viewing a file and wanting to open that file in Desktop (because the file may not exist on all branches).

cc @desktop/product for thoughts and questions about what is being proposed

**Comment by pinguin999** [comment]
@shiftkey thanks for your fast feedback. Can you provide me an example link for  

> open one file 

> opening a pull request

**Comment by shiftkey** [comment]
> open one file

Check out the header when viewing a file, e.g.: https://github.com/desktop/desktop/blob/development/.gitignore

<img width="991" src="https://user-images.githubusercontent.com/359239/53572531-d2f9a580-3b41-11e9-960a-372e850b87e8.png">

> opening a pull request

When you have permission to merge a pull request you'll see some extra links alongside the merge button at the footer:

<img width="795" src="https://user-images.githubusercontent.com/359239/53572530-d2f9a580-3b41-11e9-9e03-4ecd63a5716d.png">

In both of these cases, Desktop will use an existing repository if it's already present in the app. But if it's not found, it will be cloned and then checked out to the requested branch.

**Comment by billygriffin** [comment]
@pinguin999 Thanks for the issue! Would you mind sharing a few examples in the web UI where this would be valuable to you and you can't do it today? The primary use case we've seen here has been in the context of a PR, which should open the PR's branch in Desktop via the link that @shiftkey shared. But I'm curious if there's a different case you're thinking about, and if you wouldn't mind describing when and how you'd use it that would help us get our arms around how broadly beneficial it might be for folks.

**Comment by pinguin999** [comment]
Wow that's working great. 👍 Does this only works with repos hosted on github? 

I'm working on a repo hosted on X. If I create a link like 
`x-github-client://openRepo/https://X/project?branch=test`

this works. I can clone this and it switch into branch test. 👍 

But the second switch into master for example: 
`x-github-client://openRepo/https://X/project?branch=master` 
opens the clone window again. Is there any magic how a repo is connected to the local clone?

**Comment by shiftkey** [comment]
> Is there any magic how a repo is connected to the local clone?

I wouldn't call it magic, but I think you're interested in this code:

https://github.com/desktop/desktop/blob/40a7abaf9094bdb88c435662ea6a9b8705e4c1d4/app/src/ui/dispatcher/dispatcher.ts#L1110-L1127

https://github.com/desktop/desktop/blob/249c06d51332a7254de848e1c77a60e1ae52d587/app/src/lib/repository-matching.ts#L152-L158

**Comment by shiftkey** [comment]
@pinguin999 thanks for your interest in the Clone in Desktop feature.

At this time we're not interested in changes to how this area works without more thought about the impact to the GitHub website. If you have clarifying thoughts about the proposed change as requested in this comment https://github.com/desktop/desktop/issues/6977#issuecomment-468316183 we'd love to hear them, otherwise I'm going to close this out as resolved.

**Comment by luchopb** [comment]
Hi, I'm trying to use this functionality in my web app. I want users of my incident management system to be able to access GitHub Desktop from the web with the repository and branch already selected. I've tried the two methods mentioned above, but I haven't had any success.

With the first method, `openRepo`, every time I click the button, it takes me to GitHub Desktop with the "clone repository" screen, but the repository already exists on my local machine.

`x-github-client://openRepo/https://bitbucket.org/idealsurteam/code_crmpacientes.git?branch=Unificacion-de-ambientes`

With the second method, `openLocalRepo`, it doesn't do anything at all in GitHub Desktop.

`x-github-client://openLocalRepo//Users/luchito/Documents/GitHub/code_crmpacientes?branch=Unificacion-de-ambientes`

Can anyone help me? What I want to achieve is the same thing as on the GitHub website: when I click the link and the repository doesn't exist on my local machine, it takes me to the "clone it" screen. If the repository already exists, it takes me to the specified repository and branch.
