### ISSUE TITLE
Sublime text editor no longer shown

### ISSUE THREAD

**Issue by mjc-mia** [desktop/desktop#6978]
## Description

List of editors no longer shown after latest update.  Only Atom is listed.  Specifically, Sublime Text not shown.

## Version

1.6.2
* GitHub Desktop:

* Operating system:
Microsoft Windows [Version 10.0.17763.316]

## Steps to Reproduce

1.  Main panel first button shows "Open in Atom."
2.  From main panel, click on "options" to select list of other editors.
3.  Select "Advanced" tab.
4. Click on drop-down window to select text editor.

### Expected Behavior

Sublime text to be included (was included before github desktop version update)
### Actual Behavior

Only Atom shown

**Comment by shiftkey** [comment]
@mjc-mia thanks for the report!

> Sublime text to be included (was included before github desktop version update)

This is the registry location that Desktop checks to find a valid Sublime Text install:

https://github.com/desktop/desktop/blob/0ff5f8383150328523a933655238d05e1773f549/app/src/lib/editors/win32.ts#L126-L133

What version of Sublime do you have installed? I wonder if an upgrade has moved this and we need to check a new location to detect it...

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @mjc-mia if you're able to provide more details about your Sublime Text setup we can revisit this.

**Comment by Brambor** [comment]
I have the same issue, Sublime text isn't listed, only Visual Studio Code is.

**Comment by thataboy** [comment]
I also have the same issue. I think the problem is I did a portable sublimetext install, so there's no uninstall entry, which is what github desktop is looking for, apparently. The command line git can see and use sublimetext, because I think it is checking my path for subl (I am on Windows 64bit).

**Comment by NosferatuJoe** [comment]
Having the same issue with sublime 4 using latest github desktop.

**Comment by Justin-JHG** [comment]
same here with sublime text 4

**Comment by dchassin** [comment]
I have the same issue with Sublime Text 4 on MacOS Big Sur.

**Comment by shiftkey** [comment]
@dchassin @Justin-JHG @NosferatuJoe please open a new issue because e499d35dd0d0a8c713500ff64493d87cd142e947 should be detecting this since release `2.6.3`, and I'm able to select Sublime Text in the current beta (`2.8.4-beta1`) on macOS 10.15.7:

<img width="803" src="https://user-images.githubusercontent.com/359239/121066014-cf810a00-c79f-11eb-8aea-678020d0a1ce.png">

I also see the right identifier when I query for the app bundle, but perhaps something has changed in Big Sur that we're not aware of:

```
$ mdls -name kMDItemCFBundleIdentifier -r /Applications/Sublime\ Text.app
com.sublimetext.4%
```

**Comment by dchassin** [comment]
This is what it looks like on my freshly minted Big Sur system:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/20801735/121092971-3fdc5b00-c7a1-11eb-8879-bf6b213a3af8.png">
yet sublime is installed:
<img width="813" alt="image" src="https://user-images.githubusercontent.com/20801735/121093176-7fa34280-c7a1-11eb-835c-840a856cb1d7.png">

See #12398.
