### ISSUE TITLE
Removing files from cache not committing correctly

### ISSUE THREAD

**Issue by browner12** [desktop/desktop#6983]
## Description

When trying to remove files from git without deleting them, I go to the terminal and run `git rm --cached file/to/remove.txt`. Github Desktop shows the file with the red minus icon, indicating it will be removed. However, when I commit and push, the files remain in the repo.  If I check the commit history, it shows the files being updated instead of deleted.

## Version

* GitHub Desktop: 1.6.2

* Operating system: MacOS 10.14.3 (Mojave)

## Steps to Reproduce

1. `git rm --cached /some/file.txt`
2. Commit and push in Desktop

### Expected Behavior

I expect the files to be removed from git.

### Actual Behavior

The files are showing as changed, not deleted.

## Additional Information

None that I can think of.

**Comment by shiftkey** [comment]
@browner12 thanks for the feedback! This is the same as #4133 for which we have a fix under review in #4147. Please follow along with that issue and PR.

**Comment by browner12** [comment]
thanks for pointing these out.

thanks for all your work!
