### ISSUE TITLE
"abort rebase" should ask for confirmation when users have resolved some conflicts

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#6989]
**Please describe the problem you think should be solved**

https://github.com/desktop/desktop/issues/6548#issuecomment-468509715

From @tierninho:

>  I noticed when you abort a fixed conflicted file in a merge commit, there is no "are you sure" check like we have in the existing merge flow. Is this needed for rebasing?

![](https://user-images.githubusercontent.com/14828183/53610583-8331d300-3b6f-11e9-9152-c1df99cd7bb4.png)

From @billygriffin 

> I think I'd generally be inclined to have a confirm on abort only if they've already resolved some subset of conflicts already (which is @tierninho's use case). In that case, by aborting you're effectively losing work, so my preference would be that this should exist.

**[Optional] Do you have any potential solutions in mind?**

Something based on what we've learned from Merge Conflicts. More to details to come.

**Comment by tierninho** [comment]
Tested and LGTM.
