### ISSUE TITLE
"pull branch" blank slate action needs to be aware of force push

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#6990]
Found this bit of inconsistent UX while testing #6981:

<img width="1264" src="https://user-images.githubusercontent.com/359239/53664503-05d59380-3c3f-11e9-875d-7cfb13ea4b15.png">

Two ideas come to mind about addressing this:

 - we hide the blank slate action, because with great power comes great responsibility
 - we update this blank action to be aware a force push is permitted, and explain more about what will happen

**Comment by billygriffin** [comment]
@shiftkey Could we chat about this a bit more. I'd love to understand the circumstances when folks will end up in this situation and then figure out whether we want to nudge toward it (in which case the second thing might be more appropriate) or not (in which case your first suggestion might be).

**Comment by billygriffin** [comment]
Discussed this with @shiftkey, and we decided we'd start with just hiding the "Pull" suggested change when a user is in this scenario. We'll evaluate after we ship this whether a suggestion should be more prominent or whether there's something else that makes sense there.

**Comment by tierninho** [comment]
Confirming the when force push is present we are no longer seeing the blank slate action. 

I did spot this:

```
install.ts:31 [AppStore.withAuthenticatingUser] account found for repository: PRlist - tierninho (has token)
install.ts:31 Executing pull: git -c credential.helper= -c protocol.version=2 pull --recurse-submodules --progress origin (took 1.242s)
install.ts:23 `git -c credential.helper= -c protocol.version=2 pull --recurse-submodules --progress origin` exited with an unexpected code: 128.
First, rewinding head to replay your work on top of it...
Applying: Revert "Create bbbbbb"
Applying: #31
Using index info to reconstruct a base tree...
M	.gitignore
Falling back to patching base and 3-way merge...
Auto-merging .gitignore
CONFLICT (content): Merge conflict in .gitignore
Patch failed at 0002 #31

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".


error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch' to see the failed patch

(The error was parsed as 6: We found some conflicts while trying to rebase. Please resolve the conflicts before continuing.)
error @ install.ts:23
install.ts:31 [continueRebase] continuing rebase for 9cf0bf4b07df07c89adfbbab5391678983175c1e
install.ts:31 [continueRebase] completed rebase - got ConflictsEncountered and on tip bfa17d8ca83b3c94f7747454d61b337dd53bedc0 - kind Detached
```

which resulted in me being stuck in the rebase stage with no modal or button to click. The menu was just locked like so: 

![image](https://user-images.githubusercontent.com/14828183/55446159-310f1380-555a-11e9-845f-e4dca691cc74.png)

I do not have repro steps.

8a02833985, mac

**Comment by shiftkey** [comment]
@tierninho it looks like the error occurred when you triggered a pull with rebase enabled - does that seem right?

```
install.ts:23 `git -c credential.helper= -c protocol.version=2 pull --recurse-submodules --progress origin` exited with an unexpected code: 128.
````

This ends up caught in our default error handling, but I'm curious why it didn't end up displaying the rebase flow. I'll see if I can reproduce it myself today and report back.

**Comment by tierninho** [comment]
>  it looks like the error occurred when you triggered a pull with rebase enabled - does that seem right?

Yes, that sounds about right. If I recall correctly, the rebase flow did pop back up, but only after switching repos and returning to the said repo. Not 100%.
