### ISSUE TITLE
Compare Branches feature not working during rebase

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6995]
When you `X` about of a rebase and attempt to compare branches, the feature is not working. It suspect it is intended this way, so we should resolve this one way or another.

Note, in a merge conflict, the compare branch feature is still enabled. 

<img width="848" alt="screen shot 2019-03-01 at 3 19 02 pm" src="https://user-images.githubusercontent.com/14828183/53674984-264d2000-3c36-11e9-9992-994f2a38d76c.png">

v1.6.3-beta3, mac

**Comment by shiftkey** [comment]
For the moment I'm going to close this out as not something worth addressing for a couple of reasons:

 - the side effects of this seem negligible - if someone was able to trigger a merge from some other branch into a branch being rebased I'd be more interested in preventing this
 - I've not heard any other reports of users actively trying this and encountering confusion about trying to use this

If any of these variables changes, I'm happy to revisit this and figure out how to address the problems.
