### ISSUE TITLE
Unable to add local repository

### ISSUE THREAD

**Issue by InfinityGhost** [desktop/desktop#6996]
## Description

I am completely unable to add a local repository on github desktop. The "choose" button doesn't pick the directory, and entering it manually doesn't unlock the "Add repository" button.

## Version

* GitHub Desktop: Version 1.6.2

* Operating system: Microsoft Windows [Version 10.0.17763.316]

## Steps to Reproduce

1. Ctrl+O, File>Add a local repository, etc
2. Click choose button, pick a folder
3. Nothing is set in the textbox
4. Type in a valid directory
5. Add repository button still disabled
### Expected Behavior

Add repository button enabled so I can add my repository, picking folder should set the path textbox
### Actual Behavior

Quite literally nothing

## Additional Information

![githubdesktop_05renceo2y](https://user-images.githubusercontent.com/39218853/53676205-1270e080-3c6d-11e9-96b1-e9eddad05964.png)

### Logs

[2019-03-02.desktop.production.log](https://github.com/desktop/desktop/files/2921682/2019-03-02.desktop.production.log)

**Comment by InfinityGhost** [comment]
To add, this is ONLY an issue on my laptop, so it may be difficult to actually reproduce this issue

![githubdesktop_2019-03-02_21-53-56](https://user-images.githubusercontent.com/39218853/53690298-d8b7dc80-3d35-11e9-889f-45bf85e4f0f8.png)
On my desktop

**Comment by iAmWillShepherd** [comment]
@InfinityGhost, I bummed that you're having these issues. After reviewing your logs, these are the lines that stood out to me:

```sh
2019-03-02T02:36:04.126Z - error: [ui] `git rev-parse --is-bare-repository` exited with an unexpected code: 128.
fatal: Invalid path 'F:/OneDrive': No such file or directory
```

It seems you are trying to open a bare repository in Desktop, which is not supported. We require non-bare git repositories. Could you navigate to that working directory `F:/OneDrive` and run the command `ls -la`? If you see the contents of what typically goes under the `.git` directory in the root of that directory, you are working with a bare repo. 
The last message also makes me suspect that F:\OneDrive isn't a valid directory. Could you paste the out put of navigating to that directory from your command prompt?

**Comment by InfinityGhost** [comment]
Unable to get to my laptop at the moment, but the same repo is on my desktop right now and based on what I see its not a bare repo
![image](https://user-images.githubusercontent.com/39218853/53780235-74318480-3ed1-11e9-9bb0-5c10883f52a3.png)
The issue is persistent throughout EVERY repo on my laptop and the only way I was able to open any repo was to clone it directly from GitHub.

**Comment by iAmWillShepherd** [comment]
> Unable to get to my laptop at the moment, but the same repo is on my desktop right now and based on what I see its not a bare repo

Does the issue with Desktop persist on your desktop PC?

**Comment by InfinityGhost** [comment]
1. Yes, 2. No, 3. Yes, but it has had zero issues in the past

Besides that, it doesn't matter where the repository is because it just flat out wont add **ANY** repository no matter the location unless its from the `Open in Desktop` link on repositories.

One other question, what **program** do I actually run `la -la` on?

**Comment by steveward** [comment]
>One other question, what program do I actually run la -la on?

You will want to run that in Git Bash, which can be downloaded from here:

https://git-scm.com/download/win

@InfinityGhost Is the F:\ drive on your machine a possibly mapped network drive that is syncing with OneDrive? We have seen issues with mapped network drives in the past.

**Comment by tierninho** [comment]
@InfinityGhost As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by anmolagarwal17** [comment]
I'm facing somewhat similar problem. Whenever I add a repo from my desktop, it adds "C:\Users\Anmol Agarwal" only. Anmol Agarwal is my user name.
Is it because github desktop may not have permission to access every file in C: drive?
I have copied that repo to E: drive and everything is working fine there.
What can I do?

**Comment by tierninho** [comment]
@anmolagarwal17 Please open a new issue [here](https://github.com/desktop/desktop/issues/new?template=bug_report.md) so we can triage your issue independently. Thanks.
