### ISSUE TITLE
fatal: Unable to create '.../index.lock': No such file or directory

### ISSUE THREAD

**Issue by JackTimelessPiece** [desktop/desktop#6997]
I tried to commit my changes to the repository and I keep getting this error message. 
"fatal: Unable to create 'E:/Website/Github/Website/.git/index.lock': No such file or directory"
I tried deleting index.lock under .git folder and it still hasn't gone away.

## Version

* GitHub Desktop:

* Operating system:

**Comment by tierninho** [comment]
@JackTimelessPiece Please fill out the template above so we have more info to help the diagnose the issue.

**Comment by tierninho** [comment]
@JackTimelessPiece As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
