### ISSUE TITLE
The LICENSE file is created witout newline at end of file when creating a new repository

### ISSUE THREAD

**Issue by dennisseders** [desktop/desktop#6999]
## Description
When creating a repository with a license the LICENSE file is created without a newline a the end of file. This is indicated by the client when the LICENSE file is opened from the initial commit. It show a red sign with a tool tip containing the text "No newline at end of file".

The way in which the file is created differs from when creating the same repository from the GitHub website as it adds a newline at the end of the LICENSE file.

The creation of new repository, including the LICENSE file, should be processed identically by the GitHub website and GitHub Desktop client. As the GitHub Desktop client indicates with a warning symbol that the newline misses the correct way of processing is implemented within the GitHub website and therefore the GitHub Desktop client should adopt to that.

## Version
* GitHub Desktop:
1.6.2
* Operating system:
Microsoft Windows [Version 10.0.17134.590]

## Steps to Reproduce
1. Select "File" > "New repository" from the top menu
2. Set a value in the text field "Name"
3. Select any value from the drop down "License"
4. Click on the button "Create repository"
5. Click on the tab panel "History" of the new created repository
6. Select the file "LICENSE"

### Expected Behavior
The LICENSE file contains a newline at the end of the file.

### Actual Behavior
The LICENSE file does not contain a newline at the end of the file.

## Additional Information

> Screenshot of GitHub Desktop, after creating the repository including a LICENSE file, through the GitHub Desktop client. 

![github-dekstop-history-license](https://user-images.githubusercontent.com/25513545/53688189-67c9f200-3d40-11e9-829d-0e902fd08fb4.png)

> Screenshot of GitHub Desktop, after creating the repository including a LICENSE file, through the GitHub website. 

![github-dekstop-history-license-2](https://user-images.githubusercontent.com/25513545/53688258-69e08080-3d41-11e9-82ee-7a0b67e862dd.png)

**Comment by iAmWillShepherd** [comment]
I'm making this issue available to the community as it's a relatively straight forward fix. I think appending a newline should be enough to address the issue.

https://github.com/desktop/desktop/blob/76e5460e18d25dc1610ccd866c3e1af93f16e764/app/src/ui/add-repository/licenses.ts#L78

**Comment by shreyagupta995** [comment]
I'd like to work on this issue!

**Comment by jamesgeorge007** [comment]
@shreyagupta995 Are you working on this?

**Comment by jamesgeorge007** [comment]
@iAmWillShepherd @shiftkey Adding a `\n` character to the `tokens` array with `writeLicense()` method fixes the issue :thinking:

**Comment by jamesgeorge007** [comment]
@iAmWillShepherd @shiftkey Adding a `\n` character to the `tokens` array within `writeLicense()` method fixes the issue :thinking:

**Comment by shreyagupta995** [comment]
@jamesgeorge007 I don't think I have enough time in the next few weeks to work on this, so if you'd like you can take over this issue 🙂
