### ISSUE TITLE
"create pull request" always greyed out in new destop version (1.6.2)

### ISSUE THREAD

**Issue by edithf** [desktop/desktop#7003]
## Version

* GitHub Desktop: 1.6.2

* Operating system: Windows 8 version 6.3

## Steps to Reproduce

Step 1: change a file current repository
Step 2: commit to current release
Step 3: click on fetch origin
Step 4: Menu Branch, at the bottom "Create Pull Request" is greyed out, function not accessible.
My work around: use the "Pull Request" on GitHub desktop for WIndows 3.3.6.1

**Comment by edithf** [comment]
*desktop

I have to use my older version of the desktop to send a pull request - am I doing something wrong ? :~

**Comment by tierninho** [comment]
@edithf Please edit the original comment so we have the necessary info to help you resolve the issue. Thanks.

**Comment by shiftkey** [comment]
@edithf thanks for the extra context.

This is the function that controls the `Create Pull Request` menu item:

https://github.com/desktop/desktop/blob/eca095575ca15508debbde73a2f78c021d76ff8c/app/src/lib/menu-update.ts#L242-L245

Can you confirm that the repository is still detected as a GitHub repository? In the repository list it should appear under the **GitHub** header.

**Comment by steveward** [comment]
As we have not heard back from you about this issue we are going to close it out. If you have any more details or information please feel free to comment in this issue. Thanks!

**Comment by edithf** [comment]
Well, I must say I didn't really understand your question - sorry :/  I am not a developer, I am a mere user of your interface and I am wondering why the option to "pull request" is greyed out, I am not doing anything differently from  when I used your older version and "pull request" is readily clearly available from top level and so this is why I still use your older version.  I am not sure what else I could tell you?  Please be gentle with the the heathen! ;)

**Comment by steveward** [comment]
@edithf sure thing, I'm happy to explain further! The `Pull Request` menu option only works for repositories that have been created as a remote repository on GitHub. If you are only using GitHub Desktop for local repositories, or if you are using a third-party service like GitLab or Bitbucket, then the `Pull Request` menu option will be disabled.

When you view the sidebar that shows a list of your repositories you should see your local repositories grouped under your username or organizations that you belong to. This indicates that these repositories exist on GitHub. If there is an `Other` section then those are either local repositories or repositories that are hosted by a third-party. Here's a screenshot for example:

<img width="365" alt="Screen Shot 2019-03-15 at 9 45 41 AM" src="https://user-images.githubusercontent.com/721500/54435635-50f3aa00-4707-11e9-8be1-787a39c57259.png">

The repositories in the `Other` list are ones that I have not yet published up to GitHub.

**Comment by Borgelin** [comment]
Deleted.
