### ISSUE TITLE
Improve workflow for code review

### ISSUE THREAD

**Issue by danpalmer** [desktop/desktop#7004]
On my team we use GitHub for code review. We do this in PRs with the code review tools. Our typical practice to make reviewing easier is to reply to a code review comment with the commit that resolves it. This makes it very quick for the reviewer to click through (as commit hashes are linked) to the commit, and read the solution the PR author wrote.

I use GitHub Desktop locally, but as an _author_, this process is difficult to achieve. As far as I have managed to figure out, my process is roughly:

1. Choose changes to stage (keyboard)
2. Write commit message (keyboard)
3. Commit (keyboard)
4. Hit Cmd+2 to change to History tab. (keyboard)
5. Click the top history entry (mouse)
6. Double click the commit hash in the detail pane (mouse, small hit target)
7. Cmd+C (keyboard)
8. Switch to PR in browser (keyboard)
9. Find comment and focus reply field (mouse)
10. Paste commit hash and submit (keyboard)
11. Switch back to GitHub Desktop (keyboard)
12. Cmd+1 to return to the changes tab (keyboard)
13. Click to focus the changes list (mouse)

This is quite a long process, and there are multiple stages that need me to take my hands off my keyboard. If I have 10 comments to address on a PR, this all takes a while. I used to use Sublime Text with the Sublime Git extension, which makes extensive use of text-based UI with editor navigation control, and with that I had a shorter and more keyboard based workflow.

##### Improved tabbing between controls

I believe steps 5 and 13 above could be achieved with the keyboard, but in these UIs I have found GitHub Desktop to behave closer to a browser where there are a number of unknown focus targets between where you are and where you want to be. The large/variable/unknown number of targets makes it difficult to learn how to navigate quickly with the tab key.

Another thing that makes this difficult is that _Shift+Tab_ is supposed to iterate through tab focus targets in reverse order, but in GitHub Desktop this does not always happen – the "previous" target for a given control changes based on the direction of iteration.

These issues contribute to tabbing being generally not-understandable. I often find myself giving up and using the mouse.

I would recommend a much smaller number of tab targets, and more specialist keyboard shortcuts. For example, there is no need for the Repository selector, Branch selector, or Push/Pull button to be tab targets as these have dedicated keyboard shortcuts. I would also argue that there is no need for the "Select branch to compare" text field to be a tab target, and would be better served by a dedicated shortcut.

##### Copying commit hash

I suspect that this may be a fairly common operation to perform. I think a dedicated global shortcut would be great.

- On the "changes" tab, this shortcut would copy the latest commit on the branch.
- On the "history" tab, this shortcut would copy the commit hash of the selected history entry, or the latest if none is selected.

- - -

Happy to discuss this use-case, or general productivity in GitHub Desktop. I have had a great experience with Sublime Git (the extension, not Sublime Merge the app), and it would be great to bring some of the productivity from that across to GitHub Desktop.

**Comment by iAmWillShepherd** [comment]
@danpalmer thanks for taking the time to create this issue. I'm looping in @desktop/product so they can figure out how we can best address your feedback.

**Comment by billygriffin** [comment]
Hi @danpalmer, thanks so much for this issue, it's interesting to see how you're using it as part of your code review process. Any chance you'd mind doing a ~30 min video call to show this to us in action and help us understand things a bit better? If so, please fill out this form and I'll be in touch. https://goo.gl/forms/7rLqPVeJE8oTNB9o1

**Comment by danpalmer** [comment]
@billygriffin of course! Will be in touch.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by steveward** [comment]
I'm going to close this out as stale as the app has changed from quite a lot from an accessibility standpoint since this issue was created. @danpalmer if you still have similar feedback we can revisit this again.
