### ISSUE TITLE
restrict checkbox state when dealing with rebase conflicts

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#7006]
This was raised by @tierninho in https://github.com/desktop/desktop/pull/6984#issuecomment-468805303:

> if you navigate to the Changes tab and uncheck the changes, the Continue rebase button is still active. I expect to be be disabled until the user checks the changed file(s).

![](https://user-images.githubusercontent.com/14828183/53665275-0bb38080-3c0f-11e9-9471-8ee61f1d2b22.png)

While the "Continue rebase" state is valid feedback here, the underlying issue is that users can uncheck files that need to be handled as part of resolving conflicts. This doesn't actually affect the rebase (or merge) action, which is applied to all tracked files and ignores the checkbox status.

What I'd like to do to tighten up this behaviour is to lock down the checkbox behaviour:

 - for each tracked file, mark the file as **checked**, disable the checkbox and add a helpful tooltip
 - for each untracked file, mark the file as **unchecked** by default, leave the checkbox enabled (so the user can add the file to the rebase if they want?) and add a helpful tooltip

**Comment by tierninho** [comment]
Additionally, if all items are left unchecked, the rebase button should be disabled (if we goes this route). 

Clicking the button results in an error message: 

![image](https://user-images.githubusercontent.com/14828183/53771371-699dcd80-3e86-11e9-9229-756e09fbbabf.png)

tested 76d48b925f, mac

**Comment by shiftkey** [comment]
> Additionally, if all items are left unchecked, the rebase button should be disabled (if we goes this route).

There's a rebase state where the changes in a commit from the target branch already exist in the base branch, and so Desktop will need to drop the current commit from the rebase operation (with a `git rebase --skip`). I fear this means there'll be a situation where there are no files in the changes list shown to the user, but we'll need to enable the button to continue on nonetheless.

This will be a test case I'll keep an eye out for while working through this.
