### ISSUE TITLE
Hide Merge Tool button during rebase

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7011]
The `Merge Tool` button is exposed and clickable when a rebase is in-progress. It should be hidden even though it doesn't really do much except record a log entry like so:

`debug: [ui] Executing openMergeTool: git mergetool 2-simple-rebase-conflict/LICENSE.md`

![image](https://user-images.githubusercontent.com/14828183/53771102-74a42e00-3e85-11e9-8ebe-493cd93cf385.png)

tested: 76d48b925f, mac

**Comment by shiftkey** [comment]
@tierninho some extra context on this:

 - this is feature flagged and only visible in `development` currently, so I'm not hugely worried about it appearing as part of rebase, unless it's visible on `beta`
 - this was added in #2804 but I think the reason why we've not graduated it to `beta` or `production` is that we've not properly figured out how to detect when you have a merge tool configured, which would explain why it doesn't do anything in your case

**Comment by shiftkey** [comment]
Moving into `user-research` to identify whether we want to dig further into this in the near term.

**Comment by billygriffin** [comment]
I'm going to close this to avoid confusion since we haven't decided the disposition of it and it seems relatively low priority.
