### ISSUE TITLE
Update Rebasing terms and UI

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7012]
Rebasing is currently using two prepositions, `on` and `onto` in the UI. I suggest we use `onto` as it is more descriptive in how a rebase looks visually. (We also use `into` when doing merge conflicts).

Three places were on/onto is used... 
- a mention is in the success message banner
- and remaining two are here:
<img width="453" alt="screen shot 2019-03-04 at 3 54 50 pm" src="https://user-images.githubusercontent.com/14828183/53775463-c43f2580-3e96-11e9-9a12-a5de8ef41ec1.png">

Lastly, we should fix the spacing of the spinning icon and the text in the button:
<img width="392" alt="screen shot 2019-03-04 at 3 56 29 pm" src="https://user-images.githubusercontent.com/14828183/53775464-c43f2580-3e96-11e9-8abe-e63d299ca061.png">

76d48b925f, mac

**Comment by shiftkey** [comment]
> Three places were on/onto is used...
>
> - a mention is in the success message banner
> - and remaining two are here:

I believe all of these should be `onto` and so I've pushed c7bdb2c73 onto #6961.

> Lastly, we should fix the spacing of the spinning icon and the text in the button:

This was updated in 8cee19e052de7243e7a5352aeb68797b4eead6a6 which is part of #6981 that isn't quite ready for review, but the plan is to drop this in the future for a proper progress bar - #6962 is tracking that change.
