### ISSUE TITLE
confirmation dialog shows no visual feedback when performing an action

### ISSUE THREAD

**Issue by njbmartin** [desktop/desktop#7015]
**Please describe the problem you think should be solved**

When discarding all changes for many files, clicking on discarding all changes will begin performing the action, but there is no visual indication it's actually doing anything until the operation is complete. The button simply doesn't appear to do anything, so it's likely the user will press cancel. In the background though, the operation is still working away...

![image](https://user-images.githubusercontent.com/5699471/53872635-8bb65d80-3ff6-11e9-8eea-147a7dcb7df2.png)

Not specific to dark mode:
![image](https://user-images.githubusercontent.com/5699471/53873579-8e19b700-3ff8-11e9-817f-a572c54eabbb.png)

This is also the case when removing a large repository and moving it to the recycle bin.

![image](https://user-images.githubusercontent.com/5699471/53873162-a5a47000-3ff7-11e9-850c-7198bd0b6629.png)

**Comment by billygriffin** [comment]
Thanks for the issue @njbmartin! We totally agree we can do a better job of indicating that something is happening here, and this issue was brought up separately by @varkor. We're discussing potential design patterns we could use here and evaluating how to hook into the process, so just wanted to say thanks and update you that we're looking at this.

**Comment by tierninho** [comment]
@njbmartin Thanks for filing. 

I imagine something like this embedded within button would suffice. We will look into it and circle back soon.

![image](https://user-images.githubusercontent.com/14828183/53922541-e660b100-4018-11e9-9a13-26f10c7d3e0c.png)

**Comment by donokuda** [comment]
I did a little sleuthing in the Discard Changes codes and it looks like have a state that indicates we're in the middle of discarding files:

https://github.com/desktop/desktop/blob/bca8e0f1db767713575fdf01374e7600c374a5e4/app/src/ui/discard-changes/discard-changes-dialog.tsx#L32-L36

However, we don't currently use this to show the spinner (despite what the comment above implies 😄):

https://github.com/desktop/desktop/blob/bca8e0f1db767713575fdf01374e7600c374a5e4/app/src/ui/discard-changes/discard-changes-dialog.tsx#L65-L74

I think if we pass the `loading` property to the discard changes dialog with the `isDiscardingChanges` state, we should be able to get a happy little spinner rendered:

<img src="https://user-images.githubusercontent.com/1174461/53923723-0b135380-402e-11e9-8291-58182c0325aa.png" alt="a happy little spinner" width="400" />

An example where this is implemented is the "Create a New Repository" modal:
https://github.com/desktop/desktop/blob/bca8e0f1db767713575fdf01374e7600c374a5e4/app/src/ui/add-repository/create-repository.tsx#L511

Can someone on @desktop/core or @desktop/comrades validate my assumption? If my hunch is correct, then I think this is ready for the community to pick up 😄

**Comment by varkor** [comment]
It would also be good to give the "Discard all changes" button an obviously-disabled appearance (this probably just involves actually disabling the element), rather than simply focusing the button.

**Comment by billygriffin** [comment]
Just spoke with @niik and he said while it might be a little tricky due to the synchronous nature of the method involved, the pattern @donokuda shared above is correct. I'm going to add `help wanted` here for someone to pick up since @donokuda laid out a pretty nice description of the relevant areas.

**Comment by njbmartin** [comment]
Just wanted to add some feedback now I've used the beta on Windows 10. Let me know if I should raise a new issue...

Removing a repository and selecting "Move to Recycle Bin", it still _hangs_ with no visual feedback.

![image](https://user-images.githubusercontent.com/5699471/56624852-8955a480-6632-11e9-947b-781988765945.png)

Once it's actually moved to recycle bin, you see a brief flash of the spinner and then it's gone. I'm guessing this might be because `shell.moveitemtotrash()` is a synchronous blocking call, and the method to show the spinner comes after?

**Comment by tierninho** [comment]
@njbmartin Many thanks for bringing this to our attention and appreciate the details.

I am curious how long it hangs for you? I just tested it and it seems responsive and reacting as designed. The spinner was initiated briefly as you described and removing the repository was completed shortly thereafter. 

Were you experiencing something different or did you expect something more expedited? A gif is helpful, but optional. Also, what version of Desktop and what version of DOS are you using?

<img width="473" alt="Screen Shot 2019-04-23 at 3 17 10 PM" src="https://user-images.githubusercontent.com/14828183/56626045-c8a4d680-65db-11e9-8fbd-5de8c8b1d9ff.png">

**Comment by njbmartin** [comment]
Desktop: 1.7.0-beta4

What I tried to describe was it hanging after pressing remove. Instead of showing the spinner, it does nothing. Once the operation is actually complete, you then see the spinner very briefly while it completes the cleanup.

![TyyZRnTjDv](https://user-images.githubusercontent.com/5699471/56627024-16512b80-663c-11e9-90b8-25c2d7be2488.gif)

**Comment by njbmartin** [comment]
This may explain why... moving to recycle bin in Explorer shows it "discovering" what files to remove before actually removing them. Can't remember the last time I used explorer to remove files...

![WxLvQDsBUt](https://user-images.githubusercontent.com/5699471/56627749-07b84380-663f-11e9-88e4-ddef3f0b4666.gif)

**Comment by tierninho** [comment]
Ah, gotcha. Thanks for the gifs, it helps to see exactly what is happening.

@desktop/core any thoughts on backend processes that might affect this? Looks like the total repo size was 390 MB.
