### ISSUE TITLE
audit menu items to determine which should be enabled when dealing with conflicts

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#7017]
**Please describe the problem you think should be solved**

@tierninho has raised some excellent feedback about how menu items are enabled/disabled as part of addressing rebase conflicts:

> If a merge conflict is in progress and is currently in manual resolution mode (banner present), then the Rebase current branch menu option should not be enabled as it results in an error message:
>
> https://github.com/desktop/desktop/pull/6961#issuecomment-469857751

> the `Push` menu item is still active in the Repo menu, which triggers a console error:
`Uncaught (in promise) Error: The current repository is in a detached HEAD state`
>
> https://github.com/desktop/desktop/pull/6984

> if rebase in progress, then New Branch menu option should be disabled as well to avoid confusion and error:
>
> https://github.com/desktop/desktop/pull/6994

**[Optional] Do you have any potential solutions in mind?**

Not currently. I'd have probably thought more about it if we'd heard external feedback about this issue, but I think this just requires sitting down and reviewing the menu options and proposing better rules and the rationale behind them.

**Comment by tierninho** [comment]
Additionally, we should consider disabling the right-click `Revert This commit` option in the History list as it will always lead to a failure. This applies to both rebasing and merge conflicts.

```
`git -c credential.helper= -c protocol.version=2 revert 4bf6400a45a45f1ed3eb6e0d805e317e389155ab` exited with an unexpected code: 128.
error: Reverting is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: revert failed
```
![image](https://user-images.githubusercontent.com/14828183/54053672-1da39f00-418c-11e9-9272-f6365f3ff472.png)

**Comment by tidy-dev** [comment]
Closing as stale and no user reports of running into issues about with this. Not saying that looking into this may result in a PR to improve it, but it has not proven to be a pain point.
