### ISSUE TITLE
Clone repo list blocked by api 500

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7019]
When loading my cloned repo list, it sometimes reverts to the "cannot find" state due to a 502 in the api GET. 

Cannot reproduce at will, but it happens frequently enough. Not a blocker as it can be resolved by `cmd-R` in the dev console. Refreshing the list does not resolve the issue.

<img width="431" alt="screen shot 2019-03-06 at 7 37 08 am" src="https://user-images.githubusercontent.com/14828183/53904910-42acdc00-3feb-11e9-8dac-894099929a6b.png">

 `http.ts:135 GET https://api.github.com/user/repos?per_page=100&page=19 502 (Bad Gateway)`
`fetchRepositories: Error: Server Error`

v1.6.3, mac

**Comment by shiftkey** [comment]
This should be addressed by #7259 and available in the next update - if we encounter a network issue while fetching repositories, we return everything we've been able to paginate.
