### ISSUE TITLE
List of external editors doesn't update

### ISSUE THREAD

**Issue by gfs** [desktop/desktop#7024]
**Scenario**: I am setting up all my tools on a new system. 

**Story**: I first install GitHub Desktop. I then realized I needed to install Visual Studio Code to use as an external editor.  I completed that installation while GitHub Desktop remained open. 

**Expected Behavior**: Once Visual Studio Code has been installed, when I navigate to the settings menu to select an external editor it should be available.

**Actual Behavior**: The list of editors did not update to include Visual Studio Code until I restarted GitHub Desktop. Including opening the settings menu after the installation of Visual Studio Code.

Extra Tidbit: I did have Sublime Text installed, and it was populated in the list, before and after the installation.

**Comment by shiftkey** [comment]
@gfs thanks for the feedback! I'm going to fold this into #6114 which is an earlier discussion about this.

**Comment by goyalyashpal** [comment]
hi, coming here from the #7033
i am facing the similar issue: https://github.com/VSCodium/vscodium/issues/907
