### ISSUE TITLE
problem when use the desktop github app

### ISSUE THREAD

**Issue by sslow** [desktop/desktop#7026]
## Description

hey team, i am showlly. now i meet a problem when use the desktop github app. i sign in as a account  sslow. but when i select one project and click the button view on github on browser. the link refer to my old account name catFishTail. eg: https://github.com/catFishTail/vueJump. and which lead to the page 404. please help me to figure out it. thanks.

## Version

* GitHub Desktop:

* Operating system:

**Comment by steveward** [comment]
Thanks for contributing @sslow. When you log in with a different account in GitHub Desktop it will not change anything with your local repositories -- they will still point to the same remote repository on GitHub. If you would like to transfer that repository to a different account you can find our guide for how to do that on GitHub:

https://help.github.com/en/articles/transferring-a-repository

Let me know if you have any questions about this.

**Comment by sslow** [comment]
thank you. 发自我的华为手机-------- 原始邮件 --------主题：Re: [desktop/desktop] problem when use the desktop github app (#7026)发件人：Steve Ward 收件人：desktop/desktop 抄送：sslow ,Mention Thanks for contributing @sslow. When you log in with a different account in GitHub Desktop it will not change anything with your local repositories -- they will still point to the same remote repository on GitHub. If you would like to transfer that repository to a different account you can find our guide for how to do that on GitHub:
https://help.github.com/en/articles/transferring-a-repository
Let me know if you have any questions about this.
