### ISSUE TITLE
Desktop doesn't cleanly integrate with my editor (user feedback desired)

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#7033]
**Please describe the problem you think should be solved**
This is an exploratory issue trying to understand the problem a bit better.

If a GitHub Desktop user doesn't use [one of the editors Desktop detects](https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md), many of the workflows in the app aren't nearly as clean. This used to be less of an issue as we didn't closely tie very many workflows in Desktop to a user's editor, but as we've learned from our users in many cases a tighter relationship between the two tools makes for a much more streamlined workflow.

There are a few issues where this has manifested:
Selected editor doesn't save when a previously selected editor is uninstalled: #7463 
Manual editor setup/detection in preferences #6114 
Merge conflicts flow when no editor is detected #6386 
Different versions of Atom aren't properly detected #6324 
After installing an editor (VS Code), Desktop didn't immediately detect it #7024 
Desire for custom defined editor integration #4465 and #5083

We also know that a few of the most widely used editors including Visual Studio and [XCode](https://github.com/desktop/desktop/issues/4825) are not detected by Desktop. The reason comes down to the inability of many of the editors we don't support to open a directory in the editor (see https://github.com/desktop/desktop/pull/2039 for example, where we made the decision not to support Visual Studio because it wasn't very clean to where we'd direct the user). 

**Impact**

This started out as a convenience to be able to quickly open any file in your editor as you're looking at the diff in Desktop, but the merge conflict resolution process expanded this, and with rebasing and stashing soon to be a part of the product and both having the potential to also introduce conflicts, this will likely be increasingly affecting more and more users.

From our metrics, we've learned that more than 25% of users have no editor detected currently, which is much larger than I expected.

It's unclear to me given the huge % of people that don't have an editor detected by Desktop *why* we haven't heard about this as a larger pain point. If you have thoughts about that, I'd be super interested to hear more.

**Potential next steps**

There seem to be two areas of potential focus:
1. Improving the "no editor detected" experience to either onramp folks to editors that we do detect, or more likely improve the usability of the app in cases where they use an editor we don't detect (for example: #6386).
2. Broaden the scope of editors that are detected. If we're going to improve this process, it seems like we need to do the work up front to segregate the editors that are able to open a directory from those that are not, and have a reasonable design in place for how the handoff interactions will work when the user's primary editor is unable to open a directory.

My inclination is that we probably need to do both of these things, but for this issue my focus is more on (2) and supporting a broader set of users using various editors.

**Questions (we'd love answers from you!)**

If you're someone who doesn't have one of Desktop's detected editors as your primary editor and you therefore don't have a tight integration:
- What editor do you use most regularly?
- How does the lack of tight integration of Desktop with your editor affect you? How painful is it? How frequent?

For anyone:
- For editors that cannot open a directory (Visual Studio XCode, Android Studio, etc.), what would your expectation be if you right click on a file in your changed files and click "Open in [editor]"? How would you expect that to work? Would you be frustrated if it *only* opened the file without the context of the folder structure (I'm not sure if that's how it would work because I haven't tested this yet)?

**Comment by Bibliofile** [comment]
How convenient, I just ran into this enough times today to check to see what was being done about it. Generally, I only run into this 1-2 times per day.

My primary editor is VSCode, but I also use Vim and Notepad++ regularly, and sometimes exclusively depending on the project.

Since neither Vim nor Notepad++ are detected as an editor, I generally use CTRL+Shift+F to open the folder in Explorer and then open a file manually. (Or, if I'm after a single file, I will right click and open that file in Explorer)

What I came looking for was actually the ability to specify a custom script to be launched as an "editor" which I could then use to open the editor of my choice. The setup in #5083 is exactly what I'm after.

**Comment by shiftkey** [comment]
Moving this to `user-research` because that label feels more fitting for what we're looking for currently...

**Comment by zdog234** [comment]
I've finally gotten vscode to [run in wsl ubuntu](https://gist.github.com/mkol5222/7569bf2b508169a20c103a12de014233), and the only thing that's currently missing from my workflow is the ability to specify `wsl code .` as my external editor command. I wouldn't expect that to be detectable by github, but it would be awesome if there were a way for me to manually configure that.

Thanks a ton! Excited to hear about the new stuff coming down the pipes :)

**Comment by matthewbegun** [comment]
Desktop has never been able to find any of my editors. Which I believe is because they are all installed in my home directory (on windows 10) rather than in the registry.

I use a package manager to install them (scoop - incidentally that's how I install Desktop as well).

Desktop is not typically part of my workflow, I only use it for convenience features for certain tasks. If I need to get to my editor from within Desktop I use the terminal command to get to powershell and then `code .` or `rider .` to get to my text editor.

**Comment by Gakk** [comment]
The urge for detecting Visual Studio lead me to this issue, and to answer the initial questions:

**What editor do you use most regularly?**
Visual Studio 2019 _(alongside Visual Studio Code and Notepad++)_

**How does the lack of tight integration of Desktop with your editor affect you?**
It is not painful, but after cloning a repository in Desktop it would have been great to right click and select "Open in Visual Studio 2019". I would use this about 2-3 times per week. Currently an option to open in Visual Studio Code is available.

**For editors that cannot open a directory, what would your expectation be if you right click on a file in your changed files and click "Open in [editor]"?**
Usually I have both GitHub Desktop and Visual Studio open at the same time. If Visual Studio already is open with the same repository as Desktop, then the file could be opened directly if possible. If Visual Studio was closed or open with another repository I believe the option to open in Visual Studio should be disabled. I don't see the need to open a single file in Visual Studio if I'm not already working on the repository. With that said, I understand this probably would be a bit too much special handling for one editor.

What I was looking for was adding "Open in Visual Studio" as an option when right clicking a _repository_ in Desktop. I would then expect to open the solution file in a new Visual Studio instance. To support multiple solutions files in an repository, it could be solved by showing a context menu for each found solution, eg. "_Open 'MyProject.sln' in Visual Studio_" and "_Open 'OtherProject.sln' in Visual Studio_".

**Comment by steveward** [comment]
From #13309:

>I use normally VSCode portable. So nothing is set under HKLM...\uninstall and Github Desktop does not detect my VSCode.
BTW: I've no admin credential the add something to HKLM...\uninstall.
So please let the user select where an editor is installed.

**Comment by hl2guide** [comment]
A simple "browse" button in the **Options > Integrations** menu for this would be wonderful.

**Comment by sergiou87** [comment]
Closing this since the changes from https://github.com/desktop/desktop/pull/18954 are available in the latest beta https://desktop.github.com/beta
