### ISSUE TITLE
connection refused while cloning

### ISSUE THREAD

**Issue by HasanLisbon** [desktop/desktop#7034]
## Version

* GitHub Desktop:

* Operating system:

### Expected Behavior

I wanted to clone a file from github
### Actual Behavior

it showed error message saying connection failed with localhost 8888 or something
[2019-03-08.desktop.production.log](https://github.com/desktop/desktop/files/2943985/2019-03-08.desktop.production.log)

**Comment by tierninho** [comment]
@HasanLisbon based on the error output it looks like you are behind a proxy or firewall that is blocking the connection to GitHub. Is that a possibility? 

If you are behind a proxy that requires credentials there are some steps you can take to configure it:

1. Go to the file menu in GitHub Desktop and select `Repository` > `Open in <command line>` 
2. Run the following command:

`git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`

Replace `proxyuser` with your proxy username and `proxypwd` with your proxy password. Also, `proxy.server.com:8080` needs to point to the URL of your proxy server. Let us know if that does not get things working for you.

**Comment by billygriffin** [comment]
@HasanLisbon Hope @tierninho's guidance above was helpful, and since we haven't heard back from you, we're going to close out this issue. Thanks!
