### ISSUE TITLE
Differentiating local and remote branches

### ISSUE THREAD

**Issue by RoukePouw** [desktop/desktop#7044]
**Enhancement request**
When viewing the branch dropdown I would very much like to see which branches exists only local and which also remote. 

This for example to facilitate clean up of merged local branches, or publishing of a branch that I forgot to publish.

**Suggestions**
A different icon, color, and/or text decoration for the local branches in the dropdown.

**Comment by tierninho** [comment]
@RoukePouw Many thanks for the feedback. Note, this is a duplicate of https://github.com/desktop/desktop/issues/5330 so please follow along there. ❇️
