### ISSUE TITLE
change persian fonts

### ISSUE THREAD

**Issue by metrocoding** [desktop/desktop#7048]
Persian or Farsi or Arabic font is bad on your desktop app
in description of changes before commit add rtl support

**Comment by shiftkey** [comment]
@metrocoding are you able to provide screenshots or more details to help us understand how you are using the app?

**Comment by tierninho** [comment]
@metrocoding As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
