### ISSUE TITLE
after closing desktop during update, desktop cannot be reopened

### ISSUE THREAD

**Issue by msftrncs** [desktop/desktop#7055]
Suddenly my install of Desktop wouldn't open.  It had only been a couple days since I last had it open for just a quick moment.

Checking things, there was something wrong with the .EXE file, but I was able to use one of the backup versions (1.6.3 beta 3) to reupdate.

Looking in my squirrelSetup.log, on 3-08-2019 the log abruptly ended.

```
2019-03-08 23:19:10> DeltaPackageBuilder: lib\net45\resources\app\static\gitignore\Global\Tags.gitignore.diff exists unchanged, skipping
2019-03-08 23:19:10> DeltaPac
2019-03-10 21:12:05> Program: Starting Squirrel Updater: --checkForUpdate https://central.github.com/api/deployments/desktop/desktop/latest?version=1.6.3-beta3&env=beta
2019-03-10 21:12:05> Program: Fetching update information, downloading from https://central.github.com/api/deployments/desktop/desktop/latest?version=1.6.3-beta3&env=beta
2019-03-10 21:12:05> CheckForUpdateImpl: Using existing staging user ID: 9d06e06a-0140-5f85-877a-4997d48d69fd
```

I am guessing the updater was terminated by me closing Desktop.  I have observed this on other machines that were quite old and had a long update list to get Desktop up to date, closing down stopped the 'updater' task and then reopening Desktop would restart the whole update process all over again (from the beginning).

I don't think the update process should be killed upon closing of the Desktop application.

Looking back at the logs it appears this had gone on the previous couple times I had opened Desktop.  Looks like I had 1.6.3 beta 3 on 03-06-2019 and it was first trying to apply beta 4, and also had failed then, probably because it was closed.

OS: Windows 10 (19H1 18353)

**Comment by shiftkey** [comment]
@msftrncs thanks for the report!

> ```
> 2019-03-10 21:12:05> CheckForUpdateImpl: Using existing staging user ID: 9d06e06a-0140-5f85-877a-4997d48d69fd
> ```

This message is very early in the update process - there should be messages after this to indicate whether or not updates were found, which then need to be downloaded and applied. 

Here's one from a test environment of mine:

> ```
>2019-03-06 13:29:53> CheckForUpdateImpl: Using existing staging user ID: 9eaf1a1e-21cc-5ad0-aee0-a1a779f33362
> 2019-03-06 13:29:53> CheckForUpdateImpl: Downloading RELEASES file from https://central.github.com/api/deployments/desktop/desktop/latest?version=1.6.2&env=production
> 2019-03-06 13:29:53> FileDownloader: Downloading url: https://central.github.com/api/deployments/desktop/desktop/latest/RELEASES?version=1.6.2&env=production&id=GitHubDesktop&localVersion=1.6.2&arch=amd64
> 2019-03-06 13:29:53> FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-1.6.3-delta.nupkg
> 2019-03-06 13:30:17> DeltaPackageBuilder: Applying MSDiff to lib\net45\api-ms-win-core-console-l1-1-0.dll.diff
> ...
> ```

And the end result of the update is managed by `ApplyReleases`:

> ```
> 2019-03-06 13:31:05> ApplyReleasesImpl: Writing files to app directory: C:\Users\shiftkey\AppData\Local\GitHubDesktop\app-1.6.3
> 2019-03-06 13:31:07> LogHost: Rigging execution stub for lib/net45/GitHubDesktop_ExecutionStub.exe to C:\Users\shiftkey\AppData\Local\GitHubDesktop\GitHubDesktop.exe
> 2019-03-06 13:31:10> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\shiftkey\AppData\Local\GitHubDesktop\app-1.6.3\GitHubDesktop.exe]
> 2019-03-06 13:31:13> ApplyReleasesImpl: Starting fixPinnedExecutables
> 2019-03-06 13:31:13> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
> 2019-03-06 13:31:13> ApplyReleasesImpl: Fixing up tray icons
> 2019-03-06 13:31:13> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
> 2019-03-06 13:31:13> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
> 2019-03-06 13:31:13> ApplyReleasesImpl: cleanDeadVersions: for version 1.6.3
> 2019-03-06 13:31:13> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.6.2
> 2019-03-06 13:31:13> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.6.3
> ```

> Checking things, there was something wrong with the .EXE file

Are you able to remember what was wrong here? Ideally the application shouldn't be updated until all the upgrades are ready to be applied, and the last part about moving around shortcuts to point to the new app should be fairly fast.

> I don't think the update process should be killed upon closing of the Desktop application.

The important thing I want to call out here is the Electron runtime manages the update process here, and the app interacts with the updater through the [`autoUpdater`](https://electronjs.org/docs/api/auto-updater) API, so I'm not sure how much control we have over the internals of this to prevent updates being terminated when the app is closed.

For reference, here's the typical updater flow:

 - app invokes `autoUpdater.checkForUpdates()` 
 - `autoUpdater` emits `'update-available'` event, downloads files automatically and prepares update
 - `autoUpdater` emits `'update-downloaded'` to indicate updates are downloaded and applied 
 - user closes app (updates should be applied on next launch) OR user wants to restart (app invokes `autoUpdater.quitAndInstall()` and applies update)

I believe, if the app is closed before `'update-downloaded'` is emitted, Squirrel should just restart from `CheckForUpdateImpl` on the next launch (which I think you point out above).

**Comment by msftrncs** [comment]
Regarding the EXE file, I was trying to click on the desktop shortcut, but nothing would happen, so I went to the install folder and noticed the icon was missing from the file in the root of the install where normally you can start the latest release so I went to the specifically latest release, and it said the EXE file was not a valid windows program.

The log except I show above is just an except of the failure on 3/8.  The last lines are from a successful update on 3/10 when I resolved the issue.  Notice the last line on 3-8 ends abruptly.   I have observed Squirrel Updater in the past and know that it writes to the log file in big buffer chunks, so its very likely that if the process is aborted, the buffer won't be flushed and you end up with a cut up log file. 

I am also not surprised if this is more of an upstream issue.  Its just that this is the 3rd time an update failure has occurred to me, and I have seen the reports here that it has failed for others as well.

A couple thoughts:
- if there isn't many reports to Electron/Squirrel that the update process isn't awlays working, maybe not a lot of apps are using Electron's default update process.  I know VS Code does not.
- Also, maybe there is an Electron best practice that is not being honored by Desktop.

I would have expected that the update process wouldn't be so fallible, but after my experiences, I am sure there is something wrong somewhere.  This is why I think there is something going wrong at close of Desktop.

I am going to hypothesize another thought:
- Squirrel is almost done updating
- User requests app to close
- Event to close is mixed with event that update is ready to apply
- Event to apply update is sent, and that starts,
- Event to close is sent
- Updater is killed after it starts event process to finalize update.

I can say this because I have witnessed Electron scrambling events, probably because of things like continueing to process event requests even after a close is triggered.

It might really help if Squirrel would flush its log buffer when it is aborted, so we could get a better look at what exactly it was doing when it closed.  This should include a reason for the closing.

**Comment by shiftkey** [comment]
Moving this to `investigation-needed` to see if one of @desktop/engineering is available to dig into the updater behaviour at all.

**Comment by JontyMC** [comment]
Sounds like https://github.com/Squirrel/Squirrel.Windows/issues/1327
