### ISSUE TITLE
Bump Dugite to version 1.86.0

### ISSUE THREAD

**Issue by Daniel-McCarthy** [desktop/desktop#7057]
This issue suggests to bump Dugite to version 1.86.0. This is in order to get the benefits of the changes in [Dugite #308](https://github.com/desktop/dugite/pull/308) that allow the clone connection error to be correctly detected as `DugiteError.HostDown` and display the correct error description. This would be useful for Issue #926 for testing the retry dialog.

However, in order to bump Dugite to version 1.86.0, a change is required. A description needs to be added for `DugiteError.UnresolvedConflicts` in the `getDescriptionForError` function in `src/lib/git/core.ts`.

Without this change, after bumping Dugite and building, and error will occur. `ERROR in [at-loader] ./app/src/lib/git/core.ts:272:26 TS2345: Argument of type 'GitError.UnresolvedConflicts' is not assignable to parameter of type 'never'.`

**Comment by shiftkey** [comment]
@Daniel-McCarthy in the meantime feel free to upgrade the package in your branch to ensure your feature work isn't blocked. If we haven't addressed this by the time it's ready to review, feel free to link to this issue in your PR as a blocker.
