### ISSUE TITLE
Issue with Desktop while cloning or creating a repo

### ISSUE THREAD

**Issue by sylvain-d** [desktop/desktop#7064]
Hello

I tried to use GitHub desktop instead of basis GitBash but was unable to clone a repo from github or to create a new one from my hard drive.
Got the following error (screenshot)
![image](https://user-images.githubusercontent.com/490466/54156103-cdeffc80-4445-11e9-892f-ca87518a46e2.png)

Reading the message I may suspect that my computer username on W10 doesn't please GitHub desktop.
it's "S&C", seems that the '&' raise a bug while executing, the path isn't recognized.

Thanks

Sylvain

**Comment by billygriffin** [comment]
Thanks for the issue @sylvain-d! We've recently seen this in other issues as well, most notably in https://github.com/desktop/desktop/issues/6879#issuecomment-471042891

I'm curious if the fix they shared might be related to what's causing your issue? If not, would you mind sharing your OS version and Desktop version?

**Comment by sylvain-d** [comment]
Hi @billygriffin , I looked in my Registry and have no Autorun Key register anywhere (HKEY_LOCAL_MACHINE or HKEY_CURRENT_USER
I tried to add a new key Autorun with value "CD /d C:\" or "CD C:\". Even if my path change while running "cmd" command, GHD is still poping the same error message.
I run W10 Familly edition and GHD is 1.6.3

**Comment by billygriffin** [comment]
@sylvain-d Sorry about that. I'm going to have to ask for a hand from @desktop/support as that's about as far as my knowledge goes on this one.

**Comment by shiftkey** [comment]
@sylvain-d @billygriffin I bet the `&` in the account name is the issue

**Comment by sylvain-d** [comment]
@shiftkey I thought about it in first place. I 'll try to create a new windows account and install GHD to validate it.

**Comment by sylvain-d** [comment]
Hi. I just tried with a new User, without any special character, works like a charm.
I confirm that '&' is not handle by GithubDesktop in username, it disrupts the path.

I change my username but W10 doesn't change the folder name.

Will special character in username be handle in a future version ?

**Comment by steveward** [comment]
@sylvain-d I'm glad to hear that got things working! 

> Will special character in username be handle in a future version ?

This is an issue that we are aware of and will continue to be investigating a better fix for. I'm going to close this issue out, but please let us know if you have any further questions.

**Comment by sylvain-d** [comment]
@steveward OK, I'll look forward to the fix ;)
