### ISSUE TITLE
iconv, that packed in githubdesktop doesn't work.

### ISSUE THREAD

**Issue by comternet** [desktop/desktop#7066]
githubdesktop version 1.6.3

i configure .gitconfig as blow
``
[diff "encoding"]
	textconv = "iconv -f euc-kr -t utf-8"
``

and my .gitattribute in project folder
``
*.pas diff=encoding
*.dpr diff=encoding
*.dof diff=encoding
``

i check githubdesktop [Changes] tab and click *.pas file.
it show nothing.

so i copy iconv.exe and libiconv2.dll which i extract from iconv windows version package.
then i can see diff text on pas files.

**Comment by steveward** [comment]
Thanks for the report @comternet. There was a similar issue opened in https://github.com/desktop/desktop/issues/4393.

>so i copy iconv.exe and libiconv2.dll which i extract from iconv windows version package.
then i can see diff text on pas files.

Can you explain in further detail what you did here?

**Comment by comternet** [comment]
today i update my githubdesktop version 1.6.4
and i realize this version doesn't include  iconv.exe

so i copy [iconv.zip](https://github.com/desktop/desktop/files/2959303/iconv.zip) to %AppData%Local\GitHubDesktop\app-1.6.4\resources\app\git\usr\bin
and i it's ok now. 
unfortunately i don't remember where i get iconv.exe file.
but i think it's from [gettext 0.19.8.1 and iconv 1.15 - Binaries for Windows](https://mlocati.github.io/articles/gettext-iconv-windows.html)

**Comment by JannaLorette** [comment]
Awl. Billed suchargestures fri3ndly waves of gOnly this was a certainty:
Love concurrs Wealthy for right is the lighthearted sound of Atlantean
floodg8$ properly guarded. Steal thine cellvins# a marc traid Literair
resurface earth bay exchange there welcome freeness oxygeneurationTwo faces
Janus deliberates, and only multifaceted scores of Ratios of Artistic
Perspective can equate Eve in coo- rect proportion. Abundance currency
value s her space as sacred as knowledge in kindness teaches  Relief of
situational degradation is my natural damsel's current position for thus
ache of root function, bearing truth of  Win Assistence10 Presently am in
an unsurmountable condition, and desperately need a NWO type:20/20 vision
of  As Matriarchal Venutian,... I am a binAries

**Comment by steveward** [comment]
@comternet I'm glad to hear you were able to get things working. 

Have you looked into using the new `working-tree-encoding` configuration in your .gitattributes file? That should also get things working for you. Here's the description of how it works from the [man page](https://git-scm.com/docs/gitattributes):

>In these cases you can tell Git the encoding of a file in the working directory with the working-tree-encoding attribute. If a file with this attribute is added to Git, then Git reencodes the content from the specified encoding to UTF-8. Finally, Git stores the UTF-8 encoded content in its internal data structure (called "the index"). On checkout the content is reencoded back to the specified encoding.

I hope that is helpful! If you have any other questions, please let me know.
