### ISSUE TITLE
Navigating between Branch and "Squash and Merge" enhancement

### ISSUE THREAD

**Issue by maximekl** [desktop/desktop#7069]
Hi,
It's more an double enhancement demand.

1. It's quite hard to navigate between branch when we have a lot of them, i would love to have the possibility to sort the list by date and by prefix (all improvement grouped, all feature grouped, all fix grouped....).

2. Would love to have the choice to "Squash and Merge" when i "Merge into Current Branch"

![Capture d’écran 2019-03-12 à 10 30 17](https://user-images.githubusercontent.com/11152214/54189946-201b3700-44b3-11e9-8848-cd2d60721ba2.png)

**Comment by billygriffin** [comment]
Hi @maximekl, thanks for the issue! I'm curious if the "Recent branches" section is useful for you at all, or how frequently you're looking for branches that are significantly older or that aren't part of a PR (and therefore can be accessed via the PR tab). I guess I'd love to understand a bit more about your workflow so we can better understand how this might benefit others.

You can follow along with your "Squash and merge" request in https://github.com/desktop/desktop/issues/2507. It's closed but listed as a `future proposal`, which indicates that it's still under consideration yet but we're uncertain about whether it will be supported.

**Comment by maximekl** [comment]
We do not delete merged branch :( That why we have a lot of old branch.
We work on a lot of features/fix/improvements at the same time, and it can be easy for us to quickly see more than the 4 last Branch.
It's confusing to filter on a word and have old Branch before new one.

Hope it's help you :)

![Capture d’écran 2019-03-12 à 14 44 00](https://user-images.githubusercontent.com/11152214/54204879-7b5e2100-44d5-11e9-92cb-aa8cd7fdf650.png)

**Comment by billygriffin** [comment]
> We do not delete merged branch :( That why we have a lot of old branch.

Thanks @maximekl! Do you think #750 would help with the fact that merged branches aren't deleted in Desktop? Basically what we're going to be doing there is to prune branches periodically in Desktop that are merged and deleted on GitHub.com. Or are you saying that you don't delete them even on GitHub.com after they've been merged?

**Comment by maximekl** [comment]
We have both, some merged branch are not deleted, but every review and merge into our develop Branch are done on GitHub.com (Desktop is just for switching branch and merge our fully tested develop Branch into master).
And i am pretty sure just a sort on modified date will do the trick for us.

**Comment by mido1966** [comment]
Dankeschön alles ok Seher libe alles ok

‏‫من الـ iPhone الخاص بي‬

‫في 12‏/03‏/2019 الساعة 10:46 ص، كتب/كتبت ‏MaximeK ‏<notifications@github.com<mailto:notifications@github.com>>:‬


Hi,
It's more an double enhancement demand.

  1.  It's quite hard to navigate between branch when we have a lot of them, i would love to have the possibility to sort the list by date and by prefix (all improvement grouped, all feature grouped, all fix grouped....).

  2.  Would love to have the choice to "Squash and Merge" when i "Merge into Current Branch"

[Capture d’écran 2019-03-12 à 10 30 17]<https://user-images.githubusercontent.com/11152214/54189946-201b3700-44b3-11e9-8848-cd2d60721ba2.png>

**Comment by billygriffin** [comment]
Thanks @maximekl, sorry for the delay. Because we do have something on the horizon #750 in combination with the "Recent branches" piece, I'm going to close this for now, but if you're still experiencing confusion and difficulty sorting through things in a few months after that ships, we're definitely happy to revisit. Thanks!
