### ISSUE TITLE
Menu is missing.

### ISSUE THREAD

**Issue by tomsepe** [desktop/desktop#7078]
## Description

None of the menus are visible. Github won't connect to my repositories, probably because I changed my password recently. But I can't get to the options screen because the menu is just gone. It does not reappear when I mouse over it, nor does alt-clicking or right clicking do anything.

## Version

* GitHub Desktop: I downloaded the latest version today (and have since uninstalled it) and then a few minutes ago downloaded the latest beta release 1.64-beta1 , same problem. 

* Operating system:
Windows 7 Pro

## Steps to Reproduce

1. Open Github
2. Not see Menu
3. Not be able to connect to my repositories
4. Be frustrated

### Expected Behavior

Open github
Click on "options", log out, log in, do all the things

### Actual Behavior

1. I resist throwing a tantrum
2. I resist throwing my laptop gainst the wall
3. I click on the empty white space at the top of the Github window incessantly like a crazy person.

**Comment by steveward** [comment]
@tomsepe Thanks for the report. Could GitHub Desktop possibly be in fullscreen mode? Try hitting `F11` to see if that brings the menus back into view. If that does not work, could you please share a screenshot of what you are currently seeing?

**Comment by tomsepe** [comment]
Definitely not in full screen mode. i can move the window around and I can go in and out of full screen mode and it makes no difference.  thought I uploaded a screen shot with this message last night? anyway just imagine a blank piece of paper with nothing on it. zero. nada zilch at the top of the menu. except the github logo on the left and the resize boxes and “x” to close on  the right. 

Tom Sepe
ART - DESIGN - FABRICATION
510.499.0946
http://tomsepe.com

**Comment by steveward** [comment]
@tomsepe it sounds like you may be running into https://github.com/desktop/desktop/issues/4054. Can you try following these steps to see if it gets things working?

1. Close GitHub Desktop
2. Remove all the files in `%APPDATA%\GitHub Desktop\`
2. Launch GitHub Desktop again

Let me know if that doesn't help.

**Comment by KipTwitchell** [comment]
That did 't fix the problem for me.  Same result

**Comment by steveward** [comment]
@KipTwitchell could you share a screenshot of what you are seeing?

**Comment by KipTwitchell** [comment]
Kip TwitchellIBM Global Business ServicesKip.Twitchell@us.ibm.com630-248-0443 (cell)
 
 
----- Original message -----From: Steve Ward <notifications@github.com>To: desktop/desktop <desktop@noreply.github.com>Cc: KipTwitchell <kip.twitchell@us.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [desktop/desktop] Menu is missing. (#7078)Date: Thu, Mar 21, 2019 7:18 PM 
@KipTwitchell could you share a screenshot of what you are seeing?

**Comment by tierninho** [comment]
@KipTwitchell please try again, as the screenshot din't come through.

**Comment by KipTwitchell** [comment]
Kip Twitchell
IBM Global Business Services
Kip.Twitchell@us.ibm.com
630-248-0443 (cell)
----- Forwarded by Kip M Twitchell/Chicago/IBM on 03/22/2019 03:49 PM 
-----

From:   Kip M Twitchell/Chicago/IBM
To:     
reply@reply.github.com
Cc:     desktop@noreply.github.com, mention@noreply.github.com
Date:   03/22/2019 02:05 PM
Subject:        Re: [desktop/desktop] Menu is missing. (#7078)






Kip Twitchell
IBM Global Business Services
Kip.Twitchell@us.ibm.com
630-248-0443 (cell)
 
 
----- Original message -----

**Comment by shiftkey** [comment]
@KipTwitchell are you able to attach a screenshot by replying in the issue itself? Replying via email isn't including any attachments or embedded images.

**Comment by steveward** [comment]
@KipTwitchell @tomsepe I am going to close this issue out due to inactivity. If you are still having any issues with GitHub Desktop, please let us know and we can continue to dive into this further.

**Comment by yao443jun** [comment]
> @tomsepe it sounds like you may be running into #4054. Can you try following these steps to see if it gets things working?
> 
> 1. Close GitHub Desktop
> 2. Remove all the files in `%APPDATA%\GitHub Desktop\`
> 3. Launch GitHub Desktop again
> 
> Let me know if that doesn't help.

it works for me!Thank you!

**Comment by BoricuaEnLaLuna** [comment]
This worked around the problem for me as well. I had a previous account still setup on my GitHub Desktop from about a year ago; but I was now trying to use a new account. When I installed GitHub Desktop this time it would ask me for creds of the new account, but once I signed in it would still use the old account's settings/repos. I could not change the account I was using from the original account to a new one; no menu items were showing up for me to change the account. Once I cleaned up the files at %APPDATA%\GitHub Desktop\ then I was able to repeat the sign in process and it would reflect the correct account settings afterwards. Looks like there is some bug here since once I sign in with new creds it should automatically stop using the previous account settings.

**Comment by eganesh1982** [comment]
this worked for me too. thanks for the help

**Comment by YaromCh** [comment]
Hi,
it's also possible to change only one field and not remove all the configuration files (if you don't want to log in and set the configuration again):

**Steps:**
open: %APPDATA%\GitHub Desktop\
open: "window-state.json" file
replace the field: "isFullScreen" from 'true' to 'false'.

**The problems I had were solved:**
1. GitHub Desktop opens full size
2. The Windows taskbar is not visible
3. The top menu bar is not visible

**Comment by DS-Saurabh** [comment]
> [@tomsepe](https://github.com/tomsepe) Thanks for the report. Could GitHub Desktop possibly be in fullscreen mode? Try hitting `F11` to see if that brings the menus back into view. If that does not work, could you please share a screenshot of what you are currently seeing?

Thanks ! 

Thats helps me
