### ISSUE TITLE
Unable to add submodule to Desktop

### ISSUE THREAD

**Issue by joshvera** [desktop/desktop#708]
**Steps to Reproduce:**
1. Attempt to drag and drop a submodule of a repo to Desktop.

**Expected:**
The submodule is added and tracked as it’s own repository.

**Actual:**
<img width="404" alt="screen shot 2016-12-01 at 1 10 35 pm" src="https://cloud.githubusercontent.com/assets/24247/20806113/941d1248-b7c7-11e6-8ac7-841263a310e3.png">

This isn’t an issue on ye olde Mac app. I remember this being an issue on Windows but I can’t remember if we resolved it.

**Comment by UjLion** [comment]
A workaround:
DISCLAIMER: FOLLOW WITH CAUTION, HAVE A BACKUP, i.e. commit and push first.
1. Remove any existing submodule reference from the parent repository
2. Manually delete the git reference directory from withing the .git/modules/ directory.
3. Clone the sub repository
4. Add this to 'Github Desktop'
5. Remove the sub repository
6. Pull as submodule: git submodule add <path> <target_name>

**Comment by dustyhorizon** [comment]
@UjLion sorry can you clarify the workaround? does this mean clone -> add -> delete would resolve the issue? does not seem that way to me though ...

**Comment by joshaber** [comment]
Fixed by https://github.com/desktop/desktop/pull/1881

**Comment by ujLion** [comment]
This is now fixed. However if you are still not able to add then make sure that you have NOT renamed the submodule directory yourself and have used: git submodule add --name **<name>** <url> **[path]** - params instead.
