### ISSUE TITLE
Self-update of app on Windows 10 removes it from programs list

### ISSUE THREAD

**Issue by ilmarh** [desktop/desktop#7084]
## Description

I'm using GitGub desktop on Windows 10 Pro (build 1809). I have administrator rights on it.
I install app as downloaded binary, it appears in programs list, available from start menu.
I'm able to pin it to task bar, etc.
But when it finds an update, downloads it and suggests to restart in order to install update, it dissappears from start menu (programs list) and every place its been pinned to.
I have to go to  C:\Users\<me>\AppData\Local\GitHubDesktop to launch it.
If i look in "applications and features" -- i can see it with new install date and version.
Then i delete app, download new install binary and reinstall it -- and appears in all pinned places again.

## Version

* GitHub Desktop: 1.6.4

* Operating system: Microsoft Windows [Version 10.0.17763.316]

## Steps to Reproduce

1. Install GitHub Desktop
2. Pin app icon to start menu or taskbar
3. Wait for update release
4. Launch app and check if 'Restart for update' message appears
5. Restart app
6. Look for empty space instead of app launch icon

### Expected Behavior

Launch icon in programs list and all pinned places

### Actual Behavior

It dissapears after upgrade

## Additional Information

I was unable to locate logs subdir, the only log i've found attached below. Sorry, it's localized. But i see some exception in it. Maybe this is the cause?

### Logs

[SquirrelSetup.log](https://github.com/desktop/desktop/files/2966278/SquirrelSetup.log)

**Comment by shiftkey** [comment]
@ilmarh thanks for the report! I tried to reproduce the steps on Window `10.0.17763.316` using the latest beta we're currently testing (`1.6.4-beta1` -> `1.6.5-beta1`) and couldn't trigger the same behaviour. Here's what I did:

After installing Desktop I went into the Start Menu and pinned both to the start menu and to the taskbar:

<img width="833" src="https://user-images.githubusercontent.com/359239/54356782-33f1a500-463b-11e9-860a-71f8663a8e03.png">

Both of these should be associated with the same shortcut, which goes to `%LOCALAPPDATA%\GitHubDesktop\GitHubDesktop.exe` (not a specific version, so it shouldn't be impacted by an upgrade):

<img width="1146" src="https://user-images.githubusercontent.com/359239/54356986-b7ab9180-463b-11e9-9598-992d2f4bd93f.png">

I then run Desktop, check for updates, and wait for it to be ready to restart:

<img width="1321"  src="https://user-images.githubusercontent.com/359239/54357056-e6c20300-463b-11e9-99be-fe377058fc63.png">

And after restart, the pinned links both have the icon and are able to launch the app.

That's the "happy path" for how this should work, and I have some extra questions about your repro steps:

> It dissapears after upgrade

My gut feeling at this point is that the behaviour you're seeing is due to this shortcut being removed:

<img width="1146" src="https://user-images.githubusercontent.com/359239/54356986-b7ab9180-463b-11e9-9598-992d2f4bd93f.png">

**Can you confirm that it no longer exists?**

I'm not quite sure why this shortcut would be removed as part of the update - this was created when the app was first installed, and shouldn't be touched until the app is uninstalled:

```
2019-03-11 12:43:48> ApplyReleasesImpl: Creating shortcut for GitHubDesktop.exe => C:\Users\i.khabibulin\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk
2019-03-11 12:43:48> ApplyReleasesImpl: About to save shortcut: C:\Users\i.khabibulin\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk (target C:\Users\i.khabibulin\AppData\Local\GitHubDesktop\GitHubDesktop.exe, workingDir C:\Users\i.khabibulin\AppData\Local\GitHubDesktop\app-1.6.3, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
```

The error that you found in there shouldn't have affected the update itself (it's trying to run post-install hooks embedded in programs, but doesn't block the update from completing):

```
2019-03-14 10:51:15> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\i.khabibulin\AppData\Local\GitHubDesktop\app-1.6.4\GitHubDesktop.exe: System.OperationCanceledException: The operation was canceled.
   ...
```

**Comment by maxbed** [comment]
14.03.2019. 13.49, "Brendan Forster" <notifications@github.com> је
написао/ла:

**Comment by ilmarh** [comment]
Yes, the shortcut you asked for is absent. Anything else i should check?

![image](https://user-images.githubusercontent.com/10096924/54358969-a7fb6f80-4672-11e9-81fb-963bd922282b.png)

**Comment by shiftkey** [comment]
@ilmarh if the app is still listed under "Apps & Features" the other two bits I'm curious about are the output of these two commands, run in Command Prompt:

```
> dir %LOCALAPPDATA%\GitHubDesktop
> dir %LOCALAPPDATA%\GitHubDesktop\app-1.6.4
```

This will help me confirm the upgrade looks like it was applied correctly, but at this point I'm not sure what might have removed the shortcut without digging more into the updater framework we use...

**Comment by ilmarh** [comment]
`C:\Users\i.khabibulin>dir %LOCALAPPDATA%\GitHubDesktop
 Том в устройстве C имеет метку Windows
 Серийный номер тома: 102D-1BB4

 Содержимое папки C:\Users\i.khabibulin\AppData\Local\GitHubDesktop

14.03.2019  10:50    <DIR>          .
14.03.2019  10:50    <DIR>          ..
11.03.2019  12:43    <DIR>          app-1.6.3
14.03.2019  10:50    <DIR>          app-1.6.4
11.03.2019  12:43           129 000 app.ico
11.03.2019  12:43    <DIR>          bin
14.03.2019  10:50           382 424 GitHubDesktop.exe
14.03.2019  10:51    <DIR>          packages
14.03.2019  15:03           199 792 SquirrelSetup.log
11.03.2019  12:43         1 659 352 Update.exe
               4 файлов      2 370 568 байт
               6 папок  662 076 350 464 байт свободно

C:\Users\i.khabibulin>dir %LOCALAPPDATA%\GitHubDesktop\app-1.6.4
 Том в устройстве C имеет метку Windows
 Серийный номер тома: 102D-1BB4

 Содержимое папки C:\Users\i.khabibulin\AppData\Local\GitHubDesktop\app-1.6.4

14.03.2019  10:50    <DIR>          .
14.03.2019  10:50    <DIR>          ..
14.03.2019  10:50            19 208 api-ms-win-core-console-l1-1-0.dll
14.03.2019  10:50            18 696 api-ms-win-core-datetime-l1-1-0.dll
14.03.2019  10:50            18 696 api-ms-win-core-debug-l1-1-0.dll
14.03.2019  10:50            18 696 api-ms-win-core-errorhandling-l1-1-0.dll
14.03.2019  10:50            22 280 api-ms-win-core-file-l1-1-0.dll
14.03.2019  10:50            18 696 api-ms-win-core-file-l1-2-0.dll
14.03.2019  10:50            18 696 api-ms-win-core-file-l2-1-0.dll
14.03.2019  10:50            18 696 api-ms-win-core-handle-l1-1-0.dll
14.03.2019  10:50            19 208 api-ms-win-core-heap-l1-1-0.dll
14.03.2019  10:50            18 696 api-ms-win-core-interlocked-l1-1-0.dll
14.03.2019  10:50            19 720 api-ms-win-core-libraryloader-l1-1-0.dll
14.03.2019  10:50            21 256 api-ms-win-core-localization-l1-2-0.dll
14.03.2019  10:50            19 208 api-ms-win-core-memory-l1-1-0.dll
14.03.2019  10:50            18 696 api-ms-win-core-namedpipe-l1-1-0.dll
14.03.2019  10:50            19 720 api-ms-win-core-processenvironment-l1-1-0.dll
14.03.2019  10:50            20 744 api-ms-win-core-processthreads-l1-1-0.dll
14.03.2019  10:50            19 208 api-ms-win-core-processthreads-l1-1-1.dll
14.03.2019  10:50            18 184 api-ms-win-core-profile-l1-1-0.dll
14.03.2019  10:50            19 208 api-ms-win-core-rtlsupport-l1-1-0.dll
14.03.2019  10:50            18 696 api-ms-win-core-string-l1-1-0.dll
14.03.2019  10:50            20 744 api-ms-win-core-synch-l1-1-0.dll
14.03.2019  10:50            19 208 api-ms-win-core-synch-l1-2-0.dll
14.03.2019  10:50            19 720 api-ms-win-core-sysinfo-l1-1-0.dll
14.03.2019  10:50            19 208 api-ms-win-core-timezone-l1-1-0.dll
14.03.2019  10:50            18 696 api-ms-win-core-util-l1-1-0.dll
14.03.2019  10:50            19 720 api-ms-win-crt-conio-l1-1-0.dll
14.03.2019  10:50            22 792 api-ms-win-crt-convert-l1-1-0.dll
14.03.2019  10:50            19 208 api-ms-win-crt-environment-l1-1-0.dll
14.03.2019  10:50            20 744 api-ms-win-crt-filesystem-l1-1-0.dll
14.03.2019  10:50            19 720 api-ms-win-crt-heap-l1-1-0.dll
14.03.2019  10:50            19 208 api-ms-win-crt-locale-l1-1-0.dll
14.03.2019  10:50            27 912 api-ms-win-crt-math-l1-1-0.dll
14.03.2019  10:50            26 888 api-ms-win-crt-multibyte-l1-1-0.dll
14.03.2019  10:50            71 432 api-ms-win-crt-private-l1-1-0.dll
14.03.2019  10:50            19 720 api-ms-win-crt-process-l1-1-0.dll
14.03.2019  10:50            23 304 api-ms-win-crt-runtime-l1-1-0.dll
14.03.2019  10:50            24 840 api-ms-win-crt-stdio-l1-1-0.dll
14.03.2019  10:50            24 840 api-ms-win-crt-string-l1-1-0.dll
14.03.2019  10:50            21 256 api-ms-win-crt-time-l1-1-0.dll
14.03.2019  10:50            19 208 api-ms-win-crt-utility-l1-1-0.dll
14.03.2019  10:50             4 214 blink_image_resources_200_percent.pak
14.03.2019  10:50                18 content_resources_200_percent.pak
14.03.2019  10:50         7 482 208 content_shell.pak
14.03.2019  10:50         4 173 928 d3dcompiler_47.dll
14.03.2019  10:50         1 838 040 ffmpeg.dll
14.03.2019  10:50        71 245 784 GitHubDesktop.exe
14.03.2019  10:50        10 171 360 icudtl.dat
14.03.2019  10:50            24 536 libEGL.dll
14.03.2019  10:50         3 859 416 libGLESv2.dll
14.03.2019  10:50             1 060 LICENSE
14.03.2019  10:50    <DIR>          locales
14.03.2019  10:50           641 696 msvcp140.dll
14.03.2019  10:50           175 097 natives_blob.bin
14.03.2019  10:50        18 580 952 node.dll
14.03.2019  10:50    <DIR>          resources
14.03.2019  10:50         1 659 352 squirrel.exe
14.03.2019  10:51             3 073 SquirrelSetup.log
14.03.2019  10:50         1 016 584 ucrtbase.dll
14.03.2019  10:50           112 209 ui_resources_200_percent.pak
14.03.2019  10:50         1 766 548 v8_context_snapshot.bin
14.03.2019  10:50            87 728 vcruntime140.dll
14.03.2019  10:50            56 372 views_resources_200_percent.pak
              60 файлов    123 764 751 байт
               4 папок  662 076 334 080 байт свободно`

**Comment by ilmarh** [comment]
While importing some project from github desktop popuped info about new version 1.6.5.
I clicked "restart to update" and now i have icon and link in place. Any comments?

![image](https://user-images.githubusercontent.com/10096924/54591771-02624a80-4a3c-11e9-8581-84ae5918748c.png)
![image](https://user-images.githubusercontent.com/10096924/54591828-202faf80-4a3c-11e9-90ba-bca68f53d87b.png)
```
C:\Users\i.khabibulin>dir %LOCALAPPDATA%\GitHubDesktop\app-1.6.4
 Том в устройстве C имеет метку Windows
 Серийный номер тома: 102D-1BB4

 Содержимое папки C:\Users\i.khabibulin\AppData\Local\GitHubDesktop\app-1.6.4

14.03.2019  10:50    <DIR>          .
14.03.2019  10:50    <DIR>          ..
14.03.2019  10:50            19 208 api-ms-win-core-console-l1-1-0.dll
14.03.2019  10:50            18 696 api-ms-win-core-datetime-l1-1-0.dll
14.03.2019  10:50            18 696 api-ms-win-core-debug-l1-1-0.dll
14.03.2019  10:50            18 696 api-ms-win-core-errorhandling-l1-1-0.dll
14.03.2019  10:50            22 280 api-ms-win-core-file-l1-1-0.dll
14.03.2019  10:50            18 696 api-ms-win-core-file-l1-2-0.dll
14.03.2019  10:50            18 696 api-ms-win-core-file-l2-1-0.dll
14.03.2019  10:50            18 696 api-ms-win-core-handle-l1-1-0.dll
14.03.2019  10:50            19 208 api-ms-win-core-heap-l1-1-0.dll
14.03.2019  10:50            18 696 api-ms-win-core-interlocked-l1-1-0.dll
14.03.2019  10:50            19 720 api-ms-win-core-libraryloader-l1-1-0.dll
14.03.2019  10:50            21 256 api-ms-win-core-localization-l1-2-0.dll
14.03.2019  10:50            19 208 api-ms-win-core-memory-l1-1-0.dll
14.03.2019  10:50            18 696 api-ms-win-core-namedpipe-l1-1-0.dll
14.03.2019  10:50            19 720 api-ms-win-core-processenvironment-l1-1-0.dll
14.03.2019  10:50            20 744 api-ms-win-core-processthreads-l1-1-0.dll
14.03.2019  10:50            19 208 api-ms-win-core-processthreads-l1-1-1.dll
14.03.2019  10:50            18 184 api-ms-win-core-profile-l1-1-0.dll
14.03.2019  10:50            19 208 api-ms-win-core-rtlsupport-l1-1-0.dll
14.03.2019  10:50            18 696 api-ms-win-core-string-l1-1-0.dll
14.03.2019  10:50            20 744 api-ms-win-core-synch-l1-1-0.dll
14.03.2019  10:50            19 208 api-ms-win-core-synch-l1-2-0.dll
14.03.2019  10:50            19 720 api-ms-win-core-sysinfo-l1-1-0.dll
14.03.2019  10:50            19 208 api-ms-win-core-timezone-l1-1-0.dll
14.03.2019  10:50            18 696 api-ms-win-core-util-l1-1-0.dll
14.03.2019  10:50            19 720 api-ms-win-crt-conio-l1-1-0.dll
14.03.2019  10:50            22 792 api-ms-win-crt-convert-l1-1-0.dll
14.03.2019  10:50            19 208 api-ms-win-crt-environment-l1-1-0.dll
14.03.2019  10:50            20 744 api-ms-win-crt-filesystem-l1-1-0.dll
14.03.2019  10:50            19 720 api-ms-win-crt-heap-l1-1-0.dll
14.03.2019  10:50            19 208 api-ms-win-crt-locale-l1-1-0.dll
14.03.2019  10:50            27 912 api-ms-win-crt-math-l1-1-0.dll
14.03.2019  10:50            26 888 api-ms-win-crt-multibyte-l1-1-0.dll
14.03.2019  10:50            71 432 api-ms-win-crt-private-l1-1-0.dll
14.03.2019  10:50            19 720 api-ms-win-crt-process-l1-1-0.dll
14.03.2019  10:50            23 304 api-ms-win-crt-runtime-l1-1-0.dll
14.03.2019  10:50            24 840 api-ms-win-crt-stdio-l1-1-0.dll
14.03.2019  10:50            24 840 api-ms-win-crt-string-l1-1-0.dll
14.03.2019  10:50            21 256 api-ms-win-crt-time-l1-1-0.dll
14.03.2019  10:50            19 208 api-ms-win-crt-utility-l1-1-0.dll
14.03.2019  10:50             4 214 blink_image_resources_200_percent.pak
14.03.2019  10:50                18 content_resources_200_percent.pak
14.03.2019  10:50         7 482 208 content_shell.pak
14.03.2019  10:50         4 173 928 d3dcompiler_47.dll
14.03.2019  10:50         1 838 040 ffmpeg.dll
14.03.2019  10:50        71 245 784 GitHubDesktop.exe
14.03.2019  10:50        10 171 360 icudtl.dat
14.03.2019  10:50            24 536 libEGL.dll
14.03.2019  10:50         3 859 416 libGLESv2.dll
14.03.2019  10:50             1 060 LICENSE
14.03.2019  10:50    <DIR>          locales
14.03.2019  10:50           641 696 msvcp140.dll
14.03.2019  10:50           175 097 natives_blob.bin
14.03.2019  10:50        18 580 952 node.dll
14.03.2019  10:50    <DIR>          resources
14.03.2019  10:50         1 659 352 squirrel.exe
14.03.2019  10:51             3 073 SquirrelSetup.log
14.03.2019  10:50         1 016 584 ucrtbase.dll
14.03.2019  10:50           112 209 ui_resources_200_percent.pak
14.03.2019  10:50         1 766 548 v8_context_snapshot.bin
14.03.2019  10:50            87 728 vcruntime140.dll
14.03.2019  10:50            56 372 views_resources_200_percent.pak
              60 файлов    123 764 751 байт
               4 папок  663 065 227 264 байт свободно
```

**Comment by shiftkey** [comment]
@ilmarh I don't really have any other clues into why that shortcut might be removed between updates - I can't find anything in the logs or in the updater source code that might explain it. I'm glad that the latest update worked for you, and for the moment we have an issue in place to update `electron-winstaller` - that contains the Squirrel updater framework - in #5197 that will be a good opportunity to re-test this area.

I'm going to make a note in there to remind us to revisit this discussion then, but I don't think there's much else we can do currently. Feel free to add more comments in here if you spot anything that might explain why the shortcut is being removed during updates, and thanks for troubleshooting with me to investigate!
