### ISSUE TITLE
[Metrics] Commits to protected branches

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#7091]
To understand the potential impact of #7023 (and to decide how to prioritize it), we'd like to understand the following information about commits to protected branches.

**For users who have committed to a repo with at least one protected branch**:

1. How many users fit the above category (people who have committed to a repo with at least one protected branch)
2. How many commits per user to a protected branch
3. How frequently it's occurring for people
4. % of people accidentally committing to a protected branch
5. On repos with protected branches, % of commits to those branches

(thanks to @nerdneha for making this way better than it started, and cc: @scottypate for visibility since we've discussed this)

**Comment by shiftkey** [comment]
Closing this out as changes in the 1.7 release will provide insights into these questions, and we have the original issue  #7023 open to discuss things further
