### ISSUE TITLE
Searches related to <iframe width="100%" height="600" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3a//api.soundcloud.com/tracks/110976003&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe>

### ISSUE THREAD

**Issue by neonenoneo** [desktop/desktop#7092]
## Version

* GitHub Desktop:

* Operating system:

**Comment by neonenoneo** [comment]
https://github.com/desktop/desktop/issues/7092#issue-421377907

**Comment by neonenoneo** [comment]
https://github.com/desktop/desktop/issues/7092#issue-421377907

**Comment by steveward** [comment]
Thanks for reaching out @neonenoneo !

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further. Thanks!
