### ISSUE TITLE
cleanup custom DialogHeader inside Release Notes

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#7093]
This is some cleanup to avoid the workarounds that we've used in some dialogs to support complex headers. #6032 talked about being able to provide support for passing in a JSX element rather than a plain string, which means we can clean up this custom element:

https://github.com/desktop/desktop/blob/b5529325ae629a52b02cb3e07699f1ccbcfb2cfa/app/src/ui/release-notes/release-notes-dialog.tsx#L158-L175

**Version:** development aka b5529325ae629a52b02cb3e07699f1ccbcfb2cfa

**Testing:**

To see this dialog for yourself, build the app in development mode and run it up:

```
$ yarn
$ yarn build:dev
$ yarn start
```

With it running, find the `Help` -> `Show Popup` -> `Release notes` menu item:

<img width="527" alt="Screen Shot 2019-03-15 at 10 59 15 AM" src="https://user-images.githubusercontent.com/359239/54436747-e005bf80-4711-11e9-8c64-0361de21dd9b.png">

This will then show the dialog - make a note of how things look to ensure that the cleanup in here doesn't affect the styles.

<img width="667" alt="Screen Shot 2019-03-15 at 10 59 27 AM" src="https://user-images.githubusercontent.com/359239/54436821-062b5f80-4712-11e9-8636-23739b06b13c.png">

With that change in place, check out the contents of `render()` inside `app/src/ui/release-notes/release-notes-dialog.tsx`. We should be able to remove the `<DialogHeader>` element and only use props on `<Dialog>` now to achieve the functionality:

```ts
    return (
      <Dialog
        id="release-notes"
        title={header} // TODO
        onDismissed={this.props.onDismissed}
      >
        <DialogContent>{contents}</DialogContent>
```

One thing to check while you're in here is that the close icon is positioned in the top-right (like in the original screenshot) - it looks like having a tall header now causes the default dialog styles to change:

<img width="625" alt="Screen Shot 2019-03-15 at 11 08 43 AM" src="https://user-images.githubusercontent.com/359239/54437217-e8aac580-4712-11e9-9210-0cf4fd7a4f01.png">

These are the header-specific styles for this dialog that you might need to tweak:

https://github.com/desktop/desktop/blob/b5529325ae629a52b02cb3e07699f1ccbcfb2cfa/app/styles/ui/dialogs/_release-notes.scss#L11-L42

But I think you'll need to look at the base styles for the dialog to get this working correctly again.

**Comment by alejandronanez** [comment]
Hey there!

I'm new to the project and I'd like to help - this seems to be a good issue for beginners, am I right?

If so, can I grab it?

Thanks!

**Comment by shiftkey** [comment]
@alejandronanez go for it!

**Comment by alejandronanez** [comment]
Awesome @shiftkey, I’ll work on this durong this week!

Thanks!

**Comment by alejandronanez** [comment]
Hey @shiftkey, I had to attend a family emergency, so I won’t be able to start working on this until early next week. If that doesn’t work for the project, let me know!

Thanks!

**Comment by shiftkey** [comment]
@alejandronanez thanks for the update. I'm going to move this back into the "Available" pile to reflect that this could be picked up by someone else, but feel free to grab it next week when you have time!

**Comment by alejandronanez** [comment]
Hey @shiftkey, I'm available again - since nobody claimed this issue, I'd like to start working on it!

**Comment by tierninho** [comment]
@alejandronanez go for it and big thanks for contributing ✨

**Comment by alejandronanez** [comment]
Hey @shiftkey & @tierninho - I got some questions regarding this issue,

If I understand this correctly, what we want to achieve here is to avoid the usage of `DialogHeader` inside a `Dialog` component, to get to something like this:

```jsx
const dialogHeader = (
  <DialogHeader dismissable={false}>{dialogHeaderContents}</DialogHeader>
)

// later on
return (
  <Dialog
    title={dialogHeader} // this is the new part
    id="release-notes"
    onDismissed={this.props.onDismissed}
  >
    <DialogContent>{content}</DialogContent>
    <DialogFooter>{content}</DialogFooter>
  </Dialog>
)
```

Is that right?

Also, I want to make sure that you're aware that this would affect other dialogs, are you aware of this? - asking because this issue's title `cleanup custom DialogHeader inside Release Notes`

![Screen Shot 2019-03-29 at 6 54 00 AM](https://user-images.githubusercontent.com/464978/55231030-7694af00-51ef-11e9-8544-15faf7fde492.png)

If so, how what are the steps to open the `Merge Conflicts` and `Merge` dialogs?

Thanks!

**Comment by shiftkey** [comment]
@alejandronanez you're on the right track, but let me see if I can clarify things:

> If I understand this correctly, what we want to achieve here is to avoid the usage of `DialogHeader` inside a `Dialog` component, to get to something like this:

Because we added support for using JSX in the `header` of a `Dialog`, we should be able to just pass in `dialogHeaderContents` (or a tweaked version) and avoid the need to import and wrap it in a `<DialogHeader>`. Does that clarify things?

> Also, I want to make sure that you're aware that this would affect other dialogs, are you aware of this? - 

This is fine - the work to make changes to `Merge Conflict` and `Merge Branch` are being tracked in #7043, and we have an open PR #7151 to go with it.

**Comment by xPaw** [comment]
> One thing to check while you're in here is that the close icon is positioned in the top-right 

this was never fixed and now it blends in even more :)

<img width="826" height="219" alt="Image" src="https://github.com/user-attachments/assets/ba8ee3da-b7c3-4217-9cc6-da5da1ebbac3" />
