### ISSUE TITLE
Black squares in the app window

### ISSUE THREAD

**Issue by konopkoman** [desktop/desktop#7102]
There are black squares in the window when scrolling

![Annotation 2019-03-15 231728](https://user-images.githubusercontent.com/11742887/54459731-a0be8980-4778-11e9-9398-9377b86876be.jpg)

**Comment by tierninho** [comment]
@konopkoman Thanks for filing. 

Any other details you can share, like OS, version of Desktop, or the steps that led up to this?

**Comment by konopkoman** [comment]
Win10, just scroll the app window

**Comment by tierninho** [comment]
I cannot reproduce this. It would be great if you could send over more details @konopkoman 

Until then, closing this issue. Happy to reopen if needed or if other report the same. Thanks.
