### ISSUE TITLE
[rebase] Disable Abort button after first click

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7104]
I noticed that you can click the `Abort` button (during a rebase conflict) more than once, which leads to a `A lock file already exists in the repository, which blocks this operation from completing.)` error surfacing. Perhaps we need to disable it, although I am have no strong feels on this bug as it is unlikely to happen and the recovery is easy. 

Repro:
- pull up Rebase conflict
- double or triple-click Abort button

Tried to repro it on merge conflict flow, but could not.

![image](https://user-images.githubusercontent.com/14828183/54464560-42af8900-471b-11e9-83f1-5bf1e9c4a670.png)

8b061eac07, mac

**Comment by billygriffin** [comment]
@tierninho Does this also occur in the regular merge conflict flow on abort?

**Comment by tierninho** [comment]
No, tried to repro it on merge conflict flow but couldn't.

**Comment by shiftkey** [comment]
This flow has changed as part of #7117 and I'll retest this flow to ensure we're setting the correct state inside the new abort flow.

**Comment by tierninho** [comment]
I was able to reproduce this in Merge conflicts flow, but only because the long lag in my Windows VM, otherwise it is very difficult to reproduce...

Here is the error output:
<img width="911" alt="Screen Shot 2019-03-18 at 10 04 28 AM" src="https://user-images.githubusercontent.com/14828183/54560001-69f99680-4965-11e9-9996-eb6bc0186e4a.png">

v1.6.5-beta2, windows 10

**Comment by shiftkey** [comment]
@tierninho @billygriffin #7117 has the changes to disable when aborting a rebase (both cases) - in particular https://github.com/desktop/desktop/pull/7117/commits/81f49bf4acc48753af65deecb214ea8694881e0b and https://github.com/desktop/desktop/pull/7117/commits/1b7363871c6572c33148a031d48580ddb9366b83. Once those land in `development` I'll update this issue to indicate that Merge Conflicts is the only remaining work, which makes me think it can be dropped from the milestone.
