### ISSUE TITLE
Severe delay

### ISSUE THREAD

**Issue by Mario34** [desktop/desktop#7105]
> When I opened the software, I encountered a severe lag, mainly due to delays.My installation package is from the official website. The system is Windows 10 with CPU i5 8400,Hope to get a reply, thank you!

**Comment by tierninho** [comment]
@Mario34 Can you elaborate on the "severe lag"? What are the details and what steps were you trying to perform? Also, what version of Desktop are you using?

**Comment by tierninho** [comment]
@Mario34 As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
