### ISSUE TITLE
Github Desktop stopped to work with Windows 10 after latest Windows update

### ISSUE THREAD

**Issue by KestutisIT** [desktop/desktop#7106]
## Description

I believe that stupid Microsoft just broke a Github Desktop with his latest updates of this week. As Github desktop does not starts anymore. Only only Github Classic can be launced

## Version

* GitHub Desktop:

* Operating system:
Windows 10 x64

**Comment by billygriffin** [comment]
@KestutisIT Thanks for the issue. Would you mind filling out the rest of the template so we can try to get to the bottom of what might be happening? I’d love to understand when this started happening and what version update you did before it began.

**Comment by tierninho** [comment]
@KestutisIT As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
