### ISSUE TITLE
Issue using github desktop with a proxy

### ISSUE THREAD

**Issue by prascher** [desktop/desktop#7107]
I am running the GitHub Desktop on Ubuntu 18.04 and running a proxy locally which drives me crazy.  Please try to fix it
sincerely,
prascher

**Comment by billygriffin** [comment]
Hi @prascher, thanks for the issue and sorry it's frustrating! We're looking at this in #2789 and there's a workaround in that issue for how to make it work well until we have some better tooling around it.

**Comment by prascher** [comment]
Thanks @billygriffin following their advice and a little experimenting fixed my issue.

**Comment by billygriffin** [comment]
Glad to hear it @prascher!

**Comment by SSH93** [comment]
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
