### ISSUE TITLE
Remove multiple merged local branches

### ISSUE THREAD

**Issue by kolya182** [desktop/desktop#7109]
**Please describe the problem you think should be solved**
Currently no way to delete multiple merged branches at the time. You have to `checkout` to branch and remove it individually.

**[Optional] Do you have any potential solutions in mind?**
* Press `Shift` and select desire branches, use `delete` to remove them

**Comment by love143bethi** [comment]
Delete

**Comment by billygriffin** [comment]
Hi @kolya182, sorry for the delay. Would you mind helping us understand what your use case is and how this would be valuable. We recently shipped a feature for #750 to beta, which will prune branches in Desktop that are merged and deleted on github.com. Would this solve your issue when it ships to production?

**Comment by tierninho** [comment]
@kolya182 As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
