### ISSUE TITLE
Resolve conflict before merging "dialog" is too small.

### ISSUE THREAD

**Issue by tntc4** [desktop/desktop#7115]
> “When I run into a merge conflict, the Resolve conflict before merging dialog box ia too small and the file names is cut in the end with ...
Please make this window bigger, or at least give a hint about the file name”

see screenshot I provided
![Screenshot_1](https://user-images.githubusercontent.com/3246834/54536826-1b1a2400-499a-11e9-9876-65239de71d67.jpg)

**Comment by billygriffin** [comment]
Thanks for the issue @tntc4! We're looking at this in https://github.com/desktop/desktop/issues/6851, so I'm going to close this issue and please follow along there. Really appreciate you pointing it out!
