### ISSUE TITLE
Light/Dark mode not checked on startup

### ISSUE THREAD

**Issue by juliand665** [desktop/desktop#7116]
## Description
Recently, GitHub Desktop got the option to "Automatically switch theme to match system theme", which I really appreciate, as someone who regularly switches between light and dark mode.

However, this setting isn't applied on startup, so shutting down GD in light mode, switching to dark mode, then starting it back up results in a (desynced) light GD in a dark environment. I don't know exactly how you match the system appearance, but it should be possible to query it on startup or something, right?

## Version
* GitHub Desktop: 1.6.4
* Operating system: macOS Mojave 10.14.3

## Steps to Reproduce
1. Turn on "Automatically switch theme to match system theme" in the appearance settings.
2. Quit GitHub Desktop
3. Toggle system appearance to the other mode.
4. Open GitHub Desktop

### Expected Behavior
GitHub Desktop is in the new theme, matching the rest of the system.

### Actual Behavior
GitHub Desktop is still in the old theme. Toggling the "Automatically switch theme to match system theme" setting twice makes it match the theme again, as does toggling the system theme twice (while GD is open).

**Comment by shiftkey** [comment]
cc @say25 for :eyes: and thoughts

**Comment by say25** [comment]
Seems like a solid enhancement. I can pick this up soon. I thought we covered this case but maybe not :/ dont have my Mac atm to verify

**Comment by JB1905** [comment]
it would also be great to add the `darwinDarkModeSupport: true` option to build.ts. The window frame and the top bar in full-screen mode do not adjust to the dark mode on macOS.

**Comment by shiftkey** [comment]
@JB1905 I've moved the `darwinDarkModeSupport` request over to #7118 as that can be addressed independent of this issue.
