### ISSUE TITLE
enable darwinDarkModeSupport when packaging for macOS

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#7118]
**Please describe the problem you think should be solved**

There is a new option on `electron-packager` which sets a flag to force Mojave builds to

> [`darwinDarkModeSupport`](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#darwindarkmodesupport)
> Boolean (default: `false`)
> Forces support for Mojave (macOS 10.14) dark mode in your packaged app. This sets the `NSRequiresAquaSystemAppearance` key to `false` in your app's `Info.plist`. For more information, see the [Apple developer documentation](https://developer.apple.com/documentation/appkit/nsappearancecustomization/choosing_a_specific_appearance_for_your_app).

@JB1905 over in #7116 suggests there's other tangible benefits:

> The window frame and the top bar in full-screen mode do not adjust to the dark mode on macOS.

**Do you have any potential solutions in mind?**

This is the place that tracks our `electron-packager` config settings, where this new value should be added:

https://github.com/desktop/desktop/blob/08632922908b138da950427ad7e1ac1ce184c992/script/build.ts#L150-L196

This should also be tested by someone with Mojave to ensure the change has the desired effect.

**Comment by say25** [comment]
@shiftkey I can take this on as well 🕶

**Comment by JB1905** [comment]
> solutions
Currently, the native window elements (e.g. top bar) do not adapt to the macOS Mojave theme.

I can do PR with a proposal for change

I put a comparison:
#### Actual
<img width="700" alt="Zrzut ekranu 2019-03-18 o 21 17 10" src="https://user-images.githubusercontent.com/28870390/54560791-6bf24280-49c3-11e9-8857-c5377a0035c1.png">

#### New
<img width="700" alt="Zrzut ekranu 2019-03-18 o 21 13 46" src="https://user-images.githubusercontent.com/28870390/54560811-74e31400-49c3-11e9-8008-1bffe1481bf0.png">

**Comment by say25** [comment]
@JB1905 feel free to open a PR 😃

**Comment by juliand665** [comment]
Just hopping in to point out that "officially" supporting dark mode not only makes menu bars appear correctly, it also adjusts the appearance of the right click menu as well as any dialogs spawned by the app, which really sticks out when it doesn't match.

**Comment by say25** [comment]
@juliand665 Dark Mode is still in beta, I know @JB1905 got a PR opened to address part of it. I should be opening one tonight to fix Dark Mode Auto Switching not working when the app is closed

**Comment by shiftkey** [comment]
>  supporting dark mode not only makes menu bars appear correctly, it also adjusts the appearance of the right click menu as well as any dialogs spawned by the app, which really sticks out when it doesn't match.

@juliand665 are you able to share some screenshots of these situations to illustrate the issue?

@JB1905 are you able to look into whether your changes in #7119 does address this?

**Comment by juliand665** [comment]
@shiftkey sure; here are some screenshots:

In GitHub Desktop:
<img width="799" alt="Screenshot of right click menu in GitHub Desktop" src="https://user-images.githubusercontent.com/827762/54639683-42eab400-4a8e-11e9-9162-40530bc3b0a4.png">

What it should look like in dark mode:
<img width="324" alt="Screenshot of right click menu outside GitHub Desktop" src="https://user-images.githubusercontent.com/827762/54639696-4b42ef00-4a8e-11e9-8f8c-7f93786dfc1e.png">

In Add Local Repository > Choose…:
<img width="924" alt="Screenshot of open panel in GitHub Desktop" src="https://user-images.githubusercontent.com/827762/54639834-9c52e300-4a8e-11e9-80ea-1e41675d10fd.png">

What that should look like in dark mode:
<img width="878" alt="Screenshot of open panel outside GitHub Desktop" src="https://user-images.githubusercontent.com/827762/54639894-bab8de80-4a8e-11e9-80e2-a427df871f2f.png">

**Comment by shiftkey** [comment]
@juliand665 thanks for the screenshots. Hopefully this same flag in #7119 is enough to also get those working - let's see what we can confirm in that PR.

**Comment by JB1905** [comment]
#### With `darwinDarkModeSupport: true`

<img width="114" alt="Zrzut ekranu 2019-03-19 o 21 54 09" src="https://user-images.githubusercontent.com/28870390/54641074-8e529180-4a91-11e9-854d-00a51a24b15c.png">
