### ISSUE TITLE
git diff takes more than 10 seconds for large binary files

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#7120]
When I click a large binary file (.pdf, more than 1GB), it takes more than 10 seconds to load the diff:
![image](https://user-images.githubusercontent.com/5396286/54577610-6afaf880-4a37-11e9-9e2d-0dcf47ddc09a.png)

and the diff view didn't response during the loading:
![image](https://user-images.githubusercontent.com/5396286/54577614-6e8e7f80-4a37-11e9-903d-e4b16c5f7429.png)

Can we enhance the diff view: show the message below quickly for binary files?
![image](https://user-images.githubusercontent.com/5396286/54577741-eceb2180-4a37-11e9-87d8-cbf28145c80d.png)

**Comment by shiftkey** [comment]
@TerryChan thanks for the feedback. I'm going to fold this into an earlier issue that overlaps with this issue: #1913
