### ISSUE TITLE
TypeError: Cannot read property 'close' of undefined at FSEvent.FSWatcher._handle.onchange

### ISSUE THREAD

**Issue by zhengxi2019** [desktop/desktop#7127]
## Version

* GitHub Desktop: 1.6.4

* Operating system:Windows 10.0.17134

### Logs

TypeError: Cannot read property 'close' of undefined
    at FSEvent.FSWatcher._handle.onchange (fs.js:1385:22)

**Comment by zhengxi2019** [comment]
TypeError: Cannot read property 'close' of undefined
    at FSEvent.FSWatcher._handle.onchange (fs.js:1385:22)

Version: 1.6.4
OS: Windows 10.0.17134

**Comment by shiftkey** [comment]
@zhengxi2019 thanks for the report! I think this is related to this code:

https://github.com/desktop/desktop/blob/2a17820ded6b11e455c239dfb07233a67204edc2/app/src/lib/tailer.ts#L109-L112

In theory we should have a valid `state.watcher` but maybe there's some edge case here that we're unaware of.

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by shiftkey** [comment]
I've also noticed this same issue over on the VSCode repo (same Electron version, different repro) https://github.com/Microsoft/vscode/issues/70566#issuecomment-475152190 which makes me think it might be an internal issue in Electron that we can't easily control. https://github.com/electron/node/pull/70 has some more context, and it might require another upstream fix to the version of Node to correctly handle `null` and `undefined` when closing the `FSWatcher`.

**Comment by bpasero** [comment]
@shiftkey hey, do you have any clue how this can happen? Just looking at the code starting at https://github.com/electron/node/blob/fcaf11a29c421b0e76c9f24f5b155a53eff14e7f/lib/fs.js#L1374 how can `this._handle` ever be undefined ❓

**Comment by shiftkey** [comment]
@bpasero after pondering on this today I realised the problem, and I think I just figured out the fix too https://github.com/electron/node/pull/97

**Comment by bpasero** [comment]
@shiftkey great

**Comment by bpasero** [comment]
Oh man, coding in TypeScript with arrow functions for 7 years now made me not see the `var self`... thingy, great catch 💯

**Comment by shiftkey** [comment]
Moving this to a `bug` now that the fix has been acknowledged upstream, and this should be resolved with a future Electron `3.1.x` release.

**Comment by shiftkey** [comment]
Electron [`3.1.8`](https://github.com/electron/electron/releases/tag/v3.1.8) has been released with this bugfix. Once we've figured out when we want to upgrade Electron to this release, we'll add this issue to the relevant milestone.

**Comment by b0810** [comment]
Bonjour Brendan, 

Vous cherchez un nouveau site pouvant vous aider à gagner des millions au bout de 3 mois de travail acharné? 

Vous tombez bien parce que j"ai un tout nouveau site qui peut vous générer des millions de dollars en trois mois.
Cliquez sur ce lien si vous le voulez bien Builderall Leverage Affiliate System | Builderall Leveraged Affiliate System


| 
| 
|  | 
Builderall Leverage Affiliate System | Builderall Leveraged Affiliate Sy...

Builderall Business's Leveraged Affiliate System gives you a leveraged gain and solid recurring income based on ...
 |

 |

 |


Cordialement, 

Borath YUN



Envoyé depuis Yahoo Mail. Obtenir l’application 

    Le jeudi 28 mars 2019 à 21:57:47 UTC+1, Brendan Forster <notifications@github.com> a écrit :  
 
 
Electron 3.1.8 has been released with this bugfix. Once we've figured out when we want to upgrade Electron to this release, we'll add this issue to the relevant milestone.

**Comment by todonovan** [comment]
Just noting that I am experiencing an issue with VS Code performance -- 90%+ CPU, high memory usage + memory leak -- and the Developer Tools console shows an endless stream of these FsEvent.FsWatcher._handle.onchange errors. (In the process of writing this message I've received over 100,000 of them.) It is making code barely usable right now. Usually tends to appear after I've woken the PC up from sleep mode.

Appreciate the work that's been done so far, and I hope to see a fix from upstream soon.

**Comment by say25** [comment]
Assuming this is fixed as we have since done multiple major Electron version upgrades.
