### ISSUE TITLE
Keyboard shortcut to switch themes

### ISSUE THREAD

**Issue by dwhieb** [desktop/desktop#7128]
**Please describe the problem you think should be solved**

Switching between the light and dark themes currently requires navigating through a menu and tabs (File > Options > Appearance > Light/Dark). This is somewhat tedious for developers who switch themes often (for example, depending on time of day or lighting conditions).

**[Optional] Do you have any potential solutions in mind?**

One solution is to add a keyboard shortcut to switch between themes. A suggested shortcut might be `Alt+Shift+D`. This is the shortcut used to activate the Dark Reader plugin in Chrome, and so may be familiar to many users. Other possibilities might be `Ctrl+Shift+T` or `Ctrl+Alt+T`.

**Comment by lee-dohm** [comment]
Thanks for the suggestion.

There are already multiple theme switching packages, including the [theme-switch package](https://atom.io/packages/theme-switch) which makes it very easy to add key bindings to multiple theme switching possibilities.

I hope that helps!

**Comment by billygriffin** [comment]
Hi @dwhieb, thanks so much for the issue. macOS support automatically switching between themes based on the OS-level settings, but unfortunately Windows doesn't have that same luxury yet. We're open to considering this if it's something we hear more demand from other Windows users, but we typically don't add keyboard shortcuts based on a single request. I am curious how frequently during a given day you are changing themes, if you don't mind sharing. For now, I'm going to close this issue, but again we're totally open to considering this if we feel like it would benefit a lot of folks.

**Comment by dwhieb** [comment]
Thanks @billygriffin! That makes sense to me. I'll cross my fingers that more people like this issue!

To answer your question: I switch themes 2-4 times a day. Once in the morning, once in the evening, and twice again if I happen to be working in a particularly light or dark environment.

I _think_ Windows 10 does support OS-level theme switching, although maybe this is just limited to Microsoft apps. For example, Microsoft's Calendar, Mail, and Todo apps have an option to change themes based on whether the default app mode for my computer is Light or Dark. I love this feature and use it with any apps that allow it.
