### ISSUE TITLE
surface the current repository's group higher in the repository list

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#7134]
Motivated by #6460 
This is a sub-feature tracking issue.

The idea here is to move the group of the current repository to the top of the groups list (right after [the recent group](https://github.com/desktop/desktop/issues/7132)). This is also meant to facilitate users switching between related repos more easily.

As you can see in this mockup (thanks @niik!), the `desktop` group is first after recent because the `desktop` repo inside of it is currently selected. (Otherwise it would be further down the list alphabetically.)
![Recents mockup reproduction](https://user-images.githubusercontent.com/964912/54762562-9bff3880-4bb1-11e9-92b1-32b2aadc5b55.png)

_Credit to @feministy for this idea!_ 🌈 🐑

**Comment by outofambit** [comment]
So, after some consideration and prototyping in #7157, I won't be moving forward on this one. The concept is great (and I was really excited about it), but in practice it generates too much reordering in the list. It was hard for me to understand what was happening in using it (even with the context of having built it). I think this might be more successful with animation (but even then animating a large chunk of a list might also be jarring).

**Comment by tierninho** [comment]
One thought would be to decouple the Recent grouping from the Repo list and add it instead to the Repository menu similar to how the Mac OS does it for "Recent Folders":

<img width="551" alt="Screen Shot 2019-03-26 at 8 44 05 AM" src="https://user-images.githubusercontent.com/14828183/55024625-553f8300-4fa3-11e9-8148-b5e86023e90d.png">
