### ISSUE TITLE
Disable Rebase option in Repo menu if only one branch

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7137]
If a repo has only one branch, then we should disable the Rebase option in the Repo menu as it serves no purpose. 

![image](https://user-images.githubusercontent.com/14828183/54791396-cf57bc80-4bdd-11e9-9c9a-87cb9e8893ac.png)

24c697c144, mac

**Comment by shiftkey** [comment]
We've not disabled the related menu items for two previous features in this area:

 - 'Compare to Branch'
 - 'Merge into Current Branch'

I'd be 👍 to exploring this further, but I don't think it's a blocker for 1.7.0 (it would open the dialog and not let you do proceed with the rebase).

**Comment by billygriffin** [comment]
Agreed, think it's fine for now. It's unclear to me why someone would try that, and doesn't seem like it has the potential to put people in a bad spot.
