### ISSUE TITLE
"Push" menu item should say "Force Push" when you can only force push

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7138]
When a `force push origin` is inflight, the pull menu option is available to be clicked. Not sure what the correct resolution is, perhaps disable the menu option or do we allow the user to stash? I defer to the dev team for this as the error messaging is conflicting. 

Otherwise the end result is:
![image](https://user-images.githubusercontent.com/14828183/54793046-c1596a00-4be4-11e9-982f-8e55312230ab.png)

Edit (5/1): We're going to keep the menu items enabled for now, but we have #7017 tracking those more specifically as we iterate on this. For this issue to be closed specifically, we need to update the "Push" menu item to "Force Push" when the user is in that state after rebase.

24c697c144, mac

**Comment by tierninho** [comment]
Also, if you edit an existing file, and then try to rebase into current branch, you get a similar error message. 

<img width="840" alt="Screen Shot 2019-03-22 at 2 53 06 PM" src="https://user-images.githubusercontent.com/14828183/54859521-39419600-4cb2-11e9-8658-1f2d0fd6ea71.png">

**Comment by billygriffin** [comment]
Updated the initial issue and issue title after talking with @shiftkey and @nerdneha today to indicate that to close this issue, we'll only need to update the "Push" menu item to "Force push" when a user is in that state.

**Comment by shiftkey** [comment]
The other feedback in this issue will be incorporated into #7017
