### ISSUE TITLE
when aborted/completed rebase outside of app, it should complete flow and enable menus

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7140]
If you open a rebase conflict, then use the `git rebase --skip` command to push through every conflict, the top nav menu remains in the same disabled state as if it still were in the rebase conflict. 

Example:
<img width="195" alt="Screen Shot 2019-03-21 at 2 51 55 PM" src="https://user-images.githubusercontent.com/14828183/54793905-e4861880-4be8-11e9-836b-138f7286a569.png">

24c697c144, mac

**Comment by shiftkey** [comment]
Yep, the app should detect when the rebase is aborted outside the app when you refocus the app. I'll add this as a test case to #7117 and confirm this is working as expected.
