### ISSUE TITLE
[Idea] Git Updater

### ISSUE THREAD

**Issue by DemonRem** [desktop/desktop#7144]
guys maybe there a way to update local repo from remote repo?

**Comment by steveward** [comment]
Thanks for contributing @DemonRem. 

> guys maybe there a way to update local repo from remote repo?

You can check for any new changes in the remote repository by clicking the `Fetch origin` button in GitHub Desktop. If there are new changes that can be pulled down from the remote repository you will see the `Pull origin` button, which will pull down those changes and merge them into your local branch. You can read more about this in our help documentation:

https://help.github.com/en/desktop/contributing-to-projects/syncing-your-branch

I'm going to close this issue out, but please let me know if you have any other questions!
