### ISSUE TITLE
Missing the visual represntation

### ISSUE THREAD

**Issue by Charles92011** [desktop/desktop#7145]
I just upgraded from 3.3.6.1, and the reason I was dragging my feat is because of this feature:
![image](https://user-images.githubusercontent.com/6334019/54827496-5e60e500-4c6f-11e9-8644-5a4e2c90e566.png)
This visual graph of commits, branches and pulls makes it so easy to see, at a glance, what's going on.
Why was this excluded from more recent versions?

**Comment by steveward** [comment]
Thanks for contributing @Charles92011! We are tracking feedback about the comparison graph in https://github.com/desktop/desktop/issues/1634, so I am going to close this out. Please feel free to add any feedback you have in that issue.
