### ISSUE TITLE
Request To Change Background Color On App Startup

### ISSUE THREAD

**Issue by TheRealDannyyy** [desktop/desktop#7156]
**Problem Description:**
I'm using the GitHub Desktop app for quite a while now and enjoy working with it. As a user of the dark theme, it bothers me that the desktop app starts with a blinding, white background.

**How To Reproduce:**
1. Run GitHub Desktop App (optional: with "dark theme" selected)
2. Notice bright white background during loading process
3. Enjoy working with GitHub and its dark theme

**Request:**
Changing the background color during the startup loading process to a darker color. This can be something based on the color palette used for the dark theme ([example color](https://www.colorhexa.com/141414)).

**General Info:**
- Windows 7 SP1
- GitHub Desktop Version 1.6.5

_Cheers!_

**Comment by shiftkey** [comment]
@TheRealDannyyy thanks for the feedback! We're tracking this in an earlier issue #5631 which has some extra details. Please follow along with that discussion.

**Comment by TheRealDannyyy** [comment]
Sorry must've missed that one. Thanks for the heads up!
