### ISSUE TITLE
add option to disable githooks when committing

### ISSUE THREAD

**Issue by waghcwb** [desktop/desktop#7158]
**Please describe the problem you think should be solved**
It would be nice if we have an option to enable/disable githooks on commit.

**Comment by shiftkey** [comment]
@waghcwb thanks for the suggestion!

Are you able to elaborate on the scenarios or situations where you find yourself needing this? This would be great to help us understand your use case better...

**Comment by waghcwb** [comment]
@shiftkey,

Yes.

We have a project running with [NuxtJS](https://nuxtjs.org), and we have `git-hooks` to run the [`prettier`](https://prettier.io/) tool that normalize our source code.

Our project is big and have a lot of source files, and the script that run `prettier` doesn't filter only git staged files, so we need to wait a long time until prettier finish its job.

Sometimes we need to make a quick commit without running the `githooks`, and when using Github Desktop we need to wait much long than in CLI.

That's why I think would be nice have an option to disable `githooks`.

Sorry for bad english..

**Comment by shiftkey** [comment]
> Sometimes we need to make a quick commit without running the `githooks`, and when using Github Desktop we need to wait much long than in CLI.

I worry about providing escape hatches like that appear to speed things up.

Imagine a scenario where we have this option and the user ends up inadvertently crafting an incorrect commit which the commit hooks were designed to catch. The time saved here would be lost when the user then pushes the commits, the CI checks fail, and they have make another commit to get back to a good place.

I'm interested in hearing about other cases in this vein, but I'm not currently convinced that this would be helpful for building good Git habits with our users. 

cc @desktop/product for any other input

**Comment by billygriffin** [comment]
Thanks so much @waghcwb, I really appreciate your thoughtful response. And thanks for the additional context @shiftkey. I think I'm in agreement, especially without a lot of evidence that others also struggle with this problem. The more we allow for divergence from the expected flow, the easier it is for users to get into bad spots without realizing it or having to constantly remember all their configuration settings. For now, I'm going to close this issue to indicate that it's not something we intend to support, but if you or others have thoughts on why we might want to reconsider, we're always happy to revisit any decision. Thanks again!

**Comment by omzy** [comment]
I have a similar requirement in that our repositories use a `post-checkout` hook. So everytime I switch branches in GitHub Desktop it runs this hook. The contents of this hook contains a `php` script call. However my PHP environment is within Vagrant and thus I get the error:

![image](https://user-images.githubusercontent.com/8927010/68598323-7b645580-0496-11ea-9193-2a079fce790e.png)

I don't want to remove the command from the hook as I still want it to run when I use `git checkout` within Vagrant.

What would be useful here is an option to disable hooks. The option should sit under the "Repository Settings dialog", as it should be a per-repository setting.

**Comment by PeterTCormack** [comment]
I'm also having difficulty without this feature. Every time I try to commit, I see the following "error":
![github desktop husky error](https://user-images.githubusercontent.com/64870309/113049106-1c20e700-9158-11eb-9dde-248315914102.jpg)
My coworkers say it's not an error, just pre-commit hooks, and I should use `--no-verify` to skip them. But, I can't seem to do that in Github Desktop, so it's very frustrating. Any ideas on how I can handle this situation (without using the console)?

**Comment by Sathvik-Shanmugam** [comment]
> Thanks so much @waghcwb, I really appreciate your thoughtful response. And thanks for the additional context @shiftkey. I think I'm in agreement, especially without a lot of evidence that others also struggle with this problem. The more we allow for divergence from the expected flow, the easier it is for users to get into bad spots without realizing it or having to constantly remember all their configuration settings. For now, I'm going to close this issue to indicate that it's not something we intend to support, but if you or others have thoughts on why we might want to reconsider, we're always happy to revisit any decision. Thanks again!

@billygriffin Any idea of revisiting this? Adding a checkbox in the preferences to enable or disable checking githooks would be a lot better.

**Comment by Huluti** [comment]
![image](https://user-images.githubusercontent.com/5782198/167904837-f7b55b1f-c5b6-45c9-9a97-fad8ea7d8be8.png)
Same request because our githooks don't work in GitHub desktop

**Comment by shruti-paranjape** [comment]
Same, or please advice how to by-pass.
<img width="688" alt="Screenshot 2023-01-16 at 5 05 25 PM" src="https://user-images.githubusercontent.com/99330768/212669231-e35325d0-21a9-4aed-98a8-71fc952780c6.png">

**Comment by Kulu-M** [comment]
This is really annoying, that there is no bypass/ignore function.

**Comment by thomas-robinpowered** [comment]
This is definitely something you guys should add 👍 

adding a setting to make `-no-verify` the default commit behavior is a no brainer.

More power to the users and if people are worried about their getting into a bad state they can deal leave the commit hooks on.

**Comment by omzy** [comment]
Over 6 years have passed and this problem still exists. I use WSL2 as my development environment and I get the error popup every time I switch branches in GH Desktop because my repos have a `post-checkout` git-hook.

I know this particular issue is related to `pre-commit`, but I think the same principle applies. We just need the ability to disable all / certain git-hooks in GH Desktop.
