### ISSUE TITLE
another person is showing up in my repository

### ISSUE THREAD

**Issue by MathematicalLily** [desktop/desktop#7164]
## Version

* GitHub Desktop:

* Operating system:

**Comment by MathematicalLily** [comment]
dear billy,

thank you so much! it is a bizarre error. i am using the github desktop and
i used my friend bhoomikas computer but now when i push my programs to my
repository, bhoomika shows up instead of me (lily) and i am very confused.

best wishes,
lily

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by steveward** [comment]
@MathematicalLily this sounds like a case of the email address associated with the commits being linked to a different user account. Even though you logged in to GitHub Desktop with your account on the computer the local .gitconfig was not updated with the correct email address that is associated with your GitHub account. You can read more about this here:

https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user

You will want to check your Git configuration by going to the menu in Github Desktop and selecting `File` > `Options` > `Git` (Windows) or `GitHub Desktop` > `Preferences` > `Git` (macOS) to verify that the email address there matches an email address that is associated with your GitHub account. Let me know if that doesn't fix this issue for you.
