### ISSUE TITLE
differentiate draft PRs from normal PRs in the PR list

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#7170]
**Please describe the problem you think should be solved**

As part of reviewing #7163 I was looking at the PR list and wanted to call out that we render all the PR icons using a gray-ish colour:

<img width="383" src="https://user-images.githubusercontent.com/359239/55083974-30224180-5083-11e9-841a-b1d3385b733c.png">

This feels a bit weird now that [draft PRs](https://github.blog/changelog/2019-02-14-draft-pull-requests/) are a thing and GitHub The Website shows them in lighter gray, with green for PRs that are ready for review:

<img width="187" alt="Screen Shot 2019-03-27 at 11 24 30 AM" src="https://user-images.githubusercontent.com/359239/55084048-4af4b600-5083-11e9-9e6e-2f88fd8583b8.png">

**[Optional] Do you have any potential solutions in mind?**

I'd like to see us differentiate between draft PRs and ready-for-review PRs in the list, and align Desktop better with GitHub The Website.

**Comment by shiftkey** [comment]
Some extra information about how this would have helped me out currently...

I see this pull request without a commit status set:

<img width="406" src="https://user-images.githubusercontent.com/359239/55084478-0c133000-5084-11e9-9e95-fd74058df04e.png">

Is this a bug with the app? Is there something wrong with the PR? To verify this I:

 - checkout the PR branch
 - click **Branch** | **Show Pull Request** to [open it in the browser](https://github.com/nodejs/node/pull/26929)
 - see it's a draft PR

<img width="754"  src="https://user-images.githubusercontent.com/359239/55084806-5399bc00-5084-11e9-93b4-e611a2fe4f41.png">

This means the configured integrations for the repository will not check this PR in it's current state, which is the intended behaviour that this project has setup.

**Comment by tierninho** [comment]
+1 on this. We might want to consider grouping PRs (draft vs active) as well.
