### ISSUE TITLE
Invalid state encountered when rebase during merge conflict

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7172]
The rebase option is present during a manual merge conflict resolution. The `Rebase Current Branch` menu option should be disabled. Generally it is, but follow these steps and there is a case where it isn't.

 Repro Steps:
- Branch > Merge into current branch (make sure there are conflicted files)
- click `Merge...` button
- `x` the modal, subsequently banner pops up
- Branch > Rebase Current Branch

```
[App] invalid state encountered - rebase flow should not be used when merge conflicts found
```` 

sometimes this would show in the console as well as part of testing above:

```
install.ts:23 `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
remote: Anonymous access denied
fatal: Authentication failed for 'https://ghe.io/tierninho/Blah.git/'

(The error was parsed as 3: Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open preferences and verify that you're signed in with an account that has permission to access this repository.)
```

v ee09fac078, mac

**Comment by billygriffin** [comment]
@tierninho Thanks! What does the user actually see when they select that rebase menu option in this state?

**Comment by tierninho** [comment]
@billygriffin There is no UI change for the user. That includes no error messages.

**Comment by billygriffin** [comment]
So they click on the available rebase menu item and literally nothing happens? That _might_ be ok, if not completely ideal.

**Comment by tierninho** [comment]
Yes, that is correct. Feel free to close if needed.

**Comment by billygriffin** [comment]
I think since it doesn't actually engage the rebase, we're ok here from the user's perspective especially since it's such an edge case where you have to be trying to do something pretty strange. If it's a trivial change @shiftkey and you feel like it aligns with the direction you'd like, obviously don't let my closing this issue hold you back.

**Comment by shiftkey** [comment]
We're already tracking #7017 which is a more holistic view of these menu items, so I'm fine to cross-reference this example and close this out.
