### ISSUE TITLE
Cannot use git svn command

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#7173]
When I change the code to use "git svn clone ..." command in GitHub Desktop, I got the error below:
![image](https://user-images.githubusercontent.com/5396286/55135737-8072cf80-5167-11e9-98e7-03894fe01cf7.png)

And then I check the git executable in dugite node module, I still get the error:
![image](https://user-images.githubusercontent.com/5396286/55135814-b021d780-5167-11e9-8272-71bc726eba97.png)

But when I use the git installed on my machine, it worked, and check the git executable also work:
![image](https://user-images.githubusercontent.com/5396286/55135919-ecedce80-5167-11e9-9398-c984c1179130.png)

Do you know why and how can I use git svn command in GitHub Desktop? Thanks

**Comment by shiftkey** [comment]
Moving this discussion to https://github.com/desktop/dugite-native/issues/236 which is the package responsible for our embedded Git.
