### ISSUE TITLE
Inconsistent behavior for Recent repo grouping

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7176]
When moving between repos, when the Recent segment is present, I noticed the current repo is sometimes in the list and sometimes not. The inconsistency could be by design, but wanted to reference it here. 

❓Note: almost the same issue as: https://github.com/desktop/desktop/pull/7130#pullrequestreview-217857237 which was fixed?

#### Reproduce:
- Prerequisite: Make sure Recent segment is present in repo list, plus a few more repos

#### Scenario 1)
- Select a repo **not** in the Recent list = it doesn't get added to the Recent list (by design?)

#### Scenario 2)
- Select a repo **not** in the Recent list = it doesn't get added to the Recent list. Select the same repo again = it is now added to the Recent list.

#### Scenario 3)
- Select a repo **not** in the Recent list = it doesn't get added to the Recent list. Select the same repo again = it is now added to the Recent list. By repeating this a few times, I managed to get the Recent list down to 4 repos and even 3 repos.

<img width="227" alt="Screen Shot 2019-03-28 at 1 59 51 PM" src="https://user-images.githubusercontent.com/14828183/55200333-c75dc680-5161-11e9-9a96-b87a3b7e6273.png">
<img width="214" alt="Screen Shot 2019-03-28 at 2 40 04 PM" src="https://user-images.githubusercontent.com/14828183/55201509-705af000-5167-11e9-9ece-bb47bce341fd.png">

Looking at these, I believe the logic is "always added the repo last used, not currently used".

v1.7.0-beta1, mac

**Comment by billygriffin** [comment]
@tierninho The logic is indeed to use the last repos used that are *not* the current repo, with the idea being that the current repo is selected and therefore not as relevant for navigating amongst the repos you've used most recently (since you're already on it). When @outofambit and I discussed this though, we could see it going either way. It's tricky for me to tell from your examples whether given that logic, is there still a problem?

**Comment by tierninho** [comment]
Ok, I suspected it the logic was meant to be this way. I still suggest looking at scenario 2 and 3 as they may be bugs or at least not intended situations.

**Comment by outofambit** [comment]
this is a good catch @tierninho, thank you! i didn't consider this case in my logic

**Comment by tidy-dev** [comment]
I am unable to reproduce getting the recent repro list shorter. Bouncing between 2 didn't seem to do anything and click one multiple times didn't seem to add it to the list. I believe this is not longer an issue.
