### ISSUE TITLE
Recent repositories is annoying. Make it optional

### ISSUE THREAD

**Issue by IdanAdar** [desktop/desktop#7178]
Title says it all.

**Comment by b0810** [comment]
Bonjour ++prenom++,, 

Vous cherchez un nouveau site pouvant vous aider à gagner des millions au bout de 3 mois de travail acharné? 

Vous tombez bien parce que j"ai un tout nouveau site qui peut vous générer des millions de dollars en trois mois.
Cliquez sur ce lien si vous le voulez bien Builderall Leverage Affiliate System | Builderall Leveraged Affiliate System

| 
| 
|  | 
Builderall Leverage Affiliate System | Builderall Leveraged Affiliate Sy...

Builderall Business's Leveraged Affiliate System gives you a leveraged gain and solid recurring income based on ...
 |

 |

 |



Cordialement


Borath YUN




Envoyé depuis Yahoo Mail. Obtenir l’application 

    Le vendredi 29 mars 2019 à 05:24:19 UTC+1, Idan Adar <notifications@github.com> a écrit :  
 
 
Title says it all.

**Comment by shiftkey** [comment]
@IdanAdar thanks for the feedback. I'm going to fold this into our tracking issue about these changes #6460.

**Comment by b0810** [comment]
Bonjour ++prenom++, Regardez ce que j'ai fait pour vous depuis quelques temps et vous refusez encore de nous acheter ce site, mais heureusement qu'il n'y ait que quelques uns d'entre vous, d'autres ont commencé maintenant à s'inscrire sur mon site pour un abonnement mensuel de 44,90€, Pourquoi pas vous ? Bravo mes amis, quand on est ami, on devrait s'entraider non ? Sinon vous ne serez pas mon ami et pourtant je vous adore !Mais changeons notre pensée sur les autres du moment que l'on est gentil avec vous, vous devez leur rendre la pareille, n'ayez jamais cette mauvaise idée de nous tuer, nous massacrer parce que l'on est plus riche que vous parce que peut être c'est votre paresse qui cause votre pauvreté, ce n'est pas de notre faute même si on vous fait croire que nous sommes des étrangers que l'on est votre pire ennemi et que l'on doit mourir avec vous, dans votre attentat terroriste à la con?  Vous nous tuez, mais vous aussi vous mourez et descendrez vite en enfer pour y subir votre punition divine, brûler en enfer des siècles et des siècles mais ceux qui vous ont éduqué pour faire cet acte odieux vivent leur vie tranquille avec leur famille, le pensez vous ? Ne vous faites pas manipuler comme un imbécile sans cervelle pour réfléchir et comprendre ?Laissez nous vivre notre vie !https://affilie-fr-builderall.location-builderall.comhttps://checkout-fr-44.location-builderall.com/?slug=builderall-eur-commercial-44&sd=checkout-fr-44https://page-fr-paiement.location-builderall.com/planshttps://app.mailjet.com/templates/transactionalhttps://app.mailjet.com/templates/marketinghttps://app.mailjet.com/templates/automationchoco upgrade chocolateySet-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')https://eb4.co/83ac0e82https://github.com/settings/emailshttps://github.com/settings/adminhttps://rubyinstaller.org/downloads/$ ssh-keygen -t rsa -b 4096 -C "borathyun@location-builderall.com"Cordialement,borathyunPDG : 123marketing
