### ISSUE TITLE
Développement 

### ISSUE THREAD

**Issue by kkayri** [desktop/desktop#7179]
Bon jour je veux savoir comment peut-on monter une vidéo

**Comment by b0810** [comment]
bonjour
moi aussi je veux que tu achètes mon nouveau site en cliquant sur ce lien et payer la somme de 44,90€ d'abord avant de demander quoi que ce soit https://location-builderaml.comMerci pour ton achat borath Yun

Envoyé depuis Yahoo Mail pour Android 
 
  Le ven., mars 29, 2019 à 9:50, kkayri<notifications@github.com> a écrit :   
Bon jour je veux savoir comment peut-on monter une vidéo

**Comment by shiftkey** [comment]
@kkayri this is the issue tracker for GitHub Desktop, and I believe your question is outside of the scope of the project. Please open [a new issue](https://github.com/desktop/desktop/issues/new/choose) and fill out the template if you do have feedback about Desktop.
