### ISSUE TITLE
revert a commit while keeping changes

### ISSUE THREAD

**Issue by marcospgp** [desktop/desktop#7180]
Sometimes I accidentally commit an additional file and find myself having to google one more time the exact syntax of the `git reset --soft HEAD~1` command.

This command undoes the latest commit while keeping the changes.

It would be great if Github for Windows had this functionality through the UI! Not necessarily undoing the latest commit, maybe instead being able to undo an arbitrary commit.

Thanks!

**Comment by shiftkey** [comment]
@marcospgp thanks for the suggestion. I'm curious about this part of how you find yourself stuck after committing:

> Sometimes I accidentally commit an additional file and find myself having to google one more time the exact syntax of the `git reset --soft HEAD~1` command.

This feels like it overlaps with the intent behind our "Undo" button that sits below the commit form when you have local commits that haven't been published to the remote repository:

<img width="485" src="https://user-images.githubusercontent.com/359239/55236470-c6cf3980-520e-11e9-8e04-16ffc326de72.png">

What this does, when you click "Undo", is restore the changes from the commit into your working directory, and restore the commit message from the previous commit:

<img width="445" src="https://user-images.githubusercontent.com/359239/55236509-de0e2700-520e-11e9-9e32-9309bf82d5bd.png">

We felt this was a nice way balance to help users who made a mistake with a commit to quickly save face, and I'm curious how your workflow differs that means this isn't helpful.

I'm also curious about this comment:

> It would be great if Github for Windows had this functionality through the UI! Not necessarily undoing the latest commit, maybe instead being able to undo an arbitrary commit.

But we also have the ability to revert a commit from the UI, so I'm not sure how to reconcile these two things:

<img width="457" src="https://user-images.githubusercontent.com/359239/55236639-2a596700-520f-11e9-943b-99cd721c08da.png">


Are you able to share more about your workflow and how it relates to these features?

**Comment by marcospgp** [comment]
I missed the undo, and I actually think that works perfectly.

Does it fade away after a short interval? I might have missed it because it was hard to notice.

**Comment by shiftkey** [comment]
It doesn't fade away after a period of time, but it might be hard to notice because the button blends into the rest of the form. cc @desktop/design for :eyes: and thoughts.

I'm going to tweak this discussion to focus on that "Undo" form - thanks for the clarifying details @marcospgp!

**Comment by billygriffin** [comment]
@marcospgp @shiftkey Could the confusion be that the Undo button only exists for commits that are still only local? Once they’ve been pushed to the remote, you can no longer click “Undo,” right?

We’ve talked about the visibility and prominence of Undo a bit previously in a different issue (that I can’t find right now), but I’m interested in whether that might have caused you not to see it.

**Comment by shiftkey** [comment]
@marcospgp it doesn't fade away after a period of time, but it might be hard to notice because the button and the space itself blends into the rest of the commit form. cc @desktop/design for :eyes: and thoughts.

@billygriffin 

> Once they’ve been pushed to the remote, you can no longer click “Undo,” right?

Correct, the top local-only commit on the current branch will appear here.

> We’ve talked about the visibility and prominence of Undo a bit previously in a different issue (that I can’t find right now), but I’m interested in whether that might have caused you not to see it.

I think this might be https://github.com/desktop/desktop/issues/6901? If so, I can fold this feedback into that issue to prevent duplicate issues relating to the same problem.

**Comment by marcospgp** [comment]
There is no confusion as to the unfeasability of undoing a commit after pushing it (though it is possible, it would then require force pushing so better not to allow that through the UI).

**Comment by marcospgp** [comment]
There is no confusion as to the unfeasability of undoing a commit after pushing it (though it is possible, it would then require force pushing so better not to allow that through the UI).

**Comment by shiftkey** [comment]
I'm going to bump #6901 because I think making that more visible to the user would have helped in this situation.
