### ISSUE TITLE
Archived Repositories

### ISSUE THREAD

**Issue by kae36** [desktop/desktop#7183]
This comment/issue is really talking about the GitHub Desktop app (I'm using Windows) and how it displays repositories when the "Clone repository..." menu item is used under the "File" menu with repositories marked on the github.com website as archived.

Is there a way to somehow mark a repository in the list of clone-able repositories as "Archived" so that when someone tries to clone a remote GITHUB repository in the desktop app that it's clear that the GITHUB archive in the list has been marked as "archived" on GITHUB?  I don't know how the "archived" flag works in GITHUB, so I don't know if there is a way to tell if a repository has been archived, but the GITHUB website shows an "archived" status when a repository is archived.

On the GITHUB website, archived repositories have a little box with the word archived next to the repository name 
![image](https://user-images.githubusercontent.com/1879639/55260964-19751980-5240-11e9-87b3-c3d3e9c6ffb2.png)

This would be useful as either an option to show/hide archived repositories or maybe some kind of mark on the repository list to let users know that the repository was archived.  I still want to be able to clone a repository because I still want to have access to the code, but some sign that the repository has been archived would be helpful.

Thanks for listening.

**Comment by tierninho** [comment]
@kae36 Thanks for reaching out and filing this issue! Sorry if this is giving you in trouble or adding confusion.

Overall it is a good suggestion for an enhancement. Our only indication that a repo maybe archived is found in a generic error message, which appears after an action if performed. For example:

<img width="595" alt="Screen Shot 2019-03-29 at 11 20 07 AM" src="https://user-images.githubusercontent.com/14828183/55263763-38f74c80-5216-11e9-8bca-65fb6e106f4e.png">
 
I will let other team members weigh in as we are in the midst of adjusting the discovery of repos and this may tie into https://github.com/desktop/desktop/issues/6460.

**Comment by niik** [comment]
Thanks for opening this @kae36! I agree with @tierninho that this could be a worthwhile inclusion. I'm gonna assign this to myself so that I can bring it up in our next planning meeting.

**Comment by peterennis** [comment]
I just ran into exactly this issue!
