### ISSUE TITLE
Add keyboard shortcuts to Help menu

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7184]
Based on a convo with an experienced Desktop user, we ought to add a Keyboard shortcut link to the Help menu, as it would beneficial to see an overview of all the commands. 

Even though we have the shortcut mentions sprinkled throughout the application, it is not always obvious and can be easily overlooked.

All the shortcuts were just flushed out into an internal document, so now is a good time to consider it. 

cc @billygriffin for input

**Comment by billygriffin** [comment]
@tierninho This sounds great to me! Is your suggestion to create a doc in the repo that outlines all the keyboard shortcuts and we link to it from the `Help` menu?

**Comment by tierninho** [comment]
Yes, but I am open to suggestions. 

However, if the Help docs team is adding a page for the keyboard shortcuts, then let's link there.

**Comment by tierninho** [comment]
Adding <placeholder> for link to public doc, when ready.

**Comment by KennethSweezy** [comment]
While I do agree that having a list of all of the keyboard shortcuts in a document is a good idea. Would it not be better for the user if we had a dialog box that lists all of the shortcuts?

**Comment by billygriffin** [comment]
@KennethSweezy Thanks! Since we currently have no docs around it, I'd love to start with public documentation even if it takes users out of the app, and then go from there. I agree that ideally it would live in-app, but that doesn't feel like a high priority.
