### ISSUE TITLE
Fails to detect Log folder in Visual Studio C# Project Repository

### ISSUE THREAD

**Issue by MattMcManis** [desktop/desktop#7189]
## Description

In my C# project, I had a folder named `Log` with some `.cs` and `.xaml` files in it. They were for my program's Log Console, and not a temporary log file generated by Visual Studio.

GitHub Desktop fails to detect the folder because it has the name `Log`. I didn't know but I never pushed those files to GitHub. Someone notified me when they couldn't compile the program because the files were missing.

This is my `.gitignore` https://pastebin.com/raw/gjnSNuKW
I only see a `*.log` in there, but that is for a file extension.

## Version

* GitHub Desktop: 1.6.5

* Operating system: Windows 10

## Steps to Reproduce

1. Create a Visual Studio C# Project Repository
2. Create a folder named `Log`
3. Add a text file to it
4. Does GitHub Desktop detect the folder and file?

### Expected Behavior

GitHub Desktop to detect and upload the `Log` folder and files

### Actual Behavior

GitHub Desktop does not detect the `Log` folder or files

**Comment by steveward** [comment]
Thanks for the report @MattMcManis. It does look like log directories are being ignored -- it's the last entry in `Build results`:

```
# Build results
[Ll]og/
```

If you remove that entry then files in that directory should no longer be ignored. I hope that helps!

I'm going to close this issue out, but please let me know if you run into any further issues.
