### ISSUE TITLE
Reused repo name causing issues

### ISSUE THREAD

**Issue by danqing** [desktop/desktop#7202]
Version 1.6.5 on macOS 10.14.4.

Say I have a repo named `danqing/repo1`, which is synced using GH Desktop. I rename it to `danqing/repo2`, and GH Desktop picks up the renaming (good). But then if I create another repo named `danqing/repo1` and try to clone it, Desktop still renames it to `danqing/repo2`, and now I end up with 2 `danqing/repo2`s in the app.

This is likely due to some caching of the redirect that GitHub does when you rename a repo and the old name is not being used.

**Comment by shiftkey** [comment]
@danqing thanks for the feedback! This feels similar to #6927, and requires some investigation work to understand the behaviour given how repository redirects are implemented.

I'm going to add your case to that issue and close this out to prevent duplicates from appearing. Please follow along with that issue.
