### ISSUE TITLE
Amend flow for rebasing with uncommitted changes

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7205]
When rebasing with uncommitted changes, the user gets a "You have unstashed changes" warning as expected, however, the rebase modal reappears automatically thereafter and can lead to a novice user into a loop.

Suggestion would be to keep the rebase modal closed if the "You have unstashed changes" warning appears. 

We should also consider how this will change once staged changes feature is implemented. 

Repro:
- have uncommitted changes
- attempt rebase

8a02833985, mac

**Comment by shiftkey** [comment]
> When rebasing with uncommitted changes, the user gets a "You have unstashed changes" warning as expected

This warning doesn't appear if you have [`rebase.autoStash`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-rebaseautoStash) set in your Git config:

> When set to true, automatically create a temporary stash entry before the operation begins, and apply it after the operation ends. This means that you can run rebase on a dirty worktree. However, use with care: the final stash application after a successful rebase might result in non-trivial conflicts. This option can be overridden by the `--no-autostash` and `--autostash` options of git-rebase[1]. Defaults to false.

> Suggestion would be to keep the rebase modal closed if the "You have unstashed changes" warning appears.

I think we can detect this config config value and warn the user before they go too far down the rebase path. cc @desktop/product for additional thoughts about when we should interrupt the user.

**Comment by billygriffin** [comment]
It seems like what we do here might depend on how we handle stash conflicts? Until we know how that's going to behave, I'd be inclined to agree with @tierninho that we shouldn't currently allow rebase until the working directory is clean, but I don't feel super strongly about that.

When we have a story for handling stash conflicts, I'd be more inclined to just respect the git config for autostash and then the user can manage the conflicts when they occur after a rebase. Does that make sense? 

cc: @iAmWillShepherd (because working on stash conflicts) and @nerdneha

**Comment by shiftkey** [comment]
> When rebasing with uncommitted changes, the user gets a "You have unstashed changes" warning as expected, however, the rebase modal reappears automatically thereafter and can lead to a novice user into a loop.

@tierninho can you confirm this is the same as #7223? If so, I think we can close this out

> It seems like what we do here might depend on how we handle stash conflicts?

@billygriffin I think stash conflicts should "just work" if they appear after a rebase is completed if we can detect it right. I don't think we need to track extra work in this issue currently.

**Comment by tierninho** [comment]
Yes, a duplicate.
