### ISSUE TITLE
Ignored file reappears for rebase

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7206]
When adding a certain file type to the `.gitignore` file, and then rebasing, that file type reappears as part of the rebase flow. What are the expectations for this?

Steps to repro:
- add .txt file to gitignore and commit
- create new txt file and it should not be added to Changes list as expected
- attempt rebase and a txt file reappears

<img width="1086" alt="Screen Shot 2019-04-02 at 1 47 42 PM" src="https://user-images.githubusercontent.com/14828183/55443661-46327500-554f-11e9-9a9a-33df9ecc1555.png">
<img width="1144" alt="Screen Shot 2019-04-02 at 1 49 14 PM" src="https://user-images.githubusercontent.com/14828183/55443662-46327500-554f-11e9-95c5-c800b86bc356.png">

8a02833985, mac

**Comment by shiftkey** [comment]
@tierninho I'm curious what the `.gitignore` file contained in this screenshot (obscured by the dialog):

![](https://user-images.githubusercontent.com/14828183/55443662-46327500-554f-11e9-95c5-c800b86bc356.png)

As it's currently conflicted, Git might have problems parsing the file and the rule added is not included.

I'm not hugely worried about this case - untracked files should be skipped by the rebase unless specifically included, and #7006 will help make this clearer (it should default to excluding untracked files from the rebase).

**Comment by tierninho** [comment]
The contents of the `gitignore` file are here:

<img width="391" alt="Screen Shot 2019-04-03 at 8 00 24 AM" src="https://user-images.githubusercontent.com/14828183/55501652-9d375900-55e6-11e9-8c0e-4e7ba05d4ab5.png">

> I'm not hugely worried about this cas

👍

**Comment by shiftkey** [comment]
I looked into the most important case about this (a gitignore rule on the base branch potentially affecting the target branch commits) and verified that the commits on the target branch are preserved (the files are already tracked in Git when performing the rebase, which overrides any `.gitignore` changes) and that untracked files are handled correctly. 

With that and the work in https://github.com/desktop/desktop/pull/7377 to make clear that untracked files are excluded from the rebase, I think I'm fine to close this out.
