### ISSUE TITLE
怎么设置中文

### ISSUE THREAD

**Issue by xiongminghu** [desktop/desktop#7208]
**Please describe the problem you think should be solved**
A clear and concise description of what the problem is and who else might be impacted. Screenshots are encouraged.

Example:

> “When I run into a merge conflict, I don’t know where to go to resolve it. Anyone who works off of multiple branches will likely run into this problem at least occasionally.”

**[Optional] Do you have any potential solutions in mind?**
A clear and concise description of one or more solutions you think might solve the problem. Please include any considered drawbacks or tradeoffs, and how users might use your solution(s). Screenshots or mockups are helpful here!

**Comment by niik** [comment]
Google translated topic: 
![image](https://user-images.githubusercontent.com/634063/55469591-17c3a100-5606-11e9-9c64-37869bfcc0f2.png)

Hi @xiongminghu, I'm afraid GitHub Desktop does not currently support any other languages than English. This is something we're looking into for the future, but there is a large amount of work we'd have to do before we can and we don't have a timeline on when we will be able to make that investment.

## Auto translated response

嗨@xiongminghu，我担心GitHub Desktop目前不支持除英语以外的任何其他语言。 这是我们未来所关注的问题，但在我们可以做之前我们必须做大量的工作，而且我们没有时间表来确定何时可以进行投资。
