### ISSUE TITLE
Removing a repo crops Recent Repo list unintentionally

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7211]
As the current logic for the recent repo list is to spotlight the **last** three repos, and ignore the current repo, then when you remove a repo, the list is unintentionally reduced to two repos. 

We should account for such in the logic. 

<img width="293" alt="55368468-afea4a80-548d-11e9-92cd-c907ac2d1d91" src="https://user-images.githubusercontent.com/14828183/55501497-3a45c200-55e6-11e9-9531-62eed675c4fb.png">

Related to #7200 

f8a24c10bcbc3160bad6e441a149ed8a5b4f2761, mac

**Comment by tidy-dev** [comment]
This behavior is reproducible as of 3.4.5. However, I do not believe it would alarm a user if they removed a recent repository and the list shortened, and inversely if they removed a recent repository and another populated that may be initially confusing as the # of repos there didn't change after removal of one. The list populates back to 3 after interacting again with a repository not present in the list. We haven't received any user feedback of this being confusing so I going to close as not planned.
