### ISSUE TITLE
Linux version ?

### ISSUE THREAD

**Issue by jatin-cbs** [desktop/desktop#7215]
Where is the linux version of github desktop it was avilable on snap store and as a deb package on your website but now its not ? Has github now started to only focus on microsoft after acquisition ?

**Comment by niik** [comment]
Hi @jatin-cbs, thanks for opening this and for showing your interest in using GitHub Desktop on Linux. Please see [our written documentation for getting started with GitHub Desktop on Linux](https://github.com/desktop/desktop/blob/development/docs/contributing/linux-testing-and-you.md) as well as https://github.com/desktop/desktop/issues/1525 for the current status of packaging GitHub Desktop for Linux. There are also [unofficial builds](https://github.com/shiftkey/desktop/releases) available that you might want to take a look at.

I don't believe we've ever offered an official Linux package for GitHub Desktop on our website so I'm not sure what you're referring to but hopefully the resources I've linked to above will help you get started!
