### ISSUE TITLE
ampersand in windows username breaks command line

### ISSUE THREAD

**Issue by mtourne** [desktop/desktop#7225]
## Description
On windows a `&` in a user name seems to break certain functionalities

## Version
Github deskstop for windows 1.6.5

* Operating system:
Windows 10

## Steps to Reproduce
1. Clone a repo in username named a&b
2. publish repo it'll say c:\users\a command not found 

### Expected Behavior
the command line shouldn't be broken by a &

### Actual Behavior
impossible to publish

**Comment by niik** [comment]
Hey @mtourne, thanks for opening this!

I've been able to reproduce the problem you described

<img width="624" alt="image" src="https://user-images.githubusercontent.com/634063/55621340-81c27e80-579d-11e9-87e1-bdd1aa6e5545.png">

This is likely the same issue as @shiftkey was debugging in https://github.com/desktop/desktop/issues/2623#issuecomment-362161677.

Essentially this breaks `git push` for public repositories and all network related git operations for private repositories.

@mtourne As stated in the issue I linked to above the only known workaround for this is to rename the account to one that doesn't include `&`. Hopefully that's an option for you while we work to find a better solution.

**Comment by niik** [comment]
A little too late I found that we do have this documented in our [Known Issues](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789) document. Given that this is a known issue I'm going to close this issue for now but please let us know if the workaround is possible for you.
