### ISSUE TITLE
Move run directory

### ISSUE THREAD

**Issue by Nightenom** [desktop/desktop#7228]
I did not find a way to move github desktop entirely to external ssd. I moved app and repos but I can't move `%appdata%\GitHub Desktop`. Is there any way to do this (sorry if I failed to search it)?
If not, an app argument would be great

**Comment by niik** [comment]
Hi @Nightenom, unfortunately that's not currently supported. Electron (which we build Desktop upon) uses an installation framework called [Squirrel](https://github.com/squirrel/squirrel.windows) which governs where the application is installed. While it's possible that you could move the directory it would likely break automatic updates.

See also https://github.com/desktop/desktop/issues/1579.

**Comment by Nightenom** [comment]
This framework just died two days ago? but ok

**Comment by Nightenom** [comment]
<https://github.com/Squirrel/Squirrel.Windows/issues/712>
Seriously they give up freedom when they could just add a config option...
