### ISSUE TITLE
'View on Github' Availability For Commit Doesn't Update

### ISSUE THREAD

**Issue by dsanders11** [desktop/desktop#7232]
## Description

'View on Github' for commit in history does not update unless changing away from history tab and back. If you do a push from the history tab, or initiate a push then switch to the history tab before it completes, you won't be able to access 'View on Github' unless you leave the tab and come back.

## Version

* GitHub Desktop: 1.6.5

* Operating system:

## Steps to Reproduce

1. Make a commit
2. Go to history tab
3. Push changes
4. Right click on the commit

### Expected Behavior

'View on Github' should be clickable

### Actual Behavior

'View on Github' is greyed out

## Additional Information

This occurs because `isLocal` is passed as a static value to `CommitListItem` as a property, so it never updates.

A quick and dirty hack would be to make `isLocal` a function which when invoked runs the check, so it's always up-to-date. This works since the context menu is triggered by a user action.

However, that's not a great solution, and wouldn't help with future issues like #5873 (if it's ever closed) showing a stale state. The real solution needs to be reactive or subscribed so it updates correctly in all cases.

**Comment by outofambit** [comment]
Hi @dsanders11 thank you for taking the time to file this issue! This is a great writeup and I was able to reproduce this on my machine. Going to mark this as a bug.

How much pain is this issue causing for you?

**Comment by dsanders11** [comment]
> How much pain is this issue causing for you?

Little to none since I know about it and how to work around it. :-)

But it is indeed a bug so figured I'd file once I could reproduce and took a peek at the code and saw the cause.

As mentioned, it'd probably be a bigger pain point for new users in the future if there's more visual indication regarding local commits, but I agree at the moment it's low priority.

**Comment by outofambit** [comment]
> Little to none since I know about it and how to work around it. :-)

@dsanders11 haha fair enough! i completely agree that this will be more problematic for new users and is indeed a bug we should fix. (i mostly wanted to make sure i wasn't underestimating how much it was disrupting your workflow.) thank you again for writing this up and doing some investigation for us!

**Comment by steveward** [comment]
I was no longer able to reproduce this bug, so I'm going to close this issue out. If this is still an issue let us know and we can reopen it.

**Comment by dsanders11** [comment]
Confirmed this appears to be fixed. Thanks!
