### ISSUE TITLE
Dim window when using HDR on Windows 10

### ISSUE THREAD

**Issue by KyleNanakdewa** [desktop/desktop#7233]
## Description

The app window is displaying very dim when using an HDR monitor, and HDR enabled in Windows display settings.

The app is showing as an HDR app, so it gets HDR brightness instead of standard brightness. This seems to be the exact same issue faced by [VS Code](https://github.com/Microsoft/vscode/issues/68069) and [Signal](https://github.com/signalapp/Signal-Desktop/issues/3181) and seems like it might be a bug in the version of Chromium used in certain versions of Electron.

## Version

* GitHub Desktop: 1.6.5

* Operating system: Windows 10 version 1809 (October 2018 Update), build 17763.379

## Steps to Reproduce

1. Connect an HDR monitor to the PC
2. Enable HDR by going to Windows Settings > System > Display > turning on Play HDR games and apps

### Expected Behavior

The window should not be dim, it should be the same brightness as other windows.

### Actual Behavior

The window is significantly darker and is hard to read.

Here is a screenshot showing the difference. Top is the current behavior, bottom is a screenshot of what it looked like before I updated the app.

I had to take this picture with a camera, as an actual screenshot is not HDR, and therefore does not show the difference. 
Also note that this picture does not show it very well, the dim window is significantly dimmer in person, and very hard to read.
![image](https://user-images.githubusercontent.com/20824272/55674237-d3dbd080-587f-11e9-8e1e-be15b27a4add.png)

## Additional Information

This issue is only present on HDR monitors, running a recent version of Windows 10 (as HDR was not fully supported until April 2018, if I remember correctly). My specific monitor is an HP Pavilion Gaming 32 HDR monitor. Graphics card is an Nvidia GeForce GTX 1070. The two are connected over DisplayPort. HDR games work fine, with proper HDR colours and brightness.

### Logs

[2019-04-06.desktop.production.log](https://github.com/desktop/desktop/files/3050852/2019-04-06.desktop.production.log)

**Comment by shiftkey** [comment]
@KyleNanakdewa thanks for the report! It looks like there's a couple of options for us to address this:

 - upgrade to Electron 4, which seems to be what the Signal client did https://github.com/signalapp/Signal-Desktop/issues/3181#issuecomment-473990768
 - provide a environment override to change the runtime behaviour to let users force a certain color profile, similar to what VSCode did - https://github.com/Microsoft/vscode/issues/68069#issuecomment-472994404

I kind of favour the first option as it doesn't require users to mess around with their environment, but it requires upgrading us from Electron 3 to 4 (I'm not aware of blockers to this, it just requires QA time and planning to co-ordinate with our release schedule).

**Comment by shiftkey** [comment]
I'm going to close this out in favour of the Electron 4 upgrade issue #6888 - please follow along with that discussion.
