### ISSUE TITLE
Copy Path

### ISSUE THREAD

**Issue by gcoyle1** [desktop/desktop#7237]
**Please describe the problem you think should be solved**
A clear and concise description of what the problem is and who else might be impacted. Screenshots are encouraged.

Example:

> “When I run into a merge conflict, I don’t know where to go to resolve it. Anyone who works off of multiple branches will likely run into this problem at least occasionally.”

**[Optional] Do you have any potential solutions in mind?**
A clear and concise description of one or more solutions you think might solve the problem. Please include any considered drawbacks or tradeoffs, and how users might use your solution(s). Screenshots or mockups are helpful here!

**Comment by gcoyle1** [comment]
When I select "copy path," the full path is no longer copied.  In the past, I would select "copy path" and name.io/project_file/x.html, would be copied.  Now, when I select "copy path" only the project path is selected.  That is, I select "copy path" on the github interface and only project_file/x.html is copied.  Why has this changed?

**Comment by steveward** [comment]
@gcoyle1 thanks for contributing. This issue tracker is for GitHub Desktop -- for issues with GitHub the website you will need to reach out to support via the contact form:

https://github.com/contact

I'm going to close this out, but if you are having any issues with GitHub Desktop please let us know!
