### ISSUE TITLE
After Latest Update, GitHub Desktop Launches but UI Window is not Visible on MacOS Mojave v10.14.3 (18D109)

### ISSUE THREAD

**Issue by vallme2003** [desktop/desktop#7238]
## Description

Hi, I got an Automatic update to upgrade my Github Desktop which i am using it with my Enterprise Github, after which if i try to launch the App, the application window is not visible anymore.

I can see that the process in available in Taskbar and in Activity Monitor but the window is not visible. So far i have tried reinstallation with new version, still not able to see the UI.

## Version

* GitHub Desktop:

GitHub Desktop Version - v1.6.5
MacBook Pro (15-inch)
* Operating system: Mac OS Version - Mac OS Mojave v10.14.3 (18D109)

## Steps to Reproduce

List the steps to reproduce your issue **below** this comment
ex,
1. `Install GitHub Desktop v1.6.5`
1. `Launch Github Desktop`

### Expected Behavior

Expect to see Github Desktop UI

### Actual Behavior

Process shows up in taskbar but no UI to operate

**Comment by outofambit** [comment]
Hi @vallme2003, I'm sorry you're running into this and thanks for reaching out. @desktop/support can you help troubleshoot this?

**Comment by shiftkey** [comment]
@vallme2003 thanks for the report!

Would you be able to look in the logs and see if there's any interesting errors? These should be located at `~/Library/Application Support/GitHub Desktop/logs` and organized by date - check out the entries for the days you were seeing this issue...

**Comment by vallme2003** [comment]
@shiftkey I looked at the logs folder and the last log i see is on Apr 4th. And i see an Error related to Authentication since there was an Github Upgrade on my Org.

**Comment by vallme2003** [comment]
@desktop/support - Can you help troubleshoot this?

**Comment by vallme2003** [comment]
> Hi @vallme2003, I'm sorry you're running into this and thanks for reaching out. @desktop/support can you help troubleshoot this?

@outofambit I tagged the support - but github doesnt seem to recognize the handle

**Comment by vallme2003** [comment]
Able to get this resolved by Deleting '~/Library/Application Support/GitHub Desktop' and then doing a reinstall.

**Comment by billygriffin** [comment]
Thanks @vallme2003, glad you were able to get it resolved!
