### ISSUE TITLE
Feature request: Active repositories

### ISSUE THREAD

**Issue by Ameen-vatbox** [desktop/desktop#7239]
I currently have 20+ git repositories, but most of the time I work on 2-3 at the same time, and its hard to remember where did I make changes.

It would be nice and more effective to see in which repositories I have made uncommitted changes by adding an indicator near the repository name (star, or different color, etc...).
and also it would be nice to move it to the top of the list.

**Comment by niik** [comment]
Hi @Ameen-vatbox, thanks for opening this and giving us your feedback!

> and also it would be nice to move it to the top of the list.

This is currently being worked on by @outofambit and should make it into a release soon. See #7130 and #6460.

<img width="242" alt="image" src="https://user-images.githubusercontent.com/634063/55711362-ce4fc900-59ec-11e9-908c-7cf39ac239e0.png">

> It would be nice and more effective to see in which repositories I have made uncommitted changes by adding an indicator near the repository name (star, or different color, etc...).

This should exist in the production version already, what version of GitHub Desktop are you running at the moment? (you can check by clicking on the `GitHub Desktop -> About GitHub Desktop` menu if you're on macOS and `Help -> About` on Windows). Uncommitted changes are shown with a blue dot next to the repository name.

<img width="234" alt="image" src="https://user-images.githubusercontent.com/634063/55711257-a52f3880-59ec-11e9-800d-1f19841dd538.png">

Given that this is partially implemented with the final pieces coming soon I am going to close this issue but feel free to keep replying if there's something you feel like I didn't address.

**Comment by Ameen-vatbox** [comment]
I had a problem in updating the app for a while, so I re-installed it and this feature actually exists in the newer version.
Thank you.
