### ISSUE TITLE
Cannot Shelve/Stash changes

### ISSUE THREAD

**Issue by RichardTea** [desktop/desktop#7241]
Shelving/Stashing appears to be impossible.

This is a critical feature, without which Git is almost unusable as it is impossible to switch branches without either throwing away your work, or committing it.

**Comment by billygriffin** [comment]
@RichardTea Thanks for the feedback! We're actively working on this in #6107 and expect that our next big production release will have our first iteration. I'm going to close this issue as a duplicate but please feel free to follow along there, and thanks again! 😄
