### ISSUE TITLE
[Metrics] Working with uncommitted changes

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#7246]
In #6107, we're working to improve things for people with uncommitted changes when they're switching branches, and allowing them to stash their changes on their current branch if they want to just leave them there and come back to them. We want to measure several things to learn about the usage of the feature and whether it's successful.

#### 1. What percentage of the time do people bring their changes across to a different branch vs. stashing them in their current branch?

This helps us understand people's usage patterns and preferences around bringing work with them vs. leaving it on a branch to come back to. Our hypothesis is that it's very common for people want to stash work on their current branch when they're switching branches and that's what makes this feature valuable for them, but we want to validate that.

#### 2. What percentage of people always choose the same action (stash or bring work with them) vs. vary their choice when switching branches?

If an individual person almost always chooses the same option, potentially allowing them to default to that action or something might make sense.

#### 3. What percentage of time are people restoring the stash vs. deleting the stash vs. neither of those things? The total of these should equal the number of times users return to a branch that contains a stash.

This helps us understand whether the work users left behind on a branch is something they actually want to come back to, or whether they're just trying to get rid of it.

#### 4. Of the times people return to a branch that contains a stash, what percentage of the time is the stash viewed? 

This will help us learn whether the feature is discoverable and whether people actually care to see the changes they previously stashed on a branch.

#### 5. What percent of changes viewed are via clicking on the "Stashed changes" row directly vs. clicking on the prompt in the suggested next step? 

This is related to (4) above, and basically allows us to understand whether the stash icon itself is sufficient or whether a prompt to view the stash is helpful in increasing discoverability.

#### 6. How many times do users currently stash outside of Desktop, and can we demonstrate that supporting this shows a decline in that overall per-user number? 

This is intended to understand whether we are improving context-switching and allowing people to do more of their overall workflow in Desktop.

**I think if it's possible to get any of these metrics in before the beta, my priority order would be (6) and (4) because those are the ones where having baseline data would likely be most helpful.**

cc: @iAmWillShepherd @nerdneha @scottypate

**Comment by iAmWillShepherd** [comment]
> 5. How many times do users currently stash outside of Desktop, and can we demonstrate that supporting this shows a decline in that overall per-user number?

We can't currently answer this question with how stashing is implemented. Because we store no state, we get a list of stash entries every time there is a state change. While we can certainly count the number of stash entries not created in Desktop, we would always over count because we'd get the non-Desktop created entries every state change. So if a user has an existing stash entry created outside of Desktop, we would count that 1 entry every time state changes.

**Comment by billygriffin** [comment]
We met to take a stab at what success might look like. These are somewhat arbitrary targets but we're trying to get better at prospectively identifying what the minimum usage and value thresholds we'd like to see to call a given feature a success at solving the problems identified.

#### 1. Total stashes restored in Desktop / total stashes created in Desktop

This should be > 10% restored. Choosing to stash when switching branches is a signal that you might want to use the changes again that are in progress, and assuming you don't just abandon the branch, if fewer than 10% of these stashes are ever restored, then we need to better understand the workflow.

#### 2. Total stashes created outside of Desktop in a given period

This should be > 15% lower. This applies only to the subset of users who are *already* stashing outside of Desktop, but the idea is that with this new feature, people won't be forced to context switch to the command line many times when they need to stash.

#### 3. When switching branches and bringing changes with you, number of times that you hit an error message.

This should be > 50% lower. We expect that the way in which we implemented the ability to bring changes with you *should* provide a nicer experience and fewer error messages.
