### ISSUE TITLE
Commit Message Clears When Committing in Stages

### ISSUE THREAD

**Issue by say25** [desktop/desktop#7251]
## Description
Commit Message Clears When Committing

## Version
* GitHub Desktop: 1.7.0-beta2 (tested this still happens in 1.6.5)
* Operating system: Windows 10

## Steps to Reproduce
1. Change a number of files.
2. Commit a subset of files.
3. Start to commit more files and start writing a commit message and see that it is cleared.

### Expected Behavior
It doesn't clear my commit messages.

### Actual Behavior
It clears my commit messages.

## Additional Information
This generally happens more often during high system CPU and memory load.

**Comment by outofambit** [comment]
thanks for filing this @say25! (and sorry for the delayed response!) Sounds like this is a little race condition we need to fix.

**Comment by tierninho** [comment]
Another user running into this here: https://github.com/desktop/desktop/issues/10430
