### ISSUE TITLE
[rebasing] choosing manual conflict resolution method doesn't update modal UI

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#7255]
While in a rebase, I encountered a manual conflict. I chose a resolution method, but it wasn't reflected in the UI until I switched windows and came back to desktop.

(I have verified that this is an issue unique to the rebasing flow, as I was able to resolve a similar conflict in a merge.)

![gif](https://user-images.githubusercontent.com/964912/55901199-b3f92500-5b7d-11e9-9e2d-a643fe364466.gif)

repo used to test: https://github.com/outofambit/blegh-test.git
(branch from `master` and then rebase onto `newbie`)

**Comment by shiftkey** [comment]
I've been able to reproduce this on [`desktop/rebase-test-cases`](https://github.com/desktop/rebase-test-cases) using the [`4-manual-conflict-resolution`](https://github.com/desktop/rebase-test-cases/tree/4-manual-conflict-resolution-baseline/4-manual-conflict-resolution) test case. Hopefully I can get a fix together for the next beta.
