### ISSUE TITLE
[Stashing] Drop associated stash when branch is deleted

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#7264]
Stash entries are orphaned when the branch is deleted. While we could leave them around, we could run into issues if another branch is created with the same name as the one the stash was associated with. In order to avoid this, we should remove the associated stash along with the branch. 

Maybe it's worth alerting the user this will happen as well? 

cc/ @desktop/quality-assurance  @desktop/design

**Comment by tierninho** [comment]
> Maybe it's worth alerting the user this will happen as well?

Alerting the user would allow them to move the stash elsewhere, so I am in favor of it. 

We should also consider what happens when a branch is restored and an associated stash was present before the deletion.

**Comment by iAmWillShepherd** [comment]
@billygriffin and I have decided that it's safer to not delete stash entries. If the user does create a new branch with the same name, they can easily discard it.
