### ISSUE TITLE
[Stashing] Stash diff "flashes" when returning to Desktop app

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7276]
When opening your stashed changes and then leaving and returning to the application, the `id="stash-diff-viewer"` div flashes. I narrowed it down to this section:

<img width="843" alt="Screen Shot 2019-04-12 at 8 21 44 AM" src="https://user-images.githubusercontent.com/14828183/56058236-85558880-5cfc-11e9-9e10-4aabdf544742.png">

![Apr-12-2019 08-27-30](https://user-images.githubusercontent.com/14828183/56058348-da919a00-5cfc-11e9-9e96-073b139e4fba.gif)

I tried reproducing this using other features of the app, but seems to be only here.

686fbbc04f, mac

**Comment by outofambit** [comment]
@tierninho could you check if this is still present in https://github.com/desktop/desktop/pull/7210/commits/3353652b40a048f0843b438425e55b925cab593a? i think this has been fixed in https://github.com/desktop/desktop/pull/7267

**Comment by tierninho** [comment]
Flickering is gone 🎉

**Comment by outofambit** [comment]
Awesome! all the credit goes to @niik 😃
