### ISSUE TITLE
[Stashing] Use SentenceCase and string values for UncommittedChangesStrategy enum

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#7279]
This issue was brought up in https://github.com/desktop/desktop/pull/7210#discussion_r274673721.

https://github.com/desktop/desktop/blob/777c5110832a30a9cee05c32553923ec0fbf8b16/app/src/models/uncommitted-changes-strategy.ts#L1-L5

**What needs to change?**
1. Use sentence casing on each named constant
1. Use string values instead of numbers (implicit)

**Comment by ADustyOldMuffin** [comment]
I'd like to work on this if it's not already taken by someone. 

Just one question, by sentence casing you do mean [this](https://en.wiktionary.org/wiki/sentence_case) correct?

Thanks!

**Comment by shiftkey** [comment]
@ADustyOldMuffin apologies for the delay in replying.

Yes, this is available to work on.
Yes, you're on the right track.

Let us know if you have any other questions!
