### ISSUE TITLE
[Stashing] Overwriting stashes show old diff state

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#7280]
After creating a stash of a file, the diff of stashed file changes upon returning to the branch with an associated stash does not reflect what was just stashed. The diff seems to show old state.

**Repro steps**
1. Update the contents of an existing file
1. Stash changes on the current branch
1. Go back to branch stash was created on
1. View diff of stash (note its content)
1. Update the contents of the same file from step 1
1. Stash changes on the current branch
1. Go back to branch stash was created on
1. View diff of stash (note the content doesn't reflect what was just stashed

![2019-04-15 13 42 47](https://user-images.githubusercontent.com/1715082/56157191-81d43280-5f84-11e9-864d-2c21dfc2f14f.gif)
☝️I reloaded the app to force a state update because the previous stash entry's files were being show. After reload, the contents of the diff is correct.

**Comment by tierninho** [comment]
Ah, this might explain this as noted in https://github.com/desktop/desktop/pull/7210#issuecomment-482394496

> Getting instances of a cached file but it is hard to repro. If I reload the application, it goes away and correct stash remains. I think it may have to do with using the UI and also the cmd line... eventually Desktop get confused.

<img width="980" alt="56004948-a1f4b080-5c69-11e9-956f-36c2a7634f9d" src="https://user-images.githubusercontent.com/14828183/56064506-f2254e80-5d0d-11e9-8f99-952d3fddbc8a.png">

**Comment by outofambit** [comment]
@tierninho which commit of desktop was this last seen on?

**Comment by tierninho** [comment]
Was definitely on https://github.com/desktop/desktop/commit/686fbbc04f9b2c229ad98799dd0c4d63c8df5d01 and maybe even https://github.com/desktop/desktop/commit/5977a42c216ddcbf896c17948c7db35bbdd62dd7 but I do not recall seeing this issue in awhile.

**Comment by tierninho** [comment]
I can now see this issue on a4fa3940d1, as the reproduction steps were clarified.
