### ISSUE TITLE
[Stashing] Stashed changes disappear when the branch is renamed

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#7283]
This issue came back from @desktop/quality-assurance while testing https://github.com/desktop/desktop/pull/7210#issuecomment-482394496.

**Repro steps**
1. Create stash on branch
1. Rename branch

The stash will no longer be shown since we associate a stash to a branch when it's created. I'm not sure if this is a bug or if it's something we should be concerned about.

Thoughts?
cc/ @desktop/product

**Comment by billygriffin** [comment]
My sense is that in an ideal world, the name of the branch doesn’t have anything to do with the stash. In other words, ideally if you rename a branch you shouldn’t lose your stash on the branch. I don’t think this needs to hold up beta but would like to see it fixed. Open to thoughts from others though as well.

**Comment by iAmWillShepherd** [comment]
Maybe we can alert the user that this would cause  their stash to become no longer visible in desktop.

**Comment by shiftkey** [comment]
> Maybe we can alert the user that this would cause their stash to become no longer visible in desktop.

I'd be 👍 to exploring this, particularly as #7230 also explored warning when an existing stash will be overwritten

**Comment by outofambit** [comment]
it seems that the only way to edit the message associated with a stash is to pop and stash it again. this _should_ work in the majority of cases, but that can fail just like any time we attempt to pop a stash.

the core problem in the implementation is that we store the name of the branch a stash is associated with in the stash commit itself. i think its worth exploring a solution where we maintain a list of stash + branch name pairings in desktop's own persistent storage and update that when the branch name is changed.

**Comment by outofambit** [comment]
marking this priority 2 as it results in (recoverable) data loss for the user

**Comment by gowthamgts** [comment]
Today I faced this issue on `v2.1.3`. But, after renaming back to the older name, the "Stashed Changes" bar appeared below. Is this the intended behaviour?

**Comment by tierninho** [comment]
@gowthamgts Thanks for reaching out. This is the current logic for this feature.
