### ISSUE TITLE
[stashing] Error building trees and saving current index state

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7285]
Found a bug that prevents me from using the stashing changes feature. Each time you attempt to use it, I get an error in the logs, and the stash model progress indicator just spins. 

Here are the terminal cmds I did to get there:

```
➜  PRlist git:(master) ✗ git stash
Saved working directory and index state WIP on master: 3185a69 jjjj
➜  PRlist git:(aaa) git checkout aaa
Already on 'aaa'
Your branch is ahead of 'origin/aaa' by 2 commits.
  (use "git push" to publish your local commits)
➜  PRlist git:(aaa) git stash pop
CONFLICT (modify/delete): CHANGELOG.md deleted in Updated upstream and modified in Stashed changes. Version Stashed changes of CHANGELOG.md left in tree.
➜  PRlist git:(aaa) ✗ 
```

My current `git stash show` results in:

```
 CHANGELOG.md | 8 ++++++++
 1 file changed, 8 insertions(+)
```

LOGS:
```
debug: [ui] Executing getStashEntries: git log -g -z --pretty=%gd%x1F%H%x1F%gs refs/stash
debug: [ui] Executing createStashEntry: git stash push --include-untracked -m !!GitHub_Desktop<aaa>
error: [ui] `git stash push --include-untracked -m !!GitHub_Desktop<aaa>` exited with an unexpected code: 1.
CHANGELOG.md: needs merge
CHANGELOG.md: needs merge

CHANGELOG.md: unmerged (a209f58bc7f97df37100a4d99beff100c43835dd)
CHANGELOG.md: unmerged (6dfeffe0f28099470ccae40188139669c1b49948)
fatal: git-write-tree: error building trees
Cannot save the current index state
```

![Apr-12-2019 11-33-14](https://user-images.githubusercontent.com/14828183/56067496-0a4d9b80-5d17-11e9-98d7-12f6a7c31eae.gif)

3353652b40, mac

**Comment by tierninho** [comment]
More context: Created a new branch-B and tried to bring over a fresh changelog file from branch-A, but ran into this. Note changes went into stash and not the Changes column.

<img width="1132" alt="Screen Shot 2019-04-12 at 2 40 10 PM" src="https://user-images.githubusercontent.com/14828183/56072332-51e12100-5d31-11e9-8b84-ec8dfdf8555a.png">

5977a42c21, mac

**Comment by tierninho** [comment]
related error: 

```
Uncaught (in promise) GitError: 456 copy.txt: unmerged (dab621ca7151ce40740d359fc63db0cac2e2c405)
456 copy.txt: unmerged (e0a9f07f8c7b519da2e787d91e202c9c1ec724ac)
fatal: git-write-tree: error building trees
Cannot save the current index state
```

**Comment by outofambit** [comment]
@tierninho are you able to reproduce this on the latest beta? i'm not clear on the reproduction steps... are you executing those git commands and then trying to use stashing in desktop?

**Comment by tierninho** [comment]
@outofambit closing this as I believe it will ultimately will be fixed with https://github.com/desktop/desktop/issues/7383 as it is related to conflicted files in the Changes list.
