### ISSUE TITLE
[Stashing] Untracked files are not shown in the diff

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#7287]
Untracked files are not shown in the stash diff, but when restored, they are added to the working directory.

**Repro steps**
1. Create a new file with some contents
1. Create stash
1. View diff of stash

**Expected** 
The untracked file is present in the stash diff.

**Actual**
The untracked file is not there. In situations for the untracked file was the only stashed file, the diff view will appear to be empty.

![2019-04-12 16 11 04](https://user-images.githubusercontent.com/1715082/56069141-3da81e80-5d47-11e9-8810-c8a7b8720e83.gif)

**Comment by billygriffin** [comment]
This feels like pre-beta expected behavior to me - it's important that the uncommitted changes you think you're stashing actually display as being part of the stashed changes.
