### ISSUE TITLE
[stashing] Double clicks of buttons throws error and double log entries

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7289]
If you click either the `Restore` or `Discard` buttons multiple times in row rapidly, you get this.

Restore = error msg
<img width="1129" alt="Screen Shot 2019-04-12 at 2 51 50 PM" src="https://user-images.githubusercontent.com/14828183/56072497-41ca4100-5d33-11e9-92a9-19b6e39cbd84.png">

Discard = double logs
<img width="1107" alt="Screen Shot 2019-04-12 at 2 52 32 PM" src="https://user-images.githubusercontent.com/14828183/56072498-4858b880-5d33-11e9-9469-1f559057490a.png">

As for Clear, should we change to Discard so it's inline with right-click in the Changes list?

5977a42c21, mac

**Comment by billygriffin** [comment]
So if it's taking awhile to restore or clear, for example, you might click it again and you'll see an error message. It will still complete the first operation as expected though, right? If so, I'd say this is maybe a post-beta and maybe pre-production thing? I wonder if, like other things, we want some indication that something is happening when you restore or clear, depending on how long these operations are expected to take (in other words, let's say I have a stash with 100 files - how long will it take to restore or clear it?).

**Comment by tierninho** [comment]
Yes, all actions are still performed when clicking the buttons.

I my example I only had a few files so I had to be fast at double clicking. Haven't tried with tons of files so this may very delay the button from being disabled.

At minimum we should disable the button immediately after it's clicked, and for extra 🎨add a spinner to show something is "working".

**Comment by tierninho** [comment]
Update: can no longer repro the discard error as we added the "Are you sure?" dialogue.

**Comment by shiftkey** [comment]
I was able to reproduce this on Windows with an external mouse and using `Restore` (with 3 files stashed) instead of `Discard`:

<img width="659" src="https://user-images.githubusercontent.com/359239/58639331-17c1e380-82cd-11e9-937b-64bc2dc32811.png">

<img width="742" src="https://user-images.githubusercontent.com/359239/58639333-17c1e380-82cd-11e9-9a7c-1bf174cc0516.png">

The impact seems to be minimal (the first `git stash pop` appears to complete successfully) but I think the app could handle this case better (disable the button while the restore is happening?)

**Comment by iAmWillShepherd** [comment]
> The impact seems to be minimal (the first `git stash pop` appears to complete successfully) but I think the app could handle this case better (disable the button while the restore is happening?)

I agree that we should be disabling the button while the restore is working. We do this in other places in the UI, so doing what you suggest would ensure we are being consistent.
