### ISSUE TITLE
Add feature 'Run on Background' or 'Drop to System Tray'

### ISSUE THREAD

**Issue by maifeeulasad** [desktop/desktop#7291]
There is no feature in Github Desktop _(as far as I know)_

Can these type of features be added in later version of the application ?

**Comment by billygriffin** [comment]
Hi @maifeeulasad, thanks for the issue! I'm not quite sure what you're asking for with these features. Would you mind describing when you're running into problems, and what each of these feature might enable for you? We don't typically add new features that are unrelated to well-defined problems to solve that affect many of our users, so I'd just like to understand better what you're looking to accomplish and how the lack of them is negatively affecting you today. Thanks!

**Comment by shiftkey** [comment]
Cross-referencing an earlier discussion about this #4098 and in particular this comment https://github.com/desktop/desktop/issues/4098#issuecomment-369116015:

> Isn't what used to be called the "system tray" now the "notifications area"? From the [Windows Design Guidelines](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742495.aspx?f=255&MSPPError=-2147217396):
> 
> > The notification area was originally intended as a temporary source for notifications and status. Its efficiency and convenience has encouraged developers to give it other purposes, such as launching programs and executing commands. Unfortunately over time, these additions made the notification area too large and noisy, and confused its purpose with the other desktop access points.
> 
> > Don't abuse the notification area. Use it only as a source for notifications and status, and for features without desktop presence.
> 
> Since GitHub Desktop is intended to have a desktop presence, the guidelines would seem to say we shouldn't use the notification area this way.

**Comment by niik** [comment]
Thanks again for opening this @maifeeulasad. Given the issue @shiftkey cited above I'm going to close this issue and refer you to https://github.com/desktop/desktop/issues/4098. "Minimizing to tray" is not something we're planning on adding but there exists third-party tools to add this functionality to any application.

**Comment by bradley-berthold** [comment]
If Github Desktop has a "notification" feature than this feature won't work if you close the application, will it? I would expect it could exist in the system tray so it could send me notifications
