### ISSUE TITLE
The revocation function was unable to check revocation for the certificate

### ISSUE THREAD

**Issue by kwamc** [desktop/desktop#7294]
unable to publish new branch to my repository. InitializeSecurityContext failed.

**Comment by billygriffin** [comment]
Hi @kwamc, thanks for the issue! I'm not positive, but this looks like a known issue. The documentation for the workaround and the associated issue is here: https://github.com/desktop/desktop/blob/development/docs/known-issues.md#certificate-revocation-check-fails---3326

Let us know if that isn't what's causing it, and we'll be happy to reopen this issue and investigation further. Thanks!
