### ISSUE TITLE
Option to Sign-out When Exiting Application

### ISSUE THREAD

**Issue by Rafellus** [desktop/desktop#7297]
I believe that an option to sign out when exit, is necessary. My personal reason:

I like to have the same workflow in home and work. When working from an non-personal PC (ironic), I forget to sign out, sometimes. This worries me, because all PCs/laptops at my job are used by many employees, making it not very different from a public environment (in a info privacy point).

Currently the solution I come up to, is using Git-Bash in my job. Nonetheless, thanks for reading this suggestion, and for all the work you put into improving the app.

**Comment by shiftkey** [comment]
@Rafellus thanks for the feedback!

> This worries me, because all PCs/laptops at my job are used by many employees, making it not very different from a public environment (in a info privacy point).

I don't have any strong opinions on the proposed change, but I can provide some context about what is happening under the hood.

GitHub Desktop uses the Windows Credential Store to store the necessary credentials after completing sign-in, and installs itself into the `%APPDATA%` and `%LOCALAPPDATA%` directories, all of which are tied to the current user account. If you are working on machines where users do not share the same login to the machine, signing out from your account is enough to prevent these accidentally being shared.

**Comment by Rafellus** [comment]
@shiftkey 
>  If you are working on machines where users do not share the same login to the machine, signing out from your account is enough to prevent these accidentally being shared.

Didn't thought about that, thanks for the solution. Nothing else to argue then.

**Comment by shiftkey** [comment]
@Rafellus thanks for clarifying!

I'm going to close this out because, if you follow good security habits and don't use a shared Windows account, the user data stored by GitHub Desktop is managed by the OS and is inaccessible to other users. Adding things to the app to encourage signout is unnecessary if the users are signing out of their Windows account when they are done with the machine.
