### ISSUE TITLE
[Stashing] Add info verbiage next to restore button in stash diff UI

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#7303]
Add a bit of explanatory text next to the _Restore_ button to inform the user of what it means.

See https://github.com/desktop/desktop/issues/6987#issuecomment-472942310 for context.

There are 2 scenarios that need to be handled:
1. No uncommitted changes
    * _Discard_ and _Restore_ buttons are both enabled
    * _Restore_ button will have the following text next to it: "This will pop this stash as changed files."
2. Uncommitted changes exist
    * _Discard_ is enabled,  _Restore_ is **disabled**
    * _Restore_ button has an :exclamation: icon with the text: "Unable to restore stash when changes are present on your branch."

Some things worth considering:
* For scenario 1, depending on the button order issue (https://github.com/desktop/desktop/pull/7301), we may need to rethink the helper text because if the buttons are reversed the text is no longer next to the "restore" button and it's confusing.

![UI](https://user-images.githubusercontent.com/10404068/52888927-8f12a380-3132-11e9-9aae-e4ac8f113e2e.png)

☝️ This image uses the verb _apply_, but we will instead be going with _pop_; the info text in the image will not actually be used, it only serves as a visual aide.

**Comment by outofambit** [comment]
@ampinsk and I would like to keep the layout of the original design (regardless of button order) as long as we use the text "Restore will move your stashed files to the Changes list." https://github.com/desktop/desktop/pull/7363#discussion_r277699020
