### ISSUE TITLE
Can we use central.github.com to view and collect the data?

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#7310]
I found the central.github.com was used to collect usage data, but it cannot be accessed:
![image](https://user-images.githubusercontent.com/5396286/56194130-d2bb5800-6064-11e9-9d89-98841cd456a8.png)
Can we use central.github.com to view and collect the data?

**Comment by billygriffin** [comment]
Hi @TerryChan, thanks for the issue. Central is internal to GitHub for the purpose of sending app updates and collecting crash and usage metrics. It's not publicly accessible.

Would you mind sharing what you're interested in it for?

**Comment by TerryChan** [comment]
@billygriffin Thanks for your reply.
I also want to collect usage metrics as GitHub Desktop did, do you know any other public products like Central that I can use?

**Comment by shiftkey** [comment]
@TerryChan 

Central is a simple public front-end to serve updates to users and receive events from installed clients that we send through to other internal systems.

As this touches on to like PII and [GDPR](https://eugdpr.org/), I don’t have recommendation for an off-the-shelf equivalent currently.
