### ISSUE TITLE
[stashing] Existing stash deleted when bringing new Changes over

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7318]
I have a stash on branch B and I bring over changes from another branch to branch B, the stash on branch B gets deleted even though the files stay in Changes. 

Expected:
1. have a stash on branch B
2. do work on branch A that isn't committed
3. switch from A to B
4. choose to bring my changes over to B
5. the changes from A in the working directory, and the pre-existing stash is still present as a stash

Here you can see the stash disappear when the file is brought over:
![Apr-16-2019 08-01-25](https://user-images.githubusercontent.com/14828183/56233046-e394ab00-601d-11e9-9e20-a51a05043313.gif)

8488b66e0a, mac

**Comment by billygriffin** [comment]
So in the current state, we delete the stash on branch B without the user's knowledge that it happened? Do they have the ability to recover it?

**Comment by tierninho** [comment]
> So in the current state, we delete the stash on branch B without the user's knowledge that it happened?

Yes, that is correct.

> Do they have the ability to recover it?

No. I tried to restore it, but no luck.
