### ISSUE TITLE
Refactor getStashedFiles to use getChangedFiles

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#7320]
from @niik at https://github.com/desktop/desktop/pull/7316#pullrequestreview-227407420
> 
> Looking at this I believe we could simplify it quite a bit if we make the same change to `getChangedFile` to (perhaps optionally) not throw an error when the ref is invalid.
> 
> ```ts
> export async function getStashedFiles(
>   repository: Repository,
>   stashSha: string
> ): Promise<ReadonlyArray<CommittedFileChange>> {
>   const [trackedFiles, untrackedFiles] = await Promise.all([
>     getChangedFiles(repository, stashSha),
>     getChangedFiles(repository, `${stashSha}^3`),
>   ])
> 
>   const files = new Map<string, CommittedFileChange>()
>   trackedFiles.forEach(x => files.set(x.path, x))
>   untrackedFiles.forEach(x => files.set(x.path, x))
>   return [...files.values()].sort((x, y) => compare(x.path, y.path))
> }
> ```
> 
> Something to think on for future iterations of this.

**Comment by niik** [comment]
Addressed in https://github.com/desktop/desktop/pull/14921
