### ISSUE TITLE
Cannot see affected file in conflicts dialog

### ISSUE THREAD

**Issue by adamreisnz** [desktop/desktop#7323]
**Please describe the problem you think should be solved**
![image](https://user-images.githubusercontent.com/490562/56246567-7a349b00-60f6-11e9-90be-be6337b46b71.png)

I cannot see the filename of the file that is actually conflicted, because the path is cut off at an awkward place.

**Do you have any potential solutions in mind?**
First of all it looks like there is a lot of wasted whitespace in the dialog, even if you make space for buttons, so why not allow a bit more characters for each path?

Second, obviously in this case the priority should be to always show the end part (file name) of the path, so that we can correctly identify the file.

**Comment by steveward** [comment]
Thanks for the report @adamreisnz! This is being tracked in https://github.com/desktop/desktop/issues/6666, so I am going to close this issue out. Please follow along there for updates!

**Comment by adamreisnz** [comment]
Ah thanks, I tried to search for existing issues related to this but couldn't find any. I will track there.

**Comment by billygriffin** [comment]
Thanks @adamreisnz, fwiw I completely agree with you that it makes it a lot trickier to navigate. Thanks for bringing it up! And thanks @steveward for finding the existing issue!
