### ISSUE TITLE
[stashing] alpha order the files in stash list

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7327]
To match files in the Changes list, we should be alpha-ordering the list of files in the stash diff.

<img width="266" alt="Screen Shot 2019-04-16 at 1 34 30 PM" src="https://user-images.githubusercontent.com/14828183/56250893-f377b380-604c-11e9-8156-9687832dd929.png">

b47a0e8ea3, mac

**Comment by niik** [comment]
@outofambit I believe this was fixed in https://github.com/desktop/desktop/commit/0efbcd4111217232a57b697eb5cae4586f17ecdc right? Can we close this?

**Comment by outofambit** [comment]
@niik i think we need something like https://github.com/desktop/desktop/pull/7387/commits/f112c2edf82bfb18f2a2ae0b4bc2cdb525f81c46 to get alphabetical sorting by file path.
