### ISSUE TITLE
[stashing] stashed files disappear if all commits are undone

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7328]
If you create a fresh repo then undo all the commits -- but have stashed files on that branch -- then the stashed files will also be removed without warning.

Repro:
- create a new repo with two branches
- stash files on master
- now undo so the `gitattributes` file is in the Changes list
- the stash should now disappear 

Should we show a warning or just not allow it to happen?

b47a0e8ea3, mac

**Comment by outofambit** [comment]
marking priority 3 since the reproduction steps are fairly involved and unlikely to occur in the wild.

the stash is most likely disappearing within git because the commits it was created from were removed by the undo action.

**Comment by billygriffin** [comment]
After talking about this with @outofambit, this seems like an extreme edge case, and I think we ought to validate that it actually happens before solving this.
