### ISSUE TITLE
Github desktop hangs on cloning repository

### ISSUE THREAD

**Issue by ubuntu-repo** [desktop/desktop#7334]
## Description

Tried several times to clone a repository using Github Desktop (repository already cloned in Github to my own account). The Desktop interface hangs on about 80% of the download. Restarting Github Desktop and removing the local repository gives the same result. Also removing the repository from my Github account, re-cloning it on Github and then redoing the Github Desktop cloning of that repository fails in the same manner....

Repo: ubuntu-repo/c2rust (cloned from: immunant/c2rust). 

The cloning hangs on '.../c2rust/cross-checks/ReMon'

## Version

* GitHub Desktop: 1.6.5-linux6

* Operating system: Ubuntu 18.04.02 (LTS) Gnome 3.28.2 64 bit 

## Steps to Reproduce

Step 1: Using the Github webinterface and logged in to my account clone the repo: immunant/c2rust to 'ubuntu-repo' (my Github account).
Step 2: Using the Github Desktop, use the menu option: File->Clone repository to clone the c2rust repository (logged in to your Github account) to my local hard drive.

FAILS!  (download hangs on 80% - see screenshot).
![githubdesktop-clone-c2rust](https://user-images.githubusercontent.com/36987554/56311546-919f7280-614e-11e9-801f-7c58de29875c.png)

..

Possible resolutions tried:

Step 3: Closing Github Desktop application and deleting the local repository clone on my hard drive (on: '/home/rob/Source/github/c2rust' and re-trying Step 2. -> Same result
Step 4: Same as Step 3 and in Github web application deleting the repository 'c2rust' and then re-cloning that same repositoty in the web app and re-trying Step 2. -> Same result.

### Expected Behavior

Github Desktop started to clone/download the repository and should normally finish downloading it completely after some ampount of time.

### Actual Behavior

The downloading did progress to some point but stalled at about 80% of the progress bar indicator, mentioning: Cloning into 'home/rob/Sources/github/c2rust/cross-checks/ReMon'.

From my local computer I can see that most of the directories and files expected are there, but the folder 'cr2rust/cross-checks/ReMon' only contains '.git' file which contains: 'gitdir: /home/rob/Source/github/c2rust/.git/modules/ReMon'.

## Additional Information

![githubdesktop-clone-c2rust](https://user-images.githubusercontent.com/36987554/56310731-dd511c80-614c-11e9-8ce5-f98e7de81fcd.png)

### Logs

[2019-04-17.desktop.production.log](https://github.com/desktop/desktop/files/3091016/2019-04-17.desktop.production.log)

Note: the log contains errors of other (unrelated) problems (having relocated the download folder from earlier clones) which have been resolved by relocating the clone/download folders.

**Comment by shiftkey** [comment]
@ubuntu-repo thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by ubuntu-repo** [comment]
I noticed that the directory name in the repository on which the cloning/download hangs has some unusual name: [https://github.com/ubuntu-repo/c2rust/tree/master/cross-checks](url) -- 'ReMon @ 314a06b' -- maybe that causes Github desktop to hang on it?

**Comment by shiftkey** [comment]
> Operating system: Ubuntu 18.04.02 (LTS) Gnome 3.28.2 64 bit

We're tracking issues with the unofficial Linux releases over on my fork - https://github.com/shiftkey/desktop - please submit an issue there, the clue about submodules might be helpful here.
