### ISSUE TITLE
[react] uncontrolled/controlled component warning in Welcome flow

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#7339]
## Description

<img width="553" alt="Screen Shot 2019-04-17 at 2 13 14 PM" src="https://user-images.githubusercontent.com/5091167/56318161-d362f580-611b-11e9-913e-50f9e5858933.png">

## Version

* GitHub Desktop: 1.7.0-beta4, commit output of git rev-parse HEAD: ab7b0e9bfedd27834fa2fd3b8f49f11c0f8dcafc
* Operating system: latest macOS X

## Steps to Reproduce

1. Build the app locally with yarn start
2. Login from browser via GitHub
3. Add Git author and email info in onboarding
4. Add existing repository from Hard Drive

### Expected Behavior

Not see warnings.

### Actual Behavior

See warnings.

## Additional Information

~~Note: I'm also unable to see my GitHub repos despite having logged in via the browser.~~

<img width="470" alt="Screen Shot 2019-04-17 at 2 08 31 PM" src="https://user-images.githubusercontent.com/5091167/56318360-48362f80-611c-11e9-8275-793e07853936.png">

**Comment by shiftkey** [comment]
> Note: I'm also unable to see my GitHub repos despite having logged in via the browser.

As we talked about in Slack, this feels like https://github.com/desktop/desktop/issues/7019 but if you can spot any interesting network issues at the time I'd love to hear more...

**Comment by billygriffin** [comment]
@shiftkey Yep, based on being able to see my repos after a reload, I think that seems right. Do you think the initial warnings are related or separate? If separate, would you like to keep this issue open?

**Comment by shiftkey** [comment]
The React warning is a separate issue, and we can keep this open to focus on getting that addressed.

**Comment by ADustyOldMuffin** [comment]
If possible, I'd like to see if I can recreate this and work on it.

**Comment by shiftkey** [comment]
@ADustyOldMuffin go for it - I know this was spotted this week, so it's definitely still relevant!

**Comment by ADustyOldMuffin** [comment]
@shiftkey I don't have MacOS, and after following the steps several times I am unable to recreate any errors. Is someone with MacOS able to recreate this?

**Comment by billygriffin** [comment]
I've not seen this again, so I'm going to close it. Thanks for taking a look @ADustyOldMuffin!
