### ISSUE TITLE
[stashing] Stashing blocked when file needs to be merged

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7340]
Cannot stash if file needs to be merged first. Both stashing options in the modal result in the following error:

<img width="1139" alt="Screen Shot 2019-04-17 at 10 29 14 AM" src="https://user-images.githubusercontent.com/14828183/56318899-ea91eb00-60fb-11e9-9179-63c9c376d1c5.png">

Not sure of the exact reproduction steps for this. Notice the checkbox next to the file indicating it is ready to be merged. I was playing around with Merge Conflicts and Rebasing at the time.

v1.7.0-beta4, Windows 10

**Comment by billygriffin** [comment]
To be clear, this is during the merge conflict flow and you're trying to switch branches? I think that may be the same as https://github.com/desktop/desktop/issues/7247?

**Comment by tierninho** [comment]
Yes, this looks to be a duplicate then. Closing for now, as the two issues are linked.
