### ISSUE TITLE
Stash My Changes and Switch Branches Doesn't Work

### ISSUE THREAD

**Issue by say25** [desktop/desktop#7344]
## Description

Stash My Changes and Switch Branches Doesn't Work

## Version
* GitHub Desktop: 1.7.0-beta4
* Operating system: Windows 10

## Steps to Reproduce
1. Have a massive repository with untracked files
1. Create a new branch and try switching to it

### Expected Behavior
Switch successful

### Actual Behavior
Switch unsuccessful.

## Additional Information
1. I think this has to do with untracked files that I don't have permissions to modify.

### Logs
The last bit of the log matters most.

[2019-04-18.desktop.beta.log](https://github.com/desktop/desktop/files/3094671/2019-04-18.desktop.beta.log)

**Comment by shiftkey** [comment]
@say25 thanks for the report!

I'll pull out the relevant error from the log for convenience:

```
2019-04-18T13:48:01.686Z - error: [ui] `git stash push --include-untracked -m !!GitHub_Desktop<Yeh-Hackathon-CMA-Purge>` exited with an unexpected code: 1.
Saved working directory and index state On master: !!GitHub_Desktop<Yeh-Hackathon-CMA-Purge>

warning: failed to remove Va/Ftc.Web/aspnet_client/system_web/4_0_30319: Permission denied
```

This reads to me as "the stash was created but a non-zero exit code was raised because of a permission issue" - can you confirm the stash exists in the repository by using `git stash list`?

You should see an entry `!!GitHub_Desktop<Yeh-Hackathon-CMA-Purge>` where `Yeh-Hackathon-CMA-Purge` is the name of the branch that the stash is associated with.

If that exists, I think our best option here is to handle the exit code, inspect the `stderr` (I think) for any warning message, and proceed (but log it out for reference).

**Comment by shiftkey** [comment]
Marking as `priority-2` because of it's impact to the stashing flow - the user cannot stash and switch branches in this case, and needs to bail out to the command line...

**Comment by say25** [comment]
Can confirm stashes do exist:
```shell
SYEH@VAA-SYEH-LT1 MINGW64 /d/work/Main (Yeh-CMA-Hackaton)
$ git stash list
stash@{0}: On master: !!GitHub_Desktop<master>
stash@{1}: On master: !!GitHub_Desktop<Yeh-Hackathon-CMA-Purge>
stash@{2}: On master: !!GitHub_Desktop<Yeh-Hackathon-CMA-Purge>
stash@{3}: On master: !!GitHub_Desktop<Yeh-Hackathon-CMA-Purge>
stash@{4}: On master: !!GitHub_Desktop<Yeh-Hackathon-CMA-Purge>
```

**Comment by xt0rted** [comment]
@shiftkey I just ran into this and my new untracked files were deleted. And not in the nice let's add them to the recycle bin way. They were straight up deleted off disk and weren't part of the stash either. Thankfully I was able to copy the files from somewhere else.

This looks to be a result of having a PDF as one of my untracked files which was open in Edge and I guess locked. This caused an unhandled error to be thrown and when this happens the untracked files that aren't open & locked get deleted.

I can repro this by leaving the PDF open in Edge and adding new files to the repo, then creating a new branch and selecting to bring the files over. Each time the new files get deleted and the below errors show in the console.

**Console**
```
install.ts:23 `git stash push --include-untracked -m !!GitHub_Desktop<test>` exited with an unexpected code: 1.
Saved working directory and index state On master: !!GitHub_Desktop<test>

warning: failed to remove docs/Report 04092019.pdf: Invalid argument

error @ install.ts:23
t.git @ core.ts:171
_tickCallback @ internal/process/next_tick.js:68
async function (async)
t.git @ core.ts:111
t.createDesktopStashEntry @ stash.ts:96
_createStash @ app-store.ts:5063
_checkoutBranch @ app-store.ts:2824
checkoutBranch @ dispatcher.ts:463
stashAndCheckout @ stash-and-switch-branch-dialog.tsx:170
onSubmit @ stash-and-switch-branch-dialog.tsx:150
onSubmit @ dialog.tsx:342
r @ react-dom.production.min.js:15
invokeGuardedCallback @ react-dom.production.min.js:16
invokeGuardedCallbackAndCatchFirstError @ react-dom.production.min.js:16
p @ react-dom.production.min.js:20
h @ react-dom.production.min.js:22
g @ react-dom.production.min.js:22
c @ react-dom.production.min.js:21
S @ react-dom.production.min.js:24
v @ react-dom.production.min.js:24
Kt @ react-dom.production.min.js:83
batchedUpdates @ react-dom.production.min.js:187
nt @ react-dom.production.min.js:42
$t @ react-dom.production.min.js:85
interactiveUpdates @ react-dom.production.min.js:188
Xt @ react-dom.production.min.js:84
```
```
Uncaught (in promise) p: warning: failed to remove docs/Report 04092019.pdf: Invalid argument


    at Object.t.git (file:///C:/Users/brian/AppData/Local/GitHubDesktop/app-1.7.0-beta4/resources/app/renderer.js:5:7806)
    at process._tickCallback (internal/process/next_tick.js:68:7)
p @ core.ts:80
t.git @ core.ts:174
_tickCallback @ internal/process/next_tick.js:68
async function (async)
onSubmit @ stash-and-switch-branch-dialog.tsx:126
onSubmit @ dialog.tsx:342
r @ react-dom.production.min.js:15
invokeGuardedCallback @ react-dom.production.min.js:16
invokeGuardedCallbackAndCatchFirstError @ react-dom.production.min.js:16
p @ react-dom.production.min.js:20
h @ react-dom.production.min.js:22
g @ react-dom.production.min.js:22
c @ react-dom.production.min.js:21
S @ react-dom.production.min.js:24
v @ react-dom.production.min.js:24
Kt @ react-dom.production.min.js:83
batchedUpdates @ react-dom.production.min.js:187
nt @ react-dom.production.min.js:42
$t @ react-dom.production.min.js:85
interactiveUpdates @ react-dom.production.min.js:188
Xt @ react-dom.production.min.js:84
```

**Log file**
```
2019-04-22T18:36:08.475Z - info: [ui] Executing createStashEntry: git stash push --include-untracked -m !!GitHub_Desktop<test> (took 1.826s)
2019-04-22T18:36:08.476Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: XXXXXXXXX - xt0rted (has token)
2019-04-22T18:36:10.307Z - info: [ui] Executing popStashEntry: git stash pop stash@{0} (took 1.183s)
2019-04-22T18:36:10.308Z - info: [ui] [AppStore. _popStashEntry] popped stash with commit id 93b99a94637d48a6ec3b471d73b88d240b0fdeaa
2019-04-22T18:36:24.568Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: XXXXXXXXX - xt0rted (has token)
2019-04-22T18:36:44.266Z - info: [ui] Executing createStashEntry: git stash push --include-untracked -m !!GitHub_Desktop<test> (took 1.058s)
2019-04-22T18:36:44.269Z - error: [ui] `git stash push --include-untracked -m !!GitHub_Desktop<test>` exited with an unexpected code: 1.
Saved working directory and index state On master: !!GitHub_Desktop<test>

warning: failed to remove docs/Report 04092019.pdf: Invalid argument
```

**Comment by xt0rted** [comment]
It turns out the files did get stashed, but there was more than one stash. The first stash has the untracked files while the second stash doesn't. This is why it looked like they were completely missing. Once I get this cleaned up I'll try to repro it again and confirm if files are really being deleted or not.

**Comment by shiftkey** [comment]
@xt0rted thanks for the extra data point on this.

cc @iAmWillShepherd for :eyes: and additional thoughts about what we can do here.

**Comment by iAmWillShepherd** [comment]
I think it may be worth doing a check of file permissions just before stashing. If it turns out permissions would cause stash creation to fail, we can bail and alert the user that we're unable to create a stash due to file permissions and continue with the branch switch as usual.

**Comment by shiftkey** [comment]
>  If it turns out permissions would cause stash creation to fail, we can bail and alert the user that we're unable to create a stash due to file permissions and continue with the branch switch as usual.

We actually get this for free from Git - it emits the paths it can't access, and it feels simpler to defer to the actual implementation rather than try and emulate this ourselves.

I updated #7351 to indicate that it shouldn't close this out, and I think we have two options here if we encounter an error:

 - use the implementation in #7351 and just stash what we can, ignoring the problem paths reported by Git
 - be more conservative with the errors detected and inform the user that some paths could not be stashed, giving them the option to continue with whatever could be stashed

I could happily ship #7351 for the next beta to help the users who have encountered problems with their workflow, but I favour the second option to help make this flow less confusing.

Here's a quick mockup of what the user could see in the case this fails:

<img width="625" src="https://user-images.githubusercontent.com/359239/56590571-b4ea7780-65bd-11e9-899b-17a0a18b856e.png">

**Comment by xt0rted** [comment]
I haven't had a chance to fully try reproing this, but from my initial testing it looks like locked files do get stashed, but then it fails when trying to remove them from the folder. So then if you try again thinking the initial stash failed a second stash is created, but is missing whatever new files were already stashed & removed the first time.

**Comment by iAmWillShepherd** [comment]
@shiftkey, I'm actually inclined to go the more conservative route:

> be more conservative with the errors detected and inform the user that some paths could not be stashed, giving them the option to continue with whatever could be stashed

I am curious to know what would happen if I click _Cancel_. At the moment, it's not clear to me when this message would appear - before or after the stash is created. If it's **after** the stash being created, would we then need to pop the newly created stash to get the user back to where they started?

**Comment by shiftkey** [comment]
@iAmWillShepherd looking at the bug reports, it looks like Git does create the stash even though it returns a non-zero exit code:

```
Saved working directory and index state On master: !!GitHub_Desktop<Yeh-Hackathon-CMA-Purge>
...
Saved working directory and index state On master: !!GitHub_Desktop<test>
```

If you were to cancel the stash-and-checkout flow at this point, I think the app should pop the stash and put those changes back in the working directory to truly put you back to the "before" state.

**Comment by outofambit** [comment]
what do y'all think about closing this bug issue and opening a new issue to continue discussion of a more `enhancement` style approach to the underlying issue? it seems like we've prevented the straight up failure case (with #7351, which went out in yesterday's beta) if i'm following along right.
