### ISSUE TITLE
[Stashing] Add Explicit UI for closing the Stash Diff Viewer

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#7347]
This may be an 'x' button on the stash diff viewer header...or something else. @outofambit will pair with @ampinsk to figure out a solution.

<img width="909" alt="Screen Shot 2019-04-18 at 10 33 12 AM" src="https://user-images.githubusercontent.com/964912/56372819-5f7d2780-61c5-11e9-8607-1234cb5e9291.png">

**Comment by iAmWillShepherd** [comment]
@outofambit, I added the function `Dispatcher.hideStashedChanges` that you can hook into to close the stash diff UI.

https://github.com/desktop/desktop/blob/5069415ed1db7ab8b4842039623cee6a599ed1e1/app/src/ui/dispatcher/dispatcher.ts#L2056-L2060

**Comment by billygriffin** [comment]
After a usability test to validate my assumption that this would be useful/necessary, I'm going to close this until we have actual evidence from users that it will be.
