### ISSUE TITLE
Unable to log into github desktop ubuntu 18.04

### ISSUE THREAD

**Issue by ShivarjunBhattarai** [desktop/desktop#7354]
Unable to log into GitHub Desktop in Ubuntu 18.04. When entering a wrong password it does recognize it as a wrong password, but with correct password, it just closes the login screen and nothing happens.  

GitHub desktop version: 1.6.5-linux6

**Comment by shiftkey** [comment]
We're tracking issues with the unofficial Linux releases over on my fork - https://github.com/shiftkey/desktop - please submit a [bug report](https://github.com/shiftkey/desktop/issues/new?template=bug_report.md) and fill out the template
