### ISSUE TITLE
Right-clicking on file in Changes list should not include "Discard All Changes..." menu item in contextual menu

### ISSUE THREAD

**Issue by bamwu** [desktop/desktop#7356]
For the 3rd time in recent memory I have accidentally discarded **all** changes, only having meant to discard changes for 1 selected file.

Items in the contextual menu from right-clicking on a single file should pertain only to that file.

Thankfully in all 3 cases I was able to effectively undo the mistake by rummaging thru the trash.

The 2 minutes between destroying hours/days of work and remembering that the files with the changes are recoverable... are heart pumpingly scary.

I realize it's a "feature not a bug"... but please fix.

Thanks.

![Screen Shot 2019-04-18 at 5 28 06 PM](https://user-images.githubusercontent.com/17959315/56392460-76d90680-61ff-11e9-97b0-8c6dab2caa04.png)

**Comment by shiftkey** [comment]
@bamwu thanks for the feedback. I'm going to add this to #5342 where we're talking about the UX of this item. Please follow along with that discussion.

**Comment by tierninho** [comment]
@bamwu Apologies that you are experiencing this. 

I suggest you enable the discard warning option in Preferences. Go to the GitHub Desktop menu, and click the `Show confirmation dialog before discarding changes` checkbox under the Advanced tab in Preferences. Note, this is a warning message for discarding all files, not a single file.
