### ISSUE TITLE
`Enter` on a highlighted checkbox results in clicking primary button

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7357]
There are numerous checkboxes throughout the app that allow you to inadvertently click the primary button if you hit the `enter` key while a checkbox is highlighted. 

Here is a preliminary list, which seems to be relevant to all modals/dialogues with one checkbox only and at least one enabled button.

- Force Push dialogues (2x) 
- Discard single file dialogue
- New repo modal

<img width="618" alt="Screen Shot 2019-04-18 at 2 15 51 PM" src="https://user-images.githubusercontent.com/14828183/56400408-79336480-61ef-11e9-9a6c-c084cbabd948.png">

Expected behavior: Clicking `enter` button while checkbox is highlighted results in toggling of checkbox.

1.7.0.beta4, mac

**Comment by mgharwi** [comment]
m.gharwi2020@gmail.com

**Comment by tidy-dev** [comment]
I checked in with our Accessibility team and our behavior is expected behavior: 
> Users won’t (shouldn’t) expect Enter will toggle the checkbox, since that’s not how other checkboxes (neither on the web nor on macOS) are toggled.
> Users could be confused if their muscle memory (press Enter to confirm and close) breaks because special handling is added.
