### ISSUE TITLE
[Idea] "Open the repository in your shell" button at no changes screen

### ISSUE THREAD

**Issue by ImJustToNy** [desktop/desktop#7365]
I think if we have "open in an external editor" and "open in a file manager" buttons on no changes screen, IMO button to open shell should also be there.

I'm thinking about something like:
![image](https://user-images.githubusercontent.com/5730766/56459585-e680fa00-6395-11e9-9104-03012ee338db.png)

I work on a couple of repositories, and It would be useful to be able to quickly open terminal windows for them.

**Comment by billygriffin** [comment]
Thanks! As discussed in your PR, I’m going to close this for now, but we’ll be evaluating it as we get metrics on the things we chose to include initially.
