### ISSUE TITLE
I can't upload my node_modules into my github repository

### ISSUE THREAD

**Issue by beamerboi** [desktop/desktop#7371]
hello , i tried so hard to upload my node_modules folder into my github repository but it keep showing those errors .. please help me
![image](https://user-images.githubusercontent.com/40015058/56464616-71d5ac00-63e5-11e9-99b2-dde61eca9bfe.png)
![image](https://user-images.githubusercontent.com/40015058/56464621-7e5a0480-63e5-11e9-8867-82ca80b1b773.png)

**Comment by shiftkey** [comment]
@beamerboi you need to make a commit to the current branch:

``` 
$ git add [paths]
$ git commit -m "[some message]"
```

Then you should be able to push to the remote branch.
