### ISSUE TITLE
Windows desktop app does not trigger the onscreen keyboard with SurfaceGo devices

### ISSUE THREAD

**Issue by NewAlexandria** [desktop/desktop#7373]
## Description
When you tap in a text entry field (e.g. username login, search filter, etc), at no point does the app cause the on-screen keyboard to appear.  Users that do not have a wireless keyboard must open the system preferences and manually activate the keyboard. 

## Version

* GitHub Desktop: v1.6.5

* Operating system: windows 10 home v17134.648 for SurfaceGo

## Steps to Reproduce
1. download gihub desktop
2. install
3. have no wireless keyboard attached
4. try to enter text in the login dialogue

### Expected Behavior
onscreen keyboard should appear when you tap on a text input field

### Actual Behavior

nothing comes up 

### Logs

[2019-04-20.desktop.production.log](https://github.com/desktop/desktop/files/3101269/2019-04-20.desktop.production.log)

**Comment by iAmWillShepherd** [comment]
@NewAlexandria, could this issue be related to your machine's configuration? I've tested this on my Surface Go and was unable to reproduce this issue.


[![thumbnail](https://user-images.githubusercontent.com/1715082/56505423-433cfb80-64e1-11e9-93ff-8a520851b8db.jpg)](https://youtu.be/7B2VVJAtrNI)

**Comment by NewAlexandria** [comment]
That would be best.  I’ll look.

**Comment by tierninho** [comment]
@NewAlexandria As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
