### ISSUE TITLE
unable to log out from "lets get started" screen

### ISSUE THREAD

**Issue by HawkenKing** [desktop/desktop#7374]
## Description
I logged in as wrong user, I want to log in with a different account but theres no options.

## Version
menu item not available

* GitHub Desktop:

* Operating system:
win 10

## Steps to Reproduce
1. open github desktop, log in. 
2. Let's get started screen has no options to logout

### Expected Behavior
I want to log in as another user using the logout button

### Actual Behavior
There are no user account options on this screen

## Additional Information
I tried uninstalling github for desktop, but when reinstalling it, it went to the "lets get started" screen with the previously logged in account

**Comment by shiftkey** [comment]
@HawkenKing thanks for the feedback!

The "Let's Get Started" view is tailored to helping you add a repository into GitHub Desktop and get started, and once you've done that the default UI will be available as well as the rest of the menu system.

The **File** | **Options...** menu is where you can sign into a different account.

**Comment by billygriffin** [comment]
@HawkenKing Yep, this is intended behavior at least for now unless we hear that it's causing a lot of problems for people. I think your use case of logging into the wrong account and immediately wanting to log into a different account even prior to getting one repo set up in Desktop is unlikely to be widespread, so I'm going to close for now. But happy to reconsider if we see this come up more frequently. Thanks again!

**Comment by ma1022** [comment]
I have this annoying problem too. Even reinstall can't solve this problem.

**Comment by yvan-burrie** [comment]
I also have this extremely annoying problem. I wasted almost 3 hours reinstalling new and old versions of GD, all of that simply because of one excruciatingly annoying missing button: "Logout".

**Comment by michailmoiropoulos** [comment]
Still with this issue. I have another account and I just can't Logout from the old one.

**Comment by yvan-burrie** [comment]
@michailmoiropoulos Yes, the developers don't what they're doing. They think people only use 1 Github account. How silly of them.

**Comment by billygriffin** [comment]
Hi folks, in https://github.com/desktop/desktop/issues/8016 we're adding back the menu on Windows to provide a way to get around this issue. That will ship in the next version in a few weeks, and likely to beta before then - apologies for the inconvenience.
