### ISSUE TITLE
In Enterprise version, Push to Origin is not smooth

### ISSUE THREAD

**Issue by xploreraj** [desktop/desktop#7375]
Earlier it used to be smooth and I think it would show some processing icon as well when I pushed local commits to remote origin by clicking on the button on top. Now its not smooth and gives a feeling it isnt taking commands. After few seconds, it instantly transforms to Fetch origin. Can this be a smooth transition please with an icon like uploading or something similar?

v1.6.5, Mac Mojave 10.14.4

**Comment by shiftkey** [comment]
@xploreraj Thanks for the report!

There's some extra information here that would help to illustrate the issue:

 - Could you attach a GIF or video of the issue, so we can visually see the problem? This would help us to understand what's potentially confusing about the current experience.
 - Could you attach the full log files? The **Help** | **Show Logs in Finder** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot what might be happening under the hood in this situation.

**Comment by tierninho** [comment]
@xploreraj As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
