### ISSUE TITLE
[stashing] successfully popping a stash with conflicts doesn't drop the stash

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#7383]
**Repro steps**
1. Make a stash that touches a file
1. Update that in working directory and commit
1. Pop stash

Note that there will be conflicts and the stash content will be placed in the working directory, but Desktop will continue to show that there is a stash entry. _This is because of underlying git behavior aka desktop shows the stash because `pop` didn't actually remove the stash._

<img width="1191" alt="Screen Shot 2019-04-22 at 11 10 12 AM" src="https://user-images.githubusercontent.com/964912/56516638-d67d2d80-64ef-11e9-8635-8120550ce039.png">

You'll notice in this screenshot that while a stash has been popped (and resulted in conflicts) it still exists in the UI. We should ensure the stash is dropped as long as the pop is successful. (This doesn't include the case where [popping the stash fails due to conflicts](https://github.com/desktop/desktop/issues/7278).)

**Comment by tierninho** [comment]
We should consider this for feature for dealing with a stash merge conflict as it would give the user a cleaner option. 

> If you stash some work, leave it there for a while, and continue on the branch from which you stashed the work, you may have a problem reapplying the work. If the apply tries to modify a file that you’ve since modified, you’ll get a merge conflict and will have to try to resolve it. If you want an easier way to test the stashed changes again, you can run `git stash branch`, which creates a new branch for you, checks out the commit you were on when you stashed your work, reapplies your work there, and then drops the stash if it applies successfully.

**Comment by dyna-dot** [comment]
Why?
