### ISSUE TITLE
Error: Authenthication failed when fetch/push/pulling

### ISSUE THREAD

**Issue by csalmeida** [desktop/desktop#7384]
## Description

I have come across an authentication error when using [v1.6.5](https://github.com/desktop/desktop/releases/tag/release-1.6.5) of Desktop. 

> Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.

This started occurring after removing an older version of the app when noticing two versions of the app were installed concurrently. I cannot recall the version of the app that was removed from my machine. 

This issue is also described at #3816 and #4181, however, I was encouraged by @steveward [to open a new issue](https://github.com/desktop/desktop/issues/7039#issuecomment-485508647), sharing my logs below. 

## Version

* GitHub Desktop: [v1.6.5](https://github.com/desktop/desktop/releases/tag/release-1.6.5)

* Operating system: Microsoft Windows [Version 10.0.17134.706]

### Expected Behavior

1. `Commit`
2. `Click push or fetch`
3. `Sync repo as usual`
 

### Actual Behavior

1. `Make a commit`
2. `Click push or fetch at anytime`
3. `Authentication Error`

## Additional Information

Remote is set using `SSH`, i.e: git@github.com:csalmeida/example-repo.git

![github_desktop_authentication_failed](https://user-images.githubusercontent.com/12223613/56578374-75278e00-65c5-11e9-8d37-312b4aaf98a3.png)
> Authentication error showing up after clicking fetch.

### Logs

[2019-04-23.desktop.production.log](https://github.com/desktop/desktop/files/3107239/2019-04-23.desktop.production.log)

**Comment by steveward** [comment]
@csalmeida thanks for opening this issue! Here's the relevant line in the log file:

```
2019-04-23T00:55:06.096Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

It looks like you just need to verify GitHub's public host key -- to do this you can run a command from Git Bash or whatever your preferred shell is:

`ssh git@github.com`

You should be prompted to verify the key when running that command. After doing that, try pushing/pulling in GitHub Desktop again and let me know if you run into any issues.

**Comment by csalmeida** [comment]
Thank you @steveward for looking into it!

Following your advice I've ran the command on Git Bash:

```
$ ssh git@github.com
```
```
The authenticity of host 'github.com (140.82.118.3)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Failed to add the host to the list of known hosts (/c/Users/almeida/.ssh/known_hosts).
PTY allocation request failed on channel 0
Hi csalmeida! You've successfully authenticated, but GitHub does not provide shell access.
Connection to github.com closed.
```

Unfortunately I still get the same error. I'll keep looking into it and post updates here.

**Comment by steveward** [comment]
@csalmeida it looks like it's failing to add the key to your `known_hosts` file:

`Failed to add the host to the list of known hosts (/c/Users/almeida/.ssh/known_hosts).`

Can you check to see if that file exists on your machine? Can you also verify that the permissions are set correctly for that directory? That could be a cause of this error.

**Comment by csalmeida** [comment]
@steveward it was related with `known_hosts`, now it is working as expected. Thank you very much for your help!

I have removed the `known_hosts` file from the directory (it was empty) and ran the command again.
For documentation, here is the log I got:

```
$ ssh git@github.com
```
```
The authenticity of host 'github.com (140.82.118.4)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.118.4' (RSA) to the list of known hosts.
PTY allocation request failed on channel 0
Hi csalmeida! You've successfully authenticated, but GitHub does not provide shell access.
Connection to github.com closed.
```

Subsequently, I have attempted to push a few commits using Desktop and it worked. 🎉

**Comment by steveward** [comment]
@csalmeida I'm glad to hear that got things working for you! I'm going to close this issue out.
