### ISSUE TITLE
Can not logging in

### ISSUE THREAD

**Issue by CanftIn** [desktop/desktop#7385]
## Description
I downloaded the [AUR github-desktop-bin](https://aur.archlinux.org/packages/github-desktop-bin/) and installed, and I follow the step: select `File` > `Options` > `Accounts` then log in, with correct user name and password I can not log in github desktop.

## Version

* GitHub Desktop: Version 1.6.5-linux6

* Operating system: ArchLinux(Kernel: x86_64 Linux 5.0.7-arch1-1-ARCH)

## Steps to Reproduce

1. open github-desktop and add my local exist repository.
2. add new file in my local repo.
3. go in github-desktop and add file then commit
4. after commit this happens：
![2019-04-23-201620_581x452_scrot](https://user-images.githubusercontent.com/26135447/56580327-e5a1cf80-6604-11e9-8361-0ed6587b0d5a.png)
5. after inputting correct name and password:
![2019-04-23-201639_660x260_scrot](https://user-images.githubusercontent.com/26135447/56580328-e63a6600-6604-11e9-9169-9341beb2094e.png)
6. I try to follow the step: select `File` > `Options` > `Accounts` then log in, the
situation still happen. Error message:
```
No such interface 'org.freedesktop.Secret.Collection' on object at path /org/freedesktop/secrets/collection/login.
```

### Expected Behavior
Logging in github desktop and can commit files.

### Actual Behavior
Authentication failure and
```
No such interface 'org.freedesktop.Secret.Collection' on object at path /org/freedesktop/secrets/collection/login.
```

### Logs
[2019-04-23.desktop.production.log](https://github.com/desktop/desktop/files/3107457/2019-04-23.desktop.production.log)

**Comment by shiftkey** [comment]
@CanftIn thanks for the report!

> I downloaded the AUR github-desktop-bin 

We're tracking issues with the unofficial Linux releases over on my fork - https://github.com/shiftkey/desktop - please submit an issue there, so I can investigate separately and allow the team to focus on the platforms officially supported currently.
