### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by RanDumSocks** [desktop/desktop#7390]
## Description
When doing anything with private repositories, I get an Authentication Failed error. Was working about a month ago, but just recently when I tried using it, I get this error every time. Pushing and pulling through the GIT Bash works just fine with the same credentials.

## Version
* GitHub Desktop: 1.6.5
* Operating system: Windows 10

## Additional Information
It shows that I am logged in to the correct account, and I can push / pull on public repositories. I have signed out / signed back in, nothing worked. Also uninstalled / reinstalled, again nothing changed.

So I know the logs say I have bad credentials, but they work for everything else. I even revoked the OAuth access from GitHub Desktop to see if that was bad (somehow?) and that didn't work. I've tried signing in via browser and username/ password, same results.

I am clearly the owner of the repository and It also doesn't work for any private repository I own.

Hopefully this is enough starting information, left some areas out because they are self-explanatory and repetitive.

### Logs
```
2019-04-23T23:28:25.632Z - warn: [ui] fetchPullRequests: failed for repository randumsocks/GMS_col
Error: Bad credentials
    at Object.t.parsedResponse (C:\Users\[Private Info]\AppData\Local\GitHubDesktop\app-1.6.5\webpack:\app\src\lib\http.ts:161:4)
2019-04-23T23:28:25.633Z - warn: [ui] Error refreshing pull requests for 'GMS_col'
Error: Bad credentials
    at Object.t.parsedResponse (C:\Users\[Private Info]\AppData\Local\GitHubDesktop\app-1.6.5\webpack:\app\src\lib\http.ts:161:4)
2019-04-23T23:28:53.561Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/RanDumSocks/GMS_col.git/'

(The error was parsed as 3: Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.)
2019-04-23T23:30:25.261Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.028s)
2019-04-23T23:30:26.195Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Randumsocks.github.io - RanDumSocks (has token)
2019-04-23T23:30:33.856Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/RanDumSocks/GMS_col.git/'

(The error was parsed as 3: Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.)
```

**Comment by RanDumSocks** [comment]
Update: Can say that it worked the 9th of this month but not the 10th. Nothing changed between those two days. I did not push on the 10th, but I did commit so I didn't see the error until the next week.

**Comment by steveward** [comment]
Thanks for the report @RanDumSocks. Can you try resetting GitHub Desktop by following these steps?

1. Close GitHub Desktop
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop and log in and add your repositories again

Let me know if that does not help with this issue.

**Comment by RanDumSocks** [comment]
That did not fix the issue, same authentication error as usual. I will try to use it on another computer and see if it goes through then to see if it could be a GitHub problem, but it still wouldn't rule the Desktop app out. Just odd that I didn't do anything between when it worked then failed.

**Comment by RanDumSocks** [comment]
More testing: My repos show up when going to clone one from my account, but it won't actually let me clone because of an authentication error again.

**Comment by steveward** [comment]
>More testing: My repos show up when going to clone one from my account, but it won't actually let me clone because of an authentication error again.

It sounds like API requests are working, but the actual Git processes are failing. Do you have any other Git applications installed on your machine other than GitHub Desktop and Git for Windows?

When you uninstalled/reinstalled did you also delete the `%LocalAppData%\GitHubDesktop` directory prior to reinstalling? That may be worth trying in case there is an issue with your local installation of GitHub Desktop.

**Comment by RanDumSocks** [comment]
I only have those two installed and yes I deleted the data before reinstalling. I'll try fiddling with it later this evening again and see if I can get something to work. I've just been using git bash for the time being.

Have not looked at it from a different computer mainly because my laptop is trash-tier and can barely boot chrome.

**Comment by RanDumSocks** [comment]
Sorry it has been awhile since last update, been busy. I tried removing the contents of `%LocalAppData%\GitHubDesktop` before installation again and no luck. I've just been fully using Bash during this time and have had no problems at all there. I cannot get Github Desktop on my other really crappy computer so I can't test if it is isolated to my main computer where I am getting the error. I might just borrow someone else's computer to test there because this is still odd and frustrating. I'll get back when I have another update.

**Comment by RanDumSocks** [comment]
Alright was able to test it on another computer just to be 100% sure, and it works perfectly on other computers using the same OS. Sorta at a loss here.

**Comment by RanDumSocks** [comment]
Oh my god, figured it out and I feel dumber than ever.

I changed my registry that day to autorun `chcp 65001` temporarily for a project that I was too lazy to type in every time when bringing up the command prompt. Forgot about it until today when something else failed to run and was related. Sorry to waste your time.

**Comment by steveward** [comment]
@RanDumSocks thanks for the update! I'm glad to hear things are working for you again.
