### ISSUE TITLE
improve "discard all changes" UX

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#7394]
**Please describe the problem you think should be solved**

For the longest time we've had the ability to discard all changes by right-clicking the "Changes" header:

<img width="314" src="https://user-images.githubusercontent.com/359239/56691540-95834580-66b6-11e9-8310-1a42082bb72f.png">

This was available on at least the classic Windows app, and it came over in #1647 because we needed _somewhere_ to keep this functionality. Context menus for non-interactive elements like headers aren't very intuitive, but we marched on.

Then we added it to the context menu for a changed file in #4188 (requested in #4314):

<img width="453" src="https://user-images.githubusercontent.com/359239/56691617-bfd50300-66b6-11e9-91e4-15f4d83ac123.png">

This has lead to some confusion in #5342 because it is right next to the "Discard Change" menu item, and if a user doesn't have the "Confirm Discard Changes..."  setting enabled they could accidentally move all the files to the trash.

This combination of "header context menu" and "item context menu" makes me think that neither place is the right place for this functionality.

**[Optional] Do you have any potential solutions in mind?**

in https://github.com/desktop/desktop/issues/5342#issuecomment-457417470 we identified a list of changes that will help us to improve this area: 

> I think we can solve this through implementing these four things, I believe in this order:
> 
> 1. Remove `Discard All Changes` from file context menu
> 2. Add `Discard All Changes` as a top menu item
> 3. Remove `Discard All Changes` from the header context menu
> 4. Add a UI menu to the changes top bar (containing `Discard All Changes` and potential future actions)
> 
> For anyone who picks this up:
> 
> For 2, I think `Discard All Changes` should live in `Branch` > `Discard All Changes` in a new section between the first and the second section.
> 
> For 4, I think we can wait and see how 1-3 feels first before implementing.

**Comment by shiftkey** [comment]
We've made this point before but it got buried in a more complex issue: https://github.com/desktop/desktop/issues/5342#issuecomment-457417470

**Comment by tierninho** [comment]
One option is to combine the `Discard all Changes` and the `check all` toggle under one cog icon that opens a drop down. This opens the door to add other functionality if needed, like potentially adding the `Undo` button. 

<img width="227" alt="56692795-5c000980-66b9-11e9-8020-d9e0cfedae12" src="https://user-images.githubusercontent.com/14828183/56703828-6238ba80-66a6-11e9-83e2-e8b346cf43a7.png">

**Comment by shiftkey** [comment]
I've updated the issue body to mention the list of changes we proposed, and I'm going to mark this as `help-wanted` for someone to pick up.

**Comment by ahuth** [comment]
Should be resolved in #7415, with the Discard All Changes item moved to the Branches menu.

**Comment by karimcambridge** [comment]
WHY?

There was nothing wrong with the placement of this, both could've existed. The place where it was before actually made alot of sense. But... OK.

**Comment by kylefox** [comment]
I miss the "Discard all changes..." context menu 😕I _never_ would've thought to look under the "Branch" menu item.

**Comment by xv** [comment]
This is such a 💩 change. It doesn't make any sense having this option hidden in the Branch menu. I wasted a good five minutes trying to find the damn option, in which I still didn't and had to come here only to know where it is by reading @kylefox's comment. Bring the old stuff back. Terrible UX choice.

**Comment by shiftkey** [comment]
Please follow along with our discussion about this in #7696

**Comment by JosephTLyons** [comment]
Bring back the old functionality or add the gear icon as a button for a drop-down menu.  Putting this ONLY in a menu has completely screwed with how quickly and efficiently I can work with Desktop.
