### ISSUE TITLE
Update icons for merge/rebase status

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7404]
We decided to remove the green checkmark when a branch is up-to-date in the midst of a merge or rebase. The checkmark for the other action will remain as-is.

**Remain:**
<img width="426" alt="Screen Shot 2019-04-25 at 9 29 04 AM" src="https://user-images.githubusercontent.com/14828183/56766116-63202980-6744-11e9-9735-3a6f475da0b3.png">
<img width="430" alt="Screen Shot 2019-04-25 at 9 34 40 AM" src="https://user-images.githubusercontent.com/14828183/56765913-dffed380-6743-11e9-8bf9-0d4cbf9500bb.png">

**Remove:**
<img width="440" alt="Screen Shot 2019-04-25 at 9 28 57 AM" src="https://user-images.githubusercontent.com/14828183/56766115-63202980-6744-11e9-8eb1-d28fa0a8ebfd.png">
<img width="436" alt="Screen Shot 2019-04-25 at 9 34 46 AM" src="https://user-images.githubusercontent.com/14828183/56765914-dffed380-6743-11e9-8c93-f81592909dbd.png">

1.7.0-beta5, mac

**Comment by shiftkey** [comment]
This is handled by [`app/src/ui/lib/action-status-icon.tsx`](https://github.com/desktop/desktop/blob/8b48476bd9338bf39a677165e3fe6b1ba3f5e4cd/app/src/ui/lib/action-status-icon.tsx#L28) and the `status` prop should be `null` in this situation to not render anything:

https://github.com/desktop/desktop/blob/8b48476bd9338bf39a677165e3fe6b1ba3f5e4cd/app/src/ui/lib/action-status-icon.tsx#L8-L10

**Comment by tierninho** [comment]
Closing this as it has not come up enough times to be validated as a real problem.
