### ISSUE TITLE
Logged into a secondary account somehow

### ISSUE THREAD

**Issue by unsoluble** [desktop/desktop#7405]
## Description

I'm signed into a particular GitHub account (via Preferences > Accounts), but somehow the rest of the UI thinks I'm signed into a different account. The user photo next to the Summary line is from this other account, and any commits I make in the app are also made under the name of this other account. (To be clear, this other account is another one of my own, that I have used in the past, not some random other person's.)

I can't find a way to purge this other account from the UI, so that my commits can be made from the account I'm nominally signed into the app with. Have tried signing out of the main account and signing back in.

![Screen Shot 2019-04-25 at 1 26 26 PM](https://user-images.githubusercontent.com/801582/56766250-d4200b00-675d-11e9-9569-b48147f6c731.png)

![Screen Shot 2019-04-25 at 1 26 10 PM](https://user-images.githubusercontent.com/801582/56766252-d6826500-675d-11e9-8126-9b62b7f70e54.png)

## Version

* GitHub Desktop: 1.6.5

* Operating system: macOS 10.14.4

## Steps to Reproduce

Can't figure out how to reproduce this dual-account result.

### Expected Behavior

Not be shadow-logged into two accounts in the app.

### Actual Behavior

Somehow logged into two accounts.

**Comment by steveward** [comment]
Thanks for the report @unsoluble. My guess is that global gitconfig file on your machine has the user.email value set to an email address that is being used by a different GitHub user, which is causing their avatar to be shown. You can check this by going to the menu and selecting `GitHub Desktop` > `Preferences` > `Git`. Make sure the email address matches an email associated with our GitHub account. You can read more about commit attribution here:

https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user

Let me know if that does not get things working for you.

**Comment by unsoluble** [comment]
Aha! Thanks Steve, that was it. (Wasn't obvious, because the email that was in there was already mine, just not the one that's associated with the primary account I wanted to be using.)

**Comment by billygriffin** [comment]
Thanks @unsoluble! We're also looking at this in #610 and hoping to start to actually think about design for that in the next few months. We see lots of people run into confusion between their Git author info and their GitHub account, so thanks for helping us confirm how this happens.
