### ISSUE TITLE
Duplicate file conflicts with stash

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7408]
Bringing over a duplicate file with the Switch Branch feature results in the file being deleted and a console error:

```
install.ts:23 `git stash pop stash@{0}` exited with an unexpected code: 1.
three copy.txt already exists, no checkout
Could not restore untracked files from stash entry
```

The error is surfaced when you click the `Restore` button, even though nothing is in the Changes list.

![image](https://user-images.githubusercontent.com/14828183/56772599-602e3480-6756-11e9-807a-c535ebc8b13a.png)

Reproduce:
- stash file x on a branch
- go to another branch and work on same file
- bring that file over to the branch with the stash on it
- file is delete and error is shown

1.7.0beta5, mac

**Comment by outofambit** [comment]
@tierninho could you try to reproduce this on the latest beta (`1.7.1-beta1`)? i think this may have been fixed in some of the recent refactoring we've done.

**Comment by tierninho** [comment]
Yes, all fixed up 👍
