### ISSUE TITLE
Block restoring a stash if files in Changes list present

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7409]
The app is still allowing stashed files to be restored if files are present in the Changes list. Seems like a regression.

`Restore` button is enabled and working:
![image](https://user-images.githubusercontent.com/14828183/56772822-40e3d700-6757-11e9-9e1c-422cab98cb18.png)

1.7.0beta5, mac

**Comment by outofambit** [comment]
@tierninho thanks for catching this. sounds like the logic for this button is straight up not working.

> Restore button is enabled and working:

were you able to successfully pop that stash into the working directory? or did you encounter an error then?

**Comment by tierninho** [comment]
> were you able to successfully pop that stash into the working directory? or did you encounter an error then?

@outofambit was a clean restore with no errors.
