### ISSUE TITLE
we were unable to authenticate with github.com. please enter username and password to try again

### ISSUE THREAD

**Issue by Phil-Factor** [desktop/desktop#7411]
## Description

Created a gist, clicked on the 'save to your computer ...blah..GitHub Desktop'. All worked fine. Created a new gist and saved it to a file in Github directory created by the previous operation. saved in local directory. Tried to push to Github. 'Bang'. "We were unable to authenticate with gist.github.com. Please enter your usemame and password to try again." I did, and repeated etc etc. stuck in endless loop.

## Version

1.6.5
* GitHub Desktop: 

Microsoft Windows [Version 10.0.17134.706]
* Operating system:

## Steps to Reproduce

Step 1: Created a gist, 
Step 2: clicked on the 'save to your computer ...blah..GitHub Desktop'. All worked fine. 
Step 3: Created a new gist and saved it to a file in Github directory created by the previous operation. 
Step 4: saved in local directory. 
Step 5: Tried to push to Github. 'Bang'. 
"We were unable to authenticate with gist.github.com. Please enter your usemame and password to try again."
 Step 6: I  entered my usemame and password to try again
"We were unable to authenticate with gist.github.com. Please enter your usemame and password to try again."
 Step 7: and repeated etc etc. stuck in endless loop.

### Expected Behavior

I expected to be able to create several gists from one repository.
### Actual Behavior

I couldn't. It was baffling. You can have a git repository with more than one file in it If it isn't possible to have more than one Gist I'd expect an error message that told me that, not some misleading stuff about reentering passwords

### Logs

Cant supply these, I've been trying to get an answer for over a month without success

**Comment by steveward** [comment]
Thanks for the report @Phil-Factor. This is a known bug -- when trying to push commits to a gist, GitHub Desktop will fall back to basic authentication and not detect your current credentials. As a workaround for this you should be able to drop into the command line and run a `git push` to push your changes. 

See https://github.com/desktop/desktop/issues/2973 for more information about some of the known issues with using Gists in GitHub Desktop.  I am going to reference this issue in #2973 and close it out for the time being.
