### ISSUE TITLE
Undone file is lost if the same file is in Changes list

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7413]
If you have file X in the Changes list and the same file was also the last commit, then if you attempt to undo that commit, the file is lost and no warning is shown. We have an overwrite warning on stashing, should there be something similar in this case?

Reproduce:
- Commit file X (don't push)
- Make a change to the same file so it now shows in Changes list
- Undo the first commit

Result: undone file is lost without any warning

Expected result: some type of conflict warning is surfaced

![image](https://user-images.githubusercontent.com/14828183/56833635-b8bf0980-680a-11e9-8227-431b091594b0.png)

1.7.0beta5, mac

**Comment by shiftkey** [comment]
> Commit file X (don't push)
> Make a change to the same file so it now shows in Changes list

@tierninho can you elaborate on this bit, in particular how the changes in the working directory overlap with the changes from the previous commit to introduce a conflict?

I went through a short example where the changes do not clash, and the net result is that the working directory changes contain both sets of changes.

Commit contents:
<img width="585" src="https://user-images.githubusercontent.com/359239/57015395-0bbe0580-6beb-11e9-9ce5-d1e8ab130ae4.png">

Working directory change:
<img width="709" src="https://user-images.githubusercontent.com/359239/57015394-0b256f00-6beb-11e9-89ca-bed168812d8a.png">

After undo:
<img width="716" src="https://user-images.githubusercontent.com/359239/57015396-0bbe0580-6beb-11e9-88de-9a58dcab9624.png">

That's what I'd expect to see here, and it's be great to have more information about the steps to trigger what you're seeing.

**Comment by tierninho** [comment]
@shiftkey thanks for the details. Retested this and not an issue.
