### ISSUE TITLE
bringing changes on branch switch resulted in lost changes

### ISSUE THREAD

**Issue by msftrncs** [desktop/desktop#7414]
## Description
Attempting to switch branches while changes exists caused a dialog to appear regarding what to do with the changes.  I selected to move (bring) the changes to the branch I was switching to (master).  The result when the branch switch completed was no changes.

## Version
* GitHub Desktop: 1.7.0-beta5
* Operating system: Win 10 1809

## Steps to Reproduce
In current branch, have 1 changed file.
Switch to different branch.
answer the stash dialog with 'bring my changes'.

### Expected Behavior
I expected my changed file to still be marked changed.

### Actual Behavior
I found no changed files, and my previous changes were not in anyway present.

## Additional Information

Switching back to the original branch did not present any changes or any stashes as available.

I think the log shows an issue …  no stashes matching master.  I was moving to the master branch.  I repeated this issue twice (because the changes were saved in an open editor).  Same result both times.  Note, I also tried to 'leave my changes behind', but when all set and done I still could not find my changes.

### Logs
```
2019-04-26T21:08:22.547Z - info: [ui] Executing createStashEntry: git stash push --include-untracked -m !!GitHub_Desktop<master> (took 3.243s)
2019-04-26T21:08:22.547Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: EditorSyntax - msftrncs (has token)
2019-04-26T21:08:23.950Z - info: [ui] [AppStore._checkoutBranch] no stash found that matches master
2019-04-26T21:28:49.740Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: EditorSyntax - msftrncs (has token)
2019-04-26T21:31:57.278Z - info: [ui] Executing createStashEntry: git stash push --include-untracked -m !!GitHub_Desktop<master> (took 2.425s)
2019-04-26T21:31:57.278Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: EditorSyntax - msftrncs (has token)
2019-04-26T21:31:58.382Z - info: [ui] [AppStore._checkoutBranch] no stash found that matches master
2019-04-26T21:32:53.493Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: EditorSyntax - msftrncs (has token)
2019-04-26T21:33:30.722Z - info: [ui] Executing createStashEntry: git stash push --include-untracked -m !!GitHub_Desktop<build_grammar.ps1> (took 2.372s)
2019-04-26T21:33:30.722Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: EditorSyntax - msftrncs (has token)
2019-04-26T21:33:41.625Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: EditorSyntax - msftrncs (has token)
```

**Comment by outofambit** [comment]
Hi @msftrncs. Thanks for filing this issue and I'm so sorry this happened. I'm guessing that desktop failed to create a stash in both cases, but didn't show an error. (Moving changes from one branch to another uses stashes under the hood.)

I have two questions to help diagnose this:

1. Was the 1 changed file before you switched branches an untracked file or were untracked files present in some way? (wondering if this is related to https://github.com/desktop/desktop/issues/7344)
2. If you're able to run `git stash list` in that repo and send the results, that would be super helpful.

**Comment by msftrncs** [comment]
#7344 is similar, but reported before the current beta.  In this case, the file was already in both branches (not untracked in either).   (you already beat me to asking for this answer.  :)

**Comment by msftrncs** [comment]
`git stash list` is reporting nothing. so it appears no stashes remain.

No untracked files exist, this was the only changed file.  The file in each case appears to restore appropriately for the version in that branch.

**Comment by outofambit** [comment]
ok thank you so much @msftrncs! i'm going to start reproing/diagnosing/fixing this.

**Comment by msftrncs** [comment]
I seem to be having problems with this specific repository.  I am trying to use another tool (VS Code) to perform stashing, which I have used in the past successfully, but not with this specific clone, and while no errors are reported, the stash isn't occurring, and `git stash list` remains empty.

**Comment by outofambit** [comment]
thats very strange. if you try to manually stash with `git stash; echo $?` does it print out anything?

**Comment by msftrncs** [comment]
Result of requested command:

```
Saved working directory and index state WIP on master: 12b7d72 fix #134 (#135)
True
```

`git stash list` still reports nothing.

**Comment by outofambit** [comment]
so `git stash` appears to succeed (and reports a success exit code, `true`), but `git stash list` still doesn't list the stash. i think to diagnose more i'd have to see the contents of `.git` in that repo clone. i wonder if a fresh clone would have the same issues?

**Comment by msftrncs** [comment]
I need to spend more time to diagnose.   I use two different computers.  The one today doesn't seem to work to stash in any repository, but I cannot say for sure I have ever stashed while on this computer, while I know for sure I have stashed on the other computer (all from VS Code).  I am also experiencing a issue in that git is not reporting the status of an upstream repository branch that I know has commits I want to merge, so this is more going wrong.

I'll update once I have a reason for this behavior.

**Comment by msftrncs** [comment]
Found the stashes.  Because I am at work, and I can switch computers in the office when the event arises, I store my repositories on a mapped drive network share.  If I switch to a UNC path to reach the repository, `git stash list` shows all the stashes that have been made, including those from GitHubDesktop, but when run from the mapped drive location, it shows nothing.

## Better detail

Actually, the mapped drive includes a FQDN server (server.domain.tld).  If the FQDN is used to access the repository, GIT fails to see stashes.  The issue is that Windows (at least Win 10) considers FQDN paths to be in the internet zone for security reasons, even though the FQDN is a Windows AD site which is supposed to put it in the intranet zone.  I have an issue open with MS on this, as its been affecting me for a couple years in other areas.  Why its affecting GIT though I have no idea.  But for other apps, files stored on internet zone file shares are considered to be untrusted and causes confirmations before opening.  I have specifically added the FQDN to my intranet zone sites list to remove these confirmations, but it seems that is not enough for GIT STASH LIST.

Seems this was the same reason keeping git from receiving status from upstream repository branches as well.

I think this issue is probably 'double' upstream; MS for the failure with FQDN failing to detect as intranet site, and GIT for not reporting an error that something isn't working.

**Comment by outofambit** [comment]
@msftrncs glad you found them! and thank you for the great summary, there are certainly a lot of pieces in play there. i don't think there's much desktop could have done in this particular situation, so i'm going to close this out, but please comment if that doesn't seem right to you and we can reopen. 💖

**Comment by ianpaschal** [comment]
I have just experienced this on v2.5.4. Unfortunately I don't have any interesting set up like msftrncs, and the logs are empty for the last few hours.
