### ISSUE TITLE
Stash view state is not remembered after restart

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7416]
As we remember other panes width in Desktop, we should include the stash pane. 

Not sure if the temporary state of this feature will affect this request.

<img width="747" alt="Screen Shot 2019-04-26 at 3 36 56 PM" src="https://user-images.githubusercontent.com/14828183/56843252-ff782800-6839-11e9-90cf-ad17e2599dc5.png">

Repro:
- adjust width
- restart Desktop

Note: we also do not remember that Stash page was last shown. After restarting, the next steps is shown instead of the stash page

1.7.0beta5, mac

**Comment by outofambit** [comment]
I've verified that this is the case for _all_ of our panes. I've put together a fix (it was really simple), but i'd like to verify that this is desired behavior before we merge. anyone from @desktop/design want to weight in?
