### ISSUE TITLE
update electron-window-state to get improved checks for missing monitor

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#7418]
I haven't kept up with `electron-window-state` for a while, but it looks like they've landed a fix for the problem we've seen about the app not being restored correctly when the secondary monitor is disconnected #2107 

https://github.com/mawie81/electron-window-state/pull/45

This is available in `5.0.3` on NPM, and I'd love some help from a person with multiple monitor to upgrade our version in `app/package.json` and test this correctly works when performing these steps:

 - launch Desktop, move it to the secondary monitor
 - close Desktop
 - disconnect the secondary monitor
 - launch Desktop

**Expected behaviour:** application is launched on primary monitor at default size

I expect this is relevant to both macOS and Windows users

**Comment by say25** [comment]
I can take this on.
