### ISSUE TITLE
Handle Permission Errors When Stashing

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#7425]
In the comment below, @shiftkey outlines two approaches to fixing #7344. The first was completed in #7351 and this issue is here to continue discussion around the second approach.

________

>  If it turns out permissions would cause stash creation to fail, we can bail and alert the user that we're unable to create a stash due to file permissions and continue with the branch switch as usual.

We actually get this for free from Git - it emits the paths it can't access, and it feels simpler to defer to the actual implementation rather than try and emulate this ourselves. There's some gotchas here (it looks like it creates the stash with the files it could access) but I think that's minor.

I updated #7351 to indicate that it shouldn't close this out, and I think we have two options here if we encounter an error:

 - use the implementation in #7351 and just stash what we can, ignoring the problem paths reported by Git
 - be more conservative with the errors detected and inform the user that some paths could not be stashed, giving them the option to continue with whatever could be stashed

I could happily ship #7351 for the next beta to help the users who have encountered problems with their workflow, but I favour the second option to help make this flow less confusing.

Here's a quick mockup of what the user could see in the case this fails:

<img width="625" src="https://user-images.githubusercontent.com/359239/56590571-b4ea7780-65bd-11e9-899b-17a0a18b856e.png">

_Originally posted by @shiftkey in https://github.com/desktop/desktop/issues/7344#issuecomment-485835757_

**Comment by billygriffin** [comment]
@outofambit What's the current state of this since #7351 was merged? I'm trying to understand whether we need to do anything further here or if we're comfortable closing this until it surfaces as an issue for users in the wild.

**Comment by outofambit** [comment]
@billygriffin This is mostly a placeholder issue for us to revisit this with a more thoughtful design at some point but I'm happy to close this and only revisit this problem if it surfaces again.
