### ISSUE TITLE
Unable to log into Desktop app Mac OS

### ISSUE THREAD

**Issue by ryanoley** [desktop/desktop#7431]
## Description

Unable to log into GitHub Desktop app.  If I log into Desktop via browser I get errors when fetching/push/pull from repositories with the error "Authentication failed.  You may not have permission to access the repository or the repository may have been archived..."

Desktop app was working three days ago, today not so.  I have tried the keychain lock/unlock fix as well as reinstalling the Desktop App and changing the remote settings to http: from https to no avail. 

## Version

* GitHub Desktop: 1.6.5

* Operating system: macOS High Sierra 10.13.6

## Steps to Reproduce

1. Fetch, push, or pull from repository within Desktop App
2.  Fail with authentication error

### Expected Behavior

Expect to authenticate and push/pull/fetch etc.

### Actual Behavior

Errors out.

## Additional Information

I am able to log in via the browser and even log into the Desktop App via the log in from browser link within the app.  It just does not seem the app itself can authenticate.

### Logs

[2019-04-29.desktop.production.log](https://github.com/desktop/desktop/files/3128877/2019-04-29.desktop.production.log)

**Comment by tierninho** [comment]
Thanks for the report @ryanoley . It does look like there is an issue with the token that GitHub Desktop stores:

`Error: Cannot update an account which doesn't have a token: ryanoley`

Can you try logging out and then logging back in to see if that gets things working for you? You can do this by going to GitHub Desktop > Preferences > Accounts.

Let me know if that does not get things working for you!

**Comment by ryanoley** [comment]
Thanks @tierninho.  From the Desktop app I am unable to log in following those steps, I am seeing the image below.  When I follow the link to sign in using the browser it successfully logs me in, but i experience the same error when trying to push to my repositories.  Added my log file again as well.





<img width="403" alt="Screen Shot 2019-04-29 at 3 28 50 PM" src="https://user-images.githubusercontent.com/5911256/56921451-c20ed700-6a93-11e9-935d-350bf4e20924.png">

[2019-04-29.desktop.production.log](https://github.com/desktop/desktop/files/3128909/2019-04-29.desktop.production.log)

**Comment by tierninho** [comment]
@steveward 👋 Any chance you have seen this before and have some more suggested steps? Thanks!

**Comment by shiftkey** [comment]
@tierninho @steveward there's a clue in the output when a Git operation fails, and I wonder if it's related:

```
2019-04-29T19:30:06.627Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
/bin/sh: updatePrompt: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `updatePrompt'
/bin/sh: updatePrompt: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `updatePrompt'
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/ryanoley/lighthouse.git/'
```

@ryanoley do you know what this `updatePrompt` function might be associated with?

**Comment by ryanoley** [comment]
thanks @shiftkey - the updatePrompt function is something i've defined in my bash profile, that is very simple.  I removed it and reproduced the errors in the log below.  I have not ever used SSH so maybe I should give that a try.

[2019-04-29.desktop.production.log](https://github.com/desktop/desktop/files/3128955/2019-04-29.desktop.production.log)

**Comment by ryanoley** [comment]
@shiftkey @tierninho @steveward 
In thinking about the chain of event, I enabled two factor authentication on my account today as well.  I am not certain but I believe the issues began after that.  I have since disabled it and tried signing out/in again on Desktop as well as using a personal access token, but nothing has worked yet.

**Comment by steveward** [comment]
@ryanoley can you try these steps?

- open `Keychain Access.app` and delete the `GitHub - https://api.github.com` entry 
- go to https://admin.github.com/settings/applications and revoke the GitHub Desktop OAuth token
- log out and then log back in to GitHub Desktop

Let me know if that helps at all.

**Comment by ryanoley** [comment]
@steveward  Those steps solved the issue, many thanks.  I am closing the issue.

**Comment by steveward** [comment]
@ryanoley I'm glad to hear that got things working!

**Comment by ryanoley** [comment]
@steveward Unfortunately I am reopening the issue.  This morning I am experiencing the same issue again.  I followed the steps that worked previously, and while I can log into GitHub Desktop following those steps, I still get the same Authentication error when fetching/pushing/pulling.  Log attached.

[2019-04-30.desktop.production.log](https://github.com/desktop/desktop/files/3131403/2019-04-30.desktop.production.log)

**Comment by ryanoley** [comment]
@steveward I have changed to SSH and it seems to be working now in Desktop as well as command line.  I will close the issue again and reopen if it comes back again.
