### ISSUE TITLE
java.nio.file.AccessDeniedException:

### ISSUE THREAD

**Issue by GunMonkey7** [desktop/desktop#7436]
## Description

I get this error and I am not sure why it is denying me access. (java.nio.file.AccessDeniedException) I have connected multiple projects to Github and have had this issue 3 times now and I can not figure out how to solve it. I store my Github file on my one drive. 

## Version

* GitHub Desktop:

* Operating system:
windows 10

## Steps to Reproduce

1. link project to Github repository successfully
2. I changed my theme or cleaned up temporary files
3. Just locks a file that my project is trying to use.

**Comment by tierninho** [comment]
@GunMonkey7 Thanks for reporting. Possible to include your logs so we have more information? 

To access the log files go to the file menu in `GitHub Desktop` and select `Help > Show Logs` in Finder (macOS) or Explorer (Windows).

Did you appended the new file name to the path? Examples:

👎 `rootDirectory = "C:\\safesite_documents"`
👍 `rootDirectory = "C:\\safesite_documents\\newFile.jpg"`

**Comment by tierninho** [comment]
@GunMonkey7 As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
