### ISSUE TITLE
Branch filter persistence causes confusion when trying to switch branches

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#7437]
**Please describe the problem you think should be solved**

In a usability test yesterday for stashing, someone really struggled with the branch filter persisting information from a previous filter because they couldn't figure out why `master` wasn't showing in the list of branches. We did that for consistency, but I think it may cause more issues than it helps, and I'd love to revisit that decision.

1. Create a new branch via the branch filter box

<img width="460" alt="Screen Shot 2019-04-30 at 12 07 27 PM" src="https://user-images.githubusercontent.com/5091167/56983312-90077e80-6b40-11e9-9c7a-b1600e865e7b.png">

2. After branch is created, click branch dropdown to try to switch back to `master`
3. Be confused because `master` (or any other branch you'd want to switch to) is nowhere to be found.

<img width="460" alt="Screen Shot 2019-04-30 at 12 09 13 PM" src="https://user-images.githubusercontent.com/5091167/56983426-d65cdd80-6b40-11e9-82f9-1120e936c7ee.png">

**Do you have any potential solutions in mind?**

After you've switched to a new branch, it seems like clearing the filter text would be a reasonable approach. I know we've heard that for the repo filter, not clearing it can be helpful because you can filter by similar types of repos (and soon by org!), but I'm skeptical that the value that provides on branches outweighs mitigating the confusion that arises by not understanding why you're only seeing the filtered branches when trying to switch to a different branch.

This was originally raised in #6002 and the PR was #6088

cc: @tierninho @Daniel-McCarthy

**Comment by iAmWillShepherd** [comment]
I think clearing the filter after creating a new branch is the right approach. Keeping that filter text around after the branch has been created doesn't feel right to me because the user would have just used that input to _create_ a branch, not _search/filter_ for one.  Overall, I think it's more valuable to ensure we aren't confusing folks.

To recap, I'm suggesting we clear the filter text once the new branch has been created.

**Comment by tierninho** [comment]
+1 for changing it (back). The persisting branch filter isn't as useful here.

**Comment by billygriffin** [comment]
After more consideration and going through multiple flows here, I think we should remove the persistence in _all_ cases, regardless of whether you're just filtering amongst branches to switch to an existing one or creating a new one. 

For the case where you're filtering and switching to an existing branch, when you go to switch branches again, the persistence is actually inconvenient the vast majority of the time because you aren't likely to want to switch back to a branch in that filter, and getting back to a "clean" filter state to show all branches requires an additional keystroke or mouse click to clear the filter.

**Comment by iAmWillShepherd** [comment]
> I think we should remove the persistence in _all_ cases, regardless of whether you're just filtering amongst branches to switch to an existing one or creating a new one.

➕
