### ISSUE TITLE
next InitializeSecurityContext failed: Unknown error (0x80092013)

### ISSUE THREAD

**Issue by LalitSinghRathore** [desktop/desktop#7449]
facing this problem while pulling a repository from github.
please solve it.

next InitializeSecurityContext failed: Unknown error (0x80092013)

**Comment by shiftkey** [comment]
@LalitSinghRathore thanks for the report!

This error sometimes occurs when Git is unable to perform the certificate revocation checks when verifying its connection. We have more context and a workaround outlined here - please try it out and confirm that it works for you:

https://github.com/desktop/desktop/blob/development/docs/known-issues.md#certificate-revocation-check-fails---3326

**Comment by shiftkey** [comment]
@LalitSinghRathore I'm going to close this out as we have a known workaround, but please reach out if you have any other questions.
