### ISSUE TITLE
Github desktop will not let me clone my own repository

### ISSUE THREAD

**Issue by stevenrwood** [desktop/desktop#7454]
### Description
Trying to clone my own repository using Github Desktop app and I get authentication failed even though I am signed into my account.

### Version
GitHub Desktop: 1.6.5
Operating system: 64 bit Windows 10, Build 1809, fully patched

### Steps to Reproduce:
Go to https://github.com/stevenrwood/humbay_BoardTest and click on Clone or download button and select Open with Desktop option.

In desktop app, click on Clone button.   It then displays Authentication Failed popup, even though Github desktop shows me signed in to my account.   I do NOT have two factor auth enabled.   

### Expected Behavior
That I can clone repositories I created.

### Actual Behavior
Authentication failure even though signed in.

### Additional Information

Clone dialog:
![Github Clone](https://user-images.githubusercontent.com/50087820/57088503-4b522380-6cb7-11e9-931d-c36aba32aa44.png)

Authentication Failed popup:
![Github Clone fail](https://user-images.githubusercontent.com/50087820/57088528-57d67c00-6cb7-11e9-802b-53d229edded3.png)

Desktop shows me signed in:
![image](https://user-images.githubusercontent.com/50087820/57087749-9bc88180-6cb5-11e9-8e12-4eda4dba39b7.png)

**Comment by say25** [comment]
@stevenrwood could you upload the logs from you machine?

Seeing you are on Windows try `%APPDATA%\GitHub Desktop\logs\*.desktop.production.log`

**Comment by stevenrwood** [comment]
[2019-04-26.desktop.production.log](https://github.com/desktop/desktop/files/3138972/2019-04-26.desktop.production.log)
[2019-04-27.desktop.production.log](https://github.com/desktop/desktop/files/3138973/2019-04-27.desktop.production.log)
[2019-04-28.desktop.production.log](https://github.com/desktop/desktop/files/3138974/2019-04-28.desktop.production.log)
[2019-04-29.desktop.production.log](https://github.com/desktop/desktop/files/3138975/2019-04-29.desktop.production.log)
[2019-05-02.desktop.production.log](https://github.com/desktop/desktop/files/3138976/2019-05-02.desktop.production.log)
[2019-04-24.desktop.production.log](https://github.com/desktop/desktop/files/3138977/2019-04-24.desktop.production.log)
[2019-04-25.desktop.production.log](https://github.com/desktop/desktop/files/3138978/2019-04-25.desktop.production.log)

**Comment by shiftkey** [comment]
@stevenrwood thanks for the logs. Looking at the most recent one, I can see that we're rejecting the token that the app has stored:

```
2019-05-02T15:34:50.661Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/stevenrwood/humbay_BoardTest.git - stevenrwood (has token)
...
2019-05-02T15:34:51.916Z - error: [ui] `git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/stevenrwood/humbay_BoardTest.git C:\Users\steve\Documents\GitHub\humbay_BoardTest` exited with an unexpected code: 128.
Cloning into 'C:\Users\steve\Documents\GitHub\humbay_BoardTest'...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/stevenrwood/humbay_BoardTest.git/'

(The error was parsed as 3: Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.)
```

Could you try signing out and in again to see if that changes the behaviour?

**Comment by stevenrwood** [comment]
Signed out of desktop and signed back in again.   No change in behavior.   Still get Authentication Failed when trying to clone

**Comment by steveward** [comment]
@stevenrwood thanks for trying that out. Has cloning previously worked for you on this machine? Are you successfully able to clone via the command line?

Could you open the Windows Credential Manager and go to Windows Credentials -> Generic Credentials to verify that a `GitHub - https://api.github.com/stevenrwood` entry exists there?

**Comment by stevenrwood** [comment]
I have three entries.   I was before I had to reformat my hard drive.   Since then I haven;t been able to clone my own repositories.   I can clone other third party repositories.

![image](https://user-images.githubusercontent.com/50087820/57114573-b541eb80-6cfe-11e9-86bf-5062db210b3a.png)

**Comment by stevenrwood** [comment]
So I deleted all 3 credentials, uninstalled desktop, reinstalled desktop, which autologged me in using some other copy of saved credentials.   Signed out, signed in again.   Now I just have one saved credential for github, the api.github.com one.   No change in behavior.   Still get Authentication Failed popup when cloning my repository,

**Comment by steveward** [comment]
@stevenrwood try resetting GitHub Desktop by following these steps:

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop and try logging in and then cloning

**Comment by stevenrwood** [comment]
Done.   No change in behavior.  :(

**Comment by angeloprevitali** [comment]
Same thing here with me with W10 latest build 1809 and GitHub Desktop version 1.6.5. 
Works again with auth only by removing all of the files in %APPDATA%\GitHub Desktop\

**Comment by steveward** [comment]
@stevenrwood I'm sorry that nothing has worked yet. Would you be willing to try creating a new Windows user account on your machine to see if you are able to reproduce this issue there? GitHub Desktop installs on a per-user basis, so that may help narrow down if there is a specific configuration issue with your current user account that is causing authentication to fail.

**Comment by steveward** [comment]
@stevenrwood have you possibly modified the registry on your machine? Some users have reported modifying the command processor's AutoRun setting (`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor\Autorun`) has caused these authentication issues.

**Comment by steveward** [comment]
@stevenrwood since we have not heard back from you I am going to close this issue out. If you are continuing to encounter authentication issues please let me know and we can continue to look into this further.

**Comment by nathaneltitane** [comment]
same issue here with a fresh install...

**Comment by newlogics-dsa** [comment]
also seeing same issue (new laptop, fresh install) Was there a solution that worked for anyone?

**Comment by steveward** [comment]
@newlogics-dsa would you mind opening a new issue and filling out the template? Make sure to upload a log file as well so that we can look into any error messages you are encountering.

**Comment by paraneet** [comment]
Same issue happening for me too

**Comment by kkennedy41** [comment]
Same here. Even with a new SSH key

**Comment by ayako00** [comment]
I also have trouble this issue.

**Comment by palakbaid95** [comment]
Same issue with me. It says Authentication failed. 
I have tried many things still unable to clone the repositories.

**Comment by tierninho** [comment]
If anyone is have issues with authentication, please [open a new issue](https://github.com/desktop/desktop/issues/new?template=bug_report.md) so we can troubleshoot each one individually. Thank you!
