### ISSUE TITLE
Get a list of tags and to switch between them

### ISSUE THREAD

**Issue by velara3** [desktop/desktop#7458]
**Please describe the problem you think should be solved**
Get a list of tags and switch between them

**Example:**
Get a list of tags and show in the UI, the same as `git tags`

When double clicking a tag row, switch to that tag. The same as `git checkout mytag`.

Related but not the same: https://github.com/desktop/desktop/issues/4829
The UI here is tolerable: https://github.com/desktop/desktop/issues/4829#issuecomment-397563372

**Comment by tierninho** [comment]
@velara3 Thanks for the suggestion. Your request was added to the #4829 issue and will be considered when/if the feature moves forward.
