### ISSUE TITLE
Is there difference between commit from github desktop and commit through browser?

### ISSUE THREAD

**Issue by ccppoo** [desktop/desktop#7465]
![image](https://user-images.githubusercontent.com/46418312/57175953-14356b00-6e8d-11e9-8d87-933a8031444b.png)

As I said on title, I can't see my pull request or commits in browser github but on github desktop, I can see my commitment which makes me unclear if this commit is properly done.

History on the right of the image matches with the one I could see in browser.

**Comment by shiftkey** [comment]
@ccppoo thanks for the feedback!

Pull Requests are a different part of the site to what you're looking for, and I can show you how to find the commits for the branch on the GitHub site.

What you'll need to know is the current branch, which is found here:

<img width="512" src="https://user-images.githubusercontent.com/359239/57224891-1dcfe780-6fe1-11e9-8ca9-09193d0ce9cd.png">

Once you know the branch you want to work with, click on the **Code** tab to see the commits for the repository.

If you're not on the same branch as you are in the app, change it here:

<img width="407" src="https://user-images.githubusercontent.com/359239/57224936-448e1e00-6fe1-11e9-9796-0d1d066258a6.png">

Then click on the **Commits** link above to see the history of this branch:

<img width="346" src="https://user-images.githubusercontent.com/359239/57225023-80c17e80-6fe1-11e9-80f7-c6919b4d2b59.png">

That should contain the same commits as your local repository in GitHub Desktop.

Let me know if you have any other questions!

**Comment by shiftkey** [comment]
@ccppoo I'm going to close this out as resolved, but feel free to comment here if you have any other questions.

**Comment by ccppoo** [comment]
Thanks for really precise guide.
Hope that this could be a nice guide line for starters like me
