### ISSUE TITLE
Commit message area positioning and size

### ISSUE THREAD

**Issue by ahuth** [desktop/desktop#7466]
I tend to write long commit messages (particularly the "description"). Doing so in Desktop can be a little cumbersome because:

1. The commit message area is pretty small (as noted in #1646).
2. It's also in the lower left part of the screen.

Does you think the commit message writing experience could be improved by:

- Moving the commit message area to the top, over the changes (AKA, front and center)
- Expanding as needed as the commit message gets longer (instead of scrolling)
- Maybe even show a vertical line (wrap guide) at 80 characters

Could look something like:

<img width="1792" alt="writing up front" src="https://user-images.githubusercontent.com/2503289/57189019-a81f2b00-6ebd-11e9-9ac3-615b00b660c0.png">

Was inspired by Sublime Merge's writing area:

<img width="1792" alt="sublime merge" src="https://user-images.githubusercontent.com/2503289/57189028-c84eea00-6ebd-11e9-8c25-f412dc482f20.png">

Happy to work on this if we think it's a good idea. Either way, thank you for creating this great piece of software!

**Comment by shiftkey** [comment]
@ahuth thanks for the feedback and suggestion!

I'm going to merge this into #1646 to keep this discussion in one place.
