### ISSUE TITLE
Can't clone or pull until re-sign in

### ISSUE THREAD

**Issue by XOR-LIFE** [desktop/desktop#7467]
## Description
I'm experiencing several issues related to communicating to my repos in any way such as cloning or pulling. The problems are fixed by signing out and then sign in back again.

## Version

* GitHub Desktop:
1.7.0 beta6
* Operating system:
windows 7 x64 home premium

## Steps to Reproduce

![1](https://user-images.githubusercontent.com/48298063/57196280-c76c9580-6f5b-11e9-88cb-95d35a6f5d33.gif)

### Logs

[2019-05-05.desktop.beta.log](https://github.com/desktop/desktop/files/3145700/2019-05-05.desktop.beta.log)

**P.S.: I think that GitHub desktop should automatically create a directory for every cloned repo instead of throwing that error "the folder contains files. Git can only clone to empty directories"**

**Comment by shiftkey** [comment]
@XOR-LIFE thanks for the feedback.

The clue from the log file is that the app isn't able to find the token associated with the account:

```
2019-05-05T09:46:18.192Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: cryptochat - XOR-LIFE (empty token)
```

We store this in the Windows Credential Store, and maybe something has changed to cause it to be removed?

As you mentioned, signing in again will create and store a new token, which is what we recommend in this situation.

I'm going to close this out as resolved.

> P.S.: I think that GitHub desktop should automatically create a directory for every cloned repo instead of throwing that error "the folder contains files. Git can only clone to empty directories"

Would you mind opening a separate bug report for this and walk through the issue in more detail, so we can track it separately?
