### ISSUE TITLE
resporatory

### ISSUE THREAD

**Issue by sarb-mann** [desktop/desktop#7468]
## Description

how to delete resporitory

## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@sarb-mann thanks for the report! 

It's not quite clear to me what your situation is, so I've filled out the template for the GitHub Desktop project, so if you are using the GitHub Desktop app you can help provide more context.

If you're looking for support with using the GitHub website to delete a repository, this link should help: https://help.github.com/en/articles/deleting-a-repository

We also have other support resources on https://help.github.com.
