### ISSUE TITLE
i am unable to clone. it keeps on saying timed out

### ISSUE THREAD

**Issue by Challotte14** [desktop/desktop#7480]
## Version

* GitHub Desktop:

* Operating system:

**Comment by billygriffin** [comment]
Hi @Challotte14, thanks for the issue! Would you mind editing your message to fill out the rest of the template, to include what versions you're using and what steps you took to get into the state where you're seeing that it's timing out. That will help us better diagnose what might be occurring for you.

If you're able to include logs from the `Help` -> `Show Logs in Finder/Explorer` that would be really helpful also. Feel free to respond to this comment when that's updated and we'd be happy to take a look.
