### ISSUE TITLE
tune our CircleCI branches config to align with the other platforms

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#7483]
CircleCI is currently configured to build all refs and tags it receives, which feels excessive.

It'd be great if we could change `.circleci/config.yml` to use the same patterns as our other platforms.

Relevant docs:

 - https://circleci.com/docs/2.0/configuration-reference/#branches
 - https://circleci.com/docs/2.0/configuration-reference/#tags

**Comment by outofambit** [comment]
we'll probably move to github actions before we do this.
