### ISSUE TITLE
Selecting a PR that you're already on attempts to switch to the same branch

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7487]
When selecting a PR from the list when you have changes pending, the Switch Branch dialogue  asks you to stash on the associated branch or move your changes to the same branch. Because selecting a PR causes your branch to switch, it confuses the dialogue.

Setup:
- have at lease one PR and one change

Reproduce:
- select the PR from the PR list
- select bring my changes to new branch
- select same PR from the PR list
- both branches in the dialogue are the same

![image](https://user-images.githubusercontent.com/14828183/57405866-2eb46080-717b-11e9-8377-91a35097d107.png)

v1.7.0-beta6, mac

**Comment by billygriffin** [comment]
I think the desired behavior here is that if you select a PR branch and you're already on that branch, the dropdown goes away and you just remain on the same branch. It should work the exact same way as being on a branch and selecting the branch you're already on in the branch dropdown list.

**Comment by tidy-dev** [comment]
Followed:

- select the PR from the PR list
- select bring my changes to new branch
- select same PR from the PR list
- both branches in the dialogue are the same

It did not open a dialog with same branch. It simply did nothing since there isn't anything to switch to.
