### ISSUE TITLE
Refreshing Pull Request list results in text flicker

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7492]
If you refresh the Pull Request list when no results found in the filter, the placeholder text will flicker.

Reproduce:
- go to the PR list under the Branches tab (you do not need a PR to reproduce)
- click the refresh icon

![May-08-2019 15-10-16](https://user-images.githubusercontent.com/14828183/57420528-a39b9080-71a3-11e9-8765-96b55b6040a7.gif)

Expected result: text does not flash

tested in v1.7.0beta6, mac

**Comment by samuelko123** [comment]
Hi @sergiou87, may I create a PR to fix this bug?

I recently started using Github Desktop, and loved the work you guys have done.
Therefore, I hope to contribute by raising PRs (starting with fixing little bugs like this).

**Comment by paradijs** [comment]
Allright

**Comment by battsteam** [comment]
Ok

**Comment by sergiou87** [comment]
Per my comment here: https://github.com/desktop/desktop/pull/16580#pullrequestreview-1397551006

We're not gonna fix this as it's just a very tiny issue with no perfect solution. Sorry!
