### ISSUE TITLE
New files get added automatically even with non-empy commit summary or description

### ISSUE THREAD

**Issue by magiblot** [desktop/desktop#7493]
I am used to the CLI version of git. When I want to make a commit, I do `git add` on select files and then write the description of the commit.

Thankfully, the GUI helps me divide the changes among atomic commits, so I follow the same steps. I pick the files/lines I want to commit and then write a description. However, in the middle of the process, some doubts arise and I decide to test a bit more. In order to perform this checks, I might create new folders or files. Once everything is settled, I switch back to the GUI, I finish describing the changes and finally I commit them.

However, when reviewing the history, I find out that my commits include some undesired files: yeah, the temporary files I created while preparing the commit description, which I never chose to be in the commit. Indeed, GitHub Desktop added those changes without my consent and without me noticing, breaking the behaviour of git.

Now that I got this off my chest, I'd like to give a constructive point of view on this. In general, I'd like to be able to turn off the 'proactive' behaviour of GitHub Desktop, that is, the automatic selection of changes. Not only because deselecting all changes is the first thing I do when opening the GUI, but also because I stick to this idea of 'a program should not do something I did not tell it to do', although the latter is just a personal preference.

However, I think this specific case of changes happening while the description is being written is very clear: in no case should any changes be added silently. There should be at least some kind of visual, non-obtrusive warning so that the user can notice what's going on. There is no need for warnings if there is no proactive addition, but other people might rely on it, so I'd rather have an option so that everyone can set this behaviour to their needs. Making an option for this also relieves you from having to decide what's better and what's worse.

Thank you very much.

**Comment by shiftkey** [comment]
@magiblot thanks for the feedback! We've had a couple of discussions about this behaviour and #1788 is probably the best place to read. I currently defer to what @billygriffin shared at the end of that issue:

> However, after talking through this based on our experience to date, we just haven't seen this come up as a frequent pain point for many users. If we swapped the default, a ton of users who enjoy the way it works today would be furious, and generally we prefer to keep toggles to only the highest impact things. I totally understand how this can cause mistakes, but given that it's quick to undo a commit if something unexpected is committed, it's also fairly easy to back out of.

But I will acknowledge that this point is interesting, about the commit workflow itself:

> However, I think this specific case of changes happening while the description is being written is very clear: in no case should any changes be added silently. 

I'm not sure how that changes the dynamic, but cc @desktop/product for :eyes: and 💭  in the meantime

**Comment by billygriffin** [comment]
Hi @magiblot, thanks so much for the issue and for the detailed description of how this manifests as a problem for you. I think this offers a bit more evidence from #1788, but the concern remains about adding additional friction for those who understand and expect the existing behavior. I’ll definitely continue to look out for this in usability testing and we’ll also certainly take further feedback from other users into consideration. If we’re seeing it more, I think it would be reasonable to think through these cases a bit more and potentially provide for different workflows, but I don’t think we’re quite there yet, so I’m going to close this issue. Thanks again!

**Comment by magiblot** [comment]
First of all, thanks for your attention and excuse me for the duplicate issue.

I would like to point out that I never suggested changing any default behaviour, because I understand the situation of the rest of users. However, because the current behaviour may break user experience there should be a way to change it or measures to prevent misuse. Indeed, GitHub Desktop currently adds changes in the background, something the original `git` tool would never do. If you consider this not relevant enough to make any changes to the UI, you could at least allow us to configure this from the `Preferences` text file, which would be a non-obtrusive solution (and would satisfy me just as much).

I also want to share my disagreement with the following statement, for two main reasons:
> it's quick to undo a commit if something unexpected is committed
1. The time the developer(s) will take before noticing a commit is affected by this issue is undetermined.
2. It's not so easy to undo a commit if it has been pushed to a remote repository. Or would you be satisfied to push an additional commit titled along the lines of "Revert GitHub Desktop doing things I did not ask it to do"? And even worse: what if the undesired changes contain sensible information?

Thanks.

**Comment by billygriffin** [comment]
Hi @magiblot, I totally appreciate where you're coming from and that it's frustrating for you. As you can likely imagine, almost every feature request we get is also accompanied with "Just put a toggle for it in `Preferences`, which would quickly develop into an impossible situation where there's a toggle for everything and they would just never get used. Therefore, we try to reserve user-toggleable behavior for _the most_ divergent things where one large group of users expect `x behavior` and another large group of users expect `y behavior`. While I absolutely understand your frustration and concern here, this just isn't something we see currently as a common enough issue to necessitate a toggle to support variable preferences. As I mentioned in my earlier response, we're definitely open to revisiting this as we continue to gather more evidence, but don't want to keep people hanging expecting something to be done when it's not something we intend to support at present. Thanks again for sharing your thoughts, I really do appreciate it.

**Comment by magiblot** [comment]
I have taken a second glance at your repository. Over 20k commits, over a hundred branches, over 4k issues. I definitely understand your cautious response there. I hope more users say their word on this on the future.

In last place, I'd like to ask you a favor: can you provide me with any hints on how to patch the source code of the application to overcome this issue, for personal use? I don't want to stop using GitHub Desktop.

Thanks.

**Comment by madhukaranath** [comment]
#1788 seems to be a different issue of checking changed files. But adding new files without asking user, as mentioned in this post, is very irritating and dangerous. That is the reason I shifted from GitHub Desktop to TortoiseGit. I hardly see reason to add files automatically. May be just show a message box warning that there are new files. There will be hundreds of temporary files for reference purposes in the folder and each time adding them automatically is serious pain.

**Comment by Stripy42** [comment]
Hi,
I recognise this is an old thread. But I just came across this issue, using the GUI to get around a permissions issue with the CLI in WSL. It was surprising that it arbitrarily adds everything. it was only because this would have been hundreds on MB which stopped the chaos that would have ensured.
The names of the of the files to be blocked are secret themselves, and therefore cannot even be in the ignore file. 
It is surprising that these functionality cannot be disabled by a setting. I have no issue with it not being default, but it should ask.
I wonder if @shiftkey 's post about why it is not considered important, links to @madhukaranath 's comment about just swapping to an alternative. That will have to be what I also do, as it's an unusable tool in it's current state.

**Comment by cadagong** [comment]
What ridiculousness! Not only changing the default functionality of one of the most important tools in software development, but also actively refusing to add a feature that allows users to revert to the default functionality! I've always loved GitHub Desktop, the UI is amazing, but it's become unusable for me because of this issue. I've recently switched to SourceTree, which doesn't have this problem.
