### ISSUE TITLE
branch pruner not enabled for production usage

### ISSUE THREAD

**Issue by gfs** [desktop/desktop#7495]
## Description

Branches which were fully pushed, merged, and deleted on Github.com are not removed from GitHub Desktop. This super clutters up the list of branches.

## Version

* GitHub Desktop: 1.6.5

* Operating system: MacOS 10.14.4

## Steps to Reproduce

1. Create a branch
  - Either through cmd or through github desktop, unclear if relevant
2. Work on branch across two systems
  - Unclear if relevant
3. Push, squash-merge, delete the branch on GitHub.com
4. Wait 2 weeks #750 

### Expected Behavior

Branches are pruned after 2 weeks - (although I would prefer right away)

### Actual Behavior

Branches are never pruned.

<img width="1789" alt="SomeVeryOldBranches" src="https://user-images.githubusercontent.com/98900/57459825-d471d900-7228-11e9-9207-00634dbe5359.png">
[2019-05-09.desktop.production.log](https://github.com/desktop/desktop/files/3162498/2019-05-09.desktop.production.log)

**Comment by shiftkey** [comment]
@gfs thanks for the feedback. While we closed #750 when the feature landed on `development`, this is still behind a feature flag while we polish the feature:

https://github.com/desktop/desktop/blob/476737e3ec0c799d31bb8fe4e484611ce531139a/app/src/lib/feature-flag.ts#L49-L52

I'm going to update the title on this issue so we can track when this is enabled and shipped to everyone. Please keep an eye out!

**Comment by shiftkey** [comment]
This is available on our beta channel at the moment, if you'd like to use it and provide feedback:

https://github.com/desktop/desktop#beta-channel

**Comment by billygriffin** [comment]
Hey @gfs! If you're using the production version, today's update should include branch pruning. 😄

**Comment by zygimantas** [comment]
Still does not work in 2.1.0

**Comment by outofambit** [comment]
Hi @zygimantas, please file a new issue with our bug report template so we can help. Thanks!
