### ISSUE TITLE
can not publish

### ISSUE THREAD

**Issue by zhuiyizhiqiu** [desktop/desktop#7503]
when I create a new repository, I can not publish it. But I still publish repository the old project.
<img width="452" alt="屏幕快照 2019-05-10 下午5 07 36" src="https://user-images.githubusercontent.com/16648917/57516050-87842480-7346-11e9-919c-811ac9cc4345.png">

**Comment by shiftkey** [comment]
@zhuiyizhiqiu thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot the underlying issue.

**Comment by zhuiyizhiqiu** [comment]
Thank you help! It work well when I close my VPN.
