### ISSUE TITLE
Navigating to a submodule is difficult

### ISSUE THREAD

**Issue by dragospop** [desktop/desktop#7519]
There is no way you can easily navigate to submodules

It would be nice if there was a menu entry or on double click, I could go to a submodule.

An alternative would be to treat submodules transparent for user (eg: see changes and commit), 
but this might have some disadvantages when working with branches (should branching on submodules mirror branches on parent = have the same name? )

**Comment by billygriffin** [comment]
Hi @dragospop, thanks for opening this. Right now our support for submodules is limited and requires a little bit of extra effort to work with in the application. An idea like this is interesting for when we start investigating what expanded submodule support could look like. We’re slowly chipping away at features to make submodules easier to work with but submodules are not part of our [current roadmap](https://github.com/desktop/desktop/blob/development/docs/process/roadmap.md). I've added it to #7523 to have a central place to keep track of the surface area of submodules more broadly, just wanted to set expectations that it's not something we intend to address in the near future. Thanks again!

**Comment by sp-stuart-harrison** [comment]
+1 for this feature

**Comment by steveward** [comment]
From #12520:

>Working with submodules is cumbersome. It could be made simpler by allowing the user to browse repository submodules and directly work with them without having to do "Add Local Repository..." for each one.

**Comment by sergiou87** [comment]
We've made a few improvements in this regard in #15176 

We hope that's enough for most cases! If not, we'll gather feedback again with this new experience and work on top of that 😊
