### ISSUE TITLE
Revert commit

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#752]
On Mac it's a gear menu in a commit:

<img width="502" alt="screen shot 2016-12-14 at 9 49 44 am" src="https://cloud.githubusercontent.com/assets/13760/21186442/b426ce4c-c1e2-11e6-80b5-3332b24aaa23.png">

**Comment by garretchristensen** [comment]
Hmmm... I'm teaching a live demo now and the new Beta version seems to have eliminated the ability to revert a specific commit?

**Comment by joshaber** [comment]
Yup, this hasn't been implemented yet but we're planning to do so before 1.0.

**Comment by androvisuals** [comment]
As a new github user I installed the latest version of Github desktop and noticed that the comparison graph and revert option is unavailable. 
I've been pretty much trying to just revert a commit on a branch for over an hour now and also can't find an option (or a clear tutorial) on github itself. 
As a new user to git hub it seems to very difficult to just recover a deleted text file.

**Comment by j-f1** [comment]
@androvisuals The feature should be out in the next update. In the meantime, you can copy the SHA of the offending commit by clicking the link right after the author name, then open Terminal for the repo and type in `git revert` followed by a space, then paste in the SHA and hit <kbd>return</kbd> to revert the commit.

**Comment by androvisuals** [comment]
thanks j-f1 ! I don't think that  part was covered in the tutorials I was following.
