### ISSUE TITLE
Images comparison with 2-up method scales down small images too much

### ISSUE THREAD

**Issue by DavidPDev** [desktop/desktop#7520]
## Description
Images of 60x60 are shown too tiny when compared. Also other small images (72x72) are rendered very small. Example:
![image](https://user-images.githubusercontent.com/25801199/57617778-e97c9e00-7581-11e9-9149-78100465ae22.png)

Images below or equal 59x59 size are displayed and compared properly. Example:
![image](https://user-images.githubusercontent.com/25801199/57617808-f9947d80-7581-11e9-8b58-5805e3642bd1.png)

When the size of the image is bigger (for example 128x128) GitHub Desktop then scales down a bit the image, but it's ok.
Seems to have a "hardcoded" size of >=60 to scale the images when comparing them with the "2-up" method. The other types are working without problems (Swipe, Onion skin and Difference)

## Version
* GitHub Desktop: 1.6.5
* Operating system: Windows 7 SP1 (all patches up to date).

## Steps to Reproduce
1. `Create a 60x60 png image and a 59x59 png image`
2. `Commit both images`
3. `Modify both images`
4. `Compare images with GitHub Desktop`

### Expected Behavior
Both images should be rendered in a way to be able to compare their differences

### Actual Behavior
The 60x60 is displayed too small.

## Full images attached
![image](https://user-images.githubusercontent.com/25801199/57618418-9c99c700-7583-11e9-9779-f470e951b5f4.png)

![image](https://user-images.githubusercontent.com/25801199/57618425-a4596b80-7583-11e9-98ea-84ab6699a549.png)

![image](https://user-images.githubusercontent.com/25801199/57618431-acb1a680-7583-11e9-9f3c-089da58f8a26.png)

**Comment by niik** [comment]
Thanks for reporting this @DavidPDev, I especially appreciate your efforts to provide solid reproduction steps and explanatory images.

I've reproduced this behavior and have tentatively labelled it as a priority 2 bug since I think it fits in that criteria:

> Bug that affects more than a few users in a meaningful way but doesn't prevent core functions

**Comment by kkayri** [comment]
Merci mon ami qu'est ce que je dois faire

**Comment by DavidPDev** [comment]
If it helps... The "issue" has to do with this source file:
https://github.com/desktop/desktop/blob/249c06d51332a7254de848e1c77a60e1ae52d587/app/src/ui/diff/image-diffs/two-up.tsx#L30

![image](https://user-images.githubusercontent.com/25801199/57681984-1a67dc00-7631-11e9-8a50-fb2a9a07564d.png)
