### ISSUE TITLE
'Unlink of file failed' CLI error leaves repo in inconsistent state

### ISSUE THREAD

**Issue by ruby0x1** [desktop/desktop#7531]
Github Desktop 1.6.5 - Windows 10

When running certain applications that can have locks on files (e.g Unreal Engine 4), attempting to git pull can cause the repo to become half checked out. When this happens, the CLI git asks a question that the UI cannot answer, so the UI cancels the pull but leaves the repo in a problematic state. 

In particular I'm on an LFS repo, but the error is not from LFS, it is the CLI question/UI interaction.
- It can cause LFS files to make erroneous pointers to half checked out data
- If it fails hard enough or weirdly enough, it can cause LFS to make pointers to pointer files...

The exact error on the CLI pull is:
`Unlink of file '...' failed. Should I try again? (y/n)`

The repo state often shows all the pulled files as local modifications, and requires a good git reset with git clean to get back to head. When working on a team this kind of disruption in the git repo state is meant to be what desktop helps solve, so this one caught us by surprise a few times (if you just so happen forget to close an app before pulling).

Potential solutions/ideas:
- Handle the error more gracefully, when pull fails because of locked files
-  If possible, try not to change the repo state until the pull is confirmed. This failed pull is a guaranteed support request on a team, where as other reasons for a failure to pull aren't.

Thanks!

**Comment by tierninho** [comment]
@underscorediscovery Thank you for filing this, and providing details along with potential solutions. 

To sum it up, Desktop should surface some sort of dialogue to help resolve the `Unlink of file '...' failed. Should I try again? (y/n)` found in the CLI when pulling down a locked file, else you end up in a half checked out state.

cc @desktop/engineering for feels

**Comment by steveward** [comment]
I'm going to close this as stale for the time being since there have been no more recent reports of this.
