### ISSUE TITLE
Desktop Dock icon doesn't match size of other circle icons

### ISSUE THREAD

**Issue by jkuss** [desktop/desktop#7536]
**Please describe the problem you think should be solved**
The GitHub desktop dock icon does not match Atom's or Safari's circle size. 
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/305978/57786850-df7dab00-76f9-11e9-812f-50d04cc5ff77.png">

**[Optional] Do you have any potential solutions in mind?**
The white stroke seems to match ~1.5pt but the size of the circle itself is ~2pt too big in diameter.

**Comment by niik** [comment]
Hi @jkuss, thanks for opening this. I think this is something we could look at the next time we update the icon but given the amount of work that goes into creating these icons in all their various sizes and color depths and given how much is already on our designers plate I'm afraid I can't say anything about when we might have time to look into this.

**Comment by jkuss** [comment]
@niik totally understandable. Just marking the visual bug so someone, somewhere sees it.

**Comment by yamatsum** [comment]
Are there any plans to change to icons that are compatible with big sur, such as the following?
https://stijndv.com/goodies/big-sur-replacement-icons/

**Comment by niik** [comment]
hey @yamatsum, honestly I wasn't even aware that Big Sur will come with a new icon style so it's safe to say we don't have any plans as of yet. We probably should though. Would you mind opening a new issue specific to the Big Sur iconography and link to any specifications or other resources that Apple or the community have provided?

**Comment by yamatsum** [comment]
@niik  I created a new issue [here](https://github.com/desktop/desktop/issues/10855)
Please tell me if you have any other necessary information
