### ISSUE TITLE
effects problem

### ISSUE THREAD

**Issue by kapbook-jonny** [desktop/desktop#7542]
When I click fetch/push/pull button, **it doesn't show any effects**(like loading effect). but it also worked.

when I click push button, it just like follow image.
![1557993366473](https://user-images.githubusercontent.com/38315491/57836384-256a6a00-77f3-11e9-9b27-8275766969f8.jpg)

**Comment by shiftkey** [comment]
@kapbook-jonny thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by kapbook-jonny** [comment]
> @kapbook-jonny thanks for the report!
> 
> Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

Thanks for reply
It seems all right now, I just **Logged out my Github account..**
( _I didn't find any error or warning in Logs_)

![1558074600442](https://user-images.githubusercontent.com/38315491/57907550-607ea300-78b0-11e9-920b-eee73f4b75c5.jpg)
![1558074474743](https://user-images.githubusercontent.com/38315491/57907566-68d6de00-78b0-11e9-953b-051e709eaed1.jpg)
