### ISSUE TITLE
I have to choose file by file to commit to master

### ISSUE THREAD

**Issue by icodeworld** [desktop/desktop#7543]
Only when I  choose file by file can I click "Commit to master".I can't click "Commit to master" If I choose more than 1 files 
os: win10
github desktop: version 1.6.6

**Comment by icodeworld** [comment]
> Only when I choose file by file can I click "Commit to master".I can't click "Commit to master" If I choose more than 1 files
> os: win10
> github desktop: version 1.6.6

By the way, I can select more files and click "Commit to master"when I first clone or create repository

**Comment by shiftkey** [comment]
@icodeworld thanks for the feedback. I'm not 100% sure I understand the behaviour so I'll try and describe what I think you're looking at.

When one file is selected:
 
 - a pre-populated message appears in the Commit summary
 - the Commit button is enabled

<img width="277" src="https://user-images.githubusercontent.com/359239/57850585-9dfe0600-77b4-11e9-87b2-df06adb5808c.png">

This pre-populated message was added to emulate how GitHub the website works when you use the web editor - you're making a change to one file, and you don't need to specify a commit message.

When multiple files are selected:

 - the Commit summary is marked as required
 - the Commit button is disabled

<img width="261"  src="https://user-images.githubusercontent.com/359239/57850586-9dfe0600-77b4-11e9-9d28-4f32555cb03b.png">

This flow is now the regular Git commit flow, and we require a message to explain the changes before the Commit button is enabled.

If you're referring to something else around the commit flow, please share some screenshots or steps to walk through the problem as you see it.

**Comment by tierninho** [comment]
@icodeworld As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
