### ISSUE TITLE
light theme is dark in HDR

### ISSUE THREAD

**Issue by studiowildcard** [desktop/desktop#7546]
With HDR on in Windows, the GitHub desktop app is much darker than other apps. This is a new issue as it looked fine right before updating.

**Comment by shiftkey** [comment]
@studiowildcard thanks for the feedback.

I don't believe this is a new issue, because we had an earlier report of this in #7233 and I believe this will be fixed with an upgrade to Electron 4 (which appears to support it).

**Comment by shiftkey** [comment]
Please follow along with #6888 which is our tracking issue to upgrade the app to a newer version of Electron.
