### ISSUE TITLE
update gitignore submodule to get latest changes

### ISSUE THREAD

**Issue by VADS** [desktop/desktop#7548]
## Description
If I create a new repo and tell it to use the Unity gitignore preset, it doesn't seem to use the version found here: https://github.com/github/gitignore/blob/master/Unity.gitignore

I specifically noticed this because .meta files seem to be ingnored. Am I missing something here?

## Version

* GitHub Desktop: 1.6.6

* Operating system: Windows 10 64bit (command did not work)

## Steps to Reproduce

1. Create new repository
2. Select Unity as .gitignore preset

### Expected Behavior

.gitignore should match the one found at https://github.com/github/gitignore/blob/master/Unity.gitignore

### Actual Behavior

It doesn't match the one found at https://github.com/github/gitignore/blob/master/Unity.gitignore

### Logs

[2019-05-16.desktop.production.log](https://github.com/desktop/desktop/files/3187154/2019-05-16.desktop.production.log)

**Comment by shiftkey** [comment]
@VADS we include `github/gitignore` as a submodule in the project, so I'm not surprised we're a bit behind.

If you'd like to see this new template included in an update, the steps to update this are pretty straightforward. From the root of the `desktop` repository:

```
$ cd app/static/common/gitignore
$ git fetch
$ git checkout origin/HEAD
$ cd ..
$ git commit -am "update gitignore submodule to latest version"
```

This can be then submitted as a PR to the project to include in a later update.

**Comment by VADS** [comment]
I've never made a pull request on GitHub until now, but I've always wanted to try/learn it - do you need to assign me to this issue or can I just try to do it? :D

**Comment by shiftkey** [comment]
@VADS why not both? Let me know if you have any other questions, and good luck!

**Comment by VADS** [comment]
@shiftkey https://github.com/desktop/desktop/pull/7550 like this? I hope I didn't break anythin :D
