### ISSUE TITLE
My github site is not showing

### ISSUE THREAD

**Issue by ComputerScience9608** [desktop/desktop#7549]
![image](https://user-images.githubusercontent.com/50705535/57863912-be61ab00-781c-11e9-9399-338868a990bc.png)

**Comment by steveward** [comment]
👋  @ComputerScience9608

This repository is for issues with GitHub Desktop. If you are having specific issues with GitHub Pages I would recommend contacting [GItHub Support](https://github.com/contact).

I did take a quick look and it appears that your repository does not have a publishing source configured. You can read how to set this up here:

https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages

I'd also recommend taking a look at the [Getting Started with GitHub Pages Guide](https://guides.github.com/features/pages/).

I hope that is helpful. Let us know if you have any questions about GitHub Desktop!
