### ISSUE TITLE
Linux Shiftkey Linked

### ISSUE THREAD

**Issue by gotmax23** [desktop/desktop#7564]
Hi,

I think the Shiftkey/Desktop linux version should be linked as it is unclear that is an option from this main page. Keep up the good work!

Maxwell

**Comment by Cvbeek** [comment]
![FB_IMG_1557832942364](https://user-images.githubusercontent.com/49608394/57961636-9784a100-7910-11e9-9049-61e5fe7e08a1.jpg)

**Comment by tierninho** [comment]
@gotmax23 Thanks for recognition, we are glad you enjoying the product! We will consider you request for the Linux version. Please reach out if you have any more questions or thoughts. 😄
