### ISSUE TITLE
Alias Repoistory Name or Grouping all linked Project

### ISSUE THREAD

**Issue by CrescendoTechDevManager** [desktop/desktop#7569]
For desktop tool. Can we have the ability to create repo Alias and/or Group Git Project and repository. 
I manage a teams that have many repo. Unfortunately developers do not make unique repo names. So I end up having repo name likes "login" in several different projects.

**Comment by outofambit** [comment]
Hi @CrescendoTechDevManager! We're discussing over in #6460, which we're using for tracking some ongoing work in this area. Feel free to respond and offer feedback there!

Also, have you tried the desktop beta recently? We have some new repo organization features there and I would love to hear any feedback you have on them! (You can get them at https://github.com/desktop/desktop#beta-channel).

Going to close this out, but feel free to comment if you have any more questions. Thanks!
