### ISSUE TITLE
New repository contents differ from those created by github.com

### ISSUE THREAD

**Issue by jsejcksn** [desktop/desktop#7570]
When I create a new repository, I expect that it will be initialized with the same contents, whether I create it via
  - [github.com](https://github.com), or
  - GitHub Desktop

Presently, that is not the case. Here is an example:

## Repo creation details

Screenshot of details for repo created by [github.com](https://github.com):

<img width="768" alt="github.com-details" src="https://user-images.githubusercontent.com/868251/57989708-6e752500-7a64-11e9-9278-ec82c22fa99a.png">

Screenshot of details for repo created by GitHub Desktop:

<img width="396" alt="github-desktop-details" src="https://user-images.githubusercontent.com/868251/57989709-7339d900-7a64-11e9-8ae6-3cbf983c4336.png">

## Observed differences

  1. `.gitattributes` is only created by GitHub Desktop
```shell
diff github-desktop-respository-node/.gitattributes github.com-respository-node/.gitattributes
diff: github.com-respository-node/.gitattributes: No such file or directory
```

  2. `.gitignore` has differences. It looks like the one created by [github.com](https://github.com) is outdated?
```shell
diff github-desktop-respository-node/.gitignore github.com-respository-node/.gitignore 
23c23
< # Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
---
> # Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
60,62d59
< # parcel-bundler cache (https://parceljs.org/)
< .cache
< 
65,76d61
< 
< # nuxt.js build output
< .nuxt
< 
< # vuepress build output
< .vuepress/dist
< 
< # Serverless directories
< .serverless
< 
< # FuseBox cache
< .fusebox/
```

  3. `README.md` does not include the description when created by GitHub Desktop
```shell
diff github-desktop-respository-node/README.md github.com-respository-node/README.md
1c1,2
< # github-desktop-respository-node
---
> # github.com-respository-node
> This description is definitely not blank
```

Attached is an archive of the example repositories: [repos.tar.gz](https://github.com/desktop/desktop/files/3195759/repos.tar.gz)

<img width="267" alt="archive" src="https://user-images.githubusercontent.com/868251/57990040-64edbc00-7a68-11e9-9dfe-b4824e71cb06.png">

## Conclusion

Perhaps the two can be brought to parity.

If some of this needs to be filed with another team for the behavior related to [github.com](https://github.com), please direct me to the appropriate repo's issues list so I can re-post this issue there. Thanks.

**Comment by outofambit** [comment]
Hi @jsejcksn and thank you for this excellent write-up! As far as GitHub Desktop goes, we should fix the repo creation to include the provided description in the resulting readme. I'll open a new issue for that specific bug (https://github.com/desktop/desktop/issues/7571).

For the other points, the team that maintains this repo doesn't maintain the dot com repo creation as you suspected. However, I can pass this feedback along to the appropriate team internally (and again thank you for this overview, that makes this easy).

**Comment by Avz7uy123** [comment]
[https://media0.giphy.com/media/1Z02vuppxP1Pa/giphy.gif?cid=4ac7172f5ce1ff7d344a4b47731fe1f5&rid=giphy.gif]<https://gph.is/1biipRP>
via GIPHY<https://gph.is/1biipRP>
________________________________

**Comment by jsejcksn** [comment]
@outofambit Thank you for moving along the Desktop-related aspects of this issue. How will I be able to track the status of the dot com-related aspects if you only report it internally? I would like to be automatically notified of status changes regarding those aspects of this issue.

**Comment by Avz7uy123** [comment]
So since threads I’ve been since day one I kinda don’t trust anyone. But since you guys are constantly sending me notes I just got tired and just started ignoring because I thought it was part of it’s own thread. I read one and I saw someone taking its flag out and saying hey I’m here. Steps to me it’s the only way of the other steps of resolving. But if we meet then I’ll know for sure.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by iolsen** [comment]
Responding on behalf of @github/pe-repos. This looks like correct behavior to me, from a dotcom perspective.

When creating a new repository from Desktop you have the option to tell it about your project and it can add project-specific data to the initial repository. When you initialize a new repository from dotcom, it's general-purpose. In the screenshots given, you're telling Desktop you're creating a node project so it's adding appropriate .gitignore and .gitattributes for such a project. There's no analogous functionality when creating a new, empty repository from dotcom. Changing that would be a significant product-level change, certainly not a bug fix. The way to accomplish a similar end result without Desktop would would be to initialize your node project locally then push it into a new, empty repo.

**Comment by Avz7uy123** [comment]
Theirs two different dotcom on my experience since day one. Since day one I’ve been under the impression it wasn’t part of yesterday’s dotcom problem. Yesterday’s dotcom what’s related to? With this answer you will proven to know what I’m into. If you answer dotcom one you will answer yesterday’s dotcom with no problem. And the results will elimate any problems at all whatsoever. Please answer to the best of your abilities, but never the less around the circle but not quite in. I will understand about dotcom info.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jsejcksn** [comment]
> There's no analogous functionality when creating a new, empty repository from dotcom.

Please review my initial post, especially the screenshots. The interface options are identical other than "local path" for Desktop and "public/private" for [github.com](https://github.com).

**Comment by jsejcksn** [comment]
@outofambit This is a nudge about my previous question:

> How will I be able to track the status of the dot com-related aspects if you only report it internally? I would like to be automatically notified of status changes regarding those aspects of this issue.
