### ISSUE TITLE
New repository readme doesn't include provided description

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#7571]
_(Originally reported by @jsejcksn in #7570)_

Screenshot of details for repo created by GitHub Desktop:

<img width="396" alt="github-desktop-details" src="https://user-images.githubusercontent.com/868251/57989709-7339d900-7a64-11e9-8ae6-3cbf983c4336.png">

`README.md` does not include the description when created by GitHub Desktop
```shell
diff github-desktop-respository-node/README.md github.com-respository-node/README.md
1c1,2
< # github-desktop-respository-node
---
> # github.com-respository-node
> This description is definitely not blank
```

**Comment by shiftkey** [comment]
I'll walk through the areas that need to be modified here to match us with how GitHub The Website does it's initialization.

First, this code inside `app/src/ui/add-repository/create-repository.tsx` is what is being invoked after the user presses "Create repository" to create the README:

https://github.com/desktop/desktop/blob/82c188d68a83330a08feacec782e32fee3eed5a4/app/src/ui/add-repository/create-repository.tsx#L235

`writeDefaultReadme` needs to be updated to accept a `description` string - this is stored in `this.state.description`, which should be appended below the title if it's not an empty string.

The function that renders the contents of the `defaultReadmeContents`:

https://github.com/desktop/desktop/blob/82c188d68a83330a08feacec782e32fee3eed5a4/app/src/ui/add-repository/write-default-readme.ts#L6-L8

It'd also be great to add a couple of tests to this while we're in here to verify the changes. I sketched out a couple here that should help as a starting basis:

```
import * as FSE from 'fs-extra'
import * as path from 'path'
import { mkdirSync } from '../helpers/temp';

import { writeDefaultReadme } from '../../src/ui/add-repository/write-default-readme';

describe('repository setup', () => {
  describe('writeDefaultReadme', () => {
    let directory: string
    let file: string

    beforeEach(() => {
      directory = mkdirSync('new-readme')
      file = path.join(directory, 'README.md')
    })

    it('writes a default README without a description', async () => {
      await writeDefaultReadme(directory, 'some-repository')

      const text = await FSE.readFile(file, 'utf8')
      expect(text).toBe('# some-repository\n')
    })

    it('writes a README with description when provided', async () => {
      await writeDefaultReadme(directory, 'some-repository', 'description goes here')

      const text = await FSE.readFile(file, 'utf8')
      expect(text).toBe('# some-repository\ndescription goes here\n')
    })
  })
})
```
