### ISSUE TITLE
Adding notes to releases section of the repository

### ISSUE THREAD

**Issue by raiyanalam** [desktop/desktop#7573]
Currently the releases section of the repository has a flat list of tags and does not contain information about releases. 

![image](https://user-images.githubusercontent.com/7879476/58000342-256db100-7af6-11e9-9368-d1130bba2cdd.png)

It would be really informative for contributors if a list of changes is displayed in this section of repo every time a new release is published. I see that the repo maintains a [changelog ](https://github.com/desktop/desktop/blob/development/changelog.json)as well. Since the repo already uses Azure pipelines for CI, this can be easily automated using [github release task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops) . Here is a [sample repo](https://github.com/Microsoft/vscode-react-native/releases) that leverages this capability. 

PS: I am a PM for azure pipelines. I would be happy to help with the changes.

**Comment by shiftkey** [comment]
@raiyanalam thanks for your interest in this. 

We're tracking a discussion about this in #6457 but because we use a different process for publishing releases it's not as easy as adding something to the Pipelines configuration.
