### ISSUE TITLE
Cannot Install as Local Admin/All Users (VDI Installation)

### ISSUE THREAD

**Issue by dynamiccookies** [desktop/desktop#7582]
We'd like to install GitHub Desktop on an App Volume in our VDI environment. 

Our infrastructure team is stating they're unable to do this because the application will only allow for the installation as the current user, not for the local admin or 'all users', which is how our App Volume software applications are installed.

This would affect all organizations who use VDI environments in this manner.  

I'll be reaching out to my infrastructure team to gather more detailed info and update this issue once I have it.

Possible Solution:
Allow installation for all users on the computer.

**Comment by steveward** [comment]
Thanks for opening this @dynamiccookies! 

GitHub Desktop has a .msi installer that supports machine-wide installations. After you install the .msi it will install GitHub Desktop each time a user logs in to the machine. The application will install to `%LocalAppData%`. You can read more about how it works here:

https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/machine-wide-installs.md

You can download the .msi here:

https://central.github.com/deployments/desktop/desktop/latest/win32?format=msi

Would that possibly work for you in this scenario? I'm not very familiar with how App Volume works.

**Comment by dynamiccookies** [comment]
That worked, thank you!

**Comment by tromlet** [comment]
> Thanks for opening this @dynamiccookies!
> 
> GitHub Desktop has a .msi installer that supports machine-wide installations. After you install the .msi it will install GitHub Desktop each time a user logs in to the machine. The application will install to `%LocalAppData%`. You can read more about how it works here:
> 
> https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/machine-wide-installs.md
> 
> You can download the .msi here:
> 
> https://central.github.com/deployments/desktop/desktop/latest/win32?format=msi
> 
> Would that possibly work for you in this scenario? I'm not very familiar with how App Volume works.

I don't hate this, as it WILL work, but it would really be nice if it just put app data in the AppData folder and didn't install multiple copies of the program on the same filesystem. That does seem like a waste of space. :/

**Comment by AditiSharma-bit** [comment]
I am installing "GitHubDesktopSetup-x64.msi" which installs only "GitHubDesktopDeploymentTool.exe" at "C:\Program Files (x86)\GitHub Desktop Deployment" location.
Then I am installing "GitHubDesktopDeploymentTool.exe" from "C:\Program Files (x86)\GitHub Desktop Deployment" location which is installing entire application under "C:\Users\<Username>\AppData\Local\GitHubDesktop".

Now I have to package this application so I am passing both these commands from PowerShell script.
When I install "GitHubDesktopDeploymentTool.exe" with Execute-ProcessAsUser it is not installing the data for every user.
So, I am using ActiveSetup but I do not want to log off and login the machine.
So, in this I need to have PowerShell code to run ActiveSetup without logoff Login.

Could you all please help me on this.

**Comment by PrestonTaylor** [comment]
This is a very poor implementation of this. This places git.exe and the credential manager in a folder named for an exact version number deep in appdata. Every time it updates I have to fix credential.helper in WSL. No Bueno.
