### ISSUE TITLE
`pull` from within app is significantly slower than `git pull` from command line

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#7585]
## Description

I had a chat with one of the @desktop/comrades last week about some performance feedback from their usage of the app and a scenario that I couldn't easily explain left me scratching my head.

## Version
* GitHub Desktop: both `1.6.5` and `1.7.0-beta7` (I believe this goes back to the `1.5.x` series based on our discussion, but I'm not sure how far).
* Operating system: Windows 10

## Steps to Reproduce
1. Come to work Monday after a weekend away
2. Using a repository with a significant number of commits, fetch the new changes
3. `Pull` to get the latest changes

This also seems to be reproducible when you manually reset the branch:

```
$ git reset HEAD~50 --hard
```

I confirmed this extra information from the submitter:

 - monorepo which the whole company is working in
 - using GHE 2.16.7
 - no submodules used in the repository

### Expected Behavior
Progress indicator should indicate progress, and pull should complete in a time that's similar to the command line experience.

### Actual Behavior
A long wait for any progress information to show in the app (the "Hang on..." message is shown instead), and the overall time is 3x-4x longer to complete the pull when compared to the command line. One example provided was 5s to `git pull` from the command line, versus 21s in the app.

## Additional Information

N/A

### Logs

I'll see if I can obtain some logs to inform the issue, but I suspect they're .

**Comment by tgaeta** [comment]
I too can confirm pulling/pushing are 10x slower in Github Desktop than from the command line. From the dev tools, I see 404 errors when I click push or pull. I have also observed that when I switch to a new window (e.g., to the browser) and then back to the GH Desktop app, the action then completes, and then you see the animation indicating the push succeeded. 

![github desktop bug](https://user-images.githubusercontent.com/9040988/64884237-2e4b3b00-d62f-11e9-84ec-d1d2a2b87e70.gif)

**Comment by shiftkey** [comment]
> From the dev tools, I see 404 errors when I click push or pull. 

@tgaeta Git operations won't appear in the Chrome Dev Tools (because they happen outside the renderer process), so I'm curious what those are and why they're 404ing like that. You should be able to click into them and see what URLs are being called.

**Comment by tgaeta** [comment]
So after deleting the DB from the Application tab in the dev console, and signing out and signing back in, the issue appears to be gone. 

Instead of 404s - I'm now receiving `[AppStore.withAuthenticatingUser] account found for repository: consumer_action - tgaeta (has token)`. So it was an authentication error; however, it doesn't explain why the app would push and pull when I switched screens and came back to it. Hope you all figure that out, but for me, my issue is resolved.

**Comment by tidy-dev** [comment]
When following the reproduction steps of using `git reset HEAD~50 --hard` and pulling. Command line and desktop resolve within 2 seconds. Going to mark as fixed - tho happy to reopen if we find workable reproduction steps. We also haven't gotten a lot of use feedback about this.
