### ISSUE TITLE
uncaught rejection with fresh repository trying to get all pull requests

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#7587]
## Description

Found this one while testing `development` when starting without any tracked repositories.

<img width="580"  src="https://user-images.githubusercontent.com/359239/58047238-100c7d00-7b1e-11e9-8969-1a9b560ae358.png">

## Version
* GitHub Desktop: 4a22c4669b
* Operating system: macOS

## Steps to Reproduce
1. Clear the `Database` database of your tracked repositories
2. Restart the app
3. Add an existing GitHub Repository

### Expected Behavior
`PullRequestStore.getAll` may have a problem with getting the error, but it should only log a warning to the dev tools as it will eventually come good once it has been added to the database

### Actual Behavior
Uncaught rejection is raised by the `fatalError` and this code only looks at the `then` result of the promise:

https://github.com/desktop/desktop/blob/4a22c4669b3c5962a20bb069e4c4a4cb085985c9/app/src/lib/stores/app-store.ts#L1337-L1339

This doesn't crash the app, but could be handled better in `AppStore`.

**Comment by shiftkey** [comment]
Tentatively pulling this into `1.7.0` because its a change introduced in #7501

**Comment by shiftkey** [comment]
I thought this would eventually come good but despite selecting the repository or fetching (hoping to get the correct information from the API) I continue to see this error with `nodejs/node`.

Manually refreshing PRs doesn't seem to affect this behaviour either:

<img width="734" src="https://user-images.githubusercontent.com/359239/58094284-adab8f00-7ba6-11e9-9550-f2f59732d086.png">

 Is anyone else able to see this?

**Comment by niik** [comment]
This feels like the exact same issue as with the one where PRs would get "associated" with the wrong repository.

> 1. Clear the `Database` database of your tracked repositories

By this I'm assuming you mean dropping the main database (the not-so-aptly named `Database`) only, correct?

If that's true then this is a legit failure, you can't delete the main database without also deleting the 'GitHubUserDatabase', `IssuesDatabase`, and `PullRequestDatabase` (i.e. all but the StatsDatabase) as they are dependent on each other.

> `PullRequestStore.getAll` may have a problem with getting the error, but it should only log a warning to the dev tools as it will eventually come good once it has been added to the database

I don't believe it should just log an error and I don't believe it will or should solve itself once the repository is added to the database. What this error is saying is that there's one or more pull requests in the `PullRequestDatabase` with a head repository ID  (i.e. it's a PR from a fork) that does not exist in the `gitHubRepositories` table. If this ever happens without someone manually fiddling with the database we have a problem but assuming that my question about the reproduction steps confirms my suspicion I don't see how this can happen in real life.

A PR is only ever inserted into the `PullRequestDatabase` [if we've ensured that the ID for both the head and the base repository ID exist](https://github.com/desktop/desktop/blob/58ea4bd88cc3c9a5dfdd753f9320248d21a2ce08/app/src/lib/stores/pull-request-store.ts#L301-L339) and are added to the repositories table.

Again with the assumptions but assuming that what I've outlined above holds true I think we should close this issue as I believe it's working as intended.

**Comment by shiftkey** [comment]
@niik I went through the process of deleting all the databases (not just clearing the tables) and wasn't able to reproduce this. I guess there was one scenario where I didn't correctly clean these out.

Closing this out as not reproducible.
