### ISSUE TITLE
GitHub Desktop Doesn't Recognize that Branch has Been Published 

### ISSUE THREAD

**Issue by danielhelfand** [desktop/desktop#7592]
If I check do a `git checkout -b branch_name` and then a `git push origin branch_name` via the git cli, GitHub Desktop does not recognize that the branch has already been pushed and prompts me to Publish branch as shown below:

![image](https://user-images.githubusercontent.com/34258252/58097249-ef3b3a80-7ba4-11e9-91fe-5ca5e677e383.png)

In the scenario above, I created a branch called `test` and published the branch using the commands below:
`git checkout -b test`
`git push origin test`

Example:

When I push my branch via the git cli, as shown above, GitHub Desktop should recognize that the branch has already been published and not prompt me to publish the branch.

**Comment by shiftkey** [comment]
@danielhelfand thanks for the feedback.

If you add a `-u` to the `git push` operation Git will set the tracking branch to the remote ref after the push, which Desktop then detects and will start showing the ahead/behind information. This is also visible from the command line.

```shellsession
$ git status
On branch test
Your branch is up to date with 'origin/test'.
...
```

This also means you can do a `git push` from the command line without needing to specify the remotes.

This is a conscious decision by Desktop to avoid being too clever. Assuming `test` and `origin/test` are the same breaks down as soon as you have multiple remote repositories, so we need the local branch to be explicit here.

Let me know if you have any other questions about this area.
