### ISSUE TITLE
how do I fix authentication

### ISSUE THREAD

**Issue by mpatters2** [desktop/desktop#7593]
I'm trying to publish and it is telling me that it "requires authentication"  I can't click on this message and fix my authentication.  How do I fix it?

**Comment by steveward** [comment]
👋 @mpatters2 I would start by verifying that you are correctly logged in to your GitHub account in GitHub Desktop. You can do this by going to the menu and selecting `File` > `Options` > `Accounts` (Windows) or `GitHub Desktop` > `Preferences` > `Accounts` (macOS).

If you continue to have issues after verifying that you are logged in it would be helpful if you could fill out the template and upload a log file.

**Comment by tierninho** [comment]
@mpatters2 As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by nilslindemann** [comment]
Log out and log in again, see https://github.com/desktop/desktop/issues/4224#issuecomment-466654899 ;-)
