### ISSUE TITLE
File names from Microsoft office programs like excel, word, powerpoint  not matched properly

### ISSUE THREAD

**Issue by inesheiland** [desktop/desktop#7598]
I tested Github Desktop  on Mac, but unfortunately we have some excel, word and powerpoint files in some of our repositories and those are not recognized properly by Github Desktop. Whenever I change some of them, they get new truncated names, adding ~$ and sometimes removing the first letter of the file name in the process. When pushing the repository, a new file is added, instead of updating the old one.

## Version

* GitHub Desktop:

1.6.5

* Operating system:

Mac OS 10.13.13

**Comment by shiftkey** [comment]
@inesheiland thanks for the report!

>  Whenever I change some of them, they get new truncated names, adding ~$ and sometimes removing the first letter of the file name in the process. 

Can you share an screenshot of this to illustrate the problem? 

The `~$` prefix to these files feels like it's related to a feature of Office that uses temporary files which are stored alongside the same file in the directory.

There is a template in the `github/gitignore` project that lists some temporary files that match this pattern: https://github.com/github/gitignore/blob/master/Global/MicrosoftOffice.gitignore

```gitignore
# Word temporary
~$*.doc*

# Excel temporary
~$*.xls*

# PowerPoint temporary
~$*.ppt*
```

I believe these can be excluded from Git using a `.gitignore` file, but I also wanted to confirm that changes to the main files are still working as intended before closing this out.

**Comment by mido1966** [comment]
Pls No Email mor pls Tank you



Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: "Prof. Ines Heiland" <notifications@github.com>
Datum: 22.05.19 10:56 (GMT+01:00)
An: desktop/desktop <desktop@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [desktop/desktop] File names from Microsoft office programs like excel, word, powerpoint  not matched properly (#7598)


I tested Github Desktop on Mac, but unfortunately we have some excel, word and powerpoint files in some of our repositories and those are not recognized properly by Github Desktop. Whenever I change some of them, they get new truncated names, adding ~$ and sometimes removing the first letter of the file name in the process. When pushing the repository, a new file is added, instead of updating the old one.

Version

  *   GitHub Desktop:

1.6.5

  *   Operating system:

Mac OS 10.13.13

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @inesheiland if you're able to provide extra context from my previous comment we're happy to revisit this issue.

**Comment by inesheiland** [comment]
![Schreenshot_github](https://user-images.githubusercontent.com/7909985/58653100-4d8aba80-8315-11e9-8c0e-2b4d52954ec1.png)

The file listed at the end of the list, is listed as new file with the strange replacement, but the file exists already and has just been updated.

**Comment by shiftkey** [comment]
@inesheiland I think those files starting with `~$` can be added to the `.gitignore` in the root of the repository, using the rules provided in the earlier comment. 

It's not clear to me if `Step-by-step protocol.pptx` already existing in version control, but I think that will get you back to a happy place working with the Office suite of tools.

**Comment by inesheiland** [comment]
You might be right, it might be a kind of backup-file that GitHub-Desktop recognizes and adding it to gitignore should work. With this file I now see also a changed version if I change something. Thus it might have been a problem with another file I had. I would be happy if I could avoid handling office file, but I will keep you posted of possible further strange occurences. Closed for now from my side.

**Comment by gary-89** [comment]
When working on Windows, I have observed the following file system activity.
Opening `Test.xlsx`:
```
07:17:07.8951566Z Created file   "~$Test.xlsx", ID=14073748835585246, Size=0, Attr=(Hidden, Archive)
07:17:07.8992418Z Changed file   "~$Test.xlsx", ID=14073748835585246, Size=0, Attr=(Hidden, NotContentIndexed)
07:17:07.9020027Z Changed file   "~$Test.xlsx", ID=14073748835585246, Size=165, Attr=(Hidden, Archive, NotContentIndexed)
```
Saving the `Test.xlsx` file:
```
07:30:58.8301623Z Created file "667D6700", ID=43628621390158971, Size=0, Att=(Archive)
07:30:58.8401325Z Changed file "667D6700", ID=43628621390158971, Size=131072, Att=(Archive)
07:30:58.8417596Z Changed file "667D6700", ID=43628621390158971, Size=8318, Att=(Archive)
07:30:58.8426780Z Changed file "667D6700", ID=43628621390158971, Size=8318, Att=(Archive)
07:30:58.8765514Z Changed file "667D6700", ID=43628621390158971, Size=8318, Att=(Archive)
07:30:58.8770025Z Changed file "667D6700", ID=43628621390158971, Size=8318, Att=(Archive)
07:30:58.8773801Z Renamed file "Test.xlsx", ID=35747322042281505, Size=8273, Att=(Archive, ReparsePoint) to "C74D9088.tmp"
07:30:58.8776864Z Renamed file "667D6700", ID=43628621390158971, Size=8318, Att=(Archive) to "Test.xlsx"
07:30:58.8780919Z Changed file "C74D9088.tmp", ID=35747322042281505, Size=8273, Att=(Archive, ReparsePoint)
07:30:58.8784679Z Changed file "Test.xlsx", ID=43628621390158971, Size=8318, Att=(Archive)
07:30:58.8788661Z Changed file "Test.xlsx", ID=43628621390158971, Size=8318, Att=(Archive)
07:30:58.8792359Z Deleted file "C74D9088.tmp", ID=35747322042281505, Size=8273, Att=(Archive, ReparsePoint)
```
**Observation:**
During the save process, a temporary file with an 8-character alphanumeric name (e.g., 667D6700), without file extension, is created. 
Notably, this file is created without the standard "temporary" attribute and is used to apply the changes before swapping it with the original `Test.xlsx`.
