### ISSUE TITLE
simplify the result from getBranches to skip unnecessary work

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#7600]
As part of investigating opportunities for performance improvement, I pointed out that the result from `getBranches` is a complex model but the data it contains is not really leveraged in the app.

https://github.com/desktop/desktop/blob/afb1f0053210c692817e947287b51fae9894a87a/app/src/lib/git/for-each-ref.ts#L17-L20

Inside `getBranches` we retrieve a number of fields and convert them into a formatted branch + tip object:

https://github.com/desktop/desktop/blob/afb1f0053210c692817e947287b51fae9894a87a/app/src/lib/git/for-each-ref.ts#L24-L38

However the tip commit is not used in the app, and the branch listings only display a minimal set of information in the UI - the branch name and the most recent commit timestamp.

<img width="366" alt="Screen Shot 2019-05-22 at 9 31 21 AM" src="https://user-images.githubusercontent.com/359239/58174452-6095ee80-7c74-11e9-81ce-f4ddfa33ee8a.png">

We should investigate whether we can omit the rich commit details from `Branch` in favour of using the standard commit ID string, which would mean we can save on this second Git operation to query the config for the commit trailer separator character:

https://github.com/desktop/desktop/blob/afb1f0053210c692817e947287b51fae9894a87a/app/src/lib/git/for-each-ref.ts#L68

Other potential benefits of this change:

 - less work spend in here parsing output and creating objects - less GC pressure
 - commits not created - less work done caching commits and locating the author using the GitHub API

**Comment by outofambit** [comment]
@rafeca more or less did this in #9423! 🎉
