### ISSUE TITLE
Can't select text in commit error dialog

### ISSUE THREAD

**Issue by elias6** [desktop/desktop#7606]
## Description

Sometimes, I will try to commit something and get an error because of our pre-commit hooks (like eslint and prettier). If I commit using GitHub Desktop, the error will show in a dialog box. I am unable to select the text of the error message. This is kind of annoying because I would like to be able to copy and paste the error message somewhere, possibly to ask someone else why it is happening.

## Version

* GitHub Desktop: 1.6.6

* Operating system: macOS High Sierra Version 10.13.6

## Steps to Reproduce

Try to commit something that produces a pre-commit hook to exit with a non-zero status, indicating an error. I can come up with a more specific example if anyone wants. Then try to select the text in the error dialog by clicking and dragging.

### Expected Behavior

I should be able to select the text.

### Actual Behavior

I am unable to select the text.

### Logs

I would prefer not to attach my log file for privacy reasons, since this is happening on my work laptop. I can try to reproduce this at home if anyone wants.

**Comment by tierninho** [comment]
@elias6 Thanks for adding your suggestion.

I assume you mean something like this? That is supposed to be a `copy` icon on the right. I would say that is a reasonable ask and something that would be useful. 

<img width="642" alt="Screen Shot 2019-05-22 at 8 02 05 AM" src="https://user-images.githubusercontent.com/14828183/58197629-5d950100-7c68-11e9-9db9-5f5fb9a19f4c.png">

I will let this sit for a few days to let others chime in.

**Comment by elias6** [comment]
I don't see an icon like that.

But I would prefer being able to select some or all of the error, the same way I usually select text, and copy it using Command+C, the same way I usually copy things.

**Comment by tierninho** [comment]
So that was only a mock-up. Alternatively, we could also allow some or all of the text to be copied.

**Comment by elias6** [comment]
I wouldn't mind that icon in addition to being able to select text. But I don't see any reason to not allow selecting text.

**Comment by outofambit** [comment]
Hi @elias6, thanks for filing this, I was able to reproduce this issue locally.

I think both approaches are valid solutions! Allowing text highlighting and copying could be a good quick fix _and_ that a copy icon would be a nice addition afterwards.

**Comment by jkuss** [comment]
I have the same issue and would just like to be able to select text. If a message from the terminal is shown in a GUI I need to be able to select it. 

I understand by default this UI built in HTML probably has `user-select: none` but certain components should have text always selectable by default.

**Comment by celloworld** [comment]
**bump**

The 'copy all' button is overkill -- having to paste the whole log and trim it down to the error specifics I didn't want to retype is more work than just retyping it. Please enable users to employ the text selection cursor that already appears to highlight specific verbose errors from the log.

**Comment by KaKi87** [comment]
+1 !
Why isn't that basic and important UX problem resolved by the time as of now yet ?

**Comment by KaKi87** [comment]
@outofambit As this issue been fixed ?

**Comment by Rexogamer** [comment]
@KaKi87 yep, that PR fixed the issue, this should be in next release :D
