### ISSUE TITLE
Clean up stashing control flow

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#7607]
I'm not a fan of this function, `_checkoutBranch` in its current form because it's doing too much: checking out a branch, asking to stash, stashing changes on current branch, popping transient stash entry. I think it's worthing thinking about how to split this logic up so that it's clearer, but I don't think this PR is the place for that. So if you're reviewing and think this logic is complex, know that I likely agree with you, but I think it's mostly fine for now since it's all grouped together behind a check for `enableStashing`

_Originally posted by @iAmWillShepherd in https://github.com/desktop/desktop/pull/7474_

**Comment by outofambit** [comment]
closing this issue in favor of the two more specific refactors outlined in #7609 and #7617

**Comment by jayzho080** [comment]
lol

**Comment by jayzho080** [comment]
olololooololololololo

**Comment by jayzho080** [comment]
loololloll lo

kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
