### ISSUE TITLE
Prevent concurrent appStore._checkoutBranch call from error handlers

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#7617]
Original context from @outofambit and @niik in https://github.com/desktop/desktop/pull/7474#discussion_r286717265

A great shout @outofambit. `_checkoutBranch` does become re-entrant in this scenario. I think we should still await here though, not awaiting will not alter the re-entrant nature of the logic as `performFailableOperation` doesn't itself await the result of the error handlers. I think instead we should focus on your second idea and explore that a little bit more but I definitely agree with your assessment of risk in doing so.

I imagine that the fact that we have this disconnect in the awaitable chain will cause other problems such as the `StashAndSwitchBranch` progress not working properly. If you choose to move your changes to the next branch and hit Ok, the dialog progress will start spinning but if the checkout fails and the error handler takes over I would imagine that the dialog will close and the stash + checkout operation will continue in the background.

My gut feeling here is that a better approach would be to have `_checkoutBranch` catch this specific error inline and deal with it accordingly rather than waiting for the global error handler to pick it up. That, however, is a much bigger task that I don't think we'll have time to implement and test but definitely something worth investigating post 2.0.

A completely untested rough draft of how inline-management of this would work:

```diff
diff --git a/app/src/lib/stores/app-store.ts b/app/src/lib/stores/app-store.ts
index 05d219da5..5472d89d9 100644
--- a/app/src/lib/stores/app-store.ts
+++ b/app/src/lib/stores/app-store.ts
@@ -2918,10 +2918,48 @@ export class AppStore extends TypedBaseStore<IAppState> {
     const checkoutSucceeded =
       (await this.withAuthenticatingUser(repository, (repository, account) =>
         gitStore.performFailableOperation(
-          () =>
-            checkoutBranch(repository, account, foundBranch, progress => {
-              this.updateCheckoutProgress(repository, progress)
-            }),
+          async () => {
+            try {
+              await checkoutBranch(
+                repository,
+                account,
+                foundBranch,
+                progress => {
+                  this.updateCheckoutProgress(repository, progress)
+                }
+              )
+              return true
+            } catch (err) {
+              if (
+                !isLocalChangesWouldBeOverwrittenError(err) ||
+                stashToPop !== null
+              ) {
+                throw err
+              }
+
+              if (
+                !(await gitStore.performFailableOperation(() => {
+                  return createDesktopStashEntry(repository, foundBranch.name)
+                }))
+              ) {
+                return false
+              }
+
+              stashToPop = await getLastDesktopStashEntryForBranch(
+                repository,
+                foundBranch.name
+              )
+
+              return await checkoutBranch(
+                repository,
+                account,
+                foundBranch,
+                progress => {
+                  this.updateCheckoutProgress(repository, progress)
+                }
+              )
+            }
+          },
```

_Originally posted by @niik in https://github.com/desktop/desktop/pull/7474_

subset of #7607

**Comment by probablycorey** [comment]
Closing in favor of https://github.com/desktop/desktop/issues/8099
