### ISSUE TITLE
external editor per repository

### ISSUE THREAD

**Issue by nilswald** [desktop/desktop#7621]
The default external editor should be a per-repo setting. For instance for my python projects I use PyCharm, for PHP PhpStorm, for JavaScript rather WebStorm or VSCode.

**Comment by outofambit** [comment]
Hi @nilswald, thanks for filing this issue. Could you provide a bit more context about how that would be helpful for you? What's the underlying problem that would fix? More specifically, how often do you end up changing your external editor setting, or avoid the in-app shortcuts to use another editor?

**Comment by shiftkey** [comment]
Closing this out due to inactivity. @nilswald if you're able to answer the questions that @outofambit asked we're happy to revisit this.

**Comment by cainsrychl** [comment]
> Hi [@nilswald](https://github.com/nilswald), thanks for filing this issue. Could you provide a bit more context about how that would be helpful for you? What's the underlying problem that would fix? More specifically, how often do you end up changing your external editor setting, or avoid the in-app shortcuts to use another editor?

@shiftkey @outofambit bunch of cunts, same with the rest of the dung sucking team. GO CODE THE FEATURE. 6 YEARS NOW.
