### ISSUE TITLE
Fetch remote changes automatically for submodules

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7624]
per @pateskinasy [here](https://github.com/desktop/desktop/issues/7523#issuecomment-494301936)

Further add-on to the improvements list:

In cases where a submodule is another repo (in my case this other repo holds all images) I can only get the main repo to see newly added images to the submodule if I run an update command on the CLI. `git submodule update --recursive --remote --merge --force `

How to reproduce:
- Add new image to submodule (the separate repo).
- Commit changes to the submodule on Github Desktop.
- Main repo does not see new image when switching repos on Github desktop, no new commit suggestion shows up.
- I run my CLI build command to try to get the update to happen (In my case `gulp`). The build completes without the new image.
- I run `git submodule update --recursive --remote --merge --force ` and now my main repo sees the image. I now get a commit suggestion on Github Desktop for the new image on the Main repo.
- My CD system now completes the build with the new image.

Desired behaviour:
- Add new image to submodule (the separate repo).
- Commit changes to the submodule on Github Desktop.
- Main repo sees new image when switching repos on Github Desktop, a new commit suggestion shows up.

**Comment by sergiou87** [comment]
If I understood this correctly, the problem is Desktop doesn't know the submodule has new commits in its remote, but I think surfacing that kind of info is tricky because not all users will want to keep their submodules up-to-date with their remotes.

Maybe the submodule's repo has a ton of activity, but in the main repo we'd want to update the submodule less frequently to prevent issues.

**Comment by sergiou87** [comment]
After discussing about it, we decided not to surface that information. Sorry!

**Comment by zoeLenglemetz** [comment]
Hello

I think it would still be a good option to add. For exemple in the Options menu to be able to check yes on no on this.
This will allow each use to choose their preffered option
