### ISSUE TITLE
Can NOT display Chinese/Japanese character

### ISSUE THREAD

**Issue by ntsoftabc** [desktop/desktop#7632]
## Version

* GitHub Desktop: 1.6.6

* Operating system: Windows 10 Home Edition

## Steps to Reproduce

1. `Add some Chinese/Japanese characters for comments`
2. `Can Not display(Unreadable for humans)`

**Comment by shiftkey** [comment]
@ntsoftabc are you able to share an example repository which has this problem? I believe this is related to how Desktop renders diffs for some file encodings, and we have an example repository in https://github.com/desktop/desktop/issues/3923 that illustrates the issue.

**Comment by ntsoftabc** [comment]
> @ntsoftabc are you able to share an example repository which has this problem? I believe this is related to how Desktop renders diffs for some file encodings, and we have an example repository in #3923 that illustrates the issue.

Thanks for your reply. Maybe I should install the Chinese language pack first. If it works, I will close this issue. Thanks again!

**Comment by ntsoftabc** [comment]
> > @ntsoftabc are you able to share an example repository which has this problem? I believe this is related to how Desktop renders diffs for some file encodings, and we have an example repository in #3923 that illustrates the issue.
> 
> Thanks for your reply. Maybe I should install the Chinese language pack first.
> If it works, I will close this issue. Thanks again!

Regret, I still can NOT fix this issue. Chinese/Japanese can NOT display correctly ..... @shiftkey

**Comment by tierninho** [comment]
> are you able to share an example repository which has this problem? 

Let us know if this ☝️ is possible. We are happy to help.

**Comment by shiftkey** [comment]
I'm going to close this out and cross-reference it in #3923. @ntsoftabc if you can provide a sample repository that is currently failing for Desktop that will help us to reproduce the issue ourselves.
