### ISSUE TITLE
showOpenDialog should be bound to a given BrowserWindow

### ISSUE THREAD

**Issue by mdiep** [desktop/desktop#7636]
## Description
If you click outside the file dialog while adding a local repo, the dialog _appears_ to dismiss and the UI is unresponsive.

## Version
* GitHub Desktop: 1.6.6
* Operating system: macOS 10.14.4

## Steps to Reproduce
1. Cmd-O to add a local repo
2. Click on _Choose…_
3. Click on the underlying window, outside of the Open dialog
4. Click on _Choose…_ again

### Expected Behavior
Really, I'd expect the Open dialog to appear as a sheet on the window. That's the correct way to indicate the modality that's used here.

But it would also be fine if clicking on the window actually dismissed the Open dialog or if the buttons on the _Add Local Repository_ modal worked.

### Actual Behavior
The Open dialog goes _behind_ the window with no indication that it's there. I actually thought that the dialog _had_ been dismissed. I quit the app several times while reproducing this because I didn't realize that I could get back to the open dialog.

**Comment by shiftkey** [comment]
@mdiep thanks for the feedback!

> Really, I'd expect the Open dialog to appear as a sheet on the window. That's the correct way to indicate the modality that's used here.

This does look like it's [supported in Electron](https://electronjs.org/docs/api/dialog#sheets), but it looks like we don't provide a window when we call the API:

https://github.com/desktop/desktop/blob/9d70b3394c298008c773b12877ae2b7445563d4e/app/src/ui/add-repository/add-existing-repository.tsx#L177-L179

I'll dig into that and see if that changes the dialog to behave like a sheet, and how that affects the flow. If I have any other questions I'll let you know.

**Comment by mdiep** [comment]
The changes to use a sheet look perfect. ✨ That's exactly what sheets are meant for. 👍

**Comment by shiftkey** [comment]
@mdiep thanks for confirming. We invoke this dialog in a few places, so I'd like to address all of this in one PR so they all follow this behaviour, but this guidance helps me greatly - thanks for working through it with me!
