### ISSUE TITLE
Multiple creation of Fetch_HEAD Files

### ISSUE THREAD

**Issue by Baz336933** [desktop/desktop#7642]
GitHub desktop app is creating multiple instances of the fetch_head file.
It appear unable to overwrite the existing file and continues to generate more and more daily.

**Comment by steveward** [comment]
Thanks for the report @Baz336933. Are you seeing this behavior in multiple repositories or in one specific repository?

Could you also upload the log file from GitHub Desktop so we could check to see if anything unusual is happening here? 

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

**Comment by tierninho** [comment]
@Baz336933 As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by phaniraj2112** [comment]
I am seeing the same behavior .

**Comment by steveward** [comment]
@phaniraj2112 are you possibly storing your repositories in the same directory as a file syncing service like Dropbox or Onedrive?

**Comment by phaniraj2112** [comment]
@steveward : Yes, on OneDrive.

**Comment by steveward** [comment]
@phaniraj2112 that's likely the cause of this issue. Moving your repositories to a different location should resolve the creation of multiple `FETCH_HEAD` files. We do not recommend storing repositories in file syncing services since it can cause issues like this.

**Comment by phaniraj2112** [comment]
Got it. Thanks for the update @steveward

**Comment by varunbhalerao** [comment]
@steveward I have work circumstances which make it impossible for me to move all my github repositories out of onedrive. Is there a fix that can be implemented for this? As a very lame quick workaround, I am tempted to write a cron job that will find all `FETCH_HEAD-*` files and delete them say once a day. Will that work, or might it cause other issues?

**Comment by steveward** [comment]
@varunbhalerao this isn't something that we would be able to provide a fix for on our side, since OneDrive is creating those files. Deleting the duplicate `FETCH_HEAD` files should not be an issue.

**Comment by TastefulSamwise** [comment]
I am of the opinion that this is a ridiculous issue. Why can we not have repositories stored on onedrive as a backup without having this occur?
