### ISSUE TITLE
detect and warn about unreachable code using eslint

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#7643]
**Please describe the problem you think should be solved**

A small change to the diff of `app/src/ui/changes/no-changes.tsx` in https://github.com/desktop/desktop/commit/06b9016636f2cec67084700c76fbea611759e933 caught my eye, as it didn't look relevant to the changes in #7257.

<img width="495" alt="Screen Shot 2019-05-29 at 10 39 43 AM" src="https://user-images.githubusercontent.com/359239/58561810-63598c00-81fe-11e9-8d2d-c6a6fffd0bfe.png">

Turns out this was some unreachable code, and could be safely removed.

**[Optional] Do you have any potential solutions in mind?**

To catch any other cases like this, I'd recommend enabling [`no-unreachable`](https://eslint.org/docs/rules/no-unreachable) in our `.eslintrc.yml` file and verifying we have no more issues like this.

**Comment by Rexogamer** [comment]
do you want this as a warning or an error?
