### ISSUE TITLE
"changed files" indicator in repository list can be hidden with keyboard focus

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#7651]
## Description

This is not a regression for 1.7, but something I noticed while testing today and wanted to write up because the layout changes in #7623 make this more noticeable and cause the other indicators to appear to be floating.

## Version
* GitHub Desktop: `1.7.1-beta1`
* Operating system: Windows 10

## Steps to Reproduce
1. Add a few repositories to the app so that you can switch between then
2. Add some changes to the list so that the indicator appears (at least the "changed files" indicator, but the "ahead/behind" indicator here also helps to understand the impact)
3. Expand the repositories list and use your keyboard to move up/down until you highlight a repository that has changed files. Don't switch to it, just linger there.

### Expected Behavior
The "changed files" indicator is visible

### Actual Behavior
The "changed files" indicator is the same colour as the background when the list has keyboard focus, so it becomes invisible. And because it's after the ahead/behind indicator, it now looks misaligned.

<img width="215" alt="indicator-hidden-light-theme-keyboard-focus" src="https://user-images.githubusercontent.com/359239/58637790-b1879180-82c9-11e9-96cd-268c1780c954.png">

I think, in this situation, the indicator should be "inverted" like we do with the icon, to ensure it's visible.

When you do not have keyboard focus, the background for the list reverts to a light grey, which shows the indicator.

<img width="208" alt="indicator-light-no-keyboard-focus" src="https://user-images.githubusercontent.com/359239/58637794-b1879180-82c9-11e9-8ad9-4270b81c6220.png">

This is also visible when using the dark theme:

<img width="222" alt="indicator-hidden-when-keyboard-focus" src="https://user-images.githubusercontent.com/359239/58637793-b1879180-82c9-11e9-8970-bc5af3eb7be2.png">

And here's how it looks without the keyboard focus:

<img width="215" alt="indicator-no-keyboard-focus" src="https://user-images.githubusercontent.com/359239/58637795-b2202800-82c9-11e9-876f-6a3c3a6bf012.png">

**Comment by tierninho** [comment]
Agree that we ought to fix this. Here is another view that shows the "floating".

![Screen Shot 2019-05-30 at 3 14 46 PM](https://user-images.githubusercontent.com/14828183/58674911-af372e80-82ed-11e9-9e2a-46d85cd88aa6.png)
