### ISSUE TITLE
"unable to restore" prompt appears when restore takes time to complete

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#7652]
## Description

The warning we have setup to originally indicate that a stash cannot be restored also appears as part of the normal restore flow:

<img width="754" src="https://user-images.githubusercontent.com/359239/58640432-6ec8b800-82cf-11e9-9634-bce4ca494c6f.png">

## Version
* GitHub Desktop: `1.7.1-beta1`
* Operating system: Windows 10

## Steps to Reproduce
1. Setup a stash to restore (I've been able to see this with as few as 3 files, but 20+ is a good number)
2. Restore the stash

### Expected Behavior

Some indicator of progress while restoring the stash would be nice, but other than that the experience is fine.

### Actual Behavior

Midway through the restore process the alert about "Unable to restore stash..." appears and then disappears:

![restore-warning-appears-during-restore](https://user-images.githubusercontent.com/359239/58640900-6e7cec80-82d0-11e9-9822-47765652992b.gif)

This is confusing in a couple of ways:

 - the ⚠️ indicator suggests something hazardous
 - how it appears and disappears while I'm waiting makes me a bit nervous

**Comment by billygriffin** [comment]
Oof, yes. I don't like this at all - that's a rough experience. It's not blocking the workflow but does create unnecessary confusion and uncertainty. Just getting back into this, but this feels like a priority 2 bug and pretty high priority on the things to fix for stashing.

**Comment by tierninho** [comment]
Good catch 👍 Confirming I can repro with one stash on Mac.

**Comment by shiftkey** [comment]
The fix I had in mind for this overlaps with what's currently happening in #7683, so I'm gonna pause that and keep an eye on that PR.

**Comment by iAmWillShepherd** [comment]
> Oof, yes. I don't like this at all - that's a rough experience. It's not blocking the workflow but does create unnecessary confusion and uncertainty. Just getting back into this, but this feels like a priority 2 bug and pretty high priority on the things to fix for stashing.

I've added this to the stashing priority list for discussion.
