### ISSUE TITLE
Issues with ESLint

### ISSUE THREAD

**Issue by ADustyOldMuffin** [desktop/desktop#7655]
So this isn't a direct issue with Github Desktop, but as I've been working on it I've come across this error in almost every file.

`Definition for rule 'insecure-random' was not found eslint(insecure-random)` 
![image](https://user-images.githubusercontent.com/41391321/58648751-07f7ce80-82d0-11e9-8222-cb780274c0e2.png)

I don't think I missed any steps during setting the project up, and I've done some research and can't seem to find anything related to it. My output from my extensions are also all clear, and it does not affect the running of the app.

Anyone wanna lend a guy some help? 🙃 I'm not a fan of red squigglies.

**Comment by ADustyOldMuffin** [comment]
I believe the extension is grabbing the wrong config as the output is giving
![image](https://user-images.githubusercontent.com/41391321/58660190-79dd1180-82ea-11e9-8ba6-70b796ba2e7d.png)

This seems to be a common problem, and everyone keeps finding their own solution so I'll keep looking into it.

**Comment by ADustyOldMuffin** [comment]
So I looked into it, and it's because it cannot find the eslint rule for the `insecure-random.js` file as it's not imported in the eslintrc file as a plugin. I'm unsure how to fix this and I do not have experience with eslint to start tackling this.

**Comment by shiftkey** [comment]
> I'm unsure how to fix this and I do not have experience with eslint to start tackling this.

@ADustyOldMuffin there's a number of config values that you can set inside `.vscode/settings.json` after installing the extension, which I think might be missing here. I'd have a look at the [README](https://github.com/microsoft/vscode-eslint#README) here and see if you can provide these values to emulate what our `eslint` script action is running. 

The `eslint.options` value looks particularly promising:

```json
{
  "eslint.options": { "configFile": "C:/mydirectory/.eslintrc.json" }
}
```

This looks like it' corresponds to the eslint command line options found here: https://eslint.org/docs/developer-guide/nodejs-api#cliengine

**Comment by ADustyOldMuffin** [comment]
Much appreciated!
