### ISSUE TITLE
Suggestion – Allow grouping/sorting of local repositories

### ISSUE THREAD

**Issue by thezaza101** [desktop/desktop#7657]
**Description**
Make the list of local repositories easier to navigate by adding a few features:

- Always show the user/organization a repository belongs to
- Group repositories using user/organization, make the groups collapsible

**Why**
I have cloned over 30+ local repositories using GitHub desktop. These contain both personal and work related repositories, some of the repos are forks from different users. It would be good to be able to sort them. 

**Screenshots**
Imagine any 1 level tree view. i.e.
![Tree view](https://joekuan.files.wordpress.com/2016/02/screen.png "Tree view")

**Comment by tierninho** [comment]
@thezaza101 Thanks for sharing your thoughts. Please take a look at some recent work about repository grouping [here](https://github.com/desktop/desktop/issues/7132), which was motivated by [this](https://github.com/desktop/desktop/issues/6460). Feel free to respond and offer feedback on the latter link.

You can [download](https://github.com/desktop/desktop#beta-channel) our beta version to use the functionality now, or wait until next week when it is released to all.

Going to close this out, but feel free to comment if you have any more questions. Cheers!
