### ISSUE TITLE
"create new repository" doesn't warn about using an existing local repository

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#7660]
## Description

I thought we had a flow in "Create new repository" where if the path was to an existing repository we would redirect them to just add that to the app, but the flow doesn't seem to show that message any more.

## Version

* GitHub Desktop: `1.7.1-beta1`
* Operating system: macOS and Windows

## Steps to Reproduce

1. Create a new empty repository at some location on disk. Here's my setup:

<img width="962" src="https://user-images.githubusercontent.com/359239/58711409-e280c880-8394-11e9-80d9-652c23d8fb21.png">

2. I press "Create repository" and then switch to History to see the single new commit:

<img width="964" src="https://user-images.githubusercontent.com/359239/58711411-e280c880-8394-11e9-919f-e7518b269280.png">

3. I start the "Create new repository" flow again **but use the exact same name as before**. 
<img width="961" src="https://user-images.githubusercontent.com/359239/58711412-e280c880-8394-11e9-8c30-0adb40b0ab1b.png">

4. The only clue I could find here that something was amiss was when I went to add a README and it warning about being overwritten. 

<img width="961"  src="https://user-images.githubusercontent.com/359239/58711415-e280c880-8394-11e9-8ecc-0262e5f93a72.png">

5. I finish the flow and press "Create repository" again, and I see that the repository has two commits, one from each time it was initialized

<img width="960" alt="re-initialize-repo-step-5" src="https://user-images.githubusercontent.com/359239/58711417-e280c880-8394-11e9-8eb3-34d7eaf6e511.png">

### Expected Behavior

A warning the second time when the path matches an existing repository, and suggesting either to use a different name or let the user add this existing repository to the app.

### Actual Behavior

No warning, and me being very confused at the history I saw when I completed the flow

**Comment by samuelko123** [comment]
I am unable to reproduce the issue.

GitHub Desktop: `3.2.1`
Operating system: Windows 10 (x64)

![image](https://user-images.githubusercontent.com/91960206/233769512-31b42589-6709-42d6-8652-188ee75005f2.png)

**Comment by tidy-dev** [comment]
Thanks for taking a look at this @samuelko123!
