### ISSUE TITLE
I want to change the font.

### ISSUE THREAD

**Issue by songshinyoung** [desktop/desktop#7671]
I want to change the font of the **diff. screen.**
How can I change it?
![diff screen](https://user-images.githubusercontent.com/13674201/58773295-7f42a080-85f7-11e9-95fb-0409cc0cac52.png)

**Comment by shiftkey** [comment]
@songshinyoung thanks for the feedback. I'm going to add your comment to #3923 as the problem is not related to font selection, but to the encodings in the file not being handled correctly. Please follow along with that issue.
