### ISSUE TITLE
Need a place to manage repo issue

### ISSUE THREAD

**Issue by cnyyk** [desktop/desktop#7672]
Need a place to manage repo issue

**Comment by shiftkey** [comment]
@cnyyk thanks for the suggestion. We've had a few discussions about this in the past, but these thoughts in https://github.com/desktop/desktop/issues/1866#issuecomment-431407815 are still our current thinking:

> Generally, we do not consider Desktop to be a local version of GitHub.com, but rather a workflow tool, so we try to focus on specific problems in the context of your work as opposed to replacing the functionality of GitHub in the browser.

For the moment, we don't have plans to tackle this without more insight into the workflows related to issues and how they overlap with Desktop.

**Comment by cnyyk** [comment]
OK. thanks for you reply.
