### ISSUE TITLE
`Go to Summary` menu options closes Stash pane in favor of Next Steps 

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7675]
If you are viewing stashed changes and you use the menu or hotkeys to `Go to Summary`, then the Stashed Changes pane is closed in favor of Next Steps. 

As one can still commit files with the Stashed Changes pane in view, then I am going to label this a bug. 

Repro:
- open stashed changes
- cmd-G

1.7.1-beta1, mac

**Comment by tidy-dev** [comment]
No longer reproducible - tested in GitHub Desktop 3.4.5
