### ISSUE TITLE
Discard changes... doesn't play nicely with Textmate

### ISSUE THREAD

**Issue by doekman** [desktop/desktop#7678]
First I filed a bug with Textmate:

> I've editted some files and saved them. The change didn't work out, so I do a `Discard changes...` in GitHub Desktop. When I come back to Textmate, the changed file is still open, but it's in the Trash (screenshot `1.File-in-Trash.png`).
> 
> When I close the project (shift+cmd+W) and reopen it (via shift+cmd+O), Textmate opens the Trash again. So now I can't even open database files via the file browser.
> 
> When I open a project file via Finder, the new file opens in the project window. When I close the file from the Trash, everything is fine again.
> 
> ![1.File-in-Trash.png](https://user-images.githubusercontent.com/1086388/58868209-24bf4800-86bc-11e9-98c7-45bae6c442a7.png)
> 
> A couple of problems:
> 
> 1. The only visual clues you have that a file is (accidently) in the Trash are the File Browser shows the Trash, and there is some kind of version number in the title bar.
> 2. In the titlebar, it is suggested that the file is still in the database project (the `-- database` part) and the git repository (the `(git: master)` part).
> 
> I think when you open a file from the Trash in TextMate, it should be at least read only,  or there should be a prompt that these files are in the Trash.
> 
> I have the `Preferences > Projects > Keep current document selected` option enabled.
> 
> I'm on macOS Mojave 10.14.5 (18F132) and TextMate version 2.0-rc.23.

Response from Textmate support:

> So what is happening here is that many apps do file saving in a ‘whole’ file manner. What this means is that they write an entire copy of the file separately from the current file then swap the file once complete. This is done to be safer incase the process is interrupted or the app crashes during the save process. With the file swap method there is only a split second when problem could technically occur. TextMate does all it’s saving this way through the exchangedata system call you read about here:
> 
> <https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/exchangedata.2.html>
> 
> Now as for what is going on here… We generally only see an issue with this code when a cross platform app is used because they are doing this process manually in some fashion rather than using the correct OS system calls. Doing so mean we can’t tell the difference, when monitoring a file for changes, between you moving the folder a file is in or Github Desktop moving the files/folders. In the first case we do want to follow the file to the new location, in the latter we don’t. We do already have checks for this to work around this issue but it is done by checking when we see a file moves to make sure a new one isn’t placed into the old place very quickly. So it’s a really horrible work around really.
> 
> People constantly use git by the command line in TextMate so this can’t be a git issue, it must be unique to how Github has customized their branch of it in their app. We could attempt a workaround but it ideally would be corrected on their side.
> 
> Forgot to say: Since TextMate followed the move of the file incorrectly it will keep referencing the file like you saw until closed/opened in the correct location. So that part isn’t really incorrect, just a consequence of the incorrect behavior in the first place.

So basically, can't GitHub Desktop use the afore mentioned system call? It would make the tool much better. 

(I do like GitHub Desktop because of the simplicity, though I liked the old native version better, but you can't stop progress I guess).

**Comment by shiftkey** [comment]
@doekman thanks for the detailed writeup!

> So basically, can't GitHub Desktop use the afore mentioned system call?

The "Discard Changes" dialog uses an Electron API named [shell.moveItemToTrash](https://electronjs.org/docs/api/shell#shellmoveitemtotrashfullpath) which runs this code:

https://github.com/electron/electron/blob/d008d217f9219c5f867a67139e1aa6779fc152e4/atom/common/platform_util_mac.mm#L117-L127

```c++
bool MoveItemToTrash(const base::FilePath& full_path) {
  NSString* path_string = base::SysUTF8ToNSString(full_path.value());
  BOOL status = [[NSFileManager defaultManager]
        trashItemAtURL:[NSURL fileURLWithPath:path_string]
      resultingItemURL:nil
                 error:nil];
  if (!path_string || !status)
    LOG(WARNING) << "NSWorkspace failed to move file " << full_path.value()
                 << " to trash";
  return status;
}
```

And once that's completed, we run the minimal set of Git operations to try and put the clean repository back to a good place:

https://github.com/desktop/desktop/blob/c65cbe1aa16237ca9237b0c94a2d34ccad8add09/app/src/lib/stores/git-store.ts#L1333-L1355

It's not clear to me how `exchangedata` would be used with a trashed file, but I'll do some more reading of the issue and what the Textmate maintainers have said about things from their side.

**Comment by doekman** [comment]
I only understand this on a conceptual level, so I'm not of much use (I would have thought GitHub Desktop would use `git reset ...` to the discarting, but that's apparently not the case).

I hop you find out more.

**Comment by shiftkey** [comment]
> (I would have thought GitHub Desktop would use `git reset ...` to the discarting, but that's apparently not the case).

A `git reset` would remove the changes from your working directory without any way to recover them. The current behaviour is to move the new and modified files to the trash so that you can access and restore them if it was a mistake. That feels more forgiving to end users.

**Comment by tidy-dev** [comment]
As described above we use electron's methods for discarding to the trash and are not likely to change for the other reason of being able to recover your files from the trash if discarding was a mistake. Closing this as not planned.
