### ISSUE TITLE
idea: suggest local clone path based on both owner and repo name

### ISSUE THREAD

**Issue by zeke** [desktop/desktop#7685]
Hey Desktop friends! 👋 Please consider this a LOW priority issue.
 
I keep my local git repositories in directories by owner name, like `~/git/{owner}/{repo}`. For example, `~/git/desktop/desktop` or `~/git/zeke/dotfiles`.

It would be nifty if Desktop suggested local clone directories based on this pattern. I know not everyone may want to organize their repos this way, but I think would make a sensible default, and reduce the amount of legwork required to avoid name collisions (especially when cloning forked repos).

## Current behavior

<img width="486" alt="Screen Shot 2019-06-04 at 1 38 33 PM" src="https://user-images.githubusercontent.com/2289/58912098-2d207e80-86ce-11e9-84da-d08670423601.png">

## Desired behavior

<img width="494" alt="Screen Shot 2019-06-04 at 1 38 44 PM" src="https://user-images.githubusercontent.com/2289/58912142-4295a880-86ce-11e9-8a69-9a7d35fa6a1a.png">

I noticed some other related issues, but they all seem to be related to the organization of repos in the Desktop UI, rather than the organization of repos on the filesystem:

- Recent Repositories Group https://github.com/desktop/desktop/issues/7132
- Repositories are difficult to find, navigate, and differentiate https://github.com/desktop/desktop/issues/6460
- Group repos by organization (and make orgs collapsable): #2037

**Comment by shiftkey** [comment]
@zeke thanks for opening this up!

We've got a very similar issue to this #5449 (same suggestion, but refers to the other clone tab) which I'm going to merge this into to avoid tracking duplicate discussions...
