### ISSUE TITLE
After moving Master to new server instance, "Repository/View on GitHub" fails

### ISSUE THREAD

**Issue by danpoleary** [desktop/desktop#7690]
## Description

When a repository is moved from one server URL to another, and we re-point to the new server, everything works except when you click on "Repository/View on GitHub". It tries to open the old location, and not the new location.

All other commands/menus work (Fetch, Commit, Push. Pull, etc..)

## Version

* GitHub Desktop: 1.6.6

* Operating system:  Windows Server 2016 Standard Version 10.0.14393 Build 14393

## Steps to Reproduce

1. Click on "Repository/View on GitHub"
### Expected Behavior

Browser opens repository at correct URL
### Actual Behavior

Tries to open repository at old URL location

**Comment by steveward** [comment]
Thanks for the report @danpoleary. I was able to reproduce this as well. To workaround this you can remove the repository from GitHub Desktop and then add it back, which should then point to the correct URL.

**Comment by danpoleary** [comment]
Just tried that, now cannot get any enterprise repository. Keeps
tryingvoldcserver path and cannot get to new enterprise path.

**Comment by danpoleary** [comment]
> Thanks for the report @danpoleary. I was able to reproduce this as well. To workaround this you can remove the repository from GitHub Desktop and then add it back, which should then point to the correct URL.

I did some more investigation on the issue. When I remove the repository, and add it back in by adding local, it shows up in 'other' instead of 'enterprise' and no longer allows me to view on GitHub.  It is grayed out. I removed it again, renamed the folder on drive, and tried to reclone from server. It tried the old server. I then signed out of my enterprise, and resigned in to the new URL. This allowed me to clone a new copy, but again, it does not show up under 'enterprise' and option to view on GitHub is grayed out.

**Comment by danpoleary** [comment]
It has gotten worse. Now that I added it back, I can no longer switch branches. Removing and re-adding the repository has really messed up everything.

**Comment by steveward** [comment]
@danpoleary I'm not sure how your repository would have gotten into that state just from removing it from the application and adding it back. Are you seeing any error messages when performing operations?

It would be helpful if you could upload the log file so that I could take a closer look at what might be happening here.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by danpoleary** [comment]
My log only contains:
```
2019-06-07T15:52:02.660Z - info: [ui] [AppStore] loading 4 repositories from store
2019-06-07T15:52:02.661Z - info: [ui] [AppStore] found account: doleary (Daniel O`Leary)
2019-06-07T15:52:02.661Z - info: [ui] [AppStore] found account: danpoleary (Daniel O'Leary)
2019-06-07T15:52:02.924Z - info: [ui] launching: 2.0.3 (Windows 10.0.14393)
2019-06-07T15:52:02.960Z - info: [ui] execPath: 'C:\Users\Administrator\AppData\Local\GitHubDesktop\app-2.0.3\GitHubDesktop.exe'
```
Cannot click on "Fetch" in the UI.  "View on GitHub" is greyed out. and the repository in question shows up under "Other" and not "Enterprise"

Dan

No error messages are displayed.

**Comment by danpoleary** [comment]
We have validated that once we moved our repositories from server A to server B, and repoint the local to the new servers, GitHub desktop stops working on those repositories without any error messages in the log or on screen. I have checked this on Windows 10, Windows 7, Server 2012R2 and Server 2016.

All Git GUI, Git bash, Eclipse, VS, etc... commands work. This only affects Desktop.

**Comment by danpoleary** [comment]
If I completely de-install GitHub Desktop and remove the "appdata\roaming\GitHub Desktop" directory, then  reinstall and re-add repositories, then everything works as expected. I have left one machine in the wonky state to help in finding the root cause of this issue. Let me know if you need anything from me.

Dan

**Comment by steveward** [comment]
Reported in https://github.com/desktop/desktop/issues/16319.

**Comment by tidy-dev** [comment]
Appears to be fixed. Maybe the work about renaming repositories helped with this one. 

Steps I took to reproduce:
1. Changed the remote url of a repository to another repository.
2. Fetched and Pushed (worked)
3. Open View on GitHub. Opened new repository destination. (worked)

I may be oversimplifying my reproduction steps so if feel free to respond back.
