### ISSUE TITLE
Discard all changes doesn't appear after right clicking all changed files after 6/5/2019 update

### ISSUE THREAD

**Issue by Ruuubickk** [desktop/desktop#7698]
Hi,

After today's update, it isn't possible to discard all changes by right clicking the "X changed files" button. It was really useful, and now requires to open the branch drop-down menu at the top and select "Discard all changes". 

**[Optional] Do you have any potential solutions in mind?**
 Revert it, unless there's a very good reason as to why that option has been removed ?

**Comment by shiftkey** [comment]
@Ruuubickk thanks for the feedback.

I'm going to merge this with our other discussion on this, #7696. Please follow along with that!
