### ISSUE TITLE
Unable to clone on Mac

### ISSUE THREAD

**Issue by vijayaj5** [desktop/desktop#7703]
## Description

Unable to clone the repository on MAC machine.

## Version

* GitHub Desktop:

* Operating system:

**Comment by vijayaj5** [comment]
Unable to clone the repository on MAC machine. 
![Screenshot 2019-06-06 at 10 58 56 AM](https://user-images.githubusercontent.com/41433476/59009151-1d2da980-884a-11e9-8ee4-8ac4df317b39.png)

**Comment by shiftkey** [comment]
@vijayaj5 thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by vijayaj5** [comment]
Github Desktop version: 2.0.3 
Prob statement: When trying to clone a repository, file completely downloaded. Later it showing unable to locate your file as shown in the screenshot. 
Troubleshoot: Tried replacing Github app by deleting all old contents, yet not resolved. 
Need: Kindly do the necessary measures to resolve this and intimate.

**Comment by shiftkey** [comment]
> Troubleshoot: Tried replacing Github app by deleting all old contents, yet not resolved.

@vijayaj5 thanks for that screenshot - it looks like there's an issue with the database we use to store app data. Are you able to:

1. open the **Application** tab
2. find the **Database** entry under **IndexedDB**
3. **Delete database** to cleanup anything that might be in there
4. Restart GitHub Desktop
5. Add the existing repository from `~/Documents/GITT/bgr-app`

<img width="1327" src="https://user-images.githubusercontent.com/359239/59217847-3f4e6100-8b95-11e9-92c7-a5bb052fd4e4.png">

Hopefully that gets you back to a good place!

**Comment by vijayaj5** [comment]
Hi, I have tried all the steps you mentioned above, yet the 
![Screenshot 2019-06-11 at 11 54 08 AM](https://user-images.githubusercontent.com/41433476/59248380-dd970100-8c3f-11e9-8ff6-e68a5af5dd99.png)
problem not resolved. Please find the attached Image for reference.

**Comment by vijayaj5** [comment]
Could someone please help me with this.

**Comment by shiftkey** [comment]
@vijayaj5 this looks like a different database is having issues. Could you try deleting the `PullRequestDatabase` in the app and restarting the app?

**Comment by vijayaj5** [comment]
1. Where to find PullRequestDatabase?
2. Please find the log for your reference

Trying to resolve for a very long time, please provide a solution.
[2019-06-14.desktop.production.log](https://github.com/desktop/desktop/files/3289059/2019-06-14.desktop.production.log)

**Comment by shiftkey** [comment]
@desktop/support are you able to help out with this one?

**Comment by tierninho** [comment]
@vijayaj5 As support is wrapping up their day, here is the `PullRequestDatabase` -- see the green arrow. Similar steps you did earlier.

1. open the Application tab in dev tools
2. Find the `PullRequestDatabase` entry under `IndexedDB`
3. Delete `PullRequestDatabase`
4. Restart GitHub Desktop
5. Add the existing repository from ~/Documents/GITT/bgr-app

<img width="1327" alt="59217847-3f4e6100-8b95-11e9-92c7-a5bb052fd4e4" src="https://user-images.githubusercontent.com/14828183/59534995-766d8c80-8e8b-11e9-9033-74bb57a607da.png">

**Comment by tierninho** [comment]
@vijayaj5 As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
