### ISSUE TITLE
"Switch branch" dialog should confirm selection with double click

### ISSUE THREAD

**Issue by pinguin999** [desktop/desktop#7705]
In version 2.0 a new popup asks to leave or bring changes.

It would be nice if a double click would confirm the selected choice.

**Comment by shiftkey** [comment]
@pinguin999 thanks for the feedback.

@desktop/product @desktop/design any thoughts about this?

**Comment by billygriffin** [comment]
Hi @pinguin999, thanks for the suggestion! We're not wedded to the existing design and may iterate if we continue to hear feedback like this. We're also going to do more usability testing with folks to observe whether this is feeling like too much friction. I'm going to close this issue to indicate that we don't intend to support this exact implementation, but we are definitely gauging overall perception to see whether we stick with what we've got now or look for ways (similar to your suggestion) to reduce friction.

**Comment by danqing** [comment]
Wanted to give a +1 - came here to file exactly the same issue; searched and found this one. Double-click is something I think many users would expect to work.
