### ISSUE TITLE
Cannot right click in 'Changes' tab

### ISSUE THREAD

**Issue by Ravi5ingh** [desktop/desktop#7706]
## Description

I can no longer right click in the 'Changes' tab in the top section which shows 'x changed files'. I'm aware of issue (https://github.com/desktop/desktop/issues/7356) where the user requested that Discard All Changes be removed but I use this feature quite a lot so I suggest the following:

* User right clicks individual file in the list (Should not include Discard All Changes in context menu)
* User right clicks top section with 'x changed files' (There should be a context menu and Discard All Changes should be one of the items)

## Version

* GitHub Desktop: 2.0.3

* Operating system: Microsoft Windows [Version 10.0.17763.1]

## Steps to Reproduce

1. Open Github desktop
2. Ensure you have a repo setup with Github Desktop
3. Change multiple files in the repo
4. Right section at the top of the changed file list where it says 'x changed files'

### Expected Behavior

There should be a context menu which includes 'Discard All Changes'

### Actual Behavior

There is no context menu

## Additional Information

The following is a screenshot of the area where I would like to right click to see the context menu mentioned above
![Capture](https://user-images.githubusercontent.com/24965910/59026444-50723780-884e-11e9-9c1e-012abd8870ee.PNG)

**Comment by shiftkey** [comment]
@Ravi5ingh thanks for the feedback!

We're already discussing this in #7696, so please follow along with that issue.
