### ISSUE TITLE
Discard all changes missing.

### ISSUE THREAD

**Issue by DivyaBharti123** [desktop/desktop#7711]
## Description
Discard all changes missing

## Version
v2.0.3
* Operating system:
Windows 10

## Steps to Reproduce
1. Add changes to branch
2. Now, try to remove/ discard all the changes 
3. Observe, Discard all option is missing.

### Expected Behavior
Discard all should be present 

### Actual Behavior
Discard all option is not appear

**Comment by shiftkey** [comment]
@DivyaBharti123 thanks for the feedback!

This is something we moved to a menu item in the `Branch` menu in 2.0, but we're talking about revisiting this in #7696 - please follow along with that discussion...
