### ISSUE TITLE
Add the ablitity to browse repos in the client

### ISSUE THREAD

**Issue by steskalja** [desktop/desktop#7712]
Add the ability to browse repos in the client rather than needing to open the browser. Basically brining the web experience natively to the desktop

**Comment by billygriffin** [comment]
Hi @steskalja, thanks for the idea! Would you mind elaborating? Any repo available to you on GitHub.com should be available to clone in GitHub Desktop. If you're looking to just view repos without having them locally, we think the web is probably the best place to do that, and GitHub Desktop is not intended to be a 1 for 1 replacement for GitHub.com. I'm going to close this issue but if you have more thoughts or if I'm not understanding correctly, please let me know!
