### ISSUE TITLE
Manually Stash All Changes

### ISSUE THREAD

**Issue by the-avid-engineer** [desktop/desktop#7714]
**Please describe the problem you think should be solved**
With the release of GitHub Desktop 2.0, there is a great new feature where you can stash changes if you switch branches. It would be even greater if you could trigger the exact same behavior without switching branches!

In other words, I'm asking for a **Stash all changes...** option in the Branch toolbar menu 😊

**Comment by billygriffin** [comment]
Hi @the-avid-engineer, thanks for the suggestion! We did quite a few of user interviews and waded into a bunch of discussions on how people stash and for what purpose. We know there are a ton of different reasons why you *could* stash, but the context-switching one came up over and over again and represented the vast majority of what we heard. We know you're not the only person with this desire, and I totally understand how it could be useful. However, we want to let this ship breathe for a bit and see how people are using it and what they're missing prior to evaluating where we go with stashing from here. I would love to hear what you're doing when you want to just stash changes, but stay on the same branch, and in what scenarios this would be useful for you, if you don't mind sharing.

For now I'm going to close this to indicate it isn't something we're going to support in the near term, but we're definitely not wedded to our existing solution and will continue to collect feedback, and potentially implement something like this down the road. Thank you!!

**Comment by the-avid-engineer** [comment]
Hi @billygriffin, my use case is very much an edge case, but here we go:

I do use branches, and the current behavior is going to be GREAT for that (**thank you!**), but at least half of the time I'm just working directly on master because it usually happens to be that no one else is working on the same repository as me. (Small engineering team)

But, every now and then, my boss says, "Hey, can you fix something really quick?"

What I will usually do here is:

1. Create/switch to a `wip` branch
2. Commit all changes to `wip`
3. Switch to `master` branch
4. Create/commit fixes to `master`
5. Push `master` to the origin
6. Switch to `wip` branch
7. Undo the staged commit on `wip`
8. Switch back to `master` branch.

If I could manually trigger the stash operation that is triggered on switching branches, this would become:

1. Stash all changes for `master`
2. Create/commit fixes to `master`
3. Push `master` to origin
4. Reapply stashed changes for `master

Hope that helps

**Comment by billygriffin** [comment]
Ah, ok, got it. That makes sense. Fascinating. We'll definitely continue to look out for these types of things more broadly, appreciate you sharing!

**Comment by the-avid-engineer** [comment]
@billygriffin I might add, without this feature, my workflow is now slightly longer

1. Create/switch to a `wip` branch **+ modal to transfer changes to `wip`**
2. Commit all changes to `wip`
3. Switch to `master` branch
4. Create/commit fixes to `master`
5. Push `master`to the origin
6. Switch to `wip`branch
7. Undo the staged commit on `wip`
8. Switch back to `master`branch  **+ modal to transfer changes to master**

**Comment by the-avid-engineer** [comment]
Another use case I run into, less frequently, is when someone else committed changes and I have uncommitted changes on files that were affected by their changes. If I try to pull their changes down, I get this little popup:

![image](https://user-images.githubusercontent.com/36554739/59137245-ab358d00-893b-11e9-8c4f-92db7310a5b3.png)

The workflow I use to get a hotfix in also works for getting around this problem, with steps 4 and 5 being replaced with a step to pull `master`, and would equally benefit from manually stashing all changes.

**Comment by shiftkey** [comment]
> If I try to pull their changes down, I get this little popup:

@the-avid-engineer this use case is interesting, and I can envision a future version of Desktop that stashes changes before `pull` to then pop the stash to handle conflicts, avoiding this Git error completely.

You can setup your environment to "pull with rebase" and "autostash when rebasing", but there's no equivalent setup for "pull with merge" with uncommitted changes...
