### ISSUE TITLE
Push notification if remote-branch got updated

### ISSUE THREAD

**Issue by Simonwep** [desktop/desktop#7724]
Let's assume multiple developers work on the same branch, at the same time. And one pushes his changes. I would love it if there would be an option to get a desktop-notification when someone pushes to a branch on which you are currently working, so you can make sure to pull first before provoking merge conflicts. 

Example:
User **A** and **B** are working on _foo/master_.
User **A** changes something and pushed it to the remote branch _master_.
User **B** get's a notification that he's not up-to-date on the current branch. He quickly pulls the new stuff and continues without getting in struggle of a potential merge-conflict.

I now that's what PRs and branches are for, but I mean in this case I'd help - It's better than texting _Hey baa, I've just pushed smth, could you pull and take a look at it before making any more changes?_ 😊

**Comment by tierninho** [comment]
@Simonwep Many thanks for the suggestion. Currently, this is our viewpoint https://github.com/desktop/desktop/issues/2825#issuecomment-438807773 which doesn't mean it is not going to happen, it just needs more thought. Closing this issue for now.
