### ISSUE TITLE
Error at starting Github Desktop

### ISSUE THREAD

**Issue by krishnadubagunta** [desktop/desktop#7725]
## Description

I tried to open the application after updating to the latest release, I couldn't open, So I removed the application and tried to download it from the website, and after opening the application, I got a blank screen as the screenshots show below

## Version

* GitHub Desktop: 2.0.3

* Operating system: 10.13.6

## Steps to Reproduce

1. Notification to checkout new github desktop version
2. Download and restart application
3. White Screen

![Screen Shot 2019-06-07 at 11 00 32 AM](https://user-images.githubusercontent.com/5184242/59113682-82999d00-8913-11e9-94f3-f189056f96a8.png)

![Screen Shot 2019-06-07 at 11 01 04 AM](https://user-images.githubusercontent.com/5184242/59113705-91804f80-8913-11e9-99b9-027c804663b5.png)

### Expected Behavior

To open the diff
### Logs

[2019-06-06.desktop.production.log](https://github.com/desktop/desktop/files/3266499/2019-06-06.desktop.production.log)

**Comment by iAmWillShepherd** [comment]
Hello @krishnadubagunta,

Try this

1. Quit Desktop
1. Run `rm -rf ~/Library/Application\ Support/GitHub\ Desktop/` in your terminal
1. Reopen Desktop

**Comment by krishnadubagunta** [comment]
That helped. Thanks @iAmWillShepherd
