### ISSUE TITLE
Stash is present but no files are visible

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7730]
Ran into an issue randomly with a new Enterprise repo, where I had untracked files and a Stash present, but the Stash was empty despite the the UI telling me otherwise. 

- My repo was not published yet
- Not sure where those files came from as I never added them

![Screen Shot 2019-06-07 at 3 29 17 PM](https://user-images.githubusercontent.com/14828183/59140446-10d44a00-8939-11e9-9500-08a25ecf24c8.png)

Nothing in the logs.

My `git status`:
```
✗ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	2BForked/
	TestWebAppProject/
	asfdsdfsdf/
	dfdfsdf/
	dfsdfsdfsdfsdffff/
	fsdf/
	nkmdfmknmksdvvsd/
	sdfsdf/
	sdsdsdsdfsdfdfsfdsfsddfs/
```

Resolved by discarding all files (via Menu) then restoring stash, which did nothing.

Seems related to: https://github.com/desktop/desktop/issues/7720 and https://github.com/desktop/desktop/issues/7717

2.0.3, mac

**Comment by shiftkey** [comment]
@tierninho if you've still got this repository hand I'd love to poke at what the stash state was for this repository:

```
$ git stash list
$ git show stash@{0} // swap 0 for the entry that you think Desktop is using
```

This might help us understand why an empty stash was created in the app...

**Comment by tierninho** [comment]
Unfortunately, the repo has been altered by now, but I will try to reproduce it.

**Comment by tierninho** [comment]
@shiftkey I identified the bug. Adding a directory to a new repo and attempting to stash it will do it.

Steps:
- Add new repo
- Open it in finder
- Drag some other repo directories into that above directory
- Attempt to stash, switch branches again, stash, etc..

Nothing is the logs. 2.0.3, mac.

**Comment by iAmWillShepherd** [comment]
I was unable to reproduce this, @tierninho. Here are the steps I took: [YouTube](https://youtu.be/oyAT7Wfre-k).

**Comment by tierninho** [comment]
@iAmWillShepherd For step 3, when you open the repo in Finder, try taking two other existing repo folders and at the same time dump them into the new repo. That should do it.

![Screen Shot 2019-06-14 at 8 49 52 AM](https://user-images.githubusercontent.com/14828183/59531358-74063500-8e81-11e9-907d-ccfb1d72052b.png)

**Comment by tierninho** [comment]
This also affects submodules as they cannot be stashed.
![Screen Shot 2019-06-17 at 10 30 58 AM](https://user-images.githubusercontent.com/14828183/59634826-5b995300-90eb-11e9-820b-9c3a78a87f0b.png)

**Comment by tierninho** [comment]
Another viewpoint for this bug. Notice the `0` changes in the next step.

![Screen Shot 2019-06-28 at 11 53 59 AM](https://user-images.githubusercontent.com/14828183/60373327-79906e80-999b-11e9-9066-cdeb5e61cf4c.png)

**Comment by billygriffin** [comment]
I'd also like to let this one come up organically before we prioritize any work to fix it.
