### ISSUE TITLE
Cyrillic is not displayed correctly in the commit preview

### ISSUE THREAD

**Issue by gmikhail** [desktop/desktop#7731]
## Description

![1](https://user-images.githubusercontent.com/4838367/59143869-35cbca00-89d8-11e9-8e06-ec5076e8cfca.png)

## Version

* GitHub Desktop: 2.0.3

* Operating system: Win10 x64 1809

## Steps to Reproduce

1. `Add the file with cyrillic text and Windows-1251 encoding`
2. `See the commit preview`

### Expected Behavior

Привет мир (Hello World)

### Actual Behavior

������ ��� (Hello World)

**Comment by shiftkey** [comment]
@gmikhail thanks for the report.

I feel like this is related to #3923. Before I close this and cross-reference that issue, are you able to provide an example repository that illustrates the issue, so we can reproduce the issue and verify your problem has been resolved in the future?

**Comment by shiftkey** [comment]
@gmikhail I'm going to close this out to prevent duplicate issues from overwhelming us, but if you have a sample repository which illustrates the issue I'd love to add it #3923 to verify we can resolve this for your use case.
