### ISSUE TITLE
github desktop doesn't read to korean 

### ISSUE THREAD

**Issue by sk74575** [desktop/desktop#7733]
when i was write to korean it doen't work i think my program problem app wasn't use utf-8  so help me

**Comment by shiftkey** [comment]
@sk74575 thanks for the report.

I feel like this is related to #3923. Before I close this and cross-reference that issue, are you able to provide an example repository that illustrates the issue, so we can reproduce the issue and verify your problem has been resolved in the future?

**Comment by shiftkey** [comment]
@sk74575 I'm going to close this out to prevent duplicate issues from overwhelming us, but if you have a sample repository which illustrates the issue I'd love to add it #3923 to verify we can resolve this for your use case.
