### ISSUE TITLE
Hitting Enter doesn't create a new branch when typing its name

### ISSUE THREAD

**Issue by tooomm** [desktop/desktop#7735]
**Please describe the problem you think should be solved**

Example:

> “When I try to create a new branch and type it's name, hitting <kbd>Enter</kbd> doesn't create the branch. I have to manually hit a button.”

**Do you have any potential solutions in mind?**
Enter should trigger the `New branch`/`Create new branch` button.

**Comment by shiftkey** [comment]
@tooomm it looks like we have the same issue created twice, so I'm going to close this out in favour of the earlier issue #7734
