### ISSUE TITLE
I have 50 projects not in Github Desktop

### ISSUE THREAD

**Issue by karl-ravn** [desktop/desktop#7737]
When you have a lot of projects that you use occasionally and just installed Github Desktop, it's a pain to sit and add the projects one by one.

Looking at your competitor SourceTree, they have a "Scan directory" which finds _all_ git-projects and adds them. This is very convenient and must be a super simple feature to add since it's just a directory traversal and adding anything in there in case it's not already present in your list.

**Comment by shiftkey** [comment]
@karl-ravn thanks for the suggestion!

We had an earlier discussion about this in #1574 and I'll add your comment there. There's another workaround for this in the meantime: you can drag-and-drop multiple repositories into the app (which skips the dialog you see when you just add one).

**Comment by rkrug** [comment]
@karl-ravn you say that I can drag-and-drop the repositories into the app - but this does not help in finding them. Is there a simple way of getting (in e.g. search in the finder in macOS), a list of all repos I have? Trying to search for them by hand (they are in many different places) is really hard.

**Comment by rkrug** [comment]
Ha - Scan in SourceTree, dd all to Source Tree, drag-and-drop all found repos into the github app. And wait.
