### ISSUE TITLE
Ignored file isn't ignored, even when in .gitignore

### ISSUE THREAD

**Issue by JasonBock** [desktop/desktop#7745]
## Description
A repo I just created, a file is somehow being tracked for changes, even though I've set up my .gitignore to ignore both the directory it sits in, and the file itself.

## Version
* GitHub Desktop: 2.0.3
* Operating system: Microsoft Windows [Version 10.0.17763.316]

## Steps to Reproduce
Make changes in my project in VS. The .suo file will eventually change.

### Expected Behavior
It's not picked up as a change in GitHub Desktop

### Actual Behavior
The file is added to the repo and tracked for changes, even though my .gitignore says it shouldn't.

## Additional Information
![image](https://user-images.githubusercontent.com/904213/59192957-12c52580-8b52-11e9-80bd-e8bbb968f2df.png)

**Comment by shiftkey** [comment]
@JasonBock thanks for the report.

Can you confirm the file is previously tracked in Git (i.e. you can do a `git log -- [path]` and see it was added in a previous commit)?

**Comment by tierninho** [comment]
@JasonBock As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by shiftkey** [comment]
I also believe we are already tracking this in https://github.com/desktop/desktop/issues/2537#issuecomment-324494447, if my suspicions are correct
