### ISSUE TITLE
Stash conflict resolution

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#7748]
Sometimes restoring a stash can result in conflicts. We already have conflict resolution implemented for merge and rebase workflows, so we should include stashing for consistency.

Also worth pointing out that implementing full conflict resolution will prevent issues like https://github.com/desktop/desktop/issues/7738.

**Comment by shiftkey** [comment]
I did some digging about how Git surfaces conflicts generally in https://github.com/desktop/desktop/issues/7831#issuecomment-503534419, which should be helpful here.

**Comment by billygriffin** [comment]
I'm going to close this because we haven't seen it as a problem and it's now been shipped for quite some time. Happy to revisit if we see it come up frequently enough to warrant prioritizing.

**Comment by miqrogroove** [comment]
Using the GUI to bring changes from a master branch to a PR fork branch causes all kinds of problems like this.  Attempting restore throws error: "needs merge. The stash entry is kept in case you need it again. error: could not write index"
