### ISSUE TITLE
More granular labels based on supported workflows

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#7749]
## Problem
The current labels
* _bug_
* _enhancement_
* _performance_
*  _tech-debt_ 

are vague and don't do a great job of informing me what workflow/feature the issue or PR is addressing.

At one point, I started using the issue/PR title as a way to inform future Will and others what feature area an issue or PR was addressing.
Later on, @shiftkey added _epic_ labels that we're meant to track longer-term work for a specific feature.

### Similar label granularity problem
We decided some time ago that having a single bug label was not sufficient for our needs, so we made sub-labels that we could apply to issues. This change made it easier to quickly prioritize what bugs we needed to fix and helped move the team from working on the newest bug report to working on a bug that would have the greatest impact.

## Proposal
We should use a more granular label system for issues and PRs that are aligned with the workflows Desktop supports.

I think we should categorize issues and PRs based on workflow for a couple of reasons:

* To align how we organize our work with our ideas of who Desktop is intended for ([What is Desktop](https://github.com/desktop/desktop/blob/development/docs/process/what-is-desktop.md#1-github-desktop-reduces-frustration-and-makes-git-and-github-workflows-more-approachable)).
* Workflows do a better job of capturing how an issue or PR fits into the big picture than just `enhancement` or `bug`, which should make it easier to make informed guesses on how much risk is involved in the proposed change.

Here's some of the labels I'm thinking we could add:
* Commit
* Rebase
* Merge
* Conflict Resolution
* Uncommitted changes
* Branch switching

These labels could then be mixed and matched to better categorize an issue.

For example, if we have a PR that adds stash conflict resolution flow, we could tag it with _Enhancement_, _Uncommitted changes_, and _Conflict resolution_ to indicate what workflow the PR enhances.

**Comment by iAmWillShepherd** [comment]
An example of where this will come in handy is https://github.com/desktop/desktop/issues/7748.

I feel that `enhancement` is vague. I'd like to also label it with `conflict resolution` and `stashing`/`uncommitted changes`.

**Comment by tierninho** [comment]
I am in support of this. I liked the epic labeling we did, and this seems to be along the same lines. 👍

**Comment by outofambit** [comment]
I also think something like this would be nice. I'm sure it won't be perfect, but it would be helpful to have a quick way to see all the issues related to "branch pruning" or the "lib/git layer" or "authentication problems" or...

**Comment by tierninho** [comment]
suggestion: add a `product-input-needed` label?

**Comment by billygriffin** [comment]
We're doing this for feature-level things, and we may do something along these lines down the road, but since we've been grouping things in a variety of different ways (tracking issues, labels, etc.), I'm not sure this issue needs to stay open. Thanks!
