### ISSUE TITLE
Maximized window won't "restore down" after restarting application

### ISSUE THREAD

**Issue by jo3bingham** [desktop/desktop#7750]
## Description

The maximize button in the top-right corner of the window does nothing if the application is ran maximized.

## Version

* GitHub Desktop: 2.0.3

* Operating system: Microsoft Windows [Version 10.0.17763.437]

## Steps to Reproduce

1. Run GitHub Desktop.
2. Maximize the window.
3. Close GitHub Desktop.
4. Run GitHub Desktop.
5. Try to use the maximize button in the top-right corner of the window.
### Expected Behavior

The maximize button should actually be the "restore down" button as the window is already maximized.
### Actual Behavior

Nothing. When you click the maximize button it doesn't maximize the window (because it's already maximized), nor does it do anything else or change to the "restore down" button. The only way to get the window un-maximized is to drag the title bar away from the top of the screen or press Windows+Left/Right/Down (any direction other than up) on  your keyboard.

## Additional Information

If this can't be reproduced, I'd be happy to make a gif showing it happening in GitHub Desktop but no other application.
### Logs

[2019-06-10.desktop.production.log](https://github.com/desktop/desktop/files/3272785/2019-06-10.desktop.production.log)

**Comment by shiftkey** [comment]
@jo3bingham thanks for reporting this! We'll see if we can reproduce the behaviour on our side, and if not we'll be in touch for assistance...

**Comment by tierninho** [comment]
@jo3bingham I successfully reproduced the issue. The maximize toggle is indeed unresponsive. The restore down option should be available as soon as you maximize the window.

As a work around, I minimized the application, the open it again to make it "unstuck".

**Comment by mslonely1978** [comment]
Hi
