### ISSUE TITLE
Stash conflict warning

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#7751]
Restoring a stash can result in conflicts if the branch it is being applied on has moved ahead of the stash commit. This can be a frustrating experience since a conflict is likely not what someone expects to happen when restoring their commit. Desktop should instead warn the user that a conflict will occur if they stash is restored to set expectations.

**Comment by ADustyOldMuffin** [comment]
If this is going to be open to the community I'd like to look at working on this.

**Comment by billygriffin** [comment]
I'm going to close this because we haven't seen it as a problem and it's now been shipped for quite some time. Happy to revisit if we see it come up frequently enough to warrant prioritizing.
