### ISSUE TITLE
White Window After Running The Program

### ISSUE THREAD

**Issue by OzanKurt** [desktop/desktop#7752]
After I updated it, I started the program. It looks okay for just 1 second and then turns into a white window.

![image](https://user-images.githubusercontent.com/8682003/59214305-25257a80-8bb7-11e9-991e-34c6d6893ffa.png)

I literally do nothing else, tried re-installing it. Did not work. I am also not able to download a legacy version, which is clearly more stable.

**Comment by shiftkey** [comment]
@OzanKurt thanks for the report!

Could you attach the full log files? The details are documented here about how to find them outside the app: https://github.com/desktop/desktop/blob/development/docs/installation.md#log-files

This will help us understand what is happening behind the scenes, and identify what version of the app you are using...

**Comment by OzanKurt** [comment]
Sadly I can't replicate the problem again.

I deleted the app and installed the beta version by appending `env=beta` to the query string. Then the install deleted all my settings and existing repo configurations. I now have a working and empty app.

**Comment by OzanKurt** [comment]
I will surely include log files if this thing occurs again.
