### ISSUE TITLE
Install failing on Gathering required information when installing from MSI

### ISSUE THREAD

**Issue by ChildishGiant** [desktop/desktop#7753]
## Description
When attempting to install the installer always crashes on the "Gathering required information" step whenever I try to install from the MSI.

## Version
* GitHub Desktop: Attempting to install 2.0.3 
* Operating system: Microsoft Windows [Version 10.0.17134.472]

## Steps to Reproduce
For me this happens every time I try to install from the MSI. No problems with the exe so that's a workaround.

## Additional Information
[Video of issue](https://www.youtube.com/watch?v=qAM0AZGeFT4)
I couldn't use OBS or other screen capture software since there's the authentication screen.

### Logs
`%APPDATA%\GitHub Desktop\` hasn't even been created yet so there's no log available. If I run the MSI from PowerShell it seems to detach without an error so no log there either.

**Comment by steveward** [comment]
@ChildishGiant thanks for the report!

To get some more information about why the installation is failing it would be helpful if you could send over the log file that the Squirrel installer generates. Since no log file is being generated in `%LocalAppData%` you should be able to find one in the `SquirrelTemp` directory:

`%LocalAppData%\SquirrelTemp\SquirrelSetup.log`

Please upload that as an attachment.

**Comment by ChildishGiant** [comment]
[SquirrelSetup.log](https://github.com/desktop/desktop/files/3278181/SquirrelSetup.log)

**Comment by tierninho** [comment]
@ChildishGiant It appears you are on a 32-bit operating system based on the `at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)` spotted in the logs. Is this correct? 

Desktop only supports 64-bit.

**Comment by ChildishGiant** [comment]
No, I'm on Windows 10 64bit

Windows 10 Pro 64-bit (10.0, Build 17134) (17134.rs4_release.180410-1804)

**Comment by tierninho** [comment]
Based on other issues that came in with similar problems, here are some suggestions:
- Ensure there are no leftover GitHubDesktop.exe processes running
- Are you running any antivirus/security software on this machine that could be blocking the installation of GitHub Desktop?

Apologies for not having a direct solution for this. @steveward does anything stick out for you in the logs or video?

**Comment by ChildishGiant** [comment]
I've tried installing again from the same file and this time it's worked. 🤔 So I uninstalled the program as it was previously installed with the MS, wiped all trace of it from AppData and tried again. The exe worked. I guess this must be some extremely fringe case with my setup?

**Comment by tierninho** [comment]
@ChildishGiant Great! Glad it is resolved. 

Hard to tell what happened exactly but sometimes it just takes a fresh install to get things back up and running. Closing the issue ⚡️

**Comment by ChildishGiant** [comment]
I've since reinstalled windows and was trying to reinstall with the MSI and the same thing's happening. Here's my Squirrellog again. 
[SquirrelSetup.log](https://github.com/desktop/desktop/files/3527370/SquirrelSetup.log)

```
OS: Microsoft Windows 10 Pro 64-bit
Kernel: 10.0.18362
Uptime: 2d 12h 50m 9s
Motherboard: ASRock AB350 Pro4
Shell: PowerShell 5.1.18362.145
Resolution: 1920 x 1080  1280 x 1024
Window Manager: DWM
Font: Segoe UI
CPU: AMD Ryzen 5 1600X Six-Core Processor
GPU Radeon (TM) RX 480 Graphics
RAM: 8218MB / 16316 MB (50%)
Disk C: 65GB / 112GB (58%)
Disk D: 843GB / 932GB (90%)
Disk E: 367GB / 466GB (79%)
Disk G: 0GB / 0GB (79%)
```
