### ISSUE TITLE
Indication that branch has associated stash

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#7755]
At the moment, the only way to find out if a branch has an associated stash is to check that branch out.  Providing branch stash information in the branches list will reduce the number of steps required to determine if a branch has an associated stash.

For now, I think we can use the _notification dot_ pattern we use elsewhere in the app to lead the user to the action that should be completed.

![Screen Shot 2019-06-10 at 3 10 30 PM](https://user-images.githubusercontent.com/1715082/59224135-43797f00-8b93-11e9-9f4d-1fb04bc22e42.png)

Once the branch with the notification dot is clicked, the dot could appear next to the action that would complete the workflow.

![Screen Shot 2019-06-10 at 3 10 42 PM](https://user-images.githubusercontent.com/1715082/59224186-6b68e280-8b93-11e9-9335-77eea3ae70a3.png)

cc/ @desktop/design @desktop/product

**Comment by billygriffin** [comment]
I agree that the problem exists, but I'm not sure I like the dot as a solution, as the dot indicates otherwise that a repo has changes in progress and not yet committed, and I think it could be confusing for the same icon to be used for different concepts. Since we have an icon next to "Stashed changes" in the UI already, we could make use of that in some respect, or some other mechanism. I'd love to hear from @desktop/design on this though.

**Comment by outofambit** [comment]
> Since we have an icon next to "Stashed changes" in the UI already, we could make use of that in some respect

💯 yeah this would be my vote!

i think this is a worthwhile thing to tackle, too!

**Comment by iAmWillShepherd** [comment]
I'm not married to having a dot as a notifier. The dot has had several meanings in the past. An example is the current branch being behind the remote (notification of divergent branches). So I don't fully agree that reusing a dot is confusing, but my view on these dots have always bean along the lines of "hey, something has changed and we suggest you take a look", not that a repo has changes in progress and not yet committed.

It seems we are in agreement on the actual problem and the need for some design input, so I'm good 👍

**Comment by donokuda** [comment]
Thinking through this a little more, maybe an iteration we can try is grouping branches with stashes under a section:

<img src="https://user-images.githubusercontent.com/1174461/59389541-689cf780-8d23-11e9-9e22-43e7e746b832.png" width="290" />

If the grouping isn't enough, then there might be something we can visually do to differentiate them from the rest of the list:

![image](https://user-images.githubusercontent.com/1174461/59389823-40fa5f00-8d24-11e9-8e42-d27514a8915a.png)

**Comment by iAmWillShepherd** [comment]
@donokuda 

I like that! I think the files changed is a nice touch. I'd lean towards the mockup on the left since it states how many files have changed. I worry that the mockup on the right doesn't contain enough context for the user to know what those numbers mean.

What do y'all think, @billygriffin @ampinsk ?

**Comment by tierninho** [comment]
Might as well toss in another category from a previous `future-proposal` for "branches with pull requests" https://github.com/desktop/desktop/issues/3520

**Comment by billygriffin** [comment]
Adding onto @tierninho's comment above, I'm not sure we should look at this in isolation. I can think of five primarily things about branches that would be helpful to know at a glance (maybe more I'm not thinking of).

1. When was the last time someone committed to this branch?
2. Is there uncommitted work on this branch?
3. Has this branch not been published to the remote?
4. Is there a stash on this branch?
5. Is there an open PR on this branch?

I guess my question becomes how we convey that context in a way that makes it obvious the state of the branch, and whether all of that is necessary or just some of it (and priority). Thoughts?

**Comment by outofambit** [comment]
+1 to @billygriffin and @tierninho 's point that this should be looked at holistically. i don't think there's an urgent need to push this change out without spending more time thinking about the larger problem and context.

**Comment by tierninho** [comment]
| Branch feature        | On Desktop app     |  Under Branches tab   |
| ------------- |:-------------:|:-----:|
| Name      | ✅  |     ✅	|
| Date created     | ✅        |  ✅  |
| Default / Active / Stale | ✅       |  ✅  |
| Protected    | ✅     | ❌ |
| Commits before/after default branch    | ✅    | ❌ |
| Pull Requests + CI    | ✅   | ✅   |
| Creator    |  ❌    | ❌ |
| Contributors    |  ❌    | ❌ |
| Last updated     |  ❌    | ❌ |
| Uncommitted work    |  ❌    | ❌ |
| Local / remote    |  ❌    | ❌ |

When looking at Github.com, these are the features of a branch that one can view. While we do not need to mirror Github.com, we do have the opportunity to include some of this data to further enhance our branches tab.

**Comment by outofambit** [comment]
I also want to cross-reference this with https://github.com/desktop/desktop/issues/5155 (revisiting the recent branches list) as I think that would be worth considering as part of this work.

**Comment by billygriffin** [comment]
I'm going to close this issue in favor of #8048. Thanks @tierninho!
