### ISSUE TITLE
Select all changes with Ctrl + A

### ISSUE THREAD

**Issue by Seb33300** [desktop/desktop#7759]
After applying focus on a file in the left `Changes` tab, `ctrl + a` command will not select all changed files but the current file path.

This is very frustrating since the `Discard All changes` context menu has been removed the easiest alternative I had found is to select all files to discard them.
But the only way to select all files is to select the first item, press `shift` and click on the last item.

Could you please fix it unless it is an expected behavior?

Thanks

**Comment by billygriffin** [comment]
@Seb33300 Thanks for the issue! We were able to reproduce this, and it's definitely a bug that seems to only exist on Windows. We're looking at this in tandem with #7696, and expect to ship at least an iteration on that one soon. Thanks again for bringing this to our attention.

**Comment by billygriffin** [comment]
Hi @Seb33300, this should be working properly now with today's release, in addition to the Discard all changes context menu from #7696. Please let us know if that's not the case, and thank you so much again for the feedback here!

**Comment by Seb33300** [comment]
Working 👍
