### ISSUE TITLE
pulling error

### ISSUE THREAD

**Issue by zhoubingithub** [desktop/desktop#7760]
fatal: unable to access 'https://github.com/zhoubingithub/c-workerspace.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092013); Before today，the desktop was ok;how can i do to reselve this problem?

**Comment by shiftkey** [comment]
@zhoubingithub thanks for the report!

It looks like this is an issue with Git not being able to check the certificate revocation list on the user's machine, and it falls back to throwing an error.

We have a writeup about how to opt-out of this behaviour in our [Known Issues document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#certificate-revocation-check-fails---3326) - please check it out!
