### ISSUE TITLE
unable upload

### ISSUE THREAD

**Issue by Alvins-zya** [desktop/desktop#7764]
![image](https://user-images.githubusercontent.com/48586279/59264206-2d43ef80-8c75-11e9-9de8-d588b1f850db.png)

**Comment by shiftkey** [comment]
@zhoubingithub thanks for the report!

It looks like this is an issue with Git not being able to check the certificate revocation list on the user's machine, and it falls back to throwing an error.

We have a writeup about how to opt-out of this behaviour in our [Known Issues document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#certificate-revocation-check-fails---3326) - please check it out!
