### ISSUE TITLE
slow and stuck 2.0.3

### ISSUE THREAD

**Issue by jyxjjj** [desktop/desktop#7768]
When i updated to 2.0.3.
On Windows 10 1803 17134.765 enterprise ver.
It becomes very slow.
I forgot which ver i used before, may 1.6.6.
I didn't update manually, it automatically deleted old desktop shortcut and create a new one.
What problem i met?
What can i do?

**Comment by jyxjjj** [comment]
As #7540 said. I stopped QQPCMgr & it will not slow anymore, i restarted QQPCMgr and desktop works currectlly as usual, but when i restarted my computer, it will also slow down. To restart QQPCMgr will fix.
BUT! Must i do this every time? Why other applications will not be slow? Including VSCODE works currentlly.
& This problem they(said #7540) from 1.6.6, but i from 2.0.3.

**Comment by billygriffin** [comment]
Hi @jyxjjj, sorry about that! Are you using GitHub Enterprise, by chance? I'm wondering whether this is the same as https://github.com/desktop/desktop/issues/7713?

**Comment by jyxjjj** [comment]
@billygriffin No, It was my personal account and a private repo.

**Comment by shiftkey** [comment]
@jyxjjj there was this extra comment in #7540 that might help:

> (Based on QQPCMgr)
> 
> Someone from the forum of QQPCMgr reached to me right after I posted the report. (Thumb up)
> 
> After some testing, it came out that one feature called _process protection_ was the main cause.
> 
> You could find it here and switch it off for temporary use or simply quit the application.
> ![screenshot](https://user-images.githubusercontent.com/13071103/57965323-5ecae300-7975-11e9-897b-fd879b431f12.png)
> 
> They are looking into it, and it may take a while before the solution come out.

**Comment by jyxjjj** [comment]
@shiftkey 
I know & i add the desktop installation folder to QQPCMgr's whitelist.
It may not slow as before.
But i want to help fix instead of escape this problem.

**Comment by shiftkey** [comment]
> But i want to help fix instead of escape this problem.

@jyxjjj unfortunately we don't have much control over what QQPCMgr is doing currently, so all we can offer is mitigations until they've organized for an update - maybe the update is out by now?

**Comment by jyxjjj** [comment]
@shiftkey Ok, Thanks. But they have no updates available now.
