### ISSUE TITLE
Filtering the github account list shouldn't filter the repos as well

### ISSUE THREAD

**Issue by photonstorm** [desktop/desktop#7769]
I have hundreds of repositories set-up and they used to be all nice and alphabetical until a recent update, and now they're all grouped by the GitHub username the repository belongs to. This is a bit frustrating because my most commonly used username is right near the bottom of the list.

However, I can use the Filter at the top to make sure it only shows my GitHub username, but when I do that, all of the repositories that were previously nicely listed in alphabetical order end-up in some strange order instead. It's definitely not alphabetical, or 'last-used', so I'm really not sure what it is, and it appears to change too.

This leaves me with two choices: I either don't use the Filter and have to scroll and scroll to get to the repos I want. Or, I use the filter, which cuts the quantity down, but then have to visually scan every one of them figuring out where in the list the repo I actually wanted has gone this time. Neither are much fun :(

I'm aware there is a 'Recent' list at the top, too, but it's not a long enough list for me and the criteria for what goes up there seems vague (I think it's just the 3 most recently accessed repos? but I use far more than this for my projects).

What would be perfect would be the ability to favorite a username and/or repos and have them appear at the very top of the list in a 'Favorites' section (I don't care if this completely replaces 'Recent' tbh). Or on a similar concept: the ability to drag and drop usernames into your own defined list. Or, at the very least, if you use the Filter, don't have it filter repos below the a username _as well_, just have it filter the usernames, because as far as I can tell, if you put in the full github username as the filter text, every repo under that username will be listed, but in a random order. Maybe the Filter could be smart enough to tell that you've put a username in there and then not sort the repos under it?

**Comment by outofambit** [comment]
Hi @photonstorm thank you for filing this issue and my apologies for the delayed response.

There have been a few similar issues filed around the filtering + grouping behavior in the repo list and I certainly agree there are improvements we can make here. I'm going to write up a summary issue to use for tracking this problem. (and will link it back to this issue, and close this). Thank you again!
