### ISSUE TITLE
GitHub will not accept Azure DevOps standard authentication

### ISSUE THREAD

**Issue by Joebeazelman** [desktop/desktop#7772]
GitHub will not accept the standard from Azure DevOps, but it will only accept the token authentication. As soon as you clone the repository, it asks for a user name and password. I repeatedly entered my credentials stored Azure DevOps hoping I may have typed it in wrong.  After Googling around, I finally discovered that I had to use a personal access token.  The name of the token becomes the username, while the password becomes the token.

Why can't you guys get something as simple as usability right? It would have made things a lot easier if you had added Azure DevOps as one of the supported accounts.

At the very least, would it take too much of your playground time to at least modify the text labels to something like username/Access Token Name and Password/Token?  Aren't you guys supposed to be uber developers who passed all the whiteboard interview questions? 

Perhaps it is too much to ask from a company founded on Git, a terrible piece of software written by a socially maladjusted person who lived with his parents until full adulthood. You guys made a name for yourselves based on mediocrity. Microsoft added to their portfolio of mediocrity by acquiring you guys!

**Comment by tierninho** [comment]
@Joebeazelman We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

**Comment by Joebeazelman** [comment]
Well, that's OK.  Stay buggy!   In fact, I just realized that by being buggy, software will never be good enough to put people out of work which is a good thing.

**Comment by Joebeazelman** [comment]
Well, that's OK.  Stay buggy!   In fact, I just realized that by being buggy, software will never be good enough to put people out of work which is a good thing.
