### ISSUE TITLE
Discard all changes button is gone

### ISSUE THREAD

**Issue by dave90dave** [desktop/desktop#7775]
## Description
See expected behaviour

## Version
???
* GitHub Desktop:

* Operating system:
Windows 10

## Steps to Reproduce
Click on changes in git desktop for windows with right mouse button, the discard all button is gone, and I am not planning to remove 4000 files one at a time ;-)

### Expected Behavior

a discard all button to show up

### Actual Behavior

it doesnt show the discard all button when I right click my changes.

**Comment by shiftkey** [comment]
@dave90dave thanks for the feedback! 

This was a change we decided to make in #7394 to address some UX concerns about "Discard All Changes". We had a discussion about this in #7696, and based on that we'll be restoring this with 2.0.4 which will be published today.

**Comment by dave90dave** [comment]
Nice, thank you for your time @shiftkey!
