### ISSUE TITLE
Keep previous selected value as default

### ISSUE THREAD

**Issue by Seb33300** [desktop/desktop#7776]
Hello,

This is not a bug but an improvement.

When a choice is given to us, for example:
- when clicking on `New branch` button => choice between `master` or `current branch`
- when changing branch =>choice between `stash changes` or `keep changes`

In both case, the actual default value is not what I am expecting and this give me more clicks to do.

A solution could be to keep the previous selected value as the default value for the next time.

What do you think?

**Comment by tierninho** [comment]
@Seb33300 Thank you for the suggestion. 

I think looking at our metrics for this can help guide us should we opt to change this. As you are the first to bring this up, we must ascertain if this is a larger problem for the community before electing to change it. As stashing is a new feature, this may take some time to gather feedback and data.

Overall an interesting idea and we appreciate you reaching out!

**Comment by billygriffin** [comment]
Hi @Seb33300! We've been considering and discussing this internally, and our metrics are showing that there's quite a bit of variation between a good chunk of people's choices. In other words, a large group of people are choosing to bring changes one time, and then stash the next time, etc, and frequently switch back and forth. I was initially also attracted to the idea of remembering your previous choice, but given what we're seeing I think that would add more confusion than allowing people to just have muscle memory and know where each option is going to be. Therefore, I'm going to close this issue, and we really appreciate you floating the idea.

**Comment by cabello** [comment]
Hello 👋 I ❤️ Github desktop!

I would like to suggest an option in preferences to mark one of these options as my default setting and never ask me again, the suggestion is put it under "Advanced", similar to the following:

![Screen Shot 2019-07-25 at 7 51 11 PM](https://user-images.githubusercontent.com/60936/61916208-a2157500-af15-11e9-9cf2-de0fe20adf0c.png)

I personally **always** start doing changes in master before creating a new branch and this popup is quite disruptive for my workflow.

Thanks again for making such awesome app. 🙏

**Comment by billygriffin** [comment]
Hi @cabello, thanks for the response and describing your workflow so well! Would your desire then to just disable this altogether, a la #7746 so it just defaults to the underlying Git behavior of always bringing changes to the new branch? We're generally very hesitant to create toggles for everything and only try to do so when there's significant subset of users who do things a different way or have a divergent preference where the current state creates significant pain.

Feel free to weigh in on that issue if so, as we're collecting feedback as we evaluate how widespread that is.
