### ISSUE TITLE
Application crash Ubuntu 19.04

### ISSUE THREAD

**Issue by CobbsLab** [desktop/desktop#7777]
## Description
When I try to add an existing repository or clone one from github the application crash

## Version
* GitHub Desktop: 2.0.3-linux1
* Operating system: Ubuntu 19.04

## Steps to Reproduce
1. Launch
2. Sign in
3. Configure Git
4. Press "Finish"
5. Press "Add an Existing Repository ..." 
6. Press "Choose"

### Logs
github-desktop[30704]: segfault at 0 ip 00007fe68ebf0178 sp 00007fff892e7e78 error 6 in libc-2.29.so[7fe68eb5b000+173000]

**Comment by shiftkey** [comment]
@CobbsLab thanks for the report! I'm tracking this over in https://github.com/shiftkey/desktop/issues/142
