### ISSUE TITLE
enable --recurse-submodules support for production release

### ISSUE THREAD

**Issue by gilbdev** [desktop/desktop#7787]
## Description
when i switch between 2 branches with a submodule that is synced to a different commit in that submodule, i instantly get a diff on the submodule folder, as it doesn't update to the correct commit.
(this is a bit different from #4579,where the submodule is on a different submodule branch)

## Version

* GitHub Desktop: 2.0.4

* Operating system: WIndows 10

## Steps to Reproduce

- In a repo called repo, with branches foo and bar, add a submodule sub
- set active branch to foo
- in sub, add some commit and push
- in branch foo, update the submodule a,d commit/push the submodule folder to be synced to the latest commit in the submodule
somme diff like that : 
`-Subproject commit 895c408b9c58703ebdab2748193678f574baa877
+Subproject commit f3a9a816629a96539fc45e84290c4531bc9b45f3`
- now, switch to branch bar

=> you'll get an instant diff on the submodule folder that is the exact opposite of diff above (despite you chagned branch, the submodule did not sync to the commit that correspond to branch bar, but stays at the latest commit from branch foo)

### Expected Behavior
when switching branch, submodule should sync to the commit taht correspond in that branch

### Note
doing the checkout in command line does behave as expected
`git checkout bar --recurse-submodules`

**Comment by shiftkey** [comment]
@gilbdev thanks for the report!

We've been testing `--recurse-submodules` on beta for a few versions to ensure it's working as expected - see https://github.com/desktop/desktop/pull/5154 for more details about what's supported.

Are you able to try out [our beta channel](https://github.com/desktop/desktop#beta-channel) and confirm this addresses your issue? I think we're close to promoting this to our production channel, but getting feedback to verify we're close would be great!

**Comment by gilbdev** [comment]
just tested the beta, and yeah it's working as expected :)
thought that a closed issue in jul. 2018 would have been integrated in current release ;)

will stay on beta now ^^.

**Comment by shiftkey** [comment]
> thought that a closed issue in jul. 2018 would have been integrated in current release ;)

@gilbdev that's a valid point. I'll update this issue to be about shipping this to production, which we'll use as part of our future planning.

**Comment by gilbdev** [comment]
@shiftkey 
it seems that when using the "merge" feature from githhub desktop, the submodule commit gets not correctly update.

- pull a new commit from submodule
- push that in the parent repo
- change to another branch of the parent repo
- click on 'History', select the branch where you pushed to compare with
- click on 'merge into yourcurrentbranch'
=> observe that you got a change on the submodule folder that has not been updated to the new commit

probably some recurse submodule stuff missing for the 'merge' command

**Comment by shiftkey** [comment]
@gilbdev could you move this out to a bug report? I'd hate to lose that context buried in this thread as I think we need to investigate that one properly to understand what work is involved...

**Comment by chrisdcosta** [comment]
I've been testing in Github desktop Version 2.4.2-beta1 for MacOS and I believe this is not resolved when you compare with the submodule detached head on the command line. Please see my comments in #9547 [here](https://github.com/desktop/desktop/issues/9547#issuecomment-615934011)

**Comment by CreepyGnome** [comment]
I am confused if it's 2022 and we are on version 3.0.0 of the desktop client do we still need to be on the beta to get this functionality for a feature that was merged in 2018?  

3.0.0 has this issue still and I cannot find a way to "enable" it to use recurse submodules on pulls.  I assume this would be configurable however I cannot find any docs on this and the merged PR doesn't really explain how to enable it, which makes it seems like it's always enabled and just there.

Can someone help explain how to make this functionality work on a repository and if it requires the beta version still after almost 4 years?

**Comment by steveward** [comment]
This can be closed as this was merged into production in https://github.com/desktop/desktop/pull/15240.
