### ISSUE TITLE
After installing and uninstalling GH-desktop, can't checkout because of lfs

### ISSUE THREAD

**Issue by weitzhandler** [desktop/desktop#7788]
**Please describe the problem you think should be solved**
Hi,
I've installed the Windows desktop app, and after I checked it out for a bit I decided that it doesn't add the features I thought it will and that the web version would be enough, and so I uninstalled it.
After that, when trying to checkout a branch (`git checkout -f ^HEAD`), I'm getting the following output:

```
git-lfs filter-process: git-lfs: command not found
fatal: The remote end hung up unexpectedly
```

I tried to call `git lfs uninstall`, but then I get this message:
```
git: 'lfs' is not a git command. See 'git --help'
```

I believe, that during the installation of the desktop client, git was configured to use lfs. How can I disable it?

**Comment by iAmWillShepherd** [comment]
@weitzhandler 

Are you able to re-clone the repo? That may be the quickest work-around.

**Comment by weitzhandler** [comment]
Ok that's what I did. Luckily didn't have many of local changes so copy pasted those few.
You might wanna reopen the issue.
Repro is, create a clone in VS, install the app, open that repo on the app, go back to vs open it there.

**Comment by weitzhandler** [comment]
Reopening.
Can't get rid of the issue even after deleting the local repo.

**Comment by weitzhandler** [comment]
Ok found another workaround, installed [git-lfs](https://git-lfs.github.com/) manually, called `C:\Program Files\Git LFS\git-lfs uninstall`. Then uninstalled it. I'm keeping this issue open because really you should take care of it. The installation and uninstallation of Git Desktop took so much time of me. It shouldn't be like that.
Feel free to close tho.

**Comment by weitzhandler** [comment]
Yet another solution (because I'm still experiencing trouble):

Delete the `.git/hooks/pre-push` file in the troublesome repo.
