### ISSUE TITLE
GitHub Desktop makes macOS ask user for password before update

### ISSUE THREAD

**Issue by doekman** [desktop/desktop#7789]
It happend a couple of times now, but suddenly I get a security related popup (it's stating GitHub Desktop want to install a helper program) asking for permission: I need to enter my password here. 

Later, when checking on GitHub Desktop it's asking me to update my installation ("An updated version of GitHub Desktop is available and will be installed on next launch. See _what's new_ or _restart GitHub Desktop_.") 

I would expect the security related popup to happen **after** I click on "upgrade" application.

I forgot to capture a screenshot of the security popup. When I get a new one, I'll follow up this post.

**Comment by shiftkey** [comment]
@doekman thanks for the report! This feels like #3616, where this prompt is shown after update:

![](https://user-images.githubusercontent.com/3627664/34070927-e6451936-e23b-11e7-9252-19ac4c1d2fce.png)

Can you confirm this was what you saw?

I believe this is related to the security permissions set on the installed app when it tries to update. There's a simple way to check the permissions of the app:

> ```shell
> ~/ ls -l /Applications | grep "GitHub Desktop"
> drwxr-xr-x   3 shiftkey  staff   96 25 Jun 15:57 GitHub Desktop.app
> ```
> 
> If `root` owns this for some reason, or an account that you weren't expecting, you might need to `chown` it to change the ownership.

> To get the current owner:
> 
> ```
> $ whoami
> ```
> 
> The group should be `staff` unless your user directory manager changed it (more context [here](https://superuser.com/a/590691)).
> 
> I don't think you need to change the permissions from the defaults, but see the previous snippet for what mine is set to (note that `w` is only set for the owner).

I suspect there's some third-party tool which manages the machine and changes these permissions from the default (some people encountered this prompt after each update).

**Comment by doekman** [comment]
It's `root` indeed (sorry for keeping the Cocoa-version around 😉):

    $ ls -l /Applications | grep "GitHub Desktop"
    drwxr-xr-x   3 root    admin   96 22 mei  2017 GitHub Desktop Cocoa.app
    drwxr-xr-x   3 root    wheel   96 12 jun 17:08 GitHub Desktop.app

I think I performed a `brew cask install github`. So the "problem" could be there?

And should I do a `chown $(whoami):staff /Applications/GitHub\ Desktop`, and should I add the `-R` flag to chown?

**Comment by shiftkey** [comment]
> And should I do a `chown $(whoami):staff /Applications/GitHub\ Desktop`, and should I add the `-R` flag to chown?

This is probably a good idea, yes

**Comment by doekman** [comment]
Did it. It needed a `sudo` as well.

However, a `brew cask reinstall github` also fixed it (I hope).

**Comment by tierninho** [comment]
@doekman I hope you are in a good state now. If so, feel free to close the issue. 👍 😄
