### ISSUE TITLE
Use other git tools on GitHub Desktop

### ISSUE THREAD

**Issue by Melgaco** [desktop/desktop#7791]
**Please describe the problem you think should be solved**
It is not possible to add other git tools on remote without manual configuration

**[Optional] Do you have any potential solutions in mind?**
Add third tab on repository menu where we can add remote url from git tools

**Comment by shiftkey** [comment]
@Melgaco thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by Melgaco** [comment]
> @Melgaco thanks for reaching out!
> 
> We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.
> 
> I'm sorry. Updated! Thaks

**Comment by shiftkey** [comment]
@Melgaco thanks for the extra information!

> It is not possible to add other git tools on remote without manual configuration

Are you able to clarify what "git tools" represents here? When I think of "remote" I think this is asking about being able to add another remote to this list:

<img width="497" src="https://user-images.githubusercontent.com/359239/59439860-5f1b9a00-8dcc-11e9-8122-914e6c81651c.png">

But maybe I'm missing some context. Any extra details about what information you're interested in seeing and where it might live in the GitHub Desktop UI would be helpful here.

**Comment by Melgaco** [comment]
> @Melgaco thanks for the extra information!
> 
> > It is not possible to add other git tools on remote without manual configuration
> 
> Are you able to clarify what "git tools" represents here? When I think of "remote" I think this is asking about being able to add another remote repository URL to this view:
> 
> <img alt="" width="497" src="https://user-images.githubusercontent.com/359239/59439860-5f1b9a00-8dcc-11e9-8122-914e6c81651c.png">
> 
> But maybe I'm missing some context. Any extra details about what information you're interested in seeing and where it might live in the GitHub Desktop UI would be helpful here.

About "git tools" i would like to say services like github, bitbucket, bonobo and others.


When creating a repository and proceeding to the "REPOSITORY" menu in "REPOSITORY SETTINGS" displays image below
![GitHubDesktop](https://user-images.githubusercontent.com/15456747/59449819-41573080-8dde-11e9-9f12-aba2b618e1bd.png)

**Comment by shiftkey** [comment]
> About "git tools" i would like to say services like github, bitbucket, bonobo and others.

Aha! Connecting to other Git hosting services. Now I understand better!

@desktop/product do we have any tracking issues or summaries of what our current thoughts are about integrating with other Git hosts?

**Comment by billygriffin** [comment]
Hi @Melgaco, thanks for the issue!

GitHub Desktop does support using BitBucket, GitLab, Azure DevOps repos, and it's documented how to clone them here: https://github.com/desktop/desktop/tree/development/docs/integrations

While we intend to continue basic support for repos from other sources, our primary goal is for the GitHub <-> GitHub Desktop experience to shine. We don't intend to support publishing local repos to other hosts *from Desktop* in the near term, so I'm going to close this issue. Thanks again!
