### ISSUE TITLE
Can't log in to Github Desktop

### ISSUE THREAD

**Issue by kathep** [desktop/desktop#7792]
## Description

Downloaded new version of github desktop client for mac and I can't log in.

## Version

* GitHub Desktop: 2.0.3

* Operating system: OS High Sierra 10.13.5

### Expected Behavior
To be albe to log in on updated version of software

### Actual Behavior
Can't log in

https://www.dropbox.com/s/z179pc18kpa1o44/Screenshot%202019-06-12%2015.37.51.png?dl=0

https://www.dropbox.com/s/vwazkn9i2cso3te/Screenshot%202019-06-13%2007.56.04.png?dl=0

https://www.dropbox.com/s/l8tr35lwamytzta/Screenshot%202019-06-13%2007.56.13.png?dl=0

**Comment by shiftkey** [comment]
@kathep thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Finder** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by kathep** [comment]
2019-06-13T14:53:55.136Z - error: [ui] Error checking for updates
Error: Could not connect to the server.
2019-06-13T14:56:08.749Z - error: [ui] Error checking for updates
Error: Could not connect to the server.
2019-06-13T16:16:44.491Z - error: [ui] Error reporting opt out:
TypeError: Failed to fetch
2019-06-13T16:16:44.510Z - info: [ui] [AppStore] loading 0 repositories from store
2019-06-13T16:16:44.845Z - info: [ui] launching: 2.0.3 (Mac OS 10.13.5)
2019-06-13T16:16:44.846Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper.app/Contents/MacOS/GitHub Desktop Helper'
2019-06-13T16:16:44.858Z - error: [ui] Error checking for updates
Error: Could not connect to the server.

**Comment by shiftkey** [comment]
@kathep thanks for the log!

It looks like there's network issues with anything the app is trying to do. Is there any recent changes to the network that you're working on that might explain these errors?

**Comment by kathep** [comment]
Yeah, the university network I'm on (University of Victoria) has some weird permission issues. The strange thing is I was able to connect with the previous version of github desktop client on the same network two days ago.

**Comment by tierninho** [comment]
@kanishk98 Please try updating to 2.0.4 and try again.

**Comment by tierninho** [comment]
@kathep That was meant for you 😄

**Comment by kathep** [comment]
when I try to update I get this error: 

https://www.dropbox.com/s/vwazkn9i2cso3te/Screenshot%202019-06-13%2007.56.04.png?dl=0
https://www.dropbox.com/s/l8tr35lwamytzta/Screenshot%202019-06-13%2007.56.13.png?dl=0

**Comment by tierninho** [comment]
@kathep Possible to try another network at this point? Would be great to rule it out.

**Comment by tierninho** [comment]
@kathep As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you!
