### ISSUE TITLE
compatibility debian

### ISSUE THREAD

**Issue by RemDav** [desktop/desktop#7798]
Hello everybody,

I will can install this software on debian.
How do you do install this os ?

**Comment by tierninho** [comment]
@RemDav please have a read of the current documentation about our [Linux testing](https://github.com/desktop/desktop/blob/master/docs/contributing/linux-testing-and-you.md), which links off to where to find the release candidate installers.

After that, all you should need to do is something like this:

```
dpkg -i /path/to/deb/GitHubDesktop-linux-amd64-[version].deb
apt-get install -f
```

For any further issues or feedback, please open an issue over on this fork of Desktop: https://github.com/shiftkey/desktop.

**Comment by RemDav** [comment]
Thank you. I should install via snap.
