### ISSUE TITLE
Sometimes the description of the commit will not be emptied

### ISSUE THREAD

**Issue by kkocdko** [desktop/desktop#7801]
### Description
Sometimes the description of the commit will not be emptied.

### Version
* GitHub Desktop: `2.0.4`.
* Operating system: `Windows 10 1809`.

### Steps to Reproduce
1. Click `commit` button.
2. Switch to the `history` column **immediately**.
3. Wait until the commit is completed.
4. Cut back to the `changes` column, the description of the commit will not be cleared.
* [screen_recording.zip](https://github.com/desktop/desktop/files/3288935/screen_recording.zip)

### Expected Behavior
Clear the description input box after the commit is completed anyway.

**Comment by shiftkey** [comment]
@kkocdko thanks for the report. This is a very similar report to #4046, in particular this comment https://github.com/desktop/desktop/issues/4046#issuecomment-406566833, so I'm going to add your details to that issue and close this out to avoid tracking duplicates. Please follow along with that issue.
