### ISSUE TITLE
unable to scroll branch list in compare tab using keyboard

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#7802]
## Description

The compare tab should let you switch between the filter text and the list of filtered branches, but the keyboard navigation doesn't appear to work as expected currently.

## Version
* GitHub Desktop: 2.0.4
* Operating system: macOS and Windows

## Steps to Reproduce
1. Switch to the History tab for a repository
2. Use the <kbd>Tab</kbd> key to switch focus to the Branches list
3. Press <kbd>Down</kbd> to try and select a branch

### Expected Behavior
Keyboard moves to branches list, and user can scroll through the list of branches

### Actual Behavior
Filter textbox retains focus, and scrolling appears to be stuck at the top

### Additional information

@ADustyOldMuffin provided a GIF of the interaction in an earlier investigation of this area:

![](https://user-images.githubusercontent.com/41391321/58664476-528b4200-82f4-11e9-8d5f-0ec02a8d25b5.gif)

**Comment by ADustyOldMuffin** [comment]
:tada: I'd like to take this on please.
