### ISSUE TITLE
Cannot logout on front page

### ISSUE THREAD

**Issue by yvan-burrie** [desktop/desktop#7810]
**Logout ability on the front page is not available**
Not only does the newer version of Github Desktop install itself strangely in my personal folder, it does not even allow you to logout from the front page... no button! Did you guys do this to be part of the new annoying trend of UX that irritates those who are not [redacted]?

Screenshot: http://s000.tinyupload.com/index.php?file_id=05573514263730276820

Example:
> “When I open Github Desktop and I had previously logged in, then it brings me to the front page where all my repositories are listed... But what if I want to change account? Where on earth is the logout button!!! Do I have to clone my repository so that the menu finally shows? Only then can I finally go to File->Settings->Logout... But why not make things simple and logical?.. Just put a logout button on the front page so I don't have to clone a repo just for the sake of logging-out!!!!!!!!”

**Comment by shiftkey** [comment]
@yvan-burrie your comments are a violation of the Desktop Code of Conduct as they are insulting or derogatory. You may consider this an official warning.

As discussed earlier in #7374:

> this is intended behavior at least for now unless we hear that it's causing a lot of problems for people. I think your use case of logging into the wrong account and immediately wanting to log into a different account even prior to getting one repo set up in Desktop is unlikely to be widespread, so I'm going to close for now. But happy to reconsider if we see this come up more frequently.

For the moment we're not planning to re-evaluate this area, but if you have extra context about why you'd like to logout or switch accounts at this time feel free to add to this issue.

**Comment by yvan-burrie** [comment]
@shiftkey Who said "logging into the wrong account"? I have two accounts that I want to switch between and there's no logout button on the front page.

Man, you guys are so left-wing: "violation ... insulting or derogatory".

**Comment by yvan-burrie** [comment]
I spend almost 3 hours reinstalling GD over and over and over again, not mentioning, I went back to the archives to install older versions of GD.
