### ISSUE TITLE
"your tool of choice" should be a link in: app/src/ui/lib/conflicts/render-functions.tsx

### ISSUE THREAD

**Issue by tholden** [desktop/desktop#7820]
When there is a merge conflict, the dialog offers you the choice to "Open in command line, your tool of choice, or close to resolve manually."

"Open in command line" is a link. From the way the sentence is written, it sounds like "your tool of choice" ought to be a link as well, e.g. to the result of running "git mergetool".

I guess "your tool of choice" refers to the fact that you can open the conflicting files from the UI elements above, but it's really not clear in context. Plus, directly opening files is not really what you want to do when there's a merge conflict: you want to open a proper merge tool. At least with the default set-up, Atom is not a proper merge tool. It gives the option to accept one version or the other, but not the option to do a merge.

In any case a button for running "git mergetool" would be useful for non technical users (particularly if there was an API for setting the default merge tool).

**Comment by billygriffin** [comment]
Hi @tholden, thanks for the issue! "Tool of your choice" is intended to convey that if you don't use an editor-centric conflict resolution flow typically that you *can* open the file in a merge tool or something else that you typically use to resolve conflicts. From our research, our working theory is that most Desktop users use their editor to resolve conflicts and many of the conflict resolution tools built into editors have become very well liked. And beyond that, people have wildly varying preferences for which merge tools to use, so we didn't want to dictate one, and it can be tricky to get the setup working well. We're continuing to monitor and collect feedback on how well (or not well) this is working for folks, but for now we're going to stay with the current implementation. 

If there's anything I said that doesn't line up with how you're thinking about it, please feel free to add more context. Thanks for the feedback.

**Comment by tholden** [comment]
Even if you don't want to direct people towards a merge tool, that sentence is still terrible.

It would be clearer if you cut that central clause. (Or cut the whole sentence and just add a link to open the command line.)

I really don't see the cost of a "run git mergetool" button though.

(For some context: I'm giving a quick intro to Git presentation tomorrow and I was trying to do the whole thing without touching the command line. Running a merge tool is the one thing that is currently forcing me to show the command line, which is rather disappointing. The people I talk to will mostly be using Git for Matlab and Tex, and neither lend themselves to using a third party editor with three way merge capabilities.)
