### ISSUE TITLE
github desktop: on "Let's get started" page, but can't edit credentials

### ISSUE THREAD

**Issue by fa-cos** [desktop/desktop#7828]
There is no "File" or any other menu item (I'm on Win 10). desktop v2.0.4

how the heck do I edit my credentials? 

thanks,

![image](https://user-images.githubusercontent.com/51973076/59719637-1d2e9180-91da-11e9-9c40-ad10b8b34a3e.png)

**Comment by tierninho** [comment]
@fa-cos Select one of the three Repository options (even if you end up deleting the repository). Once you complete this step, the login will be under File > Preferences. 

Hope this helps!

**Comment by fa-cos** [comment]
that did it. thanks for the speedy reply!
