### ISSUE TITLE
Support Multiple Github.com Accounts

### ISSUE THREAD

**Issue by staabm** [desktop/desktop#7830]
I have 2 separate github.com accounts, one for personal and one for enterprise use.

it would be great if I could somehow use multiple github.com accounts at once, or at least be able to start the application with different "profiles" or similar, so I can work with both accounts, without "sign out" -> "sign in" workflows a few times a day.

**Comment by shiftkey** [comment]
@staabm thanks for the suggestion!

We're tracking this in an existing issue #3707, which I've added your details to - please follow along with that discussion.
