### ISSUE TITLE
How to verify if repository in a conflict state for conflict that caused by stash pop

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#7831]
When switching branch, if there are conflicts, it will mark the repository in a conflict state, and show the merge conflict dialog. I found it used the .git/MERGE_HEAD file existence to determine whether it's in a conflict state.
But when I pull repository, if there are same changed files in my local, I will stash them, after the pull completed, I will pop the last stash, sometimes it will conflict at this scenario, but I didn't find it entered conflict state, and I didn't found there is MERGE_HEAD file in .git folder. How can I determine it's in a conflict state for conflict that caused by stash pop?
Below are the steps of my stash and pull:
```
git stash
git pull
git stash pop
```

**Comment by shiftkey** [comment]
The `.git/MERGE_HEAD` file contains the commit from the other branch (the one you're merging into the current branch) and is used by Git as internal state while the merge is in progress.

To detect conflicts more generally - and in particular those files in the index that need to be merged - you need to look at the porcelain output from `git status`.

Here's an example setup that I did:

 - create a new branch off `development`
 - changed a line in a file
 - committed the change
 - switched back to `development`
 - made a different change to the same line
 - `git stash`
 - `git checkout [new-branch]`
 - `git stash pop`

You can then see the conflict in the working directory using `git diff`:

```
diff --cc app/src/lib/feature-flag.ts
index 30d3b4069,7c69cadce..000000000
--- a/app/src/lib/feature-flag.ts
+++ b/app/src/lib/feature-flag.ts
@@@ -91,5 -91,5 +91,9 @@@ export function enableStashing(): boole
   * protected branch?
   */
  export function enableBranchProtectionWarning(): boolean {
++<<<<<<< Updated upstream
 +  return false
++=======
+   return gkaljsgsakgjsagjslgaklgahgkhglkaghslkgas
++>>>>>>> Stashed changes
  }
```

But the output from `git status --porcelain=2` has the information you're interested in:

```
u UU N... 100644 100644 100644 100644 2f842ecb421771f77da86de37e38ce17a6d8c076 30d3b406932cd5c9bfcc795270571b196d5a4a22 7c69cadce983708c027e2797cc8593c7009f9317 app/src/lib/feature-flag.ts
```

That leading `u` character is the indicator that this path is an "unmerged entry", and the following two characters represent the state of the conflict:

```
D           D    unmerged, both deleted
A           U    unmerged, added by us
U           D    unmerged, deleted by them
U           A    unmerged, added by them
D           U    unmerged, deleted by us
A           A    unmerged, both added
U           U    unmerged, both modified
```

The docs for [`git status`](https://git-scm.com/docs/git-status) explain the porcelain format in full detail, if you want to poke at that some more.

We get this information for free as we use `git status` in the app, and I think we should be leaning on that a bit more when we handle stashing conflicts in #7748. I'm going to cross-reference these notes there.

**Comment by shiftkey** [comment]
@TerryChan I'm going to close this out for now because it overlaps with #7748, so please follow along with that discussion for how we improve the app to support this better.
