### ISSUE TITLE
MAC OS X 10.14.5 spell checking

### ISSUE THREAD

**Issue by ginko** [desktop/desktop#7843]
Hello, I'm not sure if spellchecking was ever a feature implemented in GitHub Desktop (I can't seem to get the native OS X speller to work). It would be very helpful to have the Summary and Description fields checked before commits. Thanks in advance.

**Comment by steveward** [comment]
Thanks for the feedback @ginko! We are tracking this in https://github.com/desktop/desktop/issues/1597, so I'm going to close this issue out. Please follow along there for updates.
