### ISSUE TITLE
Be able to define proxy settings in macOS

### ISSUE THREAD

**Issue by PhillyPhoto** [desktop/desktop#7844]
When I try to sign in to the desktop app I get a 407 error. It doesn't recognize our system proxy ("Automatic Proxy"), and there's no way to manually configure the proxy in the preferences. There should be better proxy detection or an option to specify from within the app.

**Comment by billygriffin** [comment]
Hi @PhillyPhoto, thanks for the issue! We agree, and we're looking at this in https://github.com/desktop/desktop/issues/2789, so please follow along there (and feel free to weigh in if you have anything to add).
