### ISSUE TITLE
User and password request all the time

### ISSUE THREAD

**Issue by luchopb** [desktop/desktop#7861]
## Description

Every time i do something the program requests for user and password, even if I put the right credentials it asks again, but when I go to repository settings and save with no changes, sometimes it works.

## Version

* GitHub Desktop:2.0.4

* Operating system: windows 10 64x

## Steps to Reproduce

1. Fetch origin
2. Requests for user and password
3. Insert user and password
4. Requests again
5. Go to Repository settings, save
6. Sometimes it works

### Expected Behavior

It didn't ask for the password and user before, with just one time it worked

### Actual Behavior

It asks all the time for user and password again and again

**Comment by tierninho** [comment]
@luchopb Thanks for filing. Possible to include your logs? See the Help menu in Desktop.

Also, are you logged when you go to File > Options > Account ? Do you see your avatar here?
