### ISSUE TITLE
New repository name input forces input cursor to end of field

### ISSUE THREAD

**Issue by xt0rted** [desktop/desktop#7862]
## Description

When creating a new repository the `Name` field forces the cursor to the end of the input so you can't easily edit the name if there's an error. You're able to move the cursor to anywhere in the input, but once you enter something it moves back to the end of the input.

## Version
* **GitHub Desktop**: 2.0.4-beta1
* **Operating system**: Microsoft Windows [Version 10.0.18362.175]

## Steps to Reproduce
1. File > New repository
2. Enter a value for the name
3. Move the cursor to the start of the input
4. Type something
5. The cursor immediately moves back to the end of the input

### Expected Behavior
The cursor should remain where it is.

### Actual Behavior
The cursor moves to the end of the input after a key press.

## Additional Information

![2019-06-24_18-00-51](https://user-images.githubusercontent.com/831974/60054953-11474180-96aa-11e9-8f56-65dec9512baa.gif)

### Logs

Nothing shows in the logs related to this.

**Comment by tierninho** [comment]
@xt0rted Confirming this is a bug. Nice find!

No logs. Cannot repro on a Mac.

**Comment by OArnarsson** [comment]
Cannot reproduce.

Version
GitHub Desktop: 2.0.4
Operating system:  Microsoft Windows [10.0.17134.765 (WinBuild.160101.0800)]

**Comment by billygriffin** [comment]
I was also unable to repro on both macOS and Windows. @xt0rted Any ideas about how we could reproduce this or whether it persists after restarting the app?

**Comment by niik** [comment]
This is only reproducible on beta and or dev and due to the nature of the bug it can be a bit finicky to reproduce at times but I've reproduced it and opened #7865 to address it.
