### ISSUE TITLE
allow files filter on startup

### ISSUE THREAD

**Issue by ngmariusz** [desktop/desktop#7873]
I would like start github-desktop with context of base path as i start git diff, aka focus mode
```
git diff .
```
usefull when working with monorepos

```
github-desktop ./packages/pkg1/
```
results with
```

/.git
/file_to_be_not_visible.ext
/packages/pkg1/file_to_be_visble.ext
```

**Comment by niik** [comment]
Hi @ngmariusz, thanks for opening this issue. I'm afraid I'm not quite sure if I understand the feature you're requesting so if you would be so kind as to elaborate a little bit more that would be much appreciated.

In the meanwhile I can say that GitHub Desktop does come with a command line tool. On macOS it needs to be installed by clicking on the `GitHub Desktop` Menu and then `Install Command Line Tool...`

Using that you can type `github .` in a repository too launch GitHub Desktop and select that repository. I hope that helps!

**Comment by tierninho** [comment]
@ngmariusz  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
