### ISSUE TITLE
Can't find certain file to uncheck in the changes

### ISSUE THREAD

**Issue by YoussefWaelMohamedLotfy** [desktop/desktop#7887]
I have a Unity project with about large number of files and need to find a certain file to uncheck in the current changes, because all files are somehow encoded.

**Comment by tierninho** [comment]
@YoussefWaelMohamedLotfy There is no way to do such a search yet. 

You can do a hack but it not perfect: 

Go to `View` > `Toggle Developer Tools` > go to `Elements` tab > do `CMD-`/`CRTL-` `F` > then search for the file you want.  

Closing this issue for now as it is a duplicate of https://github.com/desktop/desktop/issues/6407.
