### ISSUE TITLE
push not possible after clone: repository not found

### ISSUE THREAD

**Issue by staabm** [desktop/desktop#7889]
## Description
I just cloned a private repo from github.com (with github desktop) and worked in it on a branch which was initially created via github.com webinterface.

Now I had the need to rebase this branch against latest master changes.
Trying to force push this changes to github makes the github cli unhappy.

it tells me that the repository could not be found, but `git remote -v` tells me something different...? 

```bash
mstaab@COMPLEX-67 MINGW64 /c/dvl/Zend/DefaultWorkspace13/kunzmann (phpstan)
$ git remote -v
origin  https://github.com/complex-gmbh/kunzmann.git (fetch)
origin  https://github.com/complex-gmbh/kunzmann.git (push)

mstaab@COMPLEX-67 MINGW64 /c/dvl/Zend/DefaultWorkspace13/kunzmann (phpstan)
$ git push -f origin
fatal: AggregateException encountered.
   Mindestens ein Fehler ist aufgetreten.
remote: Repository not found.
fatal: repository 'https://github.com/complex-gmbh/kunzmann.git/' not found

mstaab@COMPLEX-67 MINGW64 /c/dvl/Zend/DefaultWorkspace13/kunzmann (phpstan)
$ git push -f origin phpstan
fatal: AggregateException encountered.
   Mindestens ein Fehler ist aufgetreten.
remote: Repository not found.
fatal: repository 'https://github.com/complex-gmbh/kunzmann.git/' not found

$ git --version
git version 2.12.0.windows.1
```

## Version

* GitHub Desktop: 2.0.4

* Operating system: Microsoft Windows [Version 10.0.18362.145]

## Steps to Reproduce

1. clone repo https://github.com/complex-gmbh/kunzmann via gihtub desktop
2. checkout the `phpstan` branch
3. rebase the phpstan branch against master: `git rebase master`
4. force push to gihtub: `git push -f origin`
5. alternetively try force push only the branch: `git push -f origin phpstan`

### Expected Behavior
either pushing to the origin or pushing to the origin phpstan branch should work

### Actual Behavior
git cli tells me that the repository could not be found

**Comment by staabm** [comment]
after I deleted my whole local repo and cloned it again to get into a clean state, I realized that its possible to commit locally to the branch and push to the origin.

it seem to only fail when doing a rebase and force push.

**Comment by niik** [comment]
Hi @staabm, thanks for opening this.

It seems your problems are with the Git command line tool which specifically and not with GitHub Desktop (please correct me if I'm wrong). Unfortunately there's not much support we can provide for Git itself, but it appears to me as if the error you're getting when you're trying to push is coming from a credential manager and by the looks of it a credential manager built using Microsoft's .net technology. I would guess that the error is coming from the [Git credential manager for Windows](http://microsoft.github.io/Git-Credential-Manager-for-Windows/Docs/CredentialManager.html). Here's one issue that seems similar to yours from that project: https://github.com/microsoft/Git-Credential-Manager-for-Windows/issues/613.

In the meantime you should be able to rebase your branch using GitHub Desktop, see https://help.github.com/en/desktop/contributing-to-projects/syncing-your-branch#rebase-your-project-branch-onto-another-branch. If you rebase your branch using Desktop the application will also allow you to force-push the branch.

I'm going to close this issue for the time being as it isn't directly related to GitHub Desktop but feel free to open another issue or comment on this one if you feel like GitHub Desktop itself is causing you problems.
