### ISSUE TITLE
another - Authentication Failed issue

### ISSUE THREAD

**Issue by namirda** [desktop/desktop#7895]
Using Github Desktop 2.0.4 on Win10 with a gogs local repo. 

Pull works OK but getting this error in the log file when pushing

`
2019-06-29T08:50:14.904Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 1.850s)
2019-06-29T08:50:14.904Z - error: [ui] `git -c credential.helper= push origin master:master --progress` exited with an unexpected code: 1.
stderr:
Enumerating objects: 5, done.
Counting objects:  20% (1/5)   
Counting objects:  40% (2/5)   
Counting objects:  60% (3/5)   
Counting objects:  80% (4/5)   
Counting objects: 100% (5/5)   
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects:  50% (1/2)   
Compressing objects: 100% (2/2)   
Compressing objects: 100% (2/2), done.
Writing objects:  33% (1/3)   
Writing objects:  66% (2/3)   
Writing objects: 100% (3/3)   
Writing objects: 100% (3/3), 272 bytes | 272.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
error: RPC failed; HTTP 401 curl 22 The requested URL returned error: 401 Unauthorized
Everything up-to-date
`

The above log message says that everything is up to date - but it is not. The push failed.

I gather from the log file entries above that Git Desktop is using the command "git -c credential.helper= push origin master:master --progress" under the hood. 

Entering that exact command into the command line works perfectly.

The simpler push command "git push http://192.168.1.79:3001/neil/test.git" also works from the command line.

This is presumably a bug in Git Desktop since the push works in the command line using the same command as Git Desktop is supposedly trying to use.

Thanks for any suggestions

**Comment by tierninho** [comment]
@namirda Thanks for filing the issue. Could be one of three things:

1) Curious if you are using a firewall?

If you add Github Desktop to the Firewall Exceptions, it should work:
 
Firewall -> Allow App Access through Firewall -> Change Settings -> Add other App
Then add the GitHubDesktop.exe file found in User/AppData/Local/GitHubDesktop

2) Increase buffer size to the largest individual file size of your repo, like so:

`git config --system http.postBuffer 52428800`

3) or you may have made a mistake in the remote URL, double-check the output with `git remote -v` and fix it with:

`git remote set-url origin <new-url>` assuming the remote name is `origin`

**Comment by namirda** [comment]
Thanks for your reply. I had already checked the firewall and the remote URL and both seemed OK. However, today when I look at this again, all seems to be working and so I'm not at all sure what was going on. I will close this issue and assume the problem was at my end somewhere.

**Comment by billygriffin** [comment]
Glad to see it’s working @namirda, and sorry for the confusion!
