### ISSUE TITLE
UI broken in commit

### ISSUE THREAD

**Issue by neiamenase** [desktop/desktop#7896]
What is wrong with the app? I cannot even type a commit message (or it cannot be viewed)
<img width="1030" alt="Screen Shot 2019-06-29 at 7 29 10 PM" src="https://user-images.githubusercontent.com/4963885/60383514-5998a200-9aa4-11e9-9d35-0faec4de3951.png">

**Comment by billygriffin** [comment]
Hi @neiamenase, thanks for the issue and sorry you’re having problems. Would you mind sharing what OS version you’re using and what version of Desktop?

In addition, if you could attach a log file (available in Help menu) from a day this occurred, that would be great to help us diagnose.

**Comment by neiamenase** [comment]
OS: macOS High Sierra
Version 10.13.6

Desktop: 1.6.1

[2019-06-29.desktop.production.log](https://github.com/desktop/desktop/files/3342609/2019-06-29.desktop.production.log)

**Comment by neiamenase** [comment]
maybe it would be useful too, let me add one more log
[2019-05-25.desktop.production.log](https://github.com/desktop/desktop/files/3342618/2019-05-25.desktop.production.log)

noted that I was "neiamenase", but changed to "Sam" that day in order to fix this issue...

<img width="304" alt="Screen Shot 2019-06-30 at 3 17 57 PM" src="https://user-images.githubusercontent.com/4963885/60393576-53f59780-9b4a-11e9-9577-3d477e6735bf.png">

But as you can see, the account out sync-ed and the contribution data went wrong
![image](https://user-images.githubusercontent.com/4963885/60393616-da11de00-9b4a-11e9-8727-1e9db12ba03f.png)

leading me having no contribution at all when I changed to "Sam"
if you have some ways to fix the past history, please let me know....

As I am Sam = neiamenase...

**Comment by neiamenase** [comment]
Noted that I change to be "Sam" on 25/05/2019 by changing the name to Sam

![image](https://user-images.githubusercontent.com/4963885/60393657-615f5180-9b4b-11e9-896a-eb95a475fc94.png)

**Comment by billygriffin** [comment]
Hi @neiamenase, sorry for the confusion! From the logs, it looks like there may be an issue with the app updating properly.

`Error: Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. See https://github.com/Squirrel/Squirrel.Mac/issues/182 for more information.`

Assuming the app is in your Downloads directory, would you mind moving it to a different directory and updating to the latest version (2.0.4 or 2.1)?

If the problem persists after updating the app, we'll definitely be happy to look into it further!

**Comment by outofambit** [comment]
hi @neiamenase we haven't heard back from you in a while, so i'm going to close this issue. please comment here if you have anymore questions or information and we can reopen it. thank you!
