### ISSUE TITLE
Merge branch - resolve conflicts UI cutting off file path.

### ISSUE THREAD

**Issue by michelmohr** [desktop/desktop#7897]
Using the latest version of Github desktop.
I'm trying to merge a branch into my current branch resulting in conflicts.
A UI screen pops up showing a list of conflicts. But I cannot tell which file each line is about.
They all say "dev\Unity Client\Magic Kitchen\Assets...".
![image](https://user-images.githubusercontent.com/9070829/60396642-7c7a9300-9b44-11e9-8ece-7d4470cc0fd6.png)

**Comment by billygriffin** [comment]
Hi @michelmohr, thanks for the issue! We agree that it's not optimal, and appreciate you bringing it up. We're tracking this in #6666 so I'm going to close this, but please follow along there and feel free to weigh in about the possible solution discussed.

**Comment by mekenzeke** [comment]
> Using the latest version of Github desktop.
> I'm trying to merge a branch into my current branch resulting in conflicts.
> A UI screen pops up showing a list of conflicts. But I cannot tell which file each line is about.
> They all say "dev\Unity Client\Magic Kitchen\Assets...".
> ![image](https://user-images.githubusercontent.com/9070829/60396642-7c7a9300-9b44-11e9-8ece-7d4470cc0fd6.png)
