### ISSUE TITLE
Map undo of commit to control-Z

### ISSUE THREAD

**Issue by osianSmith** [desktop/desktop#7905]
**Please describe the problem you think should be solved**
The ability to undo a commit by simply pressing Contol (or cmd) Z.

If a commit needs to be undone, there is a undo button, where the commit button is, however pressing cmd-z, does nothing and there is no easily found options in the status bar in macOS.

Example:

>The other day I had a bad commit and to undo this, I looked in the status bar, where an option should also be, tried cmd z and couldn't find how to undo the commit. I resorted to doing this in the terminal.

**Do you have any potential solutions in mind?**

The ability to undo commits with cmd-z and/or the option in the options menu.

**Comment by outofambit** [comment]
hi @osianSmith thanks for filing this issue! i would consider this part of the conversation in #5725. i've linked this issue to that discussion, but feel free to add additional thoughts! thanks!
