### ISSUE TITLE
fatal: the remote end hung up unexpectedly

### ISSUE THREAD

**Issue by mohammedelkhouly** [desktop/desktop#7912]
## Description

when i try to push files to the repository it takes too long time after that an error appears and says, fatal: the remote end hung up unexpectedly

## Version

* GitHub Desktop:

* Operating system:
windows 10

## Steps to Reproduce

- i copy the files to my local repository
-i commit it
-when i try to push it 

### Expected Behavior
 my files uploaded on the repository

### Actual Behavior
 an error appears says the remote end hung up

### Logs

[2019-06-26.desktop.production.log](https://github.com/desktop/desktop/files/3356684/2019-06-26.desktop.production.log)

**Comment by tierninho** [comment]
@mohammedelkhouly Please fill out the missing items in the template above and add your logs from the Help menu. Thanks for meeting us halfway 😄

**Comment by steveward** [comment]
@mohammedelkhouly I just sent a reply to the email you previously sent. We can continue to debug this further there.
