### ISSUE TITLE
Authentication failure on desktop app after password change

### ISSUE THREAD

**Issue by tooda02** [desktop/desktop#7913]
## Description
I've been using GitHub Desktop for a while.  Recently, GitHub online forced a password change and since then I'm unable to clone a repository or push changes to a repository I've cloned in the past.  Either action gets an authentication failure and pops up a login form that rejects my userid and password.   I've tried:

1. Logging out and logging back in again.  The login is successful, but I get the same authentication failure attempting to clone a repo.
2.  Uninstalling GitHub Desktop, deleting its files from %appdata% and %localappdata%, and reinstalling.  This makes me login again, which is successful but I still can't clone a repo.

The repo I'm trying to clone is https://github.com/aws-samples/amazon-kinesis-learning/tree/learning-module-1, which is public.  I have no trouble accessing it from the browser.

## Version
* GitHub Desktop: 2.1.0
* Operating system: Windows 10 Home 10.0.17134

## Steps to Reproduce
1. Change password online
2. Try to use GitHub Desktop for anything.

### Expected Behavior
Successful clone

### Actual Behavior
Authentication failure.

## Additional Information
![image](https://user-images.githubusercontent.com/11247671/60629646-5f93c900-9dab-11e9-8580-1ea00ca14b6a.png)
Note that it's showing my repositories, so the login is successful

![image](https://user-images.githubusercontent.com/11247671/60629668-80f4b500-9dab-11e9-927c-4e4ea2576474.png)
Attempted clone

![image](https://user-images.githubusercontent.com/11247671/60629680-8ce07700-9dab-11e9-93d0-2a124818c569.png)
Authentication failure

### Logs
[2019-07-03.desktop.production.log](https://github.com/desktop/desktop/files/3357064/2019-07-03.desktop.production.log)

**Comment by tierninho** [comment]
@tooda02 Thank you for filing this and including all the data.

I can reproduce this. Results for manual copy/paste of clone URL are the same:

```
install.ts:23 `git -c credential.helper= clone --recursive --progress -- https://github.com/aws-samples/amazon-kinesis-learning/tree/learning-module-1 /Users/tierninho/github/tests/sdfsdf/learning-module-1` exited with an unexpected code: 128.
stderr:
Cloning into '/Users/tierninho/github/tests/sdfsdf/learning-module-1'...
fatal: repository 'https://github.com/aws-samples/amazon-kinesis-learning/tree/learning-module-1/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
```

and attempting to clone via github.com desktop button (SSH or HTTPS) results in:
```
install.ts:27 Open Repository from URL failed, did not find or clone repository: https://github.com/aws-samples/amazon-kinesis-learning - payload: {"branch":null,"filepath":null,"name":"open-repository-from-url","pr":null,"url":"https://github.com/aws-samples/amazon-kinesis-learning"}
```

- I forked the repo as a test and it cloned successfully. 
- Despite the error message in the logs, the repo does still exist, is not archived, is accessible, and has not been deleted or renamed.

The investigation to continue.

**Comment by tierninho** [comment]
@tooda02 I just got it working for me. 

Change the clone URL to:
https://github.com/aws-samples/amazon-kinesis-learning

**Comment by outofambit** [comment]
hey @tooda02 i'm going to close this, but let us know if you are still having having trouble and we can reopen this issue. thank you!

**Comment by Alex-Hemming** [comment]
Same problem. Any possible solutions? Maybe a frequent mistake that causes this? Happens on multiple computers with only one account.

**Comment by steveward** [comment]
@Alex-Hemming would you mind opening a new issue and filling out the template? I'd be happy to assist you further there. Thanks!

**Comment by Alex-Hemming** [comment]
hi, I have done it . Though accidently this is not the account that does not work with GitHub, it was HemmingAlex. As such it is submitted through that.

en regards, Alex.
________________________________

**Comment by Alex-Hemming** [comment]
https://github.com/desktop/desktop/issues/10696
________________________________
