### ISSUE TITLE
Enhance error messaging for incorrect clone urls

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7914]
Currently the error messaging for the clone repo URL modal does not properly handle URLs correctly and includes more info than needed. 

For instance:
https://github.com/aws-samples/amazon-kinesis-learning/tree/learning-module-1 results in this error

```
`git -c credential.helper= clone --recursive --progress -- https://github.com/aws-samples/amazon-kinesis-learning/tree/learning-module-1 /Users/tierninho/github/tests/learning-module-1` exited with an unexpected code: 128.
stderr:
Cloning into '/Users/tierninho/github/tests/learning-module-1'...
fatal: repository 'https://github.com/aws-samples/amazon-kinesis-learning/tree/learning-module-1/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
```

when really we should recognize the url is too long and should be tapered to https://github.com/aws-samples/amazon-kinesis-learning

Current logic takes the user to an old Auth modal like so:
![Screen Shot 2019-07-03 at 2 23 01 PM](https://user-images.githubusercontent.com/14828183/60631957-14bf8480-9d9e-11e9-833c-cb0cb1c0304d.png)

Our error messaging should include this scenario and suggest to the user to check the url, not reroute them to an auth modal.

v2.1, Mac

**Comment by ADustyOldMuffin** [comment]
Hey @tierninho is this up for grabs? If so I'd like to work on it.

**Comment by tierninho** [comment]
@ADustyOldMuffin That would be great, but let's hold off for a few (business) days as I would like to allow others on the team to weigh in.

This is also semi-related to https://github.com/desktop/desktop/issues/6649 so may be a bigger issue.

Appreciate the enthusiasm! ✨

**Comment by ADustyOldMuffin** [comment]
Hello @tierninho I'm just checking in to see if anything had happened on this yet.

**Comment by tierninho** [comment]
@ADustyOldMuffin Go for it as the issue sat for some time. Thanks!

**Comment by tidy-dev** [comment]
This was addressed in https://github.com/desktop/desktop/commit/b89ac1f8ba424ffe7632804af3727ebe6d102112 which parses the hostname and and owner.
