### ISSUE TITLE
Not able to open github

### ISSUE THREAD

**Issue by akshaybandivadekar** [desktop/desktop#7926]
Error: spawn /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git EAGAIN
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Version: 1.3.2
OS: Mac OS 10.14.0

**Comment by billygriffin** [comment]
@akshaybandivadekar This looks like #5416 and may have to do with resource limits. Would you mind restarting your machine and seeing if that fixes it?

I also notice that you’re on Desktop 1.3.2. The current version is 2.1, so I’m wondering if there’s another problem updating the app. Sometimes this has occurred when the app is in the Downloads folder, so if that’s the case please move it out of there and let us know if you’re able to get the latest version.

Thanks!

**Comment by jamesbryanpalmer** [comment]
i need someone whit a moral compass to help me out of this shit hole of github ther in my whole house and i cannot get them out

**Comment by robert-matternet** [comment]
On Ubuntu 18.04 LTS, cannot start github-desktop
Using the latest from the snap store

```
/snap/bin/github-desktop
/snap/github-desktop/63/app/github-desktop: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_date_copy
```

**Comment by outofambit** [comment]
hi @robert-matternet linux is not supported by this team, its maintained in a separate fork. it looks like https://github.com/shiftkey/desktop/issues/163 is the issue for what you're describing.

**Comment by akshaybandivadekar** [comment]
This issue is resolved with restarting laptop, still strange behavior.
Thanks for helping
Closing this issue
