### ISSUE TITLE
Merge conflict resolution hides filename

### ISSUE THREAD

**Issue by danpalmer** [desktop/desktop#7931]
## Description

In the merge conflict resolution window, file paths and names are sometimes truncated such that it is impossible to figure out what it refers to.

<img width="514" alt="Screenshot 2019-07-08 at 14 32 08" src="https://user-images.githubusercontent.com/202400/60783301-5cbf1c80-a18d-11e9-8667-9f45a00c230f.png">

## Version

Will edit to add later (when the merge conflict UI is open it is not possible to view the about window).

* GitHub Desktop:
* Operating system: macOS 10.14.4

## Steps to Reproduce

1. Create a committed file with a long path/name.
2. Edit in a branch.
3. Delete in another branch.
4. Merge these branches.
5. See result in merge resolution dialog.

### Expected Behavior

I expect to be able to see the full file path/name, or, to be able to select the truncated text that is displayed and copy it to get the full path/name (as is standard with macOS text controls that use truncation).

Alternatively, I expect to be able to open this file or the diff of it in an external editor.

### Actual Behavior

The name/path is truncated. This means that I am unable to see what the file is, what the change that happened on the target branch is, or what the change that happened on the merging branch is. All I am able to see is roughly where in the codebase the change happened.

I can revert to command line git tooling, but my merge conflict resolution workflow does not typically need to revert to this tooling.

**Comment by outofambit** [comment]
Hi @danpalmer, thanks for the issue! We agree that it's not optimal, and appreciate you bringing it up. We're tracking this in #6666 so I'm going to close this, but please follow along there and feel free to weigh in about the possible solution discussed.
