### ISSUE TITLE
juypter

### ISSUE THREAD

**Issue by fhdkdbb706** [desktop/desktop#7934]
**Please describe the problem you think should be solved**
A clear and concise description of what the problem is and who else might be impacted. Screenshots are encouraged.

Example:

> “When I run into a merge conflict, I don’t know where to go to resolve it. Anyone who works off of multiple branches will likely run into this problem at least occasionally.”

**[Optional] Do you have any potential solutions in mind?**
A clear and concise description of one or more solutions you think might solve the problem. Please include any considered drawbacks or tradeoffs, and how users might use your solution(s). Screenshots or mockups are helpful here!

**Comment by billygriffin** [comment]
Hi @fhdkdbb706, thanks for the issue. Just from the title it’s unclear what this issue is about. Would you mind editing it with what problem you’d like to see solved in Desktop and respond so we know what you’re referring to? Thanks!

**Comment by billygriffin** [comment]
@fhdkdbb706 Since we haven't heard back from you, I'm closing this issue for now, but please feel free to expand on it and we'll be happy to reopen and discuss.
