### ISSUE TITLE
logged in with my username and committed and pushed. But commit shows on the name of previously logged in user.

### ISSUE THREAD

**Issue by vijayashantiM** [desktop/desktop#7936]
## Version

* GitHub Desktop:

* Operating system:

**Comment by billygriffin** [comment]
Hi @vijayashantiM, would you mind filling out the rest of the issue template please to help us understand and diagnose the problem? This looks like it may be something along the lines of #610 where your Git info doesn’t match the GitHub account you’re logged in with, but I’d like to be sure before closing this as a duplicate. Thanks!
