### ISSUE TITLE
The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.

### ISSUE THREAD

**Issue by juancampuzano** [desktop/desktop#7938]
*Description*

The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.

*Version*

GitHub Desktop version: 2.1.0

OS version: macOS Mojave versión 10.14.5

Expected behavior: able to do "fetch origin" without receiving the current alert

*Actual behavior:*

User of the company that have write permissions on the project are unable to do fetch origin from the github desktop.

Tests were performed using git directly in the terminal and for this case there was no problem.

*Steps to solve it without success:*

1) The repository was removed  locally and re-cloned.
2) User of the company was removed and then it was added again

[2019-07-11.desktop.production.log](https://github.com/desktop/desktop/files/3382776/2019-07-11.desktop.production.log)

![Screen Shot 2019-07-11 at 10 31 03 AM](https://user-images.githubusercontent.com/52759609/61064238-050bf580-a3c7-11e9-8abc-1064d42543c4.png)

**Comment by outofambit** [comment]
Hi @juancampuzano thanks for reaching out! I'm sorry you're having this issue. If I'm reading this right, you are able to clone the repository but _not_ fetch it afterwards? And you've tried this via github desktop _and_ the command line and received the same error message as above?

**Comment by juancampuzano** [comment]
> Hi @juancampuzano thanks for reaching out! I'm sorry you're having this issue. If I'm reading this right, you are able to clone the repository but _not_ fetch it afterwards? And you've tried this via github desktop _and_ the command line and received the same error message as above?

1) Yes, I am able to clone but not to fetch afterwards.
2) In the command line works but with an error. If there are new changes, it does not bring them. It's like I have a problem with permits.

**Comment by shiftkey** [comment]
@juancampuzano there's a clue in the log files that might explain the error:

```
2019-07-11T15:28:01.248Z - info: [ui] [BranchPruner] No branches to prune.
2019-07-11T15:28:03.835Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.730s)
2019-07-11T15:28:05.012Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune upstream (took 1.161s)
2019-07-11T15:28:05.013Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune upstream` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/jsastriawan/mps-microservice.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
```

The fetch works fine for `origin` but errors on `upstream` - do you have permissions to access that repository `https://github.com/jsastriawan/mps-microservice`? That might explain the error, although I'm not clear on how that remote was added.

**Comment by juancampuzano** [comment]
> @juancampuzano there's a clue in the log files that might explain the error:
> 
> ```
> 2019-07-11T15:28:01.248Z - info: [ui] [BranchPruner] No branches to prune.
> 2019-07-11T15:28:03.835Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.730s)
> 2019-07-11T15:28:05.012Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune upstream (took 1.161s)
> 2019-07-11T15:28:05.013Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune upstream` exited with an unexpected code: 128.
> stderr:
> remote: Repository not found.
> fatal: repository 'https://github.com/jsastriawan/mps-microservice.git/' not found
> 
> (The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
> ```
> 
> The fetch works fine for `origin` but errors on `upstream` - do you have permissions to access that repository `https://github.com/jsastriawan/mps-microservice`? That might explain the error, although I'm not clear on how that remote was added.

I do not have access to https://github.com/jsastriawan/mps-microservice!
But I have access to https://github.com/Tulpep/mps-microservice

https://github.com/Tulpep/mps-microservice is a fork of https://github.com/jsastriawan/mps-microservice

**Comment by tierninho** [comment]
@juancampuzano If you do not have access to the original repo (https://github.com/jsastriawan/mps-microservice) then I suspect the error is valid as private forks inherit the permissions structure of the upstream or parent repository.

Did you have access at some point to https://github.com/jsastriawan/mps-microservice?

**Comment by alexmeseguer** [comment]
Hola Juan, ¿conseguiste finalmente arreglar el problema del repositorio? Me ocurre lo mismo.

**Comment by msh855** [comment]
I have the same problem. I am the sole owner of the repository and I have access to it.

**Comment by technical-customs** [comment]
Cannot push repo to github from github desktop

**Comment by steveward** [comment]
@juancampuzano I'm going to close this issue out due to inactivity -- let us know if you are still having problems accessing this repository in GitHub Desktop and we can look into this further.

**Comment by GiusseppeSB** [comment]
i had the same problem, was solved by the admin of respository giving me admin permisions

**Comment by Xinyu416** [comment]
I had the same problem, was solved by the admin of respository giving me admin permisions.

**Comment by bopoh13** [comment]
In version 2.5.2 deleting all old branches and restarting the application helped (one branch still remained).

**Comment by eminberkay** [comment]
unnecessary waste of time.

**Comment by BillyOfficial** [comment]
Simples, depois de remover repositório do GitHub Local, apague os arquivos na pasta do repositório, e suba novamente o repositório.

**Comment by matteoruscitti** [comment]
My friend's having issues with this, we've tried pretty much everything. Senseless bug

**Comment by steveward** [comment]
@mathieudutour please open a new issue and fill out the template so that we can assist you further.
