### ISSUE TITLE
How To Connect To GitLab Enterprise on Mac 10.13 High Sierra?

### ISSUE THREAD

**Issue by dada78** [desktop/desktop#7939]
Hi,
I would like to use this desktop client to access my work repo which uses GitLab Enterprise. How would I go about setting this up on Mac High Sierra? Please advise. Thanks!

**Comment by outofambit** [comment]
Hi @dada78 you can do this from the "Clone repository" modal, which you can open by opening the  `File` menu in GitHub Desktop, choosing `Clone Repository...` and choosing the `URL` tab.

<img width="530" alt="Screen Shot 2019-07-12 at 11 22 02 AM" src="https://user-images.githubusercontent.com/964912/61150101-74e9b100-a497-11e9-914e-78da3eaed31e.png">

You can enter the URL for your GitLab Enterprise repository there and it should clone just fine. :) Let me know if you have any more questions!
