### ISSUE TITLE
Cannot clone using the right credentials

### ISSUE THREAD

**Issue by felipedrumond** [desktop/desktop#7941]
I'm trying to clone a repository of mine. GitHub Desktop asks for the username and password but although I provide the right credentials, it keeps asking for the credentials.

If I clone from prompt command using
  > git clone https://USER:PASSWORD@dev.azure.com/felipe/kala/_git/kala-ui 
it works, so I'm pretty sure I have the right credentials.

After cloning, I can add that repository to GitHub Desktop and access the repo without any issues.

**Comment by outofambit** [comment]
Hi @felipedrumond i'm sorry you're having this issue. What URL are you using in the GitHub Desktop UI to clone this repository? Are you seeing a popup in GitHub Desktop that asks for credentials? Or is it appearing some other way?

Can you please fill out the issue template, too? Knowing what version and operating system you're on is super helpful. Thanks!

**Comment by tierninho** [comment]
@felipedrumond  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
