### ISSUE TITLE
Cannot launch Github Desktop (seems not related with the previously similar issue)

### ISSUE THREAD

**Issue by imronuke** [desktop/desktop#7952]
## Description

Cannot launch Github Desktop recently. Seems happened after Ubuntu update.

## Version

* GitHub Desktop: 2.1.0-linux1

* Operating system: Ubuntu 18.04 LTS

## Steps to Reproduce

Clicking the Github Desktop icon in the menu bar

### Expected Behavior

Github Desktop should start and new window should apppear

### Actual Behavior

Nothing happened. No error message. I tried to open from terminal, I got this message:
```
/snap/github-desktop/63/app/github-desktop: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_date_copy
```

**Comment by steveward** [comment]
Thanks for the report @imronuke. All issues related to the Linux versions of GitHub Desktop are tracked in @shiftkey's fork of GitHub Desktop, where he manages the Linux releases:

https://github.com/shiftkey/desktop/issues

You can open an issue directly there. Thanks!

**Comment by imronuke** [comment]
Thanks @steveward. Didn't know about this.

**Comment by Schadrack2544** [comment]
I also found it not working to me using Linux mint 19.2 Tina

**Comment by MarnusStoltz** [comment]
Hi imronuke,

Also getting the same error for Ubuntu 18.04

Kind Regards
Marnus

**Comment by AmrSoliman** [comment]
Hey @shiftkey 
i face the same problem using ubuntu 18.04.3 with git-desktop version 2.1.0-linux1

after clicking on the Github Desktop icon in the menu bar or search, nothing happened and app don't launch

**Comment by SteveAtSentosa** [comment]
Hi All,

Same for me on Ubuntu 19.04

Kind Regards
Steve

**Comment by darielvicedo** [comment]
Same here, Ubuntu 18.04

**Comment by tierninho** [comment]
All, please see the previous comment here: https://github.com/desktop/desktop/issues/7952#issuecomment-511409872
