### ISSUE TITLE
Macro Support (user defined Git commands)

### ISSUE THREAD

**Issue by aminya** [desktop/desktop#7954]
Adding an option to make a macro by the user, so they can their git commands for a repository or branch.

For example, the user creates a macro which gets 2 inputs (title, comments), then the software edits the comment of the last commit in that repository/branch by running the following commands.
```
git commit --amend -m "title" -m "

comments

"
git push --force
```
This can make the development of Github desktop much easier, as users can share the macros with this repository,
https://github.com/desktop/desktop/issues/7953
https://github.com/desktop/desktop/issues/5219

**Comment by billygriffin** [comment]
Hi @aminya, thanks for the issue! One of our primary goals with GitHub Desktop is to make things as intuitive and quickly comprehensible as possible regardless of the user's knowledge of Git. Obviously we support some of the more common Git workflows that advanced users love, and we'll continue to look for those opportunities. But we think something like this is likely to introduce significant complexity, and when things go wrong, we won't be able to help people get out of a bind. Thanks for the idea though, we definitely love to hear how people are thinking the product could be more useful.
