### ISSUE TITLE
Open in Desktop button fails to work if clone modal is open

### ISSUE THREAD

**Issue by AlFasGD** [desktop/desktop#7961]
## Description
Pressing the Open in Desktop button in a repo from the website of GitHub while GitHub for Desktop is open and the user has already opened the clone modal does not copy the URL on the textbox

## Version
* GitHub Desktop:
2.1.0
* Operating system:
Microsoft Windows [Version 10.0.17134.885]

## Steps to Reproduce
1. Open GitHub for Desktop
2. Open the clone repository modal at any tab
3. Go to a GitHub repository that you do not have locally on your browser, for example [desktop/desktop](https://github.com/desktop/desktop)
4. In the website, press the Clone or download button and then the Open in Desktop button

### Expected Behavior
The already opened clone repository modal will change its selected tab to the last one (URL) and the URL of the repository will be automatically put in the textbox.

### Actual Behavior
The URL is not inserted in the textbox (however the tab is correctly selected to URL).

## Additional Information
![remains as is png](https://user-images.githubusercontent.com/8298332/61313517-41928380-a803-11e9-91e7-5c70bb12b3f7.png)

### Logs
[2019-07-16.desktop.production.log](https://github.com/desktop/desktop/files/3398507/2019-07-16.desktop.production.log)

**Comment by tierninho** [comment]
@AlFasGD Thank you for filing this bug. I have confirmed that it is not working as expected. 

#### Summary of the problem:
A user cannot cannot use the `Open on Desktop` button to open a GitHub.com repo on Desktop if the clone modal is already open. Closing the clone modal on Desktop and reattempting resolves the issue.

Not much in the logs. This happens no matter if the clone works or not:
```
install.ts:27 Open Repository from URL failed, did not find or clone repository: https://github.com/tierninho/zxczxczxc - payload: {"branch":null,"filepath":null,"name":"open-repository-from-url","pr":null,"url":"https://github.com/tierninho/zxczxczxc"}
```

2.1.0-beta3, mac
