### ISSUE TITLE
Diff doesn't have scroll bar and commit missing

### ISSUE THREAD

**Issue by HashimotoYT** [desktop/desktop#7967]
## Description

When trying to open big diff what's should have a scroll, but it's doesn't have the scroll, after drag and scroll this brokes window position.

## Version

* GitHub Desktop: 2.1.1-beta1 (Electron 5)

* Operating system: Microsoft Windows [Version 10.0.18362.239]

## Steps to Reproduce

1. Open diff what's need scrolling (for example big `yarn.lock` change)
2. Try to scroll by default method using mouse scroll.
2.1 Try to drag and scroll, see screencast.

### Expected Behavior

Diff have scroll bar, and it's able to scroll.

### Actual Behavior

Diff doesn't have scroll bar, and diff not scrollable.

## Additional Information

![where my scrolls](https://user-images.githubusercontent.com/24681191/61329132-4831f280-a825-11e9-9419-339bc5ee667f.gif)

**Comment by outofambit** [comment]
Hi @HashimotoYT thanks for filing this and sorry its happening! We're already looking into this bug and hope to have a fix soon. Will post updates here. Thank you!

**Comment by billygriffin** [comment]
@HashimotoYT Echoing @outofambit, thanks so much for the report. If you're in a bind, you can use the production version in the mean time until this is fixed. Prod should be working normally still (desktop.github.com for the download).
