### ISSUE TITLE
Changes tab doesn't have commit box when have changes and diff scrollable

### ISSUE THREAD

**Issue by HashimotoYT** [desktop/desktop#7968]
## Description

Changes tab doesn't have commit box when diff should be scrollable.

## Version

* GitHub Desktop: 2.1.1-beta1

* Operating system: Windows 10 1903

## Steps to Reproduce

1. Change (create, remove) any file what should have scroll bar.
2. Try to do commit

### Expected Behavior

Box shown's

### Actual Behavior

This box doesn't showns.

## Additional Information

![one more pri 1](https://user-images.githubusercontent.com/24681191/61332303-9991b000-a82c-11e9-86b4-a664a832fb7c.gif)

**Comment by tierninho** [comment]
@HashimotoYT thanks for filing this. We are attributing the underlying issue to the same bug seen in https://github.com/desktop/desktop/issues/7967. Going to close this issue for now. 

Thanks for your patience!

**Comment by tierninho** [comment]
@HashimotoYT this is fixed. Please download the latest beta version.
