### ISSUE TITLE
Why there is not native linux GUI version of desktop?

### ISSUE THREAD

**Issue by sunn-e** [desktop/desktop#7973]
I am looking for GUI and I can't find one. I want the Desktop available for linux too. :)

**Comment by iAmWillShepherd** [comment]
We have an unofficial linux distribution of Desktop [here](https://github.com/shiftkey/desktop). We take contributions to that fork, so don't hesitate to open a PR that addresses an issue or expands Linux support 👍

**Comment by renannprado** [comment]
@iAmWillShepherd I see you have the fork. I downloaded it and it's working, however I'm curious on to why those changes are cannot be merged into this repository?

**Comment by outofambit** [comment]
hi @renannprado please see #1525 for more information. thanks!
