### ISSUE TITLE
Desktop preview is empty while in full screen

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#7978]
# Description
Desktop's Mission Control preview is empty when in full screen mode.

## Version
* GitHub Desktop: 2.1.1-beta1
* Operating system: MacOS Mojave

## Steps to Reproduce
1. Full screen Desktop (use the green button)
1. Open mission control

### Expected Behavior
The contents of Desktop is visible in the preview.

### Actual Behavior
A blank white preview appears.

## Additional Information
This is a bug in Electron and was fixed in https://github.com/electron/electron/pull/18661#ref-commit-8a0d03e, but was not back ported to Electron 5.0.x.

Here is a [YouTube video](https://youtu.be/tnAo9_6g6h0) reproducing the behavior on Desktop.

### Logs
Logs are not relevant for this issue.

**Comment by iAmWillShepherd** [comment]
The fix for this will not be available until next Tuesday which is when the Electron team runs their releases.

**Comment by tierninho** [comment]
Here is a pic for perspective:

![Screen Shot 2019-07-17 at 7 11 15 AM](https://user-images.githubusercontent.com/14828183/61396038-813c8800-a862-11e9-9558-20dc1dbf8cd1.png)

**Comment by iAmWillShepherd** [comment]
https://github.com/electron/electron/pull/19315, the underlying issue, has been back ported to Electron 5.0.x and should be available next Tuesday.

**Comment by iAmWillShepherd** [comment]
Turns out the fix in Electron 5.0.8 does not fix this issue, so I've opened https://github.com/electron/electron/issues/19430.

**Comment by niik** [comment]
I don't know what version exactly fixed this but it's no longer an issue :tada:

![image](https://user-images.githubusercontent.com/634063/91542681-805b9e00-e91e-11ea-9981-488e02ebb0a3.png)

**Comment by winzig** [comment]
I continue to have this issue.

**Comment by winzig** [comment]
Hmm, just updated from 2.5.3 to 2.5.4 and seems fixed now 🥳
