### ISSUE TITLE
Orphaned branch results in branch pruner error

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7983]
I spotted two console errors after creating the orphaned branch. Not sure if they need some attention:

```
install.ts:23 `git reflog --date=iso --after="2019-07-04T18:55:30.624Z" --pretty=%H %gd %gs --grep-reflog=checkout: moving from .* to .*$ --` exited with an unexpected code: 128.
stderr:
fatal: your current branch 'adasda' does not have any commits yet

///and///

Uncaught (in promise) GitError: fatal: your current branch 'adasda' does not have any commits yet
```

Reproduce by:
- opened a repo in the terminal and type: `git checkout --orphan a-new-branch-name`
- switch back to Desktop and open the new branch
- check console

related to https://github.com/desktop/desktop/issues/7929

v2.1.1, mac

**Comment by iAmWillShepherd** [comment]
It may be worth adding an additional check to skip branches with no commits yet.

Curious to know what @desktop/product thinks. My thoughts are if a person creates a branch and hasn't done anything to it, then we should just ignore it.
