### ISSUE TITLE
Cannot clone using the right credentials

### ISSUE THREAD

**Issue by felipedrumond** [desktop/desktop#7984]
## Description
Cannot clone using the right credentials, or cannot sync (pull/push) after cloning via prompt command using the right credentials
 
I'm trying to clone a repository of mine. GitHub Desktop asks for the username and password but although I provide the right credentials, it keeps asking for the credentials.

If I clone from prompt command using

git clone https://USER:PASSWORD@dev.azure.com/felipe/kala/_git/kala-ui
it works, so I'm pretty sure I have the right credentials.

After cloning, I add that repository to GitHub Desktop and sometimes I can sync withy repo, sometimes not!

## Version

* GitHub Desktop: 2.1.0

* Operating system: Windows 10 Version 1809 Build 17763.615

## Steps to Reproduce

I cannot provide access to this repository because it is company-owned. However, it is hosted in dev.azure.com. 
1. File -> Clone Repository -> Select from URL 
2. Fill in the credentials
3. It will as for the credentials, even though you have provided the right credentials in step 2

### Expected Behavior

Should be fine using the right credentials
### Actual Behavior

Keeps asking the credentials

### Logs

These steps generated no logs!

**Comment by steveward** [comment]
Thanks for opening this @felipedrumond. For authenticating to Azure DevOps we recommend generating an access token. You can find the guide for how to do that here:

https://github.com/desktop/desktop/blob/development/docs/integrations/azure-devops.md

Let me know if you run into any issues with that.
