### ISSUE TITLE
Disable background fetch on metered connections

### ISSUE THREAD

**Issue by mattacosta** [desktop/desktop#7986]
While on a metered connection, background fetches should be disabled to prevent unnecessary data usage. The currently active repository should remain unaffected.

![git-metered](https://user-images.githubusercontent.com/1007463/61509787-21022f00-a9a5-11e9-8570-536b4141a967.png)

**Comment by steveward** [comment]
Thanks for sharing this feedback @mattacosta! Disabling background fetching has been discussed in https://github.com/desktop/desktop/issues/1128, so I'm going to drop this feedback there and close this issue out.
