### ISSUE TITLE
GitHub Desktop not recognizing Atom

### ISSUE THREAD

**Issue by TheTechRobo** [desktop/desktop#7993]
## Version

* Latest version as of the 18th

Windows 7 x64 (Home Premium)
Toshiba Satellite L510

## Steps to Reproduce

Step 1: Open GitHub Desktop and wait a few minutes
2. Install Atom
3. Ctrl-, in GH Desktop
4. Advanced
5. #### External editor
No editors found. Install Atom? 

### Expected Behavior

Atom to show up
### Actual Behavior

Atom doesn't show up

## Additional Information

![Capture](https://user-images.githubusercontent.com/52163910/61579648-0a0f2a00-aad6-11e9-8a62-757d6f33c1e5.PNG)
![GHD ScrnShot1](https://user-images.githubusercontent.com/52163910/61579649-0a0f2a00-aad6-11e9-86e8-9deb5b0d7c5c.PNG)

repository: python-shell

### unsuccessful steps to fix
* Reinstall Atom twice

Sort of like #6324 except
* Not a nightly build
* It doesn't show up AT ALL so there's no error message
* It's not a Mac bug

**Comment by steveward** [comment]
Thanks for the report @TheTechRobo.

Could you open up a command prompt (cmd.exe) and run the following commands for me?

`cd %LOCALAPPDATA%\Atom\`
`atom --squirrel-updated`

Then try restarting GitHub Desktop and let me know if you still do not see Atom in the dropdown menu.

**Comment by TheTechRobo** [comment]
Sorry for the late reply, I was running an errand
Thanks for the quick reply :smile:
It took a few minutes for GitHub Desktop to load... but when it finished its white screen... 
**IT WORKED**!!!!!!
thanks so much, steveward!

**Comment by kwnice** [comment]
Thank you for this.

**Comment by ItsEnrique** [comment]
Huge Help! Thanks!
