### ISSUE TITLE
Description shadow does not update when text changed

### ISSUE THREAD

**Issue by terreng** [desktop/desktop#7994]
## Description

A shadow appears above the co-authors row in the description field when there is enough text to scroll. Scrolling all the way to the bottom causes the shadow to disappear, but updating the description text so that it no longer needs to scroll does not, and causes the shadow to get stuck.

## Version

* GitHub Desktop: 2.1.0

* Operating system: Windows 10 version 1903 [10.0.18362.239]

## Steps to Reproduce

1. Focus on commit description, type enough so that a shadow appears.
2. Scroll to the top of the commit description
3. Select and delete all text in commit description

### Expected Behavior

Shadow should disappear

### Actual Behavior

Shadow remains

## Additional Information

Here's a gif:
![GIF](https://user-images.githubusercontent.com/11605395/61585233-d3540680-ab0b-11e9-8e56-2bd275d14bbc.gif)

**Comment by tierninho** [comment]
@terreng Thanks for filing this. I have confirmed this is a bug and labeled it as so.

2.1.1-beta2, mac
