### ISSUE TITLE
how do I publish?

### ISSUE THREAD

**Issue by ibotnik** [desktop/desktop#7997]

**Comment by ibotnik** [comment]
I uploaded files to the repository and clicked the push button. Now what? How do I publish. A tutorial said there would be a button but there is none. Instructions please?

**Comment by steveward** [comment]
@ibotnik could you share a screenshot of what you are currently seeing in GitHub Desktop? That should help me get a better understanding of the current state of your repository.

**Comment by Rexogamer** [comment]
> I uploaded files to the repository and clicked the push button. Now what? How do I publish. A tutorial said there would be a button but there is none. Instructions please?
Are you sure the tutorial isn't for an odler version of Desktop? And do you mean "how do I push the commits to Github"?

**Comment by Rexogamer** [comment]
@ibotnik see above

**Comment by tierninho** [comment]
@ibotnik 

> I uploaded files to the repository and clicked the push button. Now what? How do I publish. A tutorial said there would be a button but there is none. Instructions please?

Once you make changes to a file, you must commit them and thereafter you can push them up to the remote repository. However, the repository must be published beforehand. The `publish repository` button supersedes the `push` button. If you are seeing the `push` button the the repo is already published.

As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
