### ISSUE TITLE
support VS Codium as external editor

### ISSUE THREAD

**Issue by mediter** [desktop/desktop#8000]
VS Codium is based on VS Code, the only differences being VS Codium is VS Code without MS branding/telemetry/licensing

**Comment by tierninho** [comment]
Marking this as `help wanted` because I'd like someone from the community to explore this further.

Here is a guide to [get started](https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md) with the integration. Thanks!

**Comment by Rexogamer** [comment]
I might look into this 👀

**Comment by Rexogamer** [comment]
I'll only be able to add Win support for it, sorry

**Comment by leotm** [comment]
> I'll only be able to add Win support for it, sorry

Ah right was wondering why it's not being detected on macOS, but good work anyway

**Comment by akim8** [comment]
I'll give macOS support a shot over the weekend.

**Comment by Rexogamer** [comment]
I did my best to add MacOS support, not tested but it is in the code
