### ISSUE TITLE
"no local changes" description text

### ISSUE THREAD

**Issue by Rexogamer** [desktop/desktop#8003]
**Please describe the problem you think should be solved**
The text when there's no changes to the given repo on your machine should be changed to be easier to understand.

**Example:**
when there are no changes: ![Annotation 2019-07-23 100624](https://user-images.githubusercontent.com/42586271/61698773-923d3b80-ad31-11e9-9654-200975f97347.png)

**[Optional] Do you have any potential solutions in mind?**
The text should read: "There are no uncommited changes to this repository on your machine. Here are some friendly suggestions on what to do next:"

**Comment by tierninho** [comment]
@Rexogamer Thanks for filing this. I agree that this could be tweaked a little. 👍

**Comment by Rexogamer** [comment]
@tierninho Do you know which file this string is kept? If so, I could fork and do this myself.

**Comment by tierninho** [comment]
>  If so, I could fork and do this myself.

@Rexogamer Wish I saw this message sooner, doh! Just opened a PR for it: https://github.com/desktop/desktop/pull/8007

**Comment by shiftkey** [comment]
@Rexogamer I'd love to understand more about the motivation behind the "on your machine" part. Can you elaborate?

**Comment by Rexogamer** [comment]
@shiftkey I suggest it because there’s no uncommitted changes on *your* machine; other machines of other people might have uncommitted changes. I’d be fine without it, but I like it as it specifies that it’s your machine with no changes and that other machines might have some.

**Comment by Rexogamer** [comment]
on the topic of grammar...
![image](https://user-images.githubusercontent.com/42586271/61782798-9a16e180-adfe-11e9-81cd-7adec8c05ff6.png)

**Comment by Rexogamer** [comment]
@tierninho Shouldn't it be "That branch can't be found..."? 

Unless you're telling me that Desktop is sentient...

**Comment by shiftkey** [comment]
> Unless you're telling me that Desktop is sentient...

@Rexogamer can you open a fresh issue to cover that example - [we have a few places that follow this pattern](https://github.com/desktop/desktop/search?q=sorry&unscoped_q=sorry) and it'd be great to be consistent if we decide to change that wording

**Comment by Rexogamer** [comment]
> > Unless you're telling me that Desktop is sentient...
> 
> @Rexogamer can you open a fresh issue to cover that example - [we have a few places that follow this pattern](https://github.com/desktop/desktop/search?q=sorry&unscoped_q=sorry) and it'd be great to be consistent if we decide to change that wording

Will do

**Comment by shiftkey** [comment]
> I suggest it because there’s no uncommitted changes on _your_ machine; other machines of other people might have uncommitted changes.

@Rexogamer I feel like this add complication to something we display often in the app, but if others agree I'm happy to revisit this.

I'm happy with how #8007 is, so I'm going to approve that and we can see if it needs iterating on later.

**Comment by Rexogamer** [comment]
also see #8013
