### ISSUE TITLE
32-bit Windows Support

### ISSUE THREAD

**Issue by yaozeye** [desktop/desktop#8005]
Is there any version that supports 32-bit Windows system 'cos I think I did install GitHub Desktop successfully on a x86 Windows system months ago.

**Comment by shiftkey** [comment]
@yaozeye thanks for the feedback!

We don't ship a 32-bit version of GitHub Desktop on Electron, so you might be thinking of the previous GitHub for Windows app. The earlier discussion #1214 has some extra context behind why we're not planning to ship a 32-bit version in the near term.
