### ISSUE TITLE
Can't find atom beta

### ISSUE THREAD

**Issue by UziTech** [desktop/desktop#8010]
## Description

Can't find atom beta

![image](https://user-images.githubusercontent.com/97994/61764494-17126e80-ad9f-11e9-8ed5-1289d5aa0b07.png)

This might be due to the exe being renamed from `atom.exe` to `atom-beta.exe`
https://github.com/atom/atom/pull/17813

## Version

* GitHub Desktop: 2.1.0

* Operating system: Windows 10

## Steps to Reproduce
1. Click "Open in Atom"

### Expected Behavior

Opens atom beta

### Actual Behavior

shows error above

## Additional Information

https://github.com/atom/atom/issues/19696

**Comment by Rexogamer** [comment]
I would believe that this is due to the rename of Atom Beta/Nightly.

**Comment by mfonville** [comment]
I think there should be separate entries in https://github.com/desktop/desktop/blob/development/app/src/lib/editors/win32.ts for stable, beta and nightly.
That would also offer the user the possibility to choose between them if they are installed alongside each other

**Comment by Rexogamer** [comment]
> I think there should be separate entries in https://github.com/desktop/desktop/blob/development/app/src/lib/editors/win32.ts for stable, beta and nightly.
> That would also offer the user the possibility to choose between them if they are installed alongside each other

Sounds good to me!

**Comment by Rexogamer** [comment]
Anyone know the `SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\atom` equivalent for Nighty/Beta?

**Comment by Rexogamer** [comment]
pinging @UziTech

**Comment by tierninho** [comment]
@UziTech Was Atom working fine until the rename? In general when this happens to me, I quit and restart Desktop and it usually "finds" Atom. 

What versions of Desktop, Windows, and Atom are you using? Thanks.

**Comment by Rexogamer** [comment]
@UziTech @tierninho if you’re using Beta or Nightly this should be fixed in #8011

**Comment by UziTech** [comment]
@tierninho Yes it was working fine until I updated atom to 1.40.0-beta0

**Comment by Rexogamer** [comment]
> @tierninho Yes it was working fine until I updated atom to 1.40.0-beta0

That, I believe, was when the exe file was renamed. So it should work fine in the next beta of Desktop (either 2.1.1 beta 3, or 2.2 beta 1).
