### ISSUE TITLE
Stuck at the Let's Get Started screen

### ISSUE THREAD

**Issue by GraemeBennett** [desktop/desktop#8016]
**Issue:**
It's possible (in my case, after deleting an old account and signing into GitHub.com with a new one) to get stuck on the "Let's get started" screen with no obvious way to move forward to the actual GitHub desktop screen.

**Expected behavior:**
Expect to see some way to get to the GitHub Desktop screen with the dark top bar.

**Actual behavior:**
The only way to get to the GitHub Desktop screen (with the file menu etc.) was to create a new repository.  This seems completely unintuitive and stumped several people, all of which observed that I had done everything right, and had done it in the right order.

**Recommended mitigation:** 
Surface a sign-out button if an account is present in a currently signed-in state. 

**Notes:** 
When I eventually got to the GitHub desktop's file menu, it revealed that I was still signed in with the now-deleted account name. I was already signed in to GitHub.com with the correct account; the desktop app should have noticed that this didn't match its current state.

**Repro steps:** 
Create an account that's not on corpnet by correctly following all steps, including MFA. Delete the account, delete OAUTH keys, Uninstall GitHub Desktop and all subsequently installed GIT tools, reboot, sign out of GitHub online, but do not sign out of GitHub desktop. and then attempt to use a new corpnet account to complete all of the install, sign-in, MFA and setup steps.
Then try to clone a repo (or anything else except create new repo).

**Comment by tierninho** [comment]
@GraemeBennett Apologies for the confusing experience! I agree we ought to have some confirmation of the user account on the Lets Get Started page. 

Our intention was that each user would go through the sign up process and then reach the Lets Get Started page. Obviously, we failed to account for your experience.

Desktop does store the authentication despite uninstalling the app. You have to wipe Desktop completely by clearing the storage, or signs out then uninstall. 

I will suggest this to the team:

![Screen Shot 2019-07-24 at 11 14 11 AM](https://user-images.githubusercontent.com/14828183/61829245-2f68a480-ae04-11e9-8722-16e56730037a.png)

Add confirmation of a signed in user by including the handle here ☝️ . If the user is signed out, add a `sign-in` button after "Let's Get Started" text. 

This is not the first time this issue has occurred, so I hope we can improve on future iterations of Desktop.

cc @desktop/design

**Comment by steveward** [comment]
I'm 👍 on adding a sign in option -- I've had a couple of reports via ZD where new users skip the auth step and then aren't sure how to proceed since they aren't logged in and can't clone their existing repositories.

**Comment by outofambit** [comment]
> Add confirmation of a signed in user by including the handle here ☝️ . If the user is signed out, add a sign-in button after "Let's Get Started" text.

@tierninho i like this approach!

**Comment by billygriffin** [comment]
Because we've seen this come up several times and Windows users have looked for the menu item in every scenario. Therefore to solve this in a super lightweight iterative way, we're just going to add back the menu bar on Windows on this screen, and therefore people will be able to access the sign in portion.

**Comment by grovesben** [comment]
Is there a fix for this yet? I am currently stuck on the Let's get started! screen..

**Comment by DS-Saurabh** [comment]
@GraemeBennett 
 Could GitHub Desktop possibly be in fullscreen mode? Try hitting F11 to see if that brings the menus back into view.
