### ISSUE TITLE
can't commit with already login

### ISSUE THREAD

**Issue by SilverLeaves** [desktop/desktop#8019]
## Description

It works yestoday, but today...

![图片](https://user-images.githubusercontent.com/31165554/61839597-c6933200-aec0-11e9-9cfc-eca366e099bb.png)

## Version

* GitHub Desktop: 2.1.0

* Operating system: windows 10 1903

## Steps to Reproduce

jsut commit your change

### Expected Behavior

commit  successful!
### Actual Behavior

![图片](https://user-images.githubusercontent.com/31165554/61839594-c3984180-aec0-11e9-84f7-094f36023197.png)

### Logs

[2019-07-25.desktop.production.log](https://github.com/desktop/desktop/files/3429411/2019-07-25.desktop.production.log)

**Comment by tierninho** [comment]
@SilverLeaves Thank you for filing this.

What happened when you ran the two commands? You can also opt to set your git credentials under the Options menu > Git tab.

Also, please submit your logs --- see the Help menu.

**Comment by SilverLeaves** [comment]
> What happened when you ran the two commands? You can also opt to set your git credentials under the Options menu > Git tab.


![图片](https://user-images.githubusercontent.com/31165554/61840321-5508b300-aec3-11e9-8bb7-b99b76865059.png)

![图片](https://user-images.githubusercontent.com/31165554/61840367-81243400-aec3-11e9-96c2-a16a8fc68b31.png)

I tryed, But it didn't work. even reinstall git and github desktop.

**Comment by SilverLeaves** [comment]
> Also, please submit your logs --- see the Help menu.

[2019-07-25.desktop.production.log](https://github.com/desktop/desktop/files/3429411/2019-07-25.desktop.production.log)

**Comment by steveward** [comment]
@SilverLeaves can you go to File Explorer and navigate to `C:\Users\Silver\` and open the `.gitconfig` file located there? 

The entries should look like this in that file:

```
[user]
	name = Your Name
	email = your@email.com
```

Is it possible that there are read/write permission issues that are causing these values to not get written to that file? Generally an error would be thrown in that case, but that's one thing we have seen in the past.

**Comment by tierninho** [comment]
@SilverLeaves Thanks for the information.

There might not be a local setting for your git credentials. Go to your repo in the command line and run `git config --local -l`. If you do not see your name/email there, run:

- `git config user.email autumnsilverleaves@gmail.com`
- `git config user.name SilverLeaves`

That should do it. 

---

An alternative solution is:

You can solve the problem with the global solution, but firstly I want to describe the solution for each project individually, cause of trustfully compatibility with most of Git clients and other implemented Git environments:

Individual Solution
Go to the following location:

`Local/repo/location/.git/`

open "config" file there, and set your parameters like the example (add to the end of the file):

```
[user]
    name = YOUR-NAME
    email = YOUR-EMAIL-ADDRESS
```

**Comment by SilverLeaves** [comment]
@steveward 
![图片](https://user-images.githubusercontent.com/31165554/61918719-f6a40900-af84-11e9-8530-ee485eaa1eb2.png)


> Is it possible that there are read/write permission issues that are causing these values to not get written to that file? Generally an error would be thrown in that case, but that's one thing we have seen in the past.

I use vscode to commit  my change. when commit,  login my account and vscode works, then the change submited.  so maybe the issue not cause read/write permission, because vscode use git directly.

**Comment by SilverLeaves** [comment]
I don't know why. now it can work.

I will close this issue, thank you very much!

**Comment by tierninho** [comment]
Thanks for the update @SilverLeaves !!
