### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by LBarrionuevo** [desktop/desktop#8022]
## Description

I have two github accounts, one for my company and another for personel use, I 've changed my account from company to personel on Chrome then I changed from personel to company and now I am not able to clone my company repository due to not found repository

## Version

* GitHub Desktop:

* Operating system:

**Comment by shiftkey** [comment]
@LBarrionuevo I've updated your comment to include the bug report template.

Please fill that out so we can understand more about your situation. Any current log files will also be helpful to diagnose the issue, available from the **Help** | **Show Logs in Finder/Explorer** menu item.

**Comment by LBarrionuevo** [comment]
@shiftkey I fix using git remote set-url origin https://username:password@github.com/repository
