### ISSUE TITLE
Filename too long on clone on Windows 10

### ISSUE THREAD

**Issue by luveti** [desktop/desktop#8023]
## Description
Unable to clone repo with long file paths

## Version

* GitHub Desktop: **2.1.0**
* Operating system: **Windows 10 Version 1903**

## Steps to Reproduce
1. Clone a repo with long file paths (pretty much any older node project should do... 🙂 )

### Expected Behavior
It should properly handle long file paths on Windows

### Actual Behavior
It doesn't handle long file paths ☹

## Additional Information
I would copy and paste the path here but it looks like text selection is disabled in that dialog.

Here's a screenshot instead:
![image](https://user-images.githubusercontent.com/4952718/61890405-6490f780-aed5-11e9-8c7a-473123ba3850.png)

**Comment by shiftkey** [comment]
@luveti thanks for the report!

Because of a Windows API limit paths longer than `MAX_PATH` (260 characters) on Windows are not supported by default in Git for Windows, which is used in Desktop. [This document](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file) talks about the limitation and the workaround (using the extended-length path syntax).

Have you set `core.longpaths` to `true` before cloning to opt-in for using the extended-length path support?

```
$ git config --global core.longpaths true
```

There's some caveats to this from the [Git for Windows documentation](https://github.com/git-for-windows/git/blob/d003d728ffa6c0006da875ec6318d3f6b28a4ddb/Documentation/config/core.txt#L560-L565) which is why we don't enable this by default:

```
core.longpaths::
	Enable long path (> 260) support for builtin commands in Git for
	Windows. This is disabled by default, as long paths are not supported
	by Windows Explorer, cmd.exe and the Git for Windows tool chain
	(msys, bash, tcl, perl...). Only enable this if you know what you're
	doing and are prepared to live with a few quirks.
```

**Comment by luveti** [comment]
It worked! I had previously used `git config --system core.longpaths true`, but it makes sense that this wouldn't work since you guys are using your own copy of Git for Windows.

I know you guys are trying to keep the interface simple for beginners, but it would be awesome if you had another section or tab for setting config values!

**Comment by shiftkey** [comment]
> I had previously used `git config --system core.longpaths true`, but it makes sense that this wouldn't work since you guys are using your own copy of Git for Windows.

I'm glad you were able to work around it.

For extra context: `system` level config is associated with a specific Git distribution, and you're correct that it wasn't used by Desktop (because it's installed to a different location). `global` config will override `system`, and all Git distributions installed on your machine will look there for config.

> I know you guys are trying to keep the interface simple for beginners, but it would be awesome if you had another section or tab for setting config values!

Please open an issue to discuss this further - maybe there's some areas we can improve things like this!

**Comment by sarang13579** [comment]
> @luveti thanks for the report!
> 
> Because of a Windows API limit paths longer than `MAX_PATH` (260 characters) on Windows are not supported by default in Git for Windows, which is used in Desktop. [This document](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file) talks about the limitation and the workaround (using the extended-length path syntax).
> 
> Have you set `core.longpaths` to `true` before cloning to opt-in for using the extended-length path support?
> 
> ```
> $ git config --global core.longpaths true
> ```
> 
> There's some caveats to this from the [Git for Windows documentation](https://github.com/git-for-windows/git/blob/d003d728ffa6c0006da875ec6318d3f6b28a4ddb/Documentation/config/core.txt#L560-L565) which is why we don't enable this by default:
> 
> ```
> core.longpaths::
> 	Enable long path (> 260) support for builtin commands in Git for
> 	Windows. This is disabled by default, as long paths are not supported
> 	by Windows Explorer, cmd.exe and the Git for Windows tool chain
> 	(msys, bash, tcl, perl...). Only enable this if you know what you're
> 	doing and are prepared to live with a few quirks.
> ```



> @luveti thanks for the report!
> 
> Because of a Windows API limit paths longer than `MAX_PATH` (260 characters) on Windows are not supported by default in Git for Windows, which is used in Desktop. [This document](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file) talks about the limitation and the workaround (using the extended-length path syntax).
> 
> Have you set `core.longpaths` to `true` before cloning to opt-in for using the extended-length path support?
> 
> ```
> $ git config --global core.longpaths true
> ```
> 
> There's some caveats to this from the [Git for Windows documentation](https://github.com/git-for-windows/git/blob/d003d728ffa6c0006da875ec6318d3f6b28a4ddb/Documentation/config/core.txt#L560-L565) which is why we don't enable this by default:
> 
> ```
> core.longpaths::
> 	Enable long path (> 260) support for builtin commands in Git for
> 	Windows. This is disabled by default, as long paths are not supported
> 	by Windows Explorer, cmd.exe and the Git for Windows tool chain
> 	(msys, bash, tcl, perl...). Only enable this if you know what you're
> 	doing and are prepared to live with a few quirks.
> ```

Thank you very much, it worked. You have relieved me of a great headache

**Comment by cromero-wincomplm** [comment]
https://stackoverflow.com/questions/34565238/where-does-github-desktop-install-command-line-version-of-git

If you dont find git.exe check this article

**Comment by AraHaan** [comment]
I would like for there to be 2 versions of github desktop for those of us who install Visual Studio 2022 (which installs git for windows for us): A build that does not bundle in git for windows, along with a build that does.

That way if we enable this on the ones that we either manually installed or the one that VS2022 installed it would be preserved with the updates to github desktop.

**Comment by d-kleine** [comment]
For anyone else still having this problem even having set `core.longpaths` to `true` for Git on **Windows**: you might also to need to change the shell setting for Git in the **GitHup Desktop app** (*File* -> *Option* -> *Integrations* -> *Shell*). 

I was always running into errors when cloning large repos with multiple subrepos like [pytorch/pytorch](https://github.com/pytorch/pytorch). In the GitHub Desktop app, I have changed the shell from `Command Prompt` to `Git Bash`. 

Using this **Git Bash** shell setting, the cloning process now runs smoothly and without any errors or issues.

**Comment by saiteja-in** [comment]
doing this worked for me

git config --system core.longpaths true
