### ISSUE TITLE
always show repository list

### ISSUE THREAD

**Issue by amanpatel** [desktop/desktop#8024]
I think it wouldn't be inaccurate to say that most of us work on more than 1 repository at a time. I believe GitHub desktop can be made more useful if the Repository list sidebar would always be visible. This would allow a much quicker way to switch between repositories. It would also ensure that all repo status (unstaged changes) would be visible at all times.

Proposed Solution: Add a preference or a togglable option in the "View" menu that reads: "Always show repository list". Alternatively a pin icon in the user interface could accomplish the same thing while keeping the preferences and menu clean.

**Comment by shiftkey** [comment]
@amanpatel thanks for the feedback!

We had an earlier discussion about this in #1593 but we wanted to look at the bigger picture about the repository list itself. In the 2.0 release we shipped some changes to how repositories are organized, and you can read more about that in #6460.

I'm going to defer to @desktop/product here about whether they want to keep this issue open, but for the moment we're currently focused on iterating and learning from what we recently shipped.

**Comment by amanpatel** [comment]
Its discussed at length! Wow.  I'll go ahead and close this.
