### ISSUE TITLE
GitHub is now showing pull request commits issue graph

### ISSUE THREAD

**Issue by sakshamtaneja21** [desktop/desktop#8030]
**Please describe the problem you think should be solved**
A clear and concise description of what the problem is and who else might be impacted. Screenshots are encouraged.

Github is not showing this type of graph
![graph](https://user-images.githubusercontent.com/43172716/61948191-c1b7a680-afc4-11e9-800f-d25081b4b369.png)

**Comment by steveward** [comment]
@sakshamtaneja21 for specific issues with GitHub (the website) you will need to reach out to [GitHub Support](https://github.com/contact). This issue tracker is for GitHub Desktop -- if you have any questions or issues related to that please let us know!
