### ISSUE TITLE
I can't push to my new repository

### ISSUE THREAD

**Issue by kogorman** [desktop/desktop#8031]
## Description
I just created a new project on my desktop, and a new repository on GitHub.  I'm running from Xubuntu Linux, not using GitHub Desktop, just a Bash command-line.

 I'm trying to follow the directions that are showing in the new repo, and everything goes okay up until

git push -u origin master

Where I get an error about access rights

## Version

* GitHub Desktop: none

* Operating system: Xubuntu 18.04.2 LTS

## Steps to Reproduce
This is a copy of what's in my terminal:

kevin@camelot-b:~/Desktop/Projects/Guess$ git ls-files
.gitignore
LICENSE
README
guesser.py
knuth-mastermind.pdf
knuth-solution.csv
kevin@camelot-b:~/Desktop/Projects/Guess$ git ls-files
.gitignore
LICENSE
README
guesser.py
knuth-mastermind.pdf
knuth-solution.csv
kevin@camelot-b:~/Desktop/Projects/Guess$ git status
On branch master
nothing to commit, working tree clean
kevin@camelot-b:~/Desktop/Projects/Guess$ git log
commit 08f94810672f0177f3230ab7fd481e29ed34dd76 (HEAD -> master)
Author: Kevin O'Gorman <kogorman@gmail.com>
Date:   Fri Jul 26 13:09:33 2019 -0700

    first commit
kevin@camelot-b:~/Desktop/Projects/Guess$ git push -u origin master
Warning: Permanently added the RSA host key for IP address '192.30.255.113' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
kevin@camelot-b:~/Desktop/Projects/Guess$ 

### Expected Behavior
I expected my repo to be sent to GitHub

### Actual Behavior
An error related to access rights

### Logs
I'm not aware of a relevant log file.

**Comment by tierninho** [comment]
@kogorman Please reach out to support@github.com as this repo is only for Desktop users. Thanks.
