### ISSUE TITLE
No tags option on push or pull

### ISSUE THREAD

**Issue by Schenn** [desktop/desktop#8034]
there's no option for using tags when pushing or pulling from github in GitHub Desktop.  There should be an option under pull / push from remote that lets you sync tags as well considering how release tags are done.

**Comment by tierninho** [comment]
@Schenn Thanks for filing, however this is a duplicate request. Please follow along at https://github.com/desktop/desktop/issues/4829

**Comment by PayumoneyGithubUploads** [comment]
is there any documentation available to work with TAGs.
