### ISSUE TITLE
Allow git init --separate-git-dir

### ISSUE THREAD

**Issue by NotDeadYetDev** [desktop/desktop#8035]
I would love a way to do "git init --separate-git-dir <git dir>" through the GitHub Desktop GUI.  Allow us the option of providing the repo location that is at a different location than the project. 

OR does this already exist and I am just blind?

**Comment by shiftkey** [comment]
@NotDeadYetDev this isn't currently supported, and there's some extra information that I'd love to gather at this stage:

 - I want to hear more about _why_ and _how_ this would help with your normal workflows, so we can understand it's value
 - It's also not clear to me how many users are interested in this flag - please add a 👍 to the original issue, or add a comment if you have additional information to share

**Comment by NotDeadYetDev** [comment]
@shiftkey  I will try to answer the Why/How with an example:  My normal development version control was Sorcesafe and SVN so this might just be a "bad habit" from them.  I have my projects on my C:\Dev\foo  (c: is an SSD) and my Version controls "repos" are on Q:\Dev\foo (q: is a NAS).  It just "feels wrong" to have a repo not on the NAS but I don't want the speed hit of having the "work area" on the same NAS.  Some have said just have a repo on c: and then make a remote repo on q:  That seems wrong to me.  Seeing how there is a way to do this with  "git init --separate-git-dir " I assume there would be a need/desire to have that functionality in a git GUI.

As for "Are you able to workaround this issue currently in Desktop by adding an existing repository created in this way?" yes, it is painful and ugly but yes.

Thank you for the reply.

**Comment by billygriffin** [comment]
Hi @NotDeadYetDev, this is a really specific use case that we haven't seen come up before, so unfortunately we won't be able to support it. GitHub Desktop isn't intended to provide options for every piece of Git functionality, but rather make the most common workflows extremely simple and easy to use. Glad you're able to find a workaround here, and sorry we aren't able to solve this issue for you. Thanks for suggesting though!
