### ISSUE TITLE
Gituhub desktop not opening on Ubuntu v18

### ISSUE THREAD

**Issue by rahulbhardwaj94** [desktop/desktop#8037]
Hi, i am rahul.
i just downloaded github desktop on Ubuntu v18 & it's not opening ...
i checked the app store page, some comments say its not working when they updated their ubuntu desktops.
It's not opening..

**Comment by shiftkey** [comment]
@rahulbhardwaj94 please direct all support issues about GitHub Desktop on Linux over to @shiftkey's fork: https://github.com/shiftkey/desktop.
