### ISSUE TITLE
Error code 128 gitconfig setting

### ISSUE THREAD

**Issue by Havie** [desktop/desktop#8041]
So I am brand new ish to git

I installed git hub desktop,
signed into my account and tried to clone a repo

When I try to commit it for the first time I get this error code message 128 about identifying who i am

Upon googling- it says the solution is to go to file-->options and update your email address

No matter what I type in there- you cant click the save button it doesnt matter,
so i got into my settings thru the website and turned off the @noreply.github email to show my public email, now the file-->options email shows my correct email,
however the error persists.

![ErrprAGAOM](https://user-images.githubusercontent.com/38088407/62021214-c24e6980-b18b-11e9-8f62-63d756775a4b.PNG)

I have signed in and out and closed the application multiple times..
what is the deal?

**Comment by steveward** [comment]
Thanks for the report @Havie. Another user recently ran into this issue in https://github.com/desktop/desktop/issues/8019. 

Can you go to `C:\Users\<Your_User>` and open the `.gitconfig` file located there? Make sure there is an entry there that looks like this:

```
[user]
	name = Your Name
	email = your@email.com
```

Let me know what that shows.

**Comment by Havie** [comment]
Hello steveward,

I went to c/user/myusername

and theres tons of folders here , but no sign of .gitconfig file.

Can i make one? what else do u need to put inside of it?

**Comment by Havie** [comment]
I have tried adding a custom gitconfig to windows/system32/drivers/etc
because I have seen people reference an etc folder that needs this, also doesnt work

**Comment by Havie** [comment]
Found an etc under C:\Program Files\Git\etc
added a sample gitoncfig there, same issue

**Comment by shiftkey** [comment]
@Havie 

> and theres tons of folders here , but no sign of .gitconfig file.

Check that you have [Show hidden files](https://support.microsoft.com/en-ca/help/14201/windows-show-hidden-files) enabled for Windows Explorer, as files starting with a `.` may be hidden from you.

> Found an etc under C:\Program Files\Git\etc
> added a sample gitoncfig there, same issue

This is not the right place to make the change, and won't be detected by Desktop.

**Comment by tierninho** [comment]
@Havie Since you are having trouble finding the file, open up the command line, and type:

`git config user.email your-email-address`
`git config user.name your-username`

Be sure to substitute the email and username above. That should do it.

**Comment by steveward** [comment]
@Havie I'm going to close this issue out due to inactivity -- if you are still having problems configuring your name and email please let us know!

**Comment by Havie** [comment]
I gave up, thanks tho.

I got this working via sourcetree , cant use github desktop no mater what

**Comment by steveward** [comment]
@Havie if Sourcetree is able to find your .gitconfig then GitHub Desktop should as well since they would both use the same config files. Did you try running the commands that @tierninho gave?
