### ISSUE TITLE
GitHub Desktop focus on some command line actions

### ISSUE THREAD

**Issue by Seb33300** [desktop/desktop#8042]
Sometimes I have to use command line for some specific actions, for example when I want to rebase my fork from upstream but it's like some git actions will automatically trigger GitHub Desktop to get the focus.

Every time I do `git fetch upstream` or `git rebase`, GitHub Desktop will automatically get the focus on top of my command line window (or starts and get the focus if the application is not launched already).
So this force me to always switch back on my command line window.

Is it a bug ? Or any way to disable this?

I am using GitHub Desktop on Windows 10.

**Comment by shiftkey** [comment]
> Is it a bug ? Or any way to disable this?

I'm not familiar with this behaviour. Are you able to put together a GIF or video of this issue to illustrate the issue? 

I'm also going to try and reproduce this myself because I'm not sure how or why those two would interact.

**Comment by shiftkey** [comment]
@Seb33300 I've not been able to reproduce this with Desktop 2.1.0 on Windows 10

> (or starts and get the focus if the application is not launched already)

This feels like it's https://github.com/desktop/desktop/issues/2962 and it's related to some external program trying to launch `github` (which is on PATH as the shortcut to launch Desktop). With the old version of the app this program would act as a credential provider, but the latest version does not support this.

It's not clear to me what other tools you have in your environment, but I suspect something is configured to trigger this.

**Comment by tierninho** [comment]
@Seb33300 As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by Seb33300** [comment]
@shiftkey 

`C:\Users\xxx\AppData\Local\GitHubDesktop\bin` is in my `PATH`.
I don't remember if I added it by myself or not.
Is this path added by GitHub Desktop install?

Do I have any way yo find which is the application triggering github?

**Comment by outofambit** [comment]
hi @Seb33300, `C:\Users\xxx\AppData\Local\GitHubDesktop\bin` is indeed on your path (added by the GitHub Desktop installer), but that should only be triggered by calls to the `github` command.

i don't have a way to trace what process might be triggering this. it could be a number of things in your environment (shell configs, git configs, other programs).

@desktop/support have you had any experience with cases like this?

**Comment by steveward** [comment]
@Seb33300 do the commands you are running (i.e. `git fetch upstream`) succeed despite GitHub Desktop taking focus?

**Comment by Seb33300** [comment]
@steveward yes
