### ISSUE TITLE
Create shortcut for discard changes

### ISSUE THREAD

**Issue by Benjamin-Lee** [desktop/desktop#8050]
**Please describe the problem you think should be solved**

Please add a shortcut for discarding changes (not just all changes as in #7588)

Example:
![image](https://user-images.githubusercontent.com/13618205/62152613-e2d40c00-b2d0-11e9-80f0-bbd4c17e779f.png)

**[Optional] Do you have any potential solutions in mind?**

If it's of any value, when I tried to guess the shortcut, I did cmd+delete and was surprised to see that it was the shortcut for removing the repository. I, for one, discard changes to selected files more often than I remove repositories.

**Comment by tierninho** [comment]
@Benjamin-Lee Thanks for filing. 

>  I, for one, discard changes to selected files more often than I remove repositories.

Good point 👍. However, there are no plans to make any changes unless we hear similar feedback.

**Comment by billygriffin** [comment]
Hi @Benjamin-Lee - as @tierninho mentioned, this is the first time we've heard this request. In addition, I'm a little concerned with how it might be unintuitive or destructive just because it depends on so much state (like which file you have selected). I'm going to close this for now, but we're open to revisiting if we hear more feedback that it's something people are struggling with. Thanks for the request!

**Comment by 20dka** [comment]
Hey, at the moment I'm trying to find out what broke my build and I just overwrote everything with a known good build and am pressing "Discard changes" one by one to see where it actually breaks, and I support adding a shortcut for this feature. Or if you're not sure about the consequences maybe it could be optional, or be part of a shortcut mapper in the Options

**Comment by shopblocks** [comment]
After switching from Tower to try Github Desktop, this is one of the shortcuts I miss the most. Discarding changes on a single file via keyboard is super-useful.

**Comment by Aryaman73** [comment]
Would like to echo this - definitely would be a great feature to have! @billygriffin I definitely agree that it isn't too intuitive, but (a) I still think its usefulness overshadows this, and (b) GitHub desktop has a shortcut to nuke an entire repository,  so this is definitely not as destructive as that. 🙃

**Comment by RiversJohn** [comment]
Would really like this to be considered again, discard selected files but do it much like sourcetree does, it pops up a window listing files that contain changes to be discarded, hitting the hotkey + enter but not having it be instant misclick disaster is a great balance between safety and ease of use.

**Comment by steveward** [comment]
Requested in https://github.com/desktop/desktop/issues/16180.

**Comment by thennothinghappened** [comment]
We've currently got a shortcut for removing the repo, and its bound to the shortcut I'd expect this to be bound to, and has a message prompt very similar to it. The result of that is I pretty often accidentally remove my repo from Desktop and have to go find it again.

Personally, I feel that discarding changes is a _far_ more common action, and I don't see why this has been closed. _Having_ a shortcut hurts absolutely no-one, so long as you can customise it - another thing Desktop is lacking.

**Comment by adnaneh** [comment]
> We've currently got a shortcut for removing the repo, and its bound to the shortcut I'd expect this to be bound to, and has a message prompt very similar to it. The result of that is I pretty often accidentally remove my repo from Desktop and have to go find it again.
> 
> Personally, I feel that discarding changes is a _far_ more common action, and I don't see why this has been closed. _Having_ a shortcut hurts absolutely no-one, so long as you can customise it - another thing Desktop is lacking.

That's a great point, I've opened a PR to add a new shortcut to do this: https://github.com/desktop/desktop/pull/21164 via Cmd+D then enter to confirm. @billygriffin @thennothinghappened @steveward
