### ISSUE TITLE
View on GitHub button is disabled for an existing project in GitHub

### ISSUE THREAD

**Issue by aybe** [desktop/desktop#8051]
## Description

The View on GitHub button is disabled for a repository that exists in GitHub.

## Version

* GitHub Desktop: 2.1.0
* Operating system: Microsoft Windows [Version 10.0.18362.207]

### Expected Behavior
The button should not be disabled.

### Actual Behavior
The button is disabled.

## Additional Information

I've tried everything, 

- remove the repository from the application
- remove the origin
- delete repository in site then publish it again
- reinstall the application

All things restarting the application to see if it would help but it just didn't.

I've deleted the log, removed the repository, restarted the application and added the repository again; there is clearly an error in the log.

Also please note this is a private repository but so far I didn't have any problem with other private repositories I've created before.

### Logs

[2019-07-30.desktop.production.log](https://github.com/desktop/desktop/files/3448485/2019-07-30.desktop.production.log)

**Comment by tierninho** [comment]
@aybe Thanks for filing. Is the menu completely blacked out like so? 

<img width="814" alt="62132859-3d12a400-b2b4-11e9-85dc-f92c8bacebfc" src="https://user-images.githubusercontent.com/14828183/62158363-f0769b00-b2aa-11e9-8984-79fb888bbb56.png">

If so, we are investigating this over in https://github.com/desktop/desktop/issues/7991

**Comment by aybe** [comment]
No it is not.

Le 30 juil. 2019 21:19, Tiernan L <notifications@github.com> a écrit :

@aybe<https://github.com/aybe> Thanks for filing. Is the menu completely blacked out like so?

[62132859-3d12a400-b2b4-11e9-85dc-f92c8bacebfc]<https://user-images.githubusercontent.com/14828183/62158363-f0769b00-b2aa-11e9-8984-79fb888bbb56.png>

If so, we are investigating this over in #7991<https://github.com/desktop/desktop/issues/7991>

**Comment by aybe** [comment]
In fact it's like that:

![GitHubDesktop_2019-07-30_21-01-17](https://user-images.githubusercontent.com/1537591/62163383-8564ad00-b31a-11e9-9eb0-856be657f83b.png)

Also please note that other repository are working perfectly.

**Comment by tierninho** [comment]
Thank you for the update. Looks like the repository is failing to fetch and insert into the database. 

```
2019-07-30T19:09:13.376Z - warn: [ui] fetchRepository: 'aybe/ZeroAG' returned a 404
2019-07-30T19:09:13.911Z - warn: [ui] Unable to fetch issues for aybe/ZeroAG
Error: Cannot get issues for a repository that hasn't been inserted into the database!
```

Looks another user had the same issue and fixed it by doing this: https://github.com/desktop/desktop/issues/5717#issuecomment-424303252

**Comment by aybe** [comment]
Problem fixed, thanks ! 💯
