### ISSUE TITLE
How to resolve LFS conflict?

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#8054]
I got the same issue as this one #7166: I can't resolve LFS file conflict in GitHub Desktop, but I can resolve conflict for text and non-LFS binaries in GitHub Desktop.
I found there are two issues for LFS conflict resolve:
1. **LFS conflict detection**: GitHub Desktop will detect LFS incorrectly, it detected the LFS file in conflict state, but it thought there is no conflicts in the file, treat it as resolved. I think it's because when it getConflictDetails, both getFilesWithConflictMarkers and getBinaryPaths return 0.
![image](https://user-images.githubusercontent.com/5396286/62222483-06d54180-b3e6-11e9-849a-ded91161495a.png)

2. **LFS conflict resolve**: I tried to use both manual resolution(for binary conflict) and conflict markers resolution (for text conflict) to resolve the LFS conflict, none of them succeed.

Do you have any ideas for the two issues above?

**Comment by billygriffin** [comment]
Hi @TerryChan, we try to keep issues to a single issue tracking a problem, so I'm going to close this in favor of #7166. Thanks!
