### ISSUE TITLE
Binary conflict resolve doesn't work

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#8059]
## Description

When I pull repository from remote, there is conflict for an image. When I resolve the conflict with accept the remote branch in GitHub Desktop, and then commit and push, the result isn't expected, it's  still the image in my local, not the image of remote.
![image](https://user-images.githubusercontent.com/5396286/62279126-0c7d6680-b47c-11e9-9e40-c1dd3dc71862.png)

## Version

* GitHub Desktop: 2.1.0

* Operating system: Windows 10

## Steps to Reproduce

1. commit changes for 1.png
2. pull from remote which has changes for 1.png
3. show the conflict dialog for 1.png
4. chose "use the modified file from origin/xxx"
5. commit merge, and push

### Expected Behavior

the image is the remote one

### Actual Behavior

it's still the local one, didn't change

## Additional Information

Even for banch merge, such as merge master into branch1, the image conflict resolve doesn't work either.

**Comment by TerryChan** [comment]
Is this a complete feature? - I mean resolve binary conflict. 
I found there was a good discussion #6062, but I can't resolve binary conflict in GitHub Desktop

**Comment by TerryChan** [comment]
I think this is not a complete feature for resolving binary conflict. I found the code only stage binary conflict files when Commit Merge clicked, and do nothing else.
I think you need to execute the command below before stage binary conflict files:
`git checkout --theirs -- path/to/conflicted-file.txt`
`#or`
`git checkout --ours -- path/to/conflicted-file.txt`
As @shiftkey mentioned here https://github.com/desktop/desktop/issues/6062#issuecomment-434793215
The commands above can resolve the binary conflict issue, and can also resolve the LFS conflict issue, as bug #7166 metioned

**Comment by outofambit** [comment]
hi @TerryChan that's a really good find, thank you! you're diagnosis is completely right. i put up the fix at #8060, would you be willing to try it out and see if it fixes it for you? thanks again!

**Comment by TerryChan** [comment]
I have verified, it works for me, and it can resolve both normal binary conflict, and LFS conflict. Thanks

**Comment by IFW-OMS** [comment]
This issue appears to still exists in the current release of Github Desktop (2.5.6)

**Comment by lemonaidvkussakov** [comment]
The issue still exists and I am struggling.
