### ISSUE TITLE
Binary file conflict resolution error message

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#8061]
When resolving a conflict for a binary file, I noticed two things not consistent with the normal flow of a conflict when dealing with non-binary files.

We surface a message stating the conflict must be resolved via the command line, yet when you go to the conflict modal, you can select the file from source A or B and avoid the command line. 

Recommended text: "This file is in conflict and can be resolved via the command line or by returning to the conflict modal". Are there other binary file conflicts that cannot be resolved in the modal and that this message applies too?

![bug](https://user-images.githubusercontent.com/14828183/62320461-f18b0200-b43b-11e9-8fad-717bfb6b3e2e.png)

2.1.1-beta3, mac

**Comment by billygriffin** [comment]
Closing along with #8463 for the same reason https://github.com/desktop/desktop/pull/8463#issuecomment-542409559
