### ISSUE TITLE
Not all changed files are rendered.

### ISSUE THREAD

**Issue by philderbeast** [desktop/desktop#8064]
## Description
All but the last file in the changes list of files is displayed. The attached screenshot shows this with only two files but I've seen it with more. Only seen this today and have been a long time user of github desktop.

<img width="779" alt="Screen Shot 2019-08-02 at 12 06 46 PM" src="https://user-images.githubusercontent.com/633283/62383588-15267900-b51e-11e9-8d56-5bce54fd79f2.png">

Switching to another repository and back seems to help as does restarting. Here's the same view after switching repos away and back that now renders both changed files.

<img width="884" alt="Screen Shot 2019-08-02 at 12 12 46 PM" src="https://user-images.githubusercontent.com/633283/62383880-e4930f00-b51e-11e9-8ace-53a57384c8f9.png">

## Version
version 2.1.0

```
> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G7024
```

### Expected Behavior
I expect the list of changed files to be rendered in full.

### Actual Behavior
Only the last element of this list gets rendered.

## Additional Information

I don't have reproduction steps. I'm working on [flare-timing](https://github.com/BlockScope/flare-timing). I do notice an error in the `*.desktop.production.log`.

```
2019-08-02T16:10:54.135Z - error: [ui] Could not load new contents for syntax highlighting
Error: EISDIR: illegal operation on a directory, read
2019-08-02T16:10:54.136Z - error: [ui] Could not load old contents for syntax highlighting
Error: Git returned an unexpected exit code '128' which should be handled by the caller.'
    at ChildProcess.s.on (/webpack:/app/src/lib/git/spawn.ts:93:15)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:596:12)
```

### Logs

[2019-08-02.desktop.production.log](https://github.com/desktop/desktop/files/3462137/2019-08-02.desktop.production.log)

**Comment by tierninho** [comment]
@philderbeast Thanks for filing this. We have had two similar instances of this [here](https://github.com/desktop/desktop/issues/7691) and [here](https://github.com/desktop/desktop/issues/3568).

> `Could not load new contents for syntax highlighting Error: EISDIR: illegal operation on a directory, read`

EISDIR stands for "Error, Is Directory". This means that NPM is trying to do something to a file but it is a directory. Since the operation cannot be done the error is thrown.

By any chance, are you using submodules?

**Comment by philderbeast** [comment]
I am using two submodules `hcoord @ efee591` and `reflex-platform @ 299d4b5`. The former I added recently and, as can be seen in one of the screen shots, hcoord is marked as dirty.

**Comment by philderbeast** [comment]
The error stack dump for #7691 is exactly the same as here. I'm seeing a user interface glitch in the changes listing but with #7691 the error is seen in the devtools console log.

**Comment by tierninho** [comment]
Thank you for the update. We do not have a fix as of yet, so please follow along at https://github.com/desktop/desktop/issues/7691. 

Closing this issue for now.
