### ISSUE TITLE
Will not use system proxy settings

### ISSUE THREAD

**Issue by steskalja** [desktop/desktop#8067]
When I try to use the client behind a proxy server it does not work. It will not resolve GitHub.com

**Comment by steskalja** [comment]
![image](https://user-images.githubusercontent.com/20687346/62474899-eaccf980-b771-11e9-9c6f-23128dd1222f.png)

**Comment by outofambit** [comment]
hi @steskalja thanks for reaching out! this is a known issue for github desktop, please take a look at https://github.com/desktop/desktop/issues/2789#issuecomment-496798787 for a workaround. thanks!
