### ISSUE TITLE
Diff search keyboard shortcut conflicts with GitHub web site integration

### ISSUE THREAD

**Issue by nycdotnet** [desktop/desktop#8068]
## Description

There is a keyboard shortcut to open the repository on GitHub's website, which on Windows is CTRL+SHIFT+G.  There is also a keyboard shortcut to open the repo in the Finder or File explorer CTRL+SHIFT+F.  These used to work when viewing the history when the diff view was active.  Since (I'm assuming) https://github.com/desktop/desktop/pull/7866, CTRL+SHIFT+G and CTRL+SHIFT+F do not work in this scenario - CTRL+SHIFT+G instead opens the regex search in the diff view, and CTRL+SHIFT+F appears to do nothing.  It would be great if the SHIFT modifier would take precedence and instead open the repo/finder/file explorer when these combinations are pressed.

## Version

* GitHub Desktop: 2.1.0

* Operating system: Microsoft Windows [Version 10.0.17763.615]

## Steps to Reproduce

1. Commit some code in a repo that references an upstream on GitHub.
2. Edit some code and save.  On the "changes" screen, put your focus in the diff view (click into it).  Hit CTRL+SHIFT+G.  This used to open GitHub in your browser pointed to the repo.  It now opens the Regex diff search.  Hit CTRL+SHIFT+F.  This used to open your file explorer or finder pointed at the repo: it now appears to do nothing.
3. Click into the changes window so that the changed file's name is highlighted.  CTRL+SHIFT+G and CTRL+SHIFT+F now work as expected.
4. Click the History tab.
5. Click into the diff view.  Same issue - CTRL+SHIFT+F does nothing, CTRL+SHIFT+G opens the regex search.  These shortcuts work as expected if the changed files list or the commits list is focused.

### Expected Behavior
CTRL+SHIFT+F and CTRL+SHIFT+G should take precedence over CTRL+F and CTRL+G when SHIFT is pressed.

### Actual Behavior
CTRL+F and CTRL+G take precedence when the diff view is selected.

## Additional Information

Likely related to https://github.com/desktop/desktop/pull/7866

**Comment by tierninho** [comment]
@nycdotnet This sounds like an unintentional side effect, but I am unsure at this point. 

@niik You may have some thoughts on this as part of your work on #7866 ?

**Summary**: as we introduced `CTRL-F` after clicking into the diff view, it has altered or disabled `CTRL+SHIFT+F` and `CTRL+SHIFT+G`.

Was this intended? Thanks.

**Comment by nycdotnet** [comment]
@tierninho yes I believe that you're correct that this was an unintentional change.

**Comment by tierninho** [comment]
Labeling as a bug for now. Thanks for the input @nycdotnet

**Comment by niik** [comment]
> This sounds like an unintentional side effect, but I am unsure at this point.

@tierninho It definitely is, thanks @nycdotnet for letting us know about this. I forgot to disable these in the CodeMirror keymap when we turned on the search plugin. Turns out this is also a problem in the co-author input field (since it's a code mirror instance as well).

@probablycorey Do you mind if I steal this from you? I think I have a good idea of how to solve it quickly.

**Comment by probablycorey** [comment]
@niik please do! I still don't have my windows VM setup yet!

**Comment by nycdotnet** [comment]
ty!
