### ISSUE TITLE
How to implement stash multiple specifed files?

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#8072]
I want to implement stash multiple specified files with the command below:
`git stash push --include-untracked --message 'stashmessage' -- 1.txt 2.txt 3.txt`

I can execute the command in command line successfully but failed in GitHub Desktop.
command line:
![image](https://user-images.githubusercontent.com/5396286/62541120-b5b4ca00-b88b-11e9-9939-afa8832d1473.png)
I modified the method createDesktopStashEntry in GitHub Desktop, just append the files at the end of the command, but it failed with "No local changes to save". It succeed when there is only one file in the file list. Looks like it cannot recognize the file list.
![image](https://user-images.githubusercontent.com/5396286/62541164-cd8c4e00-b88b-11e9-8e29-dff866f512c8.png)
Do you know how to resolve this issue?

**Comment by erncat76** [comment]
I had no clue. Just kept try stuff. Thank you so much

**Comment by shiftkey** [comment]
@TerryChan I'd confirm the files are actually modified in the working directory at the time, because "No local changes to save" suggests the files might not have been modified at the time (or that this is being run in a different repository).

**Comment by outofambit** [comment]
hi @TerryChan! it looks like this is more of an issue with desktop/dugite and i see you've already filed https://github.com/desktop/dugite/issues/377 so i'm going to close this one and continue our discussion over there. thanks!
