### ISSUE TITLE
Open two different windows of GitHub Desktop on Windows 10

### ISSUE THREAD

**Issue by KnowledgeableKangaroo** [desktop/desktop#8074]
I would like to have two different repositories open in their respective desktop on windows 10. For example, Desktop 1 would have all the windows I need, including a window for GitHub Desktop, for Repository X. Desktop 2 would have all the windows I need, including a window for GitHub Desktop, for Repository Y. 

When I try right clicking on the icon, then clicking GitHub Desktop, nothing happens except the icon is highlighted orange and fades back to black.

**Comment by steveward** [comment]
Thanks for opening this @KnowledgeableKangaroo. This is a duplicate of #3606 so I am going to close this issue out and add your feedback there.

**Comment by KnowledgeableKangaroo** [comment]
Okay. Thank you.
