### ISSUE TITLE
Feature suggestion: Pinning repositories

### ISSUE THREAD

**Issue by basselch** [desktop/desktop#8075]
It would be nice if there was a way to pin certain repositories to the top of the repositories list for faster access. It would look exactly like the `Recent` section but it contains the repositories that the user manually pins by doing `Right Click -> Pin Repository` . Instead of the two sections in the picture below, there would be three: `Pinned` then `Recent` then the rest of the repos.

![pinned repos](https://user-images.githubusercontent.com/23396171/62626892-06cac980-b931-11e9-9387-3e9c8646b0f7.png)

**Comment by steveward** [comment]
Thanks for the feedback @basselch. This feature request was captured in #6460 (along with a number of other repository list improvements), so I'm going to close this issue out to help reduce open issues.

**Comment by billygriffin** [comment]
Just to add more to this, we decided that for now we’re going to stick with “Recent” as the way to navigate amongst repos frequently. We may revisit in the future, but have no plans at present to add the ability to pin a repo.
