### ISSUE TITLE
The autosetuprebase and conflictStyle settings in ~/.gitconfig can cause tests to fail

### ISSUE THREAD

**Issue by probablycorey** [desktop/desktop#8078]
I was having trouble getting the test suite to pass on the main branch. This was because I had these lines in my ~/.gitconfig.

```
# If these lines exists a dozen tests will fail!
[branch]
  autosetuprebase = always
```

It looks like it is problematic to rely on the user's `.gitconfig` file. A possible solution would be to unset the `HOME` env var in the test scripts, but I'm not sure how well that would work on windows.

-----

## Proposed Solution

@kuychaco @probablycorey @billygriffin and @outofambit discussed this further and agreed upon the following plan for now:
* `conflictStyle = diff3` will be resolved once #8049 is finished (and its currently in progress), so we'll let that go for now
*  `autosetuprebase = always` is a value we should set to `false` in the setup of tests that will fail without it. (see #6972 for an example of this approach)

there's still the open question of using a standard config (or a series of them) for our tests, but i think we're punting on that for now!

**Comment by kuychaco** [comment]
Yup, also hit this because I have the following in my ~/.gitconfig:

```
[merge]
  ff = true
	conflictStyle = diff3
```

... which inserts additional merge markers and causes tests to fail

**Comment by shiftkey** [comment]
An earlier discussion about this: https://github.com/desktop/desktop/pull/6972

**Comment by vilmibm** [comment]
for the record, i think having a standard config for tests would be A+
