### ISSUE TITLE
Stashed Changes not discarding after clicking discard.

### ISSUE THREAD

**Issue by VhatAmI** [desktop/desktop#8083]
Stashed changes on the master branch, 
switch to another branch, do some work, finish up, change back to master, 
decide to discard stash 
click discard button, popup click discard
pop up goes away, stash changes still present. 

## Version 2.1.0
windows 10
* Operating system:

### Logs

[2019-08-08.desktop.production.log](https://github.com/desktop/desktop/files/3483477/2019-08-08.desktop.production.log)

**Comment by tierninho** [comment]
@VhatAmI Thanks for filing.

Your logs show this:

```
2019-08-08T19:57:43.082Z - info: [ui] [AppStore. _dropStashEntry] dropped stash with commit id 44acc196f7d18c3645ebd4c11c9013e0355b5c37
2019-08-08T19:57:57.223Z - info: [ui] [AppStore. _dropStashEntry] dropped stash with commit id b8fa6dc33fe3e73fc33de77de3f34f3925adeef6
```

and

```
2019-08-08T20:00:05.193Z - info: [ui] [AppStore. _dropStashEntry] dropped stash with commit id 7c760e6b9beae3ee8e429d49828ce956415f293f
2019-08-08T20:03:39.749Z - info: [ui] Executing dropStashEntry: git stash drop stash@{3} (took 1.076s)
2019-08-08T20:03:39.749Z - info: [ui] [AppStore. _dropStashEntry] dropped stash with commit id 3f1433199eae92deaf29b63cb185824db410f438
```

which says the stash was dropped, however the UI may not have been updated properly. Are you able to repeat your steps and include any screenshots or gifs?

Also, if you have got this repo handy, please run this in the command line:

`$ git stash list`

**Comment by VhatAmI** [comment]
git stash list shows stashes on other branches, 
but not anything on the master branch

5 files show in stash in the UI, when I click restore, it restores 3 files, but still shows 5 files in the stash. 

Can't show the file names so I took screenshot of the icons by the stashed changes
![image](https://user-images.githubusercontent.com/10841983/62736666-86b96800-b9f3-11e9-91c1-262759ea3338.png)

and the ones by the 3 files restored 
![image](https://user-images.githubusercontent.com/10841983/62736685-920c9380-b9f3-11e9-9273-2b96a3a0454f.png)

Here is an up to date log file after taking following steps 

[2019-08-08.desktop.production.log](https://github.com/desktop/desktop/files/3483603/2019-08-08.desktop.production.log)

**Comment by VhatAmI** [comment]
One more note: if I discard the local changes of the 3 restored files, then restore the stash again, the same 3 files get restored as local changes.

**Comment by tierninho** [comment]
Ok, I think I see what is happening now. When you pop the stash, two of the files are in conflict with existing code (and the new file comes along for the ride):

`2019-08-08T19:56:53.303Z - info: [ui] [popStashEntry] a stash was popped successfully but exit code 1 reported.`

The other two appear to be dropped. Not sure why though.

I suggest bring the conflicted files up-to-date and try restoring the stash again. Let me know how it goes.

An issue on this has been filed here: https://github.com/desktop/desktop/issues/7748

**Comment by VhatAmI** [comment]
thanks, I deleted the two conflicted files from the local directory, then was able to discard the stash without issues. Then discarded the deletes to get the repo back to an accurate state. 

I think the bug could be renamed stashed changes cannot be discarded if stash has conflicts?

Anyways I'm back to a workable state. I'll leave it up to you if you want to close the issue or investigate further 

Heres the log for today in case
[2019-08-09.desktop.production.log](https://github.com/desktop/desktop/files/3487137/2019-08-09.desktop.production.log)
 it has anything helpful

**Comment by VhatAmI** [comment]
I think it is slightly different from #7748 as I don't want to restore the stash, merely easily discard it. 

In this case, only 2 files were conflicted, but if there were hundreds it could become a larger issue 

Discard shouldn't care if there are conflicts, it should just get rid of the stash.

**Comment by tierninho** [comment]
@VhatAmI Thanks for the update and glad you back in a good state.

Going to close this issue but cross reference it with similar issues https://github.com/desktop/desktop/issues/8084 and https://github.com/desktop/desktop/issues/7827 that are expected to fix the underlying cause.
