### ISSUE TITLE
Stash error with conflicted file upon new branch creation due to untracked files

### ISSUE THREAD

**Issue by kuychaco** [desktop/desktop#8084]
## Description

When switching branches and carrying over changes that produce a conflict there is an edge case when untracked files are involved in the conflict. Desktop stashes the untracked file, creates the new branch, and tries to apply the stashed changes on the new branch. But if the new branch already contains a file that corresponds to the stashed untracked file, Git throws an error and doesn't allow the changes to be applied. 

![image](https://user-images.githubusercontent.com/14828183/59728595-7694c180-91d6-11e9-8b07-fca34c1a9513.png)

For reference -- I pulled this out as a separate issue from https://github.com/desktop/desktop/issues/7827#issuecomment-503361669. It's a distinct bug and pertains specifically to untracked files being stashed as part of checking out a new branch.

## Version

* GitHub Desktop: Desktop-dev a6a2bf7859

* Operating system: macOS High Sierra 10.13.6

## Steps to Reproduce

1. checkout `master`
1. create branch `branch-a`
1. create new file `file.txt` on master and commit
1. checkout `branch-a` and create new file `file.txt` with conflicting changes. do not stage or commit.
1. checkout new branch `branch-b` based off of master. select option to carry over changes. (note: you also hit the error by checking out `master` instead of creating a new branch)

### Expected Behavior

`branch-b` is checked out and `file.txt` shows conflicting changes

### Actual Behavior

Error appears (see screenshot above)

## Additional Information

N/A

### Logs

N/A

**Comment by tierninho** [comment]
I noticed as part of this bug that the stash _sometimes_ results in the user being unable to click `discard` or `restore`. Switching tabs and returning resolves it. I suppose this will be moot once the bug fix comes in.

![Screen Shot 2019-08-09 at 11 08 31 AM](https://user-images.githubusercontent.com/14828183/62809225-0dbf1c80-ba96-11e9-8f85-21803f5712e2.png)

**Comment by benplay2** [comment]
I encountered this recently as well and it caused an infinite loop of GitHub Desktop stashing local changes & retrying. I had to quit the application, pop one of the many stashes, and clear the others before manually handling the untracked file to get around the issue.
