### ISSUE TITLE
Support to configure a browser of choice

### ISSUE THREAD

**Issue by staabm** [desktop/desktop#8086]
**Please describe the problem you think should be solved**

I am using github for desktop with 2 differnt github accounts. one for work and one for personal use.
I am using different browsers for those 2 accounts - personal use only in firefox, work use only in chrome.

**[Optional] Do you have any potential solutions in mind?**
It would be great if I could define the browser which 'github for desktop' uses.
it would be 'as simple as' adding a new option, like we already have for the 'external editor' or the preferred bash:

![grafik](https://user-images.githubusercontent.com/120441/62769217-c7b78800-ba98-11e9-871c-2cbf9c1a321b.png)

at best, this setting would depend on the used/configured github account, so it will change whenever I change the account

**Comment by tierninho** [comment]
@staabm Thanks for filing this issue! Currently we rely on the default browser setting determined by the OS, but adding the custom browser setting is an interesting suggestion. 

I will let this issue sit for awhile to give a chance for other users to weigh in before our team commits to anything. ⚡️

**Comment by billygriffin** [comment]
@staabm Sorry for the delay here, and appreciate your suggestion. I think this is too niche for us to support unless we see significant evidence that it's causing problems for people today and that a significant portion of users are using multiple browsers as part of their development workflow, which I don't think we've seen. Sorry this doesn't address your use case of differentiating between personal and work browser choice!

**Comment by ammtc** [comment]
@billygriffin  Consider this a vote in favor of adding an explicit browser selection option to the GH Desktop app's prefs.

I have started using GH for projects only recently, but the ability to use a different browser than the OS default for the various authentication functions, as described in this enhancement, precisely fits my use case. (Posting here at the suggestion of Steve Ward from GH Community Support, who pointed me to this ticket.)

Thanks!
