### ISSUE TITLE
Problem with installer, I can not select the folder

### ISSUE THREAD

**Issue by Neustradamus** [desktop/desktop#8104]
I would like to install in C:\Program Files\ for the current user or for all users.

How it is possible?

**Comment by steveward** [comment]
Thanks for opening this @Neustradamus!

Currently it is not possible to customize the installation location of GitHub Desktop. This is a constraint in the installation framework we use, Squirrel.Windows (see https://github.com/Squirrel/Squirrel.Windows#314). Squirrel supports machine-wide installs in a different way than conventional Windows installers (see https://github.com/Squirrel/Squirrel.Windows#337).

Is there a specific reason you are unable to install GitHub Desktop to `%LocalAppData%` in your user profile?

**Comment by Neustradamus** [comment]
Thanks for your reply, links are bad, I publish here:
- https://github.com/Squirrel/Squirrel.Windows/pull/314
- https://github.com/Squirrel/Squirrel.Windows/pull/337

The installer folder choice possibility is for several users at home and in company...

Normal softwares are by default in C:\Program Files\ on Windows.

There is a big problem, several installations on serveral user sessions on a lot of computers (auto-update in more):
- Mum
- Dad
- Child 1
- Child 2
- ...

**Comment by Neustradamus** [comment]
All good softwares when we install use by default "Program Files" (or recently "Program Files (x86)" for 32 bit apps in 64 bit system.
Bad softwares do not use it.

It is since Windows 95 and maybe before, no?
