### ISSUE TITLE
Unable to Authorize Gitlab account on MacOs

### ISSUE THREAD

**Issue by jtalier** [desktop/desktop#8105]
## Description

I am attempting to clone a repo that I have hosted on Gitlab into Github Desktop for Mac. When I attempt to authorize my Gitlab account with my username and Access Token I receive the following Error: "The user name or passphrase you entered is not correct." I have made sure 2FA is disabled. I have also un-installed Github Desktop (deleted files in Library->Application Support->Github Desktop) and re-installed to no avail. I attempted to do the same process on Windows 10 (Same computer, different partition) and had no issues, the repo successfully cloned. It could be important to note that when I attempted the same problem on Windows 10 the version of Github Desktop running was 1.6.6 (Mac was 2.1.0). I then updated the Windows version to 2.1.0 and was still able to clone repos. 

## Version

MacOs:
* GitHub Desktop: 2.1.0

* Operating system: Mojave 10.14.1

Windows 10:
* GitHub Desktop: 1.6.6

* Operating system: 10.0.17134.885

## Steps to Reproduce

1. File->Clone Repository
2. Go to URL Tab
3. Enter Gitlab URL and 'Local Path'
4. Click Clone and wait for an expected Authorization Failure
5. Enter in Gitlab username with Access Token
6. Error: "The user name or passphrase you entered is not correct."
### Expected Behavior

I expect after step 5, for authorization to work, and the repo to clone. That is what happened when the repo was successfully cloned on Windows 10.

### Actual Behavior

Error: "The user name or passphrase you entered is not correct."

## Additional Information

I was trying to find a download for Github Desktop 1.6.6 for Mac, so I could determine if this issue is related to MacOs, or version 2.1.0. However, I could not find any old downloads of Github Desktop.

**Comment by steveward** [comment]
@jtalier thanks for the report! Has authenticating to Gitlab previously worked on this machine? I just tested out the personal access token authentication flow using GitHub Desktop and didn't run into any issues.

Can you check to see if there is an existing credential cached in `Keychain Access.app`? It should look like `GitHub - gitlab.com`. If that exists try deleting that entry and running through the authentication steps again.

**Comment by jtalier** [comment]
@steveward Thank you! Deleting the credential in the Keychain Access application seemed to do the trick! I really appreciate the help, was troubleshooting this one for a while.

**Comment by steveward** [comment]
@jtalier I'm glad to hear that got things working!
