### ISSUE TITLE
Not able to publish repository || Failed to connect to github.com 443

### ISSUE THREAD

**Issue by Poonam24** [desktop/desktop#8107]
## Version

* GitHub Desktop:

* Operating system:

### Expected Behavior

It should get published on github.com

### Actual Behavior

Throwing an error saying FatalException : Github.com 443 is not reachable. Network Error

**Comment by steveward** [comment]
@Poonam24 based on the error it looks like you are trying to connect behind a proxy. Here's how you can set up your proxy:

1. Go to the file menu and select `Repository` > `Open in Terminal` (macOS) or `Open in command prompt` (Windows)
2. Run the following command:

`git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`

Replace `proxyuser` with your proxy username and `proxypwd` with your proxy password. Also, `proxy.server.com:8080` needs to point to the URL of your proxy server.

Let me know if you run into any issues with that.

**Comment by Poonam24** [comment]
Thank you for reply Steve! Though I figured out the resolution after
raising it
