### ISSUE TITLE
github desk version 2.1.1 does not switch branches

### ISSUE THREAD

**Issue by cryomeariver** [desktop/desktop#8108]
## Description

1. select "switch branch"
2. select Leave my changes on <old-branch>
3. click on "Switch branch"
4. note that  "Current Branch" does not change to new branch

Work Around
1. open a command window
2. change directory to <old-branch>
3. git stash
4. repeat steps 1-3 in bug report
5. note that the current branch is updated to <new-branch>  

## Version

2.1.1
* GitHub Desktop:

* Operating system:
Windows 10 

## Steps to Reproduce

git version 2.22.0.windows.1

### Logs

[2019-08-02.desktop.production.log](https://github.com/desktop/desktop/files/3502014/2019-08-02.desktop.production.log)

**Comment by cryomeariver** [comment]
note last line of the log, git is failing with error code 128

**Comment by billygriffin** [comment]
@cryomeariver Thanks for the issue, and sorry for the hassle! It looks like the log file you included is from August 2. Would you mind including the one from today when you're experiencing this issue so we can look into it further?

**Comment by cryomeariver** [comment]
sorry about that, but I am impressed with your prompt response, well done. I will get you a current log

**Comment by cryomeariver** [comment]
[2019-08-14.desktop.production.log](https://github.com/desktop/desktop/files/3502063/2019-08-14.desktop.production.log)

**Comment by cryomeariver** [comment]
same error.....

**Comment by steveward** [comment]
@cryomeariver thanks for uploading that log file! It looks like your name and email address hasn't been configured:

```
2019-08-14T15:18:21.207Z - error: [ui] `git stash push --include-untracked -m !!GitHub_Desktop<V5-58.1>` exited with an unexpected code: 128.
stderr:

*** Please tell me who you are.
Run
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
```

Can you go to `File` > `Options` > `Git` and verify that your name and email address are properly set there?

**Comment by cryomeariver** [comment]
will do, thank you

**Comment by cryomeariver** [comment]
and that made it happy, please requisition an 'atta-boy' from petty cash.
Thank you you have been most helpful

Please close this issue

**Comment by billygriffin** [comment]
Glad we were able to figure it out with you!
