### ISSUE TITLE
We are unable to access this connected repository on GitHub with Heroku

### ISSUE THREAD

**Issue by Sannermo** [desktop/desktop#8110]
![unnamed-1](https://user-images.githubusercontent.com/52680010/63077034-eef5d580-bf2e-11e9-985f-fe271dd1a962.png)

**Comment by SorinCPU** [comment]
Is your repo private?

**Comment by SorinCPU** [comment]
Anyway u need to give access to the heroku team in order to work.
https://github.com/settings/connections/applications/2bde25e3844dcbccc16d

**Comment by Sannermo** [comment]
Heroku has access and still not working

**Comment by Sannermo** [comment]
**Fixed!** I just forgot to add files to my repository.
