### ISSUE TITLE
Not able to set default directory

### ISSUE THREAD

**Issue by charlottetucker** [desktop/desktop#8115]
I used to be able to set a default directory such as C:\Github for my projects, but now it defaults to C:\Users\charlotte\Documents\Github.  I've trolled the internet and it was said that if I opened a project in my current directory (C:\Github) that anything else I cloned would also be put in that directory.  This is not the case.

Why was the option removed?

I request that it be put back.

**Comment by charlottetucker** [comment]
To be more clear, if I am in github and I clone from there, it will not put it in the directory my other projects are in.  If I clone from github desktop, I can choose a location.

**Comment by steveward** [comment]
@charlottetucker thanks for contributing! During the clone/create repository process you will see the `Local Path` field where you can choose a directory to store your repository. GitHub Desktop will set that directory as the default directory for the next time you clone or create a repository using GitHub Desktop.

**Comment by steveward** [comment]
> To be more clear, if I am in github and I clone from there, it will not put it in the directory my other projects are in. If I clone from github desktop, I can choose a location.

The `Open in Desktop` option should show the `Clone a Repository` view and allow you to set a `Local Path` to store your repository. Are you not seeing that?

**Comment by billygriffin** [comment]
@charlottetucker I think @steveward's description above should solve your issue and it should work even when cloning from GitHub.com. I'm going to close the issue for now but let us know if you're still having problems.
