### ISSUE TITLE
Branches detected as identical while they are not

### ISSUE THREAD

**Issue by oliverhausler** [desktop/desktop#8116]
In the latest version, branches that are detected as identical while they are not. Merge is disabled. It works find in one direction, but not in the other. Hard to explain, so I took a video to show you.

[ice_video_20190816-084607.zip](https://github.com/desktop/desktop/files/3510261/ice_video_20190816-084607.zip)

**Comment by tierninho** [comment]
@oliverhausler Possible to also attach you logs for this? See the Help menu in Desktop. 

Also, what build of Desktop are you using, as well as your OS? Thanks!

**Comment by tierninho** [comment]
You can also see the difference between any two branches within Desktop. Go to here:

![Screen Shot 2019-08-16 at 7 42 38 AM](https://user-images.githubusercontent.com/14828183/63187044-a22b0100-bff9-11e9-902e-b3744345af74.png)

This doesn't solve your issue, but it gives some insight into what the app is seeing.

**Comment by oliverhausler** [comment]
Windows 8.1

![image](https://user-images.githubusercontent.com/8090341/63186955-9861c780-c012-11e9-9805-4faed5853346.png)

[2019-08-16.desktop.production.zip](https://github.com/desktop/desktop/files/3510559/2019-08-16.desktop.production.zip)

I have merged this already, so no issue for me. I only wanted to let you know so you know something might be wrong.

**Comment by tierninho** [comment]
Thanks for the update and glad it's resolved. Gonna close the issue as it's no longer a problem for now and we will investigate on the side.
