### ISSUE TITLE
Feature Request - Enable keyboard arrows for button selection

### ISSUE THREAD

**Issue by ericboucher** [desktop/desktop#8117]
**Feature Request**
I would like to be able to use the keyboard arrows to select buttons and enter to finalize my decision. For example, when using the shortcut to delete a branch, pressing the return key will cancel, and the right arrow (MacOs) has no effect.

**Potential solution**
Allowing button selection by using keyboard arrows would solve this and make shortcuts more efficient. This could maybe happen at the `ButtonGroup` level.

**Comment by tierninho** [comment]
@ericboucher Thanks for the suggestion.

Arrowing between buttons is currently performed with the `tab` and `shift+tab` keys. We have no plans to incorporate the arrow keys but if someone from the community would like to summit a PR it would be welcomed.

We do utilize the use of arrow keys between any tabs, so perhaps that code can be leveraged. 

Screenshot for reference:
![Screen Shot 2019-08-16 at 10 38 50 AM](https://user-images.githubusercontent.com/14828183/63197136-b62f2c80-c012-11e9-82c4-57a8f740ae56.png)

**Comment by niik** [comment]
> if someone from the community would like to summit a PR it would be welcomed.

I'd add here that before we'd consider such a PR we'd first like to make sure that what we're doing with regards to keyboard accessibility is in line with the interface guidelines of the platforms we support. If, for example, using arrow keys to switch focus between buttons is an expected UX pattern on macOS we'd love to see some references to either official documentation or real world examples.

**Comment by billygriffin** [comment]
Hi folks, sorry for the back and forth here. Echoing @niik, I don't *think* this is in line with the interface guidelines or widely expected behavior (I've been wrong before though!). We really appreciate the suggestion @ericboucher. I'm going to close this issue for now, but if you'd like to share some documentation that supports this being a suggested pattern, we'd be happy to reconsider it.

**Comment by ericboucher** [comment]
Thanks all. @billygriffin, makes sense! Looks like you are indeed right and the tab is the default navigation for macOs.
