### ISSUE TITLE
Как настроить на русский язык

### ISSUE THREAD

**Issue by Berdi0305** [desktop/desktop#8127]
Здравствуйте!! Я не знаю английского. Как настроить на русский язык???

**Comment by niik** [comment]
Automatic translation:

> **How to set up in Russian**
> Hello!! I do not speak English. How to configure in Russian ???

Hi @Berdi0305, GitHub Desktop is unfortunately not available in any language other than English.

> Привет @ Berdi0305, GitHub Desktop, к сожалению, не доступен ни на одном языке, кроме английского.

**Comment by LeonidRen** [comment]
как поменять на английский?? умники огонь!!

**Comment by Berdi0305** [comment]
> как поменять на английский ?? умники огонь !!

чем не огонь, есть Возрождения??

**Comment by Netz-tur** [comment]
Не как на на github нет русского но ты можеж скачать себе в chrome разширение google translate при помощи него ты сможеж переводить страницы попробуй

**Comment by Mark3000** [comment]
Скачай расширение "Google Translate" https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb?utm_source=chrome-ntp-icon

**Comment by Veovela** [comment]
🔥Благодарю за видео создателей ролика!С нами Сила💖
✅ Тамара Запова
✅ Телеграмм @veovela
✅ Серебреный Партнёр
✅ адрес кабинета в Рой Клубе:
✅ PRIZM-PEG9-N62B-DHJC-AQY2B 
✅ Выполнено 6 баллов
✅ адрес кошелька #UMI в sigen.pro:     umi1p7d4v6khshdurs5zrprgcykkmu9pnzhqauy3fzplu69jg3qzzkkqax0ety

**Comment by Veovela** [comment]
🔥Благодарю за видео создателей ролика!С нами Сила💖
✅ Тамара Запова
✅ Телеграмм @veovela
✅ Серебреный Партнёр
✅ адрес кабинета в Рой Клубе:
✅ PRIZM-PEG9-N62B-DHJC-AQY2B 
✅ Выполнено 6 баллов
✅ адрес кошелька #UMI в sigen.pro:     umi1p7d4v6khshdurs5zrprgcykkmu9pnzhqauy3fzplu69jg3qzzkkqax0ety
