### ISSUE TITLE
Multiple monitors and laptops, and just laptop

### ISSUE THREAD

**Issue by DaveBrad** [desktop/desktop#8128]
#2107 uses the work around provided by MSWin. Unfortunately when using 3 monitors connected to the laptop with the ext monitors left and right of the screen, The work around does not help define which type of move you need to do if left-move right, if right-move-left. Also, ext monitors may be positioned over the top so that is top-move down.

Basically, the github desktop is not automatically adjusting to changes in the screen (monitors 1+n) arrangements. I design my apps to automatically adjust the window/frame to the 0,0 coordinates when the original coords and screen size change. Its optional but very up front setting.

Please consider making this a design. Why? github desktop has become a serious tool for people. Including none-programming people, so making it transparent when connecting and disconnecting multiple monitor is very common in a mobile world. Having to go find things is.....

**Comment by tierninho** [comment]
@DaveBrad Unfortunately I do not have three monitors to help test and diagnose this. Hopefully, someone from the community will chime in with a workaround until a fix arrives.

Thanks for reaching out and letting us know.

**Comment by DaveBrad** [comment]
> 
> 
> @DaveBrad Unfortunately I do not have three monitors to help test and diagnose this. Hopefully, someone from the community will chime in with a workaround until a fix arrives.
> 
> Thanks for reaching out and letting us know.

You may close this issue. 

It appears this has been fixed as an enhancement in version 2.1.1 of github desktop. I hit this problem with an older version. I checked the issues list and found #2107 was just a workaround rather than fixed. Similar issues after 2107 were referred to 2107 as their duplicate setting.
