### ISSUE TITLE
File Menu title bar is missing

### ISSUE THREAD

**Issue by ramyamenonrajendran** [desktop/desktop#8129]
**Version**
GitHub Desktop app : I downloaded the latest version on 08/19/2019
**Operating system:**
Windows 10

**Steps to Reproduce**

1. Open Github desktop app
2. A lets get started page opens. But, there is no Menu bar!
3. Not be able to connect to my repositories

**Expected Behavior**

1. Open Github desktop app
2. Ability to see/click file menu and options to be able to setup or update settings and able to connect to my repositories

**Actual Behavior**
Unable to see file menu just a completely useless "Let's get started page!"
![GitHubDesktopNoMenu](https://user-images.githubusercontent.com/54293324/63304882-b9e0de80-c2b2-11e9-9e35-63641289dfd6.png)

**Comment by billygriffin** [comment]
Thanks @ramyamenonrajendran! I think this is the same issue as #8016, and sorry you're running into problems with it as well. A workaround is to create a new repo so you have at least one repository in Desktop, and then all options will be present. Please follow along at the other issue for a better resolution.
