### ISSUE TITLE
Not able to publish branch 

### ISSUE THREAD

**Issue by rashhs** [desktop/desktop#8136]
## Version

* GitHub Desktop:

* Operating system:

### Logs

![image](https://user-images.githubusercontent.com/39766836/63408865-92eaef80-c40d-11e9-93e7-4ddc33b7c882.png)
![image](https://user-images.githubusercontent.com/39766836/63408876-967e7680-c40d-11e9-9391-2b0062f27275.png)

**Comment by rashhs** [comment]
![image](https://user-images.githubusercontent.com/39766836/63409002-e9f0c480-c40d-11e9-875c-24a5a08e4966.png)

**Comment by billygriffin** [comment]
Hi @rashhs, thanks for the issue. This looks to be the same issue as #8109, and we released an update this morning that should alleviate that warning. However, you may still need to deal with the underlying permissions issue - check out that issue for more details and let us know if the latest update (2.1.2) does not resolve it.
