### ISSUE TITLE
[MacOS] Updated version doesn't work on MacOS 10.9.5

### ISSUE THREAD

**Issue by snicolet** [desktop/desktop#8140]
## Description

I am using Github Desktop on MacOS 10.9.5.

GitHub Desktop version 2.1.1 was running fine, but when I accepted the dialog for the automatic update to version 2.1.2, the new version was downloaded but cannot be open in this version of MacOS (the system says that GitHub Desktop version 2.1.2 needs MacOS 10.10 or newer).

So I am now stuck, with version 2.1.1 deleted and new version 2.1.2 unable to be launched.

## Version

* GitHub Desktop: version 2.1.2

 

* Operating system: MacOS 10.9.5

## Steps to Reproduce

1. run version 2.1.1 on MacOS X 10.9.5
2. accept the automatic update of GitHub Desktop
3. the new version 2.1.2 does not launch on MacOS X 10.9.5 (without any warning in the release notes)

### Expected Behavior

Version 2.1.2 should run in MacOS X 10.9.5

### Actual Behavior

Version 2.1.2 doesn't run, and there was no hint in the release notes that this may be the case.

## Additional Information

Question: how can I download back a MacOS binary for version 2.1.1, which was the last version compatible with MacOS X 10.9.5?

**Comment by billygriffin** [comment]
Hi @snicolet, thanks for writing in and apologies that you're stuck. Unfortunately with an upgrade of our dependencies, support for OSX Mavericks is no longer available - this is due to Chromium no longer supporting it. We're looking into options for possibly making an earlier version available, but I can't make any promises. I apologize that we caused this pain for you without letting you know ahead of updating - I know that has to be really frustrating.

**Comment by snicolet** [comment]
For what it's worth, I have recovered a previous version (2.1.0) from another computer, and I zipped it in a archive on my FTP site: http://cassio.free.fr/divers/GitHub-Desktop-2.1.0.app.zip

As a kind of "signature" for this archive, the size of the zipped archive is 72660080 bytes, and the md5 checksum of the archive is ae5dd77d87b1dfc50f26611bda8e65fa :

**_md5 GitHub-Desktop-2.1.0.app.zip_**
````
MD5 (GitHub-Desktop-2.1.0.app.zip) = ae5dd77d87b1dfc50f26611bda8e65fa
````
**_ls -al | grep GitHub-Desktop-2.1.0.app.zip_**
````
-rw-r--r--   1 stephane  staff  72660080 27 aoû 18:41 GitHub-Desktop-2.1.0.app.zip
````

Hope this helps, Stéphane

**Comment by dom1817** [comment]
This is a problem for me as well, I'm stuck with a non working version of Github Desktop. I trust the link by @snicolet but I think it would be nice from the Github team to put an official link to the older version in this thread (also because it was [done before](https://github.com/desktop/desktop/issues/2885#issuecomment-332278524)). Thanks!

**Comment by snicolet** [comment]
By the way, the archive I gave (with the old 2.1.0 version) works, but then when we launch 2.1.0 it will get updated automatically each time we quit GitHub desktop. One trick to prevent the update is to use the "Get Info" window in the Finder on GitHub Desktop 2.1.0, and then click on the "locked" little box.

<img width="428" alt="locked" src="https://user-images.githubusercontent.com/6761856/64918189-3a540b80-d79b-11e9-9121-8dae8487896f.png">

**Comment by tanyadigman49** [comment]
Delete all my info and all the threads I've been hacked and the hacker is
coding all my devices and accounts do not let the hacker know

**Comment by tanyadigman49** [comment]
Delete all NY info threads etc I've been hacked and the hacker is coding
all my devices and accounts.do not tip off the hacker

**Comment by AlxNaz** [comment]
Official link to v 2.1.0 through the Wayback Machine: date July 17 2019.

**Comment by steveward** [comment]
Closing this out as stale since we haven't supported 10.9.5 in quite sometime and it's 10+ years old at this point.

**Comment by say25** [comment]
> Closing this out as stale since we haven't supported 10.9.5 in quite sometime and it's 10+ years old at this point.

Worth mentioning the team also implemented the ability to not check when system OS is unsupported
