### ISSUE TITLE
Problems with Logging onto desktop

### ISSUE THREAD

**Issue by nikutx** [desktop/desktop#8141]
## Description

problem with login

## Version

2.1.2
* GitHub Desktop:

* Operating system:
windows 10

### Expected Behavior

login to publish master branch authentication failed
### Actual Behavior

says authentication failed even login and password is correct tried many times.

**Comment by tm8544** [comment]
Same issue here

**Comment by steveward** [comment]
@nikutx and @tm8544 thanks for the reports. Could you both upload a log file as an attachment to give some more information about this error?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by tm8544** [comment]
[2019-08-21.desktop.production.log](https://github.com/desktop/desktop/files/3526972/2019-08-21.desktop.production.log)

**Comment by tm8544** [comment]
[2019-08-23.desktop.production.log](https://github.com/desktop/desktop/files/3534036/2019-08-23.desktop.production.log)
Another log file

**Comment by tierninho** [comment]
@tm8544 Thanks for sharing. Any chance you are using Visual Studio? Seems this is a new git error introduced with VS 2019.

https://developercommunity.visualstudio.com/content/problem/697976/git-failing-with-unknown-author.html

```
stderr:
warning: 'C:\ProgramData/Git/config' has a dubious owner: '(unknown)'.
For security reasons, it is therefore ignored.
To fix this, please transfer ownership to an admininstrator.
warning: 'C:\ProgramData/Git/config' has a dubious owner: '(unknown)'.
For security reasons, it is therefore ignored.
To fix this, please transfer ownership to an admininstrator.
warning: 'C:\ProgramData/Git/config' has a dubious owner: '(unknown)'.
For security reasons, it is therefore ignored.
To fix this, please transfer ownership to an admininstrator.
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/XXXXXX/ralli_koe.git/'
```

**Comment by tm8544** [comment]
I'm using Visual Studio 2019 runtime file, if that's what you mean.
Visual C++ 2015, 2017 and 2019 all share the same redistributable files.
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by tm8544** [comment]
On today's log there is no reference to ProgramData/Git/config
Actually, no such file or folder exists on my computer.
Only error is this:

```
2019-08-24T07:05:58.551Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/XXXXXX/ralli_test.git/'
```

**Comment by tm8544** [comment]
The problem still exists. Publish to branch fails.

**Comment by tm8544** [comment]
To be more precise, here is what works and what does not.
1) I can create a new repository  with GitHub Desktop, and publish it to github.
2) I can commit changes into this repository with GitHub Desktop (locally, that is)
3) i can **not** publish branch to github, this gives error

```
2019-08-27T03:50:41.793Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` 
exited with an unexpected code: 128.
stderr:
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/tm8544/ralli_test.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
```

I don't know if this means anything, but during repository publishing (phase 1 in my list above) ,GitHub Desktop displays a window with username and password fields, but it is visible for such a short time that I can not see if there are any values in those fields.

**Comment by tm8544** [comment]
I have tried

  *   logging out and back in,
  *   creating a new github account and testing with it
  *   uninstalling github desktop and removing every trace of it before installing again
No help.

**Comment by tm8544** [comment]
I have tried
-	logging out and back in,
-	creating a new github account and testing with it
-	uninstalling github desktop and removing every trace of it before installing again
No help.

**Comment by steveward** [comment]
@tm8544 it would be helpful if you could check to see if your username/password are properly being stored in the Windows Credential Manager. You can launch this application from the start menu and then navigate to Windows Credentials section. The GitHub Desktop entry should look like this:

`GitHub - https://api.github.com/username`

Let me know if you see that there.

Let me know if you see that.

**Comment by tm8544** [comment]
The GitHub - https://api.github.com/username entry is stored in the Windows Credential Manager.

**Comment by tm8544** [comment]
I did some research. In Credential Manager the entry is https://api.github.com/username, but shouldn't it be in the form https://api.github.com/users/username ?

**Comment by tm8544** [comment]
Any news on this? The problem still exists.

**Comment by steveward** [comment]
@tm8544 When you uninstalled did you delete the `%AppData%\GitHubDesktop` directory as well?

**Comment by tm8544** [comment]
Yes. I did.

**Comment by Betlis007** [comment]
same problem :-(

**Comment by steveward** [comment]
@tm8544 @Betlis007 are you still experiencing authentication issues in GitHub Desktop? I'd like to continue to debug this if you are still experiencing problems.

**Comment by tm8544** [comment]
I uninstalled Github Desktop and started using another product.
