### ISSUE TITLE
Crashes on Catalina Beta 6 19A536g

### ISSUE THREAD

**Issue by jpurnell** [desktop/desktop#8147]
## Version

* GitHub Desktop:

* Operating system:

**Comment by steveward** [comment]
@jpurnell thanks for reporting this. Currently we do not officially support beta versions of macOS, but this is helpful to track as the Catalina release date approaches. You can also follow along with [this Electron issue](https://github.com/electron/electron/issues/18660) to track official support on the Electron side of things.

**Comment by billygriffin** [comment]
Hi @jpurnell, I wanted to follow up and find out if you're still on Catalina and if so, whether the app is still having issues. I don't have a machine that I can upgrade on to test, but we would like to better understand if we're going to run into more widespread problems as people start upgrading to Catalina. Thanks!

**Comment by jpurnell** [comment]
Hi @billygriffin I never found an answer, but it cleared up around Beta 8 or so. I saw it across apps that used Electron, so I assume it was an apple bug and they got the message!

**Comment by billygriffin** [comment]
That's great news @jpurnell, and thanks so much for the quick reply! ❤️ I'm going to close this issue, and we can address anything that comes up around Catalina as we see them reported. Thank you again! ✨
