### ISSUE TITLE
Onboarding tutorial: entry point

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#8148]
### Problem:

Many users when they first download GitHub Desktop aren't certain what things they are able to do with it and how to do those things. We try to make primarily functionality in the app as discoverable as we can (and sometimes do it better than others), but that presumes a basic level of knowledge of Git.

The goal here is to help new users get more comfortable with working with GitHub repositories locally, understand how to use GitHub Desktop with GitHub, and give people muscle memory to repeat similar steps in a real repository.

### Tutorial entry point:

This proposes to allow users to create a tutorial repository when they are first using GitHub Desktop.

When they arrive at the "Let's Get Started" page where they can add, create, or clone their first repository in Desktop, we should allow them to create a tutorial repository. The tutorial repository is only available if the user is signed into GitHub.com or GitHub Enterprise Server. 

Since the publishing steps can be a bit cumbersome when you don't yet know what you're doing, we're proposing to publish the repository as a private repository on GitHub on the user's behalf during the tutorial repo creation process. This way it's already hooked up with their account on GitHub.com and we can allow them to do things like push commits to a branch and make a pull request, but they don't have to worry about it being publicly visible unless they explicitly choose to.

1. Ability to create a tutorial repository
2. Let users know what will happen (private repo published to GitHub.com)
3. Publish the repository with the correct content
4. Take users to the tutorial repo in the app

#### Considerations:

1. This issue includes being able to detect in Desktop that a given repo is a tutorial repo and should therefore display the tutorial steps.

2. This issue also includes the actual content for the tutorial repository and what it will include.

3. Since we're creating a repository for them, do we need to expose the local path for where the repository will be saved on their computer somehow?

#### What about after the repository is created?

The user should then be in that tutorial repository in Desktop and it should be published to GitHub.com. The actual contents of the repository and the tutorial steps will be addressed in #8149.

**Comment by ampinsk** [comment]
# Entry point designs
Following the steps @billygriffin outlined, we'll add a primary button to the Let's Get Started screen. We'll show a confirmation dialog, then take you to the tutorial repo.

The tutorial repo will contain a `README.md` file with some content to be finalized at a later date. For a start, I've been using:

```
# Welcome to GitHub Desktop!

This is your README. READMEs are where you can communicate what your project is and how to use it.

Make any change to this file, save it, and then head back to GitHub Desktop.
```


[🖼 **Figma Prototype**](https://www.figma.com/proto/TEgyJdoPH6Cet9VpQgVugi/Onboarding?node-id=257%3A1308&viewport=729%2C3744%2C1&scaling=min-zoom)

### GIF
![entry-point](https://user-images.githubusercontent.com/10404068/63549085-93a28500-c4e4-11e9-8f3a-14301e43e200.gif)

### Static screens
<img width="1440" alt="Entry point" src="https://user-images.githubusercontent.com/10404068/63549281-f431c200-c4e4-11e9-914d-7d525acc9f8c.png">
<img width="1440" alt="Entry point-confirm" src="https://user-images.githubusercontent.com/10404068/63549290-f6941c00-c4e4-11e9-9b87-b337d11ae895.png">
<img width="1440" alt="Guide-Step1" src="https://user-images.githubusercontent.com/10404068/63549300-fac03980-c4e4-11e9-8141-5d1ce1361cc7.png">

**Comment by billygriffin** [comment]
@niik Cross-posting from https://github.com/desktop/desktop/issues/8149#issuecomment-530585930

A question came up via @tierninho about what should happen in the tutorial itself if someone is *only* signed in on Enterprise Server and not dotcom, and whether the tutorial repo should be available in both cases. And if it is available on both, what implications that would have for needing to support behavior and verbiage differently based on whether they're on Enterprise Server or dotcom. We were curious if this is something you thought about given that it currently supports both @niik.

**Comment by niik** [comment]
> A question came up via @tierninho about what should happen in the tutorial itself if someone is _only_ signed in on Enterprise Server and not dotcom, and whether the tutorial repo should be available in both cases. And if it is available on both, what implications that would have for needing to support behavior and verbiage differently based on whether they're on Enterprise Server or dotcom. We were curious if this is something you thought about given that it currently supports both @niik.

When we discussed the entry point work in zoom (we as in me and @billygriffin) I understood the desired logic to be as follows

#### 1. User is only signed in to GitHub.com
Show the tutorial button and publish the tutorial as a private repository under their account on GitHub.com
#### 2. User is only signed in to GitHub Enterprise Server
Show the tutorial button and publish the tutorial as a private repository under their account on the GitHub Enterprise Server instance
#### 3. User is signed in to both GitHub Enterprise Server and GitHub.com
Same as 1
#### 4. User is not signed in to any accounts
Don't show the button

> what implications that would have for needing to support behavior and verbiage differently based on whether they're on Enterprise Server or dotcom. We were curious if this is something you thought about given that it currently supports both @niik.

The tutorial entry step already uses different verbiage depending on whether the repository will be created on GitHub.com or a GitHub Enterprise Server instance. Specifically it uses the term `GitHub.com` for GitHub.com and the hostname (sans protocol) when creating on a GitHub Enterprise Server.

![image](https://user-images.githubusercontent.com/634063/64949134-d142c580-d878-11e9-89a8-45355b1cf2a8.png)

![Screen Shot 2019-09-11 at 12 08 10 PM](https://user-images.githubusercontent.com/14828183/64739118-db398280-d48c-11e9-9983-7f1d2f698883.png)

Given that I've accurately understood the desire for the tutorial to work both for GitHub.com and GitHub Enterprise Server I think it follows then that the tutorial itself needs to apply the same logic.

**Comment by zeke** [comment]
> Create a tutorial repository and clone it

😍
