### ISSUE TITLE
Update to 2.1.2 broke the pop-up of "clone"-dialogue (somehow)

### ISSUE THREAD

**Issue by claudiusraphaelpaeth** [desktop/desktop#8151]
## Description

I was expecting GitHub Desktop, to behave as it did before update to version 2.1.2, precisely that ANY SINGLE TIME i use the "Open in Desktop" -button on a repository-page on github.com, GitHub Desktop will be either launched or focused (if already open) and show off the clone-pop-up.

After the clone-pop-up has been used once, it won't be shown again by using "Open in Desktop" from a repository-page on github.com; GitHub Desktop has to be closed, after that it can be used exactly ONE TIME regarding the clone-pop-up after "Open in Desktop"

## Version

* GitHub Desktop: Version 2.1.2

* Operating system: Microsoft Windows [Version 10.0.18362.295]
Windows 10 Professional 64-bit UEFI/GPT

## Steps to Reproduce

1. Click "Restart GitHub" in the "Update"/"A new version is available" -notification, to update GitHub-Desktop to Version 2.1.2
2. In a Browser open a repository on github.com, click the "Clone or Download"-Buitton , then "Open in Desktop"
3. In GitHub-Desktop, which was launched/focused by "Open in Desktop" in Step 2, click the "Clone" -button.
4. DO NOT CLOSE GitHub Desktop ...
5. Repeat Step 2
6. In GitHub Desktop, which was focused' by "Open in Desktop" in Step 5, the "Clone" -pop-up is not shown anymore.
7. Close GitHub Desktop
8. Repeat Step 2 ongoing

### Expected Behavior

I was expecting GitHub Desktop, to behave as it did before update to version 2.1.2, precisely that ANY SINGLE TIME i use the "Open in Desktop" -button on a repository-page on github.com, GitHub Desktop will be either launched or focused (if already open) and show off the clone-pop-up.
### Actual Behavior

After the clone-pop-up has been used once, it won't be shown again by using "Open in Desktop" from a repository-page on github.com; GitHub Desktop has to be closed, after that it can be used exactly ONE TIME regarding the clone-pop-up after "Open in Desktop"

## Additional Information

GitHub Desktop is a relatively fresh (1-2 months) install, completely default, no customization but using the "Dark Mode".

The behaviour still is the same even after disabling "Dark Mode", as well as after enabling "Dark Mode" again.

Regarding the log, watch for "Open Repository from URL failed", which is added when using "Open in Desktop" after it already has been used once..
### Logs

[2019-08-22.desktop.production.log](https://github.com/desktop/desktop/files/3532115/2019-08-22.desktop.production.log)

**Comment by tierninho** [comment]
@claudiusraphaelpaeth Thanks for filing this issue.

Based on the logs, this appears to be the problem:

```
2019-08-22T20:16:54.137Z - info: [main] Processing protocol url
2019-08-22T20:16:55.035Z - warn: [ui] Open Repository from URL failed, did not find or clone repository: https://github.com/twitchdev/CSharp-Helix-API-Helper - payload: {"branch":null,"filepath":null,"name":"open-repository-from-url","pr":null,"url":"https://github.com/twitchdev/CSharp-Helix-API-Helper"}
```

Try changing the local path when the clone pop up shows on the first time, and let me know how it goes.

**Comment by tierninho** [comment]
@claudiusraphaelpaeth  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
