### ISSUE TITLE
No way to do a hard reset on force-pushed branch

### ISSUE THREAD

**Issue by pento** [desktop/desktop#8153]
## Description

The workflow I'm looking at here is multiple people working on a branch, which requires rebasing and force-pushing at some point.

After doing the rebase and force push on one computer, it seems like I'm not able to do a hard reset on a second computer, which (in my limited git knowledge) is needed to deal with the new branch state.

## Version
* GitHub Desktop: 2.1.2
* Operating system: Windows 10 Pro

## Steps to Reproduce

- Machine 1: Create a new branch (`newbranch`) with some commits.
- Machine 1: Add some commits to `master`.
- Machine 2: Check out `newbranch`.
- Machine 1: Rebase `newbranch` on `master`, and force push it.
- Machine 2: Attempt to pull the rebased `newbranch`.

### Expected Behavior

After the rebase, Machine 2 would do a hard reset instead of a pull, so it has the newly rebased copy of the branch.

### Actual Behavior

Machine 2 is unable to pull the remote changes.

## Additional Information

![Screenshot from machine 2 being unable to pull the branch](https://user-images.githubusercontent.com/352291/63569745-f4ea5700-c5bd-11e9-8e5d-2e98a2d7afb5.png)

### Logs

[2019-08-23.desktop.production.log](https://github.com/desktop/desktop/files/3533002/2019-08-23.desktop.production.log)

**Comment by tierninho** [comment]
@pento Thanks for the details.

Based on the logs, it looks like you had some merge conflicts to resolve. Curious if you resolved them and then continued on?

`Automatic merge failed; fix conflicts and then commit the result.`

and

`(The error was parsed as 7: We found some conflicts while trying to merge. Please resolve the conflicts and commit the changes.)`

These may have occurred when you checked out a branch, created a new branch, or as part of a rebase.

- At what step was your screenshot taken?
- When you did the `hard reset` was there any errors in the command line? 

Lastly, some further reading on hard reset that might come in handy one day 😄 
https://jwiegley.github.io/git-from-the-bottom-up/3-Reset/4-doing-a-hard-reset.html

**Comment by pento** [comment]
The screenshot was taken on Machine 2, just before attempting to pull the `try/use-core-local-env` branch which had been rebased and force pushed from Machine 1.

The log file is from Machine 2 after clicking the "Pull origin" button: it just sees a bunch of merge conflicts.

I ran `git reset origin/try/use-core-local-env --hard` after this, and it reset my local branch as expected.

**Comment by tierninho** [comment]
> The log file is from Machine 2 after clicking the "Pull origin" button: it just sees a bunch of merge conflicts.

Did you attempt to resolve the merge conflicts?

**Comment by pento** [comment]
Yes, but gave up part way through, when it was trying to merge the local copy of the branch with the rebased remote branch, which is not what I wanted it to do.

There are no merge conflicts that actually need resolving, since the remote branch is correct, and the local branch is just an old copy of the branch that needs to be reset.

**Comment by tierninho** [comment]
As it is hard to diagnose without specific repos and branch details, I would suggest trying the scenario in the command line if possible to see if the same result occurs.

All I see is the merge conflict blocking the rebasing. Let us know how it goes.

**Comment by pento** [comment]
Here's expanded steps to reproduce a repository that displays this issue. Unless otherwise specified, each step occurs in the GitHub app. I don't know what the equivalent git commands are that the GitHub app runs.

## Steps to Reproduce

On Machine 1:

1. Create a new repository, `test-repo`.
2. Create a file `testfile` in your editor of choice with some content, save it in the directory of your new repository.
3. Commit `testfile` to `master`.
4. Publish the `test-repo` repository to GitHub.com.
5. Create a new branch, `newbranch`.
6. In your editor, edit `testfile`, and save it.
7. Commit the change to `newbranch`.
8. Publish the `newbranch` branch to GitHub.com.

On Machine 2:

9. Clone `test-repo`.
10. Switch the current branch to `origin/newbranch`.

On Machine 1:

11. Switch the current branch to `master`.
12. In your editor, create a file `testfile2`, add some content, and save it to the repo directory.
13. Commit `testfile2` to `master`.
14. Push to origin.
15. Switch the current branch to `newbranch`.
16. From the _Branch_ menu, select _Rebase current branch..._
17. Ensure `master` is selected, then click _Start rebase_.
18. Click the _Force push origin_ button.

On Machine 2:

19. If it hasn't automatically fetched, click _Fetch origin_.
20. Click _Pull origin_.

### Result

A merge commit is created on machine 2 in step 20.

## Variation with merge conflicts

Repeat the above steps, substituting the following steps _instead of_ steps 12 and 13.

12. In your editor, edit `testfile` in a way that conflicts with the changes you made in step 6. (eg, edit the same line). Save the change.
13. Commit the change to `master`.

As part of step 17, resolve the merge conflict by accepting both changes.

### Result

A merge conflict occurs on machine 2 in step 20.

## Expected Behaviour

In both cases, step 20 should do `git reset origin/newbranch --hard`, rather than a pull, as there are no local changes that need to be merged. Machine 2 just needs a fresh copy of the branch after it was rebased.

**Comment by tierninho** [comment]
I followed the steps for both scenarios and the results for Step 20 was `Pull origin with rebase`, which upon clicking brought everything up-to-date without any conflicts.

Not sure where to go from here as our results differed 🤔 

If there are any fresh logs, that _may_ be helpful 🤷‍♂

**Comment by pento** [comment]
I just ran through the steps again, here are the logs from both machines:

Machine 1 log: [2019-09-06.desktop.production.log](https://github.com/desktop/desktop/files/3581739/2019-09-06.desktop.production.log)
Machine 2 log: [2019-09-06.desktop.production.log](https://github.com/desktop/desktop/files/3581741/2019-09-06.desktop.production.log)

Here's the repo: https://github.com/pento/testrepo

After step 20, I also pushed to origin on Machine 2, showing the merge commit in `newbranch`.

**Comment by outofambit** [comment]
hi @pento is this still an issue for you? i think it likely is as we don't support "force pull" in desktop right now, but wanted to check.

**Comment by pento** [comment]
Thanks for checking in, @outofambit!

I haven't personally been running into this issue recently, since my recent work hasn't involved many multi-author PRs.

Going back to @tierninho's comment, that they see a `Pull origin with rebase` button, that difference is likely caused by the `pull.rebase` option being set to `true` in their `git config` (#6553). I don't have this option set locally.

**Comment by steveward** [comment]
Closing as stale.
