### ISSUE TITLE
Commit message and optional extended description still appears after committing is done 

### ISSUE THREAD

**Issue by maifeeulasad** [desktop/desktop#8159]
**Commit message and optional extended description still appears after committing is done :**

Previously when I committed something using Github Desktop the old commit message and additional comment would be gone, and those fields would have been empty. But after the latest stable update, due to some reason that is not happening anymore. The commit message and the additional comment still remains. Although it is not a problem, that  we really should be concerned about but it should be solved. That's what I think.

Here is a snap : 

[Please ignore what's written inside](https://i.stack.imgur.com/YYhZP.png)

**Comment by billygriffin** [comment]
Hi @maifeeulasad, thanks for the issue. I tried to reproduce this but have not yet been able to do so. Would you mind sharing your OS version and the GitHub Desktop version you're using? In addition, if you could include a log file from a day where this is occurring, that would be helpful as well. You can find the logs in  `Help` -> `Show logs in finder/explorer`. Thanks!

**Comment by tierninho** [comment]
@maifeeulasad  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
