### ISSUE TITLE
Issue links that are directly followed by a comma are not parsed

### ISSUE THREAD

**Issue by Yuudaari** [desktop/desktop#8162]
## Description

Commit summaries and descriptions that contain an issue link directly followed by a comma are not parsed into cilckable links. These are common in commits that close multiple issues, for example `Closes #5, closes #6, closes #23` would only parse `#23` as clickable.

## Version

* GitHub Desktop: 2.1.2

* Operating system: Microsoft Windows [Version 10.0.18362.295]

## Steps to Reproduce

Create a commit that links an issue and then add a comma after it.

### Expected Behavior

The issue link typed should be parsed into a clickable link.

### Actual Behavior

![image](https://user-images.githubusercontent.com/6081834/63643761-8977b680-c69d-11e9-918c-cefb7c6025eb.png)

**Comment by outofambit** [comment]
thanks for filing this @Yuudaari! @say25 already picked this up and submitted a fix, so I expect we'll have this resolved in the next release!
