### ISSUE TITLE
File diff too large

### ISSUE THREAD

**Issue by luchopb** [desktop/desktop#8176]
## Description

File diff is too large, but my real file is ok, it seems the line breaks are not displaying properly.

## Version

* GitHub Desktop: 2.1.3

* Operating system: Windows 10

## Steps to Reproduce

1. Change a file
2. Save it
3. Check Github desktop

### Expected Behavior

The file should be displayed properly, just like in the web.

### Actual Behavior

The file is displayed witout line breaks.

## Additional Information

![image](https://user-images.githubusercontent.com/22648700/63785547-e6a28080-c8c6-11e9-959d-f6bfeaaf5abf.png)

**Comment by luchopb** [comment]
Hi, thank you for your reply. We are using Sublime Text 3. I’m not really sure if this is new on this version or it didn’t happen before. The problem is just with some files. We always check the changes before commit and we just realized this.

Lucho

El ago. 28, 2019, a la(s) 13:29, Markus Olsson <notifications@github.com<mailto:notifications@github.com>> escribió:


Hi @luchopb<https://github.com/luchopb>,

It looks to me like your file is using carriage return characters to indicate line breaks. While some editors might support this it's not a commonly supported scenario.

Normally on Windows a line is terminated by a carriage return character followed by a line feed character (\r\n, or CR LF). On macOS and linux it's usually just a line feed character (\n). Really old Macintosh machines used to use just a carriage return character (\r) but that practice has been obsoleted.

There's a good article about this on wikipedia<https://en.wikipedia.org/wiki/Newline>.

Can I ask you what editor you're using?

**Comment by luchopb** [comment]
I found the error, the file had a diferent line ending, I changed that in sublime text. Now it's ok. Thanks for everything!!

**Comment by billygriffin** [comment]
I was just trying to figure out what might be going on here, thanks @luchopb! Glad it’s resolved!
