### ISSUE TITLE
Can't clone repo in Git Desktop for Windows

### ISSUE THREAD

**Issue by smanross** [desktop/desktop#8178]
## Description

Git Desktop for Windows cannot clone a repository or add from an existing repo (successfully cloned using Git Bash) from a fresh install of Git Desktop and a repo on GitHub.

## Version

* GitHub Desktop: 2.1.3

* Operating system: Windows 10 Build 1511 (OSBuild 10586.1176) (with all current cumulative updates applied for that build)

## Steps to Reproduce

1.  `Open Git Desktop (already logged in using valid credentials)..  Note: cleared credentials and reentered from scratch, as well.`
2. `Choose Repository to Clone (smanross/personal or any of the others I have access to)`
3.  `If I've tried this process before and failed, "delete c:\git-desktop\projects\%projectfoldername%" first`
4.  `Press "Clone smanross/personal"`
5.  `Defaults accepted: URL https://github.com/smanross/personal.git
       Local Path: C:\git-desktop\projects\smanross\personal`
6.  `Press "Clone"`
7.  `Wait for files to populate locally`
8.  `Error: "C:\git-desktop\projects\smanross\personal isn't a git repository"`
9.  `Tear forms in lower left of eye`

### Expected Behavior

I expect no tears to form :), because the project imports successfully.

### Actual Behavior

Originally, I was getting an error in the Developer Tools about "git lfs track" giving an error 128, but I installed git-lfs-windows, and the error went away (seen by Developer Tools->Console output).

I verified that no errors show up in the View-> Developer tools (Ctrl-Shift-I) after installing the lfs client, but the error remain the same.

Error: "C:\git-desktop\projects\smanross\personal isn't a git repository"
## Additional Information

I have uninstalled and reinstalled 3+ times.  No change in behavior.

![image](https://user-images.githubusercontent.com/36727473/63798532-1ea5c580-c8bf-11e9-883b-fe6685dea56c.png)
### Logs

[2019-08-27.desktop.production.log](https://github.com/desktop/desktop/files/3547465/2019-08-27.desktop.production.log)

**Comment by steveward** [comment]
@smanross thanks for the report. Just to clarify to make sure I understand the issue -- is the clone operation itself not completing at all?

**Comment by smanross** [comment]
The clone seems to work up until the point that it tries to read the locally stored files...  i.e. it creates the folder structure, and the accompanying files from git, but doesn't know how to read that it's a valid project/repo.

I hope the image helps.  This is the root of the smanross/personal project. (very simple repo without much activity).

Steven

![image](https://user-images.githubusercontent.com/36727473/63914177-3e380d80-c9e7-11e9-88a7-fbeae8037035.png)

**Comment by tierninho** [comment]
@smanross This seems a lot like this issue https://github.com/desktop/desktop/issues/6996 which has the same error and the user is also using git bash.

Relevant logs from your upload:

```
2019-08-27T17:01:00.406Z - error: [ui] `git lfs track` exited with an unexpected code: 128.
stdout:
This operation must be run in a work tree.

2019-08-27T17:02:20.035Z - error: [ui] `git rev-parse --is-bare-repository` exited with an unexpected code: 128.
stderr:
fatal: not a git repository: 'C:\git-repo\projects\'
```

Solution:

You repository is bare, i.e. it does not have a working tree attached to it. You can clone it locally to create a working tree for it, or you could use one of several other options to tell Git where the working tree is, e.g. the `--work-tree` option for single commands, or the `GIT_WORK_TREE` environment variable. There is also the `core.worktree` configuration option but it will not work in a bare repository.

```
# git --work-tree=/path/to/work/tree checkout master
# GIT_WORK_TREE=/path/to/work/tree git status
```

**Comment by smanross** [comment]
OK...  so..  that is making a lot more sense. 

short answer: removing the GIR_DIR environment variable allows everything to work, and span multiple projects seamlessly. 

long answer:

because GIT_DIR was an environment variable and I didn't know what it was used for, it was set to c:\git-repo\projects

--AND--

I used an alias to git that did this in git bash:

alias mygit='git --git-dir `pwd`/.git $@'

...which made it all work from git bash (when in a valid project directory while the GIT_DIR was defined to the "project root folder" and not a valid project folder).

Example:
smanross@SMANROSS-PC MINGW64 /c/git-repo/projects/smanross-personal
$ mygit worktree list
C:/git-repo/projects/smanross-personal  c5cc524 [master]

smanross@SMANROSS-PC MINGW64 /c/git-repo/projects/smanross-personal
$ mygit rev-parse --is-bare-repository
false

KUDOS TO THE COMMUNITY it all works now!

Thanks for everyone's response and help...  closing request,
Steven
