### ISSUE TITLE
Feature request: Favorite repositories

### ISSUE THREAD

**Issue by bvaschenko** [desktop/desktop#8183]
Could you please add the ability to mark some repositories as a favorite and get them always on top of the list?

**Comment by billygriffin** [comment]
Hi @bvaschenko, thanks for the issue! We recently did a revamp of the repo list and added the “Recent” repo group at the top. We’re not planning to add a favorites concept in the near future, but we’re open to revisiting as we learn more about how people are using the latest iteration. Thanks again.

**Comment by bvaschenko** [comment]
Hi @billygriffin thank you for the response. I was trying to put up with it, but I can't. I'm working most of my time with three repositories, but sometimes I need to switch on another (one from dozen or so) and when I finish with them I'd like to have former three on the top of my list. It also can be done without adding the "Favorites" group, but just with increasing "Recent" (it seems like an easy to do) or make it configurable by the user.
Sorry for bothering you.

**Comment by tierninho** [comment]
@bvaschenko You need to have a minimum of five (or six?) repositories to see the Recent group.

**Comment by bvaschenko** [comment]
> @bvaschenko You need to have a minimum of five (or six?) repositories to see the Recent group.

Maybe I was not quite clear:

> I'm working most of my time with three repositories, but sometimes I need to switch on another (one from dozen or so) and when I finish with them I'd like to have former three on the top of my list.

... but as "Recent" section is limited by three places only - I see two main repositories and one secondary that I had to open to make insignificant changes or to test my changes in the former three main repositories.

**Comment by billygriffin** [comment]
@bvaschenko Yep, totally understand why that might be frustrating for you and how you'd like more control. As I mentioned above, we opted for a method of not making people do any work to be able to navigate between the same few repos more easily (and it just works for you via the Recent list), and we don't want to have *both* options because that will just cause confusion. We're going to stay with this direction for now, and may revisit down the road. Thanks again for your input, and sorry that the experience is less than ideal for you.

**Comment by Sklein88** [comment]
What the ability to PIN Repos?

**Comment by JimmyCushnie** [comment]
@billygriffin Who exactly do you think would be confused if faced with both "recent" and "favorites"? Anyone who would be confused by that would also be confused by every single other feature in Github Desktop...

What about making favorites an opt-in feature? That way, these hypothetical users who are incredibly dumb won't get confused, but those of us who need the feature can still get to it by going through the "advanced options" menu.

I have over a hundred repos being managed with Github Desktop. The current situation is very inconvenient for me.

**Comment by JakubSteplowski** [comment]
Why something that simple and useful is not available yet?

What's the real problem/reason that justify not implementing it?
Why every single topic about this feature request is closed instantly without any valid explanation?

P.S. Saying "we're not planning it" is not a valid explanation.
Because I think you **should** plan to implement features users really want.

**Comment by steveward** [comment]
Requested in https://github.com/desktop/desktop/issues/12040.

**Comment by njbmartin** [comment]
I'd like to see a pin/favourite feature as recent is not at all helpful for me. I'm often working within 5 different repos within a week and have about 30 repos in the list, so the one I'm looking for always gets lost.

**Comment by steveward** [comment]
Request from #12399:

> Describe the feature or problem you’d like to solve
> I work between two projects that integrate with one another. It's painful clumsily clicking back-and-forth through the repos menu.
> 
> Proposed solution
> It would make life easier if the repositories menu had a pin icon I could click to keep it showing as a side menu rather than a dropdown menu.
> 
> Other possible solutions
> Being able to "favourite/star" repos, and using cmd+[1...9] to switch between those repos.
> A command pallet prompt like in sublime text or VS Code to quickly do something.

**Comment by cubbie** [comment]
I would love the ability to pin/star. I work with 3 repos consistently but often have to access 10+... recently used doesn't benefit me

**Comment by tidy-dev** [comment]
Requested in #14229

**Comment by steveward** [comment]
Requested in https://github.com/desktop/desktop/issues/14472.

**Comment by SLey3** [comment]
This feature is already implemented in Github Mobile so why not also implement it in the Desktop version?

**Comment by tidy-dev** [comment]
From #5708,

> When selecting Current Repository button in top left corner, the UI shows a list of recently used repositories, however it only shows the last 3 used repos. Please can the ability to customize this list be added, ie: view more than just 3 repos; and perhaps allow user to choose how those recent ones are ordered/sorted. Thanks

**Comment by Araxeus** [comment]
Why is this not on the roadmap?
Why is this issue closed?
You keep closing new issues as duplicates of this one, this would happen less if you kept this one open

at least allow pinning repo in the list please, shouldn't be that hard
I currently have more than 20 repos in gh desktop, its very annoying to find the ones I use the most

**Comment by steveward** [comment]
Requested in https://github.com/desktop/desktop/issues/16205.

**Comment by steveward** [comment]
Feedback from https://github.com/desktop/desktop/issues/16327:

> I have about 20 repos in my repo list across multiple accounts. I work with about 8 of them regularly, and about 5 of them very regularly (switching among them multiple times per hour).
> 
> The recent list stores the last 3 repos accessed, which means I'm frequently hunting amongst the other repos in my list which are grouped by account, so it's not a straightforward alphabetical lookup.
> 
> I can (and sometimes do) use the filter, but that's also slow and gets annoying to do frequently.

**Comment by uxrobinson** [comment]
Yes... forever having to scroll down to find that fourth or fifth repo. Oddly I can be just using three repos and still lose one of the repos to the list below.

**Comment by tidy-dev** [comment]
From #16561, 
> 3 recent repos is inadequate as it presumes that there is no need to switch to a fourth repo. Additionally, the process of selecting a new repo outside of the recent repo list means that, of course, an action is then taken with that repo, that could be for example pushing a commit, meaning that the user experience is "search for repo, select repo, perform action". At this point, the repo is added to the recent repo list, but the action has already been enacted on that repo. By adding the repo to the recent list, this then knocks a recent repo from the list, but because the action has already been performed on this now recent repo, it is more likely that the next action would need to be performed on the repo knocked from the recent repo list As such, as is often the case, the next action to be performed may or may be related to a repo in the recent repo list. Statistically, the repo that is most likely to require an action is the repo that is was the least recent to be interacted with, and the most recently interacted with repo has already been interacted with. Of course I understand that in some cases an individual may simply be working within a single repo, but if you are working on a project that is modular, this is not going to be the case. Absolutely introduce a "sort by most recent" feature, or a "pinned repos" feature, as both of these solutions enable easy access to recent repos. Where the current user experience breaks down is in that a recent repo list which is limited to 3 is always going to prioritise the repo that has already been interacted with.

> Pinned repos allowing the user to decide which repos are important and are required for the current work in hand. 2) Sort option over all repos or all repos per account, by recent. 3) Adapt most recent repos to repos used most, meaning that GitHub Desktop just keeps a tally of average repo use, meaning that repos the user uses regularly are not automatically unseated by a quick switch and action taken on another repo which is not regularly used.

**Comment by tidy-dev** [comment]
From #17366,

### The feature request

Adding a feature that allows users to mark specific repositories as favorites. 
This can be achieved by clicking on a star icon next to the repository name.
Once marked as a favorite, the repository will always appear at the top of the repository list, possibly following the "Recent Repositories" section. 
Importantly, users will have the flexibility to mark multiple repositories as favorites, providing a versatile way to manage and access their preferred repositories.

In addition to allowing users to mark repositories as favorites, we could consider implementing a drag-and-drop functionality. This feature would empower users to create fully custom-ordered lists, providing a more intuitive and personalized repository management experience.

### Proposed solution

The proposed solution aims to enhance GitHub Desktop by introducing a new feature that allows users to mark repositories as favorites. This feature will enable users to easily access their most frequently used repositories by placing them at the top of the repository list, following the "Recent repositories" section.

Implementation Details:

- Favorite Icon: A star icon will be added next to each repository name in the GitHub Desktop interface. Users can click on this star icon to mark a repository as a favorite.

- Favorite Repositories Section: Below the "Recent repositories" section, a new section called "Favorite repositories" will be introduced. This section will display all repositories that the user has marked as favorites.

- Multiple Favorites: Users will have the flexibility to mark multiple repositories as favorites. When a repository is marked as a favorite, it will appear in the "Favorite repositories" section.

- Drag-and-Drop Reordering: To provide users with greater control over the order of their favorite repositories, a drag-and-drop feature will be implemented. Users can rearrange the order of their favorite repositories in the "Favorite repositories" section.

- Persisting Favorites: The list of favorite repositories will be stored locally on the user's machine, ensuring that their favorite repositories remain the same across sessions.

Benefits to GitHub Desktop and Its Users:

- Improved Accessibility: Users will be able to quickly access their most important repositories without scrolling through the entire list.

- Enhanced User Experience: The ability to mark repositories as favorites and reorder them provides a customizable and intuitive user experience.

- Increased Productivity: Users can prioritize repositories that are actively being worked on, leading to increased productivity.

- Consistency Across Sessions: The persistence of favorite repositories ensures that users don't have to repeatedly mark repositories as favorites every time they use GitHub Desktop.

Overall, implementing the ability to mark repositories as favorites in GitHub Desktop will enhance the usability and efficiency of the application, making it more user-friendly and valuable to its users.

### Additional context

_No response_

**Comment by gingerbeardman** [comment]
I expected my GitHub web favourite repositories to be honoured in the app.

**Comment by tidy-dev** [comment]
From #17953 

>The feature request
When dealing with 100s of repos, it would be nice to have the ability to pin the repos which I frequently use to top.

>Proposed solution
Allow users to pin repositories, once Pinned, They will be displayed in a separate section called Pinned like Recent on the top

**Comment by aherrick** [comment]
wild this hasn't been implemented yet it's clear there is a desire and need for pinning "recent" list does me no good. just add a "pinned" section to the top, and then sort by most recent in the below section

**Comment by hrgdavor** [comment]
why are other issues pointed here, and this one is closed ?

I can not find when it was closed, it is a mess of comments and references

**Comment by gingerbeardman** [comment]
@ billygriffin closed this as completed on Aug 30, 2019

Yet people are still pointed here. It's a real FU ✌️

**Comment by ByteSizedMarius** [comment]
I'm sorry, but holding onto the idea of just three repos in the recent-section without any ability to manually pin or sort is just silly. The only valid workaround is to remove repositories from github desktop. That can't be intended?!

If favs/pins are not considered, an increase in the amount of items in the recent-section when you detect the user constantly switching would help a little at least. Also sorting by usage over some timeframe instead of last used would be preferable IMO (to allow building some muscle memory).

**Comment by JoshuaTyler-GitHub** [comment]
When you're working with many microservices, a cloud dev kit, and a front-end this is a real problem. With a mix of different company projects, community projects, and personal projects the repo list becomes long.

This feature request should go a step further. Not only do we need the ability to pin repos, we also need the ability to have different groups of pins.

**Comment by sergiou87** [comment]
From https://github.com/desktop/desktop/issues/19212

> ### Feature Request
> Imagine having 100 repositories on your computer, but for this week, you only plan to work on two. Instead of searching for them every time, you could simply pin these two repositories for easy access, making it quick and easy to switch between them.
> 
> The idea is to add a "pin" feature in the same location where the rest of your repositories are listed, as shown below: ![image](https://github.com/user-attachments/assets/5e5225a7-d6c4-4330-beb7-0ce037c5ebf3)
> 
> ### Proposed Solution
> This feature would allow users to conveniently pin selected repositories, ensuring they are always easily accessible without needing to search through the full list.
> 
> ### Additional context
> _No response_

**Comment by gingerbeardman** [comment]
Welcome to the thread @sergiou87 enjoy your stay

**Comment by Araxeus** [comment]
@sergiou87 can you reopen this issue? why is this even closed?

**Comment by ustk** [comment]
Still no pin possible... how could that be? 

If it can trouble some people, just please make it optional. And I don't see who could be troubled with a pin system, it's just absolutely everywhere in apps and softs around us. If a dev, even beginner, doesn't understand what a pin is and the difference with Recents, well...

With several dozens of repos, it is the navigation that brings me troubles, not a pin system, which is just intended for the exact opposite.

I would largely prefer the Recent to be an option in settings, like "Show recents", this is way more natural in every systems we all know.

I love Desktop, but the lack of some basic functionalities asks me more and more to look toward other tools.

**Comment by maciejstepie** [comment]
Bump, how this is even a problem to just change from 3 to 10 or variable in config. It has been 5 years for something that intern can do

**Comment by chase-robbins** [comment]
I am here just to dogpile and agree that pinning/favoriting is necessary and it's crazy it hasn't been implemented yet.

**Comment by ByteSizedMarius** [comment]
Also kind of disrespectful imo to keep this issue closed despite considerable interest and activity

**Comment by hrgdavor** [comment]
Guess management feels, it is better to burn money on AI. We can thank for this also all the ppl paying for Copilot.

**Comment by syed-bilal-bukhari** [comment]
I was about to request the same and saw this already as Closed. I think it's a pretty basic and much needed feature that should be there by now. Working in Careem, a large scale organisation, I have more than 30 repositories on my local, and i have to switch between 4 repositories pretty frequently, Its a basic need to have PINNED repositories, or maybe some Directories to arrange multiple repositories in a folder. Why would the product team reject this feature request?

**Comment by CarlosNZ** [comment]
Yup, just piling on too to say "Yes please"!

**Comment by dvclmn** [comment]
Befuddled as to why this isn't / cannot be a thing. I have a long-ish list of 50 or so repos, each with their place, just at different points in time. Allowing *anything* beyond the current 3-repo Recents list would be a huge help. I don't mind whether it's favourites, pinned repos, or just a longer Recents list. 

Different repos take on different levels of relevance over time. 3 Recents isn't enough. I hope you re-consider this little bit of UI, based on the many votes of support above.

**Comment by estherflails** [comment]
I recently became frustrated by the lack of this feature, so I'm just here to agree with everyone it is very much needed.

**Comment by ByteSizedMarius** [comment]
If you feel as strongly about this as I do, you may be interested in [my patch](https://github.com/ByteSizedMarius/gh-desktop-pin-repositories) that adds this feature.

Disclaimers:
- I do not usually work in these languages
- You will need to set up the dev env and recompile the installer
- You will obviously not be able to receive automatic updates

Tradeoffs I am willing to make at this point – I don't expect this to become an official feature any time soon

**Comment by SPOOKEXE** [comment]
I even implemented it here, wasn't very hard... https://github.com/SPOOKEXE/desktop/tree/ui-pinning-repos

https://github.com/desktop/desktop/issues/22751
> made a little demo for what it can look like, just something super basic. could have the pin icon on the left side too.
> <img width="356" height="346" alt="Image" src="https://github.com/user-attachments/assets/44a960f2-46d4-4499-8fd1-ac41aa68baa3" />
> <img width="695" height="348" alt="Image" src="https://github.com/user-attachments/assets/f353c784-5d0c-42cd-bf65-d16288324700" />

**Comment by maciejstepie** [comment]
So its almost 6 years and its still not added, huh 😢

**Comment by gingerbeardman** [comment]
Many of us grew tired of waiting and now use [GH Desktop Plus](https://github.com/desktop-plus/desktop-plus), which has it.

**Comment by hrgdavor** [comment]
@gingerbeardman thanks for the link. 

Ignoring features like this is plain corpo-BS.
