### ISSUE TITLE
enhancement: `git diff <commit 1> [<commit 2>]`

### ISSUE THREAD

**Issue by nathanhinchey** [desktop/desktop#8185]
The command `git diff <commit 1>` is an important part of my workflow and not supported*. In the git CLI I use `git diff <commit>` very often, but it doesn't seem to be possible in GitHub Desktop.

When I want to see changes compared to a revision that was not the most recent commit, I don't see a way in GitHub desktop to do it.

**Potential solution:**
Add an input field for comparison base (the default will be `HEAD`), which allows commit SHAs, branch names, `<sha>^^`, `HEAD~`, etc. Whatever was selected as the base is used for comparison, rather than always using `HEAD`.

---
Related to [issue #6757](https://github.com/desktop/desktop/issues/6757)

**Comment by billygriffin** [comment]
Hi @nathanhinchey, thanks for the issue. I think this is sufficiently similar to #6757, so I’m going to close this and combine into that one. Thanks!
