### ISSUE TITLE
Add support for the Touch Bar

### ISSUE THREAD

**Issue by j-f1** [desktop/desktop#8186]
**Please describe the problem you think should be solved**

When using GitHub Desktop on a Mac with a touch bar, nothing is shown in the application area. One thing the touch bar is used for in other applications is displaying the buttons of dialog boxes so that you don’t have to move your hand to the trackpad to take action:

<img width="1085" alt="Touch Bar showing Cancel and Save buttons" src="https://user-images.githubusercontent.com/25517624/64038241-970dc000-cb25-11e9-84e2-2481bd4092cb.png">

Additionally, when there isn’t a dialog being shown, there are typically several buttons in the touch bar to perform various common actions.

**[Optional] Do you have any potential solutions in mind?**

* Update the `Dialog` component to display its action buttons in the Touch Bar using Electron’s Touch Bar APIs.
* When a dialog is not visible, display a set of common actions. Here are some options:
  - Commit
  - Switch Repo → search button, list of recent repos
  - Switch Branch → search button, list of recent branches
  - Switch to PR → search button, list of recent PRs
  - Push/Pull/Fetch
  - Compare to Branch
  - Open in → GitHub, editor, terminal, file browser

The buttons marked with a `→` could be displayed as [popovers](https://electronjs.org/docs/api/touch-bar-popover), allowing the user to either tap them, then tap another option, or press and hold on the button, then drag their finger to the appropriate option and release to activate it.

Additionally, when typing the summary and description fields, as well as the co-author field, the autocomplete options could be displayed in the touch bar for easy access.

Electron has [some docs on the Touch Bar](https://electronjs.org/docs/api/touch-bar), and for those without a physical Touch Bar, Sindre Sorhus has created [a simulator](https://github.com/sindresorhus/touch-bar-simulator).

Another thing to think about is when to remove the escape button. Some apps will replace the escape button with a custom button in some cases. For example, when you’re editing a contact in the native Contacts app, the escape button is replaced with a “Done” button:

<img width="1085" alt="Touch Bar Showing custom escape button" src="https://user-images.githubusercontent.com/25517624/64039735-5b74f500-cb29-11e9-91b3-2b9fcf82afaa.png">

**Comment by steveward** [comment]
I'm going to close this out since Apple is moving away from the touch bar in their new machines. Thanks for sharing some specific design ideas @j-f1!
