### ISSUE TITLE
Application automatically discards files in random scenario.

### ISSUE THREAD

**Issue by kmuralidaran** [desktop/desktop#8187]
## Description

File changes discarded automatically without User confirmation when switching branches at random situation

## Version

* GitHub Desktop: 2.1.3

* Operating system: Windows 10

## Steps to Reproduce
Files in Changes discarded automatically at random scenarios when switching branches

### Expected Behavior
Files should not be discarded automatically

### Logs

[2019-08-31.desktop.production.log](https://github.com/desktop/desktop/files/3562029/2019-08-31.desktop.production.log)

**Comment by outofambit** [comment]
Hi @kmuralidaran thanks for reaching out, I'm sorry you're having this problem. From looking at the logs (which were very helpful, thank you!), it appears your changes were stashed on the branch before checking out the next one. If you check out the previous branch, do you see a button to view stashed changes at the bottom of the changes list?

<img width="332" alt="Screen Shot 2019-09-02 at 10 27 43 PM" src="https://user-images.githubusercontent.com/964912/64146215-efb4b580-cdd0-11e9-969f-7faa78cc4955.png">

Additionally, do you remember seeing a dialog like this when you switched branches?

<img width="489" alt="Screen Shot 2019-09-02 at 10 29 09 PM" src="https://user-images.githubusercontent.com/964912/64146254-196ddc80-cdd1-11e9-931d-a5e42e2873af.png">

(Selecting the "Leave my changes..." option is what triggers this behavior.)

Thanks!

**Comment by billygriffin** [comment]
Just wanted to call out that this feels similar to #8200, and might be addressed in #8084.

**Comment by tierninho** [comment]
@kmuralidaran  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
