### ISSUE TITLE
There is no borders in the application

### ISSUE THREAD

**Issue by deotech77** [desktop/desktop#8189]
## Description

white  aplcation on other white applicatin Explorer or SQL managment studio.
please dont copy terrible style from Microsoft Win 10

## Version
2.13
* GitHub Desktop:
* Operating system:
Windows 7 x64

## Steps to Reproduce
Run application

**Comment by coliff** [comment]
I think it looks good as it is - no need for borders.
If you find that the white background is poor contrast with your other apps try the dark mode.
`File > Options > Appearance > Dark`

**Comment by outofambit** [comment]
Hi @deotech77 we need more information to understand your issue. Please fill out the [original template](https://github.com/desktop/desktop/blob/development/.github/ISSUE_TEMPLATE/bug_report.md) with all the information you can. Screenshots are very helpful for an issue like this. (I can't tell if this is a bug, or if you just don't like the default color scheme.) Thanks!

_Note: I've edited your original post to remove some derogatory remarks._

**Comment by billygriffin** [comment]
I'm going to close this since we don't have enough information to make it actionable. Thanks for the issue and let us know if you'd like to provide the information @outofambit requested - happy to take another look if so. Also echo @coliff to try Dark Mode if that might be better for you.

**Comment by deotech77** [comment]
![borders](https://user-images.githubusercontent.com/16776822/64322493-06901d80-d006-11e9-9a68-33e3c1177090.PNG)
This is a sample of missig borders. 
the application is lookin like a spot  on the screen.

**Comment by deotech77** [comment]
чт, 5 сент. 2019 г. в 05:41, Billy Griffin <notifications@github.com>:
