### ISSUE TITLE
warn user when creating a ref longer than 255 bytes

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#819]
a push with a very long ref will fail with this sort of message:

```
remote: error: GH005: Sorry, refs longer than 255 bytes are not allowed.
```

We should catch this earlier in the process - i.e. when creating a new branch.

**Comment by shiftkey** [comment]
This is going to bubble up as a regular Git error message. If someone wants to polish this experience and bake it into the branch dialog then that's fine.

**Comment by billygriffin** [comment]
@shiftkey Do we see this frequently enough, or do you think this is ok to close? Seems super rare such that the existing error message bubbling up is reasonable, but just wanted a gut check on that.

**Comment by shiftkey** [comment]
I'm fine to drop the `future-proposal` label. If someone stumbles into this within Desktop and finds their way to this issue, we can talk about how to warn the user before they try to push the branch and spin off a `help-wanted` task.
