### ISSUE TITLE
Difficulty manually resolving conflicts (too little information)

### ISSUE THREAD

**Issue by BasThomas** [desktop/desktop#8195]
**Please describe the problem you think should be solved**
GitHub Desktop offers merging branches and then resolving merge conflicts. Some can be "resolved manually" by choosing either "yours" or "theirs":

<img width="418" alt="image" src="https://user-images.githubusercontent.com/4190298/64105457-94ee7000-cd76-11e9-8da3-0eee7097847c.png">

Nothing, however, gives any information as to what those changes are, as well as cutting off the file paths (so you can't even see which file the conflict concerns).

Example:
<img width="823" alt="image" src="https://user-images.githubusercontent.com/4190298/64105733-19d98980-cd77-11e9-824b-b8ed6ff62f5a.png">

**[Optional] Do you have any potential solutions in mind?**
A first step would be to not cut off paths to files and/or make sure they have alt-texts with the full path names.
A second step could be to always offer an option to open the file (in this case the modified one) to see the changes.
A third option could be to allow a filtering option in changed files that sorts by added/deleted/conflict/etc., so that it is easier to spot files that have conflicts when fully manually merging.

**Comment by billygriffin** [comment]
Hi @BasThomas, we're looking at this in https://github.com/desktop/desktop/issues/6666, and hoping to resolve it in the next release, but just in the context of the file path (essentially your "first step"). I'm going to close this since we're addressing part of the concern there, but I'm curious to hear more about your third option relative to what you're experiencing today.

**Comment by BasThomas** [comment]
Ah, sorry for not spotting #6666 😄

Regarding option three: resolving the conflicts leaves me with three options:
- resolving via the UI and merging;
- aborting the merge;
- dismissing the modal and doing it manually.

In case of the third, it would be helpful to more easily see which files have conflicts, which I move to Terminal for as GitHub Desktop does not (allow to) sort the files by their state.

Let me know if that clears it up. In the meantime, I'm looking forward to seeing #6666 getting tackled. Thanks again for a great product!
