### ISSUE TITLE
Username and Password Not Working From Command Line - Trity Install

### ISSUE THREAD

**Issue by Zenaf** [desktop/desktop#8196]
When attempting to utilize git clone to pull down Trity, the Terminal prompts me for a Username and Password. I correctly typed both yet I receive the following:

remote: Repository not found
fatal: repository 'https://github.com/toxic-ig/Trity.git/' not found

Thanks for your help.

**Comment by outofambit** [comment]
Hi @Zenaf, thanks for reaching out. I tried that URL and it looks like the repository no longer exists, is now private, or maybe has been moved. I'm afraid there's not much we can do on our end to help with that. Sorry and best of luck.
