### ISSUE TITLE
Allow users to stash changes without switching branches

### ISSUE THREAD

**Issue by maxloh** [desktop/desktop#8197]
Every time I wanted to stash changes in GitHub Desktop, I need to switch to another branch, choose the "Leave my changes on ..." option in pop-up, and switch back to the branch I am working on.

It would be better if there is a "stash" button in the right click menu, or in the top menu bar.

**Comment by billygriffin** [comment]
Hi @maxloh, thanks for the idea. We’re open to potentially revisiting this in the future but for now we’re going to keep the current flow for stashing, as that has been by far the most common use case we’ve heard from folks. I’m going to close this issue to convey that we don’t intend to support this in the near term but if it’s something we continue to hear from others and see workflows where it would be useful to a broader cross-section of people, we’re not opposed to adding something like this down the road. Thanks again!

**Comment by tierninho** [comment]
Duplicate requests, Ref #8775 and #8931

**Comment by JosephTLyons** [comment]
This would be extremely beneficial to me.

**Comment by thesyntaxinator** [comment]
I was looking for this feature as well and couldn't find it. Would be helpful especially if it isn't too difficult to implement.

**Comment by billygriffin** [comment]
Hi folks, I'm reopening this issue to indicate that we would like to support this. Our thinking is to support stashing changes on a branch that then leverages the existing UI for viewing, deleting, and restoring a stash on a branch.

Our proposal is to do this through the context menu in the header of the changes list, and also as a menu item in "Branch" under "Discard all changes".

cc: @shieldgenerator7 @adamwych @Alvin-Seville

**Comment by JosephTLyons** [comment]
@billygriffin  Excellent!  I’m so happy to hear this!

Will this only allow us to use one stash, or multiple?

**Comment by billygriffin** [comment]
@JosephTLyons Awesome! It'll continue to use the same paradigm that exists today, where you can't have multiple stashes per branch. That's a good point though that we'll need to consider in implementation - if you already have a stash, we'll need to also warn that stashing again will overwrite the existing stash, just like we do in the switching branches stashing flow.

**Comment by davidbarton** [comment]
I would like to have stash option available inside error dialog when trying to pull with unstaged changes. As a user this error is very frustrating and does not offer any way out. The only current workaround for this situation is to switch to different branch and back and then try to pull again.

Would even suggest pushing this out as a separate patch before you decide on how to manage stash in other scenarios.

<img width="520" alt="Screen Shot 2020-04-26 at 12 17 50 PM" src="https://user-images.githubusercontent.com/1619732/80304787-99a9dd80-87b8-11ea-883b-0ce7c213bd08.png">

**Comment by EldinZaimovic** [comment]
Great idea!!
Switching branches every time for stashing is really annoying.

**Comment by justinryder** [comment]
I was just typing up a feature suggestion when I saw this issue. I'll post here to prevent issue duplication, but I have some ideas for how to make this feature even more useful:

### Describe the feature or problem you’d like to solve

The only git command that I still need to manually run in the CLI is `git stash` and `git stash pop` - everything else I typically do with git can be done via the GitHub Desktop client. It would be awesome to have a simple way to stash all working copy change or only selected files/lines as well as to have a stash browser that can make viewing/applying stashes easier. I don't bother to use the more complex git stash operations, but if there was a GUI option to control them I would definitely use them more.

### Proposed solutions

Any or all of these feature suggestions would contribute to making it easier to manage your git stash:
* New Branch menu option: "Stash all changes" (equivalent to `git stash`)
* New Branch menu option: "Apply last stash to working copy" (equivalent to `git stash pop`)
* New Stashes tab (next to Changes/History): Similar to the History tab, displays a list of all stashes in the stack with context menu options for each to apply a specific stash to the working copy
* Select one or more files in the changes tab > right click > new option for "Stash selected files"

**Comment by justinryder** [comment]
> [...] It'll continue to use the same paradigm that exists today, where you can't have multiple stashes per branch. [...] if you already have a stash, we'll need to also warn that stashing again will overwrite the existing stash, just like we do in the switching branches stashing flow.

Why not give users the ability to control the full stash instead of limiting to a single entry per branch? It's a stack, so there's nothing in git itself preventing users from having multiple stashes if they use the CLI. It would be awesome to have this same level of control in the GUI.

**Comment by Justin-JHG** [comment]
hi 
thank you for the reply. the issue here is quite different to #9858, even this one implemented we still can't stash changes on protected branches.

if users don't want the dialog to pop up when switching away from protected branch then they can configure to not show the dialog. but for us who need to stash on protected branches there is no way to do.

So yes just asking you to reconsider this and even adding a configuration to allow stash on protected branches would be very beneficial and it will feel consistent as well.

Thank you.

**Comment by billygriffin** [comment]
Hi @justinryder, thanks for the thoughts. In lots of interviews and based on the feedback we've received so far, it seems like the design we've chosen has had overwhelmingly positive reception. We try really hard to be thoughtful in our design and not just put a button for everything Git does. I know that tying stashes to branches isn't going to be everyone's preference, but we think it creates a far more intuitive workflow than just an ever increasing stack of stashes.

And @Justin-JHG, I know this doesn't exactly solve for your use case perfectly, but providing the ability to stash on any branch at any time without switching branches would allow you to do the stash prior to switching away from the protected branch, and then switch branches.

**Comment by Justin-JHG** [comment]
> And @Justin-JHG, I know this doesn't exactly solve for your use case perfectly, but providing the ability to stash on any branch at any time without switching branches would **allow you to do the stash prior to switching away from the protected branch**, and then switch branches.

wow I must be misunderstanding before, so we will be able to stash changes on protected branches once this is out. Great! thanks @billygriffin

**Comment by justinryder** [comment]
> Hi @justinryder, thanks for the thoughts. In lots of interviews and based on the feedback we've received so far, it seems like the design we've chosen has had overwhelmingly positive reception. We try really hard to be thoughtful in our design and not just put a button for everything Git does. I know that tying stashes to branches isn't going to be everyone's preference, but we think it creates a far more intuitive workflow than just an ever increasing stack of stashes.

Thanks for the context, I appreciate it. :)
I'm excited for this feature!

**Comment by billygriffin** [comment]
We discussed this today. We'd like to include a context menu when you right click in the "[ ] changed files" header for "Stash changes" and also as a menu item in the `Branch` menu. This will leverage the existing stashing flow and your stash will be available to restore.

Separately and in addition to that, we'd also like to update the error dialog when trying to pull with changes in the working directory to add a button to stash those changes. We discussed potentially stashing and popping by default when you click that button, but that feels heavy-handed and introduces a higher likelihood of conflicts.

**Comment by davidbarton** [comment]
Thanks for adding the stash support. There is still the user trap while trying to pull with unstaged changes. The stash feature is well hidden from most users and they will likely get stuck on the error dialog. Can you provide an easy path to resolve the error? Details here https://github.com/desktop/desktop/issues/8197#issuecomment-619524546

**Comment by Justin-JHG** [comment]
can't wait for this one to come out, will it be in 2.5.3?

**Comment by tierninho** [comment]
> will it be in 2.5.3?

Correct. It is available now in our Beta Channel https://github.com/desktop/desktop#beta-channel

**Comment by billygriffin** [comment]
@davidbarton Thanks! Reopening since we're working on that remaining piece in #10053.

**Comment by maste197** [comment]
**@**

**Comment by moctk619** [comment]
> Every time I wanted to stash changes in GitHub Desktop, I need to switch to another branch, choose the "Leave my changes on ..." option in pop-up, and switch back to the branch I am working on.
> 
> It would be better if there is a "stash" button in the right click menu, or in the top menu bar.
Hwtbfafah5wu25u5q5u225u25ijqryyrjrqyteiybru47ktqgrq77i42[Parliament](Parliament)
