### ISSUE TITLE
Publish to wiki repository opens publisch repository dialog

### ISSUE THREAD

**Issue by lutz** [desktop/desktop#8198]
**Please describe the problem you think should be solved**

I clone a wiki repository of a private repository. The first comit and push works well. But with the next try of push commits the **publish repository** dialog opens and wants to publish the complete repository. When (as example) i enter a new name an error will showed that creation failes because the origin is already exists.

When i push the commits vie git cli it works well so it seems to be a problem with the github desktop client.

![grafik](https://user-images.githubusercontent.com/26437097/64155327-d9d7dc80-ce32-11e9-88d6-2e21b01ee441.png)

**Comment by steveward** [comment]
Thanks for the report @lutz. This is a known issue that we are tracking in https://github.com/desktop/desktop/issues/3839. Please follow along there for updates.
