### ISSUE TITLE
in github desktop,merge 'master' into n2,error:this branch is up to date with master

### ISSUE THREAD

**Issue by fcqqfat** [desktop/desktop#8201]
## Version

* GitHub Desktop:

* Operating system:

**Comment by billygriffin** [comment]
Hi @fcqqfat, would you mind filling out the template I included in editing your original issue? This helps us figure out what might be happening for you. Specifics about reproduction steps are particularly valuable in making sure we understand and can reproduce your issue and help you get it figured out (or identify it as a bug). Thanks!
