### ISSUE TITLE
Github Desktop keeps a lot of junk files

### ISSUE THREAD

**Issue by sasatefa2009** [desktop/desktop#8204]
**The problem is that I found that GitHub desktop keeps a lot of junk files of previous versions.**

**The folder SquirrelTemp at Appdata/Local has a lot of files for GitHub that contains a lot of junk from the previous installed versions**
<br>
![1](https://user-images.githubusercontent.com/22708418/64266030-35d65a00-cf34-11e9-8bc8-5e499d7fe0a7.png)
<br>
![2](https://user-images.githubusercontent.com/22708418/64265066-919fe380-cf32-11e9-9065-f1678ff104a6.png)
<br>
![3](https://user-images.githubusercontent.com/22708418/64265090-9b294b80-cf32-11e9-9f0e-08387e98cbfd.png)
<br>

**Moreover, I found that GitHub keeps the old version installed.**
<br>
![4](https://user-images.githubusercontent.com/22708418/64265158-b5fbc000-cf32-11e9-8fcc-c879be855e2d.png)

<br>

**Not only that but also after uninstalling GitHub desktop, the `SquirrelTemp` folder is not deleted**

**Comment by steveward** [comment]
Thanks for opening this @sasatefa2009. There is an issue open to [update electron-winstaller](https://github.com/desktop/desktop/issues/5197) (GitHub Desktop is currently on v2.6.0), which would bump up the version of Squirrel that GitHub Desktop uses. More recent versions of Squirrel have improvements around cleaning up after application updates, which would help with the issue you are experiencing. 

I'm going to close this issue out and bump up #5197.
