### ISSUE TITLE
Does not LogOut

### ISSUE THREAD

**Issue by Naveen-Jayanna** [desktop/desktop#8205]
## Version

* GitHub Desktop:

* Operating system:

**Comment by billygriffin** [comment]
Hi @Naveen-Jayanna, would you mind filling out the template in the issue to help us better understand how the problem is happening for you so we can more easily diagnose it? Thank you!

**Comment by tierninho** [comment]
@Naveen-Jayanna To logout, go to the Preferences menu by `cmd`+`,` (Mac) or `ctrl`+`,` (Windows).

**Comment by billygriffin** [comment]
Thanks @tierninho! @Naveen-Jayanna Let us know if @tierninho's guidance above doesn't work for you, and we'll be happy to take a look at it. 😄
