### ISSUE TITLE
Avatars (or all images?) should go through proxy/authentication and be cached

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#821]

**Comment by NickCraver** [comment]
Just hit missing avatars on enterprise instances. I manually authenticated inside electron via `window.location = '<url>';` and did 2-factor auth...now I have avatars.

It's a crappy workaround, but visually this is the most visible missing piece in the current UI for enterprise customers, IMO. Aside from that, I'm liking this thing :)

**Comment by shiftkey** [comment]
> I manually authenticated inside electron via window.location = '<url>'; and did 2-factor auth...now I have avatars.

Yeah, inside the renderer process we do have the ability to assign cookies from a valid GitHub session, which would explain how that workaround succeeds, but we've avoided doing the entire auth process completely in there (because security?).

> Aside from that, I'm liking this thing :)

💖

**Comment by niik** [comment]
> I manually authenticated inside electron via window.location = ''; and did 2-factor auth...now I have avatars.

👏

**Comment by alrz** [comment]
>I guess if we can serve up a placeholder image in case of failure then it's okay?

Please!

**Comment by hparadiz** [comment]
This is still an issue
![image](https://user-images.githubusercontent.com/195216/29675426-1f7a3e20-88c3-11e7-8e52-3cd78a7f2320.png)

Eight months since the issue was reported and still nothing?

**Comment by shiftkey** [comment]
@hparadiz are you connecting to GitHub or a GitHub Enterprise instance?

**Comment by hparadiz** [comment]
@shiftkey Enterprise

**Comment by shiftkey** [comment]
@hparadiz cool.

So an update on this - even with providing a valid token, there's situations where Enterprise won't return the avatar to Desktop. We're talking with the Enterprise team to get this fixed, which will then take time to reach customers in an update. Apologies for the delay.

**Comment by hparadiz** [comment]
@shiftkey 
No worries. I totally get how annoying it is to expect to be able to use a simple <img src=""> only to have someone tell you it needs to be run through a corporate pass-through.

That being said it would look nicer if there was a default avatar showing instead of a broken image.

**Comment by arminrosu** [comment]
> I manually authenticated inside electron via window.location = ''; and did 2-factor auth...now I have avatars.

I get a `401 Unauthorized` when I try to access my internal network sites via Github Desktop. Normally an authentication prompt appears. I assume the User Agent is blacklisted.

Interestingly, Sourcetree correctly dispalys the Avatars.

**Comment by shutterzee** [comment]
Agreed that SourceTree displays the avatars in my case as well - this would point to the potential for a client-only fix? Was unable to use the window.location trick. I see broken avatars as displayed above.

**Comment by kmscode** [comment]
FYI...

I have this problem with with 1.0.1 installed.

History only shows the avatar for commits that are owned by the wrong e-mail address (reference #2829). This may explain:

> Interestingly, Sourcetree correctly dispalys the Avatars.

from this [comment](https://github.com/desktop/desktop/issues/821#issuecomment-330786396). 

Otherwise all images are broken.

**Comment by joshaber** [comment]
I haven't looked into it, but it's possible Sourcetree falls back to Gravatar or something similar.

**Comment by arminrosu** [comment]
@joshaber you are right, Sourcetree displays Gravatars. I just confirmed it using [Charles](https://www.charlesproxy.com/).

**Comment by joshaber** [comment]
Thanks for doing the legwork on that @arminrosu!

**Comment by icarnaghan** [comment]
Subscribing - I have the same issue.

**Comment by sergeyspatar** [comment]
Version 1.0.4 still has this bug.

**Comment by joshaber** [comment]
Yes, this is currently blocked by some required work on GitHub Enterprise.

**Comment by shiftkey** [comment]
Bumping this thread as we've not had much movement on this from our end - a few people have suggested re-implementing Gravatar support as a fallback that we had in the classic apps. 

@desktop/core unless there's any objections to this I'll throw it on my plate this week to estimate the work involved.

**Comment by Haacked** [comment]
It may seem cosmetic, but displaying a broken image icon is worse than even just showing a placeholder image. It reduces confidence in the application. So I'm 👍 to doing something here.

The gravatar fallback seems like a good start. Gravatar itself has a fallback mechanism. So the fallback sequence would be:

1. GHE avatar
2. Gravatar
3. Placeholder

We should never show a broken image here.

**Comment by Haacked** [comment]
> We should never show a broken image here.

Now that I've said that, say hello to my upcoming new profile image.

![broken-image](https://user-images.githubusercontent.com/19977/32184365-3b0c2566-bd59-11e7-8efe-42b00618524e.png)

:trollface:

**Comment by ausiddiqui** [comment]
on 1.0.9 and the broken image is now a default robot in the commit summary / description box area (for a logged in Enterprise repo), but still a broken image under Preferences > Accounts. 

<img width="358" alt="screen shot 2017-11-29 at 10 59 27 am" src="https://user-images.githubusercontent.com/9053345/33393604-8d344a1e-d4f4-11e7-9463-ae6ef6533069.png">

<img width="467" alt="screen shot 2017-11-29 at 10 59 41 am" src="https://user-images.githubusercontent.com/9053345/33393617-933973f8-d4f4-11e7-9e21-920b9b4017cb.png">

**Comment by icarnaghan** [comment]
I'm seeing the robot too, but I'm also seeing broken avatar images in my history list.

**Comment by say25** [comment]
@shiftkey I know the current solution is to use Gravatar for fallback, do you know if the GitHub enterprise team will be able to do the work required to not require Gravatar fall back in the future?

**Comment by shiftkey** [comment]
@say25 it's an ongoing discussion with the team, and even after a fix lands it would require GitHub Enterprise administrators to update their instances.

I've made a big dent into this in #3513, so please follow along with that PR and we'll see if we can make this experience better in the short-term.

**Comment by keithy** [comment]
Still not fixed
