### ISSUE TITLE
'Publish your branch' suggested for branch that's already published

### ISSUE THREAD

**Issue by zeke** [desktop/desktop#8214]
## Description

I'm seeing a "publish your branch" suggestion box, but the branch is already published, and has an associated PR. Similar to https://github.com/desktop/desktop/issues/6765, but this time I'm only seeing the suggest for a specific branch.

Maybe it's because this PR has a change to an Actions workflow file?

## Version

* GitHub Desktop: 2.1.3-beta1
* Operating system: macOS Mojave 10.14.6

## Screenshot

![Screen Shot 2019-09-05 at 1 24 19 PM](https://user-images.githubusercontent.com/2289/64378129-dd10cb00-cfe0-11e9-982a-df369a36332a.png)

**Comment by tierninho** [comment]
Error from the logs:

```
2019-09-05T20:35:54.946Z - error: [ui] `git -c credential.helper= -c protocol.version=2 push origin expose-github-token-to-english-link-checks-workflow --set-upstream --progress` exited with an unexpected code: 1.
stdout:
husky > pre-push (node v10.16.0)

stderr:
To https://github.com/github/help-docs.git
 ! [rejected]                expose-github-token-to-english-link-checks-workflow -> expose-github-token-to-english-link-checks-workflow (non-fast-forward)
error: failed to push some refs to 'https://github.com/github/help-docs.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

(The error was parsed as 10: The repository has been updated since you last pulled. Try pulling before pushing.)
```

**Comment by zeke** [comment]
Update: I'm still seeing this issue for numerous branches, including branches that do not make any modifications to Actions workflow files.

**Comment by zeke** [comment]
@mislav here's the list of all the branches from my `git/config` as you requested: https://gist.github.com/zeke/0adb7f7867762b0977ef4838c328f9d6

The next time I see this issue pop up, I'll share more details here.

**Comment by zeke** [comment]
Ok this is happening to me again today:

<img width="818" alt="Screen Shot 2019-10-04 at 4 22 07 PM" src="https://user-images.githubusercontent.com/2289/66245538-4c9ed680-e6c3-11e9-8cdf-4a69ba89ae46.png">

---



But the branch does exist on GitHub:

<img width="627" alt="Screen Shot 2019-10-04 at 4 22 32 PM" src="https://user-images.githubusercontent.com/2289/66245547-5b858900-e6c3-11e9-9459-802c5c599609.png">

---

After pressing [Publish Branch] in Desktop, I then see:

<img width="731" alt="Screen Shot 2019-10-04 at 4 22 47 PM" src="https://user-images.githubusercontent.com/2289/66245561-6c35ff00-e6c3-11e9-9232-badd2bd08746.png">

---

After pressing [Fetch], I'm back at square one:

<img width="818" alt="Screen Shot 2019-10-04 at 4 22 07 PM" src="https://user-images.githubusercontent.com/2289/66245581-8ff94500-e6c3-11e9-86e4-08a861e6c3cd.png">


Looking in `.git/config`, the branch is absent!

```
$ cat .git/config | grep update-localization-steps
```

**Comment by mislav** [comment]
@zeke 

1. What is your fetch configuration for the origin remote? `git config --get-all remote.origin.fetch`

2. Does "update-localization-steps" exist as a remote tracking branch? `git rev-parse refs/remotes/origin/update-localization-steps`

**Comment by zeke** [comment]
```
$ git config --get-all remote.origin.fetch
+refs/heads/*:refs/remotes/origin/*

$ git rev-parse refs/remotes/origin/update-localization-steps
de6da307eb1fe6b439f5a38ce2cadb4b52bed226
```

**Comment by kuychaco** [comment]
Hmm interesting... @zeke I'm curious to learn more about your workflow and the history of these branches that seem to mistakenly not have a remote tracking branch setup... are you creating these branches locally and then publishing them via Desktop? Is it that things seem to be working fine with pushing/pulling and then suddenly the button reverts back to "Publish branch"?

I'm wondering how much of this issue is Desktop doing something weird, versus your repo being in a weird state to begin with and Desktop not being able to handle that weird state well...

Any additional context about how you checkout and manage branches could be helpful. Along with full log files that might illustrate what's going on under the hood throughout the lifetime of the branch that has issues (starting from branch creation). The **Help | Show Logs** menu items should open the logs folder, and inside those are the log files generated by day. Thanks @zeke!

**Comment by mislav** [comment]
@kuychaco @zeke Here's what I found. I can consistently reproduce this with:

```
git checkout -b feature --no-track origin/feature
```

where "feature" can be any existing remote branch, basically. This checks out the "feature" branch based on the remote tracking bracnh, but doesn't set up the "tracking" or "upstream" merge information, i.e. it _doesn't_ add this config to `.git/config`:

```
[branch "feature"]
  remote = origin
  merge = refs/heads/feature
```

In Desktop, the "feature" branch shows up as: “Your current branch … hasn't been published to the remote yet.”

Git default behavior is that `git checkout -b BRANCH origin/BRANCH` automatically sets up tracking information, but this can be disabled via `git config branch.autoSetupMerge false`:

>        branch.autoSetupMerge
>           Tells git branch and git checkout to set up new branches so that git-pull(1) will appropriately merge from the starting point
>           branch. Note that even if this option is not set, this behavior can be chosen per-branch using the --track and --no-track options.
>           The valid settings are: false -- no automatic setup is done; true -- automatic setup is done when the starting point is a
>           remote-tracking branch; always --  automatic setup is done when the starting point is either a local branch or remote-tracking
>           branch. This option defaults to true.

A way that I can imagine Desktop better handling this case is that if there was a same-named branch on the remote, but the current branch has no tracking configuration, assume that the current branch is being pushed to the same-named branch on the remote.

**Comment by zeke** [comment]
I just ran into this again today:

<img width="1117" alt="Screen Shot 2019-11-18 at 6 09 55 PM" src="https://user-images.githubusercontent.com/2289/69110167-b2a2ab80-0a2e-11ea-8cc9-fc81486654cb.png">

I think @mislav's interpretation of this cause of this issue is accurate.

> A way that I can imagine Desktop better handling this case is that if there was a same-named branch on the remote, but the current branch has no tracking configuration, assume that the current branch is being pushed to the same-named branch on the remote.

☝️ This seems reasonable to me.

**Comment by billygriffin** [comment]
@zeke Echoing @kuychaco, I'd love to hear more about how those branches came to be. How are you creating them (via Desktop or another means)? And are you explicitly setting no-track when creating them like @mislav's repro steps? If so, I'm curious for what purpose. Thanks!

**Comment by zeke** [comment]
I am creating those branches on the command line with `git push origin HEAD`.

Here's my git config:

```
$ git config --list
credential.helper=osxkeychain
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
user.name=Zeke Sikelianos
user.email=zeke@sikelianos.com
core.excludesfile=/Users/z/.gitignore_global
hub.protocol=https
credential.helper=osxkeychain
github.user=zeke
push.default=simple
```

Am I doing it wrong?

**Comment by tomiGoljevscek** [comment]
I have the same issue. Happened after adding an existing repository. I can normally fetch/pull with other clients  like Tortoise.

![image](https://user-images.githubusercontent.com/26965169/94233386-1aa40700-ff08-11ea-89b3-52f9d6ddd944.png)

**Comment by jjstickel** [comment]
I get something like this problem, too, with the Mac desktop app. Using the command line:  I create a branch, commit some changes, and push the branch with `git push origin <branch-name>`. The branch shows up on the web. But the desktop app shows "Publish branch".

**Comment by niik** [comment]
@jjstickel If you're pushing branches from the command line you need to explicitly tell Git to set up the remote tracking branch by using the `-u` parameter. I.e. `git push -u origin <branch-name>`.

Since this issue has gone rather stale I'm going to close it and ask that we open a new issue if this happens in a reliably reproducible way.

**Comment by bmwebster** [comment]
Not sure if this is related, but I managed to end up with a local repo that was missing the following `fetch` entry:

```
[remote "origin"]
	fetch = +refs/heads/*:refs/remotes/origin/*
```

This seems to prevent the app seeing the new remote branch it has just published. Adding this line fixed the issue, and a similar one in VS Code as well.

**Comment by psciascia** [comment]
I have a similar problem to @bmwebster . I create my local repo with the `--single-branch` option, not wanting to even see the master branch. So I used `--single-branch` to create only the Dev branch and branch out out of that one. 
However my gitconfig shows:
```
[remote "origin"]
	url = https://lalala.git
	fetch = +refs/heads/Dev:refs/remotes/origin/Dev
```
If I change Dev for *,  the Publish branch problem goes away.  However I now "see" all branches of the repo, which I did not want in the first place.

**Comment by jamesckemp** [comment]
I added this to the git config and it fixed the issue for me:

```
[branch "master"]
    remote = origin
    merge = refs/heads/master
```

`master` was the branch that was not tracking in the app for me.

**Comment by valentinoPereira** [comment]
> I added this to the git config and it fixed the issue for me:
> 
> ```
> [branch "master"]
>     remote = origin
>     merge = refs/heads/master
> ```
> 
> `master` was the branch that was not tracking in the app for me.

This worked for me

**Comment by phil-warner** [comment]
This is happening for me, with the master branch, in Github Desktop 3.1.4.

Where is the git config located, for me to add the lines suggested by @jamesckemp ?

**Comment by phil-warner** [comment]
> This is happening for me, with the master branch, in Github Desktop 3.1.4.
> 
> Where is the git config located, for me to add the lines suggested by @jamesckemp ?

I found the following command and edited in vi:

git config --global --edit
