### ISSUE TITLE
Can't find repository

### ISSUE THREAD

**Issue by ikerya** [desktop/desktop#8216]
Hello. Step by step problem description:

1. I've created an repository within GitHub. 
2. Then have set up VS Code SFTP. It's made the folder **.vscode**
3. After that i clicked on 'Sync from Remote to Local'
4. And there, in Desktop Client, the problem has been appeared with title Can't find **"<repository_name>"**
5. Trying to do something, I clicked on link **"Check again"**  within GH Desktop App, but nothing changed.

As i correctly understood, the Error appeared when i creating new files and replacing oldest. What can i do?

**Comment by billygriffin** [comment]
Hi @ikerya, thanks for the issue!

Would you mind sharing what your OS version and what version of GitHub Desktop you're using?

I'm also having trouble following your reproduction steps. I don't know where you mean for "Sync from Remote to Local", do you have a screenshot of where you clicked that and then what happened? Also screenshots or more detailed and specific repro steps of what occurred in Desktop afterward would be helpful to help us diagnose.

Thanks!

**Comment by ikerya** [comment]
Sorry, Windows hadn't show me hidden folder and syncing replaced hidden **.git** folder.
