### ISSUE TITLE
How do submodules get updated?

### ISSUE THREAD

**Issue by randy-johnson** [desktop/desktop#8217]
Hello,

I have a coworker who uses github desktop.  When she does a fetch and pull on the master branch it does not do the same on the submodule.    I do not see any menu items  or anything for submodules.  What does she need to do to get the submodules to update?
 

## Version

* GitHub Desktop:

* Operating system:

**Comment by tierninho** [comment]
@randy-johnson Thanks for filing an issue. Please have your friend fill out the template above and include the logs if possible so we have more information.

**Comment by tierninho** [comment]
@randy-johnson  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
