### ISSUE TITLE
Checking out a branch that has submodules that are not on the master does not initialise the submodules

### ISSUE THREAD

**Issue by epignatelli** [desktop/desktop#8221]
## Description

We are in the following situation:  
- We have a repository that does not contain any submodule in the, say, `master` branch  
- We branch out of the master, on a branch with the name `test-submodule-init`. We checkout this branch and add the `https://github.com/desktop/desktop.git `submodule to it. We commit and push the changes.  
- A collaborator clones the repo on its own machine using `desktop`, and then switches to the `test-submodule-init` branch.  
- The `desktop` folder of the submodule is not populated.  

## Version

* GitHub Desktop: `2.1.3`

* Operating system: `Microsoft Windows [Version 10.0.17763.720]`

## Steps to Reproduce

1. Open desktop
2. Clone a new repo (CTR + SHIFT + O) with this url `https://github.com/epignatelli/github-desktop-recursive-pull.git`
2. Switch to the `test-submodule-init` branch.
3. Check that the `desktop` folder is empty
### Expected Behavior

Checking out the branch should initialise the submodules and populate the `github-desktop-recursive-pull\desktop` folder.

### Actual Behavior

Checking out the branch the `github-desktop-recursive-pull\desktop` submodule folder is not populated. The submodule requires an additional `git submodule update --init --recursive` to be initialised.

**Comment by tierninho** [comment]
@epignatelli Thanks for filing this. 

After step 3, I spotted an error in the console, which prevented me from checking out the branch:
```install.ts:23 `git -c credential.helper= -c protocol.version=2 checkout --progress origin/test-submodule-init -b test-submodule-init --recurse-submodules --` exited with an unexpected code: 128.
stderr:
fatal: not a git repository: ../.git/modules/desktop
fatal: could not reset submodule index```

cc @desktop/core as they are more familiar with the expected logic here.

v2.1.3-beta1, mac

**Comment by epignatelli** [comment]
Yeah, @tierninho I experienced the same, actually.

I am working on a fix at this fork: https://github.com/epignatelli/desktop
I Wanted to discuss before I pr. Could you try having a look?

**Comment by outofambit** [comment]
hi @epignatelli i think this may need a similar fix to what was done in https://github.com/desktop/desktop/pull/8218/commits/0db5954793718a31d82fde0f1609c633c766d8ae (using the `--force` flag) but would also be destructive if any local changes had been made in that submodule

**Comment by epignatelli** [comment]
thanks @outofambit! What's the specific reason `--force` was required there?
I tested the code on [the fork](https://github.com/desktop/desktop/compare/development...epignatelli:bugfix/checkout-init-submodules) and the problem was solved for me.  Could you still reproduce after that?

Maybe that way we can avoid forcing?

**Comment by steveward** [comment]
This was reported again in #13016, and I was able to reproduce this issue as well.

**Comment by sergiou87** [comment]
@epignatelli not sure if this is still interesting to you, but I was taking a look at this issue, and it seems the app already updates submodules on checkout, fetch and pull, but only in [beta builds of the app](https://github.com/desktop/desktop/blob/25b66588c96606a1e39de3a38c2c2289328385e0/app/src/lib/feature-flag.ts#L31-L34).

You can download beta builds from https://desktop.github.com/beta and see if that works for you 😄  I'll discuss with the team if this is something we can promote to production builds, but I'd love to get your feedback first.

**Comment by yrafaf** [comment]
@steveward  hi ! plz I have the same issue, if you still remenber how I can switch to the branch (with submodule ) with success, while resettinh correctly the submodule.?
