### ISSUE TITLE
Remote https error when publishing repo

### ISSUE THREAD

**Issue by guptashashank31999** [desktop/desktop#8223]
## Version

* GitHub Desktop:

* Operating system:

### Logs

![Screenshot (50)](https://user-images.githubusercontent.com/48836089/64455617-bbf8c900-d10b-11e9-82b7-837b8aaf1b51.png)

**Comment by tierninho** [comment]
@guptashashank31999 Please fill out the above template so we can better assist you. 

Have you tried:
- Reinstalling Desktop?

else;

- I would recommend deleting the following two directories to allow you to perform a fresh installation:
`%AppData%\GitHubDesktop`
`%LocalAppData%\GitHubDesktop`

Then install GitHub Desktop again and see if you are able to perform a clone operation successfully.

also;

- Are you running any antivirus software on your machine that could be mistakenly flagging the binaries that GitHub Desktop ships with?

- Do you also run into this issue when attempting to clone a repository from the command line using the `git clone` command? If not, try [downloading Git for Windows](https://git-scm.com/download/win) and running a `git clone <REPO_URL>` to see if the same issue occurs. That will help narrow down if something on your machine is flagging that specific file.

**Comment by tierninho** [comment]
@guptashashank31999  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
