### ISSUE TITLE
[Onboarding tutorial] Create tutorial panel with accordion list 

### ISSUE THREAD

**Issue by kuychaco** [desktop/desktop#8226]
(breaking up #8149 into bite-sized issues)

Implement the structure of the panel including the accordion list component. Ensure that only one step can be expanded at a time. 

<img width="708" alt="Tutorial_Repo_Onboarding_Steps_Weekly_Sync_-_Google_Docs" src="https://user-images.githubusercontent.com/7910250/64467863-28ef6d00-d0d2-11e9-84c0-6417ec45edfc.png">

Responsive design: At minimum app size, width of the sidebar will have reduced width.

**Comment by billygriffin** [comment]
This was closed in #8225!
