### ISSUE TITLE
[Onboarding tutorial] Editor interactions

### ISSUE THREAD

**Issue by kuychaco** [desktop/desktop#8227]
(breaking up #8149 into bite-sized issues)

Implement the functionality for the "Install a text editor" and "Edit a file" steps. Use existing logic to detect editor and open a file. 
Detect when steps have been completed.
Consider pointing people to the preferences pane to select an editor.

> Some people will use an editor that is unsupported by GitHub Desktop, and we shouldn't force them to download a supported editor just to complete Step 1. Therefore they'll need to be able to skip this step and let us know they already have an editor.

> If they don't have a detected editor, we can provide options for them to install (Visual Studio Code and Atom). Ideally, when they go through the steps to download and install an editor, it should not require restarting GitHub Desktop in order to detect it.

> For the "Edit a file" step, we should account in our instructions for those who do have an editor detected in Desktop and those who do not.

For "Edit a file" if there is no editor detected do not show "Open Editor" button or keyboard shortcut. 

Clicking "Skip" and "I have an editor" both mark step as complete and move onto next step.

**Comment by Rexogamer** [comment]
Sorry if this is beyond the scope of this, but I had an idea:
If the user skips the step, saying they have an editor already, maybe we could give the option to open an issue on this repo so we can add support for said editor?

**Comment by billygriffin** [comment]
This was closed by #8242. @Rexogamer thanks for the idea! I think given that the primary audience for this feature is brand new users, that likely wouldn't provide much. If the target audience for using this tutorial was a broader subset of folks, I think that could be really interesting.
