### ISSUE TITLE
[Onboarding tutorial] Git interactions

### ISSUE THREAD

**Issue by kuychaco** [desktop/desktop#8228]
(breaking up #8149 into bite-sized issues)

Determine that the following Git steps have been successfully completed by querying the user's local repository:
* Create a branch (ex: verify that current branch is not master)
* Make a commit (ex: verify that there is at least one commit on current branch and verify that it is not master)
* Push to GitHub (ex: verify that current branch is not master, has at least one commit, and that commit is on the remote)

We can consider getting this info by shelling out to git, or simply reading directly from the `.git` folder which may be more performant.

**Comment by billygriffin** [comment]
This was closed by #8242.
