### ISSUE TITLE
[Onboarding tutorial] Track and update completion state

### ISSUE THREAD

**Issue by kuychaco** [desktop/desktop#8230]
(breaking up #8149 into bite-sized issues)

Once we've finished implementing the logic to evaluate completion state for each step, stitch everything together to flow from one step to another. 

<img width="250" alt="63551974-67d6cd80-c4eb-11e9-801d-b212b59d63bd_png__2880×1800__and_Katrina_Work___Trello" src="https://user-images.githubusercontent.com/7910250/64468123-8fc25580-d0d5-11e9-8611-34b5c6b06e9e.png">

> The steps must be completed in order. The only steps that should be able to be skipped are step 1 (install an editor) and step 6 (create a pull request).

For skippable steps we need to figure out how to store completion state when the user decides to skip. Consider if we want this state to be persisted across app refreshes.

Note that each step relies on the preceding steps to be completed correctly. So we will probably want to verify all of the assumptions we are making at the beginning of each step.

> It should be defaulted to the step you’re on

> When a user leaves and comes back, the tutorial remembers the completed steps and opens to the step that is the first incomplete step.

As much as possible, let's try to rely on git repo state to assess what step the user is on, as opposed to tracking this in application state. Unless there is a compelling reason to do otherwise, of course. 

Edge case to consider supporting: The user is on the "Push to GitHub" step, but somehow their local branch gets deleted. Should we set them back to the “Create branch” step, reverting it's status to be incomplete (reverting the subsequent steps as well)?

**Comment by outofambit** [comment]
closed by #8242
