### ISSUE TITLE
[Onboarding tutorial] Create "Welcome" and "You're done" panes

### ISSUE THREAD

**Issue by kuychaco** [desktop/desktop#8232]
(breaking up #8149 into bite-sized issues)

Note that these are not final and are subject to change 
/cc @ampinsk 

Welcome pane:

<img width="711" alt="Onboarding_tutorial__entry_point_·_Issue__8148_·_desktop_desktop" src="https://user-images.githubusercontent.com/7910250/64468312-2728a800-d0d8-11e9-8728-2d94c14d46b4.png">

"You're done" pane:
show the user some jumping off points for what to do next

<img width="704" alt="Onboarding_tutorial__tutorial_repo_steps_·_Issue__8149_·_desktop_desktop" src="https://user-images.githubusercontent.com/7910250/64468327-5dfebe00-d0d8-11e9-8e39-08fb60cb122e.png">

**Comment by billygriffin** [comment]
@ampinsk Are there alternative versions of how this should look at the minimum window size? I think the tutorial pane width decreases, but there's still likely not enough room for this static content in that case.

**Comment by ampinsk** [comment]
I don't have a mockup off hand, but I think the sections can collapse. @kuychaco @outofambit want to pair on this piece when you're up to it?

**Comment by ampinsk** [comment]
Updated designs for the finished state: 

<img width="1440" alt="Guide-Finished" src="https://user-images.githubusercontent.com/10404068/65457236-f9de3880-ddff-11e9-97d5-ce18ba9c2a1c.png">
