### ISSUE TITLE
[Onboarding tutorial] Incorporate metrics

### ISSUE THREAD

**Issue by kuychaco** [desktop/desktop#8233]
Did the user create a tutorial repo?
Record the last/furthest step the user completed in the tutorial

/cc @billygriffin

**Comment by billygriffin** [comment]
Here are some initial thoughts about what we're trying to measure here:

#### Questions we don't currently have metrics to help answer:
1. What % of new users (what's this definition) create a tutorial repo?
2. What % of new users complete the tutorial repo?
3. For those that do not complete the tutorial repo, for each step in the tutorial, what % of users made it to at least that step.
4. Compared to new users who do not complete the tutorial, are users who do complete the tutorial more likely to make subsequent contributions?

#### Questions we (may) have existing metrics to help answer:
1. Did we see an increase in % of users who make at least one commit after shipping the tutorial compared to before?
2. Did we see an increase in % of users who checkout a non-default branch after shipping the tutorial compared to before?
3. Did we see an increase in % of users who push at least a commit to GitHub after shipping the tutorial compared to before?
4. Did we see a reduction in the amount of time for new users to make their first commit?
5. Did we see a reduction in the amount of time for new users to check out a non-default branch for the first time?
6. Did we see a reduction in the amount of time for new users to push at least one commit to GitHub for the first time?
7. Did we see an increase in % of users who make at least one pull request to GitHub after shipping the tutorial compared to before?

#### Needs clarification:
1. How are we defining "new user here"? Is it a GitHub user who doesn't have any repositories or belong to any organizations with repositories on GitHub when they install and sign into GitHub from Desktop?

**Comment by billygriffin** [comment]
As discussed in release check in meeting today, if we have to cut scope on this to get it out for the next release, I think the first iteration should include (1), (2), and (3) if at all possible.

cc: @outofambit @kuychaco @niik @nerdneha @ampinsk @tierninho
