### ISSUE TITLE
Always give option of use mine / theirs for conflicts

### ISSUE THREAD

**Issue by Sairony** [desktop/desktop#8248]
We're using github desktop for a unity3d project, the problem is that prefab files, while text-based, aren't really feasible to resolve conflicts for in most cases. What one want to do is instead take the entirety of either file, this however doesn't seem to be possible from inside github desktop. Since this an option which has its uses for most type of files I propose that the resolve drop down menu always include a use mine / theirs option.

**Comment by tierninho** [comment]
@Sairony Thanks for the suggestion. We do have a selection of theirs/ours in our merge conflict resolution feature, as well as as in certain editors. Examples:

Editor:
![Screen Shot 2019-09-11 at 9 23 13 AM](https://user-images.githubusercontent.com/14828183/64728521-d4a01080-d476-11e9-9fc6-cbcba52a52c5.png)

Desktop:
<img width="730" alt="63143330-995b1080-bfa2-11e9-9e65-80fc2e86d09d" src="https://user-images.githubusercontent.com/14828183/64728523-d538a700-d476-11e9-85a2-b210ca21a6ee.png">

Perhaps you could share a screenshot of what you are seeing when resolving conflicted prefab files? 

Reference: [prefab](https://docs.unity3d.com/Manual/Prefabs.html) files

**Comment by Sairony** [comment]
Here's the dialog:
![conflict_window](https://user-images.githubusercontent.com/8151744/64763657-c3bbd180-d540-11e9-9760-4f0ceec62ebf.png)

A picture from the conflict resolve in VSCode:
![conflict_resolve_vscode](https://user-images.githubusercontent.com/8151744/64763686-d1715700-d540-11e9-9e6e-8b022c638e62.png)

While it is possible to resolve the conflict it's usually not worth it. There's generated ID's & cross references to assets & the files can grow fairly quickly in size, so it's often just faster to just pick one of the two versions.

In my opinion it would be nice to always have the option of using theirs / mine, but that might be down to the fact that I'm coming from other version control systems & clients which always seem to have that feature.

**Comment by Liturgist** [comment]
I am having difficulty with SSIS .dstx files. I am treating them as binary by using `*.dtsx -merge -text` in `.gitattributes`, However, when there is a conflict, GitHub appears to be giving me a text editor to resolve the issue.

How can I specify `mine` or `theirs` in the GitHub Desktop or web interface?

**Comment by mortenblaa** [comment]
@Liturgist a little late here, but you could force the file to be treated as binary by using
`*.dtsx -merge -diff -text`

Note that your file will not be saved in LFS, but rather each change will be part of repo history. In short, it can make your local `.git` folder grow large over time and increase the time to clone.
