### ISSUE TITLE
Doesn't seem to ignore node_modules

### ISSUE THREAD

**Issue by JonahMoses** [desktop/desktop#8251]
## Description
I'm seeing node_modules show up in my desktop diff, when git cli client isn't showing any.

## Version
* GitHub Desktop: 2.1.3
* Operating system: macOS Mojave 10.14.6

## Steps to Reproduce
1. add something new to package.json
2. make changes to some files
3. type in `git status`, witness the files that have changed (because .gitignore has `/node_modules/` within it.
4. open up github desktop, see the list of files that you changed, in additional to all node_module files that have changed.

### Expected Behavior
I'd expect the node_module changes to be ignored

### Actual Behavior
node_modules shows up in the diff for desktop, but not anywhere else.

## Additional Information
Git status:
![image](https://user-images.githubusercontent.com/3462296/64723440-61ea6180-d485-11e9-87b1-75779bb8fe50.png)

desktop:
![image](https://user-images.githubusercontent.com/3462296/64723511-87776b00-d485-11e9-89e8-86ac465de207.png)

.gitignore:
![image](https://user-images.githubusercontent.com/3462296/64725239-0cb04f00-d489-11e9-9948-6ebc07364688.png)

### Logs
[2019-09-11.desktop.production.log](https://github.com/desktop/desktop/files/3602190/2019-09-11.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @JonahMoses! Would you mind running this command from to see what it outputs?

`git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z`

This is the specific `git status` that GitHub Desktop runs.

**Comment by JonahMoses** [comment]
@steveward 
`ॐ  git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z`
```
# branch.oid 9862799649775bf2e4d75fb75cff55029766241a# branch.head LS-11333-streams-table-refresh1 .D N... 100644 100644 000000 1b298ecf7ec99ef3
5fb8d595af51a15fad0d1142 1b298ecf7ec99ef35fb8d595af51a15fad0d1142 js/webapp/src/screens/service_landing_pages/base_tab/base_tab.jsx1 .D N... 100
644 100644 000000 5eb2ad797945bb5d81a863a874ebd0aee2212222 5eb2ad797945bb5d81a863a874ebd0aee2212222 js/webapp/src/screens/service_landing_pages/
base_tab/base_tab.scss1 .D N... 100644 100644 000000 44161e7b137e501851a026460cf7f8f67f8e441f 44161e7b137e501851a026460cf7f8f67f8e441f js/webapp
/src/screens/service_landing_pages/base_tab/base_tab.test.jsx1 .D N... 100644 100644 000000 9108d8544d4e300209c4a0f5030ccd24c87ed22f 9108d8544d4
e300209c4a0f5030ccd24c87ed22f js/webapp/src/screens/service_landing_pages/base_tab/base_tab_helpers.jsx1 .D N... 100644 100644 000000 7e6b78da48
e0f1a95c04d94f7f3e8a5e079085a0 7e6b78da48e0f1a95c04d94f7f3e8a5e079085a0 js/webapp/src/screens/service_landing_pages/base_tab/base_tab_helpers.te
st.jsx1 .D N... 100644 100644 000000 e72656c93f8cf15c1fd4c6d611ebaf253024604e e72656c93f8cf15c1fd4c6d611ebaf253024604e js/webapp/src/screens/ser
vice_landing_pages/base_tab/base_tab_mixins.scss1 .M N... 100644 100644 100644 cb0b0aa252960742e4238df42568f491c85c4c33 cb0b0aa252960742e4238df4
2568f491c85c4c33 js/webapp/src/screens/service_landing_pages/dashboards_tab/dashboards_tab.jsx1 .M N... 100644 100644 100644 51b7a41a0fce6ddc4ad
a440aa042978447477934 51b7a41a0fce6ddc4ada440aa042978447477934 js/webapp/src/screens/service_landing_pages/operations_tab/header_controls.jsx1 .
M N... 100644 100644 100644 925e84204361978c306105cdbb593f251f3089c6 925e84204361978c306105cdbb593f251f3089c6 js/webapp/src/screens/service_land
ing_pages/operations_tab/operation_helpers.js1 .M N... 100644 100644 100644 3070c41577c52be07afa1449ec3f7334ea1872d3 3070c41577c52be07afa1449ec3
f7334ea1872d3 js/webapp/src/screens/service_landing_pages/operations_tab/operations_tab.jsx1 .M N... 100644 100644 100644 e2e7acd18ca76c1cc895f2
c45c202f0c154f7c7e e2e7acd18ca76c1cc895f2c45c202f0c154f7c7e js/webapp/src/screens/service_landing_pages/operations_tab/operations_tab.scss1 .M N
... 100644 100644 100644 e4addf0f75076f7d6a5ca68955d077a110d68c4f e4addf0f75076f7d6a5ca68955d077a110d68c4f js/webapp/src/screens/service_landing
_pages/operations_tab/operations_tab.test.jsx1 .M N... 100644 100644 100644 b650d965b530d6909f809af982fc610fca595fc1 b650d965b530d6909f809af982f
c610fca595fc1 js/webapp/src/screens/service_landing_pages/streams_tab/streams_tab.jsx? js/webapp/src/screens/service_landing_pages/controlled_ta
ble/controlled_table.jsx? js/webapp/src/screens/service_landing_pages/controlled_table/controlled_table.scss? js/webapp/src/screens/service_land
ing_pages/controlled_table/controlled_table.test.jsx? js/webapp/src/screens/service_landing_pages/controlled_table/controlled_table_helpers.jsx?
 js/webapp/src/screens/service_landing_pages/controlled_table/controlled_table_helpers.test.jsx? js/webapp/src/screens/service_landing_pages/con
trolled_table/controlled_table_mixins.scss%  
```

**Comment by mislav** [comment]
@JonahMoses Thank you for the extra info!

It looks like you are in the `lightstep/js/webapp` directory when you run `git status`. If you go 2 directories up into the `lightstep` directory, which I presume is your top-level project directory, and run `git status`, do entries under `node_modules` show up?

**Comment by JonahMoses** [comment]
@mislav the `node_modules` don't show up whether I'm in `lightstep/` root directory or inside the `lightstep/js/webapp/` directory.

**Comment by mislav** [comment]
@JonahMoses Thank you.

You have shown us the contents of `js/webapp/.gitignore`. Can you also paste us the (relevant) contents of `.gitignore` in the top-level of your project, if there is one?

**Comment by JonahMoses** [comment]
```
  1 .idea
  2 .DS_Store
  3 /test-results/
  4 /logs/
  5 go/src/tmp/
  6 .envrc
  7 bosh/cm_sockets
  8 dev-sarahhaskins.yaml
  9 ci/steamroll_config.yml
 10 */**/node_modules
 11 .shell/bin/fly
 12 .shell/bin/bosh
 13 certs/letsencrypt*
 14 certs/._letsencrypt
 15 certs/certbot.log
 16 *.code-workspace
 17 /bin/
 18 /tmp/
 19 .developer.sh
 20 .devmode.sh
 21 coverage.txt
 22 .modd.conf.*
```

that's the `.gitignore` from the root directory

**Comment by mislav** [comment]
@JonahMoses When I create a new repository with some files under `node_modules` and this `.gitignore`:

```
*/**/node_modules
```

then my `git status` lists those files as untracked (i.e. they are _not_ successfully ignored). If I change the expression to `**/node_modules`, then it works.

My git version is 2.22.0. This is also consistent with git 2.19.2 which we embed in your version of Desktop. Which `git version` do you have?

Is it an option for you to amend the `node_modules` entry in your `.gitignore` so that it behaves consistently between Desktop and your system version of git?

**Comment by JonahMoses** [comment]
my git version is 2.21.0

uncertain if I can change that atm, I can look into it tomorrow though. Thanks for all your help with this <3

**Comment by JonahMoses** [comment]
Can confirm that changing it to `**/node_modules` does get rid of it within desktop

**Comment by mislav** [comment]
@JonahMoses Great! Glad you solved it.

I'm not sure if there's anything to be done from our side. I don't think this is something to be "fixed"; it seems to be that the problem was a subtle difference in behavior between your system git version and the one embedded within Desktop.

Please feel free to close this as resolved, unless there's something else that you would suggest us do for a future release? Thank you!

**Comment by JonahMoses** [comment]
@mislav Thanks for all your help!

**Comment by cezary-z** [comment]
That may happen if your .gitignore file encoding is set to UTF-16. Then git seems not to recognize it. I came across that issue when I created the .gitignore file in cmd:
`echo "node_modules/" > .gitignore`
The .gitignore file was created with UTF-16 encoding (with BOM) and it didn't work until I changed the encoding to UTF-8.
