### ISSUE TITLE
add some css transitions to the tutorial panel

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#8254]
we made a few css transitions easy to add in #8225 :
* rotating chevron on issue open
* animating color of circles behind the checkmark/step number
* opacity of step summary text

other things i can think of that would be slightly more work but still pretty easy:
* height of steps in panel (upon open and close)
* slide in/out tutorial panel

it would also be fairly straightforward to do some sort of "keepalive" animation on the checkmark/step number circle icon for the step the user is currently working on 🤷‍♀ 

/cc @ampinsk 😃

**Comment by billygriffin** [comment]
@ampinsk @outofambit Do y'all still think this is something worth prioritizing? I'm know these felt like nice potential things to make it feel like a cleaner experience, so I'm curious whether you think what we have is sufficient or whether we should try to knock one or more of these out.

**Comment by outofambit** [comment]
I think what we have currently is sufficient. Gonna close this out, let us know if you disagree @ampinsk and we can reopen/revisit!
