### ISSUE TITLE
TortoiseGit steals GitHub Desktop links (closed error #4754)

### ISSUE THREAD

**Issue by tobias-loew** [desktop/desktop#8258]
The problem described in #4754 still exists.

and here's a possible solution:

I the problem is the missing registration of GitHubDesktop at HKEY_LOCAL_MACHINE\SOFTWARE\RegisteredApplications and HKEY_LOCAL_MACHINE\SOFTWARE\GitHubDesktop.
I described the solution here: https://stackoverflow.com/a/57905263/1997370
Please add the missing registration to the GitHubDesktop-installer

**Comment by Rexogamer** [comment]
Where exactly is the code related to setting up the registry stuff?

**Comment by tobias-loew** [comment]
@Rexogamer: which code do you mean?

The registry-settings that should be added are (in reg-file - format)
```
[HKEY_LOCAL_MACHINE\SOFTWARE\GitHubDesktop]

[HKEY_LOCAL_MACHINE\SOFTWARE\GitHubDesktop\Capabilities]

[HKEY_LOCAL_MACHINE\SOFTWARE\GitHubDesktop\Capabilities\UrlAssociations]
"github-windows"="github-windows"
"x-github-client"="x-github-client"

[HKEY_LOCAL_MACHINE\SOFTWARE\RegisteredApplications]
"GitHubDesktop"="Software\\GitHubDesktop\\Capabilities"
```

but I haven't searched the GitHubDesktop project for the installer code, where it should be added to

**Comment by Rexogamer** [comment]
I’m trying to find said installer code

**Comment by Rexogamer** [comment]
@outofambit mind giving some info on this?

**Comment by tobias-loew** [comment]
I think I found where it shoud be added:
app\src\main-process\main.ts line 260 calls electron's app.setAsDefaultProtocolClient (line 236 - 244)  for each protocol
directly below would be a good place to insert the additional registry-code
```
  if (__WIN32__) {
    // code writing additional registry settings...
  }
```

**Comment by tobias-loew** [comment]
the following code should do (it's from electrons workaround https://github.com/electron/electron/issues/14108
There's a additional dependency (I'm not sure if that's ok)

```
import {Registry} from 'rage-edit';
```

and the code for app\src\main-process\main.ts inserted after line 260
```
if(__WIN32__) {

    (async () => {
        await Registry.set('HKCU\\Software\\GitHubDesktop\\Capabilities', 'ApplicationName', 'GitHubDesktop');
        await Registry.set('HKCU\\Software\\GitHubDesktop\\Capabilities', 'ApplicationDescription', 'GitHubDesktop');

        await Registry.set('HKCU\\Software\\GitHubDesktop\\Capabilities\\URLAssociations', 'github-windows', 'github-windows');

        await Registry.set('HKCU\\Software\\GitHubDesktop\\Capabilities\\URLAssociations', 'x-github-client', 'x-github-client');

        await Registry.set('HKCU\\Software\\RegisteredApplications', 'GitHubDesktop', 'Software\\GitHubDesktop\\Capabilities');
    })();
}
```

**Comment by Rexogamer** [comment]
If we were to use this solution, we could also possibly redo some of the other protocols

**Comment by Rexogamer** [comment]
Per @niik on my PR, this might be Electron-related

**Comment by ISS2718** [comment]
Hey every one, 
I run this code and I managed to use the "Open in Desktop", but in Opera not worked Chrome and Edge only (at least in my tests).

---

```
Windows Registry Editor Version 5.00

[-HKEY_CLASSES_ROOT\github-windows]

[HKEY_CLASSES_ROOT\github-windows]
"URL Protocol"=""
@="URL:github-windows"

[HKEY_CLASSES_ROOT\github-windows\shell\open\command]
@="\"C:\\Users\\USERNAME\\AppData\\Local\\GitHubDesktop\\app-2.5.5\\GitHubDesktop.exe\" --protocol-launcher \"%1\""

[-HKEY_CLASSES_ROOT\x-github-client]

[HKEY_CLASSES_ROOT\x-github-client]
"URL Protocol"=""
@="URL:x-github-client"

[HKEY_CLASSES_ROOT\x-github-client\shell\open\command]
@="\"C:\\Users\USERNAME\\AppData\\Local\\GitHubDesktop\\app-2.5.5\\GitHubDesktop.exe\" --protocol-launcher \"%1\""

[HKEY_LOCAL_MACHINE\SOFTWARE\GitHubDesktop]

[HKEY_LOCAL_MACHINE\SOFTWARE\GitHubDesktop\Capabilities]

[HKEY_LOCAL_MACHINE\SOFTWARE\GitHubDesktop\Capabilities\UrlAssociations]
"github-windows"="github-windows"
"x-github-client"="x-github-client"

[HKEY_LOCAL_MACHINE\SOFTWARE\RegisteredApplications]
"GitHubDesktop"="Software\\GitHubDesktop\\Capabilities"
```
---

I found this solution [here](https://www.thetopsites.net/article/52747051.shtml)

**Comment by aviveldan** [comment]
Hey, any updates on this issue?
I still have this issue on Windows 11.

**Comment by tidy-dev** [comment]
[As this needs to be addressed in Electron](https://github.com/desktop/desktop/pull/8413#issuecomment-541552917), closing as not planned.
