### ISSUE TITLE
Unable to clone or login

### ISSUE THREAD

**Issue by shivendra-t** [desktop/desktop#8259]
## Version

* GitHub Desktop: 2.1.3

* Operating system: Windows 10

## Steps to Reproduce

1. If you are not logged in, try to login.
2. If you are already logged in, try to clone.

### Actual Behavior

1. Popup with error "Failed to fetch" appears when you try to login
2. None of the repositories from my github.com account appear when you try to clone

## Additional Information

1. Fetch, pull and push work fine.
2. I'm working behind a proxy which means git:// links don't work. All the repos have been cloned using the https:// link.
3. I'm able to login and clone using git bash.
4. Downgrading to version 2.1.0 seems to fix it.

### Logs

2019-09-13T11:14:16.488Z - warn: [ui] fetchRepositories: TypeError: Failed to fetch

**Comment by steveward** [comment]
@shivendra-t thanks for the report. Could you upload the full log file from a day where you experienced this error? Thanks!

**Comment by shivendra-t** [comment]
[2019-09-13.desktop.production.log](https://github.com/desktop/desktop/files/3614656/2019-09-13.desktop.production.log)
@steveward here are the logs for 2019-09-13 
Please note that after reporting this issue I switched to version 2.1.0, so the logs after around 14:30:00 UTC are not relevant

**Comment by tm8544** [comment]
Sounds just like #8141, which was issued almost 4 weeks ago.

@shivendra-t  could you provide me a way to download your copy of version 2.1.0?

**Comment by shivendra-t** [comment]
@tm8544 I just happened to have an old setup with me, you could try https://www.techspot.com/downloads/6741-github-desktop.html though I haven't used it myself

**Comment by CokePokes** [comment]
This is happening for me as well with this error on Mac: 

```default	23:45:07.228808 -0500	GitHub Desktop Helper	UNIX error exception: 17
```

**Comment by tierninho** [comment]
@shivendra-t Please double check that your other applications which are routed through the proxy server are still working. If all is ok, try reinstalling Desktop.

Also, please see this reference from another user with the same issue: https://github.com/desktop/desktop/issues/6900#issuecomment-466016136

There was a security update which affected Git for Windows, however I am unsure what relation this has to your issue https://github.com/desktop/desktop/pull/8101

Overall, I am glad you are in a good place with v2.1.0 for the time being.

**Comment by tierninho** [comment]
Going to close this issue for now. @shivendra-t Let us know if you experience the same issue when upgrading back to v2.1.3.

**Comment by shivendra-t** [comment]
@tierninho upgarding to 2.1.3 gave me the same issue again.
Infact, everytime I close the application and reopen it, it automatically updates and the issue resurfaces. Another thing that would help is an option to turn off updates.

**Comment by shivendra-t** [comment]
Hi @tierninho, I'd appreciate it if you reopened this issue

**Comment by shivendra-t** [comment]
@steveward I am behind a firewall, but I'm not sure how it would specifically block Github desktop. As I mentioned above, everything works when I use git bash and also when I downgrade. So it has to be a change made to the login authentication flow between 2.1.0 and 2.1.3. Are there any domains other than github.com used by the login authentication?

**Comment by steveward** [comment]
@shivendra-t there wouldn't be any other domains other than the GitHub API. Are you using the `Sign in with your browser` option in the `Accounts` view to log in to your GitHub account?

**Comment by tierninho** [comment]
@shivendra-t  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
