### ISSUE TITLE
Merge Issue deleting code

### ISSUE THREAD

**Issue by scbasile02** [desktop/desktop#8260]
There was a merge committed in the Matters repository by maheshgc committed yesterday that wiped out a bunch of code. 

The change number is 23613749 in the repository  https://github.com/nayadevsg/Matters.

We are unable to roll it back since it says nothing was committed but it clearly wiped out a bunch of changes (4 days worth).

Please assist in why this happened and how to roll this back ourselves in the future.

Scary stuff.
Steve

**Comment by scbasile02** [comment]
We rolled the change back. 

We would like to know what happened though. 

Please do not do anything.

**Comment by steveward** [comment]
@scbasile02 thanks for the report. Just to clarify -- was this change merged in locally using GitHub Desktop and then pushed to the repository? Any extra details you can share would be helpful.
