### ISSUE TITLE
Akito13:nim2019

### ISSUE THREAD

**Issue by live-user0001** [desktop/desktop#8267]
**Please describe the problem you think should be solved**
A clear and concise description of what the problem is and who else might be impacted. Screenshots are encouraged.

Example:

> “When I run into a merge conflict, I don’t know where to go to resolve it. Anyone who works off of multiple branches will likely run into this problem at least occasionally.”

**[Optional] Do you have any potential solutions in mind?**
A clear and concise description of one or more solutions you think might solve the problem. Please include any considered drawbacks or tradeoffs, and how users might use your solution(s). Screenshots or mockups are helpful here!

**Comment by mislav** [comment]
There doesn't seem to be any information in this bug report. If you're trying to report a bug, please use the template https://github.com/desktop/desktop/issues/new?template=bug_report.md and replace the placeholders with information about what specific action you were trying and how Desktop errored out or elsewhere failed to meet your expectations. Thank you!
