### ISSUE TITLE
 The template is designed to avoid  The template is designed to avoid unnecessary

### ISSUE THREAD

**Issue by Rodion8888** [desktop/desktop#8271]
## Version

* GitHub Desktop:

* Operating system:

**Comment by Rodion8888** [comment]
The template is  The template is designed to avoid  The template is designed to avoid unnecessary

**Comment by Rodion8888** [comment]
<p><a href="http://foo.bar.baz/test?q=hello&amp;id=22&amp;boolean">http://foo.bar.baz/test?q=hello&amp;id=22&amp;boolean</a></p>

**Comment by mislav** [comment]
Hi, there doesn't seem to be any information in this bug report, therefore I'm going to close this. If you are trying to report a bug, please follow the template https://github.com/desktop/desktop/issues/new?template=bug_report.md and include any information that pertains to your use-case. Thank you!
