### ISSUE TITLE
unable to merge unrelated histories

### ISSUE THREAD

**Issue by luiper79** [desktop/desktop#8279]
unable to merge unrelated histories in this repository

**Comment by mislav** [comment]
Hi, I'm not sure whether you are describing a bug or requesting a feature. To help us understand your use-case better, could you elaborate more on what did you try to merge together, what was the initial setup, what action did you select in Desktop, and how the behavior of Desktop differed from the result that you expected. If there was an error message, please include the error message as well. Thank you!

**Comment by tierninho** [comment]
@luiper79 As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
