### ISSUE TITLE
Case sensitive file name change not recognized

### ISSUE THREAD

**Issue by ariffjeff** [desktop/desktop#8280]
## Description

Github Desktop does not show any changes in the 'Changes' side panel when a file is renamed to a different case sensitive version of itself.

 i.e. hello.txt --> Hello.txt is not recognized. 

This is a problem for web developers who might need to rename a file in this manner because of a URL interpretation issue. In a worst case scenario, a web dev might not notice that a filename change didn't make it into a commit and are now losing their mind as to why their webpage is linking users to a 404. Even worse the problem doesn't show up when developing in a local environment so a dev wouldn't know until the bad URL went up to their server. All because of a one letter case sensitive change that never made it to commit.

## Version

* GitHub Desktop: 2.1.3

* Operating system: Microsoft Windows [Version 10.0.18362.356]

## Steps to Reproduce

1. Create a new folder on your desktop
2. Create a new text file in that directory called 'hello.txt'
3. Create a new local repo from this directory
4. Rename 'hello.txt' to 'Hello.txt'

### Expected Behavior

'Hello.txt' should show up as a change in the 'Changes' side panel in Github Desktop because its filename has been changed.

### Actual Behavior

Nothing.

### Logs

[2019-09-16.desktop.production.log](https://github.com/desktop/desktop/files/3614628/2019-09-16.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @ariffjeff. This is a confusing aspect of Git, but this is the correct behavior. For more information I would recommend taking a look at the reply @shiftkey wrote in a similar issue:
https://github.com/desktop/desktop/issues/2672#issuecomment-329011490. There's also a good article about this over in the [Microsoft docs](https://docs.microsoft.com/en-us/vsts/repos/git/case-sensitivity?view=vsts).

I'm going to close this issue out as I believe #2672 covers this problem. If that's not the case please let me know and I'll reopen and we can take another look.

**Comment by anniewey** [comment]
Setting `ignorecase=false` in `.git/config` works as suggested in [#2672 (comment)](https://github.com/desktop/desktop/issues/2672#issuecomment-329011490)

> Thanks for the report @ariffjeff. This is a confusing aspect of Git, but this is the correct behavior. For more information I would recommend taking a look at the reply @shiftkey wrote in a similar issue: [#2672 (comment)](https://github.com/desktop/desktop/issues/2672#issuecomment-329011490). There's also a good article about this over in the [Microsoft docs](https://docs.microsoft.com/en-us/vsts/repos/git/case-sensitivity?view=vsts).
> 
> I'm going to close this issue out as I believe #2672 covers this problem. If that's not the case please let me know and I'll reopen and we can take another look.
