### ISSUE TITLE
可否设置一个可更改语言的选项

### ISSUE THREAD

**Issue by yugongzhou** [desktop/desktop#8281]
**Please describe the problem you think should be solved**
A clear and concise description of what the problem is and who else might be impacted. Screenshots are encouraged.

Example:

> “When I run into a merge conflict, I don’t know where to go to resolve it. Anyone who works off of multiple branches will likely run into this problem at least occasionally.”

**[Optional] Do you have any potential solutions in mind?**
A clear and concise description of one or more solutions you think might solve the problem. Please include any considered drawbacks or tradeoffs, and how users might use your solution(s). Screenshots or mockups are helpful here!

**Comment by mislav** [comment]
Sorry, our team does not speak Chinese. I've translated the above as: “Can I set an option to change the language?” Right now, there is no option to use GitHub Desktop in any language other than English. However, we do have some documenation in Chinese that might help you out: https://help.github.com/cn/desktop

**Comment by Johnserf-Seed** [comment]
https://github.com/Johnserf-Seed/GitHub-Desktop-Chinese-Language-Pack
