### ISSUE TITLE
In case of Manual Conflict in the file name is not shown

### ISSUE THREAD

**Issue by rahulgolwalkar** [desktop/desktop#8282]
As you can see in the screen shot - only the first part of the URL shown in case of Manual conflict

Expected behaviour - it would be good if we can see the file name and a really good feature if we can see the whole path when we hover mouse over it.

<img width="260" alt="Screenshot 2019-09-16 at 12 53 14 PM" src="https://user-images.githubusercontent.com/629348/64940531-d0faf800-d881-11e9-9f3c-914ff4e87ebd.png">

**Comment by steveward** [comment]
Thanks for opening this @rahulgolwalkar. This is being tracked in https://github.com/desktop/desktop/issues/6666 -- you can follow along there for updates about this. I'm going to close this issue out.
