### ISSUE TITLE
Github desktop keeps crashing or displaying a blank white screen

### ISSUE THREAD

**Issue by pgmadhu** [desktop/desktop#8283]
Github desktop keeps crashing or displaying a blank white screen

Error message Github desktop has stopped working and Problem details is below

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	GitHubDesktop.exe
  Application Version:	2.1.3.0
  Application Timestamp:	5d12fbd0
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.3.9600.19304
  Fault Module Timestamp:	5c7f684f
  Exception Code:	c0000005
  Exception Offset:	00000000000cb210
  OS Version:	6.3.9600.2.0.0.16.7
  Locale ID:	1033
  Additional Information 1:	d25e
  Additional Information 2:	d25e6a61df0e6ee70cf73ed57f45ab64
  Additional Information 3:	6f52
  Additional Information 4:	6f52ee721d6b97312eb22669c7ffb4dd

**Comment by steveward** [comment]
Thanks for the report @pgmadhu. It sounds like you may be running into something similar to https://github.com/desktop/desktop/issues/3757. Can you try resetting GitHub Desktop by following these steps to see if that helps?

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop

Let us know if that doesn't get things working.

**Comment by pgmadhu** [comment]
I tried this, it isnt working. 


Regards,Madhu

On Monday, September 16, 2019, 11:57 AM, Steve Ward <notifications@github.com> wrote:


Thanks for the report @pgmadhu. It sounds like you may be running into something similar to #3757. Can you try resetting GitHub Desktop by following these steps to see if that helps?
   
   - Close GitHub Desktop
   - Remove all of the files in %APPDATA%\GitHub Desktop\
   - Restart GitHub Desktop

Let us know if that doesn't get things working.

**Comment by steveward** [comment]
@pgmadhu thanks for the update. I would recommend trying a full reinstall by deleting the `%LocalAppData%\GitHubDesktop` and the `%AppData%\GitHub Desktop` directories, and then try reinstalling again.

**Comment by pgmadhu** [comment]
This also didnt work. 


Regards,Madhu

On Monday, September 16, 2019, 4:00 PM, Steve Ward <notifications@github.com> wrote:


@pgmadhu thanks for the update. I would recommend trying a full reinstall by deleting the %LocalAppData%\GitHubDesktop and the %AppData%\GitHub Desktop directories, and then try reinstalling again.

**Comment by steveward** [comment]
@pgmadhu It looks like you are running version 6.3.9600.2.0.0.16.7 of Windows, which appears to be Windows Server 2012. Is that correct?

**Comment by pgmadhu** [comment]
Yes, my machine is windows server 2012 R2 and i am not sure of  git hub version. But i am using the latest one from your portal. 


Regards,Madhu

On Wednesday, September 18, 2019, 8:25 AM, Steve Ward <notifications@github.com> wrote:


@pgmadhu It looks like you are running version 6.3.9600.2.0.0.16.7 of Windows, which appears to be Windows Server 2012. Is that correct?

**Comment by steveward** [comment]
@pgmadhu we don't officially support Windows Server 2012, but it should work. Has GitHub Desktop previously worked on this machine?

Also, the error you are getting can sometimes be resolved by opening up an elevated command prompt and running the `sfc /scannow` command to check if there are any system issues that need repairing.

**Comment by pgmadhu** [comment]
Okay thanks steve. It completed and displayed no violations found. Since its not in your scope i will look for other options. thanks for helping on this. 


Regards,Madhu

On Thursday, September 19, 2019, 12:44 PM, Steve Ward <notifications@github.com> wrote:


@pgmadhu we don't officially support Windows Server 2012, but it should work. Has GitHub Desktop previously worked on this machine?

Also, the error you are getting can sometimes be resolved by opening up an elevated command prompt and running the sfc /scannow command to check if there are any system issues that need repairing.
