### ISSUE TITLE
gitignore is insufficient at repository creation

### ISSUE THREAD

**Issue by gatto** [desktop/desktop#8284]
**Please describe the problem you think should be solved**
When creating a repository with Desktop, I can only add one .gitignore file. This means that I can't at that time add both the language-specific .gitignore AND the platform specific .gitignore (in my case, macOS).
**Also**, I can only add language .gitignores in the root directory, and no */Global* gitignores.

Example:

> “I create a new repository for my python code on my Mac laptop. I can add the python.gitignore but not the macOS.gitignore.”

**[Optional] Do you have any potential solutions in mind?**
Adding both the following 2 capabilities:
1. adding more than one .gitignore file at repository creation
2. being able to add global .gitignores (like for instance macOS.gitignore)

This would allow to add language AND platform gitignores. I don't see potential drawbacks.

One possible mockup for number 1 would be: when, and if, a first gitignore is added, then another drop-down box appears with the possibility to add another.

**Comment by tierninho** [comment]
@gatto Thank you for the suggestion. 

Currently there is only one `gitignore` file, but you can create a global `gitignore` governing all your repos or add another one as part of a submodule, however this is probably not relevant to your case. 

Nevertheless, we will consider your suggestion on future iterations.
