### ISSUE TITLE
Do you have plans for multilingual support?

### ISSUE THREAD

**Issue by joyfuI** [desktop/desktop#8289]
Do you have plans for multilingual support?
I want to contribute to Korean translation.
If you have a schedule please tell us how to proceed.

**Comment by billygriffin** [comment]
Hi @joyfuI, thanks so much for reaching out and for the offer to contribute to a Korean translation! We've been slowly working on localizing our help documentation in a few languages and we're building that out over time (https://help.github.com/en). We've discussed localization of the GitHub Desktop app internally, but haven't yet had the bandwidth to prioritize it alongside improving the product. It's something that several of us are really excited about the prospect of, but we aren't able to say when we'll be able to do that so I'm going to close this issue for now. I will definitely reach out in this issue if it does happen and let you know how you can get involved. Thank you SO much for the issue - it's really nice to see people eager to help make the product more inclusive and accessible around the world.
