### ISSUE TITLE
ignores ignore file

### ISSUE THREAD

**Issue by JeffdeEff** [desktop/desktop#8291]
## Version

* GitHub Desktop:

* Operating system:

**Comment by JeffdeEff** [comment]
Doesnt seem to matter how many times I add or have the software add Web.config or *.config to the ignore file. The desktop app always wants me to commit my web.config file.  Then when I uncheck it and attempt to pull it errors out and aborts because it would conflict with my web.config.. So frustrating.

**Comment by steveward** [comment]
@JeffdeEff was the file `web.config` in your repository previously committed? If so, this would cause it not to be ignored until you run a specific command from the command line:

`git rm --cached web.config`

Then you should be able to ignore the file correctly. This [article](https://help.github.com/en/articles/ignoring-files) has some more information about ignoring files. Let me know if that doesn't help and we can continue to look into this further.

**Comment by tierninho** [comment]
@JeffdeEff  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
