### ISSUE TITLE
switch new branch

### ISSUE THREAD

**Issue by Parmerlee** [desktop/desktop#8297]
## Description
during I modify my code in branch eg:1.1,then the remote has builded  a new branch eg:1.2。when I checkout  to new 1.2,and I choose "Bring my changes to 1.2"**,but nothing was brought to the 1.2,and when I check back to 1.1,the modifies was gone(no commit in 1.1)**。This happened 2 times。

## Version

* GitHub Desktop:
 V2.1.3

* Operating system:
windos 10.0.17134.950

**Comment by steveward** [comment]
@Parmerlee thanks for the report. Could you upload the log file from the day this issue occurred? That should give us a better idea of what may have happened.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

**Comment by tierninho** [comment]
This seems like a result of the stashing bug, which will be fixed in https://github.com/desktop/desktop/issues/8084

**Comment by darnellbelcourt** [comment]
I dont need to change any thing I would like to have everyone one but me removed from the account I want these people charged n put in jail for fruad

**Comment by billygriffin** [comment]
Confirmed with @kuychaco that this should hopefully be fixed by #8085 and is likely the same underlying problem as #8084, so I'm going to close this issue as a duplicate. Sorry about the difficulties!
