### ISSUE TITLE
Feature Commenting on a Commit/push directly from the change view

### ISSUE THREAD

**Issue by jgwill** [desktop/desktop#8300]
**Please describe the problem you think should be solved**

I would like to comment on an image being committed/pushed to the repo.

**[Optional] Do you have any potential solutions in mind?**

![image](https://user-images.githubusercontent.com/23141173/65363074-1435cd80-dbd8-11e9-83cf-fa40e4517f96.png)

My best regards, I love Git Desktop :)

Guillaume

**Comment by billygriffin** [comment]
Hi @jgwill, thanks for the issue! Just to help me understand this a bit better, I'm curious why you're looking to do this outside the context of the commit message itself, and how you're achieving a similar goal today?

**Comment by tierninho** [comment]
@jgwill  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
