### ISSUE TITLE
Umm...I logined but github desktop said "Your id/password was wrong"

### ISSUE THREAD

**Issue by Yoruroong** [desktop/desktop#8303]
## Version

* GitHub Desktop:

* Operating system:

**Comment by niik** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that
we can be certain we have all the information we need to address your
submission efficiently. This allows the maintainers to spend more time fixing
bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by e122864** [comment]
您好！

王奐閎 (e1r22864@gmail.com) 已邀請您檢視 Dropbox 上的檔案「 檔案 2019-10-1 06 33 22 」。

 檢視檔案 

祝您使用愉快！
Dropbox 工作團隊 
 王奐閎 等人會知道您是否在查看檔案。其他透過 Dropbox 分享給您的檔案，也可能顯示這項資訊。前往說明中心 瞭解詳情 。 

[1]: https://www.dropbox.com/l/scl/AAA74kX83PF2NLwDOLCcPJETUclqO33DSiE
[2]: https://www.dropbox.com/l/AACrYkKB4U1asGbKAy0qCc0RDixA10q96Rg

**Comment by e122864** [comment]
Join j on Slack

e1r22864 (e1r22864@gmail.​com) has invited you to join the Slack
workspace j. Join now to start collaborating!

Join Now
[https://join.slack.com/t/j-s828055/invite/enQtODE2Mzc2NDc1ODYzLWUyMWM2ZGFmODc2MTI0YWQzNTJmNjM0NjBjMDdhNzQ2OWM0OThhOTIwMjMwMmY0MTI0NTAxYzRkMjAyZDRmMTU?x=x-p801727872306-814047707012-806610563153]

Workspace name: j
Workspace URL: j-s828055.slack.com

**Comment by e122864** [comment]
Set up two-factor authentication

j now requires two-factor authentication (2FA). This extra layer of
security protects your account by requiring you to log in using an
authentication code sent to your phone.

Starting on November 8th at 6:00 PM, you’ll need to have set up 2FA in
order to access your account. Use the button below to get started, and
if you’d like to learn more, head to our Help Center article
[https://slack.com/help/articles/204509068-Enabling-two-factor-authentication].

Set Up 2FA
[https://j-s828055.slack.com/x-p801727872306-814527995445-812467577122/account/settings/2fa_choose]

Workspace name: j
Workspace URL: j-s828055.slack.com
Email: reply@reply.github.com
Sign In
[https://j-s828055.slack.com/x-p801727872306-814527995445-812467577122/signin]

**Comment by e122864** [comment]
Your password for j has been reset. To sign back into Slack, create a
new password.
https://j-s828055.slack.com/x-p801727872306-814527995445-817338336081/reset/enQtODI1MjU2Nzg2MzIwLTc2YjM2ZGJlZTNkMDk1NjdkZDU1YWVlZmVkOWY4MGQxNTkxYmMxZWUwYmE5ZjVmMGE2ZDdiZDRiNTkwNjhlNzM
