### ISSUE TITLE
Cannot authenticate user account in a non-standard user namespace at the remote repository (EDIT might not be Github Desktop's problem)

### ISSUE THREAD

**Issue by YourBuddyBill** [desktop/desktop#8304]
## Description

There's a private repository that I am trying to clone. It is located at https://git.knockturnmc.com/knockturn/lore/lessons-y1.git
This is a domain using the Gitlab framework.
Github Desktop tries to authenticate with git.knockturnmc.com/knockturn and tries to authenticate me as if my user was located at git.knockturnmc.com/knockturn/Your_Buddy_Bill which results in a 500 internal server error because the authentication doesn't work.
It SHOULD be trying to authenticate with my actual user profile at git.knockturnmc.com/Your_Buddy_Bill but I have found no way to change the path that it tries to authenticate to. How do I fix this?

## Version

* GitHub Desktop: Version 2.1.3

* Operating system: Microsoft Windows [Version 10.0.18362.295]

## Steps to Reproduce

Tried to clone a repository hosted on a site that uses an apparently non-conventional namespace setup, https://git.knockturnmc.com/knockturn/lore/lessons-y1.git
### Expected Behavior

As expected for first access, the authentication will fail, putting up the error message ""We were unable to authenticate with git.knockturnmc.com. Please enter your username and password and try again." If I put in my username and the credential from the site, it should authenticate me such that the URL of the credential as seen in the credential manager is git.knockturnmc.com/Your_Buddy_Bill and from there it should succeed and clone the repository.

### Actual Behavior

The Authentication Failed window pops up as expected for first-time use. However, it states that "We were unable to authenticate with git.knockturnmc.com/knockturn. Please enter your username and password and try again."
I put in the username (Your_Buddy_Bill) and the credential I was given by the site (as the site is using the Gitlab system), but the result is an error message:
"Cloning into 'C:\Users\NAME REDACTED\Documents\GitHub\lore\lessons-y1'...
fatal: unable to access 'https://git.knockturnmc.com/knockturn/lore/lessons-y1.git/': The requested URL returned error 500"
The authentication token as shown in the Credentials Manager indicates that the token is valid authentication for "git.knockturnmc.com/knockturn/Your_Buddy_Bill", which is not a valid username to the best of my knowledge.

## Additional Information

Ignore the stuff at the top of the log file, that's from a much older thing i never got around to deleting.

### Logs

[2019-09-21.desktop.production.log](https://github.com/desktop/desktop/files/3638852/2019-09-21.desktop.production.log)

EDIT: It's possible the issue here is actually on gitlab's end or on the end of the instance the site is running, apparently other people from our group have been getting similar errors when they try to use HTTPS even with other programs.

**Comment by niik** [comment]
> EDIT: It's possible the issue here is actually on gitlab's end or on the end of the instance the site is running, apparently other people from our group have been getting similar errors when they try to use HTTPS even with other programs.

Hi @YourBuddyBill, I'm sorry to hear you're having problems authenticating. Unfortunately I don't think there's much we can do to help here. The server doesn't appear to accept the username and password you've provided to GitHub Desktop. We haven't heard any other reports of problems with GitLab authentication recently and our logic for authentication hasn't changed recently. The only tip I can give you to troubleshoot further is that you can access the developer tools console by clicking on the `View` menu and then `Toggle Developer Tools`. That will give you a standard Chrome DevTools window with a network request debugger. If you find something that would indicate a bug with GitHub Desktop please let us know here or in a new issue but for now I'm going to close this issue.
