### ISSUE TITLE
manage gitlab group

### ISSUE THREAD

**Issue by willzhang** [desktop/desktop#8308]
i use desktop manage gitlab ,but gitlab have some groups, every group have the same project name, when i open repository list ,i just see all the same name of project ,can i divide it into groups at left menu？so i can Distinguish the projects in which groups,thanks!

**Comment by niik** [comment]
Hey @willzhang, thanks for opening this issue. The new grouping by owner feature that we added this summer only works for GitHub repositories. While we intend to continue basic support for repositories from other sources (such as GitLab), our primary goal is for the GitHub <-> GitHub Desktop experience to shine. We don't intend to add support grouping repositories from other hosts in the near term, so I'm going to close this issue.

**Comment by willzhang** [comment]
but if two github account have save repo name, it still have problems when i clone them，why don't you just let me create a directory to Differentiate repo for different users? i think it's so Easy to implement
