### ISSUE TITLE
[Onboarding tutorial] Ensure "Open Editor" button shows up after installation

### ISSUE THREAD

**Issue by kuychaco** [desktop/desktop#8315]
Based on usability testing by @billygriffin it seems that the panel isn't registering that there is an editor in step 3 after the user has installed an editor in step 1. 

Desired outcome: ensure that the "Open Editor" button appears in step 3 after editor installation

**Comment by mislav** [comment]
Would clearing the editor lookup cache after step 1 help the newly installed editor be discovered? https://github.com/desktop/desktop/blob/30ebea1650524fa6ac4078662742f6df11598311/app/src/lib/editors/lookup.ts#L13-L17
