### ISSUE TITLE
Unable to merge branches, bug there are unmerged index entries github desktop

### ISSUE THREAD

**Issue by rajeshkarupakala5** [desktop/desktop#8316]
## Description

Unable to merge branches. I'm trying to merge one of my branches with another branch and I get an error saying that there are some unmerged index entries. Not sure what it is referring to. 

## Version

* GitHub Desktop: 2.1.3

* Operating system: Windows 7

## Steps to Reproduce

Step 1: Choose a branch
Step 2: Choose a branch to merge
Step 3: Merge

### Expected Behavior

Should merge the branches with no error or show merge conflicts to resolve

### Actual Behavior

![Capture](https://user-images.githubusercontent.com/26311213/65457270-35393100-de19-11e9-9b8e-00b086ff84cc.JPG)

### Logs

[2019-09-23.desktop.production.log](https://github.com/desktop/desktop/files/3643839/2019-09-23.desktop.production.log)

**Comment by billygriffin** [comment]
Hi @rajeshkarupakala5, would you mind filling out the template please so we can help diagnose the issue you're experiencing? For the "Logs" portion you can find that in `Help` -> `Show Logs in Finder/Explorer`. Thanks!

**Comment by rajeshkarupakala5** [comment]
Hi @billygriffin , Please find the updated information. Thanks

**Comment by mislav** [comment]
@rajeshkarupakala5 Thank you for including the log. These lines caught my attention:

```
2019-09-23T18:59:14.189Z - error: [ui] `git merge origin/task_17_Portal` exited with an unexpected code: 3.
stderr:

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
BUG: There are unmerged index entries:
BUG: 1 eRegulationsPortal/Service References/MembershipService/MemberShipService.xsd
BUG: 1 eRegulationsPortal/Service References/eRegService/eRegService.xsd
BUG: 1 eRegulationsPortal/Service References/eRegService/eRegService10.xsd
BUG: merge-recursive.c:407: unmerged index entries in merge-recursive.c
```

This sounds like it comes within `git merge`, but not all of these messages come from git. Do you have any custom merge driver configured for your project? You can check with `git config -l --show-origin` in the project's directory, and paste us the relevant portions of the output (e.g. keys starting with `merge.`, or anything looks like it configures merge or rebase operations). Thank you!

**Comment by rajeshkarupakala5** [comment]
Please find the below screenshot. I do not see anything.
![Screen Shot 2019-09-24 at 11 54 50 AM](https://user-images.githubusercontent.com/26311213/65528332-29ee1000-dec2-11e9-9226-3b83ef610303.png)

**Comment by mislav** [comment]
@rajeshkarupakala5 Thank you for the info. It's not clear looking at the screenshot if the whole output was included, since there are a lot of repeated sections and the output seems cut off at the bottom of the screen, but I take it that there is no custom merge configuration? There is no output if you try `git config --get-regexp --show-origin '^merge*'`?

I don't know what could be at fault here. The only thing left to look into is whether there are any git hooks that affect merges? Git hooks are any executable scripts in your project's `.git/hooks/` directory.

**Comment by tierninho** [comment]
@rajeshkarupakala5  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
