### ISSUE TITLE
Problem viewing Pull Requests when viewing multiple forks of the same repo

### ISSUE THREAD

**Issue by mark-friedman** [desktop/desktop#8328]
## Description

I have two different forks of a remote repo on my computer.  When I view one of the forks in the GitHub Desktop I can see all the current pull requests within the "Current Branch" pulldown/tab.  However, with the other fork the list of pull requests in empty.  It shows the actual branches just fine for both forks.

## Version

* GitHub Desktop: Version 2.2.0-beta1

* Operating system: MacOS 10.14.6

**Comment by billygriffin** [comment]
Hi @mark-friedman, thanks for the issue! I _think_ this is the same as https://github.com/desktop/desktop/issues/6383, so I'm going to close it for now. Supporting better workflows using forks is definitely something we're interested in but haven't gotten to yet.

**Comment by mark-friedman** [comment]
@billygriffin I don't think that this is the same as #6383.  That one refers to being able to view the PRs for a clone of a fork, as well as the fork itself.  In my case I have two forks of the same upstream repo and i can see the PRs for the upstream repo when I'm viewing one fork in the desktop client but not when I view the other fork in the desktop client.

**Comment by steveward** [comment]
@mark-friedman could you upload a log file? That should show if there are any issues fetching PRs from that specific fork.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by mark-friedman** [comment]
Attached is a log file from today, when the issue occurred.
[2019-09-24.desktop.beta.log](https://github.com/desktop/desktop/files/3649554/2019-09-24.desktop.beta.log)
