### ISSUE TITLE
removing repo wont delete folder

### ISSUE THREAD

**Issue by JandJ101** [desktop/desktop#8329]
Description:
When remove a repository in the GitHub Desktop app, the folder is not removed when some of it files are open in another program. GH Desktop seems to ignore open file deletion warnings.

## Version
2.1.3

* Operating system:
Microsoft Windows [Version 10.0.18362.356]

## Steps to Reproduce

1. Open currently cloned repos
2. Right click on desired repo and click remove

### Expected Behavior
Gives warning that folder or files are open

### Actual Behavior
removes repo from list but leaves folder and all files in place.

**Comment by billygriffin** [comment]
Thanks for the issue @JandJ101! We'll let you know if we have other questions, but looks like @mislav already has a PR up, so hopefully we can get this fixed soon.
