### ISSUE TITLE
No way to clear diff view and return to summary

### ISSUE THREAD

**Issue by francisbarton** [desktop/desktop#8338]
**Please describe the problem you think should be solved**
There is no apparent way to get back to the repository summary pane (the pane that is visible when you first open a repo in GitHub Desktop) once you have opened up a diff.

Situation: you have a list of files in the Changes pane. You click on one of these and the diff is displayed in the main pane, replacing the repo summary.

You notice that you have new data waiting to be pulled down from GitHub - the "Fetch origin" button in the bar below the menu is showing these. However, once the diff is showing in the pane, there is no apparent way via mouse click or shortcut for you to dismiss the diff and return to the main summary pane.

**[Optional] Do you have any potential solutions in mind?**
There should be a button and/or menu option to clear the diff view from the main pane and show the repo summary instead.

**Comment by mislav** [comment]
@francisbarton Is the "No local changes" in the below screenshot the repository summary pane that you are talking about? I'm trying to understand which exact view are you trying to get back to.

<img width="1072" alt="Screen Shot 2019-09-26 at 1 33 56 PM" src="https://user-images.githubusercontent.com/887/65685537-7d975f80-e062-11e9-9018-7358c2788af2.png">

The "No local changes" view, as the name suggests, is only displayed if there are currently no changes to your repository's working copy. To my knowledge, there is no way to clear it apart from committing/deleting local changes, or adding changes files to git ignore list.

**Comment by billygriffin** [comment]
Hi @francisbarton! To add a bit to what @mislav said, our goal with GitHub Desktop is to put the thing that should likely be your area of focus front and center. We want to help keep you in your flow by keeping your attention on the right things, so when there are changes present, those should usually be the focal point. In addition, the options in the "No local changes" area are always available via other means, and all of them have associated buttons and/or keyboard shortcuts. We have no plans to change this, so I'm going to close this issue. But please let us know if you meant something else, and we can look into it further.

**Comment by francisbarton** [comment]
@mislav @billygriffin thanks for your responses and I'm sorry for wasting your time. Yes the "summary" view I referred to is the "No local changes" view - I think I jus tgot a bit confused and panicked tha tI couldn't get back to it. I understand why now!

**Comment by billygriffin** [comment]
@francisbarton Thanks for the response! That totally makes sense and it's not a waste of time at all - glad we're all on the same page now! ❤️
