### ISSUE TITLE
when you have github actions on on a repo, github desktop fails to push 100% of the time

### ISSUE THREAD

**Issue by mooreatv** [desktop/desktop#8339]
when you have github actions on on a repo, github desktop fails to push 100% of the time

![image](https://user-images.githubusercontent.com/46745059/65649474-884ae980-dfbb-11e9-8e77-535f7ffec6e8.png)

ps: ^ make that text copy/pastable 

windows 10, latest desktop 2.1.3

regular git push for same commit just works:
```shell
$ git push
Enumerating objects: 14, done.
Counting objects: 100% (14/14), done.
Delta compression using up to 12 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (9/9), 2.01 KiB | 257.00 KiB/s, done.
Total 9 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/mooreatv/AuctionDB.git
   232438b..1cf99c4  master -> master
```

**Comment by steveward** [comment]
Thanks for the report @mooreatv. This is being tracked in https://github.com/desktop/desktop/issues/7079 -- please follow along there for updates. I'm going to close this issue out.
