### ISSUE TITLE
Enhancement: Create a Commit and Push shortcut

### ISSUE THREAD

**Issue by sam-bryant** [desktop/desktop#8342]
I'd love to see a new shortcut / button that allows an individual to commit a change and perform a push in one action as opposed to clicking "Commit" and then "Push".  

Current behavior:
1. Make change
2. Click "Commit"
3. Click "Push"

Desired behavior:
1. Make change
2. Click "Commit and push"

The commit takes a handful of seconds each time that must complete before we can push the change.  

Please let me know if there are actions available that I am unaware of or if you would like any additional information.
Thanks!
Sam

**Comment by billygriffin** [comment]
Hi @sam-bryant, thank you so much for the issue! Really appreciate the suggestion and makes total sense why you'd like it, but for a couple reasons we've decided not to do this at least for now, so I'm going to close this issue.

I explained our reasoning here: https://github.com/desktop/desktop/issues/2191#issuecomment-431093456

We're not opposed to revisiting anything that we see could solve pain or friction that users are experiencing regularly, but for now we have no plans to do this. Thanks again!
