### ISSUE TITLE
[onboarding] tie tutorial panel keyboard shortcuts to application accelerator config

### ISSUE THREAD

**Issue by outofambit** [desktop/desktop#8346]
follow up from #8249 to make it more robust/future-proof

There's a bunch of prior art that can be stolen from the suggested next steps view that I think would help here so that we don't have to manually keep these in sync with the application menu.

**Comment by 9105090515007** [comment]
https://github.com/desktop/desktop/issues/8732#issue-530754911

**Comment by AzrulHaruna230696** [comment]
# 8249
