### ISSUE TITLE
cannot publish my repository

### ISSUE THREAD

**Issue by forlornMWS** [desktop/desktop#8366]
**Please describe the problem you think should be solved**
A clear and concise description of what the problem is and who else might be impacted. Screenshots are encouraged.

Example:

> “When I run into a merge conflict, I don’t know where to go to resolve it. Anyone who works off of multiple branches will likely run into this problem at least occasionally.”

**[Optional] Do you have any potential solutions in mind?**
A clear and concise description of one or more solutions you think might solve the problem. Please include any considered drawbacks or tradeoffs, and how users might use your solution(s). Screenshots or mockups are helpful here!

**Comment by mislav** [comment]
Hi, we require the issue template to be filled in so we can have more information when looking into the problem you're experiencing. Would you mind filling in the rest of the information above?

If you also attach the application's log file, this can help us even more, especially if you encountered an error that you were not expecting.

To access the log files, go to the file menu in GitHub Desktop and select “Help” > “Show Logs”. Thank you!
