### ISSUE TITLE
Pausing and Resuming while Cloning for Github Desktop app for big projects

### ISSUE THREAD

**Issue by BlackMageZeraf** [desktop/desktop#8367]
Recently I've been cloning this Project from Unity3D FPSSample it's a huge projects and while cloning it using GITHUB Desktop App I found it really inconvenient to not be to pause and resume the project cloning Process. Since large projects take longer time to clone to your local Repository this quality of life feature will be really really really helpful. Please consider adding this Quality of Life Feature for those who have slower internet (Including me) this feature will be really beneficial.

**Comment by mislav** [comment]
Thank you for writing in! I'm sorry that you're having trouble with large repositories.

Project cloning and similar operations in Desktop are all handled by the underlying version control system called "git". Unfortunately, I can't find any evidence that git supports pausing and resuming the clone process. Therefore, this isn't something that we could realistically implement in Desktop.

Even if it was feasible to implement, I don't believe that this feature would see much use among our regular users, and therefore there wouldn't be much incentive for us to maintain this feature.

There are two ways you can obtain a copy of a project without having to perform a full clone, i.e. without having to fetch its entire history:

1. For any GitHub project, you can select “Download ZIP” under “Clone or Download”. This won't get you the git repository, but it will fetch all the project files, which should be enough for you to run the Unity3D sample project.

2. From the command-line, you can invoke `git clone --depth 1 https://github.com/Unity-Technologies/FPSSample.git` to create a "shallow" clone, i.e. to obtain the latest project files without fetching its entire history. You would have to do this operation outside of GitHub Desktop, but later you could potentially add this repository to Desktop if you intend to continue interacting with it, such as making new commits.

Hope this helps!
