### ISSUE TITLE
[ QUESTION 🧐 ] Are themes for GitHub Desktop welcome?

### ISSUE THREAD

**Issue by MairwunNx** [desktop/desktop#8368]
This is not a problem, this is just a question.

My question is: is the creation of themes for GitHub Desktop welcome? I am sure there are talented people who would make beautiful themes, and the most beautiful themes can be embedded in the application.

I like the dark theme that is now, but it can be done better and that's why I'm interested.

**Comment by mislav** [comment]
This is a good question. Ideas for a feature that allow for customizing Desktop came up before, but our team decided that it's not something that we intend to build and maintain. The only alternate visual theme that we are committed to supporting and iterating on is the dark theme. https://github.com/desktop/desktop/issues/2609#issuecomment-327089152

**Comment by MairwunNx** [comment]
@mislav i.e i can suggest PR with dark theme improvements \ color improvements?

**Comment by mislav** [comment]
@MairwunNx For sure! We will take your suggestions into consideration.

**Comment by MairwunNx** [comment]
@mislav Fine. Then I will start to improve the dark theme right now and will propose my changes through PR. 🐱‍🏍
