### ISSUE TITLE
The logout button should be placed better!

### ISSUE THREAD

**Issue by DanielFront-afk** [desktop/desktop#8376]
I want to log out from my account but I just can't find the button.
I just see a white browser window. 
Please help.

**Comment by billygriffin** [comment]
Hi @DanielFront-afk, thanks for the issue and sorry you're having problems. Would you mind sharing what OS (Mac or Windows) and version, as well as the version of GitHub Desktop you're using if you know it.

Also, screenshots and a log file (`Help` -> `Show Logs in Finder/Explorer`) would be helpful in allowing us to diagnose the problem.
