### ISSUE TITLE
[Onboarding] User cannot exit tutorial if another repo is created midstream 

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#8377]
Attempting to exit a tutorial after cloning a repo midstream results in the `Exit tutorial` button not working.

Steps:
- Start tutorial and Exit
- Clone a repo
- Click on tutorial repo in the Repo list
- try to exit now and its broken

Spotted in the console: `Current tutorial step is NotApplicable` however this could relate to the Open PR step or something else unrelated. 

Clicking `Exit` does this:
![Screen Shot 2019-09-30 at 11 33 15 AM](https://user-images.githubusercontent.com/14828183/65919439-fdca0780-e377-11e9-8b84-07fc8678ffa9.png)

Version 2.2.0-beta2, mac

**Comment by billygriffin** [comment]
The assumption here is that most people doing this will likely not have other repos to clone. I'm not opposed to fixing it if it's a simple fix, but the order of operations here feels relatively unlikely to occur.

**Comment by tierninho** [comment]
Somewhat related to https://github.com/desktop/desktop/issues/8341 as I forgot to add that bug into this.

**Comment by billygriffin** [comment]
Closing as expected behavior.
