### ISSUE TITLE
css-validation-fixes

### ISSUE THREAD

**Issue by AlexanderTahtadjian** [desktop/desktop#8392]
Hi,
I'm having a problem with my css naming file. When I placed this file into Markbot, it says that: "css/ main.css doesn't follow naming conventions but I changed it to make sure it does follow the naming conventions, but its still treating it as an error. Then, when i go into my css/main.css file, it says that it's either missing or misspelled, but Checked in the everywhere and it's nither missing or misspelled. So I don't know what's going on

**Comment by tierninho** [comment]
👋 Is this Desktop related? A screenshot would help along with steps to repeat the error. Thanks.
