### ISSUE TITLE
Repositories not syncing between desktop and online

### ISSUE THREAD

**Issue by ehammel** [desktop/desktop#8393]
My repository online does not match my available repositories.  Any ideas on how to make them sync?

Online:
<img width="1433" alt="pictureOfRepoOnline" src="https://user-images.githubusercontent.com/9244506/66090255-36b8d680-e548-11e9-9289-5d66fbcc5f14.png">

Desktop app:
<img width="1152" alt="desktopGithub" src="https://user-images.githubusercontent.com/9244506/66090283-52bc7800-e548-11e9-9aaf-d4f322e79ee9.png">

Thank you.

Best,
Erik

**Comment by tierninho** [comment]
@ehammel Did you clone the repo to Desktop? Click on the File menu option and click Clone to find the repo.

I see repo "Test" in your screenshot only.
