### ISSUE TITLE
Simplify external editor code

### ISSUE THREAD

**Issue by kuychaco** [desktop/desktop#8396]
I’m feeling the itch to refactor and simplify the external editor code because currently it seems to be a breeding ground for bugs, and it’s not the easiest to reason about. 

I'm thinking we can drop `selectedExternalEditor` and rely only on `resolvedExternalEditor` (resolved as in _accessible because it’s actually installed_). I can’t think of a scenario where we’d want these two to diverge. And we’ve hit a few bugs now as a result of them diverging. 

See #8315 and #8386 and #8322

**Comment by Rexogamer** [comment]
Somewhat related: #5409

**Comment by outofambit** [comment]
@kuychaco I agree this is a worthwhile refactor. I don't think preserving the user's intent to use an unavailable editor is an important use case (which I think is the primary benefit to having a separate `selectedExternalEditor`). Going forward, I imagine our use of a default editor in desktop will only increase.

We've also seen that quick fixes don't seem to be sufficient in this part of the codebase (#8389). And additional bugs like #8315.

**Comment by lilgurl** [comment]
Hey sms me

**Comment by Rexogamer** [comment]
@lilgurl ???

**Comment by lilgurl** [comment]
Yea

**Comment by lilgurl** [comment]
My number

**Comment by steveward** [comment]
Closing in favor of https://github.com/desktop/desktop/issues/14666.
