### ISSUE TITLE
Add support for IntelliJ IDEA as an editor

### ISSUE THREAD

**Issue by gssbzn** [desktop/desktop#8398]
**The problem**
Now that I'm back at being a Java developer I've been using IntelliJ more and more, it would be great to add it as a supported editor

I have already a working patch that I'll gladly submit for review if there's no problem to add the support 
![Screenshot 2019-10-03 at 12 52 38](https://user-images.githubusercontent.com/461027/66125726-ad54e300-e5df-11e9-8143-b4f9db1965e3.png)

**Comment by billygriffin** [comment]
Hi @gssbzn, thanks for the issue! Here are the docs for integrating an editor: https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md

Check those out, and if you think this is a good candidate, feel free to make a PR. I can't promise how quickly we'll get it reviewed, but we appreciate allowing more people to use Desktop with their preferred editor so it's definitely something we'll consider.

Thanks!

**Comment by harper1983** [comment]
Nice

**Comment by PLHfor3** [comment]
Was this feature set ever implemented in Windows?

**Comment by spxctreofficial** [comment]
Not yet. At least, not for me.

**Comment by theMentatHenrique** [comment]
hello, when i use github desktop with intelliJ Ultimate, sometimes occours very papers of workspace for push, papers wich i do anything, and sometimes my intellij not recognize my packages or folders, someone help me ?
