### ISSUE TITLE
Changes lost during switch to branch

### ISSUE THREAD

**Issue by renathy** [desktop/desktop#8404]
During branch swithing all changes were lost. 
It asked me to bring changes or leave changes, I wanted to bring them. 
No warning, no error messages. 
Changes now are gone. 
I cannot find them also using git stash list.

**Comment by billygriffin** [comment]
Hi @renathy, sorry you’re experiencing this. So we can further diagnose, would you mind providing a bit more information?

Which version of Desktop, and which OS version are you using?

Also, if you can provide any more info about what type of changes they were (like files added, modified, removed, etc) and any other info about what specifically you did, that would also be helpful.

Lastly, would you mind including a log file here? You can find it in Help -> Show Logs in Finder/Explorer. 

Apologies again and thank you.

**Comment by billygriffin** [comment]
@renathy To add to this, I *think* this problem should be fixed in GitHub Desktop 2.2, so hopefully you wouldn't experience it anymore on the latest version, but please let us know.

**Comment by tierninho** [comment]
@renathy  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
