### ISSUE TITLE
error: unable to read askpass response ask-pass-trampoline.bat

### ISSUE THREAD

**Issue by ksmith1787** [desktop/desktop#8406]
## Description
While attempting push or pull to origin, I get the following error:
error: waitpid for C:\Users\<my id>\AppData\Local\GitHubDesktop\app-error: unable to read askpass response from 'C:\Users\<my id>\AppData\Local\GitHubDesktop\app-2.2.0\resources\app\static\ask-pass-trampoline.bat'
fatal: could not read Username for 'https://<our VSTS domain': terminal prompts disabled

When I run a push or pull, a CMD window pops up on my desktop briefly, it contains my email address, then it disappears and the above error occurs.

## Version
* GitHub Desktop: 2.2.0
* Operating system: Windows 10
## Steps to Reproduce
Any pull or push
### Expected Behavior
Expect the push or pull to succeed
### Actual Behavior
Error message and failure
## Additional Information
Connected to VSTS not GitHub
### Logs
I see no logs folder or logs anywhere

**Comment by steveward** [comment]
@ksmith1787 thanks for the report. There are some known causes for this error mentioned in our Known Issues document:

https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789

Can you take a look there and see if any of those situations may apply to your machine?

**Comment by tierninho** [comment]
@ksmith1787  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by yrifl** [comment]
The syntax of the command is incorrect.
error: unable to read askpass response from 'C:\Users\Lenovo\AppData\Local\GitHubDesktop\app-2.6.3\resources\app\static\ask-pass-trampoline.bat'
fatal: could not read Username for 'https://github.com': terminal prompts disabled

I get this Error while im gonna upload the branch:

do i need to restart or idk⚙

PLS HELP

**Comment by tidy-dev** [comment]
@Cyber2f08 Sorry for your trouble. Could you please review the common causes in our known issues doc and see if any of those will help you? https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors
