### ISSUE TITLE
Don't enforce global user name and email

### ISSUE THREAD

**Issue by pf1gura** [desktop/desktop#8407]
**Please describe the problem you think should be solved**
I already went through similar issues on GitHub but none seem to offer a good solution. (e.g #2829)

I use the same laptop for private and company projects with multiple email addresses. With console version of git, I don't setup global config for user name and email, which enforces me to do it for each project whenever I want to commit (which is good). That way I know I use correct user information for each repo.

When I save any option in GitHub Desktop, global user config is also saved with default GitHub user. If I miss that, I might commit to a new repo with wrong user information.

**Do you have any potential solutions in mind?**
The app shouldn't enforce global user configuration. When comitting in a repo without local user config, user should be prompted to set it up (locally)

**Comment by steveward** [comment]
Thanks for the feedback @pf1gura. I'd also recommend taking a look at #610, which discusses how we'd like to provide a better way to notify users when the `user.email` in the `~/.gitconfig` does not match an email address associated with the currently logged in GitHub account. I'm going to add your feedback to that issue as well.

The best workaround I can recommend would be to use a feature of Git that allows different email addresses to be associated with repositories based on where the repository lives on your machine. See [this StackOverflow solution](https://stackoverflow.com/a/43654115) for more information and a basic guide for how to set this up.

I've tested this out in GitHub Desktop and can confirm it works. By doing this you would only need to set up a separate `work` and `personal` directory, and then make sure you clone/create/add repositories to the correct directory.
