### ISSUE TITLE
Adding existing repositories in batch

### ISSUE THREAD

**Issue by jagjordi** [desktop/desktop#8415]
### Describe the feature or problem you’d like to solve

While right now Girhub Desktop supports drag'n'drop to add existing repositories in bulk this only works if all the repos are in the same folder.

### Proposed solution

I believe it would be useful having an option where you can add a list of repos to github by giving a list of paths

### Additional context

Nothing to add

**Comment by steveward** [comment]
Thanks for contributing @jagjordi! It sounds like you are interested in a "scan for repositories" feature, which is being tracked in https://github.com/desktop/desktop/issues/1574. You can follow along there for updates. I'm going to close this issue out.
