### ISSUE TITLE
DX: misleading message when deleting a branch

### ISSUE THREAD

**Issue by staabm** [desktop/desktop#8416]
when deleting a local branch which was already merged you face the following message:

![image](https://user-images.githubusercontent.com/120441/66268280-1d5fa500-e83c-11e9-8eae-a082fbcbf3dd.png)

I think the "DELETE" Button is misleading because as the message states its not 100% clear whether a button click only deletes the local branch and/or it deletes the remote branch

**Comment by mislav** [comment]
Hi, when you say “was already merged”, do you mean merged locally (no push yet), or merged on a remote?

When the "this branch has an open pull request associated” message comes up, is there still an open PR, or was the PR state already updated as "merged" on GitHub, but Desktop has not yet pulled that information from the API?

**Comment by staabm** [comment]
> Hi, when you say “was already merged”, do you mean merged locally (no push yet), or merged on a remote?

merged on a remote

> When the "this branch has an open pull request associated” message comes up, is there still an _open_ PR, or was the PR state already updated as "merged" on GitHub, but Desktop has not yet fetched that latest information from the API?

I guess my workflow in this scenario was
1) create local branch with github desktop
2) push branch to github.com
3) open pull request
4) merge pull request via github.com
5) delete the local branch by checking it out and choose Branch->Delete Branch from the menubar

not sure whether clicking "fetch" in github desktop between step 4 & 5 would made a difference

**Comment by mislav** [comment]
Thank you! It definitely sounds like Desktop's information about the open branch was stale, since it was telling you about an open PR that is not open anymore (just got merged on dotcom).
