### ISSUE TITLE
Publishing Authentication Error

### ISSUE THREAD

**Issue by ScoaccBiscuits** [desktop/desktop#8418]
### Description:
I was trying to create a repository on GitHub Desktop, but when I want to publish it on GitHub, I get an authentication error.

### Proof Images:
https://prnt.sc/pfn3t5

### Things that you need to know:
1. My account is signed on GitHub Desktop = https://prnt.sc/pfn493.
2. The elements I am trying to publish are going to be private.
3. I don't have SSH keys associated in my account.
4. I do not use GitHub Enterprise Server.

#### I would appreciate your cooperation, any comments will help, thanks.

**Comment by mislav** [comment]
Sorry that you're having trouble, and thank you for the screenshots! Would you mind sharing with us:
- your Desktop version number
- whether you are able to create a private repository of the same name in your GitHub web interface
- whether you have other repositories in Desktop, and if so, whether pushing/pulling operations for those repositories work?

If you also attach the application's log file, this can help us even more, especially if you encountered an error that you were not expecting.

To access the log files, go to the file menu in GitHub Desktop and select “Help” > “Show Logs”. Thank you!

**Comment by tierninho** [comment]
@ScoaccBiscuits  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
