### ISSUE TITLE
Git LFS File Locking

### ISSUE THREAD

**Issue by chasse20** [desktop/desktop#8419]
### Purpose

The goal of this enhancement would be to integrate user-friendly support for Git LFS File Locking into Github Desktop. File locking is a critical tool used by diverse teams of artists (working on binary files) and programmers that will routinely experience overlap.

This would position the Github Desktop project in a way that directly competes against existing software such as Perforce, and will specifically help open up an entirely new industry for Git: game development.

This enhancement would only aimed at backend services, such as Bitbucket, that support Git LFS and file locking.

### Proposed Solution

As part of [Github Desktop's strive for user-friendliness](https://github.com/desktop/desktop/blob/development/docs/process/what-is-desktop.md), this enhancement would ideally incorporate the following:

- UI feedback in the Changes tab that indicates if a file is locked and who is the owner
- Preventing a user from committing a locked file that is not their own
- Upon commit, automatically unlocking a locked file if it is owned by the end-user
- Adding the option to Force Unlock (if not owned by a user) or Unlock (if it is owned by a user) in the file context menu
- Adding the option to lock an unlocked file via the context menu
- An "Explorer" tab that shows the entire repository in a traditional tree structure/file browser (necessary for a locking workflow in the first place)
- Change-status feedback in the "Explorer" tab
- Lock status and ownership feedback in the "Explorer" tab

Below are some mockups outlining these proposed features.

_**Current Github Desktop:**_
<img src="https://user-images.githubusercontent.com/12206652/66287148-6db12400-e889-11e9-83d2-6a656c1c0e7c.jpg" width="300">

_**Proposed Enhancement:**_
<img src="https://user-images.githubusercontent.com/12206652/66287152-71dd4180-e889-11e9-83ce-4a654d261cb0.jpg" width="300"> <img src="https://user-images.githubusercontent.com/12206652/66287556-18761200-e88b-11e9-84c9-de6c66dec978.jpg" width="300">

### Why wait?

A few of us from the game, arch-viz and web-design industries plan on contributing/making these enhancements regardless. We see a tremendous opportunity to not only improve our own workflows, but to radically disrupt current industry tools such as Perforce.

**Comment by billygriffin** [comment]
Hi @chasse20, thanks for the issue! We had an issue in #2437 that we had as something we were considering for the future, but hadn't gotten to prioritizing it yet. Since this is such a wonderful description of the issue and why you think it's important, I went ahead and removed the `future proposal` label and we'll use this issue to discuss this going forward. I really appreciate you laying out the opportunity and how it aligns with our product goals.

I would say that this does feel like a pretty huge lift for one feature, given that it would need to support a file explorer that would add complexity to the application and potentially not be widely used by folks who aren't using this feature.

> This enhancement would only aimed at backend services, such as Bitbucket, that support Git LFS and file locking.

Would you mind unpacking this a bit more? I'm not sure I understand what you mean here.

**Comment by chasse20** [comment]
In response to the bottom question: I'd run a check to see if a repository supports the LFS >= v2.0 file locking.

As far as the breakdown of work goes, this can be broken down into a phased deployment. I was thinking of this as I go:

**Milestone 1: Purely UI Feedback**
- Detect if file locking is supported on a repository
- Run periodic check of file lock status (e.g., `git lfs locks`)
- File lock UI feedback in Changes view (the lock icon in the mockup)
- File lock UI feedback in Compare view (what you see in the top right corner of the mockup) that also has a hover tooltip to indicate who owns it

**Milestone 2: Commit Functionality**
- Prevent commit of files that are locked and not your own (but commit everything else)
- If trying to commit files that are locked by you, unlock them upon commit

**Milestone 3: Context Menu Controls**
- File unlocking functionality in context menu by either "Force Unlock" or "Unlock" your own (see mockup)
- Add file "Lock" in the context menu if a file is unlocked

**Milestone 4: Explorer Tab**
- Explorer tab with tree view of all folders and files in the repository
- Able to click on folder icons to expand them
- Status feedback for files in Explorer tab
- File locking feedback in Explorer tab
- Add context menu in Explorer tab to be the same as the Changes tab

I've seen that linked issue you referenced before, along with every other Git client where people requests this kind of thing but the developers just haven't had a chance. It's a lot for sure, but I feel confident that it can be done over time.

**Comment by outofambit** [comment]
Hi @chasse20! Thanks so much for your work on this, I really appreciate your thoroughness. After discussing it internally, our team unfortunately doesn't have the bandwidth to support and accept this work right now.

This feature has potential differentiator for GitHub Desktop, but doesn't align with any of our team's focus areas right now. If we were to focus more on the game developers (and other users that deal with large binary files regularly) user base, this could be an important part of that work.

Again, thanks for this work and I'm sorry we can't support it right now. We'll be sure to let you know if anything changes.

**Comment by chasse20** [comment]
In that case, I'll just lightly maintain a fork for the many game developers out there that are looking for an alternative to Perforce and its clunkiness/pay-wall.

There is a fairly high demand for something more accessible and user-friendly for diverse teams (artists, sound designers, game designers, etc.), so it's a little bit disappointing that it won't be pushed at this time. Programmers have always felt comfortable using a console, so I've always viewed these UI-based tools as a means to widen the user-base beyond the programmer. Even then, none of them had any UI support for locking yet and the work done here was able to at least implement everything short of an Explorer Tab (which was going to be tackled next).

Hopefully in the future the value of even having a UI tool in the first place will be recognized again.

**Comment by b-hayes** [comment]
You know what's funny. I've been using git for decades and only just now found out that file locking exists with an entire startup looking at perforce because of that one simple feature that apparently already exists in git but no one knows about it because it's not visible.

I opened GitHub desktop (I'm a command-line user I don't use it usually) and looked for it and realized yes, you need to see ALL files to lock one so, my Very next logical step was go to file explorer and see if a context menu exists for it.
This IMO would be the way to do it. Just add a file context menu in explorer. Should be offered as an option during installation. Could take this further and show the lock status in file explorer.

**Comment by MatthewSiegelScopely** [comment]
> 
Did this feature ever get made? We could really use it.

**Comment by gamedevkirk** [comment]
Any chance of getting this resurrected? Lotta devs out there that this would benefit!

**Comment by chasse20** [comment]
I'll probably get booted for even saying this here, but it seems the wider VCS/Game industry surprisingly hasn't fulfilled the demand. Next year I'm interested in starting and investigating a standalone product intended to fix this for indies especially, but it will take some time to do the necessary UI/UX and to scale up a development team.

My initial take for any such solution is that it would necessarily need to work from the perspective of the game developer first, not having the entire version history stored on the local machine by default (LFS does offer some of this), robust file locking, support for previewing assets (2d, 3d, etc. otherwise), simplifying project initializations (ignores/attributes/etc.), linking to consistent identity providers for users (antithetical to the anonymous nature of git, but useful for analytics) and other on-premise tooling, and better automation when it comes to conflicts/merging which is an extreme pain point for non-programmers in general.

Ideally Github Desktop addresses those before I do though! :)

**Comment by gamedevkirk** [comment]
I'd love to see something like that come out. I mostly work with Unreal Engine, and Git is a struggle, especially with newer team members who are still learning to work with source control in general. There are too many "gotchas" namely with GitHub Desktop and the way it encourages the merging when there are conflicts in binary files. It's misleading and takes a ton of internal documentation to play around.

> Ideally Github Desktop addresses those before I do though!

Here's to hoping 🍻 But if not, make sure you release your VCS with an Unreal plugin lol.

**Comment by steveward** [comment]
Requested in https://github.com/desktop/desktop/issues/19268.
