### ISSUE TITLE
БЕТА

### ISSUE THREAD

**Issue by vova557** [desktop/desktop#8421]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by mislav** [comment]
Hi, we require the issue template to be filled in so we can have more information when looking into the problem you're experiencing. Would you mind filling in the rest of the information above?

If you also attach the application's log file, this can help us even more, especially if you encountered an error that you were not expecting.

To access the log files, go to the file menu in GitHub Desktop and select “Help” > “Show Logs”. Thank you!

**Comment by Rexogamer** [comment]
I think this is spam.

**Comment by vova557** [comment]
хотел спросить а как получать деньги за свои разработки
