### ISSUE TITLE
Windows close when I just press mouse button outside its borders.

### ISSUE THREAD

**Issue by sairus7** [desktop/desktop#8423]
### Describe the bug

A very frustrating bug, when window closes as you press mouse button outside its borders, or press the mouse inside a window, drag it outside the window and release it.

### Version & OS

2.2.0
Windows 10

### Steps to reproduce the behavior
A)
1. Go to 'Clone repository'
2. Click outside its borders. 'Clone repository' window closes immediately.

B)
1. Go to 'Clone repository'
2. Select 'Local path' string with mouse: push mouse at the end of the path and drag it left to select the whole path, then drag it outside the 'Clone repository' window and unclick it. The window closes immediately.

### Expected behavior

Window should not close when I release mouse button outside its borders.
Also, should not close when I just press mouse button outside its borders.
It will probably be bettter if closing that window require an explicit action like pressing 'Cancel' button, and not just when user clicks outside the window.

**Comment by mislav** [comment]
Thank you for writing in! We're already tracking this piece of feedback in https://github.com/desktop/desktop/issues/8276. There is also an open PR to address this. Please add to those threads if you think something is missing from the conversation so far. Thank you! ✨
