### ISSUE TITLE
Repository name incorrect

### ISSUE THREAD

**Issue by Cackerman55** [desktop/desktop#8425]
### Describe the bug

When in GitHub desktop, the second repository I have added from a local folder, after adding my first repository from a local folder, has the same name as the first repository.

### Version & OS

Windows 10 1903 Build: 18362.356
GitHub desktop version 2.20

### Steps to reproduce the behavior

1. Go to main screen with current repository
2. Click on current repository dropdown
3. (Scroll down)
4. See error - two repositories with same name but different content once clicked on to open

### Expected behavior

Different names for different repositories

### Actual behavior

2 repositories (possibly more, only added one) with same name, and under same organization

### Screenshots

![github1](https://user-images.githubusercontent.com/10200135/66345396-01cccb00-e91e-11e9-8031-c5c20ce34892.PNG)
![github2](https://user-images.githubusercontent.com/10200135/66345398-01cccb00-e91e-11e9-8c80-601a9df7a40b.PNG)
![github3](https://user-images.githubusercontent.com/10200135/66345399-01cccb00-e91e-11e9-9ee2-7470f9eb12f5.PNG)

### Logs

Not applicable

### Additional context

recently installed. was using git for windows prior. had trouble with ssh agent so I switched programs

**Comment by kuychaco** [comment]
Thanks for the report @Cackerman5. You mentioned the expected behavior of:

> Different names for different repositories

What are the names of the two repositories on github.com? Do they have the same name? I'm wondering if this issue is captured in https://github.com/desktop/desktop/issues/1929 and https://github.com/desktop/desktop/issues/6460

**Comment by Cackerman55** [comment]
one should be 442projects-katz and one should be cackerman55.github.io @kuychaco

**Comment by kuychaco** [comment]
Thanks for the extra info @Cackerman55!

Could you attach the full log files? The **Help | Show Logs** menu item should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by Cackerman55** [comment]
[2019-10-07.desktop.production.log](https://github.com/desktop/desktop/files/3708939/2019-10-07.desktop.production.log)
@kuychaco as per your request

**Comment by tierninho** [comment]
@Cackerman55 Don't see anything useful in the logs. If the repos are remote, I would recommend trying to clone the them again.

**Comment by tierninho** [comment]
@Cackerman55  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
