### ISSUE TITLE
Feature Request: Double click on a file to select/deselect the file on the changed files tab

### ISSUE THREAD

**Issue by Shakil-Shahadat** [desktop/desktop#8426]
Currently, no action is assigned to double-clicking a file on the changed files list. Double-clicking a file to select/deselect it will make it very easier to select/deselect a file instead of clicking on the tiny box on the left of the file.

**Comment by tierninho** [comment]
@Shakil-Shahadat Thanks for the suggestion. We will consider it for the next iteration in the area of the application.

In the meantime, if it helps, you may click in this area to select/deselect all boxes:
![Screen Shot 2019-10-07 at 10 51 05 AM](https://user-images.githubusercontent.com/14828183/66347625-7852d400-e8f0-11e9-862e-95375098963c.png)

**Comment by billygriffin** [comment]
Hi @Shakil-Shahadat, because there are already multiple ways to check the checkbox for files, we'd prefer not to add to the confusion by introducing another way. You can use `spacebar` in addition to clicking on the checkbox itself. Hope that's helpful!
