### ISSUE TITLE
Switch to branch with folder which is a submodule on source branch

### ISSUE THREAD

**Issue by FHannes** [desktop/desktop#8429]
### Describe the bug

Let's say I have branch `source` and branch `target`. I am currently on branch `source`, where I have replaced a folder which is on both branches, with a submodule. When now I checkout branch `target`, the checkout fails because this folder exists on branch `target` where it is not a submodule. This also fails in git commandline, but it breaks GitHub Desktop. The client shows the switching to the `target` branch, but then switches back to `source`, since git will fail to switch. However, it repeats the switching indefinitely. This does not freeze up the desktop client, but it does make it practically unusable until you restart it.

### Version & OS

GitHub desktop version 2.2.0. OS is Windows 10 Pro x64 (10.0.18362 Build 18362).

### Steps to reproduce the behavior

1. Create and commit a folder that has some files.
2. Create a new branch.
3. In the original branch, replace the folder with a submodule.
4. Use the GitHub Desktop client to switch to the second branch which does not have the submodule.

* I also have `ignore = dirty` set for the submodule, but I don't think that influences this.

### Expected behavior

I expect either an error message as is shown with git commandline, telling you that you cannot switch to the branch. Alternatively the desktop client could implement a workaround to perform the switch, though I would not recommend it.

### Actual behavior

The desktop client keeps switching back and forth between the branches.

**Comment by tierninho** [comment]
@FHannes Thanks for filing this. Tried to replicate this but I have some questions. 

- For step 3, when you replaced the folder with the submodule, did you commit the changes? 
- What did you mean by "The desktop client keeps switching back and forth between the branches" ? The app was flickering? or the submodule folder was following you as you moved between branches?

**Comment by tierninho** [comment]
@FHannes  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
