### ISSUE TITLE
Terminal prompts disabled for only one repository

### ISSUE THREAD

**Issue by ZYHowell** [desktop/desktop#8430]
As the title says, when i try to push/fetch using github desktop, such an error occurs:

error:unable to read askpass response from
'C:\Users\myusername\AppData\Local\GitHubDesktop\app-2.2.0\resources\app\static\ask-pass-trampoline.bat'
fatal: could not read Username for 'https://github.com':terminal prompts disabled.

But it is strange that this happens in only one repo and other repos goes well. And in this repo, i successfully switched to a branch that i had never switched to on this PC.
Every repo goes well when i use cmd to push/fetch. And the github desktop can act asap if i use cmd to push/fetch any repo.

**Comment by billygriffin** [comment]
Hi @ZYHowell, thanks for the issue and sorry you're having issues. This looks like a known issue documented [here](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789). I'm going to close this issue, but I'd love it if you could let us know if you get this resolved from that documentation. Thanks!

**Comment by ZYHowell** [comment]
Hi Griffin, thanks for sending such an email. I have solved it after deleting the autorun in regedit. It seems like that the anaconda on my PC makes only one repo unavaliable to use--and that's why I think the previous issues cannot help me: all of them cannot use all their repos because of this. 

Thanks again for helping me solve it.





------------------ 原始邮件 ------------------
发件人: "Billy Griffin"<notifications@github.com>; 
发送时间: 2019年10月9日(星期三) 凌晨1:19
收件人: "desktop/desktop"<desktop@noreply.github.com>; 
抄送: "Pia-ji"<1148830469@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [desktop/desktop] Terminal prompts disabled for only onerepository (#8430)




Hi @ZYHowell, thanks for the issue and sorry you're having issues. This looks like a known issue documented here. I'm going to close this issue, but I'd love it if you could let us know if you get this resolved from that documentation. Thanks!

**Comment by billygriffin** [comment]
Great, glad you got it resolved!! 🎉
