### ISSUE TITLE
Feature Request: Show progress in the taskbar for push / pull

### ISSUE THREAD

**Issue by Shakil-Shahadat** [desktop/desktop#8433]
I often change Github desktop to my editor / browser after I hit push / fetch. I had to check back after some time if it is done. Showing progress on the taskbar will make it very easy to understand if it is done. Thanks.

**Comment by ChamodyaDias** [comment]
Hello, I'm a good fan of Github desktop and I've experienced this issue too. I would like to contribute to this enhancement and fix it. May I start working on this?

**Comment by billygriffin** [comment]
Hi folks, thanks for the idea. When we consider features that GitHub Desktop may support, we like to understand the impact of the feature and who it's likely to benefit, in addition to understanding under what circumstances they're likely to use it. In this case, it sounds like you're suggesting something that's specific to one operating system. I'm curious if that's the case, how you see people using it, and who you expect to benefit the most so we can understand whether we think it's a good idea to support. Generally we've tried not to bleed too far into your other work (for example, by showing a badge on the app icon if there are new things) and we've chosen to keep the app relatively self-contained. We'd ask that you not make a PR for anything like this until we've determined that it's worth supporting to get the PR merged and longer-term, and that it fits into our goals. Thank you!

**Comment by Shakil-Shahadat** [comment]
### Impact?
- I think low.

### Who it's likely to benefit?
- I think most of the people.

### It sounds like you're suggesting something that's specific to one operating system.
- What made you say that? I didn't mention any os!

### I'm curious if that's the case, how you see people using it, and who you expect to benefit the most?
- I already explained that. And also people spontaneously supported this idea.

Did I miss anything?

**Comment by ChamodyaDias** [comment]
Hi all, correct me if I'm wrong, what I understood from the above enhancement request is, when we fetch / push, and do some other work in the computer, we have to revisit the github desktop to check whether the process is completed. If we can show the progress on the github desktop icon on the taskbar, we can keep an eye on it to get an idea of the progress. Something similar when downloading from chrome browser etc. Am I right @Shakil-Shahadat

**Comment by Shakil-Shahadat** [comment]
Exactly @ChamodyaDias

**Comment by ChamodyaDias** [comment]
@billygriffin I will be pleased if you can allow me to work on this. I'm just starting to contribute to open source projects and I think I can tackle this. Looking forward to hear from you.

**Comment by greystate** [comment]
Sidenote: I would actually be quite happy with a standard OS Notification whenever a push/pull completed.  
It's the same scenario - I push something to a repo/server that does a lot of stuff and sends a lot of messages back (I can see them inside the Push/Pull button today, actually) but I <kbd>alt</kbd>+<kbd>TAB</kbd> back to my texteditor while it completes. Instead of checking back a few times to see if it has completed, I could just wait for the notification.

**Comment by ChamodyaDias** [comment]
@greystate That's a good idea as well. Will implement and raise a pull request.

**Comment by Rexogamer** [comment]
If you/anyone else implements the notification idea, PLEASE make it toggle able.

**Comment by say25** [comment]
@ChamodyaDias please open an issue for notifications.
