### ISSUE TITLE
Discard all changes not doing anything

### ISSUE THREAD

**Issue by MCnunzio** [desktop/desktop#8439]
### Describe the bug
When choosing the Discard all Changes within the GitHub desktop app for Windows, it takes roughly 60 seconds before the progress window disappears. However all files remain in the changes window. This also happens when selecting one or more files. 
[2019-10-09.desktop.production.log](https://github.com/desktop/desktop/files/3709019/2019-10-09.desktop.production.log)

### Version & OS

Windows 10 - GitHub Desktop v2.2.1

### Steps to reproduce the behavior

1. Go to the current repository
2. Right click on any file within the changed files window
3. Select Discard Changes and confirm
4. No errors are displayed. Files still exist

### Expected behavior

Files are expected to disappear within the changed files window

### Actual behavior

discarding the changes takes longer than expected and no files are removed

### Screenshots

N/A

### Logs

Attached
[2019-10-09.desktop.production.log](https://github.com/desktop/desktop/files/3709020/2019-10-09.desktop.production.log)

**Comment by billygriffin** [comment]
Hi @MCnunzio, thank you for the report! To help us diagnose, is this *new* as of 2.2.1 where it worked fine before and now is no longer working as expected, or is it something you'd experienced before?

**Comment by tierninho** [comment]
@MCnunzio Also, if you can share a screenshot that would be great. I suspect the files have merge conflicts and that is the reason they cannot be discarded.

**Comment by MCnunzio** [comment]
I cannot say if this is a new issue, as I am new to Github. One thing to note that i should have mentioned prior, is there was a copy + paste of all the files from an original source folder to the one that GitHub monitors. The files were almost all the same as the target folder, but there may have been some discrepancies. 

[2019-10-10.desktop.production.log](https://github.com/desktop/desktop/files/3712698/2019-10-10.desktop.production.log)

![2019-10-10 09_08_55-GitHub Desktop](https://user-images.githubusercontent.com/53581827/66571878-0a035100-eb3e-11e9-8eb2-d6d786ab5e15.png)
![2019-10-10 09_09_18-GitHub Desktop](https://user-images.githubusercontent.com/53581827/66571888-0e2f6e80-eb3e-11e9-8c5c-20dffbec53ff.png)
![2019-10-10 09_09_28-GitHub Desktop](https://user-images.githubusercontent.com/53581827/66571892-112a5f00-eb3e-11e9-9e68-eb78e0c684af.png)
![2019-10-10 09_12_00-GitHub Desktop](https://user-images.githubusercontent.com/53581827/66571901-14254f80-eb3e-11e9-8797-1ce40b2a308f.png)

**Comment by MCnunzio** [comment]
I attempted to just commit the files since they were all going to be the same files anyway but received this error.

![2019-10-10 09_47_31-GitHub Desktop](https://user-images.githubusercontent.com/53581827/66574901-0d4d0b80-eb43-11e9-9216-b873ab89b459.png)

**Comment by steveward** [comment]
@MCnunzio you mentioned that you copied all of the files from another source folder -- was this source folder already an existing repository? I am wondering if you inadvertently copied the `.git` directory and as a result have nested `.git` directories. That would explain the `exit code 1`, since this is a [common error](https://github.com/desktop/desktop/issues/4432#issuecomment-381677801) that is thrown when there are nested Git directories. I would recommend enabling the option to view hidden files and checking to see if a `.git` directory made it in somehow.

**Comment by tierninho** [comment]
Piling on to the comments made by @steveward, fixes for discarding files in submodules and untracked files are coming soon via multiple pull requests:  https://github.com/desktop/desktop/pull/8218, https://github.com/desktop/desktop/pull/8363, and https://github.com/desktop/desktop/pull/8363.

**Comment by vczh** [comment]
This happens to me too, when files are only getting `\n` <--> `\r\n` changed.

**Comment by steveward** [comment]
@MCnunzio I'm not sure I fully understand the directory structure you shared. How many repositories were you working with in this instance? Does attempting to commit directly from the command line produce any output?

**Comment by tierninho** [comment]
@MCnunzio As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
