### ISSUE TITLE
Error Fetch, Commit, Push, Pull

### ISSUE THREAD

**Issue by sodepr** [desktop/desktop#8442]
### Describe the bug

Refreshing ... forever
Commit Error. Lost data

### Version & OS

Version 2.2.1
Windows 10 1903

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for reaching out @sodepr !

It would be helpful if you could upload the log file from GitHub Desktop, which will give more details about the specific error you are seeing. 

To access the log files go to the  menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. 

The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue. Thanks!
