### ISSUE TITLE
A lock file blocks this operation from completing

### ISSUE THREAD

**Issue by chriswoodrum** [desktop/desktop#8449]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@chriswoodrum 👋 Try the instructions here: https://github.com/desktop/desktop/issues/6871

If you need further help, please fill out the template above and include your logs. Thanks.

**Comment by tierninho** [comment]
@chriswoodrum If you need further help, please reach out. Closing this issue for now.
