### ISSUE TITLE
Authentication Failed. Can pull but cannot push to my own repo

### ISSUE THREAD

**Issue by mnaoumov** [desktop/desktop#8454]
### Describe the bug

I can pull and clone any repositories. But cannot push to my own ones getting an error

![image](https://user-images.githubusercontent.com/735878/66707697-76a06a80-ed4d-11e9-8112-e3e4174c3ad3.png)

Tried all the suggested steps but no changes. Pushing from the console works fine.

If I clear stored credentials and push from the console again it brings the standard GitHub Windows Login dialog and works fine as soon as I type credentials.

### Version & OS

GitHub Desktop 2.2.1
Microsoft Windows 10 Version 1803 (OS Build 17134.1006)

### Steps to reproduce the behavior

Click `Publish branch` button having commits in your own repo

### Expected behavior

Commits are pushed to your own repo

### Actual behavior

Authentication failed error

### Screenshots

See above

### Logs

[2019-10-12.desktop.production.log](https://github.com/desktop/desktop/files/3721158/2019-10-12.desktop.production.log)

### Additional context

I noticed in the logs the following command

`git -c credential.helper= -c protocol.version=2 push origin merge-russian-alphabets:merge-russian-alphabets --progress`

When I execute it in the console it asks for my credentials in the console itself. When I provide them, push works. But when I run this command again it asks for the password again

**Comment by steveward** [comment]
Thanks for the report @mnaoumov. It's definitely strange that you are able to pull and clone without issue.

Can you try resetting GitHub Desktop to a fresh state by following these steps?

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop and log in and add your repositories again

Let me know if that helps.

**Comment by mnaoumov** [comment]
@steveward same issue

**Comment by mnaoumov** [comment]
I debugged and found the root cause of that issue.

I had some command in the registry `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor` so it added an extra line to stdout for each run of `cmd.exe`

The way GitHub authenticates commands is using custom `GIT_ASKPASS` script which relies on the `cmd.exe` output.

Closing the issue as it is not a bug and I see no reasonable workaround could be made here

**Comment by steveward** [comment]
@mnaoumov I'm glad to hear you got things working. We've seen errors caused by the `Command Processor` registry entry being modified but normally it throws an `askpass` error and not a generic authentication error. Thanks for sharing this information!

**Comment by freakersmind** [comment]
just push via command line using : `git push`
`post that GitHub Desktop works fine.
