### ISSUE TITLE
Support repository directory layout that includes owner

### ISSUE THREAD

**Issue by jcansdale** [desktop/desktop#8461]
### Describe the feature or problem you’d like to solve

When a user has cloned more than a few repositories, they will likely want to start organizing their repositories in a hierarchy that includes the repository `owner`. This avoids any possible namespace collisions and makes it easy to differentiate their own repositories, repositories owned by organizations they belong to and public repositories.

### Proposed solution

Desktop currently has great support for cloning repositories into a flat hierarchy and implicitly setting the default repository directory when a repository is cloned. This intuitive default behavior avoids the need for users to discover a default directory option.

The current behavior could be extended to infer not only the default repository directory, but also the user's preferred repository directory layout. This preferred layout could be used when the user next goes to clone a repository. Just like the default directory setting, the preferred layout could be changed simply be cloning a repository to a different location.

For example:

- If a user clones `https://github.com/jcansdale/repo_name` into `C:\Source\GitHub\repo_name`, infer a default directory of `C:\Source\GitHub` and a flat directory layout.
- If a user clones `https://github.com/jcansdale/repo_name` into `C:\Source\GitHub\jcansdale\repo_name`, infer a default directory of `C:\Source\GitHub` and a directory layout that includes the repository `owner`.

The above logic would be used not only when the default location is set, but also when the user edits the clone location or changes the target repository. This would create a smooth experience, where the user doesn't need to fight to use their preferred directory layout. 😄 

### Additional context

A similar technique has been used successfully in GitHub for Visual Studio. It uses Visual Studio's default clone directory and prefers the `owner/name` layout. The above proposal combines GitHub Desktop's inferred default directory with a non-prescriptive directory layout (the best of both worlds).

- Include owner in default path when cloning a repository
https://github.com/github/VisualStudio/pull/1906

**Comment by outofambit** [comment]
hey @jcansdale, thanks for suggesting this. i understand this is a pretty subtle change, and it does preserve existing functionality. however, this isn’t a common workflow we’ve seen requested in the desktop repo or in data we’ve collected. the workaround is also straightforward for those who do have this workflow. we try to be really careful about what we add to desktop, as every change has additional overhead over time.

**Comment by niik** [comment]
As per https://github.com/desktop/desktop/pull/8462#issuecomment-643306006 I'm going to close this as it's not a behavior we're intending to change at the moment and not one that we've seen a lot of feedback about.
