### ISSUE TITLE
Show percent of code fetched for the Fetch button

### ISSUE THREAD

**Issue by Rexogamer** [desktop/desktop#8464]
### Describe the feature or problem you’d like to solve

It’s impossible to know how much code is left to be fetched.

### Proposed solution

Show the percentage of code fetched on the fetch button.

### Additional context

Originally we presumed #8451 was for this but that is a different idea.

**Comment by outofambit** [comment]
hi @Rexogamer , the fetch button already has a progress bar and corresponding text showing the percentage complete. is this issue to add additional information to that? or perhaps its not prominent enough? thanks!

**Comment by Rexogamer** [comment]
Where is this progress bar and percentage complete?

**Comment by Rexogamer** [comment]
mind sending a screenshot?

**Comment by tierninho** [comment]
![Screen Shot 2019-10-15 at 10 51 05 AM](https://user-images.githubusercontent.com/14828183/66868778-b4fa7d00-ef39-11e9-98e3-e1cfe16baf33.png)

Note: the status is only shown when there is actually something to fetch, not when you click `fetch origin` and nothing is fetched.

Going to close this out as the feature already exists.
