### ISSUE TITLE
How to solve ask pass error?

### ISSUE THREAD

**Issue by edu0405** [desktop/desktop#8465]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.
![Error](https://user-images.githubusercontent.com/56531923/66793571-f6d6f380-ef38-11e9-86dd-160281aa8a65.png)

**Comment by tierninho** [comment]
@edu0405 Please see the workarounds listed here: https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789

If you still require assistance, please upload you logs -- see the Help menu in Desktop. Thank you.
