### ISSUE TITLE
add git reset function

### ISSUE THREAD

**Issue by lifelivelove** [desktop/desktop#8467]
currently there's no git reset function in desktop client. we need this. please add this in the next release

**Comment by steveward** [comment]
@lifelivelove thanks for the feedback! This request was previously captured in https://github.com/desktop/desktop/issues/5860. At this time we have not decided to implement a `git reset` option into GitHub Desktop. Please refer to @niik's response in https://github.com/desktop/desktop/issues/5860#issuecomment-428959691 for some further context around this decision.

Is there a specific workflow you have that requires using `git reset` often?
