### ISSUE TITLE
DX: line number colors and their meaning

### ISSUE THREAD

**Issue by staabm** [desktop/desktop#8469]
### Describe the feature or problem you’d like to solve

when clicking at the line number bar the line beeing clicked will change color.
it changes between green, red and blue.

![grafik](https://user-images.githubusercontent.com/120441/66839919-7b406b00-ef67-11e9-9160-d531639bb5bb.png)

nowhere is described what this colors mean. neither hovering the colors nor looking arround the app helps me to find out what this color changing thing is trying to tell me.

'feature request': 
- please tell me what this UI is trying to tell me :-)
- whats the use-case for this feature and what can I achieve with it?

using Version 2.2.1 on windows10x64

**Comment by billygriffin** [comment]
Hi @staabm, thanks for the issue. The ones highlighted in blue will be committed as part of your commit, whereas the ones not in blue will remain as uncommitted changes. This helps people break up their commits into smaller chunks that tell a more coherent story.

We agree that this could be made more discoverable and intuitive, but I'm going to close this issue as we haven't heard a ton of feedback about this and for many people, it's the feature they love most about the app so we're hesitant to make any drastic changes at this point.

**Comment by gingerbeardman** [comment]
Also came here, but specifically on a search to find out what clicking these colours is doing.

**Comment by jvossler-cogility** [comment]
I got here wanting to find out what each color means. White, red and green seem obvious. Blue and orange are not obvious (at least to myself and several others I work with).
