### ISSUE TITLE
Tutorial unaccessible if repo is removed or deleted

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#8471]
### Describe the bug

If you are on the Let's Get Started page, and have moved your Tutorial repo (or trashed it), the `Return to Tutorial` button remains and clicking does nothing.

### Version & OS

2.2.2-beta1, mac

### Steps to reproduce the behavior

1. Add tutorial
2. Exit back to Let's Get Started page
3. Go to local directory and trash tutorial repo
4. Click the `Return to Tutorial` button

### Expected behavior

Error message or `Return to Tutorial` button is removed/updated

### Actual behavior

Clicking the button does nothing. No logs.

### Screenshots

![Screen Shot 2019-10-15 at 8 01 24 AM](https://user-images.githubusercontent.com/14828183/66857293-ae144000-ef22-11e9-8bd4-5cfab9e323c5.png)

**Comment by billygriffin** [comment]
Thanks @tierninho! We discussed this and think it's unlikely to occur on a frequent basis, and we'd like it to come up in real life for someone before we solve this use case.

If anyone comes upon this issue and is struggling with what to do next, you can just move the repository locally back to the place it was when you created it, or restore from your Recycle Bin / Trash. Thanks!
