### ISSUE TITLE
Git LFS diff not working

### ISSUE THREAD

**Issue by ssiahpolo1** [desktop/desktop#8472]
I am trying to diff .ism file which is tracked by LFS using github desktop, but it only shows diff between 2 pointer files. How do I set up github desktop to show diff between .ism files

**Comment by tierninho** [comment]
@ssiahpolo1 Thanks for filing this issue. 

I guess it depends on the how you saved the ISM file -- ie., binary file or XML file. Binary files will not render in Desktop, while XML files should render. 

Let us know how it goes and any screenshots would be appreciated if further assistance is sought. 😄

**Comment by ssiahpolo1** [comment]
Thanks @tierninho  It is not binary file. But I figured that the issue is within my company, marked the file as LFS and therefore it doesn't give diff. I've asked them to remove it. Thank you so much for the response :)

**Comment by tierninho** [comment]
Glad you figured it out! 👍
