### ISSUE TITLE
Please don't move git.exe's location if an github desktop update doesn't update git's version.

### ISSUE THREAD

**Issue by vczh** [desktop/desktop#8473]
### Describe the feature or problem you’d like to solve

Please don't move git.exe's location if a github desktop update doesn't update git's version.

### Proposed solution

Right now git is in `X:\Users\<USER>\AppData\Local\GitHubDesktop\app-<VERSION>\resources\app\git\cmd`.

It is reasonable and important to use git.exe that exactly what github desktop is using while running script against github deskopt cloned repositories. I think you could store git in `X:\Users\<USER>\AppData\Local\GitHubDesktop\git-<VERSION>`, so that people could add this path to environment variables, and they are not required to change it as quickly as github desktop updates itself.

This is very useful when opening editors or command prompts directly from github desktop. Github desktop is being updated very quickly, but this is not the case of git.exe that is deployed along with github desktop.

### Additional context

N/A

**Comment by tierninho** [comment]
@vczh Thanks for reaching out and for using Desktop!

Please see this explanation of the git.exe location: https://github.com/desktop/desktop/issues/3708#issuecomment-354665183

As of now we do not plan to make any changes, so I am closing this issue.
