### ISSUE TITLE
Wrong icon for repository

### ISSUE THREAD

**Issue by RicardoLuis0** [desktop/desktop#8476]
### Describe the bug

Shows private "padlock" icon when in public repository that was private when cloned

### Version & OS

Version 2.2.1 & Windows 10 OS

### Steps to reproduce the behavior

1. Create Private Repository
2. Clone on Github Desktop
3. Make Repository Public

### Expected behavior

Public "book" icon

### Actual behavior

Private "padlock" icon

### Logs

[2019-10-16.desktop.production.log](https://github.com/desktop/desktop/files/3736853/2019-10-16.desktop.production.log)

**Comment by tierninho** [comment]
@RicardoLuis0 Thanks for filing. The update from public to private and vice-versa takes a minute or two to process through the system. 

Can you change repositories or push some code or quit and restart, and then recheck?

**Comment by RicardoLuis0** [comment]
I've made it public a few hours ago, and commited to it several times. I'll try restarting the app.

**Comment by RicardoLuis0** [comment]
No change after restarting Github Desktop. [The repository in question]( https://github.com/RicardoLuis0/Interpreter) can be accessed publicly.

**Comment by RicardoLuis0** [comment]
Nevermind, even though commiting or restarting the app did nothing, changing repositories worked and the icon is correct now.

**Comment by tierninho** [comment]
Ok great, thanks for the update!
