### ISSUE TITLE
Login Issue on Multi-user PC

### ISSUE THREAD

**Issue by jhobbs88** [desktop/desktop#8478]
### Authentication Error on Multi-user PCs

I use GitHub desktop in the classroom and have multiple students signing into the the same windows machines (into their own login account). Occasionally when they're opening GitHub desktop their repository list will be blank, or they will encounter an authentication failed loop where it keeps asking for their credentials even if the correct ones are entered.

The only way I have found to resolve this is by getting the student to sign out (File --> Options --> Sign Out) then sign back in again. This seems to refresh everything. 

### Version & OS

2.1.3 - Windows

### Steps to reproduce the behavior

1. User logs into PC
2. Opens GitHub Desktop
3. Works in repository without issues
4. Students logout of PC and will typically leave GitHub desktop signed in when they do so
5. Second student logs into PC
6. Opens GitHub Desktop
7. Either sees no repositories listed or gets stuck in authentication loop while attempting to clone one. 

### Expected behavior

Not encounter login issues

**Comment by jhobbs88** [comment]
Hi @steveward - I believe it is roaming profiles for the students to login. 

Is there a solution to resolve this issue for roaming profiles? 
Would ensuring students logged out of GitHub desktop at the end of class prevent the issue from occurring for the next user that signed in?

**Comment by steveward** [comment]
The `AppData\Roaming\GitHub Desktop` directory where cached data is stored should roam with a user account from computer to computer if you are using a domain with roaming profiles. You may need to reach out to your IT department to see if there are any specific Group Policy settings in place that could be interfering with things. 

Would you be able to test what data persists between log out/log in in `%AppData%\GitHub Desktop` and `%LocalAppData%\GitHubDesktop`? That may give some more information.

Also -- are you using the GitHub Desktop .msi installer to perform machine-wide installations?

**Comment by jhobbs88** [comment]
I believe the .msi installer was used for installation, but will double check with our tech dem who handled the installation. 

I will also check to see what data persits between logouts and get back to you with more information as soon as possible

Thanks

**Comment by jhobbs88** [comment]
Hi, I've checked the the ``%AppData%`` and have attached a screenshot of what is included. Is there anything specific I should be looking for between login/logouts?

<img width="851" alt="Screenshot (1)" src="https://user-images.githubusercontent.com/10423811/67204956-8e8b8480-f406-11e9-844e-13fc607a6592.png">

As for the %LocalAppData% there doesn't appear to be a GitHubDesktop folder in this directory.

When first logging into a student account I encountered the error in question, where a previously logged in GitHub account can't access repositories and the list is blank. Looking at the errors in the roaming data logs I notice the following error:

```
Error: Cannot update an account which doesn't have a token:
```

I also don't seem to  ever encounter the error when logging in under a staff account, suggesting it could be a privileges issue. The error is also inconsistent, students will only encounter it sometimes (although this is difficult to track as sometimes students use the same machines and other times they will switch).

**Comment by jhobbs88** [comment]
Further to the above after testing on multiple computers it seems the issue occurs when the student switches to a PC they have not used previously, suggesting their password details don't roam with them (there is no issue if the student logs in again on a pc they have previously used).

The difference when logging in under a staff account is that when roaming it asks the user to login afresh (e.g. start with the intial login screen on github desktop as if they have never logged in). Whilst for students it typically sends them to the lets get started screen as if they have logged in previously. --> I assume this therefore means there are some group policy settings we need to alter at our end to resolve the issues we are experiencing?

**Comment by steveward** [comment]
@jhobbs88 following up on this, apologies for the delay.

>it seems the issue occurs when the student switches to a PC they have not used previously, suggesting their password details don't roam with them (there is no issue if the student logs in again on a pc they have previously used).

Credentials are stored in `Credential Manager` -> `Windows Credentials` -- my guess is that those may not be roaming properly between machines. I'm not very familiar with getting that set up unfortunately.

> The difference when logging in under a staff account is that when roaming it asks the user to login afresh (e.g. start with the intial login screen on github desktop as if they have never logged in). Whilst for students it typically sends them to the lets get started screen as if they have logged in previously.

I'm not sure what would cause this behavior, but my guess would be the same as yours in that it would be a Group Policy setting. Does `File` > `Options` > `Accounts` show anything under a student account?

I'm going to close this issue out since this isn't related to anything we'll be changing in GitHub Desktop, but I'd be happy to continue this discussion and troubleshoot further @jhobbs88.
