### ISSUE TITLE
Typo in GitHub Desktop Metrics (errorWhenSwitchingBranchesWithUncommmittedChanges)

### ISSUE THREAD

**Issue by hubalazs** [desktop/desktop#8480]
There is a typo in errorWhenSwitchingBranchesWithUncommmittedChanges, it has 3 "m"s in it.

I guess this ID is also used on the server side, so this would involve more changes than this project.

**Comment by billygriffin** [comment]
Thanks @hubalazs! Thankfully when we did that, we copied/pasted the typo across, so it is flowing through properly. Unfortunately that also means that the typo will likely persist. Really appreciate you letting us know. 😄
