### ISSUE TITLE
Global Repo Folder ("projects" folder)

### ISSUE THREAD

**Issue by rgraffbrd** [desktop/desktop#8481]
### Describe the feature or problem you’d like to solve

I have a projects folder full of repos. I'd like to tell GitHub Desktop where that is and have it always know about all the repos in it.

### Proposed solution

Seems like an obvious missing feature but it'll just make it easier to have all your repos already in the app. (Multiple "projects" folders might even be a smart idea.)

### Additional context

IDEs and other code related apps usually have this, it's kind of your home base in that sort of app. I think this feature makes even more sense for GitHub Desktop because it can do things like open your repo in your IDE.

**Comment by tierninho** [comment]
@rgraffbrd Thanks for the suggestion. This has come up in the past a few times in various forms.

Our folder selector remembers the location of the most recent repo added from your local machine, so it should be hopefully convenient for you if you keep all repo in one folder. However, Desktop does not detect any new repos, as that could get messy quick.

We will revisit this request when the time comes to iterate in this area. Until then, the issue will be closed. We appreciate you utilizing Desktop!

**Comment by rgraffbrd** [comment]
@tierninho I think you could make it optional, and all you really want to do is list them, maybe not a full on import until one is selected. Does that make sense?

**Comment by rgraffbrd** [comment]
@tierninho Oh wait! You can drag and drop multiple projects!

Maybe just a little UX finesse to denote that may be the solution here :)
