### ISSUE TITLE
GitHub Desktop Takes Forever Buffering Cloning a Repository(Windows 10)

### ISSUE THREAD

**Issue by minegazioglu** [desktop/desktop#8483]
I'm using 64-bit version of Windows 10. Recently, I downloaded Github Desktop and tried to clone a repository from my GitHub account. At first I was getting authentication error:

![Error Image](https://user-images.githubusercontent.com/47893974/61480789-bfba6b80-a964-11e9-8910-e2bacc00c79f.png)

First 4 in that error list were not the problem, I went through them and checked they were not the case. I had no SSH key associated with my GitHub account and me being a newbie at this I generated a public SSH Key with SourceTree and added that to my GitHub account. This changed nothing.I still got the same error. I tried to find my SSH key and add to SSH agent on Git Bash but I got authorization error and frankly when I listed my SSH keys there were 3 and I had no idea how to copy which one to the agent. So decided to delete all keys I generated, basically any folder/subfolder with the name ssh.

After that I no longer got the error but when I try to clone my repository GitHub Desktop buffers forever "Cloning into ..". Then I changed my Windows Firewall Settings to allow incoming/outgoing connections for GitHub Desktop.This changed nothing as well and the buffering issue continues.

Can you suggest any possible reasons causing this and help me out?

Here is how my log file looks like :

![log file](https://cdn1.imggmi.com/uploads/2019/10/17/a1d9e93eed9a3d6dba17fe9d528cd43c-full.png)

**Comment by billygriffin** [comment]
Hi @minegazioglu, sorry for the delay in responding! Would you mind sharing what the issue turned out to be so we know for future?
