### ISSUE TITLE
support squashing commits for a pull request

### ISSUE THREAD

**Issue by ethanbsmith** [desktop/desktop#8486]
### Describe the feature or problem you’d like to solve

I'm working on a project that requires pull request to follow some guidelines. one of which is: 

"A pull request should only be for one issue, so please git rebase -i and squash the commits on your feature branch into one commit before creating the pull request. Please use git commit --amend to amend your commit" 

from: https://github.com/joshuaulrich/quantmod/blob/master/.github/CONTRIBUTING.md

I can't see how to do this using the desktop app

### Proposed solution

It would be great if the desktop app could support this command, or if the github web interface could execute arbitrary git command lines. 

### Additional context

I looked into how to issue command line git commands, but setting up the software and configuring it looked rather daunting.  I'm assuming that's why desktop was built in the first place.

thnaks

**Comment by tierninho** [comment]
@ethanbsmith Thanks for the write-up. The `git commit -amend` is current not part of Desktop, and it was previously requested here: https://github.com/desktop/desktop/issues/1644 so I will be closing this issue as a duplicate. 

The `git commit -amend` command can be used in the command line if you opt to go that route. More info here: https://help.github.com/en/articles/changing-a-commit-message

As for the squashing, you may visit the Settings page of your repository on GitHub.com to see squashing options. Once all the commits have been pushed from Desktop to GitHub.com, you will have the option to squash.

![Screen Shot 2019-10-17 at 1 41 00 PM](https://user-images.githubusercontent.com/14828183/67055410-c67f8880-f0e3-11e9-97b2-e00b8aa6593b.png)

> I looked into how to issue command line git commands, but setting up the software and configuring it looked rather daunting. I'm assuming that's why desktop was built in the first place.

Just right click the any file in Desktop to open the file in the command line. Here is a nice tutorial if ya want to give it a go: https://medium.com/@igor_marques/git-basics-adding-more-changes-to-your-last-commit-1629344cb9a8

Cheers!
