### ISSUE TITLE
I  can't clone my private repository in Win10

### ISSUE THREAD

**Issue by AlimyBreak** [desktop/desktop#8488]
### Describe the bug

I  can't clone my private repository in Win10

### Version & OS
Version 2.2.1 & win10

### Steps to reproduce the behavior
0. of course, I have signed in my account with my password
1. File - Clone repository ....
2. select my private repository 
3. Cloning ....
4. a few minutes later

there is no problem when  I try to sync my public repository.
& I can clone and upload changes to this repository in other pc which installed win7.

How can I make it work?

**Comment by AlimyBreak** [comment]
![1](https://user-images.githubusercontent.com/46748901/67055898-743e7600-f17c-11e9-9b69-ba20ceb9db93.jpg)
![2](https://user-images.githubusercontent.com/46748901/67055899-76a0d000-f17c-11e9-979e-41a3e7423f88.jpg)

**Comment by tierninho** [comment]
@AlimyBreak Thanks for reaching out. Do you have any firewall or anti-virus software running? Please disable and and attempt the clone again. You can also try SSH as a workaround for above, or even a shallow clone like so:

```
$ git clone http://github.com/MyRepo --depth 1
$ cd MyRepo
$ git fetch --unshallow
```

If this doesn't help, possible to share your logs as well? (See the Help menu in Desktop.) And the repo link?

**Comment by tierninho** [comment]
@AlimyBreak  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
