### ISSUE TITLE
the ability to solve conflicts during merging branches 

### ISSUE THREAD

**Issue by philipdenys** [desktop/desktop#8489]
### Version & OS

Mac 10.15 (19A583)

### Steps to reproduce the behavior

1. Go to current branch dropdown menu
2. Click on 'merge into this branch
3. '2 conflicts' error
4.  no links to conflicts shown

### Expected behavior

Generate links of conflicts and option to open editor to solve conflicts

### Actual behavior

Shows conflicts but merges anyway

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by billygriffin** [comment]
Hi @philipdenys, thanks for the issue. It definitely shouldn’t happen in the manner you’re describing. Would you mind updating your issue with the version of Desktop you’re using, screenshots of what’s happening at each stage if possible, and the Logs from a day when this occurred? We need a bit more information to investigate this. Thanks!

**Comment by philipdenys** [comment]
can't reproduce... solved I guess 😄

**Comment by billygriffin** [comment]
Well I guess that's good news @philipdenys! Please do let us know if you see it again, as that's definitely something we'd want to dig into right away. ❤️
