### ISSUE TITLE
Add some visual indication that you can drag and drop to add Multiple Repos

### ISSUE THREAD

**Issue by rgraffbrd** [desktop/desktop#8490]
### Describe the feature or problem you’d like to solve

When adding existing repos, you can, if you just try, add multiple repos but there is no obvious indication that this is possible.

### Proposed solution

There should just be some visual hint that users can drag and drop in all of their repos.

### Additional context

I think this issue [here](https://github.com/desktop/desktop/issues/4004) seems to imply that this has somehow been added but I didn't see anything obvious so I thought I might submit an issue to see what bubbles up again.

**Comment by tierninho** [comment]
@rgraffbrd Thanks for reaching out with the suggestion.

Currently, we mention the ability to add multiple repos via `drag+drop` in our documentation [here](https://github.com/desktop/desktop/blob/b91e7dd06b7561b762afa2065e8a976bb23bbf5d/README.md#where-can-i-get-it) and [here](https://help.github.com/en/desktop/contributing-to-projects/adding-a-repository-from-your-local-computer-to-github-desktop), and the general ability to `drag+drop` in the app itself [here](https://github.com/desktop/desktop/blob/7598b986fe3f6b817e1bc865dec28f63619a4e57/app/src/ui/no-repositories/no-repositories-view.tsx#L436).

Should we receive more feedback from users that there is a discoverability problem, we will be happy to revisit this issue. We appreciate you using Desktop! 😄
