### ISSUE TITLE
Pushing often fails

### ISSUE THREAD

**Issue by blacktop** [desktop/desktop#8494]
### Describe the bug
Commit then push:
```
Enumerating objects: 9, done.
Counting objects:  11% (1/9)   
Counting objects:  22% (2/9)   
Counting objects:  33% (3/9)   
Counting objects:  44% (4/9)   
Counting objects:  55% (5/9)   
Counting objects:  66% (6/9)   
Counting objects:  77% (7/9)   
Counting objects:  88% (8/9)   
Counting objects: 100% (9/9)   
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects:  25% (1/4)   
Compressing objects:  50% (2/4)   
Compressing objects:  75% (3/4)   
Compressing objects: 100% (4/4)   
Compressing objects: 100% (4/4), done.
Writing objects:  20% (1/5)   
Writing objects:  40% (2/5)   
Writing objects:  60% (3/5)   
Writing objects:  80% (4/5)   
Writing objects: 100% (5/5)   
Writing objects: 100% (5/5), 1.18 KiB | 1.18 MiB/s, done.
Total 5 (delta 2), reused 0 (delta 0)
remote: Resolving deltas:   0% (0/2)        
remote: Resolving deltas:  50% (1/2)        
remote: Resolving deltas: 100% (2/2)        
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.        
To https://github.com/blacktop/ghidra.git
 ! [remote rejected]   master -> master (refusing to allow an integration to create or update .github/workflows/gradle.yml)
error: failed to push some refs to 'https://github.com/blacktop/ghidra.git'
```

### Version & OS
2.2.1/macOS

VSCode can commit/push however.

Maybe it's timing out?

**Comment by steveward** [comment]
@blacktop thanks for contributing! This error is due to the fact that you are using GitHub Actions with this repository. Logging out and then logging back in to GitHub Desktop should get things working for you again. This will be fixed in an upcoming release -- see [this comment](https://github.com/desktop/desktop/issues/7079#issuecomment-537904024) for more information.

**Comment by lubas569** [comment]
#3814

**Comment by lubas569** [comment]
> #3814



> ### Describe the bug
> Commit then push:
> 
> ```
> Enumerating objects: 9, done.
> Counting objects:  11% (1/9)   
> Counting objects:  22% (2/9)   
> Counting objects:  33% (3/9)   
> Counting objects:  44% (4/9)   
> Counting objects:  55% (5/9)   
> Counting objects:  66% (6/9)   
> Counting objects:  77% (7/9)   
> Counting objects:  88% (8/9)   
> Counting objects: 100% (9/9)   
> Counting objects: 100% (9/9), done.
> Delta compression using up to 8 threads
> Compressing objects:  25% (1/4)   
> Compressing objects:  50% (2/4)   
> Compressing objects:  75% (3/4)   
> Compressing objects: 100% (4/4)   
> Compressing objects: 100% (4/4), done.
> Writing objects:  20% (1/5)   
> Writing objects:  40% (2/5)   
> Writing objects:  60% (3/5)   
> Writing objects:  80% (4/5)   
> Writing objects: 100% (5/5)   
> Writing objects: 100% (5/5), 1.18 KiB | 1.18 MiB/s, done.
> Total 5 (delta 2), reused 0 (delta 0)
> remote: Resolving deltas:   0% (0/2)        
> remote: Resolving deltas:  50% (1/2)        
> remote: Resolving deltas: 100% (2/2)        
> remote: Resolving deltas: 100% (2/2), completed with 2 local objects.        
> To https://github.com/blacktop/ghidra.git
>  ! [remote rejected]   master -> master (refusing to allow an integration to create or update .github/workflows/gradle.yml)
> error: failed to push some refs to 'https://github.com/blacktop/ghidra.git'
> ```
> 
> ### Version & OS
> 2.2.1/macOS
> 
> VSCode can commit/push however.
> 
> Maybe it's timing out?
