### ISSUE TITLE
Add shortcut keys on the hover Suggestions

### ISSUE THREAD

**Issue by AashifAhamed** [desktop/desktop#8495]
### Describe the feature or problem you’d like to solve
give shortcut suggestions when the mouse hovers the button. for example in the picture which I include below, instead of show the date as the suggestion we can display the shortcut keys of the pull and push. 

![Screenshot (3)](https://user-images.githubusercontent.com/41619372/67149232-609f2680-f2c6-11e9-8d67-9176ccad248d.png)

### Proposed solution

How will it benefit Desktop and its users?

It will more easy and efficient work for the user.

[![ForTheBadge built-with-love](http://ForTheBadge.com/images/badges/built-with-love.svg)](https://GitHub.com/Naereen/)

**Comment by tierninho** [comment]
@AashifAhamed Thanks for the suggestion. We will take it into consideration during our next iteration of that feature. For now, you may see all the shortcuts listed next to each menu item, like so:
![Screen Shot 2019-10-21 at 8 29 44 AM](https://user-images.githubusercontent.com/14828183/67232453-19578980-f3dd-11e9-9298-b734ba0edbc7.png)

Also, we have a shortcut guide in the Help menu, here: https://help.github.com/en/desktop/getting-started-with-github-desktop/keyboard-shortcuts-in-github-desktop
