### ISSUE TITLE
GitHub desktop does not initialize submodules

### ISSUE THREAD

**Issue by wandyezj** [desktop/desktop#8496]
### Describe the bug

GitHub desktop does not initialize submodules

This causes issues when using repositories with submodules.

### Version & OS

2.2.1
Windows 10

### Steps to reproduce the behavior

1. Clone a repository with submodules.
    - `git clone https://github.com/Team488/XbotEdu.git`
1. open GitHub Desktop
1. open the repository
1. observe that submodules are not initialized

### Expected behavior

submodules should be initialized.

### Actual behavior

submodules are __not__ initialized.

### Additional context

I'm help teach High School robotics, there is a common library that is used year to year. Submodules are used to distribute the library between years and repositories (it makes it easy to fix bugs in common code). Many students are not familiar with git. We currently use smart git, but would like to switch to GitHub Desktop as it has a much better overall experience.

**Comment by marc2k3** [comment]
Use Desktop to clone the repo and it will do it automatically...

`File>Clone repository>URL`. Enter `Team488/XbotEdu`.

If you really want to clone using the command line first then you should add `--recurse` like this...

`git clone https://github.com/Team488/XbotEdu.git --recurse`

**Comment by steveward** [comment]
@wandyezj thanks for contributing! What @marc2k3 said is correct -- if you clone the repository using GitHub Desktop it will pull down all of the submodules associated with the repository since we pass the necessary `--recursive` flag during the clone operation. Using `git clone` on the command line will not pull down submodules by default. 

We also have a [tracking issue](https://github.com/desktop/desktop/issues/7523) for improving working with submodules. You can reference that for some of the current limitations. 

I'm going to close this issue out, but if you have any questions or issues I'd be happy to help.

**Comment by wandyezj** [comment]
Thank You @marc2k3 and @steveward !

:D

**Comment by phanhoangminhluan** [comment]
Hello @steveward, could you give me some hints about managing 3 independent projects in 1 repository. I have searched around the internet and i found the concept of **Submodules**. 
However, as a github desktop user, i can't find any setting or menu item related to create a Submodule.
Could you help me to clarify this ?. I really need it for my school project. 
Thank you very much and hope to hear your response soon.

**Comment by tierninho** [comment]
@phanhoangminhluan Here is a nice beginning guide to submodules: https://github.blog/2016-02-01-working-with-submodules/ 

Desktop does not directly allowing you to create buttons/menu, but we do support them. 

Hope this helps! and thanks for using Desktop!

**Comment by dawhum** [comment]
@tierninho This is widely disappointing. If I wanted to use the command line for Git, I wouldn't have downloaded your client in the first place.

**Comment by AWqxKAWERbXo** [comment]
Same for me - a GUI would help me to understand what's needed.

**Comment by matheus-kirchesch-old** [comment]
For maintainability, i like to use the Desktop client, i see no problem in using the terminal to git submodule update --remote

BUT

It would be really cool if we had a button in the app to update the submodules, or maybe check if there are updates to the modules and ask us if we want to download it

**Comment by shalva97** [comment]
Any updates on this. It been many years
