### ISSUE TITLE
atom no attached

### ISSUE THREAD

**Issue by Rich-cat** [desktop/desktop#8499]
hello,I have already downloaded the atom but we I use github desktop,it shows me  _**no editors found**_, so how can I solve this problem? thanks a lot.

**Comment by steveward** [comment]
👋 @Rich-cat 

Could you open up a command prompt (cmd.exe) and run the following commands for me?

`cd %LOCALAPPDATA%\Atom\`
`atom --squirrel-updated`

Then try restarting GitHub Desktop and let me know if you still do not see Atom in the dropdown menu.

**Comment by tierninho** [comment]
@Rich-cat  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by Neustradamus** [comment]
@Rich-cat: What is your Windows version?
