### ISSUE TITLE
Crash when attempting to clone

### ISSUE THREAD

**Issue by DouglasUrner** [desktop/desktop#8500]
### Describe the bug

Crash when attempting to clone a repository.

### Version & OS

GitHub Desktop: 2.2.1
macOS: 10.15.1 Beta (19B77a)

### Steps to reproduce the behavior

1. Find a Mac
2. Install 10.15.1 Beta (19B77a)
3. Launch GitHub Desktop
   - Maybe remove some old repositories that you are no longer using, including a few that have been moved.
4. From the Current Repository choose Add > Clone Repository
5. Crash

### Expected behavior

Expected the Clone a Repository dialogue.

### Actual behavior

GitHub Desktop vanishes without an error message. This happened two times, on the second crash there was the expected "Application exited unexpectedly" window/dialogue from macOS.
After briefly describing the problem and clicking the reopen button GitHub Desktop launched and I was able to clone a repository from GitHub.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Logs are not displayed. The Show Logs in Finder menu item is displayed (over the menu bar) but it is not active. I found log files in ~/Library/Application Support/GitHub Desktop/Logs - todays is attached below. I also found a files called LOG and LOG.old in the GitHub Desktop directory, they are also attached.

[2019-10-20.desktop.production.log](https://github.com/desktop/desktop/files/3748522/2019-10-20.desktop.production.log)
[LOG.old.txt](https://github.com/desktop/desktop/files/3748526/LOG.old.txt)
[LOG.txt](https://github.com/desktop/desktop/files/3748527/LOG.txt)

### Additional context

Screen capture showing Help menu, note that the menu item overlaps the menu bar. It is also unclickable.

<img width="973" alt="Screen Shot 2019-10-20 at 16 06 21" src="https://user-images.githubusercontent.com/4495780/67168137-f635c700-f355-11e9-80f2-334735860487.png">

**Comment by tierninho** [comment]
@DouglasUrner Thanks for sharing. 

In your logs, I see lots of 404 errors when trying to fetch `DouglasUrner/Prototype-1`. I cloned the repo successfully on my end. 

Based on the strange behavior of the application, I suggest downloading a fresh copy of Desktop, then try logging in and recloning your repo (if you are still having issues).

**Comment by outofambit** [comment]
Hi @DouglasUrner! I'm sorry you're experiencing this, but we don't support beta versions of macOS. I'm going to close this issue, but if you are able to reproduce this on a stable version of macOS, please let us know and we'll reopen to discuss. Thank you!
