### ISSUE TITLE
Insufficient Documentation

### ISSUE THREAD

**Issue by callebdev** [desktop/desktop#8502]
GitHub desktop has insufficient documentation, principally for beginners.
Can you add some additional information about how to use it and ?

**Comment by steveward** [comment]
Thanks for the feedback @callebdev. There are a few things that currently exist that should be helpful for getting started with GitHub Desktop:

1. There is a guide in the help docs called ["Creating your first repository using GitHub Desktop"](https://help.github.com/en/desktop/getting-started-with-github-desktop/creating-your-first-repository-using-github-desktop) that walks you through the process of creating your first repository all the way through to committing and pushing your changes up to GitHub. I'd love to hear feedback about how we could make this guide better. 

2. We also recently added the option to create a tutorial repository when you launch GitHub Desktop for the first time. This walks you through working with a repository and helps you get familiar with using GitHub Desktop.

Is there any specific documentation that you would like to see added?

**Comment by callebdev** [comment]
Thank you, I'll check it out.

Em seg, 21 de out de 2019 às 15:30, Steve Ward <notifications@github.com>
escreveu:

**Comment by billygriffin** [comment]
I'm going to close this since hopefully that's what you were looking for. Please let us know if there are other things that feel missing or incomplete!
