### ISSUE TITLE
Refresh list of repos by reading all folders/subfolder on my hard drive

### ISSUE THREAD

**Issue by cavo789** [desktop/desktop#8503]
Hi all

For an unknown reason, Github desktop was no more on my computer this morning (I suppose due to a bad action of my IT department).

My question for your developers: like other tools (I think here to the `Fork` client), is it possible please to provide an option in GitHub Desktop to scan a folder on my hard drive (let's say `c:\repositories`) and to add in the GitHub Desktop repos list, all my local repo?

On my side, I've a folder by "project" and subfolders in it with my repos.

I've almost 100 repos so adding folders (repos) one by one is no more an option for me.

Thanks a lot!

**Comment by steveward** [comment]
@cavo789 thanks for the feedback. This feature request is being tracked in https://github.com/desktop/desktop/issues/1574 -- you can follow along there for updates.

You can bulk-select repositories using shift-click in File Explorer and then drag-and-drop them directly into GitHub Desktop to add them. That's the best solution currently available for adding a large number of repositories.

**Comment by cavo789** [comment]
That's a very fast answer and a nice tip (had never tried this before; cool!)

Thanks Steve.
