### ISSUE TITLE
Stating that a repository is gone when it isnt

### ISSUE THREAD

**Issue by primrose-burdess** [desktop/desktop#8504]
So I have a repository on my local disk and i have cloned it successfully. However when I go to pull the repo, it states the following __"The repository does not seem to exist anymore. You may not have access, or it could have been deleted or renamed"__ How ever this is not the case as it is still on my local disk and I have checked online to see if my repository is still there which it is. 

### Version & OS

I am using Version 2.21 of GitHub Desktop and my OS is Windows 10

### Steps to reproduce the behavior

1. Go to https://github.com/aitsoftwaredesign/gd3individual-primrose-burdess.git
2. Click on pull origin
3. See error

### Expected behavior

I should've been able to pull down my origin so I could work on the latest version of my work

### Actual behavior

The error window appears and it states that the repository does not seem to exist anymore. You may not have access, or it could have been deleted or renamed.

### Logs

[2019-10-21.desktop.production.log](https://github.com/desktop/desktop/files/3751620/2019-10-21.desktop.production.log)

**Comment by tierninho** [comment]
@primrose-burdess Thanks for reaching out. Do you have access rights from the organization `aitsoftwaredesign` as they own the repo? 

Based on your logs, it looks like you may be getting the same error for some of your own repos, KittyMaze and PhysicsAssignment? I suggest logging out and logging back in to start.

Did Desktop also show a modal like one of these?
![Screen Shot 2019-10-21 at 7 45 50 AM](https://user-images.githubusercontent.com/14828183/67229362-dc889400-f3d6-11e9-8da2-7900bf527f5e.png)
![Screen Shot 2019-10-21 at 7 45 30 AM](https://user-images.githubusercontent.com/14828183/67229363-dc889400-f3d6-11e9-8683-4d8bf299f369.png)

**Comment by primrose-burdess** [comment]
Hi there,
Im 99% sure I have access rights to the repo as this issue hasn’t appeared before. The desktop didn’t show any of the models below and I will take your advice for logging out and logging back in again.
Thanks for helping me :)


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by tierninho** [comment]
@primrose-burdess Let us know if we can further assist and we will be happy to reopen the issue. Thanks for using Desktop.
