### ISSUE TITLE
Unable to use GitHub Desktop on MacOS Catalina 10.15

### ISSUE THREAD

**Issue by erinjerri** [desktop/desktop#8506]
### I'm unable to install. 

I get this error message here.

<img width="527" alt="Screen Shot 2019-10-21 at 5 50 59 PM" src="https://user-images.githubusercontent.com/3184381/67253233-8265ee00-f42b-11e9-8447-01ad5315d3bc.png">

I've tried modifying for privacy, but I'm thinking it's versioning support from Mac?

**Comment by tierninho** [comment]
@erinjerri Please try going 🍎 > Software Preferences > Security & Privacy > general tab

Do you see anything where the red box is? And which radio button is selected above this?
![Screen Shot 2019-10-21 at 2 54 12 PM](https://user-images.githubusercontent.com/14828183/67253340-d2848680-f412-11e9-847e-c09c150c7b71.png)

Also, what version of OS are you on? Thanks.

**Comment by erinjerri** [comment]
Ah got it to work, had to hit 'open anyway' just really annoying to do this everytime. 

![Uploading Screen Shot 2019-10-21 at 6.00.46 PM.png…]()

**Comment by tierninho** [comment]
Awesome, thanks for the update.

**Comment by billygriffin** [comment]
@erinjerri Out of curiosity, are you using macOS Catalina?

**Comment by FatimaVelic** [comment]
Hi, 
Sorry for opening this again but I have the same problem with macOS Catalina and this solution is not working. This is the message I get every time I try to install it: 
![Screenshot 2019-10-28 at 12 04 15](https://user-images.githubusercontent.com/34818034/67673755-23e4c680-f97b-11e9-934d-8284252e3801.png)

**Comment by tierninho** [comment]
@FatimaVelic Can you attempt to install again and then send a screenshot of the System Preferences page mentioned here: https://github.com/desktop/desktop/issues/8506#issuecomment-544767646 ?

**Comment by FatimaVelic** [comment]
@tierninho I managed to install it but I had to run _sudo spctl --master-disable_ command to go around Gatekeeper. This probably, is not the smartest nor safest solution but, after the installation, I restored my previous Security and Privacy settings and it works absolutely fine, with no delays or crashes whatsoever.

**Comment by daumling** [comment]
The app needs to notarized. Not a big issue, but it must be done.

**Comment by billygriffin** [comment]
@daumling We're working on exactly that, planning to release next week hopefully. Thanks for your patience everyone!

**Comment by billygriffin** [comment]
Since this issue is closed, I'm going to reopen it so we can track it in the context of the PR we're working on to fix this.

**Comment by billygriffin** [comment]
This should no longer be an issue as of today's release! Please let us know if you're continuing to have problems installing on Catalina.

**Comment by Yellowats** [comment]
Hello, I am trying to install GitHub on MacOs Catalina and I have the same problem stated here.

**Comment by billygriffin** [comment]
@Yellowats Thanks for letting us know! Would you mind filling out a new bug report please? https://github.com/desktop/desktop/issues/new/choose

This should be working correctly, so we need to see more details about your setup to hopefully try to diagnose what might be happening.

**Comment by ekgreen42** [comment]
I have the same issue as @Yellowats!
![Screen Shot 2020-05-19 at 5 00 03 PM](https://user-images.githubusercontent.com/65633297/82390603-013bfd00-99f4-11ea-9a20-6f0a42e255b2.png)

**Comment by steveward** [comment]
@ekgreen42 this issue tracker is for GitHub Desktop. If you are having issues with Sourctree you will need to reach out to Atlassian support for help.

**Comment by ekgreen42** [comment]
Apologies @steveward ! Sorry for the mistake, thank you for pointing me in the right direction.

**Comment by travisfranck** [comment]
Seeing this problem again for a build of GitHub Desktop that we downloaded today.

**Comment by Dragoncito2039** [comment]
How can i download, github for MacOS Catalina 10.15.8?
