### ISSUE TITLE
Can't publish a repository if remote already exists

### ISSUE THREAD

**Issue by aminya** [desktop/desktop#8507]
### Describe the bug

 Github Desktop assumes that if a remote exists, then the repo must already exist upstream.

### Version & OS

Version 2.2.1 Win 10

### Steps to reproduce the behavior

1. Create a local Git repository that have a remote already created. You can do that using [PkgTemplate.jl](https://github.com/invenia/PkgTemplates.jl) 
2. Click on publish repository
3. See error

### Expected behavior

Publish repository to Github

### Actual behavior

Fails publishing

### Screenshots

![image](https://user-images.githubusercontent.com/16418197/67258820-1188fb00-f458-11e9-8d9f-3813ee6190f1.png)

### Additional context

Reported by many users such as here https://github.com/desktop/desktop/issues/7686 :

> 
> ## Description
> 
> I deleted an older repository on GitHub as some things messed up and now I am trying to add the same project folder to GitHub. However, every time I select my project folder to upload it as an existing repository, it seems to try to commit to the deleted repository. No matter what I do, it just keeps on trying to commit to the no longer existing repo. I have even tried to create a repo from the desktop but identifies that it's "already on GitHub" when I know it isn't as I deleted it.
> ## Version
> 
>     * GitHub Desktop:
>       1.6.6
> 
>     * Operating system:
>       Microsoft Windows [Version 10.0.17763.504]
> 
> 
> ## Steps to Reproduce
> 
> Step 1: Have a Visual Studio Project folder and uploaded to a repo on GitHub
> Step 2: delete the repo on GitHub and remove it from GitHub Desktop (without moving project to recycling bin)
> Step 3: Try to upload the project again via GitHub Desktop
> ### Expected Behavior
> 
> Able to start a new repo with my already made project
> ### Actual Behavior
> 
> Tells me to push 6 commits to the origin remote
> Error message when doing so: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.
> ### Logs
> 
> [2019-06-05.desktop.production.log](https://github.com/desktop/desktop/files/3255182/2019-06-05.desktop.production.log)

[here](https://github.com/desktop/desktop/issues/5491)

> > 
> ## Description
> 
> Loggers when additional remote no longer exists.
> ## Version
> 
>     * GitHub Desktop: 1.3.5-beta0
> 
> 
>     * Operating system: Windows 10
> 
> 
> ## Steps to Reproduce
> 
>     1. Clone a repo (Desktop for example)
> 
>     2. Fork it to your personal account
> 
>     3. Add it as a remote, and checkout a branch from the remote on your personal account
> 
>     4. Delete the remote repo
> 
>     5. See the loggers 🔥.
> 
> 
> ### Expected Behavior
> 
> Warn user that remote no longer exists.
> ### Actual Behavior
> 
> Nothing really.

 and here https://github.com/invenia/PkgTemplates.jl/pull/61. by me 
> 
> 
> nAny chance that Desktop can create the repo if it doesn't already exist in this case? I had someone run into this issue when using [my package](https://github.com/invenia/PkgTemplates.jl) which creates local Git repos that have a remote already created.
> 
> ref: [invenia/PkgTemplates.jl#61 (comment)](https://github.com/invenia/PkgTemplates.jl/pull/61#issuecomment-544208700)

**Comment by tierninho** [comment]
> Reported by many users such as here #7686

@aminya Is this the same issue you are experiencing? Does the workaround in that issue help resolve your issue?


To clarify, you are asking to publish a repo that has its remote defined ahead of time, and then for Desktop to not error out? How is your package related to this or did someone just run into the issue coincidentally while using your package? 

Thanks.

**Comment by aminya** [comment]
@tierninho The workaround isn't a solution. It is just copying the files to a new local git repository and creating a new remote repository. 

Yes, consider the address of the remote is already configured, and you want to publish it. It isn't possible to do that. 

Tha PkgTemplate.jl is a Julia package, which generates a template for new packages (repositories). It can configure the remote repository ahead of the time.

**Comment by tierninho** [comment]
Thanks for the added details. 

Unfortunately, this is not something we will be working on right now, as our [product roadmap] (https://github.com/desktop/desktop/blob/development/docs/process/roadmap.md) is quite full at the moment. This issue will be reopened should we decide to revisit this feature change.

**Comment by billygriffin** [comment]
Adding to @tierninho's thoughts, because #5491 is still an open issue, I think this particular case is too much of an edge case to prioritize. If the repo is *gone* because it's been deleted from the remote, I think we can handle that a bit better as described in #5491, but we don't think that happens a tremendous amount either.
