### ISSUE TITLE
Couldn't commit

### ISSUE THREAD

**Issue by sodepr** [desktop/desktop#8510]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.
![image](https://user-images.githubusercontent.com/55951715/67293999-6e93b800-f50f-11e9-8234-aba4f80146af.png)
![image](https://user-images.githubusercontent.com/55951715/67294037-781d2000-f50f-11e9-885d-476b4c3c600e.png)

### Steps to reproduce the behavior

I click commit to master many times. But it's not commit.

### Expected behavior

I want to it commit my change

### Actual behavior

Nothing happens

### Screenshots

![image](https://user-images.githubusercontent.com/55951715/67294147-a995eb80-f50f-11e9-8a5c-c076e8776bfb.png)

### Logs

[2019-10-22.desktop.production.log](https://github.com/desktop/desktop/files/3756131/2019-10-22.desktop.production.log)

**Comment by steveward** [comment]
@sodepr thanks for the report. It looks like you are attempting to commit a large number of files, which could be causing the commit process to take a longer period of time. Are you able to try committing a smaller subset of files to see if that succeeds?

**Comment by tierninho** [comment]
@sodepr  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
