### ISSUE TITLE
pressing the Return key does not commit your changes

### ISSUE THREAD

**Issue by snoblenet** [desktop/desktop#8515]
### Describe the bug

1. Select changes
2. Write a commit name
3. Press the Return key on your keyboard
4. The changes are not committed

### Version & OS

GitHub Desktop 2.2.1
Mac OS X 10.15

### Steps to reproduce the behaviour

1. Select changes
2. Write a commit name
3. Press the Return key on your keyboard

### Expected behaviour

The changes are committed

### Actual behaviour

The changes are not committed

**Comment by steveward** [comment]
Thanks for contributing @snoblenet. You can use `CMD+Enter` to commit your changes after entering a commit message. I hope that is helpful!
