### ISSUE TITLE
Make Changes/History tabs look more like tabs

### ISSUE THREAD

**Issue by heronils** [desktop/desktop#8518]
It is best explained by screenshot. Lets take the screen from Github Desktop's [start page](https://desktop.github.com/). How it looks now:

![github-desktop-screenshot-now](https://user-images.githubusercontent.com/6892179/67409798-58433600-f5bb-11e9-95d6-9de981ee8322.jpg)

Here, on  the top left,  i constantly click on the wrong tab - my brain considers the tab with the blue line to be the inactive tab, because it looks like the blue line is hidden behind the other tab.

This gimpified image is what i would suggest instead:

![github-desktop-screenshot-then](https://user-images.githubusercontent.com/6892179/67410020-bcfe9080-f5bb-11e9-8d22-1835c7ba9d35.jpg)

Here, due to the missing line between the active tab and the gray background of the inactive tab it becomes clear which is the active tab.

Btw, the tabs over this Github text entry are also designed that way.

**Comment by billygriffin** [comment]
Hi @heronils, thanks for the feedback. I totally understand why you might see it that way and how it might cause confusion for you. However, this was a deliberate design choice and absent a ton of feedback that it's confusing for people, we don't think changing a really commonly interacting with part of the app would be a good decision. Many people have gotten used to the way it works currently, so we don't want to make them adjust their expectations as well. Thanks again and appreciate your idea!

**Comment by heronils** [comment]
@billygriffin I have to insist a bit on this issue.

The reason is that one of, if not _the_ worlds leading usability expert, Jakob Nielsen, claims exactly what i claim:

[tabs, used Right](https://www.nngroup.com/articles/tabs-used-right/)

Please consider **point five** ("Highlight the currently selected tab") and especially **point seven** ("Connect the current tab to the content area")

May i kindly ask for a confirmation by another team member that this issue has at least been seen by any other person in your team and that he agrees with your decision to close this issue? should this be the case i will stop to nag and accept my defeat :-)

Thank you in advance for your time.

**Comment by heronils** [comment]
@billygriffin OK. It is your Karma now.
