### ISSUE TITLE
Github Desktop acts modeless but needs to be modal

### ISSUE THREAD

**Issue by johnkslg** [desktop/desktop#8520]
### Describe the bug

Github allows you to perform concurrent operations, but totally blows up your gitrepro if you do so.
IE, try pushing a branch and then immediately switching branches.
Or try rapidly clicking various operations in turn.
You will reliably see your git repo turned to mush, a stray git lock lying around, and LFS in convulsions in the background.  

Best reproed on a large project using LFS.

Solution: Make concurrent operations work, or prevent concurrent operations from concurring. 

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@johnkslg Please provide clear steps to reproduce the issue, along with the missing details above so we may better assist you. Thank you.
