### ISSUE TITLE
Downloaded Git Hub Desktop -- Cannot Open because Apple cannot check for malicious software

### ISSUE THREAD

**Issue by AFogarty72** [desktop/desktop#8521]
I've never run into this issue before using Github Desktop, but I recently downloaded and saw the most current releases were made today, so I wasn't sure if it was correlated. 

I'm seeing this error anytime I try to start up my github desktop for the first time upon installation. 

![Screen Shot 2019-10-23 at 2 16 58 PM](https://user-images.githubusercontent.com/16338229/67434910-f0332680-f59f-11e9-81b4-e87bd6ef8231.png)

Tried uninstalling and reinstalling, made sure my Mac was up to date on software updates, MacOS Catalina v. 10.15 

Please let me know if I am missing something or if there's something I can do.

Thank you so much dev team!

**Comment by tierninho** [comment]
@AFogarty72 Please see the reply here from a similar issue: https://github.com/desktop/desktop/issues/8506#issuecomment-544767646

**Comment by AFogarty72** [comment]
Thank you 🙏 all fixed.
