### ISSUE TITLE
macOS High Sierra - GitHub Desktop met with blank white screen and indefinite loading

### ISSUE THREAD

**Issue by electro-jbillings** [desktop/desktop#8523]
### Describe the bug

Github Desktop was working fine for me last week, but on Monday my repos wouldn't synch. I closed the app and reopened it only to be met with a blank white window. I deleted the folder ~/Library/Application Support/Github Desktop/ and that got me a fresh welcome screen, but everything is running very very slowly. I was able to sign in and add back one of my local repos, but that is where I am stuck. My avatar remains the default and the window is now "refreshing repository" indefinitely.

I've attempt fixes mentioned in #4833 and #5387 and that got me to where I am now, but I haven't found anything to fix the indefinite loading and slowness.

### Version & OS

Github Desktop v2.2.2

MAC OS High Sierra 10.13.6
Model Name:	MacBook Pro
Model Identifier:	MacBookPro11,5
Processor Name:	Intel Core i7
Processor Speed:	2.8 GHz
Number of Processors:	1
Total Number of Cores:	4
L2 Cache (per Core):	256 KB
L3 Cache:	6 MB
Memory:	16 GB

[2019-10-23.desktop.production.log](https://github.com/desktop/desktop/files/3765076/2019-10-23.desktop.production.log)
[2019-10-24.desktop.production.log](https://github.com/desktop/desktop/files/3765077/2019-10-24.desktop.production.log)

**Comment by steveward** [comment]
@electro-jbillings thanks for the report. It sounds like you are running into https://github.com/desktop/desktop/issues/4054.

You should be able to resolve this by running the following command from the Terminal:

`rm -r ~/Library/Application\ Support/GitHub\ Desktop/IndexedDB`

Let us know if that doesn't get things working.

**Comment by electro-jbillings** [comment]
Thanks, Steve. Deleting the IndexedDB worked similarly to deleting the whole directory, but saved me having to log back in. When I restarted GitHub Desktop, I was greeted with the post-sign-in welcome page. I re-added one of my local directories and then was hit with the super long "refreshing repository" spinner. I left the app running for an hour and it eventually completed. The GUI is still unusable for me because it's responding really slow; for example, clicking the dropdown for changing branches takes about a minute to respond. I am attaching my log from when I restarted the app after deleting the IndexedDB. I hope this helps.

[2019-10-24.desktop.production.log](https://github.com/desktop/desktop/files/3768974/2019-10-24.desktop.production.log)

**Comment by tierninho** [comment]
@electro-jbillings In the latest set of logs, I did spot some errors I haven't seen before. They look to be related to the DB as @steveward mentioned.

```
OpenFailedError: AbortError TimeoutError Transaction timed out due to inactivity.
```

@steveward is the Mac OS equivalent fix found in https://github.com/desktop/desktop/issues/4054#issuecomment-367567297 worth a shot?

```
close GitHub Desktop
remove all files under ~/Library/Application Support/GitHub Desktop/
restart GitHub Desktop
```

**Comment by steveward** [comment]
@electro-jbillings since you're still experiencing performance issues I think it'd be worth trying a fresh reset following the steps that @tierninho mentioned above. Let us know if that helps.

**Comment by tierninho** [comment]
@electro-jbillings  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
