### ISSUE TITLE
Need a way to add descriptive repo names

### ISSUE THREAD

**Issue by jesperordrup** [desktop/desktop#8526]
### Describe the feature or problem you’d like to solve

Repositories takes name after folder. This leads to confusion when multiple projects are placed in similar named folders as they appear with exactly same name in the repository list.

Consider at project for customer a with two projects, a frontend and a backend. Typically we organise the to projects below the project or customer folder in folders named exactly "frontend" and "backend". This makes it easy to reuse structure.

When adding the folders to Github desktop all frontend projects are named the same.

### Proposed solution

Github Desktop should try to make the repo name unique. If there are multiple repos with the same name, then it should include parent folder on with same name.

Frontend (customer a)
Frontend (customer b)

Also it should be possible to specify a name manually.

How will it benefit Desktop and its users?

This would lead to less confusion in the ui when trying to select the right repo

**Comment by billygriffin** [comment]
@jesperordrup Would you be open to showing a screenshot of what you're seeing? Assuming these are GitHub repos, they should be organized by owner in the repo list. I'm curious why the similarly named repos wouldn't be separated in that manner in your use case.

**Comment by jesperordrup** [comment]
@billygriffin These are not github repos. They are created locally (and connected to gitlab and others. I wasn't aware that there was any difference. 

![image](https://user-images.githubusercontent.com/3120151/67506284-1256a280-f68d-11e9-94ad-c22f184bffe6.png)

**Comment by billygriffin** [comment]
@jesperordrup Thanks for the quick response! Unfortunately this is a known limitation of the way things are organized currently. While we aim to provide a basic level of support for repos that are hosted on services other than GitHub, we optimize the experience for the experience with GitHub. I apologize that it's suboptimal for your use case here, but given that we're not planning to optimize this for non-GitHub providers, I'm going to close this issue.

**Comment by jesperordrup** [comment]
Thanks. It is named GitHub Desktop so I guess it makes sense in a way. I doubt that most only use GitHub repos.though.
