### ISSUE TITLE
Unity Gitignore ignore TextMeshPro making some Unity app not working as expected

### ISSUE THREAD

**Issue by Thomas-6freedom** [desktop/desktop#8527]
### Describe the feature or problem you’d like to solve

Hello. When you create a new repository, you can choose a .gitignore. When you choose the Unity one, this gitignore is not correct.
![2019-10-25 13_07_47-Window](https://user-images.githubusercontent.com/49686866/67566615-9316ac80-f728-11e9-89d5-cfede4ee0362.png)

This is the generated gitignore :

<pre># This .gitignore file should be placed at the root of your Unity project directory
#
# Get latest from https://github.com/github/gitignore/blob/master/Unity.gitignore
#
/[Ll]ibrary/
/[Tt]emp/
/[Oo]bj/
/[Bb]uild/
/[Bb]uilds/
/[Ll]ogs/
/[Mm]emoryCaptures/

# Never ignore Asset meta data
!/[Aa]ssets/**/*.meta

# Uncomment this line if you wish to ignore the asset store tools plugin
# /[Aa]ssets/AssetStoreTools*

# TextMesh Pro files
[Aa]ssets/TextMesh*Pro/

# Autogenerated Jetbrains Rider plugin
[Aa]ssets/Plugins/Editor/JetBrains*

# Visual Studio cache directory
.vs/

# Gradle cache directory
.gradle/

# Autogenerated VS/MD/Consulo solution and project files
ExportedObj/
.consulo/
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# Unity3D generated meta files
*.pidb.meta
*.pdb.meta
*.mdb.meta

# Unity3D generated file on crash reports
sysinfo.txt

# Builds
*.apk
*.unitypackage

# Crashlytics generated file
crashlytics-build.properties</pre>

When I look at the "[official](https://github.com/github/gitignore/blob/master/Unity.gitignore)" Unity gitignore, this is what it looks like :

<pre># This .gitignore file should be placed at the root of your Unity project directory
#
# Get latest from https://github.com/github/gitignore/blob/master/Unity.gitignore
#
/[Ll]ibrary/
/[Tt]emp/
/[Oo]bj/
/[Bb]uild/
/[Bb]uilds/
/[Ll]ogs/
/[Mm]emoryCaptures/

# Never ignore Asset meta data
!/[Aa]ssets/**/*.meta

# Uncomment this line if you wish to ignore the asset store tools plugin
# /[Aa]ssets/AssetStoreTools*

# Autogenerated Jetbrains Rider plugin
[Aa]ssets/Plugins/Editor/JetBrains*

# Visual Studio cache directory
.vs/

# Gradle cache directory
.gradle/

# Autogenerated VS/MD/Consulo solution and project files
ExportedObj/
.consulo/
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# Unity3D generated meta files
*.pidb.meta
*.pdb.meta
*.mdb.meta

# Unity3D generated file on crash reports
sysinfo.txt

# Builds
*.apk
*.unitypackage

# Crashlytics generated file
crashlytics-build.properties</pre>

The difference I remark is theses lines :

<pre># TextMesh Pro files
[Aa]ssets/TextMesh*Pro/</pre>

It makes Unity Cloud Build [not showing any text](https://forum.unity.com/threads/tmpro-text-is-not-visible-on-a-device.636085/#post-5105864) because TextMeshPro is not pushed.

### Proposed solution

I suggest to remove theses two lines because they are important. Or at least to reach the [TextMeshPro creator](https://forum.unity.com/members/stephan_b.1309638/) to speak with them.

**Comment by billygriffin** [comment]
Hi @Thomas-6freedom, thanks for the issue! We get the gitignore templates from https://github.com/github/gitignore, and it looks like the latest of that matches your expectation for Unity. The last time it was updated in Desktop seems it was [this PR](https://github.com/desktop/desktop/pull/7550) a few months ago. Would you be open to doing the same thing as was done in that PR and making a new PR to update the gitignore submodules? You'll need to be comfortable in the command line if so as submodules are super fun! 😆 Please let us know, and thank you!

**Comment by Thomas-6freedom** [comment]
Sorry I don't have the skills to do this myself :<

**Comment by VADS** [comment]
Here you go :)
