### ISSUE TITLE
how do you delete repositories?

### ISSUE THREAD

**Issue by Bullnose** [desktop/desktop#8528]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by Rexogamer** [comment]
You have to go to github.com and delete them there (ie here).

**Comment by steveward** [comment]
@Bullnose you can right-click on a repository in GitHub Desktop and select `Remove` to stop tracking it. You will also see the option to move the repository to the Recycle Bin/Trash, which will delete the repository from your local filesystem. If you need to delete the repository on GitHub you can [follow these instructions](https://help.github.com/en/github/administering-a-repository/deleting-a-repository).
