### ISSUE TITLE
how to sign in to my account using github destop

### ISSUE THREAD

**Issue by oparaocha** [desktop/desktop#8530]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@oparaocha Please fill out the template above so we have more details to assist you. Thanks.
