### ISSUE TITLE
How can I change the primary remote (not just the url)

### ISSUE THREAD

**Issue by wenh06** [desktop/desktop#8533]
### Describe the bug

I added a remote to a repository of mine, say xxx. I edited some file elsewhere (indeed overleaf) and pushed the changes to github. I wanted to pull the changes to my computer. But when I opened github desktop and only saw `Fetch xxx`. The `primary remote` was set xxx instead of origin, and in the settings, I can only modify the url of xxx with the name left unchanged, which is certainly not I want. I know I can do `fetch origin` in the git bash or git gui, but how can I do it in github desktop? I tried to search 'how to set primary (default) git remote', but I was not able to find anything, or any concept of 'primary (default) git remote'. Can anyone help me?

### Version & OS

version: 2.2.2
OS: win10

**Comment by niik** [comment]
Hey @wenh06, thanks for opening this!

The current behavior of GitHub Desktop is to always treat the `origin` remote as the primary remote. The only exception is if the current branch is tracking a different remote. You can list your branches and see which remote they're tracking using the `git branch -vv` command from your terminal.

See https://git-scm.com/docs/git-branch for more information on how to set which remote your branch should be tracking.

I hope that helps, please let me know if there's anything else we can do. I'm going to close this issue now as it doesn't appear to be a bug in Desktop but feel free to add more context and we can take another look or reopen.
