### ISSUE TITLE
Setting an Emoji as Name triggers error on blur

### ISSUE THREAD

**Issue by thewizardwand** [desktop/desktop#8534]
### Describe the bug
I set my Commit name to an Emoji
and then when i go to edit my email it crashes

### Version & OS
Tested on OS X and Windows

### Steps to reproduce the behavior

1. Go to Github commit settings
2. Click on name and put in an emoji 🧙 
3.  down to click on email 

### Expected behavior
edit the email 

### Actual behavior

Error: `value` must be a single character at Object.n [as fatalError] (file:///app/renderer.js:1:1753) at o (file:///app/renderer.js:16:594244) at Object.t.disallowed Characters (file:///app/renderer.js:16:594543) at C.disallowed Character ErrorMessage (file:///app/renderer.js:16:605654) at Object.C.onCommitterNameChanged [as onValueChanged] (file:///app/renderer.js:16:602110) at d.<anonymous> (file:///app/renderer.js:11:26012) at Re (file:///app/renderer.js:27:20247) at commitLifeCycles (file:///app/renderer.js:27:44342) at L (file:///app/renderer.js:27:55807) at A (file:///app/renderer.js:27:54616)
A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by niik** [comment]
Hey @thewizardwand, thanks for opening this! I've opened #8541 which should hopefully address this issue. As a workaround for now you can either manually set your name by modifying the .gitconfig file directly or by using `git config --global user.name "🦸‍♂️"` from a command line.

**Comment by thewizardwand** [comment]
> Hey! Can you tell us what version of Github Desktop you’re using? Go into Settings and select About Github Desktop.

Version 2.2.2

> Hey @thewizardwand, thanks for opening this! I've opened #8541 which should hopefully address this issue. As a workaround for now you can either manually set your name by modifying the .gitconfig file directly or by using `git config --global user.name "🦸‍♂️"` from a command line.

👍
