### ISSUE TITLE
Add ability to fetch all repos on-demand

### ISSUE THREAD

**Issue by nilswald** [desktop/desktop#8540]
### Describe the feature or problem you’d like to solve

After some time, repos in the list are marked if there are any remote or local changes. I am never quite sure when this is or if all updates are indicated. So I start Github Desktop, leave it running for as long as possible and I check the status from time to time.

### Proposed solution

It would be nice to have a menu command to check all repos for local changes and also fetch the remotes. There could also a be a checkbox in preferences to "[x] check on startup" and another one to explicitly set a time interval for checking ('[x] check every __ minutes') 

### Additional context

Sourcetree does it and I find it very convenient.

**Comment by tierninho** [comment]
@nilswald Thanks for the suggestion.

We already implement background fetching at set intervals for all repos and also every time you switch repos. Although, it sounds like you are interested in more of an on-demand feature that encompasses all repos at once. Do you have a screenshot of the feature in Sourcetree, I do not see it specifically? 

Here is a [good explanation](https://github.com/desktop/desktop/issues/4950#issuecomment-397694857) of our current background fetching process.

**Comment by nilswald** [comment]
Hi Tiernan,

thanks for getting back to me.

The use case is the following: I am maintaining several repos an would like to check for and review contributions of the collaborators. This is usually the main case when starting Github Desktop in the morning.

Best regards,

Nils




-- 

FMGARAGE

Typenoffene Datenbank-Werkstatt
Spezialist für FileMaker Pro®

Kastanienallee 21 · 10435 Berlin

Tel. 030 609 88 89-22
Fax 030 609 88 89-32
https://fmgarage.com

FMGarage e.K. 
Amtsgericht Charlottenburg 
HRA 48653 B

**Comment by tierninho** [comment]
Thanks for the clarity. At this time, we don't have any plans to make the background fetching intervals configurable or allow the user to fetch all repos at once.

Here is some additional context from another similar request:

> The interval with which we refresh data from the server varies depending on what type of host we're communicating with (GitHub.com, GitHub Enterprise, or a third-party host) and there are also mechanisms in place that allow us to back of clients in case we're encountering availability concerns.

> As a data point here, background refreshing of the currently selected repository when working with GitHub.com is normally done every five minutes.

With that being said, I am going to close this issue for now. Thanks for using Desktop.

**Comment by Tommuh** [comment]
Having exactly the same. I need to click 14+ repo's to check for changes.
This is not only in the morning but continuously during the day. 

I know a repo is changed and I'm waiting for it to come up with the download arrow by itself ... :sleeping:

**Comment by dret** [comment]
Same here. What makes things "worse" is that sometimes changes in the remote show up, and therefore I tend to trust the client that they eventually will. But they don't always show up, so there seems to be a problem with the remote fetching in the background. Being able to manually request a fetch of all repos would make the process simple and hopefully reliable.

**Comment by Lagoagest** [comment]
I agree with @Tommuh and @dret! I'm trying to follow a microservice architecture and the inability to fetch all my repos or simply see which repos have changes is becoming increasingly troublesome..

**Comment by brunoherrera** [comment]
bump, I need this too

**Comment by XxHyde840xX** [comment]
Yep, gonna pop in and say a refresh-all button would be a great quality of life addition to the desktop app.

**Comment by plebianmvi** [comment]
Same here.
4 repositories, and instead of 1 click every 2 hours, I have to type the 4 repositories to click. That’s around 16 clicks per day and as much time wasted. Instead of 4 clicks :(

**Comment by un0tec** [comment]
Same here. Please @tierninho

**Comment by brunoherrera** [comment]
> > The interval with which we refresh data from the server varies depending on what type of host we're communicating with (GitHub.com, GitHub Enterprise, or a third-party host) and there are also mechanisms in place that allow us to back of clients in case we're encountering availability concerns.
> 
> > As a data point here, background refreshing of the currently selected repository when working with GitHub.com is normally done every five minutes.
> 
> With that being said, I am going to close this issue for now. Thanks for using Desktop.

@tierninho 
whatever you implemented, is not good enough, take a look:

[https://www.youtube.com/watch?v=-qaRY5UZjRI](https://www.youtube.com/watch?v=-qaRY5UZjRI)

you can see, some are well past the 5 minutes background fetch you mentioned, and some only refresh once we click them, that's why we all are asking for a manual background fetch interval time setting or just a fetch all repositories button, current solution is either lacking in some aspects, badly coded, badly thought, or I don't know, is just not what we need, we are still forced to be clicking them manually to be sure, **CURRENT SOLUTION IT IS NOT RELIABLE**

**Comment by blackletum** [comment]
Beyond time for this to be implemented.

**Comment by Tenome** [comment]
Damn, so this was already requested and isn't a feature yet...

**Comment by brunoherrera** [comment]
> Damn, so this was already requested and isn't a feature yet...

they are complety ignoring it, I suspect the reason for some of the repositories way past the 5 minutes interval is an on purpose cooldown, **they think if they are fetching all at the same time some people will abuse to overload the servers** with hundreds of fetches, but the solution is simple, **just queue all the repositories and pull them automatically after a cooldown that has been triggered ends** and a message after the queue has been completed, **that way we can have piece of mind that indeed all the repositories have been fetched** and we don't need to check each manually just to be certain (and many times discover some didnt fetch at all even after an hour)
