### ISSUE TITLE
Add Local Repository -> Create Repository Instead -> Window Disappears

### ISSUE THREAD

**Issue by zelon88** [desktop/desktop#8544]
### Describe the bug

If you click "_File->New repository_" you are taken to the "_Create a new repository_" window. The cursor is already focused on the "_Name_" input field. 

If you use the mouse to highlight any of the text in the "_Name_" or "_Description_" fields then and then let go of the mouse button off the side of the window, GH Desktop will close the "_Create a new repository_" window without giving the user an opportunity to save their changes. It is incredibly frustrating. 

I think it has something to do with an "_onmouseup_" event. The issue seems to only happen when a mouse click is initiated on the window and ended off the window. I cannot confirm but it seems more sensitive when you get the window to open using "_Add local repository_" rather than "_New repository_."

### Version & OS

Windows 7 SP1
GH Desktop v2.2.1
GH Desktop v2.2.2

### Steps to reproduce the behavior

1. Open GH Desktop.
2. Create a new repository.
3. Type a name for your new repository.
4. Highlight the name that you typed in. Start clicking ON the input field.
5. End click OFF THE SIDE of the "_New repository_" window.
6. If you let go of the mouse button AFTER the cursor has left the "_New Repository_" window; the window will close unexpectedly.

### Expected behavior

The window should only close when the "_onclick_" and "_onmouseup_" events BOTH happen outside of the "_New repository_" window.

### Actual behavior

If any "_onmouseup_" events happen outside the "_New repository_" window while it is open; it will close unexpectedly.

### Screenshots

N/A

### Logs

The following logs seem to correspond to the unexpected behaviour...
_2019-10-28T18:11:51.829Z - info: [ui] Current tutorial step is NotApplicable_
_2019-10-28T18:13:54.943Z - info: [ui] Current tutorial step is NotApplicable_
_2019-10-28T18:15:37.716Z - info: [ui] Current tutorial step is NotApplicable_
_2019-10-28T18:16:28.472Z - info: [ui] Current tutorial step is NotApplicable_
_2019-10-28T18:16:34.525Z - info: [ui] Current tutorial step is NotApplicable_
_2019-10-28T18:16:45.376Z - info: [ui] Current tutorial step is NotApplicable_
_2019-10-28T18:16:55.024Z - info: [ui] Current tutorial step is NotApplicable_
_2019-10-28T18:16:59.300Z - info: [ui] Current tutorial step is NotApplicable_

**Comment by tierninho** [comment]
@zelon88 Closing this issues as we are already tracking it over in https://github.com/desktop/desktop/issues/8276. Please follow along there and thank you for filing, regardless.

**Comment by niik** [comment]
I'm gonna reopen this because I think it's referring to a slightly different (though likely related) problem than #8276.

This PR is about the fact that a dialog shouldn't be dismissed unless the user clicks (i.e. presses down *and* up on their pointer device) _over the dialog backdrop_. The way it is now it's possible to press down on the mouse over the dialog but release it outside (over the backdrop) and still dismiss the dialog.

Me and @billygriffin talked about this and both agreed that it's worth addressing this separately, I'll be opening a PR momentarily to address this.
