### ISSUE TITLE
Automatically fetch origin on GitHub Desktop

### ISSUE THREAD

**Issue by firehacker12** [desktop/desktop#8545]
Whenever a contributor to my projects commits an action to a branch, I have to manually fetch the origin on GitHub Desktop and agree to do this. I trust my contributor enough to directly make saves to my computer but he lives far away from me and depends on me to make these changes published on my local storage.

It will make people not have to worry about fetching origin and the contributors will see their changes much faster.

**Comment by tierninho** [comment]
@firehacker12 Thanks for the suggestion. We already implement background fetching at set intervals and also every time you switch repos.

What action happened that you were you expecting a fetch to occur? Any additional info like logs and your specific OS could be useful.

Here is a [good explanation](https://github.com/desktop/desktop/issues/4950#issuecomment-397694857) of our background fetching process.

**Comment by firehacker12** [comment]
@tierninho I was hoping for a more often check. Such as every minute or so. Thank you for responding though!

**Comment by tierninho** [comment]
We will consider more frequent intervals on the next iteration of this area. Thanks for using Desktop!

**Comment by ustk** [comment]
Hi, and add an option to disable auto-fetch, please
Auto-pull is a good thing, but auto-fetch can lead to a hard time in some situations...

**Comment by Rexogamer** [comment]
@ustk sorry for the late response but there’s an issue for that in #1128

**Comment by Mushe94** [comment]
> We will consider more frequent intervals on the next iteration of this area. Thanks for using Desktop!


Since it's been over 3 years, how's this coming along? It would be great to have an option in the settings menu to select the time of the auto-fetch.

**Comment by K0ST4S** [comment]
Not only auto-fetch but also a OS-level notification that a pull is available would be awesome!

**Comment by arya-coding** [comment]
Is this feature still being considered ? It would be nice to have it, it's useful in some cases

**Comment by stom66** [comment]
Auto-fetch does not appear to be working. I see no option to configure the interval in the settings. Several times the application has been running for hours and failed to notify me of changes to the origin.

**Comment by steveward** [comment]
@stom66 you can make sure background fetching is enabled under Options -> Advanced -> Background updates. The currently selected repository should update, but there isn't a way to set an interval. You can also manually fetch from the `Repository` menu if  fetch isn't available in the action bar.

One thing I will note however is that we won't fetch repositories in the background unless the application is focused, which was implemented to ensure we weren't utilizing system resources.

**Comment by stom66** [comment]
@steveward There does not seem to be a way to toggle the feature. I just see a title "Background updates": 
![GitHubDesktop_pxWuXQTHwE](https://github.com/desktop/desktop/assets/29757739/6c5e162a-71f3-4a2c-8c74-5f82d10f015d)

A way to enable fetching in the background would be incredibly useful. I would be quite willing to lose the minimal resources required to periodically check for an update when I'm actively working on a project with others and have the application running. Being able to configure this interval would also be quite useful.

**Comment by Karim-Data000** [comment]
I just found out that VS code was responsible for the background automatic fetch and pull. i disabled this in the VS code settings.
it worked. Besides that, you can also change the period of automatic fetch also in VS code.
![image](https://github.com/desktop/desktop/assets/134317581/cfe05ba7-a388-4ade-bc73-55b708b6b6cc)

**Comment by stom66** [comment]
> I just found out that VS code was responsible for the background automatic fetch and pull. i disabled this in the VS code settings. it worked. Besides that, you can also change the period of automatic fetch also in VS code. ![image](https://private-user-images.githubusercontent.com/134317581/305144239-cfe05ba7-a388-4ade-bc73-55b708b6b6cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTQ2NzUsIm5iZiI6MTcwODAxNDM3NSwicGF0aCI6Ii8xMzQzMTc1ODEvMzA1MTQ0MjM5LWNmZTA1YmE3LWEzODgtNGFkZS1iYzczLTU1YjcwOGI2YjZjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQxNjI2MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWU1NWFkMWI4MDViZDNmYzY0Mjc0NjgwOWFhMDdhYWQ5ZTUxNzYzZWNjMDEyN2U5MWIzZWI4ODg4MWEyYTllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JR2XlwQ3g_ikCLDHqCqowA8SOq46A0OX6sAp_Jw_bMA)

Some of our team do not use VSCode (artists, modellers, etc). 

While I appreciate there are other programs that do support automatic pulling (and allow you to configure the frequency) it would be preferable to have this functionality in the software they are already using, especially as it's particularly appropriate for GitHub Desktop to support this feature.

**Comment by blackletum** [comment]
We're coming up on half a decade since the initial request and still nothing. This would substantially help my github desktop experience.

**Comment by ezrazazeldev** [comment]
Adding to the bump-train, this is a feature that I would have expected to exist years ago, let alone right now. Please!!!

**Comment by dlodaya** [comment]
Auto fetch feature will be incredibly useful. It would be great if this can be implemented. Thanks!

**Comment by adstr123** [comment]
This should be re-opened, it's still a valid request
