### ISSUE TITLE
[Fork] "Create pull request" is still a suggestion even after I've created a PR for the current branch on my fork

### ISSUE THREAD

**Issue by kuychaco** [desktop/desktop#8549]
_Extracted from https://github.com/desktop/desktop/issues/8509 (Problem 2) for tracking work on this particular issue_

### Problem: "Create pull request" is still a suggestion even after I've created a pull request for the current branch on my fork

After you create a PR from a branch of your fork that's targeting the upstream repo, the "Create pull request" suggestion is still displayed. This is very confusing because you already have a PR.

Example: I'm in billygriffin/desktop (a fork of desktop/desktop) on my branch new-work, and I make some commits and create a pull request targeting the development branch of desktop/desktop. In the app, I'm still shown the "Create pull request" suggested next step even though I've already created one.

**Comment by outofambit** [comment]
this was closed erroneously!
