### ISSUE TITLE
Allow the user to set fetch intervals, or set it to every half-hour 

### ISSUE THREAD

**Issue by Rexogamer** [desktop/desktop#8551]
We currently fetch changes every hour, however there seems to be confusion about this. For example, in #8545 @firehacker12 would rather have it every minute or so. However, there might be users who prefer not to fetch too much, so maybe just half the interval? If we decide to do the former, we could set the minimum at either 60 or 30 mins.

(For the record, I would like to fetch every 5 mins.)

**Comment by niik** [comment]
Hi @Rexogamer, thanks for opening this. We don't have any plans to make the background fetching intervals configurable. We're always interested to hear feedback such as the one provided in #8545 but we don't believe that the best solution is to make the interval configurable.

The interval with which we refresh data from the server varies depending on what type of host we're communicating with (GitHub.com, GitHub Enterprise, or a third-party host) and there are also mechanisms in place that allow us to back of clients in case we're encountering availability concerns. 

> (For the record, I would like to fetch every 5 mins.)

As a data point here, background refreshing of the currently selected repository when working with GitHub.com is normally done every five minutes.

**Comment by firehacker12** [comment]
You should make it settable in the settings
