### ISSUE TITLE
Meta: some form of communication about Desktop (eg a Discord/Slack server)

### ISSUE THREAD

**Issue by Rexogamer** [desktop/desktop#8553]
There are minor things that do not deserve an issue (eg the github sentry issue link in the 2.3 project board is a 404, although if it’s a private repo that makes sense), plus stuff like simple support, general discussion about using/developing Desktop, and IMO getting consensus on something before creating an issue that lead me to believe that some other form of communication (a Discord/Slack server, a making list etc) could be very useful.

**Comment by tierninho** [comment]
@Rexogamer Thanks for the suggestion. Some issues lead to 404 as they are private as you mentioned. Other topics no matter how trivial may end up in issues and we are okay with this as it creates a reference point and source of truth, and helps everyone with the asynchronous communication. Certain topics are discussed behind closed doors as part of the ongoing discussions needed to move Desktop forward. We will continue to evaluate each issue and discussion as they arise, so I will closing this issue for now. Cheers.
