### ISSUE TITLE
UX: Working with multiple equal named repositories

### ISSUE THREAD

**Issue by staabm** [desktop/desktop#8554]
### Describe the feature or problem you’d like to solve

in my daily business I am working on severall applications. some of these applications use components/projects hosted on github. these get bundled e.g. via composer, npm or similar.

we build the projects using a 'prefer-source' option, so the package managers checkout the actual sources of the components instead of just downloading distribution artifacts.

therefore we have some projects which contain the same external component which all link to the same upstream repo on github

Example

- app1
  - vendor/componentA
  - vendor/componentB
  - vendor/componentC

- app2
  - vendor/componentA
  - vendor/componentE
  - vendor/componentF

- app3
  - vendor/componentA
  - vendor/componentB
  - vendor/componentF

when adding all those components into gihtub desktop get failry fast into a situation where you see repos with the same name (but different file path).

![grafik](https://user-images.githubusercontent.com/120441/67857469-30058b00-fb17-11e9-82eb-e6242b026fc2.png)

its hard to decide which is the correct repo in my current context, because I can only see the actual file paths when hovering over the menu entries.

![grafik](https://user-images.githubusercontent.com/120441/67857626-938fb880-fb17-11e9-856d-b8346802136a.png)

### Proposed solution

when repo names are not unique it would be great to get a hint, e.g. the filepath, to make them easier to distinguish

**Comment by niik** [comment]
Hi @staabm, thanks for opening this.

Right now our support for submodules is limited and requires a little bit of extra effort to work with in the application. We’re slowly chipping away at features to make submodules easier to work with but submodules are not part of our current roadmap. I've added this issue to #7523 to have a central place to keep track of the surface area of submodules more broadly, just wanted to set expectations that it's not something we intend to address in the near future.

I'm going to fold this issue into https://github.com/desktop/desktop/issues/1803 which I believe describes the same problem.

**Comment by niik** [comment]
Hi @staabm, thanks for getting back to us with more information. Could you elaborate a bit on your workflow, I'm afraid I don't quite understand your setup here.

**Comment by staabm** [comment]
We use the php package manager composer to handle the package managment. 

When including packages with it which you have commit access to (own yourself) the composer will git clone these packages in-place.

So you actually get a vendor folder containing one git-repo per external for which you have commit access. 
Overall you have your projects main repo which contains a vendor folder in which some more git repos reside.
Afer you work on several projects which depend on the same externals you effectively get several equal named repositories.

Can you follow me?
