### ISSUE TITLE
Lacking variety in external editors

### ISSUE THREAD

**Issue by teddue** [desktop/desktop#8558]
I would like the option to add Notepad++ or any other editor as "External Editor" in Github Desktop

**Comment by billygriffin** [comment]
Thanks for the issue @teddue! We have documentation here on how to make sure your preferred editor will work with Desktop, and how to add it. https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md 

Please feel free to open an issue for a specific editor if you'd like to contribute and add the editor to the ones supported in the app!
