### ISSUE TITLE
Feature request: manually-name the repository in github desktop instead of using repository's original name

### ISSUE THREAD

**Issue by long-nguyenxuan** [desktop/desktop#8559]
### Describe the bug

Github desktop should have option to let user name the repository in local instead of using repository's original name.

### Version & OS

Github Desktop 2.2.2 (just updated) 
Windows 10 

### Steps to reproduce the behavior

N/A 

### Expected behavior

Github desktop should have option for user to name the repository folder (as we could name the folder ownselft using `git clone http://github.com/username/repo-name local-folder-name` 

### Actual behavior
Github desktop is using repo-name as-is. 

### Screenshots
as in screenshot, I've clone folder to local-name but it still got showed in github desktop by it's original repository name 
![image](https://user-images.githubusercontent.com/46129500/67915065-7bc23e00-fbc4-11e9-9b74-a2aebe1e3ad6.png)

### Logs
N/A 
### Additional context
n/a

**Comment by billygriffin** [comment]
Hi @long-nguyenxuan, thanks for the issue! Is there a reason you’re using version 1.6.5? We’re currently on 2.2.2. If you update to the latest version, the way repos are organized should be different. Not exactly what you asked for but hopefully an improvement over what you’re seeing today. Please let us know!

**Comment by long-nguyenxuan** [comment]
@billygriffin  thanks for quick reply, 
I've forgot to update :D I've update it to 2.2.2 but there is no option to rename the repository show in Github Desktop too. 
I think It could be better if Github Desktop show repositories using local folder name instead of original repository name.

**Comment by niik** [comment]
Hi @long-nguyenxuan, thanks for opening this, I believe this issue is the same as the one described in https://github.com/desktop/desktop/issues/7856 (please correct me if I'm wrong), so I'm going to close this issue in favor of that!
