### ISSUE TITLE
Slow Desktop Response

### ISSUE THREAD

**Issue by Lagicrus** [desktop/desktop#8562]
### Describe the bug

Actions take multiple seconds to execute, UI can become non-responsive, minimise button, for example, can decide not to work, clicking actions can take multiple seconds just to display hover over colour schemes or actually do the action.

### Version & OS

Windows 10 Pro version 1903, OS Build 18362.418
Github Desktop 2.2.2

### Steps to reproduce the behavior

1. Attempt to do any action
2. Wait
3. Action completes

### Expected behavior

Fast responsive action when I click buttons

### Actual behavior

Slow

### Logs

https://starb.in/fxKkcp.pl

**Comment by tierninho** [comment]
@Lagicrus Thanks for filing this. It is hard to tell exactly what is causing the slowness, but I did notice in the logs that there were multiple attempts to access a missing repo:

```
progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/Portsmouth-Computing/portsmouth-computing.github.io.git/' not found
(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2019-10-30T19:14:36.145Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
Error: Not Found
```

Perhaps remove that repo, and restart Desktop? Let us know how it goes.

**Comment by outofambit** [comment]
Hi @Lagicrus since we haven't heard back from you I'm going to close this issue, but please comment if you have further questions/issues. Thanks!

**Comment by Lagicrus** [comment]
Hey @tierninho . I tried that one and at first it seemed to work but then I didn't have any more work to do via Git which meant I ran out of testing data so I didn't reply until I had been able to test it more.

However, I was able to test again today and I ended up having the same slow response even after removing the repo as you suggested (and restarting a week ago).
These are the logs from today https://starb.in/YDlBqQ.pl, and I also checked in DevTools and I saw the same "X handler took 2000ms"

**Comment by tierninho** [comment]
Thanks for the update @Lagicrus Looked at the latest logs but didn't see much to go on.  The only thing I can suggest to try to pinpoint the action(s) that take more time than normal and report back. Due to the customization of every individual computer, it is very challenging to triage these types of issues.

**Comment by Lagicrus** [comment]
@tierninho yeah that makes sense.
What would you recommend to do to check for actions? Like I can say that the onhover colour change sometimes can take a while to work, or when I click it decides to take a while and so on.
I assume that the logs where it takes >6s are considered normal?

**Comment by tierninho** [comment]
> I assume that the logs where it takes >6s are considered normal?

That sounds about right. Anything over 20s is probably a clue something is wrong unless you are dealing with large amounts of data or if other CPU-expensive apps are running in the background. 

We have yet to pinpoint the root cause of any slowness issues as they are rare and the process of recreating the issue is very challenging. 

Any data helps, so feel free to share anything specific you run across.

**Comment by Lagicrus** [comment]
Hm ok.
One idea could be to use the inbuild Dev Tools, Performance option as that does a greater breakdown of what's going on in the background 
[GitHubPerformanceProfileLagicrus.zip](https://github.com/desktop/desktop/files/3861261/GitHubPerformanceProfileLagicrus.zip)
As a test try looking through this and see if it makes any sense. For context (to me) I was trying to do thus
Whilst GH was fetching master in prep to push
Clicking onto two separate files
Then when the second loaded clicking into the summary bar

From here you can see the functions and their time, along with the Events that take "too long"
