### ISSUE TITLE
Resolve conflicts: 'Open with default program' is erroneously using Xcode

### ISSUE THREAD

**Issue by williamsandonz** [desktop/desktop#8565]
### Describe the bug

When clicking on 'Open with default program' in the resolve conflicts modal, it opens Xcode instead of the default git merge tool.

### Version & OS

- Github Desktop: Version 2.2.2
- Mac OS: 10.15

### Steps to reproduce the behavior

Set Beyond Compare as default merge tool in terminal (or your preferred tool)
(The instructions are [here](https://www.scootersoftware.com/support.php?zz=kb_vcs_osx))
```
git config --global diff.tool bc3
git config --global merge.tool bc3
git config --global mergetool.bc3.trustExitCode true
```
Check that it was successfully set as your default merge tool for git by opening a terminal and:

`git mergetool foo.bar`

### Expected behavior

I expected Beyond compare to be opened to handle the merge.

### Actual behavior

Xcode was opened

### Logs
_These logs represent the timeline from opening the application to clicking on 'Open with default program'. Doesn't look like any exceptions were logged._

2019-11-01T17:46:02.657Z - info: [ui] [AppStore] loading 2 repositories from store
2019-11-01T17:46:03.328Z - info: [ui] Current tutorial step is NotApplicable
2019-11-01T17:46:03.447Z - info: [ui] Current tutorial step is NotApplicable
2019-11-01T17:46:03.590Z - info: [ui] launching: 2.2.2 (Mac OS 10.15.0)
2019-11-01T17:46:03.590Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper.app/Contents/MacOS/GitHub Desktop Helper'
2019-11-01T17:46:12.010Z - info: [ui] Current tutorial step is NotApplicable

**Comment by tierninho** [comment]
@williamsandonz I believe "Open with default program" is a setting relating to the default application set in OSX and not based on your gitconfig. See here: https://github.com/desktop/desktop/blob/249c06d51332a7254de848e1c77a60e1ae52d587/app/src/ui/lib/context-menu.ts#L18

Can a Desktop developer confirm this is correct?

You _can_ set your Editor under Preferences > Advanced, but this is the only config available from the application.

**Comment by steveward** [comment]
@williamsandonz what @tierninho said is correct -- changing the default application for a specific file type on macOS will allow GitHub Desktop to launch that application via the `Open with default program` option. At this time launching into a merge tool is not supported, but we are tracking feedback for that in https://github.com/desktop/desktop/issues/1765. I'm going to close this out.

**Comment by ivan006** [comment]
WIndows:
File > Options > Integrations > External Editor
