### ISSUE TITLE
Repository Names (when cloning repos)

### ISSUE THREAD

**Issue by santaimpersonator** [desktop/desktop#8566]
### Describe the bug

I'm having issues after renaming a repository and then creating a new repository under the original name of the aforementioned repository. When I try to clone the repos, they both direct to the first repo. Both have repositories save under separate folder names but have the same files. On the GitHub desktop, they show up as the same repo (probably because the git files are the same).

1st Repository: https://github.com/sparkfun/Qwiic_PCA9685_Py
* Originally named "PiServoHat_Py"
* Renamed to "Qwiic_PCA9685_Py"

2nd Repository: https://github.com/sparkfun/PiServoHat_Py
* Created after 1st repository was renamed, using the original name

**Issue:** I can't clone the 2nd repository... the GitHub Desktop always downloads the 1st repository instead (into a folder using the 2nd repository name; both repositories show up under the same name on GitHub Desktop).

I was able to eventually sort of work around this issue by creating a new repository from the GitHub desktop instead (files in the folder are different). However, both repositories still show up under the same name on the GitHub Desktop (see picture).

I checked the `.git` folder files, but couldn't find anything to associate the same repository name.

### Version & OS

Version 2.2.2 (latest version as of 11/1/19)

### Steps to reproduce the behavior

1. Rename 1st Repository: https://github.com/sparkfun/Qwiic_PCA9685_Py (_on website_)
  * Originally named "PiServoHat_Py"
  * Renamed to "Qwiic_PCA9685_Py"
2. Create 2nd Repository: https://github.com/sparkfun/PiServoHat_Py (_on website_)
  * Use the original name of 1st Repository: "PiServoHat_Py"
3. Clone Repositories on GitHub Desktop

Workaround:
1. Delete 2nd Repository: https://github.com/sparkfun/PiServoHat_Py (_on website_)
2. Create 2nd Repository (again), but using GitHub Desktop

### Expected behavior

Clone repositories on GitHub Desktop under proper names with correct files.

### Actual behavior

Cloned same repository/repository shows up under same name on GitHub Desktop.

### Screenshots

File Names
![GitHub Folder and Repo Name Issue](https://user-images.githubusercontent.com/36016723/68047638-7dfbc980-fca4-11e9-8ab0-47c3f27b64ba.JPG)

Different Files:
![Different Files](https://user-images.githubusercontent.com/36016723/68047882-f8c4e480-fca4-11e9-9053-dbeb33140713.JPG)

(In the original issue, both folders had the same files... of the 1st repository.)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
[2019-11-01.desktop.production.log](https://github.com/desktop/desktop/files/3799166/2019-11-01.desktop.production.log)

### Additional context

See above on the workaround.

**Comment by steveward** [comment]
Thanks for the report @santaimpersonator. This looks similar to https://github.com/desktop/desktop/issues/6927 -- clearing out `%AppData%\GitHub Desktop` should fix this issue. 

I'm going to look into this further to see if I can reproduce this issue since we have had a few reports of this in the past.

**Comment by tierninho** [comment]
I could not reproduce this, although this issue as come up a few times and I have run across it myself. 

In Repository menu > Repository Settings > Remote tab, are the remotes different? They should match the current repo names.

**Comment by santaimpersonator** [comment]
Here are the Settings:
![Setting1](https://user-images.githubusercontent.com/36016723/68150580-3fad1700-fefd-11e9-92d6-931000b6d8e9.JPG)
![Setting2](https://user-images.githubusercontent.com/36016723/68150581-40de4400-fefd-11e9-8d7d-937c3af4408c.JPG)

I am testing the workaround. I just deleted the `GitHubDesktop` folder in the `AppData` folder. Just reinstalled the GitHub Desktop; however, currently I am running into an issue cloning the repos now:
![Cannot Clone Repo](https://user-images.githubusercontent.com/36016723/68150874-d679d380-fefd-11e9-84cc-7db068a650da.JPG)

**Comment by santaimpersonator** [comment]
I figured out the issue, I had to also delete the `GitHub` where the repos get saved to.

That workaround worked... now the repositories are named appropriately.

**Comment by outofambit** [comment]
Hi @santaimpersonator, this looks to be exactly the bug outlined in https://github.com/desktop/desktop/issues/7455. Please follow along there for future updates. Apologies for the trouble!
