### ISSUE TITLE
Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by yiloo** [desktop/desktop#8567]
Hey, All!

I am using the MacOS 10.15.1 Catalina. And when I tried to open the application that I had downloaded from https://desktop.github.com, I got this window popped up. What could possibly cause this issue? How do I resolve this?

<img width="422" alt="Screen Shot 2019-11-01 at 5 27 47 PM" src="https://user-images.githubusercontent.com/5194080/68060096-f1193600-fccc-11e9-8207-a333458af190.png">

**Comment by tierninho** [comment]
@yiloo please try again but this time open your computers System Preferences > Security and Privacy, then click Open Anyway.

**Comment by yiloo** [comment]
> @yiloo please try again but this time open your computers `🍎 > System Preferences > Security and Privacy`, then click `Open Anyway`.
> 
> ![67253340-d2848680-f412-11e9-847e-c09c150c7b71](https://user-images.githubusercontent.com/14828183/68062352-f024dc00-fcad-11e9-984e-83767b88f242.png)

oh, right! Since when Apple change the message to "malicious software check". the message used to be "can't open because it is from an unidentified developer" Thank you so much!

**Comment by outofambit** [comment]
This is also an instance of #8506.
