### ISSUE TITLE
Add the possibility to squash commits together

### ISSUE THREAD

**Issue by MCrafterzz** [desktop/desktop#8569]
### Describe the feature or problem you’d like to solve

GitHub desktop makes git much easier to use and makes stuff like pushing, pulling and branch creation trivial. But on feature I really miss from git is squashing commits together (git rebase -I HEAD~2) which is essential in some cases, for example contributing to the godot game engine.

### Proposed solution

A new feature which would make the program more powerful and useful

**Comment by steveward** [comment]
Thanks for the feedback @MCrafterzz. This is a feature that has been requested previously in https://github.com/desktop/desktop/issues/2507, so I am going to close this issue out and add your feedback there.
