### ISSUE TITLE
Unrecoverable error

### ISSUE THREAD

**Issue by joostholslag** [desktop/desktop#8575]
### Describe the bug

After upgrading to macOS Catalina Github is constantly unable to launch. It gives an error (see below) quits and keeps retrying. (force) quit doesn't stop it from looping, only logout does.

### Version & OS
latest version, downloaded today as well a my previous installed version. (about GitHub Desktop is greyed out)

### Steps to reproduce the behavior

1. upgrade to Catalina 
2. open GitHub 

### Expected behavior

Launch GitHub Desktop main window

### Actual behavior

see description

### Screenshots

![Screenshot 2019-11-03 at 18 34 06](https://user-images.githubusercontent.com/13568972/68089374-869cfd00-fe68-11e9-866b-6858aed58c38.png)

### Logs

'Error: spawn /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

Version: 2.2.2
OS: Mac OS 10.15.1'

(logs also greyed out)

**Comment by outofambit** [comment]
hi @joostholslag, i'm sorry you're having this issue! we're tracking this at #8506 (and there's an in-progress fix at #8555). hoping to have this resolved soon. in the meantime, if you control click on the app and select 'Open', that should get you around the issue.

**Comment by outofambit** [comment]
Hi again @joostholslag. Upon further reflection, this looks like a different issue. Can you confirm that your Desktop app is not in the Downloads folder? That can cause something like this.

Deleting the desktop app and reinstalling might also resolve this issue.

If that's not the problem, can you share a log file from desktop? They should be at `~/Library/Application Support/GitHub Desktop/logs`. Thank you!

**Comment by joostholslag** [comment]
I can confirm it’s not in the downloads folder. I did a reinstall by downloading the latest version from the website then move it to the applications folder and click replace. After reinstall the only thing that’s changed is that now the error report is shown. I will share my logs shortly.

**Comment by joostholslag** [comment]
[2019-11-03.desktop.production.log](https://github.com/desktop/desktop/files/3807620/2019-11-03.desktop.production.log)

**Comment by joostholslag** [comment]
command line git also gives an error btw: 
$ git
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by outofambit** [comment]
@joostholslag You can fix that with the following command `xcode-select --install` (https://stackoverflow.com/questions/58280652/git-doesnt-work-on-macos-catalina-xcrun-error-invalid-active-developer-path). Let us know if you have any further issues!
