### ISSUE TITLE
如果有好几十个,好几百个文件提交的情况下,文件列表不方便

### ISSUE THREAD

**Issue by syxcools** [desktop/desktop#8578]
### 如果有好几十个,好几百个文件提交的情况下,文件列表不方便,是否可以修改成文件夹树的列表方式,更边防

>If there are dozens, hundreds of files submitted, the file list is inconvenient, can be modified into a list of folder trees, more border defense

**Comment by steveward** [comment]
Thanks for contributing @syxcools. It sounds like you may be interested in https://github.com/desktop/desktop/issues/6407, which is a feature request to be able to filter the `Changes` list. I'm going to close this issue and add your feedback to that thread.
