### ISSUE TITLE
Feature request: checkout to a specific commit

### ISSUE THREAD

**Issue by Diogo-Rossi** [desktop/desktop#8580]
### Proposed solution

Add to the commit's right click menu the option "checkout to this commit", which will run the command "`git checkout <commit SHA>`" creating a Detached HEAD on that commit.

### Additional context

It's a very basic and useful feature.
The software already recognizes the Detached HEAD, once the command is run, as shown in the screen shot bellow 
Maybe it's already on the software, but I couldn't find this feature.

![image](https://user-images.githubusercontent.com/57204023/68172408-2b493880-ff56-11e9-8496-4d969e329379.png)

Edit: also, when trying to create a new branch in this Detached commit, the software again recognizes that there is no branch checked out, and that the new branch will be based on the Detached commit, as shown bellow.

![image](https://user-images.githubusercontent.com/57204023/68172759-816aab80-ff57-11e9-8dd7-fc540cc455de.png)

I think this demonstrates that it will be easy to add this feature. It could be located right next to the option "revert to this commit" on the commit's right click menu, shown bellow

![image](https://user-images.githubusercontent.com/57204023/68172836-c1ca2980-ff57-11e9-8da9-f90233af3613.png)

**Comment by steveward** [comment]
@Diogo-Rossi thanks for the feedback! This request was previously captured in https://github.com/desktop/desktop/issues/5860. At this time we have not decided to implement a `git reset` option into GitHub Desktop. Please refer to @niik's response in https://github.com/desktop/desktop/issues/5860#issuecomment-428959691 for some further context around this decision.

Is there a specific workflow you have that requires using `git reset` often?

**Comment by Diogo-Rossi** [comment]
@steveward thanks for the answer.

Actually, I'm not requiring the `git reset` command.

I was talking about the `git checkout <commitSHA>`, where `<comitSHA>` is the hash code of the commit.

As showw above, GitHub Desktop already recognizes Detached HEAD and wait for a new branch.
But the `git checkout` can't be done to a commit, as long as I know.
May you reopen the issue?

**Comment by Jayemby** [comment]
what became of this post?

In SourceTree, you can just double-click a commit. In GitKracken, you can right-click and choose _checkout this commit_. Did this ever get added to GitHub Desktop?

**Comment by diogo-rossi** [comment]
@Jayemby, I don't know. I end up stopping using Github Desktop, I couldn't wait for this. Even the some extensions of VS Code let you do that ([here](https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph) and [here](https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory)) . It is a very basic feature

**Comment by steveward** [comment]
@Diogo-Rossi @Jayemby you can checkout a previous commit on a new branch by right-clicking on it and selecting `Create Branch from Commit`.

**Comment by ghost** [comment]
@steveward it is not the same at all we do not want a new branch just to checkout in a specific commit. I moved couple of days before in GitHub Desktop from Source Tree because it was easier to set up `ssh` keys but I think I am going back on Source Tree `git checkout` is a feature that I use multiple times per day

**Comment by KaletheQuick** [comment]
Yeah, this would be super helpful. Is there something making it difficult to implement?

**Comment by safetycar** [comment]
I was wondering why this was closed. Anyway I've found a similar issue that luckily is still open #10068

**Comment by diogo-rossi** [comment]
Seems to have been implemented in PR #16120, after all.

**Comment by diogo-rossi** [comment]
I also found other issues that also requested this, in the past:

- #10068
- #5860
- #14053
- #10858

Unfortunately, I started to learn git in 2019, and this was only available now in 2023.
