### ISSUE TITLE
Free

### ISSUE THREAD

**Issue by stoffe389** [desktop/desktop#8581]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by stoffe389** [comment]
> ### Describe the bug
> A clear and concise description of what the bug is.
> 
> ### Version & OS
> Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.
> 
> ### Steps to reproduce the behavior
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> ### Expected behavior
> A clear and concise description of what you expected to happen.
> 
> ### Actual behavior
> A clear and concise description of what actually happened.
> 
> ### Screenshots
> Add screenshots to help explain your problem, if applicable.
> 
> ### Logs
> Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
> 
> ### Additional context
> Add any other context about the problem here.

**Comment by steveward** [comment]
Thanks for reaching out!

Would you mind filling out the rest of the issue template so that we can better understand what is causing the problem you are experiencing? Without that information it will be difficult to help you further.
