### ISSUE TITLE
github page data is not being updated 

### ISSUE THREAD

**Issue by HemanthRajHemu** [desktop/desktop#8582]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by HemanthRajHemu** [comment]
unable to get latest github repo site page despite of updated via desktop & github webpage

**Comment by billygriffin** [comment]
Hi @HemanthRajHemu, sorry you're having problems! Would you mind filling out a [bug report](https://github.com/desktop/desktop/issues/new?template=bug_report.md) issue instead and filling out the template. We don't have enough information from this issue to properly diagnose the problem and help you through it. Thanks!

**Comment by HemanthRajHemu** [comment]
Sir the Complete REPOSITORY IS not showing on the Github page

My Repo https://github.com/HemanthRajHemu/FutureVisionBIE

My Site : https://hemanthrajhemu.github.io/FutureVisionBIE/

Even After Changing from Master Branch -> None & Again to Master Branch. The Website Went Blank. 404 Error.

Please Help me....

The updating Data on to my repo is not reflected on the WEBPage
