### ISSUE TITLE
Cannot clone repository that has been moved

### ISSUE THREAD

**Issue by ricky-ratis** [desktop/desktop#8583]
### Describe the bug

We had a repo that was called "xy-api". We renamed it to "xy-api_legacy" and created another repo called "xy-api". Now Github desktop wont allow me to clone the new xy-api. Instead it clones the "xy-api_legacy" again.

### Version & OS

Version 2.2.2 Windows 10

### Steps to reproduce the behavior

as seen in description

### Expected behavior

Clone the new repository instead of the renamed one.

### Actual behavior

The renamed repo is cloned.

**Comment by steveward** [comment]
Thanks for the report @ricky-ratis. It sounds like you are running into https://github.com/desktop/desktop/issues/8566 -- I'm looking into this issue but so far have been unsuccessful in directly reproducing it. I'm going to close this issue out in favor of #8566 to help keep our open issues manageable. Please follow along there for updates.

 Clearing out the `%AppData%\GitHub Desktop` and adding your repositories again should fix this issue.
