### ISSUE TITLE
why does the command git clone not work

### ISSUE THREAD

**Issue by SiXwXah** [desktop/desktop#8585]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by SiXwXah** [comment]
when I go to enter git clone the command doesn't work stressfukl

**Comment by billygriffin** [comment]
Hi @SiXwXah, this is the repository for GitHub Desktop (https://desktop.github.com). The command `git clone` is usually entered in the command line. If you have a question about GitHub Desktop specifically, we're happy to take a look at it, but we can't help with issues on the command line.
