### ISSUE TITLE
Deleted repository shown in Your Repositories list on Lets Get Started! screen

### ISSUE THREAD

**Issue by JimJamJamie** [desktop/desktop#8586]
### Describe the bug

A deleted repostitory is still shown in github desktop, even though it is not visible on github.com and after restarting the program.

### Version & OS
Github Desktop Version 2.2.2

Windows 10 Pro x64 Version 1903 (OS Build 18362.449)

### Steps to reproduce the behavior

1. Delete repository on github.com
2. Have no repositories cloned locally
3. Open Github Desktop

### Expected behavior

Unable to see deleted repository in Your Repositories list

### Actual behavior

Able to see deleted repository in Your Repositories list

### Logs
Private information has been \<redacted\>.

```
stderr:
Cloning into '<my github folder>'...
remote: Repository not found.
fatal: repository '<my repo>' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2019-11-05T18:21:51.519Z - info: [ui] storing generic credentials for 'github.com' and '<user>'
2019-11-05T18:21:51.528Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: <my_repo>.git - <user> (has token)
2019-11-05T18:21:53.223Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- <my_repo>.git <my github folder> (took 1.601s)
2019-11-05T18:21:53.224Z - error: [ui] `git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- <my_repo>.git <my github folder>` exited with an unexpected code: 128.
stderr:
Cloning into '<my github folder>'...
remote: Repository not found.
fatal: repository '<my_repo>.git' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)

```

### Additional context

I tried cloning the supposedly deleted repo for scientific discovery reasons, the error is shown in the Log.

**Comment by JimJamJamie** [comment]
Update to this: I signed out of and signed back into Github Desktop (from Options>Accounts) and the issue still persists.

**Comment by steveward** [comment]
@JimJamJamie it sounds like you are running into https://github.com/desktop/desktop/issues/6867.

What happens if you click the `Refresh` spinner next to the `Filer` text box? Does the repository disappear?

**Comment by JimJamJamie** [comment]
My apologies, I forgot to mention this in the initial report. Clicking refresh does not alter the list of repositories shown, and the deleted one is still present. I've clicked refresh multiple times over the course of the last few hours to confirm.

**Comment by JimJamJamie** [comment]
Update: Today I opened GitHub Desktop and the deleted repository no longer appears. Some sort of caching issue?

**Comment by outofambit** [comment]
Hi @JimJamJamie thanks for following up on this. It does sound like some sort of caching issue. If you experience this again, I'd be curious to hear what happens if you select the deleted but still listed repository from the repository tab.

Sounds like its resolved for now though, so I'm going to close this issue. Please comment if you have any more questions!

**Comment by sameo336** [comment]
this issue still persists. Deleted a repository using the website and it is still showing in github desktop after 1 hour. Will wait one more day to see if it changes. probably restarting the laptop might work.

**Comment by aa0-fyi** [comment]
Same issue here. The repository is private. When I select the deleted repository I am directed to the 404 page. GitHub via Firefox. Also attempted clearning cache, logging out/in.

**Comment by Shoaibhabib769** [comment]
I have deleted my first account of GitHub and made another account but when I upload my repository it shows the previous account's username besides that I remove it from my PC web credentials.

**Comment by jhaaaa** [comment]
Just an FYI that I had this same issue. I deleted the repo a second time and that removed it from view.

**Comment by srushtiKan123** [comment]
has anyone found the solution.. i was learning the GitHub desktop and i added my project there and I delete it from there but i still can see the same project when i try to add the same project 2nd time after delete
