### ISSUE TITLE
Alert Desktop when Repository has been renamed

### ISSUE THREAD

**Issue by Borumer** [desktop/desktop#8590]
### Describe the feature or problem you’d like to solve

shows that if you rename a repository or your username, GitHub Desktop is not aware and never knows of any further pull requests. 

### Proposed solution

It stops users from having the run the command
```
$ git remote set-url origin https://github.com/KnowledgeableKangaroo/Borum.git
```
every time they rename the repository or account username. 

### Additional context

#7947 is the issue you should refer to.

**Comment by outofambit** [comment]
Hi @Borumer thanks for filing this! I'm sorry this isn't working right. I suspect this is due to the same underlying cause of https://github.com/desktop/desktop/issues/3855 and would likely be fixed by https://github.com/desktop/desktop/pull/8132 will fix it.
