### ISSUE TITLE
Can't switch branches

### ISSUE THREAD

**Issue by bnhyde** [desktop/desktop#8592]
### Describe the bug
Whenever I try to switch branches, it switches back to my current branch. When I try to switch to master, it keeps flashing back and forth between the branches.

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Click branch.
2. Click desired branch.
3. See error

### Expected behavior

I expected the branch to switch to the desired branch.

### Actual behavior

A the branch switched immediately back to the original branch.

### Screenshots

A

**Comment by billygriffin** [comment]
Thanks for the issue @bnhyde, and sorry you’re having problems. Would you mind updating your issue with your OS version and which version of Desktop you’re using?

Also, logs would be really helpful in this case. You can find those in “Help” -> “Show Logs in Finder/Explorer” and please choose one from a day where you experienced this issue.

Thanks!

**Comment by tierninho** [comment]
@bnhyde  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
