### ISSUE TITLE
Error 1 returned when commiting a relocated repository

### ISSUE THREAD

**Issue by matheusmoreira12** [desktop/desktop#8601]
### Describe the bug

When repository is moved to another directory, and a relocation is suggested by the UI, upon accepting relocation the repository is rendered "uncommitable" and always exits with code 1 every time a commit is tried.

### Version & OS

GitHub: Version 2.2.2
OS: Windows 10 Pro ver. 1903

### Steps to reproduce the behavior

1. Move a repository to another folder;
2. GitHub will tell you the repository cannot be found;
3. Click on "Locate Repository";
4. Try commiting your changes to branch Master.

### Expected behavior

A commit should be made

### Actual behavior

Nothing happens and a message along the lines of "server responded with error code 1" is displayed.

### Logs

[2019-11-07.desktop.production.log](https://github.com/desktop/desktop/files/3821701/2019-11-07.desktop.production.log)

**Comment by outofambit** [comment]
Hi @matheusmoreira12 thanks for reaching out! I'm sorry you're having this issue. From looking at your logs it looks like something may have gone wrong with the installation of GitHub Desktop, or a subsequent update to it. Could you try reinstalling GitHub Desktop and see if that resolves the issue? Thanks!

**Comment by outofambit** [comment]
@matheusmoreira12 we haven't heard back from you in a while, so I'm going to close this out. Please let us know if you have further questions!
