### ISSUE TITLE
Helper install keeps prompting for admin credentials on macOS

### ISSUE THREAD

**Issue by nhoeboer** [desktop/desktop#8602]
### Describe the feature or problem you’d like to solve

I am using GitHub Desktop on macOS. My working account is not an admin account so has restricted access to system functions. GitHub Desktop is in stalling a so called Helper which apparently requires admin access to install. 

Unclear on why it happens but keeping GitHub Desktop running keeps popping up a authentication prompt to install this helper.

- Why is this pop-up still coming? Did the installation of the Helper fail? Why don't I see a message what went wrong so I can resolve the issue?

- Why is there a helper needed with in the first place? Where can I find documentation on what this helper does and above all why does it need such broad access?

- Why isn't there an option to run GitHub Desktop without this helper? In the end it should just be looking at the file system and no further access should be needed.

### Proposed solution

Removing the Helper will remove the annoying pop-ups. Earlier versions of the GitHub desktop client did not require a helper so what has changed?

### Additional context

I am running GitHub Desktop as a normal user without admin privileges

**Comment by outofambit** [comment]
Hi @nhoeboer! If this the helper I'm thinking of, it is a standard part of Electron apps. Totally understand your frustration with this, though. Could you share what version of macOS and Desktop you're using? Also, did you install GitHub Desktop yourself, or did a user with admin privileges do it? Thanks!

**Comment by nhoeboer** [comment]
I am still running Mojave. Don't fully understand the Electron argument: I have other Electron apps on my system (e.g. Slack) and they don't seem to have this issue. Installed the app my self but even if allowing for temporary admin privileges it will complain later on again and when not allowing the privileges it still works fine...
 
Grtz, Niek
 
 
----- Original message -----From: evelyn masso <notifications@github.com>To: desktop/desktop <desktop@noreply.github.com>Cc: nhoeboer <n.hoeboer@nl.ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [desktop/desktop] Helper install keeps prompting for admin credentials on macOS (#8602)Date: Sat, Nov 9, 2019 02:07 
Hi @nhoeboer! If this the helper I'm thinking of, it is a standard part of Electron apps. Totally understand your frustration with this, though. Could you share what version of macOS and Desktop you're using? Also, did you install GitHub Desktop yourself, or did a user with admin privileges do it? Thanks!
—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
 Tenzij hierboven anders aangegeven: / Unless stated otherwise above:
IBM Nederland B.V.
Gevestigd te Amsterdam
Inschrijving Handelsregister Amsterdam Nr. 33054214

**Comment by tierninho** [comment]
@noelledusahel Possible to include a screenshot of the message for reference purposes? Thanks!

**Comment by niik** [comment]
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.

**Comment by zarezkabel** [comment]
--
Sent from Mail.ru app for Android pondělí, 02 prosince 2019, 04:06odp. +01:00 from Markus Olsson  notifications@github.com :
