### ISSUE TITLE
Can't loggin in Bitbucket.

### ISSUE THREAD

**Issue by SolAleksander** [desktop/desktop#8607]
Login&password is correct! But I can't to loggin. Fetchins, pulling don't work. From console I can do 
this. 

![image](https://user-images.githubusercontent.com/29248079/68528356-9dc56a00-0302-11ea-942d-d3233f83f4b3.png)

**Comment by billygriffin** [comment]
Hi @SolAleksander, thanks for the issue. Here's the documentation for authenticating with Bitbucket: https://github.com/desktop/desktop/blob/development/docs/integrations/bitbucket.md

Let us know if that doesn't resolve it!
