### ISSUE TITLE
Scroll down to '....'m

### ISSUE THREAD

**Issue by kopaing99** [desktop/desktop#8608]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by Rexogamer** [comment]
Hey! Please could you fill out the template so we can understand your issue?
