### ISSUE TITLE
git is not pushing a .env file

### ISSUE THREAD

**Issue by Glwssa** [desktop/desktop#8609]
### Describe the bug

git is not pushing a .env file in the repository
(i dont know how to add it manally)

### Version & OS

Version 2.2.3 Windows 10

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by Glwssa** [comment]
[2019-11-07.desktop.production.log](https://github.com/desktop/desktop/files/3827823/2019-11-07.desktop.production.log)
[2019-11-09.desktop.production.log](https://github.com/desktop/desktop/files/3827824/2019-11-09.desktop.production.log)

**Comment by Glwssa** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/46265146/68536050-2f5dc780-0355-11ea-8017-a2fc910cc1a1.png)

**Comment by Glwssa** [comment]
nevermind fixed it

**Comment by Rexogamer** [comment]
Was it your gitignore?

**Comment by Glwssa** [comment]
Yeap
