### ISSUE TITLE
Undo Discard Changes

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#861]
As mentioned in https://github.com/desktop/desktop/issues/319#issuecomment-271680777:

>Mac users currently have a menu option that persists until you perform another action like committing, and even then you still have the option to recover changes from the Trash. Windows has the temporary Undo bar, which is great for those quick "oh 💩 " moments where you react quickly, but not so great if you haven't realized what you've done long after the bar is gone (we've had quite a few users write in about this). I think having a menu option like GitHub Desktop for Mac does today would be 👌 .

**Comment by shiftkey** [comment]
Given the little external feedback we've had about this (for macOS or Windows), I'm going to close this out as unnecessary for now.
