### ISSUE TITLE
No poder traducir el programa a español 

### ISSUE THREAD

**Issue by griarufe** [desktop/desktop#8610]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by Rexogamer** [comment]
Hey! Where is the translation issue?

**Comment by tierninho** [comment]
Lo siento, solo ingles por ahora.
