### ISSUE TITLE
Trying to download a file 

### ISSUE THREAD

**Issue by Airbus5717** [desktop/desktop#8611]
Hi i am trying to download https://github.com/YesAviation/747-400
but every time i am downloading it cancels 
it happens the web too
not just the desktop

**Comment by billygriffin** [comment]
Hi @Airbus5717, this issue doesn’t appear to be related to the GitHub Desktop application, and GitHub more generally doesn’t have control over your ability to download files onto your machine, so I’m going to close this issue. Best of luck.
