### ISSUE TITLE
Signout button not working on mac

### ISSUE THREAD

**Issue by crimson-med** [desktop/desktop#8612]
### Describe the bug

I have a corporate account and a personal account. This morning I signed-out from one of my accounts and connected to the other one. 

Now that I try to Sign-out nothing happens when I click the button.

### Version & OS

macOS
github desktop 2.2.3

### Steps to reproduce the behavior

1. Sign into an account
2. Do stuff
3. Sign out 
4. Sign in another account
5. Do stuff
6. Sign out not working

### Expected behavior

Be able to click and actually sign out of my account

### Actual behavior

does not sign out 

### Screenshots

![Nov-11-2019 15-01-00](https://user-images.githubusercontent.com/28290546/68567767-d006d100-0494-11ea-8529-a5a2bb296bf9.gif)

### Logs

[2019-11-11.desktop.production.log](https://github.com/desktop/desktop/files/3830013/2019-11-11.desktop.production.log)

**Comment by billygriffin** [comment]
Hi @crimson-med, thanks for the issue. I was unable to reproduce this using the steps you described and also on macOS. Is your corporate account using GitHub Enterprise Server by chance? That shouldn't matter I don't think but just wanted to clarify.

I also saw in the logs that GitHub Desktop may still be in your "Downloads" directory on your machine. To ensure you get updates, you need to move it out of that directory (we usually recommend "Applications" as the best place to keep it).

I didn't see anything else there that popped out at me, any ideas @desktop/support or @desktop/quality-assurance?

**Comment by tierninho** [comment]
> I also saw in the logs that GitHub Desktop may still be in your "Downloads" directory on your machine. To ensure you get updates, you need to move it out of that directory (we usually recommend "Applications" as the best place to keep it).

👍 

```
Error: Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. See https://github.com/Squirrel/Squirrel.Mac/issues/182 for more information.
```

Based on that, I agree that you should move it and try signing out again.

**Comment by crimson-med** [comment]
It wasn't in download folder. I have uninstalled the app and reinstalled it and it seems to be working now.

**Comment by billygriffin** [comment]
Thanks! Sorry for the confusion, and glad it’s working!
