### ISSUE TITLE
Support a `-profile` commandline switch

### ISSUE THREAD

**Issue by staabm** [desktop/desktop#8613]
### Describe the feature or problem you’d like to solve

I have found some issues in this tracker which tell us about the demand to use multi-account settings, different browsers per user or similar, see e.g.
https://github.com/desktop/desktop/issues/3707
https://github.com/desktop/desktop/issues/7830
https://github.com/desktop/desktop/issues/8086

### Proposed solution

in case github desktop would support a `-profile` (or similar) command-line switch (like e.g. [Firefox does](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Multiple_profiles)) which allows to define a profile directory to be used, a lot of this problems can be solved.

this profile directory could save then all the github desktop settings itself e.g.
- which shell should be used
- which browser to use
- which IDE to integrate with
- which git credentials to use

that way a user could start github desktop with the profile switch and use several applications at once in different context.
this might also be an simpler solution to the actual problem instead of solving this problem at the application UI level.

wdyt?

**Comment by tierninho** [comment]
@staabm Many thanks for the suggestion. We will take it into account when we address this issue in our roadmap. A few of the technical constraints are [here](https://github.com/desktop/desktop/issues/3707#issuecomment-400297401).

The current stance on this feature is:

> Hi folks, thanks for weighing in on why this is important to you. It's not part of our near-term plans, but we do recognize that it would likely be valuable for many people who are forced to have multiple accounts. All issues labeled future proposal are still under consideration for potentially being reopened, and there are 40 left that we'll continue to work through until issues are either open or closed as a way to signal whether we intend to support them at some point. Thanks again and appreciate your patience.

Until #3707 is reopened, I am going to close this issue. Appreciate the proposed solution as it may be utilized down the road.
