### ISSUE TITLE
Database compression with GitHub Desktop?

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [desktop/desktop#8617]
### Describe the feature or problem you’d like to solve
I did a search, but can't find an issue to it... even if I'm sure I can't be the first requesting this...
That's about database compression ???
The simple program "Git Gui" delivered with Git for Windows can do it... and it speed up Git!
So come this feature to GitHub Desktop and if, when?

Screenshot of the request to compress a repo DB after start Git Gui up with it:
![2019-11-12 09_08_16-Git Gui (bleachbit)](https://user-images.githubusercontent.com/11881073/68667081-70b4c980-0545-11ea-870a-3c4b0413dbb9.jpg)

**Comment by billygriffin** [comment]
Thanks @Tobias-B-Besemer for the issue! We haven't seen this come up before in several years, so this isn't something we intend to support unless we see significant evidence that it's desired by a significant percentage of our user base. I really appreciate your request and we're not opposed to looking into this further in the future if there seems to be a lot of people who it would be helpful for.
