### ISSUE TITLE
SSLCertificate Issue

### ISSUE THREAD

**Issue by Nikhilpavan944** [desktop/desktop#8618]
### Describe the feature or problem you’d like to solve
I'm getting SSLCertificate issue while using Github Desktop. I don't know how to solve this issue.

**Comment by billygriffin** [comment]
Hi @Nikhilpavan944, would you mind providing more info to help us diagnose? In particular, your OS version, GitHub Desktop version, description of when this is happening and what you're doing when it does, and screenshots if you have them?

**Comment by tierninho** [comment]
If this https://github.com/desktop/desktop/issues/4291 is the issue you are facing, please report this issue to the [Git for Windows](https://github.com/git-for-windows/git) project, as we can only help you address issues with GitHub Desktop and it's embedded Git (which is a later version than the one you are currently running).
