### ISSUE TITLE
Request: favor the branch name that exactly matches search input

### ISSUE THREAD

**Issue by zeke** [desktop/desktop#8621]
I often copy branch names directly from the GitHub.com pull request page:

---

![Screen Shot 2019-11-12 at 8 12 48 AM](https://user-images.githubusercontent.com/2289/68688836-4e5e8400-0524-11ea-8f68-5cfe50e27441.png)

---

Then I open Desktop so I can switch to that branch locally:

![Screen Shot 2019-11-12 at 8 11 27 AM](https://user-images.githubusercontent.com/2289/68688892-6504db00-0524-11ea-92ea-ae816238ca84.png)

Because I am pasting the exact name of the branch name, I don't stop to look and see if the first selected result is my branch name. I am blindly confident that the right branch will be the top result, because it's the exact name of the branch.

However, in this case, Desktop is giving preference not to the remote branch that I want to switch to, but instead to a local branch that partially matches my input. This got me into trouble, and I ended up committing and pushing my work to the wrong branch.

The ask: if there's a remote branch whose name is an exact match to what has been entered in the input, that branch should be selected by default.

**Comment by billygriffin** [comment]
Hi @zeke! Have you ever used the "Open this pull request in Desktop" link?

<img width="698" alt="Screen Shot 2019-11-12 at 1 26 59 PM" src="https://user-images.githubusercontent.com/5091167/68708047-24bb5200-0550-11ea-8b67-7226bc9efb5a.png">

I think your request is still valid, but we also always group recent branches above others so this would represent a departure from that paradigm and I'm not positive the benefit is worth potentially confusing people. Thoughts?

**Comment by zeke** [comment]
> Have you ever used the "Open this pull request in Desktop" link?

🙈 I forgot this existed! Very useful. 👍 

>  I'm not positive the benefit is worth potentially confusing people

You're probably right. Just wanted to bring it up because it caused minor confusion. Feel free to close!
