### ISSUE TITLE
Switching To Branch Text Cut Off

### ISSUE THREAD

**Issue by tebriel** [desktop/desktop#8622]
### Describe the bug

When switching branches, the text `Switching to Branch` was cut off to display `Switching to Bra...`

### Version & OS

Version 2.2.3
OSX Version 10.15.1

### Steps to reproduce the behavior

1. Switch to another branch with CI Status Checks on It
2. Note that the CI Status icon goes away, but the text is still cut off for the action text `Switching to Bra...`

### Expected behavior

If the CI Status Check icon goes away, the text should use the full area to display.

### Actual behavior

Text is cut off.

### Screenshots

![Screen Shot 2019-11-12 at 3 21 30 PM](https://user-images.githubusercontent.com/821688/68707952-b59a2980-0560-11ea-82ca-72302d2fb856.png)

### Logs

N/A

### Additional context

Minor UI Bug

**Comment by tebriel** [comment]
Upon some further context switching, I *think* it's after the branch has switched, but is still loading the CI check status. Before it knows what the status is, it shrinks the text to accommodate the image for CI Status and PR #.

**Comment by tierninho** [comment]
@tebriel Nice spot! Thanks for reporting. Adding the `bug` label to this.

**Comment by kuychaco** [comment]
> I think it's after the branch has switched, but is still loading the CI check status. Before it knows what the status is, it shrinks the text to accommodate the image for CI Status and PR #.

Here's a gif illustrating exactly when the text gets cut off:

![branch-checkout-cutoff](https://user-images.githubusercontent.com/7910250/68809903-c6f73a80-0621-11ea-84a2-8b73ba6c7118.gif)
