### ISSUE TITLE
Increase size of up/down arrows in fetch/push/pull button for better visual differentiation

### ISSUE THREAD

**Issue by ianshmean** [desktop/desktop#8624]
The up and down arrows are a little too small to be easily discerned from each other at typical viewing distances (on a macbook retina screen, for instance). It would be good to increase their size, or make them more visually top/bottom heavy.

**Comment by tierninho** [comment]
@ianshmean Just to clarify, you are talking about the arrow on the left side of this pic? 

![Screen Shot 2019-11-13 at 9 26 53 AM](https://user-images.githubusercontent.com/14828183/68796980-d6fa2480-05f7-11ea-92d1-8cad4124c3d7.png)

@desktop/design for feels.

**Comment by ianshmean** [comment]
Indeed, the arrow on the right side. Thanks for the screenshot.

I'm not sure whether the screenshot shows at the right scale here, but it does show how the arrow is a little too small to interpret clearly. That's what I find on the MacOS version at least.

**Comment by agisilaos** [comment]
+1 on that. It would be a great improvement, for accessibility reasons as well. cc: @tierninho

**Comment by billygriffin** [comment]
@ianshmean Thanks for the issue! We discussed this internally and given that it's paired with the "Push" or "Pull" text, we think the arrows provide added context but aren't the only indicator so they become slightly less important. Therefore we think it's ok as is for now, but we're definitely open to revisiting this if we see more evidence that it's causing problems for more people. Thanks again!
