### ISSUE TITLE
Push Error - Revocation Server Offline

### ISSUE THREAD

**Issue by tee1bn** [desktop/desktop#8633]
![Screenshot (134)](https://user-images.githubusercontent.com/16835858/68888453-e1f5a780-0712-11ea-8ed8-0d604fe1eab3.png)
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

This happens as I try to push to origin

**Comment by tierninho** [comment]
@tee1bn thanks for the report!

It looks like this is an issue with Git not being able to check the certificate revocation list on the user's machine, and it falls back to throwing an error.

We have a writeup about how to opt-out of this behavior in our Known Issues document - please check it out!

**Comment by billygriffin** [comment]
Since this is a known issue and not something we think we can fix, I'm going to close this. Please let us know if that doesn't resolve it @tee1bn!
