### ISSUE TITLE
Can't rename repo

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [desktop/desktop#8637]
### Describe the bug

Seems there is no option in GitHub Desktop to rename the repo.
Maybe it's intended that the admin must do this with the web interface...
But after updating the name of the repo with the web interface and after doing a new fetch with GitHub Desktop, the name of the repo doesn't get updated!
And if this is intended, then I'm still missing an option in GitHub Desktop to do it manual...

### Version & OS

GitHub Desktop v2.2.3
Win7, 64-bit

**Comment by tierninho** [comment]
@Tobias-B-Besemer You are correct, it is intended to be done via the web interface. As you have done so, try switching do a different repo in Desktop and then switch back to the renamed repo. It takes a second, but it will update.

**Comment by MarcelloTheArcane** [comment]
@tierninho What if the repository isn't hosted on GitHub?

**Comment by Tobias-B-Besemer** [comment]
And what if I haven't a second one to switch to ??? ^^
