### ISSUE TITLE
Authentic Error 

### ISSUE THREAD

**Issue by lishuhaolasu** [desktop/desktop#8638]
### Describe the bug

Always Authentic Error after set windows cmd default encode format

### Version & OS

Windows 10 Pro (1903  OS inside ver 18362.418)

### Steps to reproduce the behavior

1. Run Regedit.exe
2. Open "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor" add "autorun : chcp 65001"
3. Open Github Desktop and pull any private repo

**Comment by steveward** [comment]
@lishuhaolasu thanks for contributing. This is a [known issue](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789). At this time we do not have a way of working around this limitation. Based on this [StackOverflow thread](https://stackoverflow.com/a/57134096) it looks like there may be an option to set the system local to UTF-8 in Windows 10. I would recommend taking a look at that to see if it would be a better solution for your situation.

I'm going to close this issue out, but let us know if you have any other questions about this.
