### ISSUE TITLE
Link to View File in GitHub

### ISSUE THREAD

**Issue by intrepidws** [desktop/desktop#8639]
It would be very helpful to be able to right-click on a file, either in the Changes or History tab, and have a "View on GitHub" menu item available.

**Comment by billygriffin** [comment]
Hi @intrepidws, thanks for the issue! Would you mind sharing how viewing a file on GitHub would be useful to you and what you’ll be able to do with that that you can’t do today by opening it your editor? Just trying to understand potential use cases better.

**Comment by intrepidws** [comment]
@billygriffin Sure, no problem. I ran into this issue earlier today while editing a file because I needed to perform a git blame on a specific line. Since that isn't possible in the desktop app, it's something that I need to perform on GitHub.com - and it would be nice to be able to quickly navigate to that file in my repo. Another use case that I ran into is needing to see the history for a given file.

**Comment by billygriffin** [comment]
Thanks for the issue @intrepidws! I'm going to combine this with #3754 which is still under consideration as part of our future proposals. I could see viewing it on GitHub.com being a potential implementation for solving this problem if we choose not to bake a more fully featured history and/or blame into GitHub Desktop. Thanks!
