### ISSUE TITLE
Open in Desktop not working.

### ISSUE THREAD

**Issue by EnderBro123** [desktop/desktop#8645]
### Describe the bug
GitHub Desktop not opening/cloning when using the Open in Desktop button on other GitHub pages.

### Version & OS
I have no idea. Nor do I know where to get this from without posting a bunch of private PC info.

### Steps to reproduce the behavior
Use Open in Desktop on the Clone or Download button.

### Expected behavior
It opening and cloning the repository.

### Actual behavior
Taking me to the download page for GitHub Desktop.

### Screenshots
![image](https://user-images.githubusercontent.com/51277766/68995761-20d84a00-0846-11ea-86c1-c3a2bf65b20e.png)
![image](https://user-images.githubusercontent.com/51277766/68995763-2897ee80-0846-11ea-8e35-2e155afe1e6c.png)

### Logs
None.

### Additional context
None.

**Comment by Rexogamer** [comment]
You can get the Desktop version from the “About GitHub Desktop” dialog, and can run the winver command to get the OS version.

**Comment by tierninho** [comment]
@EnderBro123 This is intended behavior and a duplicate issue of https://github.com/github/ce-desktop/issues/621.

I believe you have to signed into both Desktop and GitHub.com.

Let us know if you run into further issues.

**Comment by EnderBro123** [comment]
@tierninho I'm signed in to both.

**Comment by billygriffin** [comment]
@tierninho I think that issue you linked might provide some clues but it’s internal only so folks outside GitHub won’t be able to see it. 

I’m going to reopen this if you’d be willing to help us figure out what’s going on @EnderBro123. Previously when we’ve seen this, the issue has been caused by someone not having signed into their GitHub Enterprise account from Desktop yet, but it sounds like maybe you have? Would you mind sharing the version of Desktop (from “About GitHub Desktop” in the menu bar) and what version your operating system is on your machine?

**Comment by EnderBro123** [comment]
I'm don't use an Enterprise Account, I'm using a normal account. Apart from that, I'm signed into both.

**Comment by niik** [comment]
Hi @EnderBro123, sorry to hear you're having problems. I took a look at this and from our end it doesn't appear as if the `EnderBro123` account has signed in to GitHub.com using GitHub Desktop yet. Now this could certainly be a problem on our end but given that we haven't heard any reports of other users having a problem with this I'd like to make doubly sure that you're signed in with the correct account in GitHub Desktop.

Please open the Options dialog (located under the File menu) and verify that the `EnderBro123` account shows up as signed in under the GitHub.com header. It should look something like this:

<img width="485" alt="image" src="https://user-images.githubusercontent.com/634063/69968850-95d0a280-151b-11ea-8bf8-540dbd517981.png">

If that appears to be correct please try signing out and then signing back in again and let us know if you're still not able to use the clone in desktop button.

**Comment by EnderBro123** [comment]
@niik I'm signed into both.

**Comment by arielcarrera** [comment]
Hi @EnderBro123, Have you tried doing logout and login again in GitHub Desktop?
I solved same problem doing that...
Regards

**Comment by niik** [comment]
This issue has been stale for a good while now so I'm going to close it out. If this is still an issue please let us know and we can see about reopening.

**Comment by dixitsandeep** [comment]
I faced an issue while launching GithubDesktop, which had been working for a month. It was not launching today.
I did not update GithubDesktop after installation a month ago. Windows version updates in between when I restart/shutdown.

I went to github.com and used the "Launch Github Desktop" button. Miraculously, the github desktop opened up. Not sure what is different in this method.

**Comment by GTAextremeX** [comment]
Nice

**Comment by GTAextremeX** [comment]
`trjgl`lhlvmmv
C. t? mfmf
F
the
c
g

vg

G

G
g
H
vh
vg

gg

**Comment by hammyofmha** [comment]
> ### Describe the bug
> 
> GitHub Desktop not opening/cloning when using the Open in Desktop button on other GitHub pages.
> 
> 
> 
> ### Version & OS
> 
> I have no idea. Nor do I know where to get this from without posting a bunch of private PC info.
> 
> 
> 
> ### Steps to reproduce the behavior
> 
> Use Open in Desktop on the Clone or Download button.
> 
> 
> 
> ### Expected behavior
> 
> It opening and cloning the repository.
> 
> 
> 
> ### Actual behavior
> 
> Taking me to the download page for GitHub Desktop.
> 
> 
> 
> ### Screenshots
> 
> ![image](https://user-images.githubusercontent.com/51277766/68995761-20d84a00-0846-11ea-86c1-c3a2bf65b20e.png)
> 
> ![image](https://user-images.githubusercontent.com/51277766/68995763-2897ee80-0846-11ea-8e35-2e155afe1e6c.png)
> 
> 
> 
> ### Logs
> 
> None.
> 
> 
> 
> ### Additional context
> 
> None.

**Comment by Rexogamer** [comment]
You're on what looks like Windows 10. You can get the OS build/version by
opening System Information. You can also get your Desktop version by
opening "About GitHub Desktop". No private info will be leaked.

**Comment by Rexogamer** [comment]
On second thoughts, this looks like a repost of an old issue

**Comment by Peaj** [comment]
Open in Dektop never worked for me either.
The log seems to indicate a problem with the arguments passed to the application:
```
2021-07-25T19:23:16.913Z - error: [main] Malformed launch arguments received: C:\Users\...\AppData\Local\GitHubDesktop\app-2.9.0\GitHubDesktop.exe,--allow-file-access-from-files,x-github-client://openRepo/https://github.com/JoshLmao/Spotify4Unity
2021-07-25T19:23:16.971Z - info: [main] Received possible protocol arguments: 2
```
Also logged in in Firefox and GitHub Desktop (2.9.0)

I should mention that it does not take me to the download page.
It just focuses/opens GitHub Dektop but does not show or clone the repo.
So on second thopught this might be a separate issue.

**Comment by kerb9729** [comment]
Still not working Feb 2023.
I am signed in to github.com under the options menu.
I logged out and back in from github.com.  I can see all of my repositories in github desktop (and could from the beginning.  
![image](https://user-images.githubusercontent.com/11187989/216186372-f2ff3f88-25e4-4bea-a839-87c2935586f7.png)
![image](https://user-images.githubusercontent.com/11187989/216186449-7e8f0df0-7f93-4a96-8355-2ab85c8af7f9.png)

**Comment by nickretallack** [comment]
This has been broken for me for ages.  Please re-open.

I'm using version Version 3.2.3 (arm64) on macOS 13.2.1 (22D68) and Chrome Version 111.0.5563.64 (Official Build) (arm64).

**Comment by markaudacity** [comment]
> This has been broken for me for ages. Please re-open.

Same here. Safari 15.6.1 (15613.3.9.1.16), Catalina 10.15.7 (19H2026), GitHub Desktop 3.2.3

**Comment by Peaj** [comment]
Today was the first time I used it and it just worked. Not sure what changed though. Maybe it was fixed in an Update?

**Comment by pacav69** [comment]
i discovered that if you are logged in with github desktop and not logged into github.com it will cause this error. To remedy this issue log into github.com then go to the githun repo you were trying and refresh the page it should allow the user to select ' open with desktop' and then  it should open github desktop.

**Comment by doctor-TZ** [comment]
I met the same question, then I find I forget to login in my web account.  XD, and after login in, the problem solved.

**Comment by ZhaoSQ-CH** [comment]
good！ I find I forget to login in my web account. after login in, the problem solved.

**Comment by SmartManoj** [comment]
Using [this Userscript](https://github.com/SmartManoj/Smart-Userscripts/blob/main/GitHub-shortcuts.user.js), Alt + D will open GitHub Desktop without logging into the website.

**Comment by tillbrodbeck-oviva** [comment]
Force refresh of github.com solved this for me
