### ISSUE TITLE
Command line arguments don't work

### ISSUE THREAD

**Issue by Denis-net** [desktop/desktop#8646]
### Describe the bug

When i try to open GithubDesktop with a repo path through the command line,
it just open the last repo.

### Version & OS

* Version 2.2.3
* Windows 1809 (build 17763.864)

### Steps to reproduce the behavior

1. Open cmd
2. type "cd my/path/to/repo"
3. type `"C:\Users\User\AppData\Local\GitHubDesktop\GitHubDesktop.exe" .`
4. type `"C:\Users\User\AppData\Local\GitHubDesktop\GitHubDesktop.exe" "C:\Progetti\Visual Studio Code\vs-kouter"`
5. Cry in a corner (because it always open the last opened repo)

### Expected behavior

I would like to open the repo and if it doesn't exist reply Yes to "The repo doesn't exist yet, would you like to add it ? "

### Actual behavior

It just open the last repo, even when i try to open a repo that exists

### Screenshots

![immagine](https://user-images.githubusercontent.com/45769702/68999806-4ad15100-08c6-11ea-94eb-5e5f2a62f505.png)

![immagine](https://user-images.githubusercontent.com/45769702/68999808-59b80380-08c6-11ea-82d6-5e8a6698c650.png)

![immagine](https://user-images.githubusercontent.com/45769702/68999816-64729880-08c6-11ea-8a6f-f86a20909c81.png)

![immagine](https://user-images.githubusercontent.com/45769702/68999821-75230e80-08c6-11ea-904a-300ae78a08ef.png)

![immagine](https://user-images.githubusercontent.com/45769702/68999824-81a76700-08c6-11ea-8e8f-6b3983e293a9.png)

![immagine](https://user-images.githubusercontent.com/45769702/68999830-9257dd00-08c6-11ea-83ca-d32afd9d920a.png)

### Logs

[logs.zip](https://github.com/desktop/desktop/files/3854798/logs.zip)

### Additional context

Is it a known issue ?
I normally work in the opposite way of GitHub:
firstly, i start to write some content,
then i want to make a repo,
after that i open GitHubDesktop,
finally i add the local repo,
so i push it in my GitHub Account.

I see that you support VSCode,
I really would like to write an VSCode extension that is able to add (if not exist) or open the repo in the GitHubDesktop, but i need working cmd line args.
What do you think about it ?

Anyway Thank you for the wonderful project !
Best

**Comment by tierninho** [comment]
@Denis-net Thanks for filing this. It looks like there are a bunch of errors in the logs:

```
2019-11-16T21:57:10.446Z - info: [main] Received possible protocol arguments: 2
2019-11-16T21:57:10.448Z - error: [main] Malformed launch arguments received: C:\Users\User\AppData\Local\GitHubDesktop\app-2.2.3\GitHubDesktop.exe,.
2019-11-16T21:57:13.802Z - warn: [ui] fetchCommit: returned an error 'denis-net/vscode-ahk-manager@ffe4053158c7d48742d5ec982f6efe62b0179fc3'
Error: No commit found for SHA: ffe4053158c7d48742d5ec982f6efe62b0179fc3
    at Object.t.parsedResponse (C:\Progetti\Visual Studio Code Extensions\vscode-ahk-manager\webpack:\app\src\lib\http.ts:175:4)
    at T.fetchCommit (C:\Progetti\Visual Studio Code Extensions\vscode-ahk-manager\webpack:\app\src\lib\api.ts:514:14)
    at c.findUserWithAPI (C:\Progetti\Visual Studio Code Extensions\vscode-ahk-manager\webpack:\app\src\lib\stores\github-user-store.ts:265:23)
    at c._loadAndCacheUser (C:\Progetti\Visual Studio Code Extensions\vscode-ahk-manager\webpack:\app\src\lib\stores\github-user-store.ts:239:17)
2019-11-16T21:57:38.592Z - info: [main] Received possible protocol arguments: 2
2019-11-16T21:59:52.200Z - info: [ui] Current tutorial step is NotApplicable
2019-11-16T21:59:52.709Z - warn: [ui] fetchRepository: 'Denis-net/Denis-net.github.io' returned a 404
2019-11-16T21:59:54.671Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/Denis-net/Denis-net.github.io.git/' not found 
```

Are you using a proxy?

@steveward have you seen this before?

---

> I really would like to write an VSCode extension that is able to add (if not exist) or open the repo in the GitHubDesktop, but i need working cmd line args.

Please fill another issue regarding this.

**Comment by Denis-net** [comment]
Hey @tierninho ! 😊👋🏻

Thanks for your assistance.

What kind of proxy you are referring to ?

I have installed this [VSC extension](https://marketplace.visualstudio.com/items?itemName=wraith13.open-in-github-desktop), which uses the url protocol.
When i clicked on the button i get:
![immagine](https://user-images.githubusercontent.com/45769702/69090892-7af52d00-0a49-11ea-8e3a-b505126912b9.png)
Not sure, but:
Could it be possible that TortoiseGit (which i use at office) can affects the normal behaviour of GD ?
Maybe it could create a proxy.

The most strange things of this story are:

* If i open GD it works well (as usual, btw)
* If i create a local .git repo and i add it to GD, it stores it, so it can works offline too
  * i have switched off the connection, and still it work 
* I don't get why it has to connect to `https://github.com/Denis-net/Denis-net.github.io.git/` while `https://github.com/Denis-net.git/` exists
 * should't "name.github.io.git" be the host for personal static websites ?

Could it be possible that GC don't allow to use path/to/repo format ?
If you try it, does it work for you?
What is the correct format for remote repos ?
I have tried "https://github.com/Denis-net/vscode-ahk-manager" and "https://github.com/Denis-net/vscode-ahk-manager.git" without success.

**Comment by tierninho** [comment]
@Denis-net After some research, I believe this is out of our hands. It looks like it is likely some settings in TortoiseGit that are causing this. 

I'd start here:
https://gitlab.com/tortoisegit/tortoisegit/issues/1444

 I will reopen this issue if you find some specifics that Desktop needs to fix.
