### ISSUE TITLE
"Discard all changes" should behave like "Discard changes" if there is only one file changed

### ISSUE THREAD

**Issue by AlexejheroYTB** [desktop/desktop#8649]
Right clicking on the `x changed files` header and clicking on `Discard all changes` should take into consideration the `Show confirmation dialog before discarding changes` setting **__if there is only one change.__**

**Comment by tierninho** [comment]
@AlexejheroYTB Please clarify as I see the confirmation dialogue when right-clicking on the `x changed files` header and clicking `Discard all changes`.

Did you mean that the setting should be ignored if there is only one file being discarded?

**Comment by gurmaigor0** [comment]
![Screenshot_20191113-121523](https://user-images.githubusercontent.com/57747994/69077301-010b7680-0a3e-11ea-8e8d-2d9cbeca1720.png)
support-bitcoin-world@protonmail.con

**Comment by AlexejheroYTB** [comment]
I think the title explains it better.

If there is only one changed file in the file list, "Discard all changes" should do the same thing as the "Discard changes" popup for the file (if its enabled, show the "Discard changes" box, otherwise simply discard changes)

**Comment by tierninho** [comment]
Gotcha. As the menu option for the right-click says `Discarding all changes...` a user should be able to reply on the option set in their Preferences. As of now, we will not be altering this for now. 

Thanks for sharing your thoughts.
