### ISSUE TITLE
Unable to commit changes on github desktop

### ISSUE THREAD

**Issue by Nbobito** [desktop/desktop#8650]
### Whenever I try to commit changes to my respiratory, it gives this error:
Commit failed - exit code 128 received, with output: 'fatal: cannot lock ref 'HEAD': unable to resolve reference 'refs/heads/master': reference broken'

### Version & OS

I have github desktop for windows, version 2.2.3

### Steps to reproduce the behavior

1. Make some file changes in a respritory
2. Get on github desktop
3. Write a summery and click commit to master

### Expected behavior

It normaly Just commits it to master, like it's supposed to.

### Actual behavior

It gives the error described above, and I am not good at github and don't know why it is happening.

### Screenshots

Here are some screenshots of what happened:
![screenshot](https://user-images.githubusercontent.com/45778854/69016273-3dfe3d00-095a-11ea-8dc7-1568a181fecc.PNG)

**Comment by Chandler-Davidson** [comment]
Doesn't seem like an issue with Github Desktop, I would expect this error given the screenshot. No branch is selected (shown by Current Branch: Unknown). Try selecting a branch, or creating a new one.

**Comment by tierninho** [comment]
@Nbobito thanks for the feedback! It looks like something with the underlying Git repository has broken, leaving it in an invalid state.

I think these steps should get you back to a happy place, but **take a backup of your repository before running any of these commands,** just in case.

I'll explain the intent behind each step as we go along. This assumes using Git Bash, but if you are using a different shell let me know which and I'll tweak it.

```
rm .git/refs/remotes/origin/master
```

Git stores refs and other Git data on disk under the `.git` folder, and it looks like the value of whatever `origin/master` entry Git was tracking is now invalid. This will remove the file to hide it from Git locally.

```
git fetch
```

This tells Git to go and fetch whatever it can find from the remote.

```
git branch --set-upstream-to=origin/master
```

This ensures your local `master` is tracking whatever is currently on `origin/master`, which should put Git back into a happy place.

**Comment by outofambit** [comment]
@Nbobito we haven't heard back in a while so I'm going to close this issue. let us know if you have further questions!
