### ISSUE TITLE
Cannot commit anymore

### ISSUE THREAD

**Issue by ckornaros** [desktop/desktop#8653]
### Describe the bug

Since few days when I commit a modification I have an unexpected error.

### Version & OS

Version 2.2.3
Windows

### Steps to reproduce the behavior

1. Select files to commit
2. Add a message on "Summary field" 
3. Click on commit button

### Expected behavior

Commit work ;) 

### Actual behavior

Error message and log message (see bellow)

### Screenshots

![image](https://user-images.githubusercontent.com/5371009/69150683-6fe9dd80-0ad9-11ea-901f-6a530cda5990.png)
.

### Logs

2019-11-19T13:17:55.926Z - info: [ui] [Timing] Action 'create commit' for 'my_orga/my_repo' took 1.527s
2019-11-19T13:18:11.054Z - error: [ui] `git commit -F -` exited with an unexpected code: 1.
stderr:
P a r a m � t r e   i n c o r r e c t . 

Thanks your help and feedback !

**Comment by steveward** [comment]
Thanks for the report @ckornaros. The `Exit code 1` error can be caused by a few things. Often it's caused by having nested `.git` repositories -- could that be a possibility here? 

Have you tried committing directly from the command line to see if that succeeds or produces a more verbose error output?

**Comment by ckornaros** [comment]
@steveward Thanks for your answer. I check and haven't nested .git repositories =>
`...$ find . -name .git
./.git`

And I also able to commit directly from the command line.

**Comment by ckornaros** [comment]
@steveward I found the issue ! When I commit with command line I have a warning due to a rubocop webhook 
`git commit -m"Beautiful comment"
husky > pre-commit (node v12.10.0)
ruby `(pwd)`/hooks/rubocop_hook.rb
/c/Users/ckornaros/RubymineProjects/my_repo/hooks/rubocop_hook.rb:5: warning: Insecure world writable dir /mnt/c/Users/ckornaros/RubymineProjects/my_repo/node_modules/.bin in PATH, mode 040777
Using Rubocop version=0.73.0
Inspecting 2 files
..
2 files inspected, no offenses detected
[xxxxxxxxxxxxxxxxxxxxxxxxx] Beautiful comment
 1 file changed, 2 insertions(+), 2 deletions(-)
`

I fix the warning issue and now it work again. 
It still a issue for me because a warning like that should not make Githb Desktop commit fail no ?

**Comment by steveward** [comment]
@ckornaros thanks for the update! I'm glad to hear you were able to get things working. 

>It still a issue for me because a warning like that should not make Githb Desktop commit fail no ?

If a pre-commit hook fails then committing in GitHub Desktop will also fail. In #5439 we are tracking better surfacing of pre-push hook errors, although in that report it looks like pre-commit hooks should show the full error output (based on https://github.com/desktop/desktop/issues/5439#issuecomment-414335487). I'm going to add some details from this issue into that thread for tracking.

**Comment by ckornaros** [comment]
> 
> 
> @ckornaros thanks for the update! I'm glad to hear you were able to get things working.
> 
> > It still a issue for me because a warning like that should not make Githb Desktop commit fail no ?
> 
> If a pre-commit hook fails then committing in GitHub Desktop will also fail. In #5439 we are tracking better surfacing of pre-push hook errors, although in that report it looks like pre-commit hooks should show the full error output (based on [#5439 (comment)](https://github.com/desktop/desktop/issues/5439#issuecomment-414335487)). I'm going to add some details from this issue into that thread for tracking.

I agree if the pre-commit hook fails but in my case it's only a warning and the pre-commit hook dosen't fail at the end. If a commit in command line works it must also works for github desktop. Did you not agree ?

**Comment by ckornaros** [comment]
@steveward you keep this ticket close ?
