### ISSUE TITLE
files don't be ignored by .gitignore

### ISSUE THREAD

**Issue by timfordev** [desktop/desktop#8654]
### Describe the bug

i have rules for some files in .gitignore, but anyway these files go to "changes" in Github Desktop

### Version & OS

2.2.3 and Windows 7 

### Expected behavior

I don't want all time discard trash files in changes

**Comment by timfordev** [comment]
`.vscode
#  Local .terraform directories
**/.terraform/*

# .tfstate files
*.tfstate
*.tfstate.*
*.swp

### JetBrains template
# Covers JetBrains IDEs: IntelliJ, RubyMine, PhpStorm, AppCode, PyCharm, CLion, Android Studio and WebStorm
# Reference: https://intellij-support.jetbrains.com/hc/en-us/articles/206544839

# User-specific stuff
.idea/**/workspace.xml
.idea/**/tasks.xml
.idea/**/usage.statistics.xml
.idea/**/dictionaries
.idea/**/shelf

# Sensitive or high-churn files
.idea/**/dataSources/
.idea/**/dataSources.ids
.idea/**/dataSources.local.xml
.idea/**/sqlDataSources.xml
.idea/**/dynamic.xml
.idea/**/uiDesigner.xml
.idea/**/dbnavigator.xml

# Gradle
.idea/**/gradle.xml
.idea/**/libraries

# Gradle and Maven with auto-import
# When using Gradle or Maven with auto-import, you should exclude module files,
# since they will be recreated, and may cause churn.  Uncomment if using
# auto-import.
.idea/modules.xml
.idea/*.iml
.idea/modules
*.iml

# CMake
cmake-build-*/

# Mongo Explorer plugin
.idea/**/mongoSettings.xml

# File-based project format
*.iws

# IntelliJ
out/

# mpeltonen/sbt-idea plugin
.idea_modules/

# JIRA plugin
atlassian-ide-plugin.xml

# Cursive Clojure plugin
.idea/replstate.xml

# Crashlytics plugin (for Android Studio and IntelliJ)
com_crashlytics_export_strings.xml
crashlytics.properties
crashlytics-build.properties
fabric.properties

# Editor-based Rest Client
.idea/httpRequests`

**Comment by steveward** [comment]
Thanks for contributing @timfordev. If the files have been previously committed in your repository you will need to run a specific command to prevent the files from being tracked by Git:

`git rm --cached <path_to_file>`

Check out this [help article](https://help.github.com/en/github/using-git/ignoring-files) for more information. Let me know if you have any questions about this.
