### ISSUE TITLE
Github Desktop gets stuck on Configure Git screen when setting it up for the first time.

### ISSUE THREAD

**Issue by JosZimmermann** [desktop/desktop#8657]
### Describe the bug

I have the same problem as the guy in issue #8505

After downloading Github Desktop, I tried using it for the first time. However, when i get to the "Configure Git" page(screenshot below), where is asked what name i would like to have written on my commits, I click Continue after putting my name and email, but the Continue button doesn't trigger anything, is like if i hadn't click the button, not even an error is thrown.
I've tried uninstalling and installing again, even deleting the GitHubDesktopSetup.exe file and downloading it again, but the same thing happens.

### Version & OS

I'm using Windows 10 and the Github Desktop version which was downloaded today.

### Screenshots

![grafik](https://user-images.githubusercontent.com/48101657/69250093-52874300-0baf-11ea-8d55-021a1375b1af.png)

### Logs

I cannot open the logs, as I cannot open GitHub Desktop (can't click "continue" and when I click "cancel" I am coming back to the "Welcome to GitHub Desktop" Page and even when I cklick there on "skip this step" I am forwarded to the same page where I cannot click on "continue".

 When I type type git config --list in the command line I get:
core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
rebase.autosquash=true
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge --skip -- %f
filter.lfs.process=git-lfs filter-process --skip
filter.lfs.required=true
credential.helper=manager

**Comment by steveward** [comment]
Thanks for the report @JosZimmermann. We've seen a couple of cases of this but have been unable to reproduce the issue directly. Could you try following these steps to see if it gets things working?

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop 

Let me know if that helps.

**Comment by JosZimmermann** [comment]
Unfortunately it doesnt help. Still same issue.
Here the logfile:
[2019-11-20.desktop.production.log](https://github.com/desktop/desktop/files/3870298/2019-11-20.desktop.production.log)

**Comment by tierninho** [comment]
Here is the error, which is preventing the config file from updating

```
2019-11-20T16:40:12.832Z - error: [ui] `git config --global --replace-all user.name JosZimmermann` exited with an unexpected code: 255.
stderr:
error: could not lock config file C:/Users/Josua/.gitconfig: File exists
```

**Comment by steveward** [comment]
@JosZimmermann can you see if there is a `.gitconfig.lock` file present in `C:/Users/Josua/`? If there is, try deleting that to see if it gets things working.

**Comment by JosZimmermann** [comment]
Yes there was a file .gitconfig.lock file present in C:/Users/Josua/. I deleted it and now it worked.
Thanks for your help!
