### ISSUE TITLE
Push origin fails on Mac when .DS_Store file is present

### ISSUE THREAD

**Issue by DougAtPeddle** [desktop/desktop#8659]
### Describe the feature or problem you’d like to solve

"Push origin" fails on Mac when .DS_Store file is present.

### Proposed solution

1. Add .gitignore file containing "*.DS_Store"
2. Fetch origin
3. Push origin

### Additional context

This should be added to the "Authorization failed" pop-up dialog as one of the possible causes.  After logging out and back in, checking repo permissions, confirming SSH token, etc, it turned out to have nothing to do with authorization at all.

**Comment by tierninho** [comment]
@DougAtPeddle Thanks for the heads up. We will make a note for the update.

Glad you resolved the issue!

**Comment by dotnetB** [comment]
Good job   u better run bot don’t fall!!

Larry E. Barton
