### ISSUE TITLE
Editor is not being recognized by Desktop

### ISSUE THREAD

**Issue by Fenix2013** [desktop/desktop#8661]
I downloaded GitHub Dektstop for Windows. I installed it on my computer, connected it to my Github.web account and created a new repository. I also downloaded and installed Atom and configured it with my Github.web account and I also downloaded and installed the app Atom for Dektoskop.On my GitHub.web website, it lets me know that I have it installed, but when I want to set it as the default editor in the advanced settings for GitHub Dektoskop, it still shows me as if I didn't have it installed.I've tried everything , I canceled the repository, restarted the GitHub Dektoskop, I downloaded the repository again, but nothing works.Please,can someone advise me what to do to installed it as the default editor in GitHub Dektostop?
Thank you for your assistance and I hope to hear you soon.

Best regards   

Fenix2013

**Comment by dotnetB** [comment]
Hey you keep reading 2013 was Gooood yr.   try LB  122

Larry E. Barton

**Comment by tierninho** [comment]
👋 @Fenix2013 

Could you open up a command prompt (cmd.exe) and run the following commands for me?

`cd %LOCALAPPDATA%\Atom\`
`atom --squirrel-updated`

Then try restarting GitHub Desktop and let me know if you still do not see Atom in the dropdown menu.

**Comment by Fenix2013** [comment]
Hi Tiernan,

I used your advice and it helped,I already can see Atom in advanced settings in the dropdown menu at GitHub Desktop and now it is set as the default editor.
Thank you for your assistance.

Kindest regards

**Comment by tierninho** [comment]
Perfect, glad to be of assistance!!

**Comment by Neustradamus** [comment]
@Fenix2013: What is your Windows version?
