### ISSUE TITLE
Change Stashed Changes Button Color

### ISSUE THREAD

**Issue by Redhunt2013** [desktop/desktop#8662]
### Describe the feature or problem you’d like to solve

Currently,  GHD displays `Stashed Changes` button in a lighter background.  We work on large amount of repositories.  Its very easy to miss when moving from one repo to another if one has stashed changes, due to the lighter color of the button.

### Proposed solution

Proposed solution is to make `Stashed Changes` button color darker (similar to `Commit` button with a different color, if possible).

### Additional context

![GitHub Desktop-Stashed Changes Button](https://user-images.githubusercontent.com/5237704/69283452-b73f9f00-0ba9-11ea-9414-e991d8e2fe37.png)

**Comment by tierninho** [comment]
@Redhunt2013 thanks for the suggestion.

@desktop/design for thoughts on this.

**Comment by billygriffin** [comment]
@Redhunt2013, thanks for the issue! We went back and forth on the level of prominence to give to this, and have seen preferences from folks who want it to have more prominence and those who don't think it should have very much. Given that we have the suggested next step for viewing the stash, we think what we currently have is reasonable, and we're planning to stick with it for now. Thanks!
