### ISSUE TITLE
Inconsistent behavior when switching branches from protected branch

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#8664]
#### Scenario 1 
When I'm on a protected branch with uncommitted changes, and I switch branches via the "Want to switch branches" link in the protected branch warning, it just brings my changes with me by default and does not prompt me to ask if I want to stash the changes.

#### Scenario 2
However, when I'm in the exact same state but I choose to switch branches (or create a new branch - thanks @tierninho!) from the branch switcher directly without clicking the "Want to switch branches" link, I am prompted with the stash dialog.

<img width="324" alt="Screen Shot 2019-11-21 at 4 16 17 PM" src="https://user-images.githubusercontent.com/5091167/69384704-43b99280-0c7a-11ea-8147-b9b4193d2cd2.png">

---

The inconsistency was particularly jarring. In thinking through it, we're skeptical that people will likely want to stash changes on a protected branch that they'll never be able to push.

### Proposed solution

Discussing with the team, we think it's reasonable to never prompt to stash changes if someone is switching _away_ from a protected branch. In other words, align scenario 2 with the behavior of scenario 1.

**Comment by tierninho** [comment]
Side note: part of `Scenario 2` includes creating a New Branch, which also prompts the stashing dialogue.
