### ISSUE TITLE
Solved problem

### ISSUE THREAD

**Issue by wolongshiyu** [desktop/desktop#8667]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by billygriffin** [comment]
Hi @wolongshiyu, this is a public repository that many people subscribe to, so please do not submit empty issues. Thanks!
