### ISSUE TITLE
yarn install fails on mac (fsevents)

### ISSUE THREAD

**Issue by benknoble** [desktop/desktop#8669]
### Describe the bug

I want to work on an external editor integration, so I'm trying to setup my dev environment with

```
# yarn
# yarn build:dev
# yarn start
```

However, yarn install fails but continues. The others continue as well, with many errors and warnings, and the app never really opens.

### Version & OS

```
# sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132
# yarn --version
1.17.3
# node --version
v13.1.0
# git rev-parse @
2870bfb005e569d37c142d5c17f4f7138a44a20c
```

### Steps to reproduce the behavior

Clone my fork (benknoble/desktop)—this is only because I haven't updated it since I forked it within the last few days.

Attempt to use `yarn` or `npm` to install on a mac.

### Logs

Separate (big): https://gist.github.com/benknoble/d61c5027bed22e852e1dd83ce2a8675b

### Other

#5107 won't solve this for me, since I can't just format the machine. Also note that `gcc` is a symlink to `clang` on macs...

**Comment by tierninho** [comment]
@benknoble Thanks for the issue. This may have to wait until next week as some folks are out.

Spotted some errors in the logs:
```
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.3/fse-v1.2.3-node-v79-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.3/fse-v1.2.3-node-v79-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.2.3 and node@13.1.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.3/fse-v1.2.3-node-v79-darwin-x64.tar.gz 
gyp info it worked if it ends with ok
```

I noticed you ran `yarn run` but our [docs](https://github.com/desktop/desktop/blob/development/docs/contributing/setup.md#building-desktop) say `yarn start`. Not sure of the exact difference but it may help? 🤷‍♂ 

cc @outofambit @kuychaco

**Comment by benknoble** [comment]
@tierninho typo, apologies. I ran `yarn start` for step 3. Those logs are for the install, however (I didn’t include the rest, I think, as it was already getting to be unwieldy.)

**Comment by outofambit** [comment]
hey @benknoble sorry for the delay here. can you make sure you have xcode dev tools installed? you can install them from the terminal with `xcode-select --install`.

**Comment by benknoble** [comment]
@outofambit uh, yes, I'm a developer by day and night (brew user, mostly, but one needs the xcode tools to get off the ground). But I can certainly try to "upgrade" and see if that makes a difference...

**Comment by outofambit** [comment]
@benknoble ok hmm. sorry for the rudimentary question. (i thought i had a similar issue to this in the past where i had to re-install dev tools after upgrading macOS or something similar.) i'll take another look at this tomorrow and see if i can offer more insight.

**Comment by benknoble** [comment]
@outofambit thanks for the help; I understand sometimes you just need to walk through the basics. I would love to get through this, because I think I can add vim as an external editor for both mac and linux...

**Comment by niik** [comment]
Hi @benknoble, I suspect that your issue stems from trying to build GitHub Desktop with Node 13, from your original issue body (thanks for including that by the way, that's super helpful!):

```
# node --version
v13.1.0
```

Right now we're building GitHub Desktop with Node 10. There's a section in our setup docs in case you need to use [several different versions of Node on your machine](https://github.com/desktop/desktop/blob/3b76b4f6a9e199fda9b22a29259debd3b9ab7ece/docs/contributing/setup-macos.md#i-need-to-use-different-versions-of-nodejs-in-different-projects).

Please try building with Node 10 and report back if that doesn't solve your problem.

**Comment by niik** [comment]
Hey @benknoble, since we haven't heard back from you I'm going to assume that the Node 10 solution worked and close this out. If you just haven't had time to try it out yet that's absolutely fine, we can always reopen this later.

**Comment by benknoble** [comment]
This worked great! Thanks @niik
