### ISSUE TITLE
Custom repository name

### ISSUE THREAD

**Issue by lefebvrecharlie** [desktop/desktop#8671]
Hi,

It would be nice to add the possibility to add a custom name to a repository.
I have multiples projects with same subproject and I have to let my cursor on repository label to know the folder location.

Thanks in advance

**Comment by steveward** [comment]
Thanks for contributing @lefebvrecharlie. This was previously requested in https://github.com/desktop/desktop/issues/7856, so I am going to add your feedback there and close this issue out.
