### ISSUE TITLE
Continual unrecoverable error

### ISSUE THREAD

**Issue by apizz** [desktop/desktop#8674]
### Describe the bug

```
Error: spawn /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git EAGAIN
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

Version: 2.2.3
OS: Mac OS 10.14.6
```
### Version & OS

macOS 10.14.6
GD 2.2.3

### Steps to reproduce the behavior

1. Open Github Desktop
2. See error. Click Quit & Restart.
3. Note same error.

### Expected behavior

No error

### Actual behavior

Continual error

**Comment by steveward** [comment]
@apizz thanks for the report. Some users have had success resolving this issue by restaring their machine (#5416 and #8539). Could you try doing that to see if it gets things working for you?

**Comment by apizz** [comment]
Yeah that did it. thanks.
