### ISSUE TITLE
Branch Change Selection after Branch Deletion

### ISSUE THREAD

**Issue by greatzambino** [desktop/desktop#8679]
When deleting a branch from a repo, github desktop automatically changes the branch to master after the deletion of the branch is complete.

A clear and concise description of what the feature or problem is.

Allow user to select the target branch to load after the branch is deleted.

How will it benefit Desktop and its users?

Allows users to select the parent branch of the deleted branch if it is NOT the master

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by billygriffin** [comment]
Hi @greatzambino, we think the default branch is a reasonable default after changing branches and adding an extra step of asking which branch folks would like to be on after deleting branches might be frustrating, so I'm not super inclined to say that we're likely to change this. However, I am interested in your workflow and how this is occurring for you, and why it would make things easier if you could choose the branch to be on each time you deleted a branch just to help us understand the potential use cases better.

I'm going to close this for now to indicate that it's not likely something we'll support, but we're always happy to revisit those decisions and learning more about your workflow will help start that discussion. Thanks!
