### ISSUE TITLE
Request make change list files more visible

### ISSUE THREAD

**Issue by b1ackmai1er** [desktop/desktop#8681]
### Describe the feature or problem you’d like to solve
When scrolling through the change list with a large number of files it can still be quite difficult to locate changed files even though the icon has changed to orange  colour with a circle in it. Would like it to be more visible. Find it particularly difficult to use on hi-resolution laptop.

A clear and concise description of what the feature or problem is.
Difficulty locating specific file changes in long change list.

### Proposed solution
Add a filter button to only show change files the square dot icon;
Change the Square dot icon to something more distinct - diamond dot or circle dot.

How will it benefit Desktop and its users?
Easier to locate specific changes in the change list
### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by Rexogamer** [comment]
Personally I’d go for a filter by change type.

**Comment by billygriffin** [comment]
Thanks for the issue! This is sufficiently similar to #8407 that I’m going to close it and any further discussion can happen there. Thanks!

**Comment by Rexogamer** [comment]
@billygriffin I think you’ve made a bit of a mistake. This issue is not at all related to global usernames/emails. Maybe you made a typo in the issue number?

**Comment by billygriffin** [comment]
@rexogamer Thanks, typo, I updated it almost immediately. 😄
