### ISSUE TITLE
Keyboard Shortcut for Copy File Explorer/Finder Path

### ISSUE THREAD

**Issue by justingolden21** [desktop/desktop#8682]
### Feature or problem to solve

Navigation to the folder of a GitHub Repository is something many people do frequently. A shortcut would be an easy way for super users to save time, while not hurting anyone else's experience because it doesn't slow down or complicate anything.

### Proposed solution

Add a keyboard shortcut to copy the path to the current git directory to clipboard. I suggest <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>L</kbd> because Ctrl and Shift align with similar key shortcuts used for similar actions, and it's similar to <kbd>Ctrl</kbd> + <kbd>L</kbd> which is used to select the address bar in file explorer.

### Additional context

This can be done by doing Ctrl Shift F to open file explorer, Ctrl L to open the link, Ctrl C to copy the highlighted link, and then ctrl W to close file explorer, however, this is time-consuming and can be simplified for ease of use.

It shouldn't be hard to implement (I'm willing to help) and we need to remember to update the [keyboard shortcuts website](https://help.github.com/en/desktop/getting-started-with-github-desktop/keyboard-shortcuts-in-github-desktop) with the shortcut, but it doesn't take up any space in the GitHub Desktop UI. Help -> Show keyboard shortcuts is the current way of accessing keyboard shortcuts, which opens the link above.

**Comment by steveward** [comment]
Thanks for contributing @justingolden21! Can you share some examples of how you would use this in your daily workflow with GitHub Desktop? I feel like the two options to either open in Explorer/Finder or open in the command line cover most usage scenarios, but I may be missing something.

**Comment by justingolden21** [comment]
Of course. I'll frequently want to `cd` into a directory and have to do the aforementioned steps before I can navigate there, so I can run commands for web development such as `jekyll`, `sass`, `node` installs, and more. I'll also want the directory in my clipboard so I can paste it in when saving a file in another program, such as in Adobe Illustrator or Photoshop or any external application where I would want to save to a directory for the first time this session.

I don't think it's the most common thing, but seeing as it would help some power users and would cost virtually no time or UI space to develop, I think it's a good option.

I would be happy to help work on it if you'd like as well. Thanks for listening to my feedback.

**Comment by niik** [comment]
Hey @justingolden21, thanks for opening this and thanks for taking the time to explain your workflow. Since a workaround exists for what you want to do and given that this is the first time we've heard this particular feedback we're not going to prioritize this for the time being.

I'm going to close this for now to indicate that it's not likely something we're looking to support at this time. My response is based on some assumptions, and if those aren't quite right and we see further evidence of this likely reducing friction for many more users, we're always happy to revisit. I really appreciate you making the issue, and hope the app is otherwise working well for you.

**Comment by justingolden21** [comment]
Those assumptions are correct, and I agree it should not be a priority given that it's a feature and not a bug. Still, I will hope it doesn't get lost in all of the other closed issues, because I really do think it's a useful feature, and just because others haven't suggested it doesn't mean they wouldn't use it.

Anyway, thank you for looking into this and have a great day.
