### ISSUE TITLE
I'd like to use it with proxy :)

### ISSUE THREAD

**Issue by x86-app** [desktop/desktop#8683]
### Expected feature

I hope there'll be options to set proxy in Desktop. 

### Proposed solution

Because of some regional factors, some countries (regions) get poor connections to GitHub. For some users, using proxy instead of direct connections can solve this problem. 
Proxy is available in browsers and terminals, but not currently Desktop. 

### Additional context

Screenshot: 
![image](https://user-images.githubusercontent.com/46947952/69478411-fdf0fb80-0e2c-11ea-9b19-a2a174ba1ef9.png)

Thanks! :D

**Comment by billygriffin** [comment]
Thanks @x86-app! I think this is the same as  #2789 so I’m going to close it as a duplicate but please let us know if that’s not correct. Thanks!
