### ISSUE TITLE
Render README.md in Github Desktop

### ISSUE THREAD

**Issue by scalderon12** [desktop/desktop#8687]
Render README.md on the home page.
Would allow for developers to have easily accessible information particularly useful for putting instructions and useful links for SOP compliance

Potential mockup below
![Mockup Github Desktop Readme](https://user-images.githubusercontent.com/45019136/69485499-0c77ec80-0e06-11ea-9bee-0602a5f4668f.png)

**Comment by billygriffin** [comment]
Hi @scalderon12, we have no plans to put the README in the product itself. The vast majority of our users are not contributors to the repo, so this feels like too much prominence. Thanks for the suggestion!

**Comment by Rexogamer** [comment]
I’m not entirely certain, but @scalderon12 might be talking about the README in any project, not just desktop/desktop.

**Comment by steveward** [comment]
@scalderon12 rendering READMEs directly in the app is an interesting idea, but is not something that we would prioritize as a feature. There are a couple of available flows that make it pretty easy to view READMEs outside of GitHub Desktop:

- Text editors like Atom and VSCode have built in markdown rendering, and can be launched directly from GitHub Desktop.
- You can use the shortcut `Control-Shift-G` in GitHub to quickly launch a browser and view the repository's README directly on GitHub.

**Comment by scalderon12** [comment]
@Rexogamer is correct that I was talking about the README from the my current repo, not Github Desktop. I just pulled that one in for the mockup.

Thanks for the potential workarounds @steveward, but I don't think it will work for our needs. Going to another application may work for small personal projects, but doesn't scale well for enterprise level workflows where we can have many developers contributing to the same project.

We have probably a couple dozen repos across multiple platforms (Java, SQL, C#, Spring, Mobile(iOS/Android) etc...) and each platform can have slightly different processes from local setup to release. 

Having quickly accessible information within a single application would provide a smooth user experience that would help developers maintain proper compliance with our SOP's. We probably all know how users tend to not review the documentation unless it's very accessible. Having it on the screen where they have to do their work, would be far more ideal rather than having to switch applications.

**Comment by Rexogamer** [comment]
I just thought of another issue with your second workaround: if the repo wasn’t on GitHub.

**Comment by billygriffin** [comment]
Thanks @scalderon12 for the additional context, that's really helpful. For now, we're going to leave this closed, but your use case makes sense and if we hear feedback that others are struggling with not having ready access to that across repositories, we'll definitely consider how to best solve it. Thanks again for the great description.

**Comment by loraderon** [comment]
I think that this issue was prematurely closed for the wrong reason (misunderstanding of the actual request) which does not make it visible in the issue list so that other people could vote for it.
Could it be reopened as a feature request (to gather votes)? Maybe change the title to something more descriptive?

**Comment by tierninho** [comment]
@loraderon Thanks for the input. I changed the title to reflect the original request. At this time we are going to leave it closed for the reasons stated above, but those interested in this feature are welcome to comment any time. Hopefully, the status of the issue does not discourage those from doing so.

**Comment by steveward** [comment]
Feedback from @anerjan in #89332:

>There is plenty of space on summary page that can be used to show Readme.md
>
>We often clone multiple repos locally and forgot what they were about. additionally readme.md have run scripts that can be handy on summary page.

**Comment by steveward** [comment]
Feedback from @J-Likeness in #9208:

>In the GitHub Desktop App, it would be super helpful if the Repositories Description was visible and searchable when you try to clone a repository.
>
>How will it benefit Desktop and its users?
>
>Helps find the repository needing to be cloned and displays more details about it.

**Comment by steveward** [comment]
Feedback from @tomkyle in https://github.com/desktop/desktop/issues/11433:

> >Describe the feature or problem you’d like to solve
> Is it possible to let desktop app render the current repo's README (like the web frontend does), or offer a shortcut way to open the repo README in its editor?
> 
> Proposed solution
> New box in the desktop app's repo canvas (where at repo clean state boxes inform about “push commits using Cmd-P” or “Open repo in external editor using Cmd-Shift-A”). The box would be titled “View README” and offer a button “Open in editor” (which then opens the .md file in the Markdown editor).
> Luxury version: In an ideal world, Desktop app would render the Markdown directly under these boxes, with its TOC in the left sidebar under a third tab “Documentation” (beneath Changes and History). Activating that tab would make the canvas render the docs again.
> >
> >How will it benefit Desktop and its users?
> A keyboard shortcut will shorten the way to the most used project documentation, the repo README. Compared to current situation: Now one has to view the repo in Finder/File explorer, locate the README and open it, and switch back to Desktop …
>

**Comment by mathiash98** [comment]
I was browsing around in the repos on my machine and this idea popped into my head. Sometimes I forget what a certain repo I have downloaded is for. So rendering the readme.md file would make it much easier and faster to remember what this repo is for and how I am supposed to use it.
- And it would give developers a reminder to actually update their readme files when they see something is off.

Right now there are lots of empty unused space when you select a repo without changes. This space could be spent rendering readme file.

> (...) and if we hear feedback that others are struggling with not having ready access to that across repositories, we'll definitely consider how to best solve it.

- The problem with this statement is that nobody is struggling with anything here, this feature suggestion is a new feature that would lift the quality of Github Desktop. It does not solve any issue or problem


I would definitively love this feature!

**Comment by jacortinas** [comment]
Feedback from @YanisBft in desktop/desktop#17248:

> ### The feature request
> When editing a markdown file (i.e. a README file), you can only view the diff in Github Desktop. It would be great to be able to view the rendered version of the file as well.
> 
> ### Proposed solution
> Markdown files, especially README, are files you can edit easily in a lightweight editor, like notepad++ or things like that. Unfortunately, you cannot view how it's rendered in these editors. That's why having a rendered view of markdown files would be very useful in Desktop.
>
