### ISSUE TITLE
Provides options for switching languages

### ISSUE THREAD

**Issue by tdk-kedion** [desktop/desktop#8691]
It provides the option to switch languages so that more people can use GitHub desktop more friendly, which is very useful for novices. It can let novices master the use of software as soon as possible

**Comment by steveward** [comment]
Thanks for the feedback @tdk-kedion. At this time we do not have plans to provide multilingual support in GitHub Desktop due to the bandwidth it would require from the team. Please see #8289 for further information.

**Comment by tdk-kedion** [comment]
What should I do to provide a native language for the GitHub desktop?
