### ISSUE TITLE
How to push only certain commits?

### ISSUE THREAD

**Issue by ariffjeff** [desktop/desktop#8697]
### Describe the feature or problem you’d like to solve

How to push only certain commits (not all current commits at once)? Another way of asking this is: If I have 3 separate commits and I only want to push one of them, how would I do that?

### Proposed solution

A new feature to select which commits to push. This is more flexible than pushing everything.

### Additional context

Do I have a fundamental misunderstanding of how git is supposed to be used or is this a feature that is just simply missing from GitHub Desktop?

**Comment by steveward** [comment]
Thanks for contributing @ariffjeff. At this time it is not possible to push specific commits to GitHub Desktop, but you can use the command line to push a subset of commits. Here's how to do that:

git push origin <commit SHA>:<branch>

So if you have three commits A (4d3bf9) - B (e55b5f) - C (c109e0) and wanted to push A and B to your `master` branch you would run this command:

`git push origin e55b5f:master`

If you wanted to integrate one specific commit into another branch you could use the [`git cherry-pick`](https://git-scm.com/docs/git-cherry-pick) command. 

I hope that helps!

**Comment by lcolen** [comment]
I'm trying to do this, but it tells me that I can't log in with a password, but when I try to use gh auth it tells me that I'm already logged in.
