### ISSUE TITLE
GitHub Desktop Dark theme.

### ISSUE THREAD

**Issue by eusebijucgla** [desktop/desktop#8701]
The dark version of Github Desktop is great but the red and green colors are too saturated, would love to be able to change them, or at least to adjust opacity.

**Comment by tierninho** [comment]
@eusebijucgla Thanks for reaching out. We currently have no plans to adjust them or allow them to be customized at this point.

Going to close this issue for now, but cc'ing @desktop/design in case they want to reopen to make some tweaks to the colors.
