### ISSUE TITLE
"Authentication Failed" Error, but I keep putting in the correct username and pas

### ISSUE THREAD

**Issue by Daimsen** [desktop/desktop#8702]
Issue:
I am putting in the correct username and password into the github desktop, but it still won't authenticate

Version with the OS:
Version is: 2.2.3
and I am using Windows 10

Reproduction Steps:
There is no way to explain it, it just happened suddenly and all I did was make a new Respitory

Expected Behavior:

I expect it to just show up with the authentication page once, and after I fill it in perfectly, it lets me in

Actual behavior:

Instead of asking once, it asks everytime I put it in perfectly, and it is starting to get annoying

Screenshot:

![Authentication](https://user-images.githubusercontent.com/54082504/69593183-0b89bb00-0fbe-11ea-9e57-c0a31633f103.PNG)

**Comment by steveward** [comment]
@Daimsen thanks for the report. Can you verify that you are logged in when you go to `File` > `Options` > `Accounts`? If you are, try logging out and then logging back in to your GitHub account to see if that gets things working.

**Comment by Daimsen** [comment]
I thought that wouldn't work, but apparently it did! Thank you, I can finally work on my project

**Comment by steveward** [comment]
@Daimsen I'm glad to hear! I'm going to close this issue out.
