### ISSUE TITLE
.gitignore still shows in changed files list after being added to the .gitignore file

### ISSUE THREAD

**Issue by maxloh** [desktop/desktop#8704]
### Describe the bug

.gitignore still shows in changed files list after being added to the .gitignore file

### Version & OS

Github Desktop Version 2.2.3
Windows 10 Home 1903

### Steps to reproduce the behavior

1. Add .gitignore to the .gitignore file
1. Go to project page in Github Desktop

### Expected behavior

.gitignore being ignored

### Actual behavior

.gitignore still shows in changed files list

### Screenshots

![image](https://user-images.githubusercontent.com/35831069/69623108-371faa80-107d-11ea-86f3-8aaad4a3c6d1.png)

**Comment by steveward** [comment]
Thanks for contributing @maxloh. If the files have been previously committed in your repository you will need to run a specific command to prevent the files from being tracked by Git:

`git rm --cached <path_to_file>`

Check out this [help article](https://help.github.com/en/github/using-git/ignoring-files) for more information. Let me know if you have any questions about this.

**Comment by maxloh** [comment]
@steveward 

I want to stop git from tracking the .gitignore file while keeping the file in the repo, but the command you provided just remove the file from repo.

After adding .gitignore to the .gitignore file, `git add *` (git cli) would not stage the .gitignore file. However, Github Desktop behaves differently by displaying the file in in changed files list.

I think this behavior should be classified as a bug.
