### ISSUE TITLE
Fatal error for certificate saying unable to check revocation using github desktop

### ISSUE THREAD

**Issue by krunalpatelflynn** [desktop/desktop#8706]
### Describe the feature or problem you’d like to solve

I am trying to push changes to GitHub using git desktop and it is giving me an error shown in the attached screenshot. I never had a problem before and today all of sudden it started throwing this. Although I am able to get updates from other branches. it just doesn't allow me to push my changes. I already tried logging in and out but didn't help.
![Capture](https://user-images.githubusercontent.com/54218623/69634614-99968d80-1020-11ea-96a5-9ea7ccd7b6ee.PNG)

### Additional context

OS- Windows 10
gihub desktop version- 2.2.3

**Comment by billygriffin** [comment]
Hi @krunalpatelflynn, thanks for the issue. This is something we've seen come up before, and here's the explanation of what's likely happening and how to get it fixed: https://github.com/desktop/desktop/blob/development/docs/known-issues.md#certificate-revocation-check-fails---3326

Let us know if that doesn't solve it!
