### ISSUE TITLE
hooks are not working

### ISSUE THREAD

**Issue by vjrjsh** [desktop/desktop#8707]
### Describe the bug

hooks are not working

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Go to 'Repository'
2. Click on 'Merge
![image](https://user-images.githubusercontent.com/58219825/69637105-fd02d880-107d-11ea-8cf1-9de673b386ad.png)
'

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by billygriffin** [comment]
Hi @vjrjsh, thanks for the issue and sorry you're running into problems. Please fill out the rest of the template, specifically OS version, Desktop version, and Logs so we can work with you to understand what's going on. Thanks!

**Comment by tierninho** [comment]
@vjrjsh  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
