### ISSUE TITLE
فثسف

### ISSUE THREAD

**Issue by medhachoum** [desktop/desktop#8709]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by medhachoum** [comment]
sory i opened this issue by mistake , im new in github :)

**Comment by tierninho** [comment]
All good 😄 Thanks for using GitHub and Desktop!!
