### ISSUE TITLE
Support multiple remotes

### ISSUE THREAD

**Issue by jgurtz** [desktop/desktop#8710]
### Describe the feature or problem you’d like to solve

Currently there is no way to update the local repository without re-creating a fork of the master repo. Would like to be able to add "main" repository for ease in keeping local and fork repos up-to-date

### Proposed solution

Be able to stay in the application rather than needing to know how and switch to CLI to handle multiple repos

### Additional context

Other issue requesting the same feature closed with no explanation

**Comment by tierninho** [comment]
@jgurtz Is this what you were thinking https://github.com/desktop/desktop/issues/2978, as yours appears to be a duplicate issue?

**Comment by jgurtz** [comment]
Ha, I had followed one req which was a dup of another which was claimed to be "the one" but which in fact was closed. So ya, I'll pile on the real one 👍

**Comment by steveward** [comment]
@jgurtz just to clarify one thing -- GItHub Desktop does support `upstream` remotes. If you look in the branches list you should see `upstream/<branch_name>`, which you can select when you want to update your local repository with the upstream repository. Is that possibly what you are looking for?

**Comment by jgurtz** [comment]
I think that is the idea, yes. I've been looking to help out some team members at school who are new to git/github. I am using the cli and generally set "upstream" to be a remote "main" and that was not appearing anywhere so thought it was not possible to have multiple remotes. I discovered "fork" so they'll probably just use that (or get on board with the cli 🥇 ).
