### ISSUE TITLE
Show warnings when commit message character-limit is reached.

### ISSUE THREAD

**Issue by m-ahmadi** [desktop/desktop#8711]
I think it's useful to put warning text around the commit message text inputs when the commit message title or description reaches the 50/72 limit.
You know just like VS or VS Code does:
![1](https://user-images.githubusercontent.com/16363767/69731295-e6708600-113e-11ea-9665-e8b1338df141.png)
![2](https://user-images.githubusercontent.com/16363767/69731304-e96b7680-113e-11ea-90f9-d7a21016865a.png)
But in Github Desktop it shows like this:
![3](https://user-images.githubusercontent.com/16363767/69731678-934b0300-113f-11ea-9b6d-5333a006a29c.png)

**Comment by niik** [comment]
Hi @m-ahmadi, thanks for opening this. It looks like this might be same issue as #2055 so I'm going to close this in favor of that one.

**Comment by kt462** [comment]
Okay thank ypu5
