### ISSUE TITLE
OpenCV Error: Assertion failed//// in cv::Mat::at ////file = \include\opencv2\core\mat.inl.hpp, line 1096

### ISSUE THREAD

**Issue by DaseotJin** [desktop/desktop#8713]
first of all,  I'm just start to learn coding so plz understand though code is messy.
hi, I'm making some code, until when I saw error message.
here's the message on console box.
OpenCV Error: Assertion failed (((((sizeof(size_t)<<28)|0x8442211) >> ((traits::Depth<_Tp>::value) & ((1 << 3) - 1))*4) & 15) == elemSize1()) in cv::Mat::at, file c:\users\~PATH~\include\opencv2\core\mat.inl.hpp, line 1096

and this is what I found something wrong in my code
`#include <iostream> 
#include <string> 
#include <opencv2/opencv.hpp>
#include <opencv/cv.h> 
#include <opencv/cxcore.h> 
#include <opencv/highgui.h> 

cv::Mat3b pcrop_L;
cv::Mat3b pcrop_R;

cv::Mat CROP_L()
{
	cv::Mat bgr_L[3];
	cv::Mat3b img_L = cv::imread("C:\\Users\\~PATH~\\british_L.png");

	cv::Rect roi_L(0, 0, 383, 487);

	pcrop_L = img_L(roi_L);

	split(pcrop_L, bgr_L);

	//cv::imshow("Original_L", img);
	cv::imshow("Crop_L", pcrop_L);
	//cv::waitKey();
	return bgr_L[3];

	//cv::cvtColor(crop_L, gray_L, CV_RGB2GRAY);

}

cv::Mat CROP_R()
{
	cv::Mat bgr_R[3];

	cv::Mat3b img_R = cv::imread("C:\\Users\\~PATH~\\british_R.png");

	cv::Rect roi_R(0, 0, 383, 487);

	pcrop_R = img_R(roi_R);

	split(pcrop_R, bgr_R);
	
	//cv::imshow("Original_R", img);
	cv::imshow("Crop_R", pcrop_R);
	//cv::waitKey();
	return bgr_R[3];

	//cv::cvtColor(crop_R, gray_R, CV_RGB2GRAY);
}

cv::Mat sub_img(cv::Mat &bgr_L, cv::Mat &bgr_R)
{
	cv::Mat merged_img;
	int width = pcrop_L.size().width;
	int height = pcrop_L.size().height;

	//cv::Mat output(height, width, CV_8UC3);
	cv::Mat output[3];

	

	for (int y = 0; y < height; y++)
	{
		for (int x = 0; x < width; x++)
		{
			//output.at<uchar>(y, x) = abs(crop_L.at<uchar>(y, x) - crop_R.at<uchar>(y, x));
			
			output[0] = abs(bgr_L.at<cv::Vec3b>(y, x)[0] - bgr_R.at<cv::Vec3b>(y, x)[0]);
			output[1] = abs(bgr_L.at<cv::Vec3b>(y, x)[1] - bgr_R.at<cv::Vec3b>(y, x)[1]);
			output[2] = abs(bgr_L.at<cv::Vec3b>(y, x)[2] - bgr_R.at<cv::Vec3b>(y, x)[2]);
		}
	}
	merge(output, 3, merged_img);

	//cv::Mat output = crop_L - crop_R;

	cv::imshow("sub_img", merged_img);
	cv::waitKey();

	return merged_img;
}

int main()
{
	cv::Mat lastcrop_L = CROP_L();
	cv::Mat lastcrop_R = CROP_R();
	sub_img(lastcrop_L, lastcrop_R);

	return 0;

}`

I guess sonething wrong with inside of double for construction
and here is the line 1096 of mat.inl.hpp

`template<typename _Tp> inline
_Tp& Mat::at(int i0, int i1)
{
    CV_DbgAssert(dims <= 2);
    CV_DbgAssert(data);
    CV_DbgAssert((unsigned)i0 < (unsigned)size.p[0]);
    CV_DbgAssert((unsigned)(i1 * DataType<_Tp>::channels) < (unsigned)(size.p[1] * channels()));
    CV_DbgAssert(CV_ELEM_SIZE1(traits::Depth<_Tp>::value) == elemSize1());
    return ((_Tp*)(data + step.p[0] * i0))[i1];
}`

I searched on google but I couldn't solve this problem.

**Comment by outofambit** [comment]
Hi @DaseotJin! the issues for this repository are limited to those with [GitHub Desktop](desktop.github.com). It sounds like your issue is separate from Desktop, so I'm going to close it, but let us know if that's wrong and we can re-open. Thank you!
