### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by HelloXiaofeng** [desktop/desktop#8715]
### Describe the bug

The git process easily conflicts with other programs, leading to the creation of a large number of git processes.

There is no way to find the source of the problem due to busy work rates. I can only restart the computer temporarily, but according to network resources, many people have encountered git memory leaks.

### Version & OS

win10 x64 1909

![QQ截图20191128073150](https://user-images.githubusercontent.com/20350048/69766096-7f3fe980-11b1-11ea-9b44-a9789685cc92.png)
![QQ截图20191128073200](https://user-images.githubusercontent.com/20350048/69766098-80711680-11b1-11ea-84d8-dc32af8c7a61.png)

**Comment by outofambit** [comment]
Hi @HelloXiaofeng! Thanks for filing this issue. I'm sorry you're having this problem. Could you please include what version of GitHub Desktop you are using? If you can attach a log file too that would be super helpful. Thank you!

**Comment by tierninho** [comment]
@HelloXiaofeng  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by chasse20** [comment]
This one exists when a user does not present the proper credentials for accessing a repo. This one actually falls within Dugite for not handling timeouts.

**Comment by chasse20** [comment]
Found an easy way to replicate:

1. Delete your test repo credentials from Windows Credentials Manager
2. In the test repo, create a new branch
3. Delete the branch you just created (repeat a few times to see the full effect)
4. Exit Github Desktop
5. Look in the Task Manager for Git processes still loaded

**Comment by tierninho** [comment]
@chasse20 Thanks for the added color on this! 

@desktop/core Does it make sense to add a preflight check for this?

**Comment by chasse20** [comment]
Caveat to this: I was testing on an inhouse bitbucket repo and not a github one.

LFS is especially impacted by this auth prompt leak since it appears the sub-process (git-lfs.exe) isn't respecting a **GIT_TERMINAL_PROMPT** at all. I have a ticket on Dugite to see if anyone there ran across it. This only impacts commands that require authorization.
