### ISSUE TITLE
Facing AskPass issue

### ISSUE THREAD

**Issue by smrity69** [desktop/desktop#8717]
While fetching, pulling or pushing from GIT lab, I am getting "Unable to read askpass response" error along with "Terminal prompts disabled" error.

**Comment by niik** [comment]
Hi @smrity69, sorry to hear you're having problems with GitHub Desktop. Please take a look at our [known issues document](https://github.com/desktop/desktop/blob/ed4e0523cb6b16f18e2d0a2f754022da22e2060c/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789) which includes a section about ask pass errors that hopefully is of use to you.

If your issue isn't resolved by following the steps in that document please open a new issue and fill out the entire issue template
