### ISSUE TITLE
Proxy Connection issue

### ISSUE THREAD

**Issue by Pretuer** [desktop/desktop#8729]
### Describe the bug

When using the software it seems like there is no way to put in a Proxy server (IP, Port, Username, and Password)

### Version & OS
Version 2.2.3
Windows 10 Home edition

### Steps to reproduce the behavior
When using a proxied network.
1. Go to 'File'
2. Click on 'Options'
3. Scroll down to 'Sign into Github'

### Expected behavior

I expected that it would log me in as Normal

### Actual behaviour

It said "unable to fetch authenticated user" and gave me a few error codes

### Screenshots
![image](https://user-images.githubusercontent.com/39959123/69909935-e52bab80-1413-11ea-908a-f32390a972d0.png)
![image](https://user-images.githubusercontent.com/39959123/69909941-f70d4e80-1413-11ea-893c-707cab23880a.png)

### Logs
[2019-12-01.desktop.production.log](https://github.com/desktop/desktop/files/3907847/2019-12-01.desktop.production.log)

**Comment by niik** [comment]
Hi @Pretuer, sorry to hear you're having problems. GitHub Desktop usually picks up the proxy settings from the Windows system level configuration. That doesn't appear to be the case for you. Can you take a look at the proxy settings in Windows and see if they're accurately configured to work with your proxy?

<img width="830" alt="image" src="https://user-images.githubusercontent.com/634063/69968221-3e7e0280-151a-11ea-823b-6825f7258eb4.png">

**Comment by Pretuer** [comment]
![image](https://user-images.githubusercontent.com/39959123/70021510-06ba9d80-15a2-11ea-8efa-4cef44e8e9c9.png)
Yes the setting is on but I am still facing the problem

**Comment by niik** [comment]
Hi @Pretuer, thanks for getting back to us so quickly.

I'm curious if you've had to manually enter your proxy details in any other application on your system. Could you try running the following command in PowerShell:

```
[System.Net.WebProxy]::GetDefaultProxy().GetProxy('https://github.com').ToString()
```

That should print either `https://github.com` if the system level proxy setting isn't automatically configured or something like `https://proxy.yourcompany.com:8888/` if it is automatically configured.

**Comment by niik** [comment]
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.
