### ISSUE TITLE
Checksum & GPG verification missing

### ISSUE THREAD

**Issue by beerisgood** [desktop/desktop#8730]
No [Checksum](https://en.wikipedia.org/wiki/Checksum) nor [GPG verification](https://www.dewinter.com/gnupg_howto/english/GPGMiniHowto-5.html) stuff is provided for binarys which both increase security for user and the project itself.

Also with GPG you can [sign your commits](https://help.github.com/en/github/authenticating-to-github/signing-commits) which is important for such projects!

For checksum SHA2-512 would be good while SHA2-256 is **still** secure.
SHA1 and less stuff like MD5 is already broken

**Comment by niik** [comment]
Hi @beerisgood, thanks for your suggestion. The GitHub Desktop binary as well as the installer is signed using a code signing certificate issued to the GitHub organization. If you're on Windows you can right click on the binary file in explorer and select 'Properties' to verify that the binary is signed by us.

<img width="422" alt="image" src="https://user-images.githubusercontent.com/634063/69967111-0e356480-1518-11ea-8662-66e8573883c2.png">

<img width="771" alt="image" src="https://user-images.githubusercontent.com/634063/69967637-1f32a580-1519-11ea-86fb-b7e771d089f1.png">


We also sign our macOS binaries, see [How to Show & Verify Code Signatures for Apps in Mac OS X](http://osxdaily.com/2016/03/14/verify-code-sign-apps-mac-os-x/) for more details on that.

Given that the code signing certificate already provide assurance that the binary is provided by us (GitHub, Inc), as well as verifying the integrity of the file itself in combination with us only delivering the binaries via HTTPS under certificates issued to the GitHub org we believe that our current approach to signage and integrity is sufficient.
