### ISSUE TITLE
I can't upload files to my branch using Github desktop.

### ISSUE THREAD

**Issue by Pedro-H-O-F** [desktop/desktop#8737]
I'm new in github, so I believe this is a basic question. Using github on Google Chrome I created a Branch from a project of the company where I work. I commited some files, but the ones bigger than 25MB couldn't be uploaded. So I was told to try to upload the bigger files using Github desktop. However, when I open the desktop version I can't access my branch (or any other). The only thing I can do is clone the master to my computer. What should I do to commit the files?

![GithubProblem1](https://user-images.githubusercontent.com/58430695/69965968-2b583c00-14f4-11ea-8292-0249a221cd86.jpg)

**Comment by niik** [comment]
Hi @Pedro-H-O-F, please take a look at our [tutorials and documentation for GitHub Desktop](https://help.github.com/en/desktop), the section called [Contributing to projects with GitHub Desktop](https://help.github.com/en/desktop/contributing-to-projects) outlines the steps you need to take to get your files committed and uploaded. In short what you need to do is:

1. [Clone the repository](https://help.github.com/en/desktop/contributing-to-projects/cloning-a-repository-from-github-desktop)
2. [Switch from master to your branch](https://help.github.com/en/desktop/contributing-to-projects/switching-between-branches)
3. Open the repository in Explorer and add the files you'd like to include
4. [Select and commit the files](https://help.github.com/en/desktop/contributing-to-projects/committing-and-reviewing-changes-to-your-project#2-selecting-changes-to-include-in-a-commit)
5. [Write a commit message and push your changes](https://help.github.com/en/desktop/contributing-to-projects/committing-and-reviewing-changes-to-your-project#3-write-a-commit-message-and-push-your-changes)

I'm going to close this issue as it's not referring to a bug or a feature request in the product itself but feel free to comment if you run into any problems and we'll do our best to help you out.
