### ISSUE TITLE
Desktop version of GitHub

### ISSUE THREAD

**Issue by AleksaIvkovic** [desktop/desktop#8742]
### Describe the bug
Application isn't able to connect to github.com

### Version & OS

Version 2.2.3 , Windows 10

### Steps to reproduce the behavior

When i try to clone repository, it asks for my username and password, but each time i get a message that github.com can't be reached 

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@AleksaIvkovic Thanks for filing this. Possible to include your logs and any screenshots?

**Comment by AleksaIvkovic** [comment]
[image: Screenshot_4.png]
here is a screenshot, where can i find the logs that i need

**Comment by steveward** [comment]
@AleksaIvkovic to access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by tierninho** [comment]
@AleksaIvkovic  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
