### ISSUE TITLE
Where Does Desktop Store Repository Information?

### ISSUE THREAD

**Issue by JosephTLyons** [desktop/desktop#8744]
This is not a bug.  I'm trying to find information about how GitHub Desktop stores its local repository information.  I"m assuming it is some sort of file on the computer that holds all the information about each repo.  I've upgraded computers and instead of automatically moving everything over using one of the Apple migration tools, I'm doing a clean install of the system.  With that being said, I have hundreds of repos in GitHub Desktop - adding them back in manually is a bit of a pain.  My new MacBook has my repos in the exact same locations as on my old machine, so I assume if there was a file holding the repository information, I could potentially drag it over onto my new system and Desktop would then instantly know of all my repos?  Any information dealing with this would be greatly appreciated.

**Comment by niik** [comment]
Hi @JosephTLyons,

GitHub Desktop stores repository data in IndexedDB, the data files of which are usually stored (on macOS) under `~/Library/Application\ Support/GitHub\ Desktop/` alongside a ton of other data that Electron (or Chromium really) creates. Copying that folder over to your new machine could work but it's not something we've tested or support. One thing that I know for certain won't be copied over correctly is your account information. We store the account name in localStorage (which resides in the same directory structure as the IndexedDB files) but the token is stored securely in keychain and won't be copied over so if you attempt to copy the directory over make sure you sign out and back in again in the app to avoid any problems with Desktop believing you're signed in when in reality you're not.

Lastly I will leave you with a tip that I'm not sure applies to your situation or not which is that you can select more than one repository directory in Finder and drag and drop them all onto GitHub Desktop to add more than one repository in one fell swoop.

Hope that helps!

**Comment by JosephTLyons** [comment]
Thank you very much for the helpful information!  It is much appreciated!
