### ISSUE TITLE
Expose specific git http settings in UI

### ISSUE THREAD

**Issue by jasonmacgowan** [desktop/desktop#8748]
### Describe the feature or problem you’d like to solve

When using `schannel` in a corporate proxy environment, `git` operations may fail when attempting to check the TLS certificate of the remote server against a revocation list (see [known issues](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#certificate-revocation-check-fails---3326)).

Implementing the workaround as described requires manually editing a `gitconfig` file which may be challenging for some users who are not used to modifying configuration files.  This file also expects unix-style line endings which may be difficult to do in a Windows environment.

### Proposed solution

Expose `git` configuration settings `http.sslBackend` and `http.schannelCheckRevoke` in GitHub Desktop settings, perhaps under the existing "git" or "advanced" tab.

**Comment by niik** [comment]
Hi @jasonmacgowan, thanks for opening this.

As stated in the known issues document we don't recommend turning off certificate revocation checks except as a temporarily escape hatch. Certificate revocation is an important piece to ensuring secure communications which makes me a little bit hesitant to include a setting to toggle this in the preferences dialog. If we do decided to implement something like that I would like for us to think about cautioning the user when they turn it on to prevent users accidentally turning it on/off as a general network troubleshooting step.

I'd like to understand under what scenario having a corporate proxy would prevent certificate revocation checks. I was under the impression that as long as the system level proxy configuration (i.e. OS-level setting) was properly configured then Windows would ping the revocation servers using that proxy. [This SO answer](https://stackoverflow.com/a/53090169/2114) provided an interesting point of view and is an argument in favor of us making it easier to opt out of revocation checks.

We're currently discussing two H2 initiatives which relate to this issue. The first is an overall support for proxies (https://github.com/desktop/desktop/issues/2789), the second is a redesign of the preferences dialog. I'd like to tee up a discussion around this for the next Desktop product meeting (in two weeks) to get some more input before we move forward with this.

**Comment by jasonmacgowan** [comment]
@niik I am still actively troubleshooting the nature of the revocation check failure during the clone process and do not have a great answer for why it fails in some proxy environments but not in others.  I agree in theory the revocation check would go through the proxy and should just work.  When I run it down, I'll update here.

The spirit of this issue is aligned with #2789, where a Desktop user needs to make an advanced git configuration change where it is difficult to do so.

Perhaps the right solution for this and requests like it is a lite .gitconfig editor inside Desktop?  I think that's a good balance between making the configuration accessible and making it more difficult than unchecking a box to turn off a security feature.

What did you have in mind?

**Comment by niik** [comment]
Gonna close this one now that #9188 has landed. Thanks for opening this and pushing us to do something in this space @jasonmacgowan. We have a much better understanding of the problem now and we're hoping that this option will only be a temporary measure as we're working on implementing proper best-effort revocation checking in https://github.com/curl/curl/pull/4981.

Note that the option to turn off revocation checking will only appear if the specific revocation failure error has been observed by GitHub Desktop. More details in #9188.

**Comment by jasonmacgowan** [comment]
This is a great :ship:!
