### ISSUE TITLE
How to view all repositories 

### ISSUE THREAD

**Issue by montao** [desktop/desktop#8749]
### Describe the feature or problem you’d like to solve

Cannot understand how to view all repositories. 

### Proposed solution

It should be easy to view all repositories. 
### Additional context

I worked with one repo. Now I want to view all my repositories but the way to get back to the list of all repositories is nowhere

**Comment by niik** [comment]
Hi @montao, the list of all repositories that you've added to your Desktop application can be found by clicking on the repository button in the toolbar

![image](https://user-images.githubusercontent.com/634063/70227293-a028b180-1752-11ea-872f-21f5dc199ee3.png)

That will expand a side bar which lists all the repositories you've cloned or added to GitHub Desktop thus far. If you wish to clone a repository that you haven't previously cloned that can be found either in the menu (`File` -> `Clone repository`) or in the repository sidebar by clicking on the `Add button`

![image](https://user-images.githubusercontent.com/634063/70227417-d7975e00-1752-11ea-8c1f-623d0102de95.png)

I'm going to close this issue now but if I've misunderstood what you're looking for please let me know and we'll reopen or continue the conversation.

**Comment by saikat1978** [comment]
This is the worst UI I have ever seen. Once I have cloned one repo, the UI is not allowing me to navigate to the repo list which are present in github.com, but not cloned in my local machine. Why isn't there a feature like a "Home" button where you can navigate to, to see all the repos which have not been cloned to the local machine yet?

**Comment by Ari-O-Alt** [comment]
The new UI is horrible. I thought I'll give up on using the CLI but after 10 minutes on Github Desktop I uninstalled the app and went back to command line.

**Comment by bbb5317** [comment]
> Hi [@montao](https://github.com/montao), the list of all repositories that you've added to your Desktop application can be found by clicking on the repository button in the toolbar
> 
> ![image](https://user-images.githubusercontent.com/634063/70227293-a028b180-1752-11ea-872f-21f5dc199ee3.png)
> 
> That will expand a side bar which lists all the repositories you've cloned or added to GitHub Desktop thus far. If you wish to clone a repository that you haven't previously cloned that can be found either in the menu (`File` -> `Clone repository`) or in the repository sidebar by clicking on the `Add button`
> 
> ![image](https://user-images.githubusercontent.com/634063/70227527-0a415680-1753-11ea-8f40-8390ec0efa7f.png)
> 
> I'm going to close this issue now but if I've misunderstood what you're looking for please let me know and we'll reopen or continue the conversation.

**Comment by bbb5317** [comment]
The answer does not answer the question. How to view all repositories - not all local repositories. All of them not only the local ones. I also can't find that option.
