### ISSUE TITLE
Credentials reappearing after closing the login dialogue 

### ISSUE THREAD

**Issue by douglasmacdonald** [desktop/desktop#8751]
I found it impossible to remove credential information from my system as it would reappear in Window Credential Manager when this dialogue was closed.

![login](https://user-images.githubusercontent.com/12778156/70244245-b186b380-177c-11ea-9146-cb39b942cf4a.png)

I was trying to remove my information from a Virtual Machine before cloning it for someone else. 

After this, as expected, when you pull/push the password dialogue appears.

Not expected, when you close the dialogue **without entering** anything the previously deleted credentials appear in Window Credential Manager. Then, you can pull/push as desired.

**Comment by steveward** [comment]
👋 @douglasmacdonald this repository is for GitHub Desktop. For specific issues with the Git Credential Manager for Windows please open an issue in their repository:

https://github.com/microsoft/Git-Credential-Manager-for-Windows
