### ISSUE TITLE
Error while connecting github repo to jenkins

### ISSUE THREAD

**Issue by Deepikagn** [desktop/desktop#8759]
I am trying to coonect github to jenkins server, when i type in the url of the repository(which is my own), soon the error pops up "Failed to connect to repository : Error performing git command: git.exe ls-remote -h https://github.com/Deepikagn/example.git HEAD". I haven't changed any default settings. I gave the credentials too in jenkins. Is there anything that you could help me out with?

**Comment by niik** [comment]
Hi @Deepikagn, this is the repository for GitHub's open source desktop client GitHub Desktop I'm afraid we can't help with Jenkins-related issues. The only thing I can suggest is consulting the [jenkins documentation](https://jenkins.io/solutions/github/). If you have a question about GitHub Desktop specifically, we're happy to take a look at it, but we can't help with issues not related to Desktop.
