### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by rlbns** [desktop/desktop#8760]
### Describe the bug

I'm trying to clone a repository at https://github.com/actusfrf/actus-core.git using GitHub desktop. When promted for github.com credentials I enter my user name (rlbns) and password and it says I can't be found. I have no problem signing in to github.com in a browser.

The repository I want to clone is also password protected. I tried those credentials and it didn't work either.

### Version & OS

Windows v2.2.3

### Steps to reproduce the behavior

explained above

### Expected behavior

I want to clone the repository.

### Actual behavior

Could not log in.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@rlbns thanks for the report. Can you verify that you are logged in to your GitHub account in GitHub Desktop by going to `File` > `Options` > `Accounts`?

It would also be helpful if you could share the log file from GitHub Desktop. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

**Comment by rlbns** [comment]
Yes, it does show me as logged in - what a surprise.
[2019-12-06.desktop.production.log](https://github.com/desktop/desktop/files/3933659/2019-12-06.desktop.production.log)

**Comment by steveward** [comment]
@rlbns thanks for sharing the log. it looks like you do not have the correct permissions to push to that repository, which is causing the authentication failure. You will need to contact someone in the `actusfrf` org to grant you access, which should resolve this issue. Let me know if that doesn't get things working.
