### ISSUE TITLE
GitHub desktop should be able to prompt for SSH key passphrase

### ISSUE THREAD

**Issue by anqinxu** [desktop/desktop#8761]
When we followed the instructions for setting up SSH keys, that involves making a passphrase. Then when we started using Github desktop, it will not clone or pull the repos. It gives error message about authentication failure. It suggested logging in again and that didn't help. It seems like the desktop app does not prompt for SSH key passphrase when it should.

Then we created a new SSH key without passphrase and the problem was solved.

We know that there could be some Windows ssh-agent workarounds that we could be missing but it would be cool if the app just prompts for passphrase and do the right thing. 😄

**Comment by kevincantu** [comment]
A screenshot of the error when trying to fetch:
* with a repo using an SSH URL
* when you have a non-empty SSH passphrase:
![githubdesktop-not-finding-ssh-agent](https://user-images.githubusercontent.com/27978219/70368891-7ca25b80-1865-11ea-885e-bf07e32c209f.png)

One ssh-agent workaround we found requires:
* configuring your .bashrc to always restart the ssh-agent ([like so](https://help.github.com/en/github/authenticating-to-github/working-with-ssh-key-passphrases)),
* starting Git Bash, and
* launching GitHub Desktop from within Git Bash.
And never ever starting GitHub Desktop from the desktop icon, etc!  🙀 

It'd be nice if it just prompted, like @anqinxu suggests.  😺

**Comment by steveward** [comment]
Thanks for contributing @anqinxu. We have a collection of known SSH limitations catalogued in https://github.com/desktop/desktop/issues/2579 (including the SSH passphrase issue), so I'm going to close this issue out in favor of that one and add your feedback there. 

@kevincantu thanks for sharing how you were able to get things working -- that's helpful!

**Comment by kevincantu** [comment]
I think it's more severe than the part you've quoted there, @steveward: the only way to run GitHub Desktop if you're using SSH keys with passphrases is to open Git Bash, set up ssh-agent, and run %appdata%\whatever\whatever\GitHubDesktop.exe.

Starting it by clicking the icons installed by the installer isn't sufficient, and this is not obvious.

**Comment by steveward** [comment]
@kevincantu it sounds like your `ssh-agent-PID` isn't getting picked up by GitHub Desktop -- you should be able to just run `github` from the command line rather than using the `%AppData%` path to fix this. I'm working on a SSH guide for GitHub Desktop where I'll make a note of this.

**Comment by Bubbleinpit** [comment]
On Win10, you can install open ssh and try this to setup ssh-agent: https://code.visualstudio.com/docs/remote/troubleshooting#_setting-up-the-ssh-agent

**Comment by gpbonillas** [comment]
> A screenshot of the error when trying to fetch:
> 
> * with a repo using an SSH URL
> * when you have a non-empty SSH passphrase:
>   ![githubdesktop-not-finding-ssh-agent](https://user-images.githubusercontent.com/27978219/70368891-7ca25b80-1865-11ea-885e-bf07e32c209f.png)
> 
> One ssh-agent workaround we found requires:
> 
> * configuring your .bashrc to always restart the ssh-agent ([like so](https://help.github.com/en/github/authenticating-to-github/working-with-ssh-key-passphrases)),
> * starting Git Bash, and
> * launching GitHub Desktop from within Git Bash.
>   And never ever starting GitHub Desktop from the desktop icon, etc!  🙀
> 
> It'd be nice if it just prompted, like @anqinxu suggests. 😺

Thanks! It helped me a lot.

**Comment by mckoss** [comment]
I have to do a similar thing using GitBash on Windows 10.

My .gitbashrc is (which must be run via $ source .gitbashrc if not included in shell start):

```
SSH_ENV="$HOME/.ssh/environment"

function start_agent {
    echo "Initializing new SSH agent..."
    ssh-agent > "$SSH_ENV"
    chmod 600 "$SSH_ENV"
    . "$SSH_ENV" > /dev/null
    ssh-add $HOME/.ssh/id_rsa
    ssh-add -l
}

if [ -z "$SSH_AGENT_PID" ]; then
    start_agent
else
    echo "Agent already running..."
fi
```

and then I put this script in my path to run githubdesktop:
```
#!/bin/bash
nohup $HOME/AppData/Local/GitHubDesktop/GitHubDesktop.exe >/dev/null 2>&1 &
```

**Comment by hardysim** [comment]
This is working fine (https://github.com/desktop/desktop/issues/8761#issuecomment-822862340). But it seems that GitHub Desktop already adds itself as `github` to the path:

```
$ which github
/c/Users/me/AppData/Local/GitHubDesktop/bin/github
```

**Comment by flavio-marchi** [comment]
Still having this issue, starting Github Desktop with Git Bash and entering the passphrase with every action made in Github Desktop isnt a solution. Has noone tackled this issue yet?

Without a detour obviously, I'll propably try the `.bashrc` "solution" in the meanwhile.

**Comment by steveward** [comment]
@FlavioSB this is being addressed in https://github.com/desktop/desktop/pull/12756.

**Comment by flavio-marchi** [comment]
@steveward Looks promising, thanks!

**Comment by sergiou87** [comment]
Latest beta should include this already 😄

**Comment by billygriffin** [comment]
We released this to production this week, so please let us know how it's working!

**Comment by ActionKeith** [comment]
Hi @billygriffin -- Eagerly awaiting.
Any high level guidance on how much time delay to expect for MacOS?

**Comment by sergiou87** [comment]
@keithhelfrich version 2.9.3 already has support for this on macOS. Is it not working for you? 😳

**Comment by laukstein** [comment]
In Windows 10 you can try solution explained in https://superuser.com/a/1296046/473500
![image](https://user-images.githubusercontent.com/183966/147971353-716caf9d-bac3-4052-b823-f3aba73fd32f.png)

**Comment by ActionKeith** [comment]
When will it work correctly for MacOS?

Thank you.

**Comment by sergiou87** [comment]
@keithhelfrich version 2.9.3 already has support for this on macOS. Is it not working for you? 😳

**Comment by nochet2211** [comment]
Version 3.0.0 ....MacOs Monterey..No prompts for me :(

**Comment by ByteToHex** [comment]
Hi, would just like to chime in- as of 6 Feb 2025, Github Desktop encounters an infinite loop of 'cloning repository' when a SSH key with passphrase is used. Unsure if there are any workarounds- no prompts are appearing on my end.

I am on Windows.

**Comment by josephtarbit** [comment]
> Hi, would just like to chime in- as of 6 Feb 2025, Github Desktop encounters an infinite loop of 'cloning repository' when a SSH key with passphrase is used. Unsure if there are any workarounds- no prompts are appearing on my end.
> 
> I am on Windows.

Still getting this issue too
