### ISSUE TITLE
updated file didn't sync

### ISSUE THREAD

**Issue by gikirima** [desktop/desktop#8762]
after I make some changes to an HTML5 page, the changes wasn't listed. and if I ignore/remove the changes, it will revert back to the old version before I make some changes.

**Comment by kt462** [comment]
Remove

**Comment by steveward** [comment]
@gikirima can you share a few more details with steps you are taking when experiencing this issue? Is the problem specifically that when you make changes to a certain file those changes are not appearing in GitHub Desktop under the `Changes` tab?

I would first recommend checking to see if your repository has a .gitignore file, which could be causing the changes to specific files to not appear. See [the ignoring files help article](https://help.github.com/en/github/using-git/ignoring-files) for more information about how that works.

**Comment by gikirima** [comment]
It seems that there was a problem in windows 10 connection settings. After restarting my PC, it's now updated properly.
Oh, and I hope the github desktop app support case-sensitive for syncing. I'm sorry for your inconvenience.
