### ISSUE TITLE
Push hangs using plink

### ISSUE THREAD

**Issue by Zannick** [desktop/desktop#8765]
### Describe the bug

Pushing may hang indefinitely if using plink. Having just set up plink (so Pageant will allow me to push both from Github Desktop as well as Git Bash), I get an error message in Git Bash:

```
The server's host key is not cached in the registry. You
have no guarantee that the server is the computer you
think it is.
The server's rsa2 key fingerprint is:
<github server's rsa fingerprint>
If you trust this host, enter "y" to add the key to
PuTTY's cache and carry on connecting.
If you want to carry on connecting just once, without
adding the key to the cache, enter "n".
If you do not trust this host, press Return to abandon the
connection.
Store key in cache? (y/n) 
```

In Github Desktop, pushing has hung with a status of "connection." which is exactly the penultimate line in the same error message on the commandline.

### Version & OS

Windows 10
Github Desktop 2.2.3

### Steps to reproduce the behavior

1. Set up SSH keys and add key to Pageant.
2. Download plink from putty website
3. Set GIT_SSH to path to plink.exe
4. Attempt to push from Github Desktop.

### Expected behavior

Prompt or error, or alternate way of ending the push attempt.

### Actual behavior

Hanging forever. GitHub Desktop must be closed to recover.

### Screenshots

![screenshot of "connection."](https://user-images.githubusercontent.com/518709/70382998-cd27c080-191a-11ea-90e9-f1398747cad4.png)

### Logs

There are no logs other than for background actions.

### Additional context

The commandline `git push` did not accept any input either (not forwarding input to plink, I guess), so I had to resolve this by manually running plink against github to store the key in the cache.

**Comment by steveward** [comment]
@Zannick thanks for contributing. Is there a specific reason you are wanting to use PuTTY/Pageant over OpenSSH? 

I'm going to close this issue out and add it to the body of https://github.com/desktop/desktop/issues/2579 where we are tracking a broader range of SSH issues.

**Comment by Zannick** [comment]
Pageant is how I managed my SSH keys on Windows when I first set up TortoiseHG for other work; I haven't tried using an openssh key agent yet. I may eventually, of course, but I was concerned that there might also be an issue with the push command hanging on input. (That might actually be a git issue though.)
