### ISSUE TITLE
Add toggle word wrap in Changes pane.

### ISSUE THREAD

**Issue by info170** [desktop/desktop#8766]
It will be more convenient to see changes.
You can place it in View or Preferences menu.

**Comment by tierninho** [comment]
@info170 Thank you for the suggestion. Can you provide more details on this idea, like how does it affect your workflow and what problems you face with it not being there now? The more information we have, the better decisions we can make when it comes to adding new features.

**Comment by info170** [comment]
Thanks for the answer. It just affects the usability of the user interface.
If the lines of code are long - they are transferred to the next line, and
the user sees at the left  the tails of the lines, which is inconvenient.

пн, 9 дек. 2019 г. в 21:01, Tiernan L <notifications@github.com>:

**Comment by outofambit** [comment]
Hi @info170! We've talked about this previously in https://github.com/desktop/desktop/issues/7136. This UI has been shipped for a long time with minimal feedback like this, so it's unlikely that we'll prioritize this work. I'm going to close this issue, but we're happy to revisit this if it becomes a more significant pain point. Thank you!
