### ISSUE TITLE
Preferences redesign

### ISSUE THREAD

**Issue by ampinsk** [desktop/desktop#8774]
Since we decided to add the new preference in #7746, we realized we're running out of room in our current preferences dialog. To accommodate this new preference and future new ones, we've decided to redesign the navigation and rearrange some tabs. 

We noted this incorporated three big changes, not including the new stashing preference: 

1. New side navigation
2. Move integration preferences to its own new tab
3. Reword the confirmation dialog preferences for less redundancy

Here are all the future tab states:

### Accounts

<img width="1010" alt="Accounts@2x" src="https://user-images.githubusercontent.com/10404068/70473359-de99d580-1a9e-11ea-894f-a4bcbf8eade0.png">

### Integrations
<img width="1010" alt="Integrations@2x" src="https://user-images.githubusercontent.com/10404068/70473356-de013f00-1a9e-11ea-962e-fb689c210c17.png">

### Git Config
<img width="1010" alt="Git@2x" src="https://user-images.githubusercontent.com/10404068/70473360-de99d580-1a9e-11ea-8f7a-a2855c9c908e.png">

### Appearance
<img width="1010" alt="Appearance@2x" src="https://user-images.githubusercontent.com/10404068/70473357-de99d580-1a9e-11ea-9479-50839f35909f.png">

### Advanced

<img width="1010" alt="Advanced@2x" src="https://user-images.githubusercontent.com/10404068/70473355-de013f00-1a9e-11ea-827c-b008f9af9833.png">

This tab is where the new stashing preference will live.

cc @kuychaco

**Comment by Rexogamer** [comment]
Somewhat unrelated, but should we drop the beta tag off dark mode? Apart from a few minor issues, it’s mostly finished.
