### ISSUE TITLE
Add "Stash Changes" to changed file dropdown

### ISSUE THREAD

**Issue by shieldgenerator7** [desktop/desktop#8775]
Sometimes I have changes to files that I want to commit sometime in the future, but not right now. I would like to stash these changes manually in the Desktop App without having to use the console or switch branches.

There could be an option in the context menu for a changed file, something like "Stash Changes in Selected File", and for multiple selected files, it could say something like "Stash Changes in 5 Files".

![image](https://user-images.githubusercontent.com/3438834/70484018-6e984900-1ab8-11ea-885c-6a571974e640.png)

**Comment by tierninho** [comment]
@shieldgenerator7 Thanks for the suggestion. Although we haven't had any requests for this feature, it seems like a valid use-case. Someone from the team will circle back in a few weeks once a decision has been made. I appreciate your patience.

**Comment by shieldgenerator7** [comment]
are you a bot? your reply time is phenomenal, altho this message is a weird copy+pasta because this feature has most definitely been requested before, in various fashions.
anyways thanks for the fast reply and i hope development goes well

**Comment by tierninho** [comment]
Thanks for the suggestion. Although we haven't had any requests for this feature, it seems like a valid use-case. Someone from the team will circle back in a few weeks once a decision has been made. I appreciate your patience.

Just kidding 😛 . Not a bot 🤖 , but I did dig one instance of this request which resulted in us promising we would revisit this suggestion: https://github.com/desktop/desktop/issues/8197

**Comment by shieldgenerator7** [comment]
not gonna lie, you had me in the first half

well i appreciate you digging through and finding that. he's requesting exactly what I'm requesting. Here's hoping that the "it’s something we continue to hear from others and see workflows where it would be useful to a broader cross-section of people" condition has been met ;)

**Comment by billygriffin** [comment]
Hi @shieldgenerator7, thanks so much for the request! Would you mind describing when you're looking to stash on a particular branch without switching branches? When we built this feature, we knew we wouldn't get every use case with our implementation and we implemented it how we did intentionally trying to get at the vast majority of times when people are looking to stash. Honestly, we expected this to be a far more widespread request than it has been, so before doing anything here, we'd love to learn more about those use cases to help evaluate how many people are likely to want to use this. So I'm going to close this for now to indicate it's not something we're willing to commit to supporting yet, but we're certainly not opposed to it on principle and learning about the use cases will help us evaluate it over time. Thanks again!

**Comment by shieldgenerator7** [comment]
My general use case is that I have changed or added files that I want to commit, but I don't want to commit them without an accompanying change that makes use of them. I don't want to make that accompanying change right at the moment, but I also don't want to lose the other changes already made. I would like to stash the changes until sometime in the future when I can make the accompanying change. Stashing seems like a good option in this case. I could stash the changes for now, and then get them back when I want to make the accompanying change.
