### ISSUE TITLE
Show number of selected files

### ISSUE THREAD

**Issue by shieldgenerator7** [desktop/desktop#8776]
I sometimes have lots of changes to files, and I only want to select some of them. Sometimes it is hard to know whether I've selected only the files I want to commit or whether I've accidentally selected some files I don't want to commit.

To improve this, have a count of the number of changed files that are partially or completely selected, in addition to the count of the number of changed files.

Below is a possible way of showing this in the current UI. In this example, it is really easy to see that there are 5 selected files. But without the count, it would be really hard to tell if only these 5 are selected, or if there's other files offscreen that are also selected.

![image](https://user-images.githubusercontent.com/3438834/70484640-7eb12800-1aba-11ea-810a-b18657d73627.png)

**Comment by tierninho** [comment]
@shieldgenerator7 Thanks for the suggestion. Although we haven't had any requests for this feature, it seems like a valid use-case. Someone from the team will circle back in a few weeks once a decision has been made. I appreciate your patience.

**Comment by shieldgenerator7** [comment]
wow thanks for the fast reply!

i hope you guys can fit this in sometime :)

**Comment by nycdotnet** [comment]
If I'm not mistaken, this was in the old GitHub Desktop client.

**Comment by billygriffin** [comment]
Thanks so much for the issue @shieldgenerator7. I just want to reference that we've seen this come up once before: https://github.com/desktop/desktop/issues/2389

I'm not opposed to this type of contextual information generally - I'm just not positive this is something that enough people struggle with to warrant the level of prominence as suggested in either issue. I'm going to leave this open for others on the team (or users) to weigh in on but unless there's a different place to put this, I'm a little hesitant to change something that's currently such a prominent part of the commit workflow and potentially introduce confusion.

**Comment by nycdotnet** [comment]
@billygriffin for context, this is not strictly useful or required in typical workflows - aka edit three files, maybe commit two, move on.

This sort of contextual info is most important in one-off situations - things like when there's a lot of files changed in a batch - "Do I have the expected 301 files selected to commit that my script edited?" or things like new repos where you maybe haven't fully optimized the .gitignore yet and there might be some selected items "below the fold" that don't appear in view.  "Huh - I only expected 1 file to be selected, but the UI says 10 - oh if I scroll down, there they are!!"

So, to be clear this feature is not needed in everyday situations, but would be very welcome in certain higher-stakes situations.

In terms of confusion - this is a very tactile feature - I click something - a number updates in a reasonable way directly in response to my click in a way that makes sense.  A number increments or decrements by 1.  As such, my opinion is that it would be very unlikely to introduce confusion with the possible exception of partially committed files.

Thanks as always for this wonderful product.

**Comment by billygriffin** [comment]
@nycdotnet Thanks for the additional thoughts!

> this is not strictly useful or required in typical workflows - aka edit three files, maybe commit two, move on. ... So, to be clear this feature is not needed in everyday situations, but would be very welcome in certain higher-stakes situations.

Agreed completely - that's largely the point I was trying to make.

> In terms of confusion - this is a very tactile feature - I click something - a number updates in a reasonable way directly in response to my click in a way that makes sense. A number increments or decrements by 1. As such, my opinion is that it would be very unlikely to introduce confusion with the possible exception of partially committed files.

I generally agree that this would become more obvious as you use the product and select/deselect files. However, I also think that everything added removes prominence from the other things that are present, and I'm concerned that something like this that would always be visible would add clutter and *possibly* confusion for the 90+% use case. That's the source of my skepticism. I know on a one-off basis this stance can seem silly and pedantic, but erring on the side of caution with things like this is how we keep the product as focused and useful as possible overall.

I'm certainly not ruling this out entirely, and your thoughts are helpful. Open to others thoughts as well.

**Comment by shieldgenerator7** [comment]
@nycdotnet thats a really good point, and I generally only want it when I'm dealing with 20+ changed files. And when I'm only dealing with 5 or less changed files, I don't miss it and don't even notice it's not there. 

So maybe you can have it only show up when it's needed. Perhaps a good heuristic is whether or not there's a scroll bar. If you can't see all the changed files on screen at the same time, then it should display a count of how many changed files are selected next to the count of total changed files. But if you can see all the changed files on screen at the same time, there's no need for the count and it should disappear.

About selecting partial changes in files, I think that if a file has even one change selected, it should count towards the total the same as if all of its changes were selected. That way, the selected file count shows the number of files that will be shown in the commit log when you select the commit afterwards.

**Summary**: The selected file count should only appear when you can't see all the changed files on screen at the same time.

**Comment by nycdotnet** [comment]
@billygriffin I agree with your philosophy, and it's part of why GitHub Desktop is magic.

@shieldgenerator7 this is a good idea.

**Comment by ErVishalM** [comment]
Hi, When we can expect this feature?

**Comment by angusdev** [comment]
I think this can be closed as [this change](https://github.com/desktop/desktop/commit/75188ca0f71a4cd53513d644e9824f78ae66e5ff)  added the tooltip 
![tooltip](https://user-images.githubusercontent.com/34896/197050417-cfff9dbb-595f-44a5-a71a-cc2532b5b0f3.jpg)
