### ISSUE TITLE
Unable to clone 

### ISSUE THREAD

**Issue by rahulpandey1** [desktop/desktop#8777]
### Describe the bug

Cloning into 'C:\Users\rahul.r.pandey\Source\Workspaces\rxjs'...
fatal: unable to access 'https://github.com/ReactiveX/rxjs.git/': Failed to connect to github.com port 443: Timed out

### Version & OS
Version 2.2.3

### Steps to reproduce the behavior

1. Go to https://github.com/ReactiveX/rxjs
try to clone to github desktop application 

### Expected behavior

clone complete

### Actual behavior

error showing

### Screenshots

![image](https://user-images.githubusercontent.com/12515078/70534759-b8993180-1b81-11ea-9c2b-ba342c8ef278.png)

**Comment by steveward** [comment]
@rahulpandey1 based on the error message I'm seeing, it looks like you are behind a proxy.

If your proxy requires credentials there are some steps you can take to configure it:

1. Go to the file menu and select `Repository` > `Open in Terminal` (macOS) or `Open in command prompt` (Windows)
2. Run the following command:

`git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`

Replace `proxyuser` with your proxy username and `proxypwd` with your proxy password. Also, `proxy.server.com:8080` needs to point to the URL of your proxy server. Let me know if that does not get things working for you.

**Comment by rahulpandey1** [comment]
can i reset this config file to default.
i clone rep from multiple sources which username and pwd do i give

**Comment by steveward** [comment]
@rahulpandey1 you can directly edit the .gitconfig file by running the command `git config --global --edit` or by opening it from `C:\Users\<Your_User>\.gitconfig`.  You want to set the username and password that is used for your proxy server -- not the username and password of the various Git services that you use. Authentication to GitHub and other Git hosting providers can be handled from within GitHub Desktop.
