### ISSUE TITLE
I don't know what went wrong

### ISSUE THREAD

**Issue by kreeee2** [desktop/desktop#8779]
For some reason, I managed to clone the folder onto my computer, but when I made changes and tried to push it back to the origin, it says that 'authentication failed'. I have no idea what went wrong... I took the possible solutions offered by github and still in vain. 

![image](https://user-images.githubusercontent.com/56826503/70539340-74933600-1b5b-11ea-8c47-fe5b29dcd1df.png)

**Comment by steveward** [comment]
@kreeee2 thanks for the report. Could you upload the log file from GitHub Desktop? That should give us some more information about this error. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by kreeee2** [comment]
![image](https://user-images.githubusercontent.com/56826503/70607937-38adae80-1bf7-11ea-915b-d757e75df491.png)

**Comment by steveward** [comment]
@kreeee2 that looks like the directory for your repository -- you will need to click `Help` > `Show Logs in Explorer` to open the directory with the GitHub Desktop log files.

**Comment by kreeee2** [comment]
Hello Steve,

Sorry for the inconvenience caused. I hope I'm giving you the correct
information this time. Do I need to open any of the log files?
Please let me know.

Cheers,
Christina
[image: image.png]

**Comment by steveward** [comment]
@kreeee2 you can drag-and-drop a log file from the day you experienced this issue directly into an issue comment in this thread -- see the `Attach files by dragging & dropping, selecting or pasting them` option. That will automatically upload it as an attachment for me to view. Thanks!

**Comment by tierninho** [comment]
@kreeee2  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
