### ISSUE TITLE
Getting packages of committed files in one or more commits

### ISSUE THREAD

**Issue by MarcelloDM** [desktop/desktop#8782]
Hi, 
I thought that it would be nice if user can select one or more commit from the "History" and generates partial export packages. The package (tar.gz, rar or zip) will contain all the files (surely the most updated version for that files that are shared by more commits) mantaining the filesystem tree. 

Regards.

**Comment by kuychaco** [comment]
👋 @MarcelloDM, would you mind elaborating on the use case for this? It's not immediately clear to me what this functionality would serve. 

Please use our template to provide extra information (thanks!):

### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by MarcelloDM** [comment]
Hi Katrina. Thanks for you answer! 
In Agile Software Development approach is needed to create packages to get incremental code easily to release and install.

**Comment by outofambit** [comment]
Hi @MarcelloDM I believe this use case is better covered with GitHub.com's Releases. Please let us know if you have further questions. Thanks!
