### ISSUE TITLE
When will Github Desktop support internet proxy？

### ISSUE THREAD

**Issue by NanoJoey** [desktop/desktop#8786]
Because of company's internet policy , only proxy i can use to access internet, so i wish github would add proxy feature to github destop. Thanks.

**Comment by steveward** [comment]
Thanks for contributing @NanoJoey. You can configure GitHub Desktop to work with a proxy by running the following command from the command line (you will need to [install Git for Windows](https://git-scm.com/download/win) if you have not already):

`git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`

Replace `proxyuser` with your proxy username and `proxypwd` with your proxy password. Also, `proxy.server.com:8080` needs to point to the URL of your proxy server.

Let me know if you run into any issues getting this working.
