### ISSUE TITLE
Github Desktop gets stuck on Configure Git screen (again)

### ISSUE THREAD

**Issue by CorentinWicht** [desktop/desktop#8794]
Dear GitHub developpers,

I have successfully installed GitHub Desktop on one of my Windows 10 (64 bits) machine, while running the installation file as administrator. Still, I wanted to install it on a second computer (same setup), but this time I am unable to click the "continue" button when reaching the "Configure Git" page.. 

I have tried to follow recommendations from issue #8505 :
1) Tried removing %APPDATA%\GitHub Desktop\ and reinstalling = Failed
2) Tried to locate and remove file .gitconfig.lock, but there are no such file on my hard-drive

I also tried to set up the Git account username and email through Git Bash, which worked and generated a .gitconfig file in my C:\ accordingly, but nothing has changed regarding the installation of GitHub Desktop..

Here is what is return by Git Bash when I type $ git config --list:
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.editor=nano.exe
credential.helper=manager

Here is the desktop app production log:
[2019-12-13.desktop.production.log](https://github.com/desktop/desktop/files/3959856/2019-12-13.desktop.production.log)

**Comment by CorentinWicht** [comment]
I figured I guessed where the error lies In the desktop production log it is mentioned that Git is trying to access : U://.gitconfig (for which I have no admin rights) while it should access the C:\Users\wichtco\.gitconfig

Any idea on how to change this? 

I tried to follow this thread but this didn't work out well..
http://practicalseries.com/1002-vcs/03-03-install.html

**Comment by steveward** [comment]
Thanks for the report @CorentinWicht. Is the `U:` drive mapped for something specific on your machine, like Program Files or Program Data? If you run the command `SET` from the Command Prompt it will show the environment variables on your machine, which should help narrow down what `U:` is being used for. Running `git config --list --show-origin` will list the locations and settings of the various config files on your machine, which should also help us track down why you have a .gitconfig in that location.

**Comment by willswords** [comment]
I have the same issue. My HOMEDRIVE is set to U: Our IT dept. does this so that our Documents folder maps to a network share instead of on the local pc. They picked U: because it sounds like "you" as in "your drive." This means if I don't have access to the network share (like if I'm at home on my wifi) I can't get to U:
However, I found that if I log in using the VPN, I am able to get past the Configure page, but it saves that .gitconfig file on the "U:" drive which I can't access unless I'm on the VPN.

**Comment by CorentinWicht** [comment]
> Thanks for the report @CorentinWicht. Is the `U:` drive mapped for something specific on your machine, like Program Files or Program Data? If you run the command `SET` from the Command Prompt it will show the environment variables on your machine, which should help narrow down what `U:` is being used for. Running `git config --list --show-origin` will list the locations and settings of the various config files on your machine, which should also help us track down why you have a .gitconfig in that location.

Dear Steve, 

many thanks for your reply. 
As mentioned by willswords, our IT dept. set the homedrive to U: so as to store data on a network drive. The problem is that the access is only restricted to the Documents folder in U:, hence we have no right or writing/editing outside the U://Documents/ folder.. 

Here is the output of the set command:
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\wichtco\AppData\Roaming
CLIENTNAME=MEDPC258
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=MEDPC31
ComSpec=C:\WINDOWS\system32\cmd.exe
DriverData=C:\Windows\System32\Drivers\DriverData
HOMEDRIVE=U:
HOMEPATH=\
HOMESHARE=\\HOME\Directories\WichtCo
KMP_DUPLICATE_LIB_OK=TRUE
LOCALAPPDATA=C:\Users\wichtco\AppData\Local
LOGONSERVER=\\SVW-DC-02
MKL_NUM_THREADS=1
MKL_SERIAL=YES
NUMBER_OF_PROCESSORS=16
OneDrive=C:\Users\wichtco\OneDrive
OS=Windows_NT
Path=C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\MATLAB\MATLAB Runtime\v95\runtime\win64;C:\Python26;C:\Python26\Scripts;C:\Program Files\MATLAB\R2018b\runtime\win64;C:\Program Files\MATLAB\R2018b\bin;C:\Program Files\Git\cmd;C:\Users\wichtco\AppData\Local\Microsoft\WindowsApps;C:\Users\wichtco\AppData\Local\GitHubDesktop\bin
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 12, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=9e0c
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Intel\Wired Networking\
PUBLIC=C:\Users\Public
SESSIONNAME=RDP-Tcp#1
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\wichtco\AppData\Local\Temp
TMP=C:\Users\wichtco\AppData\Local\Temp
USERDNSDOMAIN=UNIFR.CH
USERDOMAIN=UNIFR
USERDOMAIN_ROAMINGPROFILE=UNIFR
USERNAME=wichtco
USERPROFILE=C:\Users\wichtco
windir=C:\WINDOWS

and here is the results of the git config --list --show-origin command:
error: cannot spawn most: No such file or directory
file:C:/Program Files/Git/etc/gitconfig diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/etc/gitconfig filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/etc/gitconfig filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/etc/gitconfig filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/etc/gitconfig filter.lfs.required=true
file:C:/Program Files/Git/etc/gitconfig http.sslbackend=openssl
file:C:/Program Files/Git/etc/gitconfig http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/etc/gitconfig core.autocrlf=true
file:C:/Program Files/Git/etc/gitconfig core.fscache=true
file:C:/Program Files/Git/etc/gitconfig core.symlinks=false
file:C:/Program Files/Git/etc/gitconfig core.editor=nano.exe
file:C:/Program Files/Git/etc/gitconfig credential.helper=manager
file:C:/users/wichtco/.gitconfig        user.name=Corentin Wicht SuperOrdi
file:C:/users/wichtco/.gitconfig        user.email=corentin.wicht@unifr.ch
file:C:/users/wichtco/.gitconfig        core.editor=editor
file:C:/users/wichtco/.gitconfig        core.pager=most
file:C:/users/wichtco/.gitconfig        color.ui=auto
file:C:/users/wichtco/.gitconfig        merge.conflictstyle=diff3
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.worktree=U:/
file:.git/config        core.symlinks=false
file:.git/config        core.ignorecase=true


Regarding the .gitconfig files by running the following command in windows cmd "dir .gitconfig /s":
 Volume in drive C has no label.
 Volume Serial Number is 20A3-E558

 Directory of C:\Users\wichtco

13/12/2019  10:01               172 .gitconfig
               1 File(s)            172 bytes

     Total Files Listed:
               1 File(s)            172 bytes
               0 Dir(s)  815.711.940.608 bytes free



Is the problem clearer now?

Best regards,

Corentin

**Comment by willswords** [comment]
How about you just let us pick a location for the .gitconfig file? Problem solved.

**Comment by willswords** [comment]
Except I'm guessing that location would have to be stored in... the .gitconfig file... hmmmm. How about having a plan B for where to save the gifconfig file if it fails saving in HOMEDRIVE?

**Comment by steveward** [comment]
@willswords and @CorentinWicht thanks for sharing those details! That's very helpful. 

Are you able to edit the environment variables on your system? You could create a `HOME` environment variable and point it to something like `C:\config_files`. You can then create your .gitconfig in that location, which will be picked up by Git. Let me know if that would work.

**Comment by CorentinWicht** [comment]
> @willswords and @CorentinWicht thanks for sharing those details! That's very helpful.
> 
> Are you able to edit the environment variables on your system? You could create a `HOME` environment variable and point it to something like `C:\config_files`. You can then create your .gitconfig in that location, which will be picked up by Git. Let me know if that would work.

Dear Steve,

many thanks your idea worked! This is who I did it:

Search for “edit environment variable” in the Start menu.
From the popup which appears, click “Create”.
Add a new value with name = HOME and value = where you want the .gitconfig to be saved

Best regards

**Comment by tierninho** [comment]
Thanks for the update @CorentinWicht . Glad it all worked out!
