### ISSUE TITLE
Reduce the prominence of Branch Protection

### ISSUE THREAD

**Issue by nycdotnet** [desktop/desktop#8795]
### Describe the feature or problem you’d like to solve

The new protected branch warning is a pretty cool feature, but I have a lot of repos that I just look at (other teams' microservices).  It's a bit stressful/distracting to see a warning all the time when I have not made any changes, nor do I intend to.  I just want it to be easy to get latest master all the time.

![image](https://user-images.githubusercontent.com/3755379/70808803-75f87480-1d8e-11ea-9406-ce893d81b2d1.png)

### Proposed solution

Only show the protected branch warning if there are any tracked changes.  Alternately, only show the protected branch warning if the user has entered text in the commit summary or description boxes (though I know this would defeat the purpose with the automatic commit message).  Alternately, hide the yellow caution icon when there are zero tracked changes, but leave the other functionality the same; in this scenario, the yellow caution icon would unhide if there were tracked changes.

### Additional context

Thanks for such an awesome app!!

**Comment by tierninho** [comment]
@nycdotnet Thanks for the thoughtful write-up. We will mull this over internally and circle back. Given the holiday period, this may take some time.

Glad you are enjoying Desktop!

**Comment by billygriffin** [comment]
Thanks for the idea @nycdotnet! We discussed this as a team and we're comfortable with the suggested implementation to only show the warning when there are changes present (regardless of whether the changed files are checked or unchecked). I'm hoping we can get this into our upcoming release in a couple weeks, but depends on bandwidth. Really appreciate your feedback! ✨

**Comment by billygriffin** [comment]
I also wanted to point out that for whomever picks this up, we think the same logic should apply to the warning for being on a repository where you don't have write access and therefore won't be able to push. That warning should only show up when you have changes present.

Additionally, for both of these cases (branch protection and no write access warnings), if you go ahead and make a commit in spite of the warning, we think it's probably fine for the warning to go away until you have further uncommitted changes at which point it would return.

Happy to clarify further if there are any questions or if this is unclear.

cc: @kuychaco and @outofambit
