### ISSUE TITLE
Add user preference to disable auto-generated commit summary

### ISSUE THREAD

**Issue by srubin** [desktop/desktop#8796]
### Describe the feature or problem you’d like to solve

I understand that this feature is a time-saver for some workflows: https://github.com/desktop/desktop/issues/5240

However, I've been using it for the past year and a half, and it often leads to me creating a lot of commits that say `Update foo.bar` rather than a more useful message. 

### Proposed solution

I could solve this problem with more self control, of course 👼, but another option would be to add a user preference to disable the auto-generated commit message. The text input would default to `Summary (required)` in all cases.

### Additional context

This might be a just-me thing (and I understand the desire to not add too much configuration; that makes it more challenging to create a cohesive user experience). Would others benefit from this preference?

**Comment by tierninho** [comment]
@srubin Thanks for filing, @srubin . In order to stay in parity with Github.com, this feature will remain for now. Let's see if .com adjusts the feature or if more Desktop users find it intrusive, then we can consider a change. 

Hopefully, you don't find it too cumbersome. Thanks for using Desktop!

**Comment by marcello3d** [comment]
For what it's worth, I think the use-cases for committing via GitHub.com (minor edits/tweaks) are pretty different than GitHub desktop (working on a project).

**Comment by MauricioFerraz** [comment]
Any chances of giving users the option of editing that default message somehow?

**Comment by benknight** [comment]
+1 for this feature. I prefer to user Conventional Commit format but I often find myself accidentally committing with the default message like "Update index.js"

**Comment by TecsiAron** [comment]
+1 for this message, I understand why its useful to have that message, but I recently switched a bunch of ppl to git and this is promoting the development of the horrible habit of never actually writing a commit message.
