### ISSUE TITLE
Separate branch to new folder

### ISSUE THREAD

**Issue by Aceba1** [desktop/desktop#8797]
### Describe the feature or problem you’d like to solve

Optional functionality for separating branches of a local repository to different folders.

### Proposed solution

Side-by-side comparison of two branches, without having to switch between them or copy the repository to a new folder. Or, working on multiple branches at the same time. Multitasking.

### Additional context

...It appears that for my specific usage case, `git cherry-pick` #1685 would be the most applicable. 
I am trying to move commits from one branch in a repository to the master branch, and have been doing so through copy-pasting / retyping what these commits changed.

**Comment by tierninho** [comment]
@Aceba1 Thanks for filing this. I think the cherry-picking issue you referenced is closest we will get to this in the near-term. I hope that will be sufficient for you when it does role out one day. 

Thanks for using Desktop!
