### ISSUE TITLE
Ability to set font size

### ISSUE THREAD

**Issue by Erkam246** [desktop/desktop#8798]
### Describe the feature or problem you’d like to solve

Add an option to set font size in settings under Appearance

### Proposed solution

Better readable code

**Comment by tierninho** [comment]
@Erkam246 Thanks for filing. This is a dupe of #3543 so i will close this issue. Please follow along there.

In the meantime, have you tried our zoom feature? See the `View` menu on Mac or Windows.

Alternatively, keyboard commands are:

```
Reset Zoom (Mac: ⌘0; Windows: Ctrl+0)
Zoom In (Mac: ⌘=; Windows: Ctrl+=)
Zoom Out (Mac: ⌘-; Windows: Ctrl+-)
```

**Comment by Erkam246** [comment]
I mean only for  the code not the whole application
