### ISSUE TITLE
"error: you need to resolve your current index first"

### ISSUE THREAD

**Issue by ghnp5** [desktop/desktop#8800]
Hello,

I'm really not happy with the fact that my previous request was discarded/ignored so easily: https://github.com/desktop/desktop/issues/8739

All I'm asking is whether it's possible to add a context menu option that will simply perform the following command:

`git add FILE_PATH`

So that after a conflict was resolved, we can add the file back to the index, and therefore be able to perform a 'switch branch' without getting the error:

> error: you need to resolve your current index first

--

1) Make changes on a file as you go.
It is not convenient at this time to create a new branch, so you just work on the master.

![image](https://user-images.githubusercontent.com/57591332/70852821-d75b3900-1e9d-11ea-8b1d-d1db727b9ca6.png)

2) Now you want to create a new branch, but you want to update your current master with all the changes made since your last update.

3) You get a conflict, and you resolve it.

![image](https://user-images.githubusercontent.com/57591332/70852864-4173de00-1e9e-11ea-8314-a9c19eca1d22.png)

4) Since the conflict is resolved, there should be nothing stopping you from switching to a new branch. After all, you should be in the exact same state as you were before the conflict happened.

5) However, if you switch to the new branch with the option "Bring my changes to XXX":

![image](https://user-images.githubusercontent.com/57591332/70852877-6e27f580-1e9e-11ea-8f0f-d4177a5c4c31.png)

6) I can easily fix this by running:

`git add README.txt`

And the file is back to normal (look at the icon at the right):

![image](https://user-images.githubusercontent.com/57591332/70852887-8a2b9700-1e9e-11ea-9452-1a3746e6f324.png)

7) Now I can switch branch.

--

My question is -- **can we have this "git add" feature in GitHub Desktop itself, without having to do it manually or using 3rd party UIs?**

Or, if the "checkbox" at the left is Ticked, shouldn't "git add" be done automatically anyway?

![image](https://user-images.githubusercontent.com/57591332/70852916-04f4b200-1e9f-11ea-9b38-d73f03bbb0b5.png)

**Comment by ghnp5** [comment]
**Why do I want to do this? (use case)**

Due to the high pace development in my team, I want to always work with the latest code, as much as possible. Therefore, I develop while I am in "master".

However, at the time I'm ready to commit my changes, I must create a branch and then do a pull request.

But, every time I did an "pull/update" from master, some conflicts might have happened, and those are stopping me from moving to my new fresh branch, until I do "git add" for all those conflicted (now resolved) files.

**Comment by tierninho** [comment]
@ghnp5 Thank you for the additional thoughts. 

I am closing this issue and adding the comments to the original issue as it is better to keep all the content together in one issue despite it being closed for now.
