### ISSUE TITLE
Support Goland as external editor on Mac

### ISSUE THREAD

**Issue by bryanl** [desktop/desktop#8802]
### Describe the feature or problem you’d like to solve

Support Goland as an external editor like in #4841

### Proposed solution

Support Goland

**Comment by tierninho** [comment]
@bryanl Thanks for filing. Marking this issue as `help wanted`. 

For anyone interested in tackling this, please see the [docs](https://github.com/desktop/desktop/blob/master/docs/technical/editor-integration.md) on editor integration.

**Comment by thinklinux** [comment]
For some reason it gives me 404 on the docs link. When I change the url to point the development branch everything is good [docs](https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md).

**Comment by Rexogamer** [comment]
That is because master isn’t a branch in this repo.
