### ISSUE TITLE
Unable to delete local branches already deleted on Bitbucket server

### ISSUE THREAD

**Issue by Asperson** [desktop/desktop#8805]
### Describe the bug

Unable to delete local branches already deleted on Bitbucket server - the Branch -> Delete menu is grayed out

### Version & OS

Version 2.2.4, Windows 7 Enterprise

### Steps to reproduce the behavior

1. in GitHub desktop add existing local repository, fetch, checkout some branches
2. Go to the server, delete few check outed branches
3. Go to GitHub desktop, fetch
4. Try to delete the same branch - Branch -> Delete menu is grayed out

### Expected behavior

Should be able to delete local branches

### Actual behavior

Branch -> Delete menu is grayed out
![githubdesktop1](https://user-images.githubusercontent.com/17258058/71008576-d6512400-20b6-11ea-8e52-91128bce7137.png)

**Comment by tierninho** [comment]
@Asperson Please try switching repos and coming back to the current repo. Did that help?

We do have [logic](https://github.com/desktop/desktop/pull/6544) in place that removes deleted branches.

**Comment by Asperson** [comment]
I did, and in other repo I was able to remove deleted branch, but when I switched back the Delete menu is still grayed out for this particular branch.
And I checked, it doesn't have any uncommited changes

**Comment by tierninho** [comment]
@Asperson Can you upload your logs so we can take a look? See the Help menu in Desktop.

Also, I assume you are not on the master branch? Thanks.

**Comment by Asperson** [comment]
Sure, logs are attached
[logs.zip](https://github.com/desktop/desktop/files/3983873/logs.zip)

No, its not master, its a ticket branch

**Comment by tierninho** [comment]
@outofambit I spotted this is the logs:

```
2019-12-19T13:53:22.180Z - info: [ui] skipping fast-forward for all branches as there are 30 eligible branches (Threshold is 20 eligible branches).
```

Could this be the cause? Some background reference here: https://github.com/desktop/desktop/search?q=eligible&unscoped_q=eligible

**Comment by billygriffin** [comment]
@tierninho I don't think that should cause someone not to be able to *manually* delete a local branch, it just indicates that the automatic updating was skipped. I'm not sure why this might happen, curious if this is something @desktop/support has seen before.

**Comment by steveward** [comment]
@Asperson I tested this out and I was able to successfully delete a local branch in GitHub Desktop that had been deleted in the repository on BitBucket. I also deleted a remote branch that had not been checked out locally and it was successfully removed from the branch list in GitHub Desktop. Are you able to reproduce this consistently?

**Comment by outofambit** [comment]
@Asperson We haven't heard back from you, so I'm going to close this out. Please let us know if you have any more questions. Thanks!

**Comment by caiocesarbrito** [comment]
I have the same issue! 

![bug](https://user-images.githubusercontent.com/11236978/75448709-7abed480-594a-11ea-8a65-bbf7d4076f38.png)

I created this branch just for implement a little test locally. My branch doesn't exists in my remote repository. I don't understand why the option Delete Branch is not avaiable to me.
