### ISSUE TITLE
Desktop git user name and email address not reflected in created repo's git config

### ISSUE THREAD

**Issue by Sinclair81** [desktop/desktop#8808]
When creating a new repository, the user name and email address are not saved in the config file.

**Comment by outofambit** [comment]
Hi @Sinclair81, I'm assuming you've filled out the name and email fields in "Preferences" > "Git"? Would you expect to see these reflected in `.git/config` in a new repository created with GitHub Desktop? Can you share more about how this impacts your workflow? Thanks!

**Comment by Sinclair81** [comment]
Hi,
Yes, that's exactly my thought!
I think it should be checked with every type of adding whether there are 
the entries for username and user email.
I took two pictures where you can see how it affects github if no 
(--global && --local) username is set (I only push changes with github 
desktop!).
And GitLab can't handle it either! I have an account on a GitLab server 
from a friend. An email address is entered in the account itself, but 
when I push from github desktop, GitLab only wants to take username and 
emai from the config of the repo. (More precisely: github desktop saves 
the username@computername.local in the head files at the place where the 
email address is otherwise and gitlab then tries to send email there !!)
Of course, I already knew that everything could be done in the terminal, 
but I decided specifically for GitHub Desktop so that I don't have to do 
it.

Thank you for your prompt reply.
Sinclair.


------ Originalnachricht ------
Von: "evelyn masso" <notifications@github.com>
An: "desktop/desktop" <desktop@noreply.github.com>
Cc: "Sinclair81" <dev.sinclair81@gmail.com>; "Mention" 
<mention@noreply.github.com>
Gesendet: 18.12.2019 00:48:59
Betreff: Re: [desktop/desktop] No user name and email address in the 
config (#8808)

**Comment by steveward** [comment]
@Sinclair81 if your user.email is missing from the .gitconfig Git will use the machine name on macOS. See https://github.com/desktop/desktop/issues/1364 for the tracking issue about this. We also have an [open issue](https://github.com/desktop/desktop/issues/610) where we are tracking improvements to commit attribution to verify if the email address you are committing with matches the email address associated with your currently logged in GitHub account.

Hopefully those links are helpful. If you have any further questions about this please let us know.
