### ISSUE TITLE
Adding support for editing uncommitted changes inside Desktop

### ISSUE THREAD

**Issue by Justin-JHG** [desktop/desktop#8809]
### Describe the feature or problem you’d like to solve

Please enable us to be able to edit uncommitted changes inside Desktop 

### Proposed solution

This will be very helpful for users to be able to discard changes not required for submit without leaving Desktop

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by outofambit** [comment]
Hi @Justin-JHG, thanks for reaching out! Can you clarify what you mean by "edit uncommitted changes"? Do you mean like a text editor or perhaps simply discarding specific lines or hunks of uncommitted changes?

**Comment by Justin-JHG** [comment]
hi @outofambit 
Thank you for the reply.

yes a way to simply discarding lines or hunks would be enough.
a text editor would be better.

cheers

**Comment by outofambit** [comment]
Thanks @Justin-JHG! The discarding lines/hunks enhancement is tracked in #2414. Please follow along there.

As for a text editor inside of Desktop itself, there are no plans to implement that anytime soon since it is a large undertaking and there are many existing apps for that. Thanks!

**Comment by Justin-JHG** [comment]
@outofambit did you happen to link to the wrong issue ? I can see nothing related to discarding lines/hunks in that one, it says "Clone failed: unable to access 'https://github.com/wuhaoyu1990/MagicCamera.git/':"

**Comment by outofambit** [comment]
@Justin-JHG oh sorry I totally did! I fixed the link (the correct issue is #2402).
