### ISSUE TITLE
je n'ai remarqué aucun probleme 

### ISSUE THREAD

**Issue by kkayri** [desktop/desktop#8816]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@kkayri thanks for contributing. If you are having issues with GitHub Desktop please fill out the issue template with the necessary information so that we can help you further.
