### ISSUE TITLE
sort 'other branches' by latest update

### ISSUE THREAD

**Issue by staabm** [desktop/desktop#8819]
### Describe the feature or problem you’d like to solve

this is a similar request then https://github.com/desktop/desktop/issues/5155 but this time for the 'other branches' list.

when working with branches, most of the time we need to work with the recent ones, and not with the really old ones. after initial checkout we get a list like this:

![grafik](https://user-images.githubusercontent.com/120441/71166420-fcabc680-2252-11ea-883c-9e0821feb51d.png)

### Proposed solution

would be great to have this branches sorted from the ones with the more recent changes to the older ones

**Comment by tierninho** [comment]
@staabm Thanks for the idea. I will let this issue sit for others to weigh in as this is a responsible request.

I am not sure of the default logic in place now for sorting the places. It looks to be Alpha-ordered.

**Comment by Rexogamer** [comment]
@tierninho according to a comment by Shiftkey, it’s currently alphabetical. I personally think that sorting by last updated is a better idea, considering how the recent branches are sorted.

**Comment by Rexogamer** [comment]
could anyone point me in the direction of where the code for sorting branches (not into groups, into order) is

**Comment by tierninho** [comment]
We have an [master issue open](https://github.com/desktop/desktop/issues/8048) capturing all branch-related issues. When we address branches as a whole, we will consider this issue at that time.

For now, I will close this issue so there are not dupes floating around. Thank you.
