### ISSUE TITLE
Making selective changes for commit

### ISSUE THREAD

**Issue by Craigjw** [desktop/desktop#8820]
When I have many changes to a repository and only want to select some of them, there seems to be no way to select only these items to commit.  When I highlight the desired files for the commit and press a tick box, it un-selects all files.
The only way that I can tell to commit only a small subset of the entire list is to select them individually, which is not user friendly.
My current project, I have 60 files to select from a list of 100, it is unpractical to be required to select all these files one by one.

**Comment by tierninho** [comment]
@Craigjw Please use the `Cmd` (mac) or `Ctrl `(windows) key to select each commit then click the `spacebar` to check/uncheck each file.

The `Shift` key can also be used if the files are in a perfect row.

Closing the issue as this is resolved. Thanks for using Desktop!
