### ISSUE TITLE
Menubar flickering - Electron bug

### ISSUE THREAD

**Issue by aaronshekey** [desktop/desktop#8821]
### Describe the bug

This seems like an upstream Electron bug, since I see this across Electron apps (Spotify, Slack, Figma, etc.) but I wanted to capture it here.

### Version & OS

GitHub Desktop 2.2.4 on macOS Mojave 10.14.6

### Steps to reproduce the behavior

1. Have a few changes in your branch
2. Click on a file in the list of changed files.
3. Use your keyboard to navigate between them.
4. Watch the menu bar

### Expected behavior

The menubar shouldn't be flickering

### Actual behavior

The menubar flickers seemingly randomly when keying through the changed files.

### Screenshots

I had to crop this video for reasons™, but my menubar is the top bit of white pixels. You'll see it flicker in this [screen capture](https://www.dropbox.com/s/tyiovy8mgiiv5up/flicker.mp4?dl=0) at least twice.

**Comment by tierninho** [comment]
@aaronshekey Thanks for filing. I assume to mean here:

![Screen Shot 2019-12-19 at 9 10 37 AM](https://user-images.githubusercontent.com/14828183/71202169-b7ca6480-223f-11ea-9e97-9e315235cdb8.png)

I am not sure that is within our means to fix, but based on feedback from the team, I can fill an issue on the Electron repo if needed.

I did spot some other flickering issues there, which may be related:
https://github.com/electron/electron/issues/19699
https://github.com/electron/electron/issues/10069
https://github.com/electron/electron/issues/9413

**Comment by aaronshekey** [comment]
Yep, the red arrow is definitely the right spot—the menubar. Unfortunately, none of those issues aren't quite what we're looking at here.

**Comment by say25** [comment]
@aaronshekey we have since upgraded Desktop to use Electron 7. Does this issue still happen for you?

**Comment by aaronshekey** [comment]
Sadly, this is still occurring. Just observed it when fetching changes from a branch. I'm on `2.3.1`.

**Comment by aaronshekey** [comment]
I _think_ this has gone away. I'll re-open if I see the flickering again :v:
