### ISSUE TITLE
cannot publish unbom head

### ISSUE THREAD

**Issue by tongluren381** [desktop/desktop#8827]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
@tongluren381 thanks for contributing. Usually this issue is caused by the branch you are trying to publish not having an initial commit. Try making a commit in your repository and then click the `Publish` button again. Let me know if that doesn't help.
