### ISSUE TITLE
Where to stash changes in the new Github desktop version?

### ISSUE THREAD

**Issue by anuragmayait** [desktop/desktop#8828]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by Rexogamer** [comment]
Are you talking about stashing changes when you go from a protected branch to a different one? In that case, we automatically move them.

**Comment by billygriffin** [comment]
The way stashing works is that when you switch branches with uncommitted changes, you'll be prompted and able to select whether you want to bring your changes with you or stash them on your current branch. If you choose to stash them, you'll be able to view and either restore or discard your stash upon returning to the branch where they were stashed. Please let us know if you have other questions!
