### ISSUE TITLE
ffmpeg.dll required to install GitHub Desktop for Windows

### ISSUE THREAD

**Issue by denden4444** [desktop/desktop#8833]
### Describe the bug

When installing the latest version of GitHub Desktop for Windows I received the following error.
Why is ffmpeg.dll required ? battling to understand the requirement for this library.
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	GitHubDesktop.exe
  Application Version:	2.2.4.0
  Application Timestamp:	5d12fbd0
  Fault Module Name:	ffmpeg.dll
  Fault Module Version:	6.3.9600.17415
  Fault Module Timestamp:	5450559e
  Exception Code:	c0000135
  Exception Offset:	00000000000ec5a0
  OS Version:	6.3.9600.2.0.0.256.49
  Locale ID:	1033
  Additional Information 1:	ac05
  Additional Information 2:	ac0507478d1c5bd693cfc4fe3987e900
  Additional Information 3:	ac05
  Additional Information 4:	ac0507478d1c5bd693cfc4fe3987e900

### Version & OS

Windows 8.1 Pro N 64-bit
GitHubDesktopSetup.exe (latest stable as @ date of this posting)
### Steps to reproduce the behavior

Double click the installer to launch it.

### Expected behavior

Git Windows Desktop should install perfectly fine.

### Actual behavior

Setup/install crashed just after launching it stating that ffmpeg.dll is missing.

### Screenshots
![image](https://user-images.githubusercontent.com/34808437/71383278-48a89380-25e4-11ea-9a23-4913c375435c.png)

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
Could not retrieve any since install does not complete.

### Additional context

Not underatnding why this dll is needed at all ?

**Comment by niik** [comment]
Hi @denden4444, sorry to hear you're having problems installing GitHub Desktop!

Do you have any anti-virus software on your machine that might be interfering with the installation?

I notice that you're using Windows 8 **N**, i.e the stripped version of Windows without the Windows Media Center. This sounds related enough to the ffmpeg library that I strongly suspect they're related. While I haven't found anything directly stating that ffmpeg won't work on Windows N editions I did find [this note](https://www.howtogeek.com/322112/what-is-an-n-or-kn-edition-of-windows).

> ### Quite a Few Things Will Break
>
> [...] The removal of underlying multimedia codecs and playback features means quite a few applications won’t work properly.
>
> Many apps [...] rely on the built-in Windows video playback features. These features may not function properly in such applications, or the applications may crash completely.

Do you happen to have ffmpeg installed globally on your system? What media player do you use currently to view videos on your system?

> Not underatnding why this dll is needed at all ?

GitHub Desktop is built on top of [Electron](https://electronjs.org) which itself is built upon [Chromium](https://www.chromium.org), the open source version of Google's Chrome browser. Chromium uses ffmpeg to decode and play video and audio files (such as videos on YouTube or audio files on Soundcloud). While GitHub Desktop currently doesn't make use of audio or video playback we haven't seen any reason to attempt to remove ffmpeg from the bundle.

**Comment by niik** [comment]
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.

**Comment by leckmicham** [comment]
das problem existiert seit 2019? wie kann man es beheben, denn es ist 2025 und das problem existiert noch immer.
