### ISSUE TITLE
Can't find "<repository name>"

### ISSUE THREAD

**Issue by toddabel** [desktop/desktop#8838]
### Describe the bug
Open the app for an existing repository and get "Can't find 'repository'. Check again.

This has been working fine, but this is the second time this has occurred. Last time I had to delete the directory and re-clone

It just happens without doing anything that I'm aware of and the strange thing is that the Git command line and VSCode continue to work correctly for the same repository.

git status returns without error.

### Version & OS
2.24 on Windows 10 1909 build 18363.535

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Open the app for an existing repository.

### Expected behavior

The app continue to find the repository

### Screenshots

![screen 1](https://user-images.githubusercontent.com/4468495/71546843-2057c680-294f-11ea-8632-bedee8205f54.PNG)

### Logs

[2019-12-28.desktop.production.log](https://github.com/desktop/desktop/files/4007225/2019-12-28.desktop.production.log)

**Comment by tierninho** [comment]
@toddabel thanks for filing. Have you tried clicking the Locate button to find your repo? You were correct to reclone but this shouldnt be happening over and over.

I did not see anything interesting in the logs, nor has this issue been reported before. 

I will try to reproduce soon.

**Comment by toddabel** [comment]
Locate and Check again both could not open the repo. I just started it up again and now it works. Very strange. I didn't reclone this time, but I did use the repo for checkin and sync from within VSCode. I did do a Flutter clean, but not sure how that could effect Git. Wish I could help, but it's not broken any longer.

**Comment by Bricobit** [comment]
I'm with the same problem and I can't find a solution, sometimes due to unit change or for other reasons I have had to re-indicate the repository path and it never finds it, in the end I have to make strange inventions because the code I have in My computer is more advanced than that of the repository, I have to save my files in another place, delete the repository, clone it again and then replace the cloned files with the ones I saved previously
