### ISSUE TITLE
unable to discard changes on ubuntu 18.04

### ISSUE THREAD

**Issue by iaman221b** [desktop/desktop#8839]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@iaman221b please fill out the template so we have more information to go on. Thanks.
