### ISSUE TITLE
Winner

### ISSUE THREAD

**Issue by Forlow** [desktop/desktop#8840]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by Rexogamer** [comment]
Hey @Forlow! Please could you fill out the template so we can help you with your issue? Thanks.
