### ISSUE TITLE
You do not have permission to push to cgminer

### ISSUE THREAD

**Issue by fazluls** [desktop/desktop#8842]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by fazluls** [comment]
Dear Sir,

I am new here. How to resolve it. I don't know. Please resolve it as early as possible.

Thank you,
Best regards,
Fazlul Quader

**Comment by kcaseypoupouare** [comment]
Plz help me resolve

**Comment by Rexogamer** [comment]
Do you have push access on Github.com (this site)? If so, are you signed into the same account on Desktop as on Github.com?

**Comment by steveward** [comment]
@fazluls I took a look and it does not seem like you have permissions to push to the `cgminer` repository. You will need to request access if you want to push to a repository that is not under your account. You can also [fork the repository](https://help.github.com/en/github/getting-started-with-github/fork-a-repo) and then push to your fork. You can then submit a pull request to the upstream `cgminer` repository. I wrote a [guide about how to do this this](https://github.community/t5/Support-Protips/Contributing-to-Repositories-with-GitHub-Desktop/ba-p/17712) with GitHub Desktop. If you have any specific questions about this let me know.
