### ISSUE TITLE
Make repository favorite

### ISSUE THREAD

**Issue by DanielOberlechner** [desktop/desktop#8844]
### Describe the feature or problem you’d like to solve

Hi,
I think it would be really convenient to make a repository a favorite.
It should be listed then on the top of recent repository's.

### Proposed solution

I have a lot of repository's and it would be fine to reach them faster.
People would spare time and that is always useful.

### Additional context

I hope the idea is good and I'm curious what you people think about that idea.

Kind regards,
Daniel Oberlechner

**Comment by billygriffin** [comment]
Hi @DanielOberlechner, thanks so much for the issue. Last year we shipped a revamp to include the Recent repositories that you mentioned. We don't have any plans in the near future to add favorites, for the reasons described here: https://github.com/desktop/desktop/issues/8183#issuecomment-542217438

It's a totally valid request and I could see how it could be useful. We may consider it down the road as part of a broader revamp if/when we choose to pursue that further, but for now I'm going to close this issue to indicate it's not something we intend to support. Thank you again for the issue and for using GitHub Desktop!
