### ISSUE TITLE
GitHub Desktop: "Authentication failed." error. v2.3.1

### ISSUE THREAD

**Issue by cb-machan** [desktop/desktop#8853]
### Describe the bug

On trying to fetch against the repo, an "Authentication failed. Some common reasons include..." error appears. I am using SSH and it works when using the terminal.

### Version & OS
GitHub Desktop v2.2.4 on MacOS Catalina v10.15.2

### Steps to reproduce the behavior

1. Go to the `chargebee-app` repo.
2. Click on  **Fetch orgin**
3. See error.

### Expected behavior

The fetch should complete without errors as it does via the terminal.

### Actual behavior

The error appears instead.

### Screenshots

![image](https://user-images.githubusercontent.com/55124115/71710406-21429980-2e22-11ea-8449-944e3a1064ad.png)

### Logs
[2020-01-03.desktop.production.log](https://github.com/desktop/desktop/files/4018282/2020-01-03.desktop.production.log)

### Additional context

On trying to pull from the terminal using `git pull`, the operation is successful. The following are the steps:

1. Go to terminal and navigate to the folder where the repo is.
2. `git pull`
3. The following prompt appears: `Enter passphrase for key '/Users/cb-machan/.ssh/id_rsa':`
4. I enter the passphrase.
5. The pull is successful.

**Comment by steveward** [comment]
Thanks for contributing @cb-machan. Can you verify that `ssh-agent` is running and your key has been added?

` eval "$(ssh-agent -s)"`
`ssh-add -l -E md5`

GitHub Desktop does not have a method of entering a passphrase (see https://github.com/desktop/desktop/issues/2579), so that is likely the issue you are running into. If your passphrase is cached than `ssh` should work. Let me know if that helps.

**Comment by cb-machan** [comment]
Hi Steve,

Here's what I got:

cb-machan@cb-machan chargebee-app % eval "$(ssh-agent -s)"
> Agent pid 15056
> cb-machan@cb-machan chargebee-app % ssh-add -l -E md5
> The agent has no identities.


John Machan
Chargebee Docs

**Comment by steveward** [comment]
@cb-machan this means your key hasn't been added -- try running `ssh-add ~/.ssh/id_rsa`.

I'd also recommend adding something like this to your `~/.ssh/config` file so that your keys are automatically added to `ssh-agent`

```
Host * 
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_rsa
```

**Comment by cb-machan** [comment]
So here are the results:

```
cb-machan@cb-machan ~ % ssh-add ~/.ssh/id_rsa
Enter passphrase for /Users/cb-machan/.ssh/id_rsa:
Identity added: /Users/cb-machan/.ssh/id_rsa (machan@chargebee.com)
cb-machan@cb-machan ~ %
```

I then checked GitHub Desktop and the same authentication error shows.

So i just restarted the Mac and the error persists.

I checked `~/.ssh/config` to see what's in the folder. I only found the following:

```
cb-machan@cb-machan ~ % cd ~/.ssh/ 
cb-machan@cb-machan .ssh % ls -all
total 24
drwx------   5 cb-machan  staff   160 Jan  5 14:28 .
drwxr-xr-x+ 28 cb-machan  staff   896 Jan  5 14:55 ..
-rw-------   1 cb-machan  staff  3434 Nov  7 16:46 id_rsa
-rw-r--r--@  1 cb-machan  staff   746 Nov  7 16:46 id_rsa.pub
-rw-r--r--@  1 cb-machan  staff  1600 Nov  9 19:48 known_hosts
cb-machan@cb-machan .ssh % 
```

**Comment by steveward** [comment]
@cb-machan thanks for the update. Can you try running `github` from the Terminal to launch GitHub Desktop to see if that fixes this issue?

**Comment by cb-machan** [comment]
@steveward thanks. 

I try running `github` from Terminal and it can't find it:

```
cb-machan@cb-machan ~ % github
zsh: command not found: github
cb-machan@cb-machan ~ % 
```

I wondered whether it was due the shell so I tried switching it to `bash` from the current `zsh`:

```
cb-machan@cb-machan ~ % chsh -s /bin/bash 
Changing shell for cb-machan.
Password for cb-machan: 
cb-machan@cb-machan ~ % 
```

I restarted the computer post this but the shell was still `zsh`!

Sorry if I've digressed.

**Comment by steveward** [comment]
@cb-machan The `github` command line tool should in in `usr/local/bin/github` if you would like to try running it directly from there (and also verify its existence).

**Comment by cb-machan** [comment]
@steveward Can't find `github` command line tool:

```
cb-machan@cb-machan bin % ls *git*

git			git-receive-pack	git-upload-archive	gitk
git-cvsserver		git-shell		git-upload-pack
```

**Comment by steveward** [comment]
@cb-machan you can go to `GitHub Desktop` -> `Install Command Line Tool` to try installing it again.

**Comment by cb-machan** [comment]
Great! This seems to have fixed the problem. Here's what I did.

1. Installed **GitHub Desktop** using the steps above.
2. Did the following:

```
cb-machan@cb-machan chargebee-app % eval "$(ssh-agent -s)"
Agent pid 1576

cb-machan@cb-machan chargebee-app % ssh-add -l -E md5
The agent has no identities.

cb-machan@cb-machan chargebee-app % ssh-add ~/.ssh/id_rsa
Enter passphrase for /Users/cb-machan/.ssh/id_rsa:
Identity added: /Users/cb-machan/.ssh/id_rsa (machan@chargebee.com)

cb-machan@cb-machan chargebee-app % ssh-add -l -E md5
4096 MD5:d8:40:86:ba:2e:7c:4c:8f:83:81:11:6e:00:97:8e:0e machan@chargebee.com (RSA)

cb-machan@cb-machan chargebee-app % github
```

4. Performed a fetch on GitHub Desktop: success!

However, I run into the same problem after restarting the computer. I had to repeat the steps I described above to make it work.

**Comment by steveward** [comment]
@cb-machan are you having issues with this? It sounds like `ssh-agent` may  not be running after a restart which would cause this.

**Comment by cb-machan** [comment]
> @cb-machan are you having issues with this? It sounds like `ssh-agent` may not be running after a restart which would cause this.

Oh yes, and then I followed [the steps here](https://apple.stackexchange.com/questions/48502/how-can-i-permanently-add-my-ssh-private-key-to-keychain-so-it-is-automatically) to fix that.

**Comment by steveward** [comment]
@cb-machan it sounds like you were able to resolve this so I'm going to close this issue out. Let me know if you are still having problems.
