### ISSUE TITLE
如何制作动态库

### ISSUE THREAD

**Issue by dou1984** [desktop/desktop#8854]
你好，有幸用到lualinkerE，用c++11对luatinker的真是太棒了！不过在用的时候没有看到如何制作一个动态库加载到lua中，这个有好的建议吗？

**Comment by niik** [comment]
Automated translation

> How to make a dynamic library
>
> Hello, fortunate to use lualinkerE, using C ++ 11 is great for luatinker! But when I used it, I didn't see how to make a dynamic library to load into Lua. Is there any good suggestion for this?

Hi @dou1984, I think you may have the wrong repository. This is for the GitHub Desktop app, and we aren’t able to assist with things unrelated to the app. Best of luck!

> @ dou1984，您好，我認為您的存儲庫可能有誤。 這是針對GitHub桌面應用的，我們無法協助解決與該應用無關的事情。 祝你好運！
