### ISSUE TITLE
pull request filter does not find branch names

### ISSUE THREAD

**Issue by staabm** [desktop/desktop#8855]
### Describe the feature or problem you’d like to solve

sometimes we know the branch name when searching for a given pull request.
would be great if the search filter for pull requests would also work for a given branch name.

### Additional context

![grafik](https://user-images.githubusercontent.com/120441/71717535-afb21d80-2e18-11ea-8074-6c9aa2cb5e2d.png)

tested on GH-Desktop 2.2.4 on Windows10x64

**Comment by tierninho** [comment]
@staabm Thanks for the suggestion. We already have a similar feature albeit a little more roundabout. 

If you know the branch name, just select the branch from the Branches tab, and the Pull Request number badge is shown in the menu bar, like so:

![Screen Shot 2020-01-03 at 9 48 30 AM](https://user-images.githubusercontent.com/14828183/71745457-42998a80-2e0e-11ea-9815-92410e813cbc.png)

If we hear anymore feedback for your specific suggestion, we will reconsider. Thanks for using Desktop!

**Comment by staabm** [comment]
Thx for the feedback

My use-case was: try to find the pull request corresponding to a pull request on github.com.

I feel this is something different then the flow you suggested

**Comment by tierninho** [comment]
Ok, gotcha. 

cc @billygriffin for thoughts on this
