### ISSUE TITLE
Submodules should be better identified in the repositories list

### ISSUE THREAD

**Issue by marcosswald** [desktop/desktop#8856]
### Describe the feature or problem you’d like to solve

Since submodules are not directly supported I have to add a submodule manually as individual repository. When opening the view that shows all available local repositories, those repositories that are submodules and that are part of another repository (which is also available locally) are not identified as such. This leads to potential confusion when the submodule is added as another individual repository in a different local directory (not part of the super project), For example: Let's assume I have a repo called **project** and I have another one called **module** which was added as submodule to **project**. I have a local clone of the project called **project_ws**. My local file system looks like this:

/project_ws
/project_ws/module

Now I add both paths as local repositorues to Git Desktop. Git Desktop only lists the remote names which means in my repo view I see:

project
module

This is fine as long as I remember that my local clone of module is located in the project clone. Now I would like to do some work on the module but for practical reasons I would like to create a new clone and call it **module_ws**. My file system looks like this now:

/project_ws
/project_ws/module
/module_ws

Now I add the new path again to Git Destop and my list now shows:

project
module
module

which is very confusing because I don't know which module is which.

### Proposed solution

The best solution would be if submodules would be properly supported, i.e. whenever a project with submodules is added, the submodules would be automatically added to Git Desktop e.g. the repo list could be kind of a tree view with submodules being sub items of each project.

A simple and useful work around would be if you could edit the name of the repos in the list, e.g. in my case I copuld simply rename the repos:

project
project/module
module

**Comment by steveward** [comment]
@marcosswald thanks for the detailed feedback! I'm going to roll this issue into #1803 where better submodule identification is being tracked. We're also tracking overall improvements to submodules in #7523.
