### ISSUE TITLE
Feature request: ability to have multiple enterprise accounts

### ISSUE THREAD

**Issue by AlanCPSC** [desktop/desktop#8859]
Currently, a user is only able to sign in to a single standard account and a single enterprise account at a time. 

However, for freelancers like me - who need to sign into multiple different company accounts per day, the mind numbing task of repeatedly signing in and out can be tiresome.

Would it be possible for GitHub Desktop to support the simultaneous logged in state of multiple different enterprise accounts?

**Comment by steveward** [comment]
@AlanCPSC thanks for the feedback. I'm going to add this to https://github.com/desktop/desktop/issues/3707 where are are tracking supporting multiple accounts in GitHub Desktop.
