### ISSUE TITLE
I met a problem called Could not create directory  

### ISSUE THREAD

**Issue by chenmingzhen** [desktop/desktop#8861]
### This question has puzzled me for a long time

$ git push -u origin master
Could not create directory 'C:\\Users\\\351\231\210\345\220\215\346\214\257/.ssh'.
CreateProcessW failed error:193
ssh_askpass: posix_spawn: Unknown error
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by steveward** [comment]
@chenmingzhen this repository is for GitHub Desktop. It looks like the issue you are encountering is specific to Git for Windows. I'm not sure what is causing the `ssh_askpass` error, but the `Host key verification failed` error is a result of the the host (github.com) not being in your `known_hosts` file. You should be able to run `ssh -T git@github.com` to receive the prompt to verify github.com's public key.

If you continue to have issues I would recommend reaching out to [GitHub support](https://support.github.com/) with the version of Git you are running and your operating system information.
