### ISSUE TITLE
Add "New Window" Feature for Better Project Separation

### ISSUE THREAD

**Issue by psygo** [desktop/desktop#8867]
### Describe the feature or problem you’d like to solve

Even though you can add multiple separate repos to Github Desktop, why can't you have them open in multiple different windows?

For example, I use 2 different desktops on my Windows machine to keep track of 2 different projects I work at. I would be nice if I could have different Github Desktop windows for each of them.

### Proposed solution

From my experience, this is usually solved with a <kbd>New Window</kbd> button inside the <kbd>File</kbd> menu. Maybe this is a good enough solution?

**Comment by steveward** [comment]
Thanks for the feedback @psygo. We are tracking this feature in https://github.com/desktop/desktop/issues/3606 -- please follow along there for updates about this.
