### ISSUE TITLE
Github Desktop is very slow. Unable to fetch, pull or see my local changes.

### ISSUE THREAD

**Issue by titusr-kai** [desktop/desktop#8869]
### Describe the feature or problem you’d like to solve

Github Desktop is very slow. Unable to see my local changes. Using version 2.2.4 

my machine is a windows 10 intel core i7

When I click on the file to see the local changes, it shows no content changes found.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by steveward** [comment]
@titusr-kai thanks for the report. Could you upload the log file from GitHub Desktop so that I could get some more information about the issues you are experiencing? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks.

**Comment by titusr-kai** [comment]
[2020-01-06.desktop.production.log](https://github.com/desktop/desktop/files/4027937/2020-01-06.desktop.production.log)

**Comment by niik** [comment]
Looks like git calls are indeed taking an excessive amount of time.

```
2020-01-06T19:47:29.148Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(objectname:short)%00%(author)%00%(committer)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%(trailers:unfold,only)%00%1F refs/heads refs/remotes (took 280.242s)
2020-01-06T21:44:59.145Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 157.307s)
2020-01-06T21:45:16.784Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 141.670s)
```

@titusr-kai Could you tell us a little bit more about your environment. Do you have any anti-virus software on your machine, is this a personal or business PC, are you connected to a company network?

**Comment by titusr-kai** [comment]
@niik Yes I hav symantec, This is a business PC. I am on the company network.

**Comment by steveward** [comment]
@titusr-kai is there any chance you are able to temporarily disable Symantec or whitelist GitHub Desktop to see if that helps with this issue?

**Comment by titusr-kai** [comment]
@steveward I tried disabling Symantec and its still the same

**Comment by niik** [comment]
@titusr-kai Is your user folder hosted on a network drive? Something on your machine is causing these commands to run super slowly. Do any of your colleagues run GitHub Desktop, is it similarly slow for them?

**Comment by titusr-kai** [comment]
@niik My colleagues do not use github desktop. Yes, my folder is on the network drive.

**Comment by steveward** [comment]
@titusr-kai it's likely that the network drive is the culprit here. Are you able to test working with GitHub Desktop on a local disk instead of using your network drive?

**Comment by steveward** [comment]
@titusr-kai I'm going to close this issue out as we have not heard back from you -- let us know if you are still experiencing problems.

**Comment by togaykurtulus** [comment]
I ve same issue
[2021-12-07.desktop.production.log](https://github.com/desktop/desktop/files/7670744/2021-12-07.desktop.production.log)
!

**Comment by steveward** [comment]
@togaykurtulus are you running any antivirus/security software on your machine that could be causing performance issues?

**Comment by togaykurtulus** [comment]
Hello Steveward, I ve antivirus but It fixed , I didnt do anything but yes it is working ok now thank you
