### ISSUE TITLE
Sorting files under Changes tab by date

### ISSUE THREAD

**Issue by leo2575** [desktop/desktop#8877]
This is not an issue but a feature request, i hope i am posting it in the right plac.

I keep changing multiple files related to different Jira tickets and sometimes i end up with almost 25/30 files. It would be nice to be able to sort the files by last updated date so that i can quickly check-in the relevant ones.

Another nice to have feature is the ability to tag the individual files under a category say the jira id or some unique name.

**Comment by niik** [comment]
Hi @leo2575, thanks for opening this! I can understand that finding a file among many changed files can be cumbersome. That said I still believe that the default sorting (i.e. alphabetical) is the best approach for scanning, and locating a file and I worry that adding sorting options for this list could end up being confusing.

Given that the current behavior isn't blocking any workflows and given that we haven't seen this feedback before I'm going to close this issue to indicate that it's not something we intend to support in the near-term but it's something we'll be happy to re-evaluate in the future should circumstances change or if we receive more feedback that this is something that's widely requested.

**Comment by happysailingdude** [comment]
I would find being able to sort changed files by date VERY useful. I find it very odd that more people have not identified this issue. Can you please reconsider @leo2575 's request?

**Comment by BorisAnthony** [comment]
1. "Given that the current behavior isn't blocking any workflows" what a strange excuse! The fact that I can't sort the "Changes" list blocks MY workflows. "Quality of life", "good user experience" and all that…

2. "given that we haven't seen this feedback before" is not a "given", see: https://github.com/desktop/desktop/issues/4739 from 2018 with followups by dev team all the way up to 2022 /cc @steveward

**Comment by SevenSpiders** [comment]
I too would love this this feature. Especially sorting by file type

**Comment by reaper-sid** [comment]
Well, it's 2025. Did this get implemented and I missed it?

**Comment by Jaimi** [comment]
I would love this also. The reason is, I need to revert about 300 changes that happened in the last hour (moving files around), but they are hidden amongst 3000 changes that happened 2 hours ago (Mass moved a folder). This would be a quick fix if I could sort by date/time.
