### ISSUE TITLE
Improve experience of using Sentry

### ISSUE THREAD

**Issue by nerdneha** [desktop/desktop#8878]
(ex: filter by version)

**Comment by niik** [comment]
We're now sending the environment (beta or production) as well as the release sha to sentry which allows us to filter (albeit very crudely) by version. We're waiting on upstream support to be able to include our version number as a searchable field.

**Comment by niik** [comment]
We now (since a week ago) send the version number, platform, and error kind (in the case of non-fatal errors) as tags, making them searchable and visible in breakdowns. I've got one more tweak to send the exception name properly.

**Comment by niik** [comment]
As of today we're also correctly sending the name of the exception thrown (most of the time that'll still be `Error` but not always). This change altered the way Sentry groups exceptions but that's worth it in the long run.

With that I consider this issue sufficiently addressed. In future iterations we can consider forwarding deployment events and other niceties that the tool might allow once we have access to fiddle with settings.
