### ISSUE TITLE
Dosent work on linux debian

### ISSUE THREAD

**Issue by emadbaqeri** [desktop/desktop#8883]
Dosent work on linux debian

**Comment by emadbaqeri** [comment]
`file:///snap/github-desktop/63/app/github-desktop:%2520symbol%2520lookup%2520error:%2520/lib/x86_64-linux-gnu/libgobject-2.0.so.0:%2520undefined%2520symbol:%2520g_date_copy`

**Comment by niik** [comment]
Hi @emadbaqeri, I'm afraid we can't provide any support for GitHub Desktop on Linux at this time as it's not an officially supported platform. See #1525 for the tracking issue related to Linux support. In the meantime I'd suggest opening an issue in the repository of the Linux fork of Desktop (https://github.com/shiftkey/desktop/issues).

Best of luck!
