### ISSUE TITLE
Support for .rc (Visual Studio resource-script files). It's a plain text file (.txt).

### ISSUE THREAD

**Issue by DavidPDev** [desktop/desktop#8887]
### Describe the feature or problem you’d like to solve

Currently Github Desktop (Windows OS) doesn't compare changes between .rc files (Visual Studio resource files). It's treated as a binary file:
![image](https://user-images.githubusercontent.com/25801199/72005202-56e5e900-324d-11ea-908d-0d5e175f0e2e.png)

### Proposed solution

I think .rc files can be treated as plain .txt files (not need for syntax coloring)
Would be very useful for comparing project .exe versions, or any other changes in the resource script-definition file.

### Additional context

Useful links:
https://docs.microsoft.com/en-us/windows/win32/menurc/about-resource-files
http://www.winprog.org/tutorial/resources.html

**Comment by steveward** [comment]
@DavidPDev thanks for contributing! Files encoded in UTF-16 (like *.rc files) are recognized as binary by Git. You should be able to configure Git to diff these files by using a .gitattributes file in your repository. Check out this section on [`working-tree-encoding`](https://git-scm.com/docs/gitattributes#_code_working_tree_encoding_code) for how to set that up in your .gitattributes file.

Let me know if you run into any issues with this.

**Comment by DavidPDev** [comment]
Thank you for your reply!
I have tried to modify the .gitattributes without success.
This are the four different tests I've done:

![image](https://user-images.githubusercontent.com/25801199/72052674-e4651f80-32c5-11ea-9539-449030bdad45.png)

Maybe I am missing something?

**Comment by steveward** [comment]
@DavidPDev do you have a repository I could test this out on?
