### ISSUE TITLE
Unable to Use Personal Access Tokens (PAT) in Github Desktop

### ISSUE THREAD

**Issue by aarontitus** [desktop/desktop#8891]
### Describe the bug

Github recently sent me the following alert:
```
You recently used a password to access an endpoint through the GitHub API using git-credential-manager (Microsoft Windows NT 6.2.9200.0; Win32NT; x64) CLR/4.0.30319 git-tools/1.18.3. We will deprecate basic authentication using password to this endpoint soon:
https://api.github.com/user/subscriptions
We recommend using a personal access token (PAT) with the appropriate scope to access this endpoint instead. Visit https://github.com/settings/tokens for more information.
```
The only endpoint I have used to log in with is the Desktop app.
I created a PAT, which says it may be used as a password. I logged out of Github Desktop, then attempted to log back in with my email address and the PAT, instead of my password. I received an authentication error: Bad username or password. Instead, I signed in with my password.

### Version & OS
Win 10, Github 2.2.4

### Steps to reproduce the behavior

1. Go to https://github.com/settings/tokens 
2. Create new PAT
3. Sign out of Github Desktop
4. Sign into Github Desktop
5. Look for a place to enter a PAT. Seeing none, enter PAT in password field.
6. Authentication error.

### Expected behavior

Expected a PAT to act as an alternative to a password; OR see a location to enter a PAT; OR see a link for instructions on how to use a PAT in the desktop.

### Actual behavior

None of those things occurred. It was a regular old email/password login screen.

**Comment by niik** [comment]
Hi @aarontitus, sorry to hear you're having problems. Please try signing in using the web flow (by clicking on the "Sign in with your browser" link) instead.

<img width="410" alt="image" src="https://user-images.githubusercontent.com/634063/71897921-43a52180-3158-11ea-866f-07c8aef550c4.png">

The notification that you got from us is correct if you're using Git from the command line but for API access (which GitHub Desktop needs) you're going to have to use the web flow.

**Comment by steveward** [comment]
@aarontitus as we have not heard back from you I am going to close this issue out. If you are still having issues authenticating please let us know!

**Comment by pperez** [comment]
Hi, i have a related issue, i can login using the web flow, but when i try to clone a repo GH desktop will say that the authentication has failed and ask for my credentials; if i use the actual GH credentials it fails, if i use the PAT (username and PAT as password) it will fail.

If i clone in the command line, it'll first open GH desktop (Same login issue), when i cancel there's an openssh askpass popping up and then i can use my PAT token correctly ...

**Comment by tierninho** [comment]
@pperez Please [fill out a new issue](https://github.com/desktop/desktop/issues/new?template=bug_report.md) so we can assist you separately. Thank you.

**Comment by Stevefrdnt** [comment]
@pperez Do you already find a solution to this problem?

**Comment by BalintN-MPP** [comment]
I have similar problem. It seems we are all confuse where / how to provide the PAT, might be worth some clarification in docs.

**Comment by steveward** [comment]
@BalintN-MPP you do not need to generate a PAT to use with GitHub Desktop unless you are using a third-party service like GitLab or Bitbucket.

**Comment by artarya** [comment]
thanks man

**Comment by patrickehansen** [comment]
what if I don't want to login via the web portal and want to use a PAT? Isn't that the point?

**Comment by linonetwo** [comment]
Enumerating objects: 38, done.
Counting objects: 100% (34/34), done.
Delta compression using up to 8 threads
Compressing objects: 100% (19/19), done.
Writing objects: 100% (22/22), 24.97 KiB | 4.99 MiB/s, done.
Total 22 (delta 11), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (11/11), completed with 6 local objects.        
To https://github.com/tiddly-gittly/TiddlyWiki-CPL
 ! [remote rejected] master -> master (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/gh-pages.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/tiddly-gittly/TiddlyWiki-CPL'
