### ISSUE TITLE
Doesn't prompt for 2FA when cloning a repo

### ISSUE THREAD

**Issue by skirsch** [desktop/desktop#8892]
### Describe the bug

You get a failure to authenticate (and a lack of asking you for 2FA) when trying to clone your repo.

### Version & OS

2.2.4 windows

### Steps to reproduce the behavior

1. I moved all my files over to a new PC. Git Desktop worked normally fetching, etc.
2. Tried to clone another repo I owned. Prompted for username password ... no 2FA prompt. It basically said the authentication failed even with the right credentials.
3. I tried also from github.com to clone (and call the desktop app to complete). same problem.
4. I went to the account page in Github desktop. Logged out and in again. Voila!!!!!! everything worked perfectly.

I moved organizations so that may be part of it, but the error message of saying auth failed without hinting that I needed to go to File>Options>Account>SignOut caused me to waste 2 hours trying to figure this out.
### Expected behavior

Perhaps it could suggest going to Account and logging out and in again if it prompts you for a username password when downloading your own repo.

The logs explained the problem beautifully!!!! I wish I had known there was a log file  could check! I'd definitely incorporate the "reasons" listed in the log file into the error message (or refer people to the logfile when getting an auth failed.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

The logs explained the problem beautifully!!!! I wish I had known there was a log file  could check! I'd definitely incorporate the "reasons" listed in the log file into the error message (or refer people to the logfile when getting an auth failed.

**Comment by niik** [comment]
Hi @skirsch, sorry to hear you're having problems. I'm glad that you were able to resolve your issue.

> The logs explained the problem beautifully!!!!

Could you please attach said logs so that we could take a look?

**Comment by skirsch** [comment]
[2020-01-10.desktop.production.log](https://github.com/desktop/desktop/files/4048801/2020-01-10.desktop.production.log)

sure, here it is.

Note that when i started up, I was shown as "logged in" as skirsch in the File>Accounts menu, but when i tried picking a repo, NOTHING showed up. So my logged in state was "bogus" and Github Desktop should have said, "hey something is wrong" but it was completely silent on that leaving me puzzled as to the problem since the File>Account page showed I was clearly logged in. It should have noticed the token was invalid at that point and suggested I logout and in again which would have cured the problem. Instead, i ended up typing in the repo name manually, then getting prompted for ONLY username/password (and never my 2FA), so auth always failed. It was frustrating.

**Comment by tierninho** [comment]
Thanks for sharing! We will look at the logs and consider some language tweaks to make things easier in the future.

**Comment by skirsch** [comment]
Cool! thanks!

**Comment by avdi** [comment]
I just encountered this as well, but logging out and logging in again didn't fix it 😞
