### ISSUE TITLE
Can't sign in desktop

### ISSUE THREAD

**Issue by YangLing-HKD** [desktop/desktop#8893]
Hello:

I can login in my account on line IE explore. but can't sign in desktop, message showed fetch failed.

it looked username and pass are ok.

and I can see the folder name in Github desktop, fetch failed, so can't clone either.

can you give me some suggestions ? thx

Regards
YL
![1578638657(1)](https://user-images.githubusercontent.com/7287468/72131636-d394d680-33b7-11ea-8243-3776826f7d75.png)

**Comment by niik** [comment]
Hi @YangLing-HKD, since you closed this issue I assume you were able to resolve or work around your problem. If not, feel free to reopen this and if you do please also attach your logs by opening the `Help` menu and selecting `Show Logs...`
