### ISSUE TITLE
logged in but cannot commit

### ISSUE THREAD

**Issue by urfdvw** [desktop/desktop#8894]
### Describe the bug

signed in from 'options' but got this error. Was working but stopped working after a while.
![image](https://user-images.githubusercontent.com/17154432/72162764-90733d00-3390-11ea-9dd1-b863ffc3d0ab.png)

### Version & OS

Version 2.2.4
win10 home 1903

### Steps to reproduce the behavior

does not know the error happened since when. never recovered

### Expected behavior

should be able to commit after signing in

### Actual behavior

![image](https://user-images.githubusercontent.com/17154432/72163068-1b543780-3391-11ea-87c8-12576f8b8e3c.png)

### Additional context

can explore repositories of user, can clone. but cannot commit

**Comment by steveward** [comment]
@urfdvw thanks for contributing! It looks like you need to set your name and email address -- you can do this in GitHub Desktop by going to the menu and selecting `File` > `Options` > `Git`. Make sure you use an email address that has been added to your GitHub account. After doing that you should be able to commit. I'm going to close this out, but let me know if you run into any further issues.
