### ISSUE TITLE
Can't find repo message with pending Desktop update is a "false positive" and should be improved

### ISSUE THREAD

**Issue by peterennisrda** [desktop/desktop#8895]
### Describe the bug

Repository not found error when update is pending.

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

Windows 10. Updated Desktop to:

![Capture248](https://user-images.githubusercontent.com/1280523/72180993-49d80f80-339d-11ea-8884-4a065b5da13c.png)

### Steps to reproduce the behavior

1. Existing repo open in Desktop
2. Restart warning for new version.
3. Error message is displayed.

### Expected behavior

The repo is not lost, just blocked due to Desktop pending update.
It is somewhat disconcerting to see a message basically saying
"all you work has disappeared..."

### Actual behavior

See above.

Installing the update fixed the issue, but the message should
be fixed to better indicate the actual status of the repo.

### Screenshots

Add screenshots to help explain your problem, if applicable.

Before update:

![Capture246](https://user-images.githubusercontent.com/1280523/72181363-092cc600-339e-11ea-86a2-00979dd7e1f0.png)

After update:

![Capture247](https://user-images.githubusercontent.com/1280523/72181378-121d9780-339e-11ea-8617-2cceb2dd306a.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@peterennisrda Thanks for filing this. Please share your logs if possible as there may be some clues in there. See the Help menu in Desktop.

**Comment by peterennisrda** [comment]
@tierninho 

[2020-01-10.desktop.production.log](https://github.com/desktop/desktop/files/4047895/2020-01-10.desktop.production.log)

**Comment by tierninho** [comment]
I spotted this error:

```
2020-01-10T19:24:53.863Z - error: [ui] Could not load old contents for syntax highlighting
Error: spawn C:\Users\Administrator.RDA\AppData\Local\GitHubDesktop\app-2.2.0\resources\app\git\cmd\git.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

Looks like we had a fix for it awhile back [here](https://github.com/desktop/desktop/issues/5289) so an investigation will be needed. Thanks for using Desktop.

Can someone from @desktop/core take a look 👀

**Comment by steveward** [comment]
Closing this as stale as it seems it was likely an edge case. I couldn't find any recent reports of this behavior and was unable to reproduce anything similar after triggering an update.
