### ISSUE TITLE
I dont see my merges in a branch

### ISSUE THREAD

**Issue by GouthamRamireddy2** [desktop/desktop#8898]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by Rexogamer** [comment]
Hey! Please could you fill out the template so we can help with your issue? Thanks!
