### ISSUE TITLE
Git File RM 

### ISSUE THREAD

**Issue by PacificProMedia** [desktop/desktop#8902]
### Describe the feature or problem you’d like to solve

A UI method to remove file cache from git repo. 

### Proposed solution
When right clicking files in the changed files list, there is a add to .gitignore option. I propose adding a remove file cache option that utilizes the "git rm --cached {file}" and "git commit --amend -CHEAD" commands.

How will it benefit Desktop and its users?
If a file has been committed to the repo before that file was added to .gitignore, then the repo will continue to track that files changes. This would prevent the user of git desktop from having to go to CMD/Terminal and manually removing the file. The benefit is that it provides a seamless and more complete Git experience from the GUI

**Comment by steveward** [comment]
Thanks for contributing @PacificProMedia! We are tracking improvements to ignoring files in https://github.com/desktop/desktop/issues/2537, so I am going to close this issue out. Please follow along there for updates.
