### ISSUE TITLE
Здравствуйте я разработчик и владелец GitHub Desktop как я могу получать деньги

### ISSUE THREAD

**Issue by vova557** [desktop/desktop#8905]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by vova557** [comment]
Здравствуйте я разработчик и владелец GitHub Desktop как я могу получать деньги

**Comment by tierninho** [comment]
@vova557 Это не место для таких запросов.

**Comment by vova557** [comment]
А где я могу об этом написать,чтобы меня поняли
