### ISSUE TITLE
Miscoloring of a list of JS static properties

### ISSUE THREAD

**Issue by massimilianokraus** [desktop/desktop#8908]
### Describe the bug

A list of static properties in a JS class is miscolored: the first line is rendered differently than the others.

### Version & OS

GitHub Desktop 2.24
MacOS Catalina 10.15.2

### Steps to reproduce the behavior

Create a `.js` file. Write a class. Inside the class, put a list of at least 2 static properties, like:

```
class Constants {
    static CONST1 = 'value1'
    static CONST2 = 'value2'
    // ...        
}
```

### Expected behavior

In every row containing the static properties, `static` is red and the property's name is white.
Or, at least, the coloring is coherent among all rows.

### Actual behavior

In the first row, `static` is red and `CONST1` is white.
On every subsequent line, both the `static` keyword and the name of the constant are violet.

### Screenshots

<img width="235" alt="Screenshot 2020-01-13 at 09 48 37" src="https://user-images.githubusercontent.com/12040890/72242953-db888c80-35ea-11ea-9123-74792ca0de47.png">

### Additional context

The semicolon at the end of the rows is not important: adding or removing it does not change the issue.

**Comment by outofambit** [comment]
Hi @massimilianokraus thanks for filing this! This is indeed an issue, but its upstream in CodeMirror, one of our dependencies. As such, there's not much we can do in desktop until CodeMirror fixes the issue, which is being tracked at https://github.com/codemirror/CodeMirror/issues/5243. It doesn't sound like there's plans to address this soon, but that would be the place to ask.

Desktop stays relatively on top of CodeMirror updates, so I'm going to close this issue. Thanks for reaching out.
