### ISSUE TITLE
Improve defaults on "New Branch" modal

### ISSUE THREAD

**Issue by neiker** [desktop/desktop#8909]
1 - Even if my current and default branch is `develop`, this modal shows `master` as default.
![imagen](https://user-images.githubusercontent.com/688444/72264307-4b057880-35f9-11ea-96f9-d212e6fdea0e.png)

2 - On next step "Leave my changes on xxxx" is selected instead of "Bring my changes to yyyy"
![imagen](https://user-images.githubusercontent.com/688444/72264409-7d16da80-35f9-11ea-967a-b036cd40faf1.png)

This is confusing because `git checkout -b yyyyy` has exactlly the oposite defaults on both cases.

**Comment by billygriffin** [comment]
@neiker Thanks for the issue! Would you mind clarifying something in your first screenshot, the New Branch checkout one?

Are you saying that your default branch in the repo on GitHub.com is `develop`, but it's showing your default branch as `master` instead? Is `master` just another branch in the repo but you've changed the default branch to `develop`? I believe the intent of the new branch checkout is for the default branch to always be the first selection, and your current branch to be second. 

This is indeed different from the vanilla `git checkout -b yyyy` as you state, but we don't think mirroring the behavior of Git itself is always appropriate. In this case, starting a new branch from the default branch in many cases is what people want, and I'd be hesitant to change it at this point.

However, if `develop` is the default branch in your `repo` and GitHub Desktop is showing `master` instead, that's definitely something we'd want to look at more closely.

**Comment by neiker** [comment]
I just realize "Default Branch" is something implemented by GitHub and not is included on git itself. This specific repo is hosted con GitLab.

**Comment by billygriffin** [comment]
Ah, that makes more sense, thanks @neiker. GitHub Desktop is built to be as intuitive and user friendly as possible for GitHub repos. And unfortunately that occasionally has the side effect of making it less so for repos hosted outside of GitHub. While we try to make the product useful for repos regardless of where they're hosted, we design the product largely around optimizing the experience for GitHub users. Sorry that this is less than ideal, but we're going to keep it as is, and really appreciate you taking the time to create an issue.
