### ISSUE TITLE
Feature request: allow items in "Current repository" list to be named

### ISSUE THREAD

**Issue by NeilMacMullen** [desktop/desktop#8914]
### Describe the feature or problem you’d like to solve

At the moment the current repository list uses the folder name and provides the full path as a tooltip.  This is fine as long as each repo is in a uniquely named folder but is confusing when they have the same name.  (e.g. if you follow a workspace workflow where different branches-in-progress are checked out to different parts of the physical drive, you can't easily tell which version you are about to select because the display name is the same for all of them.  

### Proposed solution

Allow the user to provide a display name for the items in the current repository list.  This can default to the folder name but right clicking on the item should provide a "rename" option.
It would also be a convenience if each item showed the branch name (in smaller type) alongside it.

How will it benefit Desktop and its users?

Better support a workspace workflow

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

![image](https://user-images.githubusercontent.com/9131337/72357308-a8c1bf80-36e2-11ea-9f54-bbfd6e5ed941.png)

**Comment by billygriffin** [comment]
Hi @NeilMacMullen, are these GitHub repositories? We recently did work in this area around making the experience work significantly better but it assumes that the person is a GitHub user. While we support working with repos from other hosting services, our primary goal is to make the experience between GitHub Desktop and GitHub.com shine, and therefore likely won't be changing this to facilitate others.

**Comment by NeilMacMullen** [comment]
@billygriffin I'm not sure the experience is any different with GitHub repos but perhaps I haven't explained it well.... Here's a simple repro case....

- mkdir \work\wkspc1
- cd \work\wkspc1
- git clone ...someRepo...
- … checkout branch1, start making some changes
- 
- mkdir \work\wkspc2
- cd \work\wkspc2
- git clone ...someRepo...
- … checkout branch2, start making some changes
 
In this case, when you add the local repos (File/Add local repository) the display name will be "someRepo" for both entries regardless of whether the origin was GitHub or some other source.

**Comment by billygriffin** [comment]
@NeilMacMullen Thanks for the additional information. When the repos are pushed up to GitHub, they'll be grouped by the organization that they're in and therefore visually disambiguated that way. We know it's not ideal for repos that aren't published to GitHub, but we're going to stick with the way it is currently unless we get significantly more signal that a critical mass of users are experiencing this as a problem. Really appreciate you describing the issue regardless. ❤️
