### ISSUE TITLE
Can't clone private repository

### ISSUE THREAD

**Issue by Martin-Thomsen** [desktop/desktop#8916]
### Describe the bug

Over the last few days I have attempted to clone a private repository without luck. I have looked at a lot of other issues trying to find a solution, however nothing has worked so far. When I attempt to clone the repository via Github Desktop it comes up with an authentication error, and no matter what I have tried so far it keeps popping up when I try to clone the repo. I have attempted to clear windows credentials, log out/back in of Github Desktop, reinstall Github Desktop, add an exception to Github Desktop in my firewall (I use Norton Antivirus for this), clear the token and re-add it, resetting my password and probably other things I don't remember.

### Version & OS

Version 2.2.4

### Steps to reproduce the behavior

1. Open Github Desktop
2. Click 'File'
3. Click 'Clone repository'
4. Click on the repository
5. Click 'Clone'
6. After a few seconds, error pops up.

### Expected behavior

Expected it to clone the repository to my computer.

### Actual behavior

Gave me an authentication error instead of cloning the repository.

### Screenshots

![image](https://user-images.githubusercontent.com/57629580/72368678-d6b4fd00-36fe-11ea-9478-84f206ecab8d.png)

### Logs

[2020-01-14.desktop.production.log](https://github.com/desktop/desktop/files/4060574/2020-01-14.desktop.production.log)

### Additional context

I think I have explained it as best as I could. I hope you are able to help me!

**Comment by tierninho** [comment]
@Martin-Thomsen Thanks for filing. 

Some common reasons related to this issue include:
- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)

Let us know the results please.

**Comment by Martin-Thomsen** [comment]
Hi @tierninho Thank you for your response, however I am unsure if you read all of it.

I have already logged in to my account, and also several times logged out and back in. I also have access to the repository, since it shows up in the list where I can pick it from. I am 100% sure the repository is not archived on GitHub and I do not use SSH authentication.

One thing I forgot to add, was that I had no issues cloning the repository on my laptop, I am only having this issue on my desktop PC.

**Comment by tierninho** [comment]
Thanks for the confirmation.

I believe a bad install occurred as I spotted:
```
> 2020-01-14T16:57:57.330Z - error: [main] Malformed launch arguments received: C:\Users\m-s-t\AppData\Local\GitHubDesktop\app-2.2.4\GitHubDesktop.exe,--squirrel-firstrun
```

You can perform a full reinstall by following these steps:

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory (use Task Manager if not there)
4. Go to `AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

Let us know if that helps.

**Comment by Martin-Thomsen** [comment]
Thank you for the quick response. Unfortunately that did not help me. I deleted both directories both in the Local and the Roaming directory and reinstalled GitHub Desktop, yet it gave me the same error.

**Comment by tierninho** [comment]
@steveward Any ideas here?

**Comment by steveward** [comment]
@Martin-Thomsen have you been unable to clone any private repository -- even one created under your own personal account?

**Comment by Martin-Thomsen** [comment]
Hi @steveward sorry for the slow reply, the website tab bar did not prompt me with a new message. I just attempted to create a new private repository, and I can not clone this repository either.

**Comment by steveward** [comment]
Thanks for testing that out @Martin-Thomsen. Does your laptop have a similar setup (i.e. Norton Antivirus installed)? We've definitely seen issues with Norton in the past -- have you tried temporarily disabling it to see if that helps?

**Comment by Martin-Thomsen** [comment]
My laptop does not have Norton Antivirus installed, no. I have tried turning several options from Norton off, yet none of them affected the cloning.

**Comment by tierninho** [comment]
@Martin-Thomsen Here are a few more things to try: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/https-cloning-errors

If applicable, you might want to try and mirror your settings from your laptop.

**Comment by Martin-Thomsen** [comment]
Correct me if I'm wrong, but the solutions in there seems to be either unapplicable to my issue or something I have already tried. Is there something else I might try?

**Comment by Martin-Thomsen** [comment]
I'm not sure what is confusing you. I am using GitHub Desktop, but the link you sent me doesn't seem to be for GitHub Desktop.

**Comment by steveward** [comment]
@Martin-Thomsen have you tried cloning a repository using `git clone` from the command line to see if that succeeds? You can install [Git for Windows]( https://git-scm.com/download/win) to try that out.

**Comment by Martin-Thomsen** [comment]
@steveward I just tried that, and it downloaded the branch I was currently viewing. I then added it to GitHub Desktop as a local repository, which worked fine. However I can't fetch origin or pull anything from the repository, it just gives me this error: 
![image](https://user-images.githubusercontent.com/57629580/73019089-360fbd00-3e23-11ea-9d79-3b801e6bec1f.png)

**Comment by Martin-Thomsen** [comment]
This is the log file if you want to take a look at that:
[2020-01-23.desktop.production.log](https://github.com/desktop/desktop/files/4105201/2020-01-23.desktop.production.log)

**Comment by AQIBRIAZ** [comment]
Hello @Martin-Thomsen  I had the same issue. THe solution is to paste the following url in the git deskstop app 

https://myusername:mygithubpassword@github.com/myusername/project


If you have a special character in your password, replace it with values from this website https://support.brightcove.com/special-characters-usernames-and-passwords case example: p@ssword --> p%40ssword


also review this post 
https://github.community/t5/How-to-use-Git-and-GitHub/Clone-private-repo/td-p/12616

Hope this solve your issue.

Github deskstop app has this bug and github team need to solve it


Regards

**Comment by steveward** [comment]
@Martin-Thomsen and @AQIBRIAZ we have seen quite a few of these authentication issues caused by modified registry settings. See the [`authentication issues due to modified registry entires`](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#authentication-errors-due-to-modified-registry-entries) section in our known issues document to check if this could be the cause of your authentication issues.

**Comment by Martin-Thomsen** [comment]
@steveward That worked for me! I had an Autorun in my HKEY_CURRENT_USER\Software\Microsoft\Command Processor\ and deleting that resolved the issue for me, I can now push and pull! Thank you so much for your help and patience!

**Comment by rabrou** [comment]
It worked for me to log off and in again. However, all of my files have disappeared....

**Comment by yzy1996** [comment]
How to solve it in macOS?

**Comment by yixing-liu** [comment]
I have the same issue. Signing out and then back in didn't work for me.
I am not able to clone any my private repo using my Github Desktop app.

**Comment by yakla** [comment]
i have the same problem but i couldn't find HKEY_CURRENT_USER\Software\Microsoft\Command Processor\ in widows registry

**Comment by orangepropeller** [comment]
> Thanks for the confirmation.
> 
> I believe a bad install occurred as I spotted:
> 
> ```
> > 2020-01-14T16:57:57.330Z - error: [main] Malformed launch arguments received: C:\Users\m-s-t\AppData\Local\GitHubDesktop\app-2.2.4\GitHubDesktop.exe,--squirrel-firstrun
> ```
> 
> You can perform a full reinstall by following these steps:
> 
> 1. Close GitHub Desktop
> 2. Open File Explorer
> 3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory (use Task Manager if not there)
> 4. Go to `AppData%` and delete the `GitHub Desktop` directory
> 5. Reinstall GitHub Desktop from http://desktop.github.com
> 
> Let us know if that helps.

Reinstallation solved my problem.
