### ISSUE TITLE
GitHub Desktop don't show all changed files

### ISSUE THREAD

**Issue by fabas1** [desktop/desktop#8919]
### Describe the bug

This issue shows up time to time. Then you go from "History" to "Changes" GitHub Desktop shows only one changed file .

### Version & OS

GitHub Desktop version 2.2.4 , W10 Pro 1909

### Steps to reproduce the behavior

1. While you are in "History" tab.
2. Click on 'Changes'
3. See that app shows not all changed files

### Expected behavior

Should show all changed files which are in repository.

### Actual behavior

Shows only one file, but writes that more files were changed

### Screenshots

![bug](https://user-images.githubusercontent.com/23627692/72421111-94d09900-3788-11ea-8b76-40f94a10c4e8.png)

### Logs

[2020-01-15.desktop.production.log](https://github.com/desktop/desktop/files/4069716/2020-01-15.desktop.production.log)

### Additional context

File types were changed: xml, js, json, properties

**Comment by tierninho** [comment]
@fabas1 Possible to fill in the rest of the template and upload your logs? See the Help menu in Desktop.

Also, what kind of files were you changing? Any other relevant data you can share? Thanks.

**Comment by tierninho** [comment]
Thank you for the details. 

Nothing stands out thus far, but please let us know if the issue is still outstanding if:
- switch repos and return to your repo
- restart Desktop

Also, are you using a proxy? I spotted an error which hints at DNS issues:

`fatal: unable to access: Could not resolve host`

Lastly, do you recall if you received a "git pull" error message at the same time? I spotted:

```
 ! [rejected]          master -> master (fetch first)
error: failed to push some refs 
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by tierninho** [comment]
@ As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by rifatwahid** [comment]
You could try running `git config core.filemode false` in the repository to see if that resolves things.
