### ISSUE TITLE
Merge request

### ISSUE THREAD

**Issue by daikhioualid** [desktop/desktop#8921]
Hello team,

My problem is with GitHub desktop app,  i can't make custom merge between 2 branches, for example i want to merge some commits but not all the commit (we can't do that).

I really appreciate if you make this request, because it help a lot, for know to do that i have do it on the command line.

Thanks.

Oualid

**Comment by steveward** [comment]
Thanks for contributing @daikhioualid. Are you wanting something like `git cherry-pick` to be added to GitHub Desktop? If you could share some more details about the specific workflow you are hoping to achieve (and what you currently do on the command line) that would be helpful.

**Comment by daikhioualid** [comment]
Yes Steve here what i do git cherry-pick $COMMIT_ID, but in my case some times i have 20 - 50 commit separately. :( 

If we can just can do the merge on the compare section between 2 branches (in "Ahead" and "Behind" section).

**Comment by billygriffin** [comment]
Hi @daikhioualid, thanks for the issue! This isn't something we think is a common enough workflow to build a feature for this special case, but I would love to understand your use case a bit more as to why you're frequently merging only a portion of commits from one branch to another if you don't mind sharing. I'm going to close this issue as something we don't intend to support (and we have another issue requesting cherry picking commits across branches here: https://github.com/desktop/desktop/issues/1685), but I'd love to hear your thoughts and to better understand how you're working and why this might be useful for you.
