### ISSUE TITLE
delete repositories

### ISSUE THREAD

**Issue by kushalvishwak** [desktop/desktop#8925]
hi , 

I don't know how to run the github account , i made the false repository so please delete it all because  i don't required it now.
And i need fresh start so please kindly do for the same.

thanks
kushal

**Comment by tierninho** [comment]
@kushalvishwak Thanks for the issue. 

To delete a repository on Desktop, select the repository from the left-side menu and choose `Remove...` from the Repository menu. You will have the option to remove it from the remote if you check the box. 

![Screen Shot 2020-01-15 at 9 54 00 AM](https://user-images.githubusercontent.com/14828183/72466456-fc80e700-377c-11ea-8148-6f9ea188095d.png)

Happy to help further as needed!
