### ISSUE TITLE
Summary page to have README.md

### ISSUE THREAD

**Issue by anerjan** [desktop/desktop#8932]
There is plenty of space on summary page that can be used to show Readme.md

We often clone multiple repos locally and forgot what they were about. additionally readme.md have run scripts that can be handy on summary page.

**Comment by steveward** [comment]
Thanks for the feedback @anerjan. This feature request was previously brought up in https://github.com/desktop/desktop/issues/8687 -- I'm going to drop your feedback into that thread.
