### ISSUE TITLE
Can not log in Github when I push in Git 

### ISSUE THREAD

**Issue by XziSun** [desktop/desktop#8943]
### Cannot type into characters
![2020-01-18 222836](https://user-images.githubusercontent.com/52070155/72665301-f3746c00-3a41-11ea-9ce4-3f9307cdd7a5.jpg)

I can not type in any characters but the first one of my password. I cannot figure out the issue.  I would really appreciated if you can help me with that!

**Comment by steveward** [comment]
@XziSun thanks for the report. Are you using any input devices on this machine that could be causing this issue? Have you previously been able to log in to your account in GitHub Desktop?

**Comment by tierninho** [comment]
@XziSun  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
