### ISSUE TITLE
ERROR: CANNOT SPAWN C:/ ask-pass-trampoline.bat :NO ERROR FATAL: Could not read USERNAME from Github.com: terminal prompts disable

### ISSUE THREAD

**Issue by fernandocompean** [desktop/desktop#8945]
### Describe the feature or problem you’d like to solve

When I try to fetch or push show this error, actually i coudnt clone the repo trought the destop app, I did it with cmd and then opened and existing local repo
My GitDesktop version is 2.2.4
Windows 10

### Proposed solution

I've tried uninstall and install again, even deleted de folder with the user information, my user and password are correct, I can make changes (pull / push / merge /stage etc) but just with cmd, and I really dont have problem with that but I want to know why this error is..

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.
![image](https://user-images.githubusercontent.com/44001679/72745927-78f93880-3b76-11ea-8af5-5b9c58b3fb2a.png)

**Comment by steveward** [comment]
Thanks for the report @fernandocompean. We have a guide for debugging this error that lists some causes and workarounds:

https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789

The most common cause is the Windows Registry being modified by another application. Let me know if those solutions don't get things working for you.
