### ISSUE TITLE
Confirmation dialog before quitting option in Settings.

### ISSUE THREAD

**Issue by adamsir** [desktop/desktop#8946]
### Describe the feature or problem you’d like to solve

Show confirmation dialog before quitting with ⌘Q option in Settings.

### Proposed solution

This feature will remove accidentally quitting of the client by pressing the shortcut key for quitting apps.

### Additional context

Possible solution could look like this:
![Untitled 3](https://user-images.githubusercontent.com/5871877/72746969-b9c37280-3bb3-11ea-97a2-e67693b38711.png)

**Comment by outofambit** [comment]
Hi @adamsir thanks for filing this issue! Can you share more about the motivation for this? Are you losing data or work by closing the app accidentally?

**Comment by adamsir** [comment]
Hi @outofambit. Thanks for answer, tl;dr yes, and yes. Let me describe the situation. 

The developer is finishing the project sprint and he is switching between apps by ⌘TAB and sometimes happens in the rush that he accidentally hits the ⌘Q instead of ⌘TAB and he is little bit confused in the moment, why the app is not opened anymore. 

In the next moment, the developer reopen the app and he is frustrated again, because he lost the unfinished commit message and selected(picked) files, because he didn't want to commit all files.

I think this simple feature can save nerves(time) to many users and also it is a standard optional ux feature in a software, such as browsers or IDEs for example.

If you don't mind, I would like to start working on a pull-request which will contains the following functionality: 
- evoke quitting confirmation dialog if quit hotkey is pressed and evoking the dialog is allowed in settings
- if the quitting dialog is not allowed, the behavior will be the same as it is.
- if the quitting dialog is allowed and the user wants to quit the app by closing button, the dialog won't be evoked.

What do you think?

**Comment by adamsir** [comment]
@outofambit Yes, the user will lost file selection and the draft of commit message.

**Comment by tierninho** [comment]
@adamsir Thanks for the input. 

I have personally used this hack to change the key-cmds:

- Open System Preferences.
- Go to Keyboard and open the Shortcuts tab.
- In the left pane, select App Shortcuts.
- Use the new shortcut button, which looks like a plus sign (+), to create a new GitHub Desktop-specific shortcut for the command “Quit GitHub Desktop” (no quotes). I suggest `⌥⌘Q`, which is `option-cmd-Q`

![Screen Shot 2020-01-30 at 2 06 22 PM](https://user-images.githubusercontent.com/14828183/73501438-0b18f200-436a-11ea-9fe1-9cb656878c7d.png)

In the meantime, going to close this issue unless we see more users request such a feature. Happy to reconsider then. Thanks for using Desktop!

**Comment by adamsir** [comment]
@tierninho thanks for the tip. Anyway, I still think the quit-prompt settings option is not a big deal to develop. I understand it's edge case but very helpful when the situation described above will happen. Another software such as VSCode or Chrome already have this option feature. Demons are in details.
