### ISSUE TITLE
No mine/theirs to resolve conflict

### ISSUE THREAD

**Issue by Liturgist** [desktop/desktop#8947]
### Describe the feature or problem you’d like to solve

I have set *.bin to be binary files using "-merge -text" in the .gitattributes file. There is a devl1 and devl2 branch. The devl1 branch will merge into master with no conflict (as expected). However, trying to merge the devl2 branch exposes a conflict. However, it do not appear to provide a mechanism in GitHub Desktop to choose mine or theirs. The following dialog box appears.

![image](https://user-images.githubusercontent.com/2530958/72748175-21f66200-3b7c-11ea-87d0-d4372fcbc16a.png)

Choosing to complete the merge will apparently assume "mine" (in master) is to be kept. How can I choose "theirs" to use the file from the devl2 branch? Must I use the command line?

### Proposed solution

Providing a mine or theirs option will benefit Desktop users who must manage binary files.

### Additional context

Here is a script that I used to create the master, devl2, and devl2 branches before turning to GitHub Desktop to do the merge. After running this script, the repository is added to GitHub Desktop.

```
set "TEST_FILE=t.bin"
set "BASEDIR=C:\src"
set "PROJNAME=todo-list"
set "TARGETDIR=%BASEDIR%\%PROJNAME%"
echo TARGETDIR is %TARGETDIR%

cd /d "%BASEDIR%"
if exist "%TARGETDIR%" (rmdir /s /q "%TARGETDIR%")
mkdir "%TARGETDIR%"
cd "%TARGETDIR%"

REM Fetch the standard Visual Studio .gitignore. Then, add *.dtproj.user
curl https://raw.githubusercontent.com/github/gitignore/master/VisualStudio.gitignore >".gitignore"
echo>>".gitignore" *.dtproj.user

REM Create a .gitattributes file. Make .bin files binary.
echo>>".gitattributes" *.sln -merge -text
echo>>".gitattributes" *.suo -merge -text
echo>>".gitattributes" *.vcxproj -merge -text
echo>>".gitattributes" *.dtproj -merge -text
echo>>".gitattributes" *.dtsx -merge -text
echo>>".gitattributes" *.bin -merge -text
git init
git add *
git commit -m "initial commit"

git checkout master
git branch devl1
git checkout devl1
echo>"%TEST_FILE%" Line 1 of %TEST_FILE in branch devl1
git add "%TEST_FILE%"
git commit * -m "initial commit for branch devl1"

git checkout master
git branch devl2
git checkout devl2
echo>"%TEST_FILE%" Line 1 of %TEST_FILE in branch devl2
git add "%TEST_FILE%"
git commit * -m "initial commit for branch devl2"

git checkout master
exit /b 0
```

**Comment by steveward** [comment]
@Liturgist thanks for contributing! I see you commented in #8248 which is a related issue to this one. I'm going to close this issue out in favor of #8248 to help keep our open issues manageable.
