### ISSUE TITLE
While trying to clonate any repository to my git repository I get the next message: “The host is down. Check your Internet connection and try again.”

### ISSUE THREAD

**Issue by pabloramoscovestro** [desktop/desktop#8950]
### Describe the bug

While trying to clonate any repository to my git repository I get the next message: “The host is down. Check your Internet connection and try again.” This bans me to clonate.

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment]
Thanks for contributing @pabloramoscovestro. Could you upload the log file from GitHub Desktop so that I could get some more information about this error?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by pabloramoscovestro** [comment]
Hello Steve,

Thank you for your reply.
I think I solved the problem.  I could see that one month ago someone else had the same problem, and due to the lack of the same issue in other users, the problem  was considered solved. Therefore I would like to at least provide my small experience about it:

Since I am working with a company, I had to properly configure the proxy in the .gitconfig file. Everybody in the net provides the next command to be added to the file:


git config --global http.proxy http://proxyUsername:proxyPassword@proxy.server.com:port

It did not work to me as everybody suggested. Instead the next format worked:
[http]
        proxy = http://proxyUsername:proxyPassword@proxy.server.com:port
        sslverify = true
        sslCAInfo = /usr/share/ca-certificates/extra/certificate.cr
Where the last line must point out the correct certificate . I think this just must be pointed out if you work with a OS hosted in a virtual machine. It is not my case, however, you need the certificate.  Maybe everybody knows that you need to begin with [http], but nobody says it.

Nonetheless, here I provide you the log.zip. I can see that there was a problem with JSON[0] that I never solved. Maybe it is interesting for you. I could see people complaining about it too.

Best regards,

Pablo Ramos
Ph.D. at Covestro Deutschland AG

[cid:image002.png@01D5D108.F92E6AD0]

covestro.com<http://www.covestro.com>
Telephone
+49 214 6009 7356

Covestro Deutschland AG
COVDEAG-Chief Commer-PUR-R&D-EMEA-PMD
B103, R164
51365 Leverkusen, Germany
pablo.ramos@covestro.com

The processing of personal data is necessary to communicate and provide our services. Read more here:  privacy-information<https://www.covestro.com/-/media/covestro/country%20sites/global/documents/Data_Privacy_Note%202018_EN>.
Please manually add the sentence in your language here. Please make sure that this link is not lost when the sentence is transferred (Copy --> Paste --> “Merge Formatting”).

**Comment by steveward** [comment]
@pabloramoscovestro I'm glad to hear you were able to get things working. Providing better support for configuring proxies is on our roadmap.
