### ISSUE TITLE
Loading repositories is very slow

### ISSUE THREAD

**Issue by asgeirn** [desktop/desktop#8955]
### Describe the feature or problem you’d like to solve

Opening a repository from GitHub is slow if the user has access to many repositories.

### Proposed solution

By caching the repositories locally, the user would quickly be able to open all but the most recently added repositories.

### Additional context

UI should indicate that it's presenting a cached view, allowing the user to wait for a refresh if the repository is not available in cache.

**Comment by kuychaco** [comment]
@asgeirn thanks for your feedback. Could you please elaborate by providing repro steps and clarifying what you mean when you say "opening a repository from GitHub"? Do you mean when you're cloning from GitHub.com? A screenshot of what you're observing would be helpful as well.

**Comment by asgeirn** [comment]
@kuychaco thanks for your response, sorry for my less-than-obvious description. 

When opening the `Clone repository...` dialog, this spinner is presented for quite some time due to the amount of repositories available to my account.

![bilde](https://user-images.githubusercontent.com/58614/72938160-be7e5700-3d6a-11ea-8608-bdf3100de1de.png)

The spinner only shows the first time after starting the app, so it's clearly cached in-memory - I'd love to see the same cache being persisted to disk for a faster initial startup.

**Comment by tbradsha** [comment]
+1

**Comment by jrshelby** [comment]
+1
This is a huge issue for teachers - I have access to all of my student repositories within the class organization, as well as access to the student repos from previous years unless I literally delete them. This is many thousands of repos.

**Comment by carrill1** [comment]
+1
