### ISSUE TITLE
Fetch is failing and causing authentication issues

### ISSUE THREAD

**Issue by mayurigupta13** [desktop/desktop#8961]
### Describe the bug

Everytime I click on 'Fetch Origin', it displays an error 'Authentication failed....'. There is no issue with authentication because I'm able to do commits etc. At the time of commit, the origin fetching happens on its own which never gives any error.

### Version & OS

Version 2.2.4 on Windows 10 Enterprise 2019

### Steps to reproduce the behavior

Everytime I click on 'Fetch Origin', it displays an error 'Authentication failed....'. There is no issue with authentication because I'm able to do commits etc. At the time of commit, the origin fetching happens on its own which never gives any error.

### Expected behavior

Fetching origin should not give any errors.

### Actual behavior

It fails with authentication error.

### Screenshots

Add screenshots to help explain your problem, if applicable.
![image](https://user-images.githubusercontent.com/42770808/72965810-46a04300-3de3-11ea-8f8f-e2cb4eb5cb91.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by kuychaco** [comment]
Thanks for the report!

Could you attach the full log files? The Help | Show Logs in Explorer menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by mayurigupta13** [comment]
[2020-01-23.desktop.production.log](https://github.com/desktop/desktop/files/4107887/2020-01-23.desktop.production.log)
[2020-01-24.desktop.production.log](https://github.com/desktop/desktop/files/4107888/2020-01-24.desktop.production.log)
[2020-01-21.desktop.production.log](https://github.com/desktop/desktop/files/4107889/2020-01-21.desktop.production.log)
[2020-01-22.desktop.production.log](https://github.com/desktop/desktop/files/4107890/2020-01-22.desktop.production.log)

**Comment by tierninho** [comment]
@mayurigupta13 Based on the errors seen below, it seems to indicate a connectivity problem. Do you currently have any antivirus software installed other than the default antivirus that ships with Windows?

Additionally, are you using a proxy server to access the internet? Git requires special configuration to work behind proxy servers, see https://github.com/desktop/desktop/issues/1998, #2789 

If you are behind a corporate proxy, try:

`git config --global http.proxy http://proxyuser:proxypwd@proxy.server.com:8080`

Errors in logs:
```
2020-01-23T23:38:05.015Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/mayurigupta13/azure-docs-pr.git/': Could not resolve host: github.com
2020-01-23T23:38:06.651Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
TypeError: Failed to fetch
2020-01-23T23:38:08.312Z - info: [ui] Current tutorial step is NotApplicable
2020-01-23T23:38:08.312Z - warn: [ui] getFetchPollInterval: failed for mayurigupta13/azure-docs-pr
TypeError: Failed to fetch
2020-01-22T00:10:59.775Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune upstream` exited with an unexpected code: 128.
stderr:
fatal: unable to access 
```

**Comment by jasonta** [comment]
I am having the same issue, except my log looks like:

> `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
> stderr:
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> 
> (The error was parsed as 2: Authentication failed. Some common reasons include:
> 
> - You are not logged in to your account: see File > Options.
> - You may need to log out and log back in to refresh your token.
> - You do not have permission to access this repository.
> - The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
> - If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.) 
> 

None of the reasons above are applicable. It seems that desktop is not running/recognizing ssh-agent. When I run git bash from the desktop app and perform `git pull` it works fine (because I have configured `ssh-agent` to run from my `.profile` and the key is associated with my account.)

**Comment by tierninho** [comment]
@jasonta Hmmm, try re-adding your SSH private key to the ssh-agent and store your passphrase in the keychain.

`$ ssh-add -K ~/.ssh/id_rsa`

Note: On most systems the default private keys (`~/.ssh/id_rsa and ~/.ssh/identity`) are automatically added to the SSH authentication agent. You shouldn't need to run `ssh-add path/to/key` unless you override the file name when you generate a key.

Hope this helps!

**Comment by jasonta** [comment]
@tierninho I forgot to mention, I'm using desktop on windows 10, so no keychain nor `-K` option. Not sure if there's an analogous method on windows.

**Comment by steveward** [comment]
@jasonta try running `github` from the command line to launch GitHub Desktop and then see if that gets things working for you.

**Comment by Moobien** [comment]
I am having the same problem myself. Windows 10, Github Desktop version 2.3.1.

[2020-02-03.desktop.production.log](https://github.com/desktop/desktop/files/4146174/2020-02-03.desktop.production.log)

Here is my log

**Comment by tierninho** [comment]
@Moobien It looks like your repository is empty. Can you confirm you see the `master` branch?

```
2020-02-03T03:43:03.620Z - warn: [ui] fetchCommit: returned an error 'moobien/Mw5Mercs-CAR@a74774250d17b94957cfde8004bf9821ed64908a'
Error: Git Repository is empty.
```

**Comment by Moobien** [comment]
it was, so I decided to start again locally. I set up my repo locally, had some content folders in there as well. when I hit "publish this branch to github" I get the authentication error still.  The first half of the log is before I deleted the repo and remade it.


[2020-02-05.desktop.production.log](https://github.com/desktop/desktop/files/4159949/2020-02-05.desktop.production.log)

**Comment by Moobien** [comment]
Further update, it seems fetching isn't an issue, it won't push

**Comment by tierninho** [comment]
Looks to be some errors in the logs as you states, both before and after you restarted the process.

```
>2020-02-05T14:06:57.170Z - warn: [ui] fetchRepository: 'Moobien/Mw5Mercs-CAR' returned a 404
2020-02-05T14:06:57.177Z - warn: [ui] fetchMentionables: 'repos/moobien/Mw5Mercs-CAR/mentionables/users' returned a 404
2020-02-05T14:06:57.180Z - warn: [ui] fetchAll: 'repos/moobien/Mw5Mercs-CAR/issues?state=open' returned a 404
2020-02-05T14:06:57.637Z - warn: [ui] fetchAll: 'repos/moobien/Mw5Mercs-CAR/pulls?state=open' returned a 404
2020-02-05T14:06:57.967Z - info: [ui] [fetchProtectedBranches] unable to list protected branches
Error: Not Found
```

```
2020-02-05T14:09:00.519Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
find: '/I': No such file or directory
find: '/N': No such file or directory
find: 'SoundModule.exe': No such file or directory
find: '/I': No such file or directory
find: '/N': No such file or directory
find: 'SoundModule.exe': No such file or directory
```

```
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/Moobien/MW5Mercs-PCP.git/'
```

- How are you setting up the repo locally, on the command line or within Desktop? I suggest the latter.
- Can you access other repos in Desktop?

I cloned your repo fine, but noticed "Cannot publish unborn HEAD" on `master`. Try adding a file and committing it. Let us know!

**Comment by Moobien** [comment]
https://github.com/MW5Modders/MW5Mercs-PCP - this is the latest repo I tried to make and work with, the latest Github Desktop will not push to it whatsoever, but "Unnecessary Sequel (3.3.6.1) 56edc3f" works quite happily with it.

**Comment by steveward** [comment]
@Moobien it looks like your machine may be infected with a virus, specifically a cryptocurrency miner called SoundModule.exe. Based on [this StackOverflow thread](https://stackoverflow.com/questions/58849884/cmd-exe-closes-immediately-unusual-line-in-autorun-registry-entry) it looks like this application can modify your the `AutorRun` registry entry, which will break GitHub Desktop.

I would recommend running something like MalwareBytes to scan your machine for the virus, and you can also manually remove the entries in these locations in the registry:

`Computer\HKEY_CURRENT_USER\Software\Microsoft\Command Processor`
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor`

I hope that helps!

**Comment by Moobien** [comment]
I ran Malwarebytes, it found 3 registry keys.

> Registry Value: 3
> Trojan.BitCoinMiner.COMSPECRST, HKU\S-1-5-21-625640670-3306585902-4209477630-1001\SOFTWARE\MICROSOFT\COMMAND PROCESSOR|AUTORUN, No Action By User, 4040, 756081, 1.0.18772, , ame, 
> Trojan.BitCoinMiner.COMSPECRST, HKU\S-1-5-21-625640670-3306585902-4209477630-1001\SOFTWARE\MICROSOFT\WINDOWS NT\CURRENTVERSION\WINLOGON|SHELL, No Action By User, 4040, -1, 0.0.0, , action, 
> Trojan.Agent, HKLM\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\RUN|EXPLORER, No Action By User, 489, 211621, 1.0.18772, , ame, 

so it dealt with those, but the soundmodule.exe file is nowhere to be found whatsoever so it seems the miner is gone but its registry keys were still there

**Comment by steveward** [comment]
@Moobien thanks for the update -- did that fix the issue you were encountering in GitHub Desktop?

**Comment by Moobien** [comment]
@steveward  it did. I really appreciate your patience and help.

**Comment by Roberto-B-23** [comment]
git@github.com : Permiso denegado (clave pública).
fatal: no se pudo leer desde el repositorio remoto.

Asegúrese de tener los derechos de acceso correctos
y el repositorio existe.
¿ ... que tengo que hacer ...?

**Comment by bopoh13** [comment]
@mayurigupta13 I faced the same problem on a clean Windows 10 (the registry didn't change) with a connected Microsoft account. Github Desktop was installed from the Store (user doesn't have access to applications in WindowsApps directory, menu "Show log in Explorer" not opened). Initially, the repository is cloned via HTTPS, but error occurs only when I push origin.
[Need to change the Repository settings](https://github.com/desktop/desktop/issues/7039#issuecomment-596187659) bypass Sign in.

**Comment by tierninho** [comment]
For anyone still having issues, please open a new issue as this one has too many individual threads. Thank you for the understanding.

**Comment by WesJones127** [comment]
I forgot to add the `-t rsa` or `-t ed25519` option to the `ssh-keygen` command, so my key wasn't the right type. Solution was to generate a new key and then everything started working again.
