### ISSUE TITLE
Github desktop not opening on Mac OS Catalina

### ISSUE THREAD

**Issue by montgomery28** [desktop/desktop#8970]
Github desktop is able to be opened but never responds, and its a new install never before on the computer.

**Comment by tierninho** [comment]
@montgomery28 Can you share more details and add some screenshots? Also, please attached the logs if you are able to see the Help menu. Thanks.

**Comment by montgomery28** [comment]
Well cant do any of that becuase screenshots wont help and I cant access the help menu. So what’s happening is that I open it it bounces for like 10 minutes than stops and if I click on it it says not responding

**Comment by tierninho** [comment]
Hard to tell what's going on at this point. I'd suggest trashing the application and re-downloading it.

**Comment by steveward** [comment]
@montgomery28 can you try deleting `~/Library/Application Support/GitHub Desktop/` and reinstalling to see if that helps with this issue?

**Comment by montgomery28** [comment]
worked :)

**Comment by VeronicaUken** [comment]
Worked for me as well thanks @steveward

**Comment by mifi** [comment]
For me I had forgotten to sign into github in the desktop app :|
