### ISSUE TITLE
Github desktop is simply not commiting

### ISSUE THREAD

**Issue by mhega** [desktop/desktop#8973]
![Desktop_unsuccessful_commit](https://user-images.githubusercontent.com/16949171/73046872-ad544980-3e41-11ea-8d48-4d9c6252d41a.PNG)
![Browser_successful_commits](https://user-images.githubusercontent.com/16949171/73046882-b513ee00-3e41-11ea-8564-b798bb2ba904.PNG)
![Button_greyed](https://user-images.githubusercontent.com/16949171/73046897-c1984680-3e41-11ea-8f9e-a328a6430943.PNG)

### Describe the bug

I attempt to commit work, and it indicates it went through, yet I go on to Github browser, and nothing is there.
Then I go back and commit through Github browser, commit works.
Back to Github desktop, it is not even realizing the successful commits.
It is "as if" desktop commits are going to a different account

I go to the commit which Github Desktop falsely indicates it made, and I right click, I see the "View on Github" button greyed out, whereas the previous successful commits have the same button active.

### Version & OS

Github 2.2.4
Windows 7 professional 64-bit

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by billygriffin** [comment]
Hi @mhega, thanks for the issue. After you commit in GitHub Desktop, are you pushing those commits to GitHub? They won’t appear on GitHub.com until you choose to push them. Similarly, commits made on GitHub.com won’t appear in your current branch on GitHub Desktop until you choose to pull them. If this isn’t the issue, we’d love more detailed reproduction steps and your logs (Help -> Show Logs in Finder/Explorer) to better understand the issue if you don’t mind.

**Comment by mhega** [comment]
That was it. Thanks for the help and the clarification Billy!

**Comment by tierninho** [comment]
Good news! Closing the issue.

**Comment by billygriffin** [comment]
Wonderful to hear, thank you @mhega!
