### ISSUE TITLE
Crashing when discarding multiple files

### ISSUE THREAD

**Issue by philecker** [desktop/desktop#8974]
I added .cache/ then commited that change. After, I went to discard 14 files within the directory, the application crashed twice, but on the 3rd attempt worked as expected.

```
GitHub Desktop 2.2.4
macOS 10.15.2
```

1. Created a Gatsby project from Gatsby blog starter template
2. Made some init commits
3. Added .cache/ to .gitignore
4. Commited .gitignore 
5. Discarded 14 files

Expected to discard files in the .cache/ directory.

Application crashed twice, before actually discarding files.

**Comment by billygriffin** [comment]
Thanks for the issue @philecker, and sorry you’re having issues with the app crashing. Would you mind sharing your log files (in Help -> Show Logs in Finder/Explorer) so we can see if there’s anything we notice that might explain what’s going on?

**Comment by philecker** [comment]
No worries, glad to help! Please let me know if I do anything else to assist. Thanks!

[2020-01-24.desktop.production.log](https://github.com/desktop/desktop/files/4109389/2020-01-24.desktop.production.log)

**Comment by philecker** [comment]
I didn't think of this before, but I am also using a fork (https://github.com/shiftkey/desktop) on my linux setup, however the error reported didn't occur on the fork.

**Comment by billygriffin** [comment]
Thanks @philecker - unfortunately I don't see anything in the logs that indicates the reason for the crash, and I'm unable to reproduce. 😞 Did the crash dialog come up with any additional info when it occurred, and if not, is this reliably reproduceable for you? Apologies for asking you to do so much legwork and I totally understand if you aren't able to. Just trying to figure out what might be causing it and coming up empty so far.

**Comment by steveward** [comment]
@philecker I was taking a look at this to see if I could reproduce the issue and I noticed that `.cache/` is ignored by default in the `.gitignore` for the Gatsby template. Were you using https://github.com/gatsbyjs/gatsby-starter-blog for your template?

**Comment by philecker** [comment]
@billygriffin Not a problem, the application didn't provide anything else.
@steveward Yes, I was using that template, but didn't see it in the .gitignore.

**Comment by steveward** [comment]
@philecker here's the [specific line](https://github.com/gatsbyjs/gatsby-starter-blog/blob/39a13ba6976759643f15992d5d93b51bfb0ebea0/.gitignore#L58) in the .gitignore. Let us know if you are able to reproduce this issue again.

**Comment by philecker** [comment]
Thanks @steveward I will let you know if I can. I'm confused why I don't see that in my .gitignore, however I think it might be due to the fact that file was already created when I decided to use Gatsby. Should I got ahead and close the ticket since you aren't able to reproduce the error?

**Comment by steveward** [comment]
@philecker since we weren't able to reproduce this directly this issue can be closed out. If you run into this again or we receive more reports of this crash we can look into this further.
