### ISSUE TITLE
commit title panel and profile picture

### ISSUE THREAD

**Issue by muhammedfurkan** [desktop/desktop#8975]
### Describe the bug

Github desktop commit title and user profile picture area section crashed

### Version & OS

Version 2.2.4 Windows 10 64 Bit Pro

### Screenshots

![image](https://user-images.githubusercontent.com/9547040/73082759-150aa300-3edb-11ea-93f0-009ea5ebc181.png)

### Logs

[2020-01-24.desktop.production.log](https://github.com/desktop/desktop/files/4109345/2020-01-24.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @muhammedfurkan. This looks similar to https://github.com/desktop/desktop/issues/5671 and https://github.com/desktop/desktop/issues/6041. 

Could you try resetting GitHub Desktop a fresh state to see if that helps?

1. Close GitHub Desktop 
2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
3. Restart GitHub Desktop (you will need to add your repositories back to the application)

Let me know if that helps.

**Comment by muhammedfurkan** [comment]
> Thanks for the report @muhammedfurkan. This looks similar to #5671 and #6041.
> 
> Could you try resetting GitHub Desktop a fresh state to see if that helps?
> 
> 1. Close GitHub Desktop
> 2. Remove all of the files in `%APPDATA%\GitHub Desktop\`
> 3. Restart GitHub Desktop (you will need to add your repositories back to the application)
> 
> Let me know if that helps.

I did what you said. works as before again. thank you.
