### ISSUE TITLE
write docs about preferences

### ISSUE THREAD

**Issue by Rexogamer** [desktop/desktop#8976]
currently we have no docs on adding preferences, so it’d be useful for contributors if we did

**Comment by billygriffin** [comment]
@Rexogamer Would you mind sharing more specifics about what you'd be looking for in docs like this and who you expect would consume them?

**Comment by Rexogamer** [comment]
Something like [this](https://github.com/desktop/desktop/blob/development/docs/technical/adding-tests.md) explaining how to add a new preference. This would be helpful for (in particular, new) contributors.

**Comment by billygriffin** [comment]
Generally we try to shy away from using preferences except in very specific and well understood circumstances, and I don’t know of a time an external contributor has ever added one (unlike tests). As such, I’m going to close this issue. Thanks for the idea.
