### ISSUE TITLE
Summary and description fields do not clear after commit

### ISSUE THREAD

**Issue by TheSkay** [desktop/desktop#8984]
### Describe the bug

The summary and description fields sometimes do not clear after a commit.

### Version & OS

**GitHub Desktop Version :** Version 2.2.4
**Operating System :** Microsoft Windows 10 Professionnel (10.0.17134 N/A version 17134)

### Screenshots

Add screenshots to help explain your problem, if applicable.
![GitHubDesktopProblem2](https://user-images.githubusercontent.com/5277237/73125218-a2fe9080-3fa4-11ea-948b-1cb5c49c63c3.PNG)
![GitHubDesktopProblem1](https://user-images.githubusercontent.com/5277237/73125219-a3972700-3fa4-11ea-8e6e-78a5ccd75758.PNG)

**Comment by tierninho** [comment]
@TheSkay Thanks for filing. We have had occasional reports of this. Please follow along at https://github.com/desktop/desktop/issues/4046
