### ISSUE TITLE
Changes window cannot be extended right

### ISSUE THREAD

**Issue by Craigjw** [desktop/desktop#8986]
The changes window has a fixed maximum width, which is just too small, this window displays changes with directory context and often the directory string length is too long to be displayed in this window without characters being removed, often this results in not being able to see important information relating to where the file is located.

To fix this, remove the maximum fixed width the window can be extended or make the maximum width dependent on the right hand side of the main window, instead of the left side.

![Untitled](https://user-images.githubusercontent.com/2862900/73138551-bae51b80-405b-11ea-84c4-9d2c03e5fdc9.png)

**Comment by tierninho** [comment]
@Craigjw Thanks for filing this. 

At this time we plan to keep the fixed window constraint as any increase can negatively affect the other windows in the app, namely the diff area. We know this is not ideal for everyone, but your feedback will be taken into consideration on the next iteration of this area.

Note, you can see the file path by hovering over the area. Additionally, if you can use the Dev Tools under the View menu to force a window size change if you choose to go that route. 

Thanks for using Desktop!

**Comment by Craigjw** [comment]
If constraints on the window size are used based on other window sizes then
this wouldn't be a problem.

Your team should be looking to solve problems, rather than looking to close
bug reports.
