### ISSUE TITLE
3000/5000 files to submit

### ISSUE THREAD

**Issue by Craigjw** [desktop/desktop#8987]
5000 files have been added from some imported packages, however only 3000 of these are to be committed.

I can't select 3000 files at one go, to do this, I'd have to select 3000 each individually, which would require at least 3000 mouse clicks to select each file.

Seriously?????

**Comment by tierninho** [comment]
@Craigjw Thanks for filing this issue.

So you are trying to select 3000 specific files of the 5000 seen in the changes list? You are correct, the files will have to be selected manually either as a chunk or individually. You can use the Shift or Cmd (Mac)/Ctrl (Windows) keys to select more than one file at a time. 

Curious if there was another method you were expecting? 

Closing this issue for now. Thanks for using Desktop!

**Comment by Craigjw** [comment]
I was hoping that this would be more user friendly by allowing the user to
select the multiple files, then select a single check box and it would
check/uncheck all file that are selected, so that I don't have to
check/uncheck 3000 files individually.

**Comment by tierninho** [comment]
So you can select as many files as needed and then use the `spacebar` to toggle the checkboxes. Hope this helps!

**Comment by Craigjw** [comment]
This helps tremendously, thank you.  Pressing a check box while a selection
has been made, should be implemented instead of relying on the space bar,
as this would be a much better user experience.

Plus, how would anyone else know to press the space bar for this feature,
it's not intuitive.

**Comment by Craigjw** [comment]
On another note Git for Unity is terrible, it basically completely locks up
Unity each time something changes, while it checks everything in the
project for changes, and in the process causes the cursor to rapidly
blink/switch between wait and a normal cursor.

If it's going to check for changes, it should do so in the background and
not prevent the user from using Unity.

Git for Unity hasn't been updated for nearly a year, it's a shame, as it
could be useful.

I've reported this, but have my doubts that anyone will bother to fix it.

**Comment by tierninho** [comment]
I don't think Git for Unity is supported anymore.

**Comment by Craigjw** [comment]
That would explain a lot, thank you for all your help.
