### ISSUE TITLE
Authentication Issue While Git clone

### ISSUE THREAD

**Issue by jyotijuhi** [desktop/desktop#8992]
### Describe the bug

I have recently got new machine and simply trying to git clone(by HTTPS), but getting authentication error in git bash with the same username and pwd which is working fine for github.com, i have also tried Personal Access Token but still the same issue shows up, 
*Note: I am doing these behind Proxy, and I have already done git config --global proxy url.
Please let me know where I am wrong.

### Version & OS
I am Using Windows 10, trying to git clone using git bash.
### Steps to reproduce the behavior

1. Go to github repository
2. Copy the https url 
3. open git bash where you  want to clone the repository.
4. Type git clone REPOSITORY_URL
5. A Github popup appears asking  for username pwd, when provided, says Authentication failed,
however the everything is correct

### Expected behavior

Repository clone should be started.

### Actual behavior

Giving Authentication Issue.

### Screenshots

Add screenshots to help explain your problem, if applicable.
![image](https://user-images.githubusercontent.com/44154575/73263076-beaca580-41f5-11ea-8a1d-571720c74c70.png)

**Comment by billygriffin** [comment]
Hi @jyotijuhi, thanks for the issue. Unfortunately we aren’t able to help with that, as this is the repository for the GitHub Desktop application. If you email support@github.com, our support team at GitHub should be able to help you work through this. Best of luck!
