### ISSUE TITLE
Add a "favorites" section to the repo list

### ISSUE THREAD

**Issue by checkdigits** [desktop/desktop#8993]
# New feature request - favorites menu entry on repo list

Currently GitHub desktop keeps a dynamically-created "recent" list of repos as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/2126394/73271405-2509d780-41a6-11ea-854c-dcb045814110.png)

Repos in this list may change over time depending on how many different repos the user works on.  If the user works on a sufficient number of repos, names on the "recent repos" list disappear fairly frequently.

It would be very useful to be able to 'pin' a small selection of favorite repos to this menu so that they are more easily available without having to search or scroll through the list.

I have well over a hundred repos and my repo list in Github Desktop can get quite long; it can be tricky to quickly find the right one, particularly if they have similar names.  😺

**Comment by steveward** [comment]
Thanks for contributing @checkdigits. We don't have any plans in the near future to add favorites to the repository list, for the reasons described here: https://github.com/desktop/desktop/issues/8183#issuecomment-542217438. I'm going to close this issue out, but thanks for letting us know you would like to see this feature added to GitHub Desktop.
