### ISSUE TITLE
Still no lfs option 

### ISSUE THREAD

**Issue by ZackBradshaw** [desktop/desktop#8996]
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.

### Proposed solution

How will it benefit Desktop and its users?

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by tierninho** [comment]
Please see the https://github.com/desktop/desktop/issues/6055 issue for tracking this feature. Thanks.

**Comment by tierninho** [comment]
Please note, Desktop does work with files using LFS, but just doesn't offer a way to add new files to LFS or configure them. Thanks for using Desktop!
