### ISSUE TITLE
Summary Box disappears and can´t commit any changes

### ISSUE THREAD

**Issue by glauco953** [desktop/desktop#8998]
The summary box now appears displaced, with my username and e-mail in its place, commit button always greyed out (snapshot below)
This happened in an install that was working fine for months, and stays the same even if I switch branches and repositories. Persists even reinstalling Git Desktop.

### Version & OS

Version 2.2.4
Windows 10

### Steps to reproduce the behavior

1. Something snapped one day, now it happens in every repo, will post the logs

### Screenshots

![image](https://user-images.githubusercontent.com/51463960/73307138-60cf8c00-41fc-11ea-938f-996b6082f702.png)

### Logs

[2020-01-27.desktop.production.log](https://github.com/desktop/desktop/files/4124704/2020-01-27.desktop.production.log)

**Comment by tierninho** [comment]
@glauco953 Thanks for filing this. We have had sporadic accounts of this, like https://github.com/desktop/desktop/issues/5671

In your logs, I spotted this error: 
```
2020-01-27T20:31:25.392Z - info: [main] Received possible protocol arguments: 3
2020-01-27T20:31:25.393Z - error: [main] Malformed launch arguments received: C:
```

I suggest performing a full reinstall by following these steps:

1. Close GitHub Desktop
2. Open File Explorer
3. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
4. Go to `AppData%` and delete the `GitHub Desktop` directory
5. Reinstall GitHub Desktop from http://desktop.github.com

Let us know if that helps.

**Comment by glauco953** [comment]
Thank you! It works now. If you need any of those old files, I kept them in a separate folder.

**Comment by tierninho** [comment]
Good to hear! Thanks for saving the old files, you are free to dispose of them if you like. 👍
