### ISSUE TITLE
Groups or Folders in cloned repository

### ISSUE THREAD

**Issue by daymonoid** [desktop/desktop#9001]
### Groups or Folders in cloned repository

it’s not very convenient when you have many customers and each project has the same name
I propose to make a grouping of projects (optional)

**Comment by tierninho** [comment]
@daymonoid thanks for suggestion! 

When the repos are pushed up to GitHub, they'll be grouped by the organization that they're in and therefore visually disambiguated that way. We know it's not ideal for repos you personally created, but we're going to stick with the way it is currently unless we get significantly more signal that a critical mass of users are experiencing this as a problem.

**Comment by Gabrielfcs** [comment]
I think it would be very good to be able to group the projects, even if locally, but to be able to better organize the projects
