### ISSUE TITLE
"Upstream already exists" error when creating a fork

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#9004]
### Describe the bug

We're seeing an error that the upstream remote already exists when creating a fork, even though the fork is created properly.

### Version & OS

GitHub Desktop 2.3

### Steps to reproduce the behavior

Fork creation flow when you've cloned a repo you don't have write access to.

### Expected behavior

Create the fork with no errors.

### Actual behavior

See error that the upstream remote already exists.

**Comment by sunny2leo** [comment]
Hello,

Hope you are doing Great!

I am presenting from news case organization as Digital Marketing Manager.

We are providing services to submit guest posting at our blog newscase.com with domain authority 57.
This blog is having a high domain authority. Our satisfied client is happy to have services with us.

In the above context, you are invited to place a guest post.

The Article we produce its 100% Unique, Copy escape Protected And free from plagiarism.

Please let me know if you are interested in this. We will discuss further charges.

Thank you so much and I hope to hear from you soon.

Thanks,
Newscase Team 
https://newscase.com
Contact us: editor@newscase.com
