### ISSUE TITLE
Program Shuts Down due to ignored file

### ISSUE THREAD

**Issue by iking7** [desktop/desktop#9008]
When adding .idea/misc.xml intellij file (already in .gitignore), the program shuts down entirely.

**Comment by steveward** [comment]
Thanks for the report @iking7. We had a similar case reported in https://github.com/desktop/desktop/issues/8974 where the crash occurred after ignoring a file and then discarding changes. Did this crash just occur when you selected `Ignore File` in the context menu?

It would also be helpful if you could share a log file from GitHub Desktop. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by tierninho** [comment]
In addition to the logs request, if you have reproduction steps or any screenshots, that would be helpful. Thank you!

**Comment by tierninho** [comment]
@iking7  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
