### ISSUE TITLE
App crashes everytime I start it

### ISSUE THREAD

**Issue by kaushalfeb** [desktop/desktop#9009]
### Describe the bug

Some error message showed while the app was running in background, so I closed it and restarted it.
When I open the Github Desktop app from start menu it shows an error screen and does not start the app whatsoever.

### Version & OS

As it does not start, I cannot mention the app version but I am pretty sure I updated to latest version yesterday or today itself.
I am using Windows 10 operating system. 

### Steps to reproduce the behavior

1. Go to 'Start'
2. Click on 'GithubDesktop app'
3. See error

### Expected behavior

App should show the list of repos and changes being made.

### Actual behavior

Error message:
A javascript error occured in the main process.

### Screenshots

![github error](https://user-images.githubusercontent.com/31488893/73452561-226ad600-4390-11ea-8ce0-38f4c9704bad.png)

**Comment by niik** [comment]
Hi @kaushalfeb, sorry to hear you're having problems. We shipped an updated version of Github Desktop yesterday and I would guess that something went wrong when the automatic upgrade happened on your machine. I would suggest downloading the installer again from [desktop.github.com](https://desktop.github.com) and reinstalling using that. You shouldn't loose any information by reinstalling.

Please let us know if that doesn't solve your problem.

**Comment by kaushalfeb** [comment]
Thankyou @niik I downloaded the latest version and now I can gladly tell you the issue has been resolved. 
Cheers you saved the day @niik !!
