### ISSUE TITLE
Unable to resize the panel displaying the files list

### ISSUE THREAD

**Issue by franckthomas** [desktop/desktop#9010]
### Describe the bug

Unable to fully resize the file list panel to display long filenames

### Version & OS

GitHub Desktop Version 2.3.1
MacOs 10.14.6

### Steps to reproduce the behavior

1. History tab selected
2. In the right panel drag the split horizontal bar to resize file list panel

### Expected behavior

Able to fully resize the width of the panel displaying the files list.

### Actual behavior

At some point way behind the width limit of the full right panel you are blocked

**Comment by tierninho** [comment]
@franckthomas Thanks for filing this.

At this time we plan to keep the fixed window constraint as any increase can negatively affect the other windows in the app, namely the diff area. We know this is not ideal for everyone, but your feedback will be taken into consideration on the next iteration of this area.

Note, you can see the file path by hovering over the area. Additionally, if you can use the Dev Tools under the View menu to force a window size change if you choose to go that route.

Thanks for using Desktop!

**Comment by qkienly** [comment]
May ask for could be taken assistance please don't know yet to be fixed or anyone else who might have been a little bit more about it is on the issues about this conference ?

**Comment by masoud-starrez** [comment]
I do believe that this an important feature, because I think the filenames are completely hidden for some file and it makes finding them in a big pr very hard.
