### ISSUE TITLE
A window border is missing

### ISSUE THREAD

**Issue by michelecos** [desktop/desktop#9011]
### Describe the feature or problem you’d like to solve

A missing window border makes it hard to find the title bar and other interface elements.

### Proposed solution

The addition of a window border of one pixel could allow the app to inherit the contrast color from windows preferences, thus allowing the user to choose how to hilight the perimeter of the app

**Comment by michelecos** [comment]
Github Desktop does not have any window border on windows. Standard applications have a title and a border which can be styled for visibility.

Electron applications, like Github Desktop and Visual Studio Code have no border and no title. For this reason, it is not possibile to style the window borders with system preferences. They are always dark.

As a consequence, it is hard to distinguish interface elements belonging to one app or the other, when two dark applcications overlap. The problem is even worse if the dark theme is selected.

The enclosed screenshot should give an idea of how the top left corners of the two applications overlap confusingly.

![Github desktop no border 1](https://user-images.githubusercontent.com/355198/73473542-3e20ad00-438d-11ea-9c1d-a3497ee2c753.PNG)

Dark theme

![Github desktop no border 2](https://user-images.githubusercontent.com/355198/73473627-5db7d580-438d-11ea-80bd-326574ae7f88.PNG)

**Comment by outofambit** [comment]
hi @michelecos sorry for the delay on our reply! we've been doing some discussing and investigating internally. while we'd like to remedy this with a small border, it's too much technical effort to solve this reliably, especially when considered against other work we are doing. unfortunately the electron API doesn't really offer us an easy way to do this and our own app's css is built in such a way that this isn't as straightforward as it might seem at first glance. apologies and thanks for reaching out.

**Comment by michelecos** [comment]
Thank you very much, Evelyn. I suspected that Electron was not making things easy. In fact, Visual Studio Code has announced the ability to style the window border only recently.

-- Michele Costabile (http://proxybar.net) 

    On Tuesday, February 18, 2020, 8:00:04 PM GMT+1, evelyn masso <notifications@github.com> wrote:  
 
 
hi @michelecos sorry for the delay on our reply! we've been doing some discussing and investigating internally. while we'd like to remedy this with a small border, it's too much technical effort to solve this reliably, especially when considered against other work we are doing. unfortunately the electron API doesn't really offer us an easy way to do this and our own app's css is built in such a way that this isn't as straightforward as it might seem at first glance. apologies and thanks for reaching out.

**Comment by abrudz** [comment]
Having this problem, I edited resources/app/renderer.css from
```css
html{box-sizing:border-box}
```
to
```css
html{box-sizing:border-box;border:1px solid var(--box-border-accent-color)}
```
and now, voilà:
![image](https://github.com/user-attachments/assets/f4b14e8e-e3d4-444e-be8c-78cdf4b4c3fb)
