### ISSUE TITLE
Support Automatic Dark Mode Switching on Windows

### ISSUE THREAD

**Issue by say25** [desktop/desktop#9015]
### Describe the feature or problem you’d like to solve

Support Automatic Dark Mode Switching on Windows

### Proposed solution

How will it benefit Desktop and its users? Feature parity on Windows and a similar experience for users who use both Mac and Windows.

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

1. In [Windows build 17666 a system a system dark mode setting](https://www.groovypost.com/news/windows-10-build-17666-includes-cloud-clipboard-dark-file-explorer/) was created. 
2. In Electron 7, the ability to retrieve the dark mode setting for Windows became available. `nativeTheme.shouldUseDarkColors` the replacement of `systemPreferences.isDarkMode()` gets Windows support in Electron 7.

**Comment by ncanate1** [comment]
![Screenshot_20200806-004304](https://user-images.githubusercontent.com/68528699/89501573-2cc7bb80-d789-11ea-9dc7-edecbfdc9caa.jpg)

**Comment by ncanate1** [comment]
#10220
