### ISSUE TITLE
problem whith my default branch 

### ISSUE THREAD

**Issue by PapiAlou** [desktop/desktop#9019]
i want to commit my repository when GitHub desktop say my current branch is unknown. How i can put my master branch ? 

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@PapiAlou Please tell us more about your situation by filling out the template added below your comment. Thank you!

**Comment by PapiAlou** [comment]
I can't commit my projects because i Git Desktop say i have problem with my
default branch.

Le ven. 31 janv. 2020 à 18:11, Tiernan L <notifications@github.com> a
écrit :

**Comment by CleWorks** [comment]
Im not a developer, I think I want to become one in  real estate, is this what they use?  I’ve never been on anything like this before. It’s cool, I’m a little nervous but it’s new & I like new

**Comment by tierninho** [comment]
@PapiAlou Sorry for the troubles, but we do not have enough info to help you yet. Please fill out the template above.
