### ISSUE TITLE
Time out error

### ISSUE THREAD

**Issue by YingJongTian** [desktop/desktop#9022]
### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment]
@YingJongTian Please fill out the above template and be sure to include your logs if possible.
