### ISSUE TITLE
Application initialization failed

### ISSUE THREAD

**Issue by jos3s** [desktop/desktop#9029]
### Describe the bug

The application just doesn't run

### Version & OS

Windows 10

### Steps to reproduce the behavior

1. Go to GitHub Desktop

### Expected behavior

I expected to open the application and access my repositories

### Actual behavior

The application simply does not run and displays the error described in the screenshot

### Screenshots

![image](https://user-images.githubusercontent.com/50359547/73596014-3122cb80-44fd-11ea-9af6-4f73d74379f2.png)

**Comment by steveward** [comment]
Thanks for the report @jos3s. Could you try performing a fresh installation of GitHub Desktop by following these steps?

1. Go to `%LocalAppData%` and delete the `GitHubDesktop` directory
2. Go to `%AppData%` and delete the `GitHub Desktop` directory
3. Reinstall GitHub Desktop from http://desktop.github.com

Let me know if that doesn't get things working.

Best,
Steve

**Comment by jos3s** [comment]
I did something like that, I installed the beta version over the top and apparently one over wrote the original and I had no more problems.  But I believe that the problem was caused by some incompatibility with the Nimi Places app
http://mynimi.net/Projects/Nimi-Places/Download/

**Comment by steveward** [comment]
@jos3s I'm glad to hear you were able to get GitHub Desktop working, and thanks for sharing those extra details.
