### ISSUE TITLE
Support Windows on ARM (WoS)

### ISSUE THREAD

**Issue by dennisameling** [desktop/desktop#9034]
### Describe the feature or problem you’d like to solve

Please add support for Windows on ARM (e.g. Surface Pro X). Currently, only a x64 build of GitHub Desktop is available, because of which GitHub Desktop doesn't boot at all on Windows on ARM. This platform can either emulate 32-bit apps (slower performance and more battery drain) or run native Windows on ARM apps.

### Proposed solution

Windows on ARM for Electron is supported [in Electron 6.0.8 and later](https://www.electronjs.org/docs/tutorial/windows-arm). Therefore, it should be feasible now to offer an ARM build for Windows.

- [x] Upgrade Electron to v7: https://github.com/desktop/desktop/pull/8967
- [x] Follow Electron's [instructions](https://www.electronjs.org/docs/tutorial/windows-arm) to create a Windows on ARM build. This way, we can find out what's potentially not working yet on the ARM platform.
- [ ] Other requirements can be found in #9691

This will allow Windows on ARM users to use GitHub Desktop.

### Additional context

https://github.com/desktop/desktop/issues/6874 won't really do the trick, as it will only trigger emulation on the ARM platform which causes performance loss and battery drain.

**Comment by dennisameling** [comment]
First attempt to install dependencies (Yarn) by cloning #8967 and using the [cross-compilation command prompt](https://www.electronjs.org/docs/tutorial/windows-arm#creating-a-cross-compilation-command-prompt) results in:

```
Error: Failed to find Electron v3.0.0 for win32-arm64 at https://github.com/electron/electron/releases/download/v3.0.0/chromedriver-v3.0.0-win32-arm64.zip
    at Request.<anonymous> (C:\Users\denni\repos\desktop\node_modules\nugget\index.js:169:61)
    at Request.emit (events.js:223:5)
    at Request.onRequestResponse (C:\Users\denni\repos\desktop\node_modules\request\request.js:1068:10)
    at ClientRequest.emit (events.js:223:5)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at TLSSocket.socketOnData (_http_client.js:456:22)
    at TLSSocket.emit (events.js:223:5)
```

GitHub desktop is using Spectron 5.0.0, which would need to be updated to 9.0.0 to support Electron 7. After I updated to Spectron 9.0.0, yarn dependencies installed correctly. That's a first step :)

**Comment by Rexogamer** [comment]
(on the topic of electron 7, #8967

**Comment by qkienly** [comment]
> ### Describe the feature or problem you’d like to solve
> Please add support for Windows on ARM (e.g. Surface Pro X). Currently, only a x64 build of GitHub Desktop is available, because of which GitHub Desktop doesn't boot at all on Windows on ARM. This platform can either emulate 32-bit apps (slower performance and more battery drain) or run native Windows on ARM apps.
> 
> ### Proposed solution
> Windows on ARM for Electron is supported [in Electron 6.0.8 and later](https://www.electronjs.org/docs/tutorial/windows-arm). Therefore, it should be feasible now to offer an ARM build for Windows.
> 
> * [ ]  Upgrade Electron to v7: #8967
> * [ ]  Follow Electron's [instructions](https://www.electronjs.org/docs/tutorial/windows-arm) to create a Windows on ARM build. This way, we can find out what's potentially not working yet on the ARM platform.
> 
> This will allow Windows on ARM users to use GitHub Desktop.
> 
> ### Additional context
> #6874 won't really do the trick, as it will only trigger emulation on the ARM platform which causes performance loss and battery drain.

**Comment by dennisameling** [comment]
Just created a test build. Build succeeded without errors and the app starts. I can even login to GitHub. After logging in, I'm getting errors.



- Checkout https://github.com/dennisameling/desktop/tree/windows-arm-test
- Open the "cross compilation command prompt" as described in Electron's [Windows ARM guide](https://www.electronjs.org/docs/tutorial/windows-arm#creating-a-cross-compilation-command-prompt).
- Run `npm_config_arch=arm64`
- Run `set TARGET_ARCH=arm64`
- Run `yarn build:dev`
- Done 😄 

I guess it's best to wait until #8967 is done and merged, as I don't know whether the errors are related to the Electron 7 upgrade or this ARM-build. But the first steps are taken :)

**Comment by Rexogamer** [comment]
I’d say once that PR is merged then open a draft PR with any changes you needed to do to add ARM support :D

**Comment by outofambit** [comment]
Hi @dennisameling, thanks for opening this issue. I'd love to hear more about how supporting Windows on ARM would help you. Is this because your laptop/tablet is a Surface Pro X? Or is it for something educational? Something else?

Thank you!

____

For context, this is a decent bit of work and we don't add support for additional platforms lightly. We would also have to add support for Windows on ARM to [dugite](github.com/desktop/dugite) and [dugite-native](github.com/desktop/dugite-native), but it looks like [Windows for Git](https://github.com/git-for-windows/git/) (which they use for Windows) does not yet support ARM64 (see https://github.com/git-for-windows/git/issues/2346).

GitHub Desktop cannot support Windows on ARM until Git for Windows does, but even then we have to decide if the added maintenance load is sustainable for the core team. The more we can understand about the benefits and impacts of Windows on ARM support, the easier that decision is for the maintainers to make.

**Comment by dennisameling** [comment]
@outofambit Indeed I'm using a Surface Pro X, on which GitHub Desktop doesn't boot at all.

I saw that a Microsoft engineer is providing help to support ARM64 for Git for Windows (https://github.com/git-for-windows/git/issues/2346), so if we assume there's gonna be a ARM64 build of Git for Windows at some point, do you have a rough idea how much work it would be to add support to dugite and dugite-native?

Another option which might be feasible, is to use the 32-bit Windows version of Dugite native, as Windows on ARM is capable of running Windows 32-bit programs trough emulation (although with lower performance/higher battery usage). Then GitHub Desktop itself would be ARM64, but the dependencies/binaries would run 32-bit versions in the background.

I'm happy to help where possible!

**Comment by dennisameling** [comment]
By the way: just tested 32-bit test build of GitHub desktop (https://github.com/desktop/desktop/issues/6874#issuecomment-581551727) and works without any issues!

**Comment by dennisameling** [comment]
@outofambit I'm trying to create a "hybrid build" now, where GitHub Desktop is compiled for arm64 and dependencies like Git use the 32-bit version. However, I'm trying to create this build on a x64 Windows machine, and Dugite [always takes](https://github.com/desktop/dugite/blob/master/script/config.js#L17) the host OS' architecture while downloading Git dependencies:
```
const key = `${process.platform}-${os.arch()}
```
This results in a download of `win32-x64` (dugite-native-v2.23.1-c34be54-windows-x64.tar.gz) instead of `win32-ia32` (dugite-native-v2.23.1-c34be54-windows-x86.tar.gz).

- Is there a way to force Dugite to download the `x86` build of `dugite-native` on a `x64` machine?
- If not, I'll try and see if I can set up a 32-bit Windows 10 VM to see how far I can get :)

**Comment by anaisbetts** [comment]
I would like to subscribe to this newsletter! Not having a version of GitHub Desktop for my Surface Pro X is like swimming without water!

**Comment by dennisameling** [comment]
MAJOR MILESTONE! 🎉 😄 

I was able to create a test build for ARM64 that uses 32-bit dependencies (like Git) in the background. This way, GitHub Desktop itself is compiled natively for Windows on ARM, while dependencies like Git benefit from Windows' built-in emulation for 32-bit apps.

You can download my test build here: https://github.com/dennisameling/desktop/releases/tag/windows-arm-test 
@anaisbetts can you please check if it works for you too?

Steps to create the build:
- Set up a 32-bit Windows 10 VM
- Follow the steps as described in https://github.com/desktop/desktop/issues/9034#issuecomment-581332128
- Done! 😄

**Comment by dennisameling** [comment]
If https://github.com/desktop/dugite/pull/392 is merged, things will become very easy:

- Open a Command Prompt in Windows and go to the GitHub desktop repository
- Run `set npm_config_arch=arm64`
- Run `set TARGET_ARCH=arm64`
- Run `yarn` (setting the `npm_config_arch` before `yarn` will ensure you get the correct libraries for arm64)
- Run `yarn build:dev` or `yarn build:prod`

**Comment by dennisameling** [comment]
Now that https://github.com/desktop/dugite/pull/392 is merged, we can go ahead and build for ARM64. You can track my progress in #9691 👍

**Comment by dennisameling** [comment]
Windows ARM64 build working (#9691), but I need some help with the GitHub Desktop installer. I can create the installer without issues (see #9691 for all details), but it throws an error when trying to install on Windows ARM64.

Especially this part of the [debug log](https://github.com/desktop/desktop/files/4569277/SquirrelSetup.log) seems interesting:

```
2020-05-03 00:11:27> IEnableLogger: Failed to invoke post-install: System.NotSupportedException: De opgegeven methode wordt niet ondersteund.
   bij Mono.Cecil.PE.ImageReader.ReadArchitecture()
   bij Mono.Cecil.PE.ImageReader.ReadImage()
   bij Mono.Cecil.PE.ImageReader.ReadImageFrom(Stream stream)
   bij Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
   bij Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   bij Squirrel.SquirrelAwareExecutableDetector.GetAssemblySquirrelAwareVersion(String executable)
   bij Squirrel.SquirrelAwareExecutableDetector.<>c__DisplayClass1_0.<GetPESquirrelAwareVersion>b__0()
   bij Squirrel.Utility.Retry[T](Func`1 block, Int32 retries)
   bij Squirrel.SquirrelAwareExecutableDetector.GetPESquirrelAwareVersion(String executable)
   bij Squirrel.SquirrelAwareExecutableDetector.<>c__DisplayClass0_0.<GetAllSquirrelAwareApps>b__2(String x)
   bij System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   bij System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bij System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bij Squirrel.SquirrelAwareExecutableDetector.GetAllSquirrelAwareApps(String directory, Int32 minimumVersion)
   bij Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__10.MoveNext()
```

I have the feeling that [Cecil](https://github.com/jbevain/cecil) can't work with Windows arm64 yet (erroring at `ReadArchitecture()`). But that's just an assumption that needs more investigation. 

@anaisbetts, given your extensive knowledge of [Squirrel](https://github.com/Squirrel/Squirrel.Windows) (I believe you're the creator, right?), would you have a rough idea whether my assumption could be correct? And would you mind pointing me in the right direction of where to look next in order to troubleshoot the installer on Windows ARM64? Thanks! 😊

**Comment by dennisameling** [comment]
Alright, the last blocker for this one is Squirrel, the installer. Squirrel needs to update one of their dependencies, see https://github.com/Squirrel/Squirrel.Windows/issues/1616. Once that PR is merged, we are pretty much ready to go ahead and create an installer that installs GitHub Desktop for Windows ARM64 🎉 https://github.com/Squirrel/Squirrel.Windows/issues/1616

**Comment by midNight-jam** [comment]
amazing looking forward for it, just got my Pro X & the first thing I wanted to have was github desktop. Following this thread now.

**Comment by dennisameling** [comment]
@midNight-jam I created an ARM64 beta build that you can use for the time being: https://github.com/dennisameling/desktop/releases/tag/2.4.4-beta2. Please note that this build doesn't include an installer, but you should be able to use GitHub Desktop like you're used to 😃

**Comment by Ivan8R** [comment]
@dennisameling Thank you.  I wait it.

**Comment by AndrewCliftonWells** [comment]
Any progress on this?

**Comment by dennisameling** [comment]
@AndrewCliftonWells currently waiting for some dependency updates, please follow https://github.com/desktop/desktop/pull/9691#issuecomment-683456627 for updates

**Comment by dennisameling** [comment]
Just completed the work on the Windows on ARM build - it works now (including the installer) and all tests are passing 🎉 more details here: https://github.com/desktop/desktop/pull/9691#issuecomment-782854855

Example release for anyone who wants to try: https://github.com/dennisameling/desktop/releases/tag/2.6.4-beta99

It uses x86 Git for Windows in the background, but [we're working on](https://github.com/desktop/dugite-native/pull/347) a native arm64 version of Git for Windows as well 🚀

**Comment by milicodes** [comment]
thank you so much!! is working perfectly in my Samsung Book S !! 🎉 (ARM-based 64bit)

**Comment by sergiou87** [comment]
@milicodes you can just download the latest official beta from https://github.com/desktop/desktop#beta-channel and always be up to date 😄

**Comment by rafaeltoth** [comment]
Just want to add: The Windows Beta ARM64  works fine in Apple Silicon running Windows 11 ARM via Parallels 17 (MBP14)
