### ISSUE TITLE
Create pull request no longer working?

### ISSUE THREAD

**Issue by adamreisnz** [desktop/desktop#9036]
### Describe the bug

The action `Create pull request`, from menu or via shortcut, no longer seems to be working.

### Version & OS

GHD 2.3.2-beta1
OS X 10.14.6 
Browser Brave

### Steps to reproduce the behavior

1. Click `Create pull request`

### Expected behavior

For the github pull request page to be opened

### Actual behavior

Browser receives focus, but no new tab opens.

### Logs

I couldn't see anything relevant in the logs

### Additional context

Used to work fine with either Chrome or Brave

**Comment by adamreisnz** [comment]
Restarted both GHD and browser and it started working again. Might be worth investigating under what circumstances it fails though.

**Comment by steveward** [comment]
@adamreisnz thanks for the report! I'm going to close this issue out to help keep our issue list maintainable, but let us know if you run into this again.
