### ISSUE TITLE
Click on the SHA while viewing commit to copy it, like legacy Desktop

### ISSUE THREAD

**Issue by fatcerberus** [desktop/desktop#9037]
### Describe the feature or problem you’d like to solve

In the old Classic Desktop, it was possible to simply click the (truncated) SHA while viewing a commit to copy the full SHA to the clipboard.  It would be nice to have this feature again.  Right now you can right-click the commit in the left pane to get the Copy SHA option, but this requires an extra click.

### Proposed solution

Since one often needs to review the contents of commits to figure out which one to use in the first place, this would save an extra click (and often reduce mouse travel) in most cases.

### Additional context

![image](https://user-images.githubusercontent.com/4097841/73676438-5d1b8980-4682-11ea-8f58-5a9e4db83854.png)

**Comment by tierninho** [comment]
@fatcerberus Thanks for the suggestion. Here is some context on the decision that led to the current state:

https://github.com/desktop/desktop/pull/3770#issuecomment-357077106
and
https://github.com/desktop/desktop/pull/3770#issuecomment-370540302

I will leave this open as those decisions were made two years ago and it may be worth revisiting.

cc @billygriffin for thoughts

**Comment by fatcerberus** [comment]
> Initially clicking on the sha was supposed to copy the full sha to the clipboard but we had some concerns that we didn't have the proper components in place to notify users of what was going to happen (or had happened) when clicking. We also had a dedicated view on GitHub link that we intentionally removed in favor of the context menu.

The discoverability angle make some sense, though IMO I suspect that's less of a concern now that the right-click menu exists.  I don't think there's any problem with *keeping* the context menu in place as-is and adding these links for convenience.  Plus it's been my experience that new users tend to hover around with the mouse cursor while in a new environment anyway, so as long as there's a tooltip saying clicking here will copy the SHA to the clipboard, that seems plenty fine for discoverability too.

**Comment by a2937** [comment]
This seems like it could be a fun feature to work on and could be useful if we could get a drop down with "Copy Sha to clipboard", "Open on Github.com" , and other stuff like that.

**Comment by steveward** [comment]
We now have a copy option next to the SHA thanks to https://github.com/desktop/desktop/pull/17548 so this can be closed. ✨ 

![Image](https://github.com/desktop/desktop/assets/721500/d50440fe-c50f-4007-9d8d-d1a1d1e65156)
