### ISSUE TITLE
After the update a few days ago Github became very laggy and slow. 

### ISSUE THREAD

**Issue by lou55** [desktop/desktop#9042]
### Describe the bug

GitHub asked me to restart for the new update and after restarting on the new version it became extremely slow, you can come on teamviewer if you want and check it yourself. I have to click n wait to see changes, although it's very small changes.

### Version & OS

Version 2.3.1
Windows 10 Pro
I7 3770k overclocked to 4.7 Ghz
16 GB RAM DDR3 3200
Github is running on Samsung SSD 860 EVO

### Steps to reproduce the behavior

Nothing, overall it's very slow. Even clicking the top menus takes a fraction of time while in the past it used to be instant.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

[2020-01-26.desktop.production.log](https://github.com/desktop/desktop/files/4152991/2020-01-26.desktop.production.log)
[2020-01-29.desktop.production.log](https://github.com/desktop/desktop/files/4152992/2020-01-29.desktop.production.log)
[2020-01-30.desktop.production.log](https://github.com/desktop/desktop/files/4152993/2020-01-30.desktop.production.log)
[2020-02-01.desktop.production.log](https://github.com/desktop/desktop/files/4152994/2020-02-01.desktop.production.log)
[2020-02-02.desktop.production.log](https://github.com/desktop/desktop/files/4152995/2020-02-02.desktop.production.log)
[2020-02-03.desktop.production.log](https://github.com/desktop/desktop/files/4152996/2020-02-03.desktop.production.log)
[2020-02-04.desktop.production.log](https://github.com/desktop/desktop/files/4152997/2020-02-04.desktop.production.log)

**Comment by steveward** [comment]
Thanks for the report @lou55. I do see some Git operations taking longer than average in the log files. The common culprit for this type of issue is normally antivirus/security software -- are you running any software on your machine that could be interfering with GitHub Desktop?

**Comment by niik** [comment]
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.

**Comment by engineereddeveloper03** [comment]
![GithubDesktopTaskManager](https://user-images.githubusercontent.com/19498234/74473982-73cb9880-4e59-11ea-8465-01cc425be161.png)

I'm getting the same issue with the update as well.  I've posted a picture of my task manager and it seems to be spawning multiple "Git for Windows" processes.  It takes maybe 5-10 minutes of waiting before they all complete.  This happens when I click on a changed file and wait for the diff to pop up on the right.  Clicking through the different changed files spawns more and more processes brings my PC to it's knees.

Let me know if you need any more information to help narrow down this issue.

**Comment by HolyFot** [comment]
Actually I'm getting this issue with a recent update in may. It's extremely slow.

**Comment by steveward** [comment]
@HolyFot are you running any antivirus software on your machine? If so, please share the specific software you are running. This was also reported in https://github.com/desktop/desktop/issues/9801.

**Comment by lou55** [comment]
@steveward Actually the issue was from Malware Bytes, and it suddenly got fixed by itself. When I used to exit the Malware bytes it used to be back fast, then suddenly after 2-3 weeks it got fixed. Thanks!
