### ISSUE TITLE
GitHub Desktop for Mac breaks a VB6 project consistently. 

### ISSUE THREAD

**Issue by joexn** [desktop/desktop#9043]
### Describe the bug

When cloning a repo containing VB6 code through the Mac Desktop Client, the client adds on carriage returns onto some of the code and breaks the project completely. 

When cloning a repo containing VB6 code through the Windows Desktop Client, the project loads and runs fine.

### Version & OS

macOS Catalina (Running GitHub Desktop 2.3.1)
Windows 10 (Running GitHub Desktop 2.3.1)

### Steps to reproduce the behavior

We have a propriety piece of software in a private repo which is impossible to clone though the Mac version without it breaking the project. As soon as we clone the repo through the Windows version it works as expected. 

### Expected behavior

The project should open and run in VB6, but when cloned via GitHub Desktop for Mac, it fails.

### Screenshots

No screenshots can really be provided during this as this doesn't throw an error on the client itself. 

### Additional context

Me and another developer last year used the terminal code "git config --global core.autocrlf false" and it appeared to fix the issue – it no longer works. 

On another note, I'm active every week day from 9am-5pm and I'm happy to run some tests if anyone has any suggestions.

**Comment by steveward** [comment]
@joexn thanks for the report. My recommendation would be to create a `.gitattributes` file to normalize the line endings -- this will ensure consistent behavior across various environments and `core.autocrlf` settings. See this help article for how to do that:

https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings#per-repository-settings

The `* text = auto` configuration is what I would recommend using. Let me know if you have any questions about getting this configured.

**Comment by joexn** [comment]
There is already a `.gitattributes` file which contains `* text=auto` and my coworker and I are still experiencing this issue.

**Comment by steveward** [comment]
@joexn did you [follow the steps to normalize](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings#refreshing-a-repository-after-changing-line-endings) your line-endings after adding the `*text = auto` value? The line-endings changes will still appear until this is done.

**Comment by joexn** [comment]
The .gitattributes file was added in the first commit then the project was started. Running through that guide now does nothing and terminal reports:

```
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by steveward** [comment]
@joexn just to clarify -- when you clone the repository on macOS are you seeing the line-ending changes appear in the `Changes` tab?

**Comment by joexn** [comment]
No, when I clone the repo on macOS and run it using VB6 using Parallels, nothing changes with the code visibly, but the project just breaks. 

I’m using Parallels on a MacBook Pro and when I clone the repo using the Mac GitHub Client and open it in VB6 on Parallels it breaks the project completely.  

However when using GitHub Desktop on Windows (Parallels), I can open it on VB6 successfully. 

>

**Comment by steveward** [comment]
@joexn can you check if the files CRLF or LF on the macOS machine? A text editor like VSCode or Atom will show this in the bottom right. My guess is the line endings are being checked out as LF on your macOS machine, which is breaking your VB6 application since it only wants CRLF.
