### ISSUE TITLE
Lost changes when Pulling on a branch that "apparently" isn't in origin

### ISSUE THREAD

**Issue by nunoperalta** [desktop/desktop#9046]
### Describe the bug

Pulling from origin on a branch that locally is still in the state of "non-existent", using Rebase, causes changes to be lost.

### Version & OS

2.3.1
Windows 10

### Steps to reproduce the behavior

Make sure you have Pull with Rebase and Auto-stash configs enabled.

1. Create branch in Azure DevOps
2. Switch to that branch using GitHub Desktop
3. Develop, commit and push
4. In Azure DevOps, create a Pull Request which automatically deletes the branch once it's completed

5. Let GitHub Desktop be in the same branch. Eventually the "Fetch origin" button becomes "Publish branch"
6. Continue working on that branch, making changes to files.

7. Re-create branch in Azure DevOps when you're ready to commit.
8. In GitHub Desktop, while the button still says "Publish branch", go to the menu "Repository" and press "Pull".

9. What happened to me is that all my staged contents disappeared.
`git stash apply` did not have those contents (just had older contents that were already committed before)
`git fsck --lost-found` did not put my contents in the "lost-found" folder (I checked all the files there)
`git reflog` and `git reset` did not help me either

**At this point, I was completely frustrated, thinking I would have to re-do all my implementations since the last commit...**

Now, fortunately (and I'm putting this information to help any others who end up here in the same situation), I found eventually that the changes were stashed into a different place than the normal/common Stash place (and hence "git stash apply" did not help...).

**Solution:**
1. Go to ".git\rebase-apply\" and open the file "autostash"
2. Copy the hash that is in it
3. Run `git stash apply <hash>`

### Expected behavior

Whatever GitHub Desktop was trying to do, my changes should not have been "lost" like that.
If I had never found about the "rebase-apply", I would have wasted all the work I had done so far.

Would be nice if GitHub Desktop told me that I had stashed changes from an interrupted rebase, similarly to how it says when I switch to a branch that currently has stashed changes.

### Related behavior

**Note that I've seen similar behavior when I switch to a branch and move my changes, and the moved changes will conflict with some file(s) in the branch I'm switching to.**
The changes apparently disappeared, in both the new branch and the previous branch.
GitHub Desktop also doesn't tell me that I have stashed changes.
However, I can "fix" this by doing a manual `git stash apply`, which will put my files back, and show me the conflicted files too.

**Comment by dogmasega** [comment]
<?3

**Comment by outofambit** [comment]
hi @nunoperalta apologies for the delay here and i'm sorry you experienced this. did you see any error messages between steps 8 and 9? or did you press 'Pull' and then your changes just disappeared?

> told me that I had stashed changes from an interrupted rebase

was there a rebase process that got interrupted during the 'pull'? and i this would mean you had `pull.rebase` set to `true` in your git config, right?

Thanks!

**Comment by nunoperalta** [comment]
Hello @outofambit - thank you very much for your reply.

I did indeed get a big alert with an error (it was unformatted and hard to read, but I believe you guys have done a release that should make error messages more formatted),
between step 8 and 9, and therefore the Rebase was interrupted.
Unfortunately, I cannot remember what the error was saying, at this point.
I did not take a screenshot at the time, since I assumed I could just move on and "ignore" it :)

I have indeed Pull with Rebase and Auto-stash enabled (I say that in my original message above).

Thank you once more.

**Comment by niik** [comment]
Hi @nunoperalta. Without log files or screenshots there's not much for us to do here. If you experience it again we'd love it if you could capture as much information about the error as possible. When you click `Pull` in GitHub Desktop all we do is run `git pull` so I suspect the same problem could have happened had you been using the command line interface.

I'm going to close this as we don't have a clear path forward but should you (and let's hope you never do) encounter this again please let us know and we can reopen.

**Comment by nunoperalta** [comment]
@niik - haven't experienced this anymore.
I believe Desktop has become a lot more stable since, anyway.
Very well done job with this application!
