### ISSUE TITLE
Writes to .gitconfig w/o asking

### ISSUE THREAD

**Issue by nrlquaker** [desktop/desktop#9056]
### Describe the feature or problem you’d like to solve

Opening Github Desktop triggers update to `.gitconfig`.
This lines are added:
```
[filter "lfs"]
    required = true
    clean = git-lfs clean -- %f
    smudge = git-lfs smudge -- %f
    process = git-lfs filter-process
```

Its initial config for git LFS.

### Proposed solution

Ask user permission to edit .gitconfig. Or don't touch it at all.
Please let user decide what his `.gitconfig` should be like.

### Additional context

Version: 2.3.1 macOS.

**Comment by steveward** [comment]
@nrlquaker thanks for the feedback. GitHub Desktop's goal is to make it as easy as possible to work with GitHub and Git, and working with large files is one of the more painful points of Git. We've previously [shipped a feature](https://github.com/desktop/desktop/pull/6013) that prevents users from committing large files to GitHub, which was a common snag for many new users. By having Git LFS ready to go after installation it allows users to quickly get set up with versioning their large files. 

I'm going to close this issue out as this isn't something that we will change in the future. Are there any specific concerns you have with the Git LFS configuration?

**Comment by nrlquaker** [comment]
> Are there any specific concerns you have with the Git LFS configuration?
Well, I got `.gitconfig` under git as many other dotffiles. Any external modifications are easily seen and make my `git status` not clean.

Anyway, I got your point.
