### ISSUE TITLE
Use commit.template setting, and pre-populate the commit message

### ISSUE THREAD

**Issue by HEBOS** [desktop/desktop#9057]
### Pre-populate commit message using commit.template setting

To comply with the company policy, we need to use a template for our code commits.
That is easy achievable using command-line git.
Firstly we need to create a file in our user folder, and populate it with our template".
Given the file name is **.gitmessage**, we configure it in git using:

`git config --global commit.template ~/.gitmessage`

To use it we just run:
`git add .`
`git commit`

Next Vim editor will pop-up, and after we close it, we will get what is expected. This proves that command-line git works correctly. 
However, we cannot do the same using Git Desktop.

### Proposed solution
Please pre-populate commit message with the content of the file configured in the commit.template setting.

How will it benefit Desktop and its users?
It will help the users to comply to the company commit policy.

**Comment by steveward** [comment]
Thanks for contributing @HEBOS. Support for commit templates was brought up in https://github.com/desktop/desktop/issues/8698 -- I'm going to add your feedback there and close this issue out.
