### ISSUE TITLE
Add toggle to turn on/off subtractions of file.

### ISSUE THREAD

**Issue by michael-coffey** [desktop/desktop#9059]
It would be nice to be able to view a file without the subtractions on so you can view the file in its current state.  It would help in reading the changes of the file.
I am suggesting some sort of toggle to do this.  Thanks.

**Comment by steveward** [comment]
@michael-coffey thanks for the feedback. Are you wanting to view the entire file in the `History` view or the `Changes` view? There was a previous request in #5367 for the ability to view a snapshot of the file in the History view.

**Comment by tierninho** [comment]
@michael-coffey  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.
